### ISSUE TITLE
fish-shell PATH format breaks executable()

### ISSUE THREAD

**Issue by vaibhav-y** [neovim/neovim#10005]
- `nvim --version`:
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-mHBPg8/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-mHBPg8/neovim-0.3.4/build/config -I/build/neovim-mHBPg8/neovim-0.3.4/src -I/usr/include -I/build/neovim-mHBPg8/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-mHBPg8/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```                                                                                                                                                  
- Vim (version: 0.3.4) behaves differently?
Running `executable('git')` returns 0, when it should return 1 on the fish shell. This is probably because we don't parse the `$PATH` variable correctly in the fish shell.
- Operating system/version: 
```fish
$ uname -a                                                                                                                                                                11:41:05
Linux setsuko 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Terminal name/version:
```fish
$ echo $SHELL
/usr/bin/fish
```
- `$TERM`:
```fish
$ echo $TERM
xterm-256color
```

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

Each of the 
1. Start an interactive fish-shell session
```fish
$ status --is-interactive; and echo yes; or echo no                                                                                                                       
yes
```
2. Check contents of `$PATH` variable, this is a space separated list
```fish
$ echo $PATH                                                                                                                                                              
/home/tgb/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin
```
3. Check that fish knows how to find the `git` executable
```fish
$ which git && git --version
/usr/bin/git
git version 2.20.1
```
4. Run `nvim -u NORC` and `:echo executable('git')` this returns `0`
5. Run `begin; set -lx PATH /usr/bin:$PATH; nvim -u NORC; end`, and run command `echo executable('git')`. This returns `1`.

### Actual behaviour
`nvim` can't find executables on fish like `$PATH` variables

### Expected behaviour
It should be able to locate executables irrespective of the environment.

**Comment by bfredl** [comment]
`$PATH` is a standard variable that any process can use, its meaning doesn't depend on the shell. POSIX specifies that `:` separator should be used. If `fish` sets it to an incorrect value for subprocesses, it is a `fish` bug (or config issue), not a nvim `bug`.

**Comment by justinmk** [comment]
We do have some fish workarounds already. Adding a shell-specific path-separator could probably be added as yet another `shell*` option (cf. `:help shell`, `:help shellcmdflag`, ...). But as @bfredl  said if fish does that, life won't be easy...

**Comment by bfredl** [comment]
The standard interpretation of `$PATH` is coded directly into the C library, see `man 3 execve`, it is not expected to be "shell behavior" dependent like `system()` (in C library or vimL). It will just break every C program that uses executables regardless if that program purposely uses shell functionality or not.

**Comment by mqudsi** [comment]
fish doesn't mess with the `$PATH` representation, it only translates it. Within fish, the external `foo:bar` is converted to an array (`foo bar`). Changing that array exports the correct `:`-delimited value:

```fish
mqudsi@fish> set -x PATH /foo /bar /bin
mqudsi@fish> sh -c 'echo $PATH'
/foo:/bar:/bin
```

You should not modify `PATH` directly in fish. Use `fish_user_paths` to whatever you want, fish appends that `$PATH` correctly.

e.g.

```fish
mqudsi@bash$ export PATH=/bin/:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
mqudsi@bash$ fish
mqudsi@fish> echo $PATH
/bin/ /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin
mqudsi@fish> sh -c 'echo $PATH'
/bin/:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
mqudsi@fish> set -U fish_user_paths /foo /bar
mqudsi@fish> echo $PATH
/foo /bar /bin/ /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin
mqudsi@fish> sh -c 'echo $PATH'
/foo:/bar:/bin/:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
```

**Comment by vaibhav-y** [comment]
> `set -U fish_user_paths /foo /bar`

This worked, I wasn't aware of this. Thank you for this!
