### ISSUE TITLE
remote to VMs

### ISSUE THREAD

**Issue by xarthurx** [neovim/neovim#10007]
VScode just released an extension pack for remote work in WSL/VMs.
https://code.visualstudio.com/docs/remote/remote-overview

Is it possible to make this happens in neovim under the current framework?

**Comment by justinmk** [comment]
What are you asking specifically? Please reference parts of the VScode spec and then we can say whether those things are possible. It's already possible to connect to a remote Nvim instance via TCP or pipes.
