### ISSUE TITLE
Different behavior between Vim and Neovim for the same autocmd event

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#10008]
- `nvim --version`: 0.4.0
- Vim (version: ) 7.4, behaves differently
- Operating system/version: Linux CentOS 7.4
- Terminal name/version: Mintty terminal
- `$TERM`: xterm-256color

### Steps to reproduce 

1. Use this minimal config `minimal.vim` with the following content:

```
 augroup non_utf8_file
     autocmd!
     autocmd BufRead * if &fileencoding != 'utf-8' | echomsg 'file not in utf-8 format!' | endif
 augroup END
```
2. Open nvim with the above setting to a file which is not in utf-8 format :

```
nvim -u minimal.vim cp936.txt
```

[cp936.txt](https://github.com/neovim/neovim/files/3177425/cp936.txt)

### Actual behaviour

The message is not shown in Neovim. But if I use Vim, the message is shown correctly.

### Expected behaviour

The message should show in Neovim.

# Other note

I have also tried to replace `BufRead` with `BufEnter` and `BufWinEnter` and these two events work. I think `BufRead` should also work from its documentation:

> When starting to edit a new buffer, after reading the file into the buffer, before executing the modelines.

Note that someone has pointed out https://github.com/neovim/neovim/issues/8675 to me.   After adding `set shortmess-=F` to the above settings, I can see the message.

But two things are still not clear. One is that I still do not understand why does `F` flag in `shortmess` affect this autocmd. Second is that why do `BufEneter` and `BufWinEnter` events work while `BufRead` fails.

**Comment by justinmk** [comment]
> But two things are still not clear. One is that I still do not understand why does `F` flag in `shortmess` affect this autocmd.

It's an internal implementation detail. Vim works the same way.
