### ISSUE TITLE
Request for updated documentation to describe capacity to use equal sign in insert mode key bindings

### ISSUE THREAD

**Issue by EdmundsEcho** [neovim/neovim#10016]
Neovim is awesome.  Thank you!

I hope this suggestion is useful.

Searching both the documentation and the web, I found it difficult to confirm whether `nvim` supported the use of using `=` when defining an insert-mode key binding.  Based on a `vim` exchange website, I confirmed that `vim` does **not**.  Right now I'm assuming the same is true for `nvim`.

It would be great if the `nvim` documentation explicitly describes what keys cannot be used in this situation.  The section on "reserved" keys is helpful but may not be complete given my comment.

**Comment by bfredl** [comment]
what is the issue here? `inoremap = xx` and `inoremap yy =` both work fine. using `<c-r>=` works fine etc.

**Comment by justinmk** [comment]
> It would be great if the `nvim` documentation explicitly describes what keys cannot be used in this situation. The section on "reserved" keys is helpful but may not be complete given my comment.

What section precisely? `:helpgrep \<reserved\>` shows nothing relevant AFAICT.

As @bfredl mentioned, we need a specific example of what it is you tried, and what you expect.

**Comment by EdmundsEcho** [comment]
In insert mode, I cannot seem to map `<C-=>`.

**Comment by bfredl** [comment]
This the depends on the terminal and/or gui, in some terminals it is impossible. Following the issue template would have been helpful. In my terminal (pangoterm) mapping `<c-=>` works fine.

**Comment by EdmundsEcho** [comment]
Maybe just that note at the end of the section: "Using this feature depends on the terminal and/or gui. In some terminals remapping certain key may not be possible. " ?

**Comment by justinmk** [comment]
Which section exactly? It's already mentioned in various places in the help, which hints that adding another place probably isn't going to solve the core issue.

**Comment by EdmundsEcho** [comment]
When I was trying to troubleshoot the situation, I read through https://neovim.io/doc/user/insert.html#Insert.  I could not find anything that suggested I might have difficulties using `=` while mapping my Ctrl dependent commands.

One subsection I might have expected to see something would have been under "2 Special special keys".

What do you think?

- E

**Comment by bfredl** [comment]
But the issue is unrelated to "special" keys in insert mode, or really anything about insert mode. If your terminal or GUI supports the sequence, nvim will support it in _any_ map mode. If it is not supported, it is a limitation of your terminal and not of nvim (or possibly a terminfo issue).

**Comment by EdmundsEcho** [comment]
I understand your point.  I went to the insert mode part of the documentation to figure out the problem.  I don't think I've had issues like this outside of the insert mode mapping.  So, I have not had to look outside of the vim/neovim documentation before now.  In general, we are encouraged to RT_M.  If there is a dependency on something to do with the terminal that seems to pop up in insert mode, that might be a place to say it if only because the documentation (neovim) has been where users first  go to try and solve a problem I'm only having in neovim. 

\- E
