### ISSUE TITLE
 version installed by package manager not up-to-date

### ISSUE THREAD

**Issue by xarthurx** [neovim/neovim#10011]
- `nvim --version`: 0.3.4
- Vim (version: ) behaves differently? No
- Operating system/version: Windows
- Terminal name/version: any
- `$TERM`: any

This is not a bug, but a general question.
I tried to install the software by `scoop` recommended in the wiki.
However, it seems the pacakge is not updated, while on github it shows `0.3.5` has been released.

May I ask is this managed by the nvim team or the scoop team? Can I do sth help about it?

**Comment by fmoralesc** [comment]
They are looking into it at https://github.com/ScoopInstaller/Main/pull/32 I think they are having some trouble with the artifacts attached to releases. cc @justinmk

**Comment by xarthurx** [comment]
Ah, thanks.
Also got to know the other repo for managing installers.

**Comment by mhinz** [comment]
Yup, only the releases found on GitHub are "official". Everything else it provided by outside maintainers.

**Comment by fmoralesc** [comment]
@mhinz What is the solution for the problem they have, then? The assets of the latest release are produced under the `stable` name instead of the numeric version, so they cannot fetch the appropriate artifacts.

**Comment by xarthurx** [comment]
@mhinz 
In more detail, there's no binary under the `tag` section for `0.3.5`:
https://github.com/neovim/neovim/tags

**Comment by h404bi** [comment]
That's because neovim guys made the last release (0.3.5) with a [`stable`](https://github.com/neovim/neovim/tree/stable) tag instead of `tag/0.3.5`, which breaks [the autoupdate detection of scoop](https://github.com/ScoopInstaller/Main/blob/master/bucket/neovim.json#L31-L43). Don't know why they did this to break [the semver tags](https://github.com/neovim/neovim/tags), perhaps it's a mistake.

**Comment by justinmk** [comment]
We can enhance the CI script to upload to the `v0.3.5` tag as well as the `stable` tag.

**Comment by xarthurx** [comment]
@Ash258 
This actually could be simply fixed by adding a binary package to the `0.3.5` tag besides the already provided one in the `stable` tag at:
https://github.com/neovim/neovim/tags
and I assume this is an issue from the neovim team.

Not sure why it take this long to fix...

**Comment by justinmk** [comment]
@xarthurx As I said, the CI script needs to be updated. Yes, we could do it manually, jus as scoop could fix it manually :)

**Comment by xarthurx** [comment]
@justinmk 
Yes, of course. 
The question is, are you going to keep the new way of releasing neovim (only binary in stable, but not in the numbered tag) in the future, or what's happened in the `0.3.5` is a human mistake.

IMHO, if it will be the new way in the future, the scoop team should do the fix, otherwise, the neovim team should do.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/10011#issuecomment-492608374

**Comment by xarthurx** [comment]
Yes, that's why I replied to this topic again today, as it seems that CI script is not updated after the last round of communication....

Or if there's a way to submit PR / contribute, I'm happy to.

**Comment by justinmk** [comment]
> Or if there's a way to submit PR / contribute, I'm happy to.

@xarthurx that is appreciated. I pushed a fix to our CI scripts:

https://github.com/neovim/bot-ci/commit/19467b3b690cf396eaa3cd484484986631ddc7e1

**Comment by xarthurx** [comment]
@justinmk Thank you for the work! And always, my appreciation for the development team.
