### ISSUE TITLE
New :Termdebug plugin does not handle newlines in expression evaluation

### ISSUE THREAD

**Issue by Sh3Rm4n** [neovim/neovim#10020]
I tested out the new termdebug.vim plugin #10015 and noticed the following inconsistency with newline characters.

- `nvim --version`:  v0.4.0-762-g9420a2127
- Vim (version: ) behaves differently? Not tested
- Operating system/version: Antergos Linux x86_64
- Terminal name/version: `alacritty --version` alacritty_terminal 0.3.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:packadd termdebug
:Termdebug build/bin/nvim
```
_focus gdb window_
```
b ../src/nvim/main.c:255
run
```
```
:Source 
```
- put cursor over `p` from `&params`
```
:Evaluate
```

### Actual behaviour

Evaluated expression is printed out with `\n` newline literals. In result the  floating window has only line.

![img-2019-05-17-132657](https://user-images.githubusercontent.com/29653149/57925163-88b5d400-78a7-11e9-81a6-faf3a4e7f3e9.png)

### Expected behaviour

Evaluated expression should not have `\n` and instead should break the line.

I don't know much about vimscript, so suggesting a fix would be a long session of trial and error. My guess is that the [`s:HandleEvaluate`](https://github.com/neovim/neovim/blob/9420a2127fbd6a7dc28ce4115da47bb56c57e235/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim#L557) function does not handle `\n` newline characters.

**Comment by justinmk** [comment]
cc @kwon-young
