### ISSUE TITLE
<M-u>, <M-o>, and <M-x> stopped being recongized

### ISSUE THREAD

**Issue by infokiller** [neovim/neovim#10032]
- `nvim --version`:
```
NVIM v0.3.5
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.5/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
- Vim (version: ) behaves differently?
- Operating system/version:
Archlinux with kernel `5.0.15.a-1-hardened`
- Terminal name/version:
termite
- `$TERM`:
echo $TERM | xc

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:execute "normal i\<C-v>\<M-u>"
```

### Actual behaviour

The escape character printed (looks like `^[`)

### Expected behaviour

`<M-u>` printed

**Comment by infokiller** [comment]
Tested it on older versions (0.3.0, 0.3.2, 0.3.4) and it still didn't work, which is strange because I remember it used to work, so perhaps there's something off with my setup.
However, bash does seem to recognize `Alt+u` after `<C-v>`.

**Comment by justinmk** [comment]
Nothing changed here. Try a different terminal or fix the configuration of the one you're using.

**Comment by infokiller** [comment]
Why did you close this issue? there might be a bug in nvim...

I already tried several different terminals (st, xterm, kitty) and it's the same.
I just did more testing and it looks like even `u` after `<C-v>` in insert mode doesn't output the character, though it does appear in the statusline:

![image](https://user-images.githubusercontent.com/10516814/57982557-b8074500-7a4f-11e9-8f9e-8e787168ed63.png)

**Comment by infokiller** [comment]
@justinmk or someone else- can you please try to reproduce this? it should be really easy to do

**Comment by justinmk** [comment]
I closed the issue because I use alt-chords all the time. However this seems to be specific to M-o/u/x. Weird.

**Comment by infokiller** [comment]
Gotcha, thanks for reopening it.
Were you able to reproduce the behavior I see in https://github.com/neovim/neovim/issues/10032#issuecomment-493755401?

**Comment by justinmk** [comment]
> I just did more testing and it looks like even `u` after `<C-v>` in insert mode doesn't output the character, though it does appear in the statusline:

    :h i_CTRL-V_digit

**Comment by justinmk** [comment]
Actually that help explains why this happens for u/o/x and it's expected. So there is no bug. Mapping to alt-x/u/o still works correctly:

    nn <m-u> :echo 'alt-u'<cr>

_Without_ a mapping, in insert-mode Nvim forwards ESC followed by the key. This is an intentional feature to support those who like to use ALT-h/j/k/l to "leave insert-mode and move left/right/up/down".

**Comment by infokiller** [comment]
Thanks a lot for the help and the explanation!
