### ISSUE TITLE
ve=onemore does not change the cursor move when switching to Normal mode

### ISSUE THREAD

**Issue by Glavnokoman** [neovim/neovim#10039]
- `nvim --version`: NVIM v0.3.5
- Vim (version: ) behaves differently? No idea
- Operating system/version: Arch Linux x64
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set virtualedit=onemore
```

### Actual behaviour
switching from Insert to Normal mode moves cursor one character left
### Expected behaviour
switching from Insert to Normal mode does not move the cursor

This seem to have changed very recently.

**Comment by justinmk** [comment]
vim 8.0.1453 and 8.1.1005 work the same way. Where is it documented or otherwise indicated that it should work differently?
