### ISSUE TITLE
Investigate new LLVM attribute: dereferenceable

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#1003]
Currently we are using function attributes as a great way to:
1. tell a developer reading over the code what the function can accept and return (nonnull, format, malloc, ...) and what it does and does not modify (pure, const, ...).
2. tell the compiler the same thing, thus allowing it to check for stupid errors and even apply greater optimizations. Directly passing `NULL` to a nonnull argument will yield a warning from the compiler.

It seems LLVM has recently added another attribute to the fold: `dereferenceable`. The rust developers are already taking advantage of it to enable new kinds of optimizations: https://twitter.com/pcwalton/status/492869981491564544

I've found the following in the LLVM PR that describes it: http://reviews.llvm.org/D4449

```
``nonnull``
    This indicates that the parameter or return pointer is not null. This
    attribute may only be applied to pointer typed parameters. This is not
    checked or enforced by LLVM, the caller must ensure that the pointer
    passed in is non-null, or the callee must ensure that the returned pointer 
    is non-null.

``dereferenceable(<n>)``
    This indicates that the parameter or return pointer is dereferenceable. This
    attribute may only be applied to pointer typed parameters. A pointer that
    is dereferenceable can be loaded from speculatively without a risk of
    trapping. The number of bytes known to be dereferenceable must be provided
    in parentheses. It is legal for the number of bytes to be less than the
    size of the pointee type. The ``nonnull`` attribute does not imply
    dereferenceability (consider a pointer to one element past the end of an
    array), however ``dereferenceable(<n>)`` does imply ``nonnull`` in
    ``addrspace(0)`` (which is the default address space).
```

So it would seem that `dereferenceable` is a stricter version of nonnull. And it is usually what we mean when we say `nonnull`.

Comments?

There are two possible ways of integrating this (when a sufficiently recent clang is detected): 
1. define `nonnull` to be `dereferenceable`
2. change all current `nonnull` usages to `dereferenceable` when appropriate. Defining `dereferenceable` as `nonnull` when non-clang is detected.

Both can have downsides, but the second one is the one of least surprise. `nonnull` meaning `dereferenceable` (suddenly) might be too opaque.

**Comment by justinmk** [comment]
These annotation-based micro-optimizations are risky, because the annotation must be managed by a human, and could become invalid without any warning from the compiler.
