### ISSUE TITLE
Why the 0.4 release for mac missed?

### ISSUE THREAD

**Issue by SurpassAll** [neovim/neovim#10036]

**Comment by marlonfan** [comment]
+1

**Comment by justinmk** [comment]
CI job failed because of a network problem. https://travis-ci.org/neovim/bot-ci/branches

Restarted it, should be fine in the next hour.

**Comment by SurpassAll** [comment]
> CI job failed because of a network problem. https://travis-ci.org/neovim/bot-ci/branches
> 
> Restarted it, should be fine in the next hour.

thx
