### ISSUE TITLE
Shift+Tab cannot trigger Pmenu when set wildoptions=pum

### ISSUE THREAD

**Issue by sainnhe** [neovim/neovim#10042]
- `nvim --version`: v0.4.0-789-g8c842b39b
- Vim (version: ) behaves differently? `wildoptions=pum` cannot be set in vim
- Operating system/version: Arch Linux
- Terminal name/version: Tilix 1.9.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set wildoptions=pum
:set <S-Tab>
```

### Actual behaviour

Pmenu didn't trigger.

### Expected behaviour

Pmenu should be triggered the same as when I press Tab, except that the candidate is selected from the end.

**Comment by bfredl** [comment]
can reproduce.
