### ISSUE TITLE
Feature request: add support for displaying search match index like `(n of N)`

### ISSUE THREAD

**Issue by infokiller** [neovim/neovim#10041]
Corresponding vim issue: https://github.com/vim/vim/issues/453

This has been added to vim 8.1.1270 in https://github.com/vim/vim/commit/9dfa3139198b38b28673e251a3756430065914e9

Not sure how hard it would be to backport that patch.

Thanks.

**Comment by jlesquembre** [comment]
There is a PR for it: #10114
