### ISSUE TITLE
set cmdheight=0

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#1004]
Being able to hide the command line and gain an extra line would be nice.

This one is tricky. What do we do when there's output and the height is 0? One thing we could do is just not show any output, except for output that requires interaction (a choice, or tab completion). Another thing we could do is show output like normal and treat it like a multiline output that tells you to press enter to continue, after which the cmdline goes back to it's original height (0). A third thing we could do is give the user a new flag for the `shortmess` option to turn off all non-interactive messages. The flag could be `N` for "No output and all other flags are ignored".

When `:` is typed the cmdline changes to a height of 1. After the command is executed, the cmdline disappears.

A new feature could be to make the status line more customizable so that a portion of the status line could be designated for commands. Commands could appear in the middle of the status line for example, and after executing the command the output appears in the same spot, truncated on the right side with a configurable symbol like `...` or `>`.

**Comment by tonio** [comment]
> A new feature could be to make the status line more customizable so that a portion of the status line could be designated for commands

:+1: it’s been a long time I want to do this… that would be a great feature!

**Comment by christopherdumas** [comment]
This looks great! I want be able to do this in neovim!!

**Comment by llpamies** [comment]
I think this feature is useful for developing GUIs. In this context it would be nice to disable command line, and have some extra notification system in the API to receive the output that is usually sent to the command line. Does it make sense?

**Comment by dsummersl** [comment]
Would love this feature. +1!

**Comment by metalelf0** [comment]
+1! Would be awesome :)

**Comment by justinmk** [comment]
This actually gets pretty close (suggested by @tweekmonster):

    :set lines+=1

**Comment by tweekmonster** [comment]
For posterity, here's an attempt to minimize weirdness:

```vim
let &lines += 1

function! s:cmdline(key) abort
  let &lines += 1 * (a:key ==# ':' ? -1 : 1)
  redraw
  return a:key
endfunction

nnoremap <expr><silent> : <sid>cmdline(':')
cnoremap <expr><silent> <cr> <sid>cmdline("\<cr>")
cnoremap <expr><silent> <esc> <sid>cmdline("\<esc>")
```

It'll cause the screen to flicker and messages will still overwrite the the last line.  Maybe this'll be good enough if there's a PR to skip printing single line messages if there isn't enough room.

**Comment by sassanh** [comment]
I was struggling to simulate `cmdheight=0` that I found this issue (thanks to @jamessan )
I tried `let &lines=&lines+1` but flicker is really annoying. I tried to play with `lazyredraw` but it's unusable in vimscripts: https://github.com/neovim/neovim/issues/6729 
I guess if making neovim accept 0 for cmdheight doesn't make tests fail, it's safe to have it.

**Comment by sassanh** [comment]
Compiled it with the patch @nfultz suggested and it's working very nice.

**Comment by dsummersl** [comment]
Just tried out the patch myself - it does work! But...there are issues:
 * there is an extra space unpainted on my status line on the far right.
 * command line completion isn't painted (seems to do something, you just can't see what).
 * There is flickering in the lower right when you type partial commands like ciw qq etc

**Comment by sassanh** [comment]
A bold usecase for `cmdheight=0` is to remove cmdline in some plugins interactive window (like fzf, ctrlp, gundo, etc) the above patch works perfectly for this usecase as use is not supposed to use cmdline in those windows and it just provides them more space (actually it just avoids wasting space as cmdline is absolutely useless in those windows.)
CtrlP achieves this with some magic, it has a Render method that renders its prompt in cmdline regularly so that even it doesn't really hide cmdline it has the impression that it does.
The above obviously doesn't work for users who want to "autohide" their cmdline while editing normal files.

**Comment by badeip** [comment]
I looked at something similar a while ago: https://github.com/neovim/neovim/pull/4382

**Comment by twome** [comment]
This should really be the default functionality for users new to Vim entirely - it's simply better UI design. There's absolutely no good reason the command line (and temporary/modal messages, such as from `<C-g>`) should be taking up space when inactive or dismissed.

**Comment by dpacbach** [comment]
Would be nice to see a proper solution to this.

**Comment by kutsan** [comment]
I know it's a small feature but it'd be game changer for me.

**Comment by sassanh** [comment]
After the introduction of floating windows I don't need this feature anymore, but before that I was simply compiling a patched version of Neovim and it was working very nicely, to do so all you have to do is open `/src/option.c` and find the line that is checking `cmd_line` is greater than 1 and change it to 0. That file has changed a lot of time so the patch provided above doesn't work anymore but you can find the line usually by searching for `p_ch` in the file.

**Comment by dpacbach** [comment]
@sassanh Patching no longer works even when patching the equivalent code in the new file... it causes segfaults.

**Comment by kutsan** [comment]
@sassanh How's this related to floating windows? It's just better UI generally.

**Comment by sassanh** [comment]
@kutsan My usecase was to open fzf on the bottom of screen and I didn't want to have codlin below the fzf input line, after floating windows are introduced now I open fzf as a floating window. But I agree that it is generally better UI.

**Comment by BrunoGomesCoelho** [comment]
+1 That this would be a great feature to have, currently using the code provided by tweekmonster but it flashes/is buggy sometimes.

**Comment by lucastrvsn** [comment]
Would be nice to have this possibility. I want to create a statusline that provides a "omni-line" functionality that transforms itself into a cmdline when needed. Today it's not possible and should be possible to do it.

**Comment by AndreiSva** [comment]
i agree with @lucastrvsn, that would be a game changer. Imagine something like airline that integrates with the command line.

**Comment by elkowar** [comment]
I would love to have that!

**Comment by mhinz** [comment]
This is not on our list, but we welcome contributions.
