### ISSUE TITLE
Unnamed register rarely remains unchanged after deletion

### ISSUE THREAD

**Issue by e-kwsm** [neovim/neovim#10044]
First of all, I'm sorry but I cannot reproduce the phenomenon.
This happens rarely (< once per month) for a year.
I'm mainly using neovim and  not sure what about vim.

Is there anybody who has similar experience?

- `nvim --version`:  v0.4.0-651-gca1ce590257c (v0.4.0-651-gca1ce590257c)
- Vim (version: ) behaves differently? Not sure.
- Operating system/version: Debian 9.9
- Terminal name/version: GNOME Terminal 3.22.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

An operation is something like:
1. open file
```
aaa
bbb
```
2. go to the first line and `dd` twice

I encounter this after `dd` and `S`, never after yank.

### Actual behaviour
`:registers` shows
```
""   aaa^J
"1   bbb^J
"2   aaa^J
```

The unnamed register `""` is not updated, `p` puts an older one but not the last-deleted line (`bbb`).

### Expected behaviour
`:registers` should show
```
""   bbb^J
"1   bbb^J
"2   aaa^J
```

The unnamed register is updated and `p` puts `bbb`.

**Comment by justinmk** [comment]
Is there a plugin handling any of these events:

    :au TextChanged,TextYankPost

**Comment by e-kwsm** [comment]
```
:au TextChanged,TextYankPost
--- Autocommands ---
languageClient  TextChanged
    *         call LanguageClient#handleTextChanged()
matchparen  TextChanged
    *         call s:Highlight_Matching_Pair()
neosnippet  TextChanged
    *         call neosnippet#handlers#_restore_unnamed_register()
```

This happens when  [autozimu/LanguageClient-neovim](/autozimu/LanguageClient-neovim) is not enabled.



https://github.com/Shougo/neosnippet.vim/blob/3d3362622ef10deedaea8e026054064bf62aeb33/autoload/neosnippet/handlers.vim#L41-L49 looks suspicious.

**Comment by justinmk** [comment]
`_restore_unnamed_register()` indeed looks suspect. Without `nvim -u NORC` steps to reproduce, I think it's reasonable to assume that this is a plugin issue.

**Comment by e-kwsm** [comment]
OK, thank you for your advice.
