### ISSUE TITLE
recursive comments copies full line

### ISSUE THREAD

**Issue by roptat** [neovim/neovim#10045]
- `nvim --version`: 0.3.5
- Vim (version: 8.1) behaves differently? partially
- Operating system/version: fedora 30 (but neovim was installed with Guix 1.0) ; a friend was able to reproduce on Archlinux too (same neovim version, not using Guix).
- Terminal name/version: xfce4-terminal 0.8.7.4
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC test.vim
:setlocal comments=srn:/*,mb:*,exn:*/

* write some text that starts with '*' (with spaces if you want), then try command 'o'

```

### Actual behaviour

copies the whole line on the new line

### Expected behaviour

since we are outside of a comment block, I expect nothing on the new line :)

This behaviour is the same on vim, but strangely enough, neovim also has the same behaviour on .v files, but not vim.  I tried other file extensions but only '.v' and '.vim' seem to have that behaviour.

behaves wrongly with `:setlocal comments=srn:/o,mb:o,exn:o/` for instance, when the line starts with 'o'. It only copies the middle character with `:setlocal comments=s1:/*,mb:*,ex:*/`, even outside comments.

**Comment by justinmk** [comment]
> This behaviour is the same on vim, but strangely enough, neovim also has the same behaviour on .v files, but not vim. I tried other file extensions but only '.v' and '.vim' seem to have that behaviour.

Did you compare `vim -N -u DEFAULTS`?

Anyways, patch welcome. Otherwise this is the kind of thing that is better reported to https://github.com/vim/vim/ , and we will merge the result.
