### ISSUE TITLE
[Question][Feauture Request] Format the output of quickfix

### ISSUE THREAD

**Issue by ngortheone** [neovim/neovim#10056]
Is there a way to format the information in quickfix window?

I write rust with rls and often use quickfix window to find issues.

If you compare how similar "quickfix" window looks in Emacs you will notice that the output is
justified by columns, and overall is more readable.

Emacs flycheck:

![emacs-flycheck](https://user-images.githubusercontent.com/18271144/58299046-c042e580-7dab-11e9-9411-4abb6871b375.png)

Neovim quickfix:
![vim-quickfix](https://user-images.githubusercontent.com/18271144/58299047-c042e580-7dab-11e9-92b1-89647f22aa34.png)

I have not found any options to format the output of the quickfix window. Please point me to them if they exist. If not - please consider this to be a feature request. It would be great to have
the ability to provide format a string for quickfix item, specifying column length.

**Comment by justinmk** [comment]
Good idea. Please request at https://github.com/vim/vim/ . We're not going to fork the Vim quickfix behavior, there's plenty of quickfix-related activity being done upstream.

**Comment by ngortheone** [comment]
Re-opened upstream https://github.com/vim/vim/issues/4425
