### ISSUE TITLE
Text overrides line numbers...still

### ISSUE THREAD

**Issue by Priddles** [neovim/neovim#10055]
- `nvim --version`: v0.3.5
- Operating system/version: Windows 10
- Terminal name/version: Powershell v5
- `$TERM`: vtpcon

Still affected by closed issue #9461 (PR #9474) when using Powershell.

**Comment by justinmk** [comment]
#9474 is in 0.4.0 .

**Comment by Priddles** [comment]
Sorry! I only looked at the date the PR was merged and didn't check the release notes.
