### ISSUE TITLE
Neovim on Raspberian is stuck on version 0.1.7

### ISSUE THREAD

**Issue by svliantiss** [neovim/neovim#10053]
When installing neovim via ```sudo apt-get install nvim``` installs version 0.1.7 on my raspbery pi 3b+, Raspberian Stretch Lite. This version is not supported by VimPlug so I cannot install plugins.

When building the make file it gives errors:
Command: https://pastebin.com/LC2K12Lm
Log 1: https://pastebin.com/dvxe6Cj8
Log 2: https://pastebin.com/sYjmHP0J

**Comment by justinmk** [comment]
We don't control raspbian.
