### ISSUE TITLE
Hungs on calling function 'system' 

### ISSUE THREAD

**Issue by danields761** [neovim/neovim#10057]
- `nvim --version`: 
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-DbNJXT/neovim-0.3.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-DbNJXT/neovim-0.3.5/build/config -I/build/neovim-DbNJXT/neovim-0.3.5/src -I/usr/include -I/build/neovim-DbNJXT/neovim-0.3.5/build/src/nvim/auto -I/build/neovim-DbNJXT/neovim-0.3.5/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: Vi IMproved 8.1) behaves differently? yes, different
- Operating system/version: Ubuntu 19.04
- Terminal name/version: terminator 1.91
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```
Enter `:call system('echo hi')`

### Actual behaviour

Neovim hangs on this command. I can see vim child process called `vim -c echo hi` for a while.

### Expected behaviour

`:call system` not hang vim

**Comment by justinmk** [comment]
Cannot reproduce. Steps aren't sufficient. If the steps you gave were sufficient, we would have many failing tests.

**Comment by danields761** [comment]
Ofk you can't reproduce it, because something wrong with my environment or installation. 
I want to figure out root cause of this behaviour. 

Any hint suggestions?

**Comment by justinmk** [comment]
Didn't I give a hint/suggestion above?

**Comment by wsdjeg** [comment]
I use windows 7, and I can reproduce this issue too, I will try to find out how to reproduce.

**Comment by danields761** [comment]
@justinmk , thx, my SHELL environment variable wasn't being set properly, that was cause of the problem

Solved now

**Comment by justinmk** [comment]
@danields761 thanks for the followup. Can you say exactly what you changed?

**Comment by danields761** [comment]
@justinmk, as i said above, i did a stupid mistake by setting environment variable `SHELL` to `vim`. Then i fixed it by setting `SHELL` to a default value (in my case it's `/bin/zsh`).
