### ISSUE TITLE
With Remote UI: tabselect loops indefinitely

### ISSUE THREAD

**Issue by Mariappan** [neovim/neovim#10069]
- `nvim --version`: NVIM v0.4.0-819-g66d127957
- Vim (version: ) behaves differently? NA
- Operating system/version: PopOS 19.04
- Terminal name/version: Tilix 1.8.9
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

When starting neovim in remote ui mode(I used gonvim and later found issue present in veonim also), giving tabselect commands loops indefinitely. The memory used by nvim process is continuously increasing and at last linux kills nvim

### Actual behaviour
Tagselect loops forever and consume lot of memory and finally gets killed by linux

### Expected behaviour
Tagselect should return immediately

I tried to debug with gdb and found the following call_stack:
do_tag -> taglen_advance -> msg_advance -> msg_putchar (Loops forever)
``` C++
void msg_advance(int col)                                                                           
{                                                                                                   
  if (msg_silent != 0) {        /* nothing to advance to */                                         
    msg_col = col;              /* for redirection, may fill it up later */                         
    return;                                                                                         
  }                                                                                                 
  if (col >= Columns)           /* not enough room */                                               
    col = Columns - 1;                                                                              
  if (cmdmsg_rl)                                                                                    
    while (msg_col > Columns - col)                                                                 
      msg_putchar(' ');                                                                             
  else                                                                                              
    while (msg_col < col)                                                                           
      msg_putchar(' ');                                                                             
}                                                
```
In the above code, the msg_col was always zero and col was 50, which causes infinite loop.
I tried to find where should be the msg_col be increased and got lost.

Someone who is expert in neovim code might fix this easily.
Thanks

**Comment by Mariappan** [comment]
Any pointers ?? I can try to fix, Please let me know what is the expection.
Do we need to increment the msg_col each time msg_putchar() is called.
notify @bfredl

**Comment by bfredl** [comment]
Is this with `ext_messages`? I suppose in ext_messages mode we can make `msg_advance` output a single space (or a single tab to follow the reasoning in #10150 ) until the callsites have been refactored to properly support ext_messages.

**Comment by Mariappan** [comment]
Yes @bfredl It is with ext_messages only

**Comment by bfredl** [comment]
Should be fixed on master.
