### ISSUE TITLE
replace c parser with facebookresearch/CParser

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#10066]
Currently we use a custom lpeg-based C parser. It works mostly ok but there were cases where it got confused by new macros, etc. introduced by compilers or toolchains.

- https://github.com/neovim/neovim/blob/master/src/nvim/generators/gen_declarations.lua
- https://github.com/neovim/neovim/blob/master/src/nvim/generators/c_grammar.lua

This project is potentially more robust:

- Lua: https://github.com/facebookresearch/CParser
- Python: https://github.com/eliben/pycparser

Or perhaps treesitter could be used...

**Comment by lewis6991** [comment]
We will always need a custom parser to support all of our custom macros that feed the generator scripts.

I also recently consolidated and improved our lpeg grammars in https://github.com/neovim/neovim/pull/31354
