### ISSUE TITLE
Proper line breaks for CJK texts

### ISSUE THREAD

**Issue by XVilka** [neovim/neovim#10077]
See https://github.com/vim/vim/pull/3875

**Comment by justinmk** [comment]
We don't track upstream issues here. Just merge the relevant patch when it lands in Vim.

**Comment by ZhiyuanLck** [comment]
@justinmk Is [patch 8.2.0901](https://github.com/vim/vim/commit/e52702f00322c8a8861efd0bd6a3775e685e5685) merged? It seems that nvim still cannot break CJK lines correctly.

**Comment by clason** [comment]
Yes.
