### ISSUE TITLE
Do not implicitly convert <C-i> to <Tab>

### ISSUE THREAD

**Issue by sassanh** [neovim/neovim#10079]
- `nvim --version`: NVIM v0.4.0-632-g9d77a0768
- Vim (version: -) behaves differently?
- Operating system/version: Ubuntu 19.04
- Terminal name/version: neovim-qt, Konsole
- `$TERM`: xterm-256color

Related discussion: https://github.com/equalsraf/neovim-qt/issues/33#issuecomment-496554202

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:map <c-i> a
:map <c-i>

```

### Actual behaviour

It shows `<Tab>          a`

### Expected behaviour

It should show `<C-i>          a`

**Comment by justinmk** [comment]
From https://github.com/equalsraf/neovim-qt/issues/33#issuecomment-496554202 :

> `call nvim_input('<tab>')` invokes a mapping to `:nn <c-i>`. 

Changing this will break `<c-i>` mappings in the TUI. But that's the only sane way: I don't think we want `nvim_input('<tab>')` to behave differently depending on which clients are attached...

**Comment by zeertzjq** [comment]
A backward-compatible solution I can think of is to add a separate notation for Ctrl key combinations typed in a GUI (or a terminal that can distinguish `CTRL-I` and `Tab`), that automatically gets converted to `<C-…>` if unmapped.

**Comment by zeertzjq** [comment]
Closed by #17825
