### ISSUE TITLE
diff-mode: make it smarter

### ISSUE THREAD

**Issue by splinterofchaos** [neovim/neovim#1007]
I only recently discovered diff mode thanks to vim-fugitive, but now that I do know of it, I find it absolutely indispensable and use it many times a day, but it doesn't seem very popular or well known and could use some improvements.

Vim tries to do live updating when in diff mode for adding or removing a line, but modifying a context line requires the user to manually run `:diffupdate`. I submitted a bug report to vanilla vim ([BR](https://code.google.com/p/vim/issues/detail?id=242&thanks=242&ts=1406659605)--read this for more details) so I might end up submitting an upstream patch.

After having read through some of `src/nvim/diff.c`, I see that vim calls the external `diff` through `call_shell()` and [`ex_diffupdate()`](https://github.com/neovim/neovim/blob/2b62dcddf801e096bde7d4608e090018b5227e98/src/nvim/diff.c#L634) updates the diff of the entire file. How inefficient. First, it has to [copy the modified file to the file system](https://github.com/neovim/neovim/blob/2b62dcddf801e096bde7d4608e090018b5227e98/src/nvim/diff.c#L761), then the `diff` program must read both versions to generate the diff file, then vim must [open that file and compare it to the original and modified versions](https://github.com/neovim/neovim/blob/2b62dcddf801e096bde7d4608e090018b5227e98/src/nvim/diff.c#L1188) to create the diff view. We should be able to call `diff` with `-` on the modified version of the file to avoid creating a temp, and similarly, read the output instead of making a temporary diff file.

 I think we can make more extensive improvements than the vanilla team could:
- [ ] General refactorings:
  - [ ] Use `bool` over `TRUE`/`FALSE`
  - [ ] move declarations closer to their uses.
  - [ ] Improve documentation. (Undocumented `@param`s.)
  - [ ] Maybe split functions up into smaller, easier to groc, units.
    - There are four instances of `// search for a change that includes "lnum" in the list of diffblocks.` in this file. Should be `find_diff_line(lnum,idx)` or something.
- [ ] Improve implementation by one or more of:
  - [ ] Pipe in/out to/from external `diff` command (maybe use the new `os_system()`).
  - [ ] Alternative library diff solution.
- [ ] Improve error reporting. 
  - At least on [line 1817](https://github.com/neovim/neovim/blob/2b62dcddf801e096bde7d4608e090018b5227e98/src/nvim/diff.c#L1817), we can observe an instance where an error is generated, but not useful information given.
- [ ] Update diff view on context-line changes. [BR](https://code.google.com/p/vim/issues/detail?id=242&thanks=242&ts=1406659605)

**Comment by SergejZnamenskij** [comment]
What about to make word-level diff #3433 possible? I can write an external program to write word-level diff in any appropriate format with the described in http://psta.psiras.ru/read/psta2015_1_189-197.pdf improved diff algorithm.

**Comment by ZyX-I** [comment]
@SergejZnamenskij It is too early to talk about any external tool. First it is needed to change the source code. Changing `diff_find_change` function and its callers (`win_line` in `screen.c`) seems to be rather easy, assuming you want to work with in-line changes differently then with the whole buffer changes: change this function (e.g. to return array of ranges), and change place where its startp/endp arguments are used and you are done. Theoretically you can add some option like `diffinlineexpr`, but this will additionally require caching or will be very slow due to being run on each diffing line twice I think.

But that seems not so easy if you want to use something like `ndiff.py` as the diff source, or any other external tool that outputs changes for the whole file.

**Comment by SergejZnamenskij** [comment]
Thank you very much for fast respond. 
I like vim diff very much but have two problems.
First one is how to localize multiple changes in a long source line. Today I have tried diffchar.vim, unfortunately it produce errors in my vim7.3.547 from stable Debian distribution. 
Second problem was  the wrong lines alignment for large LaTeX log files. It is not vim but LCS related problem. 
I have discovered it and just presented on SiSAp-2015 novel approach to string similarity problem. The main idea is simple - the common subsequence must contain maximal number of common substrings, not number of common elements. This gives a reasonable priority to longer common substrings as each of them contain l(l+1)/2 smaller substrings which eliminates the well known LCS drawbacks. It is also more robust then patience or histogram approaches.
There are some ideas of a fast algorithm (unfortunately not so simple). For situations where it will be hard to find optimal set of a lot of small unchanged places in a short time, it can quickly optimally detect all the longest unchanged substrings and return them.  
Such approximate calculation is less complex then LCS by the nature of problems and always can be done in the linear time.
Now I look for a right frames for evaluation and testing of this new approach.

**Comment by splinterofchaos** [comment]
> I like vim diff very much but have two problems.

Vim just uses GNU's diff and parses the output. It doesn't understand word-based differs, otherwise we could (hopefully) use git's --word-diff, though your algorithm might be an improvement.

>  I can write an external program to...

Sure, just set [diffexpr](ttp://vimdoc.sourceforge.net/htmldoc/options.html#'diffexpr') to `your_prog`, but if it isn't in a format identical to GNU diff, vim can't parse it. I'd like to adopt a standard word diffing format, but I'm not sure one exists. Maybe git's --word-diff does, but I don't know it's like GNU diff enough.

Alternately, after making vim understand non-line oriented diffs, we could allow diff providers. The only real advantages I see ATM is breaking away from any specific format, but there could be others.

**Comment by SergejZnamenskij** [comment]
Yes, I have tried to discover something alike the standard format for word diff output. 
The git --word-diff=porceline appears to be the ultimate format to be found for this task. It is universal and readable simultaneously and close to the line diff. I can not figure any need for any other formats apart from the old one for the backward compatibility and this one for the robust representation of inline changes.
