### ISSUE TITLE
Background transparency ignored when open shell scripts

### ISSUE THREAD

**Issue by kureijir** [neovim/neovim#10076]
- `nvim --version`:
```
NVIM v0.3.5
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -peda
ntic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto
 -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/s
rc/build/config -I/build/neovim/src/neovim-0.3.5/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/in
clude
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: 8) behaves differently?
I can't even get Vim 8 to have transparent background.
- Operating system/version: Arch Linux
- Terminal name/version: alacritty or termite (with or without tmux)
- `$TERM`: `xterm-256color` or `tmux-256color`

### Steps to reproduce using `nvim -u NORC`
1. Just run `nvim -u NORC`. By default neovim would use my terminal's background.
2. `:colo darkblue`: this theme has a solid background color.
3. `:hi Normal ctermbg=NONE`: make it transparent
4. `:setfiletype sh`: now the background turns solid again
5. set `filetype` to another one doesn't turn it back to transparent, but run `:hi Normal ctermbg=NONE` again does

It seems only the `sh` filetype has this behavior.

In my actual config, I use `gruvbox` theme, with `set termguicolors`, and that requires `hi Normal guibg=NONE` to make the background transparent, but everytime I open a shell script (except `.zsh` files), the background turns solid. Having `au filetype sh hi Normal guibg=NONE` in my `init.vim` doesn't help either.

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!

**Comment by kureijir** [comment]
@justinmk Well, I just tested with Vim 8 (with `vim -u NORC`), and with the exact same steps as above, I can't reproduce the bug. So maybe there is something neovim-specific.

`vim --version` output:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 26 2019 21:55:55)
Included patches: 1-1186                                                                                                                Compiled by Arch Linux                                                                                                                  Huge version without GUI.  Features included (+) or not (-):                                                                            +acl               +extra_search      +mouse_netterm     -tag_old_static                                                                +arabic            -farsi             +mouse_sgr         -tag_any_white  
+autocmd           +file_in_path      -mouse_sysmouse    +tcl/dyn                                                                       
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors                                                                 
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               +perl/dyn          +user_commands
-clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python/dyn        +visualextra
+conceal           +linebreak         +python3/dyn       +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore 
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua/dyn           +ruby/dyn          +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11  
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim                                                                           
-ebcdic            -mouseshape        +statusline        -xpm    
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp     
+eval              +mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save 
   system vimrc file: "/etc/vimrc"                                                                                                      
     user vimrc file: "$HOME/.vimrc"                             
 2nd user vimrc file: "~/.vim/vimrc"                              
      user exrc file: "$HOME/.exrc"                                                                                                     
       defaults file: "$VIMRUNTIME/defaults.vim"                  
  fall-back for $VIM: "/usr/share/vim"                           
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE
 -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-
rpath,/usr/lib/perl5/5.28/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim     
   -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.28/core_perl/CORE -Wl,-O1,--sort-common,--as-
needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.28/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt
 -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm
```

Also `nvim -d /usr/share/nvim/runtime/ftplugin/sh.vim /usr/share/vim/vim81/ftplugin/sh.vim` shows no difference.

**Comment by kureijir** [comment]
@justinmk Should this be re-opened? Since I can't reproduce it on Vim.

**Comment by justinmk** [comment]
try Nvim 0.4., you are comparing the bleeding edge of Vim to the stable version of Nvim.

**Comment by kureijir** [comment]
@justinmk 

> Compare `syntax/sh.vim`. The `ftplugin/sh.vim` file never changes.

Well, `syntax/sh.vim` does get some updates in Vim, but I think that isn't the cause of the problem, because when I try to disable that file (`sudo mv sh.vim sh.vim.old`), background color still resets (while syntax coloring is lost, texts are all black). Meanwhile, disabling `syntax/synload.vim` or `syntax/syntax.vim` would get rid of the problem (but these 2 files are identical between neovim and vim).

**Comment by justinmk** [comment]
Patch welcome, otherwise I'm inclined to wait and see if the problem goes away when I get a chance to update the runtime files.

**Comment by kureijir** [comment]
@justinmk Finally I found the cause. It's my custom ftplugin `sh.vim` that has `syntax on` inside of it, so it load the colorscheme a second time, thus override any custom background color. I thought `nvim -u NORC` discarded all my custom config, but it still loaded ftplugins. Anyway this is solved and thanks for your support.
