### ISSUE TITLE
Feature request:  default local options for floating window

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#10081]
For floating window, I always use commands:
``` vim
setl nonumber norelativenumber nocursorline nocursorcolumn
setl nospell nolist nowrap foldcolumn=0
setl signcolumn=no  listchars=eol:\\ 
```
to make the floating window looks good, could be better if they can be default options for floating window.

**Comment by bfredl** [comment]
Most of these make sense. We already have `nonumber`, so `norelativenumber` is needed for consistency. I'm not sure about `signcolumn=no`, `signcolumn=auto` seems better (if a plugin adds signs to its float, they are expected to be shown). `listchars=eol:\\` is entirely a stylistic choice, seems weird for nvim itself to override the users setting there. 

Also I'm not sure about `nowrap`, it depends on the display strategy. Rather that hardcoding this into the raw API, it would be better for a wrapper function i e that calculates the size of the window to fit a certain text to decide this. One usecase is to provide the text as a list of screenlines that then not must be wrapped, but another usecase is to display paragraph text, then wrapping is expected.

**Comment by wsdjeg** [comment]
> We already have nonumber, so norelativenumber is needed for consistency. 

as neovim use nonumber and norelativenumber bydefault, I do not this change this option is good idea, this will make user perplexed. for me  I have `set nu` in vimrc, it take me too long time to find why floating windows has no number!!

**Comment by wsdjeg** [comment]
BTW, why do you think `no nu`  should be default option, It's based on what you're going to do with the floating window.

**Comment by bfredl** [comment]
> BTW, why do you think no nu should be default option, It's based on what you're going to do with the floating window.

Any default will help some usecases and be less helpful for other usecases. Currently the API is designed to be used by some plugin, rather than being used by the user directly, with some weight towards temporary popups and menus and such, rather than "ordinary" editing, even though the later is by no means excluded. The basic trade-off is how much we want the `nvim_open_win` to do by itself, as opposed as what plugins have to do (or some future wrapper function in the runtime, or lua magic or something).

**Comment by bfredl** [comment]
While setting every option as @chemzqm enumerated is a bit tedious, an intermediate could be to allow some kind of option "profiles". Like there could be a "popup" flag to `nvim_open_window` which

- disable decorations like number, rnu, manatory signcolumn, spellchecking
- makes the EOB area go away (use the same backgroud color), or downsize the window automatically
- forbid scrolling if all text already fits in the window (though with `focusable=false` accidental scrolling is already rare).
- and so on

**Comment by bfredl** [comment]
This is addressed on master. No option is changed implicitly, not even 'number'. Use `style='minimal'` arg to `nvim_open_win()` to change a larger batch of options to resonable "minimal UI" values.
