### ISSUE TITLE
Please can the 3 line limit of preview windows be removed (or increased)

### ISSUE THREAD

**Issue by dharrigan** [neovim/neovim#10088]
Hi,

Using:

```
NVIM v0.3.7    
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.7/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
```

There is a hardcoded size of `3` in a preview window height, i.e., as shown in the [source code](https://github.com/neovim/neovim/blob/8342b4486b43e6664b6412ac0c8a549097220df2/src/nvim/popupmnu.c#L650).

Could this restriction be relaxed please to allow for bigger preview window sizes? Using tools such as deoplete that offers integration to various Language Server Protocol backends, shows that 3 is a very small number for displaying method signatures and/or documentation.

Here is an [example](https://imgur.com/a/vvhCtwB)

Notice how the documenation is cut off with an ellipsis. Having the documentation available would be very handy in this instance, but I can't see it due to the hard coded 3 maximum value.

Perhaps a limit of 50 lines?

Thank you.

**Comment by justinmk** [comment]
I guess you mean `completeopt=preview`. Plugins like deoplete and other LSP plugins can already use floating windows. We plan to enhance that in https://github.com/neovim/neovim/issues/9663

**Comment by dharrigan** [comment]
Hi,

Thanks for the feedback and I look forward to 0.4.0 coming out! :-)
