### ISSUE TITLE
Feature Request: allow opening ports from lua

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#10084]
I'm opening this feature request after a short exchange about TCP ports happened here: https://github.com/glacambre/firenvim/issues/13#issuecomment-495336620.

I'm currently writing a browser extension that acts as a neovim GUI. I started by using the browser's webextension API, which enables communicating with programs over stdin/stdout. Unfortunately, this API makes messages go through several layers of IPC and results in very high latency (up to 10ms in order to get an answer to a single keystroke). In order to reduce the amount of IPC, I would like to replace the webextension API with a [websocket](https://en.wikipedia.org/wiki/WebSocket) and talk directly to neovim through it.

In order to be able to do this, I would need to be able to open a TCP port and wait for the browser to connect to it. I could write a lua plugin that just takes care of "unwrapping" msgpack-rpc messages from their "websocket shell" before forwarding them to neovim and then wrapping the answers in websocket messages before forwarding them to the browser.

**Comment by bfredl** [comment]
This will be possible when the libuv loop is exposed to lua #9546. Then `luv` interface can be used to run a TCP server with an arbitrary protocol implementation.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/4443 will be a security concern however. Maybe a good gsoc project for next year...

**Comment by glacambre** [comment]
#4443 shouldn't be a problem for my specific use case as I can still have the browser extension exchange a security token with neovim over stdio and do the bulk of my communications over the websocket.

**Comment by nostdm** [comment]
@glacambre  You could create a remote vim plugin so that the communication would be something like **localhost** > **remote plugin** > **neovim**. I think the additional step of having the plugin talk through a socket to neovim doesn't add that much overhead compared to the localhost TCP connection from the browser.

**Comment by justinmk** [comment]
@glacambre  a working example is documented at `:help tcp-server` .
