### ISSUE TITLE
Option ‘guifontwide’ is useless

### ISSUE THREAD

**Issue by mzr1996** [neovim/neovim#10094]
- `nvim --version`:
```
NVIM v0.4.0-819-g66d127957
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
```
- Vim 8.1 behaves differently?
Yes, gvim supports the option 'guifontwide'.
- Operating system/version:
Windows Home Basic 1903
- Terminal name/version:
nvim-qt

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set guifontwide=等宽更纱黑体\ SC
```

### Actual behaviour
Nothing happened. No warning, and the output of `set guifontwide=?` is `guifontwide=等距更纱黑体 SC`.
### Expected behaviour
The chinese characters' font should be changed.

I have also tried `Guifont`. It works, but it can set only one font, that means I cannot set Latin characters' font and Chinese characters' font separately. I'm wondering if I can set Chinese characters' font by the option `guifontwide` or use command `Guifont` to set two fonts, just like URxvt's configuration:
```
URxvt.font:xft:Hack Nerd Font Mono:pixelsize=23, xft:Sarasa Mono SC:pixelsize=26
```

**Comment by bfredl** [comment]
The handling of fonts is implemented by the UI itself, nvim-qt it this case. Please report the issue at https://github.com/equalsraf/neovim-qt/ .
