### ISSUE TITLE
API: function for replacing buffer content (without moving cursors)

### ISSUE THREAD

**Issue by ipod825** [neovim/neovim#10096]
As pointed out in [#7756 (comment) ](https://github.com/neovim/neovim/issues/7756#issuecomment-496834966), the semantic of `nvim_buf_set_lines` does not guarantee cursors stay at the same line (because that the line the cursor stay might be gone?). But when replacing content in a single line, the user would expect the cursor to stay at the same position. So we need either 1) a new api to replace lines with premise that the line numbers are the same 2) a flag in `nvim_buf_set_lines` so that it knows the line number stays the same.

An example on how `nvim_buf_set_lines` changes the cursor position is copied here from #7756 (note that in this example, the number of lines stays the same yet `nvim_buf_set_lines` still changes the cursor position):
With test.txt as
```
0
1
2
```
and run the the following commands after opening after `nvim -U NORC test.txt'
```vim
let buf = nvim_get_current_buf()
call nvim_feedkeys('j', 'n', v:false)
call nvim_command('vsplit')
call nvim_command('wincmd l')
call nvim_feedkeys('j', 'n', v:false)
call nvim_buf_set_lines(buf, 1, 2, v:false, ['2'])
```
Ideally, the cursor for the left window should stay at the second line. But it is set to the first line.

**Comment by bfredl** [comment]
I was thinking of a function that takes two positions `[lnum1, col1]` and `[lnum2, col2]` and new text to replace the text between these positions. You can then replace the contents of a line then by `[2, 0]` and `[2, -1]` , which would put the cursor at the beginning of the line instead. Or even just replace a part of a line, to preserve cursor column positions (and later on, extended marks) outside of this part.

**Comment by ipod825** [comment]
I don't know how `nvim_buf_set_lines` is implemented. But couldn't we check if the original cursor position is still available in `nvim_buf_set_lines`? If it is still available, there's no reason that we don't guarantee the cursor stay in the same position. If not, the user surly shouldn't expect the cursor to stay in the same position. It would be odd that we have two apis doing similar stuff with the different premise that can be induced by the arguments (whether the current cursor position is still available).

**Comment by bfredl** [comment]
`nvim_buf_set_lines` behaves the same (with respect to non-current cursors) as if you did a _line_-wise visual select and put in the current window. The cursor position is not preserved, because there are no positions to preserve. I don't think `set_lines` should behave radically different depending on the line count matches exactly or not, nor should it behave differently than the line-based edit operation that it represents. 

It sounds much clearer to me to introduce an API function that expresses the intended edit operation: change of text within a single line, which is a special case of _char_-wise replacement between two arbitrary marks.

**Comment by ipod825** [comment]
Given that a new api is implemented. Do you think that we also have a separate api for python?
```python
# which semantic are we referring to now, nvim_buf_set_lines or the new api?
nvim.current.buffer[1] = 'new text'
# And what about this?
nvim.current.buffer[2:4]=['new line2','new line3']
```

**Comment by bfredl** [comment]
@ipod825 The python buffer API is generally meant to be compatible with vim. Though when I checked, vim (arch latest version, I cannot build master with python) implements the behaviour I expected only for the current window (i e `buf[1] = "x"` and `buf[1:2] = ["x"]` are not the same), but not for non-current window. Maybe the later could be considered a bug, or no one has cared enough about the behavior before. Though it will matter a lot more if text props resp extended marks become common.

**Comment by ipod825** [comment]
Indeed, nvim & vim behaves differently now.
Given the two window (`|` indicates cursor position, the left part is left window, the right part is the right window):
```
0                      0
|1                    |1
2                      2
```
Running on vim `vim.current.buffer[1]="10"` results in
```
0                      0
|10                   |10
2                      2
```
Running on neovim `vim.current.buffer[1]="10"` results in
```
|0                      0
10                     |10
2                       2
```
Running on vim `vim.current.buffer[1:3]=["10", "20"]` results in
```
0                     |0
|10                    10
20                     20
```
Running on neovim `vim.current.buffer[1:3]=["10", "20"]` results in
```
|0                    0
10                   |10
20                    20
```

**Comment by ipod825** [comment]
I just realized that vim has a `setline` function that sets a line without moving the cursor.

**Comment by zgpio** [comment]
Inconsistent behavior in current window and others when use `nvim_buf_set_lines`.
Inconsistent behavior when length of `buffer line` and `content line` are different:
e.g.
![image](https://user-images.githubusercontent.com/19503791/63936339-29fd1a80-ca92-11e9-8d09-66af21c6358f.png)
1. `:call nvim_buf_set_lines(0,0,-1,v:true,['aaa','bbbbb','ccccccc'])`
2. `:call nvim_buf_set_lines(0,0,-1,v:true,['aaa','bbbbb','ccccccc','dddddddd'])`

`1` will change the cursor position, while `2` do not.

**Comment by justinmk** [comment]
0.5 includes `nvim_buf_set_text`
