### ISSUE TITLE
Backup Option Prevents Multiple Saves to Symlinked Files

### ISSUE THREAD

**Issue by gregbartell** [neovim/neovim#10101]
I've done a git bisect and found that this is a regression introduced by b4d894c06709b4ae807d540dfda21ab3220a989a: the previous commit works as expected.

- `nvim --version`:
```
NVIM v0.4.0-371-gb4d894c06
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolch
ain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Wall -Wex
tra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion
 -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostic
s-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -
DNVIM_UNIBI_HAS_VAR_FROM -I/Users/gregory/Workspace/neovim/build/config -I/Users/gregory
/Workspace/neovim/src -I/Users/gregory/Workspace/neovim/.deps/usr/include -I/usr/local/o
pt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platfor
m/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Users/gregory/Workspace/neovim/build/src
/nvim/auto -I/Users/gregory/Workspace/neovim/build/include
Compiled by gregory@daytona.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently? 
I haven't checked, I don't think it's relevant for a regression like this.
- Operating system/version:
Mac OSX 10.14.5
- Terminal name/version:
iTerm2 3.2.9
- `$TERM`:
xterm-256color

### Steps to reproduce

In words:
1) Set the "backup" option on.
2) Open a symlink to a file in a different directory.
3) Write to the file. This creates a file in the backup directory.
4) Write to the file again. This one fails because it cannot overwrite the backup file created in step 3.

I wrote a script to make doing the bisect easier, it might come in handy.

```
#! /bin/bash

# Make a backup dir free of any previous files
mkdir test_backupdir

# Minimal vimrc to use that dir
printf "set backup\nset writebackup\nset backupdir=./test_backupdir\n" > test_vimrc

# Create a file and a symlink to it
touch test.txt
# Specifying the full path seems to be required: "ln -s test.txt link_to_test.txt" does not reproduce the issue
ln -s $(pwd)/test.txt link_to_test.txt

# Open the symlink and try to write to it twice
./nvim -u test_vimrc -c "w" -c "w" link_to_test.txt

# In affected versions, the second write fails with the message:
# E509: Cannot create backup file (add ! to override)
# Press ENTER or type command to continue

# Running "ls -lA test_backupdir" shows that the only file is a symlink named
# "link_to_test.txt~" pointing to the path of the test.txt file
```

### Actual behaviour

The second attempt to write to the symlink fails.

In versions with the bug, the backup file is a symlink to the real one. In versions without it, it is a real text file.

### Expected behaviour

You can write to a file (or symlink to that file) as many times as you'd like.

**Comment by gregbartell** [comment]
I took a quick look at the commit in question (https://github.com/neovim/neovim/pull/9709/commits/b4d894c06709b4ae807d540dfda21ab3220a989a) and the libuv docs (http://docs.libuv.org/en/v1.x/fs.html#c.uv_fs_copyfile), and I think the problem is that we're copying the literal file that we're editing, i.e. the symlink, instead of the file that our link is pointing to. Without the flag that the commit added, libuv appears to have been following through the symlink to get to the underlying file, while with the flag it doesn't follow the link.

If that's truly the case, then that seems like an inconsistency on libuv's part and the real change needs to be made upstream there.

**Comment by justinmk** [comment]
@gregbartell Thanks for bisecting! Let's just remove `UV_FS_COPYFILE_FICLONE` flag for now. Could you send a PR (with explanation in the commit-message)?

> Without `UV_FS_COPYFILE_FICLONE`, libuv appears to have been following through the symlink to get to the underlying file, while with `UV_FS_COPYFILE_FICLONE` it doesn't follow the link.

@cjihrig is it expected that `UV_FS_COPYFILE_FICLONE` has this behavior for symlinks?

**Comment by gregbartell** [comment]
> Alternatively, we omit UV_FS_COPYFILE_FICLONE if the file looks like a symlink.

If we're already talking about identifying symlinks, then we might as well finish the job by calling `readlink` on it and passing the underlying file to the copy function. Observed behavior is the same, but maybe we can keep the perf. benefits of supporting CoW.

I'll see if I can whip up a PR quickly and get your thoughts on it.

**Comment by gregbartell** [comment]
I'm new to the GitHub workflow, but I think I've figured how to push a PR. Now to figure out how to link it to the ticket... https://github.com/neovim/neovim/pull/10102

**Comment by cjihrig** [comment]
> is it expected that UV_FS_COPYFILE_FICLONE has this behavior for symlinks?

What version of libuv is neovim using? I ask because it appears that this issue is about macOS. In versions of prior to 1.28.0, libuv called mac's [`copyfile(3)`](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/copyfile.3.html). However, we received bug reports that `copyfile(3)` was not respecting file permissions. Starting with 1.28.0, macOS uses the same implementation as all other unix platforms. Here is the [commit](https://github.com/libuv/libuv/commit/5bc4d7738a172f6361d8b5dd0949789dcf1ff60d) where the macOS-specific implementation was removed, and [this](https://github.com/libuv/libuv/blob/4a4c9a688fa2a7fad056f48304a583927044b935/src/unix/fs.c#L902-L1029) is the current implementation.

**Comment by gregbartell** [comment]
I just ran a clean build and neovim pulled in libuv 1.26.0. It sounds like that's the source of the problem then.

**Comment by justinmk** [comment]
@cjihrig Thanks! We were targeting libuv 1.26 https://github.com/neovim/neovim/blob/master/third-party/CMakeLists.txt#L130

@gregbartell could you try https://github.com/neovim/neovim/pull/10104 ? Will need `make distclean` (to remove the `.deps` directory).

**Comment by gregbartell** [comment]
@justinmk I can confirm that #10104 does fix this issue.
