### ISSUE TITLE
Error E5003 every time a file is saved

### ISSUE THREAD

**Issue by iurobpn** [neovim/neovim#10108]
I'm having the folowing error every time a file is saved:

```
E5003: Unable to create directory "/home/username." for undo file: permission denied
```

There is a dot after the username. When calling nvim with the command:

```
nvim -u NORC
```
saving a file will not return the error E5003. The :checkhealth will only give this warning:

```
WARNING: neovim-ruby-host not found.
```

My system:
```
xubuntu 16.04
nvim --version is v0.3.7
gnome-terminal 3.18.3
tmux 2.1
```

with tmux:
```
$TERM=screen-256color
```
without
```
$TERM=xterm-256color
```

It works with vim, so I think it might be a neovim bug.

**Comment by erw7** [comment]
Your .vimrc has the following settings:

```vim
set undodir=$HOME."/.undodir"
```

I think that you need to set correctly as follows.

```vim
set undodir=$HOME/.undodir

" or

let &undodir=$HOME."/.undodir"
```

**Comment by iurobpn** [comment]
It worked, but neovim vimL is different from vim? It should work...

**Comment by erw7** [comment]
> It worked, but neovim vimL is different from vim?

No. The result of `set undodir=$ HOME. "/. undodir"` will both be `/home/username.`(See. `h: option-backslash`). If `undodir` is not a directory, `vim` just ignores it, but `neovim` tries to create it.

Ref. [vim/src/undo.c#L834-L846](https://github.com/vim/vim/blob/98fb65cb051f625f4ce291a9f9cdb2e54ac1e688/src/undo.c#L834-L846)
Ref. [neovim/src/nvim/undo.c#L686-698](https://github.com/neovim/neovim/blob/f046f3a2396ea23e53e7307e8c143dc646f5273c/src/nvim/undo.c#L686-L698)
