### ISSUE TITLE
replace gperf with triehash

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#10118]
currently we use [gperf](https://www.gnu.org/software/gperf/) to generate a hashtable as a build-step. It's a somewhat cumbersome dependency. We could replace it with [triehash](https://github.com/julian-klode/triehash) or some other script, which also produces higher-quality results.

Although triehash is written in perl, this is somewhat less of a liability than C++. However, ideally, we would find a Lua script or rewrite it in Lua.

related: https://github.com/neovim/neovim/issues/10066

**Comment by craigbarnes** [comment]
I had a Lua script for a similar purpose in [`dte`](https://github.com/craigbarnes/dte). It used a similar strategy to `triehash` -- i.e. build a trie structure (out of Lua tables) and then iterate over the nodes, generating C `switch` statements until there was only 1 leaf node remaining per `case` and then checking the remainder of the string with `memcmp()`.

The problem I have with this approach is that, despite being very fast, it produces a lot of binary bloat and isn't that much faster than a `bsearch()` over a static table of strings. Also, if you check the output into git (to avoid a build dependency on the tool), it produces tons of diff churn (much like gperf) every time you have to regenerate it.

Even high speed parsers like [`md4c`](https://github.com/mity/md4c/blob/f0de1990601c1f3e8176576c27f30c00b05d7854/md2html/entity.c#L2185-L2189) seem to get away with using `bsearch()` and it has the advantage of being directly editable in C with no external dependencies.

**Comment by justinmk** [comment]
@craigbarnes very good point, and [md4c](https://github.com/mity/md4c/blob/f0de1990601c1f3e8176576c27f30c00b05d7854/md2html/entity.c) is a nice reference. Using `bsearch()` would be an easy short-term solution, and if anyone finds that triehash is somehow much faster then we could always reconsider.

**Comment by bfredl** [comment]
gperf/triehash is intended as a faster replacement for a runtime constructed hashtable (map.c / khash.h). If the point is that time differences are all too small to notice, the straightforward solution would be just to use map.c everywhere.

**Comment by justinmk** [comment]
@craigbarnes so when you say "isn't that much faster than a bsearch()" what are the actual numbers?

**Comment by craigbarnes** [comment]
@justinmk I only had to convince myself at the time, so I didn't do any writeup. I wish I had done. All I remember is that they were both so fast that it wasn't ever going to be a bottleneck and `bsearch` had the advantage in every other metric.

I'd like to have some numbers for next time I make such an assertion with no proof, so maybe I'll put together a benchmark when I get some free time.

**Comment by NikhilReddy-2** [comment]
( Newbie here) Was this addressed in any other patch? if not then can I work on this? Thinking of doing a quick benchmark for the above discussion about bsearch() and triehash.

**Comment by clason** [comment]
@NikhilReddy-2 This was partially addressed in #11365 which stalled. If you want to work on this, you could (should) continue from there (if the author doesn't want to pick it up again).

**Comment by bfredl** [comment]
@NikhilReddy-2 FWIW I was playing a bit with reimplementing a simpler version of triehash in lua here https://github.com/bfredl/neovim/blob/stupidhash/src/nvim/generators/stupidhash.lua although my primary focus/motivation for this was more for simplifying option dict access code, I hope it might serve later on as a complete gperf replacement.

Though this will not be my primary focus the following time, so if you want to set up benchmarking for existing algorithms like gperh, bsearch etc, that would be a useful contribution :+1:

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/18544 thank you @bfredl !
