### ISSUE TITLE
expand('~') inside FocusGained,FocusLost autocmd forgets current wildmenu selection

### ISSUE THREAD

**Issue by mars90226** [neovim/neovim#10121]
- `nvim --version`: NVIM v0.4.0-941-g16ee24082
- Vim (version: ) behaves differently? Yes, no issue
- Operating system/version: Ubuntu 18.04 LTS
- Terminal name/version: MobaXterm 11.1, using tmux 2.8
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u minimal.vimrc`
cat minimal.vimrc
```
set wildmenu
set wildchar=<Tab>

augroup expand_in_focus_autocmd
  autocmd!
  autocmd FocusGained,FocusLost * call s:expand()
augroup END

function! s:expand()
  call expand('~')
endfunction
```

```
sudo -i
nvim -u minimal.vimrc
:h <Tab><Tab><Tab>
tmux-switching-other-pane
tmux-switching-back
<Tab>
```

### Actual behaviour
Select 2nd candidate.

### Expected behaviour
Select 4th candidate.

When executing neovim as root, calling `expand('~')` inside FocusGained,FocusLost autocmd will cause neovim lost current wildmenu selection.

**Comment by justinmk** [comment]
Thanks for the clear steps, but I can't reproduce. Tested on ubuntu with NVIM v0.4.0-937 db415bde5f1e

If root is required most likely it's configuration related, since root usually doesn't (correctly/fully) inherit your current environment.

If you find the root cause we can re-open.

**Comment by justinmk** [comment]
Can reproduce with 16ee24082f72

**Comment by gelguy** [comment]
https://github.com/neovim/neovim/blob/2e171a6fd163e0d74c80d21a893cb6a3c3394b1f/src/nvim/ex_getln.c#L3792

Calling `expand()` resets the static variable `findex`, so the current wildmenu index becomes 0.

Perhaps `expand_T` should store its own `findex`?

**Comment by mars90226** [comment]
I've tried to git bisect it already. But when I checkout to commit about 2018-02, neovim won't build. I've got following error. So I can only sure that this issue can be reproduced at least at [3d2f4154b1d5d0bb063951c830e009505bdce359](https://github.com/neovim/neovim/commit/3d2f4154b1d5d0bb063951c830e009505bdce359).
```
Error: Error fetching file: Failed downloading https://raw.githubusercontent.com/mpeterv/luacheck/master/luacheck-scm-1.rockspec - luacheck-scm-1.rockspec
```

My previous test show that normal user is not affect. But I'll tried to test it again later today.

**Comment by mars90226** [comment]
After I update my tmux plugin in normal user, I can reproduce this issue in normal user using `NVIM v0.2.3-776-g3d2f4154b`. So I think root is not required to reproduce this issue.

**Comment by justinmk** [comment]
> But when I checkout to commit about 2018-02, neovim won't build

If the problem is more than 1 year old, no need to bisect :) I had thought a recent change introduced the behavior.

**Comment by justinmk** [comment]
Confirmed on https://github.com/neovim/neovim/commit/338b9032194a4bc4c98439eb00f65a8ec86609f2

**Comment by ViViDboarder** [comment]
This seems to be happening for anyone using `nvim-lualine` along with `vim-fugitive` since an `expand('~')` call was added to vim-fugitive on Apr 13, 2022. Lualine updates on the `CursorMoved` autocommand when in the menu and the expand call results in the cursor resetting to the top.
