### ISSUE TITLE
The <C- h> doesnt work with this key map <C-w>h

### ISSUE THREAD

**Issue by taigacute** [neovim/neovim#10134]
- `nvim --version`:NVIM v0.4.0-945-g8e8c7d754
- Vim (version: ) behaves differently?N/A
- Operating system/version: macos 10.13.6
- Terminal name/version:iterm2 stable
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nnoremap <C-h> <C-w>h
```
1. use this minal init .vim 
2. open the nvim 
3. create two window left and right 
4. type `<C-h>`

### Actual behaviour
when i type the <C-h> ,i cant jump to the left window
### Expected behaviour
work well

**Comment by dcardamo** [comment]
I'm seeing this too.  I can reproduce on nightly but it works fine on 0.3.7.

**Comment by justinmk** [comment]
Can someone bisect to the exact commit that causes this?

**Comment by taigacute** [comment]
this version `NVIM v0.4.0-902-gb65a7b7f6` is work fine.

**Comment by justinmk** [comment]
> this version `NVIM v0.4.0-902-gb65a7b7f6` is work fine. `NVIM v0.4.0-964-gf6f9e4a23` also has this problem

Thanks for narrowing it down, would be most helpful if you narrow it down to 1 commit.

However it's strange that you say f6f9e4a23 does not have the problem; https://github.com/neovim/neovim/issues/10095 claims that c6cd6081b (an older commit) has a similar problem.

I can't reproduce any of these issues, using latest master.

**Comment by taigacute** [comment]
@justinmk    i got the same problem in `NVIM v0.4.0-945-g8e8c7d754`, maybe can help? i only have these version neovim.

**Comment by justinmk** [comment]
Thanks, that helps, but since I can't reproduce the issue I need someone to bisect it to the exact commit :)

**Comment by taigacute** [comment]
Yes, narrowing down is helpful for finding commits. It's strange why the master branch doesn't have this problem. I noticed that this problem exists in every recent release.

**Comment by justinmk** [comment]
@taigacute what do you mean by "release"? Are you using the nightly appimage? What about @dcardamo @Rubonnek ?

**Comment by taigacute** [comment]
@justinmk   i  got neovim nightly from this page https://github.com/neovim/neovim/releases/

**Comment by georgewitteman** [comment]
Also seeing this issue. It seems like `<C-h>` isn't working for any mappings.

**Comment by justinmk** [comment]
I can't reproduce the issue and still need someone to bisect to the exact commit.

**Comment by dcardamo** [comment]
I bisected it to this commit:
https://github.com/neovim/neovim/commit/402b4e8fbe32c2ee1de0c39ab84c43b600db0495

**Comment by justinmk** [comment]
does this patch help?

```diff
diff --git a/src/nvim/main.c b/src/nvim/main.c
index 8ff873e1279f..701201fef46c 100644
--- a/src/nvim/main.c
+++ b/src/nvim/main.c
@@ -354,6 +354,7 @@ int main(int argc, char **argv)
     if (use_remote_ui) {
       remote_ui_wait_for_attach();
     } else {
+      input_stop();  // Stop reading input, let the UI take over.
       ui_builtin_start();
     }
     TIME_MSG("done waiting for UI");
```

**Comment by dcardamo** [comment]
That didn't fix it.
I cloned the Neovim repo, ran make -j 128 to build.   then to start it "VIMRUNTIME=runtime ./build/bin/nvim".   I'm using mosh to get into the machine and then I run tmux.
I tried the same with just ssh (no tmux) and then running nvim from there and still didn't get success.

**Comment by dcardamo** [comment]
Its treating the CTRL-h has backspace in all conditions even though my mapping is "map <C-h> <C-w>h"

**Comment by dcardamo** [comment]
Here is patch against the commit that breaks C-h that makes it work again.  I don't know this code but wanted to narrow it down a bit more to what part of the patch broke it.
```diff --git a/src/nvim/main.c b/src/nvim/main.c
index 059b8762e..a919bd1f1 100644
--- a/src/nvim/main.c
+++ b/src/nvim/main.c
@@ -319,10 +319,15 @@ int main(int argc, char **argv)
   //
   // Read ex-commands if invoked with "-es".
   //
+    bool reading_tty = !headless_mode
+                            && !embedded_mode
+                            && !silent_mode
+                            && (params.input_isatty || params.output_isatty
+                                || params.err_isatty);
   bool reading_excmds = !params.input_isatty
                         && silent_mode
                         && exmode_active == EXMODE_NORMAL;
-  if (reading_excmds) {
+  if (reading_tty || reading_excmds) {
     int fd = STDIN_FILENO;
     input_start(fd);
   }
```

**Comment by bfredl** [comment]
@dcardamo Thanks! I tried to simulate the same behavior on master:
```diff
diff --git a/src/nvim/main.c b/src/nvim/main.c
index 8ff873e12..5dee129d7 100644
--- a/src/nvim/main.c
+++ b/src/nvim/main.c
@@ -354,6 +354,8 @@ int main(int argc, char **argv)
     if (use_remote_ui) {
       remote_ui_wait_for_attach();
     } else {
+      input_start(STDIN_FILENO);
+      input_stop();
       ui_builtin_start();
     }
     TIME_MSG("done waiting for UI");
```

And it works, but I don't understand why it works. All it does is to open and close a reading stream, before it opens the reading stream on the TUI thread (using the same `rstream.c` code on both threads).

**Comment by erw7** [comment]
> And it works, but I don't understand why it works. 

I'm sorry. The static variable `global_fd` was initialized in `input_start()`. Therefore, we need to call `input_start()` before calling `tui_get_stty_erase()` form `tui_tk_ti_getstr()[TermInput.tk_ti_hook_fn()]`.

https://github.com/neovim/neovim/blob/7612dd3f8a47e25d421ce7605a165f504e5fa5a4/src/nvim/os/input.c#L40
https://github.com/neovim/neovim/blob/7612dd3f8a47e25d421ce7605a165f504e5fa5a4/src/nvim/os/input.c#L59-L68
https://github.com/neovim/neovim/blob/7612dd3f8a47e25d421ce7605a165f504e5fa5a4/src/nvim/os/input.c#L53-L57
https://github.com/neovim/neovim/blob/7612dd3f8a47e25d421ce7605a165f504e5fa5a4/src/nvim/tui/tui.c#L1963-L1975
