### ISSUE TITLE
vimscript differences

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1014]
( @ZyX-I I know you have an issue open for vimscript incompatibilities, but this is a separate issue that I hope we can close pretty quickly. )

We have removed some obsolete VimL features such as `'textmode'` and `'textauto'`. But those are still highlighted by our [vimscript syntax](https://github.com/neovim/neovim/blob/master/runtime/syntax/vim.vim) file. 

We have three options (that I can think of):

1. remove the keywords from the syntax file.
    - if the user opens a `.vimrc`, those options won't be highlighted, even though *they are valid* in a `.vimrc`.
2. keep the keywords in the syntax file
    - then the invalid keywords are syntax-highlighted in a `.nvimrc` and Neovim `.vim` plugins, even though they are invalid in Neovim
3. write some clever `ftdetect` logic to distinguish between a Neovim `.vim` file and a Vim `.vim` file.

**Comment by dumblob** [comment]
Assuming these significant differences in *VimL* are described in *neovim* documentation, we shouldn't waste resources for maintaining highlighting for "old" *vim* files. Also it doesn't feel much *KISS* ;) . Anybody can very quickly reconstruct appropriate highlighting based on the documentation.

**Comment by justinmk** [comment]
We have de facto chosen option number **1**. So, closing this.
