### ISSUE TITLE
vim-patch.sh: less fuzzy?

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10143]
vim-patch.sh applied vim/vim@1ebff3dc9 with fuzz=2 to `ex_hide`, although it is for `do_sleep`:

```diff
diff --git i/src/nvim/ex_docmd.c w/src/nvim/ex_docmd.c
index f4082fc83..16476d4f8 100644
--- i/src/nvim/ex_docmd.c
+++ w/src/nvim/ex_docmd.c
@@ -6405,6 +6405,11 @@ static void ex_hide(exarg_T *eap)
             win_close(win, false);
         }
     }
+
+    // If CTRL-C was typed to interrupt the sleep, drop the CTRL-C from the
+    // input buffer, otherwise a following call to input() fails.
+    if (got_int)
+       (void)vpeekc();
 }

 /// ":stop" and ":suspend": Suspend Vim.
```

I think we should maybe use `--fuzz=0` (or `--fuzz=1`) with `patch` to be more strict here.  The default is 2.
But that might cause it to be less helpful, i.e. rejecting too many patches then.

What do you think?  Should patch authors just pay enough attention?

**Comment by justinmk** [comment]
> I think we should maybe use `--fuzz=0` (or `--fuzz=1`) with `patch` to be more strict here. The default is 2.

Let's try it. I think most people don't use `-P` (except me).

**Comment by blueyed** [comment]
Ok.

What do you think about having more context in the patches / diff also?  E.g. `-U5` with the git-show that generates the patch.

**Comment by justinmk** [comment]
We can try experimenting with that. I'd also like to remove `.rej` files automatically, they are useless.

**Comment by blueyed** [comment]
> I'd also like to remove .rej files automatically, they are useless.

I've found that it deletes `*.orig` automatically.. which is rather bad in case somebody would have a legitimate file by that name in the repo..!

`--reject-file=-` should be used then instead, but I am using those actually.

To not create `.orig` file I will change it to use `--version-control=never`, or maybe rather set it as default via `VERSION_CONTROL`.
