### ISSUE TITLE
vim-patch.sh: do not ignore everything from version.c

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10146]
It should not ignore the functional changes in vim/vim@5d69da462 (tag: v8.0.1739, tag: v8.0.1738).

Code ref: https://github.com/blueyed/neovim/blob/244c9e5c286be9d8976a5f3c84e5c6601ae06dfd/scripts/vim-patch.sh#L166-L168

(Ref: https://github.com/neovim/neovim/pull/7555/commits/23fb833ea75107a3349dfb0be2eeccc06111399c, #7555)

**Comment by justinmk** [comment]
version.c almost never has functional changes. I don't think it's worth the effort. The one time every 4 years that version.c has functional changes, one can just `:Gedit v8.1.xxx` on the vim repo to see the missing changes.

**Comment by blueyed** [comment]
Ok, closing then for now.
