### ISSUE TITLE
urxvt: always insert some text on startup

### ISSUE THREAD

**Issue by mzr1996** [neovim/neovim#10159]
- `nvim --version`:
0.4.0 only, installed by appimage or yaourt.
```
NVIM v0.4.0-964-gf6f9e4a23
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-b8b84ff4-b35e-442b-8065-8504a5437683

Features: +acl +iconv +tui 
```
- Vim (version: ) behaves differently?
- Operating system/version:
Manjaro / Linux kernel 4.19.45-1-MANJARO
- Terminal name/version:
Appears on:
```
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```
Doesn't appear on
```
xfce4-terminal 0.8.7.4 (Xfce 4.13)
```
- `$TERM`:
Appears on `rxvt-unicode-256color`
Does't appear on `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
If start by `nvim` or `nvim emptyfile`, it will insert text `:0000/2aff/35ff/cccc` and turn to insert mode;
If start by `nvim existsfile`, it will insert text `g:0000/2aff/35ff/cccc` at the file's beginning and turn to insert mode.
And I have to press `<ESC>` twice to escape this insert mode, while I just need to press once to escape insert mode later. 
This phenomenon seems to appear only on urxvt terminal.

After startup, it looks like this (the left is urxvt, and the right is xfce-terminal)
![图片](https://user-images.githubusercontent.com/26739999/59148063-3004d180-8a36-11e9-8b32-69c94f41016d.png)

**Comment by justinmk** [comment]
similar to https://github.com/neovim/neovim/issues/10131 . But I thought rxvt supported bg color detection? @blueyed are you using urxvt still?

**Comment by justinmk** [comment]
> $TERM:
> Appears on rxvt-unicode-256color
> Does't appear on xterm-256color

If the problem does _not_ occur with `TERM=xterm-256color` _while_ using rxvt, then maybe it's a terminfo problem.

**Comment by blueyed** [comment]
I am using Kitty mostly by now - urxvt only occasionally.

> But I thought rxvt supported bg color detection?

Only in CVS.

Here this is used:

> rxvt-unicode (urxvt) v9.22 - released: 2016-01-23

**Comment by blueyed** [comment]
@mzr1996 
You might want to try https://aur.archlinux.org/packages/rxvt-unicode-cvs/ or, or https://aur.archlinux.org/packages/rxvt-unicode-cvs-patched-wideglyphs/

**Comment by justinmk** [comment]
Thanks @blueyed . I guess we need to blacklist rxvt for bg-color detection. Patch welcome.

**Comment by mzr1996** [comment]
> @mzr1996
> You might want to try https://aur.archlinux.org/packages/rxvt-unicode-cvs/ or, or https://aur.archlinux.org/packages/rxvt-unicode-cvs-patched-wideglyphs/

Thanks for your suggestion, but the bug still exists after using whether `rxvt-unicode-cvs` or `rxvt-unicode-cvs-patched-wideglyphs`

**Comment by otreblan** [comment]
I have the same bug.
It inserts from `*background: rgba:xxxx/xxxx/xxxx/xxxx` from my `.Xdefaults`
![Screenshot_20190610_184327](https://user-images.githubusercontent.com/39320840/59234375-27390a80-8bb2-11e9-89b3-a37d91236509.png)
In the photo:
All are urxvt
The up left one is my `.Xdefaults`
The botom left one is neovim started on urxvt with transparency
And the right one is neovim started on urxvt without transparency "`*background: #000000`"

rxvt-unicode-cvs-patched-wideglyphs 20170412-7 from [https://aur.archlinux.org/packages/rxvt-unicode-cvs-patched-wideglyphs/](url)
neovim-nightly 1:0.4.0+20190609-1 from [https://aur.archlinux.org/packages/neovim-nightly/](url)

**Comment by mzr1996** [comment]
> 
> 
> I have the same bug.
> It inserts from `*background: rgba:xxxx/xxxx/xxxx/xxxx` from my `.Xdefaults`
> ![Screenshot_20190610_184327](https://user-images.githubusercontent.com/39320840/59234375-27390a80-8bb2-11e9-89b3-a37d91236509.png)
> In the photo:
> All are urxvt
> The up left one is my `.Xdefaults`
> The botom left one is neovim started on urxvt with transparency
> And the right one is neovim started on urxvt without transparency "`*background: #000000`"
> 
> rxvt-unicode-cvs-patched-wideglyphs 20170412-7 from [https://aur.archlinux.org/packages/rxvt-unicode-cvs-patched-wideglyphs/](url)
> neovim-nightly 1:0.4.0+20190609-1 from [https://aur.archlinux.org/packages/neovim-nightly/](url)

I see... It inputs `rgba:dddd/dddd/dddd/dddd` into the neovim.
The first `r` replace the first character with `g`,
and the fourth `a` start insert mode and insert `:dddd/dddd/dddd/dddd`

But why do I need two `<ESC>` to escape this insert mode?

**Comment by blueyed** [comment]
> It inserts from `*background: rgba:xxxx/xxxx/xxxx/xxxx` from my `.Xdefaults`

What do you have in your config exactly?

I've tried to reproduce this, but could not.

Did this start to happen with 6bd692765 for you? (merged in February)
Please try if reverting 298608f88 fixes it for you.

**Comment by otreblan** [comment]
> > It inserts from `*background: rgba:xxxx/xxxx/xxxx/xxxx` from my `.Xdefaults`
> 
> What do you have in your config exactly?
> 
> I've tried to reproduce this, but could not.
> 
> Did this start to happen with [6bd6927](https://github.com/neovim/neovim/commit/6bd6927656500c50787b16de1fadf1bc46b7aefa) for you? (merged in February)
> Please try if reverting [298608f](https://github.com/neovim/neovim/commit/298608f88c463705cfd6ee47035c049dbb1d9fa0) fixes it for you.

https://github.com/otreblan/dotfiles/blob/master/.Xdefaults

**Comment by mzr1996** [comment]
> > It inserts from `*background: rgba:xxxx/xxxx/xxxx/xxxx` from my `.Xdefaults`
> 
> What do you have in your config exactly?
> 
> I've tried to reproduce this, but could not.
> 
> Did this start to happen with [6bd6927](https://github.com/neovim/neovim/commit/6bd6927656500c50787b16de1fadf1bc46b7aefa) for you? (merged in February)
> Please try if reverting [298608f](https://github.com/neovim/neovim/commit/298608f88c463705cfd6ee47035c049dbb1d9fa0) fixes it for you.

Sorry, I can't build [298608f](https://github.com/neovim/neovim/commit/298608f88c463705cfd6ee47035c049dbb1d9fa0) due to the build error 
```
Error: Build error: Failed installing src/luacheck/stds.lua in /mnt/myDisk/VSproject/neovim/.deps/usr/lib/luarocks/rocks/luacheck/scm-1/lua/luacheck/stds.lua
```
I have built [6bd6927](https://github.com/neovim/neovim/commit/6bd6927656500c50787b16de1fadf1bc46b7aefa), and the bug exists.

I remove the `nvim` configuration directory and bug still exists, therefore I think it's nothing about the neovim configuration.

**Comment by mzr1996** [comment]
I just tried to change the configuration in `.Xresources`, and found that if the configuration of URxvt's background color contains alpha channel, the bug would appear.
```
 *background:           [80]#002b36      <--- Appear
```
```
 *background:           #002b36          
URxvt.background:       [80]#002b36      <--- Appear
```
```
 *background:           [80]#002b36          
URxvt.background:       #002b36          <--- Not appear
```

**Comment by HarmtH** [comment]
Can you paste the output of ```(sleep 1; echo -e '\x1b]11;?\x07') & cat > /dev/null``` on urxvt with/without alpha enabled?

**Comment by mzr1996** [comment]
> Can you paste the output of `(sleep 1; echo -e '\x1b]11;?\x07') & cat > /dev/null` on urxvt with/without alpha enabled?

```
[1] 31546

^[]11;rgba:0000/2aff/35ff/cccc^G[1]  + 31546 done       ( sleep 1; echo -e '\x1b]11;?\x07'; )
```

**Comment by HarmtH** [comment]
@mzr1996 can you try #10205?

**Comment by mzr1996** [comment]
> @mzr1996 can you try #10205?

Thank you! #10205 solved the bug.

PS: I tried to build #10205 and `master` but both failed with the error:
```
Error: Could not move /mnt/myDisk/project/neovim/.deps/usr/bin/busted to /mnt/myDisk/project/neovim/.deps/usr/bin/busted_2_0_rc11_0-busted: /mnt/myDisk/project/neovim/.deps/usr/bin/busted not found
make[3]: *** [CMakeFiles/busted.dir/build.make:61：usr/bin/busted] Error 1
make[3]: 离开目录“/mnt/myDisk/project/neovim/.deps”
make[2]: *** [CMakeFiles/Makefile2:231：CMakeFiles/busted.dir/all] Error  2
make[2]: 离开目录“/mnt/myDisk/project/neovim/.deps”
make[1]: *** [Makefile:84：all] Error  2
make[1]: 离开目录“/mnt/myDisk/project/neovim/.deps”
make: *** [Makefile:88：deps] Error  2
```

Therefore, I change the `.deps/CMakeFiles/busted.dir/build.make:61`  from
```
usr/bin/luarocks build busted 2.0.rc12-1 CC=/usr/bin/cc LD=/usr/bin/cc
```
to
```
usr/bin/luarocks build busted 2.0.rc11-0 CC=/usr/bin/cc LD=/usr/bin/cc
```
and then, I built successfully. I don't know if it is important so I think I need to tell you about it.

**Comment by blueyed** [comment]
@mzr1996 
Does building work after "make distclean"?
