### ISSUE TITLE
Slow build step: Generating .mo / linking C executable

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10160]
I am seeing delays during building nvim (using ninja), where it hangs either on `Generating zh_TW.UTF-8.mo` or `Linking C executable bin/nvim`, for ~30s.

`top` shows about ~25% of CPU then, and processes like "lto1-ltrans" or "as".

Is this related to gettext, and can this be skipped when building?

I also had the suspicion that the binary might be re-linked due to the Git hash having changed?!

Having to wait half a minute there gets a bit into the way when bisecting, and/or doing patches.

**Comment by jamessan** [comment]
Sounds like you're doing a release build with LTO enabled. If suggest using debug builds for bisecting, since the compiler doesn't need to waste time optimizing.

**Comment by justinmk** [comment]
> Sounds like you're doing a release build with LTO enabled

Yes, don't use `Release` or `RelWithDebInfo` for development builds, it enables LTO, which always takes a long time.

**Comment by blueyed** [comment]
Hmm, I have `CMAKE_BUILD_TYPE := Debug` in local.mk, but it might have been after configuring CMake.
Thanks for the info, hopefully it is fast now again.
