### ISSUE TITLE
Artifacts in terminal

### ISSUE THREAD

**Issue by mcepl** [neovim/neovim#10167]
- `nvim --version`: build from commit 69b3d5acd
- Vim (version: ) behaves differently?
- Operating system/version: Linux openSUSE/Tumbleweed (rolling distro)
- Terminal name/version: gnome-terminal 3.32.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
I don't know about a foolproof way how to reproduce this. Most likely it is something done in cooperation with LSP (using https://github.com/bfredl/nvim-lspmirror and Python LSP server https://github.com/palantir/python-language-server), but when I work in neovim's terminal for some time (be it in neovim-gtk or neovim running in gnome-terminal) I get artifacts like this on the screen. The following is from neovim-gtk (where I previously mistakenly files this as issue https://github.com/daa84/neovim-gtk/issues/192):

![Snímek z 2019-04-25 17-47-54](https://user-images.githubusercontent.com/198999/56752042-b7003200-6787-11e9-8a55-0d9ba583aace.png)

However, today I was able to reproduce this even with plain neovim in gnome-termianl:

![Snímek z 2019-06-08 08-42-16](https://user-images.githubusercontent.com/198999/59143260-5fc9c000-89c9-11e9-88b4-fb61a6bda667.png)

Is there some way how to avoid these artifacts?

Thank you.

**Comment by bfredl** [comment]
Changes are this is caused by the LSP client (#6856). It might call `onDiagnostics` callback some time after current buffer has been switched, so the virtual text is added to the wrong buffer. The LSP client should probably add the bufnr to all callbacks, so this can be done correctly.

**Comment by mcepl** [comment]
I haven’t seen this for a long time.
