### ISSUE TITLE
tmux-256color configuration is not fully compatible with v0.3.7

### ISSUE THREAD

**Issue by EdmundsEcho** [neovim/neovim#10166]
- `nvim --version`: 0.3.7
- Vim (version: ) behaves differently?
- Operating system/version: 10.14.5
- Terminal name/version: iTerm2 3.2.9
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`
brew upgrade neovim (June 6th, 2019)
open nvim

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
grey background for one column at the end of each line

### Expected behaviour
background that matches the rest of the active window

Note: I solve the problem by replacing  `tmux-254color` with `screen-256color`

**Comment by justinmk** [comment]
> Note: I solve the problem by replacing `tmux-254color` with `screen-256color`

Maybe a terminfo issue with macOS. Our builtin terminfo definitions are generated from ncurses.
