### ISSUE TITLE
nvim HEAD no longer compiles on macOS

### ISSUE THREAD

**Issue by cvlmtg** [neovim/neovim#10181]
I suspect this might be because of c83926c, up until 7612dd3 it compiled fine.

- `nvim --version`:

0.4.0 6fe430f

- Vim (version: ) behaves differently?

does not apply

- Operating system/version:

macOS 10.14.5

- Terminal name/version:

kitty 0.14.2

- `$TERM`:

xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
brew install --HEAD neovim
```

### Actual behaviour

==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBU
Last 15 lines from /Users/matteo/Library/Logs/Homebrew/neovim/21.cmake:
   used as include directory in directory /tmp/neovim-20190611-62860-a569wp/runtime
   used as include directory in directory /tmp/neovim-20190611-62860-a569wp/runtime
   used as include directory in directory /tmp/neovim-20190611-62860-a569wp/runtime
   used as include directory in directory /tmp/neovim-20190611-62860-a569wp/runtime
   used as include directory in directory /tmp/neovim-20190611-62860-a569wp/runtime
   used as include directory in directory /tmp/neovim-20190611-62860-a569wp/runtime
   used as include directory in directory /tmp/neovim-20190611-62860-a569wp/runtime
LIBLUV_LIBRARY (ADVANCED)
    linked by target "libnvim" in directory /tmp/neovim-20190611-62860-a569wp/src/nvim
    linked by target "nvim-test" in directory /tmp/neovim-20190611-62860-a569wp/src/nvim
    linked by target "nvim" in directory /tmp/neovim-20190611-62860-a569wp/src/nvim
-- Configuring incomplete, errors occurred!
See also "/tmp/neovim-20190611-62860-a569wp/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/neovim-20190611-62860-a569wp/build/CMakeFiles/CMakeError.log".

 ~ cat /tmp/neovim-20190611-62860-a569wp/build/CMakeFiles/CMakeOutput.log
cat: /tmp/neovim-20190611-62860-a569wp/build/CMakeFiles/CMakeOutput.log: No such file or directory

 ~ cat /tmp/neovim-20190611-62860-a569wp/build/CMakeFiles/CMakeError.log
cat: /tmp/neovim-20190611-62860-a569wp/build/CMakeFiles/CMakeError.log: No such file or directory

**Comment by nifoc** [comment]
The actual error seems to be with `LIBLUV_INCLUDE_DIR` and possibly `LIBLUV_LIBRARY`:

```
-- Installing: /private/tmp/neovim-20190611-65596-vmasih/deps-build/lib/luarocks/rocks-5.1/luv/1.9.1-1/lib/luv.so

luv 1.9.1-1 is now installed in /private/tmp/neovim-20190611-65596-vmasih/deps-build (license: Apache 2.0)
[…]
-- Could NOT find libluv (missing: LIBLUV_LIBRARY LIBLUV_INCLUDE_DIR)
[…]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBLUV_INCLUDE_DIR (ADVANCED)
```

**Comment by justinmk** [comment]
see https://github.com/Homebrew/homebrew-core/issues/40854#issuecomment-500504444

We require the latest version of [luv](https://github.com/luvit/luv/). They added a new dependency on [lua-compat](https://github.com/keplerproject/lua-compat-5.3/) so now we also require that.

It's worth the trouble, though: Nvim now exposes the full features of libuv to script authors.

**Comment by lewis6991** [comment]
> We require the latest version of luv. They added a new dependency on lua-compat so now we also require that.

Shouldn't this new dependency be added to the brew formula for neovim?

**Comment by justinmk** [comment]
> Shouldn't this new dependency be added to the brew formula for neovim?

Indeed it should. But they may be waiting for Nvim to publish a stable release with this new dependency. Although, it would make sense to start looking at that ahead of time, to avoid delay because Nvim release and homebrew update.

**Comment by lewis6991** [comment]
Ok thanks.

Is one free to submit a PR to homebrew-core to fix this?

**Comment by telemachus** [comment]
For what it's worth, I tried (locally) adding the new dependency to the brew formula, but it still failed to build. I haven't yet had time to figure out what else may be going wrong, but it may not be as easy as just adding the one dependency.

**Comment by nerdrew** [comment]
> For what it's worth, I tried (locally) adding the new dependency to the brew formula, but `brew install --HEAD neovim` still failed to build. I haven't yet had time to figure out what else may be going wrong, but it may not be as easy as just adding the one dependency.

Do you have a diff of what you tried?

**Comment by telemachus** [comment]
> Do you have a diff of what you tried?

I don't, but it wasn't anything fancy. As I recall, I added this before `resource "luv"` etc.

```
resource "lua-compat" do
  url "https://luarocks.org/manifests/siffiejoe/compat53-0.7-1.src.rock"
  sha256 ""                                                               
end
```

(The sha is optional: you get a warning if you don't include it, but that won't make the build fail. Also, as part of the warning, `brew` will tell you what sha you need. If this had worked, I would have added the sha then.)

**Comment by thornomad** [comment]
Is there a workaround using `brew` or `luarocks` that can get HEAD working again via homebrew?  Or do we have to compile `neovim` from source at this point (this is something I have not tried yet)?  

I tried to install the latest version of`luv` via:

```luarocks install luv```

I also tried installing `luvit` via `brew` just on a whim.  Neither fixed the problem. 

Happened to grab a new laptop the last few days and I miss my neovim 0.4 !

**Comment by telemachus** [comment]
@thornomad 

> Or do we have to compile neovim from source at this point (this is something I have not tried yet)?

I gave up today and built neovim from source. It was pretty straightforward, although look out for this issue. The solution for me was [this comment](https://github.com/neovim/neovim/issues/9050#issuecomment-424417456).

**Comment by lewis6991** [comment]
I gave up too and just installed from source.

Would it not be possible to add brew install --HEAD to CI in some capacity?

**Comment by KillTheMule** [comment]
> Would it not be possible to add brew install --HEAD to CI in some capacity?

Probably. But I don't think we want that, it would mean CI would break everytime brew gets behind, which isn't appropriate (at least for HEAD). Also CI times are large enough already. I think you'll just have to live with the fact that `brew install --HEAD` is unsupported by both brew an neovim.

**Comment by nerdrew** [comment]
The neovim source install works just fine. Should we just change the `brew install --HEAD` to use neovim's source install and let it download it's own dependencies instead of trying to install all the lua-rocks, etc via the homebrew formula?

**Comment by telemachus** [comment]
@nerdrew I had the same thought, but there may be reasons why the brew team prefers to do it their way. In any case, we should probably take that question up [on the brew thread about this issue, rather than here](https://github.com/Homebrew/homebrew-core/issues/40854) since the brew maintainers have to decide this rather than the neovim maintainers.

**Comment by markwu** [comment]
Should luv version required inside FindLibLUV.cmake 1.29.1 or 1.9.1?  It is 1.9.1-1 inside neovim formula.

I try to set LIBLUV_LIBRARY and LIBLUV_INCLUDE_DIR directly, the library can found, but luv.h still missing.

**Comment by justinmk** [comment]
Indeed, see https://github.com/neovim/neovim/issues/10181#issuecomment-500749344

**Comment by nerdrew** [comment]
cc this thead: tl;dr would a homebrew cask allow homebrew to use the existing neovim releases for stable and nightly? Thoughts on moving to a cask rather than a formula?

https://github.com/Homebrew/homebrew-core/issues/40854#issuecomment-502932777
