### ISSUE TITLE
Stretch cursor to character width under it

### ISSUE THREAD

**Issue by ratheesh** [neovim/neovim#10194]
Is it possible to stretch the cursor(through an option) to the character width under it? It is useful when the user is navigating tab indented file.
This feature is present in `emacs`(x-stretch-cursor) and `kakoune`

**Comment by justinmk** [comment]
can you give a screenshot and/or links to the documentation/demo of these features in kakoune/emacs?

**Comment by KillTheMule** [comment]
Sounds like that could be done with a small plugin to me. Use https://neovim.io/doc/user/api.html#nvim_buf_add_highlight() with data from https://neovim.io/doc/user/eval.html#strdisplaywidth().

**Comment by ratheesh** [comment]
**Emacs**
`Documentation` https://www.gnu.org/software/emacs/manual/html_node/elisp/Cursor-Parameters.html

**Kakoune**
`Github Issue`  https://github.com/mawww/kakoune/issues/2788
`Screenshot`

![kak_cursor](https://user-images.githubusercontent.com/70958/59333809-be1ed780-8d16-11e9-8994-d879f6f4c944.jpg)

**Comment by justinmk** [comment]
Besides what @KillTheMule said, the "cursor" in that kakoune image is not a real cursor. That's relevant for people who expect their terminal settings to apply to the cursor. Non-GUI Emacs would need to use the same hack if it works at all.

https://github.com/neovim/neovim/issues/7488 is a similar issue that proposes display of a "fake cursor" which can be completely controlled by Nvim.

**Comment by justinmk** [comment]
This can be achieved with this script:

```vim
highlight FancyCursor ctermbg=red guibg=red
func! Fancy_cursor() abort
  let g:fancy_cursor = get(g:,'fancy_cursor',{'buf':-1,'ns':-1})
  let d = g:fancy_cursor
  if get(d,'buf',-1) != -1
    call nvim_buf_clear_namespace(d.buf,d.ns,0,-1)
  endif
  let d.buf = bufnr('%')
  let d.ns = nvim_buf_add_highlight(bufnr('%'), 0, 'FancyCursor', (line('.')-1), col('.')-1, col('.'))
endfunc
augroup fancy_cursor
  autocmd!
  autocmd CursorMoved,CursorMovedI * call Fancy_cursor()
augroup END
```

**Comment by ratheesh** [comment]
Thanks @justinmk .
I got following error
![fancy_cursor_error](https://user-images.githubusercontent.com/70958/60063837-e3024a00-971b-11e9-919b-c16d8bc95a68.jpg)

I am using neovim built@`69eb4fa0c5a4e8b039b177f556f57614b6acb422`

**Comment by ratheesh** [comment]
When I tried minimal init with your changes. It works fine.
I will debug my vimrc

Thank you very much for the support
