### ISSUE TITLE
does nvim float win support relative current window

### ISSUE THREAD

**Issue by fgheng** [neovim/neovim#10193]
- `nvim --version`:NVIM v0.4.0-1012-gf8d0e41b2
- Vim (version: ) behaves differently?yes
- Operating system/version:arch linux
- Terminal name/version: tilix
- `$TERM`:xterm-256color

hello, i have two questions.

the one is whether neovim's float window support relative current window?

And the second is why getwinposx() and getwinposy() always return -1?

thank you very much

**Comment by justinmk** [comment]
Note the `relative` key of the `{config}` parameter described at `:help nvim_open_win()`.

**Comment by fgheng** [comment]
oh, it is support relative window,

> Note the `relative` key of the `{config}` parameter described at `:help nvim_open_win()`.

thank you, i know the value is 'win', thank you very much. i used neovim stable version 0.37 before and i want to try the float window so i download the 0.4 version and copy nvim to /usr/bin, so it has no help of nvim_open_win(). but now i know how to use it, thank you very much

And i do not know how to solve the second question, getwinposx() always return -1

**Comment by justinmk** [comment]
> so i download the 0.4 version and copy nvim to /usr/bin, so it has no help of nvim_open_win(). 

If you don't install the runtime then yes, there are no help files. You need to point `VIMRUNTIME` to the `runtime/` directory (which is included in the release downloads).

**Comment by fgheng** [comment]
> > so i download the 0.4 version and copy nvim to /usr/bin, so it has no help of nvim_open_win().
> 
> If you don't install the runtime then yes, there are no help files. You need to point `VIMRUNTIME` to the `runtime/` directory (which is included in the release downloads).

i put `let $VIMRUNTIME="/path/to/runtime/which/i/download"` into my neovim config, but it still no help info of nvim_open_win()
