### ISSUE TITLE
ci: AppVeyor: disable rolling builds (for master)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10199]
Doc: https://www.appveyor.com/docs/build-configuration/#rolling-builds

This should be disabled for branch builds (master), since it is crucial to know if builds passed there, and also relevant for base coverage for PRs.

I wanted to check if a test passed when merging a PR, or if it was failing from the beginning, but the build was canceled (https://ci.appveyor.com/project/neovim/neovim/builds/23549241).

**Comment by justinmk** [comment]
I am talking about the master branch. It already gets behind by 24 hours sometimes.

**Comment by blueyed** [comment]
Oh...

How about having only the following builds then there?
```
- MSVC_64
- MINGW_32-gcov
```

instead of
```
- MSVC_64
- MSVC_32
- MINGW_64
- MINGW_32
- MINGW_64-gcov
```

(I've read that MinGW is 32bit only anyway?!)

**Comment by justinmk** [comment]
On master? We want all of the builds on master, otherwise they serve no purpose.

**Comment by blueyed** [comment]
Not in general (sorry, lost a longer answer).

See https://github.com/neovim/neovim/pull/10217 for removing one job.

Also note that MINGW builds appear to be twice as fast as MSVC (14m vs 7m; https://ci.appveyor.com/project/neovim/neovim/builds/25257037).

We might also want to consider using Azure DevOps - we've switched over to them from AppVeyor with pytest, and they are rather fast (parallel builds).

**Comment by justinmk** [comment]
This is really a low priority.

> We might also want to consider using Azure DevOps - we've switched over to them from AppVeyor with pytest, and they are rather fast (parallel builds).

Yes that is a good option. But's it very low priority for the next 12 months.

**Comment by blueyed** [comment]
Ok.

Added fast_finish in https://github.com/neovim/neovim/pull/10216/commits/3b5cef18cb5117f5cdf64b05c3ef1befd765de23.

Is it possible after all to control rolling builds for branches differently than PRs?
