### ISSUE TITLE
ci: Travis: enable ccache in general

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10204]
In https://github.com/neovim/neovim/pull/8333 it was enabled for OSX builds.

I think it would be good to have in general.

(If not, it should probably have some comment about this in .travis.yml anyway (currently it is hidden in an `if` in `ci/install.sh`.)

**Comment by jamessan** [comment]
> In #8333 it was enabled for OSX builds.

It was enabled for all builds, not just OSX.

The `ccache: true` [line](https://github.com/neovim/neovim/blob/6f27f5ef91b3eeeca9fe58f4033e3d273ccc0889/.travis.yml#L134) handles that for Linux builds.  OSX just needs to have ccache explicitly installed.

You can see this in the [Travis logs](https://travis-ci.org/neovim/neovim/jobs/545198642#L8274-L8290).

**Comment by blueyed** [comment]
I see, thanks.
For reference: https://docs.travis-ci.com/user/caching/#ccache-cache

**Comment by blueyed** [comment]
Could/should be done for Appveyor though maybe also.

**Comment by justinmk** [comment]
Appveyor cache is very tricky. Could be a big time-sink.

**Comment by blueyed** [comment]
Found this from the Inkscape project: https://gitlab.com/inkscape/inkscape/blob/master/buildtools/appveyor.sh

(but do not plan to work on this currently)
