### ISSUE TITLE
flaky test: "search highlighting is preserved during :terminal activity" might fail

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10214]
[  ERROR   ] ...d/neovim/neovim/test/functional/ui/searchhl_spec.lua @ 150: search highlighting is preserved during :terminal activity
    test/functional/ui/screen.lua:554: Row 1 did not match.
    Expected:
      |*  {3:foo} bar baz       {3:│}                   |
      |  bar baz {2:foo}       {3:│}                   |
      |  bar {2:foo} baz       {3:│}                   |
      |                    {3:│}                   |
      |{1:~                   }{3:│}                   |
      |{5:[No Name] [+]        }{3:term               }|
      |/foo^                                    |
    Actual:
      |*  {3:foo} bar baz       {3:│}xxx                |
      |  bar baz {2:foo}       {3:│}                   |
      |  bar {2:foo} baz       {3:│}                   |
      |                    {3:│}                   |
      |{1:~                   }{3:│}                   |
      |{5:[No Name] [+]        }{3:term               }|
      |/foo^                                    |
    To print the expect() call that would assert the current screen state, use
    screen:snapshot_util(). In case of non-deterministic failures, use
    screen:redraw_debug() to show all intermediate screen states.  
    stack traceback:
            test/functional/ui/screen.lua:554: in function '_wait'
            test/functional/ui/screen.lua:366: in function 'expect'
            ...d/neovim/neovim/test/functional/ui/searchhl_spec.lua:168: in function <...d/neovim/neovim/test/functional/ui/searchhl_spec.lua:150>

Does this indicate an issue with 5020daa6e?
/cc @bfredl

_Originally posted by @blueyed in https://github.com/neovim/neovim/pull/10205#issuecomment-501670360_

**Comment by blueyed** [comment]
Happened again: https://travis-ci.org/neovim/neovim/jobs/546006824

**Comment by bfredl** [comment]
The search highlighting is preserved in both cases, so it seems to be fine. The problem is just that there no longer is a unique final state for the terminal window, as the test was designed for. Pehaps the the test could be replaced by the two quasi-deterministic cases:

1. type `/`, send all terminal output, then sleep(50), then type `abc` (terminal output should be visible)
2. type `/abc`, send terminal output, expect() with increased timeout (no terminal output visible)

**Comment by blueyed** [comment]
Here line 2 did not match:
```
[ RUN      ] search highlighting is preserved during :terminal activity: ERR
test/functional/ui/screen.lua:554: Row 2 did not match.
Expected:
  |  {3:foo} bar baz       {3:│}                   |
  |*  bar baz {2:foo}       {3:│}                   |
  |  bar {2:foo} baz       {3:│}                   |
  |                    {3:│}                   |
  |{1:~                   }{3:│}                   |
  |{5:[No Name] [+]        }{3:term               }|
  |/foo^                                    |
Actual:
  |  {3:foo} bar baz       {3:│}                   |
  |*  bar baz {2:foo}       {3:│}xxx                |
  |  bar {2:foo} baz       {3:│}xxx                |
  |                    {3:│}xxx                |
  |{1:~                   }{3:│}xxx                |
  |{5:[No Name] [+]        }{3:term               }|
  |/foo^                                    |
To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  
stack traceback:
	test/functional/ui/screen.lua:554: in function '_wait'
	test/functional/ui/screen.lua:366: in function 'expect'
	...d/neovim/neovim/test/functional/ui/searchhl_spec.lua:168: in function <...d/neovim/neovim/test/functional/ui/searchhl_spec.lua:150>
```

**Comment by blueyed** [comment]
The problem with the flakyness on Travis/osx is that there is output already from the terminal before cmdline gets started.

@bfredl 
As for your plan, how should "send all terminal output" be achieved?
As far as I can see the terminal needs to be started/running already (i.e. it cannot be started from e.g. a (Vimscript) timer function, waiting for `mode() ==# 'c'`, can it?)

In any case it should/could use `nvim('set_option', 'shell', helpers.nvim_dir .. '/shell-test REP 5000 xxx')` here.

**Comment by bfredl** [comment]
Sure, terminal needs to be set up ahead of time, otherwise the test is pretty meaningless (or at least, split window is a very different event from async buffer update). But the helper process can accept some token that is send via `funcs.chansend(job, "x\n")` to send the output at a certain time. Or maybe at that point we can just use interactive `cat` in the terminal, to echo text from chansend back.

**Comment by blueyed** [comment]
ok, then `build/bin/shell-test INTERACT` could be used maybe:

```
interact $ asdf
command not found: asdf
interact $ exit
```

(or only "exit" directly)

**Comment by blueyed** [comment]
6b45e12 addressed and likely fixed this, closing for now.

**Comment by blueyed** [comment]
This might need similar treatmeant - might even have started to become only flaky recently (and happened at least once also with the gcov job (i.e. not only on osx)).

I've started to look into it yesterday, but wanted to create a reference already.]

```
[  ERROR   ] test/functional/ui/inccommand_spec.lua @ 2549: :substitute with inccommand during :terminal activity
test/functional/helpers.lua:392: 
retry() attempts: 2
test/functional/ui/screen.lua:579: Row 8 did not match.
Expected:
  |bar baz fox                   |
  |bar foo ba^z                   |
  |{15:~                             }|
  |{15:~                             }|
  |{15:~                             }|
  |{15:~                             }|
  |{11:[No Name] [+]                 }|
  |*xxx                           |
  |xxx                           |
  |xxx                           |
  |xxx                           |
  |xxx                           |
  |xxx                           |
  |{10:term                          }|
  |                              |
Actual:
  |bar baz fox                   |
  |bar foo ba^z                   |
  |{15:~                             }|
  |{15:~                             }|
  |{15:~                             }|
  |{15:~                             }|
  |{11:[No Name] [+]                 }|
  |*                              |
  |                              |
  |                              |
  |                              |
  |                              |
  |                              |
  |{10:term                          }|
  |                              |
To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  
stack traceback:
	test/functional/helpers.lua:392: in function 'retry'
	test/functional/ui/inccommand_spec.lua:2553: in function <test/functional/ui/inccommand_spec.lua:2549>
```

**Comment by justinmk** [comment]
> This might need similar treatmeant - might even have started to become only flaky recently (and happened at least once also with the gcov job (i.e. not only on osx)).

No, that's an old one :)

**Comment by blueyed** [comment]
ok, phew.. :)  (something at least :D)
