### ISSUE TITLE
ci: looping in "Re-running CMake..." / "ninja: error: manifest 'build.ninja' still dirty after 100 tries"

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10213]
Builds on Travis might fail to run cmake (https://travis-ci.org/neovim/neovim/jobs/545198646):

```
ci/before_script.sh
cache directory                     /Users/travis/.ccache
primary config                      /Users/travis/.ccache/ccache.conf
secondary config      (readonly)    /usr/local/Cellar/ccache/3.7.1/etc/ccache.conf
stats updated                       Thu Jun 13 12:18:08 2019
cache hit (direct)                   480
cache hit (preprocessed)               0
cache miss                            94
cache hit rate                     83.62 %
called for link                      123
called for preprocessing              82
autoconf compile/link                328
cleanups performed                     0
files in cache                       230
cache size                          10.5 MB
max cache size                       5.0 GB
Using third-party dependencies from Travis cache (last update: Jun 12 23:18:33 2019).
Configuring with '-DDEPS_DOWNLOAD_DIR:PATH=/Users/travis/build/neovim/neovim/deps-downloads -DUSE_BUNDLED_GPERF=OFF'.
-- Found GNU Make at /usr/bin/make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/travis/nvim-deps
==============================================================================
[0/1] Re-running CMake...
-- Found GNU Make at /usr/bin/make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/travis/nvim-deps
[0/1] Re-running CMake...
-- Found GNU Make at /usr/bin/make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/travis/nvim-deps
[0/1] Re-running CMake...
-- Found GNU Make at /usr/bin/make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/travis/nvim-deps
ninja: error: manifest 'build.ninja' still dirty after 100 tries
The command "ci/before_script.sh" failed and exited with 1 during .
```

Only have seen this with OSX builds on Travis, and restarting them might fix it then.
With https://travis-ci.org/neovim/neovim/builds/545198641 both OSX jobs failed due to this - I've restarted one of them.

**Comment by justinmk** [comment]
Known issue. Happens sometimes since I switched the builds to use `ninja`.

**Comment by blueyed** [comment]
Any idea about what's causing it?

Happened again: https://travis-ci.org/neovim/neovim/jobs/545219544

**Comment by blueyed** [comment]
And in https://travis-ci.org/neovim/neovim/jobs/545388412 - might it be related to caches on Travis?
Until now it only seems to affect OSX, so might also be due to the Ninja version then maybe.

**Comment by blueyed** [comment]
> Known issue. Happens sometimes since I switched the builds to use `ninja`.

Can we revert this then, and figure out in an enabling PR what is causing it?
(it is really bad to have flaky builds!)

**Comment by justinmk** [comment]
Flakey builds are bad but this is a Travis macos issue. It never happens locally nor on linux. If azure supports macos then maybe that's a reason to spend time on azure. 

Alternatively maybe avoid ninja on the macos builds. But not linux .

**Comment by blueyed** [comment]
Can we upgrade the image there maybe, i.e. use a newer Xcode?

**Comment by justinmk** [comment]
No objection, but it's probably only going to cause more problems. We upgraded macOS image a few months ago, and it made things worse.

**Comment by justinmk** [comment]
Seems like this isn't happening anymore?

**Comment by blueyed** [comment]
I've seen it (yesterday or the day before)..  therefore I've linked #10319 to track if it would fix it.

**Comment by blueyed** [comment]
Due to https://github.com/ninja-build/ninja/issues/1595 likely btw.
If it happens again we could use `ninja -d explain`, but likely the cache issue triggered this.

**Comment by alankdkd** [comment]
> "Flakey builds are bad but this is a Travis macos issue. It never happens locally nor on linux."

Wrong.  It's happening on Linux RIGHT NOW.  Googling shows this bug happens for dozens if not hundreds of people.  What a flaky utility!

**Comment by blueyed** [comment]
@alankdkd 
See https://github.com/ninja-build/ninja/issues/1595.  Is that your problem?
Try `ninja -C build -d explain` (if it is for the build dir).

**Comment by Ankele** [comment]
buggy ninja,,,

**Comment by blueyed** [comment]
Please consider commenting (constructively) at the Ninja issue instead.
