### ISSUE TITLE
API/UI: Externalize movement/keybinding indicator

### ISSUE THREAD

**Issue by badosu** [neovim/neovim#10219]
I noticed a bit of confusion with the command indicator on the bottom right section of neovim.

The confusion is mostly to the fact that single keystroke movements (h, j, k, l) are sent to be drawn in that section, which causes flickering when they are held and that it is presented without any indication of its purpose. See: https://github.com/vhakulinen/gnvim/issues/53

It seems like a good candidate for externalizing, self-contained, and enables a nice feature e.g. optionally presenting current movement/composite keybinding on a separate GUI section.

**Comment by bfredl** [comment]
Showcmd can already externalized, use `ext_messages`. 

The linked issue seems to be a separate bug: that nvim sometimes puts the cursor in the showcmd area. From what I can see, if `redrawing()` is false when `display_showcmd()` is called, the cursor will not be properly restored. We can fix that.

**Comment by badosu** [comment]
Was not aware of that, thanks!
