### ISSUE TITLE
jobstart behaves differently than running the command in command line

### ISSUE THREAD

**Issue by ipod825** [neovim/neovim#10210]
- `nvim --version`: NVIM v0.4.0-819-g66d127957
- Operating system/version: 5.1.7-arch1-1-ARCH

### Steps to reproduce using `nvim -u NORC`
First run in command line:

mkdir foo; cd foo; touch a; chmod u-w a

```
nvim -u NORC
:call jobstart('rm a', {'on_stdout':{j,d,e-> append(line('.'),d)}})
:!ls
```

### Actual behaviour
The file `a` is deleted without any output being append to the current buffer.

### Expected behaviour
Because the file a is write protected, `rm` prompts `rm: remove write-protected regular empty file 
'a'?` in the command line, while it didn't trigger the `on_stdout` with this prompt.

**Comment by ipod825** [comment]
Same issue in [vim](https://github.com/vim/vim/issues/4529)

**Comment by blueyed** [comment]
This is due to `rm` behaving differently without stdin:

```console
% touch a
% chmod 444 a
% rm a
rm: remove write-protected regular empty file 'a'? n
% rm a </dev/null
```

**Comment by blueyed** [comment]
Yeah, with the following you'll see the prompt:
```vim
call jobstart('rm a', {
      \ 'on_stdout':{j,d,e-> append(line('.'),d)},
      \ 'pty': 1,
      \ })
```

**Comment by justinmk** [comment]
see https://github.com/vim/vim/issues/4529#issuecomment-501997961
