### ISSUE TITLE
autocmd TextYankPost shoots before all registers are set

### ISSUE THREAD

**Issue by hgiesel** [neovim/neovim#10225]
- `NVIM v0.3.7
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/build/config -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/build/src/nvim/auto -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.7/share/nvim"`:
- Vim (version: ) behaves differently? Yes, it does the expected behavior.
- Operating system/version: macOS 10.14.5
- Terminal name/version: GNU bash, version 5.0.7(1)-release (x86_64-apple-darwin18.5.0)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```bash
nvim -u NORC -c 'source a.vim'
```

Content of a.vim:
```vim
function! s:Foo()
  if getreg('"') ==# getreg('0')
    echomsg 'You just yanked'

  elseif getreg('"') ==# getreg('-')
    echomsg 'You just small deleted / or small changed'

  elseif getreg('"') ==# getreg('1')
    echomsg 'You just big deleted / or big changed'
  endif
endfunction

autocmd TextYankPost * call s:Foo()
```

Now I write a few lines of text and execute `"adj`

### Actual behaviour

Nothing is echoed on my cmdline.

### Expected behaviour

"You just big deleted / or big changed" is echoed on my cmdline.

Querying the register contents in `s:Foo` shows me that by the time the autocmd shoots `"a` and `""` are already set, but `"1` seems only to bet set after  `s:Foo` finished. I expected to have all `""`, `"a`, and `"1` to be correctly set in the function.

**Comment by blueyed** [comment]
> * Vim (version: ) behaves differently? /

Have you checked how this behaves in Vim?

**Comment by bfredl** [comment]
Use `v:event` to access the name and contents of the yank within the autocmd. This is documented at `:help TextYankPost` (and is the same in vim).

**Comment by hgiesel** [comment]
I just tested with vim, and it does the expected behavior. It sets all `""`, `"a`, and `"1` correctly by the time the autocmd shoots.

**Comment by blueyed** [comment]
@bfredl 
Apparently Vim behaves differently.  Do you have some insights?

**Comment by bfredl** [comment]
The autocmd should get all the relevant information of the yank using `v:event`, without needing to read back any register.  `v:event.operator` will already distinguish between yanks and deletes. Perhaps we need to add a flag to distinguish between "small" and "big" deletes (or deletes that are both, which can happen with five designated normal commands).

Also looking at the code, the autocmd is fired after the yank. It wouldn't be possible otherwise as the implementation reads from the register (`"1` or `"-` for a delete). If there is a difference from vim it must be elsewhere.
