### ISSUE TITLE
:reg command should also show register types

### ISSUE THREAD

**Issue by aybberk** [neovim/neovim#10235]
Getting the type of a register is cumbersome with :call getregtype('a'). Instead, 
:reg command should also show whether the register is linewise or characterwise since the paste behavior is directly dependent to this and it's not clear just from register content. ^J at the and only gives an hint but not explanatory. 

For example, the behavior of these apparently identical registers would be vastly different when it comes to pasting.
:reg 
"a foo
"b foo

Instead, it should show

:reg
"a foo (V)
"b foo (v)

or for terseness, only linewise registers can be shown with extra mark (V).

:reg
"a foo (V)
"b foo

**Comment by bfredl** [comment]
Discussion at https://github.com/vim/vim/issues/4546
