### ISSUE TITLE
coverage: also upload to coveralls

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10242]
In https://github.com/neovim/neovim/issues/7162 coveralls was replaced with codecov.

I think we should upload to both providers, which would be easy after https://github.com/neovim/neovim/pull/10201.

This allows to ensure stable coverage regardless of provider specific issues, i.e. currently it is not clear if codecov's reported coverage dropped because of removing flags, or because of gcov jobs not being run due to previous flaky failures.

We do not need to have it report status / comments, but just having it available for investigation would be good.

**Comment by justinmk** [comment]
Even vim dropped coveralls, though they were using both for awhile .

**Comment by blueyed** [comment]
I don't think "vim dropped coveralls" is an argument / reason to not do it here.

**Comment by justinmk** [comment]
We dropped it before vim did because it doesn't work well.

**Comment by blueyed** [comment]
I do not want to replace codecov with it, but just have it available when investigating coverage related issues.. it would not cost us much to just upload data to them also.
AFAIK they are improving their service also/still anyway.
Also it might work better in general when properly uploading gcov data (i.e. via gcovr).

Anyway, not a big / pressing issue - I was able to find the reason for dropped coverage already - but it certainly would have been easier with independant reporting platforms/tools.
