### ISSUE TITLE
Looking for the ShaDa file in another user's .local directory

### ISSUE THREAD

**Issue by jhessin** [neovim/neovim#10247]
This issue is very similar to this one: https://github.com/neovim/neovim/issues/4551#issue-147137920

- `nvim --version`: NVIM v0.4.0-1046-gd32b92e26
Build type: RelWithDebInfo
LuaJIT 2.0.5

- Vim (version: ) behaves differently? (Never touch it...)
- Operating system/version: Debian 9
- Terminal name/version: Terminator 1.9
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
I recieve this error message:
Error detected while processing function <SNR>13_LoadRe
motePlugins[1]..<SNR>13_GetManifest[1]..<SNR>13_GetMani
festPath:
line   10:
E739: Cannot create directory /home/jhessin/.local/shar
e/nvim: permission denied
E886: System error while opening ShaDa file /home/jhess
in/.local/share/nvim/shada/main.shada for reading: perm
ission denied

### Expected behaviour
No Error Message. I should mention that I am build Linux From Scratch and therefore using a limited account called lfs. I am using the AppImage downloaded via the directions on the neovim.io website - freshly downloaded by the lfs user. I have deleted my user configs completely, but this didn't change anything. There is no reason for this freshly downloaded copy of neovim to look in another user's home folder for the ShaDa file.

**Comment by justinmk** [comment]
Check your `$HOME` env var. This is a configuration issue, not a bug in Nvim.

**Comment by jhessin** [comment]
Yes already did that: $HOME = “/home/lfs” so why is it looking elsewhere?

**Comment by bfredl** [comment]
Also check `XDG_CONFIG_HOME` and `XDG_DATA_HOME` env vars.

**Comment by jhessin** [comment]
Okay - so where are these variables coming from. They aren’t in either of my config files (.profile or .bashrc). I thought the whole point of creating a separate account was so it wasn’t a polluted env? Does su not remove the previous env variables?

**Comment by blueyed** [comment]
The vars can be used, but have a default (https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
I would assume it should fall back to `~/.local/share` here (https://github.com/neovim/neovim/blob/4946751906370134cd02e8da0736bef221171172/src/nvim/os/stdpaths.c#L46).

Can you provide the output of `env` (can be grepped for `XDG|HOME` I guess).

See also `:h stdpath()` (check the output for `"data"` there), and `:set shada?` (please provide it here).

**Comment by blueyed** [comment]
> $HOME = “/home/lfs”

Also make sure `:echo $HOME` in nvim reflects that.

**Comment by jhessin** [comment]
*facepalm* I can’t believe it. I forgot the ‘-‘ after su! Sorry for wasting your time.
