### ISSUE TITLE
Random characters present in nvim when run in LXTerminal 0.2.0

### ISSUE THREAD

**Issue by phansel** [neovim/neovim#10240]
I keep seeing junk characters in the terminal whenever I use neovim; it's the random chars on the first line followed by a newline and about 19 spaces. 

at the top of files:
`]112[2 q]112[2 q
                    `
in the command bar, between the colon and whatever characters I type next:
`:]112[2 q  `

The brackets are somehow underneath the garbage characters. 

- `nvim --version`:  v0.4.0-1035-gb60c986a4
- Vim (version: 7.4 ) behaves fine and does not show this issue.
- Operating system/version: Lubuntu 16.04
- Terminal name/version: LXTerminal 0.2.0
- `$TERM`: xterm and gnome-terminal do not suffer from this issue.

This is probably an LXTerm-specific bug, but I'm reporting it here for posterity.

**Comment by KillTheMule** [comment]
See https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes.
> $TERM: xterm and gnome-terminal do not suffer from this issue.

That means you should report the value of the `TERM` environment variable. In bash, do `echo $TERM` for that.

**Comment by phansel** [comment]
TERM is /usr/bin/xterm. My default terminal is (or rather was) LXTerminal.

**Comment by KillTheMule** [comment]
> TERM is /usr/bin/xterm

That would certainly be very wrong. You sure about that? I don't have enough knowledge to tell you what to set this to (the terminal should do so correctly, but apparently doesn't), but that could very well be the source of what you're seeing. Quick google seems to suggest you try `xterm` or `xterm-256color`..

**Comment by egmontkob** [comment]
> Lubuntu 16.04

18.04 fixes this by compiling LXTerminal against GTK3 and in turn a much newer VTE, rather than GTK2 and an ancient unmaintained VTE.
