### ISSUE TITLE
:hardcopy is completely broken on Windows

### ISSUE THREAD

**Issue by morgan-greywolf** [neovim/neovim#10244]
- `nvim --version`:
NVIM v0.3.7
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
- Vim (version: ) behaves differently? Yes
- Operating system/version:  Windows 10
- Terminal name/version: nvim-qt

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC filename
:set pdev=printer
:hardcopy
:set pexpr?
:set pexpr=system(['copy', v:fname_in, empty(&printdevice)?'LPT1':&printdevice]) . delete(v:fname_in)

### Actual behaviour
- printdevice gets set
- Nothing prints
- pexpr is blank
- E518: Unknown option: v:fname_in,

### Expected behaviour
- printdevice gets set
- File prints
- pexpr contains the default string on Windows
- printexpr gets set correctly

**Comment by 3N4N** [comment]
`:hardcopy` seems to have been removed in [`5841a975`][1].

[1]: https://github.com/neovim/neovim/commit/5841a97500bffa5a2b9eed2eb41025f5587790ba

**Comment by justinmk** [comment]
For reference, an alternative is planned in https://github.com/neovim/neovim/issues/21629
