### ISSUE TITLE
access alternate screen with ":!"

### ISSUE THREAD

**Issue by zokrezyl** [neovim/neovim#10243]
- `nvim --version`: 0.3.5
- Vim (version: ) behaves differently? Yes
- Operating system/version: Linux (ubuntu 19)
- Terminal name/version: xterm
- `$TERM`: xterm

Hi, 

Obviously I tried to find an answer to my question/report before spamming here, but with less success.
Am not sure if this was intentional or just a consequence of some design decisions, but I really miss a feature of original vim, that is to access the original terminal content before as it was before starting nvim from within nvim. This was possible before with ":!" as you may know.

Is there any equivalent trick from within nvim or any plans to restore the original behaviour?

**Comment by bfredl** [comment]
You can access the default screen contents using suspend `<c-z>`.

**Comment by blueyed** [comment]
> `:!`

Interesting hack - it basically runs a shell with no command.

I also recommend using `<C-z>` instead.

**Comment by zokrezyl** [comment]
Stopped nvim may turn upside down some connectivity from nvim...

**Comment by bfredl** [comment]
Then this would be an ugly but working hack 
```
function! ShowScreen()
  call chansend(v:stderr, "\033[?1049l")
  call getchar()
  call chansend(v:stderr, "\033[?1049h")
  mode
endfunction
nnoremap <leader>s <cmd>call ShowScreen()<cr>
```

**Comment by zokrezyl** [comment]
> Then this would be an ugly but working hack
> 
> ```
> function! ShowScreen()
>   call chansend(v:stderr, "\033[?1049l")
>   call getchar()
>   call chansend(v:stderr, "\033[?1049h")
>   mode
> endfunction
> nnoremap <leader>s <cmd>call ShowScreen()<cr>
> ```

sounds almost like a solution.... but without nnoremap (just calling from command mode (call ShowScreen())) kind of only sometimes working...  will experiment tomorrow

**Comment by zokrezyl** [comment]
Ok.. I found the problem.. If I press ctrl-c while waiting on getchar() ... screws up ...

**Comment by bfredl** [comment]
yes, just press return.

**Comment by zokrezyl** [comment]
Or C without C .... Anyway :100:  answer :+1:  Thanks
