### ISSUE TITLE
Auto Close Braces and Quotes

### ISSUE THREAD

**Issue by zubairakram** [neovim/neovim#10251]
It's actually feature request.
nvim should provide builtin facility of auto closing of braces and quotes, because it's every programmer's need and they use it in almost every line of  code.
I'll be very handy to resolve this issue without installing third party plugin.

- `nvim --0.3.7`:
- Ubuntu/18.04
- Gnome Terminal/3.28.2:

### Actual behaviour
def method(arg

### Expected behaviour
def method(arg)

**Comment by blueyed** [comment]
While this might be nice to have in general, there are many possiblities / config options involved - and therefore I think it is good to actually delegate this to an external plugin.
What plugin do you use / prefer?  For me it's https://github.com/Raimondi/delimitMate.

**Comment by zubairakram** [comment]
Currently I'm using [Auto Pairs](https://github.com/jiangmiao/auto-pairs.git).
In my opinion if a feature is required for every type of coding then it should be the part of editor.
Third party plugins are not requirement of everyone.

**Comment by KillTheMule** [comment]
> because it's every programmer's need

Holy hell, please not. I mean, if you can convince the maintainers that this should be in the core, by all means send a PR that makes this possible, but please don't make those kind of assumptions.

**Comment by bfredl** [comment]
Is there any issue with the current plugin based solutions? We prefer to add features that expand the possibilities and improves the usability of plugins, rather than hardcoding specific behaviors into the core.

**Comment by justinmk** [comment]
This is covered by plugins. Long-term plan is to make it easier to install a curated list of plugins (by including some sort of package manager). Other than that, this is out of scope.

**Comment by zubairakram** [comment]
> > because it's every programmer's need
> 
> Holy hell, please not. I mean, if you can convince the maintainers that this should be in the core, by all means send a PR that makes this possible, but please don't make those kind of assumptions.

as you wish my dear!

**Comment by rseichter** [comment]
> > because it's every programmer's need
>
> [...] please don't make those kind of assumptions.

Exactly. I found this issue while searching for a means to *disable* automatic pairs of braces and quotes. It annoys me, and I have been programming for a good 40 years now.
