### ISSUE TITLE
flaky test: "'wildmenu' is preserved during :terminal activity"

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10253]
```
  [ RUN      ] 'wildmenu' is preserved during :terminal activity: ERR
  test\functional\helpers.lua:294: attempt to perform arithmetic on local 'written' (a nil value)
  
  stack traceback:
  	test\functional\helpers.lua:294: in function 'nvim_feed'
  	test\functional\helpers.lua:300: in function 'feed'
  	C:/projects/neovim/test/functional\ui\wildmode_spec.lua:116: in function <C:/projects/neovim/test/functional\ui\wildmode_spec.lua:83>
```

Ref: https://ci.appveyor.com/project/neovim/neovim/builds/25334607/job/iykj6tkjmjoid0ed#L6801

**Comment by bfredl** [comment]
If a request unexpectedly returns nil it could be indicative of a crash. There is no core dump though.

**Comment by blueyed** [comment]
Here is a test failure in this regard:
```
[  ERROR   ] ...build/neovim/neovim/test/functional/ui/wildmode_spec.lua @ 83: 'wildmenu' is preserved during :terminal activity
test/functional/ui/screen.lua:554: Row 1 did not match.
Expected:
  |*                         |
  |                         |
  |                         |
  |define  jump  list  >    |
  |:sign define^             |
Actual:
  |*foo                      |
  |foo                      |
  |foo                      |
  |define  jump  list  >    |
  |:sign define^             |
To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  
stack traceback:
	test/functional/ui/screen.lua:554: in function '_wait'
	test/functional/ui/screen.lua:366: in function 'expect'
	...build/neovim/neovim/test/functional/ui/wildmode_spec.lua:21: in function 'expect_stay_unchanged'
	...build/neovim/neovim/test/functional/ui/wildmode_spec.lua:96: in function <...build/neovim/neovim/test/functional/ui/wildmode_spec.lua:83>
```

**Comment by bfredl** [comment]
Hmm, just screen failure (not EOF) is actually quite easy for this test: just `{IGNORE}` the terminal lines. Though maybe increase timeout somewhat (to maintain realistic change of failing if nvim actually is broken). 

Probably using vsplit is not intrinsic to the incsearch + terminal activity test either, so the same trick could be used there.

**Comment by justinmk** [comment]
I used splits in those tests to have a concrete effect when terminal activity erroneously happens. Otherwise the test risks going "stale" for whatever reason, reaching "false success" silently.

**Comment by bfredl** [comment]
Well, the point is that the test _does_ go stale on success (correct nvim behavior), because cmdline state is now "stale" per definition (unless overriden with `:redraw` or whatever). The only ways to ensure terminal output has been processed is (1) wait "long enough" by reasonable timeout (2) register a callback tor terminal job output. Then it can check a final "eof" output line and and rpcnotify the test runner.

**Comment by justinmk** [comment]
Is this still an issue?
