### ISSUE TITLE
ci: run "make unittest" on AppVeyor

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10254]
I've wondered how https://github.com/neovim/neovim/blob/1d06da257886d4d4ec8075bde51a51d4af5caf68/test/unit/os/env_spec.lua#L84 would not fail on Windows, but apparently `make unittest` is not being run on AppVeyor currently.

**Comment by justinmk** [comment]
@janlazo worked on this in https://github.com/neovim/neovim/pull/7786 but it was postponed. It's a big task and not a high priority. Unit tests are useful for testing isolated logic. Platform-specific tests can usually be done as functional (aka integration) tests.

**Comment by dundargoc** [comment]
we don't use appveyor anymore
