### ISSUE TITLE
keyword-completion freeze

### ISSUE THREAD

**Issue by ganwell** [neovim/neovim#10266]
- built from source
- `nvim --version`: NVIM v0.4.0-1056-g494675190
- `git revision:` 494675190637
- Operating system/version: Linux Fedora 30
- Terminal name/version: xterm
- `$TERM`: xterm-256color
- Also happens with: NVIM v0.3.6

### Steps to reproduce using `nvim -u complete.vim`

I can't reproduce with NORC. I can only reproduce the problem using the complete.vim code.

1. Get this https://git.io/fjwl6 as complete.vim (it tries to complete-as-you-type in simple way using timers and therefore has the potential to create "race-conditions")

2. nvim

3. :setlocal spell spelllang=en_us

4. Type the following text

```
I can believe my eyes

I can
```
5. If it doesn't freeze, repeat removing and retyping `can`

6. Happens with ansi-256color too

```
# env -i TERM=ansi-256color "$(which nvim)"
```

### Demo

I started a pull request: https://github.com/neovim/neovim/pull/10263, but I couldn't find a solution. Therefore I created a demo on asciinema: https://asciinema.org/a/x0LD2JKaWD1VQGaNhYz7EVF7I

The demo has some plugins active, but I also reproduced just with complete.vim.

It shows the problem and a debug session using rr (record and replay). https://github.com/mozilla/rr

This loops for ever:

https://github.com/neovim/neovim/blob/4946751906370134cd02e8da0736bef221171172/src/nvim/edit.c#L4038

searchit() does not progress:

https://github.com/neovim/neovim/blob/4946751906370134cd02e8da0736bef221171172/src/nvim/edit.c#L4051

If this condition is not set on the first iteration it can't be set if the loop doesn't break:

https://github.com/neovim/neovim/blob/4946751906370134cd02e8da0736bef221171172/src/nvim/edit.c#L4064

Later no break conditions are set.

I tried various ways to make the loop progress, but all my ideas broke tests in a valid way.

If I can I do the pull-request, but I'd like to discuss the problem. I guess I could also create a docker-container with rr and the recording of the problem for analysis with gdb. I think the problem is quite old, therefore I didn't try to bisect, yet.

**Comment by blueyed** [comment]
Can you try it with (latest) Vim?
IIRC there might be some patch in this regard.

**Comment by blueyed** [comment]
Thought about e.g. vim/vim@02ab97709 (v8.1.0242), but it might be something completely different (haven't yet looked at complete.vim).

**Comment by blueyed** [comment]
I could not reproduce it (using `TERM=tmux-256color`, i.e. in tmux).

> :setlocal spell spelllang=en_us

Is this relevant / required to make it fail for you?

> `env -i TERM=ansi-256color "$(which nvim)"`

You can just use `nvim` instead of `"$(which nvim)"`.. ;)

**Comment by justinmk** [comment]
> You can just use `nvim` instead of `"$(which nvim)"`.. ;)

No, because `env -i` clears the environment and `nvim` may not be found in some cases.

**Comment by ganwell** [comment]
With latest vim (master-branch) I can reproduce the problem consistently (easier than with neovim).

I recorded another debug session: https://asciinema.org/a/9l9YqDS68wSkkvSNmn6V2eout

But it seems identical, although I haven't compared it line by line, yet.

> :setlocal spell spelllang=en_us

> > Is this relevant / required to make it fail for you?

Yes. to give you the whole story. The completion-as-you-type code sets:

```vim
" Enable dictionary completions
set complete+=k
```
This means it will search the usual places (buffers), plus the current dictionary. I cannot reproduce the problem without the dictionary completions. But the freeze happens when searching the local buffer:

p *ins_buf

```cpp
$2 = {
  b_ml = {
    ml_line_count = 3,
    ml_mfp = 0x16718e0,
    ml_flags = 12,
    ml_stack = 0x1619000,
    ml_stack_top = 1,
    ml_stack_size = 5,
    ml_line_lnum = 1,
    ml_line_ptr = 0x16d9d9a "I can believe my eyes",
    ml_line_len = 22,
```

I think I can simplify the code in complete.vim, I will do so later today.

**Comment by chrisbra** [comment]
open an issue at  the vim repository please with minimal reproduction steps. Thanks.

**Comment by ganwell** [comment]
While I updated the complete.vim code (https://git.io/fjwl6) to be minimal, I had an epiphany. I am more confident in the new fix and it doesn't break any tests: https://github.com/neovim/neovim/pull/10263

But I assume you still like me to report it in vim, so I'll create a bug-report there.

**Comment by chrisbra** [comment]
yes, please do, together with your proposed patch. We can likely turn this into a test than, so it doesn't regress. Thanks.

**Comment by ganwell** [comment]
I reported the freeze upstream: https://github.com/vim/vim/issues/4572

**Comment by ganwell** [comment]
The maintainer can't reproduce this. I decided to go for a workaround, if feedkeys is delayed using timer_start(0,....) there is no hang. Hopefully someone will come up with a way to reproduces this systematically.

**Comment by ganwell** [comment]
Closing this sat around long enough
