### ISSUE TITLE
:map info confused with float window

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#10262]
- `nvim --version`: v0.4.0-964-gf6f9e4a23
- Vim (version: ) behaves differently? n/a
- Operating system/version: macos
- Terminal name/version: iterm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
* test_float.vim
```vim
let buf = nvim_create_buf(v:false, v:true)
call nvim_buf_set_lines(buf, 0, -1, v:true, ["test", "text"])
let opts = {'relative': 'cursor', 'width': 8, 'height': 5, 'col': 3, 'row': 1, 'anchor': 'NW'}
let win = nvim_open_win(buf, 0, opts)
```
1. `nvim -u NORC`
2. `:source test_float.vim`
3. `:map` and input `G`, then input `gg`
 
### Actual behaviour
![image](https://user-images.githubusercontent.com/19503791/59677820-5debd200-91fd-11e9-86a3-0658c954ca1d.png)

**Comment by bfredl** [comment]
pager `g` seems to use `screenclear()` which is a needless [anti-]optimization. Maybe it works if we just remove it.

**Comment by bfredl** [comment]
was fixed by #10400.

**Comment by zgpio** [comment]
> was fixed by #10400.

Scroll refresh is not complete, see [video](https://asciinema.org/a/FCAGFG4ZHgVrsdQlmI41sej7e)

**Comment by blueyed** [comment]
@zgpio 
Looks like another issue - and looks even a bit more weird for me (omitting whole lines when redrawing after scrolling there again): https://asciinema.org/a/xsybaTJquOs5t4tVJdxO68ZHT (in tmux+kitty).

**Comment by bfredl** [comment]
@zgpio This is not related to the issue with floats which was fixed. It would be better to open a separate issue for this, otherwise it is hard to keep track.
