### ISSUE TITLE
Version after v0.3.1 incompatible with tmux

### ISSUE THREAD

**Issue by willise** [neovim/neovim#10273]
- `nvim --version`: 
NVIM v0.3.7
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-a776a8ad-e815-4d6d-bd5c-25b8608a9de1

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
- Vim (version: ) behaves differently?
YES
- Operating system/version:
CentOS Linux release 7.5.1804 (Core)
- Terminal name/version:
Xshell 6 (build 0107)

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
![image](https://user-images.githubusercontent.com/8471187/59737054-bd45f280-928e-11e9-94e4-93ef10991b6b.png)

### Expected behaviour
No blank line there.

Infact, when using customed config file for a search "err", mess is more clear like:
![image](https://user-images.githubusercontent.com/8471187/59737176-304f6900-928f-11e9-9aa8-f22ffff90459.png)

When using neovim version **NVIM v0.3.1-1-g489d32f2b** or Not use tmux, everything works well.

**Comment by h-michael** [comment]
> Terminal name/version:
> GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

This is not the Terminal name but the shell name.
And would you show us the result of `nvim -n NORC -c CheckHealth`? and tmux config?

**Comment by willise** [comment]
Update terminal info.

`nvim -n NORC -c CheckHealth`

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $SSH_TTY='/dev/pts/1'

## tmux
  - OK: escape-time: 10ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: tmux

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:

    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help provider-python
          /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help provider-python
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3.6"
  - INFO: Executable: /usr/bin/python3.6
  - INFO: Python version: 3.6.6
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

**Comment by erw7** [comment]
@willise Does this issue occur even with the following settings in the tmux FAQ?

Ref. https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-a-256-colour-terminal

**Comment by willise** [comment]
@erw7 Yes.
![image](https://user-images.githubusercontent.com/8471187/59752861-8a632500-92b5-11e9-9359-0b3c32135cad.png)

**Comment by erw7** [comment]
The https://github.com/neovim/neovim/issues/10273#issue-457802973 is as follows.

> + $TERM:
> xterm-256color

However, `$TERM` should be `screen-256color` if the corresponding setting is made. What happens if you run the following command on nvim:

```
:echo &term
:echo $TERM
```

If the value of `TERM` is really `xterm-256color`, you should have set it up so somewhere. Please delete that setting. Anyway, for tmux, `TERM` needs to be set to `screen-256color` or `tmux-256color`.

**Comment by willise** [comment]
`TERM=xterm-256color` is set on my bash which is outside tmux. When starting nvim in tmux, both of &term and $TERM value are `screen-256color`.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by willise** [comment]
Fixed.
