### ISSUE TITLE
Parallel make fails if a machine does not support lock operation

### ISSUE THREAD

**Issue by e-kwsm** [neovim/neovim#10276]
- `nvim --version`: 352d5a971344e2402aaa8704b802fa7dfaaa3050
- Vim (version: ) behaves differently? not sure but probably yes
- Operating system/version: RHEL 6.7
- Terminal name/version: (over ssh)
- `$TERM`: (over ssh)

* aclocal: 1.11.1
* autoconf: 2.63

### Steps to reproduce
I'm working on a LUSTRE-variant machine which does not seem to support lock operation, resulting in parallel make (e.g., `make -j8`) faiure.
Actually `make -j8 || make` works but is it possible to fix this like  #7697?

Thank you in advance.

### Actual behaviour
```shellsession
$ make -j8
...
checking for suffix of object files... LINK libvterm.la
autom4te: cannot lock autom4te.cache/requests with mode 2: Operation not supported
autom4te: forgo `make -j' or use a file system that supports locks
aclocal: autom4te failed with exit status: 1
make[3]: *** [build/src/libuv-stamp/libuv-configure] Error 1
make[3]: Leaving directory `/opt/src/neovim/.deps'
make[2]: *** [CMakeFiles/libuv.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

### Expected behaviour
Parallel make does not fail.

**Comment by justinmk** [comment]
> Actually `make -j8 || make` works but is it possible to fix this like #7697?

That would force serialization on everyone. That doesn't make sense. You can simply invoke `make` without `-j`, can't you?
