### ISSUE TITLE
tests: test_python{2,3}.vim fails

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10270]
`make oldtest TEST_FILE=test_python3.res` fails:

> AttributeError: 'LegacyVim' object has no attribute 'bindeval'

```
From test_python3.vim:
Found errors in Test_vim_function():
function RunTheTest[37]..Test_vim_function line 13: Expected False but got 'Vim(return):Error invoking ''python_execute'' on channel 3 (python3-script-host):\nTraceback (most recent call last):\n  File "<string>", line 1, in <module>\nAttributeError: ''LegacyVim'' object has no attribute ''bindeval'''
function RunTheTest[37]..Test_vim_function line 20: Expected False but got 'Vim(return):Error invoking ''python_execute'' on channel 3 (python3-script-host):\nTraceback (most recent call last):\n  File "<string>", line 1, in <module>\nAttributeError: ''LegacyVim'' object has no attribute ''Function'''
Caught exception in Test_vim_function(): Vim(return):Error invoking 'python_execute' on channel 3 (python3-script-host):Traceback (most recent call last):  File "<string>", line 1, in <module>NameError: name 'f' is not defined @ function RunTheTest[37]..Test_vim_function[23]..provider#python3#Call, line 18
```

This is not catched on CI due to:

1. `make oldtest` passing silently on Windows/AppVeyor (a real waste on resources btw)
2. `pynvim` not being installed properly on Travis, and the test being skipped there

Started working on this / debugging it in https://github.com/neovim/neovim/pull/10269.

**Comment by justinmk** [comment]
`bindeval` is not supported in Nvim. The test (or some specific part of it) can just be skipped.

**Comment by justinmk** [comment]
Before spending more time on this I would suggest reviewing 0995f460fbebdfd7d76b8932f73ea958033c92b1 and f51a397010dcf4a8308c3b0249810696375b82b2. Travis python/pip is known to be broken, the issue https://github.com/travis-ci/travis-ci/issues/8363 was auto-closed without resolution.

I do not think this is worth spending time on.

**Comment by blueyed** [comment]
I think the Python/pip problem(s) are fixed.
I've added `:checkhealth` output in https://github.com/neovim/neovim/pull/10269 - which looks OK (but only looked at it quickly).

**Comment by justinmk** [comment]
Ok, but JFI the behavior I saw was random, even on the same travis "image".

**Comment by janlazo** [comment]
Installing pynvim in the system directory (ie. not using `--user` flag) should fix this. `$HOME` workaround for legacy tests causes the problem because `~/.local/` is not symlinked into the fake home directory.
