### ISSUE TITLE
redraw! doesn't actually clear

### ISSUE THREAD

**Issue by rgreenblatt** [neovim/neovim#10279]
- `nvim --version`: v0.4.0-dev
- Vim (version: ) 8.0
- Operating system/version: ubuntu 18.04
- Terminal name/version: st
- `$TERM`: st-256color

### Steps to reproduce using `nvim -u NORC`

This is a TUI specific issue.

```
while true; do
echo "some text"
sleep 1
done &
nvim -u NORC
:sleep 5 | redraw!
```

### Actual behaviour
"some text" remains on TUI.

### Expected behaviour
redraw! (or &lt;c-l&gt;) should clear the entire screen. This works in vim 8.0.

### Motivation
Clearing garbage characters which sometimes happen over ssh. Clearing out background text when using nvim in a tty.

**Comment by justinmk** [comment]
ctrl-l does work. I think `:redraw!` was known change, I don't recall if it was intentional. @bfredl ?

**Comment by rgreenblatt** [comment]
nvim 0.3.1 doesn't have this issue.

**Comment by rgreenblatt** [comment]
nvim 0.3.2 does have this issue.

**Comment by rgreenblatt** [comment]
The change is here https://github.com/neovim/neovim/pull/9143

**Comment by justinmk** [comment]
Thanks for bisecting. Yes, that's the change I was thinking of. It was intentional, but I can't remember if we decided that `:redraw!` should be different than CTRL-L (which already works as you expect).

**Comment by bfredl** [comment]
We decided
`:redraw -> update_screen(0)`
`:redraw! -> update_screen(NOT_VALID)`
`:mode -> update_screen(CLEAR)`
`<C-L> -> update_screen(CLEAR)`

We could make `:redraw!` clear again, but then we need another command for `update_screen(NOT_VALID)`.

**Comment by rgreenblatt** [comment]
The documentation is : "When ! is included it is cleared first.". If nothing else, this should be changed.

**Comment by justinmk** [comment]
added to https://github.com/neovim/neovim/pull/10177

**Comment by justinmk** [comment]
## Resolution/Summary

Nvim defines this behavior: 

- `:redraw -> update_screen(0)`
- `:redraw! -> update_screen(NOT_VALID)`
- `:mode -> update_screen(CLEAR)`
- `<C-L> -> update_screen(CLEAR)`

Documentation updated in #10177.

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._
