### ISSUE TITLE
vim main help file: puzzled explanation using N-1

### ISSUE THREAD

**Issue by icyhat** [neovim/neovim#10278]
official vim main help file => `quickref.txt`

### Actual behaviour
```
|$|	N  $		to the last character in the line (N-1 lines lower)
```
### Expected behaviour
```
|$|	N  $		to the next EOL(End Of Line) position
```
the original help file using `N-1 lines` which really puzzled readers how to calculate `N` and `N-1` and misleading to the origin meaning

Actually there is only `N`, go to Nth EOL, readers won't need to think of `N-1` until they really need to calculate line subtraction.

I'm willing to make official help file better if I can help.

: )

**Comment by justinmk** [comment]
Leave a comment on https://github.com/neovim/neovim/pull/10177.
