### ISSUE TITLE
Changelog for 0.3.7?

### ISSUE THREAD

**Issue by chagar** [neovim/neovim#10277]
Can we get a changelog for the 0.3.7 release? Previous releases have changes under Github Releases, but not this one.

(Also, the wiki page referenced in PR #3564 appears to be dormant or only lists breaking changes.)

**Comment by justinmk** [comment]
Every release includes the changelog in the commit message. 

https://github.com/neovim/neovim/commit/ede21f95180f44cab6b77598d34de31967f24622
