### ISSUE TITLE
xfpclassify: warning: conversion from ‘double’ to ‘float’ may change value (gcc 9.1)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10286]
I am seeing the following warning, _likely_ caused by upgrading to gcc 9.1:

```
[226/303] Building C object src/nvim/CMakeFiles/nvim.dir/math.c.o
In file included from ../src/nvim/math.c:4:
../src/nvim/math.c: In function ‘xfpclassify’:
../src/nvim/math.c:24:21: warning: conversion from ‘double’ to ‘float’ may change value [-Wfloat-conversion]
   24 |   return fpclassify(d);
      |                     ^
../src/nvim/math.c:24:21: warning: conversion from ‘double’ to ‘float’ may change value [-Wfloat-conversion]
   24 |   return fpclassify(d);
      |                     ^
```

I've seen https://github.com/neovim/neovim/pull/9532, but have not investigated further yet.

**Comment by justinmk** [comment]
Makes sense, because the `diagnostic push` workaround only is implemented for clang. I guess we need it for gcc now too.

**Comment by blueyed** [comment]
I've seen https://bugzilla.redhat.com/show_bug.cgi?id=1472437#c20 mentioning a fix for GCC 8, but maybe cclang was meant there - since apparently that issue should / might be fixed there.

**Comment by justinmk** [comment]
@blueyed does https://github.com/neovim/neovim/pull/10393 fix it?

**Comment by blueyed** [comment]
@justinmk 
I am not seeing the errors anymore.
The gcc package was updated with two backported patches: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90397 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90949 - the second one looks (more) likely to me to have fixed it.
