### ISSUE TITLE
execute('hi Group') contains extra newline when screen is narrow

### ISSUE THREAD

**Issue by Avi-D-coder** [neovim/neovim#10285]
- `nvim --version`:
NVIM v0.4.0-1016-g6f27f5ef9
Build type: RelWithDebInfo
LuaJIT 2.0.5
- Operating system/version: Linux
- Terminal name/version: kitty 0.14.2 created by Kovid Goyal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u minirc.vim`

Adapted from [highlight_inherit](https://github.com/Avi-D-coder/highlight-inherit.vim/blob/master/autoload/highlight_inherit.vim)
```vim
function! Highlight_inherit_getOpts(group)
  let output = execute('hi ' . a:group)
  let list = split(output, '\s\+')

  if list[2] == 'links'
    return Highlight_inherit_getOpts(list[4])
  endif

  let dict = {}
  for item in list
    if match(item, '=') > 0
      let splited = split(item, '=')
      let dict[splited[0]] = splited[1]
    endif
  endfor
  return dict
endfunction

function! Highlight_inherit_write(new_name, options_dict, inherit)
  let l:hl_opt = []
  for [key, value] in items(extend(Highlight_inherit_getOpts(a:inherit), a:options_dict, "force"))
    call insert(l:hl_opt, key . '=' . value)
  endfor
  execute('hi! ' . a:new_name . ' ' . join(l:hl_opt))
endfunction
```

`$ nvim -u minirc.vim`
`:call Highlight_inherit_write("Conditional", {'gui':'italic'}, "Conditional")`
### Actual behaviour
If terminal window width is less than around 400px.
![Screenshot_20190620_153942](https://user-images.githubusercontent.com/29133776/59877208-5f3f0b00-9373-11e9-9537-d734d31a30da.png)

### Expected behaviour
Narrow terminals should not trigger an error when a normal size terminal does not.

**Comment by bfredl** [comment]
>   execute('hi! ' . a:new_name . ' ' . join(l:hl_opt))

could be useful to save the exact executed string to a variable and print the value. If a superfluous `\n` snuck in somewhere it could explain the error.

**Comment by bfredl** [comment]
Also, have you tested if vim behaves the same or not? (or maybe start gvim instead...).

**Comment by Avi-D-coder** [comment]
Vim does not like any of it. I don't have gvim.
```
Error detected while processing function Highlight_inherit_write[2]..Highlight_inherit_getOpts:
line    1:
E411: highlight group not found: Conditional
Error detected while processing function Highlight_inherit_write:
line    5:
E417: missing argument: gui=
E492: Not an editor command: italic
```

@bfredl 
Nvim `echomsg` logs `hi! Conditional guifg=#ffff60 ctermfg=11 gui=italic` in a normal window and `hi! Conditional guifg=#ffff60 ctermfg=11^@ gui=italic` in a narrow window.

When/why does echomsg print `^@`?

It's displays wrapped to this
```
hi! Conditional guifg=#ffff60 
ctermfg=11^@ gui=italic
```

**Comment by bfredl** [comment]
`^@` is just a weird representation of a newline. It could be a bug with the first `execute()` actually, that it inserts a newline into the output when it would wrap in interactive execution.

**Comment by Avi-D-coder** [comment]
> It could be a bug with the first `execute()`
Your right it is.

A work around is `split(output, '\(\s\|\n\)\+')`.

**Comment by blueyed** [comment]
> It could be a bug with the first `execute()` actually

Yes, looks like it.

OTOH is really just redirects, so that is what you get/see in the end.

Might be worth to try `'silent!'` as second arg to `execute()` - but it is about wrapping after all, not trailing output, or extra messages.

@Avi-D-coder 
As for testing in Vim, you should use a group that exists there.
Would be helpful to know if it behaves the same.

**Comment by chrisbra** [comment]
>   let output = execute('hi ' . a:group)
>   let list = split(output, '\s\+')

Well, the problem is, the output is wrapped (so an additional '\n') is written out. The output is then captured and split on whitespace, but that does not remove the exta `\n`. So you should use `:echo split(output, '\_s\+')` to split it. (Note, there exists extra functions to get the syntax properties for a syntax group (`synID()`, `synIDattr()`, `synIDtrans()`), so that would be the cleaner approach, rather than trying to parse the output of `:hi`

I am not sure this is a bug.

**Comment by bfredl** [comment]
> OTOH is really just redirects, so that is what you get/see in the end.

>  is, the output is wrapped (so an additional '\n') is written out. The output is then captured and split on whitespace,

I guess you can make the case for  `execute('hi ...')` as it is using the screen. But `execute('...', 'silent!')` and `nivim_command_output('...')` are not and still exhibits the same issue. There is no reason to output `\n` in this case (done internally by message.c) as the output is not shown on the screen.

**Comment by bfredl** [comment]
Hmm, with `ext_messages` the output actually contains too little whitespace. I guess we could use the same codepath for both (a single space char between groups, regardless of `msg_col`).

**Comment by chrisbra** [comment]
>  But execute('...', 'silent!') ... are not

Are you sure or is this a neovim difference? I am not sure I follow from the documentation that `:silent!` should not be using the screen.

**Comment by bfredl** [comment]
Sorry, I mistyped when testing the commands. `execute('...', '')` is using the screen for output , but the other forms are not, including the default `silent` (as long as there is no error). This seems to be consistent with vim and the documentation?
