### ISSUE TITLE
&t_Co is incorrect for $TERM with 16777216 colours

### ISSUE THREAD

**Issue by auscompgeek** [neovim/neovim#10281]
- `nvim --version`: v0.3.7 and v0.4.0-1063-g487eaf8d4
- Vim (version: 8.1) behaves correctly
- Operating system/version: Arch Linux
- Terminal name/version: any terminal with 24-bit colour support
- `$TERM`: xterm-direct, vte-direct, etc.

### Steps to reproduce using `nvim -u NORC`

```bash
TERM=xterm-direct nvim -u NORC
```
```vim
:echo &t_Co
```

### Actual behaviour
`&t_Co` is 1677721

### Expected behaviour
`&t_Co` should be 16777216

**Comment by justinmk** [comment]
Why is this important? t_Co only exists for legacy compatibility.

**Comment by bfredl** [comment]
I don't think `t_Co` was meant to distinguish the number of colors above 256, it returns "256" for many true color terminals. `termguicolors` exists for this purpose, whenever it is set, a plugin should assume true color support, and ignore `t_Co`.

**Comment by auscompgeek** [comment]
@bfredl surely if `termguicolors` is intended for this, then it should be set when the terminfo advertises true colour support?

**Comment by bfredl** [comment]
That would break user configs that use color schemes that are 256-colors only. What is the problem with leaving the decision up to the user? Is terminfo detection reliable anyway?

**Comment by auscompgeek** [comment]
> That would break user configs that use color schemes that are 256-colors only.

Colour schemes that are 256 colours only are already broken when the terminfo advertises true colour support.
