### ISSUE TITLE
":highlight CursorLine cterm=inverse" uses "light black" instead of "black" for highlighted text.

### ISSUE THREAD

**Issue by pthfdr-42** [neovim/neovim#10282]
- `nvim --version`:
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-H9FZ0H/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-H9FZ0H/neovim-0.3.4/build/config -I/build/neovim-H9FZ0H/neovim-0.3.4/src -I/usr/include -I/build/neovim-H9FZ0H/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-H9FZ0H/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently?
Not appliable since `vim` is not installed.
- Operating system/version:
Debian Sid.
- Terminal name/version:
Linux TTY.
- `$TERM`:
linux

### Steps to reproduce using `nvim -u NORC`
Not appliable.
### Actual behaviour
In Linux TTY, when highlighting a line or column of text, you used "bright black" (ANSI 90) instead of "black" (ANSI 30) for highlighted text. Since the Linux TTY uses the "black" value for its background, this leads to unreadable text due to low contrast.
In `xterm`, this problem still exists with column highlighting.
[In Linux TTY (I used `rotate=3`). Note that the highlighted text are gray.](https://user-images.githubusercontent.com/42509223/59857823-50287f00-93ac-11e9-847d-1d2afa57c9bf.png)
[In `xterm`. Note the column highlighting.](https://user-images.githubusercontent.com/42509223/59857176-fa9fa280-93aa-11e9-861e-a830bcb40ae1.png)

### Expected behaviour
`cterm=inverse` should only do reverse video (ANSI 7).

**Comment by justinmk** [comment]
Linux vt console (`TERM=linux`) is "best effort". PR welcome, otherwise this is zero priority.
