### ISSUE TITLE
tmux + neovim home/end don't work with TERM=alacritty

### ISSUE THREAD

**Issue by daenney** [neovim/neovim#10299]
- `nvim --version`: 0.3.7
- Operating system/version: Arch Linux 5.2-rc5
- Terminal name/version: Alacritty 0.3.3
- `$TERM`: alacritty
- Tmux: 2.9-a_2

### Steps to reproduce using `nvim -u NORC`

The problem is rather curious as it only happens when running alacritty+tmux+neovim. Take out tmux and everything works as expected. The terminfo for alacritty is installed and $TERM inside and outside of tmux returns `alacritty`. Launching a subshell with `TERM=screen-256color` and using neovim in there makes the problem go away.

I believe the issue is related to something in neovim b/c other editors running under tmux do not suffer from this, such as nano.

```
tmux
nvim -u NORC
> Type a long sentence
> Try using Home/End or fn+left/right
```

### Actual behaviour

* fn+left/right or home/end keys do not move the cursor to start or end of line
* fn+up/down or pgup/pgdown do move the cursor

### Expected behaviour

fn+left/right and home/end keys behave as expected, moving the cursor to start or end of line

**Comment by blueyed** [comment]
Is this https://github.com/neovim/neovim/issues/9071?  Do you / alacritty use/uses a `$TERMINFO` env?

**Comment by daenney** [comment]
Mmm, it definitely seems related. However, both in a plain alacritty and an alacritty+tmux session I have no TERMINFO in my environment, only TERM.

**Comment by blueyed** [comment]
@daenney 
Good to know - then it's another, but possibly related issue.
Please try to check the code around this, e.g. by adding `printf` to unibilium / neovim, if you can.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

If it's not fixed there, then this is either a duplicate or is covered by other tickets which generally relate to "some key doesn't work on some terminal emulator". Patch welcome, we don't need a separate ticket for every key that doesn't work on a terminal emulator.
