### ISSUE TITLE
ci: "ightly" branch

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10295]
On codecov a "ightly" branch is referenced: https://codecov.io/gh/neovim/neovim/branch/ightly

I've seen "nightly" builds on AppVeyor (https://ci.appveyor.com/project/neovim/neovim/history, btw: several in a row (with earlier ones canceld automatically)).

Where is "ightly" coming from? (obviously missing an "n")

**Comment by justinmk** [comment]
On codecov a "ightly" branch is referenced: https://codecov.io/gh/neovim/neovim/branch/ightly

And https://codecov.io/gh/neovim/neovim/branch/nightly doesn't exist, so maybe this is a codecov bug.

> I've seen "nightly" builds on AppVeyor (https://ci.appveyor.com/project/neovim/neovim/history, btw: several in a row (with earlier ones canceld automatically)).

`nightly` branch is built once per day. How AppVeyor deals with that is beyond me.
