### ISSUE TITLE
Crash on api calls when in luv callbacks

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#10298]
- `nvim --version`: NVIM v0.4.0-1075-gbc10a15ea
- Vim (version: ) behaves differently? NA
- Operating system/version: Linux 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
- Terminal name/version: kitty v0.13.1
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Save the following as /tmp/tmp.vim:
```vimscript
let g:port = luaeval('(function()
    \ local server = vim.loop.new_tcp()
    \ server:bind("127.0.0.1", 0)
    \ server:listen(128, function(err)
            \ assert(not err, err)
            \ local sock = vim.loop.new_tcp()
            \ server:accept(sock)
            \ sock:read_start(function(err, chunk)
                  \ vim.api.nvim_command("qall!")
                  \ end)
            \ end)
    \ return server:getsockname().port
    \ end)()')
execute "! echo hello | nc 127.0.0.1 " . g:port
```
And then run neovim
```
nvim -u NORC /tmp/tmp.vim -c "source %"
```

Neovim crashes when it reaches this line:
https://github.com/neovim/neovim/blob/bc10a15ea7a5e9108a0d60a2092b099b9a6a4805/src/nvim/event/loop.c#L42

**Comment by bfredl** [comment]
Yes, it is a know problem. I've been meaning to work on this, but other things have gotten in the way.. In the meanwhile you can use `vim.schedule`:

```
sock:read_start(function(err, chunk)
  vim.schedule(function() 
    vim.api.nvim_command("qall!")
  end)
end)
```
