### ISSUE TITLE
deps: use neovim/unibilium fork

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10302]
TODO:

- [x] enable CI for https://github.com/neovim/unibilium, e.g. to run for https://github.com/neovim/unibilium/pull/2 @justinmk 
- [x] enable issues  @justinmk 
- [x] use our fork in `third-party/CMakeLists.txt`
- [x] merge any CMake PATCH_COMMAND steps as commits to the fork
- [ ] merge @erw changes from https://github.com/neovim/neovim/pull/9094

Ref: https://github.com/mauke/unibilium/issues/36#issuecomment-502956153

/cc @mauke

**Comment by justinmk** [comment]
@mauke is out to lunch. If we are going to fork unibilium then we should rename it, e.g. unibilium2. @jamessan did you start on that, or is it ok if we forge ahead on this?

**Comment by jamessan** [comment]
> did you start on that, or is it ok if we forge ahead on this?

I did not, yet, so forge away.  I'd like to be on the team for that repo, though.

> If we are going to fork unibilium then we should rename it, e.g. unibilium2

I don't think that's necessary.  It's still unibilium, just with active maintenance.  If it were being rewritten or something, I could see the rename.  However, I'm pretty sure we're just trying to keep it alive and address issues that come up.

**Comment by blueyed** [comment]
I agree that we should not use a different name.

@justinmk 
Please setup CI (i.e. enable it on Travis), and enable issues - and/or add permissions for me / @jamessan to do it.

**Comment by blueyed** [comment]
@justinmk ping

**Comment by justinmk** [comment]
@blueyed done

**Comment by blueyed** [comment]
Closing, only https://github.com/neovim/neovim/pull/9094 is missing - which is tracked therein itself.
