### ISSUE TITLE
Getting warning message after version upgrade

### ISSUE THREAD

**Issue by gmichokostas** [neovim/neovim#10301]
- `nvim --version`: NVIM v0.3.7

- Vim (version: ) behaves differently? Yes, I don't get the warning messages
- Operating system/version: macOS Mojave 10.14.5
- Terminal name/version: iTerm2 3.2.9 / Terminal.app 2.9.5
- `$TERM`: xterm-256color

### Actual behaviour

I am using Homebrew as my package manager and after I upgraded 
the version from `0.3.7` to `0.3.7_2`, every time I start the editor I am 
getting the following warning messages in the terminal.

```
Warning: Failed to set locale category LC_NUMERIC to en_DE.
Warning: Failed to set locale category LC_TIME to en_DE.
Warning: Failed to set locale category LC_COLLATE to en_DE.
Warning: Failed to set locale category LC_MONETARY to en_DE.
Warning: Failed to set locale category LC_MESSAGES to en_DE.
Warning: Failed to set locale category LC_NUMERIC to en_DE.
Warning: Failed to set locale category LC_TIME to en_DE.
Warning: Failed to set locale category LC_COLLATE to en_DE.
Warning: Failed to set locale category LC_MONETARY to en_DE.
Warning: Failed to set locale category LC_MESSAGES to en_DE.
```

### Expected behaviour
I should not get any warning messages related to locales.

**Comment by blueyed** [comment]
> after I upgraded the version from 0.3.7 to 0.3.7_2

Looks like a homebrew issue then.
Please try building Neovim yourself if you can, and see if it happens there also.

**Comment by chrisbra** [comment]
Related Vim issue https://github.com/vim/vim/issues/4556

Might be a gettext issue.

**Comment by gmichokostas** [comment]
> Related Vim issue [vim/vim#4556](https://github.com/vim/vim/issues/4556) Might be a gettext issue.
> […](#)

Indeed it is a gettext issue, after downgraded the version to gettext-0.19.8.1 the message is gone.

Thanks guys!
