### ISSUE TITLE
[RFC] build: revisit/fix USE_BUNDLED_BUSTED

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10304]
`USE_BUNDLED_BUSTED` was added in https://github.com/neovim/neovim/pull/2447 (https://github.com/neovim/neovim/commit/fe9ec9c29956cb2bd4062d3e582412006d42292e), with the intention to skip building of deps needed for tests.

From the name itself I understand it however as it would affect only "busted" itself, and not test dependencies in general.
I.e. that you could use `USE_BUNDLED_BUSTED=0`, and still have tests working, when `USE_BUNDLED_LUAROCKS=1` was used by default.

I think the current behavior is OK, but at least the description should be clarified / extended then: https://github.com/neovim/neovim/blob/b5aecfe254fbe518801e57b0224dddf863aa069c/third-party/cmake/BuildLuarocks.cmake#L6

Also renaming it to `USE_BUNDLED_TEST_ROCKS` would make it more explicit (but should keep the old name anyway I guess).

**Comment by blueyed** [comment]
Currently `USE_BUNDLED_BUSTED=1` would be ignored with `USE_BUNDLED=0` / `USE_BUNDLED_LUAROCKS=0` also, resulting in a CMake warning ("Manually-specified variables were not used by the project:").  This might be fine, but just wanted to mention it.

**Comment by justinmk** [comment]
This kind of stuff should be sent by sending a patch. We don't need tickets for this.
