### ISSUE TITLE
Silent doesn't work with rpcrequest

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#10310]
- `nvim --version`: 0.4.0
- Vim (version: ) behaves differently? N/A
- Operating system/version: Mac
- Terminal name/version: iTerm2

### Steps to reproduce using `nvim -u NORC`

Create a remote plugin that use echo command:

``` js
module.exports = (plugin) => {
  let {nvim} = plugin
  plugin.registerFunction('Echo', async () => {
    await nvim.command('echo "test"')
  })
}
```
Run `:UpdateRemotePlugins`

In neovim, run `:silent call Echo()`

### Actual behaviour

`test` is echoed.

### Expected behaviour

`test` should not be echoed, like when using silent with normal vim function.

**Comment by ShikChen** [comment]
It might be a problem of https://github.com/neovim/node-client. There is no (easy) way to run `nvim.command()` synchronously using node-client, so we cannot make `Echo()` a synchronous function, and I guess `:silent` only works for synchronous functions.

The synchronous version `:silent call EchoSync()` in [pynvim](https://github.com/neovim/pynvim) works:

``` python3
import pynvim

@pynvim.plugin
class EchoPlugin(object):
    def __init__(self, nvim):
        self.nvim = nvim

    @pynvim.function('EchoSync', sync=True)
    def echo_sync(self, args):
        self.nvim.command('echom "test"')

    @pynvim.function('EchoAsync')
    def echo_async(self, args):
        self.nvim.command('echom "test"')
```

Note that running `:call EchoSync() | echom "test2"` would print `test` then `test2`, while `:call EchoAsync() | echom "test2"` would print `test2` then `test`.

**Comment by bfredl** [comment]
Confirmed. Not a nvim issue then. RPC plugins should use synchronous requests to run nested requests in the scope of modifiers like `:silent`.
