### ISSUE TITLE
Can't find header file even though it exists

### ISSUE THREAD

**Issue by astromac** [neovim/neovim#10325]
- Operating system/version: MacOS 10.14.5
- Terminal name/version: iTerm2 3.2.9
- `$TERM`: xterm-256color

### Actual behaviour
Nightly build fails with error
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdio.h:108:15: fatal error:
      'stdio.h' file not found
#include_next <stdio.h>
              ^~~~~~~~~
1 error generated.
make[5]: *** [getline.o] Error 1
make[4]: *** [install] Error 2
make[3]: *** [build/src/gperf-stamp/gperf-install] Error 2
make[2]: *** [CMakeFiles/gperf.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2

ls -la /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdio.h
  rw-r--r--  root  wheel     3 KiB  Fri Mar  1 15:23:53 2019    stdio.h
```
### Expected behaviour
Build successfully

![Screen Shot 2019-06-24 at 1 47 00 PM](https://user-images.githubusercontent.com/296716/60041064-6d996980-9688-11e9-90fd-570649fbc230.png)

**Comment by justinmk** [comment]
This kind of problem is always an environment problem. Typically it involves some `xcode` update/reinstall/etc. See also

- many cases in https://github.com/neovim/homebrew-neovim/issues?q=is%3Aissue+is%3Aclosed
- example https://github.com/neovim/homebrew-neovim/issues/184#issuecomment-258275540
