### ISSUE TITLE
Home / end keys not working on Windows

### ISSUE THREAD

**Issue by alcroito** [neovim/neovim#10324]
- `nvim --version`: NVIM v0.3.7 installed via Releases page
- Vim (version:  Vi IMproved 8.1 ) behaves differently
- Operating system/version: Windows 10 Pro 1809 OS Build 17763.503
- Terminal name/version: cmd in Cmder, regular cmd, regular powershell
- `$TERM`: empty

### Steps to reproduce using `nvim -u NORC`

Type some words in insert mode, press HOME key, END key

### Actual behaviour
Nothing happens

### Expected behaviour
Move to beginning / end of line

# Comments
Both keys work fine in VIM

I've tried multiple combinations of shells. Regular cmd while starting from Start menu, regular PowerShell, also cmd started from Cmder.
I played around with TERM values, empty, cygwin (which is set by Cmder), xterm-256color.
I used nvim -u NORC.

None of it makes a difference. HOME and END simply do nothing. 
Note that the keys work in nvim-qt.

**Comment by justinmk** [comment]
Thanks for the report. 

- Can you try the development version?  The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)
- Read `:help $TERM` carefully and try the values suggested there.

**Comment by alcroito** [comment]
Hi,

I read through `:help $TERM`, and tried setting TERM to the following values, in conjunction with using latest  NVIM v0.4.0-1077-gde2e51439 package for Windows.

cmd.exe + TERM values I tried: empty, conemu.cygwin,interix,vtpcon,win32con,ansi,vte,st
ConEmu + cmd.exe + TERM values I tried: empty, conemu, cygwin, ansi

None of these made any difference in the HOME and END key usage, pressing them does nothing.
And i could confirm that the TERM was changed, because in some of the configurations there were weird artifacts in the rendering and typing (presumably because of the mismatch between the TERM value I set and the fact that I used cmd.exe). 

I would thus ask, to please re-open the issue.

**Comment by alcroito** [comment]
Hi, any chance this can be re-opened?

The provided advice did not make a difference, as described in my previous reply.

**Comment by lengthmin** [comment]
I'm using the PowerShell and Windows Terminal, also facing this problem.
but neovim-qt works well.

**Comment by lengthmin** [comment]
and also the Home/End key works well on vim 8.1.2372.

**Comment by lengthmin** [comment]
after setting term to conemu on Conemu, home/end key can't work too.
![image](https://user-images.githubusercontent.com/13938334/69935928-45544780-1511-11ea-8107-d69418c23f21.png)

I'm using powershell.

**Comment by lengthmin** [comment]
in Windows Terminal, I have tried conemu, cygwin, interix, vtpcon, win32con, xterm..
all of those can't work.

**Comment by jantari** [comment]
I am also experiencing this issue.

Using both the old [`conhost` and the new `Windows Terminal`](https://github.com/microsoft/terminal) terminals, <HOME> and <END> don't work. Neither in normal nor in Insert mode.

The `$TERM` environment variable (well, `$env:TERM` in PowerShell) is undefined.

`:echo $TERM` in neovim outputs `vtpcon`.

I tried setting `$env:TERM` to all kinds of values, none of them made the <HOME> and <END> keys work.

    NVIM v0.3.4
    Windows 10.0.19559.1000
    Windows Terminal 0.8.10261.0

**Comment by JosephSamela** [comment]
> Hi reporting the same issue. `<HOME>` and `<END>` keys don't work as expected in insert mode (jumping cursor to the beginning or end of the line). I'm using the powershell terminal.
> 
> ```
> NVIM v0.5.0-418-g87d892afa
> Windows 17763.1012
> Powershell 10.0.17763.1
> ```

I rolled back to stable NVIM `NVIM v0.4.3` and that version is showing the same issue.

**Comment by wldh-g** [comment]
Why this issue was closed? I'm facing the same issue, with latest neovim version (nightly 0.5.0-beta).

**Comment by PaperPlaneSoftware** [comment]
Yup, same issue here.

```
Windows Terminal 0.11.200428001-release0.11
Powershell 7.0.0
NVIM v0.4.3
```

**Comment by antonwnk** [comment]
This should be open. Same issue:
```
Windows Terminal 0.11.1251.0
PowerShell 5.1.18362.752
NeoVIM 0.4.3
```

**Comment by GregoryHorvath** [comment]
+1

```
Windows Terminal
Version: 1.0.1401.0
```

**Comment by glacambre** [comment]
I think a PR that improves keyboard handling on windows has been merged 
recently. Can you still reproduce this issue on nightly?

**Comment by GregoryHorvath** [comment]
> I think a PR that improves keyboard handling on windows has been merged recently. Can you still reproduce this issue on nightly?

@glacambre Awesome, working fine with nightly at least for me! Thanks for the quick reply.

**Comment by JosephSamela** [comment]
Working for me on `v0.5.0-539-g91e41c857`!
