### ISSUE TITLE
ci: gcov: "merge mismatch" errors

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10332]
This issue is meant to track "merge mismatch" errors due to using gcov.

With https://travis-ci.org/neovim/neovim/jobs/550297606 (restarted) "merge mismatch" errors showed up:

> profiling:/home/travis/build/neovim/neovim/build/src/nvim/CMakeFiles/nvim.dir/fileio.c.gcda:Merge mismatch for function 48

*edit*: Restarting it then worked - so likely not a ccache issue.

I will try clearing the ccache with gcov jobs, to ensure it is not causing problems in this regard.

https://travis-ci.org/neovim/neovim/jobs/553494382:
> profiling:/home/travis/build/neovim/neovim/build/src/nvim/CMakeFiles/nvim.dir/shada.c.gcda:Merge mismatch for function 5

**Comment by blueyed** [comment]
After https://github.com/neovim/neovim/pull/10404:

### Travis

> build/src/nvim/CMakeFiles/nvim.dir/ops.c.gcda:Merge mismatch for function 62

**Comment by blueyed** [comment]
For reference: https://github.com/neovim/neovim/pull/10480 was merged now, using gcc9 for the coverage job on Linux.  Hopefully this fixes problems in this regard, but should at least provide `GCOV_ERROR_FILE` now.

**Comment by justinmk** [comment]
related: https://github.com/neovim/neovim/issues/13312

Let's see how it goes if/when we restore the gcov build job.
