### ISSUE TITLE
nvi much faster than neo/vim

### ISSUE THREAD

**Issue by drozdowsky** [neovim/neovim#10338]
```
NVIM v0.3.7
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -g -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/neovim-0.3.7/build/config -I/builddir/neovim-0.3.7/src -I/usr/include -I/builddir/neovim-0.3.7/build/src/nvim/auto -I/builddir/neovim-0.3.7/build/include
Compiled by void-buildslave@a-hel-fi
Features: +acl +iconv -jemalloc +tui
```

Void Linux with ST terminal
VIM 8 is probably experiencing the same problem

### Steps to reproduce using `nvim -u NORC`
Assuming we start in normal mode, type:
```
1000000atest
```
And then ESC
This should type test 1kk times, right?

### Actual behaviour
It takes ages.

### Expected behaviour
It should take seconds as in nvi (around second)

**Comment by justinmk** [comment]
This is an old meme. http://www.galexander.org/vim_sucks.html

> I opened a new session in each and typed "1000000aaoeu^[", which adds 4MB of "aoeuaoeuaoeuaoeu...." to the buffer. nvi finished that operation in about a second ... However, vim is still chunking. 

It's covered by other performance tickets. It has also been on Bram's [todo.txt](https://github.com/vim/vim/blob/master/runtime/doc/todo.txt) for a few decades.

**Comment by drozdowsky** [comment]
Can you referance related issue?
I want to see why this issue is hard to resolve
