### ISSUE TITLE
Not allowed in a modeline: fs

### ISSUE THREAD

**Issue by yutakatay** [neovim/neovim#10350]
- `nvim --version`: NVIM v0.4.0-1155-gc62690ccc
- Vim (version: ) behaves differently? yes (VIM 8.1 Included patches: 1-1467)
- Operating system/version: ArchLinux(x86_64)
- Terminal name/version: Alacritty 0.3.3
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

1. create main.rs file

``` rust
fn main() {
    let _ = ex::fs::remove_dir_all("/foo/bar");
}
```

2. `nvim -u NORC main.rs`

3. Error message is displayed

```
Error detected while processing modelines:
line    3:
E520: Not allowed in a modeline: fs
Press ENTER or type command to continue
```

### Actual behaviour

Error message is displayed

### Expected behaviour

No error message

**Comment by justinmk** [comment]
set nomodeline

If you don't want modeline feature. `ex:` triggers modeline feature .

**Comment by yutakatay** [comment]
NeoVim default is modeline. Vim default is nomodeline. 

So I set nomodeline.
It was fixed. Thank you :smile:

**Comment by justinmk** [comment]
> Vim default is nomodeline.

No. Vim default is `modeline`, but your distro overrides the Vim default. See `:help 'modeline'` in Vim.

**Comment by yutakatay** [comment]
Oh, it's true! I understand.  Thank you for your support :joy:

**Comment by erw7** [comment]
@yutakatay The manual(`:h modeline`) does not say that the modeline allows empty options(`::`). What about trying to create a vim issue?

@justinmk  The current vim works as follows:

> Using the "-u" argument with another argument than DEFAULTS has the side effect that the 'compatible' option will be on by default.

Therefore, I think that it is necessary to execute with `vim -u NORC -N` or `vim -u DEFAULTS` when comparing with neovim. I think that it is better to write this in the issue template.

**Comment by justinmk** [comment]
@erw7 added to https://github.com/neovim/neovim/pull/10177

**Comment by yutakatay** [comment]
@erw7 Thank you for your comment.
I checked the specification of modeline. It seems to be acceptable as a specification. So I decided not to write a vim issue.

```
					*modeline* *vim:* *vi:* *ex:* *E520*
There are two forms of modelines.  The first form:
	[text]{white}{vi:|vim:|ex:}[white]{options}

[text]			any text or empty
{white}			at least one blank character (<Space> or <Tab>)
{vi:|vim:|ex:}		the string "vi:", "vim:" or "ex:"
[white]			optional white space
{options}		a list of option settings, separated with white space
			or ':', where each part between ':' is the argument
			for a ":set" command (can be empty)
```
