### ISSUE TITLE
Break visual line without breaking line

### ISSUE THREAD

**Issue by yashamon** [neovim/neovim#10367]
This is more a question then an issue: Is it possible to break visual line without breaking line?

For example i have text here: some text follows <insert visual break > 
<cursor now here> keep writing. But both these sentences is one wrapped line. 

I can imagine a brute force solution, count the number of character spaces from cursor to textwidth limit, insert that many blank spaces.

**Comment by justinmk** [comment]
You are missing some formatting thus your example isn't going to show correctly on github.

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by RRethy** [comment]
@yashamon I think you want `:set wrap` and potentially `set linebreak`.

**Comment by yashamon** [comment]
> @yashamon I think you want `:set wrap` and potentially `set linebreak`.

That doesn't work as pressing enter will hard break the line.

**Comment by yashamon** [comment]
Hi Justin, after doing some research I don't think it is possible to configure this. So could you please reopen as a feature request?
