### ISSUE TITLE
Make it easier to wait on a callback

### ISSUE THREAD

**Issue by SevereOverfl0w** [neovim/neovim#10362]
There's currently no easy way to wait for a callback from a supposed API on the main thread.  Proposed workarounds (untested):

- Sleep using `:sleep` then use `nvim_input('<C-c>')` to interrupt the sleep.
- Use `getchar()` in a loop to "eat" input until `<C-c>` is pressed.

**Comment by SevereOverfl0w** [comment]
Downside of these workarounds is that the normal effect of queuing up character presses is lost.

**Comment by abdelhakeem** [comment]
Another quick and dirty but not neat workaround is to start a dummy job, call `jobwait`, and at the tail of the callback kill that job. Meanwhile, something like `callbackwait` or whatever can be introduced, callback identification might be an issue though.

**Comment by justinmk** [comment]
> callback identification might be an issue though

Can't it just wait on any arbitrary condition? E.g.:

```vim
func! Callback()
  ...
  let s:foo += 1
endf
call wait(s:foo > 0)
```

Might be easy to implement using `LOOP_PROCESS_EVENTS_UNTIL`.

**Comment by bfredl** [comment]
implementing `wait({-> condition})` should be simple enough. Alternatively some kind of `loop_once()` function (return after processing one (possibly blocking) iteration of the loop) , so that `wait(cond)` is equivalent to:

```
while !condition
   call loop_once()
endwhile
```

**Comment by justinmk** [comment]
@bfredl Nice. Does `:lua vim.loop.run()` already achieve that? I'm still in favor of `wait()` (name subject to debate) for user convenience.

**Comment by bfredl** [comment]
>  Does :lua vim.loop.run() already achieve that?

This will only run the "inner" uv loop (which includes only "fast" lua callbacks). From vimL context (and many lua plugins) to run the "main loop" also implies process the main event queue. But I argree `wait()` is common enough to be useful as builtin even if it can be expressed as lower-level builtins.

**Comment by abdelhakeem** [comment]
I'm experimenting with some implementation for `wait` (aka `waituntil`) which expects an expression for the condition (just like `{expr2}` in `filter()`)

As for `LOOP_PROCESS_EVENTS_UNTIL`, the first two arguments are `&main_loop` and `main_loop.events`, I'm not very familiar with this multiqueue stuff so tell me if I'm missing something here.
