### ISSUE TITLE
Neovim+Lexplore clears current buffer after opening a new one

### ISSUE THREAD

**Issue by cuharobin** [neovim/neovim#10361]
- `nvim --version`: 0.3.7
- Operating system/version: Windows/x64
- Terminal name/version: Neovim-Qt

### Steps to reproduce:
```
- Open any file with neovim;
- Edit anything in this file;
- Save changes;
- Do another editing in this file;
- Open another file through :Lexplore, without saving the old one.
- Switch to the buffer with the first file.
```

### Actual behaviour
The old buffer will have all the changes discarded. You also can't do **u**ndo any more.
### Expected behaviour
Old buffers should retain their unsaved changes after any new one opened.

### Comments
I guess this can actually be usual behaviour (not a bug), but it's quite annoying. Every buffer retain its unsaved changes and change (undo) history just until new buffer opens. Since buffers is the instrument that fulfills role of tabs in other editors, there should be an opportunity to open a new file without losing all change history and unsaved changes.

**Comment by bfredl** [comment]
Seems like a bug that `:Lexplore` inhibits the confirm dialog (which should allow you to save or cancel before unloading the buffer). Does recent vim behave the same or not?

A workaround could be to use `:set hidden` option.

**Comment by justinmk** [comment]
This is an old netrw bug. We don't maintain netrw, I would sooner replace it with [dirvish](https://github.com/justinmk/vim-dirvish/) before spending time debugging netrw. #4378

> Does recent vim behave the same or not?

If it's fixed in recent Vim we'll get the fix when I get a chance to update the runtime files for Nvim. Otherwise report to https://github.com/vim/vim/
