### ISSUE TITLE
grid_line UI event: cells might be number?

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10372]
In https://travis-ci.org/neovim/neovim/jobs/552189475 there was a test failure:

```
Running tests from /Users/travis/build/neovim/neovim/test/functional/ex_cmds/digraphs_spec.lua
[ RUN      ] :digraphs displays digraphs: ERR
test/functional/helpers.lua:229: test/functional/ui/screen.lua:868: bad argument #1 to 'unpack' (table expected, got number)
stack traceback:
	test/functional/helpers.lua:229: in function 'run_session'
	test/functional/ui/screen.lua:513: in function '_wait'
	test/functional/ui/screen.lua:366: in function 'expect'
	.../neovim/neovim/test/functional/ex_cmds/digraphs_spec.lua:25: in function <.../neovim/neovim/test/functional/ex_cmds/digraphs_spec.lua:23>
```

The unpack error happened in https://github.com/neovim/neovim/blob/c0f8e35123a0f238a8eb0d62649fb712465414a0/test/functional/ui/screen.lua#L868, where `items` should be a table of cells, but apparently was a number?!

The "grid_line" only gets emitted via https://github.com/neovim/neovim/blob/c0f8e35123a0f238a8eb0d62649fb712465414a0/src/nvim/api/ui.c#L551.

What might be wrong there?

**Comment by justinmk** [comment]
duplicate of https://github.com/neovim/neovim/issues/8102 .

**Comment by bfredl** [comment]
I wonder if this is a memory corruption issue mostly/only visible on OS X. Maybe it would be interesting to run ASAN on OS X?
