### ISSUE TITLE
Highlights added with nvim_buf_add_highlight do not "move" horizontally

### ISSUE THREAD

**Issue by cdelledonne** [neovim/neovim#10399]
I've searched existing issues but I couldn't find anything, forgive me and let me know in case there is already some discussion going on somewhere.

- `nvim --version`: NVIM v0.4.0-1189-g10a533e9d
- Operating system/version: macOS 10.14.5 (Mojave)
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Launch `nvim -u NORC`, then start editing a new buffer and insert the following
```
This is a test
```

Now, add a position-based highlight to the word `test`
```
:call nvim_buf_add_highlight(0, 0, "Search", 0, 10, 14)
```

Depending on the colorscheme, you should get something like

![Screenshot 2019-07-02 at 13 14 15](https://user-images.githubusercontent.com/24732205/60508658-58958980-9ccb-11e9-85f5-579c604205c9.png)

Now, replace the word `a` with `another`. The result should be

![Screenshot 2019-07-02 at 13 13 40](https://user-images.githubusercontent.com/24732205/60508755-a4483300-9ccb-11e9-8230-69e1415aab4f.png)

### Actual behaviour

The behaviour described above is in line with what `nvim_buf_add_highlight` claims it does, that is,

> highlights follow changes to line numbering (as lines are inserted/removed above the highlighted line)

but highlights do not follow changes to a line that contains a highlight.

### Expected behaviour

It would be great if position-based highlights could follow all text changes, rather than stick to a particular column range on a line. Is there any fundamental limitation that makes this complicated?

**Comment by bfredl** [comment]
It would be relatively simple to make this track insert mode changes (and within-line normal deletes), by just using #10190 , though this will create an uncanny valley of highlights sometimes being tracked and sometimes not (this is currently the state of vim text properties).  For "full" support we need to wait for #5031
