### ISSUE TITLE
Untie Diffing From Tabpages (and maybe windows). Multiple solutions suggested.

### ISSUE THREAD

**Issue by atimholt** [neovim/neovim#10403]
- `nvim --version`: any
- `vim -u DEFAULTS` (version: ) behaves differently? n/a
- Operating system/version: any
- Terminal name/version: any
- `$TERM`: n/a

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour

Viewing diffs is tied to the current tabpage, disallowing multiple different diffs in the same tab, and requiring both diffed buffers to have a window in the current tab.

#### First Suggestion

Nothing should be done to break current behavior. Current behavior can be the default (as implemented with the new functionality) if the current commands are augmented with more arguments.

A diffed buffer should be as flexible as a regular buffer. One solution is to have a set of window-local settings that dictate which buffer(s) to diff with. A diff toggle would be useful if one wishes to turn on/off a diff view, so you don’t have to diff and edit in different windows.

This runs into problems when you want to be able to switch between different diffs in the same window (against the window’s buffer), and it makes it difficult to keep multiple windows that are diffed against each-other in parallel states, but this might be considered good enough.

#### Second suggestion

*__Note__: some of this wider-scope suggestion can be applied separately to the first suggestion, if desired.*

My other suggestion fixes these problems, but expands the scope in ways that might be considered too drastic. My other suggestion is to create a sort of “meta buffer”. A “diff object” would be a list of buffers that the editor has been asked to be able to open diff windows from.

For some uses, it might make sense to have a diff object list every buffer that is considered a different version of the other entries in the list (as chosen by the user, or automatable by plugins, such as fugitive or undotree). Then the simpler functionality of multiple diff objects that may contain the same buffer(s) can be avoided by creating subset objects that refer to the diff object. This could be done automatically when a new diff is started with buffer(s) present in an existing diff object. It may be desirable to allow a window-local diff object subset, and maybe even give the window-local version the ability to specify which buffer the window is actually editing, to allow switching between versions. Or just supply easy facility to switch between buffers within a top-level diff list or subset.

It may be desirable to allow naming of a top-level diff list, since they *are* supposed to be different versions of the same buffer. It is likely they would have an easily determined name—by the user or plugin writer. Perhaps an implementation-provided default name could be determined by the largest shared string subset of the greatest number of buffer names in the list. A tendency to break at directory dividing characters may be desired.

Considering the ability to have just one window of a diff in the current tab-page, a new kind of diff view may be desired. A sort of unified view, expanded from the current implementation, would contain the “removed” lines as special display-only text, with the correct line numbers for the other buffer (in a different color). This would be different from a new buffer containing output from a unified diff command/external program, because editing it would affect the window’s buffer (and *not* the other buffer being diffed. No “diffput”, or maybe at least optional, off by default).

A visual-mode `:diffget` or `do` normal mode command would be appreciated, and more implementable with a unified diff. If the cursor can enter the “not this buffer” section of the unified diff, individual lines could be selected for a `do`.

In a ≥3-way diff in a unified view, the sign column may be useful to distinguish which buffer certain lines come from. Perhaps the symbols used could be in a setting, like a string that is split between every character. This may be a hard problem, but there are potential solutions. Perhaps entering a “not this buffer” line displays the buffers the change comes from in the command line, along with their character sign (widen the sign column in >2 overlaps? Only indicate one buffer it comes from?).

A way to view top-level diff lists and sub lists would be desired. It should be something similar to the `:tabs` and `:buffers` commands, leaning towards `:tabs` because there’s a couple layers of hierarchy here.

All of this can be ignored by the end-user, but could still serve as a new backbone for the old diffing style by emulating it through default behaviors or re-implementation of old commands in terms of the new functionality. Expansion of old functionality would allow the user to ignore the new functionality for most of a session, then call upon it when they need to.

Defaulting to old behavior also hides the complexities of the new system, if it is believed the new system is too much of a mental burden. Most of the mental burden should *probably* be packaged together in mappings/command options/plugins, so the complexity doesn’t affect the user, but still allows powerful usage. The implementation itself should probably add new ways of dealing with diffs that may simply be pre-defined, desirable behavior, based off smaller building blocks, akin to the multiple commands executed by a new-functionality-defined “`:diffthis`”

Some old behaviors may require more input in ambiguous situations, like using “`:diffthis`” in a tab with multiple unrelated diffs. Implementation should favor default behavior that mostly behaves in the old way. In the case of `:diffthis`, tabs could keep track of which diff to diff with by default, say either the first one on scene, or the latest (I lean toward latest), and settable in a tab-local setting. Behavior could be inverted (first diff↔latest diff) by adding a “`:diffthis!`”, and/or adding a (defaultable) argument to `:diffthis` (allowing *any* diff in the current tab).

**Comment by justinmk** [comment]
Thanks for the thoughtful writeup! But this needs to be broken into separate tickets with clear requests.

> A visual-mode `:diffget` or `do` normal mode command .... If the cursor can enter the “not this buffer” section of the unified diff, individual lines could be selected for a `do`.

Potentially good idea(s).

> Viewing diffs is tied to the current tabpage, disallowing multiple different diffs in the same tab, and requiring both diffed buffers to have a window in the current tab.

Viewing tabs side-by-side will be possible with "tabgrid"  https://github.com/neovim/neovim/pull/7541 . 

In general it's unlikely that Neovim project will add big, complex changes to diff-mode. I think also that small diff-mode changes are more likely to get implemented if you request at https://github.com/vim/vim . We will merge the changes when our staff members at https://github.com/vim/vim implement them.
