### ISSUE TITLE
Cannot link to private copy of luv.so

### ISSUE THREAD

**Issue by mcepl** [neovim/neovim#10407]
- `nvim --version`: checkout from master e48257e63
- `vim -u DEFAULTS` (version: ) behaves differently? build error, NA
- Operating system/version: openSUSE/Tumbleweed
- Terminal name/version: gnome-terminal (not applicable, this is a build error)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

All Lua extension modules written in C are modules in the libtool terminology opened by dlopen and so they are stored in %{_libdir}/lua/%{lua_version}/ private directory (e.g., /usr/lib64/lua/5.1/lpeg.so) and they are called only by Lua interpreter, which knows to look for them there. Now, however, neovim decided to luv Lua library and link to it.

Bundling in external libraries is strictly forbidden in openSUSE (and any other Linux distribution, or perhaps any Unix packages), so I tried to use luv library from the standard Lua extension module. It is is located as a module in ``/usr/lib64/lua/5.1/luv.so`` and headers are in ``/usr/include/lua5.1/luv/``. The easiest way how to persuade neovim build system to accept this library seemed to me to be (abbreviated):
```rpm
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo \
       -DCMAKE_SKIP_RPATH=ON -DCMAKE_VERBOSE_MAKEFILE=ON \
       -DCMAKE_COLOR_MAKEFILE=OFF \
       -DCMAKE_C_FLAGS_RELWITHDEBINFO="$opts -Wl,-rpath %{_libdir}/lua/%{lua_version}" \
       -DCMAKE_INSTALL_PREFIX:PATH=%{_prefix} \
       -DLIBLUV_INCLUDE_DIR:PATH=%{lua_incdir} \
       -DLIBLUV_LIBRARY:FILEPATH=%{lua_archdir}/luv.so
```
and truly I can see in ``build/CMakeCache.txt`` line
```cmake
//No help, variable specified on the command line.
LIBLUV_INCLUDE_DIR:PATH=/usr/include/lua5.1

//No help, variable specified on the command line.
LIBLUV_LIBRARY:FILEPATH=/usr/lib64/lua/5.1/luv.so
```
However, even with having this configured, I get (in ``build/src/nvim/CMakeFiles/nvim.dir/link.txt``) cmake trying link to ``-lluv`` and ignoring ``/usr/lib64/lua/5.1/luv.so``.
[link.txt](https://github.com/neovim/neovim/files/3354097/link.txt)

Obviously attempt to link fails:
```
[   33s] /var/lib/build/ccache/bin/cc  -Wl,-rpath /usr/lib64/lua/5.1 -DMIN_LOG_LEVEL=3 -Og -g -flto -fno-fat-lto-objects   -Wl,--no-undefined -rdynamic CMakeFiles/nvim.dir/auto/msgpack_lua_c_bindings.generated.c.o CMakeFiles/nvim.dir/__/__/config/auto/pathdef.c.o CMakeFiles/nvim.dir/api/buffer.c.o CMakeFiles/nvim.dir/api/private/dispatch.c.o CMakeFiles/nvim.dir/api/private/handle.c.o CMakeFiles/nvim.dir/api/private/helpers.c.o CMakeFiles/nvim.dir/api/tabpage.c.o CMakeFiles/nvim.dir/api/ui.c.o CMakeFiles/nvim.dir/api/vim.c.o CMakeFiles/nvim.dir/api/window.c.o CMakeFiles/nvim.dir/arabic.c.o CMakeFiles/nvim.dir/aucmd.c.o CMakeFiles/nvim.dir/buffer.c.o CMakeFiles/nvim.dir/buffer_updates.c.o CMakeFiles/nvim.dir/channel.c.o CMakeFiles/nvim.dir/charset.c.o CMakeFiles/nvim.dir/cursor.c.o CMakeFiles/nvim.dir/cursor_shape.c.o CMakeFiles/nvim.dir/diff.c.o CMakeFiles/nvim.dir/digraph.c.o CMakeFiles/nvim.dir/edit.c.o CMakeFiles/nvim.dir/eval.c.o CMakeFiles/nvim.dir/eval/decode.c.o CMakeFiles/nvim.dir/eval/encode.c.o CMakeFiles/nvim.dir/eval/executor.c.o CMakeFiles/nvim.dir/eval/gc.c.o CMakeFiles/nvim.dir/eval/typval.c.o CMakeFiles/nvim.dir/event/libuv_process.c.o CMakeFiles/nvim.dir/event/loop.c.o CMakeFiles/nvim.dir/event/multiqueue.c.o CMakeFiles/nvim.dir/event/process.c.o CMakeFiles/nvim.dir/event/rstream.c.o CMakeFiles/nvim.dir/event/signal.c.o CMakeFiles/nvim.dir/event/socket.c.o CMakeFiles/nvim.dir/event/stream.c.o CMakeFiles/nvim.dir/event/time.c.o CMakeFiles/nvim.dir/event/wstream.c.o CMakeFiles/nvim.dir/ex_cmds.c.o CMakeFiles/nvim.dir/ex_cmds2.c.o CMakeFiles/nvim.dir/ex_docmd.c.o CMakeFiles/nvim.dir/ex_eval.c.o CMakeFiles/nvim.dir/ex_getln.c.o CMakeFiles/nvim.dir/file_search.c.o CMakeFiles/nvim.dir/fileio.c.o CMakeFiles/nvim.dir/fold.c.o CMakeFiles/nvim.dir/garray.c.o CMakeFiles/nvim.dir/getchar.c.o CMakeFiles/nvim.dir/hardcopy.c.o CMakeFiles/nvim.dir/hashtab.c.o CMakeFiles/nvim.dir/highlight.c.o CMakeFiles/nvim.dir/if_cscope.c.o CMakeFiles/nvim.dir/indent.c.o CMakeFiles/nvim.dir/indent_c.c.o CMakeFiles/nvim.dir/keymap.c.o CMakeFiles/nvim.dir/log.c.o CMakeFiles/nvim.dir/lua/converter.c.o CMakeFiles/nvim.dir/lua/executor.c.o CMakeFiles/nvim.dir/main.c.o CMakeFiles/nvim.dir/map.c.o CMakeFiles/nvim.dir/mark.c.o CMakeFiles/nvim.dir/math.c.o CMakeFiles/nvim.dir/mbyte.c.o CMakeFiles/nvim.dir/memfile.c.o CMakeFiles/nvim.dir/memline.c.o CMakeFiles/nvim.dir/memory.c.o CMakeFiles/nvim.dir/menu.c.o CMakeFiles/nvim.dir/message.c.o CMakeFiles/nvim.dir/misc1.c.o CMakeFiles/nvim.dir/mouse.c.o CMakeFiles/nvim.dir/move.c.o CMakeFiles/nvim.dir/msgpack_rpc/channel.c.o CMakeFiles/nvim.dir/msgpack_rpc/helpers.c.o CMakeFiles/nvim.dir/msgpack_rpc/server.c.o CMakeFiles/nvim.dir/normal.c.o CMakeFiles/nvim.dir/ops.c.o CMakeFiles/nvim.dir/option.c.o CMakeFiles/nvim.dir/os/dl.c.o CMakeFiles/nvim.dir/os/env.c.o CMakeFiles/nvim.dir/os/fileio.c.o CMakeFiles/nvim.dir/os/fs.c.o CMakeFiles/nvim.dir/os/input.c.o CMakeFiles/nvim.dir/os/lang.c.o CMakeFiles/nvim.dir/os/mem.c.o CMakeFiles/nvim.dir/os/process.c.o CMakeFiles/nvim.dir/os/pty_process_unix.c.o CMakeFiles/nvim.dir/os/shell.c.o CMakeFiles/nvim.dir/os/signal.c.o CMakeFiles/nvim.dir/os/stdpaths.c.o CMakeFiles/nvim.dir/os/time.c.o CMakeFiles/nvim.dir/os/tty.c.o CMakeFiles/nvim.dir/os/users.c.o CMakeFiles/nvim.dir/os_unix.c.o CMakeFiles/nvim.dir/path.c.o CMakeFiles/nvim.dir/popupmnu.c.o CMakeFiles/nvim.dir/profile.c.o CMakeFiles/nvim.dir/quickfix.c.o CMakeFiles/nvim.dir/rbuffer.c.o CMakeFiles/nvim.dir/regexp.c.o CMakeFiles/nvim.dir/screen.c.o CMakeFiles/nvim.dir/search.c.o CMakeFiles/nvim.dir/sha256.c.o CMakeFiles/nvim.dir/shada.c.o CMakeFiles/nvim.dir/sign.c.o CMakeFiles/nvim.dir/spell.c.o CMakeFiles/nvim.dir/spellfile.c.o CMakeFiles/nvim.dir/state.c.o CMakeFiles/nvim.dir/strings.c.o CMakeFiles/nvim.dir/syntax.c.o CMakeFiles/nvim.dir/tag.c.o CMakeFiles/nvim.dir/terminal.c.o CMakeFiles/nvim.dir/tui/input.c.o CMakeFiles/nvim.dir/tui/terminfo.c.o CMakeFiles/nvim.dir/tui/tui.c.o CMakeFiles/nvim.dir/ugrid.c.o CMakeFiles/nvim.dir/ui.c.o CMakeFiles/nvim.dir/ui_bridge.c.o CMakeFiles/nvim.dir/ui_compositor.c.o CMakeFiles/nvim.dir/undo.c.o CMakeFiles/nvim.dir/version.c.o CMakeFiles/nvim.dir/viml/parser/expressions.c.o CMakeFiles/nvim.dir/viml/parser/parser.c.o CMakeFiles/nvim.dir/window.c.o CMakeFiles/nvim.dir/xdiff/xdiffi.c.o CMakeFiles/nvim.dir/xdiff/xemit.c.o CMakeFiles/nvim.dir/xdiff/xhistogram.c.o CMakeFiles/nvim.dir/xdiff/xpatience.c.o CMakeFiles/nvim.dir/xdiff/xprepare.c.o CMakeFiles/nvim.dir/xdiff/xutils.c.o  -o ../../bin/nvim  -L/usr/lib64/lua/5.1 -lluv -luv -lrt -lpthread -ldl -ldl -lnsl -lrt -lmsgpackc -lvterm -ltermkey -lunibilium -lpthread -lm -lutil -lluajit-5.1 -lpthread -ldl -lnsl -lmsgpackc -lvterm -ltermkey -lunibilium -lpthread -lm -lutil -lluajit-5.1 
[   33s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: cannot find -lluv
[   33s] collect2: error: ld returned 1 exit status
```

### Expected behaviour
cmake should recognize that it should link against private module ``/usr/lib64/lua/5.1/luv.so`` and not against public ``luv`` library.

Full build log with all details [log.txt](https://github.com/neovim/neovim/files/3354152/log.txt)

**Comment by blueyed** [comment]
Not sure if you can override the `-lluv` already, but it might work better with/via the package config in the next luv release (https://github.com/luvit/luv/commit/df03f2ac6d4e7269cb0c88be3ef44cf1f0de9b24).

**Comment by blueyed** [comment]
Try maybe adding `-DCMAKE_EXE_LINKER_FLAGS+=-L%{lua_archdir}`.

**Comment by mcepl** [comment]
> Try maybe adding `-DCMAKE_EXE_LINKER_FLAGS+=-L%{lua_archdir}`.

Good try, but unfortunately it doesn't help. ``-lluv`` leads to searching for ``libluv.so``, which doesn't exist there (it is ``luv.so``).

**Comment by zhaozg** [comment]
Please https://github.com/luvit/luv#build-as-static-library, you need to generate libluv.a or libluv.so

**Comment by mcepl** [comment]
@zhaozg When I do
```rpm
%cmake -DCMAKE_C_FLAGS="$RPM_OPT_FLAGS" \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=OFF \
    -DBUILD_STATIC_LIBS=OFF -DCMAKE_INSTALL_DO_STRIP=OFF \
    -DBUILD_MODULE=ON -DBUILD_SHARED_LIBS=ON \
    -DWITH_SHARED_LIBUV=ON -DWITH_LUA_ENGINE=Lua \
    -DLUA_BUILD_TYPE=System -DLUA_COMPAT53_DIR="%{lua_incdir}/"
make
```
and get ``luv.so``, there is no hope of linking it with anything? Works just fine as a module to lua, and I would prefer not to do another build.

**Comment by zhaozg** [comment]
Try to rename luv.so to libluv.so

**Comment by mcepl** [comment]
In the end, I gave up and created a publish shared library ``libluv.so``, and now https://build.opensuse.org/package/show/home:mcepl:neovim/neovim builds again.

**Comment by blueyed** [comment]
I think https://github.com/neovim/neovim/pull/10661 would help here.

**Comment by blueyed** [comment]
@mcepl 
Can you provide feedback on / test https://github.com/neovim/neovim/pull/10661, please?

**Comment by mcepl** [comment]
> @mcepl
> Can you provide feedback on / test #10661, please?

Could you suggest, please, for an idiot, how to use it? When I have
```rpm
 /usr/bin/cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_SKIP_RPATH=ON \
-DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=OFF \
-DCMAKE_C_FLAGS_RELWITHDEBINFO="-Wl,-rpath /usr/lib64/lua/5.1' \
-DCMAKE_INSTALL_PREFIX:PATH=/usr \
-DLIBLUV_LIBRARY:FILEPATH=/usr/lib64/lua/5.1/luv.so \
-DLIBLUV_INCLUDE_DIR:PATH=/usr/include/lua5.1
```
but it still fails to build (
[log.txt](https://github.com/neovim/neovim/files/3464134/log.txt)). What do I do wrong?

**Comment by blueyed** [comment]
#10661 does not really help.
So on master, try using `-DLIBLUV_LIBRARY:STRING=-Wl,/usr/lib64/lua/5.1/luv.so` (instead of your existing `-DLIBLUV_LIBRARY:FILEPATH=/usr/lib64/lua/5.1/luv.so`).

**Comment by blueyed** [comment]
Going back to your use case: where is "luv/luv.h" coming from for you?  (how does it land in `%{lua_incdir}`?) (luarocks does not install it for me for example)
Is there a special lua-luv-dev package that you are using?

**Comment by mcepl** [comment]
Yes, openSUSE packages (see https://build.opensuse.org/package/show/devel:languages:lua/lua-luv for their definitions) generate lua51-luv-devel package with all those development files (required for development on top of luv package, not only its use). And no, exactly because of this, openSUSE (and other Linux distros) packages are not just simple translation of luarocks, but we have to reconstruct and do again all what luarocks do (and more).

**Comment by blueyed** [comment]
Where is `%{with public_lib}` coming from / being injected into https://build.opensuse.org/package/view_file/devel:languages:lua/lua-luv/lua-luv.spec?expand=1?

**Comment by mcepl** [comment]
> Where is `%{with public_lib}` coming from / being injected into https://build.opensuse.org/package/view_file/devel:languages:lua/lua-luv/lua-luv.spec?expand=1?

Line 25 (%bcond_with declares the boolean option public_lib set to 0). It is a standard way how to declare options in SPEC files.
