### ISSUE TITLE
After paste in command mode Vim stays in it

### ISSUE THREAD

**Issue by widgetii** [neovim/neovim#10415]
- `nvim --version`: 

```
NVIM v0.4.0-1208-g99b870d61
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/dima/.cache/pikaur/build/neovim-git/src/neovim-git/build/config -I/home/dima/.cache/pikaur/build/neovim-git/src/neovim-git/src -I/usr/include -I/home/dima/.cache/pikaur/build/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/dima/.cache/pikaur/build/neovim-git/src/neovim-git/build/include
Compiled by dima@trainer-arch

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?

N/A since Vim doesn't support clipboard providers

- Operating system/version: Archlinux and MacOS
- Terminal name/version: kitty 0.14.2
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```

Open NVim and copy&paste next block in normal mode:

```
:echom "line1"
:echom "line2"

```

### Actual behaviour

After its execution NVim still stays in paste mode: `:set paste?` = `paste`

### Expected behaviour

After paste is done NVim returns to nopaste mode

**Comment by blueyed** [comment]
Confirmed.  (Only) happens due to bracketed paste - and only happens with a missing newline, right?  (i.e. you have to press Enter for the 2nd echom)
Does not happen for me when also pasting the trainling newline.

Also it toggles it then, i.e. when doing it again it becomes `nopaste` again.

Related code for further investigation: https://github.com/neovim/neovim/blob/a79be7915fe84bb2b765f85f6feb91ebbcc24f04/src/nvim/tui/input.c#L338

**Comment by blueyed** [comment]
Related issues: https://github.com/neovim/neovim/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+paste+bracketed

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/10311 was an attempt to fix this. Anyways, full solution is https://github.com/neovim/neovim/pull/4448
