### ISSUE TITLE
cnoremap causes input to not be shown 

### ISSUE THREAD

**Issue by ilAYAli** [neovim/neovim#10423]
NVIM v0.4.0-1209-gefc6d9951
Build type: RelWithDebInfo

### Steps to reproduce:

```
The bug can most easily be described with the following asciinema:
https://asciinema.org/a/KmG8ozXZfFzmb9lR7dQyW4jOi

:cnoremap find Find
:find foo

```

### Actual behaviour
typing `find foo` causes the remapped input, `'f' 'i' 'n' 'd'`, in this example, to be output at the same position, until the mapping is resolved.

### Expected behaviour
sequential output of each typed character

**Comment by justinmk** [comment]
Vim has the same behavior. Not a bug.

**Comment by ilAYAli** [comment]
TIL. Indeed, unexpected behavior though.

**Comment by bfredl** [comment]
In other modes incomplete mappings are shown in the showcmd area, but it doesn't work in cmdline mode, as the cmdline is thought to occupy the same space (though it should be theoretically possible to enable it while the cmdline is short enough to not cover the showcmd area).

**Comment by ilAYAli** [comment]
Interesting. I expect that a non-overlapping cmdline/showcmd -area would be case in all but extremely rare cases?
It's not really a big deal, but the current behavior feels wrong/inconsistent, even though the experience is identical on vim.

**Comment by blueyed** [comment]
@ilAYAli 
Yes.  Please consider creating a feature request at https://github.com/vim/vim/issues/ - and then we would also get it through a patch from there.

**Comment by chrisbra** [comment]
That is the usual behaviour of mappings. You can use abbreviations instead (which may have other disadvantages however).
