### ISSUE TITLE
 windo resizes small vertically split windows

### ISSUE THREAD

**Issue by barisione** [neovim/neovim#10437]
- `nvim --version`: 0.3.8
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: macOS Mojave 10.14
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Type :vsplit
2. Make the current window big with CTRL-W and then `|` (pipe)
3. Type `:windo ''` (to do “nothing” in every window)

### Actual behaviour

The tiny window gets expanded.

### Expected behaviour

 Nothing visible happens.

I believe this happens because, when switching to a tiny vertically split window, Neovim helpfully makes it bigger so you see what you type.
With `windo` this is annyoing as I'm using it to automatically do some things in various windows but I don't want the layout to change.

The problem doesn't happen with horizontal splits as at least one line is left visible and Neovim doesn't need to expand the window when you switch to it.

As the issue affects Vim as well, I've reported it there as well: https://github.com/vim/vim/issues/4622.

**Comment by justinmk** [comment]
It's by design. Don't use windo for this.
