### ISSUE TITLE
doublewidth character not restored when closing float

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#10439]
- `nvim --version`: v0.4.0-1155-gc62690ccc
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: macOS 10.14.5
- Terminal name/version: mac builtin terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
1. nvim -u NONE
2. `:e float_test_file.txt`
3. `:so float_test.vim`
4. `<c-w><c-w>` and `:q` to close float window
5. You will find `试`   disappear

float_test_file.txt 
```txt

# TODO: foo bar
# TODO: 测试字典信息的准确性
```

float_test.vim
```vim
let buf = nvim_create_buf(v:false, v:true)
call nvim_buf_set_lines(buf, 0, -1, v:true, ["test", "text"])
let opts = {'relative': 'cursor', 'width': 8, 'height': 5, 'col': 3, 'row': 1, 'anchor': 'NW'}
let win = nvim_open_win(buf, 0, opts)
```
see [video](https://asciinema.org/a/IlDoGBvQ7B18omeNHTsCH5kvk).

**Comment by bfredl** [comment]
can reproduce.

**Comment by bfredl** [comment]
Thanks for the report, should be fixed on master.
