### ISSUE TITLE
broken layout with diff command -d

### ISSUE THREAD

**Issue by marxin** [neovim/neovim#10448]
After a recent update of TW I see a broken layout with nvim in diff mode (-d) when a scroll down. I attach a screenshot before and after CTRL-L.

I tested that this is broken:
```
$ env | grep TERM
COLORTERM=1
TERM=xterm-256color
```

If I test this:
```
$ TERM=xterm /usr/bin/nvim -d 
```

it's broken. But TERM=linux is fine. I'm using gnome-terminal, but I see the same in KDE konsole. Note that vim is fine and I've also tried to build a bit older nvim release and it's also broken on the TW.

Broken view:
![nvim-bad](https://user-images.githubusercontent.com/2658545/60790708-6a12e180-a162-11e9-98e8-5f9521160dc1.png)

After CTRL-L:
![nvim-after-ctrl-l](https://user-images.githubusercontent.com/2658545/60790712-6d0dd200-a162-11e9-87ba-d3ee479c618c.png)

**Comment by blueyed** [comment]
Thanks for the report.

>  I've also tried to build a bit older nvim release

So 0.3.8 is affected?
Have you tried master also?

What is TW?

**Comment by marxin** [comment]
> So 0.3.8 is affected?

Yes please, I've just verified that.

> Have you tried master also?
> 
> What is TW?

It's openSUSE Tumbleweed, the openSUSE rolling distribution system.

**Comment by blueyed** [comment]
Can you provide input files and steps to reproduce this?

**Comment by marxin** [comment]
> Can you provide input files and steps to reproduce this?

Sure:

```
$ yes | head -n 1000 > /tmp/1
$ yes n | head -n 1000 > /tmp/2
$ nvim -d /tmp/1 /tmp/2
[press PageDown]
screen should be broken
```

**Comment by justinmk** [comment]
cannot reproduce. what is the exact `:version`? Next time, use the issue template which has fields for all of the info that was provided in followup questions here.

**Comment by blueyed** [comment]
Cannot reproduce either (urxvt, kitty).
Does it also happen with `nvim -u NONE …`?

**Comment by marxin** [comment]
> Does it also happen with `nvim -u NONE …`?

Yes please.

**Comment by mcepl** [comment]
> cannot reproduce. what is the exact `:version`? Next time, use the issue template which has fields for all of the info that was provided in followup questions here.

It is from this package https://build.opensuse.org/package/show/openSUSE:Factory/neovim in openSUSE.

**Comment by justinmk** [comment]
AFAICT that looks like 0.3.x. Try master. And use the issue template next time.

**Comment by mcepl** [comment]
> AFAICT that looks like 0.3.x. Try master. And use the issue template next time.

What?? I thought that 0.3.* is still supported? What is the latest officially supported release of neovim we should ship in openSUSE?

**Comment by justinmk** [comment]
0.3 is supported. But for this issue, I am just suggesting to try master...

**Comment by blueyed** [comment]
Yes, it would be supported, but we cannot reproduce it.

> After a recent update of TW

So it might be caused by some updated library.

It would help if you could try it when building it yourself, both with `make USE_BUNDLED=1` (default) and `make distclean && make USE_BUNDLED=0` to figure out what might be causing it.

@mcepl 
So you are also seeing this?

**Comment by blueyed** [comment]
I think it was also mainly closed because it was not using the issue template.
I'll re-open for now.

**Comment by justinmk** [comment]
I closed because I am guessing it doesn't happen on master.

**Comment by marxin** [comment]
I can confirm it's also broken for current master (71e0768e08ffe88be1ae0b8d1580df3ef3e0c059):
```
$ make USE_BUNDLED=1
$ ./build/bin/nvim -u NONE -d /tmp/1 /tmp/2
(same happens)
````

```
$ ./build/bin/nvim -v
NVIM v0.4.0-1241-g71e0768e0
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/marxin/Programming/neovim/build/config -I/home/marxin/Programming/neovim/src -I/home/marxin/Programming/neovim/.deps/usr/include -I/usr/include -I/home/marxin/Programming/neovim/build/src/nvim/auto -I/home/marxin/Programming/neovim/build/include
Compiled by marxin@marxinbox.suse.cz
```

**Comment by blueyed** [comment]
Can you try it with Vim also?

It still sounds like it might be caused by some other update in TW then - can you see what was updated that might be causing this?

**Comment by marxin** [comment]
> Can you try it with Vim also?

Yes, `vim` is fine.

> 
> It still sounds like it might be caused by some other update in TW then - can you see what was updated that might be causing this?

That would be quite difficult, I've seen many updated packages recently. Can you please name the best candidates I can start with?

**Comment by mcepl** [comment]
> That would be quite difficult, I've seen many updated packages recently. Can you please name the best candidates I can start with?

Well (that’s my own build from the ``HEAD`` of the git repo, not the standard TW package):
```
~$ rpm -qR neovim
/bin/sh
config(neovim) = 0.4.0~git.1562515621.38342d75f-3.4
gperf
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libc.so.6(GLIBC_2.7)(64bit)
libluajit-5.1.so.2()(64bit)
libluv.so.1()(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libm.so.6(GLIBC_2.29)(64bit)
libmsgpackc.so.2()(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libtermkey.so.1()(64bit)
libunibilium.so.4()(64bit)
libutil.so.1()(64bit)
libutil.so.1(GLIBC_2.2.5)(64bit)
libuv.so.1()(64bit)
libvterm.so.0()(64bit)
lua51-bit32
python3-neovim
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
rpmlib(TildeInVersions) <= 4.10.0-1
xsel
~$
```

**Comment by mcepl** [comment]
@marxin Cannot reproduce with:
```
~$ env|grep TERM
COLORTERM=truecolor
LESS_TERMCAP_se=
LESS_TERMCAP_so=
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/ba259592_6878_4089_b3f5_c5797152621a
TERM=xterm-256color
LESS_TERMCAP_mb=
LESS_TERMCAP_me=
LESS_TERMCAP_md=
GNOME_TERMINAL_SERVICE=:1.576
LESS_TERMCAP_ue=
LESS_TERMCAP_us=
~$ 
```
(that’s gnome-terminal on Tumbleweed) ``nvim -d`` works just fine. Try my packages from https://build.opensuse.org/package/show/home:mcepl:neovim/neovim to get the latest mater build.

**Comment by justinmk** [comment]
> After a recent update of TW I see a broken layout with nvim in diff mode (-d) when a scroll 

did that update also update your terminal ? And possibly other things like terminfo definitions.

Most likely this is a terminfo issue.

**Comment by marxin** [comment]
> (that’s gnome-terminal on Tumbleweed) `nvim -d` works just fine.

Interesting as I have the same ENV values as you have.

> Try my packages from https://build.opensuse.org/package/show/home:mcepl:neovim/neovim to get the latest mater build.

I've just tried that and it's also broken :/

**Comment by justinmk** [comment]
> but I see the same in KDE konsole. 

With TERM=xterm? That's not correct for konsole. Try 

    TERM=konsole-256color nvim

> Note that vim 

Vim tends to work around terminfo in more/different cases than Nvim.

>  I've also tried to build a bit older nvim release and it's also broken on the TW.

Which strongly suggests this is terminfo/environment-related.

**Comment by marxin** [comment]
Works for me with `TERM=gnome-256color`, so I'm closing that then.

**Comment by blueyed** [comment]
Just for reference: https://github.com/neovim/neovim/pull/11027 might be related to this - at least it fixes redraw issues when scrolling in diff views.
