### ISSUE TITLE
Selecta was broken by the system() rewrite

### ISSUE THREAD

**Issue by rschmitt** [neovim/neovim#1044]
[Selecta](https://github.com/garybernhardt/selecta), a fuzzy selector (sort of like a generalized CommandT), recently stopped working with Neovim. I used a git bisect to trace the issue back to 6f30b25f455d30bb31b143b292f5d080ff64b4a3. Up through 3d3b233df8a5366180709435bbf77c0d0c48e380, Neovim worked with selecta perfectly; now it doesn't register any keyboard input at all.

By way of background, selecta works by opening `/dev/tty` directly. It takes a list of choices from stdin and produces the chosen option on stdout; all other user interaction is conducted directly through `/dev/tty`. Integrating vim with selecta is done with a bit of vimscript:

```viml
" Run a given vim command on the results of fuzzy selecting from a given shell
" command. See usage below.
function! SelectaCommand(choice_command, selecta_args, vim_command)
  try
    silent let selection = system(a:choice_command . " | selecta " . a:selecta_args)
  catch /Vim:Interrupt/
    " Swallow the ^C so that the redraw below happens; otherwise there will be
    " leftovers from selecta on the screen
    redraw!
    return
  endtry
  redraw!
  exec a:vim_command . " " . selection
endfunction

" Find all files in all non-dot directories starting in the working directory.
" Fuzzy select one of those. Open the selected file with :e.
nnoremap <leader>f :call SelectaCommand("find * -type f", "", ":e")<cr>
```

**Comment by justinmk** [comment]
Closing this as "wontfix", use `:term` instead.

**Comment by rschmitt** [comment]
Can you give an example of how to use `:term` instead of `system` in this case? It's not clear how to capture the stdout of a command, for instance.

**Comment by ZyX-I** [comment]
@rschmitt After opening a buffer with terminal use `getline()` as usual for non-terminal buffers.

**Comment by tarruda** [comment]
> Can you give an example of how to use :term instead of system in this case? It's not clear how to capture the stdout of a command, for instance.

@rschmitt you could use shell redirection and a fifo to split stdout data from a program running under `:term`, here's an idea: https://github.com/neovim/neovim/issues/2836#issuecomment-111749276

A simpler solution may be to use a temporary file and read it after the terminal program has exited, see [fzf](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim)
