### ISSUE TITLE
Scrolling performance regression 0.4.0 vs 0.3.8

### ISSUE THREAD

**Issue by dmcyk** [neovim/neovim#10460]
* `nvim --version`:

```
NVIM v0.4.0-1245-g42bdccdf6
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

* Vim (version: ) behaves differently?
  _nvim version `0.3.8` has better performance_
* Operating system/version: `macOS Catalina 10.15 Beta (19A501i) (Beta 3)`
* Terminal name/version: doesn't seem to be relevant, I can reproduce it on my iTerm2 setup as well as stock `Terminal.app`

### Steps to reproduce using `nvim -u NORC`
I'm testing on a neovim config file with ~940 lines, using a measure command to precisely compare timing.

Here's a test file: [init.vim](https://github.com/neovim/neovim/files/3374084/init.vim.txt)

```
1. nvim -u NORC init.vim
2. Set cursor at first line in the file
3. :let g:profstart=reltime() | for i in range(1,900) | exec "normal \<C-E>" | redraw | endfor | echo reltimestr(reltime(g:profstart)) . ' seconds'
```

Example output for nvim **0.4.0**:

```
1.150760 seconds
```

Example output for nvim **0.3.8**:

```
0.495297 seconds
```

there's also some difference with homebrew-installed vim 8.1.1600 (when using `-u DEFAULTS`), e.g. `0.387572 seconds`

### Additional information

This seems to be unrelated to another scrolling issue with syntax on #10328.
I've tried a patch suggested at https://github.com/neovim/neovim/issues/10328#issuecomment-509024305 but it did not seem to result in performance on pair with neovim 0.3.8.

I've also tested this on another device running `macOS Mojave 10.14.5` and difference there between both neovim versions weren't as large. e.g. `0.24 sec on 0.3.8` and `0.28 sec on 0.4.0`.

**Comment by justinmk** [comment]
> on another device running `macOS Mojave 10.14.5` and difference there between both neovim versions weren't as large. e.g. `0.24 sec on 0.3.8` and `0.28 sec on 0.4.0`.

That is "no difference". 

So this seems environmental. You can use "snapshot profiling" to find the bottleneck: 

1. put your steps in a loop so that it runs over and over:
   ```vim
   func! Test() abort
     while 1
       0
       let g:profstart=reltime() | for i in range(1,900) | exec "normal \<C-E>" | redraw | endfor | echo reltimestr(reltime(g:profstart)) . ' seconds'
     endwhile
   endf
   ```
2. `:call Test()`
2. From another terminal, attach gdb: `gdb /path/to/nvim {process-id}`
3. Get the backtrace using the gdb command: `bt`
4. continue using the gdb command `c`
5. Go to step 3, get another backtrace.

Collect 5-10 backtraces, then list them here.

Performance for me using your steps is within 10% when comparing Vim 8.1.1587 and Nvim 0.4. Not the 200% difference you are seeing.

**Comment by dmcyk** [comment]
Would time profiling would be maybe more useful?
Here are Instruments profiles of running that test function for 30 seconds.

# Heaviest stack trace

## 0.4.0

<img width="256" alt="0 4 0" src="https://user-images.githubusercontent.com/11983153/60942444-ed5b4100-a2e2-11e9-9e74-8fd90bb878ce.png">

## 0.3.8

<img width="259" alt="0 3 8" src="https://user-images.githubusercontent.com/11983153/60942445-edf3d780-a2e2-11e9-9056-e4637e68ea69.png">

# Run time

The instruments file reports `14.18 sec` of total activity time for neovim 0.3.8, for 0.4.0 it was only `9.54 sec`. And for both heaviest stacks are like almost the same. Seems maybe like rendering is less performant?

[instrumentscli0.0.3.8.trace.zip](https://github.com/neovim/neovim/files/3375829/instrumentscli0.0.3.8.trace.zip)

[instrumentscli0.0.4.0.trace.zip](https://github.com/neovim/neovim/files/3375830/instrumentscli0.0.4.0.trace.zip)

**Comment by justinmk** [comment]
`get_syntaxatrr`, `nfa_regmatch` ... Vim syntax stuff. Maybe just a difference in the runtime files, or maybe `win_line` is calling those more often. We certainly added more UI features since then.

**Comment by dmcyk** [comment]
@justinmk seems like #10564, or something in between solved the issue. I have trouble building luajit locally, but using latest nightly example time was `~0.18 sec`, thanks! 👌

nightly version I used was:
```
NVIM v0.4.0-1426-g0e23ee3cc
Build type: Release
```
