### ISSUE TITLE
`execute('syn list vimComment')` lacks newline between matches

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#10467]
- `nvim --version`:        NVIM v0.4.0-1257-g777cc6f98 Build type: Release
 - Vim (version:  8.1 Included patches: 1-1661) behaves differently? Yes
 - Operating system:     Ubuntu 16.04.6 LTS
 - Terminal emulator:    st 0.8.2
 - Terminal multiplexer: tmux next-3.1
 - `$TERM`:                tmux-256color
 - Shell:                zsh 5.7.1 (x86_64-pc-linux-gnu)

### Steps to reproduce using `nvim -u NORC`

Consider this shell command:

    $ nvim -Nu NONE --cmd 'syntax enable' +"echo execute('syn list vimComment')" /tmp/vim.vim

### Actual behaviour

It outputs the definition of the syntax group `vimComment` on a single line.

### Expected behaviour

I would expect the output to be on multiple lines, because:

 1. the output of the same command is on multiple lines in Vim
 2. the output of the same command without `execute()` (i.e. `:syn list vimComment`) is on multiple lines in Nvim
 3. it's harder to detect when the definition of an item ends when they are all on the same line

---

I'm relying on the output of `execute('syn list someSyntaxGroup')` to override the definition of some syntax groups, and other things (like highlight groups).
The more consistent the output of `execute()` is with Vim and with the command it's running, the easier it is to parse it.
Although it's probably a bad idea to parse the output of `execute()` considering all the issues I faced with it so far, I don't know how else I can get the definition of a syntax group or highlight group in a Vim script.

If you don't consider this as an issue, feel free to close it.
If you do, I bisected it to the commit 399eb49bafcbd4bf60ff32e339a1f673e75acf2b.

**Comment by lacygoill** [comment]
I didn't tag the issue with the bug label on purpose.
I missed the “Don't see your issue here? Open a regular issue.” at the bottom of the screen, and clicked on “Bug report” without knowing that would tag the issue.
I didn't find a way to remove it.
Sorry.

**Comment by bfredl** [comment]
The code change was for `hi Comment` output. Seems we need to adjust it to also work with `syn list`.

**Comment by bfredl** [comment]
should be fixed on master.
