### ISSUE TITLE
neovim with suckless terminal 

### ISSUE THREAD

**Issue by yfery** [neovim/neovim#10476]
- `nvim --version`:
```
NVIM v0.4.0-527-gc395cf018
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/opt/neovim/build/config -I/opt/neovim/src -I/opt/neovim/.deps/usr/include -I/usr/include -I/opt/neovim/build/src/nvim/auto -I/opt/neovim/build/include
Compiled by fery3@pmz-dn-fery-p

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

- Operating system/version: `Debian 9.9`
- Terminal name/version: `st 0.8.2`
- `$TERM`: `st-256color`
- Window manager: i3

### Actual behaviour

Whenever I start nvim (`nvim -u NORC`) within an instance of st the following warning is emitted to stderr:
```
erresc: unknown csi ESC[22;0;0t
erresc: unknown str ESC]11
```
Quitting nvim prints
```
erresc: unknown csi ESC[23;0;0t
```

After some digging, those error came from code that st don't understand: 

https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c
```
data->unibi_ext.save_title = (int)unibi_add_ext_str(
      ut, "ext.save_title", "\x1b[22;0;0t");
data->unibi_ext.get_bg = (int)unibi_add_ext_str(ut, "ext.get_bg",
     "\x1b]11;?\x07");
data->unibi_ext.restore_title = (int)unibi_add_ext_str(
     ut, "ext.restore_title", "\x1b[23;0;0t");
```

I don't understand what this piece of code is doing. So I don't know if it's a real issue, if I can set parameters into init.vim to counter it, or if it's a st issue.

**Comment by mschilli87** [comment]
Is this a recent thing? I use neovim under st on several systems (CentOS, Ubuntu, Gentoo) for years and never saw this error. :confused:

**Comment by yfery** [comment]
I use st since only one month, and I discover it today by looking into my syslog for another issue.

Perhaps, the problem comes from an i3 limitation

**Comment by KillTheMule** [comment]
I use neovim with st as well, and I'm seeing that also. I just discard st's output though, so I don't really mind :)

**Comment by mschilli87** [comment]
@KillTheMule: Is this under i3 as well? I'm using spectrwm and I don't seem to be able to reproduce this.
I'm still on st 0.4.1 and neovim 0.3.7 though.

**Comment by KillTheMule** [comment]
No, it's an ancient gnome, neovim 0.40 (somewhat older) and a version of st I cannot identify (somewhat recentish).

**Comment by lacygoill** [comment]
`ESC[22;0;0t` is `CSI Ps ; Ps ; Ps t` with the three numeric parameters `22`, `0` and `0`.
`ESC[23;0;0t` is also `CSI Ps ; Ps ; Ps t` with the three numeric parameters `23`, `0` and `0`.

They were introduced in ccbcd390d42d33a15f15c29fab5d6076a6d3ac08.

Both are described [here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Functions-using-CSI-_-ordered-by-the-final-character_s_) like so:

> Ps = 2 2 ; 0  -> Save xterm icon and window title on stack.
> Ps = 2 3 ; 0  -> Restore xterm icon and window title from stack.

They  seem to  be used  to save  and restore  the icon  and window  title of  an
xterm-compatible terminal.

---

`ESC]11` is probably the truncation of `OSC  Ps ; Pt BEL` with the first numeric
parameter `11` and the text parameter `?`.

It was introduced in 298608f88c463705cfd6ee47035c049dbb1d9fa0.

`OSC11;?BEL` is described [here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands) like so:

> If a "?" is given rather than  a name or RGB specification, xterm replies with
> a control sequence of the same form which can be used to set the corresponding
> color.
> Because more than one pair of color number and specification can be given in one
> control sequence, xterm can make more than one reply.

It's probably  used to  get the  color of  the background  of the  terminal, and
determine whether the Nvim `'bg'` option should be set to 'dark' or 'light'.

---

st probably doesn't implement these 3  sequences, and so doesn't understand them
when Nvim sends them.

---

You can find these sequences in Nvim's internal terminfo database:

    $ nvim -V3/tmp/log file
    :q
    $ nvim /tmp/log
    :sil exe '1,/{{{$/g/^/d_' | /}}}$/,$g/^/d_

Inside, look for `ext.save_title` and `ext.restore_title`:

    ext.save_title            = <Esc>[22;0;0t
    ext.restore_title         = <Esc>[23;0;0t

I have no idea whether they can be overridden by the user (I suspect not).

---

You can see these 3 error messages by starting st from another terminal (e.g. xterm):

    # start xterm
    $ st
    $ nvim

They should be printed in xterm.

**Comment by justinmk** [comment]
st doesn't support that stuff (as @lacygoill nicely explained), so it shows a warning. What's the problem?

We could avoid those sequences for `TERM=st*` but then if suckless terminal later decides to suck even _less_ by implementing these features, we would miss those features.

**Comment by iio7** [comment]
Should this have been closed? I have an identical setup between Neovim and Vim (they use the same configuration file) and this isn't a problem in Vim running in st.

**Comment by bfredl** [comment]
@iio7 What "problem"? All that happens is that `st` chooses to show a warning. Other terminals have realized they can ignore these sequences without a warning.

If someone thinks they can "correct" our terminfo or something (without causing trouble elsewhere, like actual missing functionality) they are free to send a PR. But I don't think we need an open issue for every corner case where a third-party app chooses to write to its own stderr.

**Comment by iio7** [comment]
@bfredl I think this exactly is the problem. All the "other" terminals have decided upon a wrong behavior so now we follow that and the applications such as `st` that does it right, have now become wrong. Ignoring sequences without giving a warning is not correct behavior of a terminal emulator.

**Comment by bfredl** [comment]
> Ignoring sequences without giving a warning is not correct behavior of a terminal emulator.

This is a very general and broad statement. There  is no "specification" that says how terminals or TUI apps should behave universally (only ones for specific terminal versions), one has to consider the tradeoffs and do the reasonable thing on a case-by-case basis. Ignoring a title restoration sequence causes no bad side effects, it just behaves as if we didn't use the sequence at all. While sending/ignoring, say, a scrolling region sequence would be a major catastrophe and damage the screen for potentially a long time.

The lack of an open issue for specific aspect X is not a claim that we think we are being "perfect" with regard to X. On the contrary, as terminal support is an empirical science, almost anything could be _potentially_ improved. Anyone who thinks they can improve our rules can just open a PR at any time and we discuss the concrete code change. A separate open issue for every small thing that potentially could be different is not needed.

**Comment by 71GA** [comment]
@bfredi It is actually totaly wrong not to warn users about defect behaviour of **any** kind of a program... So `st` is top notch here and all the others are just leading a bad example...

**Comment by justinmk** [comment]
> @bfredi It is actually totaly wrong not to warn users about defect behaviour of **any** kind of a program... So `st` is top notch here and all the others are just leading a bad example...

By that logic your TCP/IP stack should warn you when a packet is received out of order.

Terminal applications cannot cover all of the edge cases of terminal emulator versions, user environments, etc. They must be allowed to send "best effort" sequences in a harmless way without bugging users.

**Comment by dm1try** [comment]
@71GA @iio7  you have to give `st` maintainers some time, maybe someone of them will start using neovim. see https://git.suckless.org/st/commit/b650256044f867851725f712fdac58d4ff294808.html
https://git.suckless.org/st/commit/75b4ba4b4be70a3ae429b1719d18b021839216d5.html

but seriously, @bfredl is right
> This is a very general and broad statement. There is no "specification" that says how terminals or TUI apps should behave universally ...

**Comment by craigbarnes** [comment]
> It is actually totaly wrong not to warn users about defect behaviour of **any** kind of a program...

Sending an escape sequence that may or may not be supported by the terminal is almost unavoidable in any sufficiently complex TUI program. There's nothing "defective" about doing that.

There's a reason why all the related standards (e.g. ECMA-48) specify the structure and semantics of escape sequences separately -- it's so terminals can parse the sequence correctly (e.g. CSI, OSC, etc.) even if they don't support a specific operation or parameter.

**Comment by bfredl** [comment]
I forgot to write my bottom line here. Spilling words in an issue like this will not convince the neovim maintainers that neovim does anything wrong. However sending a PR with lints passing that unambiguously improves our feature detection will convince me the same second as the appveyor CI is passing.
