### ISSUE TITLE
When using ext_popupmenu, it is not possible to operate the keys according to the manual

### ISSUE THREAD

**Issue by erw7** [neovim/neovim#10471]
- `nvim --version`: NVIM v0.4.0-1256-g564d415d2
- `gvim -u DEFAULTS` (version: ) behaves differently? Yes(8.1.1640)
- Operating system/version: N/A
- Terminal name/version: N/A
- `$TERM`: N/A

### Steps to reproduce using `nvim -u NORC`

```
nvim-qt -- -u NORC
i
/usr/include/<C-x><C-f><PageDown><PageUP>
```

### Actual behaviour
Nothing happens.

### Expected behaviour
&lt;PageUp&gt;	  Select a match several entries back, but don't insert it.
&lt;PageDown&gt;	  Select a match several entries further, but don't insert it.

I confirmed that `popupmenu_select` event for the item currently selected by `<PageUp>` or  `<PageDown>` is always generated. Since `nvim` has no way of knowing the number of items displayed in the popupmenu of the UI, I do not know how to fix this.

**Comment by bfredl** [comment]
We could add an ui notification like `nvim_ui_pum_set_height` so the UI can tell nvim the height of the popupmenu. Alternatively/in addition, we should use a better default heuristic, like 10 instead of zero.
