### ISSUE TITLE
How to combine two trained models in keras?

### ISSUE THREAD

**Issue by 47euewxm** [neovim/neovim#10536]
I have two models , trained using CNN on an image data set, both models are trained to identify different-different objects.Is it possible so that i combine these two trained models in keras, to detect two different objects in the given image,using a single merged model.[购买加拿大麦吉尔大学毕业证，办加拿大回国人员证明，办加拿大文凭，办加拿大使馆认证，办加拿大学历学位认证，国外学历学位认证办理](www.diplomaclub.net)

**Comment by jszakmeister** [comment]
Looks like you have the wrong project or this is spam.
