### ISSUE TITLE
Powershell Core - Display Problems

### ISSUE THREAD

**Issue by YMba9g8j9CJp0wLoQf5y** [neovim/neovim#10538]
=======================
NVIM v0.3.8
=======================
OsName                                     : Microsoft Windows 10 Pro
OsType                                     : WINNT
OsOperatingSystemSKU                       : 48
OsVersion                                  : 10.0.18362
OsBuildNumber                              : 18362
=======================

Powershell Core, 7.0.0-preview.2

Just got scoop to install neovim and started making my init.vim file:

![image](https://user-images.githubusercontent.com/52471106/61481274-ddd49b80-a965-11e9-9951-2e19e36bdbf0.png)

Then I insert mode and press enter 3 times:
![image](https://user-images.githubusercontent.com/52471106/61481362-22f8cd80-a966-11e9-90d9-8060b53f81be.png)

I can fix this by press Ctrl-L to redraw. But that is incredibly annoying when every other edit causes this.

**Comment by bfredl** [comment]
Is this really related to powershell? If you run nvim from `cmd.exe`, won't you get the same behavior?

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by YMba9g8j9CJp0wLoQf5y** [comment]
Ok I just installed the nightly version via scoop:
![image](https://user-images.githubusercontent.com/52471106/61487513-18453500-a974-11e9-94af-77485ab0d3ea.png)

Tried the same repos steps I gave and it works beautifully!
![image](https://user-images.githubusercontent.com/52471106/61487614-55112c00-a974-11e9-8878-c130f9c14d6e.png)

What change in the development version if you don't mind my asking?
