### ISSUE TITLE
Neovim on Windows 10 cannot print Terminal Characters (chcp 949)

### ISSUE THREAD

**Issue by thekpaul** [neovim/neovim#10559]
- `nvim --version`: 0.3.8
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Windows 10
- Terminal name/version: cmd.exe, powershell.exe
- `$TERM`:

With `chcp 949` in Windows 10 (which is Korean Character Support in Command Prompt / PowerShell) Neovim does not print readable characters and prints symbols instead.

### Actual behaviour
`nvim -u NORC` and `:!chcp` prints: 
(image)
![neovim](https://user-images.githubusercontent.com/44695374/61589823-9743a300-abea-11e9-8ad3-f408f163af70.png)

### Expected behaviour
`chcp` in PowerShell prints:
![powershell](https://user-images.githubusercontent.com/44695374/61589822-9743a300-abea-11e9-878f-6e3ee8527560.png)

Is this a solvable issue right now, or a feature not yet implemented?

**Comment by bfredl** [comment]
The encoding nvim uses internally is utf-8. `:!` currently reads bytes over a pipe only, it doesn't do anything about console code pages.

Does the same issue exist with `:terminal chcp` ?

**Comment by bfredl** [comment]
The encoding nvim uses internally is utf-8. `:!` currently reads bytes over a pipe only, it doesn't do anything about console code pages.

Does the same issue exist with `:terminal chcp` ?

**Comment by bfredl** [comment]
If it has the issue, it sounds like conpty (microsoft's own pty implemenation) will support this better than winpty we are using currently, by transparently converting from/to UTF-8 for us.

**Comment by thekpaul** [comment]
`:terminal chcp` doesn't have this issue, so wintpy doesn't seem to be problematic.

**Comment by bfredl** [comment]
ok, so this would be solved by making  `:!` use the pty (which is planned #1496). Using `:terminal` instead is a workaround in the meanwhile.

**Comment by thekpaul** [comment]
Thank you, this was what I was looking for :)
