### ISSUE TITLE
jobstart() requires relative {cmd}[0] to be preceded by "./"

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10554]
With "/" as the cwd, the following returns -1: `jobstart(['usr/bin/ls'])`.

I think a leading "./" should not be required here really (as shells would handle it).

This is due to `os_can_exe` not considering to be executable.

`f_executable` has an additional check (and returns 1):
https://github.com/neovim/neovim/blob/d20bbc802245cc14176028bf209ae3a7e81e21c4/src/nvim/eval.c#L8470-L8471

**Comment by justinmk** [comment]
> I think a leading "./" should not be required here really (as shells would handle it).

The list form of jobstart() explicitly does not have shell semantics.

I have the strong feeling that this was already discussed twice before, in closed tickets.

**Comment by blueyed** [comment]
It is not specific to shells.

This also works:
```c
#include <unistd.h>

char *cmd[] = { "usr/bin/pwd", (char *)0 };

int main() {
  chdir("/");
  return execv("usr/bin/pwd", cmd);
}
```

> What is the use-case, anyway? I've never used this and I am surprised that shells accept it.

I always omit the leading "./" when not executing something from the current directory (but a path below it).

If it would be shell specific, then `executable()` should also return 0, no?

btw: Vim's `job_start` handles it.

**Comment by justinmk** [comment]
> If it would be shell specific, then executable() should also return 0, no?

There's definitely a ticket for this. Maybe tagged "windows" IIRC

**Comment by blueyed** [comment]
(Cannot find it.. there's not much for https://github.com/neovim/neovim/issues?utf8=%E2%9C%93&q=is%3Aissue+job+relative+directory also - but one has 146 comments, which I have not expanded.)

**Comment by blueyed** [comment]
> btw: Vim's `job_start` handles it.

It just starts anything..

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/issues/9569

> " it return -1 and E903, but executable('coffee') return 1
