### ISSUE TITLE
Windows: mingw nvim.exe is 10x bigger than MSVC

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#10560]
Example:

- mingw-gcov `nvim.exe` is 28 MB: https://ci.appveyor.com/project/neovim/neovim/builds/26047698/job/wo0tpuc4tj5e725r/artifacts
- mingw `nvim.exe` is 20 MB: https://ci.appveyor.com/project/neovim/neovim/builds/26047698/job/k4ijnka0j6i6e0gf/artifacts
- MSVC_64 `nvim.exe` artifact is 3 MB: https://ci.appveyor.com/project/neovim/neovim/builds/26047698/job/o37wlk9emmkcynw8/artifacts

Presuming mingw artifact is statically compiled, while the MSVC artifact is dynamically-linked. 

Where  is this decided? Was  it was intentional?

**Comment by justinmk** [comment]
Conclusion from https://github.com/neovim/neovim/issues/18551 is that we will remove msys2 / mingw CI.

**Comment by 3N4N** [comment]
Leaving it here as _possible_ answer to why mingw nvim binary is larger.

It was using MINGW64 environment, which uses msvcrt library.  This library is no longer available in Windows anymore<sup>☩</sup>, so the library is statically linked to nvim.exe<sup>☩</sup>, increasing the binary size.  If we used UCRT64 environment, it would've used ucrt library, which is present in Windows Kits, so there wouldn't've been any need to statically link that, reducing the binary size.

☩: Conjecture.  No documentation behind this claim.
