### ISSUE TITLE
wiki: Fedora install instructions need to be updated

### ISSUE THREAD

**Issue by ford-prefect** [neovim/neovim#10569]
The `python2-neovim` package seems to no longer exist (as of Fedora 30 at least), so that should probably be removed from the Fedora installation instructions.

**Comment by justinmk** [comment]
It's a wiki. Feel free.

**Comment by ford-prefect** [comment]
Uff, that's embarrassing. I assumed the wiki was for project maintainers only for some silly reason. I've fixed that section now.
