### ISSUE TITLE
TUI/xterm: scrolling in one window scrolls the other

### ISSUE THREAD

**Issue by moolow** [neovim/neovim#10562]
- `nvim --version`: 0.3.8-1.2-x86_64
- `vim -u DEFAULTS` (version: 8.1.1694-1.1-x86_64) behaves differently? Yes
- Operating system/version: openSUSE Tumbleweed, 20190718-204.1-x86_64.
- Terminal name/version: XTerm/345-1.2-x86_64
- `$TERM`: xterm-256color
### Steps to reproduce using `nvim -u NORC`
1. write any data 100~150 lines.
2. create other windows.
```
:vs
:sp
```
3. any window move up/down from first line to last line.
4. nvim has scrolled another windows too.

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```
but using ansi-256color, i can't see the problem.

### Actual behaviour
scroll another window too.

### Expected behaviour
scroll separately.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS.

**Comment by moolow** [comment]
today I have tried the development version. the development version has the same problem too.

**Comment by justinmk** [comment]
I've never seen this problem. It happens only on XTerm? Did you try other terminals?

**Comment by bfredl** [comment]
@moolow I cannot reproduce this (recent master) neither with `TERM=xterm` (which my xterm calls itself, regardless of color support) or if I manually specify `TERM=xterm-256color`. It could be an issue with your terminfo. It could be worth trying running nvim with `TERM=xterm nvim` and see if it makes a difference for you.

**Comment by jamessan** [comment]
What does `:verbose set scrollbind? cursorbind?` show?

**Comment by justinmk** [comment]
@moolow Did you actually try `nvim -u NORC` ?

**Comment by evolarium** [comment]
I see this behaviour on several terminals with `nvim -u NONE`
- xfce4-terminal (0.8.8)
- qterminal (0.14.1)
- roxterm (3.7.5)

I don't see this behaviour when running under alacritty(0.3.3) or xterm(348).

**Comment by justinmk** [comment]
Does qterminal use libvte ?

**Comment by evolarium** [comment]
qterminal uses qtermwidget, which was derived from KDE's Konsole.

**Comment by moolow** [comment]
> What does `:verbose set scrollbind? cursorbind?` show?

**Comment by evolarium** [comment]
I did a git bisect, and this behaviour started with 2f018b1833247aea885ad01d6ac7a6649254b9ac, when libunibilum was updated to 2.0.0.  Bisecting libunibilium commits from the upgrade leads me to https://github.com/mauke/unibilium/commit/42f3cdd284735bd827691c3d0bfae9472b22d5d5 as the commit where the scrolling stops working properly.

**Comment by blueyed** [comment]
@evolarium 
What `$TERM` do you have?  Is it the default from the terminals you have tried?  Does it still happen when using `TERM=xterm`?

**Comment by evolarium** [comment]
xfce4-terminal, qterminal, and roxterm have TERM set to xterm-256color, which I think is the default.  In any case, setting TERM to xterm has no effect.

Alacritty now has its own terminfo information, and TERM there now defaults to alacritty, which works.  However, if I change TERM to xterm-256color or xterm, I get the same scrolling behaviour as the other terminals.

My xterm has TERM set to xterm by default, and works properly.  It also still works if I set TERM to xterm-256color.

**Comment by blueyed** [comment]
@evolarium 
I cannot reproduce it using alacritty 0.3.3, with `TERM=xterm nvim -u NONE src/nvim/edit.c` (in Neovim's source) and `:vs`, `:sp`, and then scrolling (like in the initial comment).
Can you provide a https://asciinema.org/ screencast?
What is your OS?

**Comment by blueyed** [comment]
There are two places where alacritty is handled in the source - so I suggest poking at the code to see where this is coming from/via, e.g. by commenting https://github.com/blueyed/neovim/blob/1f515642ec9e92a0ccfec93f279b6affae92326b/src/nvim/tui/tui.c#L1872-L1873 and/or https://github.com/blueyed/neovim/blob/1f515642ec9e92a0ccfec93f279b6affae92326b/src/nvim/tui/tui.c#L1877-L1878 etc.

**Comment by blueyed** [comment]
Also try disabling handling of cursor style control codes via:
```diff
diff --git i/src/nvim/tui/tui.c w/src/nvim/tui/tui.c
index 58ef54070..1bbe8a194 100644
--- i/src/nvim/tui/tui.c
+++ w/src/nvim/tui/tui.c
@@ -144,7 +144,7 @@ UI *tui_start(void)
   ui->grid_resize = tui_grid_resize;
   ui->grid_clear = tui_grid_clear;
   ui->grid_cursor_goto = tui_grid_cursor_goto;
-  ui->mode_info_set = tui_mode_info_set;
+  // ui->mode_info_set = tui_mode_info_set;
   ui->update_menu = tui_update_menu;
   ui->busy_start = tui_busy_start;
   ui->busy_stop = tui_busy_stop;
```

And also provide the output of `infocmp xterm`.

**Comment by evolarium** [comment]
Here is an screencast from alacritty: https://asciinema.org/a/LYtQu2zhjXIentE0kpaU2FcD6

Commenting out the three things you pointed out has no effect.  I am using Gentoo Linux.  I have attached the infocmp output.

[infocmp_xterm.txt](https://github.com/neovim/neovim/files/3461519/infocmp_xterm.txt)

**Comment by blueyed** [comment]
Looks like it is not only scrolling the other window, but also not redrawing it properly?
What do you use for scrolling?  Does it also happen when scrolling at the end using `j`?

@moolow 
Is that also what you are seeing?

**Comment by blueyed** [comment]
@evolarium 
The difference between my (left) and your (right) terminfo:
```
1c1
< #	Reconstructed via infocmp from file: /usr/share/terminfo/x/xterm
---
> #	Reconstructed via infocmp from file: /etc/terminfo/x/xterm
65,66c65,70
<         kb2=\EOE,
<         kbs=^H,
---
> 	ka1=\EOw,
> 	ka3=\EOy,
> 	kb2=\EOu,
> 	kbs=^H,
> 	kc1=\EOq,
> 	kc3=\EOs,
149a154
> 	mgc=\E[?69l,
177a183
> 	smglr=\E[?69h\E[%i%p1%d;%p2%ds,
```

The problem here is the "smglr=\E[?69h\E[%i%p1%d;%p2%ds," apparently.
It causes `can_set_lr_margin` to be 1 with `TERM=xterm` then (using your terminfo), but it is 0 otherwise.  alacritty on Arch Linux uses `TERM=xterm-256color` for me.

**Comment by blueyed** [comment]
Related issue: https://github.com/neovim/neovim/issues/8151

**Comment by blueyed** [comment]
alacritty.info has no smglr entry: https://github.com/jwilm/alacritty/blob/master/extra/alacritty.info
So using that one fixes it for you, but otherwise it is advertised wrongly.
Where is your `/etc/terminfo/x/xterm` coming from?
I am not sure if xterm itself would support it, but all the other terms you are seeing this with (and that use that `$TERM`) probably do not support it.

**Comment by evolarium** [comment]
Looks like xterm added it recently.  From Patch 345 at: https://invisible-island.net/xterm/xterm.log.html

> add left/right margin capabilities to terminfo, since the default terminal emulation is VT420 (suggested by Thomas Wolff).

**Comment by blueyed** [comment]
I can see no difference between unibilium v1.2.1 and v2.0.0 there, using `TERM=xterm LD_PRELOAD=/home/user/Vcs/unibilium/.libs/libunibilium.so nvim …`.

**Comment by blueyed** [comment]
> Looks like xterm added it recently. From Patch 345 at: https://invisible-island.net/xterm/xterm.log.html

I see.
I do not know how to handle this then.. FWIW, my xterm terminfo is coming via "ncurses 6.1-6".
I assume that will cause problems all around for terminals that do not support it, but use TERM=xterm then.

**Comment by blueyed** [comment]
It does not really explain @moolow's intial issue though, where xterm 345 is used.

**Comment by blueyed** [comment]
So one solution to this problem might be to discard this for non-true xterm, if it looks like the default for TERM=xterm in/with https://github.com/neovim/neovim/blob/1f515642ec9e92a0ccfec93f279b6affae92326b/src/nvim/tui/tui.c#L1584-L1589 - assuming that distros will start to ship this.
/cc @jdebp (via 3d8e0594e)

**Comment by blueyed** [comment]
ncurses appears to ship it as "xterm-new" btw (it was updated for the patch in https://github.com/mirror/ncurses/commit/8f6d94b8d6211a2323caef53fa4c96c475ec9a62#diff-842764d6827ee1f7e8605999bb22e2d6R2741)

**Comment by blueyed** [comment]
@evolarium 
> I did a git bisect, and this behaviour started with [2f018b1](https://github.com/neovim/neovim/commit/2f018b1833247aea885ad01d6ac7a6649254b9ac), when libunibilum was updated to 2.0.0. Bisecting libunibilium commits from the upgrade leads me to [mauke/unibilium@42f3cdd](https://github.com/mauke/unibilium/commit/42f3cdd284735bd827691c3d0bfae9472b22d5d5) as the commit where the scrolling stops working properly.

I'd still like to make sure I am not missing something here - that commit in particular might have changed / broken the parsing of more complex terminfo entries like this one.  How did you do the bisecting (what have you tested (TERM/terminal), and how did you load unibilium then)?

**Comment by evolarium** [comment]
I did a git bisect on the neovim repository.  For each commit, I would do a git clean -fxd, then build and test the scrolling.  Once I found the commit in the neovim repo, I just changed UNIBILIUM_URL and UNIBILIUM_URL in third-party/CMakeLists.txt to test the different unibilium commits.

I was using roxterm for the test.  Testing it again now, alacritty, xfce4-terminal, and qterminal also show a difference in behaviour at that commit.

And looking into it further, my xterm terminfo entries are from ncurses 20190609.  xterm-new gets installed as xterm, so it is the default.

**Comment by blueyed** [comment]
Strange.  It still happens there then for me, using this in `local.mk`:
```
DEPS_CMAKE_FLAGS += -DUSE_BUNDLED_LIBTERMKEY=ON
DEPS_CMAKE_FLAGS += -DUSE_BUNDLED_UNIBILIUM=ON
DEPS_CMAKE_FLAGS += -DUSE_BUNDLED=OFF
```
and the commit before it (which appears to be "good") for you:

```diff
diff --git i/third-party/CMakeLists.txt w/third-party/CMakeLists.txt
index 6824e208a..5bb4de344 100644
--- i/third-party/CMakeLists.txt
+++ w/third-party/CMakeLists.txt
@@ -146,8 +146,8 @@ set(LUA_SHA256 2640fc56a795f29d28ef15e13c34a47e223960b0240e8cb0a82d9b073>
 set(LUAROCKS_URL https://github.com/luarocks/luarocks/archive/v2.4.4.tar.gz)
 set(LUAROCKS_SHA256 9eb3d0738fd02ad8bf39bcedccac4e83e9b5fff2bcca247c3584b925b2075d9c)
 
-set(UNIBILIUM_URL https://github.com/mauke/unibilium/archive/v2.0.0.tar.gz)
-set(UNIBILIUM_SHA256 78997d38d4c8177c60d3d0c1aa8c53fd0806eb21825b7b335b1768d7116bc1c1)
+set(UNIBILIUM_URL https://github.com/mauke/unibilium/archive/73385ba.tar.gz)
+set(UNIBILIUM_SHA256 SKIP)
 
 set(LIBTERMKEY_URL http://www.leonerd.org.uk/code/libtermkey/libtermkey-0.21.1.tar.gz)
 set(LIBTERMKEY_SHA256 cecbf737f35d18f433c8d7864f63c0f878af41f8bd0255a3ebb16010dc044d5f)
```
To test I've used `alacritty -e bash`, and then `TERM=xterm build/bin/nvim -u NONE src/nvim/edit.c` (after `tic infocmp_xterm.txt` to have your terminfo in `~/.terminfo`).

**Comment by blueyed** [comment]
@evolarium 
Have you used Neovim at the bad commit (2f018b183) then when having bisected Unibilium then?

I've just tried that now, but I am still seeing the bad behavior with neovim/unibilium@73385b then, and using `TERM=xterm` with your provided terminfo, in roxterm.

I still think the main issue is using a `$TERM` that advertises properties that are not given, and that appears due to you / your distro shipping the newer xterm terminfo as "xterm", which is also used by other terminals, and therefore should rather be only used / shipped as "xterm-new" (AFAICS).
This applies to "xterm-256color" also, but I've only tried it based on your provided "xterm" one.

(Just for reference: using Neovim master, with unibilium 73385b I am getting a segfault with a newer terminfo (xterm-256color from ncurses), which unibilium fails to load (from the system, and from Neovim's hardcoded defaults (which do not work with unibilium < 2.0)
https://github.com/neovim/neovim/pull/10681 is about preventing this).

**Comment by evolarium** [comment]
@blueyed 

Yes, I was using Neovim at commit 2f018b1 when testing Unibilium.
Before: https://asciinema.org/a/2xf0qLD4AlzJzrTlyitLm8pyJ
After: https://asciinema.org/a/zWZj5epjSMTLt82rV1WQdvnmw

That was with TERM set to xterm-256color.  Looking into it further, the xterm-256color terminfo requires the 32-bit support and just wasn't loading prior to that change.

This isn't a problem with my distro specifically.  xterm-new is the default xterm entry in ncurses, since 2004. So this will be the default as distros update ncurses.
  
https://invisible-island.net/ncurses/NEWS.html#index-t20040703

**Comment by blueyed** [comment]
> This isn't a problem with my distro specifically. xterm-new is the default xterm entry in ncurses, since 2004. So this will be the default as distros update ncurses.

Oh - I was misunderstanding that.
Apparently Arch does not have it then yet.  Sorry for the confusion.

Still, I am not sure if this shouldn't be considered a bug in ncurses then - or terminals not shipping/having a proper terminfo entry (anymore).

**Comment by evolarium** [comment]
I agree, the problem is that terminals shouldn't be depending on xterm for terminfo.  I've switched to using vte-256color, which should probably be the default for roxterm anyways.  I wish terminfo could be propagated over ssh, instead of needing to copy current terminfo files everywhere I want them.

**Comment by blueyed** [comment]
Please try https://github.com/neovim/neovim/pull/11132 if you can.
