### ISSUE TITLE
neovim doesn't exist insert mode if moves cursor immediately after pressing esc

### ISSUE THREAD

**Issue by cyb70289** [neovim/neovim#10575]
- `nvim --version`: NVIM v0.3.7
- `vim -u DEFAULTS` (version: ) behaves differently? vim works correctly.
- Operating system/version: Ubuntu 18.04
- Terminal name/version: xterm
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

```
- start neovim
- enter insert mode, input some characters
- move cursor (any direction) immediately after pressing esc, neovim will keep in insert mode

This issue may be hard to trigger at first, as the time gap between pressing esc and move cursor must be very short. After some trying you can easily reproduce it.
I first noticed this issue on a slow machine. vim8 works okay.
```

### Actual behaviour
neovim still in insert mode

### Expected behaviour
neovim exists insert mode

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed

If you aren't using tmux/screen, try setting 'ttimeoutlen' to very small number:

    :let ttimeoutlen=10

**Comment by blueyed** [comment]
Reminded me of https://github.com/neovim/neovim/pull/3758 also - i.e. @cyb70289 please try nvim master and see if it behaves better (by default).
