### ISSUE TITLE
Error detected while processing function netrw#Explore[220]

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#10572]
- `nvim --version`: NVIM v0.4.0-dev
<details>
<summary>Output of nvim --version </summary>

```
NVIM v0.4.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-HiXy_F/neovim-0.4.0+ubuntu4+git201907212017-9d0f822-6e51973/build/config -I/build/neovim-HiXy_F/neovim-0.4.0+ubuntu4+git201907212017-9d0f822-6e51973/src -I/build/neovim-HiXy_F/neovim-0.4.0+ubuntu4+git201907212017-9d0f822-6e51973/.deps/usr/include -I/usr/include -I/build/neovim-HiXy_F/neovim-0.4.0+ubuntu4+git201907212017-9d0f822-6e51973/build/src/nvim/auto -I/build/neovim-HiXy_F/neovim-0.4.0+ubuntu4+git201907212017-9d0f822-6e51973/build/include
Compiled by buildd@lgw01-amd64-025
Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

</details>

- `vim -u DEFAULTS` (version: ) behaves differently? Works with vanilla vim, not with minimal init.vim on nvim. 
- Operating system/version: Ubuntu 16.04
- Terminal name/version: Remote SSH section
- `$TERM`: xterm-256color
 
### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:Explore 
```

### Actual behaviour

```
Error detected while processing function netrw#Explore[220]..netrw#LocalBrowseCheck:
line   23:
E171: Missing :endif
Error detected while processing function netrw#Explore:
line  220:
E171: Missing :endif
```

### Expected behaviour

Netrw doesn't yield error messages

**Comment by mjlbach** [comment]
Edit: This was because my display environmental variable was set on a headless server... closing.

**Comment by justinmk** [comment]
Need exact commit

**Comment by mjlbach** [comment]
I've been using the development (0.4) releases, but I just built from source and saw the same things happens in latest 36622014c640ad5df19269e63ad037c104efce9c. It appears to be isolated to only nvim instances within a tmux session.

**Comment by Escapingbug** [comment]
same issue here, on windows, using alacritty (not within tmux)

**Comment by justinmk** [comment]
@mjlbach thanks for bisecting. Maybe 3662201  requires a newer version of netrw. After https://github.com/neovim/neovim/pull/10675 , netrw will be updated. Please try it.

**Comment by mjlbach** [comment]
@justinmk I just built and tested #10675 and the issue was resolved! Thank you!
