### ISSUE TITLE
E484: Can't open file with non-latin chars 

### ISSUE THREAD

**Issue by artkpv** [neovim/neovim#10586]
Hello! Thanks for the great neovim

- `nvim --version`:

> NVIM v0.3.8
> Build type: RelWithDebInfo
> LuaJIT 2.0.5
> Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
> Compiled by appveyor@APPVYR-WIN
> 
> Features: -acl +iconv -jemalloc +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM\sysinit.vim"
>   fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
> 
> Run :checkhealth for more info

- `vim -u DEFAULTS` (version: ) behaves differently?

The same

- Operating system/version:
Windows 8.1 6.3.9600 N/A Build 9600

- Terminal name/version:
The same on: cmder.exe, cmd.exe, powershell.exe

### Steps to reproduce using `nvim -u NORC`
```
1. Open cmd.exe
2. Run `nvim -u DEFAULTS` (which is empty)
3. Type: `:call readfile('C:\Users\wild\Desktop\testwiki\тест.md')`  
```
(Step 3 updated: it was 'readline')

### Actual behaviour
Message: "E484: Can't open file C:/Users/wild/Desktop/testwiki/тест.md"

### Expected behaviour
No such message. It works if run for test.md

**Comment by justinmk** [comment]
> ```
> 1. Open cmd.exe
> 2. Run `nvim -u DEFAULTS` (which is empty)
> 3. Type: `:call readline('C:\Users\wild\Desktop\testwiki\тест.md')`
> ```

`nvim -u DEFAULTS` is not valid. Use `nvim -u NORC`, as shown in the issue template.

`readline()` is not a valid function. Show exactly what you did, not an estimate from memory.

**Comment by bfredl** [comment]
It seems `f_readfile` just calls `fopen` (via `mch_fopen`) directly, which I think does not support unicode paths on windows, unlike `os_open` which invokes a libuv wrapper which does. Perhaps we want to change `mch_fopen` to a function which first calls `os_open` and then `fdopen` to get a `FILE *` handle.

**Comment by justinmk** [comment]
Works for me on Windows 10 with Nvim 0.4.x 184b87ee3.

    :echo readfile('тест.md')

However, migrating to libuv-wrapped layer is worth doing anyway.

**Comment by artkpv** [comment]
Thanks for answers. Tried with `nvim -u NORC`. The same. I'm trying with 0.4.x

**Comment by bfredl** [comment]
It might depend on what C runtime is used I guess (MSVCRT or mingw), and what version. Historically windows has required explicit conversion to UTF-16, but recently MS seems to care more about UTF-8 support.

**Comment by artkpv** [comment]
The same on 0.4.0-1377. :disappointed: Downloaded from https://github.com/neovim/neovim/releases/. Extracted and run: 

> ~\Desktop\Neovim\bin $
> .\nvim.exe --version
> NVIM v0.4.0-1377-g184b87ee3
> Build type: RelWithDebInfo

and `:call readfile(".../тест.md")` doesn't work. (BTW `:r ../тест.md` inserts the text into buffer).

**Comment by artkpv** [comment]
The issue actually is with Vimwiki when I generate tags there. You can check at https://github.com/vimwiki/vimwiki/issues/732.

**Comment by justinmk** [comment]
> It seems `f_readfile` just calls `fopen` ... Perhaps we want to change `mch_fopen` to calls `os_open` and then `fdopen` 

see #10589 

@artkpv can you try the .zip here: https://ci.appveyor.com/project/neovim/neovim/builds/26191325/job/0h99ktjgc1om1lnx/artifacts

**Comment by artkpv** [comment]
@justinmk Tried with it in .zip. `readfile` works. No error message. :smile:
