### ISSUE TITLE
latin1 encoded file is not well opened

### ISSUE THREAD

**Issue by Big-bros** [neovim/neovim#10587]
I was giving a try to neovim to replace my old vim but i can see the "encoding" option is not available.
I have text files coming from differents sources and neovim can't open them properly when they are not utf8 as many characters are replaces with <92> or other codes.

This is very disappointing as i have no way to open these files properly with neovim.
So i have no choice but go back to the old vim.

**Comment by bfredl** [comment]
'encoding' is for the internal encoding only. 'fileencoding' and 'fileencodings' control the encoding of files. `encoding=utf-8` is the only mode where vim can edit files in different encodings at the same time in full generality.

Is the issue rather that nvim failed to detect the encoding of the file? you can set it manually with `:e ++enc=latin-1` etc if detection fails.

**Comment by justinmk** [comment]
>  the "encoding" option is not available.

As @bfredl mentioned, 'encoding' is internal and has nothing to do with per-file encoding. `:help 'encoding'` mentions:

        See 'fileencoding' to control file-content encoding.

> I have text files coming from differents sources and neovim can't open them properly

Encoding detection is done the same as in Vim, and converted by `iconv`, same as Vim. 

Without platform details so I can't give more specific advice.

**Comment by Big-bros** [comment]
OK, thanks. The ++enc way does the trick. I didn't know it.
Vim had sometimes the same problem but by playing with encoding, fileencoding and copy paste, i could always manage these funky situations where nobody knows the used encoding.

**Comment by Big-bros** [comment]
btw, it was Windows-1252 encoding and was detected as latin1
