### ISSUE TITLE
ENV VARIABLE as provider for config path

### ISSUE THREAD

**Issue by djleonskennedy** [neovim/neovim#10602]
Hello Neovim team!

Would be nice to have feature that allow provide custom config path via environment variable
e.g.
`NEOVIM_CONFIG = 'D://somefolder/nvim'`

**motivation** a lot of people using repos to store their configs, dotfiles etc. 
env's are very easy to set on all platforms 
and i'd be very nice to have ability to set path by this way

Thank you

**Comment by KillTheMule** [comment]
There's already a lot of infrastructure available for that (so much it's actually confusing, but will offer something for many usecases). See `:h initialization` for an overview.

**Comment by djleonskennedy** [comment]
@KillTheMule thank you!
