### ISSUE TITLE
v:register sometimes contains the content of '*' even when clipboard is not set

### ISSUE THREAD

**Issue by jeroen-dhollander** [neovim/neovim#10608]
**Issue:**

I have a function where I try to read the register content if the command was preceded by `"x`.

To check if it was preceded by `"x` I use `v:register` and I check if it is not `"` (because it is always set to `"` when no register is used):

```
function! OpenList(mode, list) range
    if a:mode == "visual"
        " Use the selected text
        call OpenListWithText(s:get_visual_selection(), "--normal ".a:list)
    elseif v:register != "\""
        " Use the specified register
        call OpenListWithText(getreg(v:register), "--normal ".a:list)
    else
        " If we come here the user simply called this without specifying a
        " range nor register (or the '"' register).
        call OpenListWithText("", a:list)
    endif
endfunction
``` 
This function is then for example used in mappings like this:

```
nnoremap <leader>h :call OpenList("normal", "--no-sort mru")<cr>
```

This works most of the time but sometimes it uses the content from the `*` register *even when I specify no register*.
I have been trying to find a pattern of when this happens but so far I have not been able to spot one :/

I am aware that `clipboard` can change the behavior of `v:register`. I do not have `clipboard` set.

I also updated the function to dump the value of `clipboard`, `v:register` and `getreg()`.
When the bug occurs `clipboard` is still empty, but `v:register` contains `*` and `getreg()` returns the content of the `*` register.

**nvim version:**

I was running a nightly build of the 0.4 branch that is a few months old. I have reproduced this on the latest nightly build of the 0.4 branch as well, so the issue still exist.

```
nvim4.2 --version
NVIM v0.4.0-1395-g3566267e7
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-6131bd74-e60b-45e5-a6d1-b0d63fb90c79

Features: +acl+iconv +tui   See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```

**Steps to reproduce**

As mentioned I have no reliable steps to reproduce yet.
I will keep trying to see if I can find a pattern, but in the mean time I'm hoping somebody here might point me to something I can do to provide more information (for example by doing something to enable logs).

If you need any more information, please let me know.

With regards,

Jeroen

edit: actual add `nvim --version` output

**Comment by justinmk** [comment]
Can't your script just check `v:register != '*` ? 

> When the bug occurs `clipboard` is still empty, but `v:register` contains `*` and `getreg()` returns the content of the `*` register.

Could be a plugin, e.g. netrw accesses `"+` (maybe also `"+*`) explicitly.

Without steps to reproduce this is not actionable.

**Comment by jeroen-dhollander** [comment]
> Can't your script just check v:register != '* ?
Yes but then I'd be working around the bug which I would only like to do as a last resort

> Could be a plugin, e.g. netrw accesses "+ (maybe also "*) explicitly.
So are you saying another plugin could be overwriting `v:register` and putting `*` in there?

> Without steps to reproduce this is not actionable.
I completely agree, I was mostly hoping that 1) this was known or 2) you could point me to some steps to investigate this.

**Comment by justinmk** [comment]
Next step would be to bisect which plugins are required to reproduce it.

**Comment by jeroen-dhollander** [comment]
I found a way to reproduce it consistently and I managed to bisect the problem.

The issue is caused by this line in my `init.vim` file:

```
" When selecting things with the mouse, copy it to the primary copy buffer
" (i.e. you can now paste it using middlemouse click)
:noremap <LeftRelease> <LeftRelease>"*ygv
```
When this is triggered the next invocation of `v:register` will return `*` instead of `"`.
Whether this is a bug or not would be up to you to decided.

So full steps to reproduce:

1. Open `nvim` using this `init.vim` file:
```
set mouse=a
:noremap <LeftRelease> <LeftRelease>"*ygv
```
   2) Open a second split `:vsplit`
   3) Now use a mouse click to go to the other split. Type `:echom v:register` and it will show `*`.
   4) Type `:echom v:register` again and it will show `"`
   5) Repeat steps 3 & 4 in the other split to reproduce again.

**Comment by jeroen-dhollander** [comment]
After playing around with it some more I found easier steps to reproduce:
 
1. Do `"ayy`
2. Do `:echom v:register` and it will contain `a`
3. Do `:echom v:register` again and it will contain `"`

I also checked VIM 8.0 and it behaves exactly the same, making me assume this is the expected behavior and not a bug.

**Comment by chrisbra** [comment]
yes, that happens intetionally. See https://github.com/vim/vim/blob/master/src/normal.c#L1115-L1123
