### ISSUE TITLE
complete functions receiving wrong type for a:findstart

### ISSUE THREAD

**Issue by SevereOverfl0w** [neovim/neovim#10604]
- `nvim --version`: 0.3.8
- `vim -u DEFAULTS` (version: 8.1.1729) behaves differently? Yes
- Operating system/version: Linux
- Terminal name/version: Kitty 0.14.2
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

function! Debug(...)
  echom string(a:000)
endf

set omnifunc=Debug

ifoo<C-X><C-O>
```

### Actual behaviour

Messages are

```
['1', '']
[0, 'foo']
```

### Expected behaviour

```
[1, '']
[0, 'foo']
```

### Notes

@tpope discovered this. In fireplace `is#` is used to compare a:findstart, and this is broken under neovim.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS.

**Comment by SevereOverfl0w** [comment]
Same behavior for the nightly appimage

**Comment by justinmk** [comment]
That means vim-fireplace requires at least Vim 8.1.0053

**Comment by SevereOverfl0w** [comment]
I think that's true, yes.

**Comment by tpope** [comment]
It passes an integer on my old v0.3.4 build, that's what led me to the conclusion it was a regression.

**Comment by cangscop** [comment]
#10615
