### ISSUE TITLE
Using mapped keys is laggy against using the command directly

### ISSUE THREAD

**Issue by romariolopezc** [neovim/neovim#10618]
- `nvim --version`:
```
NVIM v0.4.0-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190722-60140-ovif2/build/config -I/tmp/neovim-20190722-60140-ovif2/src -I/usr/local/include -I/tmp/neovim-20190722-60140-ovif2/deps-build/include -I/usr/local/opt/gettext/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190722-60140-ovif2/build/src/nvim/auto -I/tmp/neovim-20190722-60140-ovif2/build/include
Compiled by rlopez@Romarios-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-184b87e/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Mac OSX 10.14.5
- Terminal name/version: iTerm2 3.2.9
- `$TERM`: xterm-256color

### Steps to reproduce
Add this to `init.vim`
```
 nmap <leader>t :NERDTreeToggle <CR>
 map <leader>l :bnext<cr>
 map <leader>h :bprevious<cr>
```

### Actual behaviour
Using `<leader>h` it takes time to get to the previous buffer but if I use `:bprevious` it changes instantly. The same happens for me for `NERDTreeToggle`.

### Expected behaviour
To behave the same as inputting the command directly

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by blueyed** [comment]
@romariolopezc 
Make sure there are no other mapping with the same prefix.  Check also `:h :map-nowait`.
But otherwise please ask in other forums (there is also IRC).
