### ISSUE TITLE
Getting nil response on MSGPACK API after connecting multiple times

### ISSUE THREAD

**Issue by myitcv** [neovim/neovim#1063]
Using the [neovim Go package](https://github.com/myitcv/neovim), I have [a very simple test](https://github.com/myitcv/neovim/blob/master/neovim_test.go) that exercises a couple of the API methods: 

```bash
$ NEOVIM_LISTEN_ADDRESS=/tmp/neovim go test
OK: 7 passed
PASS
ok      github.com/myitcv/neovim        0.029s
```

I launch Neovim manually for now - hence a test run assumes there is an instance available at `NEOVIM_LISTEN_ADDRESS=/tmp/neovim`

The test is very basic for now:

* Calls to `vim_get_buffers`, `vim_get_current_buffer`, `buffer_get_length`, `buffer_set_line`
* 100 concurrent calls to `vim_get_buffers`
* A test of notifications, from subscription to running the command to `send_event` and the handling of the notification

If however I run this same test a number of times in succession, the test starts to fail:

```bash
while true
do 
NEOVIM_LISTEN_ADDRESS=/tmp/neovim go test
sleep 1
done
```

Around the ~110th iteration I start to see (variously):

* "Connection reset by peer"
* A `nil` message being returned
* Broken pipe (when trying to make my first call)

After the first failure in this loop, things never recover.

And yet the Neovim process remains totally responsive throughout. 

Given that each iteration starts a new `go test` process I'm minded to think my code is probably not at fault. I don't rule out the possibility that my Go client is closing/cleaning up properly because:

* I don't `unsubscribe` from my topic of interest
* My client code is probably not closing the pipe cleanly

That said, I'm guessing Neovim should handle bad clients more cleanly.

Any thoughts on how I can help debug this further from the Neovim side?
Dump the process in some way?

**Comment by myitcv** [comment]
@tarruda I'm happy to close this now on the basis I haven't seen anything similar for some time.. thoughts?

**Comment by tarruda** [comment]
@myitcv The msgpack/event layer has suffered so many changes that I think it's safe to close this now

**Comment by justinmk** [comment]
That's great to hear. @tarruda and @oni-link have done significant stability improvements.
