### ISSUE TITLE
Script local options

### ISSUE THREAD

**Issue by kevincox** [neovim/neovim#1065]
_Forgive me if this has been discussed before but I could find anything, however I also had the feeling that I didn't know what to search for._

Currently there are a number of vim options that cause problems for plugins because they change the behavior of builtin commands.  Examples of this are `'ignorecase'` and `'gdefault'`.  It might be a good idea to have these options local to the script that defines them (while making .vimrc set them for the editor) so that plugins don't have to worry about weird settings much the same way as plugins use `noremap` to prevent user mappings screwing them up.

**Comment by justinmk** [comment]
## Resolution/Summary

[vim_dev is discussing](https://groups.google.com/d/msg/vim_dev/pHBc2KmQd4s/tduzAukdAwAJ) and will likely implement a mechanism to "save and restore" options, similar to python "context managers".  That's probably good enough, though not as robust as the approaches described above.

Enchancing/forking VimL is not generally in our interest, and we avoid it where possible. We will merge whatever rainbow Vim eventually barfs out.

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a new issue if you have new information/topics to discuss._
