### ISSUE TITLE
running :!git commit -av inside neovim

### ISSUE THREAD

**Issue by sevenfourk** [neovim/neovim#10658]
I've used to run these kind of commands for pretty long time in vim. Is there something specific wrong with that, so that it's full support has been removed or it's specifics got removed because of old vim code base or something else.

I understand I could easily start a :terminal, but what's wrong with running full vim window/frame/tab in the same render entity. 

Thanks.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes
