### ISSUE TITLE
Windows: python shell has no interaction after quiting neovim

### ISSUE THREAD

**Issue by Escapingbug** [neovim/neovim#10668]
- `nvim --version`: NVIM v0.4.0-1487-g65578693b
- `vim -u DEFAULTS` (version: 8.1) behaves differently? yes
- Operating system/version: Windows 10 1903
- Terminal name/version: Alacritty 0.3.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. `nvim -u NORC`
2. exit neovim
3. open python shell
4. no input will be sent to python shell now after

Powershell works fine, once exited python, powershell continues to work.

### Actual behaviour
python shell has no input

### Expected behaviour
 python shell should work fine after quiting neovim

**Comment by bfredl** [comment]
Python shell how? You mean inside the `:terminal`? Please provide complete instructions.

**Comment by Escapingbug** [comment]
My fault on missing the "quiting" part. I have tested this on both `Alacritty` and `WindowsTerminal (preview)`, my guess is that this might related to neovim.

**Comment by justinmk** [comment]
Update your nvim version. You are missing hundreds of patches.

**Comment by Escapingbug** [comment]
Hahahaha, I've checked it about 5 times, and making sure my binary is from the nightly. Also, the nightly release seems to have incorrect version string if it should be `NVIM v0.4.0-1504-g87140f234`,

**Comment by justinmk** [comment]
It's my mistake. My local build gave me the wrong impression.

**Comment by Escapingbug** [comment]
I've done a little further tests on this. I've tried this on `FluentTerminal`, `WindowsTerminal(preview)` and `alacritty` with both `cmd.exe` and `powershell.exe`. It seems all powershell has failed in this situation.

Does this mean that powershell may be responsible for this situation?

**Comment by Escapingbug** [comment]
Ok, I have successfully located the bug. It's something about `libuv`'s tty handling. It hasn't reset the mode (as in `libuv`, `uv_tty_reset_mode` just returns 0). I will fire an issue to `libuv` and see how they responde to this problem.

Currently, the workaround is to set the mode back when it is under `win32`. I will make a pull request containing my workaround once my testcases have passed.

**Comment by Escapingbug** [comment]
Ok, I have identified the bug. It is because under windows(conpty, I suppose), the terminal mode is not reset actually when `neovim` is trying to exit, although `uv_tty_reset_mode` is called. In `libuv`, this function actually does nothing under windows, which leave us in a bad status.

Currently, we could wait for `libuv` to resolve this problem, or we could make a workaround to use `uv_tty_set_mode` to reset the mode to `UV_TTY_MODE_NORMAL`. Since I'm new to this project, could anyone give me advice of whether should I fire a pull request with workaround?

**Comment by justinmk** [comment]
>  or we could make a workaround to use uv_tty_set_mode to reset the mode to UV_TTY_MODE_NORMAL. Since I'm new to this project, could anyone give me advice of whether should I fire a pull request with workaround

PR is very welcome.
