### ISSUE TITLE
Not correctly flushed the screen when moving text down under Windows

### ISSUE THREAD

**Issue by Escapingbug** [neovim/neovim#10665]
- `nvim --version`: 0.3.8
- `vim -u DEFAULTS` (version: 8.1 ) behaves differently? yes
- Operating system/version: Windows 10 1903
- Terminal name/version: Alacritty 0.3.3 (also tested under WindowsTerminal preview, same result)
- `$TERM`: xterm-256color (cygwin the same)

### Steps to reproduce using `nvim -u NORC`

turn on line numbering: `set nu`

type following text:
```
if a == 1:
    print(1)

if b == 2:
    print(2)
if c == 3:
    print(3)
if c == 3:
    print(3)
if c == 3:
    print(3)
```
move the cursor to line 1 column 1, use insert mode, and press enter to insert newline

### Actual behaviour
screen is not fully flushed, some chracaters remained.

### Expected behaviour
fully flush the screen

### Extra Info

![nvim-bug](https://user-images.githubusercontent.com/19388242/62282388-0ee2bf00-b482-11e9-9538-d24838d4bddb.gif)

Currently I'm not sure how exactly it can be triggered, but in realworld code, it almost certainly will trigger.

**Comment by justinmk** [comment]
Duplicate, already fixed in 0.4 . Search closed issues
