### ISSUE TITLE
neovim not rendering correctly in PowerShell Remote Session

### ISSUE THREAD

**Issue by jantari** [neovim/neovim#10669]
**Platform:** Windows Server 2019 ( Version 10.0.17763.615)
**Neovim Version:**  0.3.8

When starting neovim in a PowerShell-Remoting session (`Enter-PSSession`), it does not render properly and cannot be exited as it does not respond to keystrokes.

At first I thought it is a terminal problem, but I tried:

- [Classic Microsoft conhost](https://github.com/microsoft/terminal)
- [New Windows Terminal](https://github.com/microsoft/terminal)
- [Terminus](https://github.com/Eugeny/terminus)
- [ConEmu](https://github.com/Maximus5/ConEmu)

all on their respective latest versions and they all show the same behavior, which can be seen here:

https://i.imgur.com/UTRSMXk.png

---

Neovim works properly over an ssh connection to my Windows Servers though, so maybe this is a Windows Remoting problem - I still wanted to tell you about it though so you're aware of the problem and/or can perhaps implement a workaround.

Thanks!

**Comment by bfredl** [comment]
What does a PowerShell-Remoting session do? How is it different from an ssh session? Does it not handle ANSI sequences?

**Comment by jantari** [comment]
PowerShell remoting establishes a [WinRM](https://docs.microsoft.com/en-us/windows/win32/winrm/ws-management-protocol) connection to a remote machine and lets you run commands against it - either interactively like `ssh` or non-interactively like this:

```powershell
# We are in PowerShell on our local machine here
PS > Invoke-Command -ComputerName SomeRemoteMachine01 -ScriptBlock {
    # This will be executed on "SomeRemoteMachine01" and the output (if any) serialized back to us
    # Invoke-Command does not open an interactive session, it runs the scriptblock and exits
    Get-Process nvim | Stop-Process
}
```

WinRM is an HTTP(S)-based protocol, running over Ports 5985 or 5986 depending on the kind of encryption.

I'm sorry if this is not the answer you were looking for, I am also not familiar with the exact protocol specification and inner workings of WinRM. Suffice to say, it is still the #1 remote management protocol on Windows - ssh is only available in Windows Server 2019, anything older has to rely on WinRM remoting.

**Comment by erw7** [comment]
I tried to see, but neither vim nor neovim work. neovim does not display a warning, but vim displays a warning like this:

```
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
```

I think `stdout`, `stdin` is not a console. This seems to be a limitation of the PowerShell-Remoting session. Unfortunately, I think it is impossible to run neovim in the PowerShell-Remoting session.

**Comment by bfredl** [comment]
Nothing we can fix then. Use ssh to remote nvim on Windows.
