### ISSUE TITLE
Nasty work if C:\Users\User\AppData\Local\nvim\init.vim doesn't exist

### ISSUE THREAD

**Issue by wave-blessed** [neovim/neovim#10674]
Hello!
I just trying to learn vim/neovim and have that neovim is better in my windows terminal (ConEmu) than vim.
But there is something screwed.
First of all I configure neovim by editing `$VIM\runtime\plugin\init.vim`
All of my configuration made not to tuch any %AppData%. I need portable app on some internal reasons.
Another point is using plugin manager. After some googling I've choosed vim-plug.
And here we are! I gеt very screwed [bug](https://github.com/junegunn/vim-plug/issues/862).
* Almost all (or may be all) plugins via vim-plug can't start automatically but can start manually.
* (another bug) Plugin gitgutter ignores its options in `$VIM\runtime\plugin\init.vim`

I tried another plugin manager: Vundle. Same thing.

And then tried make C:\Users\User\AppData\Local\nvim\init.vim for experiment. It's miracle — everything works fine! Plugins via vim-plug start excellent, gitgutter reads and applies its options.

Please fix it somehow.

My software:
* Windows 7 x64
* /neovim/releases/tag/nightly — nvim-win64.zip — nvim.exe (but I also tested nvim 3.8 stable and nvim-qt.exe)
* vim-plug and vundle latest and all tested plugins are latest.

P.s. Also I have weird problems while mapping <F2> or <F3>. Instead doing what I mapping, they doing sending something like B, C. But command :map shows what I've mapped.
But I haven't find out who is wrong here.

**Comment by justinmk** [comment]
> First of all I configure neovim by editing `$VIM\runtime\plugin\init.vim`
> All of my configuration made not to tuch any `%AppData%`. I need portable app on some internal reasons.

Then you need to read `:help startup` . Stuff in  `$VIM` runs at a different phase of startup than stuff in the normal user-config location. And if vim-plug does its setup during that phase, then 'runtimepath' will be ordered differently. 

> Please fix it somehow.

Fix what?
