### ISSUE TITLE
The "sudo nvim" command will ignores the XDG_DATA_HOME variable

### ISSUE THREAD

**Issue by dumoppa** [neovim/neovim#10684]
- `nvim --version`: NVIM v0.3.8
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: Arch Linux / Linux 5.2.5-arch1-1-ARCH
- Terminal name/version: gnome-terminal / 3.32.2-1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

My `XDG_DATA_HOME` is set to `~/.data`, when I use `nvim`, everything works fine, but when I use `sudo nvim`, it creates `.local/share/nvim/shada/main.shada` in the `/root/` directory.

### Actual behaviour

```shell
#  ~ echo $XDG_DATA_HOME
/root/.data
#  ~ rm .local/share/ -rf
#  ~ sudo nvim
#  ~ ls .local/share/nvim/shada/
main.shada
```

### Expected behaviour
`.local/share/nvim/shada/main.shada` should not be created, use `$XDG_DATA_HOME/nvim/shada/main.shada`

**Comment by justinmk** [comment]
`sudo` by default does not inherit the environment, for security. Try `sudo -E`.
