### ISSUE TITLE
A term buffer with a continous output is not updated when changing of tab

### ISSUE THREAD

**Issue by statox** [neovim/neovim#10696]
- `nvim --version`: `NVIM v0.4.0-741-gb6ad20602`
- `vim -u DEFAULTS` (version: ) behaves differently? Yes but I don't think it is relevant
- Operating system/version: Ubuntu 18.04
- Terminal name/version: Kitty 0.14.2
- `$TERM`: `screen-256color`

### Steps to reproduce using `nvim -u NORC`

```
while; do; echo $(date) >> test.tmp; sleep 1; done

nvim -u NORC +'term tail -f test.tmp'
# Wait until the output fills the screen 
# and press G to make sure the cursor is at the bottom of the screen
:tabnew
# Wait a few second to add lines to the term buffer
:tabprev
```

### Actual behaviour
![nvim-tail-error](https://user-images.githubusercontent.com/6271599/62474210-adcd2b00-b7a2-11e9-93da-cdec31ebd3d7.gif)

When switching back to the tab containing the term buffer, the output is not updated: you need to press `G` to see the last line and have the term buffer syncing with the output of the command.

### Expected behaviour

When switching back to the tab containing the term buffer, the output should be updated and I should be able to see the last line created by the command without having to press `G`.

FWIW if I simply split the screen and put my cursor in another buffer for sometime, the term buffer say synced with the output of the command.

---

Anyway it's a good occasion for me to thank you all for neovim which is a really amazing tool! Keep up with the good job :+1:

**Comment by bfredl** [comment]
Probably `adjust_topline()` in `terminal.c` should loop over all windows `FOR_ALL_TAB_WINDOWS(tp, wp)` instead of `FOR_ALL_WINDOWS_IN_TAB(wp, curtab)` .

**Comment by statox** [comment]
@bfredl Spot on! Changing that on a local build solves my problem.

Is it ok if I create a PR to change that or is there a potential performance issue?
I was thinking maybe I could use a new option to define which behavior to apply.

**Comment by bfredl** [comment]
> Is it ok if I create a PR to change that or is there a potential performance issue?

Probably nothing to worry about. We are already throttling/batching terminal updates before we get here.
