### ISSUE TITLE
wildmenu: <C-E>, <C-Y> behavior similar to insert-mode popupmenu

### ISSUE THREAD

**Issue by CallumHoward** [neovim/neovim#10693]
From `:h complete_CTRL-E` and `:h complete_CTRL-Y`, when completion is active/popup menu is displayed, `<C-E>` can be used to cancel a completion, `<C-Y>` can be used to accept a completion. It would be nice to have these mappings available in the command line when the wildmode popup menu is visible. 

An example use case for `<C-E>` is:
1. `:e ~/<Tab>`, completes to a long directory name
2. I want to cancel the completion and type the start of the directory I want, so I do `<C-E>Doc<Tab>` to get `:e ~/Documents/`

An example use case for `<C-Y>` is:
1. `:e ~/D<Tab>`, `Desktop` and `Documents` directories are shown
2. after another `<Tab>`, `:e ~/Documents/` is shown with popup menu visible still
3. I want to see all completion options in the Documents folder by pressing `<Tab>`, so I do `<C-Y><Tab>`

**Comment by justinmk** [comment]
This isn't specific to `wildoptions=pum`, it applies to wildmenu in general.

**Comment by erw7** [comment]
Wildmenu also do not work in `<PageUP>` and `<PageDown>` as compared to insert-mode  popupmenu.

**Comment by teto** [comment]
I've tested this and it works.
I dont know this part of the code much. It is annoying to have to duplicate code to reproduce the behavior but I guess it's unavoidable.

I am not sure the error is related, maybe try rebase and push
```
  [  FAILED  ] 1 test, listed below:
  [  FAILED  ] test/functional\lua\vim_spec.lua @ 449: lua stdlib vim.rpcrequest and vim.rpcnotify
  test/functional\lua\vim_spec.lua:521: Expected objects to be the same.
  Passed in:
  (table: 0x10b33948) { }
  Expected:
  (table: 0x1342a3b8) {
   *[1] = 3
    [2] = mpack.NIL }
  
  stack traceback:
  	test/functional\lua\vim_spec.lua:521: in function <test/functional\lua\vim_spec.lua:449>
  
```

**Comment by Billy4195** [comment]
@teto Do you use my branch or someone else? I run the test without error, should I rebase local repo and push to update the PR?

**Comment by teto** [comment]
Now supported (see related PR).
