### ISSUE TITLE
The syntax `contains` argument behavior does not match documentation

### ISSUE THREAD

**Issue by talbergs** [neovim/neovim#10717]
- `nvim --version`: NVIM v0.4.0-1534-g24fb7eefa
- Operating system/version: 5.1.2-arch1-1-ARCH
- Terminal name/version: v15 
- `$TERM`: termite

### Steps to reproduce using `nvim -u NORC`

```vim
" nvim -u NORC:
set conceallevel=2
set concealcursor=nc
set termguicolors
syntax enable
highlight Normal guibg=Black guifg=White
syn match ColorRed "r%.*%" contains=ColorDelim.*
syn match ColorDelimBeginRed contained "r%" conceal
syn match ColorDelimStop contained "%" conceal
hi ColorRed guifg=red
hi ColorBlue guifg=blue
```
```
This r%text% is red.
```
`nvim -u NORC ./textfile`

### Actual behaviour
Error:
E409: Unknown group name: ColorDelim.*
E475: Invalid argument: ColorRed "r%.*%" contains=ColorDelim.*

### Expected behaviour
As described here, groups need not to be defined, this is true, and works
https://github.com/neovim/neovim/blob/6fb0020df4eb799004c4a13bcf3326c4b1cf3fe5/runtime/doc/syntax.txt#L3997
except if pattern matching is done, then they have to be defined before the `contains={pattern}` ``https://github.com/neovim/neovim/blob/6fb0020df4eb799004c4a13bcf3326c4b1cf3fe5/runtime/doc/syntax.txt#L4026

**Comment by cangscop** [comment]
why is the code not behaving as expected? your `ColorDelim` are defined *after* `contains={pattern}`, not before.

**Comment by talbergs** [comment]
Yes, but the documentation states the opposite.
> The group names do not need to be defined before they can be used.

**Comment by talbergs** [comment]
I should elaborate:
```vim
" This works
syn match ColorDelimBeginRed contained "r%" conceal
syn match ColorDelimStop contained "%" conceal
syn match ColorRed "r%.*%" contains=ColorDelimBeginRed,ColorDelimStop
```
```vim
" This does not
syn match ColorDelimBeginRed contained "r%" conceal
syn match ColorDelimStop contained "%" conceal
syn match ColorRed "r%.*%" contains=ColorDelim.*
```
Documentation indicates, that both cases should work.

**Comment by cangscop** [comment]
The documentation is not very straightforward. The group names do not need to be defined beforehand, but only if their names are fully declared. Indeed, this code works as intended:
```vimscript
:syn match ColorRed "r%.*%" contains=ColorDelimBeginRed,ColorDelimStop
:syn match ColorDelimBeginRed contained "r%" conceal
:syn match ColorDelimStop contained "%" conceal
```
On the other hand, if a pattern is given and there is no match, `syn match` will not use the group names defined at a later time, even if they do match:
> Groups that are defined later will not be matched.

**Comment by justinmk** [comment]
Does Vim have a different behavior?

**Comment by talbergs** [comment]
>  The group names do not need to be defined beforehand, but only if their names are fully declared (i.e. if they are group names, not patterns).

Yes, this sounds better!

Not sure about Vim though, how is it behaving with `syn match *`.

I am sorted now, but when I was learning the `syn` topic I lost a bit of _time_ in confusion, because this line:
>The matching will be done at moment the syntax command is executed.Groups that are defined later will not be matched.

met my eye later, during my doc-read'n'tinker process. By then, through some trail and error process I already had deduced the exact behaviour and accepted it. This ticket initially is about documentation. It is your choice if the behaviour should be tweaked instead or not.

**Comment by talbergs** [comment]
> Does Vim (mention exact version) have a different behavior?

Oh, that was in bugreport fill-out, will try to prep it soon.

**Comment by talbergs** [comment]
Vim 8.1 behaves exactly the same (documentation is also the same).

**Comment by justinmk** [comment]
Report to https://github.com/vim/vim . We will merge the result if any change is made.
