### ISSUE TITLE
hit assert at ui_compositor.c:484

### ISSUE THREAD

**Issue by comicfans** [neovim/neovim#10719]
- `nvim --version`: NVIM v0.4.0-1176-gbe949d6c9
- `vim -u DEFAULTS` (version: ) behaves differently? not tried
- Operating system/version: archlinux 64bit
- Terminal name/version: run from neovim-qt

### Steps to reproduce using `nvim -u NORC`
not tried

# Alternative for shell-related problems:
not tried

### Actual behaviour
hit assert at ui_compositor.c:484
```C
  assert(clearcol <= default_grid.Columns);
```
nvim crash with following backtrace:

<pre>
#4  0x0000000000642e8b in ui_comp_raw_line (ui=<optimized out>, grid=<optimized out>, row=0, startcol=94, endcol=0, clearcol=114, clearattr=0, flags=<optimized out>, chunk=0x4cb7736, attrs=0x423228c) at ../src/nvim/ui_compositor.c:484
#5  0x000000000063fe25 in ui_call_raw_line (grid=<optimized out>, row=<optimized out>, startcol=94, endcol=<optimized out>, clearcol=<optimized out>, clearattr=<optimized out>, flags=0, chunk=0x4cb7736, attrs=0x423228c) at src/nvim/auto/ui_events_call.generated.h:225
#6  ui_line (grid=<optimized out>, row=<optimized out>, startcol=<optimized out>, endcol=<optimized out>, clearcol=<optimized out>, clearattr=<optimized out>, wrap=<optimized out>) at ../src/nvim/ui.c:340
#7  0x00000000005e615b in grid_put_linebuf (grid=<optimized out>, row=<optimized out>, coloff=<optimized out>, endcol=<optimized out>, clear_width=<optimized out>, rlflag=<optimized out>, wp=<optimized out>, bg_attr=<optimized out>, wrap=<optimized out>)
    at ../src/nvim/screen.c:4505
#8  0x00000000005e4eb6 in win_line (wp=<optimized out>, lnum=<optimized out>, startrow=<optimized out>, endrow=<optimized out>, nochange=<optimized out>, number_only=<optimized out>) at ../src/nvim/screen.c:4009
#9  0x00000000005d8c3a in win_update (wp=0x4893bb0) at ../src/nvim/screen.c:1378
#10 0x00000000005d6d88 in update_screen (type=<optimized out>) at ../src/nvim/screen.c:480
#11 0x00000000005de319 in screen_resize (width=<optimized out>, height=<optimized out>) at ../src/nvim/screen.c:7226
#12 0x000000000063f6a6 in ui_refresh () at ../src/nvim/ui.c:212
#13 0x0000000000452d55 in handle_nvim_ui_try_resize (channel_id=<optimized out>, args=..., error=0x0) at src/nvim/auto/api/private/dispatch_wrappers.generated.h:2278
#14 0x00000000005659b2 in request_event (argv=<optimized out>) at ../src/nvim/msgpack_rpc/channel.c:372
#15 0x00000000004c872f in multiqueue_process_events (this=0x20e3370) at ../src/nvim/event/multiqueue.c:150
#16 0x0000000000574762 in nv_event (cap=0x7fff868bc350) at ../src/nvim/normal.c:7983
#17 0x000000000056e1fe in normal_execute (state=0x7fff868bc2c8, key=<optimized out>) at ../src/nvim/normal.c:1130
#18 0x000000000061c430 in state_enter (s=0x7fff868bc2c8) at ../src/nvim/state.c:73
#19 0x0000000000567d94 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at ../src/nvim/normal.c:462
#20 0x00000000005394c7 in main (argc=<optimized out>, argv=<optimized out>) at ../src/nvim/main.c:570
</pre>

I'm running X11 with i3 (tiled)  windows manager , firstly I run neovim-qt , use nvim-R console (a R lang plugin, operate just like built-in terminal) to create another GUI window , at same time nvim-R will print some output in nvim.  (under i3 wm,  newly created window will split screen into left/right space) , when neovim-qt window size changed to half screen, nvim crashed.  this is not 100% reproducible , but triggerd more easily if neovim-qt size jump back and forth( maybe under i3 wm control, ui size changed dramatically) while plugin print some output in nvim

**Comment by justinmk** [comment]
#9989

**Comment by blueyed** [comment]
Re-opened #9989.
