### ISSUE TITLE
why nvim_gui_shim.txt is not in .../nvim-qt/runtime/doc

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#10722]
- Operating system/version: Windows 10

### Actual behaviour
[nvim win64 release](https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip)  doesn't ship with `...\nvim-win64\Neovim\share\nvim-qt\runtime\doc\nvim_gui_shim.txt`

**Comment by justinmk** [comment]
`nvim_gui_shim.vim` is a temporary, unsupported feature. It will be removed after https://github.com/neovim/neovim/pull/6917 is implemented.
