### ISSUE TITLE
Incompatible behavior with vim on set bin

### ISSUE THREAD

**Issue by erw7** [neovim/neovim#10730]
- `nvim --version`: NVIM v0.4.0-1595-gce628e118
- `vim -u DEFAULTS` (version: 8.1.1806) behaves differently? Later
- Operating system/version: N/A
- Terminal name/version: N/A
- `$TERM`: N/A

### Steps to reproduce
Create an empty vimrc with the name empty.vim as shown below.

```vim
" empty vimrc
```

```
nvim -u empty.vim
:set bin
:enew
:set nobin
:e #
:set bin?
```

### Actual behaviour
`binary`

### Expected behaviour
`nobinary`

In vim, it becomes `nobinary` by the same operation. Strangely, if I run it with `vim -u NORC -N` or `vim -u DEFAULTS`, it will be `binary`. I don't know if this is a neovim bug. However, because of the difference in behavior, it was necessary to change test42.in as follows. Create an issue just in case.

```diff
--- src/nvim/testdir/test42.in.orig     2019-08-09 13:07:18.567957200 +0900
+++ src/nvim/testdir/test42.in  2019-08-09 13:03:57.215791300 +0900
@@ -11,8 +11,7 @@
 :/^ucs-2$/+1w! Xtest3
 :/^ucs-2le$/+1w! Xtest4
 :" Need to add a NUL byte after the NL byte
-:set bin
-:e! Xtest4                      " Ignore change from setting 'ff'
+:e! ++bin Xtest4                " Ignore change from setting 'ff'
 o^V^@^[:set noeol
 :w
 :set ffs& nobinary              " Allow default test42.in format
@@ -21,8 +20,7 @@
 :/^ucs-4$/+1w! Xtest5
 :/^ucs-4le$/+1w! Xtest6
 :" Need to add three NUL bytes after the NL byte
-:set bin
-:e! Xtest6                      " ! for when setting 'ff' is a change
+:e! ++bin Xtest6                " ! for when setting 'ff' is a change
 o^V^@^V^@^V^@^[:set noeol
 :w
 :set nobin
```

**Comment by justinmk** [comment]
> Strangely, if I run it with `vim -u NORC -N` or `vim -u DEFAULTS`, it will be `binary`.

cc @chrisbra @brammool

**Comment by brammool** [comment]
Check the 'cpo' option, specifically the 's' and 'S' flags.  
Normally the 'binary' flag is set (or not set) when the buffer is created, and remembered so long as the buffer exists.  It's only reset when you do that while editing the buffer.  If you re-open the buffer the previously set value will be used, not the global value.

**Comment by erw7** [comment]
@brammool Thank you very much. When `set cpo+= S`, it became `nobinary` in all cases.
