### ISSUE TITLE
Security: Limit runtimepath evaluation

### ISSUE THREAD

**Issue by BertramScharpf** [neovim/neovim#10732]
On start, NVim executes all plugins that can be found in &runtimepath.
If NVim runs as user root, this should not be done for relative path components .

My motivation:

I have some repositories where I define project-specific key bindings or abbreviations.
These lie in "./.vim/plugin/<myproject>.vim". Therefore, my vimrc has a line:

  set runtimepath+=.vim

Now consider the case I merge somebody else's code, then enter the directory as root, and start NVim...

**Comment by justinmk** [comment]
Even without root that is risky. Why spend time implementing a half-measure?

PR welcome anyways, but it should show some error or other indication, not just silently behave differently.
