### ISSUE TITLE
Enable using old MANWIDTH behavior, mostly for man pages with tables

### ISSUE THREAD

**Issue by doronbehar** [neovim/neovim#10748]
<details><summary>Boring details</summary>

- `nvim --version`:

```
NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/2yhjcv0qammzhh88fgy5l9921nqv6kw1-neovim-unwrapped-0.3.8/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: NixOS
- Terminal name/version: Alacritty
- `$TERM`: `screen`
</details>

Since my PR (#9023) was merged, when viewing certain manual pages (e.g `systemd.unit(5)`) I feel the old behavior - where `$MANWIDTH` is set to the buffer's width, was better. Basically, it comes down to the way tables appear.

Here's a screen shot:

![bad-man](https://user-images.githubusercontent.com/10998835/62835098-fa51b400-bc43-11e9-8039-43170b0acab8.png)

I was wondering, is it even possible to overcome this? Perhaps we can create binding / command that will reopen the man page at the same location but with `$MANWIDTH` set to the buffer's width? I'm not sure what's the best way to go. I'm asking for your opinion and I'd be glad to work on it my self.

**Comment by justinmk** [comment]
`g:man_hardwrap` #9633 ?

**Comment by doronbehar** [comment]
I've tried the latest git master's `runtime/` with `env VIM=$PWD/runtime` and this is what I noticed:

First of all, there's a small but different issue I forgot all about which I've noticed a while back ago and unfortunately I've worked around it but haven't reported it. To simply put it: If I don't set `$MANWIDTH` in my environment, I don't get the desired behavior for which I've created #9023 in the first place - Hard wrapping is used even with #9023 merged (both in `master` and 3.8).

This has led me to set by default `MANWIDTH=999` in my environment and I forgot this when I reported this issue.

Because of this separate issue, I can't tell you if I can see the effect of `g:man_hardwrap` at all.

@justinmk I hope you could aid me at investigating it. I've tried `echo`ing some variables here:

https://github.com/neovim/neovim/blob/cc4d463cad6ccc81ca4803092be09cd27185d646/runtime/autoload/man.vim#L151-L161

And the desired behavior seem to reach the variable `manwidth` from that expression in line 155, whether I set or unset `$MANWIDTH` and `g:man_hardwrap`.

However, in my case, the final result seem to depend only upon `$MANWIDTH` and not `g:man_hardwrap`.

I've also tried in a different terminal to view the output of that `cmd` and have a look at the way the large tables are formatted and the output was the same as in my screenshot.

**Comment by justinmk** [comment]
> However, in my case, the final result seem to depend only upon `$MANWIDTH` and not `g:man_hardwrap`.

With `:let g:man_hardwrap=1`, `:Man systemd.unit(5)` renders the tables correctly for me. It is driven by `$MANWIDTH` as [documented](https://github.com/neovim/neovim/pull/9633/files#diff-7554a5b661ea60ae84f39c79b31c2c14R552) .

**Comment by doronbehar** [comment]
I understand. This is not the separate issue I was trying to describe. What I'm saying is that from some reason, for me, even If I don't `:let g:man_hardwrap=1`, hard wrapping is used. Unless I set `$MANWIDTH` in my environment.

So I said:

> However, in my case, the final result seem to depend only upon `$MANWIDTH` and not `g:man_hardwrap`.

Could you please reopen?

**Comment by doronbehar** [comment]
Please see this Asciinema recording: https://asciinema.org/a/261943

**Comment by justinmk** [comment]
> even If I don't `:let g:man_hardwrap=1`, hard wrapping is used. Unless I set `$MANWIDTH` in my environment.

That doesn't make sense. The original screenshot shows what happens _without_ hard wrapping. And it matches what I see on my system.

I don't understand the purpose of the video you made. If MANWIDTH were being used, then `MANWIDTH=20 nvim` would show a very narrow hard-wrapped text. Does that happen, or not?

**Comment by doronbehar** [comment]
That screenshot was taken while I had `MANWIDTH=999` in my environment.

I'm sorry it comes out so confusing and that my original idea isn't yet discussed. The point is, that at least for me, there is no way I can make `Man.vim` actually use soft wrapping, without altering `$MANWIDTH`.

I tried hard to debug this by looking at the messages I see after adding some `echo` commands at `autoload/man.vim`. Here's a diff of my debug attempt:

<details>

```patch
diff --git i/runtime/autoload/man.vim w/runtime/autoload/man.vim
index 153f1afed..a1ddfd776 100644
--- i/runtime/autoload/man.vim
+++ w/runtime/autoload/man.vim
@@ -126,6 +126,11 @@ function! s:system(cmd, ...) abort
         \ 'on_exit': function('s:system_handler'),
         \ }
   let jobid = jobstart(a:cmd, opts)
+  if a:0
+    let pid = jobpid(jobid)
+    echo 'MAN* environment in our MANPAGER=cat process is ' . pid
+    echo system('grep -z "^MAN" /proc/' . pid . '/environ | tr "\0" "\n"')
+  endif
 
   if jobid < 1
     throw printf('command error %d: %s', jobid, join(a:cmd))
@@ -156,8 +161,10 @@ function! s:get_page(path) abort
   " Force MANPAGER=cat to ensure Vim is not recursively invoked (by man-db).
   " http://comments.gmane.org/gmane.editors.vim.devel/29085
   " Set MAN_KEEP_FORMATTING so Debian man doesn't discard backspaces.
+  echo 'using man width of '.manwidth
   let cmd = ['env', 'MANPAGER=cat', 'MANWIDTH='.manwidth, 'MAN_KEEP_FORMATTING=1', 'man']
-  return s:system(cmd + (s:localfile_arg ? ['-l', a:path] : [a:path]))
+  echo 'cmd is ' . string(cmd + (s:localfile_arg ? ['-l', a:path] : [a:path]))
+  return s:system(cmd + (s:localfile_arg ? ['-l', a:path] : [a:path]), 1)
 endfunction
 
 function! s:put_page(page) abort
```

</details>

If I set `MANWIDTH=20` I do get a narrow hard wrapped formatting as you described - no matter what's with `g:man_hardwrap`.

The weirdest thing, is that with that patch applied, I see `$MANWIDTH` is set correctly at the `MANPAGER=cat` command etc... but the final result looks as if `$MANWIDTH` was _not_ set to 999 during that `MANPAGER=cat` command and that it was set to `$COLUMNS` (or `winwidth()`) (:confounded:). Anyway I'm starting to rip the hairs of my head because I feel I'm not even looking at the right place..

I hope the following tables will explain the situation better:

| The _only_ variables set | Actual manwidth used in Neovim buffer |
| --- | --- |
| `$MANWIDTH` | `$MANWIDTH` |
| `g:man_hardwrap` | `$COLUMNS` |
| non | `$COLUMNS` |

| The _only_ variables set | manwidth as reported by the `echo` statements |
| --- | --- |
| `$MANWIDTH` | 999 |
| `g:man_hardwrap` | `$COLUMNS` / `winwidth()` |
| non | 999 |

Vs on your machine, I think the 1st and the 2nd tables should be:

| The _only_ variables set | Actual manwidth used in Neovim buffer |
| --- | --- |
| `$MANWIDTH` | 999 |
| `g:man_hardwrap` | `$COLUMNS` / `winwidth()` |
| non | 999 |

Just like my 2nd table.

While I tested this again today, I've done everything while `$VIM` was set 

@justinmk What messages do you see when you apply this patch?

I've also checked that my `man` command is not aliased or wrapped in a suspicious way.

Could it be that a different implementation of `man` is setting `$MANWIDTH` to `$COLUMNS` before it calls `ngroff`? I can't imagine a reason a different implementation will choose to do so but it seems as the only reasonable explanation.

**Comment by doronbehar** [comment]
I've found out what's the problem and I've concisely described it better in https://github.com/neovim/neovim/issues/10808 . As for the original suggestion / idea I've had in mind, certainly https://github.com/neovim/neovim/pull/9633 solved it already so _this_ issue is solved for me.
