### ISSUE TITLE
Feature Request: Stabilize "Special Types" Message Pack Type Codes

### ISSUE THREAD

**Issue by TyOverby** [neovim/neovim#10740]
Currently, the [msgpack_rpc API documentation](https://neovim.io/doc/user/msgpack_rpc.html#rpc-types) says this about the message pack type codes: 

> Even for statically compiled clients it is good practice to avoid hardcoding
the type codes, because a client may be built against one Nvim version but
connect to another with different type codes.

While it is certainly possible to create a statically compiled client which defers knowledge  the type-code information until run time, the instability makes the process considerably harder.  In particular, the deserialization or serialization of any types that reference buffers, tabpages, or windows must require an open connection to a neovim client.  

It would be a better experience for those writing static clients for these constants to be fixed, and considered a part of the stable API.

**Comment by bfredl** [comment]
I think we decided on keeping the EXT type representation fixed like two years ago, but apparently it never got into this part of the documentation. (I'm pretty sure it is written somewhere else, otherwise we couldn't have deprecated `nvim_buf_get_number` and the like). Sorry for the confusion.

**Comment by bfredl** [comment]
Or the language seems to suggest we have stabilized the _content_ of the EXT messages, but not their type code, which for sure is a weird discrepancy. There should be no reason to not document them as completely fixed.
