### ISSUE TITLE
&pythonx gets set to 2 despite python 2 not working

### ISSUE THREAD

**Issue by mgedmin** [neovim/neovim#10758]
- `nvim --version`: v0.4.0-1674-gad4eb18e4
- `vim -u DEFAULTS` (version: 8.1.1843) behaves differently? yes
- Operating system/version: Ubuntu 19.04
- Terminal name/version: gnome-terminal 3.32.1 using VTE 0.56.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
python -m pip uninstall neovim pynvim
python3 -m pip install pynvim
nvim -u NORC
:set pyxversion?    " prints 0
:pyx print("hi")
:py3 print("ho")
```

### Actual behaviour

```
E319: No "python" provider found. Run ":checkhealth provider"
ho
```

### Expected behaviour

```
hi
ho
```

### Other notes

The [documentation](https://github.com/neovim/neovim/blob/90e44ecf1144cb32195da00e24d23afb111ea680/runtime/doc/options.txt#L4534-L4537) says:

>         If 'pyxversion' is 0, it is set to 2 or 3 after the first execution of
>         any python2/3 commands or functions.  E.g. :py sets to 2, and :py3
>         sets to 3. :pyx sets it to 3 if Python 3 is available, otherwise sets
>         to 2 if Python 2 is available.

so :pyx is supposed to set pyxversion to 3, since

```
:echo has("python3")
1
:echo has("python")
0
```

Also, if I try :py3 it should set pyxversion to 3, according to the documentation, but you can see this doesn't happen:

```
nvim -u NORC
:set pyxversion?
  pyxversion=0
:py3 print("hi")
:set pyxversion?
  pyxversion=0
:pyx print("hi")
E319: No "python" provider found. Run ":checkhealth provider"
```

**Comment by bfredl** [comment]
can reproduce. Perhaps this got broken in the recent provider check refactor #10161 . Strange that it didn't break any test though.

**Comment by bfredl** [comment]
Rather `init_pyxversion` looks completely wrong:
```
// Detect Python 3 or 2, and initialize 'pyxversion'.
void init_pyxversion(void)
{
  if (p_pyx == 0) {
    if (!eval_has_provier("python3")) {
      p_pyx = 3;
    } else if (!eval_has_provider("python")) {
      p_pyx = 2;
    }
  }
}
```

The result of `eval_has_provider` should not be reversed.

**Comment by bfredl** [comment]
Also `pyeval()` forces `p_pyx` to 2 without even testing, which `:python` does not do, even if it is working. (The later of which is correct, 'pyxversion' must never be automatically set to 2 when python3 is available)
