### ISSUE TITLE
wildmenu: 'completeopt' behavior

### ISSUE THREAD

**Issue by wookayin** [neovim/neovim#10771]
- `nvim --version`: NVIM v0.4.0-1679-g947bd293c
- `vim -u DEFAULTS` (version: ) behaves differently?  same
- Operating system/version:  linux, but it's agnostic to OS

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set wildmenu
:set wildoptions+=pum
:set completeopt+=longest
```

### Actual behaviour

Upon popupmenu completion in the command line (wildmenu), e.g. <kbd>Tab</kbd>, it matches and selects the first match. 

### Expected behaviour

However, I would like to make it insert only the longest common text of the matches (e.g. `completeopt=longest`) This setting works in the normal completion, but it is not respected in the wildmenu. Seems there is no way to configure this.

**Comment by justinmk** [comment]
Related: #10693

**Comment by bfredl** [comment]
`wildmode` is used for this in cmdline mode. I use `wildmode=longest:full,full` myself.

**Comment by wookayin** [comment]
@bfredl Great, this works perfectly.

I had tried `:set wildmode=longest:full` (without `,full` followed), but it didn't enable `<Tab>` completion after opening the popup menu. Having the second part `,full` solves the problem.

Thank you again for all your help!
