### ISSUE TITLE
Failed to run healthcheck (Cannot redefine function health#check)

### ISSUE THREAD

**Issue by farzadmf** [neovim/neovim#10782]
- `nvim --version`:
```
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
I don't think `checkhealth()` is applicable to `vim`

- Operating system/version:
Manjaro Linux: `Linux 5.1.21-1-MANJARO GNU/Linux`

- Terminal name/version:
Gauek 3.6.3

- `$TERM`:
`screen-256color`

### Steps to reproduce using `nvim -u NORC`
1. Open neovim
2. Run `:checkhealth()`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
When I open neovim and then run `:checkhealth()`, I get the following error, stating `Failed to run healthcheck for "()" plugin`, followed by `Cannot redefine function health#check: It is in use`

![image](https://user-images.githubusercontent.com/5768792/63070268-86840580-bee8-11e9-8083-d52c8839eb15.png)

But when I run `nvim -c checkhealth` from the terminal, I can see the health status

### Expected behaviour
I should be able to run `:checkhealth()` when I'm inside neovim

**Comment by blueyed** [comment]
Thanks for the report!
Are you able to check the nightly build (or build Git master yourself)?

**Comment by farzadmf** [comment]
Thank you @blueyed for the reply. It's late at night for me now, I'm gonna give it a try, hopefully tomorrow

**Comment by justinmk** [comment]
> When I open neovim and then run `:checkhealth()`

It's a command, not a function.

    :checkhealth
