### ISSUE TITLE
Disable / fix quickbuild

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10787]
Recently quickbuild appears to fail just because it kills the tests itself?!

```
16:19:08,450 INFO  - ok 3055 - Command-line coloring does the right thing when hl start appears to split multibyte char
16:19:08,467 INFO  - Terminating launched command gracefully...
16:19:08,468 DEBUG - Executing command: sh /usr/home/quickbuild/buildagent/framework/configuration/org.eclipse.osgi/com/pmease/quickbuild/execution/kill-tree.sh 53422 
16:19:08,468 DEBUG - Command working directory: /usr/home/quickbuild/buildagent/bin
16:19:08,493 WARN  - Terminated
16:19:08,596 INFO  - Executing post-execute action...
16:19:08,597 ERROR - Step 'master>buildall>build-node?testNode=freebsd-64>build-and-run-tests>build-and-run-tests-parameterized?buildType=Release>run-tests>run-functional-tests' is failed.
    java.lang.RuntimeException: java.lang.InterruptedException
```
(https://github.com/neovim/neovim/pull/10786#issuecomment-521826500)

This should either be fixed immediately (where is the config for it after all?), and/or just get disabled for now.
It is very distracting - especially given the reluctance for when coverage builds were flaky - quickbuild is much more disturbing than that.

**Comment by justinmk** [comment]
command-line coloring has an open issue, and it is probably a legitimate failure. https://github.com/neovim/neovim/pull/8421 (the failure mentioned in that PR is different, but that code also drives command-line coloring)

> where is the config for it after all?

It's on the quickbuild server. It's possible to become an admin there, but I think our time is better spent evaluating https://sourcehut.org/  . @vext01 is working on that soon for OpenBSD, and then we could also set up FreeBSD there. 

(I pushed the repo to https://git.sr.ht/~jmk/neovim but probably not needed, sourcehut can run builds directly from GitHub.)

Meanwhile we can disable the `Command-line coloring` test on QuickBuild.

**Comment by justinmk** [comment]
There is work in progress to switch to https://sourcehut.org

**Comment by blueyed** [comment]
@justinmk 
That's nice, looking forward to it being done (https://github.com/neovim/neovim/pull/10804).

Can we disable Quickbuild then already?  (to get less red X's in general on PRs)
