### ISSUE TITLE
Weird colorschemes in neovim

### ISSUE THREAD

**Issue by vl-underworld** [neovim/neovim#10796]
- `nvim v0.3.8`:
- `vim v8.1.1776`, behaves differently: there is no issue, colorscheme works like a charm
- Operating system/version: Arch Linux, kernel v5.2.8
- Terminal name/version: urxvt v9.22 / st v0.8.2
- `$TERM`: rxvt-unicode-256color / st-256color

### Steps to reproduce using `nvim -u NORC`
Install custom theme, in my case gruvbox (https://github.com/morhetz/gruvbox);
Set this colorscheme in ~/.config/nvim/init.vim or using `:colo gruvbox`

### Actual behaviour
In neovim, `:colo gruvbox` applies theme, but nothing changes, all colors remain the same.
### Expected behaviour
In neovim, `:colo gruvbox` applies theme and everything changes colors.

### Screenshot
![2019-08-17-094625_1920x1080_scrot](https://user-images.githubusercontent.com/53948588/63207886-7cbff500-c0d6-11e9-95fa-d98f2bb6aab9.png)

Top left corner: urxvt with vim (gruvbox works)
Top right corner: st with vim (gruvbox works)
Bottom left corner: urxvt with neovim (gruvbox doesnt work)
Bottom right corner: st with neovim (gruvbox doesnt work)

My whole config is on the screenshot, I use the same for both editor to check behaviour.
Thanks in advance.

**Comment by justinmk** [comment]
People use gruvbox in Nvim, so this report is incomplete. Maybe try Nvim 0.4 (prerelease) or try a different terminal.
