### ISSUE TITLE
Adding javascriptreact / typescriptreact filetypes

### ISSUE THREAD

**Issue by impulse** [neovim/neovim#10802]
I assume all plugins trying to fully support Microsofts language server protocol are affected by this. As you can see in the [LSP specification](https://microsoft.github.io/language-server-protocol/specification) there are filetypes named `javascriptreact` and `typescriptreact`. This is also the case for [VSCode](https://code.visualstudio.com/docs/languages/identifiers) since it is built upon that. 

Taking a look at my autocomplete plugin of choice (coc.nvim), they also seem to require to set either of those filetypes f.ex [(javascriptreact or javascript.jsx)](https://github.com/neoclide/coc.nvim/blob/b9967440b806a20067342b2ecc09682e6e1c685c/src/model/document.ts#L86) in order to have support for jsx/tsx specific snippets. This is also confirmed by a maintainer [here](https://github.com/neoclide/coc.nvim/issues/459#issuecomment-465658887).

Would there be any drawbacks on making those filetypes official? I would love to hear your opinions on this.

**Comment by justinmk** [comment]
Send this request to https://github.com/vim/vim, we are not interested in forking the Vim runtime files.

**Comment by marlun** [comment]
typescriptreact was added to vim in back in 2019 with  https://github.com/vim/vim/commit/92852cee3fcff1dc6ce12387b234634e73267b22 but does not seem to have found its way into neovim. Is this intentionally or just haven't happened yet?

**Comment by stsewd** [comment]
@marlun the patch needs to be sent to neovim https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim

**Comment by marlun** [comment]
Thanks @stsewd I will look into doing that.
