### ISSUE TITLE
How I download the documentation?

### ISSUE THREAD

**Issue by NightMachinary** [neovim/neovim#10803]
I like to download https://neovim.io/doc/user/pi_netrw.html so that I can convert it to epub and read it on an ereader.

What's the format of the file used to generate the docs, and where are those files?

**Comment by justinmk** [comment]
> I like to download https://neovim.io/doc/user/pi_netrw.html so that I can convert it to epub and read it on an ereader.

script is provided in https://github.com/neovim/bot-ci/issues/147 . We would like to automate that (to produce a single, big PDF). Help there is welcome.

> What's the format of the file used to generate the docs, and where are those files?

The HTML is generated from Vim's own ad-hoc "help" format, documented at `:help help-writing`.

**Comment by NightMachinary** [comment]
@justinmk That script downloads the html files. I tried that myself, too (I have scripts that convert URLs to epub using pandoc), but the result was pretty unusable. Where’s the script that generates the HTML? That might be a better starting point.

**Comment by justinmk** [comment]
currently [makehtml.awk](https://github.com/neovim/neovim/blob/master/runtime/doc/makehtml.awk) is used but I would like to eliminate it in favor of [this python script](https://github.com/neovim/neovim/blob/master/scripts/gen_help_html.py). The python script works, but the generated HTML is ugly. Help is welcome there also.

Also, the awk script checks for duplicate tags; that needs to be done by the python script before we can eliminate the awk script.

**Comment by NightMachinary** [comment]
In the end, I copied all the text via Chrome, and put the text in a
codeblock in markdown, and converted the markdown to epub. The end result
is readable.
