### ISSUE TITLE
Un-reserve :X as a command

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#10806]
#694 and #701 removed the support for encryption (which seems totally sensical!)

But trying to bind :X still says the name is reserved:

```
:command! -bang -complete=file -nargs=? X x<bang> <args>
E841: Reserved name, cannot be used for user defined command
```

I have quick fingers, so I [rebind all the similar-ish uppercase equivalents of common quitting commands](https://github.com/Julian/dotfiles/blob/b80746311bbf66bff3bedf20c4b38d1901d51322/.vim/init.vim#L133-L148) so that if I mistype they still work.

Since :X is still reserved though, I have to resort to the sledgehammer-y `cnoabbrev`.

Maybe there's plans to re-add it at some point, but if not, it'd be nice if it didn't raise an exception.

- `nvim --version`:
```
⊙  nvim --version                                                                                                                                                     julian@Air ●
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/build/config -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/build/src/nvim/auto -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.8/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: macOS
- Terminal name/version: alacritty

**Comment by justinmk** [comment]
> Maybe there's plans to re-add it at some point, but if not, it'd be nice if it didn't raise an exception.

Even if it is restored in some form later, I don't see why `:X` should be reserved instead of a lowercase command.

**Comment by Julian** [comment]
Cool :) -- Then #10807 does this -- hopefully I haven't done anything drastically wrong, first patch.
