### ISSUE TITLE
Using the recommended $MANPAGER acts differently then using :Man!

### ISSUE THREAD

**Issue by doronbehar** [neovim/neovim#10808]
I've almost figured this out in #10748 but that issue was originally opened for a different reason which was [solved](https://github.com/neovim/neovim/pull/9633) and the issue I was describing there along the way wasn't explained very well so I'm attempting to describe it here after I've made progress investigating it.

- `nvim --version`:

```
NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/2yhjcv0qammzhh88fgy5l9921nqv6kw1-neovim-unwrapped-0.3.8/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: NixOS
- Terminal name/version: Alacritty
- `$TERM`: `screen`

### Steps to reproduce using `nvim -u NORC`

Basically, the problem is perhaps more of a documentation issue. In order to use Nvim as a manpager, `ft-man-plugin` recommends setting the following in the shell:

```
export MANPAGER='nvim +Man!'
```

This doesn't emulate perfectly what `:Man! <manpage>` does. When `man` is invoked from the shell, prior formatting is done by man / groff outside of Nvim and the output is then piped to Nvim. The disadvantage / problem with that is that e.g MANWIDTH is not set to 999 as in `:Man` (with `g:man_hardwrap` unset / `=0`) and so the output is hard wrapped in any case.

I'll demonstrate:

```
$ env MANPAGER="nvim +Man!" man man
# Here, formatting is done by man / groff so it hardwraps the output
:q
# nvim -u NORC
:Man! man
```

### Actual behaviour

The formatting of the manpage when used with `man` and `$MANPAGER` is different in comparison to the formatting done using `:Man!` _inside_ Nvim.

### Expected behaviour

Same formatting is used.

### Suggested solution

Perhaps it could suffice only to mention this issue in the help file? Perhaps we should recommend setting also `MANWIDTH=999` if one wishes to see man pages softwrapped even when viewed by `man` from the shell?

**Comment by justinmk** [comment]
> When `man` is invoked from the shell, prior formatting is done by man / groff outside of Nvim and the output is then piped to Nvim

sure, if it can be expressed without paragraphs of text please send a doc PR. Doesn't sound like this is fixable otherwise.
