### ISSUE TITLE
floats: option to truncate width instead of moving on too narrow screen

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10811]
Currently floating windows are moved left if they would overflow the screen to the right ("do not fit `width`wise").

Vim has a "fixed" option for popup windows that corresponds to this:
```
	fixed		When FALSE (the default), and:
			 - "pos" is "botleft" or "topleft", and
			 - "wrap" is off, and
			 - the popup would be truncated at the right edge of
			   the screen, then
			the popup is moved to the left so as to fit the
			contents on the screen.  Set to TRUE to disable this.
```

Without this you would have to take care of passing in an appropriate `width` (which must take into account any vertical scrolling (sidescroll) also.

I am using `{'relative': 'cursor', 'anchor': 'NW', …}`.

The use case is displaying call signatures (within jedi-vim), which should be positioned at the opening parenthesis.
I am specifying the `width` according to the longest line in there.

While this appears to work it would be nice if it could be avoided with something similar to Vim's "fixed" option:

```vim
cur_col = vim.current.window.cursor[1]
floatwin_col_offset = sig_bracket_start_col - cur_col - 1

" Extra processing to not make Nvim move it left.
start_wincol = vim.funcs.wincol() + floatwin_col_offset
max_width = vim.options["columns"] - start_wincol + 1
width = min([max_sig_width, max_width])

opts = {
    'relative': 'cursor',
    'width': width,
    'height': len(lines),
    'col': floatwin_col_offset,
    'row': -1 * len(lines),
    'anchor': 'NW',
}
win = vim.api.open_win(buf, 0, opts)
```

**Comment by bfredl** [comment]
Sure, shouldn't be too difficult to add.

**Comment by blueyed** [comment]
Thought that it might have been a good default even, but I can see that it is good to move it usually when at the right side of the screen (with NW).

**Comment by flimofly** [comment]
@blueyed Sorry to revive this old thread but given what you write in your first sentence ("Currently floating windows are moved left if they would overflow the screen to the right"), is this expected behaviour? 

<img width="923" alt="Screenshot 2021-01-15 at 22 10 56" src="https://user-images.githubusercontent.com/20085376/104779024-a4f5cc80-577e-11eb-9e0b-12baaa833c6f.png">

I'm unsure whether this float win truncation is neovim's fault or my completion engine's (coc.nvim).
