### ISSUE TITLE
win32yank doesn't need to be symlinked

### ISSUE THREAD

**Issue by thisguychris** [neovim/neovim#10812]
- `nvim --version`: NVIM v0.3.8    
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Windows 10 Pro Version 1903
- Terminal name/version: Windows Terminal (Preview)
Version: 0.3.2171.0

- `$TERM`:
xterm-256color 
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behavior
I guess this is more of a bug in the [documentation](https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl). You no longer need to symlink `win32yank` manually, as installing nvim-qt would put win32yank.exe in your PATH, and neovim from WSL is able to pick it up.

I guess it has something to do with this PR as well:
https://github.com/neovim/neovim/pull/9263

![Alt text](https://monosnap.com/image/V3baVWhSnEbcpowRJOM408svlEhJDe)

### Expected behavior

NA

**Comment by justinmk** [comment]
>  installing nvim-qt would put win32yank.exe in your PATH, and neovim from WSL is able to pick it up.

How did you install nvim-qt? That makes the difference. Maybe you used e.g. chocolatey which updates your $PATH?

The wiki says "symlinked to a directory included in your $PATH". That implies that any user which merely unzips nvim-qt instead of "installing" it will still need to heed this. Right?

**Comment by thisguychris** [comment]
@justinmk I've installed it via chocolatey. But after browsing a handful of PRs in neovim, there was one in particular (I'm trying my best to find it, to no avail). That instead of checking win32yank in that path, it just checks nvim-qt since it automatically means there's win32yank bundled with it?

It was a PR that closes a bug (it was a deletion of literally one line), but had a very long explanation. It was where neovim is having trouble with symlinked win32yank?

**Comment by justinmk** [comment]
See previous reply.

**Comment by thisguychris** [comment]
@justinmk to add a bit of context here, I installed neovim via chocolately **before**, and win32yank can't be found, not until I did a symlink of win32yank.exe to win32yank, because neovim was looking for win32yank without the exe. Related to PR #9263

Now fast forward a couple of months after, with a clean install of windows 10 pro. **I found out that I didn't need to symlink anymore.**

What I'm trying to say is, regardless if win32yank.exe was added to your $PATH, you still have to symlink ***before*** because it won't work. But with the recent release of neovim, **you don't need to symlink anymore**.

Also "That implies that any user which merely unzips nvim-qt instead of "installing".  Neovim FAQ both points installing nvim-qt via Chocolatey and Scoop, how would you imply they are simply unzipping neovim? That makes no sense.

Anyway like I said, previously you had to symlink without the ".exe", now you don't have to symlink anymore. At the very list, maybe we can add some note that symlinking is required if win32yank.exe is not in your PATH? That way can be more clear instead of relying on hidden "implications"

Agree?

**Comment by justinmk** [comment]
It's a wiki, feel free to edit it :)
