### ISSUE TITLE
Netrw doesn't open symbolic links in 'tree style listing'

### ISSUE THREAD

**Issue by lokesh1197** [neovim/neovim#10835]
- `nvim --version`:
```
NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-lpKDO8/neovim-0.3.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-lpKDO8/neovim-0.3.8/build/config -I/build/neovim-lpKDO8/neovim-0.3.8/src -I/usr/include -I/build/neovim-lpKDO8/neovim-0.3.8/build/src/nvim/auto -I/build/neovim-lpKDO8/neovim-0.3.8/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
In vim netrw says permission denied
- Operating system/version: Ubuntu 18.04
- Terminal name/version:
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
1. Type `:Lexplore`
2. Hit `i` 3 times(i.e till tree style listing)
3. Go to a symlink and hit `Enter`

### Actual behaviour
When trying to open a symlink 'Netrw' creates a new file inside a new directory with the symlink's name.
### Expected behaviour
It should open the file in the directory where it actually exists

**Comment by justinmk** [comment]
We don't maintain netrw, it is simply a burden of tradition. Please report to https://github.com/vim/vim
