### ISSUE TITLE
Netrw: tree view + nested directories + redraws yields broken UI

### ISSUE THREAD

**Issue by tstirrat15** [neovim/neovim#10832]
- `nvim --version`:
```console
NVIM v0.4.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-eVymn0/neovim-0.4.0+ubuntu4+git201908192043-46cb856-6e51973=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-eVymn0/neovim-0.4.0+ubuntu4+git201908192043-46cb856-6e51973/build/config -I/build/neovim-eVymn0/neovim-0.4.0+ubuntu4+git201908192043-46cb856-6e51973/src -I/build/neovim-eVymn0/neovim-0.4.0+ubuntu4+git201908192043-46cb856-6e51973/.deps/usr/include -I/usr/include -I/build/neovim-eVymn0/neovim-0.4.0+ubuntu4+git201908192043-46cb856-6e51973/build/src/nvim/auto -I/build/neovim-eVymn0/neovim-0.4.0+ubuntu4+git201908192043-46cb856-6e51973/build/include
Compiled by buildd@lcy01-amd64-024
```

- `vim -u DEFAULTS` (version: ) behaves differently? Nope. [EDIT: vim behaves differently, and does not exhibit the same bug. I mistakenly ran `-u DEFAULTS` against nvim instead of vim.]
- Operating system/version: Ubuntu 19.04
- Terminal name/version: Gnome terminal 3.32.1-1ubuntu1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC . # open in a directory with nested structures
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
iii # move to tree mode
# open a directory down two levels
s # sort the buffer
```
Some screenshots. Prior to pressing "s":

![image](https://user-images.githubusercontent.com/2581423/63554937-534f0100-c4fc-11e9-87f3-80e4d1dee964.png)

After pressing "s":
![image](https://user-images.githubusercontent.com/2581423/63554957-61048680-c4fc-11e9-85e3-e81073c4c091.png)

Sorting isn't the only way to trigger this behavior. I've found that workspace switching and using Gnome's screenshot capture will also cause this.

I can work around it by selecting the top level file to close its tree and then reopen it (`doc` in this case), but this is cumbersome, and I have to do it for every level of the tree that was open when I triggered the redraw (most often happens when switching workspaces). I've also found that I can prevent it from happening by having another vim tab focused when I switch focus to that window (i.e. tab redraws don't cause any problems).

### Actual behaviour
See above.

### Expected behaviour
See above. I would expect the tree structure to remain intact across redraws. I don't know whether this behavior is a Neovim bug or a NetRW bug. I also am not sure if this is present in mainline Vim - I completely uninstalled it when I switched over to Neovim.

**Comment by tstirrat15** [comment]
Additional notes:

In the "after" behavior, NetRW starts treating everything that's white as a file, rather than identifying directories as directories. When you select `doc` in the view above, it opens `doc` in the same way that it would open a file, rather than the tree view behavior that I would expect.

Hitting "i" four times to cycle through all of the non-tree file views returns you to the "after" behavior.

**Comment by justinmk** [comment]
We don't maintain netrw, it's just something foisted on us by tradition :)

Please report to https://github.com/vim/vim/

**Comment by tstirrat15** [comment]
This bug isn't present in vim, though.

`/usr/bin/vim.basic .` followed by the above reproduction steps doesn't yield the same behavior. Is that still considered a netrw issue?

**Comment by justinmk** [comment]
> vim -u DEFAULTS (version: ) behaves differently? Nope.

**Comment by tstirrat15** [comment]
Good point. I've got `vim` aliased to `nvim`, so I executed `vim -u DEFAULTS` with `nvim` without thinking about it.

That said, running `/usr/bin/vim.basic -u DEFAULTS .` doesn't load netrw. Is there a way to load autoloads without loading any other configuration?

**Comment by justinmk** [comment]
I don't know. But now I see that isn't really a netrw issue but more like a redraw issue. Try a different terminal?

**Comment by tstirrat15** [comment]
I just tried it with a system terminal (ctrl + alt + f3 on my ubuntu machine) and observed the same behavior with `nvim -u NORC .`.

**Comment by tstirrat15** [comment]
In a recent build I started getting this error window at the bottom of the screen when I observe the bug:

```console
Error detected while processing function <SNR>77_LocalBrowseRefresh[57]..<SNR>77_NetrwRefreshTreeDict[13]..<SNR>77_NetrwRefreshTreeDict[14]..<SNR>77_NetrwGlob:
line    8:
E21: Cannot make changes, 'modifiable' is off
Press ENTER or type command to continue
```

Does that help at all? Are there additional diagnostics I can provide?

**Comment by justinmk** [comment]
@tstirrat15 I plan to push a catch-up PR with upstream Vim runtime, we're a few months behind.

**Comment by janlazo** [comment]
I've synced all applicable runtime files with upstream Vim. https://github.com/neovim/neovim/pull/14424

**Comment by tstirrat15** [comment]
Thank you! I haven't seen this issue pop up in a while now, so I'll go ahead and close this.
