### ISSUE TITLE
tohtml.vim use vts option which has not been merged into neovim

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#10831]
- `nvim --version`: NVIM v0.4.0-1713-g1852dfdf9
- `vim -u DEFAULTS` (version: ) behaves differently? yes

# Description
Commit 28a681 update the runtime file autoload/tohtml.vim,
now it takes into account the `vts` feature which has not been merged into neovim.
So, `:TOhtml` cause an error.

**Comment by justinmk** [comment]
Until the 'vartabstop' feature is ported (if ever), we should add a stub for it, such that:

- `:set vts=...` is an error
- reading the option (e.g. `:echo &vts`) always returns empty

**Comment by bfredl** [comment]
Should we revert the vim update for ToHtml.vim in the meanwhile for 0.4? Or patch away the `&vts` usage? We are recommending ToHtml as a solution when `:hardcopy` doesn't work, it would be great if it was working out of the box. This seems to be enough to make it working:

```diff
diff --git a/runtime/autoload/tohtml.vim b/runtime/autoload/tohtml.vim
index 2d874c690..77def5d85 100644
--- a/runtime/autoload/tohtml.vim
+++ b/runtime/autoload/tohtml.vim
@@ -779,7 +779,7 @@ func! tohtml#GetUserSettings() "{{{
     if user_settings.no_pre == 0
       call tohtml#GetOption(user_settings,
            \ 'expand_tabs',
-       \ &expandtab || &ts != 8 || &vts != '' || user_settings.number_lines ||
+       \ &expandtab || &ts != 8 || user_settings.number_lines ||
            \   (user_settings.dynamic_folds && !user_settings.no_foldcolumn))
     else
       let user_settings.expand_tabs = 1
diff --git a/runtime/syntax/2html.vim b/runtime/syntax/2html.vim
index 4a2d1d395..e91d1891e 100644
--- a/runtime/syntax/2html.vim
+++ b/runtime/syntax/2html.vim
@@ -1570,7 +1570,7 @@ while s:lnum <= s:end
        if s:settings.expand_tabs
          let s:offset = 0
          let s:idx = stridx(s:expandedtab, "\t")
-     let s:tablist = split(&vts,',')
+     let s:tablist = []  " split(&vts,',')
          if empty(s:tablist)
            let s:tablist = [ &ts ]
          endif

```
