### ISSUE TITLE
set COLORTERM='truecolor' in :terminal when using truecolor GUI/TUI

### ISSUE THREAD

**Issue by rgreenblatt** [neovim/neovim#10836]
See https://gist.github.com/XVilka/8346728#true-color-detection for what this does.

Current behavior is to unset COLORTERM.

**Comment by justinmk** [comment]
The title of this issue is confusing, and conflicts with the URL you linked:

> check for $COLORTERM containing either "truecolor" or "24bit"

I guess you want Nvim to set 'termguicolors' if  `COLORTERM=truecolor`.
 
Many terminals are truecolor-capable but users are not necessarily using truecolor-capable Vim colorschemes (i.e. the theme only sets `ctermfg`/`ctermbg` instead of `guifg`/`guibg`). Those users will then need to discover this and `:set notermguicolors`, which is just the reverse problem.

> Current behavior is to unset COLORTERM.

Nvim does not unset COLORTERM.

**Comment by bfredl** [comment]
From gitter, I think they meant that `:terminal` should set COLORTERM if `termguicolors` is already set by the user (or preferably any GUI with `ui->rgb` I think).

**Comment by jcorbin** [comment]
Seems to even strip `$COLORTERM`, say with:
```
let $COLORTERM="truecolor"
```

Any `:terminal` commands ends up with an unset `COLORTERM` env var.

**Comment by jcorbin** [comment]
Also: doesn't neovim's terminal emulator always support 24-bit color? So shouldn't `COLORTERM=truecolor` always be set over ran commands? Adaptation to the TUI's terminal is a separate affair (pretty sure tmux does similar translation to the client terminal, while always operating in a higher color space internally?)

**Comment by bfredl** [comment]
> Also: doesn't neovim's terminal emulator always support 24-bit color? 

Nvim always stores _both_ 24-bit values as well as palette indexes, internally. But if the enclosing terminal doesn't support truecolor, then passing through 256 bit colors from the inner program is better than asking it explicitly to use truecolor and then nvim trying to degrade it by some algorithm.

**Comment by badfilms** [comment]
> Nvim does not unset COLORTERM.

https://github.com/neovim/neovim/blob/master/src/nvim/os/pty_process_unix.c#L163

Relevant discussion https://github.com/sharkdp/bat/issues/634#issuecomment-524453561.

**Comment by cumulotimbus** [comment]
> Any `:terminal` commands ends up with an unset `COLORTERM` env var.

Oh geez. It seems like we should at least be able to set it manually from within neovim. Is the workaround to use shell config/logic to set it after the terminal starts a shell?

This borks my shell theme, bat, and probably numerous other tools that rely on `COLORTERM` being set. 😭

**Comment by ThomasFeher** [comment]
```patch
diff --git a/src/nvim/os/pty_process_unix.c b/src/nvim/os/pty_process_unix.c
index f0bc13783..26569d6fc 100644
--- a/src/nvim/os/pty_process_unix.c
+++ b/src/nvim/os/pty_process_unix.c
@@ -160,7 +160,6 @@ static void init_child(PtyProcess *ptyproc)
   os_unsetenv("COLUMNS");
   os_unsetenv("LINES");
   os_unsetenv("TERMCAP");
-  os_unsetenv("COLORTERM");
   os_unsetenv("COLORFGBG");

   signal(SIGCHLD, SIG_DFL);
```

That fixes the issue for me, by not removing `COLORTERM` in neovim's terminal.

**Comment by btwiusegentoo** [comment]
> ```diff
> diff --git a/src/nvim/os/pty_process_unix.c b/src/nvim/os/pty_process_unix.c
> index f0bc13783..26569d6fc 100644
> --- a/src/nvim/os/pty_process_unix.c
> +++ b/src/nvim/os/pty_process_unix.c
> @@ -160,7 +160,6 @@ static void init_child(PtyProcess *ptyproc)
>    os_unsetenv("COLUMNS");
>    os_unsetenv("LINES");
>    os_unsetenv("TERMCAP");
> -  os_unsetenv("COLORTERM");
>    os_unsetenv("COLORFGBG");
> 
>    signal(SIGCHLD, SIG_DFL);
> ```
> 
> That fixes the issue for me, by not removing `COLORTERM` in neovim's terminal.

Thanks! applying this as patch totally fixed for me. Finally I can use neovim terminal.
Maybe I will have a local overlay that applies this patch until it fixes.
