### ISSUE TITLE
`E315: ml_get: invalid lnum: 3`

### ISSUE THREAD

**Issue by alexgenco** [neovim/neovim#10847]
Found this while investigating these build failures: https://travis-ci.org/neovim/neovim-ruby/builds/576498083

- `nvim --version`: `NVIM v0.4.0-1805-gc8fc285db`
- `vim -u DEFAULTS` (version: `8.1.1900`) behaves differently? No (should I open an issue there?)
- Operating system/version: macOS 10.14.6
- Terminal name/version: iTerm2 3.3.2beta1
- `$TERM`: `screen-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:split | call append(0, ["foo"]) | split
```

### Actual behaviour

Writes error `E315: ml_get: invalid lnum: 3`, but splits are in expected state after hitting `ENTER`.

### Expected behaviour

No error message.

**Comment by justinmk** [comment]
> `vim -u DEFAULTS` (version: `8.1.1900`) behaves differently? No (should I open an issue there?)

Sure, please link to it from here.

**Comment by alexgenco** [comment]
Will do. Should also add I ran a bisect and it seems to have been introduced with 9358979d096a6bfde371bbca5c77f8d45a4de253.

**Comment by alexgenco** [comment]
Just commented on an existing issue: https://github.com/vim/vim/issues/1737#issuecomment-524678865

**Comment by mhinz** [comment]
👉 https://github.com/neovim/neovim/pull/10866
