### ISSUE TITLE
Spell checking not working for specific file (.tex)

### ISSUE THREAD

**Issue by dasteihn** [neovim/neovim#10846]
- `nvim --version`: 0.1.7
- `vim -u DEFAULTS` (version: ) No.
- Operating system/version: Debian Stretch
- Terminal name/version: terminator 1.90, GNOME Terminal 3.22.2

### Steps to reproduce using `nvim -u NORC`
1. Open the attached Tex-file
2. `:setlocal spell spelllang=en_us`
3. Observe that for this file spell checking seems not to work. No matter what terminal, computer restart, `:set nospell`...

### Actual behaviour
No spell checking, no error report. Interestingly, nvim asks if you want to download the spellcheck-file if you type a wrong language, like `:setlocal spell spelllang=fooo`. If you refuse to downoload it, nvim warns about not being able to find the file. You get this warning as well if you type the command correctly a second time: `:setlocal spell spelllang=en_us`.

Awkwardly, the only file where this problem occurs is the one attached, a sub tex file from a report I am working on. More awkwardly, everything works when I rename the `.tex` to `.txt`; as I did to be able to upload it here.
[gnah.txt](https://github.com/neovim/neovim/files/3538454/gnah.txt)

### Expected behaviour
Activate spell checking as for any other file.

**Comment by bfredl** [comment]
`0.1.7` is very old, maybe at least try latest stable release 0.3.8. We have pre-compiled binaries if pulling it in via your distro is difficult.

**Comment by blueyed** [comment]
> * `vim -u DEFAULTS` (version: ) No.

Also would be interesting to know if Vim behaves the same, and which version of Vim that is.

**Comment by blueyed** [comment]
It works for me using `nvim -u NONE -c 'set spell' gnah.tex`, but not `nvim -c 'set spell' gnah.tex`.
Same for Vim.

The following from my config triggers it already:
```vim
  call plug#begin('~/.vim/plugged')
  call plug#end()
```

@dasteihn 
Do you use vim-plug also, or another plugin manager?

Can you try it based on a minimal vimrc/init.vim and see what causes it?

**Comment by justinmk** [comment]
No followup.

**Comment by lyu** [comment]
I am facing the same issue so please allow me to chime in.

- `nvim --version`: 0.3.8 (from Archlinux repo)
- `vim -u DEFAULTS` (version: 8.1.1906) behaves differently? No (Same issue)
- Operating system/version: Archlinux x86_64
- Terminal name/version: tilix 1.9.1
- `$TERM`: xterm-256color

### Steps to reproduce

First, I have removed `~/.config/nvim` and `~/.local/share/nvim`, and all the vim equivalence. The pynvim plugin is also removed from the system. Using the tex file provided by the OP.

```
nvim -u NORC gnah.tex
```

No spellchecking no matter what I do (`:set spell`, `setlocal spell spelllang=en_us`, ...)

[https://github.com/vim/vim/issues/1701](https://github.com/vim/vim/issues/1701) seems to be the bug report for vim. Adding `\section{Bar}` to the middle of the tex file enables spellchecking for everything after it.
