### ISSUE TITLE
Weird behavior with cgn

### ISSUE THREAD

**Issue by avalonv** [neovim/neovim#10859]
- `nvim --version`: v0.3.8
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: linux
- Terminal name/version: kitty
- `$TERM`: xterm-kitty

Write this into a file:

```
1 # head
3 part one
4
5 part two
6
7 part three
8
9 part four
```

Place cursor on line 1
Type `/part`
Type `cgn<Right><bs>`
Repeat that action `.`

##### Expected behavior

Moving the cursor and backspacing while in insert mode causes subsequent repeats to move to the next line containing "part" and backspace.

##### Actual behavior:

Moving the cursor and backspacing while in insert mode causes repeats to backspace every other character, without moving to the next match. This also happens if you insert a character instead of a backspace.

Note that the order of these actions in insert mode is what matters, not whether the cursor was moved in insert mode: moving then backspacing causes repeats to do one thing - backspacing then moving makes repeats do another (expected behavior).

The same thing happens in vim by the way, this is not specific to neovim.

I don't know if this is a bug or intentional behavior, obviously it's a minor thing, but it feels unintuitive.

**Comment by justinmk** [comment]
cc @chrisbra

**Comment by chrisbra** [comment]
Cursor Key movements break repeats. That is not a bug and even documented. You might want to try to use `Ctrl-G U` See `:h i_CTRL-G_U`
