### ISSUE TITLE
Hello, does neovim support show only one status line at bottom for all windows?

### ISSUE THREAD

**Issue by fgheng** [neovim/neovim#10861]
hello every one, I want to know whether neovim support all windows using one status line which always stay at bottom of neovim, rather than every window has a status line. thank you very much

**Comment by justinmk** [comment]
:help 'laststatus'

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by fgheng** [comment]
ok, thank you very much
