### ISSUE TITLE
pasting clipboard contents in insert and normal modes does not work

### ISSUE THREAD

**Issue by e-kwsm** [neovim/neovim#10872]
(Moved from #10865)

Since  #4448, <kbd>Shift</kbd> + <kbd>Ins</kbd> in insert mode does not work (like #10223), while <kbd>"</kbd><kbd>+</kbd>/<kbd>*</kbd><kbd>p</kbd> in normal mode works.

- `nvim --version`: NVIM v0.4.0-1856-g82d52b229df7
Build type: RelWithDebInfo
LuaJIT 2.0.5
- `vim -u DEFAULTS` (version: 8.1.1401) behaves differently? yes (`+` and `*` registers are unablable though)
- Operating system/version: Debian 10.0
- Terminal name/version: GNOME Terminal 3.30.2 using VTE 0.54.2 +GNUTLS
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

Copy the following two lines
```
a

```

and then `nvim -u NORC`
<kbd>"</kbd><kbd>+</kbd><kbd>P</kbd>
<kbd>"</kbd><kbd>*</kbd><kbd>P</kbd>
<kbd>O</kbd> <kbd>Shift</kbd>+<kbd>Ins</kbd>

### Actual behaviour
```
a^M^M
a

a


```

`od -x` gives
```
0000000 0d61 0a0d 0a61 610a 0a0a 000a
0000013
```

### Expected behaviour

```
a

a

a


```

**Comment by e-kwsm** [comment]
Checkhealth results are (`-u NORC`; python providers etc are truncated)
```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5402'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel
```

Middle click in insert mode works only when `:set mouse=i`.

**Comment by blueyed** [comment]
Confirmed in urxvt, but works in kitty (and tmux with kitty).

**Comment by blueyed** [comment]
Might be related to bracketed paste not working there also from normal mode (https://github.com/neovim/neovim/issues/8395) - @e-kwsm is that working for you, or is it also handled as commands, with extra `^M` there then?

**Comment by bfredl** [comment]
`"+p`/`"*p` in normal mode more reliably corresponds to `<c-r>+`/`<c-r>*` to insert mode. I suppose some terminals handle Shift+Insert themselves, so the "paste" handler is used, while others forward it to nvim, causing the same behavior as `<c-r>*` (i e use xclip etc).

**Comment by e-kwsm** [comment]
@blueyed In normal mode,

| key | works (no `^M`)? |
|---|---|
| <kbd>Shift</kbd>+<kbd>Ins</kbd> | N |
| middle click | N |
| middle click, `:set mouse=n` | Y |

**Comment by justinmk** [comment]
I can reproduce with Terminal.app. At first I made a patch for CRLF, but it turns out terminals are sending CR only. WIP at https://github.com/neovim/neovim/pull/10877 , I need to modify it to handle CR without CRLF.
