### ISSUE TITLE
[Feature request] Support netbsd (pkgsrc) installs

### ISSUE THREAD

**Issue by krishnakumarg1984** [neovim/neovim#10871]
May I please request packaging neovim 0.4 for netbsd. The `pkgsrc` framework is so flexible and I believe that it can build neovim from source quite easily.

**Comment by justinmk** [comment]
We depend on users of each OS to maintain packages for their OS. Please note it in https://github.com/neovim/neovim/wiki/Installing-Neovim#bsd if it becomes available.
