### ISSUE TITLE
yank produces batatom?

### ISSUE THREAD

**Issue by jpmorris** [neovim/neovim#10882]
Please excuse my ignorance on X selections. I am getting a bad atom name?/parameter?  when I copy from Neovim

Checked FAQ

- `nvim --version`: 

NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-_mzR4z/neovim-0.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-_mzR4z/neovim-0.2.2/build/config -I/build/neovim-_mzR4z/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-_mzR4z/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-_mzR4z/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

- `vim -u DEFAULTS` (version: ) behaves differently? **Cannot read from "DEFAULTS"**
- Operating system/version: ubuntu 28.04
- Terminal name/version: terminator 1.91
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC <anyfile>
("*yy a line, in separate terminal:)
xclip -selection primary -o (shows copy)
xclip -selection primary -o -t TARGETS
```

### Actual behaviour
```
TARGETS
TIMESTAMP
MULTIPLE
TARGETS
DELETE
INCR
TEXT
UTF8_STRING
STRING
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  17 (X_GetAtomName)
  Atom id in failed request:  0x0
  Serial number of failed request:  23
  Current serial number in output stream:  23
```
And cant paste to jetbrains IDE becuase it searches for valid atom name

```
2019-08-29 12:24:35,754 [156170236]   INFO - tor.actions.PasteFromX11Action - Failed to retrieve atom name.
java.lang.NullPointerException: Failed to retrieve atom name.

```

### Expected behaviour
xclip -o -t TARGETS should show all valid atom names without error and paste to jetbrains IDE should work without issue as occurs in all other applications.

**Comment by blueyed** [comment]
What is "(shows copy)" supposed to do with `xclip -selection primary -o (shows copy)`?

**Comment by blueyed** [comment]
> NVIM v0.2.2

It works for me with Neovim master - please try at least the latest release.

But it might be more an issue of xclip. I am using 0.13-2 (Arch Linux) there.

**Comment by jpmorris** [comment]
New version worked. Sorry should have done that first. Sorry for the bother, thanks!
