### ISSUE TITLE
:cexpr do not jump to the first error

### ISSUE THREAD

**Issue by liquidz** [neovim/neovim#10895]
- `nvim --version`: v0.4.0-1879-g6024fb526
- `vim -u DEFAULTS` (version: 8.1.1949) behaves differently? yes
- Operating system/version: macOS 10.13.6
- Terminal name/version: iTerm2/3.2.9
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
:cexpr ['foo.txt:1:err', 'bar.txt:2:err']
```

### Actual behaviour

* vim or nvim 0.3.8 jump to the first error.
* nvim 0.4.0 do not jump to the first error.
  * But `:copen` show 2 error correctly.

### Expected behaviour

* Jump to the first error(foo.txt).
  * https://neovim.io/doc/user/quickfix.html#:cexpr

**Comment by mhinz** [comment]
This patch needs to be backported (and potentially prior patches this one is based on): https://github.com/vim/vim/commit/531b9a3a638cb1147db4f096bfbcb14d2ae32b04
