### ISSUE TITLE
Number section is jumping which external plugins.

### ISSUE THREAD

**Issue by wh1le** [neovim/neovim#10900]
Hello, thank you for the best code editing tool! 

I have one concern. I use plugins like [Ale](https://github.com/dense-analysis/ale), [LanguageClient](https://github.com/autozimu/LanguageClient-neovim), etc. Each time it detects warning in my code it prepends the `✖` symbol to the numbers section like here:

<img width="491" alt="Screenshot 2019-08-31 at 15 36 02" src="https://user-images.githubusercontent.com/14846508/64065400-11614180-cc05-11e9-8422-dba9c2b96c0b.png">

And if an error is fixed the symbol is removed

<img width="412" alt="Screenshot 2019-08-31 at 15 37 34" src="https://user-images.githubusercontent.com/14846508/64065416-54231980-cc05-11e9-9dd4-6d9f2e9d5ad4.png">

As you notice each time it prepends this symbol the code is "jumping". For everyday routine, it's become a little bit annoying. Is there any solution to make the width of numbers bar static? 
Best!

**Comment by mhinz** [comment]
See `:h 'signcolumn'`. You probably want `:set signcolumn=yes:2`.

**Comment by wh1le** [comment]
@mhinz Thanks for the clarification!
