### ISSUE TITLE
The print/ directory

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1091]
_[migrated from the old `vimscript` repo]_

---

The `print/` directory hasn't been touched in 10 years: https://github.com/b4winckler/vim/tree/master/runtime/print

They are used for postscript encoding, see `:help postscript-print-encoding`. Vim has never really supported printing, but it supported export to postscript as a workaround. 

neovim obviates this if the GUI layer will provide native print support (I don't know if this is a fair assumption).

I recall seeing people [complain](https://www.sublimetext.com/forum/viewtopic.php?f=2&t=14638) that Sublime Text didn't print. It's a weird world.

I think a workaround might be to export syntax-highlighted files to HTML:
- http://stackoverflow.com/questions/4112510/any-way-to-copy-a-syntax-coloured-file-in-vim-as-html
- http://www.vim.org/scripts/script.php?script_id=3113

ZyX-I obviously has experience with this, so maybe he can comment on whether this would be a sufficient workaround, and if so would it be appropriate to remove these files.

**Comment by mhinz** [comment]
@justinmk

Would you be opposed to closing this? I don't see us ever acting on this and as far as I know no one ever complained about it. :)

**Comment by dundargoc** [comment]
`print` directory and hardcopy support has been removed. I believe this is solved. How to move forward with printing is discussed [here](https://github.com/neovim/neovim/issues/21629).

**Comment by justinmk** [comment]
We rewrote `:TOhtml` and it works well, so printing is simply a matter of opening the resulting HTML file in a web browser and printing from there. 

But yes, https://github.com/neovim/neovim/issues/21629 would be the final step to addressing this.
