### ISSUE TITLE
missing cmdline clear with `set display-=msgsep`

### ISSUE THREAD

**Issue by h-michael** [neovim/neovim#10912]
- `nvim --version`:

```sh
~/g/g/n/neovim> nvim --version
NVIM v0.4.0-1911-gb10d70321
Build type: Release
```

- OS: Ubuntu
- $TERM: screen-256color (use tmux)

minimal vimrc

```
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
call plug#end()

set termguicolors
set display=lastline
```

### Actual behaviour
If I use tmux and use above vim config and I open neovim, the command line background color is red.
<img width="892" alt="スクリーンショット 2019-09-02 13 40 36" src="https://user-images.githubusercontent.com/4556097/64090714-8fe5ec80-cd87-11e9-8482-730fbffeff4d.png">

### Expected behaviour
I reverted 9df3a67 commit, command line background color is black.

<img width="888" alt="スクリーンショット 2019-09-02 13 43 21" src="https://user-images.githubusercontent.com/4556097/64090729-a724da00-cd87-11e9-99b9-d87f5d73ebe5.png">

cc: @bfredl 
Is this specification changed or bug?

**Comment by blueyed** [comment]
> minimal vimrc

Can you provide a more minimal example, without vim-airline?
But maybe @bfredl already knows what's up.

**Comment by h-michael** [comment]
Sorry, this occured when I use my vimrc.
So, I bisect my vimrc at first.
I'll try to make more simle pattern latter.

**Comment by bfredl** [comment]
What does `:hi MsgArea` show? If airline is already using that name we will need to change it.

**Comment by h-michael** [comment]
This is command result.
<img width="345" alt="スクリーンショット 2019-09-02 15 39 00" src="https://user-images.githubusercontent.com/4556097/64094786-ce83a300-cd97-11e9-8f5a-c5034018c22b.png">

**Comment by chrisbra** [comment]
> What does :hi MsgArea show? If airline is already using that name we will need to change it.

It is not.

**Comment by bfredl** [comment]
@h-michael So I suppose the cmdline then only temporarily becomes red in certain situations. Is there a consistent pattern, like after every resize, or on `CTRL-L` or something?

BTW if the intention was to remove `msgsep` this can be written directly as `set display-=msgsep`.

**Comment by bfredl** [comment]
@h-michael would you mind try #10913 ?

**Comment by h-michael** [comment]
@bfredl 

> So I suppose the cmdline then only temporarily becomes red in certain situations. Is there a consistent pattern, like after every resize, or on CTRL-L or something?

I try to resize and redraw, but this issue isn't happened.

> would you mind try #10913 ?

This PR fixes  my issue :)
