### ISSUE TITLE
"-- More --" prompt cannot be quit using "q" (:echon)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10923]
Given the command:
```vim
:echon join(map(range(0, &lines*3), 'v:val'), "\n")
```

Running `nvim -u NORC` and executing it will display a screen full of numbers, and a "-- More --" prompt.

The more prompt cannot be quit anymore after 67bac681e ("ex_echo: reuse code from message.c to show arg to user"): pressing "q" will display the next page, just like "<Enter>".
Before 67bac681e it would quit the pager (as it happens in Vim).

/cc @bfredl @AlexandreDubray

**Comment by blueyed** [comment]
It works when using `:echo` in a loop:
```vim
function! F()
  let lines = []
  for i in range(0, &lines * 3)
    echo string(i)
  endfor
endfunction
```

I.e. it looks like the processing of `:echon` does not check for `q` anymore.

**Comment by bfredl** [comment]
The old code checked `got_int`, this appears to be lost in the refactored code.

**Comment by blueyed** [comment]
This fixes it:
```diff
 src/nvim/message.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git i/src/nvim/message.c w/src/nvim/message.c
index ac731210d..e21981ec9 100644
--- i/src/nvim/message.c
+++ w/src/nvim/message.c
@@ -227,7 +227,7 @@ void msg_multiline_attr(const char *s, int attr)
 {
   const char *next_spec = s;
 
-  while (next_spec != NULL) {
+  while (next_spec != NULL && !got_int) {
     next_spec = strpbrk(s, "\t\n\r");
 
     if (next_spec != NULL) {
```

Will create a PR with it.
