### ISSUE TITLE
Make jobstop() fail silently (but return a status)

### ISSUE THREAD

**Issue by gravndal** [neovim/neovim#10943]
~~Bisected to https://github.com/neovim/neovim/commit/2d4a37ebab354afb94dfe600b302d8a2b1f2d889~~

~~This is already known going by the comments on that commit, but I didn't find any open or closed issues.~~

### Steps to reproduce:
~~1. `yes abcdefg | pv -Sl -s 5000 > something`
2. run nvim with nothing but the default runtime + vim-grepper
3. `:GrepperGrep abcd something` or `:GrepperRg abcd something`~~

~~See also: https://github.com/mhinz/vim-grepper/issues/212~~

**Comment by blueyed** [comment]
Re-opening as per discussion in https://github.com/neovim/neovim/commit/2d4a37ebab354afb94dfe600b302d8a2b1f2d889#commitcomment-34164761 (still no pasted comments though ;)).

**Comment by justinmk** [comment]
Why should `jobstop()` cause an error on invalid job? It is inherently racy: a job may become invalid while `jobstop()` is being executed.

**Comment by mhinz** [comment]
@blueyed 

Oh, hmm. I somehow never saw that comment from July 3th. Well, one can't reproduce it with vim-grepper anymore, so the first post and title should be adjusted when we keep this open.

**Comment by justinmk** [comment]
> Why should `jobstop()` cause an error on invalid job? It is inherently racy: a job may become invalid while `jobstop()` is being executed. We could return a status code from `jobstop()` instead.

So is anyone opposed to this?

**Comment by astroncoda** [comment]
i am new to github   ...where is the code where we have to resolve the issue?

**Comment by justinmk** [comment]
`f_jobstart` in `eval.c` would be the place to start.

**Comment by y2s82** [comment]
@desterfhy
Are you still working on this?  I was wondering if I can take a crack at it.

**Comment by blueyed** [comment]
@y2s82 
Note that there's also https://github.com/neovim/neovim/pull/10984 already.

**Comment by y2s82** [comment]
> @y2s82
> Note that there's also #10984 already.

yeah, I was looking at that, but realized it hasn't been worked on for more than a month.  so I thought to ask, just in case.

**Comment by Billy4195** [comment]
This issue could be closed, or are there still TODOs?
