### ISSUE TITLE
The 

### ISSUE THREAD

**Issue by wasim1772** [neovim/neovim#10968]
- `nvim --version`:
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by wasim1772** [comment]
#10000

**Comment by wasim1772** [comment]
#9254

**Comment by wasim1772** [comment]
#10924

**Comment by wasim1772** [comment]
#10966 @

**Comment by wasim1772** [comment]
#10959

**Comment by bfredl** [comment]
just write in #10959 directly if you have info to add.
