### ISSUE TITLE
CheckHealth should not throw error when `TERM = xterm-256color-italic` is set in tmux config

### ISSUE THREAD

**Issue by eprislac** [neovim/neovim#10979]
- `nvim --version`: v0.3.8
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: MacOS Mojave
- Terminal name/version: KiTTY, iTerm2
- `$TERM`: `xterm-256color-italic`

### Steps to reproduce:
Run `:CheckHealth` while in tmux with TERM set to `xterm-256color-italic`

### Actual behaviour
```
## tmux
  - OK: escape-time: 10ms
  - INFO: $TERM: xterm-256color-italic
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ
```

### Expected behaviour
`xterm-256color-italic` is a variant of `xterm-256color` and should not throw an error saying that colors might look wrong, as it uses the exact same colors as `xterm-256color`

### Notes
https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/

**Comment by justinmk** [comment]
It is wrong, because your terminal is tmux.

The "italic" part is not the problem. Read the error message carefully.
