### ISSUE TITLE
Not sending buffer change notification when modify files outside of vim 

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#10987]
- `nvim --version`: v0.4.0-1459-g3cf4b0d5e
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: MacOS
- Terminal name/version: iTerm2

### Steps to reproduce using `nvim -u NORC`

Create `$XDG_CONFIG_HOME/nvim/rplugin/node/notify.js` with content:

``` js
function bindBuffer(buffer) {
  let cb = (buf, tick, firstline, lastline, linedata, more) => {
    console.error('----------')
    console.error('result:', tick, firstline, lastline, linedata, more)
  }
  buffer.listen('lines', cb)
  buffer.listen('detach', buf => {
    console.error('detached')
  })
}

async function setup(nvim) {
  let buffers = await nvim.buffers
  for (let buf of buffers) {
    let valid = await buf.valid
    console.error('valid ' + valid)
    bindBuffer(buf)
  }
}

module.exports = (plugin) => {
  let {nvim} = plugin
  setup(nvim)
}
```

```
npm install -g neovim
mkdir foo && cd foo && git init
echo "test" > bar.js
nvim -u NORC bar.js
# Run command `set autoread`.
# Use `dd` to delete first lint then use `git stash` to revert the change.
# checkout log of node-client.
```

### Actual behaviour

No buffer change event send to remote host when buffer is reloaded.

### Expected behaviour

Send buffer change event.

**Comment by justinmk** [comment]
Did you try `:checktime`? Are you sure the buffer is reloaded? This sounds like a duplicate of https://github.com/neovim/neovim/issues/1380

**Comment by justinmk** [comment]
ping @chemzqm

**Comment by chemzqm** [comment]
Nothing happens after `:checktime`, it's duplicate of #8648
