### ISSUE TITLE
Floating windows: completeopt=popup (completion preview)

### ISSUE THREAD

**Issue by clason** [neovim/neovim#10996]
(I haven't found any issue about it, so I thought I'd put it up for the sake of completeness.)

In patch 8.1.1880, vim introduced `completeopt=popup`, which shows the completion documentation in a vim popup instead of a preview buffer. A similar functionality for neovim is implemented in https://github.com/ncm2/float-preview.nvim, but it would be nice to have this builtin (ideally, toggled by the same option, although it's admittedly not the best nomenclature for neovim).

**Comment by kalvinpearce** [comment]
I noticed this has been flagged for 0.5 milestone, does anyone know if it's likely to make it in for 0.5? 🙏🤞

**Comment by janlazo** [comment]
@kalvinpearce  No :disappointed:

**Comment by Shougo** [comment]
@kalvinpearce You can do it if it is really needed.
