### ISSUE TITLE
TUI paste in :terminal mode gives error (but works)

### ISSUE THREAD

**Issue by alok** [neovim/neovim#10992]
- `nvim --version`: NVIM v0.4.0-2042-g7bb858c39
- Terminal name/version: kitty
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Copy some text with cmd-c, then try to paste into a terminal buffer (in insert mode) with cmd-v.

### Actual behaviour

The error `paste: Error executing lua: vim.lua:198: Vim(normal):Can't re-enter normal mode from terminal mode` flashes.

### Expected behaviour

No error msg.

**Comment by bfredl** [comment]
@alok does this patch work for you?

```diff
diff --git a/src/nvim/lua/vim.lua b/src/nvim/lua/vim.lua
index f8e52d31c..98519f784 100644
--- a/src/nvim/lua/vim.lua
+++ b/src/nvim/lua/vim.lua
@@ -196,7 +196,9 @@ paste = (function()
       if phase < 2 and mode ~= 'i' and mode ~= 'R' then
         vim.api.nvim_put(lines, 'c', true, true)
         -- XXX: Normal-mode: workaround bad cursor-placement after first chunk.-        vim.api.nvim_command('normal! a')
+        if mode ~= 't' then
+          vim.api.nvim_command('normal! a')
+        end
       else
         vim.api.nvim_put(lines, 'c', false, true)
       end
```

**Comment by alok** [comment]
It works.
