### ISSUE TITLE
Can't insert keycodes using python RPC nvim_feedkeys

### ISSUE THREAD

**Issue by rayhogenson** [neovim/neovim#11000]
I am trying to insert an escape key using the pynvim RPC package, using the feedkeys function. Is this possible? [The documentation](https://neovim.io/doc/user/api.html) is rather terse, and I can't figure out for the life of me what the escape_csi parameter does...

I have tried the following commands:
```python
>>> nvim.feedkeys('<Esc>')
>>> nvim.feedkeys('<Esc>', 't')
>>> nvim.feedkeys(r'\<Esc>')
>>> nvim.feedkeys('<Esc>', 't', escape_csi=False)
>>> nvim.feedkeys(r'\<Esc>', 't', escape_csi=False)
```

It is possible to insert keys using keycodes with the nvim_input RPC.

Thanks for your help

EDIT: Well, it's possible to type an escape using the undocumented flag 'x', but my question may as well apply to inserting &lt;CR&gt; or any other keycode

**Comment by justinmk** [comment]
Full docs are in `:help api`. If you really want to use feedkeys() it follows the same quirks as the VimL `:help feedkeys()` function. 

You might have an easier time with `nvim_input()` instead.

    nvim.feedkeys('<Esc>')
