### ISSUE TITLE
concealcursor=v cause selection mess up

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#11024]
- `nvim --version`: NVIM v0.4.0-2066-g3855204f5
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: macos 10.14
- Terminal name/version: alacritty
- `$TERM`: xterm-256color

### Steps to reproduce
1. `nvim -u NORC`
2. `:h`
3. `:set concealcursor=ncv`
4. press `V` and hold on `j`, then hold on `k`
5. tui selection mess up
see [video](https://asciinema.org/a/WSl8qCdh7L1945hezhH5Otcfu)

**Comment by justinmk** [comment]
cannot reproduce with db550ac99565 in kitty terminal + tmux.

Can you try with `TERM=alacritty-256color` or `TERM=ansi`

**Comment by zgpio** [comment]
> cannot reproduce with [db550ac](https://github.com/neovim/neovim/commit/db550ac995652133fed0d16964f2cef2c49dbc82) in kitty terminal + tmux.
> 

I can reproduce with `NVIM v0.4.0-2083-g8c88d98df` in macos bultin terminal with `TERM=xterm-256color`

**Comment by zgpio** [comment]
BTW, what is the connection between `commit id` and `NVIM v0.4.0-2083-g8c88d98df`?

**Comment by blueyed** [comment]
> BTW, what is the connection between `commit id` and `NVIM v0.4.0-2083-g8c88d98df`?

With `v0.4.0-2083-g8c88d98df` the commit is `8c88d98df` (just remove the "g" prefix).

**Comment by blueyed** [comment]
Can you try https://github.com/neovim/neovim/pull/11101, please?

If not it might be useful to know if `set cursorline` fixes it.

**Comment by blueyed** [comment]
Can reproduce it in urxvt, #11101 does not fix it.

**Comment by blueyed** [comment]
Caused by 23c71d5182a5e717c3a1852d9d3c90e81b4735fd (https://github.com/neovim/neovim/pull/9492), which is also related to #11101.

**Comment by blueyed** [comment]
Fix included in #11101.

**Comment by bfredl** [comment]
I cannot reproduce in xterm nor in pangoterm. @blueyed do you have a reproduce which works even in the test suite (i e doesn't depend on the terminal)?

**Comment by blueyed** [comment]
@bfredl see https://github.com/neovim/neovim/pull/11101#discussion_r328984300 for instructions.
Might be related to your keyrate (I have `xset r rate 200 30`, but also happens with `xset r rate 200 10` (not with `xset r rate 200 5` though anymore)).
https://github.com/neovim/neovim/pull/11101#discussion_r328984300
