### ISSUE TITLE
Fix tmux warning on neovim checkhealth

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/neovim#11030]
When running :checkhealth, we get this warning
```
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

```

How can I resolve it?

**Comment by justinmk** [comment]
Either don't set 'tgc' , or follow the instructions in the message.

Tracker is not for usage questions.

**Comment by Maltimore** [comment]
Shouldn't it be

```
set-option -sa terminal-overrides ',XXX:Tc'
```
instead of

```
set-option -sa terminal-overrides ',XXX:RGB'
```


for newer versions of tmux? The instructions didn't work for me with "RGB".

**Comment by justinmk** [comment]
@Maltimore are you suggesting that the checkhealth message should be swapped?

**Comment by Maltimore** [comment]
Yes that was my suggestion.
However, it was a good point to ask for ```tmux -V```. I thought version 2.6 was pretty recent (included in ubuntu 18.04). That was the verison I tested this with.
I compiled a very recent version of tmux, 3.0a and with that using "RGB" works.

So ignore my above comment then.

**Comment by nfischer** [comment]
"For older tmux versions" is a bit vague. Older than which version?

Even better, could neovim run `tmux -V` and tell me which setting is appropriate for my version?

**Comment by nabezokodaikon** [comment]
This has been resolved.
By the way, the version of tmux is 3.0a.

**Comment by nfischer** [comment]
> This has been resolved.

Has it? The code in master branch has the same error message. Should I look at a different branch?

https://github.com/neovim/neovim/blob/96be8a2c4d63faadb97c346abb336511a60ac89a/runtime/autoload/health/nvim.vim#L185-L188

> By the way, the version of tmux is 3.0a.

Thanks! This is helpful for me (I maintain my dotfiles across different environments with different tmux versions).

**Comment by rivertam** [comment]
On Alacritty, I found this message confusing because `$TERM` outside of tmux seems to be overridden. I used `gnome-terminal` instead of `echo $TERM`, which is `xterm-256color` and the error message went away. That said, I don't know if this actually changed anything about the colors.
