### ISSUE TITLE
NeoVim 0.4 unhelpful missing font error message

### ISSUE THREAD

**Issue by the42** [neovim/neovim#11037]
- `nvim --version`: 0.4.2
- Operating system/version: Windows 10 64 bit

### Actual behaviour
When starting Neovim QT a rather unhelpful "mssing font:" error is displayed in the command line. The Gui stalls for about a second (doesn't redraw), but NeoVim behaves correctly afterwards.

### Expected behaviour
Show detailed information about missing font (NB: Neovim pre-builts didn't reveal this behaviour, I didn't delete fonts, so maybe it's a regression?

**Comment by khalidchawtany** [comment]
If you are using neovim-qt then look at this issue https://github.com/equalsraf/neovim-qt/issues/585

**Comment by blueyed** [comment]
Closing in favor of https://github.com/equalsraf/neovim-qt/issues/585.
