### ISSUE TITLE
provider: clipboard: missing required variable g:loaded_clipboard_provider

### ISSUE THREAD

**Issue by nathanielescribano** [neovim/neovim#11033]
- `nvim --version`: 
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: 10.14.4
- Terminal name/version:
- `$TERM`: rxvt

### Actual behaviour

Running ```:checkhealth```  returns

```

 22   - ERROR: Failed to run healthcheck for "provider" plugin. Exception:
 23     function health#check[21]..health#provider#check[1]..<SNR>142_check_clipboard, line 10
 24     Vim(let):E117: Unknown function: provider#clipboard#Executable

 ```

### Expected behaviour
Have no checkhealth error and be able to use ```set clipboard+=unnamedplus``` to copy to clipboard

This wasn't a problem when i was on 0.3.8. 

Any idea what thtis issue could be?

**Comment by alerque** [comment]
I just updated to Neovim 0.4.2 (Archlinux) and was greeted with an absolutely unusable `nvim`. I couldn't even edit my own `init.rc` file to comment out the cliboard config line, I had to use `vi`! In retrospect (and for the benefit of anybody else hitting this issue) I could have used `nvim -u /dev/null init.rc`.

The "fix" for now to get a working editor again is to comment out the line `set clipboard+=unnamedplus`.

**Comment by blueyed** [comment]
@alerque 
What's your error?
Apparently you are not running `:checkhealth` to trigger it.  (sounds like a new / another issue maybe)
FWIW it's not a problem for me, using the Arch Linux build - but only setting `clipboard+=unnamedplus` after startup (not my default setting).
btw: `nvim -u NONE …` would also work.

**Comment by blueyed** [comment]
Does it happen to both of you with `nvim -u NONE`, setting `clipboard+=unnamedplus`, and using the clipboard already?
If not, it might be another setting or plugin etc triggering it.

**Comment by talbergs** [comment]
I have the same issue.
```
NVIM v0.5.0-23-gafd576ee9
Build type: Release
```

**Comment by blueyed** [comment]
The title mentions this error:

> missing required variable g:loaded_clipboard_provider

But the issue description then:

> Vim(let):E117: Unknown function: provider#clipboard#Executable

It is not really clear if the issue is only relevant with ":checkhealth", and how to reproduce it still.

**Comment by talbergs** [comment]
Well in addition to a fact that I recently decided to maintain my own $VIMRUNTIME (in order to avoid having few things I do not use and to learn a bit more about love), this machine uses waylad (I recall there was an issue with clopboard and wayland some time ago, that was fixed by using unnamedplus)
I might have to put my that up now for inspection (it's really minimal)?
One bit more that I can give - provider#clipboard#Executable() this function does run, does return `wl-copy` then there is the error about missing required variable g:loaded_clipboard_provider

**Comment by talbergs** [comment]
@blueyed oh, sorry - I just realized that I had copied the `autoload/provider/clipboard.vim` file from older neovim release (because of using custom rtp). From my side there is no bug and no issue, here. Thanks for great work on great software!

**Comment by justinmk** [comment]
@nathanielescribano does this happen with `nvim -u NORC`? Please double-check. And please say the results of:

    :echo $VIMRUNTIME
    :echo v:progpath

**Comment by nathanielescribano** [comment]
@blueyed  was right - it ended up being an old plugin i was using. ```cazador481/fakeclip.neovim``` 
Removed it and it's working as expected.

**Comment by ammario** [comment]
I found from https://github.com/neovim/neovim/commit/66938b928c05b913f3a11e520d13ca854621799d#diff-0893c05aff15c6899d56cb0d4f8139f7R200 that that you could surpress this error with:

```
let g:loaded_clipboard_provider = 1
```

But, with all things equal, any copying to my system clipboard fails from 0.3.8 to 0.4.2.

**Comment by thooams** [comment]
Update: I removed `Plug 'cazador481/fakeclip.neovim'` and `let g:loaded_clipboard_provider = 1` from my init.vim file. And with `clipboard+=unnamedplus`, i can use `"+yy` and it works. (on linux)

**Comment by IJustDev** [comment]
> I found from [66938b9#diff-0893c05aff15c6899d56cb0d4f8139f7R200](https://github.com/neovim/neovim/commit/66938b928c05b913f3a11e520d13ca854621799d#diff-0893c05aff15c6899d56cb0d4f8139f7R200) that that you can surpress this error with:
> 
> ```
> let g:loaded_clipboard_provider = 1
> ```
> 
> But, with all things equal, any copying to my system clipboard fails from 0.3.8 to 0.4.2.

Have the same issue. Tried building neovim from source but it still somehow fails.
