### ISSUE TITLE
yaml file indent issue

### ISSUE THREAD

**Issue by chenzhiwei** [neovim/neovim#11039]
This should be a general issue and also appears in vim, my neovim version is:

```
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/build/config -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/build/src/nvim/auto -I/tmp/neovim-20190704-11886-1ukicoc/neovim-0.3.8/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.8/share/nvim"

Run :checkhealth for more info
```

### Steps to reproduce using `nvim -u NORC`

1. Create a `test.yaml` file with following content(include the last two blank lines):

```
branches:
  only:
    - master


```

2. Open this file with `nvim test.yaml`, scroll to bottom of this file and add a new key-pair.

![vim-yaml-bug](https://user-images.githubusercontent.com/672668/65026050-55c14100-d96a-11e9-9fe1-60384170fabb.gif)

### Actual behaviour

The new key-value pair becomes the child element of the previous one.

### Expected behaviour

The new key-value pair should be top level element.

## Root Cause

The reason is because of this file: https://github.com/neovim/neovim/blob/master/runtime/indent/yaml.vim

When I remove this file, I get the expected result.

Stackoverflow: https://stackoverflow.com/questions/57951841/vim-neovim-yaml-indent-bug

cc @justinmk @dbarnett @KillTheMule

**Comment by h-michael** [comment]
@chenzhiwei 
Neovim basically does not modify runtime files.
If there is a problem with runtime files, please issue to Vim.
If runtime files are changed on the Vim side, the patch will be imported into Neovim.

**Comment by chrisbra** [comment]
Yes, but in this case @ZyX-I is the maintainer of the indent file, who is a Neovim contributor.

**Comment by chenzhiwei** [comment]
OK, thank you @h-michael @chrisbra .

I will wait for @ZyX-I 's comment, if no further comments, I will open issue to vim.

**Comment by blueyed** [comment]
> I will wait for @ZyX-I 's comment, if no further comments, I will open issue to vim.

@ZyX-I is inactive currently, so you can go ahead already.

**Comment by chrisbra** [comment]
if he is inactive, then there is nothing we can do at the vim repository. Besides someone actually volunteering to be the new maintainer.

**Comment by blueyed** [comment]
AFAIK this makes Bram the maintainer then, i.e. patches and reports should go to him.
And then the Vim repo is better than sending it per email, no?
But I agree that it might be good enough to have the issue filed here, until somebody comes up with a patch.

It is caused/returned by this line: https://github.com/vim/vim/blob/0e57dd859ecb1e8a3b91509d2f4343e839340eb8/runtime/indent/yaml.vim#L138

**Comment by blueyed** [comment]
What is the expected behavior / fix here?
Should it look further up to see that there is another mapping key on the same indent level already?

This fixes it, but is not well tested:
```diff
diff --git i/runtime/indent/yaml.vim w/runtime/indent/yaml.vim
index 3eb16f845..711b4dc34 100644
--- i/runtime/indent/yaml.vim
+++ w/runtime/indent/yaml.vim
@@ -132,6 +132,14 @@ function GetYAMLIndent(lnum)
         " Same for line containing mapping key
         let prevmapline = s:FindPrevLEIndentedLineMatchingRegex(a:lnum,
                     \                                           s:mapkeyregex)
+        let prev_indent = indent(prevmapline)
+        while prev_indent > indent(a:lnum)
+          let prevmapline = s:FindPrevLEIndentedLineMatchingRegex(prev_indent,
+                      \                                           s:mapkeyregex)
+          if !prevmapline
+            break
+          endif
+        endwhile
         if getline(prevmapline) =~# '^\s*- '
             return indent(prevmapline) + 2
         else
```

**Comment by blueyed** [comment]
=> https://github.com/vim/vim/pull/4946

**Comment by blueyed** [comment]
Fixed in https://github.com/vim/vim/commit/2e693a88b24dc6b12883fad78ff2cb9cd4469c98#diff-79d61bef04e12397c4a5d0494a590d30 (Vim runtime).  Easy patch, if you want to use it already.

**Comment by chenzhiwei** [comment]
@blueyed Do you know when will NVIM sync the runtime files from upstream VIM?

**Comment by blueyed** [comment]
@chenzhiwei 
@justinmk usually does it, likely for/with the 0.5 release then.
