### ISSUE TITLE
fzf visual artifact bug on nvim 0.4.2

### ISSUE THREAD

**Issue by Gee19** [neovim/neovim#11036]
Hitting the same visual bug as mentioned in https://github.com/junegunn/fzf.vim/issues/871

junegunn recommended we open an issue here so I figured I would do it.

https://github.com/Gee19/dotfiles/blob/master/init.vim

- `nvim --version`: v0.4.2
- Operating system/version: mojave
- Terminal name/version: iTerm2/Kitty
- `$TERM`: xterm-256color/xterm-kitty

### Steps to reproduce

Upgrade to new release (0.4.2)
Install fzf.vim
Toggle it

### Actual behaviour
Toggling fzf causes visual artifact bug shown in github issue

### Expected behaviour
:)

Thanks for all the hard work <3 Let me know if I can give any more relevant info.

**Comment by KillTheMule** [comment]
It's a problem with the homebrew build, see https://github.com/neovim/neovim/issues/11031. Use the official binary, or update libvterm (one user on gitter said a system update will have that effect).

**Comment by Gee19** [comment]
Official binary fixed it. Thanks 🙏

**Comment by kule** [comment]
FYI the homebrew build is fixed now ```brew reinstall neovim``` will fix this issue too.
