### ISSUE TITLE
Non-english language is active

### ISSUE THREAD

**Issue by habamax** [neovim/neovim#11045]
- `nvim --version`: 0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: win10
- Terminal name/version: cmd

Previous version of nvim (0.3+) I could make use english with:

`language messages en_US.UTF-8`

Now it doesn't work.

### Actual behaviour

`:lang`

![image](https://user-images.githubusercontent.com/234774/65044797-48a25300-d966-11e9-80fc-6c3da222758b.png)

`:lang mes`

![image](https://user-images.githubusercontent.com/234774/65044828-53f57e80-d966-11e9-9c36-1204c3f3bbcc.png)

### Expected behaviour

nvim should be in English, using english messages and `y/n` instead of `Да/Нет`
![image](https://user-images.githubusercontent.com/234774/65044887-75566a80-d966-11e9-8b9b-8a5d83ca6124.png)

**Comment by erw7** [comment]
@habamax Please try the #11050 artifacts.

**Comment by habamax** [comment]
@erw7 thx. I will try, although not sure how easy it would be to compile it on Win.

**Comment by erw7** [comment]
@habamax If you just want to try it, you don't need to build it yourself. You can use the CI artifact from the following link:

- [64bit MINGW_64](https://ci.appveyor.com/project/neovim/neovim/builds/27485261/job/bfks6e88q59n2xp6/artifacts)
- [32bit MSVC](https://ci.appveyor.com/project/neovim/neovim/builds/27485261/job/7mv9jqmdor1e9l44/artifacts)

If you use 64bit MINGW_64, see the following  https://github.com/neovim/neovim/issues/9461#issuecomment-514071442.

**Comment by erw7** [comment]
You can also `set LC_MESSAGES=en-US` before running `nvim` as a workaround until it is fixed.

**Comment by habamax** [comment]
> You can also set LC_MESSAGES=en-US before running nvim as a workaround until it is fixed.

didn't help

![image](https://user-images.githubusercontent.com/234774/65123233-72598980-d9fb-11e9-97c5-2687d8a225ac.png)

![image](https://user-images.githubusercontent.com/234774/65123247-7a192e00-d9fb-11e9-9cbe-e334fd98bbf7.png)

**Comment by habamax** [comment]
> 
> 
> @habamax If you just want to try it, you don't need to build it yourself. You can use the CI artifact from the following link:
> 
>     * [64bit MINGW_64](https://ci.appveyor.com/project/neovim/neovim/builds/27485261/job/bfks6e88q59n2xp6/artifacts)
> 
>     * [32bit MSVC](https://ci.appveyor.com/project/neovim/neovim/builds/27485261/job/7mv9jqmdor1e9l44/artifacts)
> 
> 
> If you use 64bit MINGW_64, see the following [#9461 (comment)](https://github.com/neovim/neovim/issues/9461#issuecomment-514071442).

I have tried '32bit MSVC build' and all messages and stuff is in english. Thx!

**Comment by the42** [comment]
A working work-around is to
set LANG=C
as environment variable before nvim.exe

**Comment by erw7** [comment]
>> You can also set LC_MESSAGES=en-US before running nvim as a workaround until it is fixed.
>
>didn't help

@habamax You are using Powershell. In that case, `$env:LC_MESSAGES="en-US"` should be used.

**Comment by erw7** [comment]
>A working work-around is to
>set LANG=C
>as environment variable before nvim.exe

In my environment, the language is set to English without any problems regardless of the environment variables `LC_MESSAGES`, `LANGUAGE`, `LC_ALL` and `LANG`.

**Comment by blueyed** [comment]
Removed from the milestone, since #11050 is there already.
