### ISSUE TITLE
`cmap x <Esc>` produces search error in command line search mode

### ISSUE THREAD

**Issue by infokiller** [neovim/neovim#11041]
- `nvim --version`:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
No
- Operating system/version: `Archlinux 5.2.14`
- Terminal name/version: termite `v15` in tmux
- `$TERM`: `screen-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -c 'cnoremap <C-s> <Esc> | call feedkeys("/\<C-s>")'
```

### Actual behaviour

`E486: Pattern not found: <x>`

It seems that nvim tries to go to the next search match. The error above shows up with `<x>` as the last search pattern, if it exists. If there isn't a previous search pattern (for example because adding `--cmd 'set shada='` to the CLI invocation) you will get:

`E35: No previous regular expression`

### Expected behaviour

No error.

**Comment by infokiller** [comment]
I tested this on previous nvim versions and it seems to have been introduced somewhere between `0.3.8` and `0.4.0`.

**Comment by blueyed** [comment]
I'm also seeing this with 0.3.8 (built from the Git tag).

**Comment by chrisbra** [comment]
> With Vim (8.1.2027) it ends up with /^S in the cmdline (^S as a single char, i.e. in blue and can be removed with single backspace).

I don't see this.

Well in Vim this is caused because only an `<esc>` that does not come from a mapping aborts the commandline. That has been discussed a lot on the vim mailinglist. See also `:h c_Esc`

**Comment by blueyed** [comment]
@chrisbra 
> I don't see this.

Ah, Vim needs `-N` also, i.e. `-Nu NONE`.

**Comment by blueyed** [comment]
@infokiller 
Do you see it with 0.3.8 really?
If so, can you git-bisect it?

(but it seems like this might be the expected behaviour now then anyway?)

**Comment by infokiller** [comment]
OK I actually **can** reproduce it in `0.3.8` as well.
Not sure why it wasn't the case before, perhaps something was wrong with the way I tried to reproduce it.
Will try older versions.

**Comment by infokiller** [comment]
Just tested it in `0.2.2` (oldest version with an appimage in the release), and I hit this issue too.
@blueyed so you were able to reproduce it in nvim `0.3.8` but not in vim?

@chrisbra were you able to reproduce it in nvim?

BTW, the command I'm running now is: `nvim -u NORC --cmd 'set shada=' -c 'cnoremap <C-s> <Esc> | call feedkeys("/\<C-s>")'`, which consistently gives me the error `AE35: No previous regular expression` (because shada is disabled, so no there's no search history).

**Comment by blueyed** [comment]
@infokiller 
> @blueyed so you were able to reproduce it in nvim 0.3.8 but not in vim?

No, happened also in Vim (I was missing `-N`).

Should we close this then according to https://github.com/neovim/neovim/issues/11041#issuecomment-532176285 ?

**Comment by infokiller** [comment]
Yes, I will go ahead and close this. I guess the solution is to use `<C-c>` to leave command line mode.
