### ISSUE TITLE
Ruler is no longer displayed when `rulerformat` is used in conjunction with `laststatus=0`

### ISSUE THREAD

**Issue by netmute** [neovim/neovim#11043]
Normally, when setting `laststatus=0`, the ruler is still displayed.
When you set i.e. `rulerformat=%l` first, and then set `laststatus=0`, the ruler is gone.

Edit:
This used to work in master as of a few weeks ago. So the breaking change is fairly recent.

**Comment by blueyed** [comment]
> This used to work in master as of a few weeks ago. So the breaking change is fairly recent.

Can you git-bisect it then, please?

**Comment by netmute** [comment]
I had the macOS homebrew HEAD version installed, but upgraded to 0.4 stable when it became available.
So, unfortunately, I'm not able to say on which commit I was anymore :(

**Comment by netmute** [comment]
I stopped messing around with homebrew and just setup the build system myself.
Bisecting right now.

**Comment by blueyed** [comment]
@netmute 
Oh, thanks - I've found it already.  Maybe you confirm it before/after with it though.

b51ba12: screen: use dedicated message grid  /cc @bfredl 

I've used `build/bin/nvim -u NONE -c ':set laststatus=0 rulerformat=%l'`.

**Comment by bfredl** [comment]
Probably missing a grid adjustment, I will look into it later.

**Comment by netmute** [comment]
Narrowed it down to b51ba122c1edfb769e72c25c4f14f469f59f1b8e, same as you 👍

**Comment by netmute** [comment]
Thank you guys!
