### ISSUE TITLE
clipboard error when put strings inside * register

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#11053]
- `nvim --version`:

NVIM v0.4.0-2050 6aed19b2b
```
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? Not known
- Operating system/version: Windows 10 1803
- Terminal name/version:  Cmder 1.3.11  (it is also replicable inside plain cmd.exe)
- `$TERM`:  --

### Steps to reproduce using `nvim -u NORC`

1. Open nvim with `nvim -u NORC`
2.  Use `:redir @* | version| redir END` command

### Actual behaviour

Output of the command is copied to the clipboard, but there is also an error message:

> clipboard: error invoking win32yank.exe: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WinAPI Error(1418)', src\libcore\result.rs:859 note: Run with `RUST_BACKTRACE=1` for a backtrace. 

### Expected behaviour

No error occurs.

**Comment by justinmk** [comment]
> clipboard: error invoking win32yank.exe: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WinAPI Error(1418)', src\libcore\result.rs:859 note: Run with `RUST_BACKTRACE=1` for a backtrace.

Looks like a problem with https://github.com/equalsraf/win32yank .  cc @equalsraf

**Comment by jdhao** [comment]
@justinmk  It works without error, thanks.

**Comment by 3N4N** [comment]
I tried with latest HEAD of win32yank (`b5ec3e257333`) and that one doesn't have this problem.  win32yank has changed quite a bit since 0.0.4 (exactly a 100 lines).  Maybe we could ask @equalsraf to release a new version.

cc @justinmk

**Comment by 3N4N** [comment]
win32yank bumped to v0.1.1 at #22700, which fixes this bug.
