### ISSUE TITLE
job/channel output: extra "^[[K" characters

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#11056]
Given `t-clone-progress.vim`:

```vim
let cmd = ['git', 'clone', '--progress', 'https://github.com/neoclide/coc.nvim.git', '/tmp/tclone']
" let cmd = join(cmd).' 2>&1 </dev/null'
function! s:nvim_cb(...) abort
  echom string(a:000)
endfunction

if has('nvim')
  let j = jobstart(cmd, {
    \ 'on_stdout': function('s:nvim_cb'),
    \ 'on_stderr': function('s:nvim_cb'),
    \ 'on_exit': function('s:nvim_cb'),
    \ })
else
  let j = job_start(cmd, {
    \ 'callback': function('s:nvim_cb'),
    \ })
endif
```

Running/sourcing it shows messages like this:
```
[61, ['remote: Compressing objects:  40% (6/15)        ^Mremote: Compressing objects:  46% (7/15)        ^M … remote: Compressing objects: 100% (15/15), done.        ', ''], 'stderr']
[61, ['^M^[[KReceiving objects:   0% (1/23177)^M'], 'stderr']
[61, ['^M^[[KResolving deltas:   0% (0/16831)^M'], 'stderr']
```

I could not figure out where the "^[[K" is coming from (where `^[` is a control character, like `^M`).

From infocmp it means `clr_eol` / `el`:

> el=\E[K

But it does not look like Git is adding this itself (https://github.com/git/git/blob/8dca754b1e874719a732bc9ab7b0e14b21b1bc10/progress.c#L118-L140), and therefore appears to
be related to the (termios?) setup for jobs.
Git appears to only turn ECHO off with regard to terminal properties (https://github.com/git/git/blob/8dca754b1e874719a732bc9ab7b0e14b21b1bc10/compat/terminal.c#L46).

It's also an issue with `:!` (and `system()`), but not so much (since likely (most) of it is handled as control characters then):
```
:!git clone --progress https://github.com/neoclide/coc.nvim.git /tmp/tclone
Cloning into '/tmp/tclone'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 23177 (delta 4), reused 7 (delta 2), pack-reused 23160
^[[KReceiving objects: 100% (23177/23177), 10.53 MiB | 7.80 MiB/s, done.
^[[KResolving deltas:  55% (9317/16831)
^[[KResolving deltas: 100% (16831/16831), done.
```

Happens both with kitty+tmux, and urxvt.

(I've noticed this with vim-plug)

NVIM v0.5.0-15-g1070c092c

**Comment by blueyed** [comment]
Looking at strace I see that git indeed writes `\r\33[K`, and it gets called
here: https://github.com/git/git/blob/8a3a6817e24ae1cf1fd08fb90b4a99e6817f646d/progress.c#L119 (should have noticed this! ;))

(It gets skipped for `TERM=dumb` (but uses spaces then) - which I've tried, but
without `pty=1`.)

Therefore this is fine for jobs, and e.g. vim-plug should filter this out.

**Comment by blueyed** [comment]
As for `:!`: it appears to handle this partly already, but not completely - I think that's a bug, no?

**Comment by blueyed** [comment]
Well - it does not handle it partly, but just always writes it at the beginning of the line.

Could `:!` be made to support this easily (i.e. delete to end of line)?

**Comment by bfredl** [comment]
The WIP for fixing `:!` is #10842 :)

**Comment by blueyed** [comment]
@bfredl 
Awesome, closing this one here then.
