### ISSUE TITLE
has('patch-X') needs to consider major/minor - nvim 0.4.2 reports 0 for `has('patch-8.1.1498')`

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#11059]
Patch 8.1.1498 was added in 632ee8d2e:

> vim-patch:8.1.1498,8.1.1501: b:changedtick

However, `VIM_VERSION_MINOR` is still 0 (https://github.com/neovim/neovim/blob/afd576ee9494a76de834f3ea2e1de631c56eb8a3/src/nvim/version.h#L14), and therefore `f_has` considers it to not be there (https://github.com/neovim/neovim/blob/afd576ee9494a76de834f3ea2e1de631c56eb8a3/src/nvim/eval.c#L11472-L11477).

I think we need to have lists for `(major, minor)`, since unlike Vim we cannot assume that all patches from the previous minor version have been applied.

**Comment by justinmk** [comment]
> I think we need to have lists for `(major, minor)`, since unlike Vim we cannot assume that all patches from the previous minor version have been applied.

No, we're not going to do this. The solution is to finish merging 8.0.x patches. Not to build a big workaround that makes it easier to lag behind.

Discussed in https://github.com/neovim/neovim/issues/9635
