### ISSUE TITLE
Provide command line arguments of neovim 

### ISSUE THREAD

**Issue by eyalk5** [neovim/neovim#11063]
Hi, 

It would be nice if neovim would provide the exact arguments that were used to run it.  
I mean if I called it "nvim -u NONE" , a variable would contain "-u NONE". 

For example, we can decide if we want to load last unsaved workspace depending on the args.

**Comment by blueyed** [comment]
Note that there's `argv()` already, but a bit different.

As for a new feature it would be best to have a list for it, instead of a string then I think.

**Comment by glacambre** [comment]
`v:argv` is available on master and gives access to all arguments passed to neovim, so I think this issue can be closed :).
