### ISSUE TITLE
how to change the font on nvim-qt.exe

### ISSUE THREAD

**Issue by irreallich** [neovim/neovim#11079]
- `nvim --version`: v0.35 
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: win10 
- Terminal name/version: gui , nvim-qt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Expected behaviour
could you please tell me how to change the font in nvim-qt on win10 ?
I want to use the monaco font
thanks

**Comment by zgpio** [comment]
ref to https://github.com/equalsraf/neovim-qt

**Comment by irreallich** [comment]
thanks very much
