### ISSUE TITLE
Terminal buffers are affected by scrolloff setting

### ISSUE THREAD

**Issue by Teteros** [neovim/neovim#11072]
- `nvim --version`: NVIM v0.5.0-25-gd6f658e38
- `vim -u DEFAULTS` (version: ) behaves differently? Yes (vim8 :terminal doesn't have this issue)
- Operating system/version: Arch Linux x64
- Terminal name/version: Konsole 19.08.1 (happens on e.g nested neovim :terminal too)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set scrolloff=3
:terminal
cat /proc/cpuinfo # Print any long text to buffer to cause scrolling.
htop # Try any ncurses/TUI app
clear
echo Any text written here will jump around / have "ghost" scroll
```

### Actual behaviour
![scrolloff_nvimterminal](https://user-images.githubusercontent.com/5067989/65377532-3fd2b980-dca5-11e9-8a46-f08bd2436f5c.gif)

When `scrolloff` value is non-zero, `:terminal` buffers misbehave with applications expecting default scrolling (e.g Many ncurses and other TUIs) and typed text jumps around because terminal buffer attempts to centre it.

### Expected behaviour
`:terminal` buffers to not be affected by `scrolloff`, behaving normally as if `scrolloff=0` was set.

~~I've tried setting `au TermOpen * setlocal scrolloff=0` to workaround this issue which works but this sets scrolloff globally, meaning scrolling in normal text buffers wouldn't be centered.~~
EDIT: Forgot I can just do
```
au TermEnter * setlocal scrolloff=0
au TermLeave * setlocal scrolloff=3
```
which works well as a workaround.

**Comment by justinmk** [comment]
We are intentionally conservative about mucking with options in a `:terminal` window. `setlocal scrolloff` is the solution as you found.

**Comment by bfredl** [comment]
Though isn't scrolloff having effects in _terminal mode_ (as opposed to normal mode in terminal window) still a bug? While terminal mode is active the cursor is "owned" by the terminal child and not nvim. That the window cursor is moved with the terminal cursor is mainly an implementation detail (so that GUI:s get the correct cursor position), it should not cause extra scrolling inside terminal mode.

**Comment by Teteros** [comment]
Yes, extra scrolling behaviour looks rather glitchy (shown when typing in the GIF) while in _terminal mode_ (i.e terminal grabs neovim's inputs) is why I opened this as a bug.
I think it would be a saner default (or at least documented) that scrolloff affects terminal mode this way.

Otherwise `TermEnter` and `TermLeave` autocmd's are needed for anyone using `:terminal` and scrolloff with TUIs.

**Comment by wookayin** [comment]
> Some people want scrolloff for whatever reason, and :terminal can't decide based on which process might be running in it.

The problem is that it would flicker even when **simply typing any characters** in the normal shell (in the terminal-insert mode). This has nothing to do with any particular process running in it. I think if it is the terminal *insert* mode, the scrolloff option should be ignored by default.
