### ISSUE TITLE
Which Windows systems are supported/targeted/tested

### ISSUE THREAD

**Issue by fekir** [neovim/neovim#11085]
https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim states that patches that apply to windows xp sp2 or earlier should not apply.

Thus my conclusion was that neovim should work on windows xp sp3.

I tried neovim (win32, version 0.4.2) on reactos (https://reactos.org/, version 0.14.2), which targets Windows Nt 5.2 (Windows Server 2003, AFAIK Windows XP SP3 was still 5.1) but it does not start.

nvim-qt fails to find CancelloEx (https://docs.microsoft.com/en-us/windows/win32/fileio/cancelioex-func) and nvim.exe fails to find ConvertInterfaceIndexToLuid (https://docs.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-convertinterfaceindextoluid).
In both cases an error message with the non-found function is shown.

For what is worth, gvim8.1 starts without issues.

As there is no explicit list of supported platforms, and as those functions are available since Windows Vista, this is a bug iff Windows XP SP3 is supported or not.

Otherwise it would be nice having a list that sheds some light on what platforms neovim is supposed to work.

**Comment by justinmk** [comment]
Windows XP is not supported.

**Comment by justinmk** [comment]
Vista is supported. https://github.com/neovim/neovim/wiki/Installing-Neovim#pre-built-archives

**Comment by fekir** [comment]
> Vista is supported. https://github.com/neovim/neovim/wiki/Installing-Neovim#pre-built-archives
> 
> You need https://support.microsoft.com/en-us/kb/2977003

OK, my answer was a little bit premature. 
I've installed on Windows Vista from https://support.microsoft.com/en-us/kb/2977003 both the x64 and x86 version.

x64 nvim version version:
`nvim.exe`: starts without issues
`nvim-qt.exe`: failed to starte because "no qt platform plugin could be initialized"

x86 nvim version:
`nvim.exe`: an empty prompt opens, but it seems to hang. If I type in it no character appears, `:q` it does to quit etc etc, but the error that it could not find `api-ms-win-crt-runtime-l1-1-0.dll` disappeared.
`nvim-qt.exe`: fails like the x64 version
