### ISSUE TITLE
netrw significantly slower than vim8 (w/default configs)

### ISSUE THREAD

**Issue by georgewitteman** [neovim/neovim#11089]
- `nvim --version`: v0.5.0-dev (full output below)
- `vim -u DEFAULTS` (version: ) behaves differently? N/A (`netrw` not loaded)
- Operating system/version: macOS Mojave 10.14.6 (18G95)
- Terminal name/version: Tried in alacritty 0.3.3 (71a818c), iTerm 3.3.5beta2, and Terminal 2.9.5 (421.2)
- `$TERM`: alacritty, xterm-256color, and ansi respectively
- `echo &clipboard`: <EMPTY>

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:Explore
```

### Actual behaviour
Neovim takes around 1s to load `netrw` and 1s or more to move between directories.

### Expected behaviour
`netrw` should move directories almost instantly. This issue does not happen in vim8. Also doesn't happen when I add `let g:loaded_clipboard_provider = 1` to the top of my `init.vim`.

Also tried updating `reattach-to-user-namespace` and added `set-option -g default-command "reattach-to-user-namespace -l zsh"` in my `tmux.conf` and nothing changed.

From the output logs below it looks like something weird is going on with the clipboard, although since I don't get it with vim8 I think it's nvim specific.

Possibly related issues: #1882, #6695, #3726, 
Possibly related PRs: #2809, #6892

### Extra

**`nvim --version`**
```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190924-99189-1y0mwkx/build/config -I/tmp/neovim-20190924-99189-1y0mwkx/src -I/usr/local/include -I/tmp/neovim-20190924-99189-1y0mwkx/deps-build/include -I/usr/local/opt/gettext/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190924-99189-1y0mwkx/build/src/nvim/auto -I/tmp/neovim-20190924-99189-1y0mwkx/build/include
Compiled by georgewitteman@George.W-MBPro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-0ab7da8/share/nvim"

Run :checkhealth for more info
```
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   42   1.138288   0.001465  provider#clipboard#Call()
   42   1.135443   0.005160  <SNR>70_try_cmd()
   40   1.080853   0.001290  4()
    4   0.707367   0.000363  netrw#LocalBrowseCheck()
    4   0.706806   0.001969  <SNR>68_NetrwBrowse()
   10   0.550346             <SNR>68_NetrwOptionsSave()
   14   0.483422   0.003829  <SNR>68_NetrwOptionsRestore()
  333   0.478200             <SNR>68_NetrwRestoreSetting()
    3   0.357461   0.001490  <SNR>68_NetrwBrowseChgDir()
    4   0.276122   0.001994  <SNR>68_PerformListing()
    3   0.269118   0.001007  <SNR>68_NetrwEnew()
    1   0.256364   0.123082  netrw#Explore()
    1   0.243573   0.000180  <SNR>34_opendir()
    1   0.243361   0.000234  <SNR>68_NetrwBrowseUpDir()
    4   0.212334   0.000909  <SNR>68_NetrwGetBuffer()
    1   0.060355   0.001628  <SNR>68_NetrwBookHistSave()
    2   0.055970   0.000090  5()
    7   0.028496   0.001864  <SNR>68_NetrwOptionsSafe()
    4   0.018156   0.009810  <SNR>68_LocalListing()
   11   0.014094             <SNR>7_LoadFTPlugin()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
   10              0.550346  <SNR>68_NetrwOptionsSave()
  333              0.478200  <SNR>68_NetrwRestoreSetting()
    1   0.256364   0.123082  netrw#Explore()
   11              0.014094  <SNR>7_LoadFTPlugin()
    4   0.018156   0.009810  <SNR>68_LocalListing()
   30              0.008647  StatusLineFilename()
   11   0.009764   0.005432  <SNR>10_SynSet()
   42   1.135443   0.005160  <SNR>70_try_cmd()
    4   0.005164   0.005069  <SNR>68_NetrwMaps()
  130              0.004821  <SNR>68_NetrwFile()
   30              0.004132  StatusLine()
   15   0.005871   0.003925  fugitive#Find()
   14   0.483422   0.003829  <SNR>68_NetrwOptionsRestore()
    8   0.004227   0.003624  <SNR>68_NetrwGlob()
  147              0.003190  <SNR>68_NetrwSetSafeSetting()
   13   0.003560   0.003165  <SNR>37_SetupAutoCommands()
    9   0.003856   0.002700  FugitiveExtractGitDir()
    4              0.002662  <SNR>68_NetrwSetSort()
    4              0.002471  <SNR>68_NetrwListHide()
   19              0.002378  <SNR>47_Highlight_Matching_Pair()
```

**Comment by georgewitteman** [comment]
Looking around some more it seems like this is because neovim is using `pbcopy`/`pbpaste` instead of directly accessing the system clipboard like in vim8. On my system those commands are pretty slow (100-300ms range). Not sure why `pbcopy`/`pbpaste` are so slow and why accessing it natively would be faster though

Vim8 macOS clipboard: https://github.com/vim/vim/blob/10d4664330b9379d5a54aa60c80c8069f73d822c/src/os_macosx.m

**Comment by blueyed** [comment]
Can you post the full profile output maybe?
It would be interesting to know why `provider#clipboard#Call()` gets called so often in the first place.
(you can use `<details>` for it: https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)

**Comment by georgewitteman** [comment]
@blueyed Pretty sure `provider#clipboard#Call()` happens anytime the clipboard is accessed.

* nvim [calls eval_call_provider]()https://github.com/neovim/neovim/blob/9cf8cf605d85ec043d4e39f73ac42c7482c6f901/src/nvim/ops.c#L5778
* ... idk where eval_call_provider is
* I think that then calls [provider#clipboard#Call]()https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/clipboard.vim#L195
* which calls [s:clipboard.get](https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/clipboard.vim#L133)
* which calls [try_cmd](https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/clipboard.vim#L139) with `pbcopy`/`pbpaste`

Full log (too large to embed): https://gist.github.com/georgewitteman/070a5eb25871ef699e1a9482b42b2cd2

**Comment by blueyed** [comment]
@georgewitteman 
I've meant more why the netrw code is calling it so often - if that's the case after all.
Is the profile only for when netrw behaves/is slow, or for a longer period where you've used the clipboard yourself (~40 times)?

**Comment by georgewitteman** [comment]
Oh I see. I'm not exactly sure why netrw reads/writes to the clipboard registers so much. There's a bunch of code like https://github.com/neovim/neovim/blob/9cf8cf605d85ec043d4e39f73ac42c7482c6f901/runtime/autoload/netrw.vim#L918-L924

There was #6892 that "fixed" it by not running those lines for neovim, but wasn't merged since it just started working again and it would require changing netrw.

The profile is from me loading netrw. Can't remember if I moved directories at all, but the only thing I did was start nvim and call `:Explore`

**Comment by justinmk** [comment]
> It would be interesting to know why `provider#clipboard#Call()` gets called so often in the first place.

It's just netrw's poor design/implementation.  https://github.com/neovim/neovim/issues/6048#issuecomment-276934150

There are many duplicates of this issue as mentioned, but this one has better info so let's close the others.

**Comment by georgewitteman** [comment]
Some more debug info comparing neovim to vim8: https://gist.github.com/georgewitteman/d4474b6f68bb0e2f91f071658af6d3e8. Still seems like calling `pbcopy`/`pbpaste` is the culprit.

I'd be happy to help contribute, but I have just a little C experience from school, so I'd need some guidance or at least be pointed in the right direction.

**Comment by justinmk** [comment]
There's no mystery about why Vim is faster, this is a known issue. Nvim invokes shell commands to work with the clipboard, whereas Vim uses the OS API. Nvim approach is more flexible, Vim approach is faster (but usually doesn't matter except for badly-designed plugins such as netrw).

Current suggestion is https://github.com/neovim/neovim/issues/11089#issuecomment-534851925 .

**Comment by bfredl** [comment]
```
let keepregstar = @*
let keepregplus = @+
...
sil! let @* = keepregstar
sil! let @+ = keepregplus
```
This code is broken even if we hack it to be "fast enough":

  - It throws away the register type (if the clipboard was owned by nvim to start with)
  - it throws away non-text contents of the system clipboard

Does netrw invoke anything that clobbers the clipboard anyway? is there any reason we cannot disable this code in nvim again? ( like #6892 but perhaps with some flag instead of `has("nvim")`, which might make upstream more keen to accept it later on, though perhaps the code is not needed even for vim)

**Comment by georgewitteman** [comment]
> We've discussed (in chat, at least) the idea of skipping clipboard updates until certain events. E.g. with `clipboard=unnamed`, to make `xxxxxxxxxxxx` fast, don't update the clipboard until a yank or focus-lost event.

Wouldn't this break any legitimate scripts that rely on functionality like `let @* = ` though?

**Comment by DealPete** [comment]
Any recent action on this? I'd like to make the switch to neovim, but I use netrw a lot and this is a deal-breaker for me.

**Comment by mhinz** [comment]
Nobody is working at this at the moment. If there is progress, this issue will be updated.

**Comment by RRethy** [comment]
Looking through the code it doesn't look like netrw does anything other than save and restore `@*` and `@+`. The one place seems to have a reason for saving the clipboard is in `autoload/netrw.vim:400` with:

```vim
  if &go =~# 'a' | sil! let {a:vt}netrw_regstar = @* | endif
```

But I don't think this check is even needed anymore for Neovim since `:h 'go'` indicates this option is only for the GUI version of Vim. I'm also not super familiar with this option so maybe someone can shed more light on it.

Looking through the releases for netrw based on [this repo](https://github.com/vim-scripts/netrw.vim), it was v107 which started saving the clipboard. These are the release notes for this version:

```
	v107: Oct 12, 2006 * bypassed the autowrite option
	      Oct 24, 2006 * handles automatic decompression of *.gz and *.bz2
			     files
	      Nov 03, 2006 * Explore will highlight matching files when
			     **/pattern is used (and if the |'hls'| option
			     is set)
	      Nov 09, 2006 * a debugging line, when enabled, was inadvertently
			     bringing up help instead of simply reporting on
			     list contents
	      Nov 21, 2006 * tree listing improved (cursor remains put)
	      Nov 27, 2006 * fixed b:netrw_curdir bug when repeated "i"s were
			     pressed.
	      Dec 15, 2006 * considerable qty of changes, mostly to share more
			     code between local and remote browsing.  Includes
			     support for tree-style listing for both remote
			     and local browsing.
	      Dec 15, 2006 * Included Peter Bengtsson's modifications to
			     support the Amiga.
```

Can't figure out why it was introduced in the first place yet. Still trying to prove it, but I don't think these saves/restores are necessary, been using it with them commented out and things seem to work fine (ik that doesn't really mean much lol).

**Comment by Shane-XB-Qian** [comment]
`There's no mystery about why Vim is faster, this is a known issue. Nvim invokes shell commands to work with the clipboard, whereas Vim uses the OS API.`

um, ok then, good to know. i have no chance to feel nvim yet, but if so, looks it solved the clipboard lost issue, but just slow. :)

**Comment by justinmk** [comment]
> But I don't think this check is even needed anymore for Neovim since `:h 'go'` indicates this option is only for the GUI version of Vim. I'm also not super familiar with this option so maybe someone can shed more light on it.

Yeah, we are open to removing those lines. Waiting for a PR.
