### ISSUE TITLE
Angle brackets not pasted in command line

### ISSUE THREAD

**Issue by infokiller** [neovim/neovim#11088]
- `nvim --version`:

```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
Yes
- Operating system/version: `Linux 5.2.14 #1 SMP PREEMPT Tue Sep 10 23:52:33 CEST 2019 x86_64 GNU/Linux`

- Terminal name/version: `termite v15`
- `$TERM`: `xterm-termite`

### Steps to reproduce using `nvim -u NORC`

1. Copy a single angle bracket to the clipboard: `<`
2. Open neovim and start command mode: `nvim -u NORC -c 'call feedkeys(":")'`
3. Paste the clipboard content (`Ctrl+Shift+v` on many terminals)

### Actual behaviour
Nothing appears in the command line

### Expected behaviour
`<` shows up in the command line

**Comment by blueyed** [comment]
Confirmed.
This is caused by `handle_bracketed_paste` - returning `false` there fixes it.

**Comment by justinmk** [comment]
It's because nvim_input is used. Quickfix is to replace `<` with `<lt>` in `vim.paste()` .

**Comment by blueyed** [comment]
Ok, I have a test already - will create a PR.

**Comment by infokiller** [comment]
Thanks @blueyed just tested your PR and it works indeed.
