### ISSUE TITLE
wildmenu appears as pink scrollbar on left side

### ISSUE THREAD

**Issue by afinit** [neovim/neovim#11108]
- `nvim --version`: v0.4.2,  v0.5.0-67-g298da52fd
- `vim -u DEFAULTS` (version: 8.1) behaves differently? yes
- Operating system/version: Arch Linux (Up to date) AND MacOSX v10.13.6
- Terminal name/version: xterm AND iTerm2
- `$TERM`: xterm AND xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```

After opening nvim:
`:<tab>`

### Actual behaviour

v0.4.2:
`wildmenu` appears as pink scrollbar on left side:
![image](https://user-images.githubusercontent.com/6353304/65791598-b2b9b580-e127-11e9-9476-c02099ebaf81.png)

v0.5.0-67-g298da52fd:
`wildmenu` appears as pink scrollbar on left side:
![image](https://user-images.githubusercontent.com/6353304/65791673-d1b84780-e127-11e9-888c-a46b45f4b11f.png)

### Expected behaviour

v0.3.4:
`wildmenu` appears in status bar at bottom
![image](https://user-images.githubusercontent.com/6353304/65791763-00ceb900-e128-11e9-99bf-c6a7231daa10.png)

vim 8.1:
![image](https://user-images.githubusercontent.com/6353304/65792081-9e29ed00-e128-11e9-9650-5e44a7e45edc.png)

If this is a new feature, is there a simple way to restyle this?
What would I be googling to find solutions to styling this differently?

**Comment by blueyed** [comment]
`:set wildoptions-=pum` disables this.
It might look nicer (i.e. not pink) with a decent colorscheme.. ;)

In general `wildoptions+=pum` is very nice.

Closing as answered.

**Comment by Exagone313** [comment]
Thanks I was looking to how to disable this list. With this, arrow keys are not intuitive, and when there are two options I always think the wrong one is selected (because I'm used to look at the first option - which is selected by default - where the second is now placed).
