### ISSUE TITLE
Register name gets inserted into current buffer with vim-peekaboo in Neovim 0.4.2

### ISSUE THREAD

**Issue by deathlyfrantic** [neovim/neovim#11102]
- `nvim --version`:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: 8.0.1365) behaves differently? Yes
- Operating system/version: macOS 10.14.6
- Terminal name/version: alacritty 0.3.3 (cc3e4d3)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

I did this with `nvim -u NONE`, that's probably basically the same?

```
nvim -u NONE
:packadd vim-peekaboo
:call peekaboo#on()

type some words in buffer, spread however you like over at least 4 lines (see screenshots in comment below to see how I set up my test buffer)
viw to select one of the words, then "+y to yank
```

### Actual behaviour

Register name gets inserted into buffer and is highlighted with `peekabooSelected` group.

### Expected behaviour

Register name should not be inserted into buffer and should not be highlighted.

It seems like the actions that should happen in the peekaboo buffer are instead happening in my current working buffer and I don't know why. See https://github.com/junegunn/vim-peekaboo/issues/61 for screenshots and more description. I'm filing this here because it doesn't happen on Vim, and I don't remember it happening before I upgraded to Neovim 0.4.2.

**Comment by blueyed** [comment]
Could not reproduce it on master.
What clipboard tool do you use?  (`:checkhealth provider`)

**Comment by blueyed** [comment]
I assume this happens only with the `"+` and `"*` clipboard registers?

**Comment by deathlyfrantic** [comment]
> Could not reproduce it on master.

I filed in haste and didn't spell out all the necessary steps, I think, so if you didn't look at the linked issue you may not have had enough lines in the buffer. (I will edit to clarify.) It seems to happen only if there are 4+ lines in the buffer, and it's always the second word of line 4 where the `+` appears. It goes from this:
<img width="632" alt="Screen Shot 2019-09-26 at 8 59 17 AM" src="https://user-images.githubusercontent.com/7629614/65732615-a20e2e80-e098-11e9-91fc-fefc3d6fbc0a.png">
To this:
<img width="632" alt="Screen Shot 2019-09-26 at 9 00 25 AM" src="https://user-images.githubusercontent.com/7629614/65732631-bfdb9380-e098-11e9-92df-78bc5161a172.png">
> What clipboard tool do you use? (:checkhealth provider)
```
## clipboard (optional)
  - OK: Clipboard tool found: pbcopy
```
(Side note - I had to fix the first letter of "clipboard" because it got changed to a `+` when I copied that information.)

> I assume this happens only with the "+ and "* clipboard registers?

Actually I just tested and it doesn't happen with `*`, just with `+`. Strangely though, with the `0` and `:` registers (and presumably others), the `s` in the the word "something" that I have selected in the first screenshot gets replaced with the register name. No highlighting though. This is super weird!
<img width="632" alt="Screen Shot 2019-09-26 at 8 08 24 PM" src="https://user-images.githubusercontent.com/7629614/65732783-6aec4d00-e099-11e9-8ed2-3527aa8d1686.png">

**Comment by deathlyfrantic** [comment]
I tried to trace the Peekaboo code to see if I could figure out what series of steps is causing this. Unfortunately I was not able to pinpoint it exactly, but it seems the general cause is the Peekaboo window is getting closed unintentionally.

In Vim, if I have my example with "something" selected in visual mode, and I type `"0`, the Peekaboo window is open with the `0` register line highlighted. In Neovim, after the same series of steps the Peekaboo window is not open.

Peekaboo [sets up a `CursorMoved` autocmd](https://github.com/junegunn/vim-peekaboo/blob/master/autoload/peekaboo.vim#L99) to delete its buffer if the cursor is moved; I added an `echomsg` to this and saw this being fired in the middle of the sequence when it didn't seem (to me) like it should be.

This series of steps reproduces a weird situation that _might_ be the cause:
```
nvim -u NONE
:wincmd v
:autocmd CursorMoved <buffer> echoerr 'moved'
:wincmd l
```

In Neovim, this event fires and I get:
```
Error detected while processing CursorMoved Autocommands for "<buffer=1>":
moved
```

In Vim, this event does not fire.

Is the CursorMoved event supposed to fire when switching between windows?

**Comment by deathlyfrantic** [comment]
Based on https://github.com/neovim/neovim/issues/9838, I guess this is an intentional incompatibility with Vim?

**Comment by blueyed** [comment]
Sounds like it - peekabo could probably check the buffer itself / only setup the autocommand for the relevant buffer?

**Comment by deathlyfrantic** [comment]
> Sounds like it - peekabo could probably check the buffer itself / only setup the autocommand for the relevant buffer?

It is already defined as a buffer-local autocmd. I guess the CursorMoved event fires for both the previous and next windows? I've submitted a PR to add `noautocmd`s to the `wincmd p`s, which fixes this specific issue for me.

Since this was identified as a won't fix in the other issue I will close this.

**Comment by blueyed** [comment]
> It is already defined as a buffer-local autocmd.

Oh, true.

> I guess the CursorMoved event fires for both the previous and next windows? 

IIRC it (should) happen only for the new window/buffer?

Why is it so hard to trigger?  Sounds like it might into something that is not expected then, isn't it?
Otherwise I would expect it to be easier to trigger.
