### ISSUE TITLE
Regression: poor scroll performance for Ruby files on Mac when using conceallevel=1

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#11100]
Hello Neovim support,

I am encountering a performance regression with the Neovim 0.4.X series. Neovim 0.3.8 and Vim 8.1.2050 do **not** have this issue, they are good.

The performance regression relates to the `conceallevel` option.

Note, my device is a 2015 12" Macbook with the slow 1.1GHz Intel Core M 5Y31 processor. Mac users with faster processors may not see this issue as obviously as I do.

A minimal `init.vim`, with the [vim-plug](https://github.com/junegunn/vim-plug) plugin manager, that highlights the issue:

```viml
syntax on
set conceallevel=1
call plug#begin('~/.vim/plugged')
Plug 'vim-ruby/vim-ruby'
call plug#end()
```

A Ruby RSpec that highlights the issue: [adding_albums_spec.rb](https://github.com/bluz71/platters/blob/master/spec/system/adding_albums_spec.rb).

Steps to repeat:

1) Use iTerm2

2) Edit the candidate RSpec file

3) Hold down `j` to scroll to the bottom, hit `gg` to go back to the top and repeat

4) In another terminal open `htop` or something similar and watch CPU usage for the editor

These are the **max** CPU usages I see when doing those steps with different flavours of Vim:

* nvim 0.3.8 --> ~12%
* vim 8.1.2050 --> ~15%
* nvim 0.4.2 --> **100%**

100% CPU usage would explain my scroll performance issue.

Now change `conceallevel=0`, the issue goes away. Here are the CPU usage stats for that case:

* nvim 0.3.8 --> 7%
* vim 8.1.2050 --> 7%
* nvim 0.4.2 --> 7%

Using `conceallevel=1` or `conceallevel=2` for Ruby files on slow Mac machines results in poor scroll performance with the recent 0.4.X Neovim series.

If there are pre-built Mac binaries for the 0.4 development series available, I would be willing to test them to narrow down the cause. But I can't find past pre-built nightlies.

Note, I am much less confident about building Neovim from source.

Thanks.

**Comment by blueyed** [comment]
Thanks for the easy to reproduce issue report!

Bisected to:

commit 54d9ea61ab2e7ce0d1dfdbf427b6d6702f972d74
Author: @janlazo 
Date:   Sat Jul 20 19:32:17 2019 -0400

    vim-patch:8.1.0856: when scrolling a window the cursorline is not always updated
    
    Problem:    When scrolling a window other than the current one the cursorline
                highlighting is not always updated. (Jason Franklin)
    Solution:   Call redraw_for_cursorline() after scrolling.  Only set
                w_last_cursorline when drawing the cursor line.  Reset the lines
                to be redrawn also when redrawing the whole window.
    https://github.com/vim/vim/commit/bbb5f8d4c2cbc5f48556008875f57cbe7fc4ac6c

The port of the patch looks good, and Vim at that patch level does not show the issue (i.e. it is not missing a later patch, but maybe an earlier one).

More likely that this triggers an unoptimized patch in Neovim's display layer though.
/cc @bfredl

**Comment by bluz71** [comment]
Excellent news @blueyed. I am very happy that it is reproducible.

Looking forward to further analysis, and eventually a fix.

**Comment by blueyed** [comment]
Seems to be caused / triggered due to refactoring in 23c71d518, which cause the state of the last cursorline now not being updated internally anymore.

The following appears to fix it:
```diff
diff --git i/src/nvim/screen.c w/src/nvim/screen.c
index 17a91f69d..1bd9fe579 100644
--- i/src/nvim/screen.c
+++ w/src/nvim/screen.c
@@ -2403,7 +2403,7 @@ win_line (
   filler_todo = filler_lines;
 
   // Cursor line highlighting for 'cursorline' in the current window.
-  if (wp->w_p_cul && lnum == wp->w_cursor.lnum) {
+  if (win_cursorline_standout(wp) && lnum == wp->w_cursor.lnum) {
     // Do not show the cursor line when Visual mode is active, because it's
     // not clear what is selected then.
     if (!(wp == curwin && VIsual_active)) {
```

**Comment by blueyed** [comment]
@bluz71 
As a workaround you can `set cursorline`.. it's usually the other way around.. :D

Why do you use `set conceallevel=1` btw?

**Comment by bluz71** [comment]
> Why do you use set conceallevel=1 btw?

I set it to 2 actually.

I use the [indentLine](https://github.com/Yggdroot/indentLine) plugin to display guide markers per-indentation level. Those markers only become visible once `conceallevel` is set to 1 or 2. That's the reason why.

I will pass on `cursorline`, I don't like the look of it enabled.
I can wait for the fix, hopefully ported to the 0.4.X series and not just a 0.5.X fix.

**Comment by blueyed** [comment]
I see.  I can recommend https://github.com/mtth/cursorcross.vim in this regard, provides a marker line only when starting insert mode.
As for cursorline: I am using one myself, but actually turn it off when scrolling / via CursorMoved (https://asciinema.org/a/J0ces0NZQOsgVPPlf6LoE32jb).

**Comment by bluz71** [comment]
[indentLine](https://github.com/Yggdroot/indentLine) allows me to use a dotted line Unicode glyph as the indent marker which looks really nice and subtle (almost akin to the guide markers displayed in Sublime/Atom/VSCode). Been using the plugin for five plus years, like it very much.

Back on topic, I see you added the fix to the 0.4.3 milestone. Superb. I can live with the performance issue until then, no worries.

**Comment by bluz71** [comment]
Thank you very much.

I look forward to the 0.4.3 release.

**Comment by blueyed** [comment]
You're welcome.
You could use the release-0.4 branch already (meant to be stable), or master, of course.

**Comment by bluz71** [comment]
@blueyed,

Just tested the nightly release (v0.5.0-140-g402afb089).
I can confirm that the this issue is fixed on my machine, superb.
Thank you or your outstanding support, I do appreciate it very much.

Also this nightly release resolves another minor regression with 0.4.2 which I did not report. On my slow Macbook (Core-M processor) running nvim 0.4.2 under tmux re-introduced a different, but visibly similar, variant of the [jumpy cursor issue I reported in 2017](https://github.com/neovim/neovim/issues/7015). When launching 0.4.2 Neovim on a Ruby file, under tmux, I could sometimes see the cursor jump all over the screen (testing each cell?). That issue was not present in 0.3.8.

Well the nightly also fixes that jumpy cursor issue.

I look forward to the upcoming 0.4.3 release via Homebrew.

**Comment by justinmk** [comment]
> When launching 0.4.2 Neovim on a Ruby file, under tmux, I could sometimes see the cursor jump all over the screen (testing each cell?). That issue was not present in 0.3.8.

That sounds like https://github.com/blueyed/neovim/commit/bfb21f3e012d9473d6038dd254fc3a0ecdf8c0e9 but I don't think any of the recent TUI changes should have regressed that. Though I was worried about https://github.com/neovim/neovim/pull/11083 at first glance.

**Comment by bluz71** [comment]
@justinmk,

Maybe it was the coceallevel fix that resolved it? All Is good now.

**Comment by blueyed** [comment]
@bluz71 
You're welcome, thanks for the report again.. :)

As for the other issue, it might be interesting to know when this was fixed (and regressed initially for you).
Since you are using the nightly it might be something that is not in the release-0.4 branch yet (and would be still there with 0.4.3).
But since you are launching it with a Ruby file already (with the settings then) it might just be the same issue after all.

**Comment by bluz71** [comment]
Is there a 0.4 nightly available? I’d be happy to test it and let you know.

My gut tells me it is the same issue.

**Comment by blueyed** [comment]
@bluz71 
Not that I know - except for the Windows builds probably (?).
But I think we should have a 0.4.3 soon anyway, but it would be bad if it's not fixed there then.. ;)

Building Neovim is not that hard (on Unix systems) after you get the build dependencies.  https://github.com/neovim/neovim/wiki/Building-Neovim
You can just "make" it, and try `build/bin/nvim` then.
