### ISSUE TITLE
Error message when pasting from visual block at end of file

### ISSUE THREAD

**Issue by mr-straw** [neovim/neovim#11105]
- `nvim --version`: `NVIM v0.4.2`
- `vim -u DEFAULTS` (version: ) behaves differently? **yes**
- Operating system/version: **Arch**
- Terminal name/version: `termite v15`
- `$TERM`: `xterm-termite`

The error message happens whenever new lines are created by a paste from visual block

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
il<CR>l<ESC><C-V>kyjp
```

### Actual behaviour
Error `E315: ml_get: invalid lnum: 4` for each new line created

**note:** This error does not happen with `nvim -u NONE`

**Comment by justinmk** [comment]
Cannot reproduce this. Tested on v0.5.0-94 e93342629

Maybe caused by (and later fixed) a vim patch.

Can you try HEAD/unstable: https://github.com/neovim/neovim/releases

Assuming this is fixed until then.
