### ISSUE TITLE
Flaky test: tui_spec.lua: TUI paste: exactly 64 bytes

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#11110]
This failed 3+ times already:

```
[  ERROR   ] test/functional/terminal/tui_spec.lua @ 561: TUI paste: exactly 64 bytes #10311
test/functional/ui/screen.lua:587: Row 1 did not match.
Expected:
  |*zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz|
  |*zzzzzzzzzzzzzz end{1: }                               |
  |{4:~                                                 }|
  |{4:~                                                 }|
  |{5:[No Name] [+]                                     }|
  |{3:-- INSERT --}                                      |
  |{3:-- TERMINAL --}                                    |
Actual:
  |* endzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz|
  |*zzzzzzzzzzzzzzzzzz{1: }                               |
  |{4:~                                                 }|
  |{4:~                                                 }|
  |{5:[No Name] [+]                                     }|
  |{3:-- INSERT --}                                      |
  |{3:-- TERMINAL --}                                    |

To print the expect() call that would assert the current screen state, use
screen:snapshot_util(). In case of non-deterministic failures, use
screen:redraw_debug() to show all intermediate screen states.  

stack traceback:
	test/functional/ui/screen.lua:587: in function '_wait'
	test/functional/ui/screen.lua:370: in function 'expect'
	test/functional/terminal/tui_spec.lua:569: in function <test/functional/terminal/tui_spec.lua:561>
```
https://builds.sr.ht/~jmk/job/91950#task-test-release-585

Initially seen in https://github.com/neovim/neovim/pull/11083#issuecomment-534375201 (ref from top comment).

Code: https://github.com/neovim/neovim/blob/fe9d54f418973f59ec88ca05489da6df3609811f/test/functional/terminal/tui_spec.lua#L561-L579

_Originally posted by @blueyed in https://github.com/neovim/neovim/pull/11086#issuecomment-535247575_

**Comment by blueyed** [comment]
@justinmk said:

> I think it's a race related to the current mode .

**Comment by justinmk** [comment]
It might help to wait_for_mode(...) before or after the paste input.

**Comment by blueyed** [comment]
Then a single `feed_data` would do it probably, too?

But doesn't it indicate some issue, like fed input not being processed in order (or rather the " end" not being queued properly for after paste is (considered to be) finished)?
/cc @bfredl

**Comment by justinmk** [comment]
> Then a single `feed_data` would do it probably, too?

No that's async so it doesn't act like a "wait".

> But doesn't it indicate some issue, like fed input not being processed in order (or rather the " end" not being queued properly for after paste is (considered to be) finished)?

Maybe. Since TUI input is normally enqued to os_inchar whereas the vim.paste invocation is queued as K_EVENT, maybe they race to reach `state.c` .

**Comment by blueyed** [comment]
> > Then a single `feed_data` would do it probably, too?
> 
> No that's async so it doesn't act like a "wait".

I've meant that this might help with getting the input in order - ruling out that what we're seeing is because of the second data (" end") to be processed before the first.
But that shouldn't be the case in the first place already.

> > But doesn't it indicate some issue, like fed input not being processed in order (or rather the " end" not being queued properly for after paste is (considered to be) finished)?
> 
> Maybe. Since TUI input is normally enqued to os_inchar whereas the vim.paste invocation is queued on `main_loop.events`, maybe they race to reach `state.c` .

:+1:

**Comment by ffanzhang** [comment]
Stumbled upon this post because my build failed with the same error.

**Comment by justinmk** [comment]
Haven't noticed this failure in quite some time. And the test is not skipped in CI.
