### ISSUE TITLE
nvim.appimage link leads to error page

### ISSUE THREAD

**Issue by thepenguinthatwants** [neovim/neovim#11111]
From the guide: https://github.com/neovim/neovim/wiki/Installing-Neovim

curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
the page itself cant load.

**Comment by justinmk** [comment]
It's working now. There might be a few seconds/minutes each day where it's broken, since the update job needs to delete the old one before uploading the new one. Or sometimes the update job fails.
