### ISSUE TITLE
Running nvim from git-bash appears to do nothing - no output at all

### ISSUE THREAD

**Issue by jjoekoullas** [neovim/neovim#11112]
- `nvim --version`:
NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

- `vim -u DEFAULTS` (version: 8.1.1777) behaves differently? _Yes, it appears to work just fine._
- Operating system/version: _windows 10_
- Terminal name/version: _mintty 3.0.2_
- `$TERM`: _"bash: xterm: command not found"_

### Steps to reproduce using `nvim -u NORC`

1. Unzip https://github.com/neovim/neovim/releases/download/v0.4.2/nvim-win64.zip and add the Neovim/bin folder to path
2.  Run nvim from git bash

### Actual behaviour
Nothing happens.  Have to crtl-c to get back to terminal

### Expected behaviour
nvim starts

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/issues/6751
https://github.com/neovim/neovim/pull/8271 is not merged so neovim does not support mintty.

**Comment by justinmk** [comment]
Maybe some small part of #8271 could be used to detect mintty and show an error message.

**Comment by jjoekoullas** [comment]
Excuse my ignorance, but I had been using nvim in git bash without issue for some time up until I reimaged my laptop a few weeks ago.

Is it possible git bash on Windows changed from something that did work (cygwin?) to something that didn't work (mintty) for nvim?

**Comment by justinmk** [comment]
Maybe. You need to say precisely what versions of terminal/Nvim you were using. "Git bash" runs in many different terminals.
