### ISSUE TITLE
[RFC] shell: pulse: display last output after some delay?

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#11128]
Running `:!make install` for nvim (with LTO) itself shows:

```
[137/156] Generating it.mo

.. [153/156] Linking C executable bin/nvim
[154/156] Generating pack/dist/opt/vimball/doc/tags
[155/156] Generating pack/dist/opt/matchit/doc/tags
[156/156] Generating doc/tags
```

It waits after the ".." for quite some time (due to the linking taking so long).

I think it might be good to display the last buffer of output in case there's no output for a given duration?

For this it likely needs to keep track of the last e.g. 1000 bytes of output always.

Update:
`out_data_cb` and therefore `out_data_decide_throttle` are not called with no output in the first place.  This would require to have some additional timer then that would take care of this.

**Comment by justinmk** [comment]
Let's not complicate this.  The throttling may even be removed after `:!` supports pty / modal `: terminal` .
