### ISSUE TITLE
Buffer changes, "shadow buffers" and the MSGPACK API

### ISSUE THREAD

**Issue by myitcv** [neovim/neovim#1114]
It is highly likely that plugins, including for example those written in Go using [`neovim`](http://godoc.org/github.com/myitcv/neovim), will need to maintain "shadow buffers", mirroring the contents of one or more buffers in a Neovim instance. The example I have right now is [`neovim-go`](https://github.com/myitcv/neovim-go), where I am parsing the shadow buffer into an AST to drive syntax highlighting by offset (see #719 for a more detailed discussion)

A naive implementation maintaining a shadow buffer might look something like this:
1. Define a buffer-local [`autocmd`](http://vimdoc.sourceforge.net/htmldoc/autocmd.html) that emits an event on each change of the text, something like `:au TextChanged,TextChangedI <buffer> call send_event(0, "text_changed", [])`
2. When this event is received in the plugin, make a call to fetch the contents of the buffer that fired the event

The obvious inefficiency here: fetching the entire contents of the buffer on each change. 

For plugins that want to maintain a shadow buffer, an alternative approach would be to send deltas on a special topic. Consider the following text as an example, the contents of a buffer we are editing:

``` go
package main

import "fmt"

func main() {
    i := 5
    fmt.Printf("
}
```

with the cursor after the `"` on line 7, a position that corresponds to byte offset 62. 

Let us assume that subscribing to events on this special topic causes an initial event to be sent with the contents of the buffer, i.e. the text you see above. The shadow buffer in our plugin is now primed with the contents of the buffer.

Returning to Neovim, if we now press `i` whilst in insert mode, we need to send a delta to the plugin to update the contents of the shadow buffer. What format should this take? There are a few different formats of change:
1. An insertion: `{offset: 62, text: "i", type: "insert"}`
2. A substitution, e.g. `:%s/test/this/g`; in this situation it might be more efficient to send the entire contents of the buffer, lest the delta we send becomes larger in size than the buffer itself
3. ... (probably other types of deltas to list here)

There are a number of benefits to this approach:
- For certain types of events, for example case 1, the overhead of sending deltas vs. the entire buffer is far less
- We save a roundtrip call to fetch the buffer contents, in whole or in part
- If the plugin can be coded to take advantage of deltas, processing effort can be saved. e.g. re-parse a small portion of a file as opposed to the entire file. There is a multiplicative benefit here if other parts of plugin can be coded to take advantage of the deltas from the parse step, etc

Thoughts? 
Is there a better place for this discussion?

**Comment by justinmk** [comment]
Implemented by #7917 / #5269  .
