### ISSUE TITLE
nvim_set_option('foldlevel', 4) gives "Invalid option name"

### ISSUE THREAD

**Issue by norcalli** [neovim/neovim#11179]
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Actual behaviour

`Invalid option name: 'foldlevel'`

### Expected behaviour

It should work.

This problem persists for both the buf and global versions. There may be other options for which this doesn't work, but I would expect it to work or give a better error message.

**Comment by justinmk** [comment]
'foldlevel' is window-local so `nvim_win_set_option()` (not `nvim_set_option()`) is expected. 

> or give a better error message

👍 

We discussed making `nvim_set_option` follow the behave of `:set` or `:setglobal` instead of its current "strict" behavior. And similar for "get" (`nvim_get_option`).

**Comment by RRethy** [comment]
Just encountered this, a better error message would be helpful, I also expected it to work like `set <option>`.

**Comment by ddickstein** [comment]
I'm not seeing this error. Has this been resolved?

**Comment by RRethy** [comment]
Yea I'm not seeing it either, guess it got resolved.
