### ISSUE TITLE
Pasting into command mode on mac deletes some characters

### ISSUE THREAD

**Issue by dylan-chong** [neovim/neovim#11175]
- `nvim --version`:
```
> vi -v
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? - Bug still happens
- Operating system/version: - Mac os 10.14.6
- Terminal name/version: Terminal.app, and Kitty 0.14.4
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Copy the following text: `s/\<\(Entity\|AppleItem)\>/$.&/Ie`
2. Open neovim
3. Press command V to paste the text into the buffer - text should be pasted as expected
4. Press `:` then command V 

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

only the following text gets pasted `s/\/$.&/Ie`

### Expected behaviour

`s/\<\(Entity\|AppleItem)\>/$.&/Ie` should be pasted

**Comment by mhinz** [comment]
This is fixed as of https://github.com/neovim/neovim/issues/11088. The commit is on `master` and was cherry-picked onto the `release-0.4` branch, but you're probably using Homebrew, which doesn't pick up new commits in that branch.
