### ISSUE TITLE
[deps/luajit] Building from source fails on osx 10.15 Catalina

### ISSUE THREAD

**Issue by dm1try** [neovim/neovim#11192]
because of the bundled `luajit` fails to compile
HEAD: `f2ad9316`
```
make distclean
make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/neovim"
```
leads to 
```
==== Building LuaJIT 2.1.0-beta3 ====
/Library/Developer/CommandLineTools/usr/bin/make -C src
BUILDVM   lj_folddef.h
host/buildvm -m folddef -o lj_folddef.h lj_opt_fold.c
make[2]: *** [lj_folddef.h] Segmentation fault: 11
make[2]: *** Deleting file `lj_folddef.h'
make[1]: *** [src/luajit] Error 2
ninja: build stopped: subcommand failed.
make: *** [deps] Error 1
```

**Comment by blueyed** [comment]
Should get reported to https://github.com/LuaJIT/LuaJIT probably.
Can you try if building LuaJIT itself segfaults in the same way?

**Comment by justinmk** [comment]
Looks like the compiler or `make` is crashing. Nothing we can do about that. Try upgrading your tools via homebrew/xcode/etc.

**Comment by zhaozg** [comment]
I hit same things with xcode 11.1

**Comment by justinmk** [comment]
Maybe try installing `ninja` (to avoid `make`), then `rm -rf build .deps && make` (this will automatically use `ninja`).

**Comment by dm1try** [comment]
> I hit same things with xcode 11.1

yep, I forgot to mention this.

> Can you try if building LuaJIT itself segfaults in the same way?

@blueyed it fails too, though I found workaround: set deployment target to `10.14`

so
1. `make distclean`
2. `make MACOSX_DEPLOYMENT_TARGET=10.14`

**Comment by blueyed** [comment]
@dm1try 
Great find, please forward it to LuaJIT.

**Comment by mhinz** [comment]
A more detailed discussion on what is actually broken in the new Xcode. (Hint: It's broken in older Xcode as well but doesn't manifest because of different default compiler settings.)

https://forums.developer.apple.com/thread/121887

Link taken from [this Erlang commit](https://github.com/erlang/otp/pull/2413/commits/46430413dd9b7ccc33675ebff4bc54e971e75c25).
