### ISSUE TITLE
update logo

### ISSUE THREAD

**Issue by ahmedselim2017** [neovim/neovim#11191]
The old logo was very good for 2014 but for now, in my honest opinion, it looks like a little bit curvy at the center because of the usage of the shadow effect and not very much sharp corners so it doesn't look modern as much as other logos around us.  So in my honest opinion, we should use the minimalist and sharper version of old logo like this one from @quark-zju https://github.com/neovim/neovim/issues/43#issuecomment-36830266
![](https://user-images.githubusercontent.com/28633984/66519056-2e840c80-eaef-11e9-8670-c767213c26ba.png)

**Comment by justinmk** [comment]
Wow. I actually like this.

**Comment by mhinz** [comment]
Okay, the shadow effect could be removed, but I prefer the edges being inwards like in the old logo.

This logo also switched the colors, but I like the fact that the green in the old logo forms a `V` (imagine it standing for the Vim origin) and the blue bar got added to form the `N`.

**Comment by justinmk** [comment]
> but I prefer the edges being inwards like in the old logo

The old logo is too "round". And although I like the green V, the blue/teal is a much "deeper" look in this one, and makes the logo much more distinctive.

Anyways this will go nowhere unless someone produces a vectorized asset, plus all of the forms [provided neovim.io website](https://neovim.io/logos/neovim-logos.zip).

**Comment by asheq-svmx** [comment]
Here's a side-by-side for quick comparison:
![image](https://user-images.githubusercontent.com/54650582/66939044-2c421680-eff7-11e9-9986-d5154234170a.png)

Personally, I prefer the octagonal shape of the original because it is appears to be neatly "closed" and symmetrical.

**Comment by Asheq** [comment]
Here's a side-by-side for quick comparison:
![image](https://user-images.githubusercontent.com/54650582/66939044-2c421680-eff7-11e9-9986-d5154234170a.png)

Personally, I prefer the octagonal shape of the original because it appears to be neatly "contained" and symmetrical.

**Comment by kalekseev** [comment]
Two variants were posted by @tonsky a year ago https://twitter.com/nikitonsky/status/1059117704945254402

![DrK97DuW4AU52cD](https://user-images.githubusercontent.com/367259/67332955-6dbb5000-f528-11e9-8d0e-02dc2c11d603.jpeg)
![DrLAO5LWsAEMrye](https://user-images.githubusercontent.com/367259/67332956-6dbb5000-f528-11e9-9963-0a4c116242d3.jpeg)

**Comment by tonsky** [comment]
I’m happy to donate any of the two for public use

**Comment by vezeli** [comment]
Check out https://www.nordax.se/ ("!i nordax bank" search on duckduckgo.com). There is a Nordic bank with a similar logo as Neovim. It is not a good to have trouble with big corporations on accounts of logo "theft" or however the company could look at this issue... Maybe asking for legal opinions or changing the logo?

**Comment by mhinz** [comment]
Maybe they're Nvim fans and created their new logo to look similar on purpose. They probably appreciate the fact that no bank nowadays would work without relying on open source software. How nice of them!

**Comment by blami** [comment]
I still like the original logo the best. Especially in opensource world stable logo is part of lasting identity of project and makes it easier for users to identify project. I'm not against slight re-colors but would keep shape and font intact. Neovim isn't one of those shiny Javascript framework fads that come and go...

**Comment by jetz** [comment]
@kalekseev +1 for the second，it looks like more modern and not so sharp.

**Comment by stringTrimmer** [comment]
Note, VS Code has a wrapping-around-blue-ribbon-like logo that Neovim probably doesn't want to vaguely resemble.

Sorry, I have no skin in the game and it's an old thread, but had a VS Code flashback when I saw the more blue proposal and thought it was worth mentioning.

**Comment by nyngwang** [comment]
I would like to stick to the old one. This is why:

1. The letter V is green. Vim's logo is well-known to be surrounded by green colors.
2. The single blue stroke means a lot for one of the core value of Neovim: We're not going to replace Vim, but extend it. A single blue stroke embodies this meaning.

Sincerely,
NW.

<img src="https://user-images.githubusercontent.com/24765272/234934871-8fb263bd-6e9c-4df1-b419-abdd82f0193f.png" width="500">

**Comment by justinmk** [comment]
Logo refresh would be welcome but the examples shown here aren't a clear improvement. If anyone has the skills to provide a refreshed logo please open a new issue.
