### ISSUE TITLE
Unibilium and termkey not found while compiling v0.4.2

### ISSUE THREAD

**Issue by vincowl** [neovim/neovim#11198]
I am trying to compile neovim v0.4.2 on a linux x86_64 with a kernel 3.18.0-19733-g972ff9adcd38. It is a chromebook Asus C302CA. I am using chromebrew and I am updating the neovim package.

While running `make CMAKE_BUILD_TYPE=RelWithDebInfo` I am facing the following error :

```
CMake Error at cmake/LibFindMacros.cmake:263 (message):
  REQUIRED PACKAGE NOT FOUND

  We only found some files of UNIBILIUM, not all of them.  Perhaps your
  installation is incomplete or maybe we just didn't look in the right place?
  This could also be caused by incompatible version (if it helps, at least
  UNIBILIUM 2.0 should work).  This package is REQUIRED and you need to
  install it or adjust CMake configuration in order to continue building
  nvim.

  Relevant CMake configuration variables:

    UNIBILIUM_INCLUDE_DIR=/usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/.deps/usr/include
    UNIBILIUM_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/FindUNIBILIUM.cmake:12 (libfind_process)
  CMakeLists.txt:411 (find_package)
```
If I run from the build directory `cmake -G 'Ninja' -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUNIBILIUM_LIBRARY=/usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/.deps/usr/lib /usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2`, I get 

```
-- CMAKE_INSTALL_PREFIX=/usr/local
-- CMAKE_BUILD_TYPE=RelWithDebInfo
-- MIN_LOG_LEVEL not specified, default is 1 (INFO)
-- Replacing -O3 in CMAKE_C_FLAGS_RELEASE with -O2
-- Found UNIBILIUM 2.0.0
-- Performing Test UNIBI_HAS_VAR_FROM
WARNING: Target "cmTC_3429e" requests linking to directory "/usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/.deps/usr/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Performing Test UNIBI_HAS_VAR_FROM - Failed
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibTermkey (missing: LIBTERMKEY_LIBRARY) (Required is at
  least version "0.18")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibTermkey.cmake:28 (find_package_handle_standard_args)
  CMakeLists.txt:431 (find_package)
```
Any hint please ?

**Comment by blueyed** [comment]
What do you have in `/usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/.deps/usr/lib`?
(NOTE: that while you pass it in it notes that it will be rejected for unibilium anyway)

**Comment by blueyed** [comment]
Also consider `make distclean && make`, and then paste all of the make output here.

**Comment by vincowl** [comment]
Here is the content of `/usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/.deps/usr/lib` 

```
cmake
libluajit-5.1.a
libluv.a
libmsgpackc.a
libtermkey.la
libunibilium.la
libuv.a
libuv.la
libvterm.la
lua
luarocks
pkgconfig
```

**Comment by vincowl** [comment]
Here is the output of `make distclean && make`

[neovim-0.4.2.log](https://github.com/neovim/neovim/files/3714993/neovim-0.4.2.log)

**Comment by blueyed** [comment]
So you are missing `.a` files.
Have seen this recently in https://github.com/neovim/neovim/pull/11138.
Can you try `make distclean && make LDFLAGS=-static`, please?
That might not have an effect everywhere, but let's see if e.g. libvterm.a shows up then.
If not, please try the patch from #11138 directly, and see if that results in a libvterm.a then.

**Comment by blueyed** [comment]
Also what do those commands show?
```
% libtool --version
% libtool --features
% libtool --config | grep -v '^#' | grep -v '^$'
```

I guess it is somehow related to some system config that does not build static lib archives by default or something similar.

When doing the above rebuilds, also try `make … VERBOSE=1` additionally, and check if the output contains `libvterm.a` then, for example.

**Comment by vincowl** [comment]
libtool is v2.4.6
`libtool --features` produces 
```
host: x86_64-unknown-linux-gnu
enable shared libraries
disable static libraries
```
`libtool --config | grep -v '^#' | grep -v '^$'` gives
```
macro_version=2.4.6
macro_revision=2.4.6
AS="as"
DLLTOOL="false"
OBJDUMP="objdump"
build_libtool_libs=yes
build_old_libs=no
pic_mode=default
fast_install=yes
shared_archive_member_spec=
SHELL="/bin/bash"
ECHO="printf %s\\n"
PATH_SEPARATOR=":"
host_alias=
host=x86_64-unknown-linux-gnu
host_os=linux-gnu
build_alias=
build=x86_64-unknown-linux-gnu
build_os=linux-gnu
SED="/bin/sed"
Xsed="$SED -e 1s/^X//"
GREP="/bin/grep"
EGREP="/bin/grep -E"
FGREP="/bin/grep -F"
NM="/usr/local/bin/nm -B"
LN_S="ln -s"
max_cmd_len=1572864
objext=o
exeext=
lt_unset=unset
SP2NL="tr \\040 \\012"
NL2SP="tr \\015\\012 \\040\\040"
to_host_file_cmd=func_convert_file_noop
to_tool_file_cmd=func_convert_file_noop
deplibs_check_method="pass_all"
file_magic_cmd="\$MAGIC_CMD"
file_magic_glob=""
want_nocaseglob="no"
sharedlib_from_linklib_cmd="printf %s\\n"
AR="ar"
AR_FLAGS="cru"
archiver_list_spec="@"
STRIP="strip"
RANLIB="ranlib"
old_postinstall_cmds="chmod 644 \$oldlib~\$RANLIB \$tool_oldlib"
old_postuninstall_cmds=""
lock_old_archive_extraction=no
LTCC="gcc"
LTCFLAGS="-g -O2"
global_symbol_pipe="sed -n -e 's/^.*[    ]\\([ABCDGIRSTW][ABCDGIRSTW]*\\)[       ][      ]*\\([_A-Za-z][_A-Za-z0-9]*\\)\$/\\1 \\2 \\2/p' | sed '/ __gnu_lto/d'"
global_symbol_to_cdecl="sed -n -e 's/^T .* \\(.*\\)\$/extern int \\1();/p' -e 's/^[ABCDGIRSTW][ABCDGIRSTW]* .* \\(.*\\)\$/extern char \\1;/p'"
global_symbol_to_import=""
global_symbol_to_c_name_address="sed -n -e 's/^: \\(.*\\) .*\$/  {\"\\1\", (void *) 0},/p' -e 's/^[ABCDGIRSTW][ABCDGIRSTW]* .* \\(.*\\)\$/  {\"\\1\", (void *) \\&\\1},/p'"
global_symbol_to_c_name_address_lib_prefix="sed -n -e 's/^: \\(.*\\) .*\$/  {\"\\1\", (void *) 0},/p' -e 's/^[ABCDGIRSTW][ABCDGIRSTW]* .* \\(lib.*\\)\$/  {\"\\1\", (void *) \\&\\1},/p' -e 's/^[ABCDGIRSTW][ABCDGIRSTW]* .* \\(.*\\)\$/  {\"lib\\1\", (void *) \\&\\1},/p'"
nm_interface="BSD nm"
nm_file_list_spec="@"
lt_sysroot=
lt_truncate_bin="/bin/dd bs=4096 count=1"
objdir=.libs
MAGIC_CMD=file
need_locks="no"
MANIFEST_TOOL=":"
DSYMUTIL=""
NMEDIT=""
LIPO=""
OTOOL=""
OTOOL64=""
libext=a
shrext_cmds=".so"
extract_expsyms_cmds=""
variables_saved_for_relink="PATH LD_LIBRARY_PATH LD_RUN_PATH GCC_EXEC_PREFIX COMPILER_PATH LIBRARY_PATH"
need_lib_prefix=no
need_version=no
version_type=linux
runpath_var=LD_RUN_PATH
shlibpath_var=LD_LIBRARY_PATH
shlibpath_overrides_runpath=no
libname_spec="lib\$name"
library_names_spec="\$libname\$release\$shared_ext\$versuffix \$libname\$release\$shared_ext\$major \$libname\$shared_ext"
soname_spec="\$libname\$release\$shared_ext\$major"
install_override_mode=""
postinstall_cmds=""
postuninstall_cmds=""
finish_cmds="PATH=\\\"\\\$PATH:/sbin\\\" ldconfig -n \$libdir"
finish_eval=""
hardcode_into_libs=yes
sys_lib_search_path_spec="/usr/local/lib/gcc/x86_64-cros-linux-gnu/4.9.4 /usr/local/x86_64-cros-linux-gnu/lib64 /usr/local/lib64 /lib64 /usr/lib64 /usr/local/x86_64-cros-linux-gnu/lib /usr/local/lib /lib /usr/lib "
sys_lib_dlsearch_path_spec="/lib /usr/lib /lib64 /usr/lib64 /usr/local/lib64 /lib /usr/lib /usr/local/lib "
configure_time_lt_sys_library_path=""
dlopen_support=yes
dlopen_self=yes
dlopen_self_static=yes
old_striplib="strip --strip-debug"
striplib="strip --strip-unneeded"
LD="/usr/local/x86_64-cros-linux-gnu/bin/ld"
reload_flag=" -r"
reload_cmds="\$LD\$reload_flag -o \$output\$reload_objs"
old_archive_cmds="\$AR \$AR_FLAGS \$oldlib\$oldobjs~\$RANLIB \$tool_oldlib"
CC="gcc"
with_gcc=yes
no_builtin_flag=" -fno-builtin"
pic_flag=" -fPIC -DPIC"
wl="-Wl,"
link_static_flag=""
compiler_c_o="yes"
build_libtool_need_lc=no
allow_libtool_libs_with_static_runtimes=no
export_dynamic_flag_spec="\$wl--export-dynamic"
whole_archive_flag_spec="\$wl--whole-archive\$convenience \$wl--no-whole-archive"
compiler_needs_object="no"
old_archive_from_new_cmds=""
old_archive_from_expsyms_cmds=""
archive_cmds="\$CC -shared \$pic_flag \$libobjs \$deplibs \$compiler_flags \$wl-soname \$wl\$soname -o \$lib"
archive_expsym_cmds="echo \\\"{ global:\\\" > \$output_objdir/\$libname.ver~
            cat \$export_symbols | sed -e \\\"s/\\\\(.*\\\\)/\\\\1;/\\\" >> \$output_objdir/\$libname.ver~
            echo \\\"local: *; };\\\" >> \$output_objdir/\$libname.ver~
            \$CC -shared \$pic_flag \$libobjs \$deplibs \$compiler_flags \$wl-soname \$wl\$soname \$wl-version-script \$wl\$output_objdir/\$libname.ver -o \$lib"
module_cmds=""
module_expsym_cmds=""
with_gnu_ld="yes"
allow_undefined_flag=""
no_undefined_flag=""
hardcode_libdir_flag_spec="\$wl-rpath \$wl\$libdir"
hardcode_libdir_separator=""
hardcode_direct=no
hardcode_direct_absolute=no
hardcode_minus_L=no
hardcode_shlibpath_var=unsupported
hardcode_automatic=no
inherit_rpath=no
link_all_deplibs=unknown
always_export_symbols=no
export_symbols_cmds="\$NM \$libobjs \$convenience | \$global_symbol_pipe | \$SED 's/.* //' | sort | uniq > \$export_symbols"
exclude_expsyms="_GLOBAL_OFFSET_TABLE_|_GLOBAL__F[ID]_.*"
include_expsyms=""
prelink_cmds=""
postlink_cmds=""
file_list_spec=""
hardcode_action=immediate
compiler_lib_search_dirs=""
predep_objects=""
postdep_objects=""
predeps=""
postdeps=""
compiler_lib_search_path=""
```

**Comment by vincowl** [comment]
`make distclean && make LDFLAGS=-static` leads to a fail with following output 
[neovim-0.4.2-static.log](https://github.com/neovim/neovim/files/3715960/neovim-0.4.2-static.log)

**Comment by blueyed** [comment]
> disable static libraries

That's it.  No idea where that comes from / is configured though.

From you log when using `LDFLAGS=-static`:
```
FAILED: libmsgpackc.so.2.0.0
: && /usr/local/bin/cc -fPIC -fPIC -O3 -DNDEBUG  -static -shared -Wl,-soname,libmsgpackc.so.2 -o libmsgpackc.so.2.0.0 CMakeFiles/msgpackc.dir/src/objectc.c.o CMakeFiles/msgpackc.dir/src/unpack.c.o CMakeFiles/msgpackc.dir/src/version.c.o CMakeFiles/msgpackc.dir/src/vrefbuffer.c.o CMakeFiles/msgpackc.dir/src/zone.c.o   && :
/usr/local/bin/ld: /usr/local/lib64/gcc/x86_64-cros-linux-gnu/8.3.0/crtbeginT.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
/usr/local/bin/ld: final link failed: nonrepresentable section on output
```
There also `-shared` is used.
We need to enable it explicitly then maybe.

Please try `make -C .deps/build/src/libvterm CC=/usr/local/bin/cc PREFIX=/path/to/deps/.deps/usr CFLAGS=-fPIC CFLAGS+=-Og CFLAGS+=-g install VERBOSE=1 LDFLAGS=-static`, and check if `libvterm.a` then shows up.

**Comment by blueyed** [comment]
`libtool` is actually a shell script..
Try changing `build_old_libs=no` to `build_old_libs=yes` therein.

This appears to what `-static` does then also:
```
      -static)
	build_libtool_libs=no
	build_old_libs=yes
```
(we just need to figure out how to do this best with all our deps)

**Comment by blueyed** [comment]
Could reproduce when using `build_old_libs=no` in `libtool`.
Affected:

- libtermkey.a
- libunibilium.a
- libvterm.a  (#11138 fixes it)

**Comment by blueyed** [comment]
Please try https://github.com/neovim/neovim/pull/11138 - it should fix this.

**Comment by vincowl** [comment]
Using `make -C .deps/build/src/libvterm CC=/usr/local/bin/cc PREFIX=/path/to/deps/.deps/usr CFLAGS=-fPIC CFLAGS+=-Og CFLAGS+=-g install VERBOSE=1 LDFLAGS=-static` makes `libvterm.a ` show up

**Comment by vincowl** [comment]
Unfortunately, applying #11138  and running `make distclean && make` produces something ending with 
```
-- Build files have been written to: /usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/build
touch build/.ran-cmake
ninja -C build
ninja: Entering directory `build'
[136/310] Linking C executable bin/shell-test
FAILED: bin/shell-test 
: && /usr/local/bin/cc -g  -Wl,--no-undefined   -rdynamic test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o  -o bin/shell-test   && :
/usr/local/bin/ld: test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o: in function `main':
/usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/build/../test/functional/fixtures/shell-test.c:48: undefined reference to `__stack_chk_guard'
/usr/local/bin/ld: /usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/build/../test/functional/fixtures/shell-test.c:138: undefined reference to `__stack_chk_guard'
collect2: error: ld returned 1 exit status
[138/310] Generating auto/unicode_tables.generated.h
ninja: build stopped: subcommand failed.
make: *** [Makefile:86: nvim] Error 1
```

**Comment by blueyed** [comment]
> shell-test.c:138: undefined reference to `__stack_chk_guard'

That's something different / another issue then I think.

**Comment by vincowl** [comment]
Changing `build_old_libs=no` to `build_old_libs=yes` in `libtool` produces the same result. May be the easiest way to change the compilation workflow, rather than using the previous `make` command.

**Comment by blueyed** [comment]
@vincowl 
> Changing `build_old_libs=no` to `build_old_libs=yes` in `libtool` produces the same result.

What do you mean?

> May be the easiest way to change the compilation workflow, rather than using the previous `make` command.

Please elaborate.

Just to be clear: I've meant that `shell-test.c:138: undefined reference to `__stack_chk_guard'` is another/new issue (not clear to me yet, just skipped over https://stackoverflow.com/questions/27290086/gcc-canaries-undefined-reference-to-stack-chk-guard).  It might be related how we're building test fixtures.

**Comment by blueyed** [comment]
@vincowl 
Can you tell where `build_old_libs=no` is coming from?
Is this from your distro?

**Comment by vincowl** [comment]
@blueyed 
> > Changing `build_old_libs=no` to `build_old_libs=yes` in `libtool` produces the same result.
> What do you mean?

Sorry, you're right, my answer is absolutely horrible... I meant that it produces the same result we got with `make -C .deps/build/src/libvterm CC=/usr/local/bin/cc PREFIX=/path/to/deps/.deps/usr CFLAGS=-fPIC CFLAGS+=-Og CFLAGS+=-g install VERBOSE=1 LDFLAGS=-static`. It was quite obvious but since I checked it, I thought it would be better to post it.

> > May be the easiest way to change the compilation workflow, rather than using the previous `make` command.
> Please elaborate.

With the previous clarification, it may be clearer : I just meant that using `libtool` modification seems a lot easier that modifying my compilation process (a chromebrew packaging) which may vary from a CPU architecture to another. But since you commited #2e14dff, both solutions are non-sense for future stable releases. I will just modify my `neovim.rb` chromebrew package for v0.4.2. Hope this is clearer now

> Just to be clear: I've meant that `shell-test.c:138: undefined reference to `__stack_chk_guard'` is another/new issue (not clear to me yet, just skipped over https://stackoverflow.com/questions/27290086/gcc-canaries-undefined-reference-to-stack-chk-guard). It might be related how we're building test fixtures.

I fully understood and was working on the same reference just after my previous post. I didn't want to create a new bug issue if the correction was trivial.

**Comment by vincowl** [comment]
@blueyed 
> Can you tell where `build_old_libs=no` is coming from?
> Is this from your distro?

As said, I am using [chromebrew](https://github.com/skycocker/chromebrew) which is a package manager for chromeOS. Indeed, `libtool` is not a native chromeOS package but is provided by chromebrew. I have checked how libtool's build is configured and found a `./configure --disable-static` like command. I am going to check which impacts it has on other packages and if we can remove it from the `libtool.rb` package or if the `build_old_libs=no` shall be set for `neovim.rb` package. 

So this bug can be closed and I will open a new one for the `__stack_chk_guard`.

**Comment by blueyed** [comment]
Ok, thanks for the clarification / follow-up.
And thanks for reporting this in the first place - we've seen other users reporting the missing-static-lib problem, but it was not clear what was causing that.  Thanks!
