### ISSUE TITLE
dot (•) char not properly cleared with iterm2

### ISSUE THREAD

**Issue by phileagleson** [neovim/neovim#11195]
- nvim --version: v0.4.2
- vim -u DEFAULTS (version: 0.4.2 ) behaves differently? No
- Operating system/version: macOS Catalina v10.15
- Terminal name/version: iTerm2 v3.3.6
- $TERM: screen-256color

### Steps to reproduce using nvim -u NORC:
Open file with :e
Open second file with :e 
Switch to previous buffer with :bp

### Actual behaviour
random characters from the previous buffer are left on screen

### Expected behaviour
screen is redrawn without characters from previous buffer - Note, redraw! does not remove these characters.

**Comment by bfredl** [comment]
> Terminal name/version: iTerm2 v3.3.6
$TERM: screen-256color

Does this mean that screen or tmux was also used? And that it won't reprocuce without screen?

A screenshot of the glitch would be nice.

> Note, redraw! does not remove these characters.

Try `<c-l>` also.

**Comment by phileagleson** [comment]
I'm not familiar with screen and I do have tmux installed but this happens when not using it as well. <c-l> does seem to make it go away, but this seems like it shouldn't be necessary when switching buffers?
Load Buffer 1
![b1](https://user-images.githubusercontent.com/16640725/66590972-eb15b680-eb5f-11e9-94ee-973e3e4055e8.png)

Load Buffer 2
![b2](https://user-images.githubusercontent.com/16640725/66591007-f832a580-eb5f-11e9-98d7-ba3358e36ff9.png)

Switch to Previous Buffer
![bp](https://user-images.githubusercontent.com/16640725/66591034-041e6780-eb60-11e9-8670-bd249fee84d7.png)

you can see I'm the screenshot I'm editing a coc.nvim settings file, but this happens when all plugins are disabled as well.

**Comment by phileagleson** [comment]
> > Terminal name/version: iTerm2 v3.3.6
> > $TERM: screen-256color
> 
> Does this mean that screen or tmux was also used? And that it won't reprocuce without screen?
> 
> A screenshot of the glitch would be nice.
> 
> > Note, redraw! does not remove these characters.
> 
> Try `<c-l>` also.

I just checked $TERM again and got xterm-256color - the previous result must have been while I was in tmux.. sorry for the confusion but the result is the same with or without tmux

**Comment by bfredl** [comment]
Seems to happen on the lines with `•` character. Perhaps nvim and iterm has different ideas of the width of it.

**Comment by phileagleson** [comment]
This issue is resolved. This was an issue with my iTerm2 settings. I changed a bunch of Window and Text settings so I can't say 100% which settings resolved this, but I believe it was unchecking Profile->Text "Use Unicode version 9 widths" and "Ambiguous characters are double-width"
