### ISSUE TITLE
`trim` argument ignored in a heredoc assignment

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#11204]
- `nvim --version`:        NVIM v0.5.0-164-g3b3a40978
 - Vim (version:  8.1 Included patches: 1-2135) behaves differently? Yes
 - Operating system:     Ubuntu 16.04.6 LTS
 - Terminal emulator:    XTerm(322)
 - Shell:                zsh 5.7.1 (x86_64-pc-linux-gnu)

### Steps to reproduce

    $ nvim -es -Nu <(cat <<EOF
    let var =<< trim END
        foo
        bar
        baz
    END
    EOF
    ) +'pu=var|%p|qa!'

### Actual behaviour

This text is printed on the terminal:

        foo
        bar
        baz

### Expected behaviour

This text is printed on the terminal:

    foo
    bar
    baz

### Additional information

The leading whitespace should be trimmed thanks to the `trim` argument.
That's what happens in Vim:

    $ vim -es -Nu <(cat <<EOF
    let var =<< trim END
        foo
        bar
        baz
    END
    EOF
    ) +'pu=var|%p|qa!'

outputs:

    foo
    bar
    baz

---

/cc @jbradaric (via https://github.com/neovim/neovim/pull/11077)

**Comment by blueyed** [comment]
Related missing Vim patches: vim/vim@e7eb92708 (v8.1.1585) and vim/vim@ecaa75b4c (v8.1.1729).

**Comment by jbradaric** [comment]
It seems that the following patches need to be applied:  8.1.1585, 8.1.1625, 8.1.1723, 8.1.1729.
