### ISSUE TITLE
undefined reference to `__stack_chk_guard' while compiling nvim 0.4.2

### ISSUE THREAD

**Issue by vincowl** [neovim/neovim#11228]
I am trying to compile neovim v0.4.2 on a linux x86_64 with a kernel 3.18.0-19733-g972ff9adcd38. It is a chromebook Asus C302CA. I am using chromebrew and I am updating the neovim package.
I am facing this error after solving #11198 
`make distclean && make` produces this error :
```
-- Build files have been written to: /usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/build
touch build/.ran-cmake
ninja -C build
ninja: Entering directory `build'
[136/310] Linking C executable bin/shell-test
FAILED: bin/shell-test 
: && /usr/local/bin/cc -g  -Wl,--no-undefined   -rdynamic test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o  -o bin/shell-test   && :
/usr/local/bin/ld: test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o: in function `main':
/usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/build/../test/functional/fixtures/shell-test.c:48: undefined reference to `__stack_chk_guard'
/usr/local/bin/ld: /usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/build/../test/functional/fixtures/shell-test.c:138: undefined reference to `__stack_chk_guard'
collect2: error: ld returned 1 exit status
[138/310] Generating auto/unicode_tables.generated.h
ninja: build stopped: subcommand failed.
make: *** [Makefile:86: nvim] Error 1
```

**Comment by vincowl** [comment]
Found a solution using :
```
make distclean && make CFLAGS="-fstack-protector-all" LDFLAGS="-fstack-protector-all"
```
Just have to find if it is possible to pass it through `libtool` or not, and if only one option could solve it.

**Comment by vincowl** [comment]
Seems that `make distclean && make CFLAGS="-fstack-protector-all"` is enough

**Comment by blueyed** [comment]
Please post the full build log for the failure, especially with regard to the handling we have already: https://github.com/blueyed/neovim/blob/10bf67b8acc20fb19fa15911606edff50a82a438/CMakeLists.txt#L299-L309

Also it might be interesting if `ninja -C build bin/nvim` fails also already (on a default build), or if it is related to the test fixtures only.

**Comment by blueyed** [comment]
We likely need to improve/fix the `check_c_compiler_flag` there.
You can use `message(STATUS/FATAL_ERROR …)` there to debug things, and `rm build/.ran-cmake && make cmake` to trigger a full re-run of CMake.

**Comment by vincowl** [comment]
Here is the full build log of `make distclean && make` [neovim-0.4.2-fstack.log](https://github.com/neovim/neovim/files/3729040/neovim-0.4.2-fstack.log)
Right after this command, I ran `ninja -C build bin/nvim` (I suppose that's what you wanted to test but it seems odd to me) which produces [ninja.log](https://github.com/neovim/neovim/files/3729050/ninja.log)

**Comment by vincowl** [comment]
> We likely need to improve/fix the `check_c_compiler_flag` there.
> You can use `message(STATUS/FATAL_ERROR …)` there to debug things, and `rm build/.ran-cmake && make cmake` to trigger a full re-run of CMake.

Here is what is told about `check_c_compiler_flag` in the cmake doc :

> Check that the <flag> is accepted by the compiler without a diagnostic. Stores the result in an internal cache entry named <var>.

But even if I am running a UNIX platform, `-fstack-protector-*` must not be set (if I change the `CMakeLists.txt` content with a `add_compile_options(-foo)` instead of `add_compile_options(-fstack-protector-strong)`, everything works like a charm. What I understand from the doc, is that `check_c_compiler_flag`only checks if it is an accepted value by the compiler, nothing more. Then, we should maybe improve the `UNIX` detection to skip this declarations in my case.

**Comment by vincowl** [comment]
I modified `CMakeLists.txt` like this : 
```
if(UNIX)
  # -fstack-protector breaks non Unix builds even in Mingw-w64
  check_c_compiler_flag(-fstack-protector-strong HAS_FSTACK_PROTECTOR_STRONG_FLAG)
  check_c_compiler_flag(-fstack-protector HAS_FSTACK_PROTECTOR_FLAG)
  check_c_compiler_flag(-fstack-protector-all HAS_FSTACK_PROTECTOR_ALL_FLAG)
  
  if(HAS_FSTACK_PROTECTOR_ALL_FLAG)
    add_compile_options(-fstack-protector-all)
  elseif(HAS_FSTACK_PROTECTOR_STRONG_FLAG)
    add_compile_options(-fstack-protector-strong)
  elseif(HAS_FSTACK_PROTECTOR_FLAG)
    add_compile_options(-fstack-protector --param ssp-buffer-size=4)
  endif()
endif()
```
and I have the following result running `make distclean && make`
```
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG_FLAG
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG_FLAG - Success
-- Performing Test HAS_FSTACK_PROTECTOR_FLAG
-- Performing Test HAS_FSTACK_PROTECTOR_FLAG - Success
-- Performing Test HAS_FSTACK_PROTECTOR_ALL_FLAG
-- Performing Test HAS_FSTACK_PROTECTOR_ALL_FLAG - Failure
```
and `-fstack-protector-strong` is found everywhere in the `build.ninja` file. Running `make distclean && make CFLAGS='-fstack-protector-all'` gives 
```
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG_FLAG
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG_FLAG - Success
-- Performing Test HAS_FSTACK_PROTECTOR_FLAG
-- Performing Test HAS_FSTACK_PROTECTOR_FLAG - Success
-- Performing Test HAS_FSTACK_PROTECTOR_ALL_FLAG
-- Performing Test HAS_FSTACK_PROTECTOR_ALL_FLAG - Success
```
and `-fstack-protector-all` is found everywhere twice in the `build.ninja` file.
So where is set the default behavior ? I don't find a trace of it in neovim sources. I think that it is the key...

**Comment by blueyed** [comment]
If you pass in `CFLAGS` it gets used always.  This might be good as a workaround, but we should figure out a way to not require it.

This is really strange:

>   check_c_compiler_flag(-fstack-protector-all HAS_FSTACK_PROTECTOR_ALL_FLAG)
>   Performing Test HAS_FSTACK_PROTECTOR_ALL_FLAG - Failure

For me it also succeeds.
This might indicate that there are flags already, so that this fails.

> and -fstack-protector-all is found everywhere twice in the build.ninja file.

Do you have `-fstack-protector-all` already once there with just `make distclean && make cmake`?
This would indicate that this is used already, and might cause the issue.

Note that `CFLAGS` gets used in the checks:

> Note Since the try_compile() command forwards flags from variables like CMAKE_C_FLAGS, unknown flags in such variables may cause a false negative for this check.
(https://cmake.org/cmake/help/latest/module/CheckCCompilerFlag.html)

For reference, you have:

> -- The C compiler identification is GNU 8.3.0

From gcc's help (9.2.0):

    -fstack-protector           Use propolice as a stack protection method.
    -fstack-protector-all       Use a stack protection method for every function.
    -fstack-protector-explicit  Use stack protection method only for functions with the stack_protect attribute.
    -fstack-protector-strong    Use a smart stack protection method for certain functions.

Do you (or chromebrew) set CLAGS or LDFLAGS already somehow?  (except from when passing it explicitly like mentioned above, of coursE)

Try `message(FATAL_ERROR "CFLAGS=$ENV{CFLAGS} LDFLAGS=$ENV{LDFLAGS}")` at the top of `CMakeLists.txt` and then `rm build -rf && make cmake`.

**Comment by blueyed** [comment]
Try also `make VERBOSE=1` to see all compile commands.  For me it looks like this for shell-test:
```
[3/323] /usr/local/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Iconfig -I../src -isystem ../.deps/usr/include -g   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -MD -MT test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o -MF test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o.d -o test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o   -c ../test/functional/fixtures/shell-test.c
…
[7/323] : && /usr/local/bin/cc -g  -Wl,--no-undefined test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o  -o bin/shell-test   && :
```

**Comment by vincowl** [comment]
> If you pass in `CFLAGS` it gets used always. This might be good as a workaround, but we should figure out a way to not require it.

Fully agree. This hack will be perfect for my very actual need, but if we find a way to solve this cleaner, this would be great.

> This is really strange:
> > check_c_compiler_flag(-fstack-protector-all HAS_FSTACK_PROTECTOR_ALL_FLAG)
> > Performing Test HAS_FSTACK_PROTECTOR_ALL_FLAG - Failure 
> For me it also succeeds.
> This might indicate that there are flags already, so that this fails.
> > and -fstack-protector-all is found everywhere twice in the build.ninja file.

Maybe I wasn't clear enough, but it seems to act as if `-fstack-protector-strong` is set by default. An interesting thing is that it is the default value when `--enable-default-ssp` is set as found in `defaults.h` in gcc sources.
 ```
/* Default value for flag_stack_protect when flag_stack_protect is initialized to -1:                                                                                                          
    --enable-default-ssp: Default flag_stack_protect to -fstack-protector-strong.                                                                                                               
    --disable-default-ssp: Default flag_stack_protect to 0.                                                                                                                                     
*/                                                                                                                                                                                            
#ifdef ENABLE_DEFAULT_SSP                                                                                                                                                                      
# ifndef DEFAULT_FLAG_SSP                                                                                                                                                                      
#  define DEFAULT_FLAG_SSP 3                                                                                                                                                                   
# endif                                                                                                                                                                                        
#else                                                                                                                                                                                          
# define DEFAULT_FLAG_SSP 0                                                                                                                                                                    
#endif  
```
When no argument is passed to make, --fstak-protector-strong is found in build.ninja. When passing an argument, it is duplicated.

> Do you have `-fstack-protector-all` already once there with just `make distclean && make cmake`?
> This would indicate that this is used already, and might cause the issue.

with just `make distclean && make cmake`, `-fstack-protector-strong` is found once in `build.ninja` lines amd in `compile_commands.json`

> Do you (or chromebrew) set CLAGS or LDFLAGS already somehow? (except from when passing it explicitly like mentioned above, of coursE)
> Try `message(FATAL_ERROR "CFLAGS=$ENV{CFLAGS} LDFLAGS=$ENV{LDFLAGS}")` at the top of `CMakeLists.txt` and then `rm build -rf && make cmake`.

This shows nothing relevant here unfortunately... 
```
cd build && cmake -G 'Ninja' -DCMAKE_BUILD_TYPE=Debug  /usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2
CMake Error at CMakeLists.txt:7 (message):
  CFLAGS= LDFLAGS=
```

**Comment by vincowl** [comment]
> Try also `make VERBOSE=1` to see all compile commands. For me it looks like this for shell-test:
> 
> ```
> [3/323] /usr/local/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Iconfig -I../src -isystem ../.deps/usr/include -g   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -MD -MT test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o -MF test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o.d -o test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o   -c ../test/functional/fixtures/shell-test.c
> …
> [7/323] : && /usr/local/bin/cc -g  -Wl,--no-undefined test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o  -o bin/shell-test   && :
> ```

Here is what I get [fstack-make-verbose.log](https://github.com/neovim/neovim/files/3731574/fstack-make-verbose.log)

**Comment by blueyed** [comment]
> When no argument is passed to `make`, `--fstack-protector-strong` is found in `build.ninja`. When passing an argument, it is duplicated.

That's because we're adding it, no?

**Comment by blueyed** [comment]
From the last log:
```
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG_FLAG
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG_FLAG - Success
-- Performing Test HAS_FSTACK_PROTECTOR_ALL_FLAG
-- Performing Test HAS_FSTACK_PROTECTOR_ALL_FLAG - Failed
-- Performing Test HAS_FSTACK_PROTECTOR_FLAG
-- Performing Test HAS_FSTACK_PROTECTOR_FLAG - Success
…
[135/310] /usr/local/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Iconfig -I../src -isystem ../.deps/usr/include -g   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -MD -MT test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o -MF test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o.d -o test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o   -c ../test/functional/fixtures/shell-test.c
[136/310] : && /usr/local/bin/cc -g  -Wl,--no-undefined   -rdynamic test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o  -o bin/shell-test   && :
FAILED: bin/shell-test
: && /usr/local/bin/cc -g  -Wl,--no-undefined   -rdynamic test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o  -o bin/shell-test   && :
/usr/local/bin/ld: test/functional/fixtures/CMakeFiles/shell-test.dir/shell-test.c.o: in function `main':
/usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/build/../test/functional/fixtures/shell-test.c:48: undefined reference to `__stack_chk_guard'
/usr/local/bin/ld: /usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/build/../test/functional/fixtures/shell-test.c:138: undefined reference to `__stack_chk_guard'
collect2: error: ld returned 1 exit status
```

Note that you have your custom addition still there (which might be OK), but
it is still puzzling while it fails, when it makes it work when forced via
`CFLAGS`:

> -- Performing Test HAS_FSTACK_PROTECTOR_ALL_FLAG
> -- Performing Test HAS_FSTACK_PROTECTOR_ALL_FLAG - Failed

Unfortunately I am out of ideas for now.

**Comment by vincowl** [comment]
To be clear, it is not MY custom addition : `-fstack-protector-strong` is not something I add since it fails with it and it requires `-fstack-protector-all` to work. This seems to be something added by default by an unidentified actor.

This is were the duplication thing comes : if I pass it manually it is duplicated. So it must be something here by default since it is not duplicated. I don't know when this `check_c_compiler` stuff occures and on what it applies ? Is it on every command that has to be run (check just before execution and add one last parameter if needed), so this addition could have occured programmatically, or is it run once for all to create a common compilation command which would more likely imply something external. 

Duplication may be related to this gcc's `--enable-default-ssp` stuff : that's the only link I found in my system that tells about `-fstack-protector-strong`. But I can not figure out where and why it is added by default to gcc's commands.

Here is the workflow I follow :
* Download and "unzip" neovim's sources
* Run `make CMAKE_BUILD_TYPE=RelWithDebInfo CFLAGS=-fstack-protector-all` through a chromebrew ruby command. This builds a working nvim binary. I could stop here since it fullfills my needs.
* Play with the created stuff with commands like `make distclean && make` to find out why I must add an argument to my make command to have it work.

I will have a look on what happens if I change the first `CMAKE_BUILD_TYPE` value. Normally it should not have any impact since `make distclean` should erase any locally produced thing and be in a state close to the unzip step.

**Comment by blueyed** [comment]
> This seems to be something added by default by an unidentified actor.

It gets added here: https://github.com/blueyed/neovim/blob/10bf67b8acc20fb19fa15911606edff50a82a438/CMakeLists.txt#L305

**Comment by vincowl** [comment]
Yes, but why `-fstack-protector-all` is not recognized (produces a failure when checked) ? I initially thought `check_c_compiler` parsed the command line but it seems to perform actions at system level. Strange that `-fstack-protector-all` is not recognized since it is while passed manually to make....

**Comment by blueyed** [comment]
Yes, it is strange.
Here it is what it does:https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/CheckCCompilerFlag.cmake

You could try creating `t.c` with `int main(void) { return 0; }`, and then running `gcc -fstack-protector-all t.c` to see if it causes a failure somehow.

**Comment by vincowl** [comment]
Absolutely no error when compiling your `t.c` sample. It is maybe a false negative case as described by [https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/CheckCCompilerFlag.cmake](https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/CheckCCompilerFlag.cmake)
> Since the :command:`try_compile` command forwards flags from variables
> like :variable:`CMAKE_C_FLAGS <CMAKE_<LANG>_FLAGS>`, unknown flags
> in such variables may cause a false negative for this check.

**Comment by blueyed** [comment]
Do you see an error with `gcc -fstack-protector-strong t.c`?
I have CMake 3.15.4 btw.
Can you try a newer gcc or clang maybe?

**Comment by blueyed** [comment]
Oh well.. since it occurs duing linking your `libtool` might be involved here also (again).
Check maybe difference in settings to mine (http://ix.io/1YWM).

**Comment by vincowl** [comment]
I  can't try with a newer gcc, but I tried with clang. No error either.... I already tried with `-fstack-protector-strong` and `-fstack-protector` : no error. Just to be sure, I tried with `-fstack-protector-tmp` which doesn't exist and it sends error....
I am going to have a look at your libtool. Thanks

**Comment by vincowl** [comment]
I had a test using your libtool diffs but could not find a suitable solution. I found diffs in `ld` args and in `gcc` args, but could not manage to solve the problem. Here is my `libtool` : [http://ix.io/1Zvp](http://ix.io/1Zvp)

**Comment by vincowl** [comment]
I have just made a fresh install of chrombrew on my machine to check if this problem is due to a misconfiguration from me. I am now facing a new error while configuring libuv. Cf #11287

**Comment by vincowl** [comment]
I found a solution !
I modified the CMakeLists.txt from 
```
if(UNIX)
     # -fstack-protector breaks non Unix builds even in Mingw-w64
     check_c_compiler_flag(-fstack-protector-strong HAS_FSTACK_PROTECTOR_STRONG_FLAG)
     check_c_compiler_flag(-fstack-protector HAS_FSTACK_PROTECTOR_FLAG)
   
     if(HAS_FSTACK_PROTECTOR_STRONG_FLAG)
         add_compile_options(-fstack-protector-strong)
     elseif(HAS_FSTACK_PROTECTOR_FLAG)
         add_compile_options(-fstack-protector --param ssp-buffer-size=4)
     endif()
endif()
```
to
```
if(UNIX)
     # -fstack-protector breaks non Unix builds even in Mingw-w64
     check_c_compiler_flag(-fstack-protector-strong HAS_FSTACK_PROTECTOR_STRONG_FLAG)
     check_c_compiler_flag(-fstack-protector HAS_FSTACK_PROTECTOR_FLAG)
   
     if(HAS_FSTACK_PROTECTOR_STRONG_FLAG)
         add_compile_options(-fstack-protector-strong)
         link_libraries(-fstack-protector-strong)
     elseif(HAS_FSTACK_PROTECTOR_FLAG)
         add_compile_options(-fstack-protector --param ssp-buffer-size=4)
         link_libraries(-fstack-protector --param ssp-buffer-size=4)
     endif()
endif()
```
`-fstack-protector-strong` was passed to the compilation commands but not to the linking ones. Seems to do the trick using `make distclean && make`
So, shall we provide a PR ?

**Comment by justinmk** [comment]
> So, shall we provide a PR ?

yes, thanks!
