### ISSUE TITLE
Compilation of master with tree_sitter fails

### ISSUE THREAD

**Issue by kekePower** [neovim/neovim#11221]
- `nvim --version`: NVIM v0.4.3-14-g56d941299
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Mageia Cauldron x86_64 (version 8 alpha)
- Terminal name/version: Terminology
- `$TERM`: xterm-256color

Last version I was able to compile is https://github.com/neovim/neovim/commit/8ff2f193bb3ed94ee215c83c13431d45d382949b
The very next commit fails: https://github.com/neovim/neovim/commit/cd100963866b2c33a286cbf6aac8e42cd16fd248

Now I'm getting these messages when compiling: https://kekepower.com/neovim.html
Line breaks inserted by me.

Don't know if this is distribution specific or something else.

I use cmake:
```
cmake -Wno-dev \
-DPREFER_LUA=ON \
-DLUA_PRG=/usr/bin/lua5.3 \
-DCMAKE_BUILD_TYPE=Release \
-DUSE_BUNDLED_LUAJIT=OFF \
-DUSE_BUNDLED=OFF \
-DUSE_SYSTEM_MSGPACK=ON \
-DWITH_PLUGINS=ON \
-DUSE_BUNDLED_LUV=OFF \
-DUSE_SYSTEM_LUV=ON \
-DUSE_BUNDLED_LUAROCKS=OFF \
-DLUA_INCLUDE_DIR=/usr/include
```

**Comment by justinmk** [comment]
try

    rm -rf .deps build
    make

**Comment by bfredl** [comment]
`lua_setfenv` error seems like it could be the wrong lua version. 

@kekePower are you building with lua5.1 or luajit libs? (LUA_PRG can be 5.3 AFAIK, but linked lua libs should be 5.1 or luajit)
