### ISSUE TITLE
lua/python/…: "q" can not quit the pager

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#11224]
- `nvim --version`: v0.5.0-68-gfe9d54f41
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: macos
- Terminal name/version: alacritty
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

1. nvim -u NONE
2. :lua print(vim.inspect(vim))
3. `q` can not quit the pager

### Expected behaviour
`q` should quit the pager

**Comment by blueyed** [comment]
Reminded me of / similar to https://github.com/neovim/neovim/issues/10923 (fixed in https://github.com/neovim/neovim/pull/10926).

**Comment by blueyed** [comment]
Simpler test case: `:exe 'py print("a\n" * '.&lines*3.')'`.

**Comment by blueyed** [comment]
WIP for Neovim at: https://github.com/neovim/neovim/pull/11226 - please check if that's what you would expected.  For once it adds the non-displayed message triggering the prompt to the history (which is okish), but not the following ones (which is good).

**Comment by zgpio** [comment]
Unfortunately, I don't follow HEAD. If this is merged, I would love to download the nightly build for testing and feedback.
