### ISSUE TITLE
command `:call CompileRunGcc()` bug

### ISSUE THREAD

**Issue by 66RING** [neovim/neovim#11223]
- `nvim --version`: 
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
-vim -u DEFAULTS (version: 8.1 + patches 1-2136) behaves differently? 
Yes, vim v8.2 is all right
- Operating system/version: macOS Catalina
- Terminal name/version: 
iTerm 3.3.6 and macOS Terminal
- `$TERM`:
xterm-256color

Here is my  CompileRunGcc()
```  
map <F5> :call CompileRunGcc()<CR>
func! CompileRunGcc()
    exec "w" 
    if &filetype == 'c' 
        exec '!g++ % -o %<'
        exec '!time ./%<'
```
When I press <F5>, it should complie and run a C program.
But if there is a `scanf` in this C program, it return immediately before I input something.

### Actual behaviour
Here is the test code.
``` c
#include<stdio.h>
int main(){
    int a;
    scanf("%d",&a);
    printf("%d",a);
    return 0;
}
```
return immediately 
```
"a.cpp" 7L, 97C written
:!g++ a.cpp -o a

:!time ./a
340627493./a  0.00s user 0.00s system 44% cpu 0.005 total
```

### Expected behaviour
It should wait until I input, and then print and return.

run with VIM v8.2
```
Press ENTER or type command to continue
1
1./a  0.00s user 0.00s system 0% cpu 1.013 total

Press ENTER or type command to continue
```

**Comment by justinmk** [comment]
> It should wait until I input, and then print and return.

https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes
