### ISSUE TITLE
Mac: Terminal pasted control character get printed instead  of execute 

### ISSUE THREAD

**Issue by zk4** [neovim/neovim#11227]
- `nvim --version`:  NVIM v0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version:  10.12.6
- Terminal name/version:  kitty 0.14.6
- `$TERM`:  xterm-kitty

I bind `<Command-s>` key  to send  `\3:w`  to nvim from terminal. 
```
# terminal python script 
 window.paste("\x03:w") 
```
When I edit a file `nvim  test.txt` ,then pressed `<Command+s>`, it should save the file. Works fine with `nvim 0.3.2 ~ 0.3.7`. But after I upgraded nvim to 0.4.2

### Actual behaviour
It print  `^C:w`  out as text.  
### Expected behaviour
nvim go back to normal mode, and save the current file.

**Comment by blueyed** [comment]
Duplicate of https://github.com/neovim/neovim/issues/11088?
Can you test the nightly?

> # terminal python script 
>  window.paste("\x03:w")

What's `window` here?

**Comment by zk4** [comment]
> Duplicate of #11088?
> Can you test the nightly?
> 
> > ```
> > # terminal python script 
> > window.paste("\x03:w")
> > ```
> 
> What's `window` here?


`window` a kitty terminal window.    The full kitty script looks like this 
mykitten.py
``` python
import time
def main(args):
   pass

def handle_result(args, answer, target_window_id, boss):
    w = boss.window_id_map.get(target_window_id)
    if w is not  None:
      w.paste("\x03")
      time.sleep(0.005)
      arg= args[1]
      if len(arg)>3 and arg[-2:] =="\\r":
          w.paste(arg[:-2]+"\r")
      elif len(arg)>4 and arg[:4] =="\\x20":
          w.paste("\x20"+arg[4:])
      else:
          w.paste(args[1])
 
handle_result.no_ui = True

```
Define binging in kitty .conf
``` python
map cmd+s kitten mykitten.py  ":w\r"
```
I testj

## test on NVIM v0.5.0-95-g2e14dffbb
Problem still exists.
 
![2019-10-15 11 53 17](https://user-images.githubusercontent.com/996674/66799130-7a491280-ef42-11e9-803d-b24677a6501a.gif)

**Comment by bfredl** [comment]
This is the expected behavior for "paste" action. probably kitty window has a send() method or something, which you should use instead of paste().

**Comment by zk4** [comment]
I think @bfredl  is right .  Changing `paste` to  `write_to_child`  works in lastest nvim.
