### ISSUE TITLE
CI/automation: use clang-format

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#11236]
Up to now we manually format the code because (1) we wanted to avoid big cosmetic changes, and (2) style was decided in 2014 after a big discussion. 

But we have changed most of the codebase since then, so "big cosmetic changes" are mostly done by now. Automating the style makes much more sense.

TODO:

- [ ] configure/revisit style with regard to running it across the whole codebase.
      There is `.clang-format` already, but maybe it could need some tweaking, e.g.
      with regard to not unnecessarily wrapping function arguments.

  ```diff
  @ src/nvim/quickfix.c:4416 @ static qfline_T *qf_find_closest_entry(qf_list_T *qfl,
    * Get the nth quickfix entry below the specified entry treating multiple
    * entries on a single line as one. Searches forward in the list.
    */
  -static qfline_T *qf_get_nth_below_entry(qfline_T *entry, int *errornr, linenr_T n)
  +static qfline_T *qf_get_nth_below_entry(qfline_T *entry,
  +                                        int *errornr,
  +                                        linenr_T n)
   {
     while (n-- > 0 && !got_int) {
       qfline_T *first_entry = entry;

  ```

  ```diff
  @ src/nvim/quickfix.c:6170 @ void ex_cbuffer(exarg_T *eap)

     au_name = cbuffer_get_auname(eap->cmdidx);
     if (au_name != NULL
  -      && apply_autocmds(EVENT_QUICKFIXCMDPRE, au_name,
  -                        curbuf->b_fname, true, curbuf)) {
  +      && apply_autocmds(EVENT_QUICKFIXCMDPRE, au_name, curbuf->b_fname, true,
  +                        curbuf)) {
       if (aborting()) {
         return;
       }
  ```

   
  Ref:
  ```
    --style=<string>           - Coding style, currently supports:
                                   LLVM, Google, Chromium, Mozilla, WebKit.
                                 Use -style=file to load style configuration from
                                 .clang-format file located in one of the parent
                                 directories of the source file (or current
                                 directory for stdin).
                                 Use -style="{key: value, ...}" to set specific
                                 parameters, e.g.:
                                   -style="{BasedOnStyle: llvm, IndentWidth: 8}"
  ```

- [ ] provide `.gitblameignore` file to be used with `git config --local blame.ignoreRevsFile .gitblameignore` then?

_Originally posted by @justinmk in https://github.com/neovim/neovim/pull/11119#issuecomment-537358288_

**Comment by justinmk** [comment]
### Problem

Formatting is tedious, undifferentiated effort.

### Solution

Relax/change some of our lint rules so that clang-format "just works". Move away from [clint.py](https://github.com/neovim/neovim/blob/22b538139606321bb1083665c510e81adb3d6670/src/clint.py).

proposed ideas, ordered by effort:

- provide a make/cmake bulid task that runs clang-format
- provide a git pre-commit hook that performs auto-formatting
- move away from `clint.py`: use a CI job like @jgehrig did for neovim-qt: https://github.com/equalsraf/neovim-qt/pull/859
    - this allows clang-format to own our lint rules
    - > Moving Clazy check to GitHub Actions.
      > 
      > Adding a new CI rule that checks Pull Requests for clang-format
      > compliance. It will only apply to changed lines in Pull Requests.
      > 
      > The rule operates by analyzing the git diff since the PR fork-point. The
      > computed diff is piped into clang-format-diff.py, and the CI fails if
      > any clang-format differences are detected.
      > 
      > The PR author can apply the results:
      > 
      > * Downloading a clang_format.patch Artifact
      > * Adding a "auto-commit" label, commits will be auto-applied
      > * Locally running contrib/clang-format-diff.sh (Linux/Mac).
      > 
      > This rule will only run for PRs, so we won't get noise for violations of
      > the existing code. We can also safely ignore clang-format, if manual
      > formatting is desired.




related: https://github.com/neovim/neovim/issues/6226

**Comment by dundargoc** [comment]
@justinmk We can close this, no?

**Comment by dundargoc** [comment]
Closing as we've decided to use `uncrustify` as our current formatter of choice.
