### ISSUE TITLE
build: move src/nvim/xdiff to src/xdiff ?

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#11239]
This would be more in line with where we've put `tree_sitter`, and would not require us to exclude / handle it in a special way from `src/nvim/CMakeLists.txt`.

**Comment by justinmk** [comment]
That was [my preference](https://github.com/neovim/neovim/pull/9306#issuecomment-443606377)  but there was some friction https://github.com/neovim/neovim/pull/9306#issuecomment-443871444 :

> it would be a little bit tricky to build the library separately:
>
> - src/nvim needs to link the executable with xdiff
> - src/xdiff would need to reach generated headers for memory.c (specifically, `x{m,re}alloc`, `xfree` signatures) to be built

However, maybe those comments only apply to the "separate CMake project" suggestion. So moving to `src/xdiff/` might be ok.

**Comment by clason** [comment]
@lewis6991 you're currently touching `xdiff` -- any opinions?

**Comment by lewis6991** [comment]
Seems like a logical change if it makes the cmake lists easier to manage. Otherwise not any strong opinions.

**Comment by clason** [comment]
Can be done in conjunction with porting https://github.com/vim/vim/pull/8431 when ready (as separate commits, of course).
