### ISSUE TITLE
[FR] Make working with buffers better

### ISSUE THREAD

**Issue by ReekyMarko** [neovim/neovim#11235]
Moving between windows is pretty intuitive:
```
<C-w> h|j|k|l|
```
And you can close a window with
```
<C-w> c
```

But for buffers we only have `:bn :bp :bc` etc. I suggest we add keybindings following the logic of windows:
```
<C-b> h|l
```
And for closing buffers:
```
<C-b> c
```

`<C-b>` doesn't seem to be binded to anything currently, at least from my own testing but I could be wrong

**Comment by justinmk** [comment]
> `<C-b>` doesn't seem to be binded to anything currently, at least from my own testing but I could be wrong

    :h CTRL-B

> And for closing buffers:

I would suggest `ZB`, in analogy with `ZZ` and `ZQ`. That's covered by other tickets.

> Moving between windows is pretty intuitive:

I use this mapping:

    nnoremap <C-b> :set nomore<bar>ls<bar>set more<cr>:buffer<space>

And `]b` / `[b` from https://github.com/tpope/vim-unimpaired
