### ISSUE TITLE
vim-patch 8.0.1287 not required

### ISSUE THREAD

**Issue by dvejmz** [neovim/neovim#11241]
I had a look at vim-8.0.1287 and I don't think it applies to Neovim as Neovim uses the ShaDa file instead, which utilises a different implementation. I don't really know if ShaDa is also susceptible to the same issue but that would be a separate piece, I guess.

```
commit aeeb6888ca3ee5122793b37c5aacc6c960b02c37
Author: Bram Moolenaar <Bram@vim.org>
Date:   Sat Nov 11 16:45:19 2017 +0100

    patch 8.0.1287: temp file used for viminfo may have wrong permissions
    
    Problem:    The temp file used when updating the viminfo file may have the
                wrong permissions if setting the group fails.
    Solution:   Check if the group matches and reduce permissions if not.
```
https://github.com/vim/vim/commit/aeeb6888ca3ee5122793b37c5aacc6c960b02c37

**Comment by blueyed** [comment]
Thanks!
Please add it to https://github.com/neovim/neovim/pull/11160 then (as a new comment for yourself (and further additions)).

> I don't really know if ShaDa is also susceptible to the same issue but that would be a separate piece, I guess.

Yes, the patch as-is would not apply, but it would be great to check if we're affected by the same.
Code appears to be here: https://github.com/neovim/neovim/blob/10bf67b8acc20fb19fa15911606edff50a82a438/src/nvim/shada.c#L3131-L3157
