### ISSUE TITLE
`shortmess` option `s` appears to be automatically set by `S`

### ISSUE THREAD

**Issue by lewisthompson** [neovim/neovim#11243]
NVIM 0.4.2
macOS 10.15
Invoked with `nvim -u DEFAULTS -u NORC`

From `help shm`:

```
          s     don't give "search hit BOTTOM, continuing at TOP" or "search
                hit TOP, continuing at BOTTOM" messages; when using the search
                count do not show "W" after the count message (see S below)
[...]
          S     do not show search count message when searching, e.g.
                "[1/5]"
```

I would expect that with `shm=` I would see `[n/N]` counter, the `W` for wrap and `search hit BOTTOM, continuing at TOP` or similar when searching & wrapping.

My experiments show:

`set shm=` -> `[n/N]` counter bottom-right & `W` when wrapping (no `search hit BOTTOM...`)
`set shm=s` -> `[n/N]` counter only
`set shm=S` -> `search hit BOTTOM, continuing at TOP` only
`set shm=sS` -> no indication

It looks as though when neither `s` nor `S` is set the `search hit BOTTOM` behaviour is incorrectly disabled?

**Comment by blueyed** [comment]
Also happens with Vim (8.1.2102).
Maybe the idea is to not require this with the search count message?  But it should be reflected in the documentation then at least.

The code for the warning is hit (checked with `abort()`): https://github.com/neovim/neovim/blob/ae7f2c38ff91c52eb4ce918518ad014b501aa3c4/src/nvim/search.c#L888-L891.
So likely it gets overwritten maybe?

Yeah.  Doing `echom "===="` before `n` with `shm=` shows in `:mess` later:
```
====
search hit BOTTOM, continuing at TOP
search hit BOTTOM, continuing at TOP
search hit BOTTOM, continuing at TOP
/script                                                                    [1/1]
```
So there are 3 warnings even?  (also with `-Nu NONE`, and in Vim)

**Comment by blueyed** [comment]
> It looks as though when neither s nor S is set the search hit BOTTOM behaviour is incorrectly disabled?

Like said above it is not really disabled, but the search stats overwrite it, and "W" indicates instead that it wrapped.
I think that's good, isn't it?

**Comment by lewisthompson** [comment]
I'd strongly prefer both and if I had to choose would go for the legacy behaviour, even at the cost of losing the `[n/N]` indicator.

The `search hit BOTTOM, continuing at TOP` message is so much more obvious, especially when running in a large window where I'm often not keeping a close eye on the very bottom right of the screen -- I generally look there when I am specifically trying to find some info (`ft`, `enc`, etc.)

**Comment by blueyed** [comment]
I see.
So you would prefer to have the show_top_bot_msg overwrite the stats then?
Would look like this then: https://github.com/neovim/neovim/pull/11244/commits/f68c32858d9c9d0ffda258598de5e9aca5c3882f

**Comment by blueyed** [comment]
As for me, I think the cursor not moving, and having an indicator is good.
But then I am also not using `wrapscan` in the first place.. :man_shrugging: :)

**Comment by lewisthompson** [comment]
> Would look like this then: [f68c328](https://github.com/neovim/neovim/commit/f68c32858d9c9d0ffda258598de5e9aca5c3882f) (where it skips displaying stats in the first place)

I can't quite tell from the diff exactly what the behaviour would be.  Is this just for the wrap case?  i.e. I would see the `[n/N]` except when a wrap occurs then the legacy behaviour?  If so, yes, to me this would be an improvement.

Presumably it is not possible to show both because `search hit BOTTOM, continuing at TOP` is a message and `[n/N]` is not?

**Comment by blueyed** [comment]
> I can't quite tell from the diff exactly what the behaviour would be.

But from the (changed) test maybe? :)

Both are messages.
You can see the other when looking at `:mess`.

**Comment by justinmk** [comment]
This is being discussed upstream, let's not spend time on it here.

**Comment by blueyed** [comment]
A reference might be useful - but we have #11244, where I've pinged Bram and Chris.

**Comment by neilweidinger** [comment]
Hi, the original effects of the various settings of `shortmess` that @lewisthompson pointed out still seem to be happening. Is it still not possible to have both `search hit BOTTOM, continuing at TOP` and `[n/N]`? Am I just misunderstanding the documentation and is this expected behavior? This is also the case in Vim. Thanks!

**Comment by mlindner** [comment]
I'm still getting this behavior. Please reopen this.

**Comment by bfredl** [comment]
Is there a vim patch? or did vim upstream think it is WONTFIX?

**Comment by johnnovak** [comment]
+1
I don't see any reasons why this is not supported, I also want "sS" to work (so I want both "search hit BOTTOM, continuing at TOP", which is super useful, AND the counter in the bottom-right corner, which is useful as well)
