### ISSUE TITLE
:lang is broken on Windows

### ISSUE THREAD

**Issue by Rantanen** [neovim/neovim#11251]
- `nvim --version`: NVIM v0.4.2 (Latest Chocolatey package)
- `vim -u DEFAULTS` (version: 8.0): Gives `E282: Cannot read from "DEFAULTS"` error
- Operating system/version: Windows 10, Version 1903
- Terminal name/version: PowerShell
- `$TERM`: Does not exist

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:lang en
:lang
```

### Actual behaviour

Results in:
```
Käytössä oleva kieli: LC_COLLATE=en_US;LC_CTYPE=en_US;LC_MONETARY=en_US;LC_NUMERIC=C;LC_TIME=en_US
```

### Expected behaviour

```
Current language: LC_COLLATE=en_US;LC_CTYPE=en_US;LC_MONETARY=en_US;LC_NUMERIC=C;LC_TIME=en_US
```

(I don't actually know _if_ that language should change on the fly and no idea how to specify `lang` before nvim start when using `-u NORC`)

I've had the following in my init.vim since Vim 7.4 or so:

```
set langmenu=none
set $lang='en'
language en_US
```

After I upgraded today from 0.3.x to the current 0.4.2 package on Chocolatey, the language changed to Finnish and I haven't found a way to change it back.

I've now worked around this issue by renaming the `fi` locale directory under `neovim\Neovim\share\locale` into `_fi` to prevent nvim from finding it.

**Comment by justinmk** [comment]
`:set $lang` is invalid, not sure what you expect that to do. If you do

    :lang <tab>

what languages are shown?

**Comment by Rantanen** [comment]
```
:lang <tab>
```
Shows `ctype` `messages` `time`. Interestingly this seems to differ from Linux, where it does show the available languages.

Yeah, I had a feeling something had changed in Neovim to make things "work" - however I'm now struggling to find the option to disable that.

(And yeah, `set $lang` was a typo on the `set` part. Should have been `let` - and even then I don't really know what to expect of that. It's something I've randomly thrown in because the internet said so. Never really looked into what each of those settings would do since they were working.) :)

It seems like the settings in `init.vim` don't effect anything anymore when it comes to the actual language that gets loaded. I can change the language by setting the `LANG` environmental variable before starting nvim.

**Comment by Rantanen** [comment]
Was this closed on purpose? I still find it a bug that the settings don't have an effect on this. Is it intended that the only way to change the language is to set the environmental parameter before starting nvim?

**Comment by justinmk** [comment]
> ```
> :lang <tab>
> ```
> 
> Shows `ctype` `messages` `time`. 

Yeah that's wrong. I can reproduce this on Windows 10 with `nvim.exe` (TUI) in cmd.exe as well as neovim-qt (GUI).

**Comment by erw7** [comment]
> ```
> :lang <tab>
> ```
> Shows ctype messages time.

Windows `vim` does the same completion.
