### ISSUE TITLE
Terminal :hardcopy with colors

### ISSUE THREAD

**Issue by artem-nefedov** [neovim/neovim#11252]
Is it feasible to make `:hardcopy` preserve colors from a terminal buffer?

**Comment by bfredl** [comment]
hardcopy feature is not really maintained, we usually recommend :TOhtml as an alternative.

Directly `:TOhtml` doesn't seem to work, but `:file somename` and then `:TOHtml` works. We should fix that at least.

**Comment by artem-nefedov** [comment]
> `:file somename` and then `:TOHtml`

This also yields colorless output for me.

**Comment by lf-** [comment]
There's a couple of things that will cause hardcopy to not emit colours that I can think of immediately:

* a nvim defect: `:hardcopy` simply doesn't look at `fg#` so if you use true colour in your theme, it will not emit colour. it will respect bold, however. I am considering fixing this defect.
* nvim-treesitter highlight is enabled for the buffer

**Comment by lf-** [comment]
Fixed the above-mentioned defect in #17525 so it will respect gui colours if present.

**Comment by lewis6991** [comment]
`:hardcopy` is now removed
