### ISSUE TITLE
Allow to remap ! to terminal

### ISSUE THREAD

**Issue by raindev** [neovim/neovim#11260]
`:terminal` effectively replaces `:!` in Neovim and `:!` is no longer interactive (see #1496). It would ease transition to Neovim for people that incorporated shelling out to external commands from Vim into their workflow (e.g. `:!git log`) if it would be possible to remap `:!cmd` to execute `cmd` in Neovim's terminal.

Currently `:command! ! terminal` results in `E182: Invalid command name`. If remapping  bang is not feasible for some reason, `:cabbrev` might also be an option. As of now the problems with creating an abbreviation is that it's expanded anywhere in command line mode, which undesirable, and requires `<Space>` or `<C-]>` to be expanded.

```
:version
NVIM v0.2.2
```

**Comment by bfredl** [comment]
It is planned https://github.com/neovim/neovim/pull/10842

**Comment by raindev** [comment]
This is great! It didn't occur to me to search pull requests in addition to the issues. Thanks for working on this Björn!
