### ISSUE TITLE
neovim in diff mode doesn't draw itself correctly in gnome-terminal

### ISSUE THREAD

**Issue by Leonid99** [neovim/neovim#11278]
https://bugzilla.redhat.com/show_bug.cgi?id=1764236

- `nvim --version`:
```NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/build/BUILD/neovim-0.4.2/build/config -I/builddir/build/BUILD/neovim-0.4.2/src -I/usr/include -I/usr/include/lua-5.1 -I/builddir/build/BUILD/neovim-0.4.2/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.4.2/build/include
Compiled by mockbuild

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Linux, Fedora 31
- Terminal name/version: gnome-terminal-3.34.1-1.fc31.x86_64, xfce4-terminal-0.8.8-2.fc31.x86_64
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`
- Find two files that have differences with enough distance between them not to fit on one screen.
- `nvim -f -d file1 file2`
- Press `]c` to jump from the first difference to another, while redrawing the entire screen.

### Actual behaviour
The window is garbled (attaching screenshot).

### Expected behaviour
The window isn't garbled.

### Additional info
This reproduces in gnome-terminal, xfce4-terminal, but not in xterm and rxvt, so the problem is somewhere between neovim, vte and the new gnome, but I can't determine which of them is actually guilty.

**Comment by Leonid99** [comment]
I can't upload the screenshot, so I posted it on imgur: https://imgur.com/a/NKTR0Hs

**Comment by Leonid99** [comment]
Doesn't reproduce with `nvim.appimage` v0.5.0-113-g02393a0c7.

**Comment by Leonid99** [comment]
Does reproduce with `nvim.appimage` v0.4.2

**Comment by agriffis** [comment]
This reproduces for me on [alacritty](https://github.com/jwilm/alacritty) with the latest nightly build of [neovim from COPR](https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/builds/)

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/10448

see also

    :help $TERM

**Comment by Leonid99** [comment]
Interesting. That bug was closed by the reporter because they found a workaround. I'll check tomorrow whether it reproduces with `TERM=gnome-256color` on 0.4.2, but even if it doesn't, arguably it's still a regression, so I'll defer it to devs to decide what to do with this bug.

**Comment by blueyed** [comment]
> Doesn't reproduce with `nvim.appimage` v0.5.0-113-g02393a0c7.

So it's fixed, isn't it?
Might also be due to #11132. 

Please try the release-0.4 branch if you can.

**Comment by blueyed** [comment]
Closes as fixed, but please consider reporting back anyway.. :)
