### ISSUE TITLE
Adding automaticly an extra comma for C and Cpp files

### ISSUE THREAD

**Issue by DiantArts** [neovim/neovim#11272]
Hi,

I'm trying to bind an extra comma to my <CR> when needed

For that, I've done some imap that works individually, but no together:

1. `autocmd FileType c,cpp imap <expr> ; strpart(getline('.'), col('.')-1, 1) == ";" ? "\<Right>" : ";"`
2. `autocmd FileType c,cpp imap <expr> <CR> virtcol('.') < 2 ? "" : ";<Left>"`
3. `autocmd FileType c,cpp imap <expr> <CR> <CR><C-f>`

(btw <C-f> is my auto indent)

The problem now is that it's really hard to merge the second and the third one. It would be great if something like the following code would work, but it doesn't...
`autocmd FileType c,cpp imap <expr> <CR> <CR><C-f>virtcol('.') < 2 ? "" : ";<Left>"`

Well, for now i'm blocked... Any idea ?

Thanks in advence

PS: sorry for my lack of english/github

-------

- NVIM v0.4.2
- Linux version 5.3.7-arch1-1-ARCH
- XTerm(349)

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
