### ISSUE TITLE
<c-/> causes a beep

### ISSUE THREAD

**Issue by eyalk5** [neovim/neovim#11270]
- `nvim --version`:
NVIM v0.4.0-1989-g754ea8d27
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

- `vim -u DEFAULTS` (version: ) behaves differently? yes. It does beep on terminal.
- Operating system/version: High Sierra 
- Terminal name/version: neovim-qt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

Well, I believe you can't reproduce this. This only happens on neovim-qt. Yet, it is possible that this is a bug of neovim. 
NVIM doesn't allow to map \<c-/\> unless you use \<c-v\> to get ^_ and map it. That is not that bad.

### Actual behaviour
On neovim-qt on the other hand, with -u NONE , when you hit \<c-/\>  , you get a beep alonside a search.  

### Expected behaviour

Shouldn't beep on it, or at least let me control beeps. 
`set noerrorbells visualbell t_vb=` doesn't have an effect. 

Beside, allow me map it the usual way.

Related issue: https://github.com/equalsraf/neovim-qt/issues/598

**Comment by justinmk** [comment]
> Well, I believe you can't reproduce this

    :call nvim_input('<c-/>')

**Comment by eyalk5** [comment]
Well, sorry mapping <c-/> works in nvim in the terminal. I remembered incorrectly.

**Comment by glacambre** [comment]
Neovim doesn't beep for me on master, whether I use the TUI or Firenvim. @eyalk5 if you're still encountering this problem, I would recommend you open an issue in the Neovim-Qt repo :).
