### ISSUE TITLE
WinEnter, WinLeave and maybe some other events do not trigger for command-line windows

### ISSUE THREAD

**Issue by monkoose** [neovim/neovim#11279]
- `nvim --version`: NVIM v0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Archlinux
- Terminal name/version: kitty
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`
Add this command in `init.vim` or after you start neovim
```
autocmd WinEnter * echom 'foo'
autocmd WinLeave * echom 'bar'
```
Enter `command-line windows` with `q:`, then `:mes` and you will see that there is no messages not only for WinEnter into `command-line window`, but even for leaving your current window. Then you can close `command-line window` with `:q` and still there is nothing echoed. You can repeat it as long as you want without any result.

Tested with `nvim --clean`

### Actual behaviour
`WinLeave` and `WinEnter` autocommands do not trigger for `command-line window`.

### Expected behaviour
They should trigger. Read some investigation on reddit [https://www.reddit.com/r/vim/comments/dlxrc6/commandline_windows_behavior/](https://www.reddit.com/r/vim/comments/dlxrc6/commandline_windows_behavior/)

**Comment by justinmk** [comment]
Sounds familiar, might be a missing vim patch.

**Comment by dnebauer** [comment]
nvim --version: NVIM v0.3.8
Operating system/version: Debian/testing
Terminal name/version: konsole
$TERM: screen-256color

I discovered this bug when a BufReadPost event failed to trigger an associated autocmd, confirmed using the "Steps to reproduce using nvim -u NORC" above, replacing the `WinEnter` event with `BufReadPost`.

The problem also occurs with nvim-qt.

**Comment by justinmk** [comment]
@dnebauer v0.3.8 is very old, so even if this were fixed it wouldn't help you. Try updating.

Meanwhile, waiting for someone to find the related vim patch.

**Comment by dnebauer** [comment]
v0.3.8 is the version currently in debian/testing. The version in unstable is 0.4.2 but its migration to testing has been held up because it introduced [a regression](https://tracker.debian.org/pkg/neovim). I figure the package maintainers know better than me when it is safe to update. I thank you for your concern, though.

I had thought this bug in nvim's event triggering might have been given a higher priority as it must surely be silently breaking a lot of configurations, and it's a sneaky bug to track down. (At least, it was for me.)

**Comment by blueyed** [comment]
The regression there appears to be with/due to python-neovim?  /cc @jamessan

**Comment by blueyed** [comment]
Found it: https://github.com/neovim/neovim/pull/11479

**Comment by monkoose** [comment]
@blueyed cool. Thank you.

**Comment by bfredl** [comment]
@blueyed pynvim 0.3.0 has a well known problem with nvim 0.4.x, fixed/worked-around in pynvim 0.4.0. (Though the root cause breakage is in nvim itself, if we make 0.4.4 we should backport #11445 )

**Comment by jamessan** [comment]
> The regression there appears to be with/due to python-neovim?

Yeah, I'm working on getting access to the python-neovim package so I can update it.

**Comment by justinmk** [comment]
> I had thought this bug in nvim's event triggering might have been given a higher priority as it must surely be silently breaking a lot of configurations, and it's a sneaky bug to track down

It's not a regression, and was intentional (in Vim) until  very recently: https://github.com/vim/vim/commit/96e38a86a710fb6daec4550ac1667f019dc3a40e#diff-570936afc3e77a78cc250972799741baL1174
