### ISSUE TITLE
Libuv configuration error while compiling neovim 0.4.2

### ISSUE THREAD

**Issue by vincowl** [neovim/neovim#11287]
While trying to compile neovim 0.4.2 on a chromebook using chromebrew (arch x86_64), I have the following error occuring during the libuv's configuration

```
[49/89] Performing configure step for 'libuv'
FAILED: build/src/libuv-stamp/libuv-configure 
cd /usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/.deps/build/src/libuv-build && sh /usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/.deps/build/src/libuv/autogen.sh && /usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/.deps/build/src/libuv/configure --with-pic --disable-shared --prefix=/usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/.deps/usr --libdir=/usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/.deps/usr/lib CC=/usr/local/bin/cc MAKE=/usr/local/bin/make && /usr/local/bin/cmake -E touch /usr/local/tmp/crew/v0.4.2.tar.gz.dir/neovim-0.4.2/.deps/build/src/libuv-stamp/libuv-configure
+ libtoolize --copy
+ aclocal -I m4
+ autoconf
+ automake --add-missing --copy
configure.ac:38: installing './ar-lib'
configure.ac:25: installing './compile'
configure.ac:22: installing './config.guess'
configure.ac:22: installing './config.sub'
configure.ac:21: installing './install-sh'
configure.ac:40: error: required file './ltmain.sh' not found
configure.ac:21: installing './missing'
Makefile.am: installing './depcomp'
```

**Comment by justinmk** [comment]
`ltmain.sh` is some generated file: https://github.com/libuv/libuv/blob/2c279504f92a7ab1fc54c85ec36272722198a77e/.gitignore#L34

Seems like autotools failed somehow. Does building libuv by itself work, if you pull down their repo ?

**Comment by vincowl** [comment]
No, I can't compile `libuv` from sources. I downloaded the zip file and ran : 
```
$ sh autogen.sh 
sh: 0: autogen.sh: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
+ libtoolize --copy
+ aclocal -I m4
+ autoconf
+ automake --add-missing --copy
configure.ac:39: installing './ar-lib'
configure.ac:25: installing './compile'
configure.ac:22: installing './config.guess'
configure.ac:22: installing './config.sub'
configure.ac:21: installing './install-sh'
configure.ac:41: error: required file './ltmain.sh' not found
configure.ac:21: installing './missing'
Makefile.am: installing './depcomp'
```
Same problem...

**Comment by vincowl** [comment]
Chromebrew provides a packaged version of `libuv` (which I did not install). If I install it and rebuild `neovim`, `neovim` still uses its own version of `libuv`. Is there a way to use chromebrew's lib ?

**Comment by vincowl** [comment]
I tried to compile `libuv` using cmake. It succeeded so probably something linked to autotools...

**Comment by justinmk** [comment]
We have wanted/planned to switch to using libuv CMake instead of Autotools, for our bundled build.

**Comment by blueyed** [comment]
You can use `DEPS_CMAKE_FLAGS += -DUSE_BUNDLED_LIBUV=OFF`, e.g. in local.mk, check the example in ./contrib/local.mk.example.

**Comment by vincowl** [comment]
@blueyed Is there a way to pass this to the main make command even if it's a cmake flag or am I forced to modify the mk files ?

**Comment by vincowl** [comment]
OK, Chromebrew's team solved this problem. It is not due to neovim files. So OK, Chromebrew's team solved this problem. It is not due to neovim files. So it doesn't seems usefull to me to investigate deeper since you plan to move to cmake instead of using autotools and since we can keep an inner libuv dependency which will ease the chromebrew's packages dependencies

**Comment by BitLayZzz** [comment]
Just attaching an additional solution that worked for me for anyone in the future. 

Correct me if I'm wrong as I'm new to commenting on github, but the libuv github repo required autom4ke in order to compile it from source. automake requires the `autoconf` package, which wasn't installed on my system. 

Once I ran `pacman -S autoconf` and rebuilt neovim using `make CMAKE_BUILD_TYPE=Release install`, everything worked perfectly without needing to compile libuv from source.
