### ISSUE TITLE
Terminal buffer PWD does not survive session restoration

### ISSUE THREAD

**Issue by cjlarose** [neovim/neovim#11288]
- `nvim --version`:

```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: 8.1) behaves differently? No. `vim` appears to suffer from the same problem.
- Operating system/version: macOS 10.14.6 Mojave
- Terminal name/version: iTerm2 3.3.6
- `$TERM`: `xterm-256color`

#### Setup

This creates a few directories and a program that just prints its pwd in a loop

```bash
mkdir foo
mkdir bar
cat > print-pwd.sh <<'EOF'
#!/bin/bash
while true; do
  echo $PWD
  sleep 1
done
EOF
chmod +x print-pwd.sh
```

#### Steps

```
nvim -u NORC
:cd foo
:terminal ../print-pwd.sh
:cd ../bar
:mksession! ~/pwd-session.vim
:qa

nvim -u NORC -S ~/pwd-session.vim
```

### Actual behaviour

The restored terminal buffer prints the path to the `bar` directory.

### Expected behaviour

The restored terminal buffer prints the path to the `foo` directory, the same as it did before closing neovim.

**Comment by cjlarose** [comment]
Session files encode the terminal buffer's `fname` as `term://{cwd}//{pid}:{cmd}`, but the `cwd` is often just `.` when using the `:terminal` command. 

Similar problems can be reproduced when calling the `termopen()` function directly, either by leaving the `cwd` option unspecified, or by specifying a path that isn't absolute.

**Comment by janlazo** [comment]
Would porting vim-patch:8.0.1592 and related patches fix this?

**Comment by cjlarose** [comment]
I look a look at the commit associated with that patch https://github.com/vim/vim/commit/4d8bac8bf593ff087517ff79090c2d224325aae6, but I couldn't tell if that patches addresses the same problem.

I can reproduce the problem in Vim 8.1, which I think must include that patch, so I'm not sure if porting that patch into neovim would address this problem.
