### ISSUE TITLE
uknown font: everytime nvim-qt starts

### ISSUE THREAD

**Issue by asolopovas** [neovim/neovim#11297]
- `nvim --version`: NVIM v0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Windows 10 x64 1903
- Terminal name/version: powershell
- `$TERM`:

Everytime I start nvim-qt I get red error uknown font: 
even though the font loads without a problem 
here is my ginit.vim configuration 
```
GuiFont Fira Mono for Powerline:h14
GuiTabline 0
let s:fontsize = 14
function! AdjustFontSize(amount)
  let s:fontsize = s:fontsize+a:amount
  :execute "GuiFont! Fira Mono for Powerline:h" . s:fontsize
endfunction

noremap <C-ScrollWheelUp> :call AdjustFontSize(1)<CR>
noremap <C-ScrollWheelDown> :call AdjustFontSize(-1)<CR>
inoremap <C-ScrollWheelUp> <Esc>:call AdjustFontSize(1)<CR>a
inoremap <C-ScrollWheelDown> <Esc>:call AdjustFontSize(-1)<CR>a
inoremap <silent>  <S-Insert>  <C-R>+
```

I have tried commenting out everything in both init.vim and ginit.vim but it still throws that error

**Comment by justinmk** [comment]
Fixed in nvim-qt v0.2.15 https://github.com/neovim/neovim/pull/11295

So next time our bot publishes a release (24 hours) this will be fixed in the Nvim 0.5 Windows artifacts. And when we release Nvim 0.4.3 (maintenance release), it will be fixed there as well.
