### ISSUE TITLE
ValueError on python3 healthcheck when sys.path doesn't contain empty string

### ISSUE THREAD

**Issue by supermomonga** [neovim/neovim#11293]
- `nvim --version`:

```
> .\nvim.exe --version
NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

      システム vimrc: "$VIM\sysinit.vim"
       省略時の $VIM: "C:/Program Files/nvim/share/nvim"
```

- `vim -u DEFAULTS` (version: 8.1.1048) behaves differently?

`Yes`. Because Vim does not have `:healthcheck` command.

- Operating system/version:

Windows 10 Pro version 1903 ( build 18362.418 )

- Terminal name/version:

PowerShell 5.1.18362.145

Also reproduced without terminal ( `nvim-qt.exe` ).

- `$TERM`: None value.

### Steps to reproduce using `nvim -u NORC`

Embeddable Python3 and pynvim package setup:

- Setup embeddable python
  - Download [Python 3.6.8 Windows x86-64 embeddable zip file](https://www.python.org/ftp/python/3.6.8/python-3.6.8-embed-amd64.zip) from https://www.python.org/downloads/windows/ and extract it.
    - e.g.) `~/vimfiles/python-3.6.8-embed-amd64/`
  - Launch powershell and move into extracted directory.
- Setup pip for embedded python
  - Download `get-pip.py` into python installed dir from https://bootstrap.pypa.io/get-pip.py
    - e.g.) `~/vimfiles/python-3.6.8-embed-amd64/get-pip.py`
  - Fix `python36._pth`
    - Change `# import site` to `import site`.
  - Install pip
    - `./python.exe ./get-pip.py`
- Install `pynvim` package
  - `./python.exe -m pip install pynvim`

Then, you can see `pynvim` in `pip list` result.

```
C:\Users\momonga\vimfiles\python-3.6.8-embed-amd64
> ./python.exe -m pip list
Package    Version
---------- -------
greenlet   0.4.15
msgpack    0.6.2
pip        19.3.1
pynvim     0.3.2
setuptools 41.4.0
wheel      0.33.6
```

How to repdoduce in neovim:

- `nvim -u NORC`
- `:let g:python3_host_prog = expand('~/vimfiles/python-3.6.8-embed-amd64/python.exe')`
- `:checkhealth`

```
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "C:\Users\momonga\vimfiles\python-3.6.8-embed-amd64\python.exe"
  - INFO: Executable: C:\Users\momonga\vimfiles\python-3.6.8-embed-amd64\python.exe
  - ERROR: Command error (job=13, exit code 1): `"C:\Users\momonga\vimfiles\python-3.6.8-embed-amd64\python.exe" -c "import sys; sys.path.remove(""""); import neovim; print(neovim.__file__)"` (in 'C:\Users\momonga\scoop\apps\neovim\current\bin')
    Output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: list.remove(x): x not in list
    Stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: list.remove(x): x not in list
  - INFO: Python version: 3.6.8
  - INFO: pynvim version: unable to load neovim Python module
  - ERROR: pynvim is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
      - Run in shell: pip3 install pynvim
```

How to reproduce without neovim:

Launch python interpreter and execute [this lines](https://github.com/neovim/neovim/blob/179c46a016388c2acead17e56d5860e667748561/runtime/autoload/provider/pythonx.vim#L13).

```
C:\Users\momonga\scoop\apps\neovim\current\bin
> cd C:\Users\momonga\vimfiles\python-3.6.8-embed-amd64\

C:\Users\momonga\vimfiles\python-3.6.8-embed-amd64
> .\python.exe
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['C:\\Users\\momonga\\vimfiles\\python-3.6.8-embed-amd64\\python36.zip', 'C:\\Users\\momonga\\vimfiles\\python-3.6.8-embed-amd64', 'C:\\Users\\momonga\\vimfiles\\python-3.6.8-embed-amd64\\lib\\site-packages']
>>> sys.path.remove("")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: list.remove(x): x not in list
>>> import neovim
```

### Actual behaviour

Python3's health check will throw `ValueError` before trying to check if `neovim` can be import.

### Expected behaviour

Python3's health check can check if `neovim` module is installed.

**Comment by justinmk** [comment]
Thanks for the detailed report. You could try fixing it here: https://github.com/neovim/neovim/blob/382391b/runtime/autoload/health/provider.vim#L205

Then send a PR.

**Comment by supermomonga** [comment]
OK, I will.
