### ISSUE TITLE
Lines starting with `.sh` are considered as blank lines

### ISSUE THREAD

**Issue by Alex-Canales** [neovim/neovim#11300]
- `nvim --version`: **v0.4.2** (details below)
- `vim -u DEFAULTS` (version: 8.0) behaves differently? **No**. [See issue #5128.](https://github.com/vim/vim/issues/5128)
- Operating system/version: **Linux Mint 19.1 Tessa 64-bit**
- Terminal name/version: **mate-terminal/1.20.0**
- `$TERM`: **xterm-256color**

### Steps to reproduce using `nvim -u NORC`

Open a file with the following or paste it in Neovim.

```
Line 1
Line 2

Line 4
.sh
Line 6

Line 8
.show { display: block; }
Line 10

Line 12
```

### Actual behaviour

* The lines starting with `.sh` are considered as blank lines.
* The `{` and `}` operators jump to lines 3, 5, 7, 9 and 11.
* Placing the cursor at line 4 and using the `ip` operator selects only the line 4.
* Placing the cursor at line 8 and using the `ip` operator selects only the line 8.
* Whatever characters are after `.sh`, this wrong behaviour happens.

### Expected behaviour

* The lines starting with `.sh` should not be considered as blank lines.
* The `{` and `}` operators should jump only to lines 3, 7 and 11.
* Placing the cursor at line 4 and using the `ip` operator should select the lines 4, 5 and 6.
* Placing the cursor at line 8 and using the `ip` operator should select the lines 8, 9 and 10.

### Version details

Neovim was compiled by myself.

```
NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/alex/Depots/neovim/build/config -I/home/alex/Depots/neovim/src -I/home/alex/Depots/neovim/.deps/usr/include -I/usr/include -I/home/alex/Depots/neovim/build/src/nvim/auto -I/home/alex/Depots/neovim/build/include
```

**Comment by justinmk** [comment]
See `:help paragraph` , it regard it as a nroff macro. Weird but true.

More-flexible `paragraph` has been on Bram's todo.txt for a long time. Would be great to have, but not going to track it here.

**Comment by Alex-Canales** [comment]
Thank you Justin for the quick reply and the explanation. I am sorry for the little waste of time, it did not even occur to me to check the paragraph motion settings.

**Comment by justinmk** [comment]
No worries. `:help {` should link to `|paragraph|` , I'll update it.
