### ISSUE TITLE
declare dependencies for non-LuaJit downstream

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#11301]
I'm quoting @jamessan in https://github.com/glacambre/firenvim/issues/138 :

>I don't think there's a clear statement from the Neovim side about what the expected Lua API is. I know we target 5.1 because that's the baseline compatibility between Lua and LuaJIT, but is that also supposed to include any additional modules LuaJIT provides or is LuaJIT just an implementation detail to get better performance? If it's the former, that it implies Neovim packagers should depend on lua-bitop (anything else?) when not building against LuaJIT. If it's the latter, projects should call those modules out as dependencies if they're using them.

Can lua plugin developpers rely on LuaJit modules always being present, even if Neovim has been compiled with a non-luajit lua? Or should they pay attention to always provide a fallback/instruct users to install modules they rely on?

**Comment by justinmk** [comment]
> it implies Neovim packagers should depend on lua-bitop (anything else?) when not building against LuaJIT

Yes, we should do that.

> is LuaJIT just an implementation detail to get better performance? 

It's both: we've planted a flag in Lua 5.1 because having a frozen language is useful. But also because LuaJit is great.

**Comment by jamessan** [comment]
> Yes, we should do that.

Ok, so is bitop the only extra Lua module needed when nvim isn't built against LuaJIT?  This should be documented somewhere, both for the benefit of packagers and user's.

**Comment by justinmk** [comment]
No idea. Someone needs to inspect http://luajit.org/extensions.html and I guess decide which of those we might want to require. E.g. `xpcall` is probably a good idea.

**Comment by jamessan** [comment]
Looks like bitop is the only external module available for non-LuaJIT, so that simplifies things. :)

**Comment by norcalli** [comment]
My test failed because I assumed `bitop` was available. It seems the travis test needs to have bitop added per this issue https://travis-ci.org/neovim/neovim/jobs/609437664?utm_medium=notification&utm_source=github_status

**Comment by norcalli** [comment]
And indeed the only mandatory external module available is bitop. Everything else like coro is optional.

**Comment by justinmk** [comment]
> Everything else like coro is optional.

Optional because we don't (currently) use it? Should we ?

**Comment by XVilka** [comment]
Note that with the appearance of MoonJIT it's unnecessary to stay at 5.1 forever: https://github.com/moonjit/moonjit
For example, 2.2.0 versions [supports some of the Lua 5.2 and 5.3 features](https://github.com/moonjit/moonjit/releases/tag/2.2.0).

**Comment by justinmk** [comment]
What would be the point of that?

**Comment by bfredl** [comment]
In theory we could just vendor a specific commit of moonjit as "the" lua for neovim 0.5 but I am afraid @jamessan would be quite mad at me if I do that :]

**Comment by janlazo** [comment]
No recent progress on this so I'm moving this to the next milestone. Same rationale for https://github.com/neovim/neovim/issues/11352.

**Comment by XVilka** [comment]
Just a heads up - moonjit is dead now, everyone moved to OpenResty's LuaJIT:  https://github.com/openresty/luajit2

**Comment by clason** [comment]
Yes, we know, that's why there's https://github.com/neovim/neovim/pull/13741.

**Comment by justinmk** [comment]
bitop is now included https://github.com/neovim/neovim/pull/21222 and mentioned in MAINTAIN.md. 

So I think this can be closed?

**Comment by lewis6991** [comment]
There's also the ffi if that matters? Lazy.nvim requires it for example.
