### ISSUE TITLE
Terminal can't start in insert mode in some situations

### ISSUE THREAD

**Issue by monkoose** [neovim/neovim#11316]
- `nvim --version`: 0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: ArchLinux
- Terminal name/version: kitty
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Not sure if it is neovim or fzf itself, so i have opened same issue there junegunn/fzf.vim#886
main fzf plugin (not fzf.vim) should be in your runtime
Here is minimal script
```vim
function! s:ls_handler(lines) abort
  " exit if empty
  if a:lines == [] || a:lines == ['','','']
      return
  endif

  " Expect at least 2 elements, `query` and `keypress`, which may be empty strings.
  let query    = a:lines[0]
  let keypress = a:lines[1]
  if keypress ==? 'enter'
    let new_search = 'FzfLs ' . query
    execute new_search
  endif
endfunction

command! -nargs=* -bang FzfLs
    \ call fzf#run(fzf#wrap('hoogle', {
            \ 'sink*': function('s:ls_handler'),
            \ 'source': 'ls ' . <q-args> . " 2> /dev/null ",
            \ 'options': [
                  \ '--print-query',
                  \ '--expect=enter',
                  \ '--ansi',
                  \ '--exact',
                  \ '--inline-info',
                  \ '--header', ':: Press `enter` to research with current query',
                  \ ]
            \ }, <bang>0))
```
If you run `:FzfLs` it starts terminal in insert mode, then type some query and hit `enter` it respawns terminal in normal mode, that can't be prevented with any `autocmd` and `startinsert`.

### Actual behaviour
Respawn fzf in terminal in normal mode
### Expected behaviour
Respawn fzf in terminal in insert(terminal) mode same as vim.

**Comment by justinmk** [comment]
This isn't a minimal repro. We don't have time to debug plugins or user configs.

**Comment by monkoose** [comment]
Understandable. Will try to find some way to hit this issue without plugins.
