### ISSUE TITLE
Lua stdlib: best practices for style, performance, idioms, errors, etc.

### ISSUE THREAD

**Issue by norcalli** [neovim/neovim#11312]
There are things which become common knowledge, such as how to handle private state in modules or how to declare modules or useful idioms, or performance considerations for certain types of idioms.

Some examples:

**Useful idioms:**
- Declaring a function on a dictionary value by doing `local value = {}; function value.method() end`

**Style:**
- Using `or` for default initialization such as `local value = default_value or 100`.

**Performance:**
- Local variables are faster to lookup than global variables.
- Declare your commonly used functions to avoid a table lookup, esp for imported functions. This can also lead to smaller and more legible lines. e.g. https://github.com/norcalli/nvim-colorizer.lua/blob/174b7a67ce384318f7500e0d256322e1cbba5e5b/lua/colorizer.lua#L8

I'll create a companion PR which houses the ones I know, but it would be good to expose them outside of the vimdocs as well for the larger Lua community.

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/issues/11311

**Comment by norcalli** [comment]
Performance: Adhere to the http://wiki.luajit.org/NYI for luajit functions.
Style: using an explicit `if value ~= nil` vs `if value`?
Style/Performance: assert messages which require construction/allocation should be wrapped in if/else?
Style: `string.format("%q", v)` vs `("%q"):format(v)` and similar for other string type functions on temporary values.

**Comment by norcalli** [comment]
http://wiki.luajit.org/Numerical-Computing-Performance-Guide

**Comment by norcalli** [comment]
Better coroutine examples for more advanced things like a push based parser (an example of which is from lsp):

```lua
local function request_parser_loop()
	local buffer = ''
	while true do
		-- A message can only be complete if it has a double CRLF and also the full
		-- payload, so first let's check for the CRLFs
		local start, finish = buffer:find('\r\n\r\n', 1, true)
		-- Start parsing the headers
		if start then
			local headers = parse_headers(buffer:sub(1, start-1))
			buffer = buffer:sub(finish+1)
			local content_length = headers.content_length
			-- Keep waiting for data until we have enough.
			while #buffer < content_length do
				buffer = buffer..assert(coroutine.yield(), ":( body") -- TODO hmm.
			end
			local body = buffer:sub(1, content_length)
			buffer = buffer:sub(content_length + 1)
			-- Yield our data.
			buffer = buffer..assert(coroutine.yield(headers, body), ':( cont') -- TODO hmm.
		else
			-- Get more data since we don't have enough.
			buffer = buffer..assert(coroutine.yield(), ":( header") -- TODO hmm.
		end
	end
end

-- Usage
local request_parser = coroutine.wrap(request_parser_loop)
-- Start the coroutine
request_parser()

-- later...
local headers, body = request_parser(chunk)
-- If we successfully parsed, then handle the response.
if headers then
-- do stuff
end
```

Also other patterns like using `coroutine.resume()` to turn a callback based call into a synchronous looking call via something like:

```lua
local function send_request_sync(method, params)
	local co = coroutine.running()
	send_request(method, params, function(...) coroutine.resume(co, ...) end)
	return coroutine.yield()
end
```

pattern for the request_parser is something I use often when I have a push based flow like a web server

**Comment by norcalli** [comment]
`do` blocks for scope local temporary variables vs other means:

```lua
do
  local overriden = vim.paste
  vim.paste = function(lines, phase)
    ...
  end
end
```
vs
```lua
vim.paste = (function(overridden)
  ...
  end
end)(vim.paste)
```

Although another example is:
```lua
local paste_handler
do
  local tempv = 123
  paste_handler = function(lines, phase) end
end
```

Although another example is:
```lua
local paste_handler = (function()
  local tempv = 123
  return function(lines, phase) end
end)()
```

**Comment by justinmk** [comment]
- no whitespace between a function call and its arguments
  - good: `foo{...}`, `foo(...)`
  - bad: `foo {...}`, `foo (...)`

**Comment by norcalli** [comment]
I've been thinking about the spacing between arguments for `{` style calls, and the thing is that I also put a space between `require` and its path when I use that syntax (which is the same) I think it's to imply that it's passing a single argument rather than a traditional call. So `require 'nvim_lsp'` vs `require'nvim_lsp'` and `setup { 123 }` vs `setup{123}`.

**Comment by justinmk** [comment]
- Related:
    - https://github.com/neovim/neovim/issues/18585
    - https://github.com/neovim/neovim/issues/18585
- > other patterns like using `coroutine.resume()` to turn a callback based call into a synchronous looking call via something like:
    - https://github.com/neovim/neovim/issues/19624 will establish the initial picture of concurrency/async patterns.
- Other than the coroutine comments, most of the comments here will be covered by automated lint: 
    - https://github.com/neovim/neovim/pull/14987 (that PR is closed but just for reference)

(Minor note: I do favor `("%q"):format(v)` instead of `a ... b` for building strings, would be nice if lint could nudge towards that.)
