### ISSUE TITLE
Glitchy mouse scrolling in diff mode

### ISSUE THREAD

**Issue by lyu** [neovim/neovim#11328]
- `nvim --version`: 0.4.2 (from Archlinux official repo)
- `vim -u DEFAULTS` (version: 8.1.2102) behaves differently? Yes, vim doesn't have this issue
- Operating system/version: Archlinux x86_64
- Terminal name/version: tilix 1.9.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Download these two text files:  [1.txt](https://github.com/neovim/neovim/files/3801557/1.txt) [2.txt](https://github.com/neovim/neovim/files/3801558/2.txt)
Then, run
```
nvim -u NORC -d 1.txt 2.txt
```
Enable mouse with `:set mouse=a`, and scroll the text in either the left window or the right window up and down, using your mouse.

### Actual behaviour
Contents get out-of-sync between the two windows every now and then: scroll to the bottom of the left window and then scroll up slowly, the right window will fail to keep up at a certain point.

Some text get displayed twice: the "6789" line stands out very clearly.

For longer and more complicated code, the result could become a complete mess and unreadable.

### Expected behaviour
Everything works fine with mouse scrolling, like vimdiff does.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS.

Looks similar to https://github.com/neovim/neovim/issues/11278

**Comment by lyu** [comment]
Sorry about the duplication. The latest nightly build doesn't have this bug, thank you.
