### ISSUE TITLE
Closing an fzf search pane errors

### ISSUE THREAD

**Issue by mitchellwrosen** [neovim/neovim#11334]
- `nvim --version`:
    ```
    NVIM v0.4.2
    Build type: Release
    LuaJIT 2.0.5
    Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
    Compiled by builduser

    Features: +acl +iconv +tui
    ```
- Operating system/version: Arch Linux 5.3.6
- Terminal name/version: alacritty 0.3.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

- Install `fzf` and the `fzf` neovim plugin.
- Open a file search buffer with `:Files`
- Close it

### Actual behaviour

The buffer closes cleanly

### Expected behaviour

It errors with a message like:

![2019-11-04-204409_1195x32_scrot](https://user-images.githubusercontent.com/1074598/68172001-f3d19080-ff43-11e9-92ad-4af38906222e.png)

and then I regain control of the editor after a second or two. Apologies, I can't figure out how to get the full error message. I only see that one line.

**Comment by mitchellwrosen** [comment]
More info: I believe the bug is new as of 0.4.

**Comment by justinmk** [comment]
Need minimum steps. Most likely just something needs to be adjusted in fzf.

**Comment by mitchellwrosen** [comment]
Can you please clarify what I need to specify? This should not have been closed, it's a regression in vim. Not an fzf bug.

**Comment by mitchellwrosen** [comment]
I've narrowed the issue down a bit. Here is a minimal `.vimrc`:

```
cal plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
cal plug#end()
tno <Esc> <C-\><C-n>
```

The problematic line is the last one, which attempts to map `Esc` to escape terminal mode (as mentioned by `nvim_terminal_emulator.txt`).

To see the bug in action, type `:Files` to open an fzf terminal emulator pane, then press `Esc`.

**Comment by mhinz** [comment]
I can reproduce it. The process started with `termopen()` exits with 129, leading to [this line](https://github.com/junegunn/fzf/blob/dceb5d09cdb0d3158a3f79e59eb3c16ffe242d6b/plugin/fzf.vim#L531).

Using that command manually in the shell works without problems though, as in, every kind of interrupt makes it return 130, which is expected.

Investigating.

**Comment by mhinz** [comment]
@mitchellwrosen https://github.com/junegunn/fzf/pull/1749
