### ISSUE TITLE
GUIcursor doesn't work in MATE 1.8.1

### ISSUE THREAD

**Issue by jrwrigh** [neovim/neovim#11339]
- `nvim --version`: 
```
NVIM v0.4.0-1822-ga851090de
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9cfec340-bad9-4f5d-b7a6-d8a206046c01

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"
```
- `vim -u DEFAULTS` (version: ) behaves differently? no, but that's to be expected with guicursor.
- Operating system/version: 8.11
- Terminal name/version: MATE 1.8.1
- `$TERM`: vte-256color

### Steps to reproduce using `nvim -u NORC`

Go into insert mode, cursor doesn't change.

### Actual behaviour
Cursor stays as block in insert mode

### Expected behaviour
Cursor changes from block to line in insert mode

**Comment by justinmk** [comment]
Are you certain your terminal supports cursor shaping? According to https://en.wikipedia.org/wiki/MATE_(software) , MATE 1.8.1 is from 2014, which is before libvte got its act together wrt to cursor shaping.

**Comment by jrwrigh** [comment]
If you're referring to whether MATE can have different cursor shapes, it can. There's a setting for it. And it works.

**Comment by justinmk** [comment]
What setting exactly? The fact that you can configure your terminal to change its cursor shape is unrelated to whether the terminal supports cursor-shaping control codes.

**Comment by jrwrigh** [comment]
Ah, no idea on control codes. The setting itself is just for a "profile", so I guess it's a hard set thing.
