### ISSUE TITLE
File Explorer Breaks <C-l> Mappings

### ISSUE THREAD

**Issue by Joshuaweiss** [neovim/neovim#11333]
- `nvim --version`:
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/
- `vim -u DEFAULTS` (version: v0.4.0) behaves differently? no
- Operating system/version: macOS 10.15.1 (19B88)
- Terminal name/version: Terminal 2.10 & Alacritty 0.3.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
* Open tmux with `<C-l>` mapped to move right a space
* Split tmux to have two spaces left and right
* Open `nvim .` to see file explorer in the left space
* Type `<C-l>` in vim

### Actual behaviour
The terminal flashes and rerenders bypassing the tmux key mapping.

### Expected behaviour
tmux moves right a space

NOTE: This issue seems to have appeared in v0.4.0 and does not occur on v0.3.8

**Comment by justinmk** [comment]
Report to vim.  We don't maintain netrw.
