### ISSUE TITLE
Mouse scrolling with anchor

### ISSUE THREAD

**Issue by eyalk5** [neovim/neovim#11341]
Hi,
It would be really nice if the style of mouse scrolling in windows(I think) would be somehow supported in neovim. 
That is, when you press the middle mouse button, you get an anchor, and depending on the position relative to it, the scroll speed is set.

Low chances it will be implemented, 
but thanks for all the work anyway.

**Comment by justinmk** [comment]
Terminals don't support mouse-drag unless a button is actually pressed. GUIs could implement this easily, it requires no special support in Nvim core.

Even if terminals did support this, I personally can't stand that feature...
