### ISSUE TITLE
api: nvim_buf_attach subscribe to specific events

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#11342]
- `nvim --version`: v0.5.0-139-g610755ff6
- Operating system/version: macos

### Actual behaviour
As far as I know, `nvim_buf_attach` does not support subscription to specific events. When I use nvim-qt api client, I only want to subscribe to `nvim_buf_detach_event` via `nvim_buf_attach`, I don't want to receive the `nvim_buf_lines_event`. 
On the one hand, I don't need `nvim_buf_lines_event`, on the other hand, I think it will consume the performance of nvim (or increase the burden of nvim).
If I miss something, please forgive me.

**Comment by justinmk** [comment]
This is micro-optimization and is not worth the extra complexity. Are you seeing an actual slowdown?
