### ISSUE TITLE
vertical split wrecked display

### ISSUE THREAD

**Issue by cbosdo** [neovim/neovim#11347]
- `nvim --version`:

```
NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc  -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/abuild/rpmbuild/BUILD/neovim-0.4.2/build/config -I/home/abuild/rpmbuild/BUILD/neovim-0.4.2/src -I/usr/include -I/usr/include/lua5.1 -I/home/abuild/rpmbuild/BUILD/neovim-0.4.2/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.4.2/build/include
Compiled by abuild@OBS

Features: +acl +iconv +tui
See ":help feature-compile"
```

- `vim -u DEFAULTS` (version: 8.1) behaves correctly
- Operating system/version: openSUSE Tumbleweed
- Terminal name/version: Gnome Terminal 3.34.2
- doesn't happen with xterm
- `TERM=xterm-256color`

### Steps to reproduce using `nvim -u NORC`

* Open a fairly large file that doesn't fit the screen. This file is a good example: https://github.com/saltstack/salt/blob/master/salt/modules/virt.py
* Create a vertical split (`:vs`)
* Scroll or move further down or up in the file to get a change of the displayed text (Page Up / Down does it fine)

### Actual behaviour

The other split display is broken like in the following screenshot:

![Screenshot from 2019-11-07 10-41-46](https://user-images.githubusercontent.com/397931/68377788-4cbf4580-014b-11ea-8f64-a9a4fe8fdaf6.png)

Pressing `Ctrl+L` refreshes the screen to get the other split right like in this screenshot:
![Screenshot from 2019-11-07 10-41-49](https://user-images.githubusercontent.com/397931/68377854-63fe3300-014b-11ea-937e-b09e448b155a.png)

### Expected behaviour

The other vertical split should stay nicely displayed as in the second screenshot

**Comment by cbosdo** [comment]
Found it to be a duplicate of #6802

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version (or maybe 0.4.3)? The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS.

**Comment by cbosdo** [comment]
@justinmk scroll works better with 0.4.3 but still has problems with up and down keys. Nightly build works fine in both cases. Closing the issue.
