### ISSUE TITLE
Setting backupdir with dirs that don't exist and linked files 

### ISSUE THREAD

**Issue by wspurgin** [neovim/neovim#11349]
- `nvim --version`:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: 8.0) behaves differently? Yes. It writes the backup to `/var/tmp` for a symlinked file
- Operating system/version: OS X 10.14.6
- Terminal name/version: iTerm2 3.3.6
- `$TERM`: `xterm-256color`

--------------------------------

Relates (I think) to #10101 (since it's about backups for symlinks).

Having `backupdir` set to a list of dirs where (in order of appearance) the first one does not exist, writing backups for symlink files will fail with `E506`.

When setting the `backupdir` option, the help indicates that it will attempt to create the backup file in the
> first directory in the list where this is possible

If one has this vimrc (only setting the backupdir):

```
set backupdir=~/.this-does-not-exist-tmp/,/var/tmp/
```

and the following files:

```
drwxr-xr-x  4 wspurgin  staff   128B Nov  7 10:17 .
drwxr-xr-x  7 wspurgin  staff   224B Nov  7 10:14 ..
lrwxr-xr-x  1 wspurgin  staff     7B Nov  7 10:14 bar.txt -> foo.txt
-rw-r--r--  1 wspurgin  staff    12B Nov  7 10:17 foo.txt
```

Attempt to edit `bar.txt` and then `:w` the file after it is open

### Actual behaviour

A `E506 Can't write backup file` error occurs when attempting to write `bar.txt`. Note, that if you swap the order of the directory list in `backupdir` (where a directory that exists appears first), there's no `E506`.

### Expected behaviour

I expect it to write the backup file to `/var/tmp` and not `E506`.

**Comment by justinmk** [comment]
I wonder if https://github.com/neovim/neovim/pull/9709 regressed this. Perhaps you (or someone else interested in this) could build b9ba1295b466a440600b36a717c701bfcea53dbc (which is before that PR was merged) and check if the problem exists then?

**Comment by wspurgin** [comment]
Hey @justinmk thanks for taking a look. I'll check out `b9ba129` and see if #9709 is the regression 👍 Thanks for digging and finding that commit!

**Comment by wspurgin** [comment]
@justinmk Just built b9ba129 and that did behave as expected (it was able to write the backup file for the symlinked file). To verify it was #9709 for sure, I build ca1ce5902 too (the merge for that PR) and it failed with the 506 on the symlinked file. I can try to take a look at that PR and see where the missing piece of logic is unless you already have an idea.

**Comment by justinmk** [comment]
@wspurgin Thanks. Yes, this is more likely to get resolved soon if you want to try debugging it.

**Comment by wspurgin** [comment]
@justinmk WIP PR with fix for symlink file backups #11417

**Comment by janlazo** [comment]
Is this fixed on master? Would porting https://github.com/vim/vim/commit/cd142e3369db8888163a511dbe9907bcd138829c improve the situation? It should have been ported before https://github.com/neovim/neovim/pull/11269. If not, can we revert the code and not use libuv for this?

**Comment by wspurgin** [comment]
Hey @janlazo (sorry this notification got buried). I haven't tried in a while to see if its fixed. If I get a chance this week/weekend I'll check master again

**Comment by rouge8** [comment]
I believe neovim 0.4.4 is still affected.

**Comment by nathanph** [comment]
This bug has been annoying me for ages, thank you for looking into this @wspurgin.

**Comment by glacambre** [comment]
Seems to be fixed on master, so I'll close this issue :).
