### ISSUE TITLE
Windows: redraw glitch with in Cmder

### ISSUE THREAD

**Issue by predatorian3** [neovim/neovim#11353]
- `nvim --version`:
```
λ nvim --version
NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
  - `vim` runs just fine, showing text in command section of Cmder window
- Operating system/version: Windows 10
- Terminal name/version: Cmder running cmd.exe
- `$TERM`: n/a

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

Using the above commands disable the other add-ons. `%LOCALAPPDATA%\nvim\init.vim` link or source the `%HOME%\vimfiles\` directory and `%HOME%\vimfiles\vimrc`. This is when the problems arise.

### Actual behaviour

![2019-11-08_neovim_cmder_not_showing_cmd_fully](https://user-images.githubusercontent.com/3039509/68519025-597b9080-0254-11ea-9488-5a6de40dc2c9.PNG)

The image above shows the attempted start of `:NERDTreeCWD`, but the first few characters are missing. Could this be a function of NERDTree or vim-airline?

### Expected behaviour

Display the expected command in the window as it would without having other plugins installed.

### Extra Notes

When running nvim with regular vim plugins sourced, as long as I execute `nvim .` and open the directory, the text displays in the command window properly, until I close NERDTree. Once NERDTree is closed, the first few characters of the command go back to not displaying until character 3 or 4. Also, the redraw in the command section doesn't seem to overwrite and remove errors that were generated upon first start until text long enough is displayed that rewrites the command section.

**Comment by justinmk** [comment]
What are the steps to reproduce? It's not clear. Can this be reproduced without cmder (Windows terminal or cmd.exe) and NERDtree?

**Comment by predatorian3** [comment]
# NeoVim Setup

Inside of the `%LOCALAPPDATA%\nvim\init.vim` I have the following settings:

```vim
" NeoVim Init
" %LOCALAPPDATA%\nvim\init.vim
set runtimepath^=~/vimfiles runtimepath+=~/vimfiles/pack
let &packpath = &runtimepath
source ~/vimfiles/vimrc
```

Then inside of the `%USERPROFILE%\vimfiles\vimrc` I have my normal configs for `vim`. I have my packages setup inside of `%USERPROFILE%\vimfiles\pack\vendor\{start,ops}\`. There I have various plugins.

```bash
dudleyp@laptop MSYS /c/Users/dudleyp/vimfiles/pack/vendor
$ tree -L 2
.
├── opt
│   ├── ale
│   └── syntastic
└── start
    ├── BufOnly.vim
    ├── nerdtree
    ├── nerdtree-git-plugin
    ├── vim-airline
    ├── vim-autoclose
    ├── vim-endwise
    ├── vim-fugitive
    ├── vim-markdown-toc
    ├── vim-misc
    ├── vim-polyglot
    ├── vim-session
    ├── vim-terraform
    └── vim-virtualenv

17 directories, 0 files
```

Most of the plugins are setup with just their defaults.

# With CMD.exe

Within `CMD.exe` nvim works just fine by executing `nvim` and shows the command window section.

# With CMDER.exe

With `CMDER.exe`, nvim shows the first two characters when launching or opening a file. However, when opening nvim with a directory, it looks and behaves like it should.

Opening NeoVim in CMDER.exe with a file or no arguments. `nvim`

![2019-11-11_neovim_cmder_not_showing_cmd_fully](https://user-images.githubusercontent.com/3039509/68603755-8e632f80-046e-11ea-829e-bc4b3b3217d2.PNG)

Opening NeoVm in CMDER.exe with a folder as an argument, `nvim .`

![2019-11-11_neovim_cmder_showing_command_when_opening_folder](https://user-images.githubusercontent.com/3039509/68603789-a20e9600-046e-11ea-88cd-207ae8002821.PNG)

When using NeoVim in both CMD.exe and CMDER.exe, they're all using the same configs and plugins.

**Comment by justinmk** [comment]
I'm struggling to understand why this matters. Does CTRL-L fix it?

**Comment by parkovski** [comment]
Cmder patches a lot of console APIs (both the clink and conemu subprojects do this independently IIRC) and I expect debugging something like this would be a nightmare. If it works in regular cmd, it's probably on cmder to fix this.
