### ISSUE TITLE
Ability to use an external command for :find (feature request)

### ISSUE THREAD

**Issue by dalz** [neovim/neovim#11358]
It would be nice to have a `findprg` option for use with :find. By using something like `fd` or `locate` recursive searches would become usable with larger directories.

**Comment by justinmk** [comment]
This can be achieved using e.g. `:make` with a clever `'makeprg'` that inspects `'path'`.

Enhancing `:find` is low priority for Neovim, but if Vim implements it we're happy to merge that patch.
