### ISSUE TITLE
Release version 0.4.3 for windows reports version 0.4.2

### ISSUE THREAD

**Issue by kearnh** [neovim/neovim#11355]
- `nvim --version`:
```
NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

(This is supposed to be 0.4.3)

- `vim -u DEFAULTS` (version: ) behaves differently?
Not relevant
- Operating system/version: Windows 10
- Terminal name/version: cmd.exe
- `$TERM`: not set (it's windows)

### Steps to reproduce using `nvim -u NORC`
:ver 

### Actual behaviour
:ver reports version 0.4.2
### Expected behaviour
:ver reports version 0.4.3

Checking the files in the bin directory (for both 32 and 64 bit builds) shows all the exes, libs etc to have an mtime of either the 14th September or 16th September, which was the release date of 0.4.2

**Comment by justinmk** [comment]
https://ci.appveyor.com/project/neovim/neovim/builds/28652833 failed, so the Windows artifacts for the `stable` tag are still pointing to 0.4.2. I have restarted that build, then the update job will get the correct 0.4.3 artifacts.
