### ISSUE TITLE
Spell file download fails from modeline

### ISSUE THREAD

**Issue by baltitenger** [neovim/neovim#11359]
- `nvim --version`:
```
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system/version:
Arch Linux x86_64 5.3.8-arch1-1
- Terminal name/version:
termite v15
- `$TERM`:
xterm-termite

I have an autocmd in my vimrc which sets spell for tex files. In some files I want to override the language with a modeline.

### Steps to reproduce using `nvim -u NORC`
```sh
# test.latex has `% vim: set spelllang=hu:`
# no spell file for `hu` yet!
nvim -u NORC --cmd 'autocmd FileType tex setlocal spell' --cmd 'set modeline' test.latex
# works without autocmd too:
nvim -u NORC --cmd 'set spell modeline' test.latex
```

### Actual behaviour
The language file failed to download with the following errors:
```
Downloading hu.utf-8.spl...
Error detected while processing /usr/share/nvim/runtime/autoload/netrw.vim:
line  583:
E12: Command not allowed from exrc/vimrc in current dir or tag search: au WinEnter *^Iif &ft == "netrw"|call s:NetrwInsureWinVars()|endif
Error detected while processing function spellfile#LoadFile[60]..spellfile#Nread[13]..netrw#NetRead[4]..<SNR>110_NetrwOptionsSave:
line   66:
E171: Missing :endif
Error detected while processing function spellfile#LoadFile[60]..spellfile#Nread:
line   13:
E171: Missing :endif
Error detected while processing function spellfile#LoadFile:
line   60:
E171: Missing :endif
Error detected while processing modelines:
line    3:
E12: Command not allowed from exrc/vimrc in current dir or tag search
```

### Expected behaviour
The download should succeed

**Comment by justinmk** [comment]
Nothing we can do about that. Use `:set spell` from the cmdline / outside of a modeline. Modelines cannot execute arbitrary code, that's a security risk.

**Comment by baltitenger** [comment]
Ok, fair, but you could at least make the errors a bit more informative. At first I thought something was wrong with netrw because of the missing endifs. Then I tried doing it by hand (`:set spell spellang=hu` in an empty file), and it worked. So I thought the problem was with the autocommand, as it said `Command not allowed from exrc/vimrc in current dir or tag search`, so it must be something from my vimrc. And very well, if I uncommented the autocommand in my vimrc and opened the file with the modeline then did `:set spell` manually, it worked, So I was fairly certain the problem was with the autocommand.

**Comment by chrisbra** [comment]
How about upstreaming those changes?
