### ISSUE TITLE
Add `bit` compat module for Lua 5.1

### ISSUE THREAD

**Issue by norcalli** [neovim/neovim#11352]
`bit` is available for luajit, and since we use luajit for all the platforms where it's available, users could come to expect that `bit` would be available. It would be relatively easy to provide a compatible interface or just compile the [bitop from luadist](https://github.com/LuaDist/luabitop) directly.

**Comment by justinmk** [comment]
> compile the [bitop from luadist](https://github.com/LuaDist/luabitop) directly

definitely, let's do it. We need this to close https://github.com/neovim/neovim/issues/11301

**Comment by norcalli** [comment]
The bit functions are pretty necessary for color operations in the LSP virtual text diagnostics and stuff, so I'll try to get to this soon. For now I've hidden them so they're not mandatory, but only if you use those functions. The pure lua polyfills for this are really not great, so compiling is definitely the best option.

**Comment by clason** [comment]
We could upstream https://github.com/nvim-lua/plenary.nvim/blob/bfe08f26bdc246a13f66e37d44334da83c27f134/lua/plenary/bit.lua for this. @tjdevries ?

**Comment by justinmk** [comment]
how does that compare to the solution discussed above?

**Comment by clason** [comment]
It's much simpler?

**Comment by jamessan** [comment]
Isn't this really a packaging/distribution thing?  Anyone not building with LuaJIT should ensure bitop is pulled in when installing neovim.  Not sure why we need to do anything in core other than installing bitop for PUC LUA when bundled deps are being used, which is already done.

**Comment by clason** [comment]
That works; then plugins are free to assume that `require'bit'` is available.

**Comment by clason** [comment]
> definitely, let's do it. We need this to close #11301

This means we need _either_ this _or_ #11301, right? (Either we bundle a compat module -- in which case I suggest we just add the pure Lua fallback from plenary -- or make `bit` a hard requirement for external dependencies.)

**Comment by bfredl** [comment]
IMHO let's bundle the bitop C extensions (and expect distros to make it available). Lua C extension dependencies is more of a rule than a exception at this point.

**Comment by Hanymato** [comment]
81560bbdbf7b2fce282b740de6a7bf9b3879a969
