### ISSUE TITLE
Feature request: nvim_open_win 'minimal' style, please also disable 'colorcolumn'

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#11361]
Hello,

I am doing some floating window development and I notice that the `minimal` style of [nvim_open_win](https://neovim.io/doc/user/api.html#nvim_open_win()) currently disables:

- `number`
- `relativenumber`
- `cursorline`
- `cursorcolumn`
- `foldcolumn`
- `spell` 
- `list`

I believe [`colorcolumn`](https://vimhelp.org/options.txt.html#%27colorcolumn%27) should be added to that list.

**Comment by justinmk** [comment]
how about a PR (with updated test)?

**Comment by bluz71** [comment]
Sure, after I finish my current floating window work I will try and figure that out.....noting that I've never built Neovim before.

How can it be :)

**Comment by bluz71** [comment]
#11427 has been merged. Task complete.
