### ISSUE TITLE
Crash on multiple startup errors with --headless

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#11362]
- `nvim --version`: NVIM v0.5.0-144-g568900806
- `vim -u DEFAULTS` (version: ) behaves differently? N/A AFAICT
- Operating system/version: Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Terminal name/version: kitty 0.13.1
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Use the following init.vim:
```
call
```

Then run the following
```
nvim -u init.vim -c "call " --headless
```

### Actual behaviour
```
Press ENTER or type command to continuenvim: /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/message.c:2234: msg_scroll_flush: Assertion `to_scroll >= 0' failed.
zsh: abort (core dumped)  nvim -u /tmp/nvim/init.vim -c "call " --headless
```

### Expected behaviour
No crash.

**Comment by glacambre** [comment]
Just removing this assert is enough:

https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/src/nvim/message.c#L2266

The reason this works is that the rest of the code is careful to make sure to_scroll is larger than 0:

https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/src/nvim/message.c#L2270

So perhaps it's ok to just remove the assert?

**Comment by justinmk** [comment]
No crash with the repro steps on b3453ea4a6b6

The assert is still there: https://github.com/justinmk/neovim/blob/307c5c63e17735aa493a43da6d514d00034e9b71/src/nvim/message.c#L2373
