### ISSUE TITLE
CI: static analysis: analyze with LGTM

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#11364]
LGTM is [part of GitHub](https://blog.semmle.com/secure-software-github-semmle/) now. But we need to enable it somehow.

In particular it enables sophisticated querying: 
https://blog.semmle.com/integer-overflow-libssh2/

**Comment by XVilka** [comment]
It is easy - just enable this app: https://github.com/marketplace/lgtm

**Comment by glacambre** [comment]
Looks like this issue can be closed :)
