### ISSUE TITLE
Neovim integration feedback

### ISSUE THREAD

**Issue by asvetliakov** [neovim/neovim#11367]
Hello guys, i'm author of [vscode-neovim](https://github.com/asvetliakov/vscode-neovim) extension which fully integrates neovim into VSCode. I think i've got some success here and want to provide some real API feedback based on my integration experience.

Firstly, thank you for all your work, it's really awesome and looking forward into future releases.

My extension works by synchronizing VScode buffer and neovim buffer and vice-versa, and, more importantly, delegating insert mode only to VS Code. Due to current state of the modern editors (code-completions, quickfixes, error reporting and other many editor operations) i think this is most straightforward way to do things - let vscode/editor handle the insert mode (which is doing much better anyway than neovim) and neovim handle other modes (which is pain to simulate properly/fully).

So suggestions/issues:

Buffer API:
1) The life will be much more easier if neovim will support something like ```nvim_buf_set_characters```, i.e. inserting/replacing some text not by lines, but by character range.
2) i was really surprised when calling ```nvim_call_atomic``` with several ```nvim_buf_set_lines``` calls was resulted to multiple buffer ```_lines``` event. It was not really an issue though, but i'd except atomic operation (from the name of ```call_atomic```) and one event.
3) Would be good if there will be a param to **NOT** send ```_lines``` event after calling ```nvim_buf_set_lines```. Also, not real issue since there is buffer ```tick```. But won't hurt

Redraw event:
1) It's not possible to correctly track the real cursor position (not screen position) in a buffer without making external call to get the cursor. The problem that then you do ```G``` from, say, top of the file - you won't get ```grid_scroll``` event so cursor position will be lost. Currently i'm calling ```nvim_win_get_cursor``` every time when i need to update cursor in editor, but i don't think this is optimal.
Adding something like ```win_cursor_goto``` or ```buffer_cursor_goto``` will help very much. Or just sending ```grid_scroll``` event every time when cursor moves offscreen. (I remember there was already an issue with scroll events, so writing again as reminder)

2) Main issue - Highlight states:
It's currently not possible to get HL states for a whole buffer (setting winheight won't help since it slows down neovim and there is anyway restriction to 999 lines)
Ideally something like ```nvim_buf_get_highlights``` with lists of interested HL groups (don't need Normal group highlights and syntax-coloring related for example) will help very much for clients who are not interested with redrawing information from neovim. I think it should be already stored internally for a whole buffer somewhere so it shouldn't be hard to expose it.

3) Don't need ```lines``` / ```grid_lines``` event at all if there will be API to get HL states. So toggle/ui-option to get only cursor updates will be very good to save rpc bandwidth

General:
1) It's not possible to properly set screenline position without hacks. The issue here - the gui client owns scrolling, when the screen position is changed , it needs to send updated screenline position to neovim (otherwise things like easymotion won't work correctly). Currently there is no API to do that, and i'm resorting to hack with sending ```20<C-e>``` after scroll for example

Thank you again for the great vim experience, if you want i can create separates issues for each my point above.

**Comment by bfredl** [comment]
> It's currently not possible to get HL states for a whole buffer (setting winheight won't help since it slows down neovim and there is anyway restriction to 999 lines)
Ideally something like nvim_buf_get_highlights with lists of interested HL groups (don't need Normal group highlights and syntax-coloring related for example) will help very much for clients who are not interested with redrawing information from neovim. I think it should be already stored internally for a whole buffer somewhere so it shouldn't be hard to expose it.

Some of this has been discussed before, see https://github.com/neovim/neovim/issues/9421#issuecomment-477931420. In short: we want to do this, but no one has had the time to work on it yet.

**Comment by bfredl** [comment]
> i was really surprised when calling nvim_call_atomic with several nvim_buf_set_lines calls was resulted to multiple buffer _lines event. It was not really an issue though, but i'd except atomic operation (from the name of call_atomic) and one event.

"atomic" is w.r.t. other concurrent event sources, it doesn't really affect undo/buffer updates etc. However,  buffer updates in general could be optimized quite a bit. Though the buffer update protocol doesn't support multi-range updates to start with. We should add this along with byte-resolution updates where it will matter even more.

**Comment by justinmk** [comment]
@asvetliakov I'm very happy to  see this! 

> delegating insert mode only to VS Code. Due to current state of the modern editors (code-completions, quickfixes, error reporting and other many editor operations)  ... let vscode/editor handle the insert mode 

That's a good tradeoff, and avoids lots of complication. 

Alternatively the tradeoff I've suggested is to make the IDE "dumb" and let Nvim control  the editor entirely, discarding IDE completions/highlighting/popups--for people like me, who only want the IDE for refactoring/navigation and opt-in to binding Nvim keys to call IDE APIs. 

Either tradeoff is good.

> `nvim_buf_set_characters`, i.e. inserting/replacing some text not by lines, but by character range.

We definitely want this. Can you create a separate issue for this?

> 2\. something like `nvim_buf_get_highlights` with lists of interested HL groups (don't need Normal group highlights and syntax-coloring related for example) will help very much for clients who are not interested with redrawing information from neovim. I think it should be already stored internally for a whole buffer somewhere

N/Vim doesn't do whole-buffer highlighting unless user does `:syntax sync fromstart`, which can be really slow. See also https://github.com/neovim/neovim/issues/9421#issuecomment-477174643



> 3\. Don't need `lines` / `grid_lines` event at all if there will be API to get HL states. So toggle/ui-option to get only cursor updates will be very good to save rpc bandwidth

Please create a separate issue.

> 1. set screenline position without ... `20<C-e>` 

Please create a separate issue.

**Comment by justinmk** [comment]
@asvetliakov btw from your [readme](https://github.com/asvetliakov/vscode-neovim#vim-easymotion):

> original vim-easymotion works fine and as expected... except one thing: it really replaces your text with markers then restores back. It may work for VIM but for VS Code it leads to broken text and many errors reported while you're jumping. For this reason i created the special vim-easymotion fork 

I thought vim-easymotion has a mode which uses "conceal" instead of replacing text. If not, [vim-sneak](https://github.com/justinmk/vim-sneak/) works like that. Maybe it's useful.

**Comment by asvetliakov** [comment]
@justinmk No, it doesn't. I'm happy with easymotion fork now. Also it's much more powerful, and the dimming is very nice-eye (missed it in VSCodeVim), and i'd recommend to use it instead with vscode
![image](https://user-images.githubusercontent.com/8881674/68563295-5d263780-044d-11ea-908d-998ec94a14d6.png)


Thanks for pointing me to #9421
