### ISSUE TITLE
Api request: buffer insert/replace by character range

### ISSUE THREAD

**Issue by asvetliakov** [neovim/neovim#11368]
From #11367 

It'd be good if neovim will support something like ```nvim_buf_set_characters```, i.e. inserting/replacing some text not by lines, but by character range.

**Comment by bfredl** [comment]
:+1:  This will be needed to preserve extmarks in changed text anyway.

**Comment by muniter** [comment]
Isn't this already solved by https://github.com/neovim/neovim/pull/11833 ?

**Comment by clason** [comment]
Looks like it, yes. If this is not what you need, feel free to open a new issue describing what exactly is missing!
