### ISSUE TITLE
UI: emit mouse_on/mouse_off on attach

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#11372]
Here are two things that would make mouse support in GUIs easier/better in my opinion:

- When connecting to Neovim, GUIs do not receive a mouse_on/mouse_off event. This event is however sent when users chose to change the value of their `mouse` setting. It would be nice if this event was sent automatically, like `guifont` currently is.

- When users deactivate mouse support (with `set mouse=`), neovim still reacts to `nvim_input_mouse` calls. In my opinion it shouldn't. You could argue that since `mouse_on`/`mouse_off` events are sent by neovim, it should be the GUI's job to track whether it should call `nvim_input_mouse` or not; but I tend to prefer the idea of having dumb GUIs that maintain as little state as they can. Since both ways of seeing things make sense to me, I won't argue if you disagree :)

**Comment by justinmk** [comment]
>  When connecting to Neovim, GUIs do not receive a mouse_on/mouse_off event

👍  we send `option_set` on attach but I guess not mouse_on/mouse_off. 

> When users deactivate mouse support (with `set mouse=`), neovim still reacts to `nvim_input_mouse` calls. ... I tend to prefer the idea of having dumb GUIs that maintain as little state as they can. 

True, but `option_set` is inherently stateful, and `mouse_on/off` is part of that. Wouldn't the UI client want to avoid sending needless calls anyway?
