### ISSUE TITLE
"Sandbox" / "Capabilities" for VimScript

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#11374]
(It's hard to search the issue tracker for this kind of thing, so I gave it a shot and didn't find anything, but I suspect I'm not the first person to have this sort of idea, so apologies in advance...)

I want to be able to run some commands (vimscript, arbitrary normal mode things, etc.) but revoke specific capabilities while running them.

The specific usecase I started with is I do not like plugins adding mappings, so the first thing I generally do when finding a new plugin is finding the way to get it to not add any mappings.

Better though than trolling through every plugin's documentation, it'd be great if I could instead write (in Python-y pseudocode, and vim-plug-like plugin management):

```
with remove_capability('map')
    Plug 'some/plugin'
endwith
```

(I assume there's at least some trickiness here around autoloading and when specifically the map happens, which maybe I'm hand waving over, but I imagine if such a feature was added to nvim that the last mile might be tractable, but who knows)

So that specific capability revocation would be super useful to me. But I suspect there are others that might be nice (all the above not for "security" purposes, just to ensure some vim code doesn't do specific things that you want to guarantee it doesn't do). As 2 other examples, revoking the ability to set specific autocmds, or revoking being able to set global variables seem like two other things that may be useful.

It'd seemingly also be nice if one could either have the revoked capability 1) silently succeed or 2) error.

Hopefully this is the right place to discuss such a thing assuming it's not obviously either 1) a bad or ridiculously hard to implement idea or 2) already discussed somewhere else.

**Comment by Julian** [comment]
Oh -- and one more thing, I know this would essentially be "ridiculously hard to implement" if it had to cover every single thing, but I was hoping to handwave that part a bit too by saying presumably if the initial list were small it's more easy to think about?

**Comment by justinmk** [comment]
Adding hacks to fix bad plugins is the wrong way to go about this. https://github.com/neovim/neovim/issues/11274 is similar request, see my reply there:

> Duplicate of #11116 .
> 
> However, this particular use-case is not a strong motivation:
> 
> > don't want any plugin to map any sequence that begins with `\c`. But I know several plugins do this,
> 
> Users should very much file bug-reports on such plugins. The Vim ecosystem is made better when people insist on well-behaved plugins. Fighting plugins via config-tricks will make everything more complicated: for plugin-authors, users, and troubleshooting.
> 
> "Well-behaved" here means economy of mappings. Plugins should define `<Plug>(foo)` mappings, and otherwise avoid default mappings. Mapping to _leader_ is specially bad behavior for a plugin.

File bugs on the bad plugins. Adding local workarounds compounds the problem because it weakens community conventions (plugin authors won't know about best practices unless users file reports).

Nevertheless, #11116 would allow you to go nuts adding workarounds.
