### ISSUE TITLE
Provide framework for adding benchmark tests

### ISSUE THREAD

**Issue by myitcv** [neovim/neovim#1137]
Per [comments](https://github.com/neovim/neovim/pull/1107#issuecomment-54426367) in #1107, creating this issue as a placeholder for some form of benchmark framework. Ideas discussed on the linked thread include (but are not limited to):
- Benchmarking of functions, e.g. `matchadd`, under varying conditions (e.g. `matchadd` would need to be tested against a large file with many calls to `matchadd`)
- Some means of tracking benchmarks over time as part of the Travis CI to spot improvements/regressions
- Some means of comparing vs. Vim's performance

**Comment by justinmk** [comment]
Not actionable.
