### ISSUE TITLE
Crash when oppening a file that is already open in another instance of neovim

### ISSUE THREAD

**Issue by Yohannfra** [neovim/neovim#11379]
- `nvim --version`: NVIM v0.5.0-23-gafd576ee9
- `vim -u DEFAULTS` (version: ) behaves differently? Yes, it doesn't crash and exit status is 1
- Operating system/version: Linux yohann-ThinkPad-T480s 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Terminal name/version: # GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2
- `$TERM`: xterm-256color

### Steps to reproduce
```shell
nvim file.txt
# leave it open and go to an other terminal
nvim file.txt
# it says 'Found a swap file by the name file.txt ...'
press q
```
### Actual behaviour
crash
### Expected behaviour
no crash

**Comment by mhinz** [comment]
I just built that version and it worked as expected, so without further info there's not much that we can do.

A [backtrace](https://github.com/neovim/neovim/wiki/FAQ#backtrace-linux) would be useful.

**Comment by Yohannfra** [comment]
I think the crash is not from nvim but from a plugin i use, this issue doesn't belong here then.
Sorry about it.
