### ISSUE TITLE
Download-link to 0.4.3 Assets leads to 0.4.2 packages

### ISSUE THREAD

**Issue by thomas-haslwanter** [neovim/neovim#11371]
The download link in the Assets for
https://github.com/neovim/neovim/releases/tag/v0.4.3
leads to 0.4.2 packages (at least for the 32 and 64 bit Windows versions)

**Comment by justinmk** [comment]
When exactly did you last try ?

**Comment by thomas-haslwanter** [comment]
I re-tried it again just now - with the same result.
Just to be exact:
I downloaded
https://github.com/neovim/neovim/releases/download/v0.4.3/nvim-win64.zip
from the page
https://github.com/neovim/neovim/releases/tag/v0.4.3
When you go into that archive, it is from September, and nvim opens as 0.4.2 :(

**Comment by ashfinal** [comment]
I'm running the nightly version on windows 10. But I just did a check, it seems the files that respectively downloaded from
https://github.com/neovim/neovim/releases/download/v0.4.3/nvim-win32.zip
https://github.com/neovim/neovim/releases/download/v0.4.2/nvim-win32.zip
share a same md5sum: 5001e55c005ad4e5df8bb0d0b3ebf2fe

**Comment by h-michael** [comment]
@justinmk Could you update binary?

**Comment by justinmk** [comment]
This is fixed since the last hour. I checked and re-checked.

Also debugged the update script, and found nothing wrong with it. Re-running the CI job did the right thing as well. No idea why it kept getting 0.4.2 previously.

**Comment by h-michael** [comment]
@justinmk I checked again, 0.4.3 was distributed. Thank you for the response.
