### ISSUE TITLE
`nvim_win_close()` raises `E11` and `E5555` from the command-line window

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#11387]
- `nvim --version`: NVIM v0.5.0-156-gdb436d527
 - `vim -u DEFAULTS` (version:  8.1 Included patches: 1-2297) behaves differently? `nvim_win_close()` does not exist in Vim
 - Operating system/version: Ubuntu 16.04.6 LTS
 - Terminal name/version: XTerm(322)
 - `$TERM`: xterm-256color

### Steps to reproduce

Run this shell command:

    nvim -Nu NONE +sp

Press `q:` to open the command-line window, then run `:call nvim_win_close(win_getid(1), 0)`.

### Actual behaviour

The errors `E11` and `E5555` are raised:

    E5555: API call: E11: Invalid in command-line window; <CR> executes, CTRL-C quits

The first window is not closed.

### Expected behaviour

No error is raised, and the first window is closed.

### Additional information

This causes [an issue](https://github.com/andymass/vim-matchup/issues/80) in the `vim-matchup` plugin, where a floating window stays opened when it should have been closed.

**Comment by lacygoill** [comment]
Now that I think about it, the fact that `nvim_win_close()` fails when run from the command-line window may be intentional, I don't know.

On the one hand, you can run `:1close` from the command-line window without any error being raised (contrary to `nvim_win_close()`). On the other hand, it fails to close the first window (like `nvim_win_close()`); it just closes the command-line window.

In any case, I don't know if it's possible, but it would be nice if `nvim_win_close()` could be invoked to at least close a floating window from the command-line window.

**Comment by lacygoill** [comment]
Never mind, it's [working as intended](https://github.com/neovim/neovim/issues/9767#issuecomment-475192895), sorry for the noise.

**Comment by bfredl** [comment]
As a workaround, we could allow to hide the float if not closing it (the later which implies destroying the window struct and a lot of autocmds which might not be expected in cmdline window). "hide" and "sticky" flags is on my TODO list for floats..

**Comment by lacygoill** [comment]
> we could allow to hide the float if not closing it

That would make sense, and it would help fix the issue in `vim-matchup`; thank you very much for your work on these features.

**Comment by andymass** [comment]
I thought the point of this nvim function was to close a window no matter where you are?

**Comment by bfredl** [comment]
@andymass Though cmdline window is a very special place in vim, not a place like "no matter where".
