### ISSUE TITLE
`nvim -r` hangs if the output is "too long"

### ISSUE THREAD

**Issue by jamessan** [neovim/neovim#11386]
- `nvim --version`: 0.4.3
- Operating system/version: CentOS 7.3
- Terminal name/version: tmux 1.8 (inside putty)
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

#11181 helped in that we can actually _see_ the swapfile information, but if there are more than a couple entries, we hang.

1. Cause there to be more than 3 swapfiles in `'directory'`
2. Run `nvim -u NORC -r`

### Actual behaviour
nvim displays 2.5 entries of swap information and then hangs.

```
Swap files found:
   In directory ~/.local/share/nvim/swap//:
1.    %home%user%path%to%fileA.swp
          owned by: user   dated: Wed Sep 25 14:35:05 2019
         file name: ~user/path/to/fileA
          modified: no
         user name: user   host name: myhost
        process ID: 26124
2.    %home%user%path%to%fileB.swp
          owned by: user   dated: Fri Oct 25 17:37:54 2019
         file name: ~user/path/to/fileB
          modified: YES
         user name: user   host name: myhost
        process ID: 16402
3.    %home%user%path%to%fileC.swp
          owned by: user   dated: Fri Oct 25 14:46:11 2019
         file name: ~user/path/to/fileC
          modified: 
```

I have to use Ctrl-c to kill nvim.

### Expected behaviour
All swapfile entries are displayed and nvim exits cleanly.

**Comment by jamessan** [comment]
It seems to be more related to amount of bytes displayed, rather than number of files.  When I get rid of some of the swapfiles with longer paths, then more entries are displayed before the hang.

**Comment by blueyed** [comment]
Seems to be a generic issue with `--headless`: `nvim -c 'for i in range(0, 1000) | echo i | endfor' --headless` also hangs (after 22 for me).
/cc @bfredl

**Comment by grational** [comment]
I can confirm the behavior also in the 0.5.0 pre-release version. Pretty annoying considering I cannot recover my swap files :/

**Comment by justinmk** [comment]
> Pretty annoying considering I cannot recover my swap files :/

@grational does `:recover` command not work instead?

**Comment by grational** [comment]
@justinmk thank you for your suggestion, it works to process a single file. The issue for me is related to the methodology I use to recover all my orphan swap files after a crash. 

I use [this little shell script I have written on my own some time ago](https://gist.github.com/grational/57f02243f2b2d77a0c305a14817004fe) to process all the orphan files and delete the swap file if it's the case. The script leverages the `nvim -r {file}` option, maybe I have to review it to find some alternative approach.

**Comment by carlobaldassi** [comment]
As a workaround, I have found (by chance) that using Ex mode, as in `nvim -re`, seems to fix the problem. No idea why.
