### ISSUE TITLE
Reproducible floating window crash when used with wincmd

### ISSUE THREAD

**Issue by norcalli** [neovim/neovim#11383]
Version 0.4.2 to current master

```lua
local api = vim.api
local should_crash = true
local function crashes(contents)
  local floating_bufnr = api.nvim_create_buf(false, true)
  local floating_winnr = api.nvim_open_win(floating_bufnr, true, {
    relative = 'cursor';
    style = should_crash and 'minimal' or nil;
		row = 0; col = 0;
    height = #contents;
    width = 10;
  })
  api.nvim_buf_set_lines(floating_bufnr, 0, -1, true, contents)
  local floating_win = api.nvim_call_function('win_id2win', {floating_winnr})
  api.nvim_command("wincmd p")
  api.nvim_command("autocmd CursorMoved * ++once "..floating_win.."wincmd c")
  return floating_bufnr, floating_winnr
end
crashes{"foo"}
crashes{"bar"}
```

`nvim -u NORC +"luafile buggy.lua"` will cause a crash.

Discovered from old LSP code. The style affects this for some reason, so if you change `should_crash` to false, it stops crashing.

Every piece here is essential to the conditions for crashing: 

- Removing `...CursorMoved...` will not cause a crash
- Removing `wincmd p` will not cause a crash
- Not entering with (i.e. `enter=false` for  `nvim_open_win(..., enter`) will not cause a crash

This leads me to suspect that the issue is due to `wincmd` for a closed window, but I'm not certain. @bfredl

**Comment by justinmk** [comment]
crashing in `win_set_minimal_style` . Doing some debugging, I see that `win_valid(wp)` is false just after  the ` win_enter(wp,...)` call in `nvim_open_win`.

```
ERROR 2019-11-28T22:59:42.093 8437  win_new_float:576: xxx new win: 0x1684a60
ERROR 2019-11-28T22:59:42.094 8437  win_new_float:576: xxx new win: 0x1688870
ERROR 2019-11-28T22:59:42.095 8437  nvim_open_win:1102: xxx after win_enter: 0x1688870
ERROR 2019-11-28T22:59:42.098 8437  win_new_float:576: xxx new win: 0x1694dd0
ERROR 2019-11-28T22:59:42.099 8437  win_close:2433: xxx closing win: 0x1694dd0
ERROR 2019-11-28T22:59:42.099 8437  nvim_open_win:1102: xxx after win_enter: 0x1694dd0
```

Looks like `win_enter` triggers the `CursorMoved` event which closes the just-created window, which is then invalid further in the codepath.
