### ISSUE TITLE
Question) How can I get the 64-bit Version for Windows?

### ISSUE THREAD

**Issue by thekpaul** [neovim/neovim#11397]
Both Chocolatey and `.zip` installations show that `nvim-qt.exe` is 32-bit on the Windows Task Manager, and apart from this I can't seem to find any other information about this issue. Is it possible to get a 64-bit version of Neovim on Windows 10 for the latest version?

**Comment by justinmk** [comment]
64bit packages  for macOS, Windows, and Linux  are built daily and uploaded to:

https://github.com/neovim/neovim/releases
