### ISSUE TITLE
Typo in documentation (powershell)

### ISSUE THREAD

**Issue by Exisar** [neovim/neovim#11403]
- `nvim --version`: 0.4.4
- Operating system/version: Windows 10 64 bit
- Terminal name/version: nvim-qt, powershell, command prompt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`
1. Open nvim
2. Run command ":help powershell"

The documentation has a typo. The code should not set "shellquote=(".

### Actual behaviour
set shell=powershell **shellquote=(** shellpipe=\| shellxquote= 

### Expected behaviour
set shell=powershell **shellquote=** shellpipe=\| shellxquote=

**Comment by mhinz** [comment]
Hi, this is already fixed on master: https://github.com/neovim/neovim/commit/51f2826f617532aaf5d682dfc3229f3723427ce6
