### ISSUE TITLE
Netrw obliterates the default register when 'g:netrw_banner' is set to 0 and the text in the register has some apostrophes in it

### ISSUE THREAD

**Issue by TyOverby** [neovim/neovim#11405]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: 8.1) behaves differently: Yes.  It works as expected.
- Operating system/version: Cent OS (custom build, don't know actual build number)
- Terminal name/version: Kitty 0.14.6
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
echo "" > a.txt 
printf "abc\n'a 'b 'c\n" > b.txt
nvim -u NORC b.txt

# yank the second line in b.txt ("''a 'b 'c")

# set the option to disable the netrw_banner
: let g:netrw_banner = 0

# open newtrw via an edit on the current directory
: edit . 

# navigate to a.txt

# paste via `p` or `"+p`

```

### Actual behaviour
The contents of the register have been replaced with a newline.

### Expected behaviour
The contents of the register should have remained `'a 'b 'c`

### Interesting details
- This weird behavior does not occur when the yanked text doesn't contain apostrophes
- This weird behavior does not occur when the netrw-bannner isn't disabled

**Comment by justinmk** [comment]
Thanks for reporting. We don't maintain netrw. Report this to https://github.com/vim/vim .

Workaround is to use something that isn't netrw (which is garbage).

**Comment by TyOverby** [comment]
@justinmk do they accept big reports that only repro in neovim?

**Comment by justinmk** [comment]
No, but that should have been mentioned here:

> `vim -u DEFAULTS` (version: **x.y.z**) behaves differently? **Yes**.

**Comment by TyOverby** [comment]
Ah dang, sorry about that.  I had all that info in my editor and must have forgotten to move it over.

I've updated the issue with the requested details.

**Comment by edi9999** [comment]
This seems to be an issue in netrw that has however been fixed : 

See : http://www.drchip.org/astronaut/vim/doc/pi_netrw.txt.html

```
12. History						*netrw-history* {{{1

	v167:	Nov 29, 2019	* netrw does a save&restore on @* and @+.
				  That causes problems with the clipboard.
				  Now restores occurs only if @* or @+ have
				  been changed.
				* netrw will change @* or @+ less often.
				  Never if I happen to have caught all the
				  operations that modify the unnamed
				  register (which also writes @*).
				* Modified hiding behavior so that "s"
				  will not ignore hiding.
	
```

**Comment by edi9999** [comment]
When I look at the diff, I see that there are somethings related to clipboard :

![image](https://user-images.githubusercontent.com/2071336/70975294-ef9fa380-20a9-11ea-96d5-9079cc47d540.png)

**Comment by justinmk** [comment]
> When I look at the diff, I see that there are somethings related to clipboard :

That's from https://github.com/neovim/neovim/commit/6c22c7ab97cca9f8dda6863ee7f1db1ce30a3451, which was pushed 1 month _after_ this issue was reported.

**Comment by edi9999** [comment]
I personally remember encountering this bug only since about a week or so, maybe it was longer but I probably can't remember it.

The diff I attached was the one between nvim and vim on master : 

icdiff vim/runtime/autoload/netrw.vim neovim/runtime/autoload/netrw.vim

**Comment by edi9999** [comment]
> Workaround is to use something that isn't netrw (which is garbage).

When you say that, which one do you recommend ? I have been using nerdtree 2 years ago, but I went back to netrw with vim-vinegar which I find minimal enough, if I remember correctly Nerdtree tries to mimick IDEs more or less

**Comment by blueyed** [comment]
For reference: netrw v167 was added to Vim in https://github.com/vim/vim/commit/91359014b359cf816bf943fe2c7d492996263def.

**Comment by edi9999** [comment]
up @justinmk , I'm not sure what I should do but the issue persists with current Neovim : 

neovim-0.5.0+ubuntu1+git202001032018-234232f-00e710e=.

**Comment by rsdenijs** [comment]
What is the status on this issue? It hits me quite often when copy-pasting from one file to another.

**Comment by tcoopman** [comment]
I've fixed this locally by autoloading https://raw.githubusercontent.com/vim/vim/master/runtime/autoload/netrw.vim
