### ISSUE TITLE
Semicolon colon mapping  breaks Alt mappings

### ISSUE THREAD

**Issue by Avi-D-coder** [neovim/neovim#11413]
- `nvim --version`:NVIM v0.5.0-167-g91f4bb0ae
Build type: RelWithDebInfo
LuaJIT 2.0.5
- Operating system/version: Arch Linux
- Terminal name/version: kitty, xterm, konsole
- `$TERM`:xterm-256color

### Steps to reproduce
minirc.vim
```vim
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>
" this breaks alt keys
nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;
```

```
nvim -u minirc.vim
:vsp
<A-Right>
```
Nothing happens

#### Behavior Expected
Without `;` `:` mappings: Switches windows

**Comment by justinmk** [comment]
use `nnoremap`, not `nmap` . Else you've told the editor to do exactly the behavior you've reported.
