### ISSUE TITLE
:terminal : bracketed paste support

### ISSUE THREAD

**Issue by randomizedthinking** [neovim/neovim#11418]
- `nvim --version`: v0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently? No.
- Operating system/version: Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux
- Terminal name/version: urxvt-256color
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:term
ipython3
## then paste some codes into the ipython3 with indentations
```

### Actual behaviour

The terminal buffer does not support bracketed paste. Below is a screenshot of the paste operation under: vim terminal buffer (left) vs a pure terminal (right).

![image](https://user-images.githubusercontent.com/5283430/69080091-296c8400-09f0-11ea-98fe-af64a0866c78.png)

### Expected behaviour

I'd expect the terminal buffer would support bracketed paste mode.

The bracketed paste mode is supported by nvim well. Yet, terminal buffers need to be treated differently that the escape sequence should be passed to the underlying terminal such that they know that the incoming text is from a paste operation.

**Comment by justinmk** [comment]
I suppose `:terminal` should wait for applications to request the mode, thus we can't always just wrap stuff in bracketed-paste delimiters.

Anyways, we definitely have wanted this, just no one has found the time to do it. Help wanted.

**Comment by teto** [comment]
@randomizedthinking does the linked PR fix your issue ?

**Comment by echasnovski** [comment]
@teto, @justinmk, I can confirm that #12080 solves this issue. I installed version from that PR and bracketed paste into terminal works as expected (at least in basic scenarios of pasting multiline statements). This greatly improves day-to-day work with interactive REPLs.

**Comment by randomizedthinking** [comment]
@teto @justinmk Yes, the PR solves the issues.

Apologize for getting back to it so late.

**Comment by echasnovski** [comment]
@randomizedthinking, I would suggest to keep this issue open as the PR is not yet merged and it might help maintainers to see that problem still exists.

**Comment by randomizedthinking** [comment]
Thanks, @echasnovski...
