### ISSUE TITLE
E886: System error while opening ShaDa file

### ISSUE THREAD

**Issue by sajusat** [neovim/neovim#11425]
- `nvim --version`: v02.2

- Operating system/version: Ubuntu 18.04
- Terminal name/version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
- `$TERM`: xterm-256

Opening any file gives me the following 

```
E886: System error while opening ShaDa file /home/saju/.local/share/nvim/shada/main.shada for reading: permission denied
Press ENTER or type command to continue
```

Quitting the editor give me 

```
E886: System error while opening ShaDa file /home/saju/.local/share/nvim/shada/main.shada for reading to merge be
fore writing it: permission denied
E886: Failed to create directory /home/saju/.local/share/nvim/shada for writing ShaDa file: permission denied
```

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/9912#issuecomment-555525048

**Comment by tibix** [comment]
I had a similar issue on MacOS Monetery (12.8), but the path was a bit different: /Users/myuser/.local/state A quick solve  for me was to `chown` ~/.local/state/ to my user as it was set for the root user for some reason.
