### ISSUE TITLE
After upgrade to 0.4.3, color of terminal emulator in nvim is inconsistent with the outside

### ISSUE THREAD

**Issue by epheien** [neovim/neovim#11422]
https://github.com/neovim/neovim/commit/b772b86d2ba256a2c03ab701d00b322cf52560e0
this commit remove "highbright bold" color, but in iTerm2 on macOS, this color is turn on default.

Is there a way to trun on "highbright bold" manually?

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by bfredl** [comment]
@epheien This problem is generally solved in nvim 0.5 (you can use it on master already). Nvim 0.5 will adapt to what the host terminal emulator does, as if by magic.
