### ISSUE TITLE
man.vim: use hard wrap instead soft wrap

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#11436]
See https://github.com/neovim/neovim/pull/9023 for background discussion.

man.vim was changed to use vim's native wrapping by default instead of man's normal wrapping 

However, this interacts poorly with the formatting of many man pages. Some previous discussion of this is at https://github.com/neovim/neovim/issues/10748 regarding tables but I find it results in poor formatting in general.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/10180857/69385529-b1bb8500-0c8d-11ea-8477-13fed6dae355.png">

As you can see, the header has been poorly formatted because man.vim sets $MANWIDTH to 999.

Similar situation with the footer.

https://github.com/neovim/neovim/blob/525bb1b55d8771939f0a9d72a532abc8f2134445/runtime/autoload/man.vim#L142

We should just hard wrap by default and not support the native vim wrapping imo. There's no good way to make it fool proof.

At the very least, given the issues, it should not be the default.

There is also precedence for hard wrapping by default as that is `:help`'s behaviour.

Another reason its nice to hard wrap by default is my terminals can be wide but I rarely want my text to span the full width, it's much easier to read narrow. Vim's soft wrapping as of now always goes end to end with the window, you can't set an arbitrary width.

**Comment by justinmk** [comment]
Did you try `g:man_hard_wrap` ? https://github.com/neovim/neovim/pull/9633

I rarely see issues with softwrap, and it works better when resizing windows.

**Comment by nhooyr** [comment]
I am using hard_wrap. This issue is about making it the default instead though. Its interesting to see that you haven't had any issues. I've seen frequent problems across both MacOS and Linux. I strongly think this should be opt in. Hard wrap never fails (aside from #9017 which is a very minor defect).

E.g. see the stdio_ext man page on linux:

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/10180857/69446475-8171f600-0d22-11ea-8e84-2f3dc62fbe74.png">

If you remain unconvinced, how about we remove `g:man_hard_wrap` and instead if $MANWIDTH is already set, use it instead of overriding with 999 and using soft wrap.

If $MANWIDTH is set, it's clear the user wants hard wrapping (or soft wrapping if they set $MANWIDTH=999).

**Comment by justinmk** [comment]
> E.g. see the stdio_ext man page on linux:

What's the problem?

> if $MANWIDTH is already set, use it 

Sounds good. But that's not equivalent to g:man_hard_wrap ...

**Comment by nhooyr** [comment]
> Sounds good. But that's not equivalent to g:man_hard_wrap ...

In the case MANWIDTH is empty its not, but we can add another option for that instead.

> What's the problem?

The header is too long and spans multiple lines. Likewise with the footer. The long lines of text also make it much harder to read. Pretty much every user of `man` and `:h` is used to hard wrapped formatting and so it should remain the default.

**Comment by justinmk** [comment]
> In the case MANWIDTH is empty its not, but we can add another option for that instead

Another different option isn't really better. Also it's not the same in any case because `g:man_hard_wrap` adapts to the current editor dimensions, whereas MANWIDTH does not.

> The header is too long and spans multiple lines. Likewise with the footer

That seems totally unimportant to me, but that is also a bug that could be fixed with some clever logic :)

> Pretty much every user of man and :h is used to hard wrapped formatting and so it should remain the default

Users who don't want anything to change could just use plain old `man` ...

**Comment by nhooyr** [comment]
> Another different option isn't really better. Also it's not the same in any case because g:man_hard_wrap adapts to the current editor dimensions, whereas MANWIDTH does not.

I apologize, I got confused. I don't actually want to add any option. I meant if $MANWIDTH is set, use it. If not set, use the window width as $MANWIDTH. Then if a user wants to use soft wrapping, they set `$MANWIDTH=999` and it'll work automatically both on the CLI and in neovim.

> That seems totally unimportant to me, but that is also a bug that could be fixed with some clever logic :) Currently it just uses a very naive heuristic.

For someone used to the way my manpages appear for many years now, its very important. It completely threw me off the first time I saw it. I care a lot about aesthetics. Yes, we can fix it and make it just work but given the issues with table formatting which we cannot fix and that `:help` is hard wrapped, it makes more sense to hard wrap by default.

A default should just work and require no work arounds.

> Users who don't want anything to change could just use plain old man ...

`man.vim` is a strict improvement over plain old `man` in every single way except this one. This is preferential but default hard wrapping is more consistent with how manpages work, `:help` and means we don't have to implement any hacks on formatting.

**Comment by justinmk** [comment]
I don't agree but I'm willing to cave. Let's start by defaulting to `g:man_hard_wrap=1`.

**Comment by nhooyr** [comment]
> I don't agree but I'm willing to cave.

I appreciate that. Please reopen and feel free to assign me.

**Comment by nhooyr** [comment]
Another user report was at https://github.com/neovim/neovim/issues/9533
