### ISSUE TITLE
man.vim: add an option to disable bold highlighting

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#11435]
I prefer no bold highlighting in my manpages.

I can easily disable with:

```
hi manBold ctermfg=NONE ctermbg=NONE cterm=NONE gui=bold
```

Which works for terminal neovim because gui=bold prevents the default manBold group from becoming active.

It'd be nice to have an option for this.

**Comment by justinmk** [comment]
> It'd be nice to have an option for this.

`hi manBold` is the option. It guess we could document it though.

**Comment by nhooyr** [comment]
> hi manBold is the option. It guess we could document it though.

Yes but its not obvious. You can't just set it to none, you have to enable a property of the highlight group to prevent the default one from kicking in.

**Comment by justinmk** [comment]
If explicit `cterm=NONE` doesn't override a `default` highlight that's disappointing... but  `link` works instead (and we can document this snippet)

    :highlight link manBold Normal

**Comment by nhooyr** [comment]
> If explicit cterm=NONE doesn't override a default highlight that's disappointing

Yea I tried it first, it's definitely unfortunate.

That snippet sounds good to me. Please feel free to assign me this.

**Comment by BIKA-C** [comment]
Hello,  where should I put this command in the config? I tried to put it in `after/ftplugin/man.vim`, or my `init.lua`, but they all got overwritten. The config is loaded from `rtp/syntax/man.vim`. I am confused why `after/ftplugin/man.vim` wouldn't work. 

I tried both in shell
```shell
man 2 read
```
and in vim:
```
:Man 2 read
```
