### ISSUE TITLE
LSP client: Column value outside range

### ISSUE THREAD

**Issue by mcepl** [neovim/neovim#11448]
@norcalli

- `nvim --version`: from master @ d5aaad14e
- `vim -u DEFAULTS` (version: ) behaves differently? #NA for the Bram’s vim
- Operating system/version: openSUSE/Tumbleweed
- Terminal name/version: gnome-terminal 3.34.2
- `$TERM`: xterm-256color

### Steps to reproduce (cannot reproduce without plugins):

1. Open a Python script and attempt omnicompletion (via Ctrl-X,Ctrl-O with ``setlocal omnifunc=v:lua.vim.lsp.omnifunc``)
2. Save changed the script

### Actual behaviour
Plenty of errors:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp.lua:70: Vim(sleep):Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
"contrib/isaac.httpslib.py" 238L, 8640C uložen
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:377: Column value outside range
```

### Expected behaviour
No errors.

**Comment by norcalli** [comment]
@mhartington There have been a few changes to the lsp and omnifunc in the meantime. @mcepl is this still reproducible?

**Comment by mcepl** [comment]
OK, this evaporated. Still doesn’t cut prefix (see https://github.com/neovim/neovim/issues/11389#issuecomment-553817191), but this one is gone.

**Comment by kristijanhusak** [comment]
I'm getting the same error but on different line, for vimlsp. Here's the exact error:
```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:644: Column value outside range
```

min vimrc:
```vimL
set rtp+=~/path/to/nvim-lsp

autocmd VimEnter * lua require'nvim_lsp'.vimls.setup{}
autocmd Filetype vim setl omnifunc=v:lua.vim.lsp.omnifunc
```

How to reproduce:

1. Open any `.vim` file
2. Type this:
```vimL
function! s:map_item()
```
3. Once you closed the parenthesis, it shows the error.

I don't think it's issue in vimls language server plugin, since i don't get error with coc.nvim which uses the same language server.

I found this issue while using completion-nvim. Owner of completion-nvim found where the issue happens, but not why. Here's link to comment with details:
https://github.com/haorenW1025/completion-nvim/issues/52#issuecomment-622925867

**Comment by h-michael** [comment]
@kristijanhusak Would you show us lsp log around error occuring.

**Comment by kristijanhusak** [comment]
@h-michael Here's log with `trace` log level. I don't see any errors in it:

[vim-lsp.log](https://github.com/neovim/neovim/files/4585799/vim-lsp.log)

I tried error log level, but not getting any output from it.

But here's how I get it in neovim:
![screenshot](https://i.imgur.com/6E2lhnA.png)

**Comment by h-michael** [comment]
@kristijanhusak 
I reported this to vim-language-server.
https://github.com/iamcco/vim-language-server/issues/40

I think coc.nvim and vim-lsp round to 0 when "range.start.character" is less than 0.
However, I am wondering if this should be done on the client-side.

**Comment by kristijanhusak** [comment]
@h-michael works now, thanks!

**Comment by Slyces** [comment]
Hello guys! Following on this issue, I had a similar problem on a very specific, unusual code sample with pyls.

I described that issue in [haorenW1025/completion-nvim #57](https://github.com/haorenW1025/completion-nvim/issues/57) and to pyls [palantir/python-language-server/issues/800](https://github.com/palantir/python-language-server/issues/800).

**Comment by h-michael** [comment]
@Slyces I think it should be a language server bug, if not, please mention me.

**Comment by kristijanhusak** [comment]
@h-michael I'm having one more issue with typescript-language-server. It's this error, but something different:
```
Error executing vim.schedule lua callback: Vim:E220: Missing }.
```

This happens when I start typing property for an object. For example:
```js
const test = { f
```
Once I type `f`, it starts erroring out for each char I type, until I close the curly bracket.

Trace level logging doesn't log anything.

Is this issue with typescript language server or it's here?

**Comment by h-michael** [comment]
@kristijanhusak That is not the same issue with this issue.
Please file a new issue with that language server version and minimal reproduce steps.

**Comment by kristijanhusak** [comment]
Issue is not related to lsp, sorry for bothering.
