### ISSUE TITLE
Seg Fault when resizing window

### ISSUE THREAD

**Issue by iclanzan** [neovim/neovim#11458]
- `nvim --version`:
  ```
  NVIM v0.4.3
  Build type: Release
  LuaJIT 2.1.0-beta3
  Compilation:
  Compiled by nixbld

  Features: +acl +iconv +tui
  See ":help feature-compile"

     system vimrc file: "$VIM/sysinit.vim"
    fall-back for $VIM: "
  /nix/store/ps5swb84y288nl1llpr0mmkc6dp4s5j9-neovim-unwrapped-0.4.3/share/nvim
  "

  Run :checkhealth for more info
  ```
- Operating system/version:
  NixOS
- Terminal name/version: _Alacritty_, _urxvt_, _st_ are the ones I tried
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

1. `nvim -u NORC`
2. Press `<C-W> S` to create a split
3. `:te` to open a terminal
4. `<C-W> J` to go to other window
5. `<C-W> _` to maximize window

### Actual behaviour

`nvim` crashes with `Segmentation fault (core dumped)`.

### Expected behaviour

No crash.

**Comment by Noah11012** [comment]
I'm on the latest commit (36d1335)[https://github.com/neovim/neovim/commit/36d1335a667d54c26ab7cca23bc60998cb8e0fb2] and I do not get a segmentation fault.

**Comment by iclanzan** [comment]
I compiled https://github.com/neovim/neovim/commit/36d1335a667d54c26ab7cca23bc60998cb8e0fb2 and I get the crash there too.

**Comment by iclanzan** [comment]
I tried `NVIM v0.4.3` on Pop OS and there is no crash there. Tried it on a different machine with NixOS and that one crashes too. So it must be related to NixOS.

**Comment by Noah11012** [comment]
When running Neovim through Valgrind I get the following output:

```❯ valgrind nvim -u NORC
==22067== Memcheck, a memory error detector
==22067== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22067== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==22067== Command: nvim -u NORC
==22067==
--22067-- WARNING: unhandled amd64-linux syscall: 332
--22067-- You may be able to write your own handler.
--22067-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--22067-- Nevertheless we consider this a bug.  Please report
--22067-- it at http://valgrind.org/support/bug_reports.html.
==22067==
==22067== HEAP SUMMARY:
==22067==     in use at exit: 3,963,370 bytes in 17,853 blocks
==22067==   total heap usage: 53,887 allocs, 36,034 frees, 71,227,731 bytes allocated
==22067==
==22067== LEAK SUMMARY:
==22067==    definitely lost: 0 bytes in 0 blocks
==22067==    indirectly lost: 0 bytes in 0 blocks
==22067==      possibly lost: 43,171 bytes in 938 blocks
==22067==    still reachable: 3,920,199 bytes in 16,915 blocks
==22067==         suppressed: 0 bytes in 0 blocks
==22067== Rerun with --leak-check=full to see details of leaked memory
==22067==
==22067== For counts of detected and suppressed errors, rerun with: -v
==22067== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)```

**Comment by iclanzan** [comment]
The problem was caused by an older version of `libvterm` that NixOS was compiling `neovim` with. Updating to the same version as this repo is using (as found [here](https://github.com/neovim/neovim/blob/5f9209389b95c03f22c660e9f36d0158b0f664e3/third-party/CMakeLists.txt#L165)) fixes the crashing: https://github.com/NixOS/nixpkgs/pull/74365.
