### ISSUE TITLE
"i_CTRL-v ALT-1 ALT-1 ALT-1" prints <M-o> instead of <M-1>

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#11468]
- `nvim --version`: NVIM v0.5.0-180-g222637c34
- Operating system/version: Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Terminal name/version: Doesn't matter, also happens in GUIs
- `$TERM`: Doesn't matter, also happens in GUIs

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:call nvim_input("a<C-v><M-1><M-1><M-1>")
```

### Actual behaviour
`<M-o>` is inserted in the buffer.

### Expected behaviour
`<M-1>` is inserted in the buffer.

**Comment by justinmk** [comment]
That's a bit weird, but it works if you 

1. remove the `<c-v>`
2.  map ALT-1 to something: `:inoremap <a-1> foo`

    :call nvim_input("a<M-1><M-1><M-1>")
    foofoofoo  " inserted text

This might be a side-effect of 224ebc0078f29ac3189 (`:help i_META`), which causes `<c-v>` to get confused.

Is there an actual problem, other than the confusing result of `<c-v>` ? After all, mapping ALT-1 should work, and it doesn't do anything useful otherwise...

**Comment by glacambre** [comment]
No "real" problem as far as I know - I just found this issue while testing something in firenvim and thought I'd report it :).

**Comment by zeertzjq** [comment]
I tested this an `I_CTRL-V ALT-1` doesn't print anything. Also, this diff fixes the problem, but I'm not sure whether it is the correct fix:
```diff
diff --git a/src/nvim/edit.c b/src/nvim/edit.c
index a9c606ec1..e7fe31ed4 100644
--- a/src/nvim/edit.c
+++ b/src/nvim/edit.c
@@ -5644,17 +5644,17 @@ int get_literal(void)
     } else {
       if (hex
           || unicode != 0) {
-        if (!ascii_isxdigit(nc)) {
+        if (mod_mask != 0 || !ascii_isxdigit(nc)) {
           break;
         }
         cc = cc * 16 + hex2nr(nc);
       } else if (octal) {
-        if (nc < '0' || nc > '7') {
+        if (mod_mask != 0 || nc < '0' || nc > '7') {
           break;
         }
         cc = cc * 8 + nc - '0';
       } else {
-        if (!ascii_isdigit(nc)) {
+        if (mod_mask != 0 || !ascii_isdigit(nc)) {
           break;
         }
         cc = cc * 10 + nc - '0';
```

**Comment by zeertzjq** [comment]
I tested this an `I_CTRL-V ALT-1` doesn't print anything. Also, this diff fixes the problem:
```diff
diff --git a/src/nvim/edit.c b/src/nvim/edit.c
index a9c606ec1..bd303318a 100644
--- a/src/nvim/edit.c
+++ b/src/nvim/edit.c
@@ -5631,6 +5631,9 @@ int get_literal(void)
   i = 0;
   for (;;) {
     nc = plain_vgetc();
+    if (mod_mask != 0) {
+      break;
+    }
     if (!(State & CMDLINE)
         && MB_BYTE2LEN_CHECK(nc) == 1) {
       add_to_showcmd(nc);
```
