### ISSUE TITLE
Neovim Displays Empty Block Even With Powerline Fonts

### ISSUE THREAD

**Issue by MetaNite64** [neovim/neovim#11465]
I have a powerline font on, and the "agnoster" theme in ohmyzsh displays correctly. However, in neovim, the triple-line and LN characters do not display correctly. My font is monofur for Powerline, and everything else displays fine. I've attached some pictures. This is in the Ubuntu WSL module.

![image](https://user-images.githubusercontent.com/32368758/69654649-bfc92700-103a-11ea-8065-83f36e8dc8a4.png)

![image](https://user-images.githubusercontent.com/32368758/69654676-c8b9f880-103a-11ea-81b1-1ab96e503982.png)

**Comment by jdhao** [comment]
The font is set by the terminal. I think it has something to do with your terminal set up and nothing to do with neovim.

Are you using mintty? You need to set up the font properly for mintty terminal. I do not have such font issue with mintty and neovim.

![image](https://user-images.githubusercontent.com/16662357/69690691-975b2e80-1107-11ea-901e-7dff1da23805.png)
