### ISSUE TITLE
wrong $VIM env var breaks Nvim

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#11462]
- `nvim --version`:  0.5.0
- `vim -u DEFAULTS` (version: ) behaves differently? no applicable
- Operating system/version: Ubuntu 18.04

### Steps to reproduce using `nvim -u NORC`

+ The root user set environment variable `VIM` to `/etc/vim` (it does not matter where the directory is) by adding `export VIM=/etc/vim` to `/etc/bash.bashrc`

+ The user installs neovim under his own HOME directory, for example to `$HOME/tools/nvim`

+ Open neovim with 

```
nvim -u NORC
```

### Actual behaviour

nvim complains the following error:

> E484: Can't open file /etc/vim/syntax/syntax.vim

### Expected behaviour

No errors occur and nvim can find its runtime files properly under directory `$HOME/tools/nvim/share/nvim/runtime`.

According to the documentation of Neovim, it will respect the environment variable `VIM`  if it is set. But the problem is that users do not usually set this variable. If this variable is set by the system administrator in the system config such as `bash.bashrc`, this env variable will be inherited by the user, which causes the error message shown above.

Maybe it is saner to first try to derive the value of $VIM from the location of nvim executable.

**Comment by justinmk** [comment]
> Maybe it is saner to first try to derive the value of $VIM from the location of nvim executable

Then why support $VIM at all? We could remove it I guess, it's really useful unlike VIMRUNTIME ...

**Comment by jdhao** [comment]
According to doc of nvim, `:h $VIM`:

```
Nvim will try to get the value for $VIM in this order:

1. Environment variable $VIM, if it is set.
2. Path derived from the 'helpfile' option, unless it contains some
   environment variable too (default is "$VIMRUNTIME/doc/help.txt").  File
   name ("help.txt", etc.) is removed.  Trailing directory names are removed,
   in this order: "doc", "runtime".
3. Path derived from the location of the `nvim` executable.
4. Compile-time defined installation directory (see output of ":version").
```

When $VIM does not exist, the first one in the above list does not apply; the option `helpfile` contains $VIMRUNTIME, the second one in the above list also does not apply.

So it seems that $VIM is derived from the location of the nvim executable.

The variable $VIMRUNTIME is derived from $VIM if it is not set. If $VIM support is dropped, you need to derive $VIMRUNTIME directly from the path the nvim executable, but that is not difficult, IMO.

**Comment by KillTheMule** [comment]
Why would the administrator set that variable, if it doesn't point to a valid runtime? Isn't that simply a misconfiguration?

Otoh, how about just unsetting that variable in your bashrc if it's bugging you?

**Comment by jdhao** [comment]
@killthekitten Because the administrator is using **Vim** not Neovim, and he put all system-wide Vim config under `/etc/vim` and set the `VIM` variable in the system startup file. But I would rather to use Neovim personally, thus the error message appears.

Unsetting the variable is surely an option. Actually that is what I am doing right now. I just think that Neovim should be more intelligent in determining the location of its runtime files.

**Comment by chrisbra** [comment]
He surely shouldn't export the variable it to the system then.

**Comment by jdhao** [comment]
@chrisbra  He is setting up Vim system-wide and expects all users will have a ready-to-use Vim environment, which I think is understandable.  Unfortunately, Neovim also respects the VIM environment variable...

**Comment by chrisbra** [comment]
why is this necessary? Vim will figure this out fine from its installation if it isn't set.

**Comment by bfredl** [comment]
@jdhao but why doesn't he just use a standard `/usr/` or `/usr/local` install dir, so that vim finds its runtime itself? Why install software in `/etc` ?

I guess as part of the detection mechanism (as in the quoted `:h $VIM` ), we could try to detect a _nvim_ runtime as opposed to a _vim_ runtime. Only if no nvim runtime is found, or if you directly set `VIMRUNTIME` to it, would we ever try to load a vim runtime (I guess you might want to be able to do this, for some weird debugging purpose or something).

**Comment by jdhao** [comment]
For clarification, Vim is compiled from source by root (`--prefix=/usr`). It is just Vim configuration is put in `/etc/vim`.

**Comment by bfredl** [comment]
> Vim runtime file is in /usr/share/vim/vim81

Then the VIM variable should really not be set to `/etc/vim`. This sounds like it could break users vim configs just as well, and not just neovim.

**Comment by jdhao** [comment]
@bfredl , according to `system-vimrc` of Vim doc, it will read system config from `$VIM/vimrc` first, then the user config is read from `$HOME/.vimrc` or  `$HOME/.vim/vimrc`.  I have tested that it won't break the user's personal config. It is just that the user's config overrides the system config.

**Comment by jdhao** [comment]
Anyway, the point is that Neovim should find its runtime files correctly regardless of the VIM environment variable because it is very likely that the VIM variable is set by the root user.

**Comment by bfredl** [comment]
> @bfredl , according to system-vimrc of Vim doc, it will read system config from $VIM/vimrc first, then the user config is read from $HOME/.vimrc or $HOME/.vim/vimrc. I have tested that it won't break the user's personal config. It is just that the user's config overrides the system config.

But nvim should have any problem with finding `init.vim` either. `/etc/vim/syntax/syntax.vim` is an (attempt to find a) runtime file, not a personal config file. I don't know how vim manages to find `VIMRUNTIME=/usr/share/vim/vim81` even if `VIM=` is incorrectly set. Perhaps vim has some condition for "`4. Value of $VIM environment variable.  This is for backwards compatibility
   with older Vim versions.`" that we are missing. Though the admin can have done any kind of hack to make it work, that we do not know about here.

**Comment by chrisbra** [comment]
That sounds more like mixing distribution wide runtime files with specific runtime files that come from the self-compiled installation. I think overriding $VIM to point somewhere else is asking for trouble sooner or later and should not be done (especially for a system wide environment variable that affects every user).

**Comment by jdhao** [comment]
@bfredl  From the doc of Vim `:h $VIMRUNTIME`

```
For Unix, when there is a compiled-in default for $VIMRUNTIME (check the
output of ":version"), steps 2, 3 and 4 are skipped, and the compiled-in
default is used after step 5.  This means that the compiled-in default
overrules the value of $VIM.  This is useful if $VIM is "/etc" and the runtime
files are in "/usr/share/vim/vim54".
```

It is seems that `VIMRUNTIME` is set via the compiled-in default. The output of `:version` also says that:

> f-b for $VIMRUNTIME: "/usr/share/vim/vim81"

**Comment by jdhao** [comment]
@chrisbra we are using a docker container and there is no default Vim. Everything necessary is installed by the root user. So no need to worry about mixing runtime files.

**Comment by bfredl** [comment]
@jdhao So, it will break a users custom vim 8 that isn't built in this particular way, just as it broke your nvim.  There isn't really any difference between vim and nvim here, then.

**Comment by chrisbra** [comment]
if this is just a docker container, I don't understand the whole problem. Just install nvim in the image and be done with it. Why do you need to export $VIM in that container/image at all?

**Comment by jdhao** [comment]
@chrisbra  The docker container is managed by the root, and I am only one of the users of this container. I have no right to install packages under system directories, and I am just connecting to the container as a normal user. Think of the container just a real remote server where I am just one of the many users.

**Comment by chrisbra** [comment]
That does not make much sense. containers are intended to be very much customized to a specific use case (application virtualization). If the container comes with Vim, just use it and do not use neovim if it isn't installed. Installing vim and neovim in a container that is most likely intended to perform a specific business application sounds doubtful. In addition, I very much question the use of exporting $VIM systemwide. Vim and Neovim are perfectly able to figure out their required environment.  If you self-compile vim in that container, then just use the provided runtime from `/usr/share/vim` and do not point it to `/etc`. This is really just a configuration issue here.

**Comment by jdhao** [comment]
I know what container is normally used for. The underlying reason why we use a docker container just like a remote server is complicated, which I would rather not elaborate on.  As I have said, Vim is installed and set up by the root user (maybe setting `VIM` variable makes it easy to manage system-wide settings more easily without polluting `/usr/share/vim` folder), not by me,  and I have no right to change the system settings inside the container.

**Comment by justinmk** [comment]
> I can not control what the root user do, and I think it is fine that root set `VIM` to `/etc/vim`.

If admin sets env vars to broken values then users have to override them. E.g. if admin sets `$SHELL=smurf` then user will need to override it. The fact that `smurf` works for the admin doesn't change this.

> I think overriding $VIM to point somewhere else is asking for trouble sooner or later and should not be done (especially for a system wide environment variable that affects every user).

Yes.

So to me, the only question here is whether Nvim supports `$VIM` env var at all. It makes no sense to ignore it and find the correct location automatically if we also still claim to respect it...

**Comment by jamessan** [comment]
> For clarification, Vim is compiled from source by root (`--prefix=/usr`) so that Vim executable is in `/usr/bin` and Vim runtime file is in `/usr/share/vim/vim81`. It is just that Vim configuration is put in `/etc/vim`.

Instead of setting `$VIM`, which is overkill for this task, the distribution should include `/etc/vim` as part of the default `'runtimepath'`.  Debian does [just this](https://salsa.debian.org/vim-team/vim/blob/debian/sid/debian/rules#L28) (along with the additional `/var/lib/vim/addons`, which is specific to a Debian tool).

Previous to being able to use `--with-global-runtime` with multiple paths (added in v8.1.0612), Debian had a file in `$VIMRUNTIME` which was sourced by the system-wide vimrc to adjust `'runtimepath'`.

_Either_ of these choices is _much_ better than hard-coding `$VIM` in the system shell files.

**Comment by thz** [comment]
`nvim` from snap on Debian 11 (bullseye) suffers from the same issue.

This comes from https://github.com/neovim/neovim-snap/blob/e806049298234401f48df3f11db337a613807d99/snap/snapcraft.yaml#L29

Where HOME is overwritten to `/home/$USER`.

I wonder if this is a Snapcraft flaw or can be done better in neovim/neovim-snap.
