### ISSUE TITLE
crash on exit with shada='100,:0 

### ISSUE THREAD

**Issue by mwgkgk** [neovim/neovim#11497]
Likely a multiple-year old issue, as I've been experiencing this crash on exit for a while.
```
fish: “nvim” terminated by signal SIGSEGV (Address boundary error)
```

Caused by the following line:
```
set viminfo='1000,:0,<0,@0,f1,/0
```

Any of the `:0,<0,@0` options in combination with any number of lines (`'100`) are causing the crash. I'm not sure there's an expected behavior with Neovim's shada.

- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
```
- `vim -u DEFAULTS` (version: ) behaves differently? 
Yes

- Operating system/version: 
```
Linux c22 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux
```
- Terminal name/version:
rxvt-unicode v9.22

- `$TERM`:
screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set viminfo='100,:0
:q
```

**Comment by KillTheMule** [comment]
I can't reproduce this on current head, the second line already produces an error about an illegal character.

**Comment by mwgkgk** [comment]
My bad: typo. The line should start with a quote: `:set viminfo='100,:0`. I've accidentally opened the issue too early with control-enter! I'm sorry.

**Comment by KillTheMule** [comment]
That _did_ reproduce. Output here:

> nvim: ../src/nvim/shada.c:602: hmll_insert: Assertion `hmll->first != NULL' failed.
>    Aborted

**Comment by mwgkgk** [comment]
Clearing `~/.local/share/nvim/skada/` fixes the issue, however as soon as there appear more files besides `main.shada` the problem reappears.

Not sure how to reproducibly force the secondary temporary files to appear, seems to have happened on accident or after a period of activity.
