### ISSUE TITLE
RFC: Change the way neovim writes files to better work with bind mounts and docker

### ISSUE THREAD

**Issue by evaryont** [neovim/neovim#11490]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: 8.1) behaves differently? No
- Operating system/version: Arch, running kernel 5.3.13
- Terminal name/version: Konsole 19.08.3
- `$TERM`: xterm-256color

### Actual behaviour

When I edit a file, and it's been bind-mounted with Docker, I expect to see the changes inside the container. However, the file inside the container does not reflect that change.

I believe it's because of https://github.com/moby/moby/issues/15793, quoted below:

> If you are using some editor like vim, when you save the file it does not save the file directly, rather it creates a new file and copies it into place.
This breaks the bind-mount, which is based on inode. Since saving the file effectively changes the inode, changes will not propagate into the container.
When the container is restarted the new inode.
If you edit the file in place you should see changes propagate.

### Expected behaviour

Neovim doesn't create a brand-new file when saving, but instead reuses the existing file.

I would like this behaviour to change, either with some combination of settings or always. I think it would be less surprising if the default were to change as well.

**Comment by KillTheMule** [comment]
However

> rather it creates a new file and copies it into place.

is standard practice to protect against crashes mid-write.

**Comment by mhinz** [comment]
The default for Linux should be `set nobackup writebackup`. So, while saving the buffer, a backup is made and removed afterwards.

There are two approaches to making a backup and `:h 'backupcopy'` explains it very well and in detail. Both have pros and cons.

In your case, you probably want to `set nowritebackup`. Maybe even conditionally, e.g. only for files below a certain directory:

```vim
autocmd BufWritePre  /path/to/dir/* set nowritebackup
autocmd BufWritePost /path/to/dir/* set writebackup
```

**Comment by justinmk** [comment]
> > rather it creates a new file and copies it into place.
> 
> is standard practice to protect against crashes mid-write.

Yes. Not doing so is bad practice.

> Expected behaviour: Neovim doesn't create a brand-new file when saving, but instead reuses the existing file.

The process is more like: write to a temp location, then _rename_ after the write succeeds. That's the typical way to atomically save a file. Blame it on the OS vendors.

Meanwhile you can disable this behavior as @mhinz noted:

    :set nobackup nowritebackup

**Comment by evaryont** [comment]
Thanks @justinmk and @mhinz for the pointers in the documentation!

**Comment by albertnetymk** [comment]
I came across this recently -- the brithtime of my file is changed after being written in neovim. I changed `backupcopy` to `yes` to still get write protection, just fyi.
