### ISSUE TITLE
Make $NVIM_LOG_FILE available earlier/always

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#11499]
I think it would be useful if `$NVIM_LOG_FILE` would be available when expanding vars in Neovim (not necessarily for subprocesses).
This would allow for `echo $NVIM_LOG_FILE` to see its location easily, and could be used to write there manually (although the plan is to provide an API for it (https://github.com/neovim/neovim/issues/8043#issuecomment-367539249 - is there an issue for it already?)).

**Comment by justinmk** [comment]
It already is available, provided the log file ever gets written. I agree this is confusing, but... perhaps the log file should always be written initially.

**Comment by blueyed** [comment]
> It already is available, provided the log file ever gets written.

Ah.

> I agree this is confusing, but... perhaps the log file should always be written initially.

Yes, might be good - e.g. logging the log level for example.

> Why does the env var need to be "special"?

I've thought it would be better to not leak into subprocesses - but if that's the case already it's fine for me.

**Comment by justinmk** [comment]
> I've thought it would be better to not leak into subprocesses - but if that's the case already it's fine for me.

Oh, right. We need to do that for various env vars, e.g. NVIM_LISTEN_ADDRESS.

> Yes, might be good - e.g. logging the log level for example.

👍

**Comment by blueyed** [comment]
> > I've thought it would be better to not leak into subprocesses - but if that's the case already it's fine for me.
> 
> Oh, right. We need to do that for various env vars, e.g. NVIM_LISTEN_ADDRESS.

What do you mean?
I can see that `NVIM_LISTEN_ADDRESS` must be exported, but not necessarily (the default) `NVIM_LOG_FILE`.

> > Yes, might be good - e.g. logging the log level for example.
> 
>  Well, it should just be blank. Multiple Nvims write to the same log file, so adding "initial info" from the first Nvim that happens to write the file is misleading, and would otherwise be too noisy if every Nvim appended their info.

It's also not trivial in general - would have to use `ELOG`, but it is not really an error.  And it seems rather noisy in general when you do not want logging in general.
I'd say it's better to make sure the env var is defined always.

**Comment by justinmk** [comment]
> What do you mean?  I can see that `NVIM_LISTEN_ADDRESS` must be exported, but not necessarily (the default) `NVIM_LOG_FILE`.

Explained in https://github.com/neovim/neovim/pull/11009

**Comment by blueyed** [comment]
> > What do you mean?  I can see that `NVIM_LISTEN_ADDRESS` must be exported, but not necessarily (the default) `NVIM_LOG_FILE`.
> 
> Explained in #11009

That does not say anything about `NVIM_LOG_FILE`, does it?
