### ISSUE TITLE
Build does not fully respect -DMIN_LOG_LEVEL

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#11496]
This happens on current [HEAD](https://github.com/neovim/neovim/commit/735d89d09e5cf50886b927ce4ec93b9098da259d): Run

```sh
git clone https://github.com/neovim/neovim/ --depth 1 && cd neovim && make CMAKE_EXTRA_FLAGS="-DMIN_LOG_LEVEL=0" CMAKE_BUILD_TYPE=RelWithDebInfo && build/bin/nvim --version |grep --color=auto MIN_LOG_LEVEL
```

and note the binary still reports a MIN_LOG_LEVEL of 3. During the built, a lot of lines of the form

> [245/315] Building C object src/nvim/CMakeFiles/nvim.dir/os/dl.c.o
> <command-line>: warning: "MIN_LOG_LEVEL" redefined
> <command-line>: note: this is the location of the previous definition

are put into the console.

This happens for RelWithDebInfo and Release, bug not Debug builds.

A workaround is to edit line 139 of CMakeLists.txt and replace 3 by 0.

**Comment by blueyed** [comment]
https://github.com/neovim/neovim/blob/1a6efa4719c906fe67f2c21ec1a2b33ae92ca17b/CMakeLists.txt#L137-L146 should probably honor/get skipped with a given MIN_LOG_LEVEL?

**Comment by blueyed** [comment]
or rather somewhere else..
IIRC the last time I've looked at it we want to define `*_RELEASE` always like that.

**Comment by blueyed** [comment]
FWIW I have this in my local.mk: `CMAKE_EXTRA_FLAGS += -DCMAKE_C_FLAGS_RELWITHDEBINFO="-DMIN_LOG_LEVEL=1 -O2 -g -DNDEBUG"`

**Comment by blueyed** [comment]
> IIRC the last time I've looked at it we want to define `CMAKE_C_FLAGS_*` always like that.

Not sure about this though really.  I think I got the impression that it should be set always for when `CMAKE_BUILD_TYPE` is switched, but likely it makes sense to only add it if `MIN_LOG_LEVEL` is not defined.

```diff
diff --git i/CMakeLists.txt w/CMakeLists.txt
index d25cd8934..361ee3590 100644
--- i/CMakeLists.txt
+++ w/CMakeLists.txt
@@ -134,20 +134,20 @@ set(NVIM_VERSION_BUILD_TYPE "${CMAKE_BUILD_TYPE}")

 set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

-# Minimize logging for release-type builds.
-if(NOT CMAKE_C_FLAGS_RELEASE MATCHES DMIN_LOG_LEVEL)
-  set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -DMIN_LOG_LEVEL=3")
-endif()
-if(NOT CMAKE_C_FLAGS_MINSIZEREL MATCHES DMIN_LOG_LEVEL)
-  set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL} -DMIN_LOG_LEVEL=3")
-endif()
-if(NOT CMAKE_C_FLAGS_RELWITHDEBINFO MATCHES DMIN_LOG_LEVEL)
-  set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} -DMIN_LOG_LEVEL=3")
-endif()
-
 # Log level (MIN_LOG_LEVEL in log.h)
 if("${MIN_LOG_LEVEL}" MATCHES "^$")
   message(STATUS "MIN_LOG_LEVEL not specified, default is 1 (INFO)")
+
+  # Minimize logging for release-type builds.
+  if(NOT CMAKE_C_FLAGS_RELEASE MATCHES DMIN_LOG_LEVEL)
+    set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -DMIN_LOG_LEVEL=3")
+  endif()
+  if(NOT CMAKE_C_FLAGS_MINSIZEREL MATCHES DMIN_LOG_LEVEL)
+    set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL} -DMIN_LOG_LEVEL=3")
+  endif()
+  if(NOT CMAKE_C_FLAGS_RELWITHDEBINFO MATCHES DMIN_LOG_LEVEL)
+    set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} -DMIN_LOG_LEVEL=3")
+  endif()
 else()
   if(NOT MIN_LOG_LEVEL MATCHES "^[0-3]$")
     message(FATAL_ERROR "invalid MIN_LOG_LEVEL: " ${MIN_LOG_LEVEL})
```
