### ISSUE TITLE
nvim fails to build in Raspbian "Could NOT find LibLUV"

### ISSUE THREAD

**Issue by vegerot** [neovim/neovim#11506]
- `nvim --version`: n/a
- `vim -u DEFAULTS` (version: ) behaves differently? n/a
- Operating system/version: Raspbian 10 (buster)
- Terminal name/version: n/a
- `$TERM`: xterm

### Steps to reproduce

```
git clone https://github.com/neovim/neovim
cd neovim
mkdir build
cd build
cmake -j ..

```
or

```
git clone https://github.com/neovim/neovim
cd neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo USE_BUNDLED=OFF -j
```
### Actual behaviour
```
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibLUV (missing: LIBLUV_LIBRARY LIBLUV_INCLUDE_DIR)
  (Required is at least version "1.30.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibLUV.cmake:29 (find_package_handle_standard_args)
  CMakeLists.txt:369 (find_package)
```

### Expected behaviour

success

**Comment by justinmk** [comment]
If you set `USE_BUNDLED=OFF` then it's up to you to install the libs using your package manager.

Example from https://github.com/neovim/neovim#install-from-source : 

    sudo apt install gperf luajit luarocks libuv1-dev libluajit-5.1-dev libunibilium-dev libmsgpack-dev libtermkey-dev libvterm-dev libutf8proc-dev


YMMV, you need to figure out the steps for your system.

**Comment by vegerot** [comment]
@justinmk I did install all of those previously too.  Should have mentioned that

**Comment by justinmk** [comment]
>   (Required is at least version "1.30.0")

The build mentions the required libuv version. Does your system have that? Probably not, raspbian tends to be out of date.

So use the bundled deps.

**Comment by vegerot** [comment]
Alright.  The reason I didn't want to use the bundled dips is because I am working with a very small environment, and when I tried using the bundled deps (which I tried before not bundling), my system ran out of space

**Comment by blueyed** [comment]
@vegerot 
You can use only some bundled, e.g. `DEPS_CMAKE_FLAGS="-DUSE_BUNDLED=OFF -DUSE_BUNDLED_LIBLUV=ON`.
(I recommend using a `local.mk` file to specify this, see `contrib/local.mk.example`.

**Comment by vegerot** [comment]
@blueyed my local.mk is as follows
```
DEPS_CMAKE_FLAGS="-DUSE_BUNDLED=OFF"
DEPS_CMAKE_FLAGS+="-DUSE_BUNDLED_LIBLUV=ON"
```
and I've tried running `make -j` and `mkdir build&&cd build&&cmake -j ..`
Both of which give the same error about not being able to find libluv :(

**Comment by blueyed** [comment]
@vegerot 
Try just `rm -rf build .deps; make`.  If it still fails then paste the full output, or at least everything around "libluv" then.

**Comment by blueyed** [comment]
@vegerot 
Note that `local.mk` is used by our Makefile, but not when using cmake directly.
