### ISSUE TITLE
LSP client shows error messages for cancellation request acknowledgements

### ISSUE THREAD

**Issue by AlexMax** [neovim/neovim#11515]
Version: NVIM v0.5.0-226-gb1e4ec1c2

Based on a conversation in the gitter channel with @norcalli I believe that there is an oversight with the LSP client in its current state.

I was attempting to get `javascript-typescript-langserver` working with LSP, and while I managed to get it working, I would occasionally get strange error messages mentioning `NO_RESULT_CALLBACK_FOUND`.  After some digging, I found out that the language server appears to respond to cancellation requests with a cancellation acknowledgement error code as shown [here](https://github.com/sourcegraph/javascript-typescript-langserver/blob/d107424f1f964c4cb3b6061570890639fd69b9e6/src/connection.ts#L211).  This behavior is apparently [endorsed by the LSP standard](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#cancelRequest) with a specific error code set aside for it, though the standard stops short of mandating its use, instead also allowing servers to return partial results.  This error code is even [already defined](https://github.com/neovim/neovim/blob/d5aaad14ecdd2047089e1a018e97af1f790b3e42/runtime/lua/vim/lsp/protocol.lua#L164) in the protocol file that neovim uses for LSP, though it's not actually used anywhere.

It seems to me like if neovim sends a cancellation request, it probably shouldn't show a verbose error message that interrupts the user when the acknowledgement "error" comes back - that seems like a bug to me.  After a conversation with @norcalli it was suggested that perhaps a terse one-line message could be displayed instead that doesn't interrupt the user that mentions that the request timed out and had to be cancelle.  Or perhaps nothing at all.  There were also suggestions of being able to override the timeout of the request, both globally and per-client.

**Comment by justinmk** [comment]
@AlexMax how about a pull request?

**Comment by norcalli** [comment]
Indirectly this is fixed because there's actually nothing using the cancellation logic anymore now that omnifunc completion is async, but it should still be fixed. Handled in #11606
