### ISSUE TITLE
Automatic syntax italicizing

### ISSUE THREAD

**Issue by huyiqun** [neovim/neovim#11538]
- `nvim --version`:0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?No
- Operating system/version: MacOS
- Terminal name/version: iTerm2
- `$TERM`:xterm-256color

I wonder if it is possible to italicize keywords in addition to syntax highlighting (or if there already exists an option to alter this, please advise!). For example, when I use VScode, keywords such as `import`, `try`, `as` are automatically italic:
![image](https://user-images.githubusercontent.com/10877536/70485581-5ecf3380-1abd-11ea-99d8-e39fa6d3960f.png)
In neovim:
![image](https://user-images.githubusercontent.com/10877536/70485628-7a3a3e80-1abd-11ea-8441-269d2169eab6.png)
(I installed both the regular and italic of the same font.)

### Actual behaviour
All fonts are regular version.
### Expected behaviour
Syntax keywords are both highlighted and italic.

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
