### ISSUE TITLE
Neovim does not use terminal colors by default.

### ISSUE THREAD

**Issue by m-kru** [neovim/neovim#11534]
I have problems with setting neovim to use terminal colors. I have been experimenting with `t_Co` and `termguicolors` but without success. Then I have decided to completely clear my init.vim. It turns out that by default neovim does not use terminal colors. This is something that vim handles correctly.
You can see neovim on the left and vim on the right, both without any configuration.
![nvim_vim](https://user-images.githubusercontent.com/26227737/70389702-15022280-19c3-11ea-9a4a-250759aa1e3f.png)

Is it a bug? If no, how can I force neovim to use terminal colors?

**Comment by bfredl** [comment]
"terminal colors" could mean anything, any color displayed in a terminal is a "terminal color".  Sounds what you mean is "it doesn't look like it used to do". 

Looks like the difference is 'background' setting. Nvim is intentionally setting the "dark" default in a dark terminal which seems like the reasonable default, but you can `set background=light` if you want.

**Comment by m-kru** [comment]
@bfredl thanks! This worked. One question. How does nvim detect it is dark terminal?

**Comment by justinmk** [comment]
> How does nvim detect it is dark terminal?

https://github.com/neovim/neovim/pull/9509
