### ISSUE TITLE
Adding a configuration about searching timeout

### ISSUE THREAD

**Issue by allenjlw** [neovim/neovim#11535]
- `nvim --version`:
NVIM v0.4.3
I've also tried the v0.5.0 version. It's the same as v0.4.3.

- `vim -u DEFAULTS` (version: ) behaves differently?
No.

- Operating system/version:
Ubuntu 18.04

- Terminal name/version:
gnome-terminal (3.28.2) + tmux (2.6)
- `$TERM`:
screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
When opening a big file (47M in my case) and doing the search, the matched number is displayed as [?/??]. I know that it's because of a search timeout from this document (https://neovim.io/doc/user/pattern.html) but I haven't found any configuration that can change the timeout value.

### Expected behaviour
So I'm wondering if it's possible to add a configuration about the timeout so that a bigger timeout value can be set and the statistic can be displayed correctly even for a big file.

**Comment by justinmk** [comment]
Might be controlled by 'redrawtime' option, or if not, you could request that feature at https://github.com/vim/vim . It isn't worth our time to deviate from Vim here.

**Comment by allenjlw** [comment]
'redrawtime' does not work for me but thanks!
I'll send the request on vim.
