### ISSUE TITLE
Missing 'pum_getpos()' breaks YouCompleteMe's signature help feature

### ISSUE THREAD

**Issue by sethfowler** [neovim/neovim#11537]
Neovim doesn't yet have support for the fairly recent `pum_getpos()` function added to Vim [in this PR](https://github.com/vim/vim/pull/4827).

YouCompleteMe relies on this function to implement its [signature help](https://github.com/ycm-core/YouCompleteMe#signature-help) feature - autocompletion for function parameters, basically. It's a really useful feature and it's a shame to not be able to use it in Neovim.

Is this something that could get pulled into Neovim fairly soon?

### Actual behaviour

`pum_getpos()` is not available in Neovim, and YCM's signature help feature does not work.

### Expected behaviour

`pum_getpos()` is available in Neovim, and YCM's signature help feature works.

**Comment by justinmk** [comment]
> Neovim doesn't yet have support for the fairly recent `pum_getpos()` function added to Vim [in this PR](https://github.com/vim/vim/pull/4827).

Nvim has a different API for "popups", see `:help api-floatwin`.  If we do decide to add some sort of imitation of VIm's API, it'll be when someone sends a PR to do so, until then it's `wontfix`.

> YouCompleteMe relies on this function to implement its [signature help](https://github.com/ycm-core/YouCompleteMe#signature-help) feature

YCM devs have said many times, they don't support Nvim.

> Is this something that could get pulled into Neovim fairly soon?

Nope.

**Comment by sethfowler** [comment]
@justinmk Thank you; I wasn’t aware Neovim had its own API for this. If I can find some time during the holiday season I’ll look into what it would take to add support for this feature to Neovim. Cheers!

**Comment by bfredl** [comment]
>  Neovim doesn't yet have support for the fairly recent pum_getpos() function added to Vim in this PR.

> Nvim has a different API for "popups", see :help api-floatwin

But `pum_setpos()` is not specific to "popup" windows, it rather concerns the popup _menu_ and is analogous to the CompleteChange and its `v:event` which already is a shared API between nvim and vim 8. So it would still be meaningful to port https://github.com/vim/vim/pull/4827 in isolation.

**Comment by mskar** [comment]
If anyone else is reading this looking for an alternative to `pum_getpos()["size"]`, I am using `len(complete_info()["items"])` and it seems to work fine.
