### ISSUE TITLE
Lua stdlib: fs/path functions

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#11536]
Nvim Lua stdlib (or the editor stdlib--doesn't matter which, really) should have various path utilities, e.g. 

- mimic python's `commonpath()` function.  https://docs.python.org/3/library/os.path.html#os.path.commonpath
  - useful for comparing ancestor/descendant relationships. https://github.com/neovim/nvim-lsp/pull/61#discussion_r355251268
- path `join()` function (how does Vim not have this already?!)

**Comment by norcalli** [comment]
You can see all the path functions I've put in nvim_lsp.util.path already. basename/dirname/join/split/SEP/exists/is_dir/is_file

vim.loop.fs_stat could be aliased as `stat` as well, and it gives you the other guys.

**Comment by tammela** [comment]
I can help with that.

Is there any reason to not consider other lua bindings?

**Comment by tammela** [comment]
Oh, now I get it. The underlying functionality is already present. Sorry about that. 
I will take a look as soon as I can.

**Comment by justinmk** [comment]
We have `vim.fs` now, and `vim.uri` is planned. https://github.com/neovim/neovim/pull/24527
