### ISSUE TITLE
There is unreadable code after I run nvim in centos6.6

### ISSUE THREAD

**Issue by leafwaltz** [neovim/neovim#11540]
![asd](https://user-images.githubusercontent.com/22277588/70514261-44a15e00-1b6e-11ea-91e3-f070321464f3.png)

**Comment by justinmk** [comment]
This is addressed in the FAQ. Read the FAQ before posting, as mentioned in the issue template.

https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes
