### ISSUE TITLE
Terminal Buffer disappearing after switching buffers

### ISSUE THREAD

**Issue by Dbz32k** [neovim/neovim#11542]
Version: NVIM 0.4.3
I Lost my terminal buffer after switching to a previous/next buffer, I was pretty much at 30% of a TestDisk deep scan analyze. Lost everything. :(

Tried going through the Jumplist to no avail. The problem repeated itself after I tried making another terminal buffer and switching to prev/next. Terminal just disappears.

This shouldn't be a default feature.

**Comment by justinmk** [comment]
The "default feature" is Vim's `:set hidden`. To turn it off, 

    :set nohidden

Discussed in https://github.com/neovim/neovim/issues/6289. PR welcome.
