### ISSUE TITLE
Strange Bug when I use set keymap option

### ISSUE THREAD

**Issue by paradoxsurpeme** [neovim/neovim#11549]
When I use :set keymap=greek_utf-8 I have some strange behaviour when I press some letters for example a. At first the letter appears in english and then in greek .This does not happen with all letters 
https://terminalizer.com/view/0149f1ba2595

**Comment by justinmk** [comment]
Need all the details requested by the issue template. Especially whether it happens in Vim.

**Comment by paradoxsurpeme** [comment]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? no 
- Operating system/version: arch , android
- Terminal name/version: kitty , urxvt , termux

**Comment by justinmk** [comment]
Sounds like 'timeout' option . This is standard vim behavior.
