### ISSUE TITLE
E212: Can't open file for writing

### ISSUE THREAD

**Issue by shaodahong** [neovim/neovim#11543]
- `nvim --version`:v0.4.3
- `vim -u DEFAULTS` (version:v8.1.1312 ) behaves differently?
- Operating system/version:macos 10.15.2
- Terminal name/version:iterm2 3.3.7
- `$TERM`: no

### Steps to reproduce using `nvim -u NORC`
I use brew to install 'neovim', and prepare to use  `vim-plug`, so i use nvim a init config `sudo nvim ~/.config/nvim/init.vim`

but when i input `:wq` error `E212: Can't open file for writing`, cause by mac **SIP** ? 

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

**Comment by justinmk** [comment]
> cause by mac **SIP** ?

Maybe? If you find out, share the solution here. Meanwhile, this report lacks enough info to give any advice. If Nvim says it can't open the file, it's up to you to find out if you have the right permissions or produce steps that allow us to reproduce the issue.

**Comment by confiq** [comment]
I can reproduce this when I'm creating new files... like `neovim newfile` can't write the file, although I have writing permission

**Comment by 0xCodeMaieutics** [comment]
In my case, let's say I executed this:
`nvim ~/directory/file`

Because `directory` didn't exist, nvim couldn't save the file.

Create the directory first `mkdir directory` and then start editing `nvim ~/directory/file`

**Comment by justinmk** [comment]
> Because `directory` didn't exist, nvim couldn't save the file.

You can use:

    :write ++p

**Comment by 0xCodeMaieutics** [comment]
> :write ++p

I also knew there was a way doing it `vim` natively but chose to showcase it with `mkdir`.

Ofc, doing it your way is more pratical if you are already in `vim`.
