### ISSUE TITLE
Portable neovim configuration on windows

### ISSUE THREAD

**Issue by YohananDiamond** [neovim/neovim#11541]
Most of my time on NeoVim is on my personal computer (which runs Linux), but sometimes I need to use NeoVim on other machines (which runs Windows) and for that I prefer a portable setup.

At least on Vim8, I could use this folder structure to store the config files near the binaries:
```
Vim/
  vim81/    # The vim binaries
  vimfiles/ # The equivalent of ~/.vim
  _vimrc    # The equivalent fo ~/.vim/vimrc
```
Is there any way of replicating said workflow on NeoVim?

**Comment by jdhao** [comment]
@YohananDiamond  The neovim user config is placed on standard locations across systems. To the where that location is, you should use `: echo stdpath('config') inside Neovim. Put all your personal config inside that directory, and that is about it.

See also `:h init.vim` about how Neovim finds its startup file and other runtime files.

**Comment by justinmk** [comment]
> At least on Vim8, I could use this folder structure to store the config files near the binaries:

It works very similar (but somewhat simpler) in Nvim, explained at `:help $VIMRUNTIME` and `:help $VIM`:

> 3. Path derived from the location of the `nvim` executable.

Also, `:version` mentions:

    system vimrc file: "$VIM\sysinit.vim"

so you can place a `sysinit.vim` file in your portable files and tell it to `:source` any other files placed wherever you want, as well as setting 'runtimepath' as needed.

---

Off-topic, but related: since Nvim follows the XDG standard (see `:help xdg`) , on Windows the config path is `~/AppData/Local/nvim/init.vim`. To keep cross-platform config, the [contents of my Windows init.vim](https://github.com/justinmk/config/commit/affc193520c026de35c6e274e18a8ba8f83aa9cf) are:

    source ~\.config\nvim\init.vim

**Comment by YohananDiamond** [comment]
Thanks, it worked. Here's the code I used (in case anyone reading this wants another example):
```
let s:config_path = fnamemodify(expand("$VIM"), ':h:h') . '\config' " Get the path equivalent to $VIM\..\..\config (where I'm putting my config files)
let &rtp .= ',' . s:config_path " Add custom runtime path
exec 'source ' . s:config_path . '\init.vim' " Source the init.vim file
```
The `config` folder I mentioned above is on the same directory as the `bin` and `share` folders.

**Comment by oatall** [comment]
@YohananDiamond 
```
exec 'source ' . s:config_path . '\init.vim' " Source the init.vim file
```
The comment on this line will cause an error.
```
E114:Missing quote:"Source the init.vim file
```
 I solved this problem with line breaks. Is this a software bug?

**Comment by YohananDiamond** [comment]
Well, this is happening for me too on my linux machine, for some reason.

I believe commenting in an exec line worked before, though. At least on the windows version.

**Comment by jamessan** [comment]
> I solved this problem with line breaks. Is this a software bug?

No, it's explicitly documented at `:help :exe-comment`.

**Comment by snth** [comment]
On Windows I am finding that my `$MYVIMRC` is not set with this configuration. So to fix that and address the exe-comment issue from above, I ended up using the following snippet:

```
let $VIMCONFIG = fnamemodify(expand("$VIM"), ':h:h') . '\config'	" Get the path equivalent to $VIM\..\..\config
let &rtp .= ',' . $VIMCONFIG    					" Add custom runtime path
let $MYVIMRC = $VIMCONFIG . '\init.vim'					" Set $MYVIMRC to point to the init.vim file
exec 'source ' . $MYVIMRC						| " Source the init.vim file
```

I created a `$VIMCONFIG` variable so that it would be accessible in the `init.vim` file for loading plugins etc ...

**Comment by oatall** [comment]
> No, it's explicitly documented at `:help :exe-comment`.

Ok, thanks.

**Comment by LeonT-A** [comment]
> Off-topic, but related: since Nvim follows the XDG standard (see `:help xdg`) , on Windows the config path is `~/AppData/Local/nvim/init.vim`. To keep cross-platform config, the [contents of my Windows init.vim](https://github.com/justinmk/config/commit/affc193520c026de35c6e274e18a8ba8f83aa9cf) are:
> 
> ```
> source ~\.config\nvim\init.vim
> ```

Thanks for this solution.

I wanted to use vim.exe inside of Portable Git-Bash, so what I ended up doing was assigning the environment variable `XDG_CONFIG_HOME=/home/.config` to a [.bat](https://github.com/git-for-windows/git/issues/320#issuecomment-140278002) file that I use to launch git-bash.exe with custom environment variables.

From there, I was able to use the default code from the docs, which I pointed to my .vim/vimrc file (I use both).

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vim/vimrc
```

**Comment by iamdebajyoti** [comment]
> Thanks, it worked. Here's the code I used (in case anyone reading this wants another example):
> 
> ```
> let s:config_path = fnamemodify(expand("$VIM"), ':h:h') . '\config' " Get the path equivalent to $VIM\..\..\config (where I'm putting my config files)
> let &rtp .= ',' . s:config_path " Add custom runtime path
> exec 'source ' . s:config_path . '\init.vim' " Source the init.vim file
> ```
> 
> The `config` folder I mentioned above is on the same directory as the `bin` and `share` folders.



> Thanks, it worked. Here's the code I used (in case anyone reading this wants another example):
> 
> ```
> let s:config_path = fnamemodify(expand("$VIM"), ':h:h') . '\config' " Get the path equivalent to $VIM\..\..\config (where I'm putting my config files)
> let &rtp .= ',' . s:config_path " Add custom runtime path
> exec 'source ' . s:config_path . '\init.vim' " Source the init.vim file
> ```
> 
> The `config` folder I mentioned above is on the same directory as the `bin` and `share` folders.

I would like to understand how and where have you placed the code as per that solution you mentioned. I too have a similar requirement where I want to keep the config folder independent of the user profile and in the same folder as Neovim is.
Can you help me out in this ?

**Comment by YohananDiamond** [comment]
@iamdebajyoti
I haven't used this setup in a while so I'm not as familiar with it as before (and it seems to be messed up for some reason), but I found the code again and it's structured like this (the relevant parts):
```
base_folder/
  bin/
    nvim/ [here's the actual neovim installation]
      bin/
      share/
        nvim/
          sysinit.vim [the file with the snippet I sent, but slightly different - I'll resend it below]
  config/
    nvim/ [my actual config]
      ...
      init.vim
    config/nvim/ [I'm not sure what happened here but I think I accidentally duplicated the config folder inside itself]
```
And, as I mentioned in the block above, the new version of `sysinit.vim`:
```vim
let s:config_path = fnamemodify(expand("$VIM"), ':h:h:h:h') . '\config\nvim'
let &rtp .= ',' . s:config_path
exec 'source ' . s:config_path . '\init.vim'
```

**Comment by iamdebajyoti** [comment]
Thanks for responding to my query.
A few points to clarify -

  1.  I am not seeing any "sysinit.vim" file under the "share\nvim" location. Do I need to create it manually?
  2.  Is that "$VIM" mentioned in the 'let' statement, an environment variable ? If yes, did you set that at the OS level separately?

________________________________

**Comment by YohananDiamond** [comment]
1. Yes, you can create it - as far as I know it doesn't come with the default installation.
2. Yes, it's an environment variable, but it's set automatically by vim/neovim (no need to change it). I'm not sure exactly what the path would be on a portable installation anymore, but on my linux machine its value is `/usr/share/nvim`.
