### ISSUE TITLE
Remaining LSP features

### ISSUE THREAD

**Issue by Kyle-Thompson** [neovim/neovim#11553]
Within neovim's new built in LSP client we have:
- textDocument/completion
- textDocument/hover
- textDocument/signatureHelp
- textDocument/declaration
- textDocument/definition
- textDocument/typeDefinition
- textDocument/implementation

Is there any plan to integrate other LSP features like
- formatting
- find references
- code folding
- code extraction
- rename
- etc, etc

I'm not aware of a roadmap for the remaining LSP features or any statement on whether or not they will eventually be included.

**Comment by bfredl** [comment]
Please see https://github.com/neovim/neovim/issues/11389. Also making noise on https://gitter.im/neovim/neovim works to advance the discussion of new features.
