### ISSUE TITLE
Lua api questions

### ISSUE THREAD

**Issue by iodpin** [neovim/neovim#11550]
vim.api.nvim_get_current_line() gives current line, but how can I get current line number directly through lua api?

...and second question: what's the most efficient way to map lua function to button, afaik, vim.api.nvim_set_keymap requires line that can contain ":lua my_func()", is it really the most efficient way?

Thank you in advance for any help.

**Comment by bfredl** [comment]
Use `vim.api.nvim_win_get_cursor(0)`. Please use https://gitter.im/neovim/neovim for usage questions like this, to not fill up the issue tracker (which is for bugs and feature requests).

> ...and second question: what's the most efficient way to map lua function to button, afaik, vim.api.nvim_set_keymap requires line that can contain ":lua my_func()", is it really the most efficient way?

Currently yes, but we would like to improve it.
