### ISSUE TITLE
Dropping quickly typed keystroke.

### ISSUE THREAD

**Issue by sixcircuit** [neovim/neovim#11557]
Thanks for the awesome software.

- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?  No
- Operating system/version: macOS 10.15.1
- Terminal name/version: iTerm2 3.3.7
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`
`:map ; :`
insert some text
enter normal mode
(very quickly) type: `<ESC>;w<CR>`
The ";" isn't picked up, the file isn't saved, and the cursor moves one word.
```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
The ":" isn't picked up, the file isn't saved, and the cursor moves one word. It's losing a key.

### Expected behaviour
The file would be saved. 
It works when pressing the keys slowly, but not when typing fast. 
I type this combination a lot, so I do it very quickly. 
I can see in my keyboard event viewer that the proper keys are being sent.

Can reproduce inside or outside of tmux with `nvim -u NORC`. 
This doesn't happen in vim.
I use zsh (if it matters).

**Comment by justinmk** [comment]
:checkhealth

may offer advice if you're using tmux. Anyways, see https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed

**Comment by sixcircuit** [comment]
Why was this closed as not a bug?

I'm not using tmux or screen. Neovim drops the keystroke.

**Comment by justinmk** [comment]
It's not a bug. ESC+key within a certain timeout (hinted in the FAQ I already referenced) is interpreted by Nvim as ALT/META. You can adjust this if you don't like it. It's a limitation of terminals.

https://github.com/neovim/neovim/issues/6279 is more robust solution.

**Comment by sixcircuit** [comment]
So it's been a year and a half and I finally revisited nvim and figured out the problem. I'm happy to say it seems fixed and nvim is useable now. I'm posting the solution here in case someone runs across it. I found the eventual solution [here](https://www.johnhawthorn.com/2012/09/vi-escape-delays/), although I didn't seem to need the zsh part:

```
# tmux.conf

# might mess with tmux's ability to detect meta characters directed at it. not an issue for me
# need it to keep nvim escape detection working properly
set-option -sg escape-time 0
```
```
" vimrc

" one part of fixing slow / missing escapes in nvim
set timeoutlen=1000 ttimeoutlen=0
```

Thanks for the great software.
