### ISSUE TITLE
command 'vscode-neovim.up' not found

### ISSUE THREAD

**Issue by subhakarks** [neovim/neovim#11567]
I am using VsCode on MAC OSX. I installed vscode-vim and editor works fine. Now, I installed vscode-neovim extension and updated settings.json with below

"vim.enableNeovim": true,
"vim.neovimPath": "/usr/local/bin/nvim"
However, when I press arrow-keys in editor, I am getting below message

command 'vscode-neovim.up' not found
I checked the Keyboard Shortcuts see below entries for vscode-neovim.up, etc. like below attachment.

![Screen Shot 2019-12-16 at 4 10 39 PM](https://user-images.githubusercontent.com/23250456/70954746-4b731980-2023-11ea-93a6-887cddfb2f49.png)

**Comment by justinmk** [comment]
This isn't a support forum for VScode plugins.

(FWIW, I do use vscode and the `vscode-neovim` plugin works just fine.)

**Comment by subhakarks** [comment]
Tried un-installing vscode, vscode-vim and installed clean slate vscode_+vscode-neovim alone.
But still seeing same issues. May be some issue with my environment. Giving-up for now.

**Comment by matsko** [comment]
Hop into your vscode settings and enter in the vscode-neovim path there.

Your `settings.json` file should end up looking like this (for OSX): 

```
    "vscode-neovim.neovimPath": "/usr/local/bin//nvim"
```
