### ISSUE TITLE
Add debian packaging directory to project repo

### ISSUE THREAD

**Issue by Toothless204** [neovim/neovim#11560]
Provide a debian packaging directory to work as base for people to build packages from, this would also provide a solution for people to build a more up to date version on Debian and enable people to make their own deb packages

**Comment by justinmk** [comment]
> his would also provide a solution for people to build a more up to date version on Debian

That's documented in the wiki for debian, and many more:

https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites

> and enable people to make their own deb packages

Wouldn't people who are versed in making deb packages, be accustomed to finding the deb package source in the deb package manager? From [the wiki](https://github.com/neovim/neovim/wiki/Building-Neovim#third-party-dependencies):

https://packages.debian.org/sid/source/neovim

**Comment by blueyed** [comment]
/cc @jamessan FYI
IIRC I've seen "debian" dirs with upstream projects, so it might be a feasible option here also, but only if it makes sense to you.
