### ISSUE TITLE
switching to english keyboard layout when return to normal mode(for non english user).

### ISSUE THREAD

**Issue by srrrrrr27** [neovim/neovim#11561]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: MacOS 10 high sierra
- Terminal name/version:
- `$TERM`:bash

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
hi,
 i type hangul(korean letter) in nvim very often. when escape from insert mode, i have to switch to english layout manually by pressing 'command+spacebar'. it's very inconvenient and causes mistyping frequently. the solutions on internet are not that effective. i think it would be a big problem in other non english language countries too.

### Expected behaviour
just when return to normal mode, automatically switch to english keyboard layout.
or such option.  thanks.
ps. pls understand my poor english.

**Comment by noocsharp** [comment]
Have you looked into the langmap feature? It allows you to map Hangul characters to Latin characters only in normal mode, while leaving them intact in insert mode. It is explained further on its help page.

**Comment by srrrrrr27** [comment]
Thank you for your answer.
I have tried 'langmap'. It does work. But i think that it's temporary solution. There are some problems in that. 

1. It works in normal mode, but still doesn't work in command mode. 

2. For example, when i press 'ㅏ' instead 'k', the cursor moves up. But unlike pressing 'k', character 'ㅏ' appears on the cursor position, besides the sentence on the cursor position's right side is pushed back 2 spaces. That 'ㅏ' never disappears until 'esc' pressed.

3. Due to Hangul's distinct nature, sometimes i have to press 'ㅏ' 2~3 times. 
*Hangul has distinctive system that can combine 2~3 letters to form one another letter. It's like Lego block. For example, when press 'ㅗ - ㅏ' instead 'h - k', the two letters are combined to 'ㅘ'. And computers recognize them distinct letter. So It doesn't work properly.

So, i think that switching to english layout automatcally is a clean solution.

**Comment by justinmk** [comment]
You could use an `InsertLeave` autocmd.
