### ISSUE TITLE
netrw: opening folders locks nvim with strange input 

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#11571]
- `nvim --version`: NVIM v0.5.0-241-g9f3d483c7
- `vim -u DEFAULTS` (version: ) behaves differently? Yes. with `-DEFAULTS` it doesn't open directories. without it, it opens the directory but it doesn't lock
- Operating system/version: Arch Linux
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:!mkdir test
:e test
```

### Actual behaviour

The terminal locks up as if there was extraneous input, forcing me to close it. 
![output](https://user-images.githubusercontent.com/221465/71070601-69539200-217b-11ea-8dee-52748c960dd9.gif)

(I recorded it with my full config, but the problem still happens with `-u NORC`).

Since the problem doesn't happen with vim, I assume it is not the terminal that is causing the issue.

### Expected behaviour

The terminal doesn't lock up.

**Comment by bfredl** [comment]
Could this part of netrw:s general issue of abusing the clipboard? IIRC there have been other issues (but not exactly a lockup) cased by netrw invoking clipboard and then the clipboard provider stealing focus (which would be the "Unknown" here)

**Comment by fmoralesc** [comment]
I thought about it, specially since I'm working in a wayland session and the clipboard is a bit janky anyway.

**Comment by justinmk** [comment]
sounds like https://github.com/neovim/neovim/issues/6695
