### ISSUE TITLE
API: UI event with real (not screen) cursor position

### ISSUE THREAD

**Issue by asvetliakov** [neovim/neovim#11584]
Currently `grid_cursor_goto`/`cursor_goto` is telling only the screen position. There is no way to get real cursor position without resorting to `nvim_win_get_cursor()`. This is big headache when you can't blindly render what you've got in `grid_lines` event and you need to maintain cursor position in external text document.

something like `grid_cursor_pos` with `[grid, line, column]` arguments would work

also related #11369

**Comment by justinmk** [comment]
> There is no way to get real cursor position without resorting to `nvim_win_get_cursor()`.

It could be derived from `nvim_win_get_width`/`height` + buffer line count, though that doesn't account for soft wrapping /  virtual chars.

What do you mean by "real" cursor position? The byte-offset relative to the buffer contents? There is `nvim_buf_get_offset` but it doesn't take a screen column...

**Comment by asvetliakov** [comment]
>What do you mean by "real" cursor position? 

analogue of ```nvim_win_get_cursor()``` result but in ui event

>It could be derived from nvim_win_get_width/height + buffer line count, though that doesn't account for soft wrapping / virtual chars.

Nope, that won't work

Sorry, i've explained incorrectly. I have fixed height/width 200/500 and buffer with 1000 lines. I put cursor on first line - `grid_cursor_goto` has [0, 0] as cursor pos. Then i type `400G` and receive `grid_cursor_goto` with `[99, 0]`. Then i type `G` and receive `[199, 0]` in `grid_cursor_goto`. In all cases the pos here is the screen pos, while i need position in a window relative to whole buffer.

And no, `grid_scroll` doesn't work in all cases

**Comment by justinmk** [comment]
If we had a "scroll" event https://github.com/neovim/neovim/issues/8854 would it be acceptable then to call `nvim_win_get_cursor()` when that event is emitted?

> And no, `grid_scroll` doesn't work in all cases

You mean it's not emitted in all cases, or what do you mean?

> i need (either as additional argument or as separate ui event) line position relative to whole buffer

What about column? And/or  byte-offset from start of buffer?

**Comment by asvetliakov** [comment]
>If we had a "scroll" event #8854 would it be acceptable then to call nvim_win_get_cursor() when that event is emitted?

No. Totally unacceptable. Any async method from `redraw` queue may produce racing effects (in case not pausing queue and moving cursor fast, like holding `j`) or will make cursor laggy (in case pausing redraw for awaiting of result of `nvim_win_get_cursor()`). I've tried both methods and they don't work good. In latest vscode-neovim i'm resorting `CursorMoved` autocmd which also doesn't work in all cases (e.g. for incsearch since we're in cmdline mode). And now trying to workaround it by reading line number (from `set number`) from `grid_line` events (works best for now😄 🐵  )

>You mean it's not emitted in all cases, or what do you mean?

1) it's not being sent if you press `G` in large file. May be few other cases as well, btw just a single case when it doesn't work makes it's not reliable for the source of truth.
2) if you set scrolloff=100 when height is like=200 (another hack to not deal with screenrow positioning, which was another pain) the scroll lines will be always `1`/`-1` (due to nature of scrolloff i think)

>What about column?

Columns & multi-byte chars are different story and deserve a separate issue(s), my concerns in short:
1) API when using multi-byte chars is not consistent: for example for chinese chars `grid_cursor_goto`/`nvim_win_get_cursor()` returns column shifted by 3byte width (e.g. if you have cursor on 0 line, 3rd column, it will return `[0, 6]`), but `grid_line` assumes they are 2byte widths (e.g. if you search 3d char if will return start `4`)
2) character byte width is implementation detail. I'd not to deal with them at all - it's useless when UI has own external buffer model. Each time i receive cursor or grid_line event i need to iterate through a line to align a proper byte offset for cursor col / start of the `grid_line` col.

>And/or byte-offset from start of buffer?

don't need byte offset at all, need character based api/events.

**Comment by bfredl** [comment]
I also think we want this. Or perhaps more general a mode of the UI protocol taylored to clients rendering the windows themselves, like vscode does. In this mode the client won't receive `grid_lines` of the buffer at all, rather "semantic" info like where the topline and cursor is (which also can be set by the UI) and the non-text "state" https://github.com/neovim/neovim/issues/9421#issuecomment-477931420 needed for equivalent rendering.

Though we should probably just add something like `win_viewport[win, grid, topline, botline, cur_row, cur_col]` already, which will make life easier for solutions based on the existing API.
