### ISSUE TITLE
Odd highlighting in floating window

### ISSUE THREAD

**Issue by ckipp01** [neovim/neovim#11585]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS`: Vim 8.1 + behaves differently
- Operating system/version: MacOS
- Terminal name/version: iTerm2
- `$TERM`: fish

### Description
To be 100% honest, I'm not sure this is a bug in the way that plugins use the feature or an odd setting that seems to be never being set right. I use `coc.nvim` very frequently as well as other LSP clients, and I've noticed that when any of them render the markdown for function signatures, etc in the floating window, there is odd highlighting that happens, which doesn't happen in vim. I've posted in various places such as themes and `coc.nvim` to see if someone can explain what is happening, but I haven't been able to nail it down yet. It'd be amazing if someone could give a bit of insight into _what_ is actually happening here. I feel like it'd really help people using the floating window to use it correctly. I've included a few examples below to illustrate what I mean.

 Here is an example with no theme and vanilla nvim with coc.nvim showing a floating window just to show that it's not theme related.
<img width="497" alt="theme" src="https://user-images.githubusercontent.com/13974112/71307165-9659ac00-23ea-11ea-8738-9d3b8c4a5ac7.png">

Here is an example of one using a theme.
<img width="267" alt="vanilla" src="https://user-images.githubusercontent.com/13974112/71307152-817d1880-23ea-11ea-8d51-2fe8f8ff0603.png">

Here is a closeup
![closeup](https://user-images.githubusercontent.com/13974112/71307169-ad000300-23ea-11ea-9679-590b62de4e64.png)

Here is a [link](https://github.com/neoclide/coc.nvim/issues/1248) to another user having this issue.

Here is [the code generating it for coc.nvim](https://github.com/neoclide/coc.nvim/blob/dc888b4a6e1e3c70049c41d1edda06c76b853983/src/model/floatFactory.ts#L165).

Again, it'd be great to clean up what the actual issue is here.

### Steps to reproduce
1. Install nvim
2. The easiest way is to probably install [coc.nvim](https://github.com/neoclide/coc.nvim), and hook up any of the language servers, trigger a hover to see a signature.
3. See the issue

**Comment by justinmk** [comment]
try installing https://github.com/tpope/vim-scriptease , then navigate to the floating window, put the cursor on the "wrong" highlight, and use `zS` to see the resolved syntax group. Use `1zS` to see the next one in the stack, `2zS`, etc...

**Comment by ckipp01** [comment]
Thanks for the quick reply, and recommendation. I didn't know about that plugin!

I did download it, but it seems that when I get the floating window to appear and then go into it, navigate to the "wrong" highlight, there is no resolved syntax group that shows up.

I tried it with a Scala project being powered by Metals
<img width="719" alt="Screenshot 2019-12-22 at 08 29 55" src="https://user-images.githubusercontent.com/13974112/71318795-e3df2300-2495-11ea-9087-21d29f01bc6d.png">

And a typescript project powered by the tsserver
<img width="821" alt="Screenshot 2019-12-22 at 08 36 04" src="https://user-images.githubusercontent.com/13974112/71318809-315b9000-2496-11ea-9721-86dda9137ba5.png">

**Comment by justinmk** [comment]
Might be one of these:

```
:hi Whitespace
:hi Special
```

**Comment by ckipp01** [comment]
> Try changing those highlights and see the result

Just tried them both. `Special` changed a couple things, but not the odd highlighting.

**Comment by ckipp01** [comment]
I'm going to go ahead and close this. I appreciate the input. I ended up figuring out a way to turn off all highlighting in the window, and when I do, then the odd highlighting goes away

<img width="821" alt="Screenshot 2019-12-22 at 16 23 32" src="https://user-images.githubusercontent.com/13974112/71323799-908dc480-24d7-11ea-8e0d-ed40f0ec271f.png">

I'm still not sure what is doing that when they have highlighting turned on, but either way, I know it's something that coc.nvim is doing, and I can dive into it there. Thanks again!

**Comment by joshdick** [comment]
I know this issue is closed now, but FWIW, it appears to be an issue with `coc.nvim` and not with Neovim: https://github.com/neoclide/coc.nvim/issues/1248#issuecomment-574700784
