### ISSUE TITLE
can't map using cmd key

### ISSUE THREAD

**Issue by eyalk5** [neovim/neovim#11583]
- `nvim --version`: 
NVIM v0.5.0-233-g76d1e9360
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall
 -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-stron
g -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/travis/build/
neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/
local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/in
clude
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: High Sierra
- Terminal name/version: Iterm2 Build 3.3.8beta3
- `$TERM`: xterm_256colors

### Steps to reproduce using `nvim -u NORC`

```
nmap <D-b> yy
nmap <d-b> yy
```
press `<d-b>` 

### Actual behaviour
nothing happens
### Expected behaviour
it will yank text.

--

It seems that you support it. So, how come it is not working in terminal?
I tried setting " Report modifiers using CSI u" and it didn't matter.

**Comment by justinmk** [comment]
> It seems that you support it. So, how come it is not working in terminal?

That's up to your terminal. Has nothing to do with Nvim.
