### ISSUE TITLE
Start Neovim asynchronously before reading the whole file

### ISSUE THREAD

**Issue by hariamoor** [neovim/neovim#11581]
Neovim currently only makes a buffer accessible to a user when the entire contents of the underlying file is available. In reality, though, it only needs enough characters to fill up the window, and the rest can be done with `:read` calls or something similar in the background (and perhaps `setl lazyredraw`).

I can see this served as a plugin doing exactly as detailed above, but I'd want it to ship with the editor itself. This way, Neovim could be able to tail a server or a log, and provide useful information with the output (perhaps in an `efm`-like fashion).

**Comment by justinmk** [comment]
Tracked in https://github.com/neovim/neovim/issues/614

**Comment by hariamoor** [comment]
Will see if I can make a plugin for this.
