### ISSUE TITLE
nvim_buf_lines_event: wrong edits received

### ISSUE THREAD

**Issue by asvetliakov** [neovim/neovim#11591]
- `nvim --version`: 0.4.3 / v0.5.0-253-g138480939
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: ArchLinux latest in WSL
- Terminal name/version: no applicable
- `$TERM`: no applicable

initial text:
```
abc
{
def
}
```
type: `yyjjvi{p`

receives following edits from nvim_buf_lines_event (`[buf, tick, firstLine, lastLine, lineData, more]`)
```json
[
 [1, 1, 2, 3, [""], 0],
 [1, 2, 2, 3, ["}"], 0], // <- here is the problem
 [1, 3, 3, 4, [], 0],
 [1, 4, 3, 3, ["abc", "}"], 0]
]
```

The result after applying these edits is
```
abc
{
}
abc
}
```
rather than:
```
abc
{

abc
}
```

I'm not sure if i don't miss anything here and it's a bug. Pressing `u` followed by `r` returns expected changes. Terminal nvim behaves as expected

**Comment by norcalli** [comment]
Other errors discovered #11380

**Comment by justinmk** [comment]
Looks like this is still an issue on b7084fef4c85

## Steps using pynvim

```
n = pynvim.attach('socket', path='/Users/justin/.local/state/nvim/nvim.68908.0')
n.request('nvim_buf_attach', 1, False, {})
while True: m=n.next_message(); print(m);

['notification', 'nvim_buf_changedtick_event', [<Buffer(handle=1)>, 6]]
['notification', 'nvim_buf_lines_event', [<Buffer(handle=1)>, 7, 2, 3, [''], False]]
['notification', 'nvim_buf_lines_event', [<Buffer(handle=1)>, 8, 2, 3, ['}'], False]]
['notification', 'nvim_buf_lines_event', [<Buffer(handle=1)>, 9, 3, 4, [], False]]
['notification', 'nvim_buf_lines_event', [<Buffer(handle=1)>, 10, 3, 3, ['abc', '}'], False]]
```

**Comment by glepnir** [comment]
I'm not sure how to handle this.
first notification `[1, 1, 2, 3, [""], 0]` from  `truncate_line` make lnum 3 to empty `''`
https://github.com/neovim/neovim/blob/d7359a87425dc38efda4f74bd580bae9946abe31/src/nvim/ops.c#L1732

in `truncate_line -> changed_bytes -> buf_updates_send_changes`

second from `do_join` 
https://github.com/neovim/neovim/blob/d7359a87425dc38efda4f74bd580bae9946abe31/src/nvim/ops.c#L1745

in `do_join` newp get value from there . It merges the text `}` of the next line (lnum 4) into lnum 3 `''` . then newp will be `}`  and lnum 3 text will replace by newp in `ml_replace_by` . then `changed_lines` invoked send buf changes. now `ml_get(3)` will by `}` .

https://github.com/neovim/neovim/blob/d7359a87425dc38efda4f74bd580bae9946abe31/src/nvim/ops.c#L4121-L4154
