### ISSUE TITLE
Missing redraw when resizing floating windows in scroll auto commands

### ISSUE THREAD

**Issue by wellle** [neovim/neovim#11597]
- `nvim --version`:
    ```
    NVIM v0.4.3
    Build type: Release
    LuaJIT 2.0.5
    Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
    Compiled by brew@Catalina.local

    Features: +acl +iconv +tui
    ```

- `vim -u DEFAULTS` (version: ) behaves differently?
    This is about neovim floating window behavior, so neovim specific.

- Operating system/version:
    macOS Catalina 10.15.2

- Terminal name/version:
    kitty 0.12.3

- `$TERM`:
    `screen-256color`

### Steps to reproduce using `nvim -u NORC`

Put this file `repro.vim` in a directory:
```vim
function! s:open()
    let s:lines = nvim_buf_get_lines(0, 0, -1, v:true)
    let s:height = 1 " initial float height
    let buf = nvim_create_buf(v:false, v:true)
    call nvim_buf_set_lines(buf, 0, -1, v:true, s:lines)
    let opts = {
                \ 'relative':  'win',
                \ 'width':     winwidth(0),
                \ 'height':    s:height,
                \ 'col':       0,
                \ 'row':       0,
                \ }
    let s:float = nvim_open_win(buf, 0, opts)
endfunction

function! s:resize()
    let s:height = 10 - s:height " toggle size between 1 and 9
    call nvim_win_set_config(s:float, {'height': s:height})
endfunction

" open floating window now
call s:open()

" resize it every time the cursor moves
autocmd CursorMoved * call s:resize()
```

Open the file in neovim (just so we have a nonempty buffer to look at):
```
nvim -u NONE --noplugin repro.vim
```

Source the file in neovim:
```vim
:source repro.vim
```

This will open a floating window showing some lines:

<img width="813" alt="Screenshot 2019-12-23 14 26 27" src="https://user-images.githubusercontent.com/474504/71360512-6b10c180-2590-11ea-9ea5-a5f6949d506c.png">

To reproduce the issue make sure the cursor is on the first visible line (<kbd>H</kbd>), then type <kbd>C-E</kbd> to scroll down one line. This will move the cursor to the second line and trigger the auto command which will resize the floating window.

### Actual behaviour

This is what it looks like:

<img width="813" alt="Screenshot 2019-12-23 14 26 32" src="https://user-images.githubusercontent.com/474504/71360514-706e0c00-2590-11ea-966e-11202379a06f.png">

### Expected behaviour

This is what it should look like instead:

<img width="813" alt="Screenshot 2019-12-23 14 26 37" src="https://user-images.githubusercontent.com/474504/71360521-74019300-2590-11ea-90a2-dddb771d4581.png">

You can fix the redraw issue by typing <kbd>C-L</kbd>, but neovim should properly redraw it itself.

You can keep going down with <kbd>C-E</kbd> or up with <kbd>k</kbd> (with cursor on topmost visible line so that they trigger both cursor movement and scrolling at the same time) to keep reproducing the issue.

### Context

This came up when working on https://github.com/wellle/context.vim trying to utilize the new floating windows, as they seem to be a very good fit for this use case. I'm very pleased with the new window and buffer API you made available and ran into this issue. I hope you can look into this and fix this redrawing issue. Thank you!

**Comment by wellle** [comment]
>- `vim -u DEFAULTS` (version: ) behaves differently?
    This is about neovim floating window behavior, so neovim specific.

Quick update: FWIW I implemented the same feature for Vim using popup windows and I don't see any issues there.

Here's a similar script to the one above which can be used to test this in Vim:
```vim
function! s:open()
    let s:lines = getbufline('.', 1, '$')
    let s:height = 1 " initial float height
    let opts = {'line': 1, 'minwidth': winwidth(0), 'wrap': v:false}
    let s:popup = popup_create(s:lines[: s:height-1], opts)
endfunction

function! s:resize()
    let s:height = 10 - s:height " toggle size between 1 and 9
    call popup_settext(s:popup, s:lines[: s:height-1])
endfunction

" open floating window now
call s:open()

" resize it every time the cursor moves
autocmd CursorMoved * call s:resize()
```

**Comment by wellle** [comment]
And another small update in case someone else runs into this: As a workaround I'll just trigger a redraw after changing the floating window's height:
```vim
call nvim_win_set_config(s:float, {'height': s:height})
mode " clears and redraws the screen
```
I'll be happy to remove it once this issue has been resolved. :v:

**Comment by justinmk** [comment]
`:mode` is drastic. Does `:redraw` not work ?

**Comment by wellle** [comment]
I tried that first, it does not fix the redraw issue unfortunately.

**Comment by kevinhwang91** [comment]
@wellle https://github.com/neovim/neovim/commit/8fe19d9d89d90eed347d9bfeb99446c0f400cca1 fix my issue, did you try it?

**Comment by wellle** [comment]
Thanks for the ping, I'll try that 👍

**Comment by glacambre** [comment]
This seems to be fixed on master, so I'll close this :)
