### ISSUE TITLE
netrw is still slow due to pbcopy/pbpaste usage on Mac OSX

### ISSUE THREAD

**Issue by artem-nefedov** [neovim/neovim#11592]
- `nvim --version`:
NVIM v0.5.0-781c708
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20191222-34593-2hpft4/build/config -I/tmp/neovim-20191222-34593-2hpft4/src -I/usr/local/include -I/tmp/neovim-20191222-34593-2hpft4/deps-build/include -I/usr/local/opt/gettext/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20191222-34593-2hpft4/build/src/nvim/auto -I/tmp/neovim-20191222-34593-2hpft4/build/include
Compiled by anefedov@mow-mbp-18-0048

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-781c708/share/nvim"

- Operating system/version:
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103
- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:Explore
... Navigate between dirs

```

### Actual behaviour

netrw directory navigation is still very slow because it calls `pbcopy`/`pbpaste` each time. `pbpaste` is even visible in terminal window header each time directory is switched. Same root cause as #11089.

### Expected behaviour

After #11089, it was assumed that netrw will no longer use system clipboard during navigation.

**Comment by justinmk** [comment]
PR welcome, otherwise not interested in spending time on netrw.

**Comment by artem-nefedov** [comment]
Sure, this is fair. But, actually, netrw only shows underlying problem: neovim's way of accessing OSX clipboard via pbcopy/pbpaste is several tens of times slower than vim's native way. Which is why, with vim, you never notice that netrw accesses system clipboard, while with neovim it becomes a problem. I believe benchmarks were already posted earlier.

I wonder why do we can't just use the same way as vim for clipboard interaction on OSX. Sure, I understand the logic of readability and better maintainability, but not when performance tradeoff is this huge.

**Comment by justinmk** [comment]
> But, actually, netrw only shows underlying problem: neovim's way of accessing OSX clipboard via pbcopy/pbpaste is several tens of times slower than vim's native way.

True (and known issue) but almost never matters. And just hides badly designed plugins like netrw.

> why do we can't just use the same way as vim for clipboard interaction on OSX

Nvim's clipboard provider architecture allows things like `g:clipboard`, seamless tmux integration, etc.
