### ISSUE TITLE
wildmode=longest,full doesn't use popup menu

### ISSUE THREAD

**Issue by MageJohn** [neovim/neovim#11622]
- `nvim --version`: v0.4.3

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set wildmode=longest,full
```
Then try and complete a command where 'longest' applies, followed by further presses of `<Tab>`. For example: `:set ba<Tab><Tab>`. 

### Actual behaviour
Wildmenu mode is started as if 'pum' was not in 'wildoptions'.

### Expected behaviour
A popup menu should open up with the list of completions. 

### Notes
If there is no longest common string to complete the popup menu still opens.

**Comment by justinmk** [comment]
confirmed NVIM v0.5.0-272 4f4c06a7a46e
