### ISSUE TITLE
Another choice of `LUAROCKS_URL` in `./third-party` ?

### ISSUE THREAD

**Issue by yeahnoob** [neovim/neovim#11621]
The following URL in `./third-party` could be `https://luarocks.github.io/luarocks/releases/luarocks-3.2.1.tar.gz` , with smaller download size and the same function (only tested in Linux)

`https://github.com/luarocks/luarocks/archive/v3.2.1.tar.gz`

Current [LUAROCKS_URL](https://github.com/neovim/neovim/blob/52566dd780a0ac5c584213111e6f5294874195a9/third-party/CMakeLists.txt#L156) .

**Comment by blueyed** [comment]
Thanks, sounds good to me.
The current URL is the Git snapshot, while the new one would be the actual release.
(the current URL allows for easier switching to some tag/commit, but that should not hold us back)
Please consider creating a PR, which would test it on CI already, but also let me/us know if we should do it instead.

**Comment by justinmk** [comment]
> with smaller download size

How much smaller exactly?
