### ISSUE TITLE
Add `OnModeSwitch` autocommand event

### ISSUE THREAD

**Issue by DrBluefall** [neovim/neovim#11627]
Hello!

I've noticed while digging through the Neovim docs that there are ways to detect mode switches. Specifically, these:

- `CmdlineEnter`         after entering cmdline mode
- `CmdlineLeave`        before leaving cmdline mode
- `InsertEnter`             starting Insert mode
- `InsertLeave`            when leaving Insert mode

However, there's no general `OnModeSwitch` event amongst them. And I think that having the former could be really useful to use (in conjunction with `mode()`) for doing more specific functions for specific modes, or for use in plugins.

**Comment by justinmk** [comment]
We definitely want this. Need someone to work on it.

Duplicate of https://github.com/neovim/neovim/issues/4399
