### ISSUE TITLE
test/CI/Travis: functional tests end abruptly

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#11635]
Recently travis `gcc-32bit` job sometimes fails. 

https://travis-ci.org/neovim/neovim/builds/630908571

Functional tests end abruptly, apparently the test runner exits in the middle of:

```
[ RUN      ] jobs does not invoke callbacks recursively: 1507.49 ms OK
[ RUN      ] jobs jobstart() works with pa-- Configuring done
-- Generating done
-- Build files have been written to: /home/travis/nvim-deps
mkdir -p build
```

Strangely, the end of the log shows:

```
F /tests/oldtests|oldtests :: Legacy tests failed
F /tests|run_oldtests :: Test run_oldtests failed
```

but the actual `oldtest` summary is:

```
Executed:  1519 Tests
 Skipped:    60 Tests
  Failed:     0 Tests
```

**Comment by justinmk** [comment]
This "test runner exits abruptly" symptom isn't consistently correlated with any particular functional test. E.g. in https://travis-ci.org/neovim/neovim/builds/635828493 :

```
[----------] 3 tests from test/functional/cmdline/history_spec.lua (26.90 ms total)
[----------] Running tests from test/functi-- Configuring done
-- Generating done
-- Build files have been written to: /home/travis/nvim-deps
```

There too the final summary reports `run_oldtests failed` with `Failed: 0 Tests`, as above.

**Comment by erw7** [comment]
This seems to be the case for all jobs, including successful ones after https://travis-ci.org/github/neovim/neovim/jobs/618434888.

```
[ RUN      ] TabClosed au TabClosed with * as <afile> matches when closing any tab: 6.69 ms OK
[ RUN      ] TabClo++submit_coverage functionaltest
++'[' -n '' ']'
++check_sanitizer /home/travis/build/neovim/neovim/build/log
```

Also, up until the last [618372347](https://travis-ci.org/github/neovim/neovim/jobs/618372347), the character attribute appeared in the test, but not after [618434888](https://travis-ci.org/github/neovim/neovim/jobs/618434888).

I don't know if it has anything to do with this or not, but since https://travis-ci.org/github/neovim/neovim/builds/691296066, it seems to fail without any output from functional tests.

```
[12/12] cd /home/travis/build/neovim/neovim/build && /opt/cmake-custom/bin/cmake -DBUSTED_PRG=/home/travis/nvim-deps/usr/bin/busted -DLUA_PRG=/home/travis/nvim-deps/usr/bin/luajit -DNVIM_PRG=/home/travis/build/neovim/neovim/build/bin/nvim -DWORKING_DIR=/home/travis/build/neovim/neovim -DBUSTED_OUTPUT_TYPE=nvim -DTEST_DIR=/home/travis/build/neovim/neovim/test -DBUILD_DIR=/home/travis/build/neovim/neovim/build -DTEST_TYPE=functional -P /home/travis/build/neovim/neovim/cmake/RunTests.cmake
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

I feel like there is a problem with the output.
