### ISSUE TITLE
Update netrw?

### ISSUE THREAD

**Issue by artem-nefedov** [neovim/neovim#11650]
One of the recent `netrw` releases includes the following change:
```
v167:	Nov 29, 2019	
				  * netrw will change @* or @+ less often.
				  Never if I happen to have caught all the
				  operations that modify the unnamed
				  register (which also writes @*).
	
```
Since we removed operations that would save/restore clipboard registers (6c22c7ab97cca9f8dda6863ee7f1db1ce30a3451 and ddffd3173730e744b4c25094be45e3673f7a186d), the risk of clipboard corruption was probably reintroduced. This seems like a valid reason to update to the newer version, which claims not to do that.

Note: new version still has those save/restore operations regardless, so they will need to be removed again, cause they're slow on OSX.

**Comment by janlazo** [comment]
Is there an a list of steps that demonstrates this clipboard corruption you speak of? If you're talking about https://wiki.ubuntu.com/ClipboardPersistence or something similar to other OS, then it happens on Vim only.

**Comment by artem-nefedov** [comment]
No, it's nothing that complicated. Just a pure netrw-specific reasons due to bad design. As one can see from the change description, newtrw may *sometimes* unintentionally write to unnamed register, which also changes `@*`, which is a system clipboard register (if clipboard operations are supported). Save/restore operations for `@*` and `@+` were added to restore clipboard back to original state, but they were recently removed (in neovim only), so the problem could occur.

**Comment by artem-nefedov** [comment]
Sorry, I don't have concrete steps for the issue reproduction.

**Comment by justinmk** [comment]
No point in speculating about "clipboard corruption" that can't be reproduced. Nvim has a different clipboard subsystem than Vim.
