### ISSUE TITLE
Question/Feature request: signcolumn=number

### ISSUE THREAD

**Issue by googleson78** [neovim/neovim#11667]
`vim` [supports](https://github.com/vim/vim/issues/4515) `signcolumn=number`, which displays signs in the number line (overriding the line number).

I searched for a bit but couldn't find: Is this possible in `nvim`, and if not, how hard would it be to implement?

**Comment by bfredl** [comment]
`numh=l` attribute (see `help :sign-define`) can already be used to change the highlight of the number column. `signcolumn=number` would be supported by someone sending a PR for porting the relevant vim patch. Closing for now, as we don't need to have an issue for each unported vim patch.

**Comment by slavistan** [comment]
For those redirected here from google: There's a [pull request](https://github.com/neovim/neovim/pull/12621) for this feature. Looks like it's going to be merged very soon.
