### ISSUE TITLE
nvim-qt.ext not supports the mouse right and laft key

### ISSUE THREAD

**Issue by sober-wang** [neovim/neovim#11665]
- `nvim --version`:0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Windows 10
- Terminal name/version: cmd
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

**Comment by justinmk** [comment]
https://gitter.im/equalsraf/neovim-qt
