### ISSUE TITLE
missing mention about completepopup in the vim_diff.txt help page

### ISSUE THREAD

**Issue by doums** [neovim/neovim#11660]
- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compilé par builduser

Features: +acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/usr/share/nvim"

Run :checkhealth for more info

```

Hi,
I'm new to Neovim and I'm currently migrating from Vim8 to it. While I'm trying to adapt my `.vimrc` to the new `init.vim` file, I noticed that the `completepopup` option does not seem to exist in Neovim. The problem is that it is not documented in `vim_diff.txt` page. I think it should be.

**Comment by justinmk** [comment]
we'll probably add it at some point, but we can mention it there meanwhile.

**Comment by justinmk** [comment]
`:help nvim-features-removed` is for intentionally removed features. Not whatever random feature vim happens to implement that we haven't yet implemented.

If something isn't in `:help` then it's probably just not implemented--just like older versions of Vim. One can use `has()` to check for features also.
