### ISSUE TITLE
clipboard=autoselect #2325

### ISSUE THREAD

**Issue by ilkerhk** [neovim/neovim#11672]
This is a comment to a locked issue : clipboard=autoselect #2325
Not sure why it is locked but  I can't add a comment there, so opening this issue. Sorry for the inconvenience, feel free to add it there or delete this comment. 

autoselect feature of clipboard is one of the most used features in vim for me. Lack of it keeps me switching to neovim and enjoying it. 

There is a workaround mentioned in #2325 but it is not consistently working (not usable for me). 
The suggested workaround is to use the settings: 

```
 set mouse=a
 vmap <LeftRelease> "*ygv 
```
 

### Steps to reproduce using `nvim -u NORC`
With the above settings enabled using mouse select one or two lines of text, but release the mouse button somewhere out of the selection paint (i.e. release when mouse pointer is out of the selected region)

### Actual behaviour
Nothing is copied to registers. Note that if you release mouse when pointer is still inside the selected region then it works fine (I can actually see the text selection blink once in that case).

### Expected behaviour
Text selected should be copied to register

**Comment by justinmk** [comment]
The issue is locked because it was getting comments that don't add new information. 

This report also doesn't contain any new information. We're aware of the issue. There are other things that are higher priority and we are working on those things instead.

**Comment by ilkerhk** [comment]
OK got it,
 After reading the discussion I thought there is a working workaround,
thats why I reported.

 keep up with the nice work.
–ilker.

**Comment by furquan-lp** [comment]
Check out my issue #27675 for a better workaround that should (hopefully) work.
