### ISSUE TITLE
`WinNew` event not triggered for float windows

### ISSUE THREAD

**Issue by pwntester** [neovim/neovim#11673]
Hi,

`WinNew` is not triggered when creating a new window and not entering it (eg: `nvim_open_win(_, false, _)`). This is the case for Lsp hover window for example.

I tried to set an autocommand to change winhighlight for this kind of windows but was not able to use `WinNew`

Thanks
A

**Comment by zeertzjq** [comment]
When `enter` is `true` or `false` is unrelated. When `enter` is `true`, `WinNew` is not triggered either.
