### ISSUE TITLE
nvim_get_hl_by_id returns -1 for empty highlight

### ISSUE THREAD

**Issue by kevinhwang91** [neovim/neovim#11680]
I invoke the `nvim_get_hl_by_id` api and get the unexpect k&v. `nvim_get_hl_by_id` will invoke low-level `hlattrs2dict` function. 
For example, using `morning` colorscheme,

    hi Normal ctermfg=Black ctermbg=LightGrey guifg=Black guibg=grey90
    hi Constant term=underline ctermfg=DarkRed guifg=Magenta guibg=grey95

Normal highlight group contains the value of ctermbg, but Constant doen't. `hlattrs2dict(constant_hl_attrs, false)` will return the unexpected dict including k&v 'background: -1' .

I think the below diff snippet code solves the unexpect key&value of the dict, maybe I'm misunderstand the "unexpect" k&v. 
```diff
diff --git a/src/nvim/highlight.c b/src/nvim/highlight.c
index c96f07ed8..c0cae5457 100644
--- a/src/nvim/highlight.c
+++ b/src/nvim/highlight.c
@@ -642,11 +642,11 @@ Dictionary hlattrs2dict(HlAttrs ae, bool use_rgb)
       PUT(hl, "special", INTEGER_OBJ(ae.rgb_sp_color));
     }
   } else {
-    if (cterm_normal_fg_color != ae.cterm_fg_color) {
+    if (cterm_normal_fg_color != ae.cterm_fg_color && ae.cterm_fg_color != 0) {
       PUT(hl, "foreground", INTEGER_OBJ(ae.cterm_fg_color - 1));
     }
 
-    if (cterm_normal_bg_color != ae.cterm_bg_color) {
+    if (cterm_normal_bg_color != ae.cterm_bg_color && ae.cterm_bg_color != 0) {
       PUT(hl, "background", INTEGER_OBJ(ae.cterm_bg_color - 1));
     }
   }
```

**Comment by justinmk** [comment]
Thanks for debugging. You didn't say exactly what args you gave, I assume this (please confirm):

    :echo nvim_get_hl_by_id(hlID('Constant'), v:false)

which returns:

    {'foreground': 1, 'background': -1}

but you want it to return:

    {}

Is that correct? Seems OK to me, perhaps @teto @bfredl can confirm there isn't a reason that callers would need the `-1` value. 

@kevinhwang91 please send a PR with a test. See `test/functional/example_spec.lua` for an example. You can [run the test](https://github.com/neovim/neovim/blob/master/test/README.md#running-tests) like this:

    TEST_FILE=test/functional/example_spec.lua make functionaltest

Please add your test to `functional/api/highlight_spec.lua`

**Comment by kevinhwang91** [comment]
Yes, I get my point.

**Comment by kevinhwang91** [comment]
Yes, you get my point.
