### ISSUE TITLE
Enhancement: show visual block dimension with multiply sign instead of ‘x’

### ISSUE THREAD

**Issue by arzg** [neovim/neovim#11684]
At the moment, when `showcmd` is enabled, the dimension of the current visual block selection is shown in the bottom right corner of the screen: `heightxwidth`. I propose changing this to `height×width`.

Nitpick, I know :)

**Comment by justinmk** [comment]
Custom UIs can already customize this via `ext_messages`. Though you can send a PR if you really feel like it (will require updating some tests most likely).
