### ISSUE TITLE
Better code search with grep

### ISSUE THREAD

**Issue by hariamoor** [neovim/neovim#11682]
People (including myself) really like interactive code search inside Vim, but the defaults and the options available could be better.

1. Options for async searching. Many codebases are large enough that synchronous`:grep` doesn't cut it. There are a lot of plugins that offer async searching, e.g. Marco Hinz's [vim-grepper](https://github.com/mhinz/vim-grepper), but it's low-hanging fruit because all we need is a thin wrapper around the existing grep with `jobstart`. Maybe we could serve this through something like `set asyngrep`.

2. A better way to handle output than `grepformat`. @justinmk mentioned in a previous issue that `*format` is a problematic pattern for dealing with the quickfix menu, and callbacks in VimL or Lua are better. Introducing a better pattern for Neovim would provide some much-needed Aspirin for a lot of people's quickfix headaches.

**Comment by justinmk** [comment]
No objection, but this isn't concrete enough. We have tickets and PRs already for some of this stuff, I'm not going to find them though.
