### ISSUE TITLE
'mouse' is checked inconsitently internally

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#11688]
- `nvim --version`: NVIM v0.5.0-300-ge8d61005d
- Operating system/version: Linux 5.0.0-37-generic 40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce using `nvim -u NORC`

Stick `set mouse=` in your init.vim and then, from a GUI that has `ext_linegrid: true`, `ext_messages: true`, `ext_multigrid: true` and `rgb: true`, run the following RPC calls:
```vim
" Create win 1001 on Grid 4, enter it
let winnr = call nvim_open_win(0, v:true, { 'width': 10, 'height': 10, 'focusable': v:true, 'external': v:true })
call nvim_command("edit buffer_for_win_" . winnr)
" Create win 1002 on Grid 5, enter it
let winnr = call nvim_open_win(0, v:true, { 'width': 10, 'height': 10, 'focusable': v:true, 'external': v:true })
call nvim_command("edit buffer_for_win_" . winnr)
" Create win 1003 on Grid 6, enter it
let winnr = call nvim_open_win(0, v:true, { 'width': 10, 'height': 10, 'focusable': v:true, 'external': v:true })
call nvim_command("edit buffer_for_win_" . winnr)

" Enter insert mode, add 'a' to buffer 'buffer_for_win_1003' on Grid 6
call nvim_input("aa")
" Click on Grid 5, expect cursor to me moved there (it isn't!)
call nvim_input_mouse("left", "press", "", 5, 1, 1)
```

### Actual behaviour
\           | set mouse=a  | set mouse=
------------|--------------|------------------
normal mode | cursor moved | cursor moved
insert mode | cursor moved | cursor not moved

### Expected behaviour
Either the cursor should not move in normal mode when `set mouse=` or the cursor should move in insert mode when `set mouse=`.

Reproducing this is a lot of work so I don't expect you to do it nor investigate this issue - I'll do this myself. However a decision needs to be made about what behavior neovim should have.

In #11372 @justinmk says he would prefer UIs to keep track of whether the mouse is disabled and not make nvim_input_mouse() calls if it is. In this scenario, it would make sense for the cursor to be moved in insert mode even when `set mouse=`.

However, the docs say that "UIs may ignore [mouse_on/off] and always send mouse input, because 'mouse' decides the behavior of nvim_input() implicitly". In this case, it would make sense for the cursor not to move in normal mode when `set mouse=`.

Either behavior is fine with me :).

**Comment by justinmk** [comment]
> When connecting to Neovim, GUIs do not receive a mouse_on/mouse_off event

Fixed in #11455 , so UIs are unblocked at least. 

> However, the docs say that "UIs may ignore [mouse_on/off] and always send mouse input, because 'mouse' decides the behavior of nvim_input() implicitly". In this case, it would make sense for the cursor not to move in normal mode when `set mouse=`.

Indeed, that was written before `nvim_input_mouse` existed. For consistency, it probably makes sense to treat `nvim_input_mouse` the same as `nvim_input`.

**Comment by bfredl** [comment]
Is this really an issue, like at all? The point of the `set mouse` option was for the TUI where nvim:s use of the mouse **actively inhibits**  the terminal:s own use of the mouse. Any GUI/embedding which has an analogous concern (like embedding nvim within a browser or editor with own mouse behviour) can use the same `mouse_on`/`mouse_off` events. The use of set 'mouse' to force the GUI mouse to *do nothing useful* sounds like inherited cargo cult behaviour, not anything anyone would want in a design from first principles. Not to mention, you can just remap mouse events to `<nop>` or whatever which is _much_ more fine-grained and problematically controllable than a global disable flag. 

Also the default of `set mouse=''` does not make sense for GUI if we were to _force_ UI:s to follow it. Keep trusting the GUI to know what it is doing sounds simpler to me than trying to "auto detect" a non-terminal UI to dynamically change the default. (to emulate gvim more directly)

**Comment by glacambre** [comment]
>Is this really an issue, like at all?

I would consider inconsistent behavior an issue, yes. It really doesn't make sense to me to have neovim react to mouse input in normal mode but not in insert mode.

**Comment by bfredl** [comment]
hmm, I agree, I missed that one sentence :D I just deleting `mouse_has` outside of mouse.c should be safe, this code was never needed in vim to start with so it is pretty inconsistent and arbitrary where it is checked.
