### ISSUE TITLE
paste gets stuck with certain data on macOS

### ISSUE THREAD

**Issue by dm1try** [neovim/neovim#11699]
- `NVIM v0.5.0-305-g29b1a4761`:
- `vim -u DEFAULTS` (version: ) yes
- Operating system/version: macOS Catalina 10.15.3 Beta (19D49f)
- Terminal name/version: kitty/terminal

[test.txt](https://github.com/neovim/neovim/files/4048827/test.txt)
### Steps to reproduce using `nvim -u NORC`
- copy content of [test.txt](https://github.com/neovim/neovim/files/4048827/test.txt) to system clipboard
- insert using Cmd-V

### Actual behaviour
escape sequences are printed instead of normal text, input is broken(no way for leaving input mode)
<img width="576" alt="Screen Shot 2020-01-11 at 04 36 13" src="https://user-images.githubusercontent.com/486807/72196831-1abcaf00-342c-11ea-87b5-685577334fae.png">

**Comment by justinmk** [comment]
confirmed at 462ee281b779 on macOS. Not on Linux, depends on buffer sizes. Thanks for the test data, that will help a lot.

**Comment by erw7** [comment]
I think this problem occurs because `handle_bracketed_paste()` does not properly handle incomplete sequences . We can reliably reproduce this problem using `tmux` in the following ways:

```
# Copy 4083-4087 bytes of data to the clipboard.
> win32yank -o --lf | tmux load-buffer -
> win32ynak -o --lf | wc
     41      41    4087
> tmux bin-key -T prefix ] paste-buffer -p
> nvim -u NORC
i
prefix+]
```

When I checked the contents of the buffer with `gdb`, it was as follows.

```
(gdb) p input->read_stream.buffer.size
$1 = 4095
(gdb) p input->read_stream.buffer.read_ptr[4093]
$2 = 27 '\033'
(gdb) p input->read_stream.buffer.read_ptr[4094]
$3 = 91 '['
(gdb) continue
(gdb) p input->read_stream.buffer.size
$4 = 4
(gdb) p input->read_stream.buffer.read_ptr[0]
$5 = 50 '2'
(gdb) p input->read_stream.buffer.read_ptr[1]
$6 = 48 '0'
(gdb) p input->read_stream.buffer.read_ptr[2]
$7 = 49 '1'
(gdb) p input->read_stream.buffer.read_ptr[3]
$8 = 126 '~
```

Bracketed Paste Mode end sequence `"\ x1b[201~"` is divided into `"\x1b["` and `"201~"`. `handle_bracketed_paste()` does not recognize this as a termination sequence.

#11393 probably doesn't happen because `handle_background_color()` doesn't handle incomplete sequences properly for similar reasons?

**Comment by dm1try** [comment]
for `handle_bracketed_paste` the fix looks easy, but I'm not sure about a general solution.
@justinmk do you already have a plan for this issue?

**Comment by erw7** [comment]
I tried to fix it in #12004. I tried using https://github.com/neovim/neovim/issues/11699#issuecomment-596472437 method and the problem seems to be fixed. However, it seems to dump core in the test on CI.

**Comment by themadsens** [comment]
Hooray! good job 👍 
Can we *please* have this scheduled for the next maintenance release? Seems to be part of 0.5 right now.

**Comment by azamuddin** [comment]
I'm still getting this issue today on MacOS Mojave, Iterm2, Tmux

```
NVIM v0.5.0-ce70edb
Build type: Release
LuaJIT 2.0.5
```

**Comment by dm1try** [comment]
@azamuddin it looks like your version is outdated.
