### ISSUE TITLE
:argedit of file in argument list -- behaviour has changed

### ISSUE THREAD

**Issue by hardenedapple** [neovim/neovim#11705]
### Steps to reproduce using `nvim -u NONE`

```
nvim -u NONE a.txt b.txt
:echo argv()
:argedit b.txt
:echo argv()
```

### Actual behaviour
Argument list originally contained `['a.txt', 'b.txt']`
Now contains `['a.txt', 'b.txt', 'b.txt']`

### Expected behaviour
Should contain  `['a.txt', 'b.txt']` both times.

This would match the documentation of `argedit` that says:
`When {name} already exists in the argument list, this entry is edited.`
			
## Behaviour introduced in bbdb074 (vim-patch:8.0.0721)
Seems that commit introduced a new feature that `:argedit` can add multiple
files to the argument list at once.

This is done by passing the arguments to `do_arglist` with the `AL_ADD` flag.
That essentially does the same as `:argadd`.

`:argadd` documentation says `There is no check for duplicates, it is possible
to add a file to the argument list twice`, while `:argedit` documentation says
`When {name} already exists in the argument list, this entry is edited.`

Previously the behaviour of `:argedit` was to switch to the relevant argument
without adding a duplicate to the argument list.

(N.B -- mainly for extra cross-reference search terms -- the plugin `vimfindsme` relies on the previous behaviour of argedit for :VFMArgument)

**Comment by glepnir** [comment]
this work as expect and doc had updated.
