### ISSUE TITLE
After upgrading Neovim, "gg" doesn't go to the beginning of line 1

### ISSUE THREAD

**Issue by daveyarwood** [neovim/neovim#11719]
- `nvim --version`: NVIM v0.5.0-dev
- `vim -u DEFAULTS` (version: ) behaves differently? NVIM v0.5.0-dev
- Operating system/version: Ubuntu 16.04
- Terminal name/version: Roxterm
- `$TERM`: xterm

```
$ apt-cache policy neovim
neovim:
  Installed: 0.5.0+ubuntu1+git202001142018-3d1531a-00e710e-8b2f2dc~ubuntu16.04.1
  Candidate: 0.5.0+ubuntu1+git202001142018-3d1531a-00e710e-8b2f2dc~ubuntu16.04.1
  Version table:
 *** 0.5.0+ubuntu1+git202001142018-3d1531a-00e710e-8b2f2dc~ubuntu16.04.1 500
        500 http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

:e /tmp/foo.txt

i

hello world<CR><CR>hello

<ESC>gg
```

### Actual behaviour

The cursor lands on the first line, but remains in the same column, i.e. it lands on the `o` in `hello world` on the first line.

### Expected behaviour

The cursor lands on the first character of the first line.

**Comment by daveyarwood** [comment]
I don't recall what the standard behavior of `G` is, but I'm also seeing that `G` puts you on the last line, in the same column instead of e.g. on the first character or last character.

**Comment by daveyarwood** [comment]
I noticed that the behavior changed because I wrote a plugin that does `ggvG$` to select the entire contents of the buffer (granted, there is probably a better way to do this, and I was able to push a work around by changing `gg` to `gg0`), and I noticed that only part of line 1 was being selected, so I typed `gg` and I noticed that it was just moving the cursor to line 1 on the same column, instead of moving the cursor to line 1, column 1 like it's always done.

**Comment by daveyarwood** [comment]
Someone just brought `:h startofline` to my attention:

```
			   *'startofline'* *'sol'* *'nostartofline'* *'nosol'*
'startofline' 'sol'	boolean	(default off)
			global
	When "on" the commands listed below move the cursor to the first
	non-blank of the line.  When off the cursor is kept in the same column
	(if possible).  This applies to the commands: CTRL-D, CTRL-U, CTRL-B,
	CTRL-F, "G", "H", "M", "L", gg, and to the commands "d", "<<" and ">>"
	with a linewise operator, with "%" with a count and to buffer changing
	commands (CTRL-^, :bnext, :bNext, etc.).  Also for an Ex command that
	only has a line number, e.g., ":25" or ":+".
	In case of buffer changing commands the cursor is placed at the column
	where it was the last time the buffer was edited.
```

I've never had that set in my vimrc, as far as I'm aware. Is it possible that Neovim used to default this option to `on`, and now the default is `off`, leading to the change in behavior?

**Comment by teto** [comment]
Yes. I plead guilty: https://github.com/neovim/neovim/commit/3aa95ef27eb8817bc2ceddb6caf2b209e00a5e8d

**Comment by teto** [comment]
@justinmk should I mention it on https://github.com/neovim/neovim/wiki/Following-HEAD ?

**Comment by daveyarwood** [comment]
A consequence of using a different `startofline` default than Vim is that plugin authors will need to account for the difference, or else their plugins might not work in Neovim. Part of the functionality of my plugin broke, for example.

**Comment by teto** [comment]
I don't think the change is especially worth fighting for but what about vim users setting `nostartofline` ? Plugins are better off not assuming anything about startofline and explicilty go to the beginning of line anyway.

**Comment by daveyarwood** [comment]
That's a good point -- I forgot about that best-practice when you're writing a Vim plugin.

**Comment by teto** [comment]
Feel free to reopen if you feel I've aggressively closed it.

**Comment by daveyarwood** [comment]
Closing this issue was the right call. I wasn't aware of `startofline`. It seems like if Neovim users really want a more Vim-like experience out of the box, they could identify all the defaults that are different in Neovim and explicitly set them to the Vim defaults.

If there isn't already a comprehensive list of settings that Neovim uses different defaults for compared to Vim, I think that would be helpful for Vim users looking to migrate without surprises.

**Comment by teto** [comment]
we do maintain such a list: `:h vim-differences` and `:h nvim-defaults` . Accessible https://neovim.io/doc/user/vim_diff.html for instance.
