### ISSUE TITLE
ffi in functional tests ?

### ISSUE THREAD

**Issue by teto** [neovim/neovim#11717]
I am trying to write a testsuite to check the robustness of filechange detection and eventually improve it: https://github.com/neovim/neovim/issues/1380
I've added some ffi code in the functionaltests, that seems to have none so far.
I manage to run my functionaltest with ffi by:
- running the unittests first to buil libnvim.so
- using itp() instead of it() to run the tests in another process (else the infra complains).
- using io:stderr.write() to log some messages

I wondered if it's fine to continue with this approach ? and maybe improve it

**Comment by bfredl** [comment]
What is the FFI for? do you have some WIP code to show? In our infrastructure, "unit test" means ffi-based test and "functional test" means RPC based test, is the issue here that you need both FFI and RPC in the same test?

**Comment by justinmk** [comment]
No, let's not do this. Currently there's a clear separation. Making things less clear isn't worth it. If you _really_ need FFI use a unit test. Most likely, FFI isn't needed. If you're trying to check an internal function, consider exposing it as an API function?
