### ISSUE TITLE
highlight after EOL/nontext

### ISSUE THREAD

**Issue by pwntester** [neovim/neovim#11711]
As commented in gitter and related with the new virtual text modes (eg: [right aligned](https://github.com/neovim/neovim/issues/11634)), it would be desireable to be able to highlight entire lines (including "text" after EOL). A use-case would be highlight Markdown fenced code blocks. It is possible to do it now using a regular hl such as `mkdCode` in `plasticboy/vim-markdown`, plus using a virtual text filled with spaces and using the same hl. Problem with this approach is that virtual text starts one cell after EOL, so there is a non-highlighted cell. A possible solution is to add an option to `nvim_buf_set_virtual_text` so that this additional cell is part of the virtual text. @bfredl  also commented that it may be better to have an option to change full-line highlight.

**Comment by zeertzjq** [comment]
There is now `line_hl_group` in `nvim_buf_set_extmark`.
