### ISSUE TITLE
LSP: Support for window/showMessageRequest

### ISSUE THREAD

**Issue by ckipp01** [neovim/neovim#11710]
For some LSP servers, like [Metals](https://github.com/scalameta/metals), having support for `showMessageRequest` is quite important. For example, in Metals, a `showMessageRequest` is what kicks off a build being imported. Without that happening, there is very little the server is able to help you with.

More info on the actual spec can be found [here in the lsp spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#window_showMessageRequest).

An actual request in the wild will look something like so:

```json
[Trace - 00:55:59 PM] Sending request 'window/showMessageRequest - (2)'
Params: {
  "actions": [
    {
      "title": "Import build"
    },
    {
      "title": "Not now"
    },
    {
      "title": "Don\u0027t show again"
    }
  ],
  "type": 3,
  "message": "New Mill workspace detected, would you like to import the build?"
}
```
And here is a quick look at how it's looks in other Vim LSP clients.

<img width="533" alt="Screenshot 2020-01-13 at 13 03 55" src="https://user-images.githubusercontent.com/13974112/72254723-2fa06a80-3605-11ea-9bc7-9ec04ed2b458.png">

**Comment by ckipp01** [comment]
I just came across another use case for this, which may throw people off. For example in [Metals](https://scalameta.org/metals/) in order to respond to a format request a `.scalafmt` file must be present. If not, we offer to create one for the user like so:

```json
[Trace - 11:11:33 AM] Sending request 'window/showMessageRequest - (4)'
Params: {
  "actions": [
    {
      "title": "Create .scalafmt.conf"
    },
    {
      "title": "Not now"
    }
  ],
  "type": 1,
  "message": "Unable to format since this workspace has no .scalafmt.conf file. To fix this problem, create an empty .scalafmt.conf and try again."
}
```
Then since this isn't handled, the user is met with the following:

```
Error executing vim.schedule lua callback: ...EAD-250e4e6/share/nvim/runtime/lua/vim/lsp/callbacks.lua:
202: RPC[Error] code_name = MethodNotFound, message = "MethodNotFound"
```

I think at first a user might expect that the formatting command is broken, which isn't actually the case.

**Comment by ckipp01** [comment]
Closed with https://github.com/neovim/neovim/pull/13641

@mjlbach you're a machine!

**Comment by mjlbach** [comment]
Whoops, sorry I completely missed this issue! The motivation was actually several crashing node language servers 😆

**Comment by ckipp01** [comment]
> Whoops, sorry I completely missed this issue! The motivation was actually several crashing node language servers 😆

ha, I'm glad I saw this. I have a very crude version of it in nvim-metals since we make heavy use of it, and I was just starting to port it over when I realized it was already done.

**Comment by mjlbach** [comment]
Just to be clear, you'll still have to implement custom handling for handlers that aren't supported yet (like $browser). Let me know if there are any issues!

**Comment by ckipp01** [comment]
🤔 I'll need to dig in a bit since it seems to not send anything to the server given this:

```
[Trace - 00:24:13 PM] Sending request 'window/showMessageRequest - (2)'
Params: {
  "actions": [
    {
      "title": "Import build"
    },
    {
      "title": "Not now"
    },
    {
      "title": "Don\u0027t show again"
    }
  ],
  "type": 3,
  "message": "New sbt workspace detected, would you like to import the build?"
}
```

**Comment by mjlbach** [comment]
You mean the inputlist choice isn't being returned to the server on selection of 1, 2, or 3?

**Comment by ckipp01** [comment]
> You mean the inputlist choice isn't being returned to the server on selection of 1, 2, or 3?

correct. After a selection is made, nothing gets sent.

Here's an example:

![2021-01-03 12 29 43](https://user-images.githubusercontent.com/13974112/103477464-6d227880-4dbf-11eb-9f53-77ede7c6f22e.gif)

**Comment by mjlbach** [comment]
Is this on metals master? I'll try to reproduce and fix it.

**Comment by ckipp01** [comment]
> Is this on metals/nvim-metals master? I'll try to reproduce and fix it. I only tested with the vuels and fake rpc server and things seemed to work fine.

yup, but you may need to install a few things, so no worries if you don't want to go through the hassle. I'll try to dig in a bit later today to see if I can figure out what's going on. However, if you do want to try, these are the steps you can follow:

- Install [coursier](https://get-coursier.io/docs/cli-installation) and make sure it's on your path
- Install [nvim-metals](https://github.com/scalameta/nvim-metals)
- Do a `:MetalsInstall`
- clone git@github.com:ckipp01/metals-minimal-sbt.git
- open `build.sbt`
- See prompt

**Comment by mjlbach** [comment]
Hmm, works for me.
```
[ DEBUG ] 2021-01-03T03:41:24-0800 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:500 ]      "server_request: callback result"       {  result = {    title = {      title = "Im
port build"    }  },  status = true}
[ DEBUG ] 2021-01-03T03:41:24-0800 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]      "rpc.send.payload"      {  id = "1",  jsonrpc = "2.0",  result = {    title = {      title = "Import build"    }  }}
[ DEBUG ] 2021-01-03T03:41:24-0800 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]      "decoded"       {  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = "2021.01.03 03:41:21 INFO  Started Metals http server at http://127.0.0.1:5031",    type = 4  }}
[ DEBUG ] 2021-01-03T03:41:24-0800 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:487 ] "notification"   "window/logMessage"     {  message = "2021.01.03 03:41:21 INFO  Started Metals http server at http://127.0.0.1:5031",  type = 4}
[ DEBUG ] 2021-01-03T03:41:24-0800 ] /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:397 ] "default_handler"       "window/logMessage"     {  client_id = 1,  params = {    message = "2021.01.03 03:41:21 INFO  Started Metals http server at http://127.0.0.1:5031",    type = 4  }}
[ DEBUG ] 2021-01-03T03:41:24-0800 ] /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:371 ] "2021.01.03 03:41:21 INFO  Started Metals http server at http://127.0.0.1:5031"
[ DEBUG ] 2021-01-03T03:41:24-0800 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]      "decoded"       {  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = "2021.01.03 03:41:24 ERROR Unexpected error initializing server\norg.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponseIssues(RemoteEndpoint.java:358)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handle(RemoteEndpoint.java:317)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:198)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)\n\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)\n\tat java.lang.Thread.run(Thread.java:832)\n",    type = 4  }}
```

**Comment by ckipp01** [comment]
ahhh I think  there is duplicate titles and that's why ` result = {    title = {      title = "Import build"    }  }}`

**Comment by mjlbach** [comment]
Yep, I see it now. Will fix.
