### ISSUE TITLE
option to disable terminal width dependent window title shortening

### ISSUE THREAD

**Issue by wis** [neovim/neovim#11728]
- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
- `vim -u DEFAULTS` (version: ) behaves differently? Yes, because of `set title`
- Operating system/version: `Linux archiver 5.4.11-arch1-1 #1 SMP PREEMPT Sun, 12 Jan 2020 12:15:27 +0000 x86_64 GNU/Linux`
- Terminal name/version: `kitty 0.15.1 created by Kovid Goyal`
- `$TERM`: `xterm-kitty`

### Steps to reproduce using `nvim -u NORC` 
open a terminal, resize it to cover most of the screen
`mkdir -p long-dir-name`
`touch ./long-dir-name/a-file-name-thats-long`
`nvim -u NORC -- ./long-dir-name/a-file-name-thats-long`
`:set title`
start resizing the terminal down and watch how the title starts shortening, beginning with the dir-name, then the file name and never the " - NVIM" part.
### Actual behaviour
window/terminal title gets shortened further the more you resize down the terminal window/decrease the terminal width
### Expected behaviour
have the same full window title regardless of terminal size

**Comment by wis** [comment]
it looks like there's no option to configure that, but you can set the title by setting `titlestring` (for more info see `:help titlestring`).

you can set `titlestring` on each buffer enter with:

`autocmd bufenter * let &titlestring = expand('%:p').' - NVIM'`

You use `autocmd bufenter *` to run something on each buffer enter, the asterisk means the file extension doesn't matter,

and use `let` with Vim options by prefixing the option name with a `&` (see `:help :let-option`) <sup>[\[1\]][1]</sup>

and use `expand('%:p')` to get the full path of the file opened in current buffer <sup>[\[2\]][2]</sup>


  [1]: https://vi.stackexchange.com/a/17983/20087
  [2]: https://vi.stackexchange.com/a/1885/20087

**Comment by justinmk** [comment]
Does not happen with macOS Terminal.app 

    nvim -u NORC +'set title'


 We didn't add any "title truncate" logic. One difference is that Nvim used "title stacking" so it's possible that kitty maybe is adjusting the title updates dynamically? Vim does not use title stacking by default (or maybe ever, I don't remember).

`titlestring` is a way to further control things, as you found.
