### ISSUE TITLE
Add Setting to Move Left After Tab Close

### ISSUE THREAD

**Issue by angelic-sedition** [neovim/neovim#1172]
This has been in the todo.txt for vim since 2012. I'd really like to have this patch added to neovim.

[This](https://groups.google.com/forum/#!topic/vim_dev/3fq0WJmlHeg) is the original discussion.

**Comment by fmoralesc** [comment]
With `TabClosed` from #1717, I implemented this as a small script:

~~~ vim
function! MoveToTabOnLeft()
    let curtab = tabpagenr()
    let tabonleft = curtab - 1
    exe tabonleft."tabnext"
endfunction

augroup tabonleft
    au!
    au TabClosed * call MoveToTabOnLeft()
augroup END
~~~

**Comment by justinmk** [comment]
@fmoralesc Speaking of which, if you rebase that PR I will merge it. Sorry for letting it slip.

**Comment by Pyrohh** [comment]
It seems like this isn't going to be implemented, at least according to the few comment here. Closing, but please reopen @justinmk if I missed something.

**Comment by justinmk** [comment]
:+1:  Thanks for going through these @Pyrohh

**Comment by Pyrohh** [comment]
So many issues... :sob:

**Comment by aemonge** [comment]
So is this feature officially killed ?

**Comment by justinmk** [comment]
@aemonge As discussed above, https://github.com/neovim/neovim/pull/1717 implemented `TabClose`.

**Comment by aemonge** [comment]
Ohhh Awesome !
