### ISSUE TITLE
Inexplicable ANSI escape sequences in output of jobs with pty on win32

### ISSUE THREAD

**Issue by tpope** [neovim/neovim#11726]
- `nvim --version`:
```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info 
```

- `vim -u DEFAULTS` (version: 8.2) behaves differently? yes
- Operating system/version: Windows 10
- Terminal name/version: Whatever the default terminal on Windows is called
- `$TERM`: blank

### Steps to reproduce using `nvim -u NORC`

```viml
let g:out = []
let g:job = jobstart('echo hi', {'pty': 1, 'on_stdout': { j, o, _ -> add(g:out, o) }})
call jobwait([g:job])
PP g:out
```

(`PP` is from scriptease.vim; you can use `:echo` but the display of strings is more cryptic.)

### Actual behaviour

```viml
[["\e[0mhi\e[0K\e[?25l\r", "\e[0K\e[?25h"], ['']]
```

### Expected behaviour

This is what is output on UNIX:

```
[["hi\r", ''], ['']]
```

This might boil down to a difference in how PTYs work across OSes, but the Vim equivalent -`job_start(['cmd', '/c', 'echo hi'], {'pty': 1, 'callback': { j, o -> add(g:out, o) }}` - behaves as I expect on both platforms.

I'm by no means 100% sure this isn't intended behavior, but it's perplexing, to say the least. Any ideas what's going on?

**Comment by bfredl** [comment]
I think this is because vim is using conpty while we are still using winpty (but we we plan to switch soon #11390).

**Comment by tpope** [comment]
This wasn't it, but it gave me the clue I needed to realize I misunderstood how the `'pty'` option works on Windows Vim. Specifically, how it does not work at all.  When I switch from `job_start()` to `term_start()`, I get nearly identical results to Neovim (there's an extra `\e[0K` at the beginning, for those keeping score):

```
\e[0m\e[0Khi\e[0K\e[?25l\r\n\e[0K\e[?25h
```

This is with winpty, which is apparently still the default. If I opt into conpty, I get a much bigger mess:

```
\e[2J\e[?25l\e[m\e[H\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\e[H\e]0;C:\\WINDOWS\\SYSTEM32\\cmd.exe\007\e[?25h\e[?25lhi\r\n\e[?25h
```

This makes me wish you'd keep winpty around as an option: 😬 

Thanks for your help.

**Comment by bfredl** [comment]
@tpope may I ask what you would be using this for? Your ongoing fugitive refactor I suppose? Is it some window command (like git subcommand) which only works when run inside a pty (as opposed to a pair of pipes)? 

For better and worse, I think pty job on windows always will be an approximation, and never match the bytes you will get on a true unix pty... The main usage of PTY of windows will be to display a `:terminal` window, where correctness comes from the visible end result and not the byte sequence.

**Comment by tpope** [comment]
Yes, for Fugitive. My big concern isn't outright breakages but behavior changes. For example, it's not documented, but `git merge` invokes the editor with the commit message if standard in and out are a terminal, but skips that step when not. I can work around things like this on a case by case basis, but there seems to be a lot of them, and I'm not sure how to track them all down.

I also was hoping to key off the invocation of `GIT_PAGER` to decide when to route output to a temp buffer rather than `:echo`. `GIT_PAGER` is only used if the process is attached to a terminal, and my reading of the Git source is that there's no way to override that.

I concur that using a terminal on Windows for these purposes is *probably* a lost cause, but I'm still a little sad to see the most viable option is going to be taken away.

**Comment by bfredl** [comment]
To be clear, the purpose of collecting output here is to display it to the user eventually, and not try to parse it or anything right? If there were a command like `:echo` except that it handled ANSI escapes, would it handle your usecase? (this is something we want to support, though not much concrete work on it yet)

**Comment by tpope** [comment]
Yes, that would handle it perfectly, at least with reasonable output and not something like that screen clearing mess that conpty initializes with.

**Comment by bfredl** [comment]
Yeah, we would need to deal with that also to re-implement 'guipty' in a reasonable fashion (i e only use as small region of the screen as possible).
