### ISSUE TITLE
Treeview `netrw` behaves weird with split

### ISSUE THREAD

**Issue by raichoo** [neovim/neovim#11727]
- `nvim --version`: NVIM v0.5.0-317-gfd89ad7bf
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: FreeBSD 12.1-STABLE r356251
- Terminal name/version: sakura version is 3.7.0
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
cd /tmp
mkdir foo
touch foo/foo
mkdir bar
touch bar/bar
nvim -u NORC
:let g:netrw_liststyle=3
:e foo | vs bar
```

### Actual behaviour

Both windows show the content of `bar`. The windows seem to point to the same buffer and when switching to another buffer this happens in both windows.

### Expected behaviour

With every other list style both windows act independently.

**Comment by justinmk** [comment]
>  `vim -u DEFAULTS` (version: ) behaves differently? No

Thanks for reporting, but if  it's the same behavior in Vim, it would be better to send the report to https://github.com/vim/vim . We don't maintain netrw and would sooner remove it entirely (after `gx` is replaced).

**Comment by raichoo** [comment]
I don't have Vim, so I'm not able to check it that issue exists there as well. Good to know that netrw is going to be removed.

**Comment by ashfinal** [comment]
Can be confirmed on Vim 8.2.0114, so it's likely an upstream problem.
