### ISSUE TITLE
[LSP] cmd_env being incorrectly validated as a function

### ISSUE THREAD

**Issue by KokaKiwi** [neovim/neovim#11720]
- `nvim --version`: v0.5.0-309-g05ea3c199
- `vim -u DEFAULTS` (version: v0.5.0-309-g05ea3c199) behaves differently? no
- Operating system/version: Arch Linux
- Terminal name/version: Konsole
- `$TERM`: fish

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:lua <<EOF
local lsp = require 'nvim_lsp'

lsp.rust_analyzer.setup { -- Can work with any other configured LSP client
  cmd_env = {
    RUST_LOG = 'debug',
  },
}
EOF
```

### Actual behaviour
Raise an error:
`E5108: Error executing lua shared.lua:423: cmd_env: expected function, got table`

Caused by: https://github.com/neovim/neovim/blob/8ba3354d74a8f90ded0997100bdbe845a8c5382f/runtime/lua/vim/lsp.lua#L156-L161
actually checking `cmd_env` is a function where a table should expected as per documentation and per implementation, passing a function makes it crash too because it tries to iterate over a function because it's supposed to be a table.

### Expected behaviour
Sould correctly pass `RUST_LOG=debug` env to the LSP server (here `ra_lsp_server`).

**Comment by teto** [comment]
fixed in 1eb0f5371ae8cee90b97f586a99505cfa5913504
