### ISSUE TITLE
Echo of a carriage return broken on win32

### ISSUE THREAD

**Issue by tpope** [neovim/neovim#11722]
- `nvim --version`:
```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info 
```

- `vim -u DEFAULTS` (version: 8.2) behaves differently? yes
- Operating system/version: Windows 10
- Terminal name/version: Whatever the default terminal on Windows is called
- `$TERM`: blank

### Steps to reproduce using `nvim -u NORC`

On Windows, invoke the following 2 commands.

```
:echo "line 1\r\nline 2"
:echo "abc\rz"
```

### Actual behaviour

```

line2
```

```
z
```

### Expected behaviour

This is what happens on UNIX Neovim, win32 terminal Vim, win32 GVim, UNIX terminal Vim, X11 GTK GVim, and MacVim:
 
```
line1
line2
```

```
zbc
```

**Comment by bfredl** [comment]
Confirmed. `\r` should only move the cursor to column zero, not clear the line. I will look into a fix.

**Comment by bfredl** [comment]
@tpope should be fixed on master now

**Comment by tpope** [comment]
Thanks!
