### ISSUE TITLE
A character string that is not related to completion will be entered in Scala.

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/neovim#11731]
- `nvim --version`: NVIM v0.5.0-316-g8fe0635e7
- Operating system/version: Mac / 10.15.2
- Terminal name/version: iTerm / 3.3.7
- `$TERM`: screen-256color

### Plugins and settings
```toml
[[plugins]]	
repo = 'Shougo/deoplete.nvim'	
hook_add = '''
call deoplete#custom#option('sources', {
    \ 'scala': ['lsp']
    \})

call deoplete#custom#source('_', 'converters', [
    \ 'converter_remove_paren',
    \ 'converter_remove_overlap',
    \ 'matcher_length',
    \ 'converter_truncate_abbr',
    \ 'converter_truncate_info',
    \ 'converter_truncate_menu',
    \ 'converter_auto_delimiter',
    \])

set completeopt-=preview

call deoplete#enable()	
'''

[[plugins]]
repo = 'Shougo/deoplete-lsp'	

[[plugins]]
repo = 'neovim/nvim-lsp'
hook_add = '''
    command! Scratch lua require'lsp'.makeScratch()
'''
```

`.config/nvim/lua/lsp.lua`
```lua
local M = {}

function M.makeScratch()
    local nvim_lsp = require'nvim_lsp'
    local configs = require'nvim_lsp/skeleton'

    -- Scala
    if not nvim_lsp.scala_lsp then
        configs.scala_lsp = {
            default_config = {
                cmd = {'metals-vim'};
                filetypes = {'scala', 'sbt'};
                root_dir = nvim_lsp.util.root_pattern('build.sbt');
        };
      }
    end

    nvim_lsp.scala_lsp.setup{}
end

return M
```

`.sbt/1.0/plugins/plugins.sbt`
```scala
resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.3.4")
```

## How to reproduce the problem from neovim startup

1. `$ sbt new nabezokodaikon/scala-basic.g8`
2. `name [My Something Project]: = issue-scala`
3. `$ cd issue-scala`
4. `$ nvim`
5. `e: src/main/scala/com/github/nabezokodaikon/Main.scala`
6. Type appropriately

### Actual behaviour
A character string that is not related to completion will be entered in Scala.
<img width="265" alt="スクリーンショット 2020-01-18 16 28 43" src="https://user-images.githubusercontent.com/3197942/72662638-bea9ea00-3a2c-11ea-9bbd-290e10a1846a.png">

### Expected behaviour
I want to remove unnecessary string completion in Scala.

**Comment by justinmk** [comment]
Thanks for reporting. This is likely a deoplete feature, read its docs. 

We don't have the resources to debug third party plugins such as deoplete.

**Comment by nabezokodaikon** [comment]
The same was true with deoplete disabled.
