### ISSUE TITLE
Ability to set number of lines to scroll on mouse wheel input

### ISSUE THREAD

**Issue by szbergeron** [neovim/neovim#11738]
- `nvim --version`: NVIM v0.5.0-317-gfd89ad7bf
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: linux, kernel 5.4.12
- Terminal name/version: alacritty 0.4.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:set mouse=a
:e ~/some_long_file
<move mousewheel one tick>
```

### Actual behaviour
Scroll amount is hardcoded/fixed at 3 lines

### Expected behaviour
Scroll amount should be configurable

### Use case
Touchpad scrolling, having the scroll quantum set to 1 allows for visually much smoother scrolling

### See-also
https://github.com/szbergeron/neovim, all visible sites where value is hardcoded changed to different value (should be made configurable for any final patch)

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/pull/10954  , it needs an owner. cc @qstrahl
