### ISSUE TITLE
LSP: vim.lsp.buf.definition() jumps to buffer not listed under :buffers

### ISSUE THREAD

**Issue by jonasrogert** [neovim/neovim#11743]
- `nvim --version`:
```
NVIM v0.5.0-324-gef379d4ea
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/lib/ccache/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/.../.cache/yay/neovim-git/src/neovim-git/build/config -I/home/.../.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/.../.cache/yay/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/.../.cache/yay/neovim-git/src/neovim-git/build/include
Compiled by ...

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently? 
**No**

- Operating system/version:
**Linux version 5.4.13-arch1-1**

- Terminal name/version:
**alacritty 0.3.3 (4dd327f0)**

- `$TERM`:
**xterm-256color**

### Steps to reproduce using `nvim -u NORC`

- nvim -u NORC main.rs
- :so minimalrc
- :set ft=rust
- Move to first hello
- :lua vim.lsp.buf.definition()
- :buffers

```
minimalrc

set runtimepath+=/home/jonas/Projects/nvim/nvim-lsp

lua << EOF
    local nvim_lsp = require'nvim_lsp'
    nvim_lsp.rls.setup{}
EOF

```

```
main.rs

mod hello;

fn main() {
    hello::hello();
}

```

```
hello.rs

pub fn hello() {
    println!("hello!");
}
```

### Actual behaviour
Opens up hello.rs in a strange buffer not displaying in :buffers.

In :buffers only main.rs is displayed if you have not edited the file it jumps too.

### Expected behaviour
A normal behaving buffer which shows up in :buffers

I am unsure what other effects this might have but for me i cant switch to prev/next buffer, jumplist works.

**Comment by justinmk** [comment]
"strange buffer" doesn't mean anything. What does `:ls!`  (note the "!") say exactly?

**Comment by jonasrogert** [comment]
Hi, I agree not a great formulated bug! Too make it work at all with NORC :). I finally switch from python to rust because virtualenvs.

This is what :ls! outputs:

```
:ls!
  1 #    "main.rs"                      line 1
  2u%a   "~/Projects/hello_cargo/src/hello.rs" line 1
```

**Comment by jonasrogert** [comment]
Is there anything i can do to make the issue better? I can still see the waiting on author tag.

**Comment by justinmk** [comment]
> Actual behaviour
> Opens up hello.rs in a strange buffer not displaying in :buffers.

Do you mean "window" here? The `:ls!` result you showed clearly indicates that your current buffer is listed there, and it is `hello.rs`. So I don't understand the problem.

Sounds like maybe you're confused about a popup window.

Without clearer steps that don't require me to install rust, this isn't actionable.

Note that the LSP support is written in Lua, so please feel free to send a PR if you find a problem.

**Comment by jonasrogert** [comment]
Firstly thanks for you patience! 

I understand, I expect the buffer to not be unlisted, I think goto definition should in my mind open a listed buffer (as with `:e`) at the specific line. Thats how most plugins and tools, that i have used, work. But great to know about the ! after ls or buf, makes it easier to switch back to it.

I don't know what a popup window is in neovim, is that a type of floating window or just an unlisted buffer?

I could try replicating it in any language which one would you prefer? Most of them would require some type of install, i guess but i will look into that.

I have started looking into the Lua code, so i will try.

**Comment by oars** [comment]
I think I've been hitting the same issue. Doing `:set buflisted` seems like a good option. Ideally I'd want to do:

```
nnoremap gd   :LspDefinition<cr>:set buflisted <CR>
```

But it seems `LspDefinition` is too slow, so `set buflisted` happens before the buffer I want to set as listed is opened.

**Comment by oars** [comment]
For reference, this happens after using `:bd` then trying to go to a definition in an unlisted buffer. `LspDefinition` doesn't change the buffer to be listed.
