### ISSUE TITLE
Buffer is not properly redrawn while Microsoft terminal resizing.

### ISSUE THREAD

**Issue by d9d6ka** [neovim/neovim#11741]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: 8.2.12) behaves differently? Yes
- Operating system/version: Windows 10 v1909
- Terminal name/version: Microsoft Terminal 0.8.10091.0

### Steps to reproduce using `nvim -u NORC`

1. Open Microsoft Terminal and start nvim (also `nvim -u NORC`).
2. Maximize or resize Terminal window.

### Actual behaviour

Buffer is not redrawn properly.
![screen](https://user-images.githubusercontent.com/29946047/72737806-5cc6bd00-3bb1-11ea-9ded-015b3bda0b3c.gif)

Vim 8.2.12 redraws buffer correctly.
![screen2](https://user-images.githubusercontent.com/29946047/72738158-09a13a00-3bb2-11ea-9947-3f1a4c25a912.gif)

### Expected behaviour

The behaviour similar to the behaviour of VIM.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS.

**Comment by d9d6ka** [comment]
Pre-release version 0.5.0 (commit ef379d4) works as expected, thanks!
