### ISSUE TITLE
snap: missing stable release in snap store

### ISSUE THREAD

**Issue by nietaki** [neovim/neovim#11758]
The [wiki states nigthly and stable versions are available in the snap store](https://github.com/neovim/neovim/wiki/Installing-Neovim#snap) from `candidate` and `edge` channels respectively.

The [snap store](https://snapcraft.io/nvim) offers what seem to be nightly builds in `beta` and `edge` channels

### Actual behaviour

The snap store offers a nightly/beta build in the `beta` channel

### Expected behaviour

The snap store offers stable version in the `candidate` channel

### Repro
```sh
$ sudo snap install --candidate nvim --classic
[sudo] password for nietaki: 
error: snap "nvim" is not available on candidate but is available to install on the following
       channels:

       beta       snap install --beta nvim
       edge       snap install --edge nvim

       Get more information with 'snap info nvim'.
```

**Comment by justinmk** [comment]
This will be fixed once 0.5 is release, since we now have snap automation.

**Comment by nietaki** [comment]
Thank you for the info, that makes a lot of sense

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/12815
