### ISSUE TITLE
'env' job option overrides variables incorrectly, broken for pty jobs

### ISSUE THREAD

**Issue by tpope** [neovim/neovim#11751]
- `nvim --version`: 
```
NVIM v0.5.0-314-g8ba3354d7
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/tpope/Code/vim/neovim/build/config -I/home/tpope/Code/vim/neovim/src -I/home/tpope/Code/vim/neovim/.deps/usr/include -I/usr/include -I/home/tpope/Code/vim/neovim/build/src/nvim/auto -I/home/tpope/Code/vim/neovim/build/include
Compiled by tpope@lancel

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: 8.2) behaves differently? Similar bug on Windows only: https://github.com/vim/vim/issues/5485
- Operating system/version: Ubuntu 19.10
- Terminal name/version: xterm
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
let $TESTVAR = '0'
let g:jobopts = {'stdout_buffered': 1, 'env': {'TESTVAR': '1'}}
call jobwait([jobstart('env', g:jobopts)])
echo join(filter(copy(g:jobopts.stdout), 'v:val =~# "^TESTVAR="'), "\n")
```

### Actual behaviour

```
TESTVAR=0
TESTVAR=1
```

Commands that use one value rather than list all values (e.g., `['sh', '-c', 'echo $TESTVAR']`) use the first value.

### Expected behaviour

```
TESTVAR=1
```

**Comment by tpope** [comment]
Related (should I open a new bug?): For jobs with `'pty': 1`, this feature appears to not work at all.

**Comment by bfredl** [comment]
One issue is fine but let's update the title.

**Comment by bfredl** [comment]
Seems we need to add the pty code separately for unix, winpty and conpty (but likely/hopefully winpty and conpty will interpret `wchar_t *env` the same way).

**Comment by justinmk** [comment]
cc @teto @jamessan

**Comment by teto** [comment]
seems like we have a fix for windows cf @erw7. I am looking into unix, I suspect replacing the execvp with execvpe solves it.

**Comment by jamessan** [comment]
> I am looking into unix, I suspect replacing the execvp with execvpe solves it.

The bigger issue is that there's environment manipulation that happens in the setup for spawning the pty job, so in the non-`'clear_env'` case we would need to re-massage the environment.

Using `execvpe()` or setting `environ = proc->env` before calling `execvp()` (like [libuv does](https://github.com/libuv/libuv/blob/7b28d36056d947e74e2c3347ee9bb04a1f5388c6/src/unix/process.c#L367-L369)) is pretty straight forward.

**Comment by teto** [comment]
`The bigger issue is that there's environment manipulation that happens in the setup for spawning the pty job, so in the non-'clear_env' case we would need to re-massage the environment.`

Yep saw that too. @jamessan was thinking maybe we could change https://github.com/neovim/neovim/blob/1ece24a329806778230034da73c25cc434b3bc9d/src/nvim/event/process.h#L26 to a dict_T and defer the conversion to `char **` only when required.

**Comment by tpope** [comment]
Can we mark [patch 8.2.0239](https://github.com/vim/vim/commit/355757aed6ae2ae5446882570d89f243e4805937) as included once this is resolved? Not the exact same thing but I do believe it is a proper subset.
