### ISSUE TITLE
Spurious warning in Python provider health check

### ISSUE THREAD

**Issue by dlukes** [neovim/neovim#11753]
`:help provider-python` states:

```
If you plan to use per-project virtualenvs often, you should assign one
virtualenv for Neovim and hard-code the interpreter path via
|g:python3_host_prog| (or |g:python_host_prog|) so that the "pynvim" package
is not required for each virtualenv.
```

Based on this, I assume running NVIM in a virtualenv other than the one I configured in `g:python3_host_prog` is a supported use case. However, doing so results in a warning when running `:checkhealth provider` (see below for details).

- `nvim --version`: NVIM v0.4.3 (from AppImage)
- Operating system/version: Linux (Solus)
- Terminal name/version: Tilix/1.9.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Set up a virtualenv to use as NVIM's Python 3 provider:

```
python3 -m venv nvim-venv
$PWD/nvim-venv/bin/pip3 install pynvim
```

You can now optionally try running `:checkhealth provider` -- at this point, everything should be fine with the Python 3 provider:

```
nvim -u NORC -c ":let g:python3_host_prog = '$PWD/nvim-venv/bin/python3' | :checkhealth provider"
```

However, the typical setup for Python development is that you're inside another virtualenv (not the one you use as the Python 3 provider for NVIM):

```
python3 -m venv project-venv
source project-venv/bin/activate
```

And now, if you rerun `:checkhealth provider` in the same way as before...

```
nvim -u NORC -c ":let g:python3_host_prog = '$PWD/nvim-venv/bin/python3' | :checkhealth provider"
```

### Actual behaviour

... you get a warning:

```
  - WARNING: $VIRTUAL_ENV exists but appears to be inactive. This could lead to unexpected results.
    - ADVICE:
      - If you are using Zsh, see: http://vi.stackexchange.com/a/7654
```

### Expected behaviour

There should be no warning :) I should be able to configure one virtualenv via `g:python3_host_prog` as NVIM's Python 3 provider for NVIM-internal stuff (remote plugins etc.), while at the same time having a different Python on my `PATH` from my current project's virtualenv, so that `:!python3` launches the correct Python with my project's dependencies.

Looking at the logic inside the [`s:check_python` function](https://github.com/neovim/neovim/blob/71ee46accfd235bad2b8460065100b31bb2d8165/runtime/autoload/health/provider.vim#L285), the warning is reported [when `python_exe` is not inside the virtualenv](https://github.com/neovim/neovim/blob/71ee46accfd235bad2b8460065100b31bb2d8165/runtime/autoload/health/provider.vim#L397-L403). But in this case, `python_exe` ends up being equal to `g:python3_host_prog`, instead of the Python inside the `project-venv` virtualenv. I'll try to investigate why and come up with a fix.

**Comment by justinmk** [comment]
> I assume running NVIM in a virtualenv other than the one I configured in `g:python3_host_prog` is a supported use case.

Yes, certainly. As long as `g:python3_host_prog` is working I don't see why `:checkhealth` should care about `$VIRTUAL_ENV` at all, but the warning was added for a reason...

Regarding your patch https://github.com/dlukes/neovim/commit/86e0c1c59c065f50c1221cfbd8451ee5224e8248

```diff
diff --git a/runtime/autoload/health/provider.vim b/runtime/autoload/health/provider.vim
index cc7d86d0c17..d361d7863e1 100644
--- a/runtime/autoload/health/provider.vim
+++ b/runtime/autoload/health/provider.vim
@@ -393,8 +393,10 @@ function! s:check_python(version) abort
   endif
 
   " Check if $VIRTUAL_ENV is valid.
-  if exists('$VIRTUAL_ENV') && !empty(python_exe)
-    if $VIRTUAL_ENV ==# matchstr(python_exe, '^\V'.$VIRTUAL_ENV)
+  let first_python_on_path = exepath('python')
+  if exists('$VIRTUAL_ENV') && !empty(first_python_on_path)
+    " this is simpler than doing matchstr and ==# but hopefully equivalent (?)
+    if first_python_on_path =~# '^\V'.$VIRTUAL_ENV
       call health#report_info('$VIRTUAL_ENV matches executable')
     else
       call health#report_warn(
```

That makes sense, except the message should be changed to `'$VIRTUAL_ENV is active'`.

Will you send a PR?

**Comment by dlukes** [comment]
> Will you send a PR?

I'd love to, but that's just the simplest way to silence the warning when the setup is legitimate, and it doesn't actually check what I believe the check is intended for. I'm working on a better patch and I'll explain why (and you may of course still decide you'd rather have the simple fix, that's up to you), but I need a little bit more time :)

**Comment by dlukes** [comment]
So here goes; apologies if it turns out to be a rather long post, but I think I've come across some other infelicities in `s:check_python`, so I'd like to discuss those as well for context :) Also apologies in advance if I get the tone wrong in some places in trying to get my point across, I don't have a whole lot of time to copy-edit. Please don't mistake it for condescension or entitlement, I definitely appreciate the ton of work you and others are putting into Neovim!

### High-level purpose of the virtualenv check

Maybe I'm mistaken, but judging by the [SO question](http://vi.stackexchange.com/a/7654) that's linked from the original warning, I think the purpose of the virtualenv check is to establish whether running Python from Neovim (as in `:!python`, not `:python`) will run the Python the user seems to be expecting based on their `$VIRTUAL_ENV` env var.

In other words, this check relates to the Python executable that the user wants to use while working on their Python project, **not** the executable that Neovim uses for remote plugin functionality etc. So it's conceptually unrelated to the Python **provider** check, and should very likely run as its own separate report, and not under the heading of "Python X provider" (e.g. if I'm in a Python 3 virtualenv, checking whether I can invoke `python2` as part of the "Python 2 provider" checks doesn't make sense). Strictly speaking, it doesn't even belong in `health/provider.vim`, since it has nothing to do with providers. But in practice, it's probably useful to keep all Python troubleshooting stuff in one place.

### Lower-level details

What do we need to check in order to make sure that invoking Python from Neovim will honor the virtualenv, if set? Two things:

1. The virtualenv Python must come first on Neovim's `$PATH`.
2. It must also come first on the `$PATH` of subshells launched from Neovim.

If the first check fails, it very likely means that the virtualenv wasn't properly activated even before launching Neovim, because Neovim should normally inherit its parent shell's `$PATH`, which should have been properly configured by `source path/to/virtualenv/bin/activate`. In theory, it could also fail because some startup files manipulate Neovim's `$PATH` (if that's possible?) and mess it up.

If it succeeds, it means that Neovim's `exepath` will locate the correct Python (inside the virtualenv).

If the second check fails, it's either for the same reason(s) as the first check, **or** it can be because launching a subshell from Neovim re-runs shell startup files and overrides the `$PATH`, even though Neovim itself has the correct one (this is the case covered by the SO question).

If it succeeds, it means that running `:!python` from Neovim should launch the correct one (inside the virtualenv).

### Suggested implementation

Please see ef75b693e98e0e843c7c651cd3a5f5032c447f63; the various messages are of course very much up for discussion, but they're trying to cover the cases described above. As argued above, the virtualenv check is factored out into its own separate report.

Here are some tests I tried to run in order to make sure the logic is right:

```sh
#!/usr/bin/env bash

# change this to fit your environment -- could be e.g. just
# /usr/bin/python3, and it should be able to import pynvim:
python_with_pynvim=$( pyenv which python3 )
cmd="let g:python3_host_prog = '$python_with_pynvim' | :checkhealth provider | :echo "
venv=$( mktemp -d )

>&2 echo "Setting up temporary virtualenv in $venv..."
python3 -m venv "$venv"

msg="'outside virtualenv -> virtualenv check shouldn''t even run'"
nvim -u NORC -c "$cmd$msg"

msg="'VIRTUAL_ENV points to non-existent virtualenv -> virtualenv warning'"
VIRTUAL_ENV=foo/bar nvim -u NORC -c "$cmd$msg"

msg="'VIRTUAL_ENV points to real virtualenv, but PATH is wrong -> virtualenv warning'"
VIRTUAL_ENV="$venv" nvim -u NORC -c "$cmd$msg"

source "$venv"/bin/activate
msg="'VIRTUAL_ENV is properly activated -> virtualenv check runs and reports OK'"
nvim -u NORC -c "$cmd$msg"

>&2 echo "Installing pynvim into $venv..."
pip install pynvim
msg='"VIRTUAL_ENV is properly activated and has pynvim; g:python3_host_prog not set\n-> this should issue a python provider warning (setup not optimal)\ncurrently however, no warning is issued and the Python executable is misreported\nit should be: "'
nvim -u NORC -c ":checkhealth provider | :echo $msg | :python3 import sys; print(sys.executable)"

>&2 echo "Removing temporary virtualenv in $venv..."
rm -rf "$venv"
```

Note that the last test should trigger a warning from `s:check_python` about suboptimal setup, because we have `pynvim` installed inside the virtualenv we're working in, which `s:check_python` frowns upon, because it likely means that we're repeatedly installing `pynvim` into each virtualenv we're using, instead of setting up a virtualenv with `pynvim` dedicated to Neovim and setting `g:python3_host_prog`.

However, no such warning is issued, because `s:check_python` mistakenly identifies the global Python executable (outside the virtualenv) as the provider, even though running `:python3 import sys; print(sys.executable)` clearly indicates that the Python **inside** the virtualenv is being used as the provider.

Which brings me to...

### `s:check_python` may be unnecessarily complicated

`s:check_python` starts by asking `provider#pythonx#Detect` about the Python provider:

https://github.com/neovim/neovim/blob/d3a9d75c0462fea7b00e639d1b324bcf08a8b02d/runtime/autoload/health/provider.vim#L304

However, even though `provider#pythonx#Detect` figures out the full path to the Python executable which will actually be used as provider, it then throws it away and returns just the basename as `pyname` here. So then `s:check_python` tries to figure out the full path on its own, in a much more complicated and error-prone manner, making mistakes along the way.

For instance, consider the following situation: let's say my global default Python is Python 3 installed via pyenv without the `pynvim` module. However, I've created a virtualenv, and inside it, I installed `pynvim`. If I run `:checkhealth provider` in a Neovim session inside this virtualenv, then I would expect to get the warning that my virtualenv is not set up optimally and that I should set up a separate one for Neovim (or possibly install `pynvim` globally, another acceptable alternative IMHO) and set `g:pythonx_host_prog`.

Instead, I currently get this:

```
- INFO: pyenv: Path: /Users/david/.local/pyenv/libexec/pyenv
- INFO: pyenv: Root: /Users/david/.local/pyenv
- INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
- WARNING: $VIRTUAL_ENV exists but appears to be inactive. This could lead to unexpected results.
  - ADVICE:
    - If you are using Zsh, see: http://vi.stackexchange.com/a/7654
- INFO: Executable: /Users/david/.local/pyenv/versions/3.8.1/bin/python3
- ERROR: Command error (job=6, exit code 1): `'/Users/david/.local/pyenv/versions/3.8.1/bin/python3' -c 'import sys; sys.path = list(filter(lambda x: x != "", sys.path)); import neovim; print(neovim.__file__)'` (in '/Users/david/tmp')
  stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>ModuleNotFoundError: No module named 'neovim'
- INFO: Python version: 3.8.1
- INFO: pynvim version: unable to load neovim Python module
- ERROR: pynvim is not installed.
  Error: unable to load neovim Python module
  - ADVICE:
    - Run in shell: pip3 install pynvim
```

Which is not even true, because if I try to use the `:python3` Neovim command, it works, and running `pip3 install pynvim` back in the shell (which is inside the virtualenv) will just tell me that it already is installed, so the advice is misleading. And again, as in the last test above, the wrong (global) Python executable is reported by the check (`INFO: Executable: /Users/david/.local/pyenv/versions/3.8.1/bin/python3`) instead of the one inside the virtualenv, which is the one actually used, as can be seen by running `:python3 import sys; print(sys.executable)`.

Maybe there are legitimate reasons for the full path detection logic in `s:check_python` being kept separate from `provider#pythonx#Detect`, and also being so complicated -- maybe it's trying to be super clever about detecting some special cases, or not raising errors in setups which are weird but functional (though the existence of an eager warning about suboptimal virtualenv setup would suggest otherwise). If so, it would probably be a good idea to at least improve variable names / add comments to the code, so that it's clearer what magic is being attempted, making it easier to fix it when the magic happens to be buggy.

Alternatively, why not just let `provider#pythonx#Detect` return the full path to the executable that can import `pynvim` and use that, instead of custom complicated logic? Environment troubleshooting code like this is super hard to test thoroughly, so having it be as simple as possible would make it easier to maintain... Not to mention not having duplicate implementations of the same thing which can yield conflicting results, and have the incorrect one be reported to the user as part of troubleshooting :)

As an example of complicated stuff that `s:check_python` tries to cover but IMHO shouldn't: I really don't think it should be Neovim's job to [detect broken pyenv installations](https://github.com/neovim/neovim/blob/d3a9d75c0462fea7b00e639d1b324bcf08a8b02d/runtime/autoload/health/provider.vim#L323-L358). It should just point out that trying to run Python results in something weird, and that the user should try doing so in their shell and investigate the errors that pop up.

### Post scriptum

Whew, that's it now :) I tried hard to replicate all of this multiple times in the correct environments to make sure these claims are correct (cf. the enclosed testing script). Nonetheless, I may have made mistakes along the way, or elided some relevant details. If any of this doesn't match your own observations, please let me know and I'll double and triple check to figure out why.

**Comment by dlukes** [comment]
One last remark: given what I've written in **Lower-level details** above, the "simple" fix in 86e0c1c59c065f50c1221cfbd8451ee5224e8248 is actually inadequate as-is: while it silences the spurious warning, it doesn't trigger it in legitimate situations because it just checks the first Python on Neovim's `$PATH` (via `exepath`) and doesn't check the first Python on the `$PATH` of subshells launched from Neovim.

**Comment by justinmk** [comment]
@dlukes thanks for your analysis! I need time to read it, but meanwhile send a PR and we'll just merge it. Since the existing check is somewhat incorrect it can't hurt much to try a different approach.

**Comment by dlukes** [comment]
OK will do :)
