### ISSUE TITLE
winhighlight does not change CursorLine

### ISSUE THREAD

**Issue by iamcco** [neovim/neovim#11778]
- `nvim --version`: NVIM v0.5.0-nightly-239-g71ee46acc
- Operating system/version: Mac OS 10.13.6
- Terminal name/version: kitty v0.14.6
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set cursorline
:set winhighlight=CursorLine:PmenuSel
```

### Actual behaviour

Cursor line does not look as PmenuSel

### Expected behaviour

Cursor line should look as PmenuSel

**Comment by justinmk** [comment]
seems related to `CursorLine`, not `PmenuSel`.
