### ISSUE TITLE
Python: vim module is imported magically in Vim but not NeoVim

### ISSUE THREAD

**Issue by puremourning** [neovim/neovim#11783]
- `nvim --version`: 

```
(nvim3) BenMBP:~ ben$ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently? YES
- Operating system/version: macOS Catalina (and others)
- Terminal name/version: iTerm2 (and others)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim --clean
:py3 print( vim )
```

### Actual behaviour

Traceback (`name vim is not defined`)

### Expected behaviour

`module< vim ... >`

Admittedly, the Vim documentation says `You need to import the vim module before using it: > :python import vim`, but that's ostensibly not true in the global scope. In vim `vim --clean` followed by `:py3 print( vim )` prints `module < vim ...>`.

**Comment by justinmk** [comment]
Thanks for reporting. We're not going to change this after so long, given `import vim` is quite a reasonable thing for scripts to do.

**Comment by justinmk** [comment]
From chat, it sounds like this was a recent change in Vim itself. So then we might as well change it too. Thought it's a really strange choice, since it could break existing scripts.

**Comment by bfredl** [comment]
> From chat, it sounds like this was a recent change in Vim itself. So then we might as well change it too. Thought it's a really strange choice, since it could break existing scripts.

How would it break existing scripts? Legacy python scripts do not have a private environment. pythonplugin2 must always be prepared that pythonplugin1 has loaded before, and run `import vim` already.

**Comment by justinmk** [comment]
addressed in https://github.com/neovim/pynvim/pull/430 but please wait for a `pyvnim` release.
