### ISSUE TITLE
.netrwhist stored in `XDG_CONFIG_HOME` instead of `XDG_DATA_HOME`

### ISSUE THREAD

**Issue by NilsIrl** [neovim/neovim#11791]
- `nvim --version`: NVIM v0.4.3

### Steps to reproduce using `nvim -u NORC`

Use netrw

### Actual behaviour

Netrw history is stored in `$XDG_CONFIG_HOME/nvim/.netrwhist`

### Expected behaviour

Netrw history is stored in `$XDG_DATA_HOME/nvim/.netrwhist`

**Comment by justinmk** [comment]
Feel free to send a PR. But generally we don't maintain netrw.

**Comment by janlazo** [comment]
See https://github.com/neovim/neovim/pull/13939.

Treating this as a duplicate of https://github.com/neovim/neovim/issues/12161 even though this was created earlier.
