### ISSUE TITLE
default: set 'fileignorecase' on macOS (WAS: cannot detect case sensitivity on apfs)

### ISSUE THREAD

**Issue by epheien** [neovim/neovim#11793]
- `nvim --version`: NVIM v0.5.0-317-gfd89ad7bf
- `vim -u DEFAULTS` (version: ) behaves differently? 
- Operating system/version: macOS 10.14.6
- Terminal name/version: ITerm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
eph@iMacPro ➜  tmp $ df -hT .
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/disk2s1   apfs  466G  389G   67G  86% /
eph@iMacPro ➜  tmp $ touch A.c a.c
eph@iMacPro ➜  tmp $ ll
total 0
-rw-r--r-- 1 eph staff 0  1 30 18:07 A.c
eph@iMacPro ➜  tmp $ nvim -u NORC
:e a<Tab>
```

### Actual behaviour
nothing
### Expected behaviour
expand completion like:
`:e A.c`

## Reason
In fact because the 'fic' option is not set automatically
And vim 8.2 is set correctly

**Comment by justinmk** [comment]
mentioning apfs implies that this is different than HFS...? And what does this shell command produce:

    ls A.*

On HFS that does not list the file, i.e., the shell is case-senstive. So it's not so clear what the "correct" behavior is on macOS. In any case you can just set the option if you want the other behavior.
