### ISSUE TITLE
use as scrollback pager in kitty terminal

### ISSUE THREAD

**Issue by Asheq** [neovim/neovim#11797]
<details><summary>nvim --version</summary>
<p>

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/config -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

</p>
</details>

- `vim -u DEFAULTS` behaves differently? no
- Operating system/version: macOS Mojave 10.14.6
- Terminal name/version: kitty terminal 10.14.6
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

- Make sure `~/.config/kitty/kitty.conf` has the following line:

```
scrollback_pager nvim -u NORC
```

- Open kitty terminal
- Enter a command, e.g., `echo hello`, to get some output on the terminal and into the scroll-back buffer.
- Press `ctrl+shift+h` to invoke the kitty scroll-back pager

### Actual behaviour

There is a flash on the screen, but neovim does not stay open to show the contents of the kitty scroll-back buffer.

### Expected behaviour

Neovim should open and display contents of the kitty scroll-back buffer.

#### In vim
In vim (version 8.2) this works (almost) as expected if kitty.conf includes:
```
scrollback_pager vim -u NORC -
```
![2020-01-31 16-26-42 2020-01-31 16_27_48](https://user-images.githubusercontent.com/4657140/73583383-aaabb280-4446-11ea-86f9-85017f534d8a.gif)

The only problem here is that the ANSI escape codes in the terminal clutter up the text. Ideally, vim should interpret the ANSI codes, hide them, and retain color/format of text (may be by using the built-in terminal?).

**Comment by blueyed** [comment]
> ```
> scrollback_pager nvim -u NORC
> ```

Try with `-` also, as with vim.
For handling ANSI escape code check https://github.com/norcalli/nvim-terminal.lua/.

**Comment by justinmk** [comment]
Can't think of a reason why this would not work, since it looks like kitty is just writing to stdin.

> Try with `-` also, as with vim.

Shouldn't be needed in Nvim.

> There is a flash on the screen, but neovim does not stay open

Does it exit with nonzero? I.e. check `echo $?` in the shell.

**Comment by Asheq** [comment]
Thanks Justin and Daniel,

> Try with - also, as with vim.

Adding the `-` at the end does not seem to help.

> Does it exit with nonzero? I.e. check echo $? in the shell.

`echo $?` returns 0.

Let me know if there is anything I can do to help with debugging, e.g. if there is a way
to create a log file.

Also, is there a way to start neovim such that the text from stdin is "read" into a terminal buffer so that the built-in terminal can automatically handle the ANSI escape codes (without using a plugin like [nvim-terminal.lua](https://github.com/norcalli/nvim-terminal.lua))?

**Comment by justinmk** [comment]
> if there is anything I can do to help with debugging, e.g. if there is a way
to create a log file.

Try adding `ELOG()` calls to `read_error_exit()` (and up the call chain) to see if/where it's getting called (or use `LOG_CALLSTACK` with a Debug build, but that only works on Linux).

> is there a way to start neovim such that the text from stdin is "read" into a terminal buffer

```
printf 'foo\nbar\nbaz\n' | nvim -
te cat
:call chansend(&channel, getbufline('#',1,'$') + ["\r"])
```

**Comment by dm1try** [comment]
maybe the flash was
![image](https://user-images.githubusercontent.com/486807/73601724-81d70a80-4577-11ea-8ecd-72643e6c006d.png)

**Comment by justinmk** [comment]
Nice, thanks @dm1try

**Comment by Asheq** [comment]
> ```
> :te cat -
> :call chansend(&channel, getbufline('#',1,'$') + ["\r"])
> ```

@justinmk Justin, I noticed that the result of this still sometimes contains some ANSI escape codes, with the escape character replaced with the literal text `^[` (an accent followed by a left square bracket).
![2020-02-02 14-59-43 2020-02-02 15_00_42](https://user-images.githubusercontent.com/4657140/73616825-1881e680-45cd-11ea-9750-6e85a2805fec.gif)

However, writing to a temporary file and cat-ing it works flawlessly as far as I can tell:
```
:write /tmp/kitty_scrollback_buffer
:te cat /tmp/kitty_scrollback_buffer
```

![2020-02-02 15-01-46 2020-02-02 15_02_43](https://user-images.githubusercontent.com/4657140/73616826-2172b800-45cd-11ea-810c-94819f2e2f2d.gif)

(Any idea what is going wrong with the first one?)

**Comment by Asheq** [comment]
> maybe the flash was
> ![image](https://user-images.githubusercontent.com/486807/73601724-81d70a80-4577-11ea-8ecd-72643e6c006d.png)
> 
> yep, `scrollback_pager /Users/dmitrydedov/neovim/bin/nvim -u NORC` helps.
> 
> <img alt="Screen Shot 2020-02-02 at 04 53 51" width="328" src="https://user-images.githubusercontent.com/486807/73601754-0aee4180-4578-11ea-9a57-1c3d6c3b65d0.png">
> 
> looks like some shell environment problem on kitty side

Thanks @dm1try. I'll open an issue in the kitty repo.
