### ISSUE TITLE
NeoVim stops file syntax highlight

### ISSUE THREAD

**Issue by breaked01** [neovim/neovim#11799]
Hello. I am so sorry if I wrote this "bug" in a wrong place, but I really do not know where I can to get an any info about my problem.

I have a successfully installed a NeoVim package from snap store in ubuntu and configured it for a comfortable web-ide. All just fine, when I starts nvim and work a full day all just fine. I am work directly on server side via SSH, no any GUI, at the end of the day I am not close anything, NeoVim and all my opened buffers are still runed on servers side. And next day in the morning when I try to continue my work - I got a problem, after opening a new files in NeoVim - the syntax highlight (PHP) stops working I see just a white text instead of any syntax highlight. If I restart nvim - all starts work fine, but this is a little bit uncomfortable, because all my opened buffers and other working environment from previous day just dropped... I use just a few plugins:
http://dpaste.com/0CNCNVF
But I have no any ideas where I can start a search in resolution of my problem and what can I do...
Can anyone maybe just tell me where I can start a problem resolving?

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
