### ISSUE TITLE
nvim_call_function cannot call dict functions

### ISSUE THREAD

**Issue by delphinus** [neovim/neovim#11800]
- `nvim --version`: NVIM v0.5.0-14a8b3b98
- ~`vim -u DEFAULTS` (version: ) behaves differently?~
- Operating system/version: macOS 10.14.6
- Terminal name/version: iTerm2 3.3.8beta5
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u vimrc`

```vim
" minimal vimrc
let g:foo = {}

function! g:foo.echo() dict
  echo 'Foo'
endfunction
```

```
nvim -u vimrc
```

### Actual behaviour

```vim
:call g:foo.echo()
" => Foo
:call nvim_eval('g:foo.echo()')
" => Foo
:call nvim_call_function('g:foo.echo', [])
" => E5555: API call: Vim:E117: Unknown function: g:foo.echo
```

### Expected behaviour

`nvim_call_function` succeeds.

**Comment by bfredl** [comment]
Try `nvim_call_dict_function`
