### ISSUE TITLE
Add an option for `fold-create-marker` to add the marker comments on their own lines

### ISSUE THREAD

**Issue by jrop** [neovim/neovim#11812]
Setup:

`set fdm=marker`

Buffer
```
1: let some_var = some.value.here();
2: let more_code = go.here();
```
Visually select both lines and `zf`.  This adds the markers as such:

```
1: let some_var = some.value.here(); // {{{
2: let more_code = go.here(); // }}}
```

What I want is to be able to set an option to add the comments on their own lines, and get the following result after `zf`:

```
1: // {{{
2: let some_var = some.value.here();
3: let more_code = go.here();
4: // }}}
```

Indeed, the given behavior is not unexpected.  Given the help text of `fold-create-marker`, this is working as advertised.  It would be nice to have an option for it to work as proposed, though.
```
:help fold-create-marker:
"zf" can be used to create a fold defined by markers.  Vim will insert the
markers for you .. The markers are appended to the end of the line.
```

**Comment by justinmk** [comment]
> Visually select both lines and `zf`. This adds the markers as such:

Always need exact steps. You mean you pressed `v`. Whereas if you press `V`, then you get linewise selection, which does what you want.

**Comment by jrop** [comment]
@justinmk I should have been more specific: I am in-fact already using `V`.  Linewise visual selection does not change the result for me (I have tried NeoVim 0.4.3, and NeoVim v0.5.0-356-gead61e5a5)

**Comment by justinmk** [comment]
Works for me.

**Comment by jrop** [comment]
@justinmk I attempted with `nvim --noplugins -u NORC`, ran `:set fdm=marker`, used `V` (linewise selection) to select some lines in a temp buffer (`:e some.c`), then created a fold with `zf`, and it still puts the fold markers at the end of the line (not on their own lines).
