### ISSUE TITLE
`toupper` output inconsistent with gU

### ISSUE THREAD

**Issue by fenuks** [neovim/neovim#11813]
- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: 8.2) behaves differently? No
- Operating system/version: Arch Linux
- Terminal name/version: Yakuake 3.0.5
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
`:h toupper()` reads that function works `just like applying gU to the string`. I was recently working with some German strings, and noticed that `toupper` (and `~` key) does not uppercase German sharp S character `ß`, while `gU` does (it turns `ß` into `SS` which is still accepted as valid, but [capital ẞ letter](https://en.wikipedia.org/wiki/Capital_%E1%BA%9E) was introduced some time ago to replace it, according to linked Wiki article). 

```
nvim -u NORC
:echo toupper('uppercase ß')
UPPERCASE ß
# applying gU to above string yields
UPPERCASE SS
# title key behaviour is the same as `tolower()` call, ß is untouched
```
For reference, nvim works correctly with new capital letter `ẞ`.

```
nvim -u NORC
:echo tolower('lowercase ẞ')
lowercase ß
# tilde key works as well
```

### Actual behaviour
gU on `ß` gives `SS`, while `echo toupper('ß')` returns `ß`.

### Expected behaviour
`toupper()` returns same string `gU` would, as stated in documentation. Possibly, `gU` should return new capital `ß` letter as it is now officially accepted, which has advantage that `gU$gu$` would revert to original string if it was written in lowercase, which is not the case when `ß` is converted to `SS`.

**Comment by justinmk** [comment]
>  `vim -u DEFAULTS` (version: ) behaves differently? No

Please report this to https://github.com/vim/vim/ and link to the issue from here. We are unlikely to spend time on this bug.

**Comment by fenuks** [comment]
Reported issue in vim/vim#5573.
