### ISSUE TITLE
Duplicate lines showing in buffer

### ISSUE THREAD

**Issue by fonnesbeck** [neovim/neovim#11810]
NeoVim version info:

NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include

Running on Debian 9 in xterm-265color

When I open files in NeoVim, I often see duplicate lines, as shown here (line 38):

![image](https://user-images.githubusercontent.com/81476/73665083-2172c680-4666-11ea-95a6-b5d8524418c8.png)

It often goes away by scrolling up and down, but just as often is replaced by another duplicate line.

**Comment by justinmk** [comment]
> Running on Debian 9 in xterm-265color

xterm-265color is TERM env var, whereas we also need to know your actual terminal.

Anyways I think this was a BCE issue that was fixed later. Try  the development version: the [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS.
