### ISSUE TITLE
snap: Enable arm64,armhf,i386 builds using remote-builds

### ISSUE THREAD

**Issue by hurricanehrndz** [neovim/neovim#11817]
We should support all supported architectures by snapcraft.  I will look into adding this.

Reference:
https://github.com/solvespace/solvespace/commit/d5351c48e3460550ebcbaa810ce45063c1dbea32

**Comment by hurricanehrndz** [comment]
@justinmk 

I was thinking perhaps we can do stable release if we move to github workflows for the snap. It would be a combination of the following two workflows:

https://github.com/Spotifyd/spotifyd/blob/master/.github/workflows/cd.yml
https://github.com/hurricanehrndz/spotify-tui/blob/master/.github/workflows/snap.yml

I would like your thoughts.

**Comment by justinmk** [comment]
@hurricanehrndz what does github workflow have to do with stable release? We aren't ready to declare a stable release.

**Comment by hurricanehrndz** [comment]
@justinmk 

I remember us discussing that in order to get tag releases working for the snap, that you would need to migrate the workflows from the publishing repository. I am just concern that step might never be taken because of how much work I suspect it would required. I thought perhaps this might be means to publish from tags without having to migrate all CD from the publishing repository.

It was just a thought and yes slightly off topic.

I am still working away on the rest of this issue. I have arm64 builds working now. Still trying to resolve an issue with armv7.

**Comment by WillNilges** [comment]
Sorry if i'm necrobumping this, but I'd really like to see an `armhf` snap of this. If you need help, I'd be down to look into it with you after I finish up another project of mine.

**Comment by hurricanehrndz** [comment]
Thanks for the reminder. I will try and get this done in the next couple of
weeks.

**Comment by Username404-59** [comment]
So this will add support for armhf?
I would really like to install neovim on a pinebook pro!

**Comment by hurricanehrndz** [comment]
Yes, I do it by June 16.

**Comment by hurricanehrndz** [comment]
Progress Update: initial builds are done. I have enclosed them.

[aarch64](https://transfer.sh/iQopK/nvim_v0.5.0-559-ga0a84fc9e-dirty_arm64.snap)
[aarch64 buildlog](https://paste.ubuntu.com/p/mVSrKJNvdH/)
[armhf](https://transfer.sh/zJofw/nvim_v0.5.0-559-ga0a84fc9e-dirty_armhf.snap)
[armhf buildlog](https://paste.ubuntu.com/p/z63R9z39Cd/)

I will try and formulate a pull request to tie the arm builds into TravisCI. This should happen within the next couple of days.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/12815
