### ISSUE TITLE
:terminal "set scrollback=x" is ignored if reset before redraw

### ISSUE THREAD

**Issue by I60R** [neovim/neovim#11811]
- `nvim --version`: 0.4.3, also tested on v0.5.0-353-g3051342f9
- `vim -u DEFAULTS` (version: ) behaves differently? - no
- Operating system/version: Manjaro Linux / 18.1.5
- Terminal name/version: alacritty 0.4.1-dev (d774c7f3)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:term
a
for i in $(seq 0 1000); echo $i<CR>
\<C-\>\<C-n>:setl scrollback=0<CR>
gg 
```

### Actual behaviour

You scroll to the line 1 

### Expected behaviour

You scroll to the first line that's visible on screen (e.g. 900) and no further because scrollback is yet disabled and lines from it should be gone.

### What is the use case

I'm trying to clear :term buffer as it was shown in this [comment](https://github.com/neovim/neovim/issues/2637#issuecomment-282482441)

### Additional information

`setl scrollback=1` somehow will work after entering and exiting insert mode

**Comment by justinmk** [comment]
`:help scrollback` explicitly says minimum is 1. Not zero.

> `setl scrollback=1` somehow will work after entering and exiting insert mode

Correct. That is a known issue, just a matter of adding some extra work in options.c to force `terminal.c` to flush scrollback.

But that is a different issue than `scrollback=0`, which is simply not supported. So I have re-titled this issue.

**Comment by I60R** [comment]
>But that is a different issue than scrollback=0, which is simply not supported

Could it be also a feature request for `scrollback=0`?

I see many reasons why it should be implemented:

1) Allows to clear screen completely unlike `scrollback=1` which preserves single line
2) Provides a straightforward way to disable scrollback
3) Users will not be surprised by the fact that `scrollback=0` is silently ignored

**Comment by I60R** [comment]
For the context, there are some viml snippets on the internet which shows `scrollback` taking 0 and even negative values, so it's very likely that users will assume `scrollback=0` simply working without reading any documentation (at least it already happened for me)

**Comment by I60R** [comment]
Moreover, I have `set scrollback=-1` in my config file and I have a program which rely on it, and it still works as previously without issuing any deprecation warnings etc.

**Comment by gysddn** [comment]
> But that is a different issue than scrollback=0, which is simply not supported. 

Can we add support? Is there a known issue with scrollback being 0?

> Correct. That is a known issue, just a matter of adding some extra work in options.c to force terminal.c to flush scrollback.

I can get in on that. I don't think anyone else started.

**Comment by ddickstein** [comment]
Should a separate issue be created to continue the `scrollback=0` discussion?

**Comment by justinmk** [comment]
> continue the `scrollback=0` discussion?

I have zero interest in that, it's a nitpick. Unless it can be done without complicating the implementation.
