### ISSUE TITLE
doc: help.txt links to missing pi_matchit.txt

### ISSUE THREAD

**Issue by ramiro** [neovim/neovim#11815]
Link is located here:

https://github.com/neovim/neovim/blob/ead61e5a52abcdff60d3b534bd32f43c61c0221a/runtime/doc/help.txt#L173

### Steps to reproduce using `nvim -u NORC`

```
$ nvim -u NORC
:help
/pi_matchit
```
* Position cursor over the 'pi_matchit.txt' link
* Try to follow it e.g. by pressing Ctrl+]

### Actual behaviour

`E149: Sorry, no help for pi_matchit.txt`

error message gest shown.

### Expected behaviour

Help on the matchit plugin should be shown.

This could be fixed by either removal of broken llink from help.txt or build process should create `pi_matchit.txt` before packaging possibly from bundled matchit own docs.

**Comment by ramiro** [comment]
Related to #8388

**Comment by justinmk** [comment]
added to https://github.com/neovim/neovim/pull/11708
