### ISSUE TITLE
Doesn't show end of line $ in :set list

### ISSUE THREAD

**Issue by theonlygusti** [neovim/neovim#11825]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? VIM behaves differently...
- Operating system/version: macOS Catalina 10.15.2
- Terminal name/version: Terminal.app 2.10
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
itype
a
bunch of lines
:set list
```

### Actual behaviour

<img width="116" alt="Screenshot 2020-02-06 at 13 13 44" src="https://user-images.githubusercontent.com/10684786/73940003-86d2eb80-48e2-11ea-9cc9-24a021586a66.png">

It doesn't show the end of line characters

### Expected behaviour

<img width="123" alt="Screenshot 2020-02-06 at 13 14 32" src="https://user-images.githubusercontent.com/10684786/73940056-aa963180-48e2-11ea-8f08-99c3bc2c2ec9.png">

**Comment by justinmk** [comment]
:set listchars+=eol:$

Defaults differ in Nvim. Always check `:help nvim-defaults`.
