### ISSUE TITLE
API: nvim_get_option('filetype') returns nothing

### ISSUE THREAD

**Issue by TravonteD** [neovim/neovim#11822]
If the filetype option is set, I expect to be able to get its value via `nvim_get_option()`

Steps to Reproduce:
- Open a buffer
- `set filetype=lua`

- This works:
  ```vimscript
  :echo &filetype "=> "lua"
  ```
- This does not:
   ```vimscript
   :echo nvim_get_option('filetype') "=> ""
   ```

**Comment by justinmk** [comment]
To get a buffer-local option use `nvim_buf_get_option`.

For behavior that matches Vim `:set`, we are considering a new API. Tracked in https://github.com/neovim/neovim/issues/11179
