### ISSUE TITLE
nvim-qt not support -c/--cmd option while startup

### ISSUE THREAD

**Issue by Chillbon** [neovim/neovim#11824]
- `nvim --version`: 0.5.0-356-gead61e5a5
- Operating system/version: win10
- Terminal name/version: nvim-qt

**Comment by justinmk** [comment]
Args after `--` are sent to nvim.

    nvim-qt -- --cmd ... -c ...

https://github.com/equalsraf/neovim-qt/wiki#passing-command-line-arguments-to-neovimexe
