### ISSUE TITLE
Complete falling apart of fugitive in neovim

### ISSUE THREAD

**Issue by mcepl** [neovim/neovim#11823]
- `nvim --version`: my own rebuild from ``master`` (commit 405f49a9b)
- `vim -u DEFAULTS` (version: ) behaves differently? yes, that works correctly (vim-8.2.0119-1.1.x86_64)
- Operating system/version: openSUSE/Tumbleweed (rolling release)
- Terminal name/version: gnome-terminal-3.34.2-3.1.x86_64
- `$TERM`: xterm-256color

### Steps to reproduce

1. with finished changes, save file
2. ``:G``
3. stage the file
4. everything look fine, so ``cvc``

### Actual behaviour

And the result is not editor with the commit message, but

![Snímek z 2020-02-06 02-09-19](https://user-images.githubusercontent.com/198999/73897540-ae946600-4886-11ea-8fa5-6c435b1f74a9.png)

### Expected behaviour

New split/tab opens for editing the commit message.

**Comment by justinmk** [comment]
Works for me at fugitive `460664018a8e` and Nvim 405f49a9b16c

NB: I don't have any fugitive options set. I do have vim-dispatch installed, maybe fugitive uses it for something?

>  `vim -u DEFAULTS` (version: ) behaves differently? yes, that works correctly (vim-8.2.0119-1.1.x86_64)

fugitive has different logic for vim/nvim. 

This is missing minimal steps, and I can't reproduce the issue anyway.

**Comment by teto** [comment]
gnome-terminal is VTE based so your why is your TERM `xterm-256color` instead of `vte` ?

**Comment by mcepl** [comment]
> gnome-terminal is VTE based so your why is your TERM `xterm-256color` instead of `vte` ?

Just using the system default.

**Comment by justinmk** [comment]
Maybe similar? https://github.com/tpope/vim-fugitive/issues/1446

**Comment by mcepl** [comment]
> Maybe similar? [tpope/vim-fugitive#1446](https://github.com/tpope/vim-fugitive/issues/1446)

I have no git-hooks whatsoever.

**Comment by tpope** [comment]
This screams #11751 plus `$GIT_EDITOR`. There's no good reason to set `$GIT_EDITOR`, stop doing it.

**Comment by mcepl** [comment]
> This screams #11751 plus `$GIT_EDITOR`. There's no good reason to set `$GIT_EDITOR`, stop doing it.

I am confused, is setting ``$GIT_EDITOR`` something neovim does? I certainly don’t, and I cannot find the string in the neovim git repository either.

**Comment by tpope** [comment]
You're saying `:echo $GIT_EDITOR` is blank?

**Comment by mcepl** [comment]
Not only that:
```sh
neovim@stitny (master)$ git grep GIT_EDITOR|cat
neovim@stitny (master)$ echo $GIT_EDITOR

neovim@stitny (master)$
```

**Comment by mcepl** [comment]
Using git-2.25.0-1.1.x86_64 if it matters (from the package from openSUSE/Factory packages).

**Comment by tpope** [comment]
Verify you can reproduce with no other plugins installed and a default nvim config and open a Fugitive issue if so.

**Comment by mcepl** [comment]
Actually, one thing which is nonstandard on my system. My variable ``$EDITOR`` has value ``editor``, which is this tiny script:
```sh
#!/bin/sh
if [ -n "$NVIM_LISTEN_ADDRESS" ] ; then
  nvr --remote-tab "$@"
else
  exec nvim "$@"
fi
```
(when starting editor inside of the neovim’s ``:term``).

@tope, could it make any difference?

**Comment by teto** [comment]
@mcepl what happens if you unset EDITOR ?

I have updated my plugins yesterday and since then fugitive seems to fail on some repos. (Gdiff master wont do a thing). I will try to investigate and see what I can do for #11751 anyway

**Comment by tpope** [comment]
`$GIT_EDITOR` (which Fugitive sets) should take precedence over `$EDITOR` but you should definitely double check that isn't a contributing factor.

**Comment by mcepl** [comment]
> @mcepl what happens if you unset EDITOR ?

Stupid me. Of course, what happens is that I will be using the Bram’s vim (which openSUSE insists to have installed as well).

**Comment by tpope** [comment]
Create the following `.git/hooks/pre-commit`

```sh
#!/bin/sh

echo "GIT_EDITOR is '$GIT_EDITOR'"
exit 1
```

What does `:Git commit` display?

**Comment by tpope** [comment]
@teto I don't think much has changed that would affect `:Gdiffsplit` but if you can't figure it out open an issue.

**Comment by mcepl** [comment]
> What does `:Git commit` display?
```
GIT_EDITOR is ''  
```

**Comment by tpope** [comment]
Try with `echo "GIT_EDITOR is '${GIT_EDITOR-unset}'"` to see if it's unset or an empty string.

After this line, add a `throw string([argv, jobopts])` and see what's in the error message.

https://github.com/tpope/vim-fugitive/blob/0e6f72b005312225ffb47290500941d59eb1f0f7/autoload/fugitive.vim#L2439

**Comment by mcepl** [comment]
```
Chyba při zpracování function fugitive#Command:
řádek   90:
E605: Exception not caught: [['env', 'GIT_MERGE_AUTOEDIT=1', 'GIT_PAGER=cat', 'NO_COLOR=1', 'GIT_EDITOR=sh /tmp/nvim28hxeI/2.sh', 'PAGER=cat', 'FUGITIVE_TEMP=/tmp/nvim28hxeI/1', 'GIT_SEQ
UENCE_EDITOR=sh /tmp/nvim28hxeI/2.sh', 'git', '-c', 'color.advice=false', '-c', 'color.branch=false', '-c', 'color.diff=false', '-c', 'color.grep=false', '-c', 'color.interactive=false',
 '-c', 'color.pager=false', '-c', 'color.push=false', '-c', 'color.remote=false', '-c', 'color.showBranch=false', '-c', 'color.status=false', '-c', 'color.transport=false', '-c', 'color.
ui=false', '-c', 'advice.waitingForEditor=false', 'commit'], {}]
```
I have no idea how this ``GIT_EDITOR`` happened, before running neovim, I had ``EDITOR`` set to plain string ``nvim`` (to avoid using the Bram’s vim), and search on whole ``~/.vim`` and all its subdirectories found only https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L396 and https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim#L2432.

**Comment by tpope** [comment]
So it's working fine, you just didn't pull before reporting a bug.

**Comment by mcepl** [comment]
I don't it is the reason, but I cannot reproduce anymore, so closing this down.

**Comment by mcepl** [comment]
> Sounds like it's working fine, you just didn't pull before reporting it.

@tpope Hmm, another day, and I got “GIT_EDITOR is 'unset'” again:

![Uploading Snímek z 2020-02-17 08-20-00.png…]()

I have absolutely no clue, what have changed since the last time I tried. Even when I unset ``$EDITOR`` again (and it would be really bad, if fugitive cannot work with ``$EDITOR`` set), the result is still the same after week or so of fugitive perfectly working.

**Comment by tpope** [comment]
Restore that `throw` and change it to a `echomsg` so you can see what command is being run next time you catch it in action.
