### ISSUE TITLE
LSP: rust-analyzer ignores already typed prefixes

### ISSUE THREAD

**Issue by 42triangles** [neovim/neovim#11826]
- `nvim --version`: NVIM v0.5.0-357-g405f49a9b
- `vim -u DEFAULTS` (version: ) behaves differently? Language servers are not supported in vim.
- Operating system/version: Arch Linux, everything up to date as of the 6th of February
- Terminal name/version: Termite 15-1
- `$TERM`: xterm-termite

### Steps to reproduce using `nvim -u NORC`

```
cargo new --bin ra-test
cd ra-test
nvim -u NORC
:set nocompatible
:filetype off
:set rtp+=~/.vim/bundle/Vundle.vim
:call vundle#begin()
:Plugin 'neovim/nvim-lsp'
:call vundle#end()
:PluginInstall
:q
:filetype plugin indent on
:lua require'nvim_lsp'.rust_analyzer.setup{}
:set omnifunc=v:lua.vim.lsp.omnifunc
:e src/main.rs
Ouse std::sy<C-x><C-o>
```

### Actual behaviour
It shows `self`, `super`, `libc`, `concat!`, etc. in that order, ignoring the prefix `sy`.

### Expected behaviour
It should only show everything starting with `sy` (`sync`, `sys`, `sys_common`), or everything matching `/s.*y.*/` (the aforementioned and `stringify!`), or any other useful metric respecting what the user already wrote.

**Comment by mjlbach** [comment]
This also happens with Microsoft's Python Language Server

**Comment by justinmk** [comment]
just guessing, maybe related to https://github.com/neovim/neovim/pull/11522 https://github.com/neovim/neovim/pull/11578 .  Would be helpful if you can revert either/both and check.

**Comment by mjlbach** [comment]
It's the result that is passed into the callback function by lsp.buf_request in lsp.omnifunc that's wrong; for some reason, the result return by pyls (and passed into the callback) are filtered, and the results returned by pyls_ms return all of the completion items.

**Comment by mjlbach** [comment]
One difference might be context support... Looking at rust-analyzer and microsoft's pyls, they both seem to be sending the 

```
    "context": {
        "triggerKind": 1
    }
```

on completion requests.

**Comment by justinmk** [comment]
> Even when fixing this though, the command sent by the internal vim lsp server is:

Those look the same?

**Comment by mjlbach** [comment]
> > Even when fixing this though, the command sent by the internal vim lsp server is ... and by vscode is ...
> 
> Those look the same?

Updated for clarity, it's still not returning completion results when sending the same commands on the same file as vscode.
