### ISSUE TITLE
Build failed without bundled parsers

### ISSUE THREAD

**Issue by markwu** [neovim/neovim#11835]
macOS: 10.14.6
Homebrew:
```
HOMEBREW_VERSION: 2.2.5-28-gb8c2e96
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b8c2e96ee6390803df7bbbc39e66d400b8ebcf52
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1252f760fe029bcafb6025bd4b3835a8dfe00264
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CUSTOM_RUBY_HOME: /Users/mark/.rvm/rubies/ruby-2.6.5
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_231
macOS: 10.14.6-x86_64
CLT: 11.3.0.0.1.1574140115
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11
```
### Actual behaviour

Build HEAD failed after commit 120a4c8e253a9c7f4fcd25351d4cb12ca99b4f3e

```
Last 15 lines from /Users/mark/Library/Logs/Homebrew/neovim/07.make:
make[1]: Nothing to be done for `preinstall'.
Install the project...
/usr/local/Cellar/cmake/3.16.3/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Installing: /usr/local/Cellar/neovim/HEAD-1f479ff/share/man/man1/nvim.1
-- Installing: /usr/local/Cellar/neovim/HEAD-1f479ff/bin/nvim
CMake Error at src/nvim/cmake_install.cmake:82 (file):
  file INSTALL cannot find
  "/tmp/neovim-20200208-70469-15xu9ya/build/lib/nvim": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:77 (include)
```

### Expected behaviour

Build without problems.

**Comment by bfredl** [comment]
This wasn't fixed by #11830 ? Maybe also the install command needs to be inside the condition. But we might put other stuff in `lib/nvim` later, perhaps we should create empty dummy dir already.

**Comment by agriffis** [comment]
Doesn't appear to have been fixed by #11830. I'm seeing the same failure in the Fedora COPR builds, which are up to date with master. For example:

https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-31-x86_64/01225096-neovim/build.log.gz

**Comment by fwalch** [comment]
Seeing the same error on [Arch Linux](https://aur.archlinux.org/packages/neovim-git/#comment-728299).

**Comment by bfredl** [comment]
@markwu @agriffis @fwalch would you mind try latest master (just pushed)

**Comment by yufanlu** [comment]
confirmed that running 'brew install --HEAD neovim' works now

thanks!

**Comment by agriffis** [comment]
@bfredl success, thanks!

**Comment by markwu** [comment]
I confirmed it fixed. Thanks!

**Comment by bfredl** [comment]
good to hear. Now we only need to fix our own CI (32-bit windows)...

**Comment by fwalch** [comment]
@bfredl Works on Arch as well, thanks!
