### ISSUE TITLE
Disable Python2 provider health check

### ISSUE THREAD

**Issue by Svetlitski** [neovim/neovim#11831]
- `nvim --version`: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/config -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"
```

- Operating system/version: macOS Mojave (10.14.6)
- Terminal name/version: iTerm2 3.3.8
- `$TERM`: xterm-256color

### Actual behaviour
When `g:loaded_python_provider` is explicitly set to 0 in init.vim, `nvim +checkhealth` still displays warnings in the form of
```
## Python 2 provider (optional)
  - INFO: Disabled (g:loaded_python_provider=0).  This might be due to some previous error.
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/local/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/local/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/local/opt/python/libexec/bin/python is Python 3.7 and cannot provide Python 2.
  - INFO: Executable: Not found
```
unlike with `g:loaded_ruby_provider` and `g:loaded_node_provider` where setting them to 0 disables warnings in the health check. It looks like this issue was brought up before in [#11040](https://github.com/neovim/neovim/issues/11040), and was previously resolved by [#11044](https://github.com/neovim/neovim/pull/11044), but seems to have returned.

### Expected behaviour
Setting `g:loaded_python_provider` to 0 in init.vim should disable health check warnings like with the node and ruby providers.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS.

**Comment by Svetlitski** [comment]
This issue is resolved in the development version, sorry for bothering you! Might be a good idea to add a note to the issue template to please try the development version first if this happens a lot.
