### ISSUE TITLE
Nvim under Cygwin Mintty

### ISSUE THREAD

**Issue by cup** [neovim/neovim#11849]
I can launch Nvim-Qt in any case. Regarding Nvim, I can launch it under the Windows Console
(`conhost.exe`) fine as well.

However if I launch Cygwin Mintty, then try to run Nvim, I just get a completely black window.

**Comment by cup** [comment]
I got this to work by getting Cygwin Winpty:

https://github.com/rprichard/winpty/releases

Then launch Mintty, then run

~~~
winpty nvim
~~~

**Comment by justinmk** [comment]
cygwin is a distribution. It's up to cygwin or some other interested party to build Nvim for cygwin.

It is possible to build Nvim for cygwin:
https://github.com/neovim/neovim/issues/873#issuecomment-364803591

The `nvim.exe` that we ship for Windows doesn't run in cygwin, it is intended for the standard Windows console/cmd.exe.

It might be possible for `nvim.exe` to be more clever: https://github.com/neovim/neovim/issues/6751

Attempted in https://github.com/neovim/neovim/pull/8271
