### ISSUE TITLE
Can't paste into / search while in V-LINE mode

### ISSUE THREAD

**Issue by theonlygusti** [neovim/neovim#11846]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: macOS Catalina 10.15.2
- Terminal name/version: Terminal.app
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

Enter visual line mode and then search for text (with `/`) and then paste stuff from the clipboard.

```
echo elephant | pbcopy
nvim -u NORC
ienter some text
to search
around in
elephant<ESC>ggV/<CMD-v>
```

### Actual behaviour

It puts elephant into the buffer like

```
eelephantnter some text
to search...
```

### Expected behaviour

It should put elephant into the command line as your search query `/elephant` and then V-line should move to the elephant in the text (line 4)

**Comment by justinmk** [comment]
Minimal repro:

    ggV/<CMD-v>

**Comment by zeertzjq** [comment]
Related: <https://github.com/vim/vim/issues/6127>
