### ISSUE TITLE
crash when removing a quickfix list

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#11855]
- `nvim --version`: NVIM v0.5.0-370-g5d5b068d5
 - `vim -u DEFAULTS` (version: 8.2 Included patches: 1-241) behaves differently? Yes
 - Operating system/version: Ubuntu 16.04.6 LTS
 - Terminal name/version: XTerm(322)
 - `$TERM`: xterm-256color

### Steps to reproduce

Run this shell command:

    nvim -u NONE +'au FileType qf let _ = getqflist({"title":0}).title' +'helpg foobar' +copen +'call setqflist([], "f")'

### Actual behaviour

Nvim crashes.

### Expected behaviour

Nvim doesn't crash.

### Additional information

This is a regression caused by 98801ec7a .

---

Here is a [backtrace](https://github.com/neovim/neovim/files/4188044/backtrace.txt).

**Comment by justinmk** [comment]
maybe fixed some followup vim patch in the 8.1.01xx range ?

**Comment by lacygoill** [comment]
I tried to reproduce on [8.1.0166](https://github.com/neovim/neovim/commit/98801ec7aea199b80373d1dc072021a98db63a8b), but I couldn't.

    " does NOT crash
    echo "x\nx\nx" >/tmp/file
    ./src/vim -Nu NONE +'au FileType qf let _ = getqflist({"title":0}).title' +'vim /x/ %' +copen +'call setqflist([], "f")' /tmp/file
    ^^^^^^^^^

    " DOES crash
    echo "x\nx\nx" >/tmp/file
    nvim -Nu NONE +'au FileType qf let _ = getqflist({"title":0}).title' +'vim /x/ %' +copen +'call setqflist([], "f")' /tmp/file
    ^^^^

If the issue is due to a missing Vim patch, I don't know how to find it, because this patch does not fix this particular crash in Vim, only in Nvim.

Here is the list of non-merged patches – after 8.1.0166 – containing the keyword "crash": https://0x0.st/i-f0.txt
And here is a similar list for the keyword "dict": https://0x0.st/i-fd.txt

FWIW, if I knew C and how to merge a Vim patch, I would first try [8.1.0489](https://github.com/vim/vim/commit/b6f1480a6a8b1a6fa4d5da97aeb5f4755b71eb91).
