### ISSUE TITLE
Nvim crashes after entering /0x symbols inside expression register

### ISSUE THREAD

**Issue by kupec** [neovim/neovim#11852]
- `nvim --version`: **v0.4.3**
- `vim -u DEFAULTS` (version: **8.0**) behaves differently? **it doesn't crash**
- Operating system/version: **Ubuntu 18.04.3 LTS**
- Terminal name/version: **GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2**
- `$TERM`: **xterm-256color**

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
i<C-r>=1/0x
```

### Actual behaviour

App crashes with text - 
```
nvim: /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/viml/parser/expressions.c:1241: viml_pexpr_handle_bop: Assertion `bop_node_lvl != new_top_node_lvl || bop_node_ass == new_top_node_ass' failed.
```

### Expected behaviour

No crash, user can type more letters to finish expression.

**Comment by lacygoill** [comment]
I can't reproduce with a `Release` build type, but I can with a `RelWithDebInfo` or `Debug` one.  I don't think it's a regression, as it already happened in v0.3.0.

Here is a [backtrace](https://github.com/neovim/neovim/files/4188130/backtrace.txt).

**Comment by lacygoill** [comment]
It looks similar to https://github.com/neovim/neovim/issues/7889, for which a PR exists (https://github.com/neovim/neovim/pull/8421).

**Comment by justinmk** [comment]
yep, someone needs to take ownership of https://github.com/neovim/neovim/pull/8421
