### ISSUE TITLE
Using Nvim-Qt colors with regular Vim

### ISSUE THREAD

**Issue by cup** [neovim/neovim#11857]
I have been using `nvim-qt` and I like it.

However I want to switch to regular `nvim`, but like other users I have had trouble with it.

So then I thought maybe I will just use plain `vim`. The issue is that I like the default
colors of `nvim-qt`, so I would like to keep that.

However I cant seems to duplicate it. I set `TERM=xterm-256color` in my environment, and
also `set termguicolors` in `.vimrc`. With `nvim-qt`, I get good looking color like this:

![Untitled](https://user-images.githubusercontent.com/60531334/74301023-54c4ed80-4d17-11ea-84b5-0643786fbd9c.png)

but with `vim` I get this:

![2](https://user-images.githubusercontent.com/60531334/74301042-63130980-4d17-11ea-9851-d66bb52079f2.png)

Its pretty close but some bolding is different. How can I resolve this? Note I am using
Windows with Mintty.

https://gist.github.com/tycho/73401cd6aed7e733fc2b97a8de1ca03e

**Comment by justinmk** [comment]
> I have been using `nvim-qt` and I like it.
> 
> However I want to switch to regular `nvim`, but like other users I have had trouble with it.

👌  
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
