### ISSUE TITLE
Failed to load python3 host despite good checkhealth

### ISSUE THREAD

**Issue by alexpopov** [neovim/neovim#11853]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: CentOS 7
- Terminal name/version: iTerm 2 > mosh > tmux 2.8
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Cannot. However I have created the following minimal init file:

```
let g:python_host_prog=expand('~/virtualenvs/nvim_py2/bin/python')
let g:python3_host_prog=expand('~/virtualenvs/nvim/bin/python')

call plug#begin()
" Plug 'numirias/semshi', {'do': ':UpdateRemotePlugins'} 
call plug#end()
```

### Actual behaviour

Calling nvim as follows:

`NVIM_LISTEN_ADDRESS=/tmp/nvim NVIM_PYTHON_LOG_FILE=/tmp/nvim_log ~/.local/bin/nvim.appimage -u mini_init.vim`

`:checkhealth` reports the following:
```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $SSH_TTY='/dev/pts/0'

## tmux
  - OK: escape-time: 100ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - ERROR: pbcopy does not work with tmux version: 2.8
    - ADVICE:
      - Install tmux 2.6+.  https://superuser.com/q/231130
      - or use tmux with reattach-to-user-namespace.  https://superuser.com/a/413233
  - OK: Clipboard tool found: tmux

## Python 2 provider (optional)
  - INFO: pyenv: Path: /usr/local/bin/pyenv
  - INFO: pyenv: Root: /home/alexpopov/virtualenvs
  - INFO: Using: g:python_host_prog = "/home/alexpopov/virtualenvs/nvim_py2/bin/python"
  - INFO: Executable: /home/alexpopov/virtualenvs/nvim_py2/bin/python
  - INFO: Python version: 2.7.14
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: pyenv: Path: /usr/local/bin/pyenv
  - INFO: pyenv: Root: /home/alexpopov/virtualenvs
  - INFO: Using: g:python3_host_prog = "/home/alexpopov/virtualenvs/nvim/bin/python"
  - INFO: Executable: /home/alexpopov/virtualenvs/nvim/bin/python
  - INFO: Python version: 3.7.5
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help g:ruby_host_prog for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v12.14.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

However when I call `:python3 print("test")` inside of nvim I get some variation on the following:

```
function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require[13]..provider#Poll, line 4
Vim(if):Error invoking 'poll' on channel 29 (python3-client):^@ch 29 was closed by the client
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
```

If I install Semshi and call `:UpdateRemotePlugins` I get essentially the same error message. 

The `NVIM_PYTHON_LOG_FILE` files always ends up empty. 

I set `NVIM_LISTEN_ADDRESS` so that I can connect a python REPL to Nvim as per [the `pynvim` instructions](https://github.com/neovim/pynvim#usage-from-the-python-repl). This works without problems and can change the text in my Nvim buffer. 

The only suspicion I have as to what is going on is that my workplace uses some sort of strange `pyenv` command which doesn't support all the features Nvim uses. For example `pyenv root` isn't a valid command under our systems—I set `$PYENV_ROOT` manually in my `.bash_profile`. 

### Expected behaviour

`:checkhealth` reports everything as a success and everything Just Works™

**Comment by alexpopov** [comment]
The issue turned out to be my employer's custom Python. greenlet could be imported, passing the nvim checks, but it was essentially an empty module. This is super niche and specific only to my work place.

**Comment by n-sweep** [comment]
@alexpopov any more info on this problem? I'm getting this exact error on my home PC in a conda environment, no workplace-specific weirdness.

**Comment by Shougo** [comment]
You should not use conda environment for neovim.
You need to use system Python instead.

**Comment by n-sweep** [comment]
@Shougo thank you, I've never been told that before and that doesn't seem to be the prevailing opinion. Is this anaconda specific? Can I use standard Python virtual environments without running into the same problems? I'm a DS so using Conda is kind of standard, but I also hate it so a good excuse to avoid would be nice.

**Comment by Shougo** [comment]
Please test pynvim with system Python.  If it works, it should be conda specific problem.
