### ISSUE TITLE
":vimgrep" too slow when filetype detection is enabled

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#11856]
- `nvim --version`: NVIM v0.5.0-370-g5d5b068d5
 - `vim -u DEFAULTS` (version:  8.2 Included patches: 1-241) behaves differently? Yes
 - Operating system/version: Ubuntu 16.04.6 LTS
 - Terminal name/version: XTerm(322)
 - `$TERM`: xterm-256color

### Steps to reproduce

Run this shell command:

    for i in {1..10}; do nvim -es -Nu NORC -i NONE +"let time = reltime() | vim /pattern/gj \$VIMRUNTIME/**/*.vim | pu=matchstr(reltimestr(reltime(time)), '.*\..\{,3}').' seconds to run :vimgrep'" +'%p|qa!'; done

### Actual behaviour

Each `:vimgrep` takes – on average – about [11.4 seconds](https://0x0.st/i-ed.txt) on my machine.

### Expected behaviour

Each `:vimgrep` takes on average 1 second.

### Additional information

The same command in Vim takes on average [0.45 seconds](https://0x0.st/i-en.txt) on my machine.

---

`:vimgrep` was not that slow in `v0.3.0` ([1.07 seconds](https://0x0.st/i-2o.txt)).
But it was still 2 to 3 times slower than current Vim's `:vimgrep`.

---

`:vimgrep` is much quicker when the filetype detection is disabled ([0.24 seconds](https://0x0.st/i-2z.txt) on average).

    for i in {1..10}; do nvim -es -Nu NORC -i NONE +"filetype off | let time = reltime() | vim /pattern/gj \$VIMRUNTIME/**/*.vim | pu=matchstr(reltimestr(reltime(time)), '.*\..\{,3}').' seconds to run :vimgrep'" +'%p|qa!'; done
                                                     ^^^^^^^^^^^^

---

The slowness is caused by a regression introduced in 98a818776.

**Comment by justinmk** [comment]
thanks for bisecting. I would guess comparing the function bodies from https://github.com/neovim/neovim/commit/98a818776419a55e8f488f4d77d413287eed2ec3 might lead to an easy fix. cc @mhinz

**Comment by shivin8974** [comment]
I had a similar error so i go through the training institutes near me i found vismera ( https://www.vismera.in ) and it solved my error and i learnt many things from there

**Comment by cballam** [comment]
Just created a pull request to fix this: #11907

I use Pop!_OS 19.04, which is effectively Ubuntu, and this drops the test done by @lacygoill from ~8.3s before the change to ~0.8 seconds after, roughly the expected behaviour.

**Comment by lacygoill** [comment]
Can confirm.  The PR brings down the time to around 1s on my machine, like it was on v0.3.0.
