### ISSUE TITLE
Change default of 'backupdir' to use trailing "//"

### ISSUE THREAD

**Issue by latricewilgus** [neovim/neovim#11860]
A couple of months ago Neovim supports trailing "//" in the 'backupdir' option.
(vim-patch:8.1.0251)

Digging up old discussions (#78, #2676, #3496) adding those would make a better default for 'backupdir' than the current one.
Therefore, I suggest changing the default from '.,$XDG_DATA_HOME/nvim/backup' to '.,$XDG_DATA_HOME/nvim/backup//'.

You might even consider dropping the '.' entirely and autocreating the 'backupdir' if needed, i.e. seting the default to '$XDG_DATA_HOME/nvim/backup//' (cf. discussions in #78, #3496 in particular first comments of @ZyX-I and @fmoralesc in #3496 and "Update 2" in #78).

And while we are at it: 'undodir' has default '$XDG_DATA_HOME/nvim/undo' but by its documentation that is treated as it would be '$XDG_DATA_HOME/nvim/undo//'.
Maybe setting there the default to '$XDG_DATA_HOME/nvim/undo//' would make things clearer. At least it would unifies all the directory specifications ('directory', 'backupdir', 'undodir').
I have no clue how they are internally implemented and whether they use the same code basis, but judging from their descriptions 'undodir' and 'backupdir' might do.

**Comment by justinmk** [comment]
PR welcome.

**Comment by 18shrijeet** [comment]
Hello @justinmk  Can I take up this issue and work on it?

**Comment by KillTheMule** [comment]
I guess that should be @tjdevries

**Comment by 18shrijeet** [comment]
Hello @tjdevries Could i work on this issue?

**Comment by KillTheMule** [comment]
Generally speaking though, you don't need to ask for permission. Open up a PR, people will look at it. If you have questions, join the gitter chat.

**Comment by tjdevries** [comment]
Yes, please do. Tag me in the resulting PR.

If you get stuck, it's OK to post a WIP PR with the questions you need help with.
