### ISSUE TITLE
`bufexists(0)` returns 1 after opening a terminal buffer

### ISSUE THREAD

**Issue by voldikss** [neovim/neovim#11875]
- `nvim --version`: NVIM v0.5.0-378-gbb331a9b3 from https://github.com/neovim/neovim/commit/bb331a9b31c441d47fc2cb3dcb87e0573f519dd9
- `vim -u DEFAULTS` (version: ) behaves differently? This issue also occurs on Vim8
- Operating system/version: Arch Linux/5.5.3-arch1-1
- Terminal name/version: terminator/1.91
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NONE`

```
nvim -u NONE
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```
After startup,
```vim
:echo bufexists(0) " output 0, which is expected
:terminal
:echo bufexists(0) " output 1, which should still be 0
```
### Expected behaviour

`bufexists(0)` should always be 0, as a bufnr must be a positive number.

**Comment by wsdjeg** [comment]
This happend in vim too. and please read the doc

bufexists({expr})					*bufexists()*
		The result is a Number, which is |TRUE| if a buffer called
		{expr} exists.
		If the {expr} argument is a number, buffer numbers are used.
		Number zero is the alternate buffer for the current window.
