### ISSUE TITLE
optionally highlight yanked text

### ISSUE THREAD

**Issue by mcepl** [neovim/neovim#11872]
- `nvim --version`: neovim from master (currently commit 58ec72f9f)
- `vim -u DEFAULTS` (version: ) behaves differently? Actually, it is the same, but it seems to me that this is so much low-level dependent, that neovim specific solution could be warranted.
- Operating system/version: Linux/openSUSE/Tumbleweed
- Terminal name/version: gnome-terminal (but should be implemented everywhere)
- `$TERM`: xterm-256colors

### Steps to reproduce using `nvim -u NORC`

Yanked text should be briefly highlighted. Like in

![example of the desired behaviour](https://camo.githubusercontent.com/2b6d854fd19242f79ab52bfaf600bb1a59bb84b0/687474703a2f2f692e696d6775722e636f6d2f48756c795a366e2e676966)

### Actual behaviour
Nothing happens, external plugin must be installed.

### Expected behaviour
No plugin required, just some configuration needs to be switched to have this behaviour on.

**Comment by pierreganty** [comment]
In the meantime the following works as suggested by justinmk in gitter:
https://github.com/justinmk/config/blob/a93dc73fafbdeb583ce177a9d4ebbbdfaa2d17af/.config/nvim/init.vim#L1087

**Comment by mcepl** [comment]
This looks a way more reasonable. I have been using https://github.com/machakann/vim-highlightedyank for this, but with 4000+ LoC it freaks me out.

**Comment by teto** [comment]
see `:h lua-highlight`
