### ISSUE TITLE
Autocommand CursorMoved is called in confusing/misleading ways

### ISSUE THREAD

**Issue by wellle** [neovim/neovim#11878]
- `nvim --version`:
    ```
    NVIM v0.4.3
    Build type: Release
    LuaJIT 2.0.5
    Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
    Compiled by brew@Catalina.local

    Features: +acl +iconv +tui
    ```

- `vim -u DEFAULTS` (version: 8.2) behaves differently?
    Yes, these issues are not present in Vim. See below.

- Operating system/version:
    macOS Catalina 10.15.3

- Terminal name/version:
    kitty 0.16.0

- `$TERM`:
    `screen-256color`

### Steps to reproduce

Put this file `repro3.vim` in a directory:
```vim
autocmd CursorMoved * echom printf('s:check(): win:%s, buf:%s line:%d/%d, preview:%d', win_getid(), bufname(), line('.'), line('$'), &previewwindow)
```
Create these files too (we'll use them as example buffer contents):
```
cat file1
a
a
```
```
cat file2
bb
bb
bb
```

1. Open one of the files with Neovim after sourcing repro3.vim:
    ```
    nvim -u repro3.vim --noplugin file1
    ```
    You'll see a message (this is expected):
    >s:check(): win:1000, buf:file1 line:1/2, preview:0

2. Now open the other file in a split: `:split file2`. You'll see another message:
    >s:check(): win:1001, buf:file1 line:1/2, preview:0

    ❗️This is unexpected. We see that the winid changed from 1000 to 1001, so the new window is active. However, the buffer is still file1 which contains 2 lines. The new window is supposed to show file2 though which contains 3 lines.

3. To illustrate move the cursor down (in newly created and currently active window) by typing `j`. Another message appears:
    >s:check(): win:1001, buf:file2 line:2/3, preview:0

    This one is as expected again. We're in the new window and looking at file2 which contains 3 lines.

If you try the same flow with `vim` instead of `nvim`, then there is no message at all after the `:split file2` command. So in Vim we don't see this confusing/misleading `CursorMoved` autocommand.

Additionally, this difference between Vim and Neovim is also apparent if you switch between the windows by typing `<C-W><C-W>`: In Vim the `CursorMoved` autocommand doesn't trigger, in Neovim it does. Is this on purpose? It seems bad/wrong to have this difference in behavior between the two.

### Bonus case (preview window)

If you execute the steps above, but instead of `:split file2` in step 2 use `:pedit file2` you'll actually see two messages instead of one:
>s:check(): win:1001, buf:file1 line:1/2, preview:0
>s:check(): win:1000, buf:file1 line:1/2, preview:0

So here it appears like opening a preview window does temporarily moves the cursor to the preview window and then back to the original window. Again this is different to Vim behavior where the `CursorMoved` autocommand doesn't get trigger on `:pedit` at all.

### Context

This weird behavior leads to unexpected behavior one of my Vim/Neovim plugins. See https://github.com/wellle/context.vim/issues/36 and https://github.com/wellle/context.vim/issues/47.

Also, FWIW, looking back at another Neovim issue I opened recently I feel like they might actually be related. https://github.com/neovim/neovim/issues/11597

**Comment by justinmk** [comment]
does the problem go away after reverting https://github.com/neovim/neovim/pull/9807 ?

**Comment by wellle** [comment]
@justinmk: Thanks! I managed to somehow revert that locally and it does indeed seem to fix this issue. What do we do now?

(In other news it seems like #11597 has been fixed in the meantime! I can't reproduce it anymore. I'll do some bisecting and then update/close that issue)

**Comment by bfredl** [comment]
> Additionally, this difference between Vim and Neovim is also apparent if you switch between the windows by typing <C-W><C-W>: In Vim the CursorMoved autocommand doesn't trigger, in Neovim it does. Is this on purpose? It seems bad/wrong to have this difference in behavior between the two.

This _does_ happen also in vim. You just won't see it in an artificially constructed test case where the cursor is on (1,0) in every buffer. Try moving cursors around before invoking <c-w><c-w> and it will happen in vim as well. The only difference is that neovim does this _consistently_ , so that know _earlier_ that there is an issue with the plugin.

**Comment by wellle** [comment]
@bfredl: Thank you, that's good to know!

For more fair comparison let's reproduce like this then:

## Steps to reproduce

1. `nvim -u repro3.vim --noplugin file1`
2. move cursor down by typing `j`
3. `:split file2`
4. move cursor down by typing `j`

In Neovim we see these `:messages` (❗️ added as highlight):
```
s:check(): win:1000, buf:file1 line:1/2, preview:0
s:check(): win:1000, buf:file1 line:2/2, preview:0
s:check(): win:1001, buf:file1 line:2/2, preview:0  ❗️
s:check(): win:1001, buf:file2 line:1/3, preview:0
s:check(): win:1001, buf:file2 line:2/3, preview:0
```

For comparison, in Vim we see these:
```
s:check(): win:1000, buf:file1 line:1/2, preview:0
s:check(): win:1000, buf:file1 line:2/2, preview:0
s:check(): win:1001, buf:file2 line:1/3, preview:0
s:check(): win:1001, buf:file2 line:2/3, preview:0
```

Note in the Neovim messages the marked line. It shows that the new window is active, but still the old buffer. This is unexpected.

## With preview window case

1. `nvim -u repro3.vim --noplugin file1`
2. move cursor down by typing `j`
3. `:pedit file2`
4. switch to preview window by typing `<C-W><C-W>`
5. move cursor down by typing `j`

Neovim `:messages` (❗️❕ added as highlight):
```
s:check(): win:1000, buf:file1 line:1/2, preview:0
s:check(): win:1000, buf:file1 line:2/2, preview:0
s:check(): win:1001, buf:file1 line:2/2, preview:0  ❗️
s:check(): win:1000, buf:file1 line:2/2, preview:0  ❕ 
s:check(): win:1001, buf:file2 line:1/3, preview:1
s:check(): win:1001, buf:file2 line:2/3, preview:1
```

Vim `:messages`:
```
s:check(): win:1000, buf:file1 line:1/2, preview:0
s:check(): win:1000, buf:file1 line:2/2, preview:0
s:check(): win:1001, buf:file2 line:1/3, preview:1
s:check(): win:1001, buf:file2 line:2/3, preview:1
```

Note how here Neovim switches to the preview window (but again still with the first buffer active, this is unexpected) and back when it opens. Vim only fires `CursorMoved` once we actively switch to the preview window.
