### ISSUE TITLE
API/UI: Allow UI to set PUM position and size, and pass the position to CompleteChanged

### ISSUE THREAD

**Issue by yatli** [neovim/neovim#11879]
- `nvim --version`: NVIM v0.5.0-309-g05ea3c199
- `vim -u DEFAULTS` (version: ) behaves differently? No.
- Operating system/version: Microsoft Windows [Version 10.0.18363.628]
- Terminal name/version: FVim/nvim-qt
- `$TERM`: FVim/nvim-qt

As per https://github.com/neovim/neovim/pull/4432, the exposed ui events are:
```
popupmenu_show(items, selected, row, col)
popupmenu_select(selected)
popupmenu_hide()
````
Additionally, there is `nvim_ui_pum_set_height({height})` to report back the height of the external pum.

However, nvim still doesn't have the full information about the pum geometry. External UIs have their own logic for placing the popup (NE/NW/SE/SW, for example).

`coc.nvim` uses the ~~MenuPopupChanged~~ (edit: now `CompleteChanged`) (see: https://github.com/neovim/neovim/commit/6c375d71c3a92b0f83f1756799520ae61d11e64e) event to show documentation from language servers, next to the completion items. When external PUM is enabled, the size passed in this event is currently set to 0, causing the documentation pane to appear at the line below cursor line, which overlaps with the PUM itself.

I've verified the behavior with `coc.nvim` and:

nvim-qt:
![image](https://user-images.githubusercontent.com/20684720/74602403-092d8d80-50e3-11ea-9e66-c8473192c115.png)

FVim: 
![image](https://user-images.githubusercontent.com/20684720/74602421-35e1a500-50e3-11ea-9e36-410988d328ea.png)

Related: #11537 , something like `pum_set_pos` would do.

**Comment by justinmk** [comment]
> `coc.nvim` uses the `MenuPopupChanged` (see: [6c375d7](https://github.com/neovim/neovim/commit/6c375d71c3a92b0f83f1756799520ae61d11e64e))

Just to avoid confusion: that was renamed to `CompleteChanged`.

> Allow external PUM to report back position and size, and pass the position to MenuPopupChanged

So it sounds like you want `nvim_ui_pum_set({info})` instead of just `nvim_ui_pum_set_height()`.

**Comment by yatli** [comment]
> Just to avoid confusion: that was renamed to CompleteChanged.

Thanks! Was wondering why both are showing up in `coc.nvim` code.

**Comment by yatli** [comment]
> So it sounds like you want nvim_ui_pum_set({info}) instead of just nvim_ui_pum_set_height().

Yes. A position tuple of `{row, col, width, height}`.
