### ISSUE TITLE
TUI: support for hyperlinks (OSC-8)

### ISSUE THREAD

**Issue by expipiplus1** [neovim/neovim#11871]
In the below screenshot I have opened some documentation in a popup window,
however the links to the documentation have wrapped and as such are
inaccessible to the url-detection of my terminal emulator.

![image](https://user-images.githubusercontent.com/857308/74549345-737eea80-4f8a-11ea-9df7-2cd03c1e7767.png)

Some documentation on hyperlinks in terminals can be found [here](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda). In short: with this escape code one can embed links behind text in a
terminal. `printf '\e]8;;https://neovim.io\e\\A link to Neovim\e]8;;\e\\\n'`
for example.

It would be super if Neovim would support such functionality, so that in the
example above whatever process is generating the string
`[Documentation](file:///nix/store/...)` could instead generate the string
`Documentation` along with a link, instructing Neovim that this should be
rendered to the terminal as a hyperlink.

There is some ever so slightly similar behaviour already in Vim, when browsing
help files, double clicking on a word will take the user to that section in the
documentation, although this is just a textual match and doesn't have an URL
hidden beneath the text.

**Comment by expipiplus1** [comment]
Ah, the comments [here](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) suggest that this may already be possible with conceal. Ping @teto (I like how we both bumped into this trying to get to Haskell documentation via LSP on Nix)

There is some prior work on this from a few years ago here: https://github.com/crbinz/vim-links

**Comment by teto** [comment]
yes it would be nice. You may be able to test with conceal and highlights that use `start` and `stop` (check `:h term-list`) to output the escape sequence.

**Comment by mcepl** [comment]
> There is some prior work on this from a few years ago here: https://github.com/crbinz/vim-links

Also, https://github.com/plan9-for-vimspace/plan9-for-vimspace if I understand this issue correctly.

**Comment by expipiplus1** [comment]
Hmm, seems like neovim is eating these escapes maybe?

`:hi testHighlight start=<ESC>]8;;https://example.com<ESC>\\ stop=<ESC>]8;;<ESC>\\` doesn't seem to work.

Neither does `printf '\e]8;;https://neovim.io\e\\A link to Neovim\e]8;;\e\\\n'` inside `:term`

As for using concealing to implement this, I'm not sure (in my very limited understanding of the conceal feature) how conceal could move the URL to in front of the link text.

Additionally, for using `start` and `stop` (at least in what I'm attempting above) wouldn't this require a separate highlight group for each distinct URL!

**Comment by bfredl** [comment]
This would need to be natively supported by the UI/TUI layer of neovim. You cannot output arbitrary terminal sequences by highlight definitions, highlights are an abstraction in nvim and not tied to a particular UI like TUI.

We would need to tie a hyperlink to a region of text via an extmark somehow, and forward the information to UI:s in a convenient fashion.

**Comment by expipiplus1** [comment]
@bfredl `:help term-list` seem (to me) to suggest otherwise; it says `It can be anything that you want to send to the terminal to highlight this area.`. Clearly this is not the case though as otherwise my attempt above would have worked. Perhaps the documentation here needs updating?

**Comment by bfredl** [comment]
I think these are still _parsed_ as to not error out on any color scheme which happens to use them. But yes the docs needs to be updated to say it takes no effect in nvim TUI.

**Comment by expipiplus1** [comment]
@bfredl Ah I see, thanks for explaining. Indeed extmarks look like a good fit for this kind of thing.

@teto, for the exact issue we ran into I wrote this little function to open the links that appear in popup windows:

```viml
        function! s:show_documentation()
          if (index(['vim','help'], &filetype) >= 0)
            execute 'h '.expand('<cword>')
          else
            call CocAction('doHover')
          endif
        endfunction

        " Use K to show documentation in preview window
        nnoremap <silent> K :call <SID>show_documentation()<CR>

        " Open the documentation window, search for a link and follow it in the
        " browser
        function! s:open_documentation_link(target)
          call s:show_documentation()
          let float_window = coc#util#get_float()
          if !float_window
            echo "No documentation available"
            return
          endif
          if !win_gotoid(float_window)
            echo "Unable to go to documentation window"
            return
          endif
          if !search("\\[" . a:target . "](", "ce")
            echo "No documenation link found"
          else
            exe "normal gx"
          endif
          call coc#util#float_hide()
        endfunction

        nnoremap <silent> <leader>l :call <SID>open_documentation_link("Source")<CR>
        nnoremap <silent> <leader>k :call <SID>open_documentation_link("Documentation")<CR>
```

**Comment by justinmk** [comment]
Would this not be solved by `:terminal` "reflow"? https://github.com/neovim/neovim/issues/2514

**Comment by expipiplus1** [comment]
@justinmk Sorry, I'm not quite sure what you mean by that. I think this feature would be more generally useful than just helping with URLs spread across multiple lines.

**Comment by justinmk** [comment]
@expipiplus1 The original report here looks like a problem with hard-wrapping.  https://github.com/neovim/neovim/issues/2514 would solve that. So I don't understand why we need this separate issue.

**Comment by expipiplus1** [comment]
Sorry @justinmk it's not a problem with hard wrapping. Certainly for my initial problem it could be solved by widening the window so the whole URL fits in one line, but I don't think that this is something that hard-wrapping would do.

But separately to wrapping long URLs I think this feature could be nice to have.

https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda, this link explains some of the motivation behind this potential change.

**Comment by expipiplus1** [comment]
@justinmk I don't think this should have been closed.

**Comment by justinmk** [comment]
> for arbitrary text to point to URLs, just as on webpages

as Björne explained  https://github.com/neovim/neovim/issues/11871#issuecomment-586406148 :

> This would need to be natively supported by the UI/TUI layer of neovim. You cannot output arbitrary terminal sequences by highlight definitions, highlights are an abstraction in nvim and not tied to a particular UI like TUI.
> 
> We would need to tie a hyperlink to a region of text via an extmark somehow, and forward the information to UI:s in a convenient fashion.

basically this would be another "decoration" jammed into `:highlight` or something like that.

**Comment by sesse** [comment]
Has anyone actually gotten this to work? In the latest 0.10.0 snapshot, I've tried setting 

```
    local ext = vim.api.nvim_buf_set_extmark(0, ns, pos[1], pos[2], {                                                   
        end_row = next_pos[1],                                                                                          
        end_col = next_pos[2],                                                                                          
        hl_group = "Grudge" .. colormap[id],                                                                            
        virt_text = {{commit, "GrudgeCommitMsg"}},                                                                      
        virt_text_pos = "right_align",                                                                                  
        url = "https://www.google.com",                                                                                 
    })       
```

and it errors out with `invalid key: url`.
