### ISSUE TITLE
insert tab with softtabstop and block insert mode

### ISSUE THREAD

**Issue by the42** [neovim/neovim#11882]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? : Yes, because softtabstops doesn't get set
- Operating system/version: Linux Manjaro KDE
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

When softatbstop is set to eg. 4 and there are many real blanks in front of the text I am editing, when block selecting a single column eg three rows long, and inserting a single tab, hitting ESC afterwards, the blanks on the row where I inserted the tab get replaced by smart tabs, however not so on the other rows affected by the block mode insert.

**To Reproduce**
File content:

    Hello1                123
    Hello2                234
    Hello3                345

Block select eg. 

    Hello1                X23
    Hello2                X34
    Hello3                X45

(X is the block selection)

press `I`, enter a single tab by pressing the <TAB>- key on the keyboard, press <ESC>

Output --> tabs expanded only for the first line
    Hello1\t      \t      \t123
    Hello2                \t234
    Hello3                \t345

Btw, no tabs get expanded, when the tab is inserted literally by preceding the tab-press with CTRL_V.

**Expected behavior**

I would propose that either
* no blanks get replaced preceding the bock selection insert <-- the user would expect block insert I to work on the block selection, not affecting the text before!   OR
* all blanks on all rows spanning the block selection insert are replaced by smart tabs.

**Comment by justinmk** [comment]
When comparing to vim you need to ensure that you're using the exact same set of options. `:help nvim-defaults`

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
