### ISSUE TITLE
decouple iskeyword

### ISSUE THREAD

**Issue by eyalk5** [neovim/neovim#11891]
iskeyword currently used for completion as well as for movement.
I think it is better to separate it into two variables. 
In my case, I want to to change the functionality of completion, but keep the functionality of movement. For example, `w` to function as before. 

In my case, I want \chi_{23} to be a single object. But it also makes \dosomething{crap}  a single object which means I can't get to crap using `w`. 

I don't think it should be very problematic to implement.

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/issues/1285

Having deja vu, was this discussed on gitter, or vim's tracker ...?

**Comment by eyalk5** [comment]
The goal of #1285 is completely different (to  allow overriding settings of syntax files). Even if it is implemented, it will effect both movement and completion. So not duplicate. 
(btw, i don't remember any chat) 

In the most straightforward way, it will break things. But in the second most straightforward way, it won't. 
Two new settings :

 iskeywordmovment, iskeywordcompletion

In case of completion it would use: iskeyword+iskeywordcompletion
as the set of keywords.

**Comment by chrisbra** [comment]
> or vim's tracker ...?

There are several related ones, eg.

https://github.com/vim/vim/issues/4563

**Comment by chrisbra** [comment]
BTW: Isn't #1285 at least partly reached with the `syn iskeyword` feature?
