### ISSUE TITLE
color glitches when scrolling buffer

### ISSUE THREAD

**Issue by doubleloop** [neovim/neovim#11893]
- `nvim --version`: NVIM v0.5.0-384-ga2efc9cf8
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: debian testing (bullseye)
- Terminal name/version: alacritty 0.4.2-dev
- `$TERM`: alacritty (also happens on gnome-terminal)

### Steps to reproduce (debug build)

testrc.vim
```vim
" note: issue occurs also without vim-syntax-extra but less frequent
call plug#begin('~/.local/share/nvim/plugged')
Plug 'justinmk/vim-syntax-extra'
call plug#end()
hi StatusLine ctermbg=red ctermfg=yellow cterm=NONE
```

```sh
# sha1sum is just used for making some background CPU load,
# it makes this more reproducible, 8 is nr of cores
$ for i in {1..8}; do  sha1sum /dev/zero &  done && \
  build/bin/nvim -u testrc.vim src/nvim/eval.c && \
  killall sha1sum
```
inside nvim, just press (and hold) `CTRL-D' to scroll down

### Actual behaviour
There are moments, when color used for `ctermbg` of statusline coveres lower portion of buffer.

![vim-status](https://user-images.githubusercontent.com/2602750/74673213-19ab3a00-51af-11ea-838b-628c09a4410e.gif)

### Expected behaviour
buffer background should remain the same during scrolling

**Comment by doubleloop** [comment]
### Release build reproduction: 
Issue is difficult to reproduce for release build without tmux. Inside tmux it happens very easy

releasetestrc.vim:
```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'justinmk/vim-syntax-extra'
Plug 'crusoexia/vim-monokai'
call plug#end()
set noshowmode
set noshowcmd
silent! colorscheme monokai
set termguicolors
hi StatusLine guibg=red guifg=yellow gui=NONE
```

tmuxrc
```
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",alacritty:RGB"
```

```sh
$ nvim -u releasetestrc.vim src/nvim/eval.c
```
inside nvim i use `CTRL-D' and `CTRL-U' to scroll up and down

![vim-status2](https://user-images.githubusercontent.com/2602750/74685636-69016280-51cf-11ea-8e0f-ba0eb59f989d.gif)

**Comment by mjlbach** [comment]
I've noticed this at the top of buffers as well

**Comment by bfredl** [comment]
Seems we should guesstimate the BCE color before scroll to reduce the perception of flicker, even if the end result doesn't depend on BCE (we always repaint after scroll).
