### ISSUE TITLE
LSP completion: text typed after invoking omnifunc is replaced when the server returns

### ISSUE THREAD

**Issue by K1DV5** [neovim/neovim#11904]
- `nvim --version`: NVIM v0.5.0-378-gbb331a9b3
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Windows 10 1903
- Terminal name/version: powershell
- `$TERM`: [none]

### Steps to reproduce using `nvim -u NORC`
Install python and pyls[all]
Make sure to have `nvim-lsp` in `packpath`
```
nvim -u NORC
# in nvim
:e some.py # existing python file
# in the file,
import numpy
numpy.<c-x><c-o>something
```

### Actual behaviour
"something" typed after invoking the completion is replaced by the first item in the completion list

### Expected behaviour
Since some other text has been typed, the completion should be canceled.

**Comment by h-michael** [comment]
[memo]
bb331a9b3 is before #11895

**Comment by K1DV5** [comment]
OK, will try it on the next release.

**Comment by h-michael** [comment]
@K1DV5 I'll see this later.

**Comment by K1DV5** [comment]
Right

**Comment by K1DV5** [comment]
This issue can be circumvented by `set completeopt=menu,noinsert,noselect`
