### ISSUE TITLE
Feature Request: Setting for forward jumplist behavior 

### ISSUE THREAD

**Issue by lanza** [neovim/neovim#11913]
Unwinding the jumplist via `ctrl-i` and then jumping to a new target currently exhibits a purely appending behavior. I think it's a little more intuitive for it to have a stack like behavior. To demonstrate the idea, here's jumplist functionality implemented in psuedopython:

Start:
```
jumplist = [locA, locB, locC, locD]
currentLocation = locD
```

performing ctrl-o sets us to
```
jumplist = [locA, locB, locC, locD]
currentLocation = locC
```

performing a new jump currently does
```
jumplist.append(locE)
// the list is now [locA, locB, locC, locD, locE]
currentLocation = locE
```

I think that there should be a `jumplistbehavior=stack` option that enables treating the list like a stack where you pop off the past-the-current-location elements:
```
currentIndex = jumplist.indexOf(currentLocation)
while len(jumplist) > currentIndex + 1:
    jumplist.pop()
jumplist.append(locE) // [locA, locB, locC, locE]
currentLocation = locE
```

This probably wouldn't be difficult to implement. Clearly explaining the behavior to others in a doc might be difficult, though.

**Comment by kdarkhan** [comment]
I too vote for this feature. There is an answer in [this stackoverflow question](https://vi.stackexchange.com/questions/18344/how-to-change-jumplist-behavior) which links to an implementation. I haven't tested it though.

**Comment by lanza** [comment]
Evidently the is implemented in `master`. 

```
						*'jumpoptions'* *'jop'*
'jumpoptions' 'jop'	string	(default "")
			global
	List of words that change the behavior of the |jumplist|.
	  stack         Make the jumplist behave like the tagstack or like a
	                web browser.  Relative location of entries in the
			jumplist is preserved at the cost of discarding
			subsequent entries when navigating backwards in the
			jumplist and then jumping to a location.
			|jumplist-stack|
```
