### ISSUE TITLE
How to a read-only file with neovim open?(Sometimes forget it's a read-only file and reopen is ...)

### ISSUE THREAD

**Issue by 66RING** [neovim/neovim#11916]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version:
- Terminal name/version: st
- `$TERM`:

Sometimes forget it's a read-only file and reopen is ...

I know neovim with some problem with interactive commands. See here:
https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes

In vim, I can map `:w !sudo tee %` to `W!` or something and quite.

But in neovim, which do weird things with interactive processes, I can't do so. Because, sudo need a interactive thing and `w` can't pipe into `terminal` command. 

Anyway, neovim is awesome.😂

**Comment by justinmk** [comment]
Not sure if @janlazo  plugin https://github.com/janlazo/vim-bang-terminal handles this, but maybe? 

Other workaround I can think of would be to creating a mapping that opens the file in `:terminal` with `sudo nvim ...`.

> But in neovim, which do weird things with interactive processes

Just to be clear, gVim (at least up to 8.0) works similarly: the "weird thing" is just that pipes are used, not pty.

**Comment by 66RING** [comment]
Thank you for your time
