### ISSUE TITLE
Windows: providing binaries without nvim-qt

### ISSUE THREAD

**Issue by K1DV5** [neovim/neovim#11917]
I know nvim-qt has some nice GUI features like a tree explorer and a "tab bar" that can be a little more friendly for a new user, but it's not strictly necessary and I don't think it should be bundled. I think it should be optional with a note on how to get it on the install instructions.

And if that is done, I think it would be good to give the Neovim icon to nvim.exe when compiling.

**Comment by justinmk** [comment]
Simply delete it. We aren't going to provide separate zip downloads, that would just create lots of extra text for users to read and decide. Not worth the tradeoff.

> would be good to give the Neovim icon to nvim.exe when compiling

Definitely, PR welcome.

**Comment by K1DV5** [comment]
That makes sense
> Definitely, PR welcome.

Ok, will try
