### ISSUE TITLE
LSP with servers using TCP

### ISSUE THREAD

**Issue by Shatur** [neovim/neovim#11911]
Some language servers require TCP to work with them.

For example, recently Godot 3.2 was released with LSP support. But LSP works only through Websocket. [This](https://github.com/godotengine/godot/pull/35864#) PR switches Godot's LSP to TCP and now can be suported for the Vim plugins. I tested it with coc.nvim and everything works. Is in possible to add TCP support to the native implementation?

**Comment by Shatur95** [comment]
The PR for TCP support was merged into Godot.
Currently built-in LSP [works through nc](https://github.com/neovim/nvim-lspconfig/blob/62977b6b2eeb20bd37703ebe4bc4b4c2ef006db2/lua/lspconfig/gdscript.lua#L6). I think other LSPs might work like this too. But this approach is not portable and very slow, so it would be great to have native TCP support.

**Comment by kenkangxgwe** [comment]
Hi, any update on this? I saw that kotlin and sourcegraph support `transport = 'socket'` in their lspconfigs settings. I wonder how they connect to the client via TCP while this is not supported yet. I am trying to config the wolfram language server, which only supports socket, on neovim lsp.

**Comment by rcorre** [comment]
Apologies if this is the wrong issue, but I've noticed diagnostics from the `gdscript` client can sometimes "lag". Does that seem related to the use of `nc`, and would builtin TCP support help? Or does this seem like an unrelated issue?


https://user-images.githubusercontent.com/2496231/151663644-0199eed7-42b4-4755-a638-79cb2fda1056.mp4

**Comment by mjlbach** [comment]
You need to use a debounce for godot (500 ms) as the language server is extremely slow.

**Comment by rcorre** [comment]
@mjlbach by "debounce" are you referring to `nc --interval`?
