### ISSUE TITLE
LSP: No braces in function after insertion

### ISSUE THREAD

**Issue by Shatur95** [neovim/neovim#11922]
- `nvim --version`: v0.5.0-389-g9897ad360
- Operating system/version: Arch Linux
- Terminal name/version: Konsole, neovim-qt
- `$TERM`: xterm-256color

### Actual behaviour:
All functions in proposed auto-completion list (with `pyls` or `clangd`) has brackets. But after completion confirmation, it is inserted without parentheses.

### Expected behaviour
Functions are inserted in the code along with brackets.

**Comment by justinmk** [comment]
No idea what you mean. When I do ctrl-x ctrl-o to complete `foo(`, it inserts `foo(`.

Going to close this because no effort was made to give a clear report.

**Comment by Shatur95** [comment]
@justinmk, I'm sorry. I updated description and added video.

**Comment by Shatur95** [comment]
@justinmk, is it look clear now? If yes, could you reopen this issue?
I'm not sure, maybe it's expected behavior.
