### ISSUE TITLE
paste: support replace mode

### ISSUE THREAD

**Issue by la-magra** [neovim/neovim#11921]
- `nvim --version`: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- `vim -u DEFAULTS` (version: ) behaves differently? 
Unknown, vim not installed.
vi does not have this issue through.
- Operating system/version: 
Arch-linux
- Terminal name/version:
None, ssh only machine, no GUI
- `$TERM`:
screen-256color

### Steps to reproduce using `nvim -u NORC`

```
copy 'helloworld.' text to clipboard

nvim -u NORC

i -> paste from clipboard (ctrl+shift+insert) -> Esc

0 (to start of line) -> R (replace mode) -> paste same content from clipboard (ctrl+shift+insert) -> Esc

final result: 'helloworld.helloworld.'

```

### Actual behaviour

In replace mode clipboard content being pasted is inserted at cursor instead of replacing at cursor.

### Expected behaviour

Pasting clipboard contents in Replace mode replaces content at cursor.

**Comment by KillTheMule** [comment]
I'm seeing the same when using `Ctrl-Shift-v` which my terminal emulator uses for pasting. When using `<Ctrl-R>+` instead though this does _not_ happen.

**Comment by justinmk** [comment]
known issue. Just hasn't been implemented in `vim.paste()`
