### ISSUE TITLE
E575 ShaDa file error "mark entry at position XXXX has invalid line number" for `nvim -c "e ~/.vimrc"`

### ISSUE THREAD

**Issue by nocibambi** [neovim/neovim#11937]
**Describe the bug**
Using the following command from gnome terminal produces the error message below

```shell
> nvim -c "e .vimrc"
```
```
E575: Error while reading ShaDa file: mark entry at position [line number] has invalid line number
Press ENTER or type command to continue
```

This happens by trying to open any kind of file or even with a nonexisting file.

**To Reproduce**
0. Optional: Create a simple text file (e.g. `test.txt`) 
2. Run the following command by using the name of an existing or a non-existing file.
```shell
> nvim -c "e test.txt"
```

**Expected behavior**
I should expect no error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/8539674/75105654-454a7c00-5616-11ea-9ec8-65c36fe089f5.png)

**Environment (please complete the following information):**
 - NVIM v0.2.2
 - Ubuntu 18.04
 - Gnome terminal
 - I turned out all plugins.

**Additional context**
- The error message also appears when I quit nvim.
- The error message also appears when I run `nvim -c "o test.txt"` (note the different command). In this case, after entering nvim, it also shows the following error

```
Error detected while processing command line:                                                                                                                                                                        
E488: Trailing characters
Press ENTER or type command to continue
```

But, after quitting nvim and running the original `nvim -c "e test.txt"`, there is no error for the first time (but reappears when I quit and run it again).
- After having the error message, quitting from nvim and simply opening nvim without any additional commands the error appears for the first time. After the next quit, however, the error disappears for good until I run the original (`nvim -c "e test.txt"`) command.
- I saw that this has been reported [here](https://github.com/neovim/neovim/issues/7677) and [here](https://github.com/neovim/neovim/issues/7169) but both are closed and I am on the same version as many of the reporters there (which I assume is the one gets installed with Ubuntu apt).
- I also [tried](https://vi.stackexchange.com/questions/15383/how-can-i-suppress-startup-error-e575/15501#15501) this workaround. After I remove my `shada` folder the error message disappears for the first time but reappears when I close nvim and rerun the same command.
- The main reason I try to do this is to open nvim at Ubuntu startup (as it is explained [here](https://askubuntu.com/questions/84740/how-to-configure-vim-to-start-automatically-when-my-pc-boots/84741#84741)) but with a file opened by default.

**Comment by justinmk** [comment]
> NVIM v0.2.2

That's quite old. Even if this bug is still present in master and we fixed tomorrow, it can never be fixed on v0.2.2. 

Try the appimage from the [Releases](https://github.com/neovim/neovim/releases) page.

> I saw that this has been reported [here](https://github.com/neovim/neovim/issues/7677) and [here](https://github.com/neovim/neovim/issues/7169) but both are closed and I am on the same version as many of the reporters there

The fix would be in a later version.
