### ISSUE TITLE
UI:  nvim_win_get_position result on float window is incorrect if ext_multigrid is true

### ISSUE THREAD

**Issue by akiyosi** [neovim/neovim#11935]
- `nvim --version`:
NVIM v0.4.3

### Steps to reproduce using `nvim -u NORC`
1.  `/Applications/goneovim.app/Contents/MacOS/goneovim -u NONE`
2. `nvim_open_win(bufnr(''), v:true, { 'width':  30, 'height': 5, 'relative': 'win', 'anchor': 'NW', 'row': 2, 'col': 10, 'external': v:false })`
3. `echo nvim_win_get_position(win_getid('%'))`

### Actual behaviour
[0, 0] is echoed

### Expected behaviour
[2, 10] is echoed

**Comment by bfredl** [comment]
`nvim_win_get_position` is for main grid only. Use `nvim_win_get_config()` to get the configured position. In general the top-left position of a multigrid float cannot be known (it might have a different anchor, and a different font size, etc)

**Comment by akiyosi** [comment]
Thanks, I understood.
Closed.
