### ISSUE TITLE
E315 when creating a float with an invalid line address in "bufpos"

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#11948]
- `nvim --version`: NVIM v0.5.0-397-g96059d72e
 - `vim -u DEFAULTS` (version:  8.2 Included patches: 1-314) behaves differently? Not applicable
 - Operating system/version: Ubuntu 16.04.6 LTS
 - Terminal name/version: XTerm(322)
 - `$TERM`: xterm-256color

### Steps to reproduce

Run this shell command:

    echo 'x' >/tmp/file && nvim -u NONE +"call nvim_open_win(nvim_create_buf(0,1), 0, {'relative': 'win', 'bufpos': [1,0], 'row': 0, 'col': 0, 'height': 3, 'width': 10,})" /tmp/file

Press `yy` to yank the first line.
Press `p` to paste it.
Press `u` to undo the paste.

### Actual behaviour

`E315` is raised:

    E315: ml_get: invalid lnum: 2

### Expected behaviour

`E315` is not raised.

### Additional information

According to `:h E315`, it's an internal error which should be reported.

---

I think the issue is somehow linked to the fact that the topline of the float is originally set on an invalid address (i.e. it's greater than the the last line of the buffer).

---

I don't know much about floats, but something seems weird.

If I specify an invalid column position in `bufpos` (i.e. the line is too short), Nvim falls back on the last column of the line.

To illustrate:

    nvim -u NONE +"call nvim_open_win(nvim_create_buf(0,1), 0, {'relative': 'win', 'bufpos': [5,40], 'row': 0, 'col': 0, 'height': 3, 'width': 10,})" <(curl -Ls https://raw.githubusercontent.com/neovim/neovim/master/LICENSE)

This command opens a float whose first column is 26, even though the second argument in the `bufpos` list is 40.  That's because in the `LICENSE` file, on the line of index 5 (i.e. the sixth line), there are only 25 characters.

But if I specify an invalid line address in `bufpos` (the buffer is too short), it doesn't look like Nvim falls back on the last line of the buffer.

To illustrate:

    nvim -u NONE +"call nvim_open_win(nvim_create_buf(0,1), 0, {'relative': 'win', 'bufpos': [300,0], 'row': 0, 'col': 0, 'height': 3, 'width': 10,})" <(curl -Ls https://raw.githubusercontent.com/neovim/neovim/master/LICENSE)

Here the topline of the float is positioned on the line of index 300, which is invalid because the buffer contains only 281 lines.  Now, if I press `G` to jump at the end of the buffer, then keep pressing `C-e` to scroll the window downwards, the topline of the float does not seem to be anchored just after the last line of the buffer.  It keeps moving further away from it.

It seems inconsistent, but I may have misunderstood something.

Maybe the solution would be to make Nvim clamp up the invalid line address to the nearest value (i.e. the last line of the buffer), like it does with an invalid column.  Incidentally, it would probably prevent the float from jumping when pasting the line in the original MWE.

**Comment by bfredl** [comment]
yes, `bufpos` should improve to follow buffer changes (it should behave like an extmark).

**Comment by zeertzjq** [comment]
The ml_get error is fixed now, although not tested, as it is not clear what the correct behavior should be.
