### ISSUE TITLE
Remove strange tag

### ISSUE THREAD

**Issue by richin13** [neovim/neovim#11953]
- `nvim --version`: n/a
- `vim -u DEFAULTS` (version: ) behaves differently? n/a
- Operating system/version: n/a
- Terminal name/version: n/a
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

N/A

### Actual behaviour

This https://github.com/neovim/neovim/releases/tag/untagged-0e014f77944d8517d79f doesn't seem to follow the standard `vx.x.x` naming and or `stable`|`nightly`. Any particular reason is there?

I'm asking because https://github.com/richin13/asdf-neovim uses the tags to provide a list of all installable versions of neovim and this one will pose a challenge to the existing regex.

### Expected behaviour

n/a

**Comment by teto** [comment]
The tag looks kinda suspicious but can't you use "vX.X.X" as a regex ?

**Comment by teto** [comment]
I deleted the tag
