### ISSUE TITLE
LSP: Adding extra characters during auto-completion with ccls

### ISSUE THREAD

**Issue by Shatur95** [neovim/neovim#11966]
`nvim --version`:
```
NVIM v0.5.0-404-g49cd750d6
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/gena/.cache/yay/neovim-git/src/build/config -I/home/gena/.cache/yay/neovim-git/src/neovim/src -I/usr/include -I/home/gena/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/gena/.cache/yay/neovim-git/src/build/include

Features: +acl +iconv +tui
```
- Operating system/version: Arch Linux
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

### Steps to reproduce

1. Setup `nvim-lsp` for `ccls`:
```vim
:lua << EOF
  local nvim_lsp = require("nvim_lsp")
  nvim_lsp.ccls.setup{}
EOF
```

2. Open any C++ project with created `compile_commands.json` (for example, [akd](https://github.com/Shatur95/akd), contains only 4 C++ files).
3. Call omnifunc and try to complete any variable or function.

### Actual behaviour

[![asciicast](https://asciinema.org/a/oKlNTubysw3kdI16qUEvkfycV.svg)](https://asciinema.org/a/oKlNTubysw3kdI16qUEvkfycV)

### Expected behaviour

Insert only `daemon` and `exec()` words after their completion without their types.

**Comment by mfussenegger** [comment]
This will be fixed with https://github.com/neovim/neovim/pull/11989

**Comment by Shatur95** [comment]
Thank you!

**Comment by teto** [comment]
feature merged so this should be fixed.
