### ISSUE TITLE
inconsistent document and behaviour for encoding name aliases.

### ISSUE THREAD

**Issue by cyyever** [neovim/neovim#11960]
NVIM v0.5.0-nightly-7-g49cd750
Build type: Release
LuaJIT 2.1.0-beta3

The help document says "prc         simplified Chinese: on Unix "euc-cn", on MS-Windows cp936" for encoding name aliases. But I checked enc_alias_table from mbyte.c and found that "prc" is always an alias for "euc-cn". Then I checked vim source code and found that vim used the following code and adhered to the document.

> 

#if defined(MSWIN) || defined(WIN32UNIX) || defined(MACOS_X)
    {"japan",		IDX_CP932},
    {"korea",		IDX_CP949},
    {"prc",		IDX_CP936},
    {"chinese",		IDX_CP936},
    {"taiwan",		IDX_CP950},
    {"big5",		IDX_CP950},
#else
    {"japan",		IDX_EUC_JP},
    {"korea",		IDX_EUC_KR},
    {"prc",		IDX_EUC_CN},
    {"chinese",		IDX_EUC_CN},
    {"taiwan",		IDX_EUC_TW},
    {"cp950",		IDX_BIG5},
    {"950",		IDX_BIG5},
#endif

> 

### Expected behaviour
Either we should change the document or revert to the old vim alias table.

**Comment by bfredl** [comment]
What was the original reason to prefer different encodings on different platforms? Are these reasons still valid? (I suppose people are using UTF-8 for new text nowadays, but maybe it makes a difference for legacy applications).

**Comment by cyyever** [comment]
> 
> 
> What was the original reason to prefer different encodings on different platforms? Are these reasons still valid? (I suppose people are using UTF-8 for new text nowadays, but maybe it makes a difference for legacy applications).
 
  A simple (maybe incomplete ) answer is that the cp936 encoding used by windows is a superset of the euc-cn encoding used by unix , so it makes sense to differentiate the two cases.

**Comment by bfredl** [comment]
what does "superset" mean? that some bytepatterns are invalid in one encoding but are interpreted as chars in the other? but never that the same bytes can be interpreted as two different chars?

**Comment by cyyever** [comment]
> 
> 
> what does "superset" mean? that some bytepatterns are invalid in one encoding but are interpreted as chars in the other? but never that the same bytes can be interpreted as two different chars?

It means it is an extension of the other, it collects more characters while maintains the same byte patterns for the intersection .

**Comment by bfredl** [comment]
So it is always safe to use the superset encoding? Nvim aims at using the same (gnu) libiconv regardless of platform, so ideally encoding names should be interpreted the same.

**Comment by cyyever** [comment]
> 
> 
> So it is always safe to use the superset encoding? Nvim aims at using the same (gnu) libiconv regardless of platform, so ideally encoding names should be interpreted the same.
> Also, it would not surprise me if libiconv already treats them as synonyms.

Sorry for my misunderstanding, I just looked at the wiki and found that the two are the same in  (gnu) libiconv . Should we need to clarify this point in the document?

**Comment by bfredl** [comment]
yes, we should just remove the claim that different encoding is used on windows.

**Comment by justinmk** [comment]
added to https://github.com/neovim/neovim/pull/11708 . Also removed "unix only" phrase everywhere in mybte.txt.
