### ISSUE TITLE
New sections in markdown impossible to fold

### ISSUE THREAD

**Issue by jaroslawr** [neovim/neovim#11964]
I am using neovim 0.4.3, as shipping in debian testing right now. I run neovim without config, do `:let g:markdown_folding=1`, open `foo.md`, typing:

```
# Level 1
## Level 2
### Level 3
adsf adsf
```

Folding the sections does not work at all, no matter where the cursor is, until the file is reloaded. If I add a new section under "#### Level 4" after the file is reloaded, the new section again can not be folded.

**Comment by justinmk** [comment]
1. this is missing the info solicited by the issue template. Those fields are there for a reason, in particular it is useful to know if the problem exists in Vim (+specific version).
2. we don't maintain the runtime files. Send this to the author listed in the relevant file.

**Comment by jaroslawr** [comment]
I do not have this problem on the stock vim in Debian testing, 8.1.2269. I suspect this is a problem with the folding code and not with the vim markdown plugin.

**Comment by justinmk** [comment]
8.1.2269 is pretty recent, it definitely has  newer runtime files than Nvim 0.4.3.

**Comment by jaroslawr** [comment]
FWIW I tested the neovim prerelease build (`NVIM v0.5.0-404-g49cd750d6`, with my system neovim removed), I get the same behaviour.
