### ISSUE TITLE
Use CPack to enable easy generation of Debian and RPM packages

### ISSUE THREAD

**Issue by txk2048** [neovim/neovim#11978]
It might be worth making CPack files in the source tree to enable users to easily create their own binary packages.

See links to both:
[CPackDeb](https://cmake.org/cmake/help/v3.6/module/CPackDeb.html)
[CPackRPM](https://cmake.org/cmake/help/v3.7/module/CPackRPM.html)

**Comment by justinmk** [comment]
It sure would. PR welcome.

**Comment by Toothless204** [comment]
I have noticed that some of the relevant info is already at the end of the main CMakeLists.txt file at the project root.

I will start testing Debian/Ubuntu package creation as that is the primary system type I run, hopefully I'll be able to move on to testing RPM packages but help would be appreciated.

**Comment by dundargoc** [comment]
This is already possible now.
