### ISSUE TITLE
Text bleeds out from the left edge of the FZF buffer window

### ISSUE THREAD

**Issue by mechkb** [neovim/neovim#11970]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Ubuntu 18.04
- Terminal name/version: Mintty 3.1.0.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Trying Neovim for the first time. Noticed that when running FZF, text bleeds out of the left edge of the window while FZF works normally in vanilla VIM (see attached pics). Really hoping to find a fix for this problem to move to Neovim. The behavior can be replicated with Neovim with a clean config with just FZF.vim plugin installed via Vim Plug. I installed NVIM from here: https://github.com/neovim/neovim/releases/download/v0.4.3/nvim.appimage

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour (behavior observed in Neovim)

![image](https://user-images.githubusercontent.com/35608309/75644993-f5694780-5c09-11ea-8ff0-1795d12146c6.png)

### Expected behaviour (behavior of vanilla VIM)

![image](https://user-images.githubusercontent.com/35608309/75645031-1893f700-5c0a-11ea-84ac-014ef263e355.png)

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS.

**Comment by mechkb** [comment]
Tried `https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage` and still seeing the same issue. 

Can you tell me what bug this is a duplicate of so I can track that. Fix of this bug is gating my move to NVIM. Thanks.
