### ISSUE TITLE
Force nvim to use 16 colors

### ISSUE THREAD

**Issue by nylen** [neovim/neovim#11974]
I'd like to force `nvim` to use only the basic 16 ANSI colors, regardless of what it detects in the `TERM` or `COLORTERM` environment variables or wherever else it is looking. The reason is that I plan to use the same config on multiple machines, including various combinations of tmux, SSH, etc, and I will configure the actual color values in my terminal emulator.

The following code is the only place `t_colors` is set that I can see, and I can't find a way to override it:

https://github.com/neovim/neovim/blob/96059d72e539c0a23c1f7a24290f35247ff01749/src/nvim/tui/tui.c#L292-L293

In `vim` you can do this using: `set t_Co=16`

But in `nvim` this seems to have no effect (or crashes, see below).

I've also tried `TERM= COLORTERM= nvim` which doesn't change anything, nvim is still using 256 colors.

I can actually get a segfault by playing with this also, here are the steps:

1. Launch `nvim`
2. Run `:set t_Co=16`
3. Press Ctrl+Z to suspend
4. Type `fg` to resume
5. Observe `Segmentation fault` (without Step 2 this does not happen).

**Comment by nylen** [comment]
Some missing info above, though I don't think it'll be super relevant here:

- `nvim --version`: NVIM v0.4.3 - Build type: RelWithDebInfo
- `vim -u DEFAULTS` (version: 7.x, 8.0) behaves differently? - yes, `vim` allows setting `&t_Co` at runtime
- Operating system/version: Linux 5.3.0 x86_64 (Debian-based)
- Terminal name/version: xfce4-terminal v0.8.3
- `$TERM`: multiple values attempted, see first post

**Comment by justinmk** [comment]
> The reason is that I plan to use the same config on multiple machines, including various combinations of tmux, SSH, etc, 

 `t_Co=16` isn't needed for that. You can force your N/Vim colorscheme to use ANSI color indexes: 

    :highlight Comment ctermfg=Red

Then changing ANSI "red" to some other color in your terminal, will color comments as such. Note that this requires `:set notermguicolors`.

The `t_xx` inner-platform is not supported. `:help t_xx`

> and I will configure the actual color values in my terminal emulator.

Why is 16 colors important? Terminals can choose colors for 

> 5\. Observe `Segmentation fault` (without Step 2 this does not happen).

Is `set t_Co=16` required to repro that? If that happens with  the [development version](https://github.com/neovim/neovim/releases) please open a new report including a [backtrace](https://github.com/neovim/neovim/wiki/FAQ#backtrace-linux).

**Comment by nylen** [comment]
Thanks for the info. You tagged this issue as a duplicate, but I wasn't able to find anything that is really the same ("force downscaling to 16 colors") on a quick search.

I do see https://github.com/neovim/neovim/issues/5538 and https://github.com/neovim/neovim/issues/11883 which also discuss `t_Co` but not quite in the same way.

I will test this further and report back, including setting a 16-color scheme such as https://github.com/noahfrederick/vim-noctu or https://github.com/jeffkreeftmeijer/vim-dim, and trying to reproduce the segfault in the latest development version.

**Comment by emivespa** [comment]
@nylen you can emulate t_Co with `ffi`:  `:lua f=require"ffi" f.cdef"int t_colors" f.C.t_colors=16`, credit to @ seandewar from #neovim:matrix.org

**Comment by voskresenie** [comment]
> > The reason is that I plan to use the same config on multiple machines, including various combinations of tmux, SSH, etc,
> 
> `t_Co=16` isn't needed for that. You can force your N/Vim colorscheme to use ANSI color indexes:
> 
> ```
> :highlight Comment ctermfg=Red
> ```
> @justinmk 

There is a reason to force it, unfortunately. It's not a requirement to achieve the end product as an environment, but it is necessary in order to properly use color names in a colorscheme alongside the standard way of configuring a 16 color terminal.

https://github.com/neovim/neovim/blob/5792546777332361a9ac49107e46149c703de90e/src/nvim/highlight_group.c#L802-L849

Compiled into a table, you can see that if you have assigned your terminal colors to 0-15, as is standard for individual customization, 88-color and 256-color terminals will not all you to use all 16 of those colors, and you will be forced to either assign custom colors to higher indexes in your terminal, or reference these colors by name rather than index, which is a pain for both readability and portability (including as the consumer of colorschemes found online).
```
                    color_numbers_16[28]        color_numbers_88[28]        color_numbers_256[28]       color_numbers_8[28] 
Black:              0,                          0,                          0,                          0,                  
DarkBlue:           1,                          4,                          4,                          4,                  
DarkGreen:          2,                          2,                          2,                          2,                  
DarkCyan:           3,                          6,                          6,                          6,                  
DarkRed:            4,                          1,                          1,                          1,                  
DarkMagenta:        5,                          5,                          5,                          5,                  
Brown:              6,                          32,                         130,                        3,                  
DarkYellow:         6,                          72,                         3,                          3,                  
Gray:               7,                          84,                         248,                        7,                  
Grey:               7,                          84,                         248,                        7,                  
LightGray:          7,                          7,                          7,                          7,                  
LightGrey:          7,                          7,                          7,                          7,                  
DarkGray:           8,                          82,                         242,                        0 + 8,              
DarkGrey:           8,                          82,                         242,                        0 + 8,              
Blue:               9,                          12,                         12,                         4 + 8,              
LightBlue:          9,                          43,                         81,                         4 + 8,              
Green:              10,                         10,                         10,                         2 + 8,              
LightGreen:         10,                         61,                         121,                        2 + 8,              
Cyan:               11,                         14,                         14,                         6 + 8,              
LightCyan:          11,                         63,                         159,                        6 + 8,              
Red:                12,                         9,                          9,                          1 + 8,              
LightRed:           12,                         74,                         224,                        1 + 8,              
Magenta:            13,                         13,                         13,                         5 + 8,              
LightMagenta:       13,                         75,                         225,                        5 + 8,              
Yellow:             14,                         11,                         11,                         3 + 8,              
LightYellow:        14,                         78,                         229,                        3 + 8,              
White:              15,                         15,                         15,                         7 + 8,              
NONE                -1                          -1                          -1                          -1                  
Missing from 0-15:  {}                          {3, 8}                      {8}                         {}                  
```
I don't quite understand why these are configured this way, such that DarkGrey isn't taken from index 8 in 88-color and 256-color modes. I'd be happy to send out a PR to adjust, but I suspect this is intended behavior, although I'm not exactly sure what that intent would be.

My terminal is being recognized as 256-color (which it is), but this has unfortunately meant I cannot reference DarkGrey in any way other than the numeral 8 without forcing nvim to treat my term as 16-color. Given I already use sed to automatically convert from a template build my final colorscheme with cterm and gui colors, it's not a big hassle to work around, but it was rather confusing for a minute, since the other 15 standard names worked entirely as expected.

I'm grateful to @emivespa for the workaround, this has solved my problem / petty annoyance.
