### ISSUE TITLE
Using <Esc> to exit the command line does not work as expected

### ISSUE THREAD

**Issue by nylen** [neovim/neovim#11976]
- `nvim --version`: NVIM v0.4.3 - Build type: RelWithDebInfo
- `vim -u DEFAULTS` (version: 8.0) behaves differently? - vim exhibits part of this issue but not all. see "Behavior" below
- Operating system/version: Linux 5.3.0 x86_64 (Debian-based)
- Terminal name/version: xfce4-terminal v0.8.3
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:cnoremap <nowait> <Esc> <C-c>
: (open command line, then press Esc)
# note about 0.5 second delay before the <Esc> keypress takes effect
# also, type <Esc> and then any letter before the 0.5 second period
# in this case the <Esc> is canceled and the letter appears in the command line
```

(also try without the `cnoremap` line, it makes no difference in behavior)

### Behavior

When you type `<Esc>` to exit the command line there is a delay before the keypress takes effect, regardless of whether `cnoremap <nowait>` has been used to try to eliminate this delay. (This part is the same in vim.)

When you type `<Esc>` to exit the command line, quickly followed by another key such as a letter, the `<Esc>` keypress is canceled and the letter appears in the command line. (This part of the bug is new to neovim.)

### Expected behaviour

`cnoremap <nowait> <Esc> <C-c>` should make `<Esc>` take effect immediately.

`<Esc>` followed by a non-mapped character should exit the command line and pass the non-mapped character through to the editor.

**Comment by justinmk** [comment]
> When you type `<Esc>` to exit the command line, quickly followed by another key such as a letter, the `<Esc>` keypress is canceled and the letter appears in the command line. (This part of the bug is new to neovim.)

Not a bug.

You're observing accidental behaviors of two opposing approaches to handling ESC in a terminal. Nvim supports META/ALT mappings by default, Vim doesn't. What you've described here are just side effects of each approach.

https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed

**Comment by nylen** [comment]
Thanks for the additional info. Just wanted to confirm that this works and explains the issue I was having :+1:
