### ISSUE TITLE
Drawing or cursor position is strange with virtual text and "ambw=double"

### ISSUE THREAD

**Issue by h-michael** [neovim/neovim#11979]
- `nvim --version`:
```
~> nvim --version                                                                                           
NVIM v0.5.0-415-gf8f41d088
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 
Features: +acl +iconv +tui
```

- `vim -u DEFAULTS` (version: ) behaves differently?
Virtual text is only Nvim.

- Operating system/version:
`Linux arch 5.5.7-arch1-1 #1 SMP PREEMPT Sat, 29 Feb 2020 19:06:02 +0000 x86_64 GNU/Linux`

- Terminal name/version:
`alacritty 0.4.2-dev (f83d55f)`

- `$TERM`:
screen-256color

### Steps to reproduce using `nvim -u NORC`

```
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $HOME/.minimal_nvimrc
endif

call plug#begin('~/.vim/plugged')
Plug 'neovim/nvim-lsp'
call plug#end()
lua << EOF
  local os_getenv = vim.loop.os_getenv;
  require'nvim_lsp'.sumneko_lua.setup{
    cmd = {os_getenv('LUA_LSP_BIN'), "-E", os_getenv('LUA_LSP_DIR')..'/main.lua'};
    settings = {
      lua = {
        diagnostics = {
          enable = false
        };
      };
    };
  }
EOF
set ambw=double
```

`nvim -u NORC foo.lua`

typing
```
local vim = vim
```

### Actual behaviour
Drawing or cursor position is strange
![vtext](https://user-images.githubusercontent.com/4556097/75841209-7f82fd00-5e10-11ea-90bc-7ed6e2b8f79d.gif)
https://asciinema.org/a/307148

### Expected behaviour
Same as `ambw=single`

**Comment by bfredl** [comment]
seems "■" is ambiwidth. If your terminal renders ambiwith chars as single-width, then `ambiwith=single` should be used (nvim cannot force the terminal to behave one way or the other).

I think pre-0.3.2 the screen layer had some paranoia code which reset the cursor position after every ambiwith character. We could reimprement this in the TUI layer. (my plan in 0.3.2 was to "wait and see" if someone would be affected. I think this is the first such reported issue).

**Comment by h-michael** [comment]
> seems "■" is ambiwidth. If your terminal renders ambiwith chars as single-width, then ambiwith=single should be used (nvim cannot force the terminal to behave one way or the other).

I tried the same steps with iTerm and set Ambiguous characters are double width.
It worked as expected.

**Comment by h-michael** [comment]
@bfredl Should I close this issue because the ambiguous width of the terminal should be changed and it is not a Nvim issue?

**Comment by bfredl** [comment]
It is not an issue, unless people want the cursor restoration hack back (ambiwith chars will still look weird, but non-ambiwith chars will be put in the right place). It would incur an extra cost of each ambiwith char though.

**Comment by h-michael** [comment]
I've understood East Asia ambigous with problem.
I think Nvim don't need to have much hack to solve this.
Thank you for your response :)
