### ISSUE TITLE
support undercurls for TERM=kitty (and TERM=xterm-kitty)

### ISSUE THREAD

**Issue by gerion0** [neovim/neovim#11973]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? unknown, not relevant
- Operating system/version: Gentoo Linux
- Terminal name/version: Kitty 0.16.0
- `$TERM`: This is the source of the problem: "kitty" or "xterm-kitty"

### Actual behaviour
When using Kitty as terminal, it has the extra feature of curly underlines. This is supported in neovim (#7479, #9052).

For terminal, it is benefitial that their terminfo files are in the ncurses database. This is the case for kitty, too. Ncurses includes kitty since quite a time but not as "xterm-kitty" but only as "kitty" ([kitty bug](/kovidgoyal/kitty/issues/879), [ncurses file](https://invisible-island.net/ncurses/terminfo.src.html#toc-_Kitty)). I have ncurses 6.1 from 2019.06.09 ([gentoo package](https://packages.gentoo.org/packages/sys-libs/ncurses)), that includes this file.

When I now switch from "xterm-kitty" the "kitty" as TERM variable the undercurls are gone, but replaced by underlines.

### Expected behaviour
The undercurls are shown, regardless whether TERM is "kitty" or "xterm-kitty".

### Addtional info
I tried to patch neovim:
```
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 22f4501be..5440d743a 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -1523,7 +1523,8 @@ static void patch_terminfo_bugs(TUIData *data, const char *term,
   bool xterm = terminfo_is_term_family(term, "xterm")
     // Treat Terminal.app as generic xterm-like, for now.
     || nsterm;
-  bool kitty = terminfo_is_term_family(term, "xterm-kitty");
+  bool kitty = terminfo_is_term_family(term, "xterm-kitty")
+     || terminfo_is_term_family(term, "kitty");
   bool linuxvt = terminfo_is_term_family(term, "linux");
   bool bsdvt = terminfo_is_bsd_console(term);
   bool rxvt = terminfo_is_term_family(term, "rxvt");
```
However, this does not seem to affect the undercurl problem.

**Comment by teto** [comment]
I can confirm it's package under the kitty name with ncurses `6.1-20190112` too. Feel free to open up a PR, I will try locally.

**Comment by gerion0** [comment]
package? Do you mean fail?

I don't have a patch. The above mentioned patch does not work (this was also a wild guess, I grepped the source for "kitty", I don't know anything about the code base).

**Comment by blueyed** [comment]
Haven't investigated, but JFI: kitty itself $TERMINFO when installing it manually, and Arch Linux ships xterm-kitty in the kitty-terminfo package.

**Comment by blueyed** [comment]
@gerion0 check https://github.com/neovim/neovim/blob/78ec95ce7dc070899caf2b35f7058ba466fe7073/src/nvim/tui/tui.c#L1943

I.e. see if `TERM=kitty infocmp -x` contains `Su` - IIRC this is something that ncurses would not add, since it is a custom kitty extension.

**Comment by blueyed** [comment]
..it likely boils down to "kitty" in ncurses being different from "xterm-kitty" from Kitty itself?
(you can use `infocmp` to compare them, and/or diff the output from `infocmp -x`)

**Comment by gerion0** [comment]
> ..it likely boils down to "kitty" in ncurses being different from "xterm-kitty" from Kitty itself?

Yes, exactly that. The `Su` extension is not reported with `TERM=kitty`. Ok, so this is not a neovim but a ncurses problem.

> Haven't investigated, but JFI: kitty itself $TERMINFO when installing it manually, and Arch Linux ships xterm-kitty in the kitty-terminfo package.

Yes, that is also mentioned in the kitty bug (see first post). In short: Kitty provides its own terminfo package and recommends it. However, on machines that you ssh into from a kitty terminal that don't have this extra terminfo package installed your terminal is broken. Therefore a (correct) entry in the ncurses database would be better.
