### ISSUE TITLE
TeX syntax: Separate conceal settings from normal syntax

### ISSUE THREAD

**Issue by jrwrigh** [neovim/neovim#11984]
- `nvim --version`:
```
➜ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: Manjaro 18.1.5
- Terminal name/version: XFCE 0.8.9.1
- `$TERM`: `xterm-256color`

My suggestion would be to have the setting `g:tex_conceal='b'` to change only the concealing settings, not the text formatting settings. ie. I want to keep the text bolding and italicizing, but ignore not conceal the actual functions

### Without setting anything
![image](https://user-images.githubusercontent.com/20801821/76001866-fed10900-5ec2-11ea-9595-fd567a67597c.png)
The `\textbf` and `\textit` commands are hidden.

### Setting `let g:tex_conceal = 'b'`
![image](https://user-images.githubusercontent.com/20801821/76002900-810dfd00-5ec4-11ea-9eda-b85ac5e57377.png)
Same exact result as before (the other functionality of conceal has been eliminated as specified by the documentation).

### Setting `:set conceallevel=0`
![image](https://user-images.githubusercontent.com/20801821/76002801-6045a780-5ec4-11ea-9404-dbd2f4b98536.png)

The `\textbf` and `\textit` now appear while retaining the text bolding and italicizing.

---
The source file lines that needs to changed are [here](https://github.com/neovim/neovim/blob/a270c33b3a49d7a47b1bb6e6b9eb2073d98e0602/runtime/syntax/tex.vim#L381-L397).

Also, I'm not sure if y'all are still holding [this policy](https://github.com/neovim/neovim/issues/5703#issuecomment-265339301) or not (runtime files changes should come through maintainers, then through Vim, then get patched into neovim).

**Comment by justinmk** [comment]
> Also, I'm not sure if y'all are still holding [this policy](https://github.com/neovim/neovim/issues/5703#issuecomment-265339301) or not (runtime files changes should come through maintainers, then through Vim, then get patched into neovim).

indeed. Send it upstream.
