### ISSUE TITLE
Substitution with no change creates empty undo blocks

### ISSUE THREAD

**Issue by tweekmonster** [neovim/neovim#11987]
- `nvim --version`: v0.5.0-415-gf8f41d088
- `vim -u DEFAULTS` (version: 8.2.0357) behaves differently?  _Kind of_
- `git bisect` first bad commit: a9065a50518ef59351f9d0d32041a991a751653f

### Steps to reproduce using `nvim -u NORC`

In an empty buffer, run the following:

```
:set cmdheight=3
:enew
:1s/\s\+$//e | undolist
```

You should see the following printed

```
number changes  when               saved
     1       1  0 seconds ago
```

If you now type `@:@@@@@@` in normal mode to repeat the command a few times, the number will keep incrementing even though nothing has actually changed in the buffer.

Here's a one-liner that makes it easier to reproduce:

```
nvim -u NONE -i NONE +'set cmdheight=3' +'call nvim_input(":enew<cr>:1s/\s\+$//e | undolist<cr>@:" . repeat("@@", 20))'
```

`/e` is used to suppress the "no match" message, but doesn't stop empty undo blocks from being created when omitted.

### Actual behaviour

Creates empty undo blocks

### Expected behaviour

Don't create empty undo blocks

---

Vim does something similar, but I think might be technically correct.

Note that the pattern is `\s\+$`, which will result in no match.  However, `\s*$` would validly match the empty line and create an undo block.  This was pretty confusing at first because I was using an empty substitution, but the reason for creating an undo block in Vim is clearer if you used `:1s/\s*$/x/e` and repeat.

If empty undo blocks in general is considered a bug, a9065a50518ef59351f9d0d32041a991a751653f may have exposed an upstream bug.

**Comment by tomtomjhj** [comment]
I encountered a very weird behavior related to this.  A `:substitute` that doesn't even run still creates an empty undo block:
```vim
:if 0 | s/\s\+$//e | endif<CR>
```

**Comment by glacambre** [comment]
Can't reproduce on master :tada:.
