### ISSUE TITLE
Investigate "possibly lost" leak report by valgrind when doing a simple funciton extraction

### ISSUE THREAD

**Issue by tarruda** [neovim/neovim#1198]
While performing some changes in eval.c, I was getting a "possibly lost" memory leak report by valgrind. After some investigation, I've isolated the cause to this simple patch:

``` diff
diff --git a/src/nvim/eval.c b/src/nvim/eval.c
index a25aaf6..0775b8e 100644
--- a/src/nvim/eval.c
+++ b/src/nvim/eval.c
@@ -16863,6 +16863,11 @@ static char_u *find_option_end(char_u **arg, int *opt_flags)
   return p;
 }

+static inline void *ufunc_alloc(char_u *name)
+{
+  return xmalloc(sizeof(ufunc_T) + STRLEN(name));
+}
+
 /*
  * ":function"
  */
@@ -17373,7 +17378,7 @@ void ex_function(exarg_T *eap)
       }
     }

-    fp = xmalloc(sizeof(ufunc_T) + STRLEN(name));
+    fp = ufunc_alloc(name);

     if (fudi.fd_dict != NULL) {
       if (fudi.fd_di == NULL) {
```

Here is the report(api-python tests):

```
==20733== HEAP SUMMARY:
==20733==     in use at exit: 235,033 bytes in 1,420 blocks
==20733==   total heap usage: 46,465 allocs, 45,045 frees, 75,873,632 bytes allocated
==20733==
==20733== 182 bytes in 1 blocks are possibly lost in loss record 208 of 270
==20733==    at 0x4C2C857: malloc (vg_replace_malloc.c:291)
==20733==    by 0x53441C: try_malloc (memory.c:80)
==20733==    by 0x5344C7: xmalloc (memory.c:121)
==20733==    by 0x4FE727: ufunc_alloc (eval.c:16868)
==20733==    by 0x500175: ex_function (eval.c:17381)
==20733==    by 0x486993: do_one_cmd (ex_docmd.c:1905)
==20733==    by 0x483EFE: do_cmdline (ex_docmd.c:614)
==20733==    by 0x5263B2: nv_colon (normal.c:4075)
==20733==    by 0x51F97D: normal_cmd (normal.c:911)
==20733==    by 0x4C70D2: main_loop (main.c:751)
==20733==    by 0x4C6ACD: main (main.c:536)
==20733==
==20733== LEAK SUMMARY:
==20733==    definitely lost: 0 bytes in 0 blocks
==20733==    indirectly lost: 240 bytes in 10 blocks
==20733==      possibly lost: 182 bytes in 1 blocks
==20733==    still reachable: 233,621 bytes in 1,373 blocks
==20733==         suppressed: 990 bytes in 36 blocks
=
```

Valgrind documentation section about this :

> "possibly lost" means your program is leaking memory, unless you're doing unusual things with pointers that could cause them to point into the middle of an allocated block; see the user manual for some possible causes. Use --show-possibly-lost=no if you don't want to see these reports.

It seems that to save an extra call to malloc, this function allocates `sizeof ufunc_T + strlen(name)`. And since the last field in the ufunc_T structure is `uf_name`, the following `strcpy` uses allocated memory even though `uf_name`  has a size of 1. I don't know if this is considered "unusual things with pointers", but I still cannot see how a simple function extraction could be affected by it.

ping @aktau and @oni-link for help

**Comment by Pyrohh** [comment]
@tarruda is this relevant anymore?

**Comment by justinmk** [comment]
Code has changed drastically since then.
