### ISSUE TITLE
lsp: references/document symbols are using quickfix instead of loclist for their results

### ISSUE THREAD

**Issue by urandom** [neovim/neovim#11983]
- `nvim --version`:
<pre>
NVIM v0.5.0-f8f41d0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200305-66585-1aiv5ob/build/config -I/tmp/neovim-20200305-66585-1aiv5ob/src -I/usr/local/include -I/tmp/neovim-20200305-66585-1aiv5ob/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200305-66585-1aiv5ob/build/src/nvim/auto -I/tmp/neovim-20200305-66585-1aiv5ob/build/include
Compiled by viktor.kojouharov@Viktors-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-f8f41d0/share/nvim"

Run :checkhealth for more info
</pre>

Currently, both references (vim.lsp.buf.references()) and document symbols (vim.lsp.buf.document_symbol()) are using the quickfix window to display their results. That seems semantically wrong. It also interferes with other usages of the quickfix, like showing the diagnostics there, and the diagnostics will remove any reference/symbol results.

FYI: with the current nightly, calling vim.lsp.buf.references() no longer opens the quickfix window.

**Comment by mfussenegger** [comment]
I think the current behavior should be kept and makes sense.

> It also interferes with other usages of the quickfix, like showing the diagnostics there, and the diagnostics will remove any reference/symbol results.

If you show the diagnostics in the quickfix list, then you break pretty much all other commands which use the quickfix list (like `:grep`) because of the frequency with which language servers publish diagnostics. They end up overriding anything else.

It's imho better to show the diagnostics in the location list and keep quickfix for references and the other commands.

**Comment by teto** [comment]
you can override the callback in your config  (defaults are in `runtime/lua/vim/lsp/callbacks.lua`)
e.g., replace set_qflist with set_loclist in the following
```
M['textDocument/references'] = function(_, _, result)
  if not result then return end
  util.set_qflist(util.locations_to_items(result))
end
```
For instance add a ~/.config/nvim/init.lua you can load from your init.vim via `luafile init.lua`
and init.lua:
```
vim.lsp.callbacks['textDocument/references'] =  function(_, _, result)
  if not result then return end
  vim.lsp.util.set_loclist(util.locations_to_items(result))
end
```

**Comment by mfussenegger** [comment]
I think this can be closed. The "better" behavior is subject to preference and neovim needs to default to one. The current choice isn't really wrong given that quickfix is often used for information that can spawn multiple windows/buffers and location list is often used for information that affects only the current window/buffer

The behavior can be changed by overriding the handlers as explained in the previous comment and there are plenty of plugins who extend the functionality (lspsaga, lsputils, telescope and so on)
