### ISSUE TITLE
get cterm color value

### ISSUE THREAD

**Issue by Kyle-Thompson** [neovim/neovim#11986]
Currently all my colors are defined through Xresources and being set in vim through `ctermfg=2` for example. Lately there have been many improvements that rely on termguicolors being enabled (pumblend for example) that I can't use since I set my colors through cterm. Is there either a way currently or any chance of implementing a way to query the value of what `ctermfg=2` would be set to so I can assign it to guifg and then use termguicolors. This way my colors can still be defined through Xresources and I'd be able to use all the termguicolors dependent features as well.

Thanks!

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
