### ISSUE TITLE
Paste bug inside Cmder, cannot quit neovim.

### ISSUE THREAD

**Issue by Moret84** [neovim/neovim#11991]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: 8.2 with patches 1-148) behaves differently? Yes work as expected.
- Operating system/version: Windows 10 / WSL Arch Linux
- Terminal name/version: Cmder 180626
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Copy a text from outside the terminal

```
nvim -u NORC
Type i to go into insert mode.
Type Shift+Ins or Ins (Cmder shortcuts) to paste the copied text

```

### Actual behaviour

![Capture](https://user-images.githubusercontent.com/7255460/76141208-4d68d980-6062-11ea-91cd-9ec10d2bf412.PNG)

The paste randomly works but most often it ends up with strange characters (see picture). After pasting, I can't do anything other than typing regular characters. Any special key such as Esc, Ctrl-C results in weird characters typed in neovim and I can't exit it.

### Expected behaviour

Paste works, no weird character, juste my copied text.

**Comment by dm1try** [comment]
looks like related to https://github.com/neovim/neovim/issues/11699

**Comment by Moret84** [comment]
Yeah same symptoms.
I just updated ConEmu to preview 191012.
Pasting still triggers strange characters, but typing special key does not write weird characters anymore and as a result I can now quit neovim.

**Comment by iamjesper** [comment]
try latest master now that #12004 was merged.

**Comment by levirs565** [comment]
To paste a text use `"+p` instead of paste from terminal emulator.

**Comment by Moret84** [comment]
Sorry for late response. I can not reproduce anymore.
