### ISSUE TITLE
Split Panes Broken Under Screen (With Unibilium 2.1)

### ISSUE THREAD

**Issue by janneronkko** [neovim/neovim#11998]
- `nvim --version`:
```NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- vim works with `-u DEFAULTS` and with same settings I'm running nvim

- `nvim -u DEFAULTS` does also work incorrectly

```vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
Included patches: 1-343
Compiled by Arch Linux
```

- Operating system/version: Archlinux (updated March 9th 2020)
- Terminal name/version: Konsole 19.12.3
- `$TERM`: `screen.xterm-256color` (works outside screen when TERM is `xterm-256color`)

Also works in text mode (outside X)

### Steps to reproduce using `nvim -u NORC`

```
screen nvim -u NORC <path to file containing multiple screens of text>
:vs  
ctrl+d
ctrl+d
```

### Actual behaviour

The split pane contents become hidden

### Expected behaviour

Both split panes show contents

**Comment by jannero** [comment]
This might also be a regression issue in Unibilium 2.1 (vs. 2.0)

**Comment by jannero** [comment]
Screen capture is available from http://jroo.kapsi.fi/neovim_screen_unibilium-2020-03-09_13.41.14.mp4

**Comment by erw7** [comment]
@jannero Does #12005 solve your problem? I think this problem is due to `smglr` as well as #10562. Looking at `termcap.c` of gnu screen, `D_ML` is not used, so I think screen doesn't have `smglr`.

**Comment by jannero** [comment]
When I'm building neovim myself the scrolling is broken under screen even when I use unibilium 2.0.

I tested with commit b99dad7b4c6418978a21977262809021fab8d356 (v0.4.3) and the latest commit from master (2b00d1d09c0ff7ee6cc2de7ba70d9e84167540e5)

I built neovim by running `make` and then ran neovim from build/bin directory.

**Comment by jannero** [comment]
And that is probably because a static unibilium library built by neovim's build is used.

I also tested the commit from #12005 (8b64a77144a87fbc9efe5535979ac612dc8e1f1b) and scrolling was still broken.

**Comment by erw7** [comment]
`terminfo_is_term_family("screen.xterm-256color", "screen")` did not return `true`. Therefore, the change in https://github.com/neovim/neovim/commit/8b64a77144a87fbc9efe5535979ac612dc8e1f1b did not disable `smglr`. Please try it because it was corrected in https://github.com/neovim/neovim/pull/12005/commits/c2d288e293a8fa8acba72d73a825213b8a1d280c.

**Comment by jannero** [comment]
c2d288e293a8fa8acba72d73a825213b8a1d280c fixes the issue

Thanks for the quick fix :)
