### ISSUE TITLE
How would I setlocal window options for a floating window?

### ISSUE THREAD

**Issue by nathanblair** [neovim/neovim#11992]
For instance, I can set window options for a preview window using something like
```
autocmd BufWinEnter * if &previewwindow | setlocal wrap | endif
```

Is there a flag set to id a floating window? I would like to be able to change the window's folding options to be different from those in my global config. Additionally, maybe set a default width by executing a `wincmd`?

I've looked at #10081 - this addresses if the user is running nvim_open_win(); My particular case is when another plugin (coc) is opening the floating window with one of its functions (ShowHover or similar).

**Comment by dm1try** [comment]
try

```
nvim_win_get_config(0)['relative'] != ''
```

I use the same condition [here]( https://github.com/dm1try/golden_size/blob/29c2543f48392dd80fcca07cce026a60c3e6ed22/lua/golden_size/init.lua#L10)

based on knowledge from `h api-floatwin`

**Comment by dundargoc** [comment]
Is there anything else needed here? It seems like it's been solved. I'll close it for now, let me know if there's still work needed here.
