### ISSUE TITLE
syntax error causes "| endif" to be silently ignored

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#12009]
- `nvim --version`: NVIM v0.5.0-416-g2b00d1d09
 - `vim -u DEFAULTS` (version:  8.2 Included patches: 1-373) behaves differently? Yes
 - Operating system/version: Ubuntu 16.04.6 LTS
 - Terminal name/version: XTerm(322)
 - `$TERM`: xterm-256color

### Steps to reproduce

Write this code in `/tmp/test.vim`:

    let files = ['/tmp/do_NOT_delete_me', '/tmp/delete_me']
    call system('touch '..join(files))
    if 1
        if !has('nvim') | let x = files->len() | endif
        call filter(files, 'v:val !~# "NOT"')
    endif
    call delete(files[0])
    if 1
        finish
    endif

Start Nvim with this shell command:

    nvim -u NONE -S /tmp/test.vim

### Actual behaviour

The file `/tmp/do_NOT_delete_me` is deleted, but not `/tmp/delete_me`.

### Expected behaviour

The file `/tmp/do_NOT_delete_me` is not deleted, but `/tmp/delete_me` is.

### Additional information

I think Nvim fails to parse the method call operator `->` in this line (since [8.1.1803](https://github.com/vim/vim/releases/tag/v8.1.1803) and related patches have not been ported yet):

    if !has('nvim') | let x = files->len() | endif
                                   ^^

Because of this, it probably ignores everything afterward, including the `endif` at the end of the line.
But the `if` at the start of the line needs to be terminated by an `endif`, so Nvim keeps looking and finds another one 2 lines below:

    if 1
        if !has('nvim') | let x = files->len() | endif
        call filter(files, 'v:val !~# "NOT"')
    endif
    ^^^^^

That's wrong; this `endif` matches the `if` in the previous `if 1`, not the `if` in `if !has('nvim')`.
Because of that, the `filter()` line is silently skipped, since we are in Nvim and `!has('nvim')` is false.

**Comment by lacygoill** [comment]
The issue is not specific to `->` though; I think any wrong syntax would cause the same issue.
But usually, a wrong syntax would raise an error, be it in Vim or in Nvim. So, you would quickly notice it and fix it.  Here the code does not raise any error, neither in Vim nor in Nvim; so I thought it was worth being reported.

One solution is to use `:exe`:

    if !has('nvim') | exe 'let x = files->len()' | endif
                      ^^^

Or break the line:

    if !has('nvim') | exe 'let x = files->len()'
    endif

But that requires that you are aware of the pitfall in advance.

**Comment by bfredl** [comment]
`if v:false | let x = ) | endif` has the same issue in vim 8 (endif is silently ignored, no syntax error).

Cc @brammool

**Comment by brammool** [comment]
Consider this:
   if has('nothing') | let x = doesnotexist | endif
Here you do not want to give an error for "doesnotexist".
May conditions with has() depend on this.
Obviously, this doesn't work very well for a syntax error.  But it's hard to make a difference.
And the example for using "->" also shows that you do want to skip expressions, and errors in expressions, in a version of Vim that doesn't support that.

So, we can only document that the "endif" should be on a separate line.

**Comment by lacygoill** [comment]
Thank you very much for the explanation; closing, since it's [now documented](https://github.com/vim/vim/blob/b17893aa940dc7d45421f875f5d90855880aad27/runtime/doc/eval.txt#L5834-L5842) and thus to be expected.
