### ISSUE TITLE
`:pythonx` gives E492: Not an editor command: pythonx

### ISSUE THREAD

**Issue by galou** [neovim/neovim#12001]
- `nvim --version`: NVIM v0.3.8
- `vim -u DEFAULTS` (version: ) behaves differently? `vim -u NONE` behaves the same, `vim -u DEFAULTS` gives `E282: Cannot read from "DEFAULTS"`.
- Operating system/version: Ubuntu 18.04.4
- Terminal name/version: `GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2`
- `$TERM`: `xterm-256color`
- `:checkhealth provider`:

```
## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.17
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.6.9
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.
```

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
:pythonx<CR>
```

### Actual behaviour

Gives `E492: Not an editor command: pythonx`.

### Expected behaviour

Should give something like `E471: Argument required`, I guess.

**Comment by Shougo** [comment]
pythonx is not supported in neovim.

**Comment by galou** [comment]
Understood, thanks for the quick answer. I was confused by the presence of the `provider/pythonx.vim` file.

How can I add the `pythonx` command manually? Some plugins use it. Thanks!

**Comment by lacygoill** [comment]
`:pythonx` works on my machine (`NVIM v0.5.0-416-g2b00d1d09`), try to upgrade Nvim to at least 0.4.0.

**Comment by galou** [comment]
That solved my issue. I installed Neovim from https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable.

Thanks!
