### ISSUE TITLE
Inconsistent behavirou between LineNr and CursorLineNr

### ISSUE THREAD

**Issue by fekir** [neovim/neovim#12002]
- `nvim --version`:
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-xAEA75/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-xAEA75/neovim-0.4.3/build/config -I/build/neovim-xAEA75/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-xAEA75/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-xAEA75/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

Also tested with appimage, version v0.4.3

- `vim -u DEFAULTS` (version: ) behaves differently?
no

- Operating system/version:
debian

- Terminal name/version:
- `$TERM`: screen-256color

### Steps to reproduce and actual behavirou

```
# current line is bold and blue
VIMINIT='highlight clear CursorLine | highlight CursorLineNr cterm=bold ctermfg=012 | set number relativenumber' nvim
VIMINIT='highlight clear CursorLine | highlight CursorLineNr cterm=bold ctermfg=012 | set number cursorline' nvim

#every line is bold and blue
VIMINIT='highlight LineNr cterm=bold ctermfg=012 | set number' nvim

# every line except current line is bold and blue
VIMINIT='highlight LineNr cterm=bold ctermfg=012 | set relativenumber' nvim
VIMINIT='highlight LineNr cterm=bold ctermfg=012 | set number relativenumber' nvim
```

### Expected behaviour

From the help

```
LineNr
Line number for ":number" and ":#" commands, and when 'number' or 'relativenumber' option is set.

CursorLineNr
Like LineNr when 'cursorline' or 'relativenumber' is set for the cursor line.
```

Thus it seems that highlight LineNr should apply only to the current line, like CursorLineNr (or the opposite), but they behave differently.

I would actually like to apply the theming only on the current line, but without using cursorline. This does not seem to be possible AFAIK.

**Comment by glacambre** [comment]
No, `LineNr` applies to all numbers and `CursorLineNr` applies to the line number of the line the cursor is on. This doesn't seem inconsistent and matches the documented behavior.

>I would actually like to apply the theming only on the current line, but without using cursorline.

`CursorLineNr` works without enabling `'cursorline'`.

I'm going to close this issue but feel free to reply if you think I'm wrong/have more questions :)
.

**Comment by fekir** [comment]
Hello @glacambre , thank you for clarifying, and I can confirm what you said about enabling `'cursorline'`.

At the time of writing this bug I surely had more question, as I was trying to achieve something.
Unfortunately I cannot remember what :-P
