### ISSUE TITLE
nvim-win64.zip contain 32bit vcruntime140.dll

### ISSUE THREAD

**Issue by url-jf** [neovim/neovim#12006]
- `nvim --version`: NVIM v0.4.3
- Operating system/version: Windows 7 Pro 64 bit

### Actual behaviour
nvim.exe does not start

**Comment by glacambre** [comment]
I'm not seeing this file in the zip file for the nightly release so I'm going to assume this has been fixed.

@url-jf let me know if I missed something and I'll re-open :)
