### ISSUE TITLE
Remaping n breaks foldopen option

### ISSUE THREAD

**Issue by jlesquembre** [neovim/neovim#12000]
- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/id1h353l8ql2lhby04mzglnmng46b5px-neovim-unwrapped-0.4.3/share/nvim
"
```

- `vim -u DEFAULTS` (version: 8.2.13) behaves differently?
No
- Operating system/version:
 NixOS 20.03
- Terminal name/version:
kitty 0.16.0
- `$TERM`:
xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Given this file, called it `test.txt`:
```
foo
bar

" Fold one  {{{1

foo
foo
bar
bar

" Fold two  {{{1

foo
foo
bar
bar
```
Start neovim with:
```bash
nvim -u NORC -c "set foldmethod=marker" test.txt
```
if you search for foo (`/foo`), and press `n`, the folds are automatically opened, as expected with the default `foldopen` option

But if you add this map (taken from https://github.com/mhinz/vim-galore#saner-behavior-of-n-and-n):
```viml
nnoremap <expr> n 'Nn'[v:searchforward]
```
folds are not opened

### Actual behaviour

Folds are not automatically opened if `n` is remapped, even with `set foldopen=search` 

### Expected behaviour

Folds are automatically opened

**Comment by lacygoill** [comment]
This is intended and documented at `:h 'foldopen`:

> NOTE: When the command is part of a mapping this option is not used.
> Add the |zv| command to the mapping to get the same effect.
> (rationale: the mapping may want to control opening folds itself)

If you want folds to be opened automatically, include `zv` in the rhs of the mapping:

    nnoremap <expr> n 'Nn'[v:searchforward]..'zv'
                                              ^^

**Comment by jlesquembre** [comment]
You are right, thanks @lacygoill, next time I'll read the documentation more carefully
