### ISSUE TITLE
How to make the cursor blink in insert mode?

### ISSUE THREAD

**Issue by catzybluphish** [neovim/neovim#12011]
- `nvim --version`: 0.4.3
- Operating system/version: Arch Linux
- Terminal name/version: rxvt-unicode 9.22 (daemon mode)
- `$TERM`: rxvt-unicode-256color

### Actual behaviour
In insert mode, the cursor stops blinking. Command mode blinks the cursor normally. IIRC, blinking for both modes used to work, but recently I've noticed it not. I have the following in my init.vim:
```
" enable cursor blinking
set guicursor=a:blinkon1

" enable vertical cursor when in insert mode
set guicursor=i:ver1
```
### Expected behaviour
The cursor blinking in insert mode instead of only command mode.

**Comment by lacygoill** [comment]
Move the `a:blinkon1` item after `i:ver1`, and append the item to the current value of `'guicursor'` instead of overwriting it:

    " enable vertical cursor when in insert mode
    set guicursor=i:ver1

    " enable cursor blinking
    set guicursor+=a:blinkon1
                 ^^
                 append

**Comment by NGPONG** [comment]
> Move the `a:blinkon1` item after `i:ver1`, and append the item to the current value of `'guicursor'` instead of overwriting it:
> 
> ```
> " enable vertical cursor when in insert mode
> set guicursor=i:ver1
> 
> " enable cursor blinking
> set guicursor+=a:blinkon1
>              ^^
>              append
> ```

Not work for me, Does anyone have another soultion?

**Comment by DarylPinto** [comment]
> Not work for me, Does anyone have another soultion?

Try the following in your `init.lua`:
```lua
vim.o.guicursor = table.concat({
  "n-v-c:block-Cursor/lCursor-blinkwait1000-blinkon100-blinkoff100",
  "i-ci:ver25-Cursor/lCursor-blinkwait1000-blinkon100-blinkoff100",
  "r:hor50-Cursor/lCursor-blinkwait100-blinkon100-blinkoff100"
}, ",")

```

<a href="https://neovim.io/doc/user/options.html#'gcr'">See here</a> for more information.

**Comment by Zhou-Yicheng** [comment]
@DarylPinto this also work
```lua
vim.opt.guicursor = {
  'n-v-c:block-Cursor/lCursor-blinkwait1000-blinkon100-blinkoff100',
  'i-ci:ver25-Cursor/lCursor-blinkwait1000-blinkon100-blinkoff100',
  'r:hor50-Cursor/lCursor-blinkwait100-blinkon100-blinkoff100'
}
```

**Comment by caseycronyn** [comment]
> " enable cursor blinking
> set guicursor+=a:blinkon1
>              ^^
>              append
> ```

I think this could be added to the documentation for clarity. There is no guidance for how to turn cursor blinking on in `:h cursor-blinking`, only that it is set to off by default in all modes and that the time is set in milliseconds.
