### ISSUE TITLE
Selection stuck in Normal mode after :copy run in Visual mode.

### ISSUE THREAD

**Issue by iovuio** [neovim/neovim#12022]
- `nvim --version`:
NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
VIM - Vi IMproved 8.0 behaves **the same**
- Operating system/version:
windows 10, WSL1 ubuntu 18.04.4 
- Terminal name/version:
Windows Terminal
- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`
1. Place following lines in buffer
```
one
two
three
four
five
```
2. Select lines 3 and  4 (`:3<Ret>Vj<Ret>`)
3. Copy using Ex command (`:'<,'>t0<Ret>) -> Visual mode exited, you're now in Normal mode

### Actual behaviour
Selection of lines 3 and 4 still displayed. Because you're already in Normal mode, hitting <Esc> will not help getting rid of selection.

### Expected behaviour
Selection of lines 3 and 4 no longer displayed. 

Why is this expected behavior? 
Selection only displayed if in a form of Visual mode (character, line, block). E.g. <Esc> will result in Normal mode -- selection gone. Or, `y` will yank the selection and transition to Normal mode -- selection gone.

In this particular example the mode transition from Visual to Normal is done via an Ex command.
There is another Ex command for which the selection is properly cleaned up -- :move.

So the general rule is: No selection displayed when in Normal mode. The above use case deviates from that rule and is a bug.

**Comment by dundargoc** [comment]
This has been fixed in https://github.com/neovim/neovim/pull/17864. Curiously enough the bug still exists in vim despite being the solution being a vim-patch.

**Comment by zeertzjq** [comment]
This bug exists in Vim v8.2.4464, but not in v8.2.4651, so it has been fixed.

**Comment by dundargoc** [comment]
Good catch. Thanks.
