### ISSUE TITLE
Cursor moving in window on search with word boundary

### ISSUE THREAD

**Issue by iovuio** [neovim/neovim#12024]
- `nvim --version`:
NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
VIM - Vi IMproved 8.0 behaves differently, as expected
- Operating system/version:
windows 10, WSL1 ubuntu 18.04.4
- Terminal name/version:
Windows Terminal 0.10
- `$TERM`:
 xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Place following line in buffer
```
one two three
```
2. Place cursor on second word (`6|`)
3. Do search with left word boundary `/\<<C-r><C-w>`

### Actual behaviour

<C-r><C-w> inserts word *three*

### Expected behaviour

<C-r><C-w> inserts word *two*

### Note
You can see the cursor moving to the beginning of next word immediately after you type `/\<`. The cursor returns to the correct position after search is complete. So the position is wrong only during search.

**Comment by erw7** [comment]
This behavior when `incsearch` is set is probably not a bug and is correct. You need to `:set noincsearch` to get the behavior you want. The vim help says (`:h 'incsearch'`):

> Note that the match will be shown, but the cursor will return to its original position when no match is found and when pressing <Esc>.  You

I checked with vim `8.0.1453` and `8.2.194`, but in the case of `vim -u DEFAULTS`, it works the same as `neovim` (`vim -u NORC` will do what you want).

**Comment by iovuio** [comment]
Thank you @erw7,
makes sense now.

Closing issue.
