### ISSUE TITLE
Adding symbols for nightly

### ISSUE THREAD

**Issue by eyalk5** [neovim/neovim#12035]
Even if it is a release, it would still be nice to have symbols for debugging.
It is just another flag when compiling and it seems helpful in case of crash dump. 
In other words, change build type to RelWithDebInfo

**Comment by sladyn98** [comment]
I could take a look at this if it is a first time issue to take on :)

**Comment by tjdevries** [comment]
@sladyn98 I don't really know anything the build systems, but if you make a PR I will investigate it. Just tag me in it

**Comment by justinmk** [comment]
> In other words, change build type to RelWithDebInfo

that is already the case for Linux: https://github.com/neovim/bot-ci/blob/50ad5a69ae3047de2e2e3b5ca6e6f5718ad9e01d/ci/nightly.sh#L33

where are you getting the nightly? Linux appimage at https://github.com/neovim/neovim/releases should have symbols already.

**Comment by eyalk5** [comment]
I am on macos

**Comment by justinmk** [comment]
not sure if something changed, but Release was chosen on macOS because it somehow _does_ still provide symbols. 

- see https://github.com/neovim/homebrew-neovim/issues/115#issuecomment-310916268
- also for reference https://github.com/rust-lang/rust/issues/24346#issuecomment-170054857

**Comment by eyalk5** [comment]
So possibly I should have done something with lldb . Or it is really strange.

**Comment by eyalk5** [comment]
There was probably a misunderstanding. As far as I understand, it does contain basic symbols. However, as witnessed here https://github.com/neovim/neovim/issues/12613, the symbols don't provide enough -> exact lines and extended data. I find it hard to believe that LLVB ignores some debug data.

**Comment by eyalk11** [comment]
Those are called `public symbols`. I noticed it this time in windows.

https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/public-symbols-and-private-symbols

> Some basic symbols, such as function names and global variables, are needed for even the most rudimentary debugging. These are called public symbols. Symbols such as data structure names, global variables visible in only one object file, local variables, and line number information are not always required for debugging, although they are useful for a more in-depth debugging session. These are called private symbols.

> A symbol file that contains both private and public symbols is called a full symbol file. A symbol file that contains public symbols alone is called a stripped symbol file.
