### ISSUE TITLE
nvim trigger CursorMoved before BufEnter

### ISSUE THREAD

**Issue by SolaWing** [neovim/neovim#12031]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? NO
- Operating system/version: MAC OS 15.3
- Terminal name/version: system terminal
- `$TERM`: fish

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:help
<C-w><Shift-T> " move to new tab
:autocmd BufEnter * echom 'enter'
:autocmd CursorMoved * echom 'moved'
gt
```

### Actual behaviour
Observed moved before enter

### Expected behaviour
enter should trigger before moved

### Other Test
when switch window, bufenter will trigger first, then moved. seems ok.

### Other Link
https://github.com/SirVer/ultisnips/issues/1189

**Comment by rwmpelstilzchen** [comment]
The problem seems to persist in Neovim 0.5.0. The bug it causes with UltiSnips makes UltiSnips+Neovim combination unusable.
