### ISSUE TITLE
Control+Shift+Key mapping overwrites Control+Key mapping

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#12037]
First, sorry if this is a duplicate, I'm pretty sure I've read issues about this before but I couldn't find them with the keywords I tried.

- `nvim --version`: NVIM v0.5.0-418-g87d892afa 

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:nnoremap <C-w> aa
:nnoremap <C-S-w> ab
:call nvim_input("<C-w>")
```

### Actual behaviour
`b` is inserted.

### Expected behaviour
`a` is inserted.

I understand that it's impossible to tell the difference between control + shift + key and control + key in a terminal, but GUIs are perfectly able to do that, so I believe neovim should not overwrite ctrl + key mappings with ctrl + shift + key mappings.

**Comment by lifecontd** [comment]
Also can we have Alt modifier support as well?? To distinguish between <C-v> <A-C-v> <A-C-S-v> (for e.g.)?

**Comment by glacambre** [comment]
Thanks a lot for fixing this @jamessan!
