### ISSUE TITLE
:term doesn't respect $SHELL variable set from inside of neovim

### ISSUE THREAD

**Issue by I60R** [neovim/neovim#12039]
- `nvim --version`: v0.5.0-418-g87d892afa
- `vim -u DEFAULTS` (version: 8.2) behaves differently?: no
- Operating system/version: 5.5.7-1-MANJARO 
- Terminal name/version: alacritty 0.4.2-dev
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
SHELL=/bin/bash nvim -u NORC
:let $SHELL = "/bin/zsh"
:term
```

### Actual behaviour

Spawns bash

### Expected behaviour

Spawns zsh

**Comment by I60R** [comment]
My use case for this: in my neovim client i need :term buffer without any command running inside, especially bash/zsh because they might load plugins that might slow down :term buffer creation.

So, I could backup $SHELL and set it to something dummy e.g. `/bin/sleep 10000000d` then spawn `:term` and after that restore its original value

**Comment by erw7** [comment]
In the case of your use case, can't you substitute `set shell=...` or `termopen(['/bin/sleep', '10000000d'])`? If the `{cmd}` passed to `termopen()` is a list, it will be executed directly and the shell will not be used.

**Comment by I60R** [comment]
This works, thank you!
