### ISSUE TITLE
Hightlight during replacement

### ISSUE THREAD

**Issue by Ni1fheim** [neovim/neovim#12034]
- `nvim --version`: 0.4.3
- Operating system/version: Arch Linux
- Terminal name/version: zsh 5.8
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Text is automatically highlighted when just using `/` searching, but this feature is not available when using `:%s/pattern/replace_string` replacement.

### Actual behaviour

No text highlighting in match pattern when using `:s/pattern/replace`

### Expected behaviour

Text can also be highlighted when using replacement, this feature is available in vim8.

**Comment by bfredl** [comment]
did you try `set inccommand=split` (or `nosplit`) ?

**Comment by Ni1fheim** [comment]
> set inccommand=split

Thank you! It worked.
