### ISSUE TITLE
Lua stdlib: vim.g should use new conversion rules

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#12048]
- `nvim --version`: NVIM v0.5.0-418-g87d892afa
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: macos
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

1. nvim -u NORC
2. :let g:WWW ={}
3. :lua print(vim.inspect(vim.g['WWW']))

### Actual behaviour
{                                                                                                                       
  [true] = 6                                                                                                            
} 
### Expected behaviour
{}

**Comment by bfredl** [comment]
Right, `vim.g` uses `vim.api` which still uses the "old" conversion semantics. I'm tempted to just switch over `vim.api` to use the "new" rules, though I don't know how much existing plugins that will break (probably too much).

**Comment by teto** [comment]
where/when were those rules introduced ?

**Comment by bfredl** [comment]
Gradually. First untagged floats https://github.com/neovim/neovim/pull/10389 , then a proper NIL value in https://github.com/neovim/neovim/pull/11310, and finally empty dict in https://github.com/neovim/neovim/pull/11470 .

**Comment by LoricAndre** [comment]
Is there a workaround for this ? Float arithmetic seems to be quite buggy with vim.g in lua (`floor` on a float returns an error).
