### ISSUE TITLE
Autocommands not triggered anymore

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#12041]
- `nvim --version`: NVIM v0.5.0-418-g87d892afa
- `vim -u DEFAULTS` (version: ) behaves differently? Yes - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 23 2020 08:34:29) Included patches: 1-430
- Operating system/version: Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 GNU/Linux

### Steps to reproduce using `nvim -u NORC`

Use the following init.vim:
```vim
autocmd BufRead * echom "BufRead"
autocmd BufReadPost * echom "BufReadPost"
autocmd BufNewFile * echom "BufNewFile"
```

```
nvim -u init.vim
:e init.vim
```

### Actual behaviour
Nothing is printed.

### Expected behaviour
`BufRead` and `BufReadPost` are printed.

**Comment by erw7** [comment]
This is because `F` is included in default of `shortmess` in neovim, it is not a bug. You should see the message if you do the following:

```
nvim -u init.vim -c "set shm-=F"
:e init.vim
```

Or you can change the `echom "BufRead"` to `let g:BufRead = 1` to see that `autocmd` is firing.

**Comment by glacambre** [comment]
You're absolutely right - sorry for the noise!

**Comment by justinmk** [comment]
Related:

- https://github.com/vim/vim/issues/4379
- http://github.com/neovim/neovim/issues/13620
- https://github.com/neovim/neovim/issues/12041
- https://github.com/neovim/neovim/issues/8675
