### ISSUE TITLE
Question about configuring the LSP annotations/diagnostics (and various usability aspects around errors/warnings)

### ISSUE THREAD

**Issue by unphased** [neovim/neovim#12051]
I've begun to use Nvim's built-in LSP. It's *bloody awesome*. I've actually been migrating from vim to nvim ever since nvim became a thing. This feature is definitely the one that will make me do the full switch.

Now, I've done enough research to work out how to more or less use Lua calls to configure Nvim's LSP functionality enough to get things going, and I've also gotten Supertab to function well with omnifunc after getting that hooked up. This is phenomenal, as at this point with completion and jump-to bindings already working there is literally no reason to stick with other LSP implementations anymore.  

The very last bit I have yet to figure out is how to configure the error/warning diagnostic/annotation, and a few other curiosities. 

One screenshot captures a number of things that are a little rough around the edges to me: 

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/1542910/77649971-4f58f500-6f9d-11ea-8662-b52baf7f6d37.png">

1. The popup was displayed by invoking `<cmd> lua vim.lsp.buf.signature_help()<CR>` through an nmap. I'm not expecting functionality to exist that automatically pulls this signature_help up whenever you are in insert mode and inside parentheses, but I hope that can be a possibility rather than having to hit a key, but I suppose this can be vimscripted.
2. The underscores in that signature help popup are somehow all highlighted red. I am not sure if it is possible to determine the highlight group that is responsible for this, but it is certainly weird and visually distracting.
3. The signature should read `clCreateBuffer(cl_context, cl_mem_flags, size_t, void* , cl_int* ) -> cl_mem`. It definitely looks to me like this string got *markdown*-ed somehow, which is both highly impressive and also totally no bueno for languages with pointers.
4. The error diagnostic uses a square glyph (or a series of them if multiple issues exist on the same line, I noticed), it looks like the square character is hardcoded in `share/nvim/runtime/lua/vim/lsp/util.lua`. 
5. The diagnostics highlights are always cleared for some reason, unless I set them in an autocmd. So my nvim config looks like this:
`autocmd BufEnter * highlight LspDiagnosticsError gui=italic ctermbg=88 guibg=#870000`
`autocmd BufEnter * highlight LspDiagnosticsWarning gui=italic ctermbg=11 guibg=#878700`
Note: my screenshot was taken before I set this up. There is another problem with this although I'm not certain right now if it is a problem with nvim or alacritty, the italic breaks alacritty but works fine in iTerm2. Going to not set italic for the time being.
6. These diagnostics (as you can see in screenshot) consist of the entire multiline LSP error message but always gets truncated. I'm actually more or less satisfied with this, but is there any mechanism to display the entire message if I want to see it? Anything using a temporary buffer or (most ideal) a popup window, or even just show it in the command/status bar? Is there perhaps a command that can return this value for the current line?
7. I see signs are set by the diagnostics, but they get clobbered by my git gutter signs. Not sure how to deal with that. I know coc handles this better. 

let me reiterate that I consider these all nits that I'm picking. the functionality is so awesome already. 

Thanks!!

**Comment by yen3** [comment]
Maybe you can try the plugin https://github.com/haorenW1025/diagnostic-nvim to resolve your problem.

**Comment by unphased** [comment]
Thanks for linking that plugin! This stuff is all very fast moving. I feel bad about kinda of complaining. I’m excited to see what the future will bring 😁

**Comment by jmdaly** [comment]
@unphased I'm about as excited about neovim's built in LSP support as you are! Have you solved the underscores being highlighted in red in the hover window? It's an issue I'm currently having. I know it's related to the text being interpreted as markdown, and underscores being used to represent Italics in markdown, but I'm not sure how to address it.

**Comment by tjdevries** [comment]
I think everything mentioned in this issue (I may have missed some items) has been implemented now by : https://github.com/neovim/neovim/commit/f75be5e9d510d5369c572cf98e78d9480df3b0bb

I'm going to close this issue because I think we've fixed these. If I missed anything, please feel free to re-open the issue and we can try and fix those problems :)
