### ISSUE TITLE
Another LSP usability question: is there a way to jump to the "next" or "previous" error / warning / diagnostic message?

### ISSUE THREAD

**Issue by nerdrew** [neovim/neovim#12052]
The built-in LSP is awesome. In the same vein as https://github.com/neovim/neovim/issues/12051, I have some usability questions.

As the title says: is there a way to jump to the "next" or "previous" error / warning / diagnostic message?

Also, is there a way to reload the LSP server (e.g. when it gets in a bad state after a file reformat)? I tried `:lua vim.lsp.stop_all_clients()`, but I get this error:

```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'stop_all_clients' (a nil value)
```

```
:version
NVIM v0.5.0-418-g87d892afa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neo
vim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-c48d5551-5074-4a05-b117-d6e98b5fddaa

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by h-michael** [comment]
> Also, is there a way to reload the LSP server (e.g. when it gets in a bad state after a file reformat)? I tried :lua vim.lsp.stop_all_clients(), but I get this error:

It seems that the document is wrong.
You can stop all clients like this.
`:lua vim.lsp.stop_client(vim.lsp.get_active_clients())`

**Comment by h-michael** [comment]
> As the title says: is there a way to jump to the "next" or "previous" error / warning / diagnostic message?

No. But we can implement it.

**Comment by bfredl** [comment]
This could be done by setting the location list to the errors and then use the standard loc list bindings. Don't we have a method for that already?

**Comment by mjlbach** [comment]
You can override the publish diagnostics callback (I do this in my config), and with vim-unimpaired can navigated the quickfix list with ]q and [q

``` lua
:lua << EOF
  local nvim_lsp = require('nvim_lsp')

  local on_attach = function(_, bufnr)
    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
    local method = 'textDocument/publishDiagnostics'

  local default_callback = vim.lsp.callbacks[method]
  vim.lsp.callbacks[method] = function(err, method, result, client_id)
    default_callback(err, method, result, client_id)
    if result and result.diagnostics then
      for _, v in ipairs(result.diagnostics) do
        v.uri = v.uri or result.uri
      end
      vim.lsp.util.set_qflist(result.diagnostics)
      end
    end

    -- Mappings.
    local opts = { noremap=true, silent=true }
    vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<leader>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<leader>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<leader>e', '<cmd>lua vim.lsp.util.show_line_diagnostics()<CR>', opts)
  end

  local servers = {'gopls', 'rust_analyzer', 'sumneko_lua', 'tsserver', 'vimls', 'pyls', 'jsonls'}
  for _, lsp in ipairs(servers) do
    nvim_lsp[lsp].setup {
      on_attach = on_attach,
    }
  end
EOF

```

**Comment by teto** [comment]
`:h vim.lsp.stop_client()` gives the correct answer.
I find the API unintuitive in the sense that stop_client should stop only one client.

also the behavior is not idempotent
``` 
By default asks the server to shutdown, unless stop was
requested already for this client, then force-shutdown is attempted.
```

To answer OP's question, feeding the location list and then mapping `:labove` / `:lbelow` is nice.

https://github.com/haorenW1025/diagnostic-nvim provides NextDiagnostic / PrevDiagnostic but what I like the most is the diagnostics as floating windows (for lengthy errors, virtualtext isn't helpful)

**Comment by weilbith** [comment]
If you don't mind, I would recommend the minimalistic [nvim-lsp-diamove](https://github.com/weilbith/nvim-lsp-diamove) plugin. It provides you with exactly what you are asking for. It works like `:cabove`, `:cbelow`, `:labove` and `:lbelow`. In contrast to those it secures the correct order of the list entries. What this plugin does not, is to differ between the different diagnostic types. Could eventually be added. I'm open for pull requests. :shrug: 

There was/is the plan to also emit a custom event when a jump took place. The idea was that the user can then chain a call like `vim.lsp.util.show_line_diagnostics()`. Unfortunately is exactly this function buggy (pop-up window does not appear). So this is still in the pipe.

**Comment by tjdevries** [comment]
After https://github.com/neovim/neovim/commit/f75be5e9d510d5369c572cf98e78d9480df3b0bb

You can use `vim.lsp.diagnostic.goto_next()` and `vim.lsp.diagnostic.goto_prev()` and their associated configurations to do what you're looking for (as well as setting loclist and using builtin commands to move there).

**Comment by BebeSparkelSparkel** [comment]
> You can use `vim.lsp.diagnostic.goto_next()` and `vim.lsp.diagnostic.goto_prev()` and their associated configurations to do what you're looking for (as well as setting loclist and using builtin commands to move there).

According to the docs  `vim.diagnostic.goto_next()` and `vim.diagnostic.goto_prev()` should be used.
