### ISSUE TITLE
Automatically generate session files in ~/.vim/sessions/default.vim

### ISSUE THREAD

**Issue by Ni1fheim** [neovim/neovim#12066]
Neovim version: 
```bash
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

`~/.vim/sessions/default.vim` file is automatically generated when I using vim.
Even if I use the vim-startify plugin and set  `let g:startify_session_dir='~/.cache/nvim/session'`. (And it ’s the same without plugins). I have tried many ways and I can't change this situation.
I think the generation of directories should seem to follow the XDG base directory standard. (Like `$XDG_DATA_HOME/nvim/session`)
My session(startify) related settings:

```vim
let g:startify_change_to_dir       = 1
let g:startify_relative_path       = 1
let g:startify_session_autoload    = 1
let g:startify_session_persistence = 1
let g:startify_update_oldfiles     = 1
let g:startify_session_dir         = '~/.cache/nvim/session'
```

Ask for help!

**Comment by teto** [comment]
nvim doesn't create sessions by default so it must be an issue with your config/plugin.

Tip: you can use stdpath to retreive standard folders for nvim, e.g. `let g:startify_session_dir = stdpath('data').'/nvim/sessions'`

**Comment by Ni1fheim** [comment]
> nvim doesn't create sessions by default so it must be an issue with your config/plugin.
> 
> Tip: you can use stdpath to retreive standard folders for nvim, e.g. `let g:startify_session_dir = stdpath('data').'/nvim/sessions'`

The problem is here, I tried to set the `g:startify_session_dir` variable to `stdpath('data').'/session'`, but it didn't work and still generated the `~/.vim/session/dafault.vim' file.
I tried a lot of methods for this, such as uninstalling the v plugin, but it didn't work, the directory and file kept generating.
My list of plugins is as follows:

```vim
" :PlugStatus

  Finished. 0 error(s).
  [=================]

  - vim-devicons: OK
  - vim-startify: OK
  - fzf.vim: OK
  - coc.nvim: OK
  - nerdtree: OK
  - goyo.vim: OK
  - nerdtree-git-plugin: OK
  - vim-markdown-toc: OK
  - vim-gruvbox8: OK
  - vim-airline-themes: OK
  - auto-pairs: OK
  - vim-nerdtree-syntax-highlight: OK
  - vim-airline: OK
  - vim-easy-align: OK
  - vim-easymotion: OK
  - vim-airline-clock: OK
  - float-preview.nvim: OK
```

The Coc.nvim extension used is as follows：

  - [coc-yank](https://github.com/neoclide/coc-yank)
  - [coc-translator](https://github.com/voldikss/coc-translator)
  - [coc-todolist](https://github.com/voldikss/coc-todolist)
  - [coc-snippets](https://github.com/neoclide/coc-snippets)
  - [coc-lists](https://github.com/neoclide/coc-lists)
  - [coc-highlight](https://github.com/neoclide/coc-highlight)
  - [coc-calc](https://github.com/weirongxu/coc-calc)
  - Language Server:
      - [coc-rls](https://github.com/neoclide/coc-rls)
      - [coc-python](https://github.com/neoclide/coc-python)
      - [coc-json](https://github.com/neoclide/coc-json)
      - [coc-clangd](https://github.com/clangd/coc-clangd)

Only **startify** can be related to the session file.

**Comment by teto** [comment]
As far as I know, this shouldn't be a fault in neovim, but rather something in your setup. Please try to get a minimal working example for instance by commenting out all plugins and enabling them one by one, search for `mksession` in your autocommands via `:autocmd` etc.

**Comment by Ni1fheim** [comment]
> As far as I know, this shouldn't be a fault in neovim, but rather something in your setup. Please try to get a minimal working example for instance by commenting out all plugins and enabling them one by one, search for `mksession` in your autocommands via `:autocmd` etc.

I think you are right, but I can‘t reproduce this issue QAQ, I reinstalled neovim and all plugins again, and then this automatically generated file disappeared...

**Comment by gaving** [comment]
Had exactly the same issue here, tracked it down to `coc.nvim` causing it.

Changed the setting shown in https://github.com/neoclide/coc-lists#options and pointed it at my sessions directory.

```
  "session.directory": "~/.local/share/nvim/session",
```

Which sorted it out!
