### ISSUE TITLE
Neovim exits on Cmd+V, attempting to paste

### ISSUE THREAD

**Issue by btc** [neovim/neovim#12062]
- `nvim --0.4.3`:
- `vim -u DEFAULTS` (version: ) behaves differently? No.
- Operating system/version: macOS 10.15.3
- Terminal name/version: Apple_Terminal
- `$TERM`: n/a

### Steps to reproduce using `nvim -u NORC`

```
nvim -ü NORC
[add something to clipboard]
Cmd+V

```

### Actual behaviour
 Neovim exits.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/734339/77828405-9821c280-70f1-11ea-82b9-b4bc537adb77.png">

### Expected behaviour

Text is pasted

**Comment by btc** [comment]
In iTerm2, if I uncheck the option "terminal may enable paste bracketing", I gain the ability to paste. ❓ 

This information seems useful for understanding what might be happening. Do I need to configure Neovim to enable and disable paste bracketing? If I understand correctly, neovim is responsible for disabling bracketing via control sequence on launch. Is this understanding correct?

**Comment by xylix** [comment]
Can't reproduce with these instructions, neither in iterm2 or apple's terminal, with neovim 0.4.3 or latest master (v0.5.0-423-g4139678f9).

Can you confirm what you are pasting isn't somehow "weird" or weirdly formatted? For example try pasting just this string "test_paste". Also did you confirm your `nvim -u NORC` actually started neovim with default settings? The command you pasted (`nvim -ü NORC`) looks like it has the wrong `u` symbol.

**Comment by btc** [comment]
I was able to reproduce again here.

I am able to confirm that `nvim -u NORC` does indeed start neovim with default settings on my machine.

With iterm2 "allow enabling paste bracketing", the test string `test_paste` causes neovim to exit.

This time, I am able to observe a specific error message, although it is possible this is not directly indicative of the root cause:

```
 14: /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/plugin/rplugin.vim
~                                                                        Vim: Finished.
-- INSERT --   E970: Failed to initialize lua interpreter
```

**Comment by xylix** [comment]
Running `:checkhealth:` in nvim and looking especially in the Lua stuff would probably be useful.

I have no clue what that rplugin is though. Checkhealth should give some info.

**Comment by btc** [comment]
> Running `:checkhealth:` in nvim and looking especially in the Lua stuff would probably be useful.
> 
> I have no clue what that rplugin is though. Checkhealth should give some info.


health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

## tmux
  - ERROR: escape-time (500) is higher than 300ms
    - ADVICE:
      - Set escape-time in ~/.tmux.conf:
          set-option -sg escape-time 10
      - https://github.com/neovim/neovim/wiki/FAQ
  - INFO: $TERM: screen
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.7.7
  - INFO: pynvim version: 0.4.0 (outdated; from ~/Library/Python/3.7/lib/python/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.1

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

**Comment by erw7** [comment]
> E970: Failed to initialize lua interpreter

From the error message above, isn't this the same problem as #11411, #11505?

**Comment by btc** [comment]
🍃 

```
:lua print('hello\n')
```

I just ran this command and it successfully printed hello.
Then, I tried pasting, in accordance with recommended settings, with paste bracketing enabled and pasting worked.

This lends some credence to the hypothesis that an external lua dependency was at the root, though it is not confirmed.

It is unfortunate we were unable to determine a root cause, but at the very least, this issue can be closed. What do you think?

gratitude for the assistance on this issue

😊
🙏🏽 

🍃

**Comment by xylix** [comment]
Probably just close the issue if the problem is now solved?

**Comment by btc** [comment]
Sounds good to me

🙏🏽
