### ISSUE TITLE
`./scripts/vim-patch.sh -l` does not work on MacOS default bash.

### ISSUE THREAD

**Issue by ya5u** [neovim/neovim#12069]
- `nvim --version`: NVIM v0.5.0-423-g4139678f9
- Operating system/version: Mac OS X 10.15.3
- Terminal name/version: iTerm2 Build 3.3.9
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```sh
$ git clone https://github.com/neovim/neovim.git
$ cd neovim
$ ./scripts/vim-patch.sh -l
```

### Actual behaviour

```sh
$ ./scripts/vim-patch.sh -l
./scripts/vim-patch.sh: line 400: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

### Expected behaviour

```sh
$ ./scripts/vim-patch.sh -l
Updating Vim sources: ...
```

This behavior is due to the version of default bash on MacOS.

```sh
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Why not add some Notes about bash prerequisites on [Wiki](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim) or somewhere?

**Comment by xylix** [comment]
I also came across this yesterday. Probably the best place to add the note would be an `if` in the shell script echoing an error message to the user if trying to use an invalid version of bash.

**Comment by xylix** [comment]
Did a PR for a possible fix here https://github.com/neovim/neovim/pull/12081 .
