### ISSUE TITLE
Neovim cursor flickers between bar and block in INSERT mode

### ISSUE THREAD

**Issue by mebaran** [neovim/neovim#12065]
When running Neovim in Windows Terminal (using Windows subsystem for Linux), the cursor annoyingly flickers between block and bar.  Behavior is not present when run without tmux.  nvim -u NORC does not change behavior.  I am running Neovim 0.4.3.

**Comment by teto** [comment]
what triggers the change ? what's your guicursor configuration (`:verbose set guicursor?`) ? If it only happens with tmux, maybe check your tmux config.

**Comment by mebaran** [comment]
This looks a problem in my Microsoft Terminal and its handling cursor escape codes.  Since they are working on it, I will close this.

**Comment by mebaran** [comment]
This looks like it’s a Microsoft Terminal issue:  they are on it.
