### ISSUE TITLE
Pasting text in Windows (OS) messes up indentation (but works fine in Ubuntu)

### ISSUE THREAD

**Issue by mangelozzi** [neovim/neovim#12068]
- `nvim --version`: 0.43, and 0.5
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Windows 10
- Terminal name/version: nvim-qt.exe and nvim.exe

### Steps to reproduce using `nvim -u NORC`
1. Start vim with -u DEFAULTS
2. Open some code with indented code.
3. Copy some of the code with various indentation levels
4. Open a line (so now one is in insert mode)
5. `CTRL-R "` to paste the lines

### Actual behaviour
Indentation is messed up because set paste does not activate. Additionally [using terminal's bracketed paste mode to automatically set/unset Vim's paste mode when you paste does not work](https://coderwall.com/p/if9mda/automatically-set-paste-mode-in-vim-when-pasting-in-insert-mode).

### Expected behaviour
`set paste` should turn on automatically before pasting (Works fine with Ubuntu 18.04), and turn off afterwards (as per behaviour in linux, and confirmed by [this post](https://github.com/neovim/neovim/issues/3566#issuecomment-332157063)

I have read quite a few closed issues about this topic, hence I tested on `NeoVim 0.5` before opening this one.

**Comment by chrisbra** [comment]
bracketed paste mode must be supported by the underlying terminal and you did not mention what terminal you are using to run vim/nvim. Is this plain cmd.exe? I very much doubt that it does support bracketed paste mode.

**Comment by michael-angelozzi** [comment]
> bracketed paste mode must be supported by the underlying terminal and you did not mention what terminal you are using to run vim/nvim. Is this plain cmd.exe? I very much doubt that it does support bracketed paste mode.

`nvim-qt.exe` has no terminal (?) which is what I mostly use when in Windows. So I expect it something independent of the terminal?

**Comment by erw7** [comment]
This is not a bug. As for the pasting from the register by `CTRL-R` in the insert mode, the following description is given in the help (`:h i_CTRL-R`).

> If you have options like 'textwidth', 'formatoptions', or 'autoindent' set, this will influence what will be inserted.  This is different from what happens with the "p" command and pasting with the mouse.

I think the reason Ubuntu 18.04 works the way you want it to is probably because it's `noautoindent`.

Switching between paste mode with bracketed paste mode is irrelevant in this case, as it is what happens when you paste from the clipboard (Pasting by `shift+insert` in xterm, etc).

**Comment by michael-angelozzi** [comment]
I use the same vimrc config for both windows and linux (checked out of git), and both have `set autoindent`.

**Comment by erw7** [comment]
I checked with ppa neovim (NVIM v0.5.0-dev) on Ubuntu 18.4. When pasting from the register with `<C-R>"` in insert mode, `set paste` is not automatically enabled.

**Comment by zeertzjq** [comment]
Just use `i_CTRL-R_CTRL-O`.
