### ISSUE TITLE
Integer overflow?

### ISSUE THREAD

**Issue by pwntester** [neovim/neovim#12071]
Using latest nvim create the following command:

```
command! -range Test echo getpos("'>")
```

Then select part of a line using `v` and enter the `'<,'>Test` command, it should show the cursor position for the end position of the selected text
Now, select the whole line with `V` and enter the `'<,'>Test` command again, it prints `[0, 16, 2147483647, 0]`

**Comment by chrisbra** [comment]
No, that is the special value for end of line.

**Comment by pwntester** [comment]
Nice to know, thanks!

For other people getting the same problem, you can write a function like:

```
function! Test() abort
    let cursor = getcurpos()
    let [line_start, column_start] = getpos("'<")[1:2]
    let [line_end, column_end] = getpos("'>")[1:2]
    let column_end = column_end == 2147483647 ? len(getline(line_end)) : column_end
    echom line_start.'::'.column_start.'::'.line_end.'::'.column_end
endfunction
```
