### ISSUE TITLE
Set build type "Release",but it's debug mode after build

### ISSUE THREAD

**Issue by chenyidao110** [neovim/neovim#12077]
OS: WSL1 Debian 10

set build type as "Release" follow the command in wiki:
--make CMAKE_BUILD_TYPE=Release--
After build, neovim is Debug type：
NVIM v0.5.0-422-ge700a88bb
--Build type: Debug--

**Comment by bfredl** [comment]
Try `rm -r build/` first before `make` with flags. The flags are cached in the cmake config process.

**Comment by chenyidao110** [comment]
> 
> 
> Try `rm -r build/` first before `make` with flags. The flags are cached in the cmake config process.

I try again,it's still "Debug":
root@DESKTOP-1ODIMFE:~/neovim# ./build/bin/nvim --version
NVIM v0.5.0-424-g6ca7ebb34
Build type: Debug

**Comment by chenyidao110** [comment]
I want to build it Release mode and special location,so can I make as follow:
`make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=/usr/local/nvim`

**Comment by chenyidao110** [comment]
Modify Makefile,change the two var as follow, then build
```
**CMAKE_BUILD_TYPE** ?= Release
**CMAKE_EXTRA_FLAGS** ?= '-DCMAKE_INSTALL_PREFIX=/usr/local/neovim'
```
detail:
`Build type: Release`

**Comment by dmocek** [comment]
Perform a 'make distclean' before building.  This will wipe the build directory.
