### ISSUE TITLE
set nocindent has to effect if put into "vimrc"

### ISSUE THREAD

**Issue by DoctorApparatus** [neovim/neovim#12079]
- NVIM v0.2.2
- `vim -u DEFAULTS` (version: ) behaves differently?
- Ubuntu 18.04.4
- rxvt-unicode-256color
- rxvt-unicode-256color

When using "(" it still gets autoindented/smartindented/cindented although my vimrc/neovimrc specifically disabled all of them.

I tried the same vimscript code in vim and it works perfectly fine there. But not in neovim. Calling ":set nocindent" within neovim does the job. But I can't do that anytime I open a .c or .h file.

**Comment by chrisbra** [comment]
you are hitting filetype (and indent) plugins, that enable specific options for a particular filetype (among those could be formatoptions, completeoptions, comment options and obviously indent settings) as those depends very much on the type of file you are editing. You can customize those using the `:filetype` command (see `:h :filetype` and all the following paragraphs) and in particular have a look at `:h ftplugin-overrule` if you want to adjust what option is set for a particular filetype

**Comment by DoctorApparatus** [comment]
Is there a way to completely disable all filetype plugins all together?

**Comment by DoctorApparatus** [comment]
filetype plugin off
did the trick for me. Thanks for the help
