### ISSUE TITLE
Is main_loop at "wiki/Code overview" deprecated? 

### ISSUE THREAD

**Issue by FurkanTheHuman** [neovim/neovim#12072]
- NVIM v0.5.0-423-g4139678f9-dirty
- Build type: Debug
- LuaJIT 2.1.0-beta3
- commit: 4139678f97ee556ab142031a1ed5c7580278b64f

At code overview file there is a section called main_loop() that tells about a function called main_loop.  However there is no main_loop function (there is a `Loop main_loop` struct). 

There is a function called normal_enter (in normal.c) and comment at the top of this function says:
`// This used to be called main_loop on main.c`

Am I missing anything?

**Comment by glacambre** [comment]
Yes, it was outdated. Thank you for letting us know! :)
