### ISSUE TITLE
editing multiple files with $ nvim * 

### ISSUE THREAD

**Issue by yelled1** [neovim/neovim#12089]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (8.1.2292) behaves differently? yes
- Operating system/version: OS version: Windows 10 Enterprise x64 1909
- Terminal name/version:
    * ConEmu build: ConEmu1901012[64]
    * Windows native Command Prompt

### Steps to reproduce using `nvim -u NORC`
In a directory with 3 files with .py extension
When I type
```
λ vim *.py
3 files to edit
```
No issues occur: I get to edit the file "tst1.py"

### Actual behaviour
when I type

```
λ nvim *.py
E303: Unable to open swap file for ".py", recovery impossible
Press ENTER or type command to continue
```
After Enter
And file open's name is "*.py" & not one of the 3 files with .py extension
(for example: tst1.py, tst2py, tst3.py were covered by *.py then tst1.py should open)

### Expected behaviour
```
λ nvim *.py
3 files to edit
```
No issues occur: I get to edit the file "tst1.py" & other two by
```
:n
```

**Comment by erw7** [comment]
This is because `cmd.exe` does not expand file glob by default. Run `cmd.exe` with `/E:ON`, or use it with a shell that expands the file glob, such as `powershell`. Of course you can also write a patch to expand the file glob in `nvim`.

**Comment by yelled1** [comment]
Thank you for ur quick response:
Not sure /E:ON works as I tried:
-new_console:d:C:\Prj cmd /E:ON /k ""%ConEmuDir%\..\init.bat" "
![image](https://user-images.githubusercontent.com/2314710/78651912-fd627a00-788e-11ea-8591-56d23def419d.png)

and
on windows: run -> cmd.exe /E:ON as below image as well.
![image](https://user-images.githubusercontent.com/2314710/78651787-d1df8f80-788e-11ea-9d4e-2ae6718ff541.png)

Prior to trying any patch - am I doing this correctly? Is there another simple alternative way?

**Comment by erw7** [comment]
I'm sorry. When I tried it earlier, file glob expansion was disabled with `/E:OFF`, but now I've tried it and it's not disabled. Therefore, it seems that `/E:ON` was a mistake on my part.

In my environment, `cmd.exe` expands the file glob, so it should be possible to expand the file glob in settings, etc., but I don't know why the file glob are expanded in my environment.

**Comment by yelled1** [comment]
Oh, no pls don't be sorry. Thank you for trying. Not sure why it works in your env. Also, it works on vim, cp, & rm etc... Think this is a bug in neovim. I have Win10 Ent 1909, which should be the latest.
Have no issues in Ubuntu. So, I am sure where the problem.
What's your env?

**Comment by erw7** [comment]
`CRT` of `MinGW` seems to expand the file glob. Therefore, if the `nvim` is compiled with `MinGW`, this problem does not occur. For `MSVC`, someone needs to create a patch to solve this problem.

**Comment by erw7** [comment]
I found the following description in the help (`:h vim-differences`).

> Startup:
>   --literal (file args are always literal; to expand wildcards on Windows, use `:n` e.g. `nvim +"n *"`)

So, this seems to be a neovim spec, not a bug.

**Comment by yelled1** [comment]
An unintuitive Spec...  But thank you for finding a solution. 
You have been great.
Stay safe!
