### ISSUE TITLE
All windows share one status bar like tmux

### ISSUE THREAD

**Issue by fgheng** [neovim/neovim#12094]
Now, neovim support one window with one status but not support all windows with only one status at the bottom, would you liket to add this feature?

**Comment by liuhaowen478** [comment]
I'm definitely happy to see that coming.

**Comment by fgheng** [comment]
That will save a lot of space and show more info about current window.

**Comment by glacambre** [comment]
This issue is a duplicate of #9342, so I'll close it :)
