### ISSUE TITLE
Quit will trigger BufNew event.

### ISSUE THREAD

**Issue by kevinhwang91** [neovim/neovim#12097]
- `nvim --version`:v0.5.0-426-g30a6e374d
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: ArchLinux Kernel 5.4.30-1-lts
- Terminal name/version: alacritty
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC +'autocmd BufNew * sleep 1' +q
```

### Actual behaviour
Hang a few seconds.
### Expected behaviour
Exit at once like vim.

**Comment by monkoose** [comment]
It actually trigger multiple times for me, not only once.

**Comment by zeertzjq** [comment]
Sees fixed long ago.
