### ISSUE TITLE
Nvim hangs when "py3 vim.eval('v:char')" is run from an "InsertCharPre" autocmd

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#12095]
- `nvim --version`: NVIM v0.5.0-423-g4139678f9
 - `vim -u DEFAULTS` (version: 8.2 Included patches: 1-520) behaves differently? Yes
 - Operating system/version: Ubuntu 16.04.6 LTS
 - Terminal name/version: XTerm(322)
 - `$TERM`: xterm-256color

### Steps to reproduce

Run this shell command:

    nvim -u NONE -i NONE +'au InsertCharPre * exe "py3 import vim" | py3 vim.eval("v:char")'

Press `i` to enter insert mode, then `<F2>`.

### Actual behaviour

Nvim hangs.  I can't interact with it; I tried to press `C-\ C-n` to get back to normal mode, and `C-c` (in case some function was stuck in an infinite loop), but I still can't interact with Nvim, so I have to `kill(1)` it.

### Expected behaviour

Nvim does not hang.

### Additional information

In practice, this issue causes Nvim to hang when [UltiSnips is used](https://github.com/SirVer/ultisnips/issues/1202) and a function key is pressed from insert mode.

---

In Vim, the same code raises an error:

    Error detected while processing InsertCharPre Autocommands for "*":
    Traceback (most recent call last):

If the verbose level is increased, one can see the cause:

    Exception thrown: Vim(py3):UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 0: invalid start byte

Searching for `UnicodeDecodeError` on Vim's issue tracker leads to [this report](https://github.com/vim/vim/issues/1053), which mentions [another issue in UltiSnips](https://github.com/SirVer/ultisnips/issues/690#issuecomment-246121159), which [was fixed](https://github.com/SirVer/ultisnips/pull/753) by using `vim.bindeval()` instead of `vim.eval()`.

Unfortunately, `vim.bindeval()` does not seem to be supported in Nvim:

    Error detected while processing function provider#python3#Call:
    line   18:
    Error invoking 'python_execute' on channel 3 (python3-script-host):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    AttributeError: 'LegacyVim' object has no attribute 'bindeval'

---

In Nvim, if the verbosity is increased, the last function which is called before Nvim hangs seems to be [`provider#python3#Call()`](https://github.com/neovim/neovim/blob/1f56f9a4b32c7d7aebafea226c148e9ed8bbabdb/runtime/autoload/provider/python3.vim#L44) with these arguments:

    provider#python3#Call('execute', ['vim.eval(''v:char'')', 1, 1])

**Comment by tomtomjhj** [comment]
This is perhaps duplicate of https://github.com/neovim/pynvim/issues/435, https://github.com/neovim/pynvim/issues/438.
https://github.com/neovim/pynvim/pull/439 this worked for me.

**Comment by lacygoill** [comment]
Can confirm that https://github.com/neovim/pynvim/pull/439 fixes the issue.

Thank you for the information.
