### ISSUE TITLE
Setting 'inccommand' breaks substitution with ~

### ISSUE THREAD

**Issue by rnevius** [neovim/neovim#12109]
- `nvim --version`: 0.4.3 and 0.5.0-nightly
- `vim -u DEFAULTS` (version: 8.2) behaves differently
- Operating system/version: macOS 10.15.4
- Terminal name/version: kitty 0.17.1
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Given the following line:

```
a,b,c,d,e,f
```

And given the following settings:

```
set inccommand=split  " or nosplit
```

1. `:s/a/z` ... works
2. `:s/b/~` ... substitutes `b` with an empty string, instead of `z`

### Expected behaviour

`~` substitutes a pattern with "the last given substitute string", even after `inccommand` has been modified from the default.

**Comment by erratic-c-programmer** [comment]
Can reproduce this one too
