### ISSUE TITLE
E576: Error while reading ShaDa file..

### ISSUE THREAD

**Issue by Ashe** [neovim/neovim#12101]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: 8.2.510 ) behaves differently?: Yes, it doesn't display the error
- Operating system/version: Arch Linux
- Terminal name/version: urxvt (with tmux)
- `$TERM`: screen

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

### Actual behaviour
Immediately as soon as I hope nvim (NORC or not), I get the error message:
```
E576: Error while reading ShaDa file: last entry specified that it occupies 58 bytes, but file ended earlier.
```

### Expected behaviour
To not show this message, or if there's actually something wrong (which there probably is), tell me how to solve the problem or where to find this 'ShaDa' file and correct it. Sorry if this is obvious but it's very invasive!

I'm not sure where to look the error code up, so I made sure to include it in the title of this issue in case others have this problem too.

**Comment by ta-tikoma** [comment]
You can go to C:\Users\<User name>\AppData\Local\nvim-data\shada and clear folder.

**Comment by Ashe** [comment]
Ah thank you. I didn't think this was safe to delete etc.

**Comment by wenfangdu** [comment]
Shorter path for Windows: `%LOCALAPPDATA%\nvim-data`.

**Comment by BatmanAoD** [comment]
Would it be possible (or desirable) for NeoVim to automatically fix or delete the file? Failing that, could the error at least prompt the user to delete it themselves?

**Comment by zhisme** [comment]
just ran onto this one on linux `Linux 5.15.86-1-lts`, however `rm -rf /home/zh/.local/share/nvim/shada/*` didn't work for me. So I searched where elsewhere it can be and found other place
```
~/.local/state/nvim/shada
```

`rm  ~/.local/state/nvim/shada/*` fixed the issue.

**Comment by hf02** [comment]
Should this be closed? While it's easy to fix, it's too common of an occurrence...

**Comment by BtAbdul** [comment]
for those who using termux and astromvim, lazyvim, lunarvim any other distro
just goto 
`cd ~/.local/state`
To see list od distro
  `ls`
very distro has folder shada  
`cd shada`

romove main.shada
`rm -r shada.main`

Some way for all os |ike mac windows goto  `local/state/` and open your respective distribution or vim and goto shada directory and remove main.shada file

**Comment by hoschi** [comment]
I needed to delete a lot of `.vim-info*` files instead to fix the issue:
![image](https://github.com/neovim/neovim/assets/163128/e0dcc01b-6ca6-4f6f-8c8b-59efb2f31227)

Does someone know where they are coming from?

**Comment by BtAbdul** [comment]
> I needed to delete a lot of `.vim-info*` files instead to fix the issue: ![image](https://user-images.githubusercontent.com/163128/265763327-e0dcc01b-6ca6-4f6f-8c8b-59efb2f31227.png)
> 
> Does someone know where they are coming from?

Its temporary files which is generated by vim or neovim

**Comment by drGeoBN** [comment]
I ran into this issue on my Mac M1 using nvim and resolved the issue by: 
`rm -rf ~/.local/state/nvim/shada/*`
