### ISSUE TITLE
gq in visual mode leaves cursor as line in normal mode

### ISSUE THREAD

**Issue by rob-3** [neovim/neovim#12112]
- `nvim --version`: NVIM v0.5.0-427-g1f56f9a4b
- `vim -u DEFAULTS` (version: ) behaves differently? No, same behavior
- Operating system/version: Arch Linux, latest
- Terminal name/version: kitty, xfce4-terminal, guake
- `$TERM`: xterm-kitty, xterm-256color for xfce4-terminal and guake

### Steps to reproduce using `nvim -u NORC`
1) Open a new html file (.html extension required)
2) Type random characters until you reach 80 chars.
3) Repeat on a new line.
4) Type V to enter visual linewise mode and highlight the two lines.
5) Type gq

### Actual behaviour
The cursor is a line.
### Expected behaviour
The cursor should be a block.

**Comment by zeertzjq** [comment]
No, still happening

**Comment by zeertzjq** [comment]
Minimal repro:
```vim
func Indent()
  normal! ^
  return 0
endfunc

setlocal indentexpr=Indent()
call setline(1, [repeat('a', 80), repeat('b', 80)])
call nvim_input('VGgq')
```

**Comment by justinmk** [comment]
Ah, my kitty terminal config may have hidden the issue, I guess it forces block cursor. In Terminal.app I can repro the issue.

**Comment by zeertzjq** [comment]
Closing in favor of #12309
