### ISSUE TITLE
`matchdelete` should allow passing in window number

### ISSUE THREAD

**Issue by lriuui0x0** [neovim/neovim#12110]
NVIM v0.5.0-dev

`matchdelete` doesn't allow passing in window number, which makes the window number passed into `matchadd` useless.

**Comment by Shougo** [comment]
It is requested in Vim8?
It should be implemented in Vim8, too.

**Comment by Shougo** [comment]
It is already implemented in Vim8.
So the patch should be ported.

**Comment by Shougo** [comment]
Vim 8.1.1084

https://github.com/vim/vim/commit/aff749145e23c0f20b5158d1d3a942948ed138e3

It should be ported.

https://github.com/neovim/neovim/pull/11637

> This should go with 8.1.1084 but it includes runtime updates.

Hm.

**Comment by lriuui0x0** [comment]
@Shougo Is this planned to be fixed soon?

**Comment by Shougo** [comment]
> @Shougo Is this planned to be fixed soon?

Unfortunately, it is not yet.
You can port it.
