### ISSUE TITLE
Neovim does not honor terminal cursorstyle

### ISSUE THREAD

**Issue by Simerax** [neovim/neovim#12116]
Neovim changes the used cursor-style of the current terminal. Vim does not.

- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: 8.2) behaves differently? Yes
- Operating system/version: Linux Fedora 31
- Terminal name/version: alacritty (0.4.2) and gnome-terminal (3.34.3)
- `$TERM`: alacritty & gnome-terminal

### Steps to reproduce using `nvim -u NORC`
start nvim, close it again.

### Actual behaviour
When Neovim is started (normal mode) the cursor-style is set to "Block". Quit Neovim and the cursor-style stays "Block"

In this example I used gnome-terminal within a bash shell.
The Problem persists in other terminal-emulators such as alacritty and shell's like zsh.

You can see that I use the "underline" cursor-style. Vim honors this, Neovim does not.

![Bildschirmfoto vom 2020-04-13 01-01-08](https://user-images.githubusercontent.com/33641215/79081967-7eec5900-7d22-11ea-82d2-615730774696.png)
![Bildschirmfoto vom 2020-04-13 01-01-15](https://user-images.githubusercontent.com/33641215/79081970-801d8600-7d22-11ea-9893-e9ac53d4302b.png)
![Bildschirmfoto vom 2020-04-13 01-01-24](https://user-images.githubusercontent.com/33641215/79081971-81e74980-7d22-11ea-88e8-0843accb1af0.png)
![Bildschirmfoto vom 2020-04-13 01-01-40](https://user-images.githubusercontent.com/33641215/79081973-83187680-7d22-11ea-89f9-df2693e468f1.png)
![Bildschirmfoto vom 2020-04-13 01-01-49](https://user-images.githubusercontent.com/33641215/79081974-83b10d00-7d22-11ea-9769-b66ce038608e.png)
![Bildschirmfoto vom 2020-04-13 01-01-58](https://user-images.githubusercontent.com/33641215/79081976-84e23a00-7d22-11ea-9004-e5b19781fd26.png)

### Expected behaviour
Neovim should either not change the cursor-style at all (like vim does it) or reset the cursor style on exit.

**Comment by erw7** [comment]
This seems to be an duplicate of #4396. You can also read more about this in the FAQ.

https://github.com/neovim/neovim/wiki/FAQ#cursor-style-isnt-restored-after-exiting-nvim

**Comment by Simerax** [comment]
I think Neovim should handle it the same way that vim does. I guess I'm the only one thinking that way
