### ISSUE TITLE
Bug in lsp, need string but get nil

### ISSUE THREAD

**Issue by zhaozg** [neovim/neovim#12122]
https://github.com/neovim/neovim/blob/05fd64777087e3f6886e3fdda2fd906ccda7e165/runtime/lua/vim/lsp/util.lua#L723-L728

> Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:560: Expected lua string

Some lsp server(https://github.com/bash-lsp/bash-language-server) not have kind in reference,  reference["kind"] is nil, ...

**Comment by teto** [comment]
It would be nice to check if that's a fault in the server or the client. 
We could default to LspReferenceText: `document_highlight_kind[reference["kind"]` or "LspReferenceText"]`.
