### ISSUE TITLE
:terminal outputs unicode replacement character for emojis (output/paste)

### ISSUE THREAD

**Issue by alex7691076** [neovim/neovim#12123]
- `nvim --version`:

```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

```
NVIM v0.5.0-429-g13b4a6fd4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DUTF8PROC_STATIC -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: Windows 10.0.18363.720
- Terminal name/version: cmd (via windows terminal 0.10.781.0)
- `$TERM`: vtpcon, ansi-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Write 😃 and save as 'test-emoji'
# :vsplit and switch to right window
# :terminal
chcp 65001
type test-emoji
xxd test-emoji
echo 😃
echo 😃 | xxd
```

### Actual behaviour

0.4.3:
![изображение](https://user-images.githubusercontent.com/63703489/79313837-9e91a600-7f09-11ea-9824-57535c1743ae.png)

0.5.0-429-g13b4a6fd4:
![изображение](https://user-images.githubusercontent.com/63703489/79314009-da2c7000-7f09-11ea-9bfa-739559d189f1.png)

### Expected behaviour
😃 displayed on:
type test-emoji
echo 😃

**Comment by erw7** [comment]
This is a problem with `conhost.exe(OpenConsole.exe)`. It may be tricky because you have to build `conpty.dll` and `OpenConsole.exe` yourself, but using #12137 will improve it somewhat. The remaining paste problem using #12137 is a problem with `OpenConsole.exe` and cannot be addressed by neovim.

**Comment by alex7691076** [comment]
Thanks for #12137 and a heads-up. Will wait for OpenConsole.exe changes...

**Comment by 3N4N** [comment]
I'm getting this:
![image](https://user-images.githubusercontent.com/32037751/223460502-8960b242-b2d9-4995-8dfe-d6913c64d2af.png)

Tested on:
```
OS: Windows 22H2
Terminal emulator: Windows Terminal v1.17.1023
$TERM: xterm-256colors
Shell: cmd.exe

NVIM v0.9.0-dev-854+g8258345c6d48-dirty
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/apps/nvim/share/nvim"

Run :checkhealth for more info
```

I remember seeing a merged PR for double-width or multi-width Unicode character display, which I'm guessing also fixed this issue, but I can't find that PR to link here.
