### ISSUE TITLE
Number of matches when using / and ? not showing 

### ISSUE THREAD

**Issue by hwangdylan** [neovim/neovim#12126]
- `nvim --version`: v0.3.7
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: MAC 10.15
- Terminal name/version: ZSH
- `$TERM`: xterm-256color

When  I set:
```
set shortmess="shm=a"
```
In the config file, the number of matches does not appear in the bottom right hand corner of the window. I am expecting something along the lines of [1/20] in the bottom right, showing which match I am currently looking at. 

When using the builtin vim, it works just fine but not with neovim.

**Comment by teto** [comment]
Your neovim is pretty old, I don't know when it was introduced but master has it. try upgrading.

**Comment by hwangdylan** [comment]
Oh wow. I didn't even realize i was so far behind. I just updated and it worked. Thanks so much.
