### ISSUE TITLE
typescript: optional chaining breaks syntax highlight

### ISSUE THREAD

**Issue by adario7** [neovim/neovim#12125]
- broken on `nvim --version`: 0.4.3
- works as expected in `vim -u DEFAULTS` (version: 8.2)
- Operating system/version: Linux

### Steps to reproduce using `nvim -u NORC`

Edit any typescript file which uses the conditional field access operator (`?.`, introduced in TS 3.7).
Code examples:
```ts
// here syntax highlighting is broken from the operator to the end of the line
let d1: number = this.date_from?.valueOf();
```
```ts
// here syntax highlighting is broken from the operator to the end of the file
this.formLapses.push(new FormGroup({
	date_from: new FormControl(lapse?.date_from, [Validators.required]),
	date_to: new FormControl(lapse?.date_to, [Validators.required]),
}));
```

### Actual behaviour

The chaining operator breaks syntax highlighting.

### Expected behaviour

The operator is treated like the normal field access operator (`.`), and does not break the syntax.

**Comment by glacambre** [comment]
Syntax highlighting is done through runtime files, which Neovim doesn't maintain. This issue thus belongs to Vim's repository (but you shouldn't open issues about runtime files in Vim - see [this document](https://github.com/vim/vim/blob/master/CONTRIBUTING.md#syntax-indent-and-other-runtime-files) to learn what to do).

**Comment by adario7** [comment]
Thanks for the information.
Neovim seems to be using an older version of the runtime files (`Last Change: 2019 Jun 07`) compared to Vim one's (`Last Change:2019 Nov 30`), and I guess that is the problem.

**Comment by tristan957** [comment]
@glacambre Can I submit a pr to update the TypeScript files?

**Comment by glacambre** [comment]
@tristan957 I don't know. I believe @janlazo is an expert on porting changes from Vim to NeoVim, perhaps he knows the answer?

**Comment by tristan957** [comment]
hmm yea if it is going to require code changes I am definitely not the guy :(. New to vimscript (as far as .vimrc goes) and never used Lua, although maybe I will learn it at some point. I just started getting into neovim for full dev, but the optional chaining bug is throwing me off a bit.

**Comment by janlazo** [comment]
Refer to https://github.com/neovim/neovim/pull/12497 on how to cherry-pick runtime patches without affecting neovim tooling.

```sh
> ./scripts/vim-patch.sh -L -- 'runtime*typescript.vim'
96f45c0b6fc9e9d404e6805593ed1e0e6795e470
09c6f265b21065ffa9437837b1d0955137175e45
91359014b359cf816bf943fe2c7d492996263def
```

https://github.com/vim/vim/commit/96f45c0b6fc9e9d404e6805593ed1e0e6795e470#diff-59fe1c17c378642cb8bf525345773ba3
https://github.com/vim/vim/commit/09c6f265b21065ffa9437837b1d0955137175e45#diff-71ab10ad5a4244b0e266f5ff9656d0f0
https://github.com/vim/vim/commit/91359014b359cf816bf943fe2c7d492996263def#diff-71ab10ad5a4244b0e266f5ff9656d0f0

I don't know if the `typescript.vim` depend on other runtime patches and filetype plugins like javascript, jsx, xml.
If you use Vim packages (`:h packages`) or a plugin manager, you can use https://github.com/HerringtonDarkholme/yats.vim in the meantime. This repo provides the same indent,syntax runtime files. If the latest commit of that repo is compatible with Neovim's `runtime`, then it's safe to cherry-pick only `typescript.vim` changes.
