### ISSUE TITLE
LSP rename - handle changed buffers properly

### ISSUE THREAD

**Issue by weilbith** [neovim/neovim#12129]
Hey guys,

thanks for the absolutely awesome in-built LSP support! I waited a while for some follow-ups and now I started to checkout the features and play around. 

What I consider as one of the most useful commands is the renaming. Before I used `far.vim`, but of course that isn't the same. During testing I observed the following behavior: the `vim.lsp.util.apply_workspace_edit` function applies changes to not open buffers, if the LSP requires that due to a refactoring. So far so good. But these buffers end up as modified and hidden. So I'm in the situation where I don't know how to handle that. I fist must recognize that after I requested the renaming, there are such buffers. I mean I have no clue how broad my requested change will be. Afterwards  I must save these buffers somewho. `:wa` would do it, but probably do more than that. So I would rather love to extend the default callback function and just save the affected buffers. But then there is the special case of an open modified buffer that should receive refactor changes. Maybe the user did not save the buffer on purpose?

So after all I would just like to ask for a recommendation and some tips how to handle this? How do you do it? Thanks for any help!

**Comment by teto** [comment]
so you would prefer:
- to see a preview of the changes
- to modify but not load the not opened files

As for the already opened files, I believe you just have to save all the changes anyway before a refactoring. Mixing different kind of changes doesn't look smart.

This kind of advanced behavior is a better fit for external plugins for now, such as 
https://github.com/haorenW1025/diagnostic-nvim .
We need to focus on providing robust basics for the lsp system in neovim and there are more low-level matters to fix before addressing this kind of scenario.

**Comment by weilbith** [comment]
Thanks for the fast response! :smiley: 

> so you would prefer:
> - to see a preview of the changes

No I barely care about a preview. I trust the language server. In fact it is more the opposite: I want to execute the renaming don't care about the saving.

> - to modify but not load the not opened files

Yes. See above.

> We need to focus on providing robust basics for the lsp system in neovim and there are more low-level matters to fix before addressing this kind of scenario.

That is true. It wasn't my intention to ask for a feature in first place. More for best practice, because I thought that this must be a general problem. :shrug: 
So I must consider to extend/adjust the client callback. :thinking: 

Thanks for your help. I close the issue since I think there is nothing to continue here by your statement. Anyways I would be happy if anyone stumbling over this issue could leave a comment if they have some noteworthy tips.

**Comment by weilbith** [comment]
For those who are interested:

I started to play around and customize the LSP callbacks. I also "fixed" the mentioned problems for the renaming. The basic function looks like this. I hope the naming is expressive enough. Else [here](https://github.com/weilbith/vim-blueplanet/blob/393d691bf8fe05e80ab69c29f2f890af5e458594/lua/custom/lsp/callbacks.lua#L28) is a maybe not so stable link to the code. It is my first time writing any Lua code, so please forgive me my sins and just get inspired. :wink:

```lua
function M.extendRenameCallback()
    local request_name = "textDocument/rename"
    local original_callback = lsp.callbacks[request_name]

    lsp.callbacks[request_name] = function(err, method, workspace_edit, _)
        local original_buffer_list = api.nvim_list_bufs()

        if lsp_utils.check_if_rename_leaves_workspace_inconsistent(workspace_edit) then
            lsp_utils.attempt_to_clean_workspace(original_buffer_list, workspace_edit)
            return
        end

        original_callback(err, method, workspace_edit)
        lsp_utils.save_buffers_affected_by_rename(workspace_edit)
        lsp_utils.avoid_nvim_lsp_plugin_issues()
        lsp_utils.wipe_buffers_loaded_for_rename(original_buffer_list, workspace_edit)
        print("Rename done. All buffers saved and eventually removed again.")
    end
end
```
