### ISSUE TITLE
UI: Change Tab Closing Symbol from X to ×

### ISSUE THREAD

**Issue by smhmd** [neovim/neovim#12148]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Linux manjaro 5.5.16-1-MANJARO
- Terminal name/version: st 0.8.2
- `$TERM`: st-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -p file1 file2
```

### Actual behaviour
Tab closing symbol at the top right is `X` which is a bit ugly.

### Expected behaviour
Have `×` as the closing symbol, instead.

**Comment by teto** [comment]
you can modify it in screen.c draw_tabline `grid_putchar(&default_grid, 'X', 0, Columns - 1, attr_nosel);` you can also generate your own tabline via `set tabline`. Maybe airline has a setting for it.
The character might be too small for a change.

**Comment by smhmd** [comment]
I'll try to find more UI elements (or issues about UI elements) that could all be changed at once. Would that be acceptable and warrant a change, @teto? (I'm a bit busy doing research, so it could take a while.)

**Comment by teto** [comment]
not sure what you mean, one of the goal of neovim is to allow different User Interfaces (UIs) to handle the display. The tabline can already be overriden so you can find different GUIs with a different display than the terminal one. 
You can check https://github.com/neovim/neovim/issues?q=is%3Aopen+is%3Aissue+label%3Aui-ext for UI elements that are not `externalized` yet.
