### ISSUE TITLE
Completion list and tabline are colorless under Win10

### ISSUE THREAD

**Issue by zz-Jade** [neovim/neovim#12147]
Nvim 0.5.0(qt)
Win10
![1](https://user-images.githubusercontent.com/45595055/79636458-5ba22d80-81aa-11ea-9059-9294f62c9864.png)

**Comment by zz-Jade** [comment]
coc.nvim for Completion, airline for tabline

**Comment by erw7** [comment]
neovim-qt uses `ext_popupmenu` by default. In the case of `ext_popupmenu`, no highlighting information is passed, so no highlighting is applied to the popup menu. If you want to apply neovim highlights to the popup menu, fortunately neovim-qt has a `--no-ext-popupmenu` command line option that disables the `ext_popupmenu`, so use this.

**Comment by zz-Jade** [comment]
I type "nvim-qt --no-ext-popupmenu" ,the completion list works but the tabline still doest work，how could I fix it
![无标题](https://user-images.githubusercontent.com/45595055/79683864-94e8a500-825f-11ea-887c-fcc251f0d3cf.png)

**Comment by zz-Jade** [comment]
I got it ，nvim-qt --no-ext-popupmenu --no-ext-tabline can solve it, thanks.
