### ISSUE TITLE
Autoloaded inputlist() does not prompt 

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#12144]
Please create the following `init.vim`:
```vim
filetype off
let s:dir = expand('<sfile>:p:h')
let &runtimepath .= ',' . s:dir
let &packpath = &runtimepath
filetype plugin indent on
syntax enable
set noswapfile

function! s:testInputlist() abort
  " echoerr 'After uncommenting this, inputlist() below prompts'
  let b:choice = inputlist([1,2,3])
  return
endfunction

augroup test
  autocmd!
  autocmd FileType sh call s:testInputlist()
        \ | echoerr 'expected inputlist before, b:choice was set to '.b:choice
augroup END
```
and run `nvim -u init.vim x.sh`.

`inputlist()` used there returns `0` without any prompt.

Please also uncomment `echoerr`.

edit: I tested on `neovim-0.5.0+ubuntu1+git202004162108-fb4c7a5-00e710e` from deb package.

**Comment by erw7** [comment]
This is because `F` is included in default of `shortmess` in neovim, it is not a bug. Add the following line to init.vim and you should get the behavior you expect.

```vim
set shortmess-=F
```

**Comment by przepompownia** [comment]
Thanks for explaining.
