### ISSUE TITLE
Syntax event is not triggered by syntax off

### ISSUE THREAD

**Issue by Dupond** [neovim/neovim#12149]
Hello,

As explained [here](https://vi.stackexchange.com/questions/24650/how-to-disable-highlighting-for-custom-group), the `Syntax` event for `autocmd` doesn't seem to be triggered when I set `:syntax on` or `:syntax off`.

- `nvim --version`:
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compilé par builduser
Features: +acl +iconv +tui

- `vim -u DEFAULTS` (version: ) behaves differently? NO
- Operating system/version: Arch Linux 5.6.4
- Terminal name/version: rxvt-unicode 9.22-9
- `$TERM`: tmux

### Steps to reproduce using `nvim -u NORC`

Add the following to your `.vimrc` or `init.vim` file :

```
function! Test()
	echo "This is a test."
endfunction
autocmd Syntax * call s:Test()
```

Save the file, exit and re-start Neovim. Type `:syntax off` or `:syntax on` a few times.

### Actual behaviour

Nothing happens.

### Expected behaviour

It should display "This is a test." each time `syntax` is set.

**Comment by Dupond** [comment]
In fact, it seems like this is intended : the `Syntax` event is only triggered with `syntax on`, not whith `syntax off`.
Well, maybe it would make sense to trigger it for `syntax off` too, so that it would be easy for example to disable spellchecking, custom `match` definitions, etc. with a single `syntax off` command.

**Comment by zeertzjq** [comment]
`:syntax off` doesn't change the 'syntax' option. It removes `Syntax` autocommands.
