### ISSUE TITLE
 Show signs on folded regions

### ISSUE THREAD

**Issue by petRUShka** [neovim/neovim#12153]
Idea is to add ability for vim to display signs (optionally?) for/with folds.

- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
```

- `vim -u DEFAULTS` (version: ) behaves differently?

same behaviour but there is an issue: https://github.com/vim/vim/issues/5949

- Operating system/version: Arch Linux (up to date at the moment)
- Terminal name/version: uvxterm
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Install [vim-gitgutter](https://github.com/airblade/vim-gitgutter) plugin.
2. Change any file withing git repository.
3. Look at the signs showing that there are changes
4. Fold changed lines.
5. Watch nvim with no signs at all.

### Actual behaviour

No signs on folded lines.

### Expected behaviour

Ability to have signs on folded lines.

### Additional details

Why it is reasonable? There is plugin [vim-gitgutter](https://github.com/airblade/vim-gitgutter) that show signs on the changed lines but not on folded area. 

More details. Suppose we have a buffer with changes within fold. There is no sign on left column in case of closed fold (take a look at lines 17-20):

![2019-09-23-232820_162x208_scrot](https://user-images.githubusercontent.com/146893/65460716-30956c80-de5b-11e9-95f0-9e888c083929.png)

In case of opened fold one can see `+` sings:

![2019-09-23-233910_145x271_scrot](https://user-images.githubusercontent.com/146893/65460795-5c185700-de5b-11e9-89ba-89ae800a6054.png)

So when fold is closed one doesn't see any changes at all. 

Feature request to give plugins ability to place signs on a folded region (plugin-developers cannot help, see [vim-gutter#655](https://github.com/airblade/vim-gitgutter/issues/655)).

**Comment by teto** [comment]
you can now see signs in front of folded lines but the sign has to be placed exactly on the folded line otherwise it won't show up.
I am not sure there is a good enough logic to aggregate signs in the folded region and show only the unique version ?

**Comment by lewis6991** [comment]
I've implemented this feature as a plugin https://github.com/lewis6991/foldsigns.nvim

Given the fact that you would want to configure this behaviour per sign type I don't think this functionality should be a part of core and the linked plugin should be the accepted resolution to this issue.

**Comment by lewis6991** [comment]
Can we consider this resolved?
