### ISSUE TITLE
New cpoptions flag to make "dge" more consistent?

### ISSUE THREAD

**Issue by KKPMW** [neovim/neovim#12154]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?: no
- Operating system/version: macOS 10.15.3
- Terminal name/version: iTerm2 3.3.9
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Start with this file:

```
word1 word2
```

### Actual behaviour

Here is the behaviour of different `<delete>` + `word-motion` commands

```
word1 word2        de:  wo word2         dw:   woword2
  ^

word1 word2        db:  word1 rd2        dge:  wordd2
        ^
```

### Expected behaviour

`dge` seems to be inconsistent in 2 ways:

- It deletes the character the cursor is on (inconsistent with `db`)
- It deletes the last character of the previous word (inconsistent with `dw`)

The expected behaviour for the above case would be:

```
word1 word2        dge:  word1rd2
        ^
```

Maybe there is a room for adjusting this behaviour in a similar fashion as was done with  
`set cpoptions-=_`

**Comment by justinmk** [comment]
Doesn't look like there is interest in this.
