### ISSUE TITLE
undefined reference to `vterm_state_convert_color_to_rgb' when building neovim v0.4.3

### ISSUE THREAD

**Issue by dmelo** [neovim/neovim#12160]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Linux 5.5.10-100.fc30.x86_64 - Fedora 30
- Terminal name/version: XTerm(350)
- `$TERM`: xterm-256color

Trying to build nvim on my system `make CMAKE_BUILD_TYPE=RelWithDebInfo USE_BUNDLED=OFF` gives the following error:
```
[100%] Linking C executable ../../bin/nvim
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find abbrev number 37
/tmp/nvim.EPmVxQ.ltrans4.ltrans.o: in function `get_rgb':
<artificial>:(.text+0x267a): undefined reference to `vterm_state_convert_color_to_rgb'
collect2: error: ld returned 1 exit status
make[3]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:3286: bin/nvim] Error 1
make[3]: Leaving directory '/home/dmelo/proj2/neovim/build'
make[2]: *** [CMakeFiles/Makefile2:2629: src/nvim/CMakeFiles/nvim.dir/all] Error 2
make[2]: Leaving directory '/home/dmelo/proj2/neovim/build'
make[1]: *** [Makefile:172: all] Error 2
make[1]: Leaving directory '/home/dmelo/proj2/neovim/build'
make: *** [Makefile:86: nvim] Error 2

```

I have libvterm-devel-0-0.8.bzr681.fc30.x86_64 installed on my system.

**Comment by erw7** [comment]
> I have libvterm-devel-0-0.8.bzr681.fc30.x86_64 installed on my system.

The latest version of `libvterm` is 0.1.3. I think version 0.8 is an error in creating the package and the real version is 0.0.8. So maybe the version of `libvterm` is too old and there is an error? 0.1.0 or later version of `libvterm` is required. Why don't you try building a `libvterm` version 0.1.0 or later instead of a package?

**Comment by dmelo** [comment]
The wrong version of the libvterm were located on the neovim/.deps . After deleting it, and installing the 0.1.3, everything went OK. Thanks @erw7
