### ISSUE TITLE
move "g:netrw_home" to $XDA_DATA_HOME/nvim/

### ISSUE THREAD

**Issue by karoliskoncevicius** [neovim/neovim#12161]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: 8.1) behaves differently? yes - it puts it in ~/.vim/
- Operating system/version: macOS 10.15.3
- Terminal name/version: iTerm2 3.3.9
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:Explore
< move somewhere across directories >
< close neovim >
< go to $XDA_CONFIG_HOME/nvim/ >
< ls -a >
< .netrwhist file is there >
```

### Actual behaviour

`.netrwhist` by default is created in `$XDA_CONFIG_HOME/nvim/`. To me it looks like it doesn't belong there. It is not config data, but rather a dump representing a variable state.

### Expected behaviour

Change default setting of `g:netrw_home` to `$XDA_DATA_HOME/nvim/ ` so that`.netrwhist` is placed among other types of variable data.

**Comment by teto** [comment]
doing this natively may be problematic for users that use both vim/neovim so I don't think it's a good idea.

**Comment by KKPMW** [comment]
@teto I do not see why would that be problematic. For vim the file is in different directory anyway (it is in .vimrc/). So it is not shared between vim and neovim. Or did I miss something?

**Comment by teto** [comment]
indeed, the code/help shows netrw_home is set to `default: the first directory on the |'runtimepath'|`.
I agree `$XDA_DATA_HOME/nvim/` (or `stdpath('data')` in vimscript) would be a better default. 
I will leave the decision pending as it's easy to fix locally and not sure how we deal with `netrw` (which has a bad reputation in general).
