### ISSUE TITLE
LspDiagnostics<Level>Sign is redefined all the time

### ISSUE THREAD

**Issue by wackbyte** [neovim/neovim#12162]
- `nvim --version`: `NVIM v0.5.0-447-g8745247cb`
- `vim -u DEFAULTS` (version: ) behaves differently? I don't have `vim` installed.
- Operating system/version: Arch Linux (rolling release)
- Terminal name/version: Alacritty 0.4.2
- `$TERM`: `screen` (in `tmux`)

### Steps to reproduce

1. Install the `nvim-lsp` plugin using `vim-plug`.
```vim
call plug#begin('wherever/your/plugin/directory/is')
Plug 'neovim/nvim-lsp'
call plug#end()
```
2. Setup `rust-analyzer` in your `init.vim` (it'll probably work with any other language server supported by `nvim-lsp`, though).
```vim
lua require("nvim_lsp").rust_analyzer.setup({})
```
3. Define the signs in your `init.vim`.
```vim
sign define LspDiagnosticsErrorSign text=!
sign define LspDiagnosticsWarningSign text=?
sign define LspDiagnosticsInformationSign text=i
sign define LspDiagnosticsHintSign text=.
```
4. Open a Rust file.
5. Error, warning, information, and hint diagnostics should be appear in the sign column as their defaults (`E`, `W`, `I`, and `H`, respectively).

#### Complete `init.vim`

```vim
call plug#begin('wherever/your/plugin/directory/is')
Plug 'neovim/nvim-lsp'
call plug#end()

lua require("nvim_lsp").rust_analyzer.setup({})

sign define LspDiagnosticsErrorSign text=!
sign define LspDiagnosticsWarningSign text=?
sign define LspDiagnosticsInformationSign text=i
sign define LspDiagnosticsHintSign text=.
```

### Actual behaviour

Diagnostics in the sign column appear as their default values.

### Expected behaviour

Diagnostics in the sign column appear as the signs defined in step 3.

**Comment by jakbyte** [comment]
You can still set the text of the signs by setting the global values, but I don't know if you can change the styling.

**Comment by jakbyte** [comment]
Also, it looks like [the signs are being set back to their default values here](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L836-L839).

**Comment by tjdevries** [comment]
If anyone wants to fix this, I think the solution would just be:

1. Check if sign exists (can use `sign_getdefined`)
2. If it already exists, don't create the sign again (this allows easy override)
3. Else, define it (while still checking for the global var).

Optionally, we can remove the global var entirely and just tell people to define the signs.

We might not have to check for them every time we call this function, but it's fine for now if there's not a better place for it atm.

**Comment by 573** [comment]
I would like to ask to reopen that ticket.

I set
```
vim.fn.sign_define("LspDiagnosticsSignError", {text="!", texthl="LspDiagnosticsError"})
vim.fn.sign_define("LspDiagnosticsSignWarning", {text="?", texthl="LspDiagnosticsWarning"})
vim.fn.sign_define("LspDiagnosticsSignInformation", {text="i", texthl="LspDiagnosticsInformation"})
vim.fn.sign_define("LspDiagnosticsSignHint", {text=".", texthl="LspDiagnosticsHint"})
```
and still the other signs are shown in the bar in the left area.

**Comment by korney4eg** [comment]
@tjdevries it's pretty old, but still reproducible on version `0.6` should I create new issue for it?

**Comment by mjlbach** [comment]
These highlight groups aren't used anymore as of the diagnostic rewrite

**Comment by korney4eg** [comment]
@mjlbach I think I find resolution https://github.com/neovim/nvim-lspconfig/wiki/UI-customization#show-line-diagnostics-automatically-in-hover-window . Recommend to everyone who come here to check how to redefine their diagnostic signs.
