### ISSUE TITLE
LSP - peek definition callback execution error and window issues

### ISSUE THREAD

**Issue by weilbith** [neovim/neovim#12166]
- `nvim --version`: `v0.5.0-455-g6c9a5743a`
- Operating system/version: `5.5.11-arch1-1`
- Terminal name/version: `kitty 0.17.0`
- `$TERM`: `xterm-256color`

### Steps to reproduce

- open a file and attach language client to buffer
- make sure the language server supports the `textDocument/peekDefinition` method
- goto a symbol and call `:lua vim.lsp.buf.peek_definition()`

### Actual behaviour

1. Raises an execution error. The `vim.lsp.callbacks` tries to call
   `vim.api.nvim_buf_add_highlight()` with 5 instead of 6 parameter.

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/callbacks.lua:164: Expected 6 arguments
```

2. The callback opens two floating windows. One with the actual code and on top
    a second window with the header `Peek:`. The latter it off position, wafting above
    the first window with a gap in-between. Furthermore does it not apply the
    same offset for the x-axis and is therefore slightly shifted to the left.

Here is a dump example as screenshot:

![screenshot_1587590398](https://user-images.githubusercontent.com/12543647/80035211-f32bb700-84ef-11ea-80ce-faa145c7987b.png)

### Expected behaviour

1. No error occurs and the header gets highlighted.
2. Both windows stack aligned on top of each other.

**Comment by teto** [comment]
I am thinking of removing the peek request as it seems to be vscode specific. Would you like to do it :p ? otherwise feel free to close this.
