### ISSUE TITLE
Cannot assign v:false to boolean options

### ISSUE THREAD

**Issue by taotao54321** [neovim/neovim#12174]
When I set boolean options using `let`, they accept `v:true` but not `v:false`.
Nvim says `E521: Number required: &ignorecase = 'false'`.

- `nvim --version`: NVIM v0.5.0-456-gdeb4566ca
- `vim -u DEFAULTS` (version: ) behaves differently? NO
- Operating system/version: Debian testing, linux-image-5.5.0-1-amd64
- Terminal name/version: alacritty 0.4.2
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
:let &ignorecase = v:true   " OK
:let &ignorecase = v:false  " E521: Number required: &ignorecase = 'false'
```

### Actual behaviour

Boolean options accept `v:true`, but not `v:false`.

### Expected behaviour

Boolean options should accept both `v:true` and `v:false`.

**Comment by teto** [comment]
@chrisbra is that expected ?

**Comment by chrisbra** [comment]
looks like a bug to me

**Comment by justinmk** [comment]
https://github.com/vim/vim/commit/65d032c779a43b767497e15e6a32d04a6a8fa65d

**Comment by ScarletAndBlacke** [comment]
it is an question.

**Comment by teto** [comment]
fix was merged.
