### ISSUE TITLE
LSP Jump-to-definition does not work for ghcide (Haskell LSP)

### ISSUE THREAD

**Issue by offendo** [neovim/neovim#12175]
Hello friends,

- `nvim --version`:
```
NVIM v0.5.0-428-g46fdad255
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
- Operating system/version: ArchLinux 
- Terminal name/version: `io.elementary.terminal` (pantheon default terminal)
- `$TERM`: `xterm-256color`

### Steps to reproduce 
- Install ghcide (currently using most recent version, compatible with ghc-8.6.5)
- Use this minimal `init.vim` with `vim-plug`, or whatever your heart desires
``` vim
" install plugin 
call plug#begin( '~/.config/nvim/bundle')
  Plug 'neovim/nvim-lsp'
call plug#end()

lua require('nvim_lsp').ghcide.setup{}

" just for ease of use
nnoremap <silent>gd    <cmd>lua vim.lsp.buf.definition()<CR>
```
then in sample Haskell project
``` haskell
module Test
    where
main :: IO ()
main = putStrLn $ test "neovim devs!"  -- press gd while on "test"

test :: String -> String
test x = "Hello " ++ x
```

### Actual behaviour
`Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:324: attempt to index local 'location' (a nil value)`
### Expected behaviour
Jumping to definition 

The problem occurs here in `callbacks.lua`:

``` lua
local function location_callback(_, method, result)
  if result == nil or vim.tbl_isempty(result) then
    local _ = log.info() and log.info(method, 'No location found')
    return nil
  end

  util.jump_to_location(result[1]) -- Here !!

  if #result > 1 then
    util.set_qflist(util.locations_to_items(result))
    api.nvim_command("copen")
    api.nvim_command("wincmd p")
  end
end
```
where neovim expects `result` to be a list of results, but ghcide only provides a singular result for whatever reason. If it's changed to this: 
``` lua
local function location_callback(_, method, result)
  if result == nil or vim.tbl_isempty(result) then
    local _ = log.info() and log.info(method, 'No location found')
    return nil
  end
-- new code begins
  if #result == 0 then 
      util.jump_to_location(result)
  elseif #result == 1 then
      util.jump_to_location(result[1])
   end
-- new code ends
  if #result > 1 then
    util.set_qflist(util.locations_to_items(result))
    api.nvim_command("copen")
    api.nvim_command("wincmd p")
  end
end
```
it works as intended. Maybe a bit hackish though, not familiar enough with either ghcide or the neovim LSP code to know what is actually wrong (if anything). Hope your quarantine is going well :)

**Comment by tjdevries** [comment]
The code looks pretty good! Would you be interested in making a PR for it and then adding a test? This happens in some other places as well where it's possible to get a list of results back or a single result, so it's not uncommon.

**Comment by teto** [comment]
thanks for the good report. Could you try with latest master, the commit 0c637898f991ff9b90e695065a0136dd9c37106a may solve the issue IIRC.

**Comment by offendo** [comment]
Tested on master - commit https://github.com/neovim/neovim/commit/0c637898f991ff9b90e695065a0136dd9c37106a indeed fixes the issue. Thanks for the quick responses!
