### ISSUE TITLE
Shada takes very long time to write (>3s) on windows even when <100 lines. 

### ISSUE THREAD

**Issue by harshad1** [neovim/neovim#12179]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Windows 10
- Terminal name/version: Powershell 5.1 
- `$TERM`: Behavior persists with conemu, cmder etc

#### Neovim takes a long time to quit:
1. Open neovim wit `nvim -u NORC`
2. Close neovim (for example with `:q`)

Expected: Neovim closes fast
Observed: Takes 3-5 seconds to close

#### Disabling shada fixes the issue
1. Open neovim with `nvim -u NORC -i NONE`
2. Close neovim 

Expected: Closes instantly
Observed: Closes instantly

#### Shada takes long time to write
1. Open neovim with `nvim -u NORC`
2. Execute `:wshada`

Expected: Write finishes fast
Observed: Write take 3-5 seconds

#### Deleting shada does not help (issue is not due to large shada)
1. Delete main.shada file
2. Open neovim
3. Close neovim
    - Neovim Closes fast
4. Open neovim again
5. Close neovim again
    - Neovim takes 3-5s to close
    - shada is under 100 lines long

**Comment by teto** [comment]
could you try with master ?

**Comment by justinmk** [comment]
does it happen with `nvim -u NONE` (not NORC)? NORC still loads any "pack" plugins you may have...

- Try `:set nofsync`
- try the development version as @teto suggested
- doesn't happen for me, so if none of the above works I assume it's antivirus or a network share or some other slow partition. PR welcome if you find otherwise.

**Comment by harshad1** [comment]
nofsync does not help
nvim -u NONE does not work

I will try master and see if I can reproduce this on a machine that does not have the same antivirus config.

**Comment by Daydreamer-riri** [comment]
Hi @justinmk, `:set nofsync` 对我管用。这有什么影响吗？我是否应该一直设置它？
