### ISSUE TITLE
Problem connecting with the luasocket library

### ISSUE THREAD

**Issue by Danoloan10** [neovim/neovim#12188]
I am trying to connect from the nvim lua interpreter to a TCP socket. I have linked the socket library of lua 5.1 in the system to /usr/local/lib/lua/ and /usr/local/share/lua/, the paths of the nvim interpreter. This code executes as expected, printing the line received by the server, if I run it in standalone lua, but not with the nvim interpreter.
local socket = require("socket")
```
local socket = require("socket")

function docon()
	local conn = assert(socket.connect("127.0.0.1", 2022))

	local msg, err = conn:receive("*l")
	if err then
		print(err)
	else
		print(msg)
	end

	conn:close()
end

docon()

```

This is the server used to test the connection. I run it in the standalone interpreter:

```
local socket = require 'socket'
local server = socket.tcp()

server:bind("127.0.0.1", 20220)
server:setoption('reuseaddr', true)
server:listen()

while(true) do
	local conn = server:accept()
	conn:send("hola\n")
        conn:close()
end
```

When executing the function `docon()` in the nvim interpreter, I get the following output:
```
El otro extremo de la conexión no está conectado
```
The message is in spanish because of the localization of my system, but the message translates roughly to:
```
The other end of the connection is down
```
As I said, the lua standalone interpreter prints `hola` as expected.

**Comment by teto** [comment]
dunno if it's a typo but you try to connect on the wrong port 2022 != 20220
