### ISSUE TITLE
[LSP] Newlines in `textEdits` not handled correctly

### ISSUE THREAD

**Issue by ckipp01** [neovim/neovim#12195]
- `nvim --version`: NVIM v0.5.0-fc98f2d
- Operating system/version: MacOS
- Terminal name/version: iTermw
- `$TERM`: fish

### Steps to reproduce

With any current setup, trigger a completion that contains a `textEdit` that contains a newline in it. For example, this is what the completion option coming in would look like:

```json
    {
      "label": "match (exhaustive)",
      "kind": 8,
      "detail": " Foo (2 cases)",
      "sortText": "00001",
      "filterText": "match (exhaustive)",
      "insertTextFormat": 1,
      "textEdit": {
        "range": {
          "start": {
            "line": 14,
            "character": 7
          },
          "end": {
            "line": 14,
            "character": 11
          }
        },
        "newText": "match {\n\tcase Bar() \u003d\u003e\n\tcase Car() \u003d\u003e\n}"
      },
```

Notice that the `newText` has multiple `\n` in it.

### Actual behaviour

This `newText` ends up being inserted like below:

```scala
test match {^@  case Bar() =>^@ case Car() =>^@}
```

### Expected behaviour

I would expect the newlines to be taken into account and to see the following:

```scala
test match {
  case Bar() =>
  case Car() =>
}
```

**Comment by mjlbach** [comment]
@ckipp01 is this still an issue? We fixed some things around new text insertion.

**Comment by ckipp01** [comment]
Just removed my snippet plugin to see and yea, it looks like this is fixed. This is the completion listed up above that had issues in the past:

![2021-09-27 10 35 22](https://user-images.githubusercontent.com/13974112/134873679-4b72ecab-fb35-4cf0-b8c4-a86219afe7e1.gif)

And it seems to handle the newlines fine new.

👍🏼

**Comment by mjlbach** [comment]
Awesome! Glad its fixed :)
