### ISSUE TITLE
Background FIFO

### ISSUE THREAD

**Issue by DoctorApparatus** [neovim/neovim#12197]
For automating personal workflows it would be extremely useful being able to run scripts in the background which can read from a file. Each vim sesion/buffer/tab would need an id.

For example having a fifo in some folder in the home directory and piping commands or keychains or whatever is possible basically.

Managed to emulate that behavior with Tmux and will be releasing a plugin soon.

Native support would be welcome

**Comment by justinmk** [comment]
? This is already possible with `jobstart()` etc. Be specific if there is something missing precisely, say what you tried that didn't work, etc. For usage questions see https://vi.stackexchange.com/
