### ISSUE TITLE
Wrong colors used for GUI cursor

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#12198]
- `nvim --version`: NVIM v0.5.0-445-gca02db1f9

### Steps to reproduce using `nvim -u NORC`

When used with `nvim -u NORC`, neovim sends the following GUI events:

<details>
<pre>
["default_colors_set", [16777215,0,16711680,0,0]],
["hl_attr_define",
        [1,{},{}, []],
        [2,{"foreground":13882323,"background":11119017},{"foreground":7,"background":242}, []],
        [3,{"bold":true,"background":16711680},{"bold":true,"background":9}, []],
        [...]
        [7,{"bold":true,"foreground":255},{"foreground":12}, []],
        [...]
        [57,{"foreground":11393254},{}, []]],
["default_colors_set", [16777215,0,16711680,0,0]]
["grid_line",
        [1,1,0, [["~",7], [" ",7,81]]],
        [1,2,0, [["~",7], [" ",7,81]]],
        [1,3,0, [["~",7], [" ",7,81]]],
        [...]
        [1,19,0, [[" ",1,82]]]],
[["mode_info_set", [true, [
        {"mouse_shape":0,"cursor_shape":"block","cell_percentage":0,"blinkwait":0,"blinkon":0,"blinkoff":0,"hl_id":0,"id_lm":0,"attr_id":0,"attr_id_lm":0,"name":"normal","short_name":"n"},
        {"mouse_shape":0,"cursor_shape":"block","cell_percentage":0,"blinkwait":0,"blinkon":0,"blinkoff":0,"hl_id":0,"id_lm":0,"attr_id":0,"attr_id_lm":0,"name":"visual","short_name":"v"},
        [...],
        {"cursor_shape":"block","cell_percentage":0,"blinkwait":0,"blinkon":0,"blinkoff":0,"hl_id":0,"id_lm":0,"attr_id":0,"attr_id_lm":0,"name":"showmatch","short_name":"sm"}]]],
        ["mode_change",["normal",0]],["flush",[]]]
</pre>
</details>

These messages mean:
- default_colors_set: set foreground to white, background to black
- define highlights: highlight attribute 1 should use default colors (white foreground, black background), attribute 7 should use a blue foreground and a black background
- grid_line: start drawing `~` with highlight 7 on row 1, column 1, fill the rest with empty space with highlight 7.
- mode_info_set: in normal mode, the cursor's highlight should use attribute 0 (default colors)

So basically, neovim tells the UI that the screen should be black and that the cursor should be black too? This doesn't seem right. How do current GUIs know what color the cursor should be?

- Firenvim ignored mode_info_set colors until yesterday: https://github.com/glacambre/firenvim/commit/756a54d733edf6ce0baed2e6d2f8e98d5ddc1964
- Onivim 1 ignored mode_info_set_colors: https://github.com/onivim/oni/blob/65d0e204557ff051d2ee593d9cb2026b03ed772e/browser/src/neovim/NeovimInstance.ts#L934
- Veonvim isn't using the default cursor color: https://github.com/veonim/veonim/blob/3cc2100845a342621440c8b9a2c8297b5c4a2e6d/src/neovim/startup.ts#L32
- Goneovim inverts background and foreground colors when using default values: https://github.com/akiyosi/goneovim/blob/0a6ac4a7805117a17a20f284b45c35fe29fd4bc8/editor/cursor.go#L152-L155
- Neovide also inverts background and foreground colors when defaults should be used: https://github.com/Kethku/neovide/blob/6c6e7867f90b7e6cae69b1fb026e9cf094e06e23/src/editor/cursor.rs#L62-L84

So the current behavior is wrong and confusing in my opinion. I would like it to be changed, but this is probably not worth the breakage it would induce. Just mentionning that background and foreground colors should be swapped when attr_id = 0 in `:h ui-global` would probably be enough.

**Comment by teto** [comment]
in shape.c all cursor highlights are initialized with hl_id 0.
Cursor is defined in syntax.c as `Cursor       guibg=fg guifg=bg`
guicursor is initialized with "n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20" , so without colors, because of the TUI probably, if you change this default to use `Cursor`, that could be better ? (and we could adapt the TUI code)

**Comment by justinmk** [comment]
> guicursor is initialized with "n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20" , so without colors, because of the TUI probably,

 because the cursor color is "system defined" by default. That's what `attr_id = 0` means IIRC... 



> Just mentionning that background and foreground colors should be swapped when attr_id = 0 in `:h ui-global` would probably be enough.

I thought we did somewhere...
