### ISSUE TITLE
Neovim 0.4.3 crashes when pasting text from clipboard

### ISSUE THREAD

**Issue by 1kit** [neovim/neovim#12205]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? YES
- Operating system/version: Fedora 4.9.76 kernel
- Terminal name/version: iterm + tmux
- `$TERM`:  xterm-256color

### Steps to reproduce using `nvim -u NORC`
Not reproducible with NORC. 
```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
#0  0x000000000072a595 in __strlen_avx2 ()
#1  0x00000000006d4e85 in get_cie_encoding ()
#2  0x00000000006d5779 in classify_object_over_fdes ()
#3  0x00000000006d5b48 in search_object ()
#4  0x00000000006d6556 in _Unwind_Find_FDE ()
#5  0x00000000006d2673 in uw_frame_state_for ()
#6  0x00000000006d3850 in uw_init_context_1 ()
#7  0x00000000006d4092 in _Unwind_RaiseException ()
#8  0x000000000066b70b in err_raise_ext (errcode=2) at lj_err.c:305
#9  lj_err_throw (L=0x41d6b378, errcode=errcode@entry=2) at lj_err.c:461
#10 0x000000000067c78a in lj_trace_err_info (J=<optimized out>, e=e@entry=LJ_TRERR_NYIFF) at lj_trace.c:48
#11 0x00000000006a4511 in recff_nyi (J=<optimized out>, rd=<optimized out>) at lj_ffrecord.c:112
#12 0x00000000006a676e in lj_ffrecord_func (J=J@entry=0x41d6b550) at lj_ffrecord.c:877
#13 0x00000000006a10b8 in lj_record_ins (J=J@entry=0x41d6b550) at lj_record.c:2078
#14 0x000000000067d2a0 in trace_state (L=0x41d6b378, dummy=<optimized out>, ud=0x41d6b550) at lj_trace.c:597
#15 0x0000000000687c2b in lj_vm_cpcall ()
#16 0x000000000067dd2b in lj_trace_ins (J=0x41d6b550, pc=pc@entry=0x41d6b4a4) at lj_trace.c:657
#17 0x00000000006703e8 in lj_dispatch_call (L=0x41d6b378, pc=0x41d6b4a8) at lj_dispatch.c:468
#18 0x000000000068932e in lj_vm_hotcall ()
#19 0x00000000006740c6 in lua_pcall (L=0x41d6b378, nargs=<optimized out>, nresults=0, errfunc=<optimized out>) at lj_api.c:1052
#20 0x0000000000523bf3 in nlua_enter ()
#21 0x0000000000528364 in executor_exec_lua_api ()
#22 0x00000000005f9722 in nvim_paste ()
#23 0x000000000044d914 in tinput_paste_event ()
#24 0x000000000058b5c9 in multiqueue_process_events ()
#25 0x00000000005de49a in insert_execute.lto_priv ()
#26 0x00000000004696bd in state_enter ()
#27 0x00000000005d056f in edit ()
#28 0x00000000004e8926 in invoke_edit.isra ()
#29 0x00000000004f286a in nv_edit.lto_priv ()
#30 0x0000000000502661 in normal_execute.lto_priv ()
#31 0x00000000004696f5 in state_enter ()
#32 0x00000000004f9290 in normal_enter ()
#33 0x0000000000403ce9 in main ()

**Comment by glacambre** [comment]
Can you reproduce this issue using neovim nightly?

If yes, since you can't reproduce this issue with a default config, could you comment bits of your config until you find what setting is making neovim crash?

**Comment by 1kit** [comment]
> Can you reproduce this issue using neovim nightly?
Sure, I can give it a try

I already tried commenting out parts of my config and this is what I found.

I use Plug to install various plugins. When I have a count of 11 "Plug ..." calls in my init.vim, things are fine. The moment, I exceed 11, it crashes when I insert from clipboard. I have tried various combinations of the plugins. So it is not any specific plugin. It is just the number. 
My .vimrc source my init.vim and I have the exact same dot files for vim8 and nvim. Vim8 works just fine for me.

**Comment by 1kit** [comment]
So I built the master and tried the nvim from there. The same problem persists.
The version I see is "NVIM v0.5.0-477-gf9055c585"

thanks

**Comment by glacambre** [comment]
@1kit if you can still reproduce this crash on master/nightly, please give us a way to reproduce it. You did not give us the content of your rc file :)

**Comment by teto** [comment]
will reopen if someone can post a repro with 0.6
