### ISSUE TITLE
cannot make latest version: commit e9cc383614d449b7269632c991525db77c387154

### ISSUE THREAD

**Issue by lukatendai** [neovim/neovim#12208]
[2/7] Generating usr/bin/busted
FAILED: usr/bin/busted 
cd /home/luke/workspace/neovim/.deps && /home/luke/workspace/neovim/.deps/usr/bin/luarocks build busted 2.0.0 CC=/usr/bin/cc LD=/usr/bin/cc

Error: Failed installing dependency: https://luarocks.org/lua-term-0.7-1.rockspec - Error fetching file: Failed downloading https://github.com/hoelzro/lua-term/archive/0.07.tar.gz - 0.07.tar.gz
Missing dependencies for busted 2.0.0-1:
   lua-term >= 0.1 (not installed)
   mediator_lua >= 1.1.1 (not installed)

busted 2.0.0-1 depends on lua-term >= 0.1 (not installed)
Installing https://luarocks.org/lua-term-0.7-1.rockspec

ninja: build stopped: subcommand failed.
make: *** [Makefile:101: deps] Error 1

**Comment by teto** [comment]
looks like a network error, I can fetch the file just fine. Try downloading again later.
