### ISSUE TITLE
Update stable PPA to Ubuntu 20.04

### ISSUE THREAD

**Issue by andradei** [neovim/neovim#12202]
- Operating system/version:
Lubuntu 20.04 fresh install

### Steps to reproduce using `nvim -u NORC`

On a fresh install of Lubuntu 20.04

```
sudo apt-add-repository ppa:neovim-ppa/stable
```

### Actual behaviour

Error message:

```
[ other info that aren't needed ... ]

E: The repository 'http://ppa.launchpad.net/neovim-ppa/stable/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Expected behaviour

The PPA would have a _Release file_ for 20.04 so the PPA can be added and `neovim` installed.

**Comment by justinmk** [comment]
@jamessan @fwalch

**Comment by jamessan** [comment]
Ubuntu 20.04 already has the latest nvim release.  There's no need for the PPA yet.

**Comment by andradei** [comment]
But it will be a need at some point right? As soon as a new `nvim` version is released and the official PPA isn't updated (which it probably won't for years).

I understand it is low priority right now, but could the issue stay opened so it can be tracked when the time comes?

Also, the documentation still reflects the custom PPA for Ubuntu 19.10 and below.

**Comment by jamessan** [comment]
Sure, at some point the PPA will be updated and at that point the new release will be added.

**Comment by fcanela** [comment]
Just as reminder, Ubuntu released the first point release yesterday. Some of us have dotfiles to install nvim using ppa so we are always using an updated version of our favorite editor. It would be great to avoid creating temporal hacks and rely on the official ppa from the start.

Thanks for all great work.

**Comment by fcanela** [comment]
I am not sure if I should open a new issue for bringing again attention to this topic after few months and the new point release (with the upgrade of all the previous 18.04 users).

**Comment by barkanido** [comment]
when is 0.5.0 expected to hit the PPA? https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable has 0.4.4-1 for 20.04

**Comment by jamessan** [comment]
Same answer as with every other release -- https://github.com/neovim/neovim/issues/12726#issuecomment-670670201

**Comment by barkanido** [comment]
Oh sorry @jamessan missed that. Any idea who is maintaining the Ubuntu PPA?

**Comment by jamessan** [comment]
Yes, I do, as the comment I linked to explains.
