### ISSUE TITLE
Error executing vim.schedule lua callback: Vim:E155: Unknown sign: LspDiagnosticsErrorSign

### ISSUE THREAD

**Issue by nerosnm** [neovim/neovim#12201]
- `nvim --version`:
```
﻿﻿﻿﻿﻿﻿﻿﻿NVIM v0.5.0-nightly
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200428-22985-1o8sq0l/build/config -I/tmp/neovim-20200428-22985-1o8sq0l/src -I/usr/local/include -I/tmp/neovim-20200428-22985-1o8sq0l/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200428-22985-1o8sq0l/build/src/nvim/auto -I/tmp/neovim-20200428-22985-1o8sq0l/build/include
Compiled by soren@Fafnir.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-c7d3630/share/nvim"

Run :checkhealth for more info
```
- nvim-lsp version(commit hash): don't know, installed through `vim-plug`
- `:checkhealth` result: All ok except an error about `$TERM` and missing Python 2 (but 3 is fine)
- What language server(If the problem is related to a specific language server): rust-analyzer
- Operating system/version: macOS Catalina 10.15.3 (19D76)
- Terminal name/version: Alacritty 0.4.2 (f68de37)
- `$TERM`: screen-256color

### How to reproduce the problem from neovim startup
- Install `rust-analyzer` from source
- Add `Plug 'neovim/nvim-lsp'` to `init.vim`
- Run `nvim +PlugInstall`
- Add `lua require'nvim_lsp'.rust_analyzer.setup({})` to `init.vim`
- Open a Rust file in a Cargo project
- Cause a syntax error and save the file

### Actual behaviour
An error is produced that reads "Error executing vim.schedule lua callback: Vim:E155: Unknown sign: LspDiagnosticsErrorSign". The error comes up on every save, and also while typing new characters, and grabs cursor focus away from the buffer, interfering with my ability to type.

![Screenshot 2020-04-28 at 14 38 44](https://user-images.githubusercontent.com/13041332/80493930-f7c3f580-895d-11ea-9aaf-37b670c91960.png)

### Expected behaviour
This error does not appear.

**Comment by justinmk** [comment]
transferred to https://github.com/neovim/neovim/.

likely related to this change: https://github.com/neovim/neovim/commit/5f41717838f4cd9d1087e452640ba554500279ab

Maybe related to this condition: https://github.com/neovim/neovim/commit/5f41717838f4cd9d1087e452640ba554500279ab#diff-b8731f813303fc789e9eb7ff76935c15R1021

try changing that to

     if 0 == vim.fn.sign_getdefined(name) then

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/12190 should fix this
