### ISSUE TITLE
terminal drawing is broken when suspending immediately after boot neovim with -V3log.

### ISSUE THREAD

**Issue by Code-Hex** [neovim/neovim#12206]
- `nvim --version`: `NVIM v0.5.0-464-g3de9452ab`, `0.4.3`
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: macOS 10.14.5（18F132）
- Terminal name/version: all terminal? (Apple Terminal, iTerm2, kitty)
- `$TERM`: `screen-256color`

This occurs only when the `-V3log` option is specified.

### Steps to reproduce using `nvim -u NORC`

Using this option did not cause this problem. If you do not specify any options, this will not happen either.

I haven't done any additional configurations.

```
$ ls ~/.config/
./  ../  configstore/  direnv/  gcloud/  gh/  iap_curl/  kitty/  telepresence/
```

### Actual behaviour

You can see that the cursor is drawn to the right side.

![aP4mjkMeK8](https://user-images.githubusercontent.com/6500104/80561370-35d51e00-8a1f-11ea-91ce-22bddfb736bc.gif)

### Expected behaviour

I'm hoping that the terminal drawing doesn't collapse after it's exited.

**Comment by teto** [comment]
not sure what's going on master works fine inside and outside of tmux. Please try with master and reopen when you have a minimal working example.

**Comment by Code-Hex** [comment]
@teto This happens even if you build the master branch (I have tried it already). I use tmux for example gif, but I get this problem even if I don't use tmux.

I think this can be reproduced by anyone with a mac.

```
nvim -V3log .
^Z
fg
:wq
```

It's the steps until the drawing breaks.

**Comment by teto** [comment]
I can reproduce thanks

**Comment by glacambre** [comment]
@teto Did you manage to reproduce this on Linux or was that OSX?

**Comment by zeertzjq** [comment]
Does this bug still exist?
