### ISSUE TITLE
Unknown function: readdir()

### ISSUE THREAD

**Issue by Shatur95** [neovim/neovim#12212]
- `nvim --version`: v0.5.0-477-gf9055c585 (also tested on 0.4.3 release)
- `vim -u DEFAULTS` behaves the same.
- Operating system/version: Arch Linux
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```vim
nvim -u NORC
:echo readdir('/') " Can be any directory
```

### Actual behaviour
Unknown function: readdir('/')

### Expected behaviour
List of files in specified directory.

### Vim
I tested it in Vim and it works as expected. Neovim and Vim documentation says that this function is present.

**Comment by Shougo** [comment]
The function is not ported yet.

**Comment by Shatur95** [comment]
Hope it will be ported. It present in Neovim documentation, can confuse users.

**Comment by Shougo** [comment]
The function is Vim 8.1.1120.
https://github.com/vim/vim/commit/543c9b1921d7605498b54afdef518e312f1b4515

I have tested `echo has('patch-8.1.1120')`.
It prints `0`.

**Comment by Shougo** [comment]
I don't know why the documentation is only ported.

> Hope it will be ported. 

You can do it.  It is open source project.

**Comment by Shatur95** [comment]
I will try, but I now familiar with Neovim codebase.

**Comment by Shatur95** [comment]
> I have tested echo has('patch-8.1.1120').

How neovim detects if patch is present? In Vim all patches added in `version.c`. I looked at the PRs that were sent and they did not contain any additions to `version.c.`.

**Comment by Shatur95** [comment]
> I have tested echo has('patch-8.1.1120').

How Neovim detects if patch is present? In Vim all patches added in `version.c`. I looked at the PRs that were sent and they did not contain any additions to `version.c.`.

**Comment by Shatur95** [comment]
Neovim does not have `src/nvim/evalfunc.c` and ` src/proto/eval.pro` as in https://github.com/vim/vim/commit/543c9b1921d7605498b54afdef518e312f1b4515. Where should I put implementation in Neovim?

**Comment by Shougo** [comment]
`src/nvim/eval.c`

**Comment by Shatur95** [comment]
Neovim does not have `vim_free`, `list_append_string`, `list_alloc`, `ga_init2`, `rettv_list_alloc` and `clear_tv`. What should I use instead?

**Comment by erw7** [comment]
@Shatur95 First, please read https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim.

When I come across a function that is not in neovim when porting a vim patch, I look for it in the following way. First, look in the vim source to find out where the function is being used. Next I look for the same function as vim in neovim. Then I can usually find the corresponding function.

Let's try it out with the `list_append_string` as an example.

### vim

```C
f_expand(typval_T *argvars, typval_T *rettv)
{
    ...
    s = tv_get_string(&argvars[0]);
    if (*s == '%' || *s == '#' || *s == '<')
    {
	++emsg_off;
	result = eval_vars(s, s, &len, NULL, &errormsg, NULL);
	--emsg_off;
	if (rettv->v_type == VAR_LIST)
	{
	    if (rettv_list_alloc(rettv) != FAIL && result != NULL)
		list_append_string(rettv->vval.v_list, result, -1);
	    vim_free(result);
	}
	else
```

### neovim

```C
static void f_expand(typval_T *argvars, typval_T *rettv, FunPtr fptr)
{
  ...
  const char *s = tv_get_string(&argvars[0]);
  if (*s == '%' || *s == '#' || *s == '<') {
    emsg_off++;
    result = eval_vars((char_u *)s, (char_u *)s, &len, NULL, &errormsg, NULL);
    emsg_off--;
    if (rettv->v_type == VAR_LIST) {
      tv_list_alloc_ret(rettv, (result != NULL));
      if (result != NULL) {
        tv_list_append_string(rettv->vval.v_list, (const char *)result, -1);
      }
    } else
```

It's a subtle difference, probably because there's a patch that hasn't been ported yet, but we can see that the function corresponding to `list_append_string` is `tv_list_append_string`.

**Comment by Shatur95** [comment]
@erw7, I'm sorry, I missed the wiki page. Will take a look, thank you a lot for explanations!
