### ISSUE TITLE
Not display "^M" line ending char even for mix line ending file

### ISSUE THREAD

**Issue by nash900** [neovim/neovim#12217]
For mix line ending file, vim will show "^M" to highlight them.
Does it possible to not show as many editor do by default? Or add an setting to enable/disable "^M" display.

![image](https://user-images.githubusercontent.com/8497245/80787221-8f248500-8bb8-11ea-9cb7-dea0b06fd66c.png)

Attached the sample mix line ending file.
[mix_line_ending.txt](https://github.com/neovim/neovim/files/4562750/mix_line_ending.txt)

I know there is an argument about not using mix line ending. But there is a case that the file is from others and you don't want to change it.

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
