### ISSUE TITLE
LSP: support LocationLink and peekDefinition

### ISSUE THREAD

**Issue by clason** [neovim/neovim#12218]
This is a two-part feature request following up on the PR #12178.

First, according to the LSP specification, servers can respond to, e.g., a `textDocument/definition` request with a [`LocationLink`](https://microsoft.github.io/language-server-protocol/specification#locationLink) instead of a `Location`, which contains as additional information a `targetRange` that the definition refers to (such as the function _body_, where the `targetSelectionRange` -- which corresponds to `Location`'s `range` -- refers to the function _name_ in the definition). 

Second, this information could be used to preview a definition in a floating window. (This is something VS Code and vim-lsp provide, and has turned out to be very useful, at least to me.)

Specifically, the following steps would be needed:

For `LocationLink` support,
* [x] advertise `linkSupport` in capabilities (in `protocol.lua`)
* [x] extend `location_callback` in `callbacks.lua` (or, maybe better, the lower level functions called by it) to recognize and handle `LocationLinks` (note that in addition to the new fields, the old fields have new names)

(see https://github.com/prabirshrestha/vim-lsp/pull/498 for how this was implemented in vim-lsp)

-> addressed in #12231 

For `peekDefinition` support,
* [x] provide a utility function (`preview_location`) that shows a result in a floating window (using `targetSelectionRange` if provided and, say 90% winheight otherwise)
* [x] provide a function that calls `textDocument/definition` with a custom callback that previews instead of jumps to the (first) result (alternatively, `location_callback` can be extended by a `preview` bool (defaulting to false) that determines whether the result is previewed or jumped to -- this is how it's implemented in vim-lsp, see https://github.com/prabirshrestha/vim-lsp/pull/412)

(these functions can be based on the code removed by #12178).

-> addressed in #12232

Repeat these steps for `implementation`, `declaration`, and `typeDefinition`.

**Comment by teto** [comment]
sounds great ! PRs welcome

**Comment by clason** [comment]
I would, if I could -- I'd need (significant) help on that, and there's some design decisions that people more familiar with the LSP core should make. But, yes, I'm willing to put some effort in.

**Comment by clason** [comment]
That was surprisingly easy -- kudos for the devs (@h-michael, @norcalli, @bfredl) for making the LSP implementation so hackable (lua 4tw)!

**Comment by teto** [comment]
any reason to keep this open ?

**Comment by clason** [comment]
probably not, although `peekDefinition` didn't make it, and the question on whether something like that could or should live in an `extensions.lua` module is still open -- although that discussion didn't take place here.
