### ISSUE TITLE
Stable PPA breaks and uninstalls neovim because of libvterm0 update

### ISSUE THREAD

**Issue by HattDroid** [neovim/neovim#12216]
Hi,

I have the stable PPA installed on my system. Everything always went well in the past years I have used it.

But today, there has been a libvterm0 package update on the PPA and it is actually removing neovim installation.

Digging a little deeper I see the following line on my system:
```

The following packages have unmet dependencies:
 libvterm0 : Breaks: neovim (< 0.4) but 0.3.8-1ppa1~ubuntu18.04.2 is to be installed
```
I could not access the old libvterm0 deb package in order to have everything in order.
At the moment, neovim from the PPA got removed and refuses to install, since it is unhappy with the newly pushed libvterm0:

```
The following packages have unmet dependencies:
 neovim : Depends: libvterm0 (>= 0~bzr635) but it is not going to be installed

```

Could you please help with the issue? Or repair the PPA if the issue is really on the repository side?

Thanks.

**Comment by HattDroid** [comment]
Quick follow-up here.

I was able to install the version Stable PPA neovim requires with the following command:

`sudo apt install libvterm0=0~bzr635`

But I guess neovim on the Stable PPA needs to be updated since it seems to require a different version of libvterm0 than the one that just got pushd on the PPA.

**Comment by Mentioum** [comment]
For others who this messed them up for work today and the above `sudo apt install libvterm0=0~bzr635` doesnt work:

On Pop OS (so also should work on a bunch of other debian / ubuntu variants).
Run the following commands:
### 1. Get a list of the available versions of libvterm0 for your distro version.
```
apt list libvterm0 -a
```
![image](https://user-images.githubusercontent.com/748170/80805814-e7f01f80-8bb0-11ea-8de5-3fccc0b1580e.png)
### 2. Install a version which is newer than the one required by neovim *(in my particular case it was listed as a downgrade for whatever reason)*
```
sudo apt-get install libvterm0=APPROPRIATE_VERSION
```
### 3. Reinstall neovim
```
sudo apt-get install neovim
```
It should install just find then :)

Hope that helps anyone who had their work / coding interrupted today!

**Comment by HattDroid** [comment]
Thanks for the details @Mentioum .

libvirt0 got updated on the stable repo from 0~bzr635 to 0~bzr715-1 between when I had the issue and today.
635 is not present on the repo anymore.
Nevertheless the issue is still there.

Other packages got updated on the repo also, so hopefully this is a sign the matching neovim package will get updated soon. 👍

**Comment by justinmk** [comment]
unless it's broken on ubuntu/debian, this is out of scope. Good to have the info in the tracker, but not as an open issue.

**Comment by Mentioum** [comment]
@justinmk I might be wrong but as far as I'm aware this is probably broken on Ubuntu.  Very rarely is PopOS different when it comes to this kind of thing.

Haven't checked as I'm still working on my own stuff at the moment but just my 2cents.

**Comment by HattDroid** [comment]
@justinmk I can confirm it is broken on a fresh ubuntu 18.04 installation.
Adding the stable PPA makes neovim uninstallable by default because of that libvterm0 version issue.

**Comment by HattDroid** [comment]
As expected, neovim also got updated a few hours ago on the stable PPA to a version matching the other dependencies.

All works now. 👍
Closing the issue.
Thanks.
