### ISSUE TITLE
LSP: Handle custom URIs returned by language servers in a plugin compatible way

### ISSUE THREAD

**Issue by mfussenegger** [neovim/neovim#12210]
- `nvim --version`: NVIM v0.5.0-477-gf9055c585

[eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls) contains an extension for LSP that allows to retrieve the contents of a classfile. If the LSP client announces the capability, various LSP responses (like references, definition) can contain items with a `jdt://` uri. For example:

```
{  
  id = 17,
  jsonrpc = "2.0",
  result = {
    {
      range = {
        end = {
          character = 21,
          line = 137
        },      
        start = {
          character = 17,
          line = 137
        }
      },
      uri = "jdt://contents/java.base/java.util/List.class?=sql/%5C/home%5C/jordi%5C/.jabba%5C/jdk%5C/openjdk%5C@1.14.0%5C/lib%5C/jrt-fs.jar%60java.base=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/14%5C/docs%5C/api%5C/=/%3Cjava.util(List.class"
    }
  }
}
```

Now, I created a [plugin](https://github.com/mfussenegger/nvim-jdtls) that adds a `BufReadCmd` handler to load the contents. This works well for the first file, but if I then want to navigate further, it acts up because `make_text_document_params` is currently implemented as:

```
function M.make_text_document_params()
  return { uri = vim.uri_from_bufnr(0) }
end
```

and `vim.uri_from_bufnr(0)`:

1. Always adds a `file://` prefix. (I think that would be reasonable to change/fix(?))
2. Decodes the uri, it changes `%5C` (among others) to `\`.

For the definition lookup to work, the uri would have to be kept 1:1 as originally returned by the server.

My workaround now is to [override make_text_document_params](https://github.com/mfussenegger/nvim-jdtls/commit/d298cf4129b94b5189841d752d141d827973e857), but I'm wondering if there would be a way to change things within neovim that are a) not eclipse.jdt.ls specific and b) don't require a workaround like that anymore. I don't really have an idea how 2) could be handled without breaking other things?

Demo of the functionality:

![asciinema-edd24f2d312171c2asciicast](https://user-images.githubusercontent.com/38700/80644348-ccc6c800-8a69-11ea-9aca-bcfd78584988.gif)

**Comment by justinmk** [comment]
> For the definition lookup to work, the uri would have to be kept 1:1 as originally returned by the server.

seems reasonable, why are we mangling it?

**Comment by mfussenegger** [comment]
> > For the definition lookup to work, the uri would have to be kept 1:1 as originally returned by the server.
> 
> seems reasonable, why are we mangling it?

Looks like it happens as part of the `file://...` uri to filename conversion. I created a [PR](https://github.com/neovim/neovim/pull/12243) that would keep the `URI` as is for "non-file" uri's. Though I'm not sure that approach is good, feels a bit hackish.
