### ISSUE TITLE
Get terminal background color

### ISSUE THREAD

**Issue by xzfc** [neovim/neovim#12220]
Neovim already detects it since 298608f88c463705cfd6ee47035c049dbb1d9fa0 and sets `bg` accordingly.
However, the colorscheme that I use overrides this value, and I see no way to get the terminal-related value.

Use-case: I want to set `hi Normal guibg=NONE` in `init.vim` only if the terminal background is dark.

- `nvim --version`: v0.5.0-dev
- Terminal name/version: gnome-terminal

### Steps to reproduce

Set light terminal background and run nvim with the following `init.vim`:
```vim
echom 'default: bg=' . &bg
autocmd VimEnter * echom 'enter: bg=' . &bg
autocmd ColorSchemePre * echom 'pre: bg=' . &bg
autocmd OptionSet background echom 'set: bg=' . &bg

colorscheme darkblue
```

I expect `bg=light` message at least somewhere, but I am getting the following:
```
default: bg=dark
pre: bg=dark
pre: bg=dark
enter: bg=dark
```

If I comment the last line (`colorscheme darkblue`), I'll get what I want:
```
default: bg=dark
enter: bg=dark
set: bg=light
```

**Comment by justinmk** [comment]
TUI sets 'background' here: https://github.com/neovim/neovim/blob/master/src/nvim/tui/input.c#L409-L411

So `OptionSet`  handler should get the value. 

More generally, returning the response of various terminal queries would be covered by `v:termresponse`, tracked in https://github.com/neovim/neovim/issues/6279

**Comment by xzfc** [comment]
> So OptionSet handler should get the value.

But it did not. See steps to reproduce in the original message. I'm guessing it's because setting `bg` re-applies the colorscheme just before `OptionSet` handler is called.
