### ISSUE TITLE
LSP: missing byte-to-char conversion on rename

### ISSUE THREAD

**Issue by clason** [neovim/neovim#12221]
I believe the function `apply_text_edits` is missing a UTF-16 byte-to-char conversion (or vice versa), since renaming gets thrown off by non-ASCII characters. (Compare the use of `str_utfindex` for `util.make_position_params`, which handles this situation correctly.)

Here's a minimal example using https://github.com/latex-lsp/texlab:

`lsp.vim` (adapt paths to taste)
```viml
call plug#begin(stdpath('cache').'/plugins')
Plug 'neovim/nvim-lsp'
call plug#end()
lua require'nvim_lsp'.texlab.setup{cmd = {vim.fn.stdpath("cache")..'/nvim_lsp/texlab'}}
```
`test.tex`
```tex
\begin{equation}\label{equation1}
    1+1=2
\end{equation}

See \eqref{equation1}.
```
If I do `nvim -u lsp.vim test.tex` and `call vim.lsp.buf.rename('equation2')` with the cursor on the `equation1` in the last line, everything works correctly (both `equation1` are replaced by `equation2`).

However, if I change the last line to

```tex
Söö \eqref{equation1}.
```
and do the same with the cursor on the last `1`, the result is
```text
Söö \eqreequation2n1}.
```
Note how the edit is shifted two characters to the left, corresponding to the number of non-ASCII characters to the left of it. (The `label` is renamed correctly.)

**Comment by justinmk** [comment]
> I believe the function `apply_text_edits` is missing a UTF-16 byte-to-char conversion (or vice versa),

it's quite possible. IIRC when lsp support was implemented it was known/planned that we were missing some utf16 conversions in some places, just a matter of finding and fixing them.

**Comment by clason** [comment]
Guess I found one :) (Side note: finding such points is easier if tests always include non-ASCII characters, too.)

Looking at it, the whole `apply_text_edits` function looks a bit fishy (`start_line` and `finish_line` are defined but never used, for example).

**Comment by clason** [comment]
Yes, I think I fixed it. I can open a pull request, but I don't think I'd be able to add a test for it without much help (and there's currently an open PR for tests in this area, #12191).

**Comment by clason** [comment]
Since this pattern occurs in several places (and likely will in several more), it might make sense to factor it out (by adding a convenience function that takes (buffer,row,col) and spits out a corrected (row,col)).
