### ISSUE TITLE
Unknown function: stdpath 

### ISSUE THREAD

**Issue by MJoergen** [neovim/neovim#12238]
- `nvim --version`: NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Linux Mint 19.3
- Terminal name/version:
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:call mkdir(stdpath('config'), 'p')
```

### Actual behaviour
E117: Unknown function: stdpath
E15: Invalid expression: stdpath('config')

### Expected behaviour
Should create the nvim config directory.

I have just done a fresh install of nvim, and want to try it out. I'm following the description in the help file: Transitioning from Vim (nvim-from-vim)

**Comment by Shougo** [comment]
Your neovim version is too old.
I think the version doesn't support stdpath.

**Comment by Shougo** [comment]
I have checked it.
`stdpath()` is added in neovim 0.3.0.

So this issue should be closed.

**Comment by HidekiAI** [comment]
Distro: Gentoo
Any chance to re-open this? I am also getting stdpath() to be 'unknown option'

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/var/tmp/portage/app-editors/neovim-0.4.3/work/neovim-0.4.3_build/config -I/var/tmp/portage/app-editors/neovim-0.4.3/work/neovim-0.4.3/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.4.3/work/neovim-0.4.3_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.4.3/work/neovim-0.4.3_build/include
Compiled by portage@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

**Comment by byque** [comment]
Same nvim --version: NVIM v0.2.2 if installed with apt using Ubuntu 18.04. Something to be aware if using LTS versions.

**Comment by pjalsGit** [comment]
stdpath does not exist in v0.5.0

**Comment by bfredl** [comment]
Are you sure about this?

**Comment by clason** [comment]
v0.5.0 does not exist in stdpath, I suspect...

**Comment by kkanhere** [comment]
> 0.7.2, shift-k on c++ function, got same error: E117: unknown function: stdpath

If cppman was being used as keywordprg then setting the cppman pager to nvim might fix this issue.
