### ISSUE TITLE
tnoremap <Cmd>wincmd doesn't preserve mode

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#12246]
- `nvim --version`: NVIM v0.5.0-487-g501ef9529

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:tnoremap <A-j> <Cmd>wincmd j<CR>
:term
:sp term://sh
:startinsert
<A-j>
```

### Actual behaviour
The cursor is moved to the bottom split, neovim goes in normal mode.

### Expected behaviour
The cursor is moved to the bottom split, neovim stays in terminal mode because when using `inoremap` and regular buffers, neovim stays in insert mode.

**Comment by glacambre** [comment]
Fixing this is as simple as replacing this line:

https://github.com/neovim/neovim/blob/496b668ad183411454c9e95f4618624388a939c1/src/nvim/terminal.c#L486

With

```c
return curbuf->handle == s->term->buf_handle
    || (curbuf->terminal != NULL && curbuf->terminal != NULL);
```

This doesn't make any test fail.

Does anyone know why we only stay in terminal mode if we're in the same buffer? I would expect to stay in terminal mode when moving from terminal buffer to terminal buffer and even to switch to insert mode when switching from a terminal buffer to a "normal" buffer.

**Comment by justinmk** [comment]
> Does anyone know why we only stay in terminal mode if we're in the same buffer? I would expect to stay in terminal mode when moving from terminal buffer to terminal buffer and even to switch to insert mode when switching from a terminal buffer to a "normal" buffer.

nice catch, that likely can be changed to check for `curbuf->terminal != NULL`.

the original logic is from 2015 and likely was just an oversight.

**Comment by glacambre** [comment]
> nice catch, that likely can be changed to check for |curbuf->terminal != 
> NULL|.

I tried that but the terminal keeps the cursor until terminal mode is 
left (after that the cursor is correctly moved to the right window).

This works a little better:
```c
   if (curbuf->terminal == NULL) {
     return 0;
   }
   s->term = curbuf-> terminal;
   invalidate_terminal(s->term, s->term->cursor.row, s->term->cursor.row 
+ 1);
   return 1;
```

But I'm not sure this is the proper place for this.

**Comment by justinmk** [comment]
perhaps `restart_edit` or `force_restart_edit`  would be involved in the solution

**Comment by glacambre** [comment]
As far as I can tell, insert mode doesn't use 
restart_edit/force_restart_edit to stay in insert mode (I just put a 
watchpoint on these two variables and stepped through the code that 
handles user input in insert mode). It looks like ex_cmd switches curbuf 
and everything just magically works.

**Comment by justinmk** [comment]
> This works a little better:
> 
> if (curbuf->terminal == NULL) {
>   return 0;
> }
> s->term = curbuf-> terminal;
> invalidate_terminal(s->term, s->term->cursor.row, s->term->cursor.row + 1);
> return 1;
> 
> But I'm not sure this is the proper place for this.

that might actually be ok. perhaps only do `invalidate_terminal` if the current buffer changed:

```
if (curbuf->terminal == NULL) {
  return 0;
}
if (s->term != curbuf->terminal) {
  s->term = curbuf->terminal;
  invalidate_terminal(s->term, s->term->cursor.row, s->term->cursor.row + 1);
}
return 1;
```

**Comment by glacambre** [comment]
Ok, I'll write a test and open a PR then :)

**Comment by oxilumin** [comment]
Is there a regression started around the build mentioned above? I can't manage to make it work since around this build, on the other hand if I undo the tweak in fzf-vim (to behavior before this issue was closed) it works.

**Comment by glacambre** [comment]
>I can't manage to make it work

What is "it"?

**Comment by oxilumin** [comment]
> > I can't manage to make it work
> 
> What is "it"?

I refer to this issue (12246). The terminal is not starting insert mode with tnoremap. In particular (regarding the mentioned issue in coc-fzf repo) any multilevel coc-fzf window resets to normal mode after hitting <CR>.
    https://asciinema.org/a/Kaw7sMP1hKsAnCgoD3UyB9bqG

**Comment by glacambre** [comment]
Do you have reliable minimal reproducer? We can't investigate CoC, it's tens of thousands of lines of code.

**Comment by antoinemadec** [comment]
@glacambre this is in fact a FZF regression: https://github.com/junegunn/fzf/commit/1a76bdf8914195ab26ebac7e49a3ed8752dd69bd

It was introduced to circumvent neovim#13769
An issue has been open here: https://github.com/junegunn/fzf/issues/2352

**Comment by glacambre** [comment]
@antoinemadec Nice, thanks for the update!
