### ISSUE TITLE
E303: Unable to open swap file ...

### ISSUE THREAD

**Issue by thomas-haslwanter** [neovim/neovim#12247]
When entering
`nvim *.txt`
the following error gets generated

"E303: Unable to open swap file for "*.txt", recovery impossible "

This does not happen when I put in the files in a list, e.g.
`nvim test_01.txt test_02.txt`

It also does not happen with gvim (other installation)

- `nvim --version`:
NVIM v0.5.0-487-g501ef9529

- `vim -u DEFAULTS` (version: ) behaves differently?
Yes. The Error does not appear in "vim"

- Operating system/version:
Win64 10 Pro, Build 18362

- Terminal name/version:
Windows command terminal

- `$TERM`:
Not defined on my system
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC *.txt
```

### Actual behaviour
The file "*.txt" gets opened after the error message

### Expected behaviour
Iterate through the files with the ending "*.txt" in the current directory

**Comment by justinmk** [comment]
> "E303: Unable to open swap file for "*.txt", recovery impossible "

Nvim on windows does `--literal` by default. If you want wildcards , use `:next` (aka `:n`). 

    nvim +'n *.txt`
