### ISSUE TITLE
[LSP] - Be a bit more opinionated on where the quickfix window opens.

### ISSUE THREAD

**Issue by ckipp01** [neovim/neovim#12241]
I've noticed that when you trigger something that utilizes the *Quickfix List* it always seems to open to the bottom right of what you're doing. I think this may be a bit unexpected. Here are a couple examples of what I mean.

If you are using split and you trigger a find references in the left viewport on a symbol, the quickfix list opens on the bottom of the right viewport.

![2020-05-03 20 13 15](https://user-images.githubusercontent.com/13974112/80922152-67c9e580-8d7b-11ea-96bc-04865beefaf9.gif)

I've also noticed that this will do the same if the buffer isn't a normal buffer. For example, if you're using somthing like [vista.vim](https://github.com/liuchengxu/vista.vim#neovim) as a symbol explorer and you do a find references, it will actually open the quickfix list in the bottom of the Vista window with is a `nofile` buftype.

![2020-05-03 20 06 36](https://user-images.githubusercontent.com/13974112/80922343-b75ce100-8d7c-11ea-9882-da2f3f654289.gif)

I encountered this today when I used the new `workspace/symbol`, which opened to the bottom right of where I was, and it threw me off a bit.

If you are in the right viewport though, then the Quickfix List opens in the bottom of that viewport.

Thoughts on maybe making this a bit more opinionated on where it opens? I think opening in the same viewport makes sense, and I also think not opening in a `nofile` buftype also probably makes sense.

Thanks for the great work on the LSP support. It's daily getting better and better!

- `nvim --version`: Latest master

**Comment by RedBeard0531** [comment]
I'd favor making the equivalent of `:botright copen` the default behavior for the quickfix list. Given that it is the global list (unlike the location list), I don't think the location should depend on which window is currently active when it is first opened. It would be odd if I had a vertical split, opened the qf list from the left plane, then updated it based on an action in the right pane, for the qf list to still be only under the left pane. It also seems like it would be odd if it moved around every time it was updated.

**Comment by mjlbach** [comment]
We are now more opinionated.

**Comment by cespare** [comment]
@mjlbach it looks like that file contains a mix of `copen` and `botright copen`. Using gopls as an example, if I list references, it opens a full-width quickfix window, but if I list diagnostics it opens a right-hand-column quickfix window.

**Comment by mjlbach** [comment]
I have merged one PR, and have a pending other PR that makes this consistent.
