### ISSUE TITLE
Prompt ignores continue: "Press ENTER or type command to continue"

### ISSUE THREAD

**Issue by mangelozzi** [neovim/neovim#12256]
- `nvim --version`:
```
NVIM v0.5.0-418-g87d892afa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DUTF8PROC_STATIC -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN
```
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Windows 10
- Terminal name/version:
- `$TERM`: vtpcon

### Steps to reproduce using `nvim -u NORC`
1. nvim -u NORC
2. Open 2 buffers .
3. Type `:ls` to list the buffers
4. It says `Press ENTER or type command to continue`
5. Type a command to continue, like `:b#` where # = desired buffer number

### Actual behaviour
When the colon in step 5 above is typed to "continue", it exits the prompt info instead of continuing.

### Expected behaviour
In VIM the prompt info stays up, its so its much faster. While you are reading which buffer to switch to, you can type `:b` , then soon as you have determined your buffer, you just type the number then enter.

**Comment by teto** [comment]
on my linux system with master, vim and neovim seem to behave the same.

**Comment by glacambre** [comment]
Seems to be fixed on master. Closing :).
