### ISSUE TITLE
[feature request] Opt-in Kakoune-style commands

### ISSUE THREAD

**Issue by BatmanAoD** [neovim/neovim#12269]
In normal mode, Kakoune behaves somewhat like Vim in visual mode: `<command><number><movement>` becomes `<number><movement><command>`, and before `<command>` is entered, the affected range of text is highlighted.

This blog post explains this and some other differences: https://medium.com/@Jernfrost/kakoune-the-text-editor-i-didnt-know-i-needed-23d5f1d6ad97

Would it be possible to have a "kakoune mode" that behaves like Kakoune's normal mode, with some way to configure nvim to use it in place of "traditional" normal mode?

**Comment by mcepl** [comment]
I think this is the same issue as with #8457 . It would be nice if [it was possible to create new modes as plugins](https://www.reddit.com/r/vim/comments/g69fvx/vimlibmodal_create_new_modes_for_vim/fo8iwz0/).

**Comment by BatmanAoD** [comment]
Hm, yes, different modes would be very cool!

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/992
