### ISSUE TITLE
What capabilities do you wish terminal emulators would report?

### ISSUE THREAD

**Issue by gnachman** [neovim/neovim#12260]
This is perhaps an abuse of issues; please feel free to redirect me if I shouldn't be asking this here.

Some terminal emulator authors (VTE, xterm, tmux, mintty, libvterm, iTerm2, and others) are discussing building a new mechanism for reporting capabilities. For context: https://github.com/mintty/mintty/issues/881

My goal is to collect desires from developers of popular applications. What capabilities do you wish you could discover about terminals that you don't already get from terminfo?

For example, being able to detect 24-bit color support, available cursor styles, bracketed paste support, and mouse reporting modes are the kinds of capabilities that would be included. They would likely be exposed through a combination of a new environment variable and a to-be-determined control sequence that reports them.

I have seen https://github.com/neovim/neovim/blob/501ef952983dba09b160d2e910d3842364502d7c/src/nvim/tui/tui.c, and I'll update my spreadsheet with its contents. I'm asking more about what features you'd like reported in a perfect world.

The results of this survey are being collected here: https://docs.google.com/spreadsheets/d/1H4OK8z98ptySnAPjlej56lrL6b0S1j6okwp7KLRTDBQ/edit#gid=0

Thanks in advance for your time!

**Comment by dundargoc** [comment]
I don't this belongs on the github issue. I'd instead recommend [discourse](https://neovim.discourse.group/) for "discussion" type questions. I also think you'll have a higher chance of sparking a discussion there.
