### ISSUE TITLE
Update to latest cmake syntax files

### ISSUE THREAD

**Issue by RedBeard0531** [neovim/neovim#12267]
The version at https://gitlab.kitware.com/cmake/cmake/-/blob/master/Auxiliary/vim/syntax/cmake.vim has been improved over what is included with neovim. The thing that made me look into it is that the neovim syntax file incorrectly highlights `"${nested${vars}in} strings"`, but that version does it correctly. I think it is also automatically kept up to date with the latest keywords and such. That repo also has an indent file, but I think the neovim version is newer.

**Comment by janlazo** [comment]
That version hasn't been merged to Vim yet. Please make a separate issue (or PR) at the Vim repo. Neovim will merge the updated version when it's merged to Vim.

**Comment by mhinz** [comment]
It's still the same in Vim, so either it was never reported or never merged. If the case of the latter, I'd expect a link to the Vim issue in here.

I will reopen this if someone cares enough to report this to Vim. Until then there's nothing we can act on.
