### ISSUE TITLE
scrollbind-like behaviour when running multiple windows from tmux

### ISSUE THREAD

**Issue by severoraz** [neovim/neovim#12265]
OS: Linux (Arch Linux)
Desktop environment: gnome-shell 3.36.2 in wayland
neovim version: 0.4.3
tmux version: 3.1b

Steps to reproduce:
1. Open a terminal and start tmux in it (single window)
2. Start neovim in the tmux window
3. In neovim, open a file long enough so that scrolling is possible
3. In neovim, split the screen to have side-by-side windows (run :vsplit)
5. Make sure scrollbind is off (run :set noscrollbind)
4. In either of the windows of neovim, start scrolling

Observed behaviour:
The window which wasn't being scrolled is scrolled too, as if scrollbind were on, and is not redrawn.
Clearing and redrawing the screen (run :mode) redraws the window.

Expected behaviour:
Only the scrolled window should be scrolled. Redraws on the other window should happen as needed.

**Comment by erw7** [comment]
I think the phenomenon is similar to #10562 and #11998. What about the host terminal and its `$TERM` and `$TERM` of tmux?

**Comment by severoraz** [comment]
Host terminal, without tmux: 

    $ echo $TERM
    xterm-termite screen.xterm-256color

Host terminal, within tmux:

    $ echo $TERM
    screen.xterm-256color

I have checked and setting `TERM` from within tmux to `xterm-termite` before starting nvim fixes the issue.

**Comment by erw7** [comment]
This has been fixed in #12005. Try nightly on the [Releases](https://github.com/neovim/neovim/releases).

**Comment by glacambre** [comment]
I don't have tmux on my computer to check if it has been fixed, but I'm confident we can trust erw7, so let's close this :).
