### ISSUE TITLE
Indicated error prevents lsp setup for clangd to work.

### ISSUE THREAD

**Issue by oni-link** [neovim/neovim#12263]
- `nvim --version`:
NVIM v0.5.0-497-gf04a9a2c9
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/oni-link/git/neovim/build/config -I/home/oni-link/git/neovim/src -I/home/oni-link/git/neovim/.deps/usr/include -I/usr/include -I/home/oni-link/git/neovim/build/src/nvim/auto -I/home/oni-link/git/neovim/build/include
Compiled by oni-link@windwaker

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: gentoo/linux
- Terminal name/version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`
Latest nvim-lsp version (commit 92717276ba0b8e184712f56a8bb7b67bd014124a).

clangd version 11.0.0 (https://github.com/llvm/llvm-project.git 6e49365dec135b17a8b8f562364a7203e1c94982)

minimal.vim:
```
set runtimepath^=~/.vim/bundle/nvim-lsp/  
filetype plugin on
lua require'nvim_lsp'.clangd.setup{}
set omnifunc=v:lua.vim.lsp.omnifunc
```

Non existing file 01.cpp.

```
nvim -u minimal.vim 01.cpp
```
### Actual behaviour
nvim opens up with the following error message:
```
Error executing vim.schedule lua callback: /home/oni-link/git/neovim//runtime/lua/vim/lsp/protocol.lua:891: attempt to index field 'save' (a boolean value)
```
Diagnostics and completions do not work.
### Expected behaviour
No error message. Diagnostics and completions work.

The indicated error line:
```vim
        text_document_save_include_text = ifnil(textDocumentSync.save and textDocumentSync.save.includeText, false);
```
A look into the LSP spec indicates that `textDocumentSync.save` can have type
`boolean | SaveOptions`.  So if `textDocumentSync.save` has type `boolean` then
`textDocumentSync.save.includeText` should not be checked.

Preventing the check makes this example work.

**Comment by h-michael** [comment]
@oni-link 

The LSP specification document looks strange.
TextDocumentSyncOptions seems to have changed between 3.14.0 and 3.15.0.
In 3.15.0, multiple TextDocumentSyncOptions are defined.
Please take a moment to explore and see this in detail.
By the way, there is no description about this in the changelog.

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#version_3_15_0

https://microsoft.github.io/language-server-protocol/specifications/specification-3-14

By the way, clangd is v11 and there are changes around here. Until v10, Nvim's lsp client should have been working.

https://github.com/llvm/llvm-project/commit/596b63ad4019e61030803789a1844a0f1aeb34db

**Comment by h-michael** [comment]
[memo]
https://github.com/microsoft/language-server-protocol/issues/909
https://github.com/microsoft/language-server-protocol/commit/11e4c5c4fb51d154cdf5a4f748c17f57e1852789

**Comment by h-michael** [comment]
resolve: #12450

**Comment by teto** [comment]
should be good now ? please reopen if not the case.
