### ISSUE TITLE
Syntax highlighting breaks for long files

### ISSUE THREAD

**Issue by wamoyo** [neovim/neovim#12274]
I can't tell what triggers this, but occasionally syntax highlighting breaks and the colors get messed up. I'll put screenshots, and my best guesses at what's going on below.

- `nvim --version`: NVIM v0.5.0-nightly-6-gef0398f | Build type: Release | LuaJIT 2.1.0-beta3
- `vim -u DEFAULTS` (version: ) behaves differently? NOPE, same behavior.
- Operating system/version: Ubuntu 18.04
- Terminal name/version: # GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2
- `$TERM`: ???

### Steps to reproduce using `nvim -u NORC`

I open a JavaScript file, press G to skip to the bottom, and the syntax highlighting looks wrong. You can tell most easily by the comments (one image below is my styles, the other neovim defaults):

![Screenshot from 2020-05-07 20-06-06](https://user-images.githubusercontent.com/1170326/81356459-3add4180-909f-11ea-9907-3c2c2bc84a09.png)

![Screenshot from 2020-05-07 20-09-36](https://user-images.githubusercontent.com/1170326/81356475-429ce600-909f-11ea-9723-5c0c4304a378.png)

Then, if I scroll to the top, and just press J to scroll all the way down, then syntax highlighting just stays proper: 

![Screenshot from 2020-05-07 20-09-48](https://user-images.githubusercontent.com/1170326/81356532-619b7800-909f-11ea-9895-2ee46c588a44.png)

![Screenshot from 2020-05-07 20-06-45](https://user-images.githubusercontent.com/1170326/81356538-66f8c280-909f-11ea-8409-4df80160d535.png)

Again you can tell most easily from the comment line. 

### Expected behaviour

My expected behaviour is that the syntax highlighting remain the same always, regardless of how I move around the file or how long the file is.

**Comment by glacambre** [comment]
Does using `:syntax sync fromstart` make this issue disapear?

**Comment by wamoyo** [comment]
That commend fixes the highlighting indeed. 

I tried putting it in my vimrc, that doesn't work however.

**Comment by glacambre** [comment]
This is because the syntax rules are probably overriden by the syntax 
files you're using. You could try setting this setting from the `Syntax` 
autocommand.

In any case, `:syntax syn fromstart` working means this isn't a bug but 
a "feature", the reason (Neo)Vim doesn't do syntax highlighting from the 
beginning of the file is that it could be slow. The situation will 
probably change thanks to LSPs and/or TreeSitter though :).

**Comment by wamoyo** [comment]
Hmmm... so any recommendations? Should I hang tight for LSPs or TreeSitter? I don't know what those are, haa : )

**Comment by wamoyo** [comment]
Happy to circle back to here and test things out to see if this resolves in the future.

**Comment by justinmk** [comment]
Known issue as mentioned. treesitter is our plan to address this, otherwise `wontfix`.

> Hmmm... so any recommendations

    :syntax sync fromstart

this is what Vim offers

**Comment by wamoyo** [comment]
@justinmk when is treesitter slated to hit nightly?

**Comment by glacambre** [comment]
@wamoyo Tree-sitter is already available in nightly, although I'm not sure Neovim already uses it for syntax highlighting. You can track progress on TreeSitter by subscribing to this issue: https://github.com/neovim/neovim/issues/11724
