### ISSUE TITLE
Setting foldcolumn="auto" swallows insert mode input

### ISSUE THREAD

**Issue by sudormrfbin** [neovim/neovim#12278]
The `auto` option introduced for `foldcolumn` by PR #11716 positions the cursor before the line number column and insert mode input is not shown.  Refreshing the screen using `ctrl-l` renders the previous input text but the cursor stays behind the line number. Further input is similarly not shown.

- `nvim --version`: NVIM v0.5.0-497-gf04a9a2c9
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: `Debian 10`
- Terminal name/version: `st`
- `$TERM`: `st-256color`
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set number
:set foldcolumn="auto"
```

### Actual behaviour
![out](https://user-images.githubusercontent.com/23398472/81416214-07fe8080-9167-11ea-837b-d7c3606eb683.gif)

### Expected behaviour

`:set foldcolumn="auto"` should enable automatic foldcolumn without
display issues.

**Comment by teto** [comment]
`:set foldcolumn="auto"` is not a valid value, only those in `p_fdc_values` should be accepted, such as `:set fdc=auto:3`. Should be an issue in the checker. Will try to look into it once I get a computer :)

**Comment by erw7** [comment]
@teto Sorry if I'm a nuisance. It seems that you need to do the following:

```diff
diff --git a/src/nvim/option.c b/src/nvim/option.c
index 7d4de4baf..7e87ca7e0 100644
--- a/src/nvim/option.c
+++ b/src/nvim/option.c
@@ -3181,7 +3181,7 @@ ambw_end:
     }
   } else if (varp == &curwin->w_p_fdc || varp == &curwin->w_allbuf_opt.wo_fdc) {
     // 'foldcolumn'
-    if (check_opt_strings(*varp, p_fdc_values, false) != OK) {
+    if (**varp == NUL || check_opt_strings(*varp, p_fdc_values, false) != OK) {
       errmsg = e_invarg;
     }
   } else if (varp == &p_pt) {
```

**Comment by teto** [comment]
@erw7  you are the opposite of a nuisance, our favorite bug crasher ;) seems like the `"` marks the start of a comment and so it's equivalent to `set fdc=`. We should fix opt_strings_flags instead as check_opt_strings is called in several places (just 4 lines upper to set signcolumn p_scl). Seems like check_opt_strings never enters the while loop when *var is 0 and thus returns OK instead of FAIL

**Comment by sudormrfbin** [comment]
Closed in https://github.com/neovim/neovim/pull/13571 🎉
