### ISSUE TITLE
Incorrect display of formatting characters in :Tutor 

### ISSUE THREAD

**Issue by Melkster** [neovim/neovim#12273]
- `nvim --version`: v0.5.0-496-gd2766b06c and v0.4.3
- Operating system/version: Tested on both Windows 10 and Arch Linux

### Steps to reproduce using `nvim -u NORC`

```
:Tutor
```

### Actual behaviour
Neovim does not conceal formatting characters in `:Tutor` as seen in these screenshots:

![Screenshot](https://gyazo.com/82a02a823e4844b4d7078d7a7dbd34df.png)

![Screenshot](https://gyazo.com/8d652767f58c4de3b7bdb98d5eb81eb5.png)

### Expected behaviour
Neovim should conceal formatting character in `:Tutor`

**Comment by justinmk** [comment]
Tutor sets `conceallevel=2` so I'm not sure what's going on. Maybe it was intentional? @fmoralesc

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/issues/11401

**Comment by fmoralesc** [comment]
@justinmk Hi! I've been looking a bit into it but I haven't had the time to work on this at all. I think at some point the syntax file broke (you can clearly see in the second screenshot that some formatting is bleeding onto the line that starts with `This exits`). I'll try to dig into this over the weekend, I have some more time at the moment.

**Comment by fmoralesc** [comment]
Well, I think I got it ;)
