### ISSUE TITLE
LSP: How should hover on longer text be displayed?

### ISSUE THREAD

**Issue by ckipp01** [neovim/neovim#12281]
In a lot of languages, it's going to be common that there will be longer signatures. For example, when using Scala, it's not uncommon to trigger a hover request on something that has a half dozen parameters. I came across this today for example. I triggered the following hover request:

```
[Trace - 05:35:40 PM] Sending response 'textDocument/hover - (3)'. Processing request took 19ms
Result: {
  "contents": {
    "kind": "markdown",
    "value": "```scala\ndef toMarkdown(input: Input, context: Context, inputFile: InputFile, siteVariables: Map[String,String], reporter: Reporter, settings: Settings): String\n```"
  },
  "range": {
    "start": {
      "line": 81,
      "character": 13
    },
    "end": {
      "line": 81,
      "character": 89
    }
  }
}
```

Currently, `vim.lsp.buf.hover()` will display this like the following. I was split vertically when I did this.

<img width="1282" alt="Screenshot 2020-05-08 at 17 35 55" src="https://user-images.githubusercontent.com/13974112/81422656-8cdf9f00-9153-11ea-9860-e56bc216845f.png">

In some of the other LSP Vim clients they will wrap in this scenario. For example, here is what coc.nvim does for the same hover request:

<img width="1190" alt="Screenshot 2020-05-08 at 17 35 14" src="https://user-images.githubusercontent.com/13974112/81422719-a680e680-9153-11ea-9541-86713e9b6a34.png">

What do you think about doing some type of determination on the viewport size and wrapping if necessary? Or there may be another better solution?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/9496

**Comment by clason** [comment]
This may not quite be what you're asking about, but I have a similar problem with texlab, so I have overridden the default callback with one that linewraps:
```lua
local function hover_wrap(_, method, result)
    util.focusable_float(method, function()
        if not (result and result.contents) then
            -- return { 'No information available' }
            return
        end
        local markdown_lines = util.convert_input_to_markdown_lines(result.contents)
        markdown_lines = util.trim_empty_lines(markdown_lines)
        if vim.tbl_isempty(markdown_lines) then
            -- return { 'No information available' }
            return
        end
        local bufnr, winnr = util.fancy_floating_markdown(markdown_lines)
        util.close_preview_autocmd({"CursorMoved", "BufHidden", "InsertCharPre"}, winnr)
        local hover_len = #vim.api.nvim_buf_get_lines(bufnr,0,-1,false)[1]
        local win_width = vim.api.nvim_win_get_width(0)
        if hover_len > win_width then
            vim.api.nvim_win_set_width(winnr,math.min(hover_len,win_width))
            vim.api.nvim_win_set_height(winnr,math.ceil(hover_len/win_width))
            vim.wo[winnr].wrap = true
        end
        return bufnr, winnr
    end)
end
```

**Comment by ckipp01** [comment]
> #9496
Ah, cool, thanks for linking this!

> This may not quite be what you're asking about, but I have a similar problem with texlab, so I have overridden the default callback with one that linewraps:

Ahhh, this is super helpful @clason, thanks. This was actually on my TODO list to figure out. To replace the default callback for this would just be this?

```lua
lsp.callbacks['textDocument/hover'] = hover_wrap
```

**Comment by clason** [comment]
Yes, exactly!

**Comment by clason** [comment]
@justinmk If you think that's a useful change (possibly behind a non-default(?) option), I can make a PR.

**Comment by ckipp01** [comment]
ahh, I just added the opts to be passed into `fancy_floating_markdown` and this is perfect. Thanks again @clason. I'm going to add this to [nvim-metals](https://github.com/ckipp01/nvim-metals) so people using it can utilize this if they want. Are you alright with that? I'll put a comment with your name on it :).

```lua
    local opts = {
      pad_left = 1;
      pad_right = 1;
    }
```

**Comment by clason** [comment]
Ah, I removed the opts on purpose because I didn't like them :) Sure, by all means use it; no need for attribution!

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/how-to-modify-inbuilt-line-diagnostics-popup-to-get-wrapped-lines/543/3
