### ISSUE TITLE
What highlight of this area?

### ISSUE THREAD

**Issue by glepnir** [neovim/neovim#12280]
- `nvim --version`: neovim --Head
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: macos
- Terminal name/version: Iterm2
- `$TERM`: xterm256

### Steps to reproduce using `nvim -u NORC`

@mhinz Hi  it's not a feature or a bug . Just want to know what highlight of this ? 
This area is between the statusline of the 2 windows
![image](https://user-images.githubusercontent.com/41671631/81419579-0e015b00-9181-11ea-91b5-5f6540e30cdd.png)

**Comment by justinmk** [comment]
`StatusLineNC`

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by glepnir** [comment]
@justinmk  Thanks. Sorry for bother you.

**Comment by glepnir** [comment]
@justinmk  I set this highlight of `StatusLineNC`, it works on left window. right window also has it.
![image](https://user-images.githubusercontent.com/41671631/81421373-fbd4ec00-9183-11ea-94a6-b2e5df5cef85.png)

**Comment by chrisbra** [comment]
Depending on where your cursor is, you need to set `StatusLine` or `StatusLineNC`

**Comment by glepnir** [comment]
@chrisbra  thanks i got it.  set to NONE it's easy for me .
