### ISSUE TITLE
No Syntax Highlighting When Opening Multiple Files

### ISSUE THREAD

**Issue by wamoyo** [neovim/neovim#12284]
- `nvim --version`: NVIM v0.5.0-nightly-6-gef0398f  ...  Build type: Release ...  LuaJIT 2.1.0-beta3
- `vim -u DEFAULTS` (version: ) behaves differently? I don't have vim installed, but nvim defaults doesn't have the issue, but it also says "Cannot read from DEFAULTS"
- Operating system/version: Ubuntu 18.04
- Terminal name/version: # GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2

### Actual behaviour

When opening multiple files, I don't set syntax highlighting, whereas when I open one file at a time I do. 

One file: 

![Screenshot from 2020-05-08 13-59-50](https://user-images.githubusercontent.com/1170326/81435050-2e0b2d00-9135-11ea-8b81-11bd127fa713.png)

![Screenshot from 2020-05-08 13-59-26](https://user-images.githubusercontent.com/1170326/81435064-32374a80-9135-11ea-9a48-2ec816dd40cc.png)

To files:

![Screenshot from 2020-05-08 13-59-43](https://user-images.githubusercontent.com/1170326/81435104-44b18400-9135-11ea-813a-14bcf461f8f3.png)

![Screenshot from 2020-05-08 13-58-55](https://user-images.githubusercontent.com/1170326/81435118-48dda180-9135-11ea-97a8-8ead8afa8b9a.png)

### Expected behaviour

I always expect syntax highlighting to work, regardless of how I open files.

**Comment by wamoyo** [comment]
The syntax highlighting doesn't work for the first file in the list of files being opened.... usually. Been dealing with this for months.

**Comment by glacambre** [comment]
I can't reproduce this with `nvim -u NORC /tmp/a.html /tmp/a.json`, can you? If you can, please upload the files here. If you can't, the problem is in your init.vim.

(Also make sure that you're really using neovim, the commands you listed use `vi`.)

**Comment by wamoyo** [comment]
Thanks! Can't seem to reproduce with nvim -u NORC. 

Yes, pardon the confusion. I alias vi to nvim. I'll try to figure out what's up with my init.vim.

**Comment by wamoyo** [comment]
Not that anyone might arrive here with the same problem, but here was the source of my issue:

```
" Avoid E173 (n more file(s) to edit)
if argc() > 1
 silent blast " load last buffer
 silent bfirst " switch back to the first
endif
```

I, of course, not need to solve the original issue.

**Comment by chrisbra** [comment]
try to do so in a VimEnter autocommand, so that vim has a chance to process the syntax and filetype autocommands.

**Comment by wamoyo** [comment]
@chrisbra 

There was some mkview, loadview code in my vimrc, that someone helped call out: https://vi.stackexchange.com/questions/25209/how-to-avoid-avoid-e173-n-more-files-to-edit/25211?noredirect=1#comment44183_25211

Thanks for the suggestion!
