### ISSUE TITLE
'echo' does not display from .../ftplugin/ (because of shortmess+=F )

### ISSUE THREAD

**Issue by andrewferrier** [neovim/neovim#12288]
- `nvim --version`: Recreated following instructions below in Neovim 0.3.4, but from less rigourous testing I believe this is still present in Neovim v0.5.0-496-gd2766b06c also.

- `vim` (version: 8.1.1401) behaves differently? Yes

- Operating system/version: Linux
- Terminal name/version: kitty 0.17.4
- `$TERM`: xterm-kitty

### Steps to reproduce

1. Install Neovim and regular Vim.

1. `curl "https://raw.githubusercontent.com/tpope/vim-sensible/master/plugin/sensible.vim" > ~/.vimrc` (I believe the exact contents are unimportant, I just need a vim-syntax file to open).

1. `echo "echomsg 'Test'\nset textwidth=40" > ~/.vim/after/ftplugin/vim.vim` (for regular Vim)

1. `echo "echomsg 'Test'\nset textwidth=40" > ~/.config/nvim/after/ftplugin/vim.vim` (for Neovim)

1. Open Vim. Type `:e ~/.vimrc<CR>`. Notice that the "Test" message is echoed. Check `textwidth` using `set textwidth?` and notice that it was set correctly (the textwidth is not important, it's just there to demonstrate the file is being read).

1. Open Neovim. Type `:e ~/.vimrc<CR>`. Notice that the "Test" message is **not** echoed (*this is the bug*). Check `textwidth` and see that it is still set correctly (so obviously the Neovim `vim.vim` is being read).

### Actual behaviour

"Test" message is not displayed in Neovim, but it displayed in Vim.

### Expected behaviour

"Test" message is displayed in Neovim like it is in Vim.

### Misc

In case it helps, Dockerfile contents I used to recreate the problem:

```
FROM debian
RUN apt-get -y update
RUN apt-get -y --no-install-recommends install neovim vim-nox curl
RUN curl "https://raw.githubusercontent.com/tpope/vim-sensible/master/plugin/sensible.vim" > ~/.vimrc
RUN mkdir -p ~/.vim/after/ftplugin
RUN mkdir -p ~/.config/nvim/after/ftplugin
RUN echo "echomsg 'Test'\nset textwidth=40" > ~/.vim/after/ftplugin/vim.vim
RUN echo "echomsg 'Test'\nset textwidth=40" > ~/.config/nvim/after/ftplugin/vim.vim
```

(then do tests about from a terminal inside the Docker container).

**Comment by erw7** [comment]
It's due to the difference in default options between vim and neovim, not a bug. If you do `:set shortmess-=F`, it works the same way as vim. Incidentally, if you `:set shortmess+=F`, vim works the same way as neovim.

**Comment by justinmk** [comment]
as @erw7 mentioned, technically this is Vim behavior. But it's something we would like to improve...

tracked in https://github.com/neovim/neovim/issues/9314

**Comment by andrewferrier** [comment]
OK, thanks for clarifying. Confirm that this does fix my issues. I was going to say that I would offer to update the docs, currently the docs for 'shortmess' are a bit vague on this point - 'note that this also affects messages from autocommands' - but doesn't say how they are 'affected'. Also, this is surprising and confusing default behaviour, I would argue. But based on what @justinmk said it sounds like this is to be improved and it's tracked in the other bug anyway.

Thanks for the insights.
