### ISSUE TITLE
nvim_feedkeys() not escaping keycodes, nvim_input() does

### ISSUE THREAD

**Issue by michael-angelozzi** [neovim/neovim#12297]
From [the docs](https://neovim.io/doc/user/api.html#nvim_open_win()), I expect `nvim_feedkeys({keys}, {mode}, {escape_csi}) ` with `{escape_csi}` set to true to interpret key codes. I tried setting it to `true` as well as `false` with no difference in behaviour. I have read the docs but still am not 100% sure if that is its intended purpose.

- `nvim --version`:
```
NVIM v0.5.0-418-g87d892afa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DUTF8PROC_STATIC -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"
```
- Operating system/version: Windows 10

### Steps to reproduce 
1: `nvim -u NORC`
2. create a new file `temp.vim`
3. Paste in the following:
```
echo "Sourced 5"
let mapleader = " "

lua <<EOF
function feed_test()
    vim.api.nvim_command('startinsert')
    vim.api.nvim_feedkeys("feedkeys feed\\<C-N>", "n", true)
end
function input_test()
    vim.api.nvim_command('startinsert')
    vim.api.nvim_input("input inp\\<C-N>")
end
EOF
imap <F5> <ESC>:lua feed_test()<CR>
imap <F6> <ESC>:lua input_test()<CR>
```
4. Save temp.vim, then `source temp.vim`
5. Enter insert mode, press `F5` and see autocomplete  menu **_does not_** pop up.
6. Enter insert mode, press `F6` and see autocomplete menu _**does**_ pop up.

### Actual behaviour
In step 5 above the <C-N> is sent as literal text instead of being interpretted as a key code.

### Expected behaviour
In step 5 above the <C-N> should be sent as if the user presses CTRL-N

### Side Note
Its hard for me to appreciate the difference between the two commands. If someone explains it here, I will try formalize it and make a PR to improve the docs.

**Comment by erw7** [comment]
I don't think this is a bug. The help doesn't say that `nvim_feedkeys()` interprets the keycode when `{escape_csi}` is true.

> {escape_csi}  If true, escape K_SPECIAL/CSI bytes in keys

If you actually send the key with the code containing `K_SPECIAL (0x80)` as follows, you can see the difference by `escape_csi`.

```
:lua vim.api.nvim_feedkeys('i\xC3\x80', 'm', true)
:lua vim.api.nvim_feedkeys('i\xC3\x80', 'm', false)
```

**Comment by michael-angelozzi** [comment]
Oh okay, is there a way to `nvim_feedkeys` with the usual vim codes, e.g. <ESC> or <CR> or <C-U> ? or must one look them up in some ASCII table?

**Comment by clason** [comment]
From @erw7's comment in the linked issue:
```vim
:lua vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('ifoo<cr>',true,false,true),'m',true)
```
works.

**Comment by nhooyr** [comment]
@tjdevries Feel free to assign me, should be fairly easy to take care of this one.
