### ISSUE TITLE
[Q] How do I get a list of recent files from neovim?

### ISSUE THREAD

**Issue by NightMachinary** [neovim/neovim#12299]
I have this function that extracts recent files from `emacs` and `vim`, and I want to add `neovim` support to it, but the shada file seems ill-suited to a naive extraction:

```
v () {
    local files
    files=()
    command rg '^>' ~/.viminfo | cut -c3- | while read line
    do
        line="${line/\~/$HOME}"
        [ -f "$line" ] && files+="$line"
    done
    test -f ~/.emacs.d/.cache/recentf && {
        command rg --only-matching --replace '$1' '^\s*"(.*)"$' ~/.emacs.d/.cache/recentf | while read line
        do
            [ -f "$line" ] && files+="$line"
        done
    }
    files=(${(0@)"$(gstat  --printf='%040.18Y:%n\0' "$files[@]" | gsort -rz | gcut -z -d':' -f2-)"})
    files=(${(0@)"$(<<<"${(F)files}" fz --print0 --query "$*")"})  || return 1
    local ve="$ve"
    reval "${veditor:-vim}" -p "${(@)files}"
}
```

**Comment by glacambre** [comment]
I think the simplest way to do this from the shell is this: `nvim 
--headless -c 'echo v:oldfiles | q'`.

**Comment by NightMachinary** [comment]
@glacambre 
```
$ nvim --headless -c 'echo v:oldfiles | q'                                                                                   1
['/Users/evar/vimfiler:default', '/Users/evar/cellar/notes/dev/notes.md', '/Users/evar/.SpaceVim.d/init.toml', '/Users/evar/Startify', '/Users/evar/.SpaceVim/vimfiler:default', '/Users/evar/.local/share/nvim/vimfiler:default', '/Users/evar/.local/share/nvim/Startify', '/Users/evar/.local/share/nvim/shada/main.shada', '/usr/local/Cellar/neovim/HEAD-30a6e37/share/nvim/runtime/doc/starting.txt', '/usr/local/Cellar/neovim/HEAD-30a6e37/share/nvim/runtime/doc/deprecated.txt', '/Users/evar/cellar/notes/creative/music/musictheory.md', 'scp://eva@82.102.11.148/scripts/zsh/auto-load/others/notes.zsh', '/Users/evar/cellar/notes/selfhelp/additivity.md', '/Users/evar/cellar/notes/journal/2020.May.07 1399-02-18.md', 'dev/notes.md', 'journal/2020.May.07 1399-02-18.md', 'read/dev.courses.md

* https://github.com/leandromoreira/digital_video_introduction
* https://www.khanacademy.org/economics-finance-domain/core-finance
<!--stackedit_data:
eyJoaXN0b3J5IjpbLTE0Mzg1MzA0MF19
-->
', '
read/dev.short.md



* https://notamonadtutorial.com/weld-accelerating-numpy-scikit-and-pandas-as-much-as-100x-with-rust-and-llvm-12ec1c630a1 @numerical
```
It gets stuck here. It is somehow printing the last file's content, or perhaps I had mistakenly called nvim with the file's content some time in the past. It gets stuck anyhow, which is possibly a bug.

**Comment by teto** [comment]
you can use `:redir` and nvim scripting mode to redirect the output of echo v:oldfiles.

**Comment by glacambre** [comment]
This works fine for me:

 >nvim -i shada "$(echo -ne 'a\n*\ntest/\n@numerical | ')"
 >nvim -i shada --headless -c 'echo v:oldfiles | q'
['a
*
test/
@numerical | ']

So you would need to create a minimal reproducer if you want to see this 
debugged.

I think if I were you I'd just delete the shada file and start afresh 
though.

**Comment by NightMachinary** [comment]
[shada.zip](https://github.com/neovim/neovim/files/4620515/shada.zip)
@glacambre Is this file good enough for reproduction? I think just deleting it is not a good idea.

**Comment by NightMachinary** [comment]
@teto  Cab you give me a shell line? I don't know vim scripting.

**Comment by farisachugthai** [comment]
> This works fine for me: nvim -i shada "$(echo -ne 'a\n*\ntest/\n@numerical | ')" nvim -i shada --  > @teto Cab you give me a shell line? I don't know vim scripting.

Deleting a shada file won't mess up your vim instance.
Also what are your settings for `&shada` or `&viminfo`? If  they've been changed that could explain it.

Regardless, if you're using this in a script, it'd probably make it easier (and faster) for your users if you disregard their configuration files.:

```bash

nvim --headless -u NONE -i ~/.local/share/nvim/shada/main.shada -c"echo v:oldfiles | qall!"

```

worked just fine for me

**Comment by farisachugthai** [comment]
> @teto  Cab you give me a shell line? I don't know vim scripting.

Do you need a shell line btw? I saw `fz` in your original post So Im guessing your making an fzf script. nvim has native fzf integration tho.

I just found this sitting my [vimrc](https://github.com/farisachugthai/viconf)

```

" Brofiles: {{{                         

function! s:CompleteBrofiles(A, L, P)
  return v:oldfiles
endfunction

let s:fzf_options = get(g:, 'fzf_options', [])

 command! -bang -bar -nargs=* -complete=customlist,s:CompleteBrofiles Brofiles
     \ call fzf#run(fzf#wrap('oldfiles',
     \ {'source': v:oldfiles,
     \ 'sink': 'sp', 
     \ 'options': s:fzf_options}, <bang>0))

```

So that'll open a buffer and provide some cmdline completion if you tab over on the ex line

**Comment by glacambre** [comment]
On 2020-05-13 09:51, NightMachinary wrote:
> shada.zip <https://github.com/neovim/neovim/files/4620515/shada.zip>
> @glacambre <https://github.com/glacambre> Is this file good enough for 
> reproduction? I think just deleting it is not a good idea.

It is, I was able to reproduce your bug. I can also confirm that 
https://github.com/neovim/neovim/pull/12209 makes it disappear.

**Comment by glacambre** [comment]
#12209 has been merged (and the fix has even been backported to v0.4.4 in https://github.com/neovim/neovim/pull/12352) so I think this can be closed :).

**Comment by glacambre** [comment]
Actually I can still reproduce this issue on master. Weird.

**Comment by glacambre** [comment]
Neovim's master branch/nightly release doesn't get stuck on this shada anymore so let's close this issue :).
