### ISSUE TITLE
Support word-completion feature in search and replace bar

### ISSUE THREAD

**Issue by tinkersavenue** [neovim/neovim#12290]
World completion (`CTRL-N` and `CTRL-P`) is very useful when dealing with variables with long names and a lot of underscores (e.g., `test_wrong_Email_format_feature`). Not only does it speed up the process of writing but it acts like a safeguard that help us avoid misspelling variables with long name and pesky bugs in code. When replacing one word with another we are 100% certain that the word we want to replace exists in the scope of our file (otherwise it doesn't make any sense to do "search and replace") and it should come naturally to have word completion feature in the "search part" of the search and replace. It is probable that such a feature exists but I just cannot find a way to activate it. In the case it doesn't exist I think it would be really nice to have it.

### Actual behaviour

Dummy file content:
```
foo_with_a_long_name = head_string + tail_string
```

When typing `:s/foo_with<CTRL-N>` nothing happens because word completion does not activate.

### Expected behaviour

When typing `:s/foo_with<CTRL-N>` the variable name would expand and the line command would change to `:s/foo_with_a_long_name` after which it is simple to add the replace part of the command `/merged_string`.

**Comment by justinmk** [comment]
completion is per-command. It just happens to not work for `:s`

You can use `ctrl-f` in cmdline to get to the `q:` window, then use `ctrl-n` from there.

@ZyX-I was working on making cmdline more feature-rich, but it's out of scope unless he or someone else shows up with a robust PR.

See also https://github.com/neovim/neovim/issues/3013

**Comment by tinkersavenue** [comment]
Thanks @justinmk that's really neat! Sorry I missed that particular issue when I was doing my research.
