### ISSUE TITLE
nvim_open_win() does not honor enter at startup

### ISSUE THREAD

**Issue by mangelozzi** [neovim/neovim#12295]
- `nvim --version`:

```
NVIM v0.5.0-418-g87d892afa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DUTF8PROC_STATIC -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN
```
Operating system/version: Windows 10
- Terminal name/version:
- `$TERM`: '' (blank)

### Steps to reproduce using:
1. Create a blank init.vim, and put the following in it:

```
lua temp = require("init")
lua temp.make_window()
```

2. Create file `lua/init.lua`, and put the following code in it:
Note that `nvim_open_win({buffer}, {enter}, {config})` has `enter` set to `true`:

```
test = {}
function test.make_window()
    buf  = vim.api.nvim_create_buf(false, true)
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, {"one", "two", "three"})
    local configi = {relative='editor', anchor='SW', width=9, height=3, col=10, row=5,  style='minimal'}
    local win = vim.api.nvim_open_win(buf, true, configi)
    vim.api.nvim_win_set_option(win, 'winhl', 'Normal:_NormalReversed')
end
return test
```

3.  Restart Neovim

### Actual behaviour
Creates a floating window and does NOT enter the window.

### Expected behaviour
Creates a floating window and does ENTER the window.

### Notes
It does honor `enter` if the function has been called via a hotkey, or called after startup, but seems to not work if fired off during startup.

**Comment by justinmk** [comment]
confirmed on b96037e42de4

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/is-it-possible-to-create-a-split-without-changing-focus/5245/2
