### ISSUE TITLE
Cursor has wrong shape after `gq`

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#12309]
- `nvim --version`: NVIM v0.5.0-502-g2f818eb9e
- `vim -u DEFAULTS` (version: ) behaves differently? Yes - but it does worse than Neovim
- Operating system/version: Linux 5.3.0-46-generic 38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 GNU/Linux
- Terminal name/version: kitty 0.13.1 created by Kovid Goyal
- `$TERM`: xterm-kitty

This can also be reproduced in GNOME Terminal 3.28.2 using VTE 0.52.2.

### Steps to reproduce using `nvim -u NORC`

Copy the following piece of Ada code:
```ada
package body B is

   procedure A (N : Node_Id) is

   begin
      Set_Was_Expression_Function (New_Body);

      --  aaaaaaaaa pre/postcondition is applied to this function. This has to
      --  aaaaa aaaaaaa aaaaa aaaaaa aaaaaa aaaaaaa aaaaaaaaaa aaaaaa aaaaaaaa
      --  aaaaaaaa aaaaa

   end;

end B;
```

```
nvim -u NORC /tmp/b.adb
"+p
9G
A
<Space>aaaaaaaaa
<Esc>
V
j
gq
```

### Actual behaviour

Neovim is in normal mode but the cursor is turned into a bar.

### Expected behaviour

Neovim is in normal mode and the cursor is a block.

**Comment by nhooyr** [comment]
Can confirm.

I also see similar behaviour with:

```
nvim -U NORC
:h
S
```

The cursor will now be `_` but in normal mode.

**Comment by glacambre** [comment]
This also happens in GUIs, so this is a neovim issue rather than a terminal issue.

**Comment by glacambre** [comment]
Here are the bits of the ada runtime that are causing this:
```
function GetAdaIndent()
   exe 'normal! $F)%'
   return 6
endfunction GetAdaIndent
setlocal indentexpr=GetAdaIndent()
```

So the problem here is that:

1) Neovim enters insert mode to do the formatting.
2) This [overwrites the global State](https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/src/nvim/ops.c#L4315).
3) [insertchar](https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/src/nvim/ops.c#L4318) calls [internal_format](https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/src/nvim/edit.c#L5628) which calls [open_line](https://github.com/neovim/neovim/blob/master/src/nvim/edit.c#L6089) which calls [do_c_expr_indent](https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/src/nvim/change.c#L1750).
4) When the indentexpr is called, `exe normal!` results in a call to [save_current_state](https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/src/nvim/ex_docmd.c#L8404) and then [restore_current_state](https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/src/nvim/ex_docmd.c#L8423), which makes a call to [ui_cursor_shape](https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/src/nvim/ex_docmd.c#L8347). Cursor shape turns into a bar.
5) ui_cursor_shape is never called again. Sadness ensues.

To me it sounds like the best solution would be to use save_current_state at the beginning and restore_current_state at the end of either do_pending_operator, op_format or format_lines.

@bfredl Sorry to bother you but I don't know if anybody's more knowledgeable than you about this state business, what would be the best solution in your opinion?

Btw I used [pernosco](https://pernos.co/debug/lKGkf0nDCTK7K9MTskr2Bg/index.html#f{m[Ek4,Afdg_,t[AQ,AqtK_,f{e[Ek4,k/4_,s{aVhPE2UAA,bBA,uFYUW,oFa+F___) to figure out what was going on and I must say this is the best debugger I've ever had the chance to use. I highly recommend it (despite its very high price).

**Comment by glacambre** [comment]
This issue is possibly a duplicate of https://github.com/neovim/neovim/issues/12112.
