### ISSUE TITLE
incsearch not working during substitution.

### ISSUE THREAD

**Issue by mrillusi0n** [neovim/neovim#12308]
- `nvim --version`: v0.4.3
- Operating System: macOS Catalina
- Terminal: Alacritty
- `$TERM`: xterm-256color

Unlike when searching for a pattern, when the incsearch works, it doesn't, when using the substitution command.

### Actual behaviour

incsearch doesn't function when doing a `:s/pattern...`.

### Expected behaviour

A visual feedback should be available when entering the pattern to be substituted during a substitution command.

**Comment by clason** [comment]
Substitution is controlled by `inccommand`; try `:set inccommand=nosplit`.

**Comment by mrillusi0n** [comment]
Thank you, but it doesn't seem to work as expected. It highlights the match only if the pattern I'm searching for is below the cursor. I'm not sure what other settings I should tweak, but with Vim, `:set incsearch` would work during searches as well as substitutions.

**Comment by clason** [comment]
But that's normal: `:s/x/y` starts from the current position; if you want to start from the top, you have to do `:%s/x/y`.

**Comment by mrillusi0n** [comment]
`fib(` is highlighted in Vim, during substitution.

![image](https://user-images.githubusercontent.com/37063502/81793291-cc790300-9526-11ea-85f5-ccfad96626d8.png)

`fib(` is not highlighted in NeoVim, during substitution.

![image](https://user-images.githubusercontent.com/37063502/81793582-3396b780-9527-11ea-9146-b6a14f9f3256.png)

I'm just looking for a way to have the same functionality on nvim, as vim.

**Comment by clason** [comment]
But it _will_ be highlighted as soon as you add `/fim(` ( `/g`) -- and in fact it will highlight _all_ (replaced) occurrences rather than only the first?

But anyway, it's clear now what you would like to have; not sure if it's actually feasible (maybe if an `inccommand=none` option were to be added, for which `:s` behaves as in vim?) or whether that will stay as it is `by-design`. (For what it's worth (which is not a lot), I _much_ prefer neovim's behavior over vim's, and I suspect many other users feel similarly.)

**Comment by bew** [comment]
Thanks for the comparison @mrillusi0n!, I agree with you that would be helpful to have incsearch working while writing the search pattern, and still keep the neovim's inccommand while writing the replacement to see the preview of the replacement

**Comment by clason** [comment]
> Thanks for the comparison @mrillusi0n!, I agree with you that would be helpful to have incsearch working while writing the search pattern, and still keep the neovim's inccommand while writing the replacement to see the preview of the replacement

Oh, yeah, that makes sense! (I didn't see it that way.)

**Comment by KillTheMule** [comment]
> `fib(` is highlighted in Vim, during substitution.

Funkily though, it's missing the second occurence for some reason.


> `fib(` is not highlighted in NeoVim, during substitution.

What's the value of `inccomand` here? Using `inccomand=nosplit` will higlight the matches while typing the search pattern, I just tried.

**Comment by bew** [comment]
You're right @KillTheMule!

For the record, using:
```
$ nvim -u NONE somefile.md

:set inccommand=split
:%s/def
```
I get:
![inccommand](https://user-images.githubusercontent.com/9730330/81805304-e4e32080-951a-11ea-9a31-ea1211177bb7.png)

**Comment by mrillusi0n** [comment]
> Substitution is controlled by `inccommand`; try `:set inccommand=nosplit`.

So, it was `:set inccommand=split`. Works well for me! I wanted that split functionality. Thank you very much!

**Comment by clason** [comment]
or `nosplit` (which I personally prefer); these are the two (non-disabled) options.

Glad it's working out now!

**Comment by mrillusi0n** [comment]
Any idea how to move to that preview window? It would be awesome if we could delete the lines where we don't want the replacement to happen!

**Comment by clason** [comment]
That's why I don't use `split` :) (`nosplit` previews changes inline)

**Comment by glacambre** [comment]
On 2020-05-13 19:15, Nikhil wrote:
> Any idea how to move to that preview window? It would be awesome if we 
> could delete the lines where we don't want the replacement to happen!

I don't think this is possible, but what you could do once you've 
written your replacement is either add `/gc` at the end to ask for 
confirmation on each replacement or move to the begging of the command 
line and prepend `%g/pattern/` to make sure your substitute command only 
applies to lines that contain `pattern`.

**Comment by glacambre** [comment]
I can't reproduce the original issue of `fib` not being highlighted when using `:set incsearch` on master, so I'm going to close this issue. @mrillusiOn let us know if you're still experiencing this bug and we'll re-open :)

**Comment by mrillusi0n** [comment]
@glacambre I no longer face the issue. It seems to be working fine for me (both with `split` and `nosplit`). Thank you!

I'm currently using the `split` mode.

**Comment by ach5948** [comment]
`inccommand="split"` and `inccommand="nosplit"` also shows the results of the substitution while typing the substitution portion and doesn't match the behavior of incsearch in vim. Is there a way to have nvim match vim's behavior (use incsearch while typing the search component of `s//`, but don't show the replacement while typing the replace component)?

**Comment by zeertzjq** [comment]
`inccommand=""`
