### ISSUE TITLE
[Q] How do I disable using icons that need patched fonts?

### ISSUE THREAD

**Issue by NightMachinary** [neovim/neovim#12300]
![image](https://user-images.githubusercontent.com/36224762/81673052-4d20fc00-9460-11ea-8f6f-540801996fc6.png)

I don't want to install patched fonts (too much trouble for too little gain). Is there an option to simply not use such nonstandard features?

**Comment by teto** [comment]
don't use plugins that leverage nonstandard features :) ?

**Comment by Shougo** [comment]
You should read the plugin documentation.
