### ISSUE TITLE
DOC: clarify `getenv`

### ISSUE THREAD

**Issue by farisachugthai** [neovim/neovim#12311]
So I was actually really confused by the documentation on `getenv` in *expr-env*.

The documentation doesn't specify that you can't prefix the var with a dollar sign.
I.E.

```vim

echo getenv('$VIMRUNTIME')   " -> v:null
echo getenv($VIMRUNTIME)     " -> v:null
echo getenv(VIMRUNTIME)       "  -> raises
echo getenv('VIMRUNTIME')     " expected value

```

In the wild, you'll frequently notice people doing stuff like `expand('$VAR')`,
so having getenv not following those conventional shell rules was confusing
In addition, the documentation on getenv is immediately followed by a section
on `expand` where the example used uses the `$` prefix.

*See below*

I'd be happy to fix this up myself since this is purely documentation but I figured i'd create the
issue before anything

```

environment variable					*expr-env*
--------------------
$VAR			environment variable

The String value of any environment variable.  When it is not defined, the
result is an empty string.

The functions `getenv()` and `setenv()` can also be used and work for
environment variables with non-alphanumeric names.
The function `environ()` can be used to get a Dict with all environment
variables.


						*expr-env-expand*
Note that there is a difference between using $VAR directly and using
expand("$VAR").  Using it directly will only expand environment variables that
are known inside the current Vim session.  Using expand() will first try using
the environment variables known inside the current Vim session.  If that
fails, a shell will be used to expand the variable.  This can be slow, but it
does expand all variables that the shell knows about.  Example: >
	:echo $shell
	:echo expand("$shell")
The first one probably doesn't echo anything, the second echoes the $shell
variable (if your shell supports it).

```

**Comment by teto** [comment]
The best might be to add an example in `getenv` doc.

**Comment by janlazo** [comment]
Please upstream your changes instead of sending a neovim PR. Vim has the same docs.

**Comment by dundargoc** [comment]
I believe this can be closed as `getenv` has been updated and also includes an example.
