### ISSUE TITLE
Display showbreak character in line number margin

### ISSUE THREAD

**Issue by jooize** [neovim/neovim#12317]
## Idea

The `showbreak` character displays at the beginning of the non-first line of a wrapped line. Instead of displaying it in content, move it to the empty space in the margin.

![Screenshot 2020-05-14 at 16 42 52](https://user-images.githubusercontent.com/719371/81948740-5c3faf80-9602-11ea-8e7f-e4ed4fc00cff.png)

Whether this is a good idea, I'm not sure.

## Issues

- With `nonumber`, it would not display without refining the implementation.

**Comment by zeertzjq** [comment]
This may be already achievable using `:set cpoptions+=n`, however the width of the number column may change.

**Comment by zeertzjq** [comment]
This is now achievable using 'statuscolumn'.

**Comment by jezzy-ultra** [comment]
> This is now achievable using 'statuscolumn'.

as a neovim noob, how do I configure the option to achieve this? I don't understand the documentation well enough to figure it out
