### ISSUE TITLE
LSP: Support for `additionalTextEdits` in `CompletionItem`

### ISSUE THREAD

**Issue by ckipp01** [neovim/neovim#12310]
Currently when completions are returned from the server Nvim doesn't take into account that there can be `additionalTextEdits` that are part of the `CompletionItem`. The can bee seen in the [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion).

### Steps to reproduce

Trigger a completion that holds `additionalTextEdits`. For example, here is one from Metals:

```json
[Trace - 09:52:55 PM] Sending response 'textDocument/completion - (25)'. Processing request took 90ms
Result: {
  "isIncomplete": false,
  "items": [
    {
      "label": "test",
      "kind": 12,
      "detail": ": String",
      "preselect": true,
      "sortText": "00000",
      "filterText": "\"$test ",
      "insertTextFormat": 1,
      "textEdit": {
        "range": {
          "start": {
            "line": 26,
            "character": 12
          },
          "end": {
            "line": 26,
            "character": 16
          }
        },
        "newText": "test"
      },
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 26,
              "character": 10
            },
            "end": {
              "line": 26,
              "character": 10
            }
          },
          "newText": "s"
        }
      ],
      "data": {
        "symbol": "example/Hello.test.",
        "target": "file:/Users/ckipp/Documents/scala-workspace/metals-minimal-sbt/?id\u003droot"
      }
    }
  ]
}
```

Currently the `textEdit` is applied, but the `additionalTextEdits` are not.

**Comment by mfussenegger** [comment]
As a workaround you could add a custom `CompleteDone` event with something like this.


```
function M._CompleteDone()
    local completed_item = api.nvim_get_vvar('completed_item')
    if not completed_item or not completed_item.user_data then
        return
    end
    local lnum, col = unpack(api.nvim_win_get_cursor(0))
    local item = completed_item.user_data.nvim.lsp.completion_item
    local bufnr = api.nvim_get_current_buf()
    if item.additionalTextEdits then
      -- Text edit in the same line would mess with the cursor position
      local edits = vim.tbl_filter(
        function(x) return x.range.start.line ~= (lnum - 1) end,
        item.additionalTextEdits
      )
      vim.lsp.util.apply_text_edits(edits, bufnr)
    end
    ...

```

**Comment by smartinellimarco** [comment]
> function M._CompleteDone()
>     local completed_item = api.nvim_get_vvar('completed_item')
>     if not completed_item or not completed_item.user_data then
>         return
>     end
>     local lnum, col = unpack(api.nvim_win_get_cursor(0))
>     local item = completed_item.user_data.nvim.lsp.completion_item
>     local bufnr = api.nvim_get_current_buf()
>     if item.additionalTextEdits then
>       -- Text edit in the same line would mess with the cursor position
>       local edits = vim.tbl_filter(
>         function(x) return x.range.start.line ~= (lnum - 1) end,
>         item.additionalTextEdits
>       )
>       vim.lsp.util.apply_text_edits(edits, bufnr)
>     end
>     ...

Is there a way to identify a snippet and expand it within this function?

**Comment by clason** [comment]
Snippet expansion will be handled by Nvim itself.

**Comment by mfussenegger** [comment]
> Is there a way to identify a snippet and expand it within this function?

Yes. the `item` has a `insertTextFormat` property. You can compare it with vim.lsp.protocol.InsertTextFormat.Snippet.

On 0.10/nightly you could then use vim.snippet.expand, but it requires some more code - e.g. to clean up the already inserted word by the built-in completion handling. 

See https://github.com/mfussenegger/nvim-lsp-compl/blob/5bde411019084ca30d6ccc194e289b12ffd38773/lua/lsp_compl.lua#L585-L688 for a more complete version.

And as clason mentioned, that will eventually be built-in in some form. See also https://github.com/neovim/neovim/issues/25714
