### ISSUE TITLE
nvim can't continue after suspended in some cases

### ISSUE THREAD

**Issue by dalu98** [neovim/neovim#12322]
- `nvim --version`:
```
NVIM v0.5.0-02155f5
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200514-8112-57hv5b/build/config -I/tmp/neovim-20200514-8112-57hv5b/src -I/usr/local/include -I/tmp/neovim-20200514-8112-57hv5b/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200514-8112-57hv5b/build/src/nvim/auto -I/tmp/neovim-20200514-8112-57hv5b/build/include
Compiled by mou@dalu.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-02155f5/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?

Yes, even vim and neovim use the same config.

- Operating system/version: macOS/10.15.4
- Terminal name/version: ITerm2/3.3.10. Happened both in tmux or not
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

Type =C-z= back to terminal
$ bg
[1]  - 25046 continued  nvim -u NORC
[1]  + 25046 suspended (tty output)  nvim -u NORC
$ fg
[1]  - 25046 continued  nvim -u NORC

```

### Actual behaviour

Nvim can't recognize my input after `fg` to bring nvim back to front while vim works fine at the same config.

For example, after `fg` brings nvim to front, press `i` to try to go into`Insert Mode`, and the reponse is input `i` into the screen. It looks like the nvim has frozen.

And after this, the only way to quit nvim is to press =C-z= again,  input `kill nvim`, and `fg`.
Then terminal will remind that
```
[1]  - 49152 continued  nvim -u NORC
Vim: Caught deadly signal 'SIGTERM'

Vim: Finished.
```

### Expected behaviour

Nvim can continue to my work just like vim does.

**Comment by erw7** [comment]
@dalu98 I think I'm failing to set the TTY mode from the phenomenon. Would you like to enter insert mode with `i+enter`?

In any case, I think it's difficult to fix the problem if you don't know the conditions such as the phenomenon always occurs after a specific command is executed.

**Comment by dalu98** [comment]
> failing to set the TTY mode from the phenomenon. 

Does this mean it's my system's config problem?

> Would you like to enter insert mode with `i+enter`?

If I continue nvim by `bg` `fg`, press `i+enter` will still cause the situation I mentioned above.

And I will get two statusline...Press `C-[` can't get back to `Normal Mode`.

<img width="1287" alt="截屏2020-05-20 下午5 52 11" src="https://user-images.githubusercontent.com/25452934/82434092-f7ce9580-9ac4-11ea-9d1e-7ff09f3749e1.png">

**Comment by erw7** [comment]
>> failing to set the TTY mode from the phenomenon.
>
> Does this mean it's my system's config problem?

No, it's possible, but I don't know why. I think that TTY is not set to Raw mode as long as I see the image. What happens if you run `stty -f /dev/pty0 -a` when there is a problem? Check the `TTY` that `nvim` is using with `ps`, etc. and replace the part in `/dev/pty0` (I don't have the actual macOS, so the command line options in `stty` may be wrong.).

**Comment by dalu98** [comment]
There are many files starts with `pty` under dir `/dev`.

I don't know which one can be useful.

```
➜  /dev ls | rg pty
ptyp0
ptyp1
ptyp2
ptyp3
ptyp4
ptyp5
ptyp6
ptyp7
ptyp8
ptyp9
ptypa
ptypb
ptypc
ptypd
ptype
ptypf
ptyq0
ptyq1
ptyq2
ptyq3
ptyq4
ptyq5
ptyq6
ptyq7
ptyq8
ptyq9
ptyqa
ptyqb
ptyqc
ptyqd
ptyqe
ptyqf
ptyr0
ptyr1
ptyr2
ptyr3
ptyr4
ptyr5
ptyr6
ptyr7
ptyr8
ptyr9
ptyra
ptyrb
ptyrc
ptyrd
ptyre
ptyrf
ptys0
ptys1
ptys2
ptys3
ptys4
ptys5
ptys6
ptys7
ptys8
ptys9
ptysa
ptysb
ptysc
ptysd
ptyse
ptysf
ptyt0
ptyt1
ptyt2
ptyt3
ptyt4
ptyt5
ptyt6
ptyt7
ptyt8
ptyt9
ptyta
ptytb
ptytc
ptytd
ptyte
ptytf
ptyu0
ptyu1
ptyu2
ptyu3
ptyu4
ptyu5
ptyu6
ptyu7
ptyu8
ptyu9
ptyua
ptyub
ptyuc
ptyud
ptyue
ptyuf
ptyv0
ptyv1
ptyv2
ptyv3
ptyv4
ptyv5
ptyv6
ptyv7
ptyv8
ptyv9
ptyva
ptyvb
ptyvc
ptyvd
ptyve
ptyvf
ptyw0
ptyw1
ptyw2
ptyw3
ptyw4
ptyw5
ptyw6
ptyw7
ptyw8
ptyw9
ptywa
ptywb
ptywc
ptywd
ptywe
ptywf
```

**Comment by erw7** [comment]
@dalu98 On Linux, I can use the `ps` command to find out what TTYs (In the following example, the `pts/0`) nvim is using by doing the following. Can't you do the same for Mac OS X? I think `man ps` will tell you something.

```
> ps awx | grep nvim
 1478 pts/0    Sl+    0:00 /tmp/.mount_nvim.aRiFr3F/usr/bin/nvim -u NORC
 1487 ?        Ssl    0:00 /home/erw7/nvim.appimage -u NORC
 1502 pts/1    S+     0:00 grep nvim
```

**Comment by dalu98** [comment]
Yes, but I got this

```
99531 s002  R+     0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox nvim
79808 s006  S+     0:00.04 nvim -u NORC
```

So this means my tty is `s002`, right?

**Comment by skeept** [comment]
In windows `ctrl-z` or `:suspend` always leaves the editor in a state that I cannot recover from I have to kill it from the process explorer list. 
Is this a documented behavior? 

I tried it with several terminals (conemu, default cmd, windows terminal and new windows terminal).

**Comment by erw7** [comment]
@skeept That is an old problem that has remained from #6660.

**Comment by erw7** [comment]
@dalu98 Sorry I don't know much about Mac TTY's, so I can't reply to you. #13084 will solve your problem?

**Comment by dalu98** [comment]
> @dalu98 Sorry I don't know much about Mac TTY's, so I can't reply to you. #13084 will solve your problem?

Thanks for your working!
But I haven't tried build from source once since I always use `brew install neovim --HEAD`, so I don't know whether I'm doing right. If there are any wrong steps I made, please let me know

**Comment by dalu98** [comment]
> @dalu98 Sorry I don't know much about Mac TTY's, so I can't reply to you. #13084 will solve your problem?

Thanks for your working!

But I haven't tried build from source once since I always use brew install neovim --HEAD, so I don't know whether I'm doing right. If there are any wrong steps I made, please let me know.

Here is the steps:
```
$ git clone --depth 1 https://github.com/neovim/neovim.git
$ cd neovim
$ nvim tui/tui.c
...
# Then I copy your pr code into the `tui.c`
...
$ make
```

After building
```
$ build/bin/nvim -u NORC
```
And the screen shows like this
![Uploading 20201011-122012.jpg…]()

But unfornately, I still can repreoduce the behavior I mentioned before...

<details>
<summary>updated information</summary>


- `build/bin/nvim --version`:
```
NVIM v0.5.0-f7cc3ae-dirty
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-pro\
totypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DIN\
CLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/Users/dalu/src/neovim/build/config -I/User\
s/dalu/src/neovim/src -I/Users/dalu/src/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettex\
t/include -I/Users/dalu/src/neovim/build/src/nvim/auto -I/Users/dalu/src/neovim/build/include
Compiled by dalu@dalu.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?

Yes, even they share the same config.

- Operating system/version: macOS/10.15.7
- Terminal name/version: iTerm2/3.3.12. Happened both in tmux or not (tested in Alacrity, the result is the same)
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
build/bin/nvim -u NORC

# Type =C-z= back to terminal

$ bg
[1]  + continued  build/bin/nvim -u NORC
[1]  + suspended (tty output)  build/bin/nvim -u NORC
$ fg
[1]  + continued  build/bin/nvim -u NORC
```

### Actual behaviour

Nvim can't recognize my input after `fg` to bring nvim back to front while vim works fine at the same config.

For example, after `fg` brings nvim to front, press `i` to try to go into`Insert Mode`, and the reponse is input `i` into the screen. It looks like the nvim has frozen.

And after this, the only way to quit nvim is to press <kbd>C-z</kbd> again,  input `kill nvim`, and `fg`.
Then terminal will remind
```
[1]  - 49152 continued  nvim -u NORC
Vim: Caught deadly signal 'SIGTERM'

Vim: Finished.
```

</details>

**Comment by erw7** [comment]
@dalu98 What happens if you apply the following patch to HEAD and build it? Does terminate abnormally by `abort()` when resuming with `fg` after suspending?

```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 2ef9bf5a2..d4c60c92a 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -316,7 +316,11 @@ static void terminfo_start(UI *ui)
 #ifdef WIN32
     uv_tty_set_mode(&data->output_handle.tty, UV_TTY_MODE_RAW);
 #else
-    uv_tty_set_mode(&data->output_handle.tty, UV_TTY_MODE_IO);
+    int r = uv_tty_set_mode(&data->output_handle.tty, UV_TTY_MODE_IO);
+    if (r) {
+      fprintf(stderr, "uv_tty_set_mode failed: %d", r);
+      abort();
+    }
 #endif
   } else {
     uv_pipe_init(&data->write_loop, &data->output_handle.pipe, 0);
```

**Comment by dalu98** [comment]
> apply the following patch to HEAD

@erw7 Does that mean I should run `git reset --hard master` first, and then apply the patch; or apply the patch based on your pr code directly?

If the former, the result is this:
```
$ build/bin/nvim -u NORC

# After enter neovim, Press =C-z=

zsh: suspended  build/bin/nvim -u NORC
$ bg
[1]  + continued  build/bin/nvim -u NORC
[1]  + suspended (tty output)  build/bin/nvim -u NORC
$ fg
[1]  + continued  build/bin/nvim -u NORC
uv_tty_set_mode failed: -4zsh: abort      build/bin/nvim -u NORC
```

**Comment by erw7** [comment]
@dalu98 Thanks, I found the cause. `uv_tty_set_mode()` failed in `EINTR`. I checked the vim source and found that if `tcsetattr()` fails with `EINTR`, it will retry. I've changed #13084 to a similar implementation as vim, so give it a try.

PS I don't know much about building on Mac OS, so you can check out [Building Neovim](https://github.com/neovim/neovim/wiki/Building-Neovim#building) on the wiki.

**Comment by dalu98** [comment]
@erw7 Great! After applying your new commit, neovim works as I expected now.
Thank you very much for your patient help!
