### ISSUE TITLE
LSP: Commands extension point for plugins for code actions

### ISSUE THREAD

**Issue by mfussenegger** [neovim/neovim#12326]
With https://github.com/neovim/neovim/pull/11607 being merged I'd like to extend it with an extension point for commands. But first checking in to see if there is interest in that.

The result of a [Code Action Request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction) is an array of commands, and the spec says that it should preferably be handled by the server via `workspace/executeCommand`:

> The result of a textDocument/codeAction request is an array of Command literals which are typically presented in the user interface. To ensure that a server is useful in many clients the commands specified in a code actions should be handled by the server and not by the client (see workspace/executeCommand and ServerCapabilities.executeCommandProvider)

Emphasis here is on *should*. It leaves the option for clients to handle the commands and there are many scenarios where this is useful or necessary. For example if there is a code-action to generate a constructor, the client may prompt the user for which fields to include as parameters. Opt-in to that is done via the codeActionLiteralSupport.

VSCode provides an extension point for plugins to add commands handlers. I think it would be beneficial if neovim had this as well.

Currently a plugin could choose to override the `textDocument/codeAction` callback or provide a custom `code_action` function. But then each plugin that wants to handle some command in a custom way would end-up re-implementing the code-action boilerplate and would be incompatible with each other.

I've a version of a commands extension point in nvim-jdtls, there is a commands table:

```lua
M.commands = {
  ['java.apply.workspaceEdit'] = java_apply_workspace_edit;
  ['java.action.generateToStringPrompt'] = java_generate_to_string_prompt;
  ['java.action.hashCodeEqualsPrompt'] = java_hash_code_equals_prompt;
  ['java.action.applyRefactoringCommand'] = java_apply_refactoring_command;
  ['java.action.rename'] = java_action_rename;
}
```

I think such a table could be added to `vim.lsp.callbacks`, so that users could register them under `vim.lsp.callbacks.commands`.

And the `textDocument/codeAction` callback is extended to check if a client-command matches:

https://github.com/mfussenegger/nvim-jdtls/blob/aa163ceb4894a7852d3b5da51171ba7909e2decf/lua/jdtls.lua#L197

One thing to note here is that the client-commands receive the `code_action_params`, that is the parameters that were sent to the server's `textDocument/codeAction` endpoint.
Currently with the callbacks/request split, these wouldn't be accessible, so we'd have to add a parameter to all callbacks that contains the params that were sent with the request.

cc: @ckipp01 this may also be interesting for nvim-metals?

**Comment by ckipp01** [comment]
Interesting, thanks for tagging me @mfussenegger. Thinking about it, we handle this situation a bit different by always shooting them back to the server. A good example is if we have a diagnostic for a symbol not found, normally the code action will give the user two options:
1. Import it if it knows what to import (just done with an edit)
2. Create a new symbol (utilizing the new-scala-file command)

Instead of handling this all client side, we instead just shoot the command back to the server and the server uses a combination of `metals/quikpick` and `metals/inputbox` to get the user input necessary. The benefit is that we ensure everything does stay server side, however at the exclusion of clients that can't implement those LSP extensions.

So I'm not 100% sure this would benefit us at all. Plus, I'm of the belief that the more the server can handle in these situations the better. Again, downside then is that many times they rely on LSP extensions, which then have to be implemented.

**Comment by mfussenegger** [comment]
> Instead of handling this all client side, we instead just shoot the command back to the server and the server uses a combination of metals/quikpick and metals/inputbox to get the user input necessary. The benefit is that we ensure everything does stay server side, however at the exclusion of clients that can't implement those LSP extensions.

Oh that's a nice approach. Unfortunately eclipse.jdt.ls doesn't follow that model :(


>  Plus, I'm of the belief that the more the server can handle in these situations the better

Yes me too, but it looks like that train has already left the station for many server implementations.

**Comment by tjdevries** [comment]
I like the idea @mfussenegger . I think it seems like a good idea to be able to register custom callbacks for custom commands. There will probably be lots of things that only make sense for certain languages, and it'd be good to allow people to just add a configuration point instead of overriding the whole callback.

**Comment by justinmk** [comment]
> Currently a plugin could choose to override the `textDocument/codeAction` callback or provide a custom `code_action` function. But then each plugin that wants to handle some command in a custom way would end-up re-implementing the code-action boilerplate and would be incompatible with each other.

what does that look like in practice? 

what if we provided a way to "inherit" an existing handler, something like:

```lua
extend_fn(lsp.handlers, 'foo', function(old_fn, handler_args)
end)

-- extend_handler saves the original function and passes it to the new one:
function extend_fn(handlers, key, new_fn)
  local old_fn = handlers[key]
  handlers[key] = function(...)
    return new_fn(..., old_fn)
  end
end
```

alternative: would it help if `handlers[key]` accepted a list of functions which are _all_ called?

**Comment by mfussenegger** [comment]
> https://github.com/mfussenegger/nvim-jdtls/blob/f52ed6ef5c71f5af976134e11674fec9720e70c9/lua/jdtls.lua#L638-L702

(This also supports `codeAction/resolve` which isn't implemented in neovim core yet.)

Is an example of a re-implementation. 

> what if we provided a way to "inherit" an existing handler, something like:

This wouldn't solve the problem, because of the side effects within the handlers. The built-in handler always tries to execute the command using the server:

https://github.com/neovim/neovim/blob/3ab73ff81f4a487e97a057c06bd6c07df9cef9e3/runtime/lua/vim/lsp/handlers.lua#L131-L140

We could change that to check the server capability (and probably should, independently of this issue here), but if plugins would then chain the handlers, each would need to implement the "pick one action" part and you'd have multiple dialogs open up.

The client commands are also relevant for the code lenses. (E.g. rust-analyzer has a "run test" code lens, which requires a client command to work).
