### ISSUE TITLE
edited read only file when saved it with vim command doesn't work

### ISSUE THREAD

**Issue by Adolf-L** [neovim/neovim#12330]
when I was using neovim with the command "w !sudo tee %" it didn't work.
![image](https://user-images.githubusercontent.com/10137107/82140689-2a795380-9863-11ea-9941-1608d9ad0416.png)

when I was using vim with the command "w !sudo tee %" it works. as you can see
![image](https://user-images.githubusercontent.com/10137107/82140710-54cb1100-9863-11ea-84ea-0fc2ecb6a057.png)

what should I do?

**Comment by glacambre** [comment]
This is a duplicate of https://github.com/neovim/neovim/issues/12103, https://github.com/neovim/neovim/issues/1716 and https://github.com/neovim/neovim/issues/1496 . One workaround is to use this plugin: https://github.com/lambdalisue/suda.vim

**Comment by teto** [comment]
closing as duplciate
