### ISSUE TITLE
Unicode lines clip into number column

### ISSUE THREAD

**Issue by justinnhli** [neovim/neovim#12335]
- `nvim --version`: v0.5.0-138-ge2b54fda7
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: Arch Linux 5.6.11-arch1-1
- Terminal name/version: kitty 0.15.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -c 'set nu' nvim-bug.txt
```

[nvim-bug.txt](https://github.com/neovim/neovim/files/4641398/nvim-bug.txt)

### Actual behaviour
![before-toggle](https://user-images.githubusercontent.com/624737/82163983-159cc000-9863-11ea-8629-3a57f1f87844.png)

Strangely, a different type of clipping occurs if I `set wrap` and `set nowrap`:

![after-toggle](https://user-images.githubusercontent.com/624737/82163997-29482680-9863-11ea-87ef-5ddfd0754fa9.png)

### Expected behaviour

![expected](https://user-images.githubusercontent.com/624737/82163987-17ff1a00-9863-11ea-817f-0e8f8dec7bfc.png)

**Comment by teto** [comment]
confirmed. thanks for the detailed report.

**Comment by glacambre** [comment]
Can't reproduce on master :tada: .
