### ISSUE TITLE
API documentation has argument in wrong place

### ISSUE THREAD

**Issue by alerque** [neovim/neovim#12340]
I tried setting up a Lua plugin to watch changes and operates on the changed line and thereafter. According to [the API docs](https://neovim.io/doc/user/api.html#nvim_buf_attach()) the first changed line should be the third argument passed to my callback.

> • buffer handle
> • b:changedtick
> • first line that changed (zero-indexed)
> • last line that was changed
> • last line in the updated range
> • byte count of previous contents
> • deleted_codepoints (if `utf_sizes` is true)
> • deleted_codeunits (if `utf_sizes` is true)

Unfortunately the 3rd argument was some other (much smaller and incrementing) number. It turs out the fourth arg seems to whe what I was after, like this:

```lua
nvim.api.nvim_buf_attach(buffer, false, {
    on_lines = function (_, _, _, firstline, _, _)
        myfunction(firstline)
...
```

I don't know what the other args are, but it seems like they changed since the document string was written.

Using distro (Arch) built Neovim v0.4.3.

**Comment by h-michael** [comment]
It seems that first argument is "lines".
https://github.com/neovim/neovim/blob/a723d605490567c9e9cf961aa85b80e8a729db1e/src/nvim/buffer_updates.c#L268
