### ISSUE TITLE
setreg({regname}, []) doesn't clear nor delete the register {regname}

### ISSUE THREAD

**Issue by Atralb** [neovim/neovim#12353]
- `nvim --version`: v0.2.2
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Ubuntu 18.04
- Terminal name/version: Terminator v1.91
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:call setreg('a', [])
```

### Actual behaviour

Register `a` value is replaced by `^J`

### Expected behaviour

Register `a` is deleted and does not appear in the output of `:reg` anymore.

### Explanation

This is the actual behavior of bare `vim`. This is also supposed to be the expected behavior as explained [here](https://stackoverflow.com/a/39348498/10104664).

The `nvim` documentation for `:h setreg()` doesn't differ from the one from vim (except for one thing that isn't related), so that is why I believe this is a bug. But I am admittedly not experienced enough to be positive on this.

**Comment by zeertzjq** [comment]
Fixed by #15731
