### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by paum3** [neovim/neovim#12354]
Hi, it is possibile to 'detach' split window into new gui instance of neovim?
thanks.

**Comment by tjdevries** [comment]
Potentially with neovim remote ( https://github.com/mhinz/neovim-remote ) or similar.

**Comment by glacambre** [comment]
I don't think this is possible for splits yet - this would require split 
windows to have their own grids and neovim's ui protocol doesn't support 
that for now (but it's planned - you can subscribe to 
https://github.com/neovim/neovim/pull/8707 to be notified once it's 
possible).

You can however do this for floating windows, which can have their own 
grids with ext_multigrid. I'm not sure any tool implements this though.

**Comment by teto** [comment]
it's not possible yet but was being worked on during last's year gsoc. The code is not merged yet though but that's one of our goal.
