### ISSUE TITLE
mpv's tct video output makes nvim segfault

### ISSUE THREAD

**Issue by FallenWarrior2k** [neovim/neovim#12366]
Yes, you read that right. I tried to play a video file in a `:terminal` buffer using mpv. Why, you ask? I found it in the man page, wanted to try it out as a joke and happened to have a nvim session with a terminal buffer open at the time. Pure coincidence paired with curiosity.

Let me preface this that I have no need to actually see this working. I just felt that, even for abnormal circumstances, it should not be possible to predictably and reliably induce a segfault in a non-alpha/beta/rc/whatever version. Feel free to ignore if you think it's okay to crash for a nonsensical use case like this, I honestly can't bring myself to disagree.

- `nvim --version`:
```                                           
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? Does not apply, since `:terminal` is a Neovim-only feature.
- Operating system/version: Arch Linux, current (at time of writing)
- Terminal name/version: Kitty 0.17.4
- `$TERM`: `xterm-kitty`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
:terminal mpv --vo=tct 'some/video/file/here.mp4'
```

### Actual behaviour

Nvim segfaults shortly after playback starts, corrupting the terminal session. How long it takes to segfault depends on the video file, and it actually survives some extremely short files, but most do crash it.

From what I've seen in my limited testing, the time-to-crash depends solely on the video file. I tried using multiple different terminal emulators for nvim itself, and while none of them would complain about mpv if run directly from the shell, nvim would always crash at the same location in the video.

If you want a file to repro, I could provide one.

### Expected behaviour

Nvim should not segfault.

**Comment by teto** [comment]
you are right in assuming that it should not segfault in any case. Can you reproduce with master ?

**Comment by oni-link** [comment]
On master:

```bash
AddressSanitizer:DEADLYSIGNAL
=================================================================
==12957==ERROR: AddressSanitizer: SEGV on unknown address 0x7f8c35cba804 (pc 0x000000b69731 bp 0x0c62000022e8 sp 0x7f8c37676360 T1)
==12957==The signal is caused by a READ memory access.
    #0 0xb69731 in update_attrs /home/oni-link/git/neovim/build/../src/nvim/tui/tui.c:524:19
    #1 0xb616d4 in print_cell /home/oni-link/git/neovim/build/../src/nvim/tui/tui.c:667:3
    #2 0xb616d4 in tui_raw_line /home/oni-link/git/neovim/build/../src/nvim/tui/tui.c:1323:3
    #3 0xb85b9b in ui_bridge_raw_line_event /home/oni-link/git/neovim/build/../src/nvim/ui_bridge.c:157:3
    #4 0x6eb2a3 in multiqueue_process_events /home/oni-link/git/neovim/build/../src/nvim/event/multiqueue.c:157:7
    #5 0x6e920f in loop_poll_events /home/oni-link/git/neovim/build/../src/nvim/event/loop.c:70:3
    #6 0xb62eac in tui_main /home/oni-link/git/neovim/build/../src/nvim/tui/tui.c:448:5
    #7 0x7f8c3b741e96 in start_thread (/lib64/libpthread.so.0+0x7e96)
    #8 0x7f8c3b51d66e in clone (/lib64/libc.so.6+0xf866e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/oni-link/git/neovim/build/../src/nvim/tui/tui.c:524:19 in update_attrs
Thread T1 created by T0 here:
    #0 0x476552 in pthread_create /home/oni-link/git/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:214:3
    #1 0xc99673 in uv_thread_create_ex /home/oni-link/git/neovim/.deps/build/src/libuv/src/unix/thread.c:258:9

==12957==ABORTING

```
Crash happens in this line:

https://github.com/neovim/neovim/blob/97bcab8f5eeb8c5b2627fdfc3adad2682bb3681e/src/nvim/tui/tui.c#L524

`attr_id` is a signed type that has a negative value when indexing the vector/array `data->attrs`.  Casting it to an unsigned type does not help.

**Comment by teto** [comment]
I got ```
Reading in symbols for /home/teto/neovim/src/nvim/ui_compositor.c...done.
#4  0x00000000007612e9 in ui_comp_raw_line (Reading in symbols for /home/teto/neovim/src/nvim/ui.c...done.
ui=0x24e8000, grid=1, row=2, startcol=49, endcol=91, clearcol=91, clearattr=0, flags=0, chunk=0x284cbad, attrs=0x2792392)
    at /home/teto/neovim/src/nvim/ui_compositor.c:549
#5  0x0000000000756f56 in ui_call_raw_line (grid=1, row=2, startcol=49, endcol=91, clearcol=91, clearattr=0, flags=0, chunk=0x284cbad, 
    attrs=0x2792392) at /home/teto/neovim/build/src/nvim/auto/ui_events_call.generated.h:230
#6  0x000000000075d545 in ui_line (Reading in symbols for /home/teto/neovim/src/nvim/screen.c...done.
grid=0x89ffd0 <default_grid>, row=2, startcol=49, endcol=91, clearcol=91, clearattr=0, wrap=false)
    at /home/teto/neovim/src/nvim/ui.c:381
#7  0x00000000006d0397 in grid_put_linebuf (grid=0x89ffd0 <default_grid>, row=2, coloff=0, endcol=136, clear_width=136, rlflag=0, 
    wp=0x279e650, bg_attr=0, wrap=false) at /home/teto/neovim/src/nvim/screen.c:4687
```
