### ISSUE TITLE
Neovim + tmux/screen + alacritty/kitty renders unicode badly with termguicolors

### ISSUE THREAD

**Issue by juliancoffee** [neovim/neovim#12364]
- `nvim --version`:

> NVIM v0.4.3
> Build type: Release
> LuaJIT 2.0.5
> Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
> Compiled by builduser
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
>
> Run :checkhealth for more info

- `vim -u DEFAULTS` (version: ) behaves differently?

> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  8 2020 23:37:13)
> Included patches: 1-717
> Compiled by Arch Linux
> Huge version with GTK3 GUI.  Features included (+) or not (-):
> +acl               -farsi             +mouse_sgr         +tag_binary
> +arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
> +autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
> +autochdir         +float             +mouse_xterm       +tcl/dyn
> -autoservername    +folding           +multi_byte        +termguicolors
> +balloon_eval      -footer            +multi_lang        +terminal
> +balloon_eval_term +fork()            -mzscheme          +terminfo
> +browse            +gettext           +netbeans_intg     +termresponse
> ++builtin_terms    -hangul_input      +num64             +textobjects
> +byte_offset       +iconv             +packages          +textprop
> +channel           +insert_expand     +path_extra        +timers
> +cindent           +ipv6              +perl/dyn          +title
> +clientserver      +job               +persistent_undo   +toolbar
> +clipboard         +jumplist          +popupwin          +user_commands
> +cmdline_compl     +keymap            +postscript        +vartabs
> +cmdline_hist      +lambda            +printer           +vertsplit
> +cmdline_info      +langmap           +profile           +virtualedit
> +comments          +libcall           +python/dyn        +visual
> +conceal           +linebreak         +python3/dyn       +visualextra
> +cryptv            +lispindent        +quickfix          +viminfo
> +cscope            +listcmds          +reltime           +vreplace
> +cursorbind        +localmap          +rightleft         +wildignore
> +cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
> +dialog_con_gui    +menu              +scrollbind        +windows
> +diff              +mksession         +signs             +writebackup
> +digraphs          +modify_fname      +smartindent       +X11
> +dnd               +mouse             +sound             -xfontset
> -ebcdic            +mouseshape        +spell             +xim
> +emacs_tags        +mouse_dec         +startuptime       -xpm
> +eval              +mouse_gpm         +statusline        +xsmp_interact
> +ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
> +extra_search      +mouse_netterm     +syntax            -xterm_save
>    system vimrc file: "/etc/vimrc"
>      user vimrc file: "$HOME/.vimrc"
>  2nd user vimrc file: "~/.vim/vimrc"
>       user exrc file: "$HOME/.exrc"
>   system gvimrc file: "/etc/gvimrc"
>     user gvimrc file: "$HOME/.gvimrc"
> 2nd user gvimrc file: "~/.vim/gvimrc"
>        defaults file: "$VIMRUNTIME/defaults.vim"
>     system menu file: "$VIMRUNTIME/menu.vim"
>   fall-back for $VIM: "/usr/share/vim"
> Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
> Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf    -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.30/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     

Similarly, but with ` :set termguicolors` colours are disappearing in vim
![image](https://user-images.githubusercontent.com/42647349/82684985-26cb3f80-9c5c-11ea-9d88-0de5be6669eb.png)
- Operating system/version:

> Arch Linux

- `uname -a`
> Linux archlinux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux

- Terminal name/version:

> alacritty 0.4.2
> kitty 0.17.4 created by Kovid Goyal

- Terminal multiplexor 
> tmux 3.1b
> Screen version 4.08.00 (GNU) 05-Feb-20

- `$TERM`:
> tmux-256color (alacritty/kitty tmux)
> screen.xterm-256color (alacritty + screen)
> screen (kitty + screen)
> xterm-kitty (kitty)
> xterm-256color (alacritty) 

### Steps to reproduce using `nvim -u NORC`
 

example.txt
```
[Desktop Entry]
Comment[ta]=உரை கோப்புகளை தொகுக்கவும்
```

```
$ tmux
$ nvim -u NORC example.txt
:set termguicolors
:colo desert
```

### Actual behaviour
Symbols rendered very strangely, not on their places. 

> (screenshot from opening /usr/share/applications/nvim.desktop)

Exception: kitty + screen, as I understand it is because $TERM variable
- alacritty + tmux
![image](https://user-images.githubusercontent.com/42647349/82685161-6d209e80-9c5c-11ea-8fc7-c0ed5085d3c2.png)
- alacritty + screen
![image](https://user-images.githubusercontent.com/42647349/82685222-84f82280-9c5c-11ea-87d2-90bc3d683cc2.png)
- kitty + tmux
![image](https://user-images.githubusercontent.com/42647349/82685274-9e00d380-9c5c-11ea-87fb-59d4293cf1c0.png)
- kitty + screen
![image](https://user-images.githubusercontent.com/42647349/82685345-b7a21b00-9c5c-11ea-8bbd-4cdd9ee25164.png)

### Expected behaviour
Everything renders correctly as without tmux
- alacritty or kitty
![image](https://user-images.githubusercontent.com/42647349/82685465-e61ff600-9c5c-11ea-901e-f45b57dcc209.png)

**Comment by juliancoffee** [comment]
After `$ export TERM=xterm-256colors` situation remains the same.

But if I set `TERM=tmux-256colors` in alacritty without tmux, I got this problem again

**Comment by kyazdani42** [comment]
I'm not sure if this would fix your issue, but did you try to set `TERM=alacritty` ? if you set bad terminfos then you might end up having rendering issues with libraries that rely on it.

**Comment by mnrce** [comment]
What is the output of `locale`? I recently ran into this issue with tmux because my `LC_ALL` was set to `C`  for some reason, and that made tmux think my terminal doesn't support Unicode.

**Comment by juliancoffee** [comment]
> I'm not sure if this would fix your issue, but did you try to set `TERM=alacritty` ? if you set bad term info then you might end up having rendering issues with libraries that rely on it.
> edit: you can check [this issue](https://github.com/alacritty/alacritty/issues/3354).

On another system, I have kitty $TERM=screen inside tmux and it also has this problem.
If I have set TERM to alacritty or remove setting TERM in .tmux.conf situation remains the same.

**Comment by juliancoffee** [comment]
My locale is 

> LANG=en_US.UTF-8
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=

**Comment by kyazdani42** [comment]
in my tmux.conf i have 
```
# only this line might not be enough
set -g default-terminal "tmux-256color"
# Needs this line also to overrides the default color
set-option -ga terminal-overrides ",xterm-256color:Tc"
```

**Comment by juliancoffee** [comment]
@kyazdani42 same as I have.

**Comment by kyazdani42** [comment]
well i can reproduce the issue with screen. In fact i think screen does not support true color, i have rendering issues with other terminal application using screen. Tmux works just fine right ?

**Comment by juliancoffee** [comment]
Tmux works fine) But when I had opened some files (nvim.desktop for example), which uses some exotic alphabet, I got this issue.
It's not so disturbing for me, because I'm usually not editing such files, but it exists even in vscode terminal (with or without tweaks with overriding the terminal in tmux.conf).
Maybe, you are using another version of tmux or neovim?

**Comment by kyazdani42** [comment]
Well this might occur because of font resolution on your system. You might even not have those fonts installed (i though this issue was about colors). You should not compare outputs from terminals in the system to terminals inside electron apps, because they are using web browser fonts, which are not the same.
This issue does not related to neovim at all. If you encounter glyphs in terminals, install the appropriate fonts

**Comment by kyazdani42** [comment]
well i don't really know, do not compare with vscode though, electron app fonts do not use you system's font if i'm not mistaken. I do not have font rendering issues on my end.
Is this issue about bad font rendering or wrong color rendering ? Either way, i do not think it's vim/neovim related, but it might just be limitations of screen/tmux or your system.

**Comment by justinmk** [comment]
can't reproduce with  v0.11.0-dev-792+g 84e85aeb10ae

works with/without tmux :

![image](https://github.com/user-attachments/assets/71b1c445-ec47-4bc7-bb9f-417779072943)
