### ISSUE TITLE
[LSP] Extra symbol in header completion

### ISSUE THREAD

**Issue by Shatur95** [neovim/neovim#12363]
- `nvim --version`: c6dc397801d0566b583d4916220a60f17e609e25
- Operating system/version: Arch Linux

### Steps to reproduce

1. Open `nvim` with configured `nvim-lsp` and `clangd`.
2. Try to complete via omnifunc: `#include <iostream>`

### Actual behaviour

`iostream` completed as `iostream>`, so the result will be `#include <iostream>>`.

### Expected behaviour

`iostream` completed as `iostream`, so the result will be `#include <iostream>`.

### Notes

Third-party LSP plugins have the same issue. For example, [vim-lamp](https://github.com/hrsh7th/vim-lamp) (was fixed in https://github.com/hrsh7th/vim-lamp/commit/b291b42bbe96805bbb59872a4eb87d3db967745f) and [vim-lsp](https://github.com/prabirshrestha/vim-lsp) (still unfixed).

I would like to help with fixing, but I not familiar with codebase. Could anyone say where the LSP completion parsing occurs?

**Comment by tjdevries** [comment]
The omni func completion is implemented in `runtime/lua/vim/lsp.lua` in `lsp.omnifunc`. It's around line 900 (depending on your version and when you look at this).

**Comment by Shatur95** [comment]
@tjdevries, thanks, but I think that this issue occurs at parsing part from language server. [completion-nvim](https://github.com/haorenW1025/completion-nvim) have the same issue. And third-party LSP clients have the issue in their side.

**Comment by mfussenegger** [comment]
@Shatur95 

The conversion from the server response to the completion candidates happens here:

https://github.com/neovim/neovim/blob/f3d0a1741ef69222ab7893ce4f801d26b6b3fb00/runtime/lua/vim/lsp/util.lua#L227-L272

**Comment by hrsh7th** [comment]
I removed the implementation that fixes completed_item.word from vim-lamp then I ported the implementation to my hobby completion engine.

I don't know where is the best place to put the fixing implementation...

I share https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe/completion/source.lua#L151 as a reference implementation but I not sure this is reasonable.

**Comment by mjlbach** [comment]
Seems to work fine for me? 

![image](https://user-images.githubusercontent.com/13316262/111838582-c7a77d00-88b6-11eb-854a-537437fae593.png)

https://user-images.githubusercontent.com/13316262/111838641-d726c600-88b6-11eb-853e-505b3a926201.mov


I also tested with comp-e and it's fine.

https://user-images.githubusercontent.com/13316262/111838667-e3ab1e80-88b6-11eb-8227-19c216b0d69e.mov


Can this be closed?
