### ISSUE TITLE
Signcolumn and number column into one

### ISSUE THREAD

**Issue by pacmanzou** [neovim/neovim#12372]
set signcolumn=number
I hope neovim can add the characteristic of vim as soon as possible.Thank you very much!

**Comment by teto** [comment]
for context, the patch https://github.com/manuelschiller/vim/commit/00d4f615ba5ccd583b5899ba6bd90d38c8354275 and the issue https://github.com
The different column configuration and request becomes so complex that at some point it may just evolve into its own DSL :s  (relative number vs number, showing showbreak, autowidth etc).
We should allow to add random columns (right/left) filled by the plugin. There was a proposal for a column API but can't find it anymore.

**Comment by pacmanzou** [comment]
OK,
Thank you for your answer!

**Comment by teto** [comment]
lets keep this open until the vim patch is merged.

**Comment by pacmanzou** [comment]
good

**Comment by pablopunk** [comment]
any news here? What's needed to get this one into neovim?

**Comment by teto** [comment]
we just need someone to port the relevant patches.

**Comment by antoinemadec** [comment]
@mhinz @da-x , is there any chance you could implement vim's **patch 8.1.1564: sign column takes up space ** https://github.com/manuelschiller/vim/commit/00d4f615ba5ccd583b5899ba6bd90d38c8354275 ?

I tried to patch it myself but there are conflicts in `option.c` and `screen.c ` around code that you wrote.
This this way above my league :smile:

**Comment by sentriz** [comment]
this would be brilliant :D

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/pull/12621

I have tried, but it is not so easy.
