### ISSUE TITLE
VimEnter autocommands more expensive in NeoVim vs Vim?

### ISSUE THREAD

**Issue by Nazeehe** [neovim/neovim#12375]
- `nvim --version`:
NVIM v0.5.0-519-g74fed7d50
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

- Vim Version (relevant):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 13 2020 22:19:49)
MS-Windows 64-bit console version
Included patches: 1-752

- Operating system/version: Windows 10 1909 (Nov Update)
- Terminal name/version: Windows Terminal running PowerShell

Issue I am seeing here is that in NeoVim, VimEnter autocmds seem to take significantly longer to execute at startup than in Vim. I ran a StartupTime on both with same Vimrc config:

NeoVim VimEnter autocommand will take 407.24 ms taking up 33.83% of my startup time. 
Vim will take 25.00 ms with a 4.55% instead.
Quite the difference. 

Running: autocmd VimEnter in both shows the exact same thing:

--- Autocommands ---
coc_nvim  VimEnter
    *         call coc#rpc#notify('VimEnter', [])
VM_start  VimEnter
    *         call s:vm_registers()
FileExplorer  VimEnter
    *         sil call s:VimEnter(expand("<amatch>"))
indentLine  VimEnter
    *         call s:VimEnter()

Is this expected? What can I share to help diagnose this?

### Actual behaviour
VimEnter autocmds take much longer to execute at startup in NeoVim vs Vim

### Expected behaviour
VimEnter autocmds take similar time to execute in NeoVim as they do in Vim.

**Comment by Nazeehe** [comment]
Little more info, I made config changes to have it so that nothing appears in "autocmd VimEnter" and it didn't matter. Time was not reduced. Not sure what else is running in there at the moment or why it takes this long. Unless possible it's buggy reporting by Startuptime plugin?

**Comment by teto** [comment]
nvim has different defaults than vim. If you can run vim with the same settings you may end up with similar numbers (see `:h nvim-defaults`)

**Comment by Nazeehe** [comment]
Makes sense. Thanks!
