### ISSUE TITLE
can't go back to normal mode after paste

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#12371]
- `nvim --version`:NVIM v0.5.0-519-g74fed7d50
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version:macos
- Terminal name/version: kitty
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`
1. https://arxiv.org/pdf/1703.08033.pdf
Copy this paragraph to the pasteboard
![image](https://user-images.githubusercontent.com/19503791/82745978-0a92e400-9dbd-11ea-821f-2e53b82859e8.png)
2. `nvim -u NONE` and start insert mode
3. paste the text to nvim (macOS: CMD-v)
4. you will find can't go back to normal mode

**Comment by glacambre** [comment]
Might be related to https://github.com/neovim/neovim/issues/11699 .

**Comment by zeertzjq** [comment]
Does this bug still exist?

**Comment by amerixan** [comment]
This bug does not exist on NVIM v0.7.0-dev+792-gc46f7caad.

**Comment by zeertzjq** [comment]
It is very likely that this has been fixed by #12004
