### ISSUE TITLE
set foldopen-=search goes to a never-ending loop

### ISSUE THREAD

**Issue by kutsan** [neovim/neovim#12370]
- `nvim --version`: `NVIM v0.5.0-04a0486c6`
- `vim -u DEFAULTS` (version: ) behaves differently? `Yes`
- Operating system/version: `macOS 10.14.6 (18G95)`
- Terminal name/version: `kitty, 0.17.4`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim --clean`

```
1. nvim --clean

2. :set foldopen-=search foldmethod=indent

3. (Write the following into the buffer)
if
	foo
	foo
endif

4. (Fold the lines with za if it's not already folded.)
if
+--  2 lines: foo··············································································································
endif

5. /foo<CR>
6. n
7. n
8. n
9. n
.
.
.
```

### Actual behaviour

Pressing `n` makes a new entry in search list, thus it goes to a never-ending cycling.

### Expected behaviour

Pressing `n` should cycle through that two `foo`.

See for the mirror issue: https://github.com/vim/vim/issues/6152

**Comment by erw7** [comment]
This issue also occurs when starting vim (8.2.773) with the following command line options. You might want to send this report to https://github.com/vim/vim as well (If so, please create a reference the issue here).

```
vim -Nu NORC -c 'set shm-=S fdo-=search fdm=indent'
```

**Comment by chrisbra** [comment]
thanks for the issue. I'll have a look

**Comment by kutsan** [comment]
@chrisbra Should I open an issue under vim repository?

**Comment by chrisbra** [comment]
if you like

**Comment by kutsan** [comment]
FYI this is fixed in https://github.com/vim/vim/commit/6cb0726215519fe94103803e4aa77a355384bcf2 by @chrisbra.

**Comment by glacambre** [comment]
Looks like the corresponding patch has been ported, let's close this :).
