### ISSUE TITLE
Way to detect if a floating window is currently present or a way to count floating windows

### ISSUE THREAD

**Issue by pyrr** [neovim/neovim#12389]
I have some stuff which depends on a winnr('$') in my init.vim. Is there any way I can exclude floating windows from this winnr('$') ?

**Comment by glacambre** [comment]
On 2020-05-28 03:54, pyrr wrote:
> I have some stuff which depends on a winnr('$') in my init.vim. Is there 
> any way I can exclude floating windows from this winnr('$') ?

I believe `filter(nvim_list_wins(), {k, v -> 
nvim_win_get_config(v).relative == ''})` should give you a list of 
windows that aren't floating, so taking the last element of that list 
would be equivalent to a `winnr('$')` that excludes floating windows.

**Comment by pyrr** [comment]
:echo filter(nvim_list_wins(), {k,v->nvim_win_get_config(v).relative ==""}) gives me [1000] on neovim-nightly
Maybe I'm just adding the quote that is missing in the wrong place..

**Comment by glacambre** [comment]
On 2020-05-28 09:20, pyrr wrote:
> :echo filter(nvim_list_wins(), {k,v->nvim_win_get_config(v).relative 
> ==""}) gives me [1000] on neovim-nightly
> Maybe I'm just adding the quote that is missing in the wrong place..

Oh, sorry, I thought you wanted the window's ID, not the window's 
number. You can use `win_id2win()` to convert window IDs to window 
numbers, e.g. `win_id2win(1000)` should return "1".

**Comment by pyrr** [comment]
I'm actually looking for the total number of un-floating windows but I think I can make this work with a loop if I am understanding thinks the right way.
Here's an example of my use case:
+ 2 windows open inside vim
+ floating window shows up because of a completion or diagnostic plugin
+ 2 windows open plus that floating window cause winnr('$') to be 3

 If it's not too much to ask please reply further with any suggestions. Thanks for all.

**Comment by glacambre** [comment]
>I'm actually looking for the total number of un-floating windows

Oh, then that's just `len(filter(nvim_list_wins(), {k,v->nvim_win_get_config(v).relative==""}))` I think :)

Note that this will return the number of windows across all tabs. If you want the number of windows in the current tab, you can replace `nvim_list_wins` with `nvim_tabpage_list_wins(0)`.

**Comment by nyngwang** [comment]
The `vim.api.nvim_win_get_config(0)` fuckingly saves me from 2hours of frustration. Thanks for @glacambre !!!!!!!!!!!!!!!!!!!!!!
