### ISSUE TITLE
Add more fields to `v:event` struct

### ISSUE THREAD

**Issue by clason** [neovim/neovim#12381]
Extending the range of fields set for the even struct would be helpful.

Specifically, the `TextYankPost` event could set a boolean `visual` that shows whether the yanked text came from a visual selection rather than, say, a motion. (This would allow ignoring the highlight on yank from #12279 for visual selections which are already sufficiently highlighted.)

I'm sure other useful additions exist?

@tjdevries

**Comment by tjdevries** [comment]
I think I'll close this in favor of just adding the one that we you have in your PR. Someone can make a separate issue / request / PR if they have a specific field they want. TY for PR.
