### ISSUE TITLE
Command remapping

### ISSUE THREAD

**Issue by badench** [neovim/neovim#12395]
Hi i'm sorry to bother everyone with this question however I have searched and searched and can not find the answer. From builtin commands I can use :Te to open a new tab page with the file explorer open. Often when I am trying to do this i type :te which opens the terminal. I want to unmap :Te and remap that same functionality to a sequence like leader-te. How can I accomplish this?

**Comment by glacambre** [comment]
On 2020-05-29 05:52, Connor Bade wrote:
> Hi i'm sorry to bother everyone with this question however I have 
> searched and searched and can not find the answer. From builtin commands 
> I can use :Te to open a new tab page with the file explorer open. Often 
> when I am trying to do this i type :te which opens the terminal. I want 
> to unmap :Te and remap that same functionality to a sequence like 
> leader-te. How can I accomplish this?

Have you tried `:nnoremap <Leader>te <Cmd>Te<Space>`?

**Comment by badench** [comment]
glacambre that mapping works, anyway to unmap the Ex command :Te so it's not possible to type anymore?

**Comment by glacambre** [comment]
I think `:delcommand Te` should work (see `:help delcommand`). However, 
this will prevent you from using your `<Leader>Te` mapping. What you 
could do then is to see what `Te` is bound to with `:command Te` and 
call the definition directly in your mapping, although I don't think 
there's really a point to that. Having a `:Te` command doesn't prevent 
you from doing anything.

**Comment by badench** [comment]
cool thanks. I'll close this issue thanks for the help
