### ISSUE TITLE
Actually Write all Files with :wa (or at least :wa!)

### ISSUE THREAD

**Issue by kcwitt** [neovim/neovim#12394]
The `:w` command will write the file whether or not it has changes. This is convenient when debugging because then it is possible to have something watch the file and reload it in the debugger anytime it is written.

The documentation for the `:wa` command notes that it won't write files that don't have changes (because it is smart enough not to).

Request to either make the `:wa` command consistent with the `:w` command and always write the file whether on not it has changes; or to make the `:wa!` command always write changes (with the exclamation meaning to write all files whether or not they have changes).

**Comment by erw7** [comment]
If you want to write all buffers unconditionally, you can use `:bufdo! w`.

**Comment by jamessan** [comment]
`:wa!` already has another meaning (also write read-only buffers), so we can't repurpose that.

I think @erw7's suggestion is a sufficient workaround.
