### ISSUE TITLE
man.vim: q should always map to :quit

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#12409]
When using `man.vim` as `$MANPAGER`, `q` is mapped to `:quit` so that you can easily quit neovim as with `less`.

However, when using `man.vim` from within an existing neovim session with `:Man printf`, `q` maps to `:close`.

I can't remember why we explicitly decided to do this but I think we should always map `q` to `:quit` as that's how the builtin `help` behaves. If you press `q` when there's only a help window remaining, neovim exits and does not require an explicit `:quit`.

Code in question is https://github.com/neovim/neovim/blob/ee1199eaba7cafa6b60611ebece1407bc274e330/runtime/ftplugin/man.vim#L29-L33

**Comment by nhooyr** [comment]
@tjdevries Please assign me this as well.

**Comment by rambip** [comment]
I have a bug with the nightly build of 0.5:
When I type "q" to quit, I get the following error "E444, cannot close last window".
I checked, and that does not come from my config: the "q" key works in the stable version of neovim.

Should I open a different issue ?

**Comment by justinmk** [comment]
> I think we should always map `q` to `:quit` as that's how the builtin `help` behaves. If you press `q` when there's only a help window remaining, neovim exits and does not require an explicit `:quit`.

Builtin help doesn't have `q` mapping so I don't get this.

Related: https://github.com/neovim/neovim/pull/18443
