### ISSUE TITLE
Invalid Server Json Error with Sumneko_lua server

### ISSUE THREAD

**Issue by ludwj61** [neovim/neovim#12405]
- `nvim --version`: v0.5.0-535-g7d8dc4c33
- Operating system/version: Ubuntu through windows 10 WSL2
- Terminal name/version: Alacritty most recent pre-release
- `$TERM`: xterm-256color, tmux-256color

### Actual behaviour
"INVALID SERVER JSON ERROR" (sometimes with other random text) shows during or after invoking the server. Here is an example with nvim-lsp & completion-nvim:

This happens when just moving through text sometimes:
![image](https://user-images.githubusercontent.com/42984254/83340412-6f5eaa80-a2a5-11ea-898d-fac05b6f840b.png)

This one happened when using a snippet from Ultisnips:
![image](https://user-images.githubusercontent.com/42984254/83340423-87362e80-a2a5-11ea-8630-c353cacfc339.png)

Completion sometimes seems to work but I do not think always (snippets especially had issues not working altogether when this error occurs).

### Expected behaviour
Completion and Snippets from sumneko_lua should not error out.

---
I originally posted about this error in completion-nvim and the author said the error was on neovim's end.

**Comment by tjdevries** [comment]
If it happens again, can you paste us the output text you get in the error message? It'd be helpful to have the text as text, rather than in the picture.

**Comment by sumneko** [comment]
I have used a more professional JSON library, which should not happen again.
See https://github.com/sumneko/lua-language-server/commit/675ba56e9d39711cf0653ccfa48423e4523baebe.

**Comment by tjdevries** [comment]
Going to close since it appears this is fixed upstream.

Thanks @sumneko  ( love the server btw. I use it daily :smile: )
