### ISSUE TITLE
Improving the built-in language support

### ISSUE THREAD

**Issue by WhyNotHugo** [neovim/neovim#12402]
neovim ships syntax highlight support for a lot of languages out of the box.

From what I see, most of these are the ones shipped upstream by Vim.

However, for a great deal of languages, there's a lot of better community-maintained version (I don't mean to criticise though; I don't think it makes sense for neovim devs to actually try to maintain plugins for every single language out there, it's just too much work!).

[vim-polyglot](https://github.com/sheerun/vim-polyglot) has even become a central repository for these (and a single package to pull them all at once).

I'd like to propose that neovim includes many (all?) of these out of the box. For example, [vim-xml](https://github.com/amadeus/vim-xml/) is basically what's bundled with Vim plus a few improvements. The [python](https://github.com/vim-python/python-syntax) has a lot of improvements too. The list goes on.

Rationale:

- It seems that there's some duplicate effort going on: work goes on upstream, but work goes on for the community-maintained language support.
- If `neovim` is to ship support for something, it should be the best available. I would also understand **not** shipping language support and requiring that to be installed separately (at least there would be only one obvious/best choice).
- It's odd to ship certain functionality, but also have a more heavily maintained plugin that **does the same thing**.
- Allow delegating per-language plugins to the community -- people out there are already doing it, it would make sense to bring that closer to neovim.

For the ones I've checked, there seems to be no licensing conflict either.

---

I thought a bit about trying to actually _address_ this before proposing the change, but there are various approaches, and I'm not sure which one would be best:

- Just copy in the syntax files from the community repositories?
  - Keeping in sync might be non-trivial, but this doesn't dramatically change neovim. And there'd be an immediate improvement for language syntax support.
- Use submodules to pull these in, so as to facilitate syncing these?
  - Also delegates their maintenance to the community in a way.
  - Easier to keep in sync; just update the revision to which the submodule points.

For the record, I'd like to address this myself, but I want to align and understand if it would be acceptable first or not.

**Comment by glacambre** [comment]
On 2020-05-30 15:16, Hugo Barrera wrote:
> Allow delegating per-language plugins to the community -- people out 
> there are already doing it, it would make sense to bring that closer to 
> neovim.

This is actually what Neovim already does. Neovim doesn't maintain 
runtime files, instead Vim's runtimes files are used. This means that if 
you want changes to be made in the runtime files (such as adding new 
syntax files), you have to ask this to Vim's maintainers.

And in fact, this is also what Vim does: if you want one of Vim's 
runtime files to change, you have to ask the maintainer of the runtime 
file to send the changes to Vim (this is described here: 
https://github.com/vim/vim/blob/master/CONTRIBUTING.md#syntax-indent-and-other-runtime-files).

**Comment by chrisbra** [comment]
> For example, vim-xml is basically what's bundled with Vim plus a few improvements.

For what it's worth: Those changes are included in https://github.com/chrisbra/vim-xml-runtime/ which gets included by Vim.

**Comment by WhyNotHugo** [comment]
Oh, it's mostly the Python one that caught my eyes as [substantially different](https://github.com/vim-python/python-syntax).

For other filestypes not included with neovim then, I guess the right think would be to push them into Vim itself first?

**Comment by teto** [comment]
I dont think we will proceed with this, the idea is to get less vimscript rather than more with things like treesitter. Likewise, I doubt we have the manpower to track runtime changes faster than vim does. Out of sync runtime is not an issue, it's easy enough to install the runtime as a plugin if you want the latest version. The problem is more about missing filetypes in vim, I would like to see more in them (nix, i3 config etc) but I don't know why they are missing. I suspect vim can't endorse filetypes if maintainers don't request it and are fine working out of tree ? or is there a threshold on the number of users ?

**Comment by WhyNotHugo** [comment]
Agreed, I'll try to push this more on the Vim side. Thanks!
