### ISSUE TITLE
LSP (tsserver): paste does not re-trigger diagnostics

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#12408]
- `nvim --version`: NVIM v0.5.0-537-g4b8724828 (master)

### Steps to reproduce using `nvim -u NORC`

0) Install tsserver (e.g. `npm install typescript`) and create a `package.json` file
1) Install nvim-lsp and make your init.ivm load tsserver (e.g. `:lua require("nvim_lsp").tsserver.setup{ on_attach = setup_lsp_settings }`).
2) Run nvim (e.g. `nvim file.ts`) and append the following content:

```typescript
type T = {
        T1: boolean,
        T2: boolean,
};

const V : T = {
        T2: false,
        T1: true,
};
```

Tsserver should be happy with this file. Place your cursor on the `T2: false` line. Press `dd` to delete the line. Tsserver should complain that `T2` is missing. Press `p` to paste the line you just deleted under `T1`.

### Actual behaviour

Tsserver still complains that `T2` is missing.

### Expected behaviour

Tsserver should not complain that `T2` is missing.

### Additional notes

Deleting whitespace is enough to trigger diagnostics and make the diagnostics disappear.

**Comment by mjlbach** [comment]
@glacambre Pretty sure this is fixed?

https://user-images.githubusercontent.com/13316262/110974960-01571180-8314-11eb-8e84-9dccbdd09507.mov

**Comment by glacambre** [comment]
@mjlbach Indeed it is, thanks for the update! (And maybe the fix? ;) )

**Comment by mjlbach** [comment]
> (And maybe the fix? ;) )

Honestly I can't remember what we would have done that would have fixed this haha 

Glad it works!
