### ISSUE TITLE
ERROR: shada file is not readable

### ISSUE THREAD

**Issue by sktrinh12** [neovim/neovim#12407]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: mac osx High Sierra 10.13.6
- Terminal name/version: Alpine Linux/3.11.6
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```
I am trying to containerize neovim with pre-installed plugins. Neovim opens, but I get this error when I check the health. I tried searching the existing issues, but there was no solution.  Here is the github repo: 
[https://github.com/sktrinh12/neovim_docker](github)
```
apk --no-cache --update add neovim neovim-doc

pip3 install --user pynvim \

sudo -u neovim python3 -m venv "${ENV_DIR}/${NVIM_PROVIDER_PYLIB}" \
	&& "${ENV_DIR}/${NVIM_PROVIDER_PYLIB}/bin/pip" install neovim
```
### Actual behaviour
:checkhealth gives me this error:

```
ERROR: shada file is not readable
/home/neovim/.local/share/nvim/shada/main.shada
```
When i ran `nvim -u NORC` it gave me some strange character output; but it cleared the error in :healthcheck. Not sure how that is related. But on a fresh start, the error is still there.

### Expected behaviour

no errors

**Comment by teto** [comment]
Feels more like an issue with your setup: does folder exist /home/neovim/.local/share/nvim/shada ? what does the shada file look like ? if you move it away does it still error out ?

**Comment by xuoutput** [comment]
root user?

**Comment by justinmk** [comment]
Does the user that the nvim process is running under have permissions to read/write `/home/neovim/.local/share/nvim/shada/main.shada` ?
