### ISSUE TITLE
[LSP] Statusline adapted from help doc code snippet causes high CPU usage

### ISSUE THREAD

**Issue by beardedsakimonkey** [neovim/neovim#12406]
- `nvim --version`:NVIM v0.5.0-nightly-1-gb8e2cd4f6
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: macOS Catalina 10.15.4
- Terminal name/version: alacritty 0.4.2 (f68de37)
- `$TERM`: tmux-256color

This issue might just be me not understanding how to use the statusline snippet from `:h vim.lsp.util.buf_diagnostics_count()` -- if that's the case, feel free to close this.

When I copied that snippet into my `vimrc` (or in `after/ftplugin/...`), it seems to not update properly: it would display "off" even when `:lua print(vim.inspect(vim.lsp.buf_get_clients()))` was non-empty. This seems expected as `LspStatus()` is only called once.  In an effor to fix this, I made the following change:

```diff
function! LspStatus() abort
  let sl = ''
  if luaeval('vim.lsp.buf.server_ready()')
    let sl.='%#MyStatuslineLSP#E:'
    let sl.='%#MyStatuslineLSPErrors#%{luaeval("vim.lsp.util.buf_diagnostics_count(\"Error\")")}'
    let sl.='%#MyStatuslineLSP# W:'
    let sl.='%#MyStatuslineLSPWarnings#%{luaeval("vim.lsp.util.buf_diagnostics_count(\"Warning\")")}'
  else
    let sl.='%#MyStatuslineLSPErrors#off'
  endif
  return sl
endfunction
-let &l:statusline = '%#MyStatuslineLSP#LSP '.LspStatus()
+set statusline=%!LspStatus()
```

However this causes the issue with high CPU usage described below.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

# install any language server, e.g. rust-analyzer
# then open a buffer with the filetype for that language, and source this:

let g:mycount = 0
function! LspStatus() abort
        let sl = ''
        call luaeval('vim.lsp.buf.server_ready()')
        let g:mycount = g:mycount + 1
        return g:mycount .. '%{luaeval("vim.lsp.util.buf_diagnostics_count(\"Error\")")}'
endfunction
set statusline=%!LspStatus()

# then source this (adjusting `cmd` and `root_dir` as appropriate)
lua vim.lsp.buf_attach_client(vim.api.nvim_get_current_buf(), vim.lsp.start_client({ cmd = { "rust-analyzer" }, root_dir = "/" }))
```

### Actual behaviour
the counter in the statusline incrememnts super fast even while nvim is idle, and CPU usage stays at 80-90%

### Expected behaviour
the counter doesn't increment while idle, and CPU usage is low

/cc @tjdevries

**Comment by haorenW1025** [comment]
I've found out that it's the `vim.lsp.buf.server_ready()` causing the high cpu issues. I've fixed by with changing
`if luaeval('vim.lsp.buf.server_ready()')`
to 
`if luaeval('#vim.lsp.buf_get_clients(0) ~= 0')`

**Comment by tjdevries** [comment]
ha, `server_ready()` sends a request to the language server... so it's sending requests from every buffer on every statusline redraw. That is not a very good idea. We should change the doc to reflect the way @haorenW1025 has mentioned.

**Comment by beardedsakimonkey** [comment]
i agree that sending requests from the statusline is not a great suggestion to have in the docs.  i think there are a couple issues with @haorenW1025's suggestion:

1) that `luaeval` will be evaluated in the context of the current buffer/window, which means if you have a split with window A with a buffer that has an LSP client attached, and window B with a buffer that has no LSP client attached, `luaeval('#vim.lsp.buf_get_clients(0) ~= 0')` will evaluate to true for both windows.
2) using the length operator on the `vim.lsp.client` object isn't a reliable way to check whether it contains entries, since you can easily get into a state where the `client` object has holes.

While trying to make an updated statusline that evaluates everything in the context of the correct buffer, I ran into an interesting gotcha:  calling `vim.lsp.util.buf_diagnostics_count` can cause the statusline to error out when initially opening nvim to a file with an LSP setup.  (By "error out", I mean that the statusline would revert to the default one, and `set stl?` would display `statusline=`) However,  I could avoid this by guarding against an empty `vim.lsp.util.diagnostics_by_buf`:
```diff
function! MyStatusLine()
-   return "%{luaeval('not vim.tbl_isempty(vim.lsp.buf_get_clients(0))
+   return "%{luaeval('(not vim.tbl_isempty(vim.lsp.buf_get_clients(0)) and not vim.tbl_isempty(vim.lsp.util.diagnostics_by_buf))
        \ and [[E:]] .. vim.lsp.util.buf_diagnostics_count([[Error]]) .. [[ W:]] .. vim.lsp.util.buf_diagnostics_count([[Warning]])
        \ or [[off]]')}"
endfunction
```

I'm not sure if this issue is specific to my setup, buf if not, it might be worth adding this check to `vim.lsp.util.buf_diagnostics_count` to take this burden off statusline authors.

**Comment by ndreas** [comment]
I discovered something similar a while back and solved it by adding a hook for `LspDiagnosticsChanged` and writing the diagnostics counts to a buffer variable and using that in the status line instead. I looked at `vim.lsp.util.buf_diagnostics_count` and saw no reason to do the sum every time I ask for the count.

One alternative solution for this would be to have `vim.lsp` set buffer variables instead for things that rarely change, but that might not be how you want the lsp library to work :)

**Comment by tjdevries** [comment]
Does latest commit fix this?

**Comment by beardedsakimonkey** [comment]
@tjdevries the CPU issue seems to be fixed.  However the snippet in the docs suffers from one of the issues I described earlier:

> that luaeval will be evaluated in the context of the current buffer/window, which means if you have a split with window A with a buffer that has an LSP client attached, and window B with a buffer that has no LSP client attached, luaeval('#vim.lsp.buf_get_clients(0) ~= 0') will evaluate to true for both windows or false for both windows, depending on which window the cursor is in.

To reproduce: open a window with some file that has LSP enabled.  Then open a split window with a file that doesn't have LSP enabled. Move focus between the two windows and observe their statuslines.

Interestingly, this issue also seems like it should exist in the `lsp-status` plugin, as they recommend something similar [in their readme](https://github.com/nvim-lua/lsp-status.nvim#all-together-now).  cc @wbthomason have you experienced this issue?

**Comment by wbthomason** [comment]
@beardedsakimonkey: I don't think so, no. When I try to reproduce the issue with one split with a Python file with MS PYLS attached and another split with a plain .txt file, the statuslines look correct - the statusline for the .txt file has no LSP component, and the statusline for the Python file has an LSP component which updates correctly for new diagnostics.

This is on bd5f0e9. I am using a very similar setup to what you describe in your initial report (specifically https://github.com/wbthomason/dotfiles/blob/linux/neovim/.config/nvim/plugin/statusline.vim#L72 and https://github.com/wbthomason/dotfiles/blob/70a67d7e4311c75f35c11810a8252df068dc41f3/neovim/.config/nvim/autoload/statusline.vim#L109-L130); I'm not sure why you see this difference and I don't (assuming that I correctly understand what you expected to happen).

**Comment by tjdevries** [comment]
Can you paste exactly how you're calling it @beardedsakimonkey ? Just wondering.

**Comment by beardedsakimonkey** [comment]
@wbthomason thanks for clarifying.  From your dotfiles it seems like you're correctly calling those functions using `%{}` evalution (as opposed to calling the function from the lsp-status readme as `set statusline=%!LspStatus()`), so I guess i just misinterpreted the readme.

@tjdevries 
```
fun! MyStatusLineNeovim() abort
  let sl = ''
  if luaeval('not vim.tbl_isempty(vim.lsp.buf_get_clients(0))')
    let sl.='%#MyStatuslineLSP#E:'
    let sl.='%#MyStatuslineLSPErrors#%{luaeval("vim.lsp.util.buf_diagnostics_count([[Error]])")}'
    let sl.='%#MyStatuslineLSP# W:'
    let sl.='%#MyStatuslineLSPWarnings#%{luaeval("vim.lsp.util.buf_diagnostics_count([[Warning]])")}'
  else
    let sl.='%#MyStatuslineLSPErrors#off'
  endif
  return sl
endf
set statusline=%!MyStatusLineNeovim()
```

**Comment by beardedsakimonkey** [comment]
closing as the suggestion in the doc no longer causes high CPU usage for me.
