### ISSUE TITLE
:checkhealth shows weird info for ##terminal

### ISSUE THREAD

**Issue by ludwj61** [neovim/neovim#12404]
- `nvim --version`: v0.5.0-535-g7d8dc4c33
- Operating system/version: Ubuntu through windows 10 WSL2
- Terminal name/version: Alacritty most recent pre-release
- `$TERM`: xterm-256color, tmux-256color

### Actual behaviour
Although true colors seem to work fine both in and outside of tmux, :checkhealth shows some nonsense for the $TERM used both in and outside of tmux as shown in this screen:

![image](https://user-images.githubusercontent.com/42984254/83339304-8a77ed00-a29a-11ea-85da-916d2d6dd144.png)

### Expected behaviour
Readable terminal info.

Sorry if this is intended behavior, I tried to find info on it but I couldn't.

**Comment by glacambre** [comment]
On 2020-05-30 23:31, Jackson Ludwig wrote:
> Although true colors seem to work fine both in and outside of tmux, 
> :checkhealth shows some nonsense for the $TERM used both in and outside 
> of tmux as shown in this screen:

Does `echo $TERM` print something else than `tmux-256color` when ran 
outside of tmux? Neovim just inherits this variable from its 
environment, so it's probably not its fault if $TERM is wrong.

**Comment by ludwj61** [comment]
echo $TERM prints "xterm-256color" outside of tmux.

**Comment by glacambre** [comment]
On 2020-05-31 06:11, Jackson Ludwig wrote:
> echo $TERM prints "xterm-256color" outside of tmux.

Huh, that's weird. Does `:echo $TERM` in neovim outside of tmux also 
print `tmux-256color`, or is `:checkhealth` the only command being 
confused about $TERM?

**Comment by ludwj61** [comment]
:echo $TERM gives "xterm-256color"/"tmux-256color" inside/outside tmux. So it does look like :checkhealth is the thing that's confused.

**Comment by erw7** [comment]
@ludwj61  What are you referring to when you say "shows some nonsense for the $TERM"? Does `$TERM` have `tmux-256color` outside of tmux? Or does it mean "INFO: key_backspace ..." etc?

If you're talking about "INFO:key_backspace ...", don't worry about it because it's INFO. It's probably related to the following FAQ, so it may be unnecessary now.

https://github.com/neovim/neovim/wiki/FAQ#my-ctrl-h-mapping-doesnt-work

**Comment by ludwj61** [comment]
Yep that's what I meant, thanks. Guess it wasn't an issue then.
