### ISSUE TITLE
nvim-lsp not sending full code to rust-analyzer

### ISSUE THREAD

**Issue by sbromberger** [neovim/neovim#12414]
- `nvim --version`: `NVIM v0.5.0-532-g2ca8f02a6`
- `vim -u DEFAULTS` (version: ) behaves differently? no.
- Operating system/version: Ubuntu 20.04
- Terminal name/version: blink app, via mosh
- `$TERM`: tmux-256color-italic

### Steps to reproduce using `nvim -u NORC`
Cannot reproduce using NORC because it relies on nvim-lsp and rust-analyzer.

1) create a simple rust file after `cargo init --bin`: https://gist.github.com/sbromberger/f796385f05096c17408b28af02492578 and save it
2) using rust analyzer config:
```
lua << EOF
  local nvim_lsp = require'nvim_lsp'
  local on_attach = function(_, bufnr)
    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
    require'diagnostic'.on_attach()
    require'completion'.on_attach()
  end
  nvim_lsp.rust_analyzer.setup{
    on_attach=on_attach;
  }
EOF
```
edit the file. hit `:w` to write the file.

Spurious error complaining about missing right curly brace.

### Expected behaviour
No error.

Video demonstration of error: https://asciinema.org/a/O97Y5icC8HfdETZ37CWgZzURv

LSP log trace: https://gist.github.com/sbromberger/909ce6d5723bb0d0d8b9e3e7424efaec

Related issue: https://github.com/rust-analyzer/rust-analyzer/issues/4630

**Comment by lithammer** [comment]
The gist is gone. What if you disable `completion` and `diagnostic`?

**Comment by sbromberger** [comment]
Sorry - it was a bad copy/paste. I've updated the issue and confirmed that the link works now.

I'll try disabling completion and diagnostic.

**Comment by sbromberger** [comment]
pinging on this. It's still an issue.

**Comment by glacambre** [comment]
On 2020-06-09 00:33, Seth Bromberger wrote:
> pinging on this. It's still an issue, even with a newly-compiled neovim.

If you want to debug this yourself you can sprinkle `print()` commands 
in runtime/lua/vim/lsp.lua and runtime/lua/vim/lsp/*.lua to follow the 
calls that are made for LSP requests and figure out what's happening. 
This is what I did the few times I had issues with the LSP client.

**Comment by sbromberger** [comment]
I think we've determined that the problem is that the LSP client is not sending the terminating close curly brace.

**Comment by glacambre** [comment]
On 2020-06-09 05:54, Seth Bromberger wrote:
> I think we've determined that the problem is that the LSP client is not 
> sending the terminating close curly brace.

Yes, but we don't know why (or at least this is not obvious to me in 
this issue).

**Comment by sbromberger** [comment]
OK, that's a reason to start trying to debug this :) First I have to learn some lua.

**Comment by h-michael** [comment]
@sbromberger Sorry for late reply.
You just did a cursor move and a ":w", but the log shows a lot of "textDocument/didChange". I'm curious about the it.
Are there any other settings or plugins other than the ones you have suggested?

**Comment by sbromberger** [comment]
I wonder if there's some sort of a race condition between rustfmt and rust-analyzer here.

**Comment by h-michael** [comment]
I think this is the cause.
https://github.com/rust-lang/rust.vim/blob/0f37349df535b61ba8c14cc2ae3ec447332ff311/autoload/rustfmt.vim#L160

**Comment by sbromberger** [comment]
(I don't know enough about Lua or the software to understand why.)

**Comment by h-michael** [comment]
@sbromberger I've fixed this.

**Comment by sbromberger** [comment]
@h-michael that's so awesome. Thank you.

**Comment by sbromberger** [comment]
Confirm this is working as expected. Thanks again.

**Comment by sbromberger** [comment]
Actually, sorry. It's not working:

https://asciinema.org/a/owxuCs9NaexRHDQBWqjanRYkv

**Comment by h-michael** [comment]
@sbromberger Please take a moment to check it again.

**Comment by sbromberger** [comment]
Should I update, or just check again?

**Comment by sbromberger** [comment]
I updated and checked again, and it appears to be fixed. Thanks.
