### ISSUE TITLE
Key mapping failed for terminal mode when output filled up the whole screen

### ISSUE THREAD

**Issue by coiby** [neovim/neovim#12419]
- `nvim --version`:

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- `vim -u DEFAULTS` (version: ) behaves differently?
  Yes
- Operating system/version: Manjaro Linux 20.0.1
- Terminal name/version: xfce4-terminal 0.8.9.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
1. Enable line numbering and map `Alt+t` to open a terminal in a new tab
```
set nu
tnoremap <M-t> <c-\><c-n> \| :tabnew +terminal<cr>
```
2. Open the nvim's terminal
3. Switch to terminal insert mode by typing `i`
4. Try to fill-up the whole screen, for example, run the following command
```bash
for i in `seq 1 200`; do echo $i; done
```
5. type `Alt+r`

### Actual behaviour

nvim return to normal mode but no terminal would be open in a new tab unless I manually disable line numbering or clear the screen by `Ctrl+l`.

### Expected behaviour

Open a terminal in a new tab.

**Comment by coiby** [comment]
Btw `<Cmd>` doesn't suffer from this issue,
```bash
set nu
tnoremap <M-t> <Cmd>tabnew +terminal<cr>
```

**Comment by kipcd** [comment]
I have the same issue in terminal insert mode with my custom `Alt-T` combination to open a new terminal in a split. It's working when the screen is not full and stops working when the output isn't fitting the screen.
```    
tnoremap <Esc> <C-\><C-n>   " switch from terminal mode to normal mode
tnoremap <A-[> <Esc>        " remap Esc for terminal
tnoremap <M-t> <C-\><C-n> :split +terminal<CR>
```

Ubuntu 19.10
NVIM v0.3.8 and v0.4.3
Terminals: Alacritty, Terminator, gnome-terminal
$TERM: xterm-256color

xmodmap:
```
shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x9)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```
Interesting though that my custom `Alt+W` combination to switch between splits is still working

**Comment by zeertzjq** [comment]
Remove the space before the colon.

This is because you have a space before the colon, and a space is a motion command. In the last line of a buffer, this motion fails, and the following of the mapping is not executed. See `:h map-error`.
