### ISSUE TITLE
LspDiagnosticHint doesn't seem to be used for virtual text and hover

### ISSUE THREAD

**Issue by dutchgecko** [neovim/neovim#12426]
- `nvim --version`: 
```
NVIM v0.5.0-539-g91e41c857
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/gecko/build/neovim/build/config -I/home/gecko/build/neovim/src -I/home/gecko/build/neovim/.deps/usr/include -I/usr/include -I/home/gecko/build/neovim/build/src/nvim/auto -I/home/gecko/build/neovim/build/include
Compiled by gecko@mortred

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
  N/A

- Operating system/version:
  Ubuntu 20.04 running under WSL 1 on Windows 10 build 18363
- Terminal name/version:
  mintty 3.1.4
- `$TERM`:
  xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Difficult to do from NORC so I've made a minimal reproducer config here: https://github.com/dutchgecko/nvim-config/tree/reproduce_minimal (branch `reproduce_minimal`)

2. `:LspInstall sumneko_lua`

3. Open a new lua file and create an unused variable:

```lua
local foo
```

4. Place cursor on that line and execute 

  `:lua vim.lsp.util.show_line_diagnostics()`

### Actual behaviour

Diagnostic virtual text of type "Hint" is shown with white text without the use of the `LspDiagnosticHint` highlight group. Additionally, the diagnostic text in the Hover window is also displayed in white.

### Expected behaviour

Diagnostic text of type "Hint" to be shown in grey according to the `LspDiagnosticHint` highlight group. Additionally, the diagnostic text in the Hover window should also be displayed in grey.

![image](https://user-images.githubusercontent.com/2513484/83526641-05354800-a4e7-11ea-944c-b6c70f434962.png)

![image](https://user-images.githubusercontent.com/2513484/83526984-783ebe80-a4e7-11ea-94aa-c935aeb8255e.png)

![image](https://user-images.githubusercontent.com/2513484/83527003-812f9000-a4e7-11ea-805d-fe7e222c8677.png)

**Comment by beardedsakimonkey** [comment]
it should be `LspDiagnosticsHint` (plural diagnostic*s*) right?

**Comment by dutchgecko** [comment]
You are right. This seems to be a bug in the colorscheme. Thanks!
