### ISSUE TITLE
latest master breaks nvim-lsp

### ISSUE THREAD

**Issue by sbromberger** [neovim/neovim#12422]
- `nvim --version`:
```

NVIM v0.5.0-539-g91e41c857
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gn
u99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_
GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/seth/build/neovim/build/config -I/
home/seth/build/neovim/src -I/home/seth/build/neovim/.deps/usr/include -I/usr/include -I/home/seth/build/neovim/build/src/nvim/auto -I/home/seth/build
/neovim/build/include
Compiled by seth@hydrogen

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/seth/.local/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: Ubuntu 20.04
### Steps to reproduce using `nvim -u NORC`
can't reproduce using NORC. Here's a minimal init.vim:
```
call plug#begin()
Plug 'neovim/nvim-lsp'
call plug#end()
```

### Actual behaviour
output: https://gist.github.com/7e1909f6e7fda2d13014866844c67c1a

### Expected behaviour
no errors.

**Comment by sbromberger** [comment]
note: nvim-lsp hasn't been updated in 9 days; I know that neovim from 2 days ago was working fine. I believe that #12401 broke things but I guess I can do a bisect if you need me to.

**Comment by h-michael** [comment]
@sbromberger 
If you run this command, `ls /home/seth/.local/share/nvim/runtime/lua/vim/`, does `highlight.lua` exist?

**Comment by e-kwsm** [comment]
In the source directory of neovim, run `rm -rf build` and then reinstall neovim—that works for me.

**Comment by sbromberger** [comment]
@h-michael - there is no `highlight.lua` anywhere under `~/.local`.

**Comment by h-michael** [comment]
@sbromberger Could you do `make distclean && make CMAKE_BUILD_TYPE=RelWithDebInfo; make install`?
It will fix this issue, I think.

**Comment by sbromberger** [comment]
`rm -rf build` and a remake solved it. Thanks, @e-kwsm . I would have figured a `make clean` would've gotten me to the desired state, but apparently not.

**Comment by h-michael** [comment]
`CMakeCache` remains in `make clean`, so build settings are not changed.
If you need to change the build settings (for example, if added or deleted the runtime file), execute `make distclean`.

**Comment by sbromberger** [comment]
So, the issue here is not quite resolved, I don't think. Unless you have specific instructions to `make distclean` after updating, anyone else who builds from source using the same process I used will run into trouble.

**Comment by h-michael** [comment]
@sbromberger 
Could you please edit this to make it easier to understand?
https://github.com/neovim/neovim/wiki/Building-Neovim#building

**Comment by sbromberger** [comment]
I wouldn't know how to edit that to make it easier to understand. The bottom line for me is that `make clean && make` worked for months, and there was no warning whatsoever that the latest commit would require a `make distclean`. There was nothing in the PR that indicated that this was necessary, and `make distclean` isn't part of the "build from source" document except in a blurb that says "if you ever want to change `CMAKE_BUILD_TYPE`..." which doesn't apply to this situation.

I guess my recommendation would be this: either a) have `make distclean` be part of the build from source instructions, b) place a notification somewhere in the PR that a `distclean` is required, and/or c) edit the build-from-source instructions with something that says, "if you have trouble with neovim after a source update, make sure you do a `make distclean` and rebuild before  submitting an issue" or something to that effect.

**Comment by e-kwsm** [comment]
It is `git clean -xdf` to remove ALL the untracked files.

**Comment by clason** [comment]
@sbromberger `make distclean` is _always_ required when a new file is added (even to `runtime`); that happens infrequently, but it does happen. (This is not the first time in the last few months; it will likely happen again while LSP implementation is polished before the release of 0.5.0.)

I've added a sentence to the build documentation to point this out; let me know if this is not clear enough (also @h-michael).

**Comment by tjdevries** [comment]
This issue should probably be closed and a new one can be opened for discussing the build documentation, IMO. We can link back to here from there if we'd like.

**Comment by teto** [comment]
@sbromberger this is a rare occurence that a rebuild is needed. Anyone is welcome to fix it but a clean build works well enough (also a good habit when sthg strange appears).
