### ISSUE TITLE
vimls omnifunc throws attempt to compare nil with string

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#12431]
- `nvim --version`: `NVIM v0.5.0-60c581b`
- nvim-lsp version(commit hash): a7fdf268b1c51f6395900e437060728701aa8b77
- `:checkhealth` result
```
## Checking language server protocol configuration
  - INFO: vimls: configuration checked.
  - INFO: gopls: configuration checked.
  - INFO: tsserver: configuration checked.
```
- Operating system/version: macOS 10.15.5
- Terminal name/version: Terminal.app
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

Just `<C-x><C-o>` after installing vimls in a vim file.

Throws:

```
Error executing vim.schedule lua callback: ...vim/HEAD-60c581b/share/nvim/runtime/lua/vim/lsp/util.lua:267: attempt to compare nil with string
```

Originally filed at https://github.com/neovim/nvim-lsp/issues/261

**Comment by tjdevries** [comment]
Do you want to try and fix this @nhooyr or no? Most likely just requires checking if no results are returned or something like that and then quitting.

**Comment by nhooyr** [comment]
Oh I didn't even investigate yet. If it's that simple yea, feel free to assign!

**Comment by tjdevries** [comment]
Well I don't *know* that it's that simple :wink: but I think comparing `nil` to `string should really just be a simple fix of not comparing them and returning something sensible in it's place or similar.

**Comment by nhooyr** [comment]
Well fingers crossed then!

**Comment by mfussenegger** [comment]
https://github.com/mfussenegger/neovim/blob/0348549d776c392a2e75650a39e9976cc47f4b09/runtime/lua/vim/lsp/util.lua#L266-L269

probably has to be changed to something like this:

```lua
if items[1] and items[1].sortText then
    table.sort(items, function(a, b) return (a.sortText or '0') < (b.sortText or '0') end)
end
```
