### ISSUE TITLE
Throws error when lsp capability not found

### ISSUE THREAD

**Issue by c0r73x** [neovim/neovim#12443]
https://github.com/neovim/neovim/blob/6f4f38cd54693ca99c887756e6179cc0775377d0/runtime/lua/vim/lsp.lua#L515

Do we really need to throw an error here? Couldn't we just output it into the debug log? Seems that it makes the lsp client to stop responding for some reason. Atleast in my test cases.

**Comment by h-michael** [comment]
I don't think this code throws the error.
`unsupported_method` only display error messages to echo area and call `lsp.rpc_response_error`(And this method also don't throw the error)

**Comment by c0r73x** [comment]
The issue beeing that when this happends on `util.fancy_floating_markdown` it will not run the correct code afterwards, which in turn means that the floating window wont get the `close_preview_autocmd`.

If i comment out the line i mentioned it works as expected. With the line active i will get the error message and I will get floating buffers that never close everytime a floating window opens (if i run a language server that do not support all the requests).

**Comment by c0r73x** [comment]
Just a thought, but wouldn't it make more sense to put these messages in `checkhealth` rather than spamming messages?

**Comment by tjdevries** [comment]
Is this better now?

**Comment by c0r73x** [comment]
Much better! Thank you very much 😁👍

**Comment by c0r73x** [comment]
Seems like an update added this spam again.. But even worse this time... Every time i save a file now i get three or even more lines of 
`RPC[Error] code_name = MethodNotFound, message = "method textDocument/documentSymbol is not supported by any of the servers registered for the current buffer"`

as a non-error message... I understand that this is work in progress, but for me as a user these messages are totally unnecessary.. If you need them for debug output, please add a toggle for it at least so that ppl can actually use the features without getting spam like this.

**Comment by mjlbach** [comment]
Isn't this in the debug log?

**Comment by c0r73x** [comment]
Yes, in messages.. as echo output... It needs to be here because? In a log output i would understand it, but I use my message output for lots of stuff, seeing constant RPC error spam because a language server dont support a feature I dont use in these files is totally unnecessary imo.

**Comment by mjlbach** [comment]
You shouldn't be seeing that on every save, do you have some sort of custom autocommand? Which server is it?

**Comment by c0r73x** [comment]
I'm using tons of custom autocommands, but the reason for it I would guess is because i use diagnostics-language-server. Seems I get these messages from every file that uses it (and I use it ALOT). I've even tried to create a void function to throw showMessage and logMessage there but the messages still shows up.

**Comment by c0r73x** [comment]
I disabled all my lsp config and the message is gone, I guess i'm doing something wrong when setting up the lsp servers or something. Ty for the responses 👍

**Comment by c0r73x** [comment]
After doing some cleanup of my config i found the issue, apparantly the Vista plugin tries to use lsp methods even if the server reports it dont support it. By uninstalling Vista the RPC message is gone. 👍
