### ISSUE TITLE
[LSP] Hover window styling quirks, and suggested improvements.

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#12441]
Hello,

I have been experimenting with the latest Neovim nightly (545 June 3 2020), specifically LSP and hovering in comparison to my existing LSP client which is [LSC](https://github.com/natebosch/vim-lsc).

- Issue 1, hover window appears to be cutting off information if long lines are contained.

Here is Flutter API in Neovim LSP (not all content is displayed):

<img width="1272" alt="nvim-LSP-Dart" src="https://user-images.githubusercontent.com/11382509/83841638-95bc9400-a744-11ea-9485-a2960648b1fd.png">

And with LSC (notice no content is cutoff or weird wrapping):

<img width="1270" alt="LSC-Dart" src="https://user-images.githubusercontent.com/11382509/83841686-b1c03580-a744-11ea-8b7e-982fbf02df3e.png">

- Issue 2, the hover window is too small and can easily get lost.

Here is some JavaScript in Neovim LSP (very hard to see the floating window, very small and thin):

<img width="964" alt="nvim-LSP-JS" src="https://user-images.githubusercontent.com/11382509/83841821-efbd5980-a744-11ea-86ad-ab58f0d46096.png">

And here is the same in LSC, notice the whitespace padding to make the hover window easy to see and read:

<img width="975" alt="LSC-JS" src="https://user-images.githubusercontent.com/11382509/83841879-0e235500-a745-11ea-858a-0da1fe22085f.png">
 
- Issue 3, full width hover window looks bulky and overwhelming

Here is a large Ruby hover, takes up nearly the whole screen and has a wrapped line divider:

<img width="1276" alt="nvim-LSP-Ruby" src="https://user-images.githubusercontent.com/11382509/83842045-74a87300-a745-11ea-8313-5b236c6b0aef.png">

And in LSC plugin, hover windows can never exceed 90% which I find more aesthetically pleasing:

<img width="1270" alt="LSC-Ruby" src="https://user-images.githubusercontent.com/11382509/83842146-9c97d680-a745-11ea-9cfb-4650bdb825c8.png">

I am not suggesting the LSC look is the correct look that should be emulated, however, some of the way that LSC styles its hover window results in less annoyances when compared with Neovim native LSP.

Best regards.

**Comment by glacambre** [comment]
On 2020-06-05 08:07, Dennis B wrote:
> Hello,
> 
> I have been experimenting with the latest Neovim nightly (545 June 3 
> 2020), specifically LSP and hovering in comparison to my existing LSP 
> client which is LSC <https://github.com/natebosch/vim-lsc>.
> 
>   * Issue 1, hover window appears to be cutting off information if long
>     lines are contained.
> 

The empty lines are pretty weird indeed. A workaround is to repeat the 
keybinding you pressed in order to make the popup appear, your cursor 
will be moved to the floating window and will let you scroll down. But 
it'd be nicer to not have to do that.

> 
>   * Issue 2, the hover window is too small and can easily get lost.
> 

I think this is more a colorscheme issue than a padding issue. Your 
background colors are very similar and thus hard to distinguish. If your 
floating window had a white background this wouldn't be an issue and you 
would be able to save 2 columns and 2 lines of context, which is 
valuable in my opinion.

> 
>   * Issue 3, full width hover window looks bulky and overwhelming
> 

I agree, capping the window's width to 90% looks nicer.

**Comment by bluz71** [comment]
The colorscheme is defining a popup colour which has enough contrast in my opinion since I have no issues when using it with completions, however the floating window is rendering the hover content with language styling which makes it very easy to be camouflaged.

Many colour schemes will have similar contrast between the background colour and popup colour as seen in the above image.

White popup window for a dark colour scheme is not standard practice.

**Comment by clason** [comment]
Can you try with latest master? There were some changes on float handling and especially width and height computation for preview and hover.

(The functions also accept an optional `opts.width` argument that you can set to force 90% winwidth; this could me made a default, but I'm not sure everyone would want that.)

**Comment by bluz71** [comment]
Which version?
I was using 545, which was the latest as of a couple hours ago.

**Comment by clason** [comment]
I mean latest (547, I think; the changes were mostly in https://github.com/neovim/neovim/commit/b7f3f11049c6847a2b0c4bbd89e8339036e00da6)

**Comment by bluz71** [comment]
Ok, will do so when it becomes available as a nightly.

**Comment by bluz71** [comment]
Looks like a lot good stuff contained in that commit, including padding.

May solve most issues, to-be-determined.

**Comment by clason** [comment]
You can also just copy the changed runtime files (`util.lua` and `callbacks.lua`) from master to your installation (assuming you don't want to build from source, which should be easy, unless you are on Windows).

> Looks like a lot good stuff contained in that commit, including padding.

I certainly hope so :) I'd be interested to hear how this impacts your hover -- the underlying function `fancy_floating_markdown` does some interesting things to turn the fenced code blocks into syntax highlighted code, which I didn't touch but can't test.

If there's strong interest in having vertical padding as well as horizontal, I can add that as a `pad_top`/`pad_bottom` option, although I wouldn't default it to 1.

**Comment by bluz71** [comment]
Strong yes to padding all around, vertical is even more important to me than horizontal. I would like one layer of padding all around the hover text.

The default would be up to you guys, all I want is a button I can flick to get all round padding like the image in the first post.

Side note, how to define padding? Quick example would be nice, I don’t know how to lua that much.

**Comment by glacambre** [comment]
On 2020-06-05 12:37, Dennis B wrote:
> The colorscheme is defining a popup colour which has enough contrast in 
> my opinion since I have no issues when using it with completions,

Completion popups are not the same thing as a hover window, you can't 
expect the style of one to always work for the other. Neovim defaults to 
the completion popup's colors because it is the least bad default there 
could be in the absence of support from colorschemes, but it's still a 
pretty bad default that can and should be overridden by colorschemes IMO.

> 
> White popup window for a dark colour scheme is not standard practice.
> 

"Standardness" is not a good goal to aim for IMO. I'd rather aim for a 
combination of prettiness and usefulness.

**Comment by clason** [comment]
> The default would be up to you guys, all I want is a button I can flick to get all round padding like the image in the first post.

Look at the `M['textDocument/hover']` function in `callbacks.lua`. As you can see, horizontal padding by 1 is the default; once somebody adds a PR to include vertical padding, you'd just add `pad.top = 1; pad.bottom = 1`. Check the documentation in the nvim-lsp repo to see how to set custom callbacks.

**Comment by bluz71** [comment]
Yes, pad.top and pad.bottom seem like an omission that needs correcting. It would solve my issue 2.

I will report my findings tomorrow with respect to the latest master.

**Comment by clason** [comment]
> Yes, pad.top and pad.bottom seem like an omission that needs correcting. It would solve my issue 2.

That's putting it a bit strongly -- after all, you're the first to request such a thing. But I'm on lunch break anyway, so I'll see if I can add it quickly.

**Comment by bluz71** [comment]
Most Neovim users are running stable 0.4 via their system package manager, not 0.5 LSP.

**Comment by bluz71** [comment]
In HTML land padding means padding all round, so that is how my brain works, I do a bit of web development where padding has a meaning. No offence intended.

I am appreciative about the current and future enhancements. Vertical padding will be nice.
