### ISSUE TITLE
LSP: handling multiple clients that publishDiagnostics

### ISSUE THREAD

**Issue by steelsojka** [neovim/neovim#12457]
- `nvim --version`: nightly
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Ubuntu
- Terminal name/version: Kitty
- `$TERM`:

When multiple clients publishDiagnostics for the same buffer, one overwrites the diagnostics of the other. Looking at the lsp callback for `publishDiagnostics` it looks like this clears all the diagnostics. Is allowing multiple clients to publish diagnostics a planned feature?

EDIT example:

For example, a tsserver and an angular-language-server both operate on typescript files but publish different diagnostic messages.

**Comment by mfussenegger** [comment]
There's a PR wip/pending for this: https://github.com/neovim/neovim/pull/12244

**Comment by steelsojka** [comment]
@mfussenegger  Awesome. I searched the issues but didn't search the PR's. Thank you. I'll close this.
