### ISSUE TITLE
NFA regex engine: Incorrect match for \u0130 (Latin Capital I with Dot Above) in collection

### ISSUE THREAD

**Issue by tmccombs** [neovim/neovim#12456]
- `nvim --version`: 
```
  NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? 
    N/A vim doesn't have NFA regex engine
- Operating system/version:
  Linux (archlinux) 5.6.15-arch1-1
- Terminal name/version:
alacritty 0.4.3
- `$TERM`:
alacritty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
iI i<esc> " create file content with "I i"
/\%#=2\c[\u0130]<cr> " search using NFA engine, case insensitive for U+130 in collection
/\%#=1\c[\u0130]<cr> " search using legacy engine, case insensitive in collection
/\%#=2\c\u0130<cr> " search using NFA engine case insensitive not in collection
/\%#=2[\u0130]<cr> " search using NFA engine case sensitive in collection
```

### Actual behavior
Both the capital and lower case i are matched when U+0130 is inside a collection, the NFA engine is used, and the search is case insensitive. In the three other searches in the reproduction steps neither the lower or upper case `I` is matched by the pattern.

### Expected behaviour
Apparantly, the lower case form of "İ" is "i", so in the first search, it makes sense that the "i" is matched (because case insensitivity), but the upper case "I" shouldn't  be matched. My guess is it is doing converting the "I" to a lowercase "i" and doing the comparison with that. Because of issues like this, converting to upper case anc comparing uppercase is more correct, although it still may not be correct for some languages.  (Also note that even if U+0130 is included in a range, such as `[\u012f-\u0131]`, this behavior is exhibited).

Also, `/\c\u0130` _should_ match the lower case i. Or at the very least it should behave the same as `\c[\u0130]`.

**Comment by jamessan** [comment]
>     * `vim -u DEFAULTS` (version: ) behaves differently?
>       N/A vim doesn't have NFA regex engine

Yes, it does.

What are your locale settings?

**Comment by jamessan** [comment]
> Also, `/\c\u0130` _should_ match the lower case i

No, it shouldn't.  `\u` is a special atom that means "uppercase character".  You would need to use `/\c\%u0130` here.

**Comment by jamessan** [comment]
Cc @chrisbra @brammool

**Comment by tmccombs** [comment]
> No, it shouldn't. \u is a special atom that means "uppercase character". You would need to use /\c\%u0130 here.

oh, oops. Well, `/c\%u0130` doesn't match "i" either.

> Yes, it does.

Oh, hmm. I don't know how I missed. that. It looks like upstream has the same behaviour. Should I file this upstream?

**Comment by brammool** [comment]
This is a strange character, I believe it is Turkish.  The upper case form is 0x130, the lower case is ordinary "i".  So you can convert the upper case to lower case, but not back, then it turns into "I".
Therefore the normal "ignore case" mechanism doesn't work.  One can argue both that it should match and that it shouldn't.  In cases like this I rather not make a change.

**Comment by tmccombs** [comment]
@brammool, it's totally a weird case. As an English speaker, I don't have a strong opinion on whether U+0130 should match lowercase "i" or not. However, it does definitely seem wrong that it matches uppercase "I" as well. It should also be more consistent. It should either always match or never match, not only match if U+0130 is part of a collection (and only with the NFA engine).

**Comment by tmccombs** [comment]
I think the problem is that regexp_nfa.c is using `mb_tolower` to compare case-insensitively rather than `utf_fold`. While for the purposes of display "İ" should be downcased to "i", for the purposes comparison using simple case folding in a non-turkish locale, it should be mapped to itself (there is no simple (S) or common (C) mapping for it in unicode/CaseFolding.txt).  It looks like `utf_fold` is used in regexp.c (I'm guessing that is the old engine?), but there is a comment mentioning it is slow, and it looks like it tries to only use it for non-ascii characters. So probably the same approach should be done in regexp_nfa.c?

**Comment by brammool** [comment]
I'm not sure how it should work, let's assume the old regexp engine had it right and adjust the NFA one.  At least using tolower() doesn't look right, utf_fold() should be used to compare ignore-case.

**Comment by brammool** [comment]
See Vim patch 8.2.0938

**Comment by glacambre** [comment]
Vim patch 8.2.0938 isn't in the list of patches that need to be ported to Neovim, so I'll close this issue :).
