### ISSUE TITLE
ftplugin/filetype.vim does not apply.

### ISSUE THREAD

**Issue by sentaro34** [neovim/neovim#12451]
- `nvim --version`:0.4.3,  0.5.0
- `init.vim`: $HOME/.config/nvim
- `ftplugin`: $HOME/.config/nvim

`init.vim`:
```
filetype plugin indent on
au BufRead,BufNewFile *.py set filetype=python
au BufRead,BufNewFile *.cpp set filetype=cpp
```

`ftplugin/python.vim` : `echo 'This is the python Neovim'`
`ftplugin/cpp.vim` : `echo 'This is the cpp Neovim`

It should be shown 'This is the python Neovim' when I run `nvim test.py`.Also too when I open the cpp file.
But 'this is python neovim' is not shown on my neovim.

Is my config wrong? Is this the bug?
if your neovim apply ftplugin/filetype.vim(e.g. python.vim) successfully, please tell me the neovim version.

My question:https://vi.stackexchange.com/questions/25752/language-specific-settings-do-not-work-in-neovim

**Comment by aaronhooper** [comment]
The plugin file does actually apply in my case, for v0.4.3 and nightly. Adding `set number` to one of the filetype plugins works properly, but echo never shows anything, whether opening `test.py` at the command line or from the editor.

**Comment by sentaro34** [comment]
Added 'set number' to init.vim.
It's work well. I'm sorry, my writing was wrong.
