### ISSUE TITLE
Make :filter recursive

### ISSUE THREAD

**Issue by eyalk5** [neovim/neovim#12453]
Hi,

I wish `:filter` could be made recursive.
that is -  `:filter /abc/ filter /cbd/ %list` would be a double filter.

**Comment by mhinz** [comment]
I see that there's no easy way to achieve that even with a more complex regexp, but we have so many more important things to work at, that this feature probably won't be implemented by us.

Maybe you have a better chance convincing [vim/vim](https://github.com/vim/vim) to implement it, then we'll merge it into Nvim.

**Comment by jamessan** [comment]
Doesn't `:filter /.*abc\&.*cbd/ %list` handle this?

**Comment by mhinz** [comment]
@jamessan Hmm, and I thought I tried exactly that!

Anyway, I consider this regexp to be a simple enough solution. No additional code in the editor needed.
