### ISSUE TITLE
redirect doesn't write stderr to file

### ISSUE THREAD

**Issue by eyalk5** [neovim/neovim#12454]
Hi,
Errors, ie python errors, appear in `:messages`. And yet, they are not present in the file generate by `redir >> fil`.

I wish they would be added too. Any chance?

![image](https://user-images.githubusercontent.com/23480511/83979474-54301280-a917-11ea-9024-3b2cfab1c72a.png)
(this content is not in the file)

Thanks.

**Comment by eyalk5** [comment]
Well, it seems to be related to this. 
But why not make it configurable? or make it true by default?
```
 EXTERN bool emsg_noredir INIT(= false);  // don't redirect error messages
```

**Comment by glacambre** [comment]
@eyalk5 The kind of python errors you're showing a properly redirected to files on master/nightly, so I'll close this issue :).
