### ISSUE TITLE
How to print the startup time.

### ISSUE THREAD

**Issue by glepnir** [neovim/neovim#12463]
- `nvim --version`:
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Question
Hi  @justinmk I doesn't search any result about this question, so i ask it here.  i want get the startup time by vim script. does there has any api ?

**Comment by chrisbra** [comment]
See `:h --startuptime`

**Comment by glepnir** [comment]
@chrisbra  I know this command also  i used it, but now i want get the startup time string. on my vim file.

**Comment by chrisbra** [comment]
you want what?

**Comment by glepnir** [comment]
Ok.fine.
