### ISSUE TITLE
LSP: support custom highlights in the floating window for show_line_diagnostics?

### ISSUE THREAD

**Issue by fsouza** [neovim/neovim#12472]
Hi there!

While working on some config for the lsp client, I realized that using the same highlight group for the virtualtext and the floating window when invoking show_line_diagnostics. In my case specifically, Pmenu is darker than the virtual text, so I'd like to use different highlight groups x)

We could introduce something like `LspDiagnostics<severity>Floating`, and similar to the Sign groups, we would link them with the regular one, providing backwards compatibility and the ability to customize it.

This is a small change, but I figured I could open an issue before sending a PR, in case someone wants to discuss the idea or implement something more sophisticated.

Any thoughts?

**Comment by glacambre** [comment]
On 2020-06-12 03:13, francisco souza wrote:
> We could introduce something like |LspDiagnostics<severity>Floating|, 
> and similar to the Sign groups, 

I think Neovim already does this for sign groups ( 
https://github.com/neovim/neovim/pull/12176 ). Or are you talking about 
something different?

**Comment by fsouza** [comment]
@glacambre hey, thanks for the response. Yes, this is different. The idea is to customize the highlight used in the diagnostics rendered by show_line_diagnostics.
