### ISSUE TITLE
Project level settings

### ISSUE THREAD

**Issue by thezealousfool** [neovim/neovim#12474]
Sometimes I have some settings applied to only the current project and not all my projects. VSCode for example has the provision to have a settings.json in the .vscode directory in the root of a project for project specific settings.

I was thinking maybe we can have a project level .vimrc or .nvimrc?

**Comment by ahmedelgabri** [comment]
This is how I'm doing this, so you can do add this to your config I & tweak it as you like.

I create a `.vim/local.vim` file in the root of my project which gets loaded when open files in that project.

```vim
function! source_project_config() abort
  let l:projectfile = findfile('.vim/local.vim', expand('%:p').';')
  if filereadable(l:projectfile)
    silent execute 'source' l:projectfile
  endif
endfunction

augroup MyAutoCmds
  autocmd!
  autocmd BufRead,BufNewFile * call <SID>source_project_config()

  if has('nvim')
    autocmd DirChanged * call <SID>source_project_config()
  endif
augroup END
```

**Comment by thezealousfool** [comment]
@ahmedelgabri Thanks. This works.

Can something like this be merged in the mainline?

**Comment by teto** [comment]
see `:h 'exrc'`, https://github.com/direnv/direnv, vim sessions I doubt we will add more support than that.

**Comment by thezealousfool** [comment]
I was not aware of this. Thank You.

This is my setup:
1. At the bottom of my `$XDG_CONFIG_HOME/nvim/init.vim` file, I set exrc
```
set exrc
```
2. The root of every project optionally has a `.nvimrc` file which then gets sourced after `$XDG_CONFIG_HOME/nvim/init.vim`

This is exactly what I was looking for. Thanks

**Comment by tcoopman** [comment]
> see `:h 'exrc'`, https://github.com/direnv/direnv, vim sessions I doubt we will add more support than that.

Isn't this deprecated because of security risks? https://github.com/neovim/neovim/issues/5784
