### ISSUE TITLE
refactor(options): impl default 'titlestring' by format flags

### ISSUE THREAD

**Issue by josephholsten** [neovim/neovim#1248]
At the moment, when `titlestring` is not set, the default value is generated by accessing `curbuf->b_fname`, `bufIsChanged(curbuf)`, `curbuf->b_ffname` & `append_arg_number()` (an extracted version of this is in [`src/nvim/title.c:113`](https://github.com/josephholsten/neovim/blob/rework-titles/src/nvim/title.c#L113)).

Unfortunately, it is not possible to reproduce this behaviour using a statusline format string. The closest might be:

```
:set titlestring=%t%(\ %M%)%(\ \(%F\)%)%a\ -\ VIM
```

where those represent the flags found in `option_defs.h`:

```
#define STL_FILENAME    't'             /* last part (tail) of file path */
#define STL_MODIFIED_ALT 'M'            /* modified flag - other display */
#define STL_FULLPATH    'F'             /* full path of file in buffer */
#define STL_ARGLISTSTAT 'a'             /* argument list status as (x of y) */
```

The only part which differs from the default `titlestring` is `%F`, which shows the full path of the file, including the last part (tail). The default uses the full path of the file with the part in `%t` and the final seperator removed.

The best way to allow for this would be to add a new statusline flag, say `%d` which shows the full path of the directory containing the current file.

Then, since statusline support is on all the time (according to [`src/nvim/version.c:140`](https://github.com/neovim/neovim/blob/master/src/nvim/version.c#L140)), we can simplify the implementation of `maketitle()` to always use the standard statusline processing.

Thoughts? Objections?

**Comment by Billy4195** [comment]
After I traced the current `titlestring` document (in :help titlestring), I think this issue is done by someone else. Maybe this could be close?

**Comment by justinmk** [comment]
> The only part which differs from the default `titlestring` is `%F`, which shows the full path of the file, including the last part (tail). The default uses the full path of the file with the part in `%t` and the final seperator removed.

This seems to mimic the default, what's missing?

    set titlestring=%t%(\ %M%)%(\ \(%{expand(\"%:~:h\")}\)%)%a\ -\ NVIM

**Comment by cristianUrbina** [comment]
Could I work on this?

**Comment by clason** [comment]
Just send a PR, no need to ask for permission. (Doesn't mean we'll merge it unconditionally, mind you.)
