### ISSUE TITLE
Cursor not restored when NeoVim suspended

### ISSUE THREAD

**Issue by nomasprime** [neovim/neovim#12498]
- `nvim --version`: 0.5.0-nightly-37-g8a1276005
- Operating system/version: MacOS 10.15.5
- Terminal name/version: iTerm 3.3.10beta2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Set iTerm to blinking vertical bar cursor
2. Open NeoVim
3. Suspend NeoVim with Ctrl-z

### Actual behaviour

Terminal cursor is now set to whatever NeoVim uses, in this case non-blinking block.

### Expected behaviour

Terminal cursor should be set to what terminal cursor was set to, in this case blinking vertical bar.

**Comment by nomasprime** [comment]
Based off [FAQ](https://github.com/neovim/neovim/wiki/FAQ#cursor-style-isnt-restored-after-exiting-nvim) I tried:

```
au VimLeave,VimSuspend * set guicursor=a:ver25
```

Which works for terminal but then cursor is wrong when NeoVim resumes.

**Comment by nomasprime** [comment]
Based on the [FAQ](https://github.com/neovim/neovim/wiki/FAQ#cursor-style-isnt-restored-after-exiting-nvim) I got this working with:

```
au VimEnter,VimResume * set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
  \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
  \,sm:block-blinkwait175-blinkoff150-blinkon175

au VimLeave,VimSuspend * set guicursor=a:ver25
```

It sounds like it's not possible to do this automatically. I'll update the FAQ.

**Comment by tmpm697** [comment]
You can disable nvim behavior of changing cursor by settings this `set guicursor=`, it's in FAQ.

**Comment by nomasprime** [comment]
Thanks @tmpm697 but that's not the issue.

I've already updated the FAQ so I guess this issue can be closed.
