### ISSUE TITLE
Please allow function to take optional arguments

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#12493]
I did not found any issue related to this incompatibility with Vim. 

https://github.com/vim/vim/commit/42ae78cfff171fbd7412306083fe200245d7a7a6

**Comment by erw7** [comment]
I've already created a PR (#12377).

**Comment by jamessan** [comment]
As a general note, @przepompownia, we're always going to be behind new Vim development.  Calling this an incompatibility is inaccurate.

You can from the [vimpatch report](https://neovim.io/doc/reports/vimpatch/) that we haven't even finished merging all the relevant 8.0 patches.

**Comment by przepompownia** [comment]
I did not realize that such a list exists. Thank you for both information.

**Comment by glacambre** [comment]
Optional arguments are available on master :tada: .
