### ISSUE TITLE
Screen isn't drawn correctly when using file launcher and particular colorscheme

### ISSUE THREAD

**Issue by noib3** [neovim/neovim#12512]
- `nvim --version`: NVIM v0.5.0-39f802b
- `vim -u DEFAULTS` (version: ) behaves differently? Yes, can't reproduce it with default config
- Operating system/version: macOS Catalina 10.15.5
- Terminal name/version: alacritty 0.4.3 (c723247)
- `$TERM`: not set

### Steps to reproduce using `nvim -u NORC`

Can't reproduce it with default config.

### Actual behaviour

I created a very basic file launcher with the command
````
alacritty -e zsh -c 'fd | fzf | (nohup xargs -I{} zsh -c '\''alacritty -e zsh -c "nvim \"${1}\""'\'' sh {} &>/dev/null &)'
````
Basically what this does is it creates a new terminal window (alacritty in my case), it runs `fd` to list the files in my home directory, and it pipes them to `fzf` so I can fuzzy search the file I want. Once I found the file I want to edit, that terminal window closes and a new one opens with that file in a neovim buffer.

The problem is that sometimes, not always, the neovim screen isn't drawn correctly, as you can see here:

![2020:06:21@01:45:59](https://user-images.githubusercontent.com/59321248/85213753-fe218d00-b362-11ea-9714-b80b8c80b3ca.png)

as you can see, the statusline is drawn in the middle of the screen. If I resize the window everything goes back to normal:

![2020:06:21@01:46:12](https://user-images.githubusercontent.com/59321248/85213760-388b2a00-b363-11ea-9c24-d06d1abe3667.png)

This doesn't happen everytime, so it's hard to reproduce reliably, and it only happens when I launch neovim with the launcher I described. Also, I can only reproduce it by using the onedark colorscheme, i.e. by having `colorscheme onedark` in my `init.vim`. If I don't use that colorscheme everything is drawn correctly everytime.

These are all my plugins:

````
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-endwise'
Plug 'farmergreg/vim-lastplace'
Plug 'jiangmiao/auto-pairs'
Plug 'Yggdroot/indentLine'
Plug 'junegunn/goyo.vim'
" colorschemes
Plug 'morhetz/gruvbox'
Plug 'joshdick/onedark.vim'
````

### Expected behaviour

The screen is drawn correctly everytime even when using the `onedark` colorscheme.

**Comment by glacambre** [comment]
Thanks for the report @noib3 :). I'm quite certain that this is the same bug as #11330 , so I'll close your issue. Feel free to subscribe to the other issue to be notified when it's fixed.
