### ISSUE TITLE
nvim change cursor shape from _ to █?

### ISSUE THREAD

**Issue by tmpm697** [neovim/neovim#12513]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: archlinux up-to-date
- Terminal name/version: st 0.8
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
just open nvim and my cursor shape change from _ to █

```

### Actual behaviour
cursor shape change from `_` to `█`

### Expected behaviour
I want to keep cursor shape as `_`.

I read FAQ and add some line to init.vim but doesn't work:  https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-shape-in-the-terminal

How to restore my cursor shape `_` or make nvim respect current one or inherit from terminal?

**Comment by glacambre** [comment]
Have you tried `:set guicursor=a:hor100`?

**Comment by tmpm697** [comment]
@glebtv : How to have it not blinking?

**Comment by glacambre** [comment]
`:set guicursor=a:blinkon0`. If your cursor keeps blinking after that, it is probably caused by your terminal rather than neovim and you should see if there's a way to disable the blinking by changing your terminal's settings.

See `:help guicursor` for more information about how to configure the cursor's settigs :).

**Comment by tmpm697** [comment]
My terminal does not have `_` blinking. so this caused by nvim.
set this partial work (no blinking):
```
set guicursor=n-v-c:hor100-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor
```
How can I understand above command correctly if I only all mode/everything just have cursor displayed as `_`?

Why nvim change this behavior of cursor, I never had any problem with vim8.

I use tmux in terminal and above workaround only happens to work on a tmux's pane, If I create new pane then `█` re-appear and blinking. how to fix this?

**Comment by glacambre** [comment]
On 2020-06-21 15:02, tmpm697 wrote:
> My terminal does not have |_| blinking. so this caused by nvim.
> set this partial work (no blinking):
> 
> |set 
> guicursor=n-v-c:hor100-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor 
> |
> 
> How can I understand above command correctly if I only all 
> mode/everything just have cursor displayed as |_|?

I don't understand what you mean. Have you tried `:set 
guicursor=a:hor100-blinkon0`?

> 
> Why nvim change this behavior of cursor

Because Neovim maintainers think this is a useful feature :).
> I use tmux in terminal and above workaround only happens to work on a 
> tmux's pane, If I create new pane then |█| re-appear and blinking. how 
> to fix this?

I'm tempted to think that this is a tmux issue, although I can't be 
certain of that.

**Comment by teto** [comment]
if you  don't want neovim to change your cursor, you can use `set guicursor=`

**Comment by tmpm697** [comment]
This issue still happens with NVIM v0.4.3
when I install neovim-git from aur, and set `set guicursor=` fixed the issue.  FAQ doesn't clear this include tmux's pane issue --> issue from neovim not tmux.
Thanks for helping.
