### ISSUE TITLE
Missing documentation for {cancelreturn} in input()

### ISSUE THREAD

**Issue by JaSpa** [neovim/neovim#12522]
- `nvim --version`: *v0.4.3*
- `vim -u DEFAULTS` (version: 8.1.2292) behaves differently? *yes*
- Operating system/version: *macOS 10.15 (Catalina)*
- Terminal name/version: *iTerm2 3.3*
- `$TERM`: `TERM=xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```vim
:h input()
" Learned about {cancelreturn} which is “same as {cancelreturn} from |inputdialog()|”
:h inputdialog()
" Only says to use |input()| instead
:helpg inputdialog
" No information about {cancelreturn} anywhere
:helpg cancelreturn
" Only match is the line “… same as {cancelreturn} from |inputdialog()|” from `:h input()`
```

### Actual behaviour

There is no way to find information about `{cancelreturn}`

### Expected behaviour

Documentation for `{cancelreturn}` somewhere. VIM documents this under `inputdialog()`.

**Comment by teto** [comment]
inputdialog recommands to use input that documents cancelreturn (on master at least).

**Comment by phaazon** [comment]
Can we re-open this? This is not fixed.

![img_031521_182509](https://user-images.githubusercontent.com/506592/111194793-d55db980-85bb-11eb-8bd2-c0f5b2274170.png)

![img_031521_182522](https://user-images.githubusercontent.com/506592/111194801-d7c01380-85bb-11eb-9406-39bafebdc79e.png)

**Comment by teto** [comment]
not sure what's wrong, you want to remove the reference to inputdialog ? by "message returned when input cancelled" ? PR welcome

**Comment by phaazon** [comment]
@teto okay sorry, maybe I was unclear. The documentation of `input` references `inputdialog` (about the `cancelreturn` field in the `opts` table that the second form can take), but `inputdialog` doesn’t have the documentation of this field as it references back to `input`. Did we use to have the documentation of this field here? If so, then this is a regression, right?
