### ISSUE TITLE
LSP: Using document_range_formatting with formatexpr

### ISSUE THREAD

**Issue by meck** [neovim/neovim#12528]
I opened this initially in https://github.com/neovim/nvim-lsp/issues/288 @tjdevries asked to open here:

Testing the builtin Lsp, loving it so far! I hit a minor issue while configuring everything.
I wanted to use Lsp formatting with `formatexpr`,  however setting:
`api.nvim_buf_set_option(bufnr, 'formatexpr', 'v:lua.vim.lsp.buf.range_formatting()')`
has some issues as `formatexpr` expects to use the range in `v:lnum` `v:count` and
only works on whole lines.

I managed to solve it by wrapping the call (I don't know any Lua so this this is most likely terrible):
```lua
Formatexpr_wrapper = function()
 -- only reformat on explicit gq command
 if not fn.mode() == 'n' then
    -- fall back to Vims internal reformatting
    return 1
 end

 local opts = {}
 local start_line = vim.v.lnum
 local end_line = start_line + vim.v.count - 1
 if start_line >= 0 and end_line >= 0 then
   lsp.buf.range_formatting(opts, {start_line, 0}, {end_line, 0})
 end

 return 0
end
```

I was thinking functionality like this might be good to include?

**Comment by tjdevries** [comment]
Thanks for posting here @meck Would you be interested in making the PR for this? I'd be happy to walk you through some of it if you're interested.

**Comment by meck** [comment]
Sure, I could give it a whirl, what would be a good implementation?

Looking at the code a alternative would be to add something like a bool `use_lnum` or `for_formatexpr` (default false) to the options passed to `vim.lsp.buf.range_formating()` changing the behaviour. Then the user command would be something like
`setlocal formatexpr=v:lua.Formatexpr_wrapper({options={for_formatexpr=true}})`

Otherwise it could just be a new function `vim.lsp.buf.lsp_formatexpr()`

As I said I really don't know lua... :)

**Comment by clason** [comment]
It seems to me that you want to implement [`DocumentRangeFormatting`](https://microsoft.github.io/language-server-protocol/specification#textDocument_rangeFormatting), right? (Here's the `vim-lsp` implementation for reference: https://github.com/prabirshrestha/vim-lsp/blob/17a7d92ed00ac5ef48e5d697181a1054d2643e59/autoload/lsp/ui/vim.vim#L235)

**Comment by clason** [comment]
For the record, here's how vim-lsp does it: https://github.com/prabirshrestha/vim-lsp/pull/528 

This basically amounts to your first option with a bool. But it might make sense to future-proof this to extend the `format` callbacks (and the underlying `apply_text_edits` functions) to accept and pass through an `opts` structure, similar to what we do already for popups (hover)?

**Comment by kovasap** [comment]
Using `vim.api.nvim_buf_set_option(0, 'formatexpr', 'v:lua.vim.lsp.formatexpr')` does not produce the same formatting as the code in https://github.com/neovim/neovim/issues/14680#issuecomment-863739006, which surprises me.  Is this intentional?  I would expect the formatting to be done by the LSP in the same way in both cases.
