### ISSUE TITLE
Add support for Windows on Arm64

### ISSUE THREAD

**Issue by be5invis** [neovim/neovim#12521]
Recently [VSCode gets native ARM64 support on Windows](https://code.visualstudio.com/updates/v1_46#_windows-arm64-insiders), and "original Vim" also [has Windows/ARM64 support](https://github.com/vim/vim/commit/577fadfc100ff8fa569a34b89f5ad055ad726646). As a great and powerful editor, NeoVim could add support to it.

**Comment by teto** [comment]
considering the vim patch and that libuv supports ARM, it doesn't seem too hard. I dont run either windows or arm but patches welcome

**Comment by jamessan** [comment]
@be5invis, have you tried to build on arm64?  I don't know of anything that would prevent us from building there, as long as you have the dependencies installed.

I don't see anything actionable in this issue, unless you know there's a build problem.

**Comment by be5invis** [comment]
@jamessan I am trying to create a cross compilation build on a x64 machine with VS2019 and corresponding toolchains, but the docs are very unclear. It looks like MSVC build doesn't need MinGW?

**Comment by be5invis** [comment]
As the first step I added following section into `third-party/cmake/TargetArch.cmake`:

```cmake
# ARM64
check_symbol_exists("_M_ARM64" "" T_M_ARM64)
check_symbol_exists("__aarch64__" "" T_AARCH64)
if(T_M_ARM64 OR T_AARCH64)
set(TARGET_ARCH "ARM64")
  return()
endif()
```

Then, the first blocker is Win32Yank which doesn't have ARM64 version.

**Comment by be5invis** [comment]
By using the x86 win32yank EXE the build for dependency mostly worked, however:

**Dependency `luajit` cannot be cross-compiled because it needs to run itself on the host.**

**Comment by teto** [comment]
Win32Yank is nice to have but you could disable it as a first step. As for luajit (and other dependencies), you don't have to use the bundled ones, you can cross compile on your system and reference that dependency via `-DLUA_PRG=/my/lua/interpreter`

**Comment by be5invis** [comment]
@teto Actually all the other deps worked. LuaJIT compiles but -- well -- it compiled to the target arch instead of the host arch so some codegen (?) cannot be done.
I saw there's a MinGW cross compilation branch in your cmake files but not sure whether MSVC could use it.

For my steps so far:

1. Install VS2019 and ARM64 cross compilation toolchain;
2. Run `cmd /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsamd64_arm64.bat"` to get a CMD with ARM64 cross compilation toolchain.
3. `mkdir .deps; cd .deps`
4. `cmake -G "Visual Studio 16 2019" -A ARM64 -DCMAKE_BUILD_TYPE=RelWithDebInfo ..\third-party\` -- you need to patch `third-party/cmake/TargetArch.cmake` to let CMake know that you are targeting ARM64
5. `cmake --build . --config RelWithDebInfo -- /verbosity:normal` ← progress so far, one error when building `luajit`.

**Comment by be5invis** [comment]
@teto Curious about whether the "original" lua (non-JIT) could be used in NeoVim... That only uses standard C so porting is really easy

**Comment by teto** [comment]
it is possible but you won't be able to run the testsuite

2020年6月24日(水) 11:54 Belleve Invis <notifications@github.com>:

**Comment by jamessan** [comment]
> it is possible but you won't be able to run the testsuite

It's cross-compiled anyway, so regardless none of the tests will be able to run.

For the non-cross-compiled case, using Lua allows running functional and legacy tests but not unit tests.

**Comment by jamessan** [comment]
> I am trying to create a cross compilation build on a x64 machine

Why?  That's just an additional layer of complexity.  I thought that since you were asking about Arm support, you actually had an Arm device.  In that case, you could just build there.

**Comment by imbushuo** [comment]
> **Why? That's just an additional layer of complexity. I thought that since you were asking about Arm support, you actually had an Arm device. In that case, you could just build there.**

Why it is technically possible to build ARM on ARM device, it is not really convenient to do so. In addition, in the Windows case, MSVC isn't really provide native arm64 toolchain, so anyway a cross compile is required (you can run the x86-arm64 toolchain on arm64 device, but anyway it is a cross-compile.)

**Comment by be5invis** [comment]
@jamessan Also lacking of ARM64 CI system made us have to do cross compilation for building.

The CMake scripts about Lua need some change for OS-arch combinations that currently doesn't have LuaJIT available. @imbushuo @yatli

**Comment by imbushuo** [comment]
Attempted to run a quick build without looking into it. Here's my result:

- The built-in third party dependencies build have a few configuration (e.g. `luv-static`) assumes LuaJIT's presence. While it is possible to use the original Lua (as described by those projects), the configuration is not get enabled yet.
- In cross-compile scenarios, a few third-party things like Lua might need to be compiled twice (for host architecture and target architecture) due to the build process.

I have not yet reached the main portion (neovim). I will update once I reached there.

It might be useful to add an option to enable using the usage of original Lua in third party dependencies since it will be useful for porting to new architectures or architectures that are not yet supported by LuaJIT.

**Comment by jeffthompsonsd** [comment]
Any progress? Would love an arm64 native nvim

**Comment by justinmk** [comment]
Nothing actionable here. We aren't going to provide arm builds until appveyor actually supports it. Meanwhile, you can build on an arm device.

**Comment by jeffthompsonsd** [comment]
> Nothing actionable here. We aren't going to provide arm builds until appveyor actually supports it. Meanwhile, you can build on an arm device.

Building on my arm device doesnt work, i get the luajit errors described above. Using be5invis steps i get the following when running cmake for the deps

CMake Error at cmake/GetBinaryDeps.cmake:25 (message):
  WIN32YANK_ARM64_URL and WIN32YANK_ARM64_SHA256 must be set

**Comment by wbsdty331** [comment]
ARM64 Windows support of LuaJIT is available. cross-compiling from Windows x64 MSVC is possible too.
https://github.com/LuaJIT/LuaJIT/pull/1081

**Comment by clason** [comment]
Cross-compiling Neovim is not supported. If you manage to compile a native build, please make a PR adding instructions. But we cannot officially support it, as long as Github doesn't provide a test environment for it.

**Comment by itpropro** [comment]
> Nothing actionable here. We aren't going to provide arm builds until appveyor actually supports it. Meanwhile, you can build on an arm device.

There is also a ARM build for MacOS available now @justinmk. Can we reopen this issue to track availability for a Windows on ARM binary?

**Comment by andriysavin** [comment]
I managed to compile a native Windows Arm64 build. My steps (assuming you have neovim sources cloned):
1. Have Windows on Arm64 (in my case it's a VM runnin in VMWare Fusion on a Mac).
2. Have Visual Studio 2026 installed with C++ development workload.
3. Open **ARM64 Native Tools Command Prompt for VS 18**.
4. cd into neovim sources dir
5. Build dependencies (note that I did **Debug** builds, you should specify what you need):
cmake -S cmake.deps -B .deps -G Ninja -D CMAKE_BUILD_TYPE=Debug
cmake --build .deps
6. Build neovim:
cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=Debug
cmake --build build
7. Bring everything together: 
cmake --install build --prefix ./dist
8. Run: .\dist\bin\nvim.exe

For me all works nice at first glance, all plugins etc. But I guess there are some dependencies which might crash at run time once hit (e.g. win32yank.exe looks suspiciosly x64-ish).

<img width="704" height="142" alt="Image" src="https://github.com/user-attachments/assets/8c51bcfa-6917-4a97-8a4f-2ec1317f0334" />
