### ISSUE TITLE
LSP: tsserver "add missing import" code action results in syntax error

### ISSUE THREAD

**Issue by ktfleming** [neovim/neovim#12526]
- `nvim --version`: NVIM v0.5.0-721f69c4a
- language server name/version: tsserver
- Operating system/version: macOS Catalina

<details>
<summary>nvim -c ":checkhealth nvim nvim_lsp"</summary>

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 10ms
  - INFO: $TERM: tmux-256color

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyls: configuration checked.
  - INFO: jdtls: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: metals: configuration checked.

</details>

<details>
<summary>lsp.log</summary>

[ DEBUG ] 2020-06-24T07:09:08+0900 ] ...r/neovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp.lua:504 ]  "LSP[tsserver]" "client.request"        1       "textDocument/codeAction"      {  context = {    diagnostics = { {        code = 2304,        message = "Cannot find name 'C'.",        range = {          end = {            character = 10,            line = 5          },          start = {            character = 9,            line = 5          }        },        severity = 1,        source = "typescript",        uri = "file:///Users/kevin/dev/nvim_bug/main.ts"      }, {        code = 6133,        message = "'c' is declared but its value is never read.",        range = {          end = {            character = 7,            line = 5          },          start = {            character = 6,            line = 5          }        },        severity = 4,        source = "typescript",        uri = "file:///Users/kevin/dev/nvim_bug/main.ts"      } }  },  range = {    end = <1>{      character = 9,      line = 5    },    start = <table 1>  },  textDocument = {    uri = "file:///Users/kevin/dev/nvim_bug/main.ts"  }}      <function 1>    1
[ DEBUG ] 2020-06-24T07:09:08+0900 ] ...ovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp/rpc.lua:267 ]  "rpc.send.payload"      {  id = 2,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = { {          code = 2304,          message = "Cannot find name 'C'.",          range = {            end = {              character = 10,              line = 5            },            start = {              character = 9,              line = 5            }          },          severity = 1,          source = "typescript",          uri = "file:///Users/kevin/dev/nvim_bug/main.ts"        }, {          code = 6133,          message = "'c' is declared but its value is never read.",          range = {            end = {              character = 7,              line = 5            },            start = {              character = 6,              line = 5            }          },          severity = 4,          source = "typescript",          uri = "file:///Users/kevin/dev/nvim_bug/main.ts"        } }    },    range = {      end = <1>{        character = 9,        line = 5      },      start = <table 1>    },    textDocument = {      uri = "file:///Users/kevin/dev/nvim_bug/main.ts"    }  }}
[ DEBUG ] 2020-06-24T07:09:08+0900 ] ...ovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp/rpc.lua:347 ]  "decoded"       {  id = 2,  jsonrpc = "2.0",  result = { {      arguments = { {          documentChanges = { {              edits = { {                  newText = ",",                  range = {                    end = {                      character = 3,                      line = 2                    },                    start = {                      character = 3,                      line = 2                    }                  }                }, {                  newText = "\n  C",                  range = {                    end = {                      character = 3,                      line = 2                    },                    start = {                      character = 3,                      line = 2                    }                  }                } },              textDocument = {                uri = "file:///Users/kevin/dev/nvim_bug/main.ts",                version = 0              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Add 'C' to existing import declaration from \"./lib\""    }, {      arguments = { {          documentChanges = { {              edits = { {                  newText = "",                  range = {                    end = {                      character = 10,                      line = 5                    },                    start = {                      character = 8,                      line = 5                    }                  }                } },              textDocument = {                uri = "file:///Users/kevin/dev/nvim_bug/main.ts",                version = 0              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Remove declaration for: 'C'"    } }}
[ DEBUG ] 2020-06-24T07:09:08+0900 ] ...EAD-721f69c/share/nvim/runtime/lua/vim/lsp/callbacks.lua:257 ]  "default_callback"      "textDocument/codeAction"     {  bufnr = 1,  client_id = 1,  params = { {      arguments = { {          documentChanges = { {              edits = { {                  newText = ",",                  range = {                    end = {                      character = 3,                      line = 2                    },                    start = {                      character = 3,                      line = 2                    }                  }                }, {                  newText = "\n  C",                  range = {                    end = {                      character = 3,                      line = 2                    },                    start = {                      character = 3,                      line = 2                    }                  }                } },              textDocument = {                uri = "file:///Users/kevin/dev/nvim_bug/main.ts",                version = 0              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Add 'C' to existing import declaration from \"./lib\""    }, {      arguments = { {          documentChanges = { {              edits = { {                  newText = "",                  range = {                    end = {                      character = 10,                      line = 5                    },                    start = {                      character = 8,                      line = 5                    }                  }                } },              textDocument = {                uri = "file:///Users/kevin/dev/nvim_bug/main.ts",                version = 0              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Remove declaration for: 'C'"    } }}[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...r/neovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp.lua:504 ]  "LSP[tsserver]" "client.request"        1       "workspace/executeCommand"     {  arguments = { {      documentChanges = { {          edits = { {              newText = ",",              range = {                end = {                  character = 3,                  line = 2                },                start = {                  character = 3,                  line = 2                }              }            }, {              newText = "\n  C",              range = {                end = {                  character = 3,                  line = 2                },                start = {                  character = 3,                  line = 2                }              }            } },          textDocument = {            uri = "file:///Users/kevin/dev/nvim_bug/main.ts",            version = 0          }        } }    } },  command = "_typescript.applyWorkspaceEdit",  title = "Add 'C' to existing import declaration from \"./lib\""}        <function 1>    1[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...ovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp/rpc.lua:267 ]  "rpc.send.payload"      {  id = 3,  jsonrpc = "2.0",  method = "workspace/executeCommand",  params = {    arguments = { {        documentChanges = { {            edits = { {                newText = ",",                range = {                  end = {                    character = 3,                    line = 2                  },                  start = {                    character = 3,                    line = 2                  }                }              }, {                newText = "\n  C",                range = {                  end = {                    character = 3,                    line = 2                  },                  start = {                    character = 3,                    line = 2                  }                }              } },            textDocument = {              uri = "file:///Users/kevin/dev/nvim_bug/main.ts",              version = 0            }          } }      } },    command = "_typescript.applyWorkspaceEdit",    title = "Add 'C' to existing import declaration from \"./lib\""  }}[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...ovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp/rpc.lua:347 ]  "decoded"       {  id = 0,  jsonrpc = "2.0",  method = "workspace/applyEdit",  params = {    edit = {      documentChanges = { {          edits = { {              newText = ",",              range = {                end = {                  character = 3,                  line = 2                },                start = {                  character = 3,                  line = 2                }              }            }, {              newText = "\n  C",              range = {                end = {                  character = 3,                  line = 2                },                start = {                  character = 3,                  line = 2                }              }            } },          textDocument = {            uri = "file:///Users/kevin/dev/nvim_bug/main.ts",            version = 0          }        } }    }  }}[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...r/neovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp.lua:352 ]  "server_request"        "workspace/applyEdit"   {  edit = {    documentChanges = { {        edits = { {            newText = ",",            range = {              end = {                character = 3,                line = 2              },              start = {                character = 3,                line = 2              }            }          }, {            newText = "\n  C",            range = {              end = {                character = 3,                line = 2              },              start = {                character = 3,                line = 2              }            }          } },        textDocument = {          uri = "file:///Users/kevin/dev/nvim_bug/main.ts",          version = 0        }      } }  }}
[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...r/neovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp.lua:355 ]  "server_request: found callback for"    "workspace/applyEdit"[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...EAD-721f69c/share/nvim/runtime/lua/vim/lsp/callbacks.lua:257 ]  "default_callback"      "workspace/applyEdit"   {  client_id = 1,  params = {    edit = {      documentChanges = { {          edits = { {              newText = ",",              range = {                end = {                  character = 3,                  line = 2                },                start = {                  character = 3,                  line = 2                }              }            }, {              newText = "\n  C",              range = {                end = {                  character = 3,                  line = 2                },                start = {                  character = 3,                  line = 2                }              }            } },          textDocument = {            uri = "file:///Users/kevin/dev/nvim_bug/main.ts",            version = 0          }        } }    }  }}[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...r/neovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp.lua:587 ]  "on_lines"      1       4       2       3       4     44       4       { "  B", "  C," }[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...ovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp/rpc.lua:278 ]  "rpc.notify"    "textDocument/didChange"        {  contentChanges = { {      text = 'import {\n  A,\n  B\n  C,\n} from "./lib";\n\nconst c: C = {};\n'    } },  textDocument = {    uri = "file:///Users/kevin/dev/nvim_bug/main.ts",    version = 4  }}[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...ovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp/rpc.lua:267 ]  "rpc.send.payload"      {  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        text = 'import {\n  A,\n  B\n  C,\n} from "./lib";\n\nconst c: C = {};\n'      } },    textDocument = {      uri = "file:///Users/kevin/dev/nvim_bug/main.ts",      version = 4    }  }}[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...ovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp/rpc.lua:358 ]  "server_request: callback result"       {  result = {    applied = true  },  status = true}[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...ovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp/rpc.lua:267 ]  "rpc.send.payload"      {  id = 0,  jsonrpc = "2.0",  result = {    applied = true  }}[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...ovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp/rpc.lua:347 ]  "decoded"       {  id = 3,  jsonrpc = "2.0",  result = vim.NIL}[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...EAD-721f69c/share/nvim/runtime/lua/vim/lsp/callbacks.lua:257 ]  "default_callback"      "workspace/executeCommand"    {  bufnr = 1,  client_id = 1}[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...ovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp/rpc.lua:347 ]  "decoded"       {  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = 1005,        message = "',' expected.",        range = {          end = {            character = 3,            line = 3          },          start = {            character = 2,            line = 3          }        },        severity = 1,        source = "typescript"      }, {        code = 6133,        message = "'A' is declared but its value is never read.",        range = {          end = {            character = 3,            line = 1          },          start = {            character = 2,            line = 1          }        },        severity = 4,        source = "typescript"      }, {        code = 6133,        message = "'B' is declared but its value is never read.",        range = {          end = {            character = 3,            line = 2          },          start = {            character = 2,            line = 2          }        },        severity = 4,        source = "typescript"      }, {        code = 6133,        message = "'c' is declared but its value is never read.",        range = {          end = {            character = 7,            line = 6          },          start = {            character = 6,            line = 6          }        },        severity = 4,        source = "typescript"      } },    uri = "file:///Users/kevin/dev/nvim_bug/main.ts"  }}
[ DEBUG ] 2020-06-24T07:09:16+0900 ] ...r/neovim/HEAD-721f69c/share/nvim/runtime/lua/vim/lsp.lua:343 ]  "notification"  "textDocument/publishDiagnostics"     {  diagnostics = { {      code = 1005,      message = "',' expected.",      range = {        end = {          character = 3,          line = 3        },        start = {          character = 2,          line = 3        }      },      severity = 1,      source = "typescript"    }, {      code = 6133,      message = "'A' is declared but its value is never read.",      range = {        end = {          character = 3,          line = 1        },        start = {          character = 2,          line = 1        }      },      severity = 4,      source = "typescript"    }, {      code = 6133,      message = "'B' is declared but its value is never read.",      range = {        end = {          character = 3,          line = 2        },        start = {          character = 2,          line = 2        }      },      severity = 4,      source = "typescript"    }, {      code = 6133,      message = "'c' is declared but its value is never read.",      range = {        end = {          character = 7,          line = 6        },        start = {          character = 6,          line = 6        }      },      severity = 4,      source = "typescript"    } },  uri = "file:///Users/kevin/dev/nvim_bug/main.ts"}

</details>

#### Setup
Not NORC, but can be reproduced with this minimal `init.vim` (using vim-plug to install the nvim-lsp plugin):
```
call plug#begin(stdpath('data') . '/plugged')
Plug 'neovim/nvim-lsp'
call plug#end()

lua << EOF
local nvim_lsp = require'nvim_lsp'
nvim_lsp.tsserver.setup{}
EOF
```

Also requires the tsserver executable:
```
npm install -g typescript-language-server
```

Then create these two files in a new directory:

`lib.ts`, with contents
```typescript
export interface A {}
export interface B {}
export interface C {}
```

`main.ts`, with contents
```typescript
import {
  A,
  B
} from "./lib";

const c: C = {};
```

Finally, create a `package.json` file so nvim-lsp will recognize the project and use tsserver (can do `npm init` and just use the defaults).

#### Reproducing

1. Open `main.ts` using the minimal `init.vim` written above
1. Put your cursor on the capital `C` in the last line. Note that `C` isn't yet imported from `./lib`, so we want to use a code action to import it.
1. Do `:lua vim.lsp.buf.code_action()<CR>`
1. Choose the code action `Add 'C' to existing import declaration from "./lib"`

### Actual behaviour

The imports are changed to

```typescript
import {
  A,
  B
  C,
} from "./lib";
```

(which is a syntax error; there should be a comma after `B`)

### Expected behaviour

The imports are changed to

```typescript
import {
  A,
  B,
  C
} from "./lib";
```

### More info

`git bisect` suggests that this started happening with https://github.com/neovim/neovim/commit/44fe8828f06a22bc9aa3617a6fd8aae447a838de; it was working as expected before that. The comments on that PR (https://github.com/neovim/neovim/pull/12434) suggest that before that, nvim's LSP was applying text edits in an incorrect order...so if nvim's behavior is in fact correct according to the spec now, then it's possible that this is a bug in tsserver. Looking at the LSP logs, though, the relevant text edits seem to be of this form:

```
{
  id = 2,
  jsonrpc = "2.0",
  result = {
    {
      arguments = {
        {
          documentChanges = {
            {
              edits = {
                {
                  newText = ",",
                  range = {
                    end = {
                      character = 3,
                      line = 2
                    },
                    start = {
                      character = 3,
                      line = 2
                    }
                  }
                },
                {
                  newText = "\n  C",
                  range = {
                    end = {
                      character = 3,
                      line = 2
                    },
                    start = {
                      character = 3,
                      line = 2
                    }
                  }
                }
              },
  ...
```

I don't know too much about the LSP spec, but it looks like two text edits with the same start position: first add a comma, and then add a newline and `C`. So it seems like applying them in that order should result in the expected code...I'm not sure why it seems to be happening backwards. The particular conditions (two textedits with the same start position, and something possibly happening with the ordering) do seem to have something to do with https://github.com/neovim/neovim/commit/44fe8828f06a22bc9aa3617a6fd8aae447a838de, though.

**Comment by ndreas** [comment]
I think I misinterpreted the spec when I did #12434, so this is probably a bug in the changes I did. I just double checked the [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textedit) and it says:

> However, it is possible that multiple edits have the same start position: multiple inserts, or any number of inserts followed by a single remove or replace edit. If multiple inserts have the same position, the order in the array defines the order in which the inserted strings appear in the resulting text.

I think I read the spec too fast when I wanted to fix my issue. I had the issue that an LSP sent first the removal of a section of text, and then added the new text with the same start position. Before my change, the changes were applied in the reverse order, making the addition happen before the removal which was erroneous, and it by chance made your case work.

Reading the quoted paragraph now makes me think it might be the LSP that was buggy in my case, but I also think that applying changes in reverse was not the correct way to do it. I can investigate this further by looking at other LSP implementations.

One fix that covers both this issue and mine would be to fold all inserts with the same start index into a single edit, but I'm unsure if that is the correct way to go.

**Comment by ndreas** [comment]
This was the case I wanted to fix in #12434:

```lua
{
  documentChanges = {
    {
      edits = {
        {
          newText = "",
          range = {
            ['end'] = {
              character = 6,
              line = 3
            },
            start = {
              character = 2,
              line = 3
            }
          }
        },
        {
          newText = "fmt",
          range = {
            ['end'] = {
              character = 6,
              line = 3
            },
            start = {
              character = 6,
              line = 3
            }
          }
        },
        {
          newText = "",
          range = {
            ['end'] = {
              character = 5,
              line = 4
            },
            start = {
              character = 2,
              line = 4
            }
          }
        },
        {
          newText = "sync",
          range = {
            ['end'] = {
              character = 5,
              line = 4
            },
            start = {
              character = 5,
              line = 4
            }
          }
        }
      },
      textDocument = {
        uri = "file:///path/to/main.go",
        version = 0
      }
    }
  }
}
```

The case was a go file with the import statements:

```go
import (
 "sync"
 "fmt"
)
...
```
Where before #12434 when it applied changes in reverse order it would do the following:

```
import (
 "sync"   ->  "fmtsync"  -> "ync"    
 "fmt"
)
...
```

Now I'm starting to think that the changes sent from `gopls` are invalid according to the spec where it says

> However, it is possible that multiple edits have the same start position: multiple inserts, or any number of inserts followed by a single remove or replace edit.

The change from `gopls` is actually a remove followed by an insert which seems to go against the spec.

I do think we can cover both cases, since we can collapse multiple inserts into a single insert which would cover the `tsserver` case while still allow for the `gopls` case. I can take a stab at this in a PR and see if it's accepted.

**Comment by ktfleming** [comment]
Thanks! I don't know enough at the moment to comment on the solution/implementation, but I compiled your branch at https://github.com/neovim/neovim/pull/12533 and confirmed that it does fix the issue I was seeing with tsserver.

**Comment by ktfleming** [comment]
Confirmed that this was fixed with https://github.com/neovim/neovim/pull/12564, thanks @ndreas!
