### ISSUE TITLE
Prevent neovim reset cursor when using sudo nvim?

### ISSUE THREAD

**Issue by tmpm697** [neovim/neovim#12532]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version:  archlinux up-to-date
- Terminal name/version: st 0.8
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
use sudo nvim to edit a file under /root
e.g: sudo nvim /root/.vimrc
my cursor's shape change from _ to ▒
```

### Actual behaviour
cursor's shape changed

### Expected behaviour
cursor's shape doesn't change

I already have these below lines in /root/.vimrc and homdir/.vimrc of current user:
```
set guicursor=
autocmd OptionSet guicursor noautocmd set guicursor=
```

**Comment by glacambre** [comment]
I'm not sure neovim reads .vimrc. Have you tried putting these options in `/root/.config/nvim/init.vim` instead?

**Comment by tmpm697** [comment]
right, I put it wrong place.
