### ISSUE TITLE
SMACK support.

### ISSUE THREAD

**Issue by splinterofchaos** [neovim/neovim#1253]
[SMACK](http://en.wikipedia.org/wiki/Smack_(software)) stands for Simplified Mandatory Access Control Kernel and it's not ancient or anything (2008), but I don't know what it's used for. Some of the oldest unmerged patches relate to it (starting with [238](https://code.google.com/p/vim/source/detail?r=v7-4-238) and since I don't know how to test it, I don't want to try. Does anyone have any knowledge of this?

Since no one has complained neovim lacks it, I doubt many people care.

**Comment by justinmk** [comment]
The patch report serves as a reminder for this.
