### ISSUE TITLE
Nvim not finding function with long arguments in tags file

### ISSUE THREAD

**Issue by Lexx666** [neovim/neovim#12535]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: 8.0) behaves differently? Yes
- Operating system/version: Xubuntu 18.04
- Terminal name/version: terminator 1.91
- `$TERM`: xterm-256color

### Steps to reproduce
Make a new PHP file:
```
nvim test.php
```
Add a function to that file and save/quit:
```
<?php
function long_arguments( $arg01, $arg02, $arg03, $arg04, $arg05, $arg06, $arg07, $arg10, $arg11, $arg12, $arg13, $arg14, $arg15, $arg16, $arg17, $arg20, $arg21, $arg22, $arg23, $arg24, $arg25, $arg26, $arg27, $arg30, $arg31, $arg32, $arg33, $arg34, $arg35, $arg36, $arg37, $arg40, $arg41, $arg42, $arg43, $arg44, $arg45, $arg46, $arg47, $arg50, $arg51, $arg52, $arg53, $arg54, $arg55, $arg56, $arg57, $arg58, $arg59, $arg60, $arg61, $arg62, $arg63, $arg64, $arg65, $arg66, $arg67, $arg68, $arg69, $arg70, $arg71, $arg72, $arg73, $arg74, $arg75, $arg76, $arg77, $arg78, $arg79, $arg80, $arg81, $arg82, $arg83, $arg84, $arg85, $arg86, $arg87, $arg88, $arg89, $arg90, $arg91, $arg92, $arg93, $arg94, $arg95, $arg96, $arg97, $arg98, $arg99, $arg100)
{
}
```
Generate tags file for this file:
```
ctags test.php
```
Then try to jump to the function with:
```
nvim -t long_arguments
```

### Actual behaviour
E426: Konnte Tag "long_arguments" nicht finden

### Expected behaviour
Open test.php and jump to function long_arguments().

**Comment by erw7** [comment]
Perhaps this has been corrected in https://github.com/neovim/neovim/pull/11431 (https://github.com/neovim/neovim/pull/11431/commits/970329ff8dd138fed74bb5e722ae7690f06ef4ac). Please try [nightly](https://github.com/neovim/neovim/releases/tag/nightly).

**Comment by Lexx666** [comment]
OK, I tried NVIM v0.5.0-575-g225f0bcd9. Unfortunately this did't fix it.

**Comment by erw7** [comment]
In my environment, NVIM v0.5.0-575-g225f0bcd9 does not have this problem. This problem with NVIM v0.5.0-575-g225f0bcd9 when trying the following command occurs?

```
nvim -u NORC -t long_arguments
```

**Comment by Lexx666** [comment]
Ok, thx. In version v0.4.3 the error occurs with '-u NORC' but in the nightly builld it's gone. But I'm confused what configuration could cause this.
