### ISSUE TITLE
Courier and Consolas reports bad fixed metrics at different height sizes. 

### ISSUE THREAD

**Issue by webmandman** [neovim/neovim#12546]
- `nvim-qt --version`: v0.4.3  -- LuaJIT: 2.0.5  -- Build type: RelWithDebInfo
- Operating system/version: Windows 10
- Terminal name/version: nvim-qt

### Actual behaviour
Setting the guifont to Consolas:h12 or Consolas:h14 gives Warning: Font "Consolas" reports bad fixed pitch metrics.

### Expected behaviour
To not get any warnings like when Consolas:h16 is used. 16 is ok. 14 or 12 is not.

**Comment by jamessan** [comment]
This is a neovim-qt issue, which should be discussed in [their repo](https://github.com/equalsraf/neovim-qt).  If you search, you'll find there are already a couple issues about this.

**Comment by webmandman** [comment]
K thanks.
