### ISSUE TITLE
without making config modications after hours of working on nvim, nvim redraw is funky

### ISSUE THREAD

**Issue by webmandman** [neovim/neovim#12548]
- `nvim --version`: v0.4.3
- Operating system/version: Windows 10
- Terminal name/version: Cmder 191012 

### Actual behaviour
When nvim gets screwed like this the movement commands do not entirely work. If I press j the cursor moves down a line but all the lines and the statusline moves up a line. Pressing l will move cursor right until about 13 characters then if I continously press l it will not move any further until about 7 key presses later and the cursor will jump to next line at a random character. 

Then if I close and reopen the file it will render the lines of code a little more mixed up everytime. after opening the file 4 or 5 times I can barely tell what the file is. And somehow parts of lines of code from other buffers are rendered with my current buffer.

![image](https://user-images.githubusercontent.com/991677/85915298-10844680-b7fb-11ea-888d-e4e51e544211.png)
![image](https://user-images.githubusercontent.com/991677/85915527-2e52ab00-b7fd-11ea-80ca-3abf8ad71931.png)

This will happen with nvim even if I open it directly or through CMD. 
![image](https://user-images.githubusercontent.com/991677/85915612-dc5e5500-b7fd-11ea-8dda-092b60c2d7c2.png)

**Comment by m-kru** [comment]
Not 100% sure but this might be terminal issue. I had similar problem with `st` terminal, but never experienced this with [Alacritty](https://github.com/alacritty/alacritty) or [Tilix](https://github.com/gnunn1/tilix).

**Comment by erw7** [comment]
@webmandman From what I've seen in the screenshots, you haven't confirmed that it works with `nvim -u NORC`. Do you have this problem with `nvim -u NORC`? If this problem only happens if you apply your settings, then you need to indicate the minimum setting that will cause this problem.

**Comment by justinmk** [comment]
looks like BCE issue https://github.com/neovim/neovim/issues/9153
