### ISSUE TITLE
omode mapping incorrectly used when playing a macro

### ISSUE THREAD

**Issue by nall** [neovim/neovim#12551]
**Describe the bug**
An omode mapping is errantly used when playing a macro

**vim**
I also filed the following as a [vim issue](https://github.com/vim/vim/issues/6350) as well since it was suggested on IRC to file in both places. I can reproduce this on nvim 0.4.3 and v0.5.0-439-gfb4c7a53c.

The issue is the same except the (incorrect) text that's inserted differs slightly between the two.

**To Reproduce**
1. Create a vimrc:
```
function! MyFunc()
    echom "hi from func"
endfunction

onoremap , :<c-u>call MyFunc()<CR>
```

2. Run vim with `vim -u <rcfile from above>` and in the new buffer and type: `foo([blah])`
3. In normal mode, starting on `f`, record a macro: `ct[,bar<Esc>`
4. Undo that change and then play the macro on the text in step 2 above. When **playing** the macro I instead see a result of:
```
call MyFunc()
blah[blah])
```
(vim results in `:<c-u>call MyFunc()<CR>bar[blah])`)

I expect vim to be in insert mode when it processes the `,` in the macro, but it seems that character is being interpreted in the context of operator pending mode.

**Expected behavior**
I expect the playing the macro to result in `,bar[blah])`. In fact, this is what happens when **recording** the macro.

**Environment (please complete the following information):**
  - neovim versiom: 0.4.3 and v0.5.0-439-gfb4c7a53c.
  - OS: macOS 10.15, CentOS 6.6
  - Terminal: iTerm2

**Additional context**
If I `:ounmap ,`, the macro plays as expected.

**Comment by zeertzjq** [comment]
There is a related note in docs:
```
Keep in mind that the expression may be evaluated when looking for
typeahead, before the previous command has been executed.  For example: >
	func StoreColumn()
	  let g:column = col('.')
	  return 'x'
	endfunc
	nnoremap <expr> x StoreColumn()
	nmap ! f!x
You will notice that g:column has the value from before executing "f!",
because "x" is evaluated before "f!" is executed.
This can be solved by inserting <Ignore> before the character that is
expression-mapped: >
	nmap ! f!<Ignore>x
```
But that workaround doesn't work in this case.
