### ISSUE TITLE
treesitter: parsing a recently added buffer?

### ISSUE THREAD

**Issue by fsouza** [neovim/neovim#12550]
- `nvim --version`: `NVIM v0.5.0-575-g225f0bcd9`

I realize that this may be not the intended use case. There's also a significant chance that I'm just doing the wrong thing, so I'm opening it as feature request x) My use case is to implement "peek definition" using lsp + treesitter. It seems that when trying to parse a new buffer created with bufadd, treesitter can't parse the contents of the file or can't see the contents rather, parser:parse() returns an empty tree.

### Steps to reproduce

Suppose we're parsing a file called `file.go` using the following script:

```lua
local ts_utils = require('nvim-treesitter.ts_utils')
local lang = 'go'

local print_contents = function(bufnr)
  local parser = vim.treesitter.get_parser(bufnr, lang)
  local tree = parser:parse()
  print(vim.inspect(ts_utils.get_node_text(tree:root())))
end

local with_edit = function(filename)
  vim.cmd('edit ' .. filename)
  print_contents(0)
end

local with_bufadd = function(filename)
  local bufnr = vim.fn.bufadd(filename)
  print_contents(bufnr)
end
```

When I call ``with_bufadd('file.go')``, I get the output `{ "" }` (i.e. the tree is empty). When I call `with_edit('file.go')`, I get the file contents (a non-empty tree).

Also, since treesitter caches parsers, if I call `with_edit` after calling `with_bufadd`, I also get an empty tree. To summarize:

- `with_bufadd('file.go')`: empty tree
- `with_edit('file.go')`: non-empty tree
- `with_bufadd('file.go'); with_edit('file.go')`: empty tree twice (due to caching)
- `with_edit('file.go'); with_bufadd('file.go');`: non-empty tree twice (due to caching)

### Actual behaviour

I get an empty parse tree for recently bufadd.

### Expected behaviour

Being able to parse buffers to extract information.

If that's not a supported use case, could `ts_parser_parse_string` get exposed via the Lua API somehow? That way I could nvim_buf_get_lines + feed the string into the parser (which is less efficient, but shouldn't be too bad for this use case).

**Comment by tjdevries** [comment]
Cc @vigoux

**Comment by fsouza** [comment]
Following suggestion from gitter, I tried bufload after bufadd, and that was... weird?

```lua
local with_bufadd_load = function(filename)
  local bufnr = vim.fn.bufadd(filename)
  vim.fn.bufload(filename)
  print_contents(bufnr)
end

with_bufadd_load('file.go');
```

Prints:

```
{ "local ts_utils = require('nvim-treesitter.ts_utils')", "local lang = 'go'", "", "local print_contents = function(bufnr)", "  local parser = vim.treesitter.get_parser(bufnr, lang)", "" }
```

Which is the current lua file, even though the `lang` is hard-coded to `'go'` 🤔

**Comment by vigoux** [comment]
That is indeed weird, I am investigating it and will be in the next few days hopefully. As we have pretty detailed reproducing steps, I think I will be able to get it.

**Comment by vigoux** [comment]
I did a bit of testing and notably removed the `nvim-treesitter` dependency, to use the `sexpr` method instead here is the final script : 
```lua
local lang = 'c'

local print_contents = function(bufnr)
  print(bufnr)
  local parser = vim.treesitter.get_parser(bufnr, lang)
  local tree = parser:parse()
  print(tree:root():sexpr())
end

local with_edit = function(filename)
  vim.cmd('edit ' .. filename)
  print_contents(0)
end

local with_bufadd = function(filename)
  local bufnr = vim.fn.bufadd(filename)
  vim.fn.bufload(filename)
  print_contents(bufnr)
end

with_bufadd("src/nvim/lua/treesitter.c")
```
This version of `with_bufadd` (which is actually your `with_bufadd_load`) seems to work properly. The thing is that it seems that the buffer is not loaded before the call to `bufload`, which might cause problems. In any case, we should report that as an error at least.
