### ISSUE TITLE
Auto-removal of whitespace with BufWritePre causes extra undo change

### ISSUE THREAD

**Issue by justone** [neovim/neovim#12554]
My config has the following line:
```
autocmd BufWritePre * :%s/\s\+$//e
```
It's been in my config for a long time, and originally came from [this tip](https://vim.fandom.com/wiki/Remove_unwanted_spaces). It ensures that there's no trailing whitespace on any lines every time I write the file.

- `nvim --version`: NVIM v0.5.0-576-g7efb302d2
- `vim -u DEFAULTS` (version: ) behaves differently? Yes, Vim 8.2 does not exhibit this bug.
- Operating system/version: Ubuntu 18.04.4 LTS
- Terminal name/version: Git Bash in Windows, connecting to a server
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

File test.txt:
```
one
two
```

Edit the file:
```
nvim -u NORC test.txt
```

Set the above config:
```
:autocmd BufWritePre * :%s/\s\+$//e
```

1. Delete the first line with `dd`
2. Write the file with `:w`
3. Try to undo the deletion with `u`.

Notice that when you hit `u`, the first line does not reappear. You have to hit `u` again. It looks like the BufWritePre introduces a second change in there.

Running `:undolist` shows:
```
number changes  when               saved
     2       2  10 seconds ago       1
```

When all of the above is run with Neovim `v0.4.3`, only one `u` is required to get the first line to come back, and `:undolist` shows:
```
number changes  when               saved
     1       1  7 seconds ago        1
```

### Actual behaviour
An extra undo is required after writing a file when the autocmd is set.

### Expected behaviour
No extra undo is required.

## Additional information

Here's the commit where the behavior changed: a9065a50518ef59351f9d0d32041a991a751653f

I used `git bisect` to find this by marking the `v0.4.3` tag as good, master (7efb302d2) as bad, and going from there.

Thank you for Neovim, it's wonderful.

**Comment by glacambre** [comment]
Can't reproduce on master :tada: .

**Comment by justone** [comment]
I just tried it out with a nightly build, and I confirmed that the bug is gone. Thank you!!
