### ISSUE TITLE
Exponentially slower loading of eruby buffers

### ISSUE THREAD

**Issue by northerner** [neovim/neovim#12562]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: 8.1) behaves differently? Yes, not an issue in Vim.
- Operating system/version: OSX 10.15.4
- Terminal name/version: iTerm2 3.2.6
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
touch test.html.erb
touch test.js

nvim -u NORC
:e test.html.erb
:e test.js
:bn
:bn
:bn
# ...and repeat, by the 20th switch back to the erb buffer you will notice the slow down.
# by the 30th switch you'll be counting the loading time in minutes.

```

### Actual behaviour

Each time switching back to an eruby buffer gets exponentially slower, eventually taking minutes to load after around 25 times. The same line does not cause an issue in Vim, the issue appears specific to NeoVim.

Running the profiler shows the line setting the [path value in the eruby ftplugin](https://github.com/neovim/neovim/blob/87140f234ac1f152f6f273dee5ab1e42c7b1d78b/runtime/ftplugin/eruby.vim#L102) was the cause. Commenting out this line solves this issue. The same line does not cause an issue in Vim, the issue appears specific to NeoVim.

`let &l:path = s:path . (s:path =~# ',$\|^$' ? '' : ',') . &l:path`

### Expected behaviour

Switching back to an eruby buffer should take roughly the same amount of time consistently, not exponentially longer.

Apologies if this should be reported to the `vim-ruby/vim-ruby` project, as this only occurs in NeoVim I thought this was the right place.

**Comment by erw7** [comment]
Probably the reason you don't have a problem with vim is because vim has regular expression changes that have not yet been ported to neovim. Still, the fundamental problem lies in ftplugin of eruby. That's why I created vim-ruby/vim-ruby#419.

**Comment by glacambre** [comment]
Can't reproduce on master :tada: .

**Comment by 9mm** [comment]
I also have this, it is astronomically slow, like you literally can't even scroll with j/k

**Comment by glacambre** [comment]
@9mm What `nvim --version` are you using?

**Comment by 9mm** [comment]
@glacambre 

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"
```

However I notice if i disable treesitter the problem goes away so ill open an issue there.
