### ISSUE TITLE
Disappearing symbols on `J`

### ISSUE THREAD

**Issue by umnikos** [neovim/neovim#12565]
- `nvim --version`: v0.3.4
- `vim -u DEFAULTS` (version: 8.1) behaves differently? Yes
- Operating system/version: Debian 10
- Terminal name/version: Tilda 1.4.1
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

1. Type the following into a new buffer:
```
>
>
```
2. Hover over the first line and press `J`

### Actual behaviour
The buffer becomes this:
```
> 
```
There is a space after the `>`.

### Expected behaviour
The buffer should become this:
```
> >
```

**Comment by clason** [comment]
Can confirm on master; this is due to different default options. If you `:set formatoptions=tcqj` (the neovim default), vim behaves the same.
