### ISSUE TITLE
lua-package-path updates too late, affects `init.lua` with lua plugins.

### ISSUE THREAD

**Issue by ms-jpq** [neovim/neovim#12577]
- `nvim --version`: v0.5.0-2ca8f02

## Actual behaviour:

According to [`the documentation on lua-package-path`](https://neovim.io/doc/user/lua.html#lua-package-path)

`package.path` is updated in accordance with `runtimepath`. But there is an important caveat, `package.path` is not updated immediately after  `runtimepath` update, but seems to be on the "next cycle".

In practice, this means that for plugin managers like `vimplug`, if we call it from lua code, we do not immediately get access to `require("blah_from_plugin").do_x()`, because at that point, only `runtimepath` have been updated, and not `package.path`.

Users will get a giant error listing all the locations that lua tried to look for. It's very confusing.

Now there are two workarounds:

Use `vim.api.nvim_command[[lua require("blah_from_plugin").do_x()]]`. 

Use `vim.schedule` to defer the lua code until `package.path` has caught up to `runtimepath`.

Neither of this are obvious, and the second one has a fatal flaw, `vim.schedule` will defer code execution until after some autocommands have already executed, which is unacceptable if you want to add hooks to those autocommands.

## Expected behaviour:

We should see `package.path` update in lockstep with `runtimepath`, so this doesn't happen.

**Comment by tjdevries** [comment]
I think this no longer applies after #12632, right?

**Comment by kamalmarhubi** [comment]
I think this the same as #11409.

---

@tjdevries as far as I can tell this still happens with the most recent nightly (`NVIM v0.5.0-789-gca7449db4`).

I also settled on the `vim.schedule` trick to delay the affected code to the next tick because it's a bit less visually unappealing than calling the `lua` command from lua.

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/pull/13119

**Comment by kamalmarhubi** [comment]
#13119 was merged, and this seems to work as expected now. @bfredl should it be closed?

(Also thanks for fixing it!)

**Comment by glacambre** [comment]
Yup, let's close this :)
