### ISSUE TITLE
startup: proper ordering between "colors mycolors" and "syntax on"

### ISSUE THREAD

**Issue by jandamm** [neovim/neovim#12573]
- `nvim --version`:
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/config -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/include
Compiled by brew@Mojave.local
- Operating system/version: macOS 10.15.5
- Terminal name/version: Alacritty 0.4.3
- `$TERM`: alacritty

### Steps to reproduce

Clone any theme into ~/.config/nvim/pack/*/opt
`git clone https://github.com/sjl/badwolf $HOME/.config/nvim/pack/theme/opt`
Add `colorscheme badwolf` to your `init.vim`

```sh
nvim --startuptime log.txt +q
cat log.txt
```

### Actual behaviour

The theme is loaded twice:
```
...
006.759  000.019: initialized screen early for UI
022.092  010.053  010.053: sourcing /Users/jandamm/.config/nvim/pack/packager/opt/badwolf/colors/badwolf.vim
023.457  001.008  001.008: sourcing /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/autoload/provider/clipboard.vim
023.496  016.440  005.378: sourcing /Users/jandamm/.config/nvim/init.vim
023.503  000.304: sourcing vimrc file(s)
032.706  000.035  000.035: sourcing /Users/jandamm/.config/nvim/ftdetect/gitconfig.vim
032.812  000.031  000.031: sourcing /Users/jandamm/.config/nvim/ftdetect/plist.vim
032.924  000.042  000.042: sourcing /Users/jandamm/.config/nvim/ftdetect/ruby.vim
033.018  000.018  000.018: sourcing /Users/jandamm/.config/nvim/ftdetect/spelladd.vim
033.105  000.019  000.019: sourcing /Users/jandamm/.config/nvim/ftdetect/terminal.vim
033.194  000.021  000.021: sourcing /Users/jandamm/.config/nvim/ftdetect/tmux.vim
033.372  009.714  009.548: sourcing /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/filetype.vim
033.699  000.194  000.194: sourcing /Users/jandamm/.config/nvim/after/filetype.vim
034.477  000.630  000.630: sourcing /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/ftplugin.vim
035.231  000.553  000.553: sourcing /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/indent.vim
038.904  000.813  000.813: sourcing /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/syntax/syncolor.vim
048.296  010.382  009.569: sourcing /Users/jandamm/.config/nvim/pack/packager/opt/badwolf/colors/badwolf.vim
...
```

### Expected behaviour

I would expect that the theme is only sourced once.
If I replace `colorscheme badwolf` with `let g:colors_name = 'badwolf'` it only gets sourced once and the colors are still applied.
From my tests this also runs the `Colorscheme` autocommand. So I'm not sure why it is loaded twice.
I've tested with vim-plug in this case it is also only sourced once.

 ```
...
005.141  000.016: initialized screen early for UI
005.994  000.211  000.211: sourcing /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/autoload/provider/clipboard.vim
006.036  000.604  000.394: sourcing /Users/jandamm/.config/nvim/init.vim
006.042  000.297: sourcing vimrc file(s)
012.458  000.028  000.028: sourcing /Users/jandamm/.config/nvim/ftdetect/gitconfig.vim
012.757  000.051  000.051: sourcing /Users/jandamm/.config/nvim/ftdetect/plist.vim
012.873  000.043  000.043: sourcing /Users/jandamm/.config/nvim/ftdetect/ruby.vim
012.969  000.020  000.020: sourcing /Users/jandamm/.config/nvim/ftdetect/spelladd.vim
013.056  000.017  000.017: sourcing /Users/jandamm/.config/nvim/ftdetect/terminal.vim
013.141  000.018  000.018: sourcing /Users/jandamm/.config/nvim/ftdetect/tmux.vim
013.289  007.109  006.933: sourcing /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/filetype.vim
013.503  000.094  000.094: sourcing /Users/jandamm/.config/nvim/after/filetype.vim
013.679  000.045  000.045: sourcing /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/ftplugin.vim
013.866  000.037  000.037: sourcing /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/indent.vim
015.823  000.381  000.381: sourcing /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/syntax/syncolor.vim
025.783  010.506  010.125: sourcing /Users/jandamm/.config/nvim/pack/packager/opt/badwolf/colors/badwolf.vim
...
```

**Comment by glacambre** [comment]
It is loaded twice because your theme also [sets g:colors_name](https://github.com/sjl/badwolf/blob/682b5215be013237f39be14954e6979426724a33/colors/badwolf.vim#L44). If you edit the colorscheme to remove this line it'll load only once.

**Comment by jandamm** [comment]
From what I've seen each major theme has this option.
Also removing setting `g:colors_name` within the theme did result in wrong colors since it was sourced too early.

**Comment by gpanders** [comment]
I just noticed this as well. @glacambre why does setting `g:colors_name` have this effect? All of the built-in color schemes set `g:colors_name` so it's a standard practice.

In my case, I'm also seeing the `syncolor.vim` script being sourced twice.

It's also worth noting that Vim does not have this issue.

**Comment by bfredl** [comment]
> The reason this only happens in neovim and not Vim is because neovim sets background to dark automatically. 

hmm "dark" is already the default. If TUI detection detects the same value, it obviously doesn't need to be set again.

**Comment by gpanders** [comment]
Ok I was wrong, it's not being sourced twice because neovim is setting `bg=dark`. It does correctly check to see if `background` has already been set.

I also *can* reproduce in Vim if I use just the right vimrc file.

The following vimrc *does not* reproduce in Vim (i.e. the colorscheme file is only sourced once):

```vim
syntax on
colorscheme my_awesome_colorscheme
```

However, if we switch the ordering then I can also reproduce in Vim (i.e. the colorscheme is sourced twice):

```vim
colorscheme my_awesome_colorscheme
syntax on
```

The second sourcing is happening in [`init_highlight`](https://github.com/neovim/neovim/blob/master/src/nvim/syntax.c#L6354). Essentially, neovim is re-creating that second vimrc file above (the one where `syntax on` is executed after the colorscheme file has already been sourced) inadvertently, causing colorscheme files to be sourced twice on startup.

**Comment by glacambre** [comment]
>why does setting g:colors_name have this effect?

I don't know, here's what the manpage has to say about this:

>					*g:colors_name*
>When a color scheme is loaded (the "g:colors_name" variable is set)
>setting 'background' will cause the color scheme to be reloaded.

My guess is that `g:colors_name` was implemented first and then more work was required for colorschemes to work and `:colorscheme` was implemented.

**Comment by bfredl** [comment]
> The following vimrc does not reproduce in Vim (i.e. the colorscheme file is only sourced once):

    syntax on
    colorscheme my_awesome_colorscheme

Does this work correctly in neovim as well? (i e only sourced once). Then I would consider this to be a documentation issue, mostly.

**Comment by gpanders** [comment]
> Does this work correctly in neovim as well? (i e only sourced once). Then I would consider this to be a documentation issue, mostly.

It does, but I disagree with classifying it as a documentation issue. Neovim enables syntax highlighting automatically and it should do so correctly (without sourcing startup files twice) and telling users to manually add `syntax on` in their startup script to correct for a bug in Neovim is not really a solution.

**Comment by clason** [comment]
Fun fact: if your color scheme is written in Lua (as `foo.lua`) and you set `vim.g.colors_name = 'foo'`, `syncolor.vim` is actually sourced _three_ times.
