### ISSUE TITLE
autocmd CursorHold and CursorHoldI are blocked by timer_start()

### ISSUE THREAD

**Issue by antoinemadec** [neovim/neovim#12587]
:warning: **we only talk about ```CursorHold``` here, but the same bug also applies for ```CursorHoldI```** :warning: 

- `nvim --version`:
```
NVIM v0.5.0-575-g225f0bcd9
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/antoine/src/neovim/build/config -I/home/antoine/src/neovim/src -I/home/antoine/src/neovim/.deps/usr/include -I/usr/include -I/home/antoine/src/neovim/build/src/nvim/auto -I/home/antoine/src/neovim/build/include
```
- `vim -u DEFAULTS` (version: ) behaves differently? **vim 8.2.716 behaves differently**
- Operating system/version: Debian testing up-to-date
- Terminal name/version: alacritty 0.4.3
- `$TERM`: alacritty

### Steps to reproduce using `nvim -u NORC`

``` sh
nvim -u NORC
```

Then, source ```test.vim``` where test.vim is:
```vim
set updatetime=100

autocmd CursorMoved * echom "CursorMoved"
autocmd CursorHold  * echom "CursorHold"

function! s:timer_callback(timer_id)
endfunction

let w:matchup_timer = timer_start(50,
      \ function('s:timer_callback'),
      \ {'repeat': -1})
```

### Actual behaviour
```neovim``` never echoes **CursorHold**, only **CursorMoved**
```vim``` echoes both **CursorHold** and **CursorMoved**

This seems to indicate that ```neovim``` ```CursorHold``` autocmd can be blocked by timers, when ```vim``` uses a different _thread_ to deal with ```CursorHold```?

**Note**: when ```timer_start```'s delay is greater than ```update_time```, ```neovim``` displays **CursorHold**, but it seems more laggy than ```vim```.

### Expected behaviour
I expect ```CursorHold``` execution not to depend on whether ```timers``` are running or not.
Especially when this results in blocking it completely or making it laggy.

Also, thanks a lot  for this amazing editor :heart: 

Thanks,
Antoine

**Comment by antoinemadec** [comment]
Here is a testcase that supports my claim that when `timer_start's` delay is greater than `update_time`, `neovim` displays **CursorHold**, but it seems more laggy than vim.

- ```vim```: **CursorHold** is executed after **CursorMoved** in **105 ms** maximum
- ```neovim```: **CursorHold** is executed after **CursorMoved** in **up to 500 ms**

```vim
set updatetime=100

function s:Start() abort
  let g:start_time = reltimefloat(reltime())
endfunction

function s:End() abort
  let g:end_time = reltimefloat(reltime())
  let g:diff_time = g:end_time - g:start_time
  echom g:diff_time
endfunction

autocmd CursorMoved * call s:Start()
autocmd CursorHold  * call s:End()

function! s:timer_callback(timer_id)
endfunction

let w:matchup_timer = timer_start(101,
      \ function('s:timer_callback'),
      \ {'repeat': -1})
```

**Comment by antoinemadec** [comment]
@tarruda @justinmk , could it be related to this comment in https://github.com/neovim/neovim/blob/master/src/nvim/os/input.c#L95 ?

>   // TODO(tarruda): Cursorhold should be implemented as a timer set during the
>   // `state_check` callback for the states where it can be triggered.

**Comment by Shougo** [comment]
I get the reason.  But it is not easy to fix...

`CursorHold` events check events key is empty.
But timer events put events repeatedly.
So if timer events exists, `CursorHold` events never fired!

**Comment by antoinemadec** [comment]
@Shougo do you know how Vim handles that differently?

**Comment by Shougo** [comment]
> @Shougo do you know how Vim handles that differently?

Yes.  It is different implementation.
Vim does not check the event queue.

**Comment by Shougo** [comment]
I don't recommend to use CursorHold events for neovim.

**Comment by antoinemadec** [comment]
@Shougo , you said:
> I don't recommend to use CursorHold events for neovim.

this is a bummer as a bunch of popular plugin rely heavily on ```CursorHold```, for instance: **coc.nvim**, **tagbar**, **vim-devicons**, **vim-polyglot**, etc.

**Comment by antoinemadec** [comment]
@Shougo , @tarruda , @mroavi , @lambdalisue , FYI, here is the proof that a ```CursorHold``` using timers would fix the performance issues: I used a User autocomand starting a timer on ```CursorMoved```.

```MyCursorHold``` is not blocking anymore:
```vim
set updatetime=100

"--------------------------------------------------------------
" user autocmd
"--------------------------------------------------------------
autocmd CursorMoved * call s:MyCursorHold()

function s:MyCursorHold_Cb(timer_id) abort
  doautocmd User MyCursorHold
endfunction

function s:MyCursorHold() abort
  if exists('g:my_cursorhold_timer')
    call timer_stop(g:my_cursorhold_timer)
  endif
  let g:my_cursorhold_timer = timer_start(&updatetime, function('s:MyCursorHold_Cb'))
endfunction
"--------------------------------------------------------------

autocmd CursorMoved * echom "CursorMoved"
autocmd User MyCursorHold  echom "MyCursorHold"

function! s:timer_callback(timer_id)
endfunction

let w:matchup_timer = timer_start(50,
      \ function('s:timer_callback'),
      \ {'repeat': -1})
```

```MyCursorHold``` is not slow anymore:
```vim
set updatetime=100

"--------------------------------------------------------------
" user autocmd
"--------------------------------------------------------------
autocmd CursorMoved * call s:MyCursorHold()

function s:MyCursorHold_Cb(timer_id) abort
  doautocmd User MyCursorHold
endfunction

function s:MyCursorHold() abort
  if exists('g:my_cursorhold_timer')
    call timer_stop(g:my_cursorhold_timer)
  endif
  let g:my_cursorhold_timer = timer_start(&updatetime, function('s:MyCursorHold_Cb'))
endfunction
"--------------------------------------------------------------
"
function s:Start() abort
  let g:start_time = reltimefloat(reltime())
endfunction

function s:End() abort
  let g:end_time = reltimefloat(reltime())
  let g:diff_time = g:end_time - g:start_time
  echom g:diff_time
endfunction

autocmd CursorMoved * call s:Start()
autocmd User MyCursorHold call s:End()

function! s:timer_callback(timer_id)
endfunction

let w:matchup_timer = timer_start(101,
      \ function('s:timer_callback'),
      \ {'repeat': -1})
```

Unfortunately I am not knowledgeable enough to fix the source code.
I will try to spend some time understanding the code this summer, but I am afraid this might be too complex for me.

**Comment by tjdevries** [comment]
One "hack" could be to do what you did above, but instead of issuing a user autocmd, you could just do `doautocmd CursorHold` I believe.

So then it would make all existing plugins "work"

**Comment by antoinemadec** [comment]
@tjdevries , this would fix the scenario where ```CursorHold``` is **blocked**.
However, in the case where ```CursorHold``` is not blocked, just **slow**, this would trigger all the ```CursorHold``` autocmd twice as many times as expected. Which could also result in a performance hit.

**Comment by Shougo** [comment]
> Unfortunately I am not knowledgeable enough to fix the source code.
> I will try to spend some time understanding the code this summer, but I am afraid this might be too complex for me.

I have read the code to fix the problem, but it is not so easy.

**Comment by antoinemadec** [comment]
Here is a temporary plugin to fix this bug: https://github.com/antoinemadec/FixCursorHold.nvim

**Comment by antoinemadec** [comment]
@erw7 , could we add this as in the 0.5 milestones, or is it too much of a complex bug to be fixed in the 0.5 version?

**Comment by erw7** [comment]
I'm not familiar with this part of neovim, but I suspect it would be difficult to fix this behavior. I suppose it's possible to change it to use a timer, but I don't think that would work any differently than the plugin in https://github.com/neovim/neovim/issues/12587#issuecomment-657314347. I think we might consider adding a plugin like https://github.com/neovim/neovim/issues/12587#issuecomment-657314347 to runtime.

**Comment by comfortablynick** [comment]
I ran into this problem using the built-in LSP and gitgutter or signify. Both plugins work great if I'm not using the LSP, but then it seems the `CursorHold` events rarely fire.

**Comment by antoinemadec** [comment]
@comfortablynick the issue appears when a plugin uses a recurring timer ```start_timer(...,{repeat: -1)}```.

The closer the delay is to your "updatetime" the more likely you are to notice slowdowns on CursoHold auto cmds.

Did you try https://github.com/antoinemadec/FixCursorHold.nvim ?
This will fix your issue.

**Comment by comfortablynick** [comment]
> Did you try https://github.com/antoinemadec/FixCursorHold.nvim ?
> This will fix your issue.

Yes, it seems to have fixed it. Thanks!

**Comment by tjdevries** [comment]
OK, I may see what I can do about this internally since it seems like a bit of fun. If I don't get it done in a month, remind me to un-assign myself :)

**Comment by antoinemadec** [comment]
@tjdevries did you get a chance to take a look at it ? :pray: :raised_hands:

**Comment by tjdevries** [comment]
Ha, yeah! Sorry, I took a look at it but it was indeed quite involved and I've been more focused on the Lua side at the moment.

Perhaps @bfredl has some ideas or we could just do the "hack" version with a timer if people want to enable it.

**Comment by bluz71** [comment]
I can well understand that this is complicated and is down the importance ladder.

I should note, folks like us only made our way here because certain plugins that use CursorHold events don't work without the use of @antoinemadec's [FixCursorHold](https://github.com/antoinemadec/FixCursorHold.nvim) plugin (which works around this issue). In my case it is the [fern](https://github.com/lambdalisue/fern.vim) file explorer plugin that does not work correctly.

For now there is a workaround of sorts. But eventually it would be nice to get this sorted out.

Best regards.

**Comment by alexaandru** [comment]
Just wanted to add that I am here for https://neovim.io/doc/user/lsp.html#vim.lsp.buf.document_highlight()
The documentation currently recommends using `CursorHold` for document_highlight, but it was also recommended above NOT to use that event.

Thank you @antoinemadec for the plugin, it works great :)
And a big thank you to Neovim maintainers for an awesome editor! :) Cheers!

**Comment by antoinemadec** [comment]
@clason @erw7 do you think we could add this in the 0.7 milestone or the backlog ?

**Comment by clason** [comment]
That wouldn't change anything -- somebody needs to make a PR with a fix.

**Comment by Shougo** [comment]
You should avoid to use CursorHold events.
It is hard to fix.

**Comment by bluz71** [comment]
**Lots** of plugins leverage `CursorHold`. That's how most of us encountered this issue, via the plugins we use, not `CursorHold` init scripts we write ourselves.

And it's not just a legacy Vimscript plugins issue.

Even completely modern Neovim **Lua-based** plugins, for example [lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim/blob/master/lua/lsp_signature/init.lua#L613) and [nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring/blob/main/lua/ts_context_commentstring/internal.lua#L94), use `CursorHold`.

`CursorHold` usages can't be wished away. 

Also, I have yet to see a statement from the Neovim core-team that clearly states that plugin authors should stop using `CursorHold`. Until that happens, plugins, both old and new, Vimscript or Lua, will continue to use `CursorHold`.

**Comment by Shougo** [comment]
If it can be fixed, it is very happy for me.
But neovim implementation is not same with Vim.  And I have tried to fix the problem but failed.
I gave up.

**Comment by clason** [comment]
> Also, I have yet to see a statement from the Neovim core-team that clearly states that plugin authors should stop using CursorHold. Until that happens, plugins, both old and new, Vimscript or Lua, will continue to use CursorHold.

PR welcome. Until then, plugin authors should either not rely on CursorHold or apply the straightforward mitigation from https://github.com/antoinemadec/FixCursorHold.nvim.

**Comment by bluz71** [comment]
> > Also, I have yet to see a statement from the Neovim core-team that clearly states that plugin authors should stop using CursorHold. Until that happens, plugins, both old and new, Vimscript or Lua, will continue to use CursorHold.
> 
> PR welcome. Until then, plugin authors should either not rely on CursorHold or apply the straightforward mitigation from https://github.com/antoinemadec/FixCursorHold.nvim.

I am not the target audience, since I have not written a plugin that uses CursorHold. 

However, it probably would be best to inform the wider community via Reddit and Discourse of this position. Most especially since modern Lua plugins, such as lsp_signature and ts-context-commentstring, are still using CursorHold. They are brand spanking new, someone should tell them they are doing it wrong?

I use the workaround plugin since a number of plugins I use do call CursorHold. So I am fine. I am more interested if Neovim core team has a non CursorHold position, if so then that position should be clearly articulated widely, rather than being buried in this discussion where 99% of plugin authors, even Lua authors, would have no idea that CursorHold is now frowned upon.

**Comment by clason** [comment]
There is no "CursorHold position" -- there are issues with that autocommand; the problem is known but a fix is not; on the other hand, there's a simple workaround. I'm also not aware of a wider audience outside this comment thread that considers this a pressing problem. I'm sure there are enough vocal users of plugins that are seriously affected by this that we can assume they are aware of it.

**Comment by Shougo** [comment]
@bluz71 Please read why the fix is hard.

https://github.com/neovim/neovim/issues/12587#issuecomment-654771630

**Comment by Shougo** [comment]
I have tried to fix it again.  But I don't know it is the right fix.

**Comment by bluz71** [comment]
> There is no "CursorHold position"

You now say *there is no CursorHold position*, yet a couple posts up you say *plugin authors should not rely on CursorHold*.

Which is it? No position, or stop using CursorHold?

> I'm also honestly not sure what you are trying to achieve by your comments here.

Read my posts carefully, I am asking whether plugin authors should stop using CursorHold or not, and is that an official position of the Neovim project?

Why am I asking?

Because plugin authors, even Neovim-only Lua authors, are still using CursorHold today as if it is sunshine and roses. They may be blissfully unaware of this issue until issues get lodged against their plugin.

**Comment by bluz71** [comment]
> @bluz71 Please read why the fix is hard.
> 
> [#12587 (comment)](https://github.com/neovim/neovim/issues/12587#issuecomment-654771630)

You misunderstand my posts, I am not asking for anyone to fix this issue. I use the workaround plugin, and that is just fine for me.

I am asking whether **plugin authors** should stop using CursorHold and whether that is official position of the Neovim project itself **since** even the most modern of Neovim plugins are **still** using CursorHold today (which will be a ticking time bomb).

If using CursorHold is now a bad thing then the wider plugin community should be informed of that position (via Reddit and Discourse Neovim communities). For example, Michael Lingelbach - Neovim LSP head honcho, has done just that sometimes with major LSP changes.

At the moment, it appears, there is a massive grey zone of whether CursorHold usage is acceptable or not in Neovim.

**Comment by Shougo** [comment]
My answer is: until the issue is fixed, plugin author should not use CursorHold events.
Unfortunately it is broken now.

**Comment by bluz71** [comment]
> My answer is: until the issue is fixed, plugin author should not use CursorHold events. Unfortunately it is broken now.

Plugin authors, I suspect, mostly would be unaware of that, for example [lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim) and [nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring), both are **very new** Lua plugins that do use `CursorHold`.

Shouldn't they, and most other plugin authors, be made aware of the dangers of relying on `CursorHold`?

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/psa-dont-rely-on-cursorhold-yet/1813/1

**Comment by mjlbach** [comment]
https://neovim.discourse.group/t/psa-dont-rely-on-cursorhold-yet/1813

**Comment by nyngwang** [comment]
Hi, I'm a user of [windwp/windline.nvim](https://github.com/windwp/windline.nvim/), could you guys experts help me check that whether my issue is related to this? https://github.com/windwp/windline.nvim/issues/34

**Comment by nyngwang** [comment]
> Here is a temporary plugin to fix this bug: https://github.com/antoinemadec/FixCursorHold.nvim
> 
> * fixes slowdowns and untriggered events
> * add `g:cursorhold_updatetime` variable to leave `updatetime` untouched (and avoid unnecessary swap writes)
> 
> The plugin also makes sure not to fire those event twice.

@antoinemadec Your awesome plugin resolves my issue! So I think I can confirm myself my previous comment.
