### ISSUE TITLE
How to configure LSP diagnostic information prompt, color, multi-line display, floating display, etc.?

### ISSUE THREAD

**Issue by LuoZhongYao** [neovim/neovim#12585]
I read lsp.txt and can't figure out how to configure it at all.
What is `LspDiagnosticsError`, `LspDiagnosticsErrorSign`, `LspDiagnosticsErrorFloating`, etc., how to set it, and where is it set

**Comment by tjdevries** [comment]
The ones without `Sign` are highlight groups.

The one with `Sign` are signs.

You can modify them with the `highlight` command / `sign_define` commands (if I remember correctly).

```
    sign define LspDiagnosticsErrorSign text=E texthl=LspDiagnosticsError linehl= numhl=
```

If there's a better way to describe that, please let me know and we can probably add some better documentation there to point to the right places.
