### ISSUE TITLE
Benchmark nvim

### ISSUE THREAD

**Issue by dm17** [neovim/neovim#12589]
This seems like a popular text editor benchmark - perhaps you could provide values for nvim?
https://github.com/jhallen/joes-sandbox/tree/master/editor-perf

**Comment by chrisbra** [comment]
This is nothing that requires the developers here to do. You can do it and provide the numbers, not?

**Comment by dm17** [comment]
Ya sure. Just figured this would be a good place to mention it... Always makes it easy to find in Google - and I googled for the benchmarks a few ways, and I bet people already have them to just paste here. Not a concern; just curious.

**Comment by teto** [comment]
thanks for the benchmark, overall nvim should behave like vim but feel free to add anentry in case we regressed. Once we have better treesitter support, highlighting should improve though.
