### ISSUE TITLE
Some keys don't work...

### ISSUE THREAD

**Issue by Mechap** [neovim/neovim#12582]
First of all I have a french azerty keyboard. When in edit mode I want to write '#' or '{' I don't get the expected result. I get 3 and 4.

**Comment by glacambre** [comment]
I'm using a french azerty keyboard too and everything works as expected. Please fill the [issue template](https://github.com/neovim/neovim/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) - we won't be able to help otherwise.

**Comment by Mechap** [comment]
Well apparently the bug appears only with the terminal version of nvim. My terminal might be the origin of the problem.
Also, I'll try to use the issue template next time.
