### ISSUE TITLE
Cannot escape " in treesitter queries

### ISSUE THREAD

**Issue by theHamsta** [neovim/neovim#12595]
- `nvim --version`:
```
➜ nvim --version
NVIM v0.5.0-bd5f0e969
Build type: Release
LuaJIT 2.0.5
Compilation: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200704-130349-1xlbcrp/build/config -I/tmp/neovim-20200704-130349-1xlbcrp/src -I/home/linuxbrew/.linuxbrew/include -I/tmp/neovim-20200704-130349-1xlbcrp/deps-build/include -I/usr/include -I/tmp/neovim-20200704-130349-1xlbcrp/build/src/nvim/auto -I/tmp/neovim-20200704-130349-1xlbcrp/build/include
Compiled by stephan@stephan-Z87-DS3H

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/HEAD-bd5f0e9_1/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
 n/a
- Operating system/version:
Ubuntu 20.20
- Terminal name/version:
```
➜ konsole --version
konsole 20.07.70
```
- `$TERM`:
```
xterm-256color
```

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Then evaluate
:lua vim.treesitter.parse_query('c', '((_) @foo (strip! foo "^\"*"))')
```
(I know that `strip!` is not supported yet)
```
:lua vim.treesitter.parse_query('c', '((_) @foo (strip! foo "^.*"))')
```
would work.

The real life example I tried was (for python)
```scheme
((function_definition
  name: (identifier) @definition.function
  body: (block (expression_statement (string) @definition.doc)?)) @scope
 (strip! @definition.doc "^['\"\s]*|['\"\s]*$)"))
```

### Actual behaviour
Neovim complains about invalid syntax whenever `\"` is present.

### Expected behaviour
Neovim accepts all queries that are accepted by  https://tree-sitter.github.io/tree-sitter/playground

This seems to be somehow related to https://github.com/neovim/neovim/blob/bd5f0e9695cb21c8b97f844ce21432ee8d06b7ed/runtime/lua/vim/treesitter.lua#L133 (note `vim.fn.escape`)

**Comment by theHamsta** [comment]
A hacky solution would be to replace `\\"` by `\"` after `vim.fn.escape(query,'\\')`. A clean solution should probably do the `vim.fn.escape(query,'\\')` thing in `check_magic` instead of before passing it to the tree-sitter runtime.

**Comment by theHamsta** [comment]
@vigoux I was about to close this but the problem still seems to be in the code just got moved to different file. I suppose  `vim.fn.escape` should not be applied to the whole file but only to before feeding the predicate to the regex functions, right?

I am not 100% sure since I made this issue a few months ago. So it would be good if you could check this.

**Comment by theHamsta** [comment]
Also, the escape should probably only be applied to vim-match, since it was only a hack for vim-regexes to behave kind of normal.

**Comment by vigoux** [comment]
> @vigoux I was about to close this but the problem still seems to be in the code just got moved to different file. I suppose `vim.fn.escape` should not be applied to the whole file but only to before feeding the predicate to the regex functions, right?

Yeah I guess that's right
