### ISSUE TITLE
With virtualedit=all, pasting a block from visual-block may cause the cursor to be off-by-one.

### ISSUE THREAD

**Issue by hugomg** [neovim/neovim#12616]
- `nvim --version`: I observed the bug on v0.4.3 and on the current master (v0.5.0-590-gb39edb5b6)
- `vim -u DEFAULTS` behaves differently? The bug is also present in VIM 8.2
- Operating system/version: Fedora 32
- Terminal name/version: GNOME Terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

With the following text in the buffer:

    QWERTY
    ASDFGH

Follow these steps:

1. Enable virtualedit with `:set virtualedit=all`
2. Place the cursor on top of Q
3. Enter visual-block mode with `Ctrl-v`
4. Place the cursor on top of D, selecting QWEASD.
5. Cut the selection with `d`.
6. Move cursor anywhere inside the line. For example, on top of R, T, or Y.
7. Paste with `P`.

### Actual behaviour

After pasting, the cursor is placed on top of W.

### Expected behaviour

After pasting, the cursor should be placed on top of Q. 

### Additional information

If virtualedit is disabled (which is the default) then the cursor will always be end up at the start of the pasted text, on top of Q.

If we use virtualedit=all and we move the cursor off to the side before pasting, taking advantage of the virtualedit feature, then the cursor also goes to the correct place, on top of Q. However, if we use virtualedit=all and paste the block inside the existing line then the cursor ends up one character to the right of where it should be.

This bug also affects the \`\[ mark. It points to the same place as the cursor, which sometimes is off-by-one.

**Comment by hugomg** [comment]
Should I also report this bug to upstream Vim? I don't know what is the etiquette around reporting the same bug in more than one place.

**Comment by chrisbra** [comment]
I have a look and post a patch to vim.

**Comment by hugomg** [comment]
Thanks! I can confirm that the proposed fix appears to solve the problem on my machine too,

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/12611
