### ISSUE TITLE
LSP: notify the user when the language server has crashed

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#12610]
- `nvim --version`: NVIM v0.5.0-583-g7b529e791 / LuaJIT 2.1.0-beta3
- language server name/version: efm-langserver (https://github.com/mattn/efm-langserver/commit/0b64dd8f71a63599c7ac0267c0c31d1c8497cc2c)
- Operating system/version: Linux Debian (Buster)

LSP log: https://gist.github.com/aktau/1c1ef881c0afb41d9808a821263ea1d7

### Steps to reproduce using `nvim -u NORC`

This basically applies to any language server that can crash. In my case it's due to https://github.com/mattn/efm-langserver/issues/57. A few times now when trying to resolve other issues with nvim-lsp I was confused because the language server had just crashed.

### Actual behaviour

When the language server crashes I get no notification that it happened, and am left to wonder why I get no diagnostics or anything else anymore.

### Expected behaviour

Either:

  1. A notification that the language server has crashed. Or,
  2. A notification that the language server has crashed (to allow filing bugs for the language server owner) followed by an automatic restart of the language server. (In my case, this would be preferable, but I'm not sure if this is the case for every language server. It could be a configurable option.)

It would be helpful (but not required), to add a note to the notification such that the user can file a better bug report (with logs) to the langserver.

**Comment by teto** [comment]
I dont think this should be a regular check but a buffer specific checkhealth could check for a process with the server name etc.

**Comment by tjdevries** [comment]
First guess is we could do this `on_exit` for the job. I can try and check this out at some point.
