### ISSUE TITLE
[RFC] How should we tackle treesitter queries ?

### ISSUE THREAD

**Issue by vigoux** [neovim/neovim#12619]
I am cheating as this is not really a feature request... But anyway.

I recently have been working quite a bit on treesitter integration, and we are making progress in @bfredl roadmap.
The big milestone I want to achieve is builtin, and smooth, syntax highlighting using treesitter.
To achieve that we need to have a way to write and use highlight queries.

Here is some proposals we discussed with @tjdevries :

- Pure `lua` query generation : it might be a bit tricky to do complex queries (tested by @kyazdani42 [here](https://github.com/nvim-treesitter/highlight.lua) )
- Plain `scheme` : it might be a bit tricky for users to extend the queries (is tested [here](https://github.com/nvim-treesitter/nvim-treesitter) )
- Hybrid `fennel` : here comes the debate, it requires to include the fennel compiler, BUT it might be better to build customizable queries without to much effort (not tested anywhere, just an idea, and a gut feeling).

I think I exposed everything.

**Comment by norcalli** [comment]
I had trouble finding an example of how to queries were built with lua, but I suspect it could be done in a nice way given how simple most queries are. Do you have a good example of that one?

scheme is the default that our tree sitter can support via `vim.treesitter.parse_query(lang, query)`.

Is there actually a way to make queries directly without making scheme to pass to parse_query?

**Comment by vigoux** [comment]
The only way for a query to be used by treesitter is through parsing scheme-like things.
The question is how we generate them, either by hand (using scheme files), by direct Lua, or using fennel.
I thought that there was a example in highlight.lua, I will try finding that, and in any case, I will provide some examples of all of the three ways (no time now though...)

**Comment by theHamsta** [comment]
My opinion: stay with the scheme queries as long as we have a solid foundation using tree-sitter. We do not have to maintain it as long as we just want to have the basics, it is used by atom users, emacs users and us. It is still extendable by some adventurers that want to explore new use cases.

If we have tree-sitter integrated in stable Neovim and we don't  have the maintenance burden we can add our own magic. We have to be ensure that each feature that deviates from standard tree-sitter has to have people that maintain it on a long run. I would see priority in making tree-sitter stable and this should be easiest by sharing maintenance effort with communities from other editors.

**Comment by Olical** [comment]
Probably not super relevant to the tree-sitter side, but I've been deeply integrating Fennel into my Neovim via [Aniseed](https://github.com/Olical/aniseed) for a while now. All of my nvim configuration (dotfiles) and plugins ([Conjure](https://github.com/Olical/conjure)) are written in Fennel, I can highly recommend it as an area of investigation :smile:

The fennel compiler is a single Lua module (file) which makes embedding it reaaaaaly smooth, for what it's worth.

**Comment by vigoux** [comment]
For the record and before closing this issue : we ended up using plain scheme together with some additional preprocessing to include and extend other queries.
