### ISSUE TITLE
Cursor color doesnot change in kitty if :hi Cursor gui=reverse and/or cterm=reverse is set

### ISSUE THREAD

**Issue by subnut** [neovim/neovim#12627]
- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?  
No
- Operating system/version:
Arch linux ( Kernel: 5.7.7-arch1-1 )
- Terminal name/version:
kitty 0.18.1
- `$TERM`:
xterm-kitty
### Steps to reproduce using `nvim -u NORC`
[Follow the steps mentioned here in the neovim wiki](https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-color-in-the-terminal)

### Actual behaviour
Cursor color remains same, no matter what
### Expected behaviour
Cursor color changes on INSERT and NORMAL modes (idk, the linked wiki says so..)

**Comment by erw7** [comment]
@subnut What happens if you run neovim after `unset VTE_VERSION`?

**Comment by subnut** [comment]
@erw7 no effect. BTW, I dug a little more, and saw that it DID change when I ran `:hi Cursor cterm=NONE gui=NONE`

**Comment by subnut** [comment]
I am closing this one, and opening new one with the new details

**Comment by subnut** [comment]
For those coming here, the new issue is #12631

**Comment by subnut** [comment]
@erw7  please checkout the new issue, #12631
