### ISSUE TITLE
Cursor color does not change in kitty

### ISSUE THREAD

**Issue by subnut** [neovim/neovim#12626]
- `nvim --version`:
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

**Comment by kantord** [comment]
Hi @subnut, was your issue resolved? If so, how?

**Comment by subnut** [comment]
Hi @kantord, I solved my problem by using the following in my `init.vim` -
```vim
set guicursor=n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20-Cursor
aug kitty_cursor
    au!
    au Colorscheme * set guicursor=n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20-Cursor
aug END
```

**Comment by subnut** [comment]
Oh and do check the `Cursor` highlight group (`:hi Cursor`) of the colorscheme you are using. If it is simply set to `cterm=reverse gui=reverse`, then too the Cursor won't change color. This behaviour is mentioned in the vim docs somewhere.
I set `:hi Cursor guibg=fg guifg=bg` for those colorschemes.

**Comment by kantord** [comment]
Nice! Thank you, @subnut

**Comment by Juniokoi** [comment]
To use this with native nvim functions use this:
`vim.opts.guicursor = "n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20-Cursor"`
