### ISSUE TITLE
On GNOME/Wayland, clipboard=unnamed causes the app name to flicker

### ISSUE THREAD

**Issue by hugomg** [neovim/neovim#12622]
- `nvim --version`: v0.4.3 and  v0.5.0-592-ga695da7d3
- `vim -u DEFAULTS` (version: 8.2) behaves differently? Doesn't flicker. However, my vim doesn't have the xterm_clipboard option enabled so I don't know if this is an apples to apples comparison
- Operating system/version: Fedora 32
- Terminal name/version: GNOME Terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Use GNOME/Wayland with wl-clipboard installed (wl-copy / wl-paste).
2. Enable Neovim's clipboard integration with `set clipboard=unnamed` or `set clipboard=unnamedplus`
3. Use a command that uses the clipboard, such as `x`, `dd`, `yy`, or `P`

### Actual behaviour

The app name flickers every time the clipboard is used. In the following video I am pressing `x` a bunch of times.

![flickering2](https://user-images.githubusercontent.com/1452192/87227631-b8a91c00-c372-11ea-9e09-91f471039938.gif)

When it is flickering the app name becomes "Unknown"

![mpv-shot0002](https://user-images.githubusercontent.com/1452192/87227678-0cb40080-c373-11ea-935e-7c8fac645470.jpg)

### Expected behaviour

The app name should not flicker when the clipboard is used.

The app name only flickers if I use Wayland. If switch to a X.org session with xclip as the clipboard provider then it does not flicker.

**Comment by hugomg** [comment]
Looking at it again, I think this might be a gnome-terminal or wl-copy bug. The flickering also happens if I run wl-copy and wl-paste by themselves on the terminal.

**Comment by glacambre** [comment]
This is a wayland issue. There is no way for a program that doesn't have a window to access the clipboard, so wl-copy has to create a window each time it needs to copy/paste something. This results in the focus being changed and your app bar reflecting that.

There is nothing neovim/wl-copy maintainers can do about this unfortunately :/.

**Comment by hugomg** [comment]
Thanks for the clarification, Ghjuvan.

**Comment by ChristianChiarulli** [comment]
In case anyone runs my specific issue with this.

If you disable the banner in netrw and focus netrw, the title will flicker infinitely. 

vim.g.netrw_banner = 0 -- remove netrw banner

**Comment by stephane-klein** [comment]
> If you disable the banner in netrw and focus netrw, the title will flicker infinitely.

I have also this bug: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4938

**Comment by stephane-klein** [comment]
See also https://github.com/neovim/neovim/issues/9806
