### ISSUE TITLE
neovim hangs after starting build-in file explorer

### ISSUE THREAD

**Issue by atifchy** [neovim/neovim#12628]
- `nvim --version`:NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
- `vim -u DEFAULTS` (version: ) behaves differently? Yes 
- Operating system/version:Linux archlinux 5.7.7-zen1-1-zen
- Terminal name/version:konsole/20.04.3
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`
neovim hangs after running :Explorer, :Lex while editing a file.

### Actual behaviour
:Explore command hangs neovim. I mean neovim hangs when i try to open the build-in file explorer while editing a file.
### Expected behaviour
File explorer should open normally. It shouldn't hang neovim.

**Comment by Shougo** [comment]
It is reproduce-able with NORC?
Why don't you upload the vimrc to reproduce?

**Comment by atifchy** [comment]
yes it happens with nvim-u NORC

my vimrc:--



set nocompatible                             " be iMproved, required

" Plugins
call plug#begin('/home/atif/.vim/plugged')   "required
" alternatively, pass a path where VimPlug should install plugins
"call plug#begin('~/some/path/here')
        
	" Tools
	Plug 'tpope/vim-fugitive'
	Plug 'vim-airline/vim-airline'
	Plug 'vim-airline/vim-airline-themes'
	Plug 'ryanoasis/vim-devicons'
	"Plug 'Yggdroot/indentLine'
	"Plug 'mhinz/vim-startify'
	"Plug 'airblade/vim-gitgutter'
	
	" Colorscheme
	Plug 'morhetz/gruvbox'
	"Plug 'gruvbox-community/gruvbox'
	"Plug 'NLKNguyen/papercolor-theme'
	"Plug 'kristijanhusak/vim-hybrid-material'
	"Plug 'joshdick/onedark.vim'
	Plug 'ap/vim-css-color'
	"Plug 'norcalli/nvim-colorizer.lua'

" All of your Plugs must be added before the following line
call plug#end()                              " required

" Brief help
" :PlugInstall    - installs plugins; append `!` to update or just :PlugUpdate
" :PlugClean      - confirms removal of unused plugins; append `!` to auto-approve removal
" :PlugUpgrade    - Upgrade vim-plug itself
" :PlugStatus     - Check the status of plugins
" :PlugDiff       - Examine changes from the previous update and the pending changes
" :PlugSnapshot   - Generate script for restoring the current snapshot of the plugins

" Put your non-Plug stuff after this line

" General Settings
set splitbelow splitright
set mouse=a                                  " enable mouse 
set number                                   " always show line number
set showmatch                                " set show matching parenthesis
set ignorecase                               " ignore case when searching
set smartcase                                " ignore case if search pattern is all lowercase, 
                                             "     case-sensitive otherwise
set cursorline                               " highlight cursor line
set clipboard=unnamedplus                    " copy paste between vim and everything else
set inccommand=nosplit
"set updatetime=100

" Color Settings
set t_Co=256
let g:gruvbox_italic=1
let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_invert_selection = 0           " selected texts are highlighted in white
colorscheme gruvbox
"set background=dark	                      " set background color
"hi Normal ctermbg=NONE guibg=NONE            " transparent background

" Air-line configuration
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

" Key Bindings
map <C-e> :Lex <bar> vertical resize 30 <CR>
map <C-r> :source /home/atif/.config/nvim/init.vim<CR>

" nvim config
if has('nvim')
    autocmd TermOpen term://* startinsert
endif

**Comment by Shougo** [comment]
> yes it happens with nvim-u NORC

Really?  If so, why I cannot reproduce the problem?

> neovim hangs after running :Explorer, :Lex while editing a file.

* `nvim -u NORC`
* `:Explorer`
* nothing to hang

Please describe more detailed for everyone.
And please test it on other environments like Docker.

**Comment by Shougo** [comment]
> nvim --version:NVIM v0.4.3

Please test the latest version of neovim.

**Comment by atifchy** [comment]
@Shougo the hang issue isn't happening on neovim 5.0

**Comment by Shougo** [comment]
If so you should use the latest version of neovim.
The issue should be closed.

**Comment by pcewing** [comment]
@AtifChy Hey, I know this is closed but out of curiosity, were you running in a VM? I think I experienced a similar hang in v0.4.4 where running the following would hang about 30% of the time:
```
cd ~ && nvim .
```

I couldn't reproduce it on my bare metal Linux box but only in a VirtualBox guest so I'm curious if that has something to do with it.

Anyways, just grabbed the v0.5.0 nightly and I can't reproduce it on that version anymore.
