### ISSUE TITLE
inccommand:  option to show old and new substitute text

### ISSUE THREAD

**Issue by zer09** [neovim/neovim#12635]
- `nvim --version`: NVIM v0.5.0-582-g2844cd54d
- Operating system/version: Linux pop-os 5.4.0-7634-generic
- Terminal name/version: alacritty 0.4.3
- `$TERM`: xterm-256color

Feature request to add option to the `inccommand` to show both the old and new text in substitute.
For example I have a sentence "This is a short paragraph", then I want to replace "short" to "shortest".
Then if I do `:%s/short/shortest` it will show both the old and new text before applying it or while typing for the new text until I press enter.

We could have seperator for the old and new like `short|shortest` or set different color for the old and the new, something like `<red>short</red><blue>shortest</blue>` that's look like on spacemacs.

**Comment by pta2002** [comment]
I'd love to implement this if I could get some pointers!

**Comment by justinmk** [comment]
Nvim 0.8 now supports user/plugin implementation of previewable ('inccommand') commands: `:help :command-preview`

A builtin option is out of scope.
