### ISSUE TITLE
LSP: Method not found: didClose

### ISSUE THREAD

**Issue by Shatur95** [neovim/neovim#12633]
- `nvim --version`: NVIM v0.5.0-593-g1ca67a73c
- language server name/version: Godot 3.2.2
- Operating system/version: Arch Linux

<details>
<summary>nvim -c ":checkhealth nvim nvim_lsp"</summary>

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: gdscript: configuration checked.
</details>

[lsp.log](https://pastebin.com/h5YzQTMV) (Godot produces very verbose log, so I uploaded to pastebin)

### Steps to reproduce

```
nvim
# Open any gdscript file
:bd
```

### Actual behaviour

I got errors:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:417: attempt to concatenate local 'result_id' (a nil value)
```
```
LSP[gdscript]: Error NO_RESULT_CALLBACK_FOUND: {
  error = {
    code = -32601,
    message = "Method not found: didClose"
  },
  id = vim.NIL,
  jsonrpc = "2.0
```

![изображение](https://user-images.githubusercontent.com/22453358/87355656-6716b200-c569-11ea-8d02-77b8dbe9cf32.png)

### Expected behaviour

Buffer closed without errors.

**Comment by jivthesh** [comment]
@Shatur95 can i work in this issue . will i get guidance i am a beginner

**Comment by Shatur95** [comment]
@jivthesh, yes, of course!

**Comment by jivthesh** [comment]
@Shatur95 can u tell me hw to start working in this .do we have any sort of communication like slack or discord?

**Comment by Shatur95** [comment]
There is [a wiki page](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md) for it.

**Comment by tjdevries** [comment]
Hi @jivthesh :smile: Thanks for wanting to work on the issue.

We primarily use https://gitter.im/neovim/neovim to communicate outside of issues & PRs.

I can help you with getting started. Do you have any particular questions?

**Comment by jivthesh** [comment]
@tjdevries okay

**Comment by tjdevries** [comment]
(Just so you know -- I'm out of town this weekend so I'm not really responding to anything. Ping me again on Tuesday or Wednesday this week and I can help)

**Comment by vishKurama** [comment]
Is @jivthesh still working on it? Or I could pick it up?

**Comment by justinmk** [comment]
No repro steps. Not going to install every LSP to debug this. 

Send a PR or a failing test case in the [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.

**Comment by Shatur95** [comment]
> No repro steps.

But I provided steps to reproduce.

> Not going to install every LSP to debug every LSP issue.

Should report issues only for LSP that used by Neovim maintainers?

> a failing test case in the lsp_spec.lua, which has code to setup a fake LSP server to simulate various scenarios.

It is possible, but first you need to understand what is causing the error. And for this need to install the LSP server that calls it. It looks like @vishKurama was interested in it. Could you reopen the issue?

**Comment by Shatur95** [comment]
@vishKurama, this is interesting... So, you have LSP completions for GDScript, but do not see any errors after `:bd`?

**Comment by vishKurama** [comment]
> @vishKurama, this is interesting... So, you have LSP completions for GDScript, but do not see any errors after `:bd`?

Oh!! Sorry, I am dumb! I don't have lsp completion

**Comment by vishKurama** [comment]
let me try with it!

**Comment by Shatur95** [comment]
Yes, you need to setup LSP for it. Check out [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig#gdscript). You need to put `require'nvim_lsp'.gdscript.setup{}` to your vimrc.

**Comment by vishKurama** [comment]
I am using init.vim for my configuration, I should set this up in that right?

**Comment by Shatur95** [comment]
No, just put mentioned line from the above to your init.vim :)

**Comment by vishKurama** [comment]
I installed the nightly version and set up lsp completions, but `:bd` works perfectly fine, no errors thrown

nvim -c ":checkhealth nvim nvim_lsp"
<details>
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: gdscript: configuration checked.
</details>

**Comment by Shatur95** [comment]
You opened Godot (and leaved it open), then opened `.gd` files in Neovim, correct?

**Comment by vishKurama** [comment]
Umm.. no 😅!

**Comment by Shatur95** [comment]
Please, read the issue description.

**Comment by dcampos** [comment]
I've found out this is caused by Godot not implementing the `textDocument/didClose` method. As per the LSP documentation, it should be implemented.

For now I'm using the following code to prevent this error from happening. It's a bit ugly but gets the job done.

```lua
require 'lspconfig'.gdscript.setup {
    on_attach = function (client)
        local _notify = client.notify
        client.notify = function (method, params)
            if method == 'textDocument/didClose' then
                return
            end
            _notify(method, params)
        end
    end
}
```
