### ISSUE TITLE
hi cursor gui=reverse doesnot work in kitty

### ISSUE THREAD

**Issue by subnut** [neovim/neovim#12631]
- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
No. (We need to `:set termguicolors` for this issue)
- Operating system/version:
Arch linux ( Kernel: 5.7.7-arch1-1 )
- Terminal name/version:
kitty 0.18.1
- `$TERM`:
xterm-kitty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set termguicolors
:hi Normal guifg=red guibg=white
:hi clear Cursor``
:hi Cursor gui=reverse
:set guicursor=n-v-c:block-Cursor/lCursor
<Insert some text into the buffer>
<move cursor over the text in NORMAL mode>

```
### Actual behaviour
Cursor is white, text underneath the cursor is black (i.e. the default configuration of kitty)
### Expected behaviour
Cursor is red, text inside it is white.

**Comment by subnut** [comment]
For the record, `unset VTE_VERSION` has no effect.

**Comment by erw7** [comment]
The current implementation is as follows:

https://github.com/neovim/neovim/blob/1ca67a73c0ba680eb8328e68bea31f839855dd29/src/nvim/tui/tui.c#L1077-L1080

Therefore, the behavior when you set the cursor color to `gui=reverse` depends on the cursor color by default on the terminal. I think it's probably possible to set the cursor color to reverse of `highlight Normal`. But if your desired behavior is to reverse the color of the cell, I think it would be hard to implement that in neovim unless the terminal supports it. Even if your desired behavior is the former, you can still use `guibg` as a workaround. As such, I believe it is a low priority for implementation.

I also noticed that the `guifg` settings for the cursor colors are not applied, but I think that this may be difficult to fix as well.

**Comment by erw7** [comment]
The `:h 'guicursor'` is described as follows. So, unfortunately, this is a specification, not a bug.

> inverse/reverse and no group-name are interpreted as "the host terminal default cursor colors" which usually invert bg and fg colors.

**Comment by teto** [comment]
as mentioned by @erw7, nothing we can do. There was another issue where someone mentioned we can hide the terminal cursor and blink cells instead to emulate a cursor (works only for block mode though).
