### ISSUE TITLE
Bug report: inccommand preview only show one match in one sentence

### ISSUE THREAD

**Issue by ryuta69** [neovim/neovim#12630]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?: same
- Operating system/version: MacOS Catalina
- Terminal name/version: iTerm 3.3.12
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:set inccommand=split

/test

## inside a textfile of contents like below
## test test test
## test

```

### Actual behaviour
Inccommand preview only shows 1 match inside 1 sentence.

<img width="671" alt="ss 3" src="https://user-images.githubusercontent.com/41639488/87256757-5fef9580-c4d0-11ea-9240-6b7bb0981e10.png">

### Expected behaviour
Inccommand preview show matches as much as search hits in sentences.

**Comment by KillTheMule** [comment]
This is intended behavior. If you want all matches on a line, use the `g` flag.

**Comment by ryuta69** [comment]
@KillTheMule 
Oh my bad. Thank you very much for telling me.
