### ISSUE TITLE
Invalid `old_byte_size` parameter on buffer updates for `~`

### ISSUE THREAD

**Issue by vigoux** [neovim/neovim#12645]
## Steps to reproduce using `nvim -u NORC`
Using the following lua file :
```lua
-- test.lua
local function cb(...)
  print(vim.inspect({...}))
end

vim.api.nvim_buf_attach(0, true, {on_lines = function(...) cb(...) end})
```
```
nvim -u NORC test.lua

:luafile %
:normal ~
```

### Actual behaviour
It prints `{ "lines", 1, 23, 1, 2, 2, 0 }`

### Expected behaviour
It should print `{"lines", 1, 23, 1, 2, 2, lenght_of_the_changed_line}`.

**Comment by vigoux** [comment]
After looking a bit into this, the invalid parameter comes down to `buf->deleted_bytes` not being updated when using `~`, I don't know if that's intentional or not though.

**Comment by pierreglaser** [comment]
Thanks for investigating @vigoux. Is it specific to `~`?

**Comment by vigoux** [comment]
Looks like the same error happens for `r` too.

**Comment by pierreglaser** [comment]
I remember i could make `tree-sitter` freeze using `o`. Do we expect the last item of the table to be 0 in this case?

**Comment by vigoux** [comment]
I wouldn't tbh. But I don't know either what this value should be

**Comment by vigoux** [comment]
@pierreglaser I can't reproduce the `o` issue, do you have an exemple for that ?

**Comment by pierreglaser** [comment]
Yes, I provided a small reproducer here: https://github.com/neovim/neovim/issues/11944#issuecomment-615961441. Feel free to try it out.
