### ISSUE TITLE
:echo has("wsl") always reports 0

### ISSUE THREAD

**Issue by mangelozzi** [neovim/neovim#12642]
## Context

Was reading `:help feature-list`, and wish to use the `wsl` feature in `MYVIMRC`
```
*feature-list*
List of supported pseudo-feature names:
wsl		WSL (Windows Subsystem for Linux) system
```

- `nvim --version`:
```
:ver
NVIM v0.5.0-563-ge628a05b5
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict
-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto
-DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/b
uild/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/bu
ild/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/n
eovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-c5758e75-4445-4564-8946-810c98499a51
```
- Operating system/version: Windows 10 running WSL2 Ubuntu 20.04
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Start Neovim in WSL
2. Issue the command: `:echo has("wsl")`

### Actual behaviour
Prints 0

### Expected behaviour
Prints 1

I opened Neovim in windows and tried, and it also printed 0.

**Comment by erw7** [comment]
@michael-angelozzi  Your neovim look like nightly. Unfortunately, `has('wsl')` doesn't return 1 unless you build on wsl. Therefore, the release page nightly will not return 1 for `has('wsl')`.

Ref. #7330.

**Comment by erw7** [comment]
I think you can use the following function to determine if it is `WSL` or not.

```vim
function! Is_WSL() abort
  let proc_version = '/proc/version'
  return filereadable(proc_version)
        \  ? !empty(filter(
        \    readfile(proc_version, '', 1), { _, val -> val =~? 'microsoft' }))
        \  : v:false
endfunction
```

**Comment by michael-angelozzi** [comment]
Thanks erw7, that does seem like the way to go as recommended by microsoft too. Will use that thanks. I am working on a plugin to fill some of the pitfalls of using Vim/Neovim under WSL.

> @michael-angelozzi Your neovim look like nightly. Unfortunately, `has('wsl')` doesn't return 1 unless you build on wsl. Therefore, the release page nightly will not return 1 for `has('wsl')`.
> 
> Ref. #7330.

I think I must have the wrong understanding... are what you saying only a version built in WSL will report 1 to having WSL? Cause the people with WSL will generally install the normal Ubuntu/Debian release, and hence will report no to has("wsl").

**Comment by erw7** [comment]
> I think I must have the wrong understanding... are what you saying only a version built in WSL will report 1 to having WSL?

Your understanding is correct. So I don't think `has('wsl')` is useful to most people.

I think it's possible to replace `has('wsl')` with a C implementation of the https://github.com/neovim/neovim/issues/12642#issuecomment-658944841 method, but I don't think it's worth bothering to implement in C what vimL or lua can implement in a few minutes. IMO The use of `has('wsl')` to determine WSL is not recommended.

**Comment by michael-angelozzi** [comment]
Okay great, thanks for the clarification @erw7
