### ISSUE TITLE
Autocmd BufReadPre does not fire

### ISSUE THREAD

**Issue by michael-angelozzi** [neovim/neovim#12640]
- `nvim --version`:
```
:ver
NVIM v0.5.0-563-ge628a05b5
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict
-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto
-DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/b
uild/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/bu
ild/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/n
eovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-c5758e75-4445-4564-8946-810c98499a51
```
- Operating system/version: Ubuntu 20.04
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Start nvim with `nvim -u NORC`
2. Enter the following into a file and save it.
```
augroup wsl_vim_autogroup
    autocmd!
    autocmd BufReadPre    * :echom "......BufReadPre"
    echom "Auto commands set"
augroup END
```
3. Source the file.
4. `:e some/other/file`
5. Check `:messages` and see "......BufReadPre" was **not** printed

### Actual behaviour
"......BufReadPre" was **not** printed. Autocmd was not run.

### Expected behaviour
"......BufReadPre"  to be printed, Autocmd to run. Test in original VIM 8.1 and it works as expected.

**Comment by erw7** [comment]
Thanks for the report, but this is a FAQ.

https://github.com/neovim/neovim/wiki/FAQ#calling-inputlist-echomsg-etc-in-filetype-plugins-and-autocmd-does-not-work

**Comment by michael-angelozzi** [comment]
Thanks for that info @erw7 ! I read the FAQ a very long time ago before I knew what vimscript was =)

**Comment by michael-angelozzi** [comment]
This behaviour I feel is a bit unfortunate, because it is maybe giving Neovim a bit of an bad name. e.g. [This SO Post, I tagged this info there too](https://vi.stackexchange.com/posts/26492/edit). People who don't want the messages will likely be able to figure it out, whereas the reverse is maybe harder. I suspect a lot people like I when testing something, the first think they do is use `echom`.
