### ISSUE TITLE
FZF Slow to open files in 0.5.0

### ISSUE THREAD

**Issue by medwatt** [neovim/neovim#12659]
- `nvim --version`: 0.5.0
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Windows 10 x64
- Terminal name/version: nvim-qt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`
When using the plugin FZF on the latest nightly version of Nvim (0.5.0), loading a file occurs after a delay of 5 sec or so irrespective of the size of the file. This is not the case on gVim or nVim 0.4.3. I've recorded a video demonstrating it.
https://streamable.com/ng30l4

**Comment by theHamsta** [comment]
I don't know whether this is related but I observed a delay whenever information is sent to the terminal (e.g. sending commands via neoterm or sending REPL commands with vlime). It happens since a few days (I always update to HEAD everyday).

**Comment by justinmk** [comment]
can you bisect to the specific commit on master branch ?

**Comment by medwatt** [comment]
@justinmk, how can I do so if there are no older versions that I can download to get a rough estimate on when the problem started so I can narrow down the search ?

**Comment by snorkysnark** [comment]
If anyone is interested, I've been trying to make fzf open in "embedded" alacritty (one terminal stacked on top of another) instead of the build-in terminal:
https://gist.github.com/snorkysnark/f3545bf573d9c6a14390b434f8c9d8e8

Seems to work mush faster, just need to make it properly focus + get rg to work
Might be a viable alternative while we are making for a fix

**Comment by panosl** [comment]
For me it really sluggish when I execute `:GFiles` (the one I use most). `:Files`, `:Tags` & `:Rg` perform much better, meaning I can work with that for now.

Can you try and see if you have the same experience?

Also, let me know if I can provide any log/output/feedback to help.

**Comment by panosl** [comment]
It's also happening for [Fugitive](https://github.com/tpope/vim-fugitive), when I execute `:G` to open up the status page. It takes forever. Not opening a new ticket until we get something out this one.

**Comment by panosl** [comment]
An update on my end. The delay was cause by slow Fish (shell) startup.

I had misconfigured my fish_user_paths and it had grown to several KBs. Ergo, the shell took 3s to load. That 3s delay was added to each command that nvim had to delegate to the shell.

I fixed my shell and the delay is gone..

The weird thing though, is that nvim 0.4.* didn't have that issue.

**Comment by teto** [comment]
sorry but closing as it's hard to debug these and most likely due to your setup.

**Comment by kaddkaka** [comment]
An enhancement to checkhealth that probably would have found this issue has been proposed here https://github.com/neovim/neovim/issues/12884
