### ISSUE TITLE
netrw netrw_list_hide regular expression escaping broken in tree-mode

### ISSUE THREAD

**Issue by sly010** [neovim/neovim#12669]
- `nvim --version`: NVIM v0.4.3
- Operating system/version: reproduces with multiple versions of macos
- Terminal name/version: reproduces with multiple terminals
- `$TERM`:  reproduces with multiple values

### Steps to reproduce
Put these two lines in config:

```
let g:netrw_liststyle=3
let g:netrw_list_hide='^\..*$'
```

### Actual behaviour
netrw hides all files

### Expected behaviour
netrw should hide dotfiles only

It works as expected in other modes (e.g. it works if netrw_liststyle=2)

**Comment by erw7** [comment]
You might want to report this to the vim issue tracker, as it works the same way in vim. I tried it and it seems to work as follows.

```vim
let g:netrw_list_hide='^\\..*$'
```

Incidentally, the following also works as expected

```vim
let g:netrw_list_hide='\v^\..*$'
let g:netrw_list_hide='\m^\..*$'
let g:netrw_list_hide='\M^.\.\*$'
```

However, the next `very magic` does not work as expected. It works in a way that I don't quite understand.

```vim
let g:netrw_list_hide='\M^.\.\*\$'
```

I think it's a problem with the original netrw, so I'll close this.
