### ISSUE TITLE
neovim fails to start on Windows Server without Desktop Experience installed

### ISSUE THREAD

**Issue by jantari** [neovim/neovim#12668]
### Explanation of the problem

On Microsoft Windows Server, the default deployment option has not included a "GUI" (Microsoft officially calls it "Desktop Experience") for many years. Windows Server installations without Desktop Experience are also reffered to as "Windows Server Core".

On Windows Server Core, neovim does not start but crashes on startup.

### Required information

- `nvim --version`: 
```
NVIM v0.5.0-607-g459800db4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
[ ... ]
```
- `vim -u DEFAULTS` (version: ) behaves differently?
I installed vim 8.2 just to run this, **and it opens up just perfectly**. Exact vim version used:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:19:27)
MS-Windows 32-bit console version
Compiled by mool@tororo
```
- Operating system/version: Microsoft Windows Server 2019 Version 10.0.17763.1339
- Terminal name/version: Default Microsoft conhost 10.0.17763.1
- `$TERM`: < Is undefined >

Additional note: I have absolutely no configuration files or plugins in place, this is just downloaded neovim, extracted and run.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC:

Exactly the same behavior as with just "nvim" - it fails to start.

# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

neovim fails to open with the error:
```
The application was unable to start correctly (0xc000007b)
Click OK to close the application.
```
![image](https://user-images.githubusercontent.com/25607767/88171682-10237380-cc20-11ea-8e6c-69e38be3a13b.png)

This happens with the `--version` or `-V` arguments as well. No output is ever printed to STDOUT/STDERR.

### Expected behaviour

neovim opens, or in the case of `--version` at least prints its version information.

### Things I've tried

I've tried installing the [App Compatibility FOD](https://docs.microsoft.com/en-us/windows-server/get-started-19/install-fod-19), which increases compatibility with applications that rely on GUI libraries, but it did not make a difference.

I've tried running vim (non-neo) and it works like one would expect, out of the box.

I've tried running neovim on a Windows Server of the same exact version/patchlevel with the full fat Desktop Experience installed and it did start and run as expected.

**Comment by erw7** [comment]
The error code(`0xc000007b`) appears to be the same as #9738. https://github.com/neovim/neovim/issues/9738#issuecomment-474311730 is not helpful?

**Comment by jantari** [comment]
I will try that tomorrow, thanks

**Comment by jantari** [comment]
Yep, that was it. After installing Microsoft Visual C++ 2017 Runtime 14.16.27027.1 it worked great. Thanks!
