### ISSUE TITLE
home & end shortcut on Windows

### ISSUE THREAD

**Issue by ahmadrasyidsalim** [neovim/neovim#12661]
- `nvim --version`: NVIM v0.4.3, Build type: RelWithDebInfo, LuaJIT 2.0.5
- Operating system/version: Microsoft Windows 10 Pro, 10.0.19042 N/A Build 19042
- Terminal name/version: PowerShell 7.0.3

### Actual behaviour
```home``` and ```end``` shortcut didn't work!
### Expected behaviour
```home```: To the first character of the line, like ```0``` on VISUAL LINE
```end```: To the end of the line, like ```$``` on VISUAL LINE

**Comment by erw7** [comment]
29f1e1995da1c3e6fb94a5f939c43481df3a500d and later versions of neovim do not have this problem on Windows 10 systems that support `ENABLE_VIRTUAL_TERMINAL_INPUT`.

For the rest of the world, you can use 5 of https://github.com/neovim/neovim/issues/11773#issuecomment-579097267 as a workaround.

**Comment by ahmadrasyidsalim** [comment]
Work like charm:
```
choco uninstall neovim -y; choco install neovim --pre -y
```
