### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by Kyle-Thompson** [neovim/neovim#12675]
I've successfully built neovim from source many times but after a recent pull it is no longer working. I'm running Arch linux and just in case I reinstalled the dependencies but the issues persisted. The commands I ran are listed below with the error posted after that. I've replicated this running from master and v0.4.3.

```
git clone git@github.com:neovim/neovim.git
cd neovim
git co stable
make CMAKE_BUILD_TYPE=Release
```

```
mkdir -p build
touch build/.ran-third-party-cmake
ninja -C .deps
ninja: Entering directory `.deps'
[1/63] Performing configure step for 'libvterm'
FAILED: build/src/libvterm-stamp/libvterm-configure
cd /home/kyle/pkg/neovim/.deps/build/src/libvterm && "" "" && /usr/bin/cmake -E
touch /home/kyle/pkg/neovim/.deps/build/src/libvterm-stamp/libvterm-configure
/bin/sh: : command not found
[7/63] Completed 'lua-compat-5.3'
ninja: build stopped: subcommand failed.
make: *** [Makefile:101: deps] Error 1
```

Not sure what to make of the error since no command is listed when it says command not found. Any help is appreciated.

**Comment by clason** [comment]
Can you check the version of `cmake` you have installed? I notice the same problem building the `libvterm` dependency on macOS after homebrew upgraded it to 3.18.0.

**Comment by telemachus** [comment]
I was having the same thing on macOS 10.15.6 with `cmake` 3.18.0. #12676 fixes it for me as well, and the resulting `nvim` seems fine according to `checkhealth`. I'm also not sure if there are any potentially bad side effects.

**Comment by bmon** [comment]
I am seeing this as well on linux - compiles fine after applying #12676

```
$ cmake --version     
cmake version 3.18.0

$ uname -a   
Linux brendanroy 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64 GNU/Linux
```

**Comment by codewiz** [comment]
I can reproduce this on Arch Linux.
I can *not* reproduce it on Fedora 32.

Also happens with CMAKE_EXTRA_FLAGS="-DUSE_BUNDLED=OFF"

**Comment by Kyle-Thompson** [comment]
I took the advice of just removing that line from the cmake file and it worked. Hopefully this fix gets merged in soon. Thanks everyone.

**Comment by timmyjose** [comment]
This caused me to waste a couple of ****ing hours before I finally decided to check the issues to see if anyone else had faced the same issue. I'd recently changed the compilers on my macOS Mojave box, and so I thought something had gone wrong with the compiler configuration. Damn!

**Comment by serif** [comment]
> in which file to remove it from???

I wish someone had answered this. I'm having the same problem a year later.

**Comment by serif** [comment]
I found `cmake.deps/cmake/BuildLibvterm.cmake`, which contains 5 results for `CMAKE_COMMAND`, but it's not being set there; it's being used as a variable in other commands after having been set somewhere else.

I found `CONFIGURE_COMMAND ""` in `cmake.deps/cmake/BuildLuv.cmake` and `cmake.deps/cmake/GetBinaryDeps.cmake`, but after removing those, I still had the original libvterm error, and now also a new error: `No patch step for 'libuv'`.

**Comment by dundargoc** [comment]
@serif try running `make distclean` before building neovim
