### ISSUE TITLE
checkhealth can't find nvm's node but coc-vim can

### ISSUE THREAD

**Issue by andradei** [neovim/neovim#12674]
- `nvim --version`:

```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?

My `vim` doesn't have `:checkhealth`

- Operating system/version: Ubuntu 20.04 (WLS 2)

- Terminal name/version: Windows Terminal 1.1.2021.0
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

- Install NodeJS via `nvm install node`
- Run `npm install -g neovim`
- Run `nvim -u NORC` and `:checkhealth`

### Actual behaviour

Can't find NodeJS, `:checkhealth` shows:

```
## Node.js provider (optional)
  - ERROR: Command error (job=7, exit code 127): `node -v` (in '/current/path')
    Output: zsh:1: command not found: node
    Stderr: zsh:1: command not found: node
  - INFO: Node.js: zsh:1: command not found: node
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

When running `:!echo $PATH` the path to `nvm`'s active `node` isn't there.
But running `echo $PATH` on the terminal shows it is there: `/home/me/.nvm/versions/node/v14.6.0/bin`

That path is appended via an `nvm.sh` script (official) that's executed from my `~/.zshrc`

The strange thing is that `coc-vim` **still works** and I get auto-completion, which I think uses `node`.

### Expected behavior

That it found `node` after I ran all commands that were asked

**Comment by erw7** [comment]
When run as a non-interactive shell, zsh will not load `.zshrc`. Therefore, if you have a path set up in `.zshrc`, the results of passing a string (In this case, use a shell) as a `system` or `jobstart` argument may be different from the results of passing a list (not use shell). I'd like to change it to use the list as much as possible for what is in neovim's rutime if there are no problems. However, we cannot guarantee that all plugins will do so. Therefore, if you have the shell option set to zsh to avoid problems, it is recommended that you use `.zshenv` to set the necessary paths.

**Comment by andradei** [comment]
Thanks for the explanation. However, I am setting my `PATH` values in `.zshenv` already.
