### ISSUE TITLE
Source lua files from plugin directories (and ftplugin, colors, etc)

### ISSUE THREAD

**Issue by clason** [neovim/neovim#12670]
Splitting this out from https://github.com/neovim/neovim/issues/7895#issuecomment-633149321 since it's a separate issue.

Similarly to `init.lua` support, neovim should allow `lua` files in user plugin directories (`$XDG_CONFIG_HOME/nvim/plugin`, `$XDG_CONFIG_HOME/nvim/ftplugin`, etc.) as well. This is particularly useful for pure lua plugins installed via native packages (e.g., through https://github.com/wbthomason/packer.nvim), since these packages -- even in `/start/` -- are by default not sourced until after `init.vim` (and, presumably, `init.lua` once supported) is sourced. This means one would have to either manually `packadd` each Lua package, or create a vimscript shim in `$XDG_CONFIG_HOME/nvim/plugin`.

As a starter, it would probably suffice to add a lua version after https://github.com/neovim/neovim/blob/326b87feb6179d1b36375844eab493e0bb4dbf7f/src/nvim/main.c#L1350 that calls https://github.com/neovim/neovim/blob/326b87feb6179d1b36375844eab493e0bb4dbf7f/src/nvim/lua/executor.c#L1178 on each lua file found in the same paths.

@tjdevries

**Comment by tjdevries** [comment]
I can't remember if we said that it should take priority over `.vim` files or just source side-by-side?

`plugin/my_plug.vim` and `plugin/my_plug.lua` should both be sourced? (it seems yes, because they get sourced in other directories, and it's not like startup where there is always only "one" startup file).

**Comment by clason** [comment]
I think they should be treated independently (`init.lua` is a special case); the order is indeed a matter for discussion (all lua first? all vim first? alphabetically, with lua/vim first? the second seems easiest for starters). 

(To be honest, I think the same argument could be made for `init.lua` -- I see good reasons to allow for both, as long as the precedence is clear; my gut feeling is "vim first", without being able to give a good example for it.)

**Comment by alexanderjeurissen** [comment]
I'm interested in this topic as well,

## RE: ftplugin

As brought up in https://github.com/neovim/neovim/pull/12378#issuecomment-812862083, ftplugin is merely syntactic sugar around `autocmd`.

https://github.com/neovim/neovim/blob/abdda664108646a8f1bd3112abb8083d721d38e6/runtime/ftplugin.vim#L11-L35

How it works:

1. Define a `augroup`
2. Define a autocmd that triggers on all filetypes
3. Invoke function that retrieves the filetype and executes the corresponding ftplugin file using `runtime`

This can easily be extended to in addition to searching for a `.vim` file to also search for a `.lua` file and load it accordingly.

This is also how https://github.com/tjdevries/astronauta.nvim approaches this.

> I think they should be treated independently (`init.lua` is a special case); the order is indeed a matter for discussion (all lua first? all vim first? alphabetically, with lua/vim first? the second seems easiest for starters).
> 
> (To be honest, I think the same argument could be made for `init.lua` -- I see good reasons to allow for both, as long as the precedence is clear; my gut feeling is "vim first", without being able to give a good example for it.)

I agree that from my perspective vim first, lua second would be the expected order. I think it's up to plugin authors and users to ensure these configs don't conflict.

I think we can achieve this with minimal code changes, e.g.

diff --git a/runtime/ftplugin.vim b/runtime/ftplugin.vim
index a434b93..2877e77 100644
--- a/test.vim
+++ b/test.vim
@@ -29,6 +29,10 @@ augroup filetypeplugin
       " "aaa.bbb" load "aaa" and then "bbb".
       for name in split(s, '\.')
 	exe 'runtime! ftplugin/' . name . '.vim ftplugin/' . name . '_*.vim ftplugin/' . name . '/*.vim'
+
+	if filereadable('ftplugin/' . name . '.lua')
+	  luafile 'ftplugin/' . name . '.lua'
+	endif
       endfor
     endif
   endfunc

@tjdevries WDYT ?
