### ISSUE TITLE
Phantom cursor in terminal

### ISSUE THREAD

**Issue by benbarbour** [neovim/neovim#12677]
- `nvim --version`: 
```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing
-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/bui
ld/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/bu
ild/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"
```

- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Ubuntu 18.04
- Terminal name/version: alacritty 0.4.3 (c723247) 
- `$TERM`: xterm256-color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
![image](https://user-images.githubusercontent.com/487715/88315688-79ac8c00-cccb-11ea-946c-5d2cb6c2c678.png)
The "real" cursor is the one at the end of the line.

### Expected behaviour
Only one cursor visible

**Comment by norcalli** [comment]
@benbarbour are you using a GUI?

**Comment by benbarbour** [comment]
> @benbarbour are you using a GUI?

Nope.

**Comment by erw7** [comment]
Are you possibly logging into Ubuntu from Windows with ssh? In other words, isn't the `alacritty` in the screenshot running on Windows? If so, I suspect this is a `ConPTY` issue. I think I've seen a cursor like this before in Windows Terminal etc (Terminals using `ConPTY`).

**Comment by benbarbour** [comment]
> Are you possibly logging into Ubuntu from Windows with ssh? In other words, isn't the `alacritty` in the screenshot running on Windows? If so, I suspect this is a `ConPTY` issue. I think I've seen a cursor like this before in Windows Terminal etc (Terminals using `ConPTY`).

I am indeed!

**Comment by bohrshaw** [comment]
This also happens on Neovim 0.4.4 (with or without Tmux) in WSL2 through "Alacritty",  but not "Windows Terminal" or "MinTTY".

**Comment by bohrshaw** [comment]
The cause is probably on Neovim's side as Vim's embedded terminal works normally on Alacritty on WSL2.

**Comment by 3N4N** [comment]
I can't reproduce.  My system specs follows.

```
Neovim:  NVIM v0.9.0-dev-1252+g5726f33e8caa
Alacritty:  v0.12.0 portable executable
WSL:  Ubuntu 20.04
OS:  Windows 11 Pro Version 22H2 Build 22621.1702
```

**Comment by bohrshaw** [comment]
Reproducible steps:
```sh
nvim -u NORC +'set relativenumber' +term
```
ENV:
```
Neovim: v0.9.0-release
Alacritty: v0.12.0-release
WSL: Debian 11
OS: Windows 10 Enterprise Version 21H2 (OS Build 19044.2846)
```
