### ISSUE TITLE
\{-} Do greedy matching

### ISSUE THREAD

**Issue by BenSYZ** [neovim/neovim#12686]
- `nvim --version`:
> NVIM v0.4.3
> Build type: Release
> LuaJIT 2.0.5
- `vim -u DEFAULTS` (version: ) behaves differently?
No.
- Operating system/version:
Linux version 5.7.8-arch1-1 
- Terminal name/version:
alacritty 0.4.3
- `$TERM`:
xterm
### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC index.html
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
/<td>\(.\{-}\)<\/td>

<tr><td>BaseException</td><td> BaseException </td></tr>

```

### Actual behaviour
Greedy matching, match two tags.
### Expected behaviour
Non-greedy matching, match one tag.

**Comment by KillTheMule** [comment]
Can't confirm, example works as expected for me (using an older version of 0.5).

**Comment by BenSYZ** [comment]
Excuse me, I cannot understand

> using an older version of 0.5

I only see version 0.4, which I thought was the latest version.

**Comment by KillTheMule** [comment]
> I only see version 0.4, which I thought was the latest version.

0.5 will be the next release. I compiled from the master branch some time in the past, and that's what I'm using. You could try the nightly binary, it seems the problem is already solved, but the fix hasn't been backported.

**Comment by BenSYZ** [comment]
I'm so SORRY to open this issue. It's all my careless. Because of 2 patterns are together, the highlight are connected. I count them only once. By the way version 0.4.3 also works well. Sorry agian!🙇‍♂️
