### ISSUE TITLE
Unable to build master in openbsd 6.7 

### ISSUE THREAD

**Issue by bikallem** [neovim/neovim#12682]
- `nvim --version`: master
- Operating system/version:OpenBsd 6.7
- Terminal name/version: xterm 
- `$TERM`:xterm

### Actual behaviour
Attempting to build neovim from master by following the instructions on https://github.com/neovim/neovim/wiki/Building-Neovim#openbsd doesn't succeed. It fails with the following
```
[67 %] Performing build step for 'msgpack'
make: don't know how to make w
Stop in /home/bikal/neovim/.deps/build/src/msgpack-build
```

### Expected behaviour
Able to build successfully

**Comment by erw7** [comment]
In the meantime, I used `ninja` as shown in the following steps and the build was successful. Unlike the wiki description, `gettext-tools` also had to be `pkg_add`.

```
pkg_add gmake ninja cmake libtool unzip gettext-tools autoconf-2.69p2 automake-1.16.2
export AUTOCONF_VERSION=2.69
export AUTOMAKE_VERSION=1.16
mkdir .deps
cd .deps
cmake -G Ninja ../third-party/
ninja
cd ..
mkdir build
cd build
cmake -G Ninja ..
ninja
```

**Comment by bikallem** [comment]
Thanks. This did it. I also added the following in the last step to create a release build
```
cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..
```
Closing this now.
