### ISSUE TITLE
How to load an lsp server only for a specific filetype?

### ISSUE THREAD

**Issue by DrGo** [neovim/neovim#12688]
Hello,
I am trying to setup gopls but only when the filetype is go using go.vim (listed below):

- when I put vim.go in my nvim/ftplugin or nvim/after/ftplugin  dir(to load when a .go file is opened):
-- file is loaded as per :scriptnames and successful call to GoLoad()
-- no lsp functionality (diagnostics, goto implementation) at all when a .go file is opened using nvim f1.go
-- no lsp functionality at all when a .go file is opened for the first time inside nvim :e f1.go
-- full lsp functionality when a second file is opened inside nvim :e f2.go but only inside f2.go (f1.go still has no lsp support).

- when I source go.vim in my init.vim: full lsp functionality in all three scenarios.

Any idea what I am doing wrong?

Thanks,

*************** go.vim *********************
```vim
:lua << EOF
local nvim_lsp = require('nvim_lsp')
nvim_lsp.gopls.setup{}
EOF
setlocal omnifunc=v:lua.vim.lsp.omnifunc
nnoremap <buffer><silent> gd    <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap <buffer><silent> <c-]> <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap <buffer><silent> K     <cmd>lua vim.lsp.buf.hover()<CR>
nnoremap <buffer><silent> gD    <cmd>lua vim.lsp.buf.implementation()<CR>
nnoremap <buffer><silent> <c-k> <cmd>lua vim.lsp.buf.signature_help()<CR>
"nnoremap<buffer> <silent> 1gD   <cmd>lua vim.lsp.buf.type_definition()<CR>
nnoremap <buffer><silent> gr    <cmd>lua vim.lsp.buf.references()<CR>
nnoremap <buffer><silent> g0    <cmd>lua vim.lsp.buf.document_symbol()<CR>
nnoremap <buffer><silent> gW    <cmd>lua vim.lsp.buf.workspace_symbol()<CR>

setlocal signcolumn=yes  "prevent text shifting with lsp errors
setlocal completeopt=menu,noinsert,noselect,menuone
function GoLoad()
  echo 'go.vim loaded!'
endfunction
```

**Comment by erw7** [comment]
`nvim_lsp.gopls.setup{}` sets up `autocmd FileType python`, ftplugin is also called by the filetype autocmd. Therefore, the autocmd set by ftplugin in autocmd would not be called. Perhaps you need to call `doautocmd` after calling `nvim_lsp.gopls.setup{}` only on the first load as follows.

```vim
let s:loaded = get(s:, 'loaded', v:false)
if !s:loaded
lua << EOF
  local nvim_lsp = require('nvim_lsp')
  nvim_lsp.gopls.setup{}
EOF
  let s:loaded = v:true
  doautomcd FileType python
endif
```

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by mangelozzi** [comment]
Heres an example of adding the `htmldjango` to the `html` LSP, maybe it helps others with a related problem.

```lua
    require('lspconfig').html.setup {
        on_attach = lsp_attach,
        capabilities = capabilities,
        filetypes = {'html', 'htmldjango'}, -- Add htmldjango
    }
```
