### ISSUE TITLE
Missing read permission treated as missing write permission

### ISSUE THREAD

**Issue by jeffs** [neovim/neovim#12684]
- `nvim --version`:

        NVIM v0.4.3
        Build type: Release
        LuaJIT 2.0.5
        Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
        Compiled by brew@Catalina.local

        Features: +acl +iconv +tui
        See ":help feature-compile"

           system vimrc file: "$VIM/sysinit.vim"
          fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

        Run :checkhealth for more info

- `vim -u DEFAULTS` (version: 8.1) behaves differently?

    Yes.  When opening a `file` for which the user hasn't got read permission:

    * `vim --clean file` correctly says `[Permission Denied]`
    * `nvim --clean file` says `[RO]`

- Operating system/version: tried macOS 10.15.5 and ubuntu:groovy
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Create a file that has no read permission:

        $ echo hello > a && chmod -r a

2. Open the file in Neovim:

        $ nvim -u NORC a

   Neovim shows [RO] rather than [Permission Denied].

### Actual behaviour

Neovim reports [RO] when opening a write-only file.

### Expected behaviour

Neovim should report [Permission Denied] when a read attempt fails.

Both Vim and Neovim set readonly, but Permission Denied should be salient.
Showing RO implies that the file is unwritable rather than unreadable.

**Comment by teto** [comment]
confirmed. statusline shows `noperm` :$

**Comment by erw7** [comment]
The behavior of vim and neovim is not different. This is also because the default `shortmessg` in neovim contains `F`. You can make neovim work the same way as vim by doing the following.

```
nvim -u NORC --cmd 'set shortmess-=F laststatus=0' test.txt
```

On the other hand, you can make vim work the same way as neovim by doing the following.

```
vim -Nu NORC --cmd 'set shortmess+=F laststatus=2' test.txt
```

**Comment by glacambre** [comment]
Vim and Neovim differing on this setting causes a lot of confusion:

- https://github.com/neovim/neovim/issues/10116
- https://github.com/neovim/neovim/issues/10008
- https://github.com/neovim/neovim/issues/12597
- https://github.com/neovim/neovim/issues/12288
- https://github.com/neovim/neovim/issues/12144
- https://github.com/neovim/neovim/issues/12041
- https://github.com/neovim/neovim/issues/11478#issuecomment-559744508
- https://github.com/neovim/neovim/issues/9870
- https://github.com/neovim/neovim/issues/8873
- https://github.com/neovim/neovim/issues/8817

It looks like this is more of a cosmetic change than anything else:

- https://github.com/neovim/neovim/pull/8619

Perhaps it should be reverted?

**Comment by justinmk** [comment]
> Expected behaviour: Neovim should report [Permission Denied] when a read attempt fails.

Following the repro steps, I now see "permission denied": 
<img width="212" alt="image" src="https://github.com/neovim/neovim/assets/1359421/c45220d2-1b19-4693-8441-3f1d655d91aa">
