### ISSUE TITLE
Statusbar rendering glitches when using WinBar

### ISSUE THREAD

**Issue by cideM** [neovim/neovim#12689]
I originally reported this in the [vim-colortemplate](https://github.com/lifepillar/vim-colortemplate/issues/33) repo

- `nvim --version`: NVIM v0.5.0-dev **The issue is NOT present in 0.4.3**
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Darwin Kernel Version 19.6.0 (happens on my Arch Linux installation too)
- Terminal name/version: alacritty 0.5.0-rc2 (happens on iTerm as well)
- `$TERM`: `tmux-256color` and `alacritty`

### Steps to reproduce using `nvim -u NORC`

1. `git clone https://github.com/k-takata/minpac.git ~/.config/nvim/pack/minpac/opt/minpac`
2. Create `init.vim` with
```vim
packadd minpac

call minpac#init()
call minpac#add('lifepillar/vim-colortemplate')
```
3. `nvim -u init.vim` (`init.vim` from above)
4. `:call min#update()`
5. `wget 'https://raw.githubusercontent.com/cideM/yui/master/yui.colortemplate'`
6. `nvim -u init.vim yui.colortemplate`
7. Scroll up and down

### Actual behaviour

Rendering glitches with e.g., the statusline (or only parts of it) starting to fill up the buffer
<img width="650" alt="Screen Shot 2020-07-28 at 09 32 44" src="https://user-images.githubusercontent.com/4246921/88633514-675c9480-d0b5-11ea-987f-681c1fa386b6.png">

### Expected behaviour

No rendering glitches

**Comment by erw7** [comment]
This problem seems to be easily reproduced by the following procedure.

```vim
nvim -u NORC
:amenu 1.10 WinBar.TEST1 :echomsg 'TEST1'<cr>
:e .vimrc
<C-f>
```

**Comment by erw7** [comment]
The following changes seem to fix this problem.

```C
diff --git a/src/nvim/menu.c b/src/nvim/menu.c
index b06046438..061d195b1 100644
--- a/src/nvim/menu.c
+++ b/src/nvim/menu.c
@@ -58,7 +58,7 @@ static bool menu_is_winbar(const char_u *const name)
 int winbar_height(const win_T *const wp)
   FUNC_ATTR_PURE FUNC_ATTR_WARN_UNUSED_RESULT FUNC_ATTR_NONNULL_ALL
 {
-  return wp->w_winbar != NULL && wp->w_winbar->children != NULL ? 1 : 0;
+  return 0;
 }

 static vimmenu_T **get_root_menu(const char_u *const name)
```

Am I wrong in my understanding that the conclusion of #11513 is to build the menu hierarchy but not to change `screen.c` for display? I think #12018 has been ported according to that policy, but it implements `winbar_click` and the case where `winbar_height` returns 1. Are they really necessary?

cc @janlazo

**Comment by janlazo** [comment]
> Am I wrong in my understanding that the conclusion of #11513 is to build the menu hierarchy but not to change `screen.c` for display? I think #12018 has been ported according to that policy, but it implements `winbar_click` and the case where `winbar_height` returns 1. I think this display problem is caused by `winbar_height` returning 1. Are they really necessary?

It's not necessary. winbar patches were ported for `menu.c` changes only. I planned to remove `winbar` code after merging menu patches to avoid cases like this.

**Comment by erw7** [comment]
@janlazo Can you remove any unnecessary changes related to `winbar`?

**Comment by janlazo** [comment]
I can remove them after merging the remaining 8.0.x `menu.c` patches. There does not seem to be any remaining 8.x patches that depend on `winbar` in the `C` source code based on Vim's commit history today.
