### ISSUE TITLE
nothing hapend after type "nvim" <enter> in the terminal 

### ISSUE THREAD

**Issue by woshichuanqilz** [neovim/neovim#12683]
system info: 

nvim --version:

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

vim -u DEFAULTS (version: 8.1) behaves differently?

vim works fine. 

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 12 2020 00:14:12)
Included patches: 1-1185
Compiled by Arch Linux
Terminal name/version: iTerm2

Description: 
It works well earlier, but after I install the mru plugin. nvim wont start. 
After type "nvim" <enter> in the terminal, nothing happened. 

1. 
I try `nvim -D` seems cant find useful infomation
2.
And I reinstall neovim and delete  **.vim** and **.vim_runtime** folder it wont work too. 
~/.local/share/nvim removed, still the same. 
3. 
nvim --noplugin no work for me.
4. 
nvim -u NORC worked!

So how to fix this issue? 

Where is the log file of the neovim cant find it.

![2020-07-25_15-28](https://user-images.githubusercontent.com/11295355/88451996-be802080-ce8d-11ea-96ee-5f7d563b7d03.png)
![2020-07-25_15-41](https://user-images.githubusercontent.com/11295355/88451999-bfb14d80-ce8d-11ea-9361-c3078ca9b3ef.png)

**Comment by erw7** [comment]
@woshichuanqilz Please respect the issue template. `nvim -u NORC` or `nvim --noplugin` does neovim start correctly? I'm not sure how you installed the plugin, but is it possible that the plugin is installed in `~/.local/share/nvim`? In addition, before https://github.com/neovim/neovim/commit/8e350c1c6922f9c678e83d97227e7edd84967571, `-D` is not normally available. If you want to use `-D`, you need to use the latest nightly.

**Comment by woshichuanqilz** [comment]
> @woshichuanqilz Please respect the issue template. `nvim -u NORC` or `nvim --noplugin` does neovim start correctly? I'm not sure how you installed the plugin, but is it possible that the plugin is installed in `~/.local/share/nvim`? In addition, before [8e350c1](https://github.com/neovim/neovim/commit/8e350c1c6922f9c678e83d97227e7edd84967571), `-D` is not normally available. If you want to use `-D`, you need to use the latest nightly.

Question template changed sorry for not following the rules.

I run the nvim with command **nvim -u NORC** and it works well. I think the issue in the init.vim, so I checked it. 
After add a **:x** in the init.vim and I not notice that. So nvim exit immediately. 

My bad sorry for this stupid question.
