### ISSUE TITLE
Incorrect <afile> expansion on BufUnload for [NO NAME] buffers

### ISSUE THREAD

**Issue by BK1603** [neovim/neovim#12690]
- `nvim --version`: NVIM v0.5.0-563-ge628a05b5
- `vim -u DEFAULTS` (version: ) behaves differently? Yes. I don't think the `BufUnload` autocommand is triggered in vim in such a case. I couldn't get `au` to print anything at all.
- Operating system/version: Debian 10 buster. (Linux 4.19)
- Terminal name/version: gnome-terminal 3.30
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:au BufUnload * echo expand('<afile>')
```

Now open a file to edit using the `:e` command. Let's say `:e test`

### Actual behaviour
The name of the file currently opened is printed. In the example case, `test` is printed.

### Expected behaviour
The name of the buffer being unloaded should be printed. (In this case `[NO NAME]`). The wrong name is printed only when a `[NO NAME]` buffer is unloaded.

I think it's because the newly opened buffer gets the same number as the `[NO NAME]` one. Though I am not too sure of if this actually is the reason why this is happening.

**Comment by glepnir** [comment]
can't reproduce now.
