### ISSUE TITLE
doc: Function signature is inconsistent with parameter interpretation

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#12691]
https://github.com/neovim/neovim/blob/33eaa171fad0c8b729b0db14eef3173dbd8c950b/runtime/doc/api.txt#L1593

https://github.com/neovim/neovim/blob/33eaa171fad0c8b729b0db14eef3173dbd8c950b/runtime/doc/api.txt#L1621

**Comment by erw7** [comment]
The same applies to the following areas.

https://github.com/neovim/neovim/blob/5f5bd576e5395ef0cd6198f16d10edc1ff4bbe76/runtime/doc/api.txt#L2056

https://github.com/neovim/neovim/blob/5f5bd576e5395ef0cd6198f16d10edc1ff4bbe76/runtime/doc/api.txt#L2081

However, `api.txt` is automatically generated from the source code. As you can see in the relevant code, the `ns_id` is returned by the `src2ns` function from the `src_id`. So, if you want to change it, you need to change the parameter interpretation to `src_id`, which may be more confusing than `ns_id`.

**Comment by tjdevries** [comment]
This is updated now?
