### ISSUE TITLE
Let variables equal hex colors

### ISSUE THREAD

**Issue by Opencode-foss** [neovim/neovim#12706]
I would like it to be possible to let a variable to be equal to a hex color. I would like it to make it possible to do the following:

let s:foo = #FC120C

hi Comment guifg = s:foo

Instead it gives you the error that #FC120C is not defined.

**Comment by teto** [comment]
you can add quote to use it as a string instead `let s:foo = '#FC120C'`. Even simple strings need to be quoted. It's not likely to change unless vim does it.

**Comment by Opencode-foss** [comment]
Thank you. I tried that and vim does not evaluate the string to a color in the highlight command.

**Comment by erw7** [comment]
> I tried that and vim does not evaluate the string to a color in the highlight command.

Try the following.

```vim
let s:guifg = '#FC120C'
execute 'hi Comment guifg=' . s:guifg
```

**Comment by Opencode-foss** [comment]
Ok, thank you.
