### ISSUE TITLE
"E315: ml_get: invalid lnum" when pasting text copied blockwise with coc.nvim enabled

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#12718]
https://github.com/neoclide/coc.nvim/issues/2227

Hi, I just filed above issue regarding `E315: ml_get: invalid lnum` when using coc.nvim and blockwise visual mode. All the relevant information is describe there.

I wasn't unsure where to start discussion as this issue is tightly related to both coc.nvim and nvim. So I'm posting on both repos.

**Comment by tomtomjhj** [comment]
This bug reproduces in nvim 0.3.2, the minimal requirement for coc.nvim.

**Comment by tomtomjhj** [comment]
This bug is triggered when nvim sends the buffer updates to channels or callbacks (`buf_updates_active(buf) == true`).

Here is a brief explanation of the bug. To make the numbers a bit more distinguished, I'll use input `i1<CR>2<CR>3<ESC>y<C-v>2k2jp` instead.

1. `do_put` calls `changed_lines(lnum=3, 0, lnume=curwin->w_cursor.lnum=6, xtra=nr_lines=2, true)`
https://github.com/neovim/neovim/blob/f26df8bb66158baacb79c79822babaf137607cd6/src/nvim/ops.c#L3195
```
1
2
31  lnum =3
 2  ┐ xtra = 2
 3  ┘ 
    lnume = 6
```
2. `changed_lines` computes
    * `num_added = lnume + xtra - lnum = 6 + 2 - 3 = 5`
    * `num_removed = lnume - lnum = 6 - 3 = 3`

   and calls `buf_updates_send_changes(curbuf, lnum=3, num_added=5, num_removed=3, true)`.
https://github.com/neovim/neovim/blob/f26df8bb66158baacb79c79822babaf137607cd6/src/nvim/change.c#L495

3. `buf_updates_send_changes` calls `buf_collect_lines(buf, n=num_added=5, start=firstline=3, ...)`
https://github.com/neovim/neovim/blob/f26df8bb66158baacb79c79822babaf137607cd6/src/nvim/buffer_updates.c#L213

4. `buf_collect_lines` calls `ml_get_buf` for lines 3, 4, 5, **6**, **7**.

So apparently, the value `num_added` seems to be wrong.  I think `num_added` and `num_removed` are assuming that `lnume` is 4 instead of 6.  In fact, for linewise put (`i1<CR>2<CR>3<CR>Vkkyjjp`), `do_put` calls `changed_lines` with `lnum=4`, `lnume=4`, `xtra=3`, producing `num_added=4+3-4=3`, `num_removed=4-4=0`. Everything makes sense if `lnume=4`.

So this technically is a vim bug, as this part of `do_put` has not been changed in nvim.
https://github.com/vim/vim/blob/fa211f3c6d27cf962b28f10e3c18b12dde4d20c3/src/register.c#L1877

**Comment by KillTheMule** [comment]
Great report!

> `do_put` calls `changed_lines(lnum=3, 0, lnume=curwin->w_cursor.lnum=6, xtra=nr_lines=2, true)`

Are you sure this is what's happening? I'm asking that because that's wrong, there should really be 4 instead of 6, as you deduced independently (see [this comment](f26df8bb66158baacb79c79822babaf137607cd6). Truth be told, it would be really surprising if `lnume` was wrong here, since this should affect so much stuff out there...

**Comment by tomtomjhj** [comment]
> Are you sure this is what's happening? 

Yes. I that's what I found out with debugger. (vimspector is awesome!) 

> So it could just be that this is wrong in vim as well

Vim does call `changed_lines` with `lnume=6`. 

> but the bug is only manifested in neovim since we're actually using lnume for getting lines from the buffer, which does not have this kind of fault-tolerance.

Right. Maybe I should report this to vim upstream.

**Comment by KillTheMule** [comment]
> Right. Maybe I should report this to vim upstream.

Tell you what, I'll try to find a fix, and then we can report the fix upstream, asking for comments and offering them to include that. Does that sound good?

**Comment by tomtomjhj** [comment]
Sure.

**Comment by KillTheMule** [comment]
Could you try https://github.com/neovim/neovim/pull/12733 and see if that fixes your issue?

**Comment by tomtomjhj** [comment]
Yes that worked! And the comments looks correct too.

**Comment by MuhammadSawalhy** [comment]
I am still getting this issue `Error executing vim. schedule lua callback: Vim: E315: ml_get: invalid Inum: 96` while debugging a nodejs code using [nvim-dap](https://github.com/mfussenegger/nvim-dap) plugin.
