### ISSUE TITLE
css 'gap' highlighting 

### ISSUE THREAD

**Issue by ecumene** [neovim/neovim#12714]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Pop!_OS
- Terminal name/version: alacritty 0.4.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC src/ ... .css
```

### Actual behaviour

![image](https://user-images.githubusercontent.com/6249465/89232846-f04a6300-d5c2-11ea-923f-829b838acf73.png)

### Expected behaviour

"gap" Should be green!

**Comment by erw7** [comment]
Could you try reporting it to https://github.com/JulesWang/css.vim/issues? Normally we do not fix the runtime files with neovim. Once the changes made by the maintainer have been incorporated into the vim, we are in sync.

**Comment by chrisbra** [comment]
I think it has already been fixed by the new css maintainer @jsit here: https://github.com/jsit/css.vim/commit/378764c7d79036f2af54d26940b2173c882170f9

**Comment by ecumene** [comment]
Well done team! Problem fixed itself 🤣
