### ISSUE TITLE
encoding default (utf8) is not correctly initialized

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1271]
Unconfirmed, followup of https://github.com/neovim/neovim/pull/1267#discussion_r18432541

> `vim` opens the original eval.txt as latin1, but `nvim` opens it as utf8.

~~This may be a regression, or it may just be an unavoidable consequence~~ **edit:** this is tangentially related to https://github.com/neovim/neovim/pull/935, see comments below.

To reproduce:

1. `./build/bin/nvim runtime/doc/eval.txt`
2. `:2381`
3. The line is displayed as (notice the question mark): <br/>
`char2nr("?"[0])       returns 195`
4. Re-reading the file with `:e ++enc=latin1` correctly shows the line: <br/>
`char2nr("á"[0])       returns 195`

**Comment by Grimy** [comment]
I can’t reproduce the bug. `encoding` is always set to `utf-8` after either `set all&` or `set encoding&`. Can you bisect your vimrc to find the line(s) that trigger the issue?
