### ISSUE TITLE
Build failure on Travis CI of snap

### ISSUE THREAD

**Issue by erw7** [neovim/neovim#12712]
The snapcraft package creation seems to have failed recently with the following error.

https://travis-ci.org/github/neovim/neovim/jobs/714259405#L362
```
snapcraft.internal.errors.SnapcraftEnvironmentError: 'sudo' cannot be used with build provider 'lxd'
```

Ref: https://forum.snapcraft.io/t/error-sudo-cannot-be-used-with-build-provider-multipass/18096
Ref: iterative/dvc#3990

**Comment by hurricanehrndz** [comment]
@erw7 Thanks for the issue. Just saw this and will look into it.
