### ISSUE TITLE
PPA for Ubuntu 20.04.1

### ISSUE THREAD

**Issue by fcanela** [neovim/neovim#12726]
Yesterday, Ubuntu published the first point release for 20.04. This means that the users from Ubuntu 18.04 version will be prompted to upgrade.

On April this year, @andradei opened the issue #12202 asking for an official Ubuntu PPA for the new Ubuntu version. Some of us would love to install NeoVim this way to be able to update it easily.

In my particular case, I also have all the system configuration performed via dotfiles and the lack of PPA is breaking the build. That is MY problem, obviously, but other users that rely on scripted installations using the PPA can run into the same issue.

Could be please this issue reconsidered?

Thanks for the great work. Please ping me if there is something that can be done to help from my side.

**Comment by fcanela** [comment]
Ping to @jamessan as he was involved in the original issue.

**Comment by jamessan** [comment]
The PPA isn't maintained by neovim, so there's no need to open issues here.  I'm going through the same process I did last time.

* Upload to Debian to verify stability
* If that looks good, prepare updates for PPA

**Comment by Gregory9931** [comment]
Just don't understand all this need one on one

**Comment by fcanela** [comment]
Thanks, @jamessan ! Pretty much appreciated.

Sorry, @Gregory9931 , I do not understand your statement.

**Comment by Gregory9931** [comment]
Just new to the site that's all

**Comment by browser-bug** [comment]
How are the stability tests going? @jamessan

**Comment by jamessan** [comment]
> How are the stability tests going?

Not good -- https://buildd.debian.org/status/package.php?p=neovim&suite=experimental

The release-0.5 branch has fixes/workarounds for some of the issues, but still waiting on others.  In the mean time, I'm also trying to package more of the treesitter stack, so people can experiment with that.
