### ISSUE TITLE
Built in Context Menu

### ISSUE THREAD

**Issue by atishay** [neovim/neovim#12727]
For developer coming from windowed IDEs, context menus can be very helpful. There should be a context menu in nvim which can be opened by a key combination in normal mode or a right click in all modes. 

While this can be done in an extension, it is worth building it in core for the following reasons:
1) Standardization across plugins.
2) Ensuring keyboard friendliness and making sure power users can find some use to it. 

The context menu is not keyboard unfriendly. It can teach keyboard shortcuts. You press a button and get a list properly grouped into menu and sub-menu items. Then the user can either use hjkl or arrow keys to navigate through them or use the shortcut as in the normal mode.

Here are some thoughts:
```
Delete (d) -> Start of word(w), A Word(aw), Inner word(iw), Till the end($), Current line(d)
System Clipboard("+) -> Cut(d), Copy/Yank(y), Paste(p)
--
Spelling -> [Spell suggestions]
Go -> Back(<C-o>), Forward(<C-i>)
```

NOTE: Tmux has a context menu. New developers introduced to tmux find this very useful. Not everyone remember all commands.

**Comment by astier** [comment]
> It can teach keyboard shortcuts. You press a button and get a list properly grouped into menu and sub-menu items. Then the user can either use hjkl or arrow keys to navigate through them or use the shortcut as in the normal mode.

So its basically just a very limited tutorial for the first day-user. Because you can put only so much into a small window and the few basic shortcuts which are shown there are so few and easy to remember that after the first day you know them and never need this feature again.

I am against hardcoding something like this into neovim. The benefit would be very small and would target only at the first day users. I think there are plenty of tutorials out there and vimtutor exists. I certainly never felt like I needed something like this when I started using vim.

If anything much better would be to have a general interface for a popupwindow which can be populated by users and actions can be bound to keypresses for each element in the window. This wouldnt limit it to a context-menu and would enable users to modify it to their liking and plugin-builders to use it for other purposes. For example diagnostics-tools could populate it with fix-suggestions for errors and warnings. However, I am not sure if even something like this is necessary.

**Comment by clason** [comment]
@astier While that's not quite the main goal of https://github.com/nvim-lua/popup.nvim, this could be a place to put such a feature (@tjdevries )

**Comment by atishay** [comment]
> that after the first day you know them and never need this feature again.

Depends on the use case. If you are browsing, doing mouse only scroll, select and copy can be more handy. That is also muscle memory from everything else in the computer. I understand vim tries to cater to keyboard purists but it still has mouse support. 

The context menu should be configurable/customizable to limit to a subset of features that too based on context. That is why it is a "context" menu and not just a popup.

**Comment by astier** [comment]
I think we agree that a context-menu which can be controlled with the mouse can be useful. My only concern is if it couldn't be modified by the user. Sure it could have a default configuration but I think there would be many usecase which the neovim-devs can not foresee and shouldn't be responsible for. For example plugin-developers for file-explorers like NERDTree maybe would want to use such a context-menu. It would be a huge waste of potential if only the neovim-devs would have control over the context-menu and not the users, plugin-developers and the whole community.

My point is it shouldn't be limited to a set of hardcoded features but rather be customizable and maybe be deployed with a default configuration.

**Comment by teto** [comment]
You an already do pretty nice things with plugins https://github.com/skywind3000/vim-quickui.
Entries in the context menu could be filled via a specific menu entry (like gvim menus are fed). 
It would also depend on the `mouse` option.
I think for now, it's best left as a plugin.

**Comment by atishay** [comment]
> You an already do pretty nice things with plugins [skywind3000/vim-quickui](https://github.com/skywind3000/vim-quickui).

Looks like a good plugin. Unfortunately, this needs all data to be filled in manually. I don't see any plugins using it. Cannot statically fill this up with spelling suggestions. And it also needs to be contextual. All possible through VimScript. Need to learn that.

**Comment by teto** [comment]
if you prefer to work in lua, you may be interested in https://github.com/nvim-lua/popup.nvim .

**Comment by tjdevries** [comment]
I'm not sure I understand what the goal would be for it to be made within neovim core.

**Comment by xylix** [comment]
(I don't consider this something that should be a part of the main neovim either)
I personally use 
liuchengxu/vim-which-key
and 
`noremap <silent><leader> :WhichKey '<Space>'<CR>`
To enable discoverability of my own leader commands. Sadly afaik there's no way to make whichkey work nicely for neovim built-in commands, but with commands where I find the default to be bad for my workflow this works well.

For example I use 
```
    noremap <leader>th :tab help<space>
    noremap <silent><leader>tn :tabnew<CR>
    noremap <silent><leader>tx :tabclose<CR>
    noremap <silent><leader>tm :tabmove<space>
    
    "Window close, split horizontal and split vertical
    noremap <silent><leader>wx <C-W>c
    noremap <silent><leader>wh <C-W>s
    noremap <silent><leader>wv <C-W>v
``` 
For (IMO) better to use tab and window split control hotkeys

The way doom-emacs and spacemacs can enable hotkey discoverability for features that are default in vim is also pretty cool. See for example how they show commands one can do after pressing `g`:

![Screenshot 2020-08-10 at 12 12 35](https://user-images.githubusercontent.com/13387304/89767556-d947cb80-db02-11ea-9171-ca6cb2c3c669.png)

**Comment by wsdjeg** [comment]
[SpaceVim](https://spacevim.org) also provides this feature via key binding guide.

![](https://user-images.githubusercontent.com/13142418/89103568-5ad59480-d445-11ea-9745-bd53e668b956.png)

**Comment by justinmk** [comment]
This already exists: `:help :menu` . It also supports trees.

What's missing is builtin support for generating a menu UI from this.

**Comment by zeertzjq** [comment]
After #19170 this enables a context menu:
```vim
set mouse=a
set mousemodel=popup
source $VIMRUNTIME/menu.vim
```

**Comment by justinmk** [comment]
We can close this, but we still are missing a way to generate a _tree_ of popup menus (i.e. a menu with submenus). I assume that's what https://github.com/nvim-lua/popup.nvim or https://github.com/skywind3000/vim-quickui does.

**Comment by teto** [comment]
I've requested the feature to these 2 plugins but the only one I know that does it (and which I use) is https://github.com/sunjon/stylish.nvim#stylishuimenu . Very cool PRs @zeertzjq , thank you so much !

**Comment by AndrejPatak** [comment]
> After #19170 this enables a context menu:
> 
> ```viml
> set mouse=a
> set mousemodel=popup_setpos
> source $VIMRUNTIME/menu.vim
> ```

where do I actually paste this?
im trying to switch to onivim from vscode but I need the context menu to open an html file with the live server plugin
