### ISSUE TITLE
Cursor shape for insert changes when in tmux

### ISSUE THREAD

**Issue by Kyle-Thompson** [neovim/neovim#12723]
nvim version:
```
NVIM v0.5.0-610-g326b87feb-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/kyle/pkg/neovim/build/config -I/home/kyle/pkg/neovim/src -I/home/kyle/pkg/neovim/.deps/usr/include -I/usr/include -I/home/kyle/pkg/neovim/build/src/nvim/auto -I/home/kyle/pkg/neovim/build/include
```

Operating System: Arch Linux
Terminal: ST (custom patch)
TERM (when not in tmux): st-256color 
TERM(when in tmux): tmux-256color

# Behavior
When not in tmux everything works as expected with regards to the cursor shape in and out of insert mode. When in normal mode it is a whole block that fills the whole space of a monospace character and when in insert mode it becomes a thin vertical line on the left of the character block. In tmux however, the change from block to line doesn't occur. In both modes it simply stays as the block. I expected this had to do with the `terminal-overrides` section in the tmuxrc but after reading through the man page and fiddling around for a while I can't seem to make it work by changing that option.

If this isn't the proper place to ask the question then I'll close the issue and ask it elsewhere. Since it deals directly with neovim though, I was hoping someone in the community might know what's going on. Thanks in advance!

**Comment by astier** [comment]
I have pretty much the same setup as you. I don't have this issue. Does it also happen with vanilla tmux and nvim without a tmux.conf and init.vim? Does it happen with other terminals? Maybe its one of your st-patches which causes it. Are you on st-0.8.4?

**Comment by astier** [comment]
Which tmux-version do you use?

**Comment by erw7** [comment]
A possible explanation is that `st-256color` in terminfo is out of date. What will be the result of the following commands?

```
infocmp -x st-256color | egrep 'Ss|Se'
```

Is `Se=\E[2 q, Ss=\E[%p1%d`? If it's not, and it's in `Se, Ss`, it's old. In that case, try recreating the terminfo with `st.info` in the latest st source. Or make the following settings in `.tmux.conf`.

```
set-option -ga terminal-overrides "st*:Ss=\\E[%p1%d q,st*:Se=\\E[2 q"
```

Another possibility is that tmux is old. But the `git log` shows that `tmux` supports changing the cursor shape with `Ss` and `Se` since `1.9a`. Therefore, I don't think you are using that old version.

**Comment by Kyle-Thompson** [comment]
@astier To answer your questions:
* My tmux version is `tmux next-3.3` so I'd imagine the problem isn't being out of date.
* I have verified that the problem persists with a config-less tmux and neovim.
* I tried it in termite and the issue does not occur there. In tmux switching to insert mode still switches to the bar properly. This is likely an issue with one of the many patches to my ST.
* My branch of ST starts after this patch `096b125 2018-12-11 Lauri Tirkkonen output child WEXITSTATUS/WTERMSIG on abnormal termination`
* If you're curious about what changes I've made, the repo is here https://github.com/Kyle-Thompson/st/. Perhaps you'll find something I've missed.

@erw7 As for your question, the command returned no output. See below
```
~ > infocmp -x st-256color | egrep 'Ss|Se'
~ > echo $TERM
st-256color
~ > infocmp
#       Reconstructed via infocmp from file: /usr/share/terminfo/s/st-256color
st-256color| simpleterm with 256 colors,
        am, bce, ccc, hs, mir, msgr, npc, xenl,
        colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
        acsc=+C\,D-A.B0E``aaffgghFiGjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        cvvis=\E[?25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
        el1=\E[1K, enacs=\E)0, flash=\E[?5h$<80/>\E[?5l, fsl=^G,
        home=\E[H, hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
        il=\E[%p1%dL, il1=\E[L, ind=\n, indn=\E[%p1%dS,
        initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
        invis=\E[8m, is2=\E[4l\E>\E[?1034l, kDC=\E[3;2~,
        kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
        kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, ka1=\E[1~,
        ka3=\E[5~, kb2=\EOu, kbs=^?, kc1=\E[4~, kc3=\E[6~, kcbt=\E[Z,
        kclr=\E[3;5~, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC,
        kcuu1=\EOA, kdch1=\E[3~, kdl1=\E[3;2~, ked=\E[1;5F,
        kel=\E[1;2F, kend=\E[4~, kent=\EOM, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
        kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
        kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
        kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
        kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
        kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
        kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
        kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
        kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
        kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
        kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
        kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
        kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
        kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
        kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
        kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\E[1~, kich1=\E[2~,
        kil1=\E[2;5~, kind=\E[1;2B, kmous=\E[M, knp=\E[6~,
        kpp=\E[5~, kri=\E[1;2A, krmir=\E[2;2~, mc0=\E[i, mc4=\E[4i,
        mc5=\E[5i, oc=\E]104\007, op=\E[39;49m, rc=\E8, rev=\E[7m,
        ri=\EM, ritm=\E[23m, rmacs=\E(B, rmcup=\E[?1049l,
        rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
        rs1=\Ec, rs2=\E[4l\E>\E[?1034l, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        setb=\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
        setf=\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
        sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        sgr0=\E[0m, sitm=\E[3m, smacs=\E(0, smcup=\E[?1049h,
        smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m, smul=\E[4m,
        tbc=\E[3g, tsl=\E]0;, vpa=\E[%i%p1%dd,
~ >

```

That being said, setting the terminal-overrides like you suggested worked! Is there a resource you could recommend so I can learn about these terminal intricacies on my own? I really have no clue what's going on with everything in your answer.

It's great that it's working now and as a result I'll close the issue but it would be excellent if I could also get an understanding of WHY this is happening. Ideally I'd prefer to be more informed than blindly copy pasting commands.

Thanks a lot to you both.

**Comment by astier** [comment]
Your version of st actually doesn't work on my machine. First of all if I run `sudo make install` it says the following:

```sh
mkdir -p /usr/local/bin
cp -f st /usr/local/bin
chmod 755 /usr/local/bin/st
mkdir -p /usr/local/share/man/man1
sed "s/VERSION/0.8.1/g" < st.1 > /usr/local/share/man/man1/st.1
chmod 644 /usr/local/share/man/man1/st.1
tic -sx st.info
"st.info", line 192, col 11, terminal 'st': expected string-type for Se, have boolean
"st.info", line 193, col 11, terminal 'st': expected string-type for Ss, have boolean
4 entries written to /usr/share/terminfo
Please see the README file regarding the terminfo entry of st.
```

The following two lines don't seem to be normal:

```
"st.info", line 192, col 11, terminal 'st': expected string-type for Se, have boolean
"st.info", line 193, col 11, terminal 'st': expected string-type for Ss, have boolean
```

@erw7 mentioned that `Se` and `Ss` need to be set correctly. Your version of st isn't doing so apparently. When I then try to start st it fails and says `could not allocate color 'color0'`.

I could reproduce your issue with my own version of st. You see I install st in `~/.local`. st creates then the directory `~/.terminfo`. If I delete `~/.terminfo` or set `$TERMINFO` to a path where no `.terminfo` can be found I get the same issue like you. Changing the cursor without tmux in st works. With tmux it stops working.

I think this issue is not related to nvim but rather to st and terminfo. Something goes wrong during the installation process it seems. You should update your st. It seems to be an old version. The patches may be also out of date.

You could try to install the latest vanilla st 0.8.4 without patches and see if it works there.

**Comment by Kyle-Thompson** [comment]
I had no idea how out of date my ST was. I totally forgot to keep pulling in the new patches from suckless so that must be a contributing factor. Thanks for the effort you've put into helping me. I'm basically going to restart my ST build from master and reapply the few patches I need. In the meantime I'll just keep the tmux overrides but hopefully updating my terminal fixes things more cleanly moving forward. Thanks again!
