### ISSUE TITLE
`equalalways` is smarter on splitting than closing

### ISSUE THREAD

**Issue by ubitux** [neovim/neovim#12738]
Relevant info:
- `NVIM v0.4.4`
- `vim 8.2.0814` [behaves the same](https://github.com/vim/vim/issues/5955)

`nvim -u NORC -c "vs | vs | sp | res +15 | winc l | winc l | sp | clo"`

```
What I got:       What I expected:

┌───┬───┬───┐     ┌───┬───┬───┐
│   │   │   │     │   │   │   │
├───┤   │   │     │   │   │   │
│   │   │   │     ├───┤   │   │
└───┴───┴───┘     └───┴───┴───┘
```

`equalalways` is on by default, and if you don't do the last close (`nvim -u NORC -c "vs | vs | sp | res +15 | winc l | winc l | sp"`) you realize the last split on the right doesn't trigger a global window equalization affecting the left split:

```
┌───┬───┬───┐
│   │   │   │
│   │   ├───┤
├───┤   │   │
└───┴───┴───┘
```

 This is a good thing: the left side should not be affected by the creation of a split on the opposite side. On the other hand, closing does affect it for some reason.

**Comment by justinmk** [comment]
This is by design

**Comment by ubitux** [comment]
I'm sorry but how is that even close to an explanation? This is a pretty rude way of handling a bug report.
