### ISSUE TITLE
Is is possible to dynamically set inline "virtual text"?

### ISSUE THREAD

**Issue by theniceboy** [neovim/neovim#12737]
Hi, I'm trying to write a plugin for Neovim that draws these "UI Guidelines" for flutter/dart code. 
![Screen Shot 2020-08-09 at 9 22 04 AM](https://user-images.githubusercontent.com/8187501/89722904-ea6cdb80-da21-11ea-94b1-65fa97f655bd.png)
I came across `virtual text`, but it seems like it can only be drawn at the end of a line. I also considered using `conceal`, but it's syntax matching based. I want to be able to dynamically set these "UI Guidelines" base on results from LSP. Does Neovim have a feature to do this? If not, is there one planned? Thanks!

**Comment by justinmk** [comment]
also https://github.com/neovim/neovim/pull/9496
