### ISSUE TITLE
Already at oldest change - Can't undo 

### ISSUE THREAD

**Issue by drskoolie** [neovim/neovim#12735]
I can't reproduce this, but it happened to me twice now. When I'm into a vim session, after some time I can't undo anymore. I'm getting the message "Already at Oldest Change". And even if I change anything like deleting a line and I press u, I still get the message "Already at Oldest Change". 

==============================

- `nvim --version`:
NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-86EB6J/neovim-0.5.0+ubuntu1+git202008011335-1153ac9-00e710e=. -fstack-protector-strong -Wformat -Werror=format-security -
U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fall
through -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_
LEVEL=3 -I/build/neovim-86EB6J/neovim-0.5.0+ubuntu1+git202008011335-1153ac9-00e710e/build/config -I/build/neovim-86EB6J/neovim-0.5.0+ubuntu1+git202008011335-1153ac9-00e710e/src -I/build/
neovim-86EB6J/neovim-0.5.0+ubuntu1+git202008011335-1153ac9-00e710e/.deps/usr/include -I/usr/include -I/build/neovim-86EB6J/neovim-0.5.0+ubuntu1+git202008011335-1153ac9-00e710e/build/src/
nvim/auto -I/build/neovim-86EB6J/neovim-0.5.0+ubuntu1+git202008011335-1153ac9-00e710e/build/include
Compiled by buildd@lgw01-amd64-034

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Operating system/version: 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

- Terminal name/version: Alacritty Version 0.5

**Comment by justinmk** [comment]
try

    :set hidden

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by a-elhag** [comment]
It just happened again, and I tried your suggestion but it didn't work @justinmk

**Comment by a-elhag** [comment]
@justinmk  It's not a usage/configuration, it's a bug. It just happened again and when I did `:set hidden` it didn't fix it. 

And googling shows that at least one other person had this issue and they didn't seem to be able to fix it:
https://stackoverflow.com/questions/31421037/why-does-vim-always-say-already-at-oldest-change-when-i-try-to-undo

**Comment by feliperama** [comment]
I have the same issue constantly...

**Comment by dundargoc** [comment]
Reopening as this still seems to be an issue

**Comment by justinmk** [comment]
> It just happened again and when I did `:set hidden` it didn't fix it.

`set hidden` won't "fix it" unless you set that from the start of your nvim session. That allows undo info to be preserved even when hiding a buffer.

There are no repro steps here.

**Comment by codexshell** [comment]
Solved it by switching to vscode vim version 1.0.0.(This was my best guess since tracking from whence it became an issue was a bit tricky). Honestly speaking while in vscode, the core experience of vim is what you should almost always care about. If you find yourself interested in more than the core features, I would recommend ditching vscode and  going vim full-blown!!!
