### ISSUE TITLE
No assets for Windows on the current stable release (0.4.4)

### ISSUE THREAD

**Issue by lambdalisue** [neovim/neovim#12730]
**It's not a bug report.** I could not find the correct place to tell it thus I used the issue. 

The current `stable` release does not have assets for Windows and AppImage which used to have. So please upload them.

![image](https://user-images.githubusercontent.com/546312/89704558-b648da80-d98f-11ea-9a7b-16e1b9738f4b.png)

P.S.
I refer these assets through https://github.com/rhysd/action-setup-vim to test my plugins in GHA.

**Comment by jamessan** [comment]
Fixed.
