### ISSUE TITLE
set guifont=Jetbrains\ Mono

### ISSUE THREAD

**Issue by TheIce-star** [neovim/neovim#12740]
If you try to set the font to jetbrains mono
we know space key is written as \<space>
but
~~~vim-script
set guifont=Jetbrains\ Mono
~~~
Neovim will give your tips
~~~
warning: Font "Jetbrains Mono" reports bad fixed pitch ...
~~~
I hope you can solve this problem

Tips:
    I'll also ask questions in JetBrains mono's warehouse
Thank you
Neovim community

**Comment by jamessan** [comment]
Neovim doesn't have a GUI. You need to report this to the project for whatever GUI you're using.

Assuming it's neovim-qt, there are [various issues](https://github.com/equalsraf/neovim-qt/search?q=bad+fixed+pitch&type=Issues) covering it.
