### ISSUE TITLE
Misbehaving folds (folds incorrect number of lines)

### ISSUE THREAD

**Issue by Marc-Bender** [neovim/neovim#12747]
- `nvim --version`: 0.4.3 (from Fedora Repos)
- `vim -u DEFAULTS` (version: ) behaves differently? : E282
- Operating system/version: Fedora 32 
- ```uname -a```: Linux DESKTOP 5.7.12-200.f32.x86_64 #1 SMP Sat Aug 1 16:13:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Terminal name/version: xfce4-terminal 0.8.9.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
```
:vnoremap <silent><Leader>f  :'<,'>fold<CR>
```
Then select multiple lines of content with ```V4j``` (4 is an example) and fold them with \f (see above mapping). 

### Actual behaviour
Folds random number of lines (including those lines which are not selected (or ommitting some of them)). Remapping the above mapping to 
```
:vnoremap <silent><Leader>f  :fold<CR>
```
(so ommiting the visual selection markers (that should be put in automatically and thus might be duplicate or superflous (and thus maybe a reason for the issue))) does not impact the result in any way.
The mapping above is only given for the fact that this is the way I would choose to use the feature. A quick test by typing the :fold command by hand does not impact the behaviour in any way.
### Expected behaviour
Folds the (in the above example 4) selected lines. No more no less. And only the selected ones...

**Comment by KillTheMule** [comment]
Can't reproduce on an older version of 0.5. Of course, that command selects 5 lines, not 4, but that's probably besides the point. Are you sure there's nothing else mucking with the folds (i.e. did you really use `-u NORC`)?

**Comment by Marc-Bender** [comment]
@KillTheMule  I will make a short screencap and put that up on youtube as an unlisted video where i try to reproduce this.

**Comment by Marc-Bender** [comment]
@KillTheMule There you go https://youtu.be/sigjSM5K_zA

**Comment by KillTheMule** [comment]
<rant> Videos are annoying imho, I really have to guess keypresses and klick on the timelime to get back and forth to find out what's going on. It's really better to give a sequence of keypresses that produces the wrong result</rant>

So, how are you deleting the folds? I'm guessing you don't, and the result you're seeing is just overlapping folds being closed together. Try playing around with `zo` and `zc`, or try `set foldcolumn=5` or so to see what's going on. That's standard behavior and should be the same in vim.

**Comment by Marc-Bender** [comment]
pressing l opens them ... on my side. 

zo and zc i have to look up. 

sadly screenkey is absent from the fedora repos...

**Comment by KillTheMule** [comment]
> It takes some tries to get to the mentioned behavior... so a list of keypresses is not exactly as helpful as you might think.

Hmm I could just reproduce the thing with the first 2 folds directly, and that was just normal behavior.

> Done: https://youtu.be/iRA8zM1Lg3E

Can you point out a specific point at the video at which there's something incorrect? Please from the `-u NORC` portion.

**Comment by Marc-Bender** [comment]
NORC section of the vid starts at 1:05 (perceived) misbehavior starts at 1:49 
if you think this is normal behavior you hopefully can enlighten me by pointing out the part of the manual that says so. 
I am still kinda noob with vim and just from what i see i cant think that this is actually what is supposed to happen. 

Regarding zo and zc:
zo and zc clearly do what you would expect them to do (opening and closing folds (whyever folds have keybinds with z by default)) and it seems as if zd is doing likewise (deleting a fold) that folds are persistent actually makes a ton of sense. Not having any indication on what is part of the fold once unfolded does not. (To me).

**Comment by KillTheMule** [comment]
> NORC section of the vid starts at 1:05 (perceived) misbehavior starts at 1:49

Totally reproducable, no idea where you get the random idea from. Feels working, although the last step is a bit weird indeed.

> if you think this is normal behavior you hopefully can enlighten me by pointing out the part of the manual that says so.

No idea. (Manual) folds can feel weird indeed. Start at `:h usr_28.txt` if you're interested.

> Not having any indication on what is part of the fold once unfolded does not. 

Try that `foldcolumn` option.
