### ISSUE TITLE
LSP: support for snippet insertion with parameters

### ISSUE THREAD

**Issue by lanza** [neovim/neovim#12753]
Sorry, but I couldn't come up with a better title description. But I'm talking about the behavior in, for example, the [first gif](https://user-images.githubusercontent.com/35623968/76489411-3ca1d480-6463-11ea-8c3a-7f0e3c521cdb.gif)
 on [completion-nvim](https://github.com/nvim-lua/completion-nvim) when the user inserts the `for` statement. 

Completion plugins use some clever heuristics to remap tab (e.g. coc.nvim uses `nnoremap <tab> <C-R>=coc#rpc#request('snippetNext', [])<CR>`) and jump the cursor around a few times to do whatever it is that's necessary to setup the functionality. This causes pretty noticeable lag to the user and is clearly a bit disorienting to see things jump around whenever you do this as compared to emacs, VSCode, Visual Studio, Xcode etc who all have proper builtin support for this feature.

I think it would make a huge different to have a `expand_as_snippet` viml or lua API that actually does this all natively and provides actual objects for vim motions (e.g. such that `das` would `delete snippet-parameter` and there could be a naturally unmapped parameter jump forward and backward analogous to `w` and `b`.)

**Comment by clason** [comment]
This is indeed a big ask, but it is already available through plugins:
* https://github.com/norcalli/snippets.nvim
* https://github.com/nvim-lua/completion-nvim
Note that you will always have problems if you want to have a "magic tab" that does different things depending on context, but expanding and advancing forward (and backwards) with (shift-)tab works well for me with these two.

**Comment by Shougo** [comment]
It should be implemented by plugins.
Because it is very complex feature.

**Comment by bfredl** [comment]
At least the lua _interface_ for a snippet plugin should be standardized. so you can just add snippets.nvim or deoppet with one line and LSP snippets automagically works.

**Comment by Shougo** [comment]
> At least the lua interface for a snippet plugin should be standardized. so you can just add snippets.nvim or deoppet with one line and LSP snippets automagically works.

neosnippet already support the feature.  deoppet.nvim does not yet.

**Comment by lanza** [comment]
> This is indeed a big ask, but it is already available through plugins:
> 
> * https://github.com/norcalli/snippets.nvim
> * https://github.com/nvim-lua/completion-nvim
>   Note that you will always have problems if you want to have a "magic tab" that does different things depending on context, but expanding and advancing forward (and backwards) with (shift-)tab works well for me with these two.

You missed the point. These plugins are always slow because they execute this in vim-script/lua via vim APIs whereas other editors all do it as part of their core functionality in native code. You can watch as the cursor jumps 6 times for the parameter upon accepting a completion in vim. In native implementations it all is inserted at once fluidly.

**Comment by bfredl** [comment]
Lua code is native in neovim.

**Comment by clason** [comment]
> Lua code is native in neovim.

To expand on that, the only difference between those plugins and an implementation in core is where these files would live on your disk (and whether you could update them independently of neovim). For example, almost all of the core LSP functionality is implemented in Lua via neovim's API.

And comparing with other editors is apples vs. oranges (as far as "native" is concerned). For what it's worth, I've never observed the described behavior with these plugins; if you have a concrete example where these do not behave as intended, that would be helpful (but probably more at the respective repo than here).
