### ISSUE TITLE
neovim seems to capture key strokes that are targeted to gnu screen

### ISSUE THREAD

**Issue by gautaz** [neovim/neovim#12754]
I am using neovim for a few years now and gnu screen for even longer, both were well working together until two or three months ago.
It took me some time to understand that quitting neovim in gnu screen was resolving the issue.
So I do not know if the root cause is located in the neovim source code or the gnu screen source code (but the issue cannot be reproduced in vim).

Here are the whole issue details:

- `nvim --version`: `NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-E1VIeX/neovim-0.5.0+ubuntu1+git202008111353-94b7ff730-00e710ec6/build/config -I/build/neovim-E1VIeX/neovim-0.5.0+ubuntu1+git202008111353-94b7ff730-00e710ec6/src -I/build/neovim-E1VIeX/neovim-0.5.0+ubuntu1+git202008111353-94b7ff730-00e710ec6/.deps/usr/include -I/usr/include -I/build/neovim-E1VIeX/neovim-0.5.0+ubuntu1+git202008111353-94b7ff730-00e710ec6/build/src/nvim/auto -I/build/neovim-E1VIeX/neovim-0.5.0+ubuntu1+git202008111353-94b7ff730-00e710ec6/build/include
Compiled by buildd@lgw01-amd64-012`
- `vim -u DEFAULTS` (version: `7.4.1689`) behaves differently? Yes, no issue
- Operating system/version: Ubuntu 16.04 (`Linux AMA-LT-4549 4.15.0-112-generic #113~16.04.1-Ubuntu SMP Fri Jul 10 04:37:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`)
- Terminal name/version: `GNOME Terminal 3.18.3` (bug was also reproduced with other terminals)
- `$TERM`: `screen-256color`
- Gnu screen version: `Screen version 4.03.01 (GNU) 28-Jun-15`

### Steps to reproduce using `nvim -u NORC`

- open a terminal
- start gnu screen
- launch `nvim -u NORC` in the already opened screen
- start a new screen (`crtl-a c`)
- enter screen copy mode (`ctrl-a esc`)
- use `ctrl-b` to scroll up in the screen buffer

### Actual behaviour

Currently using `crtl-b` in the alternate screen in copy mode will quit the copy mode and display `^B[O` on the command line.
In fact all keystrokes starting with `ctrl` seem to fail (as long as screen copy mode is opened).

### Expected behaviour

The expected behavior is that gnu screen copy mode continues to interpret correctly the `ctrl` keystrokes even when neovim is started in one of its screens.

**Comment by justinmk** [comment]
Thanks for the report. Will help a lot if you can [bisect](https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git) to find the exact commit that changed the behavior.

**Comment by gautaz** [comment]
Hi @justinmk, here is the result of the bisect:

```
✔  ~/dev/neovim [:3de9452ab|BISECTING|✔ ]
gautaz@workstation  ➤  git bisect good
f3ffe0b325170dd214b80e371bee5a56b7054940 is the first bad commit
commit f3ffe0b325170dd214b80e371bee5a56b7054940
Author: erw7 <erw7.github@gmail.com>
Date:   Sun Apr 26 22:15:47 2020 +0900

    tui: improve support for GNU Screen (#12098)
    
    Wrapping it in DCS allows the following features to work with GNU
    Screen.
    
    - Changing the cursor style.
    - bracketed paste.
    - focus reporting.

 src/nvim/ascii.h   |   2 +
 src/nvim/tui/tui.c | 147 +++++++++++++++++++++++++++++++++++++----------------
 2 files changed, 106 insertions(+), 43 deletions(-)
```

It seems that the GNU Screen support improvement did broke a few other things.

Perhaps part of the updates made by @erw7 depend on the GNU Screen configuration used, here is mine:

```
defscrollback 10000
startup_message off
term screen-256color
maptimeout 5
```

I hope this will ring a bell :-).

**Comment by erw7** [comment]
The FocusOut event sends `\x1b[O` and the screen copy mode seems to have ended, but it seems odd to me that the FocusEvent is triggered by pressing down `Ctrl-b`. In any case, such problems are inevitable when sending control sequences wrapped in a `DCS` to the host terminal. I don't think I'll ever use screen, so I don't have any particular opinion on whether it's better to be able to use bracketed paste and focus reports etc in neovim or not have problems with other applications. If the person using screen doesn't need them, they will revert the relevant changes.

In the meantime, you can use `markkeys` as a workaround for this problem.

**Comment by gautaz** [comment]
@erw7 I have done some additional testing since and the problem occurs not only for the copy mode but also when using `Ctrl-a` to switch from one screen to another.

The result is not only a screen switch but also that `Ctrl-a` is sent to the shell and the cursor goes to the beginning of the command line.
This is quite annoying and I guess using `markkeys` won't help in this particular case.
