### ISSUE TITLE
LSP: Support multiple clients with different capabilities

### ISSUE THREAD

**Issue by heapslip** [neovim/neovim#12755]
This is more of a question than a bug.

You can have multiple clients active at the same time, with different capabilities. Calling LSP methods such as `vim.lsp.buf.hover()` will execute the respective method on all the active clients, which will throw an error for the clients that don't have the requested capability.

Is there any way to either:
- Call a LSP method on a specific client / list of clients?
- Supress those error messages?

Patching the callbacks is too late, as the error is there already, and setting fake capabilities triggers `unhandledMethod`.

Thank you for all your hard work, the performance is awesome, and when the small bugs will be fixed (treesitter, etc) it's going to be perfect.

**Comment by fsouza** [comment]
I have this implemented in my prepareRename PR that's been kinda abandoned for a bit, trying to find some time. I can split that part of the change into a separate PR, as it's ready (the PR is wip on the prepareRename change, but the capabilities change should be good to go).

**Comment by fsouza** [comment]
Opened #12764 :D

**Comment by heapslip** [comment]
This is awesome, thank you!
