### ISSUE TITLE
serveral beeps when changing mode using PuTTY

### ISSUE THREAD

**Issue by Steve19802** [neovim/neovim#12769]
- `nvim --version`:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/ubuntu/workspace/neovim/build/config -I/home/ubuntu/workspace/neovim/src -I/usr/include -I/usr/local/include -I/home/ubuntu/workspace/neovim/build/src/nvim/auto -I/home/ubuntu/workspace/neovim/build/include
Compiled by ubuntu@ubuntu

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: 8.1) behaves differently?
yes. it does not beep on a mode change
- Operating system/version: arm64
- Terminal name/version: PuTTY Release 0.73
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# press 'i' to enter into insert mode
# press 'ESC' to leave insert mode
# press 'v' to enter into visual mode
# press 'ESC' to leave insert mode
```

### Actual behaviour
A beep is generated on each step of the sequence described above

### Expected behaviour
No beep should be generated

### Possible Root Cause
After digging in the code and debugging I found that PuTTY rings the bell every time the following sequence is received
```
 \033]112\a
```
Looking at the code I found that this sequence matches with the `reset_cursor_color` defined inside the `augment_terminfo` function in the `tui.c` file. The actual code looks like this:
```
 if (-1 != data->unibi_ext.set_cursor_color) {
     data->unibi_ext.reset_cursor_color = (int)unibi_add_ext_str(
        ut, "ext.reset_cursor_color", "\x1b]112\x07");
 }
```
The issue seems to happen because the `\x07` (BELL or ALARM) character is being processed by PuTTY not only as a string terminator but also fires a beep.  

What I did was to replace the '\x07' with the original string termination character '\x9c'. This is the complete change:
```
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 2be15a7d4..e1aff442c 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -1902,7 +1902,7 @@ static void augment_terminfo(TUIData *data, const char *term,

   if (-1 != data->unibi_ext.set_cursor_color) {
     data->unibi_ext.reset_cursor_color = (int)unibi_add_ext_str(
-        ut, "ext.reset_cursor_color", "\x1b]112\x07");
+        ut, "ext.reset_cursor_color", "\x1b]112\x9c"); // changed to avoid puttys annoying beeps
   }

   data->unibi_ext.save_title = (int)unibi_add_ext_str(
```

After recompiling, the annoying beeps disappeared

### Further Analysis
Since I'm not an expert on xTerm commands and I have only tested using PuTTY I don't know what implications this change could generate on other environments.
I've tested with tmux and seems to be working well, but at the end I'm still using PuTTY

**Comment by chrisbra** [comment]
Are you sure that xterm-256color is correct for putty? IIRC  there exist a couple of putty related terminfo definitions.

**Comment by justinmk** [comment]
Thanks for investigating! But yes, please try other $TERM type as suggested

**Comment by Steve19802** [comment]
I've just changed my $TERM to putty-256color and everything is working as expected. My bad that I didn't double check this before creating this issue.

**Comment by elandorr** [comment]
For the record: using putty-256color is not a solution per today, as it breaks colors in random ways. They themselves recommend xterm as they strive to emulate it.

I would prefer a clean fix, but right now only disabling bells altogether helps.

**Comment by dundargoc** [comment]
@elandorr would you mind opening a new issue? Even if this issue is related I think an exact reproduction with your specific problem would be more valuable. Bonus points if you link to this issue and explain why it isn't a proper solution.
