### ISSUE TITLE
ddkP mapping doesn't work when used on first line

### ISSUE THREAD

**Issue by MuAlphaOmegaEpsilon** [neovim/neovim#12762]
- `nvim --version`: NVIM v0.5.0-581-g267bc57d2
- `vim -u DEFAULTS` (version: 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)) behaves differently? No, same behaviour
- Operating system/version: Ubuntu 20.04
- Terminal name/version: Gnome Terminal emulator
- `$TERM`: screen

### Steps to reproduce using `nvim -u NORC`
Suppose file.txt is a file with a few written lines:
```
nvim file.txt -u NORC
```
Inside neovim, define the following mapping to move the current line up by one row each time `z` is pressed:
```
:nmap z ddkP
```

### Actual behaviour
The current line is moved up by one row, except when applied on the first line of the file: in such case the line is deleted, but never pasted again, which is equivalent to a simple `dd`.
Using this mapping repeatedly on the first line will eventually delete the entire file content, since pasting is never performed.

### Expected behaviour
The current line is moved up by one row.

### Hints
From a user perspective, it seems like the `k` part of the mapping breaks the entire mapping when performed on the first line.

**Comment by bew** [comment]
Note: You'd be better off using the move command:
```
nnoremap z :move -2<cr>
```
Also note that `z` is the start of some vim commands that you may want to use sometimes

**Comment by chrisbra** [comment]
This is not an error and documented at `:h map-error`

**Comment by MuAlphaOmegaEpsilon** [comment]
@bew thank you for the hint, I'll try replacing with that.

@chrisbra I suspected something like this, but didn't find anything related until now.

I'm closing this.
