### ISSUE TITLE
Some vimL functions should be available to Lua even while in fast events

### ISSUE THREAD

**Issue by tjdevries** [neovim/neovim#12779]
Should Neovim special case some functions to be available for lua execution even while in fast events?

For example, it seems you should be able to call something like `filter` or `reltimestr` or similar (that don't affect the editor). Any of these functions that are "pure" functions (not sure if that's the exact right term for this case).

Do we have any plans for this or even any desire to do this?

@norcalli @justinmk @bfredl

**Comment by norcalli** [comment]
Seems like extra code complexity for little benefit considering that users should be able to do the same from Lua without us special casing them. While I do see why it could be fine in principle, idk if it's worth it long term assuming we do our job right and have a decent lua stdlib.

**Comment by justinmk** [comment]
Are any eval functions really pure though? The eval engine itself may read/modify global state, to setup the Vimscript function call and then teardown its result.

I can see an analog here to `FUNC_API_FAST`, but that is not necessarily something we want more of: it means we have to document all the special functions and users need to care about this.

Let's favor a generalized solution if possible, or a generalized workaround of some sort.

**Comment by bfredl** [comment]
Just add more Lua functions already. `vim.fn` is back compat, not the future.

**Comment by tjdevries** [comment]
It feels sad to just drop all the functions related to, for example, `file-functions`, `date-functions`, `time-functions` that are well understood and already portable to all the systems neovim ships to. I don't know if any of the other ones would be helpful (like `float-functions` -- but I suppose we could just add comparable functions in Lua. Or perhaps even just add the functions as a thin wrapper over some of these lua functions that are not exposed over `vim.fn` would be fine as well.

**Comment by justinmk** [comment]
> It feels sad to just drop all the functions related to, for example, `file-functions`, `date-functions`, `time-functions` that are well understood and already portable to all the systems neovim ships to

Would agree if something were being dropped. But nothing is being dropped. 

> but I suppose we could just add comparable functions in Lua.

I'm not in favor of rewriting/duplicating anything in Lua in general.

**Comment by bfredl** [comment]
We should just add into Lua (and API_FAST Lua) what we need in lua, regardless of if a viml function exists or not. ("Eventually", like 2022, we should reimplement eval.c in lua as zyx-i intended it).

**Comment by tjdevries** [comment]
I guess I'm confused on where this leaves us? We don't want to duplicate the code, but we don't want to expose it over `vim.fn` or similar.

Does anyone have any suggestions for this? I have, in some of my plugins, directly called the C code that I know is in Neovim's core by using luajit's FFI. I don't think that's what we want to do either? :laughing:

**Comment by bfredl** [comment]
@tjdevries you have to be specific what functionality you want from core first

**Comment by bfredl** [comment]
@tjdevries "We should just add into Lua (and API_FAST Lua) what we need in lua," what is unclear about this? forget about what bram vim does or does not do in its various interfaces and async modes, that is completely irrelevant. you have to tell us what _you_ want specifically from neovim lua API.
