### ISSUE TITLE
bug when using python2

### ISSUE THREAD

**Issue by Yggdroot** [neovim/neovim#12772]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

test.vim
```python
py << EOF
import vim
b = vim.buffers[1]
print(b == vim.current.buffer, b != vim.current.buffer)
EOF
```

1. nvim test.vim
2. :so %

### Actual behaviour

outputs (True, True)

### Expected behaviour

outputs (True, False)

**Comment by KillTheMule** [comment]
Can't reproduce on current master. I also tried with `py3` which worked properly as well.

**Comment by Yggdroot** [comment]
> 
> 
> Can't reproduce on current master. I also tried with `py3` which worked properly as well.

`py3` did work well. I report it for py2.

**Comment by Yggdroot** [comment]
I updated pynvim with `python2 -m pip install --user --upgrade pynvim`, and it works well now.
