### ISSUE TITLE
Cannot use VimEnter event to do nohlsearch, shada interferes

### ISSUE THREAD

**Issue by latricewilgus** [neovim/neovim#12776]
I don't know whether this behaviour is intended, a bug, a inconsistency, or a documentation failure.

# Problem

The goal is to not highlight the last search result, when starting up Neovim. I thought I can use the VimEnter event for that, however, the shada mechanism seems to interfere.

We are using the following file:
testrc.vim
```vim
set shada-=h
autocmd VimEnter * nohlsearch | echomsg "setting nohlsearch"
```

Then do
```
nvim -u testrc testrc
/autocmd<CR>
:q
nvim -u testrc testrc # redo that as sometimes the shada gets not update (see remark below); better safe than sorry (*)
/autocmd<CR>
:q
nvim -u testrc testrc # no for the real test
```
In the last case I expect that autocmd is not highlighted (as we issued nohlsearch), however it is.

(The following three-liner might also work (and gets rid of plugins) but might not be the best way to reproduce:
``
nvim -u NONE --cmd "set shada-=h | autocmd VimEnter * nohlsearch | echomsg 'setting nohlserach'" testrc`
nvim -u NONE --cmd "set shada-=h | autocmd VimEnter * nohlsearch | echomsg 'setting nohlserach'" testrc` (*)
nvim -u NONE --cmd "set shada-=h | autocmd VimEnter * nohlsearch | echomsg 'setting nohlserach'" testrc`

```
)

# Shada interference?

There is the "h" parameter for 'shada' which reads:

```
Disable the effect of 'hlsearch' when loading the shada file.
```

Since it is not present, it should not interfer with our test.

(*) Note that the description is incomplete/wrong by omission as I think the flag also affects what is *written* to the shada file.
I quickly looked into the .c source and from the little I understood, I believe the "h" flags dictates what is written in the `.highlighted` attribute of a shada entry.
Hence the correct "h" flag in 'shada' must be set at read *and write* time.

Next looking at the documentation of |startup| process, it states
```
[...]
10. Read the ShaDa file
	See |shada-file|.
[...]
13. Execute startup commands
        [...]
	The |VimEnter| autocommands are executed.
```
So to my understanding the VimEnter event should override whatever the shada mechanism does.
(Ok, if you want to be pedantic and nitpicky, then it says it reads the shada file, and not that it also applies the settings it found ... but c'mon we cannot seriously consider that an explanation)

From what I see, I could imaging that the highlighting stuff of shada is done on opening the buffer or so, which would be after the `VimEnter` event and thus overruling our nohlsearch command.

# Where to go from here?

So what is the problem? Did I miss something?

# P.S.

I know that `set shada^=h` is pretty close to what I want (and surely a viable solution for every day life). But has slightly different behaviour as the shada mechanism can be retriggered during a editing session with
```
:wshada | rshada!
```
while the VimEnter mechanism cannot.

Furthermore, the data stored in the shada file seems to be different in these two solutions (cf Remark (*)).
Moreover, there might be more subtleties which differentiates these two.

Neovim version 0.4.3

**Comment by justinmk** [comment]
hlsearch is special and weird. try this https://github.com/neovim/neovim/issues/1719#issuecomment-67943891
