### ISSUE TITLE
vim's sass.vim has already updated.

### ISSUE THREAD

**Issue by yangxyo** [neovim/neovim#12787]
https://github.com/vim/vim/blob/master/runtime/syntax/sass.vim

It should be updated.

**Comment by yangxyo** [comment]
https://github.com/vim/vim/issues/6781

**Comment by mhinz** [comment]
This needs to be reported to the maintainer of that synax file. Create an issue for it here: https://github.com/tpope/vim-haml

Then it gets merged into Vim and we merge it from them.
