### ISSUE TITLE
LSP: don't enable snippetSupport unconditionally

### ISSUE THREAD

**Issue by clason** [neovim/neovim#12795]
In #12118, rudimentary snippet support was implemented for snippets as completion results. However, this does not cover all cases, in particular multi-line snippets (e.g., the `for` snippet from https://github.com/sumneko/lua-language-server) -- such snippets end up either as a single-line placeholder or even throw an error.

Arguably, this means that the built-in LSP client does _not_ provide (full) `snippetSupport` and therefore shouldn't advertise it in https://github.com/neovim/neovim/blob/43202964f39eed4e28fd8ad6ad0ec79a1868c33f/runtime/lua/vim/lsp/protocol.lua#L643. It may be better to set this to `false` here and leave it to snippet plugins (or https://github.com/nvim-lua/completion-nvim when such a plugin is detected) to enable it.

@tjdevries @haorenW1025 @runiq

**Comment by tjdevries** [comment]
Can close now? :smile:
