### ISSUE TITLE
There is no nvim-macos.tar.gz on pre-release 0.5.0

### ISSUE THREAD

**Issue by IIPatternII** [neovim/neovim#12790]
Just what the title says. I need 0.5.0 as a new requirement of the VSCode extension [vscode-neovim](https://github.com/asvetliakov/vscode-neovim).

Thank you for your time.

**Comment by IIPatternII** [comment]
Uploaded! Thank you!

**Comment by disrupted** [comment]
same issue, nvim-macos.tar.gz is not available from the GitHub releases page for nightly 0.5.0
