### ISSUE TITLE
folds don't open when using / in a map

### ISSUE THREAD

**Issue by nebulaeandstars** [neovim/neovim#12806]
- `nvim --version`: 0.4.4
- Operating system/version: Arch linux, LSB: 1.4
- Terminal name/version: st 0.8.4
- `$TERM`: st-256color

### Steps to reproduce

1. define (and close) a fold
2. have "bar" inside the fold
3. `nnoremap <leader>foo /bar<CR>`
4. `<leader>foo`

### Actual behaviour

The cursor finds bar, but does not open the fold.

### Expected behaviour

The fold should open to be consistent with what would happen if `/bar<CR>` was pressed manually.

**Comment by jamessan** [comment]
This is documented in [`:help 'foldopen'`](https://neovim.io/doc/user/options.html#'foldopen'):

> 	NOTE: When the command is part of a mapping this option is not used.
	Add the |zv| command to the mapping to get the same effect.
