### ISSUE TITLE
different behaviour between nvim's terminal and true terminal

### ISSUE THREAD

**Issue by Freed-Wu** [neovim/neovim#12807]
### Expected behaviour

```{.jl}
# ~/.julia/config/startup.jl
# juia: v1.4.0
using OhMyREPL # OhMyREPL has been installed
# julia
```

copy some code.

such as

```{.jl}
plot(
```

paste them in repl of julia.

the result is
![julia-julia](https://user-images.githubusercontent.com/32936898/91625885-764ca480-e9dd-11ea-852f-908f1bb326df.png)

### Actual behaviour

Now, return to vi.

```{.vim}
" FILE: $XDG_CONFIG_HOME/nvim/test.vim
" OS: linux v5.4.13
" VI: nvim v0.4.3
" TERM: guake v3.7.0
" export $TERM=xterm-256color
set runtimepath=$VIMRUNTIME
terminal julia
" vi -u $XDG_CONFIG_HOME/nvim/test.vim
```

paste the test code.
![vi-julia](https://user-images.githubusercontent.com/32936898/91625890-7f3d7600-e9dd-11ea-9dad-8fd4e746d061.png)

it will insert a bracket automatically.

in fact, some plugin like OhMyREPL in julia or oh-my-zsh in zsh, will insert
')' when user insert '(' and do nothing when user paste a code. (looks like
`set paste` in vim).
it is ppearant in this case that vi should not add a spare bracket when user
paste code, which will bother user. for example, when user paste the following
code, the spare bracket will make user crazy.

```{.jl}
plot(
xlabel = "x",
ylabel = "y",
x,
[y1, y2]
)
```

in zsh. the case is same.
![zsh-zsh](https://user-images.githubusercontent.com/32936898/91625896-882e4780-e9dd-11ea-908d-5e69543c640b.png)

```{.vi}
" FILE: $XDG_CONFIG_HOME/nvim/test.vim
" OS: linux v5.4.13
" VI: nvim v0.4.3
" TERM: guake v3.7.0
" export $TERM=xterm-256color
set runtimepath=$VIMRUNTIME
terminal zsh
" vi -u $XDG_CONFIG_HOME/nvim/test.vim
```

![vi-zsh](https://user-images.githubusercontent.com/32936898/91625899-911f1900-e9dd-11ea-87c9-7ed5ffa5e290.png)

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/11418
