### ISSUE TITLE
shellquote option applied incorrectly for PowerShell

### ISSUE THREAD

**Issue by PunkIslamist** [neovim/neovim#12805]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: ) only neovim is installed, so I don't think this applies?
- Operating system/version: Windows 10 19041
- Terminal name/version: PowerShell Core 7.0.3, Windows Terminal 1.2.2381.0
- `$TERM`: not set

### Steps to reproduce 

Add settings to init.vim as described by `:help shell-powershell`.
Restart with `nvim` and execute `:!ls`

### Actual behaviour

The parentheses seem to get applied incorrectly - `(` is added twice instead of `(` and `)` once, as can be seen in the screenshot.

![image](https://user-images.githubusercontent.com/26367652/91589739-8ec7ab00-e95a-11ea-8d77-686fbc186479.png)

### Expected behaviour

After adding the recommended settings from the help, command should be executed successfully.

**Comment by jamessan** [comment]
Based on the behavior you expect, it seems like your settings for `'shellquote'` and `'shellxquote'` are reversed.  The help explicitly states that when `'shellxquote'` is `(`, a `)` will be used to close the quote.

**Comment by justinmk** [comment]
Note that `:help powershell` was updated in master (unreleased): https://github.com/neovim/neovim/blob/fbbc8cb8b110ebf05f33dd4bce83a59b7a79d822/runtime/doc/options.txt#L5209

the old version that you're seeing in 0.4.x had some mistakes

**Comment by PunkIslamist** [comment]
> Note that `:help powershell` was updated in master (unreleased):
> 
> https://github.com/neovim/neovim/blob/fbbc8cb8b110ebf05f33dd4bce83a59b7a79d822/runtime/doc/options.txt#L5209
> 
> the old version that you're seeing in 0.4.x had some mistakes

Great, thanks for letting me know! I am now using these settings and the error is, indeed, fixed.

**Comment by justinmk** [comment]
backporting that doc to 0.4 branch: https://github.com/neovim/neovim/pull/12822
