### ISSUE TITLE
Default Cursor highlight (guifg=bg guibg=fg) could not be used to restore from blend=100 cursor

### ISSUE THREAD

**Issue by lambdalisue** [neovim/neovim#12800]
- `nvim --version`: NVIM v0.5.0-nightly
- `vim -u DEFAULTS` (version: ) behaves differently?: Vim does not support `blend=100`
- Operating system/version: macOS Catalina 10.15.6
- Terminal name/version: iTerm2 3.3.12
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Requirements
:set termguicolors
:highlight InvisibleCursor gui=reverse blend=100
# Hide cursor
:set guicursor+=a:InvisibleCursor
# Restoring cursor with Cursor (guifg=bg guibg=fg) does not work
:set guicursor+=a:Cursor
# Restoring cursor with TermCursor (cterm=reverse gui=reverse) works
:set guicursor+=a:TermCursor
```

![Kapture 2020-08-28 at 09 04 54](https://user-images.githubusercontent.com/546312/91506655-96149780-e90d-11ea-86bb-1515c836aca9.gif)

### Actual behaviour

`Cursor` highlight is not applied thus the cursor keeps invisible.

### Expected behaviour

`Cursor` highlight applied and the cursor become visible.

### Note

If I define `Cursor` highlight manually (e.g. `ctermfg=234 ctermbg=252 guifg=#161821 guibg=#c6c8d1`), `set guicursor+=a:Cursor` restore cursor thus it seems the highlight `guifg=bg guibg=fg` cause this issue.

### Related
https://github.com/neovim/neovim/issues/12796
https://github.com/lambdalisue/fern.vim/issues/177

**Comment by erw7** [comment]
If you start with `nvim -u NORC`, the normal foreground and background colors are not set. The `:h syntax` contains the following:

> When Vim knows the normal foreground and background colors, "fg" and "bg" can be used as color names.  This only works after setting the colors for the Normal group and for the Windows console. 

Therefore, this seems to me to be a normal behavior.

**Comment by Iron-E** [comment]
Removing `InvisibleCursor` and _then_ adding `Cursor` back using `guicursor` causes the cursor to reappear for me too.

**Comment by Iron-E** [comment]
I have found that using `sleep` for ≥1millisecond changes this behavior (see lambdalisue/fern.vim#183) so that no `set guicursor -=` has to be used. I don't know if it's relevant or not but I thought it should be included in case someone tries to Google this issue later.

**Comment by lambdalisue** [comment]
@erw7 

I see. But then I feel it's not consistent behavior while the cursor is visible on startup with `Cursor` highlight which uses `fg/bg`. If `fg/bg` is not defined and using `fg/bg` breaks the highlight, I feel that the cursor should be invisible on startup (and `Normal` must be defined to fix that behavior.) What do you think?

@Iron-E 
I see. I think there is some bug on Neovim if `sleep 1m` fix the issue....

**Comment by erw7** [comment]
> I see. But then I feel it's not consistent behavior while the cursor is visible on startup with Cursor highlight which uses fg/bg. If fg/bg is not defined and using fg/bg breaks the highlight, I feel that the cursor should be invisible on startup (and Normal must be defined to fix that behavior.) What do you think?

OK. Originally, the following procedure should restore cursor. So I created #12811.

```vim
nvim -u NORC
:set termguicolors
:highlight Normal guifg=white guibg=black
:highlight InvisibleCursor gui=reverse blend=100
:set guicursor+=a:InvisibleCursor
:set guicursor-=a:InvisibleCursor
```

**Comment by lambdalisue** [comment]
Thanks for that. If above works, I feel that the behavior is consistent.H 👍
