### ISSUE TITLE
ins-completion results order

### ISSUE THREAD

**Issue by eyalk5** [neovim/neovim#12813]
- `vim -u DEFAULTS` (version: ) behaves differently? no 
configuration
```
	set completeopt=menu
	set completeopt+=noinsert 
        set cpt = .,w,b,u,t
```

When doing `<c-x><c-n>` or `<c-x><c-p>` the suggestions are displayed in the order they appear in file(I think).
Often, the last(bottom)  completion suggestion is the closest to what you are looking for if it is just above your cursor.
Therefore, I suggest to fix it so that it would display results by distance(and maybe nu of encounters), or at least to have an option to reverse the menu.

**Comment by justinmk** [comment]
I strongly recommend watching https://www.youtube.com/watch?v=3TX3kV3TICU&t=3s to understand the completion options in Vim.

The behavior of each is intentional. For your use case `ctrl-x ctrlo` or `ctrl-x ctrl-u` offer a way to extend the behavior.

**Comment by eyalk5** [comment]
Hi, so I actually watched the part about <c-x><c-p>. 
He doesn't go there into specifications, but he seems to suggest that it selects the best option on the menu.  In any case, the option appears at the bottom, where some prefer it at the top. So an option to reverse the menu is nice. 

I would like to confirm my educated guess that it is ordered by the order in the file (if there are several matches). 

<c-x><c-o> does something completely different which often uses plugins. 
<c-x><c-u> asks for completion function, althogh could have been useful. 

There is no replacement for completion using parts of sentences which is what I often want, and did a lot.
