### ISSUE TITLE
Doesn't load file under autoload folder

### ISSUE THREAD

**Issue by glepnir** [neovim/neovim#12812]
- `nvim --version`: v0.5.0-c6648fe
- `vim -u DEFAULTS` (version: ) behaves differently? don't have vim
- Operating system/version: macos 10.15.6
- Terminal name/version: kitty
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
├── autoload
│   ├── initself.vim
│   └── theme.vim
```
1. `nvim --startuptime  time.txt`
2. check time.txt , I don't fine load `initself.vim` and `theme.vim`

Does `nvim -u NORC` can check this ? I run it and the result is same.

### Actual behaviour
Doesn't load file that in autolaod folder.

### Expected behaviour
auto load the file that in autoload folder.

**Comment by chrisbra** [comment]
that is not how autoloading works. Please read `:h autoload` for an introduction.

**Comment by glepnir** [comment]
I want to say that u called a function in autoload/initself.vim&nbsp; that define a command. when open vim it prompt me is not an editor command.&nbsp; it works for me before.&nbsp; when reinstall neovim with HEAD option.&nbsp; It doesnt work.&nbsp;

--------------原始邮件--------------
发件人："Christian Brabandt "<notifications@github.com&gt;;
发送时间：2020年8月31日(星期一) 凌晨1:37
收件人："neovim/neovim" <neovim@noreply.github.com&gt;;
抄送："Raphael "<glepnir@gopherhub.org&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [neovim/neovim] Doesn't load file under autoload folder (#12812)
-----------------------------------

 

 
that is not how autoloading works. Please read :h autoload for an introduction.
