### ISSUE TITLE
parse colon in path (":<number>") as line number

### ISSUE THREAD

**Issue by rodrigosetti** [neovim/neovim#1281]
This will open that file in the buffer with the cursor at the specified line number.

Basically, implement the functionality of https://github.com/bogado/file-line

Better yet is to accept also `:<line>:<column>`, as many programs output that format.

**Comment by justinmk** [comment]
Does https://github.com/kopischke/vim-fetch solve everyone's use cases here?

**Comment by fmoralesc** [comment]
Should fix if for the simplest case. It still won't be able to support // or # addresses, as required in plan9-form-vimspace ;)

**Comment by kopischke** [comment]
@fmoralesc why don’t you open an issue for that on https://github.com/kopischke/vim-fetch? I’m not familiar with the format, but details provided, I might be able to add it to the plug-in.

**Comment by fmoralesc** [comment]
@kopischke plan9's sam (which plan9-for-vimspace) has addresses like `main.c#23` (basically, byte 23 at `main.c`) and `main.c/void main/` (search for `void main` at `main.c`) , but iirc vim won't accept `#` or `/` in filenames (it is hardcoded in the source, and the second will even throw an error which can't be catched). 

I think this format is not common enough to make it worth supporting at vim-fetch, though, but if you are interested, you can check [p9fv's address compiler](https://github.com/plan9-for-vimspace/plan9-for-vimspace/blob/master/autoload/plan9/address.vim) and [address handler](https://github.com/plan9-for-vimspace/plan9-for-vimspace/blob/master/autoload/address_handler/address_handler.vim). vim-fetch looks really nice, btw.

**Comment by kopischke** [comment]
@fmoralesc let’s take that discussion to [the issue I just created](https://github.com/kopischke/vim-fetch/issues/2) – I don’t want to hijack this thread.

**Comment by XVilka** [comment]
Would be nice to have for integration with Midnight Commander as well - e.g. I'm using NeoVim as a PAGER/EDITOR - would be very convenient to open needed line directly from the search results: https://midnight-commander.org/ticket/3862

**Comment by tompreston** [comment]
Just to be clear, the suggestion is to use either:
- https://github.com/wsdjeg/vim-fetch
- https://github.com/bogado/file-line

**Comment by thiagowfx** [comment]
FYI: https://github.com/bogado/file-line is unmaintained for 5+ years and it seems to be broken. If I do `~/.vimrc:42:10` it opens the file in L42 however it doesn't go to C10.

https://github.com/wsdjeg/vim-fetch is working in both cases.

**Comment by cassepipe** [comment]
The default vim behaviour is intrusive because you can't directly open files that start with a `+` within the terminal.
Sveltekit routing files have special names that start by a `+` for example

Also both plugins are apparently unmaintained

**Comment by justinmk** [comment]
Would be in favor of putting this in core, but someone needs to make a plugin that actually works well. Or say what API is needed to do so.

**Comment by cassepipe** [comment]
Does that not contradict the fact that this is issue was previously close becaused of supposedly a plugin already implementing the functionanility ?

**Comment by lewis6991** [comment]
> The default vim behaviour is not great because you can't directly open files that start with a + within the terminal.
>
> Sveltekit routing files have special names that start by a + for example.

You can get around that by prefixing the filename with `./`. The same goes fore files starting with `-`

> Also both plugins are apparently unmaintained and none is working when installed with the lazy plugin manager

https://github.com/bogado/file-line works absolutely fine. I've been using it for years.

The whole plugin is 90LOC. It doesn't matter if it's unmaintained. And either way, something being unmaintained is not a justification for adding it to core.

**Comment by lewis6991** [comment]
I think if a commenting keymap is not appropriate for core (similar cost, drastically higher value), then I personally think this isn't either.

Either way, since there are concerns about https://github.com/bogado/file-line being unmaintained, I've created a modern Lua equivalent https://github.com/lewis6991/fileline.nvim.

**Comment by tim-hilt** [comment]
@lewis6991 you're amazing!

**Comment by lewis6991** [comment]
We already have that with `'comments'` and `'commentstring'`, we just don't have anything that leverages those options.

**Comment by cassepipe** [comment]
To me the whole point of having this in core is the adoption of a better standard for referring to a file location that I think is in line with Neovim's adoption of Lua or integration of the Language Server Protocol. 

The point is to have Neovim behave even better with the outer ecosystem, it is a small thing maybe but very much in line with Neovim's _raison d'être_

**Comment by lewis6991** [comment]
This isn't defined anywhere in any spec, so I'd disagree; unlike LSP, basedir-spec and editorconfig which are properly defined outside Neovim.

**Comment by cassepipe** [comment]
Ironically enough, I tried to install your plugin in LunarVim and I got this error :
It works but I do get an error, please pay attention to how the error's location is reported:
```
Error detected while processing BufNewFile Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/lua/editorconfig.lua:210: Invalid buffer id: 1
stack traceback:
        [C]: in function 'nvim_buf_get_name'
        /usr/share/nvim/runtime/lua/editorconfig.lua:210: in function 'config'
        /usr/share/nvim/runtime/plugin/editorconfig.lua:11: in function </usr/share/nvim/runtime/plugin/editorconfig.lua:4>
```

Maybe there does not need to be a spec for something that basic ? `path/to/filename:line(:col)`
`gdb` reports file locations like that and so many other, it is a de factor standard

I think it is totallyh a coincidence, but even in (neo)vim youcan go to a specific line with `:$line`

**Comment by lewis6991** [comment]
This is already fixed in https://github.com/neovim/neovim/pull/23922 but further enforces my point that this isn't such a low cost since it already has unintended interactions with other existing systems in core thus raising the complexity.

**Comment by mcepl** [comment]
There is a possibility of much richer sublanguage for expressing these locations used by [Plan 9 ACME](https://youtu.be/dP1xVpMPn8M?t=548), which I tried to describe in [my blogpost](https://matej.ceplovi.cz/blog/design-notes-on-plan9-for-vimspace.html).

E.g., ACME can do

```
:e filename.txt:/^VIM/
```

would open the file “filename.txt” on the first line starting with the “VIM” string.

**Comment by justinmk** [comment]
> With regards to whether there is a spec or not, vim-fetch refers to `file.cpp[:ll[:cc]]` "the gnu colon format", though this representation is certainly not exclusive to GNU

Also vim's own quickfix paradigm essentially depends on this.
