### ISSUE TITLE
different behavior when <silent> is used in mappings for command line mode

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#12821]
- `nvim --version`:  v0.5.0-416-g2b00d1d09
- `vim -u DEFAULTS` (version: ) behaves differently?: No
- Operating system/version: Ubuntu
- Terminal name/version: zoc terminal
- `$TERM`: xterm-256color

### Steps to reproduce

+ use the following minimal vimrc to start neovim:

```vim
cnoremap <silent> <c-p> <c-r>"
```

`nvim -u minimal.vim test.txt`

+ Copy a line with `yy`
+ Press `:` to start command mode, and press `<c-p>`.

### Actual behaviour

Nothing pasted on the command line. If we then press another character, the copied line will be pasted.

### Expected behaviour

The copied line is pasted there when we press the shortcut.

Also note that removing the `<silent>` argument seems to fix this issue. But after reading `:h :map-<silent>`, I do not see why is this behavior.

**Comment by justinmk** [comment]
@chrisbra are you familiar with the reason for this behavior?

**Comment by jdhao** [comment]
This issue has been filed upstream in vim repo. Link [here](https://github.com/vim/vim/issues/6832).

**Comment by chrisbra** [comment]
next time, waiting for feedback here before filing the bug in the next repository would be nice. Thanks.
