### ISSUE TITLE
Support LSP folding

### ISSUE THREAD

**Issue by the42** [neovim/neovim#12836]
Some Language Servers support textDocument/foldingRange

If the capability is present, Neovim should support folding provided by the LSP.

Here is a starter how it's done in Vim (according to my understanding): https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/ui/vim/folding.vim

**Comment by mhanberg** [comment]
If I were to tackle this, is it reasonable to mimic the code lens api for refreshing folds and providing a foldexpr function?

There is an existing PR but the discussion indicates that the implementation wasn't desirable

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/14306
