### ISSUE TITLE
Syntax Highlighting on functions doesn't work.

### ISSUE THREAD

**Issue by TornaxO7** [neovim/neovim#12834]
- `nvim --version`:
```vim
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
It gives me `E282: Cannot read from "DEFAULTS"`.

- Operating system/version:
OS: Arch Linux
Output of `uname -r`:
```
5.8.5-arch1-1
```

- Terminal name/version:
```
alacritty 0.5.0
```

- `$TERM`: `alacritty`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC file.c
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
:highlight Function ctermfg=1 guifg=#00000
```

### Actual behaviour
Nothing happens! <br>
When I'm entering my `Editor.c` file, than the declaration of the functions look like this:
![image](https://user-images.githubusercontent.com/50843046/91971868-2db52400-ed1a-11ea-8e29-87289b26af2e.png)
Than if I use this command: `:highlight Function ctermfg=1 guifg=#000000`
Nothing happens. <br>
But if I use this command for my includings than this happens: <br>
When entering the file:
![image](https://user-images.githubusercontent.com/50843046/91971990-53dac400-ed1a-11ea-85e9-71c039f26842.png)
After entering this command: `highlight Include ctermfg=1 guifg=#000000`
![image](https://user-images.githubusercontent.com/50843046/91972032-6654fd80-ed1a-11ea-9309-1e007eae3252.png)
Than it changes its color! I'm using the solarized alacritty theme so that's probably the reason why it looks red instead of black.

### Expected behaviour
The highlighting of the functions should work... I miss it.

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
