### ISSUE TITLE
LSP: Plugins should be able to add capabilities

### ISSUE THREAD

**Issue by runiq** [neovim/neovim#12833]
There have now been multiple requests for the ability to let plugins add support for certain LSP capabilities (#12573: Support for snippets completion items, #12392: Support for `$/progress`). It'd probably be useful to have some kind of interface for that.

**Comment by mjlbach** [comment]
What form do you see this taking? Currently, you can (and we often do) override the capabilities from nvim-lspconfig. In fact, these completely ovewrite the default client capabilities generated by `vim.lsp.protocol. protocol.make_client_capabilities()` https://github.com/mjlbach/neovim/blob/f87ae324bb03ccd9f723a6b2a664e6058849f0f7/runtime/lua/vim/lsp.lua#L632.

Currently a plugin could override the default capabilities in nvim-lspconfig, which would therefore set the capabilities in core. Is there something particular about how this is managed in core that you thing should change?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/12277#issuecomment-726491783 mentions `vim.lsp.with` , which may be replaced by https://github.com/neovim/neovim/pull/22598 , though the ideal solution is https://github.com/neovim/neovim/pull/22598#issuecomment-1463367606 : 

> * Have some kind of future/promise/async-thunk/whatever (relates a bit to [Lua: structured concurrency, Promises, task pipelines #19624](https://github.com/neovim/neovim/issues/19624)) that each of the `vim.lsp.buf` methods returns that allows to
>   a) cancel
>   b) use the _synthesized_ result of the operation by being able to attach an additional callback or map the result. This would address [feat(lsp): return result of buf_request() in LSP functions #18372](https://github.com/neovim/neovim/pull/18372) and lots of other feature requests.
>   c) await (coroutine aware) or get(blocking) the result.
>   I already have some local version where I played around with this a bit. There I also have a new `vim.lsp.request` that would replace `buf_request`, `buf_request_all` and `buf_request_sync` and also solve the mixed-encoding warnings.
> * Maybe add a `LspResponse` autocmd that's triggered whenever a response is received with `data` set to the payload as a generic listener mechanism.
