### ISSUE TITLE
lua: vim.validate improve error reporting

### ISSUE THREAD

**Issue by tricktux** [neovim/neovim#12843]
- `nvim --version`: 0.5-nightly
- `vim -u DEFAULTS` (version: ) behaves differently?: N/A
- Operating system/version: Arch
- Terminal name/version: N/A
- `$TERM`:

### Actual behaviour

When `vim.validate` finds an error it reports from the line in the runtime file. Example: 

```
Error executing vim.schedule lua callback: shared.lua:514: lhs: expected string, got table
```

### Expected behaviour

It would be nice to add something of the sort:

```
        local info = debug.getinfo(2, "Sl")
        local lineinfo = info.short_src .. ":" .. info.currentline
```

To report the line where validate was actually called from. Now it can be traced back by the variable, but in any moderately large code base this stops being helpful.

Very useful function nonetheless :heart:

**Comment by mfussenegger** [comment]
I think this should've been addressed with https://github.com/neovim/neovim/pull/12053

**Comment by tricktux** [comment]
Indeed. #12053 closes this issue.
