### ISSUE TITLE
Updating PHP syntax file to latest from Vim

### ISSUE THREAD

**Issue by dietrichm** [neovim/neovim#12844]
Comparing Neovim's PHP syntax file with the [latest from Vim](https://github.com/vim/vim/blob/master/runtime/syntax/php.vim), I noticed the latter has been updated on May 11, 2020 and contains PHP 7.4 syntax additions.

Neovim's version has not been updated since June 2019.

What needs to happen to bring this up to date? Can I create a PR with a copy of Vim's syntax file, or are existing vim patches usually ported for this?

---

Neovim version v0.5.0-dev (2bbbb34ce)

### Actual behaviour

PHP syntax is not updated for new(er) syntax changes. I.e. `fn` is not highlighted as a definition:

```php
$values = array_map(
    fn ($value) => '__' . strtoupper($value),
    $values
);
```

### Expected behaviour

New(er) PHP syntax changes are correctly highlighted.

**Comment by glacambre** [comment]
On 2020-09-03 19:42, Dietrich Moerman wrote:
> What needs to happen to bring this up to date? Can I create a PR with a 
> copy of Vim's syntax file, or are existing vim patches usually ported 
> for this?

I believe the procedures to follow are described here: 
https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim

**Comment by dietrichm** [comment]
Thanks for the link @glacambre.

It's listed as a possible patch when running `vim-patch.sh -l runtime/syntax/php.vim`. It seems very cumbersome to just apply the oldest one listed here though. Probably needs a bunch of other (older) patches for updating runtime files.

I'll see what I can do if I find some more time (not making promises though).
