### ISSUE TITLE
Implement mousefocus

### ISSUE THREAD

**Issue by BonaBeavis** [neovim/neovim#12849]
This only worked for gvim and not in the terminal. But now with neovim `mousescroll` works, but `mousefocus` does not. Is there a technical reason, because if mousescroll works, then neovim must know about the position of the cursor, but why can't it focus on the  corresponding window?

**Comment by justinmk** [comment]
> `mousescroll` works, but `mousefocus` does not

where are you seeing a 'mousescroll' option?

> if mousescroll works, then neovim must know about the position of the cursor, but why can't it focus on the corresponding window?

Mousescroll works by keys sent by the terminal (or UI). Focus requires different keys/events. Never heard of a "hover" key sent by terminals.

We could export 'mousefocus' as a GUI option (`option_set` UI event)

**Comment by justinmk** [comment]
With https://github.com/neovim/neovim/pull/12863 , UIs now receive updates whenever the 'mousehover' option is set/reset. It's up to the UI to actually implement this though.
