### ISSUE TITLE
consistent function execution with keybinds

### ISSUE THREAD

**Issue by sum-catnip** [neovim/neovim#12856]
- `nvim --version`: NVIM v0.5.0-638-g91109ffda

# How i got here
Ok so this might seem obvious at first but please hear me out.
Im in the process of rewriting my configs in lua. While doing the keybinds i noticed something very strange.
Lets use `CocAction('diagnosticNext')` as an example, just because thats what i was binding. What this function does is jump to the next error. So i want to bind the execution of this function to a key.

As someone familliar with vimscript the following would be the obvious solution:
> `nmap <silent> [c :call CocAction('diagnosticNext')<cr>`

This would have never crossed my mind and i dont think its a good way to go about things.
What this does is type what the user would have wrote on their keyboard to interactively call the function.
Now lets say we want to do this in insert mode (i know this is not what the insert mode is for, im just making an example)
> `imap <silent> <C-e> :call CocAction('diagnosticNext')<cr>`

This would obviously not work but insert the literal text into the current line.

What i did was evaluate an expression on keypress. I think this is a reasonable thing to want:
> `nmap <silent><expr> [c CocAction('diagnosticNext')`

This doesnt work for 2 reasons:
1. `<expr> docs`: - Moving the cursor is allowed, but it is restored afterwards.
2. CocAction returns v:null which will get interpreted like keyboard input

The first can be worked around by doing it async (CocActionAsync).
The second reason is a bigger problem since there is nothing i could return that would be a NOP.

# Why do i want this?

As i said, i was writing lua config. I made a utility function to bind keys to lua functions (again, a reasonable thing in my oppinion). so i use my function like:
```lua
bind('i', 'ge]' function vim.fn.CocActionAsync('diagnosticNext') end, 'silent')
```
And it works as long as i return something in the function. currently that something is `<ESC>` since that doesnt do anything in normal mode.

We could do things like (half lua half vimscript below because im not done porting this keybind :p):
```lua
bind('n', 'K' function()
  if (index(['vim','help'], &filetype) >= 0) then
    "execute 'h '.expand('<cword>')
  else vim.fn.CocAction('doHover')
  end
end)
```
without problems.
the tldr here is: evaluating the rhs of a keybind ONLY for its side-effects would be very convenient especially for lua configs and would work in all modes.
Imagine how extensible neovim would be if we could conveniently execute any code we want in any mode with a keypress.

# What do i propose

In my opinion there are 2 solutions:
1. if the rhs of an `<expr>` binding returns nil, dont do anything
2. another kind of `<expr>` entirely

the 2nd solution is because i dont understand the restrictions of the current `<expr>`.
```Therefore the following is blocked for <expr> mappings:
- Changing the buffer text |textlock|.
- Editing another buffer.
- The |:normal| command.
- Moving the cursor is allowed, but it is restored afterwards.
- If the cmdline is changed, the old text and cursor position are restored.
If you want the mapping to do any of these let the returned characters do
that. (Or use a |<Cmd>| mapping instead.)
```
there is probably a very good reason for those restrictions (which is why solution 1 is probably best) but i dont see how moving the cursor via `nmap <silent> [c :call CocAction('diagnosticNext')<cr>` is different from moving the cursor via `nmap <silent><expr> [c CocAction('diagnosticNext')`. But again, there probably is an important difference between those i dont understand.

**Comment by justinmk** [comment]
Did you try `<cmd>` (as mentioned in the help you quoted)?

> > `imap <silent> <C-e> :call CocAction('diagnosticNext')<cr>`
> 
> This would obviously not work but insert the literal text into the current line.

    imap <silent> <C-e> <cmd>call CocAction('diagnosticNext')<cr>

**Comment by jamessan** [comment]
> The second reason is a bigger problem since there is nothing i could return that would be a NOP.

An empty string is a NOP.

**Comment by sum-catnip** [comment]
> Did you try :help <cmd> (as mentioned in the help you quoted)?

ah damn, youre right. i didnt realize i could use <cmd> in that way.

> An empty string is a NOP.

i thought so too but
```lua
bind2('n', 'ge]', function()
  vf.CocActionAsync('diagnosticNext')
  return codes.parse('<ESC>')
end, 'silent')
```
works
while
```lua
bind2('n', 'ge]', function()
  vf.CocActionAsync('diagnosticNext')
  return ''
end, 'silent')
```


does not do anything.

if anyone else finds this with a google search, you can call lua functions without returning by doing:
```lua
-- global table to hold our functions
_bindfuncs = {}
-- current bindfunc index
local bindfunc_i = 0

return function(mode, lhs, rhs, ...)
  local opt = {}
  for _, a in ipairs({...}) do opt[a] = true end

  if type(rhs) == 'function' then
    bindfunc_i = bindfunc_i + 1
    local name = 'bindfunc_' .. tostring(bindfunc_i)
    _bindfuncs[name] = rhs
    rhs = '<cmd>call v:lua._bindfuncs.' .. name .. '()<cr>'
  end

  return vim.api.nvim_set_keymap(mode, lhs, rhs, opt)
end
```

anyways,
have a great day and sorry for the preemptive issue.
