### ISSUE TITLE
Remember &is* settings on :syn definitions

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#1285]
Problem: many syntax files set &iskeyword (did not actually see much problems with things like `&isident`) setting for their own purposes which has the following problems:
1. `w` and similar motions behave in a different fashion depending on the current filetype. I do not like remembering WTF does `w` in shell files and why it does different thing from `w` in Python files.
2. `:syn include` syntax may behave poorly because included file has its own opinion on what `&isk` setting looks like.

Proposed solution:
1. Strip off any `&is*` settings from all non-syntax files.
2. When loading syntax files make Neovim save chartab on first `:syn` call and attached a refcounted reference to the saved chartab to each syntax rule (this will be `(256 + sizeof(int)) * number_of_syntax_files + sizeof(void *) * number_of_syntax_rules` memory overhead which is not much + some CPU overhead on creating ((malloc + memcpy) once per syntax file and `=` and `++` on each rule) and deleting syntax (`--` and `if`, possibly followed by `free`) rules which is nothing).
3. Add a standard plugin which will save `&is*` settings on `SourcePre` event and restore them on `Syntax`.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/11891#issuecomment-588076689

> Isn't #1285 at least partly reached with the `syn iskeyword` feature?
