### ISSUE TITLE
E117: Unknown function: ScrollStatus

### ISSUE THREAD

**Issue by guolimin1995** [neovim/neovim#12854]
- `nvim --version`:0.4.4
- `vim -u DEFAULTS` (version:801 ) behaves differently?
- Operating system/version:macos 10.15.4
- Terminal name/version:iterm2
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
Error detected while processing function ElelineScroll:
line    1:
E117: Unknown function: ScrollStatus
Press ENTER or type command to continue
Error detected while processing function ElelineScroll:
line    1:
E116: Invalid arguments for function exists
Press ENTER or type command to continue
Error detected while processing function ElelineScroll:
line    1:
E15: Invalid expression: exists(ScrollStatus()) | return '' | endif

### Expected behaviour
no error

**Comment by glepnir** [comment]
@guolimin1995  It's not neovim issue! It looks like you instal a plugin called `eleline`.  Check your neovim config. should be close.

**Comment by guolimin1995** [comment]
> @guolimin1995  It's not neovim issue! It looks like you install a plugin called `eleline`.  Check your neovim config. should be close.

I'll check it thanks
