### ISSUE TITLE
running multiple LSP providers: attempt to index a nil value

### ISSUE THREAD

**Issue by the42** [neovim/neovim#12865]
- `nvim --version`: NVIM v0.5.0-650-g4bcf54478
- nvim-lsp version(commit hash): 419fa4006e7c15cbc2f81f5110952de562494cd4
- What language server(If the problem is related to a specific language server): jsonls
- Operating system/version: Manjaro Linux x64
- Terminal name/version: Gnome

### How to reproduce the problem from neovim startup
Install jsonls via :LspInstall jsonls
Add a minimal jsonls-setup to init.vim, mine is just empty:
	nvim_lsp.jsonls.setup{}
Open a valid .json-file
execute:

:lua vim.lsp.buf.formatting_sync()

### Actual behaviour

Error is: E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:144: attempt to index a nil value

### Expected behaviour
The buffer is being formatted (pretty-printed)

### Additional notes
The documentation for jsonls
https://www.npmjs.com/package/vscode-json-languageserver

> Formatting support requires the client to support dynamicRegistration for rangeFormatting. If not supported by the client, the server will not offer the format capability.

Maybe this requires additional setup defaults for formatting to work?

**Comment by justinmk** [comment]
Agree. I've transferred this to main repo.

**Comment by fanzeyi** [comment]
Hi, I'm seeing the same error message when I restart language server / it crashes. I'm using clangd as language server and I have `autocmd BufWritePre *.h lua vim.lsp.buf.formatting_sync(nil, 1000)` for formatting on save.

**Comment by fanzeyi** [comment]
Added a `print(vim.inspect(result))` right before here:

https://github.com/neovim/neovim/blob/01ae5e7c385e2e4996db3ef217be8e0b30fb370b/runtime/lua/vim/lsp/buf.lua#L144

It gives me:

```
{
  [2] = {
    result = {}
  }
}
```

after restarting the language server. Perhaps the index should be getting the last element in `result` instead of always `[1]`? I changed that line to `result = result[#result].result` it seems to be working fine.

**Comment by mjlbach** [comment]
Both issues are I believe resolved:

1. Jsonls doesn't support formatting (only range formatting), and I added a note about this in CONFIG.md how you can mimic a full format command:
```
require'lspconfig'.jsonls.setup {
    commands = {
      Format = {
        function()
          vim.lsp.buf.range_formatting({},{0,0},{vim.fn.line("$"),0})
        end
      }
    }
}
```

2. The formatting sync issue was fixed by https://github.com/neovim/neovim/pull/13233
