### ISSUE TITLE
Documentation mentions spell/cleanadd.vim which doesn't exist

### ISSUE THREAD

**Issue by averms** [neovim/neovim#12875]
Documentation mentions `spell/cleanadd.vim` which doesn't exist. I think a good solution would be to add that script back from vim.

https://github.com/neovim/neovim/blob/aa4557920696c45335f42f03e7b23b7038b5864e/runtime/doc/spell.txt#L346

**Comment by justinmk** [comment]
> I think a good solution would be to add that script back from vim.

why?

**Comment by a-vrma** [comment]
On Wed, Sep 9, 2020 at 12:19 AM Justin M. Keyes
<notifications@github.com> wrote:
> why?

It's certainly not an essential feature but it is a useful script: if
you use `zg` and `zw` a lot to modify the spelling dictionary, your .add
files can get messy. As the documentation says, cleanadd.vim just loops
through all add files and removes the ones that got commented by `zw`.

An argument could be made that this is a pointless optimization---it's
not like having a lot of comments in .add files will cause an OOM---but
the script is only a few lines anyway.

**Comment by junkblocker** [comment]
> why?

I came looking for this too after discovering the cleanup is not working. Looked at

https://github.com/neovim/neovim/commits/master/runtime/spell

and that does not show it being removed with any reason, just never added. Is there a reason as to why it was not added instead?

**Comment by a-vrma** [comment]
I can understand why the script isn't really worth keeping. A good alternative
would be to replace the part of the documentation that talks about this script
with an example command like this:

    :g/#[^#]/d

I can send a patch for that.

**Comment by junkblocker** [comment]
> I can understand why the script isn't really worth keeping. 

I can't yet without having gotten a reason. What you are proposing is now everybody who uses this now recreating this script on their own.
