### ISSUE TITLE
Checkhealth for slow shell invocation

### ISSUE THREAD

**Issue by philiplinell** [neovim/neovim#12884]
I had some issues where multiple plugins (vim-fzf and fugitive) was slow. The problem for me was that invoking a shell was very slow, affected by my .`zshenv`(I fixed that by moving the slow stuff to `.zshrc`). The key to understanding that problem was to use `:echo system('echo hello')` and notice that the call took a couple of seconds.

So a feature request for :checkhealth would be if it could warn if invoking a new shell is _slow_ (not sure what a definition of slow should be). 

Since miss-configured dotfiles affects the neovim experience I think this would be a great addition!

Thanks for a great editor!

**Comment by tjdevries** [comment]
This would not be a terribly difficult PR to make if you're interested in doing so. I think it would be fine to add something like checking time to execute one shell command, and if it's greater than X (not sure what X is) report that time in checkhealth.

**Comment by panosl** [comment]
Sound like it's connected to #12884 ?

@philiplinell did you have that with 0.4.* or 0.5.*?

**Comment by justinmk** [comment]
#17829
