### ISSUE TITLE
Slow to quit when ephemeral mounted filesystem unavailable (shada-related)

### ISSUE THREAD

**Issue by fweep** [neovim/neovim#12896]
neovim version:

```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-hSii_s/neovim-0.5.0+ubuntu1+git201912172018-1bfccf0-00e710e=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-hSii_s/neovim-0.5.0+ubuntu1+git201912172018-1bfccf0-00e710e/build/config -I/build/neovim-hSii_s/neovim-0.5.0+ubuntu1+git201912172018-1bfccf0-00e710e/src -I/build/neovim-hSii_s/neovim-0.5.0+ubuntu1+git201912172018-1bfccf0-00e710e/.deps/usr/include -I/usr/include -I/build/neovim-hSii_s/neovim-0.5.0+ubuntu1+git201912172018-1bfccf0-00e710e/build/src/nvim/auto -I/build/neovim-hSii_s/neovim-0.5.0+ubuntu1+git201912172018-1bfccf0-00e710e/build/include
Compiled by buildd@lgw01-amd64-019
```

OS: Ubuntu 18.04

### Steps to reproduce using `nvim -u NORC`

Not entirely sure how to reproduce this on purpose, but it's related to shada and mounted filesystems.

### Actual behaviour

When exiting (`:q`), neovim stalls/hangs for 3-10 seconds before finally cleanly dropping to the shell prompt. I determined that this is happening due to shada being enabled (default options) and an ephemeral mounted filesystem being inaccessible. Specifically, I had a FUSE volume mounted (OneDrive via `rclone mount`), but the volume was unreadable (expired OneDrive token). It would happen even if I started neovim and immediately quit, without attempting to access the mounted volume in any way.

I previously edited a file `/mountpoint/foo`, and it's referenced in `~/.local/shared/nvim/shada/main.shada`. The problem occurs when `/mountpoint/foo` hangs on read, due to FUSE issues. If I completely unmount `/mountpoint`, it doesn't hang at all.

I've since fixed this via `set shada+=r/mountpoint`, although I would prefer that shada actually remember things under `/mountpoint`, but not hang trying to access them (unless I explicitly try to edit a file there).

### Expected behaviour

I don't think neovim should care whether or not the mount point is available, if I start a new neovim session and don't explicitly try to access anything under that mount point. It seems like shada is iterating over my complete edit history when I exit, and trying to access all the files in the history. I would expect it to only update state that was modified in the current neovim invocation. Besides this problem where it was hanging for me, it also seems inefficient to access every file in shada history on exit. It's not actually writing anything to the mounted volume, so I don't know what exactly it's looking at the files for. Maybe to see if they still exist? But it doesn't remove them from shada when the access fails.

**Comment by owlsome2501** [comment]
more infomation from [/r/neovim](https://www.reddit.com/r/neovim/comments/duqg7v/shada_and_external_drives/)

**Comment by sencer** [comment]
Same here

**Comment by wdoekes** [comment]
> It seems like shada is iterating over my complete edit history when I exit, and trying to access all the files in the history.

Yup. I have systemd automounts, which mount when accessed. But can't if the NAS is offline obviously.

Now my nvim hangs _forever_ at write-quit, even though I wasn't in the vicinity of said mount point :unamused:

**Comment by glacambre** [comment]
Sounds very similar to https://github.com/neovim/neovim/issues/12075 .

**Comment by bobrippling** [comment]
I think we can close this as a duplicate - the fix is [here](https://github.com/neovim/neovim/issues/12075#issuecomment-867956505)

**Comment by justinmk** [comment]
For reference from: https://github.com/neovim/neovim/issues/12075#issuecomment-867956505

> As the reddit mentions, [the fix](https://old.reddit.com/r/neovim/comments/duqg7v/shada_and_external_drives/f79zplg/) is `set shada+=r/mnt/exdisk` - instant exit for me now.
