### ISSUE TITLE
Jump to item in loclist can access invalid memory and lead to segfault (data race?)

### ISSUE THREAD

**Issue by dlukes** [neovim/neovim#12890]
This started out as https://github.com/nvim-lua/diagnostic-nvim/issues/55, but @tjdevries [suggested](https://github.com/nvim-lua/diagnostic-nvim/issues/55#issuecomment-690306803) to also report it here :) A slightly edited copy-paste of the story so far follows below.

- `nvim --version`: current nightly / compiled from source
- Operating system/version: Solus (Linux)

### Initial report

I see this happening with the LSP diagnostics location list provided by the [diagnostic-nvim](https://github.com/nvim-lua/diagnostic-nvim) plugin in conjunction with the rust-analyzer lang server, but there might be other ways to trigger it.

Steps to reproduce:

- Open the location list with diagnostics using `:OpenDiagnostic` / `:lopen`.
- Place cursor on one of the lines in the location list.
- Press enter to navigate to that location in your source code buffer.

What happens instead is either:

- the cursor jumps to a different location in the source buffer
- or this error occurs: `E92: Buffer 168430090 not found`
- or a segfault happens

Details: The buffer number in `E92` is not always the same, it tends to grow as you make more attempts to navigate from the location list, or maybe simply as you go down the list (not entirely sure which at this point). At any rate, once it gets big enough, a segfault is triggered. So the number is probably used as an invalid pointer at some point?

AFAICS, the location list as shown in the appropriate Neovim buffer looks alright -- the filenames, line and column numbers match the highlights in the source code. When I inspect the location list with `:echo getloclist(0)`, all the `bufnr`s look valid (as in, none of them are one of those suspect large numbers).

### After some more investigation

This is starting to look like a concurrency bug -- I thought I'd narrowed down the problem to [somewhere in the `qf_jump` function in `quickfix.c`](https://github.com/neovim/neovim/blob/5581ac88c60b0a3f7595088b30a8621f280b5e4c/src/nvim/quickfix.c#L2858-L2869) by adding some crude print debugging (sorry, I've no idea how to do it properly), but the behavior is not always consistent and I even once got the correct result (i.e., a jump to the correct location in the source file). So this seems to indicate that the problem is not something that happens *inside* the `qf_jump` function, but something that happens *roughly at the same time*. Also, I don't see anything suspect in the region of code I linked to (my C skills are admittedly close to non-existent, though).

Maybe the `rust-analyzer` language server happens to send a message to update the location list roughly while `qf_jump` is running, which makes the pointers `qf_jump` is working with invalid?

For illustration, here is the crude print debugging I added:

![neovim_debug_2](https://user-images.githubusercontent.com/2734517/92725564-9f215200-f36c-11ea-9966-5762e8a7c97b.png)

And here is the "debug log" I got from one run:

![neovim_debug_1](https://user-images.githubusercontent.com/2734517/92725840-02ab7f80-f36d-11ea-96ce-b206648d60bc.png)

`qf_fnum` changes once between points `c.2` and `c.3`, where nothing that should be able to change it happens in the code AFAICS, and a second time between `c.3` and `d`, where there's literally nothing else in the code. So it looks like that memory is being modified by another thread at the same time.

As I said above, this behavior is not consistent, very rarely, you even get the correct result, i.e. `qf_fnum` stays `1` throughout and the jump leads to the correct location. Somewhat more commonly, `qf_fnum` stays `1`, but the jump ends up in the wrong location.

**Comment by dlukes** [comment]
I also added some print debugging to [`eval/funcs.c/f_setloclist`](https://github.com/neovim/neovim/blob/7ba28b1aedcb88ef5643b32dc4a6bf92ac090fed/src/nvim/eval/funcs.c#L8222-L8235) and [`vim.lsp.util.set_loclist`](https://github.com/neovim/neovim/blob/7ba28b1aedcb88ef5643b32dc4a6bf92ac090fed/runtime/lua/vim/lsp/util.lua#L1317-L1326), so here's a fuller picture of the data race:

![neovim_data_race](https://user-images.githubusercontent.com/2734517/92902805-e0c00480-f421-11ea-9f36-ef7705e4b653.png)

As shown by the traceback, as `qf_jump` is running, new diagnostics are published by the lang server, which triggers an update of the loclist.

**Comment by dlukes** [comment]
Some more general thoughts: I guess originally, Vim was built with the expectation that actions are run sequentially in a blocking fashion, either triggered manually by the user or in response to some other user actions (on open, on save etc.)? So no synchronization (locks etc.) was necessary.

With LSP as a core feature, this expectation will be increasingly violated, actions are run asynchronously from different threads so that they don't block, and they can respond to activity from the lang server which is not necessarily controlled by the user (as above -- an update is received from the lang server while the user's request to jump to a location is being processed).

So updating the location list is one area where lack of synchronization can be a problem as Neovim starts bringing LSP to the forefront, but there may be others. Is this something that needs to be investigated more systematically? Or has it already been, for the most part, and this location list data race is rather a remnant that slipped through?

**Comment by tjdevries** [comment]
@bfredl you got any ideas for this?

Or maybe @erw7 or @janlazo have seen a patch that might fix this problem?

**Comment by janlazo** [comment]
Too many to count. Some may need incsearch patches so https://github.com/neovim/neovim/pull/12721 should be merged first. quickfix patches were merged out of order.

```sh
> ./scripts/vim-patch.sh -L -- 'src/quickfix*' 'src/testdir/test_quickfix.vim'
v8.1.0431
v8.1.0489
v8.1.0499
v8.1.0523
v8.1.0720
v8.1.0743
v8.1.0753
v8.1.0779
v8.1.0809
v8.1.0877
v8.1.0892
v8.1.0988
v8.1.1015
v8.1.1036
v8.1.1261
v8.1.1275
v8.1.1281
v8.1.1384
v8.1.1386
v8.1.1393
v8.1.1414
v8.1.1524
v8.1.1544
v8.1.1547
v8.1.1549
v8.1.1891
v8.1.1955
v8.1.1966
v8.1.1996
v8.1.2011
v8.1.2040
v8.1.2243
v8.1.2297
v8.1.2310
v8.1.2320
v8.1.2322
v8.1.2339
v8.1.2360
v8.1.2394
v8.1.2401
v8.2.0004
v8.2.0095
v8.2.0156
v8.2.0243
v8.2.0260
v8.2.0261
v8.2.0275
v8.2.0293
v8.2.0295
v8.2.0500
v8.2.0523
v8.2.0559
v8.2.0634
v8.2.0644
v8.2.0687
v8.2.0853
v8.2.0869
v8.2.0917
v8.2.0933
v8.2.0934
v8.2.0936
v8.2.0959
v8.2.1040
v8.2.1049
v8.2.1061
v8.2.1101
v8.2.1102
v8.2.1183
v8.2.1255
v8.2.1281
v8.2.1384
v8.2.1420
v8.2.1432
v8.2.1557
v8.2.1591
v8.2.1593
v8.2.1599
v8.2.1618
```

```sh
> ./scripts/vim-patch.sh -L --grep loclist
v8.2.1096
v8.2.1101
v8.2.1618
```

There is https://github.com/neovim/neovim/pull/12855 for patch v8.1.0523 but the older patches should be merged first.

**Comment by dlukes** [comment]
It occurs to me that there's a stack of location lists, right? So maybe no explicit synchronization is needed in this case after all, just making sure that `f_setloclist` pushes a new location list on the stack instead of stomping over the one `qf_jump` is holding onto at the same time. Maybe one of those patches above fixes that? (Thanks for digging them up!)

**Comment by erw7** [comment]
This issue is related to https://github.com/vim/vim/commit/b6f1480. But vim 8.1.0489 seems to be incomplete. That's why I created vim/vim#6946.

**Comment by dlukes** [comment]
Looking at vim/vim#6946 -- does that mean that if the loclist changes while `qf_jump` is running, `E926: Current location list was changed` will be raised? That's certainly better than the current behavior (wrong jump / obscure buffer id error / segfault), but not ideal.

It would be fine if it only happened every once in a while, but in the LSP scenario described in OP, almost every attempt to jump to a diagnostic in the loclist would result instead in `E926`, which would mean the feature would remain basically unusable, though not fatal anymore.

(Sorry for the noise if the above is not the case -- I wanted to try the patch out and see for myself but was unable to figure out which older patches I would need to apply first in order for that one to succeed, even with the help of `vim-patch.sh -m`. I'll retry later if I can find the time.)

**Comment by dlukes** [comment]
I managed to transcribe and apply 8.1.0431 (which `vim-patch.sh -m` identified as a missing prereq), 8.1.0489 and vim/vim#6946 (sort of -- I get a heap of warnings when compiling) and just wanted to confirm that the behavior is as described in [my previous comment](https://github.com/neovim/neovim/issues/12890#issuecomment-691714123): repeated `E926`s, I never saw the jump to location succeed, though it might in theory, every once in a while, if the stars align just right.

However, I also occasionally still encounter a segfault. Admittedly, I may have made a mistake adapting the patches, but if not, I think I can see why. AFAICS, 8.1.0489 and vim/vim#6946 stash away the initial value of `qi->qf_curlist` into `old_qf_curlist`, and then at a later point use it to check if `qi->qf_curlist` has changed.

But that doesn't prevent `qi->qf_curlist` from being read in the meantime as it's being written to by another thread, so it's still possible to read junk from that region in memory and trigger a segfault when an invalid pointer is extracted from that junk.

**Comment by janlazo** [comment]
@dlukes Did you try out https://github.com/neovim/neovim/pull/12904?

**Comment by dlukes** [comment]
@janlazo I have now (thanks for bringing it to my attention!), but unfortunately the behavior is the same -- `E926` and ultimately a segfault as I try entries further down the loclist.

**Comment by dlukes** [comment]
Good thinking @erw7 coming up with nvim-lua/diagnostic-nvim#57 as a workaround in the plugin that meets Neovim half-way! Without #12904, this actually results in the appropriate behavior :) Unfortunately, with #12904 applied, I still get `E926` whenever I attempt a jump from the loclist.

On the bright side, I haven't encountered a segfault either way. The potential is undoubtedly still there, but it looks like nvim-lua/diagnostic-nvim#57 makes it less likely in practice.

**Comment by erw7** [comment]
nvim-lua/diagnostic-nvim#57 and #12904 should have solved this problem. Therefore, it is closed.

**Comment by dlukes** [comment]
> nvim-lua/diagnostic-nvim#57 and #12904 should have solved this problem

Thank you so much! With both patches applied, I was [previously](https://github.com/neovim/neovim/issues/12890#issuecomment-692767266) encountering `E926` when jumping from the loclist in my test file, but everything seems to be working great now :)

(Maybe I'd previously misapplied the patches? I'm also currently on a different machine though, as I currently have to work from home. I'll double-check on the original machine as soon as I get the opportunity.)
