### ISSUE TITLE
Documentation for libnvim?

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#12898]
I have an IDE-like application written in C++ that I want to embed nvim into. Under `:help api` it says

> Applications can also embed libnvim to work with the C API directly.

I've been searching for documentation on this to no avail. How can this be done?

**Comment by bfredl** [comment]
It is planned. For 0.6 if not earlier.

**Comment by clason** [comment]
For now, you can look at https://github.com/qvacua/vimr (which I think is the only project actually using it at the moment?)

**Comment by brhsiao** [comment]
> It is planned. For 0.6 if not earlier.

Do you mean the documentation is planned, or the release of libnvim is planned?

**Comment by bfredl** [comment]
You can use libnvim today in principle, there is just no distinction between private and public headers (so any internal code change might break your libnvim). The aim for 0.6 is to define and document a public API for libnvim.

**Comment by max397574** [comment]
Any updates on this?

**Comment by clason** [comment]
No.

**Comment by justinmk** [comment]
tracked in https://github.com/neovim/neovim/issues/21693
