### ISSUE TITLE
No error reporting for functional tests.

### ISSUE THREAD

**Issue by splinterofchaos** [neovim/neovim#1290]
I want to create a very simple test, but it fails and I can't figure out why:

```lua
local helpers = require('test.functional.helpers')
local clear, feed, insert = helpers.clear, helpers.feed, helpers.insert
local execute, expect = helpers.execute, helpers.expect

describe('nvim', function()
  before_each(clear)

  describe('can insert NULs', function()
    feed('ia<C-V>000b<Esc>')
    expect('a\x00b')
  end)
end)
```

The output:

> ●●●●●●●●●●●●●
13 successes / 0 failures / 0 errors / 0 pending : 0.0 seconds
CMake Error at /home/admin/src/neovim/cmake/RunTests.cmake:22 (message):
  Unit tests failed.

If I delete the `can insert NULs` test, it succeeds (still 13 successes), but I have no idea why it fails.

**Comment by justinmk** [comment]
> Another facet of this issue: I've got a test causing an infinite loop or wait on travis, but tell me if, from this output, you can tell which one:

This is fixed by the [utfTerminalDetailed](https://github.com/neovim/neovim/pull/2156) output provider.
