### ISSUE TITLE
`:make` won't show program output

### ISSUE THREAD

**Issue by unavaliabl3** [neovim/neovim#12910]
- `nvim --version`:NVIM v0.5.0-653-g948e625e1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compilé par appveyor@APPVYR-WIN

Features: -acl +iconv +tui

- `vim -u DEFAULTS` : no difference
- Operating system/version: Windows 10/10.19041.388
- Terminal name/version:Windows Terminal / 1.2.2381.0
- `$TERM`:Windows doesn't have $TERM
- GNU make is shipped with MingW64
### Steps to reproduce using `nvim -u NORC`
Write a Makefile that calls eternal programs that prints to stdout
```make
run:
    @gcc test.c -o test
    ./test
```
contents of test.c
```c
#include<stdio.h>

int main()
{
  for (int i = 1; i < 10; i++)
  {
    for (int j = 1; j <= i; j ++)
    {
      printf(" %d ",j);
    }
    printf("\n");
  }
}
```
and run :make command in nvim

### Actual behavior

nvim won't display the output of the program.

```
".\test.c" 13L, 160C écrit(s)
:!make  >C:\Users\Ubuntu\AppData\Local\Temp\nvimMZw55j\2 2>&1

(1 sur 9) : 1
Appuyez sur ENTRÉE ou tapez une commande pour continuer
```

but if I run ``` make ``` directly in the shell, the output of the program will be displayed
worth to mention that nvim on Linux does not have this problem.
### Expected behavior

:make command displays the program's output in the nvim

```
"test.c" [dos] 13L, 160C written
:!make  2>&1| tee /tmp/nvimX452JB/2
 1
 1  2
 1  2  3
 1  2  3  4
 1  2  3  4  5
 1  2  3  4  5  6
 1  2  3  4  5  6  7
 1  2  3  4  5  6  7  8
 1  2  3  4  5  6  7  8  9

(1 of 9): 1
Press ENTER or type command to continue
```

**Comment by 3N4N** [comment]
The solution I mentioned in the comment directly above has a problem.  Looks like piped commands don't propagate error codes, so the exit code of, say, `:make` won't be correctly retrieved if `tee` is used.  PowerShell has a solution for this: use `Tee-Object` instead of `tee` because it propagates error code.

__What I am having trouble understanding__ is, bash piping also doesn't propagate error codes by default.  You have to do `set -o pipefail` to enable that.  Then how is nvim getting proper error code for `:make` even though it's tee-ing the output?

NOTE: All this observation comes from dealing with this test --

https://github.com/neovim/neovim/blob/e0e474a4bb42c24cf13662135f53a164a826f48e/test/functional/ex_cmds/make_spec.lua#L24-L31

This test is performed only for powershell, but I ran it manually for 'shell=cmd' and it doesn't show `shell returned 3`.

**Comment by 3N4N** [comment]
`let &shellpipe='2>&1 | tee %s'` works perfectly for cmd.  So we're can consider it resolved.

Onto powershell.

```
let &shellpipe  = '2>&1 | %%{ "$_" } | Tee-Object %s; exit $LastExitCode'
```

This ^ works perfectly for PowerShell Core (`pwsh`), but for some reason, for old PowerShell (`powershell`), the output is truncated and begins with unexpected Unicode characters.

```
Unknown first argument: foo

shell returned 3

(1 of 2): <ff><fe>U
```

Whereas the output should be, and with `pwsh` the output _is_ --

```
Unknown first argument: foo

shell returned 3

(1 of 1): Unknown first argument: foo
```

**Comment by 3N4N** [comment]
For cmd, the user needs this.
```
    let &shellcmdflag = "/s /c"
    let &shellredir = ">%s 2>&1"
    let &shellpipe = "2>&1 | tee %s"
    let &shellquote = ""
    let &shellxquote = "\""
```

For either powershell or pwsh, the user needs this.

```
    let &shellcmdflag = "-NoLogo -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new();$PSDefaultParameterValues['Out-File:Encoding']='utf8';"
    let &shellredir = '2>&1 | %%{ "$_" } | Out-File -Encoding UTF8 %s; exit $LastExitCode'
    let &shellpipe  = '2>&1 | %%{ "$_" } | Tee-Object %s; exit $LastExitCode'
    let &shellquote = ""
```
