### ISSUE TITLE
Colorcolumn disappears after switching buffer

### ISSUE THREAD

**Issue by noib3** [neovim/neovim#12918]
- `nvim --version`: NVIM v0.4.4
- `vim -u DEFAULTS` (version: 8.1) behaves differently? yes
- Operating system/version: macOS 10.15.5
- Terminal name/version: alacritty 0.5.0 (a6681e3)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. open a test file: `nvim -u NONE test1`
2. set colorcolumn for the current buffer: `:setlocal cc=80`
3. open a new test file: `:e test2`
4. go back to the previous buffer: `:b test1`

### Actual behaviour

The colorcolumn is no longer visible, but `:setlocal cc?` still returns `colorcolumn=80`.

### Expected behaviour

The colocolumn is still visible when switching back to `test1`.

**Comment by zeertzjq** [comment]
Should be Vim patch 8.1.2073

**Comment by amerixan** [comment]
Also tested on Vim 8.2.2434, which works.  I think this bug can be closed.

**Comment by zeertzjq** [comment]
#16841 hasn't been merged yet.
