### ISSUE TITLE
Rewrite runtime files in Lua? 

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [neovim/neovim#12916]
I was wondering if this project would support pull request for rewriting all the files in the runtime directory from legacy vim script to Lua. It seems strange to me to have them written in vim script when one of neovim's greatest strengths is it's ability use Lua (I've recently started rewrite my config in Lua and have noticed a pretty significant drop in load time).

I understand that much of this will have to wait for the autocmd api.

Also if the project is amicable with the rewrite would a pull request to extend the filetype detection to be on par with that of vim-polyglot be acceptable?

**Comment by KillTheMule** [comment]
One huge factor to consider here is future work needed. Right now, neovim does not concern itself with most runtime files, but rather pulls updates from vim. Vim itself also does not manage the runtime files, but individual maintainers do. Rewriting them in lua would certainly not mean those maintainers keep 2 versions up-to-date, so the work of managing updates would fall to neovim. That is A LOT of work (which is the reason e.g. vim does not involve itself, but rather mechanically pulls in what the maintainers send), and my gut tells me this is not warranted.

A better idea might be to selectively rewrite performance-sensitive runtime files in lua. If there's a demonstrable upside, and if there's a maintainer for that new file, that might justify the additional load.

**Comment by bfredl** [comment]
The immediate priorities (for writing lua code) is to get tree-sitter and LSP up and working for as many filetypes as possible. We can do this without touching the upstream runtime files most at all.

For rewrites in lua it probably makes more sense to rewrite our _own_ vimL modules (like rplugin, checkheath, etc), but as @KillTheMule said it would be good to have some metric of performance and where a rewrite could make the most difference of end users.

**Comment by Th3Whit3Wolf** [comment]
@KillTheMule I was unaware that's where neovim got it's runtime files from. Thank you for your indepth response!

Would a Lua replacement of  `filetype. vim` with more file extensions (with all of the filetype extensions found in vim-polyglot)?
I don't have numbers on how much time this could save (I can benchmark it later and post it in here) but both `filetype.vim` and vim-polyglots's ftdetect file are over 2,000 lines of code, although I believe the actual autocmd are probably less than 500vin vim-polyglot. Vim-polyglot's script takes 19ms according to their Readme, a good portion of that is if statements for checking variables. I think there's potential for a 'filetype.lua' that can reduce load time and it unnecessary for the user to need to install a plugin for neovim to understand what filetype its working with.

@bfredl where can I find all the neovim modules eligible for a Lua rewrite?

**Comment by bfredl** [comment]
@Th3Whit3Wolf there is no "list", the point is we need to consider each case and decide if it is worth the effort. For instance, the `man.vim` plugin from upstream was rewritten in lua, not only for performance but also because that contributor had ideas how to improve the experience. But if you want a concrete suggestion: making it convenient to write _new_ `checkhealth` tests in lua might make more sense, before rewriting all of the existing tests into lua.

**Comment by bfredl** [comment]
also, there has been earlier discussions about rewriting the `filetype.vim` "dispatcher" _itself_. You might want to talk to @norcalli for that, he had some ideas about that before.

**Comment by Th3Whit3Wolf** [comment]
@bfredl thank you for all of the information! I will checkout checkhealth tonight.

What would changes to the dispatcher look like? I was unable to find any issues related to that?

**Comment by Th3Whit3Wolf** [comment]
Close for now. May post later with benchmarks if interesting.
