### ISSUE TITLE
UI Protocol: make neovim send hint for history hiding

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#12929]
It is currently expected that UIs will figure out when to hide `msg_history_show` messages by themselves.

I think this is bad for two reasons:
- It makes UIs less similar, increasing the number of things to learn when going from one UI to another.
- It makes UIs different from the TUI, which offers a `press ENTER` prompt when the time to hide `msg_history_show` messages has come.

After [discussing this on Gitter](https://gitter.im/neovim/neovim?at=5f62492cdf4af236f91009b5), @bfredl suggests hooking in the `press ENTER` mechanism in a configurable way:

>yea, we could do that
>hook in the press-enter thing
>we probably want a global option to enable/disable press-enter across all message kinds

I'm not sure I see the value of doing this for all message kinds as neovim already tells UI when to hide them and the TUI does not offer a `press ENTER` prompt every time a message is `echo`'ed, but it would be useful to have that for msg_history_show.

**Comment by GeorgeSheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by bfredl** [comment]
@GeorgeSheridan yes I think it is.

If any interested newcomer has questions, just ping me : )

**Comment by claudemuller** [comment]
Howdy @bfredl 

I'm a newcomer, love Neo(Vim) and would love to give it a shot. Mind if I do?

**Comment by bfredl** [comment]
@claudemuller please go ahead. Also join https://gitter.im/neovim/neovim for general questions about development :)

**Comment by verforma** [comment]
VeriForma has released its powerful platform, PNFile, which is used to perform various operations on directories and any plain text files efficiently. It is easy to get, launch, and use.
 
    - VeriForma's platform PNFile provides a one-stop graphic solution to handle directories and text files.
    - VeriForma's platform PNFile has integreated many powerful tools, like PNEdit, PNTree, PNDiff, and PNConsole.
    - To get more information, please view the products in, click here http://www.veriforma.com/vfproducts.
    - To download tools and documents, please click here http://www.veriforma.com/vfdownload.
    - To discuss your requirements, please contact us http://www.veriforma.com/vfcontact.

Business: info@veriforma.com
Sales: sales@veriforma.com
Support: support@veriforma.com

**Comment by devbhansingh** [comment]
@claudemuller any updates?
Can I take this up?

**Comment by glacambre** [comment]
@claudemuller @devbhansingh Here's a small reproducer if you want:
```python
import time
from pynvim import attach
from threading import Thread

def isInteresting (evt):
    return True

class UIThread(Thread):
    def __init__(self, nvim):
        Thread.__init__(self)
        self.nvim = nvim
        self.do_print = False
    def run(self):
        self.nvim.run_loop(self.callback, self.callback)
    def callback(self, event_name, events):
        if self.do_print:
            [print(event) for event in events if isInteresting(event[0])]

nvim = attach('child', argv=["nvim", "--embed", "-u", "NORC", "-i", "NONE"])
ui = UIThread(nvim)
ui.start()

# Create a ui with 5 lines of 80 characters. ext_messages is important because
# it frees the line that would be used for the command line.
nvim.async_call(nvim.ui_attach, 80, 5, ext_linegrid = True, ext_messages = True, rgb = True)

# Fillup history
nvim.async_call(nvim.input, ":echom 1<CR>")
nvim.async_call(nvim.input, ":echom 2<CR>")
nvim.async_call(nvim.input, ":echom 3<CR>")

time.sleep(1)
ui.do_print = True

# Print history
nvim.async_call(nvim.input, ":messages<CR>")

# Simulate user pressing keys
time.sleep(1)
nvim.async_call(nvim.input, ":<Esc>")

time.sleep(1)
ui.do_print = False
nvim.async_call(nvim.input, ":qa!<Enter>")
time.sleep(1)
```
This will print the following:
```
['msg_clear', []]
['cmdline_show', [[[0, 'messages']], 8, ':', '', 0, 1]]
['mode_change', ['cmdline_normal', 4]]
['flush', []]
['cmdline_hide', [1]]
['msg_history_show', [[['echomsg', [[0, '1']]], ['echomsg', [[0, '2']]], ['echomsg', [[0, '3']]]]]]
['mode_change', ['normal', 0]]
['flush', []]
['cmdline_hide', [1]]
['msg_showmode', [[]]]
['mode_change', ['normal', 0]]
['flush', []]
```
Notice how there aren't any `msg_history_clear` messages.

But replace `nvim.async_call(nvim.input, ":messages<CR>")` with `nvim.async_call(nvim.input, ':echo "A"<CR>')` and you'll get the following output:
```
['msg_clear', []]
['cmdline_show', [[[0, "echo 'A'"]], 8, ':', '', 0, 1]]
['mode_change', ['cmdline_normal', 4]]
['flush', []]
['cmdline_hide', [1]]
['msg_show', ['echo', [[0, 'A']], False]]
['mode_change', ['normal', 0]]
['flush', []]
['msg_clear', []]
['cmdline_hide', [1]]
['msg_showmode', [[]]]
['mode_change', ['normal', 0]]
['flush', []]
```
`echo "a"` is sent with a `msg_show` which is then cleared by a `msg_clear` message.

**Comment by quklali** [comment]
import time
from pynvim import attach
from threading import Thread

def isInteresting (evt):
    return True

class UIThread(Thread):
    def __init__(self, nvim):
        Thread.__init__(self)
        self.nvim = nvim
        self.do_print = False
    def run(self):
        self.nvim.run_loop(self.callback, self.callback)
    def callback(self, event_name, events):
        if self.do_print:
            [print(event) for event in events if isInteresting(event[0])]

nvim = attach('child', argv=["nvim", "--embed", "-u", "NORC", "-i", "NONE"])
ui = UIThread(nvim)
ui.start()

# Create a ui with 5 lines of 80 characters.
nvim.async_call(nvim.ui_attach, 80, 5, ext_linegrid = True, ext_messages = True, rgb = True)

# Fillup history
nvim.async_call(nvim.input, ":echom 1<CR>")
nvim.async_call(nvim.input, ":echom 2<CR>")
nvim.async_call(nvim.input, ":echom 3<CR>")

time.sleep(1)
ui.do_print = True

# Print history
nvim.async_call(nvim.input, ":messages<CR>")

# Simulate user pressing keys
time.sleep(1)
nvim.async_call(nvim.input, ":<Esc>")

time.sleep(1)
ui.do_print = False
nvim.async_call(nvim.input, ":qa!<Enter>")
time.sleep(1)

**Comment by xxiaocheng** [comment]
s
#m annhuinymn￼n n![image](https://user-images.githubusercontent.com/25473324/107147019-a6ce3c80-6986-11eb-836e-3f520d804c26.jpeg)nn
