### ISSUE TITLE
nvim_buf_add_highlight does not work same as <= v0.4.3

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#12924]
- `nvim --version`: master
- `vim -u DEFAULTS` (version: ) behaves differently? 
- Operating system/version: win7
- Terminal name/version: neovim-qt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

``. crate mini vim script:

```
noautocmd botright split __transient_state__
call setline(1, 'fuck')
call append(line('$'), '')

let br = bufnr('%')
let i = 2
let line = ''
for l in map(range(100), 'repeat(v:val, 10)')
    call nvim_buf_add_highlight(br, 0, 'String', i, 1, 2)
    call nvim_buf_add_highlight(br, 0, 'String', i, len(l) + 1, len(l) + 2)
    let i += 1
    call append(line('$'), l . l)
endfor
```
2. run `nvim test.vim`

3. run `:so %`

### Actual behaviour

text in the split buffer do not highlighted in master branch, but it works well in <= 0.4.3

### Expected behaviour

nvim_buf_add_highlight should work same as before.

**Comment by bfredl** [comment]
99.5% of the API users put highlight on text rather than the other way around, the rest can @ me on gitter.
