### ISSUE TITLE
Release nvim-win64.zip neovim-qt.exe do not display neovim.svg in the title bar on Windows 10

### ISSUE THREAD

**Issue by VimIcewind** [neovim/neovim#12928]
I use neovim-qt on Windows 10, neovim-qt do not display neovim.svg in the title bar.
I found the reason: there are no imageformats\qsvg.dll and imageformats\qsvgd.dll in Neovim\bin. After I put them in the directory, it workes.

**Comment by VimIcewind** [comment]
@marvim Hi, can you help up to fix this for nvim-win64.zip bug, just  put  imageformats\qsvg.dll and imageformats\qsvgd.dll into Neovim\bin

**Comment by jgehrig** [comment]
@VimIcewind marvim is a code bot, we are unlikely to get a response :)

It looks like the following CMake script needs to be extended:
https://github.com/neovim/neovim/blob/d4b4335fe330bf0558d38883cb8a2b47e8ece28a/src/nvim/CMakeLists.txt#L514-L540

There are several other `windeployqt` DLLs missing... I wonder what the history is here and if it is worth copying the complete set of libraries?

**Comment by jgehrig** [comment]
A quick and easy (non-optimal) fix should look something like this: [neovim-issue-12928.patch.txt](https://github.com/neovim/neovim/files/5239164/neovim-issue-12928.patch.txt)

I think the "correct" solution is to modify CMakeLists.txt to perform a deep copy of the `windeployqt` output instead.

**Comment by jgehrig** [comment]
@jamessan

Any thoughts on this issue? Do you know about the Windows packaging process?

**Comment by jdhao** [comment]
Same issue here after downloading the latest version of nvim-win64.zip binary releases. Older releases do not have this issue.

**Comment by justinmk** [comment]
fixed by https://github.com/neovim/neovim/pull/13004
