### ISSUE TITLE
how to set oldfiles num ?

### ISSUE THREAD

**Issue by jingkai1** [neovim/neovim#12934]
how to set oldfiles num ? I wish oldfiles sum to 2000, but it is litter than 100.

**Comment by glacambre** [comment]
You can use the `shada` option to choose how many files should be stored. Its usage is described in `:help 'shada'` :).

**Comment by erw7** [comment]
As @glacambre said, you should be able to configure it with the `shada` option. It might be easier to understand how to set it up if you read `:help 21.3`.

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
