### ISSUE TITLE
Incorrect instructions for enabling TextYankPost yank higlight

### ISSUE THREAD

**Issue by roginfarrer** [neovim/neovim#12933]
- `nvim --version`: v0.5.0-699-gd4b4335fe
- Operating system/version: MacOS Catalina
- Terminal name/version: Kitty
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Following Neovim instructions for yank highlighting, adding the following to `init.vim`:

```vim
au TextYankPost * silent! lua vim.highlight.on_yank()
```

https://github.com/neovim/neovim/blob/c3f4610922b3f26c952281481f65d255ad352ac5/runtime/doc/lua.txt#L556-L559

### Actual behaviour

Highlighting doesn't work, and no errors are thrown

### Expected behaviour

Highlighting on yank does occur

### Proposed Solution

I got it to work by exchanging `()` for `{}`

```diff
- au TextYankPost * silent! lua vim.highlight.on_yank()
+ au TextYankPost * silent! lua vim.highlight.on_yank{}
```

I'm not experienced with Lua, so I'm not sure if this is a bug in the documentation or in the implementation (i.e., if the parens should work)

**Comment by vigoux** [comment]
I am not sure it is a documentation issue... Can you try removing the `silent!` in the autocmd to see if there is some errors thrown ?

**Comment by roginfarrer** [comment]
I'm not able to recreate it now 😕 . It wasn't working for me for a few days. I'll close this out, thanks for following up.
