### ISSUE TITLE
core dumped on empty shell file

### ISSUE THREAD

**Issue by sanga** [neovim/neovim#12930]
- `nvim --version`: `NVIM v0.5.0-699-gd4b4335fe`
- `vim -u DEFAULTS` (version: ) behaves differently? It does, which is to say: It doesn't crash
- Operating system/version: ubuntu/20.04
- Terminal name/version: alacritty
- `$TERM`: alacritty

### Steps to reproduce

Note: it won't repro using `nvim -u NORC`, as presumably it needs to have treesitter active

```
touch tmp.sh
(this part is speculation) configure nvim with treestitter (I'm using nvim-treesitter, perhaps that's enough)
nvim tmp.sh
enter insert mode and type `#` (as if you were to type `#!/bin/bash`)
```
=> crash

```
nvim: /home/travis/build/neovim/bot-ci/build/neovim/src/tree_sitter/parser.c:878: ts_parser__accept: Assertion `ts_subtree_is_eof(lookahead)' failed.
~                                              fish: “nvim tmp.sh” terminated by signal SIGABRT (Abort)
```

**Comment by vigoux** [comment]
Hi, thanks for opening this issue !
This is being worked on at #12926 but still needs a proper fix.

**Comment by vigoux** [comment]
Hi, this should have been fixed in latest master now, can you try that again ?

**Comment by sanga** [comment]
look good to me!
