### ISSUE TITLE
treesitter/query.lua:20: query: invalid node type at position 2544

### ISSUE THREAD

**Issue by Z5483** [neovim/neovim#12940]
- `nvim --version`: `NVIM v0.5.0-703-gcea2417f3`
- `vim -u DEFAULTS` (version: ) behaves differently? `N/A`
- Operating system/version: `gentoo-5.8.10`
- Terminal name/version: `st-0.8.4`
- `$TERM`: `st-256color`

### Steps to reproduce using `nvim -u NORC`

1. Setup `nvim-treesitter` and enable syntax highlighting for all languages
2. Run `:checkhealth nvim_treesitter` in nvim

### Actual behaviour

checkhealth outputs the following:

```
health#nvim_treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
    function health#check[21]..health#nvim_treesitter#check, line 1
    Vim(lua):E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:20: query: invalid node type at position 2544
```

### Expected behaviour

no error message should be output

**Comment by theHamsta** [comment]
`:TSUpdate` didn't help? There was a breaking change in the dart parser. At least with newest parsers our CI stays green.

**Comment by theHamsta** [comment]
But yes, `checkhealth` should be resilient to errors and rather display them instead of stopping to output information.

**Comment by Z5483** [comment]
> `:TSUpdate` didn't help? There was a breaking change in the dart parser. At least with newest parsers our CI stays green.

`:TSUpdate` solves it for me.

Thank you for the help.
