### ISSUE TITLE
[vim-patch:8.2.0953] merge new 'spelloptions' setting in Neovim?

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#12949]
Hello Neovim team,

Vim patch 8.2.0953 via commit [362b44bd](https://github.com/vim/vim/commit/362b44bd4aa87a2aef0f8fd5a28d68dd09a7d909) added a very handy new option `spelloptions` that can be set to `camel` allowing spell checking to be aware of CamelCased words.

If possible, this would be very handy to have in Neovim as well.
If not possible technically, maybe a reason why it hasn't already been merged, then please close this issue.

Best regards.

**Comment by Shougo** [comment]
You can port the patch for neovim.

**Comment by bfredl** [comment]
So far neovim has not changed anything wrt spelling, so most spell patches should be applicable. Closing as we don't need an issue per unmerged patch.

**Comment by vigoux** [comment]
Maybe I'll try my hand at porting vim patches with this one as it seems simple, I'll keep you updated on this.

**Comment by bluz71** [comment]
> Maybe I'll try my hand at porting vim patches with this one as it seems simple, I'll keep you updated on this.

Many thanks.

I tested `set spelloptions=camel` in the newest Vim and it is a genuinely useful option when spell checking comments in code with lots of CamelCase terms. Basically we don't want to concern ourselves with `class HelloWorld` as a spelling error (it won't be when `set spelloptions=camel` is set since Hello and World are valid words).

Cheers.

**Comment by bluz71** [comment]
@vigoux,

The Vim commits of interest appear to be: [362b44bd](https://github.com/vim/vim/commit/362b44bd4aa87a2aef0f8fd5a28d68dd09a7d909) and [215f49c4d7](https://github.com/vim/vim/commit/215f49c4d720367be29f56168f363a0ee9eaf86b).

**Comment by vigoux** [comment]
Attempted to address that in the aforementioned PR, thanks for reporting that !

**Comment by bluz71** [comment]
@vigoux,

Many thanks.

Note, I reported this issue since I actually want to use this option. It is so useful when spell checking in code files.

Best regards.

**Comment by vigoux** [comment]
I agree! I think this can be really useful, and as I new to porting patches, this was a good occasion!

**Comment by bluz71** [comment]
For those interested, Neovim now has `spelloptions` (ported from Vim by @vigoux).

For maximum compatibility I recommend this setting:

```viml
if exists('&spelloptions')
    set spelloptions=camel
endif
```
