### ISSUE TITLE
virtual text broken

### ISSUE THREAD

**Issue by kyazdani42** [neovim/neovim#12943]
```
NVIM v0.5.0-705-g9f704c88a
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/kiyan/.cache/yay/neovim-git/src/build/config -I/home/kiyan/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/kiyan/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/kiyan/.cache/yay/neovim-git/src/build/include
Compiled by kiyan@kiyan

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

The virtual text is not being applied propertly with `nvim_buf_set_virtual_text`, you can see it with:
nvim's lsp:
- trigger an error (like `not` > `n ot`)
- go down one line, the virt text disappears.

I though it was lsp related, but i have a small snippet for treesitter that runs on cursor move:
```lua
  local ns_id = api.nvim_create_namespace('TSVirtualText')
  local node_info = require'nvim-treesitter'.statusline()
  local cursor = api.nvim_win_get_cursor(0)
  api.nvim_buf_clear_namespace(0, ns_id, 0,-1)
  api.nvim_buf_set_virtual_text(0, ns_id, cursor[1]-1, {{ node_info, "TsVirtText" }}, {})
```
And the virtual text is only applied on empty lines.

### Expected behaviour

virtual text should be applied

EDIT:
the bug might come from `extmark_set` in `extmark.c`. I'd like to debug this but my knowledge of the extmark C api in neovim is *0*.

**Comment by vigoux** [comment]
Is that using treesitter highlighting?
Thanks for reporting and for the repro BTW.

**Comment by kyazdani42** [comment]
hey @vigoux yes indeed it's only when using treesitter highlighting !

**Comment by vigoux** [comment]
@bfredl i think that's luahl related then, should I tag that treesitter?

**Comment by bfredl** [comment]
yea, we might be overriding the virttext by mistake

**Comment by tkolleh** [comment]
I wonder if this is whats causing [the issues I'm experiencing](https://github.com/nvim-lua/diagnostic-nvim/issues/62#issue-710456587) related to virtual text appearing and disappearing or not appearing at all.

##### Demonstration of the behavior:
![out](https://user-images.githubusercontent.com/3095197/94465894-9911da80-018e-11eb-8b15-eef00eaad9a7.gif)

**Comment by vigoux** [comment]
Hi, I think that this has been solved a while ago now, and virtual
text now works properly with `luahl`, so I am closing this.
