### ISSUE TITLE
option titlestring does not work inside tmux session

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#12944]
- `nvim --version`: v0.5.0-569e75799
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: macOS
- Terminal name/version: kitty, iterm2
- `$TERM`: screen-256color (inside tmux)

### Steps to reproduce using `nvim -u NORC`

Inside tmux, use the following config to start nvim:

```
set title
set titlestring=hello\ world
```

### Actual behaviour

The terminal window title is shown as `nvim: tmux`.

### Expected behaviour

Terminal window title shows `hello world`

**Comment by holdenSK** [comment]
Can confirm same issue on Fedora 32, VTE Terminals (GNOME Terminal/Tilix )

**Comment by erw7** [comment]
This is not a bug. It is limited by the terminal (`tmux`). If your `status-style` contains `#T`, you should see the title set by nvim in status line of tmux.

**Comment by jdhao** [comment]
@erw7  Thanks, it works.
