### ISSUE TITLE
vim.lsp.util.make_range_params() returning only current line as range

### ISSUE THREAD

**Issue by kristijanhusak** [neovim/neovim#12958]
For some time code actions for tsserver was not working for me. I thought it's either not implemented properly in neovim, or tsserver is missing the implementation (extract to method,function).
Today I debugged it a bit and noticed that range that is sent to the tsserver contains only current line.
I tried reusing the range that is used in `range_formatting`, and it started to work. At least it prompted for some options and it did some extractions, but it did throw this error:
```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/callbacks.lua:334: RPC[Error] code_name = MethodNotFound, message = "MethodNotFound"
```

`make_range_params()` should return the whole range if there's any visual selection, and not use `make_position_params()` which returns only current line.

**Comment by notomo** [comment]
FYI: `vim.lsp.util.make_given_range_params()` works with selected range.
https://github.com/neovim/neovim/pull/12962/files#diff-d2f9bc382d51d2e37999b2e5ce880750

**Comment by kristijanhusak** [comment]
Thanks, looks like that solves the issue. I'll verify.

**Comment by kristijanhusak** [comment]
It's working, thanks!
