### ISSUE TITLE
Files in `/after/ftplugin` not loaded

### ISSUE THREAD

**Issue by mangelozzi** [neovim/neovim#12951]
- `nvim --version`: NVIM v0.5.0-695-gf34eeba2d
- `vim -u DEFAULTS` (version: ) No
- Operating system/version: WSL2/Ubuntu

### Steps to reproduce using `nvim -u NORC`
1. Create a plugin dir, e.g.: `/home/USERNAME/.config/nvim/test`
2. Make $MYVIMRC contain only a line to add plugin dir to rtp:
```
let &runtimepath.=',/home/USERNAME/.config/nvim/test/'
```
3.  In the plugin dir create the following files:
```
ftplugin/qf.vim       - Content: echom "Hello from test/ftplugin"
after/ftplugin/qf.vim - Content: echom "Hello AGAIN from test/ftplugin/after"
```
4. Start neovim and run `:copen`, then `:mess`

### Actual behaviour
```
Hello from test/ftplugin
```

### Expected behaviour
```
Hello from test/ftplugin
Hello AGAIN from test/ftplugin/after
```

**Comment by mangelozzi** [comment]
Maybe this is the desired behaviour: In point 6/7/8/9 it does not mention location `5`.
(If it is feel free to close the issue, and sorry for wasting your time)
`:help after`:
![image](https://user-images.githubusercontent.com/19764314/93753964-4621ab80-fc01-11ea-8be0-a012ba640c68.png)

**Comment by tjdevries** [comment]
@bfredl since this has to do w/ startup and sourcing things :)

**Comment by taylan97** [comment]
I don't think plugins are supposed to have an `after` directory, since that's almost explicitly there for users to override plugin behavior?

**Comment by mangelozzi** [comment]
Yes that makes sense. Closing this.
