### ISSUE TITLE
Outdated linux packages.

### ISSUE THREAD

**Issue by fryeb** [neovim/neovim#12950]
Trying to setup neovim on a new machine (running [Pop!_OS](https://pop.system76.com/) 20.04), I've found a few issues.
1) FlatHub lists the neovim version as `0.4.2` not `0.4.4` ([here](https://flathub.org/apps/details/io.neovim.nvim))
2) Installing via `apt` still only yields version `0.4.3`, not exactly ideal.

I'm not entirely sure which of these issues are specific to neovim, or more general linux packaging issues (Only switched from windows recently), so any help would be much appreciated.

**Comment by blodzbyte** [comment]
When you install applications through a package manager, it fetches packages from a software repository. In your case, both repositories are outdated. If you want the latest version, you either have to wait for them to be updated or simply build neovim yourself.

**Comment by tjdevries** [comment]
I don't think this is the right repository to ask the question. is it OK to close?
