### ISSUE TITLE
review vim->neovim transition instructions for pynvim (instead of +if_pyth compile flag)

### ISSUE THREAD

**Issue by MathiasKandelborg** [neovim/neovim#12952]
- `nvim --version`:
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Expected behaviour

I am trying to get nvim with python3 support. This is so fucking hard because there's no clear steps for adding extra flags to compile. Please stop just writing a bunch of words and make some actual damn instructions. I get that it might arguably be harder to compile nvim by myself... but I've now spent hours upon hours not reading the instructions I need to compile nvim with x features.

**Comment by vigoux** [comment]
Hi and thanks for the kind words.
Looking at the nvim help files (`:h feature-compile` in nvim), it looks like nvim actually ships with, all features, thus making it hard to enable/disable some.

To help a bit, in most cases, building nvim is just a matter of `make`-ing in the root of the repository, as long at you have installed all the [dependecies](https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites).

PS: You can find your  (quoting you here) "actual damn instructions" [here](https://github.com/neovim/neovim/wiki/Building-Neovim).

**Comment by bfredl** [comment]
@MathiasKandelborg try `pip3 install pynvim`. You might need to add a `sudo` in front or `--user` in the end, depending on how you usually install pip packages.

**Comment by MathiasKandelborg** [comment]
[These are the only options](https://github.com/neovim/neovim/wiki/Building-Neovim#compiler-options) provided in all of that text. Besides that, by skimming the file I've almost read a couple times by now; I still come up with absolutely no more information on options I have available.

I still haven't been able to find the concrete no-nonsense instructions for building nvim with flags. The command you provided has sections like:
```
5. Missing legacy features                               nvim-features-missing

Some legacy Vim features are not implemented:

- if_lua: Nvim Lua API is not compatible with Vim's "if_lua"
- if_mzscheme
- if_py: python-bindeval python-Function are not supported
- if_tcl
```
And I cannot locate the instructions for adding flags and functionality in `:h feature-compile` it is a bunch of sentences and words and talking about everything nvim is; not instructions on how to compile nor how to compile with extra options.

I still have gotten zero steps closer to which options I have available for building with a flag.

I know I can build with the make command. That's the whole point here; I am bashing on the fact that there's so much data but little information on actually building the application. So much time and space is spent making sure people can do it, but not providing exhaustive information on how to do it.

**Comment by bfredl** [comment]
@MathiasKandelborg are you out for actually solving your problem or just ranting? Please try the `pip` command as I suggested and report your success/failure. If you are interested in ranting only https://gitter.im/neovim/neovim is a better place.

**Comment by MathiasKandelborg** [comment]
@bfredl I have pynvim installed. I've also managed to remove python2 support with commands. That command is successful, but does not help me compile nvim. I thank you for your time and energy spent on this, but I am seeking to learn how to compile nvim.

I am expecting there to be exhaustive information for build options _somewhere_ which is my main point.

**Comment by bfredl** [comment]
@MathiasKandelborg well you mentioned python3 as your main goal. That requires pynvim istalled inside python3, but no compile flags. just "make" in the repo root should make you a build with all needed bells and whistles. Is there any functionality actually missing?

**Comment by MathiasKandelborg** [comment]
I don't want python2 support, if I can get away with it. There's probably also a lot of other bells and whistles I'd love to **avoid**.

I realized a few weeks ago that neovim and powerline doesn't work together. Since, I've tried to make my system have nvim and a powerline integration with ZSH & ST. I use neovim in VSCode as an extention and things are working pretty well. I, however, do probably not need a lot of the things neovim compiles with by default. I wanted to start from one end: python3 only support (no python2), to then see where that leaves me. Today I decided to dive deep, just to find that 'the make pool is shallow in every end' i.e. I can't find exhaustive information on compile options with nvim, no matter where I look at official documentation.

I am awestruck by the amount of information and nowhere and at no time did anyone think to make a list of compile options.

I have a very specific use-case, and want to use neovim in VSCode with as few features as possible, while keeping the 'vim engine'. That isn't currently possible the information I've been exposed to. Please do correct me if I'm wrong here, but it seems that I'm not, which is why I had the confidence to make an issue in the first place.

**Comment by bfredl** [comment]
@MathiasKandelborg only vimL and lua languages are actually compiled into the binary (which are mandatory, as parts of neovim itself is written in vimL and lua). Python is handled via pynvim client only, you can choose exactly what python version yourself. The only relevant build option for most people are debug vs release build, which should be mentioned in readme and wiki places already.

**Comment by MathiasKandelborg** [comment]
Let me get this right. Neovim has, with no exceptions, the absolutely smallest footprint possible for a neovim installation by default? I.e. there's not one dependency or feature that could be left out?

[The wording](https://github.com/neovim/neovim/wiki/Introduction#migrate-to-a-cmake-based-build):
> Most users don't care about selecting individual features and just compile using --with-features=huge, which still generates an executable that is small enough even for lightweight systems by today's standards.
>
>All those files will be removed and Vim will be built using CMake, a modern build system that generates build scripts for the most relevant platforms.

Makes me think that there's room for changes. I just want to experiment with different options, see what brakes, and see how efficient I can make the binary. Usually defaults are for _most people_, but there's often room for expanding/removing defaults for _some people_. Especially when interacting with programs that has several modules to compile with.

**Comment by jamessan** [comment]
Like you quoted in your previous post, we removed the feature flags in nvim.  We build with all "features" enabled, both to avoid pushing choices onto the users (what flags do I need to build with?) and to reduce code/test complexity.

We also _externalized_ a lot of the features that Vim has (support for languages other than Lua, GUIs, etc.).  This reduces what needs to be in nvim's codebase.

**Comment by MathiasKandelborg** [comment]
Thank you, people, for your excellent responses. I didn't get to do what I wanted, but I indeed got the answers I needed.

I might get to try 'KB hunting' for neovim; I'm mostly from the full-stack JS/TS world because of popularity (work)... But my heart is at efficiency and performance, and this seems like a good starting point. :)

I'm sorry for being so ranty. I just couldn't understand why there weren't any instructions for building neovim. Perhaps that reasoning should be mentioned/explained somewhere a bit more in-depth :smile:
