### ISSUE TITLE
Treesitter: inccommand nosplit causes virtual text error messages

### ISSUE THREAD

**Issue by akinsho** [neovim/neovim#12967]
- `nvim --version`:
```
NVIM v0.5.0-706-g42d13b90f                                                     
Build type: RelWithDebInfo                                                     
LuaJIT 2.1.0-beta3                                                             
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -W
all -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wsh
adow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-pro
tector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLAR
ATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN
_LOG_LEVEL=3 -I/build/nvim/parts/nvim/build/build/config -I/build/nvim/parts/nv
im/build/src -I/build/nvim/parts/nvim/build/.deps/usr/include -I/usr/include -I
/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build
/build/include                                                                 
Compiled by root@lcy01-amd64-026                                               
                                                                               
Features: +acl +iconv +tui                                                     
See ":help feature-compile"                                                    
                                                                               
   system vimrc file: "$VIM/sysinit.vim"                                       
  fall-back for $VIM: "/usr/share/nvim"   
```

- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Ubuntu 20.04/ MacOS 10
- Terminal name/version: kitty 0.18.3
- `$TERM`: xterm-kitty

#### Minimal init.vim
```vim
call plug#begin(stdpath('data') . '/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()

lua << EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = 'all',
  highlight = {
    enable = true,
  },
}
EOF
```
1. open nvim with minimal vimrc above
```
nvim -u <path-to-minimal-vimrc-above>
```
2. open any filetype `nvim-treesitter` supports
3. set `inccommand=nosplit`
4. start substituting a word in the buffer until is about to be completely replaced

![nvim-treesitter-inccommand](https://user-images.githubusercontent.com/22454918/93916161-fcb88580-fd00-11ea-8770-b2fac566b786.gif)

### Actual behaviour
As the image below show when using `inccommand=nosplit` with treesitter when a word is "collapsed" during substitution it causes, error messages to be inserted into the buffer as virtual text. These are cleared once you run `:e`.

![treesitter-invalid-start](https://user-images.githubusercontent.com/22454918/93769150-542bf800-fc12-11ea-9dbf-fc2d1c01ee71.png)

### Expected behaviour
No virtual text error messages and consistent highlighting

Side note: This also seems to happen when switching git branches whilst in nvim but I haven't nailed down the exact repro for that so will submit another issue once I have.

**Comment by akinsho** [comment]
I've raised a similar/maybe related issue on nvim-treesitters repo directly https://github.com/nvim-treesitter/nvim-treesitter/issues/513, but the virtual text and invalid start errors seems to relate to nvim itself

**Comment by akinsho** [comment]
@vigoux it seems that #12968 has fixed the virtual text error from appearing 🎉 , but the will leave this open because the treesitter tree still appears to go out of sync.

<img width="1165" alt="Screen Shot 2020-10-02 at 13 17 16" src="https://user-images.githubusercontent.com/22454918/94922160-9a564680-04b1-11eb-873b-2857146ae0c1.png">

**Comment by akinsho** [comment]
Not sure what to make of this but this error now seems to almost always show `end_col out of range` similar to https://github.com/neovim/neovim/issues/12861 I'm not sure if that issue was ever fixed but if it was think it might have regressed

**Comment by bfredl** [comment]
We really need to port over inccommand display logic to use the new "decorations" api. Perhaps even move some hard coded C layer choices to lua runtime code.

**Comment by lukas-reineke** [comment]
I guess this is related so I comment here.

If I `set undofile` and delete a line. Then close and open the file again and undo the change, I get the `end_col value outside range` error message.
Tested with the same minimal config as OP.

**Comment by akinsho** [comment]
@vigoux thanks for looking into this 🥇 , I'm not sure the latest fix did resolve the issue. I'm building neovim from master and just rebuild now current version is.
```
/akin/neovim/share/nvim/runtime/lua/vim/lsp/handlers.lua:version
NVIM v0.5.0-dev+946-g958ebc733
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion
 -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPA
CK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/akin/Desktop/projects/contributing/neovim/build/config -I/home/akin/Desktop/projects/contributing/neovim/sr
c -I/home/akin/Desktop/projects/contributing/neovim/.deps/usr/include -I/usr/include -I/home/akin/Desktop/projects/contributing/neovim/build/src/nvim/auto -I/home/akin/Deskto
p/projects/contributing/neovim/build/include
```

And I still see this error, in the GIF below I made the substitution which doesn't initially cause the error, then I edited it which does. I don't have a specific set of steps since if it's deterministic I can't see the pattern, but essentially if you try substituting with `inccommand` and make edits to the pattern so different bits are being taken of screen at a time it eventually triggers this issue.

 Also note that even then the error doesn't occur the highlighting breaks, which is understandable if the line is being parsed in it's preview/inccommand state but when I stop using inccommand say I press `esc` at that point the highlighting doesn't get recalculated 

![inccommand_fix](https://user-images.githubusercontent.com/22454918/102350592-0d456880-3f9d-11eb-86c5-19f2f5ac4f68.gif)

**Comment by akinsho** [comment]
Ok trying to make sure I give you something more reproducible to test with
```lua
local ft_str =
  table.concat(
  vim.tbl_map(
    function(ft)
      return configs[ft].filetype or ft
    end,
    parsers.available_parsers() <-------------- HERE
  ),
  ","
)

vim.cmd(
  "autocmd Filetype " ..
    ft_str .. " setlocal foldmethod=expr foldexpr=nvim_treesitter#foldexpr()"
)
```
I seem to be able to consistently reproduce it by going to the `parsers.available_parsers()` line and running `s/parsers/` then I then enter the next `/` it reproduces so `s/parsers//` is the full command at which point it appears below in the autocommand block

**Comment by vigoux** [comment]
Indeed, editing the pattern, or changing the replacement leads to errors, thanks for the repro steps.

**Comment by vigoux** [comment]
When hitting `<Esc>` and aborting the substitution, and error happens too.

**Comment by alfa07** [comment]
Any workarounds in the meantime?

**Comment by akinsho** [comment]
@alfa07 you can turn off `inccommand` 🤷🏿‍♂️

**Comment by vigoux** [comment]
Sorry, I do not have that much time these days, I'll try to get back to that at some point...

**Comment by akinsho** [comment]
@bfredl is there any chance that #13878 would have had any impact on this? I just switched TS highlighting back on this morning and have been using `inccommand` substitution without seeing this error anymore. I've just tried a few different substitutions and tried to reproduce it using the methods I mentioned above and it seems to be gone 🤞🏿 . Wanted to check that the change isn't actually completely unrelated before closing this.

**Comment by bfredl** [comment]
@akinsho good to hear, I wasn't sure #13878 would fix all errors but let's assume so until more errors are confirmed.

**Comment by rafikdraoui** [comment]
The substitution preview seems fixed for me too.

But I still get similar errors when the file contents are changed outside neovim. I don't know if this belongs to this issue or to another existing one (I did report something similar in another issue, but I can't seem to find it right now...)

e.g  with file `file.py` with content

```python
x = {
    1,
    2
}
```

in one neovim instance with `set autoread`, then opening the file in a separate neovim instance and changing the buffer content to `x = {1, 2}`, then focusing back on the first neovim instance, the buffer content is updated to `x = {1, 2}`, but with a trailing error for 

```
treesitter/highlighther: Error executing lua: .../runtime/lua/vim/treesitter/highlighter.lua:219: col value outside range
```

In practice, I don't edit files in separate instances. The error usually happens when code formatters are run from outside neovim, or when switching git branches where file content is updated, etc.

This can also happen when editing code "normally", say when I delete a whole section with `dap`, and highlighting gets confused. But I don't have a reproducible case for debugging for that one yet (might be a different issue).

**Comment by akinsho** [comment]
@rafikdraoui yep this issue relates *specifically* to the `inccommand` portion of what I think are a few different treesitter errors.  I think anyone using treesitter is still seeing all the various other ones you mention such as the "changed whilst not focused", some relating to the undo tree. I think the issue is getting clear reproducible steps so the reports are more actionable. The "umbrella" issue is #12861
