### ISSUE TITLE
Lua vim.o.expandtab not working

### ISSUE THREAD

**Issue by LoricAndre** [neovim/neovim#12978]
- `nvim --version`: 
```
NVIM v0.5.0-699-gd4b4335fe
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-f993d50b-e453-4e37-bfd5-eb22513df7c2

Features: +acl +iconv +tui
```
- Operating system/version: Manjaro, linux 5.8
- Terminal name/version: Kitty 0.18.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`
include lua file with
```
vim.o.expandtab = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2
```
### Actual behaviour
The options are not set (other option set similarily in the same file like autoindent or timeoutlen work), `:verbose set expandtab` returns nothing.

### Expected behaviour
Tab gets expanded to two space

**Comment by bfredl** [comment]
Hmm `nvim_set_option("expandtab")` is executed but has no effect (perhaps it sets the default for new buffers?.). We probably want to make `vim.o` "smarter" anyway, in an `init.lua` one typically don't want to care which options that are global/buffer/window yet.

**Comment by tjdevries** [comment]
Also, we probably want to do something with tracking where `nvim_set_option` sets something in Lua land (probably with `script_ctx` or whatever that thing is in C land.

**Comment by Shatur95** [comment]
Hmm ... `vim.cmd('set expandtab')` also doesn't work when in `init.lua`.

**Comment by smithbm2316** [comment]
> Hmm ... `vim.cmd('set expandtab')` also doesn't work when in `init.lua`.

@Shatur95 I'm not sure if you were able to get that to work out, but I was having the same issue as listed above with `vim.bo.expandtab = true`, and was able to get it to work (at least thus far from some initial testing) by using the following in my `settings.lua` file that I `require(settings)` in my `init.lua` file:

```lua
vim.cmd [[
set autoindent
set expandtab
set shiftwidth=2
set smartindent
set softtabstop=2
set tabstop=2
]]
```
I'm not sure why this would work for me and the `vim.cmd('set expandtab')` wouldn't work for you (I'm very new to Lua), but it may be worth a shot in the meantime until the `vim.o` option is a bit more robust 🙂

**Comment by Shatur95** [comment]
I was wrong, `vim.cmd('set expandtab')` works, thanks!

**Comment by dm1try** [comment]
btw it's not about `vim.o.expandtab` specifically, but about the implementation of `nvim_set_option`

 ```
nvim --headless -u NORC -c "lua vim.api.nvim_set_option('expandtab', true)" -c "set expandtab?" -c "exit"
 ```
 ```
 nvim --headless -u NORC -c "lua vim.api.nvim_set_option('tabstop', 2)" -c "set tabstop?" -c "exit"
 ```

**Comment by jamessan** [comment]
> ```
> nvim --headless -u NORC -c "lua vim.api.nvim_set_option('expandtab', true)" -c "set expandtab?" -c "exit"
> ```

Looks like you mean `-c "setglobal expandtab?"` there.  If you want to change the buffer-local value, then use `lua nvim.api.nvim_buf_set_option(0, 'expandtab', true)`.

Pretty sure it was an intentional choice to be more strict in the API about which values are modified.  However, we probably want a mechanism to behave like Vim's `:set` (which changes both global and local values).

**Comment by dm1try** [comment]
@jamessan it makes sense, you are right. 

> (which changes both global and local values).

I didn't know that.

**Comment by dm1try** [comment]
this global-local concept feels strange then(or maybe it's a Vim bug).
does global mean just a "default value"?
for example, if `init.vim` has such line
```Viml
setglobal expandtab
``` 
should any opened buffer has `expandtab` option if this value has not been overwritten locally? (yes, I think)
the current behavior is different: a default(global?) option is ignored for buffers that opened for the file names provided using a command line(and for "welcome" buffer if you did not provide any file name), but for any new buffers it's applied.

also, from the doc: 

<img width="610" alt="Screen Shot 2021-02-11 at 17 28 48" src="https://user-images.githubusercontent.com/486807/107649581-a982a780-6c8e-11eb-9a89-8592d6b8229d.png">
🤔

**Comment by Shatur95** [comment]
Works correctly in the latest master.

**Comment by GaetanLepage** [comment]
It stil does not work for me.
(I am using the latest master).

**Comment by Shatur** [comment]
This is weird, I use `v0.5.0-dev+1359-g43956dea5` (when `vim.opt` was introduced) with the [following](https://github.com/Shatur/neovim-config/blob/d9ab168d2c32bde02754a3eac1decf4836577380/init.lua#L16) configuration and it works for me.

**Comment by GaetanLepage** [comment]
I have:
```
nvim --headless -u NORC --cmd "lua vim.bo.expandtab = true" -c "set expandtab?" -c "exit"                    
expandtab
```
but
```nvim --headless -u NORC --cmd "lua vim.bo.expandtab = true" -c "new" -c "set expandtab?" -c "close" -c "exit"```
noexpandtab`

**Comment by Shatur** [comment]
This is because you should use `vim.o` always after the latest changes. Check the documentation, now it behaves the same as `set` in Vimscript.

**Comment by GaetanLepage** [comment]
You mean `vim.o` instead of `vim.bo` ?
If so, should I also replace `vim.wo` with `vim.o` as well ? (Those are already working).

**Comment by Shatur** [comment]
Yes :)

**Comment by GaetanLepage** [comment]
Indeed it works ! Thank you !!!
What about `vim.wo` ?

What is the reason for this behavior ? Is now the 'right way to set options in lua' to simply `vim.o` everything without wondering about the option being global, buffer only or window only ?
Or is it just a workaround ?

**Comment by Shatur** [comment]
>  What about vim.wo ?

You can read more about it in `:h vim.wo`.

> What is the reason for this behavior ?

They decided to make `vim.o` the same as `set` for convenience. Also there is a `vim.opt`.

> Is now the 'right way to set options in lua' to simply vim.o everything without wondering about the option being global, buffer only or window only ?

Yes. Or `vim.opt`.

**Comment by tjdevries** [comment]
Sounds like everything is working the way people are hoping now :) I'll close. Feel free to re-open if I missed something.

**Comment by nicowilliams** [comment]
I also have this problem.  Tracing system calls I found that the issue is `tpope/vim-sleuth`, which tries to guess things like `expandtab`, but it's guessing wrong and it's overriding my global nvim configuration.  FYI, in case you get more of this.
