### ISSUE TITLE
Support for `TextDocumentSyncKind.Incremental` for textDocument/didChanges. 

### ISSUE THREAD

**Issue by zachbai** [neovim/neovim#12972]
- `nvim --version`: 0.5
- language server name/version: applicable to any server that supports incremental text sync; I noticed the inconsistency with the dart analysis server that ships with the dart SDK
- Operating system/version: macOS Catalina (10.15.4)

Looks like the client is designed to support incremental text document sync (see [TODO in lsp client impl](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L807-L812)), but due to some underlying issue the client is temporarily tweaked to unconditionally send the full buffer contents (a la `TextDocumentSyncKind.Full`).

I ran into the issue because I found that the built-in nvim lsp client was slower to report diagnostics than [`vim-lsc`](https://github.com/natebosch/vim-lsc), which _does_ currently support incremental sync. The language server I was using at the time is the dart analysis server, which perhaps obviously specifies `TextDocumentSyncKind.Incremental` in its server capabilities ([dartls](https://github.com/neovim/nvim-lspconfig#dartls) in nvim-lspconfig speak). 

Is there an existing tracking issue for the underlying issue ('problems with the byte_sizes sent by nvim') referenced in the TODO?

**Comment by mjlbach** [comment]
I'm closing this because #13049 (even though filed later) is where we've been discussing it. This was moved to 0.6, but can currently be used for on_lines with:

```lua
local custom_attach = function(client)
      if client.config.flags then
        client.config.flags.allow_incremental_sync = true
      end
    end
require('lspconfig').elmls.setup({
   on_attach = custom_attach;
})
```
