### ISSUE TITLE
Kill language servers started on current NeoVim when exiting

### ISSUE THREAD

**Issue by adelarsq** [neovim/neovim#12984]
- `nvim --version`: lastest
- language server name/version: all
- Operating system/version: macOS

<details>
<summary>nvim -c ":checkhealth nvim nvim_lsp"</summary>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `folds.scm` found.

## c_sharp parser healthcheck
  - OK: c_sharp parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for c_sharp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `textobjects.scm` found.
  - WARNING: No `folds.scm` query found for c_sharp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: omnisharp: configuration checked.
  - INFO: html: configuration checked.
  - ERROR: gopls: The given command "gopls" is not executable.
  - ERROR: ghcide: The given command "ghcide" is not executable.
  - ERROR: dockerls: The given command "docker-langserver" is not executable.
  - INFO: flow: configuration checked.
  - ERROR: rust_analyzer: The given command "rust-analyzer" is not executable.
  - INFO: intelephense: configuration checked.
  - ERROR: kotlin_language_server: config.cmd error, shared.lua:515: cmd: expected list, got nil
  - INFO: jsonls: configuration checked.
  - INFO: fsharp: configuration checked.
  - INFO: elixirls: configuration checked.
  - INFO: vuels: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: pyls: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: elmls: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: sourcekit: configuration checked.
  - ERROR: hie: The given command "hie-wrapper" is not executable.
  - INFO: bashls: configuration checked.

health#completion_nvim#check
========================================================================
## general
  - OK: neovim version is supported

## completion source
  - OK: all completion source are valid

## snippet source
  - OK: You are using vim-vsnip as your snippet source

health#floaterm#check
========================================================================
  - OK: Terminal feature is OK
  - OK: Floating window feature is OK
  - ERROR: nvr executable is not found, run `pip3 install neovim-remote` to install

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release
    LuaJIT

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = ""
  - ERROR: "python2" was not found.
  - INFO: Executable: Not found
  - ERROR: Detected pip upgrade failure: Python executable can import "pynvim" but not "neovim": python2
    - ADVICE:
      - Use that Python version to reinstall "pynvim" and optionally "neovim".
          pip uninstall pynvim neovim
          pip install pynvim
          pip install neovim  # only if needed by third-party software

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/Users/adelar/.asdf/shims/python3"
  - INFO: Executable: /Users/adelar/.asdf/shims/python3
  - INFO: Python version: 3.8.1
  - INFO: pynvim version: 0.4.1 (outdated; from ~/.asdf/installs/python/3.8.1/lib/python3.8/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.2

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.8.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed
</details>

<details>
<summary>lsp.log</summary>

[ ERROR ] 2020-09-25T18:36:12-0300 ] ...ar/dev/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]	"rpc"	"/Users/adelar/.cache/nvim/nvim_lsp/sumneko_lua/lua-language-server/bin/macOS/lua-language-server"	"stderr"	"...im_lsp/sumneko_lua/lua-language-server/script/config.lua:167: bad argument #1 to 'for iterator' (table expected, got nil)\nstack traceback:\n\t...im_lsp/sumneko_lua/lua-language-server/script/config.lua:167: in function <...im_lsp/sumneko_lua/lua-language-server/script/config.lua:166>\n\t[C]: in function 'xpcall'\n\t...im_lsp/sumneko_lua/lua-language-server/script/config.lua:166: in function 'config.setConfig'\n\t...m_lsp/sumneko_lua/lua-language-server/script/service.lua:821: in method 'onUpdateConfig'\n\t...ko_lua/lua-language-server/script/method/initialized.lua:28: in field 'callback'\n\t.../nvim_lsp/sumneko_lua/lua-language-server/script/rpc.lua:81: in function 'rpc.recieve'\n\t...m_lsp/sumneko_lua/lua-language-server/script/service.lua:788: in method '_loadProto'\n\t...m_lsp/sumneko_lua/lua-language-server/script/service.lua:776: in method '_doCompileTask'\n\t...m_lsp/sumneko_lua/lua-language-server/script/service.lua:1039: in method 'onTick'\n\t...m_lsp/sumneko_lua/lua-language-server/script/service.lua:1061: in method 'listen'\n\t...e/nvim/nvim_lsp/sumneko_lua/lua-language-server/main.lua:23: in main chunk\n\t[C]: in ?\n"

[ ERROR ] 2020-09-25T18:36:13-0300 ] ...ar/dev/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]	"rpc"	"/Users/adelar/.cache/nvim/nvim_lsp/sumneko_lua/lua-language-server/bin/macOS/lua-language-server"	"stderr"	"...im_lsp/sumneko_lua/lua-language-server/script/config.lua:167: bad argument #1 to 'for iterator' (table expected, got nil)\nstack traceback:\n\t...im_lsp/sumneko_lua/lua-language-server/script/config.lua:167: in function <...im_lsp/sumneko_lua/lua-language-server/script/config.lua:166>\n\t[C]: in function 'xpcall'\n\t...im_lsp/sumneko_lua/lua-language-server/script/config.lua:166: in function 'config.setConfig'\n\t...m_lsp/sumneko_lua/lua-language-server/script/service.lua:821: in method 'onUpdateConfig'\n\t...ko_lua/lua-language-server/script/method/initialized.lua:28: in field 'callback'\n\t.../nvim_lsp/sumneko_lua/lua-language-server/script/rpc.lua:81: in function 'rpc.recieve'\n\t...m_lsp/sumneko_lua/lua-language-server/script/service.lua:788: in method '_loadProto'\n\t...m_lsp/sumneko_lua/lua-language-server/script/service.lua:1038: in method 'onTick'\n\t...m_lsp/sumneko_lua/lua-language-server/script/service.lua:1061: in method 'listen'\n\t...e/nvim/nvim_lsp/sumneko_lua/lua-language-server/main.lua:23: in main chunk\n\t[C]: in ?\n"
</details>

### Steps to reproduce

Just open any file with LSP support and close NeoVim. The processes remains executing:

```
🐚  ps aux | grep lsp
adelar           15287  10,2  0,5  4331716  43348   ??  S     6:26     0:20.78 /Users/adelar/.cache/nvim/nvim_lsp/sumneko_lua/lua-language-server/bin/macOS/lua-language-server -E /Users/adelar/.cache/nvim/nvim_lsp/sumneko_lua/lua-language-server/main.lua
adelar           15228   9,8  0,5  4330636  42712   ??  S     6:26     0:20.97 /Users/adelar/.cache/nvim/nvim_lsp/sumneko_lua/lua-language-server/bin/macOS/lua-language-server -E /Users/adelar/.cache/nvim/nvim_lsp/sumneko_lua/lua-language-server/main.lua
adelar           15447   0,0  0,0  4268284    668 s002  R+    6:29     0:00.00 grep lsp
```

### Actual behaviour

At moment when closing NeoVim the LSP servers started by it still remains executing.
As a temporary solution a have created a LSP killer command:

```
command! LspKill       :!ps -ef | grep 'nvim_lsp' | grep -v grep | awk '{print $2}' | xargs kill -9
```

### Expected behaviour

Expected to kill the LSP servers started or being able to reconnect when open NeoVim again.

**Comment by mjlbach** [comment]
@adelarsq This was a bug with sumneko (not us) try the latest version and please report if you're having the issue still. I don't think we should be killing by PID, so this is a bug in the upstream language servers not respecting the shutdown signal.

**Comment by adelarsq** [comment]
@mjlbach Oh thanks for the response. So I will close this. Thanks again.
