### ISSUE TITLE
ui: The position of the float window is not correct.

### ISSUE THREAD

**Issue by akiyosi** [neovim/neovim#12985]
### nvim version:
nvim v0.4.4 or later

### Actual behaviour

The video shows the behavior when the `win_float_pos` event is handled in a straightforward way on the GUI side.

As far as I can see, there are three problems:
 - the position of the completion window in command mode is incorrect, 
    ![issue1-float-win](https://user-images.githubusercontent.com/8478977/94326727-f49e6580-ffe0-11ea-895c-6d266a4f53e4.gif)

 - the position of the completion window with SW as anchor is incorrect, 

    ![issue2-float-win](https://user-images.githubusercontent.com/8478977/94326730-fa944680-ffe0-11ea-96c1-9166c545775a.gif)

 - the pop-up window with additional information based on the completion items provided by nvim-lsp, coc-nvim, etc. seems to be missing an offset for the vertical position of the grid.

    ![issue3-float-win](https://user-images.githubusercontent.com/8478977/94326831-ce2cfa00-ffe1-11ea-939b-8bf90a13b0f8.gif)

### Expected behaviour

Display the correct position of the float window, even for multigrid ui

**Comment by last-partizan** [comment]
This should be working now :)

**Comment by akiyosi** [comment]
@last-partizan 
I have confirmed that this problem has been fixed. Thanks for your contribution!
Closed.

**Comment by akiyosi** [comment]
It seems that the third problem is still occurring.

**Comment by vhakulinen** [comment]
Here is another example for the third case comparing what the TUI does, and what neovim sends to GUIs (TUI is on the right side).

![image](https://user-images.githubusercontent.com/4594126/170867283-012a081d-4376-4284-a688-e6f578f90e59.png)

**Comment by akiyosi** [comment]
Since this issue does not seem to be occurring anymore, so I think it is ok to close it.
