### ISSUE TITLE
xkb syntax "section" appears twice AND "section" as §'s name is colored

### ISSUE THREAD

**Issue by ewen-goisot** [neovim/neovim#12990]
two minor issues related to each other:

on `/runtime/syntax/xkb.vim` file, line 44 (defining `keyword xkbIdentifier`),
the word `section` appears twice, is there a particular reason for that?

`section` is also the xkb name of this symbol: `§ (U0047)`,
so if I have a line like `key <AE04>{[ quotedbl, section, U230b, U21d2, F9, U1F4AC]};` in a xkb file,
I will see the `section` word in `Keyword` color, but it shouldn't.
A possible solution is to change line 34 to:
`syn region xkbBracket start='\[' end='\]' contains=ALLBUT,xkbBracketError,xkbSpecial,xkbTodo,xkbIdentifier transparent`
(I simply added `xkbIdentifier` in `contains=ALLBUT`).

**Comment by janlazo** [comment]
It's a generated file. Only maintainer can know why `section` appears twice.

Can you send your solution to Vim? URL in the syntax file is dead. Neovim tries to not diverge `runtime/` files from Vim so your solution cannot be merged to Neovim.

**Comment by mhinz** [comment]
As was said, this needs to be reported to Vim. Unless that's done and the issue linked in here, I'm closing this.
