### ISSUE TITLE
[LSP Hover Style] Header divider line should not wrap

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#12998]
Hello Neovim LSP team,

An LSP Hover style issue best explained with this screenshot:

<img width="634" alt="Neovim_LSP_Hover_Line_Wrap" src="https://user-images.githubusercontent.com/11382509/94395895-0714cc80-01a4-11eb-8023-94501317ab21.png">

Whenever there is multiline documentation in hover floating window, native Neovim LSP adds in a header divider line.

The divider line itself is fine.
However, it should never wrap.
Notice in the image above the wrapping below the `Axios` function.

It appears that the length of the divider line is taken from the API function it sits beneath.
Instead it would be much better if the length of the divider line is simply the width of the floating window.

This is an ideal example here:

<img width="861" alt="Neovim_LSP_Hover_No_Wrap" src="https://user-images.githubusercontent.com/11382509/94396139-a0dc7980-01a4-11eb-889d-dc233d97b5a3.png">

Flutter + Dart has fat APIs which causes the header divider line to wrap in non-pleasing ways.

Best regards.

**Comment by teto** [comment]
hard to disagree, patches welcome. On a quick glance I would say that divider is added here https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L809

**Comment by clason** [comment]
Hmm, as far as I understand the code, this should already behave as you want -- the divider is calculated based on the *wrapped* width, which is the same width used for the floating window. So we have to find out why this doesn't work for you. 

The first possibility is that the wrapping code is never called. Do you have `wrap` set for the main buffer? If not, how do you get the float wrapped (which should inherit its setting from the main buffer)?

(Also, please always share a (minimal) config when reporting bugs, since plugins and settings can interfere in subtle ways.)

**Comment by bluz71** [comment]
I do have `set wrap` in effect.

I will try and send in a minimal `init.vim` tomorrow.

**Comment by bluz71** [comment]
Minimal `init.vim` that exhibits issue:

```viml
call plug#begin('~/.vim/plugged')
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua <<EOF
local nvim_lsp   = require'nvim_lsp'

local lsp_on_attach = function(client)
  print("LSP started.")

  -- Mappings
  local opts = {noremap = true, silent = true}
  vim.fn.nvim_buf_set_keymap(0, 'n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
end

-- The Language Servers
nvim_lsp.dartls.setup {
  on_attach = lsp_on_attach
}

nvim_lsp.tsserver.setup {
  on_attach = lsp_on_attach
}

vim.lsp.callbacks["textDocument/publishDiagnostics"] = function() end
EOF
```

`K` mapping needs to be invoked on a function with a wide API, for example `Axios.then` in JavaScript/TypeScript as seen here:

<img width="1279" alt="JavaScript" src="https://user-images.githubusercontent.com/11382509/94645077-42430700-032e-11eb-9829-b5690d3991c4.png">

Or anything in Flutter + Dart as seen here:

<img width="1280" alt="Flutter_Dart" src="https://user-images.githubusercontent.com/11382509/94645138-70284b80-032e-11eb-93fd-cf5ce625a15d.png">

As can be seen, the length of the line exactly matches the length of the wrapped function it sits beneath.

Hopefully it will be repeatable. Best regards.

**Comment by clason** [comment]
Thank you! But are you sure the example is complete? You mentioned earlier that you are setting `wrap`, which you don't in your example. And can you reduce it to just a single server?

**Comment by bluz71** [comment]
> Thank you! But are you sure the example is complete? You mentioned earlier that you are setting wrap, which you don't in your example.

Explicit setting of `wrap` is not required since it already defaults to `on` as noted in `:help wrap`:

```viml
'wrap'			boolean	(default on)
			local to window
```

>  And can you reduce it to just a single server?

No, I can repeat it with multiple language servers. In the screenshots in post just above yours the first one is with `tsserver` and the second is with Dart language server. It is not a language server issue but a presentation issue.

Best regards.

**Comment by clason** [comment]
Can you try #13007?

**Comment by bluz71** [comment]
> Can you try #13007?

Success!!

That works great.

**Comment by bluz71** [comment]
New screenshot with #13007 fix:

<img width="1280" alt="Flutter_No_Wrapping" src="https://user-images.githubusercontent.com/11382509/94664968-ea68c800-034e-11eb-9017-9d91eef87d60.png">

Divider line no longer wraps.

Many thanks.
