### ISSUE TITLE
Error detected while processing FileType Autocommands for "cpp"

### ISSUE THREAD

**Issue by YIKAILucas** [neovim/neovim#13005]
![1V5T8t](https://vimeracke.oss-cn-shenzhen.aliyuncs.com/uPic/1V5T8t.png)

When I nvim my .cc file, this error happened. I can press enter to skip it, but it still annoying. I think there is something wrong with my autocmd, but I know few about autocmd. Could anyone help me?

**Comment by YIKAILucas** [comment]
When I use VIM , not neovim, it's OK

**Comment by teto** [comment]
The command ClampStart isnt defined in neovim, looks like a configuration problem on your side, check the plugin that defines ClampStart is in neovim's runtime path. Rerun PlugInstall from neovim if that's what you use.
