### ISSUE TITLE
`:norm $` behavior diverges from vim when listchars:extends and eol are defined

### ISSUE THREAD

**Issue by pyrho** [neovim/neovim#13018]
- `nvim --version`
NVIM v0.5.0-695-gf34eeba2d

- `vim -u DEFAULTS` (version: ) behaves differently?
Yes

- Operating system/version:
macOS Catalina

- Terminal name/version:
kitty master(05a254ee)

- `$TERM`:
xterm-kitty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
" (:echo winwidth(0) should be 76, this number doesn't matter, but it should be smaller than the length of the line created at a later step)
:set nowrap
:set list
" (the characters don't matter)
:set listchars=extends:>,eol:< 
:exe "norm 77ia" | exe "norm AX"
:norm $
```

### Actual behaviour
The cursor is positioned on the listchar defined for `extends` (`>` in this case).

### Expected behaviour
The cursor is positioned on the last character of the line (in this case `X`).

### Remarks
If only `extends` is set for `listchars` it works fine, so I suspect that the `eol` character is taken into account in some line maths when it should not.
~I'm also happy to attempt a pull request if given some pointers into where to look in the code (or pointers on how I would find the relevant part of code).~ edit1: I guess it's in `screen.c` edit2: or `cursor.c`.

### Other remarks
- Vim also differs in another way, it centers the cursor on the screen more often than nvim does
  - in neovim if the last position of the line is far behind the current value for `winwidth`, it behaves like vim and centers the cursor on screen.
  - but if the last character is within a small margin after `winwidth`, it will scroll horizontally so that the cursor is displayed      "touching" the border of the viewport; whereas vim always centers the cursor.

**Comment by pyrho** [comment]
Setting `sidescroll=0` in neovim indeed makes the issue disappear and conversely setting it to 1 in vim makes the issue appear.

That being said the only way to access a character that's out of the viewport is to use `zl` (just `l` does not move the cursor) which is non obvious for most people I'd say.

Not sure how this could be improved, since `sidescroll` is off, `$` should put the cursor on the right edge of the viewport, but `l` should be able to move passed the `extends` listchar.

**Comment by aufarg** [comment]
> That being said the only way to access a character that's out of the viewport is to use zl (just l does not move the cursor) which is non obvious for most people I'd say.

Yes I also think that it's a bug from Vim. In your particular case, since there will be at least one character on the right, you can set `siso=1` as a workaround. This will make sidescrolls to pan the window with at least 1 character offset. This will add offset when scrolling to the left too though.

**Comment by pyrho** [comment]
The workaround works perfectly thanks !

I tried looking into the code and did a little hack that solves my issue but I'm pretty sure it has other undesirable side effects. I have a feeling this might be a bit more complex that just a `+1` missing somewhere; then again I have no prior knowledge of (n)vim's codebase and I was just fooling around adding `printf` here and there to see where to focus.

I also tried (not too hard) adding a failing unit test but failed miserably.

For what it's worth here is the patch that "fixed" the issue for me (again huge disclaimer, 99% chance this is breaking something else).
```
diff --git a/src/nvim/charset.c b/src/nvim/charset.c
index f9d5adbc1..e98f38a5b 100644
--- a/src/nvim/charset.c
+++ b/src/nvim/charset.c
@@ -1303,7 +1305,8 @@ void getvcol(win_T *wp, pos_T *pos, colnr_T *start, colnr_T *cursor,
   }
 
   if (end != NULL) {
-    *end = vcol + incr - 1;
+    *end = vcol + incr - (wp->w_p_lcs_chars.eol != NUL ? 0 : 1); // pyrho's comment: removing the -1 fixes the issue
   }
 
   if (cursor != NULL) {
```

**Comment by zeertzjq** [comment]
I don't think this is a bug.
