### ISSUE TITLE
How to detect that macOS appearance changed

### ISSUE THREAD

**Issue by nikitavoloboev** [neovim/neovim#13010]
I want to be able to change the theme automatically based off macOS appearance. I found [this thread](https://www.reddit.com/r/vim/comments/e7hj9l/a_plugin_for_switching_between_dark_and_light/) that says it's possible to do in MacVim because it implements `OSAppearanceChanged` command. 

But it doesn't seem that neovim supports something like this?

I have a macro I use that switches between dark and light theme for me. Looks like this:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/6391776/94617920-a9b77300-02aa-11eb-9522-7ec9fe0811d5.png">

It checks for my current macOS theme with `defaults read -g AppleInterfaceStyle`. If it returns `Dark`, I then use sed to replace:

`let ayucolor="light"` variable with: `let ayucolor="mirage"` to update the theme.

The issue that although new nvim sessions will use the update theme. If I am editing an existing file or have nvim open somewhere, that theme won't change. I would have to manually open the file and run `:source ~/.dotfiles/nvim/init.vim` to update the session with new theme.

Is it possible to somehow do this automatically with neovim? Perhaps it's possible to run a command like `:source ~/.dotfiles/nvim/init.vim` externally without manually opening terminal and going to a tab with nvim?

Thank you.

**Comment by glacambre** [comment]
When you launch neovim, it opens a unix socket. On linux, these sockets are in /tmp, but this might differ on mac (you can find out the path of the socket by running `:echo $NVIM_LISTEN_ADDRESS` in neovim). Once you figure out where these sockets are, you can just use a neovim client (e.g. [nvr](https://github.com/mhinz/neovim-remote)) to connect to them and change the theme (e.g. `nvr --servername /tmp/nvimFooBar -c 'let ayucolor="light"'`).

**Comment by glacambre** [comment]
@nikitavoloboev Here are two examples of people updating their neovim colorscheme depending on the OS colorscheme:
https://old.reddit.com/r/neovim/comments/femk6t/finally_got_neovim_to_listen_for_transitions/
https://old.reddit.com/r/neovim/comments/iukdw4/darknotify_automatically_switch_to_a_dark_scheme/

Let us know if you encounter issues :)
