### ISSUE TITLE
In insert mode, after I input F3, Nvim stuck and won’t move

### ISSUE THREAD

**Issue by laniolove** [neovim/neovim#13020]
- `nvim --version`:
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

**Comment by vigoux** [comment]
Hi, thanks for reporting.

What version of neovim are you using ? I am not able to reproduce this locally...

**Comment by glacambre** [comment]
Closing since this has been awaiting an answer from the author for a while. @laniolove if you're still experiencing this issue, please let us know what terminal you're using, what neovim version you tried and how to reproduce the problem with `nvim -u NORC` and we'll re-open :).
