### ISSUE TITLE
macos binary missing for 0.5 nightly release

### ISSUE THREAD

**Issue by disrupted** [neovim/neovim#13021]
since https://github.com/neovim/neovim/issues/12790 was closed without being resolved I am opening a new issue.

For the 0.5 pre-release the macos binary is not available from the releases page. Therefore the link in the [Wiki: Installing Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim) is also broken: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz

**Comment by jamessan** [comment]
It _was_ resolved at the time, as the [last comment](https://github.com/neovim/neovim/issues/12790#issuecomment-680288640) indicated.  The nightly binaries are updated every day, and sometimes there are flakiness issues.  Just wait a day for it to get updated.
