### ISSUE TITLE
Ctrl + o causes program lockup 

### ISSUE THREAD

**Issue by Marc-Bender** [neovim/neovim#13035]
- `nvim --version` 0.4.4 :
- `vim -u DEFAULTS` (version: ) behaves differently? nope
- Operating system/version: Fedora 32
- Terminal name/version: xfce4-terminal (same behaviour in xterm)

### Steps to reproduce using `nvim -u NORC`
just press Ctrl + o
### Actual behaviour
well locks up. 
### Expected behaviour
escaping to normal mode if used in insert mode, going through the jump list if in normal mode. issue happens in normal mode only. in insert mode it works fine.

demonstration here: https://youtu.be/GyDVNwzgM9M

**Comment by KillTheMule** [comment]
Can't reproduce, neither with recentish neovim, nor with vim 8, on a variety of terminals (xterm, st, xfce4-terminal, konsole).

**Comment by glacambre** [comment]
@Marc-Bender are you still able to reproduce this bug on master? If yes, does it also happen with `nvim -u NORC -i NONE`?

**Comment by dundargoc** [comment]
Closing due to lack of response and reproduction.
