### ISSUE TITLE
[treesitter] errors with undofile

### ISSUE THREAD

**Issue by Happy-Dude** [neovim/neovim#13048]
Cross-linking to neovim core project since this is related to https://github.com/neovim/neovim/blob/3c5141d2cf359d9ac70799bb987482d753263782/runtime/lua/vim/treesitter/query.lua

ref: https://github.com/nvim-treesitter/nvim-treesitter/issues/528

Ping @bfredl and @vigoux for 👀

- `nvim --version`: `NVIM v0.5.0-f7aeac726`
- `vim -u DEFAULTS` (version: ) behaves differently? yes; treesitter specific bug
- Operating system/version: `macOS Catalina 10.15.7`
- Terminal name/version: `alacritty 0.5.0 (a6681e3)`
- `$TERM`: `tmux-256color`

### Steps to reproduce
1. In vimrc: `set undofile`
2. Create a file with multiple-highlighted lines (like sample.bash)

```bash
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
export PATH="/usr/local/opt/llvm/bin:$PATH"
export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
```

3. edit the file, delete some lines, save and quit
4. hit `u` to undo changes; treesitter errors at this point and prints text into the editor area (although text "underneath" can still be highlighted/selected)

![Screen Shot 2020-10-04 at 7 08 47 PM](https://user-images.githubusercontent.com/1098725/95033837-2f5d6900-0685-11eb-85e3-1cbe9c54cbbf.png)

### Actual behaviour

Treesitter errors and message is printed over textarea; the text "underneath" can still be edited/highlighted in visual mode

### Expected behaviour
* Treesitter should not error
* Treesitter errors should be printed into :messages
* Treesitter should be able to ingest and understand byte-changes from undofiles

**Comment by Happy-Dude** [comment]
As mentioned in https://github.com/nvim-treesitter/nvim-treesitter/issues/528#issuecomment-699660099 - I understand that `luahl` is still a WIP; this ticket was made to help track the issue.

**Comment by Happy-Dude** [comment]
Linking to https://github.com/neovim/neovim/pull/13935

**Comment by chentau** [comment]
@Happy-Dude can you try the wip pr to see if it fixes your issue?

**Comment by Happy-Dude** [comment]
Sorry @chentau, I haven't had a free moment to look at your PR extensively.
I was able to compile your changes and give it a spin; seems like it is intentional that old undofiles (pre this patch) would be incompatible moving forward?

Is there a way to calculate byte changes from old undofile versions?

**Comment by chentau** [comment]
Before the change, extmark information wasn’t saved at all. So there is no way to recover the buffer bytes update history without changing the underlying format of the undofile.
