### ISSUE TITLE
Vertical Block paste not working

### ISSUE THREAD

**Issue by medwatt** [neovim/neovim#13052]
- `nvim --version`: 0.5
- `vim -u DEFAULTS` (version: ) behaves differently? Yes.
- Operating system/version: Windows 10
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`
1. `set clipboard=unnamed`
2. Do `ctrl-v` to select a column, yank, and paste.

### Expected and Actual behaviour
After yanking a vertical column and the cursor is on the first line of the block you just yanked, if you paste the vertical column that you've just yanked, it should be appended to the block to which you're pasting. Instead, the vertical column gets pasted on a separate paragraph.

![](https://s1.gifyu.com/images/asasas.gif)

**Comment by bluz71** [comment]
This is a long-standing known issue that is noted in #1822 

The workaround is to use the [bfredl/nvim-miniyank](https://github.com/bfredl/nvim-miniyank) plugin as follows:

```viml
Plug 'bfredl/nvim-miniyank'
...
map p <Plug>(miniyank-autoput)
map P <Plug>(miniyank-autoPut)
```

I recommend closing this issue, #1822 already exists.

Best regards.

**Comment by medwatt** [comment]
> This is a long-standing known issue that is noted in #1822
> 
> The workaround is to use the [bfredl/nvim-miniyank](https://github.com/bfredl/nvim-miniyank) plugin as follows:
> 
> ```viml
> Plug 'bfredl/nvim-miniyank'
> ...
> map p <Plug>(miniyank-autoput)
> map P <Plug>(miniyank-autoPut)
> ```
> 
> I recommend closing this issue, #1822 already exists.
> 
> Best regards.

This issue has been around since 2015. Wow!!
