### ISSUE TITLE
[LSP] 'tsserver' codeActions do not work because make_range_params sets 'start' equal to 'end'

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#13058]
Hello Neovim LSP team,

Code actions for JavaScript code do work with the [LSC plugin](https://github.com/natebosch/vim-lsc).
They do not for Neovim LSP.

Note, this issue is not the same as #13057 which is also `codeAction` related.

After some debugging it appears it related to the actual `codeAction` request sent to the server.

For LSC this is the request sent to the TypeScript language server (this is successful in producing code actions at the cursor position):

```json
  "method": "textDocument/codeAction",
  "jsonrpc": "2.0",
  "id": 2,
  "params": {
    "context": { "diagnostics": [] },
    "range": {
      "end": { "character": 11, "line": 174 },
      "start": { "character": 10, "line": 174 }
    },
    "textDocument": {
      "uri": "file:///home/projects/AlbumShowPage.js"
    }
  }
}
```

And this is the request sent to the TypeScript language server by Neovim LSP (this does not work, no actions sent back):

```json
{
  "method": "textDocument/codeAction",
  "jsonrpc": "2.0",
  "id": 2,
  "params": {
    "context": { "diagnostics": [] },
    "range": {
      "end": { "character": 10, "line": 174 },
      "start": { "character": 10, "line": 174 }
    },
    "textDocument": {
      "uri": "file:///home/projects/AlbumShowPage.js"
    }
  }
}
```

The difference is the `end` position. In LSC it is position 11, which is the position of the cursor. In Neovim LSP it is 10 which is the same as the start position.

If I manually hack the Neovim LSP Lua code in `runtime/lua/vim/lsp/util.lua` and change the end position to 11 then it works, the TypeScript language server will send back actual code actions rather than an empty list.

[This is the Neovim code in question](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L1470):

```lua
function M.make_range_params()
  local position = make_position_param()
  return {
    textDocument = M.make_text_document_params(),
    range = { start = position; ["end"] = position; }
  }
end
```

The start is the same as the end.
This apparently breaks code actions for the TypeScript language server.

[This is the equivalent LSC code](https://github.com/natebosch/vim-lsc/blob/master/autoload/lsc/params.vim#L11):

```viml
function! lsc#params#documentRange() abort
  return { 'textDocument': {'uri': lsc#uri#documentUri()},
      \ 'range': {
      \   'start': {'line': line('.') - 1, 'character': col('.') - 1},
      \   'end': {'line': line('.') - 1, 'character': col('.')}},
      \ }
endfunction
```

The start has a `-1` added to it. Seems to work.

Best regards.

**Comment by kristijanhusak** [comment]
You can use `range_code_action` (https://github.com/neovim/neovim/blob/4a996bc431163b2a7b8e4bf3351d862887a78f83/runtime/lua/vim/lsp/buf.lua#L294)

**Comment by Jesse-Bakker** [comment]
Let me start by stating that the specification is not 100% clear/explicit about how this is supposed to work. However:

From the spec of `Range`:

"A range in a text document expressed as (zero-based) start and end positions. A range is comparable to a selection in an editor. Therefore the end position is exclusive."

The part "A range is comparable to a selection in an editor. Therefore the end position is exclusive." makes me think that the range `{"start": {"line":1, "character": 10}, "end": {"line":1, "character": 11}}` would correspond to character 10 being selected. In the case of the range representing a cursor position, nothing would be selected though. That means this would be a bug in tsserver's implementation and LSC's implementation being a workaround for language server bugs. Of course we could implement this workaround in neovim's client implementation as well, but maybe it would be good to file this as an issue with tsserver first.

**Comment by bluz71** [comment]
It would be interesting to see what other LSP clients send. I don’t know since LSC and Neovim LSP are the only implementations I have dealt with. If most other clients do as LSC does than that would be a strong indicator for Neovim LSP not to go against the grain.

My gut instinct is Microsoft is unlikely to change tsserver at this stage if for no other reason than it could potentially break most existing LSP clients.

**Comment by Jesse-Bakker** [comment]
I have looked at the code for [vim-lsp](https://github.com/prabirshrestha/vim-lsp) and [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim). vim-lsp sends the range for the cursor to the end of the line and LanguageClient-neovim does the same thing as the built-in neovim implementation.

There does not seem to be consensus about what range to send for a cursor position. The specification also does not specify what you should do, but just what the range you send means. That means we should choose whatever is least confusing as the default, which I would say is the current behaviour.

A workaround for the case of tsserver could be to bind your keybind for code actions to `range_code_action` with the range as the range that LSC sends.

For tsserver: as the tsserver in the typescript repo uses its own protocol, it is already conforming to that. The LSP wrapper from theia could however do the workaround that LSC uses before forwarding the request to tsserver itself, but only on empty ranges for example. That is a backward compatible change that makes it more conformant to the spec.

**Comment by bluz71** [comment]
Hello @Jesse-Bakker,

> There does not seem to be consensus about what range to send for a cursor position. The specification also does not specify what you should do, but just what the range you send means. That means we should, IMO, choose whatever is least confusing as the default, which I would say is the current behaviour.

Thanks for researching what vim-lsp and LanguageClient-neovim are doing. As you point out, there is no consensus so your point about leaving Neovim LSP is well reasoned and I agree with you.

> A workaround for the case of tsserver could be to bind your keybind for code actions to range_code_action with the range as the range that LSC sends.

Wondering out aloud, if we know this is an issue with Theia's LSP wrapper to `tsserver` then maybe it is something that should be done in [nvim-lspconfig tsserver config](https://github.com/neovim/nvim-lspconfig/blob/master/lua/nvim_lsp/tsserver.lua)? Maybe, maybe not?

Theia's LSP wrapper is now somewhat abandoned whilst [Microsoft is slowing inching there way to adding LSP support](https://github.com/microsoft/TypeScript/issues/39459) to `tsserver`.

It is probably best to just close this since LSP clients are not in agreement about code action range values.

Many thanks.
