### ISSUE TITLE
LSP: backslashes added to completions items (gopls)

### ISSUE THREAD

**Issue by fwojciec** [neovim/neovim#13061]
- `nvim --version`: NVIM v0.5.0-7b8935398
- language server name/version: golang.org/x/tools/gopls v0.5.0
- Operating system/version: Darwin Kernel Version 19.6.0 (OSX)

<details>
<summary>nvim -c ":checkhealth nvim nvim_lsp"</summary>
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color

health#nvim_lsp#check
========================================================================
  - ERROR: No healthcheck found for "nvim_lsp" plugin.
</details>

<details>
<summary>lsp.log</summary>
[lsp_log.txt](https://github.com/neovim/neovim/files/5336632/lsp_log.txt)
</details>

### Steps to reproduce using `nvim -u NORC`

```
go mod init example
touch main.go
nvim -u NORC main.go 
:lua require'nvim_lsp'.gopls.setup{}
:set omnifunc=v:lua.vim.lsp.omnifunc
:e
```
enter the following code:
```go
package main

type Test struct {
        testMap map[int32]map[int32]struct{}
}

func main() {
        var t Test
        t.testMap = ma
}
```

Try to complete the "ma" using omnicomplete (ctrl-x ctrl-o).

### Actual behaviour

The client completes the item as `map[int32]map[int32]struct{\}{`.

<img width="703" alt="Screen Shot 2020-10-06 at 22 30 48" src="https://user-images.githubusercontent.com/1042048/95257894-48048500-0825-11eb-98ec-223310c7dad6.png">

### Expected behaviour

The item should be completed as `map[int32]map[int32]struct{}{`.

**Comment by mjlbach** [comment]
@fwojciec I'm not able to reproduce, with a recent version of gopls(v0.6.2), I get the following results:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/13316262/110196212-e3f7e400-7df7-11eb-8344-40eeb63db29e.png">

**Comment by fwojciec** [comment]
Thanks for replying.  It's been a while, and I've reverted to using coc-nvim for the time being so I haven't been playing with the internal lsp at all in the last few months.  Clearly, things have changed since the initial report - I'm going to close this issue.
