### ISSUE TITLE
clipboard: provider not used after has('clipboard')

### ISSUE THREAD

**Issue by kevinoid** [neovim/neovim#13062]
- `nvim --version`: NVIM v0.4.4
- `vim -u DEFAULTS` behaves differently? Yes.  No clipboard providers.
- Operating system/version: Debian GNU/Linux (testing release, with kernel 5.8.7)
- Terminal name/version: xfce4-terminal 0.8.9.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Create `~/.config/nvim/plugin/myclipboard.vim` with the following content:
```vim
if !has('clipboard')
    echoerr '!clipboard'
endif

let g:clipboard = {
\   'name': 'myclipboard',
\   'copy': {
\      '+': 'unused',
\      '*': 'unused',
\    },
\   'paste': {
\      '+': 'echo HERE',
\      '*': 'echo HERE',
\   },
\ }
```
then run `nvim -u NORC` and paste from the clipboard `"+p`.

### Actual behaviour

Contents of the clipboard are pasted.

### Expected behaviour

`HERE` would be pasted.

If lines 1-3 of the above script are removed (or`has('clipboard')` replaced with anything else), `HERE` is pasted as expected.  Presumably this is easy to fix for plugins which only support Nvim, since `has('clipboard')` is always true, but can be problematic for scripts which attempt to support Vim as well.

Thanks for considering,
Kevin

**Comment by erw7** [comment]
In neovim, `has('clipboard')` checks if there are any providers available. Therefore your usage is not appropriate. It is appropriate to use `has('nvim')` as a condition for determining whether or not to set `g:clipboard`.

If you change your script as follows, it will most likely work the way you want it to, but if there are no available providers, it will work differently than you intend.

```vim
if !has('clipboard')
    echoerr '!clipboard'
endif

let g:clipboard = {
\   'name': 'myclipboard',
\   'copy': {
\      '+': 'unused',
\      '*': 'unused',
\    },
\   'paste': {
\      '+': 'echo HERE',
\      '*': 'echo HERE',
\   },
\ }

unlet g:loaded_clipboard_provider
runtime autoload/provider/clipboard.vim
```

**Comment by kevinoid** [comment]
Thanks @erw7.  Perhaps it's worth adding a warning to the the docs for `g:clipboard` that it has no effect if set after `has('clipboard')`?

**Comment by erw7** [comment]
@kevinoid Yes. I think we should write something in the help.
