### ISSUE TITLE
Windows Terminal transparency  not passing through?

### ISSUE THREAD

**Issue by musm** [neovim/neovim#13065]
- `nvim --version`:
```
> nvim --version
NVIM v0.5.0-709-g4f8d98e58
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Windows 10, Version 20H2 (Build 19042.546)
- Terminal name/version: Windows Terminal v1.3.2651.0
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
![image](https://user-images.githubusercontent.com/4319522/95352984-c2b6ba00-0890-11eb-8f0b-2706ebf6baf2.png)

Note the black background surrounded by the transparent border (which should be the actual background) 

### Expected behaviour

![image](https://user-images.githubusercontent.com/4319522/95353161-f560b280-0890-11eb-8fbb-3bd547fda019.png)

Note transparency is respected

**Comment by erw7** [comment]
The cause of this is probably a limitation of Window Terminal. If you specify a background color, Windows Terminal does not use transparency. You can check this in Powershell by doing the following (It should appear on a green, non-transparent background).

```
Write-Host "$([char]27)[42m0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" 
```

If you want to enable transparency in Window Teminal, set the following to disable the background color specified in colorscheme.

```vim
augroup my_color_scheme
  autocmd!
  autocmd ColorScheme * highlight Normal guibg=NONE ctermbg=NONE
  autocmd ColorScheme * highlight NonText guibg=NONE ctermbg=NONE
augroup END
```

**Comment by musm** [comment]
Many thanks, that does it.

For those looking at this, here's what I put in my `init.vim`
```

set background=dark
colorscheme vimbrant

augroup vimbrant
  autocmd!
  autocmd ColorScheme * highlight Normal guibg=NONE ctermbg=NONE
  autocmd ColorScheme * highlight NonText guibg=NONE ctermbg=NONE
augroup END

```

**Comment by erw7** [comment]
@musm I think you need to set up `autocmd` before setting up `colorscheme`.

**Comment by desmap** [comment]
The above mentioned work-arounds didn't do anything for me...
