### ISSUE TITLE
:[count]chistory not supported

### ISSUE THREAD

**Issue by knkj28** [neovim/neovim#13076]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: 8) behaves differently? yes
- Operating system/version: macOS 10.15.6
- Terminal name/version: terminal.app
- `$TERM`:xterm-256color

neovim supports only simple `:chistory` command. (no `[count]`) 
I can't specify `[count]` parameter. Is this behavior intentional?

Vim8 support `[count]` parameter.

**Comment by erw7** [comment]
Part of vim-8.1.1281 has been merged by #12888. Because the commit message contains "vim-patch:8.1.1281", `vim-patch.sh` no longer lists v8.1.1281. I think that's why the patch wasn't ported, so I don't think it was intentional.

**Comment by zeertzjq** [comment]
Closed by #13655
