### ISSUE TITLE
Saving a session with sessionoptions without 'terminal' still saves/ restores terminal buffers

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#13078]
- `nvim --version`: v0.5.0-741-gca6815115
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

By default, `sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize` which doesn't have a 'terminal' included in it. So terminal buffers should not be saved off and restored. However, these terminal buffers are restored in NVIM when the session saved file is loaded whereas they are not saved and restored in vanilla VIM.

### Expected behaviour

NVIM should obey leaving out 'terminal' in sessionoptions.

**Comment by janlazo** [comment]
Patch v8.0.1592 is not ported yet.

**Comment by yutkat** [comment]
I see. This feature is important to me, so please fix it as soon as possible!
