### ISSUE TITLE
unable to navigate when opening stdin via nvim

### ISSUE THREAD

**Issue by gko** [neovim/neovim#13073]
Hello,

I'm not sure whether it's a `neovim` bug or `prettier` or something else.

- `nvim --version`: `v0.5.0-3ea5df0` and `0.4.4`
- `vim -u DEFAULTS` (version: 8.2.1700) behaves differently? yes
- Operating system/version: macOS 10.15.7
- Terminal name/version: iterm 2 3.3.12
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. install prettier: `npm install -g prettier@1.9`
2. create a ts file `~/test.ts`:
```
const a = "test";
```
3. run `prettier ~/test.ts | nvim -`
4. try to navigate (with `hjkl` or arrow keys)

### Actual behaviour

![image](https://user-images.githubusercontent.com/1726487/95430821-9a8c9100-094c-11eb-9892-d8983e11ffc4.png)

### Expected behaviour

You should be able to navigate within buffer.

I also saw similar behaviour with `francoiscabrol/ranger.vim` plugin when opening a folder.

❤️

**Comment by Happy-Dude** [comment]
I cannot reproduce this from `iterm2` with `xterm-256color` using homebrew `prettier` v2.1.2

What is the term, filetype, encoding from within neovim?

The characters being printed onto your screen make me think that it has more to do with your terminal settings or shell than it has to do with neovim.

**Comment by erw7** [comment]
The problem is likely caused by the program on the left side of the pipe changing the `tty` to cooked mode after neovim calls `uv_tty_set_mode`. If the `stdin` is not a `tty`, delaying tui initialization until `VimEnter` may improve it. However, I don't think this problem can be completely solved due to the race condition. For example, if the program on the left side of the pipe looks like the following, there is no way to solve the problem on the neovim side.

```c
#include <stdio.h>
#include <unistd.h>
#include <termio.h>

int main(void)
{
  struct termios tm;
  if (!isatty(STDIN_FILENO)) {
    fprintf(stderr, "stdin is not tty\n");
    return 1;
  } else {
    if (tcgetattr(STDIN_FILENO, &tm)) {
      fprintf(stderr, "tcgetattr failed\n");
      return 1;
    }
  }
  fprintf(stdout, "Hello\n");
  fflush(stdout);
  close(STDOUT_FILENO);
  sleep(5);
  if (tcsetattr(STDIN_FILENO, TCSANOW, &tm)) {
    fprintf(stderr, "tcsetattr failed\n");
    return 1;
  }
  return 0;
}
```

**Comment by erw7** [comment]
How about using `:r!` as a workaround for a program that changes the state of the `TTY` at the end of the program?
