### ISSUE TITLE
Slow mapping changes when changing modes

### ISSUE THREAD

**Issue by perrin4869** [neovim/neovim#13086]
This is one of the issues preventing me from switching to neovim and enjoying the many new features such as virtual text.

When I use vim8, by muscle memory I tend to exit insert mode and hit save. I have `;` mapped to `:`.
In `nvim`, the mappings for normal mode do not seem to be reflected back as quickly as with `vim8`, so you need about a second after hitting `ESC` to be able to hit `;` and enter command mode. In `vim8` this latency is not felt.

- `nvim --version`:

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -fPIC -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/SBo/neovim-0.4.4/build/config -I/tmp/SBo/neovim-0.4.4/src -I/usr/include -I/tmp/SBo/neovim-0.4.4/build/src/nvim/auto -I/tmp/SBo/neovim-0.4.4/build/include
Compiled by root@landau.julian.dotcore.co.il

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: slackware64-current
- Terminal name/version: rxvt-unicode-truecolor
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:nmap ; :
# Start typing in insert mode, then hit ESC and quickly hit ";" after

```

### Actual behaviour
In nvim, I enter normal mode, in vim8.2 I enter command mode

### Expected behaviour
I expect to enter command mode with both nvim and vim8

**Comment by ThomasFeher** [comment]
Could [that](https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed) be the issue?

**Comment by perrin4869** [comment]
Hm... Outside of tmux the latency is indeed smaller, but vim8 still seems to be faster (i.e., in vim8 I can't hit the keys fast enough to end in normal mode)

**Comment by KillTheMule** [comment]
> (i.e., in vim8 I can't hit the keys fast enough to end in normal mode)

I have not been able to do this in nvim as well, using something close to current master (using urxvt as well as xterm). You sure you did `nvim -u NORC` so no plugin or mapping can interfere? Check `:map ;` to be sure. If so, maybe you want to try current master.

**Comment by perrin4869** [comment]
Tried both `nvim -u NORC` and `nvim -u NONE`. 
I will try current master later!

**Comment by perrin4869** [comment]
I can confirm this hasn't been fixed with latest nightly:

```
$ nvim --version
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -fPIC -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/SBo/neovim-nightly/build/config -I/tmp/SBo/neovim-nightly/src -I/usr/include -I/tmp/SBo/neovim-nightly/build/src/nvim/auto -I/tmp/SBo/neovim-nightly/build/include
Compiled by root@landau.julian.dotcore.co.il

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Regardless of running tmux or not, if I press `ESC` and `;` while in insert mode almost at the same time, `nvim` will enter normal mode, while `vim` will go into `command` mode.
However, I think I rushed into diagnosing the issue. Actually, using `:` will result in the same kind of delay as `;` mapped to `:`. Maybe vim8 is just a tiny bit more responsive than `nvim`?

**Comment by erw7** [comment]
If you type `<ESC>;` quickly enough, the key sequence generated will be `<M-;>`. So mapped in normal mode `:` will not run. As a workaround, why don't you try the following settings?

```vim
:inoremap <M-;> <ESC>:
:nnoremap ; :
```

**Comment by perrin4869** [comment]
@erw7 that was it, thanks!
Can you give a few more insights into the difference between nvim and vim8 here?
Maybe it'll be useful to add this to the FAQ?

**Comment by jamessan** [comment]
> If you type `<ESC>;` quickly enough, the key sequence generated will be `<M-;>`.

After https://github.com/neovim/neovim/pull/13042, this was only supposed to happen if a mapping for `<M-;>` exists, otherwise it should always be treated as `<Esc>;`.

**Comment by erw7** [comment]
@jamessan I don't think the change in #13042 makes sense. Because in neovim, the conversion from `ESC+c` to `<M-c>` is done by [`tk_getkeys()`](https://github.com/neovim/neovim/blob/master/src/nvim/tui/input.c#L292). So, regardless of #13042, any `ESC+c` entered within `ttimeoutlen` is treated as `<M-c>`, regardless of the mapping.

**Comment by erw7** [comment]
Sorry for the inaccuracies. In the end, I think this issue comes down to the following, please correct me if I'm wrong @jamessan.

If I type `;` following `<ESC>` quickly enough, the TUI thread will send `<M-;>` to the `input_enqueue()`. This `<M-;>` will be changed to `<ESC>;` if there is no mapping in `vgetc()`. In this case, the `;` mapping is not resolved.  So mapped in normal mode `:` will not run. By contrast, if the TUI thread sends `<ESC>;` to `input_enqueue()`, the mapping of `;` is also resolved.

If I make changes like the following patch, the mapping of `;` also seems to be resolved for `<M-;>`, is there a problem?

```diff
diff --git a/src/nvim/getchar.c b/src/nvim/getchar.c
index cbd9582f8..99219b5b3 100644
--- a/src/nvim/getchar.c
+++ b/src/nvim/getchar.c
@@ -1534,7 +1534,7 @@ int vgetc(void)
       if (!no_mapping && KeyTyped
           && (mod_mask == MOD_MASK_ALT || mod_mask == MOD_MASK_META)) {
         mod_mask = 0;
-        stuffcharReadbuff(c);
+        ins_char_typebuf(c);
         u_sync(false);
         c = ESC;
       }
```

**Comment by erw7** [comment]
> Also, why is the key sequence <M-;>? Is this because of the TERM?

Yes. The terminal generates the key sequence `<ESC>c` for a `c` modified by the Alt key. This can be confirmed in the following way.

```sh
cat -v -
# type <Alt-;><Return>
```

Ref. https://gist.github.com/justinmk/a5102f9a0c1810437885a04a07ef0a91#file-xterm-control-sequences-txt-L1181

**Comment by perrin4869** [comment]
@erw7 thanks for the clarification! Should we close this, or do want to apply some changes?

**Comment by jamessan** [comment]
> If I make changes like the following patch, the mapping of `;` also seems to be resolved for `<M-;>`, is there a problem?

Sounds reasonable.  Seems like this is a good test case, too.
