### ISSUE TITLE
Problem with rescaling when resizing or maximizing Alacritty or Windows Terminal window

### ISSUE THREAD

**Issue by CesarB794** [neovim/neovim#13082]
Neovim does not seem to rescale well when maximizing the Alacritty or Windows Terminal window, but within the native Powershell console there is no problem.
I use the PSReadline module to be able to run neovim inside Powershell.
I will attach the respective screenshots showing the problem, neovim version an my Windows version.
Windows Terminal:

![2020 10 03-01 05](https://user-images.githubusercontent.com/54776512/95651742-c762b480-0ac2-11eb-919f-e7be0d73c1f9.png)
![2020 10 03-01 05_01](https://user-images.githubusercontent.com/54776512/95651748-ccbfff00-0ac2-11eb-82ec-9f24a93a20cd.png)
![2020 10 03-01 05_02](https://user-images.githubusercontent.com/54776512/95651752-d184b300-0ac2-11eb-8369-a61bf5a7736f.png)
![2020 10 03-01 05_03](https://user-images.githubusercontent.com/54776512/95651756-d3e70d00-0ac2-11eb-938b-25700948b696.png)
Alacritty:

![2020 10 03-01 06](https://user-images.githubusercontent.com/54776512/95651757-d47fa380-0ac2-11eb-9e2d-52af3eb67bda.png)
Native Powershell console:

![2020 10 03-01 14](https://user-images.githubusercontent.com/54776512/95651758-d5183a00-0ac2-11eb-9ee7-6e2d454b40ea.png)
![2020 10 03-01 14_01](https://user-images.githubusercontent.com/54776512/95651761-d8132a80-0ac2-11eb-9951-3d0c65c132c5.png)
Neovim version(I have installed neovim using the chocolatey package manager):

![2020 10 10-06 29](https://user-images.githubusercontent.com/54776512/95651762-da758480-0ac2-11eb-8d00-851d8000a455.png)
My OS:

![2020 10 10-06 36](https://user-images.githubusercontent.com/54776512/95651781-f1b47200-0ac2-11eb-99bd-466269add081.png)

**Comment by erw7** [comment]
I have this problem fixed in the latest master at hand.

**Comment by CesarB794** [comment]
> I have this problem fixed in the latest master at hand.

Thank you. It used a somewhat old version of neovim, 0.4.5. I finished installing beta version 0.5 and problem solved.

**Comment by bluz71** [comment]
> Thank you. It used a somewhat old version of neovim, 0.4.5. I finished installing beta version 0.5 and problem solved.

I suggest closing this issue.
