### ISSUE TITLE
Tag Block motion doesn't work when the > of opening tag is on a different line.

### ISSUE THREAD

**Issue by happycoder97** [neovim/neovim#13087]
- `nvim --version`: v0.4.4
- `vim -u DEFAULTS` (version: 8.2) behaves differently? Has the same bug.
- Operating system/version: Arch Linux

### Steps to reproduce using `nvim -u NORC`

Save this file as `test.vue`:
```vue
<div
  v-if="adding"
>
  <div
    class="bg-white flex flex-col px-4 gap-3"
  >
    <div class="flex flex-col gap-3">
      <div
        :key="idx"
        class="flex gap-3"
      >
      </div>
    </div>
  </div>
</div>
```
Run `nvim -u NORC test.vue`.
Type `vat`.

### Actual behaviour
Selects till line 13.

### Expected behaviour
Select till the end of file.

**Comment by aufarg** [comment]
Should be fixed by #13097
