### ISSUE TITLE
Has pumwidth been ported?

### ISSUE THREAD

**Issue by flimofly** [neovim/neovim#13085]
Could not find this anywhere, but has `pumwidth` already been ported? 

I'm trying to find away around the issue where, with long completions near the right edge of the nvim window, the completion results get truncated. Going by [this old thread](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=450481) I thought this had long been fixed by showing the popup to the left hand side of the cursor in those cases. But that doesn't appear to be the case.

What could help me out is setting a very large `pumwidth`. But my nvim (0.4.3) only recognizes `pumheight`.

**Comment by KillTheMule** [comment]
Seems it was ported here: https://github.com/neovim/neovim/commit/703ed11c97256997aa0ce8aa5fe04b6e89e8e829. I suggest you try current master.

**Comment by lervag** [comment]
I'm on the nightly branch (currently on NVIM v0.5.0-729-gf7aeac726), and at least it does not seem like `pumwidth` has any effect on the completion window. Or perhaps I misunderstand what is supposed to happen?

**Comment by flimofly** [comment]
Both @lervag  and I have found that `pumwidth` is recognized (in Neovim 0.4.4 and the nightly build 0.5.0 mentioned above) but doesn't really do anything.

Someone knows why?

**Comment by KillTheMule** [comment]
There are [tests](https://github.com/neovim/neovim/commit/703ed11c97256997aa0ce8aa5fe04b6e89e8e829#diff-d51dffa059b1373105af778eb71eb077) that have been adjusted with that commit, do those do what they're supposed to do? Are you seeing something different? Maybe there are follow-up patches from vim that have not been ported.

**Comment by erw7** [comment]
@flimofly The releae-0.4 branch does not include 703ed11, so `pumwidth` cannot be used in the 0.4 series. If you want to use `pumwidth`, you need to use nightly.

@lervag Is it TUI or GUI that `pumwidth` is not working? If `ext_popupmenu` is enabled in GUI, the popup menu is drawn on the GUI side, so I don't think it's affected by `pumwidth`. In the case of neovim-qt, it must be invoked with the `--no-ext-popupmenu` command line option in order for `pumwidth` to have any effect.

The display position is strange, but in my environment, `pumwidth` seems to have an effect as shown below.

Left: NVIM v0.5.0-746-gf7cc3ae0b, Right vim 8.2.1830
Top: pumwidth=5
Middle: pumwidth=15
Bottom: pumwidth=30
![pumwidth](https://user-images.githubusercontent.com/11682285/95817509-9d2c2380-0d5c-11eb-9a72-fdc072f815af.png)

**Comment by lervag** [comment]
> @lervag Is it TUI or GUI that `pumwidth` is not working?

TUI (I don't use GUI).

> The display position is strange, but in my environment, `pumwidth` seems to have an effect as shown below.

I can confirm that there is an effect, but it is not consistent and not persistent. With persistent, I mean it looks "correct" the first time the completion window pops up, but then reverts to the old style on subsequent completions.

However, in my initial tests I've used my current `init.vim`. If I make a minimal vimrc with basically only `set pumwidth=35`, it seems to work more or less as expected. I will therefore look into which setting or plugin is interfering.

**Comment by janlazo** [comment]
@lervag What's exact Vim version and the `:version` output? I didn't port all of the pum patches that affect pumwidth.

**Comment by janlazo** [comment]
Nevermind. I didn't port the patches correctly. Thank you @lervag  and @erw7.

**Comment by lervag** [comment]
Great, I'm happy to hear you've figured it out! I've been too busy to respond to your first comment yet, let me know if there is something I can do (testing or providing more information from my side).
