### ISSUE TITLE
LSP: languageId should be configurable per language server

### ISSUE THREAD

**Issue by jandamm** [neovim/neovim#13093]
Currently the languageId is the current filetype.
As the comment states, the filetype has to be a valid languageId.

https://github.com/neovim/neovim/blob/948e625e1ecbdb1d4771e1481b3d6534b21250c9/runtime/lua/vim/lsp.lua#L232-L233

While this is true in probably most cases, it definitely isn't true for sub-filetypes like `ios.swift`.
I've had this issue with `vim-lsp` as well and tackled it by allowing the user to provide a function to the server config which should evaluate to the languageId. If it isn't present the filetype is used as backup. (See https://github.com/prabirshrestha/vim-lsp/issues/879)

If you think this is a valid solution here as well, I'd be happy to create a PR.

**Comment by glepnir** [comment]
yep. @tjdevries

**Comment by tjdevries** [comment]
Yup! Makes sense to me. Tag me in the pr
