### ISSUE TITLE
signcolumn values are not multiples of 1 and column width must be at least 2

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#13098]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: Manjaro Linux
- Terminal name/version: kitty 0.18.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set signcolumn=yes:1
```

### Actual behaviour
Two columns are used, even though `signcolumn` is set to `1`.
![2020-10-16-064928_93x73_scrot](https://user-images.githubusercontent.com/46303212/96216636-11dfa780-0f81-11eb-902c-7668c417131c.png)

### Expected behaviour
One column is used regardless of whether marker can fit into one column.

### Additional information

As of right now, values passed to `signcolumn` are multiples of 2 (this means that setting it to 1 yields 2 real columns, 2 yields 4 real columns etc.), which is not an obvious behavior. If so, the accepted values would be expected to be 2, 4, 6 etc. This behavior is not documented in `:h 'signcolumn'`.

### Suggestion
Ideal solution would be to make `signcolumn` yield 1 column given number 1.
If this is rejected, or as temporary measure, document that this option produces multiples of two of the given number.

### Previous work
Abandoned work in this area: https://github.com/neovim/neovim/pull/9788
ALE tracking issue: https://github.com/dense-analysis/ale/issues/1015
`signcolumn` implementation tracking issue: https://github.com/neovim/neovim/issues/990
`signcolumn` implementation: https://github.com/neovim/neovim/commit/36762a00a8010c5e14ad4347ab8287d1e8e7e064

**Comment by Shougo** [comment]
Vim has same behavior?
If so, you should report it in Vim issues.

**Comment by subnut** [comment]
@avemilia This is not a neovim-specific issue. Vim has the same behavior. Please report this to vim.

**Comment by chrisbra** [comment]
set signcolumn=yes:1 is not a valid vim option value

**Comment by fsouza** [comment]
> set signcolumn=yes:1 is not a valid vim option value

What do you mean? It is. See the docs:

```
						*'signcolumn'* *'scl'*
'signcolumn' 'scl'	string	(default "auto")
			local to window
	When and how to draw the signcolumn. Valid values are:
	   "auto"   	only when there is a sign to display
	   "auto:[1-9]" resize to accommodate multiple signs up to the
	                given number (maximum 9), e.g. "auto:4"
	   "no"	    	never
	   "yes"    	always
	   "yes:[1-9]"  always, with fixed space for signs up to the given
	                number (maximum 9), e.g. "yes:3"
	   "number"	display signs in the 'number' column. If the number
			column is not present, then behaves like 'auto'.
```

The number is indeed being multiplied by 2 (so signcolumn=yes:2 takes 4 characters): https://github.com/neovim/neovim/blob/ca7449db46062098cc9b0c84401655cba7d3a53f/src/nvim/screen.c#L1762-L1775

I think @teto had a TODO about that, he may have more info?

**Comment by fsouza** [comment]
> set signcolumn=yes:1 is not a valid vim option value

ops sorry I can't read, didn't realize you were talking about vim lol

**Comment by teto** [comment]
the other part of the implementation is https://github.com/neovim/neovim/blob/master/src/nvim/option.c#L7430
The TODO was about implementing the dynamic sizing but someone else did. We should probably get rid of win_signcol_width :s

**Comment by fsouza** [comment]
Do we get rid of win_signcol_width and change the default signcolumn to be auto:2? Just so folks using the default value don't get a surprise? Or do we just remove it and document the change in behavior?

**Comment by teto** [comment]
I think one should be a valid value so anyone feel free to pickup. You can mention the change in https://github.com/neovim/neovim/wiki/Following-HEAD

**Comment by wavded** [comment]
Just encountered this as well. The documentation stated that `1` is a valid number but doesn't seem to work.

**Comment by vurtune** [comment]
Is there an issue if _**signcolumn**_ has only one column?

**Comment by lewis6991** [comment]
Yes because signs are allowed to occupy two characters.
