### ISSUE TITLE
Quickfix window broken after e82b8ddef16eb7ce96e1d3d063ff529f79ed6bb2

### ISSUE THREAD

**Issue by gravndal** [neovim/neovim#13104]
- `nvim --version`: NVIM v0.5.0-756-g288f7f855
- `vim -u DEFAULTS` (version: ) behaves differently? Unknown.
- Operating system/version: nixos 21.03pre246591.8294af02845
- Terminal name/version: alacritty 0.5.0 + tmux 3.1b
- `$TERM`: tmux-256color

### Steps to reproduce

Plugins used:
[1] https://github.com/neovim/nvim-lspconfig
[2] https://github.com/nvim-lua/diagnostic-nvim (to populate the location list)
~~[3] https://github.com/romainl/vim-qf~~

On this sample file:
```
#!/usr/bin/env python3


this is a syntax error
```

With the following configuration:
```
$ cat config/nvim/init.vim
autocmd Filetype qf wincmd J

$ cat config/nvim/after/plugin/something.vim
lua require'nvim_lsp'.pyls.setup{on_attach=require'diagnostic'.on_attach}
```

And plugins placed under data/nvim/site/pack/...

Loaded by setting `XDG_DATA_HOME` and `XDG_CONFIG_HOME`

Do:
1. Edit `repro.py`
2. Open the location list
3. Fix the syntax error
4. Close the location list
5. Undo 3.
6. Observe the broken window

Some notes: 
 - ~~Whether or not the mapping from vim-qf is used does not seem to matter, however I have not managed to reproduce the issue without loading the plugin.~~
- ~~I'm unfamiliar with how to go about populating the location list in the background without using [1] and [2], and so have not tried reproducing this in vim.~~
- Having slept on it I realise that I'd completely forgotten about Neomake/ALE. Still, I'll trust @mechkblife on vim reproducibility. 

### Actual behaviour

![2020-10-17-14:20:30](https://user-images.githubusercontent.com/4656860/96337022-0032f880-1084-11eb-90b2-07768a540b2c.png)
After resizing it using the mouse with `set mouse=a`:
![2020-10-17-14:20:43](https://user-images.githubusercontent.com/4656860/96337024-00cb8f00-1084-11eb-8c80-7f39482f4794.png)

### Expected behaviour

No broken window/statusline.

### Bisect

```
e82b8ddef16eb7ce96e1d3d063ff529f79ed6bb2 is the first bad commit
commit e82b8ddef16eb7ce96e1d3d063ff529f79ed6bb2
Author: Jan Edmund Lazo <jan.lazo@mail.utoronto.ca>
Date:   Sat Oct 10 13:11:34 2020 -0400

    vim-patch:8.1.0877: new buffer used every time the quickfix window is opened

    Problem:    New buffer used every time the quickfix window is opened.
    Solution:   Reuse the buffer. (Yegappan Lakshmanan, closes vim/vim#3902)
    https://github.com/vim/vim/commit/ee8188fc74a7cf9ee7acb634b2bb7a032d0cb24c

 src/nvim/buffer.c                  | 14 ++-----
 src/nvim/quickfix.c                | 77 +++++++++++++++++++++++++-------------
 src/nvim/testdir/test_quickfix.vim | 43 +++++++++++++++++++++
 3 files changed, 99 insertions(+), 35 deletions(-)
```

**Comment by mechkblife** [comment]
Seeing this exact issue as well. Upon further digging, I noticed that I had `autocmd Filetype qf wincmd J` in my vimrc. Removing this line seems to stop this issue (I think under limited testing). Check if the plugins you are using define this setting. The problem doesn’t happen on vanilla VIM. Hopefully devs can figure out a fix soon.

**Comment by gravndal** [comment]
@mechkblife Thanks, that autocmd triggers it nicely.

**Comment by erw7** [comment]
The minimum procedure to reproduce this problem is as follows. This does not happen in vim.

#### minimum.vim
```vim
let w_height = winheight(0)
autocmd FileType qf wincmd J
copen
cclose
call setqflist([])
call assert_equal(w_height, winheight(0))
if !empty(v:errors)
  echomsg v:errors[0]
endif
```

```
nvim -u NORC
:so minimum.vim
```

**Comment by kevinhwang91** [comment]
@janlazo Does it mean that neovim didn't need `8.1.0877` patch from vim? I hope this patch can be merged into master bug-free.

**Comment by janlazo** [comment]
@kevinhwang91  Patch 8.1.0877 is needed for patch 8.1.1015 but I reverted both.
