### ISSUE TITLE
What's the purpose of `Fixedgq` for `typescript.vim`

### ISSUE THREAD

**Issue by cideM** [neovim/neovim#13113]
I was nearly going crazy trying to understand why `formatprg=prettier` was failing in Typescript files but working in Javascript files. In a typescript file like this:

```typescript
const foo = () => { 
	console.log("hi"); 
	console.log("bar"); 
	console.log("bar"); 
	console.log("bar"); 
	console.log("bar"); 
}
```

selecting the entire buffer and doing `gq` would give me everything on one line

```typescript
const foo = () => { console.log("hi"); console.log("bar"); console.log("bar"); console.log("bar"); console.log("bar"); }
```

Even with a vanilla Neovim instance it was formatting things incorrectly. Then I sort of stumbled upon (emphasis my own)

```
gq{motion}		        Format the lines that {motion} moves over.
			        Formatting is done with one of three methods:
			        1. **If 'formatexpr' is not empty the expression is
			             evaluated.  This can differ for each buffer.**
			        2. If 'formatprg' is not empty an external program
			            is used.
			        3. Otherwise formatting is done internally.
```
 
So because Neovim is now setting `formatexpr` in all Typescript buffers it is effectively disabling my own `formatprg` which seems like a very strange thing to do. I checked the source of both `neovim/neovim` and also `yats` but there's no comment or PR that explains the purpose of this function, so I opened this issue.

**Comment by jdhao** [comment]
You can override neovim's setting with your own setting. Does not that work for you? For example, when editing typescript file, set `formatexpr` to empty.

**Comment by erw7** [comment]
Neovim does not set the `formatprg` for either `Javascript` or `Typescript` by default. It looks like Neovim is not overriding your settings and setting the `formatprg` to empty, it just doesn't reflect the `formatprg` you set in `Typescript`. I think you should review your setup first.

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by cideM** [comment]
> You can override neovim's setting with your own setting. Does not that work for you? For example, when editing typescript file, set formatexpr to empty.

That's what I'm doing but it just struck me as a bit strange that this was the new default

**Comment by jdhao** [comment]
Are you sure it is set by neovim? What is the output of `verbose set formatexpr` when you open typescript file?

**Comment by cideM** [comment]
```
formatexpr=Fixedgq(v:lnum,v:count)
        Last set from /nix/store/2pvb6y0w4z3pch001b5sc9ymxjxy9wyh-neovim-unwrapped-master/share/nvim/runtime/indent/typescript.vim l
ine 20
```

This is what I currently get

**Comment by jdhao** [comment]
I am seeing similar result. So it seems that formatexpr is indeed set up by a runtime file bundled with Neovim.

**Comment by cideM** [comment]
For posterity [this is the file](https://github.com/neovim/neovim/blob/master/runtime/indent/typescript.vim#L19-L21) setting up `formatexpr` in Typescript. I think it's a bit unfortunate to set these options since they will silently override a `formatprg`, even though that option seems to be much more widespread when it come to "how do I format a buffer with Vim". But it is what it is and the workaround is to set `formatexpr=`

**Comment by erw7** [comment]
I'm sorry, I misunderstood the problem. It is true that `runtime/indent/typescipt.vim` prevents the user-set `formatprg` from being enabled. Why don't you try reporting the problem to https://github.com/HerringtonDarkholme/yats.vim/issues?

The workaround seems to be to set up `init.vim` or `~/.config/nvim/after/indent/typescript.vim` as follows.

```vim
" init.vim
filetype plugin indent on
" Must be set after `:filetype indent on`
augroup my_ts_ft
  autocmd!
  autocmd FileType typescript set formatexpr= formatprg=prettier\ --parser\ typescript
augroup END
```

```vim
" ~/.config/nvim/after/indent/typescript.vim
if exists('b:did_my_ts_indent')
  finish
endif
let b:did_my_ts_indent = v:true
setlocal formatexpr=
setlocal formatprg=prettier\ --parser\ typescript
if exists('b:undo_indent')
  let b:undo_indent .= ' | setlocal formatexpr< formatprg<'
else
  let b:undo_indent = 'setlocal formatexpr< formatprg<'
endif
```
