### ISSUE TITLE
Building NeoVim from source on Windows 10

### ISSUE THREAD

**Issue by Chaoticsys101** [neovim/neovim#13112]
- `nvim --version`: 0.5.0
- Operating system/version: Windows 10
- Terminal name/version: Windows Terminal / MSYS2

I would like to build neovim from source using MSYS2 in Windows 10 (or with mingw32-make or cmake using Windows Terminal). 
There are a few things I need, 64bit build, Python support and I would like to know how to specify the name in `nvim --version ` where it says `compiled by`. 
Thank you in advance for your attention.

**Comment by erw7** [comment]
First, read the following section of the Wiki.

Ref. https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msys2

For more information on Python support, please read the following sections of the FAQ

Ref. https://github.com/neovim/neovim/wiki/FAQ#python-support-isnt-working

Please read [config/CMakeLists.txt](https://github.com/neovim/neovim/blob/master/config/CMakeLists.txt) for `compiled by`.

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by Chaoticsys101** [comment]
Thank you and sorry I didn't know where to ask.
