### ISSUE TITLE
lsp: pyls custom config not applied

### ISSUE THREAD

**Issue by Glavnokoman** [neovim/neovim#13110]
- `nvim --version`: NVIM v0.5.0-754-g3566244d0
- language server name/version: python-language-server 0.35.1
- Operating system/version: Linux  5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux

<details>
<summary>nvim -c ":checkhealth nvim nvim_lsp"</summary>
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 10
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: screen-256color

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyls: configuration checked.
  - INFO: clangd: configuration checked.
</details>

<details>
<summary>lsp.log</summary>

[ INFO ] 2020-10-18T12:24:03+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:283 ]	"Starting RPC client"	{  args = {},  cmd = "pyls",  extra = {}}
[ DEBUG ] 2020-10-18T12:24:03+0200 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:568 ]	"LSP[pyls]"	"initialize_params"	{  capabilities = {    callHierarchy = {      dynamicRegistration = false,      <metatable> = <1>{        __tostring = <function 1>      }    },    textDocument = {      codeAction = {        codeActionLiteralSupport = {          codeActionKind = {            valueSet = {},            <metatable> = <table 1>          },          <metatable> = <table 1>        },        dynamicRegistration = false,        <metatable> = <table 1>      },      completion = {        completionItem = {          commitCharactersSupport = false,          deprecatedSupport = false,          documentationFormat = { "markdown", "plaintext" },          preselectSupport = false,          snippetSupport = true,          <metatable> = <table 1>        },        completionItemKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },          <metatable> = <table 1>        },        contextSupport = false,        dynamicRegistration = false,        <metatable> = <table 1>      },      declaration = {        linkSupport = true,        <metatable> = <table 1>      },      definition = {        linkSupport = true,        <metatable> = <table 1>      },      documentHighlight = {        dynamicRegistration = false,        <metatable> = <table 1>      },      documentSymbol = {        dynamicRegistration = false,        hierarchicalDocumentSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      hover = {        contentFormat = { "markdown", "plaintext" },        dynamicRegistration = false,        <metatable> = <table 1>      },      implementation = {        linkSupport = true,        <metatable> = <table 1>      },      references = {        dynamicRegistration = false,        <metatable> = <table 1>      },      signatureHelp = {        dynamicRegistration = false,        signatureInformation = {          documentationFormat = { "markdown", "plaintext" },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      synchronization = {        didSave = true,        dynamicRegistration = false,        willSave = false,        willSaveWaitUntil = false,        <metatable> = <table 1>      },      typeDefinition = {        linkSupport = true,        <metatable> = <table 1>      },      <metatable> = <table 1>    },    workspace = {      applyEdit = true,      configuration = true,      symbol = {        dynamicRegistration = false,        hierarchicalWorkspaceSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      <metatable> = <table 1>    }  },  initializationOptions = vim.empty_dict(),  processId = 2835,  rootPath = "/home/slava/tmp",  rootUri = "file:///home/slava/tmp",  trace = "off"}
[ DEBUG ] 2020-10-18T12:24:03+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:361 ]	"rpc.send.payload"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false,        <metatable> = <1>{          __tostring = <function 1>        }      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = {},              <metatable> = <table 1>            },            <metatable> = <table 1>          },          dynamicRegistration = false,          <metatable> = <table 1>        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = true,            <metatable> = <table 1>          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },            <metatable> = <table 1>          },          contextSupport = false,          dynamicRegistration = false,          <metatable> = <table 1>        },        declaration = {          linkSupport = true,          <metatable> = <table 1>        },        definition = {          linkSupport = true,          <metatable> = <table 1>        },        documentHighlight = {          dynamicRegistration = false,          <metatable> = <table 1>        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false,          <metatable> = <table 1>        },        implementation = {          linkSupport = true,          <metatable> = <table 1>        },        references = {          dynamicRegistration = false,          <metatable> = <table 1>        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            documentationFormat = { "markdown", "plaintext" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false,          <metatable> = <table 1>        },        typeDefinition = {          linkSupport = true,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        <metatable> = <table 1>      }    },    initializationOptions = vim.empty_dict(),    processId = 2835,    rootPath = "/home/slava/tmp",    rootUri = "file:///home/slava/tmp",    trace = "off"  }}
[ ERROR ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]	"rpc"	"pyls"	"stderr"	"2020-10-18 12:24:04,020 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'autopep8': No module named 'pycodestyle'\n"
[ ERROR ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]	"rpc"	"pyls"	"stderr"	"2020-10-18 12:24:04,028 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'pycodestyle': No module named 'pycodestyle'\n"
[ ERROR ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]	"rpc"	"pyls"	"stderr"	"2020-10-18 12:24:04,028 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'pydocstyle': No module named 'pydocstyle'\n"
[ ERROR ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]	"rpc"	"pyls"	"stderr"	"2020-10-18 12:24:04,051 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'rope_completion': No module named 'rope'\n"
[ ERROR ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]	"rpc"	"pyls"	"stderr"	"2020-10-18 12:24:04,051 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'rope_rename': No module named 'rope'\n"
[ DEBUG ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"decoded"	{  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      codeActionProvider = true,      codeLensProvider = {        resolveProvider = false      },      completionProvider = {        resolveProvider = false,        triggerCharacters = { "." }      },      definitionProvider = true,      documentFormattingProvider = true,      documentHighlightProvider = true,      documentRangeFormattingProvider = true,      documentSymbolProvider = true,      executeCommandProvider = {        commands = {}      },      experimental = vim.empty_dict(),      foldingRangeProvider = true,      hoverProvider = true,      referencesProvider = true,      renameProvider = true,      signatureHelpProvider = {        triggerCharacters = { "(", ",", "=" }      },      textDocumentSync = {        change = 2,        openClose = true,        save = {          includeText = true        }      },      workspace = {        workspaceFolders = {          changeNotifications = true,          supported = true        }      }    }  }}
[ DEBUG ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:361 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "initialized",  params = {    [true] = 6  }}
[ DEBUG ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:361 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "workspace/didChangeConfiguration",  params = {    settings = {      plugins = {        autopep8 = {          enabled = false,          <metatable> = <1>{            __tostring = <function 1>          }        },        black = {          enabled = false,          <metatable> = <table 1>        },        flake8 = {          enabled = false,          <metatable> = <table 1>        },        jedi_signature_help = {          enabled = false,          <metatable> = <table 1>        },        mccabe = {          enabled = false,          <metatable> = <table 1>        },        pycodestyle = {          enabled = false,          maxLineLength = 88,          <metatable> = <table 1>        },        pyflakes = {          enabled = false,          <metatable> = <table 1>        },        pylint = {          enabled = true,          <metatable> = <table 1>        },        yapf = {          enabled = false,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      <metatable> = <table 1>    }  }}
[ DEBUG ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:585 ]	"LSP[pyls]"	"server_capabilities"	{  codeActionProvider = true,  codeLensProvider = {    resolveProvider = false  },  completionProvider = {    resolveProvider = false,    triggerCharacters = { "." }  },  definitionProvider = true,  documentFormattingProvider = true,  documentHighlightProvider = true,  documentRangeFormattingProvider = true,  documentSymbolProvider = true,  executeCommandProvider = {    commands = {}  },  experimental = vim.empty_dict(),  foldingRangeProvider = true,  hoverProvider = true,  referencesProvider = true,  renameProvider = true,  signatureHelpProvider = {    triggerCharacters = { "(", ",", "=" }  },  textDocumentSync = {    change = 2,    openClose = true,    save = {      includeText = true    }  },  workspace = {    workspaceFolders = {      changeNotifications = true,      supported = true    }  }}
[ INFO ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:586 ]	"LSP[pyls]"	"initialized"	{  resolved_capabilities = {    call_hierarchy = false,    code_action = true,    declaration = false,    document_formatting = true,    document_highlight = true,    document_range_formatting = true,    document_symbol = true,    find_references = true,    goto_definition = true,    hover = true,    implementation = false,    signature_help = true,    signature_help_trigger_characters = { "(", ",", "=" },    text_document_did_change = 2,    text_document_open_close = true,    text_document_save = {      includeText = true    },    text_document_save_include_text = true,    text_document_will_save = false,    text_document_will_save_wait_until = false,    type_definition = false,    workspace_symbol = false  }}
[ DEBUG ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:361 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocument = {      languageId = "python",      text = "import math\n\nif __name__ == '__main__':\n    print('hello lsp')\n",      uri = "file:///home/slava/tmp/dummy.py",      version = 0    }  }}
[ DEBUG ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        message = "'math' imported but unused",        range = {          end = {            character = 12,            line = 0          },          start = {            character = 0,            line = 0          }        },        severity = 2,        source = "pyflakes"      } },    uri = "file:///home/slava/tmp/dummy.py"  }}
[ DEBUG ] 2020-10-18T12:24:04+0200 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:434 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = { {      message = "'math' imported but unused",      range = {        end = {          character = 12,          line = 0        },        start = {          character = 0,          line = 0        }      },      severity = 2,      source = "pyflakes"    } },  uri = "file:///home/slava/tmp/dummy.py"}

</details>

<details>
<summary>nvim-lsp-config.lua</summary>

```lua

local M = {}

function M.setup_nvim_lsp()
	local nvim_lsp = require'nvim_lsp'

	local on_attach_vim = function()
		require'completion'.on_attach()
		require'diagnostic'.on_attach()
	end

	require'nvim_lsp'.pyls.setup{
	   on_attach=on_attach_vim,
	   settings = {
	      plugins = {
	         autopep8 = {enabled = false},
	         black = {enabled = false},
	         flake8 = {enabled = false},
	         jedi_signature_help = {enabled = false},
	         mccabe = {enabled = false},
	         pycodestyle = {enabled = false, maxLineLength = 96},
	         pyflakes = {enabled = false},
	         yapf = {enabled = false},
	         pylint = {enabled = true}
	      }
	   }
	}

	require'nvim_lsp'.clangd.setup{on_attach=on_attach_vim}
end
return M
```

</details>

### Actual behaviour
pyflakes plugin used for diagnostics (see `lsp.log`)

### Expected behaviour
pylint plugin used for diagnostics

It looks like the pyls is first loaded with some default settings (and I do not know how change them), and then config update is sent. That apparently does not work at least in my case.

**Comment by fsouza** [comment]
Your configuration is incorrect, pyls config starts with the 'pyls' key. The correct one would be:

```lua
require'nvim_lsp'.pyls.setup{
  on_attach=on_attach_vim,
  settings = {
    pyls = {
      plugins = {
        autopep8 = {enabled = false},
        black = {enabled = false},
        flake8 = {enabled = false},
        jedi_signature_help = {enabled = false},
        mccabe = {enabled = false},
        pycodestyle = {enabled = false, maxLineLength = 96},
        pyflakes = {enabled = false},
        yapf = {enabled = false},
        pylint = {enabled = true}
      }
    }
  }
}
```

**Comment by Glavnokoman** [comment]
Ouch! Sorry. And thanks!
