### ISSUE TITLE
Bad indentation when opening a new structure in Python

### ISSUE THREAD

**Issue by facundobatista** [neovim/neovim#13124]
### Versions stuff:

```
$ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compilado por team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

     archivo "vimrc" del sistema: "$VIM/sysinit.vim"
            predefinido para $VIM: "/usr/share/nvim"

Run :checkhealth for more info

$ uname -a
Linux blackfx 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

$ konsole --version
konsole 19.12.3

$ echo $TERM
xterm-256color
```

### Steps to reproduce

- Open the file with `nvim -u NORC foo.py` (**note** it's important to open a `.py` file, as without it no indentation happens when hitting ENTER)
- Type `foo = {` and hit ENTER.

### Actual behaviour

A new line is created and the cursor is left at column 9, which are TWO indentation steps to the right.

### Expected behaviour

A new line must be created and the cursor should be left at column 5 (ONE indentation step to the right).

**Note**: spaces are inserted, not tabs, and the indentation step is set to 4 spaces just fine (as I can see hitting the Tab Key or even Backspace, which removes all spaces to the previous indentation step).

**Comment by erw7** [comment]
Is this behavior really a bug?  ["2.1.6. Implicit line joining"](https://docs.python.org/3/reference/lexical_analysis.html#implicit-line-joining
) in "The Python Language Reference" says the following

> The indentation of the continuation lines is not important.

Thus it appears to me to be simply a matter of taste. If you're really convinced that this is a bug, why don't you report it to the [vim issue tracker](https://github.com/vim/vim/issues), since the maintainer for `runtime/indent/python.vim` is Bram@vim.org.

**Comment by facundobatista** [comment]
Thanks!
