### ISSUE TITLE
[feature request] Way to change the color of command-line

### ISSUE THREAD

**Issue by acomagu** [neovim/neovim#13136]
- `nvim --version`: NVIM v0.5.0-660-g2cea6ab01
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: Manjaro Linux(Linux acm-manjaro 4.19.147-1-MANJARO #1 SMP Wed Sep 23 18:00:56 UTC 2020 x86_64 GNU/Linux)
- Terminal name/version: konsole 20.08.1
- `$TERM`: xterm-256color

If I disable the status line, it's really hard to distinguish the command line from the buffer area. I want to change the color of characters in command line.

### Actual behaviour

No way to change the color(highlight) of the characters only in the command line.

### Expected behaviour

I can change the color of the characters in command line to something different from one in the buffer area.

**Comment by subnut** [comment]
Is `echohl` not enough?

**Comment by acomagu** [comment]
@subnut First, it'll be disabled if any plugin executes `:echohl None`. I don't know how many plugins does it but nvim document says "Don't forget to set the group back to None" so it's normal behavior of plugins.

Second, not all messages in command line are produced by `echo`. We can type there directly, or `:lua print("hoge")` also not affected by `echohl`.

**Comment by bfredl** [comment]
`:help hl-MsgArea`
