### ISSUE TITLE
Home and end key is not working in centos 7

### ISSUE THREAD

**Issue by SamPosh** [neovim/neovim#13134]
- `nvim --version`: NVIM v0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently? Yes ,in Vim 7.4 in the same machine ,it works fine
- Operating system/version: 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"

- Terminal name/version:
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`
Open a file
go to insert mode
press home and end. It should move to first and last char in a line but it doesn't 
even in normal mode Home and end is not working 
but $ and ^ is working in normal mode
```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
In this environment also Home and end button is not working
```

### Actual behaviour
Home key is not movig to first letter
End key is not moving to last letter
### Expected behaviour
Home key should move to first letter
End key must move to last letter

**Comment by erw7** [comment]
> - Terminal name/version:

What terminal are you using?

**Comment by SamPosh** [comment]
I executed echo $TERM  it showed me xterm . Is that you are asking? (I am connecting my linux machine via mputty)

**Comment by erw7** [comment]
> I executed echo $TERM it showed me xterm.

It is the value set in the `TERM` environment variable. What I wanted to know was the terminal emulator (xterm, alacritty, Windows Terminal, PuTTY etc...) you are using.

> I am connecting my linux machine via mputty

Thus, what I wanted to know was this information. Is mputty the wrong word for [MTPUTTY](https://ttyplus.com/multi-tabbed-putty/)? If so, set `TERM` to `putty-256color` or change `Terminal > Keyboard > The Function keys and keypad` to `Xterm R6` (I don't know if MTPUTTY has that setting), then the `Home` and `End` keys should work. Anyway, `TERM` environment variables need to be set to suit the terminal emulator.

**Comment by SamPosh** [comment]
Yes it is MTPutty . I changed the settings to xTermR6 ,but still fails

**Comment by SamPosh** [comment]
![image](https://user-images.githubusercontent.com/21053120/96853680-461f0080-1478-11eb-9e6c-a95b5421f6c9.png)

**Comment by SamPosh** [comment]
Thank you @erw7 i did export TERM=putty-256color and now it is working fine

**Comment by SamPosh** [comment]
I am trying to set this in vimrc as 'set term=putty-256color' but that fails. should i run export TERM=putty-256color every time?

**Comment by erw7** [comment]
Sorry. I didn't look closely at the PuTTY configuration. The `Home` and `End` keys have settings that are separate from the function keys and can only be set to `Standard` and `rxvt`. Therefore, you're likely to have no choice but to use `TERM=putty-256color`.

> I am trying to set this in vimrc as 'set term=putty-256color' but that fails. should i run export TERM=putty-256color every time?

I think you should set `Connection > Data > Terminal details > Terminal-type string` of MTPuTTY to `putty-256color`  before connecting. If the MTPuTTY doesn't have this setting, you can only set it in a shell configuration file (`.bashrc`, `.zshrc` etc) with environment variables such as `SSH_CLIENT`.
