### ISSUE TITLE
macos package missing in nightly release

### ISSUE THREAD

**Issue by twnaing** [neovim/neovim#13133]
As of 2020/10/22 1:48 MMT, [release](https://github.com/neovim/neovim/releases) page is missing macos package for NVIM 0.5.0 nightly pre-release.

**Comment by clason** [comment]
This happens every once in a while (#13021 , #13022 )

**Comment by twnaing** [comment]
[comment](https://github.com/neovim/neovim/issues/13021#issuecomment-702088893) from #13021 

> The nightly binaries are updated every day, and sometimes there are flakiness issues. Just wait a day for it to get updated.
