### ISSUE TITLE
Wrong interactive search terminator used

### ISSUE THREAD

**Issue by phmarek** [neovim/neovim#13141]
- `nvim --version`: v0.5.0-765-g75996a2cd
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: Debian amd64
- Terminal name/version: tmux, xterm
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC /etc/services
:set hlsearch incsearch
:%s,23/..
```

Don't press Enter, just look at the highlightning - the slash and two more characters should be marked up, but are not.

It's not always reproducible - sometimes it changes just by doing
```
:set verbose=255 verbosefile=/tmp/sagag
:set verbose=0
```
(yes, right after one another), so I guess at some uninitialized variable or so.

If I don't have a `/` in the search pattern it seems to work fine.

### Actual behaviour

The match is only highlighted up to the `/`

### Expected behaviour

The match is highlighted up to the `/` and beyond

**Comment by KillTheMule** [comment]
I've found this to be 100% reproducible, it wouldn't even work after doing several tries of those `:set verbose` shennigans. Note that this seems to work properly when using `:set inccomand=nosplit`.

**Comment by Stasen19** [comment]
I've found that this bug is present not only in the `:substitute` command but with the highlighting in all substitute related commands, `:smagic` and `:snomagic`, as well as `:vglobal`.

**Comment by janlazo** [comment]
Maybe https://github.com/vim/vim/commit/c036e87bd7001238ab7cc5d9e30e59bbf989a5fd fixes the issue.

**Comment by glacambre** [comment]
Can't reproduce on master :tada: .

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/pull/14286
