### ISSUE TITLE
Converting between winnr (VimL) and nvim_open_win (Nvim API)? 

### ISSUE THREAD

**Issue by raweggdrinker** [neovim/neovim#13147]
I've embedded nvim in my application using MessagePack-RPC.

When I call `nvim_open_win`, I'm saving the returned window handle. Later on, I'm using VimL (an autocmd in my init.vim) to send a request (with `rpcrequest`) to my application. In it, I send the window id (returned by `winnr`) so the application can know which window is sending it.

The problem is, `nvim_open_win` and `winnr` return different numbers. Is there a way to convert between the two? 

Random note, I noticed that, maybe by coincidence, the window handle is always the window number + 1000. Is this a documented pattern/something I can rely on?

**Comment by raweggdrinker** [comment]
I solved this for now by using the buffer number instead of the window number, but still would be nice to know the answer to this.

**Comment by erw7** [comment]
This is the place to track issues and request features. Please don't post your questions here. For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. Thanks.

I don't think it's explicitly stated anywhere, but the api's `Window handle` is the same as the `window-ID (winid, windowid)`. This is evident from the following sources. You should be able to use `win_getid()` and `win_id2tabwin()` for these conversions.

https://github.com/neovim/neovim/blob/932585fd91dbb165670add42e5537b6dec7f1f86/src/nvim/eval/funcs.c#L11042-L11045

https://github.com/neovim/neovim/blob/932585fd91dbb165670add42e5537b6dec7f1f86/src/nvim/window.c#L6879-L6883

https://github.com/neovim/neovim/blob/932585fd91dbb165670add42e5537b6dec7f1f86/src/nvim/api/vim.c#L1017-L1021
