### ISSUE TITLE
Can't properly run code / Can't open a command line from neovim (Windows 7)

### ISSUE THREAD

**Issue by loltex** [neovim/neovim#13144]
When i'm running code from neovim it's compiling and running it without openning a command line (runs at the line that is at the bottom of the screen, where your pressed keys in normal mode are showing) and all of my programs where i need to input something are running for a moment and then instantly close. I tried to do the same in GVim and it's working well, it opens a command line and i can input something if needed (Same as in William Lin's videos). Can i somehow do the same (open a command line) from neovim?

**Comment by KillTheMule** [comment]
In neovim, you use the terminal for that. Either the command directly (e.g. `:term scp user@server:/file ~`), or you just open the terminal via `:term` and then put your command inside that.

**Comment by janlazo** [comment]
Duplicate of https://github.com/neovim/neovim/issues/1496
