### ISSUE TITLE
Incsearch: jumping while searching completes wrong word

### ISSUE THREAD

**Issue by phmarek** [neovim/neovim#13140]
- `nvim --version`: v0.5.0-765-g75996a2cd
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: Debian amd64
- Terminal name/version: xterm, tmux
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC /etc/services
:set incsearch hlsearch inccommand=nosplit<cr>
?21/<C-T><C-R><C-W>
```

After jumping around among matches via Ctrl-T and/or Ctrl-G, word insertion via Ctrl-R_Ctrl-W doesn't work correctly anymore.

### Actual behaviour

_Some_ word gets inserted, in my case eg. `Note` (first word on third line in file, comment section)

### Expected behaviour

_Current_ term gets completed (I'd expect `21/tcp` or some similar service)

**Comment by justinmk** [comment]
Seems to be fixed on b7084fef4c85
