### ISSUE TITLE
[CWE-690]

### ISSUE THREAD

**Issue by fiplox** [neovim/neovim#13158]
Hello everyone :smiley: Tried to compile neovim with gcc10 and flag `-fanalyzer` and found some [CWE-690]  NULL dereference. Here's a log, but I recommend trying to compile with `-fanalyzer` to see more. :smile: 
[log.txt](https://github.com/neovim/neovim/files/5435319/logg.txt)

**Comment by janlazo** [comment]
Some are false positives. It ignores function attributes, specifically `__attribute__((nonnull))`.
