### ISSUE TITLE
Healthcheck Python provider error

### ISSUE THREAD

**Issue by axelcorrea** [neovim/neovim#13168]
## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for           diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help provider-python
          /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help provider-python
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.8.0
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

**Comment by erw7** [comment]
The Python 2 provider is optional, as described there. Therefore, if you don't need it, you can ignore it.
