### ISSUE TITLE
Solar2d/Corona Labs

### ISSUE THREAD

**Issue by MyxAzm** [neovim/neovim#13179]
Пытаюсь создать apk файл, но не создается, раньше нормально создавалось, не знаю почему.
Для Windows без проблем создает. Помогите пожалуйста

Google translate: I try to create an apk file, but it is not created, it was created normally before, I don't know why.
For Windows, it creates without problems. Help please

**Comment by glacambre** [comment]
Are you sure you opened this issue is the right repository? This doesn't look related to neovim at all.

**Comment by clason** [comment]
Maybe they are trying to cross-build neovim for Android? 

In any case, more information is needed, and since there's not been any for two weeks, I'll close for now -- feel free to add more info and reopen!
