### ISSUE TITLE
Segfault on folding a single line which folds over into multiple lines 

### ISSUE THREAD

**Issue by ArbitRandomUser** [neovim/neovim#13171]
- `nvim --version`: NVIM v0.5.0-715-gc5ceefca7

- `vim -u DEFAULTS` (version: ) behaves differently?  Yes doesnt segfault
- Operating system/version: Description:	Ubuntu 18.04.5 LTS
- Terminal name/version: GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`
Open nvim in the terminal , type a single vim line which goes into multiple lines in the terminal add other lines  , visuall select the lines and try to fold with z-f .

### Actual behaviour 
Neovim segfaults

### Expected behaviour neovim 
Should continue working

**Comment by erw7** [comment]
Please try it with the latest master. The fold is broken in the master from v0.5.0-711-gf1fbb9e9c to v0.5.0-726-ga9851bfbb.

Ref #12988.

**Comment by ArbitRandomUser** [comment]
sorry for the noise ! ill close this issue
