### ISSUE TITLE
Nightly is missing `macos` builds

### ISSUE THREAD

**Issue by kdheepak** [neovim/neovim#13176]
Nightly is currently missing `macos` builds

<img width="1000" alt="Screen Shot 2020-10-28 at 1 45 17 AM" src="https://user-images.githubusercontent.com/1813121/97406696-3e6bbb80-18bf-11eb-9cfc-4fd60faaaf3c.png">

I'm not sure why though, I see that the CI on travis is passing fine.

**Comment by clason** [comment]
Duplicate of the (pinned) issue #13146

**Comment by kdheepak** [comment]
My bad, I even scanned for previous issues but missed that one.
