### ISSUE TITLE
:syntax region conflicts with conceal

### ISSUE THREAD

**Issue by champignoom** [neovim/neovim#13184]
- `nvim --version`: v0.4.4
- `vim -u DEFAULTS` (version: 8.2) behaves differently? No.
- Operating system/version: Manjaro 20.1.2
- Terminal name/version: xfce4-terminal 0.8.9.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

1. switch to insert mode, type `xxx yyy`, followed by a newline
2. `:set conceallevel=1`
3. `:syntax match X /x\+/ conceal cchar=X` now the xxx should be visually replaced by X
4. `:syntax region XY start=/xxx/ end=/yyy/` the X expands back to xxx

### Actual behaviour
The `X` expands back to `xxx` in the last step.

### Expected behaviour
It should not.

**Comment by erw7** [comment]
`:h :syn-define` says the following. Therefore, I believe this is not a bug, but an expected behavior.

> In case more than one item matches at the same position, the one that was defined LAST wins.  Thus you can override previously defined syntax items by using an item that matches the same text.  But a keyword always goes before a match or region.  And a keyword with matching case always goes before a keyword with ignoring case.

**Comment by champignoom** [comment]
Indeed. Thanks.
