### ISSUE TITLE
opening typescript.tsx file format first makes types show up red

### ISSUE THREAD

**Issue by unphased** [neovim/neovim#13185]
![image](https://user-images.githubusercontent.com/1542910/97512353-b38ecd80-195f-11eb-8001-2c09dfd6ffa8.png)

- `nvim --version`: NVIM v0.5.0-782-gb6897ebc0
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: Linux  4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Terminal name/version: alacritty 
- `$TERM`: tmux-256color-italic

If a non-typescript.tsx filetype file is initially opened, this does not happen.

**Comment by unphased** [comment]
I'm testing these nighly builds because the last nightly build I used the past week has been segfaulting for me, and this started getting really old. The instability as of late in neovim is getting old... Is there a branch? Can someone provide me a heuristic I can use to work something out? I'm thinking about going back to daily driving vim instead of neovim at this point.

**Comment by jdhao** [comment]
@unphased can you reproduce with `nvim -u NORC test.tsx`? If not, this is not a problem with Neovim. Maybe some of your plugins are changing the syntax highlight. You are wasting other people's time by not checking it yourself first.

**Comment by unphased** [comment]
You are right and I do feel bad, just like I should. But for the moment I've switched to vim so I can continue to get work done, and will investigate further later.

**Comment by theHamsta** [comment]
@unphased of course there's a stable branch of the 0.4.X releases.

**Comment by Teyras** [comment]
I had this exact problem with neovim nightly and the leafgarland/typescript-vim plugin.

**Comment by unphased** [comment]
> I had this exact problem with neovim nightly and the leafgarland/typescript-vim plugin. Using the stable branch solved it.

no doubt what i'm seeing. I also noticed that my setup renders more highlight colors under vim. Since i've successfully maintained vim compatibility in my setup i'm just driving vim for now. (and i think i was going bleeding edge nvim for only the native LSP stuff which I am not pursuing now i can probably use stable nvim too)

Thanks

**Comment by janlazo** [comment]
If https://github.com/neovim/neovim/issues/13185 doesn't solve the issue, then it's likely a user config issue.
