### ISSUE TITLE
Spurious / when trying to load /etc/xdg//nvim/sysinit.vim

### ISSUE THREAD

**Issue by shepard8** [neovim/neovim#13187]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? yes won't show anything.
- Operating system/version: Linux mflg-server 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Terminal name/version: XTerm(330)
- `$TERM`: xterm

### Steps to reproduce using `nvim`

Note that this is a fresh neovim install on my system and I have not configured any shell variable.
```
nvim -V | grep sysinit.vim
```

### Actual behaviour
```
$ vim -V | grep sysinit.vim
could not source "/etc/xdg//nvim/sysinit.vim"
could not source "$VIM/sysinit.vim"
```

### Expected behaviour
This double slash should be a single slash.

**Comment by glacambre** [comment]
I can't reproduce this on nightly/master. @shepard8 if you're still able to reproduce this on master/nightly, could you tell us what `:echo $XDG_CONFIG_DIRS` and `:echo $VIM` print?

**Comment by freshsun** [comment]
> `:echo $XDG_CONFIG_DIRS`

i can still reproduce this error on the latest nightly release
$XDG_CONFIG_DIRS is null
$VIM is /root/squashfs-root/usr/share/nvim (I test it in a container)
