### ISSUE TITLE
Fallback behavior of clipboard provider doesn't work as documented

### ISSUE THREAD

**Issue by necabo** [neovim/neovim#13189]
- `nvim --version`:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Operating system/version: Arch Linux 5.9.1-arch1-1
- Terminal name/version: alacritty 0.5.0 (a6681e3a)
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Have "wl-clipboard" and "xsel" installed. 

```
nvim -u NORC +echo\ "provider#clipboard#Executable()"
WAYLAND_DISPLAY= nvim -u NORC +echo\ "provider#clipboard#Executable()"
```

### Actual behaviour
Both lines echo "wl-copy".

### Expected behaviour
The first line should echo "wl-copy", the second line should echo "xsel" (interchangable with "xclip") according to this excerpt from `:h clipboard`:

  - g:clipboard
  - pbcopy, pbpaste (macOS)
  - wl-copy, wl-paste (if $WAYLAND_DISPLAY is set)
  - xclip (if $DISPLAY is set)
  - xsel (if $DISPLAY is set)

**Comment by AIGeneratedUsername** [comment]
> if $DISPLAY is set

If set to... what? This is a confusing and useless hint. What the value must be for the `$DISPLAY`?

**Comment by dundargoc** [comment]
I interpret it as "if $DISPLAY variable isn't empty"
