### ISSUE TITLE
nvim + `set tgc` + `highlight Comment cterm=italic` doesn't work, but it works in vanilla vim

### ISSUE THREAD

**Issue by jsatk** [neovim/neovim#13188]
- `nvim --version`: `0.4.4.`
- `vim -u DEFAULTS` (version: 8.2) behaves differently? No.
- Operating system/version: macOS Catalina 10.15.7
- Terminal name/version: iTerm 3.3.12
- `$TERM`: `xterm-256color-italics`

The best way to explain this is with screenshots. Please read the comment in the screenshot.

<img width="788" alt="Screen Shot 2020-10-29 at 10 30 29 AM" src="https://user-images.githubusercontent.com/1005550/97610475-28025480-19d2-11eb-94ae-6d8f7b80889b.png">
<img width="788" alt="Screen Shot 2020-10-29 at 10 30 45 AM" src="https://user-images.githubusercontent.com/1005550/97610483-2a64ae80-19d2-11eb-99bb-bbf662d689b7.png">
<img width="788" alt="Screen Shot 2020-10-29 at 10 31 09 AM" src="https://user-images.githubusercontent.com/1005550/97610485-2b95db80-19d2-11eb-98ad-0a6a418166e0.png">
<img width="788" alt="Screen Shot 2020-10-29 at 10 31 18 AM" src="https://user-images.githubusercontent.com/1005550/97610487-2c2e7200-19d2-11eb-9981-3a78110afc92.png">

This was thoroughly discussed in https://github.com/neovim/neovim/issues/3461, but the resolution for most seemed to be simply set your `$TERM` to one that supports italics. I've read many [blog posts](https://thekennethlove.com/2017/10/my-quest-for-italic-comments-in-vim/) about this and even [written my own](https://jsatk.us/posts/a-descent-into-madness-with-vim-tmux-and-italics/) in the past. However most of these apply to regular vim. As soon as I turn on `set termguicolors` italics go away in comments in nvim but not vim.

**Comment by bfredl** [comment]
Hmm shouldn't `gui=italics` be used for 'termguicolors' ? what is the logic vim uses? In particular, how does it distinguish _unset_ `gui=` from _empty_ `gui=` ? And has the recent stream of `:highlight` patches changed the behavior (from the last month or two).

**Comment by clason** [comment]
To reiterate @bfredl's comment, this is working as intended -- the differences between neovim and vim are by design and actually explained in the help:

* neovim master:
```
'termguicolors' 'tgc'   boolean (default off)
                        global
        Enables 24-bit RGB color in the TUI.  Uses "gui" :highlight
        attributes instead of "cterm" attributes. highlight-guifg
        Requires an ISO-8613-3 compatible terminal.
```

* vim 8.2.1900:
```
'termguicolors' 'tgc'   boolean (default off)
                        global
                        {not available when compiled without the
                        |+termguicolors| feature}
        When on, uses |highlight-guifg| and |highlight-guibg| attributes in
        the terminal (thus using 24-bit color).

        Requires a ISO-8613-3 compatible terminal.  If setting this option
        does not work (produces a colorless UI) reading |xterm-true-color|
        might help.

        For Win32 console, Windows 10 version 1703 (Creators Update) or later
        is required. Use this check to find out:
                if has('vcon')
        This requires Vim to be built with the |+vtp| feature.

        Note that the "cterm" attributes are still used, not the "gui" ones.
        NOTE: This option is reset when 'compatible' is set.
```

And indeed, `highlight Comment gui=italic` works fine for me in latest iTerm2 with nvim master.

**Comment by jsatk** [comment]
`highlight Comment gui=italic` is exactly what I was looking for. I didn't realize `termguicolors` was different between vim & nvim.
