### ISSUE TITLE
nvim_call_atomic not available via Lua on nvim 0.4.3 or 0.4.4

### ISSUE THREAD

**Issue by chipsenkbeil** [neovim/neovim#13191]
- `nvim --version`: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/includeCompiled by builduser
Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: ArchLinux w/ kernel 5.7.12-arch1-1
- Terminal name/version: Blink Shell v13.5.7.224
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC +'lua vim.api.nvim_call_atomic({{"nvim_get_var", {"fish"}}, {"nvim_del_var", {"fish"}}})'
```

### Actual behaviour

Function is missing from API despite being listed in `api.txt`.

```
E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1: attempt to call field 'nvim_call_atomic' (a nil value)
```

Was also mentioned [here](https://github.com/neovim/neovim/issues/12369#issuecomment-633819223).

### Expected behaviour

Function is accessible. In the above case, we'd return a two-element array with errors not being nil.

**Comment by erw7** [comment]
The `FUNC_API_REMOTE_ONLY` attribute is set to `nvim_call_atomic()` as shown below. Therefore, it will not be exported to `vim.api`.

https://github.com/neovim/neovim/blob/90f3a8ba291fb0583ab6b0bd33129fdd45df1dab/src/nvim/func_attr.h#L212-L213

https://github.com/neovim/neovim/blob/90f3a8ba291fb0583ab6b0bd33129fdd45df1dab/src/nvim/api/vim.c#L1887-L1888

The built in lua execution should always be atomic, so there is no need for `nvim_call_atomic()`. The `api.txt` does not indicate whether it is "REMOTE ONLY" or not, so you will need to look at the source code. I think the `api.txt` needs to be improved.

**Comment by chipsenkbeil** [comment]
I didn't know where to look, so this is good to know. Agree that having some mention of what is remote only, etc. in the doc would also be helpful. :)

**Comment by lewis6991** [comment]
`nvim_call_atomic` is now documented with:

```
                Attributes: ~
                    |RPC| only
```
