### ISSUE TITLE
Use System Dictionary

### ISSUE THREAD

**Issue by LandonSchropp** [neovim/neovim#13195]
It would be great if Neovim could use the system dictionary. On macOS, this would be located at `~/Library/Spelling/LocalDictionary`.

I can imagine a few variants of this:

* Neovim includes the words in the system dictionary, but also maintains its own spelling file for word additions.
* Neovim appends words directly to the system dictionary.

**Comment by teto** [comment]
duplicate of https://github.com/neovim/neovim/issues/12064 ?

**Comment by LandonSchropp** [comment]
@teto Thanks for the reply!

To answer your question, I'm not sure. Would using Nuspell or an external spell checker have the consequence of using the system spell checker? Is that ticket orthogonal in that it doesn't specify that the current spelling file should be replaced?

**Comment by teto** [comment]
It could but you may need to give up on (neo)vim spell features or find some tricks depending on what features you want. I don't have experience in this area so it's the only help I can offer sry

**Comment by mcepl** [comment]
This is definitively duplicate of https://github.com/neovim/neovim/issues/12064 … the general idea of that issue is that there would be several plugins for whatever is the system spellchecker (generally hunspell on Linux, and system spellcheckers on Mac and Windows).

**Comment by LandonSchropp** [comment]
@mcepl Okay, I'll close this then. Thanks.
