### ISSUE TITLE
Support for Elm syntax

### ISSUE THREAD

**Issue by pehota** [neovim/neovim#13193]
It looks like Elm syntax support is still missing in neovim.

There is a patch for the file type detection that has already been applied (https://github.com/neovim/neovim/pull/12403) but the syntax, ftplugin and indent files are missing. I couldn't find a Vim patch for the runtime changes.

I would like to see the same Elm support in neovim but I am not sure how to proceed.
Should I just port the changes over?
Or create a patch for the runtime commit (although there are a lot of unrelated changes in that commit)?

### PR
[vim/vim#6157](https://github.com/vim/vim/pull/6157)

### Runtime changes
[vim/vim@acc2240#diff-6189986fbc5a8d68cbeb136221f76964ef0b68a961a5d3c4202482aada9b83fe](https://github.com/vim/vim/commit/acc224064033e5cea21ef7f1eefb356ca06ff11d#diff-6189986fbc5a8d68cbeb136221f76964ef0b68a961a5d3c4202482aada9b83fe)

**Comment by willelz** [comment]
see #12497

**Comment by pehota** [comment]
Hi @willelz ,
I am sorry but I am missing to see what #12497 has to do with this issue.
