### ISSUE TITLE
Support for completionItem/resolve requests

### ISSUE THREAD

**Issue by mhartington** [neovim/neovim#13199]
- `nvim --version`: NVIM v0.5.0-787-g98024853f

<details>

```
NVIM v0.5.0-787-g98024853f
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wal
l -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fs
tack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_
HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/Users/mhartington/Github/neovim-org/neovim/build/config -I/Users/mhartington/Github/neovim-org/neovim/src -I/Users
/mhartington/Github/neovim-org/neovim/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX
10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/mhartington/Github/neovim-org/neovim/build/src/nvim/auto -I/Users/mhartington/Github
/neovim-org/neovim/build/include
Compiled by mhartington@Michaels-MBP.fios-router.home

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/mhartington/bin/nvim/share/nvim"

Run :checkhealth for more info
```

</details>

- language server name/version: n/a
- Operating system/version: macOS 10.15

<details>
<summary>nvim -c ":checkhealth nvim nvim_lsp"</summary>

```
health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: html: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: pyls_ms: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: vuels: configuration checked.
  - INFO: jsonls: configuration checked.


```

</details>

Not so much a bug, but a feature request for LSP. When completion is done, LSP can provide additional context about a completion item (either on selection change or completion "done") and provide things like docs or additional text edits.

Right now nothing is setup here to call `completionItem/resolve` in neovim itself. Other options are to have users provide their own customized callback function, which could be fine. Just wanted to raise the topic in case others were interested.

PR in LanguageClient: https://github.com/autozimu/LanguageClient-neovim/pull/1043
Implementation in vim-lsp: https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/ui/vim/completion.vim#L63

Spec for completion: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion

**Comment by mfussenegger** [comment]
Done with https://github.com/neovim/neovim/pull/27339/
