### ISSUE TITLE
Executing sxhkd within nvim crashes nvim in new instances of st

### ISSUE THREAD

**Issue by shahzebs** [neovim/neovim#13198]
- `nvim --version`: 0.4.4
- Operating system/version: Arch Linux 5.9.2
- Terminal name/version: st 0.8.2
- `$TERM`: st-256color
- `sxhkd -v`: 0.6.2

### Actual behaviour
If sxhkd is not already running, executing `:!sxhkd &` from within nvim causes st to crash when trying to run `nvim` in a **new** st window if that window was opened using a sxhkd key bind. If I open the st window using a launcher like dmenu or from an existing terminal, executing `nvim` in that new window works just fine. 

This issue only appears if I execute sxhkd from within nvim (vim works fine) and with my terminal emulator st. So the issue seems to mostly be related to st, then sxhkd and lastly nvim. All three are relevant because only st crashes (kitty works fine), a crash only occurs when opening st using a sxhkd key bind and nvim seems to be the only program inducing the crash.

If nvim is causing st to crash and I run `vim` (v8.2), from any terminal (tested both st and kitty) opened with sxhkd, it gives me this error:
```
Error detected while processing /usr/share/nvim/runtime/plugin/rplugin.vim[65]..function <SNR>27_LoadRemotePlugins[1]..<SNR>27_GetManifest[1]..<SNR>27_GetManifestPath:
line    7:
E117: Unknown function: stdpath
```
and opens fine. The error does not appear normally.
I haven't found any other program that does this. It doesn't seem to matter which vimrc I use. Even a new, empty one causes this. So does `nvim -u NONE`.
The only way to fix this is to kill the sxhkd process started from nvim and create a new process from a terminal. 

### Expected behaviour
After running `:!sxhkd &` in nvim, I expect nvim to work fine in all terminal windows with no crash.

**Comment by janlazo** [comment]
Vim does not have `stdpath` so that error is unrelated. Update the issue title and create a mini init.vim to demonstrate the issue.

I cannot reproduce the bug using the nvim 0.4.4. appimage based on your description.

```sh
./nvim-0.4.4 -u NONE -c '!sxhkd &' -c 'terminal ./nvim-0.4.4'
```

I don't see the parent nvim crashing when the child nvim runs or when the child nvim exits.

**Comment by shahzebs** [comment]
I have updated the issue but did not add a mini init.vim as it does not seem to matter what it is. I created an empty test_init.vim and tested it with `nvim -u test_init.vim` and the problem still appeared. To be specific; if sxhkd is not already running (important detail), when I run `:!sxhkd &` within nvim and open a new terminal window, any execution of nvim in a new terminal window crashes (so does the terminal window itself). 

As for your attempt to recreate the issue; when I run `:terminal nvim` from within vim, not nvim, nvim opens fine.

**Comment by shahzebs** [comment]
Update: This seems to be related to my terminal emulator st. When my system is in the "crashing state", kitty is able to open nvim fine while st is not. Any ideas why that is?

Moreover, the error message produced by vim does not appear in kitty. However, the error must be related to the error somehow, no?

**Comment by erw7** [comment]
@shahzebs Would your problem be if you performed the following steps?

```
nvim -u NORC
:!st &
" With a newly executed st
nvim -u NORC
```

In my environment, regardless of `sxhkd`, `nvim -u NORC` on a st run with `:!st &` will cause st to exit. The workaround seems to be to redirect `stderr` to `/dev/null` or use `jobstart()`.

```vim
:st 2>& /dev/null &
" or
:call jobstart('st')
```

**Comment by shahzebs** [comment]
You're right. My st exits if I perform your steps. I think I will use `jobstart()` for tasks such as this from now on. It seems like that is the better way to do things if the command writes to `stdout` or `stderr`: 

> Backgrounded ("&") commands must not write to stdout or stderr, the streams are closed immediately. 
Use `jobstart()` instead.

from `:h :!`.

Thank you for your help.
