### ISSUE TITLE
Lua highlight broken and seemingly not maintained

### ISSUE THREAD

**Issue by champignoom** [neovim/neovim#13206]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: 8.2) behaves differently? No
- Operating system/version: Manjaro 20.1.2
- Terminal name/version: xfce4-terminal 0.8.9.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```
1. type 'i--[[<Enter><Esc>'
2. type '1000ia<Enter><Esc>'

### Actual behaviour
The last lines are not rendered as comments.

### Expected behaviour
They should be.

[The syntax file](https://github.com/neovim/neovim/blob/master/runtime/syntax/lua.vim#L5) has not been changed since 8 years ago. I would suggest to switch to an actively maintained plugin which isn't broken in trivial cases.

**Comment by bfredl** [comment]
It is planned for 0.5 (tree-sitter highlights)

**Comment by champignoom** [comment]
Good to know. Thanks.
