### ISSUE TITLE
Rust syntax highlighting crate wrong

### ISSUE THREAD

**Issue by g-w1** [neovim/neovim#13202]
- `nvim --version`: 
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently? NO. it is the same.
- Operating system/version: arch linux latest
- Terminal name/version: alacritty 0.5.0
- `$TERM`: xterm-256-color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC with any file that includes crate::macro!
```

### Actual behaviour

crate is marked as wrong, even though it is correct rust syntax. ![](https://i.imgur.com/owaF3aE.png)

### Expected behaviour

`crate::macro!` should not be highlighted in red since it is correct syntax.

**Comment by erw7** [comment]
It seems to have been fixed in the `syntax/rust.vim` published in [rust-lang/rust.vim](https://github.com/rust-lang/rust.vim).

The `runtime/syntax/README.txt` contains the following

> If you are the maintainer of a syntax file and make improvements, send the new version to Bram@vim.org.

So if you want the syntax file included with neovim to be fixed as well, you'll need to ask the upstream maintainer to send it to Bram@vim.org. Eventually the changes in vim will be merged into neovim.

**Comment by mhinz** [comment]
This is nothing we can or should act on. Vim needs to merge this first, then we can port their runtime patch.

(I do agree that Rust is an important language nowadays, but was never a fan of `rust-lang/rust.vim`. It always was moving quite slowly, which is also the reason why I stopped contributing to it, too. They should move that repo to an org controlled by the community.)

So, maybe ping them again, then create an issue for Vim (ping @chrisbra). Until then, `rust-lang/rust.vim` needs to be installed as a plugin.
