### ISSUE TITLE
`brew install neovim --HEAD` does not compile on MacOS

### ISSUE THREAD

**Issue by Woolworths** [neovim/neovim#13216]
`brew install neovim --HEAD` does not compile on MacOS after the recent commits.

- `nvim --version`: N/A
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: MacOS Catalina 10.15.7 
- Terminal name/version: alacritty 0.5.0 (a6681e3)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
brew uninstall neovim
brew unlink neovim
brew cleanup
brew install neovim --HEAD
```

### Actual behaviour

> USER@USER-MacBook-Pro ~ % brew install neovim --HEAD
> Updating Homebrew...
> ==> Downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz
> Already downloaded: /Users/USER/Library/Caches/Homebrew/downloads/4b91349796a66e38e93acd77e6ca14212c869090429fd88271def2be5293d83f--libmpack-lua-1.0.8.tar.gz
> ==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.2-1.src.rock
> Already downloaded: /Users/USER/Library/Caches/Homebrew/downloads/0bc17975f0cf3981083172aa7da329b874e5780fa81494f5dd07d0665fcec23b--lpeg-1.0.2-1.src.rock
> ==> Downloading https://luarocks.org/manifests/kikito/inspect-3.1.1-0.src.rock
> Already downloaded: /Users/USER/Library/Caches/Homebrew/downloads/ecc1fa84ce4c83c9406f6d1202d4a88c80ede4a0a2bfd8d8d2bd54fd042226bb--inspect-3.1.1-0.src.rock
> ==> Downloading https://github.com/keplerproject/lua-compat-5.3/archive/v0.7.tar.gz
> Already downloaded: /Users/USER/Library/Caches/Homebrew/downloads/5f4e552e95b9a6223a5e4fabb7f04bf4b886057024507c76b1d5b803218c9363--lua-compat-5.3-0.7.tar.gz
> ==> Downloading https://github.com/luvit/luv/releases/download/1.30.0-0/luv-1.30.0-0.tar.gz
> Already downloaded: /Users/USER/Library/Caches/Homebrew/downloads/a9ce5a949370965d8f0fe70a47e7d102a3b4b6b831dbd4d088a83bbe1c00a3a2--luv-1.30.0-0.tar.gz
> ==> Cloning https://github.com/neovim/neovim.git
> Updating /Users/USER/Library/Caches/Homebrew/neovim--git
> ==> Checking out branch master
> Already on 'master'
> Your branch is up to date with 'origin/master'.
> HEAD is now at 805b9a2e7 Merge pull request #13212 from lucc/patch-2
> ==> luarocks make --lua-dir=/usr/local/opt/luajit --tree=/private/tmp/neovim-20201104-11684-1m3kzz/deps-build
> ==> luarocks make --lua-dir=/usr/local/opt/luajit --tree=/private/tmp/neovim-20201104-11684-1m3kzz/deps-build
> ==> luarocks make --lua-dir=/usr/local/opt/luajit --tree=/private/tmp/neovim-20201104-11684-1m3kzz/deps-build
> ==> cmake . -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_INSTALL_PREFIX=/private/tmp/neo
> ==> make install
> ==> cmake .. -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DLIBLUV_INCLUDE_DIR=/private/tmp/neov
> ==> make install
> Last 15 lines from /Users/USER/Library/Logs/Homebrew/neovim/07.make:
> /tmp/neovim-20201104-11684-1m3kzz/src/nvim/lua/treesitter.c:18:10: fatal error: 'tree_sitter/api.h' file not found
> #include "tree_sitter/api.h"
>          ^~~~~~~~~~~~~~~~~~~
> In file included from /tmp/neovim-20201104-11684-1m3kzz/src/nvim/lua/executor.c:40:
> /tmp/neovim-20201104-11684-1m3kzz/src/nvim/lua/treesitter.h:8:10: fatal error: 'tree_sitter/api.h' file not found
> #include "tree_sitter/api.h"
>          ^~~~~~~~~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [src/nvim/auto/lua/executor.c.generated.h] Error 1
> make[2]: *** Waiting for unfinished jobs....
> 1 error generated.
> make[2]: *** [src/nvim/auto/lua/treesitter.c.generated.h] Error 1
> cd /tmp/neovim-20201104-11684-1m3kzz/build/src/nvim && /usr/local/bin/luajit /tmp/neovim-20201104-11684-1m3kzz/src/nvim/generators/gen_declarations.lua /tmp/neovim-20201104-11684-1m3kzz/src/nvim/main.c /tmp/neovim-20201104-11684-1m3kzz/build/src/nvim/auto/main.c.generated.h /tmp/neovim-20201104-11684-1m3kzz/build/include/main.h.generated.h /tmp/neovim-20201104-11684-1m3kzz/build/src/nvim/auto/main.i
> make[1]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
> make: *** [all] Error 2
> 
> READ THIS: https://docs.brew.sh/Troubleshooting
> 
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or IRC.

### Expected behaviour
No errors.

**Comment by vigoux** [comment]
The fix is over there, being worked on : https://github.com/Homebrew/homebrew-core/pull/64015

**Comment by Woolworths** [comment]
Quick reply and thanks.

**Comment by vegerot** [comment]
@Woolworths https://github.com/neovim/neovim/issues/13216#issuecomment-721162241 is obviously the correct answer.  If you're a little less patient like I am, run `brew edit neovim` and apply this patch.

```diff
diff --git a/Formula/neovim.rb b/Formula/neovim.rb
index aa6b33797..4ab9e3c4e 100644
--- a/Formula/neovim.rb
+++ b/Formula/neovim.rb
@@ -56,6 +56,7 @@ class Neovim < Formula
   end

   def install
+    system("git checkout 432f3240f171e857beb3d1a554cbd8a649bb38ae")
     resources.each do |r|
       r.stage(buildpath/"deps-build/build/src/#{r.name}")
     end
```

**Comment by teto** [comment]
best to report this on brew if you see that master builds fine. Let's keep this open until homebrew merges their recipe.

**Comment by carlocab** [comment]
This appears to now have been merged: https://github.com/Homebrew/homebrew-core/pull/64015#issuecomment-721450090

**Comment by Woolworths** [comment]
> This appears to now have been merged: [Homebrew/homebrew-core#64015 (comment)](https://github.com/Homebrew/homebrew-core/pull/64015#issuecomment-721450090)
> 
> `brew install --HEAD nvim` now works for me.

Yep, fixed for me too now.

**Comment by vigoux** [comment]
This has been fixed in homebrew, closing now.

**Comment by sdondley** [comment]
Broken again.

**Comment by HerkG** [comment]
Mac OS Monterey.  I ran the 4 commands Woolworth mentions in his comment and neovim 0.5 --HEAD built and installed Ok.
