### ISSUE TITLE
nvim-lsp stop working after c60c737

### ISSUE THREAD

**Issue by jubnzv** [neovim/neovim#13210]
It looks like c60c737 broke nvim-lsp.

Аfter updating neovim to the c60c737 I get the following error when starting any LSP server:

```
Error executing luv callback:
vim.lua:117: E5560: nvim_get_runtime_file must not be called in a lua loop callback
```

These errors disappear after rolling back to 6224ec3.

I haven't looked at how neovim's internals work, so I can't give a more detailed feedback.

@bfredl Could you please check this?

**Comment by mechkblife** [comment]
Just hit this error also :(

**Comment by notomo** [comment]
This error may be caused by the use of vim.inspect in luv callback somewhere.

```lua
local log = require("vim.lsp.log")

table.insert(package.loaders, 1, function(name)
  print(name)
  return nil
end)

local stdout = vim.loop.new_pipe(false)
vim.loop.spawn("echo", {stdio = {nil, stdout, nil}}, function() end)
stdout:read_start(function()
  log.error("test")
end)
```

```console
$ nvim --headless --clean -n +"luafile ./test.lua"
vim.inspect
Error executing luv callback:
vim.lua:117: E5560: nvim_get_runtime_file must not be called in a lua loop callback
Press ENTER or type command to continue^C
```

https://github.com/neovim/neovim/blob/5b5848f2fb1f4b7995bb8a59d94b6766d2182070/runtime/lua/vim/lsp/log.lua#L70-L70
https://github.com/neovim/neovim/blob/5b5848f2fb1f4b7995bb8a59d94b6766d2182070/src/nvim/lua/vim.lua#L264-L264
https://github.com/neovim/neovim/blob/5b5848f2fb1f4b7995bb8a59d94b6766d2182070/runtime/lua/vim/lsp/rpc.lua#L565-L587

**Comment by ruifm** [comment]
I'm also getting the same error. Actually reverting to dc14b1468afeb53c9ca0a734a2035cc54b5e1d94 is enough to stop it.

This goes without saying, reverting just c60c7375f5754eea2a4209cc6441e70b2bb44f14 from master (as I write this) also does the trick.

**Comment by DevonMorris** [comment]
Seeing the same behavior here

**Comment by ludwj61** [comment]
I have this issue after updating, on version 0.5.0-799-g186ba3b68

**Comment by notomo** [comment]
This issue seems to be resolved by https://github.com/neovim/neovim/pull/13211 👍

https://github.com/neovim/neovim/issues/13210#issuecomment-720933145
```
$ nvim --headless --clean -n +"luafile ./test.lua"
vim.inspect^C

```

**Comment by Shougo** [comment]
If so, it should be closed.

**Comment by notomo** [comment]
nvim_get_runtime_file's error is resolved.
I just noticed, now sometimes I get the following error. 

```
Error executing luv callback:
vim.lua:264: module 'vim.inspect' not found:
	no field package.preload['vim.inspect']
	no file '/home/notomo/.local/share/lua/5.1/vim/inspect.lua'
	no file '/home/notomo/.local/share/lua/5.1/vim/inspect/init.lua'
	no file '/home/notomo/.local/lib/lua/5.1/vim/inspect.so'
	no file '/home/notomo/.local/lib/lua/5.1/vim.so'
```

`vim.api.nvim_get_runtime_file(path, false)` may return a file path that does not exist.

**Comment by jubnzv** [comment]
Yes, it seems to be fixed in the HEAD. Everything works fine after the update. 👍
