### ISSUE TITLE
lsp documentation recommends to override <c-]>

### ISSUE THREAD

**Issue by jecaro** [neovim/neovim#13217]
`lsp.txt` gives as a configuration example this statement:
```vim
nnoremap <silent> <c-]> <cmd>lua vim.lsp.buf.definition()<CR>
```
If applied, it is not possible to navigate througt the help anymore with `<c-]>`. When used in the help to jump to a tag, `nvim` complains with:
```
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/lsp/callbacks.lua:338: RPC[Error] code_name = MethodNotFound, message = "method textDocument/definition is not 
supported by any of the servers registered for the current buffer"
```
I think the document should not give an example of key bindings which override such an important shortcut. Alternatively the documentation should show how to set this binding for buffers with lsp only (not sure if it's possible though).

**Comment by DevonMorris** [comment]
I believe this is because you are remapping this globally. You should only remap it in buffers where you have lsp running. Maybe this should be mentioned in `lsp.txt`

**Comment by clason** [comment]
Yes, the documentation for LSP is in need of overhaul before release (it mostly hasn't been touched since the initial merge last December). This particular bit will be improved as part of #12655 (such mappings should indeed be set as part of the `on_attach` function, not globally).

**Comment by jecaro** [comment]
Thank you. I reported the problem as I find it difficult to find a proper example of a working configuration. But the documentation in #12655  fixes this. Closing then.
