### ISSUE TITLE
Question: How to get current window cursor row with respect to first line displayed on window?

### ISSUE THREAD

**Issue by RishabhRD** [neovim/neovim#13221]
nvim_win_get_cursor(...) returns row with respect to buffer lines. However, is there any function that returns the current cursor position with respect to the first-line displayed on the window? For example, if currently, a window is displaying lines in the range: 34-68, and currently cursor is on 37. So, this function should return 4.

**Comment by notomo** [comment]
You can get it by `line(".") - line("w0") + 1` for current window.

ref. `:h line()`

**Comment by RishabhRD** [comment]
Thanks! I was only searching nvim_get_* or nvim_win_get_* functions, and I missed it. Sorry for this noob question :sweat_smile:
