### ISSUE TITLE
Reinterpreted ALT- chords are not replayed correctly

### ISSUE THREAD

**Issue by gobwas** [neovim/neovim#13235]
- `nvim --version`: 
```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
```
- `vim -u DEFAULTS` (version: ) behaves differently (works as expected).

### Steps to reproduce

Having buffer with this text:
```
foo
bar
baz
```
Putting cursor on first line and entering in a macro recording mode: `qk`.
Register `k` contents: `^Viw"ay0C// This is some text: <80><fc>^H"ap^[`
That is, the idea is to copy whole word on the line to the register `a`, then replace line with text "This is some text _register a contents_".

After applying macro (`@k`) to three lines I expect to see:
```
This is some text: foo
This is some text: bar
This is some text: baz
```

### Actual behaviour
```
This is some text: foo
This is some text: "ap
This is some text: "ap
```

**Comment by subnut** [comment]
It's impossible to know what keys you have pressed by looking at the macro register.
Please give proper steps (including the keys you had pressed)

**Comment by gobwas** [comment]
@subnut that macro is a result of this sequence:
<kbd>Ctrl</kbd>+<kbd>v</kbd><kbd>i</kbd><kbd>w</kbd><kbd>"</kbd><kbd>a</kbd><kbd>y</kbd><kbd>0</kbd><kbd>C</kbd><kbd>// This is some text: </kbd><kbd>Esc</kbd><kbd>"</kbd><kbd>a</kbd><kbd>p</kbd>

**Comment by subnut** [comment]
Thanks for the steps! I tried with `nvim -u NONE` and got the following results - 
```
// This is some text: foo
// This is some text: bar
// This is some text: baz
```

Could you please give us a **minimal** vimrc to reproduce the issue?

**Comment by gobwas** [comment]
Wow! I can confirm it works for me too with `-u NONE`. Let me try to detect the reason 👍

**Comment by gobwas** [comment]
I can also say that with `--noplugin` it also works 🤔

**Comment by gobwas** [comment]
Oops, sorry, closed accidentally

**Comment by gobwas** [comment]
I can also say, that for one of the nigthly builds of neovim it works as expected (I pulled today); however, for the nightly build I've pulled around week ago it doesn't. Is there any way to get the git hash of the nightly build?

**Comment by subnut** [comment]
> for the nightly build I've pulled around week ago it doesn't.

Had you tried with `nvim -u NONE` ?

> Is there any way to get the git hash of the nightly build?

Are the old and new builds in separate folders? If so, you can go the the old folder and run `git rev-parse --verify HEAD` to get the hash of the latest commit (i.e. the one where you have built from)

If not, (i.e. You did `git pull` in the same folder), then I don't know of any way to get the hash from a built binary. Maybe someone else can help....

**Comment by gobwas** [comment]
Yeah, so to clarify and summarize: for the old build it doesn't work in any way (`nvim -u NONE` nor `nvim --noplugin`, as well as for just `nvim` of course).
For the new build it works in all ways.

I didn't use git, I used the asstes attached [here](https://github.com/neovim/neovim/releases/tag/nightly) (the source .tar.gz link).

**Comment by subnut** [comment]
> Is there any way to get the git hash of the nightly build?

> I didn't use git, I used the assets attached here (the source .tar.gz link).

Hmm.... Maybe the last 9 digits of `nvim --version` correspond to the git hash from where the binary was produced ?? :shrug:

See... the current build is `NVIM v0.5.0-dev+929-gfaa47eaff`, which was built from commit `faa47eafffe35ddfdee44d341d7dc06e97377b28`
See? The last 9 digits of the version match the initial digits of the commit hash!

What are the versions of your binaries?

**Comment by gobwas** [comment]
@subnut I have this:
```
$ nvim --version
NVIM v0.5.0-dev
```

**Comment by gobwas** [comment]
Closing this for now since I have to update my neovim and looks like there is no way to investigate where this bug was introduced and then fixed. Thank you anyway for your help.

**Comment by gobwas** [comment]
@subnut looks like it's not fixed, and is a bug on MacOS. I fetched latest sources and did `make && make install`, but the problem still rerpoduces.

**Comment by gobwas** [comment]
Maybe I have to build it different way?

**Comment by gobwas** [comment]
The exact installation steps are:
- ensure that these deps are installed: ninja, libtool, automake, cmake, pkg-config, gettext
- download archive from https://github.com/neovim/neovim/archive/nightly.tar.gz
- extract archive somewhere
- run `make CMAKE_INSTALL_PREFIX=$HOME/neovim CMAKE_BUILD_TYPE=Release`
- run `make install`

After that if I run `nvim -u NONE` and repeat steps with macro I have same wrong results.

**Comment by gobwas** [comment]
It still doesn't seem to work for v0.6.1.
Can anybody guide me how to help debug this?

**Comment by zeertzjq** [comment]
Do you have `<Esc>` mapped in Insert mode?

**Comment by zeertzjq** [comment]
BTW, `nvim --clean` should be used instead of `nvim -u NONE` or `nvim --noplugin` to simulate a fresh install.

**Comment by gobwas** [comment]
Huh! After random searches here and there I found the cause.

First, I found here the https://github.com/neovim/neovim/issues/5367 issue, and tried to run neovim in a different terminal. And my issue disappeared! But then I delved a bit deeper and found that the origin of the problem was the way tmux handles escape key -- I'm not sure why exactly, but if I don't have this setting in my .tmux.conf: `set -s escape-time 0`, I see a `^[<80><fc>^H` sequence in my `"k` register contents (which holds recorded macro value). If I add the setting, I see just `^[`.

However, vim handles this correctly.

**Comment by zeertzjq** [comment]
<https://github.com/neovim/neovim/wiki/FAQ#why-doesnt-this-happen-in-vim>

**Comment by zeertzjq** [comment]
Oh, `<80><fc>^H` is for the ALT key, so this can still indicate a problem with input handling when replaying a macro.

**Comment by gobwas** [comment]
Oh, great. Thank you @zeertzjq!

**Comment by gobwas** [comment]
Oh, just closed the issue without getting your latest comment. Reopen for convenience.

**Comment by zeertzjq** [comment]
Oh, this problem also applies to `-w`.

**Comment by zeertzjq** [comment]
I just found another Vim bug that may have the same root cause as this. Reported at <https://github.com/vim/vim/issues/9462>.
