### ISSUE TITLE
vim.lsp.buf.formatting_sync() fails with `attempt to index a nil value`

### ISSUE THREAD

**Issue by tyrion** [neovim/neovim#13232]
Executing `:lua vim.lsp.buf.formatting_sync()` sometimes fails with `attempt to index a nil value`
at https://github.com/neovim/neovim/blob/d17e508796be60eefe4a597df62de1fd9e7e1725/runtime/lua/vim/lsp/buf.lua#L142

I am not a lua expert and I do not know how to reproduce this with `nvim -u NORC`. However, I tried to debug this by making a small lua file `test.lua` and then executing it in the current buffer with `:luafile`. This shows that sometimes the result variable is inside the `2` key, instead of `1`.

```lua
-- dump copied from https://stackoverflow.com/a/27028488/641317
function dump(o)
   if type(o) == 'table' then
      local s = '{ '
      for k,v in pairs(o) do
         if type(k) ~= 'number' then k = '"'..k..'"' end
         s = s .. '['..k..'] = ' .. dump(v) .. ','
      end
      return s .. '} '
   else
      return tostring(o)
   end
end

local params = require'vim.lsp.util'.make_formatting_params()
local result = vim.lsp.buf_request_sync(0, "textDocument/formatting", params)

print(dump(result))
-- shows: { [2] = { ["result"] = { } ,} ,}
```

This seems to happen only when I open two different files that uses two different language server. Then the problem happens on the second one.
Not sure what this index here is meant to represent. My guess is that it seems the index of the language server used. 

- `nvim --version`:
    ```
    NVIM v0.5.0-dev
    Build type: Release
    LuaJIT 2.1.0-beta3
    Compilation: 
    Compiled by nixbld
    Features: +acl +iconv +tui
    ```
    git rev: a061d53e18168130aad537a9e8012390834ff8c2

- language server name/version: typescript-language-server v0.4.0
- Operating system/version: nixos

<details>
<summary>nvim -c ":checkhealth nvim nvim_lsp"</summary>

health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/tyrion/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.
  - INFO: svelte_lsp: configuration checked.
</details>

<details>
<summary>lsp.log</summary>

[ DEBUG ] 2020-11-05T20:39:58+0100 ] ...m-unwrapped-0.5.0-799/share/nvim/runtime/lua/vim/lsp.lua:666 ]  "LSP[tsserver]" "client.request"        2       "textDocument/formatting"       {  options = {    insertSpaces = true,    tabSize = 4  },  textDocument = {    uri = "file:///home/tyrion/src/kschema/src/main.ts"  }}     <function 1>    3
[ DEBUG ] 2020-11-05T20:39:58+0100 ] ...wrapped-0.5.0-799/share/nvim/runtime/lua/vim/lsp/rpc.lua:376 ]  "rpc.send.payload"      {  id = 5,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = true,      tabSize = 4    },    textDocument = {      uri = "file:///home/tyrion/src/kschema/src/main.ts"    }  }}
[ DEBUG ] 2020-11-05T20:39:58+0100 ] ...wrapped-0.5.0-799/share/nvim/runtime/lua/vim/lsp/rpc.lua:477 ]  "decoded"       {  id = 5,  jsonrpc = "2.0",  result = {}}

</details>

**Comment by fsouza** [comment]
Yeah, `buf_request_sync` uses the client_id as the key and we assume it's [1] here, which is wrong. The correct approach is probably to use `next(result)` instead of `result[1]` in formatting_sync.

Here's where the result is set to the client_id:

https://github.com/neovim/neovim/blob/d17e508796be60eefe4a597df62de1fd9e7e1725/runtime/lua/vim/lsp.lua#L1067-L1070

**Comment by tyrion** [comment]
I would happily open a PR, however I basically never used lua. Let me know if I should do it anyway. This is what I came up with to fix the issue:

```lua
  local util = require 'vim.lsp.util'

  function _G.formatting_sync(options, timeout_ms)
    local params = util.make_formatting_params(options)
    local result = vim.lsp.buf_request_sync(0, "textDocument/formatting", params, timeout_ms)
    if not result then return end
    local index, value = next(result)
    result = value.result
    if not result then return end
    vim.lsp.util.apply_text_edits(result)
  end
```

**Comment by fsouza** [comment]
Sent #13233.
