### ISSUE TITLE
Ugly yellow highlight when copying text that doesn't go away

### ISSUE THREAD

**Issue by lynndylanhurley** [neovim/neovim#13236]
See the yellow highlight in the attached screenshot.

These highilghts sometimes show up after I copy a visual selection. It doesn't happen all the time. When the yellow text appears, there doesn't seem to be a way to get rid of it without closing vim and re-opening.

Does anyone know what causes this or how I can disable it?

<img width="564" alt="Screen Shot 2020-11-06 at 3 49 58 PM" src="https://user-images.githubusercontent.com/468037/98418175-fb8caf00-2047-11eb-996a-8533f3d9c372.png">

**Comment by jdhao** [comment]
How do you reproduce with `nvim -u NORC`?

**Comment by clason** [comment]
Can you also give the exact neovim version (commit, if you build from master -- as you likely do, since that seems like the `highlight.on_yank()` timeout not working properly for you?

**Comment by lynndylanhurley** [comment]
> How do you reproduce with `nvim -u NORC`?

@jdhao I can't reproduce without plugins enabled. I tried to narrow down the issue to a specific plugin but the issue is so intermittent that I wasn't able to.

> Can you also give the exact neovim version (commit, if you build from master -- as you likely do, since that seems like the `highlight.on_yank()` timeout not working properly for you?

@clason it's been happening for awhile, but when I created this issue I was on cedfc1b7477060917a31d4f1c526db3da0deb15c (from about 2 days ago).

It could be that one of the plugins uses `highlight.on_yank()`. I'll investigate, thanks 👍

**Comment by lynndylanhurley** [comment]
Ok I just looked into this an none of my plugins are using `highlight.on_yank()`. I grepped the entire plugin dir and didn't get any results for `on_yank`. Any other ideas @clason ?

**Comment by clason** [comment]
Actually, I meant it the other way around -- something else is interfering with the scheduled timeout that `on_yank()` is using. That's harder to track down...

**Comment by glacambre** [comment]
@lynndylanhurley Are you still experiencing this bug on master/nightly? If yes, could you list your plugins?

**Comment by lynndylanhurley** [comment]
@glacambre I haven't seen this in awhile. I'll go ahead close.
