### ISSUE TITLE
LSP returns MethodNotFound while LSP supports it.

### ISSUE THREAD

**Issue by frondeus** [neovim/neovim#13230]
- `nvim --version`:
```
NVIM v0.5.0-799-g186ba3b68
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-df9e3951-6e7f-4b7d-b899-cb28f832c120

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```
- language server name/version: `rust-analyzer 4e8401a`
- Operating system/version: `Ubuntu 20.10 on WSL2.0`

<details>
<summary>nvim -c ":checkhealth nvim nvim_lsp"</summary>
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: rust_analyzer: configuration checked.

</details>

<details>
<summary>lsp.log</summary>

Before it was empty.
After i tried to go to declaration:

[ WARN ] 2020-11-05T09:53:39+0100 ] ...ount_nvim.aLe5k17/usr/share/nvim/runtime/lua/vim/lsp.lua:80 ]    "method textDocument/declaration is not supported by any of the servers registered for the current buffer"
[ DEBUG ] 2020-11-05T09:53:39+0100 ] ...aLe5k17/usr/share/nvim/runtime/lua/vim/lsp/callbacks.lua:336 ]  "default_callback"      "textDocument/declaration"      {  err = {    code = -32601,    message = "method textDocument/declaration is not supported by any of the servers registered for the current buffer",    <metatable> = {      __tostring = <function 1>    }  },  params = 0}

</details>

<details>
<summary>my init.vim</summary>
call plug#begin('~/.vim/plugged')

Plug 'neovim/nvim-lspconfig'

call plug#end()

syntax enable
filetype plugin indent on

lua <<EOF

require'nvim_lsp'.rust_analyzer.setup{}

EOF

nnoremap <silent> gd    <cmd>lua vim.lsp.buf.declaration()<CR>
</details>

Rust analyzer is running and its enabled.
`:lua print(vim.inspect(vim.lsp.get_active_clients()))` returns its config, declaration support is enabled there.

I tried this example of `main.rs`:
```
fn foo() -> u32 {
    4
}

fn main() {
    let _x = foo();

    println!("Hello, world!");
}
```
Installed plugin, waited till RA completed indexing and pressed `gd` under `foo()` call.
### Steps to reproduce using `nvim -u NORC`

It requires configuration of lsp_nvim so I don't know how.

### Actual behaviour
It doesn't go to declaration, returns an error
### Expected behaviour
It should go to declaration

**Comment by fsouza** [comment]
I don't think rust-analyzer supports `textDocument/declaration`, it only supports `textDocument/definition`, `textDocument/implementation` and `textDocument/typeDefinition`.

In your case, you probably want `textDocument/definition`.

**Comment by frondeus** [comment]
Oh, that makes sense. I was mislead by `capabilities.textDocument.declaration.linkSupport = true` returned by  bu these are client capabilities not ones from RA. Thanks for pointing it :)

**Comment by teto** [comment]
seems like we can close. Reopen if I misunderstood.
