### ISSUE TITLE
When using nvim_set_hl, changing linked group has no effect

### ISSUE THREAD

**Issue by fsouza** [neovim/neovim#13246]
- `nvim --version`: `NVIM v0.5.0-819-g0fcc13c11`
- `vim -u DEFAULTS` non-applicable
- Operating system/version: macos 10.15.7 (Darwin host.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64)
- Terminal name/version: Alacritty
- `$TERM`: `screen-256color`

### Steps to reproduce using `nvim -u NORC`

Execute the file below (with `luafile %`):

```lua
local api = vim.api

vim.o.termguicolors = true

vim.cmd([[
  highlight OriginalGroup guifg='#990000'
  highlight link LinkGroup OriginalGroup
]])

local bufnr = api.nvim_get_current_buf()
api.nvim_buf_clear_namespace(bufnr, -1, 0, -1)
api.nvim_buf_set_virtual_text(bufnr, 0, 2, {{'- this should not be red', 'LinkGroup'}}, {})

local ns = api.nvim_create_namespace('debugging-hl')
api.nvim_set_hl_ns(ns)
api.nvim_set_hl(ns, 'LinkGroup', {fg = 'Blue'})
```

(It works fine if I setup the link using nvim_set_hl instead of vim.cmd - see the "extra information"

### Actual behaviour

The virtual text is red.

### Expected behaviour

The virtual text is blue.

### Extra information

Noticed this while testing #12655 locally, I a using nvim_set_hl to manage my colorscheme locally, and noticed I couldn't change the color of diagnostic messages x)

See the gif below comparing a solution that uses nvim_set_hl to configure the link (it behaves as expected) vs usim vim.cmd to do the same (doesn't behave as expected).

![output](https://user-images.githubusercontent.com/108725/98453161-09176700-2124-11eb-976a-a265ae7c6313.gif)

<details><summary>repro-vcmd.lua - sets up link with vim.cmd & doesn't work as expected</summary>

```lua
local api = vim.api

vim.o.termguicolors = true

vim.cmd([[
  highlight OriginalGroup guifg='#990000'
  highlight link LinkGroup OriginalGroup
]])

local bufnr = api.nvim_get_current_buf()
api.nvim_buf_clear_namespace(bufnr, -1, 0, -1)
api.nvim_buf_set_virtual_text(bufnr, 0, 2, {{'-  this should not be red', 'LinkGroup'}}, {})

local ns = api.nvim_create_namespace('debugging-hl')
api.nvim_set_hl_ns(ns)
api.nvim_set_hl(ns, 'LinkGroup', {fg = 'Blue'})
```
</details>

<details><summary>repro.lua - sets up link with nvim_set_hl & works as expected</summary>

```lua
local api = vim.api

vim.o.termguicolors = true

local ns = api.nvim_create_namespace('debugging-hl')
api.nvim_set_hl(ns, 'OriginalGroup', {fg = '#990000'})
api.nvim_set_hl(ns, 'LinkGroup', {link = 'OriginalGroup'})
api.nvim_set_hl_ns(ns)

local bufnr = api.nvim_get_current_buf()
api.nvim_buf_clear_namespace(bufnr, -1, 0, -1)
api.nvim_buf_set_virtual_text(bufnr, 0, 2, {{'-  this should not be red', 'LinkGroup'}}, {})

api.nvim_set_hl(ns, 'LinkGroup', {fg = 'Blue'})
```
</details>

**Comment by fsouza** [comment]
cc @bfredl

**Comment by bfredl** [comment]
@fsouza Thanks for the very clear repro instructions, I turned them into a failing test #13250 :)

**Comment by ibraheemdev** [comment]
I have a similar issue where I can't update diagnostic highlights through lua, but `vim.cmd` works fine:
```lua
local hl = vim.api.nvim_set_hl
local sign = vim.fn.sign_define

function lsp_highlights(ns)
    local colors = {
        Error = "#cc241d",
        Warning = "#d79921",
        Reference = "#d79921",
        Information = "#458588",
        Hint = "#b16286"
    }

    hl(ns, "LspReferenceRead", {bg = colors.Reference; underline = true})
    hl(ns, "LspReferenceText", {bg = colors.Reference; underline = true})
    hl(ns, "LspReferenceWrite", {bg = colors.Reference; underline = true})

    for _, level in pairs({'Error'; 'Warning'; 'Information'; 'Hint'}) do
      hl(ns, 'LspDiagnosticsSign' .. level, { fg = colors[level] })
      hl(ns, 'LspDiagnosticsVirtualText' .. level, { fg = colors[level] })
      hl(ns, 'LspDiagnosticsUnderline' .. level, { fg = colors[level] })
      hl(ns, 'LspDiagnosticsFloating' .. level, { fg = colors[level] })
    end

    sign("LspDiagnosticsSignError", {text = "", texthl = "LspDiagnosticsSignError"})
end
```

I know that this function is being called correctly as the calls to `sign` are reflected in my buffer. Is this a related error, or is there something I am doing wrong?

**Comment by ibraheemdev** [comment]
Updated to neovim 0.6 and now highlights aren't working at all?

**Comment by zeertzjq** [comment]
Some highlight groups were deprecated.

**Comment by ibraheemdev** [comment]
Thanks, it works after updating per https://github.com/neovim/neovim/pull/15585/commits/a5bbb932f9094098bd656d3f6be3c58344576709

**Comment by zeertzjq** [comment]
Seem fixed now.
