### ISSUE TITLE
inconsistent vimscript-> lua cml mode mapping

### ISSUE THREAD

**Issue by ilAYAli** [neovim/neovim#13251]
- `nvim --version`:v0.5.0-812-gd17e50879
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:lua vim.api.nvim_set_keymap('c', '<up>', 'pumvisible() ? "<C-P>" : "<Up>"', { noremap = true, expr = true, silent = true })
```

### Actual behaviour
arrow up navigation of cml history does not work after executing the above command.
:\<up\> does not work
:\<c-p\> works

### Expected behaviour
:\<up\> should work, as with with the vimscript equivalent: `cnoremap <expr> <up>   pumvisible() ? "<C-p>" : "\<up>"`

**Comment by erw7** [comment]
It seems that we need to escape double quotes (`"`) and backslashes (`\`) as follows.

```
:lua vim.api.nvim_set_keymap('c', '<up>', 'pumvisible() ? \"\\<C-p>\" : \"\\<Up>\"', { noremap = true, expr = true, silent = false})
```

**Comment by ilAYAli** [comment]
@erw7 very nice. I also found that the following mapping did not work with `noremap = true`:
 `:lua vim.api.nvim_set_keymap('n', '<s-right>', "<plug>(coc-definition)", { noremap = true, silent = true })`
It seems that the lua api for defining key maps have exposed several vim inherited issues/inconsistencies.
@bfredl et al. feel free to close the issue.

**Comment by bfredl** [comment]
Well that one is just that `noremap` doesn't work with `<plug>` because all plug mappings are remaps by necessity.
