### ISSUE TITLE
Provide a provision to open a file in popup window when type gf or gF

### ISSUE THREAD

**Issue by SamPosh** [neovim/neovim#13257]
Often in my log file look like below, I will use gF to go to file with line number.
In this case , when i type gF it will open debug.yml file and cursor would be at line number 17.
```
task path: /home/ansible/codecommit/code2/test/debug.yml:17
ok: [127.0.0.1] => {
    "ansible_ssh_user": "ansible"
}
```
Some times i do not need to open the file in buffer , I just need to do glance. 
So if a file is opened in popup window (like peek in vscode)  ,it would be nice.
We can glance it and then close it . 

While using gf for go to file , It is better to add provision there to go to file in popup window

**Comment by jdhao** [comment]
I am sure you can remap `gf` to achieve that. All the functions and command you need are there, you just need to write some code to open the file in a floating window.

**Comment by SamPosh** [comment]
The reason I am asking this feature is as below:

gf/gF works with tab and buffer so I believe it should support popup File open in Vim itself

If I do my own config , I have to write a logic for vim8 differently and nvim differently as they are using different API.

**Comment by jdhao** [comment]
This kind of thing is more suitable for a plugin rather than in core nvim. It has already provided all the building blocks. If you want it work in a specific way, then config it.

Also, set up a floating window requires some aesthetic choice, such as color, padding, window options, etc. This really should not go into core nvim since different users have different choices. You can satisfy them all.

**Comment by SamPosh** [comment]
In vscode , when pressing F12 they show it in popup. If user want more aesthetics they can customise it. I think a basic popup window gF would be very nice thing.

**Comment by cyansprite** [comment]
Here is an super simple example you can use for Neovim
The scrolling could use some work but it's an example of how it can be done.

```vim
" {{{ Preview File Under Cursor
" Test: ~/Documents/bash-resources/nvim-plugs/init.vim : 100
let g:file_pop_win_id = -1
func! PreviewFile()
    call CloseFilePreview()

    let max_height = 20
    let filetype = ''
    let bufnr = bufnr()

    try
        keepj norm! gF
    catch /^Vim\%((\a\+)\)\=:E447/
        echohl ErrorMsg | echom v:exception | echohl None
        return
    endtry

    let filebuf = bufnr()
    execute 'keepj buf ' . bufnr

    let g:file_pop_win_id = nvim_open_win(filebuf, v:false, {
                \ 'relative': 'cursor',
                \ 'row': 1,
                \ 'col': 0,
                \ 'width': &tw,
                \ 'height': max_height,
                \ 'style': 'minimal'
                \ })

    call nvim_win_set_option(g:file_pop_win_id, 'foldenable',  v:false)

    nmap <c-u> <cmd>silent! call nvim_win_set_cursor(g:file_pop_win_id, [nvim_win_get_cursor(g:file_pop_win_id)[0] - nvim_win_get_height(g:file_pop_win_id), 0])<cr>
    nmap <c-d> <cmd>silent! call nvim_win_set_cursor(g:file_pop_win_id, [nvim_win_get_cursor(g:file_pop_win_id)[0] + nvim_win_get_height(g:file_pop_win_id), 0])<cr>
    autocmd CursorMoved <buffer> ++once call CloseFilePreview()
endfunc

func! CloseFilePreview()
    silent! unmap <c-u>
    silent! unmap <c-d>

    if g:file_pop_win_id != -1
        execute win_id2win(g:file_pop_win_id).'wincmd c'
        let g:file_pop_win_id = -1
    endif
endfunc

nnoremap gfp     <cmd>call PreviewFile()<CR>
"}}}

```

Here is a gif of me testing it using gfp first then gF.

[gfpexample](https://imgur.com/a/kpg9MEa)

**Comment by matu3ba** [comment]
Popups should not be provided by neovim core as there are infinitely many ways to position and organize them instead of a limited 2D pane.

Please write a plugin for this.

Suggesting to close this.

**Comment by clason** [comment]
It's fairly easy to implement yourself using `v:lua.vim.lsp.util.preview_location(location)`, where `location` is a [`Location` or `LocationLink`](https://microsoft.github.io/language-server-protocol/specification#location).

**Comment by justinmk** [comment]
> If I do my own config , I have to write a logic for vim8 differently and nvim differently as they are using different API.

Just pick a text editor then.

The general solution here is to make all builtin commands overridable/hookable/listenable.

Adding random bells and whistles to specific commands is usually not compelling.
