### ISSUE TITLE
[QUESTION] UpdateRemotePlugins - 'Not an editor command' issues and workarounds

### ISSUE THREAD

**Issue by levouh** [neovim/neovim#13267]
## Version Information

_:version_
```
NVIM v0.5.0-812-gd17e50879
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE
 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/
build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-317a2489-aba5-414a-b9f3-9551746c326c

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

_cat /etc/os-release_
```
NAME=Fedora
VERSION="31 (Thirty One)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Thirty One)"
ANSI_COLOR="0;34"
...
```

_echo $TERM_
```
xterm-256color
```

## Note

I understand from reading `:h startup` that this behavior is expected, as this _is a plugin, which will be loaded after the user `init.vim`_. The question here is around whether there's a better way to do initialization in cases where the user config relies heavily on remote plugins.

## Reproduction

_The `nvim -u NORC` sort of defeats the problem at hand here, so I'll skip that part and jump right into reproduction._

1. Setup a valid `init.vim` that is simply the following:
```
UpdateRemotePlugins
```
2. Observe the following output:
```
Error detected while processing /home/amasquelier/.config/nvim/init.vim:
line    1:
E492: Not an editor command: UpdateRemotePlugins
```

## Workarounds

Again, I understand that this behavior is expected. This is a plugin, which is loaded _after_ the `init.vim` scrit. I'm looking for a better way to do this.

I'm not incredibly familiar with Neovim, and have much more experience with standard Vim, where user-defined commands and functions have to be Pascal-case, like what we see with `UpdateRemotePlugins`. So assuming that this is indeed a standard plugin, we can confirm by running `:command UpdateRemotePlugins` and observe:

```
    Name              Args Address Complete    Definition
|   UpdateRemotePlugins 0                      call remote#host#UpdateRemotePlugins()
```

which could seemingly help us figure out a workaround. Given the way that functions are auto-loaded, it seems that we'd have better luck calling the function itself, as Vim can "find" the function, where it won't be able to do the same with the associated command. Cool, so we can change our `init.vim` to:

```
call remote#host#UpdateRemotePlugins()
```

but then we get a new set of errors, namely:

```
Error detected while processing function remote#host#UpdateRemotePlugins:
line   16:
E121: Undefined variable: g:loaded_remote_plugins
```

Again, seemingly this is something that we can work around by changing our `init.vim` to:

```
let g:loaded_remote_plugins = 0
call remote#host#UpdateRemotePlugins()
```

which allows `nvim` to start up just fine, but it appears the the remote plugin isn't actually loaded correctly:

```
remote/host: python3 host registered plugins ['pluginctl.py']
remote/host: generated rplugin manifest: 0
```

Also, now it seems that the external definition of the `g:` variable has lead to skipping defining the command in the script itself. Now, what used to work before we called the function manually, calling `:UpdateRemotePlugins` _after `nvim` has started_ results in the same `E492`. Note again, this used to work before, but in the opposite fashion, and ideally both calling the command in my `init.vim` in some form as well as manually after initialization would work.

Reading a bit through `:h startup`, we can try setting up an `autocmd` that is loaded as part of the user config, that does what we actually want once step 7., where plugins get loaded, of the initialization is completed.

```
augroup startup | au!
    au VimEnter * UpdateRemotePlugins
augroup END
```

which does ultimately get us what we want, but seems a bit "hacky" for what my intention is. A lot of my config relies on the remote plugins, so I would ideally be able to just use their defined-commands in my `init.vim`, etc. rather than having a function in my initialization script that does the actual initialization.

Another option might be to use a `plugin/plugins.vim` or `after/plugins.vim` file, but I'd have to be careful about the order in which these files are loaded.

## Question

Is there a better way to do this? Everything above seems like a workaround for something that would seemingly work in a more "out of the box" fashion.

**Comment by Shougo** [comment]
I think `:UpdateRemotePlugins` should be built-in command like `:checkhelth`.

**Comment by Shougo** [comment]
But why you need to execute `:UpdateRemotePlugins` in init.vim?
Please explain it more detailed.

**Comment by bfredl** [comment]
@Shougo Almost, it should be eliminated altogether (0.6 milestone)

**Comment by levouh** [comment]
@Shougo, the specifics don't necessarily matter as the high level idea is to be able to use commands provided by remote plugins in your `init.vim`.

---

For example, tracking and managing plugins similar to how something like [minPlug](https://github.com/Jorengarenar/minPlug) works. More specifically, I have a `pluginctl.py` that I've used to do a lot of the heavy I/O via `asyncio` for managing plugins, cloning them, updating them, etc.

The syntax would look something like:

_init.vim_
```
" Ensure that your remote plugins have the latest interface loaded
UpdateRemotePlugins

" Add a plugin for tracking by the remote plugin
Plugin 'tpope/vim-fugitive' {'branch': 'master'}
```

where `:command Plugin` is defined in `pluginctl.py`.

---

>I think :UpdateRemotePlugins should be built-in command like :checkhealth

Very much agreed.

**Comment by levouh** [comment]
>Almost, it should be eliminated altogether (0.6 milestone)

@bfredl is there a tracking issue for the milestone as a whole, or better yet, this specific change?

**Comment by Shougo** [comment]
@levouh OK.  So you should use this instead.

```vim
runtime! plugin/rplugin.vim
```

**Comment by levouh** [comment]
@Shougo, I'm confused. Looking at `:h remote-plugin-manifest`, which states:

```
Unless $NVIM_RPLUGIN_MANIFEST is set the manifest will be written to a file
named `rplugin.vim` at:

	Unix 
	  $XDG_DATA_HOME/nvim/ or ~/.local/share/nvim/
```

so seemingly you are not stating that I should be sourcing the manifest, right? You are saying that I should do something like:

_~/.config/nvim/plugin/rplugin.vim_
```
" Ensure that your remote plugins have the latest interface loaded
UpdateRemotePlugins

" Add a plugin for tracking by the remote plugin
Plugin 'tpope/vim-fugitive' {'branch': 'master'}
```

where my aforementioned configuration exists within this file? The primary motivation being that these are loaded at step 7 in `:h startup` instead of step 4?

**Comment by Shougo** [comment]
I don't understand.
If you need to execute remote plugins in vimrc, you need to load rplugin.vim file before.

**Comment by Shougo** [comment]
Because remote plugins command definition is in rplugin.vim.

**Comment by levouh** [comment]
Oh, I see. Sourcing the definition of `UpdateRemotePlugins` via any `plugin/rplugin.vim` on `&rtp`. I was confused.

_~/.config/nvim/init.vim_
```
runtime! plugin/rplugin.vim
silent! UpdateRemotePlugins
```

This works.
