### ISSUE TITLE
Math Formular a "*" in markdown hinders spellcheck all is in italic

### ISSUE THREAD

**Issue by marek-step** [neovim/neovim#13269]
- `nvim --version`: VimR 0.33.0 
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: MacOS 10.15.7
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

Markdown: An Asterics * in a Formular like: $1,358,706~*~35~=~47,554,710~Euros$ everything after is in italic AND the spellcheck is not possible anymore.

**Comment by jdhao** [comment]
Asterics are used by Markdown to denote italics. You need to escape it if you mean literal asterics.

**Comment by marek-step** [comment]
thx jdhao I know 
but Pandoc translation over LaTeX to PDF will leave the escaped \* in the math formula, which is not intended. If the Asterics is not escaped, the VimR spellcheck is not working any more.  And everything is in italic after the unescaped * in the original markdown document.

**Comment by jdhao** [comment]
Since the Markdown standard does not include LaTeX formula, you way try third-party plugin such as [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) and [vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax) to see if they work for you. There two plugins provide pandoc-related features and syntax highlighting.

**Comment by marek-step** [comment]
Thank you jdhao

both plugins installed. Problem has gone! I have to dig although into the help files of these new plugins. Many things to learn.

Best greetings

marek

**Comment by glacambre** [comment]
I'm going to close this issue since it isn't a neovim bug :).
