### ISSUE TITLE
Occasional screen corruption after :grep

### ISSUE THREAD

**Issue by akavel** [neovim/neovim#13264]
- `nvim --version`:
```
$ vim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/y2dpkdd668fd4lv28xhxgmr4acfliy94-neovim-unwrapped-0.4.4/share/nvim
"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: NixOS 20.09 (but also observed it on MacOS)
- Terminal name/version: Kitty, (also iTerm2 on MacOS)
- `$TERM`: xterm-kitty, (also something else on MacOS)

### Steps to reproduce using `nvim -u NORC`

I don't have a deterministic reproducer for now, unfortunately. This tends to happen after running `:grep something` several times, where my grepprg is `git grep -n`. 

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

Pressing Ctrl-L doesn't fix the issue, only clears the "corrupted" bottom-half of the screen (but the window still keeps looking as if it was split). The bottom "split" is not possible to switch into by e.g. pressing Ctrl-W key combos. This "corrupted split" stays on a tab. After switching to it from a different tab, it keeps displaying the bottom half of that other tab. See the animated gif below.

![neovim problem](https://user-images.githubusercontent.com/273837/98606705-036a7e80-22e8-11eb-9c74-90ce18e09e16.gif)

### Expected behaviour

No weird fake corrupted "split" should suddenly appear on screen after running `:grep`.

**Comment by zeertzjq** [comment]
Does this bug still exist?
