### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by cweagans** [neovim/neovim#13271]
I have no bug to report nor feature to request.

I just want to relay my thanks to everyone working on Neovim over the years. You've all done some incredible things. The entire vim ecosystem is better because of Neovim's existence, and using neovim as my daily driver is just a _joyful_ experience. It provides everything I need out of a modern editor + all the power and flexibility of vim.

So thanks!

**Comment by cweagans** [comment]
(also no hard feelings if you need/want to close this: I know it's important to keep issue queues tidy)

**Comment by teto** [comment]
> it provides everything I need out of a modern editor + all the power and flexibility of vim.

there is so much to improve still.  It really is a collective effort and the neovim development model really shows the power of FOSS.
