### ISSUE TITLE
foldtext or (folded line) syntax highlighting?

### ISSUE THREAD

**Issue by tamis-laan** [neovim/neovim#13277]
I'm using TreeSitter and I'm folding code based on syntax. I have a custom foldtext function that does the following:

Original:
``` javascript
      if(result.ok) {
        this.status = {code:"done",msg:"registration success"}
        return {status:result.status,content: await result.json()}
      }
```

Folded:
```
      if(result.ok) { [2l] }
```

However the code `if(result.ok) { [2l] }` is not syntax highlighted. Is there a way to turn syntax highlighting on for folded text?

**Comment by vigoux** [comment]
Hi and thanks for reporting, I think that what you are referring is akin to https://github.com/neovim/neovim/issues/12649, am I right ?

If that's the case, I think the discussion should be held there.

**Comment by tamis-laan** [comment]
Yes in fact someone is working to solve this problem https://github.com/neovim/neovim/pull/12515
