### ISSUE TITLE
LSP: suppress error when lsp command cannot be found

### ISSUE THREAD

**Issue by zegervdv** [neovim/neovim#13282]
When an LSP command cannot be found it raises an error.
Sometimes when working on a different machine, the LSP is not available and this error is expected.

Is there a way to suppress the error when it is expected?

- `nvim --version`: v0.5.0-35325dd
- `vim -u DEFAULTS` (version: ) behaves differently?: yes, LSP feature
- Operating system/version: Ubuntu 20.04
- Terminal name/version: Kitty
- `$TERM`: zsh

### Steps to reproduce using `nvim -u NORC`

not applicable

### Actual behaviour

Shows an error when the lsp command cannot be found:
```
Error detected while processing FileType Autocommands for "systemverilog":
E5108: Error executing lua ...ovim/HEAD-35325dd/share/nvim/runtime/lua/vim/lsp/rpc.lua:307: The given command "veridian" is not executable.
```

### Expected behaviour

Suppress the error or make it less intrusive.

**Comment by teto** [comment]
I would like to plug my own handler for these messages, to display them in a popup (floating window) instead (like vscode does) so that it doesn't interrupt my flow. Ideally I would like to have a notification provider so that we could forward these to system popups.

**Comment by mjlbach** [comment]
@zegervdv Were you using nvim-lspconfig? because I closed this in https://github.com/neovim/nvim-lspconfig/pull/670

**Comment by zegervdv** [comment]
I am using nvim-lspconfig. I was working around it by adding `if vim.fn.executable('cmd')` checks around my lsp config.

**Comment by mjlbach** [comment]
Great! I do that in nvim-lspconfig now, so your workaround shouldn't be necessary 

https://github.com/neovim/nvim-lspconfig/pull/670/files#diff-9e30880c16142e9d50a64563fd1260aa9f851b782dd74678163e151b93878568R264

(don't worry, the print is not actually printed).

**Comment by zegervdv** [comment]
I'll update then :)
Thanks
