### ISSUE TITLE
treesitter: Predicate for contains optimized for lookup

### ISSUE THREAD

**Issue by tjdevries** [neovim/neovim#13296]
Currently, `#contains?` loops over the list of predicates and checks each one.

I think there should be a `#keyword?` or something that allows for a ton of items to be passed in to a predicate more easily (for example, when you have 100s of keywords such as in css [ cc @rockerboo ] ).

Currently, contains is:

```lua
  ["contains?"] = function(match, _, source, predicate)
    local node = match[predicate[2]]
    local node_text = M.get_node_text(node, source)

    for i=3,#predicate do
      if string.find(node_text, predicate[i], 1, true) then
        return true
      end
    end

    return false
  end
```
I have a few ideas for implementation, but maybe I'm just missing a better way to do this @vigoux

**Comment by vigoux** [comment]
I have been thinking of moving the `eq?` predicate to this form too. What are the implementations you are thinking about ?

**Comment by rockerBOO** [comment]
This is my initial try (doesn't work correctly).

https://github.com/rockerBOO/nvim-treesitter/commit/357dab3011f9606855a347960cff48847796104c

You can see how Atom is doing it with match regex. 

https://github.com/atom/language-css/blob/master/grammars/tree-sitter-css.cson#L77
https://github.com/atom/language-css/blob/master/grammars/css.cson#L1432

Using match may be better.

**Comment by vigoux** [comment]
We also have a `match?` operator too, even two depending on the complexity of the match :wink:

**Comment by vigoux** [comment]
Comming back to this, I think that one good thing would be to optimize the `eq?` predicate to do this kind of lookup thing you suggested.

I am going to try to work on that.

**Comment by vigoux** [comment]
Hi everyone, this has been fixed by adding the `#any-of?` predicate a while ago, so I am closing this now.
