### ISSUE TITLE
When `'winheight'` is set, `nvim_open_win()` does not work well.

### ISSUE THREAD

**Issue by tamago324** [neovim/neovim#13298]
- `nvim --version`: `NVIM v0.5.0-837-g0798ad3a3`
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: `Ubuntu 18.04` (WSL2)
- Terminal name/version: [wsltty](https://github.com/mintty/wsltty)
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```vim
" minimal_vimrc
set winheight=20

let opts = {
\  'height': 1,
\  'col': 5,
\  'row': 1,
\  'relative': 'editor',
\  'style': 'minimal',
\  'width': 15
\}

let bufnr = nvim_create_buf(v:false, v:true)
call nvim_buf_set_lines(bufnr, 0, -1, v:true, ['hello world'])
let win_id = nvim_open_win(bufnr, v:true, opts)
```

1. `nvim -u NORC`
2. `:so minimal_vimrc`

### Actual behaviour

The height of the floating window changes to the 20 specified in `set winheight=20`, instead of the 1 in `height` passed in the `nvim_open_win()` argument.

<img src="https://user-images.githubusercontent.com/16581287/99188683-9dc33a00-27a0-11eb-909e-d35bf0dbf982.png" width=250>

### Expected behaviour

The height of the floating window opened by `nvim_open_win()` should be the height of `height` specified by the argument.

<img src="https://user-images.githubusercontent.com/16581287/99188799-38bc1400-27a1-11eb-98f8-f4f7c9191c30.png" width=250>

---

I encountered this when I was using https://github.com/nvim-telescope/telescope.nvim.
Is this behavior correct?

**Comment by alecgirman** [comment]
I was able to reproduce this in WSL2 with Ubuntu 20.04.  In addition, setting winwidth does not cause unexpected behavior, but only winheight does.

**Comment by vigoux** [comment]
Reproduced on my side too, will try to fix it.

**Comment by vigoux** [comment]
Calling `nvim_win_set_config` after creating the window correctly sets everything, so that must be an issue at creation only.

**Comment by seandewar** [comment]
Issue seems to happen in `win_enter_ext()` in `window.c:4612` in the block:
```c
  /* set window height to desired minimal value */
  if (curwin->w_height < p_wh && !curwin->w_p_wfh)
    win_setheight((int)p_wh);
  else if (curwin->w_height == 0)
    win_setheight(1);
```

Hope this helps!

**Comment by vigoux** [comment]
Just came to the same conclusions, I think that this is the correct fix for this issue.

**Comment by tamago324** [comment]
Thank you!
