### ISSUE TITLE
`dvk` is not the same as `dv:normal! k`

### ISSUE THREAD

**Issue by subnut** [neovim/neovim#13309]
- `nvim --version`:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? __NO__
- Operating system/version: Arch Linux fully updated
- Terminal name/version: kitty latest version
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

- `nvim -u NORC`
- paste this -
```
Lorem ipsum dolor sit amet.
LLoorreemm  ipsum ddoolloorr  ssiitt  aammeett.
              ^
```
- place the cursor at the `m` above the `^`
- Type `dvk`
- result should be -
```
Lorem ipsum dosum ddoolloorr  ssiitt  aammeett.
              ^
```
- <key>u</key> (undo)
- position the cursor as shown in step 3
- type this, and then hit <key>Enter</key>
```
dv:normal! k
```

### Actual behaviour
```
Lorem ipsum doum ddoolloorr  ssiitt  aammeett.
              ^
```

### Expected behaviour
```
Lorem ipsum dosum ddoolloorr  ssiitt  aammeett.
              ^
```

**Comment by dundargoc** [comment]
lol, didn't know you could chain operator pending mode into a command. Is this even intended? This feels almost like an accident. In my mind the most natural behavior would be that the operator mode would be canceled and that `:normal! k` is interpreted as a separate command. As an example, if we used "`dv:ls` instead of `dv:normal! k`, then I'd think the `dv` would be ignored since it doesn't make sense to combine it with `:ls`.

**Comment by zeertzjq** [comment]
Actually `:normal` saves and restores operator-pending state.

**Comment by dundargoc** [comment]
As in that it's intended? Weird.

Anyway, this isn't related to `:normal`. Typing `dv:ls`, `dv:echo` or any command after `dv` removes the characterthe cursor is at, which is what we're seeing with `dv:normal! k`.

**Comment by dundargoc** [comment]
Hmmm, also weird that `dv` isn't documented...not even sure what it is supposed to do.

**Comment by zeertzjq** [comment]
`:h forced-motion`

**Comment by zeertzjq** [comment]
It is mentioned in source code that:
```c
  if (cap->oap->op_type != OP_NOP) {
    // Using ":" as a movement is charwise exclusive.
    cap->oap->motion_type = kMTCharWise;
    cap->oap->inclusive = false;
```
But it doesn't seem documented.

**Comment by zeertzjq** [comment]
Oh, it's documented here:
```
You can use a ":" command for a motion.  For example "d:call FindEnd()".
But this can't be repeated with "." if the command is more than one line.
This can be repeated: >
	d:call search("f")<CR>
This cannot be repeated: >
	d:if 1<CR>
	   call search("f")<CR>
	endif<CR>
Note that when using ":" any motion becomes charwise exclusive.
```
