### ISSUE TITLE
Online doc is unreadable on smartphone compared to vim doc

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#13306]
The online doc of neovim is unreadable on my Android. The layout is completely broken.

The following pic is what I see for neovim doc (link [here](https://neovim.io/doc/user/)).

[![DVCwlt.jpg](https://s3.ax1x.com/2020/11/17/DVCwlt.jpg)](https://imgchr.com/i/DVCwlt)

Below is the vim doc viewed on my phone ([here](https://vimhelp.org/)):

[![DViSvq.jpg](https://s3.ax1x.com/2020/11/17/DViSvq.jpg)](https://imgchr.com/i/DViSvq)

**Comment by bfredl** [comment]
You can easily get the second layout (no wrapping) by using the "desktop view" option in Android.
