### ISSUE TITLE
Highlight on yank with virtualedit=all gets offset if cursor is beyond line end.

### ISSUE THREAD

**Issue by shade-of-noon** [neovim/neovim#13317]
### Version
- `nvim --version`: `neovim-nightly` from the AUR ([nvim-version.txt](https://github.com/neovim/neovim/files/5561095/nvim-version.txt))
- Operating system/version: Arch Linux
- Terminal name/version: Alacritty 0.6.0-dev
- `$TERM`: alacritty

### Steps to reproduce using `nvim -u NORC`

Starting from `nvim -u NORC`:

```
:set virtualedit=all
:au TextYankPost * silent! lua vim.highlight.on_yank()
```

Now move the cursor a few characters beyond the end of a nonempty line and copy the whole line via `yy` or `Y`.

### Actual behaviour

Pressing `yy` or `Y` only highlights part of the line: a number of characters equal to the cursor's offset doesn't get highlighted at the start of the line.

### Expected behaviour

When I press `yy` the whole line gets highlighted (not counting the "virtual" part between cursor and the EOL).

**Comment by clason** [comment]
Good catch, I never tested that. Can you try #13320 ?

**Comment by shade-of-noon** [comment]
Hey, thanks @clason.

I tested your commit and it does fix this issue. Nonetheless, another thing I noticed is that there's trouble for visual block and `virtualedit=all`: if the upper corner of the selection is in a virtual position (beyond EOL, etc.) the highlighting doesn't work properly.

**Comment by clason** [comment]
That `silent!` in the snippet was there for a reason ;)

Can you try again?

**Comment by shade-of-noon** [comment]
> That `silent!` in the snippet was there for a reason ;)
> 
> Can you try again?

I don't understand what you mean here, can you elaborate. Sorry.
 
---

BTW, I was checking using `vim.highlight.range()` by itself and found that it errors out with `index out of range` whenever the visual block has the upper edge of the selection beyond EOL. For example, I tested with this
```
lua vim.highlight.range(0,1,'Search',{30,20},{30,25}, "\0225")
```
where line 31 (one-based indexing) is assumed to end before column 55.

**Comment by clason** [comment]
Yes, exactly, and I just fixed that (I hope) in the PR I linked above!

**Comment by shade-of-noon** [comment]
I checked, when doing visual block the yank highlighting doesn't take into account the virtual offset, i.e. the highlighted block ends up $offset characters to the left of where the actual yank took place. I didn't see issues with the other operations (yy, v, V, etc).

**Comment by clason** [comment]
Hmm, can you give an exact repro (minimal text, and exact steps)? I didn't see any such effects in my tests.

**Comment by shade-of-noon** [comment]
>  Hmm, can you give an exact repro (minimal text, and exact steps)? I didn't see any such effects in my tests.

Oh, now I saw your most recent modifications to `highlight.lua`. Those I hadn't seen and are likely to fix the problem. I'll check the changes in a few hours time (slow internet connection right now). Thank you, again.

**Comment by shade-of-noon** [comment]
So, I managed to check your latest changes against the master branch and… it works! I guess #13320 closes this issue, awesome.

**Comment by shade-of-noon** [comment]
Oops, hit the "Close issue" button before the commits get merged.

**Comment by clason** [comment]
Glad it helps, and thanks for testing (and reporting)! 

I'll leave the issue open until the PR is merged, though.

**Comment by clason** [comment]
No longer reproducible on master; feel free to reopen with new reproducing steps.
