### ISSUE TITLE
"/var/folders/kq/k_ly_h8j4wv5zvd9xjlgs3p80000gn/T//tutorJ29mPj" 968 lines, 42309  characters Press ENTER or type command to continue

### ISSUE THREAD

**Issue by flexboni** [neovim/neovim#13325]
- `nvim --version`: NVIM v0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: macOS Catalina version 10.15.7
- Terminal name/version: iterms2 build 3.4.0
- `$TERM`:

![image](https://user-images.githubusercontent.com/29271126/99622482-984e4400-2a6d-11eb-8d19-8d0b7fd5fba0.png)

How can i fix it??

**Comment by jdhao** [comment]
You haven't provided the steps to reproduce.
