### ISSUE TITLE
python2 is deprecated - Neovim roadmap to get rid of it

### ISSUE THREAD

**Issue by EdmundsEcho** [neovim/neovim#13323]
I'm more and more thankful I chose `vim` over the alternatives (going back 30 years now).  `neovim` is exactly as you all first described it when I first started using it about 7 or so years ago.  Thank you!

One thorn in my side - upgrading python.  Every time it seems.  Today I upgraded `gem` per the `checkhealth` request and for whatever reason it had me problem solve my install of python (using `pyenv` and `fishshell` has its own quirks)... I digress. But, it does describe my context for this request.

Might it be possible to post some sort of plan for what to expect for how neovim will ultimately remove or otherwise treat differently anything to do with `python` aka `python2`.  For instance, at what point will `python` start being an alias for `python3`?  Are there hidden dependencies by plugins that somehow we need to keep an eye out for...

Thanks in advance!

\- E

**Comment by bfredl** [comment]
at some point we will remove `:python`. which means that by preexisting Ex name resolution rules, `:python` will be recognized as an abbreviation for `:pythons3`

**Comment by EdmundsEcho** [comment]
I have read other issue posts on how to configure neovim to ignore i.e., not look for, python2.  I have tried a few settings to get the `:checkhealth` report to ignore/not even try, to look for python2 to no avail.  Part of the confusion is the use of `python`; an alias to...  At the time, there were constraints given the need to support p2.  I suspect, we might be in a good position to be explicit in our configuration about the choice to operate in a p3 only.  Is that right?

**Comment by bfredl** [comment]
well currently you need to make sure to use `python3` explicitly, as just `python` without number refers to the python2 provider specifically. Though @mhinz was maybe planning to change that soon?

**Comment by Julian** [comment]
In the Python ecosystem, `python` unqualified still refers to Python2 (as recommended by [PEP394](https://www.python.org/dev/peps/pep-0394/))

There's some discussion on whether that'll at some point change -- personally I hope it never does, as there's not much benefit to doing so IMHO, and it'll cause issues again when we have `python4` binaries, but at least for now it hasn't.

So I'd hope it'd always stay `:python3` in neovim too personally, though yeah unambiguous-prefixing maybe makes `:python` find `:python3` and then problem solved for most users who don't care about `python2` ever, but for anyone who continues to need both nothing breaks.

There are still implementations of Python that support Python2 and will continue to do so, so again selfishly I hope it never becomes *impossible* to use Python2 with neovim unless there's significant burden.

**Comment by EdmundsEcho** [comment]
Your point is well-taken... and in fact is exactly right in my view.  

Caveat: I disagree with PEP394 re keeping the generic `python` alive.  For non-python spec readers, it's not a given.

Consistent with what I believe is your (@Julian) main point, I might suggest that the roadmap *drop altogether* the use of the unqualified `python` alias.  In the spirit  of 'fail-fast' to get it right that much faster :)  I would suggest the roadmap provide a deprecation warning for use of the generic *alias*.  After an acceptable period of time, drop it.  

The user fix based on python usage: 

1. python3 users: keep config as is
2. python2 users: change `python` to `python2`

This way, any service extensions with python dependencies can be made explicitly clear... and configurable.  For instance, despite my trying various proposed solutions, my `checkhealth` refuses to ignore the fact that I don't support every version of python :)

\- E

**Comment by Julian** [comment]
Yes I'd agree with your rephrasing/proposal!

**Comment by dundargoc** [comment]
python 2 support has been removed.
