### ISSUE TITLE
LSP - Floating info windows do not apply NormalFloat hightlight group

### ISSUE THREAD

**Issue by weilbith** [neovim/neovim#13327]
- `nvim --version`: `v0.5.0-834-g7c4f34966`
- language server name/version: not relevant
- Operating system/version: `5.9.4-arch1-1`

### Actual behaviour

The floating window used by the LSP modules to show hover hints, diagnostics, previews etc. uses the `NormalInactive` highlight group. At least after long search, when I change this highlight group definition and use the LSP hover again, this takes the new defined color for the background. Depending on the colorscheme this highlight group is usually always hard to distinguish from the rest of the current buffer and is not really helpful. Also it would be horrible to change the colors only for these floating windows and then end up with ugly inactive windows.

### Expected behaviour

It uses the `NormalFloat` highlight group instead and eventually expose a new highlight group used for these windows.

**Comment by rockerBOO** [comment]
@tjdevries I think the default group for the popup `NormalFloat` would be better than `NormalInactive`

**Comment by weilbith** [comment]
Eventually you could also add another new highlight group that just defaults to `NormalFloat`. Just to give the user all possibilities. I mean it would not hurt to have one more highlight group after all. :shrug:

**Comment by weilbith** [comment]
I don't use the native LSP functions anymore. As nobody else seem to complain about it, I'll close the issue for now. If there is some interest again it can be re-opened at any time.
