### ISSUE TITLE
Neovim does not report errors when the LSP crashes

### ISSUE THREAD

**Issue by poliorcetics** [neovim/neovim#13344]
- `nvim --version`:

```
NVIM v0.5.0-e192a4600
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201121-34675-1cv6t9/build/config -I/tmp/neovim-20201121-34675-1cv6t9/src -I/usr/local/include -I/tmp/neovim-20201121-34675-1cv6t9/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201121-34675-1cv6t9/build/src/nvim/auto -I/tmp/neovim-20201121-34675-1cv6t9/build/include
Compiled by alexis@Alexis-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-e192a46/share/nvim"

Run :checkhealth for more info
```

- language server name/version: `rust-analyzer cadf0e9`
- Operating system/version: `macOS Catalina 10.15.7`

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: pyls: configuration checked.

</details>

<details>
<summary>lsp.log</summary>

[ WARN ] 2020-11-22T02:23:41+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:85 ]    "method rust-analyzer/inlayHints is not supported by any of the servers registered for the current buffer"
[ WARN ] 2020-11-22T02:23:41+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:85 ]    "method rust-analyzer/inlayHints is not supported by any of the servers registered for the current buffer"
[ WARN ] 2020-11-22T02:23:41+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:85 ]    "method rust-analyzer/inlayHints is not supported by any of the servers registered for the current buffer"
[ ERROR ] 2020-11-22T02:23:41+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]  "rpc"   "rust-analyzer" "stderr"    "[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.2/benches/01_default.rs\n[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.2/benches/02_simple.rs\n"
[ ERROR ] 2020-11-22T02:23:41+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]  "rpc"   "rust-analyzer" "stderr"    "[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.2/benches/03_complex.rs\n[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.2/benches/04_new_help.rs\n[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.2/benches/05_ripgrep.rs\n[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.2/benches/06_rustup.rs\n"
[ ERROR ] 2020-11-22T02:23:41+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]  "rpc"   "rust-analyzer" "stderr"    "[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.1.2/examples/json.rs\n[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.1.2/examples/s_expression.rs\n"
[ ERROR ] 2020-11-22T02:23:41+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]  "rpc"   "rust-analyzer" "stderr"    "[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.1.2/examples/string.rs\n"
[ ERROR ] 2020-11-22T02:23:41+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]  "rpc"   "rust-analyzer" "stderr"    "[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.1.2/benches/arithmetic.rs\n[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.1.2/benches/http.rs\n"
[ ERROR ] 2020-11-22T02:23:41+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]  "rpc"   "rust-analyzer" "stderr"    "[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.1.2/benches/ini.rs\n[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.1.2/benches/ini_complete.rs\n[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.1.2/benches/ini_str.rs\n[ERROR rust_analyzer::reload] failed to load /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.1.2/benches/json.rs\n"
[ DEBUG ] 2020-11-22T02:23:46+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:477 ]  "decoded"   {  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs",    version = 0  }}
[ DEBUG ] 2020-11-22T02:23:46+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:471 ]  "notification"  "textDocument/publishDiagnostics"   {  diagnostics = {},  uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs",  version = 0}
[ DEBUG ] 2020-11-22T02:23:46+0100 ] ...HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/handlers.lua:297 ]  "default_handler"   "textDocument/publishDiagnostics"   {  client_id = 1,  params = {    diagnostics = {},    uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs",    version = 0  }}
[ DEBUG ] 2020-11-22T02:23:49+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:670 ]  "LSP[rust_analyzer]"    "client.request"    1   "textDocument/hover"    {  position = {    character = 29,    line = 24  },  textDocument = {    uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"  }}   <function 1>    1
[ DEBUG ] 2020-11-22T02:23:49+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:376 ]  "rpc.send.payload"  {  id = 2,  jsonrpc = "2.0",  method = "textDocument/hover",  params = {    position = {      character = 29,      line = 24    },    textDocument = {      uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"    }  }}
[ DEBUG ] 2020-11-22T02:23:49+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:477 ]  "decoded"   {  id = 2,  jsonrpc = "2.0",  result = {    contents = {      kind = "markdown",      value = '\n```rust\nstd::process::Command\n```\n\n```rust\npub fn spawn(&mut self) -> io::Result<Child>\n```\n\n---\n\nExecutes the command as a child process, returning a handle to it.\n\nBy default, stdin, stdout and stderr are inherited from the parent.\n\n# Examples\n\nBasic usage:\n\n```rust\nuse std::process::Command;\n\nCommand::new("ls")\n        .spawn()\n        .expect("ls command failed to start");\n```'    },    range = {      end = {        character = 32,        line = 24      },      start = {        character = 27,        line = 24      }    }  }}
[ DEBUG ] 2020-11-22T02:23:49+0100 ] ...HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/handlers.lua:297 ]  "default_handler"   "textDocument/hover"    {  bufnr = 1,  client_id = 1,  params = {    contents = {      kind = "markdown",      value = '\n```rust\nstd::process::Command\n```\n\n```rust\npub fn spawn(&mut self) -> io::Result<Child>\n```\n\n---\n\nExecutes the command as a child process, returning a handle to it.\n\nBy default, stdin, stdout and stderr are inherited from the parent.\n\n# Examples\n\nBasic usage:\n\n```rust\nuse std::process::Command;\n\nCommand::new("ls")\n        .spawn()\n        .expect("ls command failed to start");\n```'    },    range = {      end = {        character = 32,        line = 24      },      start = {        character = 27,        line = 24      }    }  }}
[ WARN ] 2020-11-22T02:23:49+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:85 ]    "method rust-analyzer/inlayHints is not supported by any of the servers registered for the current buffer"
[ WARN ] 2020-11-22T02:23:49+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:85 ]    "method rust-analyzer/inlayHints is not supported by any of the servers registered for the current buffer"
[ DEBUG ] 2020-11-22T02:23:49+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:670 ]  "LSP[rust_analyzer]"    "client.request"    1   "rust-analyzer/inlayHints"  {  textDocument = {    uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"  }} <function 1>    1
[ DEBUG ] 2020-11-22T02:23:49+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:376 ]  "rpc.send.payload"  {  id = 3,  jsonrpc = "2.0",  method = "rust-analyzer/inlayHints",  params = {    textDocument = {      uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"    }  }}
[ DEBUG ] 2020-11-22T02:23:49+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:670 ]  "LSP[rust_analyzer]"    "client.request"    1   "rust-analyzer/inlayHints"  {  textDocument = {    uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"  }} <function 1>    1
[ DEBUG ] 2020-11-22T02:23:49+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:376 ]  "rpc.send.payload"  {  id = 4,  jsonrpc = "2.0",  method = "rust-analyzer/inlayHints",  params = {    textDocument = {      uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"    }  }}
[ DEBUG ] 2020-11-22T02:23:49+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:477 ]  "decoded"   {  id = 3,  jsonrpc = "2.0",  result = { {      kind = "TypeHint",      label = "Command",      range = {        end = {          character = 23,          line = 13        },        start = {          character = 12,          line = 13        }      }    }, {      kind = "ParameterHint",      label = "program",      range = {        end = {          character = 44,          line = 13        },        start = {          character = 39,          line = 13        }      }    }, {      kind = "ParameterHint",      label = "cfg",      range = {        end = {          character = 34,          line = 17        },        start = {          character = 20,          line = 17        }      }    }, {      kind = "ChainingHint",      label = "&mut Command",      range = {        end = {          character = 34,          line = 16        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "ParameterHint",      label = "cfg",      range = {        end = {          character = 33,          line = 16        },        start = {          character = 19,          line = 16        }      }    }, {      kind = "ChainingHint",      label = "&mut Command",      range = {        end = {          character = 25,          line = 15        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "ChainingHint",      label = "Command",      range = {        end = {          character = 15,          line = 14        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "TypeHint",      label = "OsString",      range = {        end = {          character = 28,          line = 19        },        start = {          character = 20,          line = 19        }      }    }, {      kind = "ParameterHint",      label = "key",      range = {        end = {          character = 42,          line = 20        },        start = {          character = 24,          line = 20        }      }    }, {      kind = "ParameterHint",      label = "val",      range = {        end = {          character = 52,          line = 20        },        start = {          character = 44,          line = 20        }      }    }, {      kind = "TypeHint",      label = "Output",      range = {        end = {          character = 18,          line = 33        },        start = {          character = 12,          line = 33        }      }    }, {      kind = "ChainingHint",      label = "Result<Output, Error>",      range = {        end = {          character = 31,          line = 35        },        start = {          character = 21,          line = 33        }      }    }, {      kind = "ChainingHint",      label = "Child",      range = {        end = {          character = 18,          line = 34        },        start = {          character = 21,          line = 33        }      }    }, {      kind = "ChainingHint",      label = "Fzf",      range = {        end = {          character = 25,          line = 33        },        start = {          character = 21,          line = 33        }      }    }, {      kind = "ParameterHint",      label = "vec",      range = {        end = {          character = 54,          line = 40        },        start = {          character = 41,          line = 40        }      }    }, {      kind = "TypeHint",      label = "i32",      range = {        end = {          character = 27,          line = 49        },        start = {          character = 17,          line = 49        }      }    } }}
[ DEBUG ] 2020-11-22T02:23:49+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:477 ]  "decoded"   {  id = 4,  jsonrpc = "2.0",  result = { {      kind = "TypeHint",      label = "Command",      range = {        end = {          character = 23,          line = 13        },        start = {          character = 12,          line = 13        }      }    }, {      kind = "ParameterHint",      label = "program",      range = {        end = {          character = 44,          line = 13        },        start = {          character = 39,          line = 13        }      }    }, {      kind = "ParameterHint",      label = "cfg",      range = {        end = {          character = 34,          line = 17        },        start = {          character = 20,          line = 17        }      }    }, {      kind = "ChainingHint",      label = "&mut Command",      range = {        end = {          character = 34,          line = 16        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "ParameterHint",      label = "cfg",      range = {        end = {          character = 33,          line = 16        },        start = {          character = 19,          line = 16        }      }    }, {      kind = "ChainingHint",      label = "&mut Command",      range = {        end = {          character = 25,          line = 15        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "ChainingHint",      label = "Command",      range = {        end = {          character = 15,          line = 14        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "TypeHint",      label = "OsString",      range = {        end = {          character = 28,          line = 19        },        start = {          character = 20,          line = 19        }      }    }, {      kind = "ParameterHint",      label = "key",      range = {        end = {          character = 42,          line = 20        },        start = {          character = 24,          line = 20        }      }    }, {      kind = "ParameterHint",      label = "val",  ...skipping...
line = 40        },        start = {          character = 41,          line = 40        }      }    }, {      kind = "TypeHint",      label = "i32",      range = {        end = {          character = 27,          line = 49        },        start = {          character = 17,          line = 49        }      }    } }}
[ DEBUG ] 2020-11-22T02:23:53+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:670 ]  "LSP[rust_analyzer]"    "client.request"    1   "rust-analyzer/inlayHints"  {  textDocument = {    uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"  }} <function 1>    1
[ DEBUG ] 2020-11-22T02:23:53+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:376 ]  "rpc.send.payload"  {  id = 6,  jsonrpc = "2.0",  method = "rust-analyzer/inlayHints",  params = {    textDocument = {      uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"    }  }}
[ DEBUG ] 2020-11-22T02:23:53+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:477 ]  "decoded"   {  id = 6,  jsonrpc = "2.0",  result = { {      kind = "TypeHint",      label = "Command",      range = {        end = {          character = 23,          line = 13        },        start = {          character = 12,          line = 13        }      }    }, {      kind = "ParameterHint",      label = "program",      range = {        end = {          character = 44,          line = 13        },        start = {          character = 39,          line = 13        }      }    }, {      kind = "ParameterHint",      label = "cfg",      range = {        end = {          character = 34,          line = 17        },        start = {          character = 20,          line = 17        }      }    }, {      kind = "ChainingHint",      label = "&mut Command",      range = {        end = {          character = 34,          line = 16        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "ParameterHint",      label = "cfg",      range = {        end = {          character = 33,          line = 16        },        start = {          character = 19,          line = 16        }      }    }, {      kind = "ChainingHint",      label = "&mut Command",      range = {        end = {          character = 25,          line = 15        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "ChainingHint",      label = "Command",      range = {        end = {          character = 15,          line = 14        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "TypeHint",      label = "OsString",      range = {        end = {          character = 28,          line = 19        },        start = {          character = 20,          line = 19        }      }    }, {      kind = "ParameterHint",      label = "key",      range = {        end = {          character = 42,          line = 20        },        start = {          character = 24,          line = 20        }      }    }, {      kind = "ParameterHint",      label = "val",      range = {        end = {          character = 52,          line = 20        },        start = {          character = 44,          line = 20        }      }    }, {      kind = "TypeHint",      label = "Output",      range = {        end = {          character = 18,          line = 33        },        start = {          character = 12,          line = 33        }      }    }, {      kind = "ChainingHint",      label = "Result<Output, Error>",      range = {        end = {          character = 31,          line = 35        },        start = {          character = 21,          line = 33        }      }    }, {      kind = "ChainingHint",      label = "Child",      range = {        end = {          character = 18,          line = 34        },        start = {          character = 21,          line = 33        }      }    }, {      kind = "ChainingHint",      label = "Fzf",      range = {        end = {          character = 25,          line = 33        },        start = {          character = 21,          line = 33        }      }    }, {      kind = "ParameterHint",      label = "vec",      range = {        end = {          character = 54,          line = 40        },        start = {          character = 41,          line = 40        }      }    }, {      kind = "TypeHint",      label = "i32",      range = {        end = {          character = 27,          line = 49        },        start = {          character = 17,          line = 49        }      }    } }}
[ DEBUG ] 2020-11-22T02:23:57+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:670 ]  "LSP[rust_analyzer]"    "client.request"    1   "rust-analyzer/inlayHints"  {  textDocument = {    uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"  }} <function 1>    1
[ DEBUG ] 2020-11-22T02:23:57+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:376 ]  "rpc.send.payload"  {  id = 7,  jsonrpc = "2.0",  method = "rust-analyzer/inlayHints",  params = {    textDocument = {      uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"    }  }}
[ DEBUG ] 2020-11-22T02:23:57+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:477 ]  "decoded"   {  id = 7,  jsonrpc = "2.0",  result = { {      kind = "TypeHint",      label = "Command",      range = {        end = {          character = 23,          line = 13        },        start = {          character = 12,          line = 13        }      }    }, {      kind = "ParameterHint",      label = "program",      range = {        end = {          character = 44,          line = 13        },        start = {          character = 39,          line = 13        }      }    }, {      kind = "ParameterHint",      label = "cfg",      range = {        end = {          character = 34,          line = 17        },        start = {          character = 20,          line = 17        }      }    }, {      kind = "ChainingHint",      label = "&mut Command",      range = {        end = {          character = 34,          line = 16        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "ParameterHint",      label = "cfg",      range = {        end = {          character = 33,          line = 16        },        start = {          character = 19,          line = 16        }      }    }, {      kind = "ChainingHint",      label = "&mut Command",      range = {        end = {          character = 25,          line = 15        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "ChainingHint",      label = "Command",      range = {        end = {          character = 15,          line = 14        },        start = {          character = 8,          line = 14        }      }    }, {      kind = "TypeHint",      label = "OsString",      range = {        end = {          character = 28,          line = 19        },        start = {          character = 20,          line = 19        }      }    }, {      kind = "ParameterHint",      label = "key",      range = {        end = {          character = 42,          line = 20        },        start = {          character = 24,          line = 20        }      }    }, {      kind = "ParameterHint",      label = "val",      range = {        end = {          character = 52,          line = 20        },        start = {          character = 44,          line = 20        }      }    }, {      kind = "TypeHint",      label = "Output",      range = {        end = {          character = 18,          line = 33        },        start = {          character = 12,          line = 33        }      }    }, {      kind = "ChainingHint",      label = "Result<Output, Error>",      range = {        end = {          character = 31,          line = 35        },        start = {          character = 21,          line = 33        }      }    }, {      kind = "ChainingHint",      label = "Child",      range = {        end = {          character = 18,          line = 34        },        start = {          character = 21,          line = 33        }      }    }, {      kind = "ChainingHint",      label = "Fzf",      range = {        end = {          character = 25,          line = 33        },        start = {          character = 21,          line = 33        }      }    }, {      kind = "ParameterHint",      label = "vec",      range = {        end = {          character = 54,          line = 40        },        start = {          character = 41,          line = 40        }      }    }, {      kind = "TypeHint",      label = "i32",      range = {        end = {          character = 27,          line = 49        },        start = {          character = 17,          line = 49        }      }    } }}
[ DEBUG ] 2020-11-22T02:23:59+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:670 ]  "LSP[rust_analyzer]"    "client.request"    1   "rust-analyzer/inlayHints"  {  textDocument = {    uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"  }} <function 1>    1
[ DEBUG ] 2020-11-22T02:23:59+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:376 ]  "rpc.send.payload"  {  id = 8,  jsonrpc = "2.0",  method = "rust-analyzer/inlayHints",  params = {    textDocument = {      uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"    }  }}
[ DEBUG ] 2020-11-22T02:23:59+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:376 ]  "rpc.send.payload"  {  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///Users/alexis/Projects/rust/zoxide/src/fzf.rs"    }  }}
[ ERROR ] 2020-11-22T02:23:59+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]  "rpc"   "rust-analyzer" "stderr"    "thread 'main' panicked at 'Invalid notification\nMethod: textDocument/didSave\n error: missing field `version`', /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.5.0/src/msg.rs:192:17\nstack backtrace:\n"
[ ERROR ] 2020-11-22T02:23:59+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]  "rpc"   "rust-analyzer" "stderr"    "   0: _rust_begin_unwind\n   1: std::panicking::begin_panic_fmt\n   2: lsp_server::msg::Notification::extract::{{closure}}\n   3: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::on_notification\n   4: rust_analyzer::main_loop::"
[ ERROR ] 2020-11-22T02:23:59+0100 ] ...ovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]  "rpc"   "rust-analyzer" "stderr"    "<impl rust_analyzer::global_state::GlobalState>::handle_event\n   5: rust_analyzer::main_loop::main_loop\n   6: rust_analyzer::run_server\n   7: rust_analyzer::try_main\n   8: rust_analyzer::main\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
[ WARN ] 2020-11-22T02:24:00+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:85 ]    "method textDocument/hover is not supported by any of the servers registered for the current buffer"
[ DEBUG ] 2020-11-22T02:24:00+0100 ] ...HEAD-e192a46/share/nvim/runtime/lua/vim/lsp/handlers.lua:297 ]  "default_handler"   "textDocument/hover"    {  err = {    code = -32601,    message = "method textDocument/hover is not supported by any of the servers registered for the current buffer",    <metatable> = {      __tostring = <function 1>    }  },  params = 0}
[ INFO ] 2020-11-22T02:24:02+0100 ] ...r/neovim/HEAD-e192a46/share/nvim/runtime/lua/vim/lsp.lua:974 ]   "exit_handler"  {}
</details>

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

I'm not sure how to do it without pasting my config (taken from the README of `nvim-lspconfig`) for `rust-analyzer`.

### Actual behaviour

With the [`zoxide`](https://github.com/ajeetdsouza/zoxide) crate:

- Open a Rust file from the root of a crate.
- Put the cursor over some item.
- Use `lua vim.lsp.buf.hover()`
- Save (no changes have been made).
- Use `lua vim.lsp.buf.hover()` -> at this point `rust-analyzer` has crashed (through a bug in `rust-analyzer`, not a fault of `neovim`) and no warning has been raised about it.

### Expected behaviour

`neovim` should probably warn me `rust-analyzer` crashed and maybe give me the error message ?

**Comment by poliorcetics** [comment]
Additional informations:

It seems the bug occurs because `neovim` doesn't send the `version` information when sending the `textDocument/didSave` notification:

```
Invalid notification
Method: textDocument/didSave
 error: missing field `version`
```

**Comment by aktau** [comment]
Similar to https://github.com/neovim/neovim/issues/12610?

**Comment by poliorcetics** [comment]
> Similar to https://github.com/neovim/neovim/issues/12610?

Yes, I didn't find when looking for an existing issue, sorry !
