### ISSUE TITLE
Vim/Neovim inconsistency: Escaping visual text-object selection

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#13342]
- `nvim --version`: v0.4.4
- `vim -u DEFAULTS` (version: 8.2) behaves differently? yes
- Operating system/version: 5.9.1-arch1-1
- Terminal name/version: xfce4-terminal 0.8.9.2 (Xfce 4.14)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Type `itest<Esc>` (insert "test")
2. Type `vi` (enter visual mode; first step of selecting inner text object)
3. Press `<Esc>`

### Actual behaviour
Escape text object selection (i.e. return to visual mode).

### Expected behaviour
Escape visual mode (i.e. return to normal mode). This is vim's behavior.

**Comment by romgrk** [comment]
Can't reproduce with version `0.4.4`. Do you get the same behavior with `nvim -u NONE`?

**Comment by ddickstein** [comment]
Yes (and I double checked the version number).

**Comment by ddickstein** [comment]
I've attached a video of the issue. When I press `v` the bottom part changes to a "1" (indicating 1 character selected in visual mode), then I press `i` and the bottom changes to an "i" to indicate I'm now about to select an "inner" text-object. When I press `<Esc>` in Vim at this point a "^[" symbol appears at the bottom indicating I've escaped to normal mode, whereas if I press `<Esc>` in nvim you see that it changes from "i" to "1" (returned to visual mode) and then when I navigate around I'm still in visual mode.

[simplescreenrecorder-2020-11-21_16.26.41.mp4.gz](https://github.com/neovim/neovim/files/5578436/simplescreenrecorder-2020-11-21_16.26.41.mp4.gz)

**Comment by romgrk** [comment]
I misunderstood your bug report. The behavior shown in the video is the behavior I get. However I also get that same behavior in vim 8.2.

**Comment by ddickstein** [comment]
Ah you are right, this is a bad bug report. Here's what was happening:

I have a keyboard remapping script that runs each time I reconnect my keyboard, and it invokes `xcape -e 'Control_L=Escape'`. Each running instance of `xcape` does a remapping, so the number of key codes that a single remapped escape fires increases (observable with `xev | grep keycode`). It turns out that Vim was interpreting these as a series of escapes, so it was as though I was mashing on the escape key when I pressed it. Neovim did not have that behavior. The regular, proper escape works the same in both Vim and Neovim, as you pointed out.

Fixing my script to check for a running xcape instance before trying to start one resolves the issue, bringing the two behaviors in line. I probably do end up wanting the "mash escape" behavior, but that's a separate matter for me to resolve independently.
