### ISSUE TITLE
Is cursorlineopt on the roadmap?

### ISSUE THREAD

**Issue by thestumbler** [neovim/neovim#13356]
Just wondering if `cursorlineopt` will be added to Neovim anytime soon.
I just downloaded the head to see if it exists already, and no joy.
-Chris

**Comment by teto** [comment]
as usual vim patches are ported to neovim with a delay, it mostly depends on volonteers doing the work. If you are interested in porting this patch to neovim, feel free to ask for guidance in gitter.

**Comment by zeertzjq** [comment]
I ported 8.1.2019 in #15161.

I also tired to port 8.1.2029, but neovim and vim seem to use some local variables like `attr_pri` differently, so I don't know how to change those variables.

**Comment by zeertzjq** [comment]
I ported 8.1.2029 and 8.1.2214 in #15226.
