### ISSUE TITLE
Add wildsmartcase

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#13382]
We have `'ignorecase` and `'smartcase` controlling search case behavior, and `'tagcase`'s `followscs` to do so for tags, but for `wildmode`, all we have is `wildignorecase`.

`wildsmartcase` should do the equivalent for `wildmode`, where case sensitivity depends on whether the pattern contains any upper case chars.

(Alternatively this could be done similar to `tagcase` as `wildcase` and take a similar parameter).

**Comment by justinmk** [comment]
If https://github.com/vim/vim implements it sure, else not going to spend time on this.
