### ISSUE TITLE
nvim-qt doesn't recognize monospaced fonts

### ISSUE THREAD

**Issue by ndavidpsi** [neovim/neovim#13380]
- `nvim --version`: 0.5.0
- Operating system/version: Windows 10

I am using UbuntuMono NF (from the NerdFont official website).
(set guifont=UbuntuMono\ NF:h12)

I get the following error when I enter nvim-qt:
Warning: Font "UbuntuMono NF" reports bad fixed pitch metrics

Is there a way to fix this or just to suppress it?

**Comment by jamessan** [comment]
The nvim-qt repo is https://github.com/equalsraf/neovim-qt.  You're probably interested in https://github.com/equalsraf/neovim-qt/issues/732.
