### ISSUE TITLE
Help building nvim from source on/for Windows

### ISSUE THREAD

**Issue by ndavidpsi** [neovim/neovim#13381]
**I did the following:**
- I downloaded the source files for 0.5.0
- open msys2 mingw32-64
- install packages:
```
pacman -S \
    mingw-w64-x86_64-{gcc,libtool,cmake,make,perl,python2,pkg-config,unibilium} \
    gperf
```
- build:
```
mkdir .deps
cd .deps
cmake  -G "MinGW Makefiles" ../third-party/
mingw32-make
cd ..
mkdir build
cd build
cmake -G "MinGW Makefiles" -DGPERF_PRG="C:\msys64\usr\bin\gperf.exe" -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
mingw32-make
```

**My output:**
- When I do those commands I don't get python3 support (echo has("python3") outputs 0) 
- When I do checkhealth it gives an error INVALID $VIMRUNTIME

**I want the following options in my build:**
- x64 version
- python3 support
- change the USERNAME and the USERDOMAIN for "compiled by"

**_PS: I have access to Linux and I am able to use any other tools so I don't care which method I use for the build, I just want to compile it properly (similar to the official appveyor build)_**

**Comment by glacambre** [comment]
>When I do those commands I don't get python3 support (echo has("python3") outputs 0)

I think this means that either python isn't in your PATH (so neovim can't find it) or you did not install the neovim python package (I think it's `pynvim`?).

**Comment by ndavidpsi** [comment]
> either python isn't in your PATH (so neovim can't find it) or you did not install the neovim python package

I tried the nvim 0.5.0 windows build by appveyor and it's all **OK**
It is both in my PATH and `pynvim ` is installed

**Comment by glacambre** [comment]
What happens when you run `!where python3` in neovim?

**Comment by ndavidpsi** [comment]
it returns the python3 path as expected

**Comment by ndavidpsi** [comment]
@marvim What am I doing wrong? Could you give me a hand doing this? Sorry to be bothering you.

**Comment by glacambre** [comment]
@marvim is a bot, so it won't be able to help you :)

You could try the irc/matrix/gitter room, people might have answers there :)

**Comment by ndavidpsi** [comment]
lol haha oops. I just saw the name of who posted the build I thought he was the one who built it 🤣

**Comment by ndavidpsi** [comment]
Who actually built the lastest build of nvim?

**Comment by glacambre** [comment]
AFAIK Neovim is automatically built on travis and uploaded to github, so there aren't any human beings involved :)

**Comment by glacambre** [comment]
Just noticed that you had runtime issues. Does manually setting the VIMRUNTIME environment variable to your runtime dir before running neovim change anything?

**Comment by ndavidpsi** [comment]
Yes, some told me it was a runtime issue. How do I do I change VIMRUNTIME? I couldn't find an option with that name so what I did was changing `CMAKE_INSTALL_PREFIX` and then I moved the `build` folder to that path. When I did `Checkhealth` I got the following `E5009: Invalid $VIMRUNTIME: C:/Program Files/nvim/share/nvim` (`C:/Program Files/nvim` is the path I specified in `CMAKE_INSTALL_PREFIX`). Shouldn't the `build` folder contain the `share` directory?

**Comment by ndavidpsi** [comment]
What I did in the latest try was I changed `CMAKE_INSTALL_PREFIX` to `C:/Program Files/nvim` then I moved the contents of the `build` folder to that path, when I executed nvim and ran `Checkhealth` I got the error `E5009: Invalid $VIMRUNTIME: C:/Program Files/nvim/share/nvim`. Shouldn't the `build` folder contain a `share` directory?

**Comment by glacambre** [comment]
>Shouldn't the build folder contain a share directory?

`:h VIMRUNTIME` says the runtime should be in "../share/nvim/runtime", relative tothe neovim executable, so you could try moving the directory named `runtime` in neovim's source directory to that :)

**Comment by ndavidpsi** [comment]
I'll try

**Comment by ndavidpsi** [comment]
Update: that seemed to work. Moving the runtime folder that is in the same path as the build folder to the VIMRUNTIME path

**Comment by ndavidpsi** [comment]
Thanks!

**Comment by glacambre** [comment]
Glad I could help :)
