### ISSUE TITLE
Large file support with limited memory

### ISSUE THREAD

**Issue by rickywu** [neovim/neovim#13385]
Sometimes need to open large log file in prod env but with limited memory, such as docker container
It's dangerous because will cause OOM kill

Refer to this issue https://github.com/neovim/neovim/issues/614

Dose neovim surpported large file or with steam file, or some config that I can limit whole memory usage?

**Comment by jlneder** [comment]
In my experience, you start turning off syntax highlighting, then plugins. Then, you are screwed.
I just use vis for this tasks. Is has almost not dependencies, so you can put it in almost any container with any restrictions. It works excelent out of the box.
For big files vis mmap them so it always use the same memory at start(more or less) and if you don't make a lot of selections you are good.
If this can be done in vim, it would be great too.

**Comment by bfredl** [comment]
If we ever get around to memline2, this should be one of the design goals.

**Comment by rickywu** [comment]
@jlneder Thanks, I tried vis, yes it's great fast but still use lot of memory when open gigabytes file
VSZ         RSS
1520084 1500540

**Comment by Shougo** [comment]
Vim and neovim read whole of files into memory.
I think you should not use Vim/neovim for the task.

**Comment by rickywu** [comment]
> Vim and neovim read whole of files into memory.
> I think you should not use Vim/neovim for the task.
No problem

**Comment by Shougo** [comment]
Some editor has large file support like Emeditor.

**Comment by rickywu** [comment]
@jlneder mmap works like this: low memory usage when startup, but increase after scroll to the end of large file

VSZ is large size when startup, RSS will increase when page down out of current map memory.

this is ps -aux output of the two situations:
root        71  1.0  0.0 154348  5520 pts/0    S+   17:35   0:00 vis anaconda-post.log
root        60  1.4  0.9 154680 126772 pts/0   S+   17:34   0:01 vis anaconda-post.log

**Comment by bfredl** [comment]
mmapped pages can be freely discarded tho (as long as not PRIVATE i e COW sematics, then it is essentially just heap memory after modify)

**Comment by xaljer** [comment]
Maybe nvim can also provide a special mode to support large file learning from those editor design for large file.
A special mode can be designed by special scenes, so we can do some tradeoffs. I'm not sure that maybe a limitation of read-only can simplify viewing large file? But something like this can make nvim more general.
