### ISSUE TITLE
Neovim changes shiftwidth in Python files

### ISSUE THREAD

**Issue by sp1n0r** [neovim/neovim#13390]
- `nvim --version`: v0.5.0-828-g0a95549d6
- Operating system/version: Windows 10
- Terminal name/version: Alacritty

### Actual behaviour
I got the following in my `init.vim`:
```
set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
```
It works fine with all filetypes I use.
But in python, shiftwidth becomes 4. And to change that I have to set it to 2 everytime I edit a file
 
### Expected behaviour
Shiftwidth should not change.

**PS: I think it is worth mentioning that I use CoC completion I don't know if it is related to it or not.**

**Comment by chrisbra** [comment]
please read the help at `:h ft-python-plugin`

**Comment by sp1n0r** [comment]
Thank you. That solved it for me.
