### ISSUE TITLE
lsp_code_actions don't execute selected action for jdtls

### ISSUE THREAD

**Issue by ChrisAmelia** [neovim/neovim#13391]
Basically this https://github.com/neovim/nvim-lspconfig/issues/397
Although, I believe this belongs here instead of config: happened when I updated my neovim.

**Comment by mfussenegger** [comment]
This is because eclipse.jdt.ls uses the non-standard `java.apply.workspaceEdit` command. I doubt non-standard language server extensions will make it into neovim core. 
The PR in nvim-lspconfig should fix it. https://github.com/neovim/nvim-lspconfig/pull/429
