### ISSUE TITLE
LSP completions show too much info; no way to disable? 

### ISSUE THREAD

**Issue by TyOverby** [neovim/neovim#13396]
![image](https://user-images.githubusercontent.com/573215/100405713-2e680880-3032-11eb-9341-dd5e9f8df8f5.png)

^ As this image shows, the completion popup contains a _ton_ of details about the type of the function that it's completing.  I don't want this, because I'm using [completion-nvim](https://github.com/nvim-lua/completion-nvim), which should show the type for the currently-selected item.  However, because of how big the completion-list is, the type info is hidden behind it.

I spent a few hours reading through the docs, but couldn't find a way to disable these extra features of lsp-powered autocomplete.

**Comment by mhartington** [comment]
You could start by customizing the built-in completion formatting function?

https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L352-L397

**Comment by TyOverby** [comment]
@mhartington is there a way to override that function from inside my vimrc or something?

**Comment by TyOverby** [comment]
I tried this but it appears to have no effect.  

```lua
local original_c = vim.lsp.util.ext_document_completion_list_to_complete_items
  local new_c = function(...)
    local t = {...}
    print(vim.inspect(t))
    -- return original(unpack(t))
    return {}
  end
  vim.lsp.util.text_document_completion_list_to_complete_items = new_c
```

By overriding it to return an empty table, I would expect that the completion list would always be empty.  However, the behavior remains the same.

Sadly, I can't directly edit the `util.lua` file because I don't have write permissions for `/usr/share/**`

**Comment by TyOverby** [comment]
Issue moved here: https://github.com/nvim-lua/completion-nvim/issues/289
