### ISSUE TITLE
E117: Unknown function: readdir

### ISSUE THREAD

**Issue by topolyyy** [neovim/neovim#13406]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? n/a
- Operating system/version: Ubuntu 20.04.1 LTS
- Terminal name/version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
echo readdir(getcwd())
```

### Actual behaviour
E117: Unknown function: readdir

### Expected behaviour
List the current directory contents.

**Comment by h-michael** [comment]
"readdir" was portted at this commit.
https://github.com/neovim/neovim/commit/d2766b06c8fc50d06765c5c607744cc6b5f5ef0a

You can use "readdir" with nightly build.
