### ISSUE TITLE
HOME and END does not work properly in neovim in tmux in openSUSE Tumbleweed 

### ISSUE THREAD

**Issue by erenfro** [neovim/neovim#13408]
- `nvim --version`:

```
NVIM v0.4.4
Build type: RelWithDebInfo
moonjit 2.2.0
Compilation: /usr/bin/cc -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fcommon -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/abuild/rpmbuild/BUILD/neovim-0.4.4/build/config -I/home/abuild/rpmbuild/BUILD/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/home/abuild/rpmbuild/BUILD/neovim-0.4.4/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.4.4/build/include
Compiled by abuild@OBS

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?

> Same effect. To note, works in zsh before and after tmux, vim 8.2 before and after tmux, and works in nvim before tmux.

- Operating system/version:

> openSUSE Tumbleweed (20201125)

- Terminal name/version:
- `$TERM`:

> `xterm-256color` in zsh outside tmux.
> `screen-256color` in zsh _inside_ tmux.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

Home & End key do not move the cursor.

### Expected behaviour

Home & End key should move the cursor to the beginning and end of line, respectively.

infocmp | grep '256\|khome\|kend' output:

```
#       Reconstructed via infocmp from file: /usr/share/terminfo/s/screen-256color
screen-256color|GNU Screen with 256 colors,
        kdch1=\E[3~, kend=\E[4~, kf1=\EOP, kf10=\E[21~,
        khome=\E[1~, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
```

tmux version: 3.1c
terminfo version: 6.2.20201031

**Comment by app** [comment]
Same issue here
tmux 3.0a
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui

TERM=xterm-256color
inside and outside of tmux

~/.tmux.config
# Make Ctrl+a the tmux leader combination
unbind C-b
set -g prefix "C-a"
bind "C-a" send-prefix
# setw -g xterm-keys on
set -g base-index 1
# set -gq mouse on

set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# set -g status-bg colour6 # teal
set -g status-bg colour8 # grey

**Comment by app** [comment]
Try using 
TERM=tmux-256color
inside and (optional) outside of tmux
Neovim knows how to work with this type of terminal 
https://neovim.io/doc/user/term.html#terminfo

**Comment by erenfro** [comment]
That made no difference, except by specifically declaring that the terminal-overrides explicitly did change how the colors appeared. I had that but with $TERM to get the initial TERM environment (as I understand it's supposed to be).

tmux-256color TERM however, no difference in this situation. There's been other issues reported of this specific situation from others, but they were necrocommenting on already closed issues, instead of creating a new report like I did after extensive verification and testing.

**Comment by erenfro** [comment]
What using tmux-256color did do, though, is cause issues elsewhere, especially ssh'ing to CentOS 7 and Debian 9. tmux-256color is a bad or unsupported, or just too new termcap that isn't widely supported.

**Comment by erw7** [comment]
@erenfro What is your host terminal (`xterm`, `alacritty`, etc)?

> - Terminal name/version:
> - $TERM:
>> xterm-256color in zsh outside tmux.
>> screen-256color in zsh inside tmux.

**Comment by erenfro** [comment]
> @erenfro What is your host terminal (`xterm`, `alacritty`, etc)?

Huh, you know that's the one thing I did not compare against. I use Tillix primarily, which libvte based, and that's where I see the problem. I've tested, as of this message though, Gnome Terminal, Terminus, XTerm, XFCE Terminal, and so long as tmux is in the mix, that's where it the keys stop working, specifically.

**Comment by erw7** [comment]
I've checked with `tilix` + `tmux` on openSUSE Tumbleweed (20201215), but can't reproduce it. What will be the result of the following operations on the host terminal and tmux?

```
> cat -v -
<home><end><c-c>
> nvim -u NORC
i<c-v><home><c-v><end>
```

**Comment by erenfro** [comment]
> I've checked with `tilix` + `tmux` on openSUSE Tumbleweed (20201215), but can't reproduce it. What will be the result of the following operations on the host terminal and tmux?
> 
> ```
> > cat -v -
> <home><end><c-c>
> > nvim -u NORC
> i<c-v><home><c-v><end>
> ```

cat -v -:
^[[1~^[[4~^C

nvim -u NORC:
After hitting i<c-v> and hit Home and End, nothing happens. Hitting Insert, I get <Insert>

**Comment by erw7** [comment]
I overlooked the following information.

> Compiled by abuild@OBS

When I installed the openSUSE Tumbleweed package, I was able to reproduce the phenomenon. The [Release Page](https://github.com/neovim/neovim/releases/tag/v0.4.4) binary does not have this problem. I took a quick look at the versions of `libunibilium4`, `libtermkey1`, etc., and there seemed to be no problems. I am not going to track this issue any further. You can contact the maintainer of the package or use the binaries released by the project.

**Comment by mcepl** [comment]
@erenfro Check the https://build.opensuse.org/package/show/editors/neovim, I really don’t think I do anything which could do any change for neovim and keys handling. Could you try to reproduce with the plain build from the tarball on OpenSUSE/Tumbleweed machine? I suspect it could be the issue with our libraries for handling terminal, or terminfo.

**Comment by erw7** [comment]
@mcepl The OpenSUSE Tumbleweed package `libtermkey1` links to `libtinfo.so.6` as shown below.

```
> ldd /usr/lib64/libtermkey.so.1
	linux-vdso.so.1 (0x00007fffd6bdb000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007fb7c3507000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb7c333c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb7c3559000)
```

There is a bug in `libtermkey` that passes `Variable String` to `tigetstr` instead of `Cap-name`, so it will not work properly if it is built to use terminfo. Try changing `unibilium` to link to it. I haven't looked at the build log, but if `libunibilium4` and `unibilium-devel` were installed during the build, it should use unbilium.

**Comment by mcepl** [comment]
> There is a bug in `libtermkey` that passes `Variable String` to `tigetstr` instead of `Cap-name`, so it will not work properly if it is built to use terminfo. Try changing `unibilium` to link to it. I haven't looked at the build log, but if `libunibilium4` and `unibilium-devel` were installed during the build, it should use unibilium.

@erw7 So, in the conclusion, there is in your opinion a bug in `unibilium` that it doesn’t link properly to `libtermkey`? No bug in `neovim`?

**Comment by erw7** [comment]
> So, in the conclusion, there is in your opinion a bug in unibilium that it doesn’t link properly to libtermkey? No bug in neovim?

The bug exists in `libtermkey`. As you can see from the following `Makefile`, `libtermkey` will be built using `tinfo` or `ncurses` (In that case, `tigetstr()` will be used)  if `unibilium` is not found. In that case, there is a bug that `the long terminfo names` (e.g. `key_f1`) are being passed even though `the short terminfo name` (e.g. `kf1`) needs to be passed.

https://github.com/neovim/libtermkey/blob/b7fe3af141c53cce71a244282b69ea860452120a/Makefile#L24-L35.

I created neovim/libtermkey#2 which fixes this. I thought that if `libtermkey` did not use `unibilium`, it would cause an error when linking neovim, as in #2484. So I noticed this problem recently, but I did not report the bug to the maintainer of `libtermkey`.

The above patch is not very good and it is not clear if it will be merged into `libtermkey`. Therefore, the quickest way to solve the problem is to change `ncurses-devel` to `unibilium-devel` below.

https://build.opensuse.org/package/view_file/devel:libraries:c_c++/libtermkey/libtermkey.spec?expand=1

```
BuildRequires:  ncurses-devel
```

**Comment by mcepl** [comment]
@pbleser I guess this is for you, as the bug is accused being in libtermkey in the OpenSUSE package.

**Comment by app** [comment]
> What using tmux-256color did do, though, is cause issues elsewhere, especially ssh'ing to CentOS 7 and Debian 9. tmux-256color is a bad or unsupported, or just too new termcap that isn't widely supported.

Yes. I use
`TERM=xterm-256color ssh <CentOS.host>`
for ssh'ing to CentOS for avoiding issues

**Comment by soratobukuroneko** [comment]
Well, I'm not sure to have understood everything. But in my case on Gentoo the issue was solved by upgrading only unibilium from stable ebuild (ie. gentoo package), which is currently providing v2.0.0, to the unstable ebuild (ie. ~amd64 and alike package keyword) which is unibilium version 2.1.0

libtermkey is at version 0.22. neovim 0.4.4 and from what I read from the ebuild it has no dependency on ncurses. Except unibilium I didn't had to rebuild anything else.

**Comment by erenfro** [comment]
Honestly I don't get it at all. This is literally not an issue on Fedora, Ubuntu, Debian, or anything but openSUSE that I've specifically seen. I was just using openSUSE for a time to give it a thorough hands-on run. The issue is fully repeatable natively, and in a VM, so it's really easy to confirm in every possible scenario.
