### ISSUE TITLE
multigrid and guis which send mouse inputs to specific windows interact incorrectly with tabline

### ISSUE THREAD

**Issue by Kethku** [neovim/neovim#13416]
- `nvim --version`:
```
NVIM v0.5.0-828-g0a95549d6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- Operating system/version:
Windows 10

### Actual behaviour

Using a Gui with multigrid extension enabled, and which sends mouse inputs per grid rather than to the base grid, clicking in the top row of a given window will instead send the click to the tabline which may select a different buffer.

Clicking here: 
![image](https://user-images.githubusercontent.com/3323631/100557487-6784c080-325e-11eb-89bc-21164ce57112.png)

Results in:
![image](https://user-images.githubusercontent.com/3323631/100557491-72d7ec00-325e-11eb-9015-0c351890438a.png)

Clicking here:
![image](https://user-images.githubusercontent.com/3323631/100557505-8be09d00-325e-11eb-823b-8ba568d7b3a9.png)

Results in:
![image](https://user-images.githubusercontent.com/3323631/100557511-9733c880-325e-11eb-825f-162bd7be6bd7.png)

### Expected behaviour

Clicking in the top row of a window should send the input to that window rather than the tabline.

**Comment by Kethku** [comment]
If I disable the tabline, or enable the tabline gui extension, this issue goes away. I think that the tabline is hard coded to intercept mouse inputs which have a y of 1 (or 0, I don't remember) which is incorrect when the grid which the mouse input is sent to is not the global one.

**Comment by zeertzjq** [comment]
Does this bug still exist?
