### ISSUE TITLE
typescript: Nullish Coalescing breaks syntax highlight

### ISSUE THREAD

**Issue by m-nny** [neovim/neovim#13410]
- `nvim --version`: v0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently?: yes, syntax highlight works properly with `Vi IMproved 8.2`, but breaks with `Vi IMproved 8.1`
- Operating system/version: Manjaro i3
- Terminal name/version: `kitty v0.19.111`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`
Edit any typescript file, which includes [Nullish Coalescing](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing). Example:
```typescript
const str = 123; 
console.log(`${null ?? str}`); 
console.log(`${null ?? str}`);
```
```bash
echo 'const str = '123'; \nconsole.log(`${null ?? str}`); \nconsole.log(`${null ?? str}`);' > test.ts
nvim -u NORC test.ts
```

### Actual behaviour
![image](https://user-images.githubusercontent.com/12575900/100543541-ec7dd300-327a-11eb-82bf-d186839575fc.png)

### Expected behaviour
![image](https://user-images.githubusercontent.com/12575900/100543549-f4d60e00-327a-11eb-9537-549a2df34e37.png)

**Comment by m-nny** [comment]
I think, the reason behind this bug is the same as behind #12125. `vim/runtime/syntax/typescriptcommon.vim` has been updated in https://github.com/vim/vim/commit/3132cddd209ee510bde48b6520290cb26c8f604a recently, which I believe added support for **Nullish Coalescing**.
Therefore, we just need to update runtime files again, however I have no idea how to do it in order to make a PR.

**Comment by glacambre** [comment]
This is fixed on master :tada: . Thanks for the report :).
