### ISSUE TITLE
Can't properly change neovim's background color

### ISSUE THREAD

**Issue by ndavidpsi** [neovim/neovim#13412]
- `nvim --version`: 0.5.0
- Operating system/version: Windows 10
- Terminal name/version: any terminal does it, but the one I'm using is Alacritty

### How to reproduce this issue
Put the following lines in your init.vim and use a colorscheme that changes the background color:
```
highlight Normal guibg=NONE ctermbg=NONE
highlight NonText guibg=NONE ctermbg=NONE
```

### Behaviour
The color scheme I am using is called codedark, it has a grey background color. After placing those lines in my init.vim, the background color was supposed to be all black. Instead, the following happens:

![nvim_changeBGcolor](https://user-images.githubusercontent.com/73792104/100549231-aff5ab80-3269-11eb-8117-340cebc66fcd.PNG)

**Comment by jdhao** [comment]
Your reproduce steps do not show clearly how to reproduce. No one can reproduce your issue with this vague description.

BTW, this is not the right way to override the highlight groups set by color schemes. What is the output of `:verbose hi Normal` and `:verbose hi NonText`?

See also [this gist](https://gist.github.com/romainl/379904f91fa40533175dfaec4c833f2f) on how to override the highlight of a color scheme correctly.

**Comment by ndavidpsi** [comment]
That gist basically did the same as I.
The output of `:verbose hi Normal` is `Normal         xxx ctermfg=188 guifg=#D4D4D4`
and the output of `:verbose hi NonText` is `NonText        xxx ctermfg=240 guifg=#5A5A5A`

**Comment by jdhao** [comment]
> That gist basically did the same as I.

No, it is not doing the same as you did. Haven't you noticed the use of `ColorScheme` event?

> The output of `:verbose hi Normal` is `Normal xxx ctermfg=188 guifg=#D4D4D4`
> and the output of `:verbose hi NonText` is `NonText xxx ctermfg=240 guifg=#5A5A5A`

Then apparently your setting does not even work. It is simply overridden by other settings.

**Comment by ndavidpsi** [comment]
I did everything on the website now. The effect was the same as before.
Here is `:verbose hi Normal` and `:verbose hi NonText` respectively:
- `Normal         xxx ctermfg=188 guifg=#D4D4D4`
- `NonText        xxx ctermfg=240 guifg=#5A5A5A`

Here are some screenshots:
![1](https://user-images.githubusercontent.com/73792104/100622932-5d73c800-3319-11eb-9f07-1f84265e5797.PNG)
![2](https://user-images.githubusercontent.com/73792104/100622939-5fd62200-3319-11eb-8459-5032becbc0df.PNG)

**Comment by jdhao** [comment]
Then I think it is doing exactly what you want. 

This issue is more fit on vi.stackexchange.com rather than here.

**Comment by glacambre** [comment]
@ndavidpsi Does `:hi EndOfBuffer ctermbg=NONE guibg=NONE` do what you want?

**Comment by ndavidpsi** [comment]
No it is not. I want to remove that colorscheme's background color.
You see how it looks grey in lines that have no text, it was supposed to become all black.
![1](https://user-images.githubusercontent.com/73792104/100627234-ac702c00-331e-11eb-915a-65e46bd6ea49.PNG)

**Comment by ndavidpsi** [comment]
@glacambre yes, thanks!! So that's what I was missing.
