### ISSUE TITLE
Control shift mappings no longer work with neovim-qt

### ISSUE THREAD

**Issue by svermeulen** [neovim/neovim#13421]
Adding a vim rc with a `<c-s-k>` map works correctly when building neovim from commit e62beab71, but as of commit a88bc4d95, this mapping stops working.  Related:  https://github.com/neovim/neovim/issues/12037 and https://github.com/neovim/neovim/pull/13279

Testing with neovim-qt.  I'm not sure if this is related to neovim-qt or neovim but posting here since it was the change here in commit a88bc4d95 that caused it

cc @jamessan

**Comment by glacambre** [comment]
Can reproduce, and the testcase I put in #12037 isn't working either. I guess I started celebrating too fast :smile: .

**Comment by jamessan** [comment]
> Can reproduce, and the testcase I put in #12037 isn't working either.

You mean this one?

```
nvim -u NORC
:nnoremap <C-w> aa
:nnoremap <C-S-w> ab
:call nvim_input("<C-w>")
```

That works for me from the TUI and nvim-qt.  Ditto for pressing those chords in nvim-qt.

**Comment by glacambre** [comment]
Yes, I mean this one. That's weird, pressing `<C-w>` inserts `b` rather than `a` in both the TUI and Firenvim for me (while I would expect it to insert `a`). I'm using the appimage, v0.5.0-828-g0a95549d6.

**Comment by jamessan** [comment]
> I'm using the appimage, v0.5.0-828-g0a95549d6.

The appimage hasn't been updated due to #13312.  Commit 0a95549d6 is missing the fixes from a88bc4d.

**Comment by glacambre** [comment]
Woops, sorry for the noise then!

**Comment by svermeulen** [comment]
I just tried this again and confirmed the problem again.  More detailed repro steps for me on my mac:

1. Build neovim from head of master (in this test, commit 8fb786e41)
2. Build neovim qt from head of master (in this test, commit 6828be5)
3. Replace file at `~/.config/nvim/init.vim` with the following:
   
    ```
    nnoremap <c-k> :echo 'hi1'<cr>
    nnoremap <c-s-k> :echo 'hi2'<cr>
    ```

4. Run neovim qt with: `open -n -a "[path to local neovim-qt clone]/build/nvimqt/bin/nvim-qt.app" --args --maximized --nvim "[path to local neovim clone]/build/bin/nvim"`
5. Hit `<c-k>`
6. Observe output 'hi1'
7. Clear output by pressing `:echo`
8. Hit <c-s-k>
9. Observe output 'hi1' (was expecting 'hi2').  The `<c-s-k>` map appears to have zero effect.  Adding that line without the `<c-k>` also does nothing when pressing `<c-k>` or `<c-s-k>`.  It seems that `<c-s-k>` is always read as `<c-k>`

If you repeat the above except compile neovim from commit e62beab, then it seems like we have a different problem.  Pressing `<c-k>` and `<c-s-k>` both print 'hi2'.  If I remove the `<c-s-k>` map, then both cases print 'hi1'.  So it seems like the `<c-s-k>` map overrides the `<c-k>` map.

**Comment by svermeulen** [comment]
I tried another GUI ([neovide](https://github.com/Kethku/neovide)) and found this not to be an issue there, so I suspect that neovim is doing the correct thing and the problem lies with [nvim-qt](https://github.com/equalsraf/neovim-qt) instead.   So closing this here.

**Comment by jgehrig** [comment]
@jamessan 

I'd like to fix this in `neovim-qt`. However, I want to make sure I understand the format `nvim` expects. I am not aware of a spec that calls out the correct input format.

In the case of CTRL + SHIFT + B, we're sending <C-B>.
In the case of CTRL + B, we're sending <C-b>.

We're removing the shift because the letter is capitalized. What is the correct format for CTRL + SHIFT + KEY_LETTER?

Should we use: <C-B>, <C-S-B>, <C-S-b>? Which parts are case sensitive?

Related:
https://github.com/equalsraf/neovim-qt/issues/817
https://github.com/equalsraf/neovim-qt/pull/820

Thanks! :smile:

**Comment by jamessan** [comment]
> Should we use: `<C-B>`, `<C-S-B>`, `<C-S-b>`?

Either of the latter two.

> Which parts are case sensitive?

None of it.  `X-` is a modifier and the last character is the key, so:

* `<C-b>` and `<C-B>` are both Ctrl-b
* `<c-s-b>`, `<C-s-B>`, `<c-S-b>`, etc. are all Ctrl-Shift-b
* `<C-s>` is Ctrl-s
* `<C-s-s>` is Ctrl-Shift-s

**Comment by jgehrig** [comment]
@jamessan

Thank you for the clarification. I suspected that was the correct format...

I will check in the queued-up `neovim-qt` fix soon: https://github.com/equalsraf/neovim-qt/pull/820

@svermeulen 

The issue can be closed. Thanks!

**Comment by svermeulen** [comment]
Thank you all!
