### ISSUE TITLE
How can i delete ONLY background  , without syntax hightlighting and other?

### ISSUE THREAD

**Issue by peach-lasagna** [neovim/neovim#13423]
BEFORE:
![изображение](https://user-images.githubusercontent.com/59787538/100630539-40f97f00-335d-11eb-8b1b-00adf36471ef.png)

NOW:
![изображение](https://user-images.githubusercontent.com/59787538/100630508-34752680-335d-11eb-84d4-b68b28e892fa.png)
I would like to have picture (or gif) on background, but i can't find a setting, which responsible for it.

**Comment by glacambre** [comment]
If you had searched for the word "background" among the closed issues you would have found this issue: https://github.com/neovim/neovim/issues/13412 .
It mentions the following three commands:
```
:highlight Normal guibg=NONE ctermbg=NONE
:highlight NonText guibg=NONE ctermbg=NONE
:highlight EndOfBuffer guibg=NONE ctermbg=NONE
```
Run them after loading the colorscheme in the first screenshot and you should have the result you want.

I think you'll get answers faster for this kind of question if you ask them on irc/matrix/gitter :)

**Comment by peach-lasagna** [comment]
Thanks so much!
