### ISSUE TITLE
Support set virtual text in the beginning of line

### ISSUE THREAD

**Issue by glepnir** [neovim/neovim#13420]
- `nvim --version`: Head version
- `vim -u DEFAULTS` (version: ) behaves differently? NO
- Operating system/version: mac os
- Terminal name/version: kitty
- `$TERM`: xterm-kitty

### Actual behaviour

can't set the virtual text in the beginning of line

### Expected behaviour

support this feature.

**Comment by glepnir** [comment]
@bfredl  cc

**Comment by mhanberg** [comment]
What do you mean by “head of line”?

**Comment by mhanberg** [comment]
Thanks for the clarification. I'll just comment here that it would be nice for virtual text to be rendered above the line it's referring to, and to be able to wrap. 

The problem i have with virtual text right now is that if you have two splits open, and a compiler warning on a longish line, then you only see about two words of the warning and I you need to close the other splits to read it, or execute some incantation that i haven't learned yet to put that diagnostic in the quickfix or a floating window.

**Comment by glepnir** [comment]
@mhanberg Sorry for the late reply. This issue is an enhancement of the virtual text position. It can fill indented blank lines in some functions. The virtual text for diagnostic information looks a bit messy at present. I have recently implemented the use of floating window enhancement Experience with diagnostic information. But this is a complicated api so I will not add it to the upstream lsp, but I will use it as a new plugin.

**Comment by mhanberg** [comment]
I was thinking something more along the lines of this, with the virtual text being located above the affected line and the line above.

![](https://raw.githubusercontent.com/eamodio/vscode-gitlens/main/images/docs/code-lens.png).

**Comment by glepnir** [comment]
Okay  if there is no empty blank in the error line above .so the virtual still at the end of line?

**Comment by teto** [comment]
I have been working on inline folds and this could be refactored afterwards to have virtualtext at the beginning but it's gonna take some time.

@mhanberg to see the full diagnostic you can do sthg like
`nnoremap <leader>dl <cmd>lua vim.lsp.diagnostic.set_loclist()<CR>`

**Comment by ttys3** [comment]
@glepnir  allow virt_text overlay at any column merged https://github.com/neovim/neovim/pull/13952

**Comment by glepnir** [comment]
I know that. because I told bfredl to merge it yesterday.

**Comment by glepnir** [comment]
test it. works fine
![image](https://user-images.githubusercontent.com/41671631/108817706-46303800-75f3-11eb-94d8-76bc9b9f11f1.png)

**Comment by tejasvi** [comment]
> I was thinking something more along the lines of this, with the virtual text being located above the affected line and the line above.
> 
> ![](https://raw.githubusercontent.com/eamodio/vscode-gitlens/main/images/docs/code-lens.png).

@mhanberg Is this "virtual line" possible with the current implementation?

**Comment by mhanberg** [comment]
> > I was thinking something more along the lines of this, with the virtual text being located above the affected line and the line above.
> 
> > 
> 
> > ![](https://raw.githubusercontent.com/eamodio/vscode-gitlens/main/images/docs/code-lens.png).
> 
> 
> 
> @mhanberg Is this "virtual line" possible with the current implementation?

I don't think so.

**Comment by evertonse** [comment]
> > @mhanberg Is this "virtual line" possible with the current implementation?
> 
> I don't think so.

I'd like that, does anybody know the current issue (if there's one) about this "virtual **line**" feature. 
It would greatly simplify the nvim-tree feature I'm working on.


edit: Found this 
```lua
function InsertVirtualTextBelowCurrentLine()
  local buf = vim.api.nvim_get_current_buf()

  local current_line = vim.api.nvim_win_get_cursor(0)[1] - 1

  local target_line = current_line

  local namespace = vim.api.nvim_create_namespace 'example_namespace'

  vim.api.nvim_buf_set_extmark(buf, namespace, target_line, 0, {
    virt_lines = { { { 'This is virtual line above current one', 'Comment' } } },
    virt_lines_above = true,
    virt_lines_leftcol = false,
  })
end

```
Result:
![image](https://github.com/user-attachments/assets/dd588a15-59fb-4a0d-ba7f-fe4377f1003c)
