### ISSUE TITLE
Is there a way to edit nvim welcome message?

### ISSUE THREAD

**Issue by ndavidpsi** [neovim/neovim#13432]
Is there a way to edit nvim welcome message?
```
~                                NVIM v0.5.0-828-g0a95549d6
~
~                      Nvim is open source and freely distributable
~                                https://neovim.io/#chat
~
~                     type  :help nvim<Enter>       if you are new!
~                     type  :checkhealth<Enter>     to optimize Nvim
~                     type  :q<Enter>               to exit
~                     type  :help<Enter>            for help
~
~                             Help poor children in Uganda!
~                     type  :help iccf<Enter>       for information
```

**Comment by bew** [comment]
Some plugins does this by opening a custom buffer on start, like the widely-known startify plugin:
👉 https://github.com/mhinz/vim-startify

**Comment by ndavidpsi** [comment]
ah yes I know about it. But I don't wish to completely change it, I just wanted to edit or add some sentences to the default message

**Comment by glacambre** [comment]
You'd need to edit Neovim's source code I think:
https://github.com/neovim/neovim/blob/1b8867ab39ecc25d454ca67e3cb8b3ef5fca9ed3/src/nvim/version.c#L2215-L2226

**Comment by ndavidpsi** [comment]
Oh alright. I'm still waiting for some help doing so in #13381

**Comment by ndavidpsi** [comment]
Anyway, closing this issue. Thanks for the help, I'll do that once I'm able to properly build neovim from source.
