### ISSUE TITLE
mode() function doesn't return 'Rv' string when in Virtual Replace mode (VREPLACE)

### ISSUE THREAD

**Issue by trankien386** [neovim/neovim#13438]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: 8.1.2292) behaves differently? No, same issue as in neovim.
- Operating system/version: MacOS Catalina 10.15.7
- Terminal name/version: Default Terminal.app
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Use below code to see what letter does `mode()` return in statusline when switching modes
set statusline=%{'-'.mode().'-'}
```

### Actual behaviour
`mode()` return `R`, which is the same as in normal Replace mode
### Expected behaviour
`mode()` should return `Rv` when switching to Virtual Replace mode (VREPLACE) by pressing `gR`, according to `:help mode()`

**Comment by chrisbra** [comment]
you need to use `mode(1)` as mentioned on reddit. without the additional argument to `mode()`, it will only return the first character of the mode. This should also be mentioned in the help.

**Comment by trankien386** [comment]
> you need to use `mode(1)` as mentioned on reddit. without the additional argument to `mode()`, it will only return the first character of the mode. This should also be mentioned in the help.

Sorry i missed that. I don't know much about vimscript so when i looked into that part in airline source code, i just quit.

`mode(1)` did return 'Rv' in my case. In order to show full name, i need to tweak my vimrc alot more. Not easy for me right now. If i see this is a big deal, i'll use airline instead.

I've read the docs again carefully. 'Rv' is 2 letters. I should have paid attention to what it  said:

> otherwise only the 'first letter' is returned.

Thank you very much!
