### ISSUE TITLE
Changing vim.o from Lua doesn't change editor settings

### ISSUE THREAD

**Issue by GoldsteinE** [neovim/neovim#13433]
- `nvim --version`:
NVIM v0.5.0-nightly-335-g8fb786e41
- Operating system/version:
Mac OS X Big Sur
- Terminal name/version:
iTerm 3.4.2
- `$TERM`:
xterm-256color
### Steps to reproduce using `nvim -u NORC`

```
$ nvim -u NORC
:lua vim.o.shiftwidth = 4
:lua print(vim.o.shiftwidth)
4
:set shiftwidth?
shiftwidth=8
```

### Actual behaviour
Changing `vim.o.shiftwidth` only affects value of `vim.o.shiftwidth`
### Expected behaviour
Changing `vim.o.shiftwidth` changes value of `shiftwidth` setting

**Comment by GoldsteinE** [comment]
`:lua vim.api.nvim_set_option('shiftwidth', 4)` also don't work

**Comment by GoldsteinE** [comment]
Oh, I got it. `shiftwidth` is buffer-local. But why this doesn't produce an error message?

**Comment by seandewar** [comment]
> Oh, I got it. `shiftwidth` is buffer-local. But why this doesn't produce an error message?

It'll set the global value for the local option, which will change the value for buffers created afterwards.

**Comment by ojroques** [comment]
I've ran into the same issue. I set this in my init.lua:
```lua
vim.o.number = true
```
but the option was not set when I open neovim. Turns out `number` is a window-local option so the correct line is:
```lua
vim.wo.number = true
```

An error message to understand why my first attempt did not work and how to set a non-global option would have been very helpful. Or a common interface for users to set global + window/buffer-local options in one go just like `set` does in vimscript.

**Comment by bfredl** [comment]
@tjdevries is working on this :]

**Comment by mnarrell** [comment]
That's great!  I run into the same issue often.  Is there a PR tracking @tjdevries work?

**Comment by hardfau18** [comment]
I am ran into same issue too. global options reflects only after second buffers, or window

**Comment by forkbomb9** [comment]
@mnarrell @hardfau18 Here's tjdevries' PR: #13479

**Comment by hardfau18** [comment]
temporarily I changed everything `vim.cmd("set ...")` till this PR is merged

**Comment by tjdevries** [comment]
Can this be closed?

**Comment by hardfau18** [comment]
This can be closed i think,
