### ISSUE TITLE
Cannot leave built-in terminal in Windows Terminal + WSL

### ISSUE THREAD

**Issue by ojroques** [neovim/neovim#13430]
- `nvim --version`:
```sh
$ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: **Ubuntu 20.04 in WSL1**
- Terminal name/version: **Windows Terminal v1.5**
- `$TERM`: `xterm-256color`

### Steps to reproduce
1. Open nvim (an empty `init.vim` can be used)
2. Run `:term` and enter terminal mode
3. Try to exit with `<C-\><C-n>`

### Actual behaviour
Nothing happens. I can't leave the built-in terminal. I've tried in the [kitty](https://sw.kovidgoyal.net/kitty/) terminal and it works there so it must be related to the terminal emulator. It seems the `<C-\>` sequence is completely ignored by Windows Terminal. Any idea why? 

I did not find any issue related to mine so I've created one there, please tell me if it's a Windows Terminal issue.

### Expected behaviour
Exit terminal mode.

**Comment by romgrk** [comment]
I'd open an issue with Windows Terminal to get their opinion. If you can try see if the `<C-\>` sequence works with other applications in the Windows Terminal it would help pinpoint the issue. (eg try zsh's bindkey)

**Comment by ojroques** [comment]
I've tried in tmux and same issue, so it's definitely unrelated to Neovim. I'll open an issue with Windows Terminal and update this one when I get a response. I'm closing it in the meantime.
