### ISSUE TITLE
Paste from system clipboard can move a character to end of file

### ISSUE THREAD

**Issue by DanielPower** [neovim/neovim#13431]
- `nvim --version`: 0.4.4 (also tested on nightly v0.5.0-898-g8fb786e41
- `vim -u DEFAULTS` (version: 8.2) behaves differently? Yes, vim behaves as expected
- Operating system/version: Archlinux
- Terminal name/version: Kitty, xfce4-terminal
- `$TERM`: xterm-kitty, xterm-256color

### Steps to reproduce using `nvim -u NORC`
Copy all text here: https://hastebin.com/raw/vocekupoku (Ctrl+A then Ctrl+C)
Paste into Neovim using Ctrl+Shift+V

Do the same into vim.

### Actual behaviour
Notice that when pasting into Neovim, there is an additional line at the bottom containing just the letter "g". And in Vim there is no extra character.

Doing a diff between the original text and the text pasted into Neovim shows that the g was actually taken from another part of the file.

Output of diff
```
198c198
< 6-7 f: ffbfffgf
---
> 6-7 f: ffbffff
1000a1001
> g
```

### Expected behaviour
The text would paste in its original form, without moving the g.

### Additional notes
Pasting using `"+P` does not have this problem. The problem only occurs when pasting via `Ctrl+Shift+V`

**Comment by studog-github** [comment]
Saw this posted on [Reddit](https://www.reddit.com/r/adventofcode/comments/k58pvk/2020_day_2_part_2_answer_not_being_accepted_tried/), had to check it out.

An observation: the 'g' that gets displaced is at offset 0xff8 in the byte stream.
A 4 Kb buffer minus an 8 byte header, and the handling code has a fence-post error?

**Comment by snprajwal** [comment]
This is not happening with other terminal emulators. I tried it on st, xfce4-terminal, termite and also inside tmux+st. Maybe it is an issue with how kitty handles the large input.

**Comment by DanielPower** [comment]
@snprajwal as noted in the original report, this also occurs on `xfce4-terminal`.

I can also reproduce on MacOS Big Sur using both Kitty and the stock Terminal application. Except. on MacOs, the character that gets swapped is different.

Here's the diff produced on MacOs: 
```50c50
< 8-10 f: bfffzfpcfjhw
---
> 8-10 f bfffzfpcfjhw
1000c1000
< 2-5 j: bjjjj
---
> 2-5 j: bjjjj:
```

**Comment by DanielPower** [comment]
As a sanity check, since MacOS produces slightly different results from Arch, I also just tested on my laptop running Pop!_OS 20.04. It shows the same issue with the same diff as the Arch system.

So I can reproduce this across three different computers, each with a different operating system, using various terminal emulators.

On MacOS and Pop!_OS I only tested Neovim 0.4.4, but on Arch I also tested nightly.

**Comment by DanielPower** [comment]
This issue still exists on NVIM v0.5.0-dev+nightly-312-g94cf7bba0

I'd consider this to be pretty high severity. I don't trust pasting in Neovim anymore. It's not just an edge case with the text in my original post. I regularly run into this issue across multiple computers, multiple operating systems, multiple terminal emulators, where on sufficiently large pastes, a character gets misplaced to the end, invalidating the pasted data.

**Comment by onionka** [comment]
Actually this is happening for me on iTerm2+tmux+NViM v0.4.4, and on input with any size.
And I can confirm that here it is random character.

**Comment by DanielPower** [comment]
The issue still occurs on the latest Neovim. But I have managed to narrow it down a little more. Strangely, the bug occurs if the length of your paste is 4090 characters or greater. I generated random strings using this tool: https://onlineasciitools.com/generate-random-ascii

Regardless of the character set I used, if I generated 4090 characters and pasted it, I would get a random character moved to the end. And if I instead generated 4089 characters or less, the paste would succeed.

Note that if you Ctrl+A to select all, it will add a trailing newline to your clipboard. So if you're going to use Ctrl+A the values to pass to the generator should actually be 4088 for a good paste, and 4089 for a bad paste, since the newline will add a character.

**Comment by onionka** [comment]
Just FYI, in my case it is happening even on short strings, but I noticed that it must be multiline. I noticed it when I was pasting certificates, keys, short gpg encrypted values, ...

**Comment by DanielPower** [comment]
I haven't experienced this issue in quite some time, and can no longer reproduce it on 0.5 with the string I provided in my original report.

@onionka could you re-test this on 0.5 and report back on if it's still happening for you? If you can no longer reproduce it either, I'll go ahead and close the issue.

**Comment by Magnuscake** [comment]
This is still a recurring issue in 0.5. At first I thought it might be due to a bug in the nightly version, but apparently it extends way back. I have been able to reproduce this on kitty, urxvt and xfce-terminal, though the characters that get displaced to the end are different in each

**Comment by onionka** [comment]
I can confirm, it is still a problem on NeoVim v0.5 ...

**Comment by notlesh** [comment]
I ran into this today and can confirm as @studog-github mentioned that it's the char at `0xff8`:

![image](https://user-images.githubusercontent.com/2967426/131927268-1406d9eb-473b-4fbc-81c7-9356aae44f97.png)

In my case, I reproduce as follows:

1. open a new terminal and `nvim` session (stay in normal mode)
2. copy the text here: https://gist.github.com/notlesh/6e4ef059f48d4e9a61dee9e607298b65
3. middle-click in the terminal
4. notice that the `b` following `f0d3` ends up being omitted and pasted at the very end of the blob

**Comment by DanielPower** [comment]
Coming back to note that I'm seeing this again. Not sure why I was unable to reproduce for a little while.
Neovim 0.5.1.

**Comment by zeertzjq** [comment]
I think this is a bug of `vim.paste()`.

**Comment by zeertzjq** [comment]
Minimal repro:
```lua
local pasted = { { "aaaaaaa" }, { "bbbbbbb" }, { "ccccccc" }, { "ddddddd" } }
vim.paste(pasted[1], 1)
vim.paste(pasted[2], 2)
vim.paste(pasted[3], 2)
vim.paste(pasted[4], 3)
```

Result:
```
aaaaaabbbbbbbcccccccddddddda
```

**Comment by zeertzjq** [comment]
I think this workaround doesn't actually work:
<https://github.com/neovim/neovim/blob/c4d70dae802ef074aaf54bdcbbd5f73380f74a86/src/nvim/lua/vim.lua#L244-L245>

**Comment by plane** [comment]
I'm still having problems with pasting out-of-order, using this setup:

> NVIM v0.7.0-dev+848-gb4fbb9dcf
> Windows 10 (version 21H1, OS build 19043.1415)
> Windows Terminal (Preview 1.12.3472.0)
> TERM=xterm-256color

Pasting works fine in insert mode, but not in replace mode.  If I paste `abcdefghijklmnoprqstuvwxyz---` in replace mode, I get results like the following at random:
```
noprqstuvwxyz---abcdefghijklm
vwxyz---abcdefghijklmnoprqstu
vwxyz---abcdefghijklmnoprqstu
noprqstuvwxyz---abcdefghijklm
fghijklmnoprqstuvwxyz---abcde
noprqstuvwxyz---abcdefghijklm
noprqstuvwxyz---abcdefghijklm
vwxyz---abcdefghijklmnoprqstu
noprqstuvwxyz---abcdefghijklm
fghijklmnoprqstuvwxyz---abcde
noprqstuvwxyz---abcdefghijklm
fghijklmnoprqstuvwxyz---abcde
fghijklmnoprqstuvwxyz---abcde
noprqstuvwxyz---abcdefghijklm
vwxyz---abcdefghijklmnoprqstu
vwxyz---abcdefghijklmnoprqstu
noprqstuvwxyz---abcdefghijklm
noprqstuvwxyz---abcdefghijklm
```
The cursor always ends up after the `---`.

If I add a little printf debugging to `vim.paste`, I see my text is randomly broken up into 1 to 5 calls each time I paste.  For example:
```
entering vim.paste(), lines[1] = abcdefghijlmnopqrstuv, phase = 1
entering vim.paste(), lines[1] = wxyz---, phase = 3
```
or
```
entering vim.paste(), lines[1] = abcde, phase = 1
entering vim.paste(), lines[1] = fghijlmn, phase = 2
entering vim.paste(), lines[1] = opqrstuv, phase = 2
entering vim.paste(), lines[1] = wxyz---, phase = 2
```
(Interestingly, the docs for `nvim_paste` suggest that there should always be exactly one phase 3 call, but often there is no phase 3 call.)

Anyway, this all works fine in insert mode, but in replace mode it breaks.  For example, when I see this debug info:
```
entering vim.paste(), lines[1] = abcde, phase = 1
entering vim.paste(), lines[1] = fghijlmnopqrstuvwxyz---, phase = 2
```
I end up with the following output:
```
fghijlmnopqrstuvwxyz---abcde
```
As you can see, whatever text is pasted in phase 1 in replace mode gets moved to the end of the buffer.
My workaround for the time being is just to remove replace mode handling from `vim.paste` entirely (zap the whole `mode == 'R'` section).

**Comment by plane** [comment]
Since https://github.com/neovim/neovim/pull/16585 doesn't fix the problem yet, my workaround is removing the phase-1 replace mode handling from `vim.paste` entirely.  I don't think the `normal! a` workaround does anything, as far as I can tell.

**Comment by zeertzjq** [comment]
I've converted #16585 into a plugin with compatibility with Nvim v0.4.0 and above: <https://github.com/zeertzjq/nvim-paste-fix>.
