### ISSUE TITLE
Can't find neovim-qt runtime folder

### ISSUE THREAD

**Issue by ndavidpsi** [neovim/neovim#13447]
**I built NeoVim from source on Windows using the following commands:**
```
-- open msys2 mingw32-64 as admin
cd (...)/neovim(-nightly)
-- install packages:
pacman -S \
    mingw-w64-x86_64-{gcc,libtool,cmake,make,perl,python2,pkg-config,unibilium} \
    gperf

-- build:
mkdir .deps
cd .deps
cmake  -G "MinGW Makefiles" ../third-party/
mingw32-make
cd ..
mkdir build
cd build
cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX="C:\Program Files\nvim" -DGPERF_PRG="C:\msys64\usr\bin\gperf.exe" -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
mingw32-make
```

The runtime of nvim is located in neovim/ but I can't seem to find nvim-qt runtime. I need it in order to have access to some nvim-qt commands (such as GuiFont)

**_PS: I know that this isn't the nvim-qt repo but I'm posting this here because the build was done with this repo_**

**Comment by glacambre** [comment]
`nvim-qt` doesn't have a runtime, so what are you trying to do exactly? What errors are you seeing?

**Comment by ndavidpsi** [comment]
It has in share/nvim-qt. It was necessary in order to access some nvim-qt commands such as GuiFont. I ended up downloading it from the nvim-qt repo
