### ISSUE TITLE
[QUESTION] How can i map "grave" key ?

### ISSUE THREAD

**Issue by peach-lasagna** [neovim/neovim#13456]
ThisI don't now name of this key:
![изображение](https://user-images.githubusercontent.com/59787538/101245021-8d1d3880-373c-11eb-8381-1e7b7f8e6f56.png)

I try:

:map <grave> echo 123

it did not worked.

**Comment by username-goes-here** [comment]
```vim
:nnoremap ` :echo '123'<CR>
```
Does this work for you? It's supposed to print "123" to the command-line when you're in normal mode.

**Comment by peach-lasagna** [comment]
Yes! Thx so much!

**Comment by username-goes-here** [comment]
You're welcome.
