### ISSUE TITLE
Why does neovim installed with homebrew with --head depend on emscripten and openjdk?

### ISSUE THREAD

**Issue by unphased** [neovim/neovim#13465]
Output of `brew deps neovim`:
```
binaryen
emscripten
gdbm
gettext
icu4c
libtermkey
libuv
libvterm
luajit
msgpack
node
openjdk
openssl@1.1
python@3.9
readline
sqlite
tree-sitter
unibilium
xz
yuicompressor
```

I'm trying to figure out if this is a problem with my system (likely) or with homebrew formulas or with this project (not likely)

My system is MacOS 10.15.7

**Comment by glacambre** [comment]
I don't know brew but it looks like the formula doesn't contain any of these dependencies: https://github.com/Homebrew/homebrew-core/blob/e75ec6c4f9a9fc728d46dc085cd852ad7d2a91bc/Formula/neovim.rb . Understanding where your issue is coming from probably will require homebrew knowledge, so you might have better luck asking on homebrew's support channels :)

**Comment by MuhammedZakir** [comment]
HEAD build depends on `tree_sitter` and it depends on `emscripten`. [1] I don't know about `openjdk` though. You will probably have to hunt it down yourself. `brew deps` options - `--tree`, `--n` and `--1` may help you.

[1] https://github.com/Homebrew/homebrew-core/blob/47605cce7b4c91c9762bda7243392bcb48c5d951/Formula/tree-sitter.rb#L18

**Comment by bfredl** [comment]
tree-sitter itself don't depend on `emscripten`. Maybe you could ask them to move the wasm stuff to `tree-sitter-wasm` or something.

**Comment by saadparwaiz1** [comment]
This was a recent change where they combined the tree-sitter library with the tree-sitter-cli. I tried suggesting creating a `libtreesitter` but closed the issue. There's a new [pull request](https://github.com/Homebrew/homebrew-core/pull/66273) now which should fix this. However, not sure if it'll get accepted either. As an alternative you can create a custom tap for yourself to avoid installing all the `emscripten`

**Comment by carlocab** [comment]
Yes, a well-meaning individual decided to add all the extra features to the `tree-sitter` formula, so we ended up with this dependency tree:
```
❯ brew deps --tree tree-sitter
tree-sitter
├── emscripten
│   ├── node
│   │   └── icu4c
│   ├── python@3.9
│   │   ├── gdbm
│   │   ├── openssl@1.1
│   │   ├── readline
│   │   ├── sqlite
│   │   │   └── readline
│   │   └── xz
│   └── yuicompressor
│       └── openjdk
└── node
    └── icu4c
```
It's not ideal. My initial PR was to move the `tree-sitter-cli` to a different formula, but that didn't pan out. The revised PR may yet succeed. If not, maybe https://github.com/neovim/homebrew-neovim can be revived?

**Comment by unphased** [comment]
I knew I would have found the answer if i just recursively checked the deps on the formulae. Well at least the reason is now known, hopefully those deps can go away someday.

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/pull/66273 has been merged. You can now feel free to `brew uninstall node emscripten` if you don't need it.

You may need to do `brew update && brew upgrade && brew reinstall tree-sitter` (or, at least, only the first two) if `brew` still refuses to let you uninstall `node` or `emscripten`.

**Comment by mellery451** [comment]
The [current version](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tree-sitter.rb#L20) of the tree-sitter formula requires emscripten for build and test, so here we are again..and emscripten doesn't build currently on linuxbrew.

**Comment by MuhammedZakir** [comment]
> [...] maybe https://github.com/neovim/homebrew-neovim can be revived?

**Comment by clason** [comment]
@mellery451 Did you actually observe that emscripten is required for neovim? It's only a build dependency for _tree-sitter_, and building neovim from source should work straight from the tree-sitter bottle (which does _not_ require emscript).

**Comment by mellery451** [comment]
@clason yes, I observed it several times when doing `brew install neovim --HEAD`. Maybe it's because there it [no tree-sitter bottle specified](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/tree-sitter.rb) for x86_linux...I assume it has to build from source always in that case.

**Comment by clason** [comment]
Ah, right, that'd explain it. Not sure what can be done, then, as it's not strictly a homebrew issue...

**Comment by saadparwaiz1** [comment]
@mellery451 can't you just uninstall emscripten after installing neovim? Like instead of running `brew install neovim --HEAD` run `brew install neovim --HEAD && brew autoremove` which should remove all unneeded dependencies including emscripten?

**Comment by mellery451** [comment]
@saadparwaiz1 No - because emscripten won't build/install. It does not have a bottle on linux and it fails to build from source - which is perhaps two sides of the same coin. Very likely that this is all a cascading side-effect of emscripten build failures (thus no bottles for it nor tree-sitter) and thus neovim --HEAD cannot finish. Fun.

**Comment by clason** [comment]
If I understand correctly, emscripten is only need for building with the wasm module. If you remove that by reverting the above-linked homebrew PR, tree-sitter and thus neovim should build again. I'd suggest opening a linuxbrew issue about this.

**Comment by acanimal** [comment]
Issue with emscripten and openjdk continues 🙃

**Comment by sryze** [comment]
Is it possible to `brew install neovim` without building the whole openjdk if I have a JDK already installed outside of homebrew? On macOS Catalina homebrew builds everything from source and it takes a lot of time to install nvim...

Are there really any libc/c++ ABI changes between macOS versions that we have to build all packages from source?

**Comment by unphased** [comment]
not sure if i should mention but i do not use linuxbrew to build neovim on linux, I use a dockerfile to build and install it and it's been very hands off for me ever since I set it up. Linuxbrew would seem to me like a superfluous attempt to simplify an enormous amount of configuration complexity that's highly likely to trade convenience for even more headaches, but then again homebrew's momentum on macOS is such that this aspect of it has been kept in check. At the end of the day it's a chicken/egg type scenario there with that though I guess, maybe one day linuxbrew will be the defacto way to set up your docker containers 🤪
