### ISSUE TITLE
Please fix release title of pre-releases to not include version number

### ISSUE THREAD

**Issue by alerque** [neovim/neovim#13466]
For months now I've been getting more and more annoyed every time the nightly tag gets bumped in Git because I get release announcement notifications and there is no way to tell from the notification that it's a nightly tag and not the actual v0.5.0 release. When the latter happens I want to jump into gear and get some distribution packaging updated, but I don't care about the nightly tags.

Please change the title of the releases tagged nightly to not include a version number that they are not and/or include something that identifies them as nightlies. I realize the tags are marked as 'prerelease' but the GitHub notification center does not surface this information where it matters.

![image](https://user-images.githubusercontent.com/173595/101275359-13c22c00-37b6-11eb-828f-b108c0487f1e.png)

**Comment by bfredl** [comment]
the full version is actually `v0.5.0-911-g{HASH}`. but the CI script cuts it out. probably the nightly should use `v0.5.0-911`, or perhaps `v0.5.0-dev911` to be even clearer.

**Comment by jamessan** [comment]
I think using `v0.5.0-{XXX}-g{HASH}` is good enough differentiation.  I'll change that in my next PR.

**Comment by alerque** [comment]
> I think using `v0.5.0-{XXX}-g{HASH}`

I would suggest not. This format will be supremely confusing with the other use for the same format: `git describe` and friends. In many systems (not just Git itself but also many Linx distro packaging version schemes) any time you have the format you describe with a version number, an incrementor, and a hash — then the incrementor is counted since the version number was tagged. Otherwise you **cannot sort** tags and comparisg versions for less than / greater than becomes a nightmare. The current version shouldn't be `v0.5.0-{XXX}-g{HASH}` it should be `v0.4.0-{XXX}-g{HASH}`.

Please either use the incrementor since the last real version (not a pre-release of the next expected version) or use a different format altogether (and think about how distros will do version comparisons. `-alpha`, `-beta`, `-dev`, etc. suffixes are often supported and any incrementors need to come *after* such a suffix, not after the version tag syntax.

**Comment by bfredl** [comment]
> . The current version shouldn't be v0.5.0-{XXX}-g{HASH} it should be v0.4.0-{XXX}-g{HASH}

Anything with 0.4 in it will be even more confusing for everyone. Remember this is not a tag that any distro would ever read, just the _textual_ title of a binary we release. We don't do patch tags like vim does.

**Comment by alerque** [comment]
I realize it is not a tag, but my point still stands. The format `vX.Y.Z-{nnn}` implies a counter since the version. It's already confusing that you are using calling something that is not yet *v0.5.0* (and still considerably short of anything you plan on releasing as oh-dot-five as if it was. It would be a lot less confusing if you just made the title "nightly" to match the tag rather than putting a version format in there that is easily conflated with `git describe` but is calculated radically differently.

**Comment by bfredl** [comment]
I still think 0.5 should be mentioned. I have seen conventions like `0.5.0+284dev` (commit) or `even `0.5.0+2020111`  (full date, like git version on aur uses), where the `+` indictates the number is negative (as `-` is positive, very logic) in most realizations of semver and similar.

**Comment by bfredl** [comment]
hmm interestingly `version.c` already is intent on using `NVIM_VERSION_PRERELEASE` which is `-dev` in prereleases but it doesn't work for some reason.

**Comment by bfredl** [comment]
Hmm this goes some way:
```diff
diff --git a/src/nvim/CMakeLists.txt b/src/nvim/CMakeLists.txt
index 8ec087c62..db77931c1 100644
--- a/src/nvim/CMakeLists.txt
+++ b/src/nvim/CMakeLists.txt
@@ -242,7 +242,7 @@ if(use_git_version)
   add_custom_target(update_version_stamp ALL
     COMMAND ${LUA_PRG} scripts/update_version_stamp.lua
       ${relbuild}/config/auto/versiondef_git.h
-      "v${NVIM_VERSION_MAJOR}.${NVIM_VERSION_MINOR}.${NVIM_VERSION_PATCH}"
+      "v${NVIM_VERSION_MAJOR}.${NVIM_VERSION_MINOR}.${NVIM_VERSION_PATCH}${NVIM_VERSION_PRERELEASE}"
     WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
     BYPRODUCTS ${CMAKE_BINARY_DIR}/config/auto/versiondef_git.h)
 else()
```

Has one extra hyphen, which we of course could detect and remove

**Comment by jamessan** [comment]
> The current version shouldn't be `v0.5.0-{XXX}-g{HASH}` it should be `v0.4.0-{XXX}-g{HASH}`.

Not according to semver, which is what we follow.  `v0.5.0-dev` means development version for 0.5.0.  I've updated our script to generate the version in that format, with the additional context of what it's based on -- `v0.5.0-dev+v0.4.0-916-g4753c02ec`.

As for distros, they usually have ways to handle this.  For example, in Debian we would change `-dev` to `~dev` because `~` sorts less than anything so `v0.5.0~...` is always less than `v0.5.0`.
