### ISSUE TITLE
MSYS2 build doesn't recognize various help commands

### ISSUE THREAD

**Issue by ndavidpsi** [neovim/neovim#13463]
- `nvim --version`: NVIM v0.5.0
- Operating system/version: Windows 10
- Terminal name/version: Alacritty
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

**Build Neovim from source**
```
-- open msys2 mingw32-64 as admin
cd (...)/neovim(-nightly)
-- install packages:
pacman -S \
    mingw-w64-x86_64-{gcc,libtool,cmake,make,perl,python2,pkg-config,unibilium} \
    gperf

-- build:
mkdir .deps
cd .deps
cmake  -G "MinGW Makefiles" ../third-party/
mingw32-make
cd ..
mkdir build
cd build
cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX="C:\Program Files\nvim" -DGPERF_PRG="C:\msys64\usr\bin\gperf.exe" -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
mingw32-make
```
**Enter the following command**
`:help nvim-from-vim` (other commands don't work as well) 

### Actual behaviour
**E149: Sorry, no help for nvim-from-vim**
### Expected behaviour
Help should be displayed. 

### Notes
I am on Windows and I built it using the instructions I presented above.
Initially I had some trouble because it couldn't find the runtime, I later realized it is in the Neovim/ directory instead of Neovim/build/share/nvim. I don't know it that is relevant or if I'm really supposed to move it I just thought it was worth mentioning. Checkhealth now says everything is OK. So probably some help files are missing or not in the right directory right? What should I do to fix this?

**Comment by ndavidpsi** [comment]
Update: I think the help files are all there because I compared both runtimes of the official build and mine and they seem identical... The issue seems that nvim is not recognizing those (also the external plugin help commands seem to work fine, it's the ones native to nvim that don't seem to be working)

**Comment by glacambre** [comment]
This is probably a dumb question (I don't know much about compiling neovim and know nothing about compiling on windows) but did you run `mingw32-make install`? Looks like it's needed in the generic steps: https://github.com/neovim/neovim/wiki/Building-Neovim#building

**Comment by ndavidpsi** [comment]
No I actually did not. I forgot about it. I'll build it again and include that step, I'll share the results once I'm done. I don't know much about it either (only that is much easier to do so on Linux, I never get any issues there), the only other thing I have compiled on Windows before was OpenSSL (and Vim). And I think I did mingw32-make install on both

**Comment by ndavidpsi** [comment]
That's what I was missing, huge thanks!!
