### ISSUE TITLE
Latest release doesn't include windows binraries 

### ISSUE THREAD

**Issue by PhilT** [neovim/neovim#13460]
https://github.com/neovim/neovim/releases

Click on Assets.

No nvim-win64.zip or nvim-win32.zip

**Comment by PhilT** [comment]
Just it's WIP

**Comment by jayded** [comment]
What do you mean it's WIP? I would find a nightly windows release useful myself.

**Comment by bfredl** [comment]
It is WIP I'm the sense that someone is working on it.
