### ISSUE TITLE
init.lua does not set `wrap` option

### ISSUE THREAD

**Issue by kassio** [neovim/neovim#13474]
I tried to convert my `init.vim` to `init.lua` using `vim.o`. But the `wrap` options is not being set.

- `nvim --version`:
```
:version
NVIM v0.5.0-08c0eef52
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-u
nused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fall
through -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATI
ONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20
201206-48820-9lyovm/build/config -I/tmp/neovim-20201206-48820-9lyovm/src -I/usr/local/include -I/tmp/neov
im-20201206-48820-9lyovm/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr
/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201206-48820-9lyovm/build/src/nvim/auto -I/tmp/
neovim-20201206-48820-9lyovm/build/include
Compiled by kassioborges@kassioborges.lan

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-08c0eef/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? 
- Operating system/version:
$ sw_vers
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B29
- Terminal name/version:
iTerm2: Build 3.4.2
- `$TERM`:
$ echo $TERM
xterm-256color

### Actual behaviour

```
nvim -u NORC --noplugin

:echo &wrap   " returns 1
:lua vim.o.wrap = false  -- should change wrap opt to 0
:echo &wrap " still returns 1
```

### Expected behaviour

`:lua vim.o.wrap = false` should set `wrap` option to 0.

**Comment by fszymanski** [comment]
@kassio `wrap` is local to window, you have to do `:lua vim.wo.wrap = false`

**Comment by kassio** [comment]
Thanks @fszymanski.

**Comment by Liverm0r** [comment]
Is it still a recomended way?

**Comment by paanvaannd** [comment]
> How would I rewrite "set wrap linebreak nolist"

I had the same question. Consulting [this Stack Exchange answer](https://vi.stackexchange.com/questions/14408/can-i-set-multiple-options-with-a-single-set-command-spread-over-multiple-l) and the Neovim help docs, I found that splitting these multiple `set`s into different lines works.

```lua
vim.wo.wrap = true
vim.wo.linebreak = true
vim.wo.list = fasle -- something else I had on my single-line set command in init.vim compared with your question
```
