### ISSUE TITLE
runtime: requiring lua module with syntax error gives wrong error message

### ISSUE THREAD

**Issue by alecStewart1** [neovim/neovim#13477]
### Neovim Version

```
NVIM v0.5.0-dev+917-g85bce4d13
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/my_user/tools/neovim/build/config -I/home/my_user/tools/neovim/src -I/usr/include -I/home/my_user/tools/neovim/build/src/nvim/auto -I/home/my_user/tools/neovim/build/include
Compiled by my_user@my-host

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
   fall-back for $VIM: "/usr/local/share/nvim"

```

### Problem

`XDG_CONFIG_HOME/nvim/lua` should be in `LUA_PATH` in order to require user create Lua files.

Ex. in an `init.lua`

```lua
vim.o.exrc = true
vim.o.secure = true

require('some-other-file')
```

### What happens 

Unable to require files found in `XDG_CONFIG_HOME/nvim/lua` as one normally would.

Requiring any lua file that might be found in `XDG_CONFIG_HOME/nvim/lua` throws an error of `module '[x]' not found:`

### Steps to reproduce

Build Neovim from source using

```
make CMAKE_BUILD_TYPE=RelDebWithInfo USE_BUNDLED=OFF
sudo make install USE_BUNDLED=OFF
```

Create a `lua` folder in `XDG_CONFIG_HOME/nvim`

Create a file calling `settings.lua` with the contents of

```
vim.o.exrc = true
vim.o.secure = true
```

Create a `init.lua` or `init.vim` with either

```
require('settings')
```

or

```
lua require('settings')
```

Or different named `.lua` or `.vim` file that you tell Neovim to load using `nvim -u [that file name]`.

Neovim will say that `module 'settings' not found:`

### Other useful info

What `nvim -c "lua print(package.path)"` returns:

`./?.lua;/usr/share/luajit-2.1.0-beta3/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua`

I have tried building Neovim [the harder way](https://github.com/neovim/neovim/wiki/Building-Neovim) as well.

Allowing the build process to install bundled dependencies does not change this.

Attempting to manually modify the `runtimepath` variable does not effect this error either.

**Comment by dm1try** [comment]
> XDG_CONFIG_HOME/nvim/lua should be in LUA_PATH in order to require user create Lua files.

neovim uses [the custom loader](https://github.com/neovim/neovim/blob/85bce4d13d405fe009428def4fbead54bb741008/src/nvim/lua/vim.lua#L112) for those purposes.

@alecStewart1 could you please confirm that `settings.lua` on your side does not contain syntax errors? I've just noticed that this leads to a confounding "not found module" error.
```
lua print(vim.inspect(vim._load_package("settings")))
```

**Comment by alecStewart1** [comment]
@dm1try that snippet above returns `nil`.

All that's in `settings.lua` is

```
vim.o.exrc = true
vim.o.secure = true
```

I didn't put more than that in it to figure out what the problem is.

**Comment by dm1try** [comment]
@alecStewart1 cool

though we need a better error propagation for such case

**Comment by alecStewart1** [comment]
It would be a bit simpler to just say "Syntax error in 'some_file.lua'." But I don't know how loading Lua files is handled by Neovim.

**Comment by bfredl** [comment]
yes, we probably need to break a pcall in two somewhere..

**Comment by bfredl** [comment]
hmm but we **do not** intercept that error, just passing it through to letting the loader handle it. Does `loadlib.c` throw away errors from custom loader? :disappointed:

**Comment by dm1try** [comment]
I've tried to fix this in the referenced PR^

**Comment by bfredl** [comment]
aha custom loader of course uses a different error interface from builtin loader. not completely unexpected and deliberately confusing at all. anyway, the fix is simple then.
