### ISSUE TITLE
Is there a way to start a timer after exiting the neovim welcome message?

### ISSUE THREAD

**Issue by ndavidpsi** [neovim/neovim#13470]
I want to start a timer (using the timer_start function) only after I exit the nvim welcome message (because when I start the timer it stops displaying the welcome message). Is there an easy way to do so?

**Comment by glacambre** [comment]
I don't think so. You could do it the other way and start a new timer and then run the `:intro` command though.

I'm not sure this is the right place to ask this kind of user questions, reddit or irc/gitter/matrix might be better channels.

**Comment by ndavidpsi** [comment]
alright thanks
