### ISSUE TITLE
No Windows binaries for the latest nightly build

### ISSUE THREAD

**Issue by tomasz-rozanski** [neovim/neovim#13475]
Can't install nightly release (`v0.5.0-dev+916-gee5ece084`) neither by hand, nor by using package managers due to the fact, that the Windows binaries archives:
```
https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip
https://github.com/neovim/neovim/releases/download/nightly/nvim-win32.zip
```
does not exist.

**Comment by ojroques** [comment]
They're working on this, see #13312. The Windows build is not yet ready it seems.

**Comment by qmfszxn0cmk** [comment]
The VS Code [Neo Vim extension](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim&ssr=false#overview) requires a nightly build 0.5.0+. Is there an archived windows zip available until it's included in the nightly builds again?
