### ISSUE TITLE
vim.lsp.diagnostic.get_count returns zero results

### ISSUE THREAD

**Issue by alex-popov-tech** [neovim/neovim#13488]
- `nvim --version`:
```
NVIM v0.5.0-dev+85bce4d13
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -W
extra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wcon
version -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong
-fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE
 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neov
im-20201207-56559-l51eyd/build/config -I/tmp/neovim-20201207-56559-l51eyd/src -I/us
r/local/include -I/tmp/neovim-20201207-56559-l51eyd/deps-build/include -I/Library/D
eveloper/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/usr/local/opt/gettext/
include -I/tmp/neovim-20201207-56559-l51eyd/build/src/nvim/auto -I/tmp/neovim-20201
207-56559-l51eyd/build/include
Compiled by alexanderpopov@Alexanders-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-85bce4d/share/nvim"
```
- language server name/version: any? (tested on jsonls, tsserver, diagnosticls)
- Operating system/version: macos big sur 11.0.1

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

```

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
  - INFO: $TERM: screen-256color

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: diagnosticls: configuration checked.
  - INFO: html: configuration checked.
  - INFO: dockerls: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: jsonls: configuration checked.

```
</details>

<details>
<summary>lsp.log</summary>
[ INFO ] 2020-12-09T01:16:56+0200 ] ...ovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp/rpc.lua:311 ]	"Starting RPC client"	{  args = { "--stdio" },  cmd = "/Users/alexanderpopov/.cache/nvim/lspconfig/tsserver/node_modules/.bin/typescript-language-server",  extra = {}}
[ DEBUG ] 2020-12-09T01:16:56+0200 ] ...r/neovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp.lua:609 ]	"LSP[tsserver]"	"initialize_params"	{  capabilities = {    callHierarchy = {      dynamicRegistration = false,      <metatable> = <1>{        __tostring = <function 1>      }    },    textDocument = {      codeAction = {        codeActionLiteralSupport = {          codeActionKind = {            valueSet = { "", "RefactorInline", "source.organizeImports", "quickfix", "QuickFix", "Refactor", "Source", "RefactorRewrite", "refactor.inline", "RefactorExtract", "source", "SourceOrganizeImports", "refactor", "Empty", "refactor.rewrite", "refactor.extract" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        dynamicRegistration = false,        <metatable> = <table 1>      },      completion = {        completionItem = {          commitCharactersSupport = false,          deprecatedSupport = false,          documentationFormat = { "markdown", "plaintext" },          preselectSupport = false,          snippetSupport = false,          <metatable> = <table 1>        },        completionItemKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },          <metatable> = <table 1>        },        contextSupport = false,        dynamicRegistration = false,        <metatable> = <table 1>      },      declaration = {        linkSupport = true,        <metatable> = <table 1>      },      definition = {        linkSupport = true,        <metatable> = <table 1>      },      documentHighlight = {        dynamicRegistration = false,        <metatable> = <table 1>      },      documentSymbol = {        dynamicRegistration = false,        hierarchicalDocumentSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      hover = {        contentFormat = { "markdown", "plaintext" },        dynamicRegistration = false,        <metatable> = <table 1>      },      implementation = {        linkSupport = true,        <metatable> = <table 1>      },      references = {        dynamicRegistration = false,        <metatable> = <table 1>      },      rename = {        dynamicRegistration = false,        prepareSupport = true,        <metatable> = <table 1>      },      signatureHelp = {        dynamicRegistration = false,        signatureInformation = {          documentationFormat = { "markdown", "plaintext" },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      synchronization = {        didSave = true,        dynamicRegistration = false,        willSave = false,        willSaveWaitUntil = false,        <metatable> = <table 1>      },      typeDefinition = {        linkSupport = true,        <metatable> = <table 1>      },      <metatable> = <table 1>    },    workspace = {      applyEdit = true,      configuration = true,      symbol = {        dynamicRegistration = false,        hierarchicalWorkspaceSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workspaceFolders = true,      <metatable> = <table 1>    }  },  initializationOptions = vim.empty_dict(),  processId = 17831,  rootPath = "/Users/alexanderpopov/Documents/lokalise-tests",  rootUri = "file:///Users/alexanderpopov/Documents/lokalise-tests",  trace = "off",  workspaceFolders = { {      name = "/Users/alexanderpopov/Documents/lokalise-tests",      uri = "file:///Users/alexanderpopov/Documents/lokalise-tests"    } }}
[ DEBUG ] 2020-12-09T01:16:56+0200 ] ...ovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false,        <metatable> = <1>{          __tostring = <function 1>        }      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "RefactorInline", "source.organizeImports", "quickfix", "QuickFix", "Refactor", "Source", "RefactorRewrite", "refactor.inline", "RefactorExtract", "source", "SourceOrganizeImports", "refactor", "Empty", "refactor.rewrite", "refactor.extract" },              <metatable> = <table 1>            },            <metatable> = <table 1>          },          dynamicRegistration = false,          <metatable> = <table 1>        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = false,            <metatable> = <table 1>          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },            <metatable> = <table 1>          },          contextSupport = false,          dynamicRegistration = false,          <metatable> = <table 1>        },        declaration = {          linkSupport = true,          <metatable> = <table 1>        },        definition = {          linkSupport = true,          <metatable> = <table 1>        },        documentHighlight = {          dynamicRegistration = false,          <metatable> = <table 1>        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false,          <metatable> = <table 1>        },        implementation = {          linkSupport = true,          <metatable> = <table 1>        },        references = {          dynamicRegistration = false,          <metatable> = <table 1>        },        rename = {          dynamicRegistration = false,          prepareSupport = true,          <metatable> = <table 1>        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            documentationFormat = { "markdown", "plaintext" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false,          <metatable> = <table 1>        },        typeDefinition = {          linkSupport = true,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workspaceFolders = true,        <metatable> = <table 1>      }    },    initializationOptions = vim.empty_dict(),    processId = 17831,    rootPath = "/Users/alexanderpopov/Documents/lokalise-tests",    rootUri = "file:///Users/alexanderpopov/Documents/lokalise-tests",    trace = "off",    workspaceFolders = { {        name = "/Users/alexanderpopov/Documents/lokalise-tests",        uri = "file:///Users/alexanderpopov/Documents/lokalise-tests"      } }  }}
[ DEBUG ] 2020-12-09T01:16:57+0200 ] ...ovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      callsProvider = true,      codeActionProvider = true,      completionProvider = {        resolveProvider = true,        triggerCharacters = { ".", '"', "'", "/", "@", "<" }      },      definitionProvider = true,      documentFormattingProvider = true,      documentHighlightProvider = true,      documentSymbolProvider = true,      executeCommandProvider = {        commands = { "_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile" }      },      foldingRangeProvider = true,      hoverProvider = true,      implementationProvider = true,      referencesProvider = true,      renameProvider = true,      signatureHelpProvider = {        triggerCharacters = { "(", ",", "<" }      },      textDocumentSync = 2,      typeDefinitionProvider = true,      workspaceSymbolProvider = true    }  }}
[ DEBUG ] 2020-12-09T01:16:57+0200 ] ...ovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "initialized",  params = {    [true] = 6  }}
[ DEBUG ] 2020-12-09T01:16:57+0200 ] ...r/neovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp.lua:636 ]	"LSP[tsserver]"	"server_capabilities"	{  callsProvider = true,  codeActionProvider = true,  completionProvider = {    resolveProvider = true,    triggerCharacters = { ".", '"', "'", "/", "@", "<" }  },  definitionProvider = true,  documentFormattingProvider = true,  documentHighlightProvider = true,  documentSymbolProvider = true,  executeCommandProvider = {    commands = { "_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile" }  },  foldingRangeProvider = true,  hoverProvider = true,  implementationProvider = true,  referencesProvider = true,  renameProvider = true,  signatureHelpProvider = {    triggerCharacters = { "(", ",", "<" }  },  textDocumentSync = 2,  typeDefinitionProvider = true,  workspaceSymbolProvider = true}
[ INFO ] 2020-12-09T01:16:57+0200 ] ...r/neovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp.lua:637 ]	"LSP[tsserver]"	"initialized"	{  resolved_capabilities = {    call_hierarchy = false,    code_action = true,    completion = true,    declaration = false,    document_formatting = true,    document_highlight = true,    document_range_formatting = false,    document_symbol = true,    execute_command = true,    find_references = true,    goto_definition = true,    hover = true,    implementation = true,    rename = true,    signature_help = true,    signature_help_trigger_characters = { "(", ",", "<" },    text_document_did_change = 2,    text_document_open_close = true,    text_document_save = false,    text_document_save_include_text = false,    text_document_will_save = false,    text_document_will_save_wait_until = false,    type_definition = true,    workspace_folder_properties = {      changeNotifications = false,      supported = false    },    workspace_symbol = true  }}
[ DEBUG ] 2020-12-09T01:16:57+0200 ] ...ovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocument = {      languageId = "typescript",      text = "import { UploadFileType, generateKeysFile } from './__tests__/e2e/base/fileTemplates';\n\n['json']\n  .map((type) =>\n    generateKeysFile(type as UploadFileType, 'en', {\n      'just key': { translation: 'translation text' },\n      'key with a comment': { translation: 'translation text', comment: 'comments text' },\n      'key with a context': { translation: 'translation text', context: 'context text' },\n      'key with a description': { translation: 'translation text', description: 'description text' },\n      'key with a comment & context': {\n        translation: 'translation text',\n        comment: 'comments text',\n        context: 'context text',\n      },\n      'key with a comment & description': {\n        translation: 'translation text',\n        comment: 'comments text',\n        description: 'description text',\n      },\n      'key with a context & description': {\n        translation: 'translation text',\n        context: 'context text',\n        description: 'description text',\n      },\n      'key with a context & description & comment': {\n        translation: 'translation text',\n        comment: 'comments text',\n        context: 'context text',\n        description: 'description text',\n      },\n    })\n  )\n  .forEach((it) => console.log('='.repeat(20), `${it.name}\\n\\n${it.buffer.toString()}`));\nonsole.log([].filter((it) => it));\n",      uri = "file:///Users/alexanderpopov/Documents/lokalise-tests/tmp.ts",      version = 0    }  }}
[ DEBUG ] 2020-12-09T01:17:00+0200 ] ...ovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///Users/alexanderpopov/Documents/lokalise-tests/tmp.ts"  }}
[ DEBUG ] 2020-12-09T01:17:00+0200 ] ...r/neovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp.lua:471 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///Users/alexanderpopov/Documents/lokalise-tests/tmp.ts"}
[ DEBUG ] 2020-12-09T01:17:00+0200 ] ...ovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = 2552,        message = "Cannot find name 'onsole'. Did you mean 'console'?",        range = {          end = {            character = 6,            line = 33          },          start = {            character = 0,            line = 33          }        },        relatedInformation = { {            location = {              range = {                end = {                  character = 19,                  line = 19046                },                start = {                  character = 12,                  line = 19046                }              },              uri = "file:///Users/alexanderpopov/Documents/lokalise-tests/node_modules/typescript/lib/lib.dom.d.ts"            },            message = "'console' is declared here."          } },        severity = 1,        source = "typescript"      } },    uri = "file:///Users/alexanderpopov/Documents/lokalise-tests/tmp.ts"  }}
[ DEBUG ] 2020-12-09T01:17:00+0200 ] ...r/neovim/HEAD-85bce4d/share/nvim/runtime/lua/vim/lsp.lua:471 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = { {      code = 2552,      message = "Cannot find name 'onsole'. Did you mean 'console'?",      range = {        end = {          character = 6,          line = 33        },        start = {          character = 0,          line = 33        }      },      relatedInformation = { {          location = {            range = {              end = {                character = 19,                line = 19046              },              start = {                character = 12,                line = 19046              }            },            uri = "file:///Users/alexanderpopov/Documents/lokalise-tests/node_modules/typescript/lib/lib.dom.d.ts"          },          message = "'console' is declared here."        } },      severity = 1,      source = "typescript"    } },  uri = "file:///Users/alexanderpopov/Documents/lokalise-tests/tmp.ts"}
</details>

### Steps to reproduce using

So the issue is when im trying to use function 
`vim.lsp.diagnostic.get_count(vim.fn.bufnr('%'), [[Error]])`
i'm always having `0` as a result, and at the same time I can see errors in buffer/loclist/etc.

![image](https://user-images.githubusercontent.com/21224705/101553515-746f8580-39bd-11eb-8b38-c97e079f7d48.png)

**Comment by ckipp01** [comment]
When using `vim.lsp.diagnostic.get_count` you need to make sure you pass in both the buffer number (or 0 for current buffer) and also the diagnostic severity. So if you just use `vim.lsp.diagnostic.get_count()` it will return 0, whereas `vim.lsp.diagnostic.get_count(0, 'Warning')` or something may return what you're actually looking for. Did you call it with the correct params?

**Comment by alex-popov-tech** [comment]
yep, my bad, sorry.
thanks for help!
