### ISSUE TITLE
v:null and vim.NIL resolve to "null" when calling executable()

### ISSUE THREAD

**Issue by ojroques** [neovim/neovim#13485]
- `nvim --version`: `NVIM v0.5.0-dev+918-g4383c0f95`
- `vim -u DEFAULTS` (version: ) behaves differently? **yes**
- Operating system/version: Ubuntu 20.04 in WSL1
- Terminal name/version: `Windows Terminal Preview v1.5.3242.0`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`
1. Create an executable called "null" in your `$PATH`
2. Launch Neovim and execute `:echo executable(v:null)` or `:lua print(vim.fn.executable(vim.NIL))`

### Actual behaviour
The return value is 1. This is because one of the underlying C function of `executable()`, this one: https://github.com/neovim/neovim/blob/480515e4426865c37a42a452432b3463f0ab40a7/src/nvim/os/fs.c#L348 receives the string "null" in the `name` argument when we call `executable()` with `vim.NIL` or `v:null`. 

To me this is an unexpected behavior. In this scenario the C function should not receive a valid string which may resolve to an actual executable, even "null". I had such an executable on Windows which made [nvim-treesitter crash](https://github.com/nvim-treesitter/nvim-treesitter/issues/744) for instance.

This behavior is not present in vim, `executable(v:null)` correctly returns 0.

### Expected behaviour
Return 0.

**Comment by vigoux** [comment]
After investigation, the relevant vim patch seems to be : `v8.2.0103`

**Comment by janlazo** [comment]
Same issue with `v:true` and `v:false` resolving to an executable in Unix.

**Comment by janlazo** [comment]
Vim encodes booleans and null with `v:` prefix. Neovim doesn't.

**Comment by janlazo** [comment]
`Null` is considered executable because `executable()` performs case-insensitive comparisons on Windows when appending the file extensions to the filename.

**Comment by janlazo** [comment]
Neovim could diverge from Vim by restricting valid inputs to `executable` and similar functions to strings and numbers so that `executable(v:null)` always returns 0.

**Comment by jamessan** [comment]
> restricting valid inputs to `executable` and similar functions to strings and numbers so that `executable(v:null)` always returns 0.

That's seems pretty reasonable to me.  @brammool, what do you think?

**Comment by brammool** [comment]
This is a leftover from the times where you could use a number as a string, with automatic conversion.
The v:null would be converted to the string "null".
This fits in with the changes for Vim9 script, using more strict type checking.  I'll do that for a few builtin functions now, let's see how that goes.

**Comment by janlazo** [comment]
https://github.com/vim/vim/commit/7bb4e74c38642682cfdd0cb4052adfa5efdd7dd1
PRs welcome for a partial port without vim9 changes.
