### ISSUE TITLE
Choco install neovim --pre doesn't work

### ISSUE THREAD

**Issue by G-Ewing** [neovim/neovim#13480]
Currently trying to use the choco install for neovim nightly doesn't work. It gives an error message 

"ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found.""

**Comment by pnivlek** [comment]
#13312
