### ISSUE TITLE
can not run nightly nvim on older linux: GLIBC_2.29 not found.

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#13493]
I tried to run the nightly build from Linux on my Ubuntu 16.04 server. I am seeing the following runtime error:

> nvim-linux64/bin/nvim: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by nvim-linux64/bin/nvim)`

The output of `strings /lib/x86_64-linux-gnu/libm.so.6 |grep GLIBC` is:

```
GLIBC_2.2.5
GLIBC_2.4
GLIBC_2.15
GLIBC_2.18
GLIBC_2.23
GLIBC_PRIVATE
```

I have noticed that [Neovim now uses GitHub Action](https://github.com/neovim/neovim/issues/13312) to produce the nightly build.

The nightly build produced by the previous CI does not have this issue. Is there any reason to upgrade the GLIBC dependency? Or just by accident?
cc @jamessan

**Comment by jamessan** [comment]
> The nightly build produced by the previous CI does not have this issue. Is there any reason to upgrade the GLIBC dependency? Or just by accident?

I'm guessing you're using the tarball, not the appimage?  In that case, it's just an oversight that I was using the most recent Linux environment to build the release tarball.  Both the tarball and appimage will be built with the oldest support Linux environment with #13494.

**Comment by jdhao** [comment]
yes, I am using the release tarball. Thanks for the quick fix. 👍
