### ISSUE TITLE
No archived nightly build for Windows

### ISSUE THREAD

**Issue by qmfszxn0cmk** [neovim/neovim#13499]
[This](https://github.com/neovim/neovim/issues/13475) issue explains why there isn't a new binary available. However there also isn't an alternative (older) windows build for things like the [Neo Vim](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim) plugin for vsCode which requires version 0.5.0+

**Comment by erw7** [comment]
Now that the GHA builds are successful (#13540), the Windows nightly builds should eventually be released again. However, I think many people have misunderstood something. The nightly build is not intended for daily use by the average user. Therefore, it is wrong for external projects to rely on this.

**Comment by eddieparker** [comment]
>The nightly build is not intended for daily use by the average user. Therefore, it is wrong for external projects to rely on this.

While this totally makes sense, it looks like the VSCode plugin requires 0.5.0+ nightly, or so it states in it's documentation: https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim  

Might be nice to find out if they are just waiting some feature in the nightly that isn't released yet to get them off the nightly.
