### ISSUE TITLE
Fold + search results in wrong highlighting

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#13507]
- `nvim --version`: v0.5.0-dev+925-g00f60c2ce
- `vim -u DEFAULTS` (version: (8.0 - 2016 Sep 12, compiled Oct 13 2020) behaves differently? Yes
- Operating system/version: linux
- Terminal name/version: kitty 0.18.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Run `nvim -u NORC -i NONE -c 'set foldmethod=indent' /tmp/tmp.py` and paste the following:
```python
if A:
    pass
else:
    if B:
        pass
    else:
        pass
```

Search for `if B:` with `/`

### Actual behaviour
The `!A` branch is folded. The fold has the following text: `+-- 4 lines: if B:...`. ` 4 li` is highlighted.

### Expected behaviour
` 4 li` is not highlighted.

**Comment by subnut** [comment]
Just for the record,
This issue is not reproducible in `v0.4.4`

**Comment by teto** [comment]
thanks I can reproduce it. Would you prefer `if B:` ot be highlighted in the foldtext or nothing at all ?

**Comment by glacambre** [comment]
>Would you prefer if B: ot be highlighted in the foldtext or nothing at all ?

Both behaviors make sense to me so I don't really have a preference. Nothing at all is probably the easiest to implement, so I guess this should be chosen until someone comes and complains about it? :)

**Comment by subnut** [comment]
> until someone comes and complains about it? :)

I will be that someone :laugh:

@teto I highly prefer that fold highlights should remain as they currently are in v0.4.4
ie. Nothing gets highlighted till the fold gets opened

**Comment by teto** [comment]
Yeah I think it will be hidden behind a config setting as inlinefolds raise many usage questions without any behavior capable of pleasing everyone.

**Comment by subnut** [comment]
@teto Will it be possible in v0.5.0 to keep the fold highlighting **_exactly_** like v0.4.4 ?

**Comment by teto** [comment]
@glacambre I linked a PR with a fix + test if you wanna try/review. 

@subnut what changes do you refer to ? I think some changes are just iindisputably better, e.g., a coherent display of line column, taking into account CursorLine attribute when drawing the line and don't deserve a setting.  
The rest should remain unchanged (apart from this bug). I introduce a setting in  https://github.com/neovim/neovim/pull/13617 that will be used to enable new behaviors.

**Comment by glacambre** [comment]
Thanks for the fix, @teto! Sorry I wasn't able to review your PR, I had a busy weekend :).
