### ISSUE TITLE
init.lua doesn't load "exrc" files (.nvimrc, .exrc)

### ISSUE THREAD

**Issue by kristijanhusak** [neovim/neovim#13501]
- `nvim --version`: NVIM v0.5.0-dev+926-g99007bcc1
- `vim -u DEFAULTS` (version: ) behaves differently? - same
- Operating system/version: Manjaro Linux
- Terminal name/version: kitty 0.19.1
- `$TERM`: xterm-kitty

### Steps to reproduce:
```lua
--mininit.lua
vim.o.exrc = true
```

```vim
" .nvimrc in cwd
let g:test_from_nvimrc = 1
```

1. Open vim with minimal init.lua `nvim -u mininit.lua`
2. try `:echo g:test_from_nvimrc`

### Actual behaviour
Variable is undefined because `.nvimrc` is not loaded. I tried `.exrc` also, same thing.

### Expected behaviour
To print `1` in cmdline.

Edit: 
When sourcing the lua file from init.vim works.
```vim
" mininit.vim
lua require'mininit.lua'
```

```
nvim -u mininit.vim
:echo g:test_from_nvimrc
Prints 1
```

**Comment by fszymanski** [comment]
@kristijanhusak If I'm not mistaken the `.nvimrc` and `.exrc` are deprecated. They pose a security risk.

**Comment by kristijanhusak** [comment]
@fszymanski I don't think they are deprecated. They work fine with `init.vim`. There is `set secure` option to make them more secure. See `:help 'secure'`.

**Comment by teto** [comment]
if you launch with `-u`, nvim wont load .nvimrc or .exrc by design see `:h initialization`

**Comment by kristijanhusak** [comment]
@teto It happens even without `-u`.

**Comment by dm1try** [comment]
there is should be a way to use Lua only instead of mixing Lua and VimL for configs.
I would deprecate using VimL in `.nvimrc` in favor of Lua and leave VimL in `.exrc` only.

though I'm not a user of this feature :)

**Comment by kristijanhusak** [comment]
I agree with you. There should be a way to use `exrc` as lua, but I think we should just keep them backward compatible by default, and maybe introduce different file for lua.

**Comment by teto** [comment]
Its only logical now that we provide an init.lua that we load .exrc.lua/.nvimrc.lua (or similar). If we load an init.lua and nvim starts loading both .exrc and .exrc.lua it's messy. Right now I would vote for sticking to either lua or vimscript, ie., you look for .nvimrc.lua if you started with init.lua, and you look for .exrc if you started with init.vim. The user can choose to load the .exrc from the .exrc.lua for compatibility.

**Comment by kristijanhusak** [comment]
Currently none of the options work, and this fixes loading .exrc/.nvimrc in the old way as vimscript. I think we should start with the fix and then provide additional features.

**Comment by teto** [comment]
Currently it's an unreleased version so there is no need to implement a behavior we will change in 2 weeks time. Meanwhile you can use an init.vim that just runs `luafile myInit.lua ` and get back the old bheavior.

**Comment by kristijanhusak** [comment]
That's true. I have a workaround for it anyway, so it's not a rush for me.
I thought this was a bug, but if it was omitted intentionally (I guess @dm1try can tell, since he added [initial implementation](https://github.com/neovim/neovim/pull/12235)), then we can just close the PR and wait for the better solution.

**Comment by dm1try** [comment]
> I thought this was a bug, but if it was omitted intentionally (I guess @dm1try can tell, since he added initial implementation)

Yeah, it was done [intentionally](https://github.com/neovim/neovim/pull/12235#issuecomment-623189176).
I needed more context for the implementation of this feature but the naive expected behavior(mixing Lua init and VimL exrc) feels clumsy. On the other hand, adding `.nvimrc.lua` raises other questions like "What should we do with `secure` option?", so I postponed the implementation.


but I like @teto's proposal and I'm ready to implement it this weekend :)

**Comment by kristijanhusak** [comment]
My mistake, i didn't see that comment.
I closed my PR and i'll let you handle this however you planned :)

**Comment by teto** [comment]
secure option is going to be troublesome. It's off by default so in most cases it wouldn't be an issue. My naive idea would be to not load the .nvimrc.lua if secure is on (not sure how we can do otherwise, if there is some kind of safe/sandboxed lua).

**Comment by dm1try** [comment]
I thought a little bit about this functionality. Is there any profit in the implementation instead of just using
```lua
-- if some_condition or always
dofile('.nvimrc.lua')
``` 
in your `init.lua`?

**Comment by kristijanhusak** [comment]
I'm ok with it, but how does it solve "secure" issue?

**Comment by dm1try** [comment]
> I'm ok with it, but how does it solve "secure" issue?

Yeah, it is an another side of the issue. Though, outside of Lua context, I have great doubts that the `secure` option is "secure" at all(at least in Neovim, I've not checked Vim)
example
```viml
set secure
set exrc
```
`.nvimrc`
```viml
call termopen("touch evil.file")
```

it might be a different issue, though.

**Comment by dm1try** [comment]
btw
>  I've not checked Vim

vim has the same symptoms

`.vimrc`
```viml
term touch evil.file
```

there are might be other "holes", I just checked the first thing that came to my mind.

**Comment by kristijanhusak** [comment]
I'm generally not super worried about secure part anyway, not a lot of people use it/knows about it.

**Comment by dm1try** [comment]
> I'm ok with it, but how does it solve "secure" issue?

@kristijanhusak 
meanwhile, the similar behavior can be achieved by using some helpers 
with the semantic change proposed above(we do not load local rc at all for a "security" reason)

Example: 

`lua/local_rc.lua`
```lua 
local ffi = require("ffi")
local lfs = require("lfs")
ffi.cdef[[
 int getuid(void);
]]

local function file_owned_by_me(file)
  return ffi.C.getuid() == lfs.attributes(file).uid
end

local function file_exists(file)
  return lfs.attributes(file) ~= nil
end

local function load()
  local local_rc_name = ".nvimrc.lua"
  if (file_exists(local_rc_name)) then
    if (file_owned_by_me(local_rc_name)) then
      dofile(local_rc_name)
    else
      print(local_rc_name .. " exists but is not loaded. Security reason: a diffent owner.")
    end
  end
end

return {
   load = load
}
```

`init.lua`
```
require("local_rc").load()
```

what do you think?

**Comment by kristijanhusak** [comment]
I'm currently having this in my init.lua, just to satisfy my basic needs for this:

```lua
local local_vimrc = vim.fn.getcwd()..'/.nvimrc'
if vim.loop.fs_stat(local_vimrc) then
  vim.cmd('source '..local_vimrc)
end
```

Your solution also adds some security to it, so that's a nice add-on.

**Comment by dm1try** [comment]
`vim.loop.fs_stat` is useful, something I missed.

**Comment by languitar** [comment]
Looks like this issues isn't on the 0.5 roadmap but this seems to break existing behavior. Is it intended that this is left out? So far I have been using `.exrc` files for project-local settings. This doesn't work anymore now in 0.5 without adding the workaround from above.

**Comment by knpwrs** [comment]
What is the latest advice on this? Would anyone be interested in the workaround from https://github.com/neovim/neovim/issues/13501#issuecomment-758602763 as a plugin?

**Comment by zeertzjq** [comment]
It only works in v0.9
0-dev
