### ISSUE TITLE
cleanup: unused macro definitions

### ISSUE THREAD

**Issue by shade-of-noon** [neovim/neovim#13505]
While worrying about global variables, I got interested in the `State`
variable. It's only used in the `*.c` files for the most part. BUT then
I found this `CURSOR_BAR_RIGHT` macro which besides committing the sin
of sneakily depending on global state, it also seems to be unused (at
least the compilation process ran to success when I deleted it).

For some reason adding `-Wunused-macros` to the compilation flags
reports on a few other unused macros… and doesn't report on
`CURSOR_BAR_RIGHT`. I didn't check closely on whether these others
were false positives, to be sure.

So should this sneaky macro be removed (and possibly others according to
`-Wunused-macros`)? Or I missed something and it's a required macro
definition?

**Comment by vigoux** [comment]
I think it is a good think to add this `-Wunused-macros` flag, @jamessan am I right ?

**Comment by shade-of-noon** [comment]
Here's a list with the other "unused" macros I observed (and which I don't know whether they are false positives): [unused-macros.txt](https://github.com/neovim/neovim/files/5675966/unused-macros.txt)

**Comment by janlazo** [comment]
There are unmerged patches arabic.c and mbyte.c so set them aside for now.
Filter out `src/nvim/xdiff/` because it is maintained by Vim using the vim-patch process.
FIlter out code meant for vim9 or future vim patches. I added some macros listed in the text file for Vim compatibility.

Neovim-only unused macros are ok for removal.

**Comment by shanesmith** [comment]
I'd say keep `IS_LL_LIST` for consistency, but no strong opinions.

**Comment by janlazo** [comment]
SCTX_INIT is meant for `script_ctx` member of the `LastSet` type. It is currently useless because each `vimoption_T` implictly sets `last_set` member to `{ 0 }`. Need to explicity set it in the option generator script because Vim adds `sc_version` member to `sctx_T` which should be non-zero.

**Comment by justinmk** [comment]
> * `linenr_T_eq`, `uint32_t_hash`, `uint32_t_eq, linenr_T_hash`: introduced in
>   commit [44b2cef](https://github.com/neovim/neovim/commit/44b2cef83af798429f675b3f244d52c59a4a9047) (@bfredl, 2016). Neither MAP_IMPL nor MAP_DECLS was used
>   on `linenr_T` or `uint32_t`

could be removed I guess. Though they might be used later.

**Comment by bfredl** [comment]
hash functions for custom int aliases are trivial, so we could just as well remove them.
