### ISSUE TITLE
When using Visual and pasting a block. It paste the lines instead the block.

### ISSUE THREAD

**Issue by tadsn3w** [neovim/neovim#13519]
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Windows 10/WSL --> Fedora 29
- Terminal name/version: Terminator 2.01
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
The document you want to update with the list of items
This is line 1 "" for this.
This is line 2 "" for this.
This is line 3 "" for this.

The values you want to copy one per line.  i.e.
```
Item 1
Super Item 2
ITEM
```
Press Ctrl-V and select the first column of items and then press $
Visual shows a block selected only the characters from the list of items.  It does not add any space to any.
Go to the line you want to paste the block, and place the cursor between the ".
Press P for paste.

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
```

The result is:
This is line 1 "Item 1          " for this.
This is line 2 "Super Item 2" for this.
This is line 3 "ITEM            " for this.
```

### Expected behaviour
```
The result is:
This is line 1 "Item 1" for this.
This is line 2 "Super Item 2" for this.
This is line 3 "ITEM" for this.
```

**Comment by jdhao** [comment]
I do not think it is possible. The three lines to paste are not of equal length. If you copy them all in block mode, you will copy extra space. Isn't that expected?

**Comment by tadsn3w** [comment]
I can do that in some other editors such as vs code.  No spaces added.
In vs code is called cursors.  You create a cursor same as CTRL-v in vim.
I press the `end` key and the cursor selects all the values without any space same as Visual mode in nvim.
I go to the place I want to insert and paste it in vs code there are no extra spaces.  I can do the same with many other editors.
I was expecting nvim to do the same.

**Comment by tadsn3w** [comment]
Also, I forgot to add that the data selected does not contain any space.
When you select the values using the visual mode, you see the characters are selected without any space added.  When it is pasted then the spaces are added.

**Comment by amitds1997** [comment]
Visual block mode is a rectangular block and that's how it appears in the results too. In fact, there are supporting docs present for this too.

>```:help visual-block```
 With CTRL-V (blockwise Visual mode) the highlighted text will be a rectangle
between start position and the cursor.  ...

A little below after the documentation of `:help <LeftRelease>` it says:
> The start of the text is the Cursor position.  If the "$" command was used as
one of the last commands to extend the highlighted text, the area will be
extended to the rightmost column of the longest line.

And there is a section specially dedicated to this.
> ```:help v_$```
When the "$" command is used with blockwise Visual mode, the right end of the
highlighted text will be determined by the longest highlighted line.

So, although what you point out is a matter of convenience that even I would like, I don't think it's a bug.

**Comment by tadsn3w** [comment]
OK, I will give you that there is no bug.  It is documented, and it is working as planned.
IMHO is poorly implemented.  I don't mean it as an insult. I believe this option should be enhanced.
I am an old-timer that used VI in the late 80s early 90s.  I seldom use the visual mode because I am so used to mark and yank to copy multiple lines, to paste within the same file or a different file.  That tells you how old I am.  It is second nature for me.
I was forced to used different editors because my IT career took me in another direction.  I am glad that I am back using VI (nvim).  I guess I was expecting similar behavior from other text editors that provide that functionality.  I see VI (nvim) as one of the best text editors, and I hope this option can be implemented.
I will have to keep using nvim and partially use vscode to work out with the limitations of nvim.

**Comment by amitds1997** [comment]
Yes there should be a feature that should do this. I was totally bummed
because that's something even I use in VS Code. I'm sure there might be
extensions that would be making this possible. But doing text editing in
Vim should not be dependent upon an extension and I would totally love such
a feature in nvim.

**Comment by zeertzjq** [comment]
There are now "zp", "zP", and "zy" commands. (#14761)
