### ISSUE TITLE
Missing syntax hightlighting of Cython pxi-files

### ISSUE THREAD

**Issue by gerion0** [neovim/neovim#13513]
Cython files normally ends with pyx or pxd. However, Cython has another (C preprocessor like) include mechanism, which works with [pxi-files](https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#cython-file-types). neovim currently does not hightlight these files. I have fixed it locally with:
```
autocmd BufNewFile,BufRead *.pxi set ft=pyrex
```
It would be nice, if you can add it upstream.

**Comment by mhinz** [comment]
We merge the runtime patches from Vim, so they need to add it first.

Either create the same issue at https://github.com/vim/vim/issues or better yet, try contacting the maintainer of the pyrex runtime files. See `:e $VIMRUNTIME/syntax/pyrex.vim` for the maintainer's mail address.

Thanks!
