### ISSUE TITLE
PUM too small in small windows

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#13516]
- `nvim --version`: NVIM v0.5.0-828-g0a95549d6
- `vim -u DEFAULTS` (version: 8.2, 2019 Dec 12, compiled Nov 19 2020) behaves differently? No

### Steps to reproduce using `nvim -u NORC`

Save this as /tmp/init.vim:
```
set laststatus=0
set lines=6
set columns=75
set ft=markdown

au BufEnter * call nvim_buf_set_lines(0, 0, 0, 0, ["","Could you insert `ps -aef --forest -p $$ > /tmp/firenvim_tree` in ~/.local/share/"]) | call nvim_input("kA<C-x><C-f>")
```

Then run `nvim -u /tmp/init.vim -i NONE`.

### Actual behaviour

PUM is not wide enough to display its content.

### Expected behaviour

PUM is wide enough to display its content :).

**Comment by zeertzjq** [comment]
I don't think this is a bug. This is controlled by the 'pumwidth' option.

**Comment by glacambre** [comment]
I don't remember if this is what I saw when I wrote the reproducer, but here's what I'm seeing now:

![20230613_06h20m57s_grim](https://github.com/neovim/neovim/assets/11534587/b1438c4b-d154-410f-adc8-1ac90dc26839)

The PUM is not correctly placed. If it was placed correctly, the PUM could be larger, the way it is when the window is larger. I can understand choosing to classify the PUM width as working as expected, but the PUM placement is clearly wrong IMO.

**Comment by zeertzjq** [comment]
The PUM placement is correct. It should be aligned with the start of `~/.local/`, but that makes the PUM to small, so it's nudged to the left.

**Comment by glacambre** [comment]
It might be correct with regards to the code, but it does not seem correct in terms of providing the best user experience in my opinion. There clearly is room for providing more information, especially since the path is being completed from `share/`, so the PUM could be placed under the cursor after `share/` and be more useful to users.

**Comment by justinmk** [comment]
Is 'wrap' an important component of the repro (though it's a default)?

**Comment by glacambre** [comment]
@justinmk Yes, if `:set nowrap` is added to the reproducer's init.vim, the PUM gets wide enough to display useful information:

![20230615_07h51m32s_grim](https://github.com/neovim/neovim/assets/11534587/96d0ae78-66b1-4c40-978a-ff578c81b84c)
