### ISSUE TITLE
getwininfo(...)[0]['botline'] not updating for gg and G during WinScrolled event

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#13510]
- `nvim --version`: NVIM v0.5.0-dev+925-g00f60c2ce, NVIM v0.5.0-828-g0a95549d6
- `vim -u DEFAULTS` (version: ) behaves differently? Not applicable, as there is no WinScrolled event.
- Operating system/version: Ubuntu 20.04.1 LTS
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```

Go to the help page (or some other long document) with `:help`.

Create a `WinScrolled` handler that will show the value of `getwininfo(...)[0]['botline']`.

```
autocmd WinScrolled * :echo getwininfo(win_getid(winnr()))[0]['botline']
```

Then press G to go to the bottom of the document.

### Actual behaviour

The `botline` output that displays is `23` (this will depend on terminal size), which is the `botline` prior to the movement.

### Expected behaviour

The `botline` output would display `198`, corresponding to the bottom of the document.

The same issue also occurs with the `gg` movement.

When repeating the same experiment with `topline` instead of `botline`, the issue is not present. The `topline` corresponds to the actual top line that results from the movement. When repeating the same experiment with other movements that trigger `WinScrolled`, like `<ctrl-d>` or `j` or `k`, both `botline` and `topline` correspond to the actual lines that results from the movements.

**Comment by dstein64** [comment]
As a workaround, I've found a `botline` value can be correctly calculated as `l:wininfo.topline + l:wininfo.height - 1`, where `l:wininfo` is assigned `getwininfo(...)[0]`. This works when the value of `l:wininfo.botline` would otherwise have a lagging value, as described above.

**Comment by dstein64** [comment]
As a workaround, calling `redraw` prior to `getwininfo()` results in `botline` being correctly calculated.

**Comment by romgrk** [comment]
Yes, I actually avoided `botline` in the first implementation because updating it isn't free, due to folded lines. I'll try to find time to fix it soon.

**Comment by glacambre** [comment]
Slightly related to https://github.com/neovim/neovim/issues/13017 .
