### ISSUE TITLE
nvim_call_function from lua cannot return empty dict

### ISSUE THREAD

**Issue by stevearc** [neovim/neovim#13524]
Found and reported from https://github.com/nvim-lua/completion-nvim/pull/286

- `nvim --version`:
```
NVIM v0.5.0-dev+939-g4f9e7a512
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/stevearc/Downloads/neovim/build/config -I/home/stevearc/Downloads/neovim/src -I/home/stevearc/Downloads/neovim/.deps/usr/include -I/usr/include -I/home/stevearc/Downloads/neovim/build/src/nvim/auto -I/home/stevearc/Downloads/neovim/build/include
Compiled by stevearc@MSI

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```
- `vim -u DEFAULTS` (version: ) behaves differently? Nope, same issue
- Operating system/version: Ubuntu 18.04 running in WSL
- Terminal name/version: WSL 2
- `$TERM`: `screen-256color` (tmux)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
function F()
  return {}
endfunction
lua print(vim.inspect(vim.api.nvim_call_function('F', {})))
```

### Actual behaviour
```
{
  [true] = 6
}
```
### Expected behaviour
```
{}
```

### Additional information
I've also tried with python, and it seems to work fine there
```
python print(vim.api.call_function('F', []))
```

I tried adding a test to vim_spec.lua, but strangely enough the test *passed*.
https://github.com/neovim/neovim/blob/4f9e7a512dc606ddaff6dbfd78328077d685960d/test/functional/api/vim_spec.lua#L333
The test code I added:
```
      source([[
        function! F()
          return {}
        endfunction
      ]])
      eq({}, nvim('call_function', 'F', {}))
```

This behavior does *not* happen when using `vim.call('F')` from lua.

Based on all this, it seems like maybe an issue with serializing or deserializing dicts for lua specifically over the RPC connection?

**Comment by seandewar** [comment]
I believe that this is intended; from `:h lua-eval`:

> Lua tables are used as both dictionaries and lists, so it is impossible to
> determine whether empty table is meant to be empty list or empty dictionary.
> [...] To distinguish between these cases there is the following agreement:
>
> 0. Empty table is empty list.

And from `:h lua-special-dict':

> `{[vim.type_idx]=vim.types.dictionary}` is converted to an empty dictionary

You want to use `:h vim.fn` instead for this:

> Unlike vim.api.|nvim_call_function| this converts directly between Vim
> objects and Lua objects. [...] **Empty lists and dictionaries
> both are represented by an empty table.**

As you've seen, `vim.call()` can also be used to mitigate this, as it's equivalent to using `vim.fn`.
(see `:h vim.call()`)

Hope this clears things up!

**Comment by stevearc** [comment]
Thanks for the clarification! I looked through the docs on `nvim_call_function`, but didn't think to check `lua-eval` or `lua-special-dict`.
