### ISSUE TITLE
LspDiagnosticsChanged does not get triggered when diagnostics goes from having errors to having none

### ISSUE THREAD

**Issue by lucax88x** [neovim/neovim#13527]
- NVIM v0.5.0-dev+918-g4383c0f95
Build type: RelWithDebinfo
LuaJIT 2.1.0-beta3
- Operating system/version: Manjaro Kernel: 5.9.10-1-MANJARO 
- Terminal name/version:  kitty 0.19.1
- `$TERM`:

### Actual behaviour

When I make any error, and I see the error sign, and the virtual text, then the event LspDiagnosticsChanged gets triggered, and I can update my statusline properly.

But when I fix all my errors, and I then have a clean situation with no errors, this events does not get triggered.

This user is experiencing the same issue.

https://github.com/nvim-lua/lsp-status.nvim/issues/10#issuecomment-737203741

### Expected behaviour

When I fix all my errors I wants the LspDiagnosticsChanged to be triggered.

**Comment by joshfrench** [comment]
There's an open PR for this: https://github.com/neovim/neovim/pull/13483

**Comment by glacambre** [comment]
The mentionned PR has been merged so let's close this :).
