### ISSUE TITLE
HEAD build is crashing immediately on macOS

### ISSUE THREAD

**Issue by Svetlitski** [neovim/neovim#13529]
- `nvim --version`: NVIM v0.5.0-dev+82100a6bd
- Operating system/version: macOS Mojave 10.14.6 (18G6042)
- Terminal name/version: iTerm2 Build 3.4.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Press any key (for instance 'j')
```

### Actual behaviour
nvim displays  "Press ENTER or type command to continue"
Pressing Enter then quits nvim and leaves the terminal in a somewhat garbled state

![nvim_bug](https://user-images.githubusercontent.com/35482043/102038643-69d23900-3d8d-11eb-8167-c5f59bc5a64d.gif)

### Expected behaviour
nvim opens normally and responds to keypresses in a sensible way

**Comment by babariviere** [comment]
For those who want a workaround:

```sh
brew unlink luajit
brew install luajit --HEAD
```

**Comment by clason** [comment]
@babariviere Hmm, that doesn't work for me (Catalina, Intel); I then get
```
Failure while executing; `luarocks unpack --lua-dir=/usr/local/opt/luajit mpack-1.0.8-0.rockspec --tree=/private/tmp/neovim-20201214-13331-1x6jl68/deps-build` exited with 1. Here's the output:
```
(no output follows).

**Comment by babariviere** [comment]
@clason Can you show me the content of `/usr/local/opt/luajit/bin` please?

**Comment by clason** [comment]
It links to `luajit-2.1.0-beta3*`.

**Comment by babariviere** [comment]
I got your issue to @clason, I will take a look at the brew formula and try to fix it

**Comment by babariviere** [comment]
I have made a small PR to homebrew-core. This should partially fix the issue for `neovim`. I have not found a way to force `HEAD` version for brew dependencies.

So you will have to install `luajit HEAD` version anyway.

**New workaround**

For those who want it now, without waiting for the merge, you can do the following:

```bash
brew unlink luajit
brew install babariviere/core/luajit --HEAD
brew reinstall neovim
```

**NOTE: Please be aware that you will have to uninstall it when the branch is merged. I will not maintain this repository. I will notify this issue when it's merged.**
To remove it, you will have to do:

```bash
brew remove babariviere/core/luajit
brew install luajit --HEAD
brew reinstall neovim
```

**Comment by clason** [comment]
In the meantime, you can just clone this repo and `make install` (making sure you have the [build prerequisites](https://github.com/neovim/neovim/wiki/Building-Neovim#macos) installed; you don't need the full XCode, by the way).

**Comment by number5** [comment]
```
brew unlink luajit
brew install luajit --HEAD
```
^ this works for me, but I'm on Mojave (10.14.6)

**Comment by Svetlitski** [comment]
Unfortunately neither of the above workarounds ([here](https://github.com/neovim/neovim/issues/13529#issuecomment-744275940) and  [here](https://github.com/neovim/neovim/issues/13529#issuecomment-744375133)) work for me. `brew reinstall neovim` installs the latest stable version, not the nightly. Following all the other steps in [this workaround](https://github.com/neovim/neovim/issues/13529#issuecomment-744375133) but replacing `brew reinstall neovim` with `brew rm neovim && brew install --HEAD neovim` also doesn't work. Is there any workaround for the nightly build?

**Comment by babariviere** [comment]
@number5 the only issue you will have with this is that you won't be able to rebuild neovim

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/pull/66899 has been merged.

**Comment by babariviere** [comment]
You can now do:

```
brew remove babariviere/core/luajit
brew install luajit --HEAD
brew reinstall neovim
```

_Only if you have installed my fork version_

**Comment by gwerbin** [comment]
@babariviere thanks so much for the workaround and the Homebrew formula patch!

**Comment by carlocab** [comment]
I updated the installation instructions in the wiki: https://github.com/neovim/neovim/wiki/Installing-Neovim

I left out the explanation of having to do `brew install --HEAD luajit`; not sure if that needs to go in there.

**Comment by miguel550** [comment]
I tried `brew install --HEAD luajit` and it says 
`Error: luajit: no bottle available!
You can try to install from source with e.g.
  brew install --build-from-source luajit`
This is after I did `brew uninstall --ignore-dependencies luajit` because I had installed luajit latest version with `brew unlink luajit
brew install babariviere/core/luajit --HEAD` to fix the problem. Can anyone point me to what should I do to make it work?

**Comment by glepnir** [comment]
> ```
> brew uninstall --ignore-dependencies luajit
> brew install luajit --HEAD
> brew reinstall neovim
> ```

works for me 
![image](https://user-images.githubusercontent.com/41671631/102436804-50164780-4054-11eb-8f1a-cd1722dc8fae.png)

**Comment by Svetlitski** [comment]
Closing as this has been resolved. As a closing note, if you run into "no bottle available" issues like @miguel550 did above (as did I) running the following should fix it:
```
brew install --build-from-source --HEAD luajit
brew install --build-from-source --HEAD neovim
```

**Comment by glepnir** [comment]
@Svetlitski  It seems like you should reinstall `xcode-select`

**Comment by miguel550** [comment]
Thanks @Svetlitski ! That worked!

**Comment by RobertoMaurizzi** [comment]
Is there any way to switch from a bottled `0.4.4` to a source-compiled `HEAD-82100a6` without removing everything and reinstalling from scratch?
`brew switch` is now disabled, `brew switch` doesn't know HEAD, `brew reinstall` also can't do `--build-from-source --HEAD`...
I'm in a place with slow and expensive internet :-/

**Comment by carlocab** [comment]
Try

    brew unlink neovim
    brew install —HEAD neovim

**Comment by bapjiws** [comment]
@Svetlitski, thank you, the commands worked, but now `:checkhealth` gives me 

```bash
Invalid $VIMRUNTIME :/usr/local/Cellar/neovim/0.4.4/share/nvim/runtime
```

Anybody know how to fix it? Thanks! 🙂

**Comment by bapjiws** [comment]
@Svetlitski, thank you, the commands worked, but now `:checkhealth` gives me 

```bash
Invalid $VIMRUNTIME :/usr/local/Cellar/neovim/0.4.4/share/nvim/runtime
```

Should I run the `:set runtimepath?` command (looking at the [Wiki](https://github.com/neovim/neovim/wiki/FAQ#neovim-cant-find-its-runtime)) and use 

```
fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-7b65a91/share/nvim"
``` 

that those commands gave me at the end? Thanks! 🙂

**Comment by clason** [comment]
That means the installation did not fully work. Either try `brew link --overwrite neovim` after `brew install ...`, or `brew uninstall neovim` _before_  reinstalling it from `HEAD`.

**Comment by RobertoMaurizzi** [comment]
> brew install --HEAD neovim

It simply says it's already installed. Anyway thanks, I thought I wasn't seeing something very obvious in how to do it, but apparently it's breakage in how homebrew managed this deprecation. I guess I'll open an issue there (since I couldn't find anything about how to manage link/switch with bottled/HEAD versions after their change...)

**Comment by clason** [comment]
It's easy: `brew remove neovim` first, then you can `brew install --HEAD`.

**Comment by carlocab** [comment]
>It's easy: `brew remove neovim` first, then you can `brew install --HEAD`.

They were trying to avoid doing `brew remove` though:

>without removing everything and reinstalling from scratch

**Comment by sbernheim4** [comment]
I'm still not able to successfully install neovim with any of the steps outlined here...

Is `brew install --HEAD neovim` working for everyone now? I still see the same error: 
```
 nvim -v
NVIM v0.5.0-dev+4dfc5bb2d
Build type: Release
/Users/sbernheim
Vim: Finished.
E970: Failed to initialize lua interpreter
```

If all the fixes are merged, what now are the correct install steps? 

[The updated install instructions](https://github.com/neovim/neovim/wiki/Installing-Neovim#homebrew-on-macos-or-linux) aren't working for me.

Is there any other advice or guidance? Should I remove and reinstall homebrew?

**Comment by carlocab** [comment]
Try
```
brew uninstall neovim
brew uninstall --ignore-dependencies luajit
brew install --HEAD luajit
brew install --HEAD neovim
```

**Comment by sbernheim4** [comment]
The last two commands fail with the same error reported above: 

```
 brew install --HEAD luajit
Error: luajit: no bottle available!
You can try to install from source with e.g.
  brew install --build-from-source luajit
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
``` 
I tried then doing 
```
brew install --HEAD --build-from-source luajit
brew install --HEAD --build-from-source neovim
```

The installation succeeds but leads to the original issue where neovim doesn't start successfully

**Comment by carlocab** [comment]
What does `luajit --version` say? And what is the output of `brew config`?

**Comment by sbernheim4** [comment]
Luajit Info:
```
 luajit -v
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2020 Mike Pall. https://luajit.org/
```

Brew Info:
```
 brew config
HOMEBREW_VERSION: 2.7.0-68-g5818b28
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5818b284797cb470d49b0d63edaffd5283e3dc2f
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 999cebdc20b6435eb10c460a74f071850bda328d
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 11.0 build 1100
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 15.0.1, 10.0.2, 1.8.0_275, 1.8.0_131
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
```

**Comment by XVilka** [comment]
Should this issue be unpinned since closed?
