### ISSUE TITLE
Building Neovim fails on M1 Mac in both Rosetta and Native

### ISSUE THREAD

**Issue by TC72** [neovim/neovim#13533]
I've obviously done something very wrong as I get similar error messages when I try to build manually in a native iTerm or install via homebrew -s in a rosetta iterm.

My system is a 16G M1 Mac Mini running iOS 11.0.1.

To build on apple silicon I did:
```
git clone git@github.com:neovim/neovim
cd neovim
make distclean
echo "DEPS_CMAKE_FLAGS += -DCMAKE_OSX_DEPLOYMENT_TARGET=11.00" > local.mk
make SDKROOT=`xcrun --show-sdk-path`
```

This gives error

```
ninja  -C build
ninja: Entering directory `build'
[234/291] Building C object src/nvim/CMakeFiles/nvim.dir/os/lang.c.o
FAILED: src/nvim/CMakeFiles/nvim.dir/os/lang.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=1 -DNVIM_MSGPACK_HAS_FLOAT32 -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -isystem /usr/local/opt/gettext/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/os/lang.c.o -MF src/nvim/CMakeFiles/nvim.dir/os/lang.c.o.d -o src/nvim/CMakeFiles/nvim.dir/os/lang.c.o -c ../src/nvim/os/lang.c
../src/nvim/os/lang.c:63:5: error: implicit declaration of function 'setlocale' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    setlocale(LC_ALL, "");
    ^
../src/nvim/os/lang.c:63:15: error: use of undeclared identifier 'LC_ALL'; did you mean 'P_ALL'?
    setlocale(LC_ALL, "");
              ^~~~~~
              P_ALL
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:80:2: note: 'P_ALL' declared here
        P_ALL,
        ^
2 errors generated.
[243/291] Building C object src/nvim/CMakeFiles/nvim.dir/option.c.o
ninja: build stopped: subcommand failed.
make: *** [nvim] Error 1
```

In the Rosetta iTerm:
```
brew install ninja libtool automake cmake pkg-config gettext
brew install -s --HEAD neovim
```

Which gives this error:
```
cd /tmp/neovim-20201214-72905-1msxk8r/build/src/nvim && /usr/bin/clang -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -D_GNU_SOURCE -Dnvim_EXPORTS -I/tmp/neovim-20201214-72905-1msxk8r/build/config -I/tmp/neovim-20201214-72905-1msxk8r/src -I/tmp/neovim-20201214-72905-1msxk8r/build/src/nvim/auto -I/tmp/neovim-20201214-72905-1msxk8r/build/include -I/usr/local/include/luajit-2.0 -isystem /usr/local/include -isystem /tmp/neovim-20201214-72905-1msxk8r/deps-build/include -isystem /usr/local/opt/gettext/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -flto=thin -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -o CMakeFiles/nvim.dir/os/time.c.o -c /tmp/neovim-20201214-72905-1msxk8r/src/nvim/os/time.c
/tmp/neovim-20201214-72905-1msxk8r/src/nvim/os/lang.c:63:15: error: use of undeclared identifier 'LC_ALL'; did you mean 'P_ALL'?
    setlocale(LC_ALL, "");
              ^~~~~~
              P_ALL
/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include/sys/wait.h:80:2: note: 'P_ALL' declared here
        P_ALL,
        ^
2 errors generated.
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/os/lang.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 50%] Building C object src/nvim/CMakeFiles/nvim.dir/os/tty.c.o
cd /tmp/neovim-20201214-72905-1msxk8r/build/src/nvim && /usr/bin/clang -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -D_GNU_SOURCE -Dnvim_EXPORTS -I/tmp/neovim-20201214-72905-1msxk8r/build/config -I/tmp/neovim-20201214-72905-1msxk8r/src -I/tmp/neovim-20201214-72905-1msxk8r/build/src/nvim/auto -I/tmp/neovim-20201214-72905-1msxk8r/build/include -I/usr/local/include/luajit-2.0 -isystem /usr/local/include -isystem /tmp/neovim-20201214-72905-1msxk8r/deps-build/include -isystem /usr/local/opt/gettext/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -flto=thin -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -o CMakeFiles/nvim.dir/os/tty.c.o -c /tmp/neovim-20201214-72905-1msxk8r/src/nvim/os/tty.c
make[1]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make: *** [all] Error 2
```

I can see in the error message for the rosetta version it mentions -arch arm64 so I've definitely screwed things up as the Rosetta one shouldn't be using that.

**Comment by clason** [comment]
First, `brew install` is known to be broken; see #13529 (and try the workaround @babariviere posted).

Second, the error message looks related to changes in locales (and environment variables) in macOS shells. Can you try manually setting `LC_ALL=en_US.UTF-8` for `make`?

**Comment by TC72** [comment]
> First, `brew install` is known to be broken; see #13529 (and try the workaround @babariviere posted).
> 
> Second, the error message looks related to changes in locales (and environment variables) in macOS shells. Can you try manually setting `LC_ALL=en_US.UTF-8` for `make`?

I'm in the UK, running locale showed this:
```
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

I set LC_ALL using ```export LC_ALL="en_GB.UTF-8"```

It was shown when running locale but I had the same error message when running make. Am I setting this in the wrong way for make to use it?

**Comment by clason** [comment]
I have 
```
LANG=""
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```
But I am using `fish`, where I know how to set environment variables... Apple's latest `zsh` behaves seriously weird in this respect. 

Can you try `LC_ALL="en_GB.UTF-8" make`? Or `bash`, with `LC_ALL` set in `.bash_profile` (may need to log out and back in for that)?

**Comment by TC72** [comment]
I'm not getting anywhere, wondering if Apple's move to zsh is causing some of the issues. 
I've added that to .zshrc but I'm still getting the same type of errors about LC_ALL if I'm building the native or the Rosetta version.

**Comment by clason** [comment]
Do you have XCode installed or are you using the CLI? My suspicion is also Apple's changes to `zsh`. Things to try:
1. use `Terminal.app` (which is special-cased by Apple, adding insult to injury);
2. set the variables in `.zshenv`;

When you say "`locale` shows...", what do you mean precisely? If you `export` the variable, does `locale` pick it up? If it does, do `make distclean` to make sure the previous, empty, version isn't cached.

**Comment by TC72** [comment]
Yes, I have Xcode installed, just realised I'd never opened it so I did for it to install components.
Exactly the same from terminal, here's the output along with me checking for the variable straight after.

```
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/julianf/Code/neovim/build
touch build/.ran-cmake
ninja  -C build
ninja: Entering directory `build'
[237/291] Building C object src/nvim/CMakeFiles/nvim.dir/os/lang.c.o
FAILED: src/nvim/CMakeFiles/nvim.dir/os/lang.c.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=1 -DNVIM_MSGPACK_HAS_FLOAT32 -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -isystem /usr/local/opt/gettext/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/os/lang.c.o -MF src/nvim/CMakeFiles/nvim.dir/os/lang.c.o.d -o src/nvim/CMakeFiles/nvim.dir/os/lang.c.o -c ../src/nvim/os/lang.c
../src/nvim/os/lang.c:63:5: error: implicit declaration of function 'setlocale' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    setlocale(LC_ALL, "");
    ^
../src/nvim/os/lang.c:63:15: error: use of undeclared identifier 'LC_ALL'; did you mean 'P_ALL'?
    setlocale(LC_ALL, "");
              ^~~~~~
              P_ALL
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/wait.h:80:2: note: 'P_ALL' declared here
        P_ALL,
        ^
2 errors generated.
[246/291] Building C object src/nvim/CMakeFiles/nvim.dir/option.c.o
ninja: build stopped: subcommand failed.
make: *** [nvim] Error 1
Mac-mini neovim % echo $LC_ALL                        
en_GB.UTF-8
```

I thought earlier I'd managed to get it to show when you run ```locale``` but it isn't now and my history doesn't show me what I did, so ignore that part as no idea if I really did it.

**Comment by jamessan** [comment]
This has nothing to do with your shell environment.  The compiler is complaining that it doesn't know what the `LC_ALL` identifier is.  This is inside an `#ifdef HAVE_LOCALE_H` block, so we know that we've included locale.h.

Something is very wrong with your build environment.  There's no reason we should be successfully including locale.h but be missing `LC_ALL`.

**Comment by clason** [comment]
🤦 

Sounds like the SDK is not correctly set up or picked up; this may happen if you have an outdated Xcode or Command Line Tools lying around. Try removing Xcode _and_ the CLT (`sudo rm -rf /Library/Developer/CommandLineTools/`) and then reinstalling the CLT (`xcode-select --install`).

**Comment by TC72** [comment]
I'll try anything at this point. This is a brand new machine, the only things I brought from my previous computer were folders of development work, nothing that should touch the system.
I installed some standard Apps and Xcode.
Since trying to get neovim working I have been using homebrew to install things I need.
I installed the native homebrew as directed into /opt and I've setup a duplicate iTerm set to use Rosetta. Today I used the homebrew installed there along with brew bundle to bring over more tools I use, but that was after all these issues.

**Comment by clason** [comment]
Still, I'd recommend using the CLT for homebrew. Also wipe the neovim repo and re-clone (or `git clean -fdx`; you should _not_ need to do anything special beyond  `CMAKE_BUILD_TYPE=RelWithDebInfo make` since the PR is merged anymore.

**Comment by TC72** [comment]
I removed Xcode and CLT, rebooted ran xcode-select --install.
Now `brew doctor` tells me 
```
Warning: Your Xcode (11.3.1 => /Volumes/Mac/Applications/Xcode.app/Contents/Developer) is too outdated.
Please update to Xcode 12.2 (or delete it).
Xcode can be updated from the App Store.
```

**Comment by clason** [comment]
Yeah, you need to either delete Xcode (as I wrote), or go to the Preferences there and set the build tools to the CLT.

**Comment by TC72** [comment]
I did delete xcode, which was 12.2.
You told me to delete Xcode and CLT and I did exactly that.
When I ran  `xcode-select --install` it installed 11.3.1.

I can see you're getting annoyed by this but I'm trying to follow exactly what you're telling me to do.

**Comment by clason** [comment]
No, sorry, I didn't mean to come across as annoyed, sorry.

But the error message points to an Xcode installation, not a CLT installation (these live in `/Library/Developer/CommandLineTools`). So there seems to be some stale Xcode config lying around. Maybe you transferred your user directory from another machine?

**Comment by TC72** [comment]
There's no need to apologize, I really appreciate your help, I just wanted to show I am trying to follow your instructions to the letter.

There were 2 directories copied over, 1 full of xcode projects and another one full of web sites I develop.
I didn't open any of those xcode projects. But during all this I've had a hard disk mounted which is my old system.

I installed Xcode 12.2 but didn't open it, I may have used a command like `xcode-select --install` to try to install the command line tools. I've been reading so many guides today I've lost track of everything I tried. 

I installed apple silicon homebrew into /opt as recommended and used a duplicate version of Iterm to install rosetta homebrew.

Where I may have f**ked everything up is trying to run an old homebrew install from my backup hard disk. I'd read about using `brew bundle build` but my old computer is in pieces so I tried to run this direct from my old installation.

**Comment by clason** [comment]
No worries!

So this sounds indeed like crossed wires in your installation. If you've removed all Xcode instances from your drives, it _might_ be enough to remove and then reinstall the CLT (sorry for making you download so many MB...); the installation should then (re)set all the relevant links and build settings. (Maybe you can also set this without reinstallation with `xcode-select --switch <path>`.)

Otherwise (and if you _want_ to have Xcode installed), you should indeed open the new Xcode and look through the options for a drop-down menu where you can select from the installed dev environment (Xcode, CLT, ...) which should be used from the terminal. (It's been a long while since I used Xcode, so I can't be more specific, unfortunately.)

**Comment by TC72** [comment]
No problem, I've just downloaded Xcode 12.3 as it was released today. I've never installed the CLT without Xcode as I definitely want Xcode for an App I develop.

If I don't get any luck I'll probably wipe the whole computer and start again. I knew I was taking a risk moving to an M1 Mac but thought the Rosetta Neovim would work without any problems, BUT I've got used to things from 0.5 so I should have known that wouldn't be simple.

**Comment by clason** [comment]
I don't think M1 per se should be the problem; a fresh install followed by manually copying what you need usually works better on a new machine, though. But in this case, (re)downloading Xcode 12.3, opening it, and going through the preferences to find the dropdown menu to set the default build environment to Xcode 12.3 should fix it.

**Comment by TC72** [comment]
I installed Xcode 12.3 from the App Store.
Manually downloaded Command Line Tools from https://developer.apple.com/download/more/
After installing the command line tools I ran `sudo xcode-select -s /Library/Developer/CommandLineTools`
That was in a normal iTerm zsh running natively.
Cloned neovim with `git clone git@github.com:neovim/neovim`
cd into neovim and ran `CMAKE_BUILD_TYPE=RelWithDebInfo make`

Got the same error:
```
../src/nvim/os/lang.c:63:5: error: implicit declaration of function 'setlocale' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    setlocale(LC_ALL, "");
```

Tried exactly the same on a version of iTerm running under Rosetta, used a simple make and the outcome was exactly the same.

**Comment by clason** [comment]
Then I'm officially out of ideas. 😞 I just know that it _does_ work for me on Intel Big Sur and for others on Apple silicon, following the steps you describe.

**Comment by TC72** [comment]
No problem, thanks for trying.

**Comment by TC72** [comment]
There was someone else who had an identical problem, so it's not just something I'm doing wrong:
https://github.com/neovim/neovim/issues/13531

**Comment by shesanth** [comment]
I'm facing this same issue. New machine, arrived today. I haven't installed xcode yet, but  can see I'm using `xcode-select version 2384`.

**Comment by mpcsh** [comment]
hi, I'm the OP for #13531. I've tried all combinations of rosetta and native brew, CLT and full xcode, and so far every combination produces the same undeclared identifier error for `LC_ALL`.

**Comment by TC72** [comment]
> I'm facing this same issue trying to `brew install --HEAD neovim` New machine, arrived today. I'm trying to build using Rosetta. I'm using `xcode-select version 2384`.



> hi, I'm the OP for #13531. I've tried all combinations of rosetta and native brew, CLT and full xcode, and so far every combination produces the same undeclared identifier error for `LC_ALL`.

Since this may be linked to locale, can I ask where you are form? I'm from the UK.

**Comment by shesanth** [comment]
I'm from the US. my locale looks like:

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

And as was mentioned earlier, I'm not so sure this is the issue.

**Comment by TC72** [comment]
Using this you can get around the LC_ALL error but you just move on to another one: 
 
https://github.com/qvacua/neovim/commit/fa3253ee8644654fca0a581de89fd33dcdcd268c

I've now downloaded a nightly binary so I can get on with work:  
https://github.com/neovim/neovim/releases/tag/nightly

Also contacted someone from another thread who was successful if they could come and explain their steps.

**Comment by jamessan** [comment]
@TC72 Can you try #13538?

**Comment by TC72** [comment]
> @TC72 Can you try #13538?

That's a bingo!!

Thank you so much for sorting that out.

**Comment by mpcsh** [comment]
unfortunately that just moved me on to a new error:
```
dotfiles on  main
❯ ibrew install --HEAD neovim
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
modern-csv

==> Downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz
Already downloaded: /Users/mpcsh/Library/Caches/Homebrew/downloads/4b91349796a66e38e93acd77e6ca14212c869090429fd88271def2be5293d83f--libmpack-lua-1.0.8.tar.gz
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.2-1.src.rock
Already downloaded: /Users/mpcsh/Library/Caches/Homebrew/downloads/0bc17975f0cf3981083172aa7da329b874e5780fa81494f5dd07d0665fcec23b--lpeg-1.0.2-1.src.rock
==> Downloading https://luarocks.org/manifests/kikito/inspect-3.1.1-0.src.rock
Already downloaded: /Users/mpcsh/Library/Caches/Homebrew/downloads/ecc1fa84ce4c83c9406f6d1202d4a88c80ede4a0a2bfd8d8d2bd54fd042226bb--inspect-3.1.1-0.src.rock
==> Downloading https://github.com/keplerproject/lua-compat-5.3/archive/v0.7.tar.gz
Already downloaded: /Users/mpcsh/Library/Caches/Homebrew/downloads/5f4e552e95b9a6223a5e4fabb7f04bf4b886057024507c76b1d5b803218c9363--lua-compat-5.3-0.7.tar.gz
==> Downloading https://github.com/luvit/luv/releases/download/1.30.0-0/luv-1.30.0-0.tar.gz
Already downloaded: /Users/mpcsh/Library/Caches/Homebrew/downloads/a9ce5a949370965d8f0fe70a47e7d102a3b4b6b831dbd4d088a83bbe1c00a3a2--luv-1.30.0-0.tar.gz
==> Cloning https://github.com/neovim/neovim.git
Updating /Users/mpcsh/Library/Caches/Homebrew/neovim--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at c3b9c35 Merge pull request #13538 from jamessan/mac-locale
==> luarocks make --lua-dir=/usr/local/opt/luajit --tree=/private/tmp/neovim-20201216-31835-gzh3z7/deps-build
==> luarocks make --lua-dir=/usr/local/opt/luajit --tree=/private/tmp/neovim-20201216-31835-gzh3z7/deps-build
==> luarocks make --lua-dir=/usr/local/opt/luajit --tree=/private/tmp/neovim-20201216-31835-gzh3z7/deps-build
==> cmake . -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_INSTALL_PREFIX=/private/tmp/neovim-20201216-31835-gzh3z7/deps-build -DLUA_BUILD_TYPE=S
==> make install
==> cmake .. -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DLIBLUV_INCLUDE_DIR=/private/tmp/neovim-20201216-31835-gzh3z7/deps-build/include -DLIBLUV_LI
==> make install
Last 15 lines from /Users/mpcsh/Library/Logs/Homebrew/neovim/07.make:
        __attribute__((fallthrough));
/tmp/neovim-20201216-31835-gzh3z7/src/nvim/viml/parser/expressions.c:3033:9: note: insert 'break;' to avoid fall-through
        case kExprNodeInteger:
        ^
        break;
/tmp/neovim-20201216-31835-gzh3z7/src/nvim/viml/parser/expressions.c:3047:9: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
        case kExprNodeComma:
        ^
/tmp/neovim-20201216-31835-gzh3z7/src/nvim/viml/parser/expressions.c:3047:9: note: insert 'break;' to avoid fall-through
        case kExprNodeComma:
        ^
        break;
3 warnings generated.
make[1]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make: *** [all] Error 2
```

not really sure what's going on here as there are clearly `break`s. should I make a new issue for this?

**Comment by yingzhu146** [comment]
moving my comment over from #12624 - thanks for pointing me over @TC72 !

Unfortunately - this isn't fixed for me even with #13538  - still getting the exact same error (I pulled from master and this PR was merged in master 2 days ago). I've removed the repo and re-cloned so this newest change was included but the error persists


```
FAILED: src/nvim/CMakeFiles/nvim.dir/tui/tui.c.o 
/Library/Developer/CommandLineTools/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -isystem /opt/local/include -isystem /Library/Frameworks/R.framework/Headers -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g  -flto=thin -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/tui/tui.c.o -MF src/nvim/CMakeFiles/nvim.dir/tui/tui.c.o.d -o src/nvim/CMakeFiles/nvim.dir/tui/tui.c.o -c ../src/nvim/tui/tui.c
../src/nvim/tui/tui.c:552:7: error: no member named 'i' in 'unibi_var_t'
      UNIBI_SET_NUM_VAR(data->params[0], standout);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/nvim/tui/tui.c:68:43: note: expanded from macro 'UNIBI_SET_NUM_VAR'
#define UNIBI_SET_NUM_VAR(var, num) (var).i = (num);
                                    ~~~~~ ^
../src/nvim/tui/tui.c:553:7: error: no member named 'i' in 'unibi_var_t'
      UNIBI_SET_NUM_VAR(data->params[1], underline);
```

**Comment by mpcsh** [comment]
@yingzhu146 if I try to manually build this repo rather than `brew install --HEAD`, I get the same error as you.

**Comment by garrettoreilly** [comment]
`brew install -s --HEAD neovim` works for me now, though I needed to `brew install --HEAD luajit` first.

**Comment by VimalMollyn** [comment]
> `brew install -s --HEAD neovim` works for me now, though I needed to `brew install --HEAD luajit` first.

This works for me as well. Thanks!

**Comment by TC72** [comment]
This is broken for me today after updating to Big Sur 11.2.2.
Errors related to runtime/docs/tags
