### ISSUE TITLE
Nvim doesn't work if you install the nightly version using brew

### ISSUE THREAD

**Issue by DuGlaser** [neovim/neovim#13530]
- `nvim --version`: NVIM v0.5.0-dev+nightly-351-g82100a6bd
- `vim -u DEFAULTS` (version: 8.2) behaves differently? Yes
- Operating system/version: macOS 11.0.1
- Terminal name/version: zsh

### Steps to reproduce using `nvim -u NORC`
- Install neovim: ``brew install --HEAD neovim
- run: ``nvim -u NORC``

### Actual behaviour
nvim starts, but quits when I press any key

Also, when I run ``nvim --version``, I get the following message
```
NVIM v0.5.0-dev+nightly-351-g82100a6bd
Build type: Release
/Users/<user_name>
Vim: Finished.
E970: Failed to initialize lua interpreter
```
### Expected behaviour
Start nvim normally.

**Comment by DuGlaser** [comment]
Same issue #13529

**Comment by clason** [comment]
closing in favor of #13529 (because that contains a workaround)
