### ISSUE TITLE
excmds: document flexible typing rules for :echomsg

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#13542]
In Neovim version 0.4.0 (stable release). The command `:echomsg 12.0` results in following error:

> E806: using Float as a String

In Neovim version 0.5.0 (nightly release). The same command runs without any error.

Is this the intended behavior? I can not seem to find any info related to this.

**Comment by bfredl** [comment]
I think it should be. You could bisect it to find the relevant PR :)

**Comment by janlazo** [comment]
It is intended. See https://github.com/neovim/neovim/pull/11805 and the vim patch, https://github.com/vim/vim/commit/461a7fcfce3cd6414f990037e6468af3b5ccf119.

**Comment by jdhao** [comment]
Thanks for this info 👍
