### ISSUE TITLE
Specify non-existent buffer in nvim_buf_set_keymap

### ISSUE THREAD

**Issue by jbyuki** [neovim/neovim#13541]
- `nvim --version`:
NVIM v0.5.0-dev+939-g4f9e7a512
Build type: Release
LuaJIT 2.1.0-beta3
- Operating system/version: Win10
- Terminal name/version: nvim-qt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
As an ex-command execute:
:lua vim.api.nvim_buf_set_keymap(100, 'n', '<CR>', '', {noremap = true})
```

### Actual behaviour

Neovim closes unexpectedly.

### Expected behaviour

Display an error message that the buffer is not existent.

**Comment by vigoux** [comment]
Hi, thanks for reporting, and thanks for the easy repro steps, I am working on it atm.

**Comment by vigoux** [comment]
Could you try #13543 and see if it fixes your issue ?

It should (as I actually added a test for it), but just to be 100% sure.

**Comment by jbyuki** [comment]
Thanks for the quick fix. Compiled and it shows the error message correctly on my end. I guess the issue is fixed.
