### ISSUE TITLE
Can't install neovim. 404 error

### ISSUE THREAD

**Issue by fc1943s** [neovim/neovim#13554]
- `nvim --version`:
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Windows 10
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

![image](https://user-images.githubusercontent.com/688618/102599434-392b3000-40fc-11eb-8ef1-6620a5691ca7.png)

![image](https://user-images.githubusercontent.com/688618/102599465-4516f200-40fc-11eb-9636-4eda7769d89b.png)

https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip

![image](https://user-images.githubusercontent.com/688618/102599586-71cb0980-40fc-11eb-8e90-b007190305bf.png)

**Comment by teto** [comment]
there are no builds for now for windows. see the pinned issue and the other similar reports https://github.com/neovim/neovim/issues/13312.
