### ISSUE TITLE
Native julia support on neovim

### ISSUE THREAD

**Issue by paniash** [neovim/neovim#13556]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Artix linux
- Terminal name/version: st
- `$TERM`: st-256color

Apologies if a similar query has already been answered but will Julia support be integrated in neovim anytime soon? Not as a [plugin](https://github.com/JuliaEditorSupport/julia-vim) per se but native support (syntax highlighting, indentation, etc.).

Thanks!

**Comment by glacambre** [comment]
You should ask the julia-vim maintainers to send their plugin to vim. Once Vim's maintainer includes it in Vim, the Neovim maintainers will include it in Neovim (Neovim doesn't maintain its own runtime files, they're instead copied from Vim) :).

**Comment by paniash** [comment]
@glacambre Thanks for letting me know! I'll do that. :)
