### ISSUE TITLE
Remove/Replace ROT13 operator

### ISSUE THREAD

**Issue by Svetlitski** [neovim/neovim#13550]
Vim has a built-in operator to ROT13 transform text, via `g?`. This is useless cruft in the same vein as `:smile`, which neovim removed. As such, I propose that the ROT13 operator should be removed/replaced. It looks like I'm not the first person to think of this, as it was brought up in #6263, but unfortunately was never seen through. The obstacle there seemed to be the desire to *replace* the existing operator as opposed to removing it. If that is still desired, I propose that `g?` be reassigned to comment/uncomment the selection. Commenting/uncommenting code is a very common operation across all programming languages, and neovim already has enough information to know how to comment/uncomment different filetypes via the `commentstring`. Furthermore, there are existing high-quality, zero-dependency implementations of this functionality that could be used as a reference for neovim's implementation such as [tpope/vim-commentary](https://github.com/tpope/vim-commentary), or even co-opted into neovim directly (like the `man.vim` and `matchit` plugins have been). **If this enhancement is given the go-ahead, I'd be happy to implement it myself.**

**Comment by kutsan** [comment]
> I propose that g? be reassigned to comment/uncomment the selection.

If this ever is going to happen I suggest we should go with `gc` rather than `g?` since it's already available mapping to users and lands beautifully as a mnemonic mapping; `[g]o [c]omment`, `[g]et [c]ommented` and such.

**Comment by glacambre** [comment]
>Vim has a built-in operator to ROT13 transform text, via g?. This is useless cruft in the same vein as :smile, which neovim removed.

Not really. `:smile` was just never ported to neovim while `g?` already exists.

>As such, I propose that the ROT13 operator should be removed/replaced.

Removing something for the sake of removing it does not sound like a good idea to me. However, it does look like `g?`'s implementation is pretty complex: https://github.com/neovim/neovim/search?q=rot13 . So if it causes maintenance issues (I don't know if it does, the maintainers should probably weigh in), it would probably make sense to remove it. However, if it doesn't, it probably shouldn't be removed as its code seems to be tightly intertwined with other features and the removal risks both making porting patches from Vim harder and introducing new bugs.

>I propose that g? be reassigned to comment/uncomment the selection.

I think the discussion about adding comment/uncomment to neovim deserves its own discussion. It's a complicated matter and there are various approaches available here (regular textual changes that can fail, something more robust with tree-sitter...).

**Comment by justinmk** [comment]
# Proposal

Establish `g?` as a "web search" and/or "(local) AI search" command.
