### ISSUE TITLE
NeoVim not interpreting escape codes for terminal colors

### ISSUE THREAD

**Issue by sapi01** [neovim/neovim#13560]
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/samsapi0l/Desktop/neovim-0.4.4/build/config -I/home/samsapi0l/Desktop/neovim-0.4.4/src -I/usr/include -I/home/samsapi0l/Desktop/neovim-0.4.4/.deps/usr/include -I/home/samsapi0l/Desktop/neovim-0.4.4/build/src/nvim/auto -I/home/samsapi0l/Desktop/neovim-0.4.4/build/include
Compiled by samsapi0l@linux

Features: +acl +iconv +tui

- `vim -u DEFAULTS` (version:) 8.1.2269
- Operating system/version:
- NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
- Terminal name/version: WizTerm / wezterm 20201101-103216-403d002d
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
type, `:! ls --color=always`

### Actual behaviour
`ls --color=always` Issue screenshot: https://pasteboard.co/JFGj41A.png

I configured my `makeprg` recently to Build and run Tests inside NeoVim when I type `:make`, but `makeprg`/`:make` also NOT showing any colors. I have included the screenshot

Actual behaviour(when I type `:make`): https://pasteboard.co/JFGkmzr.png
Expected behaviour(when I type `make` from my shell, Outside NeoVim) : https://pasteboard.co/JFGkNT5.png

How can I make NeoVim interpret the color codes and show the colors in `make` (makeprg) and also for commands such as `ls --color=always` ?

**Comment by mhinz** [comment]
Unfortunately this is an old bug and nobody found the time to fix it yet: https://github.com/neovim/neovim/issues/1496
