### ISSUE TITLE
workDoneProgress blocking input

### ISSUE THREAD

**Issue by etrnal70** [neovim/neovim#13564]
- `nvim --version`: 0.5.0-dev+953-g7e4c91256
- language server name/version: rust-analyzer / 20201214
- Operating system/version: Arch Linux

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: custom_cmake: configuration checked.
  - INFO: custom_rust: configuration checked.
  - INFO: custom_docker: configuration checked.
  - INFO: custom_bash: configuration checked.
  - INFO: custom_ccls: configuration checked.
  - INFO: custom_lua: configuration checked.
  - INFO: custom_texlab: configuration checked.
  - INFO: custom_dart: configuration checked.
  - INFO: custom_tsserver: configuration checked.

</details>

<details>
<summary>lsp.log</summary>

[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:801 ]	"on_lines bufnr: 1, changedtick: 9, firstline: 17, lastline: 18, new_lastline: 18, old_byte_size: 4, old_utf32_size: 4, old_utf16_size: 4"	{ "   l" }
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 18          },          start = {            character = 0,            line = 17          }        },        rangeLength = 4,        text = "   l\n"      } },    textDocument = {      uri = "file:///home/hanifrmdhn/Project/Rust/play_ground/src/main.rs",      version = 9    }  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  id = 9,  jsonrpc = "2.0",  method = "window/workDoneProgress/create",  params = {    token = "rustAnalyzer/indexing"  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/indexing",    value = {      kind = "begin",      percentage = 0,      title = "indexing"    }  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:501 ]	"server_request"	"window/workDoneProgress/create"	{  token = "rustAnalyzer/indexing"}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:507 ]	"server_request: no handler found for"	"window/workDoneProgress/create"
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:500 ]	"server_request: callback result"	{  err = {    code = -32601,    message = "MethodNotFound",    <metatable> = {      __tostring = <function 1>    }  },  status = true}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  error = {    code = -32601,    message = "MethodNotFound",    <metatable> = {      __tostring = <function 1>    }  },  id = 9,  jsonrpc = "2.0"}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:487 ]	"notification"	"$/progress"	{  token = "rustAnalyzer/indexing",  value = {    kind = "begin",    percentage = 0,    title = "indexing"  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/indexing",    value = {      kind = "report",      message = "127/227 (play_ground)",      percentage = 55    }  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/indexing",    value = {      kind = "report",      message = "138/227 (scopeguard)",      percentage = 60    }  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/indexing",    value = {      kind = "report",      message = "226/227 (crossbeam_deque)",      percentage = 99    }  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "rustAnalyzer/indexing",    value = {      kind = "end"    }  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        message = "Syntax Error: expected SEMICOLON",        range = {          end = {            character = 4,            line = 17          },          start = {            character = 4,            line = 17          }        },        severity = 1,        source = "rust-analyzer"      } },    uri = "file:///home/hanifrmdhn/Project/Rust/play_ground/src/main.rs",    version = 9  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:487 ]	"notification"	"$/progress"	{  token = "rustAnalyzer/indexing",  value = {    kind = "report",    message = "127/227 (play_ground)",    percentage = 55  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:487 ]	"notification"	"$/progress"	{  token = "rustAnalyzer/indexing",  value = {    kind = "report",    message = "138/227 (scopeguard)",    percentage = 60  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:487 ]	"notification"	"$/progress"	{  token = "rustAnalyzer/indexing",  value = {    kind = "report",    message = "226/227 (crossbeam_deque)",    percentage = 99  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:487 ]	"notification"	"$/progress"	{  token = "rustAnalyzer/indexing",  value = {    kind = "end"  }}
[ DEBUG ] 2020-12-20T09:20:46+0700 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:487 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = { {      message = "Syntax Error: expected SEMICOLON",      range = {        end = {          character = 4,          line = 17        },        start = {          character = 4,          line = 17        }      },      severity = 1,      source = "rust-analyzer"    } },  uri = "file:///home/hanifrmdhn/Project/Rust/play_ground/src/main.rs",  version = 9}

</details>

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
Open rust project file
Wait for initial indexing process
Start typing
```

### Actual behaviour
Rust-analyzer did indexing each user input. Input are blocked until indexing completed. 

### Expected behaviour
Indexing shouldn't block input.

**Comment by mjlbach** [comment]
I'm not able to reproduce this on a fairly large rust project rocket](https://github.com/SergioBenitez/Rocket). `nvim -u NORC` won't load any initialization files, so that's not enough information to reproduce your issue.  Can you try with [this](https://github.com/mjlbach/nvim-lspconfig/blob/issue_template_improvements/test/minimal_init.lua) minimal init.lua (add rust-analyzer and nvim -u /path/to/minimal_init.lua) on rocket, with the latest rust-analyzer, neovim-nightly, and nvim-lspconfig and see if you can reproduce? 

```

**Comment by etrnal70** [comment]
After seeing some commit regarding workDoneProgress in core and lspconfig, i've tried it again yesterday but isn't sure whether its fixed or not. I'll try it again today

**Comment by etrnal70** [comment]
Tried it on my dual core laptop, seems its fixed ! I think this can be closed 😃
