### ISSUE TITLE
Packadd loads start packages (twice)

### ISSUE THREAD

**Issue by weilbith** [neovim/neovim#13568]
- `nvim --version`: `NVIM v0.5.0-dev+953-g7e4c91256`
- Operating system/version: `5.9.4-arch1-1`
- Terminal name/version: `zsh 5.8 (x86_64-pc-linux-gnu)`
- `$TERM`:  `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

The file tree of the example setup looks like the following:

```
├── pack
│  └── foo
│     ├── start
│     │  └── bar
│     │     └── plugin
│     │        └── start.vim
│     └── opt
│        └── bar
│           └── plugin
│              └── opt.vim
└── plugin
   └── load_opt.vim
```

The files content are the following:

`pack/foo/start/bar/plugin/start.vim`:
```vim
echom "load foo/start/bar"
```

`pack/foo/opt/bar/plugin/opt.vim`:
```vim
echom "load foo/opt/bar"
```

`plugin/load_opt.vim`:
```vim
packadd bar
```

Running now `nvim` now results into the following message output:

```
load foo/start/bar
load foo/opt/bar
load foo/start/bar
```

According to the documentation of the `packadd` command, this should only load the optional plugin.  Only if the loading of the start packages was skipped, the command also searches for `pack/*/start/{name}`.

### Actual behaviour

Packadd loads start package (twice).

### Expected behaviour

Packadd loads optional package only (or at least not the start package twice.

**Comment by bfredl** [comment]
this is weird. I get exactly the opposite issue under certain conditions ( `start/` packages are NOT loaded post-startup, which I suspected from the conditions in the code)

**Comment by bfredl** [comment]
though it actually makes kinda sense, this check is definitely not the correct one:

https://github.com/neovim/neovim/blob/abcbc5a9f346f98591f27eb73bc1c63787779368/src/nvim/runtime.c#L515

It always needs to check whether this **particular** package was loaded yet, not whether some completely arbitrary time during startup when `did_source_packages` is set has passed yet or not.

**Comment by weilbith** [comment]
@bfredl just to make sure I got that right: this really is an issue and the expected behavior is not load start packages again. Right?

**Comment by bfredl** [comment]
@weilbith who knows what intended behavior for packages are? The docs bram wrote is self-contradictory. the expected behaviour for me is the one that minimizes the number of people that needs to @ me at gitter (as a lazy proxy of "useful behavior for most people")

**Comment by weilbith** [comment]
> *:pa* *:packadd* *E919*
> :pa[ckadd][!] {name}
> Search for an optional plugin directory in 'packpath' 			and source any plugin files found. The directory must 			match: 				pack/*/opt/{name} 			The directory is added to 'runtimepath' if it wasn't 			there yet. 			If the directory pack/*/opt/{name}/after exists it is 			added at the end of 'runtimepath'. 			If loading packages from "pack/*/start" was skipped, 			then this directory is searched first: 				pack/*/start/{name} 

How is this contradictory? I mean this question serious. For me this is a pretty explicit description. Isn't it?

Sorry to annoy you with that. Unhappily you were the only one answering.

**Comment by weilbith** [comment]
I tried it another time now and it seems like it somehow got resolved. 🤷🏾 
Therefore I'll close the issue.
