### ISSUE TITLE
Set `filetype=systemd` for Systemd unit files opened with `systemctl edit`

### ISSUE THREAD

**Issue by Atralb** [neovim/neovim#13574]
Currently, if you open a sytemd unit file with `systemctl edit <service>` or `systemctl edit --full <service>`, neovim doesn't recognize the file as a "systemd" file.

I believe it is about the "hash"  appended to the filename when using this `edit` subcommand. For instance:

```
/etc/systemd/system/smartd.service

Becomes

/etc/systemd/system/.#smartd.servicee76b33b699e76c29
```

I believe this would not be very difficult to catch and `set ft=systemd` directly, but I may be wrong.

Anyway, it would be great if this was managed. I'll let you deem if this seems manageable.

Thanks for your work.

**Comment by jdhao** [comment]
This can be trivially achieved by using the [`ftdetect`](https://neovim.io/doc/user/filetype.html#ftdetect) feature.

**Comment by Atralb** [comment]
@jdhao How is this relevant in any way ? Detecting all filetypes based on extension is trivial. Does that mean none shouldn't be configured by default ? As we can cleaarly see, the consensus disagrees.

Making this a default behavior seems perfectly reasonable, unless you can provide mature argumentation instead of haughty dismissal...

**Comment by jdhao** [comment]
@Atralb I am not saying that this should not be done. Now that you agree it is trival to implement and you need it, why do not you create a pull request and contribute your code?

Also for this kind of runtime thing, nvim often merge from upstrem patch. So if you want to contribute, you may contribute to vim repository directly.

**Comment by Atralb** [comment]
@jdhao Well making a single file with a one-liner in my config and making code to implement this equivalent feature in the actual program is not the same thing. And you know it...

I would gladly have provided my time and effort if I had the necessary skills for a PR about this.

**Comment by chrisbra** [comment]
@Atralb isn't that already done:

https://github.com/neovim/neovim/blob/7b65a9135e04aade4dd66b5f9dc33c74e5ac962a/runtime/filetype.vim#L1683

It seems, this should take care of your use case already.

**Comment by Atralb** [comment]
@chrisbra Well you are totally right. I didn't know we could see a plain `filetype.vim` config file on our system.

However, it weirdly doesn't work when running as root (and through `sudo`).

I.e.:

- `EDITOR=nvim systemctl --user edit smartd` sets the filetype.
- `sudo EDITOR=nvim systemctl edit smartd` DOES NOT sets the filetype.

**Comment by chrisbra** [comment]
I don't know. perhaps the root user uses a different nvim installation (from the distribution?) which does not include this part in the filetype.vim runtime file? Check with `:scriptnames` what files have been read, check also `:verbose set ft?` to see where the filetype is set.

**Comment by windwp** [comment]
```
sudo  EDITOR='nvim --cmd "set\filetype=systemd" ' systemctl edit --full ufw
```
how about this?
