### ISSUE TITLE
No nvim-win64.zip for nightly build

### ISSUE THREAD

**Issue by n2cholas** [neovim/neovim#13583]
On the https://github.com/neovim/neovim/releases/tag/nightly page there should be a nvim-win64.zip file (https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip), but it does not exist. Would it be possible to provide one? Thanks.

**Comment by erw7** [comment]
Before creating an issue, please search for similar ones. The same question has been asked many times, but it is being addressed. Please see pinned issue #13312.

**Comment by n2cholas** [comment]
Sorry about that, thanks for the link.
