### ISSUE TITLE
[Suggestion] ideas for keybinding suggestions/examples in lsp-config

### ISSUE THREAD

**Issue by pretentious7** [neovim/neovim#13600]
`help lsp-config` doesn't have any example keybindings aside from the init.vim example, that I can find, I think it would be useful to have somewhere.

A module with an on_attach function for lsps with stuff like this would be cool, but I don't know where it would go, or atleast a sort of canonical example somewhere in the docs? Might be in nvim's lsp docs, in which case I missed it, sorry, but having the pcalls is really useful because it allows graceful fallback in case a server doesn't implement something.

```lua
if pcall(vim.lsp.buf.hover) then
	vim.fn.nvim_set_keymap("n","K","<cmd>lua vim.lsp.buf.hover()<CR>",
		{noremap = true, silent = true})
else end
```

**Comment by glacambre** [comment]
There are a few keybinding examples in `:h lsp-config` on master so let's close this :)
