### ISSUE TITLE
Recommended method for testing plugins?

### ISSUE THREAD

**Issue by zmitchell** [neovim/neovim#13601]
I'm beginning work on my first plugin and I'm wondering how exactly you're supposed to test plugins.

You can design the plugin in such a way that the core functionality can be invoked from tests, but I don't know how you take that a step further and verify that the desired output appears on screen. Basically what I'm wondering is how you would test a plugin in CI.

Is there a standard way of doing this?

Edit: I should add that I'm writing the plugin in Lua.

**Comment by dm1try** [comment]
you know, it's wrong place for such questions. use community sources(ex, [gitter](https://gitter.im/neovim/neovim)), pls.

>  step further and verify that the desired output appears on screen
> how you would test a plugin in CI

those are different things. take a look at https://github.com/dm1try/git_fastfix/blob/master/spec/git_fastfix_spec.lua#L101-L114 and https://github.com/dm1try/golden_size/blob/master/.github/workflows/main.yml#L22-L25. maybe this will help but it's not some kind of official or recommended way.

**Comment by zmitchell** [comment]
My mistake, I'll ask elsewhere.
