### ISSUE TITLE
'%' charactor lost when concating lines

### ISSUE THREAD

**Issue by aj3423** [neovim/neovim#13613]
- `nvim --version`: v0.5.0-519-g74fed7d50
- `vim -u DEFAULTS` (version: ) behaves differently? Same problem
- Operating system/version: Kali Linux 2020.4 , all packages up-to-date
- Terminal name/version: xfce4-terminal 0.8.9.2 (Xfce 4.14)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Type two lines, both line contain charactor '%', the second line must begin with '%', like:
```
%11
%22
```
2. Visual-Line select them: `ggVG`
3. Concat: `J` or `gJ`

### Actual behaviour
 `%11 22` for `J`  and  `%1122` for `gJ`.  Both missing charactor '%'.
### Expected behaviour
`%11 %22` and `%11%22`

**Comment by jamessan** [comment]
This is what the 'j' setting in `'formatoptions'` does.  Either remove that setting from `'formatoptions'` or change `'comments'` to not regard `%` as a comment.
