### ISSUE TITLE
[LSP] - Manage `workspace/configuration` in neovim instead of nvim-lspconfg

### ISSUE THREAD

**Issue by ckipp01** [neovim/neovim#13615]
I've noticed that currently the entire way to use settings to pass to a server is managed inside of `neovim/nvim-lspconfig` instead of just doing it inside of neovim. For example, in nvim-lspconfig it allows for settings to be set for your server, and then a `workspace/didChangeConfiguration` is sent as part of the `on_init` handler. You can see this happening here:

https://github.com/neovim/nvim-lspconfig/blob/4f431b992482d9edbe4ccf65170e6304503614a9/lua/lspconfig/configs.lua#L147-L160

Related to this, the `workspace/configuration` handler is also fully handled in nvim-lspconfig:

https://github.com/neovim/nvim-lspconfig/blob/4f431b992482d9edbe4ccf65170e6304503614a9/lua/lspconfig/configs.lua#L67-L86

While the settings are server specific, I think the mechanism to handle the `workspace/didChangeConfiguration` and `workspace/configuration` belong in neovim itself, not in nvim-lspconfig, since this is just part of the spec. Currently there are no way to set settings or manage them in the core lsp implementation.

**Comment by teto** [comment]
Seems sensible. Patch welcome

**Comment by pwntester** [comment]
No description provided.

**Comment by mfussenegger** [comment]
This was done:

https://github.com/neovim/neovim/pull/18847
https://github.com/neovim/neovim/pull/19548
https://github.com/neovim/neovim/pull/13649

**Comment by justinmk** [comment]
Anything we can remove from nvim-lspconfig (or do we have a tracking issue there)?

**Comment by clason** [comment]
I don't think there's anything left, really, after `vim.lsp.start`?
