### ISSUE TITLE
Problem with Bengali language writing in neovim

### ISSUE THREAD

**Issue by Sahil-pixel** [neovim/neovim#13623]
- `nvim --version  neovim-qt (0.2.8)

`:
- `vim -u DEFAULTS 8.0` (version: ) behaves differently?
- Operating system/version:kubuntu 18.04
- Terminal name/version:bash
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
![image](https://user-images.githubusercontent.com/57060638/103231651-4ea32400-495e-11eb-9760-0538627258c5.png)

### Expected behaviour
# I have written a line in Bengali language but output is different as shown in image 
# line below i have written in neo vim-qt
আমি ভাল ছেলে। জীবন সুন্দর

**Comment by glacambre** [comment]
Neovim-qt rendering issues should probably be reported in [Neovim-Qt's issue tracker](https://github.com/equalsraf/neovim-qt/issues) instead of here :).
