### ISSUE TITLE
:bdelete when there is a floating window results in "E444: Cannot close last window"

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#13628]
- `nvim --version`: NVIM v0.5.0-dev+967-g7afd4526f
- `vim -u DEFAULTS` (version: ) behaves differently? Yes (when using Vim's popup windows instead of Neovim's floating windows)
- Operating system/version: Ubuntu 20.04.1
- Terminal name/version: Konsole 19.12.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```vim
nvim -u NORC

" Start editing first file
:e file1

" Start editing second file
:e file2

" Open a floating window
:let config = {'relative': 'editor', 'focusable': v:false, 'width': 1, 'height': 1, 'row': 3, 'col': 3}
:call nvim_open_win(0, v:false, config)

" Delete the current buffer (file2)
:bdelete
```

### Actual behaviour

An error message (with duplicate lines, as shown):

```
E444: Cannot close last window
E444: Cannot close last window
Press ENTER or type command to continue
```

Followed by a change of buffer to `file1`, with `file2` still on the buffer list.

![E444](https://user-images.githubusercontent.com/541289/103248526-f0177f00-4938-11eb-9888-3f556ebe1b9f.png)

### Expected behaviour

No error message, and a change of buffer to `file1` with `file2` removed from the buffer list.

### Additional Information

This is based on https://github.com/dstein64/nvim-scrollview/issues/10, reported by @YodaEmbedding.

This seems related to Issue #11440, but results in a different error message (`E444` versus `E5601`), and occurs when there is a single tab.

**Comment by kyoh86** [comment]
This still happens.
Is there any chance of a fix?

**Comment by dstein64** [comment]
@kyoh86, there are two open PRs for Issue #11440 (PR #14387 and PR #11938). I wonder if one of those PRs also addresses this issue, given that this issue seems related to Issue #11440. I haven't tested to find out.

**Comment by kaldown** [comment]
`NVIM v0.5.0-dev+1233-g82ac44d01` still persists

**Comment by rodhash** [comment]
Having same error on **NVIM v0.6.0**

**Comment by zeertzjq** [comment]
#17360 doesn't fix this.

**Comment by lewis6991** [comment]
I realised that too. Will look into this.

**Comment by sileht** [comment]
I have NVIM v0.6.1 and the issue looks still there.

> To work around this error I silenced the error messages with `:sil! bd` so things are back to "normal" .. Just wanted to give my two cents here.

I use almost the same workaround: `cnoremap bd silent! bd`

**Comment by joshbode** [comment]
> I have NVIM v0.6.1 and the issue looks still there.

I'm on the nightly and the issue is still there.

My workaround is similar, which is to use these abbreviations:
```
cnoreabbrev bd silent! bd
cnoreabbrev bw silent! bw
```
