### ISSUE TITLE
Will neovim support vim9 script (VimL 5, VimScript 5, scriptversion 5)?

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#13625]
Not sure what the actual term is, but I've seen it referenced as vim9 script, viml 5, and vimscript 5. There doesn't seem to be an official name for it, and Bram calls it Vim script (or Vim script 9) with a space. The docs will call it `scriptversion 5`. So who knows what the language is called.

Anywho, just curious: will vim9 script be merged/integrated into neovim? Or maybe a better question is, will neovim be compatible with vim9 (and to what extent)?

I would LOVE to use the new ECMAScript-inspired [`import`](https://github.com/Bakudankun/qline.vim/blob/901ee14d4c3b03f2835d04e62e5a9cbc7f8dd755/import/qline.vim#L3) / [`export`](https://github.com/Bakudankun/qline.vim/blob/901ee14d4c3b03f2835d04e62e5a9cbc7f8dd755/import/qline.vim#L168) syntax for my vimrc/init.vim code organization. And the new static [type](https://github.com/Bakudankun/qline.vim/blob/901ee14d4c3b03f2835d04e62e5a9cbc7f8dd755/import/qline.vim#L8) [syntax](https://github.com/Bakudankun/qline.vim/blob/901ee14d4c3b03f2835d04e62e5a9cbc7f8dd755/import/qline.vim#L23)!

So nice! Can't wait to see the intellisense!

**Comment by teto** [comment]
vimscript9 is a moving target. Our focus is more on improving the lua interface (that in terms of performance is better than vim9,can be interfaced with funnel/typed lua etc). Maybe in the future when vimscript9 is mature enough we can transpile it to lua, or if someone steps up. Nothing in short term though so I'll close.

**Comment by jvoisin** [comment]
vimscript9 is now stable: https://groups.google.com/g/vim_announce/c/2XYAoPL2sqg

**Comment by clason** [comment]
Still no plans for supporting it; improving Lua scripting seems to be a better use of the team's time.

**Comment by Milldrew** [comment]
Vim script is like bash script. It is so easy and convenient and just by virtue of using vim you are learning and using vim script without knowing it. It makes more sense just to make vim and vim script better. And In this way vim 9 is better than neovim for many vim users.

**Comment by Milldrew** [comment]
Learning vim script makes you better at editing in vim also, lua api is far removed from actual vim keystrokes etc
