### ISSUE TITLE
BufRead autocommands not running

### ISSUE THREAD

**Issue by Svetlitski** [neovim/neovim#13620]
BufRead autocommands are not being run. Vim 8.2 works as expected.

- `nvim --version`:
 ```
NVIM v0.5.0-dev+a58c550
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201227-3289-9mymck/build/config -I/tmp/neovim-20201227-3289-9mymck/src -I/usr/local/include -I/tmp/neovim-20201227-3289-9mymck/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201227-3289-9mymck/build/src/nvim/auto -I/tmp/neovim-20201227-3289-9mymck/build/include
Compiled by kevin@My-MacBook-Pro.attlocal.net

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-a58c550/share/nvim"

Run :checkhealth for more info
 ```
- `vim -u DEFAULTS` (version: 8.2) behaves differently?:  **Yes** (well, with same `minimal_example.vim` below in place of DEFAULTS)
- Operating system/version: macOS Mojave 10.14.6 (18G7016)
- Terminal name/version: iTerm2 Build 3.4.3
- `$TERM`: xterm-256color

### Steps to reproduce

1. Create a file called `minimal_example.vim` with the following contents:
```
autocmd BufRead * :echom 'Hello world'
```

2. Create a example file to read by running `touch example.txt`

3. Open this file using `nvim -u minimal_example.vim example.txt`

4. Now type `:messages<Enter>`

### Actual behavior
There are no messages

### Expected behavior
Messages lists `Hello world`

**Comment by jdhao** [comment]
Try `BufEnter`, it works. It is not clear why `BufRead` won't work, though.

**Comment by chrisbra** [comment]
try removing the `F` from shortmess.

**Comment by Svetlitski** [comment]
@chrisbra That fixes it. Apologies for not RTFM close enough.

**Comment by justinmk** [comment]
Related:

- https://github.com/vim/vim/issues/4379
- https://github.com/neovim/neovim/issues/12041
- https://github.com/neovim/neovim/issues/8675
