### ISSUE TITLE
Recent commit adding support for 0-width signs breaks ALE plugin

### ISSUE THREAD

**Issue by Svetlitski** [neovim/neovim#13635]
- `nvim --version`:
```
NVIM v0.5.0-dev+c762f5220
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201229-4514-1xu1m98/build/config -I/tmp/neovim-20201229-4514-1xu1m98/src -I/usr/local/include -I/tmp/neovim-20201229-4514-1xu1m98/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201229-4514-1xu1m98/build/src/nvim/auto -I/tmp/neovim-20201229-4514-1xu1m98/build/include
Compiled by kevin@My-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-c762f52/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: 8.2) behaves differently? Yes
- Operating system/version: macOS Mojave 10.14.6 (18G7016)
- Terminal name/version: iTerm2 Build 3.4.3
- `$TERM`: xterm-256color

### Steps to reproduce
The popular [ALE Plugin](https://github.com/dense-analysis/ale) can show error-signs in the left-hand column of the screen on lines which have linting errors. ALE has a helpful setting `g:ale_sign_column_always` which, when enabled, keeps the column where these error signs appear open regardless of whether or not there are currently any errors (as opposed to the default of expanding/collapsing this column depending on whether or not there are errors). This setting has always worked well in Neovim, but has recently stopped working. I've determined via `git bisect` that the problematic commit is [88ae03bcdb8992fd91a3efdb61dbd7e2aa395eff](https://github.com/neovim/neovim/commit/88ae03bcdb8992fd91a3efdb61dbd7e2aa395eff), which allowed signs to be zero-width. Given the extreme popularity of the ALE plugin, it would be nice if this change could be taken to be a regression on Neovim's part.

A minimal vimrc for reproducing this issue is given below (assuming [vim-plug](https://github.com/junegunn/vim-plug) is installed):
```
call plug#begin()
        Plug 'w0rp/ale'
        let g:ale_sign_column_always = 1
call plug#end()
```

### Actual behavior

![neovim_actual](https://user-images.githubusercontent.com/35482043/103327399-00535b00-4a1a-11eb-8766-627239899d70.gif)

### Expected behavior

![neovim_expected](https://user-images.githubusercontent.com/35482043/103327406-047f7880-4a1a-11eb-9c67-c2f6908e83ed.gif)

**Comment by Svetlitski** [comment]
@lukas-reineke

**Comment by Svetlitski** [comment]
I can confirm after further investigation that a simple `git revert 88ae03bcdb8992fd91a3efdb61dbd7e2aa395eff` does indeed resolve the issue without conflicts (although this is a very heavy-handed approach to solving the issue).

**Comment by lukas-reineke** [comment]
ALE uses a 0 width dummy sign to keep the sign column open. It is expected behavior now that this will not render the sign column anymore.
Should be a super easy fix on ALEs side, just give that sign a space character as text.

https://github.com/dense-analysis/ale/blob/master/autoload/ale/sign.vim#L87

change that line to

```vim
sign define ALEDummySign text=\ " traling space is important
```

Or you can also set `signcolumn` to something other than `auto` to always set a fixed width.

**Comment by teto** [comment]
Is that answer satisfactory @Svetlitski ?

**Comment by Svetlitski** [comment]
Sorry for the very late reply, yes this is fine. The tweak reccomended by @lukas-reineke unforunately doesn't fix the issue, but I've come up with something else that does (see [my PR to ALE](https://github.com/dense-analysis/ale/pull/3672) if you're curious).
