### ISSUE TITLE
Is there any way to auto save buffers asynchronously in Insert mode , as file changes ......??

### ISSUE THREAD

**Issue by MrAdityaAlok** [neovim/neovim#13639]
- `nvim --version`: v0.4.4
- Operating system/version: Android 9
- Terminal name/version: Termux
- `$TERM`: xterm-256color

# Problem
- I couldn't find a way to auto save buffers asynchronously in Insert mode , as file changes .....
- It is needed for BrowserSync to load automaticaly

**Comment by teto** [comment]
many plugins out there doing that, you can use timers, checkout autocommands etc. This is not a neovim issue, please use another usage forum like reddit or stackoverflow .

**Comment by MrAdityaAlok** [comment]
Okay, thanks
