### ISSUE TITLE
Is semantic highlighting a feature on Neovim?

### ISSUE THREAD

**Issue by HTG-YT** [neovim/neovim#13637]
I pretty like semantic highlighting on my editor. I want to ask, does Neovim equip semantic highlighting?

**Comment by glacambre** [comment]
Semantic highlighting is available through plugins (e.g. https://github.com/numirias/semshi ) but not by default.

**Comment by HTG-YT** [comment]
I'm looking for semantic highlighting for Rust (with rust-analyzer https://github.com/rust-analyzer/rust-analyzer). Are there any plugins for that?

**Comment by glacambre** [comment]
There could be, although I don't know of any. You should survey the various LSP plugins available for Neovim and see if they provide semantic highlighting.

**Comment by HTG-YT** [comment]
Thanks
