### ISSUE TITLE
TOML files don't have syntax highlighting

### ISSUE THREAD

**Issue by jxs** [neovim/neovim#13632]
- `nvim --version`: NVIM v0.5.0-dev+980-g28a0f6b17
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: Linux x395 5.9.14-arch1-1
- Terminal name/version: zsh 5.8 (x86_64-pc-linux-gnu)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```
open any `.toml` file

### Actual behaviour
File is opened without syntax highlighting, 
### Expected behaviour
proper syntax highlighting for TOML files

thanks!

**Comment by chrisbra** [comment]
There is discussion about including [vim-toml](https://github.com/cespare/vim-toml/issues/36) in the vim runtime files, which would later then be merged by neovim. But there is nothing ready yet, except for manually installing the mentioned plugin.

Note, the `toml` filetype has just recently been include in the runtime files.

**Comment by jxs** [comment]
Hi, and thanks. 
Ah! I used to have nvim syntax highlight TOML files though, that's why I opened the issue as a bug

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/commit/8329f624de048c0cedaf0e8c1fc43b253e49c48c#diff-c07c0771a9f5af08e375703487a8fe7bbddd71f98a7bbe06acd78365525a243e was added in nighlty. neovim does not have a toml syntax file in https://github.com/neovim/neovim/tree/a4c41ba931a4a472fb06da2cfee1dbe298564877/runtime/syntax.

**Comment by mhinz** [comment]
As said above, Nvim never provided TOML highlighting by default. When Vim decides to add it, we'll eventually do as well (by merging their runtime patches).

**Comment by Thesola10** [comment]
I think this issue should be reopened as TOML has been merged into Vim: vim/vim@28b6a3b

**Comment by clason** [comment]
And that patch has already been ported to Neovim: https://github.com/neovim/neovim/commit/f19dc0608161622f7786eb3cddee27d086cc3ea3

So nothing remains to be done.
