### ISSUE TITLE
LSP: Implement dynamicRegistration 

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#13634]
While the language server protocol spec should allow for graceful fallback when a server doesn't broadcast certain capabilities, in reality this is not the case. Many language servers implicitly assume vscode's capabilities, especially those built using [vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node). This was first noted with pyright and jdtls which ignore dynamicRegistration settings and try to invoke the client/registerCapability handler. More recently, I discovered that vscode-json-languageserver will refuse to initialize the formatter unless dynamicRegistration is supported clientside. We could/should try to upstream issues (I filed the former issue already here https://github.com/microsoft/vscode-languageserver-node/issues/713), I'm not sure the latter can really be called a bug and the issue tracker isn't open. I think it's a losing battle to try to upstream workarounds, and would be better to implement dynamicRegistration in core. I'm currently working on a PR, but wanted to open the issue to point those posting in nvim-lspconfig to something to watch.

**Comment by kabouzeid** [comment]
For reference, adding vetur to the list of servers that refuse formatting without dynamic registration (https://github.com/vuejs/vetur/blob/da59c05009f73939c3401d3b61440d36c28237f3/server/src/services/vls.ts#L444).

**Comment by sassanh** [comment]
@mjlbach Do you have an answer for this question asked here?
https://github.com/microsoft/vscode-eslint/pull/1307#issuecomment-894438921

> Does NeoVim not support dynamic registration?

From your comment:
> I'm closing this as it's not really a thing we can do globally

I'm not sure if "it" refers to dynamic registration.

**Comment by mjlbach** [comment]
I responded, I don't actually know how to implement dynamic registration, and it's not of use to me, so I'm unlikely to research/drive this forward.

**Comment by justinmk** [comment]
dynamic registration was implemented in https://github.com/neovim/neovim/pull/23681 , though it needs to be enabled specifically for each capability ([example](https://github.com/neovim/neovim/pull/24102)): https://github.com/neovim/neovim/blob/77e3efecee4e9948044ec02caeaf6fec496c6c02/runtime/lua/vim/lsp/protocol.lua#L343
