### ISSUE TITLE
How can I change cursor style size?

### ISSUE THREAD

**Issue by fcying** [neovim/neovim#13631]
- `nvim --version`: NVIM v0.4.4
- Operating system/version: debian-wsl2
- Terminal name/version: windows terminal
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`
```
$nvim -u NORC
:set guicursor=n:ver10
:set guicursor=n:ver90
```

### Actual behaviour
cursor size not change. 

### Expected behaviour
cursor size change.

**Comment by teto** [comment]
this is a setting for GUIs, it doesn't work in terminals.
