### ISSUE TITLE
nvim_win_is_valid(nil) not throwing error

### ISSUE THREAD

**Issue by jbyuki** [neovim/neovim#13651]
- `nvim --version`: NVIM v0.5.0-dev+939-g4f9e7a512
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: win10
- Terminal name/version: nvim-qt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
# in ex-command
lua print(vim.api.nvim_win_is_valid(nil))
```

### Actual behaviour

Return `true`.

### Expected behaviour

Display that it expects a window handle.

**Comment by glacambre** [comment]
`nvim_win_is_valid` expects a window number as argument. Nil isn't a valid window number. Use `lua print(vim.api.nvim_win_is_valid(0))` to print whether the current window is valid.

**Comment by bfredl** [comment]
@glacambre well that is what OP expects. The problem here is that `print(a.win_is_valid(nil))` is ok while `a.win_is_valid()` is not, which is at least a weird discrepancy (if not a major hurdle for practical use).

**Comment by LrobieProject** [comment]
It seems this bug occurs for any string input, not just `nil`. Ex. `vim.api.nvim_win_is_valid(esnathunstaoehu))` also returns true.

**Comment by LrobieProject** [comment]
From looking at it a little bit, 0 and string inputs are treated the same by `find_window_by_handle`, which causes `nvim_win_is_valid(saontuheosanthu)` to check if the current window is valid. This returns that the current window is valid.

**Comment by matu3ba** [comment]
@jbyuki Is the issue fixed? For some reason github did not automatically close this issue, even though the PR has landed.

**Comment by clason** [comment]
Because it used "solves" instead of "fixes". Still, confirmation would be good before closing.

**Comment by gpanders** [comment]
It is indeed fixed.
