### ISSUE TITLE
Stay on the first non-blank character (^) when changing lines

### ISSUE THREAD

**Issue by albinahlback** [neovim/neovim#13662]
_In `nvim` version 0.4.3_.
### Describe the feature
When clicking `^` (caret) and directly changing lines, I would like the line-change to place me onto to the first non-blank character of the new line. (Analogous to what `$` does.) 

### To reproduce
Type
```
nvim -u NORC
```
and insert
```
asdf
  asdf
    asdf
```
(tabs or spaces don't matter in my version). In normal type
```
:3
^
kk
```
and note how the cursor does not stay on the first non-blank character of the line.

However, if we type
```
:1
$
jj
```
then we do stay on the last character on the line.

**Comment by jamessan** [comment]
> I would like the line-change to place me onto to the first non-blank character of the new line. (Analogous to what `$` does.)

That's not what `$` does.  `$` makes Vim keep the cursor on the last character of the line, regardless of what character is in the column.

For all other intra-line motion, the only thing preserved for subsequent vertical movement is the column.  It has nothing to do with the motion you use to get to that column.

What you're asking for can be accomplished in a plugin.  I don't think it's something we need to implement in core nvim.
