### ISSUE TITLE
Port vim's text props to neovim

### ISSUE THREAD

**Issue by prabirshrestha** [neovim/neovim#13661]
While re-implementing diagnostics highlights in [vim-lsp](https://github.com/prabirshrestha/vim-lsp) I noticed that the neovim's usage of `nvim_buf_add_highlight` is more complex than vim's text props. https://github.com/prabirshrestha/vim-lsp/blob/2eb8d16413b2da25d1e10cf5c57b183d6394c134/autoload/lsp/internal/diagnostics/highlights.vim#L130-L180

Would it be possible to port vim's `textprops` to neovim.

Here are also other use cases that could be helpful in the future.
1. Add support for user_data in prop_add - https://github.com/vim/vim/issues/7597
2. add support for virtual text or padding in textprop - https://github.com/vim/vim/issues/7553

**Comment by bfredl** [comment]
we have `nvim_buf_set_extmark` which nominally supports multi-line highlights though #13243 will be needed to make it reliable for nested regions and some other bug fixes (I plan to get it done of 0.5 release :)

**Comment by prabirshrestha** [comment]
That is great.

Any reason why not using the same `textprop` api? Would be good if the PR had a bit of comments that would most likely clarify.

**Comment by bfredl** [comment]
Well there are some differences in design:
- extmarks are always namespaced. namespaces can be batch updated in a line region
- extmark id:s are always unique within the namespace (and neovim generates the unique id for you).
- property sets are not predefined but set directly on the mark. in particular: highlight groups can be used directly without translate to property type name.

A limitation though is that extmarks do not have named types. We probably want this for inter-plugin communication, at least a few standard ones like "error", "warning" etc for diagnostics.

**Comment by VVKot** [comment]
@bfredl so what you're saying here is that Neovim has extmarks, hence all patches for Vim's `textprops` should be N/A? E.g. https://github.com/vim/vim/commit/98aefe7c3250bb5d4153b994f878594d1745424e

**Comment by bfredl** [comment]
Yes.

**Comment by mhinz** [comment]
Thanks, but we'll concentrate on extmarks only.
