### ISSUE TITLE
The serverlist documentation is ambiguous and unclear

### ISSUE THREAD

**Issue by jarkk0sakkinen** [neovim/neovim#13668]
I wanted to know the ordering of the server list, so I first looked up his page: https://neovim.io/doc/user/remote.html. _SERVER NAME_ section states that:

> The --serverlist argument will cause Vim to print a list of registered command servers on the standard output (stdout) and exit.

Order is neither defined in the serverlist definition: (https://neovim.io/doc/user/eval.html#serverlist().)

> Returns a list of server addresses, or empty if all servers were stopped. 

That led me to my final destination, i.e. to the definition of the list type: (https://neovim.io/doc/user/eval.html#list)

> A List is an ordered sequence of items.  An item can be of any type.  Items can be accessed by their index number.  Items can be added and removed at any position in the sequence.

Based on the experienced behaviour with a launch script that I wrote for myself, the order is ascending:

```
$ cat ~/bin/v
#!/bin/sh

SERVERNAME=`nvr --serverlist | head -1`

if test -z $SERVERNAME; then
  exec nvim "$*"
else
  exec nvr --servername $SERVERNAME "$*"
fi
```

I think that ascending order wording should be used all of the documents that I mentioned, even though the fix for the list definition is the only actual documentation bug. Sometimes redundancy is worth it because in the correct places it can improve a lot. Usually open coded terminology for orderings, strict or partial, is better just say out loud in as many places as possible. Otherwise, it's too easy to mess up your head.

**Comment by teto** [comment]
maybe the absence of specification just means "dont rely on the order as it may change in the future".  Once you document it you have to sitck to it. how is that behavior relevant for your usecase ?

**Comment by jamessan** [comment]
> A List is an ordered sequence of items

I think you're reading too much into what "ordered" means here. It's not "items are ordered among themselves", but "items, once inserted, maintain their order". It's meant to draw a distinction between a dict, whose values have a deterministic but unspecified order, and lists.

**Comment by jarkk0sakkinen** [comment]
@teto, It's relevant in a way that my script relies that it takes the oldest instance of NeoVIM, when using nvr.

**Comment by jarkk0sakkinen** [comment]
@jamessan, I'm not sure what type of definition of "order" we are speaking about there. Using "ordered" to speak about "unspecified order" would be somewhat misleading, I think.

**Comment by jarkk0sakkinen** [comment]
Empiric tests show that the order is ascending starting from the oldest instance of VIM, so why not just say it?

**Comment by jamessan** [comment]
> Empiric tests show that the order is ascending starting from the oldest instance of VIM, so why not just say it?

Because documenting it means we expect that functionality and need to avoid breaking it, as @teto already stated before.

I don't know that what you describe holds true in all cases.  Maybe that's just specific to the way the servers are discovered on your system.

It's worth noting that `nvr --serverlist` has *nothing* to do with nvim's own `serverlist()`.  Nvr does its own detection of what servers are running.

I also see no benefit in enforcing any order for `serverlist()` in the code or documentation, because that implies there's some meaning to it.  There isn't.
