### ISSUE TITLE
vim.api.nvim_set_option does not apply when directly opening files

### ISSUE THREAD

**Issue by pohzipohzi** [neovim/neovim#13666]
I am trying to migrate my `init.vim` to `init.lua`, and am running into some differences when setting options. Particularly, global options do not seem to apply "immediately" when opening files directly, as detailed below

---

- `nvim --version`: NVIM v0.5.0-dev+995-g7718826ed
- Operating system/version: Arch Linux x86_64 / 5.9.14-arch1-1
- Terminal name/version: alacritty 0.6.0-dev (1bf40a8c)
- `$TERM`: screen-256color

### Steps to reproduce

Open a file with the following minimal .vim config (`nvim -u test.vim filewithlines`):

```
set nu
```

Open a file with the following minimal .lua config (`nvim -u test.lua filewithlines`):

```
vim.api.nvim_set_option('nu', true)
```

### Actual behaviour

Lines are not displayed using the lua config. However the lines show up upon editing another file (ie `:tabe anotherfilewithlines`)

### Expected behaviour

vim and lua configs should behave the same

**Comment by mjlbach** [comment]
It's a window option `:help nvim_win_set_option`

```lua
vim.api.nvim_win_set_option(0, "number", false)
-- or
vim.wo.number = false
```

**Comment by pohzipohzi** [comment]
@mjlbach right... that fixed it. Thanks for the help!
