### ISSUE TITLE
`gx` throws error on master

### ISSUE THREAD

**Issue by ckipp01** [neovim/neovim#13675]
In the current stable version  of nvim I'm able to execute a `gx` on a url and have it open for me in the browser. For example, `gx` on the below will open duckduckgo's homepage.

```lua
-- https://duckduckgo.com
```

### Actual behaviour

However, if I use the latest master and attempt to do the same thing,  I see:

```
E117: Unknown function: netrw#CheckIfRemote
E116: Invalid arguments for function netrw#BrowseX
```

- `nvim --version`: `NVIM v0.5.0-dev+7a81a0c07`
- `vim -u DEFAULTS` (version: ) behaves differently? : This just does nothing for me
- Operating system/version: macOS
- Terminal name/version: iTerm2
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```lua
-- test.lua
-- https://duckduckgo.com
```
1. `$ nvim -u NORC test.lua`
2. `gx` on link
3. see error

### Expected behaviour

I'd expect this to  just open the link in my browser the same as the stable release does

**Comment by mjlbach** [comment]
Just chiming in to say I can't reproduce this on mac.

**Comment by ckipp01** [comment]
Hmm, any idea what could be causing this for me then, since it happens with NORC for me as well.

**Comment by mjlbach** [comment]
Are you using any of mfussenegger's vim path aliases from IRC? Does it occur with the appimage from the nightly release?

**Comment by ckipp01** [comment]
> Are you using any of mfussenegger's vim path aliases from IRC? Does it occur with the appimage from the nightly release?

No, I'm not. This happens for me when I do an install with `brew install --HEAD neovim`

**Comment by ckipp01** [comment]
So I didn't realize it, but I had https://github.com/kyazdani42/nvim-tree.lua installed and it was still being loaded with NORC and this was causing issues:

https://github.com/kyazdani42/nvim-tree.lua/blob/86944b51c0e0a8fed5a02ab44640b2b215cebe93/plugin/tree.vim#L6-L7

Once the plugin was removed, there was no issue :/

**Comment by cema-sp** [comment]
Found a solution when using https://github.com/kyazdani42/nvim-tree.lua

```vim
let g:nvim_tree_disable_netrw = 0
let g:nvim_tree_hijack_netrw = 0
```
