### ISSUE TITLE
lsp doesn't seem to erase old error messages

### ISSUE THREAD

**Issue by pretentious7** [neovim/neovim#13695]
- `nvim --version`: NVIM v0.5.0-dev+950-g5ce328df4
- language server name/version: typescript-language-server 0.4.0
- Operating system/version: Ubuntu 20.04.1 x86_64

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.
```

</details>

<details>
<summary>lsp.log</summary>

```
[ ERROR ] 2021-01-05T11:32:00-0500 ] ...imjR0wyh/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:265 ]	'[tsserver] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})\n\n'
```
</details>

### Steps to reproduce using `nvim -u NORC`

Will have a reproducible project up soon.

```
nvim -u NORC
```

### Actual behaviour
After tabopening a new file, lsp seems to stop working. then on restarting the lsp with
`lua vim.lsp.stop_client(vim.lsp.get_active_clients())`
and `:edit`, the old error messages don't go away or get updated

### Expected behaviour
Old error messages should go away

**Comment by mjlbach** [comment]
Are you saying, the lsp.log contains "old" error messages from the last time a client was initialized? If so, this is by design. New entries are appended to the log.

**Comment by pretentious7** [comment]
No no not the log I mean like syntax errors in the buffer itself, I'll have a screen cast and an example up by saturday.

**Comment by mjlbach** [comment]
Ah, yes. I know what you are talking about now (I was just confused by the inclusion of the log, but I realize now that's in the issue template. I can look into this.

**Comment by mjlbach** [comment]
@tjdevries should we add a more general interface under `lsp.stop_client()` for cleanup? I think it makes sense to wipe the diagnostics/clear the display after stopping the client.
