### ISSUE TITLE
neovim-nightly was removed from AUR

### ISSUE THREAD

**Issue by lunush** [neovim/neovim#13693]
A few days ago, I installed [neovim-nightly](https://aur.archlinux.org/packages/neovim-nightly) from AUR and today it isn't there anymore. The link in the [wiki](https://github.com/neovim/neovim/wiki/Installing-Neovim#arch-linux) returns 404.

Couldn't find anything about it. Will the package be restored/replaced? Thanks!

**Comment by clason** [comment]
It's been renamed to `neovim-nightly-bin`: https://aur.archlinux.org/packages/neovim-nightly-bin/

**Comment by lunush** [comment]
Oh cool, thanks!
