### ISSUE TITLE
Store logs in XDG_CACHE_DIR rather than XDG_DATA_HOME

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#13706]
### Actual behaviour

The current output for logs is `~/.local/share/nvim/log` and the lsp logs is `~/.local/share/nvim/lsp.log`

###  Desired behaviour

We should probably log to `~/.cache/nvim/logs/lsp.log`

cc'ing @teto who brought this up. I can do this

**Comment by teto** [comment]
oh yeah please do

**Comment by mjlbach** [comment]
When I was fixing this, I noticed all of the functions documented in `:help vim.lsp.log` are undefined, am I missing something?

**Comment by justinmk** [comment]
The reason for storing logs in data was because they are data. XDG cache is defined as things that can be deleted at any time without any loss of information. That obviously doesn't apply to logs.

I do not understand why we did https://github.com/neovim/neovim/pull/13707 and https://github.com/neovim/neovim/pull/13739 .

( stdpath("cache") is nice for plugins to use, however. For actual cache data. )

**Comment by mjlbach** [comment]
I think the main issue was that XDG_DATA_HOME is commonly backed up (or potentially under version control), and log size can be very large (in the hundreds of megabytes for long running lsp logs on trace). I think historically there has been contention in the XDG standard about where logs should go, which is why XDG_STATE_HOME was recently added https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html for logging (see also https://github.com/neovim/neovim/issues/14805). 

Happy to change the log location to XDG_STATE_HOME or to revert back to XDG_DATA_HOME.

**Comment by justinmk** [comment]
My main concerns with the change:

1. churn without a strong justification
2. XDG choices were discussed thoroughly in https://github.com/neovim/neovim/pull/3470 , https://github.com/neovim/neovim/issues/78 .
    - We need to be very sure why we are changing something that was already decided, otherwise this undermines the effort that goes into the discussions in the first place, which then reduces motivation to decide things carefully in the future.
    - If there is a strong case to change a decision, reference the previous discussion with updated counterpoints. I don't see that here, not to mention the commit message...



> historically there has been contention in the XDG standard about where logs should go, which is why XDG_STATE_HOME was recently added https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html for logging

That's interesting, though it's going to be really poorly implemented. In practice this means people now have two places to backup, because applications are going to be (even more) confused about where things go.

> main issue was that XDG_DATA_HOME is commonly backed up (or potentially under version control), and log size can be very large (in the hundreds of megabytes for long running lsp logs on trace

GB-sized logs is either a bug or an intentional, temporary decision by the user to turn on the firehose. Doesn't change the nature of the data.

**Comment by p00f** [comment]
> In practice this means people now have two places to backup

I believe mjlbach said people _don't_ want to back up logs

**Comment by ruifm** [comment]
> The reason for storing logs in data was because they are data. XDG cache is defined as things that can be deleted at any time without any loss of information. That obviously doesn't apply to logs.

Does anything break if I remove the logs?

**Comment by justinmk** [comment]
> > In practice this means people now have two places to backup
> 
> I believe mjlbach said people _don't_ want to back up logs

But my point was that application developers will be confused/inconsistent ("poorly implemented") thus _in practice_ you will need to backup XDG_STATE_HOME anyway.

> Does anything break if I remove the logs?

No, but neither does anything break if you remove shada data.

**Comment by clason** [comment]
As the person who originally suggested moving to `CACHE` on chat (IIRC), let me briefly add my argument here: I was coming from the other direction, seeing how `DATA` is often the default directory for plugins -- and logs for me are much more ephemeral _in comparison_. The other argument makes sense, too, of course; there's enough room for interpretation here about what "data" means that neither choice is _obviously_ right.

That being said, the sticking point of these comments for me is that there wasn't really sufficient reason to make such a big switch, which is a fair point. By the same argument, we shouldn't simply flop back on this. I would rather see (and that was a big part of why I brought this up) a canonical, unified, log directory (`stdpath('log')`) that also plugins can be encouraged to use so I always have only a single directory to check for logs (which for all I care may be `XDG_DATA_HOME/log`).

**Comment by p00f** [comment]
> But my point was that application developers will be confused/inconsistent ("poorly implemented") thus in practice you will need to backup XDG_STATE_HOME anyway.

https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html
![image](https://user-images.githubusercontent.com/36493671/125026924-16199b00-e0a3-11eb-8a39-c212f10126c1.png)

The spec seems clear, I don't think there is room for confusion
