### ISSUE TITLE
treesitter: highlight is not updated when duplicating last line

### ISSUE THREAD

**Issue by phelipetls** [neovim/neovim#13710]
- `nvim --version`:  0.5.0 (as of https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable)
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: GNU/Linux
- Terminal name/version: st 0.8.2
- `$TERM`: st-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC teste.c
```

Assuming nvim-treesitter is installed.

Run:

```vim
packadd nvim-treesitter
TSEnableAll highlight
```

Then write:

```c
#include <stdio.h>
```

Then use `yyp`.

### Actual behaviour
The new line is not highlighted.

### Expected behaviour
The new line should be highlighted.

**Comment by clason** [comment]
It's only the last line, though -- `yyP` works, as does `yyp` the second time (so you paste the line between the two already there -- after which _all three_ lines are highlighted correctly).

**Comment by elianiva** [comment]
This also seems to be happening on Lua as well. Just like clason said, `yyP` works but `yyp` doesn't. https://streamable.com/9mdtlx

**Comment by steelsojka** [comment]
I've narrowed this down to treesitter not updating it's tree. Treesitter updates the tree when the `on_bytes` callback is called. This callback only calls (from my investigation) when an ext mark has moved, which in the case of the last line, it hasn't. I'm not sure if `on_bytes` should be called in more scenarios or if we should be using `on_lines` and computing the byte differences there. Also, there is another issue with incremental parsing within treesitter that is not working how we think it should be. @vigoux may have some more insight.

**Comment by bfredl** [comment]
@steelsojka wouldn't https://github.com/neovim/neovim/pull/13842 solve this?

**Comment by steelsojka** [comment]
@bfredl I believe it would for the most part..... I should test it. In my testing I also ran into the problem where I would manually call `parse` on the language tree after I pasted the last line and it still wouldn't highlight it. I narrowed it down to the incremental parsing portion of treesitter. If we omit passing the "old tree" it works fine.

**Comment by bfredl** [comment]
@steelsojka but that is exactly the same issue. Tree-sitter uses buffer updates **precisely** to enable incremental parsing. If updates are incorrect then incremental parsing is guaranteed to fail in the general case, no matter if it is manually invoked or not.

**Comment by steelsojka** [comment]
Oh I see now. So passing the old tree only really works if `edit` it called on the tree from the `on_bytes` callback? That would make sense. So then that should fix it.

**Comment by bfredl** [comment]
yes, or by some mechanism all edits since old_tree must be marked.  Otherwise tree-sitter doesn't know what parts of the tree that are invalid and need reparse.
