### ISSUE TITLE
Weird prompt buffer behavior in neovim but not in vim

### ISSUE THREAD

**Issue by RishabhRD** [neovim/neovim#13715]
- `nvim --version`: 
NVIM v0.5.0-dev+1012-gfe1ebea33-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/rishabh/git/neovim/build/config -I/home/rishabh/git/neovim/src -I/home/rishabh/git/neovim/.deps/usr/include -I/usr/include -I/home/rishabh/git/neovim/build/src/nvim/auto -I/home/rishabh/git/neovim/build/include
Compiled by root@acid-burn

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
- `vim -u DEFAULTS` (version: ) behaves differently?
Yes
- Operating system/version: Arch Linux
- Terminal name/version: ST
- `$TERM`: st-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set buftype=prompt<CR>
ihello<ESC>a<BS><BS>
<ESC>Iab

```

### Actual behaviour
3rd line gives `hello` and `l` and `o` are not deleted by backspace in the buffer
4th line gives ^bahello (^ represents the position of the cursor)

### Expected behaviour
3rd line gives `hel`
4th line gives ab^hello (^ represents position of cursor)

### In terms of functional tests
```lua
  it('Insert at start using I', function()
    screen:expect([[
      ^                         |
      ~                        |
      ~                        |
      ~                        |
      [Prompt]                 |
      other buffer             |
      ~                        |
      ~                        |
      ~                        |
                               |
    ]])
    feed("i")
    feed("hello<BS><BS>")
    screen:expect([[
      % hel^                    |
      ~                        |
      ~                        |
      ~                        |
      [Prompt] [+]             |
      other buffer             |
      ~                        |
      ~                        |
      ~                        |
                               |
    ]])
    feed("<Esc>I")
    feed("ab")
    screen:expect([[
      % ab^hel                  |
      ~                        |
      ~                        |
      ~                        |
      [Prompt] [+]             |
      other buffer             |
      ~                        |
      ~                        |
      ~                        |
                               |
    ]])
  end)

end)
```

If if we put these tests in `test/functional/prompt_buffer_spec.lua`, these tests fail. However, these should not fail intuitively.

Even the actual behavior of the second test is different from what we would get in practice:
```
Expected:
  |*% ab^hel                  |
  |~                        |
  |~                        |
  |~                        |
  |[Prompt] [+]             |
  |other buffer             |
  |~                        |
  |~                        |
  |~                        |
  |                         |
Actual:
  |*% ^abhel                  |
  |~                        |
  |~                        |
  |~                        |
  |[Prompt] [+]             |
  |other buffer             |
  |~                        |
  |~                        |
  |~                        |
  |                         |
```

The actual behavior we get is `^bahel`

This is not there in case of vim.

**Comment by kaddkaka** [comment]
Performing `yyp` when in prompt normal mode breaks stuff for Telescope, I'm guessing it's related to these issues mentioned here.

**Comment by Davincible** [comment]
+1 for this issue
