### ISSUE TITLE
Contradictory behavior of `-u NONE` compared to manpage

### ISSUE THREAD

**Issue by vijaymarupudi** [neovim/neovim#13716]
This is what the man page for nvim says

```
     -u vimrc    Use vimrc instead of the default ~/.config/nvim/init.vim.  If vimrc is NORC, do not load any initialization files (except plugins), and do not attempt
                 to parse environment variables.  If vimrc is NONE, loading plugins is also skipped.  :help initialization
```
EDIT:

However nvim does store the environment variables and allows the user to access them using `environ()`. After reading `starting.txt`, and @glacambre's response, this likely refers to initializations from environment variables. Could the man page be changed to read

```
     -u vimrc    Use vimrc instead of the default ~/.config/nvim/init.vim.  If vimrc is NORC, do not load any initialization files (except plugins), and do not attempt
                 to initialize from environment variables.  If vimrc is NONE, loading plugins is also skipped.  :help initialization
```

```
NVIM v0.5.0-dev+1012-gfe1ebea33
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=native -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/vijaymarupudi/.cache/yay/neovim-git/src/build/config -I/home/vijaymarupudi/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/vijaymarupudi/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/vijaymarupudi/.cache/yay/neovim-git/src/build/include
Compiled by vijaymarupudi

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by glacambre** [comment]
I think (but am not certain) that "and do not attempt to parse environment variables" refers specifically to $VIMRUNTIME and $VIM, not other environment variables.

**Comment by vijaymarupudi** [comment]
You might be right! I wonder if it is possible to clarify, as the word `parse` doesn't seem to capture what neovim is doing.

**Comment by bfredl** [comment]
What's wrong? It doesn't parse the env vars, but it doesn't delete them either.

**Comment by vijaymarupudi** [comment]
According to @glacambre, parsing could mean that $VIMRUNTIME and $VIM are taken into account. I didn't know this, but without this issue, it seems unclear to me what parsing means. Would it possible to expand on what that means in the manpage?

**Comment by bfredl** [comment]
sure but I meant was that I don't think "not parsing" implies deleting the vars.

**Comment by vijaymarupudi** [comment]
That's fair! I just didn't know what to expect by "not parsing". I can edit the issue description to reflect this.

**Comment by clason** [comment]
Coming back to this: what is _actually_ happening when you set `-u NORC`? I don't find anything related to environment variables near `NORC` in the source. (And, in fact, `VIMRUNTIME=./runtime nvim -u NORC` and then `:scriptnames` _does_ show the local plugins being sourced!)

@bfredl ?

**Comment by clason** [comment]
(Digging a bit deeper, it might specifically mean `$VIMINIT` and `$EXINIT`.)

**Comment by vijaymarupudi** [comment]
Thank you @clason!
