### ISSUE TITLE
Docs for shell-powershell suggest setting shellpipe=\|, but shellpipe is actually used to redirect to a file

### ISSUE THREAD

**Issue by filbranden** [neovim/neovim#13713]
The documentation under [`:help shell-powershell`](https://neovim.io/doc/user/options.html#shell-powershell) suggests using this configuration:

<pre>
let &shell = has('win32') ? 'powershell' : 'pwsh'
set shellquote= <b>shellpipe=\|</b> shellxquote=
set shellcmdflag=-NoLogo\ -NoProfile\ -ExecutionPolicy\ RemoteSigned\ -Command
set shellredir=\|\ Out-File\ -Encoding\ UTF8
</pre>

(Docs for powershell were originally introduced in f72f638f976347e2f14fc6ae5e5293c02d5ccfc1.)

But this setting of `'shellpipe'` is inconsistent with how `:make` uses it. It wants to use `'shellpipe'` followed by a file name to redirect output to that file. (So, yeah, the setting is definitely a misnomer!)

It would probably be more appropriate to use:

<pre>
set shellpipe=\|\ Out-File\ -Encoding\ UTF8
</pre>

(But then, I'm not a Windows or powershell guy, so I wouldn't know for sure...)

Using a simple `>` for this redirect doesn't seem to work either... It seems to produce a UTF-16 file and NeoVim then has trouble with the Unicode BOM at the start of it.

This issue was uncovered in the investigation of this Vi & Vim Stack Exchange question: [":make appending strange folder to my makeprg on Windows"](https://vi.stackexchange.com/q/28676/18609). The issue with `shellpipe=>` (which is its default value on Windows) was then uncovered in the follow up question [":make not echoing output to the command line"](https://vi.stackexchange.com/q/28684/18609).

**Comment by janlazo** [comment]
PR with `shellpipe` test is welcome.
