### ISSUE TITLE
Crash on 'lopen' if curtain is a float and float is closed

### ISSUE THREAD

**Issue by puremourning** [neovim/neovim#13721]
- `nvim --version`:

```
ben@BenMBP neovim % ./build/bin/nvim --version
NVIM v0.5.0-dev+1013-g1ad867713
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/Users/ben/Development/neovim/build/config -I/Users/ben/Development/neovim/src -I/Users/ben/Development/neovim/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/ben/Development/neovim/build/src/nvim/auto -I/Users/ben/Development/neovim/build/include
Compiled by ben@BenMBP.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
ben@BenMBP neovim %
```

- `vim -u DEFAULTS` (version: ) behaves differently? N/A, you can't focus a popup in Vim.
- Operating system/version: macOS Big Sur
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

`ben@BenMBP neovim % ./build/bin/nvim -u NORC -c 'source test_popup_lopen.vim'

```
let buf = nvim_create_buf(v:false, v:true)
call nvim_buf_set_lines(
      \ buf,
      \ 0,
      \ -1,
      \ v:true,
      \ [ 'test' ] )

let opts = {
      \ 'relative': 'cursor',
      \ 'width': 18,
      \ 'height': 18,
      \ 'col': 0,
      \ 'row': 1,
      \ 'anchor': 'NW',
      \ 'style': 'minimal'
      \ }
let win = nvim_open_win(buf, 0, opts)

call win_gotoid( win )

augroup TEST
  autocmd!
  autocmd WinLeave * :call nvim_win_close(win, v:true) | autocmd! TEST
augroup END

call setloclist( 0, [] )
lopen

```

### Actual behaviour

```
zsh: segmentation fault  ./build/bin/nvim -u NORC -c 'source test_popup_lopen.vim'
                                                                                  %
ben@BenMBP neovim %
```

w_llist is NULL

<img width="912" alt="Screenshot-2021-01-08-at-23 03 51" src="https://user-images.githubusercontent.com/10584846/104077360-580b7680-5211-11eb-8c90-db10a159fe24.png">

<img width="456" alt="Screenshot-2021-01-08-at-23 04 44" src="https://user-images.githubusercontent.com/10584846/104077363-5a6dd080-5211-11eb-8c0b-97da6bf3ba67.png">

### Expected behaviour

Not sure. It seems odd that you can even call `lopen` in a popup, but without the `autocmd`, it opens the location list for the previous window, so I guess that.

**Comment by teto** [comment]
thanks I can repro.

**Comment by jez** [comment]
Sorry for the off-topic question: @puremourning can I ask what the setup is that generates the left hand side of the first screenshot above?

**Comment by puremourning** [comment]
That’s right. I was testing a [new vimspector feature](https://www.reddit.com/r/vimplugins/comments/lp8xom/vimspector_announcing_new_balloon_popup_with/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) that triggered this.

**Comment by chentau** [comment]
@puremourning Can you try out the linked PR to see if it fixes this crash?

**Comment by puremourning** [comment]
Appears to fix the crash, yes.
