### ISSUE TITLE
`uv.spawn` returns nothing on windows

### ISSUE THREAD

**Issue by sp1n0r** [neovim/neovim#13736]
- `nvim --version`: 0.5.0
- Operating system/version: Windows
- Terminal name/version: alacritty

### Steps to reproduce using `nvim -u NORC`
Create a lua file with the following:
```
local uv = vim.loop

local stdin = uv.new_pipe(false)
local stdout = uv.new_pipe(false)
local stderr = uv.new_pipe(false)

local handle = uv.spawn("rg", {
  args = { 'a' },
  stdio = { stdin, stdout, stderr }
}, function() end)

uv.read_start(stdout, function(err, data)
  assert(not err, err)
  if data then
    print(vim.inspect(data))
  end
end)

uv.read_start(stderr, function() end)

uv.shutdown(stdin, function()
  uv.close(handle, function() end)
end)
```
Do `:luafile %`

### Actual behaviour
Nothing happens.

### Expected behaviour
Should produce the same output as the command `rg a` in the terminal.
Also, replacing the `a` with `--files` works fine. I think this is why this [issue](https://github.com/nvim-telescope/telescope.nvim/issues/385) happens.

**Comment by jamessan** [comment]
> Also, replacing the `a` with `--files` works fine.

If changing how rg is called makes this work, why do you think this is a problem with nvim instead of rg?

Can you try changing `args = { 'a' }` to `args = { 'a', '.' }`?

**Comment by sp1n0r** [comment]
With `args = { 'a', '.' } ` it works fine. I assumed it was the case because in the terminal simply `rg a` works

**Comment by sp1n0r** [comment]
Thanks :D

**Comment by jamessan** [comment]
When run via a pipe, rg thinks it should be searching the contents of the pipe rather than the files in the working directory. That auto-detection needs to be overridden by specifying the directory/file to search.
