### ISSUE TITLE
nvim --help shows -Z flag, which has been removed

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#13731]
- `nvim --version`: NVIM v0.5.0-dev+1012-gfe1ebea33
- `vim -u DEFAULTS` (version: ) behaves differently? Not applicable, since `vim` retains `-Z`
- Operating system/version: Ubuntu 20.04.1 LTS
- Terminal name/version: Konsole 19.12.3
- `$TERM`: xterm-256color

`nvim --help` shows the `-Z` flag, which was removed in PR #11996.

In PR #13338, a lingering reference was removed from the man page.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC --help | grep '\-Z'
```

### Actual behaviour

Output:
```
  -Z                    Restricted mode
```

### Expected behaviour

No output

**Comment by srafi1** [comment]
I'm down to fix this, but, just to make sure, I have to remove the `-Z` help text from `src/nvim/main.c:2047` and then remove it from all translations right?
