### ISSUE TITLE
how to install neovim in ubuntu by non-root user？

### ISSUE THREAD

**Issue by tianyinggang** [neovim/neovim#13737]

**Comment by tianyinggang** [comment]
I 'm using vim7.2 now, want to change to the neovim ,I'm not sure if Ubuntu has fuse

**Comment by jdhao** [comment]
@tianyinggang  Does the [binary release for Linux](https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip) satisfy your need?

**Comment by tianyinggang** [comment]
![image](https://user-images.githubusercontent.com/35682964/104276801-8ffc0d80-54e0-11eb-9ece-536f124b3cd2.png)
I used source code zip file to make ,but happened the problem.

I didn't make by  nvim.appimage ,because I am non-root user ,don 't add permission .

My ubuntu can't connect to the network. I need another computer to download the required dependent files. Please tell me which dependent files I need to install neovim offline

**Comment by jdhao** [comment]
If you just want to use Neovim, there is no need to build it from source. The link I provided is an [executable file](https://en.wikipedia.org/wiki/Executable) which is directly runnable. 

If you want to build neovim from source, have you check the [relevant documentation](https://github.com/neovim/neovim/wiki/Building-Neovim)?

**Comment by tianyinggang** [comment]
@jdhao please check the binary release for Linux link , I check it is https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip , I download the nvim.appimage from release download page ,but I 'm non-root user , don 't add permission .
Thanks very much ！！！
felix

**Comment by jdhao** [comment]
Sorry, I post the wrong link, for Linux. You should use https://github.com/neovim/neovim/releases/download/v0.4.4/nvim-linux64.tar.gz.  Just extract the file to use Neovim.

**Comment by teto** [comment]
as for most software, you can install it in a different folder than the default, for instance in your $HOME/neovim. See https://github.com/neovim/neovim/issues/9743 for some intuition. Closing since it's not a neovim bug.
