### ISSUE TITLE
"nightly" tag no longer available on github?

### ISSUE THREAD

**Issue by el-iot** [neovim/neovim#13747]
I have been using the nightly-releases for nvim for some time but recently I realised that the url I had been using to download the appimage ("https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage") now returns a 404. Is there any way I can still get access to nightly releases via github?

**Comment by jamessan** [comment]
Wait for the next nightly to build.

**Comment by Bhanukamax** [comment]
> Wait for the next nightly to build.

Hi is there a way to get notified in some sort, when the latest nightly build is ready?

**Comment by jamessan** [comment]
You can [watch for releases](https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/viewing-your-subscriptions#configuring-your-watch-settings-for-an-individual-repository).

**Comment by DavidGamba** [comment]
Is this issue resolved? I can't find the nightlies either: https://github.com/neovim/neovim/releases/nightly
