### ISSUE TITLE
The "Microsoft Store Checker" treats the Neovim executable as an installer

### ISSUE THREAD

**Issue by jpleboeuf** [neovim/neovim#13743]
- NVIM version: v0.4.4
- Operating system/version: Windows 10 Home 1909

I have the "Microsoft Store Checker" enabled on Windows: before going on with an installation, it checks if the application to be installed is available on the Microsoft Store (Windows Apps).
I created a Windows shortcut to Neovim (QT) on the desktop: each time I launch Neovim through the shortcut (or directly clicking the .exe), Windows searches for Neovim on the Microsoft Store.

Expected behaviour: the "Microsoft Store Checker" should treat Neovim as a program, not an installer.

<img width="272" alt="Neovim Shortcut Properties" src="https://user-images.githubusercontent.com/6379573/104378464-50f1aa80-5528-11eb-9963-2603e7bfebc8.png">
<img width="481" alt="Microsoft Store Warning" src="https://user-images.githubusercontent.com/6379573/104378536-7088d300-5528-11eb-9362-8de8ddff5839.png">
<img width="275" alt="Apps & Features Settings" src="https://user-images.githubusercontent.com/6379573/104378505-623ab700-5528-11eb-8e82-d96ad24ffffd.png">

**Comment by jpleboeuf** [comment]
I found a solution.

Most of the files in my `Neovim\` directory had an NTFS alternative data stream (ADS) attached.
It can been seen with Windows Sysinternals [Streams](https://docs.microsoft.com/en-us/sysinternals/downloads/streams):

```
$ streams "C:\Program Files\Neovim\bin\nvim-qt.exe"

streams v1.60 - Reveal NTFS alternate streams.
Copyright (C) 2005-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

C:\Program Files\Neovim\bin\nvim-qt.exe:
   :Zone.Identifier:$DATA       79
```

I suppose it means these files are from the Internet / untrusted.
I used Microsoft Edge (Chromium) to download Neovim, therefore it may be the culprit.

It can be fixed by opening a Windows Command Prompt as admin and requesting a recursive removal of the NTFS alternative data streams attached to the `Neovim\` directory:

```
# cd "C:\Program Files"
# streams -s -d Neovim
...
C:\Program Files\Neovim\bin\nvim-qt.exe:
   Deleted :Zone.Identifier:$DATA
...
```

Is it worthy of being added to the "[Installing Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim)" page? - section "Install from package" > "Windows" > "[Pre-built archives](https://github.com/neovim/neovim/wiki/Installing-Neovim#pre-built-archives)".

**Comment by erw7** [comment]
It seems to have been resolved, so I will close it.

Note that this is a tracker for neovim issues and feature requests. I think it would be more appropriate to post this question to the [Microsoft community](https://answers.microsoft.com/en-us), etc.

**Comment by jpleboeuf** [comment]
From my point of view, this is an issue, and it lies within the documentation of Neovim.

In the aforementioned section, we can read "Unzip the package. Any location is fine, administrator privileges are not required." Yes, but one needs to check that undesired NTFS alternative data streams are wiped, or one may receive annoying notifications from MS Windows.

Anyway, at least a solution exists in this thread.
