### ISSUE TITLE
lsp.buf.hover popup shows incorrect markdown syntax highlighting

### ISSUE THREAD

**Issue by pohzipohzi** [neovim/neovim#13746]
The default popup for `vim.lsp.buf.hover()` shows additional "Error" syntax highlighting, as per the following image:

![image](https://user-images.githubusercontent.com/16781840/104397005-cb511780-5586-11eb-8ece-61354bac614c.png)

It appears that the issue is  due to a conflict in `util.fancy_floating_markdown()` where markdown syntax highlighting doesn't recognise the additional padding added on the sides (ref `runtime/lua/vim/lsp/handlers.lua:249`). I can confirm that this is a non-issue if pad_left and pad_right is set to 0 instead.

- `nvim --version`: NVIM v0.5.0-dev+1015-g0860d9c16
- language server name/version: gopls devel
- Operating system/version: macos

<details>
<summary>lsp.log</summary>
[ DEBUG ] 2021-01-13T10:00:01+0800 ] /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:394 ]	"default_handler"	"textDocument/hover"	{  bufnr = 3,  client_id = 2,  params = {    contents = {      kind = "markdown",      value = '```go\ntype Profile struct {\n\tCPU    string `flag:"profile.cpu" help:"write CPU profile to this file"`\n\tMemory string `flag:"profile.mem" help:"write memory profile to this file"`\n\tTrace  string `flag:"profile.trace" help:"write trace log to this file"`\n}\n```\n\n[`tool.Profile` on pkg.go.dev](https://pkg.go.dev/golang.org/x/tools/internal/tool?utm_source=gopls#Profile)\n\nProfile can be embedded in your application struct to automatically\nadd command line arguments and handling for the common profiling methods\\.\n'    },    range = {      end = {        character = 12,        line = 40      },      start = {        character = 5,        line = 40      }    }  }}
</details>

### Steps to reproduce using `nvim -u NORC`

Using the following minimal config

```
call plug#begin()
Plug 'neovim/nvim-lspconfig'
call plug#end()
lua require 'lspconfig'.gopls.setup{}
```

Navigate to any go file and run `:lua vim.lsp.buf.hover()`

### Actual behaviour

As mentioned above

### Expected behaviour

There should be no additional "error" syntax highlights

**Comment by mjlbach** [comment]
@pohzipohzi Can you try this branch? https://github.com/mjlbach/neovim/tree/fix_whitespace_floating_window

**Comment by pohzipohzi** [comment]
@mjlbach thanks for the response. Unfortunately the branch doesn't seem to work

The additional highlights show up everywhere, such as with this code:

```
package main

import "fmt"

func main() {
	fmt.Println("hello")
}
```

vim config:

```
call plug#begin()
Plug 'neovim/nvim-lspconfig'
call plug#end()
lua require 'lspconfig'.gopls.setup{}
```

screenshot with default mac terminal:

![image](https://user-images.githubusercontent.com/16781840/104537588-3537f280-5655-11eb-96ae-223905de41d5.png)


Additionally, I'm using the latest master version of gopls, which has a SHA of `f96436850f18fde81b5d35936abcb91f5caa8f20`

**Comment by mjlbach** [comment]
Ah, I had the wrong syntax group. It's mkdLineBreak. Try testing again.

**Comment by mjlbach** [comment]
If you pulled in the last minute, make sure to pull again as I forgot to push 😆

**Comment by pohzipohzi** [comment]
hmm unfortunately the issue persists for me

**Comment by mjlbach** [comment]
I'm not able to reproduce the issue then. My colorscheme doesn't show any of the issues by default, but on the default colorscheme on a standard terminal, this is what it looks like on master:
<img width="1280" alt="Screen Shot 2021-01-13 at 7 14 32 PM" src="https://user-images.githubusercontent.com/13316262/104540219-e1d19000-55d3-11eb-856e-45303b30d1f9.png">


This is what it looks like with my PR:
<img width="1280" alt="Screen Shot 2021-01-13 at 7 16 39 PM" src="https://user-images.githubusercontent.com/13316262/104540227-e8600780-55d3-11eb-8d7d-4b05ebda4339.png">

If you toggle to the floating window (c-w until you see your cursor in), does `:lua vim.cmd("syntax clear mkdLineBreak") ` not fix it?

**Comment by pohzipohzi** [comment]
indeed it doesn't. Thanks to your tip however (i didn't know i can toggle to the floating window via c-w), I found out that the syntax that needed to be cleared was `goSpaceError` (via `:echo synIDattr(synID(line("."), col("."), 1), "name")`), so `:syntax clear goSpaceError` works for me. Interestingly I'm not getting the additional highlights on the left that are on your first screenshot

**Comment by mjlbach** [comment]
Ah, if individual syntax errors are causing issues for each language embedded in the markdown, I'm not sure what to do. I'm not sure if we can clear the highlight group instead of the syntax per window.

**Comment by akinsho** [comment]
As a random aside, I think the go space error is extra highlighting from the `vim-go` syntax file if you are using `vim-go` or `polyglot.vim` which uses vim go and can be turned off separately. 
```vim
" there might be others
let g:go_highlight_space_tab_error
```
I've used the `mkdLinkBreak` clear in my `init.lua` for a quite a few different languages and I think removing that will solve the issue for most users in most languages i.e. I don't think it's common to have other custom space related highlights I believe that's quite rare and plugin related (not 100% sure about this but think that's the case)

I think long term I wonder if this could be handled by treesitter markdown highlighting (with language injection) although given the experimental nature of that and the need to have something that works out of the box maybe that won't be possible for quite a while or without some separate plugin 😞

**Comment by pohzipohzi** [comment]
> the go space error is extra highlighting from the vim-go syntax file if you are using vim-go or polyglot.vim which uses vim go and can be turned off separately.

hmm i'm neither using vim-go nor polyglot.vim. `goSpaceError` seems baked into the runtime for a long time already actually (see [syntax/go.vim](https://github.com/neovim/neovim/blob/master/runtime/syntax/go.vim#L165)) so I'm surprised I'm the only one encountering this

**Comment by akinsho** [comment]
👍🏿  it also seems to be something that can be turned off though? although you might not want it turned off in your code generally, but in that case it makes sense that it would apply everywhere that the go syntax is source e.g. in the floating win.

**Comment by nghialm269** [comment]
I can reproduce this with or without `vim-go`:
![image](https://user-images.githubusercontent.com/13317164/104605091-a658c380-56b0-11eb-8592-28f3150ea265.png)

@mjlbach:
I added the line `vim.cmd("syntax clear mkdLineBreak")` to my `util.lua` and I got this error when trying to show hover:
![image](https://user-images.githubusercontent.com/13317164/104604886-6abdf980-56b0-11eb-954c-c3d40257bd51.png)

**Comment by mjlbach** [comment]
Yeah, I don't know how to address this generally as we just naively inherit your syntax rules and apply them to what's rendered in the floating window. If people can send me files that reproduce, along with a minimal init.vim that reproduces the issue, that will be helpful.

**Comment by owarai** [comment]
It's easy to reproduce.

`init.vim`
```vim
set bg=light
lua require("plugins")
```

then clone `packer.nvim` to somewhere on your `packpath` like:
```
git clone https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/opt/packer.nvim
```

Add `lua/plugins.lua`
```lua
vim.cmd [[packadd packer.nvim]]
return require('packer').startup(function()
  -- Packer can manage itself as an optional plugin
  use {
    'wbthomason/packer.nvim',
    opt = true,
  }
  use {
    'neovim/nvim-lspconfig',
    config = function()
      local nvim_lsp = require('lspconfig')
      local on_attach = function(client, bufnr)
        local function buf_set_keymap(...)
          vim.api.nvim_buf_set_keymap(bufnr, ...)
        end
        local function buf_set_option(...)
          vim.api.nvim_buf_set_option(bufnr, ...)
        end

        buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

        -- Mappings.
        local opts = {
          noremap = true,
          silent = true,
        }
        buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
        buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
        buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
        buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
        buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
        buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
        buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
        buf_set_keymap('n', '<space>wl',
          '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
        buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
        buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
        buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
        buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>',
          opts)
        buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
        buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
        buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)

        -- Set some keybinds conditional on server capabilities
        if client.resolved_capabilities.document_formatting then
          buf_set_keymap("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
        elseif client.resolved_capabilities.document_range_formatting then
          buf_set_keymap("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
        end
      end

      -- Use a loop to conveniently both setup defined servers
      -- and map buffer local keybindings when the language server attaches
      local servers = {
        "gopls",
      }
      for _, lsp in ipairs(servers) do
        nvim_lsp[lsp].setup {
          on_attach = on_attach,
        }
      end
    end,
  }
end)
```

then create a go repo somewhere like:

`go.mod`:
```
module github.com/owarai/hoverissue

go 1.15
```

`main.go`:
```go
package main

import (
        "flag"
        "fmt"
)

func main() {
        var name string
        flag.StringVar(&name, "name", "world", "your name")
        flag.Parse()
        fmt.Println("hello, " + name)
}
```

For example, place your cursor on `flag.Parse`, and press `K`, this render problem will occurred.

![image](https://user-images.githubusercontent.com/9746281/105121895-226b6500-5b10-11eb-820c-e9a60f08a362.png)

**Comment by mjlbach** [comment]
@owarai the issue isn't that I can't find *a single* reproduction, but that I need many reproductions to know exactly which syntax rules we need to setup to ignore the whitespace highlighting.

**Comment by owarai** [comment]
Thank you for your efforts to try to address this issue.
Also sorry for not reading the context in details before post.

**Comment by mjlbach** [comment]
Owarai

**Comment by mjlbach** [comment]
Ok, it seems like the only thing all of these groups have in common is that they are all syntax links to the Error group, but currently in vim, there's no way to clear links given only the target (Error) name. 

* If we `:hi clear Error` it clears it for both the floating window and the buffer
* If we `:syntax clear Error`, it doesn't clear anything, since the link to Error is already set
* If we `:syntax clear goSpaceError`, it only clears for go, so we'd need to list every offending syntax rule, and we can't maintain a list of these syntax groups since it's unweildy, and plugins are free to add their own

**Comment by owarai** [comment]
@mjlbach  Do you know why some character is escaped by backslash in the floating window?

**Comment by mjlbach** [comment]
Well, this is the raw message from the server, you can see the escaped backslash. We can probably clean that up, but that should be filed in another issue.
```
[ DEBUG ] 2021-01-19T19:38:12-0800 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  id = 4,  jsonrpc = "2.0",  result = {    contents = {      kind = "markdown",      value = "```go\nfunc flag.Parse()\n```\n\n[`flag.Parse` on pkg.go.dev](https://pkg.go.dev/flag?utm_source=gopls#Parse)\n\nParse parses the command\\-line flags from os\\.Args\\[1\\:\\]\\. Must be called\nafter all flags are defined and before flags are accessed by the program\\.\n"    },    range = {      end = {        character = 18,        line = 10      },      start = {        character = 13,        line = 10      }    }  }}
```

**Comment by mjlbach** [comment]
I'm going to guess around here is where the string should be sanitized `https://github.com/mjlbach/neovim/blob/47b29e775aae3b28203c4321d351ae4b3f72eedc/runtime/lua/vim/lsp/util.lua#L526-L531`

**Comment by mjlbach** [comment]
@tjdevries one trivial fix to this would be to disable padding here and just add a parent floating window for the padding (like we do for borders). The other option would be to wait for #13998. Adding whitespace like we do, and then writing a syntax rule to ignore it is probably not the way to go.

**Comment by DrGo** [comment]
This is what my completion + hover popup looks like using a paper-like colorscheme (light background) and gopls. Is there a way to turn off syntax highlighting in the hover popup? It is too distracting. Thanks

![image](https://user-images.githubusercontent.com/12840815/111183001-75e0b900-857d-11eb-8d42-6ca458b490ab.png)

**Comment by mjlbach** [comment]
Usage questions belong on our discourse https://neovim.discourse.group/c/7-category/7

There's not a setting you can change, you'll have to override the handler for hover and replace the fancy floating markdown function with something else. It's much easier to edit your colorscheme.

**Comment by DrGo** [comment]
This was not a usage question.. more like a suggested possible solution to this issue. A random hit-and-miss syntax highlighting of a manual page that is displayed on top of a syntax-highlighted code is not going to be appealing to many users. The solution should not be that everyone maintains their own edited version of gruvbox or of the standard hover handler. Would not it make more sense to have an option that disable syntax highlighting in the hover popup?

**Comment by mjlbach** [comment]
>  Is there a way to turn off syntax highlighting in the hover popup? It is too distracting. Thanks

This is a usage question, which I did answer. You need to override the handler. I doubt we'll add an option for this, as we already make it very easy to override handlers.

**Comment by DrGo** [comment]
OK. Let us see what others think

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/underscores-highlighted-in-signature-help/306/2

**Comment by mjlbach** [comment]
@pohzipohzi You can try out #14207

**Comment by pohzipohzi** [comment]
works nicely, thank you so much for this @mjlbach !

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/incorrect-docs-formatting-in-vim-lsp-buf-hover/5090/1
