### ISSUE TITLE
Add 'runtime' command to luafile.

### ISSUE THREAD

**Issue by peach-lasagna** [neovim/neovim#13755]
- `nvim --version`: v0.5.0-dev
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: Windows 10 wsl ubuntu

I would like to use the runtime command on lua files (along with luafile). Is there a possibility?
### Actual behaviour
ls:
```bash
| ~/.config/nvim  master                                                                                                                                   
╰─> ls                                                                                                                                                                           ─╯
eviline.lua  init.vim 
```
in init.vim:
```vimscript
luafile ./eviline.lua
```

![изображение](https://user-images.githubusercontent.com/59787538/104625154-035f7400-56c7-11eb-98cc-438d99f65eec.png)

### Expected behaviour
luafileruntime ./eviline.lua
_no errors_

**Comment by peach-lasagna** [comment]
Now i did this:
1) run in bash:
```bash
~/.config/nvim -> mv  eviline.lua ./lua
```
2) write in init.vim
```
lua require 'eviline'
```

**Comment by glacambre** [comment]
Another equivalent to your `:luafileruntime` command would be `execute("luafile " . expand('<sfile>:p:h') . "/eviline.lua")`. I'm not sure implementing a command for something so trivial is really necessary.

**Comment by peach-lasagna** [comment]
Thx!

**Comment by bfredl** [comment]
require only supports loading one runtime file tho, to replace all vimL functionality `runtime!` is also needed. We could add `vim.load_runtime()` entirely written in lua without touching ex commands.
