### ISSUE TITLE
.nvimlog in every directory I work in

### ISSUE THREAD

**Issue by dimbleby** [neovim/neovim#13753]
- `nvim --version`: NVIM v0.5.0-dev+1023-gea8756f85 
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
open a file, edit it, close the file
```

### Actual behaviour
`.nvimlog` is placed in the local directory
### Expected behaviour
`.nvimlog` is not placed in the local directory

A result of #13739 presumably.  

If I create the directory `~/.cache/nvim` myself then neovim uses it.  Shouldn't neovim have created that directory?

**Comment by mjlbach** [comment]
My bad, I'll try to fix this today.

**Comment by mjlbach** [comment]
Ok, ultimately what create stdpath("data") is in rplugin.vim, so log.vim?

**Comment by mpcsh** [comment]
I already have a `~/.cache/nvim` directory and I'm still seeing this issue - does that change anything?

**Comment by mjlbach** [comment]
@mpcsh Do you want to try  #13758 and see if you still have the issue?

**Comment by mpcsh** [comment]
I'm on macOS 11.1 build 20C69 on the M1 MacBook Air. I can give that PR a try hopefully over the weekend when I have some time.

**Comment by mjlbach** [comment]
I use mac and don't have the issue when I manually create ~/.cache/nvim. Maybe check the write perms?

**Comment by mpcsh** [comment]
755 and the owner / group are correct 🤷‍♂️

**Comment by mjlbach** [comment]
The issue should be fixed. If you still have an issue with this, you should see an error as to why in `.nvimlog`

**Comment by ZacharyRizer** [comment]
I am still having this issue. 

nvim --version = NVIM v0.5.0-dev+1028-g702208daa

the nvimlog's are empty, I don't see any error messages.

**Comment by mjlbach** [comment]
You need to use a debug build now for the error message to show u.

1. Install the build [dependencies](https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites) if you haven't.
2. Clone the git repo
3. run `make`
4. If .nvimlog is still present there should be an error message as why

**Comment by schiffermtq** [comment]
I'm still seeing this issue as well, with nvim 0.5.0+ubuntu2+git202101240619-69103ff0c-d569569c9-523645f61~ubuntu18.04.1.

~/.cache/nvim exists. `.nvimlog` is empty.

**Comment by mjlbach** [comment]
@schiffermtq I went through detailed instructions on how to debug this in https://github.com/neovim/neovim/pull/13758

In short, it's likely that the permissions or owner on ~/.cache, ~/.cache/nvim ~/.cache/nvim/log are incorrect, but if you s/lldb/gdb (and the associated commands) and follow the steps in that PR, then the problem should be apparent.

**Comment by schiffermtq** [comment]
@mjlbach Thanks, it was indeed a permission problem. For some reason, `~/.cache/nvim` was owned by root, even though I thought I had deleted and recreated it as my regular user...
