### ISSUE TITLE
[RFC] Treesitter implement optional start and end row on captures and matches functions

### ISSUE THREAD

**Issue by jvgrootveld** [neovim/neovim#13761]
The documentation of [`query:iter_captures`](https://neovim.io/doc/user/treesitter.html#query:iter_captures()) implicates that the `start_row` and `end_row` parameters are optional.

> {start_row} and {end_row} **can** be used to limit matches inside a row range...

### Possible solution

Isn't this as simple as checking the given parameter values and setting the default of the node when nil?
- `Query:iter_captures` at [query.lua#L352](https://github.com/neovim/neovim/blob/9223d1450d391b06cd59f8469c53291281899c9f/runtime/lua/vim/treesitter/query.lua#L352)
- `Query:iter_matches` at [query.lua#L384](https://github.com/neovim/neovim/blob/9223d1450d391b06cd59f8469c53291281899c9f/runtime/lua/vim/treesitter/query.lua#L384)

Something like:
```lua
if start == nil and stop == nil then
    start, _, stop, _ = node:range()
end
```

**Comment by vigoux** [comment]
Hi, thanks for reporting, I'd agree with such a change, do you want to open a PR for it or shall I do it ?

**Comment by jvgrootveld** [comment]
@vigoux Slowly trying to contribute to awesome open source projects so I will make a PR.
I will check if I can setup neovim to test this change. I keep you posted trough this issue.

**Comment by vigoux** [comment]
I subscribed to this issue, and will be subscribed to the PR to, so I'll watch closely 😉

**Comment by vigoux** [comment]
Closing as the PR was merged
