### ISSUE TITLE
Duplicate "CompletionDone" events fired with multiple LSPs

### ISSUE THREAD

**Issue by mhartington** [neovim/neovim#13766]
## Problem

If multiple LSP servers are attached to a buffer, when you trigger omni-completion there will be multiple `CompletionDone` events fired for each server. 

- Related: https://github.com/neovim/neovim/issues/17712
- Found while debugging #13414. 
- This seems to be a similar issue to what @tjdevries fixed in #12655 

## Expected behaviour

When completion is finished, it should only fire CompletionDone once for all servers attached.

**Comment by mjlbach** [comment]
Isn't this expected? vim.fn.complete is called once per server completion result in the callback function passed to the buf request, each of which should trigger `CompleteDone`

https://github.com/mjlbach/neovim/blob/3d25a72a60323c9d6eab2daf9dbd4920b94b8a94/runtime/lua/vim/lsp.lua#L1233-L1239

**Comment by mhartington** [comment]
yeah, it's to be expected with the current implementation. Though in other environments, this is not the case, like vscode. Requests are sent to the server and queued up before returning a response. So for N number of servers attached to a buffer, the requests will be made, a single table will be created with the results, and the call back will be called with a combined set of results.

**Comment by mjlbach** [comment]
Right, that's true, but the advantage of our current implementation is that vim.fn.complete is called as soon as the request returns, allowing async population of the return results. If we wait until each completion result returns, and then aggregate the results before populating the completion list, the bottleneck will be the slowest server. I'm not sure if complete_add triggers complete_done, but one option would be to open the completion menu, and then call complete_add in the callback functions.

**Comment by MagicDuck** [comment]
I agree with @mjlbach that async population of results is better. In my case (#14330), I work with a large project and tsserver can be a bit slow to provide code actions sometimes, but would still like to see the code actions from the other language server. I don't think this is clearly documented now though, because every LSP UI I've tried using, like lsp-saga, etc. assumes that there is only one handler call. Even the default `textDocument/codeAction` handler assumes that as it blocks for user input.

**Comment by mfussenegger** [comment]
I think this was fixed with either https://github.com/neovim/neovim/commit/ff097f2091e7a970e5b12960683b4dade5563040 or https://github.com/neovim/neovim/commit/4c938f6d72710507db22074951eee23869ed49e0
