### ISSUE TITLE
aarch64: Memory address outside required range in bundled luajit

### ISSUE THREAD

**Issue by huyiqun** [neovim/neovim#13760]
I am looking to use a plugin that requires neovim >= 0.5.0 so I am trying to build from source on my aarch64 machine (since Arch's neovim nightly build only has x86_64 and I couldn't seem to find an appimage).

I cloned the repo and ran `make CMAKE_BUILD_TYPE=Release` and received the following error:

```
[Omitted]
[96/106] Performing install step for 'luarocks'
make[1]: Entering directory '/home/xx/neovim/.deps/build/src/luarocks'
mkdir -p "build"
mkdir -p .luarocks
cp ./build/config-5.1.lua .luarocks/config-5.1.lua
rm -f src/luarocks/core/hardcoded.lua
echo "#!/bin/sh" > luarocks
echo "unset LUA_PATH LUA_PATH_5_2 LUA_PATH_5_3 LUA_PATH_5_4 LUA_CPATH LUA_CPATH_5_2 LUA_CPATH_5_3 LUA_CPATH_5_4" >> luarocks
echo 'LUAROCKS_SYSCONFDIR="/home/xx/neovim/.deps/usr/etc/luarocks" LUA_PATH="/home/xx/neovim/.deps/build/src/luarocks/src/?.lua;;" exec "/home/xx/neovim/.deps/usr/bin/luajit" "/home/xx/neovim/.deps/build/src/luarocks/src/bin/luarocks" --project-tree="/home/xx/neovim/.deps/build/src/luarocks/lua_modules" "$@"' >> luarocks
chmod +rx ./luarocks
./luarocks init

Initializing project 'luarocks' for Lua 5.1 ...
-----------------------------------------------

Checking your Lua installation ...
Adding entries to .gitignore ...
Preparing ./.luarocks/ ...
Wrote .luarocks/config-5.1.lua
Preparing ./lua_modules/ ...
./luarocks already exists. Not overwriting it!
Preparing ./lua for version 5.1...
mkdir -p "/home/xx/neovim/.deps/usr/etc/luarocks"
install -m 644 "build/config-5.1.lua" "/home/xx/neovim/.deps/usr/etc/luarocks/config-5.1.lua"
./luarocks make --tree="/home/xx/neovim/.deps/usr"

No existing manifest. Attempting to rebuild...
luarocks 3.2.1-1 is now installed in /home/xx/neovim/.deps/usr (license: MIT)

make[1]: Leaving directory '/home/xx/neovim/.deps/build/src/luarocks'
[98/106] Generating usr/lib/luarocks/rocks-5.1/mpack
FAILED: usr/lib/luarocks/rocks-5.1/mpack
cd /home/xx/neovim/.deps && /home/xx/neovim/.deps/usr/bin/luarocks build mpack 1.0.8-0 CC=/usr/bin/cc LD=/usr/bin/cc
LuaJIT ASSERT lj_gc.c:863: lj_mem_realloc: allocated memory address 0xffffa3bc3010 outside required range
ninja: build stopped: subcommand failed.
make: *** [Makefile:105: deps] Error 1
```
I couldn't find more info online and I don't have any experience with lua/luajit. Is this a hardware related issue or is there a way to relax the memory limit in lua/luajit? Would I be able to tweak something to avoid this error? (Total RAM is 8GB and I hope that would not be the bottleneck).

**Comment by bfredl** [comment]
hmm I thought we bumped luajit in our bundled dependencies for the latest aarch64 patches on v2.1 branch (2.1beta3 is not enough unfortunately). what aarch64 machine is it more specifically?

**Comment by huyiqun** [comment]
```
OS: Manjaro ARM Linux aarch64
Host: Raspberry Pi 4 Model B Rev 1.4
Kernel: 5.4.83-1-MANJARO-ARM
Memory: 7827MiB
```
Any other info you need?

**Comment by bfredl** [comment]
I have a pi4 myself so i might try it later :)

**Comment by huyiqun** [comment]
Awesome!! Thanks a lot :) I have been stuck on this for hours (also tried installing using Arch's `makepkg` using the script in AUR as well as with other flags like USE_BUNDLED_OFF, PREFER_LUA=On, etc... ) 😵

**Comment by clason** [comment]
Might also want to try #13741 (probably not going to make a difference since these are mostly identical, but one never knows).

**Comment by huyiqun** [comment]
Digging around and happen to found this: https://eliasdaler.github.io/luavela/, which mentioned the luajit's 1GB limit if run on 64bit system. I tested the installation of the nightly build on raspberry pi os (32-bit) where everything compiled successfully, but when I switched to manjaro and ubuntu server (both 64-bit), the same error message shows. So this concludes where the problem is.

Any way to bypass using this version of luajit?

**Comment by carlocab** [comment]
Try adding `XCFLAGS=-DLUAJIT_ENABLEGC64`. I had a quick glance at [BuildLuajit.cmake](https://github.com/neovim/neovim/blob/master/third-party/cmake/BuildLuajit.cmake) and it doesn't appear to be set there, though I could've missed it.

There's also a chance I could've misunderstood what this flag does, exactly, but this sounds promising: https://blog.openresty.com/en/luajit-gc64-mode/

**Comment by oconnor663** [comment]
Forgive me if this is obvious to the maintainers, but I bisect this problem to this commit:

```
commit 12709c475b38f354bb17dd12d543662fb6db370c       
Author: Tae Won Ha <h@taewon.de>                                                               
Date:   Sat Jul 11 14:34:13 2020 +0200
                                                                                               
    Use the latest luajit for arm64 Mac compatibility.
```

After that commit, I get build failures with this error:

```
[ 87%] Generating usr/lib/luarocks/rocks-5.1/mpack
LuaJIT ASSERT lj_gc.c:864: lj_mem_realloc: allocated memory address 0xffff91e1c010 outside required range
```

Prior to that commit, the build still fails for me, but with a different error:

```
[ 87%] Generating usr/lib/luarocks/rocks-5.1/mpack
luajit: lj_gc.c:822: lj_mem_realloc: Assertion `(1 ? (((uint64_t)(uintptr_t)((p)) >> 47) == 0) : 1 ? ((uintptr_t)((p)) == (uint32_t)(uintptr_t)((p))) :1)' failed.
```

I'm on a fresh aarch64 AWS instance:

```
$ uname -a
Linux arch_bench 4.14.214-160.339.amzn2.aarch64 #1 SMP Sun Jan 10 05:53:19 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by cbows** [comment]
I run into the same issue (`memory address outside required range`) when I try to build neovim HEAD on a Pine64 Pinebook Pro with Manjaro ARM Linux aarch64.  To be able to build, I installed all 3rd-party dependencies from the Arch repositories (`pacman -S gperf luajit jemalloc unibilium libmpack libtermkey libvterm lua51 lua51-mpack lua51-lpeg lua51-bitop`) and then build with `make CMAKE_BUILD_TYPE=RelWithDebInfo USE_BUNDLED=OFF`

**Comment by huyiqun** [comment]
Thanks for all the effort and fixes!
