### ISSUE TITLE
Virtual text is not shown while working with multiple files

### ISSUE THREAD

**Issue by unknownspacewalker** [neovim/neovim#13777]
- `nvim --version`: 
```
NVIM v0.5.0-dev+0f2d37f11
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210117-72919-1msimt6/build/config -I/tmp/neovim-20210117-72919-1msimt6/src -I/usr/local/include -I/tmp/neovim-20210117-72919-1msimt6/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210117-72919-1msimt6/build/src/nvim/auto -I/tmp/neovim-20210117-72919-1msimt6/build/include
Compiled by vladimirtkachenko@Vladimirs-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-0f2d37f/share/nvim"

Run :checkhealth for more info
```
- language server name/version:
- Operating system/version:

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: gopls: configuration checked.

</details>

<details>
<summary>lsp.log</summary>

[ INFO ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:311 ]   "Starting RPC client"   {  args = {},  cmd = "gopls",  extra = {}}
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:628 ]  "LSP[gopls]"    "initialize_params"     {  capabilities = {    callHierarchy = {      dynamicRegistratio
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]  "rpc.send.payload"      {  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]  "decoded"       {  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      callHierarchyProvider
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]  "rpc.send.payload"      {  jsonrpc = "2.0",  method = "initialized",  params = {    [true] = 6  }}
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:655 ]  "LSP[gopls]"    "server_capabilities"   {  callHierarchyProvider = true,  codeActionProvider = {    code
[ INFO ] 2021-01-18T00:16:01+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:656 ]   "LSP[gopls]"    "initialized"   {  resolved_capabilities = {    call_hierarchy = true,    code_action =
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]  "rpc.send.payload"      {  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocumen
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]  "decoded"       {  id = 1,  jsonrpc = "2.0",  method = "window/workDoneProgress/create",  params = {
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:502 ]  "server_request"        "window/workDoneProgress/create"        {  token = "5577006791947779410"}
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:505 ]  "server_request: found handler for"     "window/workDoneProgress/create"
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/handlers.lua:394 ]  "default_handler"       "window/workDoneProgress/create"        {  client_id = 1,  params = {    token =
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:500 ]  "server_request: callback result"       {  result = vim.NIL,  status = true}
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]  "rpc.send.payload"      {  id = 1,  jsonrpc = "2.0",  result = vim.NIL}
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]  "decoded"       {  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "5577006791947779410"
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]  "decoded"       {  id = 2,  jsonrpc = "2.0",  method = "workspace/configuration",  params = {    items =
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:488 ]  "notification"  "$/progress"    {  token = "5577006791947779410",  value = {    kind = "begin",    messa
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/handlers.lua:394 ]  "default_handler"       "$/progress"    {  client_id = 1,  params = {    token = "5577006791947779410",
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:502 ]  "server_request"        "workspace/configuration"       {  items = { {      scopeUri = "file:///Users/vl
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:505 ]  "server_request: found handler for"     "workspace/configuration"
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:500 ]  "server_request: callback result"       {  result = { vim.NIL },  status = true}
[ DEBUG ] 2021-01-18T00:16:01+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]  "rpc.send.payload"      {  id = 2,  jsonrpc = "2.0",  result = { vim.NIL }}
[ DEBUG ] 2021-01-18T00:16:02+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]  "decoded"       {  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = "2021/01/18
[ DEBUG ] 2021-01-18T00:16:02+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:488 ]  "notification"  "window/logMessage"     {  message = "2021/01/18 00:16:02 go env for /Users/vladimirtkac
[ DEBUG ] 2021-01-18T00:16:02+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]  "decoded"       {  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = "2021/01/18
[ DEBUG ] 2021-01-18T00:16:02+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:488 ]  "notification"  "window/logMessage"     {  message = "2021/01/18 00:16:02 go/packages.Load\n\tsnapshot=0
[ DEBUG ] 2021-01-18T00:16:02+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]  "decoded"       {  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "5577006791947779410"
[ DEBUG ] 2021-01-18T00:16:02+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:488 ]  "notification"  "$/progress"    {  token = "5577006791947779410",  value = {    kind = "end",    message
[ DEBUG ] 2021-01-18T00:16:02+0600 ] ...HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/handlers.lua:394 ]  "default_handler"       "$/progress"    {  client_id = 1,  params = {    token = "5577006791947779410",
[ DEBUG ] 2021-01-18T00:16:02+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]  "decoded"       {  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnost
[ DEBUG ] 2021-01-18T00:16:02+0600 ] ...r/neovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp.lua:488 ]  "notification"  "textDocument/publishDiagnostics"       {  diagnostics = { {      message = "cannot use
[ DEBUG ] 2021-01-18T00:16:04+0600 ] ...ovim/HEAD-0f2d37f/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]  "rpc.send.payload"      {  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocumen

</details>

### Steps to reproduce using `nvim`

install `neovim/nvim-lspconfig` and put `lua require'lspconfig'.gopls.setup{}` in your `init.vim`
clone [this](https://github.com/unknownspacewalker/nvim-bug-1) repository
open `anotherfile.go`, split window and open `main.go`

### Actual behaviour
There is no virtual text message.

Note: if you move cursor on line 9 error message popup is shown.

### Expected behaviour
There is an error virtual text message on line 9 in `main.go`.

**Comment by mjlbach** [comment]
I'm not able to reproduce this. Upon any insert in the new buffer for main.go, the virtual text shows up.

**Comment by unknownspacewalker** [comment]
@mjlbach Yep, but if I open `mail.go` first, the virtual text appears without any insert, so I expect the same behaviour when I open `main.go` after `anotherfile.go`.

**Comment by mjlbach** [comment]
I'm going to rename the title to reflect the actual problem.

@tjdevries this is what's happening here/how to fix it (I can fix it if we merge my show_buffer_diagnostics PR pretty easily).

lsp.buf_attach_client() is called [here](https://github.com/neovim/nvim-lspconfig/blob/1f88798c0efe9331e83243ce05605fbac0433e9d/lua/lspconfig/configs.lua#L162). By that point, the [diagnostic handler](https://github.com/neovim/neovim/blob/f9b3110549cf7065845c92385e96760376b8c48b/runtime/lua/vim/lsp/diagnostic.lua#L994) has already received the first set of diagnostics for the buffer, and [this](https://github.com/neovim/neovim/blob/f9b3110549cf7065845c92385e96760376b8c48b/runtime/lua/vim/lsp/diagnostic.lua#L836) evals as true, so it doesn't draw(as it has sort-of incorrectly cached diagnostics). This is trivially solved by my PR https://github.com/neovim/neovim/pull/13748 with two additions:

Adding the ability to forcibly draw diagnostics, ignoring the cache
```patch
diff --git a/runtime/lua/vim/lsp/diagnostic.lua b/runtime/lua/vim/lsp/diagnostic.lua
index b30b95685..28c07e910 100644
--- a/runtime/lua/vim/lsp/diagnostic.lua
+++ b/runtime/lua/vim/lsp/diagnostic.lua
@@ -985,9 +985,9 @@ end
 
 --@private
 --- Display diagnostics for the buffer, given a configuration.
-function M.display(diagnostics, bufnr, client_id, config)
+function M.display(diagnostics, bufnr, client_id, config, force)
 
-  if not _bufs_waiting_to_update[bufnr][client_id] then
+  if not _bufs_waiting_to_update[bufnr][client_id] and not force then
     return
   end
 
@@ -1090,7 +1090,7 @@ end
 ---     - underline (boolean, default true): show underline
 ---     - virtual_text (boolean, default true): show virtual_text
 ---@return table {popup_bufnr, win_id}
-function M.show_buffer_diagnostics(bufnr, client_ids, config)
+function M.show_buffer_diagnostics(bufnr, client_ids, config, force)
   config = vim.lsp._with_extend('vim.lsp.diagnostic.on_publish_diagnostics', {
     signs = true,
     underline = true,
@@ -1104,7 +1104,7 @@ function M.show_buffer_diagnostics(bufnr, client_ids, config)
     local client_id = client.id
     if vim.lsp.buf_is_attached(bufnr, client_id) then
       local buffer_diags = M.get(bufnr, client_id)
-      M.display(buffer_diags, bufnr, client_id, config)
+      M.display(buffer_diags, bufnr, client_id, config, force)
     end
   end
 end
```

And two, adding in a forcible draw call after attaching to the buffer in nvim-lspconfig.
```patch
diff --git a/lua/lspconfig/configs.lua b/lua/lspconfig/configs.lua
index ddef845..f45ebfa 100644
--- a/lua/lspconfig/configs.lua
+++ b/lua/lspconfig/configs.lua
@@ -160,6 +160,7 @@ function configs.__newindex(t, config_name, config_def)
       local id = manager.add(root_dir)
       if id then
         lsp.buf_attach_client(0, id)
+        vim.lsp.diagnostic.show_buffer_diagnostics(nil, nil, nil, true)
       end
     end
 ```

**Comment by mjlbach** [comment]
@unknownspacewalker Can you build neovim from master and see if the problem is fixed?

**Comment by mjlbach** [comment]
This was closed (I believe) by https://github.com/neovim/neovim/pull/14184

At least, I can no longer reproduce this :)

**Comment by unknownspacewalker** [comment]
@mjlbach there is still a bug.
Recorded [screencast](https://drive.google.com/file/d/1WcF4F0Im-7vuDWdNkhALiPfgDtlt2IRl/view?usp=sharing).

**Comment by mjlbach** [comment]
I'm not able to repro, the virtual text shows up fine in main.go when I open both files regardless of order. I tried to follow the steps in your video, can you enumerate them?

**Comment by unknownspacewalker** [comment]
@mjlbach sorry, forgot to commit changes. I've just pushed changes. Could u try it again? The main idea here is that neovim does not react to changes that a user made in INSERT mode. But neovim does react to changes that user made in NORMAL mode.

**Comment by mjlbach** [comment]
I did, any change I make it insert mode that introdues a syntax error in one file immediately populates to the other file.

**Comment by unknownspacewalker** [comment]
@mjlbach may I take a look at your configs?

**Comment by mjlbach** [comment]
Yep, I've started using this to test everything now (gopls has to be added):

https://github.com/mjlbach/defaults.nvim

**Comment by unknownspacewalker** [comment]
@mjlbach thanks a lot, I will try to figure out what's wrong with my configs.

**Comment by mjlbach** [comment]
If you find a step by step repo with that let me know! I'd also make sure you're on the latest build/lspconfig.

**Comment by unknownspacewalker** [comment]
@mjlbach before every try I reinstalled neovim HEAD and updated all plugins.

**Comment by unknownspacewalker** [comment]
@mjlbach anyway if I find something I will leave a comment here.

**Comment by unknownspacewalker** [comment]
@mjlbach did you change method name like I did on the screencast? I've just tried your configuration, only added gopls to LSP list, and it behaves exactly the same.

**Comment by mjlbach** [comment]
I have a hard time following what's going on in that screencast. I did try changing a method name and the virtual text seemed fine for me:

https://user-images.githubusercontent.com/13316262/125156469-74359500-e11a-11eb-94a7-7f0a48341fbd.mov

**Comment by unknownspacewalker** [comment]
@mjlbach sorry for such screencast, next time I will try to do everything slowly. On ur video everything looks great. It's pretty weird cuz I used your init file. Where should I look for my problem?  Which versions of neovim and gopls do you use?

**Comment by mjlbach** [comment]
No worries :) It's just late for me and easier for me to follow steps.

I'm on 0.6.1 and the latest neovim (e43dbfd) / lspconfig (e5e06b4)
