### ISSUE TITLE
Feature Request: Tmux-like "zoom"

### ISSUE THREAD

**Issue by LunarLambda** [neovim/neovim#13770]
Tmux has a neat feature where you can temporarily "zoom in" on a pane. This is helpful for say, viewing things like manual pages or focusing on one editor window.

It would be nice if this was possible in Neovim too, as by default, things like `:help` split off into a new window, which is usually too small to comfortably scroll through, but one might not wanna deal with setting up commands for splitting vertically by default, moving things to a separate tab, or closing all other windows.

**Comment by mjlbach** [comment]
Pretty easy to do this with a few lines of vimscript. See vim-maximizer:

https://github.com/szw/vim-maximizer/blob/2e54952fe91e140a2e69f35f22131219fcd9c5f1/plugin/maximizer.vim#L56-L87

Are you saying you think this should be a built-in?

**Comment by LunarLambda** [comment]
I did not know about that plugin, this briefly came up in conversation with a friend asking how to do it. I do think it would be quite nice if it were built-in!

**Comment by bew** [comment]
Not everything should be builtin, although everything should be doable with builtin functions.
Vim is an editor that you can hack, and make it do the things you want, how you want.

Please keep it that way and don't try to push every features you can think of, that's what plugins are for if you don't want to do it yourself.

Here is how I do it: (pretty simple IMO)
https://github.com/bew/dotfiles/blob/2728a5e12a319969b613e3c208fc7e6d2c678778/nvim/mappings.vim#L152-L176

**Comment by teto** [comment]
as others mentioned, let's leave this to plugins.
