### ISSUE TITLE
< (lesser than) cannot be remapped

### ISSUE THREAD

**Issue by Sheepolution** [neovim/neovim#13776]
- `nvim --version`: NVIM v0.4.4
- `vim -u DEFAULTS` (version: 8.2) behaves differently? **Yes!**
- Operating system/version: Windows 10

### Steps to reproduce
Add the following mapping to your `.vimrc`:
```
" Turn >> and << into > and <
nnoremap > >>
nnoremap < <<

" Keep visual when indenting
vnoremap < <gvk
vnoremap > >gvk
```

### Actual behaviour
In normal mode:
`>` indents
`<` does nothing. Only on the second lt (<<) does it unindent.

In visual mode:
`>` indents and stays in visual mode.
`<` unindents, but loses its visual mode.

### Expected behaviour
In normal mode:
`>` indents
`<` unindents

In visual mode:
`>` indents and stays in visual mode.
`<` unindents and stays in visual mode.

### More info
I tried using `<lt>` instead of `<`, but that doesn't work either.

**Comment by glacambre** [comment]
These commands work fine for me on [Neovim nightly](https://github.com/neovim/neovim/releases/tag/nightly) - could you upgrade to that and see if you can still reproduce your problem?

**Comment by Sheepolution** [comment]
@glacambre Ah yes, with the nightly build it works for me as well. Thanks!
