### ISSUE TITLE
nvim_feedkeys/vim.fn.getreg confusing behavior

### ISSUE THREAD

**Issue by levouh** [neovim/neovim#13781]
- `nvim --version`
    - `NVIM v0.5.0-dev+1011-g2ea312769`
- `vim -u DEFAULTS` behaves differently?
    - No
- Operating system/version:
    - _Fedora 32_ with `5.8.18-200` kernel
- Terminal name/version:
    - Not relevant
- `$TERM`
   - Not relevant

### Steps to reproduce

_I'm sure there's a better way to do this, but it gets the example across._

1. Setup an incredibly terse `init.lua`, like so:
```
_G.get_visual_selection = function()
    -- Played with different arguments here; none seem to make a difference as expected
    local keys = vim.fn.nvim_replace_termcodes('"vy', true, false, false)
    vim.fn.nvim_feedkeys(keys, 'n', false)

    vim.cmd('echom "' .. vim.fn.getreg('v') .. '"')
    vim.cmd('echom "' .. vim.fn.eval('@v') .. '"')
end

vim.fn.nvim_set_keymap('v', '<leader>v', '<Cmd>lua _G.get_visual_selection()<CR>', {})
```

2. Run `nvim`, and the configured binding via visually selecting text, then pressing `\v`.
3. Run `:mess` to see the output, and note that the output is always showing the _previously_ selected text, rather than the _currently_ selected text.

### Actual behaviour

The previous contents of the `v` register are output.

### Expected behaviour

This should output the contents of the `v` register as they were _just_ set, however, it does not.

`:h nvim_feedkeys` mentions that it is blocking, but could this be a problem with the setting of registers _not_ being blocking in some manner? If I run the above mapping, and then run something like `:echo @v`, all appears to be good, so presumably waiting long enough gets you what you want, however from code like this, that isn't an option.

**Comment by levouh** [comment]
Messing around with it a bit:

```
_G.get_visual_selection = function()
    vim.fn.feedkeys('"vy')

    vim.cmd('echom "' .. vim.fn.getreg('v') .. '"')
    vim.cmd('echom "' .. vim.fn.eval('@v') .. '"')
```

has the same problem, while:

```
_G.get_visual_selection = function()
    vim.cmd('noau normal! "vy')

    vim.cmd('echom "' .. vim.fn.getreg('v') .. '"')
    vim.cmd('echom "' .. vim.fn.eval('@v') .. '"')
```

does not. I might be missing something; `:h <Cmd>` doesn't reveal much (at least that I understand the nuances of), but it seems like the approach mentioned in the original question _should_ work.

**Comment by zeertzjq** [comment]
I think the "blocking" here means that the API is blocking, not that the keys are blocking. You can try using `'nx'` instead of `'n'`. `'nx'` executes the typeahead.
```
		'x'	Execute commands until typeahead is empty.  This is
			similar to using ":normal!".  You can call feedkeys()
			several times without 'x' and then one time with 'x'
			(possibly with an empty {string}) to execute all the
			typeahead.  Note that when Vim ends in Insert mode it
			will behave as if <Esc> is typed, to avoid getting
			stuck, waiting for a character to be typed before the
			script continues.
```
