### ISSUE TITLE
Minimum signcolumn with auto

### ISSUE THREAD

**Issue by spywhere** [neovim/neovim#13783]
## Rationale
As neovim already have support for showing multiple signs in the sign column through `set signcolumn=auto:<number>` / `set signcolumn=yes:<number>`, I find both of the case a bit too much and too less at the same time for my usage.

Typically, I would like a sign column to always show to accommodate any sign that might be appeared and to not shift the whole text when the sign column start to appear. However, I would also want it to show and expand more
area when it's needed to display more signs.

## Proposal
I would like neovim to have a sign column auto-resizable with a minimum size supported. Something like

```
set signcolumn=min:1
" or
set signcolumn=yes:1,auto
```

Which would always show a sign column for zero or one sign, and will be auto-resize up to the maximum it supported (in this case 9)

To further expanded the use case, it could also support

```
set signcolumn=min:2-5
" or
set signcolumn=yes:2,auto:5
```

Which will always show a sign column for a minimum of 2 signs, and up to 5 signs maximum.

Let me know if something is not clear, or need more info.

**Comment by teto** [comment]
Having the signcolumn jump back and forth between 0 and 1 is indeed annoying I feel your pain. This is reinforced by a bug where the cursor position is not necessarily refreshed (something to look into). A trick can be to set a bunch of manual signs to force a minimal width.
Other than that, I envision the proper syntax more like `set signcolumn=auto:2-3` or `set signcolumn=auto:2,3`

**Comment by spywhere** [comment]
I have successfully build my own version of neovim that support this feature using @teto's suggested syntax.

I can make a PR but I would need help in the review the code and any missing pieces that I might have missed though, beside the tests itself.

Diff: https://github.com/neovim/neovim/compare/master...spywhere:min-size-auto-sign

**Comment by teto** [comment]
Please make a PR, I will review it. Would be nice to update the tests in test/functional/ui/sign_spec.lua

**Comment by spywhere** [comment]
PR opened, let me know if it's need anything 😄
