### ISSUE TITLE
stdpath() returns mixed path separators with shellslash option

### ISSUE THREAD

**Issue by Mike325** [neovim/neovim#13787]
- `nvim --version`:
```
NVIM v0.5.0-dev+1022-g77a6049e0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-129

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? `N/A`
- Operating system/version: `Windows 10`
- Terminal name/version: `Windows terminal 1.4.201119003-release 1.4`
- `$TERM`: `N/A`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:echo stdpath('data')
:set shellslash
:echo stdpath('data')
```

### Actual behaviour
Returns mixed \ and / path string 
`C:\Users\$USER\AppData\Local/nvim-data`

### Expected behaviour
Respect shellslash and get a forwarded slashed path 
`C:/Users/$USER/AppData/Local/nvim-data`

**Comment by matveyt** [comment]
BTW. `exepath()` suffers the same problem. E.g. `:echo exepath('cmd')` prints `C:\Windows\System32/cmd.exe`.

**Comment by worldeva** [comment]
I'm thinking of taking this one if nobody has already-

After some digging, it seems to be that `expand_env_esc()` or anything else that would normally change `\\` to `/` isn't being called, but `psepc`(which is used on windows for `do_concat_fnames()`) is still being changed to `/`, causing the mixed path names.

I'm a new contributor, so I'm not sure what I should do:

Should a function to enforce shellslash be written and used where its currently being done inside the functions doing it (`expand_env_esc()`, `set_bool_option()`,...) (I'm personally in favor of this one because I believe it would improve code readability and reduce the usage of `#ifdef BACKSLASH_IN_FILENAME`) and used inside `exepath()` and `stdpath()`, 

Or should a preexisting function like `expand_env_esc()` be used?

Additionally, is `expand_env_esc()` not being called (which would most likely result in system variables not expanding) expected behavior?

**Comment by mrshu** [comment]
@worldeva I took a quick look at `slash_adjust` (below) but could not figure out what would that one line look like. Would you happen to have any hints?

https://github.com/neovim/neovim/blob/55ad48d93955462905622a42a460ffccd99aa77a/src/nvim/path.c#L1417-L1437

**Comment by zeertzjq** [comment]
`slash_adjust()` should just need to be called somewhere appropriate.

**Comment by mrshu** [comment]
Thanks @zeertzjq, that was indeed helpful!

I was trying to find a common place that would cover both `stdpath` and `exepath` but I was not able to find one. Instead, it seems that calling `slash_adjust()` in the following two places should do the trick:

**`is_executable`** -- perhaps before the `abspath` is being returned:

https://github.com/neovim/neovim/blob/3f8703093de56254ffdbf8ef6ddbe7942af54257/src/nvim/os/fs.c#L285-L288

**`do_concat_fnames`** -- right before `fname1` gets returned:

https://github.com/neovim/neovim/blob/55ad48d93955462905622a42a460ffccd99aa77a/src/nvim/path.c#L399-L402

Would something like this make sense? If so, I'd go ahead and try to implement it.

Also, I would greatly appreciate if you could share what would the preferred way of adding a tests for a change like this look like.

Thanks!

**Comment by 3N4N** [comment]
Leaving this for @mrshu. Remember to check for null pointer.

```c
  if (abspath != NULL) {
    slash_adjust((char_u *) *abspath);
  }
```

**Comment by 3N4N** [comment]
@mrshu tests should be something like this
https://github.com/neovim/neovim/blob/3d45706478cd030c3ee05b4f336164bb96138095/test/functional/vimscript/executable_spec.lua#L11-L18

For example:

```lua
  it('exepath respects shellslash', function()
    command('let $PATH = fnamemodify("./test/functional/fixtures/bin", ":p")')
    eq('test\\functional\\fixtures\\bin\\null.CMD', call('fnamemodify', call('exepath', 'null'), ':.'))
    command('set ssl')
    eq('test/functional/fixtures/bin/null.CMD', call('fnamemodify', call('exepath', 'null'), ':.'))
  end)

  it('stdpath respects shellslash', function()
    eq('build\\Xtest_xdg\\share\\nvim-data', call('fnamemodify', call('stdpath', 'data'), ':.'))
    command('set ssl')
    eq('build/Xtest_xdg/share/nvim-data', call('fnamemodify', call('stdpath', 'data'), ':.'))
  end)
```

**Comment by 3N4N** [comment]
I think I have pulled something up. Both the bugfix and the tests (the tests need to go to proper files, of course).

Lemme know if mrshu does not response back. I will send the PR then.

**Comment by mrshu** [comment]
@3N4N go ahead and fix this -- that will be for the best :slightly_smiling_face:!
