### ISSUE TITLE
update haskell related runtime

### ISSUE THREAD

**Issue by goolord** [neovim/neovim#13797]
the haskell syntax plugin for instance is about 2 years out of date
`" Last Change:		2018 Mar 29 by Marcin Szamotulski`
vs
`" Last Change:		2020 Oct 4 by Marcin Szamotulski <profunctor@pm.me>`
effected files:
```
runtime/syntax/haskell.vim
runtime/ftplugin/haskell.vim
runtime/autoload/haskellcomplete.vim
runtime/syntax/chaskell.vim
runtime/syntax/lhaskell.vim

runtime/syntax/cabal.vim
runtime/syntax/cabalconfig.vim
runtime/syntax/cabalproject.vim
```

i tried making the patch for this myself, but I don't feel confident enough to make this patch since it's probably got its tendrils in other places as well

**Comment by clason** [comment]
For exactly this reason, neovim uses upstream runtime files whenever possible and urges fixes to be applied upstream first. There's usually a big synchronization of runtime from upstream before a release, but 0.5 took longer than planned. Hence tracking runtime files has mostly been piecemeal, whenever somebody had a pressing need for it (as you seem to have now).

You should be fine making a PR just copying the relevant upstream files (noting the last upstream commit for reference) -- but @janlazo may have more precise instructions.

(If you want to make sure, look at the files on Github and select `Blame` -- if all lines reference vim commits, you should be good.)
