### ISSUE TITLE
Copy and Paste: paste text in clipboard with Ctrl+Ins (windows)

### ISSUE THREAD

**Issue by drazde** [neovim/neovim#13791]
Be able to easily paste copied text from another editor into Windows (out of the box)

- `nvim --version`: NVIM v0.5.0-dev-+1023-gea8756f85
- `vim -u DEFAULTS` (version: ) behaves differently?: no
- Operating system/version: Windows 10
- GUI: nvim-qt.exe
- `$TERM`: -

### Steps to reproduce 
1. open `nvim-qt` 
2. go to insert mode 
3. type Ctrl+Ins

### Actual behaviour
Paste the string `<S-Insert>` and not the text copyed 

### Expected behaviour
Paste the text in the clipboard, in every situation (also when search text)

![immagine](https://user-images.githubusercontent.com/2643448/105000913-4440eb00-5a2f-11eb-859d-c7a3bc27ab43.png)

**Comment by jdhao** [comment]
@drazde  I do not think it is a bug of neovim. This issue only occurs in nvim-qt. In fact, I have the following config for nvim-qt in my [`ginit.vim`](https://github.com/jdhao/nvim-config/blob/master/ginit.vim#L2-L3):

```
inoremap <silent> <S-Insert>  <C-R>+
cnoremap <S-Insert> <C-R>+
```

It will do what you want.  You can then use `shift + insert` to paste text in your clipboard to nvim-qt.

See also [this issue](https://github.com/equalsraf/neovim-qt/issues/327).

**Comment by drazde** [comment]
@jdhao I would like use copy and paste (without remap or strange config) also when I search, like with vim

**Comment by jdhao** [comment]
Again, this is an issue with nvim-qt. You would get better answers there.  If you use neovim in a terminal, the above remapping is not needed.

**Comment by drazde** [comment]
@jdhao the same thing happen in `cmd`
![immagine](https://user-images.githubusercontent.com/2643448/105010612-3d6ca500-5a3c-11eb-9474-d128f7142989.png)

**Comment by jdhao** [comment]
I have never used cmd to do my development. No one cares cmd since it is barely usable. Would you? Better use the new windows terminal or cmde.

**Comment by drazde** [comment]
Ok @jdhao 
with 
```
set mouse=a
source $VIMRUNTIME/mswin.vim
```
Config works, thanks
