### ISSUE TITLE
E492 Not an editor command :PlugInstall

### ISSUE THREAD

**Issue by Johan-Palacios** [neovim/neovim#13801]
Tengo un problema al ejecutar los plugins de vim-plug, uso el emulador de ubuntu en windows 10 WLS

Aclarado eso, les explicare mi situación, ejecute el comando correpondiente para instalar vim-plug de neovim y me genero el archivo de plug.vim, entonces trate de instalar unos plugins y me daba el error de "E492 Not an editor command :PlugInstall"

PD: Tengo el archivo init.vim, neovim funciona bien, tengo instalado vim-plug y he utilizado el modo superior para ejecutar nvim, pero no hay respuesta

Quien me pueda dar una solución a mi problema se lo agradecere grandemente

**Comment by vigoux** [comment]
Duplicate of #13800
