### ISSUE TITLE
E492: Not an editor command: PlugInstall

### ISSUE THREAD

**Issue by Johan-Palacios** [neovim/neovim#13800]
Tengo un problema en mi terminal de ubuntu de Windows, instale Neovim, zsh y oh my zsh de manera normal, el inconveniente comenzo al querer instalar plugins en Neovim, ya que al ingresar el comando :PlugInstall, lanza el error E492: Not an editor command: PlugInstall

Las configuraciones estan en

`johan_linux/.config/nvim`

El archivo de los plugins lo cambie de rutas para ver si no era un error mio pero al parecer no ha dado resultado

PD: NVIM lo abri con super usuario 
Si alguien sabe una solución se agradeceria muchisimo 

![Captura](https://user-images.githubusercontent.com/77251405/105097740-bc7ad100-5a6e-11eb-95fc-c0f9efaf1c6d.JPG)
![Captura 2](https://user-images.githubusercontent.com/77251405/105097751-c270b200-5a6e-11eb-845a-2c0c65697769.JPG)
![Captura 3](https://user-images.githubusercontent.com/77251405/105097764-c69ccf80-5a6e-11eb-83bb-bf9c769b3490.JPG)
![Captura 4](https://user-images.githubusercontent.com/77251405/105098166-488cf880-5a6f-11eb-9899-801a1eb0fe56.JPG)

**Comment by mjlbach** [comment]
(Lo siento, hace mucho que no practico mi español) Si todavía no ha instalado vim-plug según, instálelo: 

```
iwr -useb https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim |`
    ni "$(@($env:XDG_DATA_HOME, $env:LOCALAPPDATA)[$null -eq $env:XDG_DATA_HOME])/nvim-data/site/autoload/plug.vim" -Force
```
Necesitará cambiar la ruta a nvim/data:

```
call plug#begin(stdpath('data') . '/plugged')

call plug#end()
```

**Comment by Mike325** [comment]
`:Plug` y `:PlugInstall`  son comandos del plugin Plug, necesitas intalar primero Plug y agregarlo al runtimepath de neovim para poder usar los comandos, si usas neovim dentro de WSL (como se ve en las capturas) puedes seguir las intrucciones de instalacion de linux

```sh
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
```

**Comment by Johan-Palacios** [comment]
Hola a los que respondieron, yo ya tengo el archivo de vim-plug en mi pc, pero por alguna razón no llega a funcionar

**Comment by teto** [comment]
Seems liek a plugin issue rather than a neovim bug, use stackoverflow or a similar website for this. thanks
