### ISSUE TITLE
extmarks: `complete()` function modify extmarks accidentally

### ISSUE THREAD

**Issue by hrsh7th** [neovim/neovim#13816]
- `nvim --version`:
```
NVIM v0.5.0-dev+1041-g1607dd071
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/***/Develop/Repos/neovim/build/config -I/Users/***/Develop/Repos/neovim/src -I/Users/***/Develop/Repos/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/***/Develop/Repos/neovim/build/src/nvim/auto -I/Users/***/Develop/Repos/neovim/build/include
Compiled by ***@***.local

Features: +acl +iconv +tui
See ":help feature-compile"
Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
  - vim has no extmark features.
- Operating system/version:
  - Mac/10.14.6
- Terminal name/version:
  - iTerm2/3.4.3
- `$TERM`:
  - xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC test.vim
:source %
```

<details>
<summary>test.vim</summary>

```
set completeopt=menu,menuone,noselect

inoremap <C-x> <C-r>=<SID>complete()<CR>
function! s:complete() abort
  call complete(2, [{ 'word': '/div_' }])
  return ''
endfunction

vnew
call setline(1, '</d>')

let s:ns = nvim_create_namespace('extmark-test')
call nvim_buf_set_extmark(bufnr('%'), s:ns, 0, 2, {
\   'end_line': 0,
\   'end_col': 3,
\ })

let s:prev_marks = nvim_buf_get_extmarks(bufnr('%'), s:ns, 0, -1, { 'details': v:true })
call feedkeys("1G3|a\<C-x>iv_", 'x')
let s:next_marks = nvim_buf_get_extmarks(bufnr('%'), s:ns, 0, -1, { 'details': v:true })

echomsg string({
\   'prev': s:prev_marks,
\   'next': s:next_marks,
\ })
```

</details>

### Actual behaviour

`{'prev': [[1, 0, 2, {'end_col': 3, 'end_row': 0}]], 'next': [[1, 0, 6, {'end_col': 1, 'end_row': 0}]]}`

I think the `next end_col` is modified to `pum start position` accidentally.

### Expected behaviour

`{'prev': [[1, 0, 2, {'end_col': 3, 'end_row': 0}]], 'next': [[1, 0, 6, {'end_col': 2, 'end_row': 0}]]}`

**Comment by runiq** [comment]
Repro in Lua:

1. Save this as test.lua:

    ```lua
    -- ABBBBCCCC
    local ns = vim.api.nvim_create_namespace('random_namespace_name')
    local em = vim.api.nvim_buf_set_extmark(0, ns, 0, 4, {
    	end_col = 8,
    	hl_group = 'WarningMsg',
    	right_gravity = false,
    	end_right_gravity = true,
    })
    print(vim.inspect(em))
    ```

2. `nvim -u NONE test.lua`
3. `:luafile %`
4. Enter insert mode somewhere in the `BBBB` region, press ^P or ^X^L

Some observations on behavior:

The buggy behavior depends on gravity:

- With default gravity, the beginning of the extmark range shifts towards the cursor. - With inverted gravity (i.e. as shown in the repro), the beginning of the extmark range shifts towards the beginning of the line instead.
- With inverted gravity, *how far* the extmark shifts depends on which completion function I invoke, and how many times:

    1\. The first ^P or ^X^L extends the extmark to the beginning of the line
    2a. Undoing, then entering insert mode and pressing ^P again extends the extmark to the beginning of the *word*
    2b. Undoing, then entering insert mode and pressing ^X^L extends the extmark up to the beginning of the *line*

Here's a video showing the behavior:

https://user-images.githubusercontent.com/620981/110463784-a4204d80-80d2-11eb-964c-74ba2ad1629b.mp4

1. I first press ^X^L, which extends to the beginning of the line
2. I undo and press ^P, which extends to the beginning of the word
3. I undo and press ^X^L, which extends to the beginning of the line again.

**Comment by bfredl** [comment]
Currently we consider the entire completed text to be replaced, which i think is reasonable in general but gets weird with some completions like c-xc-l which regards the entire line until cursor as replaced (visible with multiple matches in the pum)

**Comment by runiq** [comment]
I see, makes sense—but shouldn't that happen only after/when the user confirms a completion and not as soon as `complete()` is invoked?

**Comment by hrsh7th** [comment]
I found this problem in the following use-case.

I was trying to implement LSP's linkedEditingRange that feature is useful when editing HTML tag.
For example, If the line is `<div></div>`, the `linkedEditingRange` will be synchronize first and second `div` editing.

1. `<div|></div>`
2. `<di|></di>`
3. `<|></|>`
4. `<span|></span>`

It almost works fine in current extmarks. It really awesome.

But I noticed. If we edit the closing tag name, it will be wrong results because some completion engine suggests `/div` as completed text.

I think if someone implements `snippet's placeholder synchronization` with extmark, it will be occurred too.

_Sorry for my poor English. I respect to @bfredl_

**Comment by runiq** [comment]
> I think if someone implements `snippet's placeholder synchronization` with extmark, it will be occurred too.

That would be exactly my use-case, yeah :)

**Comment by bfredl** [comment]
@runiq unfortunately complete() has a bug with no select (prior to extmarks)

**Comment by runiq** [comment]
Which one? I found some bugs w/noselect, but nothing I was able to relate back to this :(

**Comment by bfredl** [comment]
The bug that it selects the first item even when noselect is set?

**Comment by hrsh7th** [comment]
I'm thinking now this is spec of nvim. I don't think this is bug now. closing.
