### ISSUE TITLE
Substitute in Visual mode is also replacing characters outside selected region

### ISSUE THREAD

**Issue by duikboot** [neovim/neovim#13811]
- `nvim --version`: v0.5.0-dev+1040-gd68026c9e
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: 5.10.7-3-MANJARO #1 SMP PREEMPT Fri Jan 15 21:11:34 UTC 2021 x86_64 GNU/Linux
- Terminal name/version: alacritty  0.7.1 (a852eb85)
- `$TERM`: alacritty

### Steps to reproduce using `nvim -u NORC`

I am in visual mode and want to replace a's with b's. but only in the selected region. 
`:'<,'>s/a/b/g`
All the occurrences of `a`, not only the a's in the selected region, are substituted on the line.

### Actual behaviour
Every occurrence of the character on the line is substituted

### Expected behaviour
Every occurrence of the character, but only in the selected region, is substituted

**Comment by clason** [comment]
See https://vi.stackexchange.com/a/13192/

(A new `s_flag` (`v`?) to simplify this might be a useful addition, but should probably be added upstream first, if possible.)

**Comment by clason** [comment]
For upstream discussion, see
https://github.com/vim/vim/issues/1448
https://github.com/vim/vim/issues/4272
https://github.com/vim/vim/issues/3292

**Comment by duikboot** [comment]
Thank you @clason , I don't know why I think it always worked that way before. Sorry for the inconvenience.
