### ISSUE TITLE
Autoformat and smartindent gives unwanted indent

### ISSUE THREAD

**Issue by fwSmit** [neovim/neovim#13814]
- `nvim --version`: NVIM v0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Arch linux
- Terminal name/version: gnome-terminal 3.38.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

create file with the contents: foo
```
if aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
Note, the a's are only to get enough characters. The `if` is neccesary. `aa` doesn't work.
```
nvim -u NORC foo
:set smartindent
gqq
```

### Actual behaviour
```
if
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

### Expected behaviour
```
if
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

This seems to be pretty specific about what text is auto-formatted, but I come across this bug quite often.

**Comment by matveyt** [comment]
This is expected, as `smartindent` respects `cinwords` including `if` by default. Just do not `set smartindent` for plain text files. It's not for them.

**Comment by fwSmit** [comment]
Ah makes sense. I somehow didn't think of that.
