### ISSUE TITLE
LSP: importing a (react) tag does not request for correct code actions

### ISSUE THREAD

**Issue by lucax88x** [neovim/neovim#13817]
- `nvim --version`: v0.5.0-dev+1037-gd6d4e3d1a
- language server name/version: typescript-language-version@latest
- Operating system/version: archlinux@latest

### Steps to reproduce using `nvim -u NORC`

Try to import a react component using tags like

<img width="324" alt="transcomponent" src="https://user-images.githubusercontent.com/6294464/105493822-2c30cc00-5cba-11eb-9ba6-0e2ea8751811.png">

will prompt for wrong imports

<img width="381" alt="transcomponentimports" src="https://user-images.githubusercontent.com/6294464/105493850-3783f780-5cba-11eb-90d0-a957d4a3150f.png">

instead if I try to import as a class / type / function like

<img width="245" alt="2021-01-22_14-00" src="https://user-images.githubusercontent.com/6294464/105493902-49fe3100-5cba-11eb-9259-6df7cab79182.png">

it will works correctly

<img width="446" alt="2021-01-22_14-00_1" src="https://user-images.githubusercontent.com/6294464/105493938-53879900-5cba-11eb-9898-b4b11e085e6b.png">

[REPRODUCIBLE REPOSITORY](https://github.com/lucax88x/repro-neovim)

Go to test1.tsx and try to import inside tags, does not work.
If you import in simple code like Test2, it will work.

Now go to App.tsx, try to import inside tags, it will work.

### Actual behaviour

Asks for wrong imports

### Expected behaviour

Should prompt correct imports

<summary>nvim -c ":checkhealth nvim lspconfig"</summary>
<details>
#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
    - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
      - INFO: $COLORTERM='truecolor'

      health#lspconfig#check
      ========================================================================
## Checking language server protocol configuration
        - INFO: tsserver: configuration checked.
          - INFO: diagnosticls: configuration checked.
            - INFO: bashls: configuration checked.
              - INFO: html: configuration checked.
                - INFO: yamlls: configuration checked.
                  - INFO: jsonls: configuration checked.
                    - INFO: sumneko_lua: configuration checked.
                      - INFO: cssls: configuration checked.

</details>

<summary>lsp.log</summary>

<details>
[ DEBUG ] 2021-01-22T13:50:23+0100 ] ...nt_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  id = 2,  jsonrpc = "2.0",  result = { {      children = { {          children = {},          detail = "",          kind = 14,          name = "createdWhen",          range = {            end = {              character = 66,              line = 39            },            start = {              character = 55,              line = 39            }          },          selectionRange = {            end = {              character = 66,              line = 39            },            start = {              character = 55,              line = 39            }          }        }, {          children = {},          detail = "",          kind = 14,          name = "feedback",          range = {            end = {              character = 18,              line = 38            },            start = {              character = 10,              line = 38            }          },          selectionRange = {            end = {              character = 18,              line = 38            },            start = {              character = 10,              line = 38            }          }        }, {          children = {},          detail = "",          kind = 14,          name = "fromPerson",          range = {            end = {              character = 20,              line = 39            },            start = {              character = 10,              line = 39            }          },          selectionRange = {            end = {              character = 20,              line = 39            },            start = {              character = 10,              line = 39            }          }        }, {          children = {},          detail = "",          kind = 14,          name = "location",          range = {            end = {              character = 53,              line = 39            },            start = {              character = 45,              line = 39            }          },          selectionRange = {            end = {              character = 53,              line = 39            },            start = {              character = 45,              line = 39            }          }        }, {          children = {},          detail = "",          kind = 14,          name = "styled",          range = {            end = {              character = 39,              line = 37            },            start = {              character = 8,              line = 37            }          },          selectionRange = {            end = {              character = 14,              line = 37            },            start = {              character = 8,              line = 37            }          }        }, {          children = {},          detail = "",          kind = 14,          name = "text",          range = {            end = {              character = 36,              line = 39            },            start = {              character = 32,              line = 39            }          },          selectionRange = {            end = {              character = 36,              line = 39            },            start = {              character = 32,              line = 39            }          }        }, {          children = {},          detail = "",          kind = 14,          name = "title",          range = {            end = {              character = 43,              line = 39            },            start = {              character = 38,              line = 39            }          },          selectionRange = {            end = {              character = 43,              line = 39            },            start = {              character = 38,              line = 39            }          }        }, {          children = {},          detail = "",          kind = 14,          name = "toPerson",          range = {            end = {              character = 30,              line = 39            },            start = {              character = 22,              line = 39            }          },          selectionRange = {            end = {              character = 30,              line = 39            },            start = {              character = 22,              line = 39            }          }        } },      detail = "",      kind = 14,      name = "FeedbackCard",      range = {        end = {          character = 1,          line = 64        },        start = {          character = 13,          line = 36        }      },      selectionRange = {        end = {          character = 25,          line = 36        },        start = {          character = 13,          line = 36        }      }    }, {      children = { {          children = {},          detail = "",          kind = 7,          name = "feedback",          range = {            end = {              character = 31,              line = 33            },            start = {              character = 2,              line = 33            }          },          selectionRange = {            end = {              character = 10,              line = 33            },            start = {              character = 2,              line = 33            }          }        } },      detail = "",      kind = 11,      name = "FeedbackCardProps",      range = {        end = {          character = 1,          line = 34        },        start = {          character = 0,          line = 32        }      },      selectionRange = {        end = {          character = 27,          line = 32        },        start = {          character = 10,          line = 32        }      }    }, {      children = { {          children = { {              children = {},              detail = "",              kind = 7,              name = "display",              range = {                end = {                  character = 19,                  line = 14                },                start = {                  character = 4,                  line = 14                }              },              selectionRange = {                end = {                  character = 11,                  line = 14                },                start = {                  character = 4,                  line = 14                }              }            }, {              children = {},              detail = "",              kind = 7,              name = "gridAutoFlow",              range = {                end = {                  character = 26,                  line = 15                },                start = {                  character = 4,                  line = 15                }              },              selectionRange = {                end = {                  character = 16,                  line = 15                },                start = {                  character = 4,                  line = 15                }              }            }, {              children = {},              detail = "",              kind = 7,              name = "gridGap",              range = {                end = {                  character = 29,                  line = 17                },                start = {                  character = 4,                  line = 17                }              },              selectionRange = {                end = {                  character = 11,                  line = 17                },                start = {                  character = 4,                  line = 17                }              }            } },          detail = "",          kind = 7,          name = "exchange",          range = {            end = {              character = 3,              line = 18            },            start = {              character = 2,              line = 13            }          },          selectionRange = {            end = {              character = 10,              line = 13            },            start = {              character = 2,              line = 13            }          }        }, {          children = {},          detail = "",          kind = 7,          name = "feedback",          range = {            end = {              character = 14,              line = 20            },            start = {              character = 2,              line = 20            }          },          selectionRange = {            end = {              character = 10,              line = 20            },            start = {              character = 2,              line = 20            }          }        }, {          children = {},          detail = "",          kind = 7,          name = "location",          range = {            end = {              character = 14,              line = 25            },            start = {              character = 2,              line = 25            }          },          selectionRange = {            end = {              character = 10,              line = 25            },            start = {              character = 2,              line = 25            }          }        }, {          children = { {              children = {},              detail = "",              kind = 7,              name = "fill",              range = {                end = {                  character = 32,                  line = 28                },                start = {                  character = 4,                  line = 28                }              },              selectionRange = {                end = {                  character = 8,                  line = 28                },                start = {                  character = 4,                  line = 28                }              }            }, {              children = {},              detail = "",              kind = 7,              name = "height",              range = {                end = {                  character = 28,                  line = 27                },                start = {                  character = 4,                  line = 27                }              },              selectionRange = {                end = {                  character = 10,                  line = 27                },                start = {                  character = 4,                  line = 27                }              }            } },          detail = "",          kind = 7,          name = "playIcon",          range = {            end = {              character = 3,              line = 29            },            start = {              character = 2,              line = 26            }          },          selectionRange = {            end = {              character = 10,              line = 26            },            start = {              character = 2,              line = 26            }          }        }, {          children = { {              children = {},              detail = "",              kind = 7,              name = "<unknown>",              range = {                end = {                  character = 26,                  line = 9                },                start = {                  character = 4,                  line = 9                }              },              selectionRange = {                end = {                  character = 26,                  line = 9                },                start = {                  character = 4,                  line = 9                }              }            }, {              children = {},              detail = "",              kind = 7,              name = "display",              range = {                end = {                  character = 19,                  line = 10                },                start = {                  character = 4,                  line = 10                }              },              selectionRange = {                end = {                  character = 11,                  line = 10                },                start = {                  character = 4,                  line = 10                }              }            }, {              children = {},              detail = "",              kind = 7,              name = "gridGap",              range = {                end = {                  character = 29,                  line = 11                },                start = {                  character = 4,                  line = 11                }              },              selectionRange = {                end = {                  character = 11,                  line = 11                },                start = {                  character = 4,                  line = 11                }              }            } },          detail = "",          kind = 7,          name = "root",          range = {            end = {              character = 3,              line = 12            },            start = {              character = 2,              line = 8            }          },          selectionRange = {            end = {              character = 6,              line = 8            },            start = {              character = 2,              line = 8            }          }        }, {          children = {},          detail = "",          kind = 7,          name = "text",          range = {            end = {              character = 10,              line = 24            },            start = {              character = 2,              line = 24            }          },          selectionRange = {            end = {              character = 6,              line = 24            },            start = {              character = 2,              line = 24            }          }        }, {          children = { {              children = {},              detail = "",              kind = 7,              name = "fontWeight",              range = {                end = {                  character = 31,                  line = 22                },                start = {                  character = 4,                  line = 22                }              },              selectionRange = {                end = {                  character = 14,                  line = 22                },                start = {                  character = 4,                  line = 22                }              }            } },          detail = "",          kind = 7,          name = "title",          range = {            end = {              character = 3,              line = 23            },            start = {              character = 2,              line = 21            }          },          selectionRange = {            end = {              character = 7,              line = 21            },            start = {              character = 2,              line = 21            }          }        }, {          children = {},          detail = "",          kind = 7,          name = "toPerson",          range = {            end = {              character = 14,              line = 19            },            start = {              character = 2,              line = 19            }          },          selectionRange = {            end = {              character = 10,              line = 19            },            start = {              character = 2,              line = 19            }          }        } },      detail = "",      kind = 14,      name = "styles",      range = {        end = {          character = 2,          line = 30        },        start = {          character = 6,          line = 7        }      },      selectionRange = {        end = {          character = 12,          line = 7        },        start = {          character = 6,          line = 7        }      }    } }}
[ DEBUG ] 2021-01-22T13:50:24+0100 ] ...nt_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"  }}
[ DEBUG ] 2021-01-22T13:50:24+0100 ] ....mount_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp.lua:497 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"}
[ DEBUG ] 2021-01-22T13:50:24+0100 ] ...nt_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        message = "Expected an assignment or function call and instead saw an expression. [no-unused-expressions]",        range = {          end = {            character = 5,            line = 41          },          start = {            character = 0,            line = 41          }        },        severity = 1,        source = "eslint"      }, {        message = "Empty components are self-closing [react/self-closing-comp]",        range = {          end = {            character = 15,            line = 46          },          start = {            character = 8,            line = 46          }        },        severity = 1,        source = "eslint"      }, {        message = "'Trans' is not defined. [react/jsx-no-undef]",        range = {          end = {            character = 14,            line = 46          },          start = {            character = 9,            line = 46          }        },        severity = 1,        source = "eslint"      } },    uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"  }}
[ DEBUG ] 2021-01-22T13:50:24+0100 ] ....mount_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp.lua:497 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = { {      message = "Expected an assignment or function call and instead saw an expression. [no-unused-expressions]",      range = {        end = {          character = 5,          line = 41        },        start = {          character = 0,          line = 41        }      },      severity = 1,      source = "eslint"    }, {      message = "Empty components are self-closing [react/self-closing-comp]",      range = {        end = {          character = 15,          line = 46        },        start = {          character = 8,          line = 46        }      },      severity = 1,      source = "eslint"    }, {      message = "'Trans' is not defined. [react/jsx-no-undef]",      range = {        end = {          character = 14,          line = 46        },        start = {          character = 9,          line = 46        }      },      severity = 1,      source = "eslint"    } },  uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"}
[ DEBUG ] 2021-01-22T13:50:24+0100 ] ...nt_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = 2304,        message = "Cannot find name 'Trans'.",        range = {          end = {            character = 7,            line = 41          },          start = {            character = 2,            line = 41          }        },        severity = 1,        source = "typescript"      }, {        code = 2304,        message = "Cannot find name 'Trans'.",        range = {          end = {            character = 14,            line = 46          },          start = {            character = 9,            line = 46          }        },        severity = 1,        source = "typescript"      }, {        code = 2304,        message = "Cannot find name 'Trans'.",        range = {          end = {            character = 22,            line = 46          },          start = {            character = 17,            line = 46          }        },        severity = 1,        source = "typescript"      } },    uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"  }}
[ DEBUG ] 2021-01-22T13:50:24+0100 ] ....mount_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp.lua:497 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = { {      code = 2304,      message = "Cannot find name 'Trans'.",      range = {        end = {          character = 7,          line = 41        },        start = {          character = 2,          line = 41        }      },      severity = 1,      source = "typescript"    }, {      code = 2304,      message = "Cannot find name 'Trans'.",      range = {        end = {          character = 14,          line = 46        },        start = {          character = 9,          line = 46        }      },      severity = 1,      source = "typescript"    }, {      code = 2304,      message = "Cannot find name 'Trans'.",      range = {        end = {          character = 22,          line = 46        },        start = {          character = 17,          line = 46        }      },      severity = 1,      source = "typescript"    } },  uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"}
[ DEBUG ] 2021-01-22T13:50:24+0100 ] ...nt_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        message = "Expected an assignment or function call and instead saw an expression. [no-unused-expressions]",        range = {          end = {            character = 7,            line = 41          },          start = {            character = 2,            line = 41          }        },        severity = 1,        source = "eslint"      }, {        message = "Empty components are self-closing [react/self-closing-comp]",        range = {          end = {            character = 15,            line = 46          },          start = {            character = 8,            line = 46          }        },        severity = 1,        source = "eslint"      }, {        message = "'Trans' is not defined. [react/jsx-no-undef]",        range = {          end = {            character = 14,            line = 46          },          start = {            character = 9,            line = 46          }        },        severity = 1,        source = "eslint"      } },    uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"  }}
[ DEBUG ] 2021-01-22T13:50:24+0100 ] ....mount_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp.lua:497 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = { {      message = "Expected an assignment or function call and instead saw an expression. [no-unused-expressions]",      range = {        end = {          character = 7,          line = 41        },        start = {          character = 2,          line = 41        }      },      severity = 1,      source = "eslint"    }, {      message = "Empty components are self-closing [react/self-closing-comp]",      range = {        end = {          character = 15,          line = 46        },        start = {          character = 8,          line = 46        }      },      severity = 1,      source = "eslint"    }, {      message = "'Trans' is not defined. [react/jsx-no-undef]",      range = {        end = {          character = 14,          line = 46        },        start = {          character = 9,          line = 46        }      },      severity = 1,      source = "eslint"    } },  uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"}
[ DEBUG ] 2021-01-22T13:50:33+0100 ] ....mount_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp.lua:709 ]	"LSP[tsserver]"	"client.request"	1	"textDocument/codeAction"	{  context = {    diagnostics = { {        code = 2304,        message = "Cannot find name 'Trans'.",        range = {          end = {            character = 14,            line = 46          },          start = {            character = 9,            line = 46          }        },        severity = 1,        source = "typescript"      }, {        code = 2304,        message = "Cannot find name 'Trans'.",        range = {          end = {            character = 22,            line = 46          },          start = {            character = 17,            line = 46          }        },        severity = 1,        source = "typescript"      }, {        message = "Empty components are self-closing [react/self-closing-comp]",        range = {          end = {            character = 15,            line = 46          },          start = {            character = 8,            line = 46          }        },        severity = 1,        source = "eslint"      }, {        message = "'Trans' is not defined. [react/jsx-no-undef]",        range = {          end = {            character = 14,            line = 46          },          start = {            character = 9,            line = 46          }        },        severity = 1,        source = "eslint"      } }  },  range = {    end = <1>{      character = 9,      line = 46    },    start = <table 1>  },  textDocument = {    uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"  }}	<function 1>	3
[ DEBUG ] 2021-01-22T13:50:33+0100 ] ...nt_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  id = 3,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = { {          code = 2304,          message = "Cannot find name 'Trans'.",          range = {            end = {              character = 14,              line = 46            },            start = {              character = 9,              line = 46            }          },          severity = 1,          source = "typescript"        }, {          code = 2304,          message = "Cannot find name 'Trans'.",          range = {            end = {              character = 22,              line = 46            },            start = {              character = 17,              line = 46            }          },          severity = 1,          source = "typescript"        }, {          message = "Empty components are self-closing [react/self-closing-comp]",          range = {            end = {              character = 15,              line = 46            },            start = {              character = 8,              line = 46            }          },          severity = 1,          source = "eslint"        }, {          message = "'Trans' is not defined. [react/jsx-no-undef]",          range = {            end = {              character = 14,              line = 46            },            start = {              character = 9,              line = 46            }          },          severity = 1,          source = "eslint"        } }    },    range = {      end = <1>{        character = 9,        line = 46      },      start = <table 1>    },    textDocument = {      uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"    }  }}
[ DEBUG ] 2021-01-22T13:50:33+0100 ] ...nt_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  id = 3,  jsonrpc = "2.0",  result = { {      arguments = { {          documentChanges = { {              edits = { {                  newText = "import React from 'react';\n",                  range = {                    end = {                      character = 0,                      line = 6                    },                    start = {                      character = 0,                      line = 6                    }                  }                } },              textDocument = {                uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx",                version = 10              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Import default 'React' from module \"react\""    }, {      arguments = { {          documentChanges = { {              edits = { {                  newText = "import React from 'react';\n",                  range = {                    end = {                      character = 0,                      line = 6                    },                    start = {                      character = 0,                      line = 6                    }                  }                } },              textDocument = {                uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx",                version = 10              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Import default 'React' from module \"react\""    } }}
[ DEBUG ] 2021-01-22T13:50:36+0100 ] ....mount_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp.lua:709 ]	"LSP[tsserver]"	"client.request"	1	"textDocument/codeAction"	{  context = {    diagnostics = { {        code = 2304,        message = "Cannot find name 'Trans'.",        range = {          end = {            character = 7,            line = 41          },          start = {            character = 2,            line = 41          }        },        severity = 1,        source = "typescript"      }, {        message = "Expected an assignment or function call and instead saw an expression. [no-unused-expressions]",        range = {          end = {            character = 7,            line = 41          },          start = {            character = 2,            line = 41          }        },        severity = 1,        source = "eslint"      } }  },  range = {    end = <1>{      character = 5,      line = 41    },    start = <table 1>  },  textDocument = {    uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"  }}	<function 1>	3
[ DEBUG ] 2021-01-22T13:50:36+0100 ] ...nt_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  id = 4,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = { {          code = 2304,          message = "Cannot find name 'Trans'.",          range = {            end = {              character = 7,              line = 41            },            start = {              character = 2,              line = 41            }          },          severity = 1,          source = "typescript"        }, {          message = "Expected an assignment or function call and instead saw an expression. [no-unused-expressions]",          range = {            end = {              character = 7,              line = 41            },            start = {              character = 2,              line = 41            }          },          severity = 1,          source = "eslint"        } }    },    range = {      end = <1>{        character = 5,        line = 41      },      start = <table 1>    },    textDocument = {      uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"    }  }}
[ DEBUG ] 2021-01-22T13:50:36+0100 ] ...nt_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  id = 4,  jsonrpc = "2.0",  result = { {      arguments = { {          documentChanges = { {              edits = { {                  newText = "import { Trans } from '@lingui/react';\n",                  range = {                    end = {                      character = 0,                      line = 6                    },                    start = {                      character = 0,                      line = 6                    }                  }                } },              textDocument = {                uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx",                version = 10              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Import 'Trans' from module \"@lingui/react\""    }, {      arguments = { {          documentChanges = { {              edits = { {                  newText = "import { Trans } from '@lingui/react/cjs/Trans';\n",                  range = {                    end = {                      character = 0,                      line = 6                    },                    start = {                      character = 0,                      line = 6                    }                  }                } },              textDocument = {                uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx",                version = 10              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Import 'Trans' from module \"@lingui/react/cjs/Trans\""    }, {      arguments = { {          documentChanges = { {              edits = { {                  newText = "import { Trans } from '@lingui/macro';\n",                  range = {                    end = {                      character = 0,                      line = 6                    },                    start = {                      character = 0,                      line = 6                    }                  }                } },              textDocument = {                uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx",                version = 10              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Import 'Trans' from module \"@lingui/macro\""    } }}

[ INFO ] 2021-01-22T13:53:48+0100 ] ....mount_nvimMbHkXk/usr/share/nvim/runtime/lua/vim/lsp.lua:1016 ]	"exit_handler"	{}

[ INFO ] 2021-01-22T13:54:13+0100 ] ....mount_nvim5uEspZ/usr/share/nvim/runtime/lua/vim/lsp.lua:1016 ]	"exit_handler"	{}
[ DEBUG ] 2021-01-22T13:55:04+0100 ] ....mount_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp.lua:709 ]	"LSP[tsserver]"	"client.request"	1	"textDocument/codeAction"	{  context = {    diagnostics = { {        code = 2304,        message = "Cannot find name 'Trans'.",        range = {          end = {            character = 7,            line = 41          },          start = {            character = 2,            line = 41          }        },        severity = 1,        source = "typescript"      }, {        message = "Expected an assignment or function call and instead saw an expression. [no-unused-expressions]",        range = {          end = {            character = 7,            line = 41          },          start = {            character = 2,            line = 41          }        },        severity = 1,        source = "eslint"      } }  },  range = {    end = {      character = 7,      line = 41    },    start = {      character = 0,      line = 41    }  },  textDocument = {    uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"  }}	<function 1>	3
[ DEBUG ] 2021-01-22T13:55:04+0100 ] ...nt_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  id = 5,  jsonrpc = "2.0",  method = "textDocument/codeAction",  params = {    context = {      diagnostics = { {          code = 2304,          message = "Cannot find name 'Trans'.",          range = {            end = {              character = 7,              line = 41            },            start = {              character = 2,              line = 41            }          },          severity = 1,          source = "typescript"        }, {          message = "Expected an assignment or function call and instead saw an expression. [no-unused-expressions]",          range = {            end = {              character = 7,              line = 41            },            start = {              character = 2,              line = 41            }          },          severity = 1,          source = "eslint"        } }    },    range = {      end = {        character = 7,        line = 41      },      start = {        character = 0,        line = 41      }    },    textDocument = {      uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx"    }  }}
[ DEBUG ] 2021-01-22T13:55:05+0100 ] ...nt_nvimqSs91a/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  id = 5,  jsonrpc = "2.0",  result = { {      arguments = { {          documentChanges = { {              edits = { {                  newText = "import { Trans } from '@lingui/react';\n",                  range = {                    end = {                      character = 0,                      line = 6                    },                    start = {                      character = 0,                      line = 6                    }                  }                } },              textDocument = {                uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx",                version = 10              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Import 'Trans' from module \"@lingui/react\""    }, {      arguments = { {          documentChanges = { {              edits = { {                  newText = "import { Trans } from '@lingui/react/cjs/Trans';\n",                  range = {                    end = {                      character = 0,                      line = 6                    },                    start = {                      character = 0,                      line = 6                    }                  }                } },              textDocument = {                uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx",                version = 10              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Import 'Trans' from module \"@lingui/react/cjs/Trans\""    }, {      arguments = { {          documentChanges = { {              edits = { {                  newText = "import { Trans } from '@lingui/macro';\n",                  range = {                    end = {                      character = 0,                      line = 6                    },                    start = {                      character = 0,                      line = 6                    }                  }                } },              textDocument = {                uri = "file:///home/lucatrazzi/repos/playfeedback/src/playfeedback.app/features/feedback/FeedbackCard.tsx",                version = 10              }            } }        } },      command = "_typescript.applyWorkspaceEdit",      title = "Import 'Trans' from module \"@lingui/macro\""    } }}

</details>

**Comment by hood** [comment]
Don't quote me on that, but that could be a LSP issue. I've had the same (annoying) issue happen to me every time on VSCode.

**Comment by glepnir** [comment]
can you post a min react code that can reproduce this issue ? i test in a react file .works fine.

**Comment by lucax88x** [comment]
***tsx
export const test = () => {
  Trans
  return <><Trans/></>;
};
***

https://user-images.githubusercontent.com/6294464/106894332-1c1fe000-66ef-11eb-8d76-be5dec79507a.mp4

**Comment by glepnir** [comment]
https://user-images.githubusercontent.com/41671631/106894846-70948100-672a-11eb-9869-7ec33914dc2a.mov

**Comment by glepnir** [comment]
@lucax88x  like this?

https://user-images.githubusercontent.com/41671631/106895147-d54fdb80-672a-11eb-8222-f9b8bcbfb45a.mov

**Comment by lucax88x** [comment]
It should NOT ask to import react, but Trans.

Maybe the issue was not clear?

**Comment by lucax88x** [comment]
Instead of Trans, you can just try another private component in another file, in my example Trans comes from another project.

**Comment by glepnir** [comment]
Aha Ok I got this. I know what you mean.

**Comment by lucax88x** [comment]
Mm.. how? which language-server are you using?

**Comment by glepnir** [comment]
typescript-language-server

**Comment by glepnir** [comment]
can you check the vim. lsp. buf. code_action() . because I found that you not use the default request call back handler.  if this works fine. should not the? upstream problem

**Comment by lucax88x** [comment]
Yeah, I already tried with the default handler, it has the same issue.

Still, I noticed that there are some tsx where the import works, and some others where import does not work, I cannot find a common cause about that.

I am confused.

![issue](https://user-images.githubusercontent.com/6294464/106907744-e08d1200-66fe-11eb-8f80-601dd430e0aa.png)
![no-issue](https://user-images.githubusercontent.com/6294464/106907739-dff47b80-66fe-11eb-95e2-9e9a509e84f6.png)

**Comment by glepnir** [comment]
can you check lspsaga？I test the default behavior tomorrow

**Comment by lucax88x** [comment]
I already tried with your code-action from lsp-saga, but for some reason it gives me 

..site/pack/packer/start/lspsaga.nvim/lua/lspsaga/libs.lua:60: Expected table, got nil

**Comment by glepnir** [comment]
aha I. will fixed it tomorrow. but I need some code snippets that can reproducr this issue then It will help me to found what happen with buf. code_action.

**Comment by glepnir** [comment]
> ..site/pack/packer/start/lspsaga.nvim/lua/lspsaga/libs.lua:60: Expected table, got nil

@lucax88x check this. I found that server does not return a response. so this issue seems like an issue of typescropt-language-server?

**Comment by lucax88x** [comment]
I already was using some features of  lspsaga . They were working and now they're broken all with same error.

I will create a issue in the specific repository, let's keep this issue clean l.

Later I will try to create a smaller repository to reproduce the issue.

**Comment by glepnir** [comment]
Okay

**Comment by lucax88x** [comment]
@glepnir Added reproducible repository in the first issue.

[repo](https://github.com/lucax88x/repro-neovim)

Go to test1.tsx and try to import <Test2/> inside tags, does not work.
If you import in simple code like Test2, it will work.

Now go to App.tsx, try to import <Test2/> inside tags,  it will work.

**Comment by glepnir** [comment]
Okay got it .test it later.

**Comment by glepnir** [comment]
check the server the response. seems like bug of language server. 
```
{ {
    result = {}
  } }
{ {
    result = { {
        arguments = { {
            documentChanges = { {
                edits = { {
                    newText = 'import React from "react";\n\n',
                    range = {
                      end = {
                        character = 0,
                        line = 0
                      },
                      start = {
                        character = 0,
                        line = 0
                      }
                    }
                  } },
                textDocument = {
                  uri = "file:///Users/bitcoder/workstation/vim/repro-neovim/src/test1.tsx",
                  version = 0
                }
              } }
          } },
        command = "_typescript.applyWorkspaceEdit",
        title = "Import default 'React' from module \"react\""
      }, {
        arguments = { {
            documentChanges = { {
                edits = { {
                    newText = "Test1",
                    range = {
                      end = {
                        character = 10,
                        line = 4
                      },
                      start = {
                        character = 5,
                        line = 4
                      }
                    }
                  } },
                textDocument = {
                  uri = "file:///Users/bitcoder/workstation/vim/repro-neovim/src/test1.tsx",
                  version = 0
                }
              } }
                  version = 0
                }
              } }
          } },
        command = "_typescript.applyWorkspaceEdit",
```

**Comment by mjlbach** [comment]
This seems like an upstream typescript-language-server bug. Has it been reported? I don't see what our client is doing wrong.

**Comment by glepnir** [comment]
yep should be problem of typescript-language-server.

**Comment by mjlbach** [comment]
Great, feel free to reopen @lucax88x if you find anything we need to do in core.
