### ISSUE TITLE
map dd "_dd makes Neovim/Vim freeze

### ISSUE THREAD

**Issue by iio7** [neovim/neovim#13810]
This problem persists on both Neovim 0.4.4 and Vim 8.2. I have tested on Arch Linux 5.10.8 and Ubuntu Bionic.

- `vim -u DEFAULTS` (version: ) behaves differently?

Yes, the problem is gone using `vim -u DEFAULTS`. And the problem is also gone using `nvim -u NORC`

I have tested this on latest release of both xterm and st.

Mapping both `d` and `dd` to the black hole with:

```
map d "_d
map dd "_dd
```

Pressing "dd" to delete a line causes both Vim and Neovim to freeze and use 100% CPU.

This works:

```
noremap d "_d
noremap dd "_dd
```

AFAIK "map" and "noremap" are identical.

**Comment by iio7** [comment]
I have also filed this upstream: https://github.com/vim/vim/issues/7716

**Comment by jdhao** [comment]
this is not true. `map` is not identical to `noremap`. It will cause recursive mapping, which will freeze Vim. This is what happens exactly. Why not search before you even file an issue?

**Comment by iio7** [comment]
Sorry, I had completely misunderstood the "Overview of which map command works in which mode" in the help, as synonyms!
