### ISSUE TITLE
highlight nvim_echo api in `:messages`

### ISSUE THREAD

**Issue by notomo** [neovim/neovim#13812]
This issue follows up https://github.com/neovim/neovim/pull/13673#discussion_r555446290 .

`:messages` doesn't support multiple highlights in one entry.
nvim_echo api needs it.

**Comment by notomo** [comment]
I plan the following change for now.

```diff
diff --git a/src/nvim/message.h b/src/nvim/message.h
index 377c725fa..1d595e114 100644
--- a/src/nvim/message.h
+++ b/src/nvim/message.h
@@ -87,9 +87,8 @@ typedef kvec_t(HlMessageChunk) HlMessage;
 /// Message history for `:messages`
 typedef struct msg_hist {
   struct msg_hist *next;  ///< Next message.
-  char_u *msg;            ///< Message text.
+  HlMessage *msg;         ///< Message text.
   const char *kind;     ///< Message kind (for msg_ext)
-  int attr;               ///< Message highlighting.
   bool multiline;         ///< Multiline message.
 } MessageHistoryEntry;
 
```

**Comment by Tastyep** [comment]
Hello,

I'm looking forward to seeing this change applied as it's a [limitation](https://github.com/Tastyep/structlog.nvim/issues/1) for [structlog](https://github.com/Tastyep/structlog.nvim).
Is something blocking or is this just not a priority ?

Thank you for your work.

**Comment by justinmk** [comment]
nothing blocking it, needs human attention and design.

**Comment by RaafatTurki** [comment]
did something change? not even a single highlight is shown in `:message` now
`:lua vim.api.nvim_echo({{ "hi friend", "Error" }}, true, {})`

https://asciinema.org/a/ntjXdpVWOLqAy90rsBkROZ39M

**Comment by wookayin** [comment]
@RaafatTurki Nothing has been changed recently and to my knowledge this *bug* has been present from the beginning when nvim_echo was introduced.
