### ISSUE TITLE
LSP completion: "Error executing vim.schedule lua callback: error converting argument 2", probably due to `vim.NIL` conversion logic

### ISSUE THREAD

**Issue by Kazy** [neovim/neovim#13829]
- `nvim --version`:
```
NVIM v0.5.0-dev+1050-g78f0f00cd
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/akear/.cache/yay/neovim-git/src/build/config -I/home/akear/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/akear/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/akear/.cache/yay/neovim-git/src/build/include
Compiled by akear@nocsik-fixe

Features: +acl +iconv +tui
```
- `vim -u DEFAULTS` (version: ) behaves differently? 
- Operating system/version: Archlinux, kernel 5.10.9-zen1-1-zen
- Terminal name/version: Kitty 0.19.3
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Not really possible with `-u NORC`, it requires `nvim-lua/completion-nvim` and `neovim/nvim-lspconfig` plugins.

LSP configuration:
```lua
local on_attach = function(_, _)
  require'completion'.on_attach()
end

nvim_lsp.purescriptls.setup{
  on_attach=on_attach;
}
```

It also requires setting up a Purescript server and opening a `.purs` file:
```bash
npm install -g spago purescript purescript-language-server
# In a new folder
spago init
nvim src/Main.purs
```

Then go to the line that says `  log "🍝"`, delete the line, and start typing `log` again. The bug should manifest itself.

### Actual behaviour

We get the following error at each keypress when trying to complete the current word, and no completion menu shows up:
```
E5100: Cannot convert given lua table: table should either have a sequence of positive integer keys or contain only string keys
Error executing vim.schedule lua callback: error converting argument 2
```

### Expected behaviour

Completion should behave normally.

### Additional informations

I've tried to debug it and traced it back to the following response from the server:

<details>
<summary>Log from log.lsp</summary>

`[ DEBUG ] 2021-01-26T18:26:55+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]  "decoded"       {  id = 4,  jsonrpc = "2.0",  result = {    isIncomplete = false,    items = { {        additionalTextEdits = vim.NIL,        command = {          arguments = { "log", "Effect.Class.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          command = "purescript.addCompletionImport",          title = "Add completion import"        },        detail = "∀ m. MonadEffect m ⇒ String → m Unit",        documentation = {          kind = "markdown",          value = "\n*From: Effect.Class.Console*"        },        filterText = vim.NIL,        insertText = "log",        kind = 3,        label = "log",        sortText = "Z.log",        textEdit = {          newText = "log",          range = {            end = {              character = 4,              line = 9            },            start = {              character = 2,              line = 9            }          }        }      }, {        additionalTextEdits = vim.NIL,        command = {          arguments = { "logShow", "Effect.Class.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          command = "purescript.addCompletionImport",          title = "Add completion import"        },        detail = "∀ m a. MonadEffect m ⇒ Show a ⇒ a → m Unit",        documentation = {          kind = "markdown",          value = "\n*From: Effect.Class.Console*"        },        filterText = vim.NIL,        insertText = "logShow",        kind = 3,        label = "logShow",        sortText = "Z.logShow",        textEdit = {          newText = "logShow",          range = {            end = {              character = 4,              line = 9            },            start = {              character = 2,              line = 9            }          }        }      }, {        additionalTextEdits = vim.NIL,        command = {          arguments = { "log", "Effect.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          command = "purescript.addCompletionImport",          title = "Add completion import"        },        detail = "String → Effect Unit",        documentation = {          kind = "markdown",          value = "\n*From: Effect.Console*"        },        filterText = vim.NIL,        insertText = "log",        kind = 3,        label = "log",        sortText = "Z.log",        textEdit = {          newText = "log",          range = {            end = {              character = 4,              line = 9            },            start = {              character = 2,              line = 9            }          }        }      }, {        additionalTextEdits = vim.NIL,        command = {          arguments = { "logShow", "Effect.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          command = "purescript.addCompletionImport",          title = "Add completion import"        },        detail = "∀ a. Show a ⇒ a → Effect Unit",        documentation = {          kind = "markdown",          value = "\n*From: Effect.Console*"        },        filterText = vim.NIL,        insertText = "logShow",        kind = 3,        label = "logShow",        sortText = "Z.logShow",        textEdit = {          newText = "logShow",          range = {            end = {              character = 4,              line = 9            },            start = {              character = 2,              line = 9            }          }        }      } }  }}
`

which once formatted gets us the following structure:
```
{  
  id = 4,  
  jsonrpc = "2.0",  
  result = {    
    isIncomplete = false,    
    items = { 
      {        
        additionalTextEdits = vim.NIL,        
        command = {          
          arguments = { "log", "Effect.Class.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          
          command = "purescript.addCompletionImport",          
          title = "Add completion import"        
        },        
        detail = "∀ m. MonadEffect m ⇒ String → m Unit",        
        documentation = {          
          kind = "markdown",          
          value = "\n*From: Effect.Class.Console*"        
        },        
        filterText = vim.NIL,        
        insertText = "log",        
        kind = 3,        
        label = "log",        
        sortText = "Z.log",        
        textEdit = {          
          newText = "log",          
          range = {            
            end = {              
              character = 4,              
              line = 9            
            },            
            start = {              
              character = 2,              
              line = 9            
            }          
          }        
        }      
      }, {        
        additionalTextEdits = vim.NIL,        
        command = {          
          arguments = { "logShow", "Effect.Class.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          
          command = "purescript.addCompletionImport",          
          title = "Add completion import"        
        },        
        detail = "∀ m a. MonadEffect m ⇒ Show a ⇒ a → m Unit",        
        documentation = {          
          kind = "markdown",          
          value = "\n*From: Effect.Class.Console*"        
        },        
        filterText = vim.NIL,        
        insertText = "logShow",        
        kind = 3,        
        label = "logShow",        
        sortText = "Z.logShow",        
        textEdit = {          
          newText = "logShow",          
          range = {            
            end = {              
              character = 4,              
              line = 9            
            },            
            start = {              
              character = 2,              
              line = 9            
            }          
          }        
        }      
      }, {        
        additionalTextEdits = vim.NIL,        
        command = {          
          arguments = { "log", "Effect.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          
          command = "purescript.addCompletionImport",          
          title = "Add completion import"        
        },        
        detail = "String → Effect Unit",        
        documentation = {          
          kind = "markdown",          
          value = "\n*From: Effect.Console*"        
        },        
        filterText = vim.NIL,        
        insertText = "log",        
        kind = 3,        
        label = "log",        
        sortText = "Z.log",        
        textEdit = {          
          newText = "log",          
          range = {            
            end = {              
              character = 4,              
              line = 9            
            },            
            start = {              
              character = 2,              
              line = 9            
            }          
          }        
        }      
      }, {        
        additionalTextEdits = vim.NIL,        
        command = {          
          arguments = { "logShow", "Effect.Console", vim.NIL, "file:///tmp/ps-foo/src/Main.purs", "NSValue" },          
          command = "purescript.addCompletionImport",          
          title = "Add completion import"        
        },        
        detail = "∀ a. Show a ⇒ a → Effect Unit",        
        documentation = {          
          kind = "markdown",          
          value = "\n*From: Effect.Console*"        
        },        
        filterText = vim.NIL,        
        insertText = "logShow",        
        kind = 3,        
        label = "logShow",        
        sortText = "Z.logShow",        
        textEdit = {          
          newText = "logShow",          
          range = {            
            end = {              
              character = 4,              
              line = 9            
            },            
            start = {              
              character = 2,              
              line = 9            
            }          
          }        
        }      
      } 
    }  
  }}

```

</details>

In the response, `result.items[i].command.arguments[3]` contains a `vim.NIL` which will be converted to a Lua `nil` in `handle_body` from `rpc.lua` (line 522). I suspect this is the issue because:
- Commenting line 522 `decoded.result = convert_NIL(decoded.result)` fixes the issue (but you get an other one down the line, so not a proper fix obviously).
- Inserting line 556 the following piece of code (before the `try_call`), which replaces the `vim.NIL` values by empty strings, fixes the issue:
```lua
if decoded.result and decoded.result.items then
  for i, table in ipairs(decoded.result.items) 
    if decoded.result.items[i] ~= nil then
      decoded.result.items[i].command.arguments[3] = ""
    end
  end
end
```

I'm not sure if the problem comes from `purescript-language-server` returning a `null` value in the middle of an array, or from the `vim.NIL` conversion logic.

Let me know if you need more information.

**Comment by gasacchi** [comment]
any progress on this?

**Comment by mjlbach** [comment]
Can you reproduce without completion-nvim? It hasn't been updated in awhile and I would recommend https://github.com/hrsh7th/nvim-compe

**Comment by Kazy** [comment]
@mjlbach I moved to `nvim-compe` as well since and the issue still exists.

I had a hacky-fix for it that wasn't specific on the Purescript Language Server anymore. It was replacing the `tbl_map` function used in `recursive_convert_NIL` from `rpc.lua` by one that checks if what we're mapping over is an array, and if so doesn't replace values with `nil` but keeps `vim.NIL`.

```lua
-- from http://ericjmritz.name/2014/02/26/lua-is_array/
function is_array(t)
    local i = 0
    for _ in pairs(t) do
        i = i + 1
        if t[i] == nil then return false end
    end
    return true
end

local function tbl_map_NIL(func, t)
  vim.validate{func={func, 'c'}, t={t, 't'}}

  local rettab = {}
  local table_is_array = is_array(t)
  for k, v in pairs(t) do
    local new_value = func(v)
    if new_value == nil and table_is_array then
      rettab[k] = vim.NIL
    else
      rettab[k] = new_value
    end
  end
  return rettab
end
```

**Comment by mjlbach** [comment]
I see, has this been reported upstream to purescript's language server?

**Comment by Kazy** [comment]
No it hasn't. I decided to report it here instead because it seems the other clients don't suffer from this issue, and because the response from the Purescript LS doesn't seem to deviate [from the specification](https://microsoft.github.io/language-server-protocol/specification#command) as `arguments` is an array of `any`. It just depends if `any` can includes `null` or not. But here to me it seems the issue is with Lua/Neovim itself and how we're transforming `vim.NIL` into `nil` in an array.

Do you think I should open an issue there first and that the issue lies in the client ?

**Comment by mfussenegger** [comment]
I think you're right that `null` is allowed within `any[]`, but it's strange that the conversion from `vim.NIL` to `nil` causes an error. Do you know where exactly in the completion plugin the error occurs? It would have to be a place where the `command` property of the completion item is used?


We could consider adapting the `recursive_convert_NIL` method to skip arrays, (there is already a `vim.tbl_islist` to check for that), but it could also break other places, so I think we should first figure out why having a `nil` in the `command` arguments is causing an issue.

**Comment by Kazy** [comment]
> Do you know where exactly in the completion plugin the error occurs? It would have to be a place where the command property of the completion item is used?

Not from the top of my head, but I'll look into it when I have more time.

Something that might help in the meantime: I just noticed the issue is also happening with an other server, `metals` for Scala. The language server is configured using [`nvim-metals`](https://github.com/scalameta/nvim-metals) but the bug doesn't rely on it. Having LSP configured in Neovim + `nvim-metals` + `sbt` installed:
- Execute `sbt new scala/scala-seed.g8`.
- Open `Hello.scala` (import the build when `nvim-metals` asks you to).
- Add this code:
  ```scala
  case class Foo(bar: Bar)
  ```
- The `Bar` should be an error. Put your cursor on it, and run: `:lua vim.lsp.buf.code_action()`.
- You should be prompted to `Create new symbol 'Bar'...`
- When accepted, we get the following error:
```
E5100: Cannot convert given lua table: table should either have a sequence of positive integer keys or contain only string keys
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:394: error converting argument 1
```

**Comment by mfussenegger** [comment]
Minimal reproduction:

```lua
function M.foo()
  local json = [[{"x": ["foo", null, "bar"]}]]
  local decoded = vim.fn.json_decode(json)
  local convert_nil
  convert_nil = function(v)
    if v == vim.NIL then
      return nil
    elseif type(v) == 'table' then
      return vim.tbl_map(convert_nil, v)
    end
    return v
  end
  return vim.fn.json_encode(convert_nil(decoded))
end
```

Not sure what's the best option to fix this. Maybe preserving `vim.NIL` in arrays is the way to go after all.

**Comment by nghialm269** [comment]
Some of [dartls](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md)'s code actions also suffer from this bug.

For example (`vim.NIL` is at the end of the `arguments` table):

```lua
{      arguments = { "EXTRACT_LOCAL_VARIABLE", "/home/nghialm/learn/flutter/test_app/lib/main.dart", 0, 3889, 93, vim.NIL },      command = "refactor.perform",      title = "Extract Local Variable"    }
```
After calling `convert_NIL`, `nil` disappears:

```lua
{        arguments = { "EXTRACT_LOCAL_VARIABLE", "/home/nghialm/learn/flutter/test_app/lib/main.dart", 0, 3889, 93 },        command = "refactor.perform",        title = "Extract Local Variable"      }
```

It seems like it is due to lua trimming `nil` in table: https://stackoverflow.com/questions/51852969/nil-as-an-element-in-a-lua-table

**Comment by mjlbach** [comment]
PR welcome that changes the nil handling to use vim.NIL, otherwise I'll try to get to this but it might not be in time for 0.5
