### ISSUE TITLE
Built in basic editor "plugins"

### ISSUE THREAD

**Issue by kristijanhusak** [neovim/neovim#13822]
I wasn't able to find related issue to this. If there is any, feel free to mark this as duplicate and point to it.

My question is: are there any plans to add some built in support for standard editor plugins, like for example:
* auto pairs
* commenting
* something else that I can't think of at this moment

All text editors out there have this built in (VSCode, Sublime Text, etc.). You open up a file and it just works, no configuration needed. I think it would be neat to have it also in neovim. 
Commenting is generally something that always looked like half done to me. We have `commentstring` but no way to use it by default.
I'm aware that there are a lot of plugins that provides this functionality, which would also make the implementation a lot easier since there is no reinventing the wheel.

**Comment by teto** [comment]
commenting is sthg that core could offer an option for.
As for the rest vim already provides a plugin system (especially with `packadd` and all) so anyone can easily build on top of vim (look at spacevim) or the other ui (https://github.com/onivim/oni). What we can do better is enforce some structure for plugin to expose their options (as we do in https://github.com/neovim/neovim/blob/master/src/nvim/options.lua and is leveraged b telescope.nvim).

**Comment by kristijanhusak** [comment]
Fair enough. I'll let you decide what to do with this ticket. If we have tracking of commenting somewhere, this can be closed I guess.

**Comment by teto** [comment]
The rise of lua plugins should make more things possible but this will take time. This is all fairly new (0.5 is not even released yet :'( ) so this may take some time. thanks for sponsoring nvim !
