### ISSUE TITLE
Visual area matcher \%V changes meaning during a substitution

### ISSUE THREAD

**Issue by rminehan** [neovim/neovim#13838]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Ubuntu 18.04.5 LTS and Macos Big Sur
- Terminal name/version: Standard default ubuntu gnome terminal and default macos terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Create a buffer like:

```
aaaaa
aaaaa
aaaaa
```

Create a jagged visual character selection: put your cursor on the 3rd 'a' on line 1, press `v`, then `jj` to extend it down, so that it looks like:

```
aa***
*****
***aa
```

(where `*` represents visually selected 'a's)

Press escape or `v` to return to normal mode - now `gv` represents the `*` pattern above and should control the behavior of `\%V` in a search.

Do `:%s/\%V\_w*\%V\_w/b` that is:

- substitute across the whole buffer
- the match must begin in the visually selected area (see `help /\%V`)
- match 0 or more wordy characters or newlines (see `help /\_w` - it just means `\w` or newline)
- the match must end in the visually selected area (hence adding one more `\_w` just after `\%V` as per the help page)
- replace with a single `b`

In other words replace all blocks of one or more `\_w` characters inside the last visual selection.

### Actual behaviour

After the substitution runs, you end up with:

```
aabb
```

The two 'b's indicate two replacements have taken place.

### Expected behaviour

All the visually selected 'a's should get replaced in one go leaving:

```
aabaa
```

The first two 'a's are from the part of the top line _before_ the original visual selection.

The 'b' represents the previous character visual selection.

The last two 'a' are from the part of the bottom line _after_ the original visual selection.

### Theory

My theory is that the matching and substituting are interleaved, meaning that characters which didn't originally fall inside the last visual selection (`gv`) are later falling into the last visual selection as the text before them shrinks. This is what I think is happening:

The regex engine correctly identifies the block `*` characters above as a match and replaces them with `b` meaning that the buffer now looks like:

```
aabaa
```

The "last visual selection" represented by `gv` shrunk by one line but because it's jagged, it still runs to the end of the line above and would go to column 3 on the next line if that line exists. `gv` would look something like:

```
aa***
   ^ start next match
```

This means that the trailing "aa" originally from line 3 now also falls within the "last visual selection". The regex engine looks for another match starting on that same "aa" and finds one as they are now considered "visually selected" (even though they weren't originally). They get replaced with a 'b' giving the final result "aabb".

### Root cause

Assuming my theory is correct, I think the root issue here is how jagged visual selections update when text from them is removed.

When inner lines get removed, the way it updates makes sense for a substitution. For example,

```
aa***
*****  <--- delete this
***aa
```

`gv` now gives:

```
aa***
***aa
```

But if you delete the 3 characters at the beginning of the last line though using `x`, the visual selection will still try to run to column 3.

So it updates correctly (with respect to substitution) in some cases but not others and leads to quirky behavior. I've written more details about this [here](https://github.com/rminehan/vim-kata/blob/main/dangers_of_visual_mode.md#deep-dive---hunting-a-most-peculiar-bug).

### Bug?

Regular vim has the same behavior and the docs for `\%V` don't explicitly address this case so I'm not sure if it's technically a "bug" - it certainly wasn't what I expected though. I always imagined that substitute used two passes like `global` does where the first pass determined all the matches, then the second pass did the substitutions.

I guess it comes down to whether the interleaving approach that substitute uses is supposed to be an internal implementation detail, or part of the spec and users are supposed to understand that the buffer will change mid-substitute.

Without using a 2 pass approach I think this bug will be very hard to fix as you'd need some ad-hoc logic to keep track of where characters originally were before the substitution started, and somehow map that back to the current state of the buffer.

An interleaved substitution might cause other subtle bugs for other `\%...` context atoms like `\%#` (cursor position), and `\%c` (column position) and `\%l` (line position), so switching to a two pass substitute might fix up some other edge cases, but I understand it would be a lot of work and might cause compatibility issues elsewhere.

**Comment by chrisbra** [comment]
can you please submit this to github.com/vim/vim? Thanks

**Comment by rminehan** [comment]
Reposted to [vim](https://github.com/vim/vim/issues/7846) as requested and closing this.
