### ISSUE TITLE
matchparen.vim doesn't escape some character before passing them to searchpairpos()

### ISSUE THREAD

**Issue by Vftdan** [neovim/neovim#13831]
https://github.com/neovim/neovim/blob/4d1fc167a8a14067a848719a1d6c772edce6e11f/runtime/plugin/matchparen.vim#L88

Only case for square brackets is handled properly, however languages may have exotic parenthesis.

## Steps to reproduce
 * Execute `:setlocal matchpairs+=\\:.`
 * Insert `\  .`

## Expected behaviour
Backslash and dot are highlighted as matching parenthesis.

## Actual behaviour
Backslash and the next character are highlighted when the cursor is on the backslash, nothing is highlighted when the cursor is on the dot.

## Possible solution
Replace the referenced lines with

``` vim
  let c = escape(c, '.\[]^$~*')
  let c2 = escape(c2, '.\[]^$~*')
```

**Comment by Vftdan** [comment]
matchit.vim also doesn't seem to work properly with this example.

**Comment by chrisbra** [comment]
this looks like a contrived example, but I guess fixing this won't hurt. Please create a PR for matchparen at https://github.com/vim/vim
and for matchit at https://github.com/chrisbra/matchit/

Thanks.

**Comment by dundargoc** [comment]
Hi! Thank you for your contribution. Unfortunately I'll need to close this down as this is an issue involving the `runtime` directory, which [vim](https://github.com/vim/vim) is responsible for. Even if we fix this there's a risk the change will be reverted the next time the runtime directory is updated. I encourage you to report this to them instead: that way any fix they make will shortly be incorporated here as well :+1: .
