### ISSUE TITLE
Node on Windows not recognized - some js.-plugins work nonetheless, others not

### ISSUE THREAD

**Issue by the42** [neovim/neovim#13839]
- `nvim --version`: NVIM v0.5.0-dev+1051-g4d1fc167a
- `vim -u DEFAULTS` (version: ) behaves differently? Yes, but still error
- Operating system/version: Windows 10 German
- Terminal name/version: cmd, powershell and Windows terminal all behave the same
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`
Run :checkhealth

Fist, it does not complete. After hitting CTRL-C the output is:
```
health#mkdp#check
========================================================================
  - INFO: Platform: win
  - INFO: Nvim Version: Das unbekannte Element "" wurde empfangen. Dieser Fall kann eintreten, wenn der Remotevorgang nicht ordnungsgem<84><e1> geschlossen oder beendet wurde.
  - INFO: Node version: Das unbekannte Element "" wurde empfangen. Dieser Fall kann eintreten, wenn der Remotevorgang nicht ordnungsgem<84><e1> geschlossen oder beendet wurde.

  - INFO: Script: C:\Users\HoechtlJ\AppData\Local\nvim\pack\plugins\start\markdown-preview.nvim-master/app/server.js
  - INFO: Script exists: 1
  - OK: Using node

health#nvim#check
========================================================================
```

and in the section
```
health#provider#check
========================================================================

## Node.js provider (optional)
  - ERROR: Command timed out: node -v
 ```

node is in path and at version `node -v` v14.15.4

**Comment by the42** [comment]
Also note the encoding issues of the error message of health#mkdp#check

**Comment by the42** [comment]
Issue was that my shell was set to powershell. After getting escape settings for this shell correct, everything works as expected.

**Comment by mattia72** [comment]
> Issue was that my shell was set to powershell. After getting escape settings for this shell correct, everything works as expected.

Could you tell us, how to do that?

**Comment by the42** [comment]
As per the documentation: `:help shell-powershell`
