### ISSUE TITLE
Capital 'V' letter in regex `%V` seems to trigger smartcase in very magic mode

### ISSUE THREAD

**Issue by rminehan** [neovim/neovim#13837]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: 8.0.1453) behaves differently? No
- Operating system/version: Ubuntu 18.04.5 LTS and Macos Big Sur
- Terminal name/version: Standard default ubuntu gnome terminal and default macos terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Create a buffer with text like:

```
abc
ABC
Abc
```

Do `:set ignorecase smartcase`.

Visually select the text and hit escape (so that it's the most recently selected text with respect to `gv`)

Do a search: `/\v%Vabc` (ie search for text "abc" starting in the last visually selected area - see `:help /\%V`)

### Actual behaviour

It only finds the "abc" (ie. it matches case sensitively).

### Expected behaviour

It should find 3 matches: "abc", "ABC" and "Abc".

Based on my understanding: the search term `abc` is lowercase and ignorecase is on, meaning the search should be case insensitive. `smartcase` _shouldn't_ switch the search to be case sensitive as there's no literal uppercase letter in the pattern.

### Notes

I think that the capital 'V' in `%V` is causing the `smartcase` setting to change the search to be case sensitive. When I turn off `smartcase` and rerun the test I get all 3 matches.

If you do the equivalent search without the "very magic" flag and escape the `%V` instead (ie. `/\%Vabc`) it finds 3 matches, so I'm guessing there's logic inside smartcase for handling capital letters when they're part of an explicit `\` escape sequence (but not when unescaped).

The help for smartcase doesn't explicitly say whether "capital letters" are just for literal capital letters but I'm pretty sure that was the intention, particularly as that's how it works when an escaped `\%V` is used. So I'm fairly confident it's a bug as smartcase shouldn't be affected by whether you're using very magic or regular magic mode.

Regular vim behaves the same as neovim, that is it yields all 3 matches when using `\%V` but only one match when using `\v%V`. If this _is_ the intended behavior it would be helpful to make that clear in the help docs for smartcase as it has implications for very magic mode: you have to explicitly put a `\c` in your pattern if you want it to ignore case.

**Comment by chrisbra** [comment]
can you please submit this to github.com/vim/vim? Thanks

**Comment by rminehan** [comment]
Posted this to vim's issues as requesed [here](https://github.com/vim/vim/issues/7845).

Will close this.
