### ISSUE TITLE
nvim_input_mouse("left", "release", "A", …) leaves insert mode

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#13846]
- `nvim --version`: NVIM v0.5.0-dev+1053-g459a6c845

### Steps to reproduce using `nvim -u NORC`

Using any gui (reproduced with Firenvim and Goneovim), enter insert mode and click somewhere while pressing `Alt`.

### Actual behaviour
Neovim leaves insert mode.

### Expected behaviour
Neovim stays in insert mode. This is the behavior Neovim has in v0.4.4. I'll try to bisect when I have time.

**Comment by glacambre** [comment]
Change introduced in 2f06413dfb3624381f112b7d8661fde659c279e7 by @godlygeek.

In my opinion this change is very wrong. If a key isn't mapped, it shouldn't have any effect. Having all alt/meta keys result in leaving the current mode serves no purpose and worse: people might start relying on `<A-WHATEVER>` to leave the current mode, which means that when neovim makes `<A-WHATEVER>` a default to, say, call `DoWhatever()`, people's workflow will break.

This change is also buggy as it makes `<A-LeftMouse>` leave insert mode even if something is bound to it with `:inoremap <A-LeftMouse> ...`.

I think there is still time to revert this as v0.5 hasn't been released yet. What do the maintainers think?

**Comment by bfredl** [comment]
hmm I thought neovim went all in on ALT being distinct from ESC? The _reverse_ of  2f06413 seems more logical to be, sequence should be autotranslated in _no_ mode by default. Possibly it could be an opt-in option, if enough users want/depend on it.

**Comment by godlygeek** [comment]
Hm. The rationale for the change is simple: when running in a terminal, NeoVim uses timing based heuristics to guess whether a byte sequence like `0x1b 0x78` means `<Esc>x` or `<M-x>`, so when I press the keys too quickly then instead of exiting visual mode and deleting the character under the cursor, instead nothing happens if an unbound `<M-x>` does nothing.

As far as quality of life goes, I found this problem immediately after trying to switch from vim to nvim, and it was incredibly frustrating that sometimes it would just eat my keypresses with no effect. And no amount of fiddling with the timings used by tmux and by NeoVim got it to the point where it could consistently detect function keys without mistaking `<Esc>x` for `<M-x>`. I almost gave up on NeoVim before I tried patching this.

If there is no such timing based ambiguity when a GUI is in use, perhaps this should only apply when no GUI is in use? Or perhaps an option could be introduced that disables meta detection entirely?

**Comment by godlygeek** [comment]
Or, of course, the bug causing it to think that `<A-LeftClick>` is unbound when it isn't could be tracked down and fixed.

**Comment by bfredl** [comment]
> As far as quality of life goes, I found this problem immediately after trying to switch from vim to nvim, and it was incredibly frustrating that sometimes it would just eat my keypresses with no effect. And no amount of fiddling with the timings used by tmux and by NeoVim got it to the point where it could consistently detect function keys without mistaking <Esc>x for <M-x>. I almost gave up on NeoVim before I tried patching this.

> If there is no such timing based ambiguity when a GUI is in use, perhaps this should only apply when no GUI is in use? Or perhaps an option could be introduced that disables meta detection entirely?

Well yes this was the intention of my idea. The behavior for _new_ configs should be to disable all automagic, but users too used to the vim behavior (or finding themselves over a broken remote connection or something) could opt-in to ESC conversion.

**Comment by godlygeek** [comment]
> The behavior for _new_ configs should be to disable all automagic

> but users ... could opt-in to ESC conversion.

Which behavior are you calling "automagic"? Because from my point of view, the behavior that unconditionally and deterministically treats `0x1b 0x78` as `<Esc>x` has nothing automagic about it, whereas treating it conditionally as either `<Esc>x` or <M-x>` depending on timing is the automagic one.

**Comment by bfredl** [comment]
The "magic" part is changing key processing depending on if there is a mapping or not in a non-standard way. So while it is deterministic for your usecase it is definitely not "unconditional". it affects UI:s (and terminals using a better alt representation or wrapped ESC mode or something) in an unexpected way for _those_ usecases.

> whereas treating it conditionally as either <Esc>x or <M-x> depending on timing is the automagic one.

Well if this is needed that depends on how your terminal emulator represents these keys. if timing is the only way a terminal emulator allows to signal the difference, it is quite too late for neovim to do anything else than detect it by timing (also vim does this for _other_ esc-baseds mapping if you set 'ttimeout', so this behaviour is hardly unique for neovim)

**Comment by godlygeek** [comment]
> if timing is the only way a terminal emulator allows to signal the difference, it is quite too late for neovim to do anything else than detect it by timing (also vim does this for _other_ esc-baseds mapping if you set 'ttimeout', so this behaviour is hardly unique for neovim)

Fair enough, but given that many (all?) terminal emulators default to sending both `<Esc>` and `<A-x>` as 0x1b 0x78, the NeoVim 0.4.4 behavior was that `<A-x>` mappings always worked, but pressing `<Esc>x` sometimes didn't. I'd strongly prefer that `<Esc>x` always works, even if that means that `<A-x>` never does, and I doubt I'm alone in that. I could live with that being an option I need to set, though.

> terminals using a better alt representation or wrapped ESC mode or something

Last I tried this was 10 years ago, but most applications at the time didn't support it well - it caused more trouble than it solved. Perhaps I should look into it again.

**Comment by glacambre** [comment]
>when I press the keys too quickly then instead of exiting visual mode and deleting the character under the cursor, instead nothing happens if an unbound <M-x> does nothing

Ah, I understand the problem better now, so the patch isn't all that wrong after all. Sorry for the strong words @godlygeek!

**Comment by glacambre** [comment]
An issue related to godlygeek's is described in https://github.com/neovim/neovim/issues/13086 .

**Comment by justinmk** [comment]
does https://github.com/neovim/neovim/pull/13109 fix this?

**Comment by glacambre** [comment]
@justinmk Nope, doesn't look like it.
