### ISSUE TITLE
Flickering commands while moving, un-/redoing with 'showcmd' option

### ISSUE THREAD

**Issue by maxthyron** [neovim/neovim#13841]
- `nvim --version`: v0.4.4
- `vim -u DEFAULTS` (version: 8.1; patches:  1-503, 505-680, 682-2292) behaves differently? : Yes(after turning showcmd on)
- Operating system/version: MacOS Catalina 10.15.7
- Terminal name/version: iTerm2 Build 3.4.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

Create some space for movement(newlines - for vertical; text lines - for horizontal):

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaa




aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa






```
Start moving with h, j, k, l.

### Actual behaviour

Flickering 'h', 'j', 'k', 'l' start showing up. This appears in the start of the long press, after rapid movement direction change(e.g. switching from 'j' to 'k' or 'l' to 'h' and vice versa) or quickly tapping the key.

Editing and undoing/redoing shows 'u' or '^R' for a short period of time.

Example:

https://user-images.githubusercontent.com/25431453/106161490-1e86b500-6198-11eb-9010-5410c7be3f9b.mov

### Expected behaviour

Launching vim with defaults and setting `showcmd` option doesn't show any signs of this issue:

https://user-images.githubusercontent.com/25431453/106160118-8936f100-6196-11eb-9637-1dcb6720467c.mov

*P.S. Pressing 'dd' to show that `showcmd` is on. Also pressing '^R' and 'u', but they don't show up.*

### Notes:

Found similar issues: [this](https://github.com/neovim/neovim/issues/7847) and [this](https://github.com/neovim/neovim/issues/8332) submitted almost 3 years ago.
While switching from vim and never knowing about this option, now I want to use it, but this flickering is quite irritating. 
Will this be fixed or is it *still* expected behaviour of 'showcmd' and I should forget about it?

**Comment by zeertzjq** [comment]
Hmm, I checked Vim version 8.0.0000 and latest version, and they both have this flickering.

**Comment by zeertzjq** [comment]
https://github.com/vim/vim/issues/11535#issuecomment-1312580515

> There is no logic about what would be
useful to show or not, it intentionally just shows whatever was typed,
since it's completely unpredictable how long it takes to execute.  Even
a simple "j" can take time, e.g. with slow syntax highlighting or when
an autocmd is triggered by it.  Anyway, guessing if it's short enough to
show will require some magic way to decide what's worth to show, which
will never satisfy users completely.  Just accept the brief display.
