### ISSUE TITLE
Wrong Indentation of JS and CSS in .html 

### ISSUE THREAD

**Issue by zubairakram** [neovim/neovim#13850]
- `nvim --0.4.3`:
- `vim -u DEFAULTS` (version: ) behaves differently? NO
- Ubuntu /20.04.1:
- GNOME Terminal/3.36.2:
- `$TERM`:

### Actual behaviour
```html
<script>
    import Nested from "./Nested.svelte";
let name = "John";
</script>
```
### Expected behaviour

```html
<script>
    import Nested from "./Nested.svelte";
    let name = "John";
</script>

**Comment by janlazo** [comment]
No init.vim to reproduce the issue. Neovim doesn't ship `svelte` runtime files. See `:h ft-html-indent`.

**Comment by elianiva** [comment]
Are you using any svelte related plugins? I believe one of them has a setting that determines this behaviour (the one I use has this)

**Comment by zubairakram** [comment]
I tried without any configuration, and create a new index.html file but same behavior. 

command `ggVG=`
```html
<!doctype html>
<html>
        <body>
                <script>
                        import File from "File.js";
let a = 4;
let b = 5;
                </script>
        </body>
</html>
```

**Comment by zubairakram** [comment]
> Are you using any svelte related plugins? I believe one of them has a setting that determines this behavior (the one I use has this)

no

**Comment by zeertzjq** [comment]
Did you try with `nvim --clean`?

**Comment by dundargoc** [comment]
I get correct indentation on neovim, both with and without treesitter, as well as vim. This sounds like plugin problem. Closing as I don't believe this is an issue with neovim.

**Comment by zubairakram** [comment]
as you wish

**Comment by dundargoc** [comment]
Are you still having this problem? 

Did you try it with `nvim --clean` and see if it works then?
