### ISSUE TITLE
Lua based statusline lags freezes when scrolling past buffer with mouse mode enabled

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#13857]
- `nvim --version NVIM v0.5.0-dev`:
- `vim -u DEFAULTS` (version: ) behaves differently? Yes (implicitly)
- Operating system/version: macOS/linux
- Terminal name/version: iTerm/alacritty
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Add the following snippet to your init.lua:

```lua
function _G.statusline()
    local filepath = '%f'
    local align_section = '%='
    local percentage_through_file = '%p%%'
    return string.format(
        '%s%s%s',
        filepath,
        align_section,
        percentage_through_file
    )
end

vim.cmd[[set statusline=%!v:lua.statusline()]]
```

### Actual behaviour

This is how smooth the scrolling is with the non-lua statusline.

https://user-images.githubusercontent.com/13316262/106392709-e9e94800-63a7-11eb-8cb2-02bf7b32b45c.mp4

### Expected behaviour

Once you scroll off buffer (flick the trackpad on a mac continuously), the lua statusline starts to lag, and continuous to lag/induce high cpu usages as you scroll back to the top. The hangs are most noticeable at the edge of the buffer. I'm wondering if we can just handle buffer scroll events when at the edge of the screen to avoid invoking the lua statusline.

cc: @glepnir 

https://user-images.githubusercontent.com/13316262/106393001-4f8a0400-63a9-11eb-8987-807c7d924563.mp4

**Comment by mpfaff** [comment]
I'm completely new to nvim's codebase but I'd be love to help fix this issue. Can someone more knowledgeable give me any pointers as to where this might be caused?

**Comment by justinmk** [comment]
I'd start by searching for issues labeled `mouse` and see if there are clues. I think there are similar discussions floating around.

**Comment by zeertzjq** [comment]
@mpfaff Can you still reproduce this bug?

**Comment by mpfaff** [comment]
> @mpfaff Can you still reproduce this bug?

@zeertzjq I'm very happy to report that I cannot (using v0.9.0)
