### ISSUE TITLE
autoload provider python, clipboard slow down neovim startup time

### ISSUE THREAD

**Issue by reportaman** [neovim/neovim#13869]
- `nvim --version`:
```
NVIM v0.5.0-dev+nightly-1-gad98b84
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210129-10302-hph3ye/build/config -I/tmp/neovim-20210129-10302-hph3ye/src -I/opt/homebrew/include -I/tmp/neovim-20210129-10302-hph3ye/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210129-10302-hph3ye/build/src/nvim/auto -I/tmp/neovim-20210129-10302-hph3ye/build/include

```
- `vim -u DEFAULTS` (version: ) behaves differently? Don't know what this question is
- Operating system/version: macOS
- Terminal name/version: Apple_Terminal 
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim --startuptime nvim.log
```
Out of 160 ms taken by nvim to start on my system, 60ms are taken by these lines... making it slower than vim 8 (vim 8 starts in 62ms, anything over 100ms is noticeable in UI business).
```
055.620  000.090  000.090: sourcing /opt/homebrew/Cellar/neovim/HEAD-ad98b84/share/nvim/runtime/autoload/provider/pythonx.vim
105.703  000.200  000.200: sourcing /opt/homebrew/Cellar/neovim/HEAD-ad98b84/share/nvim/runtime/autoload/remote/host.vim
105.805  050.455  050.165: sourcing /opt/homebrew/Cellar/neovim/HEAD-ad98b84/share/nvim/runtime/autoload/provider/python.vim
112.045  006.070  006.070: sourcing /opt/homebrew/Cellar/neovim/HEAD-ad98b84/share/nvim/runtime/autoload/provider/perl.vim
.
.
.128.417  000.315  000.315: sourcing /Users/reportaman/.vim/plugged/vim-startify/autoload/startify/fortune.vim
140.356  000.171  000.171: sourcing /opt/homebrew/Cellar/neovim/HEAD-ad98b84/share/nvim/runtime/autoload/provider/clipboard.vim
142.513  000.155  000.155: sourcing /Users/reportaman/.vim/plugged/vim-startify/syntax/startify.vim

```

Is there a way to work around this?

**Comment by Shougo** [comment]
You can set g:python_prog_path manually for it.

**Comment by reportaman** [comment]
@Shougo Is `python3_host_prog` different from `python3_prog_path`? The former came baked into neovim's init.vim.

Anyway, it didn't change anything. Here's my complete init.vim:

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath=&runtimepath
let g:python3_prog_path = '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3'
let g:python3_host_prog = '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3'
let g:vimtex_compiler_progname = 'nvr'
let g:ruby_host_prog = '/opt/homebrew/lib/ruby/gems/3.0.0/bin/neovim-ruby-host'
source ~/.vimrc


```

**Comment by Shougo** [comment]
g:python3_host_prog is correct name.
You have loaded Python3 in startup.
It is slow.
Vim is faster because Vim use dynamic link instead.

You need to upload installed plugins list in packpath.

**Comment by reportaman** [comment]
@Shougo "You need to upload installed plugins list in packpath". What does that mean? will it improve neovim load time? Thanks! I am using plugin manager [vim-plug](https://github.com/junegunn/vim-plug). [vim-plug](https://github.com/junegunn/vim-plug)'s code is in ``source ~/.vimrc``

**Comment by Shougo** [comment]
> @Shougo "You need to upload installed plugins list in packpath". What does that mean? will it improve neovim load time? Thanks! I am using plugin manager vim-plug. vim-plug's code is in source ~/.vimrc

You can load plugin lazily by vim-plug feature.  Please read vim-plug documentation for it.
You have listed plugin in `~/.vimrc`.  For example, UltiSnips uses Python3 feature.

> Can I use dynamic link in g:python3_host_prog ?

It is impossible.  neovim has different architecture from Vim.
This is neovim feature unfortunately.
You should not load Python based plugin in startuptime.
vim-plug has lazy load feature for it.

**Comment by Shougo** [comment]
If you really wanted to improve the startup time,
dein.vim is better but the configuration is difficult than vim-plug.

my neovim startup time is:

```
012.747  001.442: loading plugins
012.754  000.007: loading packages
012.882  000.128: loading after plugins
012.981  000.099: inits 3
016.931  003.950: reading ShaDa
017.293  000.363: opening buffers
017.298  000.005: BufEnter autocommands
017.301  000.003: editing files in windows
017.312  000.011: VimEnter autocommands
017.315  000.003: UIEnter autocommands
017.321  000.006: before starting main loop
017.790  000.469: first screen update
017.793  000.003: --- NVIM STARTED ---
```

**Comment by Shougo** [comment]
Python provider is not loaded if you don't load Python plugins in startup time.

**Comment by reportaman** [comment]
@Shougo Wow ``17.793ms`` is fast! That did the trick! It was this plugin that was loading python at startuptime: https://github.com/vim-scripts/PreserveNoEOL Removing it saves ``50ms``. Will definitely check dein.vim. Couldn't decipher one or two main reasons why one would want to move from vim-plug to dein.vim...

**Comment by Shougo** [comment]
My vimrc is hardly optimized...
