### ISSUE TITLE
v:lua with require('module') throw E117: Unknown function: <lambda

### ISSUE THREAD

**Issue by kevinhwang91** [neovim/neovim#13862]
- `nvim --version`: `NVIM v0.5.0-dev+1062-gcc1851c9f`
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: ArchLinux
- Terminal name/version: Alacritty
- `$TERM`: `tmux-256color`

### Steps to reproduce using `nvim -u NORC`

```
echo "function global_test()
    print('hi')
    return '10ofoo'
end

return {test = function()
    print('hello')
    return '10obar'
end}" > ~/.config/nvim/lua/test.lua
```

1. execute above shell command
2.  `nvim -u NONE +"lua require('test')" +"map <expr> o1 v:lua.require('test').test()" +"map <expr> o2 v:lua.global_test()"`
3. input `o1` and `o2`
4. run `:echo v:lua.require('test').test()` and `:echo v:lua.global_test()`
5.  run `:call v:lua.require('test').test()` and `:call v:lua.global_test()`

### Actual behaviour
1. input `o1` throw `E117: Unknown function: <lambda`, `o2` input `foo|`
2. `:echo v:lua.require('test').test()` is simlar to input `o1`, `echo v:lua.global_test()` output `hi\n10ofoo`
3. `:call v:lua.require('test').test()` output `hello` and `:call v:lua.global_test()` output `hi`

### Expected behaviour
`require('test')` and `global_test` produce the same result without any errors.

**Comment by AnthonyK213** [comment]
Same here. Now I am using `luaeval`, but it's not that ideal.

**Comment by glepnir** [comment]
cc @bfredl

**Comment by cinuor** [comment]
Same here.

**Comment by zeertzjq** [comment]
Seems fixed now.
