### ISSUE TITLE
Indent "README.txt" file not included in $VIMRUNTIME

### ISSUE THREAD

**Issue by katawful** [neovim/neovim#13864]
- `nvim --version`: NVIM v0.4.4 Build type: Release
- Operating system/version: Arch Linux

`:h indent-expression` says to check `$VIMRUNTIME/indent/README.txt` expression writing hints, but the file is not there

**Comment by clason** [comment]
You mean [this file](https://github.com/neovim/neovim/blob/master/runtime/indent/README.txt)?

**Comment by katawful** [comment]
Yeah, I guess its an Arch problem. Wasn't included for me. Closing

**Comment by clason** [comment]
No, you're right, the build script doesn't install it in `$VIMRUNTIME`.

**Comment by dundargoc** [comment]
I cannot recreate this. I believe this is solved.
