### ISSUE TITLE
Documentation: Default Control Mappings not tagged with <C-[character]> in Help Files

### ISSUE THREAD

**Issue by MaximoMachado** [neovim/neovim#13873]
`nvim --version`: v0.5.0-dev+1012-gfe1ebea33

### Actual behaviour
Typing `:help <C-d>` brings up no results

### Expected behaviour
It should bring up the help page for `Ctrl-d`

It's a rather minor issue but it'd be convenient if typing what I would type into my `init.vim` to do keybinds would also be the same thing I could type for the help command to bring me to its default mapping.

**Comment by glacambre** [comment]
I agree that this would be a worthwhile change but I think it should be suggested to Vim as most of Neovim's documentation is directly imported from Vim.

**Comment by MaximoMachado** [comment]
You're right, that would make the most sense. I'll post an issue over there instead.
