### ISSUE TITLE
lsp.log file gets filled up with line feed characters

### ISSUE THREAD

**Issue by brainplot** [neovim/neovim#13879]
### Actual behaviour
The log file generated by nvim's built-in LSP implementation gets filled up with line feed characters and no other contents in it.

```
$ wc -l ~/.cache/nvim/lsp.log
      21 /Users/gian/.cache/nvim/lsp.log
```
```
$ hexdump -C ~/.cache/nvim/lsp.log
00000000  0a 0a 0a 0a 0a 0a 0a 0a  0a 0a 0a 0a 0a 0a 0a 0a  |................|
00000010  0a 0a 0a 0a 0a                                    |.....|
00000015
```

I also pasted the log file as-is below to show that it's effectively empty.

### Expected behaviour
I expect the log file to just stay empty, with no spurious line feed characters if nothing is to be logged.
I don't know if one of the language servers I use is at fault here but I mainly use Go with `gopls` and Rust with `rust-analyzer`, in Neovim.
 
### Health check
<details>
<summary>Checkhealth result</summary>

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: rust_analyzer: configuration checked.
  - INFO: gopls: configuration checked.
```

</details>

### LSP log (located at `~/.cache/nvim/lsp.log`)

<details>
<summary>Log file</summary>

```






















```
</details>

### Nvim version
<details>
<summary>version</summary>

```
NVIM v0.5.0-dev+nightly-16-gb96db38af
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210204-13668-10drhzx/build/config -I/tmp/neovim-20210204-13668-10drhzx/src -I/opt/homebrew/include -I/tmp/neovim-20210204-13668-10drhzx/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210204-13668-10drhzx/build/src/nvim/auto -I/tmp/neovim-20210204-13668-10drhzx/build/include
Compiled by gian@mercury.fritz.box

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-b96db38/share/nvim"

Run :checkhealth for more info
```

</details>

`nvim-lspconfig` version: `2eb8567`

**Comment by srafi1** [comment]
This might be because of line `runtime/lua/vim/lsp/log.lua:78` which adds a blank line after neovim runs. It seems like some runs just didn't have any log messages, so they each just inserted an empty line into the log file.

https://github.com/neovim/neovim/blob/336eb70822970cea6797251043158ee6bd76bc69/runtime/lua/vim/lsp/log.lua#L77-L78

**Comment by brainplot** [comment]
So is the current behavior desirable?

**Comment by mjlbach** [comment]
I don't know what else we could do? I don't think it's worth adding a check if the last line was a blank before inserting a blank line for this

**Comment by srafi1** [comment]
I don't know if it's desirable, but it does look like it's intended.

Maybe instead of adding an empty line at the end of each run it would be better to start each run by adding a header line like this:
```
[ START ] LSP logging initiated: <timestamp>
```
That way we can differentiate between different runs without leaving blank lines in the log file.

**Comment by brainplot** [comment]
> `[ START ] LSP logging initiated: <timestamp>`

That would look a lot better, in my opinion. Additionally, it's much more `grep`pable than a blank line.

**Comment by TheAlakazam** [comment]
Hello, can I work on this?
