### ISSUE TITLE
#13244 breaks click on foldcolumn

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#13872]
Commit 368403a9e60ba3695717fa224b8fa249d8e6425b (PR #13244) breaks click on foldcolumn.
When the tab page label is displayed, clicking the `+` sign on the foldcolumn does nothing.

### Steps to reproduce 
```
nvim --clean -c 'set mouse=a fdc=1 stal=2'
```
Input some text and create a fold. Click the `+` sign on the fold column to unfold it.

### Actual behaviour
Nothing happens. 

### Expected behaviour
Unfold.

**Comment by teto** [comment]
@tk-shirasaka  when you made that change, for what GUI was it intended (out of curiosity) ? It's possible that we shouyld use `mouse_grid` instead in the code.

**Comment by tk-shirasaka** [comment]
@tomtomjhj 
I'm sorry...
I try to fix this problem

@teto
The GUI I'm using is a private tool I made for myself (work in progress)
https://github.com/tk-shirasaka/envim

> It's possible that we shouyld use `mouse_grid` instead in the code.

Thank you for your advice!
Check the operation in GUI and terminal and fix if possible.

**Comment by teto** [comment]
> I'm sorry...

Hehe my bad for the bad review. Shoganai :p Sorry to ask but I wondered if you have the time to look into it ? I would like to fix this for 0.5 . I haven't been able to test the multigrid yet but working towards it.

**Comment by tk-shirasaka** [comment]
Sorry this is taking so long.
Now I am looking into this issue and I think there are multiple causes.

The assumption is that I was correct in using default_grid when ext_multigrid is disabled.

I think the problems are as follows: 

1.When split tabs, set the tabline height (= 1) to [firstwin->w_winrow], so in mouse_find_win(), which is called when a cell is clicked, the row that is clicked is subtracted by [firstwin->w_winrow].
As a result, when checking the text in the clicked cell, the coordinates were wrong and the text in the clicked area could not be obtained.

2. even after fixing the above problem, it seems to be impossible to open and close the folds once you move to the second tab.

I am currently looking into the second problem, but have no idea how to fix the two issues.

I will continue to look into this issue, but it may take a very long time, so you can go ahead and solve it.
If I can fix it and no PR has been issued for this issue, I will issue one.

**Comment by tomtomjhj** [comment]
Another failure case: `nvim --clean '+set mouse=a fdc=1|rightbelow new'` (or `rightbelow vnew`), and create a fold there. Clicking on `+` sign doesn't unfold it.

**Comment by tk-shirasaka** [comment]
Thank you for check and reporting!
I'll try to fix this and add test case.

**Comment by tomtomjhj** [comment]
@teto can you re-open this? The case in which the clicking is done in the right vsplit was not fixed by #13982.
