### ISSUE TITLE
vim.fn.getcmdline() doesn't seem to be working

### ISSUE THREAD

**Issue by dorgnarg** [neovim/neovim#13887]
I'm looking to do something like [this](https://gist.github.com/romainl/047aca21e338df7ccf771f96858edb86), but entirely in lua. It doesn't seem to be working, and in trying to debug it, the culprit is either `vim.fn.getcmdline()` isn't working right, or I'm misunderstanding how to use it in this situation. I tried to just see what exactly `vim.fn.getcmdline()` had stored in it (mapping to do so below) to make sure I wasn't just using regexes incorrectly, but I'm actually getting no output at all from the function.

- `nvim --version`: `NVIM v0.5.0-dev+1061-ge85c8dff6`
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Arch Linux, kernel `5.10.11-arch1-1`
- Terminal name/version: Kitty 0.19.3
- `$TERM`: `xterm-kitty`

### Steps to reproduce using `nvim -u NORC`

```vim
:lua vim.api.nvim_set_keymap('c', [[cc]], [[<CR>]]..':'..vim.fn.getcmdline()..vim.fn.getcmdline(), {noremap = true})
" OR
:lua vim.api.nvim_set_keymap('c', [[cc]], [[<CR>]]..':'..vim.fn.getcmdline()..vim.fn.getcmdline(), {noremap = true, expr = true})

:help<cc>
```
(I had it output the same thing twice just so I could visually see if something was changing)

### Actual behaviour
```vim
: 
" OR
E15: Invalid expression: ^M:
E15: Invalid expression: ^M:
```
(in the first case, the help window opens, but this is what's left in the command line; in the second case, it displays that error and that's it)

### Expected behaviour
```vim
:helphelp
```
which is what I get in a `nvim -u NORC` session if instead I do
```vim
:cnoremap <expr> cc "\<CR>".getcmdline().getcmdline()

:help<cc>
```

**Comment by glacambre** [comment]
There is no bug here, the difference between you lua and vimscript snippet is that your vimscript snippet calls `getcmdline()` when you type `cc` while your lua snippet calls `vim.fn.getcmdline()` when you're creating the mapping :).

I'll close this issue but feel free to ask for clarifications if you need them :).
