### ISSUE TITLE
Provide a release asset for the Apple Silicon (M1) platform

### ISSUE THREAD

**Issue by paidhi** [neovim/neovim#13880]
### Actual behaviour
Currently the GitHub releases page for stable (0.4.4) and pre-release (v0.5.0-dev+1064-gb96db38af) have 1 asset file for macOS (`nvim-macos.tar.gz`). That's for x86_64.

### Expected behaviour
Have a separate asset file containing Neovim for the "Apple Silicon" (M1) ARM architecture to download.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/tree-sitter-on-m1-mac/401/5

**Comment by mhanberg** [comment]
I apologize for the bump, but is there a chance this could be moved forward? 

I can work on it if that's acceptable.

**Comment by clason** [comment]
Blocker is still the same: Github does not provide runners that can generate these artifacts. As soon as that changes, we're more than happy to use them.

**Comment by mhanberg** [comment]
Ahh, I guess I assumed the macOS 11 runner would run on apple silicon. 

No worries, thanks!

**Comment by syepes** [comment]
I have just tried building it from src and it does not build :-(
```
HEAD is now at c09656104 docs(lsp): fix resolve_capabilities docstring (#16577)
==> luarocks make --lua-dir=/opt/homebrew/opt/luajit-openresty --tree=/private/tmp/neovim-20211208-45334-1yr3to9/deps-build
==> luarocks make --lua-dir=/opt/homebrew/opt/luajit-openresty --tree=/private/tmp/neovim-20211208-45334-1yr3to9/deps-build
==> make install PREFIX=/private/tmp/neovim-20211208-45334-1yr3to9/deps-build LDFLAGS=-static
==> cmake -S . -B build -DLIBLUV_LIBRARY=/opt/homebrew/opt/luv/lib/libluv.dylib
==> cmake --build build
Last 15 lines from /Users/syepesfernandez/Library/Logs/Homebrew/neovim/05.cmake:
/tmp/neovim-20211208-45334-1yr3to9/src/nvim/terminal.c:849:29: error: passing 'VTermStringFragment' to parameter of incompatible type 'char *'
    buf_set_term_title(buf, val->string);
                            ^~~~~~~~~~~
/tmp/neovim-20211208-45334-1yr3to9/src/nvim/terminal.c:820:50: note: passing argument to parameter 'title' here
static void buf_set_term_title(buf_T *buf, char *title)
                                                 ^
1 error generated.
gmake[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:3289: src/nvim/CMakeFiles/nvim.dir/terminal.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
[ 50%] Building C object src/nvim/CMakeFiles/nvim.dir/ugrid.c.o
```

**Comment by muniter** [comment]
> I have just tried building it from src and it does not build :-(
> ```
> HEAD is now at c09656104 docs(lsp): fix resolve_capabilities docstring (#16577)
> ==> luarocks make --lua-dir=/opt/homebrew/opt/luajit-openresty --tree=/private/tmp/neovim-20211208-45334-1yr3to9/deps-build
> ==> luarocks make --lua-dir=/opt/homebrew/opt/luajit-openresty --tree=/private/tmp/neovim-20211208-45334-1yr3to9/deps-build
> ==> make install PREFIX=/private/tmp/neovim-20211208-45334-1yr3to9/deps-build LDFLAGS=-static
> ==> cmake -S . -B build -DLIBLUV_LIBRARY=/opt/homebrew/opt/luv/lib/libluv.dylib
> ==> cmake --build build
> Last 15 lines from /Users/syepesfernandez/Library/Logs/Homebrew/neovim/05.cmake:
> /tmp/neovim-20211208-45334-1yr3to9/src/nvim/terminal.c:849:29: error: passing 'VTermStringFragment' to parameter of incompatible type 'char *'
>     buf_set_term_title(buf, val->string);
>                             ^~~~~~~~~~~
> /tmp/neovim-20211208-45334-1yr3to9/src/nvim/terminal.c:820:50: note: passing argument to parameter 'title' here
> static void buf_set_term_title(buf_T *buf, char *title)
>                                                  ^
> 1 error generated.
> gmake[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:3289: src/nvim/CMakeFiles/nvim.dir/terminal.c.o] Error 1
> gmake[2]: *** Waiting for unfinished jobs....
> [ 50%] Building C object src/nvim/CMakeFiles/nvim.dir/ugrid.c.o
> ```


Follow this issue solution https://github.com/neovim/neovim/issues/16583

**Comment by clason** [comment]
That's a completely unrelated error when building from Homebrew.

**Comment by carlocab** [comment]
> Ahh, I guess I assumed the macOS 11 runner would run on apple silicon. 

The macOS 11 runner should be able to cross-compile for Apple Silicon. I don't think you'll be able to run any tests for it though.

**Comment by joviol** [comment]
Hello,
I was wondering if there had been any progress with this issue?
Thanks

**Comment by dundargoc** [comment]
[Tracking Issue](https://github.com/github/roadmap/issues/528)

**Comment by carlocab** [comment]
I suggest generating a universal release artefact in addition to x64 binary built here:

https://github.com/neovim/neovim/blob/b2ed439bd5ab1b431bb61f8754554c48453495c5/.github/workflows/release.yml#L80-L119

We would probably need to set a `CMAKE_OSX_DEPLOYMENT_TARGET=11` and `CMAKE_OSX_ARCHITECTURES=arm64;x86_64`. This will need to be built on a `macos-11` runner.

A few other modifications are required:
1. Skip bundling any library that is in `/usr/lib` -- these no longer live in the file system on Big Sur, so the `cp` operation will fail. They live in the dyld cache, though, so there is no need to bundle them.
2. We will need to provision a universal `libintl.dylib` before attempting to build `nvim`. 

A few options I can think of for (2) above:
1. Build a universal version of `gettext`.
2. Fetch an arm64 build of `gettext` (e.g. `brew fetch --bottle-tag=arm64_big_sur gettext`) and then use `lipo` to fatten our existing x64 `libintl` with our just-downloaded arm64 `libintl` into a universal binary.

**Comment by clason** [comment]
Thank you! That sounds reasonable (and doable?). Just a note: 1. we already do.

**Comment by carlocab** [comment]
> Thank you! That sounds reasonable (and doable?). Just a note: 1. we already do:
> 
> https://github.com/neovim/neovim/blob/e3bfc1293e30512a6aa23964a3486ee709ac3f21/.github/workflows/release.yml#L104-L113

Yes -- this bundles `libiconv` and `libutil`. I don't think this is necessary. At the very least, it is not needed on 10.15 and newer, and will cause the workflow to fail if you run it on `macos-11` or `macos-12`.

**Comment by carlocab** [comment]
I have a universal binary built for macOS 11+ at https://github.com/carlocab/neovim/releases/tag/nightly. I would regard the usage of this on Apple Silicon as highly experimental, but it's worked for the few things I've tried with it so far.

I would also normally say that running random binaries you find online is as bad, if not worse, than taking candy from strangers. I'd probably still recommend that advice, but the somewhat adventurous can at least verify the checksums against what was built from the [workflow that was meant to produce them](https://github.com/carlocab/neovim/runs/6981558775?check_suite_focus=true#step:16:18).

-----

> 10.15 is an acceptable minimum.
> 
> Edit: or whatever reaches the most users and works in CI with the least hassle. The prebuilt downloads are not required to be super backwards-compatible, what matters is that the build/publish script is maintainable, reliable, and works for 51+% of users. That's it.

Ok, I suggest trying out a minimum of `10.13` and then see how well that works. It may be possible to experiment with even lower than that, but `10.13` is what CMake use for their (universal) binary builds, and they'll probably have put a lot more thought into this.

**Comment by clason** [comment]
Anything below `10.15` is sugar on top, I'd say. I wouldn't worry about going lower.

In fact, one of our main dependencies LibUV only [supports macOS 10.15+](https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md), so I don't think it's reasonable to advertise anything lower.

**Comment by clason** [comment]
Seems to work well on M1, with no regression from a local build 👍 

If it's a universal build, do we still need the separate macOS build?

**Comment by carlocab** [comment]
No, I guess not. Do we want to try running the test suite on it? But we'd probably want to run the tests on arm64 after having built on x64.
