### ISSUE TITLE
Running any command with `:!` while setting `shell` variable to `pwsh` gives an error.

### ISSUE THREAD

**Issue by neelkarma** [neovim/neovim#13893]
- `nvim --version`:
```
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: 8.2) behaves differently? Yes, it works correctly.
- Operating system/version: Windows 10
- Terminal name/version: 
Shell: PowerShell 7.1.1
Terminal: Windows Terminal 1.5.10271.0
- `$TERM`: `vtpcon`

### Steps to reproduce using `nvim -u NORC`
Make sure you have PowerShell 7 installed first. Also, this might be a Windows-only issue, but I'm not certain.
```
nvim -u NORC
:set shell=pwsh
:!echo hello
```

### Actual behaviour
This error is outputted:
```
An unknown element "" was received. This can happen if the remote process closed or ended abnormally.

shell returned 4000

Press ENTER or type command to continue
```
Note: This behaviour is the same with any `:!` command, not just `echo hello`.

### Expected behaviour
This should be the output:
```
hello
```
(the same behaviour as if the command was run outside of NeoVim)

**Comment by bfredl** [comment]
you might need to change 'shellcmdflag' as well.

**Comment by neelkarma** [comment]
@bfredl *facepalms* that's exactly what I needed! `pwsh` needs the flag `-c` if you want to execute one command, so I used `set shellcmdflag=-c` and it fixed it. thx

**Comment by carlosgrillet** [comment]
This was my solution:

`vim.opt.shell = 'pwsh'`
`vim.opt.shellcmdflag = '-nologo -noprofile -ExecutionPolicy RemoteSigned -command'`
`vim.opt.shellxquote = ''`

in my lua config file

**Comment by Kolkhis** [comment]
> `vim.opt.shell = 'pwsh'` `vim.opt.shellcmdflag = '-nologo -noprofile -ExecutionPolicy RemoteSigned -command'` `vim.opt.shellxquote = ''`

Thank you! Didn't work until I added the `vim.o.shellxquote = ''`

**Comment by mbaklor** [comment]
y'all saved my sanity thank you

**Comment by wilkinnovo** [comment]
> `vim.opt.shellcmdflag = '-nologo -noprofile -ExecutionPolicy RemoteSigned -command'`
> `vim.opt.shellxquote = ''`

Yes @carlosgrillet 👍

**Comment by justinmk** [comment]
If you set 'shell' you are taking the responsibility of setting all shell-related options. This has long been documented at `:help  shell-powershell`.
