### ISSUE TITLE
Hyper Key

### ISSUE THREAD

**Issue by samyakbardiya** [neovim/neovim#13891]
- `nvim --version`: v0.4.4
- Operating system/version: Arch Linux v5.10.12
- Terminal name/version: st v0.8.4
- `$TERM`: st-256color

### I want to map my binding using `Hyper` Key

recently I came across an option of [setxbmap](https://wiki.archlinux.org/index.php/Xorg/Keyboard_configuration#Using_setxkbmap) 
```
setxkbmap -option 'ctrl:swapcaps_hyper'
```
what this command does is that it makes the `Caps Lock` as `Ctrl`, and `Ctrl` as `Hyper`.

so now I want to bind some things in the neovim to the new Hyper key, but sadly vim don't support Hyper key and so do neovim.

they only supports:
- **shift** as `<S-...>`
- **control** as `<C-...>`
- **alt** as `<A-...>`
- **meta** as `<M-...>`
- **super** as `<D-...>`

so I was hoping if neovim can add the support of Hyper key :)  
after doing some research found that Emacs support it, so I was guessing then neovim can too.

**Comment by pta2002** [comment]
I guess this would depend if the hyper key is passed on to the terminal. Does emacs support it on non-GUI mode?

**Comment by samyak039** [comment]
got your point, the Emacs in terminal does not support hyper key.

that's sad :(

**Comment by pta2002** [comment]
I guess the only way to implement this then would be to bypass the terminal and grab it from X/Wayland manually, but that'd be a whole lot of trouble. Maybe a way for GUI frontends to bind to it? Don't know if there's already a way to do that

**Comment by samyak039** [comment]
is there any application like `xev` but for tty ?

**Comment by bfredl** [comment]
Adding yet another combiner flag to core like `<H-x>` wouldn't be difficult, but it is up to UI:s to actually detect the key from os/toolkit and assign it to this falg. I don't know of any terminal who support it unfortunately (personally I just use X11 terminals that support XIM/ibus/etc, then I can preprocess keyboard input as I like).

**Comment by pta2002** [comment]
Does neovim already handle that kind of terminal? If it does it probably wouldn't be too hard to support this

**Comment by bfredl** [comment]
well no, but if such a terminal exist it wouldn't be hard, just tell us what sequences it uses :sweat_smile:

**Comment by zeertzjq** [comment]
Kitty recently introduced a new keyboard protocol that supports representing much more keys and key combinations. (<https://sw.kovidgoyal.net/kitty/keyboard-protocol.html>) I just opened issue #14400 for that.
