### ISSUE TITLE
Unneeded space in front of command description

### ISSUE THREAD

**Issue by looshch** [neovim/neovim#13901]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: 8.1.2292): same behaviour
- Operating system/version: any
- Terminal name/version: any

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:help index
735G
WW

```

### Actual behaviour
unneeded space in front of command description
### Expected behaviour
no unneeded space in front of command description :)

**Comment by dundargoc** [comment]
Hi! Thank you for your contribution. Unfortunately I'll need to close this down as it's a fix in the `runtime` directory, which [vim](https://github.com/vim/vim) is responsible for. Even if we fix this there's a risk the change will be reverted the next time the runtime directory is updated. I encourage you to send this fix to them: that way it'll only be a matter of weeks until it gets fixed here as well :+1: .
