### ISSUE TITLE
Use autocommands instead of calling `:cwindow` for lsp command that use quickfix

### ISSUE THREAD

**Issue by BoltsJ** [neovim/neovim#13904]
- `nvim --version`: `NVIM v0.5.0-dev+1073-gb894fbcbe`
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Pop_OS 20.10
- Terminal name/version: `# GNOME Terminal 3.38.0 using VTE 0.62.0 +BIDI +GNUTLS +ICU  +SYSTEMD`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

Run `:lua vim.lsp.buf.references()` on a symbol

### Actual behaviour

The quickfix window opens as if `:cwindow` had been run
![image](https://user-images.githubusercontent.com/182554/107279134-425dbc80-6a1c-11eb-947f-3935eafee1a0.png)

### Expected behaviour

The quickfix window doesn't open and instead the QuickFixCmdPre and QuickFixCmdPost autocommands are executed. For example, I have autocommands that resize the window if it has fewer than 10 entries and hardcoded behavior is rather annoying since grep and make have different behavior on the quickfix window.

References: https://github.com/neovim/nvim-lspconfig/issues/718 #12241 #13160

**Comment by mjlbach** [comment]
Sorry for the delay. 

I thought this over, and I think this falls under the "user should add an override" rather than we add an option. if we add an option, we would still want to show the quickfix list by default. I think having some type of interactive picker when given multiple references (as is the usual case) is the behavior most users would expect/want. 

It's pretty easy though to get the functionality you want with the current override driven configuration style we recommend.

```lua
  local handlers = {
    ['textDocument/references'] = function(_,result, ctx, _)
      if not result or vim.tbl_isempty(result) then
        vim.notify('No references found')
      else
        vim.fn.setqflist({}, ' ', {
          title = 'Language Server';
          items = vim.lsp.util.locations_to_items(result, ctx.bufnr);
        })
        vim.cmd [[ doautocmd QuickfixCmdPost ]]
      end
    end
  }

  nvim_lsp['tsserver'].setup { handlers = handlers }

```

Here's a minimal self-contained example of how you would add this to your config using lspconfig (ofc you can directly pass handlers to start_client as well):

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    vim.api.nvim_buf_set_keymap(
      bufnr, 'n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', { noremap = true, silent = true })
  end

  -- Add the server that troubles you here
  local handlers = {
    ['textDocument/references'] = function(_,result, ctx, _)
      if not result or vim.tbl_isempty(result) then
        vim.notify('No references found')
      else
        vim.fn.setqflist({}, ' ', {
          title = 'Language Server';
          items = vim.lsp.util.locations_to_items(result, ctx.bufnr);
        })
        vim.cmd [[ doautocmd QuickfixCmdPost ]]
      end
    end
  }

  vim.cmd [[ 
    function! Open_qf() abort
      let l:cw = win_getid()
      execute 'cclose|botright '.min([10, len(getqflist())]).'cwindow'
      call win_gotoid(l:cw)
    endfunction
    autocmd QuickfixCmdPost [^l]* call Open_qf() 
  ]]

  nvim_lsp['tsserver'].setup { handlers = handlers }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

cc @neovim/lsp if anyone disagrees. The option would require adding something like config.use_qf_autocmd_only, I think it's too user-specific though to warrant expanding the option surface given the ease of overriding as in the prior example.

**Comment by BoltsJ** [comment]
Requesting this be re-evaluated.
