### ISSUE TITLE
GCC 10 emits warning -Wstringop-overflow

### ISSUE THREAD

**Issue by dutchgecko** [neovim/neovim#13913]
- `nvim --version`:
HEAD @ 971e0ca903

- Operating system/version: Debian testing (bullseye)
- GCC version: gcc (Debian 10.2.1-6) 10.2.1 20210110

### Steps to reproduce using

With ninja installed:

    make CMAKE_BUILD_TYPE=Release

### Actual behaviour

At end of build GCC emits:

    In function ‘line_putchar’,
        inlined from ‘win_line’ at ../src/nvim/screen.c:3971:23:
    ../src/nvim/screen.c:1899:16: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
    1899 |     dest[1][0] = 0;
         |                ^

### Expected behaviour

No warnings.

**Comment by bfredl** [comment]
we might need to change `&linebuf_char[off]` into `linebuf_char+off` ( `&*` seems to imply erasing array lenght)

**Comment by glacambre** [comment]
@dutchgecko Are you still able to reproduce this warning message? I tried the same compiler version on the same commit as you and couldn't.

**Comment by dutchgecko** [comment]
Nope, just pulled from master and this warning didn't occur.
