### ISSUE TITLE
Make `!` work on nomodifiable buffers?

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#13912]
Neovim currently refuses to run `!` commands on nomodifiable buffers. I would like to be able to use `!` on nomodifiable buffers.

Use case:

I'm using a shell within a terminal buffer. I run `ls` and get the following output:

```
file1
file2
file3
...
file99
```

I use visual mode to select file3 to file90 and run `:'<,'>!xargs rm` to delete them. Since the terminal buffer is nomodifiable, it isn't modified, but the files are removed because the command was run.

**Comment by jamessan** [comment]
> I use visual mode to select file3 to file90 and run `:'<,'>!xargs rm` to delete them.

Why not use `:'<,'>w !xargs rm` instead?  That doesn't try to modify the buffer.

**Comment by glacambre** [comment]
Because it didn't cross my mind, but this is a very acceptable workaround, thanks for the suggestion :)
