### ISSUE TITLE
Windows 10 LSP infrastructure issue

### ISSUE THREAD

**Issue by the42** [neovim/neovim#13911]
I report it here as it doesn't affect a specific LSP client

- `nvim --version`: v0.5.0-dev+1080-g971e0ca90
- Operating system/version: Windows 10
- Terminal name/version: Windows terminal

### What I did before
* Install json / yaml language server with `npm install -g --save vscode-json-languageserver` and `npm install -g --save yaml-language-server`
* `:checkhealth` reports they are fine
* Set configuration from https://github.com/neovim/nvim-lspconfig#keybindings-and-completion, add `jsonls` and `yamlls` as server
* Open a json OR yaml file

### Actual behaviour
Error message is:
```
E5108: Error executing lua ...Data\Local\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:389: attempt to index upvalue 'handle' (a nil value)
```

### Expected behaviour
LSP works

**Comment by mjlbach** [comment]
From IRC: 

```
If anyone is using windows and lspconfig and gets attempt to index upvalue 'handle' (a nil value) when loading some file try adding .cmd in the cmd. On windows some language servers are not executables
```

**Comment by the42** [comment]
@mjlbach Yes, that's it. Might be worthwhile to change https://github.com/neovim/nvim-lspconfig/blob/041dfd7fb648d24c80cb8829dda2469f66f88490/lua/lspconfig/yamlls.lua#L5 to be platform specific (and for all the other langugage server client configurations where this makes a difference)

**Comment by erw7** [comment]
Since it is troublesome to add extensions to all batch files on the nvim-lspconfig side, I created #14103 to handle this on the neovim side. This can be handled by simply adding the following to `init.lua`, in which case there is no need to handle it on the neovim side.

```lua
vim.loop.spawn = (function ()
  local spawn = vim.loop.spawn
  return function(path, options, on_exit)
    local full_path = vim.fn.exepath(path)
    return spawn(full_path, options, on_exit)
  end
end)()
```

**Comment by mjlbach** [comment]
The mitigation suggested by @erw7 is now recommended in the lspconfig readme (see `:help lspconfig-windows`). I feel like it would be kinda weird to have lspconfig wrap vim.loop.spawn, so I agree if we do "fix" it, it should be in core (responding partially to what @bfredl brought up in #14103)

**Comment by mjlbach** [comment]
@erw7 It seems like this workaround will cause issues that call spawn in a lua callback (with the error "Windows: vimL function must not be called in a lua loop callback"). This happens with packer (@wbthomason). See: https://github.com/neovim/nvim-lspconfig/issues/899

**Comment by mjlbach** [comment]
I'm going to close this as there really isn't an issue, users on windows just need to postpend `.cmd` to the cmd, which can be handled in lspconfig (PRs welcome)

**Comment by webmandman** [comment]
@mjlbach I added the 'cmd' extension to the command, but all lsp functions don't do anything. 
 the lsp.log in AppData\Local\Temp\nvim doesn't have any logs for any of the lsp functions i'm calling.
 
 Perhaps, I have underlying issue. When I `:lua vim.cmd('e'..vim.lsp.get_log_path())` I get the error: 
 E5108: Error executing lua [string:":lua"]:1: Vim:E492: Not an editor command: eC:\Users\DANIEL~1.MEJ\AppData\Local\Temp\nvim\lsp.log
 
So can you give me a little guidance on how to debug this, please. 

![image](https://user-images.githubusercontent.com/991677/132740044-01699bcf-86d5-4b32-8ed5-654bdae81714.png)

**Comment by webmandman** [comment]
@mjlbach  I rebooted and ran another rename function and now I can see something in the log file. Looks to me like the request is being sent and it errors out. Does this log help?

[ DEBUG ] 2021-09-09T11:16:41-0700 ] ...elopment\Tools\Neovim\share\nvim\runtime\lua\vim\lsp.lua:897 ]	"LSP[tsserver]"	"client.request"	1	"textDocument/rename"	{  newName = "filesystem",  position = {    character = 6,    line = 0  },  textDocument = {    uri = "C:\\Development\\sites\\intra\\angularworkspace\\rename.js"  }}	<function 1>	2
[ DEBUG ] 2021-09-09T11:16:41-0700 ] ...ment\Tools\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:395 ]	"rpc.send.payload"	{  id = 4,  jsonrpc = "2.0",  method = "textDocument/rename",  params = {    newName = "filesystem",    position = {      character = 6,      line = 0    },    textDocument = {      uri = "C:\\Development\\sites\\intra\\angularworkspace\\rename.js"    }  }}
[ DEBUG ] 2021-09-09T11:16:41-0700 ] ...ment\Tools\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:496 ]	"decoded"	{  id = 4,  jsonrpc = "2.0",  result = vim.NIL}
[ DEBUG ] 2021-09-09T11:16:41-0700 ] ...Tools\Neovim\share\nvim\runtime\lua\vim\lsp\handlers.lua:461 ]	"default_handler"	"textDocument/rename"	{  ctx = '{\n  bufnr = 2,\n  client_id = 1,\n  method = "textDocument/rename"\n}'}

**Comment by webmandman** [comment]
@mjlbach I reverted back to 0.5.0 version and all lspconfig functions work.

**Comment by Shougo** [comment]
You should execute git bisect for it.

**Comment by webmandman** [comment]
@Shougo never knew about that git command. Thanks.
