### ISSUE TITLE
Extra empty lines read from stdout of jobstart

### ISSUE THREAD

**Issue by brookhong** [neovim/neovim#13910]
With below code snippet,

    function! NeoWrap(channel, msg, event)
        call appendbufline(2, '$', a:msg)
    endfunction
    call jobstart("echo 'abc'", {"on_stdout": function('NeoWrap')})

I get 3 new lines as below in buffer 2 (two empty lines appended after the expected `abc`)

    abc
    <- unexpected empty line
    <- unexpected empty line

With below in vim

    function! NeoWrap(channel, msg)
        call appendbufline(2, '$', a:msg)
    endfunction
    call job_start("echo 'abc'", {"out_cb": function('NeoWrap')})

I get what is expected -- just one line. I think the vim's way here is much more reasonable.

**Comment by glacambre** [comment]
I think the first empty line is the `\n` emitted by `echo` and the second empty line is the `EOF` caused by the end of the program. I think I prefer Neovim's behavior as it gives more control to plugin developers, but maybe other people disagree.

**Comment by brookhong** [comment]
Then please try

    function! NeoWrap(channel, msg, event)
        call appendbufline(2, '$', a:msg)
    endfunction
    let g:jdb = jobstart("jdb", {"on_stdout": function('NeoWrap')})


It writes below lines into neovim buffer:

    Initializing jdb ...

    > 

But `jdb` actually just prints when it runs from terminal

    Initializing jdb ...
    >

**Comment by glacambre** [comment]
I can't test your piece of code as I don't have `jdb` but I think `NeoWrap` is being called twice here (once with a:msg = `["Initilializing jdb ..., ""]` and then once with a:msg = `[">", ""]`). The empty line between the two lines of output is inserted by appendbufline().
Could you try running the following code to confirm my theory?
```vim
function! NeoWrap(channel, msg, event)
  echoerr a:msg
endfunction
let g:jdb = jobstart("jdb", {"on_stdout": function('NeoWrap')})
```

**Comment by bfredl** [comment]
in neovim `a:msg` is just data, not lines of the output. The only reason a list is used is because vimL requires a list to represent binary data. Use lua callbacks to avoid this problem (as lua has 8-bit strings)

**Comment by brookhong** [comment]
@glacambre 

Here is result,

    ['Initializing jdb ...', '']
    ['> ']

@bfredl but why is there an empty string at end of the list?

**Comment by bfredl** [comment]
it represents a final newline character.
