### ISSUE TITLE
vim.lsp.diagnostic.goto_next/goto_prev jump to next/previous line even if the current line has additional diagnostics

### ISSUE THREAD

**Issue by wbthomason** [neovim/neovim#13915]
- `nvim --version`:
```
NVIM v0.5.0-dev+1080-g971e0ca90
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=native -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/yaytmp-1000/neovim-git/src/build/config -I/tmp/yaytmp-1000/neovim-git/src/neovim-git/src -I/usr/include -I/tmp/yaytmp-1000/neovim-git/src/build/src/nvim/auto -I/tmp/yaytmp-1000/neovim-git/src/build/include
Compiled by wil@tesla

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Steps to reproduce
1. Install `pyright` (https://github.com/microsoft/pyright)
2. Setup LSP + `pyright` using settings from https://github.com/neovim/nvim-lspconfig
3. Open a new Python file, create multiple errors on a single line, as well as errors on a later line
4. Run `:lua vim.lsp.diagnostic.goto_next()` and observe that the cursor jumps between lines, but not between diagnostics on the same line.

### Actual behaviour
The cursor jumps between diagnostics on distinct lines

### Expected behaviour
The cursor jumps between all diagnostics in sequence, including those on the same line as other diagnostics

### Preliminary investigation notes

I haven't had time to figure out the right way to fix this yet, but this seems to happen because `get_next`/`get_prev` (in `runtime/lua/vim/lsp/diagnostic.lua`) only pass the current line to `_iter_diagnostic_lines`, ignoring the column of the cursor position. Fixing this is slightly complicated because it appears that `get_prev` relies on decrementing this line value by 2 to search "backward"; naively continuing this will not have the desired behavior (i.e. this will continue to skip previous diagnostics on the same line as the current diagnostic).

**Comment by glepnir** [comment]
yep if now the position has two or more diagnostic information the goto next/prev will fail. need improve it. I am rewriting goto behavior. pr later.
