### ISSUE TITLE
nvim_buf_set_keymap is not triggered in normal mode when cursor is at EOL

### ISSUE THREAD

**Issue by jbyuki** [neovim/neovim#13924]
- `nvim --version`:
```
NVIM v0.5.0-dev+1052-g271cec291                                                                                         
Build type: Release                                                                                                     
LuaJIT 2.1.0-beta3
```
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: win10
- Terminal name/version: nvim-qt

### Steps to reproduce using `nvim -u NORC`

In an empty buffer do:

ex-command
```
:lua vim.api.nvim_buf_set_keymap(0, 'n', 'm', [[ :lua print(math.random())<CR> ]], { noremap = true })
```

press `m` in normal mode

### Actual behaviour

Pressing `m` doesn't trigger the keymap.
First I have to write some text, go back some characters, and then press `m` in normal mode to correctly trigger it.

It also moves the cursor for no apparent reason.

### Expected behaviour

It should trigger the keymap right away.

```
nnoremap <buffer> m :lua print(math.random())<CR>
```
works as intended.

**Comment by notomo** [comment]
The following works well.

```
:lua vim.api.nvim_buf_set_keymap(0, 'n', 'm', [[:lua print(math.random())<CR>]], { noremap = true })
```

`[[ :lua print(math.random())<CR> ]]` is the same with `<Space>:lua print(math.random())<CR><Space>`.
If you enable beep, you should get beeping on the first `<Space>`.

📝 https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/src/nvim/normal.c#L5179-L5182

**Comment by jbyuki** [comment]
Thank you for the help.
Removing the spaces work as intended, it solves the issue.
I would like to enable beep, but I think it's unsupported on my distribution (neovim-qt, win10).

I close the issue as it was not a bug.
