### ISSUE TITLE
Neovim fails to properly read file URI with g + x 

### ISSUE THREAD

**Issue by 71GA** [neovim/neovim#13927]
- Nvim version: `v0.4.4`:
- Vim version: `8.1`
- OS: `Debian 10 -- 4.19.171-2 (2021-01-30) x86_64 GNU/Linux`

### Steps to reproduce

If I open any kind of C source file and create a comment like this: 

`// EXAMPLE 1: ../../example.pdf`

If I position cursor over the file path and press <kbd>g</kbd>+<kbd>x</kbd> file is opened by a default OS PDF viewer. So I conclude that relative file paths are found and opened corectly.

If I create a (file) URI like this the file is also opened:

`// EXAMPLE 2: file:///home/ziga/example.pdf`

But if I create a (file) URI like this, file is only opened, **but not on the page 10**.

`// EXAMPLE 3: file:///home/ziga/example.pdf#page=10`

### Expected behaviour

I expect Nvim to properly treat URI's and open PDF at the specified page... This is extremely important for documentation purposes.

**Comment by glacambre** [comment]
`gx` is a netrw binding. Netrw is maintained by [dr chip](http://www.drchip.org/astronaut/vim/index.html#NETRW) so you should probably contact them instead. Neovim doesn't maintain its own runtime files.

**Comment by janlazo** [comment]
netrw will not be updated in 0.4.x releases. Test nightly release after https://github.com/neovim/neovim/pull/13949 is merged. If bug remains, wait for release 0.5.1.

**Comment by 71GA** [comment]
THank you for pointing me in the right direction!

**Comment by camoz** [comment]
Might be related: netrw's `gx` functionality is broken in other ways currently: https://github.com/vim/vim/issues/4738

**Comment by 71GA** [comment]
@BachoSeven So from which `nvim` version onward it is fixed? What about verion of `vim`?

**Comment by gpanders** [comment]
That commit will be included in the forthcoming 0.6 release.

**Comment by 71GA** [comment]
@gpanders Thanks! How could I come to the same cconclusion using GitHub? Where should I look?

**Comment by clason** [comment]
It will be in the next 0.x.0 release after the commit, unless it has been backported (which you'll see from the PR view as it will have a `has-backport` label).

**Comment by 71GA** [comment]
@BachoSeven I tested today with the `nvim` nightly build 0.6.0 and it does not fix the problem! I used `.appimage`. How did you test this?

**Comment by clason** [comment]
I guess this was a misunderstanding: your _actual_ issue (which is a bit hidden in your report) is (emphasis mine)

> I expect Nvim to properly treat URI's and **open PDF at the specified page**

What lead you to believe that netrw supports this functionality? Did you configure your viewer accordingly?

**Comment by BachoSeven** [comment]
Yea @71GA I was talking about the generalised `gx` issue which has been a problem for some months in vim/neovim now, not the PDF-specific request you had. Sorry for the confusion.
