### ISSUE TITLE
No windows icon in taskbar an topbar in version 5.0

### ISSUE THREAD

**Issue by vicenteferrari** [neovim/neovim#13925]
- `nvim --version`: NVIM v0.5.0-dev+1085-g52397aaa0
- Operating system/version: Windows 10

### Steps to reproduce

Open Neovim through nvim-qt.exe

### Actual behaviour

The window gets a generic icon in the topbar and taskbar. In previous versions it would show the icon fine.

**Comment by jdhao** [comment]
Do you mean [this issue](https://github.com/neovim/neovim/issues/13682)?

**Comment by jgehrig** [comment]
This is a duplicate of #12928

There is a Pull Request out to fix this issue, #13004.

**Comment by jamessan** [comment]
Duplicate of #12928
