### ISSUE TITLE
LSP diagnostics message order should be reversed for virtualtext

### ISSUE THREAD

**Issue by hood** [neovim/neovim#13929]
- `nvim --version`: latest nightly build: 0.5.0+dev+1085+g52397aaa0-1
- language server name/version: tsserver for Typescript@4.1.3
- Operating system/version: Linux arch 5.10.13-arch1-2 #1 SMP PREEMPT Sat, 06 Feb 2021 11:07:29 +0000 x86_64 GNU/Linux

### Actual behaviour
Sorting of LSP diagnostics messages is the same for floating windows and inline virtual text messages.
[Image](https://i.imgur.com/tD4v9is.png)

### Expected behaviour
Sorting of LSP diagnostics messages should be reversed for inline virtual text messages, in order to always display the most relevant diagnostics message first.

**Comment by mjlbach** [comment]
I don't think there's any guarantee that the order of the diagnostics corresponds to the order of severity.

**Comment by hood** [comment]
@mjlbach They should be sorted by severity if that's the case. It's kinda awkward to have the least important message hide more critical errors messages.
