### ISSUE TITLE
Ctrl+Shift+V paste not working correctly in NEOVIM.

### ISSUE THREAD

**Issue by Magnus512** [neovim/neovim#13921]
- `nvim --version`: v0.5.0-dev-1083-g1aec5ba85
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Arch Linux
- Terminal name/version: Alacritty 0.7.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour Ctrl+Shift+v paste a line copied from other place but enters into a weird mode, where nvim inserts the keyboard events I'm doing
![nvimbe](https://user-images.githubusercontent.com/7065012/107722405-15b7d800-6c9c-11eb-8b40-bc721f9435b3.png)

### Expected behaviour
Ctrl+Shift+V just paste like normal Ctrl+Shift+V

**Comment by e-kwsm** [comment]
#10865
#11699

**Comment by ThePrimeagen** [comment]
Looks like 02a3c4179 is the last working commit (at least for me)

**Comment by Magnus512** [comment]
> Looks like [02a3c41](https://github.com/neovim/neovim/commit/02a3c417945e7b7fc781906a78acbf88bd44c971) is the last working commit (at least for me)

Sr. this is an honor, I follow you and enjoy your stream, I', going to try that commit and try to fix the new ones.

**Comment by ThePrimeagen** [comment]
> > Looks like [02a3c41](https://github.com/neovim/neovim/commit/02a3c417945e7b7fc781906a78acbf88bd44c971) is the last working commit (at least for me)
> 
> Sr. this is an honor, I follow you and enjoy your stream, I', going to try that commit and try to fix the new ones.

Snap!

Thanks for the nice message

**Comment by anott03** [comment]
I only experience this issue when in normal mode. When in insert mode, paste is working as expected.

System specs:
OS: Manjaro
NVIM: v0.5.0-dev+1092-g03383ee27
Terminal: kitty

**Comment by anott03** [comment]
I would suggest renaming this to "System paste not working correctly" or "terminal paste not working correctly" since this doesn't seem to have anything to do with ctrl+shift+v directly.

**Comment by worldeva** [comment]
I'm running into this bug every single time when pasting. Actually ran into this bug while trying to reproduce another bug XD.  
System:  
OS: 5.10.16-arch1-1  
NVIM: v0.5.0-dev+1099-g4d5dbea4f  
Terminal: Termite  
Some additional testing seems to reveal that after it broke it stopped processing escape and backspace literally, but it "breaking" twice seems to fix it. Improperly processed keycodes?  
Tests:  
```
Text Works Here
Test^[[201~
Text Borked:^?^[^]^[
^[[200~Test
Text Works Here  
```

**Comment by erw7** [comment]
I think the problem with @Magnus512 and the problem with @anott03, @worldeva are two different things.

The problem with @Magnus512 is that it fails to parse the sequence at the end of the bracketed paste due to mixing the sequence at the end of the bracketed paste(`^[[201~`) with the sequence in the loss of focus report(`^[[O`).

In contrast, @anott03, @worldeva's problem is that it fails to parse the normal bracketed paste end sequence.

@anott03, @worldeva If you have changed `ttimeout` and `ttimeoutlen`, try resetting them to their default values.

@Magnus512 In the meantime, can you tell me what window manager you are using?

**Comment by worldeva** [comment]
@erw7 Updated comment, I'm using NORC

**Comment by Magnus512** [comment]
> I'm running into this bug every single time when pasting. Actually ran into this bug while trying to reproduce another bug XD.
> System:
> OS: 5.10.16-arch1-1
> NVIM: v0.5.0-dev+1099-g4d5dbea4f -u NORC
> Terminal: Termite, Kitty, Alacritty
> Some additional testing seems to reveal that after it broke it stopped processing escape and backspace literally, but it "breaking" twice seems to fix it.
> Tests:
> 
> ```
> Text Works Here
> Test^[[201~
> Text Borked:^?^[^]^[
> ^[[200~Test
> Text Works Here  
> ```
> 
> **Update:** After some research, the bug appears to be caused by improper (parsing of?) ANSI escape codes for bracketed paste codes. A lead might be just grepping for "bracketed paste".

This is what is happening pasting twice let me write again, but with two copies o the lines.

**Comment by Magnus512** [comment]
> > > Looks like [02a3c41](https://github.com/neovim/neovim/commit/02a3c417945e7b7fc781906a78acbf88bd44c971) is the last working commit (at least for me)
> > 
> > 
> > Sr. this is an honor, I follow you and enjoy your stream, I', going to try that commit and try to fix the new ones.
> 
> Snap!
> 
> Thanks for the nice message

You are welcome.

**Comment by Magnus512** [comment]
> @erw7 Updated comment, I'm using NORC
> 
> Additionally, [02a3c41](https://github.com/neovim/neovim/commit/02a3c417945e7b7fc781906a78acbf88bd44c971) is the last working commit for me as well.

I am going to try I have been working in other projects, thank you.

**Comment by erw7** [comment]
> Looks like 02a3c41 is the last working commit (at least for me)

> Additionally, 02a3c41 is the last working commit for me as well.

I'm more than a little baffled by this fact. The reason is that subsequent commits don't seem to have any changes that would affect the parsing of the bracketed paste sequence.

I can't reproduce the phenomenon in my environment. I have a question for someone who is experiencing this problem. Can you please show me the nvim_paste.log that you created with the following steps? Then maybe we will have a clue as to the solution.

```
>nvim -u NORC
:echo getpid()

# In another terminal. xxxx is the nvim pid displayed by echo getpid().
>gdb -p xxxx
...
(gdb) define print_rbuffer
Type commands for definition of "hoge".
End with a line saying just "end".
>echo "
>set $c=(char*)$arg0
>set $s=(char*)$arg1
>set $e=(char*)$arg2
>set $i=(int)$arg3
>while($i)
 >if(*$c>=0x20 && *$c<0x7F)
  >printf "%c", *$c
  >else
  >printf "[0x%02x]", *$c
  >end
 >if($c==$e)
  >set $c=$s
  >else
  >set $c++
  >end
 >set $i--
 >end
>echo "\n
>end
(gdb) set pagination off
(gdb) set logging file nvim_paste.log
(gdb) set logging on
Copying output to nvim_paste.log.
(gdb) break handle_raw_buffer 
Breakpoint 1 at 0x46ab08: file ../src/nvim/tui/input.c, line 559.
(gdb) commands 
Type commands for breakpoint(s) 1, one per line.
End with a line saying just "end".
>p uv_hrtime()
>p force
>print_rbuffer input->read_stream.buffer.read_ptr input->read_stream.buffer.start_ptr input->read_stream.buffer.end_ptr input->read_stream.buffer.size
>cont
>end
(gdb) cont

# Go back to the nvim terminal and paste the appropriate content.
```

**Comment by worldeva** [comment]
[nvim_paste.log](https://github.com/neovim/neovim/files/6018044/nvim_paste.log)

Steps:
```
Pasted "Test"
Typed ctrl-]
Pasted "Test"
Typed ctrl-] :q!
```

**Comment by e-kwsm** [comment]
Which version of CMake are you using?
The issue occurs if neovim is built with CMake 2.8.12.2, but does not happen with CMake 3.17.1 (on RHEL 7.7).

**Comment by e-kwsm** [comment]
nvim works correctly with CMake 3.9.0 but does not with 3.8.0.

**Comment by Magnus512** [comment]
> nvim works correctly with CMake 3.9.0 but does not with 3.8.0 (nvim [595f6e4](https://github.com/neovim/neovim/commit/595f6e4d64bc2b44d8b9102706a84a16ed166199)).

cmake 3.19.5

**Comment by erw7** [comment]
@worldeva Thanks. Does #13987 solve this problem?

**Comment by elianiva** [comment]
This has been driving me insane, I didn't have this issue yesterday but suddenly when I paste to nvim this morning, it inserts some weird characters for some bizzare reason. I can confirm that @erw7's PR fixed it.

**Comment by Magnus512** [comment]
> @worldeva Thanks. Does #13987 solve this problem?

I have to clone your repo right ?

**Comment by elianiva** [comment]
@Magnus512 if you use gh-cli, you could just go to neovim repo (assuming you already have that) and do `gh pr checkout 13987` and build from there

**Comment by Magnus512** [comment]
> @Magnus512 if you use gh-cli, you could just go to neovim repo (assuming you already have that) and do `gh pr checkout 13987` and build from there

I just modified the input file with the contents described :P and it works

**Comment by e-kwsm** [comment]
#13987 fixes the issue.
CMake 3.9.0+ enables LTO, which seems to initialize the variables.

**Comment by worldeva** [comment]
@erw7 Yep, #13987 fixes it for me.

**Comment by ThePrimeagen** [comment]
I'll update now and confirm as well

**Comment by sthendev** [comment]
Came here from google. I was facing this issue on 0.9.1 and was stuck figuring out why. Ultimately it came down to having ttimeoutlen=0 in my config. I forget why I added this to my config in the first place. All good after removing it.
