### ISSUE TITLE
Proposal: Host version checking mechanism

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#1393]
After #1376, I got some errors until I realized I had to pip update neovim package.

I think we should put in place some mechanism so that nvim knows the minimum host version it needs for an external language, and thus we get a meaningful error message in cases like the above, instead of random python errors.

It could be as simple as:
- In the host init file (python_setup.vim) in this case:
  - have a variable defining minimum needed version.
  - in the host startup process, include a call to host asking for version, and check that against minimum one.
  - provide meaningful error if versions don't match
- In the external language client:
  - provide an api function to query for version.

Thoughts?

**Comment by justinmk** [comment]
Addressed by https://github.com/neovim/neovim/pull/6743. Merging with https://github.com/neovim/neovim/issues/4261
