### ISSUE TITLE
Help Request: On windows 8.1 Neovim stable v0.4.4 upon exiting closes all active programs and crashes windows

### ISSUE THREAD

**Issue by dseeni** [neovim/neovim#13938]
Hi Neovim, 
I'm use NVIM v0.4.4 with NVIM-QT 0.2.161 on Windows 8.1 Pro (old computer cant handle Windows 10)

I'm a new user/coder and love neovim, could someone with experience on windows help me out?
This might be a bug or maybe its just my hardware.

**Upon exiting Neovim, every couple of weeks, Neovim will close all other programs and crash (BSOD) windows.**

**Do you think compiling from source would help my issue? I could attempt to learn to do that.**

Here is the crash dump for the bug check. Other than the system itself is table, the error even log is clear except for a daily TLS Error Code 70 
A fatal alert was received from the remote endpoint. The TLS protocol defined fatal alert code is 70. 

I've been pulling my hair out trying to figure this out haha. Is it my hardware or is it Nvim???? I can't tell and any advice to point me in the right direction would be greatly appreciated. 

Please advise.

**Here is the bug check crash dump analysis from WinDbg:**
Something to do with wininit.exe and nvim terminating??

*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

CRITICAL_PROCESS_DIED (ef)
        A critical system process died
Arguments:
Arg1: ffffe001fdac38c0, Process object or thread object
Arg2: 0000000000000000, If this is 0, a process died. If this is 1, a thread died.
Arg3: 0000000000000000
Arg4: 0000000000000000

Debugging Details:
------------------

KEY_VALUES_STRING: 1

STACKHASH_ANALYSIS: 1

TIMELINE_ANALYSIS: 1

DUMP_CLASS: 1

DUMP_QUALIFIER: 401

BUILD_VERSION_STRING:  9600.19939.amd64fre.winblue_ltsb.210109-0600

SYSTEM_MANUFACTURER:  System manufacturer

SYSTEM_PRODUCT_NAME:  System Product Name

SYSTEM_SKU:  SKU

SYSTEM_VERSION:  System Version

BIOS_VENDOR:  American Megatrends Inc.

BIOS_VERSION:  0701

BIOS_DATE:  06/04/2014

BASEBOARD_MANUFACTURER:  ASUSTeK COMPUTER INC.

BASEBOARD_PRODUCT:  RAMPAGE IV BLACK EDITION

BASEBOARD_VERSION:  Rev 1.xx

DUMP_TYPE:  1

BUGCHECK_P1: ffffe001fdac38c0

BUGCHECK_P2: 0

BUGCHECK_P3: 0

BUGCHECK_P4: 0

PROCESS_NAME:  wininit.exe

CRITICAL_PROCESS:  wininit.exe

EXCEPTION_CODE: (Win32) 0xd50 (3408) - The program cannot be used with this operating system.

ERROR_CODE: (NTSTATUS) 0xd50 - The program cannot be used with this operating system.

CPU_COUNT: c

CPU_MHZ: d48

CPU_VENDOR:  GenuineIntel

CPU_FAMILY: 6

CPU_MODEL: 3e

CPU_STEPPING: 4

CPU_MICROCODE: 6,3e,4,0 (F,M,S,R)  SIG: 428'00000000 (cache) 428'00000000 (init)

DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT

BUGCHECK_STR:  0xEF

CURRENT_IRQL:  0

ANALYSIS_SESSION_HOST:  DEEPAK

ANALYSIS_SESSION_TIME:  02-14-2021 13:44:57.0148

ANALYSIS_VERSION: 10.0.17763.132 amd64fre

STACK_TEXT:  
ffffd000`203e8948 fffff802`78676e9c : 00000000`000000ef ffffe001`fdac38c0 00000000`00000000 00000000`00000000 : nt!KeBugCheckEx
ffffd000`203e8950 fffff802`785c1088 : ffffe001`fdac38c0 ffffe002`073aed20 00000000`00000000 00000000`0000000f : nt!PspCatchCriticalBreak+0xa4
ffffd000`203e8990 fffff802`7849d79f : ffffe001`fdac38c0 ffffe002`073aed20 ffffe001`fdac38c0 ffffe001`fdac38c0 : nt! ?? ::NNGAKEGL::`string'+0x32d18
ffffd000`203e89f0 fffff802`7867685c : ffffffff`ffffffff ffffd000`203e8a99 ffffe001`fdac38c0 ffffe002`073ae880 : nt!PspTerminateProcess+0x67
ffffd000`203e8a30 fffff802`781ca3e3 : ffffe002`073ae880 00000000`00000d50 ffffe002`073ae880 00000000`0000000f : nt!NtTerminateProcess+0xe0
ffffd000`203e8b00 00007ff8`509109ca : 00007ff8`4ddf10b9 00000000`00000000 00000000`00000000 00000000`000000f4 : nt!KiSystemServiceCopyEnd+0x13
00000043`0699e818 00007ff8`4ddf10b9 : 00000000`00000000 00000000`00000000 00000000`000000f4 00000000`000000f4 : ntdll!NtTerminateProcess+0xa
00000043`0699e820 00007ff6`75a3d1dd : 00000000`000000f4 00000000`00001a2c 00000000`0000025c 00000000`00000200 : KERNELBASE!TerminateProcess+0x25
00000043`0699e850 00007ff6`75a3d19e : 00000000`00000002 00000000`00001a2c 00000000`000000f4 00000000`000001b0 : nvim+0x1bd1dd
00000043`0699e9d0 00007ff6`75a3d19e : 00000043`00000002 00007ff6`00001a2c 00000000`0000011c 00000000`000001fc : nvim+0x1bd19e
00000043`0699eb50 00007ff6`75a2c264 : 00020000`00000011 00000005`e79603c8 00000043`08ac6c60 00000000`00000001 : nvim+0x1bd19e
00000043`0699ecd0 00007ff6`75a2be99 : 00000043`00000004 00000000`00000002 00000043`00000000 00000000`00000008 : nvim+0x1ac264
00000043`0699ed00 00007ff6`7593bb25 : 00000043`0699efe0 00000000`00000000 00000043`0699efe0 00000000`00000001 : nvim+0x1abe99
00000043`0699edf0 00007ff6`7598795e : 00000000`00000000 00000043`00000000 00000000`00000000 00000000`00000000 : nvim+0xbbb25
00000043`0699ee20 00007ff6`7593c61b : 00000043`06bee100 00000000`00000001 00000000`00000000 00007ff6`7590659a : nvim+0x10795e
00000043`0699ee50 00007ff6`75906796 : 00000043`06bee100 00000043`0699efe0 00000000`00000001 00000000`00000001 : nvim+0xbc61b
00000043`0699eeb0 00007ff6`75900536 : 00007ff6`759132a0 00000043`0699f210 00000043`08ea7ec7 00000043`00000000 : nvim+0x86796
00000043`0699eee0 00007ff6`758fdf0c : 00000043`0699f148 00000043`00000000 00000043`0699f210 00007ff6`759132a0 : nvim+0x80536
00000043`0699f110 00007ff6`75965575 : 00000000`00000000 00000000`ffffffff 00000000`ffffffff 00008186`9147418a : nvim+0x7df0c
00000043`0699f780 00000000`00000000 : 00000000`ffffffff 00000000`ffffffff 00008186`9147418a 00000000`0000003a : nvim+0xe5575

THREAD_SHA1_HASH_MOD_FUNC:  12d4f8166084547a36ad1919e5e9be82c6bc362c

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  7c116878a67f991ead64d1e599ff122038c53176

THREAD_SHA1_HASH_MOD:  e67a0e624c52f38b55cbc3206cd4a122f2aea89d

SYMBOL_NAME:  ANALYSIS_INCONCLUSIVE

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: Unknown_Module

IMAGE_NAME:  Unknown_Image

DEBUG_FLR_IMAGE_TIMESTAMP:  0

STACK_COMMAND:  .thread ; .cxr ; kb

FAILURE_BUCKET_ID:  0xEF_wininit.exe_BUGCHECK_CRITICAL_PROCESS_TERMINATED_BY_nvim.exe_d50_ANALYSIS_INCONCLUSIVE!unknown_function

BUCKET_ID:  0xEF_wininit.exe_BUGCHECK_CRITICAL_PROCESS_TERMINATED_BY_nvim.exe_d50_ANALYSIS_INCONCLUSIVE!unknown_function

PRIMARY_PROBLEM_CLASS:  0xEF_wininit.exe_BUGCHECK_CRITICAL_PROCESS_TERMINATED_BY_nvim.exe_d50_ANALYSIS_INCONCLUSIVE!unknown_function

TARGET_TIME:  2021-02-13T07:18:25.000Z

OSBUILD:  9600

OSSERVICEPACK:  0

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

SUITE_MASK:  272

PRODUCT_TYPE:  1

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 8.1

OSEDITION:  Windows 8.1 WinNt TerminalServer SingleUserTS

OS_LOCALE:  

USER_LCID:  0

OSBUILD_TIMESTAMP:  2021-01-09 09:46:26

BUILDDATESTAMP_STR:  210109-0600

BUILDLAB_STR:  winblue_ltsb

BUILDOSVER_STR:  6.3.9600.19939.amd64fre.winblue_ltsb.210109-0600

ANALYSIS_SESSION_ELAPSED_TIME:  693

ANALYSIS_SOURCE:  KM

FAILURE_ID_HASH_STRING:  km:0xef_wininit.exe_bugcheck_critical_process_terminated_by_nvim.exe_d50_analysis_inconclusive!unknown_function

FAILURE_ID_HASH:  {2f91859d-b39f-4762-dbed-a65310e5a9ab}

**Comment by dseeni** [comment]
Ive attached the bugcheck as a .txt file if thats easier to view the stack, its a lot of nvim and wininit.exe
[Here is the bugcheck as a txt file](https://docs.google.com/document/d/1u2Ur5aDMReRnQ1f4hMQeJ_dvoS4Ab27Y9SB2TkOHWbQ/edit?usp=sharing)

**Comment by glacambre** [comment]
Have you tried using neovim nightly? If you're lucky this problem won't appear there.

**Comment by dseeni** [comment]
> Have you tried using neovim nightly? If you're lucky this problem won't appear there.

Hey Glacambre, 
I havent, but I can def try that if it helps!

**Comment by glacambre** [comment]
@dseeni it's been a while now, have you encountered this crash on neovim nightly? :)

**Comment by dseeni** [comment]
Sorry been a while. It's def much better, I've only gotten this crash once in the last 6 months. Maybe we can close this for now.
