### ISSUE TITLE
Vim functions are not available within vim.fn object

### ISSUE THREAD

**Issue by ivaaaan** [neovim/neovim#13933]
- `nvim --version`: v0.4.4
- Operating system/version: macOS Big Sur
- Terminal name/version: Alarcitty
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
:lua print(vim.inspect(vim.fn))
```

### Actual behaviour

Prints `nil`, no functions are available within the `vim.fn` object. 

### Expected behaviour

I suppose it should return a table with functions available, but it's not the case for me, and I cannot call any functions.
Tried the same command on Alpine Linux on a different machine, the issue persists.

**Comment by bfredl** [comment]
It is 0.5 feature

**Comment by ivaaaan** [comment]
@bfredl what should I use instead then? I took it from the https://neovim.io/doc/user/lua.html
`vim.call` doesn't seem to be working as well
