### ISSUE TITLE
LSP lacks a first-class way to restart servers

### ISSUE THREAD

**Issue by dbalatero** [neovim/neovim#13946]
My LSP client for Sorbet (Ruby) can drop sometimes when my work's VPN cuts out (often when I return to my laptop the next day). I wrote an `on_exit` hook for the LSP client that detects this and prompts to reconnect to the VPN. However, it was a little difficult to figure out how to restart the LSP servers for a given buffer in an easy, ergonomic way.

I went down the rabbit hole here: https://www.reddit.com/r/neovim/comments/ljzlux/how_do_i_restart_a_failed_language_server_with/

I finally got pointed to this FAQ (which I missed because I searched the help for `restart`):

```
FAQ                                                     *lsp-faq*

- Q: How to force-reload LSP?
  A: Stop all clients, then reload the buffer. >

     :lua vim.lsp.stop_client(vim.lsp.get_active_clients())
     :edit
```

I think this is an OK approach, but `:edit` feels like the wrong API to be using to express the intent of "I want to restart my LSP servers."

If you run it in an unsaved buffer, you'll get:

```
E37: No write since last change (add ! to override)
```

If you run the `:edit!` flavor, it will overwrite any changes you have in the buffer.

If you're paranoid and just do `:write | edit`, you get a weird side effect of writing the file, and a `"blah/file.rb" 5L, 57C written"` shows up on bottom status and flashes.

As someone writing a plugin that is trying to self-heal a crashed LSP server, I'd much rather just call a method like `vim.lsp.restart_clients()` that wraps up `vim.lsp.stop_client(vim.lsp.get_active_clients())` and does whatever the autocmd attached to `:edit` was doing.

As a bonus, it will be the least surprising API for anyone looking in the documentation, and much more easily found.

Thoughts?

## Possible action items

1. (easy) Add the keyword `restart` to `Q: How to force-reload LSP?` in the help files, to help with searchability, maybe `Q: How to force-reload/restart LSP?`
2. (??) Add a `vim.lsp.restart_clients()` API method that just works and can be called from any buffer.

**Comment by aca** [comment]
+1 Many lsp servers are not stable, and have memory issues. I really miss `:CocRestart` of coc.nvim.

**Comment by mjlbach** [comment]
This is (slightly) more complicated than it seems.

Do you want a restart attribute on the client which reattaches all of the currently attached buffers? Also anything implemented here is likely going to be an orthogonal method to that of lspconfig. We can make lspconfig aware of things implemented in core, but not vice versa, so if you restart a client here, you'll break compatibility with the lspconfig management of workspaces.

**Comment by mjlbach** [comment]
This isn't really an issue anymore as I've added LspRestart/Start/Stop to nvim-lspconfig, and we provide lower level APIs in core.

**Comment by jose-elias-alvarez** [comment]
With the advent of `vim.lsp.start()`, I wonder if there's a chance of reopening this issue. For the same reasons described in the original post, the recommended workaround is not ideal, and the absence of a first-class method to restart servers is a blocker for me to switch to `vim.lsp.start()` in my personal use and in plugins.

**Comment by dbalatero** [comment]
@jose-elias-alvarez 

Do any of these help?

> This isn't really an issue anymore as I've added LspRestart/Start/Stop to nvim-lspconfig, and we provide lower level APIs in core.

**Comment by dbalatero** [comment]
First class start/stop/restart seems pretty core and would be a great API to have. IIRC, @mjlbach is not a contributor to Neovim anymore so I think you'd have to find another core member to reopen this idea with.
