### ISSUE TITLE
nvim segfaults in terminal_paste() if yank buffer is empty

### ISSUE THREAD

**Issue by gibboni** [neovim/neovim#13955]
If I try to paste while I'm in the terminal and the yank buffer/register is empty, then nvim will segfault in function terminal_paste() in file terminal.c. The reason for this seems to be that the pointer y_buffer is not checked before it is fed to strlen(). 

- `nvim --version`: v0.5.0-dev+1089-gdc3ca16a9
- Operating system/version: Debian 10 and Windows 10
- `$TERM`: screen.xterm-256color

### Steps to reproduce using `nvim -u NORC`
1. Make sure your yank buffer/register is empty
2. Open terminal using `:term`
3. Press p to paste

**Comment by dylanarmstrong** [comment]
I will work on this one
