### ISSUE TITLE
relativenumber can only be set as a boolean in lua

### ISSUE THREAD

**Issue by insertdead** [neovim/neovim#13974]
- `nvim --version`:
```
NVIM v0.5.0-dev+1099-g4d5dbea4f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/madsci/git/neovim/build/config -I/home/madsci/git/neovim/src -I/home/madsci/git/neovim/.deps/usr/include -I/usr/include -I/home/madsci/git/neovim/build/src/nvim/auto -I/home/madsci/git/neovim/build/include
Compiled by madsci@gud-pc-lol-mint20

Features: +acl +iconv +tui
```
- Operating system/version: Linux Mint 20.1 ulyssa
- Terminal name/version: Alacritty 0.7.1
- `$TERM`:  `tmux-256color`

### Steps to reproduce using `nvim -u NORC`
include lua file with:
```
vim.o.relativenumber = 'number'
```

### Actual behaviour
An error is produced:
`E5113: Error while calling lua chunk: /tmp/test.lua:1: Option 'relativenumber' requires a Boolean value`

### Expected behaviour
The option `relativenumber` can be set with either a boolean, or the string `'number'`.

**Comment by wren** [comment]
I'm sorry, but I don't think I understand this issue. `:help relativenumber` says `'relativenumber' 'rnu'	boolean	(default off)`.

Doesn't that mean that it should be a boolean? Why would setting `relativenumber` to `'number'` be expected to work?

**Comment by elianiva** [comment]
I mean, you shouldn't do that. If you want to enable number, you should use `vim.wo.number = true` instead of `vim.wo.relativenumber = 'number'`

**Comment by francis-junr** [comment]
is'nt there a third option in vim to set reltive line nubers with absolute line number at the line on the cursor

**Comment by clason** [comment]
No, you just set both `number` and `relativenumber`.
