### ISSUE TITLE
[Bug] vim.fn.has('win32') returning/showing current buffer instead of true or false value

### ISSUE THREAD

**Issue by Borwe** [neovim/neovim#13971]
- `nvim --version`: v0.5.0-dev+1099-g4d5dbea4f
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: Ubuntu 20.04
- Terminal name/version: qterminal
- `$TERM`:  screen-256color

### Steps to reproduce using `nvim -u NORC`
:v:lua vim.fn.has("win32")
```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
Just prints the buffer I was currently on into the cmd line, line by line
### Expected behaviour
Show/return a value saying if I am windows or not.

**Comment by glepnir** [comment]
use `vim.loop.os_uname().sysname`

**Comment by glacambre** [comment]
@Borwe I can't reproduce this issue with `:lua if vim.fn.has("win32") == 1 then print("windows") else print("not windows") end`. Are you sure you specified the right steps to reproduce this issue?

**Comment by bfredl** [comment]
If the error persist a screenshot would be useful.

**Comment by erw7** [comment]
@Borwe  You are probably running the `:vglobal` ex command and not evaluating `v:lua.fn.has('win32')`. Please see `:h :vglobal`.

```vim
" Execute :vglobal/lua.fn.has('win32')/p 
:v:lua.fn.has('win32')

" Evaluate v:lua.fn.has('win32')
:echo v:lua.fn.has('win32')
```

**Comment by Borwe** [comment]
It now works with a more recent build, probably got fixed.
