### ISSUE TITLE
Revert start-up test of xsel to avoid slow startup time because of "has('clipboard')" delays

### ISSUE THREAD

**Issue by xeyownt** [neovim/neovim#13999]
Hello,

- `nvim --version`: nvim 0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Debian 10 Buster 64bit (in VMWare / Windows 10 host)
- Terminal name/version: terminator 1.92-1
- `$TERM`: xterm-256color

I have a setup where unfortunately interacting with X clipboard is slow, both `xsel` and `xclip` shows a one second delay:

``` bash
time xclip -o -selection clipboard
#foobar
#
#real	0m1.047s
#...
time xsel -o -b
#foobar
#
#real	0m1.070s
```

Because of the test in `runtime/autoload/provider/clipboard.vim`, using `xsel` as clipboard provider adds a 1s penalty to boot time. The recommended fix so far is to use `xclip`, which indeed works for that problems but introduces other problems (clipboards sync issues). Hence I'd like to stick to `xsel` (another fix pointed by @bfredl is to remove all occurrences of `has('clipboard')` from vim.ini).

The following change was introduced in commit 695703ca97e9330e3dbbeb3153b57b4ca565d045 in 2017 to fix an issue in xsel, and fallback to xclip:

``` diff
-  elseif exists('$DISPLAY') && executable('xsel')
+  elseif exists('$DISPLAY') && executable('xsel') && s:cmd_ok('xsel -o -b')
```

However, in 2018, `xclip` has been promoted, and is selected before `xsel` (commit 799d9c32157c841c3b8d355fa98a5ace435eef07):

```diff
-  elseif exists('$DISPLAY') && executable('xsel') && s:cmd_ok('xsel -o -b')
-    let s:copy['+'] = 'xsel --nodetach -i -b'
-    let s:paste['+'] = 'xsel -o -b'
-    let s:copy['*'] = 'xsel --nodetach -i -p'
-    let s:paste['*'] = 'xsel -o -p'
-    return 'xsel'
   elseif exists('$DISPLAY') && executable('xclip')
     let s:copy['+'] = 'xclip -quiet -i -selection clipboard'
     let s:paste['+'] = 'xclip -o -selection clipboard'
     let s:copy['*'] = 'xclip -quiet -i -selection primary'
     let s:paste['*'] = 'xclip -o -selection primary'
     return 'xclip'
+  elseif exists('$DISPLAY') && executable('xsel') && s:cmd_ok('xsel -o -b')
+    let s:copy['+'] = 'xsel --nodetach -i -b'
+    let s:paste['+'] = 'xsel -o -b'
+    let s:copy['*'] = 'xsel --nodetach -i -p'
+    let s:paste['*'] = 'xsel -o -p'
+    return 'xsel'
```

As a result, the test on `xsel -o -b` is "less" necessary, and I would like to propose to remove it, ie. revert commit 695703ca97e9330e3dbbeb3153b57b4ca565d045, so that to fix the 1s boot delay. If there are concerns over `xsel` over alternatives like `lemonade`, maybe `xsel` could be demoted further. In any case, I think that, in practice, if xsel is available on the system, we should assume that it works correctly and the `xsel -o -b` test was more of a temporary fix.

Thanks for your time and great app!
Michaël

**Comment by janlazo** [comment]
I'm in favor of this change because I uninstalled xclip to use xsel.

I'd go further: expose an array of clipboard programs that neovim supports.
Allow the user modify this array so that neovim can skip to checking only xsel and xclip on Unix systems.

**Comment by glacambre** [comment]
@janlazo Isn't that what `g:clipboard` already kinda does? (except that the array of clipboards has to be maintained by the user rather than neovim)

**Comment by xeyownt** [comment]
I confirm we can use `g:clipboard` for that, but I think this is "reserved" to power user.

Looking for the issue above, I found many references of slow neovim start, and I suspect that many comes from the check `s:cmd_ok`. Personally I can live with a slow copy/paste (in particular, it's *not* slow when copying to/from within neovim), but a slow boot is always annoying.

**Comment by janlazo** [comment]
@glacambre The array is meant to determine the order of conditions checked in `provider#clipboard#Executable()` so that user doesn't have to copy/paste all of the code in order to configure `g:clipboard` in their init.vim. `g:clipboard` remains the top priority.

**Comment by bfredl** [comment]
"slow boot" will only happen if something in your init.vim invokes `has('clipboard')`. perhaps this can be avoided?

**Comment by xeyownt** [comment]
@bfredl Thanks for the interesting suggestion. I indeed had a couple of those in init.vim, which I just commented out. I confirm this indeed fixes boot time issues.

I also see it occurring in fugitive plugin, but it doesn't affect boot time.

**Comment by kylo252** [comment]
> Isn't that what `g:clipboard` already kinda does? (except that the array of clipboards has to be maintained by the user rather than neovim)

@glacambre, Thanks for the hint! I ended up using this in my config:
```lua
vim.g.clipboard = {
  copy = {
    ["+"] = "xsel -i -b",
    ["*"] = "xsel -i -p",
  },
  paste = {
    ["+"] = "xsel -o -b 2>/dev/null",
    ["*"] = "xsel -o -p 2>/dev/null",
  },
}
```

**Comment by justinmk** [comment]
> However, in 2018, `xclip` has been promoted, and is selected before `xsel` (commit [799d9c3](https://github.com/neovim/neovim/commit/799d9c32157c841c3b8d355fa98a5ace435eef07)):

That was reverted in https://github.com/neovim/neovim/commit/b042f6d9022a4c734477f1fdbc92b4f8134661b3
