### ISSUE TITLE
virt_text overlay hides visual selection / cursorline / colorcolumn

### ISSUE THREAD

**Issue by lukas-reineke** [neovim/neovim#13994]
- `nvim --version`: NVIM v0.5.0-dev+1106-g46a58b74f

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:lua vim.api.nvim_buf_set_extmark(0, 1, 2, 3, { virt_text={{'--', 'ErrorMsg'}, {'gg', 'String'}}, virt_text_pos='overlay'})

```

### Actual behaviour
The new overlay virtual text position (https://github.com/neovim/neovim/pull/13952) takes priority even over visual selection, cursor line etc

### Expected behaviour
I am not sure if this is expected behaviour or a bug. Normal virtual text does not behave this way.
It would be nice to make them work the same, or have an option to not take priority over these "UI" elements

**Comment by bfredl** [comment]
`line_attr` (ie cursorline and similar) should be trivial to fix. for visual selection I am not sure, depending on the usecase it shouldn't look like the virt_text is part of the selected text. I also considered making the overlays hide when you select the underlying text. What do you think about that?

**Comment by lukas-reineke** [comment]
> I also considered making the overlays hide when you select the underlying text. What do you think about that?

Makes sense to me :+1:

**Comment by bew** [comment]
I'm not sure I follow, while in visual mode I'd like to be able to use an easymotion-like-using-overlays to change the selection, to reduce it your example.
In that case the overlay should be visible over visual text. 

But the other way also has its use cases, like indent guides, and hiding them would make sense..

**Comment by bfredl** [comment]
My plan is to make it configurable.

**Comment by lynndylanhurley** [comment]
Just want to make sure you guys see the problem that resulted in this ticket.

This is how visual selection normally looks:

<img width="789" alt="Screen Shot 2021-02-22 at 12 17 12 PM" src="https://user-images.githubusercontent.com/468037/108876549-f1c19400-75c3-11eb-8f8b-9282c37dc310.png">

This is how it looks when the text overlay is used for indent guides:

<img width="790" alt="Screen Shot 2021-02-22 at 12 16 00 PM" src="https://user-images.githubusercontent.com/468037/108876629-0c940880-75c4-11eb-86eb-3ca77face0b8.png">

It would be ideal if the indent guides were still visible under the visual selection highlight.

**Comment by lukas-reineke** [comment]
fixed with https://github.com/neovim/neovim/pull/14065

thank you :rocket:
