### ISSUE TITLE
Add gen_vimdoc to CI

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#14009]
One re-occuring issue we have is that contributors (including, often egregiously, me) forget to regenerate documentation as part of their PR. We can make CI do this on merge, but it would also probably be a good idea to add a bot that gives a diff of the documentation (in a single, updating comment) on each PR, that way we can see what the doc changes would be without pushing directly to the PR branch (which teto and I disabled in nvim-lspconfig because it got too annoying having to rebase old PRs due to doc changes).

@mfussenegger @teto what do you think about this approach? I can implement the bot if this seems useful.

**Comment by teto** [comment]
agreed on the need and the fact that autocommit/merge doc is annoying. Having a bot comment on the PR could also be quite nagging if we receive a new notification on every rebase. The way we do with version.c patches is my current favorite, aka having the  bot open a PR with the changes, at regular interval. For an example: https://github.com/neovim/neovim/pull/12763

**Comment by mjlbach** [comment]
Can we suppress notifications per user? The idea would be the bot would update its comment in place (a la nixpkgs) so we would at most get one notification for the original comment. 

Maybe the version.c patch approach is a better idea, but the concern I have is that someone adds a bad change in the docs without realizing it, and then we need to merge a change in the lua source to fix the issue, then rerun the docgen PR.

**Comment by mfussenegger** [comment]
Throwing in a third variant: The CI only checks if `gen_vimdoc.py` would change files, and if it does causes a failure. So it would only act as a reminder that it's missing.

But the two other variants of having a bot making the PRs or having a bot that comments on the PR (with in-place edits or uses the checks API for less noise?) sound also good.

**Comment by mjlbach** [comment]
Hmm isn't this done now?

**Comment by muniter** [comment]
It currently runs, https://github.com/neovim/neovim/pull/16091 this PR has been open for 13 days, meaning the docs have been out of date for two weeks? 

> Throwing in a third variant: The CI only checks if `gen_vimdoc.py` would change files, and if it does causes a failure. So it would only act as a reminder that it's missing.
> 

This approach would complement the current job nicely, while reducing instances of out of date docs.
