### ISSUE TITLE
Bug: Filetype autocommands do not work

### ISSUE THREAD

**Issue by oberblastmeister** [neovim/neovim#14000]
### version
```
NVIM v0.5.0-dev+1108-g0450e155d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az36-225

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### os
arch linux

### Steps to reproduce using `nvim -u NORC --noplugin`
1. start neovim
2. run `:autocmd Filetype lua echo 'lua filetype'`
3. edit lua file

### Actual behaviour
there is no echo

### Expected behaviour
there should be echo

### Additional notes
It seems like the autocommand only works when running `set filetype=lua` and doesn't work when running `:setf=lua` which is what `filetype.vim` uses, which might explain why there is no echo when opening the file.

### Testing in `vim`
When doing the same thing in `vim` it works

**Comment by erw7** [comment]
This issue is a FAQ. Please see [FAQ](https://github.com/neovim/neovim/wiki/FAQ#calling-inputlist-echomsg-etc-in-filetype-plugins-and-autocmd-does-not-work).
