### ISSUE TITLE
Some NerdFonts can't display in Neovim 0.5

### ISSUE THREAD

**Issue by WuG978** [neovim/neovim#14015]
- `nvim --version`: 0.5
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: WINDOWS 10
- Terminal name/version: Power Shell 5.1
- `$TERM`: Windows Terminal

My report: Nerd Fonts‘ performance in Neovim 0.5 is not same as that in Neovim 0.4.4. I think something is broken. The following picture is the performance in different version Neovim. I think Neovim_0.5 can't support the colorful nerdfonts. 

###  Behaviour in Neovim 0.5
![WindowsTerminal_28hWWKgYu5](https://user-images.githubusercontent.com/38772075/109163281-2005c600-77b4-11eb-9983-fcb7e2c6ec70.png)

###  Behaviour in Neovim 0.4.4
![WindowsTerminal_1MmWMfM2zL](https://user-images.githubusercontent.com/38772075/109163328-301da580-77b4-11eb-9dc9-43c8abc3a0d5.png)

**Comment by erw7** [comment]
libuv v1.34.1 to 1.39.0 will convert the sargent pair to `U+FFFD`. We need to update libuv for .deps to v1.40.0 or later.

**Comment by zeertzjq** [comment]
Does this bug still exist?
