### ISSUE TITLE
Installation fails due to missing file

### ISSUE THREAD

**Issue by mcctuxic** [neovim/neovim#14012]
- `nvim --version`:host:/home/user>nvim --version
NVIM v0.5.0-dev+1112-ge55ded00c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/user/data/pools/pool00/CVS-Archive/NEOVIM/neovim/build/config -I/home/user/data/pools/pool00/CVS-Archive/NEOVIM/neovim/src -I/home/user/data/pools/pool00/CVS-Archive/NEOVIM/neovim/.deps/usr/include -I/usr/include -I/home/user/data/pools/pool00/CVS-Archive/NEOVIM/neovim/build/src/nvim/auto -I/home/user/data/pools/pool00/CVS-Archive/NEOVIM/neovim/build/include
Compiled by user@host

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
- 
- `vim -u DEFAULTS` (version: ) behaves differently? 
- n.a.
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
Since some days installation of github sources fails due to missing file 'callbacks.lua'
### Expected behaviour
Installation of github sources does not fail due to missing file 'callbacks.lua'

- `vim -u DEFAULTS` (version: ) behaves differently? .n.a.
- Operating system/version: GENTOO Linux rolling releas, daily updated
- Terminal name/version:rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`
.n.a
```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
n.a.
```

**Comment by klooj** [comment]
did you try `make distclean` before make && make install?

**Comment by mcctuxic** [comment]
I am using a build-script which calls:

make clean install

so, yes it cleans and no it does not distclean. I will
try distclean and report back.

**Comment by mcctuxic** [comment]
Ok, distclean works for me.

How can I decide, when distclean is necessary and when
clean is sufficient?

**Comment by clason** [comment]
> Ok, distclean works for me. How can I decide, when distclean is necessary and when clean is sufficient?
> […](#)

Anytime an update adds or removes a file (the file list is cached by CMake, and this cache is only refreshed if you delete it via `make distclean` (or `git clean -fdx`, of course); see https://github.com/neovim/neovim/wiki/Building-Neovim#building

(Another, more flippant, answer to that question would be "whenever `make clean` is not enough and the build still fails. That's how _I_ do it ;))

**Comment by mcctuxic** [comment]
The last sentence is one the most pragmatic answers to my questions I ever 
got. Put a big smile on my face! Thank you - will do as you do!

**Comment by mjlbach** [comment]
Closing :)
