### ISSUE TITLE
LSP functions do not respect silent option

### ISSUE THREAD

**Issue by khaveesh** [neovim/neovim#14016]
- `nvim --version`: v0.5.0 latest nightly
- Operating system/version: macOS Big Sur 11.1
- Terminal name/version: kitty 0.19.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
Use lspconfig to initialize some server and execute the following command on a non-function piece of code
:silent! lua vim.lsp.buf.signature_help()
```

### Actual behaviour

Since there is no signature help available, it will print out the same and appear in the messages history.

### Expected behaviour

Since, `silent` option is given, it should respect that and not print anything out or pollute the messages history.

Like how, `:silent lua print('hello')` works vs. `:lua print('hello')`.

**Comment by mjlbach** [comment]
This isn't a bug, it's callback based so you're not seeing the print from the actual command, but the triggered callback.
