### ISSUE TITLE
term.c. error: undeclared (first use in this function)

### ISSUE THREAD

**Issue by g36054** [neovim/neovim#1402]
/run/media/agriffith/37634a60-9c12-447d-9a87-602dd7559921/code/neovim/src/nvim/term.c: In function ‘clear_termcodes’:
/run/media/agriffith/37634a60-9c12-447d-9a87-602dd7559921/code/neovim/src/nvim/term.c:2772:3: error: ‘BC’ undeclared (first use in this function)
   BC = (char *)empty_option;
   ^
/run/media/agriffith/37634a60-9c12-447d-9a87-602dd7559921/code/neovim/src/nvim/term.c:2773:3: error: ‘UP’ undeclared (first use in this function)
   UP = (char *)empty_option;
   ^
/run/media/agriffith/37634a60-9c12-447d-9a87-602dd7559921/code/neovim/src/nvim/term.c:2774:3: error: ‘PC’ undeclared (first use in this function)
   PC = NUL;                     /* set pad character to NUL */
   ^
/run/media/agriffith/37634a60-9c12-447d-9a87-602dd7559921/code/neovim/src/nvim/term.c:2775:3: error: ‘ospeed’ undeclared (first use in this function)
   ospeed = 0;
   ^
make[3]: *** [src/nvim/CMakeFiles/nvim.dir/term.c.o] Error 1
make[3]: Leaving directory `/run/media/agriffith/37634a60-9c12-447d-9a87-602dd7559921/code/neovim/build'
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make[2]: Leaving directory `/run/media/agriffith/37634a60-9c12-447d-9a87-602dd7559921/code/neovim/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/run/media/agriffith/37634a60-9c12-447d-9a87-602dd7559921/code/neovim/build'
make: *** [nvim] Error 2

**Comment by jszakmeister** [comment]
There's been no response on this from @g36054 since November, so I'm closing this.
