### ISSUE TITLE
Syntax highlighting is not applied correctly for ::= in Makefiles

### ISSUE THREAD

**Issue by vdot0x23** [neovim/neovim#14024]
- `nvim --version`:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/via4xnlqpknjfh4afxiv3dvwm28mxva2-neovim-unwrapped-0.4.4/share/nvim
"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
Yes

- Operating system/version : NixOS 21.05pre272380.f6b5bfdb470 (Okapi)
- Terminal name/version: alacritty 0.7.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Open a Makefile, write e.g. `A ::= 1` and notice that syntax highlighting is missing while it is present for e.g. `A = 1`.

### Actual behaviour
Syntax highlighting is missing for that variable.
![image](https://user-images.githubusercontent.com/40716069/109353184-e8f6e980-7873-11eb-97bf-d5920b59d85f.png)

### Expected behaviour
Syntax highlighting.
![image](https://user-images.githubusercontent.com/40716069/109353206-f2805180-7873-11eb-8f01-821175c4dcfe.png)

### References

https://www.gnu.org/software/make/manual/html_node/Setting.html#Setting

**Comment by clason** [comment]
If vim behaves differently (what version?), they probably just have a newer version of the `syntax/make.vim` file that can be ported. It may be as easy as just overwriting neovim's version of the file with the latest one from vim. 

Do you want to make a PR for it? In the description, you should reference the commit that bumped the version in vim (probably https://github.com/vim/vim/commit/2cfb4a2a7248eeb40112bb482ab5b15f01b20433); @janlazo can tell you more how best to format a runtime patch for easy merging.

**Comment by vdot0x23** [comment]
> If vim behaves differently (what version?), they probably just have a newer version of the `syntax/make.vim` file that can be ported. It may be as easy as just overwriting neovim's version of the file with the latest one from vim.
> 

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 01 1980 00:00:00)
Included patches: 1-1522
Compiled by nixbld
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         -python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "
/nix/store/l0inn8dpl9l7j249ry88y5k085r2hma3-vim-8.2.1522/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,--as-needed -o vim        -lm -ltinfo  -ldl           
```
for reference

> Do you want to make a PR for it? In the description, you should reference the commit that bumped the version in vim (probably [vim/vim@2cfb4a2](https://github.com/vim/vim/commit/2cfb4a2a7248eeb40112bb482ab5b15f01b20433)); @janlazo can tell you more how best to format a runtime patch for easy merging.

Yeah, would love to hear from Jan although I'm not a git wizard and regexes scare me. I might learn something, who knows ;)

**Comment by clason** [comment]
> Yeah, would love to hear from Jan although I'm not a git wizard and regexes scare me. I might learn something, who knows ;)

Start with just forking neovim, creating a branch (`git checkout -b update-make`), overwriting the `make.vim` with the one from vim, commiting the change, `git push` (it'll tell you what you have to type to make that work ;)), then visit github on your fork and press the "create PR button". You can look at https://github.com/neovim/neovim/pull/13718 as a model for a recent runtime update PR that got merged.

**Comment by mhinz** [comment]
Fixed on master (probably due to https://github.com/neovim/neovim/pull/14424)
