### ISSUE TITLE
Setting g:completion_chain_complete_list with source using cited example

### ISSUE THREAD

**Issue by cds-amal** [neovim/neovim#14033]
- `nvim --version`: 
NVIM v0.5.0-dev+1115-gc1fbc2ddf
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1614489585930.local

- `vim -u DEFAULTS` (version: ) behaves differently? NO
- Operating system/version: OS X Big Sur - Darwin lap 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
- Terminal name/version: iTerm2
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`
1. setup sample
```
$ cat << EOF > sample.vim
" taken from :h completion-nvim
"
" You can take a step further to specify different 'scope' of different
" filetypes. 'scope' is literally syntax in your file. Say that you want
" different completion lists in comments and function calls, strings,
" etc, you can do that easily. Here is an example
"
let g:completion_chain_complete_list = {
    \ 'lua': [
    \    'string': [
    \        {'mode': '<c-p>'},
    \        {'mode': '<c-n>'}],
    \    'func' : [
    \        {'complete_items': ['lsp']}],
    \    'default': [
    \       {'complete_items': ['lsp', 'snippet']},
    \       {'mode': '<c-p>'},
    \       {'mode': '<c-n>'}],
    \],
    \ 'default' : {
    \   'default': [
    \       {'complete_items': ['lsp', 'snippet']},
    \       {'mode': '<c-p>'},
    \       {'mode': '<c-n>'}],
    \   'comment': []
    \   }
    \}

EOF
$ nvim -u NORC sample.vim
```

2. source buffer from neovim 

```
:so %
```

### Actual behaviour
```
Error detected while processing [.snip.]/sample.vim:
line    8:
E696: Missing comma in List: : [        {'mode': '<c-p>'},        {'mode': '<c-n>'}],    'func' : [        {'complete_items': ['lsp']}],    'default': [       {'complete_items': ['l
sp', 'snippet']},       {'mode': '<c-p>'},       {'mode': '<c-n>'}],], 'default' : {   'default': [       {'complete_items': ['lsp', 'snippet']},       {'mode': '<c-p>'},       {'mo
de': '<c-n>'}],   'comment': []   }}
E15: Invalid expression: { 'lua': [    'string': [        {'mode': '<c-p>'},        {'mode': '<c-n>'}],    'func' : [        {'complete_items': ['lsp']}],    'default': [       {'co
mplete_items': ['lsp', 'snippet']},       {'mode': '<c-p>'},       {'mode': '<c-n>'}],], 'default' : {   'default': [       {'complete_items': ['lsp', 'snippet']},       {'mode': '<
c-p>'},       {'mode': '<c-n>'}],   'comment': []   }}
```

### Expected behaviour
```
Should parse Example specified in help.txt
```

**Comment by mjlbach** [comment]
This should be filed on the completion.nvim repo

https://github.com/nvim-lua/completion-nvim

**Comment by mjlbach** [comment]
This should be filed on the completion.nvim repo

https://github.com/nvim-lua/completion-nvim
