### ISSUE TITLE
LSP: default diagnostic highlight groups not created

### ISSUE THREAD

**Issue by clason** [neovim/neovim#14034]
Background: Questions on Gitter about "how do I enable underline for diagnostics", which should be enabled by default.

Tracing this back, it seems that [`vim.lsp.diagnostic._define_default_signs_and_highlights`](https://github.com/neovim/neovim/blob/c1fbc2ddf15b2f44b615f90b2511349ab974cb83/runtime/lua/vim/lsp/diagnostic.lua#L912) doesn't actually define these groups _during startup_. (Before refuting this, make sure these highlight groups aren't actually defined by your colorscheme as well.)

Tracing further, the issue is that the `highlight` inside this `vim.cmd` never gets executed: https://github.com/neovim/neovim/blob/c1fbc2ddf15b2f44b615f90b2511349ab974cb83/runtime/lua/vim/highlight.lua#L12

Which is weird, since 

1. replacing that `vim.cmd` by `print`;
2. replacing that `string.format(...)` by `echo 'foo'`;
3. manually calling `:lua vim.lsp.diagnostic._define_default_signs_and_highlights()` while neovim is running

all show the expected behavior.

**Comment by clason** [comment]
@tjdevries @bfredl

**Comment by ruffson** [comment]
I have the same problem: no underline on errors and warning. I do see them when I do `:lua vim.lsp.diagnostic._define_default_signs_and_highlights()`. 

So I had to put ` autocmd CursorHold * lua vim.lsp.diagnostic._define_default_signs_and_highlights()` in my `init.vim`. 
Thank you for this issue, I was going mad not seeing __where__ the mistake is in a line.

**Comment by mjlbach** [comment]
@clason I can't reproduce this (ignore the garish unset color scheme)

<img width="495" alt="image" src="https://user-images.githubusercontent.com/13316262/111192833-bdb01200-8576-11eb-934c-e30649a7ea36.png">
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/13316262/111192860-c7d21080-8576-11eb-8b18-53c0ffe6bb70.png">

**Comment by comfortablynick** [comment]
After I set my colorscheme, all the highlight groups are cleared unless I set them (I guess this is expected). I don't know what the best way to do this is, but this is what I've been using:

```lua
local api = vim.api

function set_hl()
  local ns = api.nvim_create_namespace("hl-lsp")
  api.nvim_set_hl(ns, "LspDiagnosticsDefaultError", {fg = "#ff5f87"})
  api.nvim_set_hl(ns, "LspDiagnosticsDefaultWarning", {fg = "#d78f00"})
  api.nvim_set_hl(ns, "LspDiagnosticsDefaultInformation", {fg = "#d78f00"})
  api.nvim_set_hl(ns, "LspDiagnosticsDefaultHint", {fg = "#ff5f87", bold = true})
  api.nvim_set_hl(ns, "LspDiagnosticsUnderlineError",
                  {fg = "#ff5f87", sp = "#ff5f87", undercurl = true})
  api.nvim_set_hl(ns, "LspDiagnosticsUnderlineWarning",
                  {fg = "#d78f00", sp = "#d78f00", undercurl = true})
  api.nvim_set_hl(ns, "LspReferenceText", {link = "CursorColumn"})
  api.nvim_set_hl(ns, "LspReferenceRead", {link = "LspReferenceText"})
  api.nvim_set_hl(ns, "LspReferenceWrite", {link = "LspReferenceText"})
  api.nvim__set_hl_ns(ns) -- This changed to unstable API
end
```

My highlights recently disappeared which led me to find that `nvim_set_hl_ns()` had been changed to `nvim__set_hl_ns()`. Interestingly I never saw an error, it just stopped working.

> So I had to put ` autocmd CursorHold * lua vim.lsp.diagnostic._define_default_signs_and_highlights()` in my `init.vim`.

@ruffson Why a `CursorHold` autocmd? I have my custom highlights on a `ColorScheme` autocmd and they work fine. Not sure if you are trying to do something different.

**Comment by ruffson** [comment]
> @ruffson Why a `CursorHold` autocmd? I have my custom highlights on a `ColorScheme` autocmd and they work fine. Not sure if you are trying to do something different.

Oh just because I'm a noob and don't know what I'm doing :) What is a better way? Just replace `CursorHold` with `ColorScheme`?

**Comment by clason** [comment]
Update: the issue arises when you use a color scheme that contains the line 
```vim
hi clear
```
in the beginning (to allow switching color schemes cleanly). Removing that line (unsurprisingly) sets the default highlight groups correctly.

**Comment by koalp** [comment]
> Update: the issue arises when you use a color scheme that contains the line
> 
> ```viml
> hi clear
> ```
> 
> in the beginning (to allow switching color schemes cleanly). Removing that line (unsurprisingly) sets the default highlight groups correctly.

So is this an issue with colorscheme that do not define highlighting for lsp highlight groups rather than a neovim issue ? Do you think it could (and should) be solved in neovim or should we open issues in colorscheme repositories stating that neovim is supported ? (after 0.5 release ?)

**Comment by clason** [comment]
I think this is an issue with how (or whether) neovim defines these groups. Note that it's perfectly fine to define these groups yourself _after_ setting a color scheme, so it's not necessarily a defect in color schemes not do define it.

It's just not clear (heh) that this way of setting default highlight groups is possible (or if so, reasonable) so that it a) circumvents color schemes that clear all other highlights, b) don't overwrite highlight groups if they _are_ set by color scheme or user, and c) don't involve messy `autocommands`.

**Comment by clason** [comment]
Closing as duplicate of #12579 (🤦 for not finding this when creating this issue)
