### ISSUE TITLE
Pasting from the clipboard takes me out of my gnome session

### ISSUE THREAD

**Issue by tpabst** [neovim/neovim#14031]
- `nvim --version`: v0.4.3 and v.0.4.4
- `vim -u DEFAULTS` (version: 8.1) behaves differently? yes, I still login with vim
- Operating system/version: Ubuntu 20.04.2 LTS
- Terminal name/version: append to all terminals I tried without tmux: Gnome terminal 3.36.2 / urxvt v9.22
- `$TERM`: xterm-256color / rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`
copy any text to clipboard, then
```
nvim -u NORC
"+p
```
did not append with vim and vim -u NORC

### Actual behaviour
I am ejected from my gnome session.
Need to log in

### Expected behaviour
Paste the text from the clipboard
(and at least, stay on my session)
```

**Comment by tpabst** [comment]
I found a workaround, by disabling Wayland
[](https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-20-04-desktop)

**Comment by bfredl** [comment]
sounds like a bug in mutter-wayland when used with wl-clipboard, not actionable in this repo.

**Comment by glacambre** [comment]
Yep, sounds like a gnome bug.
