### ISSUE TITLE
Terminal emulator flashes previous command when typing

### ISSUE THREAD

**Issue by dbatten5** [neovim/neovim#14038]
- `nvim --version`: NVIM v0.4.4
- `vim -u DEFAULTS` (version: v0.4.4) behaves differently? yes, the bug doesn't appear
- Operating system/version: Mac OSX 10.15.7 
- Terminal name/version: iTerm2 3.4.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Unfortunately I haven't been able to reproduce the issue in `nvim -u NORC` so it's clearly an issue with my setup, I'm just at a bit of a loss as to where to start with it. 

### Actual behaviour

The steps I take to reproduce it are:
- Open nvim
- Open the terminal emulator
- Enter into a "subshell", eg. running `docker run -it ubuntu bash`
- Observe that as I type, the previous command I've run flashes briefly on the screen

https://user-images.githubusercontent.com/17271241/109479483-540e0f00-7a72-11eb-83d3-c3f1c2fac655.mov

### Expected behaviour

The flashing shouldn't occur.

**Comment by glacambre** [comment]
I remember experiencing this some time ago and it stopped. Can you still reproduce this with [nightly](https://github.com/neovim/neovim/releases/tag/nightly)?

**Comment by dbatten5** [comment]
@glacambre ah that seems to fix the issue. would you recommend upgrading my neovim in that case?

**Comment by glacambre** [comment]
@dbatten5 I don't recommend it but I don't recommend against either :). I've been using nightly for a few years now and have rarely experienced breakage. I think this has been the case for most people.
