### ISSUE TITLE
Add ability to renderer markdown in pop-ups instead of displaying it raw

### ISSUE THREAD

**Issue by VVKot** [neovim/neovim#14032]
For example, `vim.lsp.buf.hover()` would display raw markdown instead of turning `*foo*` into *foo* and `**bar**` into **bar**. CoC already does it after https://github.com/neoclide/coc.nvim/pull/2518, I would expect doing something similar (piping the text through some Lua markdown library) to not be hard?

- `nvim --version`: nightly
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Any
- Terminal name/version: Any
- `$TERM`: Any

**Comment by clason** [comment]
That's what `vim.lsp.util.fancy_floating_markdown` is for, isn't it?

**Comment by mjlbach** [comment]
This issue has come up already, but we should leave it open. See: https://github.com/neovim/neovim/pull/13803

I don't think we're going to bundle a lua library that does markdown processing to strip glyphs which would normally not be rendered in a markdown viewer. What I was going to do was implement syntax rules for conceal such that the vim conceal rules would not show them (similar to what's done in https://github.com/plasticboy/vim-markdown). Although even `\` is not concealed by default in that plugin https://github.com/plasticboy/vim-markdown/pull/515

FWIW we *do* render markdown, it's just vim's built-in markdown syntax rules don't conceal most characters you'd want concealed by default.

**Comment by gshpychka** [comment]
@mjlbach to be clear, have you rethought that approach since? Or do you still plan on going that route?

**Comment by mjlbach** [comment]
WDYM? No, I just haven't gotten around to implementing it yet.

The approach here would work for this particular issue if we added a rule for nbsp;

https://github.com/neovim/neovim/pull/13803/files

**Comment by gshpychka** [comment]
Got it, thanks.
