### ISSUE TITLE
Update tree-sitter to v0.19.0

### ISSUE THREAD

**Issue by tjdevries** [neovim/neovim#14044]
With https://github.com/tree-sitter/tree-sitter/pull/943 merged, we should probably update to latest version of tree sitter. This represents a breaking change to parsers compiled before and after this (so I think it's important to get it done before 0.5 probably).

cc @vigoux @bfredl 

I have tried this on my local machine but for some reason even when I recompile things with stuff like `:TSUpdate c` or `:TSInstall C` from scratch, I get that the version is too old, so I'm not sure why that is... Maybe one of you knows why that would be?

**Comment by maxbrunsfeld** [comment]
> I get that the version is too old, so I'm not sure why that is

Yeah, the parsers actually need to be regenerated with a Tree-sitter CLI version >= 0.19. I'll be taking care of this task this week, for all of the Tree-sitter parsers in the `tree-sitter` github org. Sorry for the awkwardness; I think this will be last breaking ABI change for the foreseeable future.

**Comment by tjdevries** [comment]
https://github.com/neovim/neovim/pull/14045

**Comment by bfredl** [comment]
hmm how does TSInstall work? just pulling the latest version from the tree-sitter/ repos ?

**Comment by tjdevries** [comment]
Ah, that explains it -- I had missed that part of the equation @maxbrunsfeld .

No worries :) I have my own grammar locally for a few things and I was able to get those to run, so I was confused why the other ones weren't working.

**Comment by tjdevries** [comment]
@bfredl yeah, something like that -- makes sense that it didn't work then though because of the cli version required when generating the grammar itself.

**Comment by bfredl** [comment]
Hmm you can use `TSInstallFromGrammar`, but then you need the tree-sitter cli obviously

**Comment by bfredl** [comment]
TBH we should probably just do this, but makes sense to wait to merge until @maxbrunsfeld has actually updated the parsers, please ping us again when you do :)

**Comment by theHamsta** [comment]
`TSInstallFromGrammar` with 0.19.0 CLI strangly only gives me ABI version 12.

**Comment by bfredl** [comment]
are you sure it is the one active in `$PATH` @theHamsta  ?

**Comment by theHamsta** [comment]
@bfredl is fixed now. After a clean build of Neovim.

**Comment by glepnir** [comment]
> Hmm you can use `TSInstallFromGrammar`, but then you need the tree-sitter cli obviously

confirm can work

**Comment by cloggier** [comment]
Same here, although couldn't use `ensure_installed` to install parsers as they did not build from source then (I am correct here?).

Having have built all parsers with `TSInstallFromGrammar`, how will updating them work now? Will future updates come from binaries as if I did `TSInstall`? Or will `TSUpdate` continue installing them from source?

**Comment by theHamsta** [comment]
TSInstallFromGrammar will always work when you have the tree-sitter CLI installed and the CLI matches your runtime. It includes the step grammar.js -> C files.

TSInstall right now points to C files of parsers that used the old CLI. At some point (probably when the bundled version of nvim switches to 0.19.0) we will update the pines to those parsers that already updated to 0.19.0

**Comment by maxbrunsfeld** [comment]
I've updated a bunch of the grammars to 0.19. I'll do the rest of the ones in the Tree-sitter org tomorrow.

**Comment by lucastrvsn** [comment]
Workaround for homebrew users:

1. Uninstall tree-sitter@0.19.1 ignoring neovim dependency.

```sh
brew uninstall tree-sitter --ignore-dependencies
```

2. Extract the formula from tree-sitter@0.18.3.

```sh
brew extract --version=0.18.3 tree-sitter homebrew/cask
```

3. Install the tree-sitter 0.18.3

```sh
brew install tree-sitter@0.18.3
```

3. And, for now, pin the tree-sitter version to 0.18.3.

```
brew pin tree-sitter
```

**Comment by hungrybirder** [comment]
> brew pin tree-sitter

Save my life. hahaha

**Comment by megalithic** [comment]
Came here to echo @hungrybirder and say that @lucastrvsn saved the day for us homebrew users. 🙌

**Comment by TC72** [comment]
I'm on an M1 Mac, this line fails for me:
```brew install tree-sitter@0.18.3```

Console Crash Reports shows npm is failing with this message:
```Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)```

I tried ```:TSInstallFromGrammar all``` after a fresh install of neovim but it gave errors as well:
```Error during "tree-sitter generate"```

FML

**Comment by theHamsta** [comment]
@TC72 you can try nvim-treesitter/nvim-treesitter#1000 . Most of the parsers won't need a `:TSInstallFromGrammar` and you can just use `:TSInstall` to get parsers for 0.19.X runtime.

**Comment by TC72** [comment]
Thanks @theHamsta but I'm completely lost. I use git to checkout some of the treesitter grammars and was able to use ```:TSInstallFromGrammar``` but checkhealth still had issues so tried ```:TSInstall``` for a few languages, still had issues. Followed what checkhealth told me and did ```:TSUpdate lua``` for example. checkhealth has this now, I'm getting nowhere:

```
  - lua            x x x x
  ```

**Comment by lucastrvsn** [comment]
> Workaround for homebrew users:
> 
> 1. Uninstall tree-sitter@0.19.1 ignoring neovim dependency.
> 
> ```sh
> brew uninstall tree-sitter --ignore-dependencies
> ```
> 
> 2. Extract the formula from tree-sitter@0.18.3.
> 
> ```sh
> brew extract --version=0.18.3 tree-sitter homebrew/cask
> ```
> 
> 3. Install the tree-sitter 0.18.3 (will compile everything)
> 
> ```sh
> brew install tree-sitter@0.18.3
> ```
> 
> 3. And, for now, pin the tree-sitter version to 0.18.3.
> 
> ```
> brew pin tree-sitter
> ```

Hey! I'm on m1 mac as well. This is what I did to get it to work https://github.com/neovim/neovim/issues/14044

**Comment by lucastrvsn** [comment]
> Thanks @theHamsta but I'm completely lost. I use git to checkout some of the treesitter grammars and was able to use ```:TSInstallFromGrammar``` but checkhealth still had issues so tried ```:TSInstall``` for a few languages, still had issues. 
> 
> Followed what checkhealth told me and did ```:TSUpdate lua``` for example. checkhealth has this now, I'm getting nowhere:
> 
> ```
>   - lua            x x x x
>   ```
> 
> There's something very wrong with my system if node is failing to let me run ```brew install tree-sitter@0.18.3```.
> 

Hey! I'm on m1 mac as well. This is what I did to get it to work

https://github.com/neovim/neovim/issues/14044

**Comment by TC72** [comment]
@lucastrvsn thanks for replying, I did try to follow your instructions but this failed:
```brew install tree-sitter@0.18.3```
In the console crash reports there was an issue with node, I'm still trying to fix that.

**Comment by TC72** [comment]
I'm following the steps you posted exactly. I've now managed to get the homebrew version of node to install and work by doing this:
brew uninstall node
brew update
brew reinstall icu4c
brew install node

But trying to install tree-sitter again now gives me these errors:
```
script/build-wasm

script/build-wasm: line 102: 18335 Killed: 9               $emcc -s WASM=1 -s TOTAL_MEMORY=33554432 -s ALLOW_MEMORY_GROWTH=1 -s MAIN_MODULE=2 -s NO_FILESYSTEM=1 -s NODEJS_CATCH_EXIT=0 -s NODEJS_CATCH_REJECTION=0 -s EXPORTED_FUNCTIONS=@${web_dir}/exports.json $emscripten_flags -std=c99 -D 'fprintf(...)=' -D NDEBUG= -I lib/src -I lib/include --js-library ${web_dir}/imports.js --pre-js ${web_dir}/prefix.js --post-js ${web_dir}/binding.js --post-js ${web_dir}/suffix.js lib/src/lib.c ${web_dir}/binding.c -o target/scratch/tree-sitter.js```

**Comment by TC72** [comment]
I've uninstalled python, node and redone everything from scratch, node installed from brew and python installed with pyenv.
I'm now able to `brew install tree-sitter@0.18.3` but when I run `brew pin tree-sitter` I get:
```
Error: tree-sitter not installed
```

**Comment by dahmc** [comment]
> I've uninstalled python, node and redone everything from scratch, node installed from brew and python installed with pyenv.
> I'm now able to `brew install tree-sitter@0.18.3` but when I run `brew pin tree-sitter` I get:
> 
> ```
> Error: tree-sitter not installed
> ```

You have to do
```
brew pin tree-sitter@0.18.3
```

**Comment by TC72** [comment]
Thanks @dahmc.
That worked and now when I try to launch nvim I get:
```
dyld: Library not loaded: /opt/homebrew/opt/tree-sitter/lib/libtree-sitter.0.dylib
  Referenced from: /opt/homebrew/bin/nvim
  Reason: image not found
zsh: abort      nvim
```
This is exactly what I did from no neovim installed:
```
 brew install --HEAD neovim
 brew uninstall tree-sitter --ignore-dependencies
 brew extract --version=0.18.3 tree-sitter homebrew/cask\n
 brew install tree-sitter@0.18.3
 brew pin tree-sitter@0.18.3
 ```

**Comment by ttys3** [comment]
```bash
❯ nvim --version
NVIM v0.5.0-dev+1155-g054eb31dc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

linked with ts 0.19.1 and with ArchLinux `tree-sitter 0.19.3`


then run 

```vim
:TSUninstall all
:TSInstallFromGrammar maintained
```

things got OK now.

**Comment by mjlbach** [comment]
This was closed by https://github.com/neovim/neovim/pull/14076

**Comment by patlux** [comment]
I had the same issue on my Mac mini m1: `/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch: supported between 9 and 12, found 13`

1. I uninstalled `neovim` via `brew`:

```bash
brew uninstall neovim
```

2. installed it directly from source:

```
git clone https://github.com/neovim/neovim
cd neovim
brew install ninja libtool automake cmake pkg-config gettext
make CMAKE_BUILD_TYPE=Release
sudo make install
```

3. Run ```:TSInstallFromGrammar all``` and it works as expected.

**Comment by theHamsta** [comment]
@patlux brew has the newest tree-sitter version. Just try a "brew upgrade" and maybe an explicit reinstall of nvim and tree-sitter with --HEAD

**Comment by annguyenwasd** [comment]
> I had the same issue on my Mac mini m1: `/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch: supported between 9 and 12, found 13`
> 
> 1. I uninstalled `neovim` via `brew`:
> 
> ```shell
> brew uninstall neovim
> ```
> 
> 1. installed it directly from source:
> 
> ```
> git clone https://github.com/neovim/neovim
> cd neovim
> brew install ninja libtool automake cmake pkg-config gettext
> make CMAKE_BUILD_TYPE=Release
> sudo make install
> ```
> 
> 1. Run `:TSInstallFromGrammar all` and it works as expected.

Thanks @patlux patl
I just follow instruction and it's worked for me

**Comment by patlux** [comment]
@theHamsta I had a error while installing neovim again via brew. Something like `Corefoundation.h not found`. It worked some time ago and now it don't. I just don't want to waste my time with this. But thanks.

**Comment by particledecay** [comment]
This is still an issue for me on Big Sur. I tried [the workaround](https://github.com/neovim/neovim/issues/14044#issuecomment-790242256), and it failed on the step for installing tree-sitter 0.18.3.

```
❯ brew install tree-sitter@0.18.3
==> Installing tree-sitter@0.18.3 from homebrew/cask
==> Downloading https://github.com/tree-sitter/tree-sitter/archive/v0.18.3.tar.gz
Already downloaded: /Users/particledecay/Library/Caches/Homebrew/downloads/0d6bd76f45bdb161f37d6aada0de628b1ba3f4d16728443bd8d6033510ae5a2a--tree-sitter-0.18.3.tar.gz
==> make
==> make install PREFIX=/usr/local/Cellar/tree-sitter@0.18.3/0.18.3
==> npm install -ddd --build-from-source --cache=/Users/particledecay/Library/Caches/Homebrew/npm_cache
==> script/build-wasm
Last 15 lines from /Users/joelinux/Library/Logs/Homebrew/tree-sitter@0.18.3/04.build-wasm:
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libcompiler_rt.a... (this will be cached in "/private/tmp/tree-sitterA0.18.3-20210515-59707-1qjkonk/tree-sitter-0.18.3/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libcompiler_rt.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libc++-noexcept.a... (this will be cached in "/private/tmp/tree-sitterA0.18.3-20210515-59707-1qjkonk/tree-sitter-0.18.3/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libc++-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libc++abi-noexcept.a... (this will be cached in "/private/tmp/tree-sitterA0.18.3-20210515-59707-1qjkonk/tree-sitter-0.18.3/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libc++abi-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libdlmalloc.a... (this will be cached in "/private/tmp/tree-sitterA0.18.3-20210515-59707-1qjkonk/tree-sitter-0.18.3/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libdlmalloc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libc_rt_wasm.a... (this will be cached in "/private/tmp/tree-sitterA0.18.3-20210515-59707-1qjkonk/tree-sitter-0.18.3/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libc_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/pic/libsockets.a... (this will be cached in "/private/tmp/tree-sitterA0.18.3-20210515-59707-1qjkonk/tree-sitter-0.18.3/.brew_home/.emscripten_cache/sysroot/lib/wasm32-emscripten/pic/libsockets.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/private/tmp/tree-sitterA0.18.3-20210515-59707-1qjkonk/tree-sitter-0.18.3/.brew_home/.emscripten_cache/generated_struct_info.json" for subsequent builds)
cache:INFO:  - ok
emcc: error: undefined exported symbol: "abort" [-Wundefined] [-Werror]

READ THIS: https://docs.brew.sh/Troubleshooting```

**Comment by particledecay** [comment]
Scratch that, it appears the latest version (0.19.4) now works.

**Comment by eddyekofo94** [comment]
> Scratch that, it appears the latest version (0.19.4) now works.

It appears not to be working for me still
