### ISSUE TITLE
Feature: timers

### ISSUE THREAD

**Issue by splinterofchaos** [neovim/neovim#1404]
A couple of places, I've seen where this would be useful: vim-search-pulse and lerp/linepulse, both of which use `:sleep`, the [first original commit](https://github.com/Floobits/vim/commit/17f528f4bd40970e2f009346257c006236907629) of Floobits/vim, and [this google groups post](https://groups.google.com/forum/#!topic/neovim/VxL0XMu3x18). I even decided to try out xolox/vim-easytags today and found in `autoload/xolox/easytags.vim` a bunch of timers being initialized! *(Update: ok, on closer inspection, these watch the time, not spawn events, but that still may be useful.)* It seems to me that time and intervals are basic tools that rarely, but more often than one might think, are needed.

I have a couple of (probably conflicting) ideas about how this could be done. 

(A) We could have a command `:delay {time} {expr}` which would stop sourcing a file for `time` milliseconds, and then `:exe {expr}`. That avoids any "inversion of control" problems, though I don't know how well that would work with the current codebase.

(B) We could do something similar to job control--have a `timerstart("name", {time})` function that returns a timer id and executes an `autocmd` (`TimerActivity`?) with `name`. The `autocmd` would have to call `timerstart()` again to repeat, or we could have an `intervalstart("name", {time})` with the same concept, but executing every `{time}` milliseconds. Obviously, we'd need a `timerstop({id})` as well.

I haven't looked much into how libuv's timers worked yet, but I figured if I were to even spend my time, I should at least see if this feature is even wanted.

**Comment by BohrShaw** [comment]
Vim had add timers support: https://github.com/vim/vim/commit/975b5271eed4fa0500c24a8f37be0b1797cb9db7
