### ISSUE TITLE
Problem with detecting background value on XTerm, URxvt, gnome-terminal

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#14058]
```
 /usr/bin/nvim --version
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-8risgn/neovim-0.5.0+ubuntu2+git202103040319-6995fad26-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-8risgn/neovim-0.5.0+ubuntu2+git202103040319-6995fad26-d569569c9/build/config -I/build/neovim-8risgn/neovim-0.5.0+ubuntu2+git202103040319-6995fad26-d569569c9/src -I/build/neovim-8risgn/neovim-0.5.0+ubuntu2+git202103040319-6995fad26-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-8risgn/neovim-0.5.0+ubuntu2+git202103040319-6995fad26-d569569c9/build/src/nvim/auto -I/build/neovim-8risgn/neovim-0.5.0+ubuntu2+git202103040319-6995fad26-d569569c9/build/include
Compiled by buildd@lgw01-amd64-033

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Actual behaviour
Neovim cannot detect white background from terminal. 

![image](https://user-images.githubusercontent.com/11404453/110031750-96b43d80-7d37-11eb-99da-19c4c074a202.png)
```
env -i TERM=ansi-256color /usr/bin/nvim -U NORC +'se bg'
# shows background=dark
```
```
$ echo $TERM
xterm-256color
$ /usr/bin/nvim -U NORC +'se bg'
# shows background=dark
```
### Expected behaviour
`&bg` should be equal to `light`.

See https://github.com/neovim/neovim/pull/9708 from two years ago - isn't it a regression?

What else information can I add to help?

**Comment by glacambre** [comment]
I can't reproduce this bug with Kitty 0.19.3. Do xterm/urxvt/gnome-terminal support fetching background color?

**Comment by przepompownia** [comment]
How to verify the existence of this support?

I also can't reproduce it on Kitty 0.19.3.

**Comment by przepompownia** [comment]
Another experience after installing kitty

- when on **xterm** I set `export TERM=xterm-kitty` then `&bg` is `light` and real background is light,
- when on **urxvt** I set `export TERM=xterm-kitty` then `&bg` is `dark` (not as expected) but real background is light.

**Comment by erw7** [comment]
It seems to me that this is expected behavior from the implementation. The reason is that the result of background detection by `tui` is set after `VimEnter`, while `+'se bg'` is executed before that. If you run the following on any terminal, you will not be able to see the results of background detection.

```
nvim -u NORC +'se bg'
```

If you want to see the results of background detection, you need to do the following.

```
nvim -u NORC
:se bg
```

**Comment by przepompownia** [comment]
@erw7 Right: manual displaying this variable after nvim start shows that background is correctly detected. 

Loading colorscheme plugin (that depends on `&bg` value) from `plugin/*.vim` is too early.  Loading it by autocommand on `VimEnter` also turns out to be too early (is the internal autocommand on the same event loaded later?). 

Ath the moment I have not any good practical idea - only hacky way like `autocmd VimEnter * call timer_start(1000, 'LoadColorscheme')`.

**Comment by przepompownia** [comment]
What do you think about triggering additional event after background autodetection?

**Comment by erw7** [comment]
As per the following description of `'h: background'` colorscheme will be reloaded when setting the `background`, so you shouldn't need to do anything when setting the auto-detected value.

> When a color scheme is loaded (the "g:colors_name" variable is set) setting 'background' will cause the color scheme to be reloaded. 

Also, if you want to reload plugins that are related to the value of `&bg` other than colorscheme, you can use `autocmd OptionSet background`.

**Comment by przepompownia** [comment]
I use [plugin that sets the background](https://github.com/jonathanfilip/vim-lucius/blob/master/colors/lucius.vim#L342), not only detects it. It probably should not do that by default. 

I missed `OptionSet`. Using it partially resolve this problem. With
```vim
/usr/bin/nvim -U NORC +'autocmd OptionSet background colorscheme blue' +'autocmd ColorScheme * echoerr 111'
```
colorscheme becomes `blue` as expected but the error message does not appear. Both autocommand work after changing `bg`. 

(in practice it [helps me reload](https://github.com/przepompownia/vim-arctgx/blob/master/bundleConfig/lightline.vim#L54-L61) the statusbar plugin).

For the second, please test this command on Tmux.

**Comment by erw7** [comment]
@przepompownia  You will need to use `++nested` as follows.

```
/usr/bin/nvim -u NORC +'autocmd OptionSet background ++nested colorscheme blue' +'autocmd ColorScheme * echoerr 111'
```

> For the second, please test this command on Tmux.

Yes, I know that it does not work with tmux. It should work by wrapping the `DCS` in `\x1bPtmux;\x1b...\x07\\`, but it doesn't work with tmux so I removed it with 994e40914b37b8b041e296f53aba47ea7cf0118e. I didn't pursue the cause, but now I found that tmux doesn't send `get_bg` to the host terminal if `get_bg` is sent without flushing after `enter_ca_mode`, so I created #14094.

**Comment by erw7** [comment]
@przepompownia Do you really need `'background'` auto-detection? In most of the colorscheme, the `'background'` is set. In that case, the auto-detected `'background'` will be ignored. IMO: Therefore, I think most of the developers don't focus on this feature.
