### ISSUE TITLE
In GNU screen, when `set mouse` includes the current mode, the first escape to leave that mode is lost

### ISSUE THREAD

**Issue by Aneurin** [neovim/neovim#14051]
To clarify, I mean that if `mouse` is `a` or if it's `*i*` and you're in insert mode or `*c*` and you're in command mode then `<Esc>` doesn't return to normal mode, but `<Esc>` `<Esc>` does. Similarly if you're in visual mode and it's `a` or `nv` (I don't think `n` or `v` make sense on their own).

This only happens in screen, not in tmux nor when running directly in the terminal. I don't think it's related to screen's `maptimeout`, because the escape *never* arrives, after any amount of time. Just in case though, I've tried setting `maptimeout` to `0`, `1`, `5`, and `10`, and also leaving it to its default as in the reproduction steps below, to no effect.

----

- `nvim --version`:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-u4YhjF/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-u4YhjF/neovim-0.4.4/build/config -I/build/neovim-u4YhjF/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-u4YhjF/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-u4YhjF/neovim-0.4.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? No. I would have sworn I've seen it behave differently in the past, but I can't confirm that - certainly Vim 8 acts the same way.
- Operating system/version: Ubuntu 20.04, Ubuntu 20.10. This isn't new and I've sen it at least on Debian in the past, but these are the only versions that I've confirmed today
- Terminal name/version: Konsole 20.08.2, xterm 353, probably all
- `$TERM`: `xterm` or `xterm-256color` outside screen, `screen` or `screen-256color` inside. I've also tried resetting it to `xterm` inside screen and it still happens

### Steps to reproduce using `nvim -u NORC`

```
screen -c /dev/null nvim -u NORC
:set mouse=i
cc
<Esc>
```
or
```
screen -c /dev/null nvim -u NORC
:set mouse=c
:
<Esc>
```

### Actual behaviour
NVim is in insert/command mode
### Expected behaviour
NVim is in normal mode

**Comment by erw7** [comment]
This is a problem with GNU screen. GNU screen intercepts mouse sequences from the host terminal for coordinate conversion. In that case, a single `ESC` could be part of a mouse sequence, and the GNU screen will wait for subsequent input. For some reason, timeout is not implemented, and the GNU screen keeps waiting for the next input, so the input is not passed to the neovim side until the next input is received. Therefore, there is nothing that can be done on the neovim side.

**Comment by Aneurin** [comment]
Thanks for the explanation, sounds like this is the impetus I need to give up on screen entirely and switch to tmux full time.

If this is unfixable, could it be added to the FAQ alongside the `maptimeout` information? I spent hours trying to work this out before even determining that it was dependent on mouse mode. It's hard to google because it's buried in a mountain of hits about that other issue. Next to the existing FAQ entry seems like a natural place to look so it could save people in the future quite a lot of time.

**Comment by erw7** [comment]
The FAQ is a wiki, so I think anyone with a github account can edit it. If you think you need it, you can add it to the FAQ.

I made a patch as follows and sent it to the GNU screen bugtracker, so it may be fixed in a future version.

Ref. https://savannah.gnu.org/bugs/?60196

**Comment by Aneurin** [comment]
Thanks. I've added a note to the FAQ which hopefully summarises the issue okay.
