### ISSUE TITLE
Wrong incsearch highlighting when redrawing from timer in cmdline

### ISSUE THREAD

**Issue by gelguy** [neovim/neovim#14064]
- `nvim --version`: NVIM v0.5.0-dev+1115-gc1fbc2ddf
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Windows 10 WSL
- Terminal name/version: wintty
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

autocmd CmdlineChanged * call timer_start(0, {-> execute('redraw')})
```
1. `:h<CR>` to open help file
2. `/with<CR>` search for text
3. `/Bar<CR>` search for another text

### Actual behaviour
When searching for `with`, the `incsearch` highlighting is missing.
When searching for `Bar`, `incsearch` highlights `with` instead of `Bar`.

### Expected behaviour
`incsearch` highlight works as expected.

Bisected to 910bbc3cca796f7fa941e0f6176cd0061de0e01c: ` vim-patch:8.1.2294: cursor pos wrong with concealing and search causes a scroll`

**Comment by glacambre** [comment]
Can't reproduce on nightly/master. @gelguy Can you?

**Comment by gelguy** [comment]
I can reproduce this at latest master (`NVIM v0.5.0-dev+1389-g21645e603`).

Note: the highlights after pressing `<CR>` are correct, the incsearch highlights while typing the search query are wrong.

**Comment by tzachar** [comment]
I can confirm this is still a problem. 
Using  NVIM v0.6.0-dev+119-g68f61b167
