### ISSUE TITLE
Document upgrade for new decoration api from add_highlight

### ISSUE THREAD

**Issue by resolritter** [neovim/neovim#14067]
There are applications for following the position of a highlighted element, e.g. tracking the position of brackets which have been highlighted for the current scope. Comparatively, the applications for using the returned namespace id do not do not seem very useful since it should already be available at the call site.

Not returning the extmark id is bad since it gives the user no option to do something with it, meaning they would need to create a duplicate extmark id for the same position.

At the very least this API should return both values, if not only the extmark id.

**Comment by bfredl** [comment]
It is better to use `nvim_buf_set_extmark` for this. Though we need to properly document the upgrade path.
