### ISSUE TITLE
NeoVim fails to get Super (aka winkey)+Arrows-keys combination 

### ISSUE THREAD

**Issue by msva** [neovim/neovim#14077]
- `nvim --version`:
```NVIM v0.5.0-dev+1125-gb3dd856f2-dirty
Build type: Gentoo
LuaJIT 2.1.0-beta3
Compilation: /usr/lib64/ccache/bin/x86_64-pc-linux-gnu-gcc -O2 -march=x86-64 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/config -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/include
Compiled by portage@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- `vim -u DEFAULTS` (version: 8.2.0814) behaves differently?
yes
- Operating system/version:
Gentoo
- Terminal name/version:
Konsole 20.08.1
- `$TERM`:
xterm-256color, konsole-256color, tmux-256color (all the same behaviour)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Enter "insert" mode (or command (`:`), doesn't matter)
# Press `^V` (or `^Q`) and then `Super+Up` (or any other arrow key).
# You will see that it was detected as just `<Up>` (or other arrow key), without Super.
# Although, other Super-combinations (like `Super-m`) are detected fine: (say, `^X@sm` for `Super-m`).

# Also, vim8 DO understand difference (although, using another "marking scheme". It detects Up Arrow as `^[OA`, and `Super+Up` as `^[[1;1A` (so, it also reacts on Super+arrows mappings, unlike NeoVim) 

```

**Comment by glacambre** [comment]
This works fine in GUIs and with `:call nvim_input("i<C-v><D-Up>")`, so it's probably a TUI/Konsole issue.

**Comment by zeertzjq** [comment]
Both `^[OA` and `^[[1;1A` mean `Up` pressed without any modifiers, and Konsole indeed sends `^[[1;1A` when `Super+Up` is pressed, so this is not a neovim bug, but a Konsole one.

**Comment by msva** [comment]
Btw, I can't remember how did I got `^[0A` for `<Up>`, but now I'm getting `^[[A` for `<Up>` and still `^[[1;1A` for `Super+A`, so Konsole do make the difference between them.

@zeertzjq can you advice, how did you decide that `^[[1;1A` means `<Up>` without modifiers? Is there any documentation about that sequences?

**Comment by zeertzjq** [comment]
> Btw, I can't remember how did I got `^[0A` for `<Up>`, but now I'm getting `^[[A` for `<Up>` and still `^[[1;1A` for `Super+A`, so Konsole do make the difference between them.
> 
> @zeertzjq can you advice, how did you decide that `^[[1;1A` means `<Up>` without modifiers? Is there any documentation about that sequences?

<https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-PC-Style-Function-Keys>

**Comment by msva** [comment]
Well, I don't know what they call `meta`, but taking examples with F5, `2-6` modifiers works here as in that table. I can't test Ctrl+Alt/Ctrl+Shift+Alt (I didn't disable VT switching in xorg), and `Win+F5` returns `^[[15;1~`, while "plain" `F5` returns `^[[15~`, Although their `meta`'s code is `9`, and table starting from code `2`, and tells nothing about code `1` (which I have in Konsole). :shrug: 

Btw, I tried `st` terminal, and there is `6` for `Win` (which is `Ctrl+Shift` in the table, and `Ctrl+Shift+F5` sends nothing...)

**Comment by justinmk** [comment]
> This works fine in GUIs and with `:call nvim_input("i<C-v><D-Up>")`, 
>
> Probably related: #2204

this

> * `vim -u DEFAULTS` (version: 8.2.0814) behaves differently?
>   yes

if vim in a terminal actually handled `<D-*>` that is likely covered by https://github.com/neovim/neovim/issues/6279

**Comment by msva** [comment]
@justinmk not sure if it is somehow covered by #6279, but #14350 looks related (although t is created after this bug).

And I also not sure what did you mean under `<D-*>` in vim8: as I mentioned, it sees (with `Ctrl+V`) `<Up>` as `^[OA` (`<Up>` with double `Ctrl+K`), and `Win+Up` as `^[[1;1A` (`[1;1A` with double `Ctrl+K`).

Not sure what you ment as `<D-*>` :shrug:

**Comment by zeertzjq** [comment]
> @justinmk not sure if it is somehow covered by #6279, but #14350 looks related (although t is created after this bug).
> 
> And I also not sure what did you mean under `<D-*>` in vim8: as I mentioned, it sees (with `Ctrl+V`) `<Up>` as `^[OA` (`<Up>` with double `Ctrl+K`), and `Win+Up` as `^[[1;1A` (`[1;1A` with double `Ctrl+K`).
> 
> Not sure what you ment as `<D-*>` shrug

Maybe Vim only supports `<D-*>` under macOS.

**Comment by zeertzjq** [comment]
> Well, I don't know what they call `meta`, but taking examples with F5, `2-6` modifiers works here as in that table. I can't test Ctrl+Alt/Ctrl+Shift+Alt (I didn't disable VT switching in xorg), and `Win+F5` returns `^[[15;1~`, while "plain" `F5` returns `^[[15~`, Although their `meta`'s code is `9`, and table starting from code `2`, and tells nothing about code `1` (which I have in Konsole). shrug
> 
> Btw, I tried `st` terminal, and there is `6` for `Win` (which is `Ctrl+Shift` in the table, and `Ctrl+Shift+F5` sends nothing...)

`Meta` means `Super`. Try pressing `Shift+Up` and `Super+Shift+Up` and you'll see Konsole sends both as `^[[1;2A`.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/nitty-gritty-questions-on-terminal-nvim-and-keyboard-events/1624/1
