### ISSUE TITLE
Screen got blank during web Development. 

### ISSUE THREAD

**Issue by mayankdutta** [neovim/neovim#14075]
I was working on a [Web Project](https://github.com/GoelVaibhav009/TestBooks) on neovim, changing some styling, saving and watching preview on Safari. 
in Background i had, `mongodb`, `nodemon`.

Issue: 
When i did some `change and save it`, and `switch window` for watching the preview, suddenly all window got cleared (see pics for better understanding). 
Also the `mouse functionality` goes off (unable to click and do anything using mouse).  

This is how my normal desktop look like, 
![original](https://user-images.githubusercontent.com/33067129/110237630-ff333280-7f62-11eb-8bdc-0bf0d8a7f859.png)

as I switch after watching the site preview. 
![stage1](https://user-images.githubusercontent.com/33067129/110237619-f0e51680-7f62-11eb-9cb4-32bcc2d613ba.png)

Now, I have to manually go up and down by `j` and `k` key and as I move text began reappearing. 
![stage2](https://user-images.githubusercontent.com/33067129/110237625-f93d5180-7f62-11eb-8646-0c085e21002b.png)

Mouse functionality got off, and therefore have to switch via keyboard. 
![stage3](https://user-images.githubusercontent.com/33067129/110237636-035f5000-7f63-11eb-8a6d-20c5c1f70ddb.png)

I have to move up and down in all files like this, to view the full code. 
![stage4](https://user-images.githubusercontent.com/33067129/110237642-05c1aa00-7f63-11eb-8c31-8ac24548fb4c.png)

![stage5](https://user-images.githubusercontent.com/33067129/110237644-078b6d80-7f63-11eb-8dd0-19a5771ee358.png)

![stage6](https://user-images.githubusercontent.com/33067129/110237649-09edc780-7f63-11eb-8cd8-b4065cb3a486.png)

Finally after moving up and down in all files code look like this. 
![stage7 finally](https://user-images.githubusercontent.com/33067129/110237650-0d814e80-7f63-11eb-98c9-ba568643da3b.png)

I am on Macbook air 2017
`macos Big Sur 11.2.1`

Using `iterm2`

here is the result of nvim --verison
```
NVIM v0.5.0-dev+nightly
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210222-11212-1kfmr3q/build/config -I/tmp/neovim-20210222-11212-1kfmr3q/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210222-11212-1kfmr3q/build/src/nvim/auto -I/tmp/neovim-20210222-11212-1kfmr3q/build/include
Compiled by info@Mayanks-MacBook-Air.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-595f6e4_1/share/nvim"
```

vim --version
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 27 2021 03:10:38)
macOS version - x86_64
Included patches: 1-2550
Compiled by Homebrew
```

My [init.vim](https://github.com/mayankdutta/code_template/blob/master/init.vim) 
My [vimrc](https://github.com/mayankdutta/code_template/blob/master/vimrc)

**Comment by mayankdutta** [comment]
issue get resolve after, reopening Neovim, but after some time occur again.

**Comment by glacambre** [comment]
This looks like a terminal issue to me. Can you reproduce with another terminal?

**Comment by stvhuang** [comment]
I met the same issue a few weeks ago, also on macOS Big Sur but my terminal was Alacritty. However, it has not occurred recently. I am now using the nightly version (dev-1129). Do you also use the "latest" nightly version?

**Comment by mayankdutta** [comment]
> I met the same issue a few weeks ago, also on macOS Big Sur but my terminal was Alacritty. However, it has not occurred recently. I am now using the nightly version (dev-1129). Do you also use the "latest" nightly version?

yes I was on latest version of iterm2, but I will try the same with other terminal.

**Comment by mayankdutta** [comment]
> This looks like a terminal issue to me. Can you reproduce with another terminal?

Thank, I tried with Terminal (in built mac terminal), this issue occurred twice in iTerm where as not a single time with terminal.

**Comment by mayankdutta** [comment]
Thank you guys for your support, it was Iterm2 issue, though still not resolved had to move to Kitty terminal, but raised the same on gitlab of iterm2.

**Comment by mayankdutta** [comment]
Guys issue is resolved. 
You can view the thread on [Gitlab](https://gitlab.com/gnachman/iterm2/-/issues/9551#note_528947651).
