### ISSUE TITLE
Can't start LSP server outside of `$PATH`, even though `cmd_cwd` is provided.

### ISSUE THREAD

**Issue by kabouzeid** [neovim/neovim#14072]
**Problem in the code:** `extra_spawn_params.cwd` is not considered when determining whether `cmd` is executable. Thus the LSP server is not started even though the command is executable in this case.

https://github.com/neovim/neovim/blob/115488105d3ddec2d9251d3adbcdb78dfe3cc9bc/runtime/lua/vim/lsp/rpc.lua#L318-L320

**Background:** I install my language servers locally (outside of `$PATH`) and inject the install directory through `cmd_cwd` as described in the docs. https://github.com/neovim/neovim/blob/115488105d3ddec2d9251d3adbcdb78dfe3cc9bc/runtime/lua/vim/lsp.lua#L370-L374

By the way, this https://github.com/neovim/neovim/pull/11336#issue-336710654 also uses `cmd_cwd`, so this seems like a regression to me.

**Comment by fsouza** [comment]
`cwd` means the directory from which the binary will be executed, not where the binary is located. If you want to run a process that's not in the `$PATH`, you need to pass the full path to the binary instead of just its name.

**Comment by kabouzeid** [comment]
Thanks for the input :) I suspected that too, but I have now further investigated this. Neovim uses `libuv` to spawn the process, which actually **does** use the `cwd` to resolve the binary in case of a relative path. You can try it out yourself if you like, the following will only spawn the process if the `executable` file is found in `cwd`.
```c
#include <stdio.h>
#include <stdlib.h>
#include <uv.h>

uv_loop_t *loop;
uv_process_t child_req;
uv_process_options_t options;

int main() {
    loop = uv_default_loop();

    char* args[2];
    args[0] = "executable";
    args[1] = NULL;

    options.args = args;
    options.cwd = "/path/to/executable/dir";
    options.file = "./executable"; // will execute /path/to/executable/dir/executable

    int r;
    if ((r = uv_spawn(loop, &child_req, &options))) {
        fprintf(stderr, "%s\n", uv_strerror(r));
        return 1;
    } else {
        fprintf(stderr, "Launched process with ID %d\n", child_req.pid);
    }

    return uv_run(loop, UV_RUN_DEFAULT);
}
```

I couldn't find proper documentation though, had to try it out.

**Comment by fsouza** [comment]
Oh I didn't realize you were doing "./bin-name". Yeah, in that case I'd expect it to work.
