### ISSUE TITLE
Discussion: Following HEAD wiki alternatives

### ISSUE THREAD

**Issue by ruifm** [neovim/neovim#14071]
IMO, the [Following HEAD wiki](https://github.com/neovim/neovim/wiki/Following-HEAD) is not a suitable medium to announce breaking changes.

It's impossible to get GH notifications for wiki changes, I only "notice" them by occasionally seeing it poping out in my GH feed which is not ideal.

I don't believe I am the only one that is frustated by this. Although I'm unaware of the exact % of users who use nightly/HEAD, I believe it to be substantial enough to warrant more care and communication. Specially when taking into account that such users are probably the ones more enthusiastic about neovim as a project.

I opened this issue to raise awereness and to open up a discussion on possible alternatives.

Some of them come to mind that are obviously superior to GH wiki:

* RSS feed
* Email newsletter
* A dedicated **locked** GH issue
* A changelog published in nightly releases when there is a breaking change (although this has a limited scope and only impacts GH users who "watch" neovim releases)
* A dedicated twitter
* A r/neovim pinned post

These are not mutually exclusive and the wiki can still be kept as an easily accesible log of past breaking changes.

**Comment by mjlbach** [comment]
We also have a discourse now, which offers RSS notifications, email, subscribed threads, mobile app, etc.

**Comment by ruifm** [comment]
> We also have a discourse now, which offers RSS notifications, email, subscribed threads, mobile app, etc.

That is great and I do check the discourse once in a while. Anything that can provide exclusive notifications/subscriptions to breaking changes would be better than the status quo..

Even a dedicated **locked** GH issue would be better than a wiki since at least an issue is subscribable.

If you guys do decide to address this, it would also be helpful if users were pointed to the new medium where they can subscribe to breaking changes. The same way archlinux recommends users to follow their announcement news for manual interventions and breaking changes but at the same time, does not force them to do so.

**Comment by jamessan** [comment]
> Even a dedicated **locked** GH issue would be better than a wiki since at least an issue is subscribable.

This sounds like a pretty good idea.

**Comment by teto** [comment]
discourse requires yet another login while github access should be more common for our users. I've created https://github.com/neovim/neovim/issues/14090 that you can subscribe to.

**Comment by ruifm** [comment]
I'm not sure if I get a notification if you just edit the issue. I think for it to work, each announcment would have to be a different comment.

In any case, I'm happy with it, can this be closed?

**Comment by teto** [comment]
I dont think you get a notif if I edit the issue, we've planned to add new comments for every breaking change (and maybe merge back some of them in the first comment later on to prevent the thread from getting too long).
