### ISSUE TITLE
'^.ppm' breaks paragraph text objects

### ISSUE THREAD

**Issue by nebulaeandstars** [neovim/neovim#14080]
- `nvim --version`: v0.4.4
- Operating system: Arch Linux
- `$TERM`: alacritty

### Steps to reproduce:

- Enter a few lines of text to form a paragraph
- Add ".ppm" to the start of any of those lines
- Try to do anything with paragraph text objects (`{`, `yip`, etc)

### Actual behaviour

Any line that starts with ".ppm" is treated as the start of a new paragraph.

### Expected behaviour

Those lines should be treated normally.

**Comment by chrisbra** [comment]
Vim detects that as nroff macros, as described at `:h paragraph`.
