### ISSUE TITLE
Lsp sends incorrect rangeLength when allow_incremental_sync=true and :set inccommand=nosplit, after user does :s/xxx/yyy/

### ISSUE THREAD

**Issue by danngreen** [neovim/neovim#14084]
Normally nvim sends a textDocument/didChange message with range.end - range.start = rangeLength, for example:
```
{
    "jsonrpc": "2.0",
    "method": "textDocument/didChange",
    "params": {
        "contentChanges": [
            {
                "range": {
                    "end": {
                        "character": 0,
                        "line": 2
                    },
                    "start": {
                        "character": 0,
                        "line": 1
                    }
                },
                "rangeLength": 14,
                "text": "\\tint x = 234;\\n"
            }
        ],
        "textDocument": {
            "uri": "file:///tmp/bug_report/main.c",
            "version": 5
        }
    }
}

```
But, if you do a :s command (e.g. `:s/xxx/yyy/`) when `set incommand` is not empty (that is, `set inccommand=nosplit` or `split`), AND lsp setup{} has allow_incremental_sync=true, then nvim sends an incorrect value for rangeLength. For example:
```
{
    "jsonrpc": "2.0",
    "method": "textDocument/didChange",
    "params": {
        "contentChanges": [
            {
                "range": {
                    "end": {
                        "character": 0,
                        "line": 2
                    },
                    "start": {
                        "character": 0,
                        "line": 1
                    }
                },
                "rangeLength": 28,
                "text": "\\tint x = 274;\\n"
            }
        ],
        "textDocument": {
            "uri": "file:///tmp/src/bug_report/main.c",
            "version": 6
        }
    }
}

```
Notice rangeLength: 28

I presume some lsp servers ignore rangeLength, as it is officially deprecated, as I understand, but some servers definitely need a correct rangeLength in order to work. For example: https://github.com/neovim/neovim/pull/14079#issuecomment-792914902 . Also for example, when clangd receives rangeLength that does not equal range.end - range.start, it will report back an error, and any subsequent lsp requests are also responded to with an error. The file must be reloaded with `:e` to re-establish lsp functionality.

Oddly, the incorrect rangeLength value is always approximately twice the correct value, however it's usually not exactly 2x. E.g. nvim sends `rangeLength: 396` which it should be 200...  or 13 when it should be 7.

Another clue is that when inccommand=nospit, the log output is escaped like crazy.
E.g. no inccomand:
` {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end" {"character":0,"line":2},","start":{"character":0,"line":1}},"rangeLength":14,"text":"\\tint x = 244;\\n"} `
inccommand=nosplit:
`{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didChange\",\"params\":{\"contentChanges\":[{\"range\":{\"end\":{\"character\":0,\"line\":2},\"start\":{\"character\":0,\"line\":1}},\"rangeLength\":28,\"text\":\"\\tint x = 274;\\n\"}`

### Steps to reproduce using `nvim -u NORC`
Here's a simple project to reproduce:
```
//main.c
int main() {
    int x = 555;
}
```
```
//compile_commands.json
[{
  "directory": "/tmp/bug_report/",
  "arguments": ["gcc", "-c", "-o", "main.o", "main.c"],
  "file": "main.c"
}]
```
```
//example-lsp-setup.lua
-- Note: Plugin 'neovim/nvim-lspconfig' must be installed
require'lspconfig'.clangd.setup {
    cmd = {"/usr/local/bin/clangd_12.0.0-rc2/bin/clangd"}, --clangd 11.1.0 has same behavior
    flags = {allow_incremental_sync = true}
};
```

```
$ nvim -u NORC
:lua require'example-lsp-setup'
:e main.c
:set inccommand=nosplit
:%s/5/4/g
```
At this point the lsp server will no longer respond to changes, viewing the logs shows clangd responded to the textDocument/didChange with:
```
Failed to update /tmp/bug_report/main.c: Change's rangeLength (28) doesn't match the computed range length (14).
```

NVIM v0.5.0-dev+1099-g4d5dbea4f
also tested with this PR branch (same behavior): https://github.com/neovim/neovim/pull/14079

Operating system/version:
macOS 11.2.2
clangd 12.0.0rc2
and also tested with clangd 11.1.0 (installed with brew)

**Comment by mjlbach** [comment]
See #14079 which will replace the incremental sync mechanism

**Comment by danngreen** [comment]
Excellent, thank you, that PR branch fixes the issue.
I had seen that fork, and tested it, but I must not have pulled recently enough... in any case, it works now! I'll continue to test and if I find any issues I'll report to that issue thread.
