### ISSUE TITLE
formatting plugin using setline and LSP causes nvim to hang with 100% CPU

### ISSUE THREAD

**Issue by vrischmann** [neovim/neovim#14087]
nvim version:
```
NVIM v0.5.0-dev+1130-g7c204af87
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/vincent/dev/devtools/neovim/build/config -I/home/vincent/dev/devtools/neovim/src -I/home/vincent/dev/devtools/neovim/.deps/usr/include -I/usr/include -I/home/vincent/dev/devtools/neovim/build/src/nvim/auto -I/home/vincent/dev/devtools/neovim/build/include
Compiled by vincent@hiro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/vincent/local/share/nvim"

Run :checkhealth for more info
```

Hello,

I'm sorry the title is vague but I don't know how to describe the issue I'm facing succinctly.

I'm running neovim HEAD, using the plugin [zig.vim](https://github.com/ziglang/zig.vim), the LSP server [zls](https://github.com/zigtools/zls) and the builtin LSP client with the [lspconfig for zls](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/zls.lua).

A [recent change](https://github.com/ziglang/zig.vim/blob/master/autoload/zig/fmt.vim#L29-L35) in zig.vim changed how the content of the buffer is replaced: now after formatting a file the plugin deletes the extra lines at the end and replaces the content of the buffer using `setline`.

Since that change every time I save a file, nvim hangs at 100% CPU for a couple of seconds, writing hundreds of MiB of logs in `$HOME/.cache/nvim/lsp.log`; the bigger the input file, the longer it hangs and the more data it writes to the log.

I think I've managed to determine what the problem is:  `setline` triggers a call to the LSP client [text_document_did_change_handler](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L927) _for each line_ in the range changed by setline, _sequentially_. 

This can be seen in the lsp.log by grepping `on_lines` (I've trimmed the file content at the end of each line):
```
[ DEBUG ] 2021-03-09T23:20:29+0100 ] /home/vincent/local/share/nvim/runtime/lua/vim/lsp.lua:816 ]	"on_lines bufnr: 1, changedtick: 5, firstline: 0, lastline: 1, new_lastline: 1, old_byte_size: 28, old_utf32_size: 28, old_utf16_size: 28"	
[ DEBUG ] 2021-03-09T23:20:29+0100 ] /home/vincent/local/share/nvim/runtime/lua/vim/lsp.lua:816 ]	"on_lines bufnr: 1, changedtick: 6, firstline: 1, lastline: 2, new_lastline: 2, old_byte_size: 48, old_utf32_size: 48, old_utf16_size: 48"	
[ DEBUG ] 2021-03-09T23:20:29+0100 ] /home/vincent/local/share/nvim/runtime/lua/vim/lsp.lua:816 ]	"on_lines bufnr: 1, changedtick: 7, firstline: 2, lastline: 3, new_lastline: 3, old_byte_size: 25, old_utf32_size: 25, old_utf16_size: 25"	
[ DEBUG ] 2021-03-09T23:20:29+0100 ] /home/vincent/local/share/nvim/runtime/lua/vim/lsp.lua:816 ]	"on_lines bufnr: 1, changedtick: 8, firstline: 3, lastline: 4, new_lastline: 4, old_byte_size: 19, old_utf32_size: 19, old_utf16_size: 19"	
[ DEBUG ] 2021-03-09T23:20:29+0100 ] /home/vincent/local/share/nvim/runtime/lua/vim/lsp.lua:816 ]	"on_lines bufnr: 1, changedtick: 9, firstline: 4, lastline: 5, new_lastline: 5, old_byte_size: 21, old_utf32_size: 21, old_utf16_size: 21"	
[ DEBUG ] 2021-03-09T23:20:29+0100 ] /home/vincent/local/share/nvim/runtime/lua/vim/lsp.lua:816 ]	"on_lines bufnr: 1, changedtick: 10, firstline: 5, lastline: 6, new_lastline: 6, old_byte_size: 29, old_utf32_size: 29, old_utf16_size: 29"	
[ DEBUG ] 2021-03-09T23:20:29+0100 ] /home/vincent/local/share/nvim/runtime/lua/vim/lsp.lua:816 ]	"on_lines bufnr: 1, changedtick: 11, firstline: 6, lastline: 7, new_lastline: 7, old_byte_size: 1, old_utf32_size: 1, old_utf16_size: 1"	
[ DEBUG ] 2021-03-09T23:20:29+0100 ] /home/vincent/local/share/nvim/runtime/lua/vim/lsp.lua:816 ]	"on_lines bufnr: 1, changedtick: 12, firstline: 7, lastline: 8, new_lastline: 8, old_byte_size: 21, old_utf32_size: 21, old_utf16_size: 21"	
[ DEBUG ] 2021-03-09T23:20:29+0100 ] /home/vincent/local/share/nvim/runtime/lua/vim/lsp.lua:816 ]	"on_lines bufnr: 1, changedtick: 13, firstline: 8, lastline: 9, new_lastline: 9, old_byte_size: 28, old_utf32_size: 28, old_utf16_size: 28"	
```
This goes on to the end of the file which is 1976 lines in my test.

To me this looks like a bug, `on_lines` could be called once with the correct lines; however I'm not familiar with the neovim internals so I may be missing something here.

**Comment by mfussenegger** [comment]
Could you try again with the latest master? incremental sync is now enabled by default, so all these `on_lines` triggers should be cheaper.

**Comment by vrischmann** [comment]
It doesn't seem to help, but I think that's expected since zls doesn't support incremental changes.
I'm still seeing the same behaviour in the lsp.log file.

**Comment by mfussenegger** [comment]
>  but I think that's expected since zls doesn't support incremental changes.

Oh, bummer. Yes then it's expected.
You could try out https://github.com/neovim/neovim/pull/14119 if you're feeling adventurous.

You'd have add an option to your configuration to enable it, for example:

```lua
local config = {
  -- <your usual configuration options>
  flags = {
    debounce_did_change_notify = 250,
  };
}
```

**Comment by vrischmann** [comment]
@mfussenegger I've tested #14119, looks like it resolves my issue. Thanks a lot !

**Comment by mjlbach** [comment]
#14119 is merged
