### ISSUE TITLE
Neovim nightly throws error on startup

### ISSUE THREAD

**Issue by FardeenCodes** [neovim/neovim#14086]
- `nvim --version`:

NVIM  v0.5.0-dev

Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/fardeen/neovim/neovim-nightly/build/config -I/home/fardeen/neovim/neovim-nightly/src -I/home/fardeen/neovim/neovim-nightly/.deps/usr/include -I/usr/include -I/home/fardeen/neovim/neovim-nightly/build/src/nvim/auto -I/home/fardeen/neovim/neovim-nightly/build/include
Compiled by fardeen@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

- Operating system/version:
**Alpine Linux**

- Terminal name/version:
- `xterm-256color`

### Steps to reproduce 
**Just open neovim**

### Actual behaviour

Throws error : 
E484: Can't open file /usr/local/share/nvim/runtime/syntax/syntax.vim
(syntax.vim file  is not there is a folder vim)

### Expected behaviour
Open without any error

**Comment by glacambre** [comment]
Sounds like you didn't `make install`. This error doesn't happen if you run `VIMRUNTIME="/home/fardeen/neovim/neovim-nightly/runtime" nvim`, right?

**Comment by glacambre** [comment]
Where did you configure cmake to install neovim?

**Comment by FardeenCodes** [comment]
> Where did you configure cmake to install neovim?

In `/home/fardeen/neovim/neovim-nigthly`

**Comment by glacambre** [comment]
@FardeenCodes are you still encountering this issue?

**Comment by FardeenCodes** [comment]
Yes

**Comment by glacambre** [comment]
How did you configure the install directory?

**Comment by FardeenCodes** [comment]
I didn't configured install directory , I just created an alias `alias nvim=VIMRUNTIME="/home/fardeen/neovim/neovim-nightly/runtime" nvim`

**Comment by glacambre** [comment]
I don't understand, in your first reply you said that using the VIMRUNTIME environment variable fixed the problem. Did I misunderstand something?

**Comment by FardeenCodes** [comment]
The environment variable does not I have to write that everytime like this
`VIMRUNTIME="/home/fardeen/neovim/neovim-nightly/runtime" nvim`  so I made an alias and it works.

**Comment by glacambre** [comment]
Okay, everything is working as expected then.

You have to configure your install directory before building neovim, otherwise neovim won't be able to find the runtime files (and this means that you will have to use VIMRUNTIME=... everytime you run neovim in order to tell it where to find the runtime files). See [this page](https://github.com/neovim/neovim/wiki/Building-Neovim#building) for more information.

I'll close this issue as there's no bug, but feel free to ask more questions if you need to :).
