### ISSUE TITLE
Neovim's sourcehut builds are frequently timing out

### ISSUE THREAD

**Issue by ddevault** [neovim/neovim#14083]
Hiya, sourcehut admin here. Some of your builds finish in tens of minutes ([A](https://builds.sr.ht/~jmk/job/453480), [B](https://builds.sr.ht/~jmk/job/453481)), but [a lot of builds](https://builds.sr.ht/~jmk/neovim?search=status%3Atimeout) are hanging and taking up the full build slot, which is expensive for us. What causes them to hang?

**Comment by glacambre** [comment]
Pinging @justinmk as I don't know if he's still watching this repo or not.

**Comment by mjlbach** [comment]
Also, I'm sorry Drew, a lot of these builds were mine (didn't realize we were triggering CI on draft PRs) and until this is fixed I'll be more cognizant about how frequently I push.

**Comment by bfredl** [comment]
Perhaps we could emulate travis feature of aborting the build after a few mins of no output. Unfortunately test failures regarding event processing (like #13686 ) often show up as deadlocks rather than assert fail.

**Comment by ddevault** [comment]
It's not a big deal, @mjlbach, no worries - I just don't want to be wasting a lot of build time on a deadlocked test suite.

**Comment by ddevault** [comment]
Yes, that would be possible, and I may add that, but it's not really the problem. A single build deadlocking and hitting the time limit is 20× more expensive than one draft build.

**Comment by jamessan** [comment]
Yeah, I definitely agree the timed out builds are a problem. I'll take a look at the builds and see about enforcing a better timeout as part of our pipeline, rather than hitting the overall timeout.

**Comment by ddevault** [comment]
The timeout tells you that there's a bug in your test suite. You should fix whatever causes the deadlock.

**Comment by jamessan** [comment]
Understood, but we should also avoid gratuitously wasting CI resources while we figure that out.

**Comment by ddevault** [comment]
Agreed, but given that they're my cycles being wasted, I'm prepared to wait a little bit while you guys investigate the actual cause 🙂 If a solution isn't found quickly, then maybe a workaround is appropriate.

**Comment by ddevault** [comment]
Bump.

**Comment by ddevault** [comment]
Bump?

https://builds.sr.ht/~jmk/neovim?search=status%3Atimeout

**Comment by glacambre** [comment]
@ddevault I think @jamessan been working on this: https://github.com/neovim/neovim/pull/14204

**Comment by jamessan** [comment]
Yes, I've been trying to look into it, but I have very little spare time lately, so it's slow going.  Anyone else is welcome to work on it.

**Comment by ddevault** [comment]
Cool, thanks. Keep me in the loop :)

**Comment by ddevault** [comment]
Any progress? This is happening more often again now:

https://builds.sr.ht/~jmk/neovim?search=status%3Atimeout

**Comment by bfredl** [comment]
seems the old openbsd heisenhang also occurs on freebsd now https://github.com/neovim/neovim/pull/15169

**Comment by ddevault** [comment]
Any progress? #15169 was merged but this is still regularly occurring. This isn't cheap for us - if you bought the equivalent amount of CircleCI minutes you'd be spending $10/day.

**Comment by clason** [comment]
@ddevault We found and now skip a hanging test so that builds should now finish again within ten minutes or so (except for currently open PRs, of course). Let us know if that didn't help!

**Comment by ddevault** [comment]
Thanks! I'll keep an eye out.

**Comment by justinmk** [comment]
We now enforce a much shorter timeout in the tests.
