### ISSUE TITLE
double free when using nvim-tree and checkhealth

### ISSUE THREAD

**Issue by kyazdani42** [neovim/neovim#14097]
NVIM v0.5.0-dev+1136-gc29494b71 (basically master)
Build type: RelWithDebInfo
LuaJIT 2.0.5
Archlinux 5.11.4-arch1-1

## problem
i'm not sure if this comes from the plugin or neovim, but still crashes should not happen.
i use [my tree](https://github.com/kyazdani42/nvim-tree.lua), with the option to keep the tree open when changing/opening a new tabpage.
few issue arise:
when doing `tabnew` and closing the tree, i then have no way to close neovim `bd`, `qa`, `q`, `tabclose` actions do not work.
If i'm doing a cheakhealth after opening neovim, the file explorer stays open in the new tab, do a few `:bd` and neovim crashes with either double free or an invalid pointer being freed.

I'm not too sure but this might be caused by the scheduled callbacks for syncing the tree.

## expected
no crash

**Comment by teto** [comment]
Related https://github.com/neovim/neovim/issues/13577 ?

**Comment by kyazdani42** [comment]
yes I guess, the issue has been there for quite some time.
