### ISSUE TITLE
attempt to index field '_cached_buffers' (a nil value)

### ISSUE THREAD

**Issue by klooj** [neovim/neovim#14100]
- `nvim --version`: NVIM v0.5.0-dev+1140-g097ec71bd
- language server name/version: lua (sumneko), python (jedi), possibly others. bashls seems fine.  
- Operating system/version: macOS/Big Sur

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/57016271/110737722-e6917980-81fb-11eb-9a7d-662e0a5bc051.png">

</details>

<details>
<summary>lsp.log</summary>

</details>

### Steps to reproduce using `nvim -u NORC`

1. open a lua or python file and press 'o' to enter insert mode.

### Actual behaviour

... /share/nvim/runtime/lua/vim/lsp.lua:849: attempt to index field
'_cached_buffers' (a nil value)

### Expected behaviour

more cowbell.

**Comment by mjlbach** [comment]
As amusing as the the cowbell is, what I really need is more details. I'm assuming you're using incremental sync? Did you enable it with on_attach on on_init (you need to do the latter).

**Comment by klooj** [comment]
You are correct. I enabled it with on_attach but not on_init. I totally forgot the log too, gimme a sec.

**Comment by klooj** [comment]
i disabled incremental sync and the error went away, so that's definitely it. thanks boss.

**Comment by mjlbach** [comment]
wait but did the error go away if you enabled it in on_init? Incremental sync should work now...

**Comment by klooj** [comment]
checking now

**Comment by mjlbach** [comment]
cc: @elianiva

**Comment by klooj** [comment]
yes that fixed it. i tucked into a custom_init function then just add `on_init = custom_init`

**Comment by mjlbach** [comment]
where are people getting the info to use on_attach so I can delete the comment/blog post lol

**Comment by klooj** [comment]
i blame telescopic johnson (@tjdevries ). i copied his lspconfig like 9 months ago and have been recovering/making it my own ever since

**Comment by mjlbach** [comment]
TJ!

I'm closing then. We will eventually make this more ergonomic (probably with option namespaces), but for now you can do: 

```lua
nvim_lsp = require('lspconfig')
nvim_lsp.rust_analyzer.setup {
    on_init = function(client)
        client.config.flags = {}
        if client.config.flags then
          client.config.flags.allow_incremental_sync = true
        end
    end;
 }
```

**Comment by elianiva** [comment]
Nice, moving it to `on_init` fixed it. I believe I put it `on_attach` because I just copied and paste that from somewhere not realising that's not how you supposed to do it. Thanks everyone!

**Comment by mjlbach** [comment]
Yeah, it's more that I couldn't find a nice way to get the handler to work if we put it in on attach, it previously would be fine with the old method that used on-lines, but we now have to cache changes to compute a diff which has to be done on first open of the file as well as on each subsequent edit, so we need the flag enabled before the first on_attach call.

**Comment by klooj** [comment]
That makes sense. i think this implementation works just fine.

**Comment by tjdevries** [comment]
Did I do good now @mjlbach  ? https://github.com/tjdevries/config_manager/commit/0c9b2a34031fb36db23dc0bb35fc10383839c038 :)

**Comment by mjlbach** [comment]
Oh man, you sniped me right before I made a sassy PR.

It's on by default now, so you don't even need that line :)

**Comment by tjdevries** [comment]
It's a good reminder for me of where to put stuff -- i had forgotten about `on_init`
