### ISSUE TITLE
typing ". " in `:insert` swallows dot

### ISSUE THREAD

**Issue by LunarLambda** [neovim/neovim#14109]
While trying to figure out how to insert "." literally using the :insert command, I found an inconsistenty between neovim and vim. (I still haven't figured out how)

- `nvim --version`: v0.4.4
- `vim -u DEFAULTS` (version: 8.2) behaves differently? yes
- Operating system/version: Manjaro Linux
- Terminal name/version: xfce4-terminal 0.8.1.0
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:insert
. 
.
```

Please mind the space following the first dot.

### Actual behaviour

inserts " " into the buffer

### Expected behaviour

inserts ". " into the buffer

**Comment by teto** [comment]
It is correctly inserted but the display is not refreshed for some reason (try Ctrl-l to refresh screen).

**Comment by zeertzjq** [comment]
This seems to only happen at the beginning of a buffer, and it applies to the first line of any text inserted using `:insert`.

**Comment by zeertzjq** [comment]
This also applies to `:append` in an empty buffer.

**Comment by zeertzjq** [comment]
May be a side-effect of #5850 that only applies to Nvim.

**Comment by zeertzjq** [comment]
When `:insert` is used in a mapping, Vim also has the problem.
