### ISSUE TITLE
swapname gives double slashes

### ISSUE THREAD

**Issue by AckslD** [neovim/neovim#14110]
- `nvim --version`: NVIM v0.5.0-dev+1133-g0869cbd55
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: 5.11.2-arch1-1
- Terminal name/version: kitty 0.19.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC ~/test.txt
echo swapname('%')
```

### Actual behaviour
Prints `//home/axel/.local/share/nvim/swap//%home%axel%test.txt.swp`

### Expected behaviour
Prints `/home/axel/.local/share/nvim/swap/%home%axel%test.txt.swp`
i.e. without double slash after `swap`.

**Comment by shanesmith** [comment]
Same issue appears in Vim, created a ticket [here](https://github.com/vim/vim/issues/8876).

**Comment by zeertzjq** [comment]
The Vim patch cannot be ported because of #15433.

**Comment by zeertzjq** [comment]
Inferring from [`4e516e5` (#15433)](https://github.com/neovim/neovim/pull/15433/commits/4e516e53bfde35901b055bbc85d84a6d471ebc34) there may be some Windows-related stuff that can complicate the porting of [Vim patch 8.2.3543](https://github.com/vim/vim/commit/8b0e62c93b6dad5ec5b2c7558d4f7b78c46216d2).
