### ISSUE TITLE
Leading '>' are deleted when joining to a line containing '>'

### ISSUE THREAD

**Issue by Zoybean** [neovim/neovim#14114]
- `nvim --version`:
```
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```
- `vim -u DEFAULTS` (version: VIM - Vi IMproved 8.1) behaves differently? **Vim works as expected.**
- Operating system/version: **Windows 10 enterprise 2016 LTSB**
- Terminal name/version: **GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)**
- `$TERM`: **cygwin**

### Steps to reproduce using `nvim -u NORC`
in a file with the following content
```
text > here
 > >> > 1
```
On line 1, press `J` or `gJ` to join the second line onto the first.

### Actual behaviour
Resulting joined line is missing all leading `>` characters, and all spaces up to the last leading `>`: `text > here 1`

### Expected behaviour
Resulting joined line is composed of the content of the first line, a space if `J` was used, and the content of the second line (with leasing spaces removed if J was used): `text > here > >> > 1`

### Notes
It appears that the first line can be any content that contains the `>` character at least once, and the second line can be any content that has any number of leading `>` characters and spaces.

**Comment by glacambre** [comment]
This is not a bug but a feature ;)

`>` is used to quote things when replying to an email. So when joining two lines that look like they're quoting something, Neovim (and Vim) helpfully tries to remove the multiple leading `>`.

If you want to disable this behavior, you need to remove `j` from your `formatoptions`: `:set formatoptions-=j`. You can read `:help formatoptions` and `:help fo-table` for more information :).
