### ISSUE TITLE
Please add installation instructions for Raspberry Pi OS

### ISSUE THREAD

**Issue by X-hung** [neovim/neovim#14129]
Raspberry Pi OS is based on Debian, so the installation instructions should be the same as Debian.

Ref: https://en.wikipedia.org/wiki/Raspberry_Pi_OS

**Comment by jamessan** [comment]
Then why do we need instructions specific to RPi?

**Comment by stsewd** [comment]
I've been able to compile nvim in raspbian following the debian steps.

**Comment by X-hung** [comment]
Just in case that someone newbie doesn't know that :)
