### ISSUE TITLE
Malformatting with nvim-lsp / gopls 

### ISSUE THREAD

**Issue by sergii4** [neovim/neovim#14121]
- `nvim --version`: NVIM v0.5.0-dev+nightly
- nvim-lsp version(commit hash):   465a64ad2767e5ff5b055f9bd07314fa445cedc6
- What language server (If the problem is related to a specific language server): gopls
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):
- Is the problem isolated to a particular language server:
- Operating system/version: macOS 11.1 (20C69)

### How to reproduce the problem from neovim startup
Try to format go file
### Actual behaviour
Malformat go code with 
```
buf_set_keymap("n", "ff", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
```
Format code
```
func DBConn(cfg Config) (*sql.DB, error) {

	psqlInfo := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable",
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
  db, err := sql.Open("postgres", psqlInfo)
  if err != nil {
	  return nil, errors.Wrap(err, "can't establish connection")
  }

  err = db.Ping()
  if err != nil {

	  return nil, errors.Wrap(err, "can't ping DB")
  }

  fmt.Println("Successfully connected!")
	return db, nil
}
```
to
```
func DBConn(cfg Config) (*sql.DB, error) {

	psqlInfo := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable",
		cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
  db, err := sql.Open("postgres", psqlInfo)
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
  if err != nil {
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
	  return nil, errors.Wrap(err, "can't establish connection")
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
  }
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)

	if err != nil {

		return nil, errors.Wrap(err, "can't ping DB")
	}
    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)
  }
	fmt.Println("Successfully connected!")
	return db, nil
}
```
but `go fmt ./...` works correct
### Expected behaviour
Formatting correct, same as `go fmt`
### Minimal init.vim or init.lua and code sample
<details>
call plug#begin()
Plug 'neovim/nvim-lspconfig'
Plug 'mileszs/ack.vim'
Plug 'justinmk/vim-dirvish'
Plug 'vim-airline/vim-airline'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'dracula/vim', { 'as': 'dracula' }
call plug#end()

lua <<EOF
local nvim_lsp = require('lspconfig')

local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }
  buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', 'ga', '<Cmd>lua vim.lsp.buf.code_action()<CR>', opts)
  buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
  buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
  buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
  buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
  buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
  buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
  buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
  buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
  buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)

  -- Set some keybinds conditional on server capabilities
  if client.resolved_capabilities.document_formatting then
    buf_set_keymap("n", "ff", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
  elseif client.resolved_capabilities.document_range_formatting then
    buf_set_keymap("n", "ff", "<cmd>lua vim.lsp.buf.range_formatting()<CR>", opts)
  end

  -- Set autocommands conditional on server_capabilities
  if client.resolved_capabilities.document_highlight then
    vim.api.nvim_exec([[
      hi LspReferenceRead cterm=bold ctermbg=red guibg=LightYellow
      hi LspReferenceText cterm=bold ctermbg=red guibg=LightYellow
      hi LspReferenceWrite cterm=bold ctermbg=red guibg=LightYellow
      augroup lsp_document_highlight
        autocmd! * <buffer>
        autocmd CursorHold <buffer> lua vim.lsp.buf.document_highlight()
        autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()
      augroup END
    ]], false)
  end
end

-- Use a loop to conveniently both setup defined servers 
-- and map buffer local keybindings when the language server attaches
nvim_lsp.gopls.setup{
	-- cmd = {'gopls', '-remote=auto', '-logfile=/tmp/gopls.log', '-rpc.trace'},
	cmd = {'gopls'},
	on_attach = on_attach
}

vim.lsp.set_log_level("debug")
EOF

"nnoremap <silent> ff    <cmd>lua vim.lsp.buf.formatting()<CR>
"autocmd BufWritePre *.go lua vim.lsp.buf.formatting()

" https://stackoverflow.com/questions/6991638/how-to-auto-save-a-file-every-1-second-in-vim
let g:autosave_time = 1

set ttyfast                     " Indicate fast terminal conn for faster redraw
colorscheme dracula

" Set leader shortcut to a comma ','. By default it's the backslash
let mapleader = ","

set number                      " Show line numbers

" Jump to next error with Ctrl-n and previous error with Ctrl-m. Close the
" quickfix window with <leader>a
map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>

</details>
### Health check
<details>
<summary>Checkhealth result</summary>
  - INFO: gopls: configuration checked.
</details>

### LSP log

<details>
<summary>Log file</summary>
[ DEBUG ] 2021-03-12T13:42:41+0000 ] ...neovim/HEAD-c1fbc2d_1/share/nvim/runtime/lua/vim/lsp.lua:691 ]	"LSP[gopls]"	"client.request"	1	"textDocument/formatting"	{  options = {    insertSpaces = false,    tabSize = 8  },  textDocument = {    uri = "file:///Users/sgetman/code/vonage/apex/neru-platform/stan-sub/db/db.go"  }}	<function 1>	1
[ DEBUG ] 2021-03-12T13:42:41+0000 ] ...im/HEAD-c1fbc2d_1/share/nvim/runtime/lua/vim/lsp/rpc.lua:391 ]	"rpc.send.payload"	{  id = 2,  jsonrpc = "2.0",  method = "textDocument/formatting",  params = {    options = {      insertSpaces = false,      tabSize = 8    },    textDocument = {      uri = "file:///Users/sgetman/code/vonage/apex/neru-platform/stan-sub/db/db.go"    }  }}
[ DEBUG ] 2021-03-12T13:42:41+0000 ] ...im/HEAD-c1fbc2d_1/share/nvim/runtime/lua/vim/lsp/rpc.lua:492 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "5577006791947779410",    value = {      kind = "end",      message = "Finished loading packages."    }  }}
[ DEBUG ] 2021-03-12T13:42:41+0000 ] ...neovim/HEAD-c1fbc2d_1/share/nvim/runtime/lua/vim/lsp.lua:487 ]	"notification"	"$/progress"	{  token = "5577006791947779410",  value = {    kind = "end",    message = "Finished loading packages."  }}
[ DEBUG ] 2021-03-12T13:42:41+0000 ] ...AD-c1fbc2d_1/share/nvim/runtime/lua/vim/lsp/handlers.lua:407 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = "5577006791947779410",    value = {      kind = "end",      message = "Finished loading packages."    }  }}
[ DEBUG ] 2021-03-12T13:42:41+0000 ] ...im/HEAD-c1fbc2d_1/share/nvim/runtime/lua/vim/lsp/rpc.lua:492 ]	"decoded"	{  id = 2,  jsonrpc = "2.0",  result = { {      newText = "\t\tcfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n",      range = {        end = {          character = 0,          line = 69        },        start = {          character = 0,          line = 69        }      }    }, {      newText = "  cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n  ",      range = {        end = {          character = 2,          line = 71        },        start = {          character = 2,          line = 71        }      }    }, {      newText = "    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n",      range = {        end = {          character = 0,          line = 72        },        start = {          character = 0,          line = 72        }      }    }, {      newText = "",      range = {        end = {          character = 3,          line = 73        },        start = {          character = 2,          line = 73        }      }    }, {      newText = "  cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)",      range = {        end = {          character = 3,          line = 73        },        start = {          character = 3,          line = 73        }      }    }, {      newText = "  }",      range = {        end = {          character = 0,          line = 74        },        start = {          character = 0,          line = 74        }      }    }, {      newText = "",      range = {        end = {          character = 4,          line = 75        },        start = {          character = 2,          line = 75        }      }    }, {      newText = "  cfg.Host, cfg.Po",      range = {        end = {          character = 4,          line = 75        },        start = {          character = 4,          line = 75        }      }    }, {      newText = "t,",      range = {        end = {          character = 5,          line = 75        },        start = {          character = 5,          line = 75        }      }    }, {      newText = "",      range = {        end = {          character = 7,          line = 75        },        start = {          character = 6,          line = 75        }      }    }, {      newText = "cfg.User,",      range = {        end = {          character = 7,          line = 75        },        start = {          character = 7,          line = 75        }      }    }, {      newText = "",      range = {        end = {          character = 10,          line = 75        },        start = {          character = 8,          line = 75        }      }    }, {      newText = "cfg",      range = {        end = {          character = 10,          line = 75        },        start = {          character = 10,          line = 75        }      }    }, {      newText = "",      range = {        end = {          character = 14,          line = 75        },        start = {          character = 12,          line = 75        }      }    }, {      newText = "assword, cf",      range = {        end = {          character = 14,          line = 75        },        start = {          character = 14,          line = 75        }      }    }, {      newText = "",      range = {        end = {          character = 16,          line = 75        },        start = {          character = 15,          line = 75        }      }    }, {      newText = ".DBName",      range = {        end = {          character = 16,          line = 75        },        start = {          character = 16,          line = 75        }      }    }, {      newText = "",      range = {        end = {          character = 17,          line = 76        },        start = {          character = 0,          line = 76        }      }    }, {      newText = "\n\tif err != nil {\n",      range = {        end = {          character = 17,          line = 76        },        start = {          character = 17,          line = 76        }      }    }, {      newText = "",      range = {        end = {          character = 0,          line = 77        },        start = {          character = 0,          line = 77        }      }    }, {      newText = "\t\treturn nil, errors.Wrap(err, \"can't ping DB\")",      range = {        end = {          character = 0,          line = 77        },        start = {          character = 0,          line = 77        }      }    }, {      newText = "}\n",      range = {        end = {          character = 1,          line = 78        },        start = {          character = 1,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 9,          line = 78        },        start = {          character = 3,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 14,          line = 78        },        start = {          character = 10,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 18,          line = 78        },        start = {          character = 15,          line = 78        }      }    }, {      newText = "cfg.H",      range = {        end = {          character = 18,          line = 78        },        start = {          character = 18,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 20,          line = 78        },        start = {          character = 19,          line = 78        }      }    }, {      newText = "t, cfg",      range = {        end = {          character = 21,          line = 78        },        start = {          character = 21,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 23,          line = 78        },        start = {          character = 22,          line = 78        }      }    }, {      newText = "Po",      range = {        end = {          character = 23,          line = 78        },        start = {          character = 23,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 27,          line = 78        },        start = {          character = 24,          line = 78        }      }    }, {      newText = "t, cfg.Us",      range = {        end = {          character = 27,          line = 78        },        start = {          character = 27,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 29,          line = 78        },        start = {          character = 28,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 33,          line = 78        },        start = {          character = 32,          line = 78        }      }    }, {      newText = "fg.P",      range = {        end = {          character = 34,          line = 78        },        start = {          character = 34,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 38,          line = 78        },        start = {          character = 35,          line = 78        }      }    }, {      newText = "ssword,",      range = {        end = {          character = 38,          line = 78        },        start = {          character = 38,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 42,          line = 78        },        start = {          character = 39,          line = 78        }      }    }, {      newText = "cf",      range = {        end = {          character = 42,          line = 78        },        start = {          character = 42,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 44,          line = 78        },        start = {          character = 43,          line = 78        }      }    }, {      newText = ".",      range = {        end = {          character = 44,          line = 78        },        start = {          character = 44,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 47,          line = 78        },        start = {          character = 46,          line = 78        }      }    }, {      newText = "Name",      range = {        end = {          character = 47,          line = 78        },        start = {          character = 47,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 2,          line = 81        },        start = {          character = 0,          line = 80        }      }    }, {      newText = "\t",      range = {        end = {          character = 2,          line = 81        },        start = {          character = 2,          line = 81        }      }    } }}
[ DEBUG ] 2021-03-12T13:42:41+0000 ] ...AD-c1fbc2d_1/share/nvim/runtime/lua/vim/lsp/handlers.lua:407 ]	"default_handler"	"textDocument/formatting"	{  bufnr = 1,  client_id = 1,  params = { {      newText = "\t\tcfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n",      range = {        end = {          character = 0,          line = 69        },        start = {          character = 0,          line = 69        }      }    }, {      newText = "  cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n  ",      range = {        end = {          character = 2,          line = 71        },        start = {          character = 2,          line = 71        }      }    }, {      newText = "    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n",      range = {        end = {          character = 0,          line = 72        },        start = {          character = 0,          line = 72        }      }    }, {      newText = "",      range = {        end = {          character = 3,          line = 73        },        start = {          character = 2,          line = 73        }      }    }, {      newText = "  cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)",      range = {        end = {          character = 3,          line = 73        },        start = {          character = 3,          line = 73        }      }    }, {      newText = "  }",      range = {        end = {          character = 0,          line = 74        },        start = {          character = 0,          line = 74        }      }    }, {      newText = "",      range = {        end = {          character = 4,          line = 75        },        start = {          character = 2,          line = 75        }      }    }, {      newText = "  cfg.Host, cfg.Po",      range = {        end = {          character = 4,          line = 75        },        start = {          character = 4,          line = 75        }      }    }, {      newText = "t,",      range = {        end = {          character = 5,          line = 75        },        start = {          character = 5,          line = 75        }      }    }, {      newText = "",      range = {        end = {          character = 7,          line = 75        },        start = {          character = 6,          line = 75        }      }    }, {      newText = "cfg.User,",      range = {        end = {          character = 7,          line = 75        },        start = {          character = 7,          line = 75        }      }    }, {      newText = "",      range = {        end = {          character = 10,          line = 75        },        start = {          character = 8,          line = 75        }      }    }, {      newText = "cfg",      range = {        end = {          character = 10,          line = 75        },        start = {          character = 10,          line = 75        }      }    }, {      newText = "",      range = {        end = {          character = 14,          line = 75        },        start = {          character = 12,          line = 75        }      }    }, {      newText = "assword, cf",      range = {        end = {          character = 14,          line = 75        },        start = {          character = 14,          line = 75        }      }    }, {      newText = "",      range = {        end = {          character = 16,          line = 75        },        start = {          character = 15,          line = 75        }      }    }, {      newText = ".DBName",      range = {        end = {          character = 16,          line = 75        },        start = {          character = 16,          line = 75        }      }    }, {      newText = "",      range = {        end = {          character = 17,          line = 76        },        start = {          character = 0,          line = 76        }      }    }, {      newText = "\n\tif err != nil {\n",      range = {        end = {          character = 17,          line = 76        },        start = {          character = 17,          line = 76        }      }    }, {      newText = "",      range = {        end = {          character = 0,          line = 77        },        start = {          character = 0,          line = 77        }      }    }, {      newText = "\t\treturn nil, errors.Wrap(err, \"can't ping DB\")",      range = {        end = {          character = 0,          line = 77        },        start = {          character = 0,          line = 77        }      }    }, {      newText = "}\n",      range = {        end = {          character = 1,          line = 78        },        start = {          character = 1,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 9,          line = 78        },        start = {          character = 3,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 14,          line = 78        },        start = {          character = 10,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 18,          line = 78        },        start = {          character = 15,          line = 78        }      }    }, {      newText = "cfg.H",      range = {        end = {          character = 18,          line = 78        },        start = {          character = 18,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 20,          line = 78        },        start = {          character = 19,          line = 78        }      }    }, {      newText = "t, cfg",      range = {        end = {          character = 21,          line = 78        },        start = {          character = 21,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 23,          line = 78        },        start = {          character = 22,          line = 78        }      }    }, {      newText = "Po",      range = {        end = {          character = 23,          line = 78        },        start = {          character = 23,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 27,          line = 78        },        start = {          character = 24,          line = 78        }      }    }, {      newText = "t, cfg.Us",      range = {        end = {          character = 27,          line = 78        },        start = {          character = 27,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 29,          line = 78        },        start = {          character = 28,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 33,          line = 78        },        start = {          character = 32,          line = 78        }      }    }, {      newText = "fg.P",      range = {        end = {          character = 34,          line = 78        },        start = {          character = 34,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 38,          line = 78        },        start = {          character = 35,          line = 78        }      }    }, {      newText = "ssword,",      range = {        end = {          character = 38,          line = 78        },        start = {          character = 38,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 42,          line = 78        },        start = {          character = 39,          line = 78        }      }    }, {      newText = "cf",      range = {        end = {          character = 42,          line = 78        },        start = {          character = 42,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 44,          line = 78        },        start = {          character = 43,          line = 78        }      }    }, {      newText = ".",      range = {        end = {          character = 44,          line = 78        },        start = {          character = 44,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 47,          line = 78        },        start = {          character = 46,          line = 78        }      }    }, {      newText = "Name",      range = {        end = {          character = 47,          line = 78        },        start = {          character = 47,          line = 78        }      }    }, {      newText = "",      range = {        end = {          character = 2,          line = 81        },        start = {          character = 0,          line = 80        }      }    }, {      newText = "\t",      range = {        end = {          character = 2,          line = 81        },        start = {          character = 2,          line = 81        }      }    } }}
[ DEBUG ] 2021-03-12T13:42:41+0000 ] ...neovim/HEAD-c1fbc2d_1/share/nvim/runtime/lua/vim/lsp.lua:809 ]	"on_lines bufnr: 1, changedtick: 4, firstline: 69, lastline: 82, new_lastline: 89, old_byte_size: 321, old_utf32_size: 321, old_utf16_size: 321"	{ "\t\tcfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)", "    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)", "    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)", "    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)", '  db, err := sql.Open("postgres", psqlInfo)', "    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)", "  if err != nil {", "    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)", "\t  return nil, errors.Wrap(err, \"can't establish connection\")", "    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)", "  }", "    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)", "", "\tif err != nil {", "", "\t\treturn nil, errors.Wrap(err, \"can't ping DB\")", "\t}", "    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)", "  }", '\tfmt.Println("Successfully connected!")' }
[ DEBUG ] 2021-03-12T13:42:41+0000 ] ...im/HEAD-c1fbc2d_1/share/nvim/runtime/lua/vim/lsp/rpc.lua:391 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        text = "package db\n\nimport (\n\t\"database/sql\"\n\t\"fmt\"\n\t\"strings\"\n\n\t\"github.com/pkg/errors\"\n)\n\nconst (\n\teventSubj  = \"event\"\n\tlogSubj    = \"log\"\n\teventTable = \"Events\"\n\tlogTable   = \"Logs\"\n)\n\nvar (\n\tlogHeaders   = []string{\"timestamp\", \"logId\", \"logLevel\", \"sourceType\", \"sourceId\", \"apiAccountId\", \"apiApplicationId\", \"applicationId\", \"applicationName\", \"instanceId\", \"message\"}\n\teventHeaders = []string{\"timestamp\", \"eventId\", \"eventType\", \"sourceType\", \"sourceId\", \"apiAccountId\", \"apiApplicationId\", \"applicationId\", \"applicationName\", \"instanceId\", \"details\"}\n)\n\ntype DBCopier interface {\n\tCopyCSV(filepath string) error\n}\n\ntype PostgresCopier struct {\n\tdb      *sql.DB\n\ttable   string\n\theaders []string\n}\n\nfunc (p *PostgresCopier) CopyCSV(filepath string) error {\n\ttx, err := p.db.Begin()\n\tif err != nil {\n\t\treturn errors.Wrap(err, \"cannot start transaction\")\n\t}\n\t// Load the CSV file directly into PostgreSQL, into factual.places\n\tif _, err := tx.Exec(fmt.Sprintf(\"copy neru.%s (%s) from %s with csv\", p.table, strings.Join(p.headers[:], \",\"), filepath)); err != nil {\n\t\treturn errors.Wrap(err, \"cannot copy CSV file into database\")\n\n\t}\n\n\tif err := tx.Commit(); err != nil {\n\n\t\treturn errors.Wrap(err, \"cannot commit transaction\")\n\n\t}\n\treturn nil\n}\n\nfunc NewPostgresCopier(db *sql.DB, table string, headers []string) DBCopier {\n\treturn &PostgresCopier{db: db, table: table, headers: headers}\n}\n\nfunc PostgresCopierFactory(subj string, db *sql.DB) DBCopier {\n\ttable := eventTable\n\theaders := eventHeaders\n\tif subj == logSubj {\n\t\ttable = logTable\n\t\theaders = logHeaders\n\n\t}\n\treturn NewPostgresCopier(db, table, headers)\n}\n\nfunc DBConn(cfg Config) (*sql.DB, error) {\n\n\tpsqlInfo := fmt.Sprintf(\"host=%s port=%s user=%s password=%s dbname=%s sslmode=disable\",\n\t\tcfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n  db, err := sql.Open(\"postgres\", psqlInfo)\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n  if err != nil {\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n\t  return nil, errors.Wrap(err, \"can't establish connection\")\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n  }\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n\n\tif err != nil {\n\n\t\treturn nil, errors.Wrap(err, \"can't ping DB\")\n\t}\n    cfg.Host, cfg.Port, cfg.User, cfg.Password, cfg.DBName)\n  }\n\tfmt.Println(\"Successfully connected!\")\n\treturn db, nil\n}\n"      } },    textDocument = {      uri = "file:///Users/sgetman/code/vonage/apex/neru-platform/stan-sub/db/db.go",      version = 4    }  }}
[ DEBUG ] 2021-03-12T13:42:41+0000 ] ...im/HEAD-c1fbc2d_1/share/nvim/runtime/lua/vim/lsp/rpc.lua:492 ]	"decoded"	{  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = '2021/03/12 13:42:41 unable to compute positions for type errors: no parsed file for  in handler/function/db\n\tpackage="handler/function/db"\n',    type = 1  }}
</details>

**Comment by mjlbach** [comment]
Does this happen when you open a file (fresh) without editing it? Try disabling incremental sync `:help lsp`

**Comment by sergii4** [comment]
It doen't depend on freshness: so it can be just opened or edited file.
I added to `local on_attach`
```
  if client.config.flags then
    client.config.flags.allow_incremental_sync = false
  end
```
but it doesn't help

**Comment by sergii4** [comment]
How I reproduce it - i take any formatted piece of code, do some shift with `Shift + >`, invoke formatting(with `ff` in my case) and I get malformated, duplicated code.

**Comment by mjlbach** [comment]
This isn't enough details (and that's not how you disable incremental sync, you need to do it in on_init). I need an example repo, version of gopls, repro with minimal config (see nvim-lspconfig).

**Comment by sergii4** [comment]
Could you provide example how to disable incremental sync?

**Comment by mjlbach** [comment]
Can you send me a self-contained file that this occurs on?

**Comment by sergii4** [comment]
@mjlbach I have update gopls and the problem gone :)

**Comment by sergii4** [comment]
fixed by updating gopls
