### ISSUE TITLE
map-<expr> doesn't replay properly in mappings and macros

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#14133]
This was first raised on the Neovim Discourse [here](https://neovim.discourse.group/t/how-to-work-around-map-expr-pre-evaluation-in-macros/264), but I'm opening an issue since it looks like a bug.

- `nvim --version`: v0.5.0-dev+1147-g314b222c2
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Arch Linux 5.10.5-arch1-1
- Terminal name/version: GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

1. Create a new buffer with the following vimscript, then save and source the file:
```
function! X()
  let line = line('.')
  let col = col('.')
  echomsg "Pressed x at (".l:line.", ".l:col.")"
  return "x"
endfunction

nnoremap <expr> x X()
```
2. Place your cursor at the start of the last line and record the macro `fpx`.
3. Observe that in `:messages` you see "Pressed x at (8, 8)."
4. Undo the change and restore the cursor position.
5. Replay the macro.
6. Observe that the message "Pressed x at (8, 1)" appears.

@andymass pointed out [below](https://github.com/neovim/neovim/issues/14133#issuecomment-799828849) that this issue affects mappings as well, not only macros.

I originally thought this might be unfortunate intended behavior for expression mappings and was looking for a work-around solution, but @RRethy pointed out that it's likely just a bug. Reproducing his response here:

> It seems like a bug to me.
> When using your example and recording the macro fpx;x I see echo’d:
>> Pressed x at (8, 1)                                                                                                             
>> Pressed x at (8, 12) 

> So the first x is wrong but the second one is right.
> Also, when I do lfpx, I see echo’d:
>> Pressed x at (8, 2)

> So the expression was evaluated after the macro had started (l executes before x is evaluated). Maybe file an issue.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/how-to-work-around-map-expr-pre-evaluation-in-macros/264/3

**Comment by andymass** [comment]
I think you might get some more help on vim, since this seems not neovim specific.

Note this isn't strictly a problem with macros; you can make a mapping that behaves the same:

    nmap <space> fpx

In terms of workarounds, you can use

    nmap <space> fp<ignore>x

Or even

    nmap <space> fp:<cr>x

For macros you can use e.g.,

    nnoremap gs <ignore>
    let \@q = 'fpgsx'
