### ISSUE TITLE
+clipboard for nvim from homebrew

### ISSUE THREAD

**Issue by pencilcheck** [neovim/neovim#1413]
Coming from vim from homebrew, a lot of features are missing it seems, wondering if it is possible to make it compiling with those features enabled such as +clipboard? Because copy and pasting to my Mac OSX clipboard directly from vim is very useful to my workflow.

**Comment by Pyrohh** [comment]
I'm pretty sure @bfredl fixed `:reg` a while ago, along with significant other work regarding the clipboard. We already have a few more specific issues open regarding clipboard problems, so I'll close this. Please reopen if I missed something.
