### ISSUE TITLE
LSP popup does not go away after navigating to definition in another file

### ISSUE THREAD

**Issue by pizzapim** [neovim/neovim#14135]
- `nvim --version`: NVIM v0.5.0-dev+1148-g3c8583e43
- Operating system/version: Ubuntu 20.04.2 LTS x86_64
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

I created a minimal vimrc to reproduce the error, as I use nvim-lspconfig to load the clangd LSP.

```
all plug#begin('~/.config/nvim/plugged')
Plug 'neovim/nvim-lspconfig'
call plug#end()
lua << EOF
local nvim_lsp = require('lspconfig')
require'lspconfig'.clangd.setup{}
EOF
```

1. Create a file "test.h" with ```#define TEST 1```
2. Create a file "test.c" with 
```
#include "test.h"
int a = TEST;
```
3. Open test.c with ```nvim -u samplevimrc test.c ```
4. Navigate to the TEST symbol then execute ```lua vim.lsp.buf.hover()``` and then ```lua vim.lsp.buf.definition()```.

### Actual behaviour

Nvim opens "test.h" to the correct symbol, but the popup from executing ```lua vim.lsp.buf.hover()``` does not go away. Moving inside the newly opened buffer also does not make it go away.

### Expected behaviour
The popup should go away as soon as you go to the definition.

**Comment by mjlbach** [comment]
This this is (essentially) a dupe of https://github.com/neovim/neovim/issues/11508

**Comment by pizzapim** [comment]
I see, I'll close this one then.
