### ISSUE TITLE
lsp: better highlighting of hover docs

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#14143]
See discussion (and images) in: https://github.com/neovim/neovim/pull/14098

We now bundle a custom syntax rule, so it's pretty easy to add your own highlighting, but it would be nice if we also enabled highlighting codeblocks embedded in the markdown documentation (I tried doing this, but setting the filetype breaks the highlighting elsewhere in the hover doc)

@bluz71

**Comment by bluz71** [comment]
The previous Markdown highlighter, based on Tim Pope's Markdown engine, did highlight fenced code. It worked well for me.

As stated the new LSP Markdown script extends Tim Pope's script rather than reimplements it. Hence this must be a regression / bug.

When I have time I will explore, ideally we can fix this before 0.5

**Comment by mjlbach** [comment]
Just to clear things up, I don't believe it's a regression:

The original behavior: d1074e0077024d1581a77e3bf09e80a657047847

The behavior that broke the code block: 4ed860a64cf6db8dcf33d16ce448243bf072006d

The current behavior: 054eb31dc797f9e9addd680a547215cd058b486e

**Comment by bluz71** [comment]
My before and after images say otherwise, lots of highlighting has gone.

If not a regression, then it must either be my environment or user error (my user error).

I need to do a deep dive since I really want highlighting restored back to original behaviour.

**Comment by mjlbach** [comment]
I'm not able to get color on any of the three commits listed above (before and after I touched syntax highlighting in floats) on your dart example.  It's not a code block, but a `mkdNonListItemBlock -> mkdNonListItemBlock` so it shouldn't be highlighted (there's no codefence)

**Comment by bluz71** [comment]
I am finally at my desk, ready to do some testing. Expect results in the next half hour or so.

I have this mapping already for detecting highlight groups:

```viml
nnoremap <F8> :echo synIDattr(synID(line('.'), col('.'), 1), 'name')<CR>
```

I use it all the time whilst I maintain my [moonfly](https://github.com/bluz71/vim-moonfly-colors) and [nightfly](https://github.com/bluz71/vim-nightfly-guicolors) themes.

**Comment by bluz71** [comment]
Ok, testing with JavaScript.

OLD - commit 0869cbd (the commit before d49177af)
NEW - commit 054eb31

OLD:

![old](https://user-images.githubusercontent.com/11382509/111253243-f7604600-8666-11eb-9f8f-ef7be43ef2dd.png)

NEW:

![New](https://user-images.githubusercontent.com/11382509/111253257-fdeebd80-8666-11eb-9e99-058f265afaf0.png)

With cursor on `*@param*` I get these highlight groups:

OLD: `markdownItalic`
NEW: `mkdNonListItemBlock`

With the cursor on `onfulfilled` I get these highlight groups:

OLD: `markdownCode`
NEW: `mkdNonListItemBlock`

If I click around on most of the words of the NEW I get `mkdNonListItemBlock` as the highlight group.

That can't be right? The OLD highlighting appears more correct to me.

**Comment by bluz71** [comment]
Are we sure the complex regex for `mkdNonListItemBlock` in [lsp_markdown.vim](https://github.com/neovim/neovim/blob/master/runtime/syntax/lsp_markdown.vim) is correct?

It is a beast:

```viml
syntax region mkdNonListItemBlock start=/\(\%^\(\s*\([-*+]\|\d\+\.\)\s\+\)\@!\|\n\(\_^\_$\|\s\{4,}[^]\|\t+[^\t]\)\@!\)/ end=/^\(\s*\([-*+]\|\d\+\.\)\s\+\)\@=/  contains=@mkdNonListItem
```

I think it is being applied to too much markdown in place of legitimate `markdownItalic` and `markdownCode` as seen in the screenshots above.

Let me test Dart + Flutter.

**Comment by bluz71** [comment]
Testing with Dart.

OLD - commit 0869cbd (the commit before d49177a)
NEW - commit 054eb31

OLD:

![OLD](https://user-images.githubusercontent.com/11382509/111254264-c3862000-8668-11eb-8639-d044034d799b.png)


NEW:

![NEW](https://user-images.githubusercontent.com/11382509/111254276-c84ad400-8668-11eb-803a-980e85754bdd.png)

The https links highlight group:

- OLD - `mardownUrl`
- NEW - `mkdNonListItemBlock`

On the Icon type:

- OLD - `dartUserType`
- NEW - `mkdNonListItemBlock`

Yes, I think the `mkdNonListItemBlock` highlight group is the issue, it is being applied to nearly everything.

I suggest that `mkdNonListIemBlock` be reverted until we know how to fix it.

**Comment by mjlbach** [comment]
If I do that, we lose conceal of all special characters (which IMO was a bigger problem), I'll try to fix the block highlighting before 0.5

**Comment by bluz71** [comment]
It depends on one's perspective which is the bigger issue.

Currently LSP hover docs in Markdown format are not being highlighted as Markdown. I genuinely hope it is fixed before 0.5 since it really effects the user experience.

Let me know what I can do to help, I have a vested interest in getting this fixed.

Cheers.

**Comment by bluz71** [comment]
I think #14032 was the motivator for the change (for those following this conversation).

My dislike of regex-based syntax highlighters grows stronger each day. They are way too brittle (as seen here).

It is very sad that Treesitter does not have a Markdown parser, that would have been very handy.

**Comment by mjlbach** [comment]
Tree-sitter does, but that's not a good fit for this purpose.

**Comment by bluz71** [comment]
Ok, my bad.

**Comment by mjlbach** [comment]
Pretty sure this is mostly resolved now, but I'll keep it open as a tracking issue for the 0.5 launch.

Tree-sitter is hypothetically doable, the issue is right now we strip out certain chars (like the code fence for the function signature) to make the window compact if there is now markdown (since conceal still leaves a blank line). If we didn't do that we could use tree-sitter, I'm not sure how fast tree-sitter is on first parse compared to regex and if adding a dependency on nvim-treesitter to core is a good idea (plus there are less grammars for TS currently than regex rules for other languages).

**Comment by gshpychka** [comment]
To be clear, markdown symbols are still being wrongly rendered:

![image](https://user-images.githubusercontent.com/23005347/111382908-35358c80-86b0-11eb-88d2-9eaa653ee348.png)

**Comment by mjlbach** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/13316262/111383145-0fcf6100-8665-11eb-9b59-96fe30a42d66.png">

**Comment by gshpychka** [comment]
Ugh, I apologize, I was using a custom script for the hoverdoc :/

**Comment by mjlbach** [comment]
I'm closing this because I'm actually pretty happy with them currently (I fixed the issues with the documentation hover and the signature hover), and others can feel free to file PRs improving the syntax file. I also have an open PR which will resolve the remaining blankspace highlighting issues.
