### ISSUE TITLE
Usabiity of working with multiple files

### ISSUE THREAD

**Issue by abitrolly** [neovim/neovim#14147]
Default and intuitive shortcuts play an important role in usability of any software product. It looks like `nvim` maintains compatibility with `vim` in areas that could behave better. Like editing multiple files.

- `nvim --version`: v0.4.4

Open multiple files.
```
nvim *.haml
```
First problem is that there are no shortcuts for closing current file or moving to next or previous one.

The second problem is that commands for managing open files are inconsistent.
`:n` - `next file`, but
`:p` - is `:print`, and one needs `:prev`
`:q` - warns about files left to edit, but leaves current file visible
`:c` - is `:change:` and not `:close` (I have no idea how often `:change` is used and what for)
`:close` - shows message "can not close last window"

`:bd` - I would say that 355 StackOverflow upvotes is bad metric for an intuitive usability feature https://stackoverflow.com/questions/256204/close-file-without-quitting-vim-application

Opening files.
`:o` - doesn't `:open`, but just lists `:oldfiles`
`:open` - not an editor command

Honestly, I don't know how add a new file to the list of files already open.

---

Neovim advertises itself as being focused on usability, so I am curious what is it future take on that user experience?

**Comment by glacambre** [comment]
>Honestly, I don't know how add a new file to the list of files already open.

`:edit` :).

>commands for managing open files are inconsistent.

I agree, and I wish this could be fixed, but I don't think that's possible as these commands could be used by plugins which would then break.

**Comment by sheeaza** [comment]
I would recommend plug-in 'leaderf' or 'fzf vim' for this purpose, to navigate between files or buffers powered by fuzzy engine

**Comment by justinmk** [comment]
This request per se is not actionable. What is actionable are the following (at least):

- builtin "frecency" selector for commands, files, etc. https://github.com/neovim/neovim/issues/660
    - primitives (framework) to make it easier for plugins to build this kind of thing.




> Neovim advertises itself as being focused on usability,

Yes, but within the constraint of vim. The goal isn't to replicate vscode or helix.

**Comment by clason** [comment]
Also, there's a range of very capable "fuzzy pickers" -- including frecency-based ones -- in the plugin ecosystem these days, so there's much less justification for baking this into core. (There's too much user preference in this space to pick one "reasonable default".)
