### ISSUE TITLE
termux build: missing libtreesitter references

### ISSUE THREAD

**Issue by MrAdityaAlok** [neovim/neovim#14151]
# Problem
I was building  `neovim 0.5` for android terminal emulator `Termux` using its build script, but the Github actions ran into an error stating:
![Screenshot_2021-03-17-16-19-08-478](https://user-images.githubusercontent.com/73517616/111456557-79259300-86aa-11eb-9836-efdcb1880bd7.jpeg)
 ## How may I fix it?
Please help

**Comment by bfredl** [comment]
looks like not linking libtreesitter.so . Is the entire build log available ?

**Comment by tuwile** [comment]
@bfredl 
URL : https://pipelines.actions.githubusercontent.com/KzB6xK0xS8wCIcHmnareBvANTuwkdg1MQNqAxsxOk12gCMLORb/_apis/pipelines/1/runs/23/signedlogcontent/6?urlExpires=2021-03-17T11%3A13%3A50.9234565Z&urlSigningMethod=HMACV1&urlSignature=7vIYUnohAIZ19MMxNfgsxf14qj%2BmtOiz9X8qz5%2FG6LA%3D

# OR
[logs_23.zip](https://github.com/neovim/neovim/files/6155870/logs_23.zip)

**Comment by theHamsta** [comment]
@tuwile the issue might be caching. I had problems with incremental builds when the ABI/API changed and could resolve that with `make clean` (assuming that linking to tree-sitter caused no problems before)

**Comment by MrAdityaAlok** [comment]
@bfredl I checked `lib` dir and cmake installs tree-sitter's lib  as `libtree-sitter.so` and not `libtreesitter.so`. Is that the problem?
