### ISSUE TITLE
SIGSEGV in neovim, possibly caused by treesitter.

### ISSUE THREAD

**Issue by 7415963987456321** [neovim/neovim#14153]
- `nvim --version`:
```
- NVIM v0.5.0-dev+1142-g1ce899db7
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -W
extra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-prot
ector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DM
IN_LOG_LEVEL=3 -I/home/keli/.cache/yay/neovim-git/src/build/config -I/home/keli/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/keli/.cac
he/yay/neovim-git/src/build/src/nvim/auto -I/home/keli/.cache/yay/neovim-git/src/build/include
Compiled by keli@keli

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

- `vim -u DEFAULTS` (version: ) Running with defaults works fine.
- Operating system/version: 5.11.1-arch1-1
- Terminal name/version: alacritty 0.7.2 (5ac8060b) and fish, version 3.1.2
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
Getting SIGSEGV termination on opening a C file

### Expected behaviour
Expected it to open the file without issue.

Here's a stacktrace: https://gist.githubusercontent.com/7415963987456321/b2842e73f39e414428fc94852c4c9614/raw/9cd124284c5fb0adf6bbf7764607800da3a4725b/stacktrace

Since running it with with NORC I would assume this is some problem that happens due to tresitter responding badly to my configuration. All parsers are up to date with treesitter.
My configs are available here https://github.com/7415963987456321/dotfiles/tree/master/.config/nvim
This only seems to happen with C files. I can open text files normally.

**Comment by theHamsta** [comment]
I experienced segfaults related to tree-sitter with the recent ABI break. Did you do a complete clean rebuild/reinstall of nvim. Intermediate artifacts of incremental builds can cause those segfaults.

**Comment by 7415963987456321** [comment]
> 
> It's possible that you have the C parser of Nvim. Try to force :TSInstall c although C is already installed.
Unfortunately that does not seem to work.

**Comment by 7415963987456321** [comment]
Okay I seem to have fixed this, 
Updated Nvim to latest master and read some of the stuff in https://github.com/nvim-treesitter/nvim-treesitter/issues/994
Doing TSinstallFromGrammar fixed the issue for me. 
So I am closing.
