### ISSUE TITLE
Add uninstall support.

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#1415]
I think we could be cleaner / more polite if we supported running `sudo make uninstall` at the top level.
IMO, not providing uninstall is the main reason why some users don't want to install from source to see if their problems reproduce that way.

CMake already creates an install manifest, and supporting this is only a couple of code snippets away (see http://www.cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F).

I think I could do it, but prefer leaving it to those who better know our current CMake setup.
@jszakmeister @fwalch Want to take the task?

**Comment by pickfire** [comment]
> IMO, not providing uninstall is the main reason why some users don't want to install from source to see if their problems reproduce that way.

I agree with that and I am sorry to say that I do that. I had once installed `neovim` using `sudo make install` and had no idea how to do something equavalent to `sudo make uninstall`. For now, I will just do `make` in **Neovim**.

**Comment by justinmk** [comment]
Added an [Uninstall](https://github.com/neovim/neovim/wiki/Installing-Neovim#uninstall-a-source-build) section to the wiki.

**Comment by themightyoarfish** [comment]
@justinmk Your link does not contain an Uninstall section (anymore).

**Comment by justinmk** [comment]
Someone removed it ><

**Comment by dmerejkowsky** [comment]
Maybe we could provide a real 'uninstall' target from CMake.

It's documented in the [faq](https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F)

I can write a PR if you like

**Comment by justinmk** [comment]
@dmerejkowsky Sure, but rather than using `install_manifest.txt` as the authority I suggest only doing the equivalent of these steps:

    rm $CMAKE_INSTALL_PREFIX/bin/nvim
    rm -r $CMAKE_INSTALL_PREFIX/share/nvim/

**Comment by dmerejkowsky** [comment]
@justinmk : Why?

Doing that would leave the `nvim.mo` files in `share/locale` and  the man pages in `share/man`.

Using the `install_manifest.txt` is more DRY: we won't have to fix the `uninstall` target if we start installing stuff in other directories.

I don't understand why you do not like using `install_manifest.txt` as the authority, but maybe there's something I'm missing here.

**Comment by jszakmeister** [comment]
I'm pretty sure that technique will also leave things on the file system.  Namely, some of the directory structure with empty directories left behind. :-(

**Comment by dmerejkowsky** [comment]
Ah you're right. Maybe we can still write something clever. Let me think about it

**Comment by cbosoft** [comment]
Any word on adding an uninstall option? The wiki entry's suggestion of:

```bash
sudo rm /usr/local/bin/nvim
sudo rm -r /usr/local/share/nvim/
```

doesn't remove man pages, desktop files and so on.

**Comment by KillTheMule** [comment]
> doesn't remove man pages, desktop files and so on.

But do we install those?

**Comment by cbosoft** [comment]
Yup. Running `sudo make install` command gives the following output (ignoring `/usr/local/share/nvim` and `/usr/local/bin/nvim`):

```bash
-- Up-to-date: /usr/local/share/man/man1/nvim.1
-- Up-to-date: /usr/local/share/locale/ja.euc-jp/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/cs.cp1250/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/sk.cp1250/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/nb/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/af/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/ca/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/cs/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/da/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/de/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/en_GB/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/eo/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/es/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/fi/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/fr/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/ga/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/it/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/ja/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/ko.UTF-8/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/nl/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/no/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/pl.UTF-8/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/pt_BR/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/ru/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/sk/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/sv/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/uk/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/vi/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/zh_CN.UTF-8/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/zh_TW.UTF-8/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/locale/zh_TW.UTF-8/LC_MESSAGES/nvim.mo
-- Up-to-date: /usr/local/share/applications/nvim.desktop
-- Up-to-date: /usr/local/share/pixmaps/nvim.png
```
Full output: [neovim_install_output.txt](https://github.com/neovim/neovim/files/2945472/neovim_install_output.txt)

**Comment by tausiq2003** [comment]
how to do it in windows?
