### ISSUE TITLE
avoid Press Enter prompt for multiple errors

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#14156]
- `nvim --version`:  v0.5.0-445-gca02db1f9 
- nvim-lsp version(commit hash): 39b743b9b36be26a5e58278d7608fe456a0ad3f8
- `:checkhealth` result:
```
health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.
  - INFO: als: configuration checked.
  - INFO: tsserver: configuration checked.
```
- What language server: Ada Language Server (ALS)
- Operating system/version: Linux 5.3.0-46-generic Ubuntu
- Terminal name/version: kitty 0.13.1 
- `$TERM`: xterm-kitty

### How to reproduce the problem from neovim startup
- Create empty files named `/tmp/a.gpr`, `/tmp/b.gpr` and `/tmp/a.adb`
- Install nvim-lsp
- Run `:LspInstall als`
- Run the following lua snippet:
```
local options = {}
options["ada.projectFile"] = "a.gpr"
require("nvim_lsp").als.setup{ init_options = options }
```
- Open `/tmp/a.adb`

### Actual behaviour
The Ada language server will throw the following error and ask you to press enter:
```
LSP[als] More than one .gpr found.
Note: you can configure a project  through the ada.projectFile setting. 
```
The error and the `Press Enter` prompt will appear on each modification applied to the file.

### Expected behaviour

There are two things that I would like to see.

First, if an error message has already been displayed to the user with a `Press enter` prompt, it should not ask for the user to press enter again. This can be achieved by forcing a `:redraw` after displaying the message a second time (or maybe just not displaying the message again?).

Second, I would expect the Ada Language Server to be able to detect the `ada.projectFile` setting I've set with `init_options`. I believe the `ada.projectFile` setting is an InitializationOption because the Ada Language Server provides an example showing [how to configure this setting with LanguageClient-Neovim](https://github.com/AdaCore/ada_language_server#integration-with-languageclient-neovim). LanguageClient-Neovim [reads](https://github.com/autozimu/LanguageClient-neovim/blob/18434f2cd9abc33498e705dfde70d80e19223d0f/src/language_server_protocol.rs#L100) [the](https://github.com/autozimu/LanguageClient-neovim/blob/18434f2cd9abc33498e705dfde70d80e19223d0f/src/language_server_protocol.rs#L278) [settings](https://github.com/autozimu/LanguageClient-neovim/blob/18434f2cd9abc33498e705dfde70d80e19223d0f/src/language_server_protocol.rs#L1127) and [sends them as initializationOptions](https://github.com/autozimu/LanguageClient-neovim/blob/18434f2cd9abc33498e705dfde70d80e19223d0f/src/language_server_protocol.rs#L1156).

**Comment by mjlbach** [comment]
This was fixed upstream in ada language server

**Comment by glacambre** [comment]
Great, thank you for taking the time to check this, I must admit that I had forgotten about this issue :)

**Comment by mjlbach** [comment]
Yeah this was actually a server issue, it was an explicit message being sent multiple times via `window/showMessage` which IMO we should not ignore
