### ISSUE TITLE
Svelte 

### ISSUE THREAD

**Issue by wzzbx** [neovim/neovim#14166]
treesitter 0.19.4
nvim 0.5 latest 
Opening .svelte files with explorer or telescope gives segmentation fault. Everything breaks

**Comment by theHamsta** [comment]
Can confirm that https://nvim-treesitter.zulipchat.com/#narrow/stream/252338-help/topic/Svelte.20Syntax.20Highlighting.20not.20working/near/230842069 Seems to be an issue with the svelte parser.

Debugging with gdb leads me to a SEGFAULT in this line: https://github.com/Himujjal/tree-sitter-svelte/blob/6921b591aa0f0b92a97a7314fb61edff21dd9279/src/utils.h#L871 @Himujjal @elianiva

**Comment by elianiva** [comment]
yes, it's segfaulted. Though it's been fixed on the dev branch. We'll just have to wait until it's merged to the master branch.

**Comment by Himujjal** [comment]
Woah. This error is getting too many hits. Its was to do with a dependency of the library. Let me finally merge the master.

**Comment by Himujjal** [comment]
I have updated the code in the master branch. Any way it can be updated in this repo?
@theHamsta

**Comment by theHamsta** [comment]
It will be updated automatically on the next commit to nvim-treesitter or when you create a PR exchanging the commit hash of svelte parser manually in lockfile.json (CI creates PR automatically after any merge to master)

**Comment by Himujjal** [comment]
created a PR. can you please accept it @theHamsta. We can close this issue then

**Comment by theHamsta** [comment]
Fixed via https://github.com/nvim-treesitter/nvim-treesitter/pull/1064
