### ISSUE TITLE
TSX treesitter segfault

### ISSUE THREAD

**Issue by dewey92** [neovim/neovim#14170]
NVIM: `NVIM v0.5.0-dev+1161-gfa4ee00fa`
Treesitter: `0.19.3`

Having this code:
```ts
const test = `
  transform: ${({ moveX }) => `translateX(${moveX}px) `};
`
```

will make it segfault, especially at `${` after the `translateX(`. This only happens when highlighting is on. So turning off treesitter highlighting won't segfault.

**Comment by theHamsta** [comment]
![image](https://user-images.githubusercontent.com/7189118/111885904-d41cfa00-89ca-11eb-9153-60b6d74271be.png)

@maxbrunsfeld debugging with gdb leads me to this line https://github.com/tree-sitter/tree-sitter/blob/89e1157a299596f3ce2155ba9fd69d5e2c03d3e6/lib/src/query.c#L3195 (89e1157a299596f3ce2155ba9fd69d5e2c03d3e6, newest master)

**Comment by maxbrunsfeld** [comment]
Can you reproduce this by running a query at the command line with `tree-sitter query <query-file> <tsx-file>`?

**Comment by kirill-martynov** [comment]
I got same error with segfault

**Comment by maxbrunsfeld** [comment]
If anyone can find a minimal way of reproducing this, preferably at the command line using `tree-sitter query`, I will fix it as soon as I can.

**Comment by dewey92** [comment]
@maxbrunsfeld I want to help but unfortunately even after reading the doc I still have no idea how `tree-sitter query` works and how to setup the environment to make the issue reproducable.

Anyway, I just updated to the latest version of NVIM (v0.5.0-dev+1205-g3f7cd18c4) and it no longer segfaults 🤷🏼 I'm gonna close this issue for now. Sorry if I can't help much :\
