### ISSUE TITLE
Syntax highlighting bug for 's and "s

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#14177]
- `nvim --version`: 0.5.0-dev+1115-gc1fbc2ddf
- `vim -u DEFAULTS` (version: 8.1.1602) behaves differently? no (bug in vim too)
- Operating system/version: CentOS 7
- Terminal name/version: Xfce4-terminal 0.8.7.4
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

Create `foo.vim` as below:
```
function! Foo()
  let x = ['s']
endfunction
```

Observe that the string is not highlighted correctly ('s is associated with VimSubst as opposed to VimString). Affects both `'s'` and `"s"`.

**Comment by d2weber** [comment]
Seems to be fixed in vim. Updating the necessary line as in https://github.com/vim/vim/blob/master/runtime/syntax/vim.vim#L339 solves the problem.

**Comment by mhinz** [comment]
Fixed as of https://github.com/neovim/neovim/pull/14424
