### ISSUE TITLE
Neovim not recognizing command key on macOS

### ISSUE THREAD

**Issue by Bryce-Davidson** [neovim/neovim#14181]
How am I able to use the command key on macOS? The mapping is clearly specified in the neovim key-map section yet no command key input is passed upon impression.

I have a simple mapping `<D-w> <C-w>` and suspect the call is getting intercepted by an OS level key binding but I am unable to confirm this as even mappings such as `<D-1> <C-w>` do not work as expected.

### Actual behaviour

Pressing command key **does not** get passed to neovim for an instruction when mapping using <D...>

### Expected behaviour

Pressing command key gets passed to neovim for an instruction when mapping using <D...>

**Comment by klooj** [comment]
It depends on the terminal emulator or gui you're using to launch nvim. I recommend you start by pressing <C-k> in command mode followed by the mapping. So in your situation:

1. switch to normal mode
2. press `:`
3. press <C-k>
4. press <D-w>

nvim will display the keystroke it received in step 4. then go about fixing your terminal emulator.

**Comment by Bryce-Davidson** [comment]
Yes, the confusing part is when I do that sequence:

1. switch to normal mode
2. press `:`
3. press `<C-k>`
4. press `<D-w>`

Since I'm on a mac, this closes the window because of the OS level key binding for `<D-w>`.

When I edit in programs such as VSCode, this program has an OS-level keybinding override passthrough such that when I execute a keyboard shortcut it is passed directly to VSCode and not my OS.

Neovim does not seem to have this "override-passthrough" functionality just as well as my terminal emulator. Perhaps I will contact the people over at alacrity for some help with this.

for documentation sake this issue arises on:

Terminal Emulator: `Alacritty@0.7.2`
macOS: `Catalina 10.15.7`
`neovim@v0.4.4`

**Comment by bfredl** [comment]
@Bryce-Davidson Well that is completely up to `Alacritty` in this case, not nvim core.

**Comment by Bryce-Davidson** [comment]
Understood. I've opened the issue there. 

I was simply wondering if neovim provided the ability to override and intercept OS-level keybindings given it is a running process like any other or if this is something I would need to write into any terminal emulator I wish to run neovim within. 

Thanks for the reponse.

**Comment by klooj** [comment]
i use a mac too but do not use the command key for any nvim or "in-app" bindings because it creates exactly the problem you are facing.  if you're not too far down the path, i suggest leaving the command key for OS/app level shortcuts and just using the control key for in-app/neovim level keymaps. you can remap modifier keys globally in system preferences, i.e. make better use of the caps lock. alternatively, just use vimr.

**Comment by mhinz** [comment]
Nvim takes whatever the terminal sends. In this case, probably nothing is sent.

It's the same for Vim, where `<d-X>` mappings are usually just used with MacVim.

You can use software like [Karabiner Elements](https://karabiner-elements.pqrs.org) to make any key combination to send any string that in turn could be used in Nvim, but I wouldn't recommended it.

Related: https://sw.kovidgoyal.net/kitty/keyboard-protocol.html
