### ISSUE TITLE
cursor gets visually out of sync upon resize of signcolumn when it is set to 'auto'

### ISSUE THREAD

**Issue by teto** [neovim/neovim#14195]
- `nvim --version`: 3e5efa50b689955beb36ce9f8cca7138fd5f0f8e
- `vim -u DEFAULTS` (version: ) behaves differently? NA
- Terminal name/version: kitty 0.19.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Sometimes with `signcolumn=auto`, upon new numbers, the signcolumn resizes but the cursor visually stays in place, it thus becomes out of sync with its actual position in the buffer. When resuming input, its visual position is fixed.

Maybe we should refresh the cursor in such instances. Gonna look into it

Of interest
```
    textwidth -= win_fdccol_count(curwin);
    textwidth -= win_signcol_count(curwin);

  int b_signcols_max;           // cached maximum number of sign columns
  int b_signcols;               // last calculated number of sign columns
 ```
 a change in b_signcols_max should probably trigger a redraw

**Comment by lewis6991** [comment]
I've done a few changes to the signcolumn since this was raised. Does this issue still occur?

I have `signcolumn=auto:3` and have never seen this.
