### ISSUE TITLE
E5113: Error while calling lua chunk: vim.lua:269: Tried to call API function with vim.fn: use vim.api.nvim_set_keymap instead

### ISSUE THREAD

**Issue by hrqmonteiro** [neovim/neovim#14202]
If i install any version of Nvim newer than the #13875 commit, it simply breaks my config.

It keeps saying this error: `E5113: Error while calling lua chunk: vim.lua:269: Tried to call API function with vim.fn: use vim.api.nvim_set_keymap instead if i try to open.`

And if i replace all of my `vim.fn` lines in my config with this `vim.api.nvim_set_keymap`, it simply doesn't work either.

**Comment by mjlbach** [comment]
It's probably a plugin? run a grep over ~/.config/neovim for `vim.fn`

**Comment by hrqmonteiro** [comment]
I don't have a `~/.config/neovim` folder, only `~/.config/nvim`.

And yes, many of my configurations have the `vim.fn` line, that's the question, it broke my config. And it i replace it, as it said, it doesn't work either.

[Like this](https://github.com/hrqmonteiro/nvim/blob/d1c7752dd5d991dffcee2f98f5db4bb21de3721c/lua/lsp/compe.lua#L51), for example. But i have, like a hundred lines containing `vim.fn` on the config.

**Comment by mjlbach** [comment]
> I don't have a ~/.config/neovim folder, only ~/.config/nvim.

Yeah that was my bad, typo.

> Like this, for example. But i have, like a hundred lines containing vim.fn on the config.

And you still get the error after you've replaced all of these lines with the respective vim.api call? You must have missed some.

**Comment by hrqmonteiro** [comment]
> > I don't have a ~/.config/neovim folder, only ~/.config/nvim.
> 
> Yeah that was my bad, typo.
> 
> > Like this, for example. But i have, like a hundred lines containing vim.fn on the config.
> 
> And you still get the error after you've replaced all of these lines with the respective vim.api call? You must have missed some.

Actually no. I disabled all of the callings. And was starting enabling one by one. 

Even on the first plugin config, the replacement simply doesn't work. Is like it i haven't replaced at all...

I disabled it all and started configuring Lspconfig. Didn't work.Tried disabling that and configuring the next. Same thing.

**Comment by mjlbach** [comment]
I'm sorry, I don't understand exactly what you've tried.

You can no longer use **certain** `vim.fn` calls which have an equivalent impelmentation under vim.api, or you'll get this error message. You need to find, in your entire config/in your plugins, all disallowed references. I recommend a binary search :)

**Comment by teto** [comment]
update your plugins `:PlugUpdate` or whatever plugin manager you use , restart neovim and these errors will go away. All plugins should have updated by now.

**Comment by seandewar** [comment]
I had a look at your config, I think you missed [this line](https://github.com/hrqmonteiro/nvim/blob/214bc0134ce6862657b7dced67ab96192c5e5f69/lua/settings/utils.lua#L22).

**Comment by hrqmonteiro** [comment]
> I had a look at your config, I think you missed [this line](https://github.com/hrqmonteiro/nvim/blob/214bc0134ce6862657b7dced67ab96192c5e5f69/lua/settings/utils.lua#L22). I'm on mobile and can't do a thorough check, though.
> 
> In general, the `vim.api`functions are prefixed with `nvim_`. Grepping `fn.nvim_`should help locate instances that need replacing.

That file is a 10 days old commit, is not my actual machine config, though.

**Comment by hrqmonteiro** [comment]
For you guys to see explicitly what i am saying. I started again, disabled it all and i'm refactoring all of the code. And i pushed it to my repo again.

First problem i encountered, configuring [galaxyline](https://github.com/glepnir/galaxyline.nvim)

If you could please see it [here](https://github.com/hrqmonteiro/nvim/blob/190e40bab2697025094c48ffe24d2d3de583f3b9/lua/plugins/galaxyline.lua), i was using a lot of `vim.fn`

Now i tried first replacing it with `vim.api.nvim_set_keymap`, as the error is telling me, and it didn't work. And i didn't "miss" anything cause i was using `:Far` (the plugin). Then i tried `vim.api.nvim` as you can see in the latest commit [here](https://github.com/hrqmonteiro/nvim/blob/main/lua/plugins/galaxyline.lua)

It simply doesn't work.

![2021-03-24_06-42](https://user-images.githubusercontent.com/17055027/112288599-42ccb280-8c6c-11eb-875c-d61af21b1fa6.png)

**Comment by seandewar** [comment]
You're using `vim.api` incorrectly.

Functions like `empty()` and `expand()` are regular VimL functions, and are accessed via `vim.fn`.
Only the API functions (those that start with the `nvim_` prefix in their names) need to use `vim.api`.

See `:h api` for a list of such functions.
