### ISSUE TITLE
 `cursorline` and `matchparen` highlight is not cleared over virtual text with hl_mode = "combine"

### ISSUE THREAD

**Issue by lukas-reineke** [neovim/neovim#14209]
- `nvim --version`: NVIM v0.5.0-dev+1166-g070e084a6

#### init.vim
```vim
set cursorline

normal 5o

lua << EOF
vim.api.nvim_buf_set_extmark(
    0,
    vim.api.nvim_create_namespace("foo"),
    3,
    0,
    {virt_text = {{"    ", "String"}}, virt_text_pos = "overlay", hl_mode = "combine"}
)
EOF
```

```
nvim -u init.vim new
```

### Actual behaviour
When moving over the line with virtual text, the cursorline gets not cleared when there is virtual text with `hl_mode = "combien"`

![Screen Capture_select-area_20210325114631](https://user-images.githubusercontent.com/12900252/112412549-09766e80-8d62-11eb-80cb-2436348c5fb3.png)

This also happens for `matchparen`, when the virtual text is on the next line after the highlighted character. In this case, the virtual text should not be highlighted at all.

![Screen Capture_select-area_20210325115415](https://user-images.githubusercontent.com/12900252/112412753-607c4380-8d62-11eb-91b9-81f3cec7846f.png)
![Screen Capture_select-area_20210325115356](https://user-images.githubusercontent.com/12900252/112412745-5e19e980-8d62-11eb-8de1-5bef8ffacfdc.png)

### Expected behaviour

Highlighting gets cleared.

**Comment by lukas-reineke** [comment]
Some extra info, setting `colorcolumn` fixes the issue.

**Comment by lukas-reineke** [comment]
Some more information. It also happens for fold colors.

**Comment by adigitoleo** [comment]
Possibly related: https://github.com/junegunn/fzf/issues/2406

**Comment by zeertzjq** [comment]
Does this bug still exist?

**Comment by lukas-reineke** [comment]
I can't reproduce it anymore. Looks like it has been fixed :rocket:
