### ISSUE TITLE
[Win10]python not found even though in Windows PATH

### ISSUE THREAD

**Issue by pcause** [neovim/neovim#14206]
-NVIM v0.5.0-dev+1175-g1186f7dd9
- using windows terminal / cmd

run nvim-qt.exe
 start python and run checkhealth

get this for python3

## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          python3 not found in search path or not executable.
          python3.10 not found in search path or not executable.
          python3.9 not found in search path or not executable.
          python3.8 not found in search path or not executable.
          python3.7 not found in search path or not executable.
          python3.6 not found in search path or not executable.
          C:\Users\pshev\AppData\Local\Programs\Python\Python39\python.EXE does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

I have python 3.9 from the python foundation installed from the windows store  and it is in my path.  I can type python and get the prompt and version is 3.9.1.  the executable is called python and perhaps that is the problem??

**Comment by saadparwaiz1** [comment]
seems like you haven't installed pynvim?  As the error suggests:

> C:\Users\pshev\AppData\Local\Programs\Python\Python39\python.EXE does not have the "neovim" module. :help |provider-python|

Install the pynvim module. The details to install it can be found at `:help provider-python` but it should be as simple as running the following command if python3 is in your path:

` python3 -m pip install --user --upgrade pynvim`

**Comment by pcause** [comment]
thanks.  that was it.  perhaps checkhealth might suggest installing/updating pynvim directly.
