### ISSUE TITLE
`Alt-o` in insert mode behave like `Enter` rather than `Esc` and normal mode `o` command

### ISSUE THREAD

**Issue by bruhtus** [neovim/neovim#14211]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: 8.2) behaves differently? yes
- Operating system/version: Arch linux
- Terminal name/version: Alacritty/0.7.2
- `$TERM`: Alacritty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```
- Enter insert mode
- Type something
- `Alt-o` (Escape and enter normal mode `o` command, while in insert mode)
- Type another thing
- `Alt-u` (Escape and then use normal mode `u` command, while in insert mode) or `Esc` + `u` command

### Actual behaviour
Everything typed after using `Alt-o` in insert mode get undo rather than behave like `Esc` and then `o`, basically it behave like the usual `Enter`.

### Expected behaviour
`Alt-<normal-mode-command>` in insert mode should behave like using `Esc` and `<normal-mode-command>` so the expected behavior for `Alt-o` in insert mode is like using `Esc` and `o` command but it behave like using usual `Enter` instead.

The benefit of using `Alt-o` instead of `Enter` in insert mode is that i can control the undo history and only undo one change rather than everything that was typed. I can use `Alt-o` "normally" in vanilla vim so i think that's not alacritty problem but i might be wrong. I even use `nvim -N -u NONE` but still have this issue. I'd appreciate if you have hints to fix this problem.

**Comment by glacambre** [comment]
Is `<A-o>` actually bound to something in Neovim? I can't find any piece of documentation that mentions it.

**Comment by bruhtus** [comment]
> Is `<A-o>` actually bound to something in Neovim? I can't find any piece of documentation that mentions it.

It's not bound to something, when you press `Alt` + normal mode command in insert mode then it gonna `Esc` and execute those normal mode command. So `Alt-o` in insert mode should be equivalent to `Esc` and normal mode `o` command but for some reason the undo sequence when using `Alt-o` in insert mode is different from `Esc` and normal mode `o` command.

It is quite handy and could save a few keystrokes. You can check the help page for more `:h i_META`.

**Comment by bruhtus** [comment]
Recently i've tried mapping `Alt+o` in insert mode using inoremap but the undo sequence still different from using `Esc` + normal mode `o` command.

I've tried the following remap:
- `inoremap <M-o> <C-[>o`
- `inoremap <M-o> <C-c>o`
- `inoremap <M-o> <C-o>o`
but still got the issue (which is the undo sequence). If i use the original command `<C-[>o`, `<C-c>o`, and `<C-o>o`, i can get the expected undo sequence. That's really weird. 

Is no one knows what's going on?

**Comment by erw7** [comment]
This issue should have been fixed in #11706. However, it has not been backported to the release-0.4 branch.

**Comment by bruhtus** [comment]
> This issue should have been fixed in #11706. However, it has not been backported to the release-0.4 branch.

I see, i think i should try the master branch instead. Thank you!
