### ISSUE TITLE
LSP - active signature support

### ISSUE THREAD

**Issue by FTenner** [neovim/neovim#14217]
According to [this comment on reddit](https://old.reddit.com/r/neovim/comments/mdj3ct/using_nvim_integrated_lsp_i_cant_get_signature/gs9p418/)

> This is blocked by 2 things:

> - We don't currently support context for signature help
> - We haven't implemented a way handle the active signature return info, which includes amongst other things an interface for toggling between the active signatures.

**Comment by mjlbach** [comment]
This was closed in https://github.com/neovim/neovim/commit/af263711a368bcbdea66d086537316495ed64576
