### ISSUE TITLE
Bram needs help understanding redraw on neovim vs vim

### ISSUE THREAD

**Issue by reportaman** [neovim/neovim#14225]
Bram needs help in understanding difference between ``:redraw``/ ``:redraw!`` in neovim vs vim. neovim seems do be doing something that makes openGL based GPU-accelerated terminal emulators not stutter/flicker on redraws. Here's his call for help: https://github.com/vim/vim/issues/8002#issuecomment-807184475

**Comment by klooj** [comment]
this is misleading and not an issue. 

<img width="872" alt="image" src="https://user-images.githubusercontent.com/57016271/112819134-3ffa0500-9052-11eb-814a-21fc8da78979.png">

**Comment by reportaman** [comment]
@klooj What is misleading, and not an issue? To give you some benefit of doubt, if you just read his first sentence then there is no issue. The rest of it suggests he doesn't know why Vim has stutter on redraw, and neovim doesn't. Given he is a one man army of Vim's codebase, he has left it as a question for online community to investigate & answer what's the difference between redraw in both editors. It would be the least effort for neovim core team to answer his question.

**Comment by bfredl** [comment]
I would be happy to take a closer look into what the difference is. I've just been busy lately, and spent my FOSS time into stuff needed for neovim 0.5 release. But one difference that comes to mind: AFAIK vim only allows you to do a VALID redraw with `:redraw` or a CLEAR redraw with `<c-f>` or `:redraw!` or `:mode`, while neovim allows you to force a NOT_VALID redraw _without_ forcing a CLEAR using `:redraw!` (while `:mode` or `<c-f>` still does a CLEAR).

**Comment by reportaman** [comment]
@bfredl Sure man, take your time. I confirm that ``:mode`` stutters screen in neovim. So could be that the behavior of redraw, and mode are similar in Vim. Anyway, I'll wait for your final analysis, on what the exact difference is (so Bram knows if he can improve Vim's redraw behavior).

**Comment by mhinz** [comment]
I'm sure bfredl has a (very, very) long list of things in screen.c he wants to change, so he doesn't need this issue to stay reminded about it.

If this is about changes in Vim, it should be discussed in a Vim issue.
