### ISSUE TITLE
LuaJIT: attempt to index global 'jit' (a nil value)

### ISSUE THREAD

**Issue by MrAdityaAlok** [neovim/neovim#14228]
- `nvim --version`:  NVIM v0.5.0-dev+1178-gf0ace6d41
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Android 9
- Terminal name/version: Termux
- `$TERM`:  xterm-256color

### Steps to reproduce using `nvim -u NORC`
- start nvim
- then, `:lua print(jit.version)`

## Problem

When calling `:lua(jit.version)` when compiled with `PREFER_LUA=ON` results in
```
E5108: Error executing lua [string ":lua"]:1: attempt to index global 'jit' (a nil value)
```

**Comment by jamessan** [comment]
Don't do that without checking whether `jit` is nil first.  There's no requirement that nvim is built against LuaJIT.

**Comment by MrAdityaAlok** [comment]
Okay, tnanks
