### ISSUE TITLE
Virtual text in extended marks sticks around after nvim_buf_clear_namespace

### ISSUE THREAD

**Issue by phaazon** [neovim/neovim#14236]
- `nvim --version`: NVIM v0.5.0-dev+1171-g3e5efa50b
- `vim -u DEFAULTS` (version: ) behaves differently?: so farl, I can’t reproduce with `-u NONE`.
- Operating system/version: Linux archlinux 5.11.9-arch1-1 #1 SMP PREEMPT Wed, 24 Mar 2021 18:53:54 +0000 x86_64 GNU/Linux
- Terminal name/version: kitty 0.19.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

It is not easily reproducible with no config and I still struggle to determine what’s causing the issue.  The script I’m using to reproduce is this:

```lua
local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
local ns = vim.api.nvim_create_namespace('test')

-- print the namespace id so that we can call nvim_buf_clear_namespace manually to clear everything
print('namespace', ns)

for li, line in pairs(lines) do
  for col = 1, #line, 2 do
    vim.api.nvim_buf_set_extmark(
      0,
      ns,
      li - 1,
      col - 1,
      { virt_text = {{ 'a', 'ErrorMsg'}}, virt_text_pos = 'overlay' }
    )
  end
end
```

Simply open a (big? not sure, I tend to reproduce on bigger files with ~60+ lines) file, and `:luafile <the script>.lua`; it will spawn a lot of virtual texts and will print the namespace it has created them in. Simply call `:lua vim.api.nvim_buf_clear_namespace(0, <namespace id>, 0, -1)` to clear everything. _Sometimes_, some marks will persist.

### Actual behaviour

Some marks stick around even after calling `nvim_buf_clear_namespace`. What’s weirder is that calling it again, with the same argument, will delete the extended marks (i.e. that mitigation doesn’t seem to work in the [issue with hop.nvim](https://github.com/phaazon/hop.nvim/issues/57)).

### Expected behaviour

Marks should be cleared.

**Comment by phaazon** [comment]
If this is of any help for people writing plugins and having the same issue: calling `nvim_buf_clear_namespace` twice in a row seems to clear everything.

**Comment by HungryJoe** [comment]
I'm unable to reproduce this bug on the current neovim build using the procedure and script outlined above. I tested on 4 files: a `.c`, a `.h`, a `.py`, and a `CMakeLists.txt`. All were tested with both `nvim -u NORC` and `nvim -u NONE`.

My environment:

- **nvim --version:**
 ```
NVIM v0.5.0-dev+1280-gbb7d3790b
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/sam/External/Software_from_Source/neovim/build/config -I/home/sam/External/Software_from_Source/neovim/src -I/home/sam/External/Software_from_Source/neovim/.deps/usr/include -I/usr/include -I/home/sam/External/Software_from_Source/neovim/build/src/nvim/auto -I/home/sam/External/Software_from_Source/neovim/build/include
```
- **Operating system:** Debian GNU/Linux bullseye/sid
- **Terminal:** kitty 0.19.3
- **$TERM:** xterm-kitty

**Comment by phaazon** [comment]
Thanks. I’m going to switch off the hack in Hop and will see whether I still reproduce.

**Comment by maljaroudi** [comment]
I was unable to reproduce the bug as well. I have tested the script on a 10mb random text file with 100k lines on ```nvim -u NORC```. 

Environment:
version:
```
NVIM v0.5.0-dev+1354-ga282a177d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

- Operating System: Ubuntu 20.04.2 LTS

- Terminal: Gnome Terminal 3.36.2

**Comment by folke** [comment]
@phaazon can you reproduce this in files **without** multibyte characters? I've seen this before, but in my case at least it was due to some emoji or symbols from a nerd font where the calculate width by neovim doesnt match with the width the terminal (Kitty in my case) thinks it should be

**Comment by phaazon** [comment]
@folke sorry I didn’t see the notification for this thread and wasn’t able to actually test without the Hop hack. Doing it right now.

**Comment by phaazon** [comment]
Seems fine, thanks!

**Comment by phaazon** [comment]
![Screenshot_20210623_210732](https://user-images.githubusercontent.com/506592/123154384-0b39f600-d467-11eb-9891-6f187f2b79e7.png)

Whoopsies, looks like it’s still there!

**Comment by snezhniylis** [comment]
> ![Screenshot_20210623_210732](https://user-images.githubusercontent.com/506592/123154384-0b39f600-d467-11eb-9891-6f187f2b79e7.png)
> 
> Whoopsies, looks like it’s still there!

Are you sure the Neovim version you tested included the fix? I've been using modified `hop.nvim` with only one `nvim_buf_clear_namespace` call and haven't had this occur once. If I roll back to pre-fix Neovim version, I can easily reproduce the bug.
