### ISSUE TITLE
Checkhealth instructions for fixing pyenv issues, not updated to match other doc updates.

### ISSUE THREAD

**Issue by davidscotson** [neovim/neovim#14234]
I hit an issue with checkhealth reporting (correctly) that my python setup wasn't done correctly.

I'm not a big Python user, but I did recently start using pyenv to install multiple versions as I was doing some python development, which complicates matters somewhat.

Checkhealth correctly spotted my issues and told me how to fix them, the only error was a small change in the commands I should use. This seems to have been updated within some of the code and documentation, but not in others.

I'm not an experienced Python user or developer, but my understanding is that:

```pip install``` is no longer the recommended way to install python modules, because you may have multiple python's installed, both at local and system levels

```python -m pip install``` ensures that you're installing things within the correct python installation.

https://neovim.io/doc/user/provider.html#provider-python

The above section appears to have been updated to reflect this, and the linked wiki page is also using the newer version.

The more specific section for people using pyenv though, still seems to be using the old format:

https://neovim.io/doc/user/provider.html#python-virtualenv

And following those instructions didn't solve the problem for me. (It was installing the module, but not for the pyenv that I'd created and pointed Neovim at. The linked github doc seems similarly outdated)

It's not just the docs, there's part of the checkhealth output that tries to guide you as to the next steps, and I
I think the misleading/outdated message I saw there was coming from this code:

https://github.com/neovim/neovim/blob/60158dfb818cbc8132da31bdf3ab77def9bf070e/runtime/autoload/health/provider.vim#L405-L419

### Actual behaviour

:checkhealth output suggested I run ```pip install pynvim``` to fix an issue, which didn't work

### Expected behaviour

:checkhealth output should suggest I run ```python -m pip install pynvim```

The other instructions that got updated use python2/3 and suggest only using python without a number as a fallback, but I don't know enough about Python to know whether that is current best practice or not

Googling the error message found some neovim github issues, and in several of those it was suggest in comments that ```python -m pip install``` was now the recommended approach, and that worked for me.

**Comment by teto** [comment]
`python -m pip install pynvim` seems like a better option (but python is a mess with many answers). Is pip always available with the default python ? PR welcome.

**Comment by arusahni** [comment]
The latest guidance from Python's core developers is to [use `python -m pip install`](https://snarky.ca/why-you-should-use-python-m-pip/).

> is pip always available with the default python

Sometimes! :grimacing: It's included with Python 2 >=2.7.9 or Python 3 >=3.4 when installed from Python.org (or through Pyenv).  Outside of that, it depends on the distribution (e.g., Debian has a separate `python3-pip` package).

I'll open a PR this evening. Worst case, it starts a discussion :smile:
