### ISSUE TITLE
Option for undofile isn't persistent

### ISSUE THREAD

**Issue by hahuang65** [neovim/neovim#14247]
- `nvim --version`:
```
NVIM v0.5.0-dev+0ab88c2ea
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210317-91272-z76o3b/build/config -I/tmp/neovim-20210317-91272-z76o3b/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210317-91272-z76o3b/build/src/nvim/auto -I/tmp/neovim-20210317-91272-z76o3b/build/include
Compiled by hhhuang@6649L04

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-0ab88c2_1/share/nvim"

Run :checkhealth for more info
```

- Operating system/version: macOS 10.15.7
- Terminal name/version: iTerm 2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u foo.lua`

```bash
cat "vim.bo.undofile = true" > foo.lua
nvim -u foo.lua
```

```vim
:set undofile? " returns `undofile`
:e <any other file>
:set undofile? " returns `noundofile`
```

Shouldn't setting `undofile` in the `init.lua` make it set for all future buffers?

**Comment by hahuang65** [comment]
This seems to be a bug with `vim.bo`. If I run `set undofile`, it's set for every new buffer. If I run `:lua vim.bo.undofile = true`, it's only set for the current buffer. If I change buffers, it's unset.

However, `vim.bo.swapfile` does seem to persist across buffers, as does `expandtab`, `autoindent`, `smartindent`
Seems like it's specific to `vim.bo` with `undofile`.

**Comment by p00f** [comment]
Am I missing something here? You indeed want `undofile` to persist across buffers right? For that you use `vim.opt`
> vim.bo                                                  *vim.bo*
>        Get or set buffer-scoped |local-options|. Invalid key is an error.
>        Example: >
>            `vim.bo.buflisted = true`
>            `print(vim.bo.comments)`

**Comment by hahuang65** [comment]
I'm confused by your comment.

To clarify what I'm doing:
I'm setting `vim.bo.undofile = true` in my `init.lua` as well as in command-line mode.

It only gets set for the current buffer. If I edit another file, it gets unset. 

But using `vim.bo` on other settings, such as `swapfile`, doesn't have this issue.

**Comment by p00f** [comment]
Is that because `swapfile` is off by default and `undofile` is on by default? Does `vim.bo.swapfile  = false` persist across buffers?

**Comment by hahuang65** [comment]
@p00f that seems like it would make putting any `vim.bo` in your `init.lua` pointless?

Also, I checked, `expandtab`, `autoindent`, `smartindent`, `shiftwidth`, `softtabstop`, `tabstop` all carry over to new buffers.

**Comment by p00f** [comment]
> @p00f that seems like it would make putting any vim.bo in your init.lua pointless?

Yes? Those are probably for use inside functions

**Comment by hahuang65** [comment]
@p00f so what would be the way to set these options in `init.lua`? And why do those other options I listed work?

**Comment by p00f** [comment]
Did you try `vim.o`

**Comment by hahuang65** [comment]
@p00f yeah I tried it. It's not a global option. It doesn't do anything.
I have all these other `vim.wo` and `vim.bo` options set in `init.lua`. They all work. Except for `undofile`.
Something is weird here..

**Comment by shadmansaleh** [comment]
set both bo an o 
```lua
vim.o.undofile = true
vim.bo.undofile = true
```

**Comment by hahuang65** [comment]
Thanks guys. This is kind of crazy, but I can work around it like this for now.
