### ISSUE TITLE
Prevent LSP from analyzing files other than project files

### ISSUE THREAD

**Issue by etrnal70** [neovim/neovim#14241]
- `nvim --version`:NVIM v0.5.0-dev+1167-gf0e205aa2
- language server name/version: dartls 
- Operating system/version: Arch Linux

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: dartls: configuration checked.

</details>

<details>
<summary>lsp.log</summary>

</details>

### Steps to reproduce using `nvim -u NORC`
Trying to see the documentation of a flutter function, ended up crashing diagnostics
```
- Open up a project (flutter for this one)
- `:lua vim.lsp.buf.definition()` on one of builtin library

```

### Actual behaviour
Opening up lsp_workspace_diagnostics with telescope.nvim, the list are spammed with errors from analyzing the builtin library file (telescope even crashed though)

### Expected behaviour
It shouldn't analyze file outside of the project files

**Comment by fsouza** [comment]
I think this is a server behavior, so I don't know if changing this is even possible, but if it is, please don't make this change, or make it an option. Being able to jump around in files that are not in the initial workspace is important for debugging and exploring stuff.

This could be an option in telescope.nvim to not display diagnostics for files that are not inside the current directory or something like that.

**Comment by etrnal70** [comment]
> I think this is a server behavior, so I don't know if changing this is even possible, but if it is, please don't make this change, or make it an option. Being able to jump around in files that are not in the initial workspace is important for debugging and exploring stuff.

No i didn't mean to remove this feature. I also jump to definition alot. So it seems like it's an issue from dartls itself, since other lsp didn't have this problem.
