### ISSUE TITLE
Strange issue with "gj" and similar motions while folded

### ISSUE THREAD

**Issue by lervag** [neovim/neovim#14254]
- `nvim --version`: NVIM v0.5.0-dev+1183-g2ed5a7760
- `vim -u DEFAULTS` (version: 8.2.2653) behaves differently? No.
- Operating system/version: Arch Linux
- Terminal name/version: urxvt
- `$TERM`: xterm-256color

### Steps to reproduce

Given the following minimal `test.vim`:

```
set foldmethod=marker
```

and `test.txt`:

```
{{{

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

}}}
{{{

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

}}}
```

1. Start: `nvim -u test.vim test.txt` in a terminal with 80 columns.
2. `zR` to open all folds, then `jj` to move two lines down, then `zM` to close the folds
3. Press `gj`

### Expected behaviour

Same as `j`: expect to move to the next fold.

### Actual behaviour

"Nothing" happens. It requires 4 `gj` to move to the next fold. It seems it does not go to the next fold until `gj` would actually go to the next actual line.

### Appendix

I have to admit I am not 100% sure if this is a bug or just unexpected expected behaviour. I feel like this is not how it used to behave, but I can confirm that the same behaviour is found in Vim. Perhaps there is a shared patch that changed this in both editors, or perhaps I've only been delusional...

**Comment by lervag** [comment]
Just for context: The issue is slightly annoying since I use the following mappings:

```vim
nnoremap <expr> j v:count ? 'j' : 'gj'
nnoremap <expr> k v:count ? 'k' : 'gk'
xnoremap <expr> j v:count ? 'j' : 'gj'
xnoremap <expr> k v:count ? 'k' : 'gk'
```

A simple workaround, though:

```vim
nnoremap <expr> j v:count \|\| foldclosed('.') > 0 ? 'j' : 'gj'
nnoremap <expr> k v:count \|\| foldclosed('.') > 0 ? 'k' : 'gk'
xnoremap <expr> j v:count \|\| foldclosed('.') > 0 ? 'j' : 'gj'
xnoremap <expr> k v:count \|\| foldclosed('.') > 0 ? 'k' : 'gk'
```

**Comment by mhinz** [comment]
I can reproduce it and found it worked before a certain Vim patch. I reported it here: https://github.com/vim/vim/issues/8062

**Comment by lervag** [comment]
Great, happy to see progress! :)

**Comment by mhinz** [comment]
[Fix got merged](https://github.com/neovim/neovim/commit/62a3312b8873923faf276d22cbffa75448124a3c)!

**Comment by lervag** [comment]
Great! Thank you, very much appreciated!
