### ISSUE TITLE
Windows 10 init.lua not detected by Neovim

### ISSUE THREAD

**Issue by d-mceneaney** [neovim/neovim#14277]
Neovim does not seem to detect my init.lua file. 
My init.vim file is detected fine. 
Both files are in the same "XDG_CONFIG_HOME" location (but not active at the same time).
See screenshots below where init.lua is in the correct "XDG_CONFIG_HOME" location but is not detected.
Running checkhealth shows that nvim is looking for an init.vim file and ignoring the init.lua file
On reactivating my init.vim file, everything works fine.
I use the same init.lua file on my Debian 10 desktop and it is detected fine by Neovim.
From my I understanding of the documentation, the init.lua file should be detected and used in it's current location i.e."XDG_CONFIG_HOME". This is the same location as my init.vim file (but I do not have an init.vim and init.lua file active at the same time. I simply rename the files to swap between them for testing - see screenshots below)

- `nvim --version`: nvim-qt / NVIM v0.5.0-dev+1205-g3f7cd18c4
- Operating system/version: Windows 10
- Terminal name/version: powershell

### Actual behaviour
**Env Variables**
![image](https://user-images.githubusercontent.com/58395678/113444372-aa60cb80-93eb-11eb-855a-0fd17630e9d6.png)

**nvim-qt**
![image](https://user-images.githubusercontent.com/58395678/113444254-6f5e9800-93eb-11eb-8f90-dd083ea17b62.png)

**nvim via powershell**
![image](https://user-images.githubusercontent.com/58395678/113444785-79cd6180-93ec-11eb-9be6-b9e6b20c21b5.png)

**init.lua and init.vim files (not active at the same time) - init.vim is detected fine, but init.lua is not detected**
![image](https://user-images.githubusercontent.com/58395678/113444201-52c26000-93eb-11eb-9c5a-05c1a986888d.png)

### Expected behaviour
I expect the init.lua file to be detected by Neovim and to apply my config on startup, similar to how my init.vim file is detected.

![image](https://user-images.githubusercontent.com/58395678/113445551-fdd41900-93ed-11eb-8bdd-c0a9d99d1ca9.png)

**Comment by mjlbach** [comment]
Did you manually define XDG_CONFIG_HOME on windows? From `:help init.vim`

```
          The Nvim config file is "init.vim", located at:
                  Unix            ~/.config/nvim/init.vim
                  Windows         ~/AppData/Local/nvim/init.vim
          or if $XDG_CONFIG_HOME is defined:
                                  $XDG_CONFIG_HOME/nvim/init.vim
```

FWIW, my init.lua is at `C:\Users\michael\AppData\Local\nvim\init.lua` and `checkhealth` is fine.

**Comment by erw7** [comment]
Do you get any errors when you try to run the following command?

```
nvim -u NORC
:luafile C:\home\.config\nvim\init.lua
```

If `nlua_exec_file()` fails even if `init.lua` exists, as shown below, `$MYVIMRC` will not be set. I think that because `$MYVIMRC` is not set, `:checkhealth` looks for `init.vim` and gives a WARNING if it cannot find it. There is a high probability that this is not a bug in neovim, but a problem with your `init.lua`.

https://github.com/neovim/neovim/blob/6db3ba9df27619703947fee11493354ca3a06878/src/nvim/main.c#L1812-L1814

**Comment by d-mceneaney** [comment]
Thanks mjlbach ... yes, I have defined the XDG_CONFIG_HOME environment variable manually and this is working fine with init.vin.

erw7, thank you for your advice on segmenting the issue. Your suspicions were correct. I don't receive any errors on startup, but when starting with no config and then loading the init.lua file (as per your suggestion), I receive the error below. So, in summary no issue with Neovim, just something up with my gruvbox8 install.

Thanks again for your help.

![image](https://user-images.githubusercontent.com/58395678/113487715-8cf63500-94b1-11eb-94f1-77a0eb10ce2c.png)
