### ISSUE TITLE
Connecting to docker via neovim

### ISSUE THREAD

**Issue by ankitpal1029** [neovim/neovim#14274]
Hey guys i'd like neovim to have similar functionality to what vs code's connect to remote container feature ,this is mainly because i work with docker on angular projects but since it's on docker the node_modules is empty when viewed from outside thus plugins like coc.nvim stop working and the intellisense becomes close to useless.

Is there something like this implemented already or in the works?

**Comment by bfredl** [comment]
Needs to be a bit more specific. Is this for connecting to a LSP server running inside a container?

**Comment by ankitpal1029** [comment]
@bfredl i was thinking more on the lines of "connecting" neovim(bear with me for the lack of technical terms since i'm new to a lot of these things) to the docker session rather than setting up a neovim instance inside docker and develop from it

**Comment by bfredl** [comment]
sure, but what would you _use_  connection for? I suppose apart from LSP you want to read/save files to the container?

**Comment by ankitpal1029** [comment]
> sure, but what would you _use_ connection for? I suppose apart from LSP you want to read/save files to the container?

That is correct

**Comment by glacambre** [comment]
@ankitpal1029 Yes, using `scp://` is a good workaround. But note that neovim already supports the client/server paradigm - most Neovim GUIs allow connection to an already-running neovim instance.
Even cooler, [Goneovim](https://github.com/akiyosi/goneovim) has an `--ssh=...` flag that lets you connect to a remote neovim instance (just make sure neovim is available on the remote computer/in the container).

**Comment by ankitpal1029** [comment]
> Even cooler, [Goneovim](https://github.com/akiyosi/goneovim) has an `--ssh=...` flag that lets you connect to a remote neovim instance through ssh (just make sure neovim is available on the remote computer/in the container).

That is pretty cool, although i'm not sure if the maintainer of the project which i am running will be ok with installing an nvim instance i'll probably use it in personal projects though

> @ankitpal1029 Yes, using `scp://` is a good workaround. But note that neovim already supports the client/server paradigm - most Neovim GUIs allow connecting to an already-running neovim instance.

Oh i see , i'm actually having trouble connecting to the particular container with scp can you help me out in that regard

**Comment by glacambre** [comment]
Does the container have an ssh server running? Is that ssh server listening on a specific port? What's the user for that ssh server? What's the password? Are you putting all this information in your `scp://` uri?

**Comment by mjlbach** [comment]
I think the OP more concretely is asking for vscode-remote functionality in neovim core. I'm copying and pasting a comment I made on reddit on the three ways this could be implemented:

* Remotely attaching the GUI/TUI to a neovim instance running on the server. This, IMO, is the cleanest and most practical solution. You don't need to worry about daemonizing a subset of neovim's functionality and many GUIs already support this. There is an open PR to add this functionality to the TUI [here](https://github.com/neovim/neovim/pull/10071). A plugin could handle copying over your local config and handling the remote attaching. This is very practical, and close to being done.

* Add a remote daemon that is launched on the server, implements a subset of neovim's functionality, has an API to handle server local commands (running ripgrep, communicating with language servers, piping text/UI data like the results of aforementioned commands, and handling synchronization between the client and remote buffer state). This is basically what the vscode remote plugin does to my understanding. It would be a huge engineering effort, and I would estimate would require at least a GSoC student level of time/commitment.

* Implement something like emacs's TRAMP. TRAMP is slightly different from vscode in that it opens a remote shell to handle commands (like ripgrep, and starting language servers), communicates with that remote shell to synchronize editor state, and syncs a local copy of your document to/from the server. This would be less work than the remote daemon, more work than the remote TUI, and probably would require standardization around the neovim TRAMP api. I will say, the experience of this would likely be worse than the remote daemon (slower synchronization by far), but would carry the advantage of not needing to copy and launch the remote daemon to the linux remote host.

**Comment by ankitpal1029** [comment]
@glacambre it shows that ssh is running 
![image](https://user-images.githubusercontent.com/49815751/113452034-d9ddfb00-9420-11eb-813c-b35319c7727a.png)

but when i run 
apt list --installed | grep openssh-server
from inside the docker it doesn't return anything
the port is 22 

i ran the command 
![image](https://user-images.githubusercontent.com/49815751/113452281-5244bc00-9421-11eb-9c29-8530869509d3.png)
but then it shows this
![image](https://user-images.githubusercontent.com/49815751/113452262-49ec8100-9421-11eb-8f7a-6be35f661d8d.png)

**Comment by glacambre** [comment]
@ankitpal1029 Can you log in with a regular ssh session, e.g. `ssh root@172.18.0.3:22`?

**Comment by justinmk** [comment]
>  There is an open PR to add this functionality to the TUI [here](https://github.com/neovim/neovim/pull/10071).

Remote TUI was merged.

>  something like emacs's TRAMP.

Discussed in https://github.com/neovim/neovim/issues/21635
