### ISSUE TITLE
Vimscript adding to clipboard does not work: `let @+ = "foo"`

### ISSUE THREAD

**Issue by bruno-** [neovim/neovim#1427]
Hi,
I searched for this issue, couldn't find anything so I'm opening a new one.

I'm on OS X Yosemite. Nvim version: `NVIM 0.0.0-alpha+201411050933`
I got the clipboard integration working by following the instructions from "nvim-clipboard", all works good.

The only thing I noticed is not working is setting the clipboard register via vimscript:
```viml
let @+ = "foo"
let @* = "bar"
```

**Comment by bfredl** [comment]
Was fixed in #1182
