### ISSUE TITLE
disable clipboard

### ISSUE THREAD

**Issue by horseinthesky** [neovim/neovim#14280]
- `nvim --version`: NVIM v0.5.0-dev+1180-gacd643bd4
- `vim -u DEFAULTS` (version: ) behaves differently?: don't know
- Operating system/version: Ubuntu 20.04 WSL
- Terminal name/version: Windows terminal 1.6.10571.0
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
Not exactly a bug but some behavior I don't understand how to handle.

I am under Ubuntu WSL which has `xclip` utility (and $DISPLAY env variable) but no x11 server listening on the Windows side.
I have the following issue with the build-in clipboard: every time I call `:registers` NVIM tries to connect to Windows clipboard (and obviously fails but with a long ~1 min timeout):
```
clipboard: error invoking xclip: Error: Can't open display: 172.23.176.1:0
```

There are two workarounds:
1) `unset $DISPLAY` - in this case everything works great - I get my registers fast but on startup NVIM loads `.local/share/nvim/runtime/autoload/provider/clipboard.vim` which significantly increases startup time
![image](https://user-images.githubusercontent.com/19948672/113472162-c6a34d80-9469-11eb-9ab0-41013e8cb912.png)
2) `unset $DISPLAY` but set up
```
vim.g.clipboard = {
  name = "xclip",
  copy = {
    ["+"] = "xclip -ib",
    ["*"] = "xclip -ip"
  },
  paste = {
    ["+"] = "xclip -ob",
    ["*"] = "xclip -op"
  },
  cache_enabled = true
}
```
In this case, startup time is fast (no clipboard.vim) but I get
```
clipboard: error: Error: Can't open display: (null)
```
error when running `:registers`

I have also tried to
```
set clipboard+=unnamed
```
but this change nothing.

My question is: is there a way to say NVIM not to try to connect to the clipboard at all i.e. disable the clipboard completely?

**Comment by matveyt** [comment]
If you don't need clipboard at all, you can setup "void" clipboard. Kind of

```VimScript
let g:clipboard = {"name": "void", "copy": {}, "paste": {}}
let g:clipboard.copy["+"] = {-> v:true}
let g:clipboard.paste["+"] = {-> []}
let g:clipboard.copy["*"] = g:clipboard.copy["+"]
let g:clipboard.paste["*"] = g:clipboard.paste["+"]
```

**Comment by horseinthesky** [comment]
> ```
> let g:clipboard = {"name": "void", "copy": {}, "paste": {}}
> let g:clipboard.copy["+"] = {-> v:true}
> let g:clipboard.paste["+"] = {-> []}
> let g:clipboard.copy["*"] = g:clipboard.copy["+"]
> let g:clipboard.paste["*"] = g:clipboard.paste["+"]
> ```

In this case, it behaves the way when I don't set up `g:clipboard` at all i.e. tries to use xclip which gives me this ~1 min lag.

**Comment by matveyt** [comment]
Have you even tried?

**Comment by horseinthesky** [comment]
Sure. How then could I know?

**Comment by matveyt** [comment]
Reload Neovim, run `:checkhealth provider` etc. It absolutely cannot run `xclip` if user clipboard was set up. This is nonsense.

**Comment by horseinthesky** [comment]
With
```
let g:clipboard = {"name": "void", "copy": {}, "paste": {}}
let g:clipboard.copy["+"] = {-> v:true}
let g:clipboard.paste["+"] = {-> []}
let g:clipboard.copy["*"] = g:clipboard.copy["+"]
let g:clipboard.paste["*"] = g:clipboard.paste["+"]
```
it behaves this way:
1) If I open NVIM and do `:checkhealth` (where I do of course find
```
## Clipboard (optional)           
  - OK: Clipboard tool found: void
```
)
then I can close checkhealth buffer and everything works fast and with no lags.
2) If I open NVIM and don't do `:checkhealth` every `:registers` call has a lag.

**Comment by mhinz** [comment]
With `set clipboard=` in your vimrc, the clipboard provider (`clipboard.vim`) should never be called. You can double-check that with `:scriptnames`.

There is also a [guard](https://github.com/neovim/neovim/blob/6db3ba9df27619703947fee11493354ca3a06878/runtime/autoload/provider/clipboard.vim#L5-L7) at the top of `clipboard.vim`, so putting `let g:loaded_clipboard_provider = 1` in your vimrc should work just as well.

**Comment by horseinthesky** [comment]
@mhinz `let g:loaded_clipboard_provider = 1` is exactly what I was looking for. Thank you.

**Comment by matveyt** [comment]
Setting `g:loaded_clipboard_provider` will, of course, deny Neovim from accessing external tools, but, at the same time, it will annoy with multiple error messages (`:h message-history`), because clipboard provider is essentially broken.
The real problem is that `autoload/provider/clipboard.vim` should not be sourced on startup before any user actions, such as `:checkhealth` or `:reg +` or something like that. So this is all due to wrong configuration (maybe `set clipboard=unnamed`?) and a failure to do the tests under clean Neovim instance `nvim --clean` or at least `nvim -u NORC --noplugin`.

**Comment by horseinthesky** [comment]
@matveyt Actually there are no error messages on startup.

But
```
let g:loaded_clipboard_provider = 0 (or 1)
```
breaks providers block in checkheath
```
health#provider#check                                                                    
========================================================================                 
  - ERROR: Failed to run healthcheck for "provider" plugin. Exception:                   
    function health#check[21]..health#provider#check[1]..<SNR>99_check_clipboard, line 10
    Vim(let):E117: Unknown function: provider#clipboard#Executable                       
```

I would prefer a solution that breaks nothing but I don't have any for now.

Running NVIM with:
```
nvim -u NORC --noplugin
```
still has a lag.

**Comment by matveyt** [comment]
Setting custom `g:clipboard` must be done before `autoload/clipboard/provider.vim` was sourced for the first time (`:help :scriptnames`). That's the whole point. Of course, if you do `nvim --clean` and `:reg +` then it tries to load clipboard provider while no custom `g:clipboard` is set. So it sticks with `xclip` and stores the config internally making it persist for the rest of session.

**Comment by horseinthesky** [comment]
@matveyt Setting `g:clipboard` at the very beginning of my init.vim seems a perfectly working solution.

Could you pls tell how to set it up in lua? Especially `{-> v:true}` or ` {-> []}` parts.

```
vim.g.clipboard = {
  name = "void",
  copy = {
    ["+"] = true,
    ["*"] = true
  },
  paste = {
    ["+"] = {},
    ["*"] = {}
  }
}
```
gives me `E5108: Error executing lua Vim:clipboard: provider returned invalid data` error when running `:registers`.

**Comment by matveyt** [comment]
@horseinthesky Do it in VimScript.

**Comment by horseinthesky** [comment]
@matveyt I'm moving everything to Lua.

**Comment by matveyt** [comment]
`:help nvim_exec()`
