### ISSUE TITLE
Update eval.txt on FunctionRef with more info

### ISSUE THREAD

**Issue by dhilst** [neovim/neovim#14283]
- `nvim --version`: NVIM v0.4.4
- `vim -u DEFAULTS` (version: ) No
- Operating system/version: macOS 10.15.7 (19H524)
- Terminal name/version: macOS Terminal Version 2.10 (433) 
- `$TERM`: xterm-256-color

### Actual behaviour

I was following the eval.txt doc and in FunctionRef I got this ([here is the line in code](https://github.com/neovim/neovim/blob/master/runtime/doc/eval.txt#L161))

```
Note that binding a function to a Dictionary also happens when the function is
a member of the Dictionary: >

	let myDict.myFunction = MyFunction
	call myDict.myFunction()

Here MyFunction() will get myDict passed as "self".  This happens when the
"myFunction" member is accessed.  When assigning "myFunction" to otherDict
and calling it, it will be bound to otherDict: >
```

I spend some time trying to figure out what MyFunction means in this context and even asked on stackoverflow about it: https://stackoverflow.com/q/66935825/652528

After the answer it's obvious that `MyFunction` should be a function ref, but I spent some time struggling to understand why I can't simple do this

```
function! MyFunction() dict
    echo "foo"
endfunction

let myDict = {}
let myDict.myFunction = MyFunction
```

There are two things hidden here
* The function should have `dict` attribute attached to it
* The `MyFunction` in `let myDict.myFunction = MyFunction` should be `let myDict.myFunction = function("MyFunction`) 

I would suggest to update this in the eval.txt, adding an example function and replacing `MyFunction` by `function('MyFunction')`, I'm opening a PR for this

### Expected behaviour

vimscript lack of material on internet so having the official docs to be as much as reproducible as possible would be ideal.

**Comment by mhinz** [comment]
Runtime changes like this should be reported to [vim/vim](https://github.com/vim/vim), since they develop and document Vimscript (and we merge their patches), while the Nvim community gravitates more and more towards using Lua as a replacement while keeping backward-compatibility as much as possible.

Thanks!

**Comment by dhilst** [comment]
No problem, thank you
