### ISSUE TITLE
Unzip is a dependency of building neovim but it is not checked for

### ISSUE THREAD

**Issue by magnus-ISU** [neovim/neovim#14285]
- `nvim --version`: trying to build nvim
- Operating system/version: Artix after a core install
- Terminal name/version: tty
- `$TERM`: linux

### Steps to reproduce

Create a new VM
Install other dependencies of neovim, but not `unzip`
Run the makefile

### Actual behaviour
Failure to build 13% through installation

### Expected behaviour
Failure to build immediately with an appropriate error message

**Comment by magnus-ISU** [comment]
The build worked fine and picked up where it left off once I installed unzip so the priority for this is so close to zero that it is negative. Still thought I should share

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/wiki/Building-Neovim#arch-linux
