### ISSUE TITLE
gf doesn't jump in the terminal

### ISSUE THREAD

**Issue by GGCristo** [neovim/neovim#14288]
### Actual behavior
when you press 'gf' in the terminal, it opens the file, but it doesn't respect your ``switchbuf`` option, this means that it change the current buffer terminal for the new file, instead of doing the "jump" if is already open.
If I copy the path in a regular buffer and use ``gf`` it  jumps correctly.
### Expected behavior
``gf`` and related should do a jump if the buffer it's already open.

**Comment by mhinz** [comment]
Are you talking about `switchbuf=useopen`? I can't even reproduce that in a normal buffer with `gf`.

Could you please specify the exact steps using `nvim -u NORC`?

**Comment by GGCristo** [comment]
Ups, sorry I am too dumb, you are right. The thing is I have a "Bufferline", so when I do ``gf`` the file I currently am change with the new buffer and the previous buffer join the buffer list and with the Bufferline in the top "pointing" to the new buffer it gives me the feeling that I am doing a jump.

Anyway I take this issue to ask. If I want to do a real jump with the path under my cursor, should I write a mini-script?, or do you know any command that already do this?. Maybe the ``:drop`` can help
