### ISSUE TITLE
keymap <leader>hp not work

### ISSUE THREAD

**Issue by ivyxjc** [neovim/neovim#14297]
- `nvim --version`: NVIM v0.5.0-dev+1221-g9b2d4ff62
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: 5.9.16-1-MANJARO  
- Terminal name/version: Konsole/20.12.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```mnvi
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```
I set the following keymap in config.
```mnvi
let mapleader=' '
noremap <leader>hp <c-o>
noremap <leader>tp <c-o>
noremap <leader>ap <c-o>
```

### Actual behaviour
`<leader>hp` does not work, and the other 2 key map works.

### Expected behaviour
`<leader>hp` works as `<c-o>`

**Comment by elianiva** [comment]
are you sure? I just tried it and it works perfectly fine.

**Comment by teto** [comment]
works fine here too. You can check if it was mapped with `:verbose map <leader>hp `

**Comment by ivyxjc** [comment]
I find that one plugin bind the keymap. Sorry to bother you guys.
