### ISSUE TITLE
I can't change the text of the Lsp diagnostics

### ISSUE THREAD

**Issue by hrqmonteiro** [neovim/neovim#14295]
```
vim.fn.sign_define("LspDiagnosticsSignError",
                   {texthl = "LspDiagnosticsSignError", text = "", numhl = "LspDiagnosticsSignError"})
vim.fn.sign_define("LspDiagnosticsSignWarning",
                   {texthl = "LspDiagnosticsSignWarning", text = "", numhl = "LspDiagnosticsSignWarning"})
vim.fn.sign_define("LspDiagnosticsSignHint",
                   {texthl = "LspDiagnosticsSignHint", text = "", numhl = "LspDiagnosticsSignHint"})
vim.fn.sign_define("LspDiagnosticsSignInformation",
                   {texthl = "LspDiagnosticsSignInformation", text = "", numhl = "LspDiagnosticsSignInformation"})
```

These are not working. It just shows the regular symbol and the default highlight:

![2021-04-05_10-49](https://user-images.githubusercontent.com/17055027/113580937-cbe4d180-95fc-11eb-9231-d2e057fae33d.png)

**Comment by mjlbach** [comment]
I'm not sure what the issue is. Are you trying to eliminate the virtual text? This is a usage question and belongs on discourse.

**Comment by teto** [comment]
@mjlbach what do you think about referencing the discourse in the template ?

**Comment by mjlbach** [comment]
> @mjlbach what do you think about referencing the discourse in the template ?

Pro, we should also probably include a reference to the minimal init.lua from nvim-lspconfig.

**Comment by hrqmonteiro** [comment]
> I'm not sure what the issue is. Are you trying to eliminate the virtual text? This is a usage question and belongs on discourse.

I'm trying to change the "text", as i said. I am trying to replace this default arrow to another symbol. 
And also the highlight is not working too.

**Comment by mjlbach** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/13316262/113628702-204a7a00-961a-11eb-9b5e-976262e86394.png)

**Comment by mjlbach** [comment]
That's my init.lua ^

**Comment by hrqmonteiro** [comment]
Literally doesn't work here. At all.

Which is your version? I rebuilt from source the nightly version right know, and still doesn't work.

**Comment by mjlbach** [comment]
It's an issue in your config. You can try this minimal init.lua https://paste.sr.ht/~mjlbach/8561cf81b2d520a7ef51ae72c5c92b0443c67351

**Comment by hrqmonteiro** [comment]
I was able to make it work with the minimal config. But the error is showing two lines below:

![2021-04-05_20-08](https://user-images.githubusercontent.com/17055027/113637462-04130100-964b-11eb-91d5-df984251bc43.png)

**Comment by mjlbach** [comment]
That's expected, you can repeat the same thing with

```lua
local 

x = t'est
```

If you disagree with the reporting of the diagnostics locations that you can take it up with the maintainer of the language server, we have no control over where the diagnostics get painted.

**Comment by hrqmonteiro** [comment]
But this wasn't showing like this until like two days ago when i started having this error..

**Comment by mjlbach** [comment]
Well, we haven't changed anything in core, and reading out the raw response from sumneko in the following example shows we are painting the symbol exactly where sumneko wants us to:


`{      code = "redefined-local",      message = "Redefined local `paq`.",      range = {        end = {          character = 3,          line = 26        },        start = {          character = 0,          line = 26        }      }`

<img width="518" alt="Screen Shot 2021-04-05 at 4 24 39 PM" src="https://user-images.githubusercontent.com/13316262/113638395-99060200-962b-11eb-9d50-442a9f747532.png">
