### ISSUE TITLE
lsp: error executing vim.schedule lua callback on android

### ISSUE THREAD

**Issue by MrAdityaAlok** [neovim/neovim#14296]
- `nvim --version`:  0.5-dev from master branch
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Android 9
- Terminal name/version: [Termux](https://termux.com)
- `$TERM`: xterm-256color

### Actual behaviour

When using lsp's this error arises frequently

```
Error executing vim.schedule lua callback: ....termux/files/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:394: Vim:E474: E
rror while dumping encode_tv2json() argument, itself: attempt to dump function reference

```

**Comment by mjlbach** [comment]
Going to need more info, this isn't enough for a reproduction. What were you doing? Example repo? Also I'm not even sure we officially support android and I have no way to test :/

**Comment by MrAdityaAlok** [comment]
> Going to need more info, this isn't enough for a reproduction. 

@mjlbach This issue occurs only when using completion plugins like (nvim-compe)[https://github.com/hrsh7th/nvim-compe] or (completion-nvim)[https://github.com/nvim-lua/completion-nvim]

> What were you doing when the bug occured? Example repo on which the bug occurs?

I was using nvim-compe and pyright lsp and editing a python file in my  `$HOME` dir 

>  Can you reproduce with the [minimal init.lua](https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua).
Also I'm not even sure we officially support android and I have no way to test :/ 

I too cannot reproduce this issue, it occurs randomly.....probably during signature help by lsp

**Comment by MrAdityaAlok** [comment]
I tested once more and it seems that this issue is only with `pyright`  whenever it is called for completion the issue arises

Here is a screen recording

https://user-images.githubusercontent.com/73517616/113622532-6c6ade00-965d-11eb-8f55-cd808a47bfed.mp4

**Comment by mjlbach** [comment]
Do you get the issue with omnifunc based completion?

**Comment by MrAdityaAlok** [comment]
> Do you get the issue with omnifunc based completion?

No. It occurs with every keystroke (as seen in the video)

**Comment by mjlbach** [comment]
I was implying that this issue seems isolating to a plugin, and if you disable that plugin than the omnifunc based completion works fine in neovim, so it's not a problem with our completion handler, but something unique to nvim-compe.

**Comment by MrAdityaAlok** [comment]
> I was implying that this issue seems isolated to a plugin, and if you disable that plugin than the omnifunc based completion works fine in neovim, so it's not a problem with our completion handler

Hmm...I too thought that 😄

>  but something unique to nvim-compe

Then I will open an issue in nvim-compe

Thank you for your help!

**Comment by mjlbach** [comment]
There could be a weird bug with json_encode on android, I don't really know. I meant more that this is probably going to require debugging on the nvim-compe side as well to see what these plugins re doing that triggers this bug

**Comment by MrAdityaAlok** [comment]
> There could be a weird bug with json_encode on android, I don't really know. I meant more that this is probably going to require debugging on the nvim-compe side as well to see what these plugins re doing that triggers this bug

I will try to look into it

**Comment by MrAdityaAlok** [comment]
@mjlbach  I tried with completion-nvim plugin and still the same error with every keystroke.

It seems that the bug is in `json_encode`, would you please look into it. 

Plus , it wasn't before the last [pre-release v0.5.0-dev+1225-gbbdd00203 ](https://github.com/neovim/neovim/releases/tag/nightly)

**Comment by mjlbach** [comment]
You're saying if you build https://github.com/neovim/neovim/commit/bbdd0020333eab13f42c7431fd61814230b799bd from source, you get the bug, but if you build https://github.com/neovim/neovim/commit/cc9f7e717b80208fec79150b99c17eba04535496 from source, you don't get the bug? Nothing has changed in json_encode. The patch did affect vim.fn.complete, which may have something to do with it. Android isn't really a supported platform and I have no way to test.

**Comment by MrAdityaAlok** [comment]
Cannot get neovim-lsp work on Android.....So closing it.

**Comment by MrAdityaAlok** [comment]
@mjlbach  I tried without auto-completion plugins, still the same issue . It seems that the issue is with builtin neovim-lsp and not any other plugin.
Could you do anything? 🥺

**Comment by mjlbach** [comment]
No, I don't have an android device and I don't believe we officially support it (It could be a lua on android issue, luv on android issue, libuv on android issue...). I re-opened the issue, but I won't be able work on this.

**Comment by MrAdityaAlok** [comment]
Okay

**Comment by MrAdityaAlok** [comment]
Issue was fixed.

**Comment by mjlbach** [comment]
What do you mean? What changed?
