### ISSUE TITLE
netrw incorrect documentation about netrw-c in netrw-quickmap

### ISSUE THREAD

**Issue by jurisbu** [neovim/neovim#14292]
- `nvim --version`: NVIM v0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Arch
- Terminal name/version: xfce-terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:h netrw-quickmap
<snip>
	   a	Cycles between normal display,                       |netrw-a|
	    	hiding (suppress display of files matching g:netrw_list_hide)
	    	and showing (display only files which match g:netrw_list_hide)
--->	   c	Make browsing directory the current directory        |netrw-c|
	   C	Setting the editing window                           |netrw-C|
	   d	Make a directory                                     |netrw-d|
<snip>

```
This quick documentation specifies that to make browsing directory to be current directory one needs to press `c` which does not work and is misleading, only reading on `netrw-c` one finds note that apparently `cd` should be used instead. Very misleading and non-intuitive. 

### Actual behaviour

Documentation is misleading and wrong.

### Expected behaviour

Documentation has to be up-to-date and match actual behaviour.

**Comment by mhinz** [comment]
Fixed on master (probably due to https://github.com/neovim/neovim/pull/14424)
