### ISSUE TITLE
starting neovim inside tmux 'types' the background string, seems related to PR #14094

### ISSUE THREAD

**Issue by otijhuis** [neovim/neovim#14298]
- `nvim --version`: NVIM v0.5.0-dev+2c4e9c524
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: macOS Big Sur 11.2.3
- Terminal name/version: Kitty 0.19.3
- `$TERM`: tmux-256color
- tmux: 3.1c

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

In my tmux `M-]` is bound to next window. If another window is open then it jumps to that window and the text `11;rgb:1b1b/2b2b/3333\` appears.

If another tmux window isn't open it will execute the text as neovim commands, like it was typed.

It looks like it has to do with PR #14094 . It's a tmux change and has to do with background colors. It also contains the string `"\x1b]11;?\x07"` which looks very similar to what happens. My current background color is `#1b2b33` which is also part of the text that is visible in the next window.

No problems when neovim is started in a shell without tmux running.

### Expected behaviour

Start neovim without anything happening.

**Comment by erw7** [comment]
The key sequence for `M-]` sent by the terminal is `<ESC>]`. The OSC sequence response  (get background color, etc.) starts with OSC(`<ESC>]`), so if a command is assigned to `M-]`, the command is executed by `<ESC>]` and the rest of the response is passed to the application. As a result, this phenomenon occurs.

I can't think of a smart way to solve both #14058 and this problem (We probably need a way to control the getting of the background color by command line options, etc). I don't use either, so I don't have an opinion on which solution should be prioritized, #14058 or #14298 .

**Comment by otijhuis** [comment]
If it's a normal sequence I can change my keybindings. I've used the keybinding for quite a while and had no problems until now so that's why I created the issue. It's the one thing I *really* dislike about the terminal, all those sequences that make a lot of useful keybindings impossible. I'll close the issue and try to find another keybinding that makes sense :)

**Comment by erw7** [comment]
vim can support both #14058 and #14298 by setting `t_RB`. So I thought about changing `get_bg` to get it from `RB` of terminfo, which would allow nvim to work like vim.

@przepompownia Would it be difficult for you to create a terminfo entry for tmux-256color with `RB=\EPtmux;\E\E]11;?\7\E\\` using the following steps?

```
infocmp -x tmux-256color >tmux-256color.ti
echo "\t"'RB=\EPtmux;\E\E]11;?\7\E\\\\,' >> tmux-256color.ti
tic -x -o ~/.terminfo tmux-256color.ti
```

What do developers who are familiar with the terminal think of this idea? There is a problem with `TMUX_WRAP`, as described in the following comments. Therefore, I think we should remove all TMUX_WRAP, but does anyone have an opinion?

https://github.com/neovim/neovim/blob/370469be250de546df1a674d6d5cd41283bb6b3c/src/nvim/tui/tui.c#L1994-L1996

**Comment by przepompownia** [comment]
@erw7 I can make and test such terminfo if #14094 gives side effects. I would like to know about version to test after potential revert it or fixing the bug in another way.

**Comment by przepompownia** [comment]
Should I change `tmux-256color` to `screen-256color` if I have `set -g default-terminal "screen-256color"`? I am not familiar with the hell of terminal internals.

**Comment by ruffson** [comment]
This is quite unfortunate, I use `M-[` to copy and `M-]` to paste from tmux for a long time. And so every time I now open neovim, it pastes my clipboard into the buffer. It took me some time to figure out what was going on.
I would very much appreciate if a real solution for this can be found.

**Comment by kieron-dev** [comment]
We are seeing this problem with tmux (version 3.0a), but only when two users are sharing a session. As soon as the other user detaches, nvim is fine again.

We bisected the issue to commit c266c2f36ea56220268d2b19364e28815e338c2f.

We don't have `M-[` or `M-]` bound in tmux. In fact the problem occurs using vanilla tmux without a config file.

cc: @mnitchev

**Comment by satu** [comment]
Confirming it happens consistently on many different terminals, with default (empty) configs on both tmux and nvim sides.

Quick proof at https://share.nyx.xyz/m5Lyz4Zjt8S

**Comment by taketwo** [comment]
@erw7 Is there something we (as in affected users) can do to help to find a solution to this problem?

**Comment by satu** [comment]
Can the original commit be reverted until a solution is found? I'm maintaining my own fork with that commit reverted and I haven't had any problems. Not sure what's the commit was meant to fix though.

**Comment by ilAYAli** [comment]
I had a similar problem, but I was able to work around the problem by forcing tmux to assume 256 color support and write utf-8 to the terminal: `tmux -2u new -As name`

**Comment by tek** [comment]
doesn't work here, @ilAYAli

**Comment by ruffson** [comment]
Doesn't work for me either. What about the suggestion of rolling back that change? Is whatever was added really worth breaking people's setups?

**Comment by satu** [comment]
any update here?

**Comment by fenoloftaleina** [comment]
Not a solution per se, but it's worth trying with an empty tmux.conf and without X11 forwarding (no `-Y`). It worked for me FWIW, yet to see what's not working because of that.
