### ISSUE TITLE
PowerShell Maximize Issue 

### ISSUE THREAD

**Issue by Putnug1122** [neovim/neovim#14293]
![Screenshot (119)](https://user-images.githubusercontent.com/62296958/113574583-fbbcc500-964e-11eb-9d4e-e6373e8f7c71.png)

When I try neovim in PowerShell it's getting a little bit weird :)

OS : Windows 10 Home
Neovim Version : 0.4.4

**Comment by erw7** [comment]
Thanks for the report, but this is a duplicate of #13082.
