### ISSUE TITLE
Terminal mode: <C-w>w doesn't work correctly only when cursor is on last line in terminal window

### ISSUE THREAD

**Issue by reportaman** [neovim/neovim#14305]
- `nvim --version`:
```
NVIM v0.5.0-dev+nightly-120-g1186f7dd9
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210323-5919-1tszxxi/build/config -I/tmp/neovim-20210323-5919-1tszxxi/src -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210323-5919-1tszxxi/build/src/nvim/auto -I/tmp/neovim-20210323-5919-1tszxxi/build/include
Compiled by reportaman@reportamans-mac-mini.lan

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-1186f7d_2/share/nvim"
```
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: macOS 11.2.3
- Terminal name/version: iTerm2 (doesn't really matter, happens on other terminal emulators too like WezTerm, etc)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u cww.vim`

```vim
" file: cww.vim
function! s:termCww()
    let w:termcww=1
    exec 'wincmd w'
endfunction
tnoremap <silent> <C-w><C-w> <C-\><C-n> :call <SID>termCww()<CR>
tnoremap <silent> <C-w>w <C-\><C-n> :call <SID>termCww()<CR>
function! s:termWinEnter()
    if  &filetype==#'terminal' && mode()==#'n' && w:termcww==1
        let w:termcww=0
        startinsert
    endif
endfunction
augroup TermCww
    autocmd!
    autocmd WinEnter * call <SID>termWinEnter()
    autocmd TermOpen * setlocal filetype=terminal | startinsert
augroup END
```

### Actual behaviour
Let's say one creates some splits using ``:vs`` and ``:sp``, and opens a terminal in one of the splits using ``:terminal``. Given the logic of above config file ``cww.vim``, it is expected that ``<C-w>w`` or ``<C-w><C-w>`` will move the focus to other splits, and when moving back to the split with terminal, it will start insert mode again if that window was in left in terminal mode. This works well, unless the cursor in the terminal window is on the last line. If the cursor is on last line, insert mode is not automatically started when focus is moved back to terminal window.

### Expected behaviour
Terminal window should execute user functions, mappings exactly the same irrespective of what line the cursor is on.

### mp4 video showing the problem:

As can be seen, I need to press ``i`` to enter terminal mode only when cursor is on last line, for all other lines it automatically enters terminal mode when focus moves to the same window.

https://user-images.githubusercontent.com/71736629/113780176-b5657580-96e3-11eb-8f6a-7c67c38cb8ac.mp4

**Comment by zeertzjq** [comment]
Remove the space before the colon.

This is because you have a space before the colon, and a space is a motion command. In the last line of a buffer, this motion fails, and the following of the mapping is not executed. See `:h map-error`.
