### ISSUE TITLE
Statusline mode() update regression caused by #14270 commit 7959aaf

### ISSUE THREAD

**Issue by bphilly96** [neovim/neovim#14316]
### Steps to reproduce using `nvim -u NONE`
Build any version of nvim after commit 7959aaf
Run `nvim -u NONE`
Type `:setlocal statusline=%{mode()}` and hit enter
Statusline should now show `n`
Now type `:`
Statusline still shows `n`
### Expected behaviour
After typing `:` statusline should show `c`
### Explanation
When entering command line mode, nvim should refresh the statusline but commit 7959aaf seems to have made it only refresh if statusline is non empty. However I think it only checks the global statusline, not the window-local statusline.
This can be confirmed by doing
```
:set statusline=randomwords
:setlocal statusline=%{mode()}
```
Now the statusline will refresh correctly when entering command line mode since global statusline is non-empty.
To confirm this is a regression, I built neovim without 7959aaf and the local statusline refreshed correctly even when global statusline was empty.
### Possible fix
If the window-local statusline is non-empty then refresh the statusline when entering command line mode.
Also the test added in 7959aaf didn't pick up on this problem because it only set the global statusline in the test. It might be worth adjusting the test to also check the window-local statusline.

**Comment by bfredl** [comment]
does this also affect latest vim (as specified in the issue template)?

**Comment by chrisbra** [comment]
ping @brammool

**Comment by bphilly96** [comment]
I just checked latest vim and the issue is present there also.

**Comment by chrisbra** [comment]
relevant vim patch: https://github.com/vim/vim/commit/d8db8383926cb8729417d9515cbfaf455dbbd8d1
