### ISSUE TITLE
nvim_open_win(): support normal (non-floating) windows

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#14315]
Hello. Perhaps this is already planned, but I couldn't find it. Obviously feel free to close if it the request exists.

We have `vim.api.nvim_open_win`, but it only supports opening floating windows.

It'd be nice to have a way to create normal windows from Lua. In particular, this code I wrote (or really cargo culted) to do so with command mode is slightly clunky to me:

```lua
  vim.cmd "vsplit"
  vim.cmd(string.format("buffer %d", bufnr))

  local winnr = vim.api.nvim_win_get_number(0)

  for name, value in pairs(_DEFAULT_WIN_OPTIONS) do
    vim.api.nvim_win_set_option(winnr, name, value)
  end
  vim.api.nvim_set_current_win(current_window)
```

It'd instead be nice to have either a new function `nvim_create_win` (or `nvim_split_win`, doesn't matter much) or an extension of `nvim_open_win` for non-floating windows which looked like:

```lua
vim.api.nvim_create_win(
    bufnr_to_put_in_the_window_or_0_to_use_the_current_buffer,
    opts = {
        vertical = true,
        window_opts = {
            'filename' = 'foobar',
            'wrap' = false,
            'textwidth' = 37,
        }   
    }
)
```

and which returns the `winnr` (as `nvim_buf_create` returns the `bufnr`).

**Comment by Julian** [comment]
I'm aware that `nvim_open_win`, the corresponding floating window API, doesn't support that `window_opts` proposal for setting initial window options -- I threw it in since I think that's convenient, but if it's distracting from the core issue here, that's not the main point of this ticket (so it can be ignored or I can remove it). I'm not proposing that the two APIs should look meaningfully different from each other.

**Comment by bfredl** [comment]
I think we should reuse the existing `nvim_open_win` and `nvim_win_set_config` . the latter is needed as you could also _place_ an existing window in a specific split position.

**Comment by euclidianAce** [comment]
Hey, I'm attempting to take a stab at this and am running into some issues.
Using `nvim_open_win` to open a split is working fine but the main issue is with `nvim_win_set_config` and trying to turn a float into a split.

@bfredl, you seem to be the one to talk to about this so pinging you.

I initially tried to use `win_split`, but that just splits the current window, so I tried to use `win_split_ins` with the existing float `win_T` pointer, but that seems to cause an infinite loop. (And closing the window first causes a segfault). I guess I'm asking for some advice of how to properly get a split to open with the floating window handle that properly transfers the relevant window info. (And maybe some pointers about the stuff in `window.c`.)

I can push my current work as a draft pr if you'd like more info!

**Comment by willothy** [comment]
This is functional now in #25550 if anyone wants to test it / help find weird behavior. It may have bugs still but it works and docs are updated :)
