### ISSUE TITLE
tempname() doesn't always ensure parent dir exists

### ISSUE THREAD

**Issue by dbarnett** [neovim/neovim#1432]
On the first call to tempname(), nvim returns a handle to a nonexistent file like `/tmp/nvimpJVmXL/1` in a nvimpJVmXL/ directory that _does_ exist. But sometimes that directory can get deleted and all subsequent tempname() usages that assume the directory exists will fail. It would be useful to ensure that dir exists on each tempname() call so the whole vim session doesn't get poisoned, even if there's nothing to be done for code using lingering references to previous tempname() paths.

FWIW, vim doesn't consider this a bug (https://groups.google.com/d/topic/vim_use/ef55jNm5czI/discussion), and vim itself assumes the parent dir exists in system().

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/11284
