### ISSUE TITLE
Shorter $XDG_DATA_HOME/nvim/plugins dir

### ISSUE THREAD

**Issue by abitrolly** [neovim/neovim#14329]
Installing plugins is a rather frequent task, so why not to make the plugin dir easier to type by making it as short as possible? I guess `$XDG_DATA_HOME/nvim/plugins` it the shortest path possible with the chosen XDG standard.

### Actual behaviour

`nvim` plugins are located in $XDG_DATA_HOME/nvim/site/plugin

### Expected behaviour

`nvim` plugins are located in $XDG_DATA_HOME/nvim/plugins

**Comment by matveyt** [comment]
`nvim/site` is a non-standard location. Normally plugins go under `$XDG_DATA_HOME/nvim/pack/<bundle>/{start,opt}`.

I guess you got it from `:h packages` where it says "Let's assume your Vim files are in the "~/.local/share/nvim/site" directory" and so on. This section should probably be rewritten as it looks confusing at best.

**Comment by mhinz** [comment]
If you install plugins frequently, use a plugin manager.

They often let you set the directory where to install plugins (except when they're based on built-in packages, as mentioned by @matveyt).

**Comment by abitrolly** [comment]
@matveyt yes, I got it from `nvim` docs. But `$XDG_CONFIG_HOME/nvim/pack/<bundle>/{start,opt}` is even longer! Any rationale why it should be so long?

@mhinz I though `neovim` focuses on usability. And I want to improve the out of box usability of handling plugin. The existing path is not compatible with `vim` anyway and needs special handling. So why copy this practice?

**Comment by bfredl** [comment]
Those are just the defaults. you can adjust `&rtp` and/or `&pp` yourself, or let a plugin manager do it for you.

**Comment by abitrolly** [comment]
@bfredl yes, I understand that all these are defaults and everything can be changed. However, the ability to customize is only a part of good usability, and in that I believe `neovim` is no different from `vim`. Another big part of good usability are defaults that lower entry barrier for new users and simplify interaction. The design process to figure out these defaults can be opinionated choice, like sticking to status quo, or it could involve measurements, A/B testing, etc.

**Comment by bfredl** [comment]
The behaviour of packages has already been discussed countless times (and already improved in some minor ways c.f. vim). Everyone knows no one is super happy with the status quo, what is needed is concrete proposals not more repetition of the same complaints.

**Comment by abitrolly** [comment]
@bfredl if nobody is happy and there is a lot of repetition, where there is no FAQ that sums up the arguments so far? I've just discovered that I can open new files with plugins like NERDTree yesterday. :D I can't make a thorough plugin management proposal at this point, but I did the concrete proposal is to have `$XDG_DATA_HOME/nvim/plugins` dir for all plugins. So far the comments were.

1. actually, the real path is even longer. docs need to be updated
2. use plugin manager
3. customize your dir
4. it was discussed countless times

Now we are in deep offtopic with no comments why shorter `$XDG_DATA_HOME/nvim/plugins` path is bad, no links to refer people curious about it. I don't mind writing a FAQ entry if there is any explanation, but I don't understand what's going on.

**Comment by jamessan** [comment]
https://github.com/neovim/neovim/pull/3470#issuecomment-151642023 explains why `$XDG_DATA_HOME` is suggested for plugins.

https://github.com/neovim/neovim/pull/3470#issuecomment-151656788 explains why it's `nvim/site/ inside of `$XDG_DATA_DIRS`.

If you don't like the long pathname for `$XDG_DATA_HOME/nvim/site`, then you can ignore that and put things under `$XDG_CONFIG_HOME/nvim` instead.

If a long pathname is really the only complaint you have about nvim, then we've done a good job.

**Comment by abitrolly** [comment]
@jamessan yep. The only complaint for this ticker is that the recommended plugin path is that long
```
$XDG_CONFIG_HOME/nvim/pack/<bundle>/{start,opt}
```
But if it can be any path under `$XDG_DATA_HOME/nvim/` for `neovim` to auto discover plugins, then I'd fix the docs to recommend
```
$XDG_CONFIG_HOME/nvim/plugins
```

**Comment by matveyt** [comment]
The rationale behind plugin path name:

1. `pack` is arbitrary root name. It was chosen over `plugins`, because the builtin feature is commonly called `packages`, while `plugins` may refer to all other plugins as well. In fact, `plugin` subdir can be created under `$XDG_CONFIG_HOME/nvim` path just like under any other `runtimepath` node. Then having both `plugin` and `plugins` together would look silly.
2. `<bundle>` is arbitrary name chosen by user or plugin manager. This extra level is needed to support multiple plugin managers per single installation. And also to have non-managed local plugins (for example, I created several plugins and I don't need to download them from github to my own PC).
3. `start` vs. `opt` is needed to support manual startup. If plugin resides in `opt` it will not be loaded until `:packadd plugin-name` has been executed. For example, this could be useful to disable rarely used plugins, or Neovim-specific plugins while sharing the same config for both Vim and Neovim, etc.

P.S. If you have more questions you can ask at vi.stackexchange.com instead of opening issues here.

**Comment by abitrolly** [comment]
@matveyt thanks for the clarification. While I am curious about the evolution path and rationale back then, my goal was to propose an improvement. If there was only `vim`, I wouldn't care, but for `neovim` so far I am glad there is some discussion. I guess the greater goal for me would be a unification of plugin scheme for different tools, like `$ZSH_CUSTOM/plugins/` for Oh-My-Zsh etc.

1. `nvim/plugins` and not `plugin`, because it answers the question "where do I put my plugins in?" Exposing internal `packages` details doesn't make newcomers feel better. What kind of problem does this knowledge about `plugins` feature named `packages` as a builtin help them to solve?
2. Why can not plugin managers store their plugin management meta data the other way than using `<bundle>`? If I understand it right, `neovim` does recursive scan for dirs containing plugin signatures, and managers can drop them in any dir (under `nvim/pack` currently).
3. Is it possible to have a `start` or `opt` file inside plugin directory instead of the whole dir indirection level? That turning them on and off looks like a job for plugin manager. For me it makes sense to have the ability to enable/disable plugins without moving their files around.

**Comment by matveyt** [comment]
@abitrolly Sorry for late response.

I think you miss the main point: `packages` is an optional feature. It is no way forced. You are still able to manage `runtimepath` manually, as it was in Vim7 and earlier, and to build any directory layout you like.

**Comment by abitrolly** [comment]
@matveyt `neovim` claims to provide both extensibility and usability. Your comment only addresses the former and I am interested in the latter.

**Comment by matveyt** [comment]
@abitrolly I don't see why it is poorly usable. To address your items:

1. All subdirectory names are fixed. Like `colors/`, `syntax/`, `after/`, `plugin/` and such. That's how it is designed. So there's no reason to allow to change `pack/` to `plugins/` specifically. As it was chosen once, it stays forever.
2. Plugin managers can do anything they want. `packages` are not forced, as I said already.
3. That does not make sense as plugins can not be unloaded (in Vim "plugin" is not really "module" but "config"). I mean, a plugin manager may provide some option to bypass loading specfic plugin, but to apply it one has to save config and to re-load main application. So it's pretty much useless.

**Comment by abitrolly** [comment]
> As it was chosen once, it stays forever.

That's not about usability. Usability means that if there is a more intuitive way of doing things with referencing or learning description of current hacks, then it should be adopted. The only thing to discuss is how to provide backward compatibility for existing users.

**Comment by matveyt** [comment]
Usability is a KISS. Providing an extra option to set _subdir_ name is not intuitive.

**Comment by abitrolly** [comment]
Which option? I am not discussing extra option here. I am talking about KISS defaults.

**Comment by matveyt** [comment]
@abitrolly The defaults won't be changed just because of single person's wish. It is pointless to discuss this. You're free to fork/patch/build and install anything you want on your own PC instead.

**Comment by abitrolly** [comment]
@matveyt just because a single person opened an issues, it doesn't mean that's only one person wish. Make a usability check about defaults if you really care and not just using the word for marketing.
