### ISSUE TITLE
LSP: default 'textDocument/codeAction' handler does not work well with multiple clients 

### ISSUE THREAD

**Issue by MagicDuck** [neovim/neovim#14330]
- `nvim --version`:
```
NVIM v0.5.0-dev+1231-g48e805728
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1617858555107.local

Features: +acl +iconv +tui
```
- Operating system/version: macos

### Steps to reproduce:
1. configure LSP such that you will have 2 or more clients connected to a buffer that provide `textDocument/codeAction` capability. In my case I have tsserver and diagnosticls.
2. move over a symbol with code actions from both and execute: `:lua vim.lsp.buf.code_action()`

### Actual behaviour
Because the handlers execute whenever the servers respond, and the default handler requires user input:
https://github.com/neovim/neovim/blob/91cdc11984465287539ed8f63716bb371f440ea1/runtime/lua/vim/lsp/handlers.lua#L126
what will happen is that you are first prompted to choose a code action from the first one and if you escape out of that, you are then prompted with code actions from the second.
It just feels a bit weird...

### Expected behaviour
I am not sure what the correct solution is here. In my particular case I handled it by:
1. first handler call pops up telescope.nvim with first list of actions
2. second handler call updates telescope.nvim with to include second group of actions 
I think this is nice as you see actions as they come in.

**Comment by mhartington** [comment]
Seems similar to https://github.com/neovim/neovim/issues/13766
