### ISSUE TITLE
Signcolum number breaking on master

### ISSUE THREAD

**Issue by yashLadha** [neovim/neovim#14331]
- `nvim --version`: NVIM v0.5.0-dev+1233-g82ac44d01
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: mac os catalina
- Terminal name/version: Alacritty 0.7.2
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

Happens randomly on some javascript files and in yaml or some other file

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
![image](https://user-images.githubusercontent.com/18033231/114159266-3a9a9580-9943-11eb-8d10-2819114d71f9.png)

### Expected behaviour
Should have consistent numbering

**Comment by mhinz** [comment]
If you ever find a way to reproduce it, we may be able to debug it. Like this, it's almost impossible since you clearly haven't used `nvim -u NORC` nor provided us with a minimal config.

**Comment by teto** [comment]
check `:h relativenumber` `:h number` and how they interact with eachother. It's expected in a special mode. You can check the actual values with `:verbose set relativenumber`

**Comment by teto** [comment]
with a better look at it there may be an issue but we need a minimal way to reproduce

**Comment by mhinz** [comment]
Yes, a screenshot alone won't help us debug this.

**Comment by teto** [comment]
feel free to reopen once you get reproducable steps

**Comment by chrisbra** [comment]
Isn't that just a case of `:set signcolumn=number`? https://vimhelp.org/options.txt.html#'signcolumn'
