### ISSUE TITLE
Vim Scrolling Slowly

### ISSUE THREAD

**Issue by joaovdiasb** [neovim/neovim#14357]
**Configs**
- NVIM v0.4.4
- With `vim -u DEFAULTS` works normally
- MacOS 11.2.3
- Alacritty and iTerm2 (both same experience)

**Problem**
The scroll is very slow. I tried:
- Disable most plugins and it partially resolves
- Same thing without tmux
- ttyfast, lazyredraw, nocursorline, synmaxcol, syntaxoff

**Obs.:** works on Windows 10 with this configuration (neovim-qt)

**Current config**
https://gist.github.com/joaovdiasb/02b38bbb55bb4f726cfd73ecf9b51939

**Comment by elianiva** [comment]
can you try with the latest master? There's a chance it has been fixed.

**Comment by joaovdiasb** [comment]
> can you try with the latest master? There's a chance it has been fixed.

tried, same thing :(

**Comment by teto** [comment]
without a clear reproduction course it's too vague to act upon. 

> Disable most plugins and it partially resolves

So what about disabling all of them ? what about vim with same config.
Is it the same for all filetypes or just one etc.

If you prefer  to keep it vague then neovim.discourse.group/ is a better avenue.

**Comment by joaovdiasb** [comment]
> without a clear reproduction course it's too vague to act upon.
> 
> > Disable most plugins and it partially resolves
> 
> So what about disabling all of them ? what about vim with same config.
> Is it the same for all filetypes or just one etc.
> 
> If you prefer to keep it vague then neovim.discourse.group/ is a better avenue.

Without all of them works well, also vim.
I think it's a sum of all plugins, but the essentials ones (syntax, theme, coc, lightline)
long vertical lines is harder, i will start a discussion there neovim.discourse.group and get more performance information.
Thanks all.
