### ISSUE TITLE
Js wrong syntax highlight

### ISSUE THREAD

**Issue by kaldown** [neovim/neovim#14356]
- `nvim --version`: NVIM v0.5.0-dev+1233-g82ac44d01
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: arch
- Terminal name/version: alacritty 0.7.2 (5ac8060b)
- `$TERM`: tmux

### Steps to reproduce using `nvim -u NORC`
`nvim -u NORC ` this file https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2356

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
`nvim -u NONE`:
![2021-04-13_748x115_scrot](https://user-images.githubusercontent.com/3754017/114593262-cbdf7400-9c83-11eb-9880-3c16ee1a3a4d.png)

**Comment by theHamsta** [comment]
Can you post the source code you are referring to as plain text

**Comment by kaldown** [comment]
example.ts:

```
  videoConnectivityTest = async (): Promise<CheckVideoConnectivityFeedback> => {
    this.createReadinessHtml('videoconnectivity-test', 'spinner-border');
    const videoInput = this.getVideoInputDeviceID();
    const videoConnectivityResp = await this.meetingReadinessChecker.checkVideoConnectivity(
      videoInput
    );
    this.createReadinessHtml(
      'videoconnectivity-test',
      CheckVideoConnectivityFeedback[videoConnectivityResp]
    );
    return videoConnectivityResp;
  };

```

**Comment by theHamsta** [comment]
Did you parse as typescript? Can you show us the parse tree as per https://github.com/nvim-treesitter/playground? The typescript parser has some problems to parse the parameter list on my machine of your first example.

This is how it looks on my machine top as JS / bottom as Typescript
![image](https://user-images.githubusercontent.com/7189118/114611030-dc521780-9ca0-11eb-8e78-aa7ad2111632.png)

Only your original example seems to have some issues
![image](https://user-images.githubusercontent.com/7189118/114612132-05bf7300-9ca2-11eb-8a99-024489b5d1f6.png)

```
eventDidReceive(name: EventName, attributes: EventAttributes): void {
  this.log(`Received an event: ${JSON.stringify({name, attributes})}`);
    const {meetingHistory, ...otherAttributes} = attributes;
    switch (name) {
    case 'lol': 1
    }
}
```
for some reason it keeps the highlights of the template string on my machine.

**Comment by mhinz** [comment]
He did not even mention treesitter. :) But yes, I can't reproduce it with default `typescript` highlighting.

**Comment by theHamsta** [comment]
Ooops :sweat_smile: Thought it was on nvim-treesitter repo...

**Comment by kaldown** [comment]
@theHamsta could you please tell me more about 
> Well, I kind of can reproduce it with typscript (left) and syntax=1. With JS only it looks fine

1) `syntax=1` is throwing an error.
2) what to do to get same example as your right image, without installing additional plugins?

**Comment by theHamsta** [comment]
1. > syntax=1 is throwing an error.
  
      I meant `set syntax=1`. I thought you had a problem with tree-sitter because usually people have problems with this new alternative to traditional regex highlighting

2. @kaldown the problematic line is only the one with `JSON.stringify` and it is only problematic in Typescript. The right is with Javascript highlighting.

**Comment by kaldown** [comment]
Thanks.
But I still can't understand how to fix that straight away.
Should I force syntax to determine `.ts` as `.js`?

**Comment by theHamsta** [comment]
@kaldown no, this was just a general observation. Maybe it helps to find the issue in `ts`

**Comment by mhinz** [comment]
I think it doesn't find a proper point to sync on with the defaults, because `class DemoMeetingApp` is so huge.

The main issue is that TypeScript is hell to parse. :] There's nothing necessarily wrong with the syntax file, though.

To fix it, use `:syntax sync minlines=1500` or even `:syntax sync fromstart`. See `:h :sync-syn` for more info.

If it often happens to you, put this in your vimrc:

```vim
autocmd FileType typescript syntax sync ccomment minlines=1500
```

**Comment by theHamsta** [comment]
@mhinz but it already fails to parse this example which has only a few lines and JS doesn't:
```
eventDidReceive(name: EventName, attributes: EventAttributes): void {
  this.log(`Received an event: ${JSON.stringify({name, attributes})}`);
    const {meetingHistory, ...otherAttributes} = attributes;
    switch (name) {
    case 'lol': 1
    }
}
```
> The main issue is that TypeScript is hell to parse.

Probably due to this...

**Comment by mhinz** [comment]
Then it should definitely reported to [the maintainer of the typescript syntax file](https://github.com/neovim/neovim/blob/d19348923e01bdc729fcb513327dd386be1be98e/runtime/syntax/typescript.vim#L6). If they fix it, Vim will merge and we will merge it from them. Or just use that yats plugin directly. :)
