### ISSUE TITLE
Install from Source fails with Protocol "https" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by ianpan870102** [neovim/neovim#14354]
- `nvim --version`: commit 4a36ec6 master branch
- Operating system/version: Windows 10 + WSL2 Ubuntu 20.04
- Terminal name/version: Windows Terminal v1.6.10571.0
- `$TERM`: xterm-256color

### Steps to reproduce

Git clone this master repo and `cd` into it.

Run `make CMAKE_BUILD_TYPE=RelWithDebInfo`

Fails with the following output

```text
mkdir -p build
touch build/.ran-third-party-cmake
make -C .deps
make[1]: Entering directory '/home/ianpan/Downloads/neovim/.deps'
make[2]: Entering directory '/home/ianpan/Downloads/neovim/.deps'
make[3]: Entering directory '/home/ianpan/Downloads/neovim/.deps'
make[3]: Leaving directory '/home/ianpan/Downloads/neovim/.deps'
[  9%] Built target libvterm
make[3]: Entering directory '/home/ianpan/Downloads/neovim/.deps'
make[3]: Leaving directory '/home/ianpan/Downloads/neovim/.deps'
make[3]: Entering directory '/home/ianpan/Downloads/neovim/.deps'
[  9%] Performing download step for 'lua-compat-5.3'
-- file: /home/ianpan/Downloads/neovim/.deps/build/downloads/lua-compat-5.3/v0.7.tar.gz
-- downloading...
     src='https://github.com/keplerproject/lua-compat-5.3/archive/v0.7.tar.gz'
     dst='/home/ianpan/Downloads/neovim/.deps/build/downloads/lua-compat-5.3/v0.7.tar.gz'
     timeout='none'
CMake Error at /home/ianpan/Downloads/neovim/third-party/cmake/DownloadAndExtractFile.cmake:92 (message):
  error: downloading
  'https://github.com/keplerproject/lua-compat-5.3/archive/v0.7.tar.gz'
  failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1


make[3]: *** [CMakeFiles/lua-compat-5.3.dir/build.make:90: build/src/lua-compat-5.3-stamp/lua-compat-5.3-download] Error 1
make[3]: Leaving directory '/home/ianpan/Downloads/neovim/.deps'
make[2]: *** [CMakeFiles/Makefile2:258: CMakeFiles/lua-compat-5.3.dir/all] Error 2
make[2]: Leaving directory '/home/ianpan/Downloads/neovim/.deps'
make[1]: *** [Makefile:84: all] Error 2
make[1]: Leaving directory '/home/ianpan/Downloads/neovim/.deps'
make: *** [Makefile:105: deps] Error 2
```

Before "making", I also successfully installed the dependencies with the following commands:

```text
sudo apt install gperf luajit luarocks libuv1-dev libluajit-5.1-dev libunibilium-dev libmsgpack-dev libtermkey-dev libvterm-dev libutf8proc-dev
sudo luarocks build mpack
sudo luarocks build lpeg
sudo luarocks build inspect
```

### Actual behaviour

As reproduced above.

### Expected behaviour

Make succeed, able to proceed to `sudo make install`.

**Comment by saadparwaiz1** [comment]
does libcurl on your system support https? what's the output of `curl --version`

**Comment by ianpan870102** [comment]
Hi @saadparwaiz1 , this is the output of `curl --version`

```text
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by erw7** [comment]
@ianpan870102 The procedure you show does not follow the Wiki description. If you follow the instructions in the wiki, will it still fail to build?

https://github.com/neovim/neovim/wiki/Building-Neovim#ubuntu--debian

It is possible that cmake was not built with OpenSSL support enabled, but if you installed it with `sudo apt install cmake`, this should not be the case. I can't reproduce this in my environment `Windows 10 + WLS Ubuntu 20.04`.

**Comment by ianpan870102** [comment]
@erw7 thanks for the response. I actually followed this guide: https://github.com/neovim/neovim#install-from-source

Please correct me if I'm mistaken -- doesn't "build" and "install" mean the same thing? My goal is just to get neovim nightly **so I can use tree-sitter with it**.

**Comment by erw7** [comment]
> Please correct me if I'm mistaken -- doesn't "build" and "install" mean the same thing?

Build is just one of the ways to install. Therefore, you can also install it by other means. 

> My goal is just to get neovim nightly so I can use tree-sitter with it.

If that is your goal, the easiest way is to use the [nightly build on the release page](https://github.com/neovim/neovim/releases/tag/nightly). Please follow the description of Linux(x64).

**Comment by erw7** [comment]
> I actually followed this guide: https://github.com/neovim/neovim#install-from-source

I don't have a clean environment so I can't test it, but the steps on the above page may not be enough to build HEAD. We need to update README.md.

**Comment by ianpan870102** [comment]
> If that is your goal, the easiest way is to use the nightly build on the release page. Please follow the description of Linux(x64).

Thanks so much! I can now successfully run `./nvim.appimage` to launch an instance of neovim.

What is the recommended way to "move this executable" to be on my $PATH? I was thinking perhaps manually putting under `/usr/bin/`. What do I have to do if I want to simply type `nvim` in my terminal (in any directory) and launch neovim nightly? 

(Sorry if this seems to be a simple question)

**Comment by erw7** [comment]
> What is the recommended way to "move this executable" to be on my $PATH? I was thinking perhaps manually putting under /usr/bin/. What do I have to do if I want to simply type nvim in my terminal (in any directory) and launch neovim nightly?

I would either copy it to `/usr/local/bin` or to `~/bin` and add `~/bin` to the `$PATH`.

**Comment by ianpan870102** [comment]
Cheers!
For those wondering, it's really a simple 2-step:

```text
cp nvim.appimage nvim
 mv nvim /usr/local/bin
```

Done.
