### ISSUE TITLE
Bundled libluv failes to build, cmake syntax error

### ISSUE THREAD

**Issue by dilyn-corner** [neovim/neovim#14362]
- `nvim --version`: 0.4.4
- Operating system/version: Linux

### Steps to reproduce

Attempting to build `neovim` with all bundled dependencies, using the following:

```
make \
    CMAKE_BUILD_TYPE=Release \
    CMAKE_INSTALL_PREFIX=/usr \
    CMAKE_INSTALL_LIBDIR=lib
```

### Actual behaviour

Build fails for libluv:

```
[72/89] Performing build step for 'luv-static'
ninja: job failed: cd /home/thermatix/.cache/kiss/proc/2660/build/neovim/.deps/build/src/luv-static-build && /usr/bin/cmake -DLUA_COMPAT53_DIR=/home/thermatix/.cache/kiss/proc/2660/build/neovim/.deps/build/src/lua-compat-5.3 --build . && /usr/bin/cmake -E touch /home/thermatix/.cache/kiss/proc/2660/build/neovim/.deps/build/src/luv-static-stamp/luv-static-build
CMake Error: Unknown argument --build
CMake Error: Run 'cmake --help' for all supported options.
```

### Expected behaviour

`neovim` compiles. 

0.4.4 was previously buildable; the only updates that have happened related to it are with `cmake`; currently using 3.20.1. 

Using https://github.com/neovim/neovim/pull/14167 it builds just fine, though it seemed related to https://github.com/neovim/neovim/pull/12676 at first.

**Comment by rashil2000** [comment]
Facing the same issue with MinGW. Any workarounds?

**Comment by janlazo** [comment]
```
$ git log --oneline --grep luv-static 
ce70edb Merge pull request #13302 from blueyed/fix-deps-luv-static
78f1ecc deps: Fix luv-static build issues #11961
99b870d build: bundle: clean binary dir with new downloads (#10411)
cf202b7 build: Do not ref `libuv` CMake target if USE_BUNDLED_LIBUV=OFF. (#6363)
```
https://github.com/neovim/neovim/pull/11961
https://github.com/neovim/neovim/pull/13302

**Comment by the-gremlin** [comment]
i also getthis error when trying to build nvim on manjaro using make

**Comment by clason** [comment]
New version is released, and master contains a new version of LibLUV (and there's #14997 bumping LibLUV to 1.40.0 with corresponding changes to the CMake scripts). Please try if one of those fixes your issue.

**Comment by dilyn-corner** [comment]
Version 0.5.0 works like a charm! Thank you :)
