### ISSUE TITLE
Some weird strings keeps being written into main.shada file

### ISSUE THREAD

**Issue by c02y** [neovim/neovim#14378]
- `nvim --version`:
```
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/local/clang-7.0.0/bin/clang -O2 -g -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-d8a0d531-236d-4d4c-9703-9d6e27bee65f

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Manjaro-Linux
- Terminal name/version: Alacritty
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`
This issue is not easy to be reproduced, I just hope someone would know anything about it.
```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
Some weird strings were keep being written into the `~/.local/share/nvim/shada/main.shada` file
such as `\\s\\+$` and `[\\u0009\\u0020\\u00a0\\u1680\\u180e\\u2000-\\u200b\\u202f\\u205f\\u3000\\ufeff]\\+`, when I edit the file, these string keeps coming when I tried to `/` with UP key which searchs previous searched string.

But when I tried to delete the string and related lines using nvim and exit, these strings are still inside the file when I reopen it. I've deleted `~/.local/share/nvim/shada/main.shada` file several times in the past, and it comes back from time to time, this issue is not easy to be produced and if I delete the file, I cannot produce it.

Check the attachment for the details:
![2021-04-16_18-56](https://user-images.githubusercontent.com/2135996/115014905-8326f580-9ee5-11eb-8b18-06bb0dedb02d.png)

### Expected behaviour
The weird strings should not be written into the `~/.local/share/nvim/shada/main.shada`.

**Comment by erw7** [comment]
It seems to be a regular expression that searches for whitespace characters at the end of a line. If you don't remember doing such a search, then maybe the plugin used `exe /...`? I don't think this is a bug in neovim, so I will close this. If you think there is a probable bug in neovim that causes this without any plugin, feel free to reopen this. Also consider using [Neovim Discourse](https://neovim.discourse.group/).
