### ISSUE TITLE
Terminal mode doesn't work as expected.

### ISSUE THREAD

**Issue by riceset** [neovim/neovim#14374]
I just noticed the terminal mode doesn't work properly on Neovim. I tried using the split commands on all directions but it always open a full screen terminal. I tried removing all my plugins but it still doesn't work.

### Without plugins (Neovim)
![image](https://user-images.githubusercontent.com/48802655/114929146-ce6bd600-9e09-11eb-9c96-95c3d6ea6c6f.png)

### Expected behaviour (Vanilla Vim)
![image](https://user-images.githubusercontent.com/48802655/114928568-20f8c280-9e09-11eb-9236-c12e6d8df8df.png)
![image](https://user-images.githubusercontent.com/48802655/114929463-34f0f400-9e0a-11eb-8026-d3cf6d79448b.png)

**Comment by seandewar** [comment]
Commands like ':vertical' only take effect if the given command argument opens a new split.

Neovim's terminal implementation differs from Vim's; one difference is that Nvim's terminal doesn't open in a new split when ':terminal' is invoked. 

For example, to have this work, you'll have to split the terminal into its own window first:

'''vim
:vert split +term
'''
