### ISSUE TITLE
Perl6/Raku syntax file is very outdated

### ISSUE THREAD

**Issue by demostanis** [neovim/neovim#14376]
`neovim/runtime/syntax/perl6.vim` is very outdated, its last change was in 2013.
Since then, the upstream has moved from `vim-perl/vim-perl` to `Raku/vim-raku`.
The latest versions include support for new .raku{mod,doc,test} file extensions
and various bug fixes.
It would be a good idea to keep neovim/vim in sync with it.

**Comment by saadparwaiz1** [comment]
it's really easy to port runtime files to neovim. here's are a few example PRs  #13718, #13558, #13523,  #14048. try your hand on it otherwise I'll make one by the weekend :)

**Comment by mhinz** [comment]
I'm closing this for the same reason as the PR and that ther is nothing we can act on. Vim needs to move first here. Get them to include `Raku/vim-raku` instead of `vim-perl/vim-perl`, if the latter is obsolete anyway.

Until then, your best bet is to use `Raku/vim-raku` directly as a plugin.
