### ISSUE TITLE
lsp: support multiple formatting providers

### ISSUE THREAD

**Issue by kabouzeid** [neovim/neovim#14371]
`formatting()` (and `range_formatting()` for that matter) currently requests `document/formatting` from all capable clients at once and applies the results (text edit array) once they arrive. There are two main problems with that approach:

1. `document/formatting` responses are applied to the buffer without checking whether the buffer has changed since the request has been made. But the buffer could have been changed by the `document/formatting` response of a different server, or even by user input.
2. the order in which responses are applied is undefined.

## Use Case

Personally I have the efm general purpose language server installed which provides `document_formatting`. Often times I’d like to use *both* efm *and* another language server to provide formatting. Some common use cases are:

1. JSON: formatting form json language server + formatting from efm (with fixjson)
2. HTML: formatting from html language server + formatting from efm (rustywind, a class sorter for tailwindcss)
3. Blade: formatting from html language server + formatting from efm (blade-formatter and rustywind)

## Possible Solution

I could make a PR to add the following function, which applies formatters in a chain, ie applies formatters one at a time. I assume changes to the code base will be purely additive. I’m happy to discuss the details here :)

`vim.lsp.buf.formatting_chain_sync({options}, {timeout_ms}, {order})`

Requests formatting from all capable servers, ie those that provide document_formatting or document_range_formatting. The formatting requests are send one at a time such that the formatting request to the next server is only send after the response of the previous server has been processed.

### Parameters:

**{options}** (optional, table) like in `vim.lsp.buf.formatting_sync({options}, {timeout_ms})`

**{timeout_ms}** (optional, number) like in `vim.lsp.buf.formatting_sync({options}, {timeout_ms})`

**{order}** (optional, table) list of client names used to determine the order in which formatting requests are send

### Example:

Suppose we have 4 clients attached:

1. efm: `document_formatting`
2. html: `document_range_formatting`
3. foo: `document_formatting`
4. bar: no formatting

`vim.lsp.buf.formatting_chain_sync(nil, nil, { 'html', 'efm' })`
_request order:_ foo → html → efm

`vim.lsp.buf.formatting_chain_sync(nil, nil, { 'efm' })`
_possible request order:_ foo → html → efm
_possible request order:_ html → foo → efm

`vim.lsp.buf.formatting_chain_sync(nil, nil, nil)`
html, foo and efm _with undefined request order_

### Related
https://github.com/neovim/neovim/issues/12865
https://github.com/neovim/neovim/pull/13233

**Comment by mjlbach** [comment]
Yep, this seems fine to me. I don't think the implementation should be that difficult, but feel free to ping me if you have any questions.

**Comment by kabouzeid** [comment]
Already got it working, I'll test it a bit more before sharing here :) So far it's working perfectly.

**Comment by kabouzeid** [comment]
This seems to be working fine.

```lua
-- lsp-formatting-chain.lua

local M = {}

-- SOURCE: copied from lsp.lua
local wait_result_reason = { [-1] = "timeout", [-2] = "interrupted", [-3] = "error" }

-- SOURCE: adjusted from buf_request_sync in lsp.lua
-- NOTE: this should be moved to lsp.lua as `client.request_sync`
--
-- @returns { err, result }, where `err` and `result` come from the lsp-handler
--- 				On timeout, cancel or error, returns `(nil, err)` where `err` is a
--- 			  string describing the failure reason. If the request was unsuccessful
--- 			  returns `nil`.
local function client_request_sync(client, method, params, timeout_ms, bufnr)
  local request_result = nil
  local function _sync_handler(err, _, result)
    request_result = { error = err, result = result }
  end

  local success, request_id = client.request(method, params, _sync_handler,
                                             bufnr)
  if not success then return nil end

  local wait_result, reason = vim.wait(timeout_ms or 100, function()
    return request_result ~= nil
  end, 10)

  if not wait_result then
    client.cancel_request(request_id)
    return nil, wait_result_reason[reason]
  end
  return request_result
end

--- Formats the current buffer by chaining formatting and/or range_formatting requests to all
--- attached clients of the current buffer.
---
--- Useful for running on save, to make sure buffer is formatted prior to being
--- saved. {timeout_ms} is passed on to the |vim.lsp.client| `request_sync` method. Example:
---
--- <pre>
--- vim.api.nvim_command[[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_chain_sync()]]
--- </pre>
---
--@param options (optional, table) `FormattingOptions` entries
--@param timeout_ms (optional, number) Request timeout
--@param order (optional, table) List of client names. The buffer is formatted with all capable
---      clients in the following order: first all clients that are not in the `order` list, then
---      the remaining clients in the order as they occur in the `order` list.
function M.formatting_chain_sync(options, timeout_ms, order)
  local clients = vim.tbl_values(vim.lsp.buf_get_clients());

  -- sort the clients according to `order`
  for _, client_name in ipairs(order or {}) do
    -- if the client exists, move to the end of the list
    for i, client in ipairs(clients) do
      if client.name == client_name then
        table.insert(clients, table.remove(clients, i))
        return
      end
    end
  end

  local function handle_request_result(result)
    if not result then return end
    if not result.result then return end
    vim.lsp.util.apply_text_edits(result.result)
  end
  -- loop through the clients and make synchronous formatting requests
  for _, client in ipairs(clients) do
    if client.resolved_capabilities.document_formatting then
      local result = client_request_sync(client, "textDocument/formatting", vim.lsp.util.make_formatting_params(options), timeout_ms)
      handle_request_result(result)
    elseif client.resolved_capabilities.document_range_formatting then
      local last_line = vim.fn.line("$")
      local last_col = vim.fn.col({ last_line, "$" })
      local params = vim.lsp.util.make_given_range_params({ 1, 0 }, {
        last_line, last_col
      })
      params.options = vim.lsp.util.make_formatting_params(options).options
      local result = client_request_sync(client, "textDocument/rangeFormatting", params, timeout_ms)
      handle_request_result(result)
    end
  end
end

return M
```

I would even argue to remove `vim.lsp.buf.formatting_sync` in favor of this. Otherwise I think this could cause confusion as both methods serve the same purpose.

You can test with eg
`require'lsp-formatting-chain'.formatting_chain_sync()`
`require'lsp-formatting-chain'.formatting_chain_sync(nil, 1000, {"efm"})`

I've tested this in a few different scenarios and couldn't find any issues 👍

**Comment by mjlbach** [comment]
Is there a reason you can't do client.request with a custom handler? See definition of lsp.buf_request

I would go ahead and eopen the PR. I'm not sure how I feel about having the workaround for document range formatting (50/50 right now), also I think you can just use the client_ids instead of shuffling around the actual clients in the table.

**Comment by kabouzeid** [comment]
I am in fact using client.request with a custom handler. Am I missing something here?

What do you mean by workaround for document range formatting?

Yeah I probably should not shuffle around the actual client array, will fix that.

**Comment by mjlbach** [comment]
As in having it fall back to textDocument/rangeFormatting if textDocument/formatting isn't available (I assume this is mostly targeted at jsonls). Sorry, I guess my point was what is the justification for having a whole wrapper method around client.request, which already exists (and is what you're using)

**Comment by kabouzeid** [comment]
client.request is async, but I needed a sync version here, so I created it (analog to buf_request and buf_request_sync).

The range formatting behavior applies to all of VSCodes bundled lang servers (html, css, json). I just checked and couldn't find other language servers with this behavior.

**Comment by kabouzeid** [comment]
In the long term, this is what I have in mind for the whole formatting API.

## Current API


`formatting()`

Requests formatting from all clients, with current state of buffer.  
*Problem*: all formatters use the same buffer state → they can interfere with each other

`formatting_sync()`

Requests formatting from all clients, with current state of buffer. Waits for all clients to respond, but then only picks the first result.  
*Problem*: not the same behaviour as the async call → confusing  
*Problem*: first result could be empty, but there might be a non-empty result that we could apply

`range_formatting()`

Requests range formatting from all clients, with current state of buffer.  
*Problem*: all formatters use the same buffer state → they can interfere with each other

## New API (changes in bold)


`formatting()`

Requests formatting from all clients, with current state of buffer. **Only applies the first non-empty result.**

`formatting_sync()`

Requests formatting from all clients, with current state of buffer. Waits for all clients to respond, **only applies the first non-empty result.**

`range_formatting()`

Requests range formatting from all clients, with current state of buffer. **Only applies the first non-empty result.**

`range_formatting_sync()` **new**

Requests range formatting from all clients, with current state of buffer. Only applies the first non-empty result.

`formatting_chain()` **new**

Requests formatting from all clients, one at a time, always with the updated state of buffer, so that all formatters can be applied at once without interfering with each other.

`formatting_chain_sync()` **new**

Requests formatting from all clients, one at a time, always with the updated state of buffer, so that all formatters can be applied at once without interfering with each other.
