### ISSUE TITLE
neovim with default settings freezes on opening shell scripts

### ISSUE THREAD

**Issue by matu3ba** [neovim/neovim#14384]
Meta: Is there a workaround to use (neo)vim with absolute no syntax highlighting to have no such errors?
A complete freeze due to syntax stuff is very inconvenient.

- `nvim --version`: NVIM v0.5.0-dev+1259-gfe808f02f
- `vim -u DEFAULTS` (version: ) behaves differently? *YES*
- Operating system/version: EndeavourOS
- Terminal name/version: Alacritty
- `$TERM`: tmux-256color/alacritty identical

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC anytest.sh
```

content of anytest.sh:
```
#!/bin/bash
ls testdocument
echo 123123
```

### Actual behaviour

W18: invalid characters in group name and __complete freeze__. After 30 seconds or longer some characters are read and I can quit.

### Expected behaviour

No freezing on opening shell scripts.

#### Potentially related

https://github.com/autozimu/LanguageClient-neovim/commit/99db72cb9c6451497bc038feaa08b21c1606673b

**Comment by clason** [comment]
Can't reproduce --  are you aware that `-u NORC` still loads your plugins?  You need `-u NONE` and/or `--noplugin` to skip those as well.

**Comment by matu3ba** [comment]
@clason Thanks. closing for now. Should be some plugin doing some very stupid stuff.
