### ISSUE TITLE
UI Protocol: duplicate cursors in terminals

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#14386]
- `nvim --version`: NVIM v0.5.0-dev+1135-g0f318e0f9
- Operating system/version: Linux 5.10.0-3-amd64 SMP Debian 5.10.13-1 (2021-02-06) unknown unknown GNU/Linux

### Steps to reproduce using `nvim -u NORC`

Run neovim from a GUI, open a terminal, type characters:

```python
import time
from pynvim import attach
from threading import Thread

class UIThread(Thread):
    def __init__(self, nvim):
        Thread.__init__(self)
        self.nvim = nvim
        self.do_print = False
    def run(self):
        self.nvim.run_loop(self.callback, self.callback)
    def callback(self, event_name, events):
        if self.do_print:
            [print(event) for event in events if event[0] == "grid_line" or event[0] == "grid_cursor_goto"]

nvim = attach('child', argv=["/home/me/bin/nvim", "--embed", "-u", "NORC", "-i", "NONE"])
ui = UIThread(nvim)
ui.start()
nvim.async_call(nvim.ui_attach, 20, 5, ext_messages = True, ext_linegrid = True, rgb = True)
nvim.async_call(nvim.command, "term bash --noprofile --norc --noediting")
time.sleep(1)
nvim.async_call(nvim.input, "iPS1='>'<CR> ")
time.sleep(1)
ui.do_print = True
nvim.async_call(nvim.input, " ")
time.sleep(1)
ui.do_print = False
nvim.async_call(nvim.input, "<C-\><C-n>:qa!<Enter>")
time.sleep(1)
```

### Actual behaviour

Neovim uses a grid_line event to clear the cursor (`[' ', 0]`) and then paints it again using TermCursor highlight (`[' ', 5]`) and then paints it again with a "grid_cursor_goto" event that doesn't target the same cell as the TermCursor cursor:
```
['grid_line', [1, 1, 2, [[' ', 0], [' ', 5]]]]
['grid_cursor_goto', [1, 1, 1]]
```

### Expected behaviour

Neovim only paints the cursor once.

### Additional information

This doesn't happen with every shell. I can reproduce this with zsh 5.4.2 and bash 5.1.4 but not with zsh 5.8. With the right shell, I can reproduce consistently across multiple UIs (Goneovim, Firenvim, Nwin...).

**Comment by sakhnik** [comment]
This may be a legit behaviour because neovim declares "busy_start" when entering the terminal mode expecting the cursor to be hidden. That's how I fixed it in my UI: https://github.com/sakhnik/nvim-ui/commit/15b8407b85c775f9d91e105d860449eb49aae000

**Comment by glacambre** [comment]
Ah, thanks, this could indeed be what Neovim expects! The docs could be clearer about that though:
> ["busy_start"]
> ["busy_stop"]
>	Nvim started or stopped being busy, and possibly not responsive to user input. This could be indicated to the user by hiding the cursor.

"Could" should probably be turned into "must". Thoughts @bfredl?

**Comment by bfredl** [comment]
those events are misnamed and had nothing do with business at all. we can update the docs at least.
