### ISSUE TITLE
unable to use +/* buffers on termux

### ISSUE THREAD

**Issue by 5c0tt-b0t** [neovim/neovim#14383]
- `nvim --version`:
NVIM v0.4.4
Build type: Release
Lua 5.3
- `vim -u DEFAULTS` (version: ) behaves differently?
no
- Operating system/version:
Android tablet (Samsung, android 10)
- Terminal name/version:
`termux` (with `termux-api` for `termux-clipboard-set/get`)
- `$TERM`:
`xterm-256color`
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### I am trying to achieve this:

- by default, cut/copy to a buffer, not system clipboard.
- `vim`'s other register (I think its `+`, please correct me if its `*`!) should go to the system clipboard.

I have done some research but nothing (so far) is working for me.

### Info:

- I use `tmux` so pushing to `tmux` buffers.
- I'm away from home, so currently using `termux` so example here is with  `termux-clipboard-get/set`

Here is what I thought would work in my case:
```bash
let g:clipboard = {
  \   'name': 'TmuxTermux',
  \   'copy': {
  \      '*': ['tmux', 'load-buffer', '-'],
  \      '+': ['termux-clipboard-set'],
  \    },
  \   'paste': {
  \      '*': ['tmux', 'save-buffer', '-'],
  \      '+': ['termux-clipboard-get'],
  \   },
  \   'cache_enabled': 1,
  \ }
```

Now when I cut/copy, `tmux` buffers share `vim`'s content, PERFECT! (almost...),
I cannot use the `+` buffer to use the system clipboard though, if I press `+` (system clipboard) its just moves my cursor down by one line, if I swap the above order (make `termux-clipboard-get/set` the `*` register, instead of `+`), when I press `*` it highlights all instances of the word my cursor is on.

### From reading, I expected:

- By default, `vim` use `*` register, this seems to be true as it successfully registers to `tmux` buffers with `dd/yy` and pastes with `p` (or in `tmux` with my bind of `[PREFIX]+[p]`
- If I want to cut/copy/paste to my other register `+` (system clipboard), then I would use `+dd/+yy` and then paste with `+p` (or even `*dd/*yy/*p`) but this isnt working for me.

### Problem:

As explained above, `+` will move my cursor down one line, when changing it to the `*` register, `*` highlights the current word and any other occurance of it

Apologies in advance, I'm fresh from `emacs` (with a very sore pinky finger!:)

**Comment by 5c0tt-b0t** [comment]
it seems I need to use `"` first (`"+yy` etc)
I shall close this, but if someone does find this, my above example doesnt work anyway, I think the syntax is wrong as it throws an error

**Comment by Freed-Wu** [comment]
I try your example and met a bug

```
Error detected while processing function provider#clipboard#Call[6]..2[7]..<SNR>24_try_cmd:
line    1:
E475: Invalid argument: expected String or List
clipboard: provider returned invalid data
Error detected while processing function provider#clipboard#Call[6]..2[7]..<SNR>24_try_cmd:
line    1:
E475: Invalid argument: expected String or List
clipboard: provider returned invalid data
```

I open a new issue to request the feature.

<https://github.com/neovim/neovim/issues/15572>
