### ISSUE TITLE
nvim_buf_detach is missing

### ISSUE THREAD

**Issue by Shatur95** [neovim/neovim#14395]
- `nvim --version`: 66f9dd3c6e2e2968e4534ac0eacb7695f97c11b1 (latest master at the time of writing)
- Operating system/version: ArchLinux
- Terminal name/version: any

### Steps to reproduce using `nvim -u NORC`

```vimscript
:lua vim.api.nvim_buf_detach(0)
```

### Actual behaviour

The function does not exists:

```
|| E5108: Error executing lua [string ":lua"]:1: attempt to call field 'nvim_buf_detach' (a nil value)
```

### Actual behaviour

Function exists, [documentation](https://github.com/neovim/neovim/blob/66f9dd3c6e2e2968e4534ac0eacb7695f97c11b1/runtime/doc/api.txt#L2011).

**Comment by mjlbach** [comment]
It's not missing, this came up on IRC today (and several times before). The function is intentionally not exposed via lua. You can search the archives for the comments by bfredl.

**Comment by Shatur95** [comment]
@mjlbach, thanks for the info. Probably it should be removed from the documentation (so maybe reoopen the issue?)

BTW, is there a way to remove all callbacks? I have issues when switching between `:mksession` after wiping all buffers (`Error executing vim.schedule lua callback: Vim:E158: Invalid buffer name: 146`)

**Comment by bfredl** [comment]
The function is for remote channels and it links to the corresponding lua docs (which could be moved up perhaps as lua is more popular, PRs welcome)

**Comment by Shatur95** [comment]
> The function is for remote channels and it links to the corresponding lua docs (which could be moved up perhaps as lua is more popular, PRs welcome)

Will this function allow to avoid `Error executing vim.schedule lua callback: Vim:E158: Invalid buffer name` after cleaning all buffers and sourcing a new session from `:mksession`?

**Comment by Shatur95** [comment]
Hm... When I use `vim.cmd('bufdo ' .. tostring(buffer))` - everything works fine. Is it okay that `vim.api.nvim_buf_delete` behaves differently?
I just though that `nvim_buf_detach` should solve my issue.

**Comment by bfredl** [comment]
> > The function is for remote channels and it links to the corresponding lua docs (which could be moved up perhaps as lua is more popular, PRs welcome)
> 
> Will this function allow to avoid `Error executing vim.schedule lua callback: Vim:E158: Invalid buffer name` after cleaning all buffers and sourcing a new session from `:mksession`?

No.
