### ISSUE TITLE
`:sort` can't sort Chinese in pinyin alphabetical order

### ISSUE THREAD

**Issue by flyxyz123** [neovim/neovim#14394]
- `nvim --version`: 0.4.4 and v0.5.0-dev+1263-ga129887c0
- `vim -u DEFAULTS` (version: ) behaves differently? yes, 8.2
- Operating system/version: windows 10 and arch linux
- Terminal name/version: alacritty
- `$TERM`: alacritty

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC somefile
:sort
```

### Actual behaviour

Chinese are not sort in pinyin alphabetical order

### Expected behaviour

Chinese are sort in pinyin alphabetical order

### More Information

Default vim 8.2 can sort Chinese in pinyin alphabetical order but neovim can't.

If I set vim encoding to utf-8, vim can not sort Chinese in pinyin alphabetical order either.\
 Vim is not perfect in sort on windows, I have no idea why it put 黏 and 笙 at the end for the attached example. However, vim will sort perfectly on Arch Linux.\
So I guess it might because neovim default encoding is not latin1.\
I think I can't change the encoding in neovim, so I try to change fileencoding in neovim but still can not sort Chinese in pinyin alphabetical order.

Is it a feature or BUG? If it is a feature, what is the easiest way to sort Chinese in pinyin alphabetical order in neovim?

Attached file vim_ex.txt is vim output on windows after :sort.\
Attached file nvim_ex.txt is neovim output on windows after :sort.\
vim_ex.txt contains most Chinese in pinyin alphabetical order but nvim_ex is not.\
In order to display vim_ex.txt with vim properly, you need :e ++enc=utf8 after open it with vim.

[nvim_ex.txt](https://github.com/neovim/neovim/files/6331316/nvim_ex.txt)
[vim_ex.txt](https://github.com/neovim/neovim/files/6331317/vim_ex.txt)

**Comment by flyxyz123** [comment]
It appears that default vim can't sort Chinese in pinyin alphabetical order on arch Linux either. It can only sort Chinese on Windows 10.

**Comment by chrisbra** [comment]
You should be able to set the collation order for vim to use

**Comment by flyxyz123** [comment]
> 
> You should be able to set the collation order for vim to use
> […](#)
> Am 18.04.2021 um 15:43 schrieb flyxyz123 ***@***.***>: ﻿ It appears that default vim can't sort Chinese in pinyin alphabetical order on arch Linux either. It can only sort Chinese on Windows 10. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you for help. I have foud out that with `:sort l`, vim can sort Chinese on arch linux. And I edited that comment with more details.

**Comment by flyxyz123** [comment]
### Further Update

On windows 10, with default vim-nightly 8.2.2779, Chinese can use `:sort l` to sort pinyin alphabetical order perfectly following the codes bleow.

```
vim somefile
:e ++enc=utf8
:language zh_CN
:sort l
```

It seems like neovim just doesn't have this feature yet. The help file for `:sort` in neovim is same as vim 8.2 which doesn't have `l` option as shown below. However, vim-nightly 8.2.2779 has this new feature, it has `l` option for `sort`.

https://github.com/neovim/neovim/blob/63c2a7af2da3998167c7b1b06fb461b20b144c78/runtime/doc/change.txt#L1819-L1820

I might be wrong about this. Does anyone know how to set the collation order in neovim?

**Comment by glacambre** [comment]
This feature has been added to Vim in patch 8.2.1933 ( commit https://github.com/vim/vim/commit/55e29611d20bca14fa5efc61385bc8a6b7acd9e2 ) and needs to be ported. The procedure to port patches from Vim is described [here](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim) if you want to try to do it yourself :).
