### ISSUE TITLE
`os.execute` does not correctly caputre the exit code

### ISSUE THREAD

**Issue by dedani** [neovim/neovim#14393]
- `nvim --version`: 
```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
moonjit 2.2.0
Compilation: /usr/bin/cc -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fcommon -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/abuild/rpmbuild/BUILD/neovim-0.5.0~git.1618713711.a129887c0/build/config -I/home/abuild/rpmbuild/BUILD/neovim-0.5.0~git.1618713711.a129887c0/src -I/usr/include -I/usr/include/lua5.1 -I/home/abuild/rpmbuild/BUILD/neovim-0.5.0~git.1618713711.a129887c0/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.5.0~git.1618713711.a129887c0/build/include
Compiled by abuild@cloud111

Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Opensuse Tumbleweed
- Terminal name/version: `bash 5.1.4`
- `$TERM`: `xterm-256color`

### Actual behaviour

It seems that `os.execute(...)` is not working correctly. I encounter this problem when I tried to use [kabouzeid/nvim-lspinstall](https://github.com/kabouzeid/nvim-lspinstall/), but could not get a lsp installed. I played around with a conditional around a `os.execute("mkdir -p " .. path)` command and found that the return code of the command is not correctly captures. Running `:lua os.execute("ls")` returned `ls: write error: Bad file descriptor`. Also trying to get the return code of `ls` does not work: `:lua os.execute("ls & echo $?") returns `sh: line 1: echo: write error: Bad file descriptor`.

The error is reported [here](https://github.com/kabouzeid/nvim-lspinstall/issues/30#issuecomment-821971333) in the `lspinstall` repository. Could this be a neovim problem?

**Comment by bfredl** [comment]
`os.execute` does not do IO. better to use the `vim.loop` API (or plenary high-level wrappers, which could be moved to core eventually).
