### ISSUE TITLE
Getting the left and right bounds of the viewport?

### ISSUE THREAD

**Issue by invrainbow** [neovim/neovim#14399]
I'm using `win_viewport` to store the viewport so that I can interpret `grid_line` events correctly. If I know the viewport is currently at `topline = 10`, then a `grid_line` with `row = 3` means there's a highlight on row 13.

I would like to use this same logic to calculate the *column* of highlights, but `win_viewport` doesn't have an analogous `leftcolumn`/`rightcolumn` the way it has a `topline`/`bottomline`. Is it possible to get this information?

Background: I'm building a text editor that integrates nvim. I don't want to use `grid_line` events to simply draw a replica of nvim's screen. Instead I want to manage my own buffer, use `nvim_buf_lines_event` to sync, and draw my own editor. This works great, but it seems the only way to determine what text is visually selected is through `grid_line` events, which require me to know the viewport to translate row/columns correctly.

**Comment by invrainbow** [comment]
Hi,

Any news on this?

**Comment by clason** [comment]
No.
