### ISSUE TITLE
Segmentation fault if colorscheme not present

### ISSUE THREAD

**Issue by dusans** [neovim/neovim#14407]
- `nvim --version`: NVIM v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?: Yes
- `Operating system/version`: Linux 5.4.0-70-generic 78-Ubuntu SMP x86_64 GNU/Linux
- `$TERM`: xterm-256color

### Steps to reproduce using minimal init.vim:

```
colorscheme wombat
```

But not having the colorscheme installed.

### Actual behaviour

Segmentation fault (core dumped)

### Expected behaviour

Warning: colorscheme not found

**Comment by mhinz** [comment]
Can't reproduce with neither the latest release 0.4.4 nor master. Please upgrade Nvim.

**Comment by dusans** [comment]
I was migrating my Neovim Windows config to Linux. 

There might have been some Windows specific things that caused the segmentation fault.

After cleaning up the config it works. No errors.
