### ISSUE TITLE
Add a `<LUA>` key for mapping keys to lua snippets

### ISSUE THREAD

**Issue by Joakker** [neovim/neovim#14404]
Since many people like to make their configurations in lua, it'd be nice that, for mapping key combos to lua snippets, we could simply specify that snippet directly rather than doing it through a vimscript command using `<CMD>lua` every time.

Like, say I have something like this
```lua
vim.api.buf_set_keymap('n', '<leader>lf', '<CMD>lua vim.lsp.buf.formatting()<CR>')
```

I could rewrite it like this

```lua
vim.api.buf_set_keymap('n', '<leader>lf', '<LUA>vim.lsp.buf.formatting()<CR>')
```

**Comment by jdhao** [comment]
It seems like a syntactic sugar with marginal benefit. I think it is easy to achieve with some hack in your own lua function. For example, replace `<LUA>` with `<CMD>lua` for the right hand side of the mapping.

**Comment by mhinz** [comment]
What @jdhao said.

I appreciate the request, but changing core just to avoid typing a few characters more is not good. :) This can better be solved with an own function or plugin.

**Comment by Joakker** [comment]
Fair enough 👍🏽
