### ISSUE TITLE
Neovim.io has an SSL warning

### ISSUE THREAD

**Issue by brandoncc** [neovim/neovim#14410]
This is what I see if I visit the site as of Tue Apr 20 11:11:39 PDT 2021

![image](https://user-images.githubusercontent.com/543973/115444176-1c495b00-a1c9-11eb-925e-ce7e0aafa0f1.png)

**Comment by clason** [comment]
It's known and being worked on: https://github.com/neovim/neovim.github.io/issues/217

**Comment by brandoncc** [comment]
Thanks @clason, I checked the open issues but didn't realize there was a repo for that. Sorry!

**Comment by clason** [comment]
It was also one of the pinned issues on this repository ;)

**Comment by brandoncc** [comment]
Oh wow, I've never seen a pinned issue before. Thanks for pointing that out to me. I searched the issues for "SSL", so I guess I should have also tried "cert". Sorry again.

**Comment by clason** [comment]
No worries! I was wondering whether pinning an issue made people more likely to *miss* it, paradoxically...

**Comment by brandoncc** [comment]
In this case I would say yes. I looked at the list, then searched.... Never noticing that new section on the page.

**Comment by cweagans** [comment]
Looks like some DNS changes were made this morning. The cert error is gone for me already, but it may take some time for the DNS changes to propagate.
