### ISSUE TITLE
orphaned language servers after neovim exit

### ISSUE THREAD

**Issue by dimbleby** [neovim/neovim#14428]
`v0.5.0-dev+1274-gbb3372792`, using the built-in LSP client.

Some - but not all - language servers are orphaned and continue to run after neovim exits.

In particular, [jedi-language-server](https://github.com/pappasam/jedi-language-server/) exhibits this behaviour, while rust-analyzer does not.

This has started happening very recently, pretty sure that #14180 must be relevant.

So far as I can see the changed code sends signal 15 to the server at neovim exit?  Anyway if I `kill -15 <jedi PID>` then it does exit.  So I'm not sure what's going wrong.

**Comment by mjlbach** [comment]
@oberblastmeister this is what I was worried about :(

**Comment by oberblastmeister** [comment]
yeah its probably that pr :(. I also tested with my language server and it doesn't close properly

**Comment by mjlbach** [comment]
I think for now, let's revert, and we can reopen an issue about it and investigate :)

**Comment by oberblastmeister** [comment]
yeah sure

**Comment by dimbleby** [comment]
Confirmed that after reverting #14180 jedi-language-server is no longer left orphaned by neovim
