### ISSUE TITLE
nightly gone, best to use master now?

### ISSUE THREAD

**Issue by 06kellyjac** [neovim/neovim#14421]
nightly branch is gone, is it coming back or shall i just go with master?

Thanks

**Comment by vigoux** [comment]
There are nightly releases now which are actually tags.

Nightly is updated everyday (I think), so that's approximately the same as master anyway.

**Comment by 06kellyjac** [comment]
ok, good to know. Thanks

**Comment by EmileRolley** [comment]
> There are nightly releases now which are actually tags.
> 
> Nightly is updated everyday (I think), so that's approximately the same as master anyway

I can't find any nightly tag:

![Screenshot from 2021-04-22 11-57-10](https://user-images.githubusercontent.com/44124798/115696108-a5e06080-a362-11eb-98bf-fddf349e9d90.png)

**Comment by clason** [comment]
There are problems (again) with the Github Action that does these releases (they're not tags; just releases built from the current  `HEAD` of `master`): https://github.com/neovim/neovim/actions/runs/772813738

It happened before, so I'm sure the people involved will fix it again soon ;)

**Comment by EmileRolley** [comment]
> There are problems (again) with the Github Action that does these releases (they're not tags; just releases built from the current `HEAD` of `master`): https://github.com/neovim/neovim/actions/runs/772813738
> 
> It happened before, so I'm sure the people involved will fix it again soon ;)

Okey thank you ! :heart:

**Comment by clason** [comment]
For the record, this looks like it's due to https://github.com/neovim/neovim/commit/62df537543bfc4327700d9f8930ae7c755c92ab2

**Comment by musale** [comment]
It's now back https://github.com/neovim/neovim/releases/tag/nightly

**Comment by jamessan** [comment]
The nightly build fails sometimes ... just wait a day (or for someone to trigger it). ;)

**Comment by twnaing** [comment]
2021/4/30 Nightly tag still missing (or) missing again

**Comment by thegrojas** [comment]
Yeah, it seems it's missing again. Someone tried to trigger the action manually, but it seems there's some underlying issue. Refer to  #14461. Let's hope someone can take a look into it  soon.
