### ISSUE TITLE
Is It Possible to Reduce the Amount of Space That the Spell Checker Takes up When You Hit `z=`?

### ISSUE THREAD

**Issue by K4LCIFER** [neovim/neovim#14426]
When you view the spell suggestions for a word with `z=`, a window will pop up with a whole bunch of spell suggestions/guesses that you can choose from to replace the word that was spelled incorrectly. The issue with this is that this window which contains the suggested words can end up being maximized to the entire size of the Neovim window, thereby obscuring all of your work that you are checking. I would like it if I could specify that this window only open up a smaller window at the bottom that I can then scroll through.

**Comment by oponkork** [comment]
`help spellsuggest`

**Comment by jdhao** [comment]
http://vimdoc.sourceforge.net/htmldoc/options.html#'spellsuggest'
