### ISSUE TITLE
py3eval returns v:null for the first invocation

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#14438]
- reproducible on NeoVim nightly, 0.4.4, 0.3.8 with pynvim 0.4.3
- Vim 8.2.2648 with `+python3` works correctly
- Operating system/version: ubuntu 20.04

### Steps to reproduce using `nvim -u NORC`
```
echo py3eval('0')
echo py3eval('0')
```

### Actual behaviour
The first `py3eval('0')` returns `v:null` and the second returns `0`.

### Expected behaviour
Both should return `0`.

**Comment by bfredl** [comment]
Can reproduce.

**Comment by wookayin** [comment]
Still in neovim 0.7.0

**Comment by zeertzjq** [comment]
I think this issue should belong to pynvim repository?

**Comment by zeertzjq** [comment]
Oh, this has been fixed in pynvim by https://github.com/neovim/pynvim/pull/496

**Comment by zeertzjq** [comment]
Closing as pynvim 0.5.0 has been released.
