### ISSUE TITLE
Neovim doesn't render lines correctly after switching from a maximized pane in Tmux

### ISSUE THREAD

**Issue by gregorias** [neovim/neovim#14434]
(I've also filed [this issue against tmux](https://github.com/tmux/tmux/issues/2677))

When I switch from a maximized pane with neovim to another pane, the neovim pane starts rendering new lines offset by one. The video explains it:

https://user-images.githubusercontent.com/722385/115953800-e3252980-a4ed-11eb-829a-19ee4ba6c26a.mp4

- `nvim --version`: NVIM v0.5.0-dev+1267-g7bf62ab02 (reproducible also with v0.4.4)
- `vim -u DEFAULTS` (version: 8.2): The issue doesn't appear in Vim
- Operating system/version: Manjaro Linux
- Terminal name/version: suckless and alacritty both have this issues
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
$ tmux # version 3.2
$ nvim -u NORC A_multiline_file
# In Tmux: split a vertical pane, maximize the neovim pane, switch to the other pane.
```

### Actual behaviour

When I switch from a maximized pane with neovim to another pane, the neovim pane starts rendering new lines offset by one. 

### Expected behaviour

Neovim renders lines correctly after resizing and switching panes.

### Notes

* The bug was introduced by [this Tmux commit from June 2020](https://github.com/tmux/tmux/commit/d919fa1ed0ea3b167ffc811abba26a2dbcd20631). Previous commits do not exhibit this **behavior.**
* I can "fix" this issue by maximizing and minimizing the terminal window. I suspect that forces some kind of a full refresh.
* The issue also appears with an empty config file.

**Comment by ianhomer** [comment]
I was having similar issue with the following in my tmux.conf

`
set-option -g default-terminal "screen-256color"
`

I read some guidance in https://github.com/kovidgoyal/kitty/issues/2047 which described similar glitches, I changed my tmux.conf to 

`
set-option -g default-terminal "xterm-kitty"
`

or if you want to quickly test without changing tmux config just set in local window

`
export TERM=xterm-kitty
`

This fixed it for me.

**Comment by timtyrrell** [comment]
@ianhomer Thanks for that tip! I will swap it in and see how it goes (and I do use Kitty). I feel like I never knew exactly how to trigger it so I will keep an eye on it with this change.

**Comment by timtyrrell** [comment]
I think this can be closed now. A tmux fix was merged and verified and the PR was closed 13 days ago https://github.com/tmux/tmux/issues/2677 with this commit: https://github.com/tmux/tmux/commit/cf6034da92df1dec0a2ea6230bd7a424d0d181a8

**Comment by mmngreco** [comment]
I have the same issue using `xterm`, I've installed `tmux` from the source (this commit `a971d - (4 days ago)`) but I continue experiencing this issue.

I have the following in my `tmux.conf`

```ini
set-option -sa terminal-overrides ',xterm-256color:RGB'
set-option -g default-terminal "xterm-256color"
```

I've added the last line in order to check if could fix the issue but it doesn't.

Any workaround ?

**Comment by kylo252** [comment]
There's a chance this is a zsh issue, see this section: https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
