### ISSUE TITLE
`SQLComplete: the dbext plugin must be loaded for dynamic SQL completion`

### ISSUE THREAD

**Issue by githorse** [neovim/neovim#14433]
Seems that Nvim includes [SQL completion](http://neovim.io/doc/user/ft_sql.html#sql-completion) by default and triggered by `Ctrl+C` (`:h sql-complete`). When I edit a `.sql` file, I get errors:

```
SQLComplete: the dbext plugin must be loaded for dynamic SQL completion
```

Spurious autocompletion suggestions are inserted at the cursor which I then have to undo.

Thoughts/Questions:

* Seems like `Ctrl+C` is a problematic default as that's what I use to exit insert mode. Could we use a different key?
* Frankly I was surprised to find Nvim core trying to autocomplete my SQL at all (without any plugins). Is this common? I've never had this issue with other filetypes.
* I don't have `dbext` installed, apparently. Could SQL completion do something more useful in this case (e.g. nothing at all) in preference to auto-inserting random stuff?
 

### Specs

- `nvim --version`: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: Linux Mint 20
- Terminal name/version: `# GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD`

### Steps to reproduce using `nvim -u NORC`

The problem does not manifest with `nvim -u NORC`, but it *does* manifest with `nvim -u DEFAULTS` or an empty `vimrc`:

```
$ touch empty-vimrc
$ wc -c empty-vimrc
0 empty-vimrc
$ nvim -u empty-vimrc
```

(Not sure if different behavior between empty `vimrc` and `NORC` is by design?)

### Actual behaviour

Unexpected insertions in my `.sql` files when I hit `Ctrl+C` and then another key.

### Expected behaviour

Benign neglect.

**Comment by glacambre** [comment]
I agree that it's very weird to map `<C-c>` by default, however this is not something Neovim can change: runtime files are directly imported from Vim, which directly includes files sent by the runtime file's maintainer. So what you should do is try to convince the [runtime file's maintainer](https://github.com/neovim/neovim/blob/bb7d3790bf08b5519623d261d8235bad77b5c0dd/runtime/ftplugin/sql.vim#L4) to remove that keybinding from the runtime file.

A workaround could be to [change the keybinding used](https://github.com/neovim/neovim/blob/master/runtime/ftplugin/sql.vim#L82) in your config :).

**Comment by githorse** [comment]
Roger that -- thanks! Email sent and keybinding workaround implemented.

**Comment by SkyLeach** [comment]
I don't understand why this was closed when the dbext.vim problem is both still around and regularly comes up among people editing sql files that have never installed `dbext.vim` (from: https://www.vim.org/scripts/script.php?script_id=356) but also replicated to https://github.com/vim-scripts/dbext.vim

**Comment by glacambre** [comment]
@SkyLeach This issue is closed because neovim doesn't maintain the sql runtime file. If there is a problem, you should report it on the Vim issue tracker (or, ideally, to the [maintainer of the sql runtime file](https://github.com/neovim/neovim/blob/bb7d3790bf08b5519623d261d8235bad77b5c0dd/runtime/ftplugin/sql.vim#L4)). Once upstream is fixed, neovim will be able to pull the changes and the problem will be solved.

**Comment by SkyLeach** [comment]
@glacambre I don't mean to sound ungrateful for neovim because I definitely am a huge fan.  That said, however, it seems odd to have people like me who are just incidental end-users contacting the maintainer of a plugin we didn't choose ourselves and, at least in my case, know nothing of.

I literally didn't know about any of this (and know nothing at all about said plugin) until it spammed me because I was editing SQL.  Normally I focus on ORMs not native sql and until you dropped the link I would have had no clue where to even begin.

What would I say?  I didn't even know I was using your plugin but now the neovim guys told me to have you fix it?

**Comment by glacambre** [comment]
>That said, however, it seems odd to have people like me who are just incidental end-users contacting the maintainer of a plugin we didn't choose ourselves and, at least in my case, know nothing of.

If it makes you feel better, Neovim didn't choose this plugin either. We're just importing Vim runtime files and whatever changes happen to them.

>I literally didn't know about any of this

I believe none of the people maintaining Neovim use SQL on a regular basis, so I'd be surprised if they knew about this plugin too (I certainly didn't until this PR was opened, and I had forgotten about it until you submitted your comment :) ).

>What would I say? "I didn't even know I was using your plugin but now the neovim guys told me to have you fix it."?

Yep, exactly. You could even be proactive and provide more information about the failure, possibly even send a patch :).

**Comment by rmacklin** [comment]
In case anyone stumbles on this issue and is looking for a quick workaround:
```vim
" Default to static completion for SQL
let g:omni_sql_default_compl_type = 'syntax'
```
Credit to https://github.com/hrsh7th/nvim-compe/issues/286#issuecomment-805140394

**Comment by rmacklin** [comment]
@cemsbr Can you clarify what you mean? If you add that line to your vimrc, it should be "permanent" in the sense that you would no longer see the `SQLComplete: the dbext plugin must be loaded for dynamic SQL completion` (until you remove that line).

**Comment by cemsbr** [comment]
I'll try that, @rmacklin, thanks. I thought I had to add something in the ~/.SpaceVim.d/ folder.

**Comment by cemsbr** [comment]
By permanent, I mean not having to disable everytime I start neovim. Maybe I have to add something to a bootstrap function, probably `omni_sql_default_compl_type = 'syntax'`.

**Comment by rmacklin** [comment]
What I can tell you with certainty is that after adding that line to my config, I never had any issues on subsequent neovim restarts. I'm not sure why it's not permanent for you - perhaps there's something else at play in your configuration.

**Comment by cemsbr** [comment]
@rmacklin, where exactly did you write those lines? Was it in ~/.SpaceVim.d/init.toml under `[options]`? The ~/.vimrc is not read anymore.

**Comment by rmacklin** [comment]
It's in my `~/.config/nvim/init.vim` - I do not have SpaceVim.

**Comment by cemsbr** [comment]
Thanks. Changing `~/.config/nvim/init.vim` works with nvim and SpaceVim.

**Comment by jenstroeger** [comment]
Related discussion: https://vi.stackexchange.com/questions/37127/sqlcompletethe-dbext-plugin-must-be-loaded-for-dynamic-sql-completion
