### ISSUE TITLE
Reset command-completion after `:|` (:bar)

### ISSUE THREAD

**Issue by adigitoleo** [neovim/neovim#14443]
- `nvim --version`:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Operating system/version: (Arch) Linux x86_64 5.11.16-arch1-1

### Steps to reproduce

The following example function and user command provide a minimal vimrc as well as a potential use-case:

```vim
function! SmartSplit(...) abort
    if !empty(a:1)
        exec (winwidth(0) > 120 ? 'vert ' : '') .. 'sbuffer ' .. a:1
    else
        exec (winwidth(0) > 120 ? 'vert ' : '') .. 'split|enew'
    endif
endfunction

" Smart buffer splitting based on terminal width.
command! -nargs=? -complete=buffer SmartSplit call SmartSplit(<q-args>)

```

### Actual behaviour

Suppose I want to open a `:terminal` using this automatic splitting function. I type `:Sm` and hit Tab to get `:SmartSplit`. Now I add a bar and begin the next command `:SmartSplit | t`. Pressing Tab again doesn't offer command suggestions, and instead completes any buffer names that contain `t`. Compare to `:split | t` (and hit Tab).

### Expected behaviour

The `:|` (`:bar`) resets command-completion for user-defined commands, offering suggestions for the next command.

**Comment by matveyt** [comment]
Your command lacks `:h :command-bar` attribute. For this reason "bar" is treated as command argument, not command separator. So this is clearly a misuse / user error.

**Comment by adigitoleo** [comment]
Oops, that did it. My mistake. Cheers.
