### ISSUE TITLE
Can't download nightly release on for macOS

### ISSUE THREAD

**Issue by arsoda** [neovim/neovim#14461]
can't download https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
404

**Comment by AnthonyK213** [comment]
No nightly this time, maybe nvim 0.5 will be released soon. Check this out: [download](https://github.com/neovim/neovim/releases/download/untagged-d002fb3847115e4bcbfc/nvim-macos.tar.gz)

**Comment by jamessan** [comment]
Sometimes there are issues with the nightly build.  Just wait until the next day or someone re-runs the job.

**Comment by Barbarossa93** [comment]
Thanks for triggering a re-run @jamessan! Unfortunately it seems like there's still no release tag

**Comment by jamessan** [comment]
Yeah, and neither our workflow nor the action we use to publish has changed, so this looks like a GitHub change that broke the action.  I've been meaning to write one for us, instead of relying on the third-party actions. Might be time to do that
