### ISSUE TITLE
nvim_win_get_number(0) seems to always return 0

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#14467]
- `nvim --version`:

```
NVIM v0.5.0-dev+fbe18d9ca
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210429-2111-d3i8rp/build/config -I/tmp/neovim-20210429-2111-d3i8rp/src -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210429-2111-d3i8rp/build/src/nvim/auto -I/tmp/neovim-20210429-2111-d3i8rp/build/include
Compiled by julian@Airm.lan

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-fbe18d9_2/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently? *no*
- Operating system/version: macOS
- Terminal name/version: kitty+tmux
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Open two windows, then simply run `:lua print(vim.api.nvim_win_get_number(0))` and compare with `:lua print(vim.api.nvim_win_get_number(vim.api.nvim_get_current_win()))`

### Actual behaviour

Always returns 0

### Expected behaviour

Should return the visual window ID

**Comment by bfredl** [comment]
from the gitter, `win_get_tabwin(window, &tabnr, &rv)` should be changed to  `win_get_tabwin(win->handle, &tabnr, &rv)`;

**Comment by mhinz** [comment]
@Julian Do you want to create a PR for it?

**Comment by Julian** [comment]
Yeah will send one in a few hours thanks!
