### ISSUE TITLE
src/nvim/ui_compositor.c:369: compose_line: Assertion `until <= default_grid.Columns` failed

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#14478]
## environment
- `nvim --version`: latest master (b227cedf82341813514da55baa48511eca4014b0)
- Operating system/version: ubuntu 20.04
- reproduce in tui and nvim-qt

## Steps to reproduce
This bug is reliably reproducible using LSP hover.
I believe it's possible to reproduce it only using `nvim_open_win()`,
but I couldn't find the right combination of arguments.

0. Preparation
    * `example.lua` 
        ```lua
        require'asdaf'
        ```
    * `mini.vim`
        ```vim
        set runtimepath^=/path/to/nvim-lspconfig

        " foldcolumn=2 also works. foldcolumn=1 doesn't.
        set number
        " make the window small
        set lines=8 columns=80

        lua << EOF
        require'lspconfig'.sumneko_lua.setup {
          -- your configuration
        }
        EOF
        ```

1. `nvim -u mini.vim example.lua`
2. `<C-w>v<C-w><C-l>` (right vsplit)
3. `lua vim.lsp.buf.hover()` on "require"
4. `<C-p>` (move the cursor into the floating winow)
5. `<C-d>`

```
nvim: ../src/nvim/ui_compositor.c:369: compose_line: Assertion `until <= default_grid.Columns' failed
Aborted (core dumped)
```

## note
* related? https://github.com/neovim/neovim/issues/9989

**Comment by mjlbach** [comment]
Possibly also related https://github.com/neovim/neovim/issues/14377

I suspect this might also be border related.
