### ISSUE TITLE
Segfault on undo under specific circumstances

### ISSUE THREAD

**Issue by JA-Bar** [neovim/neovim#14477]
- `nvim --version`:
```
NVIM v0.5.0-dev+1283-g59eae3b38
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/testing/neovim/build/config -I/home/testing/neovim/src -I/home/testing/neovim/.deps/usr/include -I/usr/include -I/home/testing/neovim/build/src/nvim/auto -I/home/testing/neovim/build/include
Compiled by root@708456db7b2f

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

- `vim -u DEFAULTS` (version: ) behaves differently?
Issue with an interaction with a plugin not available in vim.

- Operating system/version:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

- Terminal name/version:
```alacritty 0.6.0-dev```

- `$TERM`:
```xterm```

### Steps to reproduce using `nvim -u NORC`

```nvim -u NORC```

Create a file with this particular structure:
```python
def some_function(args):
    print("stetement above")

    print("statement below")
```

Then in normal mode place the cursor in the first print statement, press o to start writing below, then enter while in insert mode to go down one line further, then write some statement in the middle, enter normal mode, delete it with let's say: dap in normal mode, and then repeadetely press u for undo. This will result in a segfault right before the print statement is deleted.

```python
def some_function(args):
    print("stetement above followed by an empty line")

    print("This will segfault when undone")

    print("statement below preceded by an empty line")
```

### Actual behaviour
Segfault just before the print statement gets undone.

### Expected behaviour
The action gets undone without issues.

### Explanation
I isolated the problem in a container with nothing but packer and the indent-blankline.nvim plugin installed. An [issue](https://github.com/lukas-reineke/indent-blankline.nvim/issues/100) was previously opened in the mentioned plugin repo, but I'm mentioning it here due to it being more appropriate. The linked issue has a more in depth explanation, a video of how it can be replicated, and the contents of the Dockerfile.

As per the FAQ, I'm also including the [backtrace](https://github.com/neovim/neovim/files/6410893/backtrace.txt). If there's any more information that may be helpful please let me know.

**Comment by lukas-reineke** [comment]
I investigated a bit as well. It is not related to setting the exmarks, the segfault happens without any auto commands.
And it only happens when undoing adding 2 lines with `o` + `enter` in between other lines that have virtual text.

Also cc @bfredl

**Comment by glacambre** [comment]
I can't reproduce this crash with `nvim -u NORC -i NONE -c 'set rtp+=/tmp/indentLine' -c 'set rtp+=/tmp/indent-blankline.vim' /tmp/tmp.py`. Can you check if it has been fixed on master?

**Comment by JA-Bar** [comment]
Oh you're correct, it appears to be fixed in master!

Thank you.
