### ISSUE TITLE
Support for .sol filetypes

### ISSUE THREAD

**Issue by AdamBD** [neovim/neovim#14476]
Hello!

I think there is a growing community of Neovim users that are working on blockchain development and it would be great to have .sol filetypes integrated to give access to integration with plugins etc.

**Comment by teto** [comment]
as far as the runtime is concered, we mostly merge patches from vim so you better ask on vim.

**Comment by chrisbra** [comment]
so does an actual filetype/plugin repository exist for `.sol` files?

**Comment by mhinz** [comment]
We don't create new filetypes on demand. That must be done by someone who knows and cares about `.sol` files. That someone should create an own plugin for it.

Then that plugin would be accepted and merged into Vim every now and and we would merge that runtime patch from Vim. That's the way it usually goes.
