### ISSUE TITLE
Add file type detection for Podman's Containerfiles

### ISSUE THREAD

**Issue by koernepr** [neovim/neovim#14474]
In addition to `Dockerfile`, Podman supports `Containerfile` as the default file name for container image build instructions (see [podman-build(1)](https://docs.podman.io/en/v3.1.2/markdown/podman-build.1.html#description)).

It would be nice if Neovim detected these files and set the file type to `dockerfile`.

This was introduced in Vim commit [1ff14ba](https://github.com/vim/vim/commit/1ff14ba24c4d85c008d7abe5e140dbb497ffea8d) in 2019, but for some reason did not make it into Neovim (Git master at 993ca90c9b53033216d4973e2f995b995ed5740e).

**Comment by teto** [comment]
someone needs to port the patch, check that it is not pending https://github.com/neovim/neovim/pulls?q=is%3Apr+is%3Aopen+vim-patch and if not you can do it.

**Comment by mhinz** [comment]
We have a monster PR ready that will merge all the missing runtime patches from Vim (including 1ff14ba).

This will be fixed in the next few days: https://github.com/neovim/neovim/pull/14424

**Comment by mhinz** [comment]
It's merged now.
