### ISSUE TITLE
softtabstop=4 doesn't work

### ISSUE THREAD

**Issue by BenSYZ** [neovim/neovim#14479]
- `nvim --version`:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: `5.11.16-arch1-1`
- Terminal name/version: `alacritty 0.7.2 (5ac8060b)`

### Steps to reproduce using `nvim -u xxx.vim`

```sh
/usr/bin/nvim -u ./softtabstop.vim
```

```vim
" ./softtabstop.vim
set softtabstop=4
set tabstop=8
set shiftwidth=8
set noexpendtab
set backspace=indent,eol,start
```

Press `<tab>` in insert mode.

### Actual behaviour

Tab character with width of 8 whitespace was insert.

### Expected behaviour
Like vim, the input character should be 4 whitespace.

**Comment by mhinz** [comment]
It's because Nvim defaults to `set smarttab` whereas Vim does not. And I can see how that is surprising.

**Comment by mhinz** [comment]
Dear community, if you do like the current state of `smarttab` being set by default, give a :+1: _on this comment_. If you oppose of that, give a :-1: instead.

(Do not add new comments unless you have anything to say.)

**Comment by matveyt** [comment]
I'd rather proposed default to `set softtabstop=-1`. Then it all depends on `shiftwidth` and `smarttab` does not matter.

**Comment by BenSYZ** [comment]
@matveyt Yes. But that insert a tab character at middle of a line sometimes are needed to me, which like `smarttab` does. Actually I should set `shiftwidth` according to my needs, and there is no need to consider the `softtabstop`. Because it's better to make the indentation behave the same in editing operation and other operations.

Thank you both for your suggestions.
