### ISSUE TITLE
Add new highlight groups: CursorLineSign and CursorLineFold

### ISSUE THREAD

**Issue by jlesquembre** [neovim/neovim#14473]
I'd like to have the same colors for `CursorLineNr` and for `SignColumn` (if `SignColumn` is the current line). Currently my neovim  looks like this:
![44f85035c321f2a74d519dc93b20def686198dc7](https://user-images.githubusercontent.com/1058504/116794323-823cb900-aacc-11eb-8cd0-111e0a73a69a.png)
It is not possible to define a different color for the current `SignColumn`

Based on this question:
https://neovim.discourse.group/t/cursorlinenr-and-signcolumn-highlight/416

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/cursorlinenr-and-signcolumn-highlight/416/3

**Comment by jlesquembre** [comment]
#16541 got merged :-)
