### ISSUE TITLE
PANIC: unprotected error in call to Lua API (bad callback)

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#14487]
- `nvim --version`: v0.5.0-dev
- `vim -u DEFAULTS` (version: ) behaves differently? Unclear
- Operating system/version: Fedora 34
- Terminal name/version: Alacritty
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
You tell me (no please, I seriously need to know to fix it :laughing:)

### Actual behaviour

While editing, I get this error sometimes, I can't find anything in the log that is suspicious, and I haven't been able to reproduce it so I can't get a good backtrace. I have a hunch it's a lua callback associated with the language server client.

### Expected behaviour

No crash.

I'm opening this issues to collect examples, and hopefully someone has a reliable reproduction, because if so I will fix it.

**Comment by VVKot** [comment]
Can confirm it is not only you, I've seen this about 3 times during last week. One time this was me deleting all contents of the buffer, something like that: `ggVGd` (on `d` nvim panicked). I am reasonably sure that was *.vim file, so I'd be running vim-language-server. Ofc I immediately went back and tried to do the same thing - it went fine. 🤷

**Comment by lewis6991** [comment]
> Can confirm it is not only you, I've seen this about 3 times during last week. One time this was me deleting all contents of the buffer, something like that: `ggVGd` (on `d` nvim panicked). I am reasonably sure that was *.vim file, so I'd be running vim-language-server. Ofc I immediately went back and tried to do the same thing - it went fine. 🤷

@VVKot , There's reason to believe gitsigns may be causing this. There was an attempt to fix this with https://github.com/lewis6991/gitsigns.nvim/issues/166 and I haven't seen the issue since. You may want to set `config.use_internal_diff=false` and see if the issue persists.

**Comment by VVKot** [comment]
Thanks @lewis6991 , I'll try that!

**Comment by mjlbach** [comment]
I just got this again today with the latest gitsigns, but I haven't turned off internal diff, I'll try that and see if it happens again...

**Comment by lewis6991** [comment]
Do you remember any details about the instance that crashed? Specifically:

- How many files did you hve open? 
- Did these files have lots of hunks? Was the total number of hunks across all files large?
- Did the error happen on a long running instance or quickly in a new one?
- Did you error happen whilst editing?

Just an idea looking at https://luajit.org/ext_ffi_semantics.html

> Callbacks take up resources — you can only have a limited number of them at the same time (500 - 1000, depending on the architecture). The associated Lua functions are anchored to prevent garbage collection, too. 

Whilst implenting the FFI diff in gitsigns I found that using the per-line callback crashed on any files over ~1000 lines. I was able to switch to using a different callback that was only called per hunk to get around this. My theory is if you have lots of hunks you might hit the callback limit for your system which might explain why I haven't seen this issue on my M1 macbook which might have a higher limit.

If this theory is true, there are a couple things we can do to mitigate (but not eliminate) the problem:
- Modify the callback in gitsigns to do as little work as possible so we spend less time in it.
- Increase the debounce time of update to cause less diffs being run.

To actually eliminate the issue the only solutions would be to not use FFI (which would be shame), or modify core to provide a pull-style API for xdiff as opposed to the push-style we currently use.

> For new designs avoid push-style APIs: a C function repeatedly calling a callback for each result. Instead use pull-style APIs: call a C function repeatedly to get a new result. Calls from Lua to C via the FFI are much faster than the other way round. Most well-designed libraries already use pull-style APIs (read/write, get/put).

**Comment by mjlbach** [comment]
Sorry for the delay. I didn't have a way to recover the session:

I would estimate 12 files with roughly 10 hunks each, so on the order of 100 hunks? 

It was a long running instance

It happened while in insert mode/editing

I'm on an intel macbook, so no m1 goodness.

I'm going to try running for a couple weeks with the gitsigns internal diff off to see if I can't reproduce it. I wish I could find a more reliable set of triggers, as this is all still very speculative

**Comment by windwp** [comment]
i usually got this error before but after disable internal diff it is better now.

**Comment by mjlbach** [comment]
When you say better, do you mean you haven't experienced the error yet? If so, we should probably move this issue over to gitsigns (I'm happy to do any core work to support the pull-style api, although I'd need to know a bit more and the implementation might take me awhile as its not something I'm familiar with)

**Comment by duikboot** [comment]
> i usually got this error before but after disable internal diff it is better now.

For me also. The error frequently happened to me with only one file open and with a fresh instance.

**Comment by lewis6991** [comment]
So apparently the FFI usage in gitsigns had some problems which should be fixed in the latest update. If we still get the PANIC error then Lua bindings will be the way.

**Comment by bfredl** [comment]
what functions does gitsigns call over FFI?

**Comment by lewis6991** [comment]
`xdl_diff` which is in the xdiff library. Here's the ffi cdef:

```lua
ffi.cdef[[
  typedef struct s_mmbuffer { const char *ptr; long size; } mmbuffer_t;

  typedef struct s_xpparam {
    unsigned long flags;

    // See Documentation/diff-options.txt.
    char **anchors;
    size_t anchors_nr;
  } xpparam_t;

  typedef long (__stdcall *find_func_t)(
    const char *line,
    long line_len,
    char *buffer,
    long buffer_size,
    void *priv
  );

  typedef int (__stdcall *xdl_emit_hunk_consume_func_t)(
    long start_a, long count_a, long start_b, long count_b,
    void *cb_data
  );

  typedef struct s_xdemitconf {
    long ctxlen;
    long interhunkctxlen;
    unsigned long flags;
    find_func_t find_func;
    void *find_func_priv;
    xdl_emit_hunk_consume_func_t hunk_func;
  } xdemitconf_t;

  typedef struct s_xdemitcb {
    void *priv;
    int (__stdcall *outf)(void *, mmbuffer_t *, int);
  } xdemitcb_t;

  int xdl_diff(
    mmbuffer_t *mf1,
    mmbuffer_t *mf2,
    xpparam_t const *xpp,
    xdemitconf_t const *xecfg,
    xdemitcb_t *ecb
  );
]]
```

**Comment by bfredl** [comment]
ok, so at least not any `breakcheck` calls in the c code itself. let me see what your callback does..

**Comment by VVKot** [comment]
Is there anything to do in this issue for 0.5 specifically? As far as I can tell, the problem was with the plugin, the plugin is fixed, and I have't experienced panics since updating the plugin.

**Comment by VVKot** [comment]
@mjlbach @bfredl

**Comment by mjlbach** [comment]
@VVKot Are you just asking because it's milestoned? I can remove the milestone, but those are really only used for tracking purposes (and aren't affecting the 0.5 release timeline). I also haven't experienced this in awhile, and there's a tracking issue for exposing bindings to xdiff.

**Comment by lewis6991** [comment]
We highly believe but do not know it is because of a plugin. However I haven't seen the issue since the last update so I think we should just close this personally.
