### ISSUE TITLE
Plenary.job crashes editor on Windows

### ISSUE THREAD

**Issue by Shatur95** [neovim/neovim#14484]
- `nvim --version`: NVIM v0.5.0-dev+1265-g66f9dd3c6
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Windows 10

### Steps to reproduce using `nvim -u NORC`

1. Install [plenary](https://github.com/nvim-lua/plenary.nvim).
1. Execute the following code:

```lua
  local Job = require'plenary.job'
  Job:new({
  command = 'rg',
  args = { '--files', '.' },
  on_exit = function(j, return_val)
    print(return_val)
    print(j:result())
  end,
}):sync()
```

### Actual behaviour

The editor crashes.

### Expected behaviour

The editor does not crash.

**Comment by clason** [comment]
Are you sure this is an issue with neovim and not with plenary specifically?

**Comment by Shatur95** [comment]
@clason, I'm not sure. But I think that even if there is some problem in plenary, then the editor should not crash.

**Comment by Shatur95** [comment]
@clason, @Conni2461, I think it will be better to continue the discussion here. I compiled Neovim in debug on Windows and I get this error immediately at startup:

![изображение](https://user-images.githubusercontent.com/22453358/116879298-2dfb1b80-ac29-11eb-8b44-457694871554.png)

**Comment by mjlbach** [comment]
It's impossible to protect neovim from all lua crashes (esp anything involving the FFI for example). You should file an issue with plenary.

**Comment by Shatur95** [comment]
@mjlbach, it can be reproduced without plenary:

```lua
local uv = vim.loop

local stdin = uv.new_pipe(false)
local stdout = uv.new_pipe(false)
local stderr = uv.new_pipe(false)

local handle = uv.spawn("rg", {
  args = { '--files' },
  stdio = { stdin, stdout, stderr }
}, function() end)

uv.read_start(stdout, function(err, data)
  assert(not err, err)
  if data then
    print(vim.inspect(data))
  end
end)

uv.read_start(stderr, function() end)

uv.shutdown(stdin, function()
  uv.close(handle, function() end)
end)
```

**Comment by mjlbach** [comment]
^ That doesn't crash on Windows for me, so I assume there's something wrong in you config, Maybe you overrode vim.loop.spawn as according to lspconfig on windows and that's causing an issue.

**Comment by Shatur95** [comment]
You are right, very strange, but with the latest master I can no longer reproduce this problem.
