### ISSUE TITLE
API: expose list of digraphs (for completion, plugins, ...)

### ISSUE THREAD

**Issue by teto** [neovim/neovim#14485]
Digraphs are cool, I find myself using them more and more. Would love to have a popup after inputting the first character. Not sure how to do that though/how hard it is.
https://github.com/neovim/neovim/blob/ad811444424f573c4dc10b203f8f42adb3c5fdf4/src/nvim/digraph.c#L51

**Comment by clason** [comment]
Not quite what you had in mind, but should be easy to include in https://github.com/nvim-telescope/telescope-symbols.nvim :)

**Comment by teto** [comment]
Yes I had commented at https://github.com/nvim-telescope/telescope.nvim/issues/162, Was wondering if made sense to move the list of digraphs to a lua file that generates some C code like is done in options.lua .

**Comment by TornaxO7** [comment]
I'd like to have an autocompletion for diagraphs as well but without telescope. It slows down my config.

**Comment by cbandy** [comment]
https://github.com/chrisbra/unicode.vim

**Comment by zeertzjq** [comment]
Related: #17440
