### ISSUE TITLE
Making neovim use the cursor used by the terminal ?

### ISSUE THREAD

**Issue by Brokenhammer72** [neovim/neovim#14496]
Is there we to make neovim use the cursor used by the terminal like I use (_) in terminal so how can I make nvim use the same thing ?

**Comment by bew** [comment]
Hello, you can read `:h tui-cursor-shape`
Then head to `:h 'guicursor'`

```
:set guicursor=
```
Should fix it

**Comment by Brokenhammer72** [comment]
thanks for the reply its working as expected
