### ISSUE TITLE
LSP: Allow configuration to control processId

### ISSUE THREAD

**Issue by adrianord** [neovim/neovim#14504]
When running LSPs in a container that were made with [vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node), the processId is passed to the server and is periodically checked. If the PID passed to the language server no longer exists, the language server kills itself. This causes the language server to exit 3 seconds after neovim initializes the connection due to neovim's process not existing in the container.

The fix for this is to pass processId as `null` to the language server. This turns off checks that the client process is still running.

This is the current work around in neovim
```lua
vim.loop.getpid = function() return nil end
```
This will then pass nil to processId when it reaches the `initialize_params` here (`uv` being `vim.loop`)
https://github.com/neovim/neovim/blob/8a93d1028f38c77d7ad8b4ad0a93dc11a5cbe85d/runtime/lua/vim/lsp.lua#L777-L821
This seems like a rather dangerous workaround depending on how `getpid` is used in other parts of neovim.

I would rather be able to set the `processId` `initialization_param` like I would capabilities or rootUri.

**Comment by mjlbach** [comment]
I'd recommend running the container with `--pid=host`, I think this is much simpler than adding a configurable workaround.

**Comment by adrianord** [comment]
Thank you for the suggestion, while this might have worked for a regular linux distro running docker(I can try this too if you'd like, I have pop_os on my laptop), this does not work for WSL2 since Docker Desktop runs docker as a separate distro in WSL2, which gives it it's own pid namespace.

**Comment by adrianord** [comment]
I'd also like to point out that setting processId to `null` is the recommended way to avoid client process checks by the team that wrote vscode-languageserver-node

https://github.com/microsoft/vscode-languageserver-node/issues/364#issuecomment-431385346

**Comment by mjlbach** [comment]
Right, my suggestion was to enable the client process check, but just share the host process namespace with the container which should work on linux.

For your use case, you can use before_init to override initialize_params.process_id to `vim.NIL`.

https://github.com/neovim/neovim/blob/9149fe48a91a60f61a0b461231e894f0884835fd/runtime/lua/vim/lsp.lua#L822-L825

**Comment by adrianord** [comment]
Works perfect, thank you very much for your help! 😊

**Comment by davetron5000** [comment]
If you are coming here and don't know the syntax to do what is suggested, here it is:

```lua
  lspconfig.cssls.setup({
    cmd = { ... },
    before_init = function(params)
      params.processId = vim.NIL
    end,
  })
```

**Comment by richardhapb** [comment]
Nice! I made a simple tool for handling this because communicating with an LSP inside a container can be tricky due to different paths and environments; it may be useful.

https://github.com/richardhapb/lsproxy
