### ISSUE TITLE
Switch arrow key behavior in command mode

### ISSUE THREAD

**Issue by cedl38** [neovim/neovim#14506]
Since nvim changed list selection in command mode from horizontal style to vertical, I feel little bit confused/uncomfortable about the usage of arrow keys. I often use down arrow key instead of right and vice versa.

Through I like the new layout, would it be possible to switch arrow key behavior to more "natural" behavior, according to this new arrangement. Or perhaps allow user to change default behavior.

If this kind of customization is already possible, I will be glad to heard from it.

![screenshot-2021-05-06-2](https://user-images.githubusercontent.com/3024887/117337081-39567d00-ae9d-11eb-87a0-f70192471e8c.png)
_Screenshot of the selection list in command mode_

### Actual behaviour
In command mode list selection, down arrow key jump to subdirectory of selected path.

### Expected behaviour
In command mode list selection, down arrow key _should_  get to the next selected entry below the actual selection.

**Comment by jdhao** [comment]
It seems that you need to remap keys to make it work as you want, but it is not that simple. 
The following links provide some useful information:

+ https://vi.stackexchange.com/questions/22627/switching-arrow-key-mappings-for-wildmenu-tab-completion
+ https://www.reddit.com/r/neovim/comments/d76mex/query_is_it_possible_to_swap_updown_and_leftright/
+ https://github.com/neovim/neovim/pull/11001

**Comment by cedl38** [comment]
Thank you for your helpful reply. It is exactly what I was looking for.
 I close this post as it should be resolved by [#11001](url).
