### ISSUE TITLE
LSP PHP omni completion on variables / after $ not working

### ISSUE THREAD

**Issue by inventionate** [neovim/neovim#14509]
I'm unsure if it fits here, so I have already created an issue at neovim/nvim-lspconfig#886. However, after reading #12997 I think it could also be a more fundamental implementation problem. A minimal example etc. can be found in my issue at lspconfig. Maybe someone can help? Many thanks in advance!

**Comment by mjlbach** [comment]
I'll transfer your issue from nvim-lspconfig to core if it turns out to be an implementation issue (I'm almost certain it's not though). Let's try to minimize duplicate issues, as the same people will be helping you anyways.

**Comment by inventionate** [comment]
Sorry about that! I'm not familiar with the organisational structures. Thank you for the help and service!
