### ISSUE TITLE
gmock not listed as a dependency in Arch Linux in the Wiki

### ISSUE THREAD

**Issue by giftinglass** [neovim/neovim#14513]
I couldn't compile neovim because of a missing library related to gmock in Arch Linux. After installing it, it works.

**Comment by mhinz** [comment]
Neither Neovim nor any of its dependencies (to my knowledge) is using Google Mock. And it's certainly not needed when compiling from the repo.

**Comment by jamessan** [comment]
> How did you try to compile?

More importantly, where's a build log showing the problem.  Without information, it's difficult to figure out what's going on.

If you can reproduce the issue, and have data to provide, please reopen.
