### ISSUE TITLE
NVIM v0.5.0-dev+1309-g516551319 throws "cannot execute binary file: Exec format error"

### ISSUE THREAD

**Issue by luisiacc** [neovim/neovim#14519]
Tried this compilation, It throws this error:
`./squashfs-root/usr/bin/nvim: cannot execute binary file: Exec format error`
OS: WSL Ubuntu 18.04 , the version from 7 days ago was working just fine.
Can somebody upload a version prior to this one to try it ?
`uname -a` -> `Linux acc 4.4.0-17763-Microsoft #55-Microsoft Sat Oct 06 18:05:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
`
If i try with: `sudo nvim`:
```
./nvim: 1: ./nvim: ELF: not found
./nvim: 2: ./nvim: Syntax error: Unterminated quoted string
```

Any help would be appreciated, I can't use neovim because of this, I didn't save the previous ./nvim.appimage.

All versions from this one forward throw the same error.

**Comment by luisiacc** [comment]
Now with 0.5.0-dev+1311 its this error with sudo:
```
./squashfs-root/usr/bin/nvim: 1: ./squashfs-root/usr/bin/nvim: ELF: not found
./squashfs-root/usr/bin/nvim: 2: ./squashfs-root/usr/bin/nvim: ▒▒: not found
./squashfs-root/usr/bin/nvim: 3: ./squashfs-root/usr/bin/nvim: @8
                                                                 @$@@@0ppp      I       I ▒I▒i▒i▒▒8R ▒▒K▒▒k▒▒k`▒▒▒DD▒I▒i▒i P▒td▒CA▒CA▒CA▒▒Q▒tdR▒td▒I▒i▒iP▒P▒/lib64/ld-linux-x86-64.so.2GNUGNU▒wvP▒HzƋ]▒▒n▒: not found
./squashfs-root/usr/bin/nvim: 4: ./squashfs-root/usr/bin/nvim: ▒: not found
./squashfs-root/usr/bin/nvim: 3: ./squashfs-root/usr/bin/nvim: Syntax error: Unterminated quoted string
```

**Comment by garcia5** [comment]
Same issue here

**Comment by luisiacc** [comment]
I rewolved my issue by building from source, it's actually pretty easy.

**Comment by garcia5** [comment]
You're right, that is straightforward and solved the issue for me. Thanks!

**Comment by jamessan** [comment]
The only thing that's changed recently for building the appimage was switching from Ubuntu 16.04 to 18.04.  That happened with the v0.5.0-dev+1299-g1c2e504d5 nightly, on May 5th.

The appimage themselves still work in other environments, so this seems to be something specific about WSL and not the appimage.

**Comment by mg979** [comment]
I'd say it seems specific to the way it's built rather than WSL because before it worked, and now it doesn't.

**Comment by Rimann91** [comment]
Having the same problem on WSL Ubuntu 20.04. Any resolution?

**Comment by Rimann91** [comment]
I was able to solve this by upgrading to WSL2

**Comment by dundargoc** [comment]
Life finds a way :)
