### ISSUE TITLE
Nighlty builds missing

### ISSUE THREAD

**Issue by zacmar** [neovim/neovim#14527]
I can no longer find a release page for nightly builds. Since [https://github.com/neovim/neovim/wiki/Installing-Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim) links to [https://github.com/neovim/neovim/releases/nightly](https://github.com/neovim/neovim/releases/nightly) (404 Error), and it is not documented anywhere (at least not easily seen) that there are no nightly build for some reason, I assume that this is a bug (maybe in CI?).

**Comment by mhinz** [comment]
Fixed.
