### ISSUE TITLE
Bad syntax highlighting for function call in autocmd

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#14523]
- `nvim --version`: v0.5.0-dev+1268-g02909d150

### Steps to reproduce using `nvim -u NORC`
Create a file `foo.vim` and type the following:
```
augroup Foo
  autocmd WinEnter * call abs(0)
augroup END
```

### Actual behaviour
The function `abs` is highlighted as an error.

### Expected behaviour
The syntax highlighting should not report an error. This is a regression since Neovim 0.4.2.

**Comment by glacambre** [comment]
This doesn't happen in Vim and just copying `runtime/syntax/vim.vim` from Vim's repo to Neovim's fixes this problem, so it's just a matter of porting the runtime file.

**Comment by mhinz** [comment]
Either Nvim wasn't installed properly or you ran `build/bin/nvim` directly from the repo.

In the latter case and since we auto-generate the `vim` syntax file, you need to do this:

```vim
  if v:progpath =~# 'build/bin/nvim$'
    " for build/runtime/syntax/vim/generated.vim
    set runtimepath+=$VIM/build/runtime
  endif
```
