### ISSUE TITLE
PR #13664 cause floating window close

### ISSUE THREAD

**Issue by ray-x** [neovim/neovim#14524]
Is PR #13664 https://github.com/neovim/neovim/commit/5165513198dbbe7415f1b8c51225ae8f822628ec  changed floating widnow API ?

The changes between 4be0e92db0 and 5165513198db broken my plugin https://github.com/ray-x/guihua.lua/

The test: https://github.com/ray-x/guihua.lua/blob/master/lua/guihua/tests/listview_test.lua failed. The test is supposed to create a list view window and with cursor moving, it should create a floating window of preview.  But currently, if the cursor moved, the listview will be destroyed.

@ivechan

**Comment by seandewar** [comment]
#14090 documents the main breaking change:

> `nvim_win_set_buf` does not block autocommands

You may want to subscribe to that issue if you're maintaining plugins for 0.5.

**Comment by seandewar** [comment]
PR #14531 may revert the problematic commit if a fix isn't found soon.

For plugin maintainers looking for a possible temporary workaround, reading https://github.com/asvetliakov/vscode-neovim/issues/632#issuecomment-837201224 may be of some use.
