### ISSUE TITLE
lsp: Detach buffer from a client

### ISSUE THREAD

**Issue by ii14** [neovim/neovim#14535]
Besides stopping the entire client and then reattaching each buffer, is there any way to simply detach a single buffer from a client? I'm looking through both source code and documentation and I can't see anything like that.

**Comment by mjlbach** [comment]
nvim_buf_detach is for remote clients, I know how to terminate the nvim_buf_attach callback. I'll handle it, but it might not happen for a week or two.

**Comment by ii14** [comment]
Alright, thanks a lot. I wish I could help, but it seems like I don't know enough about it. What would be also cool is having a `on_detach` callback in the lsp.client config once we're able to detach buffers.

**Comment by mjlbach** [comment]
There already is an on_detach callback

**Comment by ii14** [comment]
Is there? I only found it in nvim_buf_attach, but it's not exposed to the user
