### ISSUE TITLE
Feature: Gettext support for Vimscript.

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#1453]
Messages shown by Vimscript (not only plugins, but also e.g. #1454) are part of the "UI" of (Neo)vim, yet it is not possible to localize them.

A patch to support gettext in Vimscript has been proposed upstream and maybe could be adapted: http://vim.1045645.n5.nabble.com/gettext-support-for-vim-script-td1196097.html

Just so this isn't forgotten.. original discussion was in https://github.com/neovim/neovim/pull/1358#discussion_r19572951

**Comment by justinmk** [comment]
This is `wontfix` until Vim implements it upstream. Enhancing VimL is not worth our time.

**Comment by zeertzjq** [comment]
Added in #20832
