### ISSUE TITLE
Race condition in config load while opening tabs/splits

### ISSUE THREAD

**Issue by ubitux** [neovim/neovim#14533]
- `nvim --version`: `v0.4.4`, `v0.5.0-dev+1315-g133351cbf`
- Operating system/version: Linux (x86_64)
- Terminal name/version: alacritty 0.7.2
- `$TERM`: `alacritty`

[x] `vim -u DEFAULTS` (version: 8.2.2814) behaves differently

### Steps to reproduce

When opening a file with `^T`, `^V` or `^X` from the `fzf` popup, some settings are sometimes not loaded properly. The race seems only reproducible while using `fzf` (report: https://github.com/junegunn/fzf/issues/2386) but is **not reproducible with Vim**, which makes me believe this is a neovim core issue highlighted by fzf.

The following configuration is required:

```vim
call plug#begin()
Plug 'junegunn/fzf.vim'
call plug#end()

nnoremap <C-p> :Files<CR>
set cursorline
set cursorcolumn
```

And the following context setup:

```console
% mkdir -p /tmp/test
% cd /tmp/test
% echo "123\n456\n789" > a.txt
% nvim
```

The bug can now be reproduced by spamming `^P` `^T` (keep `Ctrl` pressed down and spam `P` `T` `P` `T` ...), which will open many tabs with `a.txt`. After a few tabs (very quickly, sometimes at the first one), the `cursorline`/`cursorcolumn` settings will go away.

https://user-images.githubusercontent.com/34467/117793167-42a06a80-b24c-11eb-8a59-328336f5e920.mp4

I'm unfortunately unable to reproduce without `fzf`: I typically tried a recording with `:tabedit a.txt` but it didn't trigger the issue for some reason.

**Comment by justinmk** [comment]
> I'm unfortunately unable to reproduce without `fzf`: I typically tried a recording with `:tabedit a.txt`

fzf uses different logic for Nvim, and Nvim's `:terminal` is asynchronous whereas on Vim, fzf (at least used to) default to using `system()` which is synchronous.

**Comment by ubitux** [comment]
Re-opened here: https://github.com/neovim/neovim/issues/16941

Not actually a race condition, but a compare-after-free pointer issue.
