### ISSUE TITLE
Environment variables are getting duplicated by Neovim on Windows

### ISSUE THREAD

**Issue by rashil2000** [neovim/neovim#14541]
- `nvim --version`: NVIM v0.5.0-dev+1312-gd2be261e8
- Operating system/version: Microsoft Windows [Version 10.0.19042.928]
- Terminal name/version: doesn't matter
- `$TERM`: xterm-256color 

### Actual behaviour
Some of the git commands fail inside the builtin terminal. Can be reproduced by `nvim --cmd term`.

Examples include `scoop update` (which uses git underneath) and `git checkout`. Here's the output: 
```
> scoop update
Updating scoop...
Update failed.

> git checkout develop
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
.git/hooks/post-checkout: line 8: dirname: command not found
.git/hooks/post-checkout: line 8: /husky.sh: No such file or directory
```

### Expected behaviour
Interestingly, none of these errors occur in NVIM v0.4.4. Here's what happens in 0.4.4:

```
> scoop update
Updating scoop...
Updating 'main' bucket...
Updating 'extras' bucket...
Scoop was updated successfully!

> git checkout develop
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
```

**Comment by mhinz** [comment]
Does that also happen with other repos? (Maybe just `git init foo`, `cd foo`, `git checkout -b blah`, `git checkout main`.)

I just wonder if it could somehow be related to the custom hook `.git/hooks/post-checkout`.

**Comment by rashil2000** [comment]
I can confirm that weird errors happen with other repositories too. Like running `git stash` in a repo with unstaged changes gave me:
```
Cannot save the current worktree state
```

(The example you gave above gives an error `error: pathspec 'main' did not match any file(s) known to git`, but that error is not unique to nvim here, it happens in Git Bash too. I think we need to stage some files first for that).

I tried to build Neovim locally to bisect the commit where this regression came up, but I was not successful. See #14362

**Comment by jamessan** [comment]
Can you post the output of running the `env` command in the nvim terminal for both 0.4.4 and HEAD/nightly?

**Comment by rashil2000** [comment]
`env` is a bash-specific command. The Windows cmd equivalent is `set`. Here's the output:

<details>
<summary>0.4.4</summary>
<pre>
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\<username>\AppData\Roaming
CARGO_HOME=C:\Users\<username>\scoop\persist\rustup-msvc\.cargo
CHERE_INVOKING=1
COLORTERM=truecolor
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=OMEN-15
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\<username>
ICEMCFD_SYSDIR=win64_amd
INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
LOCALAPPDATA=C:\Users\<username>\AppData\Local
LOGONSERVER=\\OMEN-15
MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\mic
MSYS=enable_pcon
MSYS2_PATH_TYPE=inherit
NUMBER_OF_PROCESSORS=12
NVIM_LISTEN_ADDRESS=\\.\pipe\nvim-18144-0
OneDrive=C:\Users\<username>\OneDrive
OneDriveConsumer=C:\Users\<username>\OneDrive
OnlineServices=Online Services
OS=Windows_NT
Path=C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\VMware\VMware Player\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\<username>\scoop\apps\rustup-msvc\current\.cargo\bin;C:\Users\<username>\scoop\apps\nodejs-lts\current\bin;C:\Users\<username>\scoop\apps\nodejs-lts\current;C:\MSys2\cmd;C:\Users\<username>\scoop\apps\gsudo\current;C:\Users\<username>\scoop\shims;C:\Users\<username>\.local\bin;C:\Users\<username>\AppData\Local\Microsoft\WindowsApps;C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\<username>\.local\mera-samaan\Neovim-Stable\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PS1
platformcode=KV
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e0a
ProgramData=C:\ProgramData
ProgramFiles(x86)=C:\Program Files (x86)
ProgramFiles=C:\Program Files
ProgramW6432=C:\Program Files
prompt=CLINK $P$G$S
PSModulePath=D:\Data\Documents\WindowsPowerShell\Modules
PUBLIC=C:\Users\Public
RegionCode=APJ
RUSTUP_HOME=C:\Users\<username>\scoop\persist\rustup-msvc\.rustup
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\<user>~1\AppData\Local\Temp
TERM=xterm-256color
TMP=C:\Users\<user>~1\AppData\Local\Temp
USERDOMAIN_ROAMINGPROFILE=OMEN-15
USERDOMAIN=OMEN-15
USERNAME=<username>
USERPROFILE=C:\Users\<username>
VIMRUNTIME=C:\Users\<username>\.local\mera-samaan\Neovim-Stable\share\nvim\runtime
windir=C:\WINDOWS
</pre>
</details>

<details>
<summary>0.5.0-dev+1318-g61aefaf29</summary>
<pre>
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\<username>\AppData\Roaming
CARGO_HOME=C:\Users\<username>\scoop\persist\rustup-msvc\.cargo
CHERE_INVOKING=1
COLORTERM=truecolor
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=OMEN-15
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\<username>
ICEMCFD_SYSDIR=win64_amd
INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
LOCALAPPDATA=C:\Users\<username>\AppData\Local
LOGONSERVER=\\OMEN-15
MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\mic
MSYS=enable_pcon
MSYS2_PATH_TYPE=inherit
NUMBER_OF_PROCESSORS=12
NVIM_LISTEN_ADDRESS=\\.\pipe\nvim-4772-0
NVIM_LOG_FILE=C:\Users\<user>~1\AppData\Local\Temp\nvim\log
OneDrive=C:\Users\<username>\OneDrive
OneDriveConsumer=C:\Users\<username>\OneDrive
OnlineServices=Online Services
OS=Windows_NT
Path=C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\VMware\VMware Player\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\<username>\scoop\apps\rustup-msvc\current\.cargo\bin;C:\Users\<username>\scoop\apps\nodejs-lts\current\bin;C:\Users\<username>\scoop\apps\nodejs-lts\current;C:\MSys2\cmd;C:\Users\<username>\scoop\apps\gsudo\current;C:\Users\<username>\scoop\shims;C:\Users\<username>\.local\bin;C:\Users\<username>\AppData\Local\Microsoft\WindowsApps;C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\<username>\.local\mera-samaan\Neovim-Nightly\bin
PATH=C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\VMware\VMware Player\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\<username>\scoop\apps\rustup-msvc\current\.cargo\bin;C:\Users\<username>\scoop\apps\nodejs-lts\current\bin;C:\Users\<username>\scoop\apps\nodejs-lts\current;C:\MSys2\cmd;C:\Users\<username>\scoop\apps\gsudo\current;C:\Users\<username>\scoop\shims;C:\Users\<username>\.local\bin;C:\Users\<username>\AppData\Local\Microsoft\WindowsApps;C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\<username>\.local\mera-samaan\Neovim-Nightly\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PS1
platformcode=KV
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e0a
ProgramData=C:\ProgramData
ProgramFiles(x86)=C:\Program Files (x86)
ProgramFiles=C:\Program Files
ProgramW6432=C:\Program Files
prompt=CLINK $P$G$S
PSModulePath=D:\Data\Documents\WindowsPowerShell\Modules
PUBLIC=C:\Users\Public
RegionCode=APJ
RUSTUP_HOME=C:\Users\<username>\scoop\persist\rustup-msvc\.rustup
SESSIONNAME=Console
SystemDrive=C:
SYSTEMDRIVE=C:
SystemRoot=C:\WINDOWS
SYSTEMROOT=C:\WINDOWS
TEMP=C:\Users\<user>~1\AppData\Local\Temp
TERM=xterm-256color
TMP=C:\Users\<user>~1\AppData\Local\Temp
USERDOMAIN_ROAMINGPROFILE=OMEN-15
USERDOMAIN=OMEN-15
USERNAME=<username>
USERPROFILE=C:\Users\<username>
VIMRUNTIME=C:\Users\<username>\.local\mera-samaan\Neovim-Nightly\share\nvim\runtime
windir=C:\WINDOWS
WINDIR=C:\WINDOWS
</pre>
</details>

The only difference I can notice here is that the Nightly version seems to make duplicate environment variables with capitalized letters (variable names in Windows are otherwise case-insensitive) - for `windir`, `SystemDrive`, `SystemRoot`, and `Path`.

**Comment by rashil2000** [comment]
Although it's worth mentioning that, since I can specify any shell to use by doing `nvim term://<shell>`, I tried to open Git Bash shell inside it. There, all the git commands work without any errors.

**Comment by rashil2000** [comment]
Although this seems unrelated, but this duplication thing is causing some seemingly serious problems. In PowerShell, the command to list environment variables is `Get-ChildItem Env:`. This works fine in Nvim Stable (when `nvim term://powershell` is used to launch the builtin terminal). But in the nightly version, even this simple command gives me errors:
```ps
❯ Get-ChildItem Env:
Get-ChildItem : An item with the same key has already been added.
At line:1 char:1
+ Get-ChildItem Env:
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ChildItem], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands
   .GetChildItemCommand
```

On deleting the duplicated variables as mentioned in my previous comment, the above command returns the expected output successfully.

**Comment by mhinz** [comment]
Although the Win docs write environment variables all uppercase, it seems to be conventional to use camel case in Powershell, which works because Win env vars are case-insensitive.

We set these variables:

https://github.com/neovim/neovim/blob/61aefaf2993c0b55f6123ba4b0bd41b1caf1fcd3/src/nvim/eval/funcs.c#L5031-L5046

Here we check whether the required vars are in the env already or not, but `tv_dict_find()` is case-sensitive, so the search fails and vars get set twice:

https://github.com/neovim/neovim/blob/61aefaf2993c0b55f6123ba4b0bd41b1caf1fcd3/src/nvim/eval/funcs.c#L5106-L5117

**Comment by jamessan** [comment]
I specifically ignored handling the case insensitivity issue in https://github.com/neovim/neovim/pull/12937. Wasn't sure if it would cause practical problems. Kinda surprised it took this long for something to get reported.

**Comment by rashil2000** [comment]
I came to know about Nightly builds just a few days ago. Would've definitely reported this earlier if I had known 😅

Hopefully, this gets fixed soon.

**Comment by mhinz** [comment]
I guess we either need to introduce a `tv_dict_find_ignorecase()` or add `bool ignorecase` to the definition of `tv_dict_find()`. I'd vote for the latter, even though a lot of existing function calls would need to be altered.

Eventually we need to use `STRNICMP()` instead of `STRNCMP()` in `hash_lookup()`.

**Comment by jamessan** [comment]
Since we're now explicitly defining the environment for jobs we launch, maybe it's better to normalize env var names internally on Windows.

**Comment by rashil2000** [comment]
Sorry, I'm not sure I understand what we mean by normalizing env var names?

**Comment by rashil2000** [comment]
Is there any update on this? Did I miss something?

**Comment by mhinz** [comment]
> Is there any update on this? Did I miss something?

No, if no one wrote anything in here or linked a PR, then no one is working at it.

> [...] what we mean by normalizing env var names?

Our `required_env_vars` are all uppercase. Whereever we get the job environment, we should save it on Windows as all uppercase as well. So your `SystemRoot` would be saved internally as `SYSTEMROOT` and therefore comparisons would never fail due to case issues.

**Comment by rashil2000** [comment]
> Our `required_env_vars` are all uppercase. Whereever we get the job environment, we should save it on Windows as all uppercase as well. So your `SystemRoot` would be saved internally as `SYSTEMROOT` and therefore comparisons would never fail due to case issues.

But isn't this something that's happening currently at the moment? Neovim is saving them in all uppercase as in your previous comment, right?
```c
    ...
    tv_dict_add_str(env, required_env_vars[i], len, env_var);
    ...
```
Here, all the elements in the `required_env_vars` array are in uppercase.

**Comment by jamessan** [comment]
I have some changes in progress. Should have a PR today or tomorrow.
