### ISSUE TITLE
tmux clipboard load-buffer command should use -w switch

### ISSUE THREAD

**Issue by smhc** [neovim/neovim#14545]
- `NVIM v0.5.0-dev+1311-gf8173df4d`:
- Operating system/version: Linux
- Terminal name/version: tmux 3.3next
- `xterm-256color`:

### Steps to reproduce using `nvim -u NORC`

see: https://github.com/tmux/tmux/issues/2645#issuecomment-839470889
and https://gist.github.com/smhc/7b873a553d75af7142f38b7993f5f0ec

```

set clipboard+=unnamedplus

" Default setting for g:clipboard, taken from doc
let g:clipboard = {
          \   'name': 'myClipboard',
          \   'copy': {
          \      '+': ['tmux', 'load-buffer', '-'],
          \      '*': ['tmux', 'load-buffer', '-'],
          \    },
          \   'paste': {
          \      '+': ['tmux', 'save-buffer', '-'],
          \      '*': ['tmux', 'save-buffer', '-'],
          \   },
          \   'cache_enabled': 1,
          \ }
```

### Actual behaviour

When neovim uses the `tmux load-buffer` command it copies the text to the tmux buffer but does not copy to the system clipboard via OSC 52. The new '-w' switch introduced in tmux 3.2 is required to do this.

### Expected behaviour

```
let g:clipboard = {
          \   'name': 'myClipboard',
          \   'copy': {
          \      '+': ['tmux', 'load-buffer', '-w', '-'],
          \      '*': ['tmux', 'load-buffer', '-w', '-'],
          \    },
          \   'paste': {
          \      '+': ['tmux', 'save-buffer', '-'],
          \      '*': ['tmux', 'save-buffer', '-'],
          \   },
          \   'cache_enabled': 1,
          \ }
```

Note that the '-w' switch will cause an error with older versions of tmux so this may need to be configurable (or the tmux version auto detected somehow). Unfortunately tmux doesn't seem to want to add it as an option for default behaviour - so a new option may be required in neovim.

**Comment by jamessan** [comment]
I'm not sure we need a specific knob for this.  If anything, it probably just needs some documentation.  We already describe the tmux config in the help, so adding something about this new switch and putting a `tmux-clipboard` tag on it is probably enough.

**Comment by smhc** [comment]
We could do. But it'd be a shame to have to dig through the doco when neovims philosophy is to have sensible defaults without lengthy config. Neovim already uses tmux load-buffer when it detects $TMUX or uses win32yank etc - so the intent is there to do the desirable thing automatically. 

IMHO tmux should do it automatically if configured to rather than neovim having to work out when it is applicable, but that doesn't seem like it will change.

**Comment by jamessan** [comment]
There's a reasonable concern around enabling OCS 52 by default.  Pretty much every tool I have seen add support for OCS 52 has required the user to explicitly enable it's usage.

Yes, it would be preferable if a user could configure tmux to use OCS 52 by default, but I don't think it's up to nvim to work around that.

Nvim is still doing a reasonable thing by default by leveraging tmux to allow copy/pasting between different panes of tmux.
