### ISSUE TITLE
Error Executing Lua - Requires Sudo to use Lua Modueles

### ISSUE THREAD

**Issue by VVoruganti** [neovim/neovim#14548]
- `nvim --version`: 0.5.0-dev+1218-g61aefaf29
- Operating system/version: WSL 2 Debian
- Terminal name/version: Bash
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

I recently built this version of neovim from source. with release type and default `sudo make install` location. 

I have the following plugins installed using `vim-plug` with the follow setup

```
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-telescope/telescope.nvim'
```
Problem occurs when trying to run either plugin without sudo access. I'm wondering if it has something to do with which lua it is using. 

Tried unsetting `LUA_PATH` and `LUA_CPATH`, but same issue occurs
![Neovim Lua Error](https://user-images.githubusercontent.com/13438633/118190700-7e386180-b411-11eb-8ae2-e9a684d92dac.jpg)

### Actual behaviour
Gives error 
E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/lsp/log.lua:34: !/.cache/nvim/lsp.log: Permission denied

### Expected behaviour
Should be able to run lua plugins without sudo access.

**Comment by bfredl** [comment]
looks more like you ran a `sudo nvim` (with your user's xdg dirs) by mistake. try `sudo rm .cache/nvim/lsp.log`

**Comment by VVoruganti** [comment]
Oh That was it thank you!!
