### ISSUE TITLE
Flatpak and Sandbox

### ISSUE THREAD

**Issue by deisi** [neovim/neovim#14543]
I try to build a flatpak for neovide on top of the flatpak of neovim. 

https://github.com/deisi/flathub/tree/neovide

and https://github.com/Kethku/neovide/issues/634

I have a somewhat working prototype, but the Issue is, that the sandbox of flatpak is largely killing off features of `neovim`. E.g. after installing the flatpak `io.neovim.nvim` you can't run e.g. `:terminal` or say `!latexmk` as `/usr/bin` and there a like are not accessible from within the flatpak. 

Now, I know that it is somewhat possible to escape the sandbox here, as e.g. [gnome-builder](https://github.com/flathub/org.gnome.Builder) is doing it. From what I uderstood, build tools are in general allowed to escape the sandbox. In gnome builder e.g.I can launch a shell with full host access. Now gnome builder has some man power and knowledge about flatpak that I don't have, so they might be pulling some heavy tricks to make it happen. 

Anyhow, I would really love to fix this, as a) it would make the flatpak neovim package actually useful and b) it would help my neovide package as well.

**Comment by ianchanning** [comment]
I stumbled across this problem with using the Flatpak version of Neovim. It severely reduces Neovim's functionality because the `terminal` is missing key programs. Most notably 'node' can't be found for the `coc.nvim` plugin.

https://vi.stackexchange.com/questions/31300/neovim-terminal-shows-a-different-list-of-programs-available-in-usr-bin/31301#31301

**Comment by rktjmp** [comment]
I think this issue should actually be on https://github.com/flathub/io.neovim.nvim, unsure if that is maintained "officially" or not.

See:

https://docs.flatpak.org/en/latest/sandbox-permissions.html

and

https://github.com/flathub/io.neovim.nvim/blob/b1ba663133b16b0f56584fc1b0acddd916f2018b/io.neovim.nvim.yaml#L12-L20
```
finish-args:
  # Edit anything
  - --filesystem=host
  # Plugin updates
  - --share=network
  # Clipboard access
  - --socket=wayland
  - --socket=fallback-x11
  - --share=ipc
```

Specifically:

`- --filesystem=host` and https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

> As mentioned above the host option does not actually provide complete access to the host filesystem. The main rules are:
> 
> -  These directories are blacklisted: /lib, /lib32, /lib64, /bin, /sbin, /usr, /boot, /root, /tmp, /etc, /app, /run, /proc, /sys, /dev, /var
> -  Exceptions from the blacklist: /run/media
> -  These directories are mounted under /var/run/host: /etc, /usr
> 
> The reason many of the directories are blacklisted is because they already exist in the sandbox such as /usr or are not usable in the sandbox.

Probably have to stick `--filesystem=/usr/bin` in the manifest (though it does mention conflicts) or maybe some kind of symbolic link deal. 

Just guessing, I don't use flatpak.

**Comment by justinmk** [comment]
> I think this issue should actually be on https://github.com/flathub/io.neovim.nvim, 

@jurf where should this issue be raised?

**Comment by jurf** [comment]
There’s good.
