### ISSUE TITLE
Buffer closed after use `gx` in a not-first tab

### ISSUE THREAD

**Issue by QiBaobin** [neovim/neovim#14551]
- `nvim --version`: NVIM v0.5.0-dev+1318-g61aefaf29
- Operating system/version: Darwin maclb158028 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
- Terminal name/version: Wezterm stable 20210502-154244,
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
:tabnew
:help vim-differences | only
/stackov
gx
```

### Actual behaviour
The help buffer is closed and a `No Name` buffer shown
### Expected behaviour
Keep the buffer and stay in old position

**Comment by zeertzjq** [comment]
Seems fixed now.
