### ISSUE TITLE
Newest nightly version is `release` build type.

### ISSUE THREAD

**Issue by frangte** [neovim/neovim#14554]
As title and see this image.

![image](https://user-images.githubusercontent.com/19859575/118299970-a310ff80-b50b-11eb-889d-9bb3f6c80846.png)

Thank for your work.

**Comment by mhinz** [comment]
That is correct: https://github.com/neovim/neovim/blob/7c95697026e76f9ee817cbea5ab11232a2443c15/.github/workflows/release.yml#L85
