### ISSUE TITLE
swapfile UX

### ISSUE THREAD

**Issue by matjon** [neovim/neovim#1455]
Hello,
When I look at the file recovery dialog:

```
E325: ATTENTION
Found a swap file by the name ".file.txt.swp"
          owned by: mateusz   dated: Sat Nov  11 12:00:04 2014
         file name: ~mateusz/file.txt
          modified: no
         user name: mateusz   host name: mat
        process ID: 25904
While opening file "file.txt"
dated: Sat Nov  11 12:00:00 2014
```

it often takes me some time to determine which way to proceed. It is not straightforward at all to determine whether the swap file could be deleted safely: whether it matches the file in question.

In such cases, I often proceed (or should proceed) in the following way:
1. Look at the "modified" line.
2. Compare the datestamps of the swap file and the main file.
3. Even if modified=no, I recover the file, then check if it was modified.
4. I execute :DiffOrig.
5. I close the file.
6. I open the file again by using the history feature of the shell (I press arrow up) to be sure I will open the same file the second time.
7. At the prompt again, I choose "Delete".

All of this procedure is time-consuming, annoying, error-prone and kind of sucks. There were many cases when I wondered afterwards whether I had made a correct choice (eg. if I looked at the "modified" line at all). In two instances I decided to undelete the swap file to check if it didn't contain anything valuable. 

Most importantly, there is no indication whether the content of the swap file (.file.txt.swp) matches the content of the main file (file.txt).

A suggested solution - mockup:
1. .file.txt.swp matches file.txt
   
   ```
   Found a swap file ".file.txt.swp". 
   It matches perfectly "file.txt" so it can be safely deleted. Proceed?
   [Y]es, [n]o, [m]ore info
   ```
   
   ENTER should choose "yes". "More info" should show the same parameters as currently (mtime, PID, user name, hostname, location, etc.). It is hidden here to make both messages more distinctive.
2. .file.txt.swp does not match file.txt
   
   ```
   E325: ATTENTION
   Found a swap file by the name ".file.txt.swp"
             owned by: mateusz   dated: Sat Nov  11 12:00:04 2014
            file name: ~mateusz/file.txt
            user name: mateusz   host name: mat
           process ID: 25904
   While opening file "file.txt"
   dated: Sat Nov  11 12:00:00 2014
   
   Contents of ".file.txt.swp" file do not match file.txt.
   //some form of diffstat here, like:
   added 2111 lines, deleted 112 lines,
   Try to recover from .file.txt.swp?
   
   (R)ecover, (o)pen read-only, (s)how diff, (d)elete file, (q)uit
   ```
   
   (above message should be in red) The "modified" line is ommitted, because it is confusing (shold probably be reworded). After pressing D, diff should be shown with a "are you sure" prompt).
   ENTER should choose "recover".

In every case, ENTER should choose the "recommended" and "safe" way to proceed.

This issue touches the notion of **safety**: a system should make it difficult to delete data or make something similarly irreversible by mistake. Even professionals do make mistakes.

**Comment by amerlyq** [comment]
At the moment ```Recover.vim``` is incompatible with neovim (see [#39](https://github.com/chrisbra/Recover.vim/issues/39)) and seems like will never would (implementation is too specific). 
It would be nice to add at least ```D[i]ff``` dialog, splitting all mentioned recovery-related features and implementing part of them in nearest future.

Also, if someone knows workaround to fix ```Recovery.vim```, it would be nice as well.
Current way of "swap-exists"-message fetching
```
TERM=vt100 LC_ALL=C nvim -u NONE -es -V  '/path/to/file.ext'
```
don't work with neovim at all.

**Comment by wolfv6** [comment]
Big thumbs up for the changes proposed by @matjon and @tpz ![thumbs up](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
I don't use neovim, but file recovery is one of the vim pain points that would make me switch to neovim.

**Comment by wolfv6** [comment]
Big thumbs up for the changes proposed by @matjon and @tpz ![thumbs up](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
I don't use neovim, but file recovery is one of the vim pain points that would make me switch to neovim.

**Comment by justinmk** [comment]
> if someone knows workaround to fix Recovery.vim, it would be nice as well.

@amerlyq This shows the swap dialog:

    LC_ALL=C nvim -es -u NONE -V /path/to/file.ext

And this actually returns the swap dialog as a string:

    :echo system('LC_ALL=C nvim --headless -es -u NONE -V +"qa!" '.shellescape(expand('/path/to/file.ext'))) 

so that's probably enough to make recover.vim work.

**Comment by mqudsi** [comment]
If the swap file matches perfectly to the original, it's pointless to even ask if it's OK to delete it. JFD.
