### ISSUE TITLE
How to disable bundling of neovim-qt in the build? 

### ISSUE THREAD

**Issue by rashil2000** [neovim/neovim#14552]
In the Wiki I can see that I can create a custom `local.mk` Makefile for my local builds. Is there a way to build neovim without bundling the GUI neovim-qt with it? Ideally I'd like to have only nvim.exe and its dependencies in the build\bin directory.

Thanks in advance!

**Comment by janlazo** [comment]
Not at the moment.
Need a variable in https://github.com/neovim/neovim/blob/master/third-party/CMakeLists.txt to skip wintools, wingui.

**Comment by rashil2000** [comment]
This might be a personal opinion, but Windows has had good terminal emulators for a long while (5-6 years, not sure). Even the default cmd.exe terminal supports features such as Neovim mouse mode. And then Microsoft is heavily developing their own new modern Windows Terminal. I'd say the need for _bundling_ neovim-qt is very less nowadays. Of course users can install it separately in any case, just like they would on Linux.

**Comment by dundargoc** [comment]
This is now possible by setting the cmake variable `USE_BUNDLED_NVIMQT` to `OFF`.

**Comment by rashil2000** [comment]
Great news! 

Could you mention it in the build instructions for Windows so that people can find it easily: https://github.com/neovim/neovim/wiki/Building-Neovim#building-on-windows

**Comment by dundargoc** [comment]
Added example: https://github.com/neovim/neovim/wiki/Building-Neovim#building-on-windows

**Comment by rashil2000** [comment]
Thanks again!
