### ISSUE TITLE
lsp.buf.definition: quickfix list inconsistently opens

### ISSUE THREAD

**Issue by samhh** [neovim/neovim#14556]
I'm not sure where this issue belongs between here, neovim, and tsserver. My best guess is here :man_shrugging: 

- `nvim --version`: NVIM v0.5.0-dev+1318-g61aefaf29
- nvim-lsp version(commit hash): 0a921bf
- What language server (If the problem is related to a specific language server): tsserver
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): No, but it was hard to find a repro in tsserver so I wouldn't rule it out.
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? Not yet, see above.
- Is the problem isolated to a particular language server: Maybe, see above.
- Operating system/version: Arch

### How to reproduce the problem from neovim startup

Create a minimal config that loads the nvim-lspconfig plugin and initiates tsserver, for example:

```vim
packadd minpac
call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})

call minpac#add('neovim/nvim-lspconfig')
lua <<EOF
  require'lspconfig'.tsserver.setup {}
EOF

command! PackUpdate call minpac#update()
```

### Actual behaviour

Given the following TypeScript code (anywhere that the language server is active):

```ts
interface A {
  g(): void
}

const f = ({ g }: A) => g()
```

Run `:lua vim.lsp.buf.definition()` when hovering the `g` at the end of the last line. The quickfix list will open.

Virtually any changes to this code, for example changing the type of `A.g` to be `g: () => void`, or no longer destructuring `f`'s argument, will cause the quickfix list to not open.

### Expected behaviour

Consistently either open or don't open the quickfix list. If it's to be opened, make it configurable as this isn't desirable behaviour to me personally.

### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.
</details>

### LSP log

<details>
<summary>Log file</summary>
nizeImports" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        dynamicRegistration = false,        <metatable> = <table 1>      },      completion = {        completionItem = {          commitCharactersSupport = false,          deprecatedSupport = false,          documentationFormat = { "markdown", "plaintext" },          preselectSupport = false,          snippetSupport = false,          <metatable> = <table 1>        },        completionItemKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },          <metatable> = <table 1>        },        contextSupport = false,        dynamicRegistration = false,        <metatable> = <table 1>      },      declaration = {        linkSupport = true,        <metatable> = <table 1>      },      definition = {        linkSupport = true,        <metatable> = <table 1>      },      documentHighlight = {        dynamicRegistration = false,        <metatable> = <table 1>      },      documentSymbol = {        dynamicRegistration = false,        hierarchicalDocumentSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      hover = {        contentFormat = { "markdown", "plaintext" },        dynamicRegistration = false,        <metatable> = <table 1>      },      implementation = {        linkSupport = true,        <metatable> = <table 1>      },      publishDiagnostics = {        relatedInformation = true,        tagSupport = {          valueSet = { 1, 2 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      references = {        dynamicRegistration = false,        <metatable> = <table 1>      },      rename = {        dynamicRegistration = false,        prepareSupport = true,        <metatable> = <table 1>      },      signatureHelp = {        dynamicRegistration = false,        signatureInformation = {          documentationFormat = { "markdown", "plaintext" },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      synchronization = {        didSave = true,        dynamicRegistration = false,        willSave = false,        willSaveWaitUntil = false,        <metatable> = <table 1>      },      typeDefinition = {        linkSupport = true,        <metatable> = <table 1>      },      <metatable> = <table 1>    },    window = {      showDocument = {        support = false,        <metatable> = <table 1>      },      showMessage = {        messageActionItem = {          additionalPropertiesSupport = false,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workDoneProgress = true,      <metatable> = <table 1>    },    workspace = {      applyEdit = true,      configuration = true,      symbol = {        dynamicRegistration = false,        hierarchicalWorkspaceSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workspaceEdit = {        resourceOperations = { "rename", "create", "delete" },        <metatable> = <table 1>      },      workspaceFolders = true,      <metatable> = <table 1>    }  },  clientInfo = {    name = "Neovim",    version = "0.5.0"  },  initializationOptions = vim.empty_dict(),  processId = 462534,  rootPath = "/home/sam/dev/fp-ts-std",  rootUri = "file:///home/sam/dev/fp-ts-std",  trace = "off",  workspaceFolders = { {      name = "/home/sam/dev/fp-ts-std",      uri = "file:///home/sam/dev/fp-ts-std"    } }}
[ DEBUG ] 2021-05-14T16:42:59+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]  "rpc.send.payload"      {  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false,        <metatable> = <1>{          __tostring = <function 1>        }      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },              <metatable> = <table 1>            },            <metatable> = <table 1>          },          dynamicRegistration = false,          <metatable> = <table 1>        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = false,            <metatable> = <table 1>          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },            <metatable> = <table 1>          },          contextSupport = false,          dynamicRegistration = false,          <metatable> = <table 1>        },        declaration = {          linkSupport = true,          <metatable> = <table 1>        },        definition = {          linkSupport = true,          <metatable> = <table 1>        },        documentHighlight = {          dynamicRegistration = false,          <metatable> = <table 1>        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false,          <metatable> = <table 1>        },        implementation = {          linkSupport = true,          <metatable> = <table 1>        },        publishDiagnostics = {          relatedInformation = true,          tagSupport = {            valueSet = { 1, 2 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        references = {          dynamicRegistration = false,          <metatable> = <table 1>        },        rename = {          dynamicRegistration = false,          prepareSupport = true,          <metatable> = <table 1>        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            documentationFormat = { "markdown", "plaintext" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false,          <metatable> = <table 1>        },        typeDefinition = {          linkSupport = true,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      window = {        showDocument = {          support = false,          <metatable> = <table 1>        },        showMessage = {          messageActionItem = {            additionalPropertiesSupport = false,            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workDoneProgress = true,        <metatable> = <table 1>      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workspaceEdit = {          resourceOperations = { "rename", "create", "delete" },          <metatable> = <table 1>        },        workspaceFolders = true,        <metatable> = <table 1>      }    },    clientInfo = {      name = "Neovim",      version = "0.5.0"    },    initializationOptions = vim.empty_dict(),    processId = 462534,    rootPath = "/home/sam/dev/fp-ts-std",    rootUri = "file:///home/sam/dev/fp-ts-std",    trace = "off",    workspaceFolders = { {        name = "/home/sam/dev/fp-ts-std",        uri = "file:///home/sam/dev/fp-ts-std"      } }  }}
[ DEBUG ] 2021-05-14T16:42:59+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:491 ]  "decoded"       {  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      callsProvider = true,      codeActionProvider = true,      completionProvider = {        resolveProvider = true,        triggerCharacters = { ".", '"', "'", "/", "@", "<" }      },      definitionProvider = true,      documentFormattingProvider = true,      documentHighlightProvider = true,      documentRangeFormattingProvider = true,      documentSymbolProvider = true,      executeCommandProvider = {        commands = { "_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile" }      },      foldingRangeProvider = true,      hoverProvider = true,      implementationProvider = true,      referencesProvider = true,      renameProvider = true,      signatureHelpProvider = {        triggerCharacters = { "(", ",", "<" }      },      textDocumentSync = 2,      typeDefinitionProvider = true,      workspaceSymbolProvider = true    }  }}
[ DEBUG ] 2021-05-14T16:42:59+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]  "rpc.send.payload"      {  jsonrpc = "2.0",  method = "initialized",  params = {    [true] = 6  }}
[ DEBUG ] 2021-05-14T16:42:59+0100 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:853 ]      "LSP[tsserver]" "server_capabilities"   {  callsProvider = true,  codeActionProvider = true,  completionProvider = {    resolveProvider = true,    triggerCharacters = { ".", '"', "'", "/", "@", "<" }  },  definitionProvider = true,  documentFormattingProvider = true,  documentHighlightProvider = true,  documentRangeFormattingProvider = true,  documentSymbolProvider = true,  executeCommandProvider = {    commands = { "_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile" }  },  foldingRangeProvider = true,  hoverProvider = true,  implementationProvider = true,  referencesProvider = true,  renameProvider = true,  signatureHelpProvider = {    triggerCharacters = { "(", ",", "<" }  },  textDocumentSync = 2,  typeDefinitionProvider = true,  workspaceSymbolProvider = true}
[ INFO ] 2021-05-14T16:42:59+0100 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:854 ]       "LSP[tsserver]" "initialized"   {  resolved_capabilities = {    call_hierarchy = false,    code_action = true,    code_lens = false,    code_lens_resolve = false,    completion = true,    declaration = false,    document_formatting = true,    document_highlight = true,    document_range_formatting = true,    document_symbol = true,    execute_command = true,    find_references = true,    goto_definition = true,    hover = true,    implementation = true,    rename = true,    signature_help = true,    signature_help_trigger_characters = { "(", ",", "<" },    text_document_did_change = 2,    text_document_open_close = true,    text_document_save = true,    text_document_save_include_text = false,    text_document_will_save = false,    text_document_will_save_wait_until = false,    type_definition = true,    workspace_folder_properties = {      changeNotifications = false,      supported = false    },    workspace_symbol = true  }}
[ DEBUG ] 2021-05-14T16:42:59+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]  "rpc.send.payload"      {  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocument = {      languageId = "typescript",      text = "/**\n * Utility functions to accommodate `fp-ts/IO`.\n *\n * @since 0.7.0\n */\n\nimport * as IO from \"fp-ts/IO\"\n\ntype IO<A> = IO.IO<A>\n\n/**\n * Performs the side effect with the input value and then returns said input\n * value.\n *\n * @example\n * import { tap } from 'fp-ts-std/IO';\n * import * as IO from 'fp-ts/IO';\n * import { flow } from 'fp-ts/function';\n *\n * let x = 0;\n * const mutate = (y: number): IO.IO<void> => () => { x = y }\n *\n * const double = (n: number): number => n * 2;\n * const toString = (n: number): string => String(n);\n *\n * const doubledString: (n: number) => IO.IO<string> =\n *     flow(double, tap(mutate), IO.map(toString));\n *\n * assert.strictEqual(x, 0);\n * assert.strictEqual(doubledString(2)(), '4');\n * assert.strictEqual(x, 4);\n *\n * @since 0.7.0\n */\nexport const tap = <A>(f: (x: A) => IO<void>) => (x: A): IO<A> => {\n  // eslint-disable-next-line functional/no-expression-statement\n  f(x)()\n\n  return IO.of(x)\n}\n\n/**\n * Given a function, returns a new function that always returns the output\n * value of its first invocation.\n *\n * @example\n * import { once } from 'fp-ts-std/IO';\n * import * as IO from 'fp-ts/IO';\n * import { add } from 'fp-ts-std/Number';\n *\n * const f = once(add(5))\n *\n * assert.strictEqual(f(2)(), 7);\n * assert.strictEqual(f(3)(), 7);\n *\n * @since 0.7.0\n */\nexport const once = <A, B>(f: (x: A) => B): ((x: A) => IO<B>) => {\n  const uncalled = Symbol()\n  let val: typeof uncalled | B = uncalled // eslint-disable-line functional/no-let\n\n  return x => {\n    // eslint-disable-next-line functional/no-conditional-statement\n    if (val === uncalled) val = f(x) // eslint-disable-line functional/no-expression-statement\n\n    return IO.of(val)\n  }\n}\n",      uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts",      version = 0    }  }}
[ DEBUG ] 2021-05-14T16:42:59+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:442 ]     "default_handler"       "textDocument/publishDiagnostics"       {  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"  }}
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:491 ]  "decoded"       {  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"  }}
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:679 ]      "notification"  "textDocument/publishDiagnostics"       {  diagnostics = {},  uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"}
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:442 ]     "default_handler"       "textDocument/publishDiagnostics"       {  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"  }}
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:1034 ]     "on_lines bufnr: 1, changedtick: 5, firstline: 5, lastline: 5, new_lastline: 6, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0" { "" }
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]  "rpc.send.payload"      {  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 5          },          start = {            character = 0,            line = 5          }        },        rangeLength = 0,        text = "\n"      } },    textDocument = {      uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts",      version = 5    }  }}
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:491 ]  "decoded"       {  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"  }}
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:679 ]      "notification"  "textDocument/publishDiagnostics"       {  diagnostics = {},  uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"}
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:442 ]     "default_handler"       "textDocument/publishDiagnostics"       {  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"  }}
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:1034 ]     "on_lines bufnr: 1, changedtick: 6, firstline: 5, lastline: 6, new_lastline: 7, old_byte_size: 1, old_utf32_size: 1, old_utf16_size: 1" { "", "" }
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]  "rpc.send.payload"      {  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 6          },          start = {            character = 0,            line = 5          }        },        rangeLength = 1,        text = "\n\n"      } },    textDocument = {      uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts",      version = 6    }  }}
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:491 ]  "decoded"       {  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"  }}
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:679 ]      "notification"  "textDocument/publishDiagnostics"       {  diagnostics = {},  uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"}
[ DEBUG ] 2021-05-14T16:43:01+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:442 ]     "default_handler"       "textDocument/publishDiagnostics"       {  client_id = 1,  params = {    diagnostics = {},    uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"  }}
[ DEBUG ] 2021-05-14T16:43:05+0100 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:1034 ]     "on_lines bufnr: 1, changedtick: 7, firstline: 6, lastline: 7, new_lastline: 12, old_byte_size: 1, old_utf32_size: 1, old_utf16_size: 1"        { "", "interface A {", "  g(): void", "}", "const f = ({ g }: A) => g()", "" }
[ DEBUG ] 2021-05-14T16:43:05+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]  "rpc.send.payload"      {  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 7          },          start = {            character = 0,            line = 6          }        },        rangeLength = 1,        text = "\ninterface A {\n  g(): void\n}\nconst f = ({ g }: A) => g()\n\n"      } },    textDocument = {      uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts",      version = 7    }  }}
[ DEBUG ] 2021-05-14T16:43:06+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:491 ]  "decoded"       {  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = 6133,        message = "'f' is declared but its value is never read.",        range = {          end = {            character = 7,            line = 10          },          start = {            character = 6,            line = 10          }        },        severity = 4,        source = "typescript"      } },    uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"  }}
[ DEBUG ] 2021-05-14T16:43:06+0100 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:679 ]      "notification"  "textDocument/publishDiagnostics"       {  diagnostics = { {      code = 6133,      message = "'f' is declared but its value is never read.",      range = {        end = {          character = 7,          line = 10        },        start = {          character = 6,          line = 10        }      },      severity = 4,      source = "typescript"    } },  uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"}
[ DEBUG ] 2021-05-14T16:43:06+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:442 ]     "default_handler"       "textDocument/publishDiagnostics"       {  client_id = 1,  params = {    diagnostics = { {        code = 6133,        message = "'f' is declared but its value is never read.",        range = {          end = {            character = 7,            line = 10          },          start = {            character = 6,            line = 10          }        },        severity = 4,        source = "typescript"      } },    uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"  }}
[ DEBUG ] 2021-05-14T16:43:11+0100 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:894 ]      "LSP[tsserver]" "client.request"        1       "textDocument/definition"       {  position = {    character = 24,    line = 10  },  textDocument = {    uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"  }}   <function 1>    1
[ DEBUG ] 2021-05-14T16:43:11+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]  "rpc.send.payload"      {  id = 2,  jsonrpc = "2.0",  method = "textDocument/definition",  params = {    position = {      character = 24,      line = 10    },    textDocument = {      uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"    }  }}
[ DEBUG ] 2021-05-14T16:43:11+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:491 ]  "decoded"       {  id = 2,  jsonrpc = "2.0",  result = { {      range = {        end = {          character = 14,          line = 10        },        start = {          character = 13,          line = 10        }      },      uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"    }, {      range = {        end = {          character = 3,          line = 8        },        start = {          character = 2,          line = 8        }      },      uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"    } }}
[ DEBUG ] 2021-05-14T16:43:11+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:442 ]     "default_handler"       "textDocument/definition"       {  bufnr = 1,  client_id = 1,  params = { {      range = {        end = {          character = 14,          line = 10        },        start = {          character = 13,          line = 10        }      },      uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"    }, {      range = {        end = {          character = 3,          line = 8        },        start = {          character = 2,          line = 8        }      },      uri = "file:///home/sam/dev/fp-ts-std/src/IO.ts"    } }}
</details>

**Comment by mjlbach** [comment]
I actually think this is actually tsservers fault, all we are doing is checking if the result (returned by tsserver) is a list, and if the list has more than 1 entry we set the quickfix list rather than showing jumping to the location.

https://github.com/neovim/neovim/blob/cfaf666ac9e1020f75dddb66027e36ad5fed0c86/runtime/lua/vim/lsp/handlers.lua#L292-L313

**Comment by mjlbach** [comment]
@samhh I checked the tsserver log, we're correctly passing multiple definition target locations to the quickfix list when they occur, the issue is modifying the file as you suggests results in only a single definition location returned when we invoke the error. If you disagree with this behavior, I would suggest filing a bug upstream with tsserver as there is nothing we can do on the client end.

**Comment by samhh** [comment]
Let's say this is fixed upstream so that multiple locations are always returned, then it's always going to open the quickfix list, right? That's behaviour I don't personally want - is there any way to disable it? I'd think that's within the remit of the client.

**Comment by mjlbach** [comment]
How do we decide which position to jump to then if multiple possible locations are returned? If you really want to just choose the first search result, you can override the location handler I pointed you towards to only choose the first result (I don't think we'd make this a built-in option though).

**Comment by mjlbach** [comment]
Actually https://github.com/neovim/neovim/pull/13977 will do what you want, so you can follow that PR

**Comment by samhh** [comment]
Awesome, thanks for the link :slightly_smiling_face:

**Comment by samhh** [comment]
Is there a new issue or PR to track for the above feature request?

**Comment by mjlbach** [comment]
The tracking issue in tsserver is here: https://github.com/microsoft/TypeScript/issues/37816
see also: https://github.com/typescript-language-server/typescript-language-server/issues/216

If you want to override the location handler in neovim to work around this (to always jump to the first definition if there is more than one in the list), but don't know how, I can provide a snippet later. That is the expected entrypoint to user specific customization.

**Comment by samhh** [comment]
Thanks for the links!

This seems to be working per a workaround in one of those threads, let me know if there's anything obviously wrong or suboptimal with it: https://github.com/samhh/dotfiles/commit/f45359a55feb3df5c8d00dc0ed04dc56622bb868

**Comment by mjlbach** [comment]
Basically what I would do :) 

You can directly pass the handler override to setup{} in lspconfig rather than overriding it in on _attach (IMO, cleaner)
