### ISSUE TITLE
LSP Diagnostic messages do not wrap or respect textwidth

### ISSUE THREAD

**Issue by nosed1ve** [neovim/neovim#14568]
- `nvim --version`: 0.5.0
- Operating system/version: WSL 2 
- Terminal name/version: Windows Terminal 1.7
- `$TERM` : xterm-256color

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)" 

```

### Actual behaviour

Virtual text from LSP diagnostics does not wrap as per window size or textwidth.

Here are a couple of examples with rust-analyzer's diagnostic messages, the first SS is not in fullscreen, second one is.

![image](https://user-images.githubusercontent.com/67145097/118436110-d0bd9a80-b6fd-11eb-8ade-33d8109851d0.png)
![image](https://user-images.githubusercontent.com/67145097/118436220-0d899180-b6fe-11eb-895b-1f2d13776098.png)

### Expected behaviour

Virtual text from LSP diagnostics should wrap based on window size so it can be read fully.

**Comment by mhinz** [comment]
Virtual text should merely provide a quick hint. If you wanted to see everything, you should use `vim.lsp.diagnostic.show_line_diagnostics()` instead.

The current approach is simple and works. If you wanted to wrap, you would run in tons of problems like what about two subsequent lines having long diagnostics? What about wrapping the virtual text, but the next line fills out all of `&tw` already?

As long as we can't add full virtual lines (lines between actual lines), I'd prefer the current simple approach.

**Comment by mjlbach** [comment]
Also full virtual lines would get very messy with long diagnostics... I agree with mhinz that the purpose of the virtual text is just to give you a hint where the diagnostics are that is more actionable than the underline.

**Comment by nosed1ve** [comment]
Hmm, I see what you mean to say, I did think of the implications of wrapping virt. text, but I guess using `vim.lsp.diagnostic.show_line_diagnostics()` makes more sense. I'll close this, thanks for the insight.

**Comment by Notarin** [comment]
Good morning,
I was wondering if this issue could be reopened, the lsp_lines.nvim plugin makes use of vertical space to display the errors in a way I personally believe works better for me than showing diagnostics in the console or context menus, having the ability to internally toggle or set a linewrapping policy would benefit the plugin users.
Thank you.

Issue: https://todo.sr.ht/~whynothugo/lsp_lines.nvim/46
