### ISSUE TITLE
lsp: jumplist regression due to "make tagstack smarter motion wise"

### ISSUE THREAD

**Issue by SanchayanMaity** [neovim/neovim#14571]
- `nvim --version`: Latest master e0a01bdf7ff
- language server name/version: rust-analyzer ab528e85f 2021-05-14 dev
- Operating system/version: Arch Linux

### Actual behaviour

When using `vim.lsp.buf.definition()`, jumping to a definition in the same buffer and jumping back does not jump back to the exact row and column position before the jump. It works if the definition is in another buffer/file but not for the same buffer.

### Expected behaviour

When using `vim.lsp.buf.definition()`, jumping to a definition in the same buffer and jumping back jumps back to the exact row and column position before the jump.

Commit 8885ea7f24 lsp: make tagstack smarted motion wise introduced a regression with jump to location. There was an attempt to fix this with 993ca90c9 but that only jumps to first non blank character of the line. Considering the mark use in that fix, it would be expected, but, it does not fully bring back the previous behavior.

The behavior can be seen with rust-analyzer and pyls. Reverting the above commits restores the original correct behavior.

**Comment by mjlbach** [comment]
cc: @fsouza @gbrlsnchs

**Comment by fsouza** [comment]
Do you have some sample code/config where you can reproduce it? I've been using this for hours pretty much every day and can't repro :((

I don't use pyls nor rust-analyzer, but I assume that wouldn't make any difference.

**Comment by SanchayanMaity** [comment]
I can also reproduce this with a minimal config `nvim -u /tmp/minimal_init.lua`. In `minimal_init.lua`, I just changed to `pyls`.

```
nvim --version
NVIM v0.5.0-dev+1326-ge0a01bdf7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/core/GitSources/neovim/build/config -I/home/core/GitSources/neovim/src -I/home/core/GitSources/neovim/.deps/usr/include -I/usr/include -I/home/core/GitSources/neovim/build/src/nvim/auto -I/home/core/GitSources/neovim/build/include

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by gbrlsnchs** [comment]
My two cents on this issue: 

Maybe it was a bad take trying to fix phantom jumps for the tagstack like that. At the time, I naively thought it was a good idea. As my first contribution, I didn't even know the issue was about phantom jumps and that it had already been fixed for the jumplist.

Right now it might has brought more issues than benefits, so I think we should revert those commits (so, bring back phantom jumps for the tagstack) and in the meantime we should fix it the same way it was done for the jumplist, at the root cause.

What do you think?

**Comment by mhinz** [comment]
Please see if the above PR works for you.

**Comment by SanchayanMaity** [comment]
@mhinz I already carry those reverts in my local branch. Those would work.
