### ISSUE TITLE
Feature: colorschemes per buffer.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#1457]
It'd be interesting to have a different color scheme per buffer or window. I find that one colorscheme is often not the enough to use for all file types. Sometimes I want to change to a different one for a different language. Plus, I like colors and variety. :D I haven't seen this in any editor before.

Currently, `:colorscheme` sets the color globally for all of neovim. I also know of `au BufEnter` commands to switch colorschemes based on file type, but the colorscheme will still change for the entirety of neovim, but just the specific window/buffer.

**Comment by justinmk** [comment]
As a core feature, this is out of scope.

Nvim API has `nvim_buf_add_highlight()` for buffer-local highlighting. Not the same thing as per-buffer colorscheme but it enables plugins to be built for that purpose. Also one can already achieve a per-buffer "colorscheme" by creating new syntax groups, assigning different highlights to them, and assigning the buffer to some new filetype for that purpose.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/6597 allows per-window colorschemes.

**Comment by chadwtaylor** [comment]
I am with the author of this feature request to have different colorshemes per buffer such as `:term`. It is rather hard to distinguish between buffers (editor vs :term). For example, I'm using the `gruvbox` colorscheme and then I would love for the `:term` buffer to have a `black` background. It would be convenient visually. Those little things do make a huge difference for people like me and the author of this feature request. 

+1

**Comment by dm1try** [comment]
> to have different colorshemes per buffer such as `:term`. It is rather hard to distinguish between buffers (editor vs :term). For example, I'm using the `gruvbox` colorscheme and then I would love for the `:term` buffer to have a `black` background.

@chadwtaylor as mentioned above, this is already achievable.
```Viml
hi BlackBg guibg=black
au TermOpen * :set winhighlight=Normal:BlackBg
```
It depends on workflow, but if a terminal window is reused for other buffers 
```Viml
au BufHidden term://* :set winhighlight=Normal:Normal
```
can be helpful either.
