### ISSUE TITLE
[Bug Report] FocusGained autocmd is triggered on startup within tmux

### ISSUE THREAD

**Issue by laggardkernel** [neovim/neovim#14572]
To put it simple, `FocusGained` `autocmd` is triggered on startup in `neovim` within `tmux`. Or say it in another way, the `FocusGained` with neovim+tmux behaves like `VimEnter`.

It doesn't happen with `tmux + vim` but only `tmux + neovim`.

It doesn't happen with `neovim` without `tmux` but only `tmux + neovim`.

I mean the `FocusGained` should not be triggered on startup, but only when user switching back to neovim.

I only tested this on my notebook. Need some help to test whether it could be reproduced on other environments. 

### Tested Environments

I reproduced the bug successfully with different env combinations, I'll list them all.

- `nvim --version`:
  - v0.4.4
  - v0.5.0-dev+1326-ge0a01bdf7
- Operating system/version: macOS 10.14.6
- Terminal name/version:
  - kitty 0.20.3, TERM=xterm-kitty
  - iTerm 3.4.6, TERM=xterm256color
  - tmux 3.2, TERM=screen, TERM=tmux-256color

### Steps to reproduce

To leave alone impacts from other factors, create the following minimal conf for `tmux` and `neovim`.

Create a new tmp dir and create following conf files,

`tmux.conf`

```conf
set -g focus-events on
```

`focus.vim`

```vim
set nocompatible

function FocusGainedTest()
  echom "FocusGainedTest"
endfunction

augroup FocusGainedTest
  autocmd!
  autocmd FocusGained * call FocusGainedTest()
augroup END
```

Steps

- Start a tmux sever with `tmux -f ./tmux.conf -S tmux.socket`
- Once enter the tmux pane, start neovim with `nvim -u ./focus.vim`
- Then you'll find the messages `FocusGainedTest`

While, this doesn't happen with `vim -u ./focus.vim`, or `nvim` outside `tmux`.

**Comment by mhinz** [comment]
I can reproduce it. The weird thing is that it doesn't happen when you explicitly enable focus reporting before starting nvim:

```
$ printf "\e[?1004h"
$ nvim
```

**Comment by justinmk** [comment]
Confirmed on 338b9032194a . It might be time to revert this hack (without regressing #7649): https://github.com/neovim/neovim/blob/338b9032194a4bc4c98439eb00f65a8ec86609f2/src/nvim/tui/tui.c#L503

But the patch below doesn't fix the issue... 

For years I've noticed that "enabling focus events" in tmux also _triggers_ a focus event. Either we're doing something wrong, or Vim has a workaround?

```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 720abb1cec2c..be3ed90d968e 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -488,6 +488,7 @@ static void tui_main(UIBridgeData *bridge, UI *ui)
 #endif
   tinput_init(&data->input, &tui_loop);
   tui_terminal_start(ui);
+  tui_terminal_after_startup(ui);
 
   // Allow main thread to continue, we are ready to handle UI callbacks.
   CONTINUE(bridge);
@@ -499,9 +500,6 @@ static void tui_main(UIBridgeData *bridge, UI *ui)
   for (size_t ms = 0; ms < 100 && !tui_is_stopped(ui);) {
     ms += (loop_poll_events(&tui_loop, 20) ? 20 : 1);
   }
-  if (!tui_is_stopped(ui)) {
-    tui_terminal_after_startup(ui);
-  }
   // "Passive" (I/O-driven) loop: TUI thread "main loop".
   while (!tui_is_stopped(ui)) {
     loop_poll_events(&tui_loop, -1);  // tui_loop.events is never processed
```

**Comment by networkhermit** [comment]
This issue still exists on nvim 0.9.1 and tmux 3.3a (need to set `set -g focus-events on`), I tried alacritty/terminal.app on macos and alacritty/windows terminal on windows 11, all of them can be used to reproduce this bug (I think linux desktop is the same).

```bash
nvim -i NONE -u NONE -c 'autocmd FocusGained * set number'
```

One side effect of this issue is that if users set options in the FocusGained hook like above, the greeting text of neovim disappears immediately on startup.

```bash
vim -i NONE -u NONE -c 'autocmd FocusGained * set number'
```

Vim don't have this issue.

**Comment by zeertzjq** [comment]
There is now a tmux 3.4 release.
