### ISSUE TITLE
Python 3.10 version check is failed in python privider

### ISSUE THREAD

**Issue by Shougo** [neovim/neovim#14586]
- `nvim --version`: NVIM v0.5.0-dev+4178-gd16e9d8ed
- Operating system/version: Manjaro Linux
- Terminal name/version:
- `$TERM`:
- Python version: 3.10

### Actual behaviour

https://github.com/neovim/neovim/blob/52ca7f1a26e4da95f3b3b00670252cfdf788a011/runtime/autoload/health/provider.vim#L426

`str2float('3.10') < 3.3` is failed.
3.10 is smaller than 3.3.

### Expected behaviour

The check should be passed or the check should be removed.

**Comment by codewiz** [comment]
Please reopen. There's another version check on line 99 of runtime/autoload/provider/pythonx.vim which causes the check to fail for Python 3.10:

```
## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          /usr/bin/python3 is Python 3.10 and cannot provide Python >= 3.3.
          /usr/bin/python3.10 is Python 3.10 and cannot provide Python >= 3.3.
          python3.9 not found in search path or not executable.
          python3.8 not found in search path or not executable.
          python3.7 not found in search path or not executable.
          python3.6 not found in search path or not executable.
          /usr/bin/python is Python 3.10 and cannot provide Python >= 3.3.
  - INFO: Executable: Not found
```

**Comment by gpanders** [comment]
Relevant code: 

https://github.com/neovim/neovim/blob/643cb8a6ecc9c78580ccaf1821b52f836b7b7ef4/runtime/autoload/provider/pythonx.vim#L92-L103

We should follow @janlazo's [advice](https://github.com/neovim/neovim/pull/14590#pullrequestreview-663474244):

>  If we need to recommend a python version, don't use str2float and use a custom version check like s:is_minimum_version in node.vim provider.
