### ISSUE TITLE
mpack files under docs

### ISSUE THREAD

**Issue by folke** [neovim/neovim#14588]
I recently discovered the generation of the messagepack files under the `docs` directory.

Based off those files, I created [some code](https://github.com/folke/lua-dev.nvim) to convert them to an [EmmyLua](https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Annotations) annotations library for the nvim lua api.

By adding them as a workspace library to the sumneko lsp server, you then get completion, signature help and hover docs for the nvim lua api.

A couple of questions / feature requests:
* ~~the mpack files are currently not part of the distributions. Would be great if they would be, so they could be read at runtime. (right now I generate them separately and then include them in the plugin)~~
  - no longer needed for my usage
* ~~is something similar possible for the vim functions? `vim.fn`?~~
  - for now I use the data from `vim-lsp` which is sufficient for my use-case
* the current LUA runtime includes some LUA annotations already, like `@param` and `@return`, but the types are missing. Would you be willing to accept a PR that adds proper types for these methods? (Like `vim.treesitter.get_parser()` returns a `vim.treesitter.LanguageTree`. With those annotations, then users get completion on the parser as well)

**Comment by glacambre** [comment]
>the mpack files are currently not part of the distributions. Would be great if they would be, so they could be read at runtime.

Wouldn't it be better to just call `nvim_get_api_info()`? Or is this completely unrelated to what you're trying to do?

**Comment by folke** [comment]
@glacambre `nvim_get_api_info` doesn't include the docs, but it does contain all the other info.
Would be really cool of course to have the docs part of that API call. (even better than shipping the mpack files)

**Comment by smolck** [comment]
> Would be really cool of course to have the docs part of that API call. (even better than shipping the mpack files)

I believe https://github.com/neovim/neovim/pull/12040 would do exactly what you want here; I’ve actually been meaning to come back to that and finish it, so this might be the motivation for me to do so soon ;)

**Comment by folke** [comment]
@smolck exactly what I had in mind! 🙂
