### ISSUE TITLE
More vim internal functionality exposed as Lua apis

### ISSUE THREAD

**Issue by amirrezaask** [neovim/neovim#14599]
I was fiddling with my configuration and refactoring it and in the process added more functionality to vim object so I can have better lua apis for configuring my neovim.

```lua
local o_vim_highlight = vim.highlight
vim.highlight = setmetatable({}, {
  __index = o_vim_highlight,
  __call = function(_, ...)
    nvim_highlight(...)
  end
})
vim.autocmd = nvim_autocmd
vim.augroup = nvim_augroup
vim.map = nvim_map
vim.command = setmetatable({}, {
  __call = function(_, ...) nvim_command(...) end,
  __index = function(_, name)
    return setmetatable({}, {
      __call = function(_, ...)
        local args = {...}
        local cmd = {name}
        for _, a in ipairs(args) do
          table.insert(cmd, a)
        end
        vim.cmd(table.concat(cmd, ' '))
      end
    })
  end
})
vim.c = vim.command

-- vim.highlight now when called defines a new highlight.
-- vim.command on index return a callable table that calls that command and on call defines new command
-- vim.autocmd defines autocmd ( supports lua functions beside vimscript )
-- vim.map map keys but with lua function support
-- vim.command.colorscheme('gruvbox')
-- does
-- :colorscheme gruvbox
```

I was thinking if we can add these ( not the exact code just the idea ) in neovim core itself.
of course all of above or at least vim.command and autocmd should be handled in C code but until then maybe we can just add these as temporary solutions.
[link to actual code in my dotfiles](https://github.com/amirrezaask/dotfiles/blob/master/nvim/lua/nvim.lua)

**Comment by tjdevries** [comment]
We have WIP PRs for many of these features.

In general, I want to make sure we take the time to properly implement the features in C / Lua / wherever first before we try and get some code out just to make it slightly easier than it is right now.

For example, in many of the autocmd wrappers I have seen for Lua code, the lua references are not dropped when the autocmd would normally be cleared, which can lead to memory leaks as the references are held around without anyway to clean them. It's true we could spend a lot of time implementing a Lua wrapper around this that would try and make sure they get cleared correctly, but I think the better way would be to be forward thinking in how we implement these features and not just implement light shims around `vim.cmd` or similar.

I'm always happy to see things exposed via Lua though and would welcome PRs to do so :)

**Comment by amirrezaask** [comment]
For sure the best way is to handle references to lua functions in C code instead of some hacks using tables in lua itself, but these are just temporary solution to just test it out and get feedback from users for the API and usage. Since these are really simple it's easy to just add them and ask users for feedback and in the meanwhile complete the PRs for C code, this way we have better understanding of what users want
