### ISSUE TITLE
I can't get how vim.wo works

### ISSUE THREAD

**Issue by kuator** [neovim/neovim#14595]
- `nvim --version`: NVIM v0.5.0-dev+1327-gdc18c1e3e
- Operating system/version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:Linuxmint
Description:   Linux Mint 20
Release:       20
Codename:      ulyana
```
- Terminal name/version: 
```
$ konsole --version             
qt5ct: using qt5ct plugin
konsole 19.12.3
```
- `$TERM`:
```
$ echo $TERM                   
xterm-256color
```

I have a problem understanding `vim.wo` behaviour. I thought it was supposed to be identical to `setlocal <some-window-local-option>`. For some reason, setting `vim.wo` updates the global option as well.

Steps to reproduce:
```
$ cd /tmp
$ echo 'first dummy text' > /tmp/first.txt && echo 'second dummy text' > /tmp/second.txt
$ echo 'setlocal number' > /tmp/init.vim && echo 'vim.wo.number=true' > /tmp/init.lua
$ nvim --clean -u /tmp/init.vim /tmp/first.txt
```
Now inside neovim first.txt buffer
`:setlocal number?` returns `number`
`:setglobal number?` returns `nonumber`
`:vsp /tmp/second.txt` to open second file in a split window 
`:setlocal number?` returns `nonumber`
`:setglobal number?` returns `nonumber`

![image](https://user-images.githubusercontent.com/25168308/118956814-c3b0dd80-b981-11eb-9041-4ae28e90ff01.png)

Now the init.lua behaviour
$ nvim --clean -u /tmp/init.lua /tmp/first.txt
Now inside neovim first.txt buffer
`:setlocal number?` returns `number`
`:setglobal number?` returns `number`
`:vsp /tmp/second.txt` to open second file in a split window 
`:setlocal number?` returns `number`
`:setglobal number?` returns `number`

![image](https://user-images.githubusercontent.com/25168308/118957192-1f7b6680-b982-11eb-840c-855451eb0381.png)

**Comment by bfredl** [comment]
the "global" value for a (non-global-local) window option is set for the window. when the window is split the value, the value is copied.

**Comment by kuator** [comment]
Does this mean `vim.wo` also udpates global option?

**Comment by bfredl** [comment]
Yes, the window specific value _is_ the global value. This is just how things have been decided to work.
