### ISSUE TITLE
Two indents inserted when pressing <CR> after a bracket/parenthesis/square bracket

### ISSUE THREAD

**Issue by minhduc0711** [neovim/neovim#14606]
- `nvim --version`: NVIM v0.5.0-dev+1330-gd16e9d8ed
- Operating system/version: Linux 5.12.4-arch1-2 x86_64 GNU/Linux
- Terminal name/version: kitty 0.20.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`
1. Open a `.py` file
2. Type this and press enter at the cursor (the `|` indicates the cursor)
```
d = {|
```

### Actual behaviour
```
d = {
        |
```
Note: `shiftwidth=4`

### Expected behaviour
```
d = {
	|
```
i.e only one indent inserted.

**Comment by glacambre** [comment]
Indentation is controlled by `indentexpr` (see `:help indentexpr` for more information), which calls the [GetPythonIndent](https://github.com/neovim/neovim/blob/75992f2ad9189a5f39b3e2ae7962c68d3af815a4/runtime/indent/python.vim#L36) function. GetPythonIndent is defined in the runtime files, which aren't maintained by Neovim (they are instead fetched directly from Vim's repository).

So what you should do here is report the problem you're experiencing to the [maintainer of the python runtime file](https://github.com/neovim/neovim/blob/75992f2ad9189a5f39b3e2ae7962c68d3af815a4/runtime/indent/python.vim#L4) and see if they'd be willing to see the behavior change :).

**Comment by minhduc0711** [comment]
Thanks for the pointer!
