### ISSUE TITLE
range highlight doesn't work in WSL ubuntu-18.04

### ISSUE THREAD

**Issue by cyt-codemaker** [neovim/neovim#14612]
- `nvim --version`: v0.4.0
- Operating system/version: windows's WSL ubuntu-18.04
- Issue: I select some areas in visual mode, then I press colon :  because I want to do a partial replacement. When I input pattern, nvim don't highlight the result.  
```
:'<,'>s/hello
```
I try to search and highlight work
```
/hello
```
I try to substitute and it also doesn't work
```
:s/hello
```
I try to echo, the hlsearch and incsearch are turned on.
```
:set incsearch?
   incsearch
:set hlsearch?
   hlsearch
```

**Comment by matveyt** [comment]
Not supported in 0.4. Must update to 0.5-prerelease.

**Comment by cyt-codemaker** [comment]
> Not supported in 0.4. Must update to 0.5-prerelease.

Ok, thank you very much.
