### ISSUE TITLE
Quickfix buffer cannot be reloaded after switching away

### ISSUE THREAD

**Issue by kocakosm** [neovim/neovim#14610]
- `nvim --version`:
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-eK2ojg/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-eK2ojg/neovim-0.4.4/build/config -I/build/neovim-eK2ojg/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-eK2ojg/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-eK2ojg/neovim-0.4.4/build/include
Compilé par team+vim@tracker.debian.org
Features: +acl +iconv +tui
See ":help feature-compile"
fichier vimrc système : "$VIM/sysinit.vim"
$VIM par défaut : "/usr/share/nvim"
- Operating system/version: Debian 11 "Bullseye" / Linux 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux
- Terminal name/version: GNOME Terminal 3.38.3
- `$TERM`: xterm-256color

[X] `vim -u DEFAULTS` (version: 8.2-2434) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:copen
:bnext
:b2
```

### Actual behaviour
E86: Buffer 2 does not exist

### Expected behaviour
The quickfix buffer is displayed back.

**Comment by justinmk** [comment]
confirmed in a161559a006b.

Looks like we have `bufhidden=wipe` in the quickfix buffer whereas vim 8.2.2029 has `bufhidden=hide`. Easy fix, possibly a missing vim patch.
