### ISSUE TITLE
`ts` not recognized for syntax highlights in the fancy_floating_markdown popup

### ISSUE THREAD

**Issue by David-Else** [neovim/neovim#14616]
- `nvim --version`: v0.5.0-dev+1345-g6dd04ed5f
- Operating system/version: Centos 8 Linux
- Terminal name/version: Gnome Terminal
- `$TERM`: xterm-256color

When using the LSP hover typescript code blocks are not syntax highlighted when ` ```ts` is used, but only when  ` ```typescript` is. This means that any language server using ` ```ts` fails to render any syntax highlighting. `ts` is the most commonly used.

In my `init.vim` I have:
```
let g:markdown_fenced_languages = [ 'typescript', 'ts=typescript' ]
```
Which works fine for Markdown files using ` ```ts`:

![Screenshot from 2021-05-22 14-52-19](https://user-images.githubusercontent.com/12832280/119228935-56ca4e80-bb0d-11eb-8578-e0a2f8b43799.png)

But in the LSP hover for Deno that uses ` ```ts` code blocks I get no highlighting:
![Screenshot from 2021-05-22 08-44-30](https://user-images.githubusercontent.com/12832280/119228659-ebcc4800-bb0b-11eb-84b7-602b44951b8e.png)

**Comment by folke** [comment]
Working on a PR right now, to support `g:markdown_fenced_languages` in `fancy_floating_markdown`.
We might provide a default list as well.

**Comment by folke** [comment]
PR added :)
