### ISSUE TITLE
Can't set colorcolumn variable from Lua

### ISSUE THREAD

**Issue by LandonSchropp** [neovim/neovim#14626]
- `nvim --version`: v0.5.0-dev+f8173df
- Operating system/version: macOS 11.2.3
- Terminal name/version: iTerm2 3.4.6
- `$TERM`: tmux-256color-italic (custom)

### Steps to reproduce using `nvim -u NORC`

Apologies in advance if I'm doing something dumb here.

```
nvim -u NORC
:call luaeval('vim.api.nvim_set_option("colorcolumn", "+1")')
:set colorcolumn
```

### Actual behaviour

The console prints out `colorcolumn=`

### Expected behaviour

The console should print out `  colorcolumn=+1`. Could this possibly be an issue with Lua/Vimscript `nvim_set_option` API? Or am I using it wrong?

**Comment by clason** [comment]
Probably related to: https://github.com/neovim/neovim/issues/14595  ?

**Comment by LandonSchropp** [comment]
Ah, I didn't realize there were different scopes for options. Hopefully, #13479 gets merged soon.
