### ISSUE TITLE
`vim.lsp.diagnostic.show_line_diagnostics` with `set foldmethod=indent`

### ISSUE THREAD

**Issue by alexisquintero** [neovim/neovim#14627]
### Actual behaviour
When using nvim lsp and having `set foldmethod=indent` the `vim.lsp.diagnostic.show_line_diagnostics` window has the errors folded, and since it seems it can't be focused (https://gitter.im/neovim/neovim?at=60a947e243fc4a24c5bcc372) the errors are unreadable.

### Expected behaviour
Being able to focus the `vim.lsp.diagnostic.show_line_diagnostics` window, possibly in a similar way as the `vim.lsp.buf.hover` window.

**Comment by folke** [comment]
we probably always should disable folding in lsp floating windows (`open_floating_preview` & `fancy_floating_markdown`)?

```lua
  api.nvim_buf_set_option(floating_bufnr, 'modifiable', false)
```

**Comment by alexisquintero** [comment]
I think that would be ok as long as it can be scrolled (without being focused), otherwise some of the error would be lost.

**Comment by folke** [comment]
It would make sense to make that window also focusable like signature help and hover, by doinb the shortcut twice
