### ISSUE TITLE
pasting into nvim terminal is ignoring newlines

### ISSUE THREAD

**Issue by harumiya-cs** [neovim/neovim#14621]
- `nvim --version`: v0.4.4
- Operating system/version: windows
- Terminal name/version: git bash version 4.4.23(1)-release
- `$TERM`: i dont know what i should write here, if someone know please let me know so i can edit this

so i installed nvim today, and here is my init.vim file: https://pastebin.com/nRyCPTqk
and say i have this c++ code (which doesnt really matter): https://pastebin.com/18rSSvMA
and this input:
```
2
4
1 2 1 1
4
1 2 3 4
```

### Actual behaviour
when i press `f5` to compile the file im working on and open `a.exe` file, and paste the input above, this is how its being pasted:
`241 2 1 141 2 3 4`

### Expected behaviour
but it is supposed to be pasted as this:

```
2
4
1 2 1 1
4
1 2 3 4
```

im using this commmand to open a new terminal with nvim 
```
augroup compileandrun
    autocmd!
    autocmd filetype python nnoremap <f5> :w <bar> :!python % <cr>
    autocmd filetype cpp nnoremap <f5> :w <bar> !g++ -std=c++17 % <cr> :vnew <bar> :te "a.exe" <cr><cr>
    autocmd filetype cpp nnoremap <f6> :vnew <bar> :te "a.exe" <cr>
augroup END 
```
and i also have this in init.vim file: `set shell=cmd.exe` because nvim is showing this when i press `f5` if i dont have that: `/usr/bin/bash: /s: No such file or directory`
how can i fix this.

i also attached an image of input

![Screenshot (659)](https://user-images.githubusercontent.com/64304214/119265424-1c8da980-bc00-11eb-8085-b7d4f3e80b98.png)

**Comment by ekiim** [comment]
Could this be a windows issue related to the line termination characters?
I suggest piping your output through a program like `dos2unix` to check if that way it respects the line termination character, my guess is that `nvim` doesn't deal well rendering _stuff_ out that outputs text in `dos` way. 

Could  you do a `cat` command in something like the `git bash` terminal, and see how it renders that output?

**Comment by Kreijstal** [comment]
is there a workaround for paste behaviour?

**Comment by joseluisvr93** [comment]
I have the same problem. I tried
:term
:call jobsend(b:terminal_job_id, "1\n2\n3")
 => PS C:\Windows\> 123
:call jobsend(b:terminal_job_id, "1\r2\r3")
 => PS C:\Windows\> 1
    1
    PS C:\Windows\> 2
    2
    PS C:\Windows\> 3
The cause of this problem seems to be a line feed code.

**Comment by zeertzjq** [comment]
Different shells in Windows may accept different line termination characters (I inferred this from <https://github.com/akinsho/toggleterm.nvim/commit/f9845199f1d647890ca47f6185f7ac935991b442>), so this problem may be complicated.
