### ISSUE TITLE
clipboard: error: 1 with another user account

### ISSUE THREAD

**Issue by rickalex21** [neovim/neovim#14633]
- `nvim --version`:NVIM v0.5.0-dev+0a653f7ab
- Operating system/version:Mac OS Big sur Version 11.3.1 (20E241)
- Terminal name/version: Iterm2
- `$TERM`:xterm-256color

NVIM v0.5.0-dev+0a653f7ab
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210524-44504-gd2ihl/build/config -I/tmp/neovim-20210524-44504-gd2ihl/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210524-44504-gd2ihl/build/src/nvim/auto -I/tmp/neovim-20210524-44504-gd2ihl/build/include
Compiled by ritchie@mac.attlocal.net

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-0a653f7_2/share/nvim"

### Steps to reproduce using `nvim -u NORC`

Log into another accont with ```su - user``` then enter the command ```:reg```. You will get the following:

```vim
clipboard: error: 1
```

### Actual behavior

I think this has to do with the permissions? Obviously, you wouldn't want access to someone elses clipboard but
is there a work around for this? This means I can't use the clipboard, I have to log out of my session and
start over instead of just doing ```su - someAccount```.

### Expected behavior

Allow me to use the clipboard with other accounts. Even using ```set clipboard=unnamed``` does nothing.

**Comment by ekiim** [comment]
Probably this is due to the corresponding _configuration_ for your clipboard (inherited from your particular user session with X or whatever window system),  is _left_ behind by doing a `su` because you enter a _new_ session with another user, if you can _reproduce_ that with `su - yourUser`, and it fails too, I guess that that is an around the line I mention and not `neovim` itself.

**Comment by rickalex21** [comment]
@ekiim Yea you're right. I tried it on my linux machine from the terminal and it does not work.
This is more of a permissions error rather than neovim related. 

Thanks.
