### ISSUE TITLE
typescript-language-server error timeout

### ISSUE THREAD

**Issue by osenvosem** [neovim/neovim#14638]
- `nvim --version`: NVIM v0.5.0-dev+a282a177d
- language server name/version: typescript-language-server 0.5.1
- Operating system/version: MacOS 11.4

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyright: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: tsserver: configuration checked.
</details>

<details>
<summary>lsp.log</summary>

[ START ] 2021-05-25T23:52:54+0300 ] LSP logging initiated
[ ERROR ] 2021-05-25T23:53:59+0300 ] ...im/HEAD-a282a17_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"typescript-language-server"	"stderr"	'/Users/srg/.fnm/node-versions/v15.10.0/installation/lib/node_modules/typescript-language-server/lib/utils.js:25\n            this.reject(new Error(this.operation + " timeout"));\n                        ^\n\nError: compilerOptionsForInferredProjects timeout\n    at Timeout.<anonymous> (/Users/srg/.fnm/node-versions/v15.10.0/installation/lib/node_modules/typescript-language-server/lib/utils.js:25:25)\n    at listOnTimeout (node:internal/timers:557:17)\n    at processTimers (node:internal/timers:500:7)\n'
[ START ] 2021-05-25T23:57:23+0300 ] LSP logging initiated
[ ERROR ] 2021-05-25T23:58:18+0300 ] ...im/HEAD-a282a17_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"typescript-language-server"	"stderr"	'/Users/srg/.fnm/node-versions/v15.10.0/installation/lib/node_modules/typescript-language-server/lib/utils.js:25\n            this.reject(new Error(this.operation + " timeout"));\n                        ^\n\nError: compilerOptionsForInferredProjects timeout\n    at Timeout.<anonymous> (/Users/srg/.fnm/node-versions/v15.10.0/installation/lib/node_modules/typescript-language-server/lib/utils.js:25:25)\n    at listOnTimeout (node:internal/timers:557:17)\n    at processTimers (node:internal/timers:500:7)\n'
[ START ] 2021-05-25T23:54:43+0300 ] LSP logging initiated
[ START ] 2021-05-26T00:01:52+0300 ] LSP logging initiated
[ ERROR ] 2021-05-26T00:02:17+0300 ] ...im/HEAD-a282a17_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"typescript-language-server"	"stderr"	'/Users/srg/.fnm/node-versions/v15.10.0/installation/lib/node_modules/typescript-language-server/lib/utils.js:25\n            this.reject(new Error(this.operation + " timeout"));\n                        ^\n\nError: compilerOptionsForInferredProjects timeout\n    at Timeout.<anonymous> (/Users/srg/.fnm/node-versions/v15.10.0/installation/lib/node_modules/typescript-language-server/lib/utils.js:25:25)\n    at listOnTimeout (node:internal/timers:557:17)\n    at processTimers (node:internal/timers:500:7)\n'

</details>

### Steps to reproduce using nvim -u minimal_init.lua

```
nvim -u minimal_init.lua
```
I tried using `minimal_init.lua` file, inserted:

```
  -- Add the server that troubles you here
  local name = "typescript-language-server"
  local cmd = { "pyright-langserver", "--stdio"} -- needed for elixirls, omnisharp, sumneko_lua
```
but got error when I tried to run vim with it

```
E5113: Error while calling lua chunk: /Users/srg/.configalt/nvim/minimal_init.lua:55: attempt to index a nil value
```

The setup I got the error with is minimal by itself

```
-- init.lua
require('plugins')
require('lsp')

-- plugins.lua
return require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' }
  use 'neovim/nvim-lspconfig' 
end)

-- lsp.lua
local nvim_lsp = require('lspconfig')

-- Use an on_attach function to only map the following keys 
-- after the language server attaches to the current buffer
local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  --Enable completion triggered by <c-x><c-o>
  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }

  -- See `:help vim.lsp.*` for documentation on any of the below functions
  buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
  buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
  buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
  buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
  buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
  buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  buf_set_keymap('n', '<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
  buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
  buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
  buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
  buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  buf_set_keymap("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)

end

-- Use a loop to conveniently call 'setup' on multiple servers and
-- map buffer local keybindings when the language server attaches
local servers = { "pyright", "rust_analyzer", "tsserver" }
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup { on_attach = on_attach }
end
```

That is it.

### Actual behaviour

<img width="408" alt="Screenshot 2021-05-25 at 23 58 28" src="https://user-images.githubusercontent.com/6762673/119568170-e09c4500-bdb5-11eb-9abf-97fb2e41b08d.png">

```
[ START ] 2021-05-26T00:01:52+0300 ] LSP logging initiated
[ ERROR ] 2021-05-26T00:02:17+0300 ] ...im/HEAD-a282a17_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"typescript-language-server"	"stderr"	'/Users/srg/.fnm/node-versions/v15.10.0/installation/lib/node_modules/typescript-language-server/lib/utils.js:25\n            this.reject(new Error(this.operation + " timeout"));\n                        ^\n\nError: compilerOptionsForInferredProjects timeout\n    at Timeout.<anonymous> (/Users/srg/.fnm/node-versions/v15.10.0/installation/lib/node_modules/typescript-language-server/lib/utils.js:25:25)\n    at listOnTimeout (node:internal/timers:557:17)\n    at processTimers (node:internal/timers:500:7)\n'

```

### Expected behaviour

Expected to work properly)

**Comment by teto** [comment]
i dont think it's minimal (does it need treesitter ?). What does `:LspInfo` give. What happens if you run the LSP server from the command line ?

**Comment by osenvosem** [comment]
@teto after error is happened `:LspInfo` shows that there is no client connected to the LSP.
`typescript-language-server` is available from CLI and gives this after launching

```
Connection type required (stdio, node-ipc, socket). Refer to --help for more details.
```

**Comment by mjlbach** [comment]
Did you install typescript? Is it accessible on your path?

**Comment by osenvosem** [comment]
@mjlbach Sure.

<img width="501" alt="Screenshot 2021-05-26 at 22 32 01" src="https://user-images.githubusercontent.com/6762673/119720064-320a0a00-be72-11eb-831a-f7a09ad3051f.png">

**Comment by mjlbach** [comment]
Right, but that doesn't indicate it's on your path. If you run `tsserver` in your project repo, what does it say?

**Comment by osenvosem** [comment]
@mjlbach it seems like everything is OK

<img width="655" alt="Screenshot 2021-05-26 at 22 34 46" src="https://user-images.githubusercontent.com/6762673/119720389-94630a80-be72-11eb-8689-3be6c5a2975a.png">

**Comment by mjlbach** [comment]
There seems like there are two issues you're reporting here. Just to clarify, in your original snippet you didn't leave `local cmd = { "pyright-langserver", "--stdio"} -- needed for elixirls, omnisharp, sumneko_lua` in the config right?  I just want to confirm you're no longer getting
```
E5113: Error while calling lua chunk: /Users/srg/.configalt/nvim/minimal_init.lua:55: attempt to index a nil value
```
as that is a user config issue.

**Comment by osenvosem** [comment]
@mjlbach yep, I fixed the `minimal_init.lua` and no longer getting that error. But the situation with LSP timeout error still exists. Here is the lates logs:

<details>
<summary> LSP logs </summary>
[ START ] 2021-05-26T23:50:37+0300 ] LSP logging initiated
[ INFO ] 2021-05-26T23:51:35+0300 ] ...neovim/HEAD-192f89e_2/share/nvim/runtime/lua/vim/lsp.lua:1213 ]	"exit_handler"	{}
[ START ] 2021-05-26T23:51:38+0300 ] LSP logging initiated
[ INFO ] 2021-05-26T23:52:11+0300 ] ...im/HEAD-192f89e_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:311 ]	"Starting RPC client"	{  args = { "--stdio" },  cmd = "typescript-language-server",  extra = {}}
[ DEBUG ] 2021-05-26T23:52:11+0300 ] ...neovim/HEAD-192f89e_2/share/nvim/runtime/lua/vim/lsp.lua:826 ]	"LSP[tsserver]"	"initialize_params"	{  capabilities = {    callHierarchy = {      dynamicRegistration = false,      <metatable> = <1>{        __tostring = <function 1>      }    },    textDocument = {      codeAction = {        codeActionLiteralSupport = {          codeActionKind = {            valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        dynamicRegistration = false,        <metatable> = <table 1>      },      completion = {        completionItem = {          commitCharactersSupport = false,          deprecatedSupport = false,          documentationFormat = { "markdown", "plaintext" },          preselectSupport = false,          snippetSupport = false,          <metatable> = <table 1>        },        completionItemKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },          <metatable> = <table 1>        },        contextSupport = false,        dynamicRegistration = false,        <metatable> = <table 1>      },      declaration = {        linkSupport = true,        <metatable> = <table 1>      },      definition = {        linkSupport = true,        <metatable> = <table 1>      },      documentHighlight = {        dynamicRegistration = false,        <metatable> = <table 1>      },      documentSymbol = {        dynamicRegistration = false,        hierarchicalDocumentSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      hover = {        contentFormat = { "markdown", "plaintext" },        dynamicRegistration = false,        <metatable> = <table 1>      },      implementation = {        linkSupport = true,        <metatable> = <table 1>      },      publishDiagnostics = {        relatedInformation = true,        tagSupport = {          valueSet = { 1, 2 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      references = {        dynamicRegistration = false,        <metatable> = <table 1>      },      rename = {        dynamicRegistration = false,        prepareSupport = true,        <metatable> = <table 1>      },      signatureHelp = {        dynamicRegistration = false,        signatureInformation = {          documentationFormat = { "markdown", "plaintext" },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      synchronization = {        didSave = true,        dynamicRegistration = false,        willSave = false,        willSaveWaitUntil = false,        <metatable> = <table 1>      },      typeDefinition = {        linkSupport = true,        <metatable> = <table 1>      },      <metatable> = <table 1>    },    window = {      showDocument = {        support = false,        <metatable> = <table 1>      },      showMessage = {        messageActionItem = {          additionalPropertiesSupport = false,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workDoneProgress = true,      <metatable> = <table 1>    },    workspace = {      applyEdit = true,      configuration = true,      symbol = {        dynamicRegistration = false,        hierarchicalWorkspaceSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workspaceEdit = {        resourceOperations = { "rename", "create", "delete" },        <metatable> = <table 1>      },      workspaceFolders = true,      <metatable> = <table 1>    }  },  clientInfo = {    name = "Neovim",    version = "0.5.0"  },  initializationOptions = vim.empty_dict(),  processId = 2914,  rootPath = "/Users/srg/Documents/Projects/InternetBank",  rootUri = "file:///Users/srg/Documents/Projects/InternetBank",  trace = "off",  workspaceFolders = { {      name = "/Users/srg/Documents/Projects/InternetBank",      uri = "file:///Users/srg/Documents/Projects/InternetBank"    } }}
[ DEBUG ] 2021-05-26T23:52:11+0300 ] ...im/HEAD-192f89e_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false,        <metatable> = <1>{          __tostring = <function 1>        }      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },              <metatable> = <table 1>            },            <metatable> = <table 1>          },          dynamicRegistration = false,          <metatable> = <table 1>        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = false,            <metatable> = <table 1>          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },            <metatable> = <table 1>          },          contextSupport = false,          dynamicRegistration = false,          <metatable> = <table 1>        },        declaration = {          linkSupport = true,          <metatable> = <table 1>        },        definition = {          linkSupport = true,          <metatable> = <table 1>        },        documentHighlight = {          dynamicRegistration = false,          <metatable> = <table 1>        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false,          <metatable> = <table 1>        },        implementation = {          linkSupport = true,          <metatable> = <table 1>        },        publishDiagnostics = {          relatedInformation = true,          tagSupport = {            valueSet = { 1, 2 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        references = {          dynamicRegistration = false,          <metatable> = <table 1>        },        rename = {          dynamicRegistration = false,          prepareSupport = true,          <metatable> = <table 1>        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            documentationFormat = { "markdown", "plaintext" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false,          <metatable> = <table 1>        },        typeDefinition = {          linkSupport = true,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      window = {        showDocument = {          support = false,          <metatable> = <table 1>        },        showMessage = {          messageActionItem = {            additionalPropertiesSupport = false,            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workDoneProgress = true,        <metatable> = <table 1>      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workspaceEdit = {          resourceOperations = { "rename", "create", "delete" },          <metatable> = <table 1>        },        workspaceFolders = true,        <metatable> = <table 1>      }    },    clientInfo = {      name = "Neovim",      version = "0.5.0"    },    initializationOptions = vim.empty_dict(),    processId = 2914,    rootPath = "/Users/srg/Documents/Projects/InternetBank",    rootUri = "file:///Users/srg/Documents/Projects/InternetBank",    trace = "off",    workspaceFolders = { {        name = "/Users/srg/Documents/Projects/InternetBank",        uri = "file:///Users/srg/Documents/Projects/InternetBank"      } }  }}
[ DEBUG ] 2021-05-26T23:52:12+0300 ] ...im/HEAD-192f89e_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:491 ]	"decoded"	{  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      callsProvider = true,      codeActionProvider = true,      completionProvider = {        resolveProvider = true,        triggerCharacters = { ".", '"', "'", "/", "@", "<" }      },      definitionProvider = true,      documentFormattingProvider = true,      documentHighlightProvider = true,      documentRangeFormattingProvider = true,      documentSymbolProvider = true,      executeCommandProvider = {        commands = { "_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile" }      },      foldingRangeProvider = true,      hoverProvider = true,      implementationProvider = true,      referencesProvider = true,      renameProvider = true,      signatureHelpProvider = {        triggerCharacters = { "(", ",", "<" }      },      textDocumentSync = 2,      typeDefinitionProvider = true,      workspaceSymbolProvider = true    }  }}
[ DEBUG ] 2021-05-26T23:52:12+0300 ] ...im/HEAD-192f89e_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "initialized",  params = {    [true] = 6  }}
[ DEBUG ] 2021-05-26T23:52:12+0300 ] ...neovim/HEAD-192f89e_2/share/nvim/runtime/lua/vim/lsp.lua:853 ]	"LSP[tsserver]"	"server_capabilities"	{  callsProvider = true,  codeActionProvider = true,  completionProvider = {    resolveProvider = true,    triggerCharacters = { ".", '"', "'", "/", "@", "<" }  },  definitionProvider = true,  documentFormattingProvider = true,  documentHighlightProvider = true,  documentRangeFormattingProvider = true,  documentSymbolProvider = true,  executeCommandProvider = {    commands = { "_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile" }  },  foldingRangeProvider = true,  hoverProvider = true,  implementationProvider = true,  referencesProvider = true,  renameProvider = true,  signatureHelpProvider = {    triggerCharacters = { "(", ",", "<" }  },  textDocumentSync = 2,  typeDefinitionProvider = true,  workspaceSymbolProvider = true}
[ INFO ] 2021-05-26T23:52:12+0300 ] ...neovim/HEAD-192f89e_2/share/nvim/runtime/lua/vim/lsp.lua:854 ]	"LSP[tsserver]"	"initialized"	{  resolved_capabilities = {    call_hierarchy = false,    code_action = true,    code_lens = false,    code_lens_resolve = false,    completion = true,    declaration = false,    document_formatting = true,    document_highlight = true,    document_range_formatting = true,    document_symbol = true,    execute_command = true,    find_references = true,    goto_definition = true,    hover = true,    implementation = true,    rename = true,    signature_help = true,    signature_help_trigger_characters = { "(", ",", "<" },    text_document_did_change = 2,    text_document_open_close = true,    text_document_save = true,    text_document_save_include_text = false,    text_document_will_save = false,    text_document_will_save_wait_until = false,    type_definition = true,    workspace_folder_properties = {      changeNotifications = false,      supported = false    },    workspace_symbol = true  }}
[ DEBUG ] 2021-05-26T23:52:12+0300 ] ...im/HEAD-192f89e_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocument = {      languageId = "typescript",      text = "import {\n  isValidElement,\n  cloneElement,\n  Children,\n  ReactElement,\n  ReactNode,\n} from 'react';\n\nimport { useAbFeatures } from './useAbFeatures';\nimport { mergeProps, AB_ERROR_MESSAGE, isRenderedPrimitive } from './utils';\nimport { ScenariosMapType } from './types';\n\ntype AbFeatureProps = {\n  scenariosMap: ScenariosMapType,\n  children?: ReactElement,\n};\n\n/*\n  This way is the best for spot work.\n\n  Take in scenariosMap as prop.\n\n  First approach:\n  AbFeature embraced one or more childrens, purposed for testing,\n  and injecting props of active scenario at every children.\n\n  Second approach:\n  works as single JSX element to deliver from scenariosMap React or DOM element,\n  or number, or string, for render it in place.\n\n  See more about scenariosMap in useAbFeatures.js\n*/\nexport function AbFeature(\n  { scenariosMap, children }: AbFeatureProps,\n): ReactNode {\n  const ab = useAbFeatures(scenariosMap);\n\n  if (!isValidElement(ab) && children) {\n    return Children.map(children, child => cloneElement(child, mergeProps(child.props, ab)));\n  }\n\n  if (isValidElement(ab) && !children) {\n    return ab;\n  }\n\n  if (isRenderedPrimitive(ab)) {\n    return ab;\n  }\n\n  if (process.env.NODE_ENV === 'development') {\n    // eslint-disable-next-line no-console\n    console.error(AB_ERROR_MESSAGE);\n  }\n\n  return null;\n}\n",      uri = "file:///Users/srg/Documents/Projects/InternetBank/src/js/ab-features/AbFeature.ts",      version = 0    }  }}
[ DEBUG ] 2021-05-26T23:52:12+0300 ] ...AD-192f89e_2/share/nvim/runtime/lua/vim/lsp/handlers.lua:443 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///Users/srg/Documents/Projects/InternetBank/src/js/ab-features/AbFeature.ts"  }}
[ ERROR ] 2021-05-26T23:52:32+0300 ] ...im/HEAD-192f89e_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"typescript-language-server"	"stderr"	'/Users/srg/.fnm/node-versions/v15.10.0/installation/lib/node_modules/typescript-language-server/lib/utils.js:25\n            this.reject(new Error(this.operation + " timeout"));\n                        ^\n\nError: compilerOptionsForInferredProjects timeout\n    at Timeout.<anonymous> (/Users/srg/.fnm/node-versions/v15.10.0/installation/lib/node_modules/typescript-language-server/lib/utils.js:25:25)\n    at listOnTimeout (node:internal/timers:557:17)\n    at processTimers (node:internal/timers:500:7)\n'

</details>

**Comment by osenvosem** [comment]
Not sure why, but it is working now after updates. Thanx for trying to help.
