### ISSUE TITLE
Typing 'ø', by pressing AltGr + 'L' when on "U.S. International" keyboard layout, on Windows 10, produces an empty space in Neovim (QT)

### ISSUE THREAD

**Issue by amn** [neovim/neovim#14642]
- `nvim --version`:
```
NVIM v0.5.0-dev+1330-gd16e9d8ed
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-10

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

- Operating system/version:
Windows 10 Enterprise, version 1909, OS build 18363.1556, x86-64

- Terminal name/version:
- `$TERM`:
N/A -- Running Neovim QT, not through a terminal [emulator]

### Actual behaviour

I use the keyboard layout identified by the label "United States-International (QWERTY)" in the "Language options" in the new Windows control panel, which lets me trivially type characters from the extended Latin alphabet (`ø` etc.) _and_ at the same time is mostly compatible with the regular U.S. keyboard layout -- letting me type the double-quote character (`"`), for instance, with the same physical key on my "localized" keyboard as the <kbd><sup>"</sup></kbd> key on the "standard" QWERTY keyboard used in the U.S. To put this into context, the international keyboard layout thus allows me to combine development of software, usually relying on the characters from the ASCII and derivative sets, while at the same time not needing to switch layouts to type in European languages. The keyboard layout is developed by Microsoft and is installed by Windows, it isn't anything I have made myself.

The layout obviously works as described with Windows in general, including applications like GVIM and what have you; but with Neovim (QT) when I try to insert the `ø` character, for example, through the typical combination of holding down <kbd>AltGr</kbd> (to the right of the <kbd>Space</kbd> key) and pressing <kbd>L</kbd> (the Latin letter `L`), all I get is one character advance in Neovim and nothing visible -- essentially an equivalent of one single space inserted.

### Expected behaviour

I expect Neovim to adhere to the regular keyboard behaviour of Windows, as expressed through my preferred keyboard layout.

Does Neovim implement its own physical-logical key translation layer, or is there something else going on? Maybe this has everything to do with QT and its settings, as opposed to Neovim specifically?

`nvim.exe` when used from Powershell does work as expected though -- this issue only concerns the QT variant (`nvim-qt.exe`).

**Comment by jamessan** [comment]
Since this only happens in nvim-qt, please report the issue at https://github.com/equalsraf/neovim-qt.
