### ISSUE TITLE
asynchronous VimL/vimscript

### ISSUE THREAD

**Issue by ReneFroger** [neovim/neovim#1464]
I stumbled upon [Jaxbot's browserlink](https://github.com/jaxbot/browserlink.vim) which is actually a neat plugin. I thought about building a function, that checks if the node is activated, Vim will autowrite html/css filetypes every 10 seconds with < silent >, you don't get bothered with endless "writed" messages displayed. 
So you get always live feedback on your another display (in this case, the browser), without the need to saving your buffer again and again. 

But that's going to be tricky. Vim will freeze when it's writing. You will especially notice the freezing when it's writing a large chunk of buffer. 

I know that Neovim is targeting on a non-blocking feature of Vim plugins, in order to get asynchronous interaction. So I' m wondering if Neovim's non-blocking feature would be possible too to Vim's internal functions? 

Like when you initiate the writing commando, Neovim will write it behind the scenes, while you can still move your cursor. 
Neovim will not writing first, freezing all other things, then it's your turn to have your interaction with Neovim again. You will get noticed it with the "written" message. 

When all internal features of Vim could be asynchronously executed, Neovim will not be freezing anymore for some seconds (aka non-blocking, if you want to call), but this could introduce new bugs. 

But on the other side, I believe this will greatly improve the speed and the snappy feel of Neovim, since there are internal commands everywhere, that the experience benefits of Neovim will outweigh the possibility of new bugs IMHO.

**Comment by kiryph** [comment]
What about remote files opened with netrw. Saving invokes `scp`. Is it possible to get the scp call non-blocking. I assume the temp file is saved first (internal save command) and afterwards the scp call is executed.  I would think only the second step leads to a noticable block of the UI. Does the plugin netrw has to adopt the new neovim async features?

**Comment by justinmk** [comment]
>  with netrw. Saving invokes scp. Is it possible to get the scp call non-blocking

@kiryph Yes, that's possible in Neovim already with `jobstart()`. netrw will never add that feature though.

**Comment by roxma** [comment]
I think It would be nice to have a way of sending change log out of neovim. It's kinda updateing `.swp` file in real time.  Then any external program could make a shadow buffer in realtime by itself.

**Comment by mcepl** [comment]
> netrw will never add that feature though.

@justinmk ehm, why?

**Comment by justinmk** [comment]
This request is now mostly resolved or replaced by other topics:

- https://github.com/neovim/neovim/issues/12857
- https://github.com/neovim/neovim/labels/multiproc
- https://github.com/neovim/neovim/issues/1180
