### ISSUE TITLE
Error detected while processing function <SNR>20_Hi:

### ISSUE THREAD

**Issue by kavin25** [neovim/neovim#14644]
- `nvim --version`: v0.3.8
- Operating system/version: CentOS 8
- Terminal name/version: Hyper 3.0.2
- `$TERM`: xterm-256color

### Actual behaviour
When opening nvim, I get the following warning/error every time
```
Error detected while processing function <SNR>20_Hi:
line        10:
E418: Illegal value: strikethrough
Press ENTER or type command to contine
```

### Expected behaviour
No warning/error

**Comment by Caryyon** [comment]
Getting same thing @kavin25 did you find a fix?

**Comment by kavin25** [comment]
> Getting same thing @kavin25 did you find a fix?

@Caryyon Yeah, my version of neovim was pretty outdated. Had to install a newer version using a different package manager
