### ISSUE TITLE
Colours in nvim-qt, but not when running from terminal

### ISSUE THREAD

**Issue by irishgreencitrus** [neovim/neovim#14651]
- `nvim --version`:
```
NVIM v0.5.0-dev+1357-g192f89ea1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-124

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- Operating system/version:
Edition	Windows 10 Pro
Version	20H2

- Terminal name/version:
powershell.exe, cmd.exe

- Fixes tried:
Using NORC, which doesn't affect anything.
- NVIM config, which may be useful: https://github.com/irishgreencitrus/SourVim

### Actual behaviour
![image](https://user-images.githubusercontent.com/43090499/119788452-0f0b4480-beca-11eb-8d32-b785f871746e.png)
No highlighting in windows terminal, the only thing coloured differently is lightline
### Expected behaviour
![image](https://user-images.githubusercontent.com/43090499/119788597-2e09d680-beca-11eb-910c-1494745e9878.png)
When running in NVIM-QT

**Comment by 3N4N** [comment]
> * Fixes tried:
>       Using NORC, which doesn't affect anything.

Try `nvim --clean` instead of `nvim -u NORC` and check if the default colorschemes show colors properly.  If they don't show colors properly, try again with force-setting $TERM (see below).

```
PS C:\ > nvim --clean
PS C:\ > $env:TERM='xterm-256colors'
:colo peachpuff
```

**Comment by justinmk** [comment]
Also try latest Nvim.
