### ISSUE TITLE
nvim sends rgb codes to stdin upon exit

### ISSUE THREAD

**Issue by sayanarijit** [neovim/neovim#14652]
- `nvim --version`:
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

- Operating system/version:
Description:	Manjaro Linux
Release:	21.0.5

- Terminal name/version:
alacritty 0.7.2 (5ac8060b)

- `$TERM`:
alacritty

- [x] `vim -u DEFAULTS` (version: 8.2.2567) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
TERM=ansi-256color EDITOR="nvim -u NORC" xplr

# Open a text file (non empty)
# Close the file
```

### Actual behaviour

Upon exit, Neovim will send some keys to stdin which is then read by xplr.

### Expected behaviour

Neovim should not send any key to stdin upon exit.

**Comment by sayanarijit** [comment]
Demo:

![nvim-issue](https://user-images.githubusercontent.com/11632726/119801325-38909400-befb-11eb-943e-4cfaf18e9d0a.gif)

**Comment by dylanarmstrong** [comment]
Appears to be a `]` based on a quick test of `xplr` logging.

**Comment by sayanarijit** [comment]
@dylanarmstrong thanks for looking into this. With the following config, I was able to capture: `11;rgb:1e1e/2121/2727`.

```lua
------ Recover
xplr.config.modes.builtin.recover = {
  name = "recover",
  help = nil,
  extra_help = nil,
  key_bindings = {
    on_key = {
      ["ctrl-d"] = {
        help = "done",
        messages = {
          {
            BashExecSilently = [===[
              echo "LogInfo: $XPLR_INPUT_BUFFER" >> $XPLR_PIPE_MSG_IN
            ]===]
          },
          "PopMode",
          "Refresh",
        },
      }
    },
    on_alphabet = nil,
    on_number = nil,
    on_special_character = nil,
    default = {
      help = nil,
      messages = {
        "BufferInputFromKey",
      }
    }
  }
}
```

I'm sure there are a lot of keys I wasn't able to capture using this method.

**Comment by sayanarijit** [comment]
Looks like some color code escape sequence.

**Comment by sayanarijit** [comment]
Apparently, different file produces different keys. From one file I got a lot of `~`.

**Comment by dylanarmstrong** [comment]
So, found the likely culprit:

https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c#L1783

```
  data->unibi_ext.get_bg =
    (int)unibi_add_ext_str(ut, "ext.get_bg",
                           SCREEN_TMUX_WRAP((screen && !tmux), tmux,
                                            "\x1b]11;?\x07"));
```

Commenting this out stops the bug from occurring for me.

I'm not testing inside of tmux or screen technically, but I am declaring my `TERM=screen-256color`.

Unfortunately, I don't know the why behind that code block, so I can't really offer a fix.

**Comment by sayanarijit** [comment]
I'm now using `nvim v0.6.0-dev`, but the issue is still there.

**Comment by justinmk** [comment]
related https://github.com/neovim/neovim/issues/10131

**Comment by sayanarijit** [comment]
I think I captured the actual code. Unlike #10131, it's `]11;rgb:1e1e/2121/2727`.

**Comment by sayanarijit** [comment]
Happens in Alacritty and Konsole, but not in Kitty.

**Comment by sayanarijit** [comment]
Turns out it's not nvim specific. More info here: https://github.com/sayanarijit/xplr/issues/301#issuecomment-933192274

**Comment by sayanarijit** [comment]
I have figured it out. It will be fixed in https://github.com/sayanarijit/xplr/pull/339.
