### ISSUE TITLE
Nvim crashing with pyenv

### ISSUE THREAD

**Issue by chgara** [neovim/neovim#14658]
- `nvim --version`: 0.4.4
- Operating system/version: Manjaro 5.9.16-1
- Terminal name/version: Alacritty 0.7.2
- `$TERM`: alacritty

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
pyenv install "some python version"
pyenv global "some python version"
nvim -u NORC
--on nvim i quit using : q--
it crashes
```
![WhatsApp Image 2021-05-28 at 20 14 13](https://user-images.githubusercontent.com/57034271/120025660-53453480-bff1-11eb-97e4-218101057364.jpeg)

### Actual behaviour
If I do not set any python version with pyenv all works fine but when I set some version like 3.8.8 it crash and freezes my laptop

### Expected behaviour
It should not crash when I quit nvim command

**Comment by glacambre** [comment]
This doesn't look like a crash, it's just a regular error. Also, I think it might be fixed on the master branch. @chgara can you reproduce this issue on the master branch/with the nightly release?
