### ISSUE TITLE
Embedding config / plugin in AppImage

### ISSUE THREAD

**Issue by oxodao** [neovim/neovim#14653]
Hello !

I'm not sure if this have ever been discussed, I haven't found any issue with this. I'm also not 100% certain its not possible with workaround right now.

Would it be possible to have a feature to load config and plugins (Have the ~/.config/nvim) embeddable in the appimage ? That would be really neat as this would mean we could configure neovim the way we like, build an appimage with this config embedded and simply download it on any computer / server we use.

I'm not sure if this would be easily doable but it would be a really interesting feature

**Comment by glacambre** [comment]
I think you can already do this by creating a `sysinit.vim` containing your settings in `$VIM`, which the appimage sets.

**Comment by oxodao** [comment]
This looks interesting thanks!

However the $VIM var seems to be set correctly on my work computer (/tmp/.mount_XXX/usr/share/nvim / Debian) but on my home computer the variable is empty (Archlinux)

I'm trying to export the VIM variable myself like this:
`export VIM=$APPDIR/usr/share/nvim/runtime`

When I ls it, it looks like OK (:!ls $VIM) I get the correct folder but the sysinit.vim (nor init.vim) inside of it is not loaded

**Comment by glacambre** [comment]
Are you sure you're using an appimage on your archlinux computer?

**Comment by oxodao** [comment]
I definitely am, since I edited the AppRun script I unpacked / reapcked it with appimagetool

**Comment by oxodao** [comment]
I'm bringing up this old thread but I still not managed to do it for some reason. 

When I do `:echo $VIM` I get this path: `/tmp/.mount_NeovimWaIcT9/usr/share/nvim`
So I added a `sysinit.vim` as you said in the appimage at `AppImageDir/usr/share/nvim/sysinit.vim` and repacked it.

It does not get loaded. I also checked the `-V` arg to find a not used file, and it tells me it can't load `/etc/xdg/nvim/init.vim` so I tried putting it there in the appimage and it also does not work.

Any clue ?

**Comment by oxodao** [comment]
Ok so I found a way, I'm not that fond of it but it does work for now. Not sure how I would put my whole config in it (Like with plugin & such) but it will do the job for now.

If anyone want to do the same here's my solution:

```
$ ./nvim.appimage --appimage-extract
```

Replace the AppRun with this content (We basically just tell vim it should run with a given config file, in the mounted path of the appimage):
```
#!/bin/bash

export ROOT_PATH="$(dirname "$(readlink -f "${0}")")"
echo $ROOT_PATH

unset ARGV0
exec "$ROOT_PATH/usr/bin/nvim" "-u" "$ROOT_PATH/vimcfg/vimrc" ${@+"$@"}
```

Create the folder: `$ mkdir squashfs-root/vimcfg`
Put your config in `$PWD/squashfs-root/vimcfg/vimrc`

Finally, rebuild the image: `$ appimagetool -n squashfs-root`

You will have an appimage with your embedded config.

Now I need to figure out how to embed plugins and use multiple files without too much hacks

**Comment by justinmk** [comment]
The last comment shows how to resolve this, right?

Also since this was posted, Nvim now supports `$NVIM_APPNAME` which may be useful.
