### ISSUE TITLE
Random character renders

### ISSUE THREAD

**Issue by gleich** [neovim/neovim#14650]
- `nvim --version`: v0.5.0-dev+1339-g5d9c56012
- Operating system/version: macOS 11.3.1 x86_64
- Terminal name/version: kitty 0.20.3 created by Kovid Goyal
- `$TERM`: xterm-kitty

- [x] `vim -u DEFAULTS` (version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 20 2021 19:14:20)) behaves differently

### Steps to reproduce using `nvim -u NORC`

1. Open a file such as [my init.vim file](https://github.com/Matt-Gleich/dots/blob/master/matt/.config/nvim/init.vim) (I have no idea what kind of files cause this) in neovim in kitty.
2. Move down the page with <kbd>}</kbd>.

### Actual behaviour

There are random characters being rendered as seen in the video below:

https://user-images.githubusercontent.com/43759105/119752368-e9028780-be6a-11eb-8036-bb39cd6b3f05.mov

### Expected behaviour

There shouldn't be any characters, just blank spaces.

### Sidenote

Thank you, maintainers! You guys do this work out of the love for this project and do an amazing job. Y'all rock!

**Comment by Matt-Gleich** [comment]
This problem doesn't happen with regular `vim`

**Comment by folke** [comment]
Do you have any unicode characters (or symbols from a nerd font) in that buffer by any chance? If there's a disagreement between vim and your terminal on the width of certain characters, then that's what can happen. Not sure if that's the case here though...

**Comment by zeertzjq** [comment]
Fixed by #19686
