### ISSUE TITLE
Make `:help vim.api.fully_qualified_name` jump to the help for `fully_qualified_name`

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#14655]
(It's hard to search for this, so hopefully I haven't missed a duplicate feature request) --

but it'd be nice if e.g.:

`:help vim.api.nvim_win_get_position`

or perhaps even

`:help api.nvim_win_get_position`

took one to the help for `nvim_win_get_position`, as an alternative for `:help nvim_win_get_position`.

(The reasoning being that copying out of some lua source code, it's often likely someone's got the full name in front of them and may not know to trim it to the final component)

**Comment by justinmk** [comment]
> (The reasoning being that copying out of some lua source code, it's often likely someone's got the full name in front of them and may not know to trim it to the final component)

That works if the fully-qualified name is used in Lua code, but again fails if the code does this common pattern:

```
local a = vim.api
...
a.nvim_...()
```

So this is not a strong reason to add hundreds of redundant help tags.
