### ISSUE TITLE
How to install Neovim-nightly 5.0 in Alpine linux

### ISSUE THREAD

**Issue by danger44** [neovim/neovim#14666]
I am using ISH app on ipad which gives us chance to use the linux on Ipad. ISH app uses the alpine linux in virtual machine. 
I wanted to use the neovim-nightly as I use it on my linux desktop but I tried to different methods to install it but none of them worked. 
-I tried to compile neovim from source then it force closes itself after some time. 
-I tried to excecute appimage files but that also gives error. The normal binary executable are also not working.
I really like to use the nightly version on the ipad.

**Comment by glacambre** [comment]
>I tried to compile neovim from source then it force closes itself after some time.

This sounds like an issue with ish.

>-I tried to excecute appimage files but that also gives error.

Also sounds like an issue with ISH.

You should report these issues to ISH, I don't think Neovim can do anything about these :). If the error messages specifically point to Neovim being at fault please upload them here and I'll re-open :)
