### ISSUE TITLE
Problem with & packer

### ISSUE THREAD

**Issue by LohanGuedes** [neovim/neovim#14662]
- `nvim --version`: v0.5.0-dev+43956de
- Operating system/version: ArchLinux (Archcraft) - Archcraft OS 26.05.2021 (latest version)
- Terminal name/version: 5.12.6-arch1-1
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
E5113: Error while callin lua chunk: /usr/local/share/nvim/runtime/lua/vim/_meta.lua:21 attemp to index local 'info' (a nil value)
### Expected behaviour
not sure :c

**Comment by clason** [comment]
`nvim -u NORC` still loads plugins -- you need `-u NONE` or added `--noplugin` instead. So something must be interfering/not fully up to date. (Needless to say, just `nvim -u NORC` works fine for me.)

**Comment by Antonio-Bennett** [comment]
@clason Oh hey Clason! Saw u on Teej's stream yesterday lol. I'm experiencing the same issue as well luckily I was reading Lunarvim logs because someone reported the same error and Christian found that it was vim.o.t_Co was our issue. Not sure if it's the same for @LohanGuedes but yeah vim.o.t_Co = "256" threw the error

**Comment by clason** [comment]
Right, `t_Co` doesn't seem to be picked up. It works via `vim.go.t_Co` (note that #13479 changed the meaning of `vim.o` from, roughly, "setglobal" to "set").

**Comment by Antonio-Bennett** [comment]
Ahhh that worked! Wow, I need to really read the docs. Thanks a lot tho!

**Comment by clason** [comment]
So it seems that `t_Co` is not accessible from either `vim.o` nor `vim.opt`. Trying to set it gives the above mentioned error (unless you try to set it as a number, then it suddenly remembers this option and complains that it wants a string ;)), trying to print it complains that it is not a valid option. 

@tjdevries

**Comment by Antonio-Bennett** [comment]
I might not be using the new syntax correctly but after going through my settings file these are the options that do not work for me or I'm not sure on

```
vim.opt.shortmess:append {"c"} doesn't work -> vim.opt.iskeyword:append {"-"} works however
vim.opt.whichwrap:append {"<", ">", "[", "]", "h", "l"} doesn't work, maybe not the correct way to set?
vim.cmd(fileype plugin indent on) -> How do you do this?
```

**Comment by clason** [comment]
Thanks for testing!

(The last one is not an option but a command, so not related to that PR. `vim.cmd` is indeed the way to go, but you need to pass it a string, so `vim.cmd("fileype plugin indent on")`.)

**Comment by Antonio-Bennett** [comment]
Ok I'll keep it with vim.cmd thanks!

**Comment by argapost** [comment]
> I might not be using the new syntax correctly but after going through my settings file these are the options that do not work for me or I'm not sure on
> 
> ```
> vim.opt.shortmess:append {"c"} doesn't work -> vim.opt.iskeyword:append {"-"} works however
> vim.opt.whichwrap:append {"<", ">", "[", "]", "h", "l"} doesn't work, maybe not the correct way to set?
> vim.cmd(fileype plugin indent on) -> How do you do this?
> ```

```lua
vim.opt.shortmess:append {c = true}
vim.opt.whichwrap:append {['<'] = true, ['>'] = true, [','] = true, h = true, l = true} -- move to next line with theses keys
```

these should work for you

**Comment by Antonio-Bennett** [comment]
That did work thank you very much @argapost

**Comment by clason** [comment]
Regarding the initial error: `t_Co` and friends aren't supported by neovim anymore and have been deprecated for a long time, so that option shouldn't have been set in the first place ;)

**Comment by clason** [comment]
> > vim.opt.shortmess:append {"c"} doesn't work -> vim.opt.iskeyword:append {"-"} works however

Careful: `append{"c"}` is not just a "curly" version of writing `append("c")` (which does work!) -- it's just shorthand for `append({"c"})`, which is a different thing. (Lua allows omitting the parentheses for functions with a single argument.)

> > vim.opt.whichwrap:append {"<", ">", "[", "]", "h", "l"} doesn't work, maybe not the correct way to set?
> > vim.cmd(fileype plugin indent on) -> How do you do this?
> > ```
> 
> ```lua
> vim.opt.shortmess:append {c = true}
> vim.opt.whichwrap:append {['<'] = true, ['>'] = true, [','] = true, h = true, l = true}
> ```
> 
> these should work for you

**Comment by Antonio-Bennett** [comment]
Ahh okay, thanks for the explanation! @clason

**Comment by clason** [comment]
@LohanGuedes Could you please edit the issue title to something more descriptive? (Like `"Error when calling Lua chunk" with `vim.opt`/`vim.o`?) 

I won't close this issue even though it's technically `wont-fix` (`t_Co` is deprecated and therefore not supported deliberately) because a) people seem to keep hitting that issue b) the comments contain useful tips for migrating and c) it may be possible to improve the error message in a followup PR.

**Comment by tjdevries** [comment]
I'm going to close this because `t_Co` has been mentioned to be deprecated for a long time :)
