### ISSUE TITLE
The table returned by `vim.opt.whichwrap:get()` contains a comma

### ISSUE THREAD

**Issue by nanotee** [neovim/neovim#14669]
- `nvim --version`:
    ```
    NVIM v0.5.0-dev+1359-g43956dea5
    Build type: RelWithDebInfo
    LuaJIT 2.1.0-beta3
    ```
- Operating system/version: Solus 4.2 Fortitude
- Terminal name/version: Konsole 21.04.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```sh
nvim -u NORC
```
```vim
:set whichwrap=b,s
:lua print(vim.inspect(vim.opt.whichwrap:get()))
```

### Actual behaviour

Neovim prints `{[","] = true, b = true, s = true}`. Currently `get_option_type()` assumes an option is a `SET` if `info.flaglist` is `true` and an `ARRAY` if `info.commalist` is `true`. The `'whichwrap'` option is both a `commalist` and a `flaglist`

### Expected behaviour

The `:get()` method should return `{b = true, s = true}`

**Comment by crispgm** [comment]
> https://github.com/neovim/neovim/blob/master/runtime/lua/vim/_meta.lua#L377

It's because the value is not split `,` here, so should we split the value before for loop?

```lua
assert(info.flaglist, "That is the only one I know how to handle")

local result = {}
local values = vim.split(value, ",")
for i in pairs(values) do
  result[values[i]] = true
end
```

If this was correct, I would PR.

**Comment by smolck** [comment]
@crispgm I think that should be done only if it `info.commalist` is true? Regardless, you could make that change locally and run the `vim.opt` tests and see if they still pass, and then open a PR; I'm not sure if this is the right way to go about this (not familiar with `vim.opt`'s code) but seems like it could be fine.

**Comment by crispgm** [comment]
> @crispgm I think that should be done only if `info.commalist` is true? Regardless, you could make that change locally and run the `vim.opt` tests and see if they still pass, and then open a PR; I'm not sure if that solution is the "right" way to fix this issue (not familiar with `vim.opt`'s code) but seems like it could be fine.

if `info.type == "string"` and `info.flaglist`, it's a `set` option type by definition in this implementation. So the real set and get part only operate based on option type.
