### ISSUE TITLE
Invalid option name `number` when accessing via `vim.opt.number`

### ISSUE THREAD

**Issue by ckipp01** [neovim/neovim#14677]
- `nvim --version`: `NVIM v0.5.0-dev+3cd688ff7`
- Operating system/version: `Mac OS`
- Terminal name/version: `iTerm 2 3.4.8`
- `$TERM`: `xterm-256color`

When trying to retrieve the value of `number` without explicity setting it right before throws an error that `Invalid option name: 'number'`. For example I've tested using the following minimal `init.lua`.

### Steps to reproduce using `nvim -u NORC`

```lua
--init.lua
local number_setting = vim.opt.number:get()
print(number_setting)
```

Upon opening with `nvim -u /path/init.lua <file>`:

```
E5113: Error while calling lua chunk: ...ovim/HEAD-3cd688f_2/share/nvim/runtime/lua/vim/_meta.lua:617: Invalid option name: 'number'
```

I've tried a few different versions of this all with the same result. For example the same error is throwing when trying:

```lua
local number_setting = vim.api.nvim_get_option("number")
print(number_setting)
```
One interesting this is that when I try:

```lua
local number_setting = vim.wo.number
print(number_setting)
```
That works fine.

If I also do the following, it will correctly print `true`:

```lua
vim.opt.number = true
local number_setting = vim.opt.number:get()
print(number_setting)
```

### Expected behaviour

I'd expect to be able to use `vim.opt.number:get()` to get the current value without having to explicitly set it.

**Comment by clason** [comment]
> I've tried a few different versions of this all with the same result. For example the same error is throwing when trying:
> 
> ```lua
> local number_setting = vim.api.nvim_get_option("number")
> print(number_setting)
> ```

Note that you get a similar error from vimscript:
```vim
:echo nvim_get_option("number")
```
```
E5555: API call: Invalid option name: 'number'
```

**Comment by clason** [comment]
(Note that `number` is a window option, so it should be `vim.api.nvim_win_get_option(0,"number")`. Nevertheless, the _new_ `vim.o` -- and `vim.opt` -- should be able to access it.)

**Comment by bfredl** [comment]
The check on line 212 in `_meta.lua` is incorrect, `nvim_win_get_option` should be used even when the `was_set` flag is false.

**Comment by clason** [comment]
I think that was discussed here: https://github.com/neovim/neovim/pull/13479#issuecomment-800775647 ?

**Comment by bfredl** [comment]
yes, as 'number' is not global-local it needs to always use `nvim_win_get_option`

**Comment by ckipp01** [comment]
> (Note that number is a window option, so it should be vim.api.nvim_win_get_option(0,"number")

Ahh, yea of course, that's why `vim.wo` works fine. Makes sense.

If I understood everything, I've gone ahead and made the changes and sent in a pr. It does fix this specific scenario and I did add a test, I'm just unsure if there are ever times there why we shouldn't actually call `nvim_win_get_option`.
