### ISSUE TITLE
Add callback to vim.lsp.diagnostic.on_publish_diagnostics

### ISSUE THREAD

**Issue by MrcJkb** [neovim/neovim#14672]
I am looking for a way to hook into diagnostics events and programatically analyse/react to diagnostics.

My use case is to automatically resolve certain errors. For example, if an autocomplete suggestion is chosen, my workflow is often interrupted because of missing module or package imports. In many cases, this can be resolved by a code action ("import module/package x"), which could be somewhat automated.

I took a look at the `vim.lsp.diagnostic.on_publish_diagnostics` function, which takes a `config` argument that can be overridden using `vim.lsp.with`, e.g.

```
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, {
    -- Disable signs
    signs = false,
  }
)
```
So I feel it would make sense to add a callback function to the config parameter that is evaluated on the diagnostics. Something like:

```
function M.on_publish_diagnostics(_, _, params, client_id, _, config)

  -- ...

  local diagnostics = params.diagnostics
  if config and config.callback then
    config.callback(diagnostics)
  end

  -- '''

end

```

I realise I could just wrap the entire `on_publish_diagnostics` function and extract the diagnostics from the `params` argument. But since it's not an official API endpoint, I figured I would leave this suggestion here.

**Comment by mjlbach** [comment]
> But since it's not an official API endpoint, I figured I would leave this suggestion here.

I'm not sure I understand this. IMO, wrapping the function is more clear/easier than implementing a callback (within a callback) system.

**Comment by MrcJkb** [comment]
> > But since it's not an official API endpoint, I figured I would leave this suggestion here.
> 
> I'm not sure I understand this. IMO, wrapping the function is more clear/easier than implementing a callback (within a callback) system.

I believe it would be more clear than wrapping the `on_publish_diagnostics` callback, since it would work with the `vim.lsp.with` convenience wrapper, and the nested callback would only have one argument (the diagnostics).

One potential issue I see with the nested approach would be the potential for conflicting overrides, so it would definitely need more thought.

**Comment by tjdevries** [comment]
What do you mean "not official endpoint"?

**Comment by MrcJkb** [comment]
> What do you mean "not official endpoint"? 

There's no documented, concise API (that I know of) for hooking into LSP events.

I would see wrapping the entire `on_publish_diagnostics` function for the purpose of analysing/reacting to new diagnostics as a workaround.

**Comment by tjdevries** [comment]
Does `:help lsp-handlers` give you the information you need? I don't understand I guess how that is not hooking into LSP events?

**Comment by MrcJkb** [comment]
Yes, the lsp handlers work perfectly fine. My only issue with them is that they come with boilerplate for my specific use case. I don't need to change any configurations, for example.

My plan is to attempt to automate the resolving of some common errors, by hooking into diagnostics events. For example, missing packages in Java, or missing modules in Haskell or Rust that could be auto-imported without the need for user action.

To do so, my initial idea is to replace the default `on_publish_diagnostics` handler with one that decorates the default handler with an additional callback. The additional callback would only emit the information I need, and not allow any modification of the default behaviour of `on_publish_diagnostics`.
Because I would likely create multiple "auto-fix" plugins for different languages, I would extract my "lsp handler decorator" to its own plugin, on which all the "auto-fix" plugins would depend.

I am trying to find out if you see a potential use for such a callback (_that only emits information, but does not modify behaviour_) in NeoVim, in which case I wouldn't create a plugin, but would open a PR instead. If not, I would close this issue and just write a plugin.

Sorry for causing all the confusion btw.

**Comment by mjlbach** [comment]
> Yes, the lsp handlers work perfectly fine. My only issue with them is that they come with boilerplate for my specific use case. I don't need to change any configurations, for example.

I think adding a callback mechanism will ultimately end up in you writing approximately the same amount of code as overriding the handler with a function that wraps the original handler. 

I guess what you're saying, is you want an extensible way to add handlers such that multiple plugins can co-exist by registering their own callbacks within each handler? I feel like that is going to be messy/stateful (dealing with the order in which callbacks are called, we can't enforce that they don't overwrite state used by the other, etc.)

**Comment by MrcJkb** [comment]
> I think adding a callback mechanism will ultimately end up in you writing approximately the same amount of code as overriding the handler with a function that wraps the original handler...

Yes, passing the callback via an argument would be error-prone, and it's probably not the best place for it from a design perspective (that was just a rough initial idea). But maybe something like this would work:

```
-- Overridable hook: Default is an empty function
vim.lsp.hooks.["textDocument/publishDiagnostics"] = function(diagnostics) end
```

... called by the default handler:

```
function M.on_publish_diagnostics(_, _, params, client_id, _, config)
...
  local diagnostics_hook = vim.lsp.hooks.["textDocument/publishDiagnostics"]
  if diagnostics_hook then
    diagnostics_hook(params.diagnostics)
  end
...
end
```

A plugin could then wrap the more concise vim.lsp.hooks.["textDocument/publishDiagnostics"]  function.

**Comment by mfussenegger** [comment]
Currently you could write something like this:


```lua
local orig_handler = vim.lsp.handlers["textDocument/publishDiagnostics"]
vim.lsp.handlers["textDocument/publishDiagnostics"] = function(...)
  local result = select(3, ...)
  -- do something with result
  orig_handler(...)
end
```


If we wanted to have a generic approach to listen to responses or events, I think we'd need a listener approach like there is in nvim-dap. (See https://github.com/mfussenegger/nvim-dap/blob/826a1931fdf1b3b67a0b456aa3abc1b72185a7a7/doc/dap.txt#L780-L832 for a description on how it works)

There's an additional key per subscription, to make it easy to register/de-register.

In your `vim.lsp.hooks` example it would translate to:

```
vim.lsp.hooks[handler][subscription_id] = function(...) end

-- or

vim.lsp.hooks[subscription_id][handler] = function(...) end
```


But given that there are already some options to override and inject handlers I'm not sure if adding another way to subscribe to events is warranted.

**Comment by MrcJkb** [comment]
I would see the following benefits in your listener approach:

- Interface segregation: Adding additional behaviour by reacting to events (without side effects regarding the default behaviour) vs. configuration of the default behaviour.
- The ability to safely deregister listeners. In the current approach, you could restore the `orig_handler`, but that would have a chance of breaking another plugin that uses the same approach.

**Comment by mjlbach** [comment]
> But given that there are already some options to override and inject handlers I'm not sure if adding another way to subscribe to events is warranted.

I agree with this, I don't thing adding another way to subscribe to events is something I would support.

**Comment by folke** [comment]
Not entirely sure this first your use-case, but you could also define an autocmd for the `User LspDiagnosticsChanged` event and then simply get the diagnostics with `vim.lsp.diagnostic.get()` or `vim.lsp.diagnostic.get_all()` to act on them.

**Comment by MrcJkb** [comment]
> Not entirely sure this fits your use-case, but you could also define an autocmd for the `User LspDiagnosticsChanged` event and then simply get the diagnostics with `vim.lsp.diagnostic.get()` or `vim.lsp.diagnostic.get_all()` to act on them.

Thanks. That looks like it will fit my use case quite well (though it only works for loaded buffers, which is fine for my use case).
