### ISSUE TITLE
Breaking changes?

### ISSUE THREAD

**Issue by ray-x** [neovim/neovim#14674]
https://github.com/ray-x/lsp_signature.nvim/issues/19

```
focusable_preview is deprecated. Please use open_floating_preview and pass focus_id = [unique_name] instead
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1322: syntax: expected string, got table
stack traceback:
/usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1322: in function 'focusable_preview'
...ck/packer/start/lsp_signature.nvim/lua/lsp_signature.lua:139: in function 'handler'
/usr/local/share/nvim/runtime/lua/vim/lsp.lua:896: in function 'cb'
vim.lua:277: in function vim.lua:277
```

The way I am using focusable_preview:

```lua
    vim.lsp.util.focusable_preview(method .. "lsp_signature" .. id, function()
      lines = vim.lsp.util.trim_empty_lines(lines)
      return lines, vim.lsp.util.try_trim_markdown_code_blocks(lines), config
    end)
```
The issue seems to be I can no longer use try_trim_markdown_code_blocks. is there an alternative, or it is been handled?

I can understand I should switch to `open_floating_preview`.  But the error sounds to me a breaking change.

**Comment by mjlbach** [comment]
Yep, I should have updated the breaking change issue earlier today (which I just did). The issue is that focusable preview has been deprecated in favor of `open_floating_preview` . If you need help additional help, you could ask on matrix/gitter/IRC.
