### ISSUE TITLE
Strikethrough Vim Color Rendering Differences

### ISSUE THREAD

**Issue by jgehrig** [neovim/neovim#14683]
Neovim renders `underline` and `strikethrough` differently than gVim.

I'm assuming the `underline` behavior is by-design.

Is there any reason we don't render `strikethrough` using the same color logic as Vim?

| Editor | Mode | Render |
| --- | --- | --- |
| gVim | underline | always foreground |
| gVim |  strikethrough | special then foreground |
| Neovim | underline | special then foreground |
| Neovim | strikethrough | always foreground |

**Neovim TUI:**
Highlight Group | Result
-- | --
`:hi SpellBad gui=underline guisp=Red guifg=Green` | ![image](https://user-images.githubusercontent.com/86065/120048013-53a3f680-c016-11eb-9b2e-2bdafac52355.png)
`:hi SpellBad gui=underline guisp=NONE guifg=Green` |![image](https://user-images.githubusercontent.com/86065/120048014-543c8d00-c016-11eb-9a6a-1e558115044a.png)
`:hi SpellBad gui=undercurl guisp=Red guifg=Green` | ![image](https://user-images.githubusercontent.com/86065/120048015-543c8d00-c016-11eb-9b90-9481eb92d214.png)
`:hi SpellBad gui=undercurl guisp=NONE guifg=Green` | ![image](https://user-images.githubusercontent.com/86065/120048016-543c8d00-c016-11eb-8dfb-98dce90baafc.png)
`:hi SpellBad gui=strikethrough guisp=Red guifg=Green` | ![image](https://user-images.githubusercontent.com/86065/120048017-543c8d00-c016-11eb-9071-95992ffc55ef.png)
`:hi SpellBad gui=strikethrough guisp=NONE guifg=Green` | ![image](https://user-images.githubusercontent.com/86065/120048018-54d52380-c016-11eb-9b8a-586d810ede7f.png)

**gVim**
Highlight Group | Result
|-- | --|
| `:hi SpellBad gui=underline guisp=Red guifg=Green` | ![image](https://user-images.githubusercontent.com/11207308/120145124-09a34800-c1b1-11eb-8cd1-f99ab00652e4.png) |
| `:hi SpellBad gui=underline guisp=NONE guifg=Green` | ![image](https://user-images.githubusercontent.com/11207308/120145181-1a53be00-c1b1-11eb-8364-4de971f914f3.png) |
| `:hi SpellBad gui=undercurl guisp=Red guifg=Green` | ![image](https://user-images.githubusercontent.com/11207308/120145233-2dff2480-c1b1-11eb-9209-6a48721f3bb1.png) |
| `:hi SpellBad gui=undercurl guisp=NONE guifg=Green` | ![image](https://user-images.githubusercontent.com/11207308/120145282-3f483100-c1b1-11eb-8a86-433132fbaa26.png) |
| `:hi SpellBad gui=strikethrough guisp=Red guifg=Green` | ![image](https://user-images.githubusercontent.com/11207308/120145324-4ec77a00-c1b1-11eb-81fe-284bb530b4e5.png) |
| `:hi SpellBad gui=strikethrough guisp=NONE guifg=Green` | ![image](https://user-images.githubusercontent.com/11207308/120145364-6141b380-c1b1-11eb-92cb-959605f7e7bf.png) |

See:
https://github.com/equalsraf/neovim-qt/pull/860#issuecomment-849918817

**Comment by justinmk** [comment]
From https://github.com/neovim/neovim/issues/14453 (which appears to be a duplicate):

> we should ignore the guisp of the float unless it has underline or undercurl set.

Is this still an issue @jgehrig ?
