### ISSUE TITLE
Accepting a motion for `vim.lsp.buf.range_formatting`

### ISSUE THREAD

**Issue by kovasap** [neovim/neovim#14680]
It looks like the `range_formatting` function takes in line positions that would allow it to format lines that are specified by a motion.  I would love to have some kind of normal mode mapping to e.g. `gl` that allows me to do something like `glip` to format a paragraph.  I feel like this is possible and maybe has already been done, but I'm at a loss for how to do it myself or where to find this functionality.  Any pointers?

**Comment by kovasap** [comment]
Any ideas here?  This has probably already been done somewhere?

**Comment by mjlbach** [comment]
It hasn't been for any lsp functionality, given that you can already do this by first going into visual mode (I know that's not what you want) and then format_range, it's not a high priority for me, but happy to review any PR!

**Comment by shadmansaleh** [comment]
You could easily do something like

```lua
local function format_range_operator()
  local old_func = vim.go.operatorfunc
  _G.op_func_formatting = function()
    local start = vim.api.nvim_buf_get_mark(0, '[')
    local finish = vim.api.nvim_buf_get_mark(0, ']')
    vim.lsp.buf.range_formatting({}, start, finish)
    vim.go.operatorfunc = old_func
    _G.op_func_formatting = nil
  end
  vim.go.operatorfunc = 'v:lua.op_func_formatting'
  vim.api.nvim_feedkeys('g@', 'n', false)
end
```

And map that map that function to what ever key you want to use . I haven't tested it though . I can't find server that does range formatting :P

**Comment by kovasap** [comment]
To clarify, do you mean that you could add this to `init.lua` and then be able to use `gmip` in normal mode to format a paragraph?

```
local function format_range_operator()
  local old_func = vim.go.operatorfunc
  _G.op_func_formatting = function()
    local start = vim.api.nvim_buf_get_mark(0, '[')
    local finish = vim.api.nvim_buf_get_mark(0, ']')
    vim.lsp.buf.range_formatting({}, start, finish)
    vim.go.operatorfunc = old_func
    _G.op_func_formatting = nil
  end
  vim.go.operatorfunc = 'v:lua.op_func_formatting'
  vim.api.nvim_feedkeys('g@', 'n', false)
end
vim.api.nvim_set_keymap("n", "gm", "<cmd>lua format_range_operator()<CR>", {noremap = true})
```

This doesn't seem to work for me.  Perhaps I missed something?

**Comment by shadmansaleh** [comment]
```diff
-local function format_range_operator()
+function format_range_operator()
```

Make it a global function you can only map global functions the way you're mapping. Also check if your lasp server has range formatting capability set

**Comment by kovasap** [comment]
Hmm, I think that helps, but now I get this error when I type `gmip`:
```lua
function format_range_operator()
  local old_func = vim.go.operatorfunc  -- ERROR: Error executing lua: <path to init.lua>: attampt to index field 'go' (a nil value)
  _G.op_func_formatting = function()
    local start = vim.api.nvim_buf_get_mark(0, '[')
    local finish = vim.api.nvim_buf_get_mark(0, ']')
    vim.lsp.buf.range_formatting({}, start, finish)
    vim.go.operatorfunc = old_func
    _G.op_func_formatting = nil
  end
  vim.go.operatorfunc = 'v:lua.op_func_formatting'
  vim.api.nvim_feedkeys('g@', 'n', false)
end
vim.api.nvim_set_keymap("n", "gm", "<cmd>lua format_range_operator()<CR>", {noremap = true})
```

My language server definitely supports range formatting - it works with `  buf_set_keymap("v", "gl", "<cmd>lua vim.lsp.buf.range_formatting()<CR>", opts)` (in visual mode)!

**Comment by shadmansaleh** [comment]
Update nvim

**Comment by kovasap** [comment]
This works, thanks!!  A internal company LSP for python.

**Comment by kovasap** [comment]
It would be cool if this function was built into https://github.com/neovim/nvim-lspconfig and referenced in the docs : ).  @mjlbach do you have an opinion about this?

**Comment by mjlbach** [comment]
It wouldn't go in lspconfig, lspconfig is (supposed) to be just configurations for language servers. It would probably go in `vim.lsp.buf` or `vim.lsp.util`. I feel like the solution as it stands is a little hacky, so I probably wouldn't feel comfortable merging it. You can put it in the nvim-lspconfig user tips section of the lspconfig wiki if you want though.

**Comment by kovasap** [comment]
Done!  https://github.com/neovim/nvim-lspconfig/wiki/User-contributed-tips

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/format-a-text-object-using-lsp/3255/3
