### ISSUE TITLE
Useless output of manual pages for a given token

### ISSUE THREAD

**Issue by dumblob** [neovim/neovim#1468]
EDIT: The issue is described in https://github.com/neovim/neovim/issues/1468#issuecomment-62932261 . The following description is no more valid.

Let's select some text, say `strstr`, press `3K` and a man page will occur. Press few times `j` and `k`. You'll notice, that it's somehow slow and that it reacts only no every second press approximately. After that press `q` to quit the man page and afterwards `Enter`. In the best case you'll be presented with a nice auto-scrolling show composed from keys pressed when viewing the manual. Sometimes nvim gets even stuck in the man page or before or after the `Press ENTER or type...` message (see the output below) and one needs to press Ctrl+D to produce a closing character and then Ctrl+C because the input can't be opened any more in any simple way (though it might be already possible through the msgpack API from another client).

~~~~
0$ nvim del/dao_test00.c 

QQ
Press ENTER or type command to continueVim: Error reading input, exiting...

Vim: Finished.
1$
~~~~

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/1878
