### ISSUE TITLE
Keybindings not working as expected in :Man

### ISSUE THREAD

**Issue by rYR79435** [neovim/neovim#14688]
- `nvim --version`: NVIM v0.4.4
- Operating system/version: 5.12.8-arch1-1 (Arch Linux)
- Terminal name/version: alacritty 0.8.0 (a1b13e68)
- `$TERM`: alacritty

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using ~~`nvim -u NORC`~~
No `-u NORC` since my problem is specific to my init.vim. I can reproduce this with only the below 4 keybindings in my init.vim:
```
noremap j h #left
noremap k j #down
noremap l k #up
noremap ; l #right
```
(comments for clarity, not actually present in my init.vim)
1. Open nvim
2. `:Man systemd`
3. Try to move around

### Actual behaviour
My `j` (left) is down (what it would be without keybinding) and my `k` (down) key is up (again, like without keybinding).
My `l` (up) and `;` (right) keys, however, behave like expected and not as if there were no keybindings.

### Expected behaviour
Movement keys how they are specified in the config.

I can fix it by adding the following:
```
au filetype man nnoremap <buffer> j h
au filetype man nnoremap <buffer> k j
au filetype man nnoremap <buffer> l k
au filetype man nnoremap <buffer> ; l
```

I would expect all my keybindings to work and not just some of them, is that a misunderstanding?

**Comment by glacambre** [comment]
It looks like you can define `g:no_man_maps` to prevent Neovim from re-defining these keybindings:

https://github.com/neovim/neovim/blob/7d4f890aa92a1d961c5a048486adf9195427e940/runtime/ftplugin/man.vim#L30-L32

I agree that it's a bit weird to create them in the first place though. @doronbehar I think you're the one who added them in #9023, what was the reasoning?

**Comment by doronbehar** [comment]
> I agree that it's a bit weird to create them in the first place though. @doronbehar I think you're the one who added them in #9023, what was the reason?

That's a good question :). Since softwrap is used ever since #9023, it's likely to get very long lines in manpages that will be wrapped softly, and without this mapping, pressing `j` can make your cursor jump between very long paragraphs and that's an unintuitive behavior I tried to hide.

Maybe the OP should try `map` and not `noremap`? I think this kind of situations are exactly the reason there's a distinction between the two.

**Comment by rYR79435** [comment]
`noremap` is necessary, otherwise the bindings "trip" over each other (they become recursive).

Would it make sense to use [\<unique>](https://vimhelp.org/map.txt.html#%3Amap-%3Cunique%3E) in man.vim? If I understand correctly, using this would prevent them from being mapped in my case but would still work for everyone else.

**Comment by doronbehar** [comment]
> `noremap` is necessary, otherwise the bindings "trip" over each other (they become recursive).
> 
> Would it make sense to use [<unique>](https://vimhelp.org/map.txt.html#%3Amap-%3Cunique%3E) in man.vim? If I understand correctly, using this would prevent them from being mapped in my case but would still work for everyone else.

That looks exactly like what's missing! I think you can test if this works using a clone of this repo and running:

```
# Inside the repo
$ env VIMRUNTIME=$PWD/runtime nvim
```

While `man.vim` was edited.

**Comment by jamessan** [comment]
Instead of using maps, maybe you want to use `set langmap=jkl\\;;hjkl`.

**Comment by rYR79435** [comment]
`langmap` is the perfect solution for this. Thanks a lot @jamessan.
