### ISSUE TITLE
vim.api.open_floating_preview inaccurate floating window position

### ISSUE THREAD

**Issue by ray-x** [neovim/neovim#14691]
HI, I switch to open_floating_preview recently.
I use this API to show signature help.

I found by default, the floating window is a bit too far away from cursor if I set ` relative = "cursor",     ` 

<img width="1285" alt="Screen Shot 2021-06-01 at 6 54 53 am" src="https://user-images.githubusercontent.com/1681295/120241920-17d39000-c2a7-11eb-94f4-8a0a2f236075.png">

It might caused by `make_floating_popup_options`, so I dump the result of make_floating_popup_options:

```lua
{                                                                                                                                                                                  
  anchor = "SW",                                                                                                                                                                   
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },                                                                                                                             
  col = 0,                                                                                                                                                                         
  height = 9,                                                                                                                                                                      
  relative = "cursor",                                                                                                                                                             
  row = -8,                                                                                                                                                                        
  style = "minimal",                                                                                                                                                               
  width = 109                                                                                                                                                                      
}     
```

What I would like is (previous behaviour)

![float](https://github.com/ray-x/files/blob/master/img/signature/virtual_text.jpg?raw=true)

Is there an additional setup I am missing when using open_floating_preview?

**Comment by folke** [comment]
I can't reproduce this.

When I do `:lua vim.lsp.buf.hover()` (which uses `open_floating_preview`), the popup is positioned as it should.

![image](https://user-images.githubusercontent.com/292349/120277512-ff448500-c268-11eb-879e-f73893c3dcf8.png)


Can you provide the exact parameters you use to call `open_floating_preview`?

**Comment by folke** [comment]
Would also be great if you could point me to the commit when things were still working as they should.

**Comment by folke** [comment]
I'm able to reproduce it.

The border config expects either a string, or a table with border character and highlight groups.

I'll change it so it also accepts a table of just border characters.

**Comment by folke** [comment]
I created  a PR to allow a list of border characters.
fyi: the bug (feature) you experienced, was there for at least two months, so not something new.

**Comment by ray-x** [comment]
Great. @folke 
Thanks for looking into this. Hope it will be merged soon.
