### ISSUE TITLE
vim.bo no longer exists

### ISSUE THREAD

**Issue by stevensojka-toast** [neovim/neovim#14697]
In the latest master `vim.bo` no longer exists (same thing for wo), but in the docs it still states the aliases exist. This is breaking several plugins that relied on those aliases, like nvim-compe. This PR removes them but still retains the docs for them https://github.com/neovim/neovim/pull/13479

**Comment by clason** [comment]
Works for me, e.g., `:lua vim.bo.buflisted=true`.

Are you sure you built _and installed_ master correctly? (Runtime files changed, so you need to `make cmake` or `make distclean` first to update the cmake cache and make sure the new runtime file is in $VIMRUNTIME path.)

**Comment by bfredl** [comment]
They still exist. Did you update your runtime along with the nvim executable?

**Comment by stevensojka-toast** [comment]
Ah ok. I think I missed the new runtime file. Thanks for the quick response!
