### ISSUE TITLE
nvim doesn't load ~/.config/nvim/init.lua file

### ISSUE THREAD

**Issue by phenax** [neovim/neovim#14699]
- `nvim --version`:
```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/66qykx321vz3vabqwgh5vpsfy4wi2zm0-neovim-nightly/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: `NixOS unstable`
- Terminal name/version: `st 0.8.4`
- `$TERM`: `st-256color`

### Steps to reproduce using `nvim -u NORC`
Not relevant in this case as `nvim` and `nvim -u NORC` will yield the same result

### Actual behaviour
- Running `nvim`, doesn't load my `~/.config/nvim/init.lua` file.
- Running `nvim -u ~/.config/nvim/init.lua` works as expected which confirms that my config is sane.
- `echo $XDG_CONFIG_HOME` gives me the correct path to `~/.config` so that isn't the cause either.

### Expected behaviour
Expected nvim to load `~/.config/nvim/init.lua` by default

**Comment by phenax** [comment]
The issue got fixed after another update yesterday. Unsure how.

**Comment by featheryus** [comment]
@phenax, I have a similar issue in 0.4.4, it seems a basic function, can you give some explanation.
And now, what can I do to make it work. Thx.
In my env, $HOME is /root, but nvim try to load /home/root/.config/nvim/init.lua, so it failed.

**Comment by mjlbach** [comment]
init.lua support was added in 0.5.0

**Comment by Cyliann** [comment]
I've got the same issue. When I open nvim I get:
```
Error detected while processing VIMINIT:
E484: Can't open file /home/username/.config/nvim/init.vim
Press ENTER or type command to continue
```
but loading with `nvim -u $XDG_CONFIG_HOME/nvim/init.lua` opens with proper config.

**Comment by clason** [comment]
Please open a new issue with full(!) details.
