### ISSUE TITLE
Unable to build on OpenBSD

### ISSUE THREAD

**Issue by samebchase** [neovim/neovim#14709]
Hello, I am trying to build SHA `68d40388f356587726ea7db83f87846dfaecf9d9` on OpenBSD 6.9

I had to find a few libraries and add the CMake variables for them, so here's the command I tried:

```
cmake -DCMAKE_BUILD_TYPE="Release" -DLIBLUV_LIBRARY=/usr/local/lib/l
ua/5.1/ -DLIBLUV_INCLUDE_DIR=/usr/local/include/lua-5.1/ -DTreeSitter_LIBRARY=../tree-sitter/ -DTreeS
itter_INCLUDE_DIR=../tree-sitter/lib/include/ -S ../neovim/
```

The error I get is:

```
-- CMAKE_INSTALL_PREFIX=/usr/local
-- CMAKE_BUILD_TYPE=Release
-- MIN_LOG_LEVEL not specified, default is 3 (ERROR) for release builds
-- Replacing -O3 in CMAKE_C_FLAGS_RELEASE with -O2
-- Found TreeSitter
-- Found UNIBILIUM 2.1.0
-- Found LIBVTERM 0.1.2
-- Found Iconv
CMake Error at CMakeLists.txt:511 (message):
  Failed to find a Lua 5.1-compatible interpreter
```
which is surprising because I have both Lua and LuaJIT installed from the packages.

```
> which luajit51
/usr/local/bin/luajit51

> which lua51
/usr/local/bin/lua51
```

Would appreciate it if someone can give me some pointers as to what I can do to get this building.

Thanks in advance, and thanks for all the work in maintaining neovim. It's a great project. 💯

**Comment by jamessan** [comment]
Add `-DLUA_PRG=luajit51` to your cmake invocation.  `luajit51` and `lua51` aren't ["standard" names](https://github.com/neovim/neovim/blob/68d40388f356587726ea7db83f87846dfaecf9d9/CMakeLists.txt#L492) that we look for when trying to find a lua binary.
