### ISSUE TITLE
WORD motion via C-S-Space in Normal mode (does not happen in Vim)

### ISSUE THREAD

**Issue by mathstuf** [neovim/neovim#14700]
- `nvim --version`: 0.4.4
- Operating system/version: Fedora 33
- Terminal name/version: rxvt-unicode 9.26
- `$TERM`: tmux-256color

[x] `vim -u DEFAULTS` (version: 8.2.2875) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
ifoo bar baz<Esc>0
```

### Actual behaviour

Pressing `Ctrl+Shift+Space` jumps by WORDs (motion `W`)

### Expected behaviour

`vim` does not move the cursor.

Not complaining about the difference, just would like to know where it comes from so that it can either:

  - be fixed
  - documented as a difference and I can disable it

**Comment by jamessan** [comment]
Can you download the nightly appimage and see if that works better?  There were some fixes for key combos which may help.

>     * Terminal name/version: rxvt-unicode 9.26

Can you also try using some other terminal (maybe xterm)?  rxvt-unicode uses different escape codes than pretty much every other terminal emulator.

**Comment by mathstuf** [comment]
`xterm` with 0.4.4 has the same behavior. I compiled `master` locally and it is still happening in `rxvt-unicode` and `xterm`.

**Comment by bruhtus** [comment]
I've tried using nightly build on alacritty but `Ctrl-Shift-Space` doesn't trigger WORD motion. I also tried using xterm and `Ctrl-Shift-Space` indeed trigger WORD motion.

It's seem like a bug with only a certain terminal like urxvt and xterm. I'm not sure what's going on tho.

**Comment by jamessan** [comment]
If this is happening on newer Vim's but not old, then it's likely that the newer ones actually understand `<C-Space>`/`<S-Space>` as distinct from `<Space>`.

Any of the "right" motions will move by a word when combined with Ctrl or a WORD when combined with Shift:

https://github.com/neovim/neovim/blob/93f15db5d61800a2029aa20684be31c96ebcca5b/src/nvim/normal.c#L5149-L5155

https://github.com/vim/vim/blob/b55d618f193d9f413612d8d4e62758056e842e46/src/normal.c#L3991-L3998

The behavior is documented for `<Right>` and `<Left>` under `:help word-motions`, and it happens that `<Space>` uses the same code path.

**Comment by jamessan** [comment]
You can verify this by typing <kbd>C-v</kbd><kbd>C-S-Space</kbd> in insert mode when running nvim in various terminal emulators and seeing what gets inserted.  The terminals where you see a space inserted won't exhibit the word motion, but the ones that show `<C-S-Space>` will.

**Comment by mathstuf** [comment]
Hmm. I see `<C-Space>` and the WORD motion still happens for me.

**Comment by mathstuf** [comment]
Ah, `vim` shows `^@`, so it just doesn't understand it. Alas, there's no explicit mapping for this, so `mapc` or `unmap` fails. Is there a safe "do nothing" target I can bind the key to instead?

**Comment by jamessan** [comment]
`noremap <C-Space> <nop>`
