### ISSUE TITLE
Can't use '~' with the bépo keyboard disposition

### ISSUE THREAD

**Issue by franckspike** [neovim/neovim#14702]
- `nvim --version`: v0.5.0-828
- Operating system/version: Win 10 x64
- Terminal name/version: nvim-qt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
using bépo keyboard disposition https://bepo.fr/wiki/Accueil

nvim-qt -- -u NORC

try inserting the ~ character: done using a dead key combination: AltGr-; AltGr-;
 ; here represents the qwerty (physical) ; key
thinking in the bépo disposition, the ; physical key gives n so the bépo combination is rather named: AltGr-n AltGr-n
(just press AltGr-; AltGr-; on the physical keyboard)

the same happens on a : command or / search

note that nvim works properly, only nvim-qt has this problem

I'm pretty sure other dead key combinations should also cause such a problem
```

### Actual behaviour

~ won't appear is it should
doing the combination 3 times types something weird and is not a simple ~ character

### Expected behaviour

this combination twice should just give a single ~ character

**Comment by clason** [comment]
Does this happen in terminal nvim as well? Otherwise it's a neovim-qt bug that should be reported upstream: https://github.com/equalsraf/neovim-qt

**Comment by franckspike** [comment]
Oh !  Good then, it is neovim-qt specific !  Thank you!

**Comment by franckspike** [comment]
For reference I opened: https://github.com/equalsraf/neovim-qt/issues/864
