### ISSUE TITLE
How to tell what Python Binary Neovim is Using

### ISSUE THREAD

**Issue by fishbotics** [neovim/neovim#14714]
Hi,

I'm using Neovim on a mac. I also use Pyenv for Python version management and venv for virtual environment management. I'm running into an issue where Neovim can't seem to find some of my plugins. I suspect it has to do with the Python setup. Is there a way to tell which Python binary Neovim is looking in? I previously had installed everything correctly, but now they seem to be missing. I'm guessing something is minconfigured and Neovim is referencing my active Python environment instead of the Global one. 

What I'd really like to be able to do is specify a specific Python binary for Neovim where I can have all my neovim stuff and not have it conflict with any of the rest of my system Python.

Thanks!
-Adam

**Comment by KillTheMule** [comment]
Run `:checkhealth`, and read `:h provider-python`.

**Comment by glacambre** [comment]
To answer the second part of your question, you can use `:help g:python3_host_prog` to choose what python binary neovim will use.

Question answered, let's close this issue :)
