### ISSUE TITLE
stack smashing detected under kitty when pressing Ctrl+Keypad key

### ISSUE THREAD

**Issue by pattop** [neovim/neovim#14718]
- `nvim --version`:
<pre>NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info</pre>

- Operating system/version:

`Arch Linux`

- Terminal name/version:

`kitty 0.20.3`

- `$TERM`:

`xterm-kitty`

### Steps to reproduce using `nvim - u NORC`

```
kitty nvim -u NORC
press Ctrl+Keypad-1
```

### Actual behaviour

`*** stack smashing detected ***: terminated`

### Expected behaviour

No stack smashing :)

**Comment by glacambre** [comment]
Can you reproduce with [neovim nightly](https://github.com/neovim/neovim/releases)?

**Comment by pattop** [comment]
I can't reproduce with `NVIM v0.5.0-dev+1384-gf2906a466` so it looks like the issue has already been fixed.

Sorry for the noise.
