### ISSUE TITLE
Unexpected opening quickfix-list

### ISSUE THREAD

**Issue by timsofteng** [neovim/neovim#14713]
Hello. I use `typescript-language-server` with native `lsp`.
When I'm trying to go to definition it works but it also opens quickfix-list with two files with right one and another strange file something like that
`node_modules/@types/react/index.d.ts|547 col 9| (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;`

how can i fix it?

![image](https://user-images.githubusercontent.com/51912173/120679466-e07d0300-c4a1-11eb-9c43-4887cf8839c8.png)

NVIM v0.5.0-dev+1372-g056c464e8
Debian testing
alacritty:
tmux-256color:

**Comment by mjlbach** [comment]
This is the expected behavior, the server is returning multiple definition locations so we show you both. If you want to change this, you'll have to override the handler (I don't have a snippet to do this).

**Comment by timsofteng** [comment]
> This is the expected behavior, the server is returning multiple definition locations so we show you both. If you want to change this, you'll have to override the handler (I don't have a snippet to do this).

Look at the file please. There is no definition in first file which I looking for. I'm trying to go to `UsageAndPlan` component.

**Comment by mjlbach** [comment]
It doesn't matter, tsserver is reporting multiple server results, one I assume is from your user installed node modules (the first one). File an upstream bug with tsserver if you are unhappy with the results returned.

**Comment by timsofteng** [comment]
> It doesn't matter, tsserver is reporting multiple server results, one I assume is from your user installed node modules (the first one). File an upstream bug with tsserver if you are unhappy with the results returned.

Got it. I have opened issue in server's repo.
