### ISSUE TITLE
LSP semantic token support

### ISSUE THREAD

**Issue by NickeZ** [neovim/neovim#14711]
Hello,

what version of LSP is supported in the neovim client and is there already work being done on supporting [semantic tokens](https://microsoft.github.io/language-server-protocol/specification#textDocument_semanticTokens)?

Thank you for your efforts!

**Comment by mjlbach** [comment]
I want to say "3.15", we have call hierarchy support (3.16). There's an open PR for semantic tokens https://github.com/neovim/neovim/pull/14122

**Comment by theHamsta** [comment]
There is an open but unfinished PR https://github.com/neovim/neovim/pull/14122/files

**Comment by NickeZ** [comment]
Cool, thanks!
