### ISSUE TITLE
Lua plugins using vim.o no longer work with nightly

### ISSUE THREAD

**Issue by ovidiu-ionescu** [neovim/neovim#14727]
On neovim nightly plugins accessing vim.o get the following error:

```
attempt to index field 'o' (a nil value) 
```

Same issue for vim.wo

**Comment by clason** [comment]
Sounds like a duplicate of https://github.com/neovim/neovim/issues/14662 (make sure to `make distclean` before and `make install` after building.)

**Comment by ovidiu-ionescu** [comment]
`make install` seems to have solved it

Thanks Christian!
