### ISSUE TITLE
Neovim ruins shell commands when using powershell on Windows 10

### ISSUE THREAD

**Issue by k2s09** [neovim/neovim#14725]
- `nvim --version`: v0.4.4
- Operating system/version: Windows 10, 20H2 April Update
- Terminal name/version: Windows Terminal, 1.8.1444.0 / May 25, 2021 (Stable)
- `$TERM`: --

### Steps to reproduce using `nvim -u NORC`
Actually, this can't be done using NORC, but I have tried this with `nvim` with just the three lines required for this issue.

```
nvim
:help powershell
Copy the lines below "To use powershell (on Windows)"
Open init.vim (I did echo stdpath('config') and then went to the directory and then opened it)
Paste lines
Save by doing :w
Open nvim again or do :source %
Now do any shell command like :!ls
```

### Actual behaviour
When I do any shell command like `:!ls`, Nvim puts `(` before and after the command and then executes it in the shell, which gives an error. Doing `:!ls` gives - 

```
:!(ls(
An expression was expected after '('.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpression


shell returned 1
```

### Expected behaviour
When doing any command, it should be executed in Powershell properly. To note, this problem does not occur using default settings. When shell is command prompt, the commands work as expected.

**Comment by 3N4N** [comment]
Seems to have been fixed.  Doc for `:h shell-powershell` has changed a few times since this ticket was filed, but the most relevant change was in https://github.com/neovim/neovim/commit/8b0765390292.
