### ISSUE TITLE
When displaying LSP underlines for diagnostics, (optionally) skip underlines for leading whitespace

### ISSUE THREAD

**Issue by YorickPeterse** [neovim/neovim#14720]
When a LSP diagnostic is displayed, the offending text can be highlighted (e.g. by using an underline). Somewhat annoyingly, when a diagnostic spans multiple lines, leading whitespace is also highlighted. This looks like this:

![Screenshot from 2021-06-03 23-26-09](https://user-images.githubusercontent.com/86065/120796254-e7a41f80-c53a-11eb-87f6-842624455e11.png)

Perhaps this is a matter of personal taste, but this looks quite jarring. Using a background or foreground color instead of an underline has its own drawbacks: using a foreground color you lose details about the syntax. Using a background color has the same issues as the underline approach. It may also be tricky to find a background color that works for all other colors in your colorscheme.

Would it be possible to somehow extend the LSP integration so leading whitespace isn't highlighted? That way it would end up looking something like this:

![fixed](https://user-images.githubusercontent.com/86065/120796579-449fd580-c53b-11eb-9586-b2186cee5699.png)

See also [this Reddit post](https://www.reddit.com/r/neovim/comments/nromix/highlight_lsp_diagnostics_without_also/) where I asked about this, but sadly didn't get any answers on how to best approach this.

**Comment by mjlbach** [comment]
I can't reproduce this. Which language server is this? Can you send a file which reproduces this? 

<img width="423" alt="image" src="https://user-images.githubusercontent.com/13316262/120824187-0ab7da80-c50d-11eb-85ff-6d784615cfd4.png">

**Comment by YorickPeterse** [comment]
@mjlbach rust-analyzer does this for certain diagnostics. For example:

```rust
macro_rules! unused_macro {
    ($name: expr) => {
        $name
    };
}

fn main() {}
```

Here things will be highlighted like so:

![Screenshot from 2021-06-04 17-43-28](https://user-images.githubusercontent.com/86065/120828075-63fb2a80-c55c-11eb-888b-7e344310e48f.png)

With that said, this isn't unique to rust-analyzer. For example, I have a custom tool that displays [RuboCop](https://rubocop.org/) diagnostics using the NeoVim LSP integration. RuboCop at times also produces multi-line diagnostics, resulting in similar highlighting as rust-analyzer.

**Comment by mjlbach** [comment]
I still can't reproduce:

<img width="619" alt="image" src="https://user-images.githubusercontent.com/13316262/120828455-65533580-c511-11eb-9454-319af46e4015.png">

The only diagnostics I get also seem to match this
```
[ DEBUG ] 2021-06-04T08:48:13-0700 ] ...-unwrapped-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:491 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = "unlinked-file",        codeDescription = {          href = "https://rust-analyzer.github.io/manual.html#unlinked-file"        },        message = "file not included in module tree",        range = {          end = {            character = 3,            line = 0          },          start = {            character = 0,            line = 0          }        },        severity = 4,        source = "rust-analyzer"      } },    uri = "file:///Users/michael/Repositories/neovim_development/language_server_tests/test_rust_project/src/test2.rs",    version = 0  }}
[ DEBUG ] 2021-06-04T08:48:13-0700 ] ...ovim-unwrapped-master/share/nvim/runtime/lua/vim/lsp.lua:679 ]	"notification"	"$/progress"	{  token = "rustAnalyzer/Indexing",  value = {    kind = "end"  }}
[ DEBUG ] 2021-06-04T08:48:13-0700 ] ...apped-master/share/nvim/runtime/lua/vim/lsp/handlers.lua:434 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = "rustAnalyzer/Indexing",    value = {      kind = "end"    }  }}
[ DEBUG ] 2021-06-04T08:48:13-0700 ] ...ovim-unwrapped-master/share/nvim/runtime/lua/vim/lsp.lua:679 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = { {      code = "unlinked-file",      codeDescription = {        href = "https://rust-analyzer.github.io/manual.html#unlinked-file"      },      message = "file not included in module tree",      range = {        end = {          character = 3,          line = 0        },        start = {          character = 0,          line = 0        }      },      severity = 4,      source = "rust-analyzer"    } },  uri = "file:///Users/michael/Repositories/neovim_development/language_server_tests/test_rust_project/src/test2.rs",  version = 0}
```

**Comment by mjlbach** [comment]
I can't reproduce, my underlines look fine.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/13316262/120829363-2bcefa00-c512-11eb-80c2-b8a3ec3b4338.png">

**Comment by YorickPeterse** [comment]
@mjlbach You seem to have indent lines enabled, perhaps those somehow cancel out the highlighting? My highlight groups are like this:

```
:hi LspDiagnosticsUnderlineError
LspDiagnosticsUnderlineError xxx gui=underline guisp=#cc3e28
:hi LspDiagnosticsUnderlineWarning 
LspDiagnosticsUnderlineWarning xxx gui=underline guisp=#b58900
```

**Comment by YorickPeterse** [comment]
Assuming you're using https://github.com/lukas-reineke/indent-blankline.nvim/tree/lua, that indeed seems to overwrite the highlighting of leading whitespace:

![Screenshot from 2021-06-04 20-54-33](https://user-images.githubusercontent.com/86065/120849964-1c35cc80-c577-11eb-88f8-1f477977051a.png)

Here I set the indent guide color to red.

So I guess this _could_ be a workaround, but only if you actually want to use an indent guide plugin.

**Comment by mjlbach** [comment]
Ah yes, I see what you're asking for. We are correctly highlighting the returned range (which from the language server includes the blankspace), but maybe we could (at least provide a guide) for highlighting only text in that range, not blankspace. I'm a bit concerned that there might be language servers which intend for blankspace to be highlighted (like overindentation for example).

**Comment by YorickPeterse** [comment]
@mjlbach Yeah there definitely are cases where whitespace does matter, e.g. in Python and Makefiles. Maybe it could be an option set per language server?

**Comment by folke** [comment]
@mjlbach we definitely need to keep highlighting whitespace. Linters for formatting or Python code for example.

**Comment by mjlbach** [comment]
I'm going to say that this is a feature that could be offered as a plugin, but not a feature that should be in the core client until language servers offer more granular highlight options. There's no way we can write a set of rules to distinguish between highlighted leading blankspace that has, or does not have, semantic relevance (python as @folke pointed out). A plugin is welcome to override the default behavior, and if you're interested in addressing this upstream by filing an RFC for the language server protocol 

Also, for reference, vscode shows the same behavior we do:
![image](https://user-images.githubusercontent.com/13316262/121122990-51405a00-c7d7-11eb-86cc-e0f5f3be6f46.png)
