### ISSUE TITLE
language server client does not respect markupkind plaintext

### ISSUE THREAD

**Issue by dimbleby** [neovim/neovim#14746]
- `nvim --version`: nvim --version
NVIM v0.5.0-dev+1384-gf2906a466-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/dch/neovim/build/config -I/home/dch/neovim/src -I/home/dch/neovim/.deps/usr/include -I/usr/include -I/home/dch/neovim/build/src/nvim/auto -I/home/dch/neovim/build/include
Compiled by dch@DESKTOP-NA4O3IV

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/dch/.local/nvim/share/nvim"

Run :checkhealth for more info
- Operating system/version: Ubunto 20.04
- Terminal name/version: wsltty
- `$TERM`: tmux-256color

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour

Hover text is presented as markdown even though the server declared that it was plaintext.

### Expected behaviour

plaintext should be presented as plain text.

I am using a python language server.  Python conventions
- do not write comments in markdown
- do make heavy use of `snake_case` and `__dunder__` methods and suchlike

The server does not attempt to escape everything and so I have configured it to return hover etc with kind `plaintext`.

But the neovim language client presents it as markdown anyway.  This is annoying because eg the markdown syntax insists that an underscore in the middle of a word (method name) is an error, and tries to present `__foo__` as __foo__ , and so on.

cf https://github.com/pappasam/jedi-language-server/issues/144#issuecomment-856445819

**Comment by mjlbach** [comment]
@folke we should probably check here https://github.com/neovim/neovim/blob/cabf8ab26b21c295355b8024ad6533fe0a675c5e/runtime/lua/vim/lsp/handlers.lua#L268 if it's plaintext and avoid calling any markdown parsing

**Comment by folke** [comment]
I'll check. Also needs to change in other places like signature_help I think.

**Comment by mjlbach** [comment]
Oh can you not assign yourself yet? Done.

**Comment by folke** [comment]
@mjlbach can't do it myself. thanks!
