### ISSUE TITLE
Fix vim_strchr() duplication

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#1474]
It seems to me like the final part of `vim_strchr()`:

``` c
  while ((b = *p) != NUL) {
    if (b == c)
      return p;
    ++p;
  }
  return NULL;
}
```

Is more or less the same as `vim_strbyte()`:

``` c
char_u *vim_strbyte(char_u *string, int c)
{
  char_u      *p = string;

  while (*p != NUL) {
    if (*p == c)
      return p;
    ++p;
  }
  return NULL;
}
```

So I propose that `vim_strchr()` just calls `vim_strbyte()` in its tail. NONNULL function attributes should also be added. For a reference: https://gcc.gnu.org/ml/gcc-patches/2001-11/msg01628.html

This is an entry level issue.

**Comment by Yamakaky** [comment]
close ?

**Comment by justinmk** [comment]
Why?

**Comment by Yamakaky** [comment]
Oh sorry, #2848 is closed so I thought this one too.

**Comment by nyeecola** [comment]
So, it appears to me that its taking way longer than expected to address #1476. Would it be okay for me to implement a fix for this again and try to actually get this merged? Or should we just wait for #1476?

**Comment by justinmk** [comment]
I don't know why @aktau left https://github.com/neovim/neovim/issues/1476 open for interpretation instead of just implementing it. So far we have people coming and asking for advice on how to proceed, when the only thing we actually need is for someone to do the analysis and answer the question of how to proceed. There is no work to be done except to analyze and answer the question of how to proceed. Proceeding per second is not the actual task. Deciding how to proceed is the task.

**Comment by aktau** [comment]
I'm sorry for letting this drop by the wayside so long ago, it's understandable you're miffed. I can't remember, but I'd guess that at the time I didn't do these things myself because I wanted to let others contribute.

**Comment by jamessan** [comment]
I don't see why this issue can't be addressed while whatever investigation needs to be done for #1476 happens.  #1489 looked like it was handling this, but then got bogged down in also trying to address #1476, which is a separate matter.

**Comment by justinmk** [comment]
Not miffed, I just want to make things exxxxtra clear since previous attempts have failed.

**Comment by aktau** [comment]
@justinmk OK :).

@jamessan Yes, it can be done fully separately, and probably should be. I think one of the reasons some attempts have bogged down were because I was interested in the performance impact of this change, so I (unjustly) withheld LGTM based on that. If I'm being honest with myself though, we know that this will have a positive (non-zero) impact, and that may already be enough, without quantifying how much exactly. If I was so interested, I should've done it myself.

**Comment by arkaray** [comment]
vim_strchr() has been modified to use standard strchr(). Instead vim_strrchr() (purpose not clear since vim_strchr() handles the general case) has a similar problem.

**Comment by justinmk** [comment]
Addressed by https://github.com/neovim/neovim/pull/6460. And 171baaee93c8 removed `vim_strbyte`.
