### ISSUE TITLE
Vim inheritance tiny bug related to greek language

### ISSUE THREAD

**Issue by SpyrosMourelatos** [neovim/neovim#14750]
This vim bug also appears in neovim I think it has to do with mkspell 
https://github.com/vim/vim/issues/299

**Comment by SpyrosMourelatos** [comment]
Vim fixed it.I am closing this issue but I would like to open a conversation about capitalization of the greek "sigma" on the other functions like `VU` on a line and then `Vu` and also `~~`(twice purposefully)  on a "σ" and `~~` on a "ς"if anyone is interested

**Comment by clason** [comment]
Just like the original bug, this discussion should be had on vim/vim; we'll port any fixes they make.

**Comment by sotirismorf** [comment]
Are there any updates on the bug? I saw there was a commit by @janlazo that didn't pass a test but after that nothing. Seems like vim/vim has fixed it.

**Comment by clason** [comment]
Do you have a link to the Vim patch?

**Comment by sotirismorf** [comment]
I couldn't find the patch but i read [this thread](https://github.com/vim/vim/issues/299#issuecomment-859723402)

**Comment by lerooze** [comment]
> Do you have a link to the Vim patch?

Here is the [patch](https://github.com/vim/vim/commit/4f135275984722c1b1e9ace72eeeb7ce7e4ec983)

**Comment by zeertzjq** [comment]
Then it seems already fixed.

**Comment by panosz** [comment]
I understand that in vim it is fixed and that there is a vim patch for it, but I am still experiencing the same problem in neovim, as described in the original vim [issue](https://github.com/vim/vim/issues/299).

Has the patch been applied to neovim?

**Comment by sotirismorf** [comment]
> I understand that in vim it is fixed and that there is a vim patch for it, but I am still experiencing the same problem in neovim, as described in the original vim [issue](https://github.com/vim/vim/issues/299).
> 
> Has the patch been applied to neovim?

https://github.com/vim/vim/issues/299#issuecomment-1725491044

"The issue is fixed, but the spell file for greek language has not yet been updated on the"

The Makefile this person recommends works perfectly. You can generate, `el.utf-8.sp` and `el.utf-8.sug` using the Makefile and then move them to `~/.config/nvim/spell/`. It should work perfectly (at least it does for me)
