### ISSUE TITLE
Option to hide nesting level denoted with numbers when `foldcolumn` is narrow

### ISSUE THREAD

**Issue by sudormrfbin** [neovim/neovim#14751]
- `nvim --version`: v0.5.0-dev+1342-gde96626ad

From `:h fold-foldcolumn`:

```
Where the fold column is too narrow to display all nested folds, digits are
shown to indicate the nesting level.
```

Is there any way to disable the numbers showing up ? With `:set fillchars+=foldopen:\ ,foldsep:\ ,foldclose:` (i.e. show an indicator only if there are folded lines, à la vscode if you will) and `:set foldcolumn=1` this is how it looks:

![Screenshot_2021-06-08_22-48-46](https://user-images.githubusercontent.com/23398472/121229527-b49bbc00-c8ab-11eb-98fe-47a4e74c8623.png)

It's also very distracting placed next to the number column (the current line in the screenshot is actually 83; the 3 in front is showing the nested folding level).

**Comment by andersevenrud** [comment]
I was looking up how to hide these nesting level numbers and came across this issue.

Took a stab at this here: https://github.com/neovim/neovim/pull/17446

Seems to work, but I'm not very confident in my work :sweat_smile:

**Comment by justinmk** [comment]
'statuscolumn' provides full control over the fold/sign/number column. https://github.com/neovim/neovim/pull/20621

**Comment by lewis6991** [comment]
I'm not sure if `statuscolumn` in its current incantation provides a solution to this.

**Comment by luukvbaal** [comment]
I think it is but you would need a non-trivial plugin that places the fold markers instead of using the `%C` fold column item.

**Comment by CatHood0** [comment]
Just see this commnet. It fixes this for me: https://github.com/kevinhwang91/nvim-ufo/issues/92#issuecomment-2241150524
