### ISSUE TITLE
VimL styleguide for writing runtime code

### ISSUE THREAD

**Issue by rainerborene** [neovim/neovim#1475]
Just like what we have for C language on the wiki page I think it is important to have consistency across the `runtime` code base, like namespaces (`provider#clipboard#set`) and private functions (`s:get_clipboard`) should be lowercase, and so on. Inpiration: https://github.com/styleguide/ruby

**Comment by justinmk** [comment]
https://github.com/Kuniwak/vint is a new vimscript linter that so far has produced good results for me.

**Comment by ZyX-I** [comment]
@dbarnett 

I think it is good idea to save my [replies](https://gitter.im/neovim/neovim?at=5765a9cdf0528c4c5bba46a7) in gitter here:

> `ZyX-I` When writing shada.vim set of files I looked at maktaba source and did something similar. But documentation in runtime/doc was not generated, I also treated such comments as “doxygen for VimL” (i.e. source code documentation for developers, not user documentation).

> `ZyX-I` l: prefix is a thing I never followed, it makes code less readable and if you can make linter check that you are not omitting g: prefix (outside of functions) this does not make much sense either.

> `ZyX-I` Basically the only argument for this I know is that you will not accidentally use global scope instead (which is actually likely should you e.g. write cycles to initialize some global variable). Interesting, this argument is *not* listed in Google style guide, while there are four more subjectable ones (“good practice”: it is you saying good, not me; “help remember about scope”: your code will not work if you forget this; “predefined variables”: there are *five* (search for VV_COMPAT), they are there for historical reasons (“…COMPAT”: Vi compatibility) and nobody is planning on adding any more (and I have only ever hit two of them: count and version)).

> `ZyX-I` Also don’t think that using scope will prevent you from hitting some kind of predefined variables: there is `b:changedtick`, but there is no `b:['changedtick']`: it is the kind of predefined variable which internally is not even kept in *any* scope at all, there are only some checks here and there like “b:changedtick? do this: do else”.

**Comment by ZyX-I** [comment]
Though I am wrong about *Vi* compatibility, vi does not have +eval. It is compatibility with previous versions that did not have v: to store such variables in.

**Comment by wsdjeg** [comment]
thanks for the link，vim-maktaba is what I need.

**Comment by justinmk** [comment]
For new runtime code, `:help dev-lua` is where patterns/practices are documented. And style is defined by the `lintlua` build target.

Don't need a Vimscript style guide because most Nvim-owned runtime files are in Lua.
