### ISSUE TITLE
Screen seems to tear when using xterm

### ISSUE THREAD

**Issue by Kronifer** [neovim/neovim#14755]
- `nvim --version`:
 ```
VIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
- Operating system/version: Arch Linux
- Terminal name/version:  XTerm(368)
- `$TERM`: Opens a new window of XTerm

### Steps to reproduce using `nvim -u NORC`
You can't, it seems that xterm does not like my colorscheme.

### Actual behaviour
The screen doesn't refresh and i get image tearing.
![image](https://user-images.githubusercontent.com/44979306/121259513-d7ab7900-c875-11eb-845f-39fadea29534.png)

### Expected behaviour
The screen shouldn't tear.

**Comment by bew** [comment]
> You can't, it seems that xterm does not like my colorscheme.

Try to load your colorscheme to try to reproduce then?

**Comment by timtyrrell** [comment]
sounds a bit like this? https://github.com/neovim/neovim/issues/14434#issuecomment-846458263

**Comment by glacambre** [comment]
@Kronifer does this happen on master/with neovim nightly?

**Comment by Davincible** [comment]
@glacambre To answer that question, I am experiencing the same on `NVIM v0.6.0-dev+13-ga6cdfa27d`

**Comment by zeertzjq** [comment]
Does this bug still exist?
