### ISSUE TITLE
Neovim can't load init.lua config

### ISSUE THREAD

**Issue by arpangreat** [neovim/neovim#14768]
I just installed nvim.Appimage and it can't loadout `init.lua` config file , which symlinked from my dotfiles to the default `$HOME/.config/nvim/` 

`:checkhealth` gives me an error that init.vim not found and My Neovim looks like this ...

![Screenshot from 2021-06-11 01-27-28](https://user-images.githubusercontent.com/46556080/121589025-39c1d500-ca54-11eb-8611-c11ee0ad9ef8.png)

please help me ...

My dotfiles can be found here https://github.com/arpangreat/dotfiles

**Comment by clason** [comment]
Then I am afraid you need to put in a bit of work to pear this down to a more minimal example and add a lot more information about your setup. (Symlinking `init.lua` into my config directory gets it picked up just fine.)

**Comment by arpangreat** [comment]
Okay so I use Lua for my configuaration file , I do use dashboard.nvim , and galaxyline.nvim . I can assure that there is not brokage on my config because it was just working fine before updating in new version.

It was before the update ...
![120155264-418ca880-c20e-11eb-97c2-a265160ca5f0](https://user-images.githubusercontent.com/46556080/121591238-dd13e980-ca56-11eb-84b5-02d8256e1b2a.png)

And now it became like this ...
![Screenshot from 2021-06-11 01-27-28](https://user-images.githubusercontent.com/46556080/121591319-f74dc780-ca56-11eb-9651-7bdfe6fc200d.png)


also I have a lua directory where I have my mappings , sets , other configs file for  telescope, nvim-compe etc . And those aren't working too . I don't know happened . And also fun fact checkhealth gives me an WARNING for not having config file for nvim . as init.vim
![Screenshot from 2021-06-11 01-51-24](https://user-images.githubusercontent.com/46556080/121591842-97a3ec00-ca57-11eb-85fe-7e54ad4e115b.png)

**Comment by clason** [comment]
We don't know, either, without some (but not too much) details... Nobody is going to go through your dot file repo line by line looking for clues.

**Comment by arpangreat** [comment]
I told every single fucking details that cause trouble with screenshots and still If you think any other information is needed , you can call it out for that.

And I clearly didn't tell to read my dotfiles line by line to anybody. 

So stop being rude , help if you want to , if you don't , just stop giving shit comments .

It's frustrating for me rn , I am neovim lover and I have so much work to do but neovim is broken.

I hope I made it clear

**Comment by clason** [comment]
> I hope I made it clear

Crystal clear.

**Comment by mjlbach** [comment]
@arpangreat I strongly suggest you watch your tone and language, and consider the impact publicly posting such content will have when employers look at it.

**Comment by arpangreat** [comment]
Sorry for using rude words @clason 

hope you will understand right now

**Comment by arpangreat** [comment]
> @arpangreat I strongly suggest you watch your tone and language, and consider the impact publicly posting such content will have when employers look at it.

Absoulutely I agree with that , I am just frustrated rn 

I am Sorry to all of you

**Comment by arpangreat** [comment]
So ran through all my config files rn again, as of now nothing is broken on configs ... nor inside init.lua .

this is my linking status iside my $HOME/.config
![Screenshot from 2021-06-11 02-27-32](https://user-images.githubusercontent.com/46556080/121596121-ac36b300-ca5c-11eb-94e3-703ec3c2d710.png)


FYI , I tried nvim.AppImage , I tried installing neovim-git AUR package also I build it from source but It's not working

**Comment by bfredl** [comment]
> I just installed nvim.Appimage and it can't loadout init.lua config file , which symlinked from my dotfiles to the default $HOME/.config/nvim/

this is the "after" but what was the "before"? another appimage? a distro package?

**Comment by arpangreat** [comment]
It was a build from source , with all deps and no errors

and The after is updating till the latest commit

**Comment by bfredl** [comment]
roughly what time? if you don't remember exactly, are we talkning days, weeks or months?

**Comment by arpangreat** [comment]
> roughly what time? if you don't remember exactly, are we talkning days, weeks or months?

maybe a week ago , when I updated neovim from source , after that everything was going fine too

**Comment by arpangreat** [comment]
> I dont know about appImage but there was some other comment saying it needs special care for dotfiles. You are probably better trying something else out.

Yeah I'm actually going through every possibilties and checking out evey article 

would you mind if you can remember where you read it ?

**Comment by bfredl** [comment]
so, if you check out a week-ish old commit again, everything works fine? In that case, we could try a `git bisect` .

**Comment by arpangreat** [comment]
> so, if you check out a week-ish old commit again, everything works fine? In that case, we could try a `git bisect` .

That's a great idea ...

**Comment by mjlbach** [comment]
> 
> 
> I dont know about appImage but there was some other comment saying it needs special care for dotfiles. You are probably better trying something else out.

I thought this was for the flatpak

**Comment by arpangreat** [comment]
Interesting thing I fallback to a really old commit https://github.com/neovim/neovim/commit/27fb03f5a03db6738967f9e0e0ea85ea0fab7592

And Now Neovim is working fine ... strange

**Comment by shaunsingh** [comment]
I'm using both neovim --HEAD and luajit --HEAD on macOS, and can't reproduce this issue. Your config seems just fine as well.

**Comment by arpangreat** [comment]
Yeah , maybe it is a runtime issue or something else , I have been brainstorming this issue for one day and still going on 😀

**Comment by featheryus** [comment]
I have a similar issue, after analyze, I find nvim gets the wrong value by $HOME.
for my issue, $HOME is "/root" in vim, but it's "/home/root" in nvim, so nvim can't load all plugins in $HOME "/root/"

**Comment by arpangreat** [comment]
closing this issue , as I fixed it ❤️😄
