### ISSUE TITLE
research replacing vim_strbyte() with standard strchr()

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#1476]
Vim has its own implementation of `strchr()` (slightly altered semantics) called `vim_strbyte()`. I'd like to research together with any volunteers whether we can revert that to be more based on `strchr()`.

Would-be advantages of `strchr` over `vim_strbyte()`:
- It's often over 4x faster because it uses vector operations on our target platforms
- Less custom code

Proposed reasons why Bram didn't use `strchr()`:
- Perhaps some platforms had really funky strchr()'s
- Something I didn't think of, more research required

`vim_strbyte()`'s code and comments:

``` c
/*
 * Version of strchr() that only works for bytes and handles unsigned char
 * strings with characters above 128 correctly. It also doesn't return a
 * pointer to the NUL at the end of the string.
 */
char_u *vim_strbyte(char_u *string, int c)
{
  char_u      *p = string;

  while (*p != NUL) {
    if (*p == c)
      return p;
    ++p;
  }
  return NULL;
}
```

This seems to imply that `strchr()` has problems with characters above 128. The [docs for strchr](http://pubs.opengroup.org/onlinepubs/009695399/functions/strchr.html) mention that the input argument `c` is converted to a char. So supplying an integer between [128-255] should yield a negative char. Above that, it wraps around again (check C standard). This is the main difference between `vim_strbyte()` and `strchr()`. `vim_strbyte()` _never_ converts its argument to `char`.

A program I've been using to test these implementations' reactions to all sorts of input: https://gist.github.com/aktau/11975b15dfb8d5504a58

Conclusions for now:

It seems `strchr()` and `vim_strbyte()` start to react differently only when `c` >= 255 is passed, not `c` >= 128 as implied by the docs. We now need to research whether this is relevant. Cursory grepping through the source tree for `vim_strchr()` and `vim_strbyte()` informs me that in the grand majority of cases a `char` is passed to these functions. Since a `char` is bounded between 0 and 255, that makes `strchr()` and `vim_strbyte()` mostly equivalent.

Links up a bit with issue #1474 

**EDIT**: I've created a function based on `strchr()` that in my tests completely emulates `vim_strbyte()`:

``` c
/* a wrapper around strchr that brings it more in line with vim_strbyte(), commented version */
char *akt_strbyte(const char *str, int c) {
  if (c == 0) {
    return NULL; /* Vim prefers returning NULL instead of the end of string */
  }

  if (c > (unsigned char) -1) {
    /* vim_strbyte() never casts c to int, which means that if c >= 255, it
     * simply never matches and will always return NULL, but not before
     * running through the entire string first. We emulate this behaviour by
     * just returning NULL immediately. */
    return NULL;
  }

  return strchr(str, c);
}

/* short version */
char *akt_strbyte_short(const char *str, int c) {
  return (c > 0 && c <= (unsigned char) -1) ? strchr(str, c) : NULL;
}
```

**EDIT2**: benchmarks show the `strchr()` wrapper to be quite a bit faster

```
benchmarking finding a needle in a short string: 255 chars, 65536 rounds
chr:    14.73 ns per call, akt_strbyte_short, nulls counted = 255
chr:    13.27 ns per call, akt_strbyte, nulls counted = 255
chr:    12.84 ns per call, strchr, nulls counted = 0
chr:   123.78 ns per call, vim_strbyte, nulls counted = 255
int:     0.96 ns per call, akt_strbyte_short, nulls counted = 65280
int:     1.13 ns per call, akt_strbyte, nulls counted = 65280
int:    12.36 ns per call, strchr, nulls counted = 0
int:   203.81 ns per call, vim_strbyte, nulls counted = 65280
benchmarking finding a needle in a longer string: 262143 chars
chr:    25.31 ns per call, akt_strbyte_short, nulls counted = 255
chr:    23.45 ns per call, akt_strbyte, nulls counted = 255
chr:    96.49 ns per call, strchr, nulls counted = 0
chr:  1168.29 ns per call, vim_strbyte, nulls counted = 255
int:     1.02 ns per call, akt_strbyte_short, nulls counted = 65280
int:     1.24 ns per call, akt_strbyte, nulls counted = 65280
int:    89.16 ns per call, strchr, nulls counted = 0
int: 211970.09 ns per call, vim_strbyte, nulls counted = 65280
benchmarking finding a needle that's usually not there: 262143 chars
int:   125.05 ns per call, akt_strbyte_short, nulls counted = 65534
int:   105.50 ns per call, akt_strbyte, nulls counted = 65534
int: 19511.74 ns per call, strchr, nulls counted = 65024
int: 215712.53 ns per call, vim_strbyte, nulls counted = 65534
```

**Comment by a1lu** [comment]
@aktau i tried ur tool and got strange results
http://pastebin.com/AjWYU6Q3

The last benchmark test failed for strchr and vim_strbyte. 
I get the same long times for each function but vim_strbyte if i benchmark a needle that is usually not there with use_chars

i do some more tests

**Comment by jamessan** [comment]
> Since a char is bounded between 0 and 255, that makes strchr() and vim_strbyte() mostly equivalent.

This is false.  A `char` can be either signed or unsigned, depending on the platform, so it's only safe to use for values [0, 128).  That's why Vim has its own implementation.

**Comment by ZyX-I** [comment]
This is also why I have `(uint8_t)` casts in a number of places where I replace `char_u` with `char`. When doing the replacement if you pass something potentially non-ASCII you will have to do the same thing. I think that should be safe if you replace `vim_strbyte` with

```C
#include <limits.h>
#include "nvim/func_attr.h"
static inline char *strchr_checked(const char *const s, const int c)
  REAL_FATTR_PURE REAL_FATTR_NONNULL_ALL REAL_FATTR_WARN_UNUSED_RESULT
  REAL_FATTR_ALWAYS_INLINE;
static inline char *strchr_checked(const char *const s, const int c)
{
  assert(0 <= c && c <= UCHAR_MAX);
  return strchr(s, c);
}
```

in places where you are not sure.

**Comment by jamessan** [comment]
Don't you mean

```c
assert(0 <= c && c <= CHAR_MAX);
```

since `strchr` casts `c` to `char`, so we need to make sure it's within the safe range of a signed char?

**Comment by ZyX-I** [comment]
@jamessan I do not see why characters above 127 are going to be a problem, casting `int` to `char` does not emit undefined behaviour. But this is going to have semantic problems: `int` characters in our code are nonnegative  when they are characters (and there are actually two kinds of them: bytes similar to `fgetc()` return, negative means EOF, nonnegative are in `[0, 255]`; and unicode: any nonnegative or something special, depending on the user).

**Comment by jamessan** [comment]
Ah, right, once the `int` is cast as `char` (signed or not), it will match the representation in `s`.  I had confused myself and was thinking there would be comparisons between (`int` cast as `char`) and `int`, which would be a problem.

**Comment by aktau** [comment]
> ```c
> static inline char *strchr_checked(const char *const s, const int c)
> ```

I'm not a big fan of the `*const s` and `const int c`. They don't tell the user of the function anything more (and wouldn't affect performance AFAICS). I like `const <type> *<var>` because that's a promise to the user you won't be changing their memory.

Also, if you do this (with the assert), we have to be pretty sure that `strchr_checked`/`vim_strbyte` is never called with any needle (integer) that the user can supply.

**Comment by aktau** [comment]
...also, your `vim_strbyte` explicitly returns `NULL` instead of the end of string if you pass `0` as the needle. Your implementation doesn't handle that, it would pass the value to `strchr` which would return the end of the string.

**Comment by ZyX-I** [comment]
@aktau The user should not supply strange needles. And would first try with exactly this implementation, I do not see where this behaviour should be useful. Additionally run `ag` and found that function is useless:

- ex_cmds.c:5093: called with `'*'`
- mbyte.c:361: called with 0xEF
- getchar.c:3591: called with K_SPECIAL
- regexp_nfa.c:4864: never entered, has_mbyte always true
- regexp.c:3439: never entered, has_mbyte always true
- regexp.c:3492: never entered, has_mbyte always true
- strings.c:459: definition

Am I missing something?

**Comment by ZyX-I** [comment]
So you do not need to optimize vim_strbyte: replace it with `strchr` in a few cases when it is called with a constant, remove dead code.

**Comment by ZyX-I** [comment]
`cstrchr` on the other side is what should be the problem in regexp code: below “never entered” cases there are `cstrchr` usages.

**Comment by ZyX-I** [comment]
I am wondering whether the following `vim_strchr` implementation is better:

```Patch
diff --git a/src/nvim/strings.c b/src/nvim/strings.c
index 5dcffe0..8fc66c7 100644
--- a/src/nvim/strings.c
+++ b/src/nvim/strings.c
@@ -409,46 +409,17 @@ int vim_strnicmp(const char *s1, const char *s2, size_t len)
 char_u *vim_strchr(const char_u *string, int c)
   FUNC_ATTR_NONNULL_ALL FUNC_ATTR_PURE
 {
-  int b;
-
-  const char_u *p = string;
-  if (enc_utf8 && c >= 0x80) {
-    while (*p != NUL) {
-      int l = (*mb_ptr2len)(p);
-
-      // Avoid matching an illegal byte here.
-      if (l > 1 && utf_ptr2char(p) == c) {
-        return (char_u *) p;
-      }
-      p += l;
-    }
-    return NULL;
-  }
-  if (enc_dbcs != 0 && c > 255) {
-    int n2 = c & 0xff;
-
-    c = ((unsigned)c >> 8) & 0xff;
-    while ((b = *p) != NUL) {
-      if (b == c && p[1] == n2)
-        return (char_u *) p;
-      p += (*mb_ptr2len)(p);
-    }
+  assert(c >= 0);
+  if (c == 0) {
     return NULL;
+  } else if (c < 0x80) {
+    return strchr((const char *)string, c);
+  } else {
+    char u8char[MB_MAXBYTES + 1];
+    const int len = utf_char2bytes(c, (char_u *)u8char);
+    u8char[len] = NUL;
+    return strstr((const char *)string, u8char);
   }
-  if (has_mbyte) {
-    while ((b = *p) != NUL) {
-      if (b == c)
-        return (char_u *) p;
-      p += (*mb_ptr2len)(p);
-    }
-    return NULL;
-  }
-  while ((b = *p) != NUL) {
-    if (b == c)
-      return (char_u *) p;
-    ++p;
-  }
-  return NULL;
 }
 
 /*
```

It mostly relies on libc functions being more optimized.

**Comment by ZyX-I** [comment]
And removes branches which are never entered because e.g. `enc_utf8` is now always true.

**Comment by aktau** [comment]
> So you do not need to optimize vim_strbyte: replace it with strchr in a few cases when it is called with a constant, remove dead code.

Sounds good, getting rid of dead code and static needle cases.

I also agree that your `vim_strchr` looks better and should be much faster. The open-coded versions perform very poorly.

`cstrchr` also looks dreadful, as you say. And optimizing the regexp engine will actually have a noticeable effect.

**Comment by ZyX-I** [comment]
`cstrchr` uses `vim_strchr` in many cases. I would not say that reg_ic is uncommon though, so `vim_strchr` is not the only thing which needs to be optimized in `cstrchr`, but that is a good start. Maybe `vim_strchr` is worth moving to the header and made static inline REAL_FATTR_ALWAYS_INLINE.

**Comment by ZyX-I** [comment]
It seems like my variant is by an order of magnitude faster on long strings. Though I am using busted to benchmark, this is rather imprecise: for old version on the below code it reports 9.2 seconds, 0.9 seconds for new variant, same for both 0xbb and 99 ('c') variants.

```lua
local helpers = require('test.unit.helpers')(after_each)

local itp = helpers.gen_itp(it)

local lib = helpers.cimport('./src/nvim/strings.h')

describe('', function()
  itp('', function()
    local strchr = lib.vim_strchr
    local s = ("ab"):rep(999) .. "«»cc"
    s = helpers.to_cstr(s)
    for i = 1, 1000000 do
      strchr(s, 0xbb)
      -- strchr(s, 99)
    end
  end)
end)
```

**Comment by ZyX-I** [comment]
I have created related commits, feel free to cherry-pick them.

**Comment by aktau** [comment]
Added my comment on the first commit (just style nits). Why don't you turn it into a PR?

**Comment by ZyX-I** [comment]
I thought you have/are going to have a PR. Also I would not do proper benchmarking.

**Comment by ZyX-I** [comment]
And `cstrchr` refactoring.

**Comment by aktau** [comment]
> BTW, is using libc locale-dependent functions actuall valid there? We are always using UTF-8, do we set locale to something with UTF-8 or this code is going to get something above 0x80 for some single-byte locales? I would really go with our ASCII_… functions/macros: they are faster and we know for sure what they are going to return.

Which ones are locale dependent? Not `strchr` or `strstr` AFAIK.

**Comment by ZyX-I** [comment]
@aktau Nothing *I* added. vim_toupper/vim_tolower/vim_isupper/vim_islower is using libc implementations for ASCII characters, with some fixes for character at and below. We have not-locale-dependent ascii_… functions, ASCII_… macros and `TO…_ASC` macros.

**Comment by aktau** [comment]
Right. Seems like that would be a good improvement.

**Comment by dundargoc** [comment]
I'm closing this as I believe this has been resolved and just slipped through the cracks. Please reopen if I've misunderstood the situation and that there's more to be done.
