### ISSUE TITLE
Build failing with "Could not resolve host: www.leonerd.org.uk"

### ISSUE THREAD

**Issue by clason** [neovim/neovim#14764]
The server that is hosting two dependencies of neovim (`libtermkey` and `libvterm`) is currently down, so unless you have these cached (especially, if you removed them via `make distclean`), the build will fail. The problem is known; in the meantime, you can replace the links to the tarballs with ones to cached files:

```
diff --git a/third-party/CMakeLists.txt b/third-party/CMakeLists.txt
index e24823290..e5cc80bd2 100644
--- a/third-party/CMakeLists.txt
+++ b/third-party/CMakeLists.txt
@@ -159,10 +159,10 @@ set(LUAROCKS_SHA256 0cab9f79311083f33e4d8f5a76021604f1d3f7141ce9a2ef1d8b717d9205
 set(UNIBILIUM_URL https://github.com/neovim/unibilium/archive/92d929f.tar.gz)
 set(UNIBILIUM_SHA256 29815283c654277ef77a3adcc8840db79ddbb20a0f0b0c8f648bd8cd49a02e4b)

-set(LIBTERMKEY_URL http://www.leonerd.org.uk/code/libtermkey/libtermkey-0.22.tar.gz)
+set(LIBTERMKEY_URL https://distfiles.macports.org/libtermkey/libtermkey-0.22.tar.gz)
 set(LIBTERMKEY_SHA256 6945bd3c4aaa83da83d80a045c5563da4edd7d0374c62c0d35aec09eb3014600)

-set(LIBVTERM_URL http://www.leonerd.org.uk/code/libvterm/libvterm-0.1.4.tar.gz)
+set(LIBVTERM_URL https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/libvterm/0.1.4-1/libvterm_0.1.4.orig.tar.gz)
 set(LIBVTERM_SHA256 bc70349e95559c667672fc8c55b9527d9db9ada0fb80a3beda533418d782d3dd)

 set(LUV_VERSION 1.30.1-1)
 ```

**Comment by arpangreat** [comment]
https://github.com/neovim/homebrew-neovim/issues/169#issuecomment-237832016

**Comment by markuspeloquin** [comment]
> [neovim/homebrew-neovim#169 (comment)](https://github.com/neovim/homebrew-neovim/issues/169#issuecomment-237832016)

That's from 2016, and the gitter comment you're referring to is from the same time. I see no evidence that leonerd is even aware of the issue currently.

**Comment by shadmansaleh** [comment]
www.leonerd.org.uk is up now

**Comment by novakne** [comment]
Yep building works now
