### ISSUE TITLE
treesitter impact of redraw performance

### ISSUE THREAD

**Issue by kevinhwang91** [neovim/neovim#14762]
- `nvim --version`:
- Operating system/version: `ArchLinux`
- Terminal name/version: `alacritty`
- `$TERM`: `alacritty`

### Steps to reproduce using `nvim -u NORC`
`cat mini.vim`
```
set rtp+=/home/kevin/.local/share/nvim/site/pack/packer/opt/nvim-treesitter
lua <<EOF
require('nvim-treesitter.configs').setup({
    ensure_installed = 'maintained',
    highlight = {enable = true}
})
EOF
```
`src/nvim/eval.c` is the source code in neovim repo.

`nvim -u mini.vim src/nvim/eval.c`
1. After entering the buffer of eval.c, enter insert mode and then press one key last for a few seconds
2. `TSBufDisable highlight`
3. repeat step 1
### Actual behaviour
step 1 is lag, but step 3 is smooth
### Expected behaviour
step 1 is as smooth as step 3.

**Comment by bfredl** [comment]
Not much profiling of the TS redraw code has been done yet. This will be part of the 0.6 milestone of making tree-sitter more robust.

**Comment by guijun** [comment]
v0.8.0
the issue is still there. 
steps:
enable highlighting
open minified javascript (which has all text in 1 line).
try move cursor.

**Comment by theHamsta** [comment]
It depends a lot on on the used parser: See https://github.com/nvim-treesitter/nvim-treesitter/issues/2916 https://github.com/nvim-treesitter/nvim-treesitter/issues/2996. I did some profiling in https://github.com/nvim-treesitter/nvim-treesitter/issues/2916 using https://github.com/neovim/neovim/pull/18761

From my experience:
- some parsers are slow
- some parsers fail to efficiently parse a file incrementally. some rules cause an invalidation of almost the whole file on some single letter edits
- big files are not parsed with timeout yet
- nested languages are not parsed incrementally yet

**Comment by lewis6991** [comment]
This should be fixed somewhat with https://github.com/neovim/neovim/pull/22309. @kevinhwang91 can you provide an update from your end?

**Comment by kevinhwang91** [comment]
`v0.8.3` and `master` is not lagging. I'm not sure whether the patch improves the perf, but should close this issue now.
