### ISSUE TITLE
set tabstop doesn't works

### ISSUE THREAD

**Issue by palandovalex** [neovim/neovim#14774]
- `nvim --version`: v0.4.3
- Operating system/version: linux mint 20.1
- Terminal name/version: terminator 1.91

in my .config/nvim/init.vim. i add:
```

set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath=&runtimepath
source ~/.vimrc
```
So, other parametrs from .vimrc works correctly.

But... I set in .vimrc parametrs:

```
 set expandtab                               
 set tabstop=2
```

In vim(Vi IMproved 8.1) this works correctly. 

But in nvim - this doesn't work. 

### Actual behaviour
tab add 8 spaces
### Expected behaviour
tab should add 2 spaces

**Comment by clason** [comment]
Neovim doesn't read `.vimrc` at all, it uses `.config/nvim/init.vim`.

**Comment by palandovalex** [comment]
> Neovim doesn't read `.vimrc` at all, it uses `.config/nvim/init.vim`.

in my `.config/nvim/init.vim`. i add:
```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath=&runtimepath
source ~/.vimrc
```
So, other parametrs from .vimrc works correctly.

**Comment by clason** [comment]
Does it work if you set it in your `init.vim` directly? Can you reproduce it on the latest nightly?

**Comment by chrisbra** [comment]
Note, that `tabstop` is a *buffer-local* option, that means it can (and probably will) be overridden by filetype plugins. Meaning, it matters in which file you check the value of the tabstop option. Check `:verbose set ts?`

**Comment by matu3ba** [comment]
@chrisbra This lua code does not work
```lua
  vim.bo.expandtab        = true; --use space character on pressing Tab key
  vim.bo.softtabstop      = 0; --Tab and BS: insert+delete number of spaces
  if ( vim.bo.filetype == "cpp" ) then -- something is very broken here
    vim.bo.shiftwidth       = 4; --visual mode >,<-key: number of spaces for indendation
  else
    vim.bo.shiftwidth       = 2;
  end
  if ( vim.bo.filetype == "cpp" ) then -- something is very broken here
    vim.bo.tabstop          = 4; --Tab key: number of spaces for indendation
  else
    vim.bo.tabstop          = 2;
  end
```
and sets always to 2.
Ie for `neovim -u init.lua min.cpp` containing that file indentation is not 4, but 2.
`min.cpp`:
```c++
int main() {
    //minimal example file
    int a = 3;
    if (a == 3)
    {//curor here
    }
}
```
```c++
int main() {
    //minimal example file
    int a = 3;
    if (a == 3)
    {
      //curor here
    }
}
```

**Comment by gpanders** [comment]
`'tabstop'` only controls how many spaces a tab character (`\t`) *appears* to take up on the screen. When you have `'expandtab'` set then the Tab key inserts spaces, not tabs, so the `'tabstop'` option is not used.

Take a look at `:h 'shiftwidth'`, `:h 'softtabstop'`, and `:h 'smarttab'`. In particular, I suspect the reason this works for you in Vim but not Neovim is that Neovim sets 'smarttab' on by default.
