### ISSUE TITLE
`BufWinEnter` and `FileType` appear to be broken in newer versions of nvim

### ISSUE THREAD

**Issue by LunarWatcher** [neovim/neovim#14798]
I'm maintaining a plugin that relies on autocmds working in  order to start the plugin correctly. I use `BufWinEnter` to guarantee I _always_ get the filetype. In regular Vim, `BufWinEnter` is called after the normal filetype is set, and after modelines have been evaluated. While I don't use `FileType` to start anything, I'm still using it in this post to keep track of events, be cause I can't be arsed to break down three other plugins to pin down the problem there - I'm reporting on what I see in my plugin (which is unrelated to the other three).

Unfortunately, starting with 1def3d1 (thanks to gregorias for the bisect), I see four BufWinEnters called for a popup, and the filetype set long after the BufWinEnters are called. 

- `nvim --version`: NVIM v0.5.0-dev+1401-g12d8ff7cc , NVIM 0.5.0 , NVIM v0.6.0-dev+10-g18bfcfe77
- Operating system/version: Mint 20.1 (live install), Ubuntu latest (docker), Manjaro (live install, not confirmed by me)
- Terminal name/version: Gnome Terminal 3.36.2 on the first two
- `$TERM`: `xterm-256color`, `xterm`

Vim behaves differently from nvim on 8.2 patches 1-2968 (2021.06.10) and 1-2984 (2021.06.13).

### Steps to reproduce using `nvim -u NORC`

```vim
nvim -u NORC

:autocmd BufWinEnter * unsilent echom "BufWinEnter"
:autocmd FileType * unsilent echom "Filetype set"
:e test.py
```
### Non-standard repro:

```vim
set nocompatible

filetype off

autocmd FileType * unsilent echom "Filetype set"
autocmd BufWinEnter * unsilent echom "BufWinEnter"

call plug#begin()
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim' 
call plug#end()

filetype on
filetype plugin indent on
filetype plugin on
```

Install plugins and call `:Telescope`.

### Expected behaviour
In both:
```
Filetype set
# Either BufWinEnter or nothing
```

### Actual behaviour 
Telescope:
```
BufWinEnter
BufWinEnter
BufWinEnter
BufWinEnter
Filetype set
```

And in normal buffers:

```
BufWinEnter
Filetype set
```

---

Note that the expected behavior is present in NVIM v0.5.0-dev+1127-g667e3bfb6 - that's why I'm reporting it here and not in one of the three plugins. I've tested both versions of nvim mentioned in this post on the _same version_ of the three plugins. Even if it somehow was their fault, though, the inconsistent  autocmds and incorrect orders is guaranteed to be an nvim issue.

The order in which stuff is called in newer versions of nvim prevents me from accessing `&ft` when I need it, by triggering `BufWinEnter` before the filetype is set.

I also honestly have no idea whether this is a bug or intentional, but I can't find much documentation indicating that it's meant to be intentional. To be fair, I also can't find anything indicating that it _isn't_ intentional.

### An observation

I just came back to this a second time, and I've noticed that the order is some times correct, and some times not. It'd also appear as if it's some times dependent on the declaration order of the autocmds, which makes no sense what so ever. Adding a second augroup with the reverse order also fixed the order for yet another reason I don't comprehend. The lack of a filetype when BufWinEnter is called when Telescope is invoked remains a problem, and remains one that's dependent on nvim -- again, it used to work, and now it doesn't, and has nothing to do with the version of Telescope.

**Comment by justinmk** [comment]
> Unfortunately, starting with [1def3d1](https://github.com/neovim/neovim/commit/1def3d1542d6a65f057e743faea39a760b50db87) (thanks to gregorias for the bisect), I see four BufWinEnters called for a popup, and the filetype set long after the BufWinEnters are called.

reverted in https://github.com/neovim/neovim/pull/14531

see also https://github.com/neovim/neovim/pull/14659

**Comment by LunarWatcher** [comment]
I'm still able to reproduce this. Might've been bisected to the wrong version, but I recompiled on June 13th, July 8th, and today, and reproduced it all three times. Something still remains wrong with the autocmds.
