### ISSUE TITLE
:source without argument doesn't recognize '\'

### ISSUE THREAD

**Issue by shadmansaleh** [neovim/neovim#14807]
- `nvim --version`: v0.5.0-dev+1403-g141647cfb

[x] `vim -u DEFAULTS` (version: 8.2) behaves differently

Vim doesn't have `:source` sourceing current buffer I think . This functionality was added to neovim in #11444 . So this difference doesn't mean anything

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC test.vim
```

Write these lines and save the file

```vim
let example = {
      \ 'key' : 'val',
      \ }
```
Now source current buffer with
```vim
:source
```
Note: source command without any arguments

### Actual behaviour

Shows errors
```log
Error detected while processing :source (no file):
E15: Invalid expression: {
E10: \ should be followed by /, ? or &
E10: \ should be followed by /, ? or &
```

### Expected behavior

Should source the buffer similar to 
```vim
source %
```
without any errors.

### Speculations

I think it's occuring because how the buffer is split into statements. I think each line is ran separately without noticing that '\\' in following line means continuation of current statement.

**Comment by clason** [comment]
Same happens for `:'<,'>source` with the lines selected.

Funnily, it works for the equivalent Lua:
```lua
local example = {
  key = 'val'
}
```

**Comment by shadmansaleh** [comment]
Yeah range and this follow the same code path so expected tohave same issue . It works for lua because I ran entire selection or buffer as single chunk :D

**Comment by seandewar** [comment]
`getsourceline()` does the concatenation if `cpo` doesn't have `S` set but this logic looks like it's missing from `get_str_line()`?
