### ISSUE TITLE
Issues adding python3 support to neovim, can't run Vimspector plugin

### ISSUE THREAD

**Issue by oden360** [neovim/neovim#14808]
### General Info
- nvim --version: **v0.4.4**
- Operating system/version: **deb**
- Terminal name/version: **urxvt**
- window manager: **i3**

### Disclaimer 
I know there are several threats containing this topic, However I created a new one seeing all other once are old and don't provide the information to resolve my issue. If the creation of this issue is not following protocol I apologise in advance.

### Issue
I'm trying to enable Vimspector in Neovim. When starting Neovim I receive the following error:
`Vimspector unavailable: Requires Vim compiled with +python3`

I followed several steps to resolve this issue but was unsuccesfull, I believe my neovim doesn't contain python as seen in the feature fields given by nvim --version. 
`Features: +acl +iconv +tui`
I have no idea how to add python3 to my nvim. Is there anyone who can resolve this issue ? 
Thanks in advance. 

### Expected behaviour
Able to run the plugging with python3 support.

### Actions taken 
I searched several threats and followed the recommended actions, namely : 
* Install the python support module with pip3 
   pip3 install --upgrade pynvim (also tried with sudo)
* check system health and version (information below)
* tried the appimage from neovim, this was succefull in loading the plugin.

### History

To get the required version of nvim I compiled nvim from source following:
https://github.com/neovim/neovim/wiki/Building-Neovim

Then I moved the binairy to /usr/bin/nvim

#### echo has('python3.7') 
returns =0

#### CheckHealth

```
##Python 2 provider (optional)    
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.    
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.    
  - INFO: Executable: /usr/bin/python2    
  - INFO: Other python executable: /bin/python2    
  - INFO: Python version: 2.7.16    
  - INFO: pynvim version: 0.4.3    
  - **OK: Latest pynvim is installed.**    
    
##Python 3 provider (optional)    
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3.7"    
  - INFO: Executable: /usr/bin/python3.7    
  - INFO: Python version: 3.7.3    
  - INFO: pynvim version: 0.4.3    
  - **OK: Latest pynvim is installed.**   
```

#### nvim --version 
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM 

**Features: +acl +iconv +tui**
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
#### init.vim
```
set runtimepath+=~/.config/nvim      
set packpath+=~/.config/nvim    
source ~/.config/nvim/vimrc
````
#### vimrc          
```                                                                        
"Plug    
call plug#begin('~/.config/nvim/plugged')    
Plug 'puremourning/vimspector'    
Plug 'szw/vim-maximizer'    
call plug#end()    
**let g:python3_host_prog = '/usr/bin/python3.7'**    
```
#### runtimepath 
```
runtimepath=
~/.config/nvim,
~/.config/nvim/plugged/vim-fugitive,
~/.config/nvim/plugged/gruvbox,
~/.config/nvim/plugged/lightline.vim,
~/.config/nvim/plugged/vim-surround,
~/.config/nvim/plugged/vimwiki,
~/.config/nvim/plugged/vimspector,
~/.config/nvim/plugged/vim-maximizer,
/etc/xdg/nvim,
~/.local/share/nvim/site,
/usr/local/share/nvim/site,
/usr/share/nvim/site,/usr/share/nvim/runtime,
/usr/share/nvim/site/after,
/usr/local/share/nvim/site/after,
~/.local/share/nvim/site/after,/etc/xdg/nvim/after,
~/.config/nvim/after
```

**Comment by glacambre** [comment]
Maybe try `sudo apt install python3-pynvim`?

**Comment by oden360** [comment]
Hey, thanks for the reply but unfortunately this doesn't work.

**Comment by glacambre** [comment]
Weird. Could you try master/nightly? :)

**Comment by oden360** [comment]
> 
> 
> Weird. Could you try master/nightly? :)

Is it possible to disclose some more information, not following what you mean exactly ;).

**Comment by glacambre** [comment]
By "trying master" I meant trying the master branch of the repository. By "trying nightly", I meant "trying the nightly release", which you can download [here](https://github.com/neovim/neovim/releases). Trying the master release on linux is very simple, download the file named "nvim.appimage", make it executable with `chmod +x nvim.appimage` and then run it with `./nvim.appimage`.

**Comment by oden360** [comment]
Yes, I used this appimage methode before and it worked. However when building from source I get the above mentioned error message.

**Comment by oden360** [comment]
> 
> 
> Yes, I used this appimage methode before and it worked. However when building from source I get the above mentioned error message.
Yes, I used this appimage methode before and it worked. However when building from source I get the above mentioned error message.

**Comment by oden360** [comment]
> 
> By "trying master" I meant trying the master branch of the repository. By "trying nightly", I meant "trying the nightly release", which you can download here. Trying the master release on linux is very simple, download the file named "nvim.appimage", make it executable with chmod +x nvim.appimage and then run it with ./nvim.appimage.
 Yes, I used this appimage methode before and it worked. However when building from source I get the above mentioned error message.

**Comment by glacambre** [comment]
Okay, this means that the issue you're having is very likely to be fixed on master and that upgrading to 0.5 once it's released will make your problem disappear.

>when building from source I get the above mentioned error message.

Did you set the runtime path?

**Comment by oden360** [comment]
> 
> 
> Okay, this means that the issue you're having is very likely to be fixed on master and that upgrading to 0.5 once it's released will make your problem disappear.
> 
> > when building from source I get the above mentioned error message.
> 
> Did you set the runtime path?

well that's the thing, I build 0.5 from source and the same error gets generated making me believe it's a other issue. This is the output of the runtimepath variable in vim. 
runtimepath=~/.config/nvim,~/.config/nvim/plugged/vim-fugitive,~/.config/nvim/plugged/gruvbox,~/.config/nvim/plugged/lightline.vim,~/.config/nvim/plugged/vim-surround,~/.config/nvim/plugged/vimwiki,~/.config/nv
im/plugged/vimspector,~/.config/nvim/plugged/vim-maximizer,/etc/xdg/nvim,~/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/share/nvim/runtime,/usr/share/nvim/site/after,/usr/local/shar
e/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/after

**Comment by glacambre** [comment]
>I build 0.5 from source and the same error gets generated

If the Appimage works, the problem most probably is that you have not set your runtime path. What happens if you run neovim with `VIMRTUNIME=neovim/runtime neovim/build/bin/nvim`?

**Comment by oden360** [comment]
Oke so I did the following on my 0.4 build:
I checked my runtime
```
:echo $VIMRUNTIME
/usr/share/nvim/runtime  
```
then  add this line to my vimrc.
```
let $VIMRUNTIME='neovim/runtime' 
```
It returned the error stated above:
```
Vimspector unavailable: Requires Vim compiled with +python3
```
to confirm ran this in nvim:
```
:echo $VIMRUNTIME
neovim/runtime 
```

Next i removed the previous vimrc command and added

```
let $VIMRUNTIME='neovim/build/bin/nvim'  
```
It returned the following: 
```
.config/nvim/vimrc:
line   59:
E484: Can't open file neovim/build/bin/nvim/syntax/syntax.vim
Vimspector unavailable: Requires Vim compiled with +python3
```
to confirm ran this in nvim:
```
:echo $VIMRUNTIME
neovim/build/bin/nvim
```

**Comment by glacambre** [comment]
You can't set `VIMRUNTIME` in your .vimrc, you have to set it in your shell. This environment variable is used before your vimrc is read :).

Please run neovim with `VIMRUNTIME=neovim/runtime neovim/build/bin/nvim`. If it works, we can be certain that the reason your 0.5 build did not work while the appimage did was that there was a runtime path issue :).

**Comment by oden360** [comment]
Hey I ran the command you posted in the terminal and like you said it worked ! Can I be so curious to ask why you suspected the VIMRUNTIME variable? (had no clue that was a thing btw XD)

**Comment by glacambre** [comment]
The reason I suspected this variable is that it's always correctly set by default when running the appimage and never correctly set by default when running neovim from its build dir.

There are multiple solutions, one could be to add `export VIMRUNTIME="/path/to/neovim/runtime/directory`, another could be to always use the appimage, and a third one could be to [configure your install prefix](https://github.com/neovim/neovim/wiki/Building-Neovim#quick-start) and then running `make install` after having run `make`.

I'll close this issue since the bug you encountered with neovim 0.4 isn't there in neovim 0.5 when the runtime path is correctly set, but feel free to ask any other question you may have :).

**Comment by oden360** [comment]
Thanks ! , fixed my issue :) sorry for the late reply got caught in something.
