### ISSUE TITLE
Use XDG_STATE_HOME for logs

### ISSUE THREAD

**Issue by p00f** [neovim/neovim#14805]
Currently `XDG_CACHE_HOME` is used for logs, however the [latest version of the spec](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) introduces `XDG_STATE_HOME`

>  The $XDG_STATE_HOME contains state data that should persist between (application) restarts, but that is not important or portable enough to the user that it should be stored in $XDG_DATA_HOME. It may contain:
>
>   - actions history (logs, history, recently used files, …)
>
>   - current state of the application that can be reused on a restart (view, layout, open files, undo history, …)

Will a PR implementing this (only) for logs be accepted?

**Comment by p00f** [comment]
I'll keep it equal to `kXDGCacheHome` for non-Linux I guess?

**Comment by mjlbach** [comment]
I would (as the person who last dealt with the headache of moving an XDG directory, to (in-fact) XDG_CACHE_HOME) suggest we wait awhile, until this is more widely adopted. We're currently only storing logs, and it's ok for these not to be persistent.

**Comment by mjlbach** [comment]
Oh, I didn't mean close this, just saying we should probably wait until after 0.5 for the 0.6 cycle.

**Comment by p00f** [comment]
Dibs? I want to do some real-life C

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/15583

**Comment by p00f** [comment]
Since discussion has started in the PR, should I close this issue?

**Comment by gpanders** [comment]
No need, you can leave it open until we decide one way or another what to do
