### ISSUE TITLE
Tutor is buggy. Links and and other markdown stuff stops working

### ISSUE THREAD

**Issue by DundarGoc** [neovim/neovim#14827]
- `nvim --version`:

> NVIM v0.4.4
> Build type: Release
> LuaJIT 2.0.5
> Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
> Compiled by builduser
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info

- Operating system/version: Manjaro
- Terminal name/version: kitty 0.20.3, alacritty 0.8.0, konsole 21.04.1
- `$TERM`: xterm-kitty (kitty), alacritty (alacritty), xterm-256color (konsole) 

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:Tutor
```
Everything breaks down after line 73:

### Actual behavior
    `:q!`{vim} `<Enter>`{normal}.

### Expected behavior
    `:q!` `<Enter>`.

but with highlighting or links. It's the exclamation mark ("!") that's the problem, everything works if you remove the "!" on line 73.

Correction: everything works until the next exclamation mark on line 157 and so on.

**Comment by glacambre** [comment]
Could you try the nightly release? If the bug is still present there, could you describe in deeper detail how to reproduce the bug and what "everything breaks down after line 73" means?

**Comment by DundarGoc** [comment]
@glacambre  Huh. The bug isn't there in the nightly build. So I guess this is fixed then. Do I close this issue?

**Comment by glacambre** [comment]
Yep, I think we can close this issue. Thanks for checking :)
