### ISSUE TITLE
Japanese text inserting line is highlighted with the same color defined by StatusLine

### ISSUE THREAD

**Issue by JohnRama** [neovim/neovim#14820]
- `nvim --version`:
$ nvim --version    
NVIM v0.4.4         
Build type: Release 
LuaJIT 2.1.0-beta3  

- Operating system/version:
macOS Big Sur version 11.1
- Terminal name/version:
mac standard terminal version 2.11
- `$TERM`:
screen-256color

[x] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
$ nvim --noplugin /tmp/hoge2.txt -u NONE 
: colorscheme blue                       
: hi StatusLine ctermbg=1            
Then, try to insert Japanese character    
```
[hoge2.txt](https://github.com/neovim/neovim/files/6654682/hoge2.txt)

### Actual behaviour
- when trying to input Japanese Language, the line is 
highlighted the same color defined by StatusLine      

![image](https://user-images.githubusercontent.com/23188902/122032989-212c2480-cd9e-11eb-9909-ef85893d79e6.png)

### Expected behaviour
- No highlight is expected for the line.

### Other info
- Highlighted color is same as the StatusLine.                              
- If we change the setting for StatusLine, then the highlighted color       
	changed accordingly.                                                      
	- example                                                                 
		:hi StatusLine ctermbg=1                                                
- The problem happens when trying to input Japanese language in insert mode 
   No problem when trying to input alphabet                                  
- The problem happens when using nvim.                     
   No problem with vim (8.2)                                                 
- The problem does not happen when the window size is half by using vsplit  
- The problem happens on mac, not windows.                                  
- This problem does not always happens. But probability is very high.            
- This problem happens with following colorscheme                           
	- blue                                                                    
	- darkblue                                                                
   but not happens with following colorscheme                                     
	- default                                                                 
	- delek

**Comment by zeertzjq** [comment]
It seems Vim does have the same behavior with `laststatus=2`.

**Comment by justinmk** [comment]
Cannot reproduce on 01b6bff7e9bc
