### ISSUE TITLE
lsp: add helper to toggle display of diagnostics

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#14825]
Users want to toggle showing diagnostics (especially if using virtual text). We should probably have this on a buffer basis (vim.lsp.diagnostics.toggle_buf_display_diagnostics()?) that sets, per client, an option that prevents displaying diagnostics on the next textdidchange (but continues to populate the diagnostics cache), and subsequently clear's the diagnostics that are currently displayed.

We get this question a lot on matrix/reddit/discourse.

Also, we should probably make it more clear in the docs that we *cannot* request diagnostics from the language server on an event, but only listen for updated diagnostics from the server. There's a lot of misunderstanding around this.

For now, you can do something like (stolen from reddit):

```lua
virtual_text = {}

virtual_text.show = true

virtual_text.toggle = function()
    virtual_text.show = not virtual_text.show
    vim.lsp.diagnostic.display(
        vim.lsp.diagnostic.get(0, 1),
        0,
        1,
        {virtual_text = virtual_text.show}
    )
end

vim.api.nvim_set_keymap(
    'n',
    '<Leader>lv',
    '<Cmd>lua virtual_text.toggle()<CR>',
    {silent=true, noremap=true}
)

**Comment by bluz71** [comment]
Per-buffer is nice, as is global toggling as [noted in this Reddit discussion](https://www.reddit.com/r/neovim/comments/ng0dj0/lsp_diagnostics_query_is_there_an_way_to_toggle).

This is what I ended up with to globally toggle diagnostics (signs and virtual text):

```lua
vim.g.diagnostics_visible = true

function _G.toggle_diagnostics()
  if vim.g.diagnostics_visible then
    vim.g.diagnostics_visible = false
    vim.lsp.diagnostic.clear(0)
    vim.lsp.handlers["textDocument/publishDiagnostics"] = function() end
    print('Diagnostics are hidden')
  else
    vim.g.diagnostics_visible = true
    vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
      vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = true,
        signs = true,
        underline = true,
        update_in_insert = false,
      }
    )
    print('Diagnostics are visible')
  end
end

vim.api.nvim_buf_set_keymap(0, 'n', '<Space>D', ':call v:lua.toggle_diagnostics()<CR>', {silent=true, noremap=true})
```

**Comment by lcrockett** [comment]
If it helps, i use the following combinations of functions and `on_attach` logic to achieve buffer bound LSP diagnostics that can be toggled on-demand and persistently.

**Globally defined functions**
```lua
function _G.self_core_lsp_diagnostic_indicators_clear()
  vim.lsp.diagnostic.clear(0)
end

function _G.self_core_lsp_diagnostic_indicators_disable()
  vim.lsp.handlers['textDocument/publishDiagnostics'] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics, {
      signs = false,
      underline = false,
      update_in_insert = false,
      virtual_text = false
    }
  )
end

function _G.self_core_lsp_diagnostic_indicators_none()
  vim.b.self_core_lsp_diagnostic_indicators_show = false

  _G.self_core_lsp_diagnostic_indicators_disable()
  _G.self_core_lsp_diagnostic_indicators_clear()

  return
end

function _G.self_core_lsp_diagnostic_indicators_redraw()
  -- NOTE: This function might become obsolete after the merge of 'https://github.com/neovim/neovim/pull/13748', who knows !
  for _,lsp_client_id in pairs(vim.tbl_keys(vim.lsp.buf_get_clients())) do
    vim.lsp.handlers['textDocument/publishDiagnostics'](
      nil,
      'textDocument/publishDiagnostics', {
          diagnostics = vim.lsp.diagnostic.get(0, lsp_client_id),
          uri = vim.uri_from_bufnr(0)
      },
      lsp_client_id
    )
  end
end

function _G.self_core_lsp_diagnostic_indicators_set()
  vim.lsp.handlers['textDocument/publishDiagnostics'] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics, {
      severity_sort = true,
      signs = function()
        if vim.b.self_core_lsp_diagnostic_indicators_mode == 'Signs' or vim.b.self_core_lsp_diagnostic_indicators_mode == 'SignsVirtualText' then
          return true
        else
          return false
        end
      end,
      underline = false,
      update_in_insert = false,
      virtual_text = function()
        if vim.b.self_core_lsp_diagnostic_indicators_mode == 'VirtualText' or vim.b.self_core_lsp_diagnostic_indicators_mode == 'SignsVirtualText' then
          return "{ severity_limit = 'Hint', spacing = 10 }"
        else
          return false
        end
      end,
    }
  )
end

function _G.self_core_lsp_diagnostic_indicators_signs()
  vim.b.self_core_lsp_diagnostic_indicators_mode = 'Signs'
  vim.b.self_core_lsp_diagnostic_indicators_show = true

  _G.self_core_lsp_diagnostic_indicators_set()
  _G.self_core_lsp_diagnostic_indicators_redraw()

  return
end

function _G.self_core_lsp_diagnostic_indicators_signsvirtualtext()
  vim.b.self_core_lsp_diagnostic_indicators_mode = 'SignsVirtualText'
  vim.b.self_core_lsp_diagnostic_indicators_show = true

  _G.self_core_lsp_diagnostic_indicators_set()
  _G.self_core_lsp_diagnostic_indicators_redraw()

  return
end

function _G.self_core_lsp_diagnostic_indicators_virtualtext()
  vim.b.self_core_lsp_diagnostic_indicators_mode = 'VirtualText'
  vim.b.self_core_lsp_diagnostic_indicators_show = true

  _G.self_core_lsp_diagnostic_indicators_set()
  _G.self_core_lsp_diagnostic_indicators_redraw()

  return
end
```

**`on_attach` logic to include in setup of LSP client**
```lua
local on_attach = function()
  if vim.b.self_core_lsp_diagnostic_indicators_show == nil then
    vim.b.self_core_lsp_diagnostic_indicators_show = true
  end

  if vim.b.self_core_lsp_diagnostic_indicators_mode == nil then
    vim.b.self_core_lsp_diagnostic_indicators_mode = 'SignsVirtualText'
  end

  _G.self_core_lsp_diagnostic_indicators_set()
  _G.self_core_lsp_diagnostic_indicators_redraw()
end
```

**On-demand buffer bound Lua calls**
```lua
lua _G.self_core_lsp_diagnostic_indicators_none()
lua _G.self_core_lsp_diagnostic_indicators_redraw()
lua _G.self_core_lsp_diagnostic_indicators_signs()
lua _G.self_core_lsp_diagnostic_indicators_virtualtext()
lua _G.self_core_lsp_diagnostic_indicators_signsvirtualtext()
```

**Comment by mjlbach** [comment]
This was mostly addressed by #15134 

I'll probably do a follow-up PR that adds the necessary utils to write your own toggleable. Right now, you'd need to track which buffers were disabled by yourself.

**Comment by mjlbach** [comment]
Use enable/disable, see details in the new diagnostic API https://github.com/neovim/neovim/pull/15585/files

**Comment by bluz71** [comment]
@mjlbach,

Will the new API only be for 0.6 (and beyond) or will they be part of 0.5.1?

**Comment by mjlbach** [comment]
I'd be surprised if we backport it, but it's not out of the realm of possibility

**Comment by bluz71** [comment]
A possibility would be to have both APIs in 0.5.1, but with a deprecation warnings emitted by all the old API functions thereby easing the transition from the old to the new API.

Food for thought.

**Comment by bluz71** [comment]
Maybe the back-end is so different between the old and new APIs that my suggestion above is not feasible. If so, scrub that idea.

**Comment by tgy** [comment]
Could someone detail here how it's done with new API? Like just a command? It would help those who stumble upon this issue when searching for a solution. Thanks

**Comment by mjlbach** [comment]
`:lua vim.diagnostic.disable()` and `:lua vim.diagnostic.enable()`, you could wrap those into a toggle function if you would like.

**Comment by djfinnoy** [comment]
> `:lua vim.diagnostic.disable()` and `:lua vim.diagnostic.enable()`, you could wrap those into a toggle function if you would like.

Sorry for poling an old issue, just sharing this to hopefully save somebody some time (pieced together from information in this thread)

```
vim.g.diagnostics_visible = true
function _G.toggle_diagnostics()
  if vim.g.diagnostics_visible then
    vim.g.diagnostics_visible = false
    vim.diagnostic.disable()
  else
    vim.g.diagnostics_visible = true
    vim.diagnostic.enable()
  end
end
vim.api.nvim_buf_set_keymap(0, 'n', '<Leader>l', ':call v:lua.toggle_diagnostics()<CR>', {silent=true, noremap=true})
```

**Comment by nkcfan** [comment]
Instead of disable/enable, is it possible just show/hide? I cannot figure out the right parameters.

People were following https://www.reddit.com/r/neovim/comments/m7ne92/how_to_redraw_lsp_diagnostics/?utm_source=share&utm_medium=web2x&context=3 to show/hide, but the function `vim.lsp.diagnostic.display` is deprecated now.

**Comment by sdondley** [comment]
coc-intelephense has a nifty feature to hide diagnostics on a particular line: https://github.com/yaegassy/coc-intelephense/blob/master/src/actions.ts

Any plugins out there that have generalized this solution?

**Comment by mjlbach** [comment]
The required inserted text differs per server, so a generalized solution is unlikely. Not all servers support comments that ignore diagnostics.

From: Steve Dondley ***@***.***>
Date: Tuesday, February 22, 2022 at 9:19 PM
To: neovim/neovim ***@***.***>
Cc: Michael Lingelbach ***@***.***>, Mention ***@***.***>
Subject: Re: [neovim/neovim] lsp: add helper to toggle display of diagnostics (#14825)

coc-intelephense has a nifty feature to hide diagnostics on a particular line: https://github.com/yaegassy/coc-intelephense/blob/master/src/actions.ts

Any plugins out there that have generalized this solution?

**Comment by Danielratmiroff** [comment]
What I ended up with:

-- Toogle diagnostics
local diagnostics_active = true
local toggle_diagnostics = function()
  diagnostics_active = not diagnostics_active
  if diagnostics_active then
    vim.api.nvim_echo({ { "Show diagnostics" } }, false, {})
    vim.diagnostic.enable()
  else
    vim.api.nvim_echo({ { "Disable diagnostics" } }, false, {})
    vim.diagnostic.disable()
  end
end

**Comment by Danielratmiroff** [comment]
I adchieve this using:

```
-- Toogle diagnostics
local diagnostics_active = true
local toggle_diagnostics = function()
  diagnostics_active = not diagnostics_active
  if diagnostics_active then
    vim.api.nvim_echo({ { "Show diagnostics" } }, false, {})
    vim.diagnostic.enable()
  else
    vim.api.nvim_echo({ { "Disable diagnostics" } }, false, {})
    vim.diagnostic.disable()
  end
end
```

**Comment by rafi** [comment]
This one supports buffer/global toggle, and persists toggle after read/save.
Add this somewhere in your LSP `on_attach` function:
```
	if vim.b[bufnr].diagnostics_disabled or vim.g.diagnostics_disabled then
		vim.diagnostic.disable(bufnr)
	end
```

And use this toggle function:
```
function diagnostic_toggle(global)
	local vars, bufnr, cmd
	if global then
		vars = vim.g
		bufnr = nil
	else
		vars = vim.b
		bufnr = 0
	end
	vars.diagnostics_disabled = not vars.diagnostics_disabled
	if vars.diagnostics_disabled then
		cmd = 'disable'
		vim.api.nvim_echo({ { 'Disabling diagnostics…' } }, false, {})
	else
		cmd = 'enable'
		vim.api.nvim_echo({ { 'Enabling diagnostics…' } }, false, {})
	end
	vim.schedule(function() vim.diagnostic[cmd](bufnr) end)
end
```
