### ISSUE TITLE
Rendering glitch when loading a session file.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#1482]
I'm using [vim-startify](https://github.com/mhinz/vim-startify) which gives you commands to easily manage sessions. Session files are saved in ~/.vim/session, and a list of sessions is shown when NeoVim starts instead of the default vim start screen.

Loading a session causes neovim to go haywire. Here's two videos, the first one of vim without the glitch, and the second one of NeoVim with the glitch.
- http://youtu.be/z5rvNb8glTY
- http://youtu.be/EcljQMZhLwU

I've also confirmed that simply sourcing a session files causes the glitch. In case it's of any help, here's what the session file looks like:

``` viml
let SessionLoad = 1
if &cp | set nocp | endif
let s:so_save = &so | let s:siso_save = &siso | set so=0 siso=0
let v:this_session=expand("<sfile>:p")
silent only
cd ~/src/sk8earth/sk8earth-node
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
badd +0 sk8earth.css
badd +0 sk8earth.jade
badd +0 sk8earth.js
argglobal
silent! argdel *
set lines=65 columns=205
winpos 0 23
edit sk8earth.js
set splitbelow splitright
wincmd _ | wincmd |
split
wincmd _ | wincmd |
split
2wincmd k
wincmd w
wincmd w
set nosplitbelow
set nosplitright
wincmd t
set winheight=1 winwidth=1
exe '1resize ' . ((&lines * 38 + 32) / 65)
exe '2resize ' . ((&lines * 20 + 32) / 65)
exe '3resize ' . ((&lines * 2 + 32) / 65)
argglobal
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let s:l = 1 - ((0 * winheight(0) + 19) / 38)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
1
normal! 0
wincmd w
argglobal
edit sk8earth.jade
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let s:l = 9 - ((8 * winheight(0) + 10) / 20)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
9
normal! 012|
wincmd w
argglobal
edit sk8earth.css
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let s:l = 1 - ((0 * winheight(0) + 1) / 2)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
1
normal! 031|
wincmd w
2wincmd w
exe '1resize ' . ((&lines * 38 + 32) / 65)
exe '2resize ' . ((&lines * 20 + 32) / 65)
exe '3resize ' . ((&lines * 2 + 32) / 65)
tabnext 1
if exists('s:wipebuf')
  silent exe 'bwipe ' . s:wipebuf
endif
unlet! s:wipebuf
set winheight=1 winwidth=20 shortmess=filnxtToO
let s:sx = expand("<sfile>:p:r")."x.vim"
if file_readable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &so = s:so_save | let &siso = s:siso_save
doautoall SessionLoadPost
unlet SessionLoad
" vim: set ft=vim :
```

**Comment by fmoralesc** [comment]
@trusktr Can you see if this was fixed or improved by #3048?

**Comment by trusktr** [comment]
Hi @fmoralesc. Let me see if it is fixed. Before I try, another tidbit: I've been loading sessions created in NeoVim just fine. The glitch only happens when I load a session that was created with Vim. Luckily I still have some of those old session files.

**Comment by fmoralesc** [comment]
It was probably because vim's default 'sessionoptions' includes 'options', and that means it tries to save the value of '&col' and '&lines', which weren't properly handled by nvim before.

**Comment by trusktr** [comment]
@fmoralesc I just tried `brew reinstall --HEAD neovim`. No luck, I still have the same result: loading a Vim session still causes glitches.

**Comment by fmoralesc** [comment]
What terminal are you using? In iTerm2 you might need to allow resizing from applications (see https://github.com/neovim/neovim/pull/3048#issuecomment-122663323)

**Comment by trusktr** [comment]
I tried it in [NeoVim-e](https://github.com/coolwanglu/neovim-e) just now.

**Comment by fmoralesc** [comment]
Ah. Does NeoVim-e respect the 'columns' and 'lines' settings? Can you resize the window using `:set cols=` or `:winsize ...`?

**Comment by trusktr** [comment]
@fmoralesc Yes indeed it does.

**Comment by fmoralesc** [comment]
Ok, thanks for checking things out. I had seen glitches like this without the merged patches, so I wanted to confirm if they were fixed. Seems not :/

**Comment by trusktr** [comment]
Maybe your patch is part of the solution. (:

**Comment by elken** [comment]
Can confirm this issue, also works when sourcing my rc file in every term I tried (gnome term, urxvt, st and termite) in tmux.

**Comment by trusktr** [comment]
It just happened to me again in an SSH session yesterday (but the action
wasn't sourcing a file, it was something else, but I don't remember what),
although it hasn't happened for a really long time (so not as often as it
was happening before).

/#!/JoePea

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/5436 may have fixed this.
