### ISSUE TITLE
Appending to the `vim.opt.wildignore` default value leaves an empty element at the start; ignores all directories

### ISSUE THREAD

**Issue by ZeroKnight** [neovim/neovim#14828]
- `nvim --version`: `NVIM v0.5.0-dev+1417-g6a77def1e`
- Operating system/version: openSUSE Tumbleweed
- Terminal name/version: Konsole 20.12.3
- `$TERM`: `tmux-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set wildmode=longest,full
:lua vim.opt.wildignore:append{'*.foo', '*.bar'}
# Assuming `pwd` contains a dir named "hello", try to tab-complete:
:e h<TAB>
```

### Actual behaviour

- `:set wildignore?` will result in `wildignore=,*.foo,*.bar` (note the leading comma)
- Attempting to tab-complete the above will **not** expand to "hello".

### Expected behaviour

- `:set wildignore?` should result in `wildignore=*.foo,*.bar` (no leading comma)
- Attempting to tab-complete should expand to "hello"

---

The inclusion of the leading blank pattern seems to inadvertently ignore directories. If the leading blank is removed, you'll get the expected behavior:

    # After the reproduction:
    :lua vim.opt.wildignore:remove('')

**NOTE**: The leading blank element is **not** added when using `:set+=`, only with the `vim.opt` append method and operator.

**Comment by rktjmp** [comment]
I know why this happens.
