### ISSUE TITLE
python venv activation on run nvim

### ISSUE THREAD

**Issue by peach-lasagna** [neovim/neovim#14834]
- `nvim --version`: NVIM v0.5.0-dev

Hello I am running into pyright nvim lsp not seeing my venv when running nvim gui. I think this is where the problem lies:
https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/pythonx.vim#L13

**Comment by mjlbach** [comment]
The python provider has nothing to do with pyright detecting your appropriate virtual environment. You need to set up the VIRTUAL_ENV environmental variable to point to the correct virtual environment when launching pyright, which is done via uv_spawn. One example is doing this with a shell script:

https://github.com/neovim/nvim-lspconfig/issues/500#issuecomment-752327577

Another option would be passing the VIRTUAL_ENV value in cmd_env in setup{} call of start_client, which passes it to uv_spawn. This can be done in the on_new_config hook in lspconfig.
