### ISSUE TITLE
Ctrl-Alt-Space isn't recognized, even though terminal sends ^[^@ (works in vim)

### ISSUE THREAD

**Issue by bew** [neovim/neovim#14836]
- `nvim --version`: `v0.4.3`
- Operating system/version: (Arch)Linux, up to date
- Terminal name/version: Wezterm 20210502-154244-3f7122cb
- `$TERM`: `xterm-256color`

[YES] `vim -u DEFAULTS` (version: `8.2.2891`) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC (or vim -u DEFAULTS)
Then type `:` (to open the cmdline)
Then do Ctrl-v
Then do Ctrl-Alt-Space
Watch what is printed to the cmdline
```

### Actual behaviour

In vim: `^[^@`
In neovim: `^[`

### Expected behaviour

Get `^[^@` in both, or even have `<M-C-Space>` in neovim

**Comment by glacambre** [comment]
@bew could you try master/nightly? :)

**Comment by bew** [comment]
Hello @glacambre I just downloaded the appimage from the latest nightly `NVIM v0.5.0-dev+1423-ge2d3ad7bc` and the behavior is still the same.
(it's not fixed)

**Comment by hazeled** [comment]
I tried replicating the issue with @bew's steps, and it just switches from `COMMAND` to `NORMAL` mode for me

**Comment by bew** [comment]
@hazeled are you sure your terminal sends the correct sequence?
(You can verify by running `cat` and pressing the keys)

For completeness I checked with the latest 0.5.0 stable release, the behavior is the same (not surprisingly).

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/2379 https://github.com/neovim/neovim/issues/6279

**Comment by zeertzjq** [comment]
I think the problem here is that Ctrl-Alt-Space is recognized as a "forced escape" (`ESC NUL`).

**Comment by ZizouHuweidi** [comment]
> I think the problem here is that Ctrl-Alt-Space is recognized as a "forced escape" (`ESC NUL`).
> 
> Making `handle_forced_escape()` always only return `false` makes Ctrl-Alt-Space work:
> 
> ```diff
> diff --git a/src/nvim/tui/input.c b/src/nvim/tui/input.c
> index 5fec41f9a..0799153f8 100644
> --- a/src/nvim/tui/input.c
> +++ b/src/nvim/tui/input.c
> @@ -429,16 +429,6 @@ static HandleState handle_bracketed_paste(TermInput *input)
>  // ESC NUL => <Esc>
>  static bool handle_forced_escape(TermInput *input)
>  {
> -  if (rbuffer_size(input->read_stream.buffer) > 1
> -      && !rbuffer_cmp(input->read_stream.buffer, "\x1b\x00", 2)) {
> -    // skip the ESC and NUL and push one <esc> to the input buffer
> -    size_t rcnt;
> -    termkey_push_bytes(input->tk, rbuffer_read_ptr(input->read_stream.buffer,
> -                                                   &rcnt), 1);
> -    rbuffer_consumed(input->read_stream.buffer, 2);
> -    tk_getkeys(input, true);
> -    return true;
> -  }
>    return false;
>  }
> ```
> 
> Is "forced escape" really needed? There is already another way to encode an unambiguous ESC keystroke: `ESC [ 27 u`.

pull request worked just fine for me (Arch)
