### ISSUE TITLE
keep help text in lua plugin

### ISSUE THREAD

**Issue by yuhuihu** [neovim/neovim#14837]
keep help text in lua plugin and any other plugin.

And keep it as party of the new plugin sys.

Because perfect document is the best tutor for contributor and greenhands.  Doc text in lua plug is not enough.

**Comment by shadmansaleh** [comment]
Sorry I don't understand what you're trying to mean here. But plugin documentation is plugin issue . If you think documantation on some plugin is lacking you should open an issue in that plugin not in neovim repo .
