### ISSUE TITLE
Cursor jumps into function signature help floating window

### ISSUE THREAD

**Issue by loshjawrence** [neovim/neovim#14846]
- failing commit hash `a03ffe1`
 built with:
 ```
 rm -rf build
 make distclean
 make CMAKE_BUILD_TYPE=Release
 sudo make install
 ```

- working `nvim --version`: NVIM v0.5.0-dev+1229-g91cdc1198
 `Merge pull request #14309 from mjlbach/feature/hover_return_win_buf`
 Not sure if this is the earliest working version but it is a version that works.
 Built with same script as above

- Terminal name/version: WLS2 20.04.1 LTS (Focal Fossa)
- `$TERM`: xterm-256color: command not found

**My testing minimal init.vim**
```
call plug#begin('~/.vim/bundle')
    Plug 'neovim/nvim-lspconfig'
    Plug 'nvim-lua/completion-nvim'
call plug#end()
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
lua require'lspconfig'.tsserver.setup{on_attach=require'completion'.on_attach}
au Filetype javascript setl omnifunc=v:lua.vim.lsp.omnifunc
set completeopt=menuone,noinsert,noselect
```

**How to reproduce**
1. Get the function signature help to pop up by typing some params in a function call.
2. Sometimes cursor will window jump into the floating window. for me its >50% of the time.
3. Can try to brute force trigger by holding `,` or holding delete on a long string of `,`
![image](https://user-images.githubusercontent.com/13598291/122481015-f3143380-cf9b-11eb-9d6f-2dd25172f8ce.png)

**Expected behavior**
The cursor should not jump into the floating window of the function signature help.

**Comment by mjlbach** [comment]
You need to set focusable=false in opts passed to signature_help (see the documentation.

**Comment by loshjawrence** [comment]
idk seems like a bug since the behavior is inconsistent. sometimes it steals the cursor and sometimes it does not. I'm not trying to focus it by clicking it with a mouse or window jumping. It's really odd to be typing along an then cursor is suddenly in a floating window.

is there a some reason this is now the default (passed that working commit)? This isn't the same behavior in other editors . Not that that should be some goal, it's just for floating window signature help, there's no reason not to behave exactly the same as it would in any other editor out of the box.

**Comment by mjlbach** [comment]
By default, signature help is does *not* automatically get called when you are in a function arglist, that's provided by completion.nvim. You should file an issue with the plugin. The underlying API that completion.nvim calls is implemented in neovim core, but not the logic for triggering the signature help window.

**Comment by wllenyj** [comment]
The same problem is on `vim.lsp.show_line_diagnostics`

**Comment by clason** [comment]
...with the same answer: this is by design (you might wish to copy something from the documentation), can be easily overridden, and any problem with unexpected focus stealing is very likely due to whatever plugin or config is triggering the line diagnostics (and should therefore be reported there first).
