### ISSUE TITLE
Bug: Tip HelpCurwin from docs gives error in neovim but not in vim

### ISSUE THREAD

**Issue by reportaman** [neovim/neovim#14847]
- nvim version:
```
NVIM v0.5.0-dev+nightly-356-gb28d458f8
Build type: Release
LuaJIT 2.1.0-beta3
```
- Operating system/version: macOS BigSur 11.4 ARM64
- Terminal name/version: WezTerm, Apple's inbuilt Terminal, iTerm2, Alacritty.
- `$TERM`: doesn't matter, varies by terminal above. I am using xterm-256color in general.

### Steps to reproduce

1) Add following snippet of code from nvim/vim help docs (look for ``help-curwin`` in [tips.txt](https://neovim.io/doc/user/tips.html)) into your .vimrc:

```vim
	command -bar -nargs=? -complete=help HelpCurwin execute s:HelpCurwin(<q-args>)
	let s:did_open_help = v:false
	
	function s:HelpCurwin(subject) abort
	  let mods = 'silent noautocmd keepalt'
	  if !s:did_open_help
	    execute mods .. ' help'
	    execute mods .. ' helpclose'
	    let s:did_open_help = v:true
	  endif
	  if !getcompletion(a:subject, 'help')->empty()
	    execute mods .. ' edit ' .. &helpfile
	  endif
	  return 'help ' .. a:subject
	endfunction
```

2) Close and reopen neovim

3) Run command ``:HelpCurwin`` with usual ``:help`` semantics.

###
Upon performing step 3), the following error is observed:
```
Error detected while processing function <SNR>2_HelpCurwin:
line    7:
E745: Using a List as a Number
E15: Invalid expression: !getcompletion(a:subject, 'help')->empty()
Press ENTER or type command to continue
```

### Expected behaviour

Vim does not give this error, and works perfectly as marketed in help file tips.txt, i.e. it opens help in current window. Neovim docs have this as an example, but neovim gives error on this. Ideally this would work in neovim too.

### Source of code 
Search for ``help-curwin`` in https://vimhelp.org/tips.txt.html or https://neovim.io/doc/user/tips.html

**Comment by seandewar** [comment]
v8.1.1803 needs porting.
