### ISSUE TITLE
elixir files (*.ex, *.exs) are not being recognized correctly

### ISSUE THREAD

**Issue by juantascon** [neovim/neovim#14842]
- `nvim --version`: NVIM v0.5.0-dev+1421-ga72dfec85
- Operating system/version: voidlinux
- Terminal name/version: kitty
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC mix.exs
OR
nvim -u NORC sup.ex
```

### Actual behaviour
:set filetype
filetype=
### Expected behaviour
:set filetype
filetype=elixir

**Comment by rktjmp** [comment]
I don't believe vim comes with elixir support built in (there is no elixir file in `runtime/ftplugin`). You need https://github.com/elixir-editors/vim-elixir/.

**Comment by aegatlin** [comment]
I opened a feature request issue on this in vim https://github.com/vim/vim/issues/8401

**Comment by stsewd** [comment]
The patch to be ported is https://github.com/vim/vim/commit/f3caeb63d62c08b579e9b5f40b35e8bf64dde87a

**Comment by clason** [comment]
... which has already happened in #14914 :)

(any faster and @janlazo travels back in time!)
