### ISSUE TITLE
lagging cursor movement in big json with tree-sitter 

### ISSUE THREAD

**Issue by comicfans** [neovim/neovim#14852]
- `nvim --version`:  
```
NVIM v0.5.0-dev+1424-g96d83e2a6
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/wangxinyu/neovim/build/config -I/home/wangxinyu/neovim/src -I/home/wangxinyu/neovim/.deps/usr/include -I/usr/include -I/home/wangxinyu/neovim/build/src/nvim/auto -I/home/wangxinyu/neovim/build/include
Compiled by wangxinyu@PRODUCTION

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/wangxinyu/.local/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: archlinux x64
- Terminal name/version: ssh
- `$TERM`: xterm

[ ] `vim -u DEFAULTS` (version: ) behaves differently:  not tried

### Steps to reproduce using `nvim -u NORC`

```
only happen when tree-sitter highlight is enabled. nvim -u NORC cursor move much quicker
```

### Actual behaviour

while enabling tree-sitter highlight with following config:
```
set nocompatible
filetype off


call plug#begin('~/.vim/bundle')

"vim-scripts

Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
call plug#end()


lua << EOF


require'nvim-treesitter.configs'.setup {
    ensure_installed = "maintained",
    highlight = {
        enable = true
    },
    indent = {
        enable = true
    }
}

EOF
```

cursor movement in one line big json is much slower than nvim -u NORC. especially when cursor hit json object/array start mark(seems nvim is trying to highlight the corresponding mark).  I've test both config by continuous moving cursor around json object mark.

* while using -u NORC,  it's a little slower than normal movement, but still acceptable. profiler shows that addstate consume 16% and then nfa_regmatch consume 14% cputime. 
* while using tree-sitter config,  movement is much lagged around json start mark,  profiler shows that decor_redraw_col consume 53% cputime. switching build type to RelWithDebInfo, profiler shows that decoration.c
```
  302   size_t j = 0;
  303   for (size_t i = 0; i < kv_size(state->active); i++) {
  304     DecorRange item = kv_A(state->active, i);     -----> 38% of hotspot
  305     bool active = false, keep = true;
  306     if (item.end_row < state->row                             -----> 9%  of hotspot (I guess it came from kv_size)
  307         || (item.end_row == state->row && item.end_col <= col)) {
  308       if (!(item.start_row >= state->row && kv_size(item.decor.virt_text))) {
  309         keep = false;
  310       }

...
 
  332     if (keep) {
  333       kv_A(state->active, j++) = item;               -----> 23% of hotspot
  334     } else if (item.virt_text_owned) {
  335       clear_virttext(&item.decor.virt_text);
  336     }

```

and no matter if tree-sitter is enabled, nvim both hang for minutes if jump from very first json mark to corresponding end mark by pressing '%'. profiler shows addstate/nfa_regexmatch as hotspot( similar to using -u NORC to moving around json mark). seems nvim is spending time in regex.

### Expected behaviour
neovim should be responsive.

**Comment by comicfans** [comment]
@vigoux  maybe you're interested in this problem.

**Comment by vigoux** [comment]
Indeed it's interesting!
I'll try to see what I can do!

**Comment by vigoux** [comment]
I can indeed reproduce it locally (just make nvim `compile_command.json` into one line).

The thing is that it depends on the column you are in. And the performance issue only seems to happen on the very first column.
It also seem to get worst the further we get to the end of the line.

**Comment by bfredl** [comment]
IIUC the decorations code take no account of `w_skipcol`, even tho the marktree data structure itself has no problem with long lines. When displaying really long lines, we need to skip the iterator to the first displayed column, and also stop at the last displayed column if it doesn't fit the end of the window. probably this information also needs to be forwarded to decoration provider (so same adjustments can make to the TS tree iteration).

**Comment by vigoux** [comment]
Yep, that's what we need to do.
Or we can filter that out when calling `set_extmark` with `ephemeral` on, this way the decoration provider does not need to think about it?

**Comment by bfredl** [comment]
> Or we can filter that out when calling set_extmark with ephemeral on, this way the decoration provider does not need to think about it?

That doesn't completely cover it. we want to avoid to iterate through the tree-sitter subtrees that are outside the display, so the provider needs access to the skipped and maximum column.

**Comment by justinmk** [comment]
Fixed by https://github.com/neovim/neovim/pull/18760

May be revisited in https://github.com/neovim/neovim/pull/18109
