### ISSUE TITLE
Tab / Buffer Grouping

### ISSUE THREAD

**Issue by ZeroZXZ** [neovim/neovim#14855]
### Actual behaviour
Currently there's no way to group related tabs or related buffers together. Yes, those are 2 features.

### Expected Behaviour
It would be nice if we could group related tabs(or buffers) together:

Grouping Tabs Together:
Example 1: let's say I have 6 different tabs with school related documents open, and I want to group them in a single tab, yet keeping the existing tabs in the same model(as tabs, instead of windows). Then I would have School Tab grouping together all those other 6 different school tabs.

Grouping Buffers Together:
example 2.: let's say I have 3 buffers open on 3 different windows on 1 same tab. Now pretend that I want to open them in a different tab just the same way I would open a buffer by typing :b <buffer_name> , currently there is no way to get this done neither.

Currently, I would have to either move to the pre-existing tab OR re-open those same 3 buffers and set the same windows size for all of them by hand.

The reason I want the Grouping Buffers feature, is because I want to be able to change one of the 3 open buffers to something else on the go IN A DIFFERENT TAB, but I want to keep the previous tab untouched.

example 3.: 
tab 1: MainPage.html, my_css.css, my_javascript.js
tab 2: SubPage.html, my_css.css, my_javascript.js

Then I need to create 3rd tab with the same files open, plus a 4th new buffer/window:
tab 3: MainPage.html, my_css.css, my_javascript.js, new_page.html 

Currently I would have to summon all 4 buffers manually by hand to have the third tab, even tho the 1st tab is already there. I'm not aware if it's possible to copy/clone a tab into another tab. But it would still be nice if you could just group related buffers/tabs together and call them by name just like we currently do for tabs and buffers.

**Comment by justinmk** [comment]
For "grouping" anything, consider using a `t:` (tab-local) vimscript variable, or a global (`g:`) Dict variable.

> I'm not aware if it's possible to copy/clone a tab into another tab. 

In the tab, do this:

- One can use `gettabinfo()['windows']` to restore the buffers in a new tab. 
- I'm not sure if the tab _layout_ is exposed yet: #3933

> But it would still be nice if you could just group related buffers/tabs together and call them by name just like we currently do for tabs and buffers.

Sure, but "nice to have" typically is not strong justification for a niche feature in core, if a plugin or script can reasonably achieve the feature.
