### ISSUE TITLE
autocmd doesn't work in init.lua but works in init.vim

### ISSUE THREAD

**Issue by valignatev** [neovim/neovim#14850]
- `nvim --version`:
```
NVIM v0.5.0-dev+1417-g6a77def1e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Скомпилирован  runneradmin@fv-az152-902

Features: -acl +iconv +tui
See ":help feature-compile"

            общесистемный файл vimrc: "$VIM\sysinit.vim"
          значение $VIM по умолчанию: "C:/Program Files/nvim/share/nvim"
```
- Operating system/version:
Windows 10 Pro 20H2
- Terminal name/version:
neovim-qt or powershell
- `$TERM`:
...

Both
```
:autocmd FileType * setlocal formatoptions-=ro
```
and
```
:lua vim.cmd[[autocmd FileType * setlocal formatoptions-=ro]]
```
work as expected though. So only cmd call in init.lua gets ignored. The same autocmd in vanilla init.vim works successfully. Maybe it's somehow related to https://github.com/neovim/neovim/issues/14798?

### Steps to reproduce
```
-- in init.lua
vim.cmd[[autocmd FileType * setlocal formatoptions-=ro]]
```

### Actual behaviour
vim.cmd doesn't affect newly opened files, `:set formatoptions` still shows the default value `jcroql`

### Expected behaviour
formatoptions should become jcql for newly opened files.

**Comment by clason** [comment]
Can you do a few more tests to see what exactly is not working? (I.e., try a few different autocommands that just `echo 'foo'` and see if they trigger.)

**Comment by valignatev** [comment]
seems like `:autocmd FileType * echom "KLSDFJKLSDFJKL"` doesn't work at all, regardless whether called from lua config or directly as a command

**Comment by chrisbra** [comment]
did you check `:mess`? Have you tried this with `:set cpo-=F`?

**Comment by valignatev** [comment]
yeah, messages don't have anything from my custom echom. What should I expect from removing `F` from cpo?

**Comment by valignatev** [comment]
Ok it's really weird. Seems like it works sporadically? I mean, it doesn't work, but then after a while I see one test echo in the message history. But after restart it doesn't work again. Seems like modifiing cpo doesn't particularly affect it

**Comment by pranair** [comment]
For some reason, running `:autocmd FileType * echo "message"` seems to work fine when command line window or quickfix window is opened.

**Comment by beardedsakimonkey** [comment]
FWIW i was not able to reproduce this
init.lua:
```lua
vim.cmd[[filetype plugin on]]
vim.cmd[[autocmd FileType * setlocal formatoptions-=ro]]
```
i ran `nvim a.vim` in a terminal
i ran the command `:set fo`
it prints out `formatoptions=jcql`

However, I was running into a similar issue, but I realized it was because I was removing a flag that was not already set (I was doing `fo-=rot`), and, as hinted at in `:help set-=`, it seems like if one of the flags you are removing isn't already set, the whole command will fail.  I understand this isn't the case described in the issue - I'm just calling it out in case it helps anyone else running into this issue.

**Comment by valignatev** [comment]
Just checked the latest 0.6 nightly and it's indeed working now, so thanks a lot!
