### ISSUE TITLE
Stausline with another window open fills up with "^" characters

### ISSUE THREAD

**Issue by samrath2007** [neovim/neovim#14857]
- `nvim --version`:NVIM v0.5.0-dev+1417-g6a77def1e
- Operating system/version:MacOS Big Sur
- Terminal name/version: Iterm2, fish

### Actual behaviour
![image](https://user-images.githubusercontent.com/69572668/122638486-f3ced600-d111-11eb-88d3-58dccaba0f99.png)

### Expected behaviour

No ^^^ in the statusline(I have tried many of them). My config is [here](https://github.com/samrath2007/Dotfiles/tree/main/.config/nvim)

**Comment by glacambre** [comment]
This doesn't happen with `nvim -u NORC` so please provide a minimal reproducer for us to investigate. :)

**Comment by samrath2007** [comment]
> This doesn't happen with `nvim -u NORC` so please provide a minimal reproducer for us to investigate. :)

I removed a couple of plugins and it went away(seems like a theme glitch).
