### ISSUE TITLE
rpc.lua:553: attempt to index upvalue 'message_callbacks' (a nil value)

### ISSUE THREAD

**Issue by mcepl** [neovim/neovim#14863]
When briefly opening a file with neovim a03ffe160 (Linux/openSUSE/Tumbleweed, terminal alacrity with `TERM=xterm-256color`) I’ve got this error message on stderr:
```
python-backports@stitny (master)$ vim backports_repo.py
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:553: attempt to index upvalue 'message_callbacks' (a nil value)python-backports@stitny (master)$
```

I cannot reproduce it any more, it is probably not a big deal, just that the value can actually be `nil`, so it should be checked before accessing.

**Comment by mjlbach** [comment]
There should never be a scenario in which message_callbacks is not a table, so I'm confused how this can be happening. message_callbacks is created on client start, and is only set to `nil` after stdin/stdout closes during shutdown of the language server (see https://github.com/neovim/neovim/blob/1df8a34a7b91028413d6ac751b9dbf9fdcd6cda2/runtime/lua/vim/lsp/rpc.lua#L352-L366) .

@mfussenegger do you have any ideas?

**Comment by mfussenegger** [comment]
I suspect it could be a race condition, I think `onexit` runs in the luv event loop and something else could call `request` in the main loop. `onexit` sets `message_callbacks` to `nil` and then the `request` logic (which was triggered earlier/concurrently) tries to access it.

We could probably set `message_callbacks` to `{}` in `onexit` instead of `nil`.

**Comment by mjlbach** [comment]
That's a good idea/fix. Is there a way we should be cancelling all outstanding requests from the main thread? I don't think we can, but just brainstorming as I can imagine there might be other edge cases like this.

**Comment by mjlbach** [comment]
@mfussenegger one thing, if we allow message_callbacks to an empty table, are we going to prevent GC on any outstanding callbacks? Would it be better to just add checks if message_callbacks is nil as suggested by @mcepl? It's only checked in 3 places.

**Comment by mfussenegger** [comment]
> if we allow message_callbacks to an empty table, are we going to prevent GC on

Resetting `message_callbacks` to `{}` will also clear the reference - so if nothing else holds any references to the original table or any of the items they can be GC'd.

But the `request` function in rpc might add something to the new table. Not sure if that is an issue, given that the client should become eligible for GC once the client is stopped.

**Comment by mjlbach** [comment]
> But the request function in rpc might add something to the new table. Not sure if that is an issue, given that the client should become eligible for GC once the client is stopped.

This is more the scenario I am thinking of
