### ISSUE TITLE
[nvim-lsp] Support CodeAction diagnotic sign

### ISSUE THREAD

**Issue by ldelossa** [neovim/neovim#14869]
- `nvim --version`: 0.5.0
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Fedora
- Terminal name/version: Tilix
- `$TERM`: zsh

Currently, I do not see any sign declaration on lines where CodeActions can take place. Is there any plans to add this to diagnostics?

**Comment by mjlbach** [comment]
This isn't possible to do in a non-hacky way with the current spec. Plugins like lsp-lightbulb work by caching the code actions available on each line by calling the code action handler at each location with a dummy handlers, and checking if the code action is present. Any autocommand bound request like this will add some additional performance overhead. I'd rather make an RFC to allow subscribing to code actions the same way diagnostics work, sending a list of lines with available code actions.

**Comment by ldelossa** [comment]
Thank you @mjlbach 

Is there any suggestion on how to become aware of code actions when they are available in a document?

**Comment by mjlbach** [comment]
So there is https://github.com/kosayoda/nvim-lightbulb, however it works in the way that I described as being "hacky". It will only refresh diagnostics on lines you are currently on.

**Comment by ldelossa** [comment]
Yes I see, and that's way too "in your way" for my personal taste. 

Right now I have added this to my "on_attach" method:

```
-- Use an on_attach function to only map the following keys 
-- after the language server attaches to the current buffer
local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end
  -- reference codelens when opening file.
  vim.lsp.codelens.refresh()
...
```

which does an OK job for codelens - anytime a buffer is opened I get virtualtext showing any codelens. I'm assuming this is not possible for CodeActions?

**Comment by mfussenegger** [comment]
> which does an OK job for codelens - anytime a buffer is opened I get virtualtext showing any codelens. I'm assuming this is not possible for CodeActions?

Code lenses can be retrieved for a full document, but the same is not possible for code actions.

If a client requests code-actions, the client needs to provide a context - the location/range for which you want the code actions and also the diagnostics that got reported in the area (=the ones you as user might want to fix).

Lightbulb basically asks the server for code actions each time you don't move the cursor for a bit. Depending on the server that can have a bit of an impact. 


You could put something like this in a file like `lua/foo.lua`

```lua
local M = {}

function M.bar()
  local context = { diagnostics = vim.lsp.diagnostic.get_line_diagnostics() }
  local params = lsp_util.make_range_params()
  params.context = context
  vim.lsp.buf_request(0, 'textDocument/codeAction', params, function(err, _, result)
    -- do something with result - e.g. check if empty and show some indication
  )
end

return M
```

And then bind the function to `autocmd CursorHold,CursorHoldI * lua require('foo').bar()` to basically have your own light bulb implementation.

**Comment by mjlbach** [comment]
Given there is not a good way to query code action locations without a context, I'm going to close this for now. I added the above snippet to the lspconfig wiki as a workaround. Feel free to reopen if Microsoft adds something to LSP protocol to fetch code action candidate locations.
