### ISSUE TITLE
lsp(ux): always/never focus the quickfix window/location list in handlers

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#14877]
It was brought up on matrix by @seandewar that we call `wincmd p` by default for several handlers that open the quickfix list. This prevents losing focus of the editing area (useful when populating the quickfix list with diagnostics), but may be unintuitive to those used to the quickfix list stealing focus (although, they may not know they are opening the quickfix list with the handler). 

We'll solicit user feedback and determine whether we should change the default. I personally don't use this function, so I don't have a strong opinion.

**Comment by seandewar** [comment]
Thanks! Also related: #12906.
