### ISSUE TITLE
TUI: screen messed up when inserting newline with `set nu`

### ISSUE THREAD

**Issue by CarterLi** [neovim/neovim#14872]
- `nvim --version`: v0.4.4
- Operating system/version: 5.10.16.3-microsoft-standard-WSL2
- Terminal name/version: Windows Terminal Preview 1.9.1523.0
- `$TERM`: xterm-256color

[x] `vim -u DEFAULTS` (version: 8.2) behaves differently

vim doesn't have this issue

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```

* nvim -u NORC
* i
* Input some text. In my case  
```
if &shell =~# 'fish$'
  set shell=sh
endif

set termguicolors

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'mhinz/vim-startify'
Plug 'lambdalisue/battery.vim'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'rhysd/committia.vim'
Plug 'preservim/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'dag/vim-fish'
Plug 'chrisbra/csv.vim'
Plug 'neoclide/coc-git'
Plug 'bling/vim-bufferline'
Plug 'vim-airline/vim-airline'
call plug#end()

let g:airline_powerline_fonts = 1
set updatetime=100
set nu
set laststatus=2
```

* <ESC> `:10` `:set nu`

![image](https://user-images.githubusercontent.com/6134068/122737357-8a86c880-d2b3-11eb-9abf-31a778fe6566.png)

* o

![image](https://user-images.githubusercontent.com/6134068/122737450-9ecac580-d2b3-11eb-8b50-61a51a0c2a9e.png)

### Actual behaviour

The text become a mass ( sorry for my bad English )

### Expected behaviour

A new line should be added without changing other text.

### Note

This issue doesn't happen with `env -i TERM=ansi-256color nvim`

**Comment by CarterLi** [comment]
Confirmed that this issue only occurs when $TERM contains `xterm`

eg.

1. `env -i TERM=xterm-256color nvim` buggy
2. `env -i TERM=xterm nvim` buggy
3. `env -i TERM=vt100 nvim` ok
4. `env -i TERM=ansi nvim` ok

**Comment by justinmk** [comment]
> Confirmed that this issue only occurs when $TERM contains `xterm`

Then that is a bug in Windows Terminal, or you need to set $TERM correct. If Windows Terminal claims to support xterm then it needs to behave like xterm.
