### ISSUE TITLE
Inconsistent behavior of extmarks

### ISSUE THREAD

**Issue by tejasvi** [neovim/neovim#14873]
### Steps to reproduce
1. Buffer contains
   ```
   line 1
   line 2
   ```
2. Run
    ```
    :let g:ns  = nvim_create_namespace('bug')
    :let g:id = nvim_buf_set_extmark(0, g:ns, 0, 0, {})
    :echo nvim_buf_get_extmarks(0, g:ns, 0, -1, {})
    ```
    It gives `[1, 0, 0]`
3. Now do `ddp` (move line 1 below 2) and `:echo nvim_buf_get_extmarks(0, g:ns, 0, -1, {})`
   It gives `[1, 0, 0]` instead of `[1, 1, 0]` or throwing error like conventional marks.

Essentially, the extmarks are not removed when the line is deleted.

**Comment by glacambre** [comment]
According to `:help api-extended-marks`:

> Deleting all text surrounding an extmark does not remove the extmark. To remove an extmark use |nvim_buf_del_extmark()|.

So I think that's the expected behavior. Why are you expecting something different? :)

**Comment by tejasvi** [comment]
@glacambre Not the case with conventional marks, at least. Check with `madd'a`. Unfortunately, this makes extmarks unreliable while tracking lines, but I guess that's the subject of another discussion.

**Comment by bfredl** [comment]
but what you added is an extmark which tracks the position (0,0), it knows nothing of the integrity of the line as a whole. What you want might be possible with an extrange covering the entire line `(0,0) - (0, strlen(line1))`, which is planned for 0.6.
