### ISSUE TITLE
tree-sitter highlighter.lua report end_col value outside range

### ISSUE THREAD

**Issue by comicfans** [neovim/neovim#14882]
- `nvim --version`:NVIM v0.5.0-dev+1357-g192f89ea1
- Operating system/version: archlinux x64
- Terminal name/version: run from neovim-qt
- `$TERM`:

[ ] `vim -u DEFAULTS` (version: ) behaves differently: not tried 

### Steps to reproduce using `nvim -u NORC` 

```
nvim -u NORC
can not reproduce after reopen nvim, or running with nvim -u NORC

```

### Actual behaviour

I'm editing a C++ header file, highlighter worked at first, but I inserted a new line
in code, tree-sitter error just appeared ,and all lines after the error line lose highlight.
the error shows:
```
treesitter/highlighter: Error executing lua: ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:259: end_col value outside range
```

I can't reproduce such problem if re-open neovim.

**Comment by dundargoc** [comment]
Since the duplicate has been solved I assume this one has too.
