### ISSUE TITLE
  vim.api.nvim_echo( ) Fail in lua.

### ISSUE THREAD

**Issue by Borwe** [neovim/neovim#14880]
- `nvim --version`: 
NVIM v0.5.0-dev+1339-g5d9c56012
Build type: Release
LuaJIT 2.1.0-beta3

- Operating system/version: Windows 10
- Terminal name/version: neovim-qt, and cmd.exe
- `$TERM`: CMD.EXE

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`
just call from lua 
```
vim.api.nvim_echo( {"Hello Test","WarningMsg"},true,{})
```

### Actual behaviour
Error:
```
Chuck is not an array, 
```

### Expected behaviour
Print "Hello Test" with WarningMsg highlights.

**Comment by bfredl** [comment]
You need `vim.api.nvim_echo( {{"Hello Test","WarningMsg"}},true,{})`

**Comment by Borwe** [comment]
> 
> 
> You need `vim.api.nvim_echo( {{"Hello Test","WarningMsg"}},true,{})`

What do the {} intepret to then? I thaught they turn to list/array, since vim.fn.termopen({}) works good.

**Comment by bfredl** [comment]
a list. The documentation mentions a "list of chunks" which in turn should be two-element lists.
