### ISSUE TITLE
[nvim-lsp] RPC[Error] in status bar

### ISSUE THREAD

**Issue by ldelossa** [neovim/neovim#14885]
- `nvim --version`: NVIM v0.5.0-dev+1428-g997a9c879
- Operating system/version: Fedora 34
- Terminal name/version: tilix
- `$TERM`: xterm-256color

https://github.com/ldelossa/dotfiles/blob/louis/just-neovim-lsp/nvim/nvim-lsp.vim

### Actual behaviour

When utilizing nvim-lsp and doing typical Golang developement I begin seeing the following errors on my status line:

```
RPC[Error] code_name = unknown, code = 0, message = "327:4: missing ',' before newline in argument list (and 1 more errors)"
RPC[Error] code_name = unknown, code = 0, message = "328:4: missing ',' before newline in argument list (and 1 more errors)"
4 fewer lines
RPC[Error] code_name = unknown, code = 0, message = "325:3: expected '}', found 'EOF'"
4 more lines; before #26  7 seconds ago
RPC[Error] code_name = unknown, code = 0, message = "328:4: missing ',' before newline in argument list (and 1 more errors)"
RPC[Error] code_name = unknown, code = 0, message = "329:4: missing ',' before newline in argument list (and 1 more errors)"
RPC[Error] code_name = unknown, code = 0, message = "141:2: expected '}', found 'case' (and 1 more errors)"
RPC[Error] code_name = unknown, code = 0, message = "153:46: missing ',' in argument list (and 10 more errors)"
```
Now, I am not sure if these are sponses from the LSP, or if this is the nvim library bubbling up an error. If it is the former, I'd like to silence them, if it is the latter, I'd like to know how to fix these issues. 

### Expected behaviour

These errors are not present in my status log.

**Comment by mjlbach** [comment]
Need more info, do you have a minimal golang file that reproduces this?

**Comment by ldelossa** [comment]
A bit tough to reproduce with only a minimal file. It seems like it becomes an issue when multiple diagnotics are going on.

**Comment by mjlbach** [comment]
Try removing this line https://github.com/ldelossa/dotfiles/blob/9fbfa6cb3f7ac376b840513ebb401cb4c19cd2df/nvim/nvim-lsp.vim#L20

 and see if it goes away

**Comment by ldelossa** [comment]
That did not help, tho I did mean to change that to the autocmd suggested in 'h :lsp' .

After a bit more testing, I'm realizing its occuring when the document losses some sense of structure. 

Here is a gofile to reproduce:

```
package main

import (
	"log"
)

func main() {
	if nil = nil {
		log.Fatal(err)
	
	log.Printf("%v", t)
}
```

Attempting to save this file reproduces every time.

**Comment by mjlbach** [comment]
That doesn't show up in the status bar for me. Try reproducing with the minimal config referenced in the issue template.

**Comment by ldelossa** [comment]
Okay its from this:

```
autocmd BufWritePre *.go silent! lua vim.lsp.buf.formatting()
``` 

Apparently the formatting rpc call will fail since an error is in the document.

**Comment by ldelossa** [comment]
Closing issue, but if you have suggestion on format on save which does not break when the format is not valid syntax LMK. Thank you for helping with this!!

**Comment by mjlbach** [comment]
It's not that it's broken, it's that gopls will refuse to format the document with that error IIRC. It would have to be addressed server-side.

**Comment by ldelossa** [comment]
Anyway to silent it from the vim status line?

**Comment by mjlbach** [comment]
It's throwing an error because the error code returned from gopls (0) doesn't correspond to an error we match against. I don't know if 0 is a valid error code in the spec

https://github.com/neovim/neovim/blob/cf4033034a5557ba46a147d5b1d47b9e643cb040/runtime/lua/vim/lsp/rpc.lua#L189-L228

**Comment by ldelossa** [comment]
Worth a cross ticket into gopls/
