### ISSUE TITLE
Issues with + in file name or path on Windows

### ISSUE THREAD

**Issue by amoweb** [neovim/neovim#14898]
- `nvim --version`: NVIM v0.5.0-dev+1434-g24e0c16fd
- Operating system/version: Windows 10
- Terminal name/version: -
- `$TERM`: -

### Steps to reproduce using `nvim -u NORC`

```
Create a files +a.txt (put content to see the problem)
nvim -u NORC
:e +a.txt
File not found
:e \+a.txt
```

### Actual behaviour
a.txt is not opened

### Expected behaviour
Under Linux, `:e \+a.txt` opens the file.

**Comment by pranair** [comment]
Have you tried opening with `:e .\+a.txt`? 
Using `:e \+a.txt` does not work because it actually tries to open C:\+a.txt, which doesn't exit.

**Comment by amoweb** [comment]
Thank you, it works this way.
