### ISSUE TITLE
Treesitter 0.19.5 unlimited pending matches makes Neovim unusable when active

### ISSUE THREAD

**Issue by levouh** [neovim/neovim#14897]
- `nvim --version`: `NVIM v0.5.0-dev+1434-g24e0c16fd`

### Steps to reproduce

1. Install `nvim-treesitter`
2. Ensure it is the only plugin installed, and is setup something like:
```
vim.cmd('packadd nvim-treesitter')
require('nvim-treesitter.configs').setup {
    ensure_installed = { 'python' },
    highlight = {
        enable = true,
    },
}
```
3. Update to the latest parsers with `:TSUpdate`/`:TSInstall`
4. Open a large _Python_ buffer (find something in the system `site-packages` with `find / -type d -name 'site-packages' 2>/dev/null` or similar).

Note that this is not reproducible before `3085788a3ef84cebaf532bbe77fde6df16a694a2`.

### Actual behavior

Especially notable when there are a lot of lines _below_ the cursor, parsing is un-usably slow and can spike CPU usage by _Neovim_ to 100%, bringing everything to a grinding halt.

### Expected behavior

_Treesitter_ highlighting is usable for _Python_ buffers.

**Comment by stsewd** [comment]
Just linking to the original issue reported here https://github.com/nvim-treesitter/nvim-treesitter/issues/1415

And a little of context

> based on my limited testing, the problem seems to start when treesitter in the neovim was upgraded to 0.19.5 on 6/11/21

**Comment by clason** [comment]
For reference, that commit updated tree-sitter from
https://github.com/tree-sitter/tree-sitter/commit/89e1157a299596f3ce2155ba9fd69d5e2c03d3e6
to
https://github.com/tree-sitter/tree-sitter/commit/6ed42747a4e0faee9b65edbbacc86ed0caeae05c

If someone wanted to bisect this (manually, I'm afraid) by replacing the commit ID (and hash) in
https://github.com/neovim/neovim/blob/24e0c16fd6cb33a399772330cb80dfa4c1306284/third-party/CMakeLists.txt#L213-L214
and rebuilding to see which commit between the two introduced the performance regression, that would be helpful.

**Comment by mizlan** [comment]
I can take a shot at this, but how is the sha256 for line 214 generated?

**Comment by clason** [comment]
Well, the "easy" way is to just omit it and check the error message for the expected hash ;)

**Comment by levouh** [comment]
I can also mess with it after work @mizlan, let me know how it goes for you.

**Comment by brymer-meneses** [comment]
This is not exclusive to python, it also happens in tex files.

**Comment by brymer-meneses** [comment]
The unbearable lag also exists in my tex files.

**Comment by mizlan** [comment]
Is it solved by building from the old commit?

**Comment by mizlan** [comment]
> If someone wanted to bisect this (manually, I'm afraid) by replacing the commit ID (and hash) in

```
78010722a49ed6224c773c22b0d25a8c9fbde584 is the first bad commit
commit 78010722a49ed6224c773c22b0d25a8c9fbde584
Author: Douglas Creager <dcreager@dcreager.net>
Date:   Thu May 13 15:38:11 2021 -0400

    query: Allow unlimited pending matches
    
    Well, not completely unlimited — we're still using a 16-bit counter to
    keep track of them.  But we longer have a static maximum of 32 pending
    matches when executing a query.

 cli/src/tests/query_test.rs |  4 +++
 lib/src/query.c             | 72 ++++++++++++++++++---------------------------
 2 files changed, 33 insertions(+), 43 deletions(-)
```

I made a script for this https://gist.github.com/mizlan/50ea7fadbc9b016eae87d6522cb771ab that may be useful in the future.

**Comment by clason** [comment]
For the record, that is https://github.com/tree-sitter/tree-sitter/commit/78010722a49ed6224c773c22b0d25a8c9fbde584

A later commit (https://github.com/tree-sitter/tree-sitter/commit/cd96552448a6e0d4eb27fc54b27cb5130c4b6f76) introduced a configurable match limit via `ts_query_cursor_set_match_limit`  that may be used to set it back to the old default of 32 (as is done in their test).

**Comment by levouh** [comment]
Does that answer the question around:

>and rebuilding to see which commit between the two introduced the performance regression, that would be helpful.

then @clason? And presumably, granted I have _zero_ clue how _Neovim_ interacts with the parsers, the path forward then would be to either specify a value for the parameter with what is pulled in to _Neovim_, or make it exposed to _Neovim_ and defaulted to the old value?

Not sure I'm the best person (more than willing to try though), but I assume the path forward is to either do something like above, or rollback the version pulled in to _Neovim_?

**Comment by clason** [comment]
Yes, that answers the question. We'll have to see what to do with this information. Rolling back is not an option since that commit was deliberately pulled in because it fixes other bugs.

(Again, to make this clear: right now there is _zero_ guarantee that tree-sitter is usable for your actual work. Use it _only_ if you like playing early access and want to help find and fix bugs.)

**Comment by brymer-meneses** [comment]
> Is it solved by building from the old commit?

I can confirm that building neovim at `988f88c24e83c37e1dc011e3561fb505ca7b8706` fixes the issue.

**Comment by JoseConseco** [comment]
@brymer-meneses Do you have linux build? If so can u share it?

**Comment by levouh** [comment]
I have an `appimage` that I built from that SHA, but it isn't anything close to official nor am I super sure how to go about sharing it (along with that downloading things from strangers on the internet is generally a bad idea). You can also compile it yourself @JoseConseco by following something similar to what is [here](https://github.com/neovim/neovim/wiki/Building-Neovim).

**Comment by brymer-meneses** [comment]
> @brymer-meneses Do you have linux build? If so can u share it?

Sorry,  but I don't know how to build an `appimage`, and I'm quite busy at the moment.

**Comment by brymer-meneses** [comment]
Here's what I did to build neovim at that hash
```
git clone https://github.com/neovim/neovim/issues/14897
cd neovim
git checkout 988f88c24e83c37e1dc011e3561fb505ca7b8706
make CMAKE_BUILD_TYPE=Release
sudo make install
```

**Comment by JoseConseco** [comment]
I can confirm that issue is gone on  988f88c24e83c37e1dc011e3561fb505ca7b8706.   Thx for build code

**Comment by stsewd** [comment]
From https://github.com/tree-sitter/tree-sitter/pull/1127#pullrequestreview-669427889 looks like we should set that option to the old value, another step would be to debug the queries that are exceeding that limit.

**Comment by clason** [comment]
First off, this is likely _not_ a fix, but if one of the people affected by this issue could try the following patch, this would be helpful:
```
--- a/src/nvim/lua/treesitter.c
+++ b/src/nvim/lua/treesitter.c
@@ -1073,6 +1073,7 @@ static int node_rawquery(lua_State *L)
   // TODO(bfredl): these are expensive allegedly,
   // use a reuse list later on?
   TSQueryCursor *cursor = ts_query_cursor_new();
+  ts_query_cursor_set_match_limit(cursor, 32);
   ts_query_cursor_exec(cursor, query, node);

   bool captures = lua_toboolean(L, 3);
```

**Comment by JoseConseco** [comment]
It seems to work for me great @clason  .  Hopefully I have build it correctly - here is my  nvim --version:
![image](https://user-images.githubusercontent.com/13521338/123518635-0e232980-d6a7-11eb-8cb0-855364c54e78.png)
And I'm on  latest master.

**Comment by clason** [comment]
So this fixes the issue for you?

**Comment by JoseConseco** [comment]
Yes. Scrolling and navigation is silky smooth

https://user-images.githubusercontent.com/13521338/123518735-8be73500-d6a7-11eb-9277-a6532ae7b7ab.mp4

**Comment by mizlan** [comment]
Can confirm fixes for me as well!
