### ISSUE TITLE
gen_vimdoc.py RuntimeError

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#14899]
- `nvim --version`: `NVIM v0.5.0-dev+1434-g24e0c16fd-dirty`
- Operating system/version: Ubuntu 21.04
- Terminal name/version: Knosole 20.12.3
- `$TERM`: xterm-256color

### Steps to reproduce

Run `python3 scripts/gen_vimdoc.py --target TARGET` for some `TARGET` not equal to `api` (e.g., `lua`, `lsp`, `treesitter`), or omit the `--target` option.

### Actual behaviour

`RuntimeError: no sections for target: TARGET`

### Expected behaviour

Documentation generated without error.

**Comment by dundargoc** [comment]
I think this is fixed. I cannot recreate it. @dstein64: Please confirm if this still is a problem.

**Comment by dstein64** [comment]
> "Please confirm if this still is a problem."

I no longer encounter this issue, and I cannot reproduce when going back to the commit I was on at the time I filed this. I guess the issue was due to a problematic state of my workspace or some mistake I was making in running the program. Thanks for looking into it! Sorry for the erroneous report.
