### ISSUE TITLE
Add package to winget in windows... thats the official windows package manager

### ISSUE THREAD

**Issue by Joel-Nickson** [neovim/neovim#14893]
Windows package manager - winget

Just create a manifest and pass for validation..

more @msfDocs https://docs.microsoft.com/en-us/windows/package-manager/package/

We can then install using `winget install neovim`. 
> Just given the command if you are hearing for the first time

**Comment by glacambre** [comment]
Hi, thanks for the suggestion. I am going to close this issue because it is a duplicate of https://github.com/neovim/neovim/issues/12571 , which contains more information. Don't hesitate to ask questions if you have any :).
