### ISSUE TITLE
[QUESTION] Debugging 100% CPU usage

### ISSUE THREAD

**Issue by levouh** [neovim/neovim#14892]
- `nvim --version`: `NVIM v0.5.0-dev+1432-g5a24284b8`

This isn't a bug report, so I'm going to skip some of the usual things here as I'm just looking for help debugging what exactly is happening.

## Issue

Sometimes `nvim` will get floored at 100% CPU usage and stay there for a long period of time after loading _Python_ buffers within various projects:

![image](https://user-images.githubusercontent.com/31262046/123201111-4b04db80-d46f-11eb-8e15-92f72933a19e.png)

This doesn't really mean anything as there are a whole heap of things that could be causing it. One thing I've noticed though is that if I `:TSDisable highlight` in the buffer, it goes away completely. So, presumably, it is something with _Treesitter_ (note I have the nightly build of _Neovim_ and `:TSUpdate` notes all parsers are up to date).

This only happens in some cases, and some projects, and is incredibly random (not to mention completely stops me from being able to work as the editor is entirely locked up). I'm not sure how to go about debugging it at all.

I've gone the standard route of profiling and things like `:9verbose` to see if it is something evident with _Vimscript_, but haven't had any luck. The typical workflow for this would be:

```
:profile start /tmp/profile.log
:profile func *
:profile file *
```

Perform a set of actions, then:

```
:profile pause
:noau qall
```

which, as perhaps expected since I don't have a _ton_ of _Vimscript_, shows nothing taking anywhere even close to a 10th of a second, however my _Neovim_ instance completely freezes up.

## Solution

Clearly as mentioned before I can `:TSDisable highlight` and the problem goes away almost completely. I obviously want to have _Treesitter_ highlighting, so the next step would be to remove plugins that use _Treesitter_ one at a time and see where that gets me. Then, given that it might not be any of the plugins, the only thing would then be removing _Treesitter_ itself?

## Question

Given above, is there a better way to go about finding out exactly what is causing the slow down? This hasn't always happened (new within the last week or so) and while the way I'm going might get me there, I feel like there has to be an easier way.

Any suggestions?

**Comment by levouh** [comment]
Going to close for now and continue with the standard approach of disabling plugins and whatnot. If it ends up being reproducible with only treesitter, I'll create another issue.

**Comment by cristian-heredia** [comment]
> Going to close for now and continue with the standard approach of disabling plugins and whatnot. If it ends up being reproducible with only treesitter, I'll create another issue.

I recently starting experiencing the same bug. Were you able to identify the cause of the issue?
