### ISSUE TITLE
[Question] How can I avoid the check health error caused by the lack of snippet source?

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/neovim#14890]
How can I avoid the check health error caused by the lack of snippet source?
I don't use snippets, so I want to avoid this error.
<img width="976" alt="スクリーンショット 2021-06-23 20 58 23" src="https://user-images.githubusercontent.com/3197942/123092738-c5306280-d465-11eb-8b77-b64058522df8.png">

**Comment by clason** [comment]
You need to report this at https://github.com/nvim-lua/completion-nvim, as this is _their_ health check, not neovim's -- nothing we can do here.

**Comment by nabezokodaikon** [comment]
OK.
