### ISSUE TITLE
zindex documentation not generated properly

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#14900]
- `nvim --version`: `NVIM v0.5.0-dev+1423-ge2d3ad7bc`
- Operating system/version: Ubuntu 21.04
- Terminal name/version: Knosole 20.12.3
- `$TERM`: xterm-256color

### Steps to reproduce

Run `python3 scripts/gen_vimdoc.py --target api` to generate documentation.

### Actual behaviour

The documentation for `zindex` under `nvim_open_win` (`:help nvim_open_win()`) is not wrapped properly, and spaces are omitted surrounding the word `zindex`, between `higher` and `go`. The data used to generate the documentation, from `nvim/api/vim.c`, appears fine.

![zindex](https://user-images.githubusercontent.com/541289/123374057-7dd4cf80-d554-11eb-87c0-78482c15b3fa.png)

### Expected behaviour

Proper wrapping and spaces retained.

### Additional information

Removing the following lines in `nvim/api/vim.c` results in the proper output from `gen_vimdoc.py` for the text that precedes those lines.

```
///       - 100: insert completion popupmenu
///       - 200: message scrollback
///       - 250: cmdline completion popupmenu (when wildoptions+=pum)
```

**Comment by justinmk** [comment]
Fixed by `scripts/gen_vimdoc.lua`
