### ISSUE TITLE
Change cursor style

### ISSUE THREAD

**Issue by vando2108** [neovim/neovim#14901]
How I can set cursor in insert mode look like normal mode? Thank you

**Comment by reo101** [comment]
Do `:set guicursor=` to disable cursor styling (remain a block in all modes). Read `:help 'guicursor'` for more info.

**Comment by glacambre** [comment]
Yep, as reo101 said `guicursor` is the right option for this. For example, `:set guircursor=a:block` will make the cursor look like a block in all modes.


I'll close this issue but feel free to ask any other question you may have :).

**Comment by teto** [comment]
please use https://neovim.discourse.group/  for usability issues, the bugtracker is for bug reports/feature requests.
