### ISSUE TITLE
Feature Request: Right Mouse Click Context Menu

### ISSUE THREAD

**Issue by gitpubber** [neovim/neovim#14918]
I am requesting feature "Right Click Context Menu" . It must be optional feature to be enabled via init.lua/init.vim .

Menu Items must be user defined. Menu Items should be addable/removable through init file. also, menu items should be configurable via lua api . Extensions must be able to configure Menu Items.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues?q=is%3Aopen+label%3Amouse+Right+Click+Context+Menu
