### ISSUE TITLE
Code action error with tsserver

### ISSUE THREAD

**Issue by sQVe** [neovim/neovim#14925]
- `nvim --version`:
 ```
NVIM v0.5.0-dev+1455-gf83c25942
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/builds/neovim-git/src/build/config -I/tmp/builds/neovim-git/src/neovim-git/src -I/usr/include -I/tmp/builds/neovim-git/src/build/src/nvim/auto -I/tmp/builds/neovim-git/src/build/include
Compiled by sqve@calcifer
```
- Operating system/version: Arch Linux
- Terminal name/version: Alacritty
- `$TERM`: `alacritty`

### Reproduce

Run nvim with `lspconfig` and `typescript-language-server` LSP. Trigger code action window on valid code action line.

### Actual behaviour

When opening the code action list the following error appears:
```
RPC[Error] code_name = unknown, code = 0, message = "json: cannot unmarshal number into Go struct field Diagnostic.context.diag
nostics.code of type string"
```

It still seems to work as intended though. 

### Expected behaviour

It should not output any error.

**Comment by elianiva** [comment]
do you have EFM installed by any chance? I don't think that's coming from tsserver as it's written in Typescript. That error message seems like an error from Go(lang) which is the language that EFM was written.

**Comment by sQVe** [comment]
@elianiva Yes. I'm indeed running `efm`. I'll see if turning it off removes the message 👍🏼

**Comment by sQVe** [comment]
If you have the same issue and find this I had incorrectly set `efm` with option:
```lua
init_options = {codeAction = true, documentFormatting = true}
```
Removing the `codeAction` key/value removes the error. Closing issue! 🎉
