### ISSUE TITLE
mousemodel=popup not working

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#14921]
- `nvim --version`: NVIM v0.5.0-dev+1449-gbdf3df402-dirty
- Operating system/version: Ubuntu 21.04
- Terminal name/version: Konsole 20.12.3
- `$TERM`: xterm-256color

[X] `vim -u DEFAULTS` (version: 8.2.2434) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```
```vim
:set mouse=a
:set mousemodel=popup
:menu PopUp.Save :w<CR>
```

* Right click on the screen

### Actual behaviour

No response

### Expected behaviour

A popup menu shown with a `Save` item

### Additional information

`:help 'mousemodel'` suggests that a setting of `popup` would result in a popup menu when right-clicking.

```
	   popup	Right mouse button pops up a menu.  The shifted left
			mouse button extends a selection.  This works like
			with Microsoft Windows.
```

**Comment by snprajwal** [comment]
From the Vim documentation at https://vimhelp.org/gui.txt.html#popup-menu

`In the Win32, GTK+, Motif, Athena and Photon GUI, you can define the
special menu "PopUp".`

nvim does not have a built-in GUI, hence this feature does not work.

**Comment by dstein64** [comment]
> "nvim does not have a built-in GUI, hence this feature does not work."

I confirmed that the `mousemodel=popup` works in Vim when there is no GUI (both when running Vim in the terminal and specifically using a version of Vim compiled without GUI support). That suggests that not having a built-in GUI doesn't fully explain why this feature doesn't work in Neovim.

The TUI right-click functionality was added to Vim in [patch 8.0.1558](https://github.com/vim/vim/commit/aef8c3da2ba59285b7cfde559ae21cdce6ba6919).

Two possible ways to address the issue here include:

1. Don't support the `mousemodel` option and remove the corresponding documentation.
2. Port [patch 8.0.1558](https://github.com/vim/vim/commit/aef8c3da2ba59285b7cfde559ae21cdce6ba6919) and any other code required for `mousemodel` to Neovim.

**Comment by teto** [comment]
yes it works in vim's TUI.

I would distinguish the task in two
- ability to set cursor in TUI:  I would love to be able to right click wherever in the TUI, I have this mapping but it opens where the current cursor is:
`map <RightMouse>  <Cmd>call quickui#context#open(content, quick_opts)<CR>`
- The part about actually creating the menu could be different than vim's; for instance written in lua via our (future) vim.ui api
