### ISSUE TITLE
Build failed when brew install --HEAD neovim 

### ISSUE THREAD

**Issue by smartrejames** [neovim/neovim#14927]
- `nvim --version`: HEAD f83c25942
- Operating system/version: macOS 11.3.1
- Terminal name/version: Apple Terminal 2.11 (440)
- `$TERM`: xterm-256color

### Steps to reproduce

```
brew update
brew install --HEAD neovim
```

### Actual behaviour

```
==> make install
...
[100%] Linking C executable ../../bin/nvim
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/nvim] Error 1
make[1]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make: *** [all] Error 2

```

### Expected behaviour

It should be able to install successfully

**Comment by tomcur** [comment]
Seems to be the same issue as #14926.

**Comment by clason** [comment]
Duplicate of #14923 (this is a packaging issue; nothing we can do here).

**Comment by clason** [comment]
(Please report issues with downstream distributions on their issue tracker.)
