### ISSUE TITLE
Artifacts remain after removing a floating window's border when there is a zindex specified

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#14922]
- `nvim --version`: NVIM v0.5.0-dev+1423-ge2d3ad7bc
- Operating system/version: Ubuntu 21.04
- Terminal name/version: Konsole 20.12.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```
```vim
" Create a window with a border
:let opts = {'relative': 'editor', 'width': 30, 'height': 2, 'col': 20, 'row': 10, 'border': 'single', 'zindex': 20}
:let win = nvim_open_win(bufnr(), 0, opts)
" Remove the border
:let opts.border = 'none'
:call nvim_win_set_config(win, opts)
```

### Actual behaviour

Artifacts remain adjacent to the window.

![border_artifacts](https://user-images.githubusercontent.com/541289/123697047-78180c00-d82a-11eb-9ab2-9d70c157d7cb.png)

The artifacts remain after `:redraw`.

The artifacts remain after creating a new tab.

![border_artifacts_new_tab](https://user-images.githubusercontent.com/541289/123697031-73535800-d82a-11eb-9eb8-97705deaeb41.png)

The artifacts go away when editing intersecting lines.

### Expected behaviour

No artifacts.

### Additional information

I don't encounter the issue when omitting `'zindex': 20` along with the original options.

**Comment by zeertzjq** [comment]
Is this bug still present? It doesn't seem present in v0.5.0, but I cannot find a commit before v0.5.0 release that fixes this.

**Comment by dstein64** [comment]
I can no longer reproduce this issue on `master`. I checked out code from around the time this was reported, and also cannot reproduce the issue. Perhaps it had something to do with my environment at the time.
