### ISSUE TITLE
Add checksum for assets in releases download page

### ISSUE THREAD

**Issue by meiuwa** [neovim/neovim#14924]
I'm using the AppImage release and automate the updates through a script. Usually, I'm comparing the local and remote versions by parsing the latest release version in GitHub API. Now I would like to switch to nightly release, but it doesn't have a standard version like the stable/latest release. So I thought it would be easier to just parse a checksum file to compare against the nightly release in this case.

E.g md5sum for the current nightly release v0.5.0-dev+1449-gbdf3df402):

```
876a5619597408ba29f6c542a90735c4  nvim-linux64.tar.gz
2fa47a9ebd47c7b0ac6c69d41d5f4bb9  nvim-macos.tar.gz
50d3b3641da52b1be46cd1815d258905  nvim-win64.zip
c59b371aebfd68e2b69a24a80895ddb5  nvim.appimage
```

**Comment by teto** [comment]
can't your script retreive the dates or parse  the commit bit in `v0.5.0-dev+1449-gbdf3df402 ` aka `bdf3df402` ? 
Not sure why you want to compare ?  nightly should be always different . Is your script public ?

**Comment by rktjmp** [comment]
Apparently you must include the SHA's manually in release notes: https://github.community/t/release-checksums-on-github/137764 

PR WIP (just waiting on builds): https://github.com/rktjmp/neovim/tree/14924-checksums

**Comment by rktjmp** [comment]
PR if wanted: https://github.com/neovim/neovim/pull/14951
