### ISSUE TITLE
[Help] customizing nvim terminal title

### ISSUE THREAD

**Issue by backermanbd** [neovim/neovim#14949]
I have talked in https://gitter.im/neovim but it was of no use.

Can anyone please help me customize the nvim terminal title?
I couldn't customize the tab number `(1 of 4)`

If i open 4 tabs (A.cpp, B.cpp, C.cpp, D.cpp)  via nvim, I want my nvim terminal title to look like this
`A.cpp - nvim (1 of 4)`

PS: default `set title` causes nvim terminal to show `(1 of 4)`
I need that feature to add in my code

my code: ( got this from [here](https://github.com/factorylabs/vimfiles/blob/ad1f9ffcd8c1e620a75a28822aaefc2097640b0d/home/.vimrc#L309) )
```
set title

if has('title') && (has('gui_running') || &title)
    set titlestring=
    set titlestring+=%f 	" filename
    set titlestring+=%h%m%r%w 	" Flag
    set titlestring+=\ -\ %{v:progname}
  " set titlestring+=\ -\ %{substitute(getcwd(),\ $HOME,\ '~',\ '')}
endif
```

I checked this myself.. but don't know how to add this in my code
```
let buflist = []
for i in range(tabpagenr('$'))
   call extend(buflist, tabpagebuflist(i + 1))
endfor
```

**Comment by clason** [comment]
Useage questions should go on Discourse -- where this was already asked (and answered): https://neovim.discourse.group/t/help-needed-customizing-nvim-terminal-title/721

**Comment by backermanbd** [comment]
ok then give me the default neovim configuration of `set title`
