### ISSUE TITLE
runtime: support JSON5/JSONC

### ISSUE THREAD

**Issue by izhakjakov** [neovim/neovim#14947]
- `nvim --version`: 0.4.4
- `vim -u DEFAULTS` (version: 8.2) behaves differently? No
- Operating system/version: Linux 5.10.0-6-amd64
- Terminal name/version: Alacritty 0.8.0
- `$TERM`: xterm-256color

I see more and more tools using jsonc and json5 formats for their configuration files.  I believe this trend will only increase as NeoVIM should consider supporting this formats

### [jsonc](https://komkom.github.io)
Basically a JSON with C-style line (`//`) and block (`/**/`) comments.
Exiting vim plugin: https://github.com/kevinoid/vim-jsonc

### [json5](https://json5.org) 
Described as a json for humans.
Here is the specifications: https://spec.json5.org
Existing vim plugin for it already: https://github.com/gutenye/json5.vim

### Steps to reproduce using `nvim -u NORC`

```
$ nvim -u NORC sample.jsonc
<opened as a plain text>

$ nvim -u NORC sample.json5
<opened as a plain text>
```

### Actual behaviour
opens up as a plain text

### Expected behaviour
Opened as a jsonc/json5 file:
- proper syntax highlighting
- proper error messages
- proper indentation and formatting

**Comment by clason** [comment]
So what is actually your proposal here?

(Runtime files in neovim are taken, if at all possible, verbatim from upstream vim. The typical workflow for such a request is to find -- or write -- a filetype plugin that implements these, then convince vim to include this in _their_ runtime files (with the maintainers' explicit permission), and then open a PR here to pull in the new runtime files (or wait until this is done during one of the more or less frequent rounds of synchronization.)

**Comment by izhakjakov** [comment]
Looks like the regular JSON is also missing a maintainer since 2019 Sep 17
```sh
$ head runtime/syntax/json.vim`
```
```vimL
" Vim syntax file
" Language:	JSON
" Maintainer:	vacancy
" Previous Maintainer:	Eli Parra <eli@elzr.com>
" Last Change:	2019 Sep 17
" Version:      0.12
```

**Comment by izhakjakov** [comment]
> So what is actually your proposal here? What exactly is needed on top of (already supported) json files?

jsonc, json5 files -- _as the title suggest and as "Steps to reproduce..." shows._

**Comment by izhakjakov** [comment]
> open a PR here to pull in the new runtime files

Soon

**Comment by clason** [comment]
Yes, but for someone not familiar with jsonc, what is the difference to json?

(And you need to get it into vim first!)

**Comment by izhakjakov** [comment]
### [jsonc](https://komkom.github.io)
Basically a JSON with C-style line (//) and block (/* */) comments.
Exiting vim plugin: https://github.com/kevinoid/vim-jsonc
I already created `runtime/indent/jsonc.vim` to ignore the comments
### [json5](https://json5.org) 
Described a json for humans.
Here is the specifications: https://spec.json5.org
Existing vim plugin for it already: https://github.com/gutenye/json5.vim

**Comment by izhakjakov** [comment]
I updated the description with the info from above comment

**Comment by izhakjakov** [comment]
I have some changes ready on my local branch
Can I push my branch upstream (without merging) ?

**Comment by clason** [comment]
You couldn't merge even if you wanted :) You'd make a pull request by forking the repo, creating a branch, making your changes in that branch, pushing the branch to your fork, and then visiting the github page for the repo (there should be a button).

But I think I was not clear with my explanation: you need to discuss this first on https://github.com/vim/vim, nothing will happen here before you do that!

**Comment by clason** [comment]
You couldn't merge even if you wanted :) You'd make a pull request by forking the repo, creating a branch, making your changes in that branch, pushing the branch to your fork, and then visiting the github page for the repo (there should be a button).

But I think I was not clear with my explanation: you need to discuss this first on https://github.com/vim/vim, nothing will happen here before you do that!

**Comment by izhakjakov** [comment]
Will do.  Thank you!

**Comment by izhakjakov** [comment]
Hi @clason
I created a PR for vim https://github.com/vim/vim/pull/8500
Bram Moolenaar closed it and said:
> The other files will be in the next runtime files update.
Check the PR (not the issue) for more details

**Comment by izhakjakov** [comment]
Hi @clason
I created a PR for vim https://github.com/vim/vim/pull/8500
Bram Moolenaar closed it and said:
> The other files will be in the next runtime files update.

Check the PR (not the issue) for more details
</br>
Should I fork nvim and push my change here as well?
Please let me know my next steps

**Comment by clason** [comment]
Wait for the runtime files to be merged and then open a PR as I explained above. Look at other (merged) runtime PRs to see the exact format that you should follow.

**Comment by mfussenegger** [comment]
Is this fixed with https://github.com/neovim/neovim/commit/d7060183b89742bdb89537beb06201faf05f2fef ?

**Comment by clason** [comment]
No, it's missing the corresponding runtime files (and JSON5 support, completely).
