### ISSUE TITLE
Lua: with "nvim -u", require() points to the default directory

### ISSUE THREAD

**Issue by booperlv** [neovim/neovim#14948]
- `nvim --version`: NVIM v0.5.0-dev+1466-gf35a5f2ef
- Operating system/version: Arch Linux/1.4
- Terminal name/version: foot/1.8.0
- `$TERM`: foot

### Steps to reproduce
**PS: Same thing happens with an init.lua**
```
$ nvim -u ~/.config/othernvim/init.vim
```
~/.config/othernvim/init.vim
```vim
lua require('config')
```
~/.config/
```
nvim
  init.vim
  lua
    config.lua

othernvim
  init.vim
  lua
    config.lua
```

### Actual behaviour
Opening using `nvim -u ~/.config/othernvim/init.vim`, 
the `lua require('config')` in the init.vim points to `~/.config/nvim/lua/config.lua`
Following that,
requiring files in `config.lua` now searches for required files in `~/.config/othernvim/lua.`
```
othernvim/init.vim -> nvim/lua/config.lua -> othernvim/lua
```
### Expected behaviour
Opening using `nvim -u ~/.config/othernvim/init.vim`,
the `lua require('config')` in the init.vim points to `~/.config/othernvim/lua/config.lua`
Following that,
requiring files in `config.lua` now searches for required files in `~/.config/othernvim/lua`
```
othernvim/init.vim -> othernvim/lua/config.lua -> othernvim/lua
```
### Temporary Solution/Workaround used
Using this file structure:
```
nvim
  init.vim
  lua
    config.lua
    otherconfig.lua

othernvim
  init.vim
  lua
    tobereferencedbyotherconfig.lua
```
```
othernvim/init.vim -> nvim/lua/otherconfig.lua -> othernvim/lua/tobereferencedbyotherconfig.lua
```

**Comment by justinmk** [comment]
from `:help lua-intro`

```
Module conflicts are resolved by "last wins".  For example if both of these
are on 'runtimepath':
    runtime/lua/foo.lua
    ~/.config/nvim/lua/foo.lua
then `require('foo')` loads "~/.config/nvim/lua/foo.lua", and
```

complete rules are documented at `:help lua-require`

**Comment by booperlv** [comment]
I see, hadn't noticed this and forgot lua-(whatever u need help with) existed. Thank you!
