### ISSUE TITLE
Inconsistency in VimL highlighting between `v0.5.0` and `v.0.4.4`

### ISSUE THREAD

**Issue by paniash** [neovim/neovim#14940]
- `nvim --version`: v0.5.0-dev+1449-gbdf3df402
- Operating system/version: Artix Linux
- Terminal name/version: st 0.8.4
- `$TERM`: `st-256color`

Comparing with stable version `v0.4.4`, there is a slight inconsistency in highlighting a particular section of `init.vim` when using [vim-plug](https://github.com/junegunn/vim-plug).

## Screenshot

**v0.4.4**:

![pic-selected-210630-1307-06](https://user-images.githubusercontent.com/59497618/123922316-88a0c180-d9a5-11eb-9b6f-68c1b5a4f9c9.png)

**v0.5.0-dev+1449-gbdf3df402**

![pic-selected-210630-1314-08](https://user-images.githubusercontent.com/59497618/123922323-8b031b80-d9a5-11eb-8a52-09641109e4eb.png)

### Actual behaviour

After the `Plug` command, the text with enclosed quotes `'` are not highlighted in v0.5.0 in contrast to v0.4.4.

### Expected behaviour

Both the versions must be consistent in vimL highlighting (no treesitter being used here), preferably with the enclosed text being highlighted (green in my case).

**Comment by clason** [comment]
Have you checked whether vanilla `vim` behaves the same? Might be an updated syntax file we pulled in recently.

**Comment by paniash** [comment]
> Have you checked whether vanilla `vim` behaves the same? Might be an updated syntax file we pulled in recently.

Yes, you were right. Vanilla vim also doesn't highlight the enclosed text.

> Also, please always provide a minimal reproducing example people can copy and test; these things depend on way too many variables to help otherwise. (The issue template is there for a reason...)

Sorry about that. I'll keep it in mind henceforth.

**Comment by clason** [comment]
I'll go ahead and close this, then, since it's not actually a _neovim_ bug. If vim "fixes" this in their syntax file, we'll pull in their change as well. (Hence if you think this is an actual bug or should be changed, you should report this at https://github.com/vim/vim -- but maybe look through their tracker for a discussion of the change first.)

**Comment by paniash** [comment]
@clason Thanks for the suggestion. I've opened an issue on the official vim repo. Hopefully, they'll fix this "bug".

**Comment by clason** [comment]
I just saw your issue -- you should have tried the _latest_ version (8.2.3075), it seems they have already fixed that issue.

**Comment by clason** [comment]
I believe it was fixed in this runtime update: https://github.com/vim/vim/commit/d2ea7cf10a4d026ebd402594d656af7d5c811c24

(@janlazo should we cherry pick the latest vim syntax, or rather pull in this update (and the following two), before or after 0.5?

**Comment by stsewd** [comment]
Hi, I tried to port this patch in https://github.com/neovim/neovim/pull/14787 but I'm not sure about the errors

**Comment by janlazo** [comment]
Pull the vim syntax update only unless the test errors can be fixed. I don't know how to fix the tests on my end.

**Comment by clason** [comment]
@janlazo We don't use upstream `vim.vim` as-is; there's some autogeneration going on that I don't fully grok yet (as well as some nvim-specific differences that are relatively clear). If I can assume that this only affects the first block of `syn keyword *` (before `"--- syntax here and above generated by mkvimvim ---` in the upstream file), I can manually merge the latest version in and make a PR.

**Comment by janlazo** [comment]
@clason Innocuous. As with other syntax files, we don't maintain them. Vim syntax is the exception where we maintain a subset of the syntax, supported by Neovim.
