### ISSUE TITLE
sockconnect() function returns connection refused

### ISSUE THREAD

**Issue by aditya-K2** [neovim/neovim#14958]
Hi, I am trying to connect to tcp socket at localhost port 10043, so that i can then interface with the nvim through pynvim. But when I call sockconnect() 
` :call sockconnect('tcp', '127.0.0.1:10043') `
it shows connection failed: connection refused
what am I doing wrong?

**Comment by bfredl** [comment]
sounds like you actually want `serverstart('127.0.0.1:10043')`

**Comment by aditya-K2** [comment]
thanks
