### ISSUE TITLE
neovim is sending win_viewport event even though ext_multigrid is disabled

### ISSUE THREAD

**Issue by hismailbulut** [neovim/neovim#14956]
- `nvim --version`: NVIM v0.5.0-dev+1455-gf83c25942
- Operating system/version: Windows 10 20H2 19042.1052
- Terminal name/version: GUI
- `$TERM`: nvim

### Actual behaviour
Neovim is sending win_viewport multigrid event even though ext_multigrid is disabled. It doesn't happen in 0.4.5.
I only tested in this version and windows 10.

**Comment by bfredl** [comment]
the event is new for 0.5. What's the issue? if your client has no need for it, you can just ignore it.

**Comment by hismailbulut** [comment]
Sorry, I didn't know it's new. If sending it doesn't broke things it isn't an issue and I can't see any broken things for now. I opened this because this is unexpected. I am closing this issue.

**Comment by ddickstein** [comment]
> the event is new for 0.5. What's the issue? if your client has no need for it, you can just ignore it.

@bfredl I think the issue is that `win_viewport` doesn't make sense when `ext_multigrid` is disabled, at least according to the help doc, so it's not obvious what to do with it / if it's safe to ignore.

**Comment by bfredl** [comment]
The issue is resolved because there is no issue. If you have suggestions for the docs you can just open a PR (An open issue is not a prerequisite - _all_ docs can be potentially improved)

**Comment by ddickstein** [comment]
I think the issue is that `win_viewport` events are being sent even when `ext_multigrid` is disabled. I would expect not to receive these events. If my expectation is correct, then this is a bug. If my expectation is incorrect then there's a documentation issue but I'm not sure what it is since I don't know why the expectation is wrong.
