### ISSUE TITLE
Automatically choose one language server to formatting when using multiple language servers

### ISSUE THREAD

**Issue by kovasap** [neovim/neovim#14952]
When I use multiple language servers (for python) and call `vim.lsp.buf.formatting` or `vim.lsp.buf.range_formatting` I have an option to select a language server via pressing 1 or 2 and then enter.  I'd prefer to always autochoose language server 1 for formatting.  Perhaps this could work as an argument to these functions, or perhaps formatting could be disabled on a language server basis?

**Comment by mjlbach** [comment]
We're not going to automatically choose a language server for you, there's no heuristic that would work (the start order depends on how quickly the language servers speed up). You can already pass an order table to formatting_seq_sync, https://github.com/neovim/neovim/blob/e8247bc739cd0cdc32833f44973bf2d635373086/runtime/lua/vim/lsp/buf.lua#L203

**Comment by kovasap** [comment]
Sorry I meant that I'd like to code in my vimrc which language server should be selected automatically (not just the order in which they appear).  I definitely don't want one to be randomly selected!  Any way to do this?

**Comment by yujinyuz** [comment]
I have this in my config to disable tsserver formatting. I'm not sure if there is a better way to do this

```lua
  if lang == "typescript" then
    config.on_attach = function(client)
      client.resolved_capabilities.document_formatting = false
      on_attach(client)
    end
  end
```

**Comment by kovasap** [comment]
Hmm, I added this to my config:

```lua
nvim_lsp.pyls.setup {
  on_attach = function(client, bufnr) 
    if <condition> then
      print('hello')
      client.resolved_capabilities.document_formatting = false
    end
    on_attach(client, bufnr)
  end,
  settings = {
    pyls = {
      plugins = {
        -- This requires: pip install yapf
        yapf = { enabled = true },
        autopep8 = { enabled = false },
        pylint = { enabled = true },
        pycodestyle = { enabled = false },
      }
    }
  }
}
```

I get my `hello` print, but I still have the option to choose formatters when I go to format.  Is `client.resolved_capabilities.document_formatting` a typescript LSP specific variable or common to all language servers?

**Comment by clason** [comment]
The issue tracker is for actual bugs or feature requests -- usage questions should go to https://discourse.julialang.org or https://gitter.im/neovim/neovim.

**Comment by mjlbach** [comment]
@clason I think julia folks might be a bit confused 🙃 (neovim.discourse.group/)

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/automatically-choose-one-language-server-to-formatting-when-using-multiple-language-servers/800/1

**Comment by clason** [comment]
Too many discourses... 🤕
