### ISSUE TITLE
make 'mousehide' into proper ui_option

### ISSUE THREAD

**Issue by hismailbulut** [neovim/neovim#14955]
- `nvim --version`: NVIM v0.5.0-dev+1455-gf83c25942
- Operating system/version: Windows 10 20H2 19042.1052
- Terminal name/version: GUI
- `$TERM`: nvim

[x] `vim -u DEFAULTS` (version: 8.2) behaves differently

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
echo nvim_get_option("mousehide")
```

### Actual behaviour
On vim 8.2 mousehide option can be used in OptionSet autocmd but in neovim it doesn't work.
And nvim_get_option_info works with mousehide but nvim_get_option doesn't work.

### Expected behaviour
Get the value of the mousehide.

**Comment by bfredl** [comment]
I think the option is not implemented. but it could be made into a (pure) ui_option, like 'linespace'.

**Comment by hismailbulut** [comment]
It would good to have mousehide an ui option. I like it very much. If someone tries to get this option now and in older versions just call rpcnotify with &mousehide after initilization.
