### ISSUE TITLE
Return values of vim.loop.os_uname (on Windows)

### ISSUE THREAD

**Issue by benallan** [neovim/neovim#14953]
Could someone point me to documentation for the function `vim.loop.os_uname()`? 

I'm asking because I often seem to see code [like this](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/log.lua#L20):

```
vim.loop.os_uname().sysname == "Windows"
```

But on my system the return value is "Windows_NT", so I'm wondering how to thoroughly test that something is running on Windows. 

Thanks!

Version Info: 
NVIM v0.5.0-dev+1429-gb585f723b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Windows 10 Pro (2009)

**Comment by rktjmp** [comment]
`vim.loop` aliases the `luv` library, so replace `uv` with `vim.loop` in the docs:

https://github.com/luvit/luv/blob/master/docs.md#uvos_uname

**Comment by rktjmp** [comment]
In fact the line you linked maybe a bug? Not sure.

You can see what LibUV is calling in here https://github.com/libuv/libuv/blob/95f88f47f28b4686a6959377c8d2c31daa40bd64/src/win/util.c

Seems that sysname should be `Windows_NT` (Maybe it strips the underscores at some point, if you're not seeing them):

```
  uv__strscpy(buffer->sysname, "Windows_NT", sizeof(buffer->sysname));
```

You can also see they call RtlGetVersion() or GetVersionEx() as well as check SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion. You can look up the MS docs to see what those return.

Without a system to test on, IDK.

It looks like Luv is calling straight through: https://github.com/luvit/luv/blob/b85b9ef7b4c0abb2b507632ad3b885c965ccc0c4/src/misc.c#L595 so I would expect it to to be `Windows_NT` unless something changed between libuv versions?

**Comment by benallan** [comment]
Thanks a lot!

> In fact the line you linked may be a bug? Not sure.

Right, on my own machines I always see "Windows_NT" but I think I've seen more than one person use code that expects "Windows" so I assumed it was possible. (Sorry I missed the underscore in the description above).

From the code you've linked, it really looks like "Windows_NT" is correct so I'll probably stick with that.

**Comment by rktjmp** [comment]
See this commit which is probably the best method:

https://github.com/neovim/nvim-lspconfig/commit/2c6f8dbd7e5adc732c0d679351b2a18d025c650b

**Comment by benallan** [comment]
Thanks, that commit has more than one useful trick. 

And thanks for opening the PR too. I can see the logger basically works as it is, so I'm not confident enough to look into it much. (But forward slashes will often work fine on windows, e.g. if there's no attempt to split the path using the wrong separator.)
