### ISSUE TITLE
Norton doesn't like nvim.exe (x64 only)

### ISSUE THREAD

**Issue by BlueStaggo** [neovim/neovim#14960]
- `nvim --version`: I can't run this command but I know it's 0.5 and this only happens with 0.5.
- Operating system/version: Windows 10 1909 x64
- Terminal name/version: Doesn't matter
- `$TERM`: Doesn't matter

### Steps to reproduce

1. Download NeoVim 0.5: https://github.com/neovim/neovim/releases/tag/v0.5.0
2. Unzip the Windows archive
3. If you have Norton installed, it will remove nvim.exe.
4. nvim-qt.exe cannot work without nvim.exe.

### Actual behaviour

Norton removes nvim.exe and nvim-qt.exe cannot work.

### Expected behaviour

Norton is ok with nvim.exe

### Workaround

Install the 32 bit version.

### Notes

I cannot remove the file from quarantine because Norton is annoying:
![image](https://user-images.githubusercontent.com/71090710/124305250-bd0aae00-db5c-11eb-8fe2-a14b39ba5186.png)
Norton has just removed every single feature.

**Comment by BlueStaggo** [comment]
Actually, I don't think this is worth going on about. Just install the 32 bit version.

**Comment by justinmk** [comment]
related: https://github.com/neovim/neovim/issues/11011 https://github.com/neovim/neovim/issues/5433

**Comment by BlueStaggo** [comment]
Reopening because Norton just straight up removed nvim.exe for the 32 bit version.

**Comment by chrisbra** [comment]
Am 2021-07-08 20:23, schrieb BlueStag:
> Reopening because Norton just straight up removed nvim.exe for the 32
> bit version.

There is nothing the maintainers can do against it. You really should 
contact your AV vendor and have it whitelisted.
See e.g. 
https://support.norton.com/sp/en/us/home/current/solutions/kb20100222230832EN?client=norton&site=nrtn_en_US&x=0&y=0

Best,
Christian

**Comment by boehs** [comment]
in 6.0 nightly norton flags `c.dll` as malware
![image](https://user-images.githubusercontent.com/51836263/125352493-57be7600-e32f-11eb-8eb6-233059c71b6a.png)
![image](https://user-images.githubusercontent.com/51836263/125352537-6442ce80-e32f-11eb-9c8c-7cb1a889b805.png)

I expect you did not add malware to c.dll so have removed from quarantine - norton has been really crappy with detection lately with lots of false positives. Still worth investigating because... well.

**Comment by clason** [comment]
There's nothing we can do if AV software reports false positives. You need to complain to Norton about this.
