### ISSUE TITLE
[doc] Document the behavior of having both init.vim and init.lua

### ISSUE THREAD

**Issue by michaellee8** [neovim/neovim#14965]
- `nvim --version`: v0.5.0-stable
- Operating system/version: Ubuntu 20.04.2 LTS
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

Currently, there are no documentation about the bahvior of neovim v0.5.0 when both an `init.lua` and `init.vim` are provided. The [current behavior](https://github.com/neovim/neovim/blob/master/src/nvim/main.c#L1819) is to show an error message that shows conflicing configuration and loads both of the scripts. 

I believe this can use some better documentation, so that users that are just trying out neovim v0.5.0 (like me) can have both `init.lua` and `init.vim` in our config directiory, have `nvim < 0.5.0` just ignore the init.lua, and detect `nvim >= 0.5.0`  in `init.vim` with `has('nvim-0.5')` to disable loading of tradiitional vim script plugins. 

It may also be great if we can suspress this error message or even suspress the whole `init.vim` directly in `init.lua`.

**Comment by clason** [comment]
The documentation (`:h init.lua`) says

> 	A file that contains initialization commands is generically called
	a "vimrc" or config file.  It can be a Vimscript or Lua file named
	"init.vim" or "init.lua" respectively.  **It is an error to use both at
	the same time.**  Each line in a "init.vim" is executed as an Ex command
	line.  See also |vimrc-intro| and |base-directories|.

Is this is not clear enough? Silently ignoring an init file is dangerous, so the explicit error was decided to be the best (most expressive) option during the transition. Over the course of `0.5.x`, this can be turned into a deprecation warning (rather than an error) and removed for `0.6.0`.

**Comment by michaellee8** [comment]
> The documentation (`:h init.lua`) says
> 
> > A file that contains initialization commands is generically called
> > a "vimrc" or config file.  It can be a Vimscript or Lua file named
> > "init.vim" or "init.lua" respectively.  **It is an error to use both at
> > the same time.**  Each line in a "init.vim" is executed as an Ex command
> > line.  See also |vimrc-intro| and |base-directories|.
> 
> Is this is not clear enough? Silently ignoring an init file is dangerous, so the explicit error was decided to be the best (most expressive) option during the transition. Over the course of `0.5.x`, this can be turned into a deprecation warning (rather than an error) and removed for `0.6.0`.

So user aren't allowed to have init.vim and init.lua in the same time? I know it is an error message but the actual behavior seems to be that both rc file will be loaded. I would like to make my single config works on both pre 0.5.0 and 0.5.0 installations.

**Comment by clason** [comment]
No, users aren't allowed to have both, and only one of the two will ever be loaded. If you want to keep your config compatible, keep it in `init.vim` (there is no practical benefit of `init.lua` over lua heredoc in `init.vim`).

**Comment by michaellee8** [comment]
Thank you for your explanation, let's close this issue then.

**Comment by justinmk** [comment]
> Silently ignoring an init file is dangerous, so the explicit error was decided to be the best (most expressive) option during the transition. Over the course of `0.5.x`, this can be turned into a deprecation warning (rather than an error) and removed for `0.6.0`.

Why would the error ever be removed? It's nice to have a clear and self-documenting expectation.

**Comment by clason** [comment]
Sorry, that wasn't clear -- just for the record, I meant that it "_may_ be removed for 0.6, but certainly not before (if ever)".
