### ISSUE TITLE
Request a way to override formatoptions for all filetypes

### ISSUE THREAD

**Issue by rkuester** [neovim/neovim#14963]
- `nvim --version`: NVIM v0.6.0-dev+1-g62d67de59

It would sure be nice if `formatoptions` could be modified for all filetypes without making `after/ftplugin/$type.{vim,lua}` files for each file type. The problem is that built-in ftplugins often modify `formatoptions`, and built-in ftplugins are difficult to override. Local `after/ftplugin/$type.{vim,lua}` files appear to be about the only thing that runs after the built-in ftplugins (see `:scriptnames`).

A local `after/ftplugin.vim` will run for every type, but it loads before the built-in, type-specific ftplugins. Perhaps that's a solution—load `after/ftplugin.vim` *after* the built-in, type-specific ftplugins? It is in *after*, after all.

Is there already a way to do this of which I'm unaware? I could imagine a properly-constructed autocommand doing the job, but that's an ugly solution.

**Comment by shadmansaleh** [comment]
You can try putting something like

```vim
autocmd FileType * setlocal formatoptions=your_options
```
in a file in `after/plugin`
And see if that works for you.

It's not ugly imo .
in short you could just write
```vim
au FileType * setl fo=your_options
```

**Comment by justinmk** [comment]
If autocommands are ugly we need to fix that by enhancing Lua support. Not by adding special-case features.

**Comment by rkuester** [comment]
Autocommands aren't ugly, per se, but needing to use one because it's the only way to workaround surprising built-in behavior is conceptually ugly. I'll elaborate.

There are two problems I'm seeing. First, it violates the principle of least surprise that a straightforward setting of `formatoptions` in user config files like `init.{vim,lua}` is overwritten by built-in ftplugins. Even as a long-time vimmer, it didn't occur to me that built-in ftplugins were running after my configuration until I did some research. Figuring this out will definitely frustrate a new user. I even see a likely mis-expectation in this regard in @tjdevries [configs](https://github.com/tjdevries/config_manager/blob/1803fa530ce1b45493bbe44c8335fdf4d95327a6/xdg_config/nvim/plugin/options.lua#L70) (which I was browsing for ideas, thanks teej!).

ftplugins are supposed to tread lightly according to `runtime/ftplugin/README.txt`, but the weight with which they tread varies. At least 154 of the 246 built-in ftplugins modify `formatoptions`. The problem might generalize to other settings like widths, tabs vs. spaces, etc. Of course, changing those settings is often the value of these ftplugins.

I don't see a good solution in general to this surprise of having ftplugins overwrite settings the user didn't want overwritten, because it's hard to know what the user would or wouldn't want overwritten. Perhaps we can at least improve the help for `formatoptions`, mentioning the likelihood of it being overridden by a built-in ftplugin and suggesting better ways to affect
the desired outcome? Do we touch the help for long-standing, upstream features?

The second part of the problem is once the user learns about ftpluins and understands what's going wrong, the mechanisms for fixing it are lacking. The canonical way to override a built-in ftplugin is to add a user `after/ftplugin/language.vim` file. That's clean, but needing to do that for every language individually is unfortunate. Perhaps we could add a catch-all ftplugin name that's run for every filetype in addition to the language-specific file—e.g., so a user could add `after/ftplugin/allfiletypes.vim`? (Contrary to my suggestion otherwise above, `ftplugin.vim` is not designed for this purpose.)

As @shadmansaleh suggests above, an autocommand in the right place works today as a workaround. That's helpful but somewhat unsatisfying, because it's outside of the ftplugin mechanism that's causing the problem. The user also has to worry about making sure the autocommand runs after built-in ftplugins by picking the right events and or defining the autocommand in the right place (e.g, `after/plugin`). That's trending towards obscure and advanced knowledge. It's bad enough having to be aware of ftplugins and their ordering.

Does this surprise or bother anyone else? Am I making too big a deal out of this? Should we augment the help? Should we add an applies-to-all-types ftplugin name? I'm willing to hack on this if there were agreement on an approach from those who see the big picture better than I can see it. Thanks for the feedback, everyone!

**Comment by shadmansaleh** [comment]
There's not much hacking really .
You just need to add two lines after this line
https://github.com/neovim/neovim/blob/75f758b993b842c4afd03fdaa0063b573fdf8751/runtime/ftplugin.vim#L34

like following.
```vim
runtime! ftplugin/allfiletypes.vim ftplugin/allfiletypes_*.vim ftplugin/allfiletypes/*.vim
runtime! ftplugin/allfiletypes.lua ftplugin/allfiletypes_*.lua ftplugin/allfiletypes/*.lua
```

Since runtime files are ported mostly from vim . So you'll most likely have to go through vim for this. You should open a pr in [vim](github.com/vim/vim) and try to convince bram about this :P .

Oh for vim you just need the 1st line lua one is neovim specific .

**Comment by justinmk** [comment]
> The second part of the problem is once the user learns about ftpluins and understands what's going wrong, the mechanisms for fixing it are lacking.

definitely agree, ftplugins are a gross, half-baked hack.  they can't be fixed really, because they are convention-based and basically just more vimscript run at a particular time.

related: https://github.com/neovim/neovim/issues/11891 , https://github.com/vim/vim/issues/4563

> Perhaps we can at least improve the help for `formatoptions`

not sure why you are focused on `formatoptions`, isn't the problem applicable to all options? But pasting some boilerplate in the doc for every option will cause a different problem (lower single-to-noise ratio). 



> it violates the principle of least surprise that a straightforward setting of `formatoptions` in user config files like `init.{vim,lua}` is overwritten by built-in ftplugins. Even as a long-time vimmer, it didn't occur to me that built-in ftplugins were running after my configuration until I did some research

`:verbose set <option>?` is intended to show the cause of an option change. It would be a good investment to enhance that kind of insight.

**Comment by rkuester** [comment]
> related: #11891

Locking an option is an interesting, generally-applicable idea. Maybe that can be generalized to masking an option: e.g., certain characters in a string-type option that are effectively always set or cleared. Just brainstorming—unfortunately it's more complexity and I'm sure it'd break things.

> not sure why you are focused on `formatoptions`, isn't the problem applicable to all options? But pasting some boilerplate in the doc for every option will cause a different problem (lower single-to-noise ratio).

Yes, you're right. I was focused on my concrete example, but the general problem is ftplugins might alter and do anything. A note on `formatoptions` alone makes no sense. Generalizing: when reading the help, I find it easy to miss the big-picture that options are not one-time, declarative things, but may change as multiple config files are read and as events fire. And reading it now, even `:h starting` doesn't paint the picture too clearly. Maybe there are better places to look? Not sure there's a concrete suggestion or solution here, just reporting the data point that as a daily user I still managed to miss really grasping how ftplugins, syntax files, after/, autocommands, all interact, and the value of tools like `:verbose` and `:scriptnames`.

> :verbose set <option>? is intended to show the cause of an option change. It would be a good investment to enhance that kind of insight.

Indeed! How did I not know or forget about `:verbose <option>?`? Thanks for the reminder. A couple of thoughts:
* It'd be useful to show a full backtrace of all the places an option was changed. There are corner cases to that, e.g., an autocommand toggling a setting around frequently.
* Things set in Lua don't indicate from where they came other than saying "Last set from Lua..." I imagine that's nontrivial or it would have been done already, but that'd be a nice enhancement.

Obviously, I had and have a lot to learn, just thinking about how to smooth the path for the next guy.

**Comment by justinmk** [comment]
> * It'd be useful to show a full backtrace of all the places an option was changed. There are corner cases to that, e.g., an autocommand toggling a setting around frequently.

oh absolutely.

>  Things set in Lua don't indicate from where they came other than saying "Last set from Lua..." I imagine that's nontrivial or it would have been done already, but that'd be a nice enhancement.

yep, nontrivial but definitely needed.
