### ISSUE TITLE
API: nvim_cmd or nvim_exec_cmd (like nvim_command but takes a list)

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#14966]
Given a table, e.g. `{"foo", "-bar", "baz"}` (produced e.g. programmatically), it'd be nice to be able to execute this as an Ex command rather than needing to manually join it into a string, and then need to worry about escaping.

Analogous to how when executing subprocesses it's usually nicer to have a list of arguments rather than needing to join into a string and then deal with a shell figuring out how to break it up again.

**Comment by shadmansaleh** [comment]
You can have it with a small snippet in your config. like:
```lua
function cmd_list(args)
    return vim.api.nvim_command(table.concat(args, ' '))
end
```

now you can do
```lua
cmd_list {"foo", "-bar", "baz"}
```

**Comment by Julian** [comment]
That doesn't work if one of the args has a space in it. But I know this can be done if course, I'm asking whether it's useful for others. To me it seemed "yes" since it's even nice to have for missing neovim Lua APIs until they're finished, but @bfredl didn't seem too keen. Feel free to close if not.

**Comment by shadmansaleh** [comment]
I'm not sure if it would be much useful.

I think internal executer works with strings only. So we will have concat it and send it as string and executer will parse and split it up anyway .

Also since `vim.ex` wasn't upstreamed from [nvim.lua](https://github.com/norcalli/nvim.lua) I'm not sure if this will be better than that.

**Comment by shadmansaleh** [comment]
Actually I was just thinking from lua side :P .

From rpc api perspective this idea makes a lot more sense .

**Comment by justinmk** [comment]
> That doesn't work if one of the args has a space in it.

The quoting rules for vim commands are totally random. Each command has its own quoting rules. So it is not trivial to add support for this. Though it would indeed be valuable.

**Comment by justinmk** [comment]
> I think internal executer works with strings only. So we will have concat it and send it as string and executer will parse and split it up anyway .

Initially, even having something that correctly quotes the args would be quite useful. E.g. the caller may want `%` to be interpreted literally.

related: #18231
