### ISSUE TITLE
Please, don't remove cscope😭

### ISSUE THREAD

**Issue by kuator** [neovim/neovim#14964]
I use cscope @tjdevries

**Comment by bfredl** [comment]
There's no concrete plans to do this. also the issue tracker is for actionable items, opinions are better on the gitter/matrix room.

**Comment by justinmk** [comment]
Why do you need/want cscope instead of using LSP? The idea would be to add some standard commands like `:cscope foo` which would delegate to LSP instead this old single-purpose interface.

**Comment by kuator** [comment]
@justinmk I work with the relatively large codebases, and LSP (specifically python-lsp) starts to freeze when working with them. I use ctags for jumping to definition and cscope to jump to references

**Comment by justinmk** [comment]
ctags would not be removed, fwiw. ctags has nice cross-platform support, and is very useful to navigate polyglot projects without involving the build system. 

cscope is hard to setup, fragile, [unmaintained](http://cscope.sourceforge.net/) (?). If LSP client is "freezing" we need to fix that. If the LSP server is freezing... :(

**Comment by bfredl** [comment]
Maybe cscope can be wrapped in a LSP compliant API? Then we won't need a separate client inside the c core to access this coveted ancient technology.

**Comment by justinmk** [comment]
yes! https://github.com/jpeach/cscope-lsp looks interesting

**Comment by kuator** [comment]
> ctags would not be removed, fwiw. ctags has nice cross-platform support, and is very useful to navigate polyglot projects without involving the build system.
> 
> cscope is hard to setup, fragile, [unmaintained](http://cscope.sourceforge.net/) (?). If LSP client is "freezing" we need to fix that. If the LSP server is freezing... :(

The neovim client is blazing fast, it's the server that can't handle the larger codebases

**Comment by lewis6991** [comment]
@kuator have you tried using something like [pyright](https://github.com/microsoft/pyright)? It's implemented in typescript (not python) so should be better at handling larger projects.

**Comment by kuator** [comment]
> @kuator have you tried using something like [pyright](https://github.com/microsoft/pyright)? It's implemented in typescript (not python) so should be better at handling larger projects.

Yes, I use it, it does indeed work better, but I still prefer ctags+cscope when I prefer speed over accuracy

**Comment by kuator** [comment]
rip cscope
