### ISSUE TITLE
nvim in manjaro

### ISSUE THREAD

**Issue by theice-star** [neovim/neovim#14972]
first run 
nvim: symbol lookup error: nvim: undefined symbol: ts_query_cursor_set_match_limit

**Comment by justinmk** [comment]
not enough info. if this came from a package for manjaro, contact the package maintainer. otherwise say how you built it, and in general answer the questions in the issue template.

**Comment by tcstory** [comment]
I met the same problem. I used the following commands to install neovim

```
yay -S archlinuxcn/neovim-git
```

**Comment by clason** [comment]
For the record: this means you are using a packaged nightly that is too old. that problem has been fixed in 0.5 (and later nightlies).

**Comment by bfredl** [comment]
`archlinuxcn/neovim-git` looks outdated, without any meaningful changes. why not just use the ordinary AUR package: `yay -S neovim-git`
