### ISSUE TITLE
Allow `vim.api.nvim_set_keymap` to accept a lua callback function

### ISSUE THREAD

**Issue by DanielPower** [neovim/neovim#14976]
My apologies if this already exists or has already been requested. I did try searching for it, but couldn't come up with any keywords to bring up any related issues.

`vim.api.nvim_set_keymap` currently takes as its third argument a string, which is a vim expression that will be called when the mapping is activated. This can be used to call a lua function by running `v:lua.SomeGlobalFunction` or with `<cmd>lua require('file_that_exports_function').some_exported_function()<cr>`.

My request would be to allow the third argument to optionally be a lua function, which will be called when the mapping is activated.

Currently legal example:
```lua
function TabComplete()
  -- implementation irrelevant to example
end

vim.api.nvim_set_keymap("i", "<Tab>", "v:lua.TabComplete()", {expr = true})
```

Here, `TabComplete` must be a global function, so that it can be called as a vimscript expression. This means I must ensure to name it such that it hopefully won't collide with any other globally named functions defined by other plugins.

Desired example:
```lua
local function tab_complete()
  -- implementation irrelevant to example
end

vim.api.nvim_set_keymap("i", "<Tab>", function() tab_complete() end, {expr = true})
```

Here we solve the problem of cluttering the global namespace. Additionally, if it were a short function, we could inline it directly in the keymap call. And any other local values defined within the scope will be accessible to the callback without needing to be made global.

Is this something that is currently possible, or may be considered for a future release? As shown with my legal example, this is not something that is currently blocking me. However it would be a preferrable syntax.

**Comment by shadmansaleh** [comment]
It's being worked on #13823

Until it's finished you can use [vimpeccable](https://github.com/svermeulen/vimpeccable) or [astronauta.nvim](https://github.com/tjdevries/astronauta.nvim). They allow lua callbacks for keymaps.

**Comment by DanielPower** [comment]
Thank you, I was unaware of that PR. It looks like that solution won't work for me just yet since it doesn't support `expr`. However I'll be looking forward to it.

Vimpeccable supposedly supports expr, but I wasn't able to get it working unfortunately. I'll continue with my global function workaround for now.

**Comment by DanielPower** [comment]
Here's the solution I came up with for anyone that's looking for one.

I created this function, which takes the same arguments as `vim.api.nvim_set_keymap`, except that the callback argument can either be a string or a function. It automates creating a uniquely named global function, so that it can then be passed to `vim.api.nvim_set_keymap` as a `v:lua.function_name()` expression.

```lua
function set_keymap(mode, key, callback, options)
  local callback_string
  if type(callback) == "string" then
    callback_string = callback
  elseif type(callback) == "function" then
    if not _G.set_keymap_index then
      _G.set_keymap_index = 1
    end
    local index = _G.set_keymap_index
    _G.set_keymap_index = _G.set_keymap_index + 1
    _G["set_keymap_callback_"..index] = callback
    callback_string = "v:lua.set_keymap_callback_"..index.."()"
  end
  vim.api.nvim_set_keymap(mode, key, callback_string, options)
end
```
I can then use this function anywhere I want to set a keymap, whether it be a vim expression or a lua function. And it supports `expr`.

```lua
set_keymap("i", "<Tab>", TabComplete, {expr = true})
set_keymap("s", "<Tab>", TabComplete, {expr = true})
set_keymap("i", "<S-Tab>", ShiftTabComplete, {expr = true})
set_keymap("s", "<S-Tab>", ShiftTabComplete, {expr = true})

set_keymap("i", "<C-Space>", "compe#complete()", {expr = true})
set_keymap("i", "<CR>", "compe#confirm('<CR>')", {expr = true})
set_keymap("i", "<C-e>", "compe#close('<C-e>')", {expr = true})
```

**Comment by shadmansaleh** [comment]
Are you sure astronauta doesn't support expr ?

I've been using [this](https://gist.github.com/shadmansaleh/4f7eba765b413502fcfea893f4cf00b0) in my config for a while you can guve it a try .

**Comment by DanielPower** [comment]
I'm not sure astronauta doesn't support expr. But I received errors when I attempted to use it. When looking over the PR, I saw this comment, which I read as meaning expr support was going to be added in another PR. But now that I'm re-reading it, I'm not sure what exactly it means: https://github.com/neovim/neovim/pull/13823#issuecomment-766688131

Thank you for linking your keymap function. That's a clever solution, I didn't think of using `<cmd>` to be able to require a file. This gets around the need to add anything to the global namespace at all.

**Comment by shadmansaleh** [comment]
> I didn't think of using <cmd> to be able to require a file.

Actually yoy can do `call v:lua.require'file'.function()` too. But I prefered `<cmd>` 😄

**Comment by DanielPower** [comment]
@shadmansaleh is your keymap solution (the one you linked in https://github.com/neovim/neovim/issues/14976#issuecomment-873523661) still working for you on 0.5 stable?
If I require it, and then define a keybind like this:
`keymap.inoremap('<Tab>', function() print('hello') return('') end, 'expr')`

Upon pressing Tab in insert mode, I receive the error: `E15: Invalid expression: <80><fd>hlua require("lua_callbacks")[2]()^M`.
I was receiving the same error when I tried to write my own implementation which uses a required callbacks object. 

The strange thing is I can call the callback directly from the ex command line by running `:lua require('lua_callbacks')[1]()`, and it will run the function. But if I instead run `:call v:lua.require('lua_callbacks')[0]()` I get a `Key not present in Dictionary` error.

In fact, even trying to create the most minimal reproduction. I created a lua module which just returns table of length 1, with a single function in it. I cannot figure out how to call the function from `v:lua`. :thinking:

**Comment by shadmansaleh** [comment]
In my one you don't need expr for functions .

just do `keymap.inoremap('<Tab>', function() print('hello') return('') end)`

**Comment by DanielPower** [comment]
> In my one you don't need expr for functions .
> 
> just do `keymap.inoremap('<Tab>', function() print('hello') return('') end)`

The function `TabComplete` returns key codes. So I need the `expr` option to have those key codes interpreted and run. Removing `expr = true` makes the error go away, but the value returned by the function doesn't get interpreted. I think the errors I'm getting with `expr` on your implementation are the same as or similar to the ones I got with austronata. So I'll investigate to see if there's something different I need to do with the return value of my callback function versus when using nvim_set_keymap.

> > The strange thing is I can call the callback directly from the ex command line by running :lua require('lua_callbacks')1, and it will run the function. But if I instead run :call v:lua.require('lua_callbacks')0 I get a Key not present in Dictionary error.
> 
> lua starts index with 1 not 0 that's why

Using `1` gives the same result. Vimscript indexes arrays at `0`, which causes some complication here. I tried `:echo v:lua.require('lua_callbacks')`, and it turns out vimscript only sees the named members when using the `v:lua` method of accessing the callbacks. So I guess this has to do with an incompatibility between vimscript arrays/dictionaries being separate data structures, vs lua tables. It looks like vimscript interprets `lua_callbacks` return as a dictionary and disregards the numbered values.

This doesn't seem to happen with your `<cmd>` usage.

**Comment by shadmansaleh** [comment]
> But if I instead run :call v:lua.require('lua_callbacks')[0]() I get a Key not present in Dictionary error.

I got it why you received this error . I totally forgot the fact the keymaps are stored in `registers` table inside `lua_calbacks` and and `lua_callbacks` has a meta method giving you those when you ask for them . But metatables aren't a thing in viml that's why when you access lua_callbacks from viml it doesn't work but when you access from lua it works.

> Upon pressing Tab in insert mode, I receive the error: E15: Invalid expression: <80><fd>hlua require("lua_callbacks")[2]()^M.

This one is also because I didn't handle `expr` . I've updated the [gist](https://gist.github.com/shadmansaleh/4f7eba765b413502fcfea893f4cf00b0) it should now support lua `expr` callbacks.

Also I've recently switched all my keymaps to [nvim-cartographer](https://github.com/Iron-E/nvim-cartographer) . It supports lua expr callbacks too . Has a nicer lua syntax imo . You can check that out if you want to 😄
