### ISSUE TITLE
Neovim-qt gui does not allow to change default font (Consolas)

### ISSUE THREAD

**Issue by duytrung** [neovim/neovim#14973]
- `nvim --version`: v0.6.0-dev+3-gd791274a9
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Windows 10
- Terminal name/version: Windows 10 CMD - or Neovim Qt
- `$TERM`:

### Actual behaviour
Neovim Qt GUI does not have a right-click menu to allow changing default font from Consolas to the other fonts

### Expected behaviour

I'm not sure whether this is a bug of Neovim so I would like to request for this feature in Neovim-qt GUI.

Thanks for considering the issue

**Comment by justinmk** [comment]
https://github.com/equalsraf/neovim-qt
