### ISSUE TITLE
Crash due to assertion when autocompleting lua commands

### ISSUE THREAD

**Issue by pranair** [neovim/neovim#14970]
- `nvim --version`: NVIM v0.5.0
- Operating system/version: Windows 10, WSL
- Terminal name/version: Windows Terminal
- `$TERM`: vtpcon

When `:lua xyz**a<TAB>` is executed it crashes due to assertion `../src/nvim/ex_getln.c:3951: nextwild: Assertion ccline.cmdpos >= i failed`. From messing around a bit it seems that this occurs only due to a single case i.e. when a single character is typed after the double asterix and `<TAB>` is pressed and this seems to occur only when `wildmode` is set to `longest:full`. Apart from that this also only seem to affect `:lua` commands.

### Steps to reproduce using `nvim -u NORC`

```
nvim -c "set wildmode=longest:full" -u NORC
```

### Actual behaviour
No crash, works like expected
### Expected behaviour
Crashes due to assertion.

**Comment by matu3ba** [comment]
@pranair I can not reproduce this with current master on Linux. Can you check, if the same error occurs? `assert(ccline.cmdpos >= i);` is now at line 3694.

I checked if `:lua pr` properly tabcompletes to `:lua print` and `:lua print(123)` properly prints 123.
