### ISSUE TITLE
Script to convert undofiles from before neovim 0.5 to be compatible with v0.5+ 

### ISSUE THREAD

**Issue by Srijan1214** [neovim/neovim#14978]
NVIM v0.5.0
Build type: Release
OS: Arch Linux

Upgrading from NVIM 0.4 to NVIM 0.5 caused undo files of previous versions to not be supported anymore. This was documented in this commit https://github.com/neovim/neovim/commit/6995fad260e3e7c49e4f9dc4b63de03989411c7b

Can the neovim team recommend any script to convert the previous undofiles to be compatible with NVIM v0.5+?

I currently get the `E824: Incompatible undo file: *path-to-undo-file*` message.

Thank you

**Comment by TimB87** [comment]
related #13973

**Comment by justinmk** [comment]
This never materialized and the urgency has waned by now.
