### ISSUE TITLE
ubuntu stable ppa version is not the latest stable version 0.5

### ISSUE THREAD

**Issue by stuart-warren** [neovim/neovim#14992]
following https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu

### Actual behaviour
```sh
$ sudo apt-get install -y software-properties-common
$ sudo add-apt-repository ppa:neovim-ppa/stable
$ sudo apt-get update
$ apt-cache show neovim | grep Version
Version: 0.4.4-1~ubuntu20.04.1~ppa1
Version: 0.4.3-3
```

### Expected behaviour
```sh
$ sudo apt-get install -y software-properties-common
$ sudo add-apt-repository ppa:neovim-ppa/stable
$ sudo apt-get update
$ apt-cache show neovim | grep Version
Version: 0.5.0-1~ubuntu20.04.1~ppa1
Version: 0.4.3-3
```

Many thanks

**Comment by jamessan** [comment]
https://github.com/neovim/neovim/issues/12726#issuecomment-670670201

**Comment by bavalpey** [comment]
Does this mean that 0.5.0 will be uploaded to the ubuntu stable ppa in the near future?  Do we have an eta for this?  What about for other package managers, including ones used by Fedora, etc.?

**Comment by jamessan** [comment]
It means that distro packages are maintained independently from the neovim repo, so this is not the place to discuss it.  The maintainers will get to it as they are able to.
