### ISSUE TITLE
Version confusion?

### ISSUE THREAD

**Issue by rgnkn** [neovim/neovim#14993]
I'm using the neovim-ppa on ubuntu for your fantastic editor, but just a couple of minutes ago there was this argument which version it is. `nvim --version` shows this (reduced to the important part):

NVIM v0.6.0-dev
[...]
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-THfJpv/neovim-0.5.0+ubuntu2+git202107041758-18bfcfe77-d569569c9=. [...]

Now we're all a bit confused, which version info is now valid - I guess I was wrong and it isn't v0.6.0-dev but v0.5.0, but could you please confirm this?

**Comment by Nine-H** [comment]
Commit 62d67de598286734536b63807d6b0f4e82b34128 bumped the version number. You're running the unstable PPA and the 0.5 release was three days ago. I'm wondering when a release build will hit the stable ppa. I'm not keen on running nightly.

**Comment by bfredl** [comment]
You need to bother the Ubuntu mainainers about this.

**Comment by rgnkn** [comment]
Another Bug: Neovim is too fantastic to be an Editor.

Never fix this!

;-)

**Comment by jamessan** [comment]
https://github.com/neovim/neovim/issues/12726#issuecomment-670670201
