### ISSUE TITLE
Feature: Ability to split windows along window's edge.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#1500]
For example, suppose open NeoVim, then split the window vertically. You now have 2 windows. Inside of  each of the two windows you can make any number of horizontal splits. There is an edge between the two groups that can be moved left or right. It'd be nice to be able to make a split right on that edge. The following video shows the scenario.

http://youtu.be/u_So9B5_fWc

Here's what it would look like after making the split:

http://youtu.be/EmlSV9JunaY

When you make lots of window splits, you'll notice atomic window groups. They consist of either all horizontal splits, or all vertical splits. For example, here are three window groups containing vertical splits:

http://youtu.be/MrAHLUt0CCA

I'd like to make a new window on the line below the middle group.

Lastly, here is the previous example, showing a sub-window-group inside the middle group:

http://youtu.be/U4GlfLXBsuo

In the last example, suppose I want to split along the right edge of the sub-window-group's left edge, then that would look like this:

http://youtu.be/OPWMKP04Rlo

In the last example, it was easy to do because I made a new window with `ctrl`+`w`, then `ctrl`+`shift`+`l` to move the window all the way to the right.

Now, if I want to split from that same sub-window-group along it's bottom edge, it would look like this:

http://youtu.be/mOdfMMyhhaM

In the last example, the new window appears along the bottom edge that is shared between the other windows.

So basically, these new windows splits would happen along an entire edge shared between window groups.

There would need to be some type of directional mapping to designate the top, bottom, left, or right edge of the window groups. For example, it might be `ctrl+w` followed by `ctrl+e` (e for "edge") followed one of `h`, `j`, `k`, or`l`. The sequence `ctrl+w` `ctrl+e` `k`, for example, would split along the top edge of a window group.

Alternatively, instead of splitting along a window-group's edge, you might just split along a window's edge with the previous commands, in which case it's be simple enough to navigate to a window that is on the edge of a window group, then use the commands on the edge of the window-group that is also the edge of the edge-window. 

When three or more windows exists in any workspace (i.e. tab), then there is always at least one window edge that is shared with other windows, and moving the edge resizes multiple windows, and when this edge is targetted from any window using the above command examples, then the new window is always born from the entire shared edge.

Does it make sense? I think this would add a huge amount of convenience and power to the way windows can be split. I've always encountered scenarios where I want to do this, and it requires some cumbersome window manipulation. It _might_ be possible as a plugin, but it seems better as a native feature.
#1500 seems to be a nice lucky number for this feature request. :D

**Comment by justinmk** [comment]
This feature won't be part of core, rather it is the domain of a plugin. Plugins need https://github.com/neovim/neovim/issues/3933 , that issue covers all window-management enhancements.
