### ISSUE TITLE
checkhealth/perl: Neovim::Ext" cpan module is not installed

### ISSUE THREAD

**Issue by nuanyang233** [neovim/neovim#15006]
- `nvim --version`:  NVIM v0.5.0
- Operating system/version: Macos Big Sur 11.4
- Terminal name/version: iterm2
- `$TERM`: xterm-256color

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

run `checkhealth`

### Actual behaviour

report:

```
## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed
```

### Expected behaviour

I tried to use `cpan Neovim::ext `  but it failed with error: 

```
Result: FAIL
Failed 56/59 test programs. 7/28 subtests failed.
make: *** [test_dynamic] Error 255
  JACQUESG/Neovim-Ext-0.05.tar.gz
one dependency not OK (MsgPack::Raw); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports JACQUESG/Neovim-Ext-0.05.tar.gz
```

**Comment by saadparwaiz1** [comment]
are you using the system perl? I think it's an issue with system perl; Try using the homebrew version or install it yourself

**Comment by jamessan** [comment]
Do you actually need the Perl bindings?  If not, there's no need to install them.  That being said, issues with the Perl bindings should be reported to https://github.com/jacquesg/p5-Neovim-Ext.

**Comment by jacquesg** [comment]
Please report this upstream with the full error output, then I can have a look at it.
