### ISSUE TITLE
Regression: "Invalid value for argument cmd: 'zsh -l' is not executable"

### ISSUE THREAD

**Issue by Goorzhel** [neovim/neovim#15009]
- `nvim --version`: v0.5.0
- Operating system/version: Void Linux
- Terminal name/version: `tmux`
- `$TERM`: `screen-256colors`

### Steps to reproduce ~using `nvim -u NORC`:~

`jobstart()` some kind of command that uses `[&shell, &shellcmdflag, a:cmd]`. I'm no good at Vimscript so I can't build a working example from scratch, but here's the specific problem I run into:

* Have [vim-airline](https://github.com/vim-airline/vim-airline) in `init.vim` (mine's through Vundle)
* Open a file, `nvim README.md`
* `vim-airline` [calls](https://github.com/vim-airline/vim-airline/blob/a94d8034c3d6548575482b434a6cead8acc1cfab/autoload/airline/async.vim#L101) `airline#async#nvim_vcs_clean` ([def](https://github.com/vim-airline/vim-airline/blob/a94d8034c3d6548575482b434a6cead8acc1cfab/autoload/airline/async.vim#L305-L331))
* Proceed to "Actual behaviour"

### Actual behaviour
```
Error detected while processing function airline#extensions#branch#get_head[1]..airline#extensions#branch#head[6]..<SNR>97_update_untracked[42]..airline#async#vcs_clean[6]..airline#async#nvim_vcs_clean:
line   24:
E475: Invalid value for argument cmd: 'zsh -l' is not executable
```
(I believe line 24 is [this one](https://github.com/vim-airline/vim-airline/blob/a94d8034c3d6548575482b434a6cead8acc1cfab/autoload/airline/async.vim#L329).)
 
### Expected behaviour

Neovim doesn't pop the above error, like in v0.4.4 with the same version of `vim-airline` (vim-airline/vim-airline@a94d803).

However, with `strace -vtttfo $log` and `grep 'zsh -l' $log` I _do_ see both versions doing this:
```
3723  1625628153.550045 statx(AT_FDCWD, "/usr/libexec/git-core/zsh -l", AT_STATX_SYNC_AS_STAT, STATX_ALL,  <unfinished ...>
3723  1625628153.550091 statx(AT_FDCWD, "/home/ag/bin/zsh -l", AT_STATX_SYNC_AS_STAT, STATX_ALL,  <unfinished ...>
3723  1625628153.550177 statx(AT_FDCWD, "/home/ag/.local/bin/zsh -l", AT_STATX_SYNC_AS_STAT, STATX_ALL,  <unfinished ...>
3723  1625628153.550241 statx(AT_FDCWD, "/srv/projects/.go/bin/zsh -l", AT_STATX_SYNC_AS_STAT, STATX_ALL,  <unfinished ...>
<and so on>
```

**Comment by chrisbra** [comment]
so what is the value of  `&shell` and `&shellcmdflag`?  Do you have perhaps `:set shell=zsh -l`?

**Comment by justinmk** [comment]
https://github.com/vim-airline/vim-airline/blob/70b06be4b067fec44756e843e2445cce5c97082f/autoload/airline/async.vim#L317-L329

`jobstart(["zsh -l", ...], ...) has never worked. If you didn't get that error before it was an accident of some other circumstance.

Without steps to reproduce a bug this is not actionable.

**Comment by Goorzhel** [comment]
To be frank, I don't know why `zsh` and `-l` are being concatenated together. But I'll take it up with `vim-airline` instead.
