### ISSUE TITLE
Treesitter Nixos

### ISSUE THREAD

**Issue by AusCyberman** [neovim/neovim#15019]
I'm running the flake in the contrib folder
- `nvim --version`: 
```
- NVIM v0.6.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/7bg8npcn53mi21j7zd7n7862293zcri7-neovim-unwrapped-master/share/nvim
"

Run :checkhealth for more info

```
- Operating system/version:
NixOS master
- Terminal name/version:
alacritty 0.8.0
- `$TERM`:
alacritty

### Steps to reproduce using `nvim -u NORC`
Have built parser, either compilled with nvim or from built grammers, in folder, nvim-treesitter installed.
Open a file that supports treesitter
```

```

### Actual behaviour
```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch f
or /home/auscyber/.config/nvim/parser/c.so: supported between 9 and 12, found 13
```
checkhealth
```
 ERROR: Neovim was compiled with tree-sitter runtime ABI version 12.
    nvim-treesitter expects at least ABI version 13
    Please make sure that Neovim is linked against are recent tree-sitter runtime when building or raise an issue at your Neovim packager. Parsers must be compatible with runtime ABI.
```
### Expected behaviour
Neovim correctly loads neovim treesitter object files

**Comment by justinmk** [comment]
> Neovim was compiled with tree-sitter runtime ABI version 12.

you need to build nvim, or get a nixos nvim package, with the required ts ABI. How you go about doing that is out of scope for the issue tracker.

This doesn't look like a bug, but a packaging issue or nixos question.

**Comment by AusCyberman** [comment]
> > Neovim was compiled with tree-sitter runtime ABI version 12.
> 
> you need to build nvim, or get a nixos nvim package, with the required ts ABI. How you go about doing that is out of scope for the issue tracker.
> 
> This doesn't look like a bug, but a packaging issue or nixos question.
Yes. it is a packaging issue, with the neovim repo being the culprit. You have control over the nix flake and control of dependencies in the flake.

**Comment by mjlbach** [comment]
Hi @AusCyberman, why don't you file an issue over on https://github.com/nix-community/neovim-nightly-overlay and I'll try to help you out. Teto and I manage the flake and it's in contrib, so let's not bother the non-nixos folks about it :)

**Comment by AusCyberman** [comment]
> Hi @AusCyberman, why don't you file an issue over on https://github.com/nix-community/neovim-nightly-overlay and I'll try to help you out. Teto and I manage the flake and it's in contrib , so let's not bother the non-nixos folks about it :) You probably just need to bump the pinned packages with `nix flake update` and rebuild

I have bumped everything multiple times and it still doesn't have the right treesitter
