### ISSUE TITLE
mapping <C-m> to xyz maps <CR> to xyz too

### ISSUE THREAD

**Issue by shaeinst** [neovim/neovim#15021]
- `nvim --version` v0.5.0
- Operating system/version:  Arch Linux/5.12.14
- Terminal name/version:  Tilix version: 1.9.4

`vim -u DEFAULTS` (version: 8.2) behaves differently

### Steps to reproduce using `nvim -u NORC`
I can reproduce this behavior when running neovim with nvim -nu NORC and doing nnoremap <c-m> :echo "hello, world!"<cr>. After that nnoremap <cr> shows that mapping.

### Actual behaviour
i thought this is related with telescope plugin so i [opened  #960](https://github.com/nvim-telescope/telescope.nvim/issues/960#issue-938764726) issue there but found it's may be bug in neovim.
when i map <c-m> to anything like
`nnoremap <c-m> :echo "hello, world!"`
it make \<CR\> to map to :echo "hello, world" too

### Expected behaviour
`nnoremap <c-m> :echo "hello, world!"` should not make \<CR\> to map to :echo "hello, world!"

**Comment by justinmk** [comment]
> `vim -u DEFAULTS` (version: 8.2) behaves differently

the answer is "no", because this is how vim works. `:help <cr>`
