### ISSUE TITLE
Cannot work with multibyte emojis

### ISSUE THREAD

**Issue by epii1** [neovim/neovim#15031]
- `nvim --version`: v0.5.0
- Operating system/version: macos big_sur
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color
- `vim -u DEFAULTS` (version: 8.2.3125) behaves NOT differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
# enter
👩‍✈️
👨‍👨‍👧‍👧
# or open file containing "👩‍✈️\n👨‍👨‍👧‍👧"
```

### Actual behaviour
```
👩<200d>✈️
👨<200d>👨<200d>👧<200d>👧
```

### Expected behaviour
```
👩‍✈️
👨‍👨‍👧‍👧
```

**Comment by clason** [comment]
Can you add the (mandatory) information whether vim behaves differently (making sure to note the version you tested)?

**Comment by lvht** [comment]
@clason updated

**Comment by bfredl** [comment]
`<200d>` seems like ZWJ, special case of https://github.com/neovim/neovim/issues/7151

**Comment by justinmk** [comment]
> `<200d>` seems like ZWJ, special case of #7151

closing as duplicate
