### ISSUE TITLE
Window resize shortly after start is ignored

### ISSUE THREAD

**Issue by getreu** [neovim/neovim#15044]
- `nvim --version`: 0.5.0
- Operating system/version: Debian 10
- Terminal name/version: xfce4terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

In the i3 window manager open a terminal window and type:

```
xfce4-terminal -x nvim -u NORC; xfce4-terminal
```

The above simulates the opening of 2 windows, where the second shortly appears after the first and causes a resize of the former. With the `i3` window manager this is a very common scenario. 

### Actual behaviour

The window resize caused by opening the last window is ignored. All lines are formatted wrongly (see screenshot).

![Screenshot_2021-07-10_09-08-46](https://user-images.githubusercontent.com/579082/125155589-550e2600-e161-11eb-88f7-78b7dd991e18.png)

### Expected behaviour

Neovim should buffer the resize event in case it can not execute it immediately.

**Comment by justinmk** [comment]
see also [sigwinch](https://github.com/neovim/neovim/issues?q=is%3Aopen+label%3Atui+sigwinch) and https://github.com/neovim/neovim/issues/11330 .

> Neovim should buffer the resize event in case it can not execute it immediately.

Something like that. Maybe we should debounce: 

1. schedule resize for 1 second later
2. any new resize request, replaces the scheduled one
3. only perform the last resize request

**Comment by getreu** [comment]
My workaround until this bug gets fixed:
Place `nvim.appimage` in `/usr/loca/bin/`, then edit a file `/usr/local/bin/nvim` with the following content:

```bash
#!/bin/sh
sleep 1
/usr/local/bin/nvim.appimage "$@"
```

**Comment by reportaman** [comment]
Seems like this could be related to https://github.com/tmux/tmux/issues/2981#issuecomment-981545602

**Comment by samhh** [comment]
@reportaman Happens for me without tmux.

**Comment by rdfing-respells-live** [comment]
Facing this same issue, see screenshot.

Works properly with workaround mentioned by @getreu

![Screenshot](https://user-images.githubusercontent.com/107582805/173916231-7228f27b-fc78-40e0-9eab-e95a855fc29b.png)
