### ISSUE TITLE
Neovim flashes intro display and status bar then everything disappears

### ISSUE THREAD

**Issue by jeffkbkim** [neovim/neovim#15046]
- `nvim --version`:
```
nvim --version
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-43048-zidk8j/neovim-0.5.0/build/config -I/tmp/neovim-20210702-43048-zidk8j/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-43048-zidk8j/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-43048-zidk8j/neovim-0.5.0/build/include
Compiled by brew@Mojave

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info
```

- Operating system/version: macOS Mojave 10.14.6
- Terminal name/version: iTerm2 Build 3.4.8
- `$TERM`: screen-256color

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

1. install neovim via brew install neovim. This installs 0.5.0
2. run `nvim`. `nvim -u NORC` also shows the same issue
3. empty `$HOME/.config/nvim` directory. no settings, no mappings, no plugins.

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
The intro display (`NeoVim 0.5`) and the status bar (`[No Name]`) upon startup blinks for around 100 millisecond then disappears. This affects other plugins, i.e. [vim-airline](https://github.com/vim-airline/vim-airline).

### Expected behaviour
The intro screen should stay up, and the status bar should show the buffer name. instead, they both disappear instantly.

**Comment by clason** [comment]
I can't reproduce that with `nvim -u NONE` (which skips plugins). Maybe there's something left in another `runtimepath`/`packpath` location (e.g., `.local/share/nvim/site/pack/**`)?

**Comment by jeffkbkim** [comment]
@clason thanks! removing that directory did the trick. closing.
