### ISSUE TITLE
Highlight folded line when cursor is on it    

### ISSUE THREAD

**Issue by huangyingw** [neovim/neovim#15053]
I found a behavior change at nvim, I used bisect to find the first commit for this change. https://github.com/neovim/neovim/commit/f8134f2fd1e2effe79d011b1ff12ebb8719c3ffe

        commit f8134f2fd1e2effe79d011b1ff12ebb8719c3ffe
        Author: Matthieu Coudron <mattator@gmail.com>
        Date:   Sat Jun 20 01:57:07 2020 +0200

        screen.c: remove fold_line
    
    before this commit, 
        all the folded line, including the current cursor line would be high lighted.
![image](https://user-images.githubusercontent.com/91757/125183548-38f39e80-e1cc-11eb-8560-f304939b1d65.png)

    after this commit, 
        move the cursor to the folded line, the high light would disappear.
![image](https://user-images.githubusercontent.com/91757/125183551-401aac80-e1cc-11eb-9ec3-575a3eec863b.png)

    I prefer the previous behavior, so I know easily,  with the high light,  that the current line is folded.    
    I could not simply revert that commit in latest master branch, it would result in lots of conflicts.

**Comment by teto** [comment]
it's because it was impossible to highlight the current fold that I made the change. I think you would  like CursorLine highlights to be merged with the folded one.

**Comment by huangyingw** [comment]
> it's because it was impossible to highlight the current fold that I made the change. I think you would like CursorLine highlights to be merged with the folded one.

    I will try, while this is definitely not easy for me:(

**Comment by teto** [comment]
why closing, this is still an issue is it not ?

**Comment by huangyingw** [comment]
> why closing, this is still an issue is it not ?
I found a rude solution:
https://github.com/neovim/neovim/issues/15156
maybe we could introduce a vim configuration there?
or maybe a better solution?
