### ISSUE TITLE
Windows: luajit ffi calls to Nvim core functions broken

### ISSUE THREAD

**Issue by Kartiku** [neovim/neovim#15063]
- `nvim --version`:
```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"
```
- Operating system/version:  Windows 10

### Steps to reproduce

While hitting a [telescope bug](https://github.com/nvim-telescope/telescope.nvim/issues/706) (duplicate [here](https://github.com/nvim-telescope/telescope.nvim/issues/968)) I looked into why luajit ffi calls were failing only on windows.

To repro the bug call a neovim core function using ffi.  I put this in `init.lua`

```lua
local ffi = require('ffi')
ffi.cdef [[
typedef unsigned char char_u;
char_u *__stdcall shorten_dir(char_u *str);
int printf(const char *fmt, ...);
]]

ffi.C.printf("Hello %s!", "world")
local filepath = "C:\\Users\\joe\\.vim\\plugged\\telescope.nvim\\lua\\telescope\\path.lua"
local c_str = ffi.new("char[?]", #filepath + 1)
ffi.copy(c_str, filepath)
ffi.string(ffi.C.shorten_dir(c_str))
ffi.C.printf(c_str)
```

Running nvim on windows gives error `cannot resolve symbol 'shorten_dir': The specified procedure could not be found.`.  I'm told it works on unix.

Adding `__declspec(dllexport)` to the function definition in `src/nvim/path.c` like so fixes the issue.

```c
__declspec(dllexport) char_u *shorten_dir(char_u *str)
```

The above telescope bug can be easily fixed by providing a pure lua version of `shorten_dir`.  However calling neovim core functions from lua could still be useful.  Could we add a `#define` that is set to `__declspec(dllexport)` on windows?  Then marking all neovim core functions with this define? (or selectively export functions that could be useful in lua)

**Comment by Kartiku** [comment]
Perhaps also related.  Can't tell if this was fixed later.  Looks like ffi usage in the unittest

> Unit tests are not working in windows, due to the inability to use the luajit ffi.

https://github.com/neovim/neovim/issues/5229

**Comment by bfredl** [comment]
Normally for cases like this we add new API functions, something like `nvim_path_shorten`, which would have stability guarantees going forward unlike internal C functions (which have none).

**Comment by romgrk** [comment]
On the other hands, being able to have access to an unstable API now is still nicer than not being able to access anything, for plugins. It also allows plugins to hack experiments faster than if there is the need to wait on an upstream contributor (hitting this issue in [context](https://github.com/romgrk/nvim-treesitter-context/issues/51), trying to call `curwin_col_off`).

**Comment by lewis6991** [comment]
Also, Gitsigns currently relies on the FFI (until #14536 is merged) and at the moment windows users are stuck with running diffs via an expensive external process.

**Comment by justinmk** [comment]
related: https://github.com/neovim/neovim/pull/7786

**Comment by famiu** [comment]
> On the other hands, being able to have access to an unstable API now is still nicer than not being able to access anything, for plugins. It also allows plugins to hack experiments faster than if there is the need to wait on an upstream contributor (hitting this issue in [context](https://github.com/romgrk/nvim-treesitter-context/issues/51), trying to call `curwin_col_off`).

Agree with this completely. I'd absolutely love this to be implemented since it's often very useful to not have to wait for an internal function to be made public through the API for implementing a feature in a plugin.
