### ISSUE TITLE
Spellfile argument regression in 0.5.0

### ISSUE THREAD

**Issue by randrej** [neovim/neovim#15066]
- `nvim --version`: 
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Operating system/version: Arch Linux (rolling release, updated today)
- Terminal name/version: `alacritty 0.8.0 (a1b13e68)`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set spellfile+=$HOME/.config/nvim/spell/sr@latin.utf-8.add
```

### Actual behaviour
An error message is reported.
```
E474: Invalid argument: spellfile+=$HOME/.config/nvim/spell
/sr@latin.utf-8.add
```

### Expected behaviour
The user spellfile for Serbian language, Latin script is added to the list of spellfiles, as was the case in versions <0.5.0

**Comment by MarcelRobitaille** [comment]
I am having a similar issue with spellfile paths with spaces inside, even after `set isfname+=32`. https://vi.stackexchange.com/questions/27837/how-to-set-spellfile-with-spaces https://github.com/vim/vim/issues/7230

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by randrej** [comment]
I've tried again (and made absolutely sure I was on the latest nightly), nothing changed. The same issue still occurs.

**Comment by kylo252** [comment]
@randrej, this is probably the same issue in #17059

It's because of the `@` symbol in `sr@latin.utf-8.add`, so please try this:

```vim
set isfname+=@-@
set spellfile+=$HOME/.config/nvim/spell/sr@latin.utf-8.add
echo &spellfile
```
