### ISSUE TITLE
Abbreviations not saved in session file

### ISSUE THREAD

**Issue by cab-1729** [neovim/neovim#15076]
- `nvim --version`: 0.4.3
- Operating system/version: OpenSuse Leap 15.2 on wsl
`:

### Steps to reproduce using `nvim`
1. make an abbreviation in vim using : ab <string> <string>
2. save session to a file using : mks! <filename.vim>
3. exit nvim and reload session with nvim -S <filename.vim>

### Actual behaviour

abbreviation set previously no longer available

### Expected behaviour

abbreviation stored in session file

I tried adding ```set sessionoptions+=localoptions``` in my init.vim. Still didn't get my abbreviations saved in the session file.

**Comment by justinmk** [comment]
1. abbreviations are not options , and `:help` for localoptions mentions nothing about also saving abbreviations.
2. you did not say whether you tried this in vim (and the version) but the issue template asks for that

**Comment by cab-1729** [comment]
I didn't try in vim at the time. Just installed vim and tried it out. Vim session are storing abbreviations. The version is 8.0.
