### ISSUE TITLE
Autoload variables doesn't get loaded when called "directly" from Lua functions.

### ISSUE THREAD

**Issue by atchim** [neovim/neovim#15074]
- `nvim --version`: NVIM v0.6.0-dev+42-geece0735f-dirty
- Operating system/version: Gentoo
- Terminal name/version: alacritty 0.9.0-dev (b0bc2a2)
- `$TERM`: alacritty

Consider that there's a file called `foo.vim` located at `~/.config/nvim/autoload/` and the following code is its content.

```vim
if exists('g:loaded_foo_autoload') | finish | endif
let g:loaded_foo_autoload = 1
let g:foo#bar = 2
```

Now consider that the first call to the global variable `g:foo#bar` comes from a file Lua file called `foo.lua` located at `~/.config/nvim/lua/foo.lua` and the following code is its contet.

```lua
vim.opt.cmdheight = vim.g['foo#bar']
```

The previous situation would lead to an error in my editor complaining that `cmdheight` doesn't accept `nil` as value. It happens because `g:foo#bar` wasn't actually loaded. In order to "avoid" that issue, I have to call `g:foo#bar` from VimL first to it get loaded, as the following code shows.

```lua
vim.api.nvim_exec('echo g:foo#bar', false)
vim.opt.cmdheight = vim.g['foo#bar']
```

Is this behavior expected or is it a bug?

**Comment by jdhao** [comment]
Can not reproduce this issue. I have tried to add a global variable `g:foo#bar` under one file in `~/.config/nvim/autoload`. Create a file under `~/.config/nvim/lua/foo.lua`:

```
print("foo#bar is", vim.g['foo#bar'])
```

Then open nvim and run `lua require('foo')`. The value of `g:foo#bar` is printed correctly.

I am using NVIM v0.6.0-dev+8-g75f758b99.

**Comment by atchim** [comment]
Even following your steps it keeps getting `nil` as result. I'll try to recompile Neovim. I don't know if `CFLAGS` used to compile Neovim led to this weird behavior.

**Comment by atchim** [comment]
> Even following your steps it keeps getting `nil` as result. I'll try to recompile Neovim. I don't know if `CFLAGS` used to compile Neovim led to this weird behavior.

Didn't worked even recopiling with CFLAGS='-O2 -march=native'.

**Comment by Chattille** [comment]
Same case in NVIM v0.6.1 (Compiled by brew@Monterey).
If the global variable defined in `autoload/*.vim` is loaded in Lua through `vim.g` for the first time, its value will be `nil`.
If the variable is first accessed in VimL, it will work as expected.

https://user-images.githubusercontent.com/53635735/153618840-565ca970-6130-4a9e-a142-27e294ca2542.mov
