### ISSUE TITLE
multigrid: mouse events crash neovim

### ISSUE THREAD

**Issue by yatli** [neovim/neovim#15075]
- `nvim --version`: NVIM v0.6.0-dev+32-ge43dbfdd0
- Operating system/version: win10-x64 build 19042
- UI: fvim/neovide (with multigrid support)

### Steps to reproduce using `nvim -u NORC`

```
fvim --debug-multigrid -u NORC
- or -
neovide --multiGrid -u NORC


:set mouse=a
press down mouse from within the buffer grid (usually grid #2)
drag mouse down towards status line (part of the "base grid #1")
once the mouse hits the status line, neovim crashes.

```

https://user-images.githubusercontent.com/20684720/125405892-cb718900-e3ea-11eb-9920-49f9c3f8878f.mp4

**Comment by akiyosi** [comment]
This will also be reproduced in goneovim.

**Comment by yatli** [comment]
The usual suspects show up :D :D

Related:
https://github.com/neovim/neovim/pull/12667

**Comment by bfredl** [comment]
> Related: #12667

does it fix this crash specifically?

**Comment by yatli** [comment]
I haven't tried that patch but I guess not likely. All it does is to translate between relative/absolute coordinates, and we can do it already in various frontends.

A few extra clues:
- It only happens with vertical boundaries. Horizontal out-of-bound events are fine and trigger scrolling.
- There's one curious case when I test in fvim though: if I bound test the drag event, and overwrite row number with 999 if it hits the statusline, it doesn't crash anymore (but obviously this isn't desired behavior because it scrolls so fast to the bottom of the buffer)
- Dragging the base grid (id=1) for window resizing works fine.

**Comment by yatli** [comment]
Crash site is `mouse_check_fold`, L740 -- it tries to read screen grid pass boundary.
