### ISSUE TITLE
[Lua] Globbing, When Adding All Files Within Directory, to $Var Not Working As Excepted in Lua

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [neovim/neovim#15071]
I have been researching this issue, but sadly have been unable to find any documentation or posts regarding it. I am trying to add all files within `/usr/share/dict` and `~/.loca/share/dict` to `vim.opt.dictionary`, but am running into some unexpected behavior. In vimscript the way this was often done was using globbing, in other words the proper setting would be

`set dictionary = "**/usr/share/dict/*,**~/.local/share/dict/*"

But when the above is translated into Lua, i.e.

`vim.opt.dictionary:append({"**/usr/share/dict/*,**/home/user/share/dict/*"})`

I get an error at startup which simply references the line number in my configuration file where the error was encountered, i.e. the line number containing the above code, and then says an unexpected argument was passed, it refers to the `*`. What would be the proper method for setting this variable in Lua with globbing?

I am using `nvim` version `0.6.0-dev` on Ubuntu.

**Comment by jdhao** [comment]
@FOSSilizedDaemon  Maybe you can use `vim.fn.globpath()` to get the file paths you want and then add it to option `dictionary`.

**Comment by FOSSilizedDaemon** [comment]
@jdhao I was just reading the documentation on that function :) Thank you so much.

**Comment by jdhao** [comment]
I have also found this page: http://lua-users.org/wiki/FileGlob. It seems that glob feature is missing in Lua. You need to use 3rd party lua packages for that.

**Comment by FOSSilizedDaemon** [comment]
@jdhao For vim.fn.globpath?

**Comment by jdhao** [comment]
No, I mean it is hard to glob paths in native lua.

**Comment by FOSSilizedDaemon** [comment]
@jdhao Ohhhhhhhhhhhhh

**Comment by FOSSilizedDaemon** [comment]
@jdhao Could you expand doing this with `globpath`? I did some attempts at this and `globpath` needs two arguments, but I only have one to give it, the path. There is no file extension to give `globpath` as I want every file in those two directories.

**Comment by jdhao** [comment]
> vim.opt.dictionary:append(vim.fn.globpath(global_dictionaries, ''))

You are doing it the wrong way. First, you do not provide the glob pattern in the second parameter of `globpath()`. Second, other parameters are missing. Please read `:h globpath()` carefully and make sure you understand it.

@FOSSilizedDaemon  The following works for me:

```
local dict_files = vim.fn.globpath('/usr/share/dict', '*',  0, 1)
```

`dict_files` will be a lua table containing all the files under directory `/usr/share/dict`.

**Comment by FOSSilizedDaemon** [comment]
@jdhao Ohhhh, okay this is working. The only last issue I am having is that doing

```
-- Load all files from '/usr/share/dict/' and '~/.local/share/dict/' to be used as dictionary files.
local local_dictionaries      = vim.env.HOME .. '/.local/share/dict/'
local local_dictionary_files  = vim.fn.globpath(local_dictionaries, '*', 0, 1)
local global_dictionary_files = vim.fn.globpath('/usr/share/dict/', '*', 0, 1)

vim.opt.dictionary:append(local_dictionary_files)
vim.opt.dictionary:append(global_dictionary_files)
```

does not seem to append every files within my dicts. Do I need to loop through them all and append each entry one by one?

**Comment by FOSSilizedDaemon** [comment]
@jdhao I got it working! Here is the solution for anyone else who asks:

```
-- Load all files from '/usr/share/dict/' and '~/.local/share/dict/' to be used as dictionary files.
local local_dictionaries      = vim.env.HOME .. '/.local/share/dict/'
local local_dictionary_files  = vim.fn.globpath(local_dictionaries, '*', 0, 1)
local global_dictionary_files = vim.fn.globpath('/usr/share/dict/', '*', 0, 1)

for directory, file in pairs(local_dictionary_files) do
	vim.opt.dictionary:append(file)
end

for directory, file in pairs(global_dictionary_files) do
	vim.opt.dictionary:append(file)
end
```

**Comment by jdhao** [comment]
@FOSSilizedDaemon i think this can ne closed now.
