### ISSUE TITLE
Divide and extract default runtime to "plugin"s

### ISSUE THREAD

**Issue by hauleth** [neovim/neovim#1507]
Connected with #247

If this will be accepted then IMHO most of default runtime could (and should) be extracted to external "plugins" that will be added to default `vimrc`.

What should be extracted:
- color schemes
- macros
- keymaps

I think that even `syntax`, `ftplugin` and others folder should be cleaned and extracted to extra repos.

**Comment by justinmk** [comment]
vimballs was decided in https://github.com/neovim/neovim/issues/2231. The other suggestions here are low priority since they are in `autoload/`. If there is a specific, singular task from this issue that anyone wants to address, feel free to make a PR.
