### ISSUE TITLE
No completion event is triggered when popup just disappeared but completion is active

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#15077]
There is no completion event triggered when doing the following:
- Initialize completion popup.
- Type to the point when popup just disappeared after most recent character. In this case completion is still active (if delete previous character, popup reappears).

**Edit**: latest Vim (8.2, patches 1-2815) also has the same behavior, but as Neovim has the initial implementation of `CompleteChanged`, I decided to open issue here.

Setup information:
- `nvim --version`: NVIM v0.5.0, Build type: RelWithDebInfo, LuaJIT 2.1.0-beta3
- Operating system/version: Ubuntu 18.04
- Terminal name/version: Gnome Terminal
- `$TERM`: xterm-256color

### Steps to reproduce

- Create the following configuration file (for example, under 'completion-event.vim')

```vim
let g:count_changed = 0
function TrackCompleteChanged()
  let g:count_changed = g:count_changed + 1
  echo 'CompleteChanged #' . g:count_changed
endfunction

let g:count_done_pre = 0
function TrackCompleteDonePre()
  let g:count_done_pre = g:count_done_pre + 1
  echo 'CompleteDonePre #' . g:count_done_pre
endfunction

let g:count_done = 0
function TrackCompleteDone()
  let g:count_done = g:count_done + 1
  echo 'CompleteDone #' . g:count_done
endfunction

au CompleteChanged * call TrackCompleteChanged()
au CompleteDonePre * call TrackCompleteDonePre()
au CompleteDone * call TrackCompleteDone()

set shortmess+=c
set noshowmode
```

- Run `nvim -u completion-event.vim`.
- Type `aaa<CR>bbb<CR>`.
- Initialize complete with `<C-N>` (`CompleteChanged` is triggered).
- Empty completion suggestion with `<C-P>` (`CompleteChanged` is triggered).
- Type `a` (`CompleteChanged` is triggered) and then type `c` (**no** event is triggered).
- Type `<DEL>` to see that completion is still active (`CompleteChanged` is triggered).

### Actual behaviour

No completion event is triggered.

Animation of behavior:

![neovim_completion-event-issue](https://user-images.githubusercontent.com/24854248/125478264-b1894b79-e95a-430e-b324-48766fae40a1.gif)

### Expected behaviour

Some completion event is triggered. More intuitively, it should be `CompleteChanged` as it does trigger when no item is selected.

**Edit**: Maybe even more intuitive would be to stop completion at this point (and thus trigger both `CompleDonePre` and `CompleteDone`). But this is probably too drastical. Is this behavior (not stopping completion when typing one character beyond all suggestions) intentional, because I couldn't find any reference?

**Comment by zeertzjq** [comment]
I think it is intentional, as if you type Backspace there will be more completion matches.

**Comment by echasnovski** [comment]
@justinmk, just to be clear: you think that Neovim will not fix this and it should be solved on Vim's side? So maybe I better create issue there?

**Comment by justinmk** [comment]
Makes more sense to send a PR to VIm, we wouldn't want to have a random behavior difference here.

**Comment by echasnovski** [comment]
Thanks, @glepnir!
