### ISSUE TITLE
A request to allow nvim-qt to initialize via ginit.lua instead of ginit.vim

### ISSUE THREAD

**Issue by peppermilldetective** [neovim/neovim#15080]
Since the base Neovim executable is now able to run using either init.vim or init.lua, it would be great if nvim-qt would have the same option. As-is (unknown if this is a bug at the moment as no one else one a quick search is talking about it), nvim-qt does not accept a ginit.lua file.

As for _why_ I would like to use the GUI, it's simple: Windows 10 is kinda garbage with terminals, and I've had little luck getting the terminals to work with nvim in a way that doesn't cause me headaches.

- CMD: some fonts and ligatures just don't work and it's so outdated that it occasionally breaks itself.
- PWSH: Rendering breaks on a different machine for _some reason_ making the tabs of barbar invisible and some code disappear when scrolling sideways.
- Alacritty: Mouse does not work. Period.
- Cmder: Scrolling with mouse has severe stuttering issues. I can see the cursor jumping all over the place.
- Windows Terminal: Slow and same problems as both CMD and PWSH intermittently.

**Comment by peppermilldetective** [comment]
Note: I do not believe the problems I have with the terminals are nvim problems as each terminal acts differently under with the same config files.

**Comment by glacambre** [comment]
I think this feature request should be opened in [neovim-qt](https://github.com/equalsraf/neovim-qt/)'s repository rather than here. As far as I can tell, loading a ginit.vim is performed [here](https://github.com/equalsraf/neovim-qt/blob/cafc9ca9f03e7f4104cc81c0330ae220e5f23497/src/gui/shell.cpp#L237-L242) and neovim doesn't do anything on its own.

**Comment by peppermilldetective** [comment]
Ah, my bad! I didn't know it was a separate repo, thanks for letting me know!
