### ISSUE TITLE
How can I disable default colorschemes.

### ISSUE THREAD

**Issue by ashincoder** [neovim/neovim#15083]
Hey, How can I disable the builtin colorschemes of neovim.

neovim version : NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include

ArchLinux

St Terminal

**Comment by clason** [comment]
What do you mean by "disable"? There must be _some_ colors to fall back to if no explicit `colorscheme` is set, otherwise you have an invisible editor...

**Comment by ashincoder** [comment]
Can I disable for instance the industry colorscheme.

**Comment by jdhao** [comment]
> Can I disable for instance the industry colorscheme.

It is not clear what you mean by 'disable'. Always state clearly the why of doing something. Maybe there is a better way to do what you want.

**Comment by ashincoder** [comment]
By disable I mean not to show the colorscheme in the menu

**Comment by clason** [comment]
You can remove the file from `/usr/local/share/nvim/runtime/colors/`

**Comment by ashincoder** [comment]
Does it cause any errors

**Comment by clason** [comment]
Why don't you try it?

**Comment by ashincoder** [comment]
ok

**Comment by ashincoder** [comment]
It works

**Comment by ashincoder** [comment]
no errors

**Comment by ashincoder** [comment]
Is there any option to disable it. It would be great

**Comment by clason** [comment]
No. Why? You still haven't answered _why_ you would want this.

**Comment by ashincoder** [comment]
Just my preference thanks

**Comment by reorx** [comment]
I write a script called `disable_nvim_builtin_colors.sh` to address the same issue I have with nvim on MacOS:

```
#!/bin/bash

# Directory path
base_path="/opt/homebrew/Cellar/neovim"

# Loop over directories in the path
for dir in $(ls $base_path); do
  # Check if the directory exists
  if [ -d "$base_path/$dir/share/nvim/runtime/colors" ]; then
    # Change to the directory
    dir_path="$base_path/$dir/share/nvim/runtime/colors"
    cd "$dir_path"
    # Rename all .vim files to .vim.disabled
    for file in *.vim; do
      if [ "$file" != "default.vim" ]; then
        mv "$file" "${file%.vim}.vim.disabled"
      fi
    done
    echo "Done $dir_path:"
    ls *.vim
  fi
done
```

**Comment by damionvega** [comment]
You can add the colorschemes to `wildignore` to have them not show up in a picker/menu:

```lua
vim.cmd([[set wildignore+=blue.vim,darkblue.vim,delek.vim,desert.vim,elflord.vim,evening.vim,industry.vim,koehler.vim,lunaperche.vim,morning.vim,murphy.vim,pablo.vim,peachpuff.vim,quiet.vim,retrobox.vim,ron.vim,shine.vim,slate.vim,sorbet.vim,torte.vim,wildcharm.vim,zaibatsu.vim,zellner.vim]])
```

### Using a .vim config file

```lua
-- init.lua

vim.cmd([[source ~/.config/nvim/setup.vim]])
```


```vim
" setup.vim

" Ignore default vim colorschemes
set wildignore+=blue.vim,darkblue.vim,delek.vim,desert.vim,elflord.vim,evening.vim,industry.vim,koehler.vim,lunaperche.vim,morning.vim,murphy.vim,pablo.vim,peachpuff.vim,quiet.vim,retrobox.vim,ron.vim,shine.vim,slate.vim,sorbet.vim,torte.vim,wildcharm.vim,zaibatsu.vim,zellner.vim
```

**Comment by telemachus** [comment]
@damionvega Great tip, but you don't need `vim.cmd`

```lua
vim.o.wildignore = join({
    -- A list of whatever else you want to ignore. E.g., "__pycache__", "*.o", etc.
    "blue.vim",
    "darkblue.vim",
    "delek.vim",
    "desert.vim",
    "elflord.vim",
    "evening.vim",
    "habamax.vim",
    "industry.vim",
    "koehler.vim",
    "lunaperche.vim",
    "morning.vim",
    "murphy.vim",
    "pablo.vim",
    "peachpuff.vim",
    "quiet.vim",
    "retrobox.vim",
    "ron.vim",
    "shine.vim",
    "slate.vim",
    "sorbet.vim",
    "torte.vim",
    "wildcharm.vim",
    "zaibatsu.vim",
    "zellner.vim",
}, ",")
```

**Comment by alanfzf** [comment]
Here's another way to do it if any one need it:

```lua
vim.opt.wildignore:append({
  "blue.vim",
  "darkblue.vim",
  "delek.vim",
  "desert.vim",
  "elflord.vim",
  "evening.vim",
  "industry.vim",
  "habamax.vim",
  "koehler.vim",
  "lunaperche.vim",
  "morning.vim",
  "murphy.vim",
  "pablo.vim",
  "peachpuff.vim",
  "quiet.vim",
  "ron.vim",
  "shine.vim",
  "slate.vim",
  "sorbet.vim",
  "retrobox.vim",
  "torte.vim",
  "wildcharm.vim",
  "zaibatsu.vim",
  "zellner.vim",
})
```

**Comment by oldbuilding** [comment]
I'm using Astronvim with lazy.nvim.  Had to do this inside astrocore.lua


        wildignore = table.concat({
          "blue.vim",
          "darkblue.vim",
          "delek.vim",
          "desert.vim",
          "elflord.vim",
          "evening.vim",
          "industry.vim",
          "koehler.vim",
          "lunaperche.vim",
          "morning.vim",
          "murphy.vim",
          "pablo.vim",
          "peachpuff.vim",
          "ron.vim",
          "shine.vim",
          "slate.vim",
          "sorbet.vim",
          "torte.vim",
          "wildcharm.vim",
          "zellner.vim",
        }, ","),
