### ISSUE TITLE
Tutor: Long, oddly-spaced lines

### ISSUE THREAD

**Issue by willeccles** [neovim/neovim#15088]
The following two lines have a slight problem at the moment (on nightly). I am not certain that these lines are supposed to break the 80 column limit, and they have a weird amount of space in them (implying to me that two lines were accidentally merged). It's been a while since I properly went through the tutor so it's entirely possible this is intentional, but I don't recall this being a feature of any particular lesson.

https://github.com/neovim/neovim/blob/02bf251bb3f1dd55a2c6599790ae6a7772082cdd/runtime/tutor/en/vim-01-beginner.tutor#L494
https://github.com/neovim/neovim/blob/02bf251bb3f1dd55a2c6599790ae6a7772082cdd/runtime/tutor/en/vim-01-beginner.tutor#L672

**Comment by rktjmp** [comment]
I would have thought these were synced with upstream, but it looks like neovims tutor has diverged in content and technical presentation, so I guess the patch should be done here?

**Comment by willeccles** [comment]
Thanks, I haven't had time to look at opening a PR for this!
