### ISSUE TITLE
Lsp aysnc formatting paste the code into my other buffer

### ISSUE THREAD

**Issue by marcushwz** [neovim/neovim#15089]
- `nvim --version`: 0.5.0 (release)
- nvim-lspconfig version(commit hash): cfab466
- What language server (If the problem is related to a specific language server): solargraph
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): no
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): no
- Is the problem isolated to a particular language server: I think so, tested the async format with rust seems to works fine
- Operating system/version: macOS (11.2.2)

### How to reproduce the problem from neovim startup
- Set auto command to run lsp async formatting on ruby file type
```vim
autocmd BufWritePre *.rb,*.rs lua vim.lsp.buf.formatting()
```
- Open two ruby files in split (wait until solargraph is initialized)
- Save and close one of the file

### Actual behaviour
- The content of the saved and closed file will be pasted in the next buffer
- Here is a short clip showing the problem
https://user-images.githubusercontent.com/40255418/125559870-19ebad2a-b165-4ffe-a778-80dba8a9a9dd.mp4

### Expected behaviour
- I am expecting that it shouldn't paste the code into another buffer
- It might be because solargraph is slow and I am wondering is there anyway to get this work, or I will just have to just use the sync formatting.

**Comment by mjlbach** [comment]
Can you try BufWritePost instead?

**Comment by marcushwz** [comment]
Thanks for fixing this, I actually have this setup currently with `BufWritePost`, but it's still the same problem. Do you mind sharing with me how can I trigger a save after the formatting with autocommand?
```lua
local on_attach = function(client)
    if client.resolved_capabilities.document_formatting then
        vim.api.nvim_command [[augroup Format]]
        vim.api.nvim_command [[autocmd! * <buffer>]]
        vim.api.nvim_command [[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]]
        vim.api.nvim_command [[augroup END]]
    end
end
```

**Comment by mjlbach** [comment]
I'd recommend using the non-asynchronous handler for formatting.

**Comment by marcushwz** [comment]
That does the tricks, thank you so much. Even though I can feel some delay as compared with the async formatting but it's fine for me. Thanks again and have a good day :)

**Comment by mjlbach** [comment]
Yeah, the sync formatting though will be much more reliable with `:wq` :)
