### ISSUE TITLE
Cmake cannot find remote.txt

### ISSUE THREAD

**Issue by koopa1338** [neovim/neovim#15081]
I have tried to update and install the latest version and got an error while installing, that the doc `remote.txt` could not be found.

These docs where removed in commit f2205b83c553367a76b6cad04a673077ae150fc1. Beside that this doc file is still required for installation (included in `build/runtime/cmake_install.cmake`), there are some interlinks in the docs to this document that should've also been removed:

```sh
grep -rin remote.txt
runtime/doc/help.txt:137:|remote.txt|	using Vim as a server or client
```

**Comment by clason** [comment]
I can't reproduce this. (Always `make distclean` first if `make` fails, especially when runtime files have been added or removed.)
