### ISSUE TITLE
global unsilent option

### ISSUE THREAD

**Issue by folke** [neovim/neovim#15096]
Right now, it's sometimes tricky to debug issues for code that is running part of silenced keybindings or autocommands.

Even when errors happen (like calling `vim.tbl_isempty` with a `nil` arg), they will not be shown anywhere.

Especially within lsp, things can break and the user won't always see any error message.

Would be really useful to have a global `unsilent` option, that when it's on, we always do echo, or writeerr regardless of whether it was started with `silent`

**Comment by justinmk** [comment]
This would be the 'verbose' option. If there's some component that you think should be added to a particular 'verbose' level, which exactly?
