### ISSUE TITLE
Q: How do I scroll a float window?

### ISSUE THREAD

**Issue by cathaysia** [neovim/neovim#15092]
Just like this picture:

![图片](https://user-images.githubusercontent.com/42114817/125713711-aa793d7b-4415-4d03-b225-a4375db09a23.png)

How do I scroll content of float window?

**Comment by theHamsta** [comment]
In case of this LSP preview window you can trigger `hover()` twice to enter the window and scroll like in regular Vim windows. You can also use `<c-w>w` to go to the next window until your cursor enters the float (or you scroll with the mouse, very un-vimy ;-))

**Comment by cathaysia** [comment]
Thanks. It works :)
