### ISSUE TITLE
'%' is extreamly slow in neovim

### ISSUE THREAD

**Issue by pheonix9001** [neovim/neovim#15108]
- `nvim --version`: v0.6.0-dev+43-g02bf251
- Operating system/version: Artix Linux s6 with 5.12.14-zen1-1-zen kernel
- Terminal name/version: st
- `$TERM`: st-256color

- NOTE: The system runs on busybox coreutils

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`
You should use a crappy VM to simulate this since my cpu is a potato

```
nvim -u NORC ex_commands.lua # this file has braces with >3000 lines in between
:39f{%
```

### Actual behaviour
Takes more than two seconds to find the corresponding brace

### Expected behaviour
It should find the corresponding brace instantly

I tested this with (busybox)`vi` and `vim` and both of them instantly find the corresponding brace.

**Comment by chrisbra** [comment]
Most likely, you did not enable the matchit plugin for vim. See if it makes a difference if you disable syntax highlighting.

**Comment by pheonix9001** [comment]
how do I enable matchit? I tried `packadd! matchit` but it makes no differance.

but turning off syntax highlighting makes it instant.

my vim also has syntax higlighting enabled btw(default in artix).

**Comment by chrisbra** [comment]
packadd should do it. You can check `:nmap %`. If it is mapped, than matchit is enabled.

**Comment by pheonix9001** [comment]
```
n  %             <Plug>(MatchitNormalForward)
```

it appears matchit gets loaded(by default as well).

**Comment by justinmk** [comment]
matchit is enabled by default. You did not say whether vim behaves the same, nor which version of vim you tested.
