### ISSUE TITLE
lsp: improve performance by converting vim.NIL to nil during JSON deserialization

### ISSUE THREAD

**Issue by hrsh7th** [neovim/neovim#15109]
- `nvim --version`: v0.6.0-dev+32-ge43dbfdd0
- language server name/version: typescript-language-server@0.5.4
- Operating system/version: Mac OS X BigSur

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>
health#nvim#check
========================================================================
## Configuration
  - WARNING: $NVIM_TUI_ENABLE_CURSOR_SHAPE is ignored in Nvim 0.2+
    - ADVICE:
      - Use the 'guicursor' option to configure cursor shape. :help |'guicursor'|
      - https://github.com/neovim/neovim/wiki/Following-HEAD#20170402

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: intelephense: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: purescriptls: configuration checked.
  - INFO: cssls: configuration checked.
  - ERROR: jdtls: The given command "vim.NIL/bin/java" is not executable.
  - INFO: html: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: gopls: configuration checked.
  - INFO: efm: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: rust_analyzer: configuration checked.
</details>

### Steps to reproduce using nvim -u minimal_init.lua

1. Apply the following patch to `runtime/lua/vim/lsp/rpc.lua`
<details>
<summary>patch</summary>

```diff
diff --git a/runtime/lua/vim/lsp/rpc.lua b/runtime/lua/vim/lsp/rpc.lua
index 4c5f02af9..bc4bda1bb 100644
--- a/runtime/lua/vim/lsp/rpc.lua
+++ b/runtime/lua/vim/lsp/rpc.lua
@@ -11,7 +11,9 @@ local validate, schedule, schedule_wrap = vim.validate, vim.schedule, vim.schedu
 --@param data (table) Data to encode
 --@returns (string) Encoded object
 local function json_encode(data)
+  local t = os.clock()
   local status, result = pcall(vim.fn.json_encode, data)
+  print(string.format("json_decode: %sms", 1000 * (os.clock()-t)))
   if status then
     return result
   else
@@ -68,7 +70,10 @@ end
 --@param v (any) Argument
 --@returns (any)
 local function convert_NIL(v)
-  return recursive_convert_NIL(v, {})
+  local t = os.clock()
+  local r = recursive_convert_NIL(v, {})
+  print(string.format("convert_NIL: %sms", 1000 * (os.clock()-t)))
+  return r
 end
 
 --@private
```

</details>

2. Create sample project with npm

<details>
<summary>package.json</summary>

```json
{
  "name": "sandbox-typescript",
  "main": "index.js",
  "devDependencies": {
    "@babel/cli": "^7.14.5",
    "@babel/core": "^7.14.6",
    "@babel/preset-env": "^7.14.5",
    "@types/date-fns": "^2.6.0",
    "@types/jest": "^26.0.24",
    "@types/lodash": "^4.14.171",
    "@types/node": "^16.3.2",
    "@types/react": "^17.0.14",
    "@types/react-dom": "^17.0.9",
    "babel-loader": "^8.2.2",
    "date-fns": "^2.22.1",
    "jest": "^27.0.6",
    "typescript": "^4.3.5"
  },
  "dependencies": {
    "@emotion/react": "^11.4.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "@material-ui/core": "^4.12.1",
    "@material-ui/icons": "^4.11.2",
    "formik": "^2.2.9",
    "lodash": "^4.17.21",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

</details>

3. Create `App.tsx` under the above sample project's (`src/App.tsx`)
<details>
<summary>App.tsx</summary>

```tsx
import React from 'react';

export const App = () => {
  return (
    <>
    </div>
  );
};
```

</details>

4. Invoke `v:lua.vim.lsp.omnifunc` on the `<|>` _| is cursor_
- This step needs a setup `typescript-language-server`

### Actual behaviour

`json_decode` and `convert_NIL` will take the time near the 100ms.

<details>
<summary>screenshot</summary>
<img width="1423" alt="スクリーンショット 2021-07-16 16 28 14" src="https://user-images.githubusercontent.com/629908/125909314-df429d31-e830-41af-8640-dbc4f1072d75.png">
</details>

### Expected behaviour

It will be good if these move to another thread or do more quickly.

**Comment by hrsh7th** [comment]
@mjlbach I've created the issue. If this is not a problem with neovim itself, feel free to close it.

**Comment by hrsh7th** [comment]
I've added a screenshot for explanation.

**Comment by vigoux** [comment]
This may be fixed by using `cjson` as suggested in https://github.com/neovim/neovim/pull/14871 ?
We'll follow this and see...

**Comment by clason** [comment]
It also helps to add a debounce via
```lua
  flags = { debounce_text_changes = 100 },
```
in the server setup call.

**Comment by clason** [comment]
(We've talked about making that a default -- any opinions?)

**Comment by mjlbach** [comment]
@clason that doesn't solve the case here, compe will clear our debounced cache on each completion call. The main issue is the size of the json packet from the server when the number of completion candidates is large, #14871 will address @hrsh7th's first point, but it will need a follow-up PR to make it drop nil's during the deserialization process in order to address the second. I think the first is enough that 0.5.1 will have acceptable completion performance for theia (in my testing)

**Comment by clason** [comment]
Gotcha; sorry for the drive-by comment!

**Comment by hrsh7th** [comment]
This issue does not relate to compe's implementation because the reproduce step uses `v:lua.vim.lsp.omnifunc`. (BTW, compe will cache completion response as much as possible).

I think this issue will be a real-world problem only the user using any *auto* completion engine.

**Comment by mjlbach** [comment]
@hrsh7th, sorry I didn't mean to imply that compe was unnecessarily flushing the cached text changes, just that any completion plugin will have to do this to provide up to date completion candidates which mean @clason's suggestion will not affect performance in this case (apart from reducing pressure on the language server generally).

**Comment by mjlbach** [comment]
@tjdevries and I talked about this and we decided the best solution is to patch the new cjson decoder (which solves half the original issue) to simultaneously convert vim.NIL to nil when applicable. Not sure when I will have time to do this, but the current status quo should (at least) be much better with the new decoder.
