### ISSUE TITLE
Conflicting advice in helphelp.txt 

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#15107]
- `nvim --version`: v0.6.0-dev+46-g682247b52

If you search for the text "the first line" in helphelp.txt, you will find 3 results. The first says:

```
Note that the title lines from the local help files are automagically added to
the "LOCAL ADDITIONS" section in the "help.txt" help file local-additions.
This is done when viewing the file in Vim, the file itself is not changed.  It
is done by going through all the help files and obtaining the first line of each
file.  The files in $VIMRUNTIME/doc are skipped.
```

The third result says:

```
The first line in a help file should have the following format:

helpfile_name.txt         For Vim version 7.3         Last change: 2010 June 4
```

If you take that advice, the entry that appears in local-additions is useless.

**Comment by chrisbra** [comment]
I don't follow. Why is this useless?

**Comment by ddickstein** [comment]
@chrisbra here's a sample of the local-additions that I have:

```
|tmux-navigator.txt| Plugin to allow seamless navigation between tmux and vim
|speeddating.txt| Use CTRL-A/CTRL-X to increment dates, times, and more
|matchit.txt|   Extended "%" matching
|merlin.txt|	For Vim version 7.3 	Last change: 2013 March 30
```

You'll see that for the first 3 there's a very useful summary, which I think is the point of local-additions taking the first line. But because `merlin.txt` followed the advice from the third result, its entry doesn't add any descriptive value in local-additions.

**Comment by rktjmp** [comment]
I don't disagree that the "for vim version ... last change" line is maybe less valuable than the one-line intro to a plugin, but that file is sourced from upstream (vim/vim).

From my observation, most of these requests are asked to be funneled upstream so both projects can benefit, perhaps you could see if there was any traction there?

Or I guess you could open a PR with a suggested language change and see how the core responded.

**Comment by chrisbra** [comment]
Okay understood, there is clearly some documentation issue. So please report to vim with concrete doumentation improvements. You may also want to report this to plugins that don't add any value there, like Merlin.

Thanks 
Christian

**Comment by dundargoc** [comment]
Oh yeah, I fixed this ages ago lol.

The new text in helphelp is

```
The first line in a help file should have the following format:

*plugin_name.txt*	{short description of the plugin}
```
