### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by huangyingw** [neovim/neovim#15106]
My os:
````    
    Ubuntu 20.04.2 LTS \n \l
````    

the commit I used, the latest one in master branch:
````    
    commit 682247b52e76180e4c49b794c6cc2548bfd32d4c (HEAD -> master, neovim/master)
    Merge: 19a2e59f7 f0cc3a948
    Author: Björn Linse <bjorn.linse@gmail.com>
    Date:   Wed Jul 14 22:21:57 2021 +0200

        Merge pull request #15078 from bfredl/p_vim_vi

        refactor(options): remove obsolete distinction of "vi" vs "vim" defaults
````    

The command I used to build:
````    
    apt-get install -y \
        autoconf \
        automake \
        cmake \
        g++ \
        libtool \
        libtool-bin \
        ninja-build \
        pkg-config \
        unzip

    rm -fr .deps/ build/ ; \
        make clean ; \
        make CMAKE_BUILD_TYPE=RelWithDebInfo \
        && sudo make install
````    

The command output:
````    
    CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
    Could NOT find Gettext (missing: GETTEXT_MSGMERGE_EXECUTABLE
    GETTEXT_MSGFMT_EXECUTABLE)
    Call Stack (most recent call first):
    /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
    /usr/share/cmake-3.16/Modules/FindGettext.cmake:81 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    src/nvim/po/CMakeLists.txt:1 (find_package)


    -- Configuring incomplete, errors occurred!
    See also "/root/myproject/git/vim/huangyingw/neovim/build/CMakeFiles/CMakeOutput.log".
    See also "/root/myproject/git/vim/huangyingw/neovim/build/CMakeFiles/CMakeError.log".
    make: *** [Makefile:100: build/.ran-cmake] Error 1
````    

The last part of the build log: build/CMakeFiles/CMakeError.log
````    
    Determining if the function pthread_create exists in the pthreads failed with the following output:
    Change Dir: /root/myproject/git/vim/huangyingw/neovim/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/ninja cmTC_9c8be && [1/2] Building C object CMakeFiles/cmTC_9c8be.dir/CheckFunctionExists.c.o
    [2/2] Linking C executable cmTC_9c8be
    FAILED: cmTC_9c8be 
    : && /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DCHECK_FUNCTION_EXISTS=pthread_create -O2 -g  -Og -g   CMakeFiles/cmTC_9c8be.dir/CheckFunctionExists.c.o  -o cmTC_9c8be  -lpthreads  /root/myproject/git/vim/huangyingw/neovim/.deps/usr/lib/libtree-sitter.a && :
    /usr/bin/ld: cannot find -lpthreads
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.



    Performing C SOURCE FILE Test HAS_WSTATIC_IN_INLINE failed with the following output:
    Change Dir: /root/myproject/git/vim/huangyingw/neovim/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/ninja cmTC_acdb2 && [1/2] Building C object CMakeFiles/cmTC_acdb2.dir/src.c.o
    FAILED: CMakeFiles/cmTC_acdb2.dir/src.c.o 
    /usr/bin/cc   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DHAS_WSTATIC_IN_INLINE -O2 -g  -Og -g   -Wstatic-in-inline -o CMakeFiles/cmTC_acdb2.dir/src.c.o   -c src.c
    cc: error: unrecognized command line option '-Wstatic-in-inline'
    ninja: build stopped: subcommand failed.


    Source file was:
    int main(void) { return 0; }
````

**Comment by rktjmp** [comment]
You're missing gettext.

https://github.com/neovim/neovim/wiki/Building-Neovim#ubuntu--debian

>     sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip

So
 
```
    apt-get install -y \
        autoconf \
        automake \
        cmake \
        g++ \
        libtool \
        libtool-bin \
        ninja-build \
        pkg-config \
        unzip \
        gettext
```

When testing I also had to `apt-get install git curl`, which may have brought other missing packages in, so cant promise just adding `gettext` will be all you need.

You will need to `apt-get install curl` if you get a luarocks install mpack error.

**Comment by clason** [comment]
Would be worth testing and, if `curl` and `git` are indeed needed, updating the instructions on the Wiki accordingly.

**Comment by rktjmp** [comment]
I added curl to the wiki, which definitely is a req. It's included on most systems but not guaranteed (deb has it, deb-slim for docker doesn't for example).

Luarocks fails to download its manifests, then fails to install mpack, but the error doesn't mention curl at all (or missing bin/command) and the host is reachable so it's a potential head scratcher. https://github.com/luarocks/luarocks/issues/952#issuecomment-546610645

I just guessed that curl would be the package name on all platforms... finding out is actually harder than it maybe should be since some package managers don't have a web interface.

Don't *think* git would be pulling in any reqs and honestly I'm too lazy to setup the docker mount to test. :-1:

**Comment by clason** [comment]
Adding known hard requirements is already helpful, thank you. And it's enough to add it for Ubuntu since we now know that it fails without it. We can add more systems (and dependencies) as they crop up.

**Comment by rktjmp** [comment]
So I went to test git, and it turns out `gettext` actually ends up installing the `curl` bin. Probably still worth listing it explicitly?

**Comment by clason** [comment]
Can't hurt, no.

**Comment by rktjmp** [comment]
Just confirming git isn't a req :tada:.

**Comment by huangyingw** [comment]
Thanks, yes, I need to install gettext.
and one more thing for my build failure is, in my Ubuntu, there is another libtool: /root/anaconda3/bin/libtool

I could help to setup a docker to verify nvim installation.
so, I will later create a PR for you to review?

**Comment by huangyingw** [comment]
I have a question, what's
    rm -fr .deps/ build/ 
vs    
    make clean 
?

sometimes, I feel I need to manually
    rm -fr .deps/ build/ 
especially after I copy codes from machineA(macos) to machineB(linux) and continue to build there.

could make clean also clean these 2 folders?
or maybe someone could help to update make clean to also clean these 2 folders?

**Comment by rktjmp** [comment]
`make clean` only cleans neovims build, not it is dependencies because you likely want to rebuild neovim more often than you want to rebuild the the dependencies since they are mostly static.

`make distclean` will remove the build folder.

I guess a `make depsclean` wouldn't be impossible, not my decision to make though I'm just cruising though.

I would look at your workflow first, transferring `.deps` and `build/` between different systems isn't a great idea because they will be incompatible. I.e. ignore those files in your copy script or docker mount, or use git push/pull to transfer just the source changes, etc.

**Comment by rktjmp** [comment]
Also I'm not sure what you mean about anaconda3, shouldn't have anything to do with nvim afaik.

**Comment by rktjmp** [comment]
@huangyingw Do you think this is closable, given the original issue is solved?
