### ISSUE TITLE
Lua lsp.log methods are not bound to public vim.lsp

### ISSUE THREAD

**Issue by vatosarmat** [neovim/neovim#15100]
There is `Lua module: vim.lsp.log` in `lua.txt` but it is not actually available
- `nvim --version`: v0.5.0

### Actual behaviour
`lua print(vim.lsp.log)` prints `nil`

### Expected behaviour
`lua print(vim.lsp.log)` prints something like `table: 0x7fd6666666`

**Comment by clason** [comment]
`vim.lsp.log` is in runtime, so you explicitly have to require it.

**Comment by clason** [comment]
Probably should be documented, though (that it's an internal API that is not exposed by default)? @mjlbach

**Comment by clason** [comment]
(Depending on what you are trying to do, there is a public log API exposed through `vim.lsp` itself, e.g., `vim.lsp.set_log_level()`.)

**Comment by teto** [comment]
we need to know your intention. If you are looking for some generic logging utilies, we dont have it yet but it is planned see https://github.com/neovim/neovim/pull/12503
