### ISSUE TITLE
makeprefix variable that gets prepended to makeprg

### ISSUE THREAD

**Issue by joshtriplett** [neovim/neovim#15105]
Sometimes I may be editing a file that resides on (or is mirrored to) a remote server, and when I go to do a build, I want to run the build command on that remote server. However, I don't want to override any file-type-specific logic that sets `makeprg`; for instance, the Rust mode automatically sets `makeprg` to either cargo or rustc depending on if a cargo project is detected.

I'd love to have an option `makeprefix`, which is automatically used as a prefix to `makeprg` whenever running `:make` command. That way, I can set `makeprefix`, but continue to allow file-type-specific vim modes to set `makeprg`.

- `nvim --version`:

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-eK2ojg/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-eK2ojg/neovim-0.4.4/build/config -I/build/neovim-eK2ojg/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-eK2ojg/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-eK2ojg/neovim-0.4.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently? No.
- Operating system/version: Debian, latest unstable
- Terminal name/version: gnome-terminal 3.38.3
- `$TERM`: xterm-256color

**Comment by justinmk** [comment]
Seems special-case or I'm missing something. Can this not be achieved by modifying 'makeprg' dynamically, e.g. on CmdlineEnter or via a mapping?

**Comment by joshtriplett** [comment]
@justinmk It certainly could be, but that level of hook seems more invasive, and I wouldn't have expected it would be the preferred approach.

This isn't a special-case for my personal system or usage; I'm thinking about general-purpose caching and distributed build tools, as well as tools that check or set project-specific environments, or other similar wrappers. Such things are easy to invoke on the command line by just prefixing a command, whatever that command might be.

**Comment by justinmk** [comment]
Would that be addressed by the introduction of a "project" concept in the editor? https://github.com/neovim/neovim/issues/8610
