### ISSUE TITLE
Does neovim depend/require a python-provider?

### ISSUE THREAD

**Issue by EdmundsEcho** [neovim/neovim#15119]
I've been using neovim for over 5 years now.  It's been great.  The one pain-point: the python-provider.

The question that I could not figure out reading the docs nor searching "online" (not just google :)):

Does neovim require a python-provider? I ask for several reasons, but just today, I could not run my neovim on a computer I had not used in about 6 months. My preference would be to dump the provider altogether.  I suspect there may be some plugins that need rely on python, they will have to go, so be it.  

Thanks for anyone with a better understanding of neovim and it's relationship with the python-provider to help me accomplish this declaration of independence from Python! :))

\- E

**Comment by Joakker** [comment]
Afaik, neovim doesn't *need* a python provider, and it can easily be deactivated by setting `g:loaded_python_provider` for Python2, and `g:loaded_python3_provider` for Python3. Since most plugins are written in vimL or, most recently, lua, this shouldn't render your config completely unusable.

**Comment by fsouza** [comment]
@EdmundsEcho it's not required, you can drop it. Yes some plugins will stop working, but you'll know right away.

**Comment by jdhao** [comment]
For plugins written in Python, you need to ensure that python provider is present. Those plugins require that you run the `:UpdateRemotePlugins` command after installation or update, for example, [Semshi](https://github.com/numirias/semshi), [deoplete](https://github.com/Shougo/deoplete.nvim).

As long as you do not use python remote plugins, it is fine to not have a python provider. For more information, see `:h remote-plugin`.

**Comment by EdmundsEcho** [comment]
Thank you to everyone for such complete and thoughtful answers.  I'm going to proceed accordingly.  \- E
