### ISSUE TITLE
lsp: document highlight and rename ranges incorrect with multibyte characters

### ISSUE THREAD

**Issue by jcorbin** [neovim/neovim#15116]
Two primary use cases:  reference highlighting and symbol renaming.

Example code used below: https://gist.github.com/jcorbin/100a4a2b690e3028813da84733f3b5a6

Here's my [vimrc](https://github.com/jcorbin/home/blob/main/.vimrc) used below; (just builtin LSP, no legacy LSP plugins involved). Screenshots done with numbering, cursor column, and cursor line enabled. Since LSP reference highlighting and renaming requires at least some vimrc, and I don't suspect that mine has any causal nature to this issue, I've not tried to do any config minimization / reproduction yet.

## Reference Highlighting

![image](https://user-images.githubusercontent.com/49715/126038579-2e900153-de8a-4230-b3c5-69113097a6f5.png)

With cursor on a symbol definition we see:
- correct highligh on lines 3, 7, and 11
- incorrect off by -2 highlight on lines 5 and 9 which have a unicode mid ellipsis and emoji respectively

## Symbol Renaming

Next up we use `vim.lsp.buf.rename()` to make the obvious rename of "data" to "lore":

![image](https://user-images.githubusercontent.com/49715/126038857-e6adcc38-f688-46fa-8a7e-a0444ee02546.png)

- the rename succeded on all but line 9 ; so it handled the unicode mid ellipsis correctly, but not the emoji
- here the rename is off by +1 rather than -2

## Detail

The two codepoints used are U+22EF and U+1F92F, but this problem will present with any emoji, or with any multibyte unicode codepoint (something I only learned while writing this issue actually)

![image](https://user-images.githubusercontent.com/49715/126039038-90a7fc0c-6a2d-4f53-9687-14b9ea46caca.png)

![image](https://user-images.githubusercontent.com/49715/126039046-8d0f70cf-21c3-4fc0-b293-f4dedd077759.png)

## Boilerplate

- `nvim --version`: this behavior has been present for a while during 0.5 dev cycle ; apologies for not reporting earlier
```
NVIM v0.6.0-dev+46-g682247b52
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/jcorbin/neovim/build/config -I/Users/jcorbin/neovim/src -I/Users/jcorbin/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/jcorbin/neovim/build/src/nvim/auto -I/Users/jcorbin/neovim/build/include
Compiled by jcorbin@anatta.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/jcorbin/.local/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: irrelevant
- Terminal name/version: irrelevant
- `$TERM`: irrelevant

### Steps to reproduce using `nvim -u NORC`

Skipped ; happy to attempt a reproduce if a "minimal LSP enabled RC" is suggested.

### Actual behaviour

See above.

### Expected behaviour

At the very least, anything that manipulates buffer content needs to be correct; highlighting is nice to have, but merely annoying if wrong.

**Comment by clason** [comment]
Multibyte unicode characters are a long-standing pain point; there are a number of similar issues and partial PRs already.

**Comment by jcorbin** [comment]
> Multibyte unicode characters are a long-standing pain point; there are a number of similar issues and partial PRs already.

Interesting, in my experience, the core vi/ex/vim stuff handles unicode properly: e.g. `:%s/data/lore/g` and search highlighting neither have this problem. It's only the new LSP hotness that has a problem; or do I misunderstand your sense of "long-standing"? ;-)

**Comment by clason** [comment]
Yes. It's synching up the (by itself correct) internal handling with the (different) Lua/LSP handling that is the problem. (LSP has been in development for long enough to merit "long-standing" ;))

The current thinking of the best approach is to expose the internal `mbyte.c` handling to the Lua API and use that: https://github.com/neovim/neovim/issues/14281

**Comment by jcorbin** [comment]
Gotcha, thanks for providing context and link!

**Comment by clason** [comment]
To the issue at hand: there have been a number of (repeated) fixes to multibyte handling that may not have been applied to every possible handler yet; e.g., https://github.com/neovim/neovim/pull/14231.

**Comment by mjlbach** [comment]
This should fix at least the highlighting issue https://github.com/neovim/neovim/pull/16218
