### ISSUE TITLE
why the hell does the cursor moves so damn fast now

### ISSUE THREAD

**Issue by D0nnieD4rk0** [neovim/neovim#15123]
whats the config variable for changing cursor speed anyway ?

**Comment by clason** [comment]
I don't even know what you mean -- that is completely determined by your terminal. (If neovim's input latency has gotten better, that is nice to hear, but I don't think there was any deliberate work in this direction.)

**Comment by D0nnieD4rk0** [comment]
yeah its something to do with alacritty thx
