### ISSUE TITLE
checkhealth Perl provider: ERROR: perl provider error "Neovim::Ext" cpan module is not installed

### ISSUE THREAD

**Issue by EdmundsEcho** [neovim/neovim#15130]
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3-
Compiled by brew@BigSur
Features: +acl +iconv +tui

- Operating system/version: Big Sur 11.4
- Terminal name/version: fish, version 3.1.2
- `$TERM`: tmux-256color

I just loaded Big Sur last night along with other updates using brew.  The following error came up in checkhealth.  

```
## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed
```

I went ahead with:`cpan -i Neovim::Ext` to install the package.  All seemed to install as expected.  However, the checkhealth gave me the same error.

... using `cpanm -n Neovim::Ext` with `sudo` did however work. 

\- E

**Comment by sober-wang** [comment]
why need perl ?
we already have the Python3 and Ruby and Node.js and Lua .

**Comment by clason** [comment]
If you don't use any Perl remote plugins, you don't need Perl and can just ignore the message. (The `checkhealth` output here is a bit inconsistent; it should be a `WARNING` not an `ERROR`, similar to other provider checks.)

**Comment by EdmundsEcho** [comment]
... someone mentioned "already have python..."

While I do work in python (when I have to :)), I'm happy to report that my neovim configuration no longer depends on python. This may be a unique state that generated the above mentioned errors with Perl.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/15006#issuecomment-874968926

need a perl person to look at this. cc @jacquesg

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/15006#issuecomment-899309603

report to https://github.com/jacquesg/p5-Neovim-Ext
