### ISSUE TITLE
Nvim causes freeze in next focussed pane of tmux at launch time when creating tmux panes and launching nvim quickly via some script

### ISSUE THREAD

**Issue by reportaman** [neovim/neovim#15148]
- `nvim --version`: NVIM v0.5.0-dev+nightly-356-gb28d458f8
- Operating system/version: macOS 11.4 ARM64/Apple M1
- Terminal name/version: Alacritty, latest
- `$TERM`: xterm-256color inside terminal, tmux-256color inside tmux

### Steps to reproduce:

This is not as relevant here, read tmux authors debug comments: https://github.com/tmux/tmux/issues/2787#issuecomment-884526880, https://github.com/tmux/tmux/issues/2787#issuecomment-884528399

### Actual behaviour

Described and discussed at length in https://github.com/tmux/tmux/issues/2787

In short: imagine having a script to launch tmux with two tmux vertical panes. After creating panes, launch nvim in pane-2 (right vertical pane), and put the focus back to pane-1 (left vertical pane). Given the focussed pane has login shell, it would be expected that user can start typing some command right away within login shell. But thats not what happens, the keyboard is largely frozen & the only way to be able to type something is to first hit one of these keys: ``C-c`` or ``Enter`` or ``a``. From the debug logs of tmux, its author says this is because of nvim (https://github.com/tmux/tmux/issues/2787#issuecomment-884526880):

> Whatever is running in pane %2 is requesting the terminal background colour using the bypass escape sequence which means the result will go as key presses to whatever pane is the active pane when it is received:
> 
> ```
> 1626903696.036945 input_dcs_dispatch: "tmux;\033]11;?\a"
> ```

Please suggest is there is a way to disable bypass escape sequence, or please consider fixing this if its not reconfigurable & there is another alternative. In my testing this does not happen with vim, but only neovim.

**Comment by glacambre** [comment]
@reportaman Have you tried manually setting your background color with `:set bg=light` or `:set bg=dark` in your init.vim?

**Comment by reportaman** [comment]
@glacambre The behavior reported in this bug does not happen anymore in nvim ``NVIM v0.6.0-dev+nightly-481-g6f48c018b``. Perhaps someone fixed it? Should I close it or let someone confirm if that is actually the case?

Yes I have tried ``set bg=dark`` in my .vimrc. I guess nvim will query the background of terminal if there is at least one highlight group that has ``fg=None`` or ``bg=None``.

**Comment by reportaman** [comment]
Closing as I don't see this issue anymore.
