### ISSUE TITLE
Statusline is always a blank bar, even on a fresh install with no configs, but NOT when I use "-u NONE"

### ISSUE THREAD

**Issue by hazeled** [neovim/neovim#15140]
- `nvim --version`:
```
NVIM v0.6.0-dev+59-g2475161de
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-948

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: 
Debian x86

- Terminal name/version:
Alacritty 0.8.0, but issue occurs on all terminals

- `$TERM`:
xterm-256color

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```
That's it, even with a new binary it's broken. The only way to have a working statusline is to use `nvim -u NONE`

### Actual behaviour
Statusline inside neovim is just blank, no matter what. Sometimes will flash back to correct statusline, but quickly flash back
![image](https://user-images.githubusercontent.com/74346877/126280735-ed72b5a6-35f4-4683-a2d5-c2585339009c.png)

### Expected behaviour
See a statusline as pictured
![image](https://user-images.githubusercontent.com/74346877/126280771-9e1d490f-9685-4f6e-9e5f-eca8e8a00ee3.png)

**Comment by clason** [comment]
Then it's something to do with your plugins (`-u NORC` will still load plugins, `-u NONE` doesn't).

**Comment by chrisbra** [comment]
please show the output of `:verbose set laststatus? ruler? rulerformat? statusline?`

**Comment by hazeled** [comment]
I disabled every plugin, and the issue still persists. I also moved the nvim directory and did `:PlugClean`. It definitely has to be something with plugins, but I have no idea how there would be a plugin

**Comment by hazeled** [comment]
@chrisbra Here you go!
`  laststatus=2
  ruler
  rulerformat=
  statusline=%=
        Last set from Lua`

**Comment by chrisbra** [comment]
there you have it, some lua plugin is causing this.

**Comment by hazeled** [comment]
@chrisbra That would make sense, but there's no Lua plugins installed. I moved the `nvim` folder, cleaned all plugins, and did a fresh install

**Comment by chrisbra** [comment]
check with `:scriptnames` perhaps this gives a clue

**Comment by hazeled** [comment]
I tried that, and it was almost all just things in tmp! However, when looking again, I see that somehow packer had installed to usr/local. I don't have packer installed, and I have no idea how it got on my machine, but deleting the files fixed it! Thank you so much!
