### ISSUE TITLE
`hi` does not work from lua with `vim.cmd`

### ISSUE THREAD

**Issue by ExpandingMan** [neovim/neovim#15149]
- `nvim --version`: v0.6.0-dev+61-g6f48c018b
- Operating system/version: Manjaro Linux 21.1.0
- Terminal name/version: alacritty 0.8.0
- `$TERM`: alacritty

### Actual behaviour
Calling any `hi` command in lua with `vim.cmd("hi...")` has no effect.  Works fine when called either in `init.vim` or as a direct command.

For example I have 
```
vim.cmd("hi Identifier guifg="..dracula.orange)    -- symbols
vim.cmd("hi Constant guifg="..dracula.red)         -- literals
vim.cmd("hi Macro guifg="..dracula.green)          -- macros
vim.cmd("hi Function guifg="..dracula.purple)      -- functions
```
but it isnt' doing anything.

### Expected behaviour
Expect it to change highlighting like ti does in the vim script configs.

Btw, if there is a way to do this purely in lua, that would seem preferable, but I couldn't find it.

Update:  Oddly, I find that I can launch `nvim` and then do `:lua vim.cmd("hi Function guifg=#000000")` in the terminal and it works... this is really weird, it might suggest something is overwriting my options?  I'm not sure what that could be.  It doesn't work even if I put this at the very end of my `init.lua`

**Comment by jdhao** [comment]
what is the output of `:verbose hi Identifier` when you are inside Neovim? I suspect that your colorscheme may have overwritten the settings. [This post](https://jdhao.github.io/2020/09/22/highlight_groups_cleared_in_nvim/) may be helpful.

**Comment by clason** [comment]
If you set a color scheme, you _need_ to put additional highlighting commands into an `au ColorScheme` autocommand. Otherwise they get overridden by the color scheme (which usually does -- and should do -- `hi clear` at the very beginning).

**Comment by ExpandingMan** [comment]
Ok, you're right the `colorscheme` command is overriding it even if I call it *before* the rest of the `hi` commands.

I think there may still be a real issue here in that the behavior seems to be different depending on whether I declare the colors in `init.vim` or `init.lua`, which does not seem ideal.  I'm guessing that the difference has something to do with where in the loading pipeline each of them is processed.
