### ISSUE TITLE
better way to partly disable area_highlighting?

### ISSUE THREAD

**Issue by huangyingw** [neovim/neovim#15156]
This is the current behavior of folding:
![66D7B3CA-1024-49C2-B9DB-C39E54F50E82_4_5005_c](https://user-images.githubusercontent.com/91757/126739053-a767b69c-285c-42ea-a949-079d16f32fa7.jpeg)

This is the behavior I prefer.
![3D12729F-7F1E-457A-BE10-AF9418922DAB_4_5005_c](https://user-images.githubusercontent.com/91757/126739058-f6992aa7-56e2-4d48-bab0-c843592cb665.jpeg)

So, I made the rude change to make it happen:

````
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
index ae785132b..1472fade1 100644
--- ./src/nvim/screen.c
+++ ./src/nvim/screen.c
@@ -2396,10 +2396,6 @@ static int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow,
     line_attr = win_hl_attr(wp, HLF_QFL);
   }
 
-  if (line_attr_lowprio || line_attr) {
-    area_highlighting = true;
-  }
-
   line = ml_get_buf(wp->w_buffer, lnum, FALSE);
   ptr = line;
 
````

to make this customization happen, I need to compiled nvim on every machine I used.
any other better solution?

could we introduce a vim configuration to allow the user to conveniently customize the behavior they like?
I am imaging some change like following:

````
M src/nvim/screen.c
@@ -2396,7 +2396,7 @@ static int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow,
     line_attr = win_hl_attr(wp, HLF_QFL);
   }
 
-  if (line_attr_lowprio || line_attr) {
+  if (!vim_config_name && (line_attr_lowprio || line_attr)) {
     area_highlighting = true;
   }
 
````

**Comment by huangyingw** [comment]
related to this ticket:
https://github.com/neovim/neovim/issues/15053
@teto

**Comment by justinmk** [comment]
there is now `:help 'cursorlineopt'`
