### ISSUE TITLE
Gets ^I when remapping `<right>` to `<down>` in wildmenu with wildoptions=pum

### ISSUE THREAD

**Issue by themadsens** [neovim/neovim#15155]
This is nagging me every day, and it seems to be known but with no _specific_ issue  covering the glitch. Hence this one.

Strangely, I only get the issue on Linux, **not** on MacOS 

Linked comment below: (Also, next comment https://github.com/neovim/neovim/issues/9953#issuecomment-569893556 mentions this discussion: https://github.com/neovim/neovim/pull/11001#issuecomment-536450197)

/Flemming

But how to also remap `<right>` to `<down>` so that `<right>` confirms the completion (when completing directories)?

```
cnoremap <expr> <left> pumvisible() ? "<up>" : "<left>"
cnoremap <expr> <right> pumvisible() ? "<down>" : "<right>"
```

The remapping of `<left>` works as expected, but not `<right>`.
Pressing `<right>` when completing files inserts `^I` into the commandline instead of confirming the completion.

_Originally posted by @cjxgm in https://github.com/neovim/neovim/issues/9953#issuecomment-569891381_

**Comment by justinmk** [comment]
works for me, tested with `nvim -u NONE` bc570b006413 and

```
cnoremap <expr> <left> pumvisible() ? "<up>" : "<left>"
cnoremap <expr> <right> pumvisible() ? "<down>" : "<right>"
```

likely a terminfo issue on your system
