### ISSUE TITLE
Neovim Fails to Run on Mac - High Sierra (10.13.6)

### ISSUE THREAD

**Issue by ossie-git** [neovim/neovim#15160]
- `nvim --version`: 0.5.0 + v0.6.0-dev+63-ga8c3d50fa
- Operating system/version: Mac OS - High Sierra (10.13.6)
- Terminal name/version: iTerm2
- `$TERM`: screen

### Steps to reproduce using `nvim -u NORC`

```
$ ./nvim-osx64/bin/nvim -u NORC
```

### Actual behaviour

Just downloaded Neovim to try it out on a Mac OS - High Sierra (10.13.6). I tried both the latest (0.6) and the stable (0.5) and running either would result in the following error:

```
$ ./nvim-osx64/bin/nvim -u NORC
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/me/Downloads/./nvim-osx64/bin/nvim
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/me/Downloads/./nvim-osx64/bin/nvim
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

So it doesn't even launch. After a little search, I ran into a similar error [here](https://help.galaxyproject.org/t/command-line-error-dyld-lazy-symbol-binding-failed-symbol-not-found-chkstk-darwin/4188) and it looks like it is due to it being compiled on a newer OS version. Would it be possible to add backwards compatibility in future builds? Thanks.

### Expected behaviour

That it would run. I tried an older version (0.4.4) and it works.

**Comment by hronro** [comment]
It seems the prebuilt binaries are targeting macOS 10.15, try build it yourself may fix the problem.

BTW, is it possible to ship rebuilt binaries can run in older macOS?

**Comment by ossie-git** [comment]
For anyone else who finds themselves in the same situation, here's a summary after some investigation. When running:

```
brew install neovim
```

it looks like Neovim itself isn't the issue (at least I didn't get to that stage) but rather, some of the dependencies like: *emscripten* which require jdk which in turn looks for the 10.14 SDK and fails as shown below:

```
...
==> Installing dependencies for neovim: openjdk, yuicompressor, emscripten, rust and tree-sitter
==> Installing neovim dependency: openjdk
==> ./configure --disable-warnings-as-errors --with-boot-jdk-jvmargs=-Duser.home=/Users/me/Library/Caches/Homebrew/java_cache --with-boot-jdk=/private/tmp/openjdk-20210730-95071-tvnba5/jdk16u-jdk-16.0.1-ga/boot-jdk/Contents/Home --with-debug-level=re
==> make images
Last 15 lines from /Users/me/Library/Logs/Homebrew/openjdk/02.make:
                                    watchos(1.0, API_TO_BE_DEPRECATED),
                                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:357:47: error: expected a version of the form 'major[.minor[.subminor]]'
                                    tvos(2.0, API_TO_BE_DEPRECATED));
   ... (rest of output omitted)

* All command lines available in /private/tmp/openjdk-20210730-95071-tvnba5/jdk16u-jdk-16.0.1-ga/build/macosx-x86_64-server-release/make-support/failure-logs.
=== End of repeated output ===

No indication of failed target found.
Hint: Try searching the build log for '] Error'.
Hint: See doc/building.html#troubleshooting for assistance.

make[1]: *** [main] Error 2
make: *** [images] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
openjdk 16.0.2 https://github.com/Homebrew/homebrew-core/pull/81708
openjdk@8: upstream Linux fixes https://github.com/Homebrew/homebrew-core/pull/80957
OpenJDK is somewhat broken on newer MacOS instances, console is flooded with errors when using JMeter, AdoptOpenJDK has no issues https://github.com/Homebrew/homebrew-core/issues/66953

Error: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
```

On the plus side, I was able to find a way to install it by using *MacPorts* instead (they have a binary for it so you don't even have to compile it)

**Comment by ossie-git** [comment]
@hronro I'm pretty sure you can. For example, MacPorts releases binaries that run on Mac OS versions that are 10 years old (check this for an example: https://ports.macports.org/port/neovim/details/)

**Comment by justinmk** [comment]
> dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin

@ossie-git  are you on M1 by chance? Or maybe this was fixed accidentally by a CI hardware change? The latest nightly @ 1f49268c4 works for me on macos big sur `11.5.2`. Although, running it was tricky because macos wanted me to verify the binary and the included `libs/*` : 

![image](https://user-images.githubusercontent.com/1359421/133890255-6d88ba0a-5632-4741-a76d-a060bc726a89.png)

> BTW, is it possible to ship prebuilt binaries can run in older macOS?

Nope. Whatever CI (GitHub Actions, at the moment) gives us is what we can target. 

> ==> Installing dependencies for neovim: openjdk, yuicompressor, emscripten, rust and tree-sitter

That's a different issue. Er...  must be a detail of how homebrew has packaged treesitter.

**Comment by clason** [comment]
> Er... must be a detail of how homebrew has packaged treesitter.

Yep, at least initially. They don't pull the kitchen sink in any longer if you just `brew install neovim`.
