### ISSUE TITLE
Add missing nvim_buf_get_text

### ISSUE THREAD

**Issue by max397574** [neovim/neovim#15168]
There is the `nvim_buf_get_lines` and the `nvim_buf_set_lines` these are to get and set whole lines and take a start and end row as arguments.
and there is the `nvim_buf_set_text` which takes rows and columns as arguments
but there is no `nvim_buf_get_text`

**Comment by max397574** [comment]
I just found two other "missing" functions. I don't know if they are possible or not.

`nvim_buf_del_lines``nvim_buf_del_text`I think it's obvious what they would do

**Comment by bfredl** [comment]
> nvim_buf_del_lines/nvim_buf_del_text I think it's obvious what they would do

those are already covered by set_lines and set_text: just use empty list for replacement text.

**Comment by max397574** [comment]
oh true sorry

**Comment by shadmansaleh** [comment]
In case of buf_set_text it was useful as replacing entire line removed all extmarks from the line .
But for buf_get_text why can't user just grab the entire line and get specific colums from there ? It'll just be a small helper function .
