### ISSUE TITLE
CI: static analysis: analyze with cppcheck

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#15173]
https://github.com/danmar/cppcheck

```
cppcheck --enable=all --force src/nvim
```

**Comment by bfredl** [comment]
A good start could be for someone to run it locally, configure it properly and provide a log with relevant errors :)

**Comment by rktjmp** [comment]
**Run results with "most obvious options"**

Via `cppcheck --enable=all --force --quiet --error-exitcode=1 src/nvim`,

Time: (yes, 21 **minutes**)
```
real	1300.65s
user	1294.36s
sys	2.38s
```
Machine: i5-4670k, 24gb (cppcheck ram usage was v. low though), SSD (disk access also didn't seem like a bottle neck).

Results: [cppcheck.log (208kb) ](https://github.com/neovim/neovim/files/6954411/cppcheck.log)

**About cppcheck options**

where

- `--enable=all` is all checks.
- `--force` is see below.
- `--quiet` is only print errors (successful run should just exit 0 afaict like a good ci tool)
- `--error-exitcode=1` is exit with code 1 if errors detected

List of possible checks, if all was too broad:

```
       --enable=<id>
           Enable additional checks. The available ids are:

           all
               Enable all checks. It is recommended to only use --enable=all when the whole
               program is scanned, because this enables unusedFunction.

           warning
               Enable warning messages

           style
               Enable all coding style checks. All messages with the severities 'style',
               'performance' and 'portability' are enabled.

           performance
               Enable performance messages

           portability
               Enable portability messages

           information
               Enable information messages

           unusedFunction
               Check for unused functions. It is recommend to only enable this when the whole
               program is scanned

           missingInclude
               Warn if there are missing includes. For detailed information use
               --check-config
```

`--force`,

```
       -f, --force
           Force checking of files that have a lot of configurations. Error is printed if
           such a file is found so there is no reason to use this by default. If used
           together with --max-configs=, the last option is the one that is effective.
```

Notable options:

- `--std` for c89 through c11/++11 (default).
- `--xml` can write to xml format if report needed to be munged (probably not, nothing else in CI is AFAIK).
- Has options for job/threading. It pegged one of my cores at 100%, so probably would see improvements with threading but unsure how well that works in a ci env (how many cores, is it stable between runs).
- Also `-D` and `-U`

```
       -D<id>
           By default Cppcheck checks all configurations. Use -D to limit the checking. When
           -D is used the checking is limited to the given configuration. Example: -DDEBUG=1
           -D__cplusplus

       -U<id>
           By default Cppcheck checks all configurations. Use '-U' to explicitly hide certain
           #ifdef <id> code paths from checking. Example: '-UDEBUG'
```

**Comment by rktjmp** [comment]
I would say, a 21 minute run time is unacceptable for CI.

And at 208kb of results (hard to get accurate "error count" since they are line broken), it's probably "non trivial" to get the current build into a passing state.

```
wc -l cppcheck.log
5057 cppcheck.log
```

Probably divide that by 3 or 4 in best case, you still have ~1000 errors to fix.

Probably better taken as a separate project/issues targeting subtrees first before trying to integrate.

**Comment by dundargoc** [comment]
> I would say, a 21 minute run time is unacceptable for CI.

For each pull request, absolutely. But I think if we were to use it then it'd make more sense to run it once per day like [PVS](https://neovim.io/doc/reports/pvs/PVS-studio.html.d/) or [clang analysis](https://neovim.io/doc/reports/clang/). Running clang analyzer also takes a long time, comparable to cppcheck if I had to guess, so I don't think it's outrageous by any measure.

> And at 208kb of results ~(hard to get accurate "error count" since they are line broken)~, actually it's probably 3 lines per error pretty reliably, it's probably "non trivial" to get the current build into a passing state.

Following the above point, if we run it on a schedule and generate a report then it won't become a problem.

I think using `enable=all` or `enable=style` is overkill. I'd guess 90% of the warnings brought up for neovim is that variable scopes can be reduced. Which they should, but it can distract from the real potential issues it finds.

**Comment by jamessan** [comment]
> Running clang analyzer also takes a long time, comparable to cppcheck if I had to guess, so I don't think it's outrageous by any measure.

Just as a data point, generating all the reports](https://github.com/neovim/doc/runs/3277198215?check_suite_focus=true) takes ~17 minutes.  Clang's scan-build is ~10 minutes and PVS is ~5.

**Comment by rktjmp** [comment]
I can look at integrating cppcheck into neovim/doc, but will need guidance on appropriate options (`--enable`, maybe `-U/D` flags).

Btw: http://neovim.github.io/doc/ and http://neovim.io/doc/ both 404.

**Comment by ansimita** [comment]
I'm seeing mostly `variableScope` and `unusedFunction` reports in @rktjmp's log.

---

`variableScope` is a style suggestion i.e., cppcheck is suggesting that

```c
int x;
{
  x = 0;
  printf("%d\n", x);
}
// x no longer used beyond the block above
```

be

```c
{
  int x = 0;
  printf("%d\n", x);
}
```

instead. This is a suggestion that can be ignored imo.

---

P.S. One can create a `suppressions.txt` with the following contents (as an example):

```
unsedFunction
variableScope
```

From the [manual](http://cppcheck.sourceforge.net/manual.pdf) under "Suppressions" > "Suppressions in a file":

```
$ cppcheck --suppressions-list=suppressions.txt src/
```

**Comment by dundargoc** [comment]
I've created a [gist](https://gist.github.com/dundargoc/0557a80a8ba73e770709dd362f4bd536) with most "style" warnings removed such as variable scope warnings and such.

Are these messages useful enough to add to the CI chain?

**Comment by dundargoc** [comment]
Eh, I've tried this. It's decent but nothing spectacular. It also has a *lot* of false positives which is always annoying. Closing for now, can reopen if it improved later on.
