### ISSUE TITLE
Built-in LSP server doesn't honor `executeCommandProvider` server capability

### ISSUE THREAD

**Issue by matklad** [neovim/neovim#15183]
Meta: this might be a bit of a chinese whispers game, as I don't myself use neovim and try to piece together several comments from several issues, please bear with me and correct any misconceptions you notice!

According to [this comment](https://github.com/rust-analyzer/rust-analyzer/issues/1232#issuecomment-886175129), when using neovim LSP client with rust-analyzer, the client sometimes sends `workspace/executeCommand` to the server. However, rust-analyzer [says that it doesn't support](https://github.com/rust-analyzer/rust-analyzer/blob/2fe586a8a781f22f4e5a82037ed459fe28e87f8f/crates/rust-analyzer/src/caps.rs#L69) this command in its capabilities. So neovim behavior seems wrong here: it shouldn't be invoking something ra explicitly says it can't do. 

Background: this has to do with [code lens request](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_codeLens). 

The server returns a [CodeLens](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#codeLens) structure as a response, which contains [commands](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#command).

The docs for it say:

>Commands are identified by a string identifier. The recommended way to handle commands is to implement their execution on the server side if the client and server provides the corresponding capabilities. Alternatively the tool extension code could handle the command. The protocol currently doesn’t specify a set of well-known commands.

rust-analyzer doesn't provide the capability, and relies on the client to handle commands. In particular, we use code lens to implement "run this test and display results" command, and that simply can't be implemented server-side, the entirety of the command is about showing a particular UI to the user. 

Now, obviously neovim shouldn't build in support for the rust-analyzer specific commands, and, ideally, the server shouldn't send the commands which are not implemented by the client. However, as far as I know, there isn't a capability we can took at to understand which commands are supported by the client :( So it seems that the best behavior here is to do the filtering on the client side, and just hide unsupported commands. Unlike the server, the client knows what commands are supported by both sides, and can do the filtering correctly. 

The VS Code behavior here isn't ideal either -- it tries to execute command on the client side, and fails with an error that such client-side command doesn't exist:

![image](https://user-images.githubusercontent.com/1711539/126896221-73292b03-756c-4c43-86b8-c092e1390269.png)

While not ideal, that's at least not in the conflict with the protocol. 

Aside: this is not strictly related to the issue, but I want to notices that the "the recommended way to handle commands" recommendation is a wishful thinking and not something that works in practice. There's only one thing you can do from the server side, `workspace/applyEdit`. But if the lens is expressible as an edit, it's better to uses Code Action instead. Additionally, server-initiated edits are problematic, because they don't allow the client to attach the edit to a specific user action that triggered it.

**Comment by mfussenegger** [comment]
To understand this right - the issue with the server receiving the `workspace/executeCommand` request is currently mostly that it is confusing to users because of the error - leading them to believe it is a server issue, instead of a missing client language extension?

Neovim currently also doesn't support client side custom commands, but there is a [PR](https://github.com/neovim/neovim/pull/14115) pending.

Once that's in I would like to extend the code lens implementation to utilize it as well, and then we can also take care of checking the `executeCommandProvider` server capability.

---


> In particular, we use code lens to implement "run this test and display results" command, and that simply can't be implemented server-side, the entirety of the command is about showing a particular UI to the user.


gopls also has a `run test` code lens and they use the `window/showMessage` handlers to show the test results to the user. It is not ideal but maybe something to consider using as a fallback in rust-analyzer?


> However, as far as I know, there isn't a capability we can took at to understand which commands are supported by the client

Other language servers use the `initializationOptions` of the `initialize` request to set custom capabilities that are not pare of the core protocol. Maybe something to consider for rust-analyzer.

**Comment by matklad** [comment]
I think there are two problems here:

* users are confused that the feature doesn't work. The perfect fix here would be to show a message like "this is a non-standard extension, please install rust-tools.nvim to use it". Not sure what's the best practical fix is though.
* server implementers are confused because the client sends request it shouldn't. The fix here is simple -- just honor the capability. 

> It is not ideal but maybe something to consider using as a fallback in rust-analyzer?

:thinking: I guess that could work to some extent, but I am not sure its worth it, for two reasons:

* the output of tests can be rather big (especially if the test fails with backtrace)
* I'd rather let the client manage running the actual process, as the user might want to be able to `ctrl+C` it, or copy stdout, or restart, etc. If we implement process spawning in the server, we'll have to add custom functionality to expose some control over the child process to the user. Seems cleaner if the server just describes which process to spawn, and lets the client figure out this details. 

> use the initializationOptions 

Hey, I think that'd actually work! We already have custom client capabilities, seems we can just add the list of commands supported by the client there.

**Comment by matklad** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/9732 adds experimental client cap for client commands. Note that it doesn't have any immeriate effect -- if the client doesn't set a capability at all (as opposed to setting it to an empty list of commands), then we still emit our custom commands. That is to give time for existing custom clients to start advertising their commands. Some time in the future, we'll stop sending commands unless the client explicitly claims to support them.

cc @simrat39
