### ISSUE TITLE
Trouble installing vim plug wiyh neovim in pop/os

### ISSUE THREAD

**Issue by jackbenemble** [neovim/neovim#15186]
- `nvim --version`:
- Operating system/version:
- Terminal name/version:
- `$TERM`:

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

**Comment by jackbenemble** [comment]
Christian, I used your tutorial to install plug vim for neovim on my pop os
distro, The three demo plus in the sample plugins.vim install. When
attempting to install
any additional plugins , I get a " not a editor Command " after invoking
:PlugInstall. Any suggestions will be accepted!
                       Jack

**Comment by clason** [comment]
Sorry, that is still not clear at all. What exactly is "my/our tutorial"? Please open a new issue and make sure to take the time to fill out the template completely.

But I suspect that this is not a bug at all but just a usage question; these don't belong on the issue tracker but should be asked either on [Gitter](https://gitter.im/neovim/neovim) or the [Discourse](https://discourse.julialang.org).

**Comment by jackbenemble** [comment]
I don't think it's a bug ,I have plug working well in MXlinux, but I don't
know why it isn't functioning in pop os?

I had Spacevim installed in pop os then removed it . Now I am unable to
install plug ! Are you able to give me any assistance ?

**Comment by clason** [comment]
Not here, sorry. I gave you two places where you can ask such questions and get assistance.

**Comment by jackbenemble** [comment]
Ok, I'll check it out.
