### ISSUE TITLE
Porting Vim's blob handling

### ISSUE THREAD

**Issue by VVKot** [neovim/neovim#15192]
### Feature already in Vim?

Yes

### Feature description

Do we need to port https://github.com/vim/vim/commit/6e5ea8d2a995b32bbc5972edc4f827b959f2702f? If so - in which capacity, e.g. it makes Vim's channel implementation handle - do we need that too? There is a bunch of PRs related to blobs, so we need to either mark them N/A or port them to minimise conflicts.

**Comment by VVKot** [comment]
@janlazo @bfredl @justinmk

**Comment by bfredl** [comment]
Lua strings are already "blobs" and can be used with luv.

**Comment by VVKot** [comment]
@bfredl I guess the question is more of "do we want to support that at Vimscript level for compatibility"?

**Comment by bfredl** [comment]
Well, are there any noteworthy plugins using it outside the context of vim channels?

**Comment by VVKot** [comment]
I don't think so, https://github.com/search?l=Vim+script&p=5&q=0z&type=Code (sorry other hosting providers) only returns checked in copies of Vim.

If we decide *not* to port it - we ignore all the changes from corresponding PRs even to common files (e.g. `eval.c`) and reconcile subsequent changes given resulting differences?

**Comment by seandewar** [comment]
Fyi I ported a few of these patches [to my fork](https://github.com/seandewar/neovim/commits/vim-8.1.0735) a while ago but got caught up with other stuff and forgot about them.

I can try to continue porting them if there's demand for having these patches, but I'm happy if somebody else wants to take over. :smile:

**Comment by VVKot** [comment]
@seandewar yep, I saw you started it on your fork but wasn't sure what was the end decision. If you can PR that - it would be lovely - but let's get a response from @bfredl first.

**Comment by janlazo** [comment]
Yes, blob feature should be ported without touching Vim's code on channels, jobs, etc. for further Vimscript compatibility. It's a lot of work but it is useful for porting Vim's tests that use blobs.

**Comment by VVKot** [comment]
Makes sense, thanks for confirming! @seandewar - let me know if you can look into that!

**Comment by seandewar** [comment]
Awesome! I think I'll have a go at re-basing the patches once I have time. 👍

**Comment by janlazo** [comment]
Closing because of partial support for blob feature in vimscript, shada, lua, JSON, binary strings, etc. Full support requires porting vim 8.2+ patches, listed in https://github.com/neovim/neovim/pull/15211#issuecomment-921165666, and blob implementation in the language provider (ie. python,ruby,nodejs,perl,golang).
