### ISSUE TITLE
Ignore some filetypes in ShaDa

### ISSUE THREAD

**Issue by roflolilolmao** [neovim/neovim#15195]
### Feature already in Vim?

I have no idea

### Feature description

Hello,

I am using vim-fugitive and vim's help a lot in my daily workflow. My problem is that I also use the file history a lot and it is cluttered by entries of filetype `fugitive` (`.git/index`) and `help` (sometimes also `gitcommit`).  The ShaDa `r` options is close to what I need but it seems to only ignore files starting with some prefix instead of filtering by filetype.

I have tried finding a solution to keep my `oldfiles` clean but I couldn't find any reference to this on the web and I have been unable to write a hack that would preserve the correct behavior for other filetypes.

How can I filter the ShaDa entries by filetype? If it is not currently possible, could neovim itself include support for it?

Thank you!

**Comment by glacambre** [comment]
Slightly related: https://github.com/neovim/neovim/issues/12298

**Comment by justinmk** [comment]
> How can I filter the ShaDa entries by filetype?

There is a `:filter` command that works with various commands:

    :filter! /fugitive/ oldfiles
