### ISSUE TITLE
Weird lsp diagnostic behaviour in large project

### ISSUE THREAD

**Issue by itmecho** [neovim/neovim#15198]
### Neovim Version

```
NVIM v0.6.0-dev+30-g191d3e6af
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/iain/src/neovim/build/config -I/home/iain/src/neovim/src -I/home/iain/src/neovim/.deps/usr/include -I/usr/include -I/home/iain/src/neovim/build/src/nvim/auto -I/home/iain/src/neovim/build/include
Compiled by iain@orion

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/iain/.local/share/nvim"

Run :checkhealth for more info
```

### Operating system/version:

arch linux: `Linux orion 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux`

### Terminal name/version:

`alacritty 0.8.0 (a1b13e68)`

### TERM environment variable

`xterm-256color`

### Installation

build from repo

### Steps to reproduce

Not entirely sure on the steps to reproduce as it only happens in the large mono repo I have to use for my job. I see this issue pretty much whenever I'm typing.

If I create a new project outside of the repo, or work on an existing smaller project, I don't see this issue at all.

### 

- [ ] Please check the box if it's possible to reproduce the bug with `nvim --clean` as well

### Vim

Can't test as it relates to LSP

### Expected behavior

The diagnostic should only show the latest result and it should affect performance of other LSP related functions like completion.

### Actual behavior

It seems to really slowly redraw the virtualtext for every character I type. For this recording, I have added the following config:
```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] =
    vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics,
    {
        update_in_insert = true
    }
)
```

If I don't add this, this whole thing happens when I exit insert mode. Without this config, I feel like it shouldn't care about the individual characters while typing and only send the whole string for diagnostics.

https://user-images.githubusercontent.com/8384983/127006306-f3e5922c-04f7-4a64-8033-04b2596a762c.mp4

This gets slower and slower the longer the text gets

**Comment by itmecho** [comment]
Here's the same thing but without the overridden handler. I basically see the same behaviour as before but only when I exit insert mode. Not sure why it seems to pass each individual change through for diagnostics instead of the text at the time of exiting insert mode?


https://user-images.githubusercontent.com/8384983/127008707-eaa13db1-0369-4eff-8288-54c07a3825e6.mp4

**Comment by mfussenegger** [comment]
Which language server(s) are you using?

It could be that the server isn't fast enough, and the diagnostics pile up and are then processed after the fact.

You could try setting `flags.debounce_text_changes = 150` or some higher value within the LSP configuration.

**Comment by mjlbach** [comment]
> Not sure why it seems to pass each individual change through for diagnostics instead of the text at the time of exiting insert mode

The changes used for synchronizing diagnostics are the same changes used for every functionality of the server. We do not request diagnostics, the servers sends us to them when they are ready. You're seeing lag because you're using an autocompletion plugin which is sending multiple requests to the server for completion results. You didn't mention which language server, but if it's theia (typescripts), it currently overeports completion candidates which massively slows down processing the language server response.

1. Add the flag mfussenegger suggested
2. Try disabling autocompletion

**Comment by itmecho** [comment]
@mfussenegger This is `gopls`. Wow, didn't know about that setting! That's made it soooo much better, thank you!

@mjlbach Well that makes a lot more sense. Thanks for filling that knowledge gap =] Adding the flag has sorted it,  completion is working instantly and the diagnostics are perfect!

Thanks for your speedy help guys!

**Comment by itmecho** [comment]
For anyone else with the same issue, this is the exact config I added to the gopls setup function:
```
nvim_lsp.gopls.setup {
    flags = {
        debounce_text_changes = 300
    }
}
```

I'm also using `nvim-compe` with `throttle_time = 300`
