### ISSUE TITLE
Missing highlights for colorschemes that rely on default highlights

### ISSUE THREAD

**Issue by rafikdraoui** [neovim/neovim#15205]
### Neovim Version

NVIM v0.6.0-dev+81-gc642f3ac2

### Operating system/version:

Arch Linux x86_64, Mac OS 10.15.7

### Terminal name/version:

kitty 0.22.0

### TERM environment variable

xterm-kitty

### Installation

Built from source, with `CMAKE_BUILD_TYPE = RelWithDebInfo`

### Steps to reproduce

minrc.vim:
```
colorscheme desert
```

main.go:
```
package main

import "fmt"

func main() {
	fmt.Println("hello world")
}
```

Then `$ nvim --clean -u minrc.vim main.go`.

### Expected behavior

The string `"hello world"` gets highlighted

`:verbose hi String` shows:

```
String         xxx links to Constant
        Last set from ~/code/neovim/runtime/syntax/syncolor.vim line 63
```

`:verbose hi Function` shows:

```
Function       xxx links to Identifier
        Last set from ~/code/neovim/runtime/syntax/syncolor.vim line 68
```

### Actual behavior

The string `"hello world"` isn't highlighted

`:verbose hi String` shows

```
String  xxx cleared
```

`:verbose hi Function` shows

```
E411: highlight group not found: Function
```
---

Manually calling `:colorscheme desert` or `:set bg<` will set the missing highlights.

Another way to reproduce:

```
$ nvim -u NONE main.go

:colorscheme desert
:syntax on
```

But doing `:syntax on` before `:colorscheme desert` will work.

---

This is a regression introduced in #14771

**Comment by clason** [comment]
Can you test _without_ `--clean` (which skips _all_ runtime files, in particular all syntax scripts, so this is hardly unexpected behavior)?

**Comment by bfredl** [comment]
Maybe we should just internalize the definitions already.

**Comment by rafikdraoui** [comment]
With `nvim -u minrc.vim main.go`, things look a bit different because tree-sitter highlighting kicks in for me (only `Println` ends up being highlighted), but the symptoms are similar. The `String` and `Function` highlights are cleared.

The `scriptnames` sequence goes like:

```
init.vim
colorscheme
...
syntax/syntax.vim
syntax/synload.vim
...
```

`syntax/syncolor.vim` appears only after manually calling `:colo` or `:set bg`.

**Comment by clason** [comment]
Yes, but tree-sitter disables built-in syntax highlighting. Please test with a clean (plugin) config otherwise.

**Comment by clason** [comment]
But I can reproduce that; `syncolor` is not loaded in the startup sequence at all.

**Comment by clason** [comment]
However, I don't see a difference with my color scheme; `desert.vim` is apparently just a bad one (mixing up `guifg` and `ctermfg`, for one...)

**Comment by bfredl** [comment]
```
if (params.use_vimrc == NULL || !strequal(params.use_vimrc, "NONE")) {
    // Source syncolor.vim to set up default UI highlights if the user didn't
    // already enable a colorscheme
    if (!get_var_value("g:colors_name")) {
      source_runtime((char_u *)"syntax/syncolor.vim", DIP_ALL);
    }
```

This check is wrong as colorschemes might not load syncolor (not all do `syn en`)

**Comment by rafikdraoui** [comment]
I use a color scheme where only the "preferred highlight groups" from `:help group-name` are defined (e.g. `Constant`, `Identifier`, `Statement`, etc.), and other "minor highlight groups" rely on the default linking to the corresponding preferred group.

**Comment by gpanders** [comment]
> ```
> if (params.use_vimrc == NULL || !strequal(params.use_vimrc, "NONE")) {
>     // Source syncolor.vim to set up default UI highlights if the user didn't
>     // already enable a colorscheme
>     if (!get_var_value("g:colors_name")) {
>       source_runtime((char_u *)"syntax/syncolor.vim", DIP_ALL);
>     }
> ```
> 
> This check is wrong as colorschemes might not load syncolor (not all do `syn en`)

Yes I suppose it is. I made the (apparently incorrect) assumption that colorscheme files would be responsible for defining all of the highlights, so sourcing syncolors.vim after a colorscheme was already loaded would only override already set highlights. 

>I use a color scheme where only the "preferred highlight groups" from :help group-name are defined (e.g. Constant, Identifier, Statement, etc.), and other "minor highlight groups" rely on the default linking to the corresponding preferred group.

*A* solution would be to move the `exists('g:colors_name')` guard around [lines 35-57 in `syncolor.vim`](https://github.com/neovim/neovim/blob/master/runtime/syntax/syncolor.vim#L35-L57) but let the rest of it still be sourced. This would create those default links in every case. Though this strikes me as just further hackiness...

>Maybe we should just internalize the definitions already.

I am all for this. Let's knock out this highlighting headache once and for all.

**Comment by rafikdraoui** [comment]
Fixed by https://github.com/neovim/neovim/pull/15207. Thanks everyone!
