### ISSUE TITLE
Bug: listchars with certain Unicode for tab gives an error

### ISSUE THREAD

**Issue by danielyli** [neovim/neovim#15201]
### Neovim Version

v0.5.0

### Operating system/version:

macOs 11.4

### Terminal name/version:

iTerm 3.4.8

### TERM environment variable

xterm-256color

### Installation

homebrew

### Steps to reproduce

Enter nvim via either `nvim -u NORC` or `nvim -u NONE`. Then execute:

```
:set listchars=tab:◀︎━▶︎
```

The error message that shows is:

```
E474: Invalid argument: listchars=tab:◀︎━▶︎
```

Notably, the same command works as expected in `vim -u DEFAULTS`.

### Vim

VIM - Vi IMproved 8.2, macOS version - x86_64, Included patches: 1-3150

### Expected behavior

Tabs should be listed as `◀︎━━━━━━▶︎`

### Actual behavior

nvim gives `E474`

vim behaves correctly

**Comment by jdhao** [comment]
@danielyli  It seems that your tab option actually contains five chars, there are two variation selections (`U+FE0E`) not visible, but they are there.

I tried to remove the two `U+FE0E`, then the tab setting works.

```
set list listchars=tab:◀━▶
```

**Comment by danielyli** [comment]
Brilliant! Thank you.

This fixes my immediate problem. However, there’s a case to be made that the expected behavior of the original, five-char version is to work, since visually the width of the characters is 3. I’ll defer to the maintainers to decide if they want to support multiwidth Unicode here.

**Comment by clason** [comment]
We do, but multiwidth is _hard_...

Assume single-byte unicode to work, but multibyte to be strictly "best effort" (i.e., expect breakage).

**Comment by justinmk** [comment]
confirmed in nvim 0.6 8a9f292991bc

**Comment by zeertzjq** [comment]
I don't think there is a Vim patch for this. This can, in a way, be considered a regression from #8546.

**Comment by fedemengo** [comment]
This is happening to me as well, not limited to `tab` but for all the keys when using bytes string `vim.o.listchars = {tab = "\226\150\184 ", space = "\226\139\133", eol = "\226\134\181"}` which works fine with plain lua

**Comment by zeertzjq** [comment]
Because you are using `vim.o` instead of `vim.opt`.
