### ISSUE TITLE
pastetoggle of backslash-p not working

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#15210]
### Neovim Version

NVIM v0.5.0

### Operating system/version:

Ubuntu 21.04

### Terminal name/version:

Konsole 20.12.3

### TERM environment variable

xterm-256color

### Installation

appimage

### Steps to reproduce

```
$ nvim -u NORC
:set pastetoggle=\\p
```
Then type backslash quickly followed by p.

### Vim

The issue is not present on Vim version 8.2.2434. Using `pastetoggle` of backslash-p works as expected.

### Expected behavior

`paste` setting would be toggled.

### Actual behavior

Text is put from the default register.

**Comment by jdhao** [comment]
`set pastetoggle=\\p` works for me.

+ OS: CentOS 7.4
+ terminal: zoc terminal
+ nvim version: v0.6.0-dev+63-ga8c3d50fa

**Comment by dstein64** [comment]
Thanks for testing @jdhao!

I just tried again on macOS, using Neovim nightly, and I encounter the same issue that I encountered on Ubuntu using Neovim 0.5. After setting `pastetoggle=\\p`, when I enter backslash-p, `paste` is not toggled and Neovim effectively ignores the backslash by `put`ing text (as if I entered `p` alone).

> "Maybe it fails because of your specific settings."

I used `-u NORC` in both cases.

**Comment by jdhao** [comment]
Okay, I have double checked with `nvim -u NORC --onplugin`. With this setting, the pastetoggle indeed does not work. However, if I use my full nvim config, setting pastetoggle to `\\p` works. I think we may need to turn on other options, but i am not sure which one.

Also on the doc of `pastetoggel`:

> No timeout is used, this means that a multi-key 'pastetoggle' can not 
be triggered manually.                                                

IIUIC, it seems to suggest that multi-key pastetoggle does not work if triggered manually?  I am now confused. It did work when I use my full nvim config.

**Comment by jdhao** [comment]
with `nvim -u NORC --noplugin`, `set pastetoggle=\p` works. It seems that no black slash escape is needed in this case.

**Comment by dstein64** [comment]
When I `set pastetoggle=\p`, with only one backslash, the toggle key is set to `p` alone with no initial backslash. I've confirmed this by looking at the output of `set pastetoggle?` and also by pressing `p` alone, which toggles `paste`.

**Comment by jdhao** [comment]
> When I `set pastetoggle=\p`, with only one backslash, the toggle key is set to `p` alone with no initial backslash. I've confirmed this by looking at the output of `set pastetoggle?` and also by pressing `p` alone, which toggles `paste`.

My mistake. Setting `pastetoggle` to `\p` actually set `p` as the toggle character.

**Comment by justinmk** [comment]
pastetoggle will be removed https://github.com/neovim/neovim/pull/10867
