### ISSUE TITLE
Compile fails because of missing syncolor.vim

### ISSUE THREAD

**Issue by rebuilt** [neovim/neovim#15219]
### Neovim Version

❯ nvim -v NVIM v0.6.0-dev+91-gd628e4250 Build type: Release LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/nelson/builds/neovim/build/config -I/home/nelson/builds/neovim/src -I/home/nelson/builds/neovim/.deps/usr/include -I/usr/include -I/home/nelson/builds/neovim/build/src/nvim/auto -I/home/nelson/builds/neovim/build/include Compiled by root@arcane  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"

### Operating system/version:

arch

### Terminal name/version:

alacritty

### TERM environment variable

alacritty

### Installation

Compile

### Steps to reproduce

Compiling commit d628e42 results in this error.

```
CMake Error at runtime/cmake_install.cmake:51366 (file):
  file INSTALL cannot find
  "/home/nelson/builds/neovim/runtime/syntax/syncolor.vim": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:91 (include)
```

Manually placing `syncolor.vim` in that directory allows compiling to complete

### Expected behavior

Able to compile
### Actual behavior
Unable to compile.   Removing syncolor seems to be intentional.  Does it need to be included in the compiler requirements anymore?

_No response_

**Comment by bfredl** [comment]
you need to `rm -rf build` as noted here https://github.com/neovim/neovim/pull/15207#issuecomment-889579991 .

CMake needs to be (potentially) rerun every time a file is added or removed from our sources, this is expected behavior (until someone convinces cmake not to).

**Comment by rebuilt** [comment]
Ok.  Thanks!
