### ISSUE TITLE
echo[m] does not work on BufRead

### ISSUE THREAD

**Issue by maharvey** [neovim/neovim#15223]
### Neovim Version

0.5.0

### Operating system/version:

Manjaro Linux

### Terminal name/version:

xfce4-terminal

### TERM environment variable

xterm-256color

### Installation

pacman -S neovim

### Steps to reproduce

In vimrc,

```
function VimEnterFunc()
  echom "called VimEnter"
endfunction
function BufReadFunc()
  echom "called BufRead"
endfunction
au VimEnter * call VimEnterFunc()
au BufRead * call BufReadFunc()
```

The use nvim to load a file, for example:
```
touch dummy.txt
nvim dummy.txt
```

### Vim

vim 8.2 conforms to the Expected Behavior below

### Expected behavior

Startup messages:
`called VimEnter`
`called BufRead`

Output of :messages
`called VimEnter`
`called BufRead`

### Actual behavior

Startup messages:
`called VimEnter`

Output of :messages
`called VimEnter`

(messages are not displayed for BufRead)

**Comment by seandewar** [comment]
By default, Nvim sets the `F` flag in `shortmess`, which will cause the message to be silenced. See `:h 'shortmess'` for details.

You'll be able to see the message if you put `set shortmess-=F` in your `init.vim`, though I believe the order of the messages might be different from Vim.
