### ISSUE TITLE
`:mksession` disregards the Windows' path separator `\` and always sets `/`

### ISSUE THREAD

**Issue by MIvanchev** [neovim/neovim#15220]
### Neovim Version

NVIM v0.5.0

### Operating system/version:

Windows 7 x64

### Terminal name/version:

nvim-qt

### TERM environment variable

n/a

### Installation

https://github.com/neovim/neovim/releases/download/v0.5.0/nvim-win64.zip

### Steps to reproduce

Start nvim(-qt), open any file which is not in the current directory, execute `:ls`, the buffer's path will use the path separator `\`. Do a `mksession foo.vim`, open the file, the path separator will now be changed to `/`. Reload the session, `:ls` now shows the changed path separator.

### Expected behavior

Consistency because plugins depend on it.

**Comment by MIvanchev** [comment]
OK I just found out this is [being done deliberately](https://github.com/neovim/neovim/blob/master/src/nvim/ex_session.c#L270), but the question is why :))

**Comment by clason** [comment]
Consistency (so plugins _don't_ all have to special-case Windows in this respect) and to significantly simplify code to make maintenance easier.

**Comment by MIvanchev** [comment]
Yes, this makes sense, I was just confused because `foo\bar\ohoh.txt` suddenly becomes `foo/bar/ohoh.txt` after a session so a plugin should be able to handle both I guess. Anyhow, this doesn't seem to be a bug really :)
