### ISSUE TITLE
How to configure snap version

### ISSUE THREAD

**Issue by NightH4nter** [neovim/neovim#15229]
Since the snap version (at least, 0.5) has no plugs, also it has no devmode, and the configs in `~/snap/nvim/current/.config/nvim` are ignored, how should it be configured?

**Comment by vuki656** [comment]
You should ask this in the forums since its technically not an issue: https://neovim.discourse.group/

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/how-to-configure-snap-version-of-neovim/938/1
