### ISSUE TITLE
nvim seperate window with same session

### ISSUE THREAD

**Issue by vzytoi** [neovim/neovim#15230]
### Feature already in Vim?

idk but i don't think so

### Feature description

hello!
i have two monitors for a while and it feels kinda sad that i can't use nvim on both with same yanks, buffers, marks and stuff.
is there today any way i can acheve this?
thanks & have a good day (:

**Comment by mjlbach** [comment]
I feel like this is a dupe, but I can't find the parent issue.

There's work towards this in https://github.com/neovim/neovim/pull/10071

no ETA.

**Comment by vzytoi** [comment]
> I feel like this is a dupe, but I can't find the parent issue.
> 
> There's work towards this in #10071
> 
> no ETA.

C'est super prometteur, avec un peu de chance ça pourrait arriver d'ici 0.6.

**Comment by teto** [comment]
I think @mjlbach was thinking of https://github.com/neovim/neovim/issues/2161, if that's correct ,let's close this as a duplciate.

**Comment by mjlbach** [comment]
I was, thanks @teto :)
