### ISSUE TITLE
set shell=pwsh.exe hangs :checkhealth

### ISSUE THREAD

**Issue by fragrans** [neovim/neovim#15237]
### Neovim Version

NVIM v0.5.0

### Operating system/version:

Windows 10 64-bit 21H2

### Terminal name/version:

powershell 7.1.3

### TERM environment variable

N/A

### Installation

chocolatey

### Steps to reproduce

insert this line into init.vim

```
set shell=pwsh.exe
```
```
:checkhealth
```

### Expected behavior

Pass checkhealth.
```
" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')


" Multiple Plug commands can be written in a single line using | separators
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

Plug 'morhetz/gruvbox'
Plug 'pprovost/vim-ps1'


" Initialize plugin system
call plug#end()

colorscheme gruvbox

set shiftwidth=4
set tabstop=4
set expandtab
set clipboard^=unnamed,unnamedplus

cd g:/dev.azure.com
set shell=pwsh.exe
set number
let g:python3_host_prog="C:/Python39/python.exe"

```

### Actual behavior

Whole UI didn't response any more.
Have to kill it using System Task Manager.

![image](https://user-images.githubusercontent.com/102768/127808834-2685b4e0-ddf8-46a6-a58d-5402dbdb676c.png)

**Comment by comiluv** [comment]
Try adding ```set shellcmdflags=-c``` and :checkhealth again.

**Comment by justinmk** [comment]
`:help shell-powershell`
