### ISSUE TITLE
API to get horizontal scroll position

### ISSUE THREAD

**Issue by lukas-reineke** [neovim/neovim#15247]
### Feature already in Vim?

No

### Feature description

To be able to tell how far a window is scrolled horizontally, it would be nice to have a `nvim_win_get_` API that returns `w_leftcol`.
AFAIK, there is currently no way to get this information.

Might make sense to return it with `w_topline`, to get vertical scroll position in the same API call.

**Comment by vigoux** [comment]
I'm on it fam.

**Comment by romgrk-comparative** [comment]
Got a draft started @vigoux.

**Comment by vigoux** [comment]
Lol me too hehe

**Comment by romgrk** [comment]
Mmm, alright, it's yours. I'm gonna open a PR if you don't have it done soon though.

**Comment by vigoux** [comment]
No but I don't want to block your work, open a PR if you want.

**Comment by romgrk** [comment]
Not urgent and I only had one function written down, you can proceed you're probably ahead.

**Comment by vigoux** [comment]
Could you try the linked PR to see if this is what you had in mind ?

**Comment by romgrk** [comment]
Yes, seems good.

**Comment by romgrk** [comment]
While you're touching that, can you add an API or include in that new function a way to retrieve the gutter width? It will avoid the need to do [ugly stuff](https://github.com/romgrk/nvim-treesitter-context/blob/b15604abc0b4b45f89cfe9c60e065ff86741af0d/lua/treesitter-context.lua#L17).

**Comment by lewis6991** [comment]
> While you're touching that, can you add an API or include in that new function a way to retrieve the gutter width? It will avoid the need to do [ugly stuff](https://github.com/romgrk/nvim-treesitter-context/blob/b15604abc0b4b45f89cfe9c60e065ff86741af0d/lua/treesitter-context.lua#L17).

Already discussed this in the PR. Also https://github.com/neovim/neovim/pull/14392

**Comment by justinmk** [comment]
Related: UI clients like https://github.com/vscode-neovim/vscode-neovim want to _set_ the Nvim viewport / scroll position:

- https://github.com/neovim/neovim/issues/11370
- https://github.com/neovim/neovim/issues/16166

**Comment by glepnir** [comment]
@lukas-reineke now can use `vim.fn.getwininfo(winid)` to get `leftcol` for a window

**Comment by lukas-reineke** [comment]
👍 thanks
