### ISSUE TITLE
No neovim module found for Python 2.7.6

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#1524]
Thanks to the recently integrated clipboard functionality (kudos @tarruda!), I've finally been able to switch to nvim for all tasks that I used to fall back to vim to. Which is great. I still don't feel like loading python though. That's why it bothers me a bit that I have to press enter on every startup:

```bash
➜  ~  nvim
No neovim module found for Python 2.7.6
Press ENTER or type command to continue
```

I suppose this is intentional, but could it be made optional or relegated to `.nvimlog`? The information is handy, I must admit, but still it slows me down even for a tiny fraction and makes me not think of the text I want to edit when I do `nvim <file>`.

**Comment by jtheoof** [comment]
I'm also experiencing this issue. I just installed neovim to try it out. I symlinked my `.vimrc` and `.vim` to `.nvimrc` and `.nvim` respectively. Hoping things would work as is but it is not the case. This is the only issue I'm having so far.

**Comment by justinmk** [comment]
@jtheoof Did you `pip install --upgrade neovim`? See http://neovim.org/doc/user/nvim_python.html

**Comment by jtheoof** [comment]
Thanks it worked. 

—

**Comment by blueyed** [comment]
AFAIC there are currently no errors being displayed when the loading of a Python host fails (via `has('python3')`).

Only if you call `:py` / `:py3` then nonetheless there will be an error (`E117: Unknown function: provider#python#Call`).

**Comment by fwalch** [comment]
@blueyed You mean that `has('python3')` returns 1 even if is not installed?

**Comment by Pyrohh** [comment]
I think he means that nvim doesn't complain when there is no python host (assuming no plugins complain). Before, nvim complained unconditionally (I believe it was @Shougo's Python 3 PR that fixed this).

**Comment by fwalch** [comment]
Right.. that means this issue could be closed?
