### ISSUE TITLE
vim.lsp.buf.hover shows blank line between horizontal lines

### ISSUE THREAD

**Issue by datwaft** [neovim/neovim#15246]
### Neovim Version

NVIM v0.6.0-dev+105-g8baf7bce2

### Operating system/version:

Ubuntu 20.04 LTS inside the WSL 2/Windows 10

### Terminal name/version:

Windows Terminal 1.9.1942.0

### TERM environment variable

tmux-256color

### Installation

homebrew

### Steps to reproduce

**Note:** the LSP configuration was extracted from `lspconfig` example configuration.

1. Install _lua-language-server_ inside `~/.local/bin/lua-language-server`
2. Execute Neovim with a _init.lua_ file such as this:
```lua
local packer = require("packer")
local use = packer.use
packer.startup(function()
  use "wbthomason/packer.nvim"
  use "neovim/nvim-lspconfig"
end)

local system_name
if vim.fn.has("mac") == 1 then
  system_name = "macOS"
elseif vim.fn.has("unix") == 1 then
  system_name = "Linux"
elseif vim.fn.has('win32') == 1 then
  system_name = "Windows"
end

local root_path = vim.fn.expand("~").."/.local/bin/lua-language-server"
local binary_path = root_path.."/bin/"..system_name.."/lua-language-server"

local runtime_path = vim.split(package.path, ";")
table.insert(runtime_path, "lua/?.lua")
table.insert(runtime_path, "lua/?/init.lua")

local lspconfig = require("lspconfig")
lspconfig.sumneko_lua.setup({
  cmd = { binary_path, "-E", root_path.."/main.lua" },
  settings = {
    Lua = {
      runtime = {
        version = "LuaJIT",
        path = runtime_path,
      },
      diagnostics = {
        globals = { "vim" },
      },
      workspace = {
        library = vim.api.nvim_get_runtime_file("", true),
      },
      telemetry = {
        enable = false,
      },
    },
  },
})
```
3. Open a Lua file such a this one:
```lua
---Bla bla bla Lorem Ipsum bla bla
---@param text string # Something Something print
---@return nil
local function testFunction(text)
	print(text.."!!")
end

testFunction("Hello World")
```
4. Execute `:lua vim.lsp.buf.hover()` while hovering over the `testFunction` symbol.

### Vim

N/A

### Expected behavior

The blank space between the two horizontal lines shouldn't be displayed.

### Actual behavior

As you can see in the image, there is a blank space between the two horizontal lines.

![image](https://user-images.githubusercontent.com/37723586/127939171-1939f52f-0b25-45b3-887c-4d69198e10fa.png)

**Comment by mjlbach** [comment]
I think we're accurately rendering what the server is sending:

Before stylize_markdown
`{ "```lua", "function testFunction(text: string)", "  -> nil", "```", "", "---", "Bla
 bla bla Lorem Ipsum bla bla", "", "@*param* `text` —  Something Something print" } `

after:
`{ "function testFunction(text: string)", "  -> nil", "───────────────────────────────
─────────────", "", "────────────────────────────────────────────", "Bla bla bla Lore
m Ipsum bla bla", "", "@*param* `text` —  Something Something print" } `

The issue is sumneko is sending us an empty line and delineator.

cc @folke

**Comment by folke** [comment]
I'll see for a fix tomorrow. I have a couple of days to work on Neovim, so if there's anything I missed over the last two weeks, let me know! 🙂

**Comment by datwaft** [comment]
Thanks! :D
