### ISSUE TITLE
[DOCS] Wrong link for nvim_buf_add_highlight

### ISSUE THREAD

**Issue by vuki656** [neovim/neovim#15245]
In the docs [here](https://neovim.io/doc/user/api.html), go to `nvim_buf_add_highlight` section and click on `nvim_buf_add_highlight` link in the description. 

It will take you [here](https://neovim.io/doc/user/intro.html#nvim_buf_set_virtual_text()) which has no reference to the virtual text anywhere on the page.

**Comment by bfredl** [comment]
The docs need an update but it would be nice with an explicit failure for broken tag instead of link to intro.txt

**Comment by gpanders** [comment]
I can't reproduce this, clicking the `nvim_buf_add_highlight` link takes me to `nvim_buf_add_highlight`.

**Comment by bfredl** [comment]
Yes, nvim_buf_set_virtual_text was recently deprecated. Not sure if we want a separate api-deprecated section or something.

**Comment by vuki656** [comment]
> I can't reproduce this, clicking the `nvim_buf_add_highlight` link takes me to `nvim_buf_add_highlight`.
> 
> **EDIT:** The `nvim_buf_set_virtual_text` link is broken though, is that what you meant?

Pasted the wrong thing, by bad

**Comment by vuki656** [comment]
> Yes, nvim_buf_set_virtual_text was recently deprecated. Not sure if we want a separate api-deprecated section or something.

What was it replaced with?

**Comment by gpanders** [comment]
> What was it replaced with?

`nvim_buf_set_extmark` already covers this functionality. See the PR linked above to see what replacing `nvim_buf_set_virtual_text` with `nvim_buf_set_extmark` looks like.
