### ISSUE TITLE
Can we map <C-c> to do something and also send an unmapped <C-c> that can interrupt system() ?

### ISSUE THREAD

**Issue by mckellygit** [neovim/neovim#15258]
### Feature already in Vim?

Yes, this seems to work properly in vim 8.2

### Feature description

Hi,
Thank you all for neovim.
Without a \<C-c\> mapping, \<C-c\> works fine for me to stop a system() command.
But is there a way to map \<C-c\> to do something and also issue an unmapped \<C-c\> - which will interrupt a system() cmd ?
This seems to work ok in vim, but just not in neovim.
I have tried using nvim_input(), feedkeys() and nvim_feedkeys() - but I think the issue is that once \<C-c\> is mapped it no longer is seen asyncronously while a system() cmd is running ???
thx,
-m

**Comment by bfredl** [comment]
Sounds like a bug to me, when `system()` is running neovim is not in a mappable mode, so `<c-c>` should not be remapped to something else anyway. Probably missing a state flag around the system() inner event loop.

**Comment by mckellygit** [comment]
Just an fyi, there is a very old but perhaps similar issue ?
https://github.com/neovim/neovim/issues/1234

**Comment by mckellygit** [comment]
```
static void process_interrupts(void)
{
  if ((mapped_ctrl_c | curbuf->b_mapped_ctrl_c) & get_real_state()) {
    return;
  }
```
Not sure yet if this is where we get

**Comment by justinmk** [comment]
> perhaps similar issue ? #1234
> But quite a way into the issue is the part about remapping <C-c> and have it still interrupt system() cmds

related but different. 

7cd204dbfa9b was a partial attempt to fix this.

**Comment by mckellygit** [comment]
@zeertzjq awesome, ty so much!
