### ISSUE TITLE
charidx fails at the last character of the line

### ISSUE THREAD

**Issue by ragnarov** [neovim/neovim#15254]
### Neovim Version

NVIM v0.5.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version:

Arch Linux 5.10.55-1-lts x86_64

### Terminal name/version:

rxvt-unicode (urxvt) v9.26 - released: 2021-05-14 (From pacman Arch Linux)

### TERM environment variable

rxvt-unicode-256color

### Installation

appimage (https://github.com/neovim/neovim/releases/download/v0.5.0/nvim.appimage)

### Steps to reproduce

`		let l:cc = charidx(getline('.'), col('.'))`
Note the cursor position.
Go to command-line mode.
type:
`:echo charidx(getline('.'), col('.'))`
Should give -1 as shown in the image below.
![image](https://user-images.githubusercontent.com/35137670/128041612-842cf523-a26d-4a14-a371-8da0313fbfcc.png)
However if I type:
`:echo col('.')`
I get 44. See the image below.
![image](https://user-images.githubusercontent.com/35137670/128042452-1ebdcc9f-ad80-4eca-ba95-c4d36f4e77bb.png)

I think I should get 44 here. But charidx don't give 44. :(

### Vim

Vim behaves same as nvim but that doesn't mean it is the right behavior.

### Expected behavior

I expect to get 44 not -1

### Actual behavior

Gives -1

### Edit
For some reason after pasting the text from 'Steps to reproduce' gives 43 using col('.')
So I made a small gist, you may copy the text from here.
I don't think this is necessary, still to reproduce the problem one may want it.
https://gist.github.com/ragnarov/c15ab616e4ba48d1d1a884f270552451

**Comment by vigoux** [comment]
This will need to be opened upstream, and the fix will need to be ported over there then.

**Comment by hrsh7th** [comment]
The charidx seems to expect 0-origin index.

So you should do `echomsg charidx(getline('.'), col('.') - 1)`, I think.
