### ISSUE TITLE
spell check depends on filetype

### ISSUE THREAD

**Issue by tkkcc** [neovim/neovim#15263]
### Neovim Version

v0.5.0

### Operating system/version:

archlinux

### Terminal name/version:

urxvt/9.26

### TERM environment variable

rxvt-unicode-256color

### Installation

pacman -S neovim

### Steps to reproduce

```sh
cat > a << EOF
# func
func

function
functionn
# functionn
EOF

# use sh filetype and jump to the second spell error
nvim -u NORC -c 'set spell | set filetype=sh |normal 2]s' a

# use markdown filetype and jump to the second spell error
nvim -u NORC -c 'set spell | set filetype=markdown |normal 2]s' a
```

### Expected behavior

Both cursors are on the second line `func`.

Spell check is enabled for all contents, not just comments, otherwise we can not find typo in function and vairable name. 

### Actual behavior

The first command's cursor is on the last line `# functionn`.
The second command works as expected.

**Comment by matveyt** [comment]
This is not a bug but a feature. Make sure you've read `:h spell-syntax` and other relevant help topics first.

If you really believe that some specific filetype should have spell check enabled globally, you'd better contact maintainer of that filetype first. If no success then open PR and/or issue for Vim.

**Comment by tkkcc** [comment]
Thanks!
