### ISSUE TITLE
can not use lua command after bar in vim script: E5107: Error loading lua [string ":lua"]:1: unexpected symbol near '|'

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#15271]
### Neovim Version

v0.6.0-dev+98-ga5c25e4f3

### Operating system/version:

macOS

### Terminal name/version:

kitty

### TERM environment variable

xterm-256color

### Installation

binary release

### Steps to reproduce

1. Use the following config `mini.vim`

```vim
augroup demo
    au!
    au FileType * if &filetype == 'markdown' | lua print("markdown") | endif
augroup END
```

2. Run the following command:

```
nvim -u mini.vim test.md
```

### Vim

N/A

### Expected behavior

I see no error

### Actual behavior

I see the following error:

> E5107: Error loading lua [string ":lua"]:1: unexpected symbol near '|'

**Comment by seandewar** [comment]
It's the bar _after_ the `:lua` command that's triggering the error, not the one before.

The `TRLBAR` flag is not set for the `:lua` command, which allows bars to be used inside the command as part of its argument.

**Comment by gpanders** [comment]
After `:lua`, *everything* is considered Lua, so the `|` is being parsed as Lua which is where the error comes from.

You can do one of the following:

```vim
au FileType * if &filetype == 'markdown' | exec 'lua print("markdown")' | endif
```

or

```vim
au FileType * if &filetype == 'markdown' | call luaeval('print("markdown")') | endif

**Comment by jdhao** [comment]
@seandewar @gpanders Thanks for the explanation. Now it makes sense to me. I find that using v:lua.print() may be a more robust way to use lua inside vim script.
