### ISSUE TITLE
LSP client notification hooks

### ISSUE THREAD

**Issue by rish987** [neovim/neovim#15275]
### Feature description

It would be very convenient to have, similar to `on_init` and `on_exit`, an `on_notify` hook that would be a table mapping from client-to-server notification methods to functions that would be called _immediately after_ the notification is sent. We could also have a "default" key in this table for a function that is called regardless of the particular method.

VSCode has the (seemingly undocumented) `middleware` option which does this -- see, for example, [how it is used in the Lean 4 VSCode extension to trigger on `textDocument/didChange`](https://github.com/leanprover-community/vscode-lean4/blob/d5f1926be34e73af23d551be779a5b98e721e0ba/vscode-lean4/src/leanclient.ts#L122), which is what we'll be trying to replicate at Julian/lean.nvim#84.

**Comment by justinmk** [comment]
from https://github.com/neovim/neovim/pull/15276

> So, I've realized that we've gotten around the issue at [Julian/lean.nvim#113](https://github.com/Julian/lean.nvim/pull/113) on our side with [Julian/lean.nvim#114](https://github.com/Julian/lean.nvim/pull/114), at least when not debouncing, which allows us to use `on_lines`, so I'll close this for now. But if someone else comes up with the need for this feel free to revive it.

**Comment by glepnir** [comment]
now there has `LspNotify` event.
