### ISSUE TITLE
ftdetect files are sourced twice

### ISSUE THREAD

**Issue by gpanders** [neovim/neovim#15272]
### Neovim Version

0.5.0

### Operating system/version:

N/A

### Terminal name/version:

N/A

### TERM environment variable

N/A

### Installation

Any

### Steps to reproduce

Run `nvim` with `--startuptime` and see that `ftdetect` files from packages are sourced twice.

### Vim

Yes

### Expected behavior

ftdetect files are sourced once.

### Actual behavior

ftdetect files are sourced twice.

[`filetype.vim` is sourced on startup](https://github.com/neovim/neovim/blob/master/src/nvim/ex_docmd.c#L9290), which in turn runs:

```vim
runtime! ftdetect/*.vim
runtime! ftdetect/*.lua
```

This happens *before* `load_plugins()` is called, and therefore before any packages are on `'runtimepath'`. However, in [`source_runtime`](https://github.com/neovim/neovim/blob/master/src/nvim/runtime.c#L238) the flags are modified to also search in `start` directories, so even though packages haven't been set up yet, the ftdetect files in the packages are sourced.

Later, when packages are setup and loaded, the [ftdetect files are sourced again](https://github.com/neovim/neovim/blob/master/src/nvim/runtime.c#L424-L431).

The culprit seems to be this modification to `source_runtime`:

```c
flags |= (flags & DIP_NORTP) ? 0 : DIP_START
```

which was made in c60c7375f5 back in Oct 2020. Presumably this change was added for a good reason, though I'm not sure what it is, so just ripping it out might break something (@bfredl).

**Comment by wbthomason** [comment]
If I recall correctly, c60c737 was added (at least in part) to allow using autoload functions and Lua modules provided in `start` plugins using the native packages feature to be used in `init.lua` (though I could be thinking of a different commit). Personally, I would not like that commit to be ripped out. Perhaps a simpler solution is to not include the `runtime! ftdetect...` lines in `filetype.vim`? I wouldn't be too surprised if doing so broke something else, though.

**Comment by gpanders** [comment]
Packages do not load until after `init.vim`/`init.lua`. That is part of the contract as specified in the documentation. If a user wants to use something from a start package inside of their `init.vim`/`init.lua` then the `:packloadall` command is available, or they can make it an opt package and use `:packload {plugin}`.

Right now the `:runtime` command does not behave as advertised:

```
:ru[ntime][!] [where] {file} ..
			Source vim/lua {file} in each directory given by
			'runtimepath' and/or 'packpath'. The vim files are
			executed in same mannar as |:source| and lua files
			similarly as |:luafile|. There is no error
			for non-existing files.

                        ...

			When [where] is omitted only 'runtimepath' is used.
			Other values:
				START	search under "start" in 'packpath'
				OPT 	search under "opt" in 'packpath'
				PACK	search under "start" and "opt" in
					'packpath'
				ALL	first use 'runtimepath', then search
					under "start" and "opt" in 'packpath'
```

That last paragraph is wrong: the current behavior is that when `[where]` is omitted both `runtimepath` is used *and* we search under "start" in 'packpath'.

IMO this is a bug, one with at least one adverse affect (the one in this issue) but perhaps others. I do not think changing the behavior of `:runtime` to also change the behavior of native packages is the right thing to do and I propose we revert that line in `source_runtime` I mentioned above. I'll open a PR with this change and we can discuss it there.

> Perhaps a simpler solution is to not include the runtime! ftdetect... lines in filetype.vim

`filetype.vim` has sourced the `ftdetect` files for a very long time. This is also how Vim does it. This is just a symptom of a larger problem (`:runtime` not behaving as advertised), so I don't think this is the right approach.

**Comment by bfredl** [comment]
Reverting c60c737 will not happen. Packages in neovim will work like rtp plugins have worked for 30 years because that is how every single neovim users uses them. No one uses them the way Bram intended them so breakage with brampackages is intentional whenever it serves our users (and plugin writers for every single plugin written before 2017).

Rather we should fix all the cases that that commit _omitted_ so that rtp can be fully deduplicated for start packages.

**Comment by gpanders** [comment]
In light of that then I'm reconsidering @wbthomason's comment:

> Perhaps a simpler solution is to not include the runtime! ftdetect... lines in filetype.vim

I think we have two options: 1) remove the `runtime! ftdetect` lines from filetype.vim or 2) tweak the package loading logic so that ftdetect files are only sourced for opt packages.

(1) is simpler but introduces an inconsistency with upstream runtime files. (2) preserves the runtime files but with (slightly) more complexity. Any opinions either way?

FWIW I have a patch ready to go for option (2).
