### ISSUE TITLE
nvim_open_win with non-current buffer leads to wrong working directory with 'autochdir'

### ISSUE THREAD

**Issue by gelguy** [neovim/neovim#15280]
### Neovim Version

NVIM v0.5.0-dev+1115-gc1fbc2ddf

### Operating system/version:

WSL Ubuntu

### Terminal name/version:

mintty 3.4.5

### TERM environment variable

xterm-256color

### Installation

Built from source

### Steps to reproduce

vimrc:
```vim
set autochdir

autocmd CmdlineLeave * call Leave()

let s:buf = nvim_create_buf(0, 1)
call nvim_buf_set_name(s:buf, 'Foo')

function! Leave()
  let l:win = nvim_open_win(s:buf, 0, {
        \ 'relative': 'editor',
        \ 'height': 1,
        \ 'width': 1,
        \ 'row': 0,
        \ 'col': 0,
        \ })
  call nvim_win_close(l:win, 1)
endfunction
```

1. Open nvim: `nvim -u vimrc`.
2. Edit a file in a different directory: `:e ~/foo/bar.txt`
3. Check pwd: `pwd`

### Vim

No, Vim doesn't have floating windows

### Expected behavior

`pwd` should show `~/foo`.

### Actual behavior

`pwd` shows `~`.

**Comment by zeertzjq** [comment]
This seems to be a problem of `nvim_open_win()`: `'autochdir'` is triggered even if the window isn't entered.

**Comment by zeertzjq** [comment]
This seems to be a problem of `nvim_buf_set_name`: `'autochdir'` is triggered even if the buffer isn't focused.

**Comment by zeertzjq** [comment]
Vim has a similar problem in autocommands triggered for non-current buffer. I've opened <https://github.com/vim/vim/issues/9276>.

**Comment by zeertzjq** [comment]
Workaround: change the second parameter of `nvim_open_win()` from `0` to `1`.

**Comment by NoahTheDuke** [comment]
Looking through the code a little, seems like the cause might be `buffer/nvim_buf_set_name` calling `ex_cmds/rename_buffer` calling `buffer/do_autochdir` calling `file_search/vim_chdirfile` calling `fs/os/os_chdir`.

Would it be possible to save or store the current working directory in `nvim_buf_set_name`, call `rename_buffer` like normal, and then restore the saved cwd?

**Comment by NoahTheDuke** [comment]
I played around with it a little and `nvim_buf_set_name` is not the source of the issue, as far as I can tell, but I couldn't figure out much more than that.

**Comment by zeertzjq** [comment]
Oh, this is actually a problem with `nvim_open_win`.

**Comment by glepnir** [comment]
because win_set_buf make it to current and do_auchdir .. i think i know how to fix ..
