### ISSUE TITLE
Neovim "lags" when inserting new lines in a "large" (400+ lines) python file.

### ISSUE THREAD

**Issue by Mulling** [neovim/neovim#15299]
### Neovim Version

NVIM v0.5.0

### Operating system/version:

OS: Manjaro Linux x86_64 Kernel: 5.10.53-1-MANJARO

### Terminal name/version:

st 0.8.4

### TERM environment variable

st-256color

### Installation

system package manager

### Steps to reproduce

Open vim, move to the middle of the file, hold/press the enter key (in insert mode).

I've attached a profile log.

[prof.log](https://github.com/neovim/neovim/files/6948629/prof.log)

The problem IS NOT present when using `vim -u NONE` (syntax on/off does not matter).

The problem IS present when using `vim -u NORC`.

This appears to be the same problem as #5055.

### Expected behavior

New lines should be inserted without the editor freezing/lagging.

### Actual behavior

Editor freezes/hangs/lags when inserting new lines on a 400+ lines python file. But it only happens in certain parts of the file. Inserting lines at the beginning of the file works fine and does not seem to cause any problem.

**Comment by vigoux** [comment]
Could you paste your init.vim here?
The fact that `-u NORC` matters indicates that it may be a plugin causing this.

**Comment by Mulling** [comment]
Sorry for the late reply.

I don't think its related to my init.vim, i don't even use any external plugin.

I managed to fix de issue by setting `:set g:pyindent_disable_parentheses_indenting=1`. The problem comes from `GetPythonIndent` in `nvim/runtime/indent/python.vim`. See the profile log that I've attached and #5055. The way that indentation inside and around parenthesis is done seems **very** inefficient.

```vim
  " Identing inside parentheses can be very slow, regardless of the searchpair()
  " timeout, so let the user disable this feature if he doesn't need it
  let disable_parentheses_indenting = get(g:, "pyindent_disable_parentheses_indenting", 0)
 ```
My init.vim:

```vim
filetype plugin indent on
syntax on

set path+=**

let mapleader=" "

noremap <leader><space> :b#<CR>
noremap <leader>s :setlocal spell!<CR>
noremap <leader>/ :setlocal hlsearch!<CR>

noremap Y y$

tnoremap S-<esc> <c-\><c-n>

command! -nargs=* T :belowright split | resize 10 | term <args>

map <C-j> :cn<CR>
map <C-k> :cp<CR>

let g:loaded_python3_provider = 0
let g:loaded_python_provider  = 0
let g:netrw_banner = 0
let g:pyindent_disable_parentheses_indenting = 1

set autochdir ignorecase incsearch nowrap smartcase smartindent expandtab nohlsearch rnu lazyredraw

set sj=-50 tabstop=4 softtabstop=4 shiftwidth=4 fillchars+=vert:┃ shortmess=aoOtT laststatus=1 showtabline=0 tw=80 clipboard=unnamedplus

aug UsrFiletype
    au!
    au Filetype haskell  setlocal tabstop=2 softtabstop=2 shiftwidth=2
    au Filetype markdown setlocal wrap linebreak
    au Filetype text     setlocal wrap linebreak
    au Filetype c        setlocal complete+=i
    au FIletype c++      setlocal complete+=i
    au FIletype qf       setlocal nonu nornu
aug END

aug UsrBufReadPost
    au!
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
aug END

aug UsrTermOpen
    au!
    au TermOpen * setlocal nonu nornu
aug END

set statusline=\ %F\ %h%m%r\%=%-13.(%l,%c%V%)\ %P\ %<
```

**Comment by vigoux** [comment]
If that's related to python runtime files, I think you should check whether `vim/vim` has that issue or not.
If that's the case, then you should open an issue there, or even try to fix it and send the patch there, then port it here.
If that's not the case, there must be a patch (a runtime update probably), that we are missing, and that need to be ported.

**Comment by chrisbra** [comment]
sounds more like an runtime file problem (either the indent script or the ftplugin). Check if this happens after `:filetype indent off` (which should disable the indent script for python). It's most likely to blame. According to the profile, it is indeed the indent function. A complete profile of that function would be help to further pinpoint the problem.

**Comment by justinmk** [comment]
This is a runtime syntax issue. We pull those files from vim. File the issue there.
