### ISSUE TITLE
VirusTotal reports MaxSecure Virus

### ISSUE THREAD

**Issue by GaryFurash** [neovim/neovim#15290]
Uploading NVIM to virustotal.com reports MaxSecure error. My org wont let me install with a virus report (url)

**Comment by bfredl** [comment]
Is there like a report of what it specifically dislikes?

**Comment by GaryFurash** [comment]
nvim-win32 reports no errors
nvim-win32 reports MaxSecure Trojan.Malware.300983.susgen

**Comment by GaryFurash** [comment]
I was able to download the 32 bit but Symantec also reported a virus I wasn't able to catch.

I assume all these are false positives.

**Comment by rktjmp** [comment]
- [64bit nightly](https://www.virustotal.com/gui/url/48265cc1c00112e12c4b25dba8bae42efbe37f366ce1e7e68a9cddbe673e0bab/detection)
- [32bit nightly](https://www.virustotal.com/gui/url/2a9ec13f36f0781640ab5989e83a1bfa456c8437c2dac24ff74385cd8c545a60/detection)
- [64bit 0.5](https://www.virustotal.com/gui/url/f38e4440699cf698d3579ada7b3102b7df772f1f819d4586857d1f847356de2e/community)
- [32bit 0.5](https://www.virustotal.com/gui/url/ba11cb4d0134e0d84c06826740c35eedf374dd80d051d2ae3e4a2d6d7f68e4c9/detection)

Not sure there is anything actionable here without specific binaries to check against and even then the heuristics are generally blackboxes.

**Comment by rktjmp** [comment]
I guess *sort of* related https://github.com/neovim/neovim/issues/14960. Mentions specific files (not that I think it holds water).

**Comment by dundargoc** [comment]
@GaryFurash could you link the specific virustotal url that failed like @rktjmp did?

I also don't understand how this is a neovim problem and not a virustotal problem. Is there anything neovim _can_ do to fix this?

**Comment by chrisbra** [comment]
There is nothing neovim devs can do, if your AV vendor flags the artifacts. Sometimes, they only flag it, because they haven't seen that specific binary very often (can happen with nightlies and self-build binaries) and just mark as *WS.BadReputation* (which is just a heuristic). That by itself does not mean it contains a virus. Please complain to your AV vendor, they have to fix it.
