### ISSUE TITLE
Is there a lua api function that gives the word under my cursor?

### ISSUE THREAD

**Issue by aditya-K2** [neovim/neovim#15296]
I am working on a plugin that requires the word under the cursor as input is there a way to get it?

**Comment by booperlv** [comment]
There is no lua api function for it, but you can do so in other ways.
Here's one of many ways to do it:
```lua
-- <cword> means current word, expand function returns the actual value of <cword>.
-- check out :help cword if you might need something else.
local function getWordUnderCursor()
  return vim.fn.expand("<cword>")
end
```
I just visited two stackoverflow pages and a single help page to get this :P
May I ask why you are looking for a lua api function?
There are already many solutions that are very easily found.

**Comment by yochem** [comment]
There now is: `vim.api.nvim_win_get_cursor(0)`
