### ISSUE TITLE
LSP: tagfunc

### ISSUE THREAD

**Issue by VVKot** [neovim/neovim#15309]
### Feature already in Vim?

Yes, if you consider ctags et all. Yes, if you consider coc.nvim.

### Feature description

Does it exist? If so - we should make it clearer in the docs, if not - why not?

**Comment by clason** [comment]
Does it make sense? Could you describe a usecase in more detail? Why would you not just use the corresponding LSP functions?

**Comment by VVKot** [comment]
Same as LSP implementation of omnifunc, coc's implementation of tagfunc - integration with existing editor concepts/shortcuts. For example, `<C-w><C-]>` to spilt and go to definition would've been nice.

**Comment by clason** [comment]
No, sorry, you have to be more specific. What exactly (in terms of the LSP spec) should that tagfunc be doing?

**Comment by VVKot** [comment]
It should perform "go to definition". `vim.lsp.buf.definition` already does roughly `tjump` semantics, showing the list of possible locations if there is more than one, and performing "jump" if there is one. There is also already some custom code that pushes jumps using LSP to tagstack because I cant `<C-t>` back after going to definition.

**Comment by clason** [comment]
So what's missing? You can just override the `textDocument/definition` handler to open the location in a new split and bind that to `<c-w><c-]>`.

(The `tagfunc` itself doesn't do any jumping; it just returns a list of tags. It's certainly possible to write a `tagfunc` that just returns `workspace/Symbols` instead -- similar to what CoC does -- but so far nobody has missed this enough to actually implement it. If you _do_ feel the need, though, a PR would be welcome.)

**Comment by clason** [comment]
Also, there's already a plugin that does this: https://github.com/weilbith/nvim-lsp-smag

**Comment by mfussenegger** [comment]
I've also got a tagfunc implementation - in case somebody wants to use this as a basis for a PR: It supports the `<c-]>` and `:tselect` cases:

https://github.com/mfussenegger/dotfiles/blob/65e983e896589323fe1dd62a944e0bbb802523f1/vim/.config/nvim/lua/me/lsp/ext.lua#L1-L66
