### ISSUE TITLE
[Feature] Add virtual text beyond eol

### ISSUE THREAD

**Issue by ray-x** [neovim/neovim#15318]
### Feature description

How to put `virtual text 2` from `^`

```
some text.          virtual text 1 from here                       virtual text 2

          ^EOL                                                    ^  I want to put virtual text form here

```

Currently, I am using 
```
    vim.api.nvim_buf_set_extmark(0, 2, 1, 63, {
      virt_text = {{ 'virtual text 2 from here', 'ErrorMsg'}},
      virt_text_pos = 'overlay'
    })
```

But I got a `col outside range error`.

**Comment by bfredl** [comment]
use `virt_text_win_col=63`. see `:help nvim_buf_set_extmark()`

**Comment by jdhao** [comment]
It seems that `col` param only works  when we use `opts.virt_text_pos = 'overlay'`. If `opts.virt_text_pos= 'eol'`, virtual text will be placed after EOL. And if  `opts.virt_text_pos = 'right_align'`, virtual text will be put in the far right of the line.

Only `opts.virt_text_win_col` can truly help you put virt text in any column.  The doc is not really very clear in stating that. I learned this the hard way after a lot of trial and error with this function.
