### ISSUE TITLE
LSP completion ignoring "longest" in completeopt

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#15314]
### Neovim Version

NVIM v0.5.0

### Operating system/version:

Ubuntu 21.04

### Terminal name/version:

Konsole 20.12.3

### TERM environment variable

xterm-256color

### Installation

appimage

### Steps to reproduce

```vim
nvim -u NORC

" Add lspconfig to the runtime path (path should be updated accordingly)
:set runtimepath+=~/.local/share/nvim/site/pack/plugins/opt/nvim-lspconfig

" Configure LSP
:lua require('lspconfig').clangd.setup{}

" Set completeopt to show a popup menu and only insert longest common text of matches
:set completeopt=menu,longest

" Edit a C file and configure omnifunc to use LSP
:edit test.c
:setlocal omnifunc=v:lua.vim.lsp.omnifunc
```

Enter insert mode and add the following lines:

```c
int func1(void);
int func2(void);
```

Then add another line with text:

```c
int x = fu
```

When pressing `<c-x><c-o>` to complete the text, "func2" is inserted, as opposed to "func".

Pressing `<c-n>` instead of `<c-x><c-o>` inserts "func", respecting "longest" in "completeopt".

### Expected behavior

A popup menu would show, with "func" inserted.

### Actual behavior

A popup menu shows, with "func2" inserted.

**Comment by dstein64** [comment]
It doesn't appear to be an issue with `omnifunc` generally. When I edit a Python file without using LSP, the `omnifunc` is automatically set to `python3complete#Complete`.

When I add the following in insert mode:

```python
var1 = 20
var2 = 30

print(v
```

And then press `<c-x><c-o>`, `var` is inserted (as opposed to `var1` or `var2`, which would ignore `longest`, analogous to the issue I'm reporting).

**Comment by dstein64** [comment]
The issue also arises when `menu` is omitted from `completeopt`, and only `longest` is used.

**Comment by mjlbach** [comment]
I'm wondering if this is because the completefunc we use is populated asynchronously, I think longest is only applied on the initial invocation at which point the completion list would be empty.

**Comment by dstein64** [comment]
It appears due to the call to `complete()` not respecting `completeopt`.

I thought this was a bug, so I filed [Vim Issue #8736](https://github.com/vim/vim/issues/8736), but the behavior is intended.

I've worked around the issue by defining a synchronous omnifunc that doesn't rely on `complete()`, but rather follows the protocol specified in `:help complete-functions`.

https://github.com/dstein64/dotfiles/blob/e4b5332a63cfcf57a5b70cbed7867baffb4c112a/packages/vim/.vimrc#L482-L518

**Comment by dstein64** [comment]
> "Is it ok if I close this issue in favor of that one?"

Using a synchronous omnifunc was a workaround for me, but perhaps there are ways to address the issue using an asynchronous omnifunc (e.g., avoiding `complete()` or modifying the text after `complete()` finishes). If that's the case, then this ticket would be independent of #12390.

In either case, it's fine with me if you think this ticket should be closed 👍.
