### ISSUE TITLE
Commented lines does not show up in nested tmux session

### ISSUE THREAD

**Issue by nippyin** [neovim/neovim#15326]
### Neovim Version

NVIM v0.6.0-dev+119-g68f61b167

### Operating system/version:

RHEL 8.4

### Terminal name/version:

Kitty

### TERM environment variable

screen

### Installation

snap

### Steps to reproduce

Within tmux nested session when Using NVIM, try to open file /etc/chrony.conf I don't see commented lines. see below screen shot.
![image](https://user-images.githubusercontent.com/41337248/128794892-f873ad82-bffb-4f24-b7dd-85a606be25a3.jpeg)

If at the same nested session I to open same file using vi editor, as we can see it does show all lines.

![image](https://user-images.githubusercontent.com/41337248/128794922-e4bd5b2b-5c11-4455-86d3-11d12282d29a.jpeg)

### Vim

VIM - Vi IMproved version 8.0.1763

### Expected behavior

Expect to see all lines of config file, as it does work within single tmux session as show in the screen shot below.

![image](https://user-images.githubusercontent.com/41337248/128795181-dd79147b-9e00-4021-b41b-a3946f211b8a.jpeg)

### Actual behavior

Nested tmux session nvim does not show all lines of a file.

**Comment by justinmk** [comment]
> ### TERM environment variable
> screen

this is not correct for tmux
