### ISSUE TITLE
Stuck when split window

### ISSUE THREAD

**Issue by cage1618** [neovim/neovim#15328]
### Neovim Version

0.5.0

### Operating system/version:

mac os 11.4 big sur

### Terminal name/version:

iTerm2 Build 3.4.8

### TERM environment variable

xterm-256color

### Installation

homebrew

### Steps to reproduce

run command :vnew or  :new

**Comment by clason** [comment]
Please add an actual description about what happens -- as it stands, this report is not reproducible at all.
