### ISSUE TITLE
sometimes screen is completely screwed up when I press Enter

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#15338]
### Neovim Version

 v0.6.0-dev+119-g68f61b167

### Operating system/version:

Linux CentOS 7

### Terminal name/version:

zoc terminal

### TERM environment variable

xterm-256color

### Installation

binary release

### Steps to reproduce

I can not seem to fully reproduce it. Sometimes, when I run `PackerUpdate` and press `Enter` on one of the updated packages, the screen got screwed up. Other times, when I search a word and press `Enter`, the issue occurs. I have to press `Ctrl-L` to redraw the screen  to return to normal state.

### Vim

Not tested.

### Expected behavior

The screen is not screwed up.

### Actual behavior

The neovim screen is screwed up and I have to press `Ctrl-L` to redraw it.

 See the image below for an example.

https://imgtu.com/i/fUYKHO

**Comment by justinmk** [comment]
not actionable
