### ISSUE TITLE
Dev Q: Where are the various types (`*_T`) defined?

### ISSUE THREAD

**Issue by danielyli** [neovim/neovim#15337]
Hey there,

After cloning the repo and grepping around in `src/nvim/`, I quickly realized I can’t find many of the type definitions (or value definitions) used throughout the code. For example, the `event_T` and `buf_T` types, or the `EVENT_*` values.

Where are these defined?

**Comment by muniter** [comment]
I've been in the same process. Using built-in LSP with clangd go to definition is your friend.

`buf_T` is in https://github.com/neovim/neovim/blob/master/src/nvim/buffer_defs.h

There's a Neovim IRC/matrix channel that might be better for some of this questions. 

https://matrix.to/#/#neovim:matrix.org

😃

**Comment by danielyli** [comment]
Thank you

**Comment by danielyli** [comment]
Thank you

**Comment by dundargoc** [comment]
> Hey there,
> 
> After cloning the repo and grepping around in `src/nvim/`, I quickly realized I can’t find many of the type definitions (or value definitions) used throughout the code. For example, the `event_T` and `buf_T` types, or the `EVENT_*` values.
> 
> Where are these defined?

I think they're generated when building neovim in `src/nvim/CMakeLists.txt` which in turn calls `src/nvim/generators/gen_events.lua`. As for why this design choice was made I really can't answer. 

I think you'd get more mileage by asking in [gitter](https://gitter.im/neovim/neovim) or [discourse](https://neovim.discourse.group/).
