### ISSUE TITLE
Customizable window-local filler lines

### ISSUE THREAD

**Issue by oxilumin** [neovim/neovim#15331]
### Feature description

I was thinking about some use cases & UI enhancing plugins that are difficult to implement now without the ability to have customizable filler lines (like +- in diff) on a per-window basis.

Currently filler lines processing seems to be heaviliy localized in diff-related code, but conceptually is not tied much to diff-ing logic.

One of the most interesting (IMO) use-cases is inline comments in code-reviews like here: 
![](https://i.stack.imgur.com/0tN3e.png)
The work-around now is: creating a merged buffer with code + comments, creating a new tab (since 1 diff per tab), internally going into diff mode, hiding the helper window & using buffer linked floating windows to show comments. This kinda works for me now, but seems to be a fragile contraption + doesn't really work well out of the box with different buffer/bufline/tabline managers.

Why not just insert newlines?
* Messes up line numbers
* Does not always produce valid code (for syntax highlighting + lsp), esp. around verbatim strings.
* Messes up with line navigation

Another use cases: 
* More sofisticated codelenses (on a separate line).
* Cursor-positioned signature helpers that don't obscure the code around
* Non-obscuring code peek: ![](https://i.stack.imgur.com/scYDM.png)
* ...

Conceptually I see 2 ways to implement it in API:

1) Like with filler lines, the structures behind would stay a single window/a single buffer, and fillers API is implemented similar to extmarks (to get some position consistency when editing) but with attached "size" to indicate how many filler lines to insert.

```
nvim_buf_set_filler({window}, {ns_id}, {line}, {opts})
  {opts}    Optional parameters. Keys:
                              • id : id of the extmark to edit.
                              • line_num : line to put filler after
                              • lines_len : number of lines for the filler

nvim_buf_get_filler({window}, {ns_id}, {id})

nvim_buf_get_filler_by_id({window}, {ns_id}, {id})

nvim_buf_get_fillers({window}, {ns_id}, {start}, {end}, {opts})
  {opts}    Optional parameters. Keys:
                • details Whether to include the details dict
```

2) More user-friendly and flexible (IMO): add new `relative = 'win_inline'` option for floating windows.

```
let buf = nvim_create_buf(v:false, v:true)
call nvim_buf_set_lines(buf, 0, -1, v:true, ["test", "text"])
let opts = {'relative': 'win_inline', 'height': 2, anchor:'N', bufpos_line: 100, focusable: v:false}
let win = nvim_open_win(buf, 0, opts)

  anchor='N' to add filler below bufpos
  anchor='S' to add filler above bufpos
```

Navigation/lines numbering in host window could be similar to the case of diff mode with removed lines.
`width` and `bufpos={row, col}` might arguably make sense to support multiple floating windows per filler-chunk (as example - to support syntax highlighting for suggested edits). When set the space would be allocated as without `width`/`col`, but the floating window itself would be positioned inside the filler at `col` and be of width `width`

**Comment by clason** [comment]
I think that should be completely addressed by https://github.com/neovim/neovim/pull/9496

**Comment by oxilumin** [comment]
> I think that should be completely addressed by #9496

I looked through all the issues with all relevant keywords I could think of before posting, but anticonceal was not one of them.
But looking at it now: virtual text is less feature rich in this sense as it does not allow to bind a different buffer (with all autocmds etc) to the filler lines. I thought of the case for writing/replying to comments & scrolling in this filler floating window (so it could potentially be focusable).

**Comment by clason** [comment]
That sounds like an XY problem to me? (You can style extmarks however you want, and I don't see what autocommands you want on inline comments? And you can always add empty virtual lines and plop a floating window over them...)

**Comment by oxilumin** [comment]
API verbosity aside - yeah, I guess this should work (add floating window anchored to the same pos an extmark with virtual lines is attached to).  Hope #9496 will eventually get implemented... Would link this issue as one more usecase to #9496.

**Comment by oxilumin** [comment]
Duplicate of #9496
