### ISSUE TITLE
Assertion failure when requiring missing lua module, in a Cmdline* autocmd, when package.path is long

### ISSUE THREAD

**Issue by rktjmp** [neovim/neovim#15348]
### Neovim Version

NVIM v0.8.0-dev-961-g0b72e23bf (Debug build)

### Operating system/version:

Linux/Arch

### Terminal name/version:

NA

### TERM environment variable

NA

### Installation

asdf

### Steps to reproduce

This can occur if you're using packer, since it sets a longer than usual `package.path`.

**init.lua**

```lua
-- value pulled from packer_compiled.lua source
local package_path_str = "/home/username/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua;/home/username/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua;/home/username/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua;/home/username/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua"
package.path = package.path .. ';' .. package_path_str

vim.api.nvim_exec(
  [[
  augroup Crasher
    autocmd!
    autocmd CmdlineLeave / lua require("fake-moustache")
  augroup end
]],
  false
)
```

`Containerfile` reproduction against master HEAD:

<details>

```containerfile
# Build neovim separately in the first stage
FROM alpine:latest AS base

RUN apk --no-cache add \
    autoconf \
    automake \
    build-base \
    cmake \
    ninja \
    coreutils \
    curl \
    gettext-tiny-dev \
    git \
    libtool \
    pkgconf \
    unzip

# Build neovim (and use it as an example codebase
RUN git clone https://github.com/neovim/neovim.git

ARG VERSION=master
RUN cd neovim \
    && git checkout ${VERSION} \
    && make CMAKE_BUILD_TYPE=RelWithDebInfo install

RUN echo $' \n\
-- value pulled from packer_compiled.lua source \n\
local package_path_str = "/home/username/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua;/home/username/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua;/home/username/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua;/home/username/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua" \n\
package.path = package.path .. ";" .. package_path_str \n\
vim.api.nvim_exec( \n\
  [[ \n\
  augroup Crasher \n\
    autocmd! \n\
    autocmd CmdlineLeave / lua require("fake-moustache") \n\
  augroup end \n\
]], \n\
  false \n\
)' >> /init.lua

CMD ["nvim", "--clean", "-u", "/init.lua"]
```

</details>

**Steps**

1) `nvim --clean -u init.lua`
2) `/<cr>`

Note we:

- have a long `package.path`
- require a missing module in an `autocmd` (please remove your fake moustache if you have one)

If you comment out setting `package.path`, the `autocmd` will simply print an error.

### Vim

Does not crash, prints normal lua "require error"

<details>

```viml
lua package.path = string.rep((package.path .. ";"), 20)

augroup Crasher
  autocmd!
  autocmd CmdlineLeave / lua require("fake-moustache")
augroup end
```

</details>

### Expected behavior

Print error to messages.

### Actual behavior

```
Assertion failed: len < 0 || memchr(str, 0, (size_t)len) == NULL (/neovim/src/nvim/message.c: msg_puts_attr_len: 2058)
                         Aborted (core dumped)
```

**Comment by clason** [comment]
(can reproduce on macOS)

**Comment by rktjmp** [comment]
Additional: The effect doesn't occur for `BufEnter`, `ColorScheme`, `InsertEnter`, `CmdwinEnter`.

Does occur for `CmdlineEnter`, `CmdlineChanged`, `CmdlineLeave`, possibly only those.

**Comment by clason** [comment]
I can no longer reproduce this on master (proper `E5500` error, no crash).

**Comment by rktjmp** [comment]
Still reproduced on linux, via [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim/blob/master/Dockerfile) container

![image](https://user-images.githubusercontent.com/866010/186950563-05665c6d-6d4e-47d1-b275-ba121fd6ade9.png)

**Comment by clason** [comment]
Can you update the MRE in the issue then?

**Comment by rktjmp** [comment]
Sorry, I was just linking the kickstarter dockerfile as a "builds against master", it still reproduces against a zero'd config. I have included a minmal containerfile in the OP too.

**Comment by clason** [comment]
That's fine; I missed that this was an assertion failure rather than a crash so is only triggered on `Debug` builds. I edited the title (and text) to make that clear (so I won't fall for it again).

**Comment by dundargoc** [comment]
@rktjmp please test: https://github.com/neovim/neovim/pull/18705

**Comment by rktjmp** [comment]
lgtm?

![image](https://user-images.githubusercontent.com/866010/188535107-1d6284d0-2aa0-4eca-992f-6fabfdec58a9.png)
