### ISSUE TITLE
TUI: Enable/disable modifyOtherKeys automatically

### ISSUE THREAD

**Issue by gnachman** [neovim/neovim#15352]
### Feature already in Vim?

Yes in patch 8.1.2194

### Feature description

neovim added support for `modifyOtherKeys` in #176 but it requires the user to enable it, and it's not clear how users are expected to do this. iTerm2 added a UI switch to enable it, but this causes a million other problems since most programs (including shells) don't handle CSI u style input well.

vim defines `t_TI` and `t_TE` which (by default) enable or disable `modifyOtherKeys` mode. For details, see the help text here: https://github.com/vim/vim/blob/63b9173693015b135aad8e3657bef5e7f776787e/runtime/doc/map.txt#L905

Use `CSI > 4 ; 2 m` to enable and `CSI > 4; 0 m` to disable.

There are newer control sequences of `CSI > 1 u` and `CSI < u` to push and pop keyboard state but they are not widely supported in terminal emulators.

The only downside I see to implementing this is if neovim crashes or an enclosing ssh session ends unexpectedly the terminal will be left in modifyOtherKeys mode, making it hard for the user to interact with their shell. Most terminal emulators have a reset function to let the user get back to a good state.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/nitty-gritty-questions-on-terminal-nvim-and-keyboard-events/1624/1

**Comment by zeertzjq** [comment]
This may be achieved using something like:
```vim
autocmd UIEnter * if v:event.chan ==# 0 | call chansend(v:stderr, "\x1b[>4;2m") | endif
autocmd UILeave * if v:event.chan ==# 0 | call chansend(v:stderr, "\x1b[>4;0m") | endif
```
or
```vim
autocmd UIEnter * if v:event.chan ==# 0 | call chansend(v:stderr, "\x1b[>1u") | endif
autocmd UILeave * if v:event.chan ==# 0 | call chansend(v:stderr, "\x1b[<1u") | endif
```
