### ISSUE TITLE
New parser/translator merging plan

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#1536]
With the current progress of writing the translator it is going to take forever to make it. Thus instead of waiting when it was completely finished I suggest the following plan:
1. Finish the parser and printer. They are almost complete anyway, but I am sure they do contain bugs.
2. Keep current executor, make it be feeded with the results of parsing code by the new parser and then dumping it back again.
   
   This will highly slow down Vim, but still at this point it makes sense to merge (the result of each of the following step is to be merged as well) to some experimental branch so that a number of errors in parser and printer can be caught. Another reasoning is that I will know entry points for the code and will rewrite them to use the new parser: in any case this will be needed as the first step.
3. Replace `eval*` with the code that will use the new parser (again) and execute the resulting AST. Reasoning for this step is the existence of the next step.
4. Refactor all functions that are currently executing strings with functions that are executing AST. It is much faster then rewriting them in lua and opens the way to the next step. This should speed up NeoVimL greatly I think and may be included in `master`.
5. Refactor all functions that were refactored in the previous step to use _only_ API functions (actually this is “factor the API functions out of the commands”). Reasoning is the same as in #801. It makes sense to refactor them using macro-based very restricted pseudo-language so that a few `#define`s will make C code lua code or anything else you want.
6. Benchmark and optimize the existing lua translator, without actually using it (or adding any new commands there). If solution from the previous step (which compared to the currest state is “replace code that executes C strings with code that executes AST”) proves to be 2 or more times faster then anything I (or somebody else) can come up with give up the translator and check for another possibilities.
   
   Some notes about last statement:
   1. Core of the lua translator is almost finished. There are lots of things that must be added to call it VimL replacement, but it makes sense to benchmark what is already there, just add some type-manipulating functions `extend` which is trivial.
   2. Other possibilities include “write yet another VM and use it”, “use LLVM JIT compilation capabilities” (note: will reduce number of architectures that can be supported), “try writing another JIT based on PyPy” (it claims to have support for adding languages other then Python, but I have never heard of any project like this, it is also not as portable as LuaJIT), “use somebody’s else VM like parrot”, “leave the situation as-is” (last one means “replace strange interpreter that executes C strings with strange interpter that executes AST”) and “find another person that can do this”.  I do not include: a) libjit as it is known to be too low-level b) JVM and .Net/Mono VM as they are too bold c) translating to javascript/Python/… as these solutions will likely face similar problems as translating to lua or are not portable or bold. If I have not mentioned some other VM or some other way to write JIT compiler then I do not know it.

As I side note I should say that current parser is not suitable for syntax highlighting (direct consequence of the initial decision “take existing code and rewrite it to get the parser”) and thus will eventually be refactored. It is still suitable for executing code and for the code formatter (but not linter).

**Comment by justinmk** [comment]
@ZyX-I As a first step, could you push your branch to a new branch (e.g. `luaviml`) on this repo and start using that as your WIP?

**Comment by ZyX-I** [comment]
**Update**:

- Lots of error messages (see commit log).
- `:syn cluster Foo add=A,B,C remove=C add=C` or similar will probably not do 
  what you want: such things are parsed into `syn cluster Foo add=A,B,C,C 
  remove=C` (separate arguments are always parsed into one list and thus you 
  will most likely end up with `C` in `Foo` cluster).
- `:syn cluster` subarguments order is not preserved, executors are supposed to 
  process them in order contains, add, remove.

@justinmk I would rather not do anything with the main repository until we switch to mercurial. I happened to do funny things (like pushing unrelated repository or dropping a few months of work) when history is editable.

**Comment by justinmk** [comment]
@ZyX-I We have non-fast-foward disabled on master (but only master). So you won't be able to delete history from master on the main repo, at least.

**Comment by elmart** [comment]
> until we switch to mercurial

What? Has switching to mercurial ever been discussed?

**Comment by justinmk** [comment]
@elmart cheeky wording

**Comment by ZyX-I** [comment]
**Update**:

- Invalid range in glob pattern prevents pattern from being used, *not* emits an 
  error and proceeds with treating this range literally.
- “E16: Invalid range” is “E16: Invalid range: end is greater then start” in 
  glob patterns.
- Treatment of the “corner cases” like `[a-[:alnum:]]` differs.
- It is currently not possible to fall back to “treat the file name literally” 
  variant if pattern matching failed in many cases because parser does not save 
  this information (this will be a few lines fix to save this information, but 
  I do not think this is a good idea: if user meant a pattern he should get 
  a pattern, if user meant no pattern then there is backslash at his service).

**Comment by wdv4758h** [comment]
just some comments about PyPy :P

AFAIK, they are creating a framework (and toolchain) for writing dynamic languages' VM. They use a language called RPython to implement interpreter, and the toolchain can generate Tracing JIT and GC for you. The RPython is a language similar to Python with some restriction of features which are too much dynamic. The major concept is the toolchain will do type inference and some analysis for RPython to generate better result. The overall result is decided by backend, they are using a backend called GenC which generate C code now (but someone can still make other backends, e.g. generate Java bytecode).

So, PyPy is a Python interpreter written in RPython and compiled by GCC or Clang (with RPython's GenC backend).

Pros:

* you can write interpreter in RPython which may cost less effort compare to C or C++ or something.
* you can get a JIT easily (3 lines for a basic version, use some Python decorator can improve it)
* you can get a incremental generational mark-and-sweep GC easily (by just a CLI option)
* you can get some improvement by just update RPython toolchain in the future (JIT or GC or something) (or maybe Software Transactional Memory which they still working on)

Cons:

* RPython's restriction is still not well documented (they have written something, but not specific)
* the toolchain to generate JIT is still slow and need some resource (IIRC, about 16 mins for just generating and compiling a normal Brainfuck interpreter, I tried it last winter)
* we need to make the new VM available for a lot of platforms (effort here)
* maybe the debugging will be much more complex ?

Notice: I'm not a master for this :P

----

Documentation

* [RPython’s documentation](http://rpython.readthedocs.org/en/latest/index.html)

Other Languages' implementation

* Lisp : [Pixie](https://github.com/pixie-lang/pixie)
* PHP : [HippyVM](https://github.com/hippyvm/hippyvm)
* Ruby : [Topaz](https://github.com/topazproject/topaz)
* Prolog : [Pyrolog](https://bitbucket.org/cfbolz/pyrolog/)
* Smalltalk : [RSqueak](https://github.com/HPI-SWA-Lab/RSqueak)

**Comment by ZyX-I** [comment]
I was considering PyPy, but did not find enough documentation and examples. You have done better. I did not try too much because of the two larger concerns:

1. PyPy builds are *very* slow. Average merge time reported by `genlop` is 2,5 hours and my PC is not one of the worst ones.
2. PyPy builds need lots of RAM.
3. PyPy supports far less architectures then luajit.
