### ISSUE TITLE
Incorrect appdata.xml version in 0.5.0 release

### ISSUE THREAD

**Issue by yvesnrb** [neovim/neovim#15362]
### Neovim Version

0.5.0

### Operating system/version:

N/A

### Terminal name/version:

N/A

### TERM environment variable

N/A

### Installation

Flatpak

### Steps to reproduce

Go to the 0.5.0 release branch and navigate to the runtime/nvim.appdata.xml file. The release section only lists releases up to version 0.4.4.

### Vim

N/A

### Expected behavior

The 0.5.0 release should have the newest version listed on the appdata file.

### Actual behavior

This problem causes the flatpak version to only report 0.4.4 version, even though it has already been updated to 0.5.0 for two months. This mismatch could possibly cause problems in other places as well. A 0.5.1 release that fixes this issue would be greatly appreciated by the flatpak community.

**Comment by rktjmp** [comment]
Tentative fix here https://github.com/rktjmp/neovim/commit/7de0c1eb5e611595c5cfa5b7a7bd7da91c670c20 (careful, big changeset).

Not sure if a 0.5.1 release needs to be cut, https://github.com/flathub/io.neovim.nvim can maybe rebuild and redeploy, which would bump the version to 0.5.0, making it *look* like a new version to flathub anyway?

:thinking:

**Comment by yvesnrb** [comment]
That would change the diff of the release tar, so flathub/io.neovim.nvim would break. We would need to fix that but I suppose it's not that big of a deal.

**Comment by yvesnrb** [comment]
Actually I should not be so quick to assume it won't be a big deal. I'm assuming the flathub build bot won't try to rebuild the current release with the same build file that would then have a wrong diff, but I could be wrong on that.

**Comment by rktjmp** [comment]
> I'm assuming the flathub build bot won't try to rebuild the current release with the same build file that would then have a wrong hash, but I could be wrong on that.

https://flathub.org/apps/details/io.neovim.nvim lists it as 0.4.4, I assume it pulls that from the build artefact? So wouldn't the bump from 0.5.0 just let everything run as normal even though there is no code changes? It should look like a real version bump to the robots :robot:?

The hash can break and just "pretend" it's going from 4 to 5?

**Comment by yvesnrb** [comment]
> https://flathub.org/apps/details/io.neovim.nvim lists it as 0.4.4, I assume it pulls that from the build artefact?

It pulls it from that appdata.xml file, yes.

>So wouldn't the bump from 0.5.0 just let everything run as normal even though there is no code changes? It should look like a real version bump to the robots?

The current build pulls the "https://github.com/neovim/neovim/archive/v0.5.0.tar.gz" file with a hash of "2294caa9d2011996499fbd70e4006e4ef55db75b99b6719154c09262e23764ef". If the changes are pushed to that same release the hash for that file would change, we would then have to push a new commit to the Flathub repository with a new hash which should make the bots build a new version of the Flatpak and deploy it to Flathub (they do that on every commit, they don't wait for a new version to do it). What I'm worried about is the in between period of that hash changing and a commit being accepted into the Flathub repository to fix the hash. I'm leaning towards it being fine but I've asked on the Flatpak matrix channel just to be safe.

**Comment by yvesnrb** [comment]
I have now received word that changing the release archive checksum should be avoided if possible, it could affect any other distro that packages neovim otherwise, and they won't necessarily understand why the checksum changed. This is ultimately a decision of the neovim maintainers though, they could have a different policy on this kind of thing.
