### ISSUE TITLE
"set title" causes cursor to jump to statusline or commandline

### ISSUE THREAD

**Issue by m8dotpie** [neovim/neovim#15369]
### Neovim Version

0.5.0

### Operating system/version:

MacOS 11.5.1

### Terminal name/version:

Neovide 0.7.0

### TERM environment variable

xterm-256color

### Installation

brew

### Steps to reproduce

**Minimal config:**
set title

**Steps to reproduce:**
Try to search something and stop search or write buffer or change buffer/etc

### Vim

Without title it works nice

### Expected behavior

Cursor stays where it was

### Actual behavior

Cursor jumps to tabline/statusline
Interesting fact that nvim considers cursor on correct line, so continuing typing solves the issue, but the cursor draws in other place.

**Comment by m8dotpie** [comment]
Related issue from Neovim: #11806

**Comment by justinmk** [comment]
> Related issue from Neovim with lazyredraw: #11806

closing this as duplicate
