### ISSUE TITLE
The cursor move to the popup definition and active the insert mode

### ISSUE THREAD

**Issue by guerreroz01** [neovim/neovim#15371]
### Neovim Version

v.0.4.4

### Operating system/version:

kali linux 2021.2

### Terminal name/version:

zsh 5.8

### TERM environment variable

xterm-256color

### Installation

repo

### Steps to reproduce

If anybody can help me because this is annoying

[https://www.youtube.com/watch?v=--xBnSCAUik](url)

### Vim

VIM - Vi IMproved 8.2

### Expected behavior

I expect not jump to the text in the definition pop up

### Actual behavior

Is jumping to the pop up window and stay in insert mode

**Comment by saadparwaiz1** [comment]
What language server client is this? It's most likely an error with the client and not neovim itself

**Comment by clason** [comment]
It's probably the (intended) "invoking hover twice enters the float" functionality that is occurring here. Without more details (in the issue itself; I'm not watching Youtube videos frame by frame to sleuth it out) it is impossible to tell.

**Comment by guerreroz01** [comment]
it's with the python server
