### ISSUE TITLE
External command output displays broken text

### ISSUE THREAD

**Issue by comiluv** [neovim/neovim#15388]
### Neovim Version

NVIM v0.6.0-dev+116-g35041432b

### Operating system/version:

Windows 10/21H1 19043.1165

### Terminal name/version:

Windows Terminal Preview/1.10.1933

### TERM environment variable

Nothing is displayed

### Installation

chocolatey

### Steps to reproduce

1. !dir

### Vim

Vim correctly displays unicode characters

### Expected behavior

Correct display of characters such as shown below which is output of !dir in Vim started with ```vim -u DEFAULTS```
<img width="866" alt="화면 캡처 2021-08-16 170615" src="https://user-images.githubusercontent.com/19642705/129532392-a9c89950-86b5-461e-8446-7d2c61a548dd.png">

When the user give command !chcp in Vim, it shows the codepage is 65001 which is UTF-8

### Actual behavior

Neovim fails to display characters
<img width="866" alt="화면 캡처 2021-08-16 170504" src="https://user-images.githubusercontent.com/19642705/129531950-ed591b51-4e95-4890-9822-54d3488f451f.png">
Issuing command !chcp in Neovim says its codepage is 949 which is euc-kr, which suggests root of this issue.

**Comment by comiluv** [comment]
Tried ```!chcp 65001 && dir``` but failed to render text correctly.

**Comment by justinmk** [comment]
> When the user give command !chcp in Vim, it shows the codepage is 65001 which is UTF-8
>
> Issuing command !chcp in Neovim says its codepage is 949 which is euc-kr, which suggests root of this issue.

in nvim , `:!` always runs in a pipe, it has no concept of the terminal codepage. 

this is wontfix.

a workaround is to use `:terminal`
