### ISSUE TITLE
Inconsistent behaviour in vim.tbl_deep_extend

### ISSUE THREAD

**Issue by Slyces** [neovim/neovim#15382]
### Neovim Version

NVIM v0.6.0-dev+132-g7d2233fad

### Operating system/version:

Ubuntu 16.04.6 LTS (Xenial Xerus)

### Terminal name/version:

alacritty 0.7.0-dev (de9ed25)

### TERM environment variable

xterm-256color

### Installation

From source

### Steps to reproduce

```lua
lua print(vim.inspect(vim.tbl_deep_extend("keep", {1, 2}, {[3]=3})))
-> {1, 2, 3}
```
vs.
```lua
lua print(vim.inspect(vim.tbl_deep_extend("keep", {key={1, 2}}, {key={[3]=3}})))
-> {
  key = { 1, 2 }
}
```

### Vim

Does not apply

### Expected behavior

As the documentation of `vim.tbl_deep_extend` states:
> Merges recursively two or more map-like tables.

I expected that function to behave consistently over `table1, table2` and `{key=table1}, {key=table2}`.

**Expected Code**
```lua
lua print(vim.inspect(vim.tbl_deep_extend("keep", {1, 2}, {[3]=3})))
-> {1, 2, 3}

lua print(vim.inspect(vim.tbl_deep_extend("keep", {key={1, 2}}, {key={[3]=3}})))
-> {
  key = { 1, 2, 3 }
}
```

Please note that I am a beginner with lua and the neovim API, so my expectations might be wrong.

### Actual behavior

It appears that this is not true when the keys are numbers: the merge is successfull on the main level (`table1, table2`) but not on subkeys (`{key=table1}, {key=table2}`).

**Actual Code**
```lua
lua print(vim.inspect(vim.tbl_deep_extend("keep", {1, 2}, {[3]=3})))
-> {1, 2, 3}

lua print(vim.inspect(vim.tbl_deep_extend("keep", {key={1, 2}}, {key={[3]=3}})))
-> {
  key = { 1, 2 }
}
```

**Comment by p00f** [comment]
"We only merge empty tables or tables that are not a list"
`{ 1, 2 }` is a list ( `{ 1, 2}` is `v` here: https://github.com/neovim/neovim/blob/5fd21b8d3e9dcb2b3dc3bdab4b58218ac908e3e8/runtime/lua/vim/shared.lua#L228)

**Comment by p00f** [comment]
See #15124

**Comment by justinmk** [comment]
> when the keys are numbers

For reference, we tried supporting this in https://github.com/neovim/neovim/pull/30251 , but it was reverted later.

We do plan to introduce something more comprehensive similar to what was started in https://github.com/neovim/neovim/pull/15124 .
