### ISSUE TITLE
Expose more of treesitter node API

### ISSUE THREAD

**Issue by Dkendal** [neovim/neovim#15408]
### Feature description

The lua/treesitter.c API should be extended to include more of the individual node accessors, as well as expose the stateful TSTreeCursor object. These additions would provide more efficient treesitter operations for library authors.

The current Treesitter lua API exposes a few methods that allow for moving to other nodes, namely

```lua
tsnode:parent()
tsnode:iter_children()
tsnode:named_child({index})
tsnode:child({index})
```

But if you want to perform sibling look ups you have to find _this_ nodes index in its parent's children (_O(N)_), and then adjust the index relative to that. You can see this in nvim-treesitter/nvim-treesitter here:

https://github.com/nvim-treesitter/nvim-treesitter/blob/b8a6928b529fff6ea04593b381e73d4cbc9a9cdc/lua/nvim-treesitter/ts_utils.lua#L71-L80

While this is fine for singular operations if you need to do a full walk of the tree this becomes quite expensive (_O(N^N)_).

## Proposal

Given that treesitter exposes C functions for these standard operations I propose that we extend the lua/treesitter.c lua binding API to expose them.

```c
TSNode ts_node_next_sibling(TSNode);
TSNode ts_node_prev_sibling(TSNode);
TSNode ts_node_next_named_sibling(TSNode);
TSNode ts_node_prev_named_sibling(TSNode);
```

As a further enhancement I propose that we expose the [TSTreeCursor](https://tree-sitter.github.io/tree-sitter/using-parsers#walking-trees-with-tree-cursors) object in the lua API for more efficient tree traversals.

```c
TSTreeCursor ts_tree_cursor_new(TSNode);

bool ts_tree_cursor_goto_first_child(TSTreeCursor *);
bool ts_tree_cursor_goto_next_sibling(TSTreeCursor *);
bool ts_tree_cursor_goto_parent(TSTreeCursor *);

TSNode ts_tree_cursor_current_node(const TSTreeCursor *);
const char *ts_tree_cursor_current_field_name(const TSTreeCursor *);
TSFieldId ts_tree_cursor_current_field_id(const TSTreeCursor *);
```

## Questions

Are there any technical limitations that prevent this API from being implement today?

## Suggestions

I'm happy to work on this feature, any suggestions about the API, or other concerns I should be aware of would be appreciated :)

**Comment by bfredl** [comment]
There's no limitations, and a PR would be the most welcome.

**Comment by vigoux** [comment]
I can help with this if you want, we can make that something like a "tutored" PR.

**Comment by lewis6991** [comment]
Most of these are now added. Please raise a PR for any that are missing.
