### ISSUE TITLE
TUI: re-detect background color on SIGWINCH

### ISSUE THREAD

**Issue by will** [neovim/neovim#15411]
### Feature already in Vim?

not to my knowledge

### Feature description

An enhancement to https://github.com/neovim/neovim/pull/9509 / https://github.com/neovim/neovim/pull/5027 , it would be nice if upon receiving SIGWINCH, neovim re-detected the background color and set `background` to `light` or `dark` again as it does on startup (which seems to be, set the value if it's not set explicitly, then pretend it wasn't set).

The motivation for this is on profile changes iTerm2 [will soon send SIGWINCH](https://gitlab.com/gnachman/iterm2/-/issues/9855#note_651273659) and coupled with also upcoming feature of [changing terminal profiles automatically on system light/dark changing](https://gitlab.com/gnachman/iterm2/-/issues/7943), we could also have neovim themes that have light/dark modes like [tokyonight](https://github.com/folke/tokyonight.nvim) automatically change at the same time.

I've given this feature a quick stab by making `handle_background_color`non-static and calling it from `sigwinch_cb` but that's not quite working and I don’t really know anything about the codebase so it was just a guess. Maybe @joshtriplett  and @justinmk who wrote and merged the base feature have better ideas? Of course if this is at all an acceptable idea in the first place. I'd like it at least.

**Comment by bfredl** [comment]
Hmm I am not sure this is worthwhile unless the implementation is really trivial. changing terminal config at runtime is not a typical usecase, and even then I would argue that the terminal app (i e neovim) changing its internal behavior at the same time is _not_ expected. (what if you wanted to test various combinations of terminal config and neovim config)

**Comment by tomprince** [comment]
I'd definitely like something like this. I have long running terminals/nvim session, and reasonably frequently switch from light to dark and back, depending on time of day or whether I am inside or outside. It would be nice if I didn't need to manually switch each nvim instance (particularly as some of them may be suspended).
