### ISSUE TITLE
Setting vim.b.term_title behaves differently on 2 OSses

### ISSUE THREAD

**Issue by hahuang65** [neovim/neovim#15415]
### Neovim Version

```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system/version:

Arch Linux

### Terminal name/version:

kitty 0.23.1 created by Kovid Goyal

### TERM environment variable

xterm-kitty

### Installation

AUR

### Steps to reproduce

```
local function create_terminal(name, split)
  cmd(split..'new +terminal')
  bufnr = api.nvim_get_current_buf()
  terminals[name] = bufnr
  vim.b.term_title = name
  
  return bufnr
end
```

### Vim

N/A since this is written as a lua function

### Expected behavior

`:echo b:term_title` should return the name passed in.

### Actual behavior

On macOS with these properties:

```
$ nvim --version
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/build/config -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/build/include
Compiled by brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info
```

```
$ kitty --version
kitty 0.23.1 created by Kovid Goyal
```

```
$ echo $TERM
xterm-kitty
```

Installed nvim from `brew`

This works.

However, in Arch Linux, it seems that the terminal will overwrite the `b:term_title` after I've set it (I can see it happening in the statusline).

Curious. why this is different in Arch vs MacOS Catalina 10.15.7 (19H1323)

**Comment by muniter** [comment]
I believe `b:term_title` is set by your shell, which sends it to nvim terminal emulator which nvim sets as a buffer variable. So that variable is for reading, you are not supposed to write to it because nvim will overwrite it.

**Comment by gpanders** [comment]
I think @muniter is right: https://github.com/neovim/neovim/blob/15b736d6e88dba114294b84a21e463b77a0b2857/src/nvim/terminal.c#L801

Your shell is likely setting the terminal title (through the terminal escape code), which Nvim uses to set b:term_title. You can test this yourself by running

```sh
printf '\033]2;Hello\a'
```

From within the terminal shell and then see that `b:term_title` is now `Hello`.

**Comment by hahuang65** [comment]
@muniter the help pages actually says it's user writable:

```
*b:term_title*  Terminal title (user-writable)
```

@gpanders so I understand that the terminal will set it. The goal is that I set it after the terminal sets it. As far as macOS vs Arch... I'm using the same terminal emulator and I'm also using the same shell, so why would one be different than the other?

**Comment by gpanders** [comment]
> @gpanders so I understand that the terminal will set it. The goal is that I set it after the terminal sets it. As far as macOS vs Arch... I'm using the same terminal emulator and I'm also using the same shell, so why would one be different than the other?

It's possible the shells are different versions, or maybe they're packaged differently between the two OS's. Some shells will re-set the terminal title on each prompt (I have seen shells that do this and find it extremely annoying).

What shell are you using?

**Comment by hahuang65** [comment]
> What shell are you using?

```
GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)
```
and
```
GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)
```

**Comment by justinmk** [comment]
> The goal is that I set it after the terminal sets it.

The terminal can send the escape sequence at any time, it is not deterministic.
