### ISSUE TITLE
doc: "lcs"-tag not unique

### ISSUE THREAD

**Issue by marcusatiliusregulus** [neovim/neovim#15413]
### Neovim Version

v0.5.0

### Operating system/version:

arch linux

### Terminal name/version:

alacritty 0.9.0 (fed349aa)

### TERM environment variable

tmux-256color

### Installation

pacman -S neovim

### Steps to reproduce

`:h listchars`
`:h lcs`

### Vim

same problem

### Expected behavior

i wanted to go the the helppage "listchars"

### Actual behavior

i got to the page of "lcscope"

**Comment by clason** [comment]
The tag for the option is `'listchars'` (note the single quotes -- that's a standard convention).

**Comment by gpanders** [comment]
In general, to go to an option you need to use single quotes: `:h 'lcs`. This is documented in `:h help-context` (which also happen to be the first page when you open `:help`).

**Comment by marcusatiliusregulus** [comment]
sry
