### ISSUE TITLE
LSP: Add config option to not filter completion results

### ISSUE THREAD

**Issue by tomsmeding** [neovim/neovim#15414]
### Feature description

Currently, [in `vim.lsp.util.text_document_completion_list_to_complete_items`](https://github.com/neovim/neovim/blob/15b736d6e88dba114294b84a21e463b77a0b2857/runtime/lua/vim/lsp/util.lua#L658-L659), the completion results from the language server are not kept as-is, but instead some preprocessing is performed:

1. Only completions which exactly match the already-typed prefix are kept;
2. The completions are sorted.

While this is probably nice for some language servers that return weird results, this is completely counterproductive when a language server tries to be helpful by returning results with:
- case-insensitive matching
- typo-fixing
- intelligent result ordering so that most likely matches come first
- (maybe other things too)

At least the first three are performed by the Haskell language server.

At least for the Haskell language server in particular, my completion results get _significantly_ more useful when I remove [the two lines linked above](https://github.com/neovim/neovim/blob/15b736d6e88dba114294b84a21e463b77a0b2857/runtime/lua/vim/lsp/util.lua#L658-L659). However, this functionality is probably not in the LSP implementation for nothing. Therefore:

**Request**: A configuration option that allows me to turn off this result filtering and sorting. I don't know how granular this option should be, i.e. if it should be more than just one boolean. A logical option would seem to be two booleans: one to control exact-prefix-match filtering, and one to control sorting.

Thanks for the good work!

**Comment by mjlbach** [comment]
Haven't tested it, but can you check out #16102?

**Comment by mfussenegger** [comment]
> The completions are sorted.

Can you explain why removing that makes the completion results more useful? If the language server has some sort of scoring they would ideally populate the `sortText` property so that the client can utilize that order.

I don't think vscode provids the option to turn off ordering based on that - so I would be surprised if language server authors return results where the ordering of the results as they appear is better/more meaningful then the items ordered by `sortText`

**Comment by mjlbach** [comment]
Good news! This should be mitigated by https://github.com/haskell/haskell-language-server/issues/2291#event-5596119236

**Comment by tomsmeding** [comment]
Yeah I didn't test yet with the custom omnifunc, but with released neovim, sorting now works fine but I still need to disable the exact prefix matching.

Side not I don't like HLS's decision to make the first character case-sensitive, but that's not neovim's problem :p

**Comment by tomsmeding** [comment]
@mjlbach To be honest, I don't see the reason why neovim should do prefix filtering. Are there really incompetent language servers around for which such filtering is beneficial to the user, and in those cases, is it really neovim's task to do the filtering?

The sorting by `sortText` is specified and hence neovim should do this, because language servers may depend on it. But prefix filtering?

**Comment by mjlbach** [comment]
> Are there really incompetent language servers around for which such filtering is beneficial to the user, and in those cases, is it really neovim's task to do the filtering?

This predates my involvement with core (I was just a user back then), but I did comment on this issue with a similar result with pyls_ms (https://github.com/neovim/neovim/issues/11826)

This was added in https://github.com/neovim/neovim/pull/11895 (which I had tested at the time)

@hrsh7th, sorry for the ping, do you do prefix matching? What are your thoughts on dropping it from omnifunc?

**Comment by hrsh7th** [comment]
Most language server expects the client has supported the fuzzy matching.

But vim's omnifunc supports only `prefix matching` or `do not matching` (equal = 1).

So I think native omnifunc can't support this situation correctly.

**Comment by tomsmeding** [comment]
Hello again. :) I've been trying to navigate the various issues and PRs (transitively) linked from this one, and didn't find anything that looked like it solves this issue. Looking at the current source code on master, I find that the completion list is still unconditionally [filtered on the typed prefix](https://github.com/neovim/neovim/blob/5fc25ecc7a383a4bed2199774ed2e26022456ca3/runtime/lua/vim/lsp/completion.lua#L353-L354) (even if [using `matchfuzzy`](https://github.com/neovim/neovim/blob/5fc25ecc7a383a4bed2199774ed2e26022456ca3/runtime/lua/vim/lsp/completion.lua#L248)). However, I'm not familiar with the codebase, so I may well be missing something! Please point me in the right direction if some option of controlling prefix filtering does indeed exist.

Assuming such an option has not yet been added: are there language servers in use where filtering completion results in neovim _improves_ completion results, and where this is _not_ a bug in the language server? If there aren't, why does neovim filter completion items on a matching prefix?

**Comment by mfussenegger** [comment]
On master neovim uses fuzzy match for pre-filtering, and the subsequent filtering is either strict prefix or fuzzy, depending on your `completeopt` settings.

**Comment by tomsmeding** [comment]
Does this mean that if a language server decides that the input "abc" completes to "xyz", master neovim will still not show that completion (because it doesn't match the input at all)?

If so, why would neovim filter that completion out? Surely the language server had a reason to return "xyz".
