### ISSUE TITLE
change background color of nvim_open_win

### ISSUE THREAD

**Issue by bon-ami** [neovim/neovim#15416]
### Feature already in Vim?

No

### Feature description

Currently, the BG color of a nvim_open_win is magenta, at least for 'style': 'minimal', which I searched in the code but failed to find where magenta was set to use, instead of syntaxes and themes. If "set background=light", it is light magenta, I suppose.
I strongly hope this color can be customized. Thank you.

**Comment by matveyt** [comment]
Floating window has color of `NormalFloat` which is linked by default to `PMenu`. Refer to builtin help to know how the bits work... or just choose a different `colorscheme`.

**Comment by bon-ami** [comment]
yes. sorry for this. just found "darkblue" already sets it.

**Comment by bfredl** [comment]
for reference if anyone stumbles upon this: also see `help winhighlight`
