### ISSUE TITLE
Should/Could vim.lsp.diagnostic.show_diagnostics be a 'public' function?

### ISSUE THREAD

**Issue by IndianBoy42** [neovim/neovim#15443]
### Feature already in Vim?

No

### Feature description

This function, used by show_line_diagnostics and show_position_diagnostics is mentioned in the documentation but is not actually an exposed function, its fairly easy to write ourselves, but for consistency/ease it would be nice to just reuse the builtin function

**Comment by mjlbach** [comment]
No, this is an internal function.
