### ISSUE TITLE
LSP rust-analyzer panic

### ISSUE THREAD

**Issue by koopa1338** [neovim/neovim#15446]
### Neovim Version

NVIM v0.6.0-dev+164-g50b30de20

### Language server name/version:

rust-analyzer 199ebf1

### Operating system/version:

Arch Linux 5.13.12-arch1-1

### Checkhealth

```markdown
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.
  - INFO: html: configuration checked.
  - INFO: jdtls: configuration checked.
  - INFO: gopls: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: ocamlls: configuration checked.
  - INFO: yamlls: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: dockerls: configuration checked.
  - INFO: texlab: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: jedi_language_server: configuration checked.
```

### Steps to reproduce

- Open a rust project (e.g. ripgrep)
- use the lsp go to declaration function (`gD` key binding  in `minimal_init.lua`

### Expected behavior

Expected the lsp go to declaration function to work properly

### Actual behavior

- Error:
```
Error executing lua /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:461: bad argument #2 to 'format' (number expected, got nil)
 ```

### Link to uploaded log file

https://gist.github.com/koopa1338/ae340c8d579bdff9c7e122d98c2c374b

**Comment by mjlbach** [comment]
Can't reproduce with this container, works fine:

https://github.com/mjlbach/lsp-containers/tree/master/rust-analyzer

**Comment by koopa1338** [comment]
Can be closed, I already tried the rust-analyzer and rust-analyzer-git packages from my distro as well as neovim 0.5 branch but still got the same error. It seems like the version of the rust-analyzer packages are not working with the master branch atm. I installed the rust-analyzer from src and it works as it should.
