### ISSUE TITLE
Lua: expose mpack

### ISSUE THREAD

**Issue by hrsh7th** [neovim/neovim#15452]
### Feature already in Vim?

No.

### Feature description

Currently, neovim has msgpack module in testing environment.
I'm happy if it bundled as first class module in neovim like `luv`.

The reason is that maximize `luv` module's threading features.
Currently, `luv` can create thread but we can't pass some of the data between main thread and another thread.
So we should encode/decode data as string.

If we can encode/decode msgpack instead of string, it might be useful to make non-blocking plugin.

**Comment by bfredl** [comment]
`require'mpack'` should be builtin. We want to replace `libmsgpack-c` with `libmpack` anyway (and get rid of lot of small, unnecessary allocations surrounding RPC use).

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/5724

**Comment by shadmansaleh** [comment]
@bfredl, @hrsh7th  should be closed ?

**Comment by clason** [comment]
Neovim now has `vim.mpack` builtin (no need for `require`).
