### ISSUE TITLE
treesitter: Retrieving child languages trees is really slow

### ISSUE THREAD

**Issue by ddeville** [neovim/neovim#15461]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+155-g15b736d6e

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch linux

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

nightly from github

### How to reproduce the issue

I noticed that opening (large) files in nvim was fairly slow and since I wasn't able to reproduce the issue in vim I went down the rabbit hole of perf debugging.

As a test case I've been using the [parser file](https://github.com/tree-sitter/tree-sitter-c/blob/master/src/parser.c) from `tree-sitter-c` which is a nice simple C files containing 67k LOC.
Opening this file with nvim (simply running `time nvim tree-sitter-c/src/parser.c +qall`) takes 15+ seconds.

```
Executed in   15.61 secs    fish           external
   usr time   15.55 secs    0.00 micros   15.55 secs
   sys time    0.05 secs  729.00 micros    0.05 secs
```

After running the usual `--startuptime` and `:profile` in both nvim and vim, disabling and re-enabling all plugins independently, I realized that tree-sitter was the cause of said slowness when opening a new buffer.

Since I didn't really know where to start I opted for running `perf` and feeding it into `flamegraph`. The result was quite interesting (see [out.zip](https://github.com/neovim/neovim/files/7028919/out.zip) for the svg)

![image](https://user-images.githubusercontent.com/356759/130385096-b66a4bbe-de05-406c-bff2-38e175871321.png)

The tiny part at the top left is `parser_parse`, contributing to 0.94% of the run time which is roughly 150ms and is very similar to what I get parsing this file manually with `tree-sitter-cli`.

Since I wasn't sure where `query_next_match` was coming from I took a look at the source and realized that it's being called from [`_get_injections`](https://github.com/neovim/neovim/blob/c2a211b8e3e00dfae594ccbd9a107aef85a9919c/runtime/lua/vim/treesitter/languagetree.lua#L131) when creating the language tree. `_get_injections` creates a TS query from the [`injections.scm`](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/c/injections.scm) file for the language in order to look for embedded source in different languages in source file that could be parsed with a different TS language and appended to the language tree.
Turns out that this is really really slow, contributing 97.50% of the buffer load time.

Commenting out the part that get injections in `languagetree.lua` and recompiling nvim gives me a much more reasonable load time:

```
Executed in  368.50 millis    fish           external
   usr time  340.13 millis  363.00 micros  339.77 millis
   sys time   15.89 millis  203.00 micros   15.69 millis
```

### Expected behavior

I would expect tree-sitter parsing when loading a new buffer to be really fast, and in fact it is! (and it parses the entire file, unlike vim's regex parsing that usually gives up after a couple of screens).

### Actual behavior

However, running a query against the entire parsed tree to identify embedded source in different languages makes the overall TS file parsing waaaay too slow.

I understand that there is value in providing support for embedded languages, in particular for "web" languages that often use this, but for languages like C, Rust, etc, it's very much a nice to have for macros, preprocessor and the like but certainly does not warrant such a perf hit.

**Comment by ddeville** [comment]
cc @vigoux and @steelsojka. I've been thinking of how this could potentially be fixed but since I have no context about the current design and rationale for the injection feature in the TS language tree (and whether this is something that you are aware of and just haven't gotten a chance to look into), I thought I'd first ask here :)

**Comment by vigoux** [comment]
So so so, we actually know this issue from a while ago, and I am currently working on it (just not really finished yet).
So I am glad you reached out to us and reported the issue.

I have a little question though: do you have the `tree-sitter-comment` parser installed on your machine ? We already had performances issues with this one... But in any case, we need to get that fixed.

**Comment by ddeville** [comment]
Ah great, I’m really happy to hear!

> I have a little question though: do you have the tree-sitter-comment parser installed on your machine ? We already had performances issues with this one... But in any case, we need to get that fixed.

I do have it installed as part of `nvim-treesitter` yep. I tried uninstalling it but the loading time doesn’t seem impacted.

**Comment by vigoux** [comment]
Okay, good to know too, this means that our code is really badly written performance wise hehe.

**Comment by vigoux** [comment]
Really nice issue report btw.

**Comment by lewis6991** [comment]
There's been quite a few updates on HEAD and upstream. Can we get a status update using HEAD?
