### ISSUE TITLE
Odd interaction between 'wrapscan' and 'wildmode'

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#1546]
I'm noticing that when using `wildmenu` and `wildmode=full` (or any value including it), pressing `wildchar` to complete has different behavior in vim and nvim. For example, while vim does this

![captura de pantalla de 2014-11-25 13 09 16](https://cloud.githubusercontent.com/assets/221465/5186343/69cf81a0-74a4-11e4-9fdf-baa356295eec.png)

nvim does

![captura de pantalla de 2014-11-25 13 09 09](https://cloud.githubusercontent.com/assets/221465/5186342/69ce7c38-74a4-11e4-8ad4-483223e89b9f.png)

It takes 4 keypresses fot the completion candidates to appear in the statusline, and then the second item is selected:

![captura de pantalla de 2014-11-25 13 12 55](https://cloud.githubusercontent.com/assets/221465/5186393/c7f26b12-74a4-11e4-8e01-f6b4fa1fc973.png)

I'm using the same configuration for vim and nvim (see [here](https://github.com/fmoralesc/dotfiles/blob/master/.vimrc)). 

Oddly enough, the issue goes away if I reset the wildmenu value while nvim is running: 

![captura de pantalla de 2014-11-25 13 16 26](https://cloud.githubusercontent.com/assets/221465/5186484/4fd36752-74a5-11e4-974c-c1efe7ae923f.png)

**Comment by justinmk** [comment]
Does #1820 fix this?

**Comment by fmoralesc** [comment]
It does ;)

**Comment by fmoralesc** [comment]
However, it seems like the arrow keys are not working for navigating the wilmenu. I get `E394: No identifier under the cursor` for the `<Left>` arrow (like if `*` was pressed), `E164: There is only one file to edit` for `<Up>` (like with `:Next`), and `<Down>` and `<Right>` seem to send `<Escape>`.

**Comment by fmoralesc** [comment]
Fixed by #1820
