### ISSUE TITLE
Statusline jumps to the top of neovim and I'm unable to reset it

### ISSUE THREAD

**Issue by kdheepak** [neovim/neovim#15476]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+181-g5d633546b

### Vim (not Nvim) behaves the same?

VIM - Vi IMproved 8.2

### Operating system/version

macOS 10.15

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

Github Releases

### How to reproduce the issue

```
$ nvim lua/cmp_latex_symbols/init.lua
```

From here: https://github.com/kdheepak/cmp-latex-symbols/blob/main/lua/cmp_latex_symbols/init.lua

1. Paste this symbol `þ`
2. Copy this symbol to clipboard using `v"+y` or `V"+y`.

neovim ends up in the following state:

![neovim-statusline mov](https://user-images.githubusercontent.com/1813121/130656543-dde0ff73-e8f8-4baa-98d2-7a33c22c2131.gif)

The statusline jumps to the third line in the screen. It does not happen if I copy more than one line in this file or any other line in this file.

I'm using the following configuration:

https://github.com/kdheepak/dotfiles/tree/6b4b3424974286969169c11ad3e0e06037295e44/nvim

It does not happen with `neovim -u NORC`. It happens only when I use my local dotfiles configuration. I'll update this with a minimal working example when I get the time to put one together.

### Expected behavior

I would expect the statusline does not jump to the top of the screen.

### Actual behavior

Statusline jumps to the top of the screen as shown in the screenshot and gif above.

**Comment by ii14** [comment]
Whenever something like this happens you can do `:resize` or `<C-W>_` to reset window height back to default.

**Comment by kdheepak** [comment]
Thanks! Any idea what might be causing it though? I’m doing a bisect through my plugins to try to figure it out.

**Comment by justinmk** [comment]
bisect your plugins, provide minimal steps to reproduce without plugins.
