### ISSUE TITLE
Clipboard backend not using all registers

### ISSUE THREAD

**Issue by krishenm94** [neovim/neovim#15478]
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

not sure if can be compared

### Operating system/version

Manjaro Linux x86_64 5.10.59-1-MANJARO 

### Terminal name/version

xfce4-terminal 0.8.10

### $TERM environment variable

xterm-256color

### Installation

System package manager (pacman)

### How to reproduce the issue

in terminal:
`sudo pacman -Syyu xclip neovim`

in `.config/nvim/init.vim`:
`set clipboard+=unnamedplus`

in nvim
`:checkhealth` clipboard ok and registers xclip
`:reg` 

### Expected behavior

System clipboard should use all the registers in nvim

### Actual behavior

System clipboard only uses `" `and `+` registers.

**Comment by krishenm94** [comment]
![Screenshot_2021-08-25_08-13-18](https://user-images.githubusercontent.com/52146997/130706017-225317b9-cc47-4e06-9106-ca57a65e6132.png)

**Comment by krishenm94** [comment]
Doing `nvim --clean` then `:set clipboard+=unnamedplus` doesn't seem to fix the issue. So I don't think it's my config at least.

I've also tried reinstalling `xclip` and `neovim` to no avail.

**Comment by krishenm94** [comment]
I rebooted now, the errors are reoccuring. All I've done is `:reg`

![image](https://user-images.githubusercontent.com/52146997/130707117-a797ccba-df07-4bf8-8ea2-35efb6590023.png)

**Comment by gpanders** [comment]
Related https://github.com/neovim/neovim/issues/15350

**Comment by krishenm94** [comment]
https://github.com/neovim/neovim/issues/14967#issuecomment-873381423

I've applied the following fix to fix nvim's error handling of this issue. It's not on release and it's a one liner so I made the change locally.

The root error still remains i.e. `clipboard: error: Error: target STRING not available`. But it seems it might be an `xclip` issue. I'd appreciate any links to fixes

**Comment by justinmk** [comment]
> The root error still remains i.e. `clipboard: error: Error: target STRING not available`. But it seems it might be an `xclip` issue.

yep

**Comment by hackerb9** [comment]
@justinmk What is the desired behavior for xclip in the situation where neovim asks for a string and one is not available? Should it be changed to not say anything and just return an error code?
