### ISSUE TITLE
Moving to a fold with a 'gk' and then opening fold lands you on last line of fold

### ISSUE THREAD

**Issue by jghauser** [neovim/neovim#15490]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+182-ga373ca1d8

### Vim (not Nvim) behaves the same?

yes, vim 8.2.2891

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

AUR

### How to reproduce the issue

1. Save the following as test.txt:
```
{{{

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

}}}
{{{

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

}}}
```
2. Open the file with `nvim -u NORC test.txt` or `nvim -u NONE text.txt`
3. Run `:set foldmethod=marker`
4. Move to bottom with `G`
5. Move up with `gk`
6. Open fold with `zo`

### Expected behavior

The cursor should (just as when moving up with `k`) be on the first line of the fold.

### Actual behavior

The cursor is on the last line of the fold.

**Comment by jghauser** [comment]
Unfortunately, I don't have easy access to a computer with a different operating system. I'll try in the next days and will report back when I do!

**Comment by jghauser** [comment]
It only happens with `wrap` enabled. Do you maybe have it set to `nowrap`?

**Comment by justinmk** [comment]
@jghauser can you verify that the settings are the same in vim and nvim. compare the output of:

    :set

(ignore the 'runtimepath' part)

**Comment by jghauser** [comment]
I finally got around to checking this. Running `vim -u DEFAULTS` and `nvim -u NONE` have slightly different settings, though I don't think these should have an impact. Here's what I get with `:set`

nvim:
```
--- Options ---
  columns=106         lines=58            scroll=28
  helplang=en       noloadplugins         window=57
  fileencoding=utf-8
```

vim:
```
--- Options ---
  background=dark     history=200         mouse=a             showcmd             ttymouse=sgr
  commentstring=      incsearch           nrformats=bin,hex   syntax=text         wildmenu
  display=truncate    langnoremap         ruler               ttimeout
  filetype=text     nolangremap           scroll=28           ttimeoutlen=100
  helplang=en       noloadplugins         scrolloff=5         ttyfast
  backspace=indent,eol,start
  comments=fb:-,fb:*,n:>
  fileencoding=utf-8
  fileencodings=ucs-bom,utf-8,default,latin1
```

Should I create a minimal init.vim/vimrc to try to force them both to the same settings?

**Comment by clason** [comment]
`nvim -u NONE` skips _all_ plugins, even the builtin ones; if you want to have a guaranteed "factory defaults" Neovim, you have to use a minimal `init.vim` where you `set runtimepath=$VIMRUNTIME` and `set packpath=` to skip any plugins or packages you might have in your local config.

So, yes, a minimal `init.vim` would be good.

**Comment by jghauser** [comment]
Ok, I created such a init.vim and used it as the config for both vim and nvim. There are still some differences, but only very few. If I start vim with `vim -u DEFAULTS`, the differences are quite a bit more substantial (as you can see above). Let me know if I should narrow them down even further.

nvim:
```
--- Options ---
  columns=106         filetype=text       helplang=en         packpath=           syntax=text
  commentstring=      foldmethod=marker   lines=58            scroll=28           window=57
  comments=fb:-,fb:*,n:>
  fileencoding=utf-8
```

vim (with -u init.vim):
```
--- Options ---
  foldmethod=marker   packpath=           ttyfast
  helplang=en         scroll=28           ttymouse=xterm
  fileencoding=utf-8
  fileencodings=ucs-bom,utf-8,default,latin1
```

The bug still occurs in the exact same fashion in both vim and nevoim.

**Comment by luukvbaal** [comment]
So was a vim issue ever opened for this? My initial (reverted) [commit](https://github.com/neovim/neovim/commit/49ab10414789e9fd36464cc9818faaf065cda9dc) #2242 would fix this.

**Comment by jghauser** [comment]
I never opened an issue on vim, not sure if anyone else did.
