### ISSUE TITLE
q doesn't quit nvim as Manpager

### ISSUE THREAD

**Issue by LamprosPitsillos** [neovim/neovim#15506]
### Neovim version (nvim -v)

NVIM v0.5.0 Build type: Release LuaJIT 2.0.5

### Vim (not Nvim) behaves the same?

Vim says there is no cmd "Man!"

### Operating system/version

Artix Linux x86_64 , 5.13.12-artix1-1

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

Pacman

### How to reproduce the issue

```bash
echo "vim.cmd [[ syntax on ]]" > init_test.lua
man ls | nvim -u ./init_test.lua +Man!
```
I debugged my config and narrowed down to this one setting causing this problem.

### Expected behavior

`q` to quit nvim  . 
```man
q                         :quit if invoked as $MANPAGER, otherwise :close.
```

### Actual behavior

`E444: Cannot close last window `

__workaround__

```man
g:no_man_maps             Do not create mappings in manpage buffers.
# set to 1
```
and export pager as follows:
```bash
export MANPAGER="nvim -c \"map q :quit<cr>\" +Man!"   
```

**Comment by gpanders** [comment]
I can't reproduce this. I have

```bash
export MANPAGER='nvim +Man!'
```

and `q` closes Nvim as expected.

**Comment by justinmk** [comment]
Also works fine for me with `MANPAGER= man ls | nvim -u ./init_test.lua '+Man!'`.

@LamprosPitsillos try latest master, there were changes to man.vim: https://github.com/neovim/neovim/commit/2548a9e18037339c4c502d971bdeaf909b82a739
