### ISSUE TITLE
`set spell` emits a warning

### ISSUE THREAD

**Issue by jwhitley** [neovim/neovim#1551]
A `.nvimrc` with `set spell` or `set spelllang=[...]` emits a warning and enter prompt at startup.

### Repro steps

0) Install neovim via the homebrew formula (from the new tap repo).

1) Put the following in a file `.nvimtest`
```
set spell
set spelllang=en_us
```

2) Run `nvim -u .nvimtest`

### Expected result

neovim starts without warnings.

### Actual result

```
>> nvim -u .nvimtest
Warning: Cannot find word list "en.utf-8.spl" or "en.ascii.spl"
Warning: Cannot find word list "en.utf-8.spl" or "en.ascii.spl"
Press ENTER or type command to continue
```

### Notes

It appears that spelling files in vim's repo don't exist in neovim's repo.  E.g., in vim's repo:

```
>> find -name '*.spl'
./runtime/spell/en.ascii.spl
./runtime/spell/en.latin1.spl
./runtime/spell/en.utf-8.spl
```

Likewise, these files are installed as part of a vim installation (e.g. in vim's Homebrew formula).  No such `*.spl` files exist in neovim/neovim, nor are they installed by the brew formula.

Possibly related to #356, but that issue appears to have been closed without action taken to remove spell.c.

**Comment by xu-cheng** [comment]
This can be closed. https://github.com/neovim/neovim/pull/1990 fixed it.

**Comment by dbarnett** [comment]
@xu-cheng @justinmk I don't think it's actually fixed. I just updated and still see `Warning: Cannot find word list "en.utf-8.spl" or "en.ascii.spl"`, and I don't see any way the change in #1990 would have fixed the issue here.

**Comment by xu-cheng** [comment]
@dbarnett. It did fix the problem for me. Do you enable vim view? It's always good to clean the caches created by vim.

**Comment by dbarnett** [comment]
What do you mean by "enable vim view"?

I tried a few different configurations but anything with `set spell` in .nvimrc gives me the error. For example, I get the error with `nvim -u NONE -c 'set spell'`. I'm running neovim a06186de41, BTW.

**Comment by xu-cheng** [comment]
> What do you mean by "enable vim view"?

I mean something like [this](https://github.com/vim-scripts/restore_view.vim).

>  I get the error with nvim -u NONE -c 'set spell'

I found I got the same error. It turns out that [this plugin](https://github.com/reedes/vim-wordy) fixes my problem.

So I disable the plugin vim-wordy and run `set spell` in the neovim. It will ask me whether to download en.utf-8.spl file. After that, everything is smooth. Therefore, problem is indeed solved.

**Comment by justinmk** [comment]
I don't know what is prompting to download the spell file, but whatever it is, we should think about including it.

**Comment by xu-cheng** [comment]
Like this:
![](http://cl.ly/image/2X321b1I2z1L/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-03-06%20%E4%B8%8B%E5%8D%8811.18.32.png)

**Comment by justinmk** [comment]
Huh. I guess it's built-in. Perhaps we should point it to a github repo though.

**Comment by dbarnett** [comment]
@xu-cheng Oh, no I don't use vim sessions. This prompting and downloading isn't happening for me, I guess because `set spell` in your vimrc happens too early and it doesn't try to do anything interactive?

Also, like jwhitley I symlink `.nvimrc->.vimrc` and `.nvim/->.vim/`. If nvim is downloading local copies of spell files that vim already has, I assume they'll just be updated versions and vim will use those fine?

**Comment by xu-cheng** [comment]
I think you should not put `set spell` in the `.nvimrc`. Instead, you should run `:set spell` manual in the first time. After it's downloaded, you can add `set spell` in the `.nvimrc`.

**Comment by dbarnett** [comment]
That's going to bite a lot of people since it never used to be an issue. I would never have guessed that running `:set spell` interactively is the solution; the error doesn't give any suggestion like that and it's pretty unusual for the solution to "file missing" issue to be "try again". It will also happen every time a user moves their nvimrc to a new machine.

**Comment by justinmk** [comment]
> That's going to bite a lot of people since it never used to be an issue

We can adjust that so it prompts on startup. I'm just happy this feature is already built-in; it means we don't need to dump these files into the master repo, and we don't need to build a plugin (which was my original thought).

**Comment by kenorb** [comment]
Related: [Warning when opening commit message with Neovim](http://vi.stackexchange.com/questions/2514/warning-when-opening-commit-message-with-neovim)

**Comment by DAddYE** [comment]
When I do `set spell`:

```
:set spell
Cannot find spell file for "en" in utf-8
Do you want me to try downloading it?

Downloading en.utf-8.spl...
Error detected while processing function spellfile#LoadFile..spellfile#Nread:
line   13:
E117: Unknown function: netrw#SavePosn
Could not find it, trying en.ascii.spl...
E117: Unknown function: netrw#SavePosn
Sorry, downloading failed
1 buffer wiped out
Warning: Cannot find word list "en.utf-8.spl" or "en.ascii.spl"
Press ENTER or type command to continue
```

**Comment by anzellai** [comment]
Since having the same frustration as many here do, I try out NeoVim today and have come across the same `spell` warning issue which leads me here, and in fact after `:set spell` and editing the `.nvimrc` and include `set spell` this warning has gone away.

**Comment by tiagoboldt** [comment]
Update on this: I'm using the HEAD version. First time I opened a file which used `set spell`, I had the issue described above. Continuing through data, I've issued a `:set spell` and nvim downloaded the required files. No more warnings were issued from then on.

**Comment by Goddard** [comment]
I still get this error using latest Unstable Neovim on Ubuntu 14.04

**Comment by justinmk** [comment]
@Goddard If you `:set spell`, do you get a prompt? Did you answer "yes" to the prompts?

**Comment by sesselastronaut** [comment]
Doesn't work for me either as  ':setlocal spell spelllang=en_gb' results in 'Warning: Cannot find word list "en.utf-8.spl" or "en.ascii.spl"'. I've my nvim directory as a symbolic link following the set up commands from the docs: "mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
 ln -s ~/.vim $XDG_CONFIG_HOME/nvim
 ln -s ~/.vimrc $XDG_CONFIG_HOME/nvim/init.vim"

**Comment by gianarb** [comment]
Hello

I have this problem

<img width="1267" alt="screen shot 2016-08-21 at 12 36 06" src="https://cloud.githubusercontent.com/assets/1630267/17836710/ed152dd0-679b-11e6-8ccc-fe30b92e7b84.png">

Why is nvim trying to download spell file in `/var/folders/15`?
I am using Mac 10.10.5
Thanks

**Comment by justinmk** [comment]
@gianarb that path is generated by `tmpname()`. Usually on macos `/tmp` is a symlink, perhaps you can check that.

**Comment by gianarb** [comment]
Hello @justinmik you are right my `tmpname()` is `/var/folder/15/` do you have an idea about how change this patch I am looking on google but I can not find a good solution

**Comment by justinmk** [comment]
> do you have an idea about how change this patch

What patch? If the downloaded `1.spl` file isn't readable, there must be some environment (or permissions) problem. Did you check the contents of the file at the path in your screenshot?

**Comment by gianarb** [comment]
Yes @justinmk it's not writable from my user `var/folder/15`.. but right know I am trying to understand why `tmpname` is `/var/folder/15`
Thanks a lot

**Comment by justinmk** [comment]
What does `ls -ld /tmp` say? And `echo $TMPDIR` ?

**Comment by gianarb** [comment]
```
Gianlucas-MacBook-Pro:~ gianlucaarbezzano$ ls -ld /tmp
lrwxr-xr-x@ 1 root  wheel  11  9 Jan  2016 /tmp -> private/tmp
```

```
Gianlucas-MacBook-Pro:~ gianlucaarbezzano$ echo $TMPDIR
/var/folders/15/r96rbkf92_zdnhfg2tk4wwm80000gn/T/
```
Ok there is something strange in my environment.. :)

**Comment by justinmk** [comment]
I don't think it's strange, it is normal. Compare this in Vim and Nvim:

    :echo tempname()

The path is irrelevant. If you can't write to it, yes, there's a problem with your environment.

**Comment by gianarb** [comment]
Ok thanks a lot! :)

**Comment by troubas** [comment]
I also got the message when starting nvim with `set spell` in my `.nvimrc`. 

When pressing yes during startup nvim started and the message was back on the next start. 
However when I started nvim and then entered `:set spell` and answered the prompt with yes the spellfiles `en.utf-8.spl` and `en.utf-8.sug` got downloaded to my local spell folder and as a restult the error disappeared.

I consider this wierd behaviour because I didn't even set the spelllang to en. However in order to get rid of the annoying startup message this seems to be a way.

**Comment by justinmk** [comment]
@troubas What `:version` ?

**Comment by troubas** [comment]
Yeah sorry. Just realized I was using the arch package...
After building from source the first prompt on startup properly downloaded the spell files. 
I'm still not sure why they are needed but I suppose it has its reasons.

**Comment by razor-x** [comment]
The way I fixed this on Arch:

Arch provides vim-spell packages which are normally loaded by vim and provide the missing spell files. I just syslinked to these so updates are handled by pacman. Ideally neovim would load these directly or provide it's own spell packages.

```
if ! [[ -h $HOME/.local/share/nvim/site/spell ]]; then
  mkdir -p $HOME/.local/share/nvim/site
  if [[ -d /usr/share/vimfiles/spell ]]; then
    ln -s /usr/share/vim/vimfiles/spell $HOME/.local/share/nvim/site/spell
  fi
fi
```
