### ISSUE TITLE
Terminal mode should soft-wrap lines, not hard-wrap

### ISSUE THREAD

**Issue by mortie** [neovim/neovim#15511]
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

No (Vim's terminal mode has no relation to neovim's afaik)

### Operating system/version

macOS 11.5.2

### Terminal name/version

iTerm2 3.4.8

### $TERM environment variable

xterm-256color

### Installation

HomeBrew

### How to reproduce the issue

Run a command which produces output with long lines

### Expected behavior

The lines should be soft-wrapped; I should be able to select lines and copy them without newlines, I should be able to resize nvim, and the terminal output should just in general behave as if the lines from the running program aren't hard-wrapped

### Actual behavior

The lines are hard-wrapped, so resizing vim doesn't work correctly, selecting and copying lines also copies the newlines which weren't present in the program output, etc.

**Comment by justinmk** [comment]
totally https://github.com/neovim/neovim/issues/2514
