### ISSUE TITLE
RPC: Can't open a file if file path contains less-than sign

### ISSUE THREAD

**Issue by alopatindev** [neovim/neovim#15512]
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

There's no standard RPC in vim as far as I know

### Operating system/version

GNU/Linux

### Terminal name/version

xterm 351

### $TERM environment variable

screen

### Installation

Gentoo Portage

### How to reproduce the issue

```
nvim --listen /tmp/1.sock
```

In another terminal:
```
$ echo 1 > '/tmp/<'
$ pip3 install --user neovim-remote
$ nvr --servername '/tmp/1.sock' --remote-send '<esc>:e /tmp/\<<cr>'
```

### Expected behavior

Should run `:e /tmp/\<` and open the file

### Actual behavior

Neovim shows unfinished command `:e /tmp/\`

**Comment by justinmk** [comment]
nvr is not part of neovim, but anyway... `--remote-send` is implemented via `nvim_input`:

https://github.com/mhinz/neovim-remote/blob/2279ef2da1ef1388cbad57f9a8d86484fad1934c/bin/nvr#L230-L231

`:help nvim_input()` : 

> Note:
> |keycodes| like <CR> are translated, so "<" is special. To
> input a literal "<", send <LT>.
