### ISSUE TITLE
win_set_option sets global option value in addition to local value

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#15529]
### Neovim version (nvim -v)

NVIM v0.5.0

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Ubuntu 21.04

### Terminal name/version

Konsole 20.12.3

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

```vim
nvim -u NORC
:setglobal foldlevel=1
:call nvim_win_set_option(0, 'foldlevel', 3)
:setglobal foldlevel?
```

### Expected behavior

My expectation was that `nvim_win_set_option` would only set the _local_ option value for the specified option, `foldlevel`, resulting in the global option value remaining `1` in the example above. This would be similar to how `nvim_buf_set_option` works, where only the local option is set, and `nvim_set_option` could be used to set the global value.

### Actual behavior

`nvim_win_set_option` sets both the global and local values for the specified options, resulting in an output of `3` for the example above. This seemingly prevents usage of the Neovim API for _only_ setting the local value for a window-local option.

That is, `nvim_win_set_option` appears to match the behavior of using `set` (or both `setglobal` and `setlocal`), whereas `nvim_buf_set_option` appears to match the behavior of using `setlocal`.

### Additional information

A similar issue occurs when using `vim.opt_local` in Lua in place of the Neovim API. This is reported in https://github.com/neovim/neovim/issues/15531.

**Comment by gpanders** [comment]
I can reproduce this and can confirm that it only happens with "local to window" options.

**Comment by dstein64** [comment]
Thanks @gpanders!

I'll close this ticket, since the behavior is intentional.

> "So I think vim.opt_local is actually doing the right thing and :setlocal is in the wrong in this case."

The behavior of `:setlocal` matches what's described in `:help local-options`. The example uses `'list'` (as opposed to `'number'` in the running example here).

Perhaps https://github.com/neovim/neovim/issues/15531 should be kept open, since there is a mismatch between what's in the documentation and the behavior. That is, the documentation says that "in any of the above examples, to replicate the behavior `setlocal`, use `vim.opt_local`", which is not true for the first example (`set number`). If the behavior is intended there too, then the issue would be intended for the documentation.
