### ISSUE TITLE
lsp: vim.lsp.util.parse_snippet can't parse snippet correctly

### ISSUE THREAD

**Issue by hrsh7th** [neovim/neovim#15522]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

No.

### Operating system/version

MacOS 11.5

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```
nvim -u NONE
:lua print(vim.lsp.util.parse_snippet('aiueo${0}'))
```

### Expected behavior

Print `aiueo`

### Actual behavior

Print `aiueo$`

**Comment by clason** [comment]
I don't think snippet expansion is (fully) implemented in core yet:
https://github.com/neovim/neovim/blob/4e66e74fd7c6afb1813c40dd59f17091e546789d/runtime/lua/vim/lsp/util.lua#L567-L569

**Comment by clason** [comment]
There have been discussions about adding minimal(!) support for that in core in a way that allows more full-featured snippet plugins to hook into and override it (https://github.com/neovim/neovim/projects/9#card-61635953).

**Comment by hrsh7th** [comment]
I thought `vim.lsp.util.parse_snippet` could remove placeholders correctly at least.

If we implement a minimal snippet engine, I think `parse_snippet` should return AST so it is another discussion, I think.

**Comment by clason** [comment]
Right, I understand now.

But are you sure that's valid syntax? According to the [LSP spec](https://microsoft.github.io/language-server-protocol/specification#snippet_syntax), a placeholder can either be `$0` or `${0:foo}` -- it doesn't mention the "mixed" form `${0}`.

**Comment by hrsh7th** [comment]
Yes. The LSP spec seems to define the `tabstop` as `tabstop ::= '$' int | '${' int '}'`

**Comment by clason** [comment]
Yep, that's a bug then. PR welcome :)

**Comment by hrsh7th** [comment]
Yes. I can fix the snippet parsing and text edit behavior (maybe!).

**Comment by mjlbach** [comment]
One nice step towards snippets support in core might be defining a common "AST"/parsed structure that @hrsh7th and @L3MON4D3 could both leverage for their respective snippets plugins :)

**Comment by hrsh7th** [comment]
I think we should use `lpeg` to parse snippet.
I'm trying implement by it but it's too difficult for me 🤣

**Comment by clason** [comment]
In the Luasnip chat, there was talk about using the parser from https://github.com/archseer/snippets.nvim/blob/master/lua/snippet/parser.lua for LSP snippets, which looks self-contained and fairly robust. Maybe including this in core would make sense?

**Comment by hrsh7th** [comment]
The parser is based on my parser ( https://github.com/hrsh7th/vim-vsnip/blob/master/autoload/vsnip/snippet/parser.vim )

I wrote a parser to learn a parser combinator.
So It's not an advanced implementation and I'm not confident in its performance.

If using lpeg is not an overkill, I personally think it's better to use it.

(google translated)

**Comment by hrsh7th** [comment]
However, that the parser is minimal and can parse correctly. So I don't think we should avoid it.

**Comment by clason** [comment]
*woops* ;)

Well, then if _you_ say we should use `lpeg` instead of that, then that's a strong argument.

An alternative would be to leverage tree-sitter for it -- the grammar for LSP snippets shouldn't be complex, and that would allow running a tree-sitter query for each expansion (which may be more performant than working with regex?)

> However, that the parser is minimal and anyway can parse correctly. So I don't think we should avoid it.

I like both these things ("minimal" and "correctly"...) So one option could be to use that for 0.5.x (since getting LSP snippets parsed correctly arguably counts as a bugfix), and replace it with a tree-sitter implementation for 0.6.x?

**Comment by hrsh7th** [comment]
I think lpeg is fastest in current candidates (maybe. I didn't benchmark it) but the tree-sitter way is interesting!

I will try lpeg a bit then I will implement minimal parser for now if it is still difficult for me.

**Comment by clason** [comment]
Only thing to keep in mind is that `lpeg` may not be available on all platforms (for example, `homebrew` builds neovim without it), so this would be an external requirement for many users.

**Comment by hrsh7th** [comment]
Ah. I have overlooked it. Sorry. Hm... In that case, We might have to implement a minimal version.

**Comment by clason** [comment]
I'm not saying that needs to stop us -- after all, distributions change the upstream build at their own peril (if a core functionality is broken in their build, that's _their_ problem, not ours) -- just something to keep in mind (and give packagers who follow the neovim repo a heads-up).

**Comment by leiserfg** [comment]
I did some minor changes to the parser from archseer to handle the regex  correctly ( it didn't work well with regexes including '\/' ,
https://github.com/leiserfg/LuaSnip/blob/parser_combinator/lua/luasnip/loaders/parser.lua  although I also think having a faster lib to do the work (lpeg or treesitter) will be better.

**Comment by mjlbach** [comment]
I don't have a strong preference, is it actually feasible to write a treesitter grammar for snippets? I think that would be lower activation energy than bundling lpeg.

**Comment by hrsh7th** [comment]
I'm trying to port it.

**Comment by hrsh7th** [comment]
Orogonal version supports escape sequence https://github.com/hrsh7th/vim-vsnip/blob/master/autoload/vsnip/parser/combinator.vim#L27

**Comment by leiserfg** [comment]
The only issue with using treesitter that I can see is that it returns ranges of text instead of the string values, which is pretty good in terms of performance but requires a second pass over all the ranges in order to remove escaped characters (when it applies) like when parsing placeholders one need to replace the `\}` with `}` accordingly.
