### ISSUE TITLE
defaults: enable mouse support

### ISSUE THREAD

**Issue by matveyt** [neovim/neovim#15521]
### Feature already in Vim?

No

### Feature description

Set default to `set mouse=ar`

**Comment by gpanders** [comment]
I don't think this should be a default. See the discussion [here](https://github.com/tpope/vim-sensible/issues/152) for some background.

**Comment by justinmk** [comment]
We had this enabled but later reverted it. We can address most of the objections by:

- mapping `<A-leftmouse>` to "escape" mouse-mode
- mapping `<rightmouse>` to open a menu with copy/paste/etc (things people expect from their terminal)
    - ideally this would be driven by `:menu`. https://github.com/neovim/neovim/issues/12727#issuecomment-907880785
    - `mousemodel=popup` https://github.com/neovim/neovim/issues/14921

**Comment by justinmk** [comment]
With https://github.com/neovim/neovim/pull/19170 there is now zero reason not to enable mouse by default. (see above)

**Comment by justinmk** [comment]
# Resolution

- Oceania has always been at war with Eastasia. Nvim has always enabled 'mouse' by default.
- https://github.com/neovim/neovim/pull/6022 temporarily disabled 'mouse' with the intention of re-enabling it after we had a full answer for users who were used to the old behavior.
- The full answer is now provided by https://github.com/neovim/neovim/pull/19290 , specifically:
    - `:set mouse=nvi`
    - Pressing ":" (to enter cmdline-mode) temporarily _disables mouse_. Try it.
    - Right-click shows a popup menu with: `Cut`, `Copy`, `Paste`, `Disable mouse`
        - The `Disable mouse` item shows `:help default-mouse` which explains how to disable mouse permanently.

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open an issue if you have new information/topics to discuss._
