### ISSUE TITLE
:help restore-cursor advice doesn't work in git commits

### ISSUE THREAD

**Issue by dimbleby** [neovim/neovim#15536]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+205-g9695691ee

### Vim (not Nvim) behaves the same?

No, 8.1.2269

### Operating system/version

Ubuntu

### Terminal name/version

wsltty

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

init.vim:
```
" Restore cursor position {{{2
augroup RestoreCursor
    autocmd!
    autocmd BufReadPost *
      \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
      \ |   exe "normal! g`\""
      \ | endif
augroup END
```
make a git commit, leave the cursor on something other than the first line.
make a second git commit

### Expected behavior

Cursor should be in top left in git commit editor.

### Actual behavior

Cursor is where you left it in the previous commit.

The autocmd is taken from `:help restore-cursor`

Works as expected in vim.

Does neovim do things in a different order eg maybe the filetype is set after that autocmd fires?

**Comment by gpanders** [comment]
Yes, this happens because the `BufReadPost` autocommand in your init.vim is defined before the `FileType` autocommands in `filetype.vim`, which are loaded after `init.vim`.

Eventually we plan to make this autocommand one of the default autocommands provided by Neovim, which *will* be created after the `FileType` autocommands, which will solve this.

**Comment by dimbleby** [comment]
is there somewhere else I should put this autocmd?  Should the docs be updated to say so?

**Comment by gpanders** [comment]
> Eventually we plan to make this autocommand one of the default autocommands provided by Neovim, which will be created after the FileType autocommands, which will solve this.

In the meantime, you can use this instead:

```vim
autocmd! BufRead * autocmd FileType <buffer> ++once if &ft !~# 'commit\|rebase' | exec 'silent! normal! g`"' | endif
```

> is there somewhere else I should put this autocmd?

As an alternative to the above, you could also use the original autocommand defined in a plugin file (e.g. `~/.config/nvim/plugin/restore-cursor.vim`). These are sourced after `filetype.vim`.

**Comment by dimbleby** [comment]
thanks, I'll try one or more of those!

Is the deviation from vim intentional?

**Comment by gpanders** [comment]
No. Neovim sets `:filetype plugin indent on` by default, but this is done after the user's startup script.

You could replicate this behavior in Vim if you put `:filetype plugin indent on` at the end of your `~/.vimrc` (which is functionally what Neovim does).

**Comment by justinmk** [comment]
You can workaround this by putting `:filetype plugin indent on` at the top of your config. Nvim will skip its own attempt after that.

**Comment by ericvw** [comment]
Would `BufEnter` be better than `BufRead` to use the original auto command logic? It appears that `&ft` is set by when `BufEnter` is triggered. @justinmk, if you think this is worthwhile, I'll be happy to contribute a PR for the change.
