### ISSUE TITLE
Confirmation and improvement regarding neovim-git in MPR (makedeb Package Repository)

### ISSUE THREAD

**Issue by onlyvip** [neovim/neovim#15539]
I have tried to get neovim-git in mpr.
I am asking if the pkgbuild is proper and sufficient or have I missed something which you would want me to be added? 
Any help and suggestions are appreciated
Here's the link
[neovim-git](https://mpr.hunterwittenborn.com/packages/neovim-git/)

**Comment by justinmk** [comment]
https://mpr.hunterwittenborn.com/cgit/aur.git/tree/PKGBUILD?h=neovim-git

> makedepends=('ninja-build' 'gettext' 'libtool' 'libtool-bin' 'autoconf' 'automake' 'cmake' 'g++' 'pkg-config' 'unzip' 'curl')

should Lua be in there somewhere?

> _commits=$(git rev-list --count HEAD | sed 's:-:.:g') # total commits is the most sane way of getting incremental pkgver

Note that `nvim --version` is generated from `git describe` normally, but idk what the precise requirements are for MPR.

> url="https://github.com/neovim/neovim"

Should it be https://neovim.io/ ?

@jamessan likely has better insight.

**Comment by onlyvip** [comment]
> https://mpr.hunterwittenborn.com/cgit/aur.git/tree/PKGBUILD?h=neovim-git
> 
> LGTM, @jamessan likely has more insight.
> 
> > makedepends=('ninja-build' 'gettext' 'libtool' 'libtool-bin' 'autoconf' 'automake' 'cmake' 'g++' 'pkg-config' 'unzip' 'curl')
> 
> should Lua be in there somewhere?
> 
> > _commits=$(git rev-list --count HEAD | sed 's:-:.:g') # total commits is the most sane way of getting incremental pkgver
> 
> Note that `nvim --version` is generated from `git describe` normally, but idk what the precise requirements are for MPR.
> 
> > url="https://github.com/neovim/neovim"
> 
> Should it be https://neovim.io/ ?

1. added the following as depends() 
`depends=('libluajit-5.1-2' 'libluajit-5.1-common' 'libmsgpackc2' 'libtermkey1' 'libunibilium4' 'libvterm0' 'lua-luv')`
2.  this manner of version fetching is saner i think. if you feel like i can improve please tell how exactly.
3. changed the url. 
Thanks. do tell if anything else is missing

**Comment by jamessan** [comment]
>     3\. i cant find any documentation for all the relevant dependencies thats why lua got skipped i suppose

By default, just running `make` will build the dependencies for you.  If you're intending to use the packaged dependencies, then you need to build differently.  That also explains why you didn't see any problems.

You may want to reference the existing Debian packaging for that.

* [Dependencies](https://salsa.debian.org/vim-team/neovim/-/blob/d5a8e5982b8ec9789f6a828d1fd4acbb439e02df/debian/control#L6-34), annotated according to the relevant platform needs and whether they're only used for tests (which you're currently not running)
* [CMake build](https://salsa.debian.org/vim-team/neovim/-/blob/d5a8e5982b8ec9789f6a828d1fd4acbb439e02df/debian/rules#L52) command (indirected through debhelper's cmake buildsystem helper, so the common cmake switches aren't shown)

**Comment by onlyvip** [comment]
> > ```
> > 3\. i cant find any documentation for all the relevant dependencies thats why lua got skipped i suppose
> > ```
> 
> By default, just running `make` will build the dependencies for you. If you're intending to use the packaged dependencies, then you need to build differently. That also explains why you didn't see any problems.
> 
> You may want to reference the existing Debian packaging for that.
> 
> * [Dependencies](https://salsa.debian.org/vim-team/neovim/-/blob/d5a8e5982b8ec9789f6a828d1fd4acbb439e02df/debian/control#L6-34), annotated according to the relevant platform needs and whether they're only used for tests (which you're currently not running)
> * [CMake build](https://salsa.debian.org/vim-team/neovim/-/blob/d5a8e5982b8ec9789f6a828d1fd4acbb439e02df/debian/rules#L52) command (indirected through debhelper's cmake buildsystem helper, so the common cmake switches aren't shown)

oh i just noticed that lus-system, lua-say, lua-filesystem, lua-coxpcall, lua-cliargs, lua-dkjson,  lua-luassert, lua-term, lua-mediatorlua-argparse,  lua-coxpcall
if are not mentioned as dependencies and thus if are not installed get checked and installed by make. so, regarding this,
1. what if i keep the build process limited to make? that would be better as it would fetch lua dependencies in a better way. so i dont intend to use cmake if make gets the job done as intented.
2. should i add these dependencies in the current build or not, 
`lua-filesystem lua-cliargs lua-system lua-dkjson lua-say lua-luassert lua-term lua-mediator lua-argparse lua-coxpcall lua-love`

**Comment by jamessan** [comment]
>     1. what if i keep the build process limited to make?

That depends on what the requirements are for MPR.  For Debian, reaching out to the network to download and build dependencies during the package is completely forbidden.  Everything must be built using packaged software.

Note that make can also be used to build without the bundled dependencies, but I explicitly use CMake in the Debian package because it's simpler to pass arguments directly to CMake rather than through make variables.

**Comment by onlyvip** [comment]
> That depends on what the requirements are for MPR. 

Mpr has no requirement as such. It's like aur as a central repository but for debian checkout [this ](https://docs.hunterwittenborn.com/makedeb/makedeb-package-repository/intro)

>For Debian, reaching out to the network to download and build dependencies during the package is completely forbidden. Everything must be built using packaged software.


I'm sorry but, what do you mean by this can you make it easier to understand?

**Comment by onlyvip** [comment]
> With neovim, running just plain `make` will download the required dependencies from the internet and build them. That is not allowed when building official Debian packages. All software must be packaged within Debian.

That's not mandatory in MPR. So using make should be fine if that's the only reason.

**Comment by onlyvip** [comment]
>Note that nvim --version is generated from git describe normally, but idk what the precise requirements are for MPR.

Regarding this, if I run git describe inside the cloned neovim repo then the version I get is `v0.5.0-379-g0603eba6e` however the actual installed neovim shows a nightly version,
![image](https://i.imgur.com/bSDaTlB.png)

**Comment by Aeres-u99** [comment]
@jamessan "All software must be packaged within Debian." is this some sort of license term? or something which is an opinion or a security guideline? Can you please elaborate a bit on this?

**Comment by jamessan** [comment]
@Aeres-u99 this isn't really the right venue for the discussion, but Debian main must be self-contained.  Things are less restrictive for contrib and non-free, but _at build time_ no network access is allowed.

Part of it is license related, but it's also a matter of reliability.  Random internet sites can go down, which would be a problem if Debian needs to re-build something and the site that the build was trying to download from didn't exist any more.
