### ISSUE TITLE
Add A integrated terminal (if already exists, sorry) like vscode

### ISSUE THREAD

**Issue by HankB-o-t** [neovim/neovim#15530]
### Feature already in Vim?

Yes, Vim 8.2 and neovim(but in a different way)

### Feature description

If it's possible, please add an integrated terminal (like in vscode) that can be used wihout using an external program(like tmux) 
and wihout plugins (it will be a nice addition)

**Comment by gpanders** [comment]
`:help terminal`

**Comment by HankB-o-t** [comment]
> `:help terminal`

Oh thanks :D
