### ISSUE TITLE
Man pages opened manually in a running vim, cannot be closed if it's the last window

### ISSUE THREAD

**Issue by bew** [neovim/neovim#15544]
### Neovim version (nvim -v)

v0.5.0 (also tested on v0.4.4)

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux (CentOS)

### Terminal name/version

wezterm 20210814-124438-54e29167

### $TERM environment variable

tmux-256color

### Installation

nix

### How to reproduce the issue

```
nvim -u NORC foo  # open vim not in man pager mode
:Man man
<C-w>o     # keep only the man window
q          # try quit the man window
```

### Expected behavior

close the last window and quit nvim

### Actual behavior

we get the error: `E444: Cannot close last window`

also:
```
:verbose nmap q
n  q           *@:lclose<CR><C-W>c
        Last set from /nix/store/n01bgxllq3b5xvcmh5dgqa43hi27z0i2-neovim-unwrapped-0.5.0/share/nvim/runtime/ftplugin/man.vim line 38
```

**Comment by dundargoc** [comment]
I think your mapping is wack.

Documentation for `CTRL-W c`:

```
This command fails when:			*E444*
- There is only one window on the screen.
```

Did you set the mapping for `q` manually?

**Comment by justinmk** [comment]
duplicate https://github.com/neovim/neovim/issues/15506

> works fine for me with `MANPAGER= man ls | nvim -u ./init_test.lua '+Man!'`.
> 
> try latest master, there were changes to man.vim: [2548a9e](https://github.com/neovim/neovim/commit/2548a9e18037339c4c502d971bdeaf909b82a739)

**Comment by gpanders** [comment]
@justinmk This isn't quite a duplicate: I can reproduce this one. However, I don't think it's a bug. Once you open a `:Man` window in a running Nvim instance, it no longer is emulating a MANPAGER, so the fact that it does fail to close the last window is very much intentional.

**Comment by justinmk** [comment]
oh just noticed this:

> not in man pager mode

This is intentional...

**Comment by bew** [comment]
Ok, it's fair, I'll add my own keybinding to always close the window then (with `:q`)
Thanks
