### ISSUE TITLE
TUI: mouse: support sidescroll

### ISSUE THREAD

**Issue by Delta-official** [neovim/neovim#15557]
### Neovim version (nvim -v)

NVIM v0.5.0

### Vim (not Nvim) behaves the same?

Yes, VIM v8.0.1365

### Operating system/version

MacOS Mojave 10.14.6

### Terminal name/version

Iterm2 3.4.8 (also tested in Terminal.app 2.9.5)

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

nvim -u NONE
:edit foo
:set nowrap

### Expected behavior

On sidescroll, NVIM scrolls horizontally with nowrap

### Actual behavior

On sidescroll, NVIM does nothing

**Comment by justinmk** [comment]
what exactly does "sidescroll" mean? Is this a mouse gesture? Or related to `:help 'sidescroll'` option?

**Comment by Delta-official** [comment]
by "sidescroll" i mean touchpad gesture that is identical to vertical scrolling, just horizontal

**Comment by nobodyatandnothing** [comment]
i think the problem might be that sidescroll is same as shift+scroll

**Comment by zeertzjq** [comment]
I don't think there are escape sequences for horizontal touchpad scrolling...

**Comment by zeertzjq** [comment]
Maybe it's better to close this, as it is very unlikely that this will be possible in TUI.

**Comment by zeertzjq** [comment]
Oh, there are.

**Comment by zeertzjq** [comment]
This makes sidescroll work in xterm:
```diff
diff --git a/src/nvim/tui/input.c b/src/nvim/tui/input.c
--- a/src/nvim/tui/input.c
+++ b/src/nvim/tui/input.c
@@ -398,6 +398,14 @@ static void forward_mouse_event(TermInput *input, TermKeyKey *key)
     button = last_pressed_button;
   }
 
+  if (ev == TERMKEY_MOUSE_UNKNOWN && !(key->code.mouse[0] & 0x20)) {
+    int code = key->code.mouse[0] & ~0x3c;
+    if (code == 66 || code == 67) {
+      ev = TERMKEY_MOUSE_PRESS;
+      button = code - 60;
+    }
+  }
+
   if (button == 0 || (ev != TERMKEY_MOUSE_PRESS && ev != TERMKEY_MOUSE_DRAG
                       && ev != TERMKEY_MOUSE_RELEASE)) {
     return;
@@ -431,8 +439,11 @@ static void forward_mouse_event(TermInput *input, TermKeyKey *key)
     if (button == 4) {
       len += (size_t)snprintf(buf + len, sizeof(buf) - len, "ScrollWheelUp");
     } else if (button == 5) {
-      len += (size_t)snprintf(buf + len, sizeof(buf) - len,
-                              "ScrollWheelDown");
+      len += (size_t)snprintf(buf + len, sizeof(buf) - len, "ScrollWheelDown");
+    } else if (button == 6) {
+      len += (size_t)snprintf(buf + len, sizeof(buf) - len, "ScrollWheelLeft");
+    } else if (button == 7) {
+      len += (size_t)snprintf(buf + len, sizeof(buf) - len, "ScrollWheelRight");
     } else {
       len += (size_t)snprintf(buf + len, sizeof(buf) - len, "Mouse");
       last_pressed_button = button;
```

**Comment by JosefLitos** [comment]
This sequence is parsed, but not resent when in terminal buffer (instead it prints some garbled mess):

expected: `\[[<66;\d;\dM`, `\[[<67;\d;\dM`
received: in byte values: `253 191 191 187 132 131`, `253 191 191 187 136 131`

when modifiers are used, it prints negative numbers:
`\[[-19965;5u`, `\[[-20221;5u`

**Comment by zeertzjq** [comment]
That's strange, as it should be ignored in terminal buffer.
