### ISSUE TITLE
E5677: Error writing input to shell-command: EPIPE

### ISSUE THREAD

**Issue by kdheepak** [neovim/neovim#15554]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+210-g6751d6254

### Vim (not Nvim) behaves the same?

No.

### Operating system/version

macOS 10.15.7

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

Github Releases

### How to reproduce the issue

The following is my neovim folder:

```
$ tree 
.
├── init.lua
├── lua
│  └── kd
│     ├── config.lua
│     └── plugins.lua
└── plugin
   └── packer_compiled.lua
```

The following is the `init.lua` file:

```lua
-- ./init.lua
require("kd/plugins")
require("kd/config")
```

The following is the plugins.lua file:

```lua
-- ./lua/kd/plugins.lua
M = {}

local install_path = vim.fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"

if vim.fn.empty(fn.glob(install_path)) > 0 then
  vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
  vim.api.nvim_command("packadd packer.nvim")
end

local packer = require("packer")
local use = packer.use

packer.reset()

packer.startup({
  function()
    use("wbthomason/packer.nvim")

    use({
      "ibhagwan/fzf-lua",
      requires = {
        "vijaymarupudi/nvim-fzf",
        "kyazdani42/nvim-web-devicons",
      },
    })

  end,
})

return M
```

The `config.lua` is located at the link below and is entirely commented:

https://github.com/kdheepak/dotfiles/blob/4ac28a0017f586f2188ac1628f6d4796b7e72a0d/nvim/lua/kd/config.lua

If the file is empty then the issue does not occur. If the file has content that is more than the screen height (???), the issue occurs, even if all the content is commented.

Open `neovim` with the above configuration and run `:PackerCompile`.

Opening `neovim lua/kd/config.lua` and then running `:lua require("fzf-lua").files({cwd = "~/gitrepos/dotfiles"})` gives me the following error:

```txt
E5677: Error writing input to shell-command: EPIPE
E5677: Error writing input to shell-command: EPIPE
```

The error appears to originate from internal neovim: https://github.com/neovim/neovim/blob/5f8518b3f04c2295be24912dba78d3e34ca74b91/src/nvim/os/shell.c#L1196

Opening `neovim` without any file arguments and then running `:lua require("fzf-lua").files({cwd = "~/gitrepos/dotfiles"})` does not result in any error. 

Deleting the contents of `lua/kd/config.lua` and then opening `neovim lua/kd/config.lua` and then running `:lua require("fzf-lua").files({cwd = "~/gitrepos/dotfiles"})` does not cause the error.

Here's screencase of this error:

https://user-images.githubusercontent.com/1813121/131826898-ee924f45-25d6-486d-9a68-e9e537a532b9.mov

When the contents of the config.lua file are all commented, I get the error. When I delete the contents of the config.lua file, I don't get any error. 

After the error occurs, `fzf-lua` appears to run normally. Every time I run `fzf-lua`.files I get the same error. 

This was originally discussed here: https://github.com/ibhagwan/fzf-lua/issues/89

### Expected behavior

Error does not occur.

### Actual behavior

Vim internal error

```txt
E5677: Error writing input to shell-command: EPIPE
E5677: Error writing input to shell-command: EPIPE
```

**Comment by justinmk** [comment]
explained at `:help E5677`

```
                                                *E5677*
Note: system() cannot write to or read from backgrounded ("&")
shell commands, e.g.: >
    :echo system("cat - &", "foo"))
<		which is equivalent to: >
    $ echo foo | bash -c 'cat - &'
```

**Comment by EdmundsEcho** [comment]
Thank you for the input.  I came across this issue when neovim was raising the same error.  I was in the process of debugging why I had zero clients attached despite having available lsp servers.

Anyway, the `:help E5677` returns "Sorry no help" error.  I'm using the bleeding edge version of neovim which I generally try to avoid, except for the fact that I'm using a M1 chip.

```
:version
NVIM v0.7.0-dev+809-ge42c90659
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by edmund@Edmunds-MacBook-Pro.local
```

It would be great to know more about the source and how to identify which of the plugins or my configurations is raising this error.  Any advice?

**Comment by byte1234** [comment]
@EdmundsEcho Maybe you can check whether the third-party executable your plugins depends on is installed or works fine. I came across this error when my format tool `rustfmt` was not installed. this error disappear after a `rustfmt` installation.
