### ISSUE TITLE
Custom keywords are cleared on load

### ISSUE THREAD

**Issue by nebulaeandstars** [neovim/neovim#15556]
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

Yes (8.2.2891), with default settings.

### Operating system/version

arch linux

### Terminal name/version

st

### $TERM environment variable

st-256color

### Installation

pacman

### How to reproduce the issue

1. Define a keyword (eg. with `syntax keyword rustKeyword foo` for rust).
2. Reloading with :edit will reset the syntax again.

This applies to changes made in init.vim, ftplugin, or colorscheme files as well. No change will be visible unless you manually reload the colorscheme with `colorscheme bar`

### Expected behavior

Keywords defined in init.vim, ftplugin, or colorscheme files should do what they're supposed to, and syntax overrides should stick even after loading a new buffer.

### Actual behavior

They used to, but don't anymore.

**Comment by matveyt** [comment]
This is just normal. Syntax must be defined under `syntax` (or `after/syntax`).
