### ISSUE TITLE
:checkhealth should check LSP log level

### ISSUE THREAD

**Issue by 0mco** [neovim/neovim#15567]
### Feature description

I found the lsp.log file in cache directory has over 700M file size. It would be great if its size gets restricted.

**Comment by kraftwerk28** [comment]
Adding something like this to `init.vim` should solve the issue:
```vim
let g:log_limit = 1000
function TruncLog()
  let path = v:lua.vim.lsp.get_log_path()
  execute '!echo "$(tail -n '.g:log_limit.' '.l:path.')" > '.l:path
endfunction
autocmd VimEnter * call TruncLog()
```

**Comment by mjlbach** [comment]
Are you sure you didn't set `set_log_level` at some point? I would be surprised if at the default logging level you were able to accumulate 700 Mb.

**Comment by jdhao** [comment]
FYI, my lsp.log file from March 2021 to now is about 16M in size.

**Comment by justinmk** [comment]
`:checkhealth`  should check this if it doesn't already. Probably should also warn when `lsp.lua` is first loaded.

**Comment by 0mco** [comment]
I'm really sorry, I forgot I set the log level to debug when I was trying to configure built-in lsp.

**Comment by justinmk** [comment]
reopening, we need to do https://github.com/neovim/neovim/issues/15567#issuecomment-913805093

**Comment by mjlbach** [comment]
I went ahead and added a runtime check, but we can remove it (I personally would)
