### ISSUE TITLE
Nighty build broken?

### ISSUE THREAD

**Issue by jc00ke** [neovim/neovim#15568]
### Neovim version (nvim -v)

unable to install

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Ubuntu 21.04 (Regolith)

### Terminal name/version

alacritty 0.9

### $TERM environment variable

xterm-256color

### Installation

asdf

### How to reproduce the issue

https://github.com/neovim/neovim/runs/3511973885?check_suite_focus=true

### Expected behavior

I should be able to `asdf install neovim nightly` but it fails because it can't download the release archive.

### Actual behavior

```
asdf install neovim nightly
rm: cannot remove '/tmp/neovim_build_Ym0ORW/neovim-nightly.tar.gz': No such file or directory
==> curl -Lo /tmp/neovim_build_Ym0ORW/neovim-nightly.tar.gz -C - https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     35      0 --:--:-- --:--:-- --:--:--    35

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat '/home/jesse/.asdf/downloads/neovim/nightly/**': No such file or directory
```

**Comment by rktjmp** [comment]
Might have just been a one off, at the very tail:

```
  curl: (55) OpenSSL SSL_write: Connection reset by peer
```

Might just need a re-run. 

From my experience the

```json
  {
    "message": "Not Found",
    "documentation_url": "https://docs.github.com/rest/reference/repos#delete-a-release-asset"
  }
``` 

messages aren't an error, just a side effect of the uploader when it tries to clear old assets.

**Comment by Gelio** [comment]
Looks like the same problem happened in today's nightly:
https://github.com/neovim/neovim/runs/3530275099?check_suite_focus=true

Meaning there is no nightly release present [on the Releases page](https://github.com/neovim/neovim/releases/)

**Comment by rktjmp** [comment]
Anyone who wants to could maybe see if there is a way to get better logs out of meeDamian/github-release or docker containers in GH Actions. I assume it's just some endpoint failure on GH's side since we don't do anything but pass some strings really but there might be an actual cause (too many files? cert rejection? timeout?) hidden away. If only to make a better report upstream somewhere.
