### ISSUE TITLE
Neovim crashes when typing the expression for i_CTRL-R

### ISSUE THREAD

**Issue by bohrshaw** [neovim/neovim#15564]
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 2004

### Terminal name/version

Alacritty and Tmux

### $TERM environment variable

screen-256color

### Installation

https://github.com/neovim/neovim/releases/download/v0.5.0/nvim.appimage

### How to reproduce the issue

    nvim -u NORC
    i<C-r>=2*2^

### Expected behavior

Neovim should not crash.

### Actual behavior

nvim: ../src/nvim/viml/parser/expressions.c:1237: viml_pexpr_handle_bop: Assertion `bop_node_lvl != new_top_node_lvl || bop_node_ass == new_top_node_ass' failed.
[1]  15980 abort (core dumped)  nvim -Nu NORC

**Comment by gpanders** [comment]
Duplicate https://github.com/neovim/neovim/issues/7889
