### ISSUE TITLE
Support Python numbers with underscores

### ISSUE THREAD

**Issue by lucatpa** [neovim/neovim#15576]
### Feature already in Vim?

No, but there is a PR

### Feature description

Since Python 3.6 it is valid to add underscored in the middle of numeric literals: https://www.python.org/dev/peps/pep-0515/

VIM PR: https://github.com/vim/vim/pull/8033

**Comment by clason** [comment]
Then we'll have to wait until the PR is merged; once the runtime file is updated in vim, we will include it as part of our continuous porting of upstream runtime updates.
