### ISSUE TITLE
No text colors when running Neovim within screen on iTerm2

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#15584]
### Neovim version (nvim -v)

NVIM v0.5.0

### Vim (not Nvim) behaves the same?

Vim 8.2.3275 behaves differently, showing colors

### Operating system/version

macOS 11.5.2

### Terminal name/version

iTerm2 3.4.8

### $TERM environment variable

screen

### Installation

homebrew

### How to reproduce the issue

```vim
nvim -u NORC
" Confirm colors work outside screen (the help screen shows colored text)
:help
" Run Neovim within screen
:qall
screen
nvim -u NORC
" Check for colors again
:help
```

### Expected behavior

Colored text would be shown when Neovim is run within `screen`.

### Actual behavior

Text has no colors when Neovim is run within `screen`.

### Additional information

- I do not encounter the issue on macOS when using the built-in `Terminal.app`.
- I do not encounter the issue on Ubuntu 21.04.
- I encountered the issue on macOS with `screen` version `4.08.00`. I tried with an older version, `4.00.03` and still encountered the issue.

**Comment by clason** [comment]
That's because your `TERM` variable is wrong; it needs to be set to `screen-256color`; see https://github.com/neovim/neovim/wiki/FAQ#home-or-some-other-special-key-doesnt-work

(Note that screen doesn't support truecolor.)

**Comment by dstein64** [comment]
Thanks @clason!
