### ISSUE TITLE
[ RUN      ] user config init loads init.lua from XDG config home by default:  

### ISSUE THREAD

**Issue by codehia** [neovim/neovim#15581]
### Neovim version (nvim -v)

0.5.0 687a0b3d3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

popos 21.04

### Terminal name/version

kitty 0.19.3

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

Steps to reproduce:
make tests
[ RUN      ] user config init loads init.lua from XDG config home by default:

### Expected behavior

This should go on to finish the test

### Actual behavior

The tests get stuck at this step.

**Comment by justinmk** [comment]
It passes in many CI systems, so you need to make changes to the test to narrow down the issue. Then send a PR.
