### ISSUE TITLE
ctrlp-py-matcher not working in neovim

### ISSUE THREAD

**Issue by rvega** [neovim/neovim#1558]
I installed the CtrlP plugin and it works fine with neovim. However, it's a bit slow to index and to find matches for a search so I installed @felikz 's plugin [ctrlp-py-matcher](https://github.com/FelikZ/ctrlp-py-matcher).

Here's the relevant stuff in my ~/.nvimrc:

```vim
call plug#begin('~/.nvim/plugged')
Plug 'kien/ctrlp.vim'
Plug 'FelikZ/ctrlp-py-matcher'
call plug#end()

" Make Ctrl+P indexing faster by using ag silver searcher
let g:ctrlp_lazy_update = 350
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_max_files = 0
if executable("ag")
   set grepprg=ag\ --nogroup\ --nocolor
   let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --ignore ''.git'' --ignore ''.DS_Store'' --ignore ''node_modules'' --hidden -g ""'
endif 

" Make Ctrl+P matching faster by using pymatcher
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
```

If I comment out that last line, indexing works fast and matching works fine, but if I put it in, indexing seems to work but nothing is ever matched so I always get an empty results list.

How can I help debug this issue? what kind of output/logs can I provide? 

*Edit:* The exact same thing works fine in vim 7.3.944

**Comment by Pyrohh** [comment]
This plugin was fixed a while ago (I'm using it), so this can probably be closed.

**Comment by jszakmeister** [comment]
Thanks again. :-)
