### ISSUE TITLE
background=light not set in screen on macOS

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#15582]
### Neovim version (nvim -v)

NVIM v0.5.0

### Vim (not Nvim) behaves the same?

Vim 8.2.3275 behaves differently

### Operating system/version

macOS 11.5.2

### Terminal name/version

Terminal.app 2.11 (440)

### $TERM environment variable

`screen` was set by default. I encounter this issue both with `screen` and with `screen-256color`.

### Installation

homebrew

### How to reproduce the issue

```vim
nvim -u NORC
" Confirm background=light
:set background?
" Run Neovim within screen
:quit
screen
nvim -u NORC
" Check background
:set background?
```

### Expected behavior

`background=light` when running Neovim within `screen`.

### Actual behavior

`background=dark` when running Neovim within `screen`

### Additional information

- I do not encounter the issue on Ubuntu 21.04.
- I encountered the issue on macOS with `screen` version `4.00.03`. I tried with a newer version, `4.08.00` and still encountered the issue.
- ~~Possibly related to Issue #15365.~~

**Comment by justinmk** [comment]
- is `handle_background_color` being entered at all (_after_ line 472) ? https://github.com/neovim/neovim/blob/687a0b3d3e8878b6de058b02d84fbd1f78aa2e89/src/nvim/tui/input.c#L482
    - compare the args on the system that works vs the one that doesn't


> * Possibly related to Issue [background=light not properly set for nvim running within screen on macOS #15582](https://github.com/neovim/neovim/issues/15582).

did you mean to link somewhere else?

**Comment by dstein64** [comment]
> "is handle_background_color being entered at all (after line 472) ?"

The code is entered both through screen and not through screen. However, when running Neovim not through screen the debugger breaks on that function right after I run the program, returning from the function [here](https://github.com/neovim/neovim/blob/db695cc4cafa6c26eb71a183cc73a167b842731e/src/nvim/tui/input.c#L549). However, when running through screen, the breakpoint is not hit until I enter a key within the running Neovim, and the function returns from [here](https://github.com/neovim/neovim/blob/db695cc4cafa6c26eb71a183cc73a167b842731e/src/nvim/tui/input.c#L500).

> "Although, you say it works in Vim?"

Yeah.

> "And it works in Nvim on ubuntu...?"

Yeah.

**Comment by dstein64** [comment]
This seems unrelated, but I also noticed that the intro screen is shown when I enter Neovim through `screen`, whereas it is not shown (or possibly flashes on then off quickly) when I enter Neovim outside of `screen`.

<img width="464" alt="intro" src="https://user-images.githubusercontent.com/541289/132268924-2f8570b6-0091-491a-b520-c9b640bc99f8.png">

**Comment by justinmk** [comment]
> However, when running through screen, the breakpoint is not hit until I enter a key within the running Neovim, and the function returns from [here](https://github.com/neovim/neovim/blob/db695cc4cafa6c26eb71a183cc73a167b842731e/src/nvim/tui/input.c#L500).

so probably https://github.com/neovim/neovim/blob/db695cc4cafa6c26eb71a183cc73a167b842731e/src/nvim/tui/input.c#L498

This might be a terminfo issue. 

If you want to investigate, you can see terminal debugging info when the 'verbose' level is >=3 (see `:help 'verbose')`.  Try this:

    nvim -V3log
    :q

Then the file named `log` will have a `--- Terminal info ---` section. Please post that section. (Note: invoke `:q` manually, so that the builtin UI has a chance to start up. Don't add `-c "q"` in the command-line args.)

Then you could compare this to `:set termcap` in Vim.

**Comment by dstein64** [comment]
> "Please post that section."

I've generated the Neovim log data under 3 scenarios:

1. Neovim running outside of screen
    - [log_outside_screen.txt](https://github.com/neovim/neovim/files/7131089/log_outside_screen.txt)
2. Neovim running within screen, with `TERM=screen`
    - [log_within_screen.txt](https://github.com/neovim/neovim/files/7131098/log_within_screen.txt)
3. Neovim running within screen, with `TERM=screen-256color`
    - [log_within_screen_256color.txt](https://github.com/neovim/neovim/files/7131101/log_within_screen_256color.txt)

The log file generated outside screen shows a `initialize_color` entry, whereas the others do not. The other entries that sounded relevant were present and had the same values across the files (e.g., `ext.get_bg`, `setrgbb`, `set_a_background`).

I also ran `:set termcap` within Vim running in `screen`.
[vim_within_screen.txt](https://github.com/neovim/neovim/files/7131153/vim_within_screen.txt)

**Comment by justinmk** [comment]
> I also ran `:set termcap` within Vim running in `screen`.
> [vim_within_screen.txt](https://github.com/neovim/neovim/files/7131153/vim_within_screen.txt)

I see `t_8b=` in there which I think means no bg response.


I actually forgot that the default 'background' in Vim is "light". From vim's `:help 'bg'`

```
	For MS-Windows the default is "dark".
	For other systems "dark" is used when 'term' is "linux",
	"screen.linux", "cygwin" or "putty", or $COLORFGBG suggests a dark
	background.  Otherwise the default is "light".
```

So this only works in Vim by accident.
