### ISSUE TITLE
fuse: mount failed: Permission denied when using neovim as MANPAGER

### ISSUE THREAD

**Issue by Gelio** [neovim/neovim#15590]
### Neovim version (nvim -v)

v0.6.0-dev+220-gdb695cc4c

### Vim (not Nvim) behaves the same?

no clue

### Operating system/version

Ubuntu 20.04 LTS

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

1. Install neovim appimage
2. Set `MANPAGER` variable according to https://github.com/neovim/neovim/issues/14090#issuecomment-913837694
3. Run `man ls`

### Expected behavior

Neovim opens with the man page for `ls`

### Actual behavior

There is an error about mounting the appimage:

```
13:26 $ env | grep MANPAGER
MANPAGER=nvim +Man!
13:26 $ man ls
fuse: mount failed: Permission denied

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage
if you run it with the --appimage-extract option.
See https://github.com/AppImage/AppImageKit/wiki/FUSE
for more information
open dir error: No such file or directory
man: command exited with status 127: sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }' | LESS=-ix8RmPm Manual page ls(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$PM Manual page ls(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$ MAN_PN=ls(1) nvim +Man!
```

The same error occurs for other man pages (`pwd`, `echo`).

Using the `:Man ls` command after neovim is open works fine.

**Comment by Gelio** [comment]
Thanks for pointing that out. I switched to using a regular binary and it works fine

**Comment by treequin** [comment]
Ran into this today. I got it to work by combining the two commands in [this SE answer](https://unix.stackexchange.com/a/656923).
`export MANPAGER='nvim.appimage --appimage-extract-and-run +Man!'`

**Comment by PandaWill** [comment]
On Ubuntu this is caused by AppArmor's sandboxing of man.

We can add a local override to allow it:

/etc/apparmor.d/local/usr.bin.man
```
mount fstype=fuse.nvim options=(ro, nosuid, nodev) -> /tmp/**,
/usr/bin/fusermount Ux,
```

**Comment by justinmk** [comment]
@PandaWill thanks, in https://github.com/neovim/neovim/issues/30268 I was waiting for a way to configure this.
