### ISSUE TITLE
O shouldn't go back to front of line

### ISSUE THREAD

**Issue by GopherJ** [neovim/neovim#15608]
### Feature description

I'd like to draw rectangle using neovim and I'd like to achieve this using `o`, `a`, `O`, I did:

1. `100o|esc` which draws correctly a vertical line
2. `100a_esc` which draws correctly a horizontal line
3. `100O|esc` this doesn't work as expected, it goes back to front of the line

I'm wondering why `o` and `O` are designed to go back to front of line? can this be changed?

**Comment by justinmk** [comment]
For questions about usage/configuration, try 
- http://discourse.neovim.io/ 
- https://vi.stackexchange.com
- https://neovim.io/#chat

The issue tracker is for bugs and feature requests.

**Comment by GopherJ** [comment]
@justinmk as the title says, I think `o` shouldn't go back to front of line.

**Comment by bfredl** [comment]
for the record, use 'virtualedit'
