### ISSUE TITLE
Regression in df17d7844ed7dedcb80f9405f7078a046a12524a breaks :ClangdSwitchSourceHeader for lsp

### ISSUE THREAD

**Issue by matu3ba** [neovim/neovim#15606]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+183-gf7dabbc11 (bisection ends there)

### Vim (not Nvim) behaves the same?

vim has no inbuild lsp

### Operating system/version

Linux

### Terminal name/version

alacritty 0.9.0 (fed349aa)

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

1. have clangd installed
2. have a header and source file
3. run `:ClangdSwitchSourceHeader`

### Expected behavior

neovim should change into respective source and header file

### Actual behavior

neovim does not change into respective source and header file as explained here: https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#clangd

The following error message is shown:
```txt
Error executing vim.schedule lua callback: ...sterspoon/.local/nvim/
share/nvim/runtime/lua/vim/uri.lua:96: attempt to call method 'match
' (a nil value)
```

**Comment by clason** [comment]
Since `:ClangdSwitchSourceHeader` is a special command provided by `nvim-lspconfig` and not part of the LSP spec (and hence implemented in the builtin client itself), this needs to be fixed (and reported, which it already is: https://github.com/neovim/nvim-lspconfig/issues/1239) there.
