### ISSUE TITLE
variable and :set for colorcolumn

### ISSUE THREAD

**Issue by frogtile** [neovim/neovim#15617]
### Feature already in Vim?

No

### Feature description

Introduce a variable to store colorcolumn's value and a option to set it. Must like how listchars and list works.

**Comment by justinmk** [comment]
this already exists: 

    :echo &colorcolumn

can you be more specific. give a full example.

**Comment by frogtile** [comment]
in init.vim i have

```vim
set listchars=tab:▸\ ,eol:¬,space:.
nmap <leader>l :set list!<CR>
```
In a similar fashion i would like to have something like

```vim
set colorcolumns=+1
nmap <leader>cc :set highlightcolumn!<CR>
```

**Comment by gpanders** [comment]
You can trivially do this with an `<expr>` mapping.

```vim
nnoremap <expr> <leader>cc &colorcolumn ==# '' ? '<Cmd>set colorcolumn=+1<CR>' : '<Cmd>set colorcolumn=<CR>'
```
