### ISSUE TITLE
Example of a statusline for the LSP in the help file does not work

### ISSUE THREAD

**Issue by David-Else** [neovim/neovim#15623]
### Neovim version (nvim -v)

NVIM v0.5.0

### Vim (not Nvim) behaves the same?

na

### Operating system/version

Centos 8

### Terminal name/version

Gnome Terminal

### $TERM environment variable

xterm-256color

### Installation

AppImage

### How to reproduce the issue

Copy and paste the statusline example from the help file into `init.vim`:

```
function! LspStatus() abort
  let sl = ''
  if luaeval('not vim.tbl_isempty(vim.lsp.buf_get_clients(0))')
    let sl.='%#MyStatuslineLSP#E:'
    let sl.='%#MyStatuslineLSPErrors#%{luaeval("vim.lsp.diagnostic.get_count(0, [[Error]])")}'
    let sl.='%#MyStatuslineLSP# W:'
    let sl.='%#MyStatuslineLSPWarnings#%{luaeval("vim.lsp.diagnostic.get_count(0, [[Warning]])")}'
  else
      let sl.='%#MyStatuslineLSPErrors#off'
  endif
  return sl
endfunction
let &l:statusline = '%#MyStatuslineLSP#LSP '.LspStatus()
```

### Expected behavior

It shows the number of errors and warnings from the LSP

### Actual behavior

It correctly shows "LSP off" when a file is opened with no LSP configured, but when a file is open with an LSP  and errors/warning it shows nothings, and the "LSP off" has gone away.

**Comment by justinmk** [comment]
needs to be changed to

    autocmd BufWinEnter * let &l:statusline = '%#MyStatuslineLSP#LSP '.LspStatus()

**Comment by David-Else** [comment]
@justinmk This solution seems to only work if you open another file after and go back to the original.

For example, start nvim and open a file with LSP errors, it now (with your suggested modification) says `LSP Off`. Open another file, and then toggle back to the file with errors and now it works. Please advise how to fix this, thanks!

(I am using an `init.vim` and the LSP setup is called within it with `lua require("lsp")`)

**Comment by clason** [comment]
Should be `BufRead,BufEnter`?

**Comment by gpanders** [comment]
For the sake of an example it’s probably simpler to just set the global 'statusline' option rather than the local version. Users can integrate the example into their actual statusline however they want at that point.

I’ll update this example in #15585 as well.

**Comment by David-Else** [comment]
@clason `BufNewFile,BufRead` means it does not work at all.
@gpanders I am a bit of a newb with this, please could you tell me how I can add this LSP statusline to my current statusline?
```
function! LspStatus() abort
  let sl = ''
  if luaeval('not vim.tbl_isempty(vim.lsp.buf_get_clients(0))')
    let sl.='%#MyStatuslineLSP#E:'
    let sl.='%#MyStatuslineLSPErrors#%{luaeval("vim.lsp.diagnostic.get_count(0, [[Error]])")}'
    let sl.='%#MyStatuslineLSP# W:'
    let sl.='%#MyStatuslineLSPWarnings#%{luaeval("vim.lsp.diagnostic.get_count(0, [[Warning]])")}'
  else
      let sl.='%#MyStatuslineLSPErrors#off'
  endif
  return sl
endfunction

set statusline=
set statusline+=%#PmenuSel#
set statusline+=%{StatuslineGit()}
set statusline+=%#LineNr#
set statusline+=\ %f
set statusline+=%m\
set statusline+=%=
set statusline+=%#CursorColumn#
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=\ %p%%
set statusline+=\ %l:%c
set statusline+=\ 

-- ?? what should this line be to simply add to my statusline?
autocmd BufNewFile,BufRead * let &l:statusline = '%#MyStatuslineLSP#LSP '.LspStatus() 
```

**Comment by gpanders** [comment]
Probably

`set statusline+=LSP\ %{LspStatus()}`

but I don’t use this and haven’t tested it.

**Comment by justinmk** [comment]
> For the sake of an example it’s probably simpler to just set the global 'statusline' option rather than the local version

yeah though the current form wouldn't re-evaluate `LspStatus()`

**Comment by gpanders** [comment]
> > For the sake of an example it’s probably simpler to just set the global 'statusline' option rather than the local version
> 
> yeah though the current form wouldn't re-evaluate `LspStatus()`

Yep, I’ll update it accordingly.

**Comment by David-Else** [comment]
@gpanders 

> Probably
> 
> `set statusline+=LSP\ %{LspStatus()}`
> 
> but I don’t use this and haven’t tested it.

Afraid this gives me `<#E:%#MyStatuslineLSPErrors#%{luaeval("vim.lsp.diagnostic.get_count(0, [[Error]])")}%#MyStatuslineLSP# W:%#MyStatuslineLSPWarnings#%{luaeval("vim.lsp.diagnostic.get_count(0, [[Warning]])")}` as my statusline.

@justinmk adding `autocmd BufWinEnter *` does not solve the problem for the reasons given in https://github.com/neovim/neovim/issues/15623#issuecomment-916898821

I am not sure if you are saying it will be fixed in the future or `autocmd BufWinEnter *` is the fix?

Can anyone make another suggestion to solve https://github.com/neovim/neovim/issues/15623#issuecomment-916909517 ? Cheers!

**Comment by justinmk** [comment]
> @justinmk adding `autocmd BufWinEnter *` does not solve the problem for the reasons given in [#15623 (comment)](https://github.com/neovim/neovim/issues/15623#issuecomment-916898821)

it works well enough. it's just an example. since @gpanders plans to improve it in their existing PR, this is enough to close this issue.
