### ISSUE TITLE
LSP Diagnostic `hl_mode` combine

### ISSUE THREAD

**Issue by haze** [neovim/neovim#15624]
### Feature already in Vim?

No

### Feature description

as of aab3583e74fa3fd295bd367113be60965c748205, the built in LSP client diagnostics virtual text view does not play well with things like `CursorLine`.

Here is what it looks like:
<img width="1322" alt="CleanShot 2021-09-10 at 08 43 14@2x" src="https://user-images.githubusercontent.com/15584994/132854976-fd7caee1-60d7-4a51-8509-96b05d06a29a.png">
The diagnostic is jarring as it does not respect the background that it is being displayed over.

I've fixed it locally with a hack here:
```diff
--- a/runtime/lua/vim/lsp/diagnostic.lua
+++ b/runtime/lua/vim/lsp/diagnostic.lua
@@ -776,6 +776,7 @@ function M.set_virtual_text(diagnostics, bufnr, client_id, diagnostic_ns, opts)

     if virt_texts then
       api.nvim_buf_set_extmark(bufnr, diagnostic_ns, line, 0, {
+        hl_mode = 'combine',
         virt_text = virt_texts,
       })
     end
```

<img width="1342" alt="CleanShot 2021-09-10 at 08 44 03@2x" src="https://user-images.githubusercontent.com/15584994/132855092-836432a0-50fa-4d68-9194-689da6b2bb01.png">

Notice how in the second image, the virtual text respects my cursor line background.

I'm unsure if this is the correct way, so Instead of a PR I am opening an issue.

**Comment by gpanders** [comment]
I think this is reasonable. I'll include this change in #15585

**Comment by haze** [comment]
Thank you @gpanders 🥳
