### ISSUE TITLE
windows: I added the 'cmd' extension to the command, but all lsp functions don't do anything.

### ISSUE THREAD

**Issue by webmandman** [neovim/neovim#15628]
nvim -v:
NVIM v0.6.0-dev+235-ga422f2136
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az159-362
OS: windows 10

I added the 'cmd' extension to the command, but all lsp functions don't do anything. 
 
 Perhaps, I have underlying issue. When I call `:lua vim.cmd('e'..vim.lsp.get_log_path())` I get the error: 
 E5108: Error executing lua [string:":lua"]:1: Vim:E492: **Not an editor command**: eC:\Users\DANIEL~1.MEJ\AppData\Local\Temp\nvim\lsp.log
 
So can you give me a little guidance on how to debug this, please. 

![image](https://user-images.githubusercontent.com/991677/132740044-01699bcf-86d5-4b32-8ed5-654bdae81714.png)

> @mjlbach I rebooted and ran another rename function and now I can see something in the log file. Looks to me like the request is being sent and it errors out. 
> 
> [ DEBUG ] 2021-09-09T11:16:41-0700 ] ...elopment\Tools\Neovim\share\nvim\runtime\lua\vim\lsp.lua:897 ] "LSP[tsserver]" "client.request" 1 "textDocument/rename" { newName = "filesystem", position = { character = 6, line = 0 }, textDocument = { uri = "C:\Development\sites\intra\angularworkspace\rename.js" }} <function 1> 2
> [ DEBUG ] 2021-09-09T11:16:41-0700 ] ...ment\Tools\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:395 ] "rpc.send.payload" { id = 4, jsonrpc = "2.0", method = "textDocument/rename", params = { newName = "filesystem", position = { character = 6, line = 0 }, textDocument = { uri = "C:\Development\sites\intra\angularworkspace\rename.js" } }}
> [ DEBUG ] 2021-09-09T11:16:41-0700 ] ...ment\Tools\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:496 ] "decoded" { id = 4, jsonrpc = "2.0", result = vim.NIL}
> [ DEBUG ] 2021-09-09T11:16:41-0700 ] ...Tools\Neovim\share\nvim\runtime\lua\vim\lsp\handlers.lua:461 ] "default_handler" "textDocument/rename" { ctx = '{\n bufnr = 2,\n client_id = 1,\n method = "textDocument/rename"\n}'}

UPDATE: I reverted back to 0.5.0 and lspconfig works.

**Comment by webmandman** [comment]
> @mjlbach I rebooted and ran another rename function and now I can see something in the log file. Looks to me like the request is being sent and it errors out. Does this log help?
> 
> [ DEBUG ] 2021-09-09T11:16:41-0700 ] ...elopment\Tools\Neovim\share\nvim\runtime\lua\vim\lsp.lua:897 ] "LSP[tsserver]" "client.request" 1 "textDocument/rename" { newName = "filesystem", position = { character = 6, line = 0 }, textDocument = { uri = "C:\Development\sites\intra\angularworkspace\rename.js" }} <function 1> 2
> [ DEBUG ] 2021-09-09T11:16:41-0700 ] ...ment\Tools\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:395 ] "rpc.send.payload" { id = 4, jsonrpc = "2.0", method = "textDocument/rename", params = { newName = "filesystem", position = { character = 6, line = 0 }, textDocument = { uri = "C:\Development\sites\intra\angularworkspace\rename.js" } }}
> [ DEBUG ] 2021-09-09T11:16:41-0700 ] ...ment\Tools\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:496 ] "decoded" { id = 4, jsonrpc = "2.0", result = vim.NIL}
> [ DEBUG ] 2021-09-09T11:16:41-0700 ] ...Tools\Neovim\share\nvim\runtime\lua\vim\lsp\handlers.lua:461 ] "default_handler" "textDocument/rename" { ctx = '{\n bufnr = 2,\n client_id = 1,\n method = "textDocument/rename"\n}'}

**Comment by mjlbach** [comment]
I am not an appropriate issue title, and you're probably running into https://github.com/neovim/neovim/issues/15261 (duplicate)

**Comment by webmandman** [comment]
I updated the title right as you were replying back. I simply use a github feature of creating a new issue from a comment and didn't realize it had put your name there.

anyways, thanks.
