### ISSUE TITLE
`shell` set to `powershell` fails `termopen` command

### ISSUE THREAD

**Issue by EdenEast** [neovim/neovim#15634]
### Neovim version (nvim -v)

```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```

### Vim (not Nvim) behaves the same?

No as termopen is neovim specific.

### Operating system/version

Windows 10 10.0.19043 Build 19043

### Terminal name/version

nvim-qt, powershell & cmd

### $TERM environment variable

nvim-qt = "", powershell = "vtpcon", cmd = ""

### Installation

Chocolatey

### How to reproduce the issue

nvim -u NORC
:set shell=powershell
:execute termopen('powershell')

### Expected behavior

A new terminal window to open up with powershell launched.

### Actual behavior

Powershell launched in a state waiting for some input. When I enter terminal mode (either `a` or `i`) and press enter there is a powershell error message. 

```
An unknown element "" was received. This can happen if the remote process closed or ended abnormally. 
[Process exited 4000]
```

This happens when the shell is set to `powershell` or even `powershell.exe`.
If the shell is not changed and the default `cmd.exe` is set the `:execute termopen('powershell')` launches successfully. 

This issue seems only related to `termopen` as just executing `:terminal` is successful.

**Comment by justinmk** [comment]
ensure that you have set all of the options explained at `:help shell-powershell`
