### ISSUE TITLE
if statement with pipe (if x() | return | endif) produces E171: Missing :endif when in command mode

### ISSUE THREAD

**Issue by mckellygit** [neovim/neovim#15635]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+253-ge31652879

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 18.04 with latest updates

### Terminal name/version

kitty or alacritty  but I dont think it matters ?

### $TERM environment variable

tmux-256color but I dont think it matters ?

### Installation

built from repo

### How to reproduce the issue

lightline plugin and some others (gitgutter for example) have stmts such as:
  if s:skip() | return | endif
When in command mode this produces the error:
E171: Missing :endif
If we change the if stmts to be traditional -
if s:skip()
    return
endif
Then there is no issue.

### Expected behavior

does not produce error msg

### Actual behavior

E171: Missing :endif error msg - when in command mode

**Comment by justinmk** [comment]
For questions about usage/configuration, try 
- http://discourse.neovim.io/ 
- https://vi.stackexchange.com
- https://neovim.io/#chat

The issue tracker is for bugs and feature requests.

**Comment by mckellygit** [comment]
ok, will do.

**Comment by mckellygit** [comment]
Seems to be a dup of https://github.com/neovim/neovim/issues/8796
Sorry I didn't find that before.
