### ISSUE TITLE
lsp: respect cmd_env when checking if servers are executable

### ISSUE THREAD

**Issue by williamboman** [neovim/neovim#15648]
### Neovim version (nvim -v)

v0.6.0-dev+182-ga373ca1d8

### Language server name/version

*

### Operating system/version

*

### Steps to reproduce using "nvim -u minimal_init.lua"

<details><summary>Click to expand</summary>

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
      { 'williamboman/nvim-lsp-installer', branch = 'io-speedups' }
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Run :LspInstall <server> to install servers inside $HOME/.local/share/nvim/lsp_servers
  local lsp_installer = require('nvim-lsp-installer')
  lsp_installer.on_server_ready(function(server)
    server:setup { on_attach = on_attach }

    vim.cmd [[ do User LspAttachBuffers ]]
  end)

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

</details>

### Expected behavior

Hi! I'm currently looking into changing the behaviour of https://github.com/williamboman/nvim-lsp-installer/ so that it, to the extent possible, doesn't alter the `cmd` and instead lets lspconfig take care of that. Instead, I'd like to only configure an amended `PATH` in the `cmd_env` option, which will allow libuv to locate the executable when neovim's LSP client spawns it.

I'm however running into some issues with both neovim's LSP RPC module as well as lspconfig having `executable()` checks in place, which will all fail because the amended `PATH` is not applied to the running neovim instance (I don't think this would be feasible at all). I think it'd be neat if the "executability" of a command is delegated to libuv itself, and not the neovim runtime?

### Actual behavior

1. lspconfig rejects the LSP server setup [here](https://github.com/neovim/nvim-lspconfig/blob/1344a859864d4e6d23d3f3adf56d49e6386ec0d2/lua/lspconfig/util.lua#L262-L265) (`:LspInfo` will also display that the cmd [is not executable](https://github.com/neovim/nvim-lspconfig/blob/1344a859864d4e6d23d3f3adf56d49e6386ec0d2/lua/lspconfig/ui/lspinfo.lua#L38-L40))
2. if the above is commented out, neovim will reject the LSP server [here](https://github.com/neovim/neovim/blob/413e86869ef147431a78946562c125938b41f533/runtime/lua/vim/lsp/rpc.lua#L325-L327)

If you want to jump right into a running example I've published a docker image:

```sh
$ docker run --rm -ti williamboman/nvim-repro:lspconfig-env nvim -S /root/Session.vim
```

`clangd` and `sumneko_lua` are both installed, and there's an open `main.c` buffer where `clangd` fails to start, and instead prints an error message:

<img width="277" alt="Screenshot 2021-09-12 at 18 06 35" src="https://user-images.githubusercontent.com/6705160/132994758-10b94d88-32cd-455c-98d4-998217a06ebf.png">

### Log file

N/A

**Comment by justinmk** [comment]
"bug" isn't the right label for this. `cmd_env` cannot and must not modify Nvim's $PATH or environment, that would be a strange surprising quirk. 

> 1. lspconfig rejects the LSP server setup [here](https://github.com/neovim/nvim-lspconfig/blob/1344a859864d4e6d23d3f3adf56d49e6386ec0d2/lua/lspconfig/util.lua#L262-L265) (`:LspInfo` will also display that the cmd [is not executable](https://github.com/neovim/nvim-lspconfig/blob/1344a859864d4e6d23d3f3adf56d49e6386ec0d2/lua/lspconfig/ui/lspinfo.lua#L38-L40))

      elseif vim.fn.executable(new_config.cmd[1]) == 0 then
        vim.notify(string.format('cmd [%q] is not executable.', new_config.cmd[1]), vim.log.levels.Error)
        return
      end

> Instead, I'd like to only configure an amended `PATH` in the `cmd_env` option, which will allow libuv to locate the executable when neovim's LSP client spawns it.

You can set `$PATH` in the editor I guess

    lua vim.cmd('let $PATH="..."')

 Then `executable()` will use that. Then you could restore it. 



> looking into changing the behaviour of https://github.com/williamboman/nvim-lsp-installer/ so that it, to the extent possible, doesn't alter the `cmd` and instead lets lspconfig take care of that

Without more insight, that seems like a clear "XY problem". Why _not_ modify `cmd`?

**Comment by williamboman** [comment]
> "bug" isn't the right label for this.

Ah sorry I just used the LSP client bug template which applied the labels for me.

> `cmd_env` cannot and must not modify Nvim's $PATH or environment, that would be a strange surprising quirk.

Totally agree on this! I guess what I'm after is deferring the "is executable" checks from both neovim core and lspconfig to `uv_spawn` itself, something along the lines of

```lua
local handle, pid = vim.loop.spawn(cmd, ...)
if not handle and pid == ENOENT then
  error(string.format("[%s] is not an executable.", cmd))
end
```

> You can set `$PATH` in the editor I guess
> 
> ```
> lua vim.cmd('let $PATH="..."')
> ```
> 
> Then `executable()` will use that. Then you could restore it.

Ah yeah I was thinking along these lines too! But then I realized that (if I understand lspconfig correctly) there will be scenarios where throughout the lifecycle of a LSP client, it will sort of re-instantiate itself (through for example the `on_new_config` hook) - and so 3rd party plugins will not have the ability to for example temporarily modify the `let $PATH` and then restore it.

> Without more insight, that seems like a clear "XY problem". Why not modify cmd?

I find it interesting for a couple of reasons:
1) It'd allow for reducing the room for possible drift in the ecosystem of LSP plugins. lspconfig would be able to more easily keep the status of being the "main custodian" of most-things-LSP, where in this case it'd dictate the commands used to spawn servers. The LSP installer plugins could then leverage this and reduce their scopes to just fill the function of amending the search path with the non-standard, local, install directories. I feel like this could probably also help with the triaging of issues in-between core and 3rd party plugins?
1) For practical reasons. It'd allow me to cut out so much boilerplate that is currently necessary and really just a replication with slight modifications of what's already in lspconfig, example:

```diff
diff --git "a/.\\too.lua" "b/.\\too1.lua"
index 8de5b29..6160eba 100644
--- "a/.\\too.lua"
+++ "b/.\\too1.lua"
@@ -1,47 +1,13 @@
-local util = require "lspconfig/util"
 local server = require "nvim-lsp-installer.server"
 local npm = require "nvim-lsp-installer.installers.npm"

--- Angular requires a node_modules directory to probe for @angular/language-service and typescript
--- in order to use your projects configured versions.
--- This defaults to the vim cwd, but will get overwritten by the resolved root of the file.
-local function get_probe_dir(root_dir)
-    local project_root = util.find_node_modules_ancestor(root_dir)
-
-    return project_root and (project_root .. "/node_modules") or ""
-end
-
-local default_probe_dir = get_probe_dir(vim.fn.getcwd())
-
 local root_dir = server.get_server_root_path "angularls"

-local executable_path = npm.executable(root_dir, "ngserver")
-
 return server.Server:new {
     name = "angularls",
     root_dir = root_dir,
     installer = npm.packages { "@angular/language-server" },
     default_options = {
-        cmd = {
-            executable_path,
-            "--stdio",
-            "--tsProbeLocations",
-            default_probe_dir,
-            "--ngProbeLocations",
-            default_probe_dir,
-        },
-        on_new_config = function(new_config, new_root_dir)
-            local new_probe_dir = get_probe_dir(new_root_dir)
-
-            -- We need to check our probe directories because they may have changed.
-            new_config.cmd = {
-                executable_path,
-                "--stdio",
-                "--tsProbeLocations",
-                new_probe_dir,
-                "--ngProbeLocations",
-                new_probe_dir,
-            }
-        end,
+        cmd_env = npm.env(root_dir),
     },
 }
```

Btw thanks for all your and the teams work on neovim, bravo!

**Comment by justinmk** [comment]
> I guess what I'm after is deferring the "is executable" checks from both neovim core and lspconfig to `uv_spawn` itself, something along the lines of
> 
> ```lua
> local handle, pid = vim.loop.spawn(cmd, ...)
> if not handle and pid == ENOENT then
>   error(string.format("[%s] is not an executable.", cmd))
> end
> ```

Ok I get it now :) You want `cmd_env` (which may contain a custom `$PATH`) to apply to any checks for the validity of `cmd`.

That makes sense. Mentioning libuv was throwing me off, it is irrelevant.



## Summary

- This particular request only applies to nvim-lspconfig AFAICT.
- Your specific suggestion would entail e.g. [lspinfo](https://github.com/neovim/nvim-lspconfig/blob/1344a859864d4e6d23d3f3adf56d49e6386ec0d2/lua/lspconfig/ui/lspinfo.lua#L38-L40) actually attempting to execute `cmd` to check if it's executable.
- Ugly: nvim-lspconfig could set-and-restore Nvim's env when it checks executable()
- Ideal: Nvim's `executable()` would take a `env` parameter.

**Comment by williamboman** [comment]
> Ok I get it now :) You want `cmd_env` (which may contain a custom `$PATH`) to apply to any `executable(cmd)` checks.

Exactly :)! Haha sorry I was under the impression that libuv also is responsible for locating the `cmd` path.

> This particular request only applies to nvim-lspconfig...

I believe neovim core is also impacted by this - [here](https://github.com/neovim/neovim/blob/413e86869ef147431a78946562c125938b41f533/runtime/lua/vim/lsp/rpc.lua#L325-L327).

**Comment by justinmk** [comment]
> I believe neovim core is also impacted by this - [here](https://github.com/neovim/neovim/blob/413e86869ef147431a78946562c125938b41f533/runtime/lua/vim/lsp/rpc.lua#L325-L327).

Ah thanks for tracking these down. If our LSP interface accepts `cmd_env` then it probably makes sense for all of those cases to use the pattern described above, encapsulated in a `lsp.util.cmd_executable()` function I suppose.

**Comment by justinmk** [comment]
> I believe neovim core is also impacted by this - [here](https://github.com/neovim/neovim/blob/413e86869ef147431a78946562c125938b41f533/runtime/lua/vim/lsp/rpc.lua#L325-L327).

Ah thanks for tracking these down. If our LSP interface accepts `cmd_env` then it probably makes sense for all of those cases to use the pattern described above, encapsulated in a `lsp.util.cmd_executable()` function I suppose.

- Can you send a PR? The `jobwait(jobstart(...))` pattern given in https://github.com/neovim/neovim/issues/15648#issuecomment-921707494 would be a way to achieve what you want.
    - replace the various cases you found, with the proposed `vim.lsp.util.cmd_executable()` function.
    - add a 1-line update to the [documentation](https://github.com/neovim/neovim/blob/8d7a64a09a99cd345d8c3e39ecf2434c77eaa05e/runtime/doc/lsp.txt#L839) for `{cmd_env}`, something like "also affects the search path of {cmd}".

**Comment by mjlbach** [comment]
@justinmk This is what I was talking about on matrix the other day, it would be pretty trivial to replicate vim.fn.executable with llibuv apis called via luv, which would allow us to check on PATH

**Comment by justinmk** [comment]
> it would be pretty trivial to replicate vim.fn.executable with llibuv apis called via luv, which would allow us to check on PATH from cmd_env

On Windows, executable() looks at $PATHEXT, this is not trivial.

So, what do you think about the `jobwait(jobstart(...))` pattern described above?

**Comment by mjlbach** [comment]
I'm concerned about potential overhead in jobstart/jobwait vs. just checking the executable bit (which I know doesn't work on windows), this is already handled-ish in the current vim.fn.executable implementation with the exception of PATHEXT/PATH.

**Comment by justinmk** [comment]
It's definitely slow, but why should LSP be checking executable() more than once per buffer (and LSP tasks are asynchronous, so...)

**Comment by mjlbach** [comment]
It's mostly the startup time I'm concerned about, which our users are extremely attentive to. This isn't asynchronous as it's called in start_client and would block during opening a new buffer with an unattached language server, not in a handler.

**Comment by justinmk** [comment]
> This isn't asynchronous as it's called in start_client and would block during opening a new buffer with an unattached language server, not in a handler.

The "executable" flag could cached/memoized, so a one-time sub-second hit per Nvim session per LSP server.

**Comment by mjlbach** [comment]
I think it's easier to just handle the failure of uv_spawn, #16430 does this
