### ISSUE TITLE
buftype=help propagates from help window to man buffer

### ISSUE THREAD

**Issue by ii14** [neovim/neovim#15650]
### Neovim version (nvim -v)

neovim-0.6.0~ubuntu1+git202109011157-284199bc4-adeb5640f

### Vim (not Nvim) behaves the same?

idk

### Operating system/version

Ubuntu 18.04.5 LTS

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

Neovim PPA

### How to reproduce the issue

`vim -u NORC`
`:Man man` - open some manpage
`:set bt?` - should print `buftype=nofile`
`:h` - open help
`<C-W><C-W><C-W>c` - go back to man window and close it
`:h` - focus help window
`:Man man` - open window with manpage again
`:set bt?` - prints `buftype=help`

### Expected behavior

man buffer should have `nofile` buftype.

### Actual behavior

`buftype=help` occasionally propagates from help to man buffer. As a result the next time you open help it opens in the man window, replacing the manpage.

**Comment by zeertzjq** [comment]
[This line](https://github.com/neovim/neovim/blob/685cf398130c61c158401b992a1893c2405cd7d2/runtime/autoload/man.vim#L59) seems to set `buftype=help` in this case.

**Comment by zeertzjq** [comment]
Maybe that's because `BufReadCmd` is not run for existing buffers.
