### ISSUE TITLE
Mouse drag select is offset when using 'vim.opt.mouse = 'a'' and 'vim.opt.showtabline = 2'

### ISSUE THREAD

**Issue by charbelnicolas** [neovim/neovim#15659]
### Neovim version (nvim -v)

0.6.0 commit 5fd21b8

### Vim (not Nvim) behaves the same?

I don't know, neovim 0.5 works correctly

### Operating system/version

Arch Linux

### Terminal name/version

Kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

Arch User Repository (AUR)

### How to reproduce the issue

Install neovim-git from AUR and set vim.opt.mouse = 'a' and 'vim.opt.showtabline = 2' in your config.

Then, try to select some text with your mouse by dragging it and watch how it selects the lower or upper line instead of the line you are really trying to select.

Here is a video I've since deleted:

[Reddit Post](https://www.reddit.com/r/neovim/comments/pnpyd5/is_mouse_drag_select_broken_in_neovim_nightly_for/)

### Expected behavior

I expect the dragging of the mouse to select only what I want and not something else.

### Actual behavior

When I drag the mouse cursor over a line of text, it actually selects the upper or lower line.

**Comment by zeertzjq** [comment]
I cannot reproduce this with `nvim --clean` (then running `:lua vim.opt.mouse = 'a'`), same commit and same terminal.

**Comment by charbelnicolas** [comment]
> I cannot reproduce this with `nvim --clean` (then running `:lua vim.opt.mouse = 'a'`), same commit and same terminal.

You are right, I cannot reproduce it either with nvim --clean. Must be a weird keybind then? I don't have the craziest of configs though... who knows.

**Comment by charbelnicolas** [comment]
> I cannot reproduce this with `nvim --clean` (then running `:lua vim.opt.mouse = 'a'`), same commit and same terminal.

I found the culprit, it's the tab line at the top that causes the issue and it is definitely a bug.

Try using ```vim.opt.showtabline = 2``` along with ```vim.opt.mouse = 'a'```

**Comment by zeertzjq** [comment]
> > I cannot reproduce this with `nvim --clean` (then running `:lua vim.opt.mouse = 'a'`), same commit and same terminal.
> 
> I found the culprit, it's the tab line at the top that causes the issue and it is definitely a bug.
> 
> Try using `vim.opt.showtabline = 2` along with `vim.opt.mouse = 'a'`

I can reproduce this.

**Comment by zeertzjq** [comment]
Seems to be introduces by #12667.

**Comment by numbcoder** [comment]
I also had this bug when I updated neovim to the lastest commit yesterday.
NVIM v0.6.0-dev+262-g643cb8a6e

**Comment by justinmk** [comment]
cc @vhakulinen

**Comment by Kethku** [comment]
Could it be related to https://github.com/neovim/neovim/issues/13416?

**Comment by zachliu** [comment]
isn't this ironic?
if we're so into tools like neovim and call ourselves hard-core programmer, why the hell am i using the mouse? :joy:

**Comment by zeertzjq** [comment]
I guess #15813 will fix this.

**Comment by charbelnicolas** [comment]
> I guess #15813 will fix this.

I hope so, I'm so used to the tab line.... It hurts not having it.

**Comment by charbelnicolas** [comment]
> I guess #15813 will fix this.

It's fixed now!
