### ISSUE TITLE
Foreground Color of Cursor ignores Color Scheme

### ISSUE THREAD

**Issue by smeikx** [neovim/neovim#15673]
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

yes, 8.2.3441

### Operating system/version

Gentoo Linux

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

Gentoo’s Package Manager

### How to reproduce the issue

nvim -u NONE
:set termguicolors
:set guicursor=n-v-c:block-Cursor/lCursor,i-ci-ve:ver25-Cursor2/lCursor2,r-cr:hor20,o:hor50
:color desert  " or any other scheme where guifg and guibg for Cursor are set

### Expected behavior

The color or the character under the cursor should match the one specified by `hi Cursor guifg`.

### Actual behavior

The color of the character under the cursor is controlled by the terminal’s configuration.

**Comment by smeikx** [comment]
I have now tried other terminal emulators (iTerm2, Alacritty, Termnal.app; the latest release of each), with the exact same result as described above.

**Comment by smeikx** [comment]
Is it even possible to change the foreground color of the cursor? [Here](https://github.com/neovim/neovim/issues/12796#issuecomment-682152303) I have found a command to test if the terminal supports changing the cursor’s background color (to red): `printf "\x1b]12;rgb:ffff/0000/0000\x1b\\"`.  

Unfortunately, I could not find the code for changing the foreground color. Does it even exist?

**Comment by justinmk** [comment]
> Is it even possible to change the foreground color of the cursor?

you mean, you want the text in the cursor to change color, not the cursor itself? Not supported in TUI. 

see also https://github.com/neovim/neovim/issues/7488

**Comment by smeikx** [comment]
> Not supported in TUI.

Thank you for clearing that up. But would it be possible?  
Is there a standard way of instructing a terminal emulator to change the text color of the character under the cursor?
