### ISSUE TITLE
[LSP] `start` & `end` in `range` of `vim.lsp.diagnostic.get` are always empty tables

### ISSUE THREAD

**Issue by fdschmidt93** [neovim/neovim#15689]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+284-gc2a65921d

### Vim (not Nvim) behaves the same?

doesn't apply

### Operating system/version

Arch Linux x86_64 

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

AUR: neovim-git

### How to reproduce the issue

Open files with LSP attached that produce diagnostics for the opened file
Do `:lua print(vim.inspect(vim.lsp.diagnostic.get(0)))`

### Expected behavior

`start` and `end` in `range` of a diagnostic should not be empty tables which they seemingly are for any diagnostic (tested on Pyright and Sumneko). This does not apply to `vim.lsp.diagnostic.get_all`.

### Actual behavior

Populate `range` adequately such that plugins levering `vim.lsp.diagnostic.get` like telescope do not break. Thanks in advance for taking a look :)

**Comment by clason** [comment]
That is a bug (although these functions are deprecated; Telescope should probably move to using functions from `vim.diagnostic` if that is not `nil`.)

The issue is in this block: https://github.com/neovim/neovim/blob/4881456e83fb49994677fe06aef3b0c597ba4517/runtime/lua/vim/lsp/diagnostic.lua#L260-L269

If you pass the `client_id` like `print(vim.inspect(vim.lsp.diagnostic.get(0,1)))`, you get correct locations.

**Comment by clason** [comment]
D'oh! The table `all_diagnostics` is already converted to `lsp` format -- so trying to do it again in that block fails. Try
```diff
diff --git a/runtime/lua/vim/lsp/diagnostic.lua b/runtime/lua/vim/lsp/diagnostic.lua
index 48c0dd92c..eef840bee 100644
--- a/runtime/lua/vim/lsp/diagnostic.lua
+++ b/runtime/lua/vim/lsp/diagnostic.lua
@@ -265,7 +265,7 @@ function M.get(bufnr, client_id, predicate)
         table.insert(all_diagnostics, diagnostic)
       end
     end)
-    return diagnostic_vim_to_lsp(all_diagnostics)
+    return all_diagnostics
   end
…
   local namespace = M.get_namespace(client_id)
```
