### ISSUE TITLE
[LSP] diagnostic.lua:634: Expected 3 arguments

### ISSUE THREAD

**Issue by ray-x** [neovim/neovim#15686]
### Neovim version (nvim -v)

v0.6.0-dev+284-gc2a65921d

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

source code build

### How to reproduce the issue

E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/diagnostic.lua:634: Expected 3 arguments  
```
634:    vim.api.nvim_echo({"No more valid diagnostics to move to", "WarningMsg"})
```

### Expected behavior

shoudl output `No more valid diagnostics to move to`

### Actual behavior

Shows E5108

**Comment by clason** [comment]
You need to add actual reproducing steps (together with minimal example); I don't get any such error.

**Comment by ray-x** [comment]
The way nvim_echo API is using is incorrect!
try running it in cmd
```
:lua vim.api.nvim_echo({"No more valid diagnostics to move to", "WarningMsg"})
 ```
You will see the error.  The error message is self explanatory, `nvim_echo` need 3 arguments. Line 634 only pass 1 argument.

@gpanders introduce this issue.

**Comment by clason** [comment]
Try https://github.com/neovim/neovim/pull/15687

**Comment by ray-x** [comment]
I think it should be something like this:

    vim.api.nvim_echo({{"No more valid diagnostics to move to", 'WarningMsg'}}, true, {})

**Comment by clason** [comment]
Yes, that's right -- that's what I did?

**Comment by ray-x** [comment]
Thanks. Should be able to close once it merged.
