### ISSUE TITLE
build: Enable linking with LLD by default when available

### ISSUE THREAD

**Issue by kylo252** [neovim/neovim#15681]
### Feature description

I have been compiling from source a lot lately and one thing that stood out to me was how long the linking stage took, so I went ahead and did some testing. 

I got the linker command like this

```bash
ninja -C build -t commands bin/nvim | tail -1 
```

Here are the timings on my laptop with a 4c/8t processor:

<table>
<tr> 
	<td>
	<td> GNU ld
	<td> lld
<tr>
	<td> time
	<td> 25.31s
	<td> 0.01s
</table>

Yes, you read that right! It's less than 200ms for `lld`. Even `gold` was around 25s for me as well.

Here are some benchmark results on a 12c/24t processor:

```c#
$ hyperfine 'bash linker.sh' --runs 10
Benchmark #1: bash linker.sh
  Time (mean ± σ):     16.413 s ±  0.164 s    [User: 15.578 s, System: 0.798 s]
  Range (min … max):   16.187 s … 16.599 s    10 runs

$ hyperfine 'bash lld_linker.sh' --runs 10
Benchmark #1: bash lld_linker.sh
  Time (mean ± σ):     135.0 ms ±   2.4 ms    [User: 122.7 ms, System: 94.8 ms]
  Range (min … max):   132.5 ms … 139.8 ms    10 runs
```

I know it's trivial with anyone who's familiar with linkers to change this manually or system wide, but I still thought it could be useful since there's already a target using `clang` so it would be a matter of adding `--fuse-ld=lld` to `CMAKE_EXE_LINKER_FLAGS`.

If there's enough interest, I can make a PR and add it either as a flag, or as part of a complete toolchain file for CMake.

**Comment by justinmk** [comment]
Debug build skips link-time optimization (LTO) so it won't take so long.  https://github.com/neovim/neovim/pull/8654/



> could be useful since there's already a target using `clang` so it would be a matter of adding `--fuse-ld=lld` to `CMAKE_EXE_LINKER_FLAGS`.

Sounds great. Are you certain that `lld` is doing LTO?  I wonder if CMake `CheckIPOSupported` is actually just skipping LTO in the `lld` case.

**Comment by kylo252** [comment]
You were right, that flag is actually missing for clang.

```diff
@@ -1,883 +1,883 @@
 [
   {
     "directory": "/home/hatsu/.local/share/neovim/build",
-    "command": "/usr/bin/clang -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/auto/lua_api_c_bindings.generated.c.o -MF src/nvim/CMakeFiles/nvim.dir/auto/lua_api_c_bindings.generated.c.o.d -o src/nvim/CMakeFiles/nvim.dir/auto/lua_api_c_bindings.generated.c.o -c src/nvim/auto/lua_api_c_bindings.generated.c",
+    "command": "/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g  -Og -g -flto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/auto/lua_api_c_bindings.generated.c.o -MF src/nvim/CMakeFiles/nvim.dir/auto/lua_api_c_bindings.generated.c.o.d -o src/nvim/CMakeFiles/nvim.dir/auto/lua_api_c_bindings.generated.c.o -c src/nvim/auto/lua_api_c_bindings.generated.c",
     "file": "src/nvim/auto/lua_api_c_bindings.generated.c",
     "output": "src/nvim/CMakeFiles/nvim.dir/auto/lua_api_c_bindings.generated.c.o"
   },
   {
     "directory": "/home/hatsu/.local/share/neovim/build",
-    "command": "/usr/bin/clang -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/__/__/config/auto/pathdef.c.o -MF src/nvim/CMakeFiles/nvim.dir/__/__/config/auto/pathdef.c.o.d -o src/nvim/CMakeFiles/nvim.dir/__/__/config/auto/pathdef.c.o -c config/auto/pathdef.c",
+    "command": "/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g  -Og -g -flto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -MD -MT src/nvim/CMakeFiles/nvim.dir/__/__/config/auto/pathdef.c.o -MF src/nvim/CMakeFiles/nvim.dir/__/__/config/auto/pathdef.c.o.d -o src/nvim/CMakeFiles/nvim.dir/__/__/config/auto/pathdef.c.o -c config/auto/pathdef.c",
     "file": "config/auto/pathdef.c",
     "output": "src/nvim/CMakeFiles/nvim.dir/__/__/config/auto/pathdef.c.o"
   },
```

It's not a problem for `lld` however:

> Link-time optimization (LTO) is supported by default. Essentially, all you have to do to do LTO is to pass the -flto option to clang. Then clang creates object files not in the native object file format but in LLVM bitcode format. LLD reads bitcode object files, compile them using LLVM and emit an output file. Because in this way LLD can see the entire program, it can do the whole program optimization.

I'll report again once I have done some more testing with that flag enabled.

**Comment by zchee** [comment]
@justinmk FYI, lld macOS (lld new Mach-O frontend) driver can use(linking) Neovim at least my machine.

In Linux, almost should be working. In FreeBSD, lld has been default linker after 13. So I think this proposal would be make sense.

**Comment by dundargoc** [comment]
I'm opting to close this as there didn't seem to be any actual performance benefits if I interpreted it correctly, nor any indication that lld is actually faster.

**Comment by dundargoc** [comment]
I think I need at least 5 more links to be convinced that lld is faster /s

Anyway, I don't understand the point then. lld might be faster, but it also doesn't do any LTO? Then what does it matter. Linking with ld takes 0 seconds on neovim with LTO as well.

> it might be worth it to investigate why CMake is ignoring LTO for clang.

Please do.

**Comment by dundargoc** [comment]
Then we need to investigate why clang doesn't enable LTO and fix it, not a priori assume that lld is faster or that it will be worth implementing.

**Comment by dundargoc** [comment]
LTO is enabled when using clang

```bash
cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang --fresh -DENABLE_LTO=OFF
hyperfine "cmake --build build --clean-first"

cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang --fresh -DENABLE_LTO=ON
hyperfine "cmake --build build --clean-first"

git diff --color -U0 --word-diff --no-index -- before after | grep -v ^@@
```

gives the following benchmark:

```
Benchmark 1: Without LTO
  Time (mean ± σ):      1.754 s ±  0.024 s    [User: 12.595 s, System: 5.733 s]
  Range (min … max):    1.719 s …  1.792 s    10 runs

Benchmark 2: With LTO
  Time (mean ± σ):      7.629 s ±  0.073 s    [User: 79.694 s, System: 5.968 s]
  Range (min … max):    7.488 s …  7.702 s    10 runs
```

Looking at `build/build.ninja`, there is also an extra `-flto=thin` flag.

Furthermore, lld is already the default linker for clang on linux, so I'd suggest to just use clang instead of gcc if you want lld.
