### ISSUE TITLE
Overriding signs in the new diagnostic namespace?

### ISSUE THREAD

**Issue by fsouza** [neovim/neovim#15684]
### Feature already in Vim?

N/A

### Feature description

Wasn't sure whether to report as a bug (could call it a regression 🙈) or feature request (it's something I'd like to be able to), but here we are.

After #15585 was merged, I am no longer able to redefine the signs used for diagnostics (I like setting the text so I don't have a signcolumn, having a diagnostic just causes the linenumber to change color). The signs are defined whenever the diagnostics are displayed for the first time, so overriding it is very tricky.

I'm using a weird workaround for now:

Override the handler for publishDiagnostics so it:

1. Calls vim.lsp.diagnostic.on_publish_diagnostics
2. Checks whether there are any diagnostics in the result
3. If so, redefine the signs, call vim.diagnostic.reset and call vim.lsp.diagnostic.on_publish_diagnostics again (yes, it's awful)

Here is the code if anyone is interested: https://github.com/fsouza/dotfiles/blob/758eb06e94eaaf8ba3513da878615610f1b2ed2b/nvim/lua/fsouza/lsp/buf_diagnostic.lua#L42-L51

I imagine some other plugins will want to override the signs too (with emojis and what not), so this is probably a legit use-case?

Perhaps I'm missing something though, so please feel free to tell I'm just wrong :)

**Comment by spywhere** [comment]
I faced the same issue here today after rebuild to the latest master. I have migrated most of my setup to a new API, but sign definitions are getting overridden as state in the original issue above.

**Comment by justinmk** [comment]
> The signs are defined whenever the diagnostics are displayed for the first time, so overriding it is very tricky.
> 
> I'm using a weird workaround for now:

what is non-workaround sample code that you expect to work?

**Comment by fdschmidt93** [comment]
Related, docs conflict on how to define the respective signs:

`:h diagnostic-signs`

```viml
	sign define DiagnosticSignError text=E texthl=DiagnosticSignError linehl= numhl=
	sign define DiagnosticSignWarning text=W texthl=DiagnosticSignWarning linehl= numhl=
	sign define DiagnosticSignInformation text=I texthl=DiagnosticSignInformation linehl= numhl=
	sign define DiagnosticSignHint text=H texthl=DiagnosticSignHint linehl= numhl=
```

whereas `:h diagnostic-highlight`

```viml
						*hl-DiagnosticSignError*
DiagnosticSignError
  Used for "Error" signs in sign column.

						*hl-DiagnosticSignWarn*
DiagnosticSignWarn
  Used for "Warn" signs in sign column.

						*hl-DiagnosticSignInfo*
DiagnosticSignInfo
  Used for "Info" signs in sign column.

						*hl-DiagnosticSignHint*
DiagnosticSignHint
  Used for "Hint" signs in sign column.
```

A non-workaround sample code on my end would be for something like the below to work wherever I define highlights and sign at neovim startup (signs might be incorrectly shown as my brower fonts are a bit borked).

```lua
local signs = { "", "", "", "" }
local diagnostic_types = { "Error", "Warn", "Info", "Hint" } -- or Warning, Information, ... 
for i = 1, #diagnostic_types do
  local diagnostic_type = string.format("DiagnosticSign%s", diagnostic_types[i])
  local opts = {
    text = signs[i],
    texthl = string.format("Diagnostic%s", diagnostic_types[i]),
    linehl = "",
    numhl = "",
  }
  vim.fn.sign_define(diagnostic_type, opts)
end
```

Another related change:  `vim.diagnostic.severity` now defines severity groups in capital letters (`ERROR`) whereas `vim.lsp.protocol.DiagnosticSeverity` only capitalizes the first letter (`Error`) as per [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#diagnosticSeverity). Ignore if this is an intentional change.

**Comment by fsouza** [comment]
> > The signs are defined whenever the diagnostics are displayed for the first time, so overriding it is very tricky.
> > 
> > I'm using a weird workaround for now:
> 
> what is non-workaround sample code that you expect to work?

Previously, I was able to simply define them, like in init.lua.

I think it makes sense that neovim defines the default ones: it's a resource owned by core. Perhaps the user could customize the signs, maybe passing as a config to the on_publish_diagnostics handler?

Then _set_signs would take that as a parameter and create and user the default ones whenever the parameter is omitted.

Alternatively, we could introduce a boolean flag telling _set_signs to not define the default signs (and pass that via on_publish_diagnostics), but idk boolean flags are pretty much always a smell.

**Comment by gpanders** [comment]
Does #15696 fix the issue?

**Comment by spywhere** [comment]
> Does #15696 fix the issue?

That works for me

**Comment by fsouza** [comment]
> Does #15696 fix the issue?

Sorry hectic day today, can't test it until later in the evening. The PR looks correct though, and @spywhere confirmed it fixes the issue for them, so I'd say ship it 😁

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/15696
