### ISSUE TITLE
Strange interaction between cursorbind and conceallevel

### ISSUE THREAD

**Issue by tpope** [neovim/neovim#15692]
### Neovim version (nvim -v)

0.4.4, 0.5.0, 685cf398130c61c158401b992a1893c2405cd7d2

### Vim (not Nvim) behaves the same?

no, vim 8.2.2434

### Operating system/version

Ubuntu 21.04

### Terminal name/version

Xterm(361)

### $TERM environment variable

xterm-256color

### Installation

compiled

### How to reproduce the issue

```
nvim -u NONE
:20vsplit /etc/passwd
:set conceallevel=2
:windo set nowrap scrollbind cursorbind
iabcdefghijklmnopqrstuvwxyz
```

### Expected behavior

Vertical split on left stays put.

### Actual behavior

Vertical split scrolls horizontally to reflect cursor position. And with larger files, performance is excruciatingly slow.

Note that updating the cursor column is correct. The preemptive redraw with `'conceallevel'` is the anomaly.

**Comment by zeertzjq** [comment]
Hmm, Vim also sometimes does this horizontal scrolling when `'cursorline'` is set.

**Comment by zeertzjq** [comment]
Bram thinks the horizontal scrolling is correct: <https://github.com/vim/vim/issues/10014>.

**Comment by tpope** [comment]
I have no strong feelings either way. It's the abysmal performance with large files that drew my attention, but Vim fairs no better here than with Neovim.
