### ISSUE TITLE
Substitution doesn't escape searching

### ISSUE THREAD

**Issue by LamprosPitsillos** [neovim/neovim#15691]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+286-g4881456e8 Build type: RelWithDebInfo LuaJIT 2.0.5 Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/inferno/.cache/paru/clone/neovim-git/src/build/config -I/home/inferno/.cache/paru/clone/neovim-git/src/neovim-git/src -I/usr/include -I/home/inferno/.cache/paru/clone/neovim-git/src/build/src/nvim/auto -I/home/inferno/.cache/paru/clone/neovim-git/src/build/include Compiled by inferno  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"

### Vim (not Nvim) behaves the same?

Yes, vim-8.2.3441-1

### Operating system/version

Artix Linux x86_64 

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

AUR

### How to reproduce the issue

cal --color=always | nvim -u NONE -
```:%s/^[[7m\(.*\)^[[27m/\1/g```

### Expected behavior

![Window_nvimbug](https://user-images.githubusercontent.com/61395246/133770467-f65f7a60-bf9d-43fc-bca0-ed8092451cce.png)
 Since it finds it it should be able to replace.

### Actual behavior

![Window_nvimbug2](https://user-images.githubusercontent.com/61395246/133770480-618365c0-0667-4156-812c-009a56394c39.png)
E486: Pattern not found: ^[[7m\(.*\)^[[27m/\1/g

**Comment by zeertzjq** [comment]
You need to use `:%s/^[\[7m\(.*\)^[\[27m/\1/g`.

**Comment by LamprosPitsillos** [comment]
> You need to use `:%s/^[\[7m\(.*\)^[\[27m/\1/g`.

Most likely but why does it get highlighted?

**Comment by zeertzjq** [comment]
> > You need to use `:%s/^[\[7m\(.*\)^[\[27m/\1/g`.
> 
> Most likely but why does it get highlighted?

What do you mean by "highlighted"?

**Comment by zeertzjq** [comment]
> You need to use `:%s/^[\[7m\(.*\)^[\[27m/\1/g`.

You can also use `:%s/\V^[[7m\(\.\*\)^[[27m/\1/g`. (See `:help /magic`) I don't know why `:%s/\M^[[7m\(\.\*\)^[[27m/\1/g` doesn't work though.

**Comment by zeertzjq** [comment]
Oh, this indeed seems a bug.

**Comment by zeertzjq** [comment]
I have opened <https://github.com/vim/vim/issues/8883>.

**Comment by zeertzjq** [comment]
See `:help E769`.

**Comment by justinmk** [comment]
>  [vim/vim#8883](https://github.com/vim/vim/issues/8883)
>
>>  I believe Vim is being a bit smart when searching and detects that `/[` the user is actually trying to match a square bracket and not a regex collation. This breaks, when doing a substitution, perhaps because of the delimiter or such.
