### ISSUE TITLE
`vim.{diagnostic, lsp.diagnostic}.show_line_diagnostics()` show all diagnostic instead of current line

### ISSUE THREAD

**Issue by etrnal70** [neovim/neovim#15690]
### Neovim version (nvim -v)

v0.6.0-dev+285-gc13242cf4

### Language server name/version

tested on pyright and rust-analyzer

### Operating system/version

linux

### Steps to reproduce using "nvim -u minimal_init.lua"

1. Open a project file
2. Go to line with error
3. `lua vim.lsp.diagnostic.show_line_diagnostics()`

### Expected behavior

Floating window with only current line diagnostic

### Actual behavior

Show all diagnostic on buffer

![image](https://user-images.githubusercontent.com/5826834/133750868-838574f1-0666-47f3-b6a4-2221df2217e0.png)

**Comment by etrnal70** [comment]
Btw currently for displaying line diagnostic, can use `vim.diagnostic.show_position_diagnostics()`. It's just that show_line_diagnostics currently is misleading

**Comment by clason** [comment]
This is another functional regression: The new version no longer defaults to the current line if `linenr` is omitted.

**Comment by clason** [comment]
Can you try the following patch?
```diff
diff --git a/runtime/lua/vim/diagnostic.lua b/runtime/lua/vim/diagnostic.lua
index 893d0d5cb..1775b8f7e 100644
--- a/runtime/lua/vim/diagnostic.lua
+++ b/runtime/lua/vim/diagnostic.lua
@@ -1049,7 +1049,7 @@ function M.show_line_diagnostics(opts, bufnr, lnum)
 
   opts = opts or {}
   opts.focus_id = "line_diagnostics"
-  opts.lnum = lnum
+  opts.lnum = lnum or (vim.api.nvim_win_get_cursor(0)[1] - 1)
   local line_diagnostics = M.get(bufnr, opts)
   return show_diagnostics(opts, line_diagnostics)
 end
```
