### ISSUE TITLE
`DiagnosticSign*` signs are reverted to default values when first lsp diagnostic is displayed.

### ISSUE THREAD

**Issue by pbogut** [neovim/neovim#15694]
### Neovim version (nvim -v)

v0.6.0-dev+286-g4881456e8

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ArchLinux

### Terminal name/version

urxvt v9.26

### $TERM environment variable

xterm-256color

### Installation

AUR repository (neovim-git)

### How to reproduce the issue

Open Nvim with configured lsp.

`:sign define DiagnosticSignError text=X texthl=DiagnosticSignError linehl= numhl=`

`sign list DiagnosticSignError` will produce:
`sign DiagnosticSignError text=X  linehl= texthl=DiagnosticSignError numhl=`

Without closing neovim open file with lsp error.
`sign list DiagnosticSignError` will produce:
`sign DiagnosticSignError text=E  linehl= texthl=DiagnosticSignError numhl=`

### Expected behavior

Keep X as text sign for lsp errors.

### Actual behavior

X is overriden by default E sign for lsp errors.

Only happens when first error is displayed, if I change sign after that everything works as expected.

**Comment by justinmk** [comment]
is this different than https://github.com/neovim/neovim/issues/15684 ?

**Comment by pbogut** [comment]
Nope, it's the same. Sorry for duplication, didn't see it when I was looking for this issue.
