### ISSUE TITLE
404 when trying to download nightly neovim

### ISSUE THREAD

**Issue by hood** [neovim/neovim#15707]
### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

no

### Operating system/version

na

### Terminal name/version

na

### $TERM environment variable

na

### Installation

na

### How to reproduce the issue

https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz returns a 404 error, making it impossible to update the software.

### Expected behavior

Being able to update neovim.

### Actual behavior

Unable to update neovim because the archive containing nightly release is not being served under the usual url.

**Comment by clason** [comment]
Nightly builds fail sometimes; that is a known issue (and reported regularly). The only sure-fire way to follow HEAD closely is to build from source yourself. (This will also allow you to bisect problems and revert to last-known-good commits, which is very important when testing the bleeding edge.)

**Comment by hood** [comment]
The problem is I'm using the `yay` package manager to manage my NeoVim installation. As the `AUR` version is not updated regularly, I manually retrigger the update (`yay -u nvim-nightly-bin` in my case). This is now impossible due to the build not being reachable. If it's a temporary issue no problem tho.

**Comment by clason** [comment]
Doesn't AUR have a `neovim-git`? That should always get you the latest version. ("Nightly" is not special in any way, it's just the commit that happens to be latest when the workflow runs. It can be badly broken if you're unlucky...)

**Comment by clason** [comment]
And I know that before the 0.5 release, there was chorus of "just use nightly already, it's fine" (of which I was a part), but now that we _do_ have 0.5.x releases, that's no longer such a clear recommendation -- a lot more breaking changes happen on master, and I think following it _blindly_ by automated installation of nightlies is dangerous. It's better to update manually (both Neovim and plugins) and pay attention to the changes to avoid surprises. (And, as a corollary, _don't_ update when you have to do actual work and rely on a working installation...)

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/issues/15709
