### ISSUE TITLE
Certain buffers have incorrect line number highlighting

### ISSUE THREAD

**Issue by b0o** [neovim/neovim#15719]
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

unknown

### Operating system/version

Linux 5.14.2-arch1-2 GNU/Linux

### Terminal name/version

Same behavior with `alacritty 0.10.0-dev (58985a4d)` and `kitty 0.23.1`

### $TERM environment variable

Same behavior with `screen-256color` and `xterm-256color`

### Installation

pacman

### How to reproduce the issue

This bug is very difficult to reproduce. It happens to me regularly, but every time I attempt to reproduce it from scratch I am unable to. If it does happen, it is after I do one of the following things (this list is not exhaustive):

- `:split`
- `:vsplit`
- `:buffer <existing bufid>`
- `:new | buffer <existing bufid>`

There seems to be some pre-condition that’s necessary to reproduce the bug and I can't figure out what it is. However, it happens to me in my normal workflow on average 3-4 times per day so it is not exceedingly rare.

Since it's so difficult to reproduce, I haven't been able to reproduce with a minimal config.

### Expected behavior

Line numbers other than the cursor line should be highlighted with the `LineNr` highlight group; the cursor line number should be highlighted with the `CursorLineNr` highlight group.

### Actual behavior

All line numbers are highlighted with the `CursorLineNr` highlight group. If the affected buffer is split or otherwise opened in another window, the bug persists in the new window. Other windows/buffers are not affected.

https://user-images.githubusercontent.com/21299126/133923028-7556647f-f89d-4e86-9251-88c2f4bd0c09.mp4

**Comment by justinmk** [comment]
Possibly a plugin is doing `:hi link` in the other window?


Can you try Nvim development version?

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built packages for Linux/Windows/macOS.
- Check `:version` to confirm that you are using the latest version.

**Comment by b0o** [comment]
I haven’t seen this issue since I upgraded to 0.6. I will re-open if it does reappear.
