### ISSUE TITLE
path-related error from lualine trying to load theme

### ISSUE THREAD

**Issue by dimbleby** [neovim/neovim#15714]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+301-g340f77e78

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ubuntu 20.04

### Terminal name/version

wsltty

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

I am using [shadmansaleh/lualine](https://github.com/shadmansaleh/lualine.nvim) installed via packer

```
  use {
    'shadmansaleh/lualine.nvim',
    config = [[require('lualine-config')]]
  }
```
where that lualine-config is:
```
require('lualine').setup {
  options = {
    icons_enabled = false,
    theme = 'gruvbox'
  }
}
```

### Expected behavior

No errors. gruvbox theme is used by lualine.

### Actual behavior

```
E5108: Error executing lua ...k/packer/start/lualine.nvim/lua/lualine/utils/loader.lua:232: lua/lualine/themes/gruvbox.lua Not found
```

Error is coming from [this line](https://github.com/shadmansaleh/lualine.nvim/blob/c5cb601a6ac3390c9e872c19a54f7371aa61f542/lua/lualine/utils/loader.lua#L232).

It should be finding [`lualine.nvim/lua/lualine/themes/gruvbox.lua`](https://github.com/shadmansaleh/lualine.nvim/blob/master/lua/lualine/themes/gruvbox.lua), I think.

Broken as at 396280d3030685c6b7c4d962f24bb5171a735b47

**Comment by dimbleby** [comment]
Possibly this is expected since I now see that the message for that commit talks about 

> Now remove the addition of "start/*" packages ...

On the other hand the commit message also calls this a refactor, which suggests that it wasn't intended to be breaking?

**Comment by justinmk** [comment]
depends on how lualine searches for runtime files. is it using `globpath(&rtp,...)` ?

**Comment by dimbleby** [comment]
https://github.com/shadmansaleh/lualine.nvim/blob/c5cb601a6ac3390c9e872c19a54f7371aa61f542/lua/lualine/utils/loader.lua#L227-L229

https://github.com/shadmansaleh/lualine.nvim/blob/c5cb601a6ac3390c9e872c19a54f7371aa61f542/lua/lualine_require.lua#L46-L58

**Comment by justinmk** [comment]
thanks, so it is inspecting &rtp: 

    for dir in vim.gsplit(vim.api.nvim_get_option 'rtp', ',') do

**Comment by shadmansaleh** [comment]
This is not an neovim issue . This was due to  [documented breaking change](https://github.com/neovim/neovim/issues/14090#issuecomment-922327377) made by #15632

lualine will fix the incompatibility in it in plugin side .

This issue should be closed .

**Comment by justinmk** [comment]
@shadmansaleh thanks :) but we are still collecting feedback on this change so I'll keep this open. We need to get a sense of how many cases there are in the wild, and whether we need to adjust our strategy.

**Comment by shadmansaleh** [comment]
Glad to hear that . `nvim_list_runtime_paths` is basically direct replacement for searching &rtp that's why this is non issue .

But I think more serious issue is the one reported by [clason](https://github.com/neovim/neovim/pull/15632#issuecomment-922346901) and [ironE](https://github.com/neovim/neovim/pull/15632#issuecomment-922393768) .

**Comment by shadmansaleh** [comment]
The issue on lualine has been fixed with https://github.com/shadmansaleh/lualine.nvim/commit/ebea516ac7f8fc22604728c2193388992ef4e9ec

**Comment by spindensity** [comment]
> @shadmansaleh thanks :) but we are still collecting feedback on this change so I'll keep this open. We need to get a sense of how many cases there are in the wild, and whether we need to adjust our strategy.

@justinmk 

Some paths returned by `nvim_list_runtime_paths` have a trailing path separator, others don't, could that cause some compatible problems?

Execute `lua for k, v in pairs(vim.api.nvim_list_runtime_paths()) do print(v) end`, the results are:
![Snipaste_2021-09-19_14-10-31](https://user-images.githubusercontent.com/33576822/133917427-7e38206f-9e6e-4907-a3fc-f8c786a6f700.png)

**Comment by shadmansaleh** [comment]
Looks like only start plugins have trailing path separator.

**Comment by bfredl** [comment]
Is this still an issue? We hare fixed a bunch of packpath issues, in particular, no extra trailing slash will be added.

**Comment by shadmansaleh** [comment]
As I [stated earlier](https://github.com/neovim/neovim/issues/15714#issuecomment-922406072) this issue has been long fixed in lualine by utilizing `nvim_get_runtime_file`.
