### ISSUE TITLE
math.randomseed returns nil

### ISSUE THREAD

**Issue by s1n7ax** [neovim/neovim#15724]
### Neovim version (nvim -v)

NVIM v0.5.0 Build type: Release LuaJIT 2.0.5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux: up to date

### Terminal name/version

suckless st

### $TERM environment variable

st-256color

### Installation

pacman official repositories

### How to reproduce the issue

Run following command on neovim

```
lua print(math.randomseed(os.time()))
```

### Expected behavior

print a random number similar to following `1632067011      0`

### Actual behavior

function returns nil so nothing is printed

**Comment by clason** [comment]
`math.randomseed()` sets the seed (starting value) for the pseudo random number generator; it does _not_ return a random number, that's `math.random()`.
