### ISSUE TITLE
Neovim fails to build luarocks in Homebrew with OS X 10.10.1

### ISSUE THREAD

**Issue by kamitchell** [neovim/neovim#1573]
Thought I'd give it a try and see how it's progressing, but frustation :disappointed:

Tried updating and upgrading Homebrew, reinstalling autoconf and autotools, and some other fiddling. It's just beyond my understanding.

Anyway, the log files from the builds are in [this gist](https://gist.github.com/kamitchell/369dfed5c96ef966be02).

**Comment by madis** [comment]
I'm getting the same error as @jeffpamer on OS X 10.9.5 with ```brew reinstall --HEAD neovim```. Any suggestions?

**Comment by aktau** [comment]
I'm afraid the error is a bit too sparse. Can you try to do that homebrew build verbosely?

**Comment by dlikhten** [comment]
Same issue. 

    ==> Cloning https://github.com/neovim/neovim.git
    git --git-dir /Library/Caches/Homebrew/neovim--git/.git status -s
    Updating /Library/Caches/Homebrew/neovim--git
    git config remote.origin.url https://github.com/neovim/neovim.git
    git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
    git fetch origin
    git checkout -f master --
    Already on 'master'
    Your branch is up-to-date with 'origin/master'.
    git reset --hard origin/master
    HEAD is now at 8d51d7e Merge PR #1863 'Fix tests for plain lua'
    ==> Checking out branch master
    git checkout-index -a -f --prefix=/private/tmp/neovim-TYGZwA/
    ==> Patching
    ==> make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/usr/local/Cellar/neovim/HEAD" install
    mkdir -p .deps
    cd .deps && \
    		cmake -G 'Unix Makefiles'  \
    		 ../third-party
    -- The C compiler identification is AppleClang 6.0.0.6000056
    -- The CXX compiler identification is AppleClang 6.0.0.6000056
    -- Check for working C compiler: /usr/local/Library/ENV/4.3/clang
    -- Check for working C compiler: /usr/local/Library/ENV/4.3/clang -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++
    -- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Found GNU Make at /usr/local/Library/ENV/4.3/gmake
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/neovim-TYGZwA/.deps
    mkdir -p build
    touch build/.ran-third-party-cmake
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  -C .deps
    Scanning dependencies of target libunibilium
    [  1%] Creating directories for 'libunibilium'
    [  3%] Performing download step for 'libunibilium'
    -- file: /tmp/neovim-TYGZwA/.deps/build/downloads/libunibilium/520abbc8b26910e2580619f669b5cc2c4ef7f864.tar.gz
    -- downloading...
         src='https://github.com/mauke/unibilium/archive/520abbc8b26910e2580619f669b5cc2c4ef7f864.tar.gz'
         dst='/tmp/neovim-TYGZwA/.deps/build/downloads/libunibilium/520abbc8b26910e2580619f669b5cc2c4ef7f864.tar.gz'
         timeout='none'
    -- downloading... done
    -- extracting...
         src='/tmp/neovim-TYGZwA/.deps/build/downloads/libunibilium/520abbc8b26910e2580619f669b5cc2c4ef7f864.tar.gz'
         dst='/tmp/neovim-TYGZwA/.deps/build/src/libunibilium'
    -- extracting... [tar xfz]
    -- extracting... [analysis]
    -- extracting... [rename]
    -- extracting... [clean up]
    -- extracting... done
    [  5%] No patch step for 'libunibilium'
    [  6%] No update step for 'libunibilium'
    [  8%] No configure step for 'libunibilium'
    [ 10%] Performing build step for 'libunibilium'
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c unibilium.c  -fno-common -DPIC -o .libs/unibilium.o
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c unibilium.c -o unibilium.o >/dev/null 2>&1
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c uninames.c  -fno-common -DPIC -o .libs/uninames.o
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c uninames.c -o uninames.o >/dev/null 2>&1
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -DTERMINFO_DIRS=\"/etc/terminfo:/lib/terminfo:/usr/share/terminfo:/usr/lib/terminfo:/usr/local/share/terminfo:/usr/local/lib/terminfo\" -Wall -std=c99 -fPIC -c uniutil.c  -fno-common -DPIC -o .libs/uniutil.o
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -DTERMINFO_DIRS=\"/etc/terminfo:/lib/terminfo:/usr/share/terminfo:/usr/lib/terminfo:/usr/local/share/terminfo:/usr/local/lib/terminfo\" -Wall -std=c99 -fPIC -c uniutil.c -o uniutil.o >/dev/null 2>&1
    glibtool: link: clang -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libunibilium.0.dylib  .libs/unibilium.o .libs/uninames.o .libs/uniutil.o      -install_name  /tmp/neovim-TYGZwA/.deps/usr/lib/libunibilium.0.dylib -compatibility_version 3 -current_version 3.0 -Wl,-single_module
    glibtool: link: (cd ".libs" && rm -f "libunibilium.dylib" && ln -s "libunibilium.0.dylib" "libunibilium.dylib")
    glibtool: link: ar cru .libs/libunibilium.a  unibilium.o uninames.o uniutil.o
    glibtool: link: ranlib .libs/libunibilium.a
    glibtool: link: ( cd ".libs" && rm -f "libunibilium.la" && ln -s "../libunibilium.la" "libunibilium.la" )
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c tools/gen-static-test.c  -fno-common -DPIC -o tools/.libs/gen-static-test.o
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c tools/gen-static-test.c -o tools/gen-static-test.o >/dev/null 2>&1
    glibtool: link: /usr/local/Library/ENV/4.3/clang -o tools/.libs/gen-static-test tools/.libs/gen-static-test.o  ./.libs/libunibilium.dylib
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c tools/unibi-dump.c  -fno-common -DPIC -o tools/.libs/unibi-dump.o
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c tools/unibi-dump.c -o tools/unibi-dump.o >/dev/null 2>&1
    glibtool: link: /usr/local/Library/ENV/4.3/clang -o tools/.libs/unibi-dump tools/.libs/unibi-dump.o  ./.libs/libunibilium.dylib
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c tools/unibi-put.c  -fno-common -DPIC -o tools/.libs/unibi-put.o
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c tools/unibi-put.c -o tools/unibi-put.o >/dev/null 2>&1
    glibtool: link: /usr/local/Library/ENV/4.3/clang -o tools/.libs/unibi-put tools/.libs/unibi-put.o  ./.libs/libunibilium.dylib
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c t/00_load.c  -fno-common -DPIC -o t/.libs/00_load.o
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c t/00_load.c -o t/00_load.o >/dev/null 2>&1
    glibtool: link: /usr/local/Library/ENV/4.3/clang -o t/.libs/00_load.t t/.libs/00_load.o  ./.libs/libunibilium.dylib
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c t/static_screen.c  -fno-common -DPIC -o t/.libs/static_screen.o
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c t/static_screen.c -o t/static_screen.o >/dev/null 2>&1
    glibtool: link: /usr/local/Library/ENV/4.3/clang -o t/.libs/static_screen.t t/.libs/static_screen.o  ./.libs/libunibilium.dylib
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c t/static_tmux.c  -fno-common -DPIC -o t/.libs/static_tmux.o
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c t/static_tmux.c -o t/static_tmux.o >/dev/null 2>&1
    glibtool: link: /usr/local/Library/ENV/4.3/clang -o t/.libs/static_tmux.t t/.libs/static_tmux.o  ./.libs/libunibilium.dylib
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c t/static_xterm.c  -fno-common -DPIC -o t/.libs/static_xterm.o
    glibtool: compile:  /usr/local/Library/ENV/4.3/clang -I. -Wall -std=c99 -fPIC -c t/static_xterm.c -o t/static_xterm.o >/dev/null 2>&1
    glibtool: link: /usr/local/Library/ENV/4.3/clang -o t/.libs/static_xterm.t t/.libs/static_xterm.o  ./.libs/libunibilium.dylib
    [ 11%] Performing install step for 'libunibilium'
    glibtool: install: cp .libs/libunibilium.0.dylib /tmp/neovim-TYGZwA/.deps/usr/lib/libunibilium.0.dylib
    glibtool: install: (cd /tmp/neovim-TYGZwA/.deps/usr/lib && { ln -s -f libunibilium.0.dylib libunibilium.dylib || { rm -f libunibilium.dylib && ln -s libunibilium.0.dylib libunibilium.dylib; }; })
    glibtool: install: cp .libs/libunibilium.lai /tmp/neovim-TYGZwA/.deps/usr/lib/libunibilium.la
    glibtool: install: cp .libs/libunibilium.a /tmp/neovim-TYGZwA/.deps/usr/lib/libunibilium.a
    glibtool: install: chmod 644 /tmp/neovim-TYGZwA/.deps/usr/lib/libunibilium.a
    glibtool: install: ranlib /tmp/neovim-TYGZwA/.deps/usr/lib/libunibilium.a
    [ 13%] Completed 'libunibilium'
    [ 13%] Built target libunibilium
    Scanning dependencies of target libtermkey
    [ 15%] Creating directories for 'libtermkey'
    [ 16%] Performing download step for 'libtermkey'
    -- file: /tmp/neovim-TYGZwA/.deps/build/downloads/libtermkey/7b3bdafdf589d08478f2493273d4d75636ecc183.tar.gz
    -- downloading...
         src='https://github.com/neovim/libtermkey/archive/7b3bdafdf589d08478f2493273d4d75636ecc183.tar.gz'
         dst='/tmp/neovim-TYGZwA/.deps/build/downloads/libtermkey/7b3bdafdf589d08478f2493273d4d75636ecc183.tar.gz'
         timeout='none'
    -- downloading... done
    -- extracting...
         src='/tmp/neovim-TYGZwA/.deps/build/downloads/libtermkey/7b3bdafdf589d08478f2493273d4d75636ecc183.tar.gz'
         dst='/tmp/neovim-TYGZwA/.deps/build/src/libtermkey'
    -- extracting... [tar xfz]
    -- extracting... [analysis]
    -- extracting... [rename]
    -- extracting... [clean up]
    -- extracting... done
    [ 18%] No patch step for 'libtermkey'
    [ 20%] No update step for 'libtermkey'
    [ 21%] No configure step for 'libtermkey'
    [ 23%] No build step for 'libtermkey'
    [ 25%] Performing install step for 'libtermkey'
    /bin/sh: pkg-config: command not found
    /bin/sh: pkg-config: command not found
    /bin/sh: pkg-config: command not found
    /bin/sh: pkg-config: command not found
    ln -sf termkey_new.3.gz /tmp/neovim-TYGZwA/.deps/usr/share/man/man3/termkey_destroy.3.gz
    ln -sf termkey_new.3.gz /tmp/neovim-TYGZwA/.deps/usr/share/man/man3/termkey_new_abstract.3.gz
    ln -sf termkey_set_flags.3.gz /tmp/neovim-TYGZwA/.deps/usr/share/man/man3/termkey_get_flags.3.gz
    ln -sf termkey_set_canonflags.3.gz /tmp/neovim-TYGZwA/.deps/usr/share/man/man3/termkey_get_canonflags.3.gz
    ln -sf termkey_set_buffer_size.3.gz /tmp/neovim-TYGZwA/.deps/usr/share/man/man3/termkey_get_buffer_size.3.gz
    ln -sf termkey_set_waittime.3.gz /tmp/neovim-TYGZwA/.deps/usr/share/man/man3/termkey_get_waittime.3.gz
    ln -sf termkey_getkey.3.gz /tmp/neovim-TYGZwA/.deps/usr/share/man/man3/termkey_getkey_force.3.gz
    ln -sf termkey_start.3.gz /tmp/neovim-TYGZwA/.deps/usr/share/man/man3/termkey_stop.3.gz
    ln -sf termkey_start.3.gz /tmp/neovim-TYGZwA/.deps/usr/share/man/man3/termkey_is_started.3.gz
    [ 26%] Completed 'libtermkey'
    [ 26%] Built target libtermkey
    Scanning dependencies of target libtickit
    [ 28%] Creating directories for 'libtickit'
    [ 30%] Performing download step for 'libtickit'
    -- file: /tmp/neovim-TYGZwA/.deps/build/downloads/libtickit/33f4afb3891df05955429acbf5b406dfe87ec22b.tar.gz
    -- downloading...
         src='https://github.com/neovim/libtickit/archive/33f4afb3891df05955429acbf5b406dfe87ec22b.tar.gz'
         dst='/tmp/neovim-TYGZwA/.deps/build/downloads/libtickit/33f4afb3891df05955429acbf5b406dfe87ec22b.tar.gz'
         timeout='none'
    -- downloading... done
    -- extracting...
         src='/tmp/neovim-TYGZwA/.deps/build/downloads/libtickit/33f4afb3891df05955429acbf5b406dfe87ec22b.tar.gz'
         dst='/tmp/neovim-TYGZwA/.deps/build/src/libtickit'
    -- extracting... [tar xfz]
    -- extracting... [analysis]
    -- extracting... [rename]
    -- extracting... [clean up]
    -- extracting... done
    [ 31%] No patch step for 'libtickit'
    [ 33%] No update step for 'libtickit'
    [ 35%] No configure step for 'libtickit'
    [ 36%] No build step for 'libtickit'
    [ 38%] Performing install step for 'libtickit'
    /bin/sh: pkg-config: command not found
    /bin/sh: pkg-config: command not found
    /bin/sh: pkg-config: command not found
    /bin/sh: pkg-config: command not found
    In file included from src/mockterm.c:6:
    include/tickit-termdrv.h:15:10: fatal error: 'termkey.h' file not found
    #include <termkey.h>
             ^
    1 error generated.
    make[4]: *** [src/mockterm.lo] Error 1
    make[3]: *** [build/src/libtickit-stamp/libtickit-install] Error 2
    make[2]: *** [CMakeFiles/libtickit.dir/all] Error 2
    make[1]: *** [all] Error 2
    make: *** [deps] Error 2
    ==> Formula
    Tap: path or URL
    Path: /Library/Caches/Homebrew/Formula/neovim.rb
    ==> Configuration
    HOMEBREW_VERSION: 0.9.5
    ORIGIN: https://github.com/Homebrew/homebrew
    HEAD: cce4501dece6f7b2fbd16c9ed8782cc09250fb27
    Last commit: 87 minutes ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_CELLAR: /usr/local/Cellar
    CPU: 8-core 64-bit haswell
    OS X: 10.9.5-x86_64
    Xcode: 6.1.1
    CLT: 6.1.1.0.1.1416017670
    Clang: 6.0 build 600
    X11: 2.7.7 => /opt/X11
    System Ruby: 2.0.0-p481
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /Users/dlikhten/.rvm/rubies/ruby-2.0.0-p353/bin/ruby
    Java: 1.7.0_51
    ==> ENV
    HOMEBREW_CC: clang
    HOMEBREW_CXX: clang++
    CMAKE_PREFIX_PATH: /usr/local
    CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
    CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
    PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.9
    ACLOCAL_PATH: /usr/local/share/aclocal
    PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/opt/git/bin:/usr/bin:/bin:/usr/sbin:/sbin
    
    Error: neovim HEAD did not build
    Logs:
         /Users/dlikhten/Library/Logs/Homebrew/neovim/01.make
         /Users/dlikhten/Library/Logs/Homebrew/neovim/01.make.cc

**Comment by jszakmeister** [comment]
Install `pkg-config` with `brew install pkg-config`.  Then it should work.  I thought that was already in the formula, but perhaps not.  I'd check, but I'm not in front of a machine I can do that with at the moment.

**Comment by dlikhten** [comment]
Actually i tried `brew install libtermkey` and it worked afterwards.

**Comment by jeffpamer** [comment]
Yep, manually installing `libtermkey` solved it for me as well.

**Comment by jszakmeister** [comment]
@dlikhten @jeffpamer Manually installing libtermkey is not a good idea (at least not for use with Neovim).  We have a fork that we put patches into until the patches are applied upstream, so you may be running without some necessary bits.

Can you two run `head -n 15 /usr/local/Library/Taps/neovim/homebrew-neovim/Formula/neovim.rb` and paste the output?  I expect to see a `depends_on "pkg-config" => :build` line in there.  I'm pretty sure that pkg-config is not present, causing this in the output:

```text
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
```

And that's the root cause of why libtermkey can't build: it can't find the correct path because the .pc file was never generated.  Installing libtermkey helps, but only because it's failing to find our dependency and falling back to the one supplied by Homebrew.

**Comment by frewsxcv** [comment]
I am also unable to build. I haven't tried installing `libtermkey`.

```
[ 31%] No patch step for 'libtickit'
[ 33%] No update step for 'libtickit'
[ 35%] No configure step for 'libtickit'
[ 36%] No build step for 'libtickit'
[ 38%] Performing install step for 'libtickit'
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
In file included from src/mockterm.c:6:
include/tickit-termdrv.h:15:10: fatal error: 'termkey.h' file not found
#include <termkey.h>
         ^
1 error generated.
make[4]: *** [src/mockterm.lo] Error 1
make[3]: *** [build/src/libtickit-stamp/libtickit-install] Error 2
make[2]: *** [CMakeFiles/libtickit.dir/all] Error 2
make[1]: *** [all] Error 2
```

@jszakmeister In response to your request:

```ruby
~ $ head -n 15 /usr/local/Library/Taps/neovim/homebrew-neovim/Formula/neovim.rb
class Neovim < Formula
  homepage "http://neovim.org"
  head "https://github.com/neovim/neovim.git"

  depends_on "cmake" => :build
  depends_on "libtool" => :build
  depends_on "automake" => :build
  depends_on "autoconf" => :build
  depends_on "pkg-config" => :build
  depends_on "gettext" => :build
  depends_on :python => :recommended if MacOS.version <= :snow_leopard

  resource "libuv" do
    url "https://github.com/libuv/libuv/archive/v1.2.0.tar.gz"
    sha1 "38d1ba349fcfc1b221140523ba3d7cf3ea38c20b"
```

**Comment by jszakmeister** [comment]
@frewsxcv Can you run `brew list`?  Is `pkg-config` listed in there?

**Comment by frewsxcv** [comment]
```
~ $ brew list | grep pkg-config
pkg-config
~ $ which pkg-config
/usr/local/bin/pkg-config
```

**Comment by frewsxcv** [comment]
Like others in here, I just installed `libtermkey` from homebrew and it seemed to compile alright. Despite that, the `/bin/sh: pkg-config: command not found` messages still appeared throughout the compile process but didn't seem to affect the process.

**Comment by xu-cheng** [comment]
@jszakmeister many of similar problems reported in neovim are due to homebrew picked up the wrong formula. We used to put formula in the neovim main repo, and download it through url. This result of homebrew cached the outdated  formula. You can see this in log, that formula comes from path/url and the path is in the cache. Like this:
```
=> Formula
Tap: path or URL
Path: /Library/Caches/Homebrew/Formula/neovim.rb
 ```

To solve the problem, run
```
brew uninstall neovim --force
brew prune
brew tap neovim/homebrew-neovim
brew tap --repair
brew install neovim --HEAD
```

I will report this issue back to homebrew core.

**Comment by xu-cheng** [comment]
Also a small tip, use `brew cat neovim` to see the formula homebrew using.

**Comment by frewsxcv** [comment]
Thanks @xu-cheng , your steps worked for me

**Comment by jszakmeister** [comment]
@xu-cheng  I was looking for that!  Now I see it just after the failure.  I thought it was closer to the top of the output.  Thanks for the hints!

**Comment by jszakmeister** [comment]
@xu-cheng Two questions.

1) If the wrong formula is being used, can we see that with `brew info neovim`?
2) At what point does would our message in the main repo get shown?  Or would it not ever get shown because homebrew is using a cached neovim.rb?

I'm hoping to update the README for the homebrew-neovim repo because this seems to be a common problem (though it appears to have manifested itself a little differently each time).

Thanks!

**Comment by xu-cheng** [comment]
@jszakmeister 

1. Yeah, `brew info neovim` will show the origin:

         From: https://github.com/neovim/homebrew-neovim/blob/master/Formula/neovim.rb

2. The message will only be shown if users install neovim by 

         brew install https://raw.githubusercontent.com/neovim/neovim/master/neovim.rb

    If a user has a cached neovim.rb AND tap is broken or never being tapped. Invoking `brew install neovim` will go to the cached one.

**Comment by jszakmeister** [comment]
> Yeah, brew info neovim will show the origin:
> 
>  From: https://github.com/neovim/homebrew-neovim/blob/master/Formula/neovim.rb

Even if it's using a different formula?  If so, that kind of stinks.  Is there any other way to tell which formula is actually being used when a user has tapped the wrong one?

**Comment by xu-cheng** [comment]
> Even if it's using a different formula?

You misunderstood me. I mean it will show the real origin. The correct formula will show the url and the cached one will show like this:
     
       https://github.com//homebrew/blob/master/../../Library/Caches/Homebrew/Formula/neovim.rb

**Comment by jszakmeister** [comment]
> I mean it will show the real origin.

Very good!  Thanks!

**Comment by xu-cheng** [comment]
@jszakmeister The Homebrew's gist-logs have been updated. Now the formula's origin is in the gist. [An example](https://gist.github.com/xu-cheng/b514c9552daaf9f5bb2e#file-tap-out). I also send another PR to improve `brew info`'s output.

**Comment by jszakmeister** [comment]
@xu-cheng Fantastic!

**Comment by ElDeveloper** [comment]
This is still a problem, I haven't been able to get the formula to work, I've tried all the suggestions that are listed in this thread.

When installing from source, I get the following error:

```bash
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -C .deps
[ 13%] Built target unibilium
[ 26%] Built target libtermkey
[ 39%] Built target libuv
[ 52%] Built target libvterm
[ 65%] Built target luajit
[ 78%] Built target luarocks
[ 91%] Built target msgpack
[ 93%] Built target stable-busted-deps
[ 95%] Built target busted
[ 96%] Built target lua-messagepack
[ 98%] Built target lpeg
[100%] Built target nvim-client
[100%] Built target third-party
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -C build
Linking C executable ../../bin/nvim
Undefined symbols for architecture x86_64:
  "_cur_term", referenced from:
      _load_terminfo in libtermkey.a(driver-ti.o)
  "_setupterm", referenced from:
      _load_terminfo in libtermkey.a(driver-ti.o)
  "_strfnames", referenced from:
      _load_terminfo in libtermkey.a(driver-ti.o)
  "_strnames", referenced from:
      _load_terminfo in libtermkey.a(driver-ti.o)
  "_tigetstr", referenced from:
      _load_terminfo in libtermkey.a(driver-ti.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bin/nvim] Error 1
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [nvim] Error 2
```


When installing using brew:

```bash
yoshikivazquezbaeza:~$ sudo brew install neovim --HEAD --debug
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/neovim/homebrew-neovim/Formula/neovim.rb
==> Installing neovim from neovim/homebrew-neovim
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cmake.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libtool.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/xz.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/automake.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/autoconf.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/gettext.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/neovim/homebrew-neovim/Formula/neovim.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cmake.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libtool.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/xz.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/automake.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/autoconf.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/gettext.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/git.rb
==> Cloning https://github.com/neovim/neovim.git
Updating /Library/Caches/Homebrew/neovim--git
==> Checking out branch master
==> Downloading https://github.com/libuv/libuv/archive/v1.4.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--libuv-1.4.2.tar.gz
==> Downloading https://github.com/msgpack/msgpack-c/archive/cpp-1.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--msgpack-1.0.0.tar.gz
==> Downloading http://luajit.org/download/LuaJIT-2.0.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--luajit-2.0.3.tar.gz
==> Downloading https://github.com/mauke/unibilium/archive/v1.1.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--libunibilium-1.1.2.tar.gz
==> Downloading https://github.com/neovim/libtermkey/archive/8c0cb7108cc63218ea1
Already downloaded: /Library/Caches/Homebrew/neovim--libtermkey-19603.tar.gz
==> Downloading https://github.com/neovim/libvterm/archive/1b745d29d45623aa8d22a
Already downloaded: /Library/Caches/Homebrew/neovim--libvterm-7088.tar.gz
==> make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREF
make[4]: *** [bootstrap] Abort trap: 6
make[3]: *** [build/src/luarocks-stamp/luarocks-install] Error 2
make[2]: *** [CMakeFiles/luarocks.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/usr/local/Cellar/neovim/HEAD" install
```

Any help would be greatly appreciated!

**Comment by jszakmeister** [comment]
> ```text
> /Applications/Xcode.app/Contents/Developer/usr/bin/make  -C .deps
> [ 13%] Built target unibilium
> [ 26%] Built target libtermkey
> [ 39%] Built target libuv
> [ 52%] Built target libvterm
> [ 65%] Built target luajit
> [ 78%] Built target luarocks
> [ 91%] Built target msgpack
> [ 93%] Built target stable-busted-deps
> [ 95%] Built target busted
> [ 96%] Built target lua-messagepack
> [ 98%] Built target lpeg
> [100%] Built target nvim-client
> [100%] Built target third-party
> /Applications/Xcode.app/Contents/Developer/usr/bin/make  -C build
> Linking C executable ../../bin/nvim
> Undefined symbols for architecture x86_64:
>   "_cur_term", referenced from:
>       _load_terminfo in libtermkey.a(driver-ti.o)
>   "_setupterm", referenced from:
>       _load_terminfo in libtermkey.a(driver-ti.o)
>   "_strfnames", referenced from:
>       _load_terminfo in libtermkey.a(driver-ti.o)
>   "_strnames", referenced from:
>       _load_terminfo in libtermkey.a(driver-ti.o)
>   "_tigetstr", referenced from:
>       _load_terminfo in libtermkey.a(driver-ti.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[3]: *** [bin/nvim] Error 1
> make[2]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
> make[1]: *** [all] Error 2
> make: *** [nvim] Error 2
> ```

This looks like you have a library that was built as 32-bit.  From the functions referenced, it looks like it's probably ncurses.  If you run with `make VERBOSE=1` we can see the command line which will give a little more information about what's going on.  

> ```text
> yoshikivazquezbaeza:~$ sudo brew install neovim --HEAD --debug
> ```

Homebrew doesn't recommend running under `sudo`.  I'd encourage you to try the [troubleshooting tips in the readme](https://github.com/neovim/homebrew-neovim#troubleshooting) for the Neovim homebrew formula.

**Comment by ElDeveloper** [comment]
Thanks for the help, linking against a newly built ncurses (and
including the proper CPPFLAGS and LDFLAGS) seemed to do the trick!
Thanks a lot!

**Comment by dubspeed** [comment]
@xu-cheng your solution also worked for me, thanks a lot.

**Comment by justinmk** [comment]
@xu-cheng @jszakmeister  Does the neovim-homebrew repo still need a [README update](https://github.com/neovim/neovim/issues/1573#issuecomment-73851436) or can this be closed?
