### ISSUE TITLE
Switch to OpenResty LuaJIT2

### ISSUE THREAD

**Issue by clason** [neovim/neovim#15737]
### Feature already in Vim?

N/A

### Feature description

OpenResty's LuaJIT2 fork (which is now the only fork in town since moonjit became unmaintained) has a few advantages over the original LuaJIT:

1. Although not proper releases, they tag regularly, making more convenient points of reference for issues and for considering an upgrade.
2. It is already used instead of LuaJIT (for reason 1) by some distributions (Homebrew, ...)
3. It adds a few extensions that are useful for us: https://github.com/openresty/luajit2#new-lua-apis
In particular, `table.isempty`, `table.isarray`, and `table.nkeys` are native jittable versions of `vim.tbl_*` functions that could leverage these (if available); `table.clone` would be a useful addition.

Otherwise LuaJIT2 follows upstream LuaJIT very closely and quickly. (And CI shows that at least the currently latest tag is a drop-in replacement: #13741)

**Comment by goolord** [comment]
i am mildly skeptical, luajit forks seem to have a tendency to die. if this were to happen, say we migrate back to https://github.com/LuaJIT/LuaJIT, how do you mitigate breakage from features that didn't make it back upstream? some of the api functions they provide aren't formalized anywhere in luac

**Comment by clason** [comment]
We need to keep the pure Lua implementations anyway since we need to support PUC Lua; this would just be a (further) optimization for builds with LuaJIT(2).

**Comment by numToStr** [comment]
I am looking forward to this change. As a plugin author and user, faster `table.isempty` and `table.clone` are always welcome.

**Comment by clason** [comment]
After watching and considering the situation for a few months, I am no longer convinced about LuaJIT2 providing substantial enough benefit to merit switching tracks.
