### ISSUE TITLE
Code actions (for diagnostics) stopped working (eslint, typescript, ...)

### ISSUE THREAD

**Issue by entropitor** [neovim/neovim#15733]
### Neovim version (nvim -v)

v0.6.0-dev+nightly-977-g 340f77e78

### Vim (not Nvim) behaves the same?

/

### Operating system/version

macOS 

### Terminal name/version

kitty

### $TERM environment variable

screen-256color

### Installation

homebrow

### How to reproduce the issue

from a language server output a diagnostic and try to echo it back, the diagnostic doesn't fully match. E.g. the code field is dropped

### Expected behavior

The code field is send back when doing a code_action request

### Actual behavior

The code field is dropped

I think this broke because of https://github.com/neovim/neovim/pull/15585

**Comment by justinmk** [comment]
> v0.6.0-dev+nightly-977-g [340f77e](https://github.com/neovim/neovim/commit/340f77e78ef6589176822d53cf5507295bae771e)

there were fixes on master since then, try updating first.

**Comment by gpanders** [comment]
I think it's reasonable to preserve the 'code' field in the `vim_to_lsp` and `lsp_to_vim` transformation functions. We don't use it in `vim.diagnostic` anywhere but there's no harm in keeping it around for diagnostics that originate from LSP.

**Comment by gpanders** [comment]
@entropitor Please try #15735.

**Comment by entropitor** [comment]
@gpanders That works!
