### ISSUE TITLE
startup: "-l" enables Lua mode

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#15749]
`nvim -l` should enable "Lua mode" during startup, i.e.:

1. ✅ stdin can be executed as Lua?
2. ✅ args are copied to the Lua magic `_G.arg` global, for use in scripts
    - "negative args" contain all other `nvim` args?
3. ~~`-u {file}`is executed as the main Lua script _regardless of file extension_.~~

I see at least 2 ways of doing this:

* ~~`-l` strictly enables "Lua mode", and `-u foo.lua` specifies the file.~~
* ✅ `-l foo.lua` works, and also enables "Lua mode".
* ✅ All other `nvim` args can be used also (until `-l`). So you can mix vimscript `-c`/`+` with `-l`, load files into buffers, etc.

"Lua mode" could work like this (other suggestions welcome):
* ~~all args after `--` are sent to the Lua magic `arg` global.~~
* ✅  all args after `-l` are sent to the Lua magic `arg` global. 

Other:

- Tradtionally/conventionally, the [`lua` CLI](https://www.lua.org/pil/1.4.html) sets _negative_ args to CLI args _not_ sent to the "main" script. 
    - But this is awkward to work with in Lua. We already have `v:argv`, so scripts can inspect that if they care about the full arg list.
    - We will break `lua` CLI tradition here unless a use-case is presented.
- > one more thing: can the script control if the "normal" editor loop is started or not after its done? sometimes you want to run a one-shot script using nvim's builtin libraries and then exit, some other times the script would set up the editor to do something and then hand off to the main loop after the script is node.
    - ❌  Not planned. Workarounds:
        - Use `-c "luafile ..."`
        - Use `-S foo.lua -S bar.lua` to run multiple Lua scripts.

**Comment by ii14** [comment]
Is the purpose of this using neovim as lua interpreter? If so, can we also get this working for vim script?:

> * all args after `--` are sent to the Lua magic `args` global.
> * all args after `-l` are sent to the Lua magic `args` global.

Maybe those arguments should be placed in some new `v:` variable?

I wanted to write a nvr-like tool with just neovim as a dependency, and I don't think it's possible to do without a shell script that splits the arguments. This is what I ended up doing:

```sh
#!/bin/sh
for arg in "$@"; do args="$args'$(printf '%s' "$arg" | sed "s/'/''/g")',"; done
exec vim -u NONE --clean -c "let g:args = [$args] | source $VIMCONFIG/g/remote.vim"
```

**Comment by justinmk** [comment]
> Maybe those arguments should be placed in some new `v:` variable?

All args are already available in `v:argv`.

**Comment by ii14** [comment]
> All args are already available in `v:argv`.

Sure, but I'm talking about the arguments after `-l`/`--`. These won't be parsed as files, but just passed to lua? Do I understand it correctly? From there I guess you can parse `v:argv` yourself, so fair enough.

**Comment by groves** [comment]
This sounds like it'd be lovely for https://github.com/groves/invim. Currently I'm running `nvim -s -` and then using `:silent lua <<EOLUA` as my first and only command to feed Lua into nvim via stdin.

It sounds like this would allow me to feed the Lua directly to`nvim -l -` without the command wrapper. If so, definitely a useful feature for me! I had to dig around for a bit before I figured out how to wrap Lua with the existing options, and it distractingly echoes the `:silent lua` command regardless of what I do.

**Comment by mfussenegger** [comment]
> all args after -l are sent to the Lua magic args global.

I think this would be required to make something like `busted --lua=nvimlua` work, because it passes other options along

**Comment by justinmk** [comment]
> > All args are already available in `v:argv`.
> 
> Sure, but I'm talking about the arguments after `-l`/`--`. These won't be parsed as files, but just passed to lua?

The Lua `_G.arg` global will be set with all args afte `-l <script>`.

**Comment by justinmk** [comment]
> Is the purpose of this using neovim as lua interpreter? If so, can we also get this working for vim script?:

@ii14 `-es` and `-S foo` are intended for that already. What's missing? I can think of one thing: they can't accept "script args".

**Comment by ii14** [comment]
@justinmk Yeah, that was my point, passing arguments from the command line to the script. Now I'm fine with it being lua only though. You can always run vim script from lua anyway.
