### ISSUE TITLE
New argument for jobstart() to get JobActivity without newline

### ISSUE THREAD

**Issue by jalvesaq** [neovim/neovim#1574]
I am implementing an option in the [Vim-R-plugin] to run R as a Neovim job and display the R output in a Neovim buffer. So far, I was able to either emulate or substitute with Vim/Neovim commands the most useful features of R Console that depend on libreadline. However, I could not solve a much simpler problem, that does not depend on libreadline at all.

Because output that does not end in a newline character does not generate JobActivity, when R outputs a question not terminated in a new line the question is not displayed. For example, after the command `quit()`, R asks

```
Save workspace image? [y/n/c]:
```

and the user has to type `y`, `n` or `c` right after the colon. But with R running as a Neovim job the question does not trigger a JobActivity event because it does not end in a new line and, thus, it is not displayed in the Neovim buffer.

The solution that I could think of was the addition of an optional argument to `jobstart()` to generate the JobActivity even if the output does not ends in a newline. Is there a better solution?

[Vim-R-plugin]: https://github.com/jcfaria/Vim-R-plugin

**Comment by splinterofchaos** [comment]
`jobstart()` no longer waits for newlines. Please re-open if this is still an issue.

**Comment by jalvesaq** [comment]
Thanks for having worked on this! The new `termopen()` solved all issues that I was having.
