### ISSUE TITLE
Under special circumstances, neovim will be stuck 

### ISSUE THREAD

**Issue by Cpointerz** [neovim/neovim#15744]
### Neovim version (nvim -v)

0.5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ubuntu 21.04

### Terminal name/version

gnome terminal 

### $TERM environment variable

xterm-256color

### Installation

snap 

### How to reproduce the issue

ok

### Expected behavior

[https://imgur.com/a/AinifA8](url)

### Actual behavior

When I enable mouse support and coc-java at the same time, saving the file will cause neovim to freeze

**Comment by clason** [comment]
I'm sorry, that's not nearly enough to go on. Please explicit reproducing steps using a minimal (provided) config so somebody can reproduce that. It would also be good to try with https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#clang-sanitizers-asan-and-ubsan
