### ISSUE TITLE
Keymapped/langmapped ':' character appears in strange place while in Normal mode

### ISSUE THREAD

**Issue by VKondakoff** [neovim/neovim#15752]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+319-gc20899302

### Vim (not Nvim) behaves the same?

No, VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 19 2021 03:54:06)

### Operating system/version

macOS 12 beta

### Terminal name/version

Terminal 2.12 (442)

### $TERM environment variable

xterm-256color

### Installation

Homebrew

### How to reproduce the issue

Add `vim.api.nvim_set_keymap('n', 'Ж', ':', { noremap = true, silent = true })` to init.lua, source the file and press 'Ж'.

### Expected behavior

The ':' character should appear at the beginning of the command line:
<img width="565" alt="Снимок экрана 2021-09-21 в 20 27 22" src="https://user-images.githubusercontent.com/230824/134218640-568e5a94-8564-4865-a02f-f4359a371b2e.png">

### Actual behavior

The ':' character appears at the strange place and the previous command stays visible:
<img width="572" alt="Снимок экрана 2021-09-21 в 20 09 08" src="https://user-images.githubusercontent.com/230824/134218416-0053efe4-b977-4e43-a47c-28e4317b6c25.png">

**Comment by zeertzjq** [comment]
That `:` appearing at bottom right should be `'showcmd'`.

**Comment by zeertzjq** [comment]
@justinmk I think this is still a bug, because `:` should clear the command line.

**Comment by zeertzjq** [comment]
@VKondakoff After typing `'Ж'`, does typing more characters change the command line, or act like normal mode?

**Comment by VKondakoff** [comment]
The next character after 'Ж' (which is mapped to ':') clears the command line and the entire command shifts to the left of the screen.

**Comment by zeertzjq** [comment]
So the next character appears at the bottom left after a `:`?

**Comment by zeertzjq** [comment]
Oh, I know. It is `silent = true` causing the problem. Try removing `silent = true`. @VKondakoff

**Comment by VKondakoff** [comment]
Yes! This is it! Removing 'silent = true' solves the issue.
