### ISSUE TITLE
Win 32/x64 installation

### ISSUE THREAD

**Issue by TarunavBA** [neovim/neovim#15760]
### Feature already in Vim?

No 

### Feature description

@nono it would be nice if `neovim`. Installation is more easier.

**Comment by TarunavBA** [comment]
> ### Feature already in Vim?
> No
> 
> ### Feature description
> @nono it would be nice if `neovim`. Installation is more easier.

Probably a `msi` installer?

**Comment by justinmk** [comment]
@TarunavBA you've now made two low-effort requests. This wastes our time.

Duplicate of https://github.com/neovim/neovim/issues/6649

**Comment by itsmeboy0** [comment]
@TarunavBA as of #17390, this has been fulfilled.
