### ISSUE TITLE
inoremap expo expression inserts incorrectly

### ISSUE THREAD

**Issue by jasoneveleth** [neovim/neovim#15779]
### Neovim version (nvim -v)

0.6.0-dev+nightly-372-g9c7e04eb3

### Vim (not Nvim) behaves the same?

yes, 8.2.2029

### Operating system/version

macOS 11.6

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

It seems to be typing the '>' that was part of a control sequence.

nvim -u NONE

`inoremap <expr>k "k\<c-g>u\<c-\\>\<c-o>d? mk\<cr> $$\<left>"`
Then type:
`i mk`

### Expected behavior

 $|$

### Actual behavior

\> $|$

**Comment by seandewar** [comment]
Don't escape the `\` in `<c-\>`.
