### ISSUE TITLE
[LSP] restricting diagnostics signs is no longer possible since set signs was internalised

### ISSUE THREAD

**Issue by akinsho** [neovim/neovim#15770]
### Feature already in Vim?

N/A

### Feature description

Since the refactor of `vim.lsp.diagnostic` to `vim.diagnostic` in #15585 `vim.lsp.diagnostics.set_signs` has been internalised, which means that a user is no longer able to restrict the number of signs added by the lsp.

<img width="653" alt="Screen Shot 2021-09-23 at 15 06 05" src="https://user-images.githubusercontent.com/22454918/134522140-1897575f-7985-4f98-b6c3-bb5309deb9b3.png">

Just to clarify the functionality and the rationale behind it, currently lsp diagnostics adds a sign for *every* error of *every type* potentially also per client on a line which means that if your `signcolumn` is set to `auto:min-max` or `yes:count` you can easily end up have it jump up to 3+ columns or if you clamp it down to a fixed amount then it overrides other items in the signcolumn.

This feature was first requested/attempted to be added in https://github.com/neovim/neovim/pull/13763 but was rejected and TJ commented https://github.com/neovim/neovim/pull/13763#issuecomment-761970500 that a user could override `set_signs` to achieve this themselves. This lead to http://reddit.com/r/neovim/comments/mvhfw7/can_built_in_lsp_diagnostics_be_limited_to_show_a i.e. user solutions/workarounds for this feature (which is mentioned in lspconfig's wiki). This however depends on `set_signs` being exposed which is no longer the case.

Rather than relaunch the debate on this issue which (which was/?is surprisingly contentious) I'm wondering if something could be exposed to allow a user to control how the diagnostics are added i.e. the general idea being to just show the worst thing that is happening on X line i.e. there are 10 errors and 2 hints, just show me an error (or the most severe issue) marker so I know *something* is wrong rather than trying to consume a bunch of horizontal space to show the exact count of issues.

I wasn't sure how to class this i.e. feature request or regression, it is essentially a piece of functionality that is no longer available but I wonder if something like it could be restored.

**Comment by gpanders** [comment]
If you're using `auto:min-max` then presumably you'd *want* to see all of the signs, no? Why not set the max number of signs in the `'signcolumn'` option itself? If you're concerned about signs being hidden, you can use `severity_sort` to ensure that errors are always on top. Is there some other use case that isn't covered by these existing options?

**Comment by akinsho** [comment]
Understood at @gpanders, no worries re. the questions.

So I guess it's important to clarify my reasoning and perhaps that of other people that have shown an interest in this functionality.

I use `auto:min-max` primarily as a way of accommodating some max acceptable number of signs from various providers e.g. lsp, gitsigns, marks etc. for each provider that adds signs I only want an indication of an issue, ultimately it's not really possible (or desirable to me) for the lsp signs to try and fully communicate all of the issues with a line as signs since
1. There might never be enough columns e.g. I have 20+ issues, then I still don't know the count
2. Doing this eats up too much screen real estate anyway.
3. It prevents me seeing any other issues there e.g. what's the git state of the line, do I already have a mark there (the specifics don't matter just trying to show the reasoning).
4. *Most importantly*, I only want an *indication* of a problem, the severity and the line I need to go to e.g. I don't want the `signcolumn` to try and tell me exactly how many issues are on a line since it will never be able to give me useful granular information, i.e. the diagnostic message will tell me what went wrong, nor is the fact that it's 5 vs 2 errors useful to me, just that there are problems I need to look into on line X.

I already use `severity_sort` but the issue is primarily that showing X number of signs in the column isn't anymore useful (to me) than just one showing the most severe type and occupies too much space when working on small screens seeing `W W E E E E` isn't any more valuable to me than `E`. Hope that makes my reasoning/use case clearer. Clamping the number down though means you lose information since the lsp signs will overwrite other things.

**Comment by gpanders** [comment]
Thanks for the detailed response.

I think limiting signs to one per severity per line is a reasonable default.

**Comment by gpanders** [comment]
@akinsho I believe you can still do what the solution in that Reddit post suggests using the new diagnostic API:

```lua
local ns = vim.api.nvim_create_namespace("test")

function _G.my_set_signs()
    local diagnostics = vim.diagnostic.get(0)
    local max_severity_per_line = {}
    for _, d in pairs(diagnostics) do
        if max_severity_per_line[d.lnum] then
            local current_d = max_severity_per_line[d.lnum]
            if d.severity < current_d.severity then
                max_severity_per_line[d.lnum] = d
            end
        else
            max_severity_per_line[d.lnum] = d
        end
    end

    local filtered_diagnostics = {}
    for i, v in ipairs(max_severity_per_line) do
        table.insert(filtered_diagnostics, v)
    end

    vim.diagnostic.show(ns, 0, filtered_diagnostics, {virtual_text=false, underline=false, signs=true})
end

vim.cmd [[
augroup set_signs
autocmd! User DiagnosticsChanged call v:lua.my_set_signs()
augroup END
]]
```

I just cooked this up in a couple of minutes, but it should work. The only downside is that you have to use a global Lua function in order to access it from the autocmd, but that should be resolved one day when autocommands are supported in Lua.

**Comment by akinsho** [comment]
@gpanders I tried out your example locally and it doesn't clear signs on undoing or changing text, looking at the code in `diagnostic.lua` I managed to get it working by re-using the existing namespace which is what is used to clear diagnostics.

so something like
```lua
  -- had to duplicate this function diagnostic.lua to find the signgroup to re-use
  -- so it would be cleared when signs are reset
  local function get_namespace(ns)
  if not all_namespaces[ns] then
    local name
    for k, v in pairs(vim.api.nvim_get_namespaces()) do
      if ns == v then
        name = k
        break
      end
    end

    if not name then
      return vim.notify('namespace does not exist or is anonymous', vim.log.levels.ERROR)
    end

    all_namespaces[ns] = {
      name = name,
      sign_group = string.format('vim.diagnostic.%s', name),
      opts = {},
    }
  end
  return all_namespaces[ns]
end


  local function display_signs(namespace, bufnr, diagnostics, opts)
    local ns = get_namespace(namespace)
    local filtered = filter_diagnostics(diagnostics, bufnr) -- gets max diagnostics helper
    for _, diagnostic in ipairs(filtered) do
      local name = vim.diagnostic.severity[diagnostic.severity]
      local hl = 'DiagnosticSign' .. name:sub(1, 1) .. name:sub(2, -1):lower()
       -- needed `ns.sign_group` otherwise signs aren't removed
      fn.sign_place(0, ns.sign_group, hl, bufnr, {
        priority = opts and opts.priority,
        lnum = diagnostic.lnum + 1,
      })
    end
  end

  local show = vim.diagnostic.show
  function vim.diagnostic.show(namespace, bufnr, diagnostics, opts)
    show(namespace, bufnr, diagnostics, opts)
    display_signs(namespace, bufnr, diagnostics, opts)
  end
```

The problem mainly being having to copy paste an internal function `get_namespace` whose behaviour could change/depends on implementation details which could cause this function to stop working.

As I mentioned I'd rather avoid the debate since I know there will be many disagreements and strong feelings but is there not a more ergonomic way to resolve this e.g. a user can maybe pass in a diagnostic processing function so in my case I can filter the values or someone else could supress certain things they don't want programatically etc 🤷🏿‍♂️ .

Ultimately I'm sure I can get something like this to work but it seems like a high barrier to entry to get this working especially for anyone new to nvim or just lua.

**Comment by gpanders** [comment]
> Ultimately I'm sure I can get something like this to work but it seems like a high barrier to entry to get this working especially for anyone new to nvim or just lua.

Of course we don't want you or anyone else to have to jump through a thousand hoops to customize the behavior and we don't want to create a high barrier to entry. The API still has some rough edges and we need users like you to help us find those edges so we can smooth them out, and this is a case of that.

> @gpanders I tried out your example locally and it doesn't clear signs on undoing or changing text

Good catch, and I understand why. I'll address this soon.

**Comment by akinsho** [comment]
Thanks for picking this up and adding the changes/docs @gpanders tested it out on the nightly and it works great 👍🏿

**Comment by galou** [comment]
@akinsho Thanks! This works on my setup.
