### ISSUE TITLE
nvim_open_win(): behavior of south and east `anchor` is inconsistent across different `border` values when multigrid is not enabled

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#15789]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+341-g05d685be52

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

AUR neovim-git

### How to reproduce the issue

1. Run `nvim --clean -O2`.
2. Type some text in the two buffers. Put cursor at somewhere near the center of the left window.
3. Run one of the following commands:
    - `:call nvim_open_win(2, v:true, { 'relative': 'cursor', 'width': 8, 'height': 3, 'row': 0, 'col': 0, 'anchor': 'SE', 'border': 'none' })`
    - `:call nvim_open_win(2, v:true, { 'relative': 'cursor', 'width': 8, 'height': 3, 'row': 0, 'col': 0, 'anchor': 'SE', 'border': 'single' })`
    - `:call nvim_open_win(2, v:true, { 'relative': 'cursor', 'width': 8, 'height': 3, 'row': 0, 'col': 0, 'anchor': 'SE', 'border': ['', '', '', '|', '', '', '', ''] })`
    - `:call nvim_open_win(2, v:true, { 'relative': 'cursor', 'width': 8, 'height': 3, 'row': 0, 'col': 0, 'anchor': 'SE', 'border': ['', '', '', '', '', '', '', '|'] })`
    - `:call nvim_open_win(2, v:true, { 'relative': 'cursor', 'width': 8, 'height': 3, 'row': 0, 'col': 0, 'anchor': 'SE', 'border': ['', '', '', '|', '', '', '', '|'] })`
    - `:call nvim_open_win(2, v:true, { 'relative': 'cursor', 'width': 8, 'height': 3, 'row': 0, 'col': 0, 'anchor': 'SE', 'border': ['', '-', '', '', '', '', '', ''] })`
    - `:call nvim_open_win(2, v:true, { 'relative': 'cursor', 'width': 8, 'height': 3, 'row': 0, 'col': 0, 'anchor': 'SE', 'border': ['', '', '', '', '', '-', '', ''] })`

### Expected behavior

Behavior of `anchor` is consistent across different `border` values.

### Actual behavior

Behavior of south and east `anchor` is inconsistent across different `border` values (maybe always treated as having no border).
The cursor is on the `*` before running the command which is also where the corner of the floating window should be anchored to.

No Border:
![No Border](https://user-images.githubusercontent.com/35768171/134792190-01d333e2-e6df-4fde-bfea-9ef2299ffeab.png)

Full Border:
![Full Border](https://user-images.githubusercontent.com/35768171/134792192-d2a5b567-e253-4f16-aba5-be084283667f.png)

Only Right Border:
![Only Right Border](https://user-images.githubusercontent.com/35768171/134792203-3d387d3b-7fd9-49bf-b006-25443fc7c3b3.png)

Only Left Border:
![Only Left Border](https://user-images.githubusercontent.com/35768171/134792204-ebe530f8-c769-4e46-af8b-2cdc5237866c.png)

Left and Right Border:
![Left and Right Border](https://user-images.githubusercontent.com/35768171/134792207-a16d8bdd-e960-4abd-8630-3fd39586309c.png)

Only Top Border:
![Only Top Border](https://user-images.githubusercontent.com/35768171/134792211-7a462222-e601-4c11-885f-2c6c31a8131a.png)

Only Bottom Border:
![Only Bottom Border](https://user-images.githubusercontent.com/35768171/134792212-1d410570-252e-4c5f-ad40-7cda887c6bcb.png)

<details>
<summary>Northwest Anchor For Comparison</summary><br />

Full Border:
![Northwest Anchor Full Border](https://user-images.githubusercontent.com/35768171/134792757-ae1bc335-71ab-4de9-822b-30d026806c52.png)

No Border:
![Northwest Anchor No Border](https://user-images.githubusercontent.com/35768171/134795844-7b7b988c-a2a5-47dd-a2de-018e62f07898.png)

</details>

I'm not sure if the inconsistency should be fixed. If it is made consistent, some plugins may break and `vim.lsp.util.open_floating_preview()` may need changes, as they already depend on the inconsistent behavior.

If it should not be changed, I think the behavior of `anchor` should be better documented.

**Comment by justinmk** [comment]
> If it should not be changed, I think the behavior of `anchor` should be better documented.

can you suggest a 1-2 sentence change? Or maybe an example that hopefully does not involve 8 nvim_open_win() calls :)

**Comment by zeertzjq** [comment]
Inferring from:
<https://github.com/neovim/neovim/blob/bec7f47cee8b69fbaa3452762745c9d0e8ea4256/src/nvim/window.c#L856-L857>

```
`anchor` doesn't take `border` into consideration. 'south' actually subtracts `height` from `row`, and 'east' actually subtracts `width` from `col`.
```

**Comment by bfredl** [comment]
It would make more sense to fix the behavior, otherwise southern anchor is pretty much pointless with border.

**Comment by zeertzjq** [comment]
A plugin I can find that may need change if this is made consistent is [which-key.nvim](https://github.com/folke/which-key.nvim/blob/b582c9d78f0d105041ed29ec3a8ee11d98ddfd50/lua/which-key/view.lua#L30-L46).

**Comment by zeertzjq** [comment]
This may also be inconsistent with GUIs that implement multigrid.

**Comment by zeertzjq** [comment]
Also, is there an API to check if the UI supports multigrid?

**Comment by zeertzjq** [comment]
There are two option for the corrected behavior:
- N and W are still inclusive, and S and E are still exclusive, just take border in consideration
- N, W, S, E are all inclusive, i.e., always anchor to the exact corner of the window (including border)

**Comment by bfredl** [comment]
> BTW, is there an API to check if GUI supports multigrid?

`ui_has(kUiMultigrid)`

> N, W, S, E are all inclusive, i.e., always anchor to the exact corner of the window (including border). This line may also need change in this case (change 0 to -1): 

This sounds most consistent and easiest to reason about, especially with GUI:s whose border do not need to have width/height of 1/1 in cell units.

**Comment by zeertzjq** [comment]
I mean Lua or Vim script API. If there is one, it is possible to make which-key.nvim show window with border correctly in both TUI and Goneovim in an older version of Neovim (v0.5 or v0.5.1).

**Comment by bfredl** [comment]
that would be `nvim_list_uis()`

**Comment by zeertzjq** [comment]
> that would be `nvim_list_uis()`

Thanks!
