### ISSUE TITLE
Expr8 method call throw E884 or E107 if sentence starts with `call`

### ISSUE THREAD

**Issue by Groctel** [neovim/neovim#15783]
Quick edit: Formatted my own header levels for better reading.

### Neovim version (nvim -v)

NVIM v0.6.0-dev+313-g490e09c6d

### Vim (not Nvim) behaves the same?

vim 8.2.3441-1

### Operating system/version

Linux grocpc 5.14.7-arch1-1 #1 SMP PREEMPT Wed, 22 Sep 2021 21:35:11 +0000 x86_64 GNU/Linux

### Terminal name/version

kitty 0.23.1-1

### $TERM environment variable

xterm-256color

### Installation

aur/neovim-git 0.4.0.r2972.g3fbff98cf-1 (+226 2.07) (Installed: 0.5.0.r616.g490e09c6d-1)

#### E884

Create a file called `error.vim` (for example) and fill it:

```vim
fu! s:add_method (object, num) abort
	let a:object['num'] += a:num
endf

fu! Create_error () abort
	let l:object = { 'num' : 0 }
	call l:object->add_method(3) " Unexpected E884
endf
```

Open either `nvim -u NORC` or `nvim -u NONE` and proceed:

- `:source error.vim`
- `:call Create_error()`

#### E107

Create the same file but remove `l:` from the local variables:

```vim
fu! s:add_method (object, num) abort
	let a:object['num'] += a:num
endf

fu! Create_error () abort
	let object = { 'num' : 0 }
	call object->add_method(3) " Unexpected E107
endf
```

Open either `nvim -u NORC` or `nvim -u NONE` and proceed:

- `:source error.vim`
- `:call Create_error()`

### Expected behavior

According to the `:help method`: 

```vimhelp
expr8->name([args])	method call			*method* *->*
expr8->{lambda}([args])

For methods that are also available as global functions this is the same as: >
	name(expr8 [, args])
```

This means that `call l:object->add_method(3)` should be equivalent to its working counterpart `	call add_method(l:object, 3)` and call the method without ever throwing an `E884`. Calling `call object->add_method(3)` should also work the same as `call add_method(object, 3)` without throwing an `E107`.

### Actual behavior

And `E884` is thrown when the object is local (i.e. is prefixed by `l:` thus containing a semicolon) and an `E107` is thrown when the object has no scope prefix but isn't followed by parenthesis.

**Comment by seandewar** [comment]
Method calls can be used only in expressions, so `:call` can't be used.
If, for example, you'd like to use method call syntax but discard the result, use `:eval` instead:

```vim
let result = object->do_stuff(3)  " OK, assigns result to variable
eval object->do_stuff(3)          " OK, discards result
```
