### ISSUE TITLE
Creating $NVIM on Windows is breaking coloring

### ISSUE THREAD

**Issue by PawelBis** [neovim/neovim#15787]
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

I have no idea

### Operating system/version

Windows 10

### Terminal name/version

Allacrity, cmd, powershell

### $TERM environment variable

With $NVIM - "win32con", withouth $NVIM - "vtpcon"

### Installation

choco install neovim

### How to reproduce the issue

1. Set env variable NVIM to anything
2. Start nvim and notice lack of colors (even if you are not using any theme)

Without $NVIM:
![image](https://user-images.githubusercontent.com/24803993/134781333-e0761ab5-fbce-41aa-a3cb-a719206a8b4d.png)

With $NVIM:
![image](https://user-images.githubusercontent.com/24803993/134781357-7cf3c385-6710-4a71-9895-67ef8e34adc6.png)

### Expected behavior

Colors working even with $NVIM, cursor behaving correctly (beam in insert mode, block in normal mode)

### Actual behavior

Colors not working with NVIM, cursor is broken in alacrity - block both in insert mode and normal mode. Notice that cursor is working correctly in cmd and powershel, however colors are still broken.

**Comment by justinmk** [comment]
`$NVIM` is not a documented or supported feature. 

It forces winpty: https://github.com/neovim/neovim/blob/b854e3ee8c7234f0e144c5e850c3cea9c3e01388/src/nvim/os/tty.c#L26

, if you don't want that behavior... don't set the variable. It's going to be removed / repurposed: https://github.com/neovim/neovim/issues/3118
