### ISSUE TITLE
Cursor stops blinking in tmux 3.3-rc

### ISSUE THREAD

**Issue by laggardkernel** [neovim/neovim#15782]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+331-gaba397991

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

macOS 10.14.6

### Terminal name/version

iTerm2 3.4.10

### $TERM environment variable

xterm-256color outside tmux, tmux-256color within tmux

### Installation

Nightly release from GitHub realeases

### How to reproduce the issue

MInimal `tmux.conf`

```conf
set-option -s  escape-time        25
set-option -gs default-terminal   "tmux-256color"
```

Minimal neovim conf `test.vim`

```vim
set guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20,a:blinkwait0-blinkon400-blinkoff300
```

### Expected behavior

Requirements

- tmux 3.3-rc
- neovim 0.5.0 or nightly

Steps

- Outside tmux, `nvim -u test.vim`, the cursor blinks
- Start and enter tmux with `tmux -f ./tmux.conf -S ./tmux.socket`. Run `nvim -u test.vim` cursor doesn't blink

### Actual behavior

Neovim cursor should blink within tmux-3.3rc. I've reported this problem to tmux. According to the author's debugging

> vim is not asking xterm to turn the cursor off again, which means it must be sending cnorm inside tmux but not outside tmux. You should probably ask the vim developers why it is doing this?

Related issues in tmux https://github.com/tmux/tmux/issues/2891

**Comment by justinmk** [comment]
Thanks for the very clear repro steps. However, I tried them precisely and the cursor blinks for me ( macOS 11.6, Terminal.app, tmux 3.2a )

**Comment by laggardkernel** [comment]
@justinmk This problem doesn't appear in tmux 3.2a. You need to try 3.3-rc. I first reported this problem to tmux, but the author told me this a problem of vim side.

**Comment by justinmk** [comment]
> You should probably ask the vim developers why it is doing this?

uh because it wasn't needed until tmux 3.3 apparently

**Comment by laggardkernel** [comment]
Problem fixed on tmux's side. Sorry for having bothered you neovim developers.
