### ISSUE TITLE
Improve Ubuntu PPA.

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#1579]
Daily updated "unstable" PPA: https://code.launchpad.net/~neovim-ppa/+archive/ubuntu/unstable

Beta builds / snapshots might go into a "testing" PPA, releases into a "stable" PPA (like Debian's unstable/testing/stable repository names).
### (Possible) steps (not particularly in that order):
- [x] Package Neovim: https://code.launchpad.net/~neovim-ppa/+recipe/neovim-unstable
  - Currently uses static dependency linking.
- [ ] Create packages instead of static dependency linking:
  - [ ] Package libuv
  - [ ] Package msgpack
  - [ ] Package libvterm
  - [ ] Package libtermkey
  - [ ] Package unilibium
  - [x] Package lua-messagepack: https://code.launchpad.net/~neovim-ppa/+recipe/lua-messagepack
    - [x] Fix file location on Precise (https://github.com/neovim/neovim/issues/1579#issuecomment-66755947)
- [ ] Set up imports for dependency source code (like it was done for Neovim at https://code.launchpad.net/~neovim-ppa/neovim-ppa/neovim-master/)
  - [x] Create `bot-ci` build that publishes the dependencies' source code to `neovim/deps` in a separate directory (or branch?), import into Launchpad and use that instead of https://code.launchpad.net/~neovim-ppa/neovim-ppa/neovim-deps.
  - [ ] Import https://github.com/fperrad/lua-MessagePack/ into Launchpad instead of manually maintaining https://code.launchpad.net/~neovim-ppa/neovim-ppa/lua-messagepack.
- [x] ~~Ask for access to https://launchpad.net/neovim / https://launchpad.net/~neovim and use instead of semi-duplicate https://launchpad.net/neovim-ppa / https://launchpad.net/~neovim-ppa. Although it kind of begins to make sense to me to use `neovim-ppa`; after all, Neovim is on Github, only the PPA code is on Launchpad. But it might be confusing.~~
- [ ] Host package files ([for Neovim](https://code.launchpad.net/~neovim-ppa/neovim-ppa/neovim-packaging), [for lua-MessagePack](https://code.launchpad.net/~neovim-ppa/neovim-ppa/lua-messagepack-packaging), subsequently for other 3rd-party deps) on Github instead of Launchpad (to accept PRs for the packaging scripts). To import into Launchpad, they would need to be in separate repositories (not really an option) or in different branches on the same repo (slightly better).

**Comment by deivid-rodriguez** [comment]
> Beta builds / snapshots might go into a "testing" PPA, releases into a "stable" PPA (like Debian's unstable/testing/stable repository names).

:+1: Now that there's a public release available, it'd be nice to install it from a PPA as well.

Maybe it's worth adding this to the TODO list?

**Comment by justinmk** [comment]
@fwalch Now that neovim is in debian, can we assume ubuntu will inherit it? Or is there still work to be done here?

**Comment by fwalch** [comment]
> @fwalch Now that neovim is in debian, can we assume ubuntu will inherit it? Or is there still work to be done here?

I think we can assume that, but maybe @jamessan has more insight here?
The PPA will still be useful for unstable builds, but I guess it doesn't make too much sense to spend time packaging the 3rd-party dependencies..

**Comment by jamessan** [comment]
Since Yakkety just released, the next development cycle is just spinning up.  I'd imagine that neovim will get pulled into Zesty as they start syncing, but we'll have to wait and see.

I might have to do a little architecture cleanup on the Debian side to ensure the next neovim release is able to migrate into testing, since there was an initial migration before I enabled the tests (which caused various architectures to fail).

**Comment by ysolis** [comment]
You can find in Debian sid now, neovim package and in experimental branch, python2-neovim and python3-neovim, that will go to debian sid in a future.

The normal way of work with Ubuntu and the PPAs is provide packages that not come in the repos (main, universe, multiverse, restricted, etc) until the packages get released. At this point the PPA continue to provide packages for the stable/LTS Ubuntu versions, and more udpated versions that the version that come released officially.

My idea will be that continue with the way of work, providing and "stable" branch with the versions released (0.1.6 today) and another branch for daily releases.

**Comment by jamessan** [comment]
@fwalch Can we close this now that https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable exists?

**Comment by Deraen** [comment]
I don't know if it is in the scope of this issue, but it would be useful to have the python libs available in the PPA, like in Debian.

**Comment by delijati** [comment]
need stable for yakkety :)

**Comment by ysolis** [comment]
uhm ... happy for the backporting to an stable release, but, python-neovim, python3-neovim and neovim gem will get packaged in the repo too ?

**Comment by ysolis** [comment]
gg
