### ISSUE TITLE
Modifying packpath interferes with finding files on runtimepath

### ISSUE THREAD

**Issue by gpanders** [neovim/neovim#15807]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+356-gbec7f47ce

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 11.5

### Terminal name/version

kitty (tmux)

### $TERM environment variable

tmux-256color

### Installation

Source

### How to reproduce the issue

Consider a plugin that modifies packpath and runtimepath to limit the search scope for runtime files (for performance reasons). The plugin wants to find files in the user's runtime path that aren't searched for by Nvim itself (say, `*.fnl` files). The plugin has a script at `after/plugin/my_plugin.lua` with:

```lua
local rtp_save = vim.o.runtimepath
local pp_save = vim.o.packpath

vim.o.packpath = ""
vim.o.runtimepath = vim.fn.stdpath("config") .. "/after"

vim.api.nvim_get_runtime_file("plugin/**/*.fnl", true)

vim.o.packpath = pp_save
vim.o.runtimepath = rtp_save
```

You can recreate this locally by copying the above to `~/.local/share/nvim/site/pack/test/start/my_plugin/after/plugin/my_plugin.lua`.

Then use the following to reproduce:

```
mkdir -p ~/.config/nvim/after/plugin
echo 'assert(false)' > ~/.config/nvim/after/plugin/test.lua
nvim
```

This only happens when `packpath` and `runtimepath` are modified from a plugin (i.e. during the `pack/*/start/*` search).

### Expected behavior

With the above setup, you should expect to see an error at startup indicating that `after/plugin/test.lua` has been sourced.

More generally, if `runtimepath` and `packpath` are temporarily modified but then restored to their saved values, future runtimepath searches should continue to work normally.

### Actual behavior

There is no error message.

When the plugin restores `runtimepath` to its saved value, the cached path is invalidated and regenerated the next time a runtimepath search is performed. Somehow, also setting `packpath` to the empty string seems to affect the cached runtime path such that Lua files are no longer found under `after/plugin/`.

If the following lines are removed from the script above:

```lua
vim.o.packpath = ""

vim.o.packpath = pp_save
```

(that is, no modification of `packpath` is performed) then the issue does not occur. So there is some kind of non-obvious relationship between packpath and runtimepath.

Bisected to https://github.com/neovim/neovim/commit/ac3288d556965b0aaae03c59244278700eb598e8.

**Comment by gpanders** [comment]
This actually seems to be a bit trickier to reproduce than I thought. The issue is actually caused by the fact that [a package is sourcing files in the user after/plugin/](https://github.com/gpanders/nvim-moonwalk/blob/master/after/plugin/moonwalk.lua) directory. This seems to affect the cached runtime path so that other Lua plugin files under `after/plugin` then are not sourced.

I'll try and come up with a way to reproduce this.

**Comment by gpanders** [comment]
Updated the original issue comment and added a reproducible test case.

**Comment by bfredl** [comment]
We can handle this analogously to how vim did it for save_rtp: we take a reference to the specific version of the cached path and keep using that for the call in flight

**Comment by bfredl** [comment]
@gpanders note, if you wanna do something like`nvim_get_runtime_file` with a custom search path, you should just use `globpath(path, 1, 1)` instead of messing with global state.
