### ISSUE TITLE
JSON boolean/serialization - LSP Go to References

### ISSUE THREAD

**Issue by hjanuschka** [neovim/neovim#15809]
### Neovim version (nvim -v)

v0.6.0-dev+356-gbec7f47ce

### Vim (not Nvim) behaves the same?

no

### Operating system/version

debian 11

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

install go LSP / or any other - mark a word and do `gd`  or `:lua vim.lsp.buf.references()`

### Expected behavior

jump to defninition - in `v0.5.0`  it does - on master it doesnt

### Actual behavior

errors 

<img width="1485" alt="Bildschirmfoto 2021-09-27 um 08 26 10" src="https://user-images.githubusercontent.com/2891702/134855261-35397587-a5ab-4fbf-b938-a8501f3ad80f.png">

**Comment by hjanuschka** [comment]
bisecting, v0.5.0 to master revealed this "bad" commit.

```
c217766f7c32f17598563b16ef260322ce80bfc9 is the first bad commit
commit c217766f7c32f17598563b16ef260322ce80bfc9
Author: Michael Lingelbach <m.j.lbach@gmail.com>
Date:   Sun Sep 26 13:53:04 2021 -0700

    feat(lsp): use cjson for lsp rpc (#15759)

:040000 040000 43d38d4a480d2474f023489f6f3e55ef2ebe4fa3 3cb87a726a8100e2375aa2b8b0c4e3212a687c9a M      runtime
:040000 040000 fbcf9ddea3883bf409939c045e13d87cd848a2c2 a306bc8f503af3d13911958b4dc1c301d59121a9 M      test

````

**Comment by mjlbach** [comment]
See the linked PR. I switched the RPC client to the new lua-cjson backend which has caught what should have been a bug (we're trying to serialize a boolean key). Simple fix.

**Comment by hjanuschka** [comment]
@mjlbach awesome! thx, just checked out your branch, and verified it, works!!!
