### ISSUE TITLE
Could not turn Bell/Visualbell in the fresh Neovim nightly

### ISSUE THREAD

**Issue by VKondakoff** [neovim/neovim#15816]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+357-g96614f84a

### Vim (not Nvim) behaves the same?

no, VIM 8.2

### Operating system/version

macOS Monterey latest beta

### Terminal name/version

MacOS Terminal, Kitty

### $TERM environment variable

xterm-256color

### Installation

Homebrew

### How to reproduce the issue

Start `nvim -u NONE`
Type `:set visualbell`
Enter Insert mode and press left arrow several times - nothing happens there is no beep and no visualbell.

### Expected behavior

There should be beep and visualbell. At least they are in Vim 8.2.

### Actual behavior

-

**Comment by justinmk** [comment]
nvim has different defaults e.g. for 'belloff'. 

`:help nvim-defaults`

**Comment by VKondakoff** [comment]
Thanks for your answer, but I have tried to add this to init.lua:
```
vim.o.belloff = ''
vim.o.errorbells = true
vim.o.visualbell = true
```
And still no errorbell/visual bell. Any other glues?

**Comment by zeertzjq** [comment]
I suspect this is a bug in unibi_format()

**Comment by clason** [comment]
Now tracked in #20234

**Comment by zeertzjq** [comment]
Oh this is not a bug in `unibi_format()`
