### ISSUE TITLE
Broken link to documentation on Neovim front-page

### ISSUE THREAD

**Issue by VKondakoff** [neovim/neovim#15811]
### Neovim version (nvim -v)

-

### Vim (not Nvim) behaves the same?

-

### Operating system/version

-

### Terminal name/version

-

### $TERM environment variable

-

### Installation

-

### How to reproduce the issue

-

### Expected behavior

-

### Actual behavior

There is a broken link to Documentation on Neovim.io:
<img width="628" alt="Снимок экрана 2021-09-27 в 13 15 39" src="https://user-images.githubusercontent.com/230824/134892017-6eeba855-f298-4465-936b-5ef1513d29e0.png">

<img width="678" alt="Снимок экрана 2021-09-27 в 13 14 29" src="https://user-images.githubusercontent.com/230824/134892046-5868ca9d-657b-4956-8f0a-52bad210b9b1.png">

**Comment by seandewar** [comment]
Website issues should be reported to https://github.com/neovim/neovim.github.io

There's already a discussion at neovim/neovim.github.io#232, though there's talk of it being an issue with the doc generation at https://github.com/neovim/doc
