### ISSUE TITLE
Unclear Windows build instructions - fails to build with both MSVC and MSYS2

### ISSUE THREAD

**Issue by ahelwer** [neovim/neovim#15827]
### Neovim version (nvim -v)

9ca7b6b71a1e98ff6a76270d165fc8f07763a0c3

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 10 (Version 20H2, OS Build 19042.1237)

### Terminal name/version

x64 Native Tools Command Prompt for VS 2019

### $TERM environment variable

N/A

### Installation

Attempting to build from source

### How to reproduce the issue

1. Open "x64 Native Tools Command Prompt for VS 2019"
2. `git clone https://github.com/neovim/neovim.git neovim`
2. `cd neovim`
3. `make CMAKE_BUILD_TYPE=Release`

### Expected behavior

I expected neovim to build successfully, with a working executable file created at build/bin/nvim.exe.
The [Windows build instructions](https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msvc) alternatively say to "Open the Neovim project" but it isn't clear what that means and I can't find any *.vcproj or *.sln files in the repo except in .deps/build/src/msgback

### Actual behavior

Runs for quite a while, seemingly successfully, then ends with:
> Generating code
Finished generating code
[336/341] cmd.exe /C "cd /D C:\Users\ahelwer\source\to...helwer/source/tools/neovim/cmake/WindowsDllCopy.cmake"
Copying lua51.dll to C:/Users/ahelwer/source/tools/neovim/build/windows_runtime_deps
Copying msgpackc.dll to C:/Users/ahelwer/source/tools/neovim/build/windows_runtime_deps
Copying uv.dll to C:/Users/ahelwer/source/tools/neovim/build/windows_runtime_deps
Copying winpty.dll to C:/Users/ahelwer/source/tools/neovim/build/windows_runtime_deps
[339/341] Generating pack/dist/opt/matchit/doc/tags
FAILED: runtime/pack/dist/opt/matchit/doc/tags
cmd.exe /C "cd /D C:\Users\ahelwer\source\tools\neovim\build\runtime\pack\dist\opt\matchit && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E copy_directory C:/Users/ahelwer/source/tools/neovim/runtime/pack/dist/opt/matchit C:/Users/ahelwer/source/tools/neovim/build/runtime/pack/dist/opt/matchit && C:\Users\ahelwer\source\tools\neovim\build\bin\nvim -u NONE -i NONE -e --headless -c "helptags doc" -c quit"
[340/341] Generating pack/dist/opt/vimball/doc/tags
FAILED: runtime/pack/dist/opt/vimball/doc/tags
cmd.exe /C "cd /D C:\Users\ahelwer\source\tools\neovim\build\runtime\pack\dist\opt\vimball && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E copy_directory C:/Users/ahelwer/source/tools/neovim/runtime/pack/dist/opt/vimball C:/Users/ahelwer/source/tools/neovim/build/runtime/pack/dist/opt/vimball && C:\Users\ahelwer\source\tools\neovim\build\bin\nvim -u NONE -i NONE -e --headless -c "helptags doc" -c quit"
[341/341] Generating doc/tags
FAILED: runtime/doc/tags
cmd.exe /C "cd /D C:\Users\ahelwer\source\tools\neovim\build\runtime && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E remove doc/* && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E copy_directory C:/Users/ahelwer/source/tools/neovim/runtime/doc doc && C:\Users\ahelwer\source\tools\neovim\build\bin\nvim -u NONE -i NONE -e --headless -c "helptags ++t doc" -c quit"
ninja: build stopped: subcommand failed.
make: *** [Makefile:92: nvim] Error 1

Full output is attached in [this file](https://github.com/neovim/neovim/files/7245736/build-output.txt). Re-running the command results in the same error output. There is an nvim.exe file in build/bin but it crashes immediately on running with no output. I also tried building right off the v0.5.1 tag with the same result.

**Comment by clason** [comment]
Could it be a permissions issue?

**Comment by ahelwer** [comment]
@clason unfortunately not, I tried re-running the command as an administrator with the same result.

**Comment by ahelwer** [comment]
I've also tried to follow the msys2 compilation instructions [here](https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msys2--mingw), which failed in a number of ways; there are some missing dependencies in the instructions, such as:
- cmake
- ninja
- m4

but even with all those installed and running cmd.exe as an administrator, I fail when running `ninja` for the first time with:
>FAILED: build/src/tree-sitter-stamp/tree-sitter-download /c/Users/ahelwer/source/tools/neovim/.deps/build/src/tree-sitter-stamp/tree-sitter-download
cd /c/Users/ahelwer/source/tools/neovim/.deps/build/downloads/tree-sitter && /usr/bin/cmake.exe -DPREFIX=/c/Users/ahelwer/source/tools/neovim/.deps/build -DDOWNLOAD_DIR=/c/Users/ahelwer/source/tools/neovim/.deps/build/downloads/tree-sitter -DURL=https://github.com/tree-sitter/tree-sitter/archive/v0.20.0.tar.gz -DEXPECTED_SHA256=4a8070b9de17c3b8096181fe8530320ab3e8cca685d8bee6a3e8d164b5fb47da -DTARGET=tree-sitter -DUSE_EXISTING_SRC_DIR=OFF -P /c/Users/ahelwer/source/tools/neovim/third-party/cmake/DownloadAndExtractFile.cmake && /usr/bin/cmake.exe -E touch /c/Users/ahelwer/source/tools/neovim/.deps/build/src/tree-sitter-stamp/tree-sitter-download
-- file: /c/Users/ahelwer/source/tools/neovim/.deps/build/downloads/tree-sitter/v0.20.0.tar.gz
-- downloading...
       src='https://github.com/tree-sitter/tree-sitter/archive/v0.20.0.tar.gz'
       dst='/c/Users/ahelwer/source/tools/neovim/.deps/build/downloads/tree-sitter/v0.20.0.tar.gz'
       timeout='none'
-- downloading... done
-- extracting...
     src='/c/Users/ahelwer/source/tools/neovim/.deps/build/downloads/tree-sitter/v0.20.0.tar.gz'
     dst='/c/Users/ahelwer/source/tools/neovim/.deps/build/src/tree-sitter'
-- extracting... [tar xfz]
CMake Error: Problem with archive_write_header(): Can't create 'tree-sitter-0.20.0/CONTRIBUTING.md'
CMake Error: Current file: tree-sitter-0.20.0/CONTRIBUTING.md
CMake Error: Problem extracting tar: /c/Users/ahelwer/source/tools/neovim/.deps/build/downloads/tree-sitter/v0.20.0.tar.gz
-- extracting... [error clean up]
CMake Error at /c/Users/ahelwer/source/tools/neovim/third-party/cmake/DownloadAndExtractFile.cmake:164 (message):
  error: extract of
  '/c/Users/ahelwer/source/tools/neovim/.deps/build/downloads/tree-sitter/v0.20.0.tar.gz'
  failed

**Comment by clason** [comment]
Wait, that's now a different (and earlier!) error than you showed. I assume that you don't have a program installed that can extract `tar.gz` files?

And `cmake` and `ninja` _are_ listed explicitly as build dependencies: https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msys2--mingw

**Comment by ahelwer** [comment]
@clason do you have any debugging suggestions, other things to try, etc? I've tried running these commands:
- the `cd .deps; cmake -G Ninja ..\third-party\; ninja; ...` commands
- the `make CMAKE_BUILD_TYPE=Release` command

across the following shells:
- Regular cmd.exe
- x64 Native Tools Command Prompt for VS 2019
- MSYS2 MinGW 64-bit

and they fail in various ways, either the two already illustrated or another error:
```
The detected version of Ninja () is less than the version of Ninja required by CMake (1.3).
```
even though running `ninja --version` outputs 1.10.2.

Should I give up and just try to build neovim by running the github actions release pipeline in a fork?

**Comment by clason** [comment]
No, sorry, I have no experience with Windows. If you are _very_ sure you're following the build instructions exactly, you'll have to wait for someone familiar with building on Windows to pass by...

**Comment by ahelwer** [comment]
This is less urgent as I have worked around it by just building a release with github actions in a fork: https://github.com/tlaplus-community/neovim/releases/tag/v0.5.2
Still it would be very nice to be able to build locally on windows, for faster iteration times with more complicated changes!

**Comment by erw7** [comment]
I was surprised to read the Wiki entry [Building on Windows - Windows/MSVC](https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msvc). No one has probably attempted to build with this procedure for quite some time. Therefore, I would not be surprised if the build does not succeed in this step. The only procedure that has been continuously verified is by the CI build script ([build.ps1](https://github.com/neovim/neovim/blob/ec4731d982031e363a59efd4566fc72234bb43c8/ci/build.ps1)). Someone needs to verify and rewrite the wiki.

Regarding the [Windows/MSYS2/MinGW](https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msys2--mingw) procedure, if you run `ninja` again after the build fails, will it succeed? The reason why the extraction fails is that `CONTRIBUTING.md` is a symbolic link to `docs/section-6-contributing.md`, but `CONTRIBUTING.md` is extraction first, at which point `docs/section-6-contributing. md` does not exist (Windows will not allow you to create symbolic links to non-existent files). The second time you run `ninja`, the extraction should succeed because the `docs/section-6-contributing.md` that was extracted last time exists. I know that sometimes the tree sitter extraction fails, but I haven't pursued it deeply because it succeeds on the second run and doesn't happen with CI. I just tried it and it did not occur in my environment. I'm not sure what the difference is between an environment that fails and one that doesn't.

As for Windows, the number of contributors is far less than the number of users. Therefore, my motivation regarding Windows support is no longer there. If no one actively contributes, Windows support will only get worse in the future.

**Comment by ahelwer** [comment]
Alas this is my curse! I'm on windows for the video games, and last time I tried to set up dual-boot with Linux I trashed my boot setup and had to reinstall everything from scratch. One day I'll buy a workstation from system76 and join the rest of the open source world. Just finished fixing windows build issues with the tree-sitter repo, actually. I guess I should actually get around to learning how make and ninja work so I can debug these issues.

**Comment by KillTheMule** [comment]
Maybe try to run ci\build.ps1

**Comment by matveyt** [comment]
I don't use (or have) MS build tools, but I can confirm that at least Win/MSYS build instructions work (and always worked) without any problems.
If cmake says that ninja has wrong version then it must be because you've got also an outdated executable somewhere on your machine.

**Comment by erw7** [comment]
I've added a note to the Wiki.

https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msvc

The steps that @ahelwer took in https://github.com/neovim/neovim/issues/15827#issue-1009931186 are not explained anywhere, so it's no surprise that you can't build it. As for building with Windows/MSYS2/MinGW, it succeeds in my hand, and there are other https://github.com/neovim/neovim/issues/15827#issuecomment-930191463 that there is no problem. Therefore, it is highly likely that there is something wrong with procedure of @ahelwer. For the above reasons, this is closed.

If you want to continue this conversation any further, please do so somewhere below.

- http://discourse.neovim.io/
- https://vi.stackexchange.com
- https://neovim.io/#chat

**Comment by ahelwer** [comment]
Build.ps1 doesn't work because it uses tools from the GitHub actions build cache directory. I'll poke around the MSYS2 directions a bit more to see where things go. Don't know what you mean by the commands I used not being present anywhere, they're at the bottom of the wiki page under Windows build dependencies.
