### ISSUE TITLE
LSP: vim.lsp.commands: support per-client commands / codeactions

### ISSUE THREAD

**Issue by nghialm269** [neovim/neovim#15822]
### Feature already in Vim?

N/A

### Feature description

I'm using `vim.lsp.commands` to intercept the `refactor.perform` command of `dartls`, this way I can prompt the user for input (and modify the command) before sending the command to the server. [Here](https://github.com/nghialm269/flutter-tools.nvim/commit/82acf30efae982463e57397337b033081fb0ec42) is my implementation.

The problem is that this is a server-side command, so its name is not prefixed with the language server name, and since `vim.lsp.commands` is shared between all clients, I'm worrying about name collisions.

So, I'd like a way to define commands for specific client so that I don't have to worry about collisions.

**Comment by justinmk** [comment]
vim.lsp.commands["refactor.perform"] = function(command, ctx)

Does the `command` or `ctx` param have something you can check?

Not really sure what you expect. I do not think making a big nested map in `vim.lsp.commands` is a good idea. A "registry" also is overwrought.

**Comment by nghialm269** [comment]
> Does the command or ctx param have something you can check?

@justinmk: #15818 added `client_id` to the `ctx`, and I think I can use it to check.

But, the problem I'm facing is that the command I'm overriding doesn't prefixed with the language server name, so there might be collision, what if other plugin also decides to override `refactor.perform` as I do?

> Not really sure what you expect. I do not think making a big nested map in vim.lsp.commands is a good idea. A "registry" also is overwrought.

Yes, I don't think doing that is a good idea, either.  What I'm thinking is that can we add the `commands` directly to the `client`, instead of a global `vim.lsp.commands` like we're doing?

To achieve what I'm trying to do, I guess I can override `vim.lsp.buf.execute_command` directly as suggested in https://github.com/neovim/nvim-lspconfig/issues/858#issuecomment-825030807, but is there any problems if multiple plugins override it? And since we can already define custom commands, I think it's better to use that instead of overriding `vim.lsp.buf.execute_command`.

**Comment by justinmk** [comment]
> What I'm thinking is that can we add the `commands` directly to the `client`, instead of a global `vim.lsp.commands`

Makes sense at first glance. Also for `handlers` ?  @neovim/lsp

**Comment by fsouza** [comment]
Clients can already have their own handlers. So yeah, I think that clients having their own commands makes sense too.
