### ISSUE TITLE
Treesitter: `#match?` predicate and multiline nodes

### ISSUE THREAD

**Issue by stsewd** [neovim/neovim#15833]
### Feature description

Just realized that the match predicate always returns false for multiline nodes

https://github.com/neovim/neovim/blob/ec4731d982031e363a59efd4566fc72234bb43c8/runtime/lua/vim/treesitter/query.lua#L243-L245

I don't know if there was some discussion about how to support those, but maybe we could at least just try matching the first line? (from start_col till the end of the first line).

Also, looks like vim does support multiline strings in a pattern (`:h string-match`), so maybe we could just extract the text from the node and pass it to vim's match().

**Comment by vhyrro** [comment]
Woops, made a mistake. I looked in the wrong place when writing my previous comment, I've deleted that one :)

Regarding the matching, i say we could concatenate the node text by using `\n` chars to create one big string, e.g.:
```
[[
    multiline string
]]
```
would produce: `[[\n    multiline string\n]]`, then we could perform the regex match on that? It would then allow `#match?` regexes like `\\[\\[\n` for example.

Seems the most logical, let me know what y'all think.
