### ISSUE TITLE
Lua interface for getting marks. 

### ISSUE THREAD

**Issue by adgai19** [neovim/neovim#15830]
### Feature description

Right now, there is no clean way to access marks from inside lua. I looked at telescope.nvim implementation and it parses the output of  `marks` to get the marks. I think that it would be nice to get them from inside lua

**Comment by adgai19** [comment]
I would be happy to send a PR for this

**Comment by muniter** [comment]
This is on the works https://github.com/neovim/neovim/pull/15346 address mark retrieval and manipulation.

**Comment by adgai19** [comment]
Cool.

**Comment by justinmk** [comment]
There is also `vim.fn.getmarklist()`. Any vimscript function can be used from Lua, see `:help vim.fn`
