### ISSUE TITLE
Allow having a global statusline at the bottom

### ISSUE THREAD

**Issue by famiu** [neovim/neovim#15834]
### Feature already in Vim?

No

### Feature description

Most modern editors only have one statusline plugin at the bottom instead of a statusline for each window. It would be nice to have an option that allows having only one statusline for the current window at the bottom, instead of having a statusline under each window. It'd allow better utilization of screen space for those who don't need a statusline for inactive windows, plus it also looks more beautiful (in my opinion). So it's definitely a feature I'd love to see implemented in Neovim.

[floatline.nvim](https://github.com/windwp/floatline.nvim) already implements this through floating windows, but I'm not a big fan of how that's done personally, and would like a native Neovim way of doing this.

Also, unrelated but, a huge thank you to all the Neovim contributors for making this awesome text editor. Really grateful to all of you. Hope you all keep up the amazing work.

**Comment by clason** [comment]
duplicate: #9342

**Comment by chrisbra** [comment]
FWIW, you can abuse the tabline for that. Of course it will be at the top then.
