### ISSUE TITLE
Cannot load plugins from start packages in packpath

### ISSUE THREAD

**Issue by notomo** [neovim/neovim#15837]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+364-gec4731d98

### Vim (not Nvim) behaves the same?

N/A (needs `nvim_get_runtime_file` or `nvim_list_runtime_paths` to deal start package)

### Operating system/version

Ubuntu 20.04

### Terminal name/version

wsltty

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```
build/bin/nvim -u NORC +'luafile minimal.lua'
```

minimal.lua
```lua
-- create plugin files for test
local packpath = "./mypackpath"
vim.fn.mkdir(packpath, "p")
local lua_dir = packpath .. "/pack/mypackage/start/myplugin/autoload/"
vim.fn.mkdir(lua_dir, "p")
io.open(lua_dir .. "myplugin.vim", "w"):close()

vim.cmd("set packpath^=" .. packpath)
vim.cmd("packloadall")

print(vim.api.nvim_get_runtime_file("autoload/myplugin.vim", false)[1]) -- nil
print(table.concat(vim.api.nvim_list_runtime_paths(), ";"):find("start/myplugin") ~= nil) -- false
```

### Expected behavior

found file and runtimepath.

```
$ build/bin/nvim -u NORC --headless +'luafile minimal.lua'
./mypackpath/pack/mypackage/start/myplugin/autoload/myplugin.vim
true
```

### Actual behavior

```
$ build/bin/nvim -u NORC --headless +'luafile minimal.lua'
nil
false
```

from ac3288d

**Comment by matveyt** [comment]
This works as expected.

`-u NORC` allows for plugins to load. `+` will be executed afterwards. Hence `:packloadall` will do nothing as clearly documented under `:h :packloadall`.

**Comment by notomo** [comment]
Thanks, but `packloadall!` doesn't change anything.
`myplugin` is not loaded automatically because it isn't in the default packpath.

In addition, nvim before ac3288d works as expected behavior.

**Comment by bfredl** [comment]
Hmm even with fixing this embarrassing error it doesn't work

```diff
diff --git a/src/nvim/runtime.c b/src/nvim/runtime.c
index d87f8f980..4422b8c4a 100644
--- a/src/nvim/runtime.c
+++ b/src/nvim/runtime.c
@@ -420,7 +420,7 @@ RuntimeSearchPath runtime_search_path_build(void)
   }
 
   for (size_t i = 0; i < kv_size(pack_entries); i++) {
-    handle_T h = map_get(String, handle_T)(&pack_used, cstr_as_string((char *)buf));
+    handle_T h = map_get(String, handle_T)(&pack_used, kv_A(pack_entries, i));
     if (h == 0) {
       expand_pack_entry(&search_path, &after_path, (char_u *)kv_A(pack_entries, i).data);
     }

```

I'll investigate more tomorrow.
