### ISSUE TITLE
API function to expand statusline string

### ISSUE THREAD

**Issue by famiu** [neovim/neovim#15849]
### Feature already in Vim?

No

### Feature description

Currently, I'm working on automatic component truncation for my statusline plugin ([`feline.nvim`](https://github.com/famiu/feline.nvim)). But in order to do that I need a way to accurately determine which characters of the statusline strings are going to actually be displayed on the statusline, so I can find the length of the statusline to see if it fits within the window. I'd like if there was an equivalent of `expand()` for Vim statusline strings. One that'd parse the statusline string and return just a normal string containing only the characters that'd be displayed, with all statusline modifiers and such removed. My plugin could then use it to get the length of the statusline and do things like removing statusline components.

Alternatively, there could also be also be a function to check if statusline is being truncated by Neovim, in which case the plugin could detect that and start truncating components when needed.

I know this is probably not going to be very high on the priority list, but I decided to make this Issue anyway. I don't think it'd be that hard to implement since Neovim already parses the statusline while displaying it. I could try to make it myself but sadly I'm not familiar with Neovim's codebase.

**Comment by justinmk** [comment]
there is an open PR that exposes `build_stl_str_hl` for some indirect purpose, if anyone knows which PR please link it here.
