### ISSUE TITLE
LSP: code actions handler is not called after update

### ISSUE THREAD

**Issue by gfanto** [neovim/neovim#15848]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+366-g270cc1d70

### Vim (not Nvim) behaves the same?

-

### Operating system/version

ubuntu 20.04

### Terminal name/version

-

### $TERM environment variable

-

### Installation

build from repo

### How to reproduce the issue

nvim -u NONE

:lua vim.lsp.handlers["textDocument/codeAction"] = function() print("hello hello") end
:lua vim.lsp.buf.code_action()

### Expected behavior

Call my custom handler function and print "hello hello".

I used to have a custom handler for code actions, but after one of the last updates the handler is never called.
I don't understand if i'm missing something obvious or something ha changed.

### Actual behavior

Call the standard terminal prompt handler

**Comment by mjlbach** [comment]
You can't override code actions anymore via the handlers table, you'll need to write your own custom function to call the code action request, see #15818 for discussion as to why this is, and the inline comment.

**Comment by hood** [comment]
@mjlbach I'm pretty sure plugin maintainers need a clear documentation on how to adapt to this change. This breaks quite a few plugins actually. 

See:
https://github.com/gbrlsnchs/telescope-lsp-handlers.nvim/issues/5
https://github.com/RishabhRD/nvim-lsputils/issues/44

**Comment by mjlbach** [comment]
Option 1: override vim.ui.select

Option 2: override the buffer function, essentially just copy/paste (with modifications) the following block into your plugin, and override vim.lsp.buf

```
local function on_code_action_results(results, ctx)
  local action_tuples = {}
  for client_id, result in pairs(results) do
    for _, action in pairs(result.result or {}) do
      table.insert(action_tuples, { client_id, action })
    end
  end
  if #action_tuples == 0 then
    vim.notify('No code actions available', vim.log.levels.INFO)
    return
  end

  ---@private
  local function apply_action(action, client)
    if action.edit then
      util.apply_workspace_edit(action.edit)
    end
    if action.command then
      local command = type(action.command) == 'table' and action.command or action
      local fn = vim.lsp.commands[command.command]
      if fn then
        local enriched_ctx = vim.deepcopy(ctx)
        enriched_ctx.client_id = client.id
        fn(command, ctx)
      else
        M.execute_command(command)
      end
    end
  end

  ---@private
  local function on_user_choice(action_tuple)
    if not action_tuple then
      return
    end
    -- textDocument/codeAction can return either Command[] or CodeAction[]
    --
    -- CodeAction
    --  ...
    --  edit?: WorkspaceEdit    -- <- must be applied before command
    --  command?: Command
    --
    -- Command:
    --  title: string
    --  command: string
    --  arguments?: any[]
    --
    local client = vim.lsp.get_client_by_id(action_tuple[1])
    local action = action_tuple[2]
    if not action.edit
        and client
        and type(client.resolved_capabilities.code_action) == 'table'
        and client.resolved_capabilities.code_action.resolveProvider then

      client.request('codeAction/resolve', action, function(err, resolved_action)
        if err then
          vim.notify(err.code .. ': ' .. err.message, vim.log.levels.ERROR)
          return
        end
        apply_action(resolved_action, client)
      end)
    else
      apply_action(action, client)
    end
  end

  vim.ui.select(action_tuples, {
    prompt = 'Code actions:',
    format_item = function(action_tuple)
      local title = action_tuple[2].title:gsub('\r\n', '\\r\\n')
      return title:gsub('\n', '\\n')
    end,
  }, on_user_choice)
end


--- Requests code actions from all clients and calls the handler exactly once
--- with all aggregated results
---@private
local function code_action_request(params)
  local bufnr = vim.api.nvim_get_current_buf()
  local method = 'textDocument/codeAction'
  vim.lsp.buf_request_all(bufnr, method, params, function(results)
    on_code_action_results(results, { bufnr = bufnr, method = method, params = params })
  end)
end

--- Selects a code action available at the current
--- cursor position.
---
---@param context table|nil `CodeActionContext` of the LSP specification:
---               - diagnostics: (table|nil)
---                             LSP `Diagnostic[]`. Inferred from the current
---                             position if not provided.
---               - only: (string|nil)
---                      LSP `CodeActionKind` used to filter the code actions.
---                      Most language servers support values like `refactor`
---                      or `quickfix`.
---@see https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction
function M.code_action(context)
  validate { context = { context, 't', true } }
  context = context or {}
  if not context.diagnostics then
    context.diagnostics = vim.lsp.diagnostic.get_line_diagnostics()
  end
  local params = util.make_range_params()
  params.context = context
  code_action_request(params)
end
```

vim.ui.select probably will suit the needs of plugin maintainers more.

**Comment by rmagatti** [comment]
@mjlbach @mfussenegger  something I'm not quite getting with overriding `vim.ui.select` is how could one have different UIs for different LSP handlers exactly?

In the code for https://github.com/gbrlsnchs/telescope-lsp-handlers.nvim for example, one could override a particular handler in a particular way, for code actions for example I'd configure it to use the telescope cursor theme. But for other handlers like "references" I'd use the regular theme where previews were available for example. 

With having to override a single point, i.e `vim.ui.select` I don't quite see how I'd pull this off? Maybe by doing the LSP call manually myself but if that's the case it seems to me like something was easier to do before than it is now with the new changes and maybe there's a way to make things more granular going forward?

Disclaimer: I don't really know enough about how all of this works to be certain I'm making valid observations here, please enlighten me if perhaps I'm just blatantly missing something.
