### ISSUE TITLE
Documentation on `:ha` doesn't state that `pdev` needs to be set to the printer URI

### ISSUE THREAD

**Issue by BlueManedHawk** [neovim/neovim#15843]
### Neovim version (nvim -v)

v0.4.4.

### Vim (not Nvim) behaves the same?

Yes.

### Operating system/version

GalliumOS 3.1.

### Terminal name/version

Kitty, v0.19.3.

### $TERM environment variable

`xterm-kitty`

### Installation

I think I just got it from APT?

### How to reproduce the issue

View `print.txt` in the Reference Manual.

### Expected behavior

The documentation would mention that `pdev` needs to be set to the URI of the printer one wishes to print to.

### Actual behavior

It does not.

**Comment by gpanders** [comment]
Thanks for the issue report; however, Neovim does not maintain `:hardcopy` nor its documentation. We simply port changes from upstream. Try opening an issue with [Vim](https://github.com/vim/vim) and if it's accepted we will merge the patch.

**Comment by BlueManedHawk** [comment]
Ah, alright then.  Thanks for redirecting me.
