### ISSUE TITLE
Support vim.lsp.start_client parameter to avoid uv.spawn(...)

### ISSUE THREAD

**Issue by chipsenkbeil** [neovim/neovim#15847]
### Feature description

Today, when you call `vim.lsp.start_client({...})`, an external process is eventually spawned using `vim.loop.spawn(...)` (aka `uv.spawn`). For libraries that provide alternate means of communicating with LSP processes that need direct control over the spawning, it is currently required to temporarily overwrite the spawn method:

```lua
-- Must overwrite with this before calling vim.lsp.start_client
vim.loop.spawn = function(cmd, spawn_params, on_exit)
    local pid = 123
    local handle = {
        -- ...
    }
    return handle, pid
end
```

In the case of [distant.nvim](https://github.com/chipsenkbeil/distant.nvim), the upcoming release is going to switch to using a shared object Rust library where we talk to remote processes. Today, this involves spawning a proxy process per LSP. Tomorrow, this should just have the library inject itself in the creation process and return a handler that provides all of the same methods.

* `handle:is_closing()`
* `handle:close([callback])`
* `handle:kill(signum)`
* Working with `uv.new_pipe(false)` created for stdin, stdout, and stderr all of which are supplied as arguments to `uv.spawn`
    * `stdout:read_start(...)`
    * `stderr:read_start(...)`
    * `stdin:write(...)`

Talking with @tjdevries about this briefly on discord, the scalable idea here would be to allow passing a function that can be called, defaulting to `uv.spawn` if none is provided. Depending on the complexity of working with uv pipes, we may need to abstract a little bit more to allow a function that returns a handle AND stdin, stdout, and stderr which all mirror the uv pipe methods. This is because we may not be able to work with the uv pipes directly if they don't actually connect to anything local.

This is something I hope to tackle before the next neovim release.

**Comment by mfussenegger** [comment]
I think if we do this, we should also account for the Ip/TCP case and have an abstraction that works for both.  

Similar to how nvim-dap does it:

https://github.com/mfussenegger/nvim-dap/blob/409fd0cfbaa39e52e02c06eeae5456cadb0b6748/lua/dap/session.lua#L631
https://github.com/mfussenegger/nvim-dap/blob/409fd0cfbaa39e52e02c06eeae5456cadb0b6748/lua/dap/session.lua#L684

**Comment by chipsenkbeil** [comment]
I've now successfully written a hack that overwrites `uv.spawn` and `uv.new_pipe` so I can provide my own implementation. See [distant.lsp.start_client](https://github.com/chipsenkbeil/distant.nvim/blob/4436ce18fd13cdea171fbdcbdaa498371f51dc43/lua/distant/lsp.lua#L18).

For `uv.spawn`, I return a table that implements:
* is_closing
* close
* kill

For `uv.new_pipe`, I return a table that implements:
* close
* read_start
* write

I have to do some extra trickery for the pipes as I need to update them when they are passed to `uv.spawn` in order for them to be functional.

Ideally, if we wrote an alternative way to start a client, creating the stdin, stdout, and stderr pipes would be handled by the user and not something done explicitly by neovim. That way, the user just needs to return tables that have the above methods on them, rather than having to overwrite `uv.new_pipe` as well.

**Comment by chipsenkbeil** [comment]
@mjlbach I added one extra gotcha I just ran into. Had missed that if the binary didn't exist locally, a call to `vim.fn.executable` would fail. I had to temporarily overwrite that function as well during the call to `vim.lsp.start_client` to prevent `vim.lsp.rpc.start` from failing prematurely. We'd want to have checks like that done by the user-defined implementation rather than neovim verifying it. Of course, in neovim's default implementation, it would do all of the verifying itself like usual.

**Comment by justinmk** [comment]
This use case was discussed in https://github.com/neovim/neovim/issues/15648 , where I proposed https://github.com/neovim/neovim/issues/15648#issuecomment-921707494

**Comment by mjlbach** [comment]
@chipsenkbeil Yes, I'm aware distant doesn't use TCP, but if I'm rewriting the start client logic to allow swapping stdio via spawn, I'm going to also have it support TCP as that's required for certain servers.

**Comment by chipsenkbeil** [comment]
> @chipsenkbeil Yes, I'm aware distant doesn't use TCP, but if I'm rewriting the start client logic to allow swapping out the uv_spawn, I'm going to also have it support TCP as that's required for certain servers. Maybe my original post was unclear in retrospect, I'm lumping anything that is not a `uv_spawn`'d server over stdio together.

Okay, my misunderstanding :) I would just prefer to avoid writing too much special logic to handle LSPs within distant. For the most part, distant treats an LSP server like any other remote process and just acts as the bridge to forward stdin, stdout, and stderr back and forth. So if I can keep that functionality and plug it into neovim's `vim.lsp.start_client` in some way by providing an alternate version of spawning and pipes, I'm a happy camper!

**Comment by chipsenkbeil** [comment]
@mjlbach looks like this got moved to 0.7. Is there something I can do to help accelerate this? Would a draft PR help speed up the refactor?

**Comment by clason** [comment]
Neovim 0.6 is currently in feature-freeze, as we would like to release it by the end of the month. That would not be enough testing time for a PR, so it got bumped to 0.7 (which hopefully won't be that long afterwards).

**Comment by mjlbach** [comment]
We're planning on releasing 0.6 in a couple weeks, and technically in "feature freeze" mode right now. If you want to lead this I would consider merging it before the 0.7 cycle, but informally I think we're targeting around a 6 month release cycle (pending roadmap discussions). Of course I only speak for me :) 

I'm focused right now on ensuring our multibyte handling is correct because I think that's a more pressing issue.

**Comment by chipsenkbeil** [comment]
> We're planning on releasing 0.6 in a couple weeks, and technically in "feature freeze" mode right now. If you want to lead this I would consider merging it before the 0.7 cycle, but informally I think we're targeting around a 6 month release cycle (pending roadmap discussions). That being said I would like to redesign the interface around start_client which I think is likely going to be hard to do/approve before 0.6. Of course I only speak for me :) 
> 
> I'm focused right now on ensuring our multibyte handling is correct because I think that's a more pressing issue. 

Alright, why don't I kick off a pr in the next couple of weeks to start the conversation? This doesn't need to be accepted, but I want to make sure we're progressing towards a solution in time for 0.7. :)

**Comment by mjlbach** [comment]
If it instills any confidence, it's my highest priority for 0.7

**Comment by chipsenkbeil** [comment]
@mjlbach just wanted to check on the status of this one. Is it now planned for 0.8 of neovim? Or is it no longer on the roadmap? It's both in the LSP integration project for 0.8 and on the unplanned milestone. Wanted to know what I should expect with this :)

**Comment by clason** [comment]
Expect nothing; enjoy surprises.

**Comment by mfussenegger** [comment]
As far as I can tell this has mostly been done with the introduction of the tcp support (https://github.com/neovim/neovim/pull/19916)

The `cmd` property of lsp.start_client can be a function. This will also be used for named pipe/domain socket support: https://github.com/neovim/neovim/pull/26032
