### ISSUE TITLE
lsp: NO_RESULT_CALLBACK_FOUND with ccls, rust-analyzer

### ISSUE THREAD

**Issue by doupongzeng** [neovim/neovim#15844]
### Description

Same as [multiple NO_RESULT_CALLBACK_FOUND errors printed on LSP init. neovim/nvim-lspconfig#225](https://github.com/neovim/nvim-lspconfig/issues/225#issue-614559536)

### Neovim version

NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

4a392902152dd2c152608aa9f7ad73f73d26fcdd

### Operating system and version

ubuntu 20.04

### Affected language servers

ccls

### Steps to reproduce

1. git clone https://github.com/espressif/esp-idf.git
```
mkdir -p ~/esp
cd ~/esp
git clone --recursive https://github.com/espressif/esp-idf.git
```
2. config esp-idf,
```
cd ~/esp/esp-idf
./install.sh esp32
. $HOME/esp/esp-idf/export.sh
```
3. cp -r esp-idf/examples/get-started/hello_world .
4. cd hello_world
5. idf.py build
6. cp build/compile_commands.json .
7. nvim main/hello_world_main.c

### Actual behavior

LSP[ccls]: Error NO_RESULT_CALLBACK_FOUND: {                                                                                                                          
  error = {                                                                                                                                                           
    code = -32603,                                                                                                                                                    
    message = "failed to index /home/myname/esp/esp-idf/components/xtensa/expression_with_stack_xtensa_asm.S"                                                     
  },                                                                                                                                                                  
  id = 1,                                                                                                                                                             
  jsonrpc = "2.0"                                                                                                                                                     
Press ENTER or type command to continue

### Expected behavior

Everything will be ok.

### Minimal config

```
404: Not Found
```
my vimrc https://github.com/doupongzeng/myvimrc.lua

### Health check

health#lspconfig#check                                                                                                                                            
  2 ========================================================================                                                                                          
  3 ## Checking language server protocol configuration                                                                                                                
  4   - INFO: jsonls: configuration checked.                                                                                                                          
  5   - INFO: ccls: configuration checked.

### LSP log

https://gist.github.com/doupongzeng/4886b48e02fa22bc1a33262b067d158c

**Comment by justinmk** [comment]
We do not / cannot troubleshoot all LSP servers. If you find a problem with the vim.lsp client then provide a minimal repro , or send a PR.

**Comment by justinmk** [comment]
see https://github.com/rust-lang/rust-analyzer/issues/12482#issuecomment-1149176195

> > How do other LSP clients handle this? Just ignore it?
> 
> There isn't really anything to ignore here, when a reply comes in a client should only mark the request that belongs to that reply as resolved. "Resolving" multiple requests from one reply and then expecting no replies for the other requests to come in won't work as per spec the server should reply to every request in some form.

**Comment by igorlfs** [comment]
I have the same error with `sqlls`.

**Comment by keyboard-clacker** [comment]
@igorlfs also having the issue with sqlls, might be an issue with that specific LSP. Haven't been able to find an LSP that works with postgres yet.

**Comment by igorlfs** [comment]
> might be an issue with that specific LSP

Yeah, there's even an open [issue](https://github.com/joe-re/sql-language-server/issues/128), but since it was happening with other servers, I decided to comment here too.

**Comment by sbromberger** [comment]
Just adding - getting this with neovim master as of last night, with rust-analyzer and nvim-lsp.

**Comment by bobtwinkles** [comment]
Something is causing the r-a LSP to send two replies with the same ID, see the attached log:
[lsp_debug.log](https://github.com/neovim/neovim/files/8884851/lsp_debug.log)

It would be nice for the neovim LSP to handle this more gracefully (not filling my screen with garbage and taking focus), but I do think the bug is in R-A here? The problem seems to be related to `editor.action.triggerParameterHints`?

**Comment by bobtwinkles** [comment]
I grabbed a rust-analyzer log in parallel with the neovim LSP log as well:

[error-0-lsp.log](https://github.com/neovim/neovim/files/8884904/error-0-lsp.log)
[error-0-r-a.log](https://github.com/neovim/neovim/files/8884905/error-0-r-a.log)

**Comment by bobtwinkles** [comment]
The particular rust-analyzer problem was fixed via https://github.com/rust-lang/rust-analyzer/pull/12508, but I think some UI improvement could still be made on the neovim side. The "extra" replies seem ultimately harmless for the neovim LSP to swallow, instead of printing a verbose and distracting error message.

**Comment by sbromberger** [comment]
Can also confirm that #12508 fixes the pages of error messages. Thank you!

**Comment by justinmk** [comment]
## Status

Fixed in rust-analyzer by https://github.com/rust-lang/rust-analyzer/pull/12508

> I think what might be happening here is that the client cancels the completion request, we acknowledge that but still return a response.

rust-analyzer was resetting the cancelled state of requests when retrying them which made it reply to already cancelled requests again.

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._
