### ISSUE TITLE
Blocks of code being underlined for seemingly no reason

### ISSUE THREAD

**Issue by K4LCIFER** [neovim/neovim#15855]
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

Don't have vim

### Operating system/version

ArchLinux

### Terminal name/version

Alacritty 0.9.0

### $TERM environment variable

alacritty

### Installation

archlinux repository

### How to reproduce the issue

I'm not sure how to reproduce the issue, but I have noticed it sometimes occurring within math environments in LaTeX. 

### Expected behavior

I expect the code to not be randomly underlined.

### Actual behavior

As seen here this latex code has been underlined for some reason.
![image](https://user-images.githubusercontent.com/7829231/135557729-66e8aba8-b3fd-434b-bbd7-5194ebd9e054.png)

**Comment by zeertzjq** [comment]
Try installing [vim-scriptease](https://github.com/tpope/vim-scriptease) and pressing `zS` on the underlined code to see the highlight group.

**Comment by clason** [comment]
We need a minimal example to reproduce it; as it stands, this is impossible to act on: What plugins are you using? Is this syntax highlighting from Neovim's default syntax file, from VimTeX, or from tree-sitter? Are you running an LSP (so this might be diagnostics)? etc.

**Comment by justinmk** [comment]
Looks like a syntax/runtime question, we can't spend the time to troubleshoot that here.
