### ISSUE TITLE
floaterm terminal mouse drag x,y offset in visual mode not correct

### ISSUE THREAD

**Issue by mckellygit** [neovim/neovim#15857]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+368-g9337fff8a

### Vim (not Nvim) behaves the same?

no, but vim doesn't support visual drag in terminal

### Operating system/version

ubuntu 18.04

### Terminal name/version

st, alacritty, kitty, xterm all show same issue

### $TERM environment variable

xterm-256color

### Installation

built from git repo

### How to reproduce the issue

I am using a plugin -
Plug 'voldikss/vim-floaterm'
I create a floating terminal.
If I go into normal mode in that terminal and then visual mode in that terminal and then drag with LeftMouse,
the x,y of the drag-end is off by about the same offset as the upper left corner of the floatterm as compared to base window.  If I create a full-size terminal (not floating) then the x,y from a drag are correct.
I recall it used to work properly a while ago, but I have not done a bisect, sorry.
thx again for awesome neovim,
-m

### Expected behavior

mouse x,y when dragging with LeftMouse are aligned to mouse pointer

### Actual behavior

x,y are offset about the same as the floating terminal is to the base window

**Comment by mckellygit** [comment]
I think this may be a plugin issue.  I will close it.

**Comment by zeertzjq** [comment]
I can also reproduce this with toggleterm.nvim.

**Comment by zeertzjq** [comment]
I guess #15813 will fix this.

**Comment by mckellygit** [comment]
@zeertzjq thanks so much.  Yes, I tested the https://github.com/neovim/neovim/pull/15813 commit and it fixes the issue for me.
take care,
-m
