### ISSUE TITLE
Mappings are not applied to the `<Esc>` and the following key for unmapped `ALT-` keystrokes

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#15869]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+373-g36408146a

### Vim (not Nvim) behaves the same?

no, vim 8.2.3441

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

Build from source

### How to reproduce the issue

1. Run `nvim --clean`
2. Add mappings `:nnoremap <Esc> <Cmd>echomsg 'Esc'<CR>` and `:nnoremap x <Cmd>echomsg 'x'<CR>`.
3. Press `ALT-x` or press `<Esc>` and `x` quickly
4. Run `:messages`

### Expected behavior

There are two lines of messages:
```
Esc
x
```
Doing the same things in Vim in terminal shows these two messages.

### Actual behavior

There are no messages

***

Since a key typed too fast following `<Esc>` in terminal is indistinguishable from an `ALT` keystroke, I think it is reasonable that mappings should be applied to the `<Esc>` and the following key just like they are applied to normally typed keys if the `ALT-` keystroke is unmapped.

**Comment by justinmk** [comment]
This is a feature, 

```
:help i_ALT
:help c_ALT
:help v_ALT
```

 I don't think there is a way to have it "both ways". If you want `<m-x>` to be mapped... just map it.

**Comment by zeertzjq** [comment]
Consider this use case:
1. One has [vim-sneak](https://github.com/justinmk/vim-sneak) or [lightspeed.nvim](https://github.com/ggandor/lightspeed.nvim) installed.
2. In Insert mode, they press `<Esc>` to go to normal mode and then press `s` to sneak to a position.
3. `<Esc>` and `s` are pressed too fast that they are recognized as `<M-s>`.
4. `<M-s>` is unmapped, so it is translated to `<Esc>` and `s`, but mappings don't apply to the `<Esc>` and `s` in the current version of Neovim.

Of course it is also possible that they have `<Esc>` mapped as well, for example, [coq_nvim](https://github.com/ms-jpq/coq_nvim) requiring mapping `<Esc>` in Insert mode so it behaves less surprisingly.

**Comment by justinmk** [comment]
do things work as you expect if you comment out this: https://github.com/neovim/neovim/blob/2f06413dfb3624381f112b7d8661fde659c279e7/src/nvim/getchar.c#L1531-L1540

**Comment by zeertzjq** [comment]
I think commenting out this just prevents `<A-s>` from being converted back to `<Esc>s` at all, doesn't it?

I have tried to change these three lines:
<https://github.com/neovim/neovim/blob/2f06413dfb3624381f112b7d8661fde659c279e7/src/nvim/getchar.c#L1537-L1539>
to:
```c
    KeyNoremap = false;
    ins_char_typebuf(c);
    ins_char_typebuf(ESC);
    c = vgetorpeek(true);
```
And mappings for the following character worked, but mappings for `<Esc>` didn't.

**Comment by justinmk** [comment]
does https://github.com/neovim/neovim/pull/13109 fix this?

**Comment by zeertzjq** [comment]
> Looks like #13109 fixes this.
> 
> > * Add mappings `:nnoremap <Esc> <Cmd>echo 'Esc'<CR>` and `:nnoremap x <Cmd>echo 'x'<CR>`.
> 
> I assume you mean `:echom`, not `:echo` (which does not write to `:messages` )

Oh, Indeed. I've corrected the typo.
