### ISSUE TITLE
I think I found an issue with errorformat for :compiler jest

### ISSUE THREAD

**Issue by refaelsh** [neovim/neovim#15876]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

Arch Linux

### Terminal name/version

Alacritty 0.9.0

### $TERM environment variable

alacritty

### Installation

Arch Linux's package manager: pacman

### How to reproduce the issue

Hi all,

I think I found an issue with `errorformat` for `:compiler jest`. It does not filter out `console.log` thingies. Here are some screenshots (you can see the `console.log` thingies):
![6_002](https://user-images.githubusercontent.com/2750775/135728702-825a342e-5c3d-47d9-9642-f1191c31a6ce.jpg)
Then I press enter and I see the `console.log` thingies in the quicklist window:
![6_001](https://user-images.githubusercontent.com/2750775/135728709-34c23b74-3818-4a36-b3c4-79876c38e784.jpg)
I think its a problem with the `errorformat` for `:compiler jest`. What do you guys think?

Thanks.

### Expected behavior

The `console.log` thingies should have been filtered out.

### Actual behavior

The `console.log` thingies are not filtered out.

**Comment by gpanders** [comment]
Thanks for taking the time to submit an issue. Unfortunately, neovim does not maintain the Jest compiler plugin nor any runtime files for that matter. You will need to submit an issue (or even better, a PR) to [Vim](https://github.com/vim/vim) directly, which will also need approval from the maintainer of the compiler plugin. Once the change is accepted in Vim it will be ported into Neovim.

**Comment by refaelsh** [comment]
I understand. Thank you very much for the answer.
