### ISSUE TITLE
No filetype assigned to some JavaScript configuration files

### ISSUE THREAD

**Issue by eruizc-dev** [neovim/neovim#15887]
### Feature already in Vim?

No

### Feature description

As mentioned in the title, when you open either a .babelrc, .eslintrc, .prettierrc, and also .firebaserc (not related to JS but sill) there's no filetype assigned causing no highlight and no LSP attachment.

They're all JSON files, I've added the following to my configuration and was considering if this is worth implementing to neovim itself:

```vim
au BufRead,BufNewFile .babelrc setfiletype json
au BufRead,BufNewFile .eslintrc setfiletype json
au BufRead,BufNewFile .prettierrc setfiletype json
au BufRead,BufNewFile .firebaserc setfiletype json
```

**Comment by clason** [comment]
Filetype detection is part of the runtime files we inherit from vim; hence that's a change that needs to be made upstream. (Your autocommands are the usual way of handling such things, though.)
