### ISSUE TITLE
Failed to find the `s:` scoped function

### ISSUE THREAD

**Issue by tani** [neovim/neovim#15880]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

no. vim 8.2

### Operating system/version

Ubuntu 20.04, WSL

### Terminal name/version

MobaXterm v21.2

### $TERM environment variable

xterm-256color

### Installation

repo's binary

### How to reproduce the issue

The minimal `init.vim` is

```vim
call plug#begin(data_dir . '/plugged')
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
call plug#end()

let g:lsp_log_file = expand('~/.cache/vimlsp.log')
```

and `test.ts` file is

```typescript
import * as path from "https://deno.land/std/node/path.ts"
path.resolve
```

1. Run `:PlugInstall` in neovim
2. Run `:e test.ts` to open TypeScript file
3. Run `:LspInstallServer deno` install deno language server
4. Run `:LspDenoDefintiion` on `resolve` in `test.ts`

Then, the last command is failed.
We can see the reason in the log file `~/.cache/vimlsp.log`

```
...
Sun Oct  3 08:12:37 2021:["s:on_stdout client request on_notification() error", "Vim(if):E121: Undefined variable: v:none", "function <SNR>199_on_stdout[2]..<SNR>197_on_stdout[79]..<SNR>165_request_on_notification[3]..<SNR>166_createNext[1]..<SNR>166_subscribeSourceCallback[2]..<lambda>149[1]..<SNR>164_handle_deno_location, line 16"]
...
```

### Expected behavior

Jump to the definition.

### Actual behavior

vim-lsp code is

https://github.com/mattn/vim-lsp-settings/blob/e658a1f04d492ce7638e36055f394fe456139e9b/settings/deno.vim#L71-L199

I expect the following line refers to the local function `s:handle_deno_location`. In the fact, vim can find this local function. On the other hand, neovim does not.

https://github.com/mattn/vim-lsp-settings/blob/e658a1f04d492ce7638e36055f394fe456139e9b/settings/deno.vim#L195

thanks

**Comment by justinmk** [comment]
We don't have the resources to troubleshoot your plugins.

For questions about usage/configuration, try 
- http://discourse.neovim.io/ 
- https://vi.stackexchange.com
- https://neovim.io/#chat

The issue tracker is for bugs and feature requests.

**Comment by tani** [comment]
Oops, okay. thanks.

2021年10月3日(日) 9:46 Justin M. Keyes ***@***.***>:
