### ISSUE TITLE
Omnicompletion skips results from lsp

### ISSUE THREAD

**Issue by gemboj** [neovim/neovim#15884]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+388-g23d13aa4c

### Language server name/version

gopls 0.7.2

### Operating system/version

Ubuntu 18.04, Ubuntu 20.04.3 (wsl 2)

### :checkhealth

```markdown
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: gopls: configuration checked.
```

### Steps to reproduce using "nvim -u minimal_init.lua"

Sample golang file:
```
package main

func main() {
	FoB
}

func FooBar() {}
func FoBar() {}
func FooDaz()   {}
```

1. Copy the provided golang file into a new directory `test`
2. Inside the `test` directory initialize a go module with `go mod init test`
3. Open the provided golang file with minimal config: `nvim -nu ~/.config/nvim/minimal.lua main.go`
4. Go to line 4 where the `FoB` word is.
5. Try to complete it using Omnifunc: `<C-X><C-O>`

### Expected behavior

The Omnifunc displays two results: `FoBar` and `FooBar`.

### Actual behavior

The Omnifunc displays only a single result of `FoBar` function.

The response from the lsp server actually returns expected matches (both the `FoBar` and `FooBar`), just the Omnifunc does not display them (JSON formatted for convinence, line 52 from included `lsp.log`):
```
{
   id = 2,
   "jsonrpc =""2.0",
   "result ="{
      "isIncomplete = true",
      "items ="{
         {
            "detail =""func()",
            "filterText =""FoBar",
            insertTextFormat = 1,
            kind = 3,
            "label =""FoBar",
            "labelDetails = vim.empty_dict()",
            "preselect = true",
            "sortText =""00000",
            "textEdit ="{
               "newText =""FoBar",
               "range ="{
                  "end ="{
                     character = 4,
                     line = 3
                  },
                  "start ="{
                     character = 1,
                     line = 3
                  }
               }
            }
         },
         {
            "detail =""func()",
            "filterText =""FooBar",
            insertTextFormat = 1,
            kind = 3,
            "label =""FooBar",
            "labelDetails = vim.empty_dict()",
            "sortText =""00001",
            "textEdit ="{
               "newText =""FooBar",
               "range ="{
                  "end ="{
                     character = 4,
                     line = 3
                  },
                  "start ="{
                     character = 1,
                     line = 3
                  }
               }
            }
         }
      }
   }
}
```

### Log file

https://gist.github.com/gemboj/aa4871e644ef7b67eb8b309e2ca67551

**Comment by mfussenegger** [comment]
The built-in omni function only does prefix matching - not fuzzy matching. `FooBar` doesn't share the prefix with `FoB` - assuming you places the cursor after the `B` on `FoB|`.

**Comment by mfussenegger** [comment]
One more thing to add - there is another issue about using the ranges of the textEdit to determine the word boundary - https://github.com/neovim/neovim/issues/15884

If we do that, the example here in this issue may end up working as a side-effect.

**Comment by gemboj** [comment]
> The built-in omni function only does prefix matching - not fuzzy matching. `FooBar` doesn't share the prefix with `FoB` - assuming you places the cursor after the `B` on `FoB|`.

Then the question is: why does the built-in omni function do any kind of matching, especially when dealing with the response from the lsp servers? The response from the Golangs LSP gopls is already filtered and ordered, so there is no more matching required. Is there any way to disable this?

Also, by my understanding, the documentation is a bit misleading. It says here
https://github.com/neovim/neovim/blob/73280a7987dac01be77f787ab4a5880babdee391/runtime/doc/lsp.txt#L48
that the `vim.lsp.omnifunc` is an omnifunc handler that will `will provide completions from the language server`. In reality, this is not true, as it seems to not only provide completions from the language server, but also FILTERS them. This led me to believe that the language server returns only a handful of matches while in reality, the language server does its job well returning all the matches but the build-in omni function hampers it by skipping valuable fuzzy matches.

**Comment by zeertzjq** [comment]
Maybe this can be solve by changing this line:
<https://github.com/neovim/neovim/blob/acd5e831b6294e54b12c09983bee3da89c0f183a/runtime/lua/vim/lsp.lua#L1431>
to:
```lua
vim.fn.complete(vim.fn.col('.'), items)
```
I don't have time to test if this works though.
