### ISSUE TITLE
[Possible regression from vim] display bugs

### ISSUE THREAD

**Issue by batbone** [neovim/neovim#15898]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

8.2.3450  

### Operating system/version

macOS 11.2.1

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

brew install nvim

### How to reproduce the issue

I have documented the bug on https://github.com/kovidgoyal/kitty/issues/4094 , and I am not sure if it is a neovim bug, but it does not happen using `vim 8.2.3450`, so you might still want to take a look.

Update: Based on Kitty's maintainer responses, this is likely to be a neovim issue.

### Expected behavior

_

### Actual behavior

_

**Comment by bfredl** [comment]
There's a lot of noise and discussion in that thread. Please submit, in this issue, full reproduction steps for _nvim_ and then show us a screenshot of actual behavior from _nvim_ (+ expected behaviour from vim or some other editor without the issue, or nvim in some other mode), otherwise we need to close the issue for being vague and unactionable.

**Comment by batbone** [comment]
@clason @bfredl  Okay, I'll copy the most relevant bits from that thread over.

---

Prescript: I have no idea if these two bugs are related or not. Feel free to create two separate issues if you think they are unrelated, which I increasingly suspect.

# First bug (`weird.txt`)
Steps to reproduce the behavior:
1. `command kitty --config=/dev/null`
2. `curl https://files.lilf.ir/tmp/weird.txt > weird.txt`
3. `nvim weird.txt`
4. Try deleting that `e` and type `A`. The corruption is obvious:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60806622/135812976-087e100c-f893-4497-a110-3363be7096eb.png">


This bug reproduces with nvim on Kitty and iTerm, but not on Alacritty or Terminal.app.


I have also reproduced the bug on Ubuntu 20 via SSH, so it happens on both macOS and Linux, at least when the terminal emulator runs from macOS.


`vim` works correctly:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60806622/135852335-9fcdf125-9987-47f6-a099-a6404450991e.png">


# Second bug (`bug_ltr.txt`)
1. `command kitty --config=/dev/null`
2. `curl https://files.lilf.ir/tmp/bug_ltr.txt > bug_ltr.txt`
2. Do `cat bug_ltr.txt` and note the output:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/60806622/135824409-034d3a3e-8c26-400b-bfc7-5b4efba1bc84.png">
3. `nvim bug_ltr.txt`
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60806622/135824455-f5c44117-8f3d-4968-995a-b4b2903c4b30.png">
4. Note the corruption; In particular, the line `#+TITLE: sharif/contact info` is not displayed at all, and the mode-line is displayed incorrectly.



This bug reproduces with nvim, on Kitty, and not on iTerm, Alacritty, or Terminal.app. This is presumably because the other terminal emulators do not support  unicode variation selectors, and so the two bugs cancel each other out.


`vim` still works correctly though:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60806622/135814733-7180fce8-d9b2-4fb8-ac1c-0c673b1b9260.png">


Removing the unicode variation selectors in `bug_ltr.txt` will make the bug go away:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/60806622/135845873-d0142588-c7ff-4bfe-ad37-adafaf4b8ad5.png">

I used this code to remove the variation selectors:
```go
package main

import (
	"fmt"
	"io/ioutil"
	"unicode"
	"os"
	"log"
)

func main() {
	inBytes, err := ioutil.ReadAll(os.Stdin)
	if err != nil {
		log.Fatalln(err.Error())
	}
	input := string(inBytes)

	output := make([]rune, 0)
	for _, rune := range input  {
		if ! unicode.In(rune, unicode.Variation_Selector) {
			output = append(output, rune)
		}
	}

	fmt.Printf("%s", string(output))

}
```


**Environment details**
```
nvim: 0.5.1
kitty: 0.23.1
TERM: xterm-kitty
macOS: 11.2.1

Important settings:
  value of $LC_ALL: en_US.UTF-8
  value of $LANG: en_US.UTF-8
  locale-coding-system: utf-8-unix
```

I have attached the reproduction files here as well:
- [bug_ltr.txt](https://github.com/kovidgoyal/kitty/files/7276937/bug_ltr.txt)
- [bug.txt](https://github.com/kovidgoyal/kitty/files/7276629/bug.txt)
- [weird.txt](https://github.com/kovidgoyal/kitty/files/7276630/weird.txt)

**Comment by batbone** [comment]
Both issues seem to be caused by different assumptions about character widths between the terminal emulator programs and neovim. I suggest reading the original thread, but here is a summary (read `emacs` as `neovim`, as it is highly likely they are both making the same assumptions):


# `weird.txt`

> The problematic character in the first example is U+00AD SOFT HYPHEN.
> Kitty assumes that character is never rendered, and therefore
> effectively treats it as zero-width character.

(Presumably iTerm makes the same assumption as Kitty.)

# `bug_ltr.txt`
> The character pair U+25ab and U+FE0F must be rendered in two cells, as
> U+FE0F converts U+25ab from *text presentation* to *emoji presentation*. And
> emoji in terminals are rendered at width two.
> 
> kitty does this, Terminal.app does not. emacs assumes it must be
> rendered in one cell.

**Comment by zeertzjq** [comment]
There are some existing `wcwidth` related issues. I think this is the first one related to non-emoji characters though.

That thread also seems to mention U+FE0F, so #10026 may also be related.

**Comment by batbone** [comment]
@bfredl How are you handling older terminal emulators like Terminal.app where U+FE0F does NOT change the width?

**Comment by justinmk** [comment]
Is this still an issue?

**Comment by NightMachinery** [comment]
@justinmk I just tested it and it seems there is no longer an issue. But I am not using `nvim` much nowadays, so others should also chime in.
