### ISSUE TITLE
Unclear behavior for `make_given_range_params()` and related functionality

### ISSUE THREAD

**Issue by ckipp01** [neovim/neovim#15905]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+8a9f29299

### Language server name/version

All of them, as this is just an issue with `lsp/util.lua`

### Operating system/version

Mac Big Sur 11.6

### :checkhealth

```markdown
I don't have `lspconfig` configured for this. It's an issue that is more tied to the general use of some of the LSP functionality around ranges.
```

### Steps to reproduce using "nvim -u minimal_init.lua"

To reproduce what I'm showing you can use the following `init.lua`:

```lua
function print_range()
  print(vim.inspect(vim.lsp.util.make_given_range_params()))
end

vim.api.nvim_set_keymap("v", "<leader><leader>1", [[<cmd>lua print_range()<CR>]], {})
```

I'll do my explanation with a file called `test.txt` that contains the following:

```
123456789
123456789
123456789
123456789
123456789
```

### Expected behavior

When using the above mapping to get the selection range a la `vim.lsp.util.make_given_range_params()`. I'd expect to get the expected range params to be sent to the server for the currently visual selected text.

### Actual behavior

When opening the file I have above with `nvim -u ~/.config/nvim/repro.lua test.txt` I see some odd behavior which make using the functionality quite difficult. I'll explain some steps and some behaviors below which I think are confusing. Either that or I'm totally missing how a plugin should use this:

1. Open the file
2.  Go to line 4 and visual select the items on the line `123456789`. When you trigger the mapping for `print_range()` you should see the following:
```
{
  range = {
    end = {
      character = 1,
      line = -1
    },
    start = {
      character = 0,
      line = -1
    }
  },
  textDocument = {
    uri = "file:///Users/ckipp/Documents/scratch-workspace/test.txt"
  }
}
```
3. Now move one line down and do the same thing on line 5 and you'll see the following:
```
{
  range = {
    end = {
      character = 9,
      line = 3
    },
    start = {
      character = 0,
      line = 3
    }
  },
  textDocument = {
    uri = "file:///Users/ckipp/Documents/scratch-workspace/test.txt"
  }
}
```
It seems that the behavior of this function is to always return the _last_ visually selected range, which makes this impossible use to use when you're trying to grab a range to send into a server. For example in Metals, the Scala Language Server, we have a feature where you can send in a range to get the type of that range expression. However, using this from a visual mapping seems not to work at all? Am I maybe totally missing something here? For what it's worth I also tried manually creating the start and end of the range via:

```
  local start = vim.api.nvim_buf_get_mark(0, "<")
  local fin = vim.api.nvim_buf_get_mark(0, ">")
```
But this seems to emit some of the same behavior. I'm pretty stuck on how to actually capture the current selected range and feel like the given example above should do what I was expecting. I'd love to know if I'm totally missing something, if this behavior is actually expected, or what is going on here. Thanks!

**Comment by muniter** [comment]
So I found the reason for this, the visual mode ranges are update only on the following cases:

- Visual mode ends `end_visual_mode`
- Put commands `nv_put`
- Pending operator mode `do_pending_operator`

So running a mappings that's not an operator won't have the current visual ranges set for the current buffer. This should not be hard to fix by setting the visual mode ranges once a mappings is triggered if visual mode is set.

I could look into it to send a PR, but would also like input from one of the core devs.

**Comment by dundargoc** [comment]
You forgot the batsignal :) @neovim/core

**Comment by mfussenegger** [comment]
I thought this was kinda intentional. To get mappings to work it is possible to include an `<Esc>` - like in `<Esc><Cmd>lua vim.lsp.buf.range_formatting()<CR>` or `<Esc><Cmd>lua vim.lsp.buf.range_code_action()<CR>`

But others know this better than I do

**Comment by ckipp01** [comment]
> I thought this was kinda intentional

Any idea why this is intentional? Like what is the use case that you'd want the last range instead of the current one? Part of me feels like this behavior isn't what most would assume.

> To get mappings to work it is possible to include an <Esc> - like in <Esc><Cmd>lua vim.lsp.buf.range_formatting()<CR> or <Esc><Cmd>lua vim.lsp.buf.range_code_action()<CR>

I didn't think of this. Although again, I'm assuming that without explicit instruction to include the `<Esc>` most people wouldn't think to do this.

**Comment by mjlbach** [comment]
My understanding is this is a workaround for the behavior noted by @muniter, and unless I'm mistaken (totally possible) we don't have a good way to get the current visual ranges, but can only get the *last* visual ranges. This basically only applies to range_formatting and range_code_action, so it's not particularly widely used.

**Comment by muniter** [comment]
Is overall confusing behavior. But in a way, in vim language if you want to do something with a range you create an "operator" which in this case would update the visual selection range before returning because of `do_pending_operator`. 

On the other hand it should be straightforward to implement, if something asks for the visual range while in visual mode return the actual marks not the previous, but I don't know if this behavior would break plugins. I agree it might be worth tracking in another issue since the LSP function is doing the right thing.
