### ISSUE TITLE
When using split windows (:vsplit) mouse drag select (mouse=a) will always select from the cursor to the eol instead of what is being actually dragged on

### ISSUE THREAD

**Issue by charbelnicolas** [neovim/neovim#15903]
### Neovim version (nvim -v)

0.6.0-dev+398-gc4d581dea

### Vim (not Nvim) behaves the same?

No, vim 8.2

### Operating system/version

Arch Linux

### Terminal name/version

Kitty

### $TERM environment variable

xterm-kitty

### Installation

Arch User Repository AUR

### How to reproduce the issue

nvim --clean
:edit path/to/file
:vsplit
:set mouse=a

1. Drag select any text on the LEFT window.
2. Notice everything is working correctly.
3. Drag select the same text (or any text) on the RIGHT window.
4. Did you notice how it selects everything from the cursor to the end of the line?

Vim works as expected.

### Expected behavior

I expect the selected text to be only what I have dragged on, nothing more, nothing less.

### Actual behavior

It selects everything from where you started the drag select all the way until the end of that line.

https://user-images.githubusercontent.com/14960414/135897319-5d1d8736-6073-4e9e-9633-1b1299066a8f.mp4

**Comment by charbelnicolas** [comment]
Here is the same procedure on Vim (minus the set mouse=a part):


Uploading vimworks.mp4…

**Comment by charbelnicolas** [comment]
Here is the same procedure on Vim (minus the set mouse=a part):

https://user-images.githubusercontent.com/14960414/135898923-b48774c5-3ac9-4c61-8c71-fbd5f302802c.mp4

**Comment by bfredl** [comment]
potentially fixed by https://github.com/neovim/neovim/pull/15813

**Comment by charbelnicolas** [comment]
Nice, hopefully it gets merged soon, thanks!

**Comment by charbelnicolas** [comment]
I just tested it and everything seems to be working fine now! Thank you!
