### ISSUE TITLE
Cannot create temp file for executing external commands over a range when shell is set to powershell

### ISSUE THREAD

**Issue by 3N4N** [neovim/neovim#15913]
### Neovim version (nvim -v)

NVIM v0.5.1

### Vim (not Nvim) behaves the same?

Can't say. Do not have vim installed.

### Operating system/version

Windows 10 21H1

### Terminal name/version

Windows Terminal, Conhost

### $TERM environment variable

Nil

### Installation

Put the zip folder from release page and added the location in Windows path variable

### How to reproduce the issue

```vim
nvim -u NONE
:let &shell = 'pwsh'
:let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
:let &shellredir = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
:let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
:set shellquote= shellxquote=
:e random-nonempty.file
:1,5!sort
```

### Expected behavior

The lines from 1 to 5 should be sorted with the external `sort` command (which exists in my path).

### Actual behavior

I get the following error.

```vim
E485: Can't read file C:\Users\ACER\AppData\Local\Temp\nvim6UJx04\7
```

I checked with Process Monitor and saw that neovim is failing to create the file/subdirectory `...\nvim6UJx04\7` when the `:h 'shell'` is set to `pwsh` (PowerShell Core). With shell set to cmd, it works alright. ~~Note that in my full config, I set up the shell according to `:h 'shell-powershell'` but the same issue persists.~~

**Comment by 3N4N** [comment]
Here is a snap of the process with `shell=cmd`:
![image](https://user-images.githubusercontent.com/32037751/136010778-40ad279c-5ae4-4d5b-a270-00a2f3f6e98c.png)


And here is one with `shell=pwsh`:
![image](https://user-images.githubusercontent.com/32037751/136010902-d7f5e663-5fa4-4ba3-9504-f4b940c7e7f9.png)

**Comment by justinmk** [comment]
> ```viml
> :let &shell = 'pwsh'
> ```

There are many shell-related options in vim, it is not a simple matter of setting 'shell' only. See `:help shell-powershell` for the correct settings (which is a section of `:help 'shell'`... read the help before opening issues).

**Comment by justinmk** [comment]
> Note that in my full config, I set up the shell according to `:h 'shell-powershell'` but the same issue persists.

Wait, why isn't that part of the repro steps?

**Comment by 3N4N** [comment]
@justinmk I will update now. Thought I should reduce the steps as much as possible.

**Comment by justinmk** [comment]
> Thought I should reduce the steps as much as possible.

Yes :) But in this case setting only 'shell' is incorrect so it is not a sufficient repro.

**Comment by 3N4N** [comment]
Just checked with the newest release (0.5.1) and the issue remains.

**Comment by 3N4N** [comment]
@justinmk, I think I found where the problem is. It's in [here](https://github.com/neovim/neovim/blob/master/src/nvim/ex_cmds.c#L1352). The command for filtering is messed up. Following are gdb outputs of the variables for cmd and pwsh. The breakpoint was set at 

- CMD:
![image](https://user-images.githubusercontent.com/32037751/136437990-a0a6d72a-436c-488d-8c93-d44c6a03f99f.png)
- PWSH:
![image](https://user-images.githubusercontent.com/32037751/136438043-300abd4c-4ee5-48e3-a80c-953554ae9c51.png)


Breakpoint was set here:
![image](https://user-images.githubusercontent.com/32037751/136438362-93cd666f-ea22-4173-9101-d45dda8ec698.png)

**Comment by 3N4N** [comment]
Changing the title because nvim can *create* both in and out temp files, but just can't read the out temp file.

Need some insight from devs, though, to make sense of what's happening.

**Comment by 3N4N** [comment]
Okay, the problem *was* with powershell redirection. The one suggested in `:h shell-powershell` gives [`cmd_buf`](https://github.com/neovim/neovim/blob/master/src/nvim/ex_cmds.c#L1349) to be --

```gdb
gdb> p cmd_buf
$1 = (char_u *) 0x2513025da80 "sort.exe < C:/Users/ACER/AppData/Local/Temp/nvimnr4hM4/0 2>&1 | Out-File -Encoding UTF8 C:/Users/ACER/AppData/Local/Temp/nvimnr4hM4/1; exit $LastExitCode"
```

But PowerShell doesn't use `<` as file input redirection. It has a special argument. When I change `cmd_buf` like in the following, the filter works (the lines are sorted, I mean).

```gdb
gdb> set cmd_buf = "Start-Process sort.exe -RedirectStandardInput C:/Users/ACER/AppData/Local/Temp/nvimnr4hM4/0 -RedirectStandardOutput C:/Users/ACER/AppData/Local/Temp/nvimnr4hM4/1  -NoNewWindow -Wait"                                                              gdb> p cmd_buf
$2 = (char_u *) 0x2513026b0b0 "Start-Process sort.exe -RedirectStandardInput C:/Users/ACER/AppData/Local/Temp/nvimnr4hM4/0 -RedirectStandardOutput C:/Users/ACER/AppData/Local/Temp/nvimnr4hM4/1  -NoNewWindow -Wait"
```

I guess the easy workaround would be to force-use `cmd.exe` whatever the `shell` is set to. I don't think we users would care who is doing our work, as long as the work is done. Then again, someone may want to use powershell-specific command. Then you'd have to create a powershell-specific command for `make_filter_cmd` function. But judging by how no one except me found this bug, I'm gonna bet no one actually cares.

Tagging @justinmk for update.

**Comment by 3N4N** [comment]
This is working, but you guys could make it better.

```git
diff --git a/src/nvim/ex_cmds.c b/src/nvim/ex_cmds.c
index 1bd9411fa560..b612937aa47f 100644
--- a/src/nvim/ex_cmds.c
+++ b/src/nvim/ex_cmds.c
@@ -1553,17 +1553,31 @@ char_u *make_filter_cmd(char_u *cmd, char_u *itmp, char_u *otmp)
 #else
     false;
 #endif
+  bool is_pwsh =
+#if defined(UNIX)
+      false;
+#else
+    STRNCMP(invocation_path_tail(p_sh, NULL), "pwsh", 4) == 0;
+#endif
 
   size_t len = STRLEN(cmd) + 1;  // At least enough space for cmd + NULL.
 
   len += is_fish_shell ?  sizeof("begin; " "; end") - 1
                        :  sizeof("(" ")") - 1;
+  len += is_pwsh    ? sizeof("Start-Process "  " -RedirectStandardInput ")
+                    :  sizeof("(" ")") - 1;
 
   if (itmp != NULL) {
-    len += STRLEN(itmp) + sizeof(" { " " < " " } ") - 1;
+      if (is_pwsh)
+          len += STRLEN(itmp);
+      else
+          len += STRLEN(itmp) + sizeof(" { " " < " " } ") - 1;
   }
   if (otmp != NULL) {
-    len += STRLEN(otmp) + STRLEN(p_srr) + 2;  // two extra spaces ("  "),
+      // if (is_pwsh)
+      //     len += STRLEN(otmp) + STRLEN(p_srr) + 2;  // two extra spaces ("  "),
+      // else
+          len += STRLEN(otmp) + STRLEN(p_srr) + 2;  // two extra spaces ("  "),
   }
   char *const buf = xmalloc(len);
 
@@ -1585,7 +1599,17 @@ char_u *make_filter_cmd(char_u *cmd, char_u *itmp, char_u *otmp)
 #else
   // For shells that don't understand braces around commands, at least allow
   // the use of commands in a pipe.
-  xstrlcpy(buf, (char *)cmd, len);
+  if (is_pwsh) {
+      // Start-Process sort.exe -RedirectStandardInput C:/Users/ACER/AppData/Local/Temp/nvimnr4hM4/0
+      // -RedirectStandardOutput C:/Users/ACER/AppData/Local/Temp/nvimnr4hM4/1
+      // -NoNewWindow -Wait
+      xstrlcpy(buf, "Start-Process ", len);
+      xstrlcat(buf, (char *)cmd, len);
+  }
+  else {
+      // sort.exe < C:/Users/ACER/AppData/Local/Temp/nvimnr4hM4/0 2>&1 | Out-File -Encoding UTF8 C:/Users/ACER/AppData/Local/Temp/nvimnr4hM4/1; exit $LastExitCode
+      xstrlcpy(buf, (char *)cmd, len);
+  }
   if (itmp != NULL) {
     // If there is a pipe, we have to put the '<' in front of it.
     // Don't do this when 'shellquote' is not empty, otherwise the
@@ -1596,14 +1620,20 @@ char_u *make_filter_cmd(char_u *cmd, char_u *itmp, char_u *otmp)
         *p = NUL;
       }
     }
-    xstrlcat(buf, " < ", len);
-    xstrlcat(buf, (const char *)itmp, len);
+    if (is_pwsh) {
+        xstrlcat(buf, " -RedirectStandardInput ", len);
+        xstrlcat(buf, (const char *)itmp, len);
+    }
+    else {
+        xstrlcat(buf, " < ", len);
+        xstrlcat(buf, (const char *)itmp, len);
+    }
     if (*p_shq == NUL) {
-      const char *const p = find_pipe((const char *)cmd);
-      if (p != NULL) {
-        xstrlcat(buf, " ", len - 1);  // Insert a space before the '|' for DOS
-        xstrlcat(buf, p, len - 1);
-      }
+        const char *const p = find_pipe((const char *)cmd);
+        if (p != NULL) {
+            xstrlcat(buf, " ", len - 1);  // Insert a space before the '|' for DOS
+            xstrlcat(buf, p, len - 1);
+        }
     }
   }
 #endif
```
