### ISSUE TITLE
tabstop=8 doesn't work

### ISSUE THREAD

**Issue by ragnarov** [neovim/neovim#15925]
### Neovim version (nvim -v)

NVIM v0.5.0 (appimage)

### Vim (not Nvim) behaves the same?

No. Vim works purrrrrrrrfect
Version :

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 15 2021 21:48:21)
Included patches: 1-3441
Compiled by Arch Linux
```

Filetype: `.bashrc`

I directly set the options in command-line mode as I no longer have a .vimrc file.
### Operating system/version

Arch Linux 5.10.69-1-lts x86_64

### Terminal name/version

rxvt-unicode (urxvt) v9.26 - released: 2021-05-14

### $TERM environment variable

rxvt-unicode-256color

### Installation

AppImage

### How to reproduce the issue

Just add to `~/.config/nvim/init.vim` the following :

```
set expandtab
set shiftwidth=4
set tabstop=8
```
One could directly apply this in command-line mode.
Try inserting tab character in insert mode.
You will see tab inserts 4 spaces not 8.

Filetype: `.bashrc, init.vim` 

### Expected behavior

Should insert 8 spaces

### Actual behavior

Inserts 4 spaces with the config I used.

**Comment by chrisbra** [comment]
Note: tabstop is a buffer-local option, so this may get overridden by some filetype plugins. Check the output of `:verbose set ts?`

**Comment by clason** [comment]
Nevermind, that is by design: Neovim sets `smarttab` by design (`:h vim-differences`):
```
'smarttab' 'sta'        boolean (default on)
                        global
        When on, a <Tab> in front of a line inserts blanks according to
        'shiftwidth'.  'tabstop' or 'softtabstop' is used in other places.  A
        <BS> will delete a 'shiftwidth' worth of space at the start of the
        line.
```

**Comment by ragnarov** [comment]
`set nosmarttab`
Fixed this for me.
thanks @clason
