### ISSUE TITLE
job-control example in other languages

### ISSUE THREAD

**Issue by notalex** [neovim/neovim#1592]
Neovim's job-control example in `:help job-control` works well for bash scripts. However, I am unable to make it work for ruby. Consider the following example:

    set nocp
    set buftype=nowrite

    call jobstart('shell', 'bash', ['-c', 'for ((i = 0; i < 5; i++)); do sleep 2 && printf "Hello Bash!\n"; done'])
    call jobstart('shell', 'ruby', ['-e', '5.times do sleep 2 and puts "Hello Ruby!" end'])

    function JobHandler()
      if v:job_data[1] == 'exit'
        let str = v:job_data[0] . ' exited'
      else
        let str = join(v:job_data[2])
      endif

      call append(line('$'), str)
    endfunction

    au JobActivity shell* call JobHandler()

Running `nvim -u NONE -S <filename>` produces the following output:

    Hello Bash!
    Hello Bash!
    Hello Bash!
    Hello Bash!
    Hello Bash!
    1 exited
    Hello Ruby! Hello Ruby! Hello Ruby! Hello Ruby! Hello Ruby!
    2 exited

How do we make the ruby example work like that for bash?

**Comment by lucc** [comment]
Should this be closed and #1593 put in the 0.1 milestone instead?

**Comment by fmoralesc** [comment]
@lucc Yes, this should have been closed.
