### ISSUE TITLE
`vim.diagnostic.show_line_diagnostics()` not respecting severity sort (no option to set either)

### ISSUE THREAD

**Issue by megalithic** [neovim/neovim#15947]
### Neovim version (nvim -v)

v0.6.0-dev+401-gb60e6448e

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

macOS 11.6

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

-- requires some setup, basic lsp configured for anything (using lua in this case)
nvim foo.lua

-- for easiest recreate; define some locals: 
`local vcmd, lsp, api, fn, set, g = vim.cmd, vim.lsp, vim.api, vim.fn, vim.opt, vim.g`

-- then alter to be:
`lcl vcmd, lsp, api, fn, set, g = vim.cmd, vim.lsp, vim.api, vim.fn, vim.opt, vim.`

-- show diagnostics for that line:
:lua vim.diagnostic.show_line_diagnostics({ border = 'rounded', show_header = false, focusable = false })

-- result is an out of order list of diagnostics:
![image](https://user-images.githubusercontent.com/3678/136457332-e60f6b9a-b8c8-434f-83c5-53b7ab2831d2.png)

### Expected behavior

Diagnostics in severity sorted order. (error being first)

### Actual behavior

Diagnostics in reverse severity sorted order. (error being last)

**Comment by gpanders** [comment]
Not that I'm aware of. But I'm in the process of adding some tests so that you don't need to test it manually :)
