### ISSUE TITLE
`vim.fn.getbufinfo({buflisted = 1})` reporting path with mixed (windows + unix) path separators

### ISSUE THREAD

**Issue by Neelfrost** [neovim/neovim#15966]
### Neovim version (nvim -v)

NVIM v0.5.1

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Windows 10, 1909

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

chocolatey 

### How to reproduce the issue

Create a session file using `:mksession` with 2-3 buffers.

nvim --clean
source <session_file>
lua verbose_print(vim.tbl_map(function(b) return b.name end, vim.fn.getbufinfo({buflisted=1})))

### Expected behavior

![image](https://user-images.githubusercontent.com/64243795/136590079-e4c8ea98-1f7f-4b83-8f39-353e23b5017e.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/64243795/136590327-6732983a-e0cd-4bdc-b7ba-cbe4575053c2.png)

**Comment by 3N4N** [comment]
Seems to have been fixed.  I am getting this output:
```
{ "E:\\projects\\dotfiles\\PowerShell\\Microsoft.PowerShell_profile.ps1", "E:\\projects\\dotfiles\\.gitconfig", "E:\\projects\\dotfiles\\.config\\nvim\\plugin\\user\\functions.vim", "E:\\projects\\dotfiles\\.config\\nvim\\plugin\\user\\options.vim", "E:\\projects\\dotfiles\\.config\\nvim\\lua\\user\\clipboard.lua", "E:\\projects\\dotfiles\\.config\\nvim\\init.vim" }
```

My system specs:
```
Neovim: v0.9.0
Terminal: Windows Terminal v1.18.1241.0
Shell: PowerShell 7
OS: Windows 11 Pro Version 22H2 Build 22621.1702
```
