### ISSUE TITLE
[RFC] Questions about neovim forked dependencies.

### ISSUE THREAD

**Issue by xu-cheng** [neovim/neovim#1597]
Recently, neovim adds more third-party dependencies. You can find them [here](https://github.com/neovim/neovim/blob/master/third-party/CMakeLists.txt#L73-L83). All of them are from neovim forked dependencies. Therefore, I have following questions:

* Is it necessary to have neovim forking these repo as it will add workload to sync them with upstream changes?
* The deps' urls are not versionized. So any changes in that branch will break the checksum, hence break the building.

/cc @tarruda

**Comment by justinmk** [comment]
We no longer fork. bot-ci mirrors the repos.
