### ISSUE TITLE
release 0.5: debian armhf fails in "autocmd TermClose reports the correct <abuf>" test

### ISSUE THREAD

**Issue by EvanCarroll** [neovim/neovim#15980]
### Feature description

Neovim is really close to getting included in Debian Testing. [They now have a tracker for the excuses why Neovim 0.5 isn't in Debian.](https://qa.debian.org/excuses.php?package=neovim). Let's track this on the Neovim board too.

In short there are two large issues, that seem like they could be fixed quick.

* get Neovim building on armel: https://buildd.debian.org/status/logs.php?arch=armel&pkg=neovim&ver=0.5.1-1
* get Neovim building on armhf: https://buildd.debian.org/status/logs.php?arch=armhf&pkg=neovim&ver=0.5.1-1

Both of these build failures are very likely caused by the same issue, which stops the build from completing and causes a hang in compilation.

----

The above is the overview on the package. Click the `Maybe-Failed` on that page to view the log, or find the links below,

* armel: https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=armel&ver=0.5.1-1&stamp=1633404513&raw=0
* armhf: https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=armhf&ver=0.5.1-1&stamp=1633404977&raw=0

**Comment by EvanCarroll** [comment]
@bfredl sure there is click the "Maybe-Failed" at the links above to see the logs.

* armel: https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=armel&ver=0.5.1-1&stamp=1633404513&raw=0
* armhf: https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=armhf&ver=0.5.1-1&stamp=1633404977&raw=0

**Comment by EvanCarroll** [comment]
My guess is that this is related to https://github.com/neovim/neovim/issues/15349

**Comment by justinmk** [comment]
> My guess is that this is related to #15349 which also targets termxx_spec.lua, and is described with the same text,

Yes. Do we need this issue then?

**Comment by jamessan** [comment]
> My guess is that this is related to #15349 which also targets termxx_spec.lua,

Which was filed by me -- the Debian maintainer of neovim and contributor to neovim.  I appreciate the concern, but if you see issues in a Debian package, it's generally better practice to interact with the Debian maintainer to avoid situations like this.
