### ISSUE TITLE
nvim `statusline` behaves weirdly with some characters

### ISSUE THREAD

**Issue by ndavd** [neovim/neovim#15993]
### Neovim version (nvim -v)

v0.6.0-dev+454-gee342d3ce

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

Arch Linux x86-64

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

nvim --clean
:let &l:stl='%=stl'
:set fillchars=stl:᠃,stlnc:᠃

### Expected behavior

it should display the statusline correctly. 
Like it does using Vim:
![image](https://user-images.githubusercontent.com/74260683/136834943-49300435-707d-4534-97b3-7cdc03d36c90.png)

### Actual behavior

It doesn't display it correctly:
![image](https://user-images.githubusercontent.com/74260683/136835035-f426ab3e-534c-47a4-bbde-ae6ca72e50fc.png)

**Comment by zeertzjq** [comment]
Seems to be [patch 8.2.2569](https://github.com/vim/vim/commit/008bff967f7fcaa6af066f71d65bfbba5ef5c7d3).

**Comment by zeertzjq** [comment]
Nvim also performs an extra cast.
