### ISSUE TITLE
Invalid argument: listchars=tab:»·,trail:·,nbsp:·

### ISSUE THREAD

**Issue by wouterw** [neovim/neovim#1601]
A `.nvimrc` file containing `set list listchars=tab:»·,trail:·,nbsp:·` throws the following error: 

```
Error detected while processing /Users/wouterw/.nvimrc:
line   71:
E474: Invalid argument: listchars=tab:»·,trail:·,nbsp:·
```

The full `vimrc` file can be found [here](https://github.com/thoughtbot/dotfiles/blob/master/vimrc#L71).

I've been using neovim with this `vimrc` file successfully for a few weeks now. I've `brew --reinstall --HEAD neovim` today which resulted in this error.

**Comment by Pyrohh** [comment]
@wouterw please try what was mentioned in #1858, assuming you're still experiencing this issue.

**Comment by wouterw** [comment]
@Pyrohh Thanks, this indeed fixes my issue. :+1:

**Comment by sullome** [comment]
Well, I have this error. #1858 not helped.
```
[13:46] ~ % nvim .config/nvim/init.vim 
Error detected while processing /home/none/.config/nvim/init.vim:
line   39:
E518: Unknown option:  
line   42:
E474: Invalid argument: listchars=trail:•,nbsp:≡,tab=>-
Press ENTER or type command to continue
[13:46] ~ % export LC_ALL=en_US.UTF-8    
[13:46] ~ % export LANG=en_US.UTF-8 
[13:46] ~ % nvim .config/nvim/init.vim 
Error detected while processing /home/none/.config/nvim/init.vim:
line   39:
E518: Unknown option:  
line   42:
E474: Invalid argument: listchars=trail:•,nbsp:≡,tab=>-
Press ENTER or type command to continue
```
Runned `:set encoding` with config file opened, answer was `encoding=utf-8`

**Comment by justinmk** [comment]
@sullome Try `tab:> ` instead of `tab=> `.

**Comment by sullome** [comment]
Oh. My bad. Don't how I missed this. Thanks, it worked!

**Comment by mseri** [comment]
Did not fix it for me on ubuntu. This works: `set listchars=trail:-,nbsp:+,eol:$`, however as soon as I add a `tab` it raises an error (e.g. the following does not worl `set listchars:trail:-,nbsp:+,eol:$`).

**Comment by justinmk** [comment]
Again, you have a syntax error. Issue tracker is not for usage questions.

**Comment by mseri** [comment]
It was inserted in the comment by mistake, sorry. The line in the `init.vim` has no syntax error.

**Comment by fwalch** [comment]
@mseri Are you using two characters for `tab` (see `:h lcs-tab`)?

**Comment by mseri** [comment]
Oh gosh, you are perfectly right. We should keep this issue as a reminder for all the people that have automatic trailing space deletion. Thanks!

**Comment by seadb** [comment]
It seems like if you have expandtab turned on, vim doesn't like you to set the tab listchar

**Comment by polvoazul** [comment]
Im having the same problem. It works fine on vim, but not on nvim:

```
set listchars=tab:»·,trail:·,extends:»
```

Error detected while processing ~/.vimrc: (i source my vimrc from init.vim)
line  112:
E474: Invalid argument: listchars=tab:<bb><b7>,trail:<b7>,extends:<bb>

This works, though: (justed subbed my utf8 chars to ascii)
```
set listchars=tab:aa,trail:a,extends:a
```
