### ISSUE TITLE
Joining lines 

### ISSUE THREAD

**Issue by alemuller** [neovim/neovim#16016]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+460-g6b9cb665f

### Vim (not Nvim) behaves the same?

no, vim 8.2.3441

### Operating system/version

Arch, Linux 5.10.37-1-lts x86_64

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

```
$ echo "%\n*" > foo
$ nvim --clean foo
:join
```

This is also reproducible pressing `ggJ` (`gg` not needed, used here to position the cursor).

### Expected behavior

Expected to both to be joined.

Buffer after opening
```
%
*
```

Expected text on buffer after `:join`
```
% *
```

### Actual behavior

Actual buffer content after `:join`
```
%
```

**Comment by zeertzjq** [comment]
Probably because `*` is treated as a comment leader. Neovim's `'formatoptions'` defaults to `tcqj` whereas VIm's defaults to `tcq`. If you run `:set formatoptions-=j` in Neovim then Neovim behave the same as Vim.

**Comment by zeertzjq** [comment]
This is [documented](https://github.com/neovim/neovim/blob/b63b4777ec80069e42326778023db30bd8217f1a/runtime/doc/vim_diff.txt#L42) in `vim_diff.txt`, so I think this is unlikely to be changed.
