### ISSUE TITLE
Neovim with Scoop, finding init.vim

### ISSUE THREAD

**Issue by Jay1** [neovim/neovim#16024]
Good morning guys, 

I have an issue locating my init.vim at the moment. 

Neovim is installed with "Scoop" on Windows10. 

First,
I searched in my Local folder, here: "C:\Users\admin\AppData\Local"
there is only an nvim-data folder: "C:\Users\admin\AppData\Local\**nvim-data**"

Then,
I thought of going maybe in Scoop installation folder and navigate the path
Here: "C:\Users\admin\scoop\apps\neovim\current\share\nvim\runtime"

However, there is still no init.vim file anywhere in there. I thought maybe searching init.vim in that upper folder structure. but it returned no result for this specific file. 

I'm not super experienced with Vim in general, I'm sorry if I missed something obvious here I don't want to waste your time. 

TIA

**Comment by gpanders** [comment]
Open Neovim and run `:echo stdpath('config')`. The directory that shows is where you should put your `init.vim` file. It does not exist until you create it.
