### ISSUE TITLE
SIGABRT double free or corruption (when using pmenu?)

### ISSUE THREAD

**Issue by rktjmp** [neovim/neovim#16037]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+460-g6b9cb665f

### Operating system/version

Linux

### Terminal name/version

Alacritty

### $TERM environment variable

tmux-256color

### Installation

Built from repo

### How to reproduce the issue

No really reliable way to recreate, but I have had *a* crash occur repeatedly through multiple build versions but I don't believe I can get a useful BT from those anymore since the executable has been replaced.

It always(?) occurs when the auto-completion/popup menu is open and providing completions (via nvim-cmp & nvim-compe) from an LSP source. I am not navigating the menu but it is updating as I type.

Attached is 2 near identical traces, and another separate backtrace that is different but seems to occur when using the pmenu/autocomplete so it may be related. As I said, I have had this happen a bit during the past weeks but hadn't looked at the dumps so I can't say if they would provide more data.

Similar/identical:

[2380.bt.txt](https://github.com/neovim/neovim/files/7356583/2380.bt.txt)
[311989.bt.txt](https://github.com/neovim/neovim/files/7356585/311989.bt.txt)

Possibly unrelated but occurs by the same actions:

[278494.bt.txt](https://github.com/neovim/neovim/files/7356584/278494.bt.txt)

This build isn't at HEAD (though it's only 2-3 days old) but figured I would post this before I rebuild in case other info was needed.

**Comment by muniter** [comment]
In this case cmp and compe are using their own implementation of a popup menu. And from a small look in the backtrace I can see the expected call sto the window API.

So the issue is not a bug with pop-up menu but with the window API perhaps.

**Comment by rktjmp** [comment]
Another one: [bt.txt](https://github.com/neovim/neovim/files/7356609/bt.txt) which I assume tells nothing new.

**Comment by rktjmp** [comment]
After reducing `cmp`'s max results, I haven't seen this in months. That or it got patched in subsequent builds.

Since I couldn't get a good repro, maybe it's fair to close this out? If it's a real issue it will appear again elsewhere otherwise it might even already be fixed?

**Comment by rktjmp** [comment]
Closing this, I haven't since and it's too un-actionable.
