### ISSUE TITLE
ftplugin files are not loaded when using `syntax on` before enabling nvim-treesitter.highlight module

### ISSUE THREAD

**Issue by YorickPeterse** [neovim/neovim#16059]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+416-g59edd377d

### Vim (not Nvim) behaves the same?

Not appliccable

### Operating system/version

Linux

### Terminal name/version

GNONE Terminal

### $TERM environment variable

xterm-256color

### Installation

Git

### How to reproduce the issue

1. Clone https://gitlab.com/yorickpeterse/nvim-treesitter-ftplugin-bug
2. `cd nvim-treesitter-ftplugin-bug`
3. `env XDG_CONFIG_HOME=$PWD nvim /tmp/test.lua`

### Expected behavior

An error is produced, as the ftplugin file contains an invalid command

### Actual behavior

No error is produced, because the `syntax on` line (the same happens when using `syntax enable`) seems to prevent the `ftplugin` file from running. Removing the line entirely results in the expected behaviour.

**Comment by YorickPeterse** [comment]
cc @bfredl as we talked about this on Matrix.

**Comment by lewis6991** [comment]
This looks stale. Closing.
