### ISSUE TITLE
typo in help of msgpack#strptime()

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#16051]
### Neovim version (nvim -v)

v0.6.0-dev+464-g1ced6cf08

### Vim (not Nvim) behaves the same?

None

### Operating system/version

None

### Terminal name/version

None

### $TERM environment variable

None

### Installation

None

### How to reproduce the issue

```
msgpack#strptime({format}, {time})			*msgpack#strptime()*
	Reverse of |msgpack#strptime()|: for any time and format 
	|msgpack#equal|( |msgpack#strptime|(format, |msgpack#strftime|(format, 
```
There is spelling mistake here.

### Expected behavior

None

### Actual behavior

None

**Comment by clason** [comment]
PR welcome!

**Comment by dundargoc** [comment]
What is the typo here? I don't speak vimscript.

**Comment by clason** [comment]
Should be "Reverse of |msgpack#str**f**time()|"

**Comment by dundargoc** [comment]
Fixed: https://github.com/neovim/neovim/pull/16361
