### ISSUE TITLE
Buffers created with nvim_create_buf which are not (yet) associated with windows should error when setting window-local options

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#16056]
### Feature already in Vim?

N/A

### Feature description

Consider an `ftplugin/foo.lua` file on the `runtimepath` which sets options for `foo` files, containing a line like:

```
vim.opt_local.wrap = true
```

Given some Lua code like:

```
local bufnr = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_option(bufnr, 'filetype', 'foo')
vim.cmd'split'
vim.cmd(string.format('buffer %d', bufnr))
print(vim.opt.wrap)
```

whose job it is to programmatically open a `foo` file, it is easy to set a `foo` filetype before actually putting the new buffer in a window -- which today silently does not set the window-local options, such as here, `wrap`.

Compare specifically what `set wrap?` shows if one moves the `vim.api.nvim_buf_set_option(bufnr, 'filetype', 'foo')` to be after the `buffer %d` line.

Ideally, the above should trigger a loud error when a window-local option is set but the buffer is not in a window.

An alternative would be to somehow have an API which handles both buffer and window creation and filetype setting in a more joint way, such that they're created in the right order sequentially (so perhaps #14315 is somehow related) and it's harder to make this mistake.

Or, a third alternative which avoids any functional changes would be instead to document (in `nvim_create_buf` I suppose) to be careful with setting filetypes on it before placing it in a window.

For a real-life version of this issue, see https://github.com/Julian/lean.nvim/commit/25b8fb3b8a9e3f2719f4e701878223e358895c48.

```terminal
⊙  nvim --version                                                                 julian@Airm ●
NVIM v0.6.0-dev+30af69509
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by julian@Airm.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-30af695/share/nvim"

Run :checkhealth for more info
```

**Comment by justinmk** [comment]
> An alternative would be to somehow have an API which handles both buffer and window creation and filetype setting in a more joint way, such that they're created in the right order sequentially (so perhaps #14315 is somehow related)

#14315 was implemented: #25550 but doesn't address your exact request.

> Or, a third alternative which avoids any functional changes would be instead to document (in `nvim_create_buf` I suppose) to be careful with setting filetypes on it before placing it in a window.

My sense is that this is the nature of having scope-relative options. It can be annoying to run into the mistake, but adding disclaimers in numerous docs for all the ways that a buffer can be created, won't help. There are tons of interacting parts, we can't list all the permutations. Plugin authors must be aware of how the system works.
