### ISSUE TITLE
Segfault in popupmnu.c

### ISSUE THREAD

**Issue by zidingz** [neovim/neovim#16069]
Hey there!

I belong to an open source security research community, and a member (@yifengchen-cc) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by vigoux** [comment]
Hi, if you have matrix, feel free to send me a pm for now, we are setting up the security advisories on github.

My matrix handle: `@vigoux:matrix.org`

**Comment by vigoux** [comment]
@zidingz we realized that this issue was not worth an actual CVE, and is just a regular NULL pointer deref (from what we saw), thus we are not going to raise the full blown security thing this time.

**Comment by dundargoc** [comment]
Security sensitive information can be forwarded with https://github.com/neovim/neovim/security/advisories/new. As there is no information here on how to recreate the NULL pointer I will close this.
