### ISSUE TITLE
LSP: Support workspace/didChangeWatchedFiles

### ISSUE THREAD

**Issue by simrat39** [neovim/neovim#16078]
### Feature already in Vim?

No

### Feature description

> The watched files notification is sent from the client to the server when the client detects changes to files and folders watched by the language client (note although the name suggest that only file events are sent it is about file system events which include folders as well). It is recommended that servers register for these file system events using the registration mechanism. In former implementations clients pushed file events without the server actively asking for it.

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_willRenameFiles

Used by omnisharp iirc, and maybe rust-analyzer.

Needs a filesystem watcher like libuv, watchman, chokidar...

**Comment by yueyingjuesha** [comment]
Note this lack of support also affect gopls auto reloading go.mod files
