### ISSUE TITLE
LSP: Support for file change requests/notifications (tracking issue)

### ISSUE THREAD

**Issue by simrat39** [neovim/neovim#16075]
### Feature already in Vim?

No

### Feature description

The LSP spec defines a few notifications which should be sent from the client to the server when a file is renamed/deleted/created/changed. This is then used by the server to do cool things like changing the imports and other stuff.

The workspace/didChangeWatchedFiles notification is to be sent when the filesystem changes, which can happen from outside of neovim, so we either need to use luv, or an external program like watchman to watch for file changes.

The did/will<whatever> notifications are to be sent when neovim(client) itself is going to create/rename/delete files on a user action / text edit, so this would need some more changes in those areas (nvim-tree, workspace edits)

The notifications:
- [ ] didCreate
- [ ] didRename
- [ ] didDelete

The methods:
- [ ] workspace/didChangeWatchedFiles
- [ ] willCreate
- [ ] willRename
- [ ] willDelete

**Comment by sumneko** [comment]
There are two filesystem related notifications in the LSP:
1. [workspace/didChangeWatchedFiles](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWatchedFiles): Watching filesystem changes, can happen from outside of client.
2. [file operations events](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_willCreateFiles): Only triggered from within the client either by a user action or by applying a workspace edit.
