### ISSUE TITLE
Feature Improvement: When recovering swap files, allow "Delete All", etc.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#1610]
For example, it currently looks like this:

```
Swap file "~/.vim/swap//%Users%josephpea%src%climate+legacy%applications%preso%insurance%bower_components%preso-common%src%js%layouts%base.js.swp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (D)elete it, (Q)uit, (A)bort: 
```

but sometimes, if vim crashes with like 50 files open, and you don't want to recover anything, you just want to get right back to work, then something like this would be nice:

```
[O]pen Read-Only, (E)dit anyway, (R)ecover, (D)elete it, (S)kip and delete all, (Q)uit, (A)bort
```

etc. Perhaps Recover all, Edit all anyway, Open all Read-Only, etc.

I currently have 70 buffers to make a selection for, which as you can imagine is annoying. I have 70 buffer because I loaded a session with 70 or so buffers. Most of the time my work is saved, so I just need to delete swap files and move on. Less often I might actually need to recover, so I like have the option to do so, but more often I'd just like to skip everything and get back to work.

**Comment by trusktr** [comment]
This is even more annoying lately, as there isn't even a `Delete All` option the last few crashes I've had. I have to make a selection for all files, and on top of that I have to manually delete the relevant swap files. It's definitely a pain point. 

The `*All` options for delete, recover, etc, should perhaps only be present when sourcing a file, and the chosen selection applies only until that file (or buffer, etc) is done being sourced.

**Comment by justinmk** [comment]
> This is even more annoying lately, as there isn't even a Delete All

I assume you mean just "Delete". I noticed it too, it is annoying. Not related to this issue though.

**Comment by trusktr** [comment]
Oops, yeah, just "Delete", but my imagination was still wishing for this feature. :laughing:

**Comment by wolfv6** [comment]
Thumbs up for the changes proposed by @matjon and @tpz ![thumbs up](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
I don't use neovim, but file recovery is one of the vim pain points that would make me switch to neovim.

**Comment by justinmk** [comment]
Merging with https://github.com/neovim/neovim/issues/5086.
