### ISSUE TITLE
neovim (& vim) toxic file causes crash w/ 100% CPU

### ISSUE THREAD

**Issue by jwhitley** [neovim/neovim#1611]
### Repro steps
1.  [From this gist](https://gist.github.com/jwhitley/080d53d3e6a83ce8fe61), download the files `killvimrc` and `longline.rb`.
2.  Run neovim with `nvim -u killvimrc longline.rb`.  This issue also appears in vim upstream via `vim -u killvimrc longline.rb`.
### Actual results

`nvim` locks up at 100% CPU utilization and must be killed with `kill -9 ...`
### Expected results

File loads and is editable.
### Notes

Reproduced with neovim 45ae6eadfd3184b860ac19bd2661e1338c4efc89 and vim 7.4.488.

This issue appears to be tied to the vim ruby syntax file.  Removing the line `syntax on` from `killvimrc` allows the file to load, as does renaming `longline.rb` to `longline.txt`.  As expected, loading the file as a .txt file and running `:set ft=ruby` will trigger the lockup.

**Comment by justinmk** [comment]
AFAICT for ruby specifically this was addressed by a runtime update, https://github.com/vim/vim/issues/274 .

Syntax performance in general is covered by https://github.com/neovim/neovim/issues/4736
