### ISSUE TITLE
autocomplete: fuzzy match, trigger (also in cmdline)

### ISSUE THREAD

**Issue by purpleP** [neovim/neovim#16142]
### Feature already in Vim?

No

### Feature description

I would [still](https://github.com/neovim/neovim/issues/5604) like to have fuzzy as you type completions in command mode so that one wouldn’t need to resort to plugins like fzf, telescope etc etc.

**Comment by 4513ECHO** [comment]
Now, original vim has support of fuzzy completion on cmdline. It will resolve this issue.

ref: https://github.com/vim/vim/commit/38b85cb4d7216705058708bacbc25ab90cd61595

**Comment by zeertzjq** [comment]
That one is still manual completion, not autocompletion.

**Comment by justinmk** [comment]
> I would guess that deciding when to show a completion is the only thing missing in the core to make it into “as you type”.

@purpleP this is a good callout. That seems very useful to have in core.

**Comment by costincaraivan** [comment]
> @purpleP Let me be very clear here: there are currently zero plans for having builtin autocompletion, and even less so for the commandline. Furthermore, "offloading more and more responsibilities to plugins" is very much by design and has served us well so far. If you are not happy with the fundamental goals of this project, you are welcome to look at other editors; maybe https://github.com/helix-editor/helix suits you better.

@clason 

Priorities do get revisited, though, as the world around us changes.

And for many other ecosystems I've seen, if there is a plugin system and there are many plugins doing the same thing, some of the functionality in those most popular plugins does get dragged into the core system.

Fuzzy file search, at least, for the existing vim-derived command line primitives would make neovim a lot more usable out of the box.

**Comment by clason** [comment]
> Priorities do get revisited, though, as the world around us changes.

And yet these priorities haven't changed in the meantime.

**Comment by justinmk** [comment]
> I would guess that deciding when to show a completion is the only thing missing in the core to make it into “as you type”.

@purpleP this is a good callout. Seems very useful to have in core.

# Status

`:help fuzzy-matching` is part of core now. Remaining work is tracked here:

- https://github.com/neovim/neovim/issues/12428
- https://github.com/neovim/neovim/issues/16488
- https://github.com/neovim/neovim/issues/25670
- https://github.com/neovim/neovim/issues/12620

Topics covered in this issue:

1. As-you-type is _autocompletion_ (as opposed to mere "completion"). We want to have strong primitives for building autocomplete solutions:
    - Function that decides _when to trigger autocomplete_ (based on buffer text + cursor position)
    - Anything else...?
2. "fuzzy" matching / completion:
    - https://github.com/neovim/neovim/pull/13854
    - https://github.com/neovim/neovim/pull/12995
3. cmdline (command line) mode
    - CursorMovedC was added in https://github.com/neovim/neovim/pull/29436

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open an issue if you have new information/topics to discuss._
