### ISSUE TITLE
Synchronous Scrolling without 'scrollbind' set

### ISSUE THREAD

**Issue by FlyingWaffleDev** [neovim/neovim#16144]
### Neovim version (nvim -v)

0.5.0 0.5.1

### Vim (not Nvim) behaves the same?

no, 8.2.3428

### Operating system/version

Gentoo Linux 2.8 , Kernel 5.10.75

### Terminal name/version

konsole/yakuake 21.08.2

### $TERM environment variable

xterm-256color

### Installation

Compiled via portage/emerge

### How to reproduce the issue

nvim --clean
:e ANY_LARGE_TEXT_FILE
:vs ANY_LARGE_TEXT_FILE
use any scrolling method to reach the top/bottom of the screen
keep scrolling

### Expected behavior

Only the currently selected buffer scrolls its file.

### Actual behavior

Once the edge of the visible buffer is reached, both open buffers start scrolling synchronously (accompanied by rendering artifacts and missing chunks of the file in the non-selected buffer).

I checked with ":windo verbose set", nothing there is causing this.

Might be related to [Issue 15692](https://github.com/neovim/neovim/issues/15692)

**Comment by zeertzjq** [comment]
May be fixed by #16239.

**Comment by zeertzjq** [comment]
I can reproducing this after installing ncurses 6.3.

**Comment by apodkowa2112** [comment]
I know this is an old ticket, but I seem to be having this issue when using this version in Windows using mintty 3.8.2 (bundled with Git Bash):
```
NVIM v0.12.2
Build type: Release
LuaJIT 2.1.1774638290      
```

I installed nvim using `winget`, and the `$TERM=xterm`.

For more context:
```
$ bash --version
GNU bash, version 5.3.9(1)-release (x86_64-pc-cygwin)
Copyright (C) 2025 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

```
$ git --version
git version 2.54.0.windows.1
```

Curiously, running from cmd or powershell terminal works fine. In those terminal sessions, running `echo $TERM` returns the empty string, and not `xterm` like launching when launching Git Bash directly.

This is probably an integration issue with MinTTY, which I'm sure is outdated compared to anything Linux native. As a citizen of both OS's, this is a pain point for me, and likely for other would be neovim users forced by circumstance to develop on Windows.

Please let me know if there is anything I can do to help debug this issue further.
