### ISSUE TITLE
Alt-key in cmd prompt inside neovim terminal clears the line and enters that key

### ISSUE THREAD

**Issue by 3N4N** [neovim/neovim#16202]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

Don't know. Don't have it installed.

### Operating system/version

Windows 10 21H2

### Terminal name/version

Command prompt

### $TERM environment variable

Nil

### Installation

Release build from repo

### How to reproduce the issue

```
nvim --clean
:te
random keystrokes <alt-b>
```

### Expected behavior

I have clink installed, so I expect the cursor to go back one word. But, to retrace my steps with reproduction, I have also checked with clink disabled, which would result in a `b` being inserted, but the bug still exists, that is, the whole line is deleted and a single `b` is inserted.

### Actual behavior

The whole line is deleted and only a `b` is left. Here `b` is a stand-in for any key pressed with `Alt`.

**Comment by zeertzjq** [comment]
Does running `clink.exe inject` in Nvim `:terminal` make it work?

**Comment by 3N4N** [comment]
@zeertzjq, nvim won't load it, yes, but I have clink injection turned on as an autoload with cmd. So doesn't matter where I start cmd from, it will inject clink.

But that's not the issue. I have checked with *and* without clink. The alt-key behaviour is buggy either way.

**Comment by erw7** [comment]
This is not a noemvim problem. You can easily confirm this by doing the same thing before launching neovim. Windows Terminal works with `alt-b`, so it is better to use Windows Terminal.

**Comment by 3N4N** [comment]
I have no way to reopen this. Tagging the first person that comes when pressed @seandewar for communication.

erw7, I am not saying I want the cursor to go back one word. I just noted that since I'm using clink, it *should* go back one word. But for the sake of minimal reproducibility, I'm excluding the matter of clink entirely.

In command prompt, when you press `alt-b`, it doesn't clear the whole line. But neovim terminal cmd does. That's what the bug is. Why would you close an issue without waiting for an answer?

**Comment by zeertzjq** [comment]
> Here b is a stand-in for any key pressed with Alt.
Do you mean any ALT- chord clears the line?

**Comment by zeertzjq** [comment]
If that is, I know what is the problem. It may have already been fixed by #16222 on master.

**Comment by zeertzjq** [comment]
You can download the nightly build and check if the bug still exists.

**Comment by 3N4N** [comment]
@zeertzjq, you're right. And thank you so much. Switching from Linux bash to Windows cmd broke my workflow. Now I can work better.

**Comment by 3N4N** [comment]
@zeertzjq, I have a separate question. It's not a bug so I didn't want to open an issue.

I was trying to build neovim for Windows with MSVC and after building the dependencies, it gave this error:
```
Could NOT find LibUV (missing: LIBUV_LIBRARY LIBUV_INCLUDE_DIR)
```

I tried with MSYS as well, and although it could find LibUV, it errored on another library. I think MSYS didn't error on LibUV is because it's already installed with pacman.

I think the `.\ci\build.ps1` script is not using the bundled dependencies for some reason, even though it downloads and builds them in a folder. Any idea how I could turn it on? Maybe it's not finding the directory for some reason.

**Comment by zeertzjq** [comment]
Well, I don't know much about this. I think that `build.ps1` may be only for building Nvim in GitHub CI and may not be very user-friendly, and it is only listed for reference in the wiki.

**Comment by 3N4N** [comment]
Might be. Doesn't matter. I found [this walkthrough](https://gist.github.com/equalsraf/6cc26951981fa254b53a80cf73eaf47d) for MSYS, which worked well. I think the wiki should add a link to it. The current wiki entry is too old.

**Comment by clason** [comment]
If it still works, and the current instructions don't, we should edit the Wiki with this information. (A link is not enough since Gists can disappear.)

Anyone can edit the Wiki, and it would be better if someone (you?) did it who is actually using Neovim on MSYS.

**Comment by 3N4N** [comment]
I'll edit the wiki, then. First I'll try and build it with MSVC. Should be the same approach. Then add a comprehensive enough entry in the wiki.

**Comment by 3N4N** [comment]
@clason, the MSYS build steps were already in the wiki, but they were in the end instead of the "Build for Windows" section. I moved it. Should be easier to find now.
