### ISSUE TITLE
lsp: do not sanitize capabilities

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#16200]
When the server returns capabilities, it passes the response to [vim.lsp.protocol.resolve_capabilities()](https://github.com/smolck/neovim/blob/ad5e301ea3ac22fb11949263d016e8e2fcaabff0/runtime/lua/vim/lsp/protocol.lua#L971-L1132). This function sanitizes the capability name by:

* flattening the internal list
* sanitizing the capability names (renaming, snake_case instead of camelCase)

This makes adding a new capability a chore, as you need to internally add the handling to the resolve_capabilities function. We can shift the burden of checking the capability to the calling sites and instead store the resolved capabilities with the same structure as the response from the server.

I've said this a couple times, but documenting here 1) to milestone and 2) for discussion if someone has a compelling reason we should continue doing what we're doing.

**Comment by przepompownia** [comment]
I used `client.resolved_capabilities` to disable some capabilities from servers that cannot do it in another way. The same effect can be achieved by overriding `client.server_capabilities` so this change did not turn out to be sad news.
