### ISSUE TITLE
Automatically open folds when passing a CLI jump

### ISSUE THREAD

**Issue by xeruf** [neovim/neovim#16209]
### Neovim version (nvim -v)

NVIM v0.5.1 Build type: Release LuaJIT 2.0.5 Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.1/build/config -I/build/neovim/src/neovim-0.5.1/src -I/usr/include -I/build/neovim/src/neovim-0.5.1/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.1/build/include Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Arch

### Terminal name/version

-

### $TERM environment variable

-

### Installation

Pacman

### How to reproduce the issue

Will add clean instructions after acknowledgement, currently time-pressed.

These are my folding settings:
```vim
set foldmethod=marker
set foldopen+=jump
```

Normally, when opening a file, the line under the cursor is unfolded.
However, when starting with `nvim +n` (n being a line in another fold than the one it would land on by default) it stays with the old fold.

### Expected behavior

The fold the cursor is in unfolded so the line under the cursor is visible.

### Actual behavior

The line the cursor would be one without CLI args is unfolded to visibility.

**Comment by muniter** [comment]
You can always append `+"normal! zo` to make sure it opens.

**Comment by xeruf** [comment]
> You can always append `+"normal! zo"` to make sure it opens.

I know (actually `zx`), but from what I understand this should be automatic.

**Comment by xeruf** [comment]
Running with `'+normal! ${line}gg'` shows the same issue, even though executing `Ngg` after startup behaves correctly.
I suspect the configuration is loaded afterwards.

**Comment by zeertzjq** [comment]
The source code suggests that jumping only opens folds if you performed the jump using keys typed from the keyboard:
<https://github.com/neovim/neovim/blob/ed2573b7e121fe8b9b6b70a16cdb3b2a8bc4dbd3/src/nvim/normal.c#L7799-L7801>

**Comment by zeertzjq** [comment]
This seems to be intentional. I think you should open a feature request to Vim.

**Comment by xeruf** [comment]
So Neovim will only fix this once vim fixes it? Why?

**Comment by chrisbra** [comment]
> Vim also has this behavior.

This is mentioned in the [documentation briefly](https://vimhelp.org/options.txt.html#%27foldopen%27):

>         NOTE: When the command is part of a mapping this option is not used.
>         Add the zv command to the mapping to get the same effect.
>         (rationale: the mapping may want to control opening folds itself)

**Comment by zeertzjq** [comment]
Oh, I didn't see those lines in documentation. Then this should be wontfix.

**Comment by zeertzjq** [comment]
> So Neovim will only fix this once vim fixes it? Why?

This is not a bug. This is documented behavior.

**Comment by zeertzjq** [comment]
You can also achieve this by defining a custom command. For create `~/.config/nvim/plugin/G.vim`:
```vim
command! -range G call feedkeys("<line2>" .. 'G', 'tx')
```

And you can go to line 10 and open folds by using `+10G` instead of `+10` on the CLI.
