### ISSUE TITLE
TUI/xterm: scrolling in one window scrolls the other (broken again with ncurses 6.3)

### ISSUE THREAD

**Issue by heftig** [neovim/neovim#16238]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

no, vim 8.2.3441

### Operating system/version

Arch Linux

### Terminal name/version

VTE 0.66.0, ncurses 6.3

### $TERM environment variable

xterm-256color

### Installation

system package manager

### How to reproduce the issue

```
nvim --clean
:r!seq 300
gg
:vs
<C-f>
```

### Expected behavior

Only the left window scrolls.

### Actual behavior

The entire screen scrolls and is not redrawn properly.

**Comment by heftig** [comment]
This is similar to https://github.com/neovim/neovim/issues/10562, which was fixed before, but is broken again after upgrading to ncurses 6.3.

I bisected this to https://github.com/mirror/ncurses/commit/f6b436c4fb50275df43ea10ba9c744fe195a327d.

I believe the problem is that `smglp` and `smgrp` are added for xterm, but like `smglr` they're not implemented by VTE. The hack at https://github.com/neovim/neovim/blob/5ce35abae6427dac7ac2b147bae8f16adcd8ddff/src/nvim/tui/tui.c#L1661-L1665 needs to be extended to unset `unibi_set_left_margin_parm` and `unibi_set_right_margin_parm` as well.

**Comment by heftig** [comment]
Also see https://gitlab.gnome.org/GNOME/vte/-/issues/2526.

**Comment by zeertzjq** [comment]
Similar to #16144. However that issue is in Konsole, which is not VTE-based.

**Comment by Iron-E** [comment]
I just rebuilt Neovim and it is still happening for me

**Comment by zeertzjq** [comment]
> I just rebuilt Neovim and it is still happening for me. Using `v0.6.0-dev+555-gf26b39131` on lxterminal 0.4.0.

That's not the latest commit.

**Comment by Iron-E** [comment]
Yup. It was my build script. Ayay… sorry for the trouble

**Comment by Xyhlon** [comment]
So the only solutions are either to upgrade neovim to an unstable version or fix the issue on a local branch of the stable version. What should I do if I want to keep using the pacman maintained version of neovim currently 5.1.

**Comment by zeertzjq** [comment]
> So the only solutions are either to upgrade neovim to an unstable version or fix the issue on a local branch of the stable version. What should I do if I want to keep using the pacman maintained version of neovim currently 5.1.

pacman maintained version?

**Comment by egmontkob** [comment]
> I believe the problem is that `smglp` and `smgrp` are added for xterm, but like `smglr` they're not implemented by VTE.
> 
> Also see https://gitlab.gnome.org/GNOME/vte/-/issues/2526.

FYI: Better late than never, VTE's development version received left+right margin support today.
