### ISSUE TITLE
healthcheck for tmux RGB capabilities can be misleading

### ISSUE THREAD

**Issue by christianfosli** [neovim/neovim#16237]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

no, 8.2.3568

### Operating system/version

Fedora Linux 35

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

tmux-256color

### Installation

system package manager

### How to reproduce the issue

* Have tmux 3.2 or newer installed

* Enable RGB color in tmux using terminal-features (new in tmux 3.2). [Ref tmux wiki - how do I use rgb-colour](https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour)

  ```
  cat << EOF > ~/.config/tmux/tmux.conf
  set -as terminal-features ",*:RGB" # <-- this is the important line
  set -g default-terminal "tmux-256color"
  set -sg escape-time 10
  set -g focus-events on
  EOF
  ```

* Open tmux

  ```
  tmux
  ```

* Check health in neovim

  ```
  nvim --clean -c checkhealth
  ```

### Expected behavior

```
## tmux
  - OK: escape-time: 10
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color
```

### Actual behavior

```
## tmux
  - OK: escape-time: 10
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'
```

---

Note:

* My terminal does in fact have RGB capabilities working
* `termguicolors` does in fact work properly, as far as I can tell, so it's just the warning that is misleading.

**Comment by christianfosli** [comment]
Not 100% sure this is considered a bug, since neovim works fine. But it can be misleading and cause users to spend time fiddling with their tmux conf when it's actually okay.

A fix could be to use `tmux display -p '#{client_termfeatures}'` to check if Tc/RGB is enabled, like suggested in https://github.com/tmux/tmux/issues/2892

It only works on new tmux versions though, so I guess it's needed to check this in addition to `tmux server-info` like we do now.

**Comment by venthur** [comment]
Stumbled about this today as well. Maybe a more sophisticated check is needed here.
