### ISSUE TITLE
"make test" fails

### ISSUE THREAD

**Issue by shlomif** [neovim/neovim#16233]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+555-gf26b39131

### Vim (not Nvim) behaves the same?

irrelevant

### Operating system/version

fedora 34 x86-64

### Terminal name/version

Konsole 21.08.0

### $TERM environment variable

screen

### Installation

build from repo

### How to reproduce the issue

```
    make distclean
    make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$HOME/apps/neovim"
    make test
```

### Expected behavior

Tests pass.

### Actual behavior

Failure:

```
stack traceback:
        test/functional/helpers.lua:400: in function 'retry'
        test/functional/legacy/memory_usage_spec.lua:48: in function 'op'
        test/functional/legacy/memory_usage_spec.lua:77: in function 'monitor_memory_usage'
        test/functional/legacy/memory_usage_spec.lua:186: in function <test/functional/legacy/memory_usage_spec.lua:170>


 20 SKIPPED TESTS
 1 FAILED TEST
-- Tests exited non-zero: 1
-- Output to stderr:
ERROR 2021-11-04T07:08:37.781 60419 open_log_file:211: Logging to stderr, failed to open $NVIM_LOG_FILE: Xtest-startup-xdg-logpath/nvim/log
DEBUG 2021-11-04T07:08:37.781 60419 read_cb:118: closing Stream (0x16dbd10): EOF (end of file)
ERROR 2021-11-04T07:08:37.781 60419 open_log_file:211: Logging to stderr, failed to open $NVIM_LOG_FILE: Xtest-startup-xdg-logpath/nvim/log
DEBUG 2021-11-04T07:08:37.781 60419 stream_close:107: closing Stream: 0x16dbd10
ERROR 2021-11-04T07:08:37.781 60419 open_log_file:211: Logging to stderr, failed to open $NVIM_LOG_FILE: Xtest-startup-xdg-logpath/nvim/log
DEBUG 2021-11-04T07:08:37.781 60419 stream_close:107: closing Stream: 0x16dbeb0
ERROR 2021-11-04T07:08:37.781 60419 open_log_file:211: Logging to stderr, failed to open $NVIM_LOG_FILE: Xtest-startup-xdg-logpath/nvim/log
INFO  2021-11-04T07:08:37.781 60419 call_set_error:615: RPC: ch 1 was closed by the client
ERROR 2021-11-04T07:08:37.781 60419 open_log_file:211: Logging to stderr, failed to open $NVIM_LOG_FILE: Xtest-startup-xdg-logpath/nvim/log
INFO  2021-11-04T07:08:37.782 60419 os_exit:571: Nvim exit: 0

CMake Error at /home/shlomif/Download/unpack/file/vim/neovim/cmake/RunTests.cmake:94 (message):
  functional tests failed with error: 1


FAILED: CMakeFiles/functionaltest 
cd /home/shlomif/Download/unpack/file/vim/neovim/build && /usr/bin/cmake -DBUSTED_PRG=/home/shlomif/Download/unpack/file/vim/neovim/.deps/usr/bin/busted -DLUA_PRG=/home/shlomif/Download/unpack/file/vim/neovim/.deps/usr/bin/luajit -DNVIM_PRG=/home/shlomif/Download/unpack/file/vim/neovim/build/bin/nvim -DWORKING_DIR=/home/shlomif/Download/unpack/file/vim/neovim -DBUSTED_OUTPUT_TYPE=nvim -DTEST_DIR=/home/shlomif/Download/unpack/file/vim/neovim/test -DBUILD_DIR=/home/shlomif/Download/unpack/file/vim/neovim/build -DTEST_TYPE=functional -P /home/shlomif/Download/unpack/file/vim/neovim/cmake/RunTests.cmake
ninja: build stopped: subcommand failed.
make: *** [Makefile:144: functionaltest] Error 1
shlomif[neovim]:$base$ which nvim
/home/shlomif/apps/neovim/bin/nvim
shlomif[neovim]:$base$ nvim
shlomif[neovim]:$base$ nvim -v
NVIM v0.6.0-dev+555-gf26b39131
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by shlomif@telaviv1.shlomifish.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/shlomif/apps/neovim/share/nvim"

Run :checkhealth for more info
shlomif[neovim]:$base$ uname -a
Linux telaviv1.shlomifish.org 5.14.14-200.fc34.x86_64 #1 SMP Wed Oct 20 16:15:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
shlomif[neovim]:$base$ echo $TERM
screen
shlomif[neovim]:$base$ 

```

**Comment by zeertzjq** [comment]
Did you paste the full failure? What's before `stack traceback`?

**Comment by shlomif** [comment]
> Did you paste the full failure? What's before `stack traceback`?

Hi @zeertzjq ! I pasted a konsole screen capture. How do I generate a file with the full failure and complete tests' log? where is it documented?

**Comment by zeertzjq** [comment]
Why not just redirect it to a file?
```
make test >test.log 2>&1
```

**Comment by shlomif** [comment]
@zeertzjq : fair enough. doing it now.

**Comment by zeertzjq** [comment]
Oh, you make need to replace `make test` with `make functionaltest`. I'm not sure whether oldtests can be redirected.

**Comment by zeertzjq** [comment]
Wait, I just realized redirecting will cause some tests to fail.

**Comment by shlomif** [comment]
> @shlomif Wait, I just realized redirecting will cause some tests to fail.
> 
> You are running `screen` inside Konsole which can cause problem with scrolling. You can run Konsole without `screen` using some command like `konsole -e bash`.

1. I am using tmux rather than `screen`.
2. What should I do top-to-bottom to help you?

**Comment by shlomif** [comment]
[nvim-make-functest.txt](https://github.com/neovim/neovim/files/7472973/nvim-make-functest.txt)
[nvim-make-test.txt](https://github.com/neovim/neovim/files/7472974/nvim-make-test.txt)

The redirected "make *test" outputs

**Comment by zeertzjq** [comment]
> > @shlomif Wait, I just realized redirecting will cause some tests to fail.
> > You are running `screen` inside Konsole which can cause problem with scrolling. You can run Konsole without `screen` using some command like `konsole -e bash`.
> 
>     1. I am using tmux rather than `screen`.
> 
>     2. What should I do top-to-bottom to help you?

Oh, there is no need for you to do more.

**Comment by zeertzjq** [comment]
Oh, there is no need for you to do that.

**Comment by shlomif** [comment]
> Oh, then there is no need for you to do that.

OK. thanks!

**Comment by zeertzjq** [comment]
These tests are slow and have a timeout, so one possibility is that they are timing out.

**Comment by shlomif** [comment]
[nvim-make-functest.txt](https://github.com/neovim/neovim/files/7492110/nvim-make-functest.txt)
`make functionaltest ` output after `export TEST_TIMEOUT=100000`. @zeertzjq

**Comment by zeertzjq** [comment]
Well, I mean a hard-coded timeout. I don't really know much about those tests.

**Comment by justinmk** [comment]
`test/functional/legacy/memory_usage_spec.lua` is pretty flaky and system-dependent, but it was also changed since this issue was reported. cc62f3d6cb63 72652cbc46f5
