### ISSUE TITLE
LSP doesn't attach pyright client to the py-buffer

### ISSUE THREAD

**Issue by d9d6ka** [neovim/neovim#16235]
### Neovim version (nvim -v)

0.5.1

### Language server name/version

pyright 1.1.184

### Operating system/version

Windows 10/11

### :checkhealth

```markdown
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyright: configuration checked.
```

### Steps to reproduce using "nvim -u minimal_init.lua"

The provided minimal_init.lua works as expected. `:LspInfo` reports 1 client attached.

### Expected behavior

Client attached on `py`-file opening.

### Actual behavior

`:LspInfo` reports 0 clients attached. Also, nothing is written to the log.

I've attached the `ZIP`-file with my `init.vim`.

[init.zip](https://github.com/neovim/neovim/files/7474267/init.zip)

### Log file

https://gist.github.com/d9d6ka/91e754ecb6ccceba8f9182e361fe88de

**Comment by mjlbach** [comment]
Not enough info, doesn't follow the issue template, not a feature implemented in neovim.

You can ask on our discourse, this feature (autoattach) is implemented in lspconfig.
