### ISSUE TITLE
Calling range function through command makes the cursor jump to top

### ISSUE THREAD

**Issue by michaelb** [neovim/neovim#16244]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

yes, Vim v8.2.3441

### Operating system/version

Archlinux- based (Garuda)

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

system package manager

### How to reproduce the issue

nvim --clean

(insert some characters and some new line, and position yourself somewhere not on the first line)

declare the following (everything may not be necessary but I haven't been able to find out what triggers the issue):

```
:function! T(...) range 
    echo a:firstline
    echo a:lastline
    endfunction
 
 : command! -range -nargs=? TTTT <line1>,<line2> call T(<q-args>)

:%TTTT
```

I'm a plugin developper and this issue has been signaled to me by an user, so at least two people with different setup were able to reproduce

### Expected behavior

The output:
1
11

(or similar depending on the actual number of lines) is observed in the command area, without any additionnal side effect

### Actual behavior

The expected output is there, but the cursor has jumped to the top of the file

**Comment by jamessan** [comment]
Isn't this what's described in `:help :call`?

> When a range is given the cursor is
		positioned at the start of the first line before executing the
		function.

**Comment by michaelb** [comment]
You're right! I hadn't thought about looking up the `call` documentation (I've probably made a typo in my first tests and wrongly assumed it only happened when executed from a command)

I'll close this issue in a few moments
