### ISSUE TITLE
lsp: rust analyzer panicks with "bad range" if syntax enable explicitly set

### ISSUE THREAD

**Issue by yshui** [neovim/neovim#16249]
### Description

Seems like extending a source file beyond its original length causes rust_analyzer to panic when trying to get completion

### Neovim version

```
NVIM v0.6.0-dev+557-g5ce35abae
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -march=native -mtune=native -O2 -pipe -fcommon -U_FORTIFY_SOURCE -fno-semantic-interposition -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-git/src/build/config -I/build/neovim-git/src/neovim-git/src -I/usr/include -I/build/neovim-git/src/build/src/nvim/auto -I/build/neovim-git/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Nvim-lspconfig version

6224c54a9945a52bf43a8bc1a42a112084590c0b

### Affected language servers

rust_analyzer

### Steps to reproduce

1. Create a rust file
2. Add content to it
3. Attempt completion at a position beyond its original length

### Actual behavior

rust_analyzer panics.

Comparing the behavior a minimal config had and my config had, for some reason when using my config, no `didChange` notification is sent to the server.

### Minimal config

I was unable to reproduce this on a minimal config.

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: ccls: configuration checked.
  - INFO: rust_analyzer: configuration checked.

### LSP log

https://gist.github.com/yshui/02b430e836889182d01529e3c9ea1b83

**Comment by mjlbach** [comment]
Can you test #16252

**Comment by yshui** [comment]
Hi, I am not working with non-ascii, or using rust-tools.

I tested #16252 but it didn't fix this problem.

**Comment by yshui** [comment]
OK, I managed to make a minimal config. And things got weirder, I had to do `syntax enable` in `init.vim`, if I `vim.cmd[[syntax enable]]` this bug doesn't happen.

**Comment by yshui** [comment]
minimal_init.lua: (almost unchanged besides adding rust-analyzer)

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'rust_analyzer'
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

init.vim:

```vim
lua require'minimal_init'
syntax enable
```

Run: `nvim -u init.vim file`

Rust file I used for testing:

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        let result = 2 + 2;
        assert_eq!(result, 4);
    }
}
fn main() {

}
```

(This need to be in a cargo project), I inserted a bunch of whitespaces in `main`, and then `<C-x><C-o>`.

**Comment by mjlbach** [comment]
Thanks for the repro, I'll look into it and hopefully will have it sorted before 0.6 is released this month :)

**Comment by mjlbach** [comment]
Also I forgot to mention but you don't need to/shouldn't call `syntax on/enable` anymore with neovim. It's already on by default and retriggers a bunch of internal state. The only thing I'll fix relevant to this issue is trying to short-circuit those calls when the built-in client is enabled/provide a healthcheck that warns you if you are using them.

**Comment by yshui** [comment]
yeah I understand `syntax on` is no needed anymore. but I am curious what's the underlying mechanism that caused this problem, and if that means there's some deeper problem in neovim.

**Comment by jamessan** [comment]
> Also I forgot to mention but you don't need to/shouldn't call `syntax on/enable` anymore with neovim. It's already on by default and retriggers a bunch of internal state.

IMO, this statement means Nvim is buggy.  We _used_ to only trigger this after handling the user's init.vim, which avoided any duplicated effort.  Either way, having `syntax on` in the init.vim shouldn't cause things to misbehave.  It's not uncommon to have shared config between Vim and Nvim.

**Comment by mjlbach** [comment]
> IMO, this statement means Nvim is buggy. 

In https://github.com/neovim/neovim/pull/14361 it was changed to syntax enable. I'm pretty sure this and #16297 are duplicates, or at least share a common cause.

I think triggering `syntax` on breaks lspconfig's mapped autocommands, it's these lines that are the issue:

```
 filetype on
 doautoall filetypedetect BufRead
```

**Comment by gpanders** [comment]
> Maybe pertinent, in #14361 it was changed to syntax enable. 

Since https://github.com/neovim/neovim/pull/15207 `syntax on` and `syntax enable` are synonymous.

**Comment by mjlbach** [comment]
> Since #15207 syntax on and syntax enable are synonymous

Thanks, I was looking for that one :)

**Comment by bfredl** [comment]
for the record `syntax on` in a startup file sets a flag, so that the automatic invocation of `syntax on` after startup files is disabled, so there should be no retriggering. It should behave more or less the same as vim.The only think that neovim preloads before init files are the syncolor definitions (so you have a bunch of `:hi` definitions not already present in vim), not anything regarding autocmds and logic.

**Comment by mjlbach** [comment]
Here's a more minimal reproduction (sans lspconfig)

```
vim.lsp.set_log_level("debug")

function Start()
  local client_id = vim.lsp.start_client({ cmd = { "rust-analyzer" } })
  vim.lsp.buf_attach_client(vim.api.nvim_get_current_buf(), client_id)
  vim.api.nvim_buf_set_option(0, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
end

vim.cmd [[autocmd FileType rust unsilent lua Start()]]

vim.cmd[[
 filetype on
 doautoall filetypedetect BufRead
]]
```

```
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        let result = 2 + 2;
        assert_eq!(result, 4);
    }
}
fn main() {

}
```

**Comment by mjlbach** [comment]
Please test https://github.com/neovim/neovim/pull/16723

**Comment by yshui** [comment]
Works for me :+1: :rocket:
