### ISSUE TITLE
Null pointer exception - diagnostics

### ISSUE THREAD

**Issue by marcinmaciukiewicz** [neovim/neovim#16240]
https://github.com/neovim/neovim/blob/3ba800f1538e083f8172655c6bab096cd604a0b5/runtime/lua/vim/lsp/diagnostic.lua#L149

The last change caused null pointer exception - if the client can't be found by ID the client variable is null and in consequence next line fail. Safer approach will be to use default client name if it can't be found. Previous implementation used default client name only concatenated with the ID.

**Comment by zeertzjq** [comment]
Are you sure this is a null pointer exception? I think you meant `attempt to index local 'client' (a nil value)`.

**Comment by zeertzjq** [comment]
This function probably needs a better error message in this case.

**Comment by marcinmaciukiewicz** [comment]
To be precise it's not NLP (I've deliberately made a shortcut since majority of my professional life I've spent with Java). Probably the error is a result of some misconfiguration but it's really hard to track without the context information in the message.

**Comment by marcinmaciukiewicz** [comment]
Maybe I don't understand the error. But the function fails when it's trying to get a client name for the client_id 2,3,4 and success in case of 1,5,6, and the LspInfo shows the clients with IDs 1,5,6. So how to find information about who is client  2,3,4?
