### ISSUE TITLE
lsp: formatting deletes unexpected lines

### ISSUE THREAD

**Issue by BitInByte** [neovim/neovim#16248]
### Description

When I save a file with the following command: `autocmd BufWritePre *.java lua vim.lsp.buf.formatting_sync(nil, 1000) ` it just randomly deletes lines of chars of my code.

### Neovim version

`NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20211103-23020-g5ct33/neovim-0.5.1/build/config -I/tmp/neovim-20211103-23020-g5ct33/neovim-0.5.1/src -I/usr/local/include -I/tmp/neovim-20211103-23020-g5ct33/neovim-0.5.1/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20211103-23020-g5ct33/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20211103-23020-g5ct33/neovim-0.5.1/build/include
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.1_1/share/nvim"

Run :checkhealth for more info`

### Operating system and version

macOS Monterey 12.0.1

### Affected language servers

Until now I only tested with Java

### Steps to reproduce

Just use `:w` and it will just randomly delete lines or chars

### Actual behavior

Deleting random lines and/or chars

### Expected behavior

Auto-Format

### Minimal config

```Lua
require'lspconfig'.jdtls.setup{}
require'lspconfig'.vuels.setup{}
require'lspconfig'.tsserver.setup{}
require'lspconfig'.vimls.setup{}

local nvim_lsp = require('lspconfig')

-- Use an on_attach function to only map the following keys
-- after the language server attaches to the current buffer
local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  -- Enable completion triggered by <c-x><c-o>
  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }

  -- See `:help vim.lsp.*` for documentation on any of the below functions
  buf_set_keymap('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
  buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
  buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
  buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
  buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
  buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  buf_set_keymap('n', '<space>lA', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
  buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
  buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
  buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
  buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  buf_set_keymap('n', '<space>f', '<cmd>lua vim.lsp.buf.formatting()<CR>', opts)

end

-- Add additional capabilities supported by nvim-cmp
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

-- Use a loop to conveniently call 'setup' on multiple servers and
-- map buffer local keybindings when the language server attaches
local servers = { 'pyright', 'tsserver', 'jdtls' }
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    on_attach = on_attach,
    flags = {
      debounce_text_changes = 150,
    },
    capabilities = capabilities,

  }
end


vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, {
    -- Enable underline, use default values
    underline = true,
    -- Enable virtual text, override spacing to 4
    virtual_text = {
      spacing = 4,
      -- prefix = '~',
    },
    -- Use a function to dynamically turn signs off
    -- and on, using buffer local variables
    signs = function(bufnr, client_id)
      local ok, result = pcall(vim.api.nvim_buf_get_var, bufnr, 'show_signs')
      -- No buffer local variable set, so just enable by default
      if not ok then
        return true
      end

      return result
    end,
    -- Disable a feature
    update_in_insert = false,
    virtual_text = true
  }
)

-- Setup nvim-cmp.
vim.o.completeopt = "menuone,noselect"

-- %% Sources %%
local luasnip = require 'luasnip'
local lspkind = require('lspkind')

local cmp = require'cmp'
cmp.setup({
    snippet = {
    -- REQUIRED - you must specify a snippet engine
    expand = function(args)
        -- vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
        require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
        -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
        -- require'snippy'.expand_snippet(args.body) -- For `snippy` users.
    end,
    },
    mapping = {
            ['<C-p>'] = cmp.mapping.select_prev_item(),
            ['<C-n>'] = cmp.mapping.select_next_item(),
            ['<C-d>'] = cmp.mapping.scroll_docs(-4),
            ['<C-f>'] = cmp.mapping.scroll_docs(4),
            ['<C-Space>'] = cmp.mapping.complete(),
            ['<C-e>'] = cmp.mapping.close(),
            ['<CR>'] = cmp.mapping.confirm {
            behavior = cmp.ConfirmBehavior.Replace,
            select = true,
    },
    ['<Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif luasnip.expand_or_jumpable() then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-expand-or-jump', true, true, true), '')
      else
        fallback()
      end
    end,
    ['<S-Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-jump-prev', true, true, true), '')
      else
        fallback()
      end
    end,
    },
    formatting = {
        format = require("lspkind").cmp_format({with_text = true, menu = ({
            buffer = "[Buffer]",
            nvim_lsp = "[LSP]",
            luasnip = "[LuaSnip]",
            nvim_lua = "[Lua]",
            latex_symbols = "[Latex]",
            path = "[Path]",
            calc = "[Calc]",
            cmp_tabnine = "[Tab9]"
            })}),
    },
    sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    -- { name = 'vsnip' }, -- For vsnip users.
    { name = 'luasnip' }, -- For luasnip users.
    -- { name = 'ultisnips' }, -- For ultisnips users.
    -- { name = 'snippy' }, -- For snippy users.
    }, {
    { name = 'buffer' },
    }, {
    { name = 'path' },
    }, {
    { name = 'spell' },
    }, {
    { name = 'calc' },
    }, {
    { name = 'cmp_tabnine' },
    })
})

-- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline('/', {
    sources = {
    { name = 'buffer' }
    }
})

-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline(':', {
    sources = cmp.config.sources({
    { name = 'path' }
    }, {
    { name = 'cmdline' }
    })
})
```

### Health check

health#lspconfig#check                                                                                                                                                                                         ========================================================================                                                                                                                                        
## Checking language server protocol configuration                                                                                                                                                              
  - INFO: pyright: configuration checked.                                                                                                                                                                       
  - INFO: jdtls: configuration checked.                                                                                                                                                                         
  - INFO: vuels: configuration checked.                                                                                                                                                                         
  - INFO: tsserver: configuration checked.                                                                                                                                                                      
  - INFO: vimls: configuration checked.    

### LSP log

https://gist.github.com/BitInByte/5c99020ca1958b8c34a490d60d176cca

**Comment by mjlbach** [comment]
Possibly unicode issue, also your config isn't very minimal. Can you reproduce without nvim-cmp? That shouldn't affect things, but you should still follow the issue template.

**Comment by mjlbach** [comment]
You might test #16252

**Comment by BitInByte** [comment]
One thing that I noticed is that if I use the same command to format with a map, this behaviour doesn’t happens but if I use it with autocmd it happens

**Comment by mjlbach** [comment]
@BitInByte Can you try on the latest nightly?

**Comment by mjlbach** [comment]
I'm pretty sure I closed this in https://github.com/neovim/neovim/pull/16444, feel free to re-open if not the case.

**Comment by BitInByte** [comment]
Hey, sorry the late response.

So, I’ve remade my config entirely to lua and it stopped making this behaviour but in the meanwhile, in the uni computer, with the same config, it still has a similar behaviour… 

I’ll try today after the 0.6 release, there should be a fix there right?

thanks one more time

**Comment by richardbizik** [comment]
Hi, I am experiencing the same issue. I am on nvim v0.6.0.
When I run `:lua vim.lsp.buf.formatting()` first time my code gets formatted however each subsequent call will remove a line seemingly from the place where formatting took place.

**Comment by mjlbach** [comment]
Try the latest master.

**Comment by richardbizik** [comment]
It's still happening even on the latest master

**Comment by mjlbach** [comment]
Then you’ll need to file an issue with the minimal reproductions including the language server version
________________________________
