### ISSUE TITLE
M1 brew install error 

### ISSUE THREAD

**Issue by sohunjug** [neovim/neovim#16243]
### Neovim version (nvim -v)

HEAD-c0ba315_1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

brew upgrade --fetch-HEAD

### Expected behavior

Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from a044c5f35 to f2e2a290c.
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 23 formulae.
==> Updated Casks
Updated 3 casks.

==> Upgrading 1 outdated package:
neovim HEAD-ed2573b -> HEAD-c0ba315_1
==> Downloading http://www.leonerd.org.uk/code/libvterm/libvterm-0.1.4.tar.gz
Already downloaded: /Users/sohunjug/Library/Caches/Homebrew/downloads/8f3cd21ee6cd4d11bb90593de5719ad147669ec1e7e32c46e907df1e6ade7f8b--libvterm-0.1.4.tar.gz
==> Downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz
Already downloaded: /Users/sohunjug/Library/Caches/Homebrew/downloads/4b91349796a66e38e93acd77e6ca14212c869090429fd88271def2be5293d83f--libmpack-lua-1.0.8.tar.gz
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.2-1.src.rock
Already downloaded: /Users/sohunjug/Library/Caches/Homebrew/downloads/0bc17975f0cf3981083172aa7da329b874e5780fa81494f5dd07d0665fcec23b--lpeg-1.0.2-1.src.rock
==> Cloning https://github.com/neovim/neovim.git
Updating /Users/sohunjug/Library/Caches/Homebrew/neovim--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at c0ba315b5 Merge pull request #16241 from bfredl/disptick
==> Upgrading neovim
  HEAD-ed2573b -> HEAD-c0ba315_1

==> luarocks make --lua-dir=/opt/homebrew/opt/luajit-openresty --tree=/private/tmp/neovim-20211106-45108-100c4hr/deps-build
==> luarocks make --lua-dir=/opt/homebrew/opt/luajit-openresty --tree=/private/tmp/neovim-20211106-45108-100c4hr/deps-build
==> make install PREFIX=/private/tmp/neovim-20211106-45108-100c4hr/deps-build LDFLAGS=-static
==> cmake -S . -B build -DLIBLUV_LIBRARY=/opt/homebrew/opt/luv/lib/libluv.dylib
==> cmake --build build
Last 15 lines from /Users/sohunjug/Library/Logs/Homebrew/neovim/05.cmake:
[ 50%] Building C object src/nvim/CMakeFiles/nvim.dir/tui/terminfo.c.o
cd /tmp/neovim-20211106-45108-100c4hr/build/src/nvim && /opt/homebrew/Library/Homebrew/shims/mac/super/clang -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -Dnvim_EXPORTS -I/tmp/neovim-20211106-45108-100c4hr/build/config -I/tmp/neovim-20211106-45108-100c4hr/src -I/tmp/neovim-20211106-45108-100c4hr/build/src/nvim/auto -I/tmp/neovim-20211106-45108-100c4hr/build/include -I/opt/homebrew/opt/luajit-openresty/include/luajit-2.1 -isystem /opt/homebrew/opt/gettext/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -flto=thin -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -MD -MT src/nvim/CMakeFiles/nvim.dir/tui/terminfo.c.o -MF CMakeFiles/nvim.dir/tui/terminfo.c.o.d -o CMakeFiles/nvim.dir/tui/terminfo.c.o -c /tmp/neovim-20211106-45108-100c4hr/src/nvim/tui/terminfo.c
/tmp/neovim-20211106-45108-100c4hr/src/nvim/terminal.c:818:29: error: passing 'VTermStringFragment' to parameter of incompatible type 'char *'
    buf_set_term_title(buf, val->string);
                            ^~~~~~~~~~~
/tmp/neovim-20211106-45108-100c4hr/src/nvim/terminal.c:789:50: note: passing argument to parameter 'title' here
static void buf_set_term_title(buf_T *buf, char *title)
                                                 ^
1 error generated.
[ 50%] Building C object src/nvim/CMakeFiles/nvim.dir/tui/tui.c.o
cd /tmp/neovim-20211106-45108-100c4hr/build/src/nvim && /opt/homebrew/Library/Homebrew/shims/mac/super/clang -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -Dnvim_EXPORTS -I/tmp/neovim-20211106-45108-100c4hr/build/config -I/tmp/neovim-20211106-45108-100c4hr/src -I/tmp/neovim-20211106-45108-100c4hr/build/src/nvim/auto -I/tmp/neovim-20211106-45108-100c4hr/build/include -I/opt/homebrew/opt/luajit-openresty/include/luajit-2.1 -isystem /opt/homebrew/opt/gettext/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -flto=thin -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -MD -MT src/nvim/CMakeFiles/nvim.dir/tui/tui.c.o -MF CMakeFiles/nvim.dir/tui/tui.c.o.d -o CMakeFiles/nvim.dir/tui/tui.c.o -c /tmp/neovim-20211106-45108-100c4hr/src/nvim/tui/tui.c
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/terminal.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

### Actual behavior

two days

**Comment by clason** [comment]
Try removing and reinstalling `neovim`. This is due to https://github.com/Homebrew/homebrew-core/pull/88701.
