### ISSUE TITLE
[RFC] Preparing for the first release

### ISSUE THREAD

**Issue by tarruda** [neovim/neovim#1625]
#1605 paves the way for a completely refactored UI and this means Neovim is getting close to its first release. I'm opening this issue to draw a line for which tasks must be performed before Neovim becomes beta.

#1605 exposes a new UI API based on the ideas of how Vim GUI is implemented: A custom termcap parser that is fed with data passed to ui_write(which normally simply writes to the screen) and calls UI update functions in ui.c. This scenario is hacky and far from ideal(in essence Nvim is parsing its own output), but it will let us do the migration in smaller steps, especially because #1605 introduces a nice way of testing screen state. 

With that said, here's what I have planned for the first release:

- [x] Merge #1605
- [x] Add more screen tests
- [x] Refactor the builtin terminal UI for the new UI architecture. The new TUI is based on [unibilium](https://github.com/mauke/unibilium) and [libtermkey](http://www.leonerd.org.uk/code/libtermkey/)
- [x] Remove term.c, term.h and term_defs.h and replace all calls to out_str that output terminal codes by direct calls to ui.c functions. This will remove the termcap hack introduced in #1605 
- [ ] Add a new implementation of the UI layer based on a GUI toolkit. I still haven't chosen a GUI library so suggestions are welcome as long as the library meets these requirements: 
  - is implemented in pure C
  - is very lightweight, Nvim doesn't need advanced GUI features, just enough to implement a RGB terminal-like grid.
  - is cross platform(windows/unix)
- [x] Implement an alternative way of handling commands that require a terminal(#1496/#1528). Fixed by #2076.
- [ ] Make the necessary changes to build/run on Windows(@equalsraf seems to have done a lot of the work already)

Note that even though libtermkey is incompatible with Windows, we are still going to use it for Neovim. The reason is simple: Windows console is a pain and there's no need to maintain a terminal version  that is windows-compatible because no one will ever use it.

If anyone remembers something critical that should be added to the above list just let me know

**Comment by justinmk** [comment]
@tarruda I think we can close this issue.

- GUI is postponed to 0.2 milestone
- Windows work is ongoing and doesn't need this issue to track it

**Comment by tarruda** [comment]
:+1:
