### ISSUE TITLE
WinNew not triggered during autocmd

### ISSUE THREAD

**Issue by luukvbaal** [neovim/neovim#16255]
### Neovim version (nvim -v)

`v0.6.0-dev+525-ge921e98ce` (same behavior was present on `0.5`).

### Vim (not Nvim) behaves the same?

~~no, vim `8.2.3441`~~ yes

### Operating system/version

Linux

### Terminal name/version

simple terminal/0.8.4

### $TERM environment variable

st-256color

### Installation

Arch User Repoistory (AUR)

### How to reproduce the issue

```vim
nvim --clean <file>
:autocmd QuickFixCmdPost [^l]* split
:autocmd WinNew * unsilent echomsg 'test'
:vimgrep /test/j %
```
"test" is not echoed by nvim, ~~but is echoed by vim.~~

### Expected behavior

`WinNew` is triggered for windows spawned during autocmds?

### Actual behavior

`WinNew` is not triggered by windows spawned by other autocmds such as `QuickFixCmdPost` and `User LspDiagnosticsChanged`. Not sure about the root issue but this is how it manifests for me.

I ran into this issue while developing plugin [stabilize.nvim](https://github.com/luukvbaal/stabilize.nvim) which currently requires a workaround for certain window events as described [here](https://github.com/luukvbaal/stabilize.nvim#note).

(The current suggestion for the workaround is to use a user `autocmd` `User StabilizeRestore` as I erred on the safe side to prevent problems with WinNew autocmds not defined by my stabilize.nvim. Now that I confirmed that `WinNew` is in fact not triggered in the described events, the suggested workaround might as well be a `doautocmd WinNew` however.)

I've been using the workaround for a while and it works fine but I thought I would report the issue ~~after noticing that the behavior is different(correct?) for vim~~.

Edit: I could have sworn `vim` was echoing "test" when I tested this earlier but now I cant reproduce the correct behavior on vim either. The issue still stands though I think, unless this is intended behavior?

**Comment by zeertzjq** [comment]
Well, although this is indeed a bug, your steps to reproduce seem a bit strange. I suggest you change `echo("test")` to `unsilent echomsg 'test'`.

**Comment by zeertzjq** [comment]
Wait, see `:h ++nested`.

**Comment by zeertzjq** [comment]
Wait, see `:h autocmd-nested`.

**Comment by zeertzjq** [comment]
Unfortunately you need to add `++nested` to the `QuickFixCmdPost`, which doesn't seem very convenient in your case.

**Comment by luukvbaal** [comment]
Ah that explains, thanks. Unfortunately that indeed doesn't help me.

I suppose the only thing that could help me is if `WinNew` was a valid candidate to be ignored by the nest protection by default. 

This supposed "enhancement" would lead to problems when defining an autocmd for `WinNew` that itself spawns a new window but I'm not sure if this is something that you would ever want to do/is done by any plugin. 

Perhaps the enhancement could be that `WinNew` is triggered by other autocmds but not by itself. Or have the disabled nest protection for `WinNew` enable after `x` nested triggers.

Not sure if any of these options are valid, feel free to close if not.

**Comment by luukvbaal** [comment]
At the very least this made me rethink the suggested workaround for stabilize.nvim which no longer requires a patch to trouble.nvim, thanks @zeertzjq. 

Perhaps this is good enough and there is no "enhancement" to neovim required.

**Comment by luukvbaal** [comment]
I added a user cfg option to stabilize.nvim in https://github.com/luukvbaal/stabilize.nvim/commit/52303e5003659eb796c68c3016ca337ac23b9ce3 that I think is elegant enough that I don't think any change is necessary in neovim. 

Feel free to close this unless you think that the issue warrants further discussion.
