### ISSUE TITLE
Deno language server Markdown TypeScript code blocks have no syntax highlighting

### ISSUE THREAD

**Issue by David-Else** [neovim/neovim#16269]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+558-g3ba800f15

### Language server name/version

deno 1.16.0

### Operating system/version

Linux Centos 8.4 (using appimage)

### :checkhealth

```markdown
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5204'
  - INFO: $COLORTERM='truecolor'

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: bashls: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: denols: configuration checked.
  - INFO: null-ls: configuration checked.
  - INFO: ltex: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: html: configuration checked.
```

### Steps to reproduce using "nvim -u minimal_init.lua"

The Deno LS has TypeScript Markdown code blocks that should be syntax highlighted, but they are not. This was previously assumed to be a bug in Deno, but this bug has [since been fixed](https://github.com/denoland/deno/issues/12620#issuecomment-957679790) and is now assumed to be in Neovim itself.

I reported the issue for nvim-cmp, but was told it was an upstream issue https://github.com/hrsh7th/nvim-cmp/issues/500

There was a similar issue in the past which may shed some light on this https://github.com/hrsh7th/nvim-compe/issues/373

It is not just the SignatureHelp, but all markdown code blocks returned by Deno that have no syntax highlighting:

![Screenshot from 2021-11-09 10-44-22](https://user-images.githubusercontent.com/12832280/140910412-f6ea3052-c43f-4934-9caf-c8b59fd613f4.png)

**To Reproduce**
1. Use the Deno language server https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#denols
3. Start typing `Deno.test` (or any function that has code blocks)

I have tested on Neovim 0.5.1 and the latest master, same result.

**Comment by mjlbach** [comment]
@folke if you have time to look at this the actual RPC response is
```
[DEBUG][2021-11-12 22:22:52] .../vim/lsp/rpc.lua:446	"rpc.receive"	{
  id = 2,
  jsonrpc = "2.0",
  result = {
    contents = { {
        language = "typescript",
        value = "function Deno.test(t: Deno.TestDefinition): void (+1 overload)"
      }, 'Register a test which will be run when `deno test` is used on the command\nline and the containing module looks like a test module.\n`fn` can be async if required.\n```ts\nimport {assert, fail, assertEquals} from "https://deno.land/std/testing/asserts.ts";\n\nDeno.test({\n name: "example test",\n fn(): void {\n   assertEquals("world", "world");\n },\n});\n\nDeno.test({\n name: "example ignored test",\n ignore: Deno.build.os === "windows",\n fn(): void {\n   // This test is ignored only on Windows machines\n },\n});\n\nDeno.test({\n name: "example async test",\n async fn() {\n   const decoder = new TextDecoder("utf-8");\n   const data = await Deno.readFile("hello_world.txt");\n   assertEquals(decoder.decode(data), "Hello world");\n }\n});\n```' },
    range = {
      end = {
        character = 9,
        line = 0
      },
      start = {
        character = 5,
        line = 0
      }
    }
  }
}
```

**Comment by mjlbach** [comment]
Ah yes, not a bug

Add
```
vim.g.markdown_fenced_languages = {
  "ts=typescript"
}
```

**Comment by David-Else** [comment]
This is a classic case of bad user experience in Neovim. A new user should not have to deal with these time wasting frustrations. Why not just make `markdown_fenced_languages` set to ALL languages? Also, please turn on the folding by default! `let g:markdown_folding = 1`, how does it help to have it off?

**Comment by mjlbach** [comment]
> This is a classic case of bad user experience in Neovim. 

You are welcome to file a PR against vim improving the default markdown highlighting experience, and then port it to neovim.

> Why not just make markdown_fenced_languages set to ALL languages? 

What is your expectation on how this will work?

I would suggest reading through the implementation of the markdown syntax file (or trying vim.g.markdown_fenced_languages = "all"/ {"all"} before suggesting fixes. The pertinent source code that explains why "all" does not make sense is [here](https://github.com/mjlbach/neovim/blob/b74916cfd21fc307ad4898a519e1407411a01ba5/runtime/syntax/markdown.vim#L22-L32). Again, this really is not an LSP issue, you can reproduce the same behavior with a bare markdown file

```ts
console.log("test")
```

> Also, please turn on the folding by default! let g:markdown_folding = 1, how does it help to have it off?

This would be, at best, extremely controversial. I don't see why we would do this, as it would require users to toggle into the documentation would to unfold things, or we would have to add a function to "unfold" the current active diagnostic window.

If you're asking why this isn't the global default, you can take this up with the author of the markdown runtime file, although I would caution you that its Tim Pope.

**Comment by David-Else** [comment]
@mjlbach Sorry if I came across as demanding or annoying. I am afraid I don't have the skills in vimscript, c or lua to file any PR's that would help. I am trying to help by sharing my user experience, I love Neovim and want it to be used by as many people as possible.

> Why not just make markdown_fenced_languages set to ALL languages?
> What is your expectation on how this will work?

I might be missing something, but I don't know why `markdown_fenced_languages` even exists. If I want to use a code block in markdown I obviously want it highlighted, why wouldn't I? If the syntax is available it should be used, if not then it can give a warning or simply not highlight it. That is what I would expect to happen, The idea I have to look up a special command and give it a list seems very unintuitive and time wasting. I think I must be missing something here, or it would just do this?

Regarding the folding, I would have the default for markdown `setlocal foldlevel=99 conceallevel=2`. This solves the problem, and is the default I would have expected.... but that is just me!

**Comment by zeertzjq** [comment]
I think Vim's current syntax highlight engine requires this? Maybe tree-sitter can make this easier in the future.

**Comment by mjlbach** [comment]
It's not that we aren't loading/applying a particular languages highlighting rules, it's that we have no way of knowing what those rules are from an arbitrary string like `ts`, so we rely on the mapping of string identifier to filetype built-into vim.

The main issue is, much like vim's current syntax engine, we have to inject the highlight groups by manually parsing the buffer contents to find the codefenced language identifier. If this doesn't map directly onto a given filetype, we do as the markdown plugins do and use the user provided additional mappings from string identifier to filetype plugin. If in a week deno decides to change from ts to deno-ts (maybe because they add some custom vim highlighting rules for highlighting the word Deno) and start sending that string identifier, the highlighting will break again.

The ergonomic alternative is to hardcode into neovim a list of common identifiers, which IMO is brittle for the aforementioned reasons. I'd rather filetype plugins start adding aliases for the common ones than us try to augment that with some global list.

**Comment by clason** [comment]
> Regarding the folding, I would have the default for markdown setlocal foldlevel=99 conceallevel=2. This solves the problem, and is the default I would have expected.... but that is just me!

And, yes, this is just you.
