### ISSUE TITLE
Unable to set `list` option from init.lua

### ISSUE THREAD

**Issue by and3rson** [neovim/neovim#16273]
### Neovim version (nvim -v)

v0.6.0-dev+527-ga141f6e92

### Vim (not Nvim) behaves the same?

NVim-specific feature

### Operating system/version

ArchLinux

### Terminal name/version

alacritty 0.9.0 (fed349aa)

### $TERM environment variable

screen-256color

### Installation

from source

### How to reproduce the issue

```sh
$ cat `~/.config/nvim/init.lua`
vim.o.list = true
vim.go.list = true
vim.wo.list = true
vim.api.nvim_set_option('list', true)
vim.api.nvim_win_set_option(0, 'list', true)
vim.cmd('set list')
$ vim --clean
```

### Expected behavior

```
$set list?
list
```

### Actual behavior

```
$ set list?
nolist
```

**Comment by zeertzjq** [comment]
Runing with `--clean` skips `init.lua`.

**Comment by clason** [comment]
You can do `nvim --clean -u <path/to/init.lua>` (note the order).
