### ISSUE TITLE
:find does not prune 'wildignore' matches during file system traversal for <Tab>-completions generation

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#16272]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+542-g5ad15c9fa

### Vim (not Nvim) behaves the same?

Yes, Vim 8.2.2029

### Operating system/version

macOS 11

### Terminal name/version

kitty 0.23.1, fish 3.3.1

### $TERM environment variable

xterm-kitty

### Installation

Build from source

### How to reproduce the issue

1. Find to a folder `foo/` with a large tree under `foo/bar/` but no other large trees under `foo/` (something like `foo/node_modules/`, for example).
2. `cd foo/`
3. `vim`
4. `:set path+=**`
5. `:find (something)<Tab>`. Generating the completions will take a while because `foo/bar/` is a large tree.
6. `:set wildignore+=*/bar/*`
7. `:find (something)<Tab>`. Now this should be snappy (assuming there are no other large trees under `foo/`), but it isn't. No completions under `foo/bar` are returned, but the file system traversal is clearly still walking the whole tree.
8. This is easy to verify by executing `mv foo/bar /tmp/bar` repeating the above steps -- now `:find (something)<Tab>` will be snappy.

### Expected behavior

I expected that `:set wildignore+=*/bar/*` would make tab completion using `:find` fast, because the under-the-hood `:find` traversal would prune all of `foo/bar/` from its search.

### Actual behavior

`:find (something)<Tab>` continues to be slow, because it traverses this large subtree. (I'm inferring the "because" since `:find` is fast if I just move the subtree somewhere else.)

(Vim issue: https://github.com/vim/vim/issues/9111)

**Comment by andrey-mishchenko** [comment]
Reproduced with `nvim --clean` on 0.5.1.

One more note: Neovim is very noticeably slower at this `:find` than vanilla Vim, for me. Like at least twice as slow.

**Comment by andmis** [comment]
FWIW this has been rejected by Bram. So it sounds unlikely to get fixed upstream. https://github.com/vim/vim/issues/9111

**Comment by justinmk** [comment]
It's true that `path=**` basically defeats the purpose of 'path' so it's not really something that should be designed around. 

> `wildignore` is squarely ignored by the file search portion of `:find foo<Tab>` and only used by the completion portion, which only happens _after_ the search part. In practice, this has zero negative effect if you use `path` and `wildignore` correctly.

So tab-complete has a "completion portion" and a "search portion"? If so, yes, that is a bug. Does this affect only `:find`, or does it affect tab-complete for other commands? Why would `:find` have a different tab-complete implementation than say `:edit` ?

**Comment by andmis** [comment]
It's been a while, but here is a quick synopsis: if you `:find` with `**` in your `path`, and `*/foo/*` in your `wildignore`, then `:find` will never return a result under `foo/something/else`, but if `foo/some/subdir` has a ton of files in it (like `node_modules`), then tab-completion after `:find` will be slow, because the code that walks the directory tree dealing with `**` doesn't just ignore everything under `foo/`, as I claim it should because it will never return a result from there anyway because `*/foo/*` is in `wildignore`.

All this would take is, in the code that generates tab completion results on behalf of `:find`, when we recurse downward, we match the directory we are recursing into against `wildignore` and skip recursing in if we get a match. But this is easier said than done last time I looked at the code.

When I filed this issue I was not using FZF or any other plugin -- I was using `path+=**` and `:find` for a plugin-free FZF-like experience to open files, and actually that works really well. *Except* that if you are in a folder with `node_modules` in it, your `:find` will be slow, and `wildignore+=node_modules` will make it so that `:find` never _returns_ anything from under `node_modules`, but it does _not_ make the tab-completion FS walking code ignore everything under `node_modules`.

Since a huge majority (I think) of [Neo]vim users use FZF or some other plugin for file system navigation (myself included, now), I'm not sure this is very high-priority. I looked into this once and the C code implementing this functionality is pretty complex for what it does. Probably if we ever move `:find` to Lua, for instance, this would be worth fixing.

---

> Why would :find have a different tab-complete implementation than say :edit ?

`:edit` does not use `path`. If `foo` is in `path` and `MyFile.txt` and `MyOtherFile.txt` are under `foo/`, then `:find My<Tab>` should (and does) show `MyFile.txt` and `MyOtherFile.txt` as options, but `:e My<Tab>` should be (and is) empty. I guess this comes down to, `:e` does not do `**` expansion, and `:f` does.

**Comment by andmis** [comment]
Also I don't think it's true that
> `path=**` basically defeats the purpose of 'path'

The docs say `path` gives a list of directories to search under. And `**` is explicitly supported. How else do you say, "search everything under `$(pwd)`"?

From the docs:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/5308024/169714041-d5ceb466-9ac9-4828-be27-ab90b907eaa0.png">

**Comment by justinmk** [comment]
> Also I don't think it's true that
> 
> > `path=**` basically defeats the purpose of 'path'

See https://github.com/neovim/neovim/issues/3209


> "search the entire directory tree under $(pwd), except for node_modules", and wildignore


Does it work if you explicitly put `**/` in the cmdline? That also can be a mapping. So setting 'path' is too blunt.

**Comment by andmis** [comment]
I'm not sure what that thread is supposed to demonstrate. It looks like that was a proposal to add a naked `**` to `path` _by default_, which some people apparently thought was reasonable. We are just talking about what happens if a user happens to have any `path` entry with `**` in it _at all_.

If I add `path/to/my/project/**` to my `path`, to indicate that I want `:find` to search the entire tree under my project, then this bug remains. I have no mechanism for excluding `my/project/node_modules` from the search, even though everything under `my/project/node_modules` will be excluded from the _results_ of the search (assuming I add `*/node_modules/*` to `wildignore`).

I just tried `:find **/something<Tab>` with `path=` and `wildignore=node_modules` and the bug remains (the search is slow).

**Comment by andmis** [comment]
Maybe @tpope has better context on how `path` actually gets used in the wider ecosystem, in particular with filetype plugins – and maybe we should add a blurb in `:h 'path'` about this, because (1) there are definitely people that add `**` to `path` and use `:find` as a fuzzy finder, which IMO is a totally natural thing to do, (2) there is at least one popular Vim talk (https://www.youtube.com/watch?v=XA2WjJbmmoM&t=408s, 700k views) which explicitly advises to `set path+=**`, (3) there is at least one example of `set path+=**` in the [Neo]vim `:help` docs.

So if our advice is "don't set `path` unless you know what you're doing, use a fuzzy finder plugin" (which is reasonable IMO) then maybe we should converge on that?

**Comment by tpope** [comment]
My thoughts on how it "should" be used are at https://github.com/tpope/vim-apathy.

If my offer a suggestion: back up a step and figure out if this is strictly a performance optimization, or if it would change the behavior in some way. If it's only performance, then all the sourpussing in https://github.com/vim/vim/issues/9111 about how it's "supposed to be" is completely irrelevant, because nothing is changing that regard. But on the flip side, you don't get to whine about "we should support it", because it's already 100% supported. Move on to proposing an implementation.

**Comment by andmis** [comment]
This thread is about a performance optimization:
>All this would take is, in the code that generates tab completion results on behalf of :find, when we recurse downward, we match the directory we are recursing into against wildignore and skip recursing in if we get a match.

---

I agree that the discussion about how `path` is "supposed to be" is irrelevant. And I think that includes comments of the form "you should not put `**` into `path`", in this thread as well as in https://github.com/vim/vim/issues/9111. So I'm going to drop that line of discussion. We can also resolve those comments as off-topic. Thanks for your input and the vim-apathy reference, I wasn't aware of it.

**Comment by andmis** [comment]
Actually it looks like [this Vim issue](https://github.com/vim/vim/issues/2132) from 2017 may have the same root cause (perhaps the issue is just the that `**` expansion does not respect `wildignore`, and `:find` and `path` may be red herrings). That issue also includes a small patch in the description which the author claims yielded a huge perf improvement.

That issue also references https://github.com/neovim/neovim/issues/11624, so I am gonna close this as a duplicate, but it would be nice if we pulled https://github.com/neovim/neovim/issues/11624 up out of "not planned" IMO.
