### ISSUE TITLE
Off-spec LSP requests are showing method not supported messages (for Lean LSPs) on startup

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#16279]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+4174244d8

### Language server name/version

leanlsp / lean3lsp

### Operating system/version

macOS 12.0.1

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: tsserver: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: lean3ls: configuration checked.
  - INFO: ccls: configuration checked.
  - INFO: leanls: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: pylsp: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - WARNING: "nvim-ipy" is not registered.
  - WARNING: Out of date
    - ADVICE:
      - Run `:UpdateRemotePlugins`

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
  - INFO: $TERM: screen-256color
```

### Steps to reproduce using "nvim -u minimal_init.lua"

With:

* Install Lean (4) via e.g. [nix instructions here](https://leanprover.github.io/lean4/doc/setup.html#nix-setup) or by simply downloading a binary from [here](https://github.com/leanprover/lean4-nightly/releases/tag/nightly-2021-11-10)
* Run `nvim -u below_minimal_init.lua` and then `:e foo.lean` (you should immediately see an autoopened second window open on the right side if everything is properly installed)

#### minimal_init.lua

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'Julian/lean.nvim',
      'neovim/nvim-lspconfig',
      'nvim-lua/plenary.nvim',
      'wbthomason/packer.nvim',
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  require'lean'.setup{
    lsp = { on_attach = on_attach }
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### Expected behavior

No messages.

(You can type `#check 12` into the lean buffer which should confirm to you it's alive / connected to the language server)

### Actual behavior

An error message is often shown like:

```
method $/lean/rpc/connect is not supported by any of the servers registered for the current buffer
```

or

```
method $/lean/discoverWidget is not supported by any of the servers registered for the current buffer
```

when the `:e` opens the Lean file. Everything however seemingly functions correctly, including widget support which is what we call that LSP method for. It's just the warning that shows.

How often is unfortunately a bit non-deterministic. For me it happens around half the time on my "normal" vimrc, but on the minimal vimrc which starts up faster, it seems more like a quarter of the time. Will try to play with getting it to happen more often, but this came out of a conversation with @mjlbach who says he knows what the problem is already probably :)

**Comment by zeertzjq** [comment]
Maybe it is a problem with that plugin? Also see the comments is #15926

**Comment by mjlbach** [comment]
I explicitly asked Julian to file this issue, and will take care of this personally.

**Comment by Julian** [comment]
Do let me know if I didn't include enough info and thanks again!

**Comment by mjlbach** [comment]
Hey @Julian, sorry for the delay. With your steps above I'm unable to reproduce the issue. Is there something else I need to do?

**Comment by Julian** [comment]
Arg. So you see the second window open, and no error message?

**Comment by Julian** [comment]
I just re-tried it again myself with the minimal vimrc and successfully reproduced 3 times, then when I went to record a screenshot have unsuccessfully managed to get it to happen ~15 times :( :( :( -- will try to figure out how to get it more reliably.

**Comment by Julian** [comment]
OK! I *think* my suspicion originally is correct -- I just saturated all my CPUs by running an expensive `make` in the background, and then finally got it to reproduce a bit more reliably:

https://asciinema.org/a/CeWZqnJAgwb5W1w6XnyQVLlJv

It's at the 7:15 mark. Albeit still not every time, but more often.

**Comment by mjlbach** [comment]
That is strange, it shouldn't matter where in the init process you are for the (lack of) validation check, because we never check those messages... I'll look into it more.

**Comment by mjlbach** [comment]
I think this is technically a plugin error right @Julian? About calling buf requests before the server is ready (so the server isn't attached to the buffer). I believe you all have patched this upstream, so can it be closed?

**Comment by Julian** [comment]
Yes, sorry for wasting some of your time, we appreciate it!
