### ISSUE TITLE
`nvim_buf_set_lines` reported E523 in map-expr

### ISSUE THREAD

**Issue by lotabout** [neovim/neovim#16278]
### Neovim version (nvim -v)

NVIM v0.5.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 11.0.1

### Terminal name/version

kitty 0.18.1

### $TERM environment variable

screen-256color

### Installation

homebrew

### How to reproduce the issue

1. open neovim `nvim`
2. define a function that uses 
    ```
    :function X()
    :  let buf = nvim_create_buf(v:false, v:true)
    :  call nvim_buf_set_lines(buf, 0, -1, v:true, ["test", "text"])
    :  let opts = {'relative': 'cursor', 'width': 10, 'height': 2, 'col': 0, 'row': 1, 'anchor': 'NW', 'style': 'minimal'}
    :  let win = nvim_open_win(buf, 0, opts)
    :endfunction
    ```
3. define an `expr` mapping by `:map <expr> x X()`
4. enter normal mode and press `x` key.

### Expected behavior

No error occurs

### Actual behavior

Error occurs:
```
Error detected while processing function X:
line    2:
E5555: API call: E523: Not allowed here
Press ENTER or type command to continue
```

Note that with "normal" bindings like `:map t :call X()<CR>` actually works.

**Comment by zeertzjq** [comment]
In `:h map-<expr>`
```
Be very careful about side effects!  The expression is evaluated while
obtaining characters, you may very well make the command dysfunctional.
Therefore the following is blocked for <expr> mappings:
- Changing the buffer text |textlock|.
- Editing another buffer.
- The |:normal| command.
- Moving the cursor is allowed, but it is restored afterwards.
- If the cmdline is changed, the old text and cursor position are restored.
If you want the mapping to do any of these let the returned characters do
that. (Or use a |<Cmd>| mapping instead.)
```

**Comment by lotabout** [comment]
@zeertzjq Thanks for clarification.

I was actually trying to port an input method plugin [ywvim](http://www.vim.org/scripts/script.php?script_id=2662)'s calling to vim's popup window to floating window. The plugin would use popup window to display the choices around the cursor, and popup window's APIs are called(and legitimate) in there `map-expr` functions. e.g.

![image](https://user-images.githubusercontent.com/1527040/141249285-9814c4fe-feee-4857-bcc0-547af24ccdbe.png)

Is there any workaround in neovim for implementing this?

**Comment by zeertzjq** [comment]
Have you tried `<Cmd>` mappings?
