### ISSUE TITLE
Typo in Documentation of `:runtime`

### ISSUE THREAD

**Issue by jam1015** [neovim/neovim#16288]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

No

### Operating system/version

maOS 10.15.7

### Terminal name/version

Kitty

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

run `:help runtime`

### Expected behavior

The word `manner` should be spelled correctly.

### Actual behavior

It's spelled `mannar`.

**Comment by clason** [comment]
Thank you, but I cannot find `mannar` anywhere in the current(!) runtime -- so either this was fixed already, or the corresponding entry has been rewritten and the typo removed.
