### ISSUE TITLE
getchangelist() not compatable with vim / missing useful behavior

### ISSUE THREAD

**Issue by yomotherboard** [neovim/neovim#16282]
### Neovim version (nvim -v)

v0.6.0-dev+356-gbec7f47ce

### Vim (not Nvim) behaves the same?

no, 8.2.3441

### Operating system/version

Arch    (Linux 5.14.14-arch1-1)

### Terminal name/version

st 0.8.4

### $TERM environment variable

st-256color

### Installation

repo / nightly

### How to reproduce the issue

Run command `:call getchangelist()` with no argument.

### Expected behavior

In vim this returns a changelist for all buffers.

The vanilla vim behavior makes it much easier to use the global jumplist, for example to implement a jumplist [fuzzy-finding function.](https://github.com/junegunn/fzf.vim/issues/865#issuecomment-955740371)

### Actual behavior

Nvim it returns an error `E119: Not enough arguments for function: getchangelist`.

**Comment by zeertzjq** [comment]
Reinstall `neovim-nightly-bin` to install the latest nightly release.
