### ISSUE TITLE
"Bad argument #2 to 'format'" when executing vim.lsp.buf.rename()

### ISSUE THREAD

**Issue by konapun** [neovim/neovim#16281]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Xubuntu 21.04

### Terminal name/version

kitty 0.19.3

### $TERM environment variable

screen-256color

### Installation

appimage

### How to reproduce the issue

1. Start nvim
2. Open a file for which there's an associated language server
3. Position the cursor over a variable to be renamed
4. Type `:lua vim.lsp.buf.rename()`
5. Enter a new name when prompted for "New Name"
6. Hit Enter
7. Encounter error

### Expected behavior

Variable renamed without error

### Actual behavior

Receive the following error message and variable is not renamed:
```
Error executing lua ...imF3iZds/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:458: bad argument #2 to 'format' (nu
mber expected, got nil)
```

**Comment by mjlbach** [comment]
I am almost certain this is a plugin related issue.

You can test the unreleased 0.5.2 (there is no pertinent backport which would affect this AFAIK) in a clean environment with
`podman run --rm -it quay.io/nvim-lsp/try.nvim:stable-lua nvim ./runtime/lua/man.lua`

You can substitute docker instead of podman if necessary.

**Comment by konapun** [comment]
It works fine with 0.5.2 :+1:

**Comment by mjlbach** [comment]
I'd recommend wiping and bisecting your configuration. (~/.local/share/nvim/site can be temporarily moved) and using a known to work initial configuration. The container uses [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim). It should work on 0.5.1.

**Comment by konapun** [comment]
Thanks, it looks like it might be a bug from [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig).

**Comment by mjlbach** [comment]
I'd be very surprised, given the container is using the latest lspconfig (I'm also the maintainer of lspconfig).

**Comment by konapun** [comment]
Turns out it was an error with the efm language server. After running `:LspUninstall efm` followed by `:LspInstall efm` everything now works as expected.
