### ISSUE TITLE
LSP `contentChanged` updates not sent if `filetypedetect` triggered during before loading buffer

### ISSUE THREAD

**Issue by Isopod** [neovim/neovim#16297]
### Neovim version (nvim -v)

0.5.1

### Language server name/version

all

### Operating system/version

Arch Linux

### Steps to reproduce using "nvim -u minimal_init.lua"

I prepared a [testcase](https://github.com/Isopod/nvim-lsp-testcase) just for this issue. Detailed instructions are in the README.

#### init.vim
```
packadd nvim-lspconfig
lua require'lspconfig'.dummy.setup{}
syntax on
```

You can use any language server of your choice (substitute `dummy` accordingly). Feel free to use the minimal [`dummyls.py`](https://github.com/Isopod/nvim-lsp-testcase/blob/master/dummyls.py) from my repository.

#### Actions
- Open a file supported by the language server and modify the buffer. 
- Observe the messages sent by Neovim. (You can do this either by checking `lsp.log`, or, if you use my dummy language server, check the output of `transcript.txt` in the current directory.)
- Notice that no updates are being sent (but initialization, shutdown and other messages *are* sent)

#### Observations
- The critical line is `syntax on` in `init.vim`. If it is *not* present, then updates work.
- The issue *cannot* be reproduced if there is a mode line in the file specifying the type, e.g. `# vim:et ft=dummy`
- I bisected and discovered that the bug started with commit 519848f64eda3aacb6d2ceac63c3b52c9ff0c59b.

I hope this is clear. I'm sorry if it is a bit messy, I reduced it as best I could. It took me several days to find out the exact circumstances under which it could be reproduced.

### Expected behavior

When the buffer content is changed, `contentChanged` updates should be sent to the language server.

### Actual behavior

`contentChanged` updates are not sent. As a result, features like code completion do not work.

**Comment by mjlbach** [comment]
It's probably something to do with clearing/forcing the autocommands, but why are you calling `syntax on` in the first place?

**Comment by Isopod** [comment]
I don't remember, I've been using the same vimrc for years. Either syntax highlighting used to not be on by default, or the line might have just been copied over from a tutorial or something and never questioned. Removing the line fixed it for me, but that doesn't explain why it caused a problem in the first place. It should at worst be redundant. It's also not clear if there are other commands that could also trigger this bug.

**Comment by mjlbach** [comment]
Also to clarify, it's not really `syntax on`, it's the filetypedetect autocommand group that causes the issue

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.fn.execute('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
end

vim.cmd  [[
  augroup Packer
    autocmd!
    autocmd BufWritePost init.lua PackerCompile
  augroup end
]]

local use = require('packer').use
require('packer').startup(function()
  use 'wbthomason/packer.nvim' -- Package manager
  use 'neovim/nvim-lspconfig' -- Collection of configurations for built-in LSP client
end)

if os.getenv('INSTALL') then
  goto eof
end

require('lspconfig').pyright.setup{}
vim.cmd [[
  filetype on
  doautoall filetypedetect BufRead
]]
```

**Comment by mjlbach** [comment]
Please test https://github.com/neovim/neovim/pull/16723

**Comment by Isopod** [comment]
I can confirm that #16723 fixes the issue.
