### ISSUE TITLE
Suppress number in front of diagnostic in show_position_diagnostics()

### ISSUE THREAD

**Issue by smhc** [neovim/neovim#16309]
### Feature already in Vim?

No

### Feature description

The show_position_diagnostics() call was added recently as a far more practical means of 'hover help' on an underlined error via LSP.

However each diagnostic is still prefixed with an index, which is pretty unlikely to be useful, it is quite a bit of clutter when combined with "show_header=false". For the 'position' diagnostic it's quite likely there is only 1 error.

https://github.com/neovim/neovim/blob/master/runtime/lua/vim/diagnostic.lua#L1228

Can this be suppressed? It could be smart and suppress if the count of errors is greater than 1, or the 'format' callback could be used to customise it properly. Or it could be optional suppression via something like opts.no_prefix=true

I'm not too fussed how it is done, as long as I can nix it. I even think it makes sense to get rid of it by default.

**Comment by mjlbach** [comment]
it doesn't make sense in the context of the formatting function which operates on the diagnostic level, maybe as an opt. I imagine users wants some visual delineation per diagnostic and don't think we should go overboard with customization. We could make it opt.prefix_func that takes in the current diagnostic count, and then if users want a single bullet, nothing, or the conditional number the can handle that ithemselves.

> However each diagnostic is still prefixed with an index, which is pretty unlikely to be useful

I disagree, and think the default should remain as is. It means the diagnostics are in a consistent visual position WRT to the left side of the hover window, and don't shift depending on if there is only a single diagnostic (it also means it's easy at a glance to determine the diagnostic count for a single position).

**Comment by smhc** [comment]
For lspsaga I added a 'prefix_diagnostic_format' config option that defaulted to "%d. ", but could be "" or "- ". 
Not necessarily the best method, but it was a quick way to solve the problem.

I don't mind if the default stays, as long as I can easily override it. However I do think its a legacy decision that made sense for  'show_line_diagnostics' but is less sensible for 'show_position_diagnostics' that is a more sensible alternative for "hover" style help.

If you consider other tools and IDEs very few would number each message like this when hovering over an underlined error, and you'd very rarely expect there to be more than one error.  The shift and bullet point/numbre of the errors is almost a desirable change in behaviour to indicate to the user this is one of those rare events where an underlined problem has more than one issue. (As an aside, bullet points are more visual appealing than numbers in this scenario plus don't suffer from alignment issues with 10+.  If you have so many errors for an individual position that you can't count them, you probably don't need to count them and have bigger issues anyway)

When trying to customise neovim to behave like a traditional IDE with 'hover to see error' it does look a bit silly with the number:



![Untitled](https://user-images.githubusercontent.com/6404304/141668139-4404e745-7280-4e94-92a9-e071d13db4c3.png)

**Comment by gpanders** [comment]
I'm not opposed to a `number` option that has the same values as `source`; namely "always" or "if_many" (or `false` to disable). It makes sense to me to hide the numbers when using position diagnostics as there will rarely be more than one.

This doesn't give you the ability to change the format of the enumeration though (e.g. using bullets instead of numbers). But you could use `false` to disable numbering and then add whatever prefix you wanted to manually after calling `open_float`.

**Comment by smhc** [comment]
> It makes sense to me to hide the numbers when using position diagnostics as there will rarely be more than one.

agreed - and I wonder if it might even make sense to limit the diagnostics to a single 'top priority' value in this scenario. AFAIK we have 'severity sort' already. It seems like a useful convenience function for 'CursorHold' to do:

- show_position_diagnostics(
   - opt.suppress number prefix
   - opt.sort by severity
   - opt.limit to 1 result) 

Or at least make it easier for a user to configure this. I realise this is getting into the custom config/plugin grey area however.

**Comment by mjlbach** [comment]
> agreed - and I wonder if it might even make sense to limit the diagnostics to a single 'top priority' value in this scenario. 

Huge -1 from me, I don't like the idea of "hiding" things from users.

I'm also concerned about option bloat. If a user really wants to tailor these options so specificially and cannot do so by overriding some element of the vim.diagnostic submodule directly, than I think we need to refactor it such that that is possible similar to how it was when the module lived under vim.lsp.diagnostic.

**Comment by smhc** [comment]
I guess it is along the lines of the format function for virtual text to truncate it to something more practical from a UI perspective. Long/lots of errors are already effectively hidden with virtual text as it extends off screen. But the user generally only cares that there is a problem and what the top priority problem is - which they fix before addressing the next one that bubbles up if any. Getting a list of 'all problems' is best addressed by other UI actions that populate qf list etc rather than 'tooltips' that are there to just indicate problems rather than being a detailed report. 

Given there is a 'format' and a 'severity sort' I would think a 'limit' would fall in this same category and address problems with virtual text too.

Anyway - I don't mind too much, with 'position diagnostics' there should only be one error anyway, or I may have to write my own handler.

**Comment by gpanders** [comment]
Closed by #16321.
