### ISSUE TITLE
End-of-line does not work ($)

### ISSUE THREAD

**Issue by f-squirrel** [neovim/neovim#16302]
### Neovim version (nvim -v)

NVIM v0.5.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 20.04

### Terminal name/version

gnome-terminal, alacritty

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

* Create a new file with some content
* Open it in the following way:
```
nvim --clean foo.txt
```
* Delete content until the end of a line:
```
dt$
```

Note:
* I do not have vim on the machine but it is a very old functionality so I expect it to work there.
* The command used to work for nvim 0.4.x.

### Expected behavior

The command `dt$` shall delete content from the current cursor's position till the end of a line.

### Actual behavior

Nothing happens, the same for yank, etc.

**Comment by mjlbach** [comment]
You're looking for d$ I assume, neovim is consistent with vim.

**Comment by clason** [comment]
> Vim (not Nvim) behaves the same?

> no

Did you actually test? 

`$` is a motion, not an actual character, so what you want is `d$`(and friends).

**Comment by f-squirrel** [comment]
@clason @mjlbach sorry guys for bothering, my bad.
