### ISSUE TITLE
Neovim deletes itself

### ISSUE THREAD

**Issue by tarsobcaldas** [neovim/neovim#16303]
### Neovim version (nvim -v)

0.5.1 and 0.6.0

### Vim (not Nvim) behaves the same?

not yet, at least

### Operating system/version

Windows 11

### Terminal name/version

Windows Termianl

### $TERM environment variable

-

### Installation

Chocolatey, then the Git Repository

### How to reproduce the issue

Don't know how to reproduce

### Expected behavior

-

### Actual behavior

I'm new to Vim/Neovim and I'm taking the firsts steps on the editor, but for some unknown reason the nvim.exe binary just deleted itself from the folder three times.

The first time I installed via 

``` 
choco install neovim
```
 and it was working fine, but suddenly the app closed (was using via Windows Terminal, and the tab just closed) and I couldn't start it again, getting
```
The term 'nvim' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Then I downloaded this repository's last build, but when I tried to unpack the `.zip` file in the same folder, I got
```
 Access to the path 'C:\tools\Neovim\bin\nvim.exe' is denied.
```

So I tried unpacking it in a different folder, and I worked fine for a while, but when installing the nvim perl plugin via `cpan`, it happened again, the exact same thing.

Again, a unpacked the files on a different folder and tried using it again, this time avoiding the perl plugin, but when editing a file on another directory, it happened a third time, so I decided to post this issue.

Did anyone have the same problem or have a clue of what might be happening?

**Comment by clason** [comment]
I'm sorry, but that's impossible to reproduce; in any case, this sounds like an issue with the Windows distribution and not Neovim itself. For "anybody else have this problem" questions, please ask on https://app.element.io/#/room/#neovim:matrix.org.
