### ISSUE TITLE
bad characters

### ISSUE THREAD

**Issue by echoface** [neovim/neovim#16319]
### Neovim version (nvim -v)

v0.5.1

### Vim (not Nvim) behaves the same?

no, vim 8 is ok

### Operating system/version

mac os 1.15

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

binary package

### How to reproduce the issue

after install nvim 0.5.1 relase binary package for macos, test golang/c++ lsp config powered by gopls/clangd; both will occur bad character;

### Expected behavior

no bad character

### Actual behavior

![image](https://user-images.githubusercontent.com/10153981/141686555-29646f42-dc70-497a-811d-b7ce862858ba.png)
![image](https://user-images.githubusercontent.com/10153981/141686792-bcfce520-ef34-4363-939c-c412653566f4.png)
![image](https://user-images.githubusercontent.com/10153981/141686869-e62f5964-a1ee-4d55-9f98-b2a936762879.png)

**Comment by zeertzjq** [comment]
Can you explain your steps to reproduce in more details?

**Comment by echoface** [comment]
after testing step by step, it seems lsp error; 
now focus on follow config:
clangd version 12.0/13.0 both

```lua
require('lspconfig').clangd.setup({})  -- can produce bug

--[[   **follow also has problem
-- Enable some language servers with the additional completion capabilities offered by nvim-cmp
-- local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
local servers = { 'clangd', 'gopls', 'pyright'}
local nvim_lsp = require('lspconfig')
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    -- capabilities = capabilities,
  }
end
--]]
```

how can debug this, or is there any where debug buildin lsp client?

**Comment by echoface** [comment]
i will have test with minimal configure tomorrow.

**Comment by echoface** [comment]
![image](https://user-images.githubusercontent.com/10153981/141901251-0424b2db-41c9-4661-a926-1a633f5bbe49.png)
find out and resolved, it is a bug caused by [lspsaga](https://github.com/glepnir/lspsaga.nvim)，seems this plugin not compatible with neovim version 0.5.1

**Comment by zeertzjq** [comment]
It is more likely a missing font.
