### ISSUE TITLE
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp.lua:863: RPC[Error] code_name = InvalidRequest, message = "expected rootUri"

### ISSUE THREAD

**Issue by OnionHat** [neovim/neovim#16329]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+581-g8f984dc1f

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

5.14.16-arch1-1

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

xterm-256color

### Installation

Arch User Repository::

### How to reproduce the issue

- Using ccls with lsp: `require('lspconfig').ccls.setup {}`
- Opening a .c or .cpp ( will not happen if you open a .h file )

### Expected behavior

Not getting this error. Changing ccls to clangs makes the error not appear anymore. 

### Actual behavior

```vim
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp.lua:863: RPC[Error] code_name = InvalidRequest, message = "expected rootUri"
stack traceback:
        [C]: in function 'assert'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:863: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

**Comment by mjlbach** [comment]
This is a bug in lspconfig. 

https://github.com/neovim/nvim-lspconfig/blob/2589549ed16a605cd52f8c8d55aa00d413956834/lua/lspconfig/ccls.lua#L9

ccls does not accept null root directory (apparently)

**Comment by mjlbach** [comment]
fixed in https://github.com/neovim/nvim-lspconfig/pull/1429/files
