### ISSUE TITLE
Using Neovim changes Konsole cursor type

### ISSUE THREAD

**Issue by JohannesGaessler** [neovim/neovim#16320]
### Neovim version (nvim -v)

v0.6.0-dev+73-g192adfe99

### Vim (not Nvim) behaves the same?

No, bug occurs in Neovim only

### Operating system/version

Manjaro Linux 21.1.6

### Terminal name/version

Konsole 21.08.2

### $TERM environment variable

xterm-256color

### Installation

AUR

### How to reproduce the issue

* Change Konsole Cursor to I-Beam by going to *Settings -> Edit Current Profile... -> Appearance -> Cursor -> I-Beam*
* `nvim --clean`
* `:q`

### Expected behavior

Cursor reverts to I-Beam when exiting Neovim.

### Actual behavior

Cursor reverts to block (the default cursor) when exiting Neovim.

**Comment by zeertzjq** [comment]
What shell are you using?

**Comment by JohannesGaessler** [comment]
I'm using zsh 5.8 (x86_64-pc-linux-gnu).
With bash 5.1.8(1)-release (x86_64-pc-linux-gnu) I get the same bug.

**Comment by zeertzjq** [comment]
I can reproduce this.

**Comment by erw7** [comment]
The only thing neovim can do to restore the cursor style at the end is to output `Se`. As you can see in `tput Se`, `Se` cannot restore the cursor style of a konsole profile.

See also https://github.com/neovim/neovim/wiki/FAQ#cursor-style-isnt-restored-after-exiting-or-suspending-and-resuming-nvim
