### ISSUE TITLE
vim.tabpage.valid is different from vim during TabClosed autocmd

### ISSUE THREAD

**Issue by puremourning** [neovim/neovim#16327]
### Neovim version (nvim -v)

NVIM v0.5.1

### Vim (not Nvim) behaves the same?

no, vim 8.2.3550

### Operating system/version

macOS Montery

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

`nvim --clean -S test_tabclose.vim`

`test_tabclose.vim`:

```viml

function! s:TabClosed() abort
  echom 'The tab is' py3eval( 'the_tab.valid' ) ? 'valid' : 'invalid'
endfunction

tabnew
py3 << EOF
import vim
the_tab = vim.current.tabpage
EOF

augroup Test
  au!
  autocmd TabClosed * call s:TabClosed()
augroup END

tabclose

```

### Expected behavior

Prints "The tab is invalid"

This behaviour is usful as it's pretty much the only way to determine which tab was closed in the TabClosed auto command.

See for example: https://github.com/puremourning/vimspector/pull/488 ; this fix works in vim, but not neovim.

### Actual behavior

Prints "The tab is valid".

**Comment by clason** [comment]
This prints `The tab is valid` for me on master.

**Comment by puremourning** [comment]
> This prints `The tab is valid` for me on master.

I know, that's what I'm claiming is incorrect - it should say "invalid"

**Comment by clason** [comment]
Oops, sorry, I misread that. It means we're missing a relevant patch, I suspect.

**Comment by zeertzjq** [comment]
Can't you pass `expand("<afile>")` to Python?

**Comment by puremourning** [comment]
Sorry if it wasn't clear - I should explain why (there's no background section in the template): In vimspector I'm trying to do some cleanup when the users closes the tabpage that vimspector stuck its UI in. In order to do this, I check the `.valid` on the python `tabpage` object for the tab that vimspector created in the `TabClosed` autocmd. This is about the only "reliable" way to determine which tab was closed in vim, as the python window/tabpage objects are updated by vim synchronously and then TabClosed is triggered. However, in neovim, the objects are not invalidated.

**Comment by puremourning** [comment]
> Can't you pass `expand("<afile>")` to Python?

how does that help? it returns the name of the current buffer at the time the auto command triggers, right ? I don't see how that can help.

**Comment by zeertzjq** [comment]
> it returns the name of the current buffer at the time the auto command triggers, right ?

No. It returns the tab number.

**Comment by puremourning** [comment]
> > it returns the name of the current buffer at the time the auto command triggers, right ?
> 
> No. It returns the tab number.

oh, only in neovim though, so this issue is still relevant.

**Comment by puremourning** [comment]
Let's just put this down to "Stuff that's different between vim and neovim, particularly in the Python API"
