### ISSUE TITLE
Home and end keys dont work

### ISSUE THREAD

**Issue by Unknown-User2** [neovim/neovim#16344]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

gentoo kernel version 5.10.74

### Terminal name/version

st 0.8.4

### $TERM environment variable

xterm-256color

### Installation

portage

### How to reproduce the issue

I don't know it just doesn't work for me

### Expected behavior

The cursor will got to the start of line when pressing home and go to the end of the line when pressing end

### Actual behavior

The cursor just stays where it is

**Comment by jdhao** [comment]
This is likely to be an issue with your terminal or shell. You can ask vim-related questions on https://vi.stackexchange.com/.

Inside nvim, in insert mode, press `Ctrl-v` and then press `HOME` or `END`, what do you get?

**Comment by zeertzjq** [comment]
Do you have libtermkey and unibilium installed?

**Comment by zeertzjq** [comment]
It can also be helpful if you can provide your libtermkey and unibilium versions.

**Comment by Unknown-User2** [comment]
@jdhao nothing happens
@zeertzjq my libtermkey version is 0.22 from portage and unibilium 2.1.0 from portage

**Comment by Unknown-User2** [comment]
home and end work when I'm using tmux and running nvim in it

**Comment by zeertzjq** [comment]
`export TERM=st-256color` in st should solve your problem.

**Comment by Unknown-User2** [comment]
that fixed it thanks
