### ISSUE TITLE
fnamemodify with empty modifiers always returns empty string

### ISSUE THREAD

**Issue by kuuote** [neovim/neovim#16367]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+600-gf71be1f87

### Vim (not Nvim) behaves the same?

no, vim 8.2.3623

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.9.0 (fed349aa)

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

nvim --clean
:echo fnamemodify('/bin/bash', '')

### Expected behavior

Display `/bin/bash`.

### Actual behavior

Won't display anything.

**Comment by clason** [comment]
You didn't answer whether vim behaves the same; please test and edit the issue report accordingly.

**Comment by kuuote** [comment]
Sorry, rewrite it.

**Comment by kuuote** [comment]
In my research this behavior is reproduce since `https://github.com/neovim/neovim/commit/1dbbaf89bf5d3bcd1edac3af9938c2e2dd18f816`

**Comment by clason** [comment]
Which means we're missing the fixup from the follow-up patch https://github.com/vim/vim/commit/c530852315517a44354edbbd6c3375355bbec37e

**Comment by zeertzjq** [comment]
<https://github.com/neovim/neovim/commit/1dbbaf89bf5d3bcd1edac3af9938c2e2dd18f816> came after that,

**Comment by clason** [comment]
I don't understand, then -- the port was done as part of https://github.com/neovim/neovim/commit/3026a5f41db83ff3af83dd9064461c4c15eaed64

How did our implementation diverge from upstream?

**Comment by clason** [comment]
Ah, I see, https://github.com/neovim/neovim/commit/1dbbaf89bf5d3bcd1edac3af9938c2e2dd18f816 was faulty. I'll make a fixup PR.
