### ISSUE TITLE
Certain key mapping not working under tmux

### ISSUE THREAD

**Issue by yanhao-li** [neovim/neovim#16366]
### Neovim version (nvim -v)

0.5.1 commit 0159e4d

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

macOS 11.6, Debian 11

### Terminal name/version

iTerm2 3.4.12

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

1. `nvim --clean`
2. `:set hlsearch`
3. Add some text and search with `/{keyword}`
4. `:nnoremap <esc><esc> :noh<CR>`

Behavior:  Press `Esc` twice **CAN** clear the search highlight.

---

1. `tmux`
2. `nvim --clean`
3. `:set hlsearch`
4. Add some text and search with `/{keyword}`
5. `:nnoremap <esc><esc> :noh<CR>`

Behavior:  Press `Esc` twice **CANNOT** clear the search highlight.

---

1. `tmux`
2. `vim --clean`
3. `:set hlsearch`
4. Add some text and search with `/{keyword}`
5. `:nnoremap <esc><esc> :noh<CR>`

Behavior:  Press `Esc` twice **CAN** clear the search highlight.

### Expected behavior

Expected the key-binding have consistent behavior with vim8

### Actual behavior

All the other mappings are working fine
This certain `:nnoremap <esc><esc> :noh<CR>` key mapping does not work under tmux.

**Comment by clason** [comment]
Note that before Neovim 0.6, `--clean` does not have the same behavior as in Vim (it will not load any builtin plugins). Can you try again with the latest nightly?

**Comment by zeertzjq** [comment]
<https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed>

**Comment by yanhao-li** [comment]
@clason Confirmed nightly solved the problem.
@zeertzjq Exactly the issue that I came across.
Thank you both, closing this issue.

**Comment by zeertzjq** [comment]
Oh, this is actually is duplicate of #15869
