### ISSUE TITLE
Comments not visible in cursor line with `slate` colorscheme and `cursorline` set

### ISSUE THREAD

**Issue by otommod** [neovim/neovim#16365]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

probably? didn't check

### Operating system/version

Arch Linux

### Terminal name/version

foot 1.10

### $TERM environment variable

foot

### Installation

system package manager

### How to reproduce the issue

nvim --clean your-favorite-source-file.py
:set termguicolors cursorline
:colo slate
:syntax on

### Expected behavior

A comment should be visible even with the cursor on top of it

### Actual behavior

It is not.  `slate` uses `grey40` as hl-Comment `guifg` which happens to be the default `guibg` of hl-CursorLine

**Comment by dundargoc** [comment]
> Vim (not Nvim) behaves the same?
probably? didn't check

Well, please do. The questions are there for a reason and help us pinpoint the problem faster.

**Comment by zeertzjq** [comment]
I just tested. Vim behaves the same.

**Comment by zeertzjq** [comment]
The slate theme hasn't been updated since Vim 7.2. Maybe it is unmaintained?

**Comment by zeertzjq** [comment]
Anyway Neovim doesn't maintain this theme. You can try to contact the maintainer of the theme as shown at the top of <https://github.com/vim/vim/blob/master/runtime/colors/slate.vim>.

**Comment by chrisbra** [comment]
Note: There is an effort to redo and improve the distributed colorschemes: https://github.com/vim/colorschemes/ 

You may want to test those. Any help and feedback is appreciated.
