### ISSUE TITLE
Got error when execute `checkhealth` in neovim nightly

### ISSUE THREAD

**Issue by Alienover** [neovim/neovim#16374]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+604-g725cbe7d4 Build type: RelWithDebInfo

### Vim (not Nvim) behaves the same?

Nope

### Operating system/version

macOS 12.0.1

### Terminal name/version

kitty

### $TERM environment variable

tmux-256color

### Installation

Download from the github release page

### How to reproduce the issue

1. run `nvim` from shell
2. execute `:checkhealth`

### Expected behavior

![image](https://user-images.githubusercontent.com/12182069/142718266-970bc7a8-fdef-4aae-ae70-ec39e41bf163.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/12182069/142718068-2ac0bd1f-c276-4ccd-8a7b-891d1f081800.png)

**Comment by zeertzjq** [comment]
Can you give more details about how you installed Nvim?

**Comment by Alienover** [comment]
1. Download the `nvim-macos.tar.gz` from https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz.
2. `tar xzf nvim-macos.tar.gz`
3. And then soft link `nvim-macos/bin/nvim` to `/bin/local/bin/nvim`

Is that any help?

**Comment by zeertzjq** [comment]
What does `:echo $VIMRUNTIME` print in Nvim?

**Comment by erw7** [comment]
The reason seems to be that some plugins have empty healthcheck results. I have created a PR(#16375) to check if valid results are returned on the neovim side. @Alienover #16375 solves the problem?

Essentially, it's a problem with the healthcheck function of plugin, so that needs to be fixed.

**Comment by Alienover** [comment]
@erw7 FYI, the health check works fine in v5.1 with the same config and plugins. 
And, How can I do the test to see whether #16375 solves the problem?

**Comment by zeertzjq** [comment]
You can download artifacts.

**Comment by Alienover** [comment]
@zeertzjq  Still no idea. Can you give more details about it? Or just paste the link here?

**Comment by zeertzjq** [comment]
Since that PR only changes one file, you can just download <https://raw.githubusercontent.com/erw7/neovim/fix-health-check/runtime/autoload/health.vim>, and replace `nvim-macos/runtime/autoload/health.vim` with it.

**Comment by Alienover** [comment]
![image](https://user-images.githubusercontent.com/12182069/142721546-c9418ee1-0975-4e77-a733-3b73655fcd00.png)
Looks like it's the `lspconfig`. (cc @erw7 )

@zeertzjq Thx for your instructions.

**Comment by erw7** [comment]
This is a problem with nvim-lspconfig (neovim/nvim-lspconfig#1460).
