### ISSUE TITLE
`xcwd` returns `/` when provider#clipboard tries to set the clipboard

### ISSUE THREAD

**Issue by mcastorina** [neovim/neovim#16372]
### Neovim version (nvim -v)

NVIM v0.5.1

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

Arch linux 5.15.2-arch1-1

### Terminal name/version

rxvt-unicode v9.26

### $TERM environment variable

rxvt-unicode-256color

### Installation

system package manager (community/neovim)

### How to reproduce the issue
```
# note: xcwd is https://github.com/schischi/xcwd

:call provider#clipboard#Call('set', ['', '', '+'])
:!xcwd
```
### Expected behavior

Outputs the current working directory of neovim.

### Actual behavior

Outputs `/`.

**Comment by mcastorina** [comment]
This could actually be an `xcwd` bug, but since this doesn't happen with `vim` I'm opening the issue here. Additionally, running `xclip -quiet -i -selection clipboard` in a terminal works as expected with `xcwd`.

**Comment by zeertzjq** [comment]
I cannot reproduce this with either Neovim v0.5.1 or HEAD.

**Comment by mcastorina** [comment]
I'm using i3 version 4.20.1 (2021-11-03)

**Comment by zeertzjq** [comment]
Even with i3 and rxvt-unicode I cannot reproduce this.

**Comment by mcastorina** [comment]
Hm.. I have both `xclip` and `xsel` instealled. When I uninstall `xclip` it works fine (I also notice there are no child processes hanging from `neovim`).

xclip v0.13

**Comment by mcastorina** [comment]
Okay I just noticed something really strange.

If I don't open another terminal, the output of `!xcwd` is correct. When I open another terminal, the output of `!xcwd` becomes `/`. If I close the new terminal, the output goes back to being correct.

My i3 config has the following for opening a new terminal.
```
bindsym $alt+Return exec --no-startup-id urxvt -cd "`xcwd`"
```

**Comment by zeertzjq** [comment]
I'm not very familiar i3, so it is a bit hard for me to reproduce this.

**Comment by mcastorina** [comment]
Thanks for trying.. I have confirmed on my system that the `cwd` of the `xclip` that neovim spawns is indeed `/` by doing:

1. Run `:call provider#clipboard#Call('set', ['', '', '+'])` in neovim
2. In a separate shell, `ls` the `cwd` symlink of the `xclip` process: `ls -l /proc/$(pidof xclip)/cwd`

I'm not sure why it would do this though. Maybe I'm missing an env variable?

**Comment by zeertzjq** [comment]
Oh...
<https://github.com/neovim/neovim/blob/120a88163078e61b272e9629138642bc5df80e4a/runtime/autoload/provider/clipboard.vim#L201>

**Comment by mcastorina** [comment]
Oh shoot. Well at least it's intentional.

Do you know if it can be made configurable? It's really frustrating trying to open a new terminal and it opens in the root directory.

**Comment by zeertzjq** [comment]
The easiest workaround I can think of is to manually edit `/usr/share/nvim/runtime/autoload/provider/clipboard.vim`, search for that line, and remove it...

**Comment by zeertzjq** [comment]
Does `:let g:clipboard = { 'cache_enabled': 0 }` solve the problem?

**Comment by zeertzjq** [comment]
<https://github.com/jhunt/xclipd> maybe prevent hanging `xclip` process.

**Comment by mcastorina** [comment]
Thanks for the suggestion. It does in fact prevent hanging, however `xclipd` breaks copying and pasting of images via `xclip -t image/png`.

**Comment by zeertzjq** [comment]
Oh, removing `-quiet` may solve the problem.
```vim
let g:clipboard = {
\   'copy': {
\      '+': ['xclip', '-i', '-selection', 'clipboard'],
\      '*': ['xclip', '-i', '-selection', 'primary'],
\    },
\   'paste': {
\      '+': ['xclip', '-o', '-selection', 'clipboard'],
\      '*': ['xclip', '-o', '-selection', 'primary'],
\   },
\ }
```

**Comment by mcastorina** [comment]
Removing `-quiet` works great, thank you!

**Comment by justinmk** [comment]
What is expected here? Processes may briefly set their own CWD, that's common.
