### ISSUE TITLE
Rename map.c and map.h

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#16385]
I'm looking into [Vim patch 8.1.1785](https://github.com/vim/vim/commit/b66bab381c8ba71fd6e92327d1d34c6f8a65f2a7) recently. That patch introduces a `map.c` and a `map.h` file to Vim. Those two files are related to `:map` command in Vim. Nvim also has `map.c` and `map.h`, but they are data structure wrappers. Therefore, I am proposing renaming Nvim's `map.c` and `map.h` to some other name to make the porting of that patch and future patches to Vim's `map.c` easier. I don't know much about those two files, so I cannot think of a new name.

**Comment by bfredl** [comment]
Can't we call the new one `keymap.c` ? We don't always follow vim name of files anyway.

**Comment by zeertzjq** [comment]
I have previously thought about that. Then I thought that will be a bit confusing.

**Comment by zeertzjq** [comment]
`mapping.c` for the new one may be fine.

**Comment by clason** [comment]
I also prefer `keymap.c` -- makes much more explicit what it is about.

**Comment by zeertzjq** [comment]
`'keymap'` has another meaning.

**Comment by clason** [comment]
Ah, `keymap.c` already exists. Well, I guess `mappings.c` it is, then...

**Comment by bfredl** [comment]
isn't the `keymap.c` already keymapping code we have broken out (but not vim, before that patch)? so would sense to add more stuff there?

**Comment by clason** [comment]
Looks like it's for handling special keys (`KEY_HOME` and friends)

**Comment by zeertzjq** [comment]
Those seem to be mostly for key encoding.

**Comment by bfredl** [comment]
yes, in vim those are in misc2.c but as we want to get rid of misc files, it seems reasonable to have them where they are most used, i e with keymapping logic?

**Comment by zeertzjq** [comment]
`keymap.h` is included by `vim.h`, so it should be for more low-level stuff. Vim `map.c` contains the definitions of many Ex commands.

**Comment by zeertzjq** [comment]
In Nvim, `keymap.h` is included by `vim.h`, so it should be for more low-level stuff. Vim's `map.c` contains the definitions of several mapping-related Ex commands.

**Comment by bfredl** [comment]
so `ex_map.c`, if the idea is we want to separate ex command layer from lower layer?

**Comment by zeertzjq** [comment]
Well, I think the purpose of that patch should be to separating defining mappings from character input handling.

**Comment by zeertzjq** [comment]
Oh, Nvim already has the precedence of `ex_session.c`, so `ex_map.c` makes sense.

**Comment by zeertzjq** [comment]
Nvim already has `ex_session.c` for session-related stuff, so `ex_map.c` kind of makes sense.
