### ISSUE TITLE
How to show Chinese character in Neovim's floating terminal?

### ISSUE THREAD

**Issue by nyngwang** [neovim/neovim#16400]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+605-g2bd8f2fb5

### Vim (not Nvim) behaves the same?

no, version 8.2.2671

### Operating system/version

macOS 12.0.1

### Terminal name/version

alacritty 0.9.0 (fed349a)

### $TERM environment variable

alacritty

### Installation

brew install neovim --HEAD

### How to reproduce the issue

Open neovim and run `git logs` on any repo. with Chinese commits logs.

### Expected behavior

If I run `:terminal` with `vim` then I got Chinese characters displayed correctly:

<img src="https://user-images.githubusercontent.com/24765272/142792538-c6171ed7-1dd9-4694-b49c-af0b5d156e70.png" width="400">

### Actual behavior

Open neovim and run `git logs` on any repo. with Chinese commits logs.

For example I saw this:

<img src="https://user-images.githubusercontent.com/24765272/142792099-0afa035e-bb66-42d6-9507-ff58808e65c3.png" width="400">

**Comment by zeertzjq** [comment]
Did you test with `nvim --clean`?

**Comment by nyngwang** [comment]
OK, I just found that one of the FAQs resolved my problem. Just add

```
export LC_ALL=zh_TW
export LANG=zh_TW
```

Ref.: https://github.com/neovim/neovim/issues/1858#issuecomment-70811623

**Comment by zeertzjq** [comment]
It just needs to be a UTF-8 locale. `en_US.UTF-8` should also work.
