### ISSUE TITLE
Could not find a valid tsserver version when using typescript-language-server@0.8.0

### ISSUE THREAD

**Issue by hood** [neovim/neovim#16413]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+622-gfd6df748

### Vim (not Nvim) behaves the same?

don't know

### Operating system/version

5.15.4-arch1-1

### Terminal name/version

tmux

### $TERM environment variable

screen-256color

### Installation

build from repo

### How to reproduce the issue

Install typescript-language-server v0.8.0 then open NeoVim in a TypeScript codebase, opening a TypeScript buffer.

### Expected behavior

Handling TypeScript buffers flawlessly.

### Actual behavior

Getting the following error:
```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp.lua:877: RPC[Error] code_name = InternalError, message
 = "Request initialize failed with message: Could not find a valid tsserver version. Exiting."
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:877: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

**Comment by clason** [comment]
Support for specific servers is handled by https://github.com/neovim/nvim-lspconfig, while usage questions should be asked on https://neovim.discourse.group.
