### ISSUE TITLE
winhighlight / winhl doesn't affect groups that are linked to the overridden one

### ISSUE THREAD

**Issue by oblitum** [neovim/neovim#16419]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

does not apply

### Operating system/version

Arch Linux

### Terminal name/version

xfce4-terminal 0.8.10

### $TERM environment variable

tmux-256color

### Installation

system package manager

### How to reproduce the issue

echo 'foo bar' > foo
nvim --clean ./foo
:set termguicolors
:hi clear Normal
:hi clear NonText
:hi clear Foo
:syntax keyword Foo foo
:hi Normal guifg=#ff0000 guibg=#000000
:hi NonText guifg=#00ff00 guibg=#000000
:hi link Foo Normal
:set winhl=Normal:NonText

### Expected behavior

In the last step, _I_ expect that all text ("foo bar") becomes green, because `NonText` is green, and it overrides `Normal` (due to `winhl`), so all `Normal` text (" bar") should be in green, but not just that, all text whose highlighting group _links_ to `Normal` ("foo" is `Foo`, which links to `Normal`) should all be in green as well.

### Actual behavior

The implementation of `winhighlight` currently doesn't seem to follow links and only applies to groups directly, that means that the `winhighlight` overrides does half of the job, and hence, makes " bar" green (because it's `Normal` text, which gets overridden) but keeps "foo" in red (which is `Foo` that links to `Normal`).

https://github.com/neoclide/coc.nvim/issues/1251

**Comment by zeertzjq** [comment]
Related: <https://github.com/neovim/neovim/issues/15379#issuecomment-907201125>. If this behavior is changed it will break that workaround.

**Comment by oblitum** [comment]
@zeertzjq heh, tbh, that workaround sounds like making a bug into a feature 😅

**Comment by bfredl** [comment]
This is documented behavior. Winhl applies to UI highlights (and in that case follow links) but not to syntax highlights. More flexible behaviors will be enabled by deprecating winhl and introducing namespaced highlights #13457 .

**Comment by oblitum** [comment]
`winhl` documentation is not clear at not supporting this. It states the highlighting pairs have to be built-in first, and any highlighting second. This is why the above works without any error message, because that's followed. Then docs states that only built-in's are supported, but a built-in is what is being overridden when setting `winhl`. If "supported" means not just that, but that links from built-in's to non-built-in's won't be followed, then it should be made clearer to avoid such confusion (that has span along two years with many experienced devs unable to spot the cause) from happening again.

**Comment by bfredl** [comment]
The absence of mentioning every single edge case is not a claim of actively supporting every non-mentioned imaginable edge case. The general issue has been discussed frequently, and the resolution is the new namespace mechanism (hopefully for 0.7).

**Comment by oblitum** [comment]
'Every single edge case" is an exaggeration, this doesn't resemble that. There's two main cases worth noticing, direct override and indirect (links). These are the main cases worth covering. Highlight links is also a very commonly used feature, so it's not edge at that either.

**Comment by bfredl** [comment]
Yes, and links, just as "direct override", are supported for UI highlights but not for syntax highlights. Just as documented. Minutiae of an interface everyone agrees to be too limited and obsolete is not worth discussing. Let's discuss the namespace interface we actually want to build moving forward instead.
