### ISSUE TITLE
Synchronized VT rendering

### ISSUE THREAD

**Issue by christianparpart** [neovim/neovim#16417]
### Feature description

We have a small spec and nice support-matrix rundown at this [Gist](https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036) that I'd like (Neo)VIm to implement.

Having tearing of editors over slow-ish SSH lines is a very prominent behavior that is known to be a problem for many years now (at least as far as Google search results are concerned ^^).

I'd like to see some kind of synchronized output support in Neovim.

Side node, it seems like (Neo)vim is sending out superfluous VT sequences per frame that can cause the screen to look like it's flickering. This is not a problem on local PTY connected to locally running processes, but over SSH it certainly may become one (depending on the link speed).

**Comment by christianparpart** [comment]
@clason I'm not so sure putting a ticket right after the creation and without commenting on it to the "zero-priority" trashcan isn't suggesting the best intentions. But let's see. :-)

**Comment by clason** [comment]
It's not a trash can, but it does not align with current development priorities of the core team. I.e., if you want this to happen, you need to drive the implementation.

**Comment by mjlbach** [comment]
Unplanned isn't 0 priority, it's a staging label that means it does not have an explicit milestoned release.

**Comment by clason** [comment]
> Unplanned isn't 0 priority, it's a staging label that means it does not have an explicit milestoned release.

You're thinking of "backlog" ;)

**Comment by bfredl** [comment]
Not to mention, it would be completely pointless to give this any priority before any terminal emulator implements it. (yes it is an chicken-and-egg problem, but anyone who really thinks we should be the first-mover can send us some actual code, just as @clason mentioned).

**Comment by bew** [comment]
Well, it's implemented in wezterm :)
https://github.com/wez/wezterm/issues/882

**Comment by christianparpart** [comment]
> Not to mention, it would be completely pointless to give this any priority before any terminal emulator implements it. 

You clearly clicked on the link I did provide. Because otherwise you would not have said that. Interesting. :)

**Comment by gpanders** [comment]
Implemented in https://github.com/neovim/neovim/pull/25871.
