### ISSUE TITLE
diagnostic: calling goto_next on last diagnostic focuses floating window

### ISSUE THREAD

**Issue by hinzp** [neovim/neovim#16425]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+624-ga2e5c2f7c

### Language server name/version

Debian clangd version 13.0.0-9

### Operating system/version

Debian

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: clangd: configuration checked.
  - INFO: vimls: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5402'
  - INFO: $COLORTERM='truecolor'
```

### Steps to reproduce using "nvim -u minimal_init.lua"

I am new to the LSP feature and do not know Lua but I think I found a small annoying bug. It occurs if you only have a single error in your program and you execute `:lua vim.lsp.diagnostic.goto_next()` twice. The second time your cursor focuses the diagnostic window which I think is not intended. You then have to close it with `wq`, you cannot just move to another line using for example the `k` or `j` because your cursor is stuck within that subwindow. I have made two screenshots. After executing `:lua vim.lsp.diagnostic.goto_next()` one time I arrive at the correct error position.
![grafik](https://user-images.githubusercontent.com/26443389/143288810-660f1cc9-9ec0-4a2f-a97f-2d0932f6ab86.png)
If I now execute `:lua vim.lsp.diagnostic.goto_next()` a second time, my cursor will be trapped within that diatnostics window:
![grafik](https://user-images.githubusercontent.com/26443389/143288655-8e236b0b-7ef3-4016-9da7-a8b0d2e2bf26.png)
Note that this problem only occurs when there is only one error, in case of multiple errors you would cycle through their positions as expected and the cursor will not enter the diagnostic subwindow.

### Expected behavior

The cursor should not enter the diagnostics subwindow.

### Actual behavior

Unfortunately the cursor enters the diagnostics subwindow.

**Comment by clason** [comment]
Yes, that is intended behavior: if you trigger a floating window twice, you enter it. You can leave it again using the standard commands, like `<c-w>w`.

**Comment by hinzp** [comment]
Thank you, it makes sense when you say this is a general property of floating windows. 

But when you attached the command `:lua vim.lsp.diagnostic.goto_next()` to keyboard shortcuts, it is annoying that when I want to cycle through errors, depending on whether there are other errors in the file, you either enter the floating window or jump to the next error position. From a user's perspective I think this is weird. It should just do nothing when there are no other errors and stay at that position without entering the floating window

**Comment by gpanders** [comment]
This isn’t a general floating window feature, it is specific to a subset of floating windows (those created with `vim.lsp.util.open_floating_preview`, which diagnostics uses). The idea is that a user may want to copy the text out of a diagnostic floating window. If this is not a feature you want, you can pass `focusable = false` to the options table of `goto_next` and `goto_prev`.

**Comment by mjlbach** [comment]
Maybe we should add some special logic to goto_next to prevent this from happening

**Comment by hinzp** [comment]
@gpanders I see the idea behind. But this argument is invalidated by the fact that a user still cannot copy text out of the diagnostic floating window when there are multiple errors:

If a user wants to enter the floating window using a double call of `goto_next` he can only do so if there are no further errors in the file, otherwise he will just jump to the other error position. So this way of entering the floating window makes no sense because its reliability is depending on other factors the end user might not be aware of (Are there more errors in the file?). Therefore I cannot understand your motivation for this behaviour. 

There should be a reliable way to enter the floating window and a reliable way to cycle through error positions without entering. In my opinion what you are advocating for is a mix of both where none can be done reliably.

Thank you for the hint, `focusable = false` I appreciate it. I will try it when I better understand Lua and option tables.

**Comment by muniter** [comment]
There are reliable ways to enter floating Windows, try `C-w w` you can read more about in `help: window-move-cursor`

**Comment by gpanders** [comment]
The behavior is intended for `open_float` itself, not the `goto` family of functions. I agree that it makes little sense for `goto_next`. As @mjlbach suggested, I’ll take a look at making this more intuitive for that use case.

> Therefore I cannot understand your motivation for this behaviour.

I do not use this feature, so I have no motivation. But it exists because someone else at some point wanted it, and there are users who depend on it (I know, because I’ve answered their bug reports too).

**Comment by hinzp** [comment]
Thank you for looking into this. Indeed, I agree that for `:lua vim.lsp.diagnostic.show_line_diagnostics()` it makes sense: If you want to copy the error message, just call it twice to enter the floating window. I was just complaining about this very specific case of `goto_next` (and also `goto_prev`). If other users depend on it, maybe one could describe a workaround for my case and maybe give a friendly hint in some readme file. 

As mentioned before I am a beginner with the lsp and lua topics but couldn't one just prepend the lua command in `:lua vim.lsp.diagnostic.goto_next()` with something that closes the diagnostics window just before `lsp.diagnostic.goto_next()` is called to avoid entering the diagnostic floating window? 
A hint in case you want to help me with this idea: I don't know whether it will be a problem but maybe one also needs to put the cursor forward by one character to avoid getting stuck at the same error position. I mean if you explicitly close the diagnostic window, maybe the next call will lead you to the exact same position and in order to make progress using `goto_next` one would need to push the cursor forward by one character. 

This would provide a dirty but useful hack for users like me in case you decide to keep the current behaviour.

**Comment by wookayin** [comment]
Regarding #16433,

>  The float can still be focused by calling open_float with scope = "cursor".

Why is this the case? I would still want to have the cursor **not automatically moved** while using `scope = cursor` (rather than line diagnostics). I also would want `focusable = true` so that I can move to the floating window if needed.

**Comment by gpanders** [comment]
The `focusable` option is a bit of a misnomer. The window itself is still "focusable", but `focusable = false` simply means that it will not focus the window if it already exists.

So `focusable = false` in the `goto_` functions means that the `goto_` functions will never move focus into the window themselves (which is as it should be), but if the window is already open you can still move your cursor into it with `open_float(0, {scope="cursor"})`.
