### ISSUE TITLE
[LSP] Diagnostic: failed to handle response from multiple lsp clients 

### ISSUE THREAD

**Issue by ray-x** [neovim/neovim#16428]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+615-gf45b2f313

### Vim (not Nvim) behaves the same?

no,  8.2.27

### Operating system/version

Macos 15

### Terminal name/version

kitty 

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

Issue was found when I have two lsp clients for a `go` project
1) lsp client   gopls  and efm both was installed and enabled for `go`
2) efm is setup to use golangci-lint as lint tool and send lint result
3) create a hello-world project and add some codes which is incorrect to gopls but ok to efm. E.g. 
```
time.Date(2020, 12, 24) 
// miss arguments to hour, min, sec, microsec
```

As golangci-lint is slower than gopls.  gopls will send a valid diagnostic result with 1 diagnostic error when I save the file.  And in about 1 second, golangci-lint will send another diagnostic response. The result is empty(no lint errro). I found that 2nd response will overwrite first response in diagnostic. So if I query with vim.diagnostic.get API I will get `0` error

### Expected behavior

lsp diagnostic should support mutiple lsp clients and if the result should be merged if they come from different clients.

### Actual behavior

Result from slower lsp client will overwrite the diagnostic from the faster client.

**Comment by gpanders** [comment]
> lsp diagnostic should support mutiple lsp clients and if the result should be merged if they come from different clients.

This should already be the case. You say that `vim.diagnostic.get` shows no errors. Can you provide the exact call you’re using? Can you also provide your gopls and efm configuration setup so that I can try and reproduce locally?

**Comment by clason** [comment]
Also, your version predates several recent bugfixes for diagnostics. Please try the latest commit on `master` and see if it still happens.

**Comment by ray-x** [comment]
Thanks for the suggestion. 
I updated the neovim and latest (0.6.x) works fine.
