### ISSUE TITLE
[count]J only join 2 lines in normal mode.

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [neovim/neovim#16438]
### Neovim version (nvim -v)

NVIM v0.5.1

### Vim (not Nvim) behaves the same?

no, vim 8.1.2292

### Operating system/version

macOS 10.15

### Terminal name/version

Alacritty 0.9.0

### $TERM environment variable

xterm-256color

### Installation

brew install

### How to reproduce the issue

nvim --noplugin txt.log
txt.log has 3 lines
press 3J , only join 2 lines.

### Expected behavior

join [count] lines

### Actual behavior

join only 2 lines

**Comment by zeertzjq** [comment]
I cannot reproduce this. What's the contents of `txt.log`?

**Comment by clason** [comment]
Also, please test a nightly with `--clean`.

**Comment by FinallyFinancialFreedom** [comment]
> Also, please test a nightly with `--clean`.

with --clean it works as wish. thank you, i will check through my nvim config.
