### ISSUE TITLE
Dynamic Font sizes

### ISSUE THREAD

**Issue by AusCyberman** [neovim/neovim#16445]
### Feature description

Obviously this would only be for gui, but the ability for dynamic font sizes to be a real thing supported would be really useful.
For example with neorg, or markdown.

**Comment by clason** [comment]
So a GUI would have to implement this, not Neovim (and, for example, https://github.com/yatli/fvim already does to some extent).

**Comment by AusCyberman** [comment]
Does it use highlights as where to change the size?

**Comment by clason** [comment]
You'll have to ask there.
