### ISSUE TITLE
Defaults: `scope = 'line'` in `vim.diagnostic.open_float`

### ISSUE THREAD

**Issue by cbarrete** [neovim/neovim#16453]
### Feature already in Vim?

Not applicable

### Feature description

I've moved from using `vim.lsp.show_line_diagnostics` to using `vim.diagnostic.open_float` since the former is now deprecated.
The default for `open_float` is to put all diagnostics in the floating window, as opposed to just the ones for the current line for `show_line_diagnostics`.

This is very easy to configure so it's not a big deal, but I'd argue that `scope = 'line'` would be a much better default:
1. that's what people like me, moving from `vim.lsp.show_line_diagnostics` would expect
2. I think that buffer-wide diagnostics make much more sense in the qflist/loclist. I fail to see why someone would want to cram possibly many warnings/erros in a floating window: it's harder to read, not actionable (you can't just jump to the error 300 lines further in the buffer from the floating window) and less subjectively less intuitive.
3. more importantly, it's much harder to find the diagnostics corresponding to the current line in a bloated floating window

I'll be happy to submit a PR if the core/LSP team agrees and otherwise interested in learning why `'buffer'` was made default.

Thanks!

**Comment by gpanders** [comment]
This sounds good to me. PR welcome.
