### ISSUE TITLE
truncate echo, nvim_echo to avoid prompt

### ISSUE THREAD

**Issue by LandonSchropp** [neovim/neovim#16462]
### Feature already in Vim?

No?

### Feature description

I tried [asking this](https://neovim.discourse.group/t/truncating-nvim-echo-to-avoid-prompt/1418) on the Discourse group, but I didn't get a response on there. Since I'm not sure if this is a feature in Neovim, I thought I'd post it here as a feature request.

I'm using `vim.api.nvim_echo` to output some text for a plugin I'm writing, and I'm trying to avoid the `Press ENTER or type command to continue` prompt.

Here's an example that triggers that prompt:

``` lua
:lua vim.api.nvim_echo({ { string.rep("A", 200) } }, false, {})
```

<img width="1536" alt="Screen Shot 2021-11-28 at 3 56 26 PM" src="https://user-images.githubusercontent.com/361591/143787643-fcc5edd3-0222-4a67-833d-9fc7ae7d433d.png">

I've tried using the window width to truncate the result. Even though the message now fits on one line, I'm still seeing the prompt.

``` lua
:lua vim.api.nvim_echo({ { string.sub(string.rep("A", 200), 1, vim.fn.winwidth(0) - 1) } }, false, {})
```

<img width="1521" alt="Screen Shot 2021-11-28 at 3 56 53 PM" src="https://user-images.githubusercontent.com/361591/143787650-a7ac1b6b-1753-4776-b846-3744ad4a808d.png">

In my Vim instance, it seems the magic number of `103` is what's needed to prevent this prompt from being displayed. Is there a way that I can programmatically determine what value is needed to truncate my string to avoid the prompt? Or, better yet, is there a way I can avoid the prompt entirely while using `vim.api.nvim_echo`?

**Comment by resolritter** [comment]
You can try to use `vim.api.nvim_eval("&columns")` which will get the width of the entire screen regardless of the active window.

Alternatively check for notification UIs, such as https://github.com/rcarriga/nvim-notify, for displaying the messages.

**Comment by zeertzjq** [comment]
> You can try to use `vim.api.nvim_eval("&columns")` which will get the width of the entire screen regardless of the active window.
> 
> Alternatively check for notification UIs, such as [rcarriga/nvim-notify](https://github.com/rcarriga/nvim-notify), for displaying the messages.

`vim.api.nvim_get_option('columns')` should be faster.

**Comment by LandonSchropp** [comment]
Thanks for the replies! `vim.api.nvim_eval("&columns")` returns `138`, which is the width of the screen, but doesn't seem to be the right width to avoid the `Press ENTER or type command to continue` prompt. Do you know of an alternative way to determine that?

**Comment by zeertzjq** [comment]
That is also dependent on whether `'showcmd'` and `'ruler'` is enabled.

**Comment by Shougo** [comment]
Hm.  You can use the PR instead.
https://github.com/neovim/neovim/pull/16383

**Comment by LandonSchropp** [comment]
Thanks for the replies! 

@zeertzjq That makes sense. Maybe this makes sense as a feature request then? Some way to echo messages without a prompt?

@Shougo I don't think I'm quite following. That PR looks like a new API that allows you to intercept messages and display them however you want. I'm looking to use the existing echo API, but without a user prompt. Am I misunderstanding that API?

**Comment by Shougo** [comment]
For existing API, nothing solution.  You should request the feature.
Internally, Vim/neovim calculate the prompt width.

**Comment by zeertzjq** [comment]
Actually this value can be obtained using FFI:
```lua
local ffi = require('ffi')
ffi.cdef('int sc_col;')
vim.api.nvim_echo({ { string.rep("A", ffi.C.sc_col - 1) } }, false, {})
```

The longest length is `ffi.C.sc_col - 1`.

**Comment by LandonSchropp** [comment]
@zeertzjq Awesome! I'll give this a shot. Thanks for the suggestion.

**Comment by justinmk** [comment]
> ffi.cdef('int sc_col;')

So we just need to expose `sc_col` ?

**Comment by zeertzjq** [comment]
Hmm, `v:echospace` can be used:
```lua
vim.api.nvim_echo({ { string.rep("A", vim.v.echospace) } }, false, {})
```
