### ISSUE TITLE
Add to FAQ: Debugging win32yank in WSL

### ISSUE THREAD

**Issue by JeremyTheocharis** [neovim/neovim#16464]
### Feature already in Vim?

No

### Feature description

https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl

If Neovim and win32yank does not work, execute the command :checkhealth to identify any issues (e.g., whether xclip is installed and takes precedent over win32yank, this happened to me)

**Comment by zeertzjq** [comment]
You can just edit the wiki.

**Comment by JeremyTheocharis** [comment]
lol, did not know I can just change it. Thank you!

**Comment by mohityadav7** [comment]
Hey @JeremyTheocharis, could you please let me know if you were able to fix the issue and what worked for you?
I'm having a similar issue. I had xclip installed which took precedence over win32yank. I check `:checkhealth` and it was showing xclip.

So, I tried after removing xclip (`sudo apt-get remove xclip`. I followed the [steps from FAQs](https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl) to symlink win32yank on wsl. 

Now neovim does not open up (blank vim screen is shown, seems like it is waiting for something in the background). However when I do `<C-c>`, it opens up. Now when I run `:checkhealth`, it keeps on running forever. But I can see the results after some time. Now it is using win32yank.

The clipboard seems working fine now. But currently, I'm having two problems:
- neovim does not start up correctly.
- `:checkhealth` does not finish and nvim becomes unusable without closing the terminal window.

How can I diagnose the issue and fix it?

**Comment by JeremyTheocharis** [comment]
As far as I remember I removed xclip and it solved the issue. Maybe you have a different plugin / vim snippet running that requires xclip?
