### ISSUE TITLE
Regarding xxd, vimdiff, and evim

### ISSUE THREAD

**Issue by Pyrohh** [neovim/neovim#1646]
I see that `runtime/doc/manpages` contains man pages for vimdiff, evim, and xxd, but none of these binaries seem to be built. I'm wondering if these man pages are going to be removed, or if their respective binaries will eventually be built by default. I ask because I'm unsure about the inclusion about a few of these.
- `xxd` seems like the byproduct of feature creep for it to be included with a text editor at all. Even if it is useful, I'm still unsure about its inclusion (probably because I've never used it). It'd be great if someone could chime in on its value over something like `xd`.
- Is there any particular need for evim anyways? It really confuses me why it was even included in vim in the first place. Why not just use nano?
- I don't see much reason for `vimdiff` to exist, let alone have its own man page. I say this because it's the same thing as `vim -d`, at least according to `:h vimdiff`:
```
1. Starting diff mode

The easiest way to start editing in diff mode is with the "vimdiff" command.
This starts Vim as usual, and additionally sets up for viewing the differences
between the arguments. >

	vimdiff file1 file2 [file3 [file4]]

This is equivalent to: >

	vim -d file1 file2 [file3 [file4]]
```
I'm not a fan of having all these symlinks (`viewdiff`, `gviewdiff`, `evim`, `vimdiff`, `rview`, etc.), especially since:
- Their one letter arguments are usually shorter, although not by much
- It introduces the possibility that people would falsely think that something like `vimdiff` is a separate binary, especially since it has a separate man page. I can understand having separate man pages for something like git, but vim doesn't have any subcommands with unique arguments, only arguments for `vim` (I think).

**Comment by Pyrohh** [comment]
After re-reading this thread, it seems like general consensus is that extra interfaces should be removed. Here's the interfaces (from `starting.txt`) which I'm referring to:
```
ex     vim -e      Start in Ex mode (see |Ex-mode|).               *ex*
exim   vim -E      Start in improved Ex mode (see |Ex-mode|).      *exim*
                       (normally not installed)
view   vim -R      Start in read-only mode (see |-R|).             *view*
gvim   vim -g      Start the GUI (see |gui|).                      *gvim*
gex    vim -eg     Start the GUI in Ex mode.                     *gex*
gview  vim -Rg     Start the GUI in read-only mode.              *gview*
rvim   vim -Z      Like "vim", but in restricted mode (see |-Z|)   *rvim*
rview  vim -RZ     Like "view", but in restricted mode.          *rview*
rgvim  vim -gZ     Like "gvim", but in restricted mode.          *rgvim*
rgview vim -RgZ    Like "gview", but in restricted mode.         *rgview*
```

The only one I'm not completely sure about removing is gvim. I think there's no need for it as you would just call the name of your UI frontend directly, like neovim-qt, but this is just conjecture.

**Comment by Pyrohh** [comment]
I forgot to mention the whole reason for that: would anyone object to a PR removing the interfaces above?

**Comment by fmoralesc** [comment]
I think the -g variants might go, but I'm not so sure about the others.
When discussing the removal of ex mode, it was settled that the command
line ex mode would be preserved.

Or do you mean to merely remove the aliases?

**Comment by Pyrohh** [comment]
Yes, only the aliases.

**Comment by fmoralesc** [comment]
Ah, I guess the consensus on that is as you thought. :+1:

**Comment by ZyX-I** [comment]
About `xxd`: you can consider removing it entirely for linux and using `hexdump` instead. You need to use format file with the following contents to have the output exactly matching `xxd` output:

```C
"%07.7_ax:" " " 1/1 "%02x" 1/1 "%02x" " " 1/1 "%02x" 1/1 "%02x" " " 1/1 "%02x" 1/1 "%02x" " " 1/1 "%02x" 1/1 "%02x" " " 1/1 "%02x" 1/1 "%02x" " " 1/1 "%02x" 1/1 "%02x" " " 1/1 "%02x" 1/1 "%02x" " " 1/1 "%02x" 1/1 "%02x"
"  " 16/1 "%_p"
"\n"
```

(note: I do not quite like lots of repeats on the first line, but failed to figure out alternative solution). I have `hexdump` in sys-apps/util-linux package alongside with such interesting (and basic) things like `mkfs`, `fsck`, `ionice`, `cal`.

**Comment by Pyrohh** [comment]
It looks like OS X [has hexdump too](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/hexdump.1.html), but it's from "BSD" (FreeBSD?) so I'm not sure the output will be the same, and I lack a machine with OS X to test.

**Comment by ZyX-I** [comment]
This means that you can make xxd binary either a shell script or an external windows-specific dependency bundled into an installer by a release script and remove from this repository entirely.

@Pyrohh It is said to support format files as well. I do not think there are going to be any differences.

**Comment by justinmk** [comment]
I think we can close this. There is still a bit of a question regarding xxd, but we can always dig up this issue when we get around to addressing that.

**Comment by Earnestly** [comment]
If only `hexdump` was even remotely comparable to `xxd`.  Sadly it seems `hexdump` is not capable of outputing a format like `xxd -b` and the format needed to emulate `xxd` itself is gross, even as a wrapper.

This is not to mention the other functions it had which I have used quite often such as generating character arrays in C.

This decision was probably made too hastily by people who have admitted no personal requirements/understanding.

However it would probably make more sense to package `xxd` as a separate tool given how useful it is compared to `hexdump`.

**Comment by justinmk** [comment]
> This decision was probably made too hastily by people who have admitted no personal requirements/understanding.

What decision? Only thing that was decided in this issue was to not install aliases that would conflict with Vim, and are redundant with `nvim` command-line flags. Nothing was decided about xxd, except that we cannot remove it: we must ship with it or depend on it in some fashion, though it is not yet clear how.

**Comment by ZyX-I** [comment]
By the way, there is another option which was not discussed: emulate `xxd` using VimL code. This is rather easy, though much slower then xxd. Other options: convert `xxd` into a C function available through `xxdump(lines[, format_args])` (e.g. `call setline(1, xxdump(readfile('/bin/sh', 'b'), {'values': 'hex', 'cols': 16, 'autoskip': 0, 'format': 'ascii', 'groupsize': 2, 'offset': 0})` (`'format'` is for a number of mutually exclusive switches like `-EBCDIC`, `-e`, `-include`, `-postscript`; `'values'` may be `hex`, `upperhex` and `bin`; `-seek` was removed as one can truncate `lines` instead)) and `xxparse(lines)`.

There is also an option to finally start using lua and port `xxd` to lua: parts of the #243 which execute lua code without parts that translate VimL may be ported for this purpose.

**Comment by justinmk** [comment]
> parts of the #243 which execute lua code without parts that translate VimL may be ported for this purpose.

That's a splendid idea.

**Comment by Earnestly** [comment]
And how does your version of xxd create binaries from a dump?

**Comment by ZyX-I** [comment]
@Earnestly What is the problem? `writefile()` works in case VimL or C variant is used (basically they are the same, just in case of viml variant `xxdump`/`xxparse` will be something like `xxd#dump`/`xxd#parse`). Lua has no problems with writing binary data to file.

If you ask how they *detect* the format, then this is simple: we do not have to be 100% compatible, so can simply add necessary information to the first, last or each line of the dump. Since there are not much variants to detect (basically we need only to tell it what byte order was used and whether format is binary; formats like `include` or `postscript` can be easily detected without additional information, other data regarding binary and hex formats does not need additional characters anywhere to be detected), this is just one character somewhere in the line, in the first line or in the last line. Though, of course, one may prefer having second argument to `xxparse`.

**Comment by Earnestly** [comment]
I'm talking about `xxd -r`, also I'm not particularly interested in detecting character encodings.

**Comment by ZyX-I** [comment]
@Earnestly Where have you seen detecting character encodings? In my variant you are supposed to select this when dumping, and dumping is supposed to result in something which makes detection possible when parsing back.

**Comment by Earnestly** [comment]
I've not seen detecting character encodings and I've never looked for it.

As for `xxd` I'm just simply going to package it as standalone instead as it is a useful tool even outside the context of an editor.  It's only ~700 lines of C and should probably be separate/standalone anyway.

**Comment by abonander** [comment]
Anyone running into this issue in 2019, you apparently need to have `vim` installed to use `xxd`, at least on Arch.

**Comment by xoores** [comment]
> Anyone running into this issue in 2019, you apparently need to have `vim` installed to use `xxd`, at least on Arch.

In 2022 on Gentoo too :shrug: Seems that I have to install Vim to get xxd...

**Comment by jamessan** [comment]
> In 2022 on Gentoo too shrug Seems that I have to install Vim to get xxd...

Then the Gentoo packager should split that into its own package, like I did for Debian ~6 years ago.
