### ISSUE TITLE
fix(lsp): do not attempt to index nil client in progress handler (#2)

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [neovim/neovim#16471]
### Neovim version (nvim -v)

0.6.0 & HEAD

### Language server name/version

2.5.0-dev sumneko lua

### Operating system/version

MacOS

### Steps to reproduce using "nvim -u minimal_init.lua"

--

### Actual behavior

```bash
LSP[id=1] client has shut down after sending the messageError executing vim.schedule lua callback: ...llar/neovim/0.6.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:465: method "window/workDoneProgress/create": either a result or an error must be sent to the server in response
stack traceback:
	[C]: in function 'error'
	...llar/neovim/0.6.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:465: in function <...llar/neovim/0.6.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:457>
LSP[id=1] client has shut down after sending the message⏎    
```
this error is printed to terminal when I open a lua file directly ex: `nvim init.lua`. Everything works fine, but this message is printed to terminal, which is visible after you (successfully xd) exit neovim.

REDDIT Discussion Post: https://www.reddit.com/r/neovim/comments/r4je4y/lsp_client_shut_down_message_printed_in_console/?utm_source=share&utm_medium=web2x&context=3

@mjlbach

**Comment by ViRu-ThE-ViRuS** [comment]
#16463 tried a fix, it changed the error being dumped, but issue still exists

**Comment by clason** [comment]
Sorry, without exact reproduction steps, we can't do anything.

(Also, Reddit is _not_ Discourse.)

**Comment by mjlbach** [comment]
I asked for this bug report :)
