### ISSUE TITLE
autowrite does not working when switching files using :next

### ISSUE THREAD

**Issue by robgura** [neovim/neovim#16470]
### Neovim version (nvim -v)

v0.6.0-dev+581-g8f984dc1f

### Vim (not Nvim) behaves the same?

No  Vi IMproved 8.0 (2016 Sep 12, compiled Jun 21 2019 04:10:35)

### Operating system/version

Debian Linux

### Terminal name/version

WezTerm

### $TERM environment variable

screen-256color

### Installation

build from repo

### How to reproduce the issue

`touch a b`
`nvim --clean a b`
`:set autowrite`
Modify file `a` (should be current buffer)
`:next`
`:q`

### Expected behavior

nvim should exit, since file `a` should have been written on `:next` and there are no changes to file `b`

from documentation for `autowrite`
> Write the contents of the file, if it has been modified, on each :next, :rewind, :last, :first, :previous, :stop, :suspend, :tag, :!, :make, CTRL-] and CTRL-^ command; ...

### Actual behavior

```
E37: No write since last change
E162: No write since last change for buffer "a"
```

**Comment by gpanders** [comment]
I suspect this is because `'hidden'` is enabled, though the docs for `'autowrite'` don't mention that.

**Comment by robgura** [comment]
Thanks, I'll give that a shot.

Is the intent to close this bug or are you thinking using `:set nohidden` a temporary work-around? 

I'm obviously not familiar with `hidden` since I haven't been using it, but it does seem to make `autowrite` pointless without it. In other words is it possible for `autowrite` to work without `nohidden`? 

Additionally it's inconsistent with `vim` and `nvim 0.5.0` behavior (I just verified). Just surprised at the change and curious if it will be "fixed" or if this is the way...

Thanks for the help.

**Comment by gpanders** [comment]
>Additionally it's inconsistent with vim and nvim 0.5.0 behavior (I just verified). Just surprised at the change and curious if it will be "fixed" or if this is the way...

Yes, `'hidden'` is set by default on current master (as well as the forthcoming 0.6 release), but not in Vim or Neovim 0.5.1 and earlier.

>Is the intent to close this bug or are you thinking using :set nohidden a temporary work-around?

I sent a patch upstream to modify the docs for `'autowrite'` to indicate that it has no effect for "hidden" buffers. I'll wait to see what Bram thinks about it. If it is indeed a bug then presumably he'll say so and a fix will arrive shortly after, but if it is intended behavior (which is what I suspect) then there's nothing left to do other than document it.
