### ISSUE TITLE
[RFC] LSP: do not attempt to spawn `server.cmd` on Windows

### ISSUE THREAD

**Issue by kylo252** [neovim/neovim#16484]
### Description

Attempting to start a server that was installed by `npm` will result in this error:

```console
start `vscode-html-language-server` failed: ENOENT: no such file or directory
```

### Background

Here's an excerpt  taken from nodejs' [docs](https://nodejs.org/api/child_process.html#spawning-bat-and-cmd-files-on-windows) to explain the problem and the solution: 
> ... On Windows, however, `.bat` and `.cmd` files are not executable on their own without a terminal, and therefore cannot be launched using [`child_process.execFile()`][]. When running on Windows, `.bat` and `.cmd` files can be  invoked using [`child_process.spawn()`][] with the `shell` option set, with [`child_process.exec()`][], or by spawning `cmd.exe` and passing the `.bat` or `.cmd` file as an argument (which is what the `shell` option and [`child_process.exec()`][] do)...

Furthermore, the same logic is applied for every `uv.spawn()` in the tests done by `luv`: 
```lua
    local input = "Hello World"
    local cmd, args, expectedOutput
    if isWindows then
      cmd = "cmd.exe"
      args = {"/c", "echo "..input}
      expectedOutput = input .. "\r\n"
    else
      cmd = "echo"
      args = {input}
      expectedOutput = input .. "\n"
    end
```
See: https://github.com/luvit/luv/blob/6561d5422322fe3b9c45c398255409fd958b63a3/tests/test-process.lua#L12-L22

### Suggestion

Add the same sort of handling to https://github.com/neovim/neovim/blob/d3585e0ec52ee828fd68c4bd3e3ec1c294e1f4a0/runtime/lua/vim/lsp/rpc.lua#L324

---

Related: https://github.com/neovim/nvim-lspconfig/issues/1500

**Comment by williamboman** [comment]
> On Windows, however, `.bat` and `.cmd` files are not executable on their own without a terminal, and therefore cannot be launched using [`child_process.execFile()`][].

I think this is a problem local to Node.js's libuv integration (and I also think their docs are by now outdated). I found https://github.com/nodejs/node/issues/15217 which provides some background I think. I believe with `UV_PROCESS_WINDOWS_HIDE` (added in `libuv v1.24.0`), this is now possible.

> Furthermore, the same logic is applied for every `uv.spawn()` in the tests done by `luv`:

From just looking at the tests, my understanding of the reason they're doing this is simply because there are no standard system commands on Windows that provide those primitives (`echo(1)`, `sleep(1)`, `cat(1)`), instead they're shell builtins.

**Comment by williamboman** [comment]
With ☝️  said, I have no idea which approach is preferable. If normalizing the spawn args in neovim's LSP RPC is still of interest, maybe [this function](https://github.com/nodejs/node/blob/94de738aa4ad1728242677b5ef1cf1a8504e7872/lib/child_process.js#L502-L654) in Node.js core will be good to study.

**Comment by mjlbach** [comment]
1.   we don’t use RFC labels like this
  2.  I don’t want to add “magic” in core that tries to handle npm specific quirks, user commands should be forwarded directly to uv spawn

________________________________
From: kylo252 ***@***.***>
Sent: Wednesday, December 1, 2021 8:32:14 AM
To: neovim/neovim ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [neovim/neovim] [RFC] LSP: do not attempt to spawn `server.cmd` on Windows (Issue #16484)


Feature already in Vim?

NA

Feature description
Description

Attempting to start a server that was installed by npm will result in this error:

start `vscode-html-language-server` failed: ENOENT: no such file or directory

Background

Here's an excerpt taken from nodejs' docs<https://nodejs.org/api/child_process.html#spawning-bat-and-cmd-files-on-windows> to explain the problem and the solution:

... On Windows, however, .bat and .cmd files are not executable on their own without a terminal, and therefore cannot be launched using [child_process.execFile()][]. When running on Windows, .bat and .cmd files can be invoked using [child_process.spawn()][] with the shell option set, with [child_process.exec()][], or by spawning cmd.exe and passing the .bat or .cmd file as an argument (which is what the shell option and [child_process.exec()][] do)...

Furthermore, the same logic is applied for every uv.spawn() in the tests done by luv:

    local input = "Hello World"
    local cmd, args, expectedOutput
    if isWindows then
      cmd = "cmd.exe"
      args = {"/c", "echo "..input}
      expectedOutput = input .. "\r\n"
    else
      cmd = "echo"
      args = {input}
      expectedOutput = input .. "\n"
    end

See: https://github.com/luvit/luv/blob/6561d5422322fe3b9c45c398255409fd958b63a3/tests/test-process.lua#L12-L22

Suggestion

Add the same sort of handling to https://github.com/neovim/neovim/blob/d3585e0ec52ee828fd68c4bd3e3ec1c294e1f4a0/runtime/lua/vim/lsp/rpc.lua#L324

________________________________

Related: neovim/nvim-lspconfig#1500<https://github.com/neovim/nvim-lspconfig/issues/1500>

**Comment by kylo252** [comment]
> 1. we don’t use RFC labels like this 

Sorry, I tried looking for new guidelines referencing the [RFC] tag for issues but couldn't find any, so I replicated the way it's done for one of the old ones.

> 2. I don’t want to add “magic” in core that tries to handle npm specific quirks, user commands should be forwarded directly to uv spawn

This is not `npm` specific. It just so happens that `npm` uses https://github.com/npm/cmd-shim#readme. As mentioned earlier, this is always applied in the tests from `luv`. Any other installer that creates a `server.cmd` will face the same issue.

**Comment by mjlbach** [comment]
Right now there is a 1:1 mapping of cmd -> uv.spawn arguments, I'm not going to change that.

**Comment by kylo252** [comment]
The ruby installer has the same behavior as well

```console
$ gem install solargraph
$ which solargraph
C:\Users\User\AppData\Roaming\gem\ruby\3.0.0\bin\solargraph.bat
```

**Comment by mjlbach** [comment]
https://github.com/neovim/neovim/issues/16484#issuecomment-983710876
