### ISSUE TITLE
Neovim 0.6.0 does not start on Windows 7

### ISSUE THREAD

**Issue by Jenyay** [neovim/neovim#16482]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 7 64 bit

### Terminal name/version

none

### $TERM environment variable

none

### Installation

https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip

### How to reproduce the issue

Run nvim.exe or nvim-qt.exe

### Expected behavior

Run application

### Actual behavior

```
---------------------------
nvim.exe - Entry Point Not Found
---------------------------
The procedure entry point GetHostNameW could not be located in the dynamic link library WS2_32.dll. 
---------------------------
OK   
---------------------------
```

There is no problem in neovim 0.5.1.

**Comment by clason** [comment]
Windows 7 support was dropped for 0.6.0 (since it was dropped by a dependency LibUV).

**Comment by LinArcX** [comment]
Some people still use windows 7.
Is there any workaround for that?

**Comment by clason** [comment]
Stay on Neovim 0.5.1 (if you use an old, no longer supported, OS, it's reasonable to expect that you'll have to use old, no longer supported, software, too).

That being said, there is a PR for libUV that (possibly) restores Win7 compatibility. If that is accepted and is included in a release, and we update our dependency next time, Neovim will build on Windows 7 again.

**Comment by AKDev21** [comment]
I'm also facing the same issue.

**Comment by theHamsta** [comment]
It should be possible to build Neovim from source with the older libuv version. But seriously: don't use a system that doesn't get security updated anymores!
