### ISSUE TITLE
unexpected prompt: Press ENTER or type command to continue

### ISSUE THREAD

**Issue by leenzhu** [neovim/neovim#16491]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

no, 8.1.1365

### Operating system/version

CentOS/7

### Terminal name/version

mintty/3.5.1

### $TERM environment variable

xterm

### Installation

appimage

### How to reproduce the issue

1. vim ~/.config/nvim/init.lua
2. add the following key map and save
   ```lua
   vim.api.nvim_set_keymap('n', '<leader>l', ':ls!<CR>:b<SPACE>', { noremap = true, silent = true })
   ```
3. restart nvim or source the init.lua
4. in normal mode, enter `<leader>l` 

### Expected behavior

don't diplay the `Press ENTER or type command to continue`.
![vim8](https://user-images.githubusercontent.com/25599632/144374926-147a7bd8-f421-441d-9977-d8ba5bdf39ee.png)

### Actual behavior

after following the reproduing steps,
1. you'll the prompt: `Press ENTER or type command to continue`
2. when press any key, you'll see `:b` already there
![scad_shot_2021_12_02_15_06_56](https://user-images.githubusercontent.com/25599632/144374511-34277761-35a1-43ac-9a97-d934bec897fb.png)

**Comment by zeertzjq** [comment]
Vim behaves the same with `:nnoremap <silent> <leader>l :ls!<CR>:b<SPACE>`.

**Comment by zeertzjq** [comment]
This is how `<silent>` works: the mapping doesn't change the command line, so the hit-enter prompt from `:ls` is still there. If you want it to disappear, remove `silent = true`.
