### ISSUE TITLE
Integrated settings sync

### ISSUE THREAD

**Issue by majkinetor** [neovim/neovim#16495]
### Feature already in Vim?

No

### Feature description

VSCode has this awesome [settings sync](https://code.visualstudio.com/docs/editor/settings-sync) integrated (it was first available via [extension](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)). It makes fascinating difference when onboarding on new machine - I just install vscode on any OS via package repository and login using Github credentials, then all my plugins and their settings are immediately downloaded and set.  This even works on web versions of code.

I was using Vim before vscode for years and the most problematic part for me was getting it to behave the same on any OS I use without any ceremony. I was keeping everything in git repository and loading hundreed or so of plugins using [NeoBundle](https://github.com/Shougo/neobundle.vim). While it worked and was relatively fast, it suffered from periodic hiccups, required git CLI installed and configured on each machine, and you could not set and forget it like with vscode sync which handles automatically updates, downloads and offer even merge conflicts resolution - I had to commit manually all the setting changes.

What are the chances that we have something identical in NeoVim ? I miss Vim a lot (vscode is great, but editing is light years away compared to vim style, even with emulators) and this is the only thing that keeps me from using it - once you have a freedom to have your editor set up in seconds on any machine like its your main one, you can't look back .

Sorry if this is something already discussed, I searched all tickets before creating this.

**Comment by mjlbach** [comment]
This seems like something you should implement on your system (Nextcloud, gnu stow, syncthing, etc.). I don't think neovim could or should maintain a server to sync user settings.

**Comment by clason** [comment]
There are (very early) discussions about more declarative configuration, but I don't think we will ever be able to provide a centralized "configuration/plugin" storage for users -- not least for lack of money to _pay_ for such an infrastructure. I'm afraid setting up your own git or cloud storage is the best you can hope for.

**Comment by clason** [comment]
I'll close this as it's far outside the scope of what this project can offer, but I'm happy to reopen if you edit your proposal to something more modest that is reasonably doable.

**Comment by majkinetor** [comment]
>  don't think neovim could or should maintain a server to sync user settings.

Server is not needed for this to work. Extension used Gist to store it. It could use whatever (local git, dropbox etc.)

> I'll close this as it's far outside the scope of what this project can offer, but I'm happy to reopen if you edit your proposal to something more modest that is reasonably doable.

Its not outside of the scope like I mentioned already.  "Reasonably doable" is not part of the problem but of solution.

**Comment by clason** [comment]
Well, then please edit your issue with a more detailed description of how this "serverless sync" should behave _for Neovim_. ("Just like VS Code" is not really helpful, since a) many people here do not use VS Code and b) VS Code is a very different piece of software.)

**Comment by zeertzjq** [comment]
Also, there are some plugins require their own extra installation steps.
