### ISSUE TITLE
"expected table, got function" as one of the specs passed to vim.validate

### ISSUE THREAD

**Issue by Gelio** [neovim/neovim#16501]
### Neovim version (nvim -v)

v0.7.0-dev+662-g73b35ef10

### Vim (not Nvim) behaves the same?

no, it does not have Lua

### Operating system/version

Ubuntu 20.04.3 LTS x86_64

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

Unpack `nvim-linux64.tar.gz` and use `stow` to install it in `/usr`

### How to reproduce the issue

I don't have any good reproduction steps.

After leaving neovim idle for some time (> 5 minutes, but I didn't find a pattern as to when it happens), the following error is shown:

```
E5108: Error executing lua ...m/nvim-linux64/share/nvim/runtime/lua/vim/diagnostic.lua:704: opt[6.9283908576005e-310]: expected table, got function
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:607: in function 'validate'
        ...m/nvim-linux64/share/nvim/runtime/lua/vim/diagnostic.lua:704: in function 'get'
        ...im-linux64/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:344: in function 'get_count'
        ...line.nvim/lua/lualine/components/diagnostics/sources.lua:8: in function <...line.nvim/lua/lualine/components/diagnostics/sources.lua:7>
        ...line.nvim/lua/lualine/components/diagnostics/sources.lua:58: in function 'get_diagnostics'
        ...lualine.nvim/lua/lualine/components/diagnostics/init.lua:72: in function 'update_status'
        ...pack/packer/start/lualine.nvim/lua/lualine/component.lua:175: in function 'draw'
        .../packer/start/lualine.nvim/lua/lualine/utils/section.lua:26: in function 'draw_section'
        ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:153: in function 'statusline'
        ...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:316: in function <...nvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:297>
Press ENTER or type command to continue
```

![image](https://user-images.githubusercontent.com/889383/144049865-8c640c43-f6f8-49da-87ba-3b08b0880e0a.png)

After that, lualine stops working and I am back to the default neovim statusline. As I investigated the function calls, looks like there is nothing in [lualine](https://github.com/nvim-lualine/lualine.nvim)'s code that is wrong here. The stacktrace mentions:

https://github.com/neovim/neovim/blob/04c7b550384b2246d37c1a893c0f858bc332cb8b/runtime/lua/vim/diagnostic.lua#L704-L707

and 

https://github.com/neovim/neovim/blob/04c7b550384b2246d37c1a893c0f858bc332cb8b/runtime/lua/vim/lsp/diagnostic.lua#L339-L344

If I'm not mistaken, `vim.validate` is failing on this line https://github.com/neovim/neovim/blob/04c7b550384b2246d37c1a893c0f858bc332cb8b/runtime/lua/vim/shared.lua#L570 (given the format of the error message), which means that there is some `spec` in the `opt` table passed to `vim.validate` that is a function, even though clearly they are valid tables
https://github.com/neovim/neovim/blob/04c7b550384b2246d37c1a893c0f858bc332cb8b/runtime/lua/vim/diagnostic.lua#L704-L707
(`{ opts, 't', true }` and `{ bufnr, 'n', true }` are both valid tables)

After using a different lualine configuration (as recommended in https://github.com/nvim-lualine/lualine.nvim/issues/462#issuecomment-982812587), I got the same error but with a different stacktrace:
![image](https://user-images.githubusercontent.com/889383/144447866-761b29c4-5b02-41a6-881f-08722d2566da.png)

I have reported this problem in the lualine repository (https://github.com/nvim-lualine/lualine.nvim/issues/462), but it seems to be a problem with neovim (or LuaJIT, as suggested in https://github.com/nvim-lualine/lualine.nvim/issues/462#issuecomment-984781710) which is only sparked by a lualine callback.

### Expected behavior

I am able to leave neovim idle for a long time without encountering problems with validation parameters of internal neovim lua function calls.

### Actual behavior

There is an error, as described in the previous section.

### Environments where I encountered the error

I am sure I have encountered it on a GCP VM:

OS: Ubuntu 20.04.3 LTS x86_64
Host: Google Compute Engine
Kernel: 5.8.0-1038-gcp
CPU: Intel Xeon (4) @ 2.800GHz

```sh
17:17 $ nvim -v
NVIM v0.7.0-dev+662-g73b35ef10
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-350

Features: +acl +iconv +tui
```

I don't remember if I faced it on my laptop locally. I am trying to reproduce it locally (by leaving neovim idle for some time) and will let you know if that happens.

<details>
<summary>My laptop environment info, in case I am able to reproduce the problem</summary>

OS: Ubuntu 20.04.3 LTS x86_64
Host: 82JU Legion 5 15ACH6H
Kernel: 5.11.0-41-generic
CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 3.200GHz

I have just fetched the latest nightly (2021-12-02 17:20 UTC):
```sh
18:22 $ nvim -v
NVIM v0.7.0-dev+662-g73b35ef10
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-350

Features: +acl +iconv +tui
```
</details>

**Comment by clason** [comment]
If you could share a project where it has happened in the past (and your Neovim config), this would be very helpful.

**Comment by Gelio** [comment]
My Neovim config lives at https://github.com/Gelio/ubuntu-dotfiles/blob/master/install/neovim/stowed/.config/nvim/init.lua

For the project, unfortunately, the one I am sure I encountered the problem in is at work and it's private. I have just started a few neovim instances on one of my public repos to try to reproduce the issue. I will let you know as soon as I get the error. I don't know how long it will take, though.

**Comment by williamboman** [comment]
Sharing for visibility: there seem to similar reports in https://github.com/williamboman/nvim-lsp-installer/issues/277. I've not yet been able to identify whether it's caused by something else but I figured I'd share anyway. For now I'll continue the discussion in that issue.

**Comment by shadmansaleh** [comment]
@williamboman that looks like an actual validation failure. From traceback it seems filename argument wasn't provided at time of call.

**Comment by matiasvc** [comment]
@shadmansaleh Reporter here. I am using the neovim provided by `http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu` which I update against daily. So my neovim is not outdated.

**Comment by Gelio** [comment]
I haven't experienced the problem for almost a month. I still upgrade to Neovim nightly almost daily (using the Nightly CI build) and still have neovim open for a few days (e.g. over a weekend).

From my perspective, the problem is solved, but I don't know what changed. IMO the issue can be closed.

However, I see that there are still people who experience similar problems (https://github.com/windwp/windline.nvim/issues/30). Not sure how to proceed
