### ISSUE TITLE
Constant problem with clipboard, E353: Nothing in register +

### ISSUE THREAD

**Issue by iio7** [neovim/neovim#16503]
### Neovim version (nvim -v)

0.6.0-1

### Vim (not Nvim) behaves the same?

Don't know, I don't use Vim

### Operating system/version

Arch Linux 5.15.5-arch1-1

### Terminal name/version

xterm 370-1

### $TERM environment variable

xterm-256color

### Installation

System package manager

### How to reproduce the issue

I don't want to deal with the registers and just want to copy and paste from a to the clipboard. I have `xclip` installed and I have the following in my nvim settings in order to be able to also use CTRL+x/c/v:

```
vnoremap <C-c> "+yi
vnoremap <C-x> "+c
vnoremap <C-v> c<ESC>"+p
inoremap <C-v> <C-r><C-o>+
```
Open a file and type some random text, visual select a part of it, CTRL-c to copy, go some lines down and insert with CTRL-v. 

This works.

Open another file and type some random text, press CTRL-v for insert.

This also works.

Stay in the second file. Press RETURN a couple of times to get some lines down, then press CTRL-v to insert again.

This is NOT working.

I get:

```
clipboard: error: Error: target STRING not available
E353: Nothing in register +
```

What am I missing here? Why is the + register suddenly empty?

### Expected behavior

To continue using copy and paste with the clipboard without problems.

### Actual behavior

Described above.

**Comment by seandewar** [comment]
IIRC this may be an issue with `xclip`? https://github.com/astrand/xclip/issues/38

**Comment by iio7** [comment]
@seandewar just now, right before you posted this, I tried installing `xsel` and the problem is gone. Then re-installed `xclip` and the problem is back.

The issue is with `xclip`.

Thanks!

**Comment by iio7** [comment]
It seems like Neovim defaults to xclip when both xclip and xsel is installed. Is there a way to always make Neovim use xsel when both are installed?

**Comment by seandewar** [comment]
In your `init.vim`, you can set `:help g:clipboard` to something like:

```vim
let g:clipboard = #{
      \   name: 'xsel',
      \   copy: {
      \     '+': ['xsel', '--nodetach', '-i', '-b'],
      \     '*': ['xsel', '--nodetach', '-i', '-p'],
      \   },
      \   paste: {
      \     '+': ['xsel', '-o', '-b'],
      \     '*': ['xsel', '-o', '-p'],
      \   },
      \   cache_enabled: 1,
      \ }
```

**Comment by iio7** [comment]
Thank you very very much, you just saved my day! I was struggling getting this right from various examples that just didn't work right.
