### ISSUE TITLE
`virt_lines` overlap when at the end of a buffer in a small window

### ISSUE THREAD

**Issue by l-kershaw** [neovim/neovim#16500]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+662-g73b35ef10

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal 1.11

### $TERM environment variable

N/A

### Installation

Download windows release asset

### How to reproduce the issue

- Write the following into a lua file:
```lua
local buf = vim.api.nvim_get_current_buf()
local ns = vim.api.nvim_create_namespace("")
local line_num = 9
local col = 0

local opts = {
  virt_lines = {{{"foo","Function"}},{{"bar","String"}},{{"baz","Number"}}},
}

vim.api.nvim_buf_set_extmark(buf, ns, line_num, col, opts)
```
- Open file in a window with at most 10 lines.
- Run `:luafile %`

### Expected behavior

Virtual lines appear below the last line, as in the top of the example image.

### Actual behavior

Virtual lines stack on top of the last non-virtual line of the buffer
![image](https://user-images.githubusercontent.com/35707277/144470293-fa17c693-f7bf-4140-8180-a7f00cb9385e.png)

**Comment by zeertzjq** [comment]
It seems the last line of the buffer is visually replaced by the last virtual line when pressing `ggG`:
![Screenshot_20211203_064221](https://user-images.githubusercontent.com/35768171/144514919-b268786c-24cc-4772-99f4-f05127c7dcbe.png)

When pressing `gg<C-F>` the virtual text is shown correctly:
![Screenshot_20211203_064410](https://user-images.githubusercontent.com/35768171/144515024-53e5d5ff-542a-4ece-8205-4e87fb489866.png)

When pressing `ggG<C-F>` it is not:
![Screenshot_20211203_064500](https://user-images.githubusercontent.com/35768171/144515099-27ad5c7d-e0fb-4065-acb9-2cd93968d13f.png)

**Comment by zeertzjq** [comment]
I think this happens when there is virtual text past the last line of the buffer and the when last line of the buffer is scrolled from out of view to the last line of the window.

**Comment by zeertzjq** [comment]
The following diff seems to solve the problem:
```diff
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
index 2ce2be0bf..a3ec6e26a 100644
--- a/src/nvim/screen.c
+++ b/src/nvim/screen.c
@@ -1692,7 +1692,7 @@ static void win_update(win_T *wp, Providers *providers)
     if (eof) {  // we hit the end of the file
       wp->w_botline = buf->b_ml.ml_line_count + 1;
       j = win_get_fill(wp, wp->w_botline);
-      if (j > 0 && !wp->w_botfill) {
+      if (j > 0 && !wp->w_botfill && row < wp->w_grid.Rows) {
         // Display filler text below last line. win_line() will check
         // for ml_line_count+1 and only draw filler lines
         foldinfo_T info = FOLDINFO_INIT;
```

**Comment by Detegr** [comment]
Confirming this bug in Linux using Alacritty. The suggested fix seems to work.

**Comment by zeertzjq** [comment]
This problem also exists in diff mode, when the last buffer line is also the last window line and there are filler lines below it, and my fix also fixes that.

![Screenshot_20211207_225301](https://user-images.githubusercontent.com/35768171/145052253-336bfa72-b0ca-48eb-86a7-a787249d97b7.png)

![Screenshot_20211207_225308](https://user-images.githubusercontent.com/35768171/145052279-7d6a0e03-c9d0-4b59-b4ab-feb6d3ac68a4.png)
