### ISSUE TITLE
Formatoptions overwritten

### ISSUE THREAD

**Issue by ikerurda** [neovim/neovim#16502]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+7229afcd6 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

yes, vim 8.2

### Operating system/version

macOs 12.1

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

```lua
local o = vim.opt
o.formatoptions = o.formatoptions
- "o" -- O and o, don't continue comments
- ...
+ ...
```
If file is sourced again, formatoptions are set correctly

### Expected behavior

`:set fo?` to return
```lua
formatoptions=lqjrc
```

### Actual behavior

`:verb set fo` returns:
```lua
  formatoptions=jncroql
        Last set from /usr/local/Cellar/neovim/HEAD-7229afc_1/share/nvim/runtime/ftplugin/lua.vim line 20
```

**Comment by gpanders** [comment]
Are you setting `formatoptions` in your init.lua? If so, this is not a bug and is precisely how ftplugins are designed to work.

If you don't like the formatoptions that the Lua ftplugin file uses by default, you can override them by creating `~/.config/nvim/after/ftplugin/lua.vim` and modify the `'formatoptions'` there.

**Comment by ikerurda** [comment]
Thanks, but is there a way of setting formatoptions for every filetype?
