### ISSUE TITLE
CTRL+A and CTRL+E in term mode don't jump to beginning and end of line

### ISSUE THREAD

**Issue by caheredia** [neovim/neovim#16505]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+665-g4e352ecc4

### Vim (not Nvim) behaves the same?

yes, 8.2

### Operating system/version

macOS 12.0.1

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

nvim --clean
:term
abc Ctrl+A Ctrl+E

### Expected behavior

neovim on  master
❯ abc

### Actual behavior

neovim on  master
❯ abc^A^E

**Comment by caheredia** [comment]
CTRL+A and CTRL+E print ^A^E instead of jumping to beginning and end of line

**Comment by zeertzjq** [comment]
What shell are you using?

**Comment by caheredia** [comment]
> What shell are you using?

I'm using zsh and the keybindings work as expected when I'm in a regular term session with alacritty or Terminal—not through neovim. 
```shell
❯ echo $SHELL
/bin/zsh
```

**Comment by caheredia** [comment]
@igorlfs thanks, using `bindkey -e` at the end of my zshrc file fixed it. Weird because I use the same dotfiles on multiple machines, but this behavior is only happening on one machine.
