### ISSUE TITLE
coc-java-vimspector gives error when trying to launch debugger on java file

### ISSUE THREAD

**Issue by Kan-Rup** [neovim/neovim#16511]
### Neovim version (nvim -v)

v0.5.1

### Vim (not Nvim) behaves the same?

don't know

### Operating system/version

Debian GNU/Linux 11 (bullseye)

### Terminal name/version

GNU bash, version 5.1.4(1)-release

### $TERM environment variable

xterm-256color

### Installation

download nvim.appimage (v0.5.1)

### How to reproduce the issue

install coc.nvim
install coc-java
install coc-java-vimspector

(launch nvim) nvim.appimage MainClass.java (only one main class in the directory)

enter command ' :CocList mainClassListRun ' (F5 doesn't do anything)

select the only main class there is in the directory from the option given

(I have not made an ‘eclipse project’ for the Java file (as it says in the use section of https://github.com/lidulibai/coc-java-vimspector). this is just a .java and .class file in a directory.

### Expected behavior

The debugger window starts and I am able to use it.

### Actual behavior

I get the following error :

----------------------------------------------------------------------------------
[coc.nvim]: UnhandledRejection: request error nvim_eval - Vim:E117: Unknown function: vimspector#LaunchWithSettings
Error
    at wF.request (/home/kaushan/.vim/plugged/coc.nvim/build/index.js:30:34430)
    at wF.eval (/home/kaushan/.vim/plugged/coc.nvim/build/index.js:33:3288)
    at Object.startVimspector (/home/kaushan/.config/coc/extensions/node_modules/coc-java-vimspector/lib/index.js:17703:38)
----------------------------------------------------------------------------------

sorry if this is not apropriate here, but I don't know what to do next and I currently can't use any debugger with nvim.

**Comment by clason** [comment]
I'm sorry, but this is with overwhelming likelihood an issue with those plugins. I'd suggest opening an issue with the most specific one (coc-java-vimspector) first, and work your way up. If it turns out to be an actual Neovim bug, you should then be able to reproduce it without those plugins and open a new issue.

**Comment by clason** [comment]
Also, 0.5.1 is obsolete; the latest release is 0.6.0.
