### ISSUE TITLE
NVIM displays a blank screen with a bugged cursor

### ISSUE THREAD

**Issue by jamesWalker55** [neovim/neovim#16514]
### Neovim version (nvim -v)

NVIM v0.6.0

### Vim (not Nvim) behaves the same?

no, vim 8.2.2824

### Operating system/version

Windows 10, v. 1809

### Terminal name/version

CMD 10.0.17763.2330, Powershell 5.1.17763.2268, Alacritty 0.9.0 (fed349a)

### $TERM environment variable

xterm-256color

### Installation

Downloaded latest release from Github, extracted to folder then ran nvim

### How to reproduce the issue

nvim --clean
(screen is blank, but keyboard input is accepted)
:q

### Expected behavior

The nvim screen is displayed, any commands are shown at the bottom of the screen.

### Actual behavior

The screen is completely blank except for a single cursor. Typing commands work as usual but there is no visual feedback. The cursor changes shape or moves to the other corner of the screen for certain commands, but in general it stays fixed on the top-left corner.

![image](https://user-images.githubusercontent.com/30405220/144684092-b3478694-3960-47cb-9179-e3436fbae321.png)

Here are some video recordings:

[Recording: I run nvim then quit.](https://streamable.com/43t9l4)

```
nvim --clean
:q
```

[Recording: I run vim, input some text, attempt to quit without saving, then force quit.](https://streamable.com/0226bi)

```
nvim
:a (cursor turns into a line)
(random inputs)
<esc> (cursor turns into a block)
:q (cursor moves to bottom right of screen)
<enter> (cursor moves to top left of screen)
:q!
```

**Comment by erw7** [comment]
Can't reproduce. The phenomenon is similar to the behavior of #6751 and #10669 when `stdin`, `stdout` is not console. In any case, I think it's a problem with your environment.

**Comment by jamesWalker55** [comment]
I'm not sure what you mean by "my environment", I'm guessing you're referring to the environment variables. Here is a list of the environment variables when running nvim: [nvim-env.txt](https://github.com/neovim/neovim/files/7688683/nvim-env.txt)

These are the environment variables when running vim, where this bug doesn't occur: [vim-env.txt](https://github.com/neovim/neovim/files/7688757/vim-env.txt)

Between those two, the most notable difference is that `ProgramFiles` is set to `C:\Program Files (x86)` for vim, and `C:\Program Files` for nvim. Beyond this I'm not sure how to debug this further.

**Comment by mkote** [comment]
Any progress on this one? I am having the exact same issue on Windows 10, v. 1809 with powershell (or any terminal for that matter)

Strangely enough, it works correctly when configuring powershell to [Legacy Mode](https://docs.microsoft.com/en-us/windows/console/legacymode) (which is of course not really a solution).

**Comment by niilz** [comment]
I have the exact same problem/behaviour as @mkote.

I use:
OS: `Windows 10.0 build 17763`
PowerShell: `5.1 (11932)`
neovim: `v0.6.1`

I've installed Neovim via the windows zip-Package.

Setting PowerShell to `Legacy Mode` made `nvim` work.
Otherwise it would just show a black screen. Where, as long as wouldn't try to enter anything, could exit with `:q`.
Although the command would only appear on screen after nvim had exited.

`nvim-qt` btw. works completely fine.

**Comment by mkote** [comment]
Today I managed to find a workaround for this issue. Setting the environment variable TERM to 'winpty' resolves the problem for me.

**Comment by blue-cloak** [comment]
> Today I managed to find a workaround for this issue. Setting the environment variable TERM to 'winpty' or 'conpty' resolves the problem for me.

> @mkote Setting the TERM environment-variable to winpty or conpty is getting me much closer 👏
But unfortunately the editor view does not get cleared out when I exit neovim.
The command prompt just continues underneath the buffer after exiting.
Same issue here, also using the `Windows 10 build 17763` and `Neovim v0.6.1`. Both my powershell and cmd shell is not working.

I did some more investigations following the above instruction.

1. Change `$TERM` in cmd shell
Before changing `$TERM`, I enter the neovim and type `:put=$TERM` blindly then save the file, the file shows the deteced `$TERM` is `vtpcon`
Change the `$TERM` by set `$TERM=win32con`, this seems to solve the issue.
This will not have the same issue mentioned by @niilz , the buffer is clear after quit.

2. Change `$TERM` in powershell
Powershell also have the `$TERM` as `vtpcon` as default
But when I change the `$TERM` by `$env:TERM="win32con"`, it still doesn't work.
Both winpty and conpty work, and have the same issue where the buffer is not cleared after quit.

I'm curious, winpty and conpty are not mentioned in the help file in https://neovim.io/doc/user/term.html, @mkote where did you find these?

This seems to be the problem of $TERM @erw7 , is there any more information that I can help to provide?

**Comment by jamesWalker55** [comment]
> 2\. Change `$TERM` in powershell
>         Powershell also have the `$TERM` as `vtpcon` as default
>         But when I change the `$TERM` by `$env:TERM="win32con"`, it still doesn't work.
>         Both winpty and conpty work, and have the same issue where the buffer is not cleared after quit.

I've tried your second method on my Powershell console, and interestingly it solves the issue. I set the variable with `$env:TERM="win32con"` then ran `nvim`, `nvim` runs as expected.

Refer to the first post for my Windows specs:

> ## Operating system/version
> 
> Windows 10, v. 1809
> 
> ## Terminal name/version
> 
> CMD 10.0.17763.2330, Powershell 5.1.17763.2268, Alacritty 0.9.0 (fed349a)

**Comment by niilz** [comment]
I can confirm, that @jamesWalker55's `Term`-Setting (`$env:TERM="win32con"`) in Powershell (not-legacy-mode) works for me aswell.

OS: Windows 10 v. 1809
Powershell: 5.1 (5436)

**Comment by erw7** [comment]
From the phenomenon, it seems that the display is no longer displayed when one of the `xterm-256color` sequences is sent. Therefore, this is not a neovim issue, but a terminal issue. The only reported problem is with Windows 10 Version 1809, for which support has already ended. I think the easiest solution is to update Windows.

Closed because it is not a neovim issue. Feel free to re-open it if you can prove it is a bug in neovim.
