### ISSUE TITLE
Convert filetype detection to a single autocommand

### ISSUE THREAD

**Issue by gpanders** [neovim/neovim#16512]
### Feature already in Vim?

N/A

### Feature description

This is a tracking/discussion issue for updating filetype detection from many autocommands to a single autocommand.

The primary motivation for this is performance: `filetype.vim` is one of the slowest runtime files that is loaded every time Nvim starts up. Part of the reason it's so slow is that it creates a new autocommand for every single filetype pattern. An alternate solution is to have a single `BufRead,BufNewFile` autocommand dedicated to filetype detection that then dispatches based on the extension or contents of the given file.

@nathom has created an excellent plugin that leverages this idea with [filetype.nvim](https://github.com/nathom/filetype.nvim). The intent with this feature is not to sherlock that plugin, but rather to integrate that concept into core in some basic way while still allowing filetype.nvim to innovate and provide value on its own.

Design goals:

1. While backward compatibility with Vim is not *essential*, we still need to port runtime patches from Vim and any solution should ensure that this remains straightforward to do
2. In a similar vein, existing filetype detection methods for the user (custom `filetype.vim`, `scripts.vim`, `ftdetect`, etc.) must all continue to work. From the end user's point of view, **this must not be a breaking change**.

Other considerations:

1. If we write this mechanism in Vimscript, it can be submitted for consideration upstream (they may not want it of course). The primary performance benefit comes from having a single autocommand, not necessarily rewriting in Lua.
2. Any solution must of course ensure all existing tests continue to pass (e.g. `testdir/test_filetype.vim`).

**Comment by runiq** [comment]
Can this be closed since #16600 has been merged?
