### ISSUE TITLE
Use `vim.ui.select` for selecting lsp client

### ISSUE THREAD

**Issue by IndianBoy42** [neovim/neovim#16529]
### Feature already in Vim?

no

### Feature description

https://github.com/neovim/neovim/blob/f5fb79733e30b6444e9637e9a1aa4bfcb2050ab5/runtime/lua/vim/lsp/buf.lua#L119

If you call a formatting method and there are multiple clients that support that method. 

It uses `vim.fn.confirm` but I think it can be replaced with `vim.ui.select` which is actually closer to the intention semantically

Would a simple PR that changes the `select_client` function above be accepted or are there tests that need to be changed as well?

**Comment by mjlbach** [comment]
#16531 was merged, although I don't really like moving the request into a ui.select callback.

**Comment by glyh** [comment]
Now this is merged, is there a way to configure this, so that I can choose to use multiple lsps together rather than forced to use one? Thanks a lot!

**Comment by zeertzjq** [comment]
> Now this is merged, is there a way to configure this, so that I can choose to use multiple lsps/specify the default one rather than forced to choose one? Thanks a lot!

I don't think there is one. There is an open issue #17044 for this.

**Comment by glyh** [comment]
Thanks, what about default behavior? I found it annoying to choose one when saving,
