### ISSUE TITLE
Doc Regression: vim.lsp.clients missing the requests field in doc

### ISSUE THREAD

**Issue by IndianBoy42** [neovim/neovim#16528]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+672-g1e6eeca9d

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

build from repo

### How to reproduce the issue

- `:h vim.lsp.client`

This commit (from a PR) added the requests field and the documentation

https://github.com/neovim/neovim/commit/d1c470957b49380ec5ceba603dbd85a14f60f09b#diff-6b5f3071d65558aab177912061ac6a2f5312660655a449276c83697686f28e72R627

This commit removed it 

https://github.com/neovim/neovim/commit/2d340a3746dd5d6caf17b2c2e78380fa423409e8#diff-6b5f3071d65558aab177912061ac6a2f5312660655a449276c83697686f28e72L631

### Expected behavior

This is not a behaviour problem, but a documentation problem. I guess I expect to see the correct documentation

### Actual behavior

`{requests}` is missing

**Comment by zeertzjq** [comment]
You can make a PR to add it after line 561 in `lsp.lua`:
<https://github.com/neovim/neovim/blob/1e6eeca9d1360554ee18525603e83c3a1999a622/runtime/lua/vim/lsp.lua#L560-L563>
