### ISSUE TITLE
Automake shortcut for neovim like vim

### ISSUE THREAD

**Issue by HungPham3112** [neovim/neovim#16532]
### Feature already in Vim?

All version

### Feature description

when install vim it has shortcut in `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Vim 8.2`

I hope this available soon.

**Comment by clason** [comment]
Sorry, that installs `GVim` -- which is the Win32 GUI that Vim includes.

In contrast, Neovim does _not_ include a GUI; this is by design. There are [a number of Neovim GUIs](https://github.com/neovim/neovim/wiki/Related-projects#gui) you can choose from and install instead.
