### ISSUE TITLE
status bar doesnot show anything, even when vim-airline installed

### ISSUE THREAD

**Issue by 15675919482** [neovim/neovim#16544]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+676-g4306b395d

### Vim (not Nvim) behaves the same?

no,8.2.2681

### Operating system/version

macos12.0.1

### Terminal name/version

iterm2 3.4.14

### $TERM environment variable

16color

### Installation

system package manager brew

### How to reproduce the issue

nvim --clean

~/.config/nvim/init.vim is:
```
if empty(glob(expand('~/.config/nvim/autoload/plug.vim')))
    silent !curl -fLo expand('~/.config/nvim/autoload/plug.vim') --create-dirs
                \ http://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync --insecure | source $MYVIMRC
endif
call plug#begin(expand('~/.config/nvim/plugged'))

"status bar
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()
```
![image](https://user-images.githubusercontent.com/57145262/144797760-d8f725a2-5730-4956-a91b-99e59998effd.png)

my zsh version is :5.8
oh-my-zsh is latest version
iterm2 version is 3.4.14, in fact 3.4.9 and 3.5.0-beta3 have the same problem, either.
my zsh theme is powlevel10k, when i use agnoster, the problem is not leaving.
my text font is  Hack Nerd Font.
But on another mac of mine, also mbp amd macos12.0.1, the problem doesnot exsist.
![image](https://user-images.githubusercontent.com/57145262/144797822-e33e75e0-ae87-413d-901b-10e24bf27d2e.png)

![Uploading image.png…]()

### Expected behavior

status bar should work well.

### Actual behavior

status bar dont show anything when i use "nvim " open any file, even if i set status line, or install vim-airline, lightline, etc. But when i flip screen to other software, and when i come back to neovim, status line is shown correctly, but when i use ":w" to save file, status bar returns to grey and doesnot shows anything.

**Comment by clason** [comment]
This is almost certainly an issue with the configuration of the fork(!) of airline you are using (the "reall" airline plugin is https://github.com/vim-airline/vim-airline).

**Comment by zeertzjq** [comment]
That repository redirects to the airline repo.

**Comment by zeertzjq** [comment]
Your `$TERM` environment variable is `16color`. This doesn't seem right in iTerm2. Use `export TERM=xterm-256color` in your shell.

**Comment by 15675919482** [comment]
No, it has the same apperance. But now I change to use init.lua, the problem is gone.

**Comment by zeertzjq** [comment]
You mean the problem exists when you run `nvim --clean`, but not when you use `init.lua`?

**Comment by Shougo** [comment]
It seems your configuration problem.
You should create the minimal vimrc.

**Comment by 15675919482** [comment]
maybe, i will close the issue, thank you all.
