### ISSUE TITLE
Allow to right align diagnostic virtual text and allow it to have all diagnostics of the current line instead of just one of them

### ISSUE THREAD

**Issue by vatosarmat** [neovim/neovim#16545]
### Feature description

There is `vim.diagnostic.config` `opts.virtual_text.format` but it allows to format and display only one diagnostic. How about to add something like `opts.virtual_text.format_line` which would allow to format and display in virtual text all the diagnostics of the current line?

Currently it is possible via re-implementing `vim.diagnostic.handlers.virtual_text.show`, but I had to hack-export `private local function save_extmarks(namespace, bufnr)`
![diagnostic_virtual_text](https://user-images.githubusercontent.com/35213999/144816888-64dd6706-bc14-48ae-8dfa-f8e6fe53a6dd.png)

**Comment by gpanders** [comment]
I think finding out why (and if) `save_extmarks` and `restore_extmarks` are necessary and fixing the underlying issue there (and thus allowing us to remove those two functions) is the best solution here, as that then allows the underline and virtual text handlers to be fully overridable.

**Comment by ColinKennedy** [comment]
@vatosarmat Could you share your implementation on how you got virtual text to right-align?

I'm trying to get one of the following behaviors in Neovim

Right align (@vatosarmat 's request)

``` 
foo text                     # virtual stuff
bar                              # more blah
more text here                # text here tt
```

Or even just "starts at a certain column"

``` 
foo text                         # virtual stuff
bar                              # more blah
more text here                   # text here tt
really long text that exceeds column  # more text
```

I've been looking around for any way to do this via `vim.diagnostic.config()` but haven't found anything. So far I'm just setting the virtual text spacing very high while I wait to find a cleaner solution.

**Comment by MariaSolOs** [comment]
@gpanders (cc @justinmk @glepnir) what do you think of changing the API of `vim.diagnostic.config.virtual_text.format` to take an list of diagnostics instead? This would address this issue and it seems like it wouldn't require a lot from neovim's side [(given that `reformat_diagnostics` already receives all diagnostics)](https://github.com/neovim/neovim/blob/58a1ef8e6a93c615379f6fbe7234697bcdc42b3e/runtime/lua/vim/diagnostic.lua#L131). It does introduce a breaking change, but I find it reasonable for the virtual text handler to have all the diagnostic information available for the current line.

**Comment by gpanders** [comment]
A breaking change is not needed here. I think what we can do is add support for more of the `virt_text` options in `nvim_buf_set_extmark`. Apropos to this issue is `virt_text_pos`, which accepts a `"right_align"` option.

Then one could simply use this:

```lua
vim.diagnostic.config({
  virtual_text = {
    format = function(diagnostic)
      local lines = vim.split(diagnostic.message, '\n')
      return lines[1]
    end,
    virt_text_pos = 'right_align',
    suffix = ' ',
  },
})
```

![image](https://github.com/neovim/neovim/assets/8965202/c9b20987-4217-4716-a5f7-1501750d9930)

**Comment by ColinKennedy** [comment]
@gpanders I'm confused by your screenshot. If all that's desired is putting the text, unaligned, far to the right, you can already do that with base Neovim. That's what I do currently when I said "So far I'm just setting the virtual text spacing very high while I wait to find a cleaner solution". A clean right-alignment is what's desired. @vatosarmat suggests a true right-align. My example is a "starts at column" sort of alignment which isn't really the same thing. I hope what you're proposing can accommodate either.

**Comment by gpanders** [comment]
"Right aligned" means the text is aligned on the right, which is what my screenshot shows. Your [example](https://github.com/neovim/neovim/issues/16545#issuecomment-1501355259) is not right alignment, but left alignment at a fixed column offset. This should also be possible with the `virt_text_win_col` option which you can use if #24724 is merged.
