### ISSUE TITLE
Does not restore echo flag on suspension

### ISSUE THREAD

**Issue by RaviRahar** [neovim/neovim#16554]
### Neovim version (nvim -v)

0.7.0 commit g523f03b50

### Vim (not Nvim) behaves the same?

yes, 8.2.3753

### Operating system/version

ubuntu 20.04

### Terminal name/version

alacritty 0.10.0-dev

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

` nvim --clean <filename> `  
` Ctrl + Z `

**NOTE:**  
- ` nvim `  
` Ctrl + Z `  

This does work, i.e. not typing filename and opening empty buffer.

### Expected behavior

After suspension neovim should reset echo flag and also other flags that it set.

### Actual behavior

Neovim does not reset echo flag after opening file and suspending it. Works fine if I do not provide a filename. Vim behaves similarly.  
Tried on other terminals too (like xfce4-terminal 0.8.9.1).

**Comment by zeertzjq** [comment]
You steps to reproduce look a bit confusing. What does the "**NOTE:**" part mean?

Also, `nvim -u NORC` still loads plugins. Use `nvim --clean` to mimic a fresh install.

**Comment by RaviRahar** [comment]
Okay, updated.

**Comment by zeertzjq** [comment]
Also, what shell are you using?

**Comment by RaviRahar** [comment]
Bash

**Comment by RaviRahar** [comment]
Sorry, the problem was by fzf completions and not on neovim's end.
