### ISSUE TITLE
:checkhealth non-function in 0.6.0

### ISSUE THREAD

**Issue by SeamusConnor** [neovim/neovim#16551]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Ubuntu 18.04

### Terminal name/version

tmux/alacritty

### $TERM environment variable

tmux-256color

### Installation

appimage

### How to reproduce the issue

nvim -u NORC +checkhealth

### Expected behavior

Expect to see checkhealth

### Actual behavior

```
Running healthchecks...
Error detected while processing function health#check:
line   37:
E684: list index out of range: 0
Press ENTER or type command to continue```

**Comment by jamessan** [comment]
The template mentions using `nvim --clean` to remove the issue of user-config interfering.  `-u NORC` _only_ removes your init.vim not any of your plugins.

I'd suggest re-trying with `nvim --clean +checkhealth` and if that works, find out what's wrong in your config.

**Comment by zeertzjq** [comment]
Is this a duplicate of #16374?

**Comment by muniter** [comment]
> Is this a duplicate of #16374?

Seems like it's a case of stale runtime files, in this case `runtime/autoload/health.vim`

**Comment by SeamusConnor** [comment]
Yep. With --clean, the issue partially resolves. Apologies for missing that option. Wiping out cached files was enough to get checkhealth to run. There is a lua error in treesitter's health check, but I can make a separate ticket for that.
