### ISSUE TITLE
`hi! link Visual Foo` isn't immediately effective

### ISSUE THREAD

**Issue by bew** [neovim/neovim#16552]
### Neovim version (nvim -v)

v0.7.0-dev+677-g523f03b50 / 0.5.1

### Vim (not Nvim) behaves the same?

No, it works (8.2)

### Operating system/version

ArchLinux

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

appimage / nix

### How to reproduce the issue

```
nvim --clean
:hi VisualFoo ctermbg=236      " Grey
:hi VisualBar ctermbg=52       " Red
:hi! link Visual VisualFoo
iabc def<esc>

---- then select a word,
---- => see that visual is grey

:hi! link Visual VisualBar

---- then select a word,
---- => see that visual is STILL grey, but should be red

:split
---- alternative is to enter insert mode and back to normal

---- then select a word,
---- => see that visual is now red
```

### Expected behavior

Visual highlight should be changed immediately

### Actual behavior

Visual highlight is not effectively applied, and stays the same as before until new window created, or going to insert mode and back (and probably other cases)

**Comment by zeertzjq** [comment]
`:redraw` also doesn't change Visual highlight, while `:redraw!` does.

**Comment by zeertzjq** [comment]
This bugs seems to also apply to some other highlight groups, not only `Visual`.

**Comment by zeertzjq** [comment]
It seems after using `:hi! link`, the global `highlight_attr` is updated, but `w_hl_attrs` are not.
