### ISSUE TITLE
Using lua function to handle tabline click events

### ISSUE THREAD

**Issue by noib3** [neovim/neovim#16555]
### Feature already in Vim?

No

### Feature description

Hi, I'm writing a [bufferline plugin](https://github.com/noib3/cokeline.nvim) in Lua, and the last piece of Vimscript I have left in my codebase is the function that handles mouse clicks.

The tabline help page `:h tabline` says this
```
	@ N   For 'tabline': start of execute function label. Use %X or %T to 
	      end the label, e.g.: %10@SwitchBuffer@foo.c%X.  Clicking this 
	      label runs specified function: in the example when clicking once 
	      using left mouse button on "foo.c" "SwitchBuffer(10, 1, 'l', 
	      '    ')" expression will be run.
```
I was wondering if there was a way to put a lua function call between the `@`s. I tried using `%10@v:lua.cokeline_handle_click@foo.c%X`, having defined
```
-- cokeline/init.lua

_G.cokeline_handle_click = function(...)
  -- some logic
end
```
but that doesn't work, I still get a `E117: Unknown function: v:lua.cokeline_handle_click` error when I try to click on a buffer.

**Comment by nullchilly** [comment]
It seems to work now :)

https://github.com/akinsho/bufferline.nvim/pull/457

**Comment by justinmk** [comment]
thanks @nullchilly 

Closed by https://github.com/neovim/neovim/pull/18650
