### ISSUE TITLE
Double indenting when pasting

### ISSUE THREAD

**Issue by luqasz** [neovim/neovim#16558]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

no, 8.2

### Operating system/version

macOS 12.0.1

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

Copy a text with indent in it:
```
It is possible to move the cursor after an abbreviation:
   :iab if if ()<Left>

You can even do more complicated things.  For example, to consume the space
typed after an abbreviation:
```

Enter insert mode
type in `CTRL+R` `*`

More info in [this](https://github.com/equalsraf/neovim-qt/issues/948) neovim-qt bug report.

### Expected behavior

Paste text as is, without indenting too much.

### Actual behavior

Above example text is pasted as:
```
It is possible to move the cursor after an abbreviation:
   :iab if if ()<Left>

   You can even do more complicated things.  For example, to consume the space
   typed after an abbreviation:
```

Not extra indent

**Comment by seandewar** [comment]
Isn't this due to Nvim having `autoindent` set by default? Putting via `<C-R>` inserts text as if its typed.

**Comment by zeertzjq** [comment]
Did you also use `<C-R>*` when pasting in Vim?

**Comment by luqasz** [comment]
> Did you also use <C-R>* when pasting in Vim?

Yes

**Comment by seandewar** [comment]
What happens if you do it with `autoindent` set in Vim? Does it do the same as Nvim?

**Comment by zeertzjq** [comment]
I tested on Linux, and Vim with `'autoindent'` behaves the same as Nvim with `'autoindent'`, and Vim with `'noautoindent'` behaves the same as Nvim with `'noautoindent'`. I think this can be closed.

**Comment by seandewar** [comment]
Agreed. Thanks for verifying for me @zeertzjq (I don't have access to Vim atm :sweat_smile:)

**Comment by zeertzjq** [comment]
BTW, you can try mapping to `<Cmd>call nvim_paste(getreg('+'), v:false, -1)<CR>`.

**Comment by zeertzjq** [comment]
BTW, you can try `<C-R><C-O>+` and `<C-R><C-P>+`.
