### ISSUE TITLE
winhighlight does not work with Diagnostic* highlight groups

### ISSUE THREAD

**Issue by smackesey** [neovim/neovim#16550]
### Neovim version (nvim -v)

0.6.0 (release)

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.0.1

### Terminal name/version

VimR (GUI)

### $TERM environment variable

N/A

### Installation

download VimR release

### How to reproduce the issue

highlight MyDiagnosticUnderlineHint ctermfg=red guifg=red
set winhighlight=DiagnosticUnderlineHint:MyDiagnosticUnderlineHint

### Expected behavior

The above should work with `winhighlight`. The `winhighlight` doc says that built-in groups are supported, and `DiagnosticUnderlineHint` (and other Diagnostic groups) are builtin.

### Actual behavior

Neovim complains that the argument to `winhighlight` is invalid (as if you tried to override a custom group, which is not supported).

**Comment by gpanders** [comment]
The builtin highlight groups are only the ones listed in `:h highlight-groups`. The diagnostic highlights are not one of them.

**Comment by bfredl** [comment]
The specific issue for diagnostics would be a documentation issue. The general issue will be fixed by namespaced highlights https://github.com/neovim/neovim/pull/13457 .

**Comment by zeertzjq** [comment]
#13547 has been merged
