### ISSUE TITLE
syncolor.vim not automatically sourced

### ISSUE THREAD

**Issue by bryankaplan** [neovim/neovim#16566]
### Neovim version (nvim -v)

v0.6.0

### Vim (not Nvim) behaves the same?

no, n/a because paths are different

### Operating system/version

Arch Linux

### Terminal name/version

xterm 370

### $TERM environment variable

xterm-256color

### Installation

AUR

### How to reproduce the issue

nvim --clean some-file-with-syntax.ext

### Expected behavior

~/.config/nvim/after/syntax/syncolor.vim loads automatically.

### Actual behavior

~/.config/nvim/after/syntax/syncolor.vim no longer loads automatically.

**Comment by bryankaplan** [comment]
Note that my runtimepath is unaltered.

**Comment by zeertzjq** [comment]
I think this file has been deprecated by #15207. So it turns out it is still needed.

**Comment by gpanders** [comment]
syncolor.vim doesn't load automatically because it no longer exists. Why do you need it? The highlight groups that it defined are now defined automatically internally (#15207).

**Comment by bryankaplan** [comment]
I created it years ago — at least 15 years ago — and it has all of my default color definitions. Is there info somewhere explaining how to migrate them to somewhere else?

**Comment by gpanders** [comment]
Is there a reason you cannot use a colorscheme file? Just move `syncolor.vim` to `colors/some_name.vim` and add `colorscheme some_name` to init.vim.

**Comment by bryankaplan** [comment]
That worked. Thank you @gpanders.
