### ISSUE TITLE
Normal mode command 'Y' (yank a line) is  broken

### ISSUE THREAD

**Issue by tjavdar** [neovim/neovim#16569]
### Neovim version (nvim -v)

NVIM v0.6.0, Build type: Release, LuaJIT 2.0.5

### Vim (not Nvim) behaves the same?

no,  vim 8.2.3582

### Operating system/version

Linux zpx 5.15.6-arch2-1 #1 SMP PREEMPT Thu, 02 Dec 2021 15:47:09 +0000 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.9.0-2

### $TERM environment variable

screen

### Installation

Arch official package

### How to reproduce the issue

nvim --clean
i                       #  Enter insert mode
Enter a line      #  Enter a line of text
<Esc>              #  Escape to normal line
Y                      # Yank a line (supposed to be a shorcut to 'yy')
p                      # Paste pastes just one char, not the whole line 
          

### Expected behavior

In normal mode, the result of 'Yp' should be identical to 'yyp' (yank a line). 

### Actual behavior

In normal mode, the result of 'Yp' is erroneously identical to 'ylp' (yank a char)

**Comment by zeertzjq** [comment]
See #13268

**Comment by ulidtko** [comment]
Just stumbled over this myself independently. Total surprise!

BTW, `y$` is not equivalent to `Y` (or at least, used to be). The former copies **from the cursor** to end of line — the latter copies **the entire line** regardless of where the cursor stands.

**Comment by clason** [comment]
Yes. As the linked issue (and the release notes) make clear, that is an _intentional_ change for more consistency with `C` and `D`. Just `unmap Y` in your `init.vim` if you don't like it.

**Comment by ulidtko** [comment]
Thanks, will do.

FWIW, now `S` feels inconsistent. But whatever, I'm not here for extended discussion.

**Comment by tallakt** [comment]
Changing key bindings for very basic editing at this point in time seems user hostile towards existing users...
