### ISSUE TITLE
where the privacy policy page?

### ISSUE THREAD

**Issue by ys-oo** [neovim/neovim#16567]
### Feature already in Vim?

no

### Feature description

I would ask about neovim and privacy, does : 
1.neovim connect to wifi or have any online connection 
2.neovim have tracking or something like bug report
3.is neovim privacy friendly.

Thank you for your response and for your hard work ☺️

**Comment by gpanders** [comment]
1. No
2. No
3. Yes

**Comment by ys-oo** [comment]
Thank you so much
