### ISSUE TITLE
gitter.im

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#1658]
I found out about https://gitter.im/ a while back; it's basically a chat room integrated with Github. There's also an IRC bridge: https://irc.gitter.im/

I'm not sure if it would be useful for Neovim, but I wanted to bring it to your attention. It might be a nice addition to the issue queue, e.g. to discuss things before an issue is even created. Contrary to other things like IRC, reddit, and Google groups it doesn't require people to create separate accounts (Github account is used) and is "integrated" (not sure what this entails exactly, I only tried it with a toy repo) with Github issues & activity (and even Travis).

**Comment by fwalch** [comment]
Comment in #2122 by @starcraftman:

> Small side note, though perhaps relevant in coordinating review/commit & questions, do you plan on deciding regarding https://gitter.im/ ? This was raised in #1658, but left unresolved. Ability to discuss then use @/# notifications can be useful. As noted in the topic, lots of people use IRC for support, gitter could be a mainly reviewer/commiter area?

**Comment by tarruda** [comment]
> Who manages the IRC room? I suggest changing the tagline to "vim out of the box".

I do. I think I added @ashleyh as a moderator but since he/she disappeared nobody touched the title anymore.

**Comment by tarruda** [comment]
I say we activate this gitter chat and see what happens. Its not gonna hurt to try.

**Comment by Pyrohh** [comment]
Yes please. Also since almost no one is going to see this issue, it might be a good idea to mention the gitter channel near the top of README.MD for now, as to get more people using it.

**Comment by justinmk** [comment]
:+1: 

If questions are answerd on gitter.im, how do users search that knowledge base? Does it integrate with GH issues search?

**Comment by fwalch** [comment]
@justinmk I don't think so, but if it's a "real" issue (i.e. which needs to be fixed in code), I think it will need to be posted as a Github issue anyway. The chat might help to direct people to already existing GH issues and help them with stuff that's not really a bug. If some knowledge comes out of this, it should be added to the documentation (`:help`) or the wiki.

**Comment by rgrinberg** [comment]
I'd love to see a gitter page for neovim. I think that the group of users that would use gitter but refuse to use irc is sufficiently large that a project of neovim's size should reach out to.

**Comment by tarruda** [comment]
Done: https://gitter.im/neovim/neovim

Very easy, they even have a bot to send a PR with the badge inclusion in README

**Comment by fwalch** [comment]
@tarruda From https://gitter.zendesk.com/hc/en-us/articles/200176722-Integrations, you could set up Gitter integration with Travis to show build results in the sidebar.
