### ISSUE TITLE
`nvim_win_close` can't close last window with `force` set to `true` or 1

### ISSUE THREAD

**Issue by younger-1** [neovim/neovim#16595]
### Neovim version (nvim -v)

NVIM v0.6.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux 5.10.60.1

### Terminal name/version

st 0.8.4

### $TERM environment variable

xterm-256color

### Installation

 system package manager: pacman

### How to reproduce the issue

1. `nvim --clean a.txt`
2. `:lua vim.api.nvim_win_close(0, 1)`

### Expected behavior

Close the window and exit nvim.

### Actual behavior

Error:
```
E5108: Error executing lua [string ":lua"]:1: Vim:E444: Cannot close last window
stack traceback:
        [C]: in function 'nvim_win_close'
        [string ":lua"]:1: in main chunk
```

**Comment by dundargoc** [comment]
`:close!` will never close the last window and exit nvim, even with the exclamation mark. The documentation is a bit confusing because I also got confused by this.
