### ISSUE TITLE
Neovim build for latest Ubuntu arm64 & Debian arm64 bundle with a Lua runtime rather than LuaJIT runtime, which prevent telescope to work

### ISSUE THREAD

**Issue by githubzilla** [neovim/neovim#16605]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

no, Vim doesn't bundle Lua

### Operating system/version

Ubuntu 20.04.3 LTS

### Terminal name/version

xterm

### $TERM environment variable

xterm

### Installation

system package manager

### How to reproduce the issue

Run following steps on a Ubuntu 20.04.3 arm64 machine 
> uname -a 
Linux 3854189fcdba 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux)

> sudo apt install -y software-properties-common
> sudo add-apt-repository ppa:neovim-ppa/stable
> sudo apt update
> apt install neovim
> nvim --version

### Expected behavior

> nvim --version
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-3t303a/neovim-0.5.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-3t303a/neovim-0.5.1/build/config -I/build/neovim-3t303a/neovim-0.5.1/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-3t303a/neovim-0.5.1/build/src/nvim/auto -I/build/neovim-3t303a/neovim-0.5.1/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Actual behavior

Telescope plugin depends on LuaJIT to work, the Lua bundle makes it fail to work. 
(Error with the warning message: [telescope] [WARN  12:03:10] (tail call):-1: Finder failed with msg:  attempt to yield across metamethod/C-call boundary)
 
> nvim --version
NVIM v0.5.1
Build type: Release
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-BxR5JG/neovim-0.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-BxR5JG/neovim-0.5.1/build/config -I/build/neovim-BxR5JG/neovim-0.5.1/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-BxR5JG/neovim-0.5.1/build/src/nvim/auto -I/build/neovim-BxR5JG/neovim-0.5.1/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

**Comment by clason** [comment]
You have to take this up with Ubuntu, which build Neovim with Lua; this is out of our control.

**Comment by clason** [comment]
Use the appimage or build from source yourself in the meantime.

**Comment by githubzilla** [comment]
@clason Thanks for the information!

**Comment by jamessan** [comment]
This requires a newer LuaJIT to be packaged for Debian. The current version doesn't work properly on arm64.

**Comment by githubzilla** [comment]
@jamessan Ok, good to know that, Thanks! 
How can we make it happen to ask Debian to upgrade the newer LuaJIT version? BTW, which LuaJIT version shall we ask for? I see the current packaged stable version is 2.1.0~beta3+dfsg-5.3: arm64. (https://packages.debian.org/search?arch=arm64&keywords=luajit)
