### ISSUE TITLE
LSP: Add tag to stack when using "go to reference"

### ISSUE THREAD

**Issue by holmanb** [neovim/neovim#16610]
### Feature already in Vim?

No

### Feature description

After calling Goto definition, one can use <C-t> to "go back to where I was when I called goto definition", using the tag stack. It would be great if a tag was also added to the tag stack when using "go to reference" for consistent navigation behavior. Currently if I do "go to definition", followed by "go to references", and then <C-t> (go back), I would expect to be taken to the definition, but I'm taken back to the location I was at before "go to definition". I would expect a tag to be added when calling at "go to references", which would cause <C-t> to bring me back to the definition.

**Comment by teto** [comment]
there exists a plugin to integrate lsp and tagstack. Sorry I dont remember the name (probably https://github.com/weilbith/nvim-lsp-smag)  but you might want to give it a try.

**Comment by holmanb** [comment]
> there exists a plugin to integrate lsp and tagstack. Sorry I dont remember the name (probably https://github.com/weilbith/nvim-lsp-smag) but you might want to give it a try.

Thanks for the heads-up. It is already integrated with (`vim.lsp.buf.definition()` at least it works for me), so I was hoping not to require a plugin for this.

**Comment by gpanders** [comment]
There is an important difference between `vim.lsp.buf.definition()` (which jumps to a definition) and `vim.lsp.buf.references()` which simply lists the references in the quickfix list. Adding quickfix list items to the tagstack isn't consistent with behavior in any other part of Vim, so I don't think this is a good idea.

In my mind, `references()` is a descendant of the `:isearch`/`:dsearch` commands, which also do not use the tagstack.

*However*, a variant of `references()` that worked like `:tselect` or `:tjump` (list available references and prompt the user for a number to jump to) would make much more sense for this use case. A PR with an implementation of such a variant would be welcome.

**Comment by holmanb** [comment]
> There is an important difference between `vim.lsp.buf.definition()` (which jumps to a definition) and `vim.lsp.buf.references()` which simply lists the references in the quickfix list. Adding quickfix list items to the tagstack isn't consistent with behavior in any other part of Vim, so I don't think this is a good idea.
> 
> In my mind, `references()` is a descendant of the `:isearch`/`:dsearch` commands, which also do not use the tagstack.


Excellent feedback @gpanders, thanks for the insight. I didn't realize that `vim.lsp.buf.references()` just uses the quick fix list, that makes sense.

> _However_, a variant of `references()` that worked like `:tselect` or `:tjump` (list available references and prompt the user for a number to jump to) would make much more sense for this use case. A PR with an implementation of such a variant would be welcome.

I might try to put together a contribution (first time) for this.

**Comment by lukebakken** [comment]
FWIW, I am using this with Neovim 0.6.0 on Windows:

```
set tagfunc=v:lua.vim.lsp.tagfunc
```

It works fine for my basic use of `CTRL-]` / `CTRL-T`. I tried `weilbith/nvim-lsp-smag` but it did not work OOTB 🤷

**Comment by mjlbach** [comment]
> However, a variant of references() that worked like :tselect or :tjump (list available references and prompt the user for a number to jump to) would make much more sense for this use case. A PR with an implementation of such a variant would be welcome.

@gpanders I'm not sure I want to pollute the LSP namespace with multiple interfaces to the same functionality. This seems like an excellent candidate for a plugin (I'm pretty sure saga had a similar implementation) like dressing.nvim.

**Comment by gpanders** [comment]
@holmanb Another solution that you could use right now is to just set a mark when you call references. Just make the right hand side of your mapping

`<Cmd>kR<Bar>lua vim.lsp.buf.references()<CR>`

Then you can jump back to where you were with `'R`.

**Comment by mjlbach** [comment]
I'd recommend people follow @gpanders advice, adding to the tag stack doesn't make sense for something that *only* populates the qflist.
