### ISSUE TITLE
segfault at 4 ip 000000000048afcf sp 00007ffe37d76580 error 4 in nvim[445000+311000]

### ISSUE THREAD

**Issue by dzintars** [neovim/neovim#16622]
### Neovim version (nvim -v)

v0.6.0-dev+0c2a7aa

### Vim (not Nvim) behaves the same?

Vim not installed

### Operating system/version

Fedora 34

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

Have no idea. It just sometimes happens. Will make comments when will discover the pattern.

### Expected behavior

As a User I wish Nvim does not crash.

### Actual behavior

Rarely it just crash. Last time i noticed that when was trying to delete visual selection.
I only use it within Tmux. Can't tell it crash in a plain terminal.

```bash
[275125.051452] nvim[2231837]: segfault at 4 ip 000000000048afcf sp 00007ffe37d76580 error 4 in nvim[445000+311000]
[275125.051461] Code: 48 89 3d 94 93 41 00 48 89 35 85 93 41 00 c3 55 53 48 83 ec 08 48 89 fd bb 00 00 00 00 eb 17 48 89 d8 48 c1 e0 04 48 03 45 10 <48> 8b 38 e8 34 42 0d 00 48 83 c3 01 48 39 5d 00 77 e3 48 8b 7d 10
```

**Comment by dzintars** [comment]
![image](https://user-images.githubusercontent.com/547420/145691025-9f63eb74-5d06-40ff-91a9-6c4276771acf.png)
Seems it has something to do with LSP. It crashes when I try to delete such stanza.
I am preparing my Ansible role for a fresh build. Will see does it crash on nightly.

**Comment by clason** [comment]
Then it's probably a bug related to extmarks on the final lines of a buffer. Update to the latest version.

(As a remark: if you build from source, you are expected to track HEAD. Please always test the latest commit before opening an issue!)

**Comment by dzintars** [comment]
So, I'm on `NVIM v0.7.0-dev+3aff3d6` now and I don't see it anymore. At least for now. Keep it open for a couple days. I will report or close it later.

**Comment by muniter** [comment]
This looks a lot like https://github.com/neovim/neovim/issues/15927 which was already solved.

**Comment by clason** [comment]
Let's close this, as I strongly believe that bug is fixed; you're welcome to reopen it (with exact reproduction steps) if it does occur again.
