### ISSUE TITLE
TexLab error when inserting text before multibyte characters

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#16624]
### Neovim version (nvim -v)

v0.7.0-dev+714-g3aff3d634, also exists in v0.6.0

### Language server name/version

texlab 3.3.1

### Operating system/version

Arch Linux

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: texlab: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/zeertzjq/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - INFO: Build type: Debug
  - WARNING: Non-optimized (DEBUG) build. Nvim will be slower.
    - ADVICE:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'
```

### Steps to reproduce using "nvim -u minimal_init.lua"

This is `/tmp/minimal_init.lua`:
```lua
vim.lsp.set_log_level('trace')
require('vim.lsp.log').set_format_func(vim.inspect)
vim.cmd([[set rtp+=~/.local/share/nvim/site/pack/packer/start/nvim-lspconfig]])
require('lspconfig').texlab.setup({})
vim.o.showmode = false
```

This is `/tmp/tmp.tex`:
```tex
\begin{document}
→
\end{document}
```

1. Run `VIMRUNTIME=./runtime ./build/bin/nvim --clean -u /tmp/minimal_init.lua /tmp/tmp.tex`
2. Press `2ggII`

### Expected behavior

No errors. LSP client doesn't quit.

### Actual behavior

`Client 1 quit with exit code 1 and signal 0`

### Log file

https://gist.github.com/zeertzjq/5afb01d99afd99af9537e12669b05905

**Comment by zeertzjq** [comment]
This problem doesn't exist in v0.5.1, so this is regression.

**Comment by zeertzjq** [comment]
The problem seems to have if the inserted character is occupies a different number of bytes from a following character. For example, if the line contains a 2-byte character, then inserting a 1-byte character and a 3-bytes character before it will cause an error, but inserting a 2-byte character before it will not.

**Comment by gebner** [comment]
We're seeing the same issue with the Lean language server when inserting a space before `⟨` (which encodes into 3 bytes of UTF-8).  Interestingly, this results in an LSP message which is not valid UTF-8:
```
Content-Length: 270

{"method":"textDocument\/didChange","params":{"contentChanges":[{"text":" <E2><9F>","rangeLength":0,"range":{"end":{"line":0,"character":0},"start":{"line":0,"character":0}}}],"textDocument":{"uri":"file:\/\/\/home\/gebner\/lean4\/scratch5.lean","version":5}},"jsonrpc":"2.0"}
```
I have escaped the malformed bytes. The actual bytes between the quotes in the text field is `"\x20\xe2\x9f"`.

**Comment by rish987** [comment]
Bisected to neovim/neovim#16358.

**Comment by mjlbach** [comment]
Well, the handling before #16358 was incorrect, so the fact that it was not explicitly erroring/crashing does not mean #16358 caused a regression.

**Comment by rish987** [comment]
@mjlbach I've identified the original problem causing #16352 in the Lua stdlib as [a faulty cast of `offset` to `char_u` in `str_utf_start()`](https://github.com/neovim/neovim/blob/bdfea9d9ae2b1db03c9cad9b0b07330b6f09cfa2/src/nvim/lua/stdlib.c#L233), which explains why we were seeing an issue exactly at the 256 byte boundary.

I don't yet have much experience with the C code, so lmk if this is an easy fix for you, but I see you're taking a (well-deserved) break so I can look into fixing this over the next few days.

**Comment by clason** [comment]
@bfredl ☝🏻
