### ISSUE TITLE
LSP diagnostics disappear on :edit

### ISSUE THREAD

**Issue by wvanlint** [neovim/neovim#16623]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+714-g3aff3d634

### Language server name/version

golang.org/x/tools/gopls v0.7.3

### Operating system/version

MacOS 12.0.1

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: gopls: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - INFO: Build type: Debug
  - WARNING: Non-optimized (DEBUG) build. Nvim will be slower.
    - ADVICE:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='Apple_Terminal'
```

### Steps to reproduce using "nvim -u minimal_init.lua"

- Modify `cmd` in `minimal_init.lua` to `gopls`.
- Run `go mod init github.com/test/test`.
- Run `echo "pakage main" > test.go`.
- Run `nvim --clean -u minimal_init.lua test.go`.
- See diagnostics.
- Run `:edit`.

### Expected behavior

The expected behavior would be to still see the current diagnostics.

### Actual behavior

The diagnostics disappear.

I did some investigation and the following happens:
- The LSP won't publish diagnostics unless changes occur.
- The diagnostics are stored in the diagnostics cache which get cleared `on_detach`:
  - [Diagnostics being set](https://github.com/neovim/neovim/blob/3aff3d6349d878f2f57b8931b2f1a2397926f889/runtime/lua/vim/lsp/diagnostic.lua#L209)
  - [Diagnostics cache being cleared on_detach](https://github.com/neovim/neovim/blob/3aff3d6349d878f2f57b8931b2f1a2397926f889/runtime/lua/vim/diagnostic.lua#L52)
  - [:edit calling on_detach](https://github.com/neovim/neovim/blob/3aff3d6349d878f2f57b8931b2f1a2397926f889/src/nvim/ex_cmds.c#L2658-L2664)
  - [buf_updates_unload()](https://github.com/neovim/neovim/blob/3aff3d6349d878f2f57b8931b2f1a2397926f889/src/nvim/buffer_updates.c#L137)

Happy to look into a solution if there's any feedback on the best path forward.

### Log file

https://gist.github.com/wvanlint/6782a35df3df564ea98d9a3d00c69097

**Comment by mjlbach** [comment]
I consider this a gopls bug that should be filed upstream with the gopls team.

To summarize the issue, when `:e` is called, the language server is summarily

* sent a `textDocument/didClose` notification for a given buffer
* `nvim_buf_attach` is terminated
* a new instance of `nvim_buf_attach` is started
* `textDocument/didOpen` is sent to the langauge server along with the text of the file

For most language servers, they will immediately re-send diagnostics as this is equivalent to opening a new file. See pyright:

```
[DEBUG][2021-12-19 19:34:29] .../vim/lsp/rpc.lua:344	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didClose",
  params = {
    textDocument = {
      uri = "file:///home/michael/Repositories/neovim_development/neovim-worktree/neovim/main.py"
    }
  }
}
[DEBUG][2021-12-19 19:34:29] .../vim/lsp/rpc.lua:344	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didOpen",
  params = {
    textDocument = {
      languageId = "python",
      text = "import os\n",
      uri = "file:///home/michael/Repositories/neovim_development/neovim-worktree/neovim/main.py",
      version = 0
    }
  }
}
[DEBUG][2021-12-19 19:34:29] .../vim/lsp/rpc.lua:451	"rpc.receive"	{
  jsonrpc = "2.0",
  method = "textDocument/publishDiagnostics",
  params = {
    diagnostics = {},
    uri = "file:///home/michael/Repositories/neovim_development/neovim-worktree/neovim/main.py"
  }
}
```

With gopls, no notification is sent:

```
[DEBUG][2021-12-19 19:36:45] .../vim/lsp/rpc.lua:344	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didClose",
  params = {
    textDocument = {
      uri = "file:///home/michael/Repositories/neovim_development/neovim-worktree/neovim/test.go"
    }
  }
}
[DEBUG][2021-12-19 19:36:45] .../vim/lsp/rpc.lua:344	"rpc.send"	{
  jsonrpc = "2.0",
  method = "textDocument/didOpen",
  params = {
    textDocument = {
      languageId = "go",
      text = "pakage main\n",
      uri = "file:///home/michael/Repositories/neovim_development/neovim-worktree/neovim/test.go",
      version = 0
    }
  }
}
```

**Comment by mjlbach** [comment]
See https://github.com/golang/go/issues/50267

**Comment by wvanlint** [comment]
Interesting, I browsed the [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_publishDiagnostics) and the interaction between the ownership defined by `textDocument/didClose`, `textDocument/didOpen` and the ownership of diagnostics seems to change depending on whether the language is single file or project based.

The relevant snippets:

> Diagnostics are “owned” by the server so it is the server’s responsibility to clear them if necessary.

> If a language is single file only (for example HTML) then diagnostics are cleared by the server when the file is closed.

> If a language has a project system (for example C#) diagnostics are not cleared when a file closes.

**Comment by mjlbach** [comment]
If you follow the upstream issue the issue was tagged by the gopls developers as for the next release. I'm not sure what you mean by the above snippets.

**Comment by wvanlint** [comment]
The specification gave me the impression that diagnostics from a validation run could remain valid across open/close for project based languages, as long as the file didn't change. As a corollary, I also noticed that diagnostics will currently be published for all files in the project, even ones that aren't opened yet.

I'll probably be wrong though as the ticket is accepted. Thanks for filing it! :)

**Comment by mjlbach** [comment]
Diagnostics *can* persist, but `:e` effectively closes and reopens the file. The diagnostic module flushes the diagnostics when the buffer is closed, so it needs a new set of diagnostics. Servers send diagnostics upon upon a buffer, so the behavior will be consistent with what you desire.

I wouldn't be in favor of adding some sort of caching mechanism to work around this, as it would redundantly cache for almost all servers an identical set of diagnostics that would be sent after the didClose/didOpen cycle.

**Comment by wvanlint** [comment]
> Servers send diagnostics upon opening a buffer

I was mainly wondering whether the specification requires the server to do so and resend these diagnostics for project based languages if the file didn't change. I think this will be clarified in golang/go#50267 though.

**Comment by abenz1267** [comment]
I'm not sure IF this is related, but diagnostics also disappear for me when saving, but only if nothing has to be formatted. F.e. i have an error and text that needs to be formatter, i do `:w` > formatting happens, i do `:w` again > diagnostic disappear.

I'm on neovim stable.
