### ISSUE TITLE
[LSP Diagnostics Feature Enhancement] Add border color options for severity level (if possible)

### ISSUE THREAD

**Issue by zigotica** [neovim/neovim#16627]
### Feature already in Vim?

No

### Feature description

Hi.

We have `LspDiagnosticsFloatingError`,  `LspDiagnosticsFloatingWarning`,  `LspDiagnosticsFloatingInformation`and `LspDiagnosticsFloatingHint` to customise diagnostic text depending on the severity level. 

I would love to have border color be also customised. This could be done, either using a similar approach, or allowing `vim.lsp.util.open_floating_preview` to handle the severity level and intercept it to inject different border data into `opts` object, before the `return orig_util_open_floating_preview(contents, syntax, opts, ...)`. 

Thank you so much for the incredible neovim and LSP integration.

**Comment by clason** [comment]
The underlying API allows specifying custom highlight groups for borders, so this can already be done: From `:h nvim_open_win()`,

> By default, `FloatBorder` highlight is used, which links to `VertSplit` when not defined.
It could also be specified by character: `[{"+", "MyCorner"}, {"x", "MyBorder"} ]`.

I don't think we want to add more customization options in this direction, as it is rather niche; a plugin would be a better place to offer such customized UX.

**Comment by clason** [comment]
The sentiment seems to be shared by most of the devs, so I'm closing this issue. Feel free to ask on https://neovim.discourse.group if you have trouble setting this up yourself.

**Comment by zigotica** [comment]
Fair enough. I understand you cannot add stuff because a random guy on the internet. I have been reading through the vim and lsp APIs and help pages. Sorry, I still don't see the relation between the `nvim_open_win` and `vim.lsp.util.open_floating_preview` which is what I am using to open the diagnostics. 

In my mind, maybe because I'm just new with lua/neovim architecture, `vim.lsp.util.open_floating_preview`  would be a good place to _know_ the severity level, since it is there where I can modify the opts. Only data I am able to get there is `contents` and `syntax` (they return as strings). `opts` is empty at that point. 

To be clear, I am modifying the border color, but I cannot intercept the severity level so I can modify the color depending on that level. My code:

```lua
vim.cmd [[autocmd CursorHold * lua vim.diagnostic.open_float(nil, {focus=false})]]

local border = {
      {"🭽", "LspFloatWinBorder"},
      {"▔", "LspFloatWinBorder"},
      {"🭾", "LspFloatWinBorder"},
      {"▕", "LspFloatWinBorder"},
      {"🭿", "LspFloatWinBorder"},
      {"▁", "LspFloatWinBorder"},
      {"🭼", "LspFloatWinBorder"},
      {"▏", "LspFloatWinBorder"},
}

local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview
function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
  opts = opts or {height = 34}
  opts.border = opts.border or border
  return orig_util_open_floating_preview(contents, syntax, opts, ...)
end
```

I think adding a plugin to only do that is way overkill (besides, no plugin that I know of does this). 

Thank you again for your attention.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/lsp-diagnostics-how-and-where-to-retrieve-severity-level-to-customise-border-color/1679/1

**Comment by gpanders** [comment]
> This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:
> 
> https://neovim.discourse.group/t/lsp-diagnostics-how-and-where-to-retrieve-severity-level-to-customise-border-color/1679/1

@zigotica Did you make a post on Discourse? This link doesn't seem to work for me. I'd be happy to offer some pointers there if you did.

**Comment by zigotica** [comment]
@gpanders yes i did, but akismet took it. I was sent an email, but I thought I would give staff members some time. Thank you for asking.

> Hello,
>
> Our automated spam filter, Akismet, has temporarily hidden your post in LSP Diagnostics, how and where to retrieve severity level to customise border color for review.
> 
> A staff member will review your post soon, and it should appear shortly.
> 
> We apologize for the inconvenience.

**Comment by clason** [comment]
Yep, just un-flagged it. Bad spam bot!

**Comment by zigotica** [comment]
No prob! Thank you @clason
