### ISSUE TITLE
Executing `:normal` inside a function erases forced-motion information from `mode(1)` on 0.6

### ISSUE THREAD

**Issue by ggandor** [neovim/neovim#16621]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+617-g64abd7be7

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal

### $TERM environment variable

none

### Installation

build from repo

### How to reproduce the issue

Having the following script:
```vim
fun! DownByOne()
    echomsg mode(1)
    norm! j
    echomsg mode(1)
endfun
onoremap z :call DownByOne()<cr>
```

Do `y^Vz`.

### Expected behavior

```
no^V
no^V
```

### Actual behavior

```
no^V
no
```

**Comment by ggandor** [comment]
The output on 0.5.1 is as expected:

```
no^V
no^V
```

**Comment by zeertzjq** [comment]
I think your Vim version is too old. Latest Vim behaves the same.

**Comment by zeertzjq** [comment]
What's your Vim version?

**Comment by zeertzjq** [comment]
Oops, I didn't test it correctly.

**Comment by zeertzjq** [comment]
Oh, I did.

**Comment by zeertzjq** [comment]
I think your Vim version is too old. Latest Vim behaves the same. What's your Vim version?

**Comment by ggandor** [comment]
Indeed, I used the latest stable version, but 8.2.3779 behaves the same way as Nvim 0.6.

**Comment by zeertzjq** [comment]
Bisected to patch 8.2.2938

<https://github.com/vim/vim/commit/21492743e80c6740bac65a91311c28bede8ef2f8>
<https://github.com/neovim/neovim/commit/b35de6c525e7c8ad9d64d42f57f348dff608b9e5>

**Comment by zeertzjq** [comment]
I've reported this to Vim: <https://github.com/vim/vim/issues/9332>.

**Comment by zeertzjq** [comment]
This intended behavior.
