### ISSUE TITLE
Position virtual text at both eol and right align

### ISSUE THREAD

**Issue by imcaizheng** [neovim/neovim#16634]
### Feature already in Vim?

No.

### Feature description

`nvim_buf_set_extmark` allows virtual text to be positioned `right_aligned`. It ends up overlaying the normal text if a single line spans multiple rows, as shown like this:

``` neovim
┌───────────────────────────────────────────────────────────────────────┐
│line_too_looooooooooooooooooooooooooooooooooooooooooooooo[virtual_text]│
│ooooooooooog                                                           │
│                                                                       │
│                                                                       │
│                                                                       │
│                                                                       │
└───────────────────────────────────────────────────────────────────────┘
```

What I'm expecting is the virtual text automatically being shifted to the eol row. Just like below:

``` neovim
┌───────────────────────────────────────────────────────────────────────┐
│line_too_looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo│
│ooooooooooog                                             [virtual_text]|
│                                                                       │
│                                                                       │
│                                                                       │
│                                                                       │
└───────────────────────────────────────────────────────────────────────┘
```

**Comment by clason** [comment]
Virtual text is an "overlay", it doesn't take the actual text into account. If you tell it to draw the text on a given line and columns, that's where it will get drawn. There is _no_ "automatic shifting"; that needs to be taken care of by the higher-level functions that call `nvim_buf_extmark`.

**Comment by imcaizheng** [comment]
If virtual text is configured to be positioned at `eol` it does aware of the actual text. The result will look like this:
``` vim
┌───────────────────────────────────────────────────────────────────────┐
│line_too_looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo│
│ooooooooooog [virtual_text]                                            |
│                                                                       │
│                                                                       │
│                                                                       │
│                                                                       │
└───────────────────────────────────────────────────────────────────────┘
```

So put it simple I'm looking for a combination of `eol` and `right_aligned` for virtual text.

**Comment by clason** [comment]
Could you add a concrete reproducing example to show what you think is not working correctly?

**Comment by clason** [comment]
It looks to me more like an issue of `right_aligned` in combination with `wrap`.

**Comment by zeertzjq** [comment]
It can also be added as another value of `virt_text_pos`. The documentation of `right_align` is not very clear.

**Comment by imcaizheng** [comment]
Hope it clarifies my intention below.

I tried to make a popup window to show all files being loaded. The popup window looks like this:
![https://i.imgur.com/7q8rA4i.png](https://i.imgur.com/7q8rA4i.png)

File type info is added as virtual text right aligned the window. When the filename is too long(the last item shown on the screenshot), virtual text starts overlaying the filename, which is of course not desired.

As a comparison, if I set `virt_text_pos = 'eol'` then file type info shows up immediately after its filename regardless the length of the filename.
![https://i.imgur.com/hC6XoCw.png](https://i.imgur.com/hC6XoCw.png)

What I want is when `virt_text_pos` is set to `right_aligned` it behaves like when `virt_text_pos` is set to `eol` but right aligned to the window.

**Comment by clason** [comment]
Yeah, so it's (potentially) a bug with `right_aligned` if `wrap` is set -- the screen line where the virtual text is drawn does not correspond to the screen line where the _buffer_ line ends.

**Comment by zeertzjq** [comment]
In this case the length of each lines is fixed, so I think you can just put the extmark on the last column?

**Comment by zeertzjq** [comment]
Oh this is indeed a bug. Even when the extmark is on the second screen line occupied by that text line, the virtual text is still on the first screen line.
