### ISSUE TITLE
Resize windows by giving a percentage of the screen size.

### ISSUE THREAD

**Issue by jeremycostanzo** [neovim/neovim#16635]
### Feature already in Vim?

No (tested in 8.2.2434)

### Feature description

Window resizing is a pain, the parameter N given to `N c-w |` or `N c-w _` should be a percentage of the screen height / width.
We could also keep the default behavior but have an option which would allow to give a percentage to this option.

Sorry if this already exists, I couldn't find anything for this in the opened issues or in the manual.

**Comment by gpanders** [comment]
The defaults are not likely to change, and I don't think a new option is likely either. You can float the idea upstream to Vim and see how Bram feels about it: we would port any changes they made.

Best course is to create your own mappings or commands that do this: if you need help with that, the [Neovim Discourse](https://neovim.discourse.group) is the place to ask.
