### ISSUE TITLE
Diagnostics from sourcekit-lsp do not update after running `swift build`

### ISSUE THREAD

**Issue by heygarrett** [neovim/neovim#16641]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+nightly-1242-gf37c5f180

### Language server name/version

SourceKit-LSP, packaged with Xcode 13

### Operating system/version

macOS 12.0.1

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: sourcekit: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /Users/garrett/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'
```

### Steps to reproduce using "nvim -u minimal_init.lua"

- Create a Swift package with `swift package init --type executable`  
- In `main.swift` call a function that doesn't exist  
- Define the function in a new Swift file   
- Run `swift build`

### Expected behavior

The error for the undefined function in `main.swift` would disappear after defining the function in a different file and then running `swift build`, unless I'm misunderstanding [Indexing While Building](https://github.com/apple/sourcekit-lsp#indexing-while-building).

### Actual behavior

The error remains until making, and undoing, a change in `main.swift` (I normally do `o<esc>dd`) or until running `:LspRestart`.

### Log file

https://gist.github.com/heygarrett/1bf20e2313e1c12667008590451c3936

**Comment by mjlbach** [comment]
Can you reproduce the issue on vscode? The snippet linked does not imply to me that the language server will automatically push diagnostics on file change, but this may also be closed by https://github.com/neovim/neovim/pull/16214

**Comment by mjlbach** [comment]
The same problem occurs on vscode, you can report to the sourcekit team (although I can't find the issue tracker for them)
