### ISSUE TITLE
use defaults from sensible.vim

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1664]
Neovim should use most or all defaults from https://github.com/tpope/vim-sensible.

~~These should *not* change the option defaults in `options.c` `vimoption` struct, because that changes the behavior of `set all&` (unless there's a way around this). Rather, `main.c` should simply set these options before loading `.nvimrc`.~~

This issue specifically is in regards to sensible.vim. Use https://github.com/neovim/neovim/issues/276 for discussion of any other defaults.

**Comment by trusktr** [comment]
Wow, eigenvim is cool. Very insightful.

**Comment by fmoralesc** [comment]
@justinmk Can we close this in favor of #2676?
