### ISSUE TITLE
Missing --not-a-term cli flag

### ISSUE THREAD

**Issue by knpwrs** [neovim/neovim#16652]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

no, vim 8.2 (2019 Dec 12) behaves as expected

### Operating system/version

macOS 12.0.1

### Terminal name/version

Alacritty 0.9.0

### $TERM environment variable

```
xterm-256color
```

### Installation

```
brew install neovim
```

### How to reproduce the issue

Run the following from a shell:

```
nvim --not-a-term
```

### Expected behavior

neovim should start

### Actual behavior

neovim prints `nvim: Unknown option argument: "--not-a-term"`. Note that there are instances of `--not-a-term` in this repo: https://github.com/neovim/neovim/search?q=%22--not-a-term%22&type=code; however, `--not-a-term` does not appear in `:h startup-options` (though it does in regular vim). Was `--not-a-term` merged in after `0.6.0` was released?

**Comment by clason** [comment]
I think those are artifacts from automatic merging of upstream patches (note that most of the occurrences are in translations and test files that are not directly applicable to Neovim).

So this is an incompatible (N/A) upstream feature; I think you want `--headless` instead.

**Comment by knpwrs** [comment]
When I run `nvim --headless -e +"redir>>/dev/stdout | map | redir END" -scq` from my shell I get a listing of keymaps configured for `nvim`; however, when I run it from a non-shell (e.g., via [Rust's Command](https://doc.rust-lang.org/stable/std/process/struct.Command.html) or [Node's execa](https://www.npmjs.com/package/execa)) I get no output. Is there a way to capture the output from an ex command from an external program without a PTY or TTY?

**Comment by knpwrs** [comment]
Actually I got it working by changing some quoting! Instead of passing `"+\"redir>>/dev/stdout | map | redir END\""` as one string argument I passed `"-c"` and `"redir>>/dev/stdout | map | redir END"` as separate string arguments.

Thank you!
