### ISSUE TITLE
Neovim 0.6.0 creates "$XDG_CACHE_HOME" folder in random places in my home dir

### ISSUE THREAD

**Issue by spcbfr** [neovim/neovim#16651]
### Neovim version (nvim -v)

NVIM v0.6.0

### Vim (not Nvim) behaves the same?

no, im 8.2

### Operating system/version

Arch Linux

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

system package manager

### How to reproduce the issue

1. open neovim
2. that's it

### Expected behavior

no random folders to be created

### Actual behavior

neovim creates a folder litterly called $XDG_CACHE_HOME inside random folders which has this a folder called vim and a file "info". I knew this was a neovim issue because the file had this in the top `1   │^A�a��XJ��generator�^Dnvim�version�^KNVIM v0.6.0�max_kbyte`

**Comment by clason** [comment]
Does this happen with `nvim --clean`?

**Comment by spcbfr** [comment]
doesnt seem like it, so it seems to be a problem with my configuration then..

**Comment by spcbfr** [comment]
I'll close this issue for now and investigate more with my configuration on my own
