### ISSUE TITLE
LSP throws diagnostic error using eslint with two signs

### ISSUE THREAD

**Issue by ram02z** [neovim/neovim#16673]
### Neovim version (nvim -v)

v0.7.0-dev

### Language server name/version

eslint v8.4.1

### Operating system/version

Linux 5.15.8_1

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: html: configuration checked.
  - INFO: eslint: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: lean3ls: configuration checked.
  - INFO: pyright: configuration checked.
  - INFO: cssls: configuration checked.
```

### Steps to reproduce using "nvim -u minimal_init.lua"

(This probably won't work until I setup a minimal repro)
1. Open this [file](https://gist.github.com/ram02z/e85910e6b8aa1044637607c5c950f595)
2. Error will be presented

My judgement of the error is probably very wrong since I have not been able to create a basic reproduction file.

### Expected behavior

No error

### Actual behavior

![image](https://user-images.githubusercontent.com/59267627/146284757-d3eddd42-c459-4239-9ada-dd8ad5e2840c.png)

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/highlight.lua:33: attempt to compare nil with number    
stack traceback:
        /usr/share/nvim/runtime/lua/vim/highlight.lua:33: in function 'range'
        /usr/share/nvim/runtime/lua/vim/diagnostic.lua:896: in function 'show'
        /usr/share/nvim/runtime/lua/vim/diagnostic.lua:1131: in function 'show'
        /usr/share/nvim/runtime/lua/vim/diagnostic.lua:656: in function 'set'
        /usr/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:209: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:735: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

This is line 33:
```lua
  -- sanity check
  if start[2] < 0 or finish[1] < start[1] then return end
```

I simply changed it to the following. The error went away and the highlights were correct.
```lua
if not start[2] or start[2] < 0 or finish[1] < start[1] then return end
```

I am using custom diagnostic logic:
https://github.com/ram02z/dotfiles/blob/master/dot_config/nvim/lua/modules/diagnostic.lua
https://github.com/ram02z/dotfiles/blob/master/dot_config/nvim/plugin/40-autocommands.vim#L57-L62

However, disabling the custom diagnostic logic doesn't fix the error.

### Log file

https://gist.github.com/ram02z/b11a3bbd53211d0199a13b32ad1e7a81

**Comment by gpanders** [comment]
Some of the diagnostics that are being sent by the language server don’t include a column in the range. This is a bug in the language server, but we should probably still check for this to avoid errors from misbehaving servers.

**Comment by gpanders** [comment]
@ram02z Please report this bug upstream to eslint. In general, our policy is not to work around bugs in language servers, so they need to fix this on their end.

**Comment by ram02z** [comment]
> @ram02z Please report this bug to eslint. In general, our policy is not to work around bugs in language servers, so they need to fix this on their end.

Sure. What is the bug however? Is it that the column key is missing sometimes?

**Comment by gpanders** [comment]
> Sure. What is the bug however? Is it that the column key is missing sometimes?

Yes. Any diagnostics sent should have both a `line` and `character`. Eslint is sending diagnostics without a `character` field.

**Comment by gpanders** [comment]
This is no longer actionable on our end, so I'm going to close the issue.

**Comment by ram02z** [comment]
I have opened an issue (https://github.com/microsoft/vscode-eslint/issues/1393). However, it will probably take a while for a new release to happen, so I am wondering if there is a quickfix I can apply locally without having to patch neovim's runtime files because files affected by this issue are unusable.

**Comment by gpanders** [comment]
In the meantime, you can add this to your `init.lua`:

```lua
vim.diagnostic.set = (function(orig)
    return function(namespace, bufnr, diagnostics, opts)
        for _, v in ipairs(diagnostics) do
            v.col = v.col or 0
        end
        return orig(namespace, bufnr, diagnostics, opts)
    end
end)(vim.diagnostic.set)
```

(If this doesn't work or if you have any follow up questions, please ask on Matrix or Discourse. You can ping me if you need to).
