### ISSUE TITLE
Visual block paste bug

### ISSUE THREAD

**Issue by Manish0925** [neovim/neovim#16676]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

yes, 8.2.3811

### Operating system/version

Windows 11

### Terminal name/version

windows terminal 1.11.2921.0

### $TERM environment variable

xterm-256color

### Installation

chocolatey

### How to reproduce the issue

select text to be pasted in visual mode
pasting it at the beginning or somewhere in between in new few line(s) visual block mode
The character after which the visual block pointed is no more there

### Expected behavior

select text to be pasted in visual mode
pasting it at the beginning or somewhere in between in new few line(s) visual block mode
The character after which the visual block pointed should be present intact

### Actual behavior

select text to be pasted in visual mode
pasting it at the beginning or somewhere in between in new few line(s) visual block mode
The character after which the visual block pointed is no more there

**Comment by clason** [comment]
Please add _concrete_, minimal steps to reproduce the issue (and make sure these work with `nvim --clean`!)

**Comment by zeertzjq** [comment]
What you mean? Can you be more specific?

**Comment by Manish0925** [comment]
Suppose I have the following lines:
"""
line1
line2
line3
"""
I want to prepped line1 to line2 and line3, so I select and yank line1 and
then go to visual block mode and then click P for prepending line1
Expected results:
"""
line1
line1line2
line1line3
"""

Obtained results:
"""
line1
line1ine2
line1ine3
"""

**Comment by zeertzjq** [comment]
That's the intended behavior. See `:h put-Visual-mode`.

**Comment by Manish0925** [comment]
> That's the intended behavior. See `:h put-Visual-mode`.

**Comment by Manish0925** [comment]
How to obtain the desired output then? Bit confused since that is what happens when prepending one line at a time without visual block mode. Any help would be hugely appreciated

**Comment by zeertzjq** [comment]
Paste on every line.

**Comment by zeertzjq** [comment]
Paste on every line.
