### ISSUE TITLE
K command does not show output

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#16692]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

No, Vim does not have this issue

### Operating system/version

macOS 12.0.1

### Terminal name/version

Terminal.app 2.12

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

```vim
:set keywordprg=echo
```
Enter insert mode and type "hello".

Exit insert mode and press `K` with the cursor over the word "hello".

### Expected behavior

The word "hello" would appear as the output of the `echo` program.

### Actual behavior

Output flickers on and off quickly, but is not retained. It is not on screen long enough to read.

When I change the `keywordprg` to `cat`, which results in a non-zero return code and an error message since there is no file "hello", the output is retained on screen.

### Additional information

The example above is intended as a minimal reproducible example of the issue, as opposed to being an actual use case where I encountered the problem.

I noticed this issue when using [fugitive.vim](https://github.com/tpope/vim-fugitive), which sets the `keywordprg` to `git --git-dir=... show`. When pressing `K` on a commit hash, I found that the information would be shown when the output was long enough to result in paging, but would not show otherwise.

**Comment by zeertzjq** [comment]
This can a bit hard to deal with, as for some programs (e.g. `man`) the current behavior is intended, while for some other programs (e.g. `echo`, `cat`) this is not.

**Comment by zeertzjq** [comment]
I checked Vim's behavior and it always shows an hit-enter prompt. To match Vim's behavior better, we just need to remove these lines:
<https://github.com/neovim/neovim/blob/b1757e1c29d07c7958c62427e19e85916670049d/src/nvim/normal.c#L4432-L4435>

**Comment by zeertzjq** [comment]
@gpanders What do you think should be done here?

**Comment by gpanders** [comment]
I am fine with removing those lines. To be honest, I don't remember why I did it that way in the first place.

In https://github.com/neovim/neovim/pull/15398 Justin requested that I "add a buffer-local `:tnoremap <esc>` which kills the buffer". So if we remove the autocommand we should update the `<Esc>` mapping to also close the buffer (this is probably what should have been to begin with).

**Comment by mjlbach** [comment]
Closed by #17046?
