### ISSUE TITLE
Glitches when running nvim under tmux

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#1669]
I have some intermitent (I just now tried to reproduce, without success, while some minutes ago the problem presented itself constantly) glitches when running nvim under tmux. Here are some screenshots:

outside tmux:

![captura de pantalla de 2014-12-14 18 48 53](https://cloud.githubusercontent.com/assets/221465/5429212/e937b576-83c1-11e4-84c4-ee15486529aa.png)

inside tmux:

![captura de pantalla de 2014-12-14 18 49 09](https://cloud.githubusercontent.com/assets/221465/5429215/025a7a34-83c2-11e4-8164-155945661e81.png)

I have 

    set t_ut=
    set t_ZH=[3m
    set t_ZR=[23m

in my vimrc

**Comment by cvlmtg** [comment]
I'm having other kind of issues. under tmux/osx the mouse scrollwheel inserts random characters.
Am I the only one? google didn't found anything...

**Comment by fmoralesc** [comment]
PR #1820 fixes these issues, btw.

**Comment by justinmk** [comment]
Yay! :)

**Comment by fmoralesc** [comment]
Fixed by #1820
