### ISSUE TITLE
Linux - crash after startup: PANIC: unprotected error in call to Lua API 

### ISSUE THREAD

**Issue by twidxuga** [neovim/neovim#16709]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+741-gff1b0f632

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux - 5.15.8-arch1-1 #1 SMP PREEMPT Tue, 14 Dec 2021 12:28:02 +0000 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.10.0-dev (58985a4d)

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

`nvim -u none`
<press any key>

### Expected behavior

Vim starts normally and doesn't crash

### Actual behavior

Vim crashes with the error

`PANIC: unprotected error in call to Lua API (bad argument #3 to '?' (function expected, got nil))`

**Comment by clason** [comment]
Can you add the exact build steps you use? (Make sure to `make distclean` and `make install` when building.)

**Comment by twidxuga** [comment]
`make distclean && make -j 6 CMAKE_BUILD_TYPE=Release`

**Comment by clason** [comment]
try without the `-j` (you should have `ninja` installed, which parallelizes automatically)

**Comment by twidxuga** [comment]
Just checked without the -j 6, and obtained the same behaviour, i.e. crash. I compiled nvim yesterday and all was fine.

I also notice that after the crash the terminal output is jumbled. I need to use `reset` to make it go back to normal.

Additionally, if I run it with my own `init.vim` instead of  `nvim -u none`,  I get a stack of errors related to lua libraries not being found. 

Note that: 
```
$ echo $LUA_PATH                                                                  
/usr/local/share/nvim/runtime/lua;
```

And the errors that I get when starting `nvim` are:
```
Error detected while processing /home/twidxuga/.config/nvim/init.vim:
line  378:
E5108: Error executing lua error loading module 'telescopeconfig' from file '/usr/local/share/nvim/runtim
e/lua':
        cannot read /usr/local/share/nvim/runtime/lua: Is a directory
stack traceback:
        [C]: at 0x55a2dfbbcf60
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
line  748:
E5108: Error executing lua error loading module 'lspcfg' from file '/usr/local/share/nvim/runtime/lua':
        cannot read /usr/local/share/nvim/runtime/lua: Is a directory
stack traceback:
        [C]: at 0x55a2dfbbcf60
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
line  752:
E5108: Error executing lua error loading module 'nvim-cmp' from file '/usr/local/share/nvim/runtime/lua':

        cannot read /usr/local/share/nvim/runtime/lua: Is a directory
stack traceback:
        [C]: at 0x55a2dfbbcf60
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
line  755:
E5108: Error executing lua error loading module 'treesitter' from file '/usr/local/share/nvim/runtime/lua
':
        cannot read /usr/local/share/nvim/runtime/lua: Is a directory
stack traceback:
        [C]: at 0x55a2dfbbcf60
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
line  796:
E5108: Error executing lua error loading module 'colorizer' from file '/usr/local/share/nvim/runtime/lua'
:
        cannot read /usr/local/share/nvim/runtime/lua: Is a directory
stack traceback:
        [C]: at 0x55a2dfbbcf60
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
Error detected while processing /home/twidxuga/.config/nvim/plugged/nvim-lspconfig/plugin/lspconfig.vim:
line   16:
E5108: Error executing lua error loading module 'lspconfig' from file '/usr/local/share/nvim/runtime/lua'
:
        cannot read /usr/local/share/nvim/runtime/lua: Is a directory
stack traceback:
        [C]: at 0x55a2dfbbcf60
        [C]: in function 'require'
        [string ":lua"]:9: in main chunk
Error detected while processing /home/twidxuga/.config/nvim/plugged/nvim-treesitter/plugin/nvim-treesitte
r.vim:
line   15:
E5108: Error executing lua error loading module 'nvim-treesitter' from file '/usr/local/share/nvim/runtim
e/lua':
        cannot read /usr/local/share/nvim/runtime/lua: Is a directory
stack traceback:
        [C]: at 0x55a2dfbbcf60
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

**Comment by clason** [comment]
Yes, I assumed that this is related to https://github.com/neovim/neovim/pull/16631. Not sure why this fails for you, as you use the provided build scripts and the bundled dependencies. Can you make sure that this is indeed the case, and all the build dependencies (cmake etc.) are up-to-date (which version)?

**Comment by clason** [comment]
It would be very helpful if you could bisect to the actual commit that introduced the build failure for you.

**Comment by twidxuga** [comment]
Good suggestions. Will report back soon.

**Comment by gpanders** [comment]
Please also provide the full build log (i.e. the entire output of running `make` **after** running `make distclean`).

**Comment by twidxuga** [comment]
Build log attached:
[nvim-build.log](https://github.com/neovim/neovim/files/7739645/nvim-build.log)

Will look at the other items.

**Comment by gpanders** [comment]
This is the issue

```
/home/twidxuga/Apps/neovim/.deps/usr/bin/luajit: unknown luaJIT command or jit.* modules not installed
/home/twidxuga/Apps/neovim/.deps/usr/bin/luajit: unknown luaJIT command or jit.* modules not installed
/home/twidxuga/Apps/neovim/.deps/usr/bin/luajit: unknown luaJIT command or jit.* modules not installed
/home/twidxuga/Apps/neovim/.deps/usr/bin/luajit: unknown luaJIT command or jit.* modules not installed
/home/twidxuga/Apps/neovim/.deps/usr/bin/luajit: unknown luaJIT command or jit.* modules not installed
```

Related #16659.

**Comment by twidxuga** [comment]
Not sure if this is still needed, but looking at the [dependencies for Arch](https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites): 

`sudo pacman -S base-devel cmake unzip ninja tree-sitter curl`

**The versions I have installed are:**
automake (GNU automake) 1.16.5
cmake version 3.22.1
gcc (GCC) 11.1.0
UnZip 6.00 of 20 April 2009
ninja 1.10.2
tree-sitter 0.20.1
curl 7.80.0 (x86_64-pc-linux-gnu) libcurl/7.80.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.46.0

Let me know if I'm missing something. Now to spot the commit that broke it.

**Comment by twidxuga** [comment]
Confirmed that this issue was introduced in commit 4240ce8eb38ee9c89ce8694faab37e8db8fca209

It is actually from Thursday, not Friday, as I originally thought.

**Comment by cvlmtg** [comment]
It happens for me too, on macOS 11.6.1, with nvim build with `brew install --build-from-source --HEAD neovim`

**Comment by zeertzjq** [comment]
Does it crash with `nvim --clean`?

**Comment by zeertzjq** [comment]
Note: `nvim -u none` reads from file `none`. You should use `nvim -u NONE` or `nvim --clean` to run without config.

Does this error happen if you run `VIMRUNTIME=./runtime ./build/bin/nvim` after building in the cloned Git repository?

**Comment by zeertzjq** [comment]
> $ echo $LUA_PATH
> /usr/local/share/nvim/runtime/lua;

Where does this environment variable come from?

**Comment by twidxuga** [comment]
I set it in my `.environment` file that is loaded when the shell starts (e.g. as if it was set in `.zshrc` or `.bashrc`).  If memory serves, it is needed so that nvim lsp knows where `lspcfg.lua`, `treesitter.lua`, etc. are. Not something that I changed recently.

Neovim will still crash even if LUA_PATH is unset.

**Comment by twidxuga** [comment]
> Does this error happen if you run `VIMRUNTIME=./runtime ./build/bin/nvim` after building in the cloned Git repository?

Confirmed, yes it does crash.

**Comment by twidxuga** [comment]
> Note: `nvim -u none` reads from file `none`. You should use `nvim -u NONE` or `nvim --clean` to run without config.

Noted and thanks!

**Comment by gpanders** [comment]
@twidxuga Try rebuilding with `LUA_PATH` unset.

```console
$ unset LUA_PATH
$ make distclean
$ make
```

While trying to figure out what's going on here I've found that `LUA_PATH` modifies `luajit`'s ability to detect the `jit.bcsave` module. If it can't find it, you get the 

```
/home/twidxuga/Apps/neovim/.deps/usr/bin/luajit: unknown luaJIT command or jit.* modules not installed
```

error that you're seeing. See #16714.

**Comment by gpanders** [comment]
Should be fixed by #16714.

**Comment by twidxuga** [comment]
> Try rebuilding with `LUA_PATH` unset.

I was already doing that inside my build script. I've found it to be needed a long time ago. All my builds are made with unset LUA_PATH. I guess I should have mentioned that.

**Comment by clason** [comment]
Please test the latest commit on master and confirm whether it's still broken.

**Comment by twidxuga** [comment]
I just did a new pull and build, and nvim is fully working now! It seems like #16714 did it!

Thank you very much guys. You rock!
