### ISSUE TITLE
wrong tag for nvim_open_win() in vim.lsp.handlers.hover

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#16718]
### Neovim version (nvim -v)

v0.7.0-dev+717-gf37c5f180

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

binary release

### How to reproduce the issue

The doc on `vim.lsp.handlers.hover`:

```
hover({_}, {result}, {ctx}, {config})               *vim.lsp.handlers.hover()*
                |lsp-handler| for the method "textDocument/hover" >

                 vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(
                   vim.lsp.handlers.hover, {
                     -- Use a sharp border with `FloatBorder` highlights
                     border = "single"
                   }
                 )
<

                Parameters: ~
                    {config}  table Configuration table.
                              • border: (default=nil)
                                • Add borders to the floating window
                                • See |vim.api.nvim_open_win()|
```

The tag for `nvim_open_win()` is wrong, we do not need `vim.api`, just `nvim_open_win()` is enough.

### Expected behavior

I can use `:h vim.api.nvim_open_win()` to check the function doc.

### Actual behavior

> E149: sorry, no help for vim.api.nvim_open_win()

**Comment by gpanders** [comment]
Closed by #16719
