### ISSUE TITLE
Build fails with cmake 2.8.12; needs 3.10

### ISSUE THREAD

**Issue by ctranstrum** [neovim/neovim#16720]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Amazon Linux 2

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

build

### How to reproduce the issue

download the 0.6 source, untar, cd to the directory, and enter the build command "make CMAKE_BUILD_TYPE=Release"

### Expected behavior

compilation succeeds, since the Build prerequisites at https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites state that cmake 2.8.12 should work.

### Actual behavior

After a long period of building, it finally gets to 100%, and then promptly fails with this message:
```
[100%] Built target treesitter-c
make[2]: Leaving directory `/home/ec2-user/src/neovim-0.6.0/.deps'
make[1]: Leaving directory `/home/ec2-user/src/neovim-0.6.0/.deps'
cd build && cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release  /home/ec2-user/src/neovim-0.6.0/
CMake Error at CMakeLists.txt:6 (cmake_minimum_required):
  CMake 3.10 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
make: *** [build/.ran-cmake] Error 1
```

**Comment by clason** [comment]
Thank you; that bump was deliberate, but we forgot to update the information on the Wiki -- which I just did.
