### ISSUE TITLE
Calling nvim_buf_call within an `on_lines` handler added with nvim_buf_attach causes Ctrl-A and Ctrl-X to misbehave

### ISSUE THREAD

**Issue by dmitmel** [neovim/neovim#16729]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

pacman, official repositories

### How to reproduce the issue

1. Open an empty buffer
2. Run this Lua code:
   ```lua
   vim.api.nvim_buf_attach(0, false, {
     on_lines = function()
       vim.api.nvim_buf_call(0, function() end)
     end,
   })
   ```
3. Type `test 0` in Insert mode
4. Exit the Insert mode
5. Press Ctrl-A

Here's a script which automates this process:

```vim
function! Test() abort
  enew
  lua <<EOF
  vim.api.nvim_buf_attach(0, false, {
    on_lines = function()
      vim.api.nvim_buf_call(0, function() end)
    end,
  })
EOF
  call nvim_input("itest 0\<Esc>\<C-a>")
endfunction
autocmd VimEnter * call Test()
```

It can be used with `nvim -u repro.vim`

(Interestingly enough, the bug only happens with the number 0 and not others.)

### Expected behavior

The buffer contains text `test 1`.

### Actual behavior

The buffer contains text `test1` instead (without the whitespace in between).

**Comment by zeertzjq** [comment]
I tested this, and this bug happens with any number, but only at the end of a line.

**Comment by zeertzjq** [comment]
This bug also only applies to Normal mode CTRL-A and CTRL-X. Visual mode ones work fine.

**Comment by zeertzjq** [comment]
The white space is actually moved after the number. If the whitespace is removed, then the `t` is moved after the number instead.

**Comment by zeertzjq** [comment]
It appears `op_addsub()` requires the cursor to be on the NUL character on the eol in the middle of its operation, but `nvim_buf_call()` doesn't allow that and moves cursor to the last character. If `'virtualedit'` contains `onemore` the this bug doesn't happen.

**Comment by zeertzjq** [comment]
I guess buffer update callbacks shouldn't be allowed to change cursor position?

**Comment by zeertzjq** [comment]
I think buffer updates callback should not be allowed to change cursor position. However, this can be tricky, as cursor position is stored per window, not per buffer.

**Comment by dmitmel** [comment]
> This bug also only applies to Normal mode CTRL-A and CTRL-X. Visual mode ones work fine.

I forgot to specify, Ctrl-A is invoked from the Normal mode (the automatic script switches to the Normal mode first).
