### ISSUE TITLE
StatusLineTerm and StatusLineTermNC have no effect

### ISSUE THREAD

**Issue by davidwoodburn** [neovim/neovim#16739]
### Neovim version (nvim -v)

0.6.0, Release, +acl +iconv +tui

### Vim (not Nvim) behaves the same?

No, vim 8.2.2671 works correctly

### Operating system/version

macOS 12.0.1

### Terminal name/version

Apple Terminal v2.12

### $TERM environment variable

xterm-256color

### Installation

brew install nvim

### How to reproduce the issue

nvim --clean
:term
<c-\><c-n>
:hi StatusLineTerm ctermfg=234 ctermbg=112

### Expected behavior

It is expected that while in a term window, the status line should have a green background with dark gray text as the hilite command specifies.

### Actual behavior

This has no effect in NeoVim.  It does have an effect in Vim.

**Comment by clason** [comment]
This is by design: `:h hl-StatusLineTerm`

**Comment by davidwoodburn** [comment]
My bad.  Thank you for the help.
