### ISSUE TITLE
C++ indenting does not respect cinoptions 'N' flag with inline namespaces

### ISSUE THREAD

**Issue by willeccles** [neovim/neovim#16746]
### Neovim version (nvim -v)

v0.6.0-dev+4c4353c32-dirty

### Vim (not Nvim) behaves the same?

yes, vim 8.2

### Operating system/version

macOS, Linux 5.x

### Terminal name/version

Alacritty, Windows Terminal (WSL) 1.11.3471.0, Linux console

### $TERM environment variable

xterm-256color, linux

### Installation

built from source

### How to reproduce the issue

(Note: I don't recall the full set of commands/options to enable syntax highlighting/filetype plugins, so insert those into this list of steps as appropriate.)
```
nvim --clean
:set ft=cpp
:set cindent
:set cinoptions=N-s
```

Now insert `namespace X {` and press enter--the cursor will correctly be positioned at the very beginning of the next line and not after an indent. This is the expected behavior.

However, if you insert `inline namespace X {` and press enter, the cursor will be placed on the next line indented like any other block (exact amount depends on your shift width and whatnot, but some indent should be present).

### Expected behavior

Following the steps above, the new line after the opening `{` of the inline namespace should not be indented. Essentially, the output should look like this after pressing the enter key:
![image](https://user-images.githubusercontent.com/3360049/146998231-697d8a54-30e4-42be-b11b-8cf9f82aea1e.png)

### Actual behavior

The namespace is indented, contrary to the settings specified in `cinoptions`. The actual result looks like this (note that in this screenshot the trailing whitespace is highlighted in red and indicated with a +, and I indent with two spaces):
![image](https://user-images.githubusercontent.com/3360049/146998334-ea156205-28e4-4dfb-83a6-c314c2c07628.png)

**Comment by willeccles** [comment]
Some answers to questions you may have:
1. I build from source using my own fork (see #13709)
2. It's dirty because I apply a crude patch to comment two lines of code relating to searching, but nothing else is modified
3. I do not use LSP or anything else which may influence code formatting; this is purely the builtin cindent

**Comment by zeertzjq** [comment]
This look easy to fix, but it needs to be fixed in Vim first.

**Comment by zeertzjq** [comment]
BTW this is my fix:
```diff
diff --git a/src/nvim/indent_c.c b/src/nvim/indent_c.c
index faa9b38cf..bd27e39ca 100644
--- a/src/nvim/indent_c.c
+++ b/src/nvim/indent_c.c
@@ -541,6 +541,11 @@ static bool cin_is_cpp_namespace(char_u *s)
   bool has_name_start = false;
 
   s = cin_skipcomment(s);
+
+  if (STRNCMP(s, "inline", 6) == 0 && (s[6] == NUL || !vim_iswordc(s[6]))) {
+    s = cin_skipcomment(skipwhite(s + 6));
+  }
+
   if (STRNCMP(s, "namespace", 9) == 0 && (s[9] == NUL || !vim_iswordc(s[9]))) {
     p = cin_skipcomment(skipwhite(s + 9));
     while (*p != NUL) {
```

I'll make a Vim patch later.

**Comment by zeertzjq** [comment]
<https://github.com/vim/vim/pull/9383>
