### ISSUE TITLE
large files (28mb json) crash Neovim (but open in Vim)

### ISSUE THREAD

**Issue by BoilingSoup** [neovim/neovim#16744]
### Neovim version (nvim -v)

0.6

### Vim (not Nvim) behaves the same?

No it doesn't behave the same. Vim 8.1

### Operating system/version

ubuntu 20.04

### Terminal name/version

terminator 1.91

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

Open a large file, 28mb in my case, in nvim causes the terminal to become unresponsive.

### Expected behavior

Vim opens the same file almost instantly. It looks like it lazy loads as I scroll down the file.
I was expecting something similar with neovim.

### Actual behavior

Opening the file in neovim turns the terminal to a blank screen, the computer fan runs loud, and I have to close the terminal.

**Comment by dundargoc** [comment]
Neovim opens a 30GB json file slightly faster for me under the same circumstances. Did you try opening the file with `nvim --clean` and then check how long it takes to start it? I suspect a plugin is the culprit in this case.

**Comment by BoilingSoup** [comment]
It is definitely a plugin causing it as the file opens instantly when I run nvim with the `--noplugin` flag.
Thanks for your help I will close this issue
