### ISSUE TITLE
E5113: Error while calling lua chunk: main.lua:2: attempt to index global 'mymodule' (a boolean value)

### ISSUE THREAD

**Issue by aliawan01** [neovim/neovim#16743]
### Neovim version (nvim -v)

NVIM v0.5.1

### Vim (not Nvim) behaves the same?

This is about neovim's implementation of lua which Vim does not support

### Operating system/version

Windows 10

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

I just installed the zip file containing the executable for Windows

### How to reproduce the issue

I don't know if this is just something which I am doing wrong, or if this is an actual bug in neovim. I have been trying to learn lua and I was on the part about modules. I have gone to my `nvim` directory which is located in `C:\Users\name_of_user\AppData\Local\nvim`.  I have created a directory in here called `lua` and I have made 2 files `main.lua` and `thing.lua`. In `thing.lua` I have the following code:
(This is how the directory tree looks like)
```
.
├── init.vim
└── lua
    ├── main.lua
    └── thing.lua
```
```
local mymodule = {}

function mymodule.foo()
    print("Hello World!")
end

return mymodule
```
In `main.lua` I have the following code:
```
local mymodule = require "thing"
mymodule.foo()
```

I have saved both files, however when I run `so %` in `main.lua` I get the following error:
```
E5113: Error while calling lua chunk: main.lua:2: attempt to index local 'mymodule' (a boolean value)
```

I have seen other tutorials and none of them seemed to have this issue. I would appreciate it if you could explain whether to me whether this is a bug in neovim or if it due to a lack of my understanding about how modules work in lua.

### Expected behavior

I want it to print out `Hello World!` when I run `so %` in `main.lua`

### Actual behavior

It just returns an error: 
```
E5113: Error while calling lua chunk: main.lua:2: attempt to index local 'mymodule' (a boolean value)
```

**Comment by zeertzjq** [comment]
1. v0.6.0 is the latest release. Does this happen in v0.6.0?
2. Does this happen if you rename `thing` to something else?

**Comment by aliawan01** [comment]
Yes, I have switched over to nvim v0.60 and the same issue persists.

**Comment by aliawan01** [comment]
When I restarted nvim, it suddenly worked. I think nvim was having some issue updating the file.

**Comment by aliawan01** [comment]
For some reason, whenever I change the code I need to restart nvim for it to run it properly.

**Comment by zeertzjq** [comment]
That's because once a module is `require()`ed, it is cached. `require()`ing an empty file returns `true`.

**Comment by aliawan01** [comment]
I added this line at the top of `main.lua` and the issue of me having to restart nvim for it to update the output still persists.
