### ISSUE TITLE
luafile command not working whereas source command works

### ISSUE THREAD

**Issue by RaZ0rr-Two** [neovim/neovim#16751]
### Neovim version (nvim -v)

NVIM v0.6.0 Build type: Release LuaJIT 2.0.5 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

nvim only

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.9.0 (fed349aa)

### $TERM environment variable

xterm-256color

### Installation

pacman ( arch official package repo )

### How to reproduce the issue

In my init.lua, the following works :
`vim.cmd [[ source ~/.config/nvim/lua/mappings/general.lua ]]`
whereas the the following shows error
`vim.cmd [[ luafile ~/.config/nvim/lua/mappings/general.lua ]]`

Manually entering the command inside nvim also works.
`:luafile ~/.config/nvim/lua/mappings/general.lua`

`require('mappings/general')` also works fine but I want to know why the former works and luafile fails.

### Expected behavior

No error

### Actual behavior

```nvim
Error detected while processing /home/razzor/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/razzor/.config/nvim/init.lua:
104: Vim(luafile):E5112: Error while creating lua chunk: cannot open /hom
e/razzor/.config/nvim/lua/mappings/general.lua : No such file or director
y
stack traceback:
        [C]: in function 'cmd'
        /home/razzor/.config/nvim/init.lua:104: in main chunk
```

**Comment by zeertzjq** [comment]
That's because you have a trailing space:
```
                                                        *:luafile*
:[range]luafile {file}
                        Execute Lua script in {file}.
                        The whole argument is used as the filename (like
                        |:edit|), spaces do not need to be escaped.
                        Alternatively you can |:source| Lua files.

                        Examples: >
                            :luafile script.lua
                            :luafile %
```

**Comment by RaZ0rr-Two** [comment]
`source` works fine with trailing spaces. Can `luafile` me made to work similarly?

**Comment by RaZ0rr-Two** [comment]
As of now, there's no alternative to say
```vim
source $HOME/.config/nvim/lua/mappings/general.lua | echo "loaded mappings"
```
because the following throws errors
```vim
luafile $HOME/.config/nvim/lua/mappings/general.lua | echo "loaded mappings"
```

**Comment by zeertzjq** [comment]
Changing this will break backward compatibility and compatibility with Vim.

**Comment by zeertzjq** [comment]
You can use:
```lua
vim.api.nvim_exec([[
luafile $HOME/.config/nvim/lua/mappings/general.lua
echo "loaded mappings"
]]]
```

**Comment by RaZ0rr-Two** [comment]
Alright.

Can `source` and `luafile` be used interchangeably for loading lua scripts ?
`:h luafile` indicates that it can be used interchangeably. But just wanted to confirm.

**Comment by RaZ0rr-Two** [comment]
> You can use:
> 
> ```lua
> vim.api.nvim_exec([[
> luafile $HOME/.config/nvim/lua/mappings/general.lua
> echo "loaded mappings"
> ]])
> ```

Thank you very much for the quick and very useful responses :1st_place_medal:
