### ISSUE TITLE
NeoVim stops my entire computer

### ISSUE THREAD

**Issue by rzksobhy78** [neovim/neovim#16760]
### Neovim version (nvim -v)

NVIM v0.6.0

### Vim (not Nvim) behaves the same?

didn't try vim before

### Operating system/version

5.15.10-arch1-1

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

xterm-256color

### Installation

sudo pacman -S --needed neovim python-pynvim

### How to reproduce the issue
It just happens and my computer stops

### Expected behavior

To not stop my entire computer

### Actual behavior

while I'm using Neovim my computer sometimes
stops entirely and I have to hard reset
and that only happens when I'm using Neovim
In the begging It happened like 2 times in 5 days and I ignore it
but It happened 3 times today and it only happens while I'm using Neovim

### My neovim config
https://github.com/rzksobhy78/nvim-config

**Comment by teto** [comment]
> It just happens and my computer stops

that doesn't help us really.:
- does `coredumpctl list` list neovim crashes ? 
- Look also in your journal for errors `journalctl`

Depending on your setting if neovim crashes and generate a coredump, it can make the laptop freeze. Should be short though. How long do you wait before hard resetting ? Does this phenomenon appear with `nvim -u NONE`  ?

**Comment by dundargoc** [comment]
Closing due to lack of response and because we lack enough information to actually do anything.
