### ISSUE TITLE
line cursor being green after updating to 0.6.0 from 0.5.1

### ISSUE THREAD

**Issue by popshia** [neovim/neovim#16778]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

no, vim 8.2.3489

### Operating system/version

macOS 12.2 Beta (21D5025f)

### Terminal name/version

iTerm2 3.4.15

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

open any file using `vim` filename
one workaround is to run `source $MYVIMRC` inside neovim again.

### Expected behavior

<img width="1440" alt="Screen Shot 2021-12-25 at 20 15 16" src="https://user-images.githubusercontent.com/3250328/147384658-09fc1a4e-cdf3-4491-b352-4807345d2d53.png">

### Actual behavior

<img width="1440" alt="Screen Shot 2021-12-25 at 20 16 03" src="https://user-images.githubusercontent.com/3250328/147384665-85fbf2c9-53a2-4fa6-9fbf-fba711f5f9b5.png">

**Comment by zeertzjq** [comment]
Can you test if this bug exists on nightly or HEAD build?

**Comment by zeertzjq** [comment]
Also, this is not **minimal** steps to reproduce.

**Comment by popshia** [comment]
> Can you test if this bug exists on nightly or HEAD build?

yes it still exist.

**Comment by popshia** [comment]
> Also, this is not **minimal** steps to reproduce.

Sorry about that, I'm quite new here, I'm not quite sure what kind of steps should I provide.

**Comment by zeertzjq** [comment]
> open any file using `vim` filename

Does this mean this only happens when you open a `.vim` file?

**Comment by popshia** [comment]
> > open any file using `vim` filename
> 
> Does this mean this only happens when you open a `.vim` file?

Sorry for the vague description, I mean opening any file with the command `vim` in the terminal.

**Comment by zeertzjq** [comment]
Does the color become correct if you press `CTRL-L` without reloading `$MYVIMRC`?

**Comment by popshia** [comment]
No it doesn't, the problem still exist.

**Comment by zeertzjq** [comment]
What does `:hi CursorLine` show before and after you run `:source $MYVIMRC`?

**Comment by popshia** [comment]
CursorLine     xxx ctermbg=10 guibg=#282828
CursorLine     xxx ctermbg=18 guibg=#282828

**Comment by zeertzjq** [comment]
I think you need to to `let base16colorspace` before `colorscheme base16-default-dark`.

**Comment by popshia** [comment]
> I think you need to move `let base16colorspace=256` before `colorscheme base16-default-dark`.

Thanks, this solves the problem, and may I ask why does this solve my problem?

**Comment by zeertzjq** [comment]
If you read [base16-vim's README](https://github.com/chriskempson/base16-vim#256-colorspace) carefully:

> you'll need to add the following to your ~/.vimrc before the colorscheme declaration.

If the variable is not set before the colorscheme is loaded, the colorscheme won't be aware of the existence of that variable. I don't know why it worked for you previously. Maybe there has been something else that reloads the colorscheme.

**Comment by popshia** [comment]
Really appreciate for your help! Wish your a merry christmas!
