### ISSUE TITLE
Shift+$ doesnt work in cyrillic layout

### ISSUE THREAD

**Issue by HappyCthulhu** [neovim/neovim#16770]
### Neovim version (nvim -v)

NVIM v0.4.3 

### Vim (not Nvim) behaves the same?

yes, \]VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 20 2021 11:42:42)

### Operating system/version

ubuntu 20.04

### Terminal name/version

fish, version 3.1.0, alacritty 0.8.0-dev (28abb1f)

### $TERM environment variable

idk

### Installation

idk

### How to reproduce the issue

change layout to cyrillic layout (russian version in my case)
type random sentense
press Shift+$

### Expected behavior

"Shift+$" shortcut is needed to go to the end of line. 
It works in en layout well, but not in cyrillic layout

### Actual behavior

Nothing happened. What can i do to fix it?

**Comment by matveyt** [comment]
Pressing Shift-4 (while standard Russian keyboard layout is active) produces semicolon. And semicolon is not a (default) command to go to the end of line, obviously.
The recommended way is to set `:h 'keymap'` option and to switch layouts for Insert mode only by using Vim/Neovim builtin `:h i_ctrl-^`. Thus staying Latin in Normal mode all the time. I believe it's all documented in the help system and other places.
