### ISSUE TITLE
Click-and-drag to arrange tabs in GUI client

### ISSUE THREAD

**Issue by joeljose350** [neovim/neovim#16795]
### Feature description

Allow the user to click and drag tabs to arrange them in the GUI client of Neovim.

### Information

- Neovim: v0.6.0
- OS: Windows 11 Home

**Comment by seandewar** [comment]
Is this in reference to Neovim-qt? That project is managed here: https://github.com/equalsraf/neovim-qt.

**Comment by joeljose350** [comment]
I have opened an identical issue at [equalsraf/neovim-qt](https://github.com/equalsraf/neovim-qt/issues/955) and closed this issue. Thank you @seandewar for letting me know about the neovim-qt repo, I thought it belonged to this one.
