### ISSUE TITLE
listchars eol and extends sometimes hide last character in line

### ISSUE THREAD

**Issue by jheidbrink** [neovim/neovim#16793]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

no, vim 8.2.3890

### Operating system/version

Archlinux, kernel 5.10.88

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

alacritty

### Installation

system package manager

### How to reproduce the issue

* open a 18 characters wide terminal window
* From Bash or Zsh, run `nvim -u <(echo 'set nowrap'; echo 'set list listchars=eol:¬,extends:>') <(echo 1234567890123456789)`
* Hit `$` to go to the end of line
* confirm that the 9 isn't shown. It looks like neovim should scroll right one character more to make it visible.

This problem manifests itself only for certain combinations of line lengths and terminal width. I found that it also fails for `nvim -u <(echo 'set nowrap'; echo 'set list listchars=eol:¬,extends:>') <(echo 12345678901234567890123456)` but works for `nvim -u <(echo 'set nowrap'; echo 'set list listchars=eol:¬,extends:>') <(echo 123456789012345678901234567)`

### Expected behavior

When following the steps mentioned in "How to reproduce the issue", I would expect the last character of the line to be shown.

### Actual behavior

The last character of the line isn't shown.

**Comment by jheidbrink** [comment]
I also confirmed this behaviour with xterm, so I don't think it's an issue with alacritty.

**Comment by zeertzjq** [comment]
I tested this and this bug also exists in v0.5.1.

**Comment by zeertzjq** [comment]
Vim also has this bug with `sidescroll=1`, which is a Nvim default.

**Comment by zeertzjq** [comment]
This problem doesn't happen if you set `sidescrolloff=1` though.

**Comment by zeertzjq** [comment]
You can also scroll more using `zl`.

**Comment by zeertzjq** [comment]
I rethought about this and I don't think this is a bug. There is already an example in documentation (`:h sidescrolloff`) for this:
```
	Example: Try this together with 'sidescroll' and 'listchars' as
		 in the following example to never allow the cursor to move
		 onto the "extends" character: >

		 :set nowrap sidescroll=1 listchars=extends:>,precedes:<
		 :set sidescrolloff=1
```

**Comment by jheidbrink** [comment]
Wow, that was a quick resolution. Thanks for looking into this!
