### ISSUE TITLE
Regarding syntax/vim.vim generation

### ISSUE THREAD

**Issue by Pyrohh** [neovim/neovim#1680]
I noticed `'breakindent'` is not defined in `syntax/vim.vim`, so I wanted to add it. When I went to do that, I noticed these two lines surrounding the area where command definitions would go:

`Automatically generated keyword lists`
`"--- syntax here and above generated by mkvimvim ---`

I couldn't find anything on regenerating `vim.vim` besides this old vim_dev thread, which wasn't of much use: https://groups.google.com/forum/#!topic/vim_dev/z5IolTbchW8

I'm wondering if anyone who's added definitions just did so manually, or used mkvimvim (which doesn't seem to be present in nvim or vim's repo).

**Comment by ZyX-I** [comment]
Ref #2288.

**Comment by justinmk** [comment]
Resolved by https://github.com/neovim/neovim/pull/2288
