### ISSUE TITLE
Cannot unmap default keybindings using Lua configuration

### ISSUE THREAD

**Issue by zoqaeski** [neovim/neovim#16803]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.9.0 (fed349aa)

### $TERM environment variable

tmux-256color

### Installation

System package manager

### How to reproduce the issue

I'm trying to port my configurations over to lua, and encountering difficulties in remapping certain default keys. In particular, trying to remove the `s` mapping so I can use it as part of a `[window]` chord reports:
```
E5113: Error while calling lua chunk: /home/zoqaeski/window_keymaps.lua:20: E31: No such mapping
stack traceback:
        [C]: in function 'nvim_del_keymap'
        /home/zoqaeski/window_keymaps.lua:20: in main chunk
```

So far, I have tried the following:
```
vim.api.nvim_del_keymap('', 's')
vim.api.nvim_del_keymap('n', 's')
vim.cmd [[unmap s]]
```
I've also tried calling the `vim.api.nvim_del_keymap('', 's')` in the command line, and it also fails.

[window_keymaps.txt](https://github.com/neovim/neovim/files/7778150/window_keymaps.txt)

### Expected behavior

I should be able to unmap any default key binding. This works in my configuration using pure vimscript.

### Actual behavior

Neovim reports `E5113: Error while calling lua chunk: /home/zoqaeski/window_keymaps.lua:20: E31: No such mapping`, and refuses to unmap the key.

**Comment by zeertzjq** [comment]
There is no default `s` mapping.

**Comment by zeertzjq** [comment]
> This works in my configuration using pure vimscript.

Can you give an example?

**Comment by zeertzjq** [comment]
You do not need to unmap it. Just create a new mapping.

**Comment by zeertzjq** [comment]
You do not need to unmap it. Just create a new mapping.
