### ISSUE TITLE
CTRL-L with insertmode required twice after opening a file via socket

### ISSUE THREAD

**Issue by M1cha** [neovim/neovim#16823]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

vim doesn't have `--listen`

### Operating system/version

Arch Linux

### Terminal name/version

both nvim-qt 0.2.16.1-1 and alacritty 0.9.0+tmux 3.2_a-1

### $TERM environment variable

xterm-256color

### Installation

pacman (community repo)

### How to reproduce the issue

test.vim:
```vim
set insertmode
```

test.py:
```python
import neovim
nvim = neovim.attach("socket", path="/tmp/nvimsocket")
nvim.command(f"e /tmp/tmp")
```

now run:
```bash
nvim -u test.nvim --listen /tmp/nvimsocket
./test.py
```

### Expected behavior

Press `CTRL-L` once to get into normal mode as it is the case when you open a file without the socket API.

### Actual behavior

You have to press `CTRL-L` twice to get into normal mode.

**Comment by zeertzjq** [comment]
It seems the first `CTRL-L` leaves Insert mode, and then re-enters Insert mode immediately. Further `CTRL-L` keypresses don't have the problem, even if `test.py` is run again.

**Comment by M1cha** [comment]
for me it does have the problem after re-running `test.py` if you go back into insert-mode (using `i`) after the second `CTRL-L`.
