### ISSUE TITLE
vim.mpack.encode fails on list-like tables where keys are strings ("1", "2", "3" etc) instead of numbers

### ISSUE THREAD

**Issue by dmitmel** [neovim/neovim#16837]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

pacman, official repositories

### How to reproduce the issue

```lua
vim.mpack.encode({ ['1'] = 1 })
vim.mpack.encode({ ['1'] = 1, ['2'] = 3, ['3'] = 4 })
vim.mpack.encode({ ['0'] = 1 })  -- but this one works fine
vim.mpack.encode({ ['1'] = 1, ['3'] = 4 })  -- sparse "lists" don't cause the problem either
vim.mpack.encode({ [1] = 1, ['2'] = 3, ['3'] = 1 })  -- mixed key types also cause the issue
vim.mpack.encode({ [5] = 1, ['2'] = 3, ['3'] = 1 })  -- but this works, so mixed key types are generally allowed
```

### Expected behavior

All of the above cases are encoded as dictionaries with string keys, and the latter two serialize to dictionaries with string and number keys.

### Actual behavior

Cases 1, 2 and 5 throw the following error:

```
E5108: Error executing lua [string ":lua"]:1: can't serialize object of type 0
stack traceback:
        [C]: in function 'encode'
        [string ":lua"]:1: in main chunk
```

**Comment by nwounkn** [comment]
https://github.com/neovim/neovim/commit/307a7abf86c439177910d05003a81ea4a13d2650 fixed
