### ISSUE TITLE
Bash Syntax Broken By A <

### ISSUE THREAD

**Issue by The-Repo-Club** [neovim/neovim#16838]
### Neovim version (nvim -v)

NVIM v0.6.0

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Arch Linux

### Terminal name/version

Kitty

### $TERM environment variable

xterm-kitty

### Installation

community/neovim

### How to reproduce the issue

1. Open a file with `sh` syntax
2. Write:
 
```shell
#!/usr/bin/env bash

test_fn() {
    IFS=' '
    local raw_size=($(printf "%b" "${pre_size}" | od -An -tu1 -N2))
    # Split the upper 4 bits (exponent) the lower 12.
    local lowers=$((((raw_size[0] % 16) << 8) + (raw_size[1])))
    local upper4=$((raw_size[0] >> 4))
    qt5ct_font_size=$(((2 ** (upper4 + 1)) + (lowers >> (11 - upper4))))
}
```
3. See it break

vim report [9436](https://github.com/vim/vim/issues/9436)

### Expected behavior

image taken from emacs

![1640898074](https://user-images.githubusercontent.com/9284733/147788904-20d7cc77-045c-4e94-85a8-3743b6993f80.png) 

### Actual behavior

![image](https://user-images.githubusercontent.com/9284733/147788513-a79312bb-c32c-4c38-a77e-dc7524f7da2a.png)

**Comment by amerixan** [comment]
Can confirm this is the case on **NVIM v0.7.0-dev+792-gc46f7caad** also.

**Comment by The-Repo-Club** [comment]
@amerixan seems like it stems from vim as vi also has the same issue :)

**Comment by clason** [comment]
Issues with syntax files need to be raised upstream ([which you already did](https://github.com/vim/vim/issues/9436)).

**Comment by TruncatedDinosour** [comment]
> Issues with syntax files need to be raised upstream ([which you already did](https://github.com/vim/vim/issues/9436)).

I'm a different person lol, The-Repo-Club and me spotted that issue so we decided to report it on what we use, I use pure vim and he uses nvim

**Comment by clason** [comment]
Ah, sorry, the timing was too close ;) In any case, in case it wasn't clear: we take syntax files wholesale from Vim, so it needs to be fixed there (and only there); once Vim updates their runtime files, we pull in the changes routinely.

**Comment by TruncatedDinosour** [comment]
> Ah, sorry, the timing was too close ;) In any case, in case it wasn't clear: we take syntax files wholesale from Vim, so it needs to be fixed there (and only there); once Vim updates their runtime files, we pull in the changes routinely.

sure :)
