### ISSUE TITLE
vim-patch: 8.2.2345 no foucs events in a terminal

### ISSUE THREAD

**Issue by 4513ECHO** [neovim/neovim#16832]
### Feature already in Vim?

Yes, since Vim 8.2.2345

### Feature description

Please add the `t_fd` and `t_fe` termcap entries to implement detecting focus events.

ref: https://github.com/vim/vim/commit/681fc3fa782e99fe69ed2c83c3e29109d2d61e1a

Maybe, It fixes some issues #15355 and #14572.

**Comment by 4513ECHO** [comment]
I found the PR #14070, but it isn't seem including  vim-patch 8.2.2345.

**Comment by zeertzjq** [comment]
`t_xx` options have been deprecated. What exactly do you want?

**Comment by zeertzjq** [comment]
`t_xx` options have been deprecated (see `:h t_xx`). Nvim already supports focus events in a terminal. What exactly do you want?

**Comment by 4513ECHO** [comment]
I'm using [tmux-plugins/vim-tmux-focus-events](https://github.com/tmux-plugins/vim-tmux-focus-events)                                                            and I found this message today.

> **Update:** this plugin is now obsolete and no longer needed as both neovim and vim (since version 8.2.2345) have native support for this functionality.

Then, I tried `:echo has('patch-8.2.2345')` in Neovim, but its result is 0. So I wrote this issue.

**Comment by zeertzjq** [comment]
`has()` in Nvim cannot change for Vim 8.1.xxxx and Vim 8.2.xxxx, because Nvim isn't compatible with Vim 8.1 yet.

**Comment by 4513ECHO** [comment]
I see. Neovim already has supported focus events in a terminal. Thank you.
