### ISSUE TITLE
Extra blank lines when formatting final lines of a file with efm language server

### ISSUE THREAD

**Issue by fsouza** [neovim/neovim#16842]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+793-g991e872d8

### Language server name/version

efm-langserver 0.0.38 (rev: HEAD/devel go1.18-6178d25f Wed Dec 29 20:20:32 2021 +0000)

### Operating system/version

Darwin _ 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: efm: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /Users/fsouza/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: screen-256color
```

### Steps to reproduce using "nvim -u minimal_init.lua"

Modified minimal_init.lua: https://gist.github.com/fsouza/a21bc749af74046b2a90be67d77da2b3

```
$ nvim -u minimal_init.lua sample.yaml
```

Write the following yaml:

```yaml
things:
- name: whatever
```

Format the code with `:lua vim.lsp.buf.formatting()`

(I included ocaml as a config option to ensure it's not a problem with prettierd itself, if you want to reproduce with ocaml, write some poorly formatted code as the last lines of a file and invoke `vim.lsp.buf.formatting()`.

### Expected behavior

Code should be formatted to:

```yaml
things:
  - name: whatever
```

### Actual behavior

Code gets formatted to:

```yaml
things:

  - name: whatever
```

The issue happens with all of the last lines, not just the last one, meaning if I have:

```yaml
things:
- name: thing-1
- name: thing-2
- name: thing-3
- name: thing-4
```

Formatting takes me to:

```yaml
things:

  - name: thing-1

  - name: thing-2

  - name: thing-3

  - name: thing-4
```

And the issue only happens when formatting the last lines of the file. If you try the steps above with this code:

```yaml
things:
- name: whatever
other: thing
```

Then it gets correctly formatted to:

```yaml
things:
  - name: whatever
other: thing
```

Can't repro with other servers, so I assume it's something efm is doing wrong when getting the output from the process and turning into LSP commands, but I'm kinda lost on what exactly is going on.

Couple of recordings:

1. Formatting the last line in a file

https://user-images.githubusercontent.com/108725/147802999-47f4ce64-b318-476a-9563-a16f54d51661.mov

Logs (also included in the field below): https://gist.github.com/fsouza/cd967ebe4b324fafcc3e5ef62288c675

2. Formatting a line that's not the last one

https://user-images.githubusercontent.com/108725/147803062-a912ba5d-9156-4416-9d0e-d21b85fb8678.mov

Logs: https://gist.github.com/fsouza/ee6b6fdf5bd97ef3d6d0fc10b76f85e1

Looking at the responses for `textDocument/formatting`, they're equal, but maybe I'm missing something. I plan to dig into it over the next day or two, but figured I could open this issue just in case it's something obvious.

I can also reproduce it in neovim 0.5.1 and 0.6.0. And I imagine I would have noticed this before? 🙈 Which leads me to think something changed in the efm-langserver, idk. I'll look into that later.

### Log file

First recording, unexpected behavior: https://gist.github.com/fsouza/cd967ebe4b324fafcc3e5ef62288c675

Second recording, behaving as expected: https://gist.github.com/fsouza/ee6b6fdf5bd97ef3d6d0fc10b76f85e1

**Comment by mjlbach** [comment]
There's this issue. Given that formatting works well with every other language server, I think the problem likely lies with EFM.

**Comment by fsouza** [comment]
> There's this issue ([mattn/efm-langserver#181](https://github.com/mattn/efm-langserver/issues/181)) Given that formatting works well with every other language server, I think the problem likely lies with EFM.

I haven't found any other language server that does line-wise diffs though, so it could be a bug in neovim too.

Basically, given this response:

```
{
  id = 2,
  jsonrpc = "2.0",
  result = { {
      newText = "",
      range = {
        end = {
          character = 0,
          line = 2
        },
        start = {
          character = 0,
          line = 1
        }
      }
    }, {
      newText = "  - name: whatever\n",
      range = {
        end = {
          character = 0,
          line = 2
        },
        start = {
          character = 0,
          line = 2
        }
      }
    } }
}
```

apply_text_edits behaves differently if line 2 is the last one 🤷 I'll keep digging.

**Comment by fsouza** [comment]
(can confirm `coc.nvim` behave as expected with that payload)

**Comment by mjlbach** [comment]
If you reproduce with something that isn't efm/diagnosticls/null-ls I'll take a look

**Comment by fsouza** [comment]
My current hypothesis is that this is a client bug (reasoning: given a payload from the server, client behaves differently based on client-only state). I'll keep on that path, can check other servers later.

**Comment by mjlbach** [comment]
I'm not saying it's not a client bug, I'm just only interested in working on it with a reproduction case for a real language server.

**Comment by fsouza** [comment]
Ohh, sorry, didn't mean to imply that that's what you were saying. My initial
reluctance was due to the fact that many language servers implement
textDocument/formatting just like efm: by shelling out to some external tool
and calculating the diff, so I figured it'd be either an issue with how efm
calculates the diff or how neovim applies it. And that's it.

Some notes:

The extra `\n` is prepended by this block:
https://github.com/neovim/neovim/blob/fc62fdd42fde37949af3c6b6273acc1c116cb6f0/runtime/lua/vim/lsp/util.lua#L408-L425

Line 2 doesn't exist, so

```
{
  id = 2,
  jsonrpc = "2.0",
  result = { {
      newText = "",
      range = {
        end = {
          character = 0,
          line = 2
        },
        start = {
          character = 0,
          line = 1
        }
      }
    }, {
      newText = "  - name: whatever\n",
      range = {
        end = {
          character = 0,
          line = 2
        },
        start = {
          character = 0,
          line = 2
        }
      }
    } }
}
```

gets transformed into

```
{
  id = 2,
  jsonrpc = "2.0",
  result = { {
      newText = "",
      range = {
        end = {
          character = 0,
          line = 1
        },
        start = {
          character = 0,
          line = 1
        }
      }
    }, {
      newText = "\n  - name: whatever\n",
      range = {
        end = {
          character = 0,
          line = 1
        },
        start = {
          character = 0,
          line = 1
        }
      }
    } }
}
```

Ultimately, I think it's an incompatibility between efm's diff algorithm and
neovim? I guess it could be called a bug on either side, idk. Basically, efm is
saying:

- Keep line 0
- Delete line 1
- Write line 2 with the contents "  - name: whatever"

If you take those changes individually (in any order, really) you'd end-up with
line 0 and line 2, which is what coc.nvim and vscode do, but neovim tries to
fix the TextEdit object by moving it one line above and prepending `\n`.

**Note:** when line 2 exists, neovim does the right thing. The rest of neovim's
algorithm is correct, just the prepending of `\n` is problematic here (but it
may make sense in other cases, I'm not sure).

coc.nvim and VSCode are fine with that because of [how TextEdit's are
applied](https://github.com/microsoft/vscode-languageserver-node/blob/2020cb4254abe91de1749cecad8283d397eea0b7/textDocument/src/main.ts#L354-L379).

Some potential solutions:

- change how the diff is generated on efm-langserver: there's opportunity to
  make it more efficient using something like go-diff to calculate
  character-level diff anyways. Could get some inspiration from
  [gopls](https://github.com/golang/tools/blob/ee1ca4ffc4daac3e266c00d2310f526cc41d1829/gopls/internal/hooks/diff.go#L15-L41)
  (copying it directly won't work due to the fact that gopls operates on byte
  offsets, not line/col) cc @mattn @lukas-reineke
- update neovim to special-case the logic to prepend `\n` to not do it when
  appending after the end of file follows deletion (this is probably too
  fragile/would likely break)
- have neovim handle byte offsets instead of lines (would require ditching
  nvim_buf_set_text or operating on some virtual data structure before invoking
  it - basically what coc.nvim does).

Or... the absolute simplest solution would be to revert the [change that
implemented](https://github.com/mattn/efm-langserver/commit/0f1394fc43ae6c431a3d3deb3f8f00775c064c19)
the diffing logic in efm-langserver, but efm authors could argue that efm is
compliant with the protocol (spec doesn't say anything about it, but the
reference implementation supports it).

I'm not super interested into pursuing this, but thought I'd share my findings
in case someone is. Will cross link from that efm issue too.

**Comment by lukas-reineke** [comment]
The diff implementation in EFM was largely copied from gopls at that time.
I haven't looked at what gopls does now, but if the issue doesn't happen there we can probably port the changes over.

Reverting isn't really an option, that would break a lot of other stuff.

I can take a look, but it probably won't be for a couple days.

**Comment by fsouza** [comment]
> The diff implementation in EFM was largely copied from gopls at that time.
> I haven't looked at what gopls does now, but if the issue doesn't happen there we can probably port the changes over.
> 
> Reverting isn't really an option, that would break a lot of other stuff.
> 
> I can take a look, but it probably won't be for a couple days.

gopls has two algorithms, the one you copied over to efm and one built on top of go-diff (which is itself a port of a Google library). In my tests with both go files and go.mod files, gopls is using the latter, not sure when the former is used.

**Comment by mjlbach** [comment]
Thanks for digging into this :) 

@hrsh7th was the last person to work on this, see: https://github.com/neovim/neovim/pull/15561

Do you have time to take a look?

**Comment by hrsh7th** [comment]
OK. I'll check it.

**Comment by hrsh7th** [comment]
OK. I could reproduce this.
