### ISSUE TITLE
`vim.diagnostic.set` not working

### ISSUE THREAD

**Issue by SiddharthShyniben** [neovim/neovim#16844]
### Neovim version (nvim -v)

v0.7.0-dev+793-g991e872d8

### Vim (not Nvim) behaves the same?

N/A (using `vim.diagnostic`)

### Operating system/version

macOS 10.15.7

### Terminal name/version

iTerm2 3.4.15

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

1. `$ nvim --clean`
2. Add some dummy text
3. Run the following lua (`:so test/lua` or `:lua <code>`):
    ```lua
     local namespace = vim.api.nvim_create_namespace('whatever')

     vim.diagnostic.set(namespace, 0, {
		bufnr = 0,
		lnum = 3,
		end_lnum = 4,
		col = 1,
		end_col = 2,
		severity = vim.diagnostic.severity.WARN,
		message = 'test',
		source = 'test'
     })
     ```

### Expected behavior

The diagnostic is set.

### Actual behavior

This error comes up:

```
Error detected while processing /Users/mac/Sites/Projects/vide/videl/test.lua:
E5113: Error while calling lua chunk: ...m/HEAD-991e872/share/nvim/runtime/lua/vim/diagnostic.lua:385: attempt to compare number with nil
stack traceback:
        ...m/HEAD-991e872/share/nvim/runtime/lua/vim/diagnostic.lua:385: in function 'add'
        ...m/HEAD-991e872/share/nvim/runtime/lua/vim/diagnostic.lua:419: in function 'get_diagnostics'
        ...m/HEAD-991e872/share/nvim/runtime/lua/vim/diagnostic.lua:1110: in function 'show'
        ...m/HEAD-991e872/share/nvim/runtime/lua/vim/diagnostic.lua:660: in function 'set'
        test.lua:3: in main chunk
Press ENTER or type command to continue
```

**Comment by theHamsta** [comment]
When reading the docs, it appears to me that `set` expects a list of diagnostics while you're only providing a single one.

**Comment by mjlbach** [comment]
> When reading the docs, it appears to me that set expects a list of diagnostics while you're only providing a single one. Could you check whether this is the problem?

This is the problem.

**Comment by gpanders** [comment]
Note for myself, we can provide validation and a helpful error message for cases like this.
