### ISSUE TITLE
vim.lsp.diagnostic.get_all is deprecated

### ISSUE THREAD

**Issue by bryant-the-coder** [neovim/neovim#16858]
### Neovim version (nvim -v)

NVIM v0.6.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compiled by runneradmin@fv-az152-430

### Language server name/version

all

### Operating system/version

windows 10

### :checkhealth

```markdown
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: tsserver: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: html: configuration checked.
  - INFO: emmet_ls: configuration checked.
  - INFO: cssls: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date
```

### Steps to reproduce using "nvim -u minimal_init.lua"

update to the latest version. and type `nvim`

### Expected behavior

![image](https://user-images.githubusercontent.com/92417638/147843180-3b1154d2-55c6-407e-8c34-9ae82f55ee43.png)

### Actual behavior

no error

**Comment by zeertzjq** [comment]
The image wasn't successfully uploaded.

**Comment by mjlbach** [comment]
I'm assuming this is a plugin that needs to update to the latest diagnostic API.

**Comment by bryant-the-coder** [comment]
> I'm assuming this is a plugin that needs to update to the latest diagnostic API.

i cant find the exact phrase in my config files. i updated all plugins but it is still there

**Comment by bryant-the-coder** [comment]
![image](https://user-images.githubusercontent.com/92417638/147843188-2abbea75-8f10-4fed-9f50-e36addf06203.png)

**Comment by mjlbach** [comment]
Did you try grepping #HOME/.local/nvim?

**Comment by bryant-the-coder** [comment]
yup

**Comment by zeertzjq** [comment]
For Windows it should be somewhere in `AppData`.

**Comment by bryant-the-coder** [comment]
i did... nothing was wrong... or mayb sending the command? mayb i did smth wrong

**Comment by mjlbach** [comment]
I would try grepping for get_all incase the plugin made vim.lsp.diagnostic local

**Comment by bryant-the-coder** [comment]
so what is the right command? the telescope screenshot is by finding the words in my file...

**Comment by zeertzjq** [comment]
What Telescope command did you use?

**Comment by bryant-the-coder** [comment]
telescope live grep

**Comment by zeertzjq** [comment]
Then you can try `:call chdir(stdpath('data') .. '/site') | Telescope live_grep` and searching for `vim.lsp.diagnostic.get_all`.

**Comment by bryant-the-coder** [comment]
huh?

**Comment by bryant-the-coder** [comment]
uhh... what is the full command?? (・∀・)

**Comment by zeertzjq** [comment]
For what?

**Comment by zeertzjq** [comment]
If you don't know how to search for that, at least list what plugins you have installed.

**Comment by zeertzjq** [comment]
Oh, you can run `:lua vim.lsp.diagnostic.get_all = nil` to turn the warning into an error with a stacktrace, and then you can post a screenshot of the stacktrace.

**Comment by bryant-the-coder** [comment]
https://github.com/bryant-the-coder/NvHack

my repo

**Comment by zeertzjq** [comment]
Does disabling `bufferline.nvim` make the warning disappear?

**Comment by zeertzjq** [comment]
If it does, then this is tracked by <https://github.com/akinsho/bufferline.nvim/issues/285>, which will be fixed by <https://github.com/akinsho/bufferline.nvim/pull/286>.

**Comment by zeertzjq** [comment]
> Does disabling `bufferline.nvim` make the warning disappear?

Just comment out this line in your config:
<https://github.com/bryant-the-coder/NvHack/blob/2fa4a7b4cbc3b02655bd755f09a76e90bd7b75bc/init.lua#L9>

**Comment by bryant-the-coder** [comment]
I'll try once i get to use my comp

**Comment by bryant-the-coder** [comment]
it is indeed related to bufferline. thanks for the help ヾ(•ω•`)o
