### ISSUE TITLE
calling feedkeys twice for abbreviations expands first call but not second

### ISSUE THREAD

**Issue by 0styx0** [neovim/neovim#16854]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+575-g2ef9d2a66

### Vim (not Nvim) behaves the same?

yes, VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 25 2021 11:17:40)

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.9.0 (fed349aa)

### $TERM environment variable

xterm-256color

### Installation

AUR

#### Reproduction in Neovim

`nvim --clean abbr-bug-reproduction.lua`

```lua

local trigger = 'trigger'
local value = 'value'

 -- space is a non-keyword character, so expands abbreviations
vim.cmd('iabbrev ' .. trigger .. ' ' .. value)

vim.api.nvim_feedkeys('a'.. trigger .. ' ', 'xt', true)

vim.api.nvim_feedkeys('a'.. trigger .. ' ', 'xt', true)

-- <cursor over here so that don't mess up what we wrote>
```
`:source %`

#### Reproduction in pure Vim
`vim -u DEFAULTS abbr-bug-reproduction.vim`

```vim
iabbrev trigger value

call feedkeys('atrigger ', 'xt')

call feedkeys('atrigger ', 'xt')

" <cursor over here so that don't mess up what we wrote>
```
`:source %`

### Expected behavior

abbreviation should be expanded both times, and so `value` should be printed twice.
expected output after source: "value value "

### Actual behavior

`value` is printed the first time, but `trigger` is printed the second time
actual output after source: "value trigger "

**Comment by 0styx0** [comment]
_Note_: Doing the following does produce the expected behavior

```lua

local trigger = 'trigger'
local value = 'value'

vim.cmd('iabbrev ' .. trigger .. ' ' .. value)

-- no x flag
vim.api.nvim_feedkeys('a'.. trigger .. ' ', 't', true)

vim.api.nvim_feedkeys(trigger .. ' ', 't', true)

-- not needed when reproducing in regular neovim, but yes needed to reproduce 
-- using plenary
vim.api.nvim_feedkeys(' ', 'x', true)
```
`:source %`

**Comment by zeertzjq** [comment]
v0.6.0-dev+575-g2ef9d2a66 is before the v0.6.0 release. This bug also exists in v0.6.0 and latest HEAD though.

**Comment by zeertzjq** [comment]
Adding a `<Esc>` avoids the problem though.
```vim
iabbrev trigger value

call feedkeys("atrigger \<Esc>", 'x')

call feedkeys("atrigger \<Esc>", 'x')

" <cursor over here so that don't mess up what we wrote>
```

**Comment by zeertzjq** [comment]
Reported at Vim: <https://github.com/vim/vim/issues/9448>
