### ISSUE TITLE
Absence of `vim.api.nvim_exec_lua()`

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#16865]
### Neovim version (nvim -v)

0.6.0 (also present in 0.5.0 and 0.6.1)

### Vim (not Nvim) behaves the same?

No, Vim doesn't have Lua API

### Operating system/version

Ubuntu 18.04

### Terminal name/version

Kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

1. Run `nvim --clean`
2. Execute `:lua print(vim.inspect(vim.api.nvim_exec_lua))`.

### Expected behavior

Not `nil` is printed (but something like `<function 1>`) indicating that `vim.api.nvim_exec_lua` is present.

I am not really sure if that is a problem in documentation (stating that `vim.api.nvim_exec_lua` should exist, when it is not designed to be exported) or in implementation (it should be exported but in fact does not). I have a feeling that I might miss something obvious here, but couldn't find `nvim_exec_lua()` anywhere available for general usage inside Lua.

### Actual behavior

`nil` is printed.

**Comment by clason** [comment]
The function is indeed annotated as `FUNC_API_REMOTE_ONLY`.

But why would you want to use that function from Lua in the first place instead of just executing whatever Lua code you want directly?

**Comment by echasnovski** [comment]
The main use case is receiving Lua code as strings and need to execute it.

I am writing an auto documentation functionality which collects help lines from EmmyLua-like annotations. I have a very useful case when eventual lines in help file might be generated with the help of Lua code (for example, have default plugin config created through code and duplicated in help file via adding appropriate `@eval` section in annotation).

For now I used `nvim_exec` and wrapped code with `lua << EOF` and `EOF` lines but this seems like a redundant work. For more context:
- [Current implementation of `@eval` section](https://github.com/echasnovski/nvim/blob/f5c2c86a34656529e95592aa3b027ab30035720f/lua/mini-dev/doc.lua#L161-L165).
- [Example of how I see it can be used](https://github.com/echasnovski/nvim/blob/f5c2c86a34656529e95592aa3b027ab30035720f/lua/mini-dev/test-doc.lua#L58-L76).

**Comment by clason** [comment]
Why not use Lua's `loadstring` for that?

**Comment by echasnovski** [comment]
Yeah, I tried it interactively when was researching and couldn't get it working with multline Lua code. I planned to try it again but forgot in favor of making this issue first as it is some kind of a bug nevertheless. Now I tried it and it works, so thanks for reminder :)

**Comment by jamessan** [comment]
Then this can be closed, right?

**Comment by clason** [comment]
Depends on whether we want to extend the documentation with this information, but I think this would be better as a new issue.

**Comment by echasnovski** [comment]
Well, there is an information that `vim.api.nvim_exec_lua()` is present (`:help nvim_exec_lua()` actually points to some function making no distinction with its neighbors) but `vim.api.nvim_exec_lua()` is absent. I didn't close this because it is still an issue, but if you want to track it somewhere else, then sure, no problem.

**Comment by smackesey** [comment]
This just bit me, really confusing that some of the API functions are defined under `vim.api` and others are not.

**Comment by justinmk** [comment]
> really confusing that some of the API functions are defined under `vim.api` and others are not.

In Nvim 0.8 (unreleased), remote-only functions are documented as RPC-only:

```
nvim_exec_lua({code}, {args})                                *nvim_exec_lua()*
...
                Attributes: ~
                    |RPC| only
```
