### ISSUE TITLE
nvim_buf_call() causes rendering artifacts with :redrawstatusline

### ISSUE THREAD

**Issue by dmitmel** [neovim/neovim#16872]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

pacman, official repositories

### How to reproduce the issue

1. The minimal vimrc:

   ```vim
   set runtimepath^=~/.config/nvim/plugged/nvim-lspconfig

   " I chose sumneko/lua-language-server because it publishes empty lists of
   " diagnostics for all files in the workspace upon completing indexing of the
   " project, so it makes the problem more apparent.
   lua require('lspconfig')['sumneko_lua'].setup({})

   set title

   " A sufficiently complex statusline to show the screen rendering glitches.
   set runtimepath^=~/.config/nvim/plugged/vim-airline
   let g:airline#extensions#tabline#enabled = 1
   let g:airline#extensions#nvimlsp#enabled = 1

   " I have this in my vimrc to update the counters in the statusline.
   autocmd DiagnosticChanged * redrawstatus

   " This is unrelated to the bug, it is simply done to ease the wait for the
   " workspace to be fully indexed.
   autocmd User LspProgressUpdate echo v:lua.vim.lsp.util.get_progress_messages()
   ```
2. Inside the neovim work tree, run `nvim -u minimal_init.vim runtime/lua/vim/lsp/buf.lua runtime/lua/vim/lsp/*.lua`. Strictly speaking, opening multiple files like this is not a requirement, but it just shows more rendering artifacts with the statusline. The `buf.lua` file is first in the list because there are some diagnostics reported for it, and they will be shown in the statusline.

### Expected behavior

Neovim v0.6.0

https://user-images.githubusercontent.com/15367354/147855804-96824bcb-6c7d-4c4a-ae86-a440afab76bd.mp4

### Actual behavior

Neovim v0.6.1 (the pink flashing box is caused by `redrawstatus`)

https://user-images.githubusercontent.com/15367354/147855811-177b2b2b-693d-4175-af7f-52065c692265.mp4

### Additional context

The problem is caused by #16474 and #16589. I believe that a proper solution would be to execute the autocommands with Vim's internal functions (`apply_autocmds_group`?), that only change the effective buffer (`<abuf>`) instead of also changing the real current buffer.

**Comment by gpanders** [comment]
I wonder if this is because of the `nvim_buf_call`. If you remove that wrapper from diagnostic.lua can you still reproduce the issue?

**Comment by dmitmel** [comment]
Yes, it is because of `nvim_buf_call`. I've tried that and it worked just fine - that's why I pinpointed the cause to those two PRs.

**Comment by dmitmel** [comment]
Merely calling `vim.api.nvim_buf_call` (without doing `:doautocmd` inside of it) in `vim.diagnostic.set` is enough to reproduce the issue. And, again, it has the problem of changing the real current buffer, so you can't do something like this (which you would be able to only if the effective buffer was changed):

```vim
autocmd DiagnosticChanged * if +expand('<abuf>') == bufnr('') | redrawstatus | endif
```

**Comment by gpanders** [comment]
> Yes, it is because of `nvim_buf_call`. I've tried that and it worked just fine - that's why I pinpointed the cause to those two PRs.

Apologies, I missed that in your original comment (I really ought to stop replying to issues on mobile).

It seems that the issue is really with `nvim_buf_call` switching buffers, not with the `DiagnosticChanged` autocommand itself. Out of curiosity, if you add a check in `diagnostic.lua` to see if `bufnr` is the current buffer and omit the call to `nvim_buf_call` in that case, does that fix the problem (I am guessing it won't, but I'm still curious)?

**Comment by dmitmel** [comment]
> Apologies, I missed that in your original comment (I really ought to stop replying to issues on mobile).

Ah, no problem, I edited the body of the issue after posting it.

> if you add a check in `diagnostic.lua` to see if `bufnr` is the current buffer and omit the call to `nvim_buf_call` in that case, does that fix the problem (I am guessing it won't, but I'm still curious)?

Just tried - no effect.

**Comment by tomtomjhj** [comment]
I had a similar issue with lightline:
```
au DiagnosticChanged * call lightline#update()
```
Lightline thinks that the `nvim_buf_call`ed buffer/window is the "current window", and this makes "active window"'s statusline appear in an actually inactive window.

Wrapping the command with `schedule_wrap` fixed the issue for me.
```
au DiagnosticChanged * lua vim.schedule_wrap(function() vim.fn['lightline#update']() end)
```

**Comment by dmitmel** [comment]
This bug may be fixed by `nvim_exec_autocmds`, now that it exists, it has a bufnr argument.

**Comment by dmitmel** [comment]
@tomtomjhj By the way, `vim.schedule_wrap` creates a function that calls `vim.schedule` with the function you gave it. So, in your code, `lightline#update` is not called at all.

**Comment by tomtomjhj** [comment]
@dmitmel Ah, thanks. `vim.schedule(function() vim.fn['lightline#update']() end` seems to do what I actually meant.
