### ISSUE TITLE
(Neo)Vim hangs with freeing a lot of objects

### ISSUE THREAD

**Issue by Shougo** [neovim/neovim#1687]
https://groups.google.com/forum/#!searchin/vim_dev/GC/vim_dev/DBYOdHQWvqY/1WH04_dwETIJ

I think this patch is important for neovim and Vim.
But it is not included yet.

Do you think about the problem?

Note: This problem maybe reproduced if you use unite.vim.  Because, unite.vim uses a lot of memories.

**Comment by Pyrohh** [comment]
Is this still an issue after #1761?

**Comment by justinmk** [comment]
No, thanks @Pyrohh
