### ISSUE TITLE
Starting neovim with no keybindigs at all, just what's in the nvimrc file

### ISSUE THREAD

**Issue by victormihalache** [neovim/neovim#16882]
### Feature already in Vim?

No

### Feature description

I use the colemak keyboard layout, so I basically have to remap every single key to fit my needs, but I would also like not to stumble upon something I don't know exists by accident. I think the solution to this i just to have an option to read only the mapping in the rc file and ignore the default ones.

**Comment by jamessan** [comment]
There's no need to remap anything.  Just use the keys where they are in colemak.  If you really feel like things should be changed, then create a colemak [`'keymap'`](https://neovim.io/doc/user/options.html#'keymap'), similar to the [dvorak](https://github.com/neovim/neovim/blob/master/runtime/keymap/dvorak.vim) one.

Discussions of how to configure nvim belong on [discourse](https://neovim.discourse.group/).
