### ISSUE TITLE
usr_05.txt - tag 5.3 no longer exists.   Appears to have become  "05.4    Simple mappings" 

### ISSUE THREAD

**Issue by daveb68** [neovim/neovim#16885]
### Neovim version (nvim -v)

commit 5b839ced692230fe582fde41f79f875ee90451e8 (HEAD, tag: v0.6.1)0

### Vim (not Nvim) behaves the same?

No idea

### Operating system/version

Ubuntu 20.04

### Terminal name/version

Ubuntu default

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

Reading the documentation has several places that link to the help topic 5.3, which no longer exists.

For example,
:help map.txt

Within map.txt, try to jump to the tag 5.3 in:

  This subject is introduced in sections 05.3, 24.7 and 40.1 of the user
  manual.

It looks like something caused what was 05.3 to become 05.4 and there is now no 05.3 section.

### Expected behavior

The tag that has become 5.4 is restored to 5.3.

### Actual behavior

Receive "Sorry, No help for 05.3"

**Comment by clason** [comment]
Unlike Vim, Neovim doesn't have a `defaults.vim`; that link should be removed from the top of `map.txt`.

**Comment by daveb68** [comment]
@clason I am not sure I agree.

That topic is covered in 05.4 "*05.4*	Simple mappings"

Removing that link, instead of fixing it, makes quickly learning mapping more difficult when referenced from map.txt and 
"*40.1*	Key mapping"

The original documentation links the user manual sections covering mapping and the reference with all of the details of mapping.

**Comment by clason** [comment]
The point is that we have removed a section (on `defaults.vim`; I'd advise you to check out `:h 05.3` in Vim) that does not apply to Neovim but missed some places in the manual that needed to be adapted. The linked PR fixes that.

**Comment by daveb68** [comment]
@clason thank you for the illumination.

I now realize that the vim documentation is incorrect.  Both map.txt and 40.1 should be referring to 05.4 and not 05.3.

**Comment by clason** [comment]
Yep, should be fixed now!
