### ISSUE TITLE
BufRead not triggered when switching to previously open file

### ISSUE THREAD

**Issue by MRAAGH** [neovim/neovim#16887]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no, vim 8.2.3890

### Operating system/version

Arch Linux

### Terminal name/version

urxvt 9.26

### $TERM environment variable

rxvt-unicode-256color

### Installation

pacman -S neovim

### How to reproduce the issue

```
touch file1 file2
nvim --clean file1
:e file2
:au BufRead * norm iTEST
:e file1
```

### Expected behavior

When switching from `file2` to `file1`, `BufRead` should be triggered, inserting the text `TEST`.
This is how it works in Vim and past versions of Nvim.

### Actual behavior

`BufRead` does not get triggered because the file was previously opened in the same Nvim session. This is incorrect behavior.
This breaks existing configurations, for example when using the `BufRead` trigger to enable file-specific settings or mappings.

**Comment by jamessan** [comment]
Nvim sets [`'hidden'`](https://neovim.io/doc/user/options.html#'hidden') by default, so switching away from a buffer doesn't unload it.  Therefore, there's no `BufRead` that happens when switching back to it.

If you desire that behavior, then add `set nohidden` to your init.vim.
