### ISSUE TITLE
After calling termopen('bash') previous buffer has been deleted

### ISSUE THREAD

**Issue by nyatsui** [neovim/neovim#16892]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.1

### Terminal name/version

iTerm2 Build 3.4.15

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

nvim test.py
:call termopen('bash')
C-^

Test.py buffer has been deleted.

### Expected behavior

Return to buffer of test.py

### Actual behavior

E23 error occurred.

**Comment by zeertzjq** [comment]
This is similar to #3146. I'm not sure if this is duplicate.

**Comment by zeertzjq** [comment]
Have you read `:h termopen()`?
```
termopen({cmd}[, {opts}])			*termopen()*
		Spawns {cmd} in a new pseudo-terminal session connected
		to the current buffer.  {cmd} is the same as the one passed to
		|jobstart()|.  This function fails if the current buffer is
		modified (all buffer contents are destroyed).
```

**Comment by zeertzjq** [comment]
If you don't want to return the current buffer, use `enew | call termopen('bash')`.

**Comment by nyatsui** [comment]
Thank you for the explanation.
