### ISSUE TITLE
When running vim.lsp.buf.code_action() I get an error

### ISSUE THREAD

**Issue by mcepl** [neovim/neovim#16905]
### Neovim version (nvim -v)

0.6.1 commit 297ff9764

### Vim (not Nvim) behaves the same?

NA (native LSP)

### Operating system/version

Linux, openSUSE/Tumbleweed as of 2022-01-04

### Terminal name/version

alacritty, 0.9.0

### $TERM environment variable

xterm-256color

### Installation

openSUSE nightly build from https://build.opensuse.org/package/show/home:mcepl:neovim/neovim

### How to reproduce the issue

Using python-lsp-server 1.3.3 when I run `lua vim.lsp.buf.code_action()` in the Normal mode, I get error:
```
pylsp: -32602: TypeError: m_workspace__execute_command() got an unexpected keyword argument
 'title'
```

Maintainer of python-lsp-server suggested in https://github.com/python-lsp/python-lsp-server/issues/146 that the true culprit of this erorr is neovim, not LSP server, because according to the protocol:

https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand

executeCommand accepts a command and some options for it, not title, which is what Neovim seems to be sending. So this error seems to be on the Neovim side and not here.

### Expected behavior

Code action is done (in this case, imports are sorted).

### Actual behavior

See above error message.

**Comment by mjlbach** [comment]
Need the actual RPC logs when you send the command, preferably with the minimal init.lua from the lspconfig repo

**Comment by mcepl** [comment]
All data are in the linked issue on pylsp, but it is probably bug in pylsp-rope.
