### ISSUE TITLE
lsp omnifunc cannot handles candidates when insertReplaceSupport = true

### ISSUE THREAD

**Issue by cbarber** [neovim/neovim#16909]
### Neovim version (nvim -v)

0.6.1  nvim.appimage

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 21.10

### Terminal name/version

fish 3.3.1

### $TERM environment variable

xterm-256color

### Installation

nvim.appimage download from github

### How to reproduce the issue

nvim
configure omnifunc and lsp `vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')`
`<c-x,c-o>`

### Expected behavior

omnifunc completion

### Actual behavior

```
Error executing vim.schedule lua callback: ....mount_nvimkzUaOA/usr/share/nvim/runtime/lua/vim/lsp.lua:1538: attempt to index field 'range' (a nil value)                                                
stack traceback:
        ....mount_nvimkzUaOA/usr/share/nvim/runtime/lua/vim/lsp.lua:1538: in function 'adjust_start_col'
        ....mount_nvimkzUaOA/usr/share/nvim/runtime/lua/vim/lsp.lua:1612: in function 'handler'
        ....mount_nvimkzUaOA/usr/share/nvim/runtime/lua/vim/lsp.lua:964: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
Press ENTER or type command to continue
```

**Comment by mjlbach** [comment]
What server is causing this? What is the reproduction?

**Comment by cbarber** [comment]
Ah, I hadn't considered it was rust-analyzer. Sure enough, the other language servers are working with omnifunc. I did a little bit of investigation and rust-analyzer is using lsp-types which has range as a required property:
https://github.com/gluon-lang/lsp-types/blob/master/src/lib.rs#L405

Going to debug more tomorrow and report back.

**Comment by cbarber** [comment]
It appears that the `CompletionItem` returned from `util.extract_completion_items(result)` has an optional `textEdit` field that can be `TextEdit` or `InsertReplaceEdit`:
https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionItem

`InsertReplaceEdit` has a range but its called `replace` instead

**Comment by mjlbach** [comment]
```
   * Most editors support two different operations when accepting a completion
	 * item. One is to insert a completion text and the other is to replace an
	 * existing text with a completion text. Since this can usually not be
	 * predetermined by a server it can report both ranges. Clients need to
	 * signal support for `InsertReplaceEdit`s via the
	 * `textDocument.completion.completionItem.insertReplaceSupport` client
	 * capability property.
```

Out of curiosity, do you have nvim-cmp installed? We don't set insertReplaceSupport (by default) because the omnifunc doesn't support it, so if you aren't overriding the default capabilities (as nvim-cmp does) it's a rust-analyzer bug.

**Comment by cbarber** [comment]
I do have nvim-cmp installed. If the server is sending both, is it fair for `adjust_start_col` to ignore `InsertReplaceEdit` with the nil check? I can add a comment that those types are being skipped.

**Comment by mjlbach** [comment]
I think the better fix would be to filter out those candidates if `textDocument.completion.completionItem.insertReplaceSupport` is true

**Comment by mjlbach** [comment]
Generally I don't think people can/should rely on omnifunc if they are setting additional capabilities. I'm almost more in favor of just documenting the limitations of omnifunc. It's not feasible to disable/filter all of the results from servers returned when nvim-cmp sets all of these capabilities (snippets, etc.)

**Comment by mjlbach** [comment]
I made a PR here, I think users should not use omnifunc if they are using nvim-cmp, but instead use manually triggered nvim-cmp. I'll update the lspconfig wiki

https://github.com/hrsh7th/cmp-nvim-lsp/pull/21
