### ISSUE TITLE
LSP ContentModified errors should be hidden or opt-out with capabilities

### ISSUE THREAD

**Issue by sam-mccall** [neovim/neovim#16900]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+758-g0c35fd5fc

### Language server name/version

clangd 13 (and trunk)

### Operating system/version

debian testing

### Steps to reproduce using "nvim -u minimal_init.lua"

This simulates a user editing a file and concurrently triggering document_highlight() (e.g. with CursorHold):
```
nvim -u minimal_init.lua
:lua require'lspconfig'.clangd.setup{}
:e ~/some/large/file.cpp
:lua vim.lsp.buf.document_highlight(); vim.api.nvim_set_current_line(tostring(os.time()))
```
This is a race condition, but that script is pretty reliable for me. You may have to repeat the last line a couple of times.

### Expected behavior

Highlighting is either added, or not added, but no error messages are printed
Editing should not be disrupted.

### Actual behavior

Error message is shown: "clangd: -32801: Request cancelled because the document was modified".
It uses `vim.notify()` + `:redraw`, which disrupts editing.

---

One fix would be to mute the error messages for -32801 (per LSP: "If clients receive a ContentModified error, it generally should not show it in the UI for the end-user"). -32800 is already muted, unfortunately in this case handlers would still probably need to be invoked.

Another fix would be to set the client capability `general.staleRequestSupport.cancel`, in which case the client is explicitly takes responsibility for cancelling requests that become stale. (This is not trivial to do in general).
In this case, the server will never abandon seemingly-stale requests.

---

A bit of background: these cancellations happen because old/sad/simplistic clients would trigger requests on every keystroke and not notice they were creating a backlog on the server, which must parse every version of the document in order to service each request.
These error responses allows the server to drop requests that (heuristically) seem to have been invalidated by changes to the document.

Microsoft's preferred solution is to make the _client_ responsible for aggressively cancelling requests, however not all clients do this. So they created the `staleRequestSupport` capability, and set it in VSCode.

They also later added text to "ContentModified" that said servers shouldn't cancel requests in this way, and clients should cancel instead. Unfortunately this ignores the reality that many legacy and current clients will never do this.
(This isn't a theoretical issue, users [reported this in eglot](https://old.reddit.com/r/emacs/comments/fc7bhq/lspmodeclangd_extremely_slow_characterbycharacter/))

**Comment by mjlbach** [comment]
> Microsoft's preferred solution is to make the client responsible for aggressively cancelling requests, however not all clients do this.

It would actually be pretty easy for us to register a timer to cancel requests since we don't generate any request by default (we could set these in buf.lua), I would worry a bit about shifting complexity onto plugin developers though, who would be required to then manage their own requests. 

For document_highlight, we could add a request cancellation by default that inspects the most recent document version sent to the server and cancels the request if the last document version sent to the server doesn't match the current document version.

**Comment by sam-mccall** [comment]
> I would worry a bit about shifting complexity onto plugin developers though, who would be required to then manage their own requests.

Agreed, I like how plugins on top of nvim's LSP are lightweight.
The MS model makes more sense if someone owns the whole design end-to-end.

I think just suppressing the err_message() call in handlers.lua based on code is the best option (per the LSP guidance about not showing this error in UI).
If I'm reading right this only affects the built-in handlers, plugin handlers get the errors today and will continue to.

Is it useful to send a PR?

> For document_highlight, we could add a request cancellation by default

Yeah, you could check for invalidation after a timer or something. Another option is to cancel the first request when a second is issued.
At least for clangd it's not critical that any particular requests get cancelled, as long as we're allowed to drop them (without displaying loud errors).

**Comment by mjlbach** [comment]
> Is it useful to send a PR?

Sure, if you have the time. It should be pretty simple.

> Yeah, you could check for invalidation after a timer or something. 

One thing that might be useful (generally) is to expose an API for "cancelling". Right now we just return the request ID or a closure (in the case of the buf_request) series of functions. It's pretty trivial to wrap this with a timer, but that timer would be unaware of any subsequent requests/notification.

**Comment by mjlbach** [comment]
I'm not actually able to reproduce this. Can you send me an example file that causes an issue? The fix should be in rpc.lua instead of handlers (see where we suppress other warnings).

**Comment by sam-mccall** [comment]
Making this into a tight loop works or my machine even with an empty cpp file:

```
:lua for i=1,100 do vim.lsp.buf.document_highlight(); vim.api.nvim_set_current_line(tostring(math.random())) end
```

(Previously I was using a large file, [SemaCodeComplete.cpp](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaCodeComplete.cpp) triggers this without looping)

> The fix should be in rpc.lua instead of handlers (see where we suppress other warnings).

I'm happy to do change this if you like, but let me explain why I didn't :-)

In general, I don't think it's OK if the handler doesn't get invoked at all on error. Suppose a plugin associates state with requests it issues, then it will never get a chance to clean up the state.
(This could happen anyway if the server just never responds, but that shouldn't happen in normal operation). 

OTOH in handlers.lua none of the handlers do anything like this, and in fact most of them begin with `if not result then return end` - those particular handlers are fine to ignore on transient error.
 
Suppressing the handler call in rpc.lua on RequestCancelled is a bit different: if we trust the request really was cancelled, then it must be the issuing plugin that did the cancellation and can take care of cleanup. Personally I think it's cleaner to invoke the handler in any case, but either way is workable.

**Comment by mfussenegger** [comment]
> The fix should be in rpc.lua instead of handlers (see where we suppress other warnings).

We removed that from rpc.lua so that clients have the option to handle the ContentModified errors: https://github.com/neovim/neovim/commit/3f097321955e32b0724e0f0d059ecef3d764aac8

I think re-adding handling in the default handlers is a good compromise - it still allows users to override & handle them, but mutes them per default.
