### ISSUE TITLE
OSX: clipboard provider acting strangely

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#1690]
I'm on commit 10a45846dc959f8b3 (current master at the time of writing).

It seems that trying to yank always yields good results. I yank some line(s) of text in vim and can paste them in any other app. The other way around doesn't seem to work as well though. When I copy text (for example from this textbox) and try to paste it into nvim with 'p', it just pastes the text I yanked from vim in the first place.

At first I thought this might be because of the difference between `unnamed` and `unnamedplus` (even though I thought that OSX didn't make that distinction). But they both show exactly the same behaviour.

Even more curiously, it seems like the text I copy from other applications _can_ be pasted if I just pick the right register. For example, with `clipboard=unnamed`, I can paste text from the OSX clipboard with `"+p` and `"*p` (this always works).

The worst thing is that it doesn't seem to be 100% deterministic, sometimes it does work, though mostly it doesn't (or maybe it's my mind playing tricks on me. (it also seems that sometimes, using `"+p` seems to "synchronize" the clipboards sometimes, but using `"*p` always synchronizes it).

What I mean by synchronizing is that after using `"*p`, I can just use `p` and it works.

I know this is a pretty vague bug report but I can't detect a pattern. I'm hoping that @bfredl or someone else have a lightbulb moment after reading this :).

(I did `make install` btw, so the runtime should be of the current version, unless there is a problem with overwriting the runtime).

**EDIT**: I take that back, yanking doesn't always seem to work either...

**Comment by aktau** [comment]
Related vim_dev discussion that could help with the tao of external vim pasting:

https://groups.google.com/forum/#!msg/vim_dev/SgjFRJemgKM/ztt0q3bkR10J

Bumped upon it because I was thinking of just handling any external information as being characterwise (avoiding the need to check the register type and invoking the provider all the time), but that obviously wouldn't work since there could be something from either Vim or from an external program in the buffer at any given moment and we'd be none the wiser. Obviously we at least need to keep the linewise modes for Vim selections.

If the delay of doing ]p (which basically forces linewise paste) wasn't noticeable for me, maybe I wouldn't notice so badly. Then again, something feels like that `s:putline` could be optimized a bit for interaction with an external clipboard a bit more. But it's Tim Pope we're talking about so I'm sure I'm missing about 100 pitfalls of doing it another way.

**Comment by aktau** [comment]
Another update on useful links. This is for my personal clipboard (pun only slightly intended) so that when I get some time I can fix it myself if others haven't gotten to it first.

### Linux

X11 clipboard operation shortly explained in a sane fashion, must read to get an idea of how to fix it on Linux: http://burrows.svbtle.com/universal-copy-paste-in-linux
X11 selections by Keith Packard, for those who want to delve deeper: http://x.cygwin.com/docs/cg/porting-docs/selection.pdf (I had already posted this in #1908)

**Comment by bfredl** [comment]
> The issue seems to center on the adjust_clipboard_name() as called by get_clipboard() function not anticipating that someone could pass the " register directly. Currently it just checks for *name == NUL, but it should also check if *name == '"'. (v:register is often ").

I don't think this should be done. `getreg()`/`p`and `getreg('"')`/`""p` are not synonymous. the later pastes `y_previous` even if `clipboard=unnamed`.

**Comment by aktau** [comment]
So is this a flaw in vim-unimpaired's assumptions? At any rate, it seems to work differently from vanilla Vim.

**Comment by bfredl** [comment]
yes, it is not entirely correct in `nvim` right now.

**Comment by bfredl** [comment]
the later I mean, haven't checkt `vim-unimpaired`

**Comment by bfredl** [comment]
No, there was no flaw in `vim-unimpaired` (at least not the snippet you posted), it relies on `v:register` which was broken in `nvim` when `clipboard=unnamed`.  #2381 might fix it.

**Comment by justinmk** [comment]
Assuming this is fixed by the numerous commits from @bfredl
