### ISSUE TITLE
Can't use all the colors defined in syntax.c

### ISSUE THREAD

**Issue by ericonr** [neovim/neovim#16913]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

I don't have vim installed right now

### Operating system/version

Linux, tested on glibc and musl libc

### Terminal name/version

Both inside tmux and in foot

### $TERM environment variable

`screen` or `foot`

### Installation

Void Linux package

### How to reproduce the issue

`nvim --clean`
`:highlight Normal ctermfg=darkorange`

### Expected behavior

The interface would be set to the dark orange color, as specified in the file `RGB_(0xff, 0x8c, 0x00)`

### Actual behavior

Errors out with `E421: Color name or number not recognized: ctermfg=darkorange`.

Using the same spelling as `src/nvim/syntax.c`, `DarkOrange`, doesn't work either.

The colors that work (`darkblue`, `darkcyan`, ...) seem to be mentioned in `runtime/syntax/mp.vim`, and the ones I tested which don't work aren't there.

**Comment by zeertzjq** [comment]
`:h cterm-colors` doesn't list `DarkOrange` as a recognized color name for `ctermfg`. It is supported for `guifg`.

**Comment by ericonr** [comment]
Oh, I see. Thanks!
