### ISSUE TITLE
Neovim version 0.4.4 installed when installing from command line

### ISSUE THREAD

**Issue by ameya-deshmukh** [neovim/neovim#16915]
### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

Pop!_OS 21.10

### Terminal name/version

-

### $TERM environment variable

-

### Installation

Command Line (sudo apt-get install)

### How to reproduce the issue

sudo apt-get install neovim

### Expected behavior

Expected that latest stable release will be installed. 

### Actual behavior

Version 0.4.4 installed.

**Comment by clason** [comment]
That's an issue you have to raise with your distribution; we have no control over which versions they package.
