### ISSUE TITLE
Lua ftplugin file from user config is sourced after runtime ftplugin

### ISSUE THREAD

**Issue by gbrlsnchs** [neovim/neovim#16928]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+829-g39238435d

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Arch Linux (5.15.12-arch1-1)

### Terminal name/version

alacritty 0.9.0 (fed349aa)

### $TERM environment variable

alacritty

### Installation

neovim-git through AUR

### How to reproduce the issue

This example applies to a Rust file, but might be reproducible for other filetypes as well. In `~/.config/neovim`, there should be a `ftplugin/rust.lua`. This enough to check the sourcing order.

Then, run Neovim (sorry, the clean version would not source the custom ftplugin) and edit a rust file (`:edit test.rust`).

Now, check `:scriptnames`.

### Expected behavior

`~/.config/nvim/ftplugin/rust.lua` should be sourced _before_ `/usr/share/nvim/runtime/ftplugin/rust.vim`, allowing to set, for example, `b:did_ftplugin` so it can skip things from the runtime ftplugin file. If instead of a Lua file we use a Vim file, it works correctly.

### Actual behavior

`~/.config/nvim/ftplugin/rust.lua` is source _after_ `/usr/share/nvim/runtime/ftplugin/rust.vim`, acting just similar to as if it was in `after/ftplugin`, forcing me to maintain a Vim ftplugin file only to bypass the runtime ftplugin file.

**Comment by gpanders** [comment]
This is due to these lines in `ftplugin.vim`:

https://github.com/neovim/neovim/blob/a45b578dbe6ba02ba9a052a7b058f4243d38a07b/runtime/ftplugin.vim#L28-L34

**Comment by fenuks** [comment]
This is also problem for those that have their init file spitted over many files.

In my case, in `init.vim` file I source `functions.vim`, and in `after/ftplugin/rust.vim` I call some of those functions. Since nvim 0.7 `after/ftplugin` scripts are sourced before ones in `init.vim`.

**Comment by clason** [comment]
That is not correct -- `after/ftplugin` is definitely sourced (long) after `init.vim`.

You can check `:scriptnames` for the exact load order.

**Comment by fenuks** [comment]
Well, I was wrong again… The problematic configuration is… `syntax on`.

Minimal configuration to reproduce issue on my machine:

```vimrc
" min.vim
syntax on
source min-functions.vim
```

```vimrc
" min-functions.vim
function! ConfigureLanguage() abort
    echom 'test'
endfunction
```

```vimrc
" ~/.config/nvim/after/ftplugin/mail.vim
call ConfigureLanguage()
```

Running something like `nvim -u ~/.config/nvim/min.vim mail.eml` results in 

```
Error detected while processing /home/fenuks/.config/nvim/after/ftplugin/mail.vim:
line   11:
E117: Unknown function: ConfigureLanguage
```

and scriptnames order is

```
 :scriptnames                                                                                                                                                      
  1: /usr/share/nvim/runtime/ftplugin.vim
  2: /usr/share/nvim/runtime/indent.vim
  3: ~/.config/nvim/min.vim
  4: /usr/share/nvim/runtime/syntax/syntax.vim
  5: /usr/share/nvim/runtime/syntax/synload.vim
  6: /usr/share/nvim/runtime/filetype.lua
  7: /usr/share/nvim/runtime/filetype.vim
  8: /usr/share/nvim/runtime/ftplugin/mail.vim
  9: ~/.config/nvim/after/ftplugin/mail.vim
 10: /usr/share/nvim/runtime/indent/mail.vim
 11: /usr/share/nvim/runtime/syntax/mail.vim
 12: ~/.config/nvim/min-functions.vim
 13: /usr/share/nvim/runtime/plugin/gzip.vim
 14: /usr/share/nvim/runtime/plugin/health.vim
 15: /usr/share/nvim/runtime/plugin/man.vim
 16: /usr/share/nvim/runtime/plugin/matchit.vim
 17: /usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
 18: /usr/share/nvim/runtime/plugin/matchparen.vim
 19: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
 20: /usr/share/nvim/runtime/plugin/rplugin.vim
 21: ~/.local/share/nvim/rplugin.vim
 22: /usr/share/nvim/runtime/autoload/remote/host.vim
 23: /usr/share/nvim/runtime/autoload/remote/define.vim
 24: /usr/share/nvim/runtime/plugin/shada.vim
 25: /usr/share/nvim/runtime/plugin/spellfile.vim
 26: /usr/share/nvim/runtime/plugin/tarPlugin.vim
 27: /usr/share/nvim/runtime/plugin/tohtml.vim
 28: /usr/share/nvim/runtime/plugin/tutor.vim
 29: /usr/share/nvim/runtime/plugin/zipPlugin.vim
```

Moving `syntax on` below line that sources file helps. I'm running 
```
$ nvim --version
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
on Arch Linux.

**Comment by clason** [comment]
Yes. `syntax on` triggers a bunch of things (it's a _command_ not an opt).

It's virtually never needed in Neovim as syntax is enabled by default.

**Comment by fenuks** [comment]
I see, but in previous versions of vim, it didn't behave this way. I had this very config since at least nvim-0.4, and it worked. Are you certain that this change of behaviour isn't a bug? If it isn't considered a bug, it's still rather unexpected and difficult to predict, and behaviour is not compatible with vim.

**Comment by clason** [comment]
It's not a bug (at least going by the information you have shared so far), and definitely intended. 

The goal of Neovim is different from Vim (same defaults on modern systems rather than backward compatibility for old systems).

**Comment by fenuks** [comment]
> It's not a bug (at least going by the information you have shared so far), and definitely intended.

I must admit I still have doubts. I would say it's a breaking change, and it's not mentioned in release notes. Regarding syntax and filetype detection, release notes mention filetype.lua, syntax being turned on with `--clean`, but I could find note about that change, and it seems strange.

> The goal of Neovim is different from Vim (same defaults on modern systems rather than backward compatibility for old systems).

I know, but question is how breaking this behaviour makes neovim closer to the goal given that syntax highlighting was on by default in prior releases already, and it worked. That's why reading about all those changes, it seems probable to me that this change might not be intentional. I will try to bisect nvim repository when I have a moment, maybe commit message contains some rationale behind this change.

**Comment by clason** [comment]
Sorry, but let me be blunt: this is an edge case, and an instance of the egg broken to make an omelet. There wee a lot of changes under the hood to make typical(!) behaviour _less_ broken; it's impossible to anticipate the effect on all the million different legacy configs in the wild. 

We can only warn about _intended_ breakage (which we do!)

**Comment by fenuks** [comment]
I don't mind and I understand what you mean, and I surely think there is high probability it *is* intended change, but you never know. Neovim moves fast, and I would say that in each major release I stumbled upon some minor issues that were later fixes in bugfix releases. What mainly makes me wonder is that as a humble user, superficially, I don't see how this change is an improvement, but it might a huge improvement under the hood for the developers, of course.

**Comment by clason** [comment]
I don't want to drag this out, but for the sake of clarity:
1. `syntax on` has not been needed for a long time
2. If there are issues, removing it from your config is extremely easy and without drawbacks
3. the documentation has already been adapted to not mention it as something useful

So I don't really see anything actionable?

**Comment by fenuks** [comment]
For the reference, this behaviour was introduced in https://github.com/neovim/neovim/commit/de6f9233eee937139f607d3a59fd5b1f479d8a13.

**Comment by clason** [comment]
Anyway, this is a _different_ issue than the one reported here, which specifically affects **Lua** ftplugin files -- that one indeed needs to be fixed.

**Comment by clason** [comment]
Note from chat: this seems to also affect `after/ftplugin` where runtime `ftplugin/c.lua` takes precedence over user `after/ftplugin/c.vim`.  (@3N4N)

**Comment by 3N4N** [comment]
@clason PR 23801 doesn't fix my issue.
