### ISSUE TITLE
vim.on_key(): more user-friendly way to pass modifiers

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#16932]
### Feature already in Vim?

No

### Feature description

Currently `vim.on_key()`  is not very user-friendly when passing modifiers: it encodes them as `K_SPECIAL` sequences. A more user-friendly way to pass modifiers is probably to pass a table. This will break backward-compatibility, but I doubt anyone bothers parsing `K_SPECIAL` sequences manually.

**Comment by zeertzjq** [comment]
Maybe only passing modifiers in a more user-friendly way is not enough, as it is hard to convert keycode back to key notations as well (AFAIK this can currently only be done using FFI). So maybe a better solution is to add a method to do the reverse of `nvim_replace_termcodes()`.

**Comment by cjquines** [comment]
adding a method to do the reverse of `nvim_replace_termcodes()` sounds like the move? it's backwards compatible, at least.

i'm aware of two plugins that use `on_key()` or `register_keystroke_callback()`. there's [nvim-cmp](https://github.com/hrsh7th/nvim-cmp/blob/main/plugin/cmp.lua#L115) which compares the key to the result of `nvim_replace_termcodes()`; this will break if the output is changed. also, [vim-apm](https://github.com/ThePrimeagen/vim-apm/blob/master/lua/vim-apm/init.lua#L154) which checks previous inputs of `on_key()` to new inputs of `on_key()` for equality; this will break with tables.

**Comment by zeertzjq** [comment]
I no longer want to keep this issue open as it sounds like an XY problem.
