### ISSUE TITLE
`do filetypedetect BufRead filename` doesn't work if using filetype.lua

### ISSUE THREAD

**Issue by kevinhwang91** [neovim/neovim#16939]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ArchLinux

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

build from repo

### How to reproduce the issue

1. enable filetype.lua by setting `vim.g.did_load_filetypes = 0; vim.g.do_filetype_lua = 1`
2. `echo 'print("hello world!, lua filetype")' > a.lua`
3. `nvim +'read a.lua' +'do filetypedetect BufRead a.lua'`, no file type detect;
4. Use filetype.vim instead of filetype.lua and repeat step 3, currrent buffer can be detected as a lua file.

[ctrlsf.vim](https://github.com/dyng/ctrlsf.vim) and [nvim-bqf](https://github.com/kevinhwang91/nvim-bqf) use this way to get the content read from the files into the temporary buffer and get its file type to do syntax highlighting, resulting in smaller side effect.

I think filetype.lua should check `<amatch>` before `<abuf>`

### Expected behavior

filetype.lua should work like filetype.vim.

### Actual behavior

filetype.lua can't detect file type from `do filetypedetect BufRead filename`.

**Comment by clason** [comment]
Filetype.lua is only in the latest nightly, not in 0.6.1.

**Comment by kevinhwang91** [comment]
I write so fast, sorry, it's nightly
