### ISSUE TITLE
<BS> doesn't work in Telescope search field/nvim-dap after toggleing insert mode

### ISSUE THREAD

**Issue by Drllap** [neovim/neovim#16931]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 10

### Terminal name/version

MIcrosoft Windows Terminal 1.11.3471

### $TERM environment variable

vtpcon

### Installation

chocolatey

### How to reproduce the issue

Minimal vimrc:
```
call plug#begin(stdpath('data') . '/test-plugged')
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()
```
* Install the pluggins `:PlugInstall`
* Run `:Telescope`
* Type something into the search field
* Exit insert mode
* Enter insert mode again
* Press `<BS>`

### Expected behavior

The content the the Telescope search field should be removed

### Actual behavior

Nothing happens.

* I'm posting this issue in this repo instead of in the Telescope repo because I see the exact same problem when using the repl in nvim-dap.
* The same appears when using both TUI and nvim-qt.
* This works perfectly when running on WSL Ubuntu 20.04

**Comment by seandewar** [comment]
This is fixed in https://github.com/neovim/neovim/pull/16421 for 0.7, but we decided not to backport to 0.6.1 due to the behaviour changes with <C-W> in insert mode.

**Comment by Drllap** [comment]
Can confirm, tried installing the v0.7 via `choco install neovim --pre` and it workes fine there
Also, it turned out I was already using the v0.7 on my WSL so maybe this wasn't a Windows-specific issue
