### ISSUE TITLE
vim.lsp.util.get_progress_messages

### ISSUE THREAD

**Issue by melsiir** [neovim/neovim#16947]
### Neovim version (nvim -v)

0.6.1

### Language server name/version

typescript-language-server@0.8.1

### Operating system/version

Android 10

### :checkhealth

```markdown
2 lspconfig:                                                                                                                                 3 ========================================================================
   4   - ERROR: No healthcheck found for "lspconfig" plugin.                                                                                    5
   6 nvim: health#nvim#check
   7 ========================================================================                                                                   8 ## Configuration
   9   - ERROR: Locale does not support UTF-8. Unicode characters may not display correctly.
  10   ▏ $LANG=en_US.UTF-8 $LC_ALL= $LC_CTYPE=
  11   ▏ - ADVICE:
  12   ▏ ▏ - If using tmux, try the -u option.
  13   ▏ ▏ - Ensure that your terminal/shell/tmux/etc inherits the environment, or set $LANG explicitly.
  14   ▏ ▏ - Configure your system locale.
  15
  16 ## Performance
  17   - OK: Build type: Release
  18
  19 ## Remote Plugins
  20   - OK: Up to date
  21
  22 ## terminal
  23   - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  24   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  25   - INFO: $COLORTERM='truecolor'
  26
```

### Steps to reproduce using "nvim -u minimal_init.lua"

Actually my lsp work full but I am trying to use this plugin that show loading animation while lsp is loading :

https://github.com/arkav/lualine-lsp-progress

But it didn't 
It use this api command to get lsp updates :
vim.lsp.util.get_progress_messages()

And when I tried it on neovim cmd I got following error :

"util.get_progress_messages()" [New]
Cannot open file "util.get_progress_messages()"
E480: No match: lsp
Press ENTER or type command to continue

Does neovim has any limitations on Android devices I am using termux v 0.117 on Android 10

### Expected behavior

Get lsp_progress animation

### Actual behavior

Not work

**Comment by mjlbach** [comment]
The function works on neovim built-from source on macos, Windows, and linux. I can only assume this is a build issue, perhaps there are missing runtime files. Regardless we don't officially support android so you will have to debug your installation.

**Comment by melsiir** [comment]
> The function works on neovim built-from source on macos, Windows, and linux. I can only assume this is a build issue, perhaps there are missing runtime files. Regardless we don't officially support android so you will have to debug your installation.

How ?

**Comment by melsiir** [comment]
> The function works on neovim built-from source on macos, Windows, and linux. I can only assume this is a build issue, perhaps there are missing runtime files. Regardless we don't officially support android so you will have to debug your installation.

I use termux which give Linux environment on Android :
Termux is a terminal emulator for Android which allows for running a Linux environment on an Android device.

It based on debian

I do all my development on it with high capabilities

**Comment by mjlbach** [comment]
I'm sorry, I don't have termux experience. There's something wrong with your build, that's all I know. You can try posting on our discourse and see if anyone else has experience using termux with neovim.

**Comment by melsiir** [comment]
> I'm sorry, I don't have termux experience. There's something wrong with your build, that's all I know. You can try posting on our discourse and see if anyone else has experience using termux with neovim.

Where ?

**Comment by mjlbach** [comment]
https://neovim.discourse.group/

**Comment by fsouza** [comment]
@melsiir you're trying to invoke `vim.lsp.util.get_process_messages` as a nvim command, but it's a lua function. You need to invoke it as part of some lua code.

If you want to simply test it from the command line, you need to do something like:

```
:lua print(vim.inspect(vim.lsp.util.get_progress_messages()))
```

**Comment by mjlbach** [comment]
Thanks @fsouza, I didn't realize that was what they were doing.

**Comment by melsiir** [comment]
> @melsiir you're trying to invoke `vim.lsp.util.get_process_messages` as a nvim command, but it's a lua function. You need to invoke it as part of some lua code.
> 
> If you want to simply test it from the command line, you need to do something like:
> 
> ```
> :lua print(vim.inspect(vim.lsp.util.get_progress_messages()))
> ```

I tested with my project like this :

nvim server.js -c ":lua print(vim.inspect(vim.lsp.util.get_progress_messages()))" but I only got just empty curly Brackets I suppose to be there some vslues for the lsp right

**Comment by mjlbach** [comment]
> nvim server.js -c ":lua print(vim.inspect(vim.lsp.util.get_progress_messages()))" but I only got just empty curly Brackets I suppose to be there some vslues for the lsp right

There are many reasons that snippet doesn't make sense. The issue tracker isn't the place for that, so I suggest you ask on the discourse. Progress messsages are not instantly sent to the server, I'm not even sure the vim command that executes the lua snippet runs after bufenter (or for that matter when exactly it runs) so the server may not even be started at that point.
