### ISSUE TITLE
Flaky `curwin` pointer comparisons

### ISSUE THREAD

**Issue by ubitux** [neovim/neovim#16941]
### Neovim version (nvim -v)

0.6.1, v0.7.0-dev+835-gf65b0d423

### Vim (not Nvim) behaves the same?

no (but repro case is different)

### Operating system/version

Linux / glibc 2.33

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

alacritty

### Installation

package (0.6.1) and built from source (0.7.0-dev)

### How to reproduce the issue

1. Install `fzf` on the system
2. Assuming `fzf` is installed in `/usr` (adjust the `source` setting otherwise):
```console
% mkdir /tmp/test
% cd /tmp/test
% cat <<EOF > init.vim
source /usr/share/vim/vimfiles/plugin/fzf.vim
nnoremap <C-p> :FZF<CR>
set cursorline
set cursorcolumn
set number
EOF
% nvim --clean -u init.vim
```
3. press `C-p` and `C-t` repeatedly

### Expected behavior

The only file present in the directory (`init.vim` here) should open in a new tab, preserving the current window configuration.

### Actual behavior

Sometimes, the new window doesn't inherit properly all the settings (`cursorline` and `cursorcolumn` go away):

https://user-images.githubusercontent.com/34467/148231181-9fd480e5-dd75-442b-a75d-b190800764cd.mp4

---

I did some investigation, and the cause of the issue is the following: neovim is doing `curwin` comparison between pointers, but sometimes malloc returns the same pointer after being free'd.

Given the following debug-diff:
```diff
diff --git a/src/nvim/terminal.c b/src/nvim/terminal.c
index 70a5c7aa0..126a8a262 100644
--- a/src/nvim/terminal.c
+++ b/src/nvim/terminal.c
@@ -416,7 +416,15 @@ void terminal_enter(void)

   s->state.execute = terminal_execute;
   s->state.check = terminal_check;
+
+  smsg(">>> state enter / curwin unchanged:%s [saved:%p (h:%d) curwin:%p (h:%d)])",
+       save_curwin == curwin ? "yes": "no",
+       (void*)save_curwin, save_curwin->handle, (void*)curwin, curwin->handle);
+
   state_enter(&s->state);
+  smsg("<<< state exit  / curwin unchanged:%s [saved:%p (h:%d) curwin:%p (h:%d)])",
+       save_curwin == curwin ? "yes" : "no",
+       (void*)save_curwin, save_curwin->handle, (void*)curwin, curwin->handle);

   restart_edit = 0;
   State = save_state;
diff --git a/src/nvim/window.c b/src/nvim/window.c
index 1e747a67e..c17a08c7c 100644
--- a/src/nvim/window.c
+++ b/src/nvim/window.c
@@ -3690,6 +3690,7 @@ void win_alloc_aucmd_win(void)
 static int win_alloc_firstwin(win_T *oldwin)
 {
   curwin = win_alloc(NULL, false);
+  smsg("win_alloc_firstwin() -> %p", (void*)curwin);
   if (oldwin == NULL) {
     // Very first window, need to create an empty buffer for it and
     // initialize from scratch.
@@ -4800,6 +4801,7 @@ static void win_free(win_T *wp, tabpage_T *tp)
   int i;
   wininfo_T *wip;

+  smsg("win_free(%p)", (void*)wp);
   pmap_del(handle_T)(&window_handles, wp->handle);
   clearFolding(wp);
```

Here is a sequence of what typically happens:

```
win_free(0x5587ef127310)
win_alloc_firstwin() -> 0x5587ef126b10
<<< state exit  / curwin unchanged:no [saved:0x5587ef127310 (h:0) curwin:0x5587ef126b10 (h:1004)])
>>> state enter / curwin unchanged:yes [saved:0x5587ef12fbb0 (h:1005) curwin:0x5587ef12fbb0 (h:1005)])
win_free(0x5587ef12fbb0)
win_alloc_firstwin() -> 0x5587ef12cb80
<<< state exit  / curwin unchanged:no [saved:0x5587ef12fbb0 (h:0) curwin:0x5587ef12cb80 (h:1006)])
>>> state enter / curwin unchanged:yes [saved:0x5587ef1370d0 (h:1007) curwin:0x5587ef1370d0 (h:1007)])
win_free(0x5587ef1370d0)
win_alloc_firstwin() -> 0x5587ef19b8c0
<<< state exit  / curwin unchanged:no [saved:0x5587ef1370d0 (h:1007) curwin:0x5587ef19b8c0 (h:1008)])
>>> state enter / curwin unchanged:yes [saved:0x5587ef13c390 (h:1009) curwin:0x5587ef13c390 (h:1009)])
win_free(0x5587ef13c390)
win_alloc_firstwin() -> 0x5587ef13c390
<<< state exit  / curwin unchanged:yes [saved:0x5587ef13c390 (h:1010) curwin:0x5587ef13c390 (h:1010)])
```

The last `win_free()`/`win_alloc_firstwin()` pair has matching pointers, which messes up a lot of comparison, typically in `terminal.c` the following (but not the only place):

```c
  if (save_curwin == curwin) {  // save_curwin may be invalid (window closed)!
```

I'm not sure how to fix that, in particular because I see a lot of other `curwin` pointer comparison. I would say that having the `free` happening *after* the allocation of the new window would be the safest, but I'm not sure how to achieve that (I'm not familiar with the codebase at all).

This bugs is expressed relatively harmlessly in this case (pretty annoying though), but I believe very bad things could happen messing with pointers like this.

Also note that `cursorcolumn` and `cursorline` are reset because the floating window uses a minimal style which resets those, but for some reason the line numbering is not affected.

**Comment by jamessan** [comment]
Hmm, it sounds like this should also be a problem upstream with Vim, since a lot of the `curwin == ...` checks are inherited from it.  Although the specific code you're talking about _has_ been heavily refactored, so maybe we introduced an issue here?

**Comment by ubitux** [comment]
> Hmm, it sounds like this should also be a problem upstream with Vim, since a lot of the `curwin == ...` checks are inherited from it. Although the specific code you're talking about _has_ been heavily refactored, so maybe we introduced an issue here?

I'm not able to reproduce in Vim but the spawning logic of fzf is very different:

```vim
    if has('nvim')
      call termopen(command, fzf)
    else
      let term_opts = {'exit_cb': function(fzf.on_exit)}
      if v:version >= 802
        let term_opts.term_kill = 'term'
      endif
      if is_popup
        let term_opts.hidden = 1
      else
        let term_opts.curwin = 1
      endif
      let fzf.buf = term_start([&shell, &shellcmdflag, command], term_opts)
      if is_popup && exists('#TerminalWinOpen')
        doautocmd <nomodeline> TerminalWinOpen
      endif
      if !has('patch-8.0.1261') && !s:is_win
        call term_wait(fzf.buf, 20)
      endif
    endif
```

The popup is also created differently:
```vim
if has('nvim')
  function s:create_popup(hl, opts) abort
    let buf = nvim_create_buf(v:false, v:true)
    let opts = extend({'relative': 'editor', 'style': 'minimal'}, a:opts)
    let win = nvim_open_win(buf, v:true, opts)
    call setwinvar(win, '&winhighlight', 'NormalFloat:'..a:hl)
    call setwinvar(win, '&colorcolumn', '')
    return buf
  endfunction
else
  function! s:create_popup(hl, opts) abort
    let s:popup_create = {buf -> popup_create(buf, #{
      \ line: a:opts.row,
      \ col: a:opts.col,
      \ minwidth: a:opts.width,
      \ maxwidth: a:opts.width,
      \ minheight: a:opts.height,
      \ maxheight: a:opts.height,
      \ zindex: 1000,
    \ })}
    autocmd TerminalOpen * ++once call s:popup_create(str2nr(expand('<abuf>')))
  endfunction
endif
```

So it's hard to say if Vim is affected or not.

**Comment by justinmk** [comment]
> in particular because I see a lot of other `curwin` pointer comparison.

This is usually just a sad hack. Comparing handles is much better, if we can.
