### ISSUE TITLE
Vertical split is not creating independant buffers. All buffers are scrolling together. The buffer which isn't foucsed will have lots of rendering issues as it scrolls.

### ISSUE THREAD

**Issue by K4LCIFER** [neovim/neovim#16966]
### Neovim version (nvim -v)

v0.6.0-dev+1-g62d67de59

### Vim (not Nvim) behaves the same?

no 8.2 (2019 Dec 12, compiled Dec 25 2021 11:17:40)

### Operating system/version

Arch Linux

### Terminal name/version

gnome-terminal 3.42.2

### $TERM environment variable

xterm-256color

### Installation

AUR

### How to reproduce the issue

1. Open 2 different files in a vertical split: one with a lot of lines, the other with less
2. Focus one buffer and scroll
3. Observe that both buffers scroll together
4. Observe the rendering glitches in the unfocused buffer

### Expected behavior

I expect to be able to scroll each buffer individually with no rendering glitches

### Actual behavior

Actual behaviour as seen [here](https://imgur.com/DSwrELJ).

**Comment by zeertzjq** [comment]
You Nvim version is too old.

**Comment by zeertzjq** [comment]
Duplicate of #16238

**Comment by K4LCIFER** [comment]
> Your Nvim version is too old.

Ah, yeah. I just uninstalled neovim-git, and reinstalled it. Now I'm on `NVIM v0.7.0-dev+844-gb43575545` and the problem is solved. Not sure why it hadn't been updating.
