### ISSUE TITLE
No command for the clipboard

### ISSUE THREAD

**Issue by cacplate** [neovim/neovim#1696]
I'm using neovim on Archlinux 64bit and I don't seem to be able to use the system clipboard in Neovim. Everytime I use the key combination "+p it complains:

clipboard: No shell command for communicating with the clipboard found.
E117: Unknown function: provider#clipboard#Call

**Comment by nfm** [comment]
I also just hit this error. It happens to me when I launch neovim, as well as when I try to use `"+p`. I think the on-launch error may be to do with the YankRing plugin.

I'm on Ubuntu 14.10.1, and I installed neovim using the PPA (https://launchpad.net/%7Eneovim-ppa/+archive/ubuntu/unstable), so I think I should be up to date.

NVIM 0.0.0-alpha (compiled Feb 23 2015 00:20:21)
neovim-0.0.0+git201502221955+6~ubuntu14.10.1

**Comment by cacplate** [comment]
Since then I set the clipboard in my nvimrc from the wiki

**Comment by justinmk** [comment]
@cacplate are/were you using a plugin like yankring?

**Comment by cacplate** [comment]
no nothing
just plain: set clipboard+=unnamed

**Comment by cacplate** [comment]
That way I can use "p" and "y" for system clipboard which is better IMHO.

**Comment by nfm** [comment]
I don't know much about vim and X11 clipboard handling but am happy to provide more info if needed.

Disabling YankRing fixed the error on launch. I still get a `clipboard: provider is not available` error when trying to yank into the `+` or `*` registers.

It looks like the Neovim Ubuntu PPA package is compiled without `xterm_clipboard`:

```sh
NVIM 0.0.0-alpha (compiled Mar  1 2015 17:17:41)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/buildd/neovim-0.0.0+git201502281412+1389+8+6~ubuntu14.10.1/build/config -I/build/buildd/neovim-0.0.0+git201502281412+1389+8+6~ubuntu14.10.1/src -I/build/buildd/neovim-0.0.0+git201502281412+1389+8+6~ubuntu14.10.1/.deps/usr/include -I/build/buildd/neovim-0.0.0+git201502281412+1389+8+6~ubuntu14.10.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/buildd/neovim-0.0.0+git201502281412+1389+8+6~ubuntu14.10.1/.deps/usr/include -I/build/buildd/neovim-0.0.0+git201502281412+1389+8+6~ubuntu14.10.1/.deps/usr/include -I/usr/include -I/build/buildd/neovim-0.0.0+git201502281412+1389+8+6~ubuntu14.10.1/build/src/nvim/auto -I/build/buildd/neovim-0.0.0+git201502281412+1389+8+6~ubuntu14.10.1/build/include
Compiled by buildd@lcy01-07  Features included (+) or not (-):
+acl             +farsi           -mouse_gpm       +tag_old_static
+arabic          +file_in_path    +mouse_netterm   -tag_any_white
+autocmd         +find_in_path    +mouse_sgr       +termresponse
-browse          +folding         -mouse_sysmouse  +textobjects
+byte_offset     -footer          +mouse_urxvt     +title
+cindent         +fork()          +mouse_xterm     -toolbar
-clipboard       +gettext         +multi_byte      +user_commands
+cmdline_compl   +iconv           +multi_lang      +vertsplit
+cmdline_hist    +insert_expand   +path_extra      +virtualedit
+cmdline_info    +jumplist        +persistent_undo +visual
+comments        +keymap          +postscript      +visualextra
+conceal         +langmap         +printer         +viminfo
+cscope          +libcall         +profile         +vreplace
+cursorbind      +linebreak       +quickfix        +wildignore
+cursorshape     +lispindent      +reltime         +wildmenu
+dialog_con      +listcmds        +rightleft       +windows
+digraphs        +localmap        +scrollbind      +writebackup
-dnd             +menu            +signs           -X11
-ebcdic          +mksession       +smartindent     -xfontset
-emacs_tags      +modify_fname    +startuptime     -xsmp
+eval            +mouse           +statusline      -xterm_clipboard
+ex_extra        -mouseshape      +syntax          
+extra_search    +mouse_dec       +tag_binary      
   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "$HOME/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by justinmk** [comment]
> clipboard: provider is not available

That's a different case than the one reported in this issue.

> It looks like the Neovim Ubuntu PPA package is compiled without xterm_clipboard

Please ignore the feature list, it's meaningless for Neovim. We will remove it.

**Comment by nfm** [comment]
Thanks for following up @justinmk. You're right, the `clipboard: provider is not available` is a different issue.

For reference, if anyone else comes across the `clipboard: provider is not available`, `:help nvim-clipboard` will point you in the right direction.

Sorting out my `clipboard: provider is not available` issue by installing xclip also solved the error YankRing was causing for me on launch. So this may not be a neovim issue at all, just a missing provider that the user needs to install.

Unless @cacplate has something to add this issue can probably be closed.

**Comment by kevinushey** [comment]
Just stumbled upon this.

Could `neovim` add something like this to the error message:

```
Please check ':help nvim-clipboard' for more information.
```

?

**Comment by justinmk** [comment]
Instead of spamming `See :help foo` in every single error message, we should assign an error number like `E42` so that users can do `:help E42`.

**Comment by justmytwospence** [comment]
what is the current state of this? using `set clipboard+=unnamedplus`, as per `:help neovim-clipboard` works for me yaking to the clipboard, but not pasting from the clipboard.

**Comment by clozed2u** [comment]
I have the same problem as @justmytwospence. yanking to the clipboard working find, but can not pasting from the clipboard.

**Comment by danielmanesku** [comment]
@clozed2u did you install xsel as `:help nvim-clipboard' suggests? After doing this and restarting nvim, + register started to work for me both ways.

**Comment by dnmario** [comment]
Dear Daniel Manesku,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] No command for the clipboard (#1696)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by Pyrohh** [comment]
@dnmario I've deleted your message. I don't know if you're a bot, but please stop.

**Comment by dnmario** [comment]
Dear Michael Reed,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] No command for the clipboard (#1696)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by clozed2u** [comment]
@danielmanesku Just reinstall neovim from HEAD and my problem has gone. Tested on OS X and latest version of Ubuntu.

**Comment by dnmario** [comment]
Dear Lattapon Yodsuwan,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] No command for the clipboard (#1696)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by ZyX-I** [comment]
@justinmk [I do not see](https://github.com/issues?utf8=%E2%9C%93&q=involves%3Adnmario+) (neither in [public activity](https://github.com/dnmario?tab=activity): used Python script to find any non-bot comments and failed) @dnmario done anything useful here. How about [blocking him](https://help.github.com/articles/blocking-a-user/)? This action can only be done by a project owner to make any sense (== prevent him from commenting here) according to the documentation.

Note that after blocking public activity can no longer be seen for some reason while you are logged in. Not makes much sense for me: logged out curl works just fine.

**Comment by justinmk** [comment]
@ZyX-I I did block him and so did @tarruda. Waiting for a reply from GH staff.

**Comment by HarishVangala** [comment]
Just for clarity:

**Problem:** Unable to use system clipboard via + register. Usually people use a command like "+yy

**Solution:** Simply install an application called `xclip`. Neovim implicitly takes care of it. You may have to restart neovim (`nvim`).

**Reasons:**  As taken from `:help clipboard` run from neovim commandline

> Nvim has no direct connection to the system clipboard. Instead it is
> accessible through a |provider| which transparently uses shell commands for
> communicating with the clipboard.
> 
> Clipboard access is implicitly enabled if any of the following clipboard tools
> are found in your `$PATH`.
> 
>   - xclip
>   - xsel (newer alternative to xclip)
>   - pbcopy/pbpaste (Mac OS X)
>   - lemonade (for SSH) https://github.com/pocke/lemonade
>   - doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/

As on 5 October, 2016 on Ubuntu 16.04LTS, neovim installed via ppa.

**Comment by raph-amiard** [comment]
This is terrible. I don't really care what mechanism your editor uses for clipboard communication. neovim is not a library, it's also a standalone text editor.

1. First the error message could be a lot better, and directly point me towards the help I need. If I need to google, your error reporting already failed.
2. The ppa should install xclip.

Sorry if I'm being cold, but we're talking here about a text editor that *cannot paste by default* on the major Linux distribution, and which will print an obscure error message when you try to do so.

**Comment by raph-amiard** [comment]
What would you think about "clipboard provider is not available - please read :help clipboard for more information" as an error message ?

**Comment by mhinz** [comment]
@raph-amiard 

1. https://github.com/neovim/neovim/pull/5812
2. We don't maintain PPA. Please report it to the maintainer.

**Comment by Stratovarius93** [comment]
I just installed xclip using: sudo pacman -S xclip
Good luck
