### ISSUE TITLE
Under nvim -e, mode(1) returns incorrect value

### ISSUE THREAD

**Issue by bk2204** [neovim/neovim#16981]
### Neovim version (nvim -v)

v0.6.1

### Vim (not Nvim) behaves the same?

no, Vim 8.2.3995

### Operating system/version

Debian unstable/amd64

### Terminal name/version

tmux 3.2a on mate-terminal

### $TERM environment variable

tmux-direct

### Installation

Debian repositories

### How to reproduce the issue

nvim -e
:echo mode(1)

### Expected behavior

The result should be `cv` (documented behavior) or `ce` (Vim's behavior).  In such a case, my configuration should disable loading the colorscheme, since a TTY might be missing.

### Actual behavior

The value is `n` (normal mode), but I am not in normal mode.  As a result, my colorscheme is loaded.

**Comment by zeertzjq** [comment]
Regression for #14311
