### ISSUE TITLE
ubuntu ppa amd64 build failed for impish (ubuntu 21.10)

### ISSUE THREAD

**Issue by csch0** [neovim/neovim#16999]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 21.10

### Terminal name/version

-

### $TERM environment variable

xterm-256color

### Installation

system package manager

### How to reproduce the issue

sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get install nvim

### Expected behavior

nvim 0.6.1 is installed

### Actual behavior

nvim 0.5.1 is installed

The amd64 faild: https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable/+builds?build_text=&build_state=all

The log can be seen here: https://launchpadlibrarian.net/578146613/buildlog_ubuntu-impish-amd64.neovim_0.6.1-3~bpo21.10.1~ppa1_BUILDING.txt.gz

**Comment by zeertzjq** [comment]
If build failed it cannot be tried again?

**Comment by jamessan** [comment]
The PPA isn't supported by the Nvim project.
