### ISSUE TITLE
Workspace diagnostics no longer work with `vim.diagostic`

### ISSUE THREAD

**Issue by urandom** [neovim/neovim#16994]
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

arch linux

### Terminal name/version

Arch linux

### $TERM environment variable

xterm-256color

### Installation

pacman -S community/neovim

### How to reproduce the issue

Invoking `lua  vim.lsp.diagnostic.set_loclist{ open_loclist = false, workspace = true }` no longer populates diagnostics from the whole workspace. Documentation for the new `vim.diagnostic` module says nothing about getting diagnostics from the whole workspace, and the `workspace` option doesn't appear to be used, even though the deprecated function is setting it.

Calling `vim.inspect(vim.diagnostic.get(0))` also does not produce the workspace diagnostics, or even just all buffer diagnostics.
### Expected behavior

The loclist to be populated with diagnostics from all files in the workspace

### Actual behavior

Only the current buffer's diagnostics are shown.

**Comment by gpanders** [comment]
>Calling vim.inspect(vim.diagnostic.get(0)) also does not produce the workspace diagnostics, or even just all buffer diagnostics.

Please refer to the documentation at `:h vim.diagnostic`. The docs for `vim.diagnostic.get()` state that the first argument is a buffer number, so `vim.diagnostic.get(0)` gives you diagnostics only from the current buffer. Use `vim.diagnostic.get()` to get all diagnostics.

`vim.diagnostic.setloclist()` shows diagnostics for the buffer in the current window. If you want to use *all* diagnostics, use `vim.diagnostic.setqflist()`. This is consistent with the pattern that location lists are window specific while quickfix lists are global. If you really want to have all diagnostics in the location list, you can do so yourself using a combination of `vim.diagnostic.get()` with `vim.fn.setloclist`.
