### ISSUE TITLE
Calling nvim_*_set_var with a Lua function segfaults nvim

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#16995]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+e92b81633

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 12.0.1

### Terminal name/version

Kitty 0.24.1

### $TERM environment variable

xterm-kitty

### Installation

brew install --head neovim

### How to reproduce the issue

nvim -u NONE -c 'lua vim.api.nvim_buf_set_var(0, "foo", function() end)'

`nvim_win_set_var` and `nvim_tabpage_set_var` behave similarly.

### Expected behavior

I was originally hoping I could stash Lua objects in there, which I assume is planned, but if not that, in the interim, an `error()`

### Actual behavior

Big boom.

**Comment by zeertzjq** [comment]
I think you mean SIGABRT?

**Comment by Julian** [comment]
I do, sorry.
