### ISSUE TITLE
Expose vimscript parser / interpreter

### ISSUE THREAD

**Issue by dbarnett** [neovim/neovim#170]
Up to now, no vimscript parser or interpreter existed outside of the vim editor itself. As a result, there has been no [syntax checker](https://github.com/scrooloose/syntastic/issues/154) for vimscript, no such thing as vimscript "unit tests" (i.e., for utility functions), and some other neat projects I'd like to build on top of a such vimscript tools are just not possible without hacking up an iffy re-implementation of vimscript.

With neovim's proposed modular architecture, it seems like it's finally possible to provide access to an AST for parsed vimscript and an interpreter for sending commands to a headless vim environment. Is that in the plan?

**Comment by elmart** [comment]
Closing, as it doesn't seem relevant anymore.

**Comment by justinmk** [comment]
Nvim has a Vimscript expression parser:

https://neovim.io/doc/user/api.html#nvim_parse_expression()
