### ISSUE TITLE
LSP Diagnostics sometimes not being cleared

### ISSUE THREAD

**Issue by bellini666** [neovim/neovim#17017]
### Neovim version (nvim -v)

v0.7.0-dev+861-g6ecaba510

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian Unstable

### Terminal name/version

GNOME Terminal 3.42.2 using VTE 0.66.2 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

Don't really know how to reproduce, it happens "ramdomly", but sometimes old LSP diagnostics will be kept on cache even after that was already solved.

Two examples here:
![Screenshot from 2022-01-09 16-48-30](https://user-images.githubusercontent.com/134025/148702965-b82c829e-2e9d-4792-9830-bd74a563e5f6.png)

![Screenshot from 2022-01-09 17-01-18](https://user-images.githubusercontent.com/134025/148702967-b9cd2569-1ddf-4695-bd0d-33c8e95966e1.png)

(in this second case, note what the error is saying. It thinks the string there is different from what really is)

In both cases the problem was already fixed, but the issue is still being displayed, no matter how many times I save or even change that line.

I tried inspecting `:lua print(vim.inspect(vim.diagnostic.get(0)))` and I can see that the diagnostics are still there in the cache. I even logged the `on_publish_diagnostics` and saw that the language server is really reporting those every time.

At first I thought it could be a problem with `pyright` specifically, but I saw that happening when editing my lua files too. Also, if I do a `:e`, the file gets parsed again and the issue goes away. The issue is also fixed if I delete the line and then insert it again (no need to save, just have to make it disappear and appear again)

That issue started happening some days ago (don't remember exactly when).

### Expected behavior

Described above.

### Actual behavior

Described above.

**Comment by mjlbach** [comment]
Check `LspInfo` and ensure only one copy of the language server is running on the buffer, Make sure you are using the minimal config, and not lsp-installer, or some other lsp plugin.

**Comment by bellini666** [comment]
@mjlbach I checked `LspInfo` and there was only one there. I'll try to find a minimal config, but like I said, the issue happens very randomly to me, don't really know how to "reproduce" it... Sometimes it will take 2 minutes to happen, sometimes 30 minutes.

Also, note that the problem doesn't seem to be on diagnostic. Like i said, what is being displayed is really what was sent by `pyright`. I have a custom `"textDocument/publishDiagnostics"` implementation (https://github.com/bellini666/dotfiles/blob/master/vim/lua/config/lsp.lua#L22) that I use to remove HINTS from diagnostics and then I call the original func. I added a log to that function and I can see that pyright is really sending those "non existing" issues every time. So, for it to think that the line still looks like that, either it is a problem with it (I don't think so, because I saw something similar with lua language server), or neovim is failing to send some buffer update to it..

**Comment by bellini666** [comment]
Hey @mjlbach , here is a video showing the issue.

https://user-images.githubusercontent.com/134025/148708473-4fbb4a6f-6d4c-4bd5-ad62-eb76e4407679.mp4

As you can see, the diagnostics is always changing, but for some reason it thinks there's an `u` at the end of that word, no matter how many times I delete and rewrite the line. What "fixes" the issue is when I make the line "don't exist anymore"  and make it "exist again" (with undo).

**Comment by mjlbach** [comment]
I need a minimum reproduction (the file that causes the issue reproduced with the minimal config) to do anything about this.

**Comment by bellini666** [comment]
@mjlbach the problem is that I can't create a minimum reproduction example... The same file with the same contents and the same change doesn't always produce the issue. I'm still trying to find a way to reproduce it and I'll for sure get back here if I find a way.

But having said that, I just discovered the reason of the issue! I defined `vim.lsp.set_log_level("debug")` and got it.

When the error happened here I deleted the character 74 and saw this on the log:
```
[DEBUG][2022-01-10 00:17:41] .../vim/lsp/rpc.lua:347	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 73,            line = 32          },          start = {            character = 73,            line = 32          }        },        rangeLength = 0,        text = ")"      } },    textDocument = {      uri = "file:///home/bellini/dev/strawberry-django-plus/strawberry_django_plus/types.py",      version = 1221    }  }}
```

As you can see there, neovim is reporting to the language server that I changed the character 73 and not 74. After I deleted and created the line again to fix the issue, doing the same reported the line 74 correctly.

I really don't know how to properly reproduce that (I'm trying). But maybe that can give a hint?

**Comment by fsouza** [comment]
Sounds like pyright is getting out of sync with neovim? Do you have any customizations around textDocument/didChange? Did this start recently? Perhaps you can try setting `debounce_text_changes` to 0 and see if that has any effect?

**Comment by mjlbach** [comment]
https://github.com/neovim/neovim/pull/17015/files may have fixed it, but I would be surprised as the scenario that PR addresses is extremely rare.

**Comment by bellini666** [comment]
@fsouza no I do not have any customizations with `textDocument/didChange`, only [this one](https://github.com/bellini666/dotfiles/blob/master/vim/lua/config/lsp.lua#L26) for filtering hints out of diagnostics.

@mjlbach tested it today and it seems to have fixed the issue for me for pyright. At least the pending change that never got flushed.

I'm still seeing diagnostics from old buffer version though. With debounce set to 0 I pratically don't see it with pyright, but it happens with null-ls a lot. The next change to the buffer now fixes it, but it is an annoying issue.

Also, don't know if that is related, but sometimes the buffer seems to "crash" and the `BufWritePre` autocmd doesn't get called. This also started happening at the same time of this issue, but I thought they were related. Now I see that their causes might be different.

More specifically, I have a `autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync(nil, 1500)` that gets registered as soon as any lsp client gets attached. As I'm editing a file, when that "crash" happens (don't know what causes it), saving the file doesn't trigger the formatting anymore. I can see that null-ls is still working because it is still giving flake8 diagnostics, but the formatting function never gets called. Even more strange, if I do `:lua vim.lsp.buf.formatting_sync(nil, 1500)` by hand it works, which means that the lsp is still working fine, it is just that the autocmd is not being called at all.

**Comment by mjlbach** [comment]
I don't see `update_in_insert=true` in your config. That might be it.

> Also, don't know if that is related, but sometimes the buffer seems to "crash" and the BufWritePre autocmd doesn't get called. This also started happening at the same time of this issue, but I thought they were related. Now I see that their causes might be different.

I'm not sure what crashing buffer means.

> I'm still seeing diagnostics from old buffer version though. With debounce set to 0 I pratically don't see it with pyright, but it happens with null-ls a lot. 

You can file an issue with null-ls, it's not a real language server and unsupported by neovim's built-in language server client as far as I'm concerned.

**Comment by fsouza** [comment]
@bellini666 perhaps check if the client isn't getting detached from the buffer (see https://neovim.discourse.group/t/prevent-detaching-lsp-clients/202). I think I ran into this issue last month during Advent of Code, but I haven't had a chance to revisit it since going back to work (guess who spends more time on Google Docs than neovim lol)

If you do run into that, it may be a good idea to continue the discussion on that discourse thread (unless you see a clear reproducer).

I did run into a bug with efm where it wouldn't send the empty list diagnostics when there were no problems (https://github.com/mattn/efm-langserver/issues/197), but I assume null-ls doesn't have that issue.

**Comment by bellini666** [comment]
> I don't see update_in_insert=true in your config. That might be it.

I can see that issue in normal mode. I even try to save the file and it wont go away. I have to really trigger a change to the buffer (any chage) to send the updated buffer to the clients when that happens.

> I'm not sure what crashing buffer means.

Don't know how to properly describe it, sorry :(. There aren't any errors at my infobar, there aren't any errors at the log, but the autocommand doesn't seem to be working. Any idea of what might cause the `autocmd BufWritePre <buffer>` to stop working from one time to another? Because the function that it calls, `lua vim.lsp.buf.formatting_sync(nil, 1500)`, if I call by hand it still works, so what seems to not be working is the autocmd.

Also, since I think it is very unlikely for the `BufWritePre` to have stopped working, as it is a core event, my guess was that something happened to the `<buffer>`. I didn't unregister it and neither have closed the buffer or nothing like that. So, what might have caused that?

> You can file an issue with null-ls, it's not a real language server and unsupported by neovim's built-in language server client as far as I'm concerned.

I can surely do that... But the reason I'm saying it here is because after reading this line of how null-ls works (https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/diagnostics.lua#L138), I think what might be happening is that the old version is being sent (or if the version is empty, the changetick hasn't updated yet?). Does that make any sense? If not, I'm reporting this to null-ls.

> @bellini666 perhaps check if the client isn't getting detached from the buffer (see https://neovim.discourse.group/t/prevent-detaching-lsp-clients/202). I think I ran into this issue last month during Advent of Code, but I haven't had a chance to revisit it since going back to work (guess who spends more time on Google Docs than neovim lol)

I actually checked every time and the clients are not detached (btw, cheers from a brazilian "irmão" here too :) )

> If you do run into that, it may be a good idea to continue the discussion on that discourse thread (unless you see a clear reproducer).

I'll take a look at that thread and check if it has anything to do with my issues. Thanks for pointing that out :)

**Comment by mjlbach** [comment]
> Don't know how to properly describe it, sorry :(. There aren't any errors at my infobar, there aren't any errors at the log, but the autocommand doesn't seem to be working. Any idea of what might cause the autocmd BufWritePre <buffer> to stop working from one time to another? Because the function that it calls, lua vim.lsp.buf.formatting_sync(nil, 1500), if I call by hand it still works, so what seems to not be working is the autocmd.

null-ls does weird things to inject itself as a language server, so I have no idea. I would file an issue with them. I strongly discourage plugins from pretending to be language servers.

**Comment by collindutter** [comment]
@bellini666 did you ever find a proper solution for this? I'm having the exact same behavior with pyright configured through lspconfig. It happens very randomly, and running `:e` or restarting the LSP fixes it.

**Comment by bellini666** [comment]
> @bellini666 did you ever find a proper solution for this? I'm having the exact same behavior with pyright configured through lspconfig. It happens very randomly, and running `:e` or restarting the LSP fixes it.

Unfortunately no. It happens randomly with pyright as well, although it has been less common to me lately. I'm running neovim from `HEAD` though

And yes, when that happens, usually a `:e` or `:LspRestart` fixes the issue
