### ISSUE TITLE
virt_lines overwrite foldtext on folded lines

### ISSUE THREAD

**Issue by cinghiopinghio** [neovim/neovim#17027]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

do not apply

### Operating system/version

linux (Archlinux)

### Terminal name/version

kitty 0.24.0

### $TERM environment variable

xterm-kitty

### Installation

pacman

### How to reproduce the issue
```
nvim --clean

:set fdm=indent
ifirst line
        indented line
        another indented line<Esc>
:lua vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace("vline"), 1, 0, { virt_lines={{{"Virt Line", "Comment"}}}, virt_lines_above=true })
za
```

### Expected behavior

the virtual line is not shown as referring to a folded text.
I can see the `foldtext`.

### Actual behavior

The `foldtext` is hidden by an empty virtual line.

This happens if the virtual line is `above` the first line of the folded text.
When `virt_lines_above=false` and the virtual line is `below` last line of the folded text, the virtual line is shown below the `foldtext` even when the text is folded (not sure is this the intended behaviour).

**Comment by zeertzjq** [comment]
I can confirm this bug. Your steps to reproduce don't seem to create a fold though.

**Comment by cinghiopinghio** [comment]
@zeertzjq : github removed front spaces. fixed now.

**Comment by zeertzjq** [comment]
https://github.com/neovim/neovim/blob/25eb7692d8e29cc83a70d74cbe1a8a1fae1f8ba2/src/nvim/diff.c#L1826-L1829

`diff_check()` calls `hasFoldingWin()` and returns immediately when in a fold, so something similar should need to be done for virtual lines, but I don't know whether it should be done in `win_line()` or `decor_virt_lines()`.

**Comment by zeertzjq** [comment]
Adding this check to `decor_virt_lines()` seems to solve the first bug, but not the second one.

**Comment by lewis6991** [comment]
I've got another repro for this issue. I've also found the cursor acts weirdly when navigating across lines.

```lua
-- a
-- fold title {{{

-- }}}

local ns = vim.api.nvim_create_namespace('test')

vim.api.nvim_buf_set_extmark(0, ns, 0, -1, {
  virt_lines = {
    {{'hello', 'Error'}},
    {{'hello', 'Error'}},
    {{'hello', 'Error'}}
  }
})
-- vim: set ft=text fdm=marker :
```

```
nvim test.lua
:source %
```
