### ISSUE TITLE
vim.keymap.set not found

### ISSUE THREAD

**Issue by alok** [neovim/neovim#17023]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+2338-g8f27c4a04 

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Macos monterey

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

built from source on homebrew

### How to reproduce the issue

I tried switching over to `vim.keymap.set` and got this:

```
Error detected while processing /Users/alokbeniwal/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/alokbeniwal/.config/nvim/init.lua:54: attempt to call field 'set' (a nil value)
```	

### Expected behavior

no error

### Actual behavior

the error above

**Comment by zeertzjq** [comment]
What does `:echo $VIMRUNTIME` print in Nvim?

**Comment by clason** [comment]
I cannot reproduce this. Make sure the installation actually succeeded (if you've built from source yourself at some point, you may need to `brew link neovim --overwrite`).

**Comment by alok** [comment]
`echo $VIMRUNTIME` gives `/usr/local/Cellar/neovim/HEAD-8f27c4a/share/nvim/runtime`, which is commit `8f27c4a0417c001fa2dedb6346673da501ea78e5`.

I ran brew link just in case and no change.

**Comment by clason** [comment]
Try building yourself from source; it seems there are problems with homebrew's LuaJIT2 build.

**Comment by lewis6991** [comment]
Is this still an issue?

**Comment by orangestara** [comment]
I have the same problem：
```
处理 /Users/daiyinlong/.config/nvim/init.lua 时发生错误:
E5113: Error while calling lua chunk: /Users/daiyinlong/.config/nvim/lua/core/keybinds.lua:4: attempt to index field 'keymap' (a nil value)
```

**Comment by dundargoc** [comment]
> I tried switching over to vim.keymap.set and got this

Do you have an actual code snippet we could try out?

**Comment by dundargoc** [comment]
@orangestara thanks for the example.

I tried it with neovim from homebrew using `brew install neovim --HEAD` but it works fine for me. This was on linux, so I'm not sure if that makes any difference.

**Comment by juniway** [comment]
@muniter 
When I executed, I get this error

```
ls: /usr/local/Cellar/neovim/HEAD-bdfea9d_1/share/nvim/runtime/lua/vim/keymap.lua: No such file or directory
```

my nvim version is:
```
NVIM v0.7.0-dev+719-gbdfea9d9a
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by juniway** [comment]
![image](https://user-images.githubusercontent.com/3980841/163755369-bd1c6999-440b-4167-834e-33d39e67e8df.png)

**Comment by clason** [comment]
This means your Neovim installation is broken. Remove Neovim (manually, if needed), then reinstall (with `--overwrite --force`, if needed).

**Comment by clason** [comment]
Now that Neovim 0.7 is released, you should just `brew install neovim`.

**Comment by juniway** [comment]
@clason I re-installed neovim, but the problems still exist.
<img width="680" alt="CleanShot 2022-04-19 at 14 11 18@2x" src="https://user-images.githubusercontent.com/3980841/163937598-07f87364-646a-4fd8-9c58-539656884525.png">

```
NVIM v0.8.0-dev+10-ge73ef5c09
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by zeertzjq** [comment]
> @clason I re-installed neovim, but the problems still exist when I do `:lua vim.keymap.set()` <img alt="CleanShot 2022-04-19 at 14 11 18@2x" width="680" src="https://user-images.githubusercontent.com/3980841/163937598-07f87364-646a-4fd8-9c58-539656884525.png">
> 
> ```
> NVIM v0.8.0-dev+10-ge73ef5c09
> Build type: Release
> LuaJIT 2.1.0-beta3
> ```

It is working as intended.

**Comment by juniway** [comment]
can you elaborate a little bit? my `Commment.nvim` does not work any more.

**Comment by zeertzjq** [comment]
> can you elaborate a little bit?

You must pass an argument to that function.

**Comment by juniway** [comment]
@zeertzjq Thanks, suddenly `Comment.nvim` works, and I checked that `/usr/local/Cellar/neovim/HEAD-e73ef5c/share/nvim/runtime/lua/vim/keymap.lua` is actually there after reinstall neovim.

**Comment by davidc360** [comment]
Hope this helps the next person:
I kept getting `keymap: no match`, but manually running `lua vim.keymap.set()` works and I verified that `keymap.lua` exists. 
Turns out changing the command from `vim.keymap.set` to `lua vim.keymap.set` makes it work.

**Comment by Lemanrp** [comment]
Can someone in the instructions advise people to try adding "lua" in case of weird issues like this? I spend a few hours not figuring out why knap wasn't working on my nixos system. Same issue as Davidc360 had above and solution worked for  me. thanks @davidc360
