### ISSUE TITLE
Handle @combined capture for language injections per match

### ISSUE THREAD

**Issue by MDeiml** [neovim/neovim#17039]
### Feature description

At the moment the `@combined` capture is handled per query, meaning that it does not behave as one may expect when used in more complex queries. For example with a query

```
[
  (node1) @lang @combined
  (node2) @lang
]
```

and a tree

```
(node1)
(node2)
(node1)
```

all nodes would be parsed combined.

It is not clear and not documented what should happen in this example so it is not really a bug. Also I don't know of a tree-sitter grammar that currently uses this kind of query. I still propose that nodes that have the `@combined` capture should get parsed together with previous node. This would mean that in the given example the first node is parsed by itself and the second and third regions are combined.

This implementation would enable queries for which only *some* of the matches should be combined. In particular this would be useful for https://github.com/nvim-treesitter/nvim-treesitter/issues/2212.

I'm also willing to implement this myself, but I wanted to ask before investing time since I've not yet contributed to neovim.

**Comment by clason** [comment]
Just to make clear: you are sure that this needs to be handled by Neovim, and not in the tree-sitter library itself?

**Comment by MDeiml** [comment]
Yes, I had a look at the code. It's handled by `LanguageTree:_get_injections` [here](https://github.com/neovim/neovim/blob/43b95b5430e85a81d4b7e78e98ae683ad04a89f8/runtime/lua/vim/treesitter/languagetree.lua#L303). Only the `combined` property of the first match actually gets used.

**Comment by theHamsta** [comment]
@MDeiml the implementation of @steelsojka was partially reverted because it was causing problems. We have to handle it properly here.

**Comment by tomtomjhj** [comment]
Should this be closed (or renamed)? It seems to be decided that `injection.combined` should be a per-pattern configuration that combines all the matches in the full document, and the use case discussed in this issue should be handled by proper handling of quantifiers (https://github.com/neovim/neovim/pull/24738).

**Comment by clason** [comment]
Indeed, closing as the injection handling has been changed significantly. We are also _much_ more strict about following upstream behavior instead of rolling our own.

If this is still an issue _and_ different from how tree-sitter documents/behaves in this situation, please open a new issue about it (which would be appreciated)!
