### ISSUE TITLE
Problem printing information to terminal with Term=dumb

### ISSUE THREAD

**Issue by kaddkaka** [neovim/neovim#17032]
### Neovim version (nvim -v)

NVIM v0.6.0

### Vim (not Nvim) behaves the same?

No, vim 8.2, Included patches: 1-3945

### Operating system/version

Description:    Ubuntu 18.04.6 LTS

### Terminal name/version

wezterm over ssh connection

### $TERM environment variable

screen-256color

### Installation

appimage

### How to reproduce the issue

I was trying to print the filetype of a file directly to terminal without seemingly starting vim/neovim. I got help at reddit: https://www.reddit.com/r/vim/comments/s0q6ve/is_it_possible_to_just_ask_vim_for_filetype/

However the command did not work out of the box with Neovim. To get output cmdheight has to be increased from default 1 to `2` for neovim.

### Expected behavior

These are outputs with vim (version `8.2 (2019 Dec 12, compiled Dec 30 2021 14:31:32)`)

```
> TERM=dumb vim -c"set cmdheight?" -cq -u NORC

  cmdheight=1
> TERM=dumb vim -e -c"set cmdheight?" -cq -u NORC
  cmdheight=1
> TERM=dumb vim -e banan -c"set cmdheight?" -cq -u NORC
"banan" [New File]
  cmdheight=1
```

### Actual behavior

The outputs with Neovim is just empty:
```
> TERM=dumb nvim -c"set cmdheight?" -cq -u NORC
> TERM=dumb nvim -e -c"set cmdheight?" -cq -u NORC
> TERM=dumb nvim -e banan -c"set cmdheight?" -cq -u NORC
```

If cmdheight is set to 2, the output is visible but still a bit different from the vim output:
```
> TERM=dumb nvim -c"set cmdheight=2" -c"set cmdheight?" -cq -u NORC

  cmdheight=2
> TERM=dumb nvim -e -c"set cmdheight=2" -c"set cmdheight?" -cq -u NORC

  cmdheight=2
> TERM=dumb nvim -e banan -c"set cmdheight=2" -c"set cmdheight?" -cq -u NORC

  cmdheight=2
  ```
  
I don't know if there is any need to be compatible with vim here, but it's certainly tricky to get any visible output with the current nvim behavior. I was just lucky to find that the `cmdheight` setting made a difference.

**Comment by zeertzjq** [comment]
Why not use `-Es`?

**Comment by kaddkaka** [comment]
> Why not use `-Es`?

Because I didn't know what it does. Is there any difference between `-e` and `-E`?

**Comment by zeertzjq** [comment]
I mean `-Es`.

**Comment by kaddkaka** [comment]
> I mean `-Es`, which in unrelated to `-E`. See `:h -Es`.

So the question becomes, what's the difference between `-es` and `-Es`, and the answer is how they handle stdin:

```
                -es reads/executes stdin as Ex commands.
                        printf "put ='foo'\n%%print\n" | nvim -es

                -Es reads stdin as text (into buffer 1).  Use -c or "+" to
                send commands.
                        printf "foo\n" | nvim -Es +"%print"
```

**Comment by kaddkaka** [comment]
Silent batch mode was the answer I got in the reddit thread as well. The working command becomes:

`nvim -es banana -c"set ft?" -cq -u ~/.config/nvim/init.vim`

`-u` is needed if the config modifies filetype detection.

**Comment by zeertzjq** [comment]
Just use `nvim -Es -c 'set ft?' foo.bar`

**Comment by kaddkaka** [comment]
> Just use `nvim -Es -c 'set ft?' foo.bar`

Did you try it? That leaves you in ex mode and also does not use your `init.vim` file which might be surprising.

Anyway, I found a way to do what I want. The difference in behavior with vim might still be seen as surprising, but not really an issue.

**Comment by zeertzjq** [comment]
I edited my comment before you replied, and it doesn't leave you in Ex mode.

**Comment by kaddkaka** [comment]
Right, `-es` leaves you with stdin prompt, `-Es` does not, my bad.

**Comment by kaddkaka** [comment]
For me it's fine to close this issue.
