### ISSUE TITLE
Startify cursor doesn't initialize correctly after launching any more

### ISSUE THREAD

**Issue by poetaman** [neovim/neovim#17033]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+863-g8f27c4a04

### Vim (not Nvim) behaves the same?

no, vim 8.2.4058

### Operating system/version

macOS 12.1

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

brew install nvim -s --HEAD

### How to reproduce the issue

```nvim -u test.vim```

test.vim:
```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath=&runtimepath
call plug#begin('~/.vim/plugged')
Plug 'mhinz/vim-startify'
call plug#end()
```

### Expected behavior

Cursor should land on 'e' shown below:

```
 |--------------------- on that 'e'
[e] <empty buffer>
```

### Actual behavior

It lands on the first character in the buffer.

**Comment by zeertzjq** [comment]
You set `packpath` to `~/.vim,~/.vim/after`, this still loads other plugins. For minimal steps to reproduce, you should only add the directory of `vim-startify` to `runtimepath`.

**Comment by reportaman** [comment]
@zeertzjq How do I ensure to load only one plugin. Btw, the problem does not happen if I load nvim with following setup. Perhaps its not a neovim problem then?

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/autoload
let &packpath=&runtimepath
call plug#begin('~/.vim/plugged')
Plug 'mhinz/vim-startify'
call plug#end()
```
