### ISSUE TITLE
nightly release occasionally left in draft state

### ISSUE THREAD

**Issue by surmish** [neovim/neovim#17047]
### Neovim version (nvim -v)

nigthly

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

NA

### Terminal name/version

NA

### $TERM environment variable

NA

### Installation

NA

### How to reproduce the issue

This link https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz does not exist anymore. Is this the plan going forward? Compiling neovim on work machines is a hassle since Lua/Luajit is a requirement. The built image was a solid solution for downloading nightly releases. Can these be restored?

### Expected behavior

NA

### Actual behavior

NA

**Comment by zeertzjq** [comment]
There seems to be something wrong with CI. Meanwhile, you can download [artifacts](https://github.com/neovim/neovim/actions/runs/1680918859).

**Comment by surmish** [comment]
Thanks, I was concerned if this was intentional.

**Comment by jamessan** [comment]
The release was created, but it was left in draft state for some reason.  We've seen this happen a few times.

I've filed an [issue](https://github.com/cli/cli/issues/5024) with gh.

**Comment by justinmk** [comment]
Haven't seen this in a long time.

**Comment by clason** [comment]
It did happen again a few weeks ago, although it does seem to have gotten rarer.

(You probably don't see it since I tend to notice it in the morning when nvim-treesitter CI fails a scheduled runand then publish it manually.)

**Comment by justinmk** [comment]
feel free to reopen then!

**Comment by jamessan** [comment]
The issue is being tracked upstream. It's not a problem we can resolve.  I think it's fine to leave this closed.
