### ISSUE TITLE
Add a Lua API for retrieving visible virtual text

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#17042]
### Feature already in Vim?

N/A

### Feature description

Consider a plugin which calls `vim.api.nvim_buf_set_extmark(... virt_text='foo')` somewhere within it. It likely will want to write tests which say "when I do XYZ, some virtual text saying "foo" becomes visible, and is aligned right in the buffer.

Today, it doesn't appear there is an easy way to express this test, because there is no Lua API to retrieve visible virtual text. (In particular, things like `nvim_buf_get_extmarks` retrieve only position information about an extmark).

In neovim's own test suite, it seems most of the tests of this sort use the internal test suite's helpers for rendering a fake screen (e.g. https://github.com/neovim/neovim/blob/ddf48193e6f86163a0ecae76bc4b802b07135acb/test/functional/ui/decorations_spec.lua#L146).

An API more like:

`vim.api.nvim_get_decorations(bufnr, start, end, opts)` which returns tables containing information about virtual text being displayed somewhere within the given range would be nice. (I am no expert in decorations, so the above may not be the right signature, or place to put it, but hopefully the idea is clear enough).

**Comment by gpanders** [comment]
It is possible to get the virtual text from existing extmarks. We do this in our test suite (e.g. in `diagnostic_spec.lua`):

https://github.com/neovim/neovim/blob/ffc8e91b5f49e7c89f995fde93b52ec2185cb505/test/functional/lua/diagnostic_spec.lua#L971-L989

The `virt_text` information is included in the return value of `nvim_buf_get_extmarks` if you include `{details=true}` in the `opts` argument.

**Comment by Julian** [comment]
Aha, indeed that likely looks perfect, somehow missed it. Thanks for the pointer!
