### ISSUE TITLE
BufWritePre suddenly stops being called when saving a file

### ISSUE THREAD

**Issue by bellini666** [neovim/neovim#17048]
### Neovim version (nvim -v)

v0.7.0-dev+872-g70fe3ce00

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian Unstable

### Terminal name/version

GNOME Terminal 3.42.2 using VTE 0.66.2 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

I have talked about this in https://github.com/neovim/neovim/issues/17017#issuecomment-1009460227 with @mjlbach but don't really know how to reproduce the issue, let me try to explain:

Sometimes for no reason at all, all of the sudden I notice that when saving a file, my autocmd `autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync(nil, 1500)` stopped working. My first though was that LSP did break, but calling `:vim.lsp.buf.formatting_sync(nil, 1500)` still works fine.

Suspecting that the autocmd was not working, I changed it to:
```lua
vim.cmd(string.format([[
  augroup __lsp_document_format
    autocmd!
    autocmd BufWritePre <buffer> lua require("autocmds").on_buf_write_pre(%s)
  augroup END
]], tostring(bufnr)))
```

And here is the function that it is calling:
```lua
M.on_buf_write_pre = function(bufnr)
    require('vim.lsp.log').info(string.format("BufWritePre: %s %s", tostring(bufnr)))
    vim.lsp.buf.formatting_sync(nil, 1500)
end
```

With that, I can see in the logs that everything is working fine (you can see my log in the first line)
```
[INFO][2022-01-11 20:42:16] ...lua/autocmds.lua:27	"BufWritePre: 593"
[DEBUG][2022-01-11 20:42:16] .../lua/vim/lsp.lua:993	"LSP[null-ls]"	"client.request"	2	"textDocument/formatting"	{  options = {    insertSpaces = true,    tabSize = 4  },  textDocument = {    uri = "file:///home/bellini/dev/veroo/backend/veroo/user/models.py"  }}	<function 1>	593
[DEBUG][2022-01-11 20:42:16] .../vim/lsp/rpc.lua:347	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///home/bellini/dev/veroo/backend/veroo/user/models.py"    }  }}
[DEBUG][2022-01-11 20:42:16] .../vim/lsp/rpc.lua:347	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///home/bellini/dev/veroo/backend/veroo/user/models.py"    }  }}
```

After the "crash" happened, when I save I can only see this at the logs:
```
[DEBUG][2022-01-11 20:40:53] .../vim/lsp/rpc.lua:347	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didSave",  params = {    textDocument = {      uri = "file:///home/bellini/dev/veroo/backend/veroo/user/models.py"    }  }}
```

So, the fact that my print is not appearing at the log shows that the event is not really being called.

As I said, it happens from time to time (sometimes it takes minutes, sometimes hours) and I have absolutely no idea of how to reproduce it. I know that in 6h session of work today I had it happening at least 4 times if I remember correctly. Just issuing a `:e` to reload the buffer fixes the issue. Maybe there's even more than that, but when that happens I don't see errors, I don't see anything at the logs, the only thing that makes me know that it happened is that my lsp formatting stopped working.

### Expected behavior

BufWritePre gets called for the buffer when it is about to be saved

### Actual behavior

BufWritePre stops getting called after some unknown events

**Comment by davidsierradz** [comment]
I'm seeing something similar, but when two (or more) servers are providing the formatting capability. 

For example, for lua files I have two lsp servers with formatting capabilities (null-ls configured with stylua, and sumneko_lua server) or for json files (null-ls configured with prettier, and jsonls), if the two servers have the formatting capability enabled, the autocommand `vim.cmd [[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()]]` doesn't work. 

If I run `:lua vim.lsp.buf.formatting_sync()` from the commandline then neovim ask me what server should I use and the formatting works as expected.

If I disable the formatting capability of sumneko_lua (and jsonls), with:
```
  if client.config.name == 'sumneko_lua' or client.config.name == 'jsonls' then
    client.resolved_capabilities.document_formatting = false
    client.resolved_capabilities.document_range_formatting = false
  end
```
Then the autocmd works again (I press `:w` and the buffer first get formatted before saving).

I guess is because when there is only one server that can format the current buffer, the `buf_formatting_sync` function doesn't halt until user interaction.

**Comment by mjlbach** [comment]
`vim.cmd [[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_seq_sync()]] `

**Comment by bellini666** [comment]
Just received a notification about this issue and notice that I forgot to update this... Its been a while since I did not see this happening anymore.

I'm using neovim from master and I update it everyday, so I don't know exactly when this was fixed, but considering that it was happening _a lot_ and I don't remember it happening at least for a month now, it should be safe to close this.

**Comment by airtonix** [comment]
vimnoob here 🤷🏻 found this link here which solved my problem: 

https://neovim.discourse.group/t/lsp-formatting-doesnt-always-work/1884/21
