### ISSUE TITLE
virt_lines don't move cursor if on the same line

### ISSUE THREAD

**Issue by Saecki** [neovim/neovim#17055]
### Neovim version (nvim -v)

NVIM v0.6.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.6.1/redhat-linux-build/config -I/builddir/build/BUILD/neovim-0.6.1/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.6.1/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.6.1/redhat-linux-build/include Compiled by mockbuild@koji  Features: +acl +iconv +tui

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Fedora 35

### Terminal name/version

kitty/tmux

### $TERM environment variable

tmux-256color

### Installation

system package manager

### How to reproduce the issue

- nvim --clean
- add some text (at least 2 lines)
- goto line 2
- execute following command:
    `lua vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace("foo"), 1, 0, { virt_lines_above = true, virt_lines = { { { "hi there", "NonText" } } } })`

### Expected behavior

The cursor is moved outside of the `virt_line` to stay at the position it was before.

### Actual behavior

The cursor stays at it's screen position and is at an invalid position on the `virt_line`.
Even moving horizontally keeps it on the `virt_line`

Edit: The nightly appimage behaves the same

**Comment by zeertzjq** [comment]
Fixed by #22706
