### ISSUE TITLE
nvim (>= 0.6) crashes at startup when built statically on Linux and macOS (regression)

### ISSUE THREAD

**Issue by Elv13** [neovim/neovim#17052]
### Neovim version (nvim -v)

git-master since 43956dea55a49a847a0f2e5d9e0f48384cb34635

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux x86_64, GCC 9.x, musl libc git-master ~~AND LLVM+macOS~~

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

https://github.com/Elv13/reclaimail/blob/master/docker-editorbuilder/Dockerfile

### How to reproduce the issue

**Self contained container to reproduce the issue:**

This will compile `nvim` statically

```sh
# Setup the build toolchain (this will take a long time)
git clone https://github.com/Elv13/reclaimail/
cd reclaimail/docker-editorbuilder/
git checkout 7b959d2347be1edd2015dc05945689be153d1cb0
docker build . -t static_nvim
docker run --rm --entrypoint /bin/bash -ti static_nvim

# Because `make install` wont work due to the Lua panic
export LUA_PATH="$LUA_PATH;/opt/lto-toolchain/x86_64-linux-musl/lib/lua/5.1/?.lua"
ln -s /neovim/runtime/lua/vim/ /opt/lto-toolchain/x86_64-linux-musl/lib/lua/5.1/

# Compile nvim
./build.sh

# Run `nvim`
/neovim/build/bin/nvim
```

**What is a static `nvim`:**

Static executable, or portable executables, don't link to system libraries at all. Every library is compiled into the final executable.

**Why on earth are you making your like so miserable?**

Ok, that might not be so obvious, so lets explain why building nvim statically is relevant/important. First of all, your official `.appimage` is 14mb (and 35mb for Windows!?!) and when built statically with LTO and dead code elimination, it is ~3.8mb. That alone is a good enough reason I guess. PGO could probably make it ever higher quality.

However, that's not the point here. The point is portability. `.appimage` built normally can only run on system with a newer version of glibc than the one it was built with. I deal with a lot of weird systems. Some are just plain old, some are just esoteric. I need a portable editor I can push when I ssh into a box. Static nvim are really universally portable. They work on all Linux and Linux compatible *nix.

The fact that it also embed my config, support cross compiling start 60% faster and run 25% faster are also nice bonuses.

### Expected behavior

Not crash on an `assert` on startup or when entering any command calling Lua directly or indirectly.

This was working last time I build nvim

### Actual behavior

```
PANIC: unprotected error in call to Lua API"
```

Crashes startup if a config file is present **OR**, if no config file is present, when entering any command, such as `:q`. ~~This happens because something calls into Lua without a `pcall` from C.~~ (edit: more debugging shows that this is not actually the real issue)

~~Apparently, this happens on macOS too https://github.com/Homebrew/homebrew-core/issues/91470 (edit: Note that they can fix it by upgrading LuaJIT, but not because it fixes the problem, just because it shuffles the code enough to win the race condition)~~

### Debugging

`git bisect` found:

```txt
commit 43956dea55a49a847a0f2e5d9e0f48384cb34635
Author: TJ DeVries <devries.timothyj@gmail.com>
Date:   Fri May 28 08:24:48 2021 -0700

    lua: Add vim.opt and fix scopes of vim.o (#13479)
    
    * lua: Add vim.opt
    
    * fixup: cleaning
    
    * fixup: comments
    
    * ty clason
    
    * fixup: comments
    
    * this is the last commit. period.
runtime/doc/lua.txt              | 186 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 runtime/lua/vim/F.lua            |   7 +++
 runtime/lua/vim/_meta.lua        | 631 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/nvim/api/vim.c               |   2 +-
 src/nvim/lua/vim.lua             | 246 +++++++++++++++++++++++------------------------------------------------------
 src/nvim/option.c                |   2 +-
 test/functional/lua/vim_spec.lua | 458 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 7 files changed, 1354 insertions(+), 178 deletions(-)

```

So, this is the commit which first added `lua` code at startup. To confirm this, I just have to replace the file content with nothing

```sh
root@5abd61d70e15:/neovim# mv /neovim/runtime/lua/vim/_meta.lua /neovim/runtime/lua/vim/_meta.old.lua
root@5abd61d70e15:/neovim# touch /neovim/runtime/lua/vim/_meta.lua
```

And yes, that obviously work. Now, time to debug. But now it makes no sense. Everytime I try to "just load" `_meta.lua`, it explodes. But as soon as I put a print in there, it works. So maybe there is a race condition and something isn't loaded yet when Lua starts?

Then it gets worst. If I `git checkout master` and try the same trick, then it crashes on startup again. Why? According to the `strings` command, `_meta.lua` is now bundled into the executable. So I recompiled. And now `vim.lua` is the one crashing.

Here's the command to `git bisect` in the container:

```sh
rm -rf /neovim/build/*; cd /neovim/build/; cmake ..     -DCMAKE_AR=$AR -DCMAKE_LINKER=$LD -DCMAKE_NM=$NM     -DLIBUV_LIBRARY=/libuv/build/libuv_a.a -DLIBUV_INCLUDE_DIR=/libuv/include/     -DMSGPACK_LIBRARY=/msgpack-c/build/libmsgpackc.a -DMSGPACK_INCLUDE_DIR=/opt/lto-toolchain/x86_64-linux-musl/include/     -DLIBLUV_LIBRARY=/luv/build/libluv_a.a -DLIBLUV_INCLUDE_DIR=/luv/src/     -DLUAJIT_LIBRARY=/LuaJIT/src/libluajit.a -DLUAJIT_INCLUDE_DIR=/LuaJIT/src     -DUNIBILIUM_LIBRARY=/unibilium/build/libunibilium.a -DUNIBILIUM_INCLUDE_DIR=/unibilium/     -DLIBTERMKEY_LIBRARY=/libtermkey/.libs/libtermkey.a -DLIBTERMKEY_INCLUDE_DIR=/libtermkey/     -DLIBVTERM_LIBRARY=/libvterm/.libs/libvterm.a -DLIBVTERM_INCLUDE_DIR=/libvterm/     -DLibIntl_INCLUDE_DIR=/opt/lto-toolchain/x86_64-linux-musl/include -DLibIntl_LIBRARY=/libuv/build/libuv_a.a     -DLUA_PRG=/LuaJIT/src/luajit -DCMAKE_INSTALL_PREFIX=/opt/neovim-static -DCMAKE_SYSROOT=$PREFIX && make -j16; cd /neovim/; /neovim/build/bin/nvim

# In vim
# :lua print("hello")
# :q

# git bisect <good/bad>
```

So, can any codebase/initialization expert clarify what's going on here? Static executable have much more room to re-order initialization. With all the `.so` things can only happen in a certain order. Now, it can happen in *any* order. 

So, with the clues from my little debugging session, it seems like `nvim` had race conditions during startup since a long time. However they had no side effects/crash until some Lua code was added to the startup sequence. Now `nvim` is stable when built dynamically because it always win the race due to `luajit` static initialization happens later. But with `LTO` anc static initialization, `luajit` starts earlier and the embedded code gets executed (?) sooner. Now `nvim` panic within `luajit` and the process quits.

Google searches seems to agree with this https://github.com/istio/istio/issues/13722 and https://github.com/envoyproxy/envoy/pull/6994 are good examples of other projects hitting the same type of bug. They disable sections, which also kills LTO to mitigate the problem. I tried the same workaround, and it works. Anyway, it's just swapping an undefined behavior for another in the hope it works better. The error is a symptom of the problem, not the problem. I acknowledge the real issue will be hard to track down and fix... I gave it a shot, but I am not familiar enough with the code.

The bug happens on macOS with LLVM and Linux with GCC according to the homebrew link above. It happens with the `master` and `v2.1` branch of LuaJIT. LuaJIT itself support sections and LTO. I use it elsewhere.

(Please note that this container also breaks translations. That's my fault. I could fix it if anyone else is interested in a static `nvim`.)

**Comment by clason** [comment]
I'm not sure the Homebrew link is related; that was due to precompiling the embedded Lua files during build, which needed adaptations to the changed build process. Embedding the files verbatim worked fine.

**Comment by Elv13** [comment]
You may be correct (btw/offtopic, it might be worth minifiying those embedded files, put them in an ELF section and not install the duplicates when doing `make install`, that will save ~1mb. Embedded systems have small disk, so I care :P ).

This whole class of issue is very fragile. From the other `PANIC: unprotected error in call to Lua API (7)` links from Google, I see a lot of randomness in the fixes. From random code changes, `sleep()`, reverting commits and build systems changes. `-fno-function-sections` is the most reliable "fix". But my guts tell me none of actually 100% guaranteed to fix anything. Static initialization in C and C++ is nasty (with C++ being 1000x worst). LTO (link time optimization / dead code elimination) is a nightmare to debug (having done my fair share of debugging since I just enabled it in Gentoo when GCC 4.8 was releases). With Fedora and RHEL now starting to enable it by default, people are finally starting to fix the bugs. But since Fedora still enforces `.so` everywhere, their `nvim` cannot be affected by this. Still, I think it's worth fixing. If only because maybe you can consider adopting my code to build a smaller and more portable AppImage.

**Comment by clason** [comment]
> (btw/offtopic, it might be worth minifiying those embedded files, put them in an ELF section and not install the duplicates when doing make install, that will save ~1mb. Embedded systems have small disk, so I care :P ).

By default, these files are embedded as compiled bytecode; I'm not sure how more mini you can get...

And as a general note, `PANIC: unprotected error in call to Lua API (7)` is the equivalent of a segfault, so of course the fixes vary wildly, because the causes can be very different. I'm certain they're not all related to what you're dealing with.

**Comment by Elv13** [comment]
> By default, these files are embedded as compiled bytecode; 

Weird, maybe I am missing a compile option. I see them as raw Lua when calling `strings` on the executable.

/offtopic

**Comment by clason** [comment]
Yes, the compilation is only enabled for release builds, on platforms where this is known to work.

**Comment by zeertzjq** [comment]
The compilation was also only added about a month ago, so if you are building v0.6.0 then there won't be compilation.

**Comment by Elv13** [comment]
(still offtopic)

Thanks. The problem was that the `jit` LuaJIT module wasn't in `LUA_PATH`. I fixed it https://github.com/Elv13/reclaimail/commit/01db67ce24592da225025d85ec35ef86b8dd5e81 here. Now the appimage is 4636kb instead of 4756kb! Still sad it's no longer 100% LTOed with the LuaJIT compile hack. Still better than the 14mb of the official AppImage. Strangely, adding `-DCMAKE_BUILD_TYPE=Release` actually adds > 200kb over a stripped debug build...

**Comment by clason** [comment]
Then it _was_ in fact the same problem as with Homebrew -- apologies!

**Comment by justinmk** [comment]
Glancing at the comments it seems like this was resolved?

**Comment by Elv13** [comment]
No, what was resolved is a different thing. While I didn't test in a few weeks, that was still a problem. Please re-open

**Comment by justinmk** [comment]
still happening on latest master ?
