### ISSUE TITLE
Error detected while processing function UltiSnips#CursorMoved

### ISSUE THREAD

**Issue by askobara** [neovim/neovim#1705]
Hello!
I observe strange behaviour of Unite and Ultisnips in my workflow.
When I try to open Unite buffer (file_rec/async, for example) and I have not finished snippet 
```
// stopped at first placeholder, but have two or more
if (|) {
    ${2:next_placeholder}
}
```
I get this error 
```viml
Error detected while processing function UltiSnips#CursorMoved:
line    1:
E31: No such mapping
```
As result I can't move between opened windows and all I can do is ```:qa!```

neovim version is 951d00a
python plugin is updated
opensuse 13.2
[nvimrc gist](https://gist.github.com/askobara/b4f06fb68043f884a15e)

**Comment by Pyrohh** [comment]
Since this doesn't look necessarily related to Neovim (and because significant work has been done since this was filed), I'll close this. Please feel free to reopen if you think I'm wrong in doing so.
