### ISSUE TITLE
Treesitter queries using `+` quantifiers do not work as expected

### ISSUE THREAD

**Issue by MDeiml** [neovim/neovim#17060]
### Neovim version (nvim -v)

0.7.0-dev

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 20.04

### Terminal name/version

Konsole 19.12.3

### $TERM environment variable

xterm-256color

### Installation

apt

### How to reproduce the issue

* run nvim with nvim-treesitter and nvim-treesitter-playground
* `:set filetype=c`
* `:TSPlaygroundToggle`
* insert
  ```c
  #define FOO
  #define BAR
  ```
* Press o (open query editor)
* enter `(preproc_def)+ @test`
* hover over `@test` to highlight query results

### Expected behavior

Both `preproc_def` nodes get highlighted

### Actual behavior

Only the last `preproc_def`node is highlighted

**Comment by MDeiml** [comment]
This is not specific to the C grammar.

**Comment by MDeiml** [comment]
I also verified that this is not a problem with tree-sitter. I should still verify that this is a problem with neovim and not nvim-treesitter-playground

**Comment by MDeiml** [comment]
Ok, using this code
```lua
local bufnr = 0
local parser = vim.treesitter.get_parser(bufnr, "c")
local tree = parser:parse()[1]
local root = tree:root()
local lang = vim.treesitter.inspect_language("c")
local query = vim.treesitter.parse_query("c", "(preproc_def)+ @test")
for pattern, match in query:iter_matches(tree:root(), 0) do
    for cid, node in pairs(match) do
        print(node:type(), node:range())
    end
end
```
(replace the value of `bufnr` with the bufnr of something containing
```c
#define FOO
#define BAR
```
)
I could verify that this is indeed a problem with neovim.

**Comment by MDeiml** [comment]
This is actually a problem with the API of `Query:iter_matches`. It returns a table a table `match` which has the capture id (`cid` in the lua code above) as its keys and the nodes as its values. But there could be multiple nodes for the same capture id, as for example if you use quantifiers in a query.

I don't think that there is a backwards compatible way to resolve this. I would propose making `match` a list of `{cid, node}` pairs.

**Comment by gpanders** [comment]
Fixed by https://github.com/neovim/neovim/pull/24738.
