### ISSUE TITLE
garbled characters when pasting unicode with non-US locale

### ISSUE THREAD

**Issue by yamatsum** [neovim/neovim#17062]
### Neovim version (nvim -v)

0.7.0-dev+b43575545

### Vim (not Nvim) behaves the same?

no, 8.2.3489

### Operating system/version

macOS 12.1

### Terminal name/version

iTerm 3.4.14

### $TERM environment variable

screen-256color

### Installation

homebrew

### How to reproduce the issue

``` 
あいう
```

If I copy the above text with `yy` and then paste it with `p`, it pastes correctly, 
but if I paste it with `command+v` ( `vim.o.clipboard = "unnamedplus"` is already set ), I get the following

```
"ÅÇ "ÅÑ "ÅÜ 
```

I've set the following as a workaround, but I'd like to be able to do without it 
```
vim.cmd("lan en_US.UTF-8") 
````

### Expected behavior

It can be pasted as follows
```
あいう
```

### Actual behavior

```
"ÅÇ "ÅÑ "ÅÜ 
```

**Comment by clason** [comment]
works for me. make sure you have set your locale correctly (you _must_ specify an encoding, so something like `en_US` is not enough, it has to be `en_US.UTF-8`).

**Comment by clason** [comment]
> I've set the following as a workaround, but I'd like to be able to do without it

Sorry, just saw that. I don't think you can do without if your terminal's locale is not properly set up.

**Comment by yamatsum** [comment]
@clason Thanks foy reply.
Vim and past versions of neovim behave correctly. What's the difference?

**Comment by clason** [comment]
If previous versions behave differently, can you bisect when it stopped working? I suspect it's due to a change in one of our dependencies (libvterm, libuv, etc.) that got stricter about locales (encodings used to be optional; now something like `en_US` without the `.UTF-8` is no longer a valid locale).

**Comment by yamatsum** [comment]
@clason 
It's a very old version, but I've confirmed that it works fine with 0.2.2 and is garbled with 0.3.8

**Comment by justinmk** [comment]
Works for me with NVIM v0.11.0-dev-840 f2fa4ca97ea3 . But I'm using en_US.UTF-8" locale which was mentioned as a workaround.

What is the locale that reproduces the issue? Can you try the [latest development version](https://github.com/neovim/neovim/releases/tag/nightly).
