### ISSUE TITLE
TUI: in tmux, background color is not detected

### ISSUE THREAD

**Issue by JonRowe** [neovim/neovim#17070]
### Neovim version (nvim -v)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@HMBRW-A-001-M1-004.local

### Vim (not Nvim) behaves the same?

No, VIM 8.2 (1-3800 Compiled by Homebrew)

### Operating system/version

macOS 12.1

### Terminal name/version

iTerm Build 3.5.0beta4

### $TERM environment variable

screen-256color

### Installation

homebrew

### How to reproduce the issue

tmux attach
nvim --clean
:echo &background

### Expected behavior

I expect the background to be picked up from the OS, regardless of running in tmux or not e.g. I expect this output:

Vim (outside tmux): light
Vim (inside tmux): light
NeoVim (outside tmux): light
NeoVim (inside tmux): light

### Actual behavior

However inside tmux, only neovim returns the "wrong" value.

Vim (outside tmux): light
Vim (inside tmux): light
NeoVim (outside tmux): light
NeoVim (inside tmux): dark

**Comment by JonRowe** [comment]
Thanks for the great project and all the hardwork, I'm a recent upgrade from a long time vim setup. I use solarised in light mode and initially I thought this was a 256 colour / theme issue. After fixing the 256 colour setup I was left with strange border colours only in my theme, some manual investigation then found that background was being detected incorrectly. I'm working around this by forcing it to light, but thought I'd raise the issue as I couldn't find any similar reports. Have a great day.

**Comment by haolian9** [comment]
what's the color scheme you using exactly? i use nvim inside tmux always and never found this ...

**Comment by JonRowe** [comment]
@haolian9 solarized light,but as I say its the background setting which would affect all colourschemes

**Comment by fsouza** [comment]
@JonRowe I'm confused. MacVim is a UI, it shouldn't interact with tmux 🤔 I don't know much about MacVim though.

Does `vim` detect the background correctly?

**Comment by JonRowe** [comment]
@fsouza Sorry I was mistaken, its just vim installed via brew. I used to run macvim from the terminal but apparently on this machine I skipped it and went straight to regular vim compiled via homebrew.

**Comment by erw7** [comment]
The reason the background auto-detection that works in vim does not work in neovim is because neovim does not have `t_RB`. As a workaround, the following settings in `init.lua` should work with any luck.

```lua
vim.loop.fs_write(2, "\27Ptmux;\27\27]11;?\7\27\\", -1, nil)
```

**Comment by even4void** [comment]
@erw7's trick was working fine for me until I upgraded to Tmux 3.2a (Ubuntu 22.04 LTS). I tried updating various settings from my Tmux config file (including `features` and/or `overrides` of `Tc`/`RGB` options), but apparently my Neovim custom colorscheme is stucked with this newer version of Tmux. If I manually `set background=light`, it works as expected, but I would prefer to keep the automatic background detection option since I rely on it to set my nvim colorscheme and various other option in my terminal (Alacritty, FWIW). Any workaround?

**Comment by ctrl2wei** [comment]
@even4void maybe try put this in .tmux.conf

> set-option -g allow-passthrough on

**Comment by even4void** [comment]
@ctrl2wei Thanks! I think this only applies to [v3.3](https://stackoverflow.com/a/74922390), though.

**Comment by sixtusagbo** [comment]
@erw7's workaround didn't work for me. This worked: https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6

**Comment by JohnStarich** [comment]
FWIW I can reproduce on Fedora Linux inside tmux. I can confirm @erw7's work-around works! I required tmux's `set-option -g allow-passthrough on` as well (on tmux 3.3a).

Is this something that'd be reasonable to improve in neovim's default background detection? I can't seem to find an option within tmux to allow normal (unmodified) escape sequences to pass through unimpeded.

**Comment by gonstoll** [comment]
@erw7's and @ctrl2wei's suggestions actually work to some extend. Some colors are still off, like float background, lazy loaded plugins, and more.

**Comment by gpanders** [comment]
See https://github.com/neovim/neovim/pull/26557. tmux 3.3a and earlier require `allow-passthrough` to be set. This will not be necessary whenever a new tmux version is released, since tmux [natively responds to OSC 11 queries now](https://github.com/tmux/tmux/commit/a41a92744188ec5c8a8d4ddc100ec15b52d04603).

**Comment by gonstoll** [comment]
This is what I mean by some colors still being off:

<img width="1470" alt="Screenshot 2023-12-16 at 01 11 18" src="https://github.com/neovim/neovim/assets/25900010/f7fc1901-9094-4808-9d65-bf8d6b0d0241">

<img width="1470" alt="Screenshot 2023-12-16 at 01 10 54" src="https://github.com/neovim/neovim/assets/25900010/db5b6f67-5dd8-4754-9573-30c04440e420">

**Comment by QuentinClyy** [comment]
I don't know if this can help, I have been trying to fix this for days. Setting this in my `tmux.conf` fixed the background for me

```
set-option -sa terminal-overrides ",xterm*:Tc"
```
