### ISSUE TITLE
`vim.lsp.buf.formatting_seq_sync()` throws error `offset_encoding: expected string, got nil`

### ISSUE THREAD

**Issue by kunish** [neovim/neovim#17074]
### Neovim version (nvim -v)

v0.7.0-dev+881-g4570df0b4

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.2

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

```shell
nvim

:lua vim.lsp.buf.formatting_seq_sync()
```

### Expected behavior

Format buffer correctly

### Actual behavior

Throws error:

`offset_encoding: expected string, got nil`

**Comment by mjlbach** [comment]
It will be fixed for most language servers by https://github.com/neovim/neovim/pull/17075, if the bug still persists for null-ls with that PR then it is a bug in null-ls.

**Comment by kunish** [comment]
Yes, that makes sense. Just leave this issue here as a note for plugin maintainers.

**Comment by gbrlsnchs** [comment]
I still see this when using `vim.lsp.buf.rename()` with `rust-analyzer` (didn't test with other servers). Does the mentioned PR fixes that as well or am I doing something wrong?

**Comment by mjlbach** [comment]
it's fixed

**Comment by gbrlsnchs** [comment]
You rock @mjlbach!
