### ISSUE TITLE
List breaks %v in the statusline

### ISSUE THREAD

**Issue by SoheilElahi** [neovim/neovim#17071]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

I haven't tested :(

### Operating system/version

windows 10

### Terminal name/version

Alacritty 0.9

### $TERM environment variable

Alacritty

### Installation

Downloaded the zip file from release page and ran nvim.exe

### How to reproduce the issue

```
set virtualedit=all
set laststatus=2
set statusline=\ %t\ %m\ %r%=%p%%\ \ col:%-3.v\ %Y\ 
set list
```

### Expected behavior

Hello everyone
Well as the guide says %v is supposed to show the visual column number in the statusline. But when I `set list` then it somehow doesn't work as expected and after turning list off with `set nolist` the issue disappears

### Actual behavior

%v is somehow working the same as %c when `list` is on

**Comment by zeertzjq** [comment]
This bug only happen when `'listchars'` contains eol. You should mention this in steps to reproduce. This bug is also reproducible in Vim.

**Comment by SoheilElahi** [comment]
> This bug only happens when `'listchars'` contains eol. You should mention this in steps to reproduce.

ok
my `'lcs'` is only containing `trail` but the bug is still there
so how could I remove `eol` from `'lcs'`?

**Comment by zeertzjq** [comment]
Oh wait, I was wrong. This is interesting.

**Comment by zeertzjq** [comment]
Oh, this bug only happens when `'listchars'` doesn't contain `tab`.
