### ISSUE TITLE
move command does not behave as vim

### ISSUE THREAD

**Issue by zenobht** [neovim/neovim#17088]
### Neovim version (nvim -v)

v0.7.0-dev+f92a2457c

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos 12.1

### Terminal name/version

kitty 0.24.1

### $TERM environment variable

xterm-kitty

### Installation

brew install neovim --HEAD

### How to reproduce the issue

in init.lua
```
local set = vim.keymap.set
local sil = { silent = true }
 
set({'n'}, '<C-j>', ":m .+1<CR>==<CR>", sil)
set({'n'}, '<C-k>', ":m .-2<CR>==<CR>", sil)
set({'v'}, '<C-j>', ":m '>+1<CR>gv=gv<CR>", sil)
set({'v'}, '<C-k>', ":m '<-2<CR>gv=gv<CR>", sil)
```

![Untitled](https://user-images.githubusercontent.com/6837979/149498892-0fbf0d20-4e31-494e-a10c-2ba6e8448a0b.gif)

Ref: https://vim.fandom.com/wiki/Moving_lines_up_or_down

#### Normal Mode
 
It should move just one line

#### Visual mode

It should move the selected lines and reselect the previous selection

#### Normal Mode
 
It should move just one line but moves 2 lines

#### Visual mode

It moves and reselects the previous selection but it add the next line to selection as well.

**Comment by zeertzjq** [comment]
Which Vim version did you check? Vim 8.2.3890 seems to behaves the same.

**Comment by zeertzjq** [comment]
You have an extra carriage return at the end of your mappngs.
