### ISSUE TITLE
The highlight "MsgArea" hl_group is misbehaving when used with the Lua API

### ISSUE THREAD

**Issue by Elv13** [neovim/neovim#17089]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

From source

### How to reproduce the issue

Call

Bug 1: It doesn't work if called too early

```
vim.api.nvim_command("hi MsgArea ctermbg=236 ctermfg=230")
```

before `colorsheme` and it does nothing. Call it after (or in `vim.scheduled_wrap`) and it works.

Bug 2:

Calling `vim.api.nvim_set_hl(NS, "MsgArea", { ctermbg = "white" })` explodes. Or if done later using `:lua vim.api.nvim_set_hl(1, "MsgArea", { ctermbg = "white" })`, does nothing.

If you manually call `vim.api.nvim_command("hi MsgArea ctermbg=236 ctermfg=230")`, *then* **in another event loop iteration** call `set_hl`, then,  it starts to work correctly.

### Expected behavior

Work just like every other color groups. Not have to call `:hl MsgArea` before the Lua API starts working. 

### Actual behavior

For "bug 1", it does nothing unless the call is placed after the colorsheme is loaded. Other `hl` groups don't behave like this.

For "bug 2":

It explodes when calling `nvim_set_hl`.

```txt
E5108: Error executing lua highlight.lua:61:                   
Expected lua string                                                                                 
stack traceback:                                                                                    
         [C]: in function 'nvim_set_hl'                                                 
```

Calling any other color take a table with `ctermbg`, `bold`, `foreground`, etc. This group, for some reason, think it needs a string. Passing it a string also explodes.

### Workaround

```lua
local set_hl_ns = vim.api.nvim__set_hl_ns or vim.api.nvim_set_hl_ns
local namespace = vim.api.nvim_create_namespace("hl")

-- The delay mitigates a bug.
-- https://github.com/neovim/neovim/issues/17089
vim.schedule_wrap(function()
    vim.api.nvim_command("hi MsgArea ctermbg=None ctermfg=None")

    vim.schedule(function()
        pcall(function()
            vim.api.nvim_set_hl(namespace, name, {
                ctermbg = 236,
                ctermfg = 230
            })
            set_hl_ns(namespace)
        end)
    end)
end)

```

edit: mitigation in my config https://github.com/Elv13/reclaimail/commit/223b7595b3ce2df364ac8b058b489280f1e3a27f#diff-bdc56ba78f46e5c354431ef45a14094b952fb6765a827b27f922c8db42328221R1

**Comment by glepnir** [comment]
bug 1 duplicate https://github.com/neovim/neovim/issues/17832

**Comment by justinmk** [comment]
> Bug 1: It doesn't work if called too early

This works on Nvim 0.11 c1378413c142e1762b80132c41b10c16c4aa7c13 :

    nvim --cmd 'set notermguicolors' --cmd 'lua vim.api.nvim_command("hi MsgArea ctermbg=236 ctermfg=230")'



> Bug 2:
> 
> Calling `vim.api.nvim_set_hl(NS, "MsgArea", { ctermbg = "white" })` explodes. Or if done later using `:lua vim.api.nvim_set_hl(1, "MsgArea", { ctermbg = "white" })`, does nothing.

This works (ns=0):

    nvim --cmd 'set notermguicolors' --cmd 'lua vim.api.nvim_set_hl(0, "MsgArea", { ctermbg = "white" })'
