### ISSUE TITLE
The Tab-Completion for cmdline mode, i.e. `:`, seems to be broken

### ISSUE THREAD

**Issue by nyngwang** [neovim/neovim#17098]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+890-g574a58220

### Vim (not Nvim) behaves the same?

no, i don't use vim anymore

### Operating system/version

macOS 11.6.2

### Terminal name/version

alacritty 0.9.0 (fed349a)

### $TERM environment variable

alacritty

### Installation

compile on master

### How to reproduce the issue

TL;DR: I cannot use tab-completion in `:`-mode anymore.

Inside `:`, just type some plugin-define keyword (prefix) and try to use `<Tab>` (or whatsoever you define for completion) to finish the keyword.

### Expected behavior

can tab-completion in `:`-mode.

### Actual behavior

can't

**Comment by clason** [comment]
Can't reproduce, sorry (latest master on macOS). You need to be more specific (please give _exact_ reproducing steps, and make sure to test with `--clean` and a minimal config).

**Comment by zeertzjq** [comment]
> just type some plugin-define keyword (prefix)

Were you completing a command or an argument of a command?

**Comment by nyngwang** [comment]
> 

A command.

**Comment by nyngwang** [comment]
I just re-installed everything, and it still exists.

**Comment by clason** [comment]
Still, we can't help you without being able to reproduce the exact situation you see the wrong behavior in.

**Comment by nyngwang** [comment]
@clason: the word is indeed get completed but never shown. I have something like `:^I` and hit enter the "invisible" command did get triggered.

**Comment by zeertzjq** [comment]
Can you provide a screenshot or screen recording perhaps?

**Comment by clason** [comment]
We _need_ your `init.vim` config (please try to make it minimal before sharing here).

**Comment by nyngwang** [comment]
https://user-images.githubusercontent.com/24765272/149619679-589aa65d-e1b3-40ff-a91f-1a3c44f009b7.mov

**Comment by nyngwang** [comment]
Wait, I think it may be a plugin issue. I have tested so many old commits, and this bug happens in all cases.

**Comment by hrsh7th** [comment]
I think this is nvim-cmp's problem. (and I've fixed it). Sorry for annoying...

**Comment by nyngwang** [comment]
@hrsh7th: no worries. I love your plugin(s)! I just saw this comment right after I open the issue :(

**Comment by hrsh7th** [comment]
I think we should use `nvim -u NONE` when reporting the issue to the nvim core.

BTW, This problem caused by `vim.api.nvim_set_keymap(..., { silent = true })` for the cmdline.
I think it's very strange but I guess it's vim itself's issue.

**Comment by zeertzjq** [comment]
That's how `<silent>` is documented to behave:
```
						*:map-<silent>* *:map-silent*
To define a mapping which will not be echoed on the command line, add
"<silent>" as the first argument.  Example: >
	:map <silent> ,h /Header<CR>
The search string will not be echoed when using this mapping.  Messages from
the executed command are still given though.  To shut them up too, add a
":silent" in the executed command: >
	:map <silent> ,h :exe ":silent normal /Header\r"<CR>
Prompts will still be given, e.g., for inputdialog().
Using "<silent>" for an abbreviation is possible, but will cause redrawing of
the command line to fail.
```

**Comment by clason** [comment]
> I think we should use nvim -u NONE when reporting the issue to the nvim core.

The issue template already requests testing with `nvim --clean` (which uses "factory defaults", i.e., still loads the bundled plugins but only those).

**Comment by nyngwang** [comment]
@clason: Sorry for my rudeness. I will follow it the next time.
