### ISSUE TITLE
API: add lua-only attribute to nvim_get_api_info

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#17116]
nvim_get_api_info sends the following data:
```json
{
  "since": 7,
  "parameters": [
    [
      "Buffer",
      "buffer"
    ],
    [
      "LuaRef",
      "fun"
    ]
  ],
  "return_type": "Object",
  "method": true,
  "name": "nvim_buf_call"
},
```
It would be nice if this function was marked as lua-only, so that RPC client generators could ignore it.

**Comment by clason** [comment]
In general, the scope (lua-only, remote-only, ...) should be exposed more widely (also to docs, in particular).

**Comment by glacambre** [comment]
In #17116, it sounds like the goal is to eventually make all of the Lua API available to RPC clients, so this issue can probably be closed.
