### ISSUE TITLE
Opening references doesn't work with the NERDTree

### ISSUE THREAD

**Issue by mrded** [neovim/neovim#17123]
### Neovim version (nvim -v)

v0.6.0

### Language server name/version

typescript-language-server 0.9.3, gopls 0.0.1-security.5

### Operating system/version

macOS 12.1 (21C52)

### Steps to reproduce using "nvim -u minimal_init.lua"

- Install `Plug 'scrooloose/nerdtree', { 'tag': '6.10.11' }`.
- Select a function which is used elsewhere
- Call `<cmd>lua vim.lsp.buf.references()<CR>`
- Select a references

### Expected behavior

Open up the reference in the current buffer.

### Actual behavior

The error is shown: 
```
NERDTree: no file for the current buffer
```

![image](https://user-images.githubusercontent.com/347098/149804430-75a761d2-1b66-4ae1-b88d-a69187dfb2b9.png)

**Comment by mjlbach** [comment]
This is a plugin issue, please file the bug report with them.

**Comment by mrded** [comment]
https://github.com/preservim/nerdtree/issues/1291
