### ISSUE TITLE
Cursorline unexpectedly turns off after current buffer in window is switched

### ISSUE THREAD

**Issue by imcaizheng** [neovim/neovim#17120]
### Neovim version (nvim -v)

v0.7.0-dev+896-g7085e5b0c

### Vim (not Nvim) behaves the same?

idk

### Operating system/version

5.10.70-1-MANJARO

### Terminal name/version

xfce4-terminal

### $TERM environment variable

xterm-256color

### Installation

AUR

### How to reproduce the issue

echo test_01 > /tmp/test_01.txt
echo test_02 > /tmp/test_02.txt
echo test_03 > /tmp/test_03.txt
nvim --clean /tmp/test_01.txt /tmp/test_02.txt /tmp/test_03.txt

:buffer 2
:set cursorline
:buffer 3
:buffer 1

### Expected behavior

Buffer `#2` has cursorline.
Buffer `#3` has cursorline.
Buffer `#1` also has cursorline.

### Actual behavior

Buffer `#2` has cursorline.
Buffer `#3` has cursorline.
Buffer `#1` does NOT have cursorline.

Demo: https://asciinema.org/a/t7H5wa6QJJMo3etfpKRg2NrVa

**Comment by zeertzjq** [comment]
See `:h local-options`:
```
When editing a buffer that has been edited before, the options from the window
that was last closed are used again.  If this buffer has been edited in this
window, the values from back then are used.  Otherwise the values from the
last closed window where the buffer was edited last are used.
```
