### ISSUE TITLE
`vim.keymap.set` lacks an equivalent to `:map` (nvo modes)

### ISSUE THREAD

**Issue by goolord** [neovim/neovim#17138]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+894-g561df3098

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Arch Linux x86_64 5.15.11-arch2-1

### Terminal name/version

alacritty 0.10.0-dev (ec4dc326)

### $TERM environment variable

alacritty

### Installation

Arch User Repository (AUR) (neovim-git)

### How to reproduce the issue

1. call `vim.keymap.set('',..`

### Expected behavior

since the first parameter is the 'Same mode short names as|nvim_set_keymap()|', i would expect it to create an nvo keymap

### Actual behavior

no keymap is created

**Comment by zeertzjq** [comment]
I think supporting this can cause mistakes.

**Comment by zeertzjq** [comment]
This is also already achievable using `{'n', 'v', 'o'}`, isn't it?

**Comment by fsouza** [comment]
Isn't it a matter of invoking `vim.keymap.set({'n', 'v', 'o'}, ...)`?

**Comment by goolord** [comment]
yes, but

1. the blessed mode short-name for `nvo` (:map) is `''` in `nvim_set_keymap`, if intentional this is an undocumented discrepancy between the api and the lua api
2. vimL users don't have to know that `:map` is equivalent to `nmap+vmap+omap`

**Comment by zeertzjq** [comment]
Wait, I just tested and it is supported.

**Comment by zeertzjq** [comment]
Please provide minimal steps to reproduce.

**Comment by goolord** [comment]
you're right, it does work, the keymap that *doesn't* work is this, actualy `vim.keymap.set('', '<Space>', '<Leader>', {silent = true} )` and i wrongly assumed that it was the shortname since it was the only keymap i had that used the `nvo` shortname. my mistake. this still seems like a bug, since that works with `vim.api.nvim_set_keymap`

**Comment by zeertzjq** [comment]
Isn't that because `remap` is off by default?

**Comment by goolord** [comment]
no, as i said the keybinding works with `vim.api.nvim_set_keymap`, and it doesn't work with `vim.keymap.set`, with `noremap` set to true or false

**Comment by goolord** [comment]
ah, ok, `noremap` does not exist, and the behavior defaults to the inverse of `vim.api.nvim_set_keymap` that is the problem

**Comment by zeertzjq** [comment]
Oh, if `noremap` is already set it should not be overridden.

**Comment by zeertzjq** [comment]
Or should it?

**Comment by zeertzjq** [comment]
This may make sense if one passes the dictionary returned by `nvim_get_keymap()` to `vim.keymap.set()`.

**Comment by clason** [comment]
It's a different API -- it's meant not to have the exact same options as `nvim_set_keymap` (in particularly regarding `noremap`). 

They are not interchangeable; you're not meant to be able to feed the output of `nvim_get_keymap` to `keymap.set()`.
