### ISSUE TITLE
clipboard paste may lose data

### ISSUE THREAD

**Issue by doppioandante** [neovim/neovim#1714]
I was trying to open this file using nvim:
https://gist.github.com/doppioandante/66df8fd0a28ac7c7a0da
As you can see it's actually not that big, but that long line surely needs wrapping. The only thing I see if I try to paste it is a truncated bit of that file filling the whole screen, and then neovim is completely frozen up.
Using plain vim it works.
Also, there's no problem if I save the file in some other way and I then open it with neovim.

**Comment by justinmk** [comment]
The sample input works fine on latest master.

**Comment by oni-link** [comment]
We still lose much of the sample input if `Shift-Insert` pasting is used.

**Comment by justinmk** [comment]
Thanks.
