### ISSUE TITLE
Maybe I broke the Neovim runtime binary file, when I used packer remove a plugin, next it's always show the plugin error whe I reopen my Neovim.

### ISSUE THREAD

**Issue by sober-wang** [neovim/neovim#17144]
### Neovim version (nvim -v)

0.6.

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10 1909 internal version: 18363.1500

### Terminal name/version

windows terminal/ cmd.exe 

### $TERM environment variable

windows terminal 256

### Installation

use zip file install 

### How to reproduce the issue

I run `nvim --clean` is not problem.

installation form ![install_package_0.6.0](https://github.com/neovim/neovim/releases/download/v0.6.0/nvim-win64.zip)

but run `nvim` have problem 
![](https://user-images.githubusercontent.com/35804630/150279491-0aed6e28-7dbe-4c5c-bf2f-f50abe7615b1.png)

### Expected behavior

look like `nvim --clean`  is not problem

### Actual behavior

![图片](https://user-images.githubusercontent.com/35804630/150283899-3b716fa5-f65f-4040-a161-bd605b89390c.png)

**Comment by zeertzjq** [comment]
Which plugin did you remove?

**Comment by zeertzjq** [comment]
Anyway, it is likely that you forgot to run `:PackerCompile` after uninstalling the plugin.

**Comment by sober-wang** [comment]
C:\Users\Sober\AppData\Local\nvim\lua>nvim -r
Swap files found:
   In directory ~\AppData\Local\nvim-data\swap\\:
1.    C%%Users%Sober.swp
             dated: Fri Jan 14 17:22:01 2022
         file name: [No Name]
          modified: YES
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 23712
2.    D%%code%golang%gopath%pkg%mod%github.com%gin-gonic%gin@v1.6.3%gin.go.swp
             dated: Fri Jul 02 12:45:43 2021
         file name: D:\code\golang\gopath\pkg\mod\github.com\gin-gonic\gin@v1.6.3\gin.go
          modified: YES
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 18664
3.    D%%code%golang%gopath%pkg%mod%github.com%json-iterator%go@v1.1.10%adapter.go.swp
             dated: Thu Feb 25 19:33:06 2021
         file name: D:\code\golang\gopath\pkg\mod\github.com\json-iterator\go@v1.1.10\adapter.go
          modified: no
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 39532
4.    D%%code%golang%gopath%pkg%mod%github.com%json-iterator%go@v1.1.10%any.go.swp
             dated: Thu Feb 25 19:36:36 2021
         file name: D:\code\golang\gopath\pkg\mod\github.com\json-iterator\go@v1.1.10\any.go
          modified: no
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 39532
5.    D%%code%golang%gopath%pkg%mod%github.com%sober-wang%sendingtalk@v0.0.0-20190419094416-55109eca0429%sendingtalk.go.swp
             dated: Thu Feb 25 17:34:46 2021
         file name: D:\code\golang\gopath\pkg\mod\github.com\sober-wang\sendingtalk@v0.0.0-20190419094416-55109eca0429\sendingtalk.go
          modified: YES
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 39532
6.    D%%code%javaScript%vue-study%vue-test%vue-test.vue.swp
             dated: Tue Dec 29 21:02:01 2020
         file name: D:\code\javaScript\vue-study\vue-test\vue-test.vue
          modified: no
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 18384
7.    D%%code%myGithubCode%OpScript%goStudy%design-patterns%bridage%main.go.swp
             dated: Wed Feb 17 17:55:11 2021
         file name: D:\code\myGithubCode\OpScript\goStudy\design-patterns\bridage\main.go
          modified: YES
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 18460
8.    D%%code%myGoCode%cloudbg-webhook%go.mod.swp
             dated: Thu Feb 25 17:29:46 2021
         file name: D:\code\myGoCode\cloudbg-webhook\go.mod
          modified: no
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 39532
9.    D%%code%myGoCode%cloudbg-webhook%module%bluewhale%bluewhale.go.swp
             dated: Wed Mar 03 19:37:06 2021
         file name: D:\code\myGoCode\cloudbg-webhook\module\bluewhale\bluewhale.go
          modified: no
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 30616
10.    D%%code%myGoCode%cloudbg-webhook%module%dingtalk%dingtalk.go.swp
             dated: Wed Mar 03 19:47:25 2021
         file name: D:\code\myGoCode\cloudbg-webhook\module\dingtalk\dingtalk.go
          modified: no
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 30616
11.    D%%code%myGoCode%test%leetcode%towsum.swp
             dated: Thu Feb 18 14:13:00 2021
         file name: [No Name]
          modified: YES
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 25288
12.    D%%working%das%pdenv%zabbix%cloudbg-pushd%main.go.swp
             dated: Tue Oct 12 20:34:35 2021
         file name: D:\working\das\pdenv\zabbix\cloudbg-pushd\main.go
          modified: no
         user name: 0   host name: LAPTOP-7U1UTJ34
        process ID: 9860
packer.nvim: Error running config for galaxyline.nvim: [string "..."]:0: module 'galaxyline.themes.eviline' not found:
^Ino field package.preload['galaxyline.themes.eviline']
^Ino file '.\galaxyline\themes\eviline.lua'
^Ino file 'D:\software\Neovim\bin\lua\galaxyline\themes\eviline.lua'
^Ino file 'D:\software\Neovim\bin\lua\galaxyline\themes\eviline\init.lua'
^Ino file 'C:\Users\Sober\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\share\lua\5.1\galaxyline\themes\eviline.lua'
^Ino file 'C:\Users\Sober\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\share\lua\5.1\galaxyline\themes\eviline\init.lua'
^Ino file 'C:\Users\Sober\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\lib\luarocks\rocks-5.1\galaxyline\themes\eviline.lua'
^Ino file 'C:\Users\Sober\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\lib\luarocks\rocks-5.1\galaxyline\themes\eviline\init.lua'
^Ino file '.\galaxyline\themes\eviline.dll'
^Ino file 'D:\software\Neovim\bin\galaxyline\themes\eviline.dll'
^Ino file 'D:\software\Neovim\bin\loadall.dll'
^Ino file 'C:\Users\Sober\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\lib\lua\5.1\galaxyline\themes\eviline.so'
^Ino file '.\galaxyline.dll'
^Ino file 'D:\software\Neovim\bin\galaxyline.dll'
^Ino file 'D:\software\Neovim\bin\loadall.dll'
^Ino file 'C:\Users\Sober\AppData\Local\Temp\nvim\packer_hererocks\2.1.0-beta3\lib\lua\5.1\galaxyline.so'

> I remove the `glepnir/galaxyline.nvim`

**Comment by zeertzjq** [comment]
Does running `:PackerCompile` and restarting Nvim make the error disappear?

**Comment by sober-wang** [comment]
> Anyway, it is likely that you forgot to run `:PackerCompile` after uninstalling the plugin.

Cool , Thanks .
