### ISSUE TITLE
Virtual lines don't render `\t` correctly

### ISSUE THREAD

**Issue by lewis6991** [neovim/neovim#17148]
### Neovim version (nvim -v)

v0.7.0-dev+908-ga795c7e73

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Redhat 7

### Terminal name/version

kitty 0.24.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Create `test.lua` with the contents:
```lua
local ns = vim.api.nvim_create_namespace('test')

vim.api.nvim_buf_set_extmark(0, ns, 7, -1, {
  virt_lines = {
    {{'\t\t-- VIRT TEXT', 'Error'}}
  }
})

		-- REAL TEXT (this line begins with \t\t)

-- vim: set noet ft=lua ts=8 sw=8 :
```

2. `nvim test.lua -c 'source %'`

### Expected behavior

The virtual line `\t\t-- VIRT TEXT` should be aligned with `\t\t-- REAL TEXT`

### Actual behavior

![image](https://user-images.githubusercontent.com/7904185/150383902-4060bd39-3d5d-4360-bce1-ca77f7c699e6.png)

**Comment by lewis6991** [comment]
@bfredl

**Comment by younger-1** [comment]
@lewis6991 seem like the the problem don't appear in my test. (0.7.2 nvim, ArchLinux)

`nvim --clean a.lua`

![图片](https://user-images.githubusercontent.com/45989017/192140436-8a85fbd4-7b77-47f5-af32-fd9440a2195d.png)
 
Looks like irtual lines could render `\t` correctly.

**Comment by zeertzjq** [comment]
I guess `vim.o.number = true` is missing from the steps to reproduce.

**Comment by zeertzjq** [comment]
This fixes the problem:
```diff
diff --git a/src/nvim/drawline.c b/src/nvim/drawline.c
index 5c3fa3d3b..10e1d9573 100644
--- a/src/nvim/drawline.c
+++ b/src/nvim/drawline.c
@@ -2607,7 +2607,7 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
           assert(i >= 0);
           int offset = kv_A(virt_lines, i).left_col ? 0 : win_col_offset;
           draw_virt_text_item(buf, offset, kv_A(virt_lines, i).line,
-                              kHlModeReplace, grid->cols, offset);
+                              kHlModeReplace, grid->cols, 0);
         }
       } else {
         draw_virt_text(wp, buf, win_col_offset, &draw_col, grid->cols, row);

```

**Comment by younger-1** [comment]
> I guess `vim.o.number = true` is missing from the steps to reproduce.

Yes!  And it is also related to `'signcolumn'` and `'foldcolumn'`. The align behaviour seems to be a mix result of these "column" values.
(note: with 'number' be set and 'signcolumn=yes:2', it align right again)
