### ISSUE TITLE
Exception thrown constantly in r language server, but still works

### ISSUE THREAD

**Issue by joshpetit** [neovim/neovim#17140]
### Neovim version (nvim -v)

0.6.1

### Language server name/version

r_language_server

### Operating system/version

Arch

### Steps to reproduce using "nvim -u minimal_init.lua"

The only modifications I made to the minimal init file is change the name of the language server from pyright to r_language_server

```lua
  local name = 'r_language_server'
  local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    on_attach = on_attach,
  }
```

### Expected behavior

It should work without the exception being thrown

### Actual behavior

It outputs
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/highlight.lua:33: attempt to compare string with number
stack traceback:
        /usr/share/nvim/runtime/lua/vim/highlight.lua:33: in function 'range'
        /usr/share/nvim/runtime/lua/vim/diagnostic.lua:900: in function 'show'
        /usr/share/nvim/runtime/lua/vim/diagnostic.lua:1138: in function 'show'
        /usr/share/nvim/runtime/lua/vim/diagnostic.lua:660: in function 'set'
        /usr/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:209: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:735: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

randomly. It still has things such as autocomplete and diagnostics, but this error pops up consistently

### Log file

https://gist.github.com/joshpetit/ec4176bf39ac34e35b394e3a302b0192

**Comment by mjlbach** [comment]
Is this your actual minimal config?

```lua
  local name = 'r_language_server'
  local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
```

This will override r_language_server to use pyright, a python language server.

I can't reproduce your issue, R_language_server seems to work fine for me.

* `brew install R openssl` (or linux equivalent)
* `R`
* `install.packages("languageserver")`
*  add `require('lspconfig').r_language_server.setup{}`to your config

**Comment by joshpetit** [comment]
So I reran `install.packages("languageserver")` and it fixed it some how 🤷. Thanks for the time haha 😅.

**Comment by joshpetit** [comment]
> Is this your actual minimal config?
> 
> ```lua
>   local name = 'r_language_server'
>   local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
>   if not name then
> ```
> 
> This will override r_language_server to use pyright, a python language server.
> 
> I can't reproduce your issue, R_language_server seems to work fine for me.
> 
>     * `brew install R openssl` (or linux equivalent)
> 
>     * `R`
> 
>     * `install.packages("languageserver")`
> 
>     * add `require('lspconfig').r_language_server.setup{}`to your config

Also I removed the `cmd` variable when setting up the lsp thing so it was unused, just for clarification

**Comment by mjlbach** [comment]
No worries, just checking :)

**Comment by joshpetit** [comment]
Hey, so after a week the exceptions are back 😅. I tired reinsintalling the server again and that did nothing. This is the same excpetion:

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/highlight.
lua:33: attempt to compare string with number
stack traceback:
        /usr/share/nvim/runtime/lua/vim/highlight.lua:33: in function 'range'
        /usr/share/nvim/runtime/lua/vim/diagnostic.lua:900: in function 'show'
        /usr/share/nvim/runtime/lua/vim/diagnostic.lua:1138: in function 'show'
        /usr/share/nvim/runtime/lua/vim/diagnostic.lua:660: in function 'set'
        /usr/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:209: in function 'handler'

        /usr/share/nvim/runtime/lua/vim/lsp.lua:735: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

This is called from the lsp, it seems to be this function in the trace:
```lua
function highlight.range(bufnr, ns, higroup, start, finish, rtype, inclusive)
  rtype = rtype or 'v'
  inclusive = inclusive or false

  -- sanity check
  if start[2] < 0 or finish[1] < start[1] then return end

  local region = vim.region(bufnr, start, finish, rtype, inclusive)
  for linenr, cols in pairs(region) do
    api.nvim_buf_add_highlight(bufnr, ns, higroup, linenr, cols[1], cols[2])
  end
end
```

**Comment by mjlbach** [comment]
Seems to be a server issue then, I would share the rpc log with them.

**Comment by joshpetit** [comment]
Ah, I don't know much, but it seems to be some kind of error involving syntax highlighting? Does the call stack indicate it's a problem with the server? It seems to be a problem with the lsp based on the trace. I may be wrong though

**Comment by mjlbach** [comment]
> Ah, I don't know much, but it seems to be some kind of error involving syntax highlighting? 

It is not. `highlight` is used in setting diagnostics highlights, not syntax highlighting.

>  Does the call stack indicate it's a problem with the server?

All the callstack says is highlight range is being called with some incorrect parameters, as these are directly forwarded from the language server, the problem is there.

> It seems to be a problem with the lsp based on the trace

LSP is the protocol, the problem is either in the language server or the language server client (neovim). I'm assuming given this issue only occurs with r language server, that r language server is sending an invalid diagnostic.

**Comment by joshpetit** [comment]
Ok makes perfect sense! Sorry for making you explain it 😅. So I should open up an issue on the R language server? What should I say in the issue?

**Comment by mjlbach** [comment]
Yes, you should file an upstream request and include the rpc log (from setting log level to debug, the log you pasted before has no information, see `:help lspconfig-logging`) with the *first* set of diagnostics that causes the issue. I believe it is likely a malformed diagnostic response. You can paste it here for me to verify for you, but this issue is most certainly not on the neovim side.

**Comment by sandersantema** [comment]
For anyone running into the same issue: https://github.com/REditorSupport/languageserver/issues/481

It's fixed for the latest (at the time of writing dev) version of the R language server.

**Comment by fisher-j** [comment]
I'm still getting this error with neovim 10 and r-languageserver 0.3.15

Still getting this error in Neovim 10

```
Error executing vim.schedule lua callback: ...m Files\Neovim\share\nvim\runtime/lua/vim/diagnostic.lua:405: attempt to compare string with number
stack traceback:
        ...m Files\Neovim\share\nvim\runtime/lua/vim/diagnostic.lua:405: in function 'add'
        ...m Files\Neovim\share\nvim\runtime/lua/vim/diagnostic.lua:422: in function 'add_all_diags'
        ...m Files\Neovim\share\nvim\runtime/lua/vim/diagnostic.lua:443: in function 'get_diagnostics'
        ...m Files\Neovim\share\nvim\runtime/lua/vim/diagnostic.lua:1201: in function 'show'
        ...m Files\Neovim\share\nvim\runtime/lua/vim/diagnostic.lua:665: in function 'config'
        ...les/Neovim/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:233: in function 'handler'
        C:/Program Files/Neovim/share/nvim/runtime/lua/vim/lsp.lua:1122: in function 'cb'
        vim/_editor.lua:324: in function <vim/_editor.lua:323>
```
