### ISSUE TITLE
guioptions is not a legal option.

### ISSUE THREAD

**Issue by WuG978** [neovim/neovim#17159]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

Not test

### Operating system/version

Windows 10 latest

### Terminal name/version

PowerShell

### $TERM environment variable

default

### Installation

From release

### How to reproduce the issue

```
nvim --clean
:set guioptions-=e
:set guioptions?
```

### Expected behavior

Finally, show me a error: `E519: Option not supported: guioptions?`
So that I can't use a non-GUI tab pages line, and only a GUI tab are supported everywhere

### Actual behavior

I want to use a non-GUI tabs.

**Comment by zeertzjq** [comment]
Are you running Nvim in a terminal and setting `'guioptions'`?

**Comment by jamessan** [comment]
Use `'showtabline'` to decide when to show the tab line.  Refer to your GUI's documentation to determine if it gives you control for whether the tab line is rendered by the GUI or by nvim.  E.g., [nvim-qt](https://github.com/equalsraf/neovim-qt) has the `GuiTabline` command to control that (`:GuiTabline 0` to have nvim render the tabline).
