### ISSUE TITLE
lsp: add semantic tokens support

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#17153]
### Feature already in Vim?

N/A

### Feature description

For 3.16 compliance, we should add semantic tokens support. This could be used for semantic highlighting. There is an open PR addressing this, but I want to open specific feature requests that can be tracked.

**Comment by theHamsta** [comment]
This is the mentioned PR #15723. It has do add tests and needs to handle offset encoding correctly. I hope i can finish it this weekend.
