### ISSUE TITLE
Provide debug symbols

### ISSUE THREAD

**Issue by laomaiweng** [neovim/neovim#17151]
### Feature description

Would it be possible to provide debug symbols along with the various releases of Neovim? (Not necessarily bundled with the releases, I was more thinking about separate artifacts.)
This may help troubleshoot issues without having to rebuild Neovim to generate said symbols, making debugging less painful and error-prone.

On Windows, building with /DEBUG should generate the PDBs.
On Linux, -ggdb3 should be used, then objcopy to separate the debug info apparently: https://stackoverflow.com/a/866731

As debug symbols may get quite large, it may be inappropriate to provide them as releases, in which case, fine, sorry about the noise. 🤷

**Comment by laomaiweng** [comment]
I'm sorry, I didn't check thoroughly enough before filing this issue, as it turns out Neovim is already built as `RelWithDebInfo`.

I'm confused though, since WinDBG only reports having access to export symbols, and does not show local variables when attached. Is this normal behavior with `RelWithDebInfo`? I'd have expected more debugging features to be available. :-/

**Comment by dundargoc** [comment]
Is there a reason you'd prefer downloading the artifact instead of building neovim with `-DCMAKE_BUILD_TYPE=Debug`?

> Would it be possible to provide debug symbols along with the various releases of Neovim? (Not necessarily bundled with the releases, I was more thinking about separate artifacts.)

It's certainly possible. I'm personally not convinced it's useful enough to counteract the cost of maintaining it (especially considering the neovim release process is already quite intricate). But this is not my decision to make. @jamessan ?

**Comment by laomaiweng** [comment]
Well I tend to always have a debugger at hand, but not necessarily a build toolchain. :)
Plus, this way I'd be sure to be debugging the actual, released Neovim, not a build of mine that may exhibit random slight differences due to different build toolchains.

Though I must admit after going through it today on both Windows & Linux, the build process for Neovim is quite streamlined, kudos!

Overall I understand that it's a rather niche use case, and a maintenance burden, so "No." would be a perfectly valid answer.

**Comment by glacambre** [comment]
@laomaiweng I've also experienced WinDBG being unable to debug Neovim. GDB (installed through mingw, if I recall correctly) worked fine though. Have you tried it?

**Comment by laomaiweng** [comment]
I'm not sure what you mean by "unable": I can attach Neovim, but I find I'm missing a lot of symbols & debug information (local variables, static functions, …) I'd expect to be available from a _RelWithDebInfo_ build.
I tried both WinDBG and LLDB and both seem to show the same amount of information.

I also tried rebuilding Neovim in _RelWithDebInfo_ configuration on Windows, and this time with the _.pdb_ file available next to my Neovim binary, all those symbols show up. So it looks more like a case of missing debug info rather than a WinDBG issue. :)

**Comment by glacambre** [comment]
>I'm not sure what you mean by "unable"

I mean that I was able to attach to the process but did not have symbols, source mapping etc.

>I'd expect to be available from a RelWithDebInfo build.

And I think it is, but as DWARF, which GDB supports but WinDebug might have issues with.

>I also tried rebuilding Neovim in RelWithDebInfo configuration on Windows, and this time with the .pdb file available next to my Neovim binary, all those symbols show up.

Right, this seems to corroborate my theory :)

**Comment by laomaiweng** [comment]
I must admit I'd be very surprised to see DWARF debug info in a PE binary. :-o
In fact I took a closer look at the distributed Neovim 0.6.1 PE binary for Windows, and it turns out it indeed contains a debug Data Directory referencing a _D:\a\neovim\neovim\build\bin\nvim.pdb_ PDB file.

So I'm guessing the _RelWithDebInfo_ CI build already produces the debug info in this PDB file, but that file is left behind while packaging Neovim for Windows.

I tried my luck and added the following line to _src/nvim/CMakeLists.txt_:

```cmake
install(FILES $<TARGET_PDB_FILE:nvim> DESTINATION ${CMAKE_INSTALL_BINDIR} OPTIONAL)
```

After building and producing the Zip install bundle, it contained the missing _nvim.pdb_ file. :)
The PDB file is currently around 10 MB unpacked, 4 MB zipped. Is this worth a PR to include it by default in Windows releases, or is it too niche of a use case?

**Comment by glacambre** [comment]
>I must admit I'd be very surprised to see DWARF debug info in a PE binary. :-o

You shouldn't be, that's the only debug info you'll ever see in binaries compiled from gcc/mingw :).

But I looked at the CI again and discovered that we were in fact using MSVC instead of mingw to build windows releases, so my theory is completely invalidated and your sounds much more likely.

>The PDB file is currently around 10 MB unpacked, 4 MB zipped. Is this worth a PR to include it by default in Windows releases, or is it too niche of a use case?

Given that the windows zip file is already 32MB, I'd say 4 more MB won't hurt much. On top of that, anything that makes debugging easier for windows users is worth doing as there already seems to be a high barrier of entry for contributing to neovim on this OS.
