### ISSUE TITLE
0.6.0 messes up colorscheme background

### ISSUE THREAD

**Issue by esn89** [neovim/neovim#17167]
### Neovim version (nvim -v)

NVIM v0.6.0

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS 12.0.1

### Terminal name/version

Kitty 0.20.3

### $TERM environment variable

xterm-kitty

### Installation

Macports

### How to reproduce the issue

Simply start nvim with the following colorscheme: https://github.com/sainnhe/everforest

```set t_Co=256
set background=dark

set termguicolors
colorscheme everforest
let g:everforest_background = 'hard'
let g:everforest_diagnostic_text_highlight = 1
let g:everforest_diagnostic_line_highlight = 1
let g:everforest_diagnostic_virtual_text = 'colored'
let g:everforest_enable_italic = 1
```

And this in the config.  I have even tried commenting out the `set background` and `everforest_background`

### Expected behavior

I expect that the background matches my terminal 's background so that the terminal + nvim is all uniform in color.
It should look like this: [https://imgur.com/a/H4nizCc](https://imgur.com/a/H4nizCc)
This is not happening in the 0.5 release

### Actual behavior

It looks like this at the moment, with the latest 0.6
[https://imgur.com/a/5J2obIp](https://imgur.com/a/5J2obIp)

**Comment by zeertzjq** [comment]
Does moving `colorscheme everforest` to be bottom of `init.vim` solve the problem?

**Comment by esn89** [comment]
Yes it does.  Thanks for the help.
