### ISSUE TITLE
No Python executable found that can `import neovim`

### ISSUE THREAD

**Issue by jeffschwartz** [neovim/neovim#17172]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

mac os 11.6.2

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

brew install neovim

### How to reproduce the issue

:checkhealth provider results in
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3.9"
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - INFO: Executable: Not found

### Expected behavior

To find my installed python3:

➜  ~ which python3
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3

➜  ~ file /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 (for architecture x86_64):Mach-O 64-bit executable x86_64
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 (for architecture arm64):	Mach-O 64-bit executable arm64

### Actual behavior

:checkhealth provider results in
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3.9"
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - INFO: Executable: Not found

**Comment by zeertzjq** [comment]
Did you install `pynvim`?

**Comment by jeffschwartz** [comment]
@zeertzjq yes, it is installed. See as per below:
➜  ~ pip3 install pynvim                                                                                                                                                           <<<
Requirement already satisfied: pynvim in ./Library/Python/3.10/lib/python/site-packages (0.4.3)
Requirement already satisfied: msgpack>=0.5.0 in ./Library/Python/3.10/lib/python/site-packages (from pynvim) (1.0.3)
Requirement already satisfied: greenlet in ./Library/Python/3.10/lib/python/site-packages (from pynvim) (1.1.2)

**Comment by Mcculloughj** [comment]
Hi yes I’m sorry I haven’t gotten back to this but I have a lot todo and no
help. But I will get to it as soon as I can. I’m still really new at all of
this and my buisness is on a level I have no idea about but I’m working 18
to 14 hours a day to stay in compliance and regulation. But it is only me
and I am disabled plus’s only one person so can I get GitHub to help my
development please y’all have been so good to me and I love y’all but I
have worked three years for my company and I haven’t paid myself nor gotten
a break from anything thanks

**Comment by jeffschwartz** [comment]
I'm also experiencing permission denied for tree-sitter (see image below) when I start nvim but not sure if this is related to my op. FYI I installed neovim using Homebrew.

<img width="1507" alt="Screen Shot 2022-01-23 at 2 33 45 PM" src="https://user-images.githubusercontent.com/271288/150695189-e156424a-cd17-4bb5-930a-6acea58342c4.png">

**Comment by glacambre** [comment]
Does this happen with `nvim -u NORC`? I don't see why neovim would pick up python 3.9 ( `Using: g:python3_host_prog = "/usr/local/bin/python3.9"` ) if 3.10 is first in your $PATH ( `/Library/Frameworks/Python.framework/Versions/3.10/bin/python3` ).
Does adding `let g:python3_host_prog = "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3` at the end of your init.vim fix the problem?

**Comment by jeffschwartz** [comment]
@glacambre I found the problem. I had been using both Homebrew and Macports and found that the two package managers do not coexist very well, specifically in their path requirements. I have uninstalled Macports and I am currently in the process of reinstalling my environment using only Homebrew. Once that is done I will close this issue out once I have Neovim working on my Mac M1. Sorry that I burdened all with this but I didn't know that using the 2 package managers would cause a problem.

**Comment by jeffschwartz** [comment]
I remove Macports and reset my .zprofile to default and this eliminated the permission denied issues (see above). I now get no errors when starting nvim. However, I am now still getting the E319: No "python3" provider found. Run ":checkhealth provider".

<img width="1106" alt="Screen Shot 2022-01-24 at 10 23 57 AM" src="https://user-images.githubusercontent.com/271288/150811649-33dbc730-8b4b-4996-8b90-00706801a5af.png">

As stated, my paths are now correct so python3 should have been found:

<img width="1482" alt="Screen Shot 2022-01-24 at 10 27 37 AM" src="https://user-images.githubusercontent.com/271288/150812502-be60d510-ec1e-4029-a550-54dd493d94e8.png">

<img width="1602" alt="Screen Shot 2022-01-24 at 10 29 56 AM" src="https://user-images.githubusercontent.com/271288/150812716-5b5a4f2a-0d79-47ff-b884-78871964f795.png">

I also aliased python to python3:

<img width="948" alt="Screen Shot 2022-01-24 at 10 31 51 AM" src="https://user-images.githubusercontent.com/271288/150813002-02391378-5350-4b0d-b419-f23a89adad7a.png">

So presumably python is discoverable now yet nvim plugins cannot.

**Comment by clason** [comment]
Did you (re)install `pynvim` _for this Python version_?

**Comment by glacambre** [comment]
@jeffschwartz My questions still stand :) :
- Does this happen with `nvim -u NORC`?
- Does adding `let g:python3_host_prog = "~/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"` at the end of your init.vim fix the problem?
- Additionally, does adding `export PYTHONPATH="~/Library/Python/3.9/lib/python/site-packages:$PYTHONPATH"` to your .zshrc fix the problem?

**Comment by jeffschwartz** [comment]
@clason I removed python 10. Now using  3.9.10. As for pynvim, yes, it is installed as shown below:
<img width="490" alt="Screen Shot 2022-01-24 at 11 50 43 AM" src="https://user-images.githubusercontent.com/271288/150827895-546e75d6-d637-415f-89d6-55eb6bf34f69.png">

**Comment by jeffschwartz** [comment]
@clason 
Thank you for assistance. I really appreciate it. Everything works now as it should. You have been a great help! I am closing out this issue now.

**Comment by Endermanbugzjfc** [comment]
It appears that installing **Python3 via Winget** may be causing some issues. I do not wish to replicate the problem here, but I wanted to bring it to your attention. I **recommend using the official installer** and restarting your system to resolve any potential issues.

**Comment by Sleepful** [comment]
For me, I was using pipx so:
```
-- path returned by `which pynvim-python` after installing `pipx install  pynvim`
vim.g.python3_host_prog = '~/.local/share/../bin/pynvim-python'
```
