### ISSUE TITLE
Gravity highlights make syntax highlights broken after set lines

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#17170]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+913-ge07a4b97f

Happens on nvim >= 0.6.0

### Vim (not Nvim) behaves the same?

Not happens with vim's `textprop`

### Operating system/version

MacOS 12.1

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

repo

### How to reproduce the issue

Highlight variables by api`nvim_buf_set_extmark` with `right_gravity` and `end_right_gravity` set to `1`.
Update variable name by change related lines using api `nvim_buf_set_lines`, some syntax highlights would be removed and get restored on cursor move.

https://user-images.githubusercontent.com/251450/150640304-557d496f-4826-4653-8330-55dbc068f351.mov

### Expected behavior

`right_gravity` and `end_right_gravity` should not affect syntax highlights of unrelated line.

### Actual behavior

Syntax highlights broken.

**Comment by wadinj** [comment]
Hi, 

Is this fixed ?

**Comment by dundargoc** [comment]
If an issue is open it's generally safe to assume that the problem still exists and that it hasn't been fixed :)

**Comment by bfredl** [comment]
@chemzqm the attached video does not match the description at all. did you perchange attach the wrong video?

**Comment by chemzqm** [comment]
No, it describes the wired highlight behavior.
Can't reproduce it any more.

**Comment by wadinj** [comment]
Few infos : 
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

My treesitter plugin is up to date ; with : 
html            [✓] installed

Terminal : 
iTerm 3.4.15

nvim .config : 
set termguicolors

Sometimes, when I open a big HTML file, the syntax highlighting are disabled by portion. The code is completely white and syntax highlight can comeback when I save or scroll up & down An example :
<img width="1685" alt="image" src="https://user-images.githubusercontent.com/6746970/163271812-69062525-000c-4743-b0fb-fd7c51622951.png">

**Comment by clason** [comment]
That is completely unrelated.

**Comment by dundargoc** [comment]
@wadinj hmm, this looks like this should be sent to https://github.com/nvim-treesitter/nvim-treesitter .

@clason please confirm or deny so I don't send someone on a goose chase :)

**Comment by LeiTi34** [comment]
There is already an issue nvim-treesitter/nvim-treesitter#1788 .
But they say it's an upstream bug.

**Comment by clason** [comment]
If you have a reproducible(!) example (minimal config _and_ html file) you can share, please open a new issue here about it. The nvim-treesitter issue is not clear at all (it sounds like this happens even without editing? in this case, it's very unlikely to be _this_ bug).

**Comment by bfredl** [comment]
this bug is already resolved as not existing. open a new one if there is a bug.
