### ISSUE TITLE
paste: Error executing lua: vim.lua:0: attempt to index a nil

### ISSUE THREAD

**Issue by ta-tikoma** [neovim/neovim#17189]
### Neovim version (nvim -v)

NVIM v0.7.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-o30hrS/neovim-0.7.0~ubuntu1+git202201240048-7e2ce35e3-dd05b3569=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-o30hrS/neovim-0.7.0~ubuntu1+git202201240048-7e2ce35e3-dd05b3569/build/config -I/build/neovim-o30hrS/neovim-0.7.0~ubuntu1+git202201240048-7e2ce35e3-dd05b3569/src -I/build/neovim-o30hrS/neovim-0.7.0~ubuntu1+git202201240048-7e2ce35e3-dd05b3569/.deps/usr/include -I/usr/include -I/build/neovim-o30hrS/neovim-0.7.0~ubuntu1+git202201240048-7e2ce35e3-dd05b3569/build/src/nvim/auto -I/build/neovim-o30hrS/neovim-0.7.0~ubuntu1+git202201240048-7e2ce35e3-dd05b3569/build/include Compiled by buildd@lgw01-amd64-031

### Vim (not Nvim) behaves the same?

not

### Operating system/version

Ubuntu 20.04.1 LTS (Focal Fossa) 4.19.128-microsoft-standard on WSL2 in Windows 11

### Terminal name/version

windows terminal / Version: 1.11.3471.0

### $TERM environment variable

xterm-256color

### Installation

system package manager 

### How to reproduce the issue

1. [Open https://github.com/nvim-treesitter/nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter#language-parsers)
2. copy "TSInstall "
3. nvim -u NONE
4. press :
5. do paste: ctrl+shift+v

### Expected behavior

:TSInstall 

### Actual behavior

![image](https://user-images.githubusercontent.com/2934128/150829235-c521a7d2-459b-485a-841c-430d389bfdf0.png)
`paste: Error executing lua: vim.lua:0: attempt to index a nil value^@stack traceback:^@^Ivim.lua: in function <vim.lua:0>`

**Comment by clason** [comment]
So the issue here is with command completion not handling unicode whitespace correctly on Windows (cannot reproduce this on macOS)?

**Comment by zeertzjq** [comment]
Can you check if #16585 fixes this?

**Comment by zeertzjq** [comment]
Also, was clipboard empty when you pasted?

**Comment by zeertzjq** [comment]
I've converted #16585 into a plugin: <https://github.com/zeertzjq/nvim-paste-fix>. You can check that.

**Comment by ta-tikoma** [comment]
@zeertzjq , so fast answer, great thanks! it is work.
