### ISSUE TITLE
import { type } messes up highlighting

### ISSUE THREAD

**Issue by nikolay-govorov** [neovim/neovim#17188]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux, kernel 5.16.2-arch1-1

### Terminal name/version

alacritty 0.10.0 (8a26dee0)

### $TERM environment variable

xterm-256color

### Installation

pacman

### How to reproduce the issue

```
nvim -u NORC typescript_file.ts

# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```

Input the following code:

```typescript
// => a.ts
type TName = string;

// => b.ts
import { type TName } from 'a./ts'
let name: TName = 'Jake';
```

### Expected behavior

Code after `{ type TName` until the end of file is rendered in the same color.

### Actual behavior

In TypeScript version 4.5, a special syntax was added to describe the type inside the import: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names

The highlighting should be correctly.

**Comment by nikolay-govorov** [comment]
Related with #13135

**Comment by clason** [comment]
If this is without tree-sitter, this is an issue with the bundled syntax files, which we don't maintain.

The usual procedure here is to check `/runtime/syntax/<filetype.vim>` for a listed maintainer (in this case https:github.com/HerringtonDarkholme/yats.vim) and file bugs there. Corrections should be PR'd to vim/vim, and when these are merged (in the form of a runtime file update), we will port it as a matter of course.

**Comment by nikolay-govorov** [comment]
Thank you for such a quick response. I checked, with Tree-setter works correctly, the bug is only in the default syntax highlighting.
