### ISSUE TITLE
float : beak color-column line when over it

### ISSUE THREAD

**Issue by n3wborn** [neovim/neovim#17190]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+922-g1b6ae2dbb Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Fedora 32

### Terminal name/version

xfce4-terminal --version xfce4-terminal 0.8.10 (Xfce 4.14)

### $TERM environment variable

tmux-256color

### Installation

built from source

### How to reproduce the issue

- open a float_window large enough to hide colorcolumn (for example vim.lsp.buf.hover())
- escape hover() float_window
- see that colorcolumn has changed

### Expected behavior

Once I escape from a float_window, for example hover(), if this window was over, colorcolumn is unchanged

### Actual behavior

Actually, once I escape from hover(), column seems broken. This can be repeated more than once, as long as float_window hides colorcolumn it will seems broken each time float_window is closed

![image](https://user-images.githubusercontent.com/10246722/150884703-f569afc7-58c3-4ea9-b44c-f582b51cdf1e.png)

**Comment by zeertzjq** [comment]
I cannot reproduce this. Does colorcolumn become normal if you press Ctrl-L?

**Comment by n3wborn** [comment]
Damn, I can't too now -_- 
Don't understand. Sorry. I close
