### ISSUE TITLE
`WinScrolled` event misbehaves if horizontal scroll was caused by cursor move

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#17196]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+908-g431915fe6

### Vim (not Nvim) behaves the same?

No, Vim doesn't have `WinScrolled` event

### Operating system/version

Ubuntu 20.04

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

appImage

### How to reproduce the issue

1. nvim --clean -u NONE
2. `:set nowrap | let g:counter=0`
3. `:au WinScrolled * let g:counter+=1 | echo 'Hello scroll #' . g:counter`
4. Type lines `\n\nFoo`.
5. Position cursor at `F`.
6. Execute `zl` two times (should lead to window only showing `o` at third line).
7. Execute either of the following:
    7.1. Move cursor left three times.
    7.2. Move cursor up two time.

### Expected behavior

Message(s) `Hello scroll #...` should be shown immediately after first movement (and also second one in case of 7.1.).

### Actual behavior

Messages are shown lagging by one cursor movement. Interestingly enough, movement in Insert mode behaves as expected.

Animation of current behavior:
<details>
<summary>Animation of lagging `WinScrolled`</summary>

![neovim_winscrolled-lag](https://user-images.githubusercontent.com/24854248/150994489-e4c86b99-de5a-48ba-afe7-772eecfbb58e.gif)

</details>

**Comment by echasnovski** [comment]
Maybe related to this Vim's behavior: vim/vim#9625 .

**Comment by zeertzjq** [comment]
This fixes the problem:
```diff
diff --git a/src/nvim/normal.c b/src/nvim/normal.c
index 72e80952f..66227aedf 100644
--- a/src/nvim/normal.c
+++ b/src/nvim/normal.c
@@ -1359,6 +1359,7 @@ static int normal_check(VimState *state)
     // Need to make sure w_topline and w_leftcol are correct before
     // normal_check_window_scrolled() is called.
     update_topline(curwin);
+    validate_cursor();
 
     normal_check_cursor_moved(s);
     normal_check_text_changed(s);
```
The comment above mentions that `w_leftcol` needs to correct, but `update_topline()` does not update `w_leftcol`. `validate_cursor()` does that.

**Comment by zeertzjq** [comment]
There is something else wrong with this event: `w_last_topline`, `w_last_leftcol`, etc. are not initialized, so when `WinScrolled` is just defined they contain uninitialized values.
