### ISSUE TITLE
autocmd BufReadPost doesn't work

### ISSUE THREAD

**Issue by ayroblu** [neovim/neovim#17208]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no, 8.2.3800

### Operating system/version

macOS 12.1

### Terminal name/version

alacritty 0.9.0 (fed349a)

### $TERM environment variable

screen-256color

### Installation

brew install

### How to reproduce the issue

I set my init.vim to:

```vim
autocmd BufReadPost * echom 'hi there'
```

### Expected behavior

I expect to see the event called when I open `nvim file`

### Actual behavior

File opens without message, and no messages are logged in `:messages`

Doing the same in vim shows the message

**Comment by zeertzjq** [comment]
See <https://github.com/neovim/neovim/wiki/FAQ#calling-inputlist-echomsg--in-filetype-plugins-and-autocmd-does-not-work>.
