### ISSUE TITLE
LSP: error: parsing of rpc headers with word `content` in buffer

### ISSUE THREAD

**Issue by seblj** [neovim/neovim#17212]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+908-g431915fe6

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.1

### Terminal name/version

kitty 0.24.1

### $TERM environment variable

xterm-kitty

### Installation

Build from source

### How to reproduce the issue

Set up the built-in lsp client to use `grammarly` language server, and open up a file with the word `content` inside. The word `content` must already be in the buffer when the file is opened up. If it is typed after the server is attached, it works as expected.

### Expected behavior

Should not error

### Actual behavior

It sends a bunch of errors, and it is almost impossible to do anything without shutting the server down

### Additional context: 
I have pinpointed where the error is happening. I am also not sure if this is something that is possible to fix in core, or if it should be addressed in the language server, but I'll try to open up an issue here to see if it's possible to do something with it.

So the problem is starting with the variable `header_start_pattern` on line 84 in `runtime/lua/vim/lsp/rpc.lua`. It happens because it matches on the word `content`, and then believes that it is a header. Then it can't further parse it into for example `Content-Length: 100` inside `parse_headers`. This makes it error.

I am not entirely sure why it doesn't error with other language servers when the word `content` is in the buffer, so I assume it could be that the grammarly language server sends a bad message.

If you think this isn't something that the built in client could/should do something with, and that this should be handled by the server, feel free to close the issue!

### Minimal init.vim

```vim
call plug#begin()
Plug 'neovim/nvim-lspconfig'
call plug#end()
 
lua require('lspconfig').grammarly.setup({})
```

Also make sure grammarly is installed with:
`npm i -g @emacs-grammarly/unofficial-grammarly-language-server`

Open up a file (for example):
```md
### This is a test to show grammarly

Look how grammarly errors out when the word content is in the buffer
```

**Comment by jdhao** [comment]
Same issue here,  when we open a Mark down file and its paths contains `content`,  we will also see error messages.

**Comment by mjlbach** [comment]
> So the problem is starting with the variable header_start_pattern on line 84 in runtime/lua/vim/lsp/rpc.lua. It happens because it matches on the word content, and then believes that it is a header. Then it can't further parse it into for example Content-Length: 100 inside parse_headers. This makes it error.

I'm pretty sure the current logic is fine if the language server is sending well-formed json packets. I would recommend using `ltex-ls` for the time being (IMO it's better anyways) and filing an upstream issue with the language server including the RPC log of the first message that causes the issue.

**Comment by seblj** [comment]
> I'm pretty sure the current logic is fine if the language server is sending well-formed json packets. I would recommend using `ltex-ls` for the time being (IMO it's better anyways) and filing an upstream issue with the language server including the RPC log of the first message that causes the issue.

Okay, I understand! I will use `ltex-ls` for now. I'll just close this issue then
