### ISSUE TITLE
Vala filetype detect

### ISSUE THREAD

**Issue by matbme** [neovim/neovim#17227]
### Feature already in Vim?

No

### Feature description

Add filetype detection for [Vala](https://wiki.gnome.org/Projects/Vala)'s file type (*.vala)

**Comment by clason** [comment]
Sorry, I meant _really_ upstream: Vim. (We take runtime files verbatim from Vim.)

**Comment by clason** [comment]
Once Vim merges this, we'll pull in the change as a matter of course, so no need to track it.
