### ISSUE TITLE
Error when launching nvim binary

### ISSUE THREAD

**Issue by jkgithubrep** [neovim/neovim#17249]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no, 8.2

### Operating system/version

maxOS 10.13.6

### Terminal name/version

iterm2 3.2.5

### $TERM environment variable

screen-256color

### Installation

Build from repo

### How to reproduce the issue

Download nvim-macos.tar.gz
Extract: tar xzvf nvim-macos.tar.gz
Run ./nvim-osx64/bin/nvim

### Expected behavior

Nvim should open normally.

### Actual behavior

I get this error:
```
% ./nvim-osx64/bin/nvim
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/jk/Documents/./nvim-osx64/bin/nvim
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/jk/Documents/./nvim-osx64/bin/nvim
  Expected in: /usr/lib/libSystem.B.dylib

zsh: abort      ./nvim-osx64/bin/nvim
```

**Comment by clason** [comment]
We possibly don't support macOS 10.13 anymore (due to a dependency dropping support).

Can you try actually building from source?

**Comment by jkgithubrep** [comment]
> Can you try actually building from source?

Thanks for your quick reply. I will try.

**Comment by jkgithubrep** [comment]
@clason I solved the issue, thanks!
