### ISSUE TITLE
Empty string <expr> maps prevent timers from triggering

### ISSUE THREAD

**Issue by tpope** [neovim/neovim#17257]
### Neovim version (nvim -v)

0.6.1, 0.4.4

### Vim (not Nvim) behaves the same?

No, Vim 8.0.0000

### Operating system/version

Linux, macOS

### Terminal name/version

Any

### $TERM environment variable

xterm-256color

### Installation

Build from source

### How to reproduce the issue

```
nvim --clean
:imap <expr> <C-J> [timer_start(0, { _ -> execute("throw 'x'", "") }), ''][-1]
i<C-J>
```

### Expected behavior

Exception triggered immediately.

### Actual behavior

Nothing happens until typing another key or leaving insert mode.

**Comment by zeertzjq** [comment]
May be related to #9006.

**Comment by zeertzjq** [comment]
I just also found out that a `<Nop>` mapping can also break timers from triggering (same root cause).
```vim
:imap <C-J> <Cmd>call timer_start(1000, { _ -> execute("throw 'x'", "") })<CR>
:imap <C-K> <Nop>
```
Press `i<C-J>`, and then press `<C-K>` in less than one second, and the timer is not triggered until the next key.
