### ISSUE TITLE
write and quit (:wq) overwritten the PS1 on tty

### ISSUE THREAD

**Issue by youkwhd** [neovim/neovim#17265]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no, vim 8.2.4106

### Operating system/version

arch

### Terminal name/version

tty

### $TERM environment variable

linux

### Installation

Arch official repository (community)

### How to reproduce the issue

```sh
env -i TERM=linux "$(which nvim)"
```

### Expected behavior

<h6 id="foo-123"></h6>

when i tried to write and quit a file (using :wq not :w then :q after), the message after writing a file e.g. "init.vim 40L, 995C written" overwritten my PS1 line, which resolves into a PS1 that looks like:

```sh
[foo@bar ~]$ itten
```

this could be worsen if i had a minimal PS1:
```sh
~ $ nit.vim" 40L, 995C written
```

here's  a screenshot of write and quit behaviour on nvim:

> i ran nvim using tty, this was recorded using [asciinema](https://asciinema.org/)

![nvim :wq](https://i.imgur.com/s6XZLzQ.png)

however, when i use :w then :q, this problem doesn't occur. It'll behave normally.

![nvim :w then :q](https://i.imgur.com/igaJ0jT.png)

i have no problem when :wq using **vim**:

![vim :wq](https://i.imgur.com/F6qkPAZ.png) 

### Actual behavior

see: [expected behaviour](#foo-123)

**Comment by youkwhd** [comment]
### tried on a virtual machine (debian)

i also have tried it on several virtual machines like debian bullseye, nvim was installed using apt, the bug still present

![nvim on debian](https://i.imgur.com/KcAzOps.png)

**Comment by glacambre** [comment]
@youkwhd Your screenshots show that you use `st`. Using `TERM=linux` with st is wrong, you need to use `TERM=st-256color` instead.

**Comment by zeertzjq** [comment]
If I understood OP correctly, that's probably because OP could not do screen recording in getty.

**Comment by youkwhd** [comment]
@glacambre i did in fact used the terminal `st` to replay the tty session. That screenshot there was pre-recorded using [asciinema](https://asciinema.org/) (a terminal session recorder) or something equivalent like [ttyrec](https://www.linuxlinks.com/ttyrec/).

## here's another try on void:

![void tty_1](https://i.imgur.com/tllSJ35.png)
![void tty_2](https://i.imgur.com/7LIlxFV.png)

**Comment by zeertzjq** [comment]
I can reproduce this with bash. This also doesn't happen when using zsh or fish.

**Comment by erw7** [comment]
Fixing this is not difficult. Simply output `LF` in the first column of the last line before exiting the alternate screen. As a workaround, the following should be available.

```sh
PS1=\\033[K$PS1
or
PS1=$(tput el)$PS1
```

**Comment by youkwhd** [comment]
this issue seems like it has nothing to do with neovim, i occur the same problem with other softwares such as ncmpcpp, pulsemixer, etc.
