### ISSUE TITLE
LSP: Standard diagnostic code in the diagnostic structure

### ISSUE THREAD

**Issue by wookayin** [neovim/neovim#17260]
### Feature already in Vim?

No, it's about neovim API

### Feature description

I propose neovim's diagnostic structure (introduced in neovim 0.6.0+) should include `code` as a standard entry. This can be error/warning code from many LSP or linter implementations (such as eslint, pylint, flake8, etc.).

Currently, error codes are stored under either:
- (1) `diagnostic.user_data.lsp.code` (neovim's current way of handling this, see `:help diagnostic-table`) or 
- (2) `diagnostic.code` as a top-level entry (e.g., [null-ls.nvim#632](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/632)) which is "non-standard".

My proposal is to make `code` standarized and become a top-level entry in the diagnostic table.

### More information and context

Continuation from discussion https://github.com/jose-elias-alvarez/null-ls.nvim/issues/632#issuecomment-1026093907.

[The Diagnostic API defined in LSP](https://microsoft.github.io/language-server-protocol/specification#diagnostic) includes `code` (as well as `source`, `message`, `severity`, etc.) as a top-level entry. Neovim's diagnostic data structure does not, as per `:help diagnostic-table`.

```
A diagnostic is a Lua table with the following keys:                        
                                                                            
        bufnr: Buffer number                                                
        lnum: The starting line of the diagnostic                           
        end_lnum: The final line of the diagnostic                          
        col: The starting column of the diagnostic                          
        end_col: The final column of the diagnostic                         
        severity: The severity of the diagnostic vim.diagnostic.severity    
        message: The diagnostic text                                        
        source: The source of the diagnostic                                
        user_data: Arbitrary data plugins or users can add                  
```

When the API was introduced in neovim 0.6.0, `code` were not included as a standard field of the diagnostic table structure, but I believe this is worth including and there is no reason to exclude that. Error codes are very common in diagnostic and linters, and many existing plugins such as [trouble.nvim](https://github.com/folke/trouble.nvim) are displaying the error codes.

Typical LSP servers configured (but not all) through nvim-lspconfig would follow the `user_data.lsp.code` convention, as seen in a helper function [`diagnostic_lsp_to_vim`](https://github.com/neovim/neovim/blob/v0.6.0/runtime/lua/vim/lsp/diagnostic.lua#L92-L118). But some other diagnostic sources such as [null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim), not necessarily being aware of LSP, would want to use different namespaces. @jose-elias-alvarez, the author of null-ls.nvim proposed `user_data.null_ls` in jose-elias-alvarez/null-ls.nvim#632, but this would make use of the exposed error code quite complicated for the clients.

For instance, some plugins like [trouble.nvim](https://github.com/folke/trouble.nvim/blob/aae12e7b23b3a2b8337ec5b1d6b7b4317aa3929b/lua/trouble/util.lua#L177) will fail to extract the data because of the plugin-specific namespace. In addition, picking up the code information for custom diagnostic messages (e.g., `vim.diagnostic.config { float = { message = function(diagnostic) ... end } }`) will be also difficult unless `code` is standarized.

Any reasons why `code` were not included back then, and possible issues of this (potentially) breaking change? Thanks for your consideration.

/cc @jose-elias-alvarez @folke

**Comment by gpanders** [comment]
>Any reasons why code were not included back then

If I remember correctly the only concern was that we didn't want to saturate the main diagnostic structure with LSP-specific items. However, as you've pointed out `code` is not LSP specific, it's used by linters as well. So I think adding it to the top level is fine.

I would be happy to review a PR that does this. Some notes for such a PR:

1. The docs section you quoted that lists the fields of the diagnostic structure should be updated to add an `(*)` next to fields that are required for diagnostic producers (i.e. anything calling `vim.diagnostic.set`). These fields are `lnum`, `col`, and `message`. Optional fields are `code`, `end_lnum`, `end_col`, and `severity` (`bufnr` and `namespace` don't ever need to be set, these are only used when "reading" diagnostics).
2. We must preserve backward compatibility, which means we must continue to also populate `user_data.lsp.code` as well as the new top-level `code` attribute. Add a comment to the source code that indicates that usage of `user_data.lsp.code` is deprecated.

**Comment by mxteries** [comment]
I'm willing to try implementing this. It doesn't seem like anyone else is working on this at the moment but let me know otherwise
