### ISSUE TITLE
`<c-c>` causes `vim.on_key` to raise an error when calling `vim.fn` functions

### ISSUE THREAD

**Issue by RRethy** [neovim/neovim#17273]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+894-g561df3098

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 12.1

### Terminal name/version

kitty 0.21.0

### $TERM environment variable

xterm-kitty

### Installation

brew install --HEAD neovim

### How to reproduce the issue

`foo.lua`:
```lua
vim.on_key(function(key)
    -- vim.api.* functions don't cause an error
    print(vim.fn.mode())
end, nil)
```

```bash
nvim --clean foo.lua
:so %
:startinsert
`<c-c>`
```

### Expected behavior

```
Error executing  vim.on_key Lua callback: vim.lua:0: Error executing 'on_key' with ns_ids '2'                                                            
    Messages: Keyboard interrupt
stack traceback:
        [C]: in function 'error'
        vim.lua: in function <vim.lua:0>
```

### Actual behavior

I would expect no error to show. Should I be wrapping calls to `vim.fn` in `vim.schedule_wrap`?

**Comment by tjdevries** [comment]
yes, you need to schedule wrap them

**Comment by zeertzjq** [comment]
I think this should be changed.
