### ISSUE TITLE
nvim_buf_get_extmarks doesn't return extmarks that contain than the requested span

### ISSUE THREAD

**Issue by isovector** [neovim/neovim#17270]
### Neovim version (nvim -v)

NVIM v0.6.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

ArchLinux

### Terminal name/version

Running in neovide

### $TERM environment variable

xterm-256color

### Installation

Manjaro pacman

### How to reproduce the issue

Buffer contains:

> hello

Run

```
:let g:ns  = nvim_create_namespace('bug')
:call nvim_buf_set_extmark(0, g:ns, 0, 0, {"end_line": 0, "end_col": 4})
:echo nvim_buf_get_extmarks(0, g:ns, [0, 1], [0, 1], {})
```

### Expected behavior

Because the requested position is spanned by the `col` and `end_col` of the extmark, it should be returned: 

`[[1, 0, 0]]`

### Actual behavior

The extmark is not returned:

`[]`

**Comment by zeertzjq** [comment]
I think this should be an option of `nvim_buf_get_extmarks` to not break backward-compatibility.

**Comment by lewis6991** [comment]
This sounds like an outright bug. Any consumer that is dependent on this behaviour is broken IMO.

Is there something I'm missing?

**Comment by lewis6991** [comment]
Sorry @zeertzjq , I misunderstood the issue and your comment.

The extmark is being set to `(0,0)`, `(0,4)`, but `nvim_buf_get_extmarks` is requesting marks within `(0,1)`, `(0,1)`.

I think you're right and `nvim_buf_get_extmarks` should only return marks **fully within** the requested range.

However, when extranges get added, we will want the functionality to get marks that intercept a range, so I agree this should be an option.

**Comment by isovector** [comment]
What's the reasoning behind `nvim_buf_get_extmarks` should only return marks fully in the requested range? 

The original use case here is that Agda's syntax highlighting is controlled by the compiler, which additionally attaches go-to-definition destinations and other metadata for every token. I've created extmarks for each token to do the highlighting, and attached the metadata to a dictionary keyed by extmark id. But given the current implementation of `nvim_buf_get_extmarks`, go to definition only works if the cursor is on the first character of the token, since the behavior doesn't get extmarks that overlap with the requested range.

**Comment by lewis6991** [comment]
> What's the reasoning behind nvim_buf_get_extmarks should only return marks fully in the requested range?

Quite a technical one.

Extmarks are stored in a b-tree, which is an efficient data structure for searching elements. However, extmarks are stored in the b-tree in pairs, for the start and end. What `nvim_buf_get_extmarks(0, g:ns, [0, 1], [0, 1], {})` is really saying is: "look for extmarks starting at `[0,1]` and stop at `[0,1]`". If we were to change this to find all extmarks that intersect then we would need every call `nvim_buf_get_extmarks` to scan the **entire** structure, which is obviously not very efficient.

However, there are quite a lot of applications that want to know where extmarks intersect a certain region which is what https://github.com/neovim/neovim/pull/13243 plans to address.

**Comment by bfredl** [comment]
in #13243 this will be made available by setting a new "overlap" option on `nvim_buf_get_extmark`

**Comment by sesse** [comment]
It seems this doesn't actually work; even in the latest git snapshot, I get

`Invalid 'opts' key: 'overlap'`

I think maybe the option parsing was never hooked up to Lua.

**Comment by bfredl** [comment]
@sesse cannot reproduce. are you sure this is the latest snapshot of master (not anything 0.9)?

**Comment by clason** [comment]
And how do you install Neovim? (Make sure you don't have outdated runtimefiles from an older version lying around.)

**Comment by sesse** [comment]
I downloaded nvim-linux64.tar.gz from the snapshot page. I see now that it actually claims 0.9.5, which surprises me a lot, so I'll have another go and see what's happening.

**Comment by sesse** [comment]
Indeed, I had simply unpacked the wrong version. With v0.10.0-dev-2709+g00e9c6955, it works. Sorry, please disregard.
