### ISSUE TITLE
SIGWINCH is not honored, window does not resize itself correctly

### ISSUE THREAD

**Issue by reportaman** [neovim/neovim#17285]
### Neovim version (nvim -v)

v0.7.0-dev+1002-g59fa5f4ec

### Vim (not Nvim) behaves the same?

no, 8.2.4293

### Operating system/version

macOS 12.1

### Terminal name/version

iTerm2, 3.4.12

### $TERM environment variable

tmux-256color

### Installation

brew install nvim -s --HEAD

### How to reproduce the issue

Hard to reproduce, first open nvim in such a way that it does not occupy the entire terminal screen. In my case it happens with a combination of tmux+tmux-resurrect at times. Then find the PID of the tty and nvim running in it, I use htop. Finally send SIGWINCH to both tty and nvim. In my case it just messes up the nvim buffer, things look haywire.

### Expected behavior

Neovim should not open erratically such that it does not occupy the full size of tty it is opened in. Moreover, if it has opened like this, it should honor SIGWINCH and resize itself.

### Actual behavior

Neovim does not open to fully occupy the size of tty it is opened in. If it does open like this, it does not honor a SIGWINCH sent from another tty command line.

**Comment by glacambre** [comment]
Sounds close to https://github.com/neovim/neovim/issues/15044, https://github.com/neovim/neovim/issues/11330 .

**Comment by reportaman** [comment]
One observation: I ran ``:!tput cols`` and ``:!tput lines`` from within a messed up nvim session. It reported cols as ``80``, and lines as ``24``. When I close the nvim session and run the command in the same tmux pane, it reports the correct values of ``114`` for cols, and ``60`` for lines. This is even after I had sent SIGWINCH after a 2 second delay after nvim opened.

**Comment by reportaman** [comment]
Found where ``{80, 24}`` is coming from. From neovim documentation: https://neovim.io/doc/user/term.html#window-size, section ``Window Size``
```
==============================================================================

Window  size						*[window](https://neovim.io/doc/user/windows.html#window)-size*

On Unix systems, three methods are tried to get the [window](https://neovim.io/doc/user/windows.html#window) size:

- an ioctl call (TIOCGSIZE or TIOCGWINSZ, depends on your system)
- the environment [variables](https://neovim.io/doc/user/eval.html#variables) "LINES" and "COLUMNS"
- from the |[terminfo](https://neovim.io/doc/user/term.html#terminfo)| entries "lines" and "columns"

If everything fails a default size of 24 lines and 80 columns is assumed...
```

I wonder if checking for ``tput lines`` and ``tput cols``, and using it is a more robust way of finding the columns and lines.

As a side note, I am using ``zsh 5.8 (arm-apple-darwin21.1.0)`` as my default shell. Haven't tested with bash, as all my setup is with zsh.
