### ISSUE TITLE
nvim can't read vim's undo files

### ISSUE THREAD

**Issue by l29ah** [neovim/neovim#17301]
### Feature already in Vim?

Yes

### Feature description

NVIM v0.6.1, vim 8.2
nvim says: `E824: Incompatible undo file: foo`

**Comment by clason** [comment]
Yes, they are incompatible. Is there a compelling reason why you _need_ them to be compatible?

**Comment by l29ah** [comment]
I want to switch vim to nvim or even use both w/o having to lose years of my edit history.

**Comment by clason** [comment]
Sorry, that just won't be possible. I'm afraid you have to make a clean break of stick with Vim then.

**Comment by kantum** [comment]
What is so different about those new files? Is there no way to make a converter?

**Comment by sevmonster** [comment]
I was also curious about this. The fact that undo files are not compatible is not listed in [Vim_diff](https://neovim.io/doc/user/vim_diff.html) so it comes as a surprise to the user. I spent a lot of time searching to see what was and wasn't compatible, and what I could and couldn't use under Neovim.
