### ISSUE TITLE
Setting option viewoptions not work

### ISSUE THREAD

**Issue by xiaolitongxue666** [neovim/neovim#17304]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

8.2

### Operating system/version

macOS 12.1

### Terminal name/version

alacritty 0x11-dev

### $TERM environment variable

xterm 256

### Installation

brew install neovim

### How to reproduce the issue

I just change my config from vimrc to lua with packer ,  all configs work well expect option viewoptions not work

```lua
-- int.lua
vim.api.nvim_set_option('viewoptions', 'cursor,folds,slash,unix')
print(vim.o.viewoptions)
```

### Expected behavior

Everytime reopen file can locate the last edit place

![image](https://user-images.githubusercontent.com/35646108/152672746-bb408a03-4265-43c1-871b-69b4ab94a3f1.png)

### Actual behavior

Reopen file locate at the begin of file

**Comment by zeertzjq** [comment]
I cannot reproduce. Did you run `:mkview` properly?

**Comment by xiaolitongxue666** [comment]
@zeertzjq First, thanks you replay , here is my config lua code

```lua
-- utf8
vim.g.encoding = "UTF-8"
vim.o.fileencoding = 'utf-8'
-- jk移动时光标下上方保留8行
vim.o.scrolloff = 8
vim.o.sidescrolloff = 8
-- 使用相对行号
vim.wo.number = true
vim.wo.relativenumber = true
-- 高亮所在行
vim.wo.cursorline = true
-- 显示左侧图标指示列
vim.wo.signcolumn = "yes"
-- 右侧参考线，超过表示代码太长了，考虑换行
-- vim.wo.colorcolumn = "80"
-- 缩进4个空格等于一个Tab
vim.o.tabstop = 4
vim.bo.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftround = true
-- >> << 时移动长度
vim.o.shiftwidth = 4
vim.bo.shiftwidth = 4
-- 新行对齐当前行，空格替代tab
vim.o.expandtab = true
vim.bo.expandtab = true
vim.o.autoindent = true
vim.bo.autoindent = true
vim.o.smartindent = true
-- 搜索大小写不敏感，除非包含大写
vim.o.ignorecase = true
vim.o.smartcase = true
-- 搜索高亮
vim.o.hlsearch = true
-- 边输入边搜索
vim.o.incsearch = true
-- 使用增强状态栏后不再需要 vim 的模式提示
vim.o.showmode = false
-- 命令行高为2，提供足够的显示空间
vim.o.cmdheight = 2
-- 当文件被外部程序修改时，自动加载
vim.o.autoread = true
vim.bo.autoread = true
-- 在下次打开文件的时候光标位置
vim.api.nvim_command('set viewoptions=cursor,folds,slash,unix')
-- vim.api.nvim_set_option('viewoptions','cursor,folds,slash,unix')
-- vim.o.viewoptions = "cursor,folds,slash,unix"
-- vim.g.viewoptions = "cursor,folds,slash,unix"
-- 自动换行
vim.o.wrap = true
vim.wo.wrap = false
-- 行结尾可以跳到下一行
vim.o.whichwrap = 'b,s,<,>,[,],h,l'
-- 允许隐藏被修改过的buffer
vim.o.hidden = true
-- 鼠标支持
vim.o.mouse = "a"
-- 禁止创建备份文件
vim.o.backup = false
vim.o.writebackup = false
vim.o.swapfile = false
-- smaller updatetime
vim.o.updatetime = 300
-- 设置 timeoutlen 为等待键盘快捷键连击时间200毫秒，可根据需要设置
-- 遇到问题详见：https://github.com/nshen/learn-neovim-lua/issues/1
-- vim.o.timeoutlen = 200
-- split window 从下边和右边出现
vim.o.splitbelow = true
vim.o.splitright = true
-- 自动补全不自动选中
vim.g.completeopt = "menu,menuone,noselect,noinsert"
-- 样式
vim.o.background = "dark"
vim.o.termguicolors = true
vim.opt.termguicolors = true
-- 不可见字符的显示，这里只把空格显示为一个点
vim.o.list = true
vim.o.listchars = "space:·"
-- 补全增强
vim.o.wildmenu = true
-- Dont' pass messages to |ins-completin menu|
vim.o.shortmess = vim.o.shortmess .. 'c'
vim.o.pumheight = 10
-- always show tabline
vim.o.showtabline = 2


vim.api.nvim_exec([[ :mkview ]], false)

```

**Comment by zeertzjq** [comment]
You only run `:mkview` on startup, so it only saves cursor position on startup.

**Comment by zeertzjq** [comment]
If you want to restore cursor position every time you reopen a file without using `:mkview` and `:loadview`, see `:h last-position-jump`.

**Comment by xiaolitongxue666** [comment]
@zeertzjq I jsut save my config and reopen a file via nvim , but not work.

So  in you enviroment , just add '''vim.api.nvim_command('set viewoptions=cursor,folds,slash,unix')''' will work ?

**Comment by zeertzjq** [comment]
`'viewoptions'` is for `:mkview` and `:loadview` only. I think `:h last-position-jump` is what you want. To use it in Lua:
```lua
vim.cmd([[autocmd BufReadPost * if line("'\"") >= 1 && line("'\"") <= line("$") | execute "normal! g`\"" | endif ]])
```

**Comment by xiaolitongxue666** [comment]
> `'viewoptions'` is for `:mkview` and `:loadview` only. I think `:h last-position-jump` is what you want. To use it in Lua:
> 
> ```lua
> vim.cmd([[autocmd BufReadPost * if line("'\"") >= 1 && line("'\"") <= line("$") | execute "normal! g`\"" | endif ]])
> ```

Thanks a lot , you code work well !!! 

I need to read more about help document , i'll close this issue.

THANKE AGAIN~
