### ISSUE TITLE
Idea: Ability to "hide" windows from appearing in a window layout, but are still in the layout.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#1731]
Just an idea for the future, but allow windows to be hidden so they take up zero vertical and horizontal space (gutter and status line also hidden) but are still effectively in the layout. Windows can be unhidden all at once, and would be toggleable.

The practical use for this would be in layouts with many splits, each vertical divider and each status line add up and take up real estate that would be useful to have when viewing a subset of the windows in the layout, where even using <c-w>_ and <c-w>| to maximize the windows still leaves you with limited space due to the stacked status lines and vertical dividers.

In my following screenshot, you can see at the top and bottom multiple status lines taking up space that could instead allow more viewing space for the windows I'm interested in.

![](http://i.imgur.com/bc43qo7.jpg)

The ability to add the current window to the hidden pool, along with a toggle command, would be enough. A GUI could take things further and do things like allow the user to select multiple windows at once and add them to the hidden pool by communicating to neovim each window to hide one at a time.

F.e., I'd like to hide the windows marked with blue:

![](http://i.imgur.com/0H6icFl.jpg)

In the even further future, this could be improved to have multiple visibility groups, an the ability to move visibility groups into new tabs.

**Comment by justinmk** [comment]
Merging into https://github.com/neovim/neovim/issues/3933

**Comment by ivan-vilches** [comment]
What theme is that? looks nice. Thanks

**Comment by trusktr** [comment]
@ivan-vilches That's a customized version of base16-eighties, not released anywhere. 

Basically I was just doing something like this:

```viml
                    let g:terminal_color_0  = '#2e3436'
                    let g:terminal_color_1  = '#cc0000'
                    let g:terminal_color_2  = '#4e9a06'
                    let g:terminal_color_3  = '#c4a000'
                    let g:terminal_color_4  = '#3465a4'
                    let g:terminal_color_5  = '#75507b'
                    let g:terminal_color_6  = '#0b939b'
                    let g:terminal_color_7  = '#d3d7cf'
                    let g:terminal_color_8  = '#555753'
                    let g:terminal_color_9  = '#ef2929'
                    let g:terminal_color_10 = '#8ae234'
                    let g:terminal_color_11 = '#fce94f'
                    let g:terminal_color_12 = '#729fcf'
                    let g:terminal_color_13 = '#ad7fa8'
                    let g:terminal_color_14 = '#00f5e9'
                    let g:terminal_color_15 = '#eeeeec'

                    set background=dark
                    execute "silent! colorscheme base16-eighties"
                    highlight Comment guifg=#585858
                    highlight Normal guifg=#999999
                    "highlight TabLine guifg=#333333 guibg=#777777
                    "highlight TabLineSel guifg=#FA7F7F
                    highlight MatchParen gui=bold guibg=black guifg=limegreen
```

The commented parts I wasn't done with. It also only works in GUI mode, not in a terminal. I've been using NeoVim in terminal mode lately, but I'd like to get back to the GUI sometime.
