### ISSUE TITLE
Regular expresssions engine improvement.

### ISSUE THREAD

**Issue by kaiuri** [neovim/neovim#17333]
### Feature already in Vim?

No

#### Attention: This is only a suggestion and me making myself available for working on it, please feel free to critique or dismiss it. My intention is not pushing some Rust down Neovim. 

So, here me out. I was working on a way to parse PCRE syntax compatible regular expressions into Vim's own regular expression syntax. For context but cutting it short, I went for Rust's regex because, well, I'm a proud rustacean. After lots of brain damaging code digging and carving, asking other rustaceans for help and web stalking the original authors of Vim's Regex, it came to me that a simpler solution could be achieved mathematically - off with the failed parsers and lexers I wrote, be sure there were quite a few of those - through the following theoretical approach:

**Obs**: I've included a primer on the issue's bottom to get those interested but lacking formal basis to follow through and two simple code snippets for replication. Please forgive any typos as my ADHD makes it impossible for me to make sure of their absence.

1. Theorem: If an `NFA` recognizes `A` then `A` is a regular language.

2. Theorem: If `R` is a regular expression and `A=L(R)` then `A` is regular. Simply put, Every language describable with regular expressions is regular.

Proof: `R` being a regular expression, it can be so either by being [atomic] or [composite].

```text
* Case: R is atomic ::= if R is a single symbol then an NFA will reject anything other than it.
                        if R = an empty string or empty language, those are also regular.

* Case R is composite ::= Closure construction through concatenation,
                          union and star, also result in regular languages.
```

Then, after hacking the source code of Neovim and Vim, I've studied the algorithm for their new `NFA engine` which then occurred to me must be mathematically compatible through Nondeterministic Finite Automata as they're both formal regular languages. Therefore, after researching [Kleene](https://en.wikipedia.org/wiki/Kleene%27s_algorithm)'s algorithm and [Glushkov](https://en.wikipedia.org/wiki/Thompson%27s_construction)'s construction algorithm, it's implied that both are compatible at high-level intermediate representations `Hir`, aka NFA.

Concluding, transforming a Rust's (`ripgrep`'s) regex, formalized on the [regex_syntax](https://docs.rs/regex-syntax/latest/regex_syntax/) `crate` (library) into an [HIR](https://docs.rs/regex-syntax/latest/regex_syntax/hir/struct.Hir.html) and printing (thru the [Printer](https://docs.rs/regex-syntax/latest/regex_syntax/hir/print/struct.Printer.html) `struct`) it back out as a different, actually equivalent - regular expression bridges the gaps between the two syntaxes and this output would ideally be accepted by both machines(engines). I then ran some tests and it is indeed so, more, Vim would automatically switch engines to accommodate the expression derived from the HIR, sometimes explicitly reporting an `NFA engine` syntax typo on my part.

I'm packaging the solution into an app ([vrex](https://github.com/kaiuri/vrex)), but it was the implication of this success which got me here on the first place, that is, if there's interest, it's possible to actually replace - or add an opt out of - the old vimregex `NFA engine` with Rust's, through **FFI**, or even fully replace it, provided we implement some features like lookahead, etc or use Ripgrep [library](https://docs.rs/grep/latest/grep/) crate, shielding old plugins from breaking changes by using the old `NFA engine` as a bridge between incompatible patterns.

PS: I'll be working on that rewrite of the old engine, for my own leisure anyway though.

## Primer

Quick primer to help out on those interested but lacking theoretical background.

- Deterministic Finite Automata (**DFA**) is a 5-tuple `(Q, Σ, &, q_0,F)` where
  - `Q` is a finite set of states,
  - `Σ` is a finite set of alphabet symbols,
  - `&` is a transition function `&: Q×Σ → Q`,
  - `q0` is the start state,
  - `F` is a set of accepted states.
- Nondeterministic Finite Automata (**NFA**), think DFA but with infinite sets, that is, `&` is now defined as `&: Q×Σε → P(Q) === { R| ⊆ Q }`
- _String_: finite set of symbols in `Σ`
- _Language_: Set of strings.
- _Regular Language_: Let `M` be a machine and `L` a language, `L(M)` is a language of that machine if it is accepted by it.
- _Regular expressions_: A regular Expression `R` is a set of `L` languages that have the `Union`, `Concatenation` and `Star` operations defined within it.
- Closure Properties for Regular Languages: Set of mathematical behaviour shared among all regular languages.

Regular language acceptance examples:

```text
+--------------- DFA -----------------+-------------- NFA -------------------+
|   0                                 |   0---->---1---->----2--->-----3     |
| +---+                               |   a        |         |         |     |
| |   |      1                  0,1   | +->-+      |         |         |     |
| +-+-+  +--->----+           +-->--+ | |   |      a         |        a,ε    |
|   |    |        |    1      |     | | +-+-<  +--->----+    |      +-->--+  |
|   q1---+        +--->q2---> q3<---+ |   |    |        |    b      |     |  |
|        |        |                   |   q1---+        +--->q2---> q3    q4 |
|        +---<----+                   |        |        |                    |
|            0                        |        +---<----+                    |
|                                     |            b                         |
+--------------- DFA -----------------+-------------- NFA -------------------+
```

### Further reading:

- [Automata Theory](https://en.wikipedia.org/wiki/Automata_theory),
- [NFA](https://en.wikipedia.org/wiki/Nondeterministic_finite_automaton),
- [DFA](https://en.wikipedia.org/wiki/Deterministic_finite_automaton).

## Code

`main.rs`

```rust
#![deny(unused, unused_variables, unused_imports)]
use regex_syntax::{
    ast::parse::{self, Parser as AstParser},
    hir::{Error, Hir},
    Parser as HirParser, Result,
};

fn main() {
    let to_hir = |expr: &str| -> Result<Hir> {
        //TODO Build a parser to generate the most generic Hir possible
        use regex_syntax::Parser as HirParser;
        HirParser::new().parse(expr)
    };

    let from_hir = |hir: Hir| -> String { hir.to_string() };

    let is_ascii = |output: &str| -> bool { output.is_ascii() };
    let output = from_hir(hir);
    // Make sure to turn "very magic" on or escaping the special characters before using the output on Neovim
    if is_ascii(&output) {
        println!("{}", &output);
    } else {
        println!("{} impossible conversion.", &output);
    }
}
```

`Cargo.toml`

```toml

...

[dependencies]
regex-syntax = "0.6.25"
```

**Comment by clason** [comment]
Thank you for that detailed writeup; this is an interesting project to work on as a plugin, and I'm looking forward to checking it out when you're finished.

That being said, there is currently no plan or interest in adding any sort of Rust dependency to Neovim, let alone rewriting core parts of it.

**Comment by kaiuri** [comment]
> Thank you for that detailed writeup; this is an interesting project to work on as a plugin, and I'm looking forward to checking it out when you're finished.
> 
> That being said, there is currently no plan or interest in adding any sort of Rust dependency to Neovim, let alone rewriting core parts of it.

Thank you so much for your time and interest @clason . Happy you liked the writeup and project as plugin. Have a nice one, man 😄
