### ISSUE TITLE
Ability to add a description to vim.keymap.set

### ISSUE THREAD

**Issue by AckslD** [neovim/neovim#17356]
### Feature already in Vim?

No

### Feature description

The new `vim.keymap.set` is extremely useful, in particular how easy it is to map keys to `lua` functions. One downside which I realised is that it's harder to investigate what your current keys are actually doing. For example if I've set something like:
```lua
vim.keymap.set("n", "<leader>s", function() ... end)
```

If I then look at `:nmap <leader>s` I will see something like:
```
n  <Space>s * <Lua function 297>
```
Which doesn't give any indication of what the mapping does and makes looking up keymaps this way pretty useless.

Would it make sense to add the ability to give a custom optional description to the mapping? Such as:
```lua
vim.keymap.set("n", "<leader>s", function() ... end, {desc="My cool mapping"})
```

Which would show up for example in `:nmap` as:
```
n  <Space>s * <Lua function 297> (My cool mapping)
```

**Comment by clason** [comment]
Isn't that already possible? `nvim_set_keymap` supports the `desc` key in the `opts` table, and `vim.keymap.set` just calls that under the hood.

**Comment by clason** [comment]
Yep, just tested it, your example already works.

**Comment by AckslD** [comment]
Oh damn! I'm so sorry, I don't understand why I missed this when just reading the docs. I think I need some more coffee. Sorry for wasting you time!

**Comment by bryant-the-coder** [comment]
@clason , where can i find what is added into nightly? or at least explain the advamce stuff aboutwhat vim.keymap.set can do

**Comment by glacambre** [comment]
@bryant-the-coder `:h lua-keymap` should contain all the information you need about `vim.keymap` :)
