### ISSUE TITLE
Allow separate priority of `virt_text` entries in `nvim_buf_set_extmark()`

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#17366]
### Feature already in Vim?

No, Vim doesn't have extmarks

### Feature description

At the moment, in `opts` argument of `nvim_buf_set_extmark()` user can supply:
- `virt_text` as `A list of [text, highlight] tuples, each representing a text chunk with specified highlight`.
- `priority` as `a priority value for the highlight group`.

As there can be multiple highlight groups associated with extmark, it might be reasonable to allow adding priority to each of them. For example, with `[text, highlight, priority] tuples` API.

For context, here is my (quite narrow) use case. I implemented a functionality to display a line visualizing current indent scope ([mini.indentscope](https://github.com/echasnovski/mini.nvim#miniindentscope)). As I want it to also be visualized on empty lines (and extmarks can't be placed outside of text), I used approach from 'lukas-reineke/indent-blankline.nvim': add all extmarks over first column with appropriate text (whitespace prefix padding plus visualization symbol). With current extmark functionality whitespace padding and visualization symbol have same priority, which leads to either hiding all other extmarks under whitespace padding or visualization symbol under other extmarks.

**Comment by yyy33** [comment]
cool

**Comment by lewis6991** [comment]
Is this not possible with multiple extmarks?

**Comment by echasnovski** [comment]
> Is this not possible with multiple extmarks?

The main use case was to be able to place a single extmark at the beginning of line with all the text. Initial text serving as "invisible prefix" (and thus should have low priority) while next one is the "main text" (and thus with higher priority).

Having multiple extmarks is possible only if there is text near which it can be placed. This is a problem for empty lines.

This is partially solved by using `opts.virt_text_win_col` instead of using `col` directly, but this is not ideal because might need a recomputation on every horizontal window scroll.

That said, my use case in 'mini.indentscope' is no longer an issue (`opts.virt_text_win_col` is enough for me), so I personally don't really need this. Not sure if that is enough to close this.

**Comment by lewis6991** [comment]
I think this'll be hard to implement, and I think a solution using multiple extmarks would be preferable.

If someone else wants this then we can reopen it.
