### ISSUE TITLE
More official support for plugin tests

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#17367]
### Feature already in Vim?

No

### Feature description

It would be very nice to have some official guidelines with how plugin writers can write tests for their plugins. In particular, what I have in mind:
- A dedicated help file describing the suggested infrastructure needed to set up and run basic tests. Like which files should be put where, which command runs tests, etc.
- A dedicated Lua module with Neovim-specific assertions and helpers (like `vim.testing`), so plugin writer can test, for example, what exactly is shown on screen, etc. Maybe something like exported helpers from 'test/functional/'.

At the moment, all information about this topic seems to be a [plenary.test_harness](https://github.com/nvim-lua/plenary.nvim#plenarytest_harness) along with some custom solutions from plugin authros (ranging from quite basic to quite elaborated ones, like in [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim)).

I really wish adding new and running existing tests would be as easy as `vim.testing.add_test("Plugin works")` and `vim.testing.run_tests()`.

**Comment by clason** [comment]
As always, the question that needs to be addressed in such a feature request is "Why does this _need_ to be in core?" (and these should be _technical_ reasons, not "because it's better if it's official" or "more convenient!)

**Comment by echasnovski** [comment]
Main *technical* reason is for having assertions specific for Neovim's execution (like [screen state](https://github.com/neovim/neovim/blob/master/test/functional/ui/screen.lua); actually displayed colors, statusline, tabline, signcolumn; etc.) without needing to clone Neovim source code.

**Comment by clason** [comment]
So you're suggesting exposing `screen.lua` as a `vim.util.screen` module?

**Comment by echasnovski** [comment]
> So you're suggesting exposing `screen.lua` as a `vim.util.screen` module?

Maybe something like `vim.testing.screen`, with more or less friendlier user experience and along with other helpers.

> The problem here is that this (like most tests) requires `busted`. So exposing this makes `busted` a _runtime_ dependency rather than a build dependency like it is now. I don't think we want to do this.

Well, that is a problem, I agree. Not sure if it can be solved with some sort of compromise.

All I can say is that for me not having a more or less unified and straightforward way of writing tests for various behavior (custom statusline, tabline, auto-pairs, visualization with extmarks) led to not writing any tests at all. Having this in core might be an investment in overall stability of Neovim ecosystem.

**Comment by clason** [comment]
> All I can say is that for me not having a more or less unified and straightforward way of writing tests for various behavior (custom statusline, tabline, auto-pairs, visualization with extmarks) led to not writing any tests at all. Having this in core might be an investment in overall stability of Neovim ecosystem.

Unfortunately, that's not how this works: as long as you don't force people to write tests (which is obviously not possible), there will always be excuses not to write them. `plenary.busted` is the closest you'll likely get to an "official" Neovim plugin test harness. I'd recommend contributing to improving that instead.

An alternative course would be to try to use the approach of `plenary` to drop the `busted` dependency for Neovim's tests. If that were feasible, you'd have a stronger case for exposing the already existing testing infrastructure. (Writing a completely new one just for plugins is a much too hard sell.)

**Comment by clason** [comment]
And I just looked at `gitsigns`' tests -- those look pretty straightforward and make use Neovim's built-in test helpers just fine? I don't think it's going to get any better than that (although you might try asking Lewis nicely for a blog post on how he set them up).

Anything beyond that is basically shifting the burden for plugin tests from plugin authors to Neovim maintainers, which I don't think is reasonable.

**Comment by echasnovski** [comment]
Thanks for your insight and suggestions!

Although, I am still not comfortable closing this issue myself (mainly because I've seen that "official guidelines" for writing plugins and testing them can improve whole ecosystem; for example in R language), I totally respect the decision of Neovim Core on this matter.

**Comment by clason** [comment]
We can leave it open for a while to see what other team members think (especially @tjdevries as the main plenary dev), but I'd say the situation for Neovim is very different from that for R (much smaller team, hazy line between config and plugins, no centralized package repository (and _zero_ interest in creating one!), Lua being an independent language with its own ecosystem, ...)

**Comment by KillTheMule** [comment]
I'm not sure if I'm missing the point, but one can keep neovim as a git submodule and directly use its test infrastructure. I [wrote about it ](https://github.com/KillTheMule/KillTheMule.github.io/blob/master/test_plugins_from_neovim.md) (quite outdated by now I guess), and I still thinks that's the best way to be testing your lua plugins. Once set up, it's quite easy to write more tests, I think.

**Comment by echasnovski** [comment]
> I'm not sure if I'm missing the point, but one can keep neovim as a git submodule and directly use its test infrastructure. I [wrote about it ](https://github.com/KillTheMule/KillTheMule.github.io/blob/master/test_plugins_from_neovim.md) (quite outdated by now I guess), and I still thinks that's the best way to be testing your lua plugins. Once set up, it's quite easy to write more tests, I think.

That is nice, thank you! Couple of thoughts:
- I am not sure having `neovim` submodule in some user plugin is a good idea. It might be automatically pulled depending on plugin manager, which is not good. After all, it shouldn't be a *runtime* dependency for plugin, but only for test :)
- Using code from Neovim's own tests have a general feel of using unexported functions: might work right now, but there is no confidence that it will work in future.

**Comment by hrsh7th** [comment]
I'm using [vusted](https://github.com/notomo/vusted) and we can also use [plenary.nvim](https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/busted.lua).

I mostly don't have any complaints about these.

But one missing piece is async tests with consuming key-ahead (`vim.wait` will stop the key-ahead consumptions...)

**Comment by mfussenegger** [comment]
There's also https://github.com/nvim-lua/nvim-lua-plugin-template as a starter template for a plugin. It includes plenary for testing - including GHA workflows.


I think the only reason to include some sort of testing library in core is if we also utilize it in some portion of the neovim test suite. We could avoid some of the `exec_lua` dance in many cases.


Other than that, I don't think there is a compelling reason to include it. If you look at other programming languages, having external testing libraries is not a major impediment to prevent people from writing tests. In the case of Python people even tend to prefer an external one over the built-in testing library (`pytest` vs `unittest`).


That said - I think there's potential to improve the current lua-dev tooling situation. I'd really like to have some "run this individual test function and debug it" functionality from within neovim - but I currently also don't see that this would require more parts to be integrated into neovim core.

**Comment by echasnovski** [comment]
> I think the only reason to include some sort of testing library in core is if we also utilize it in some portion of the neovim test suite.

Probably, the main pain point that led to this issue was the (seemingly unnecessary) complications that go with the idea of making test that actually checks what is displayed on screen.

> No, that's not how you would do it: you'd clone the Neovim repo separately via CI (and as a plugin developer, you (should) have the sources available locally anyway).

Sure, get it. I am (at least at the moment) more focused on how to organize test running that is:
1. Complete enough (testing what *actually* is done or shown by Neovim). At the moment the best option seems to be cloning whole Neovim source code without certainty that it will keep the API of inner tests.
1. Straightforward enough to set up locally from zero (having potential contributors and future self in mind). At the moment the best option seems to involve 'plenary.nvim' and 'busted' (like in 'nvim-lua-plugin-template').

**Comment by shadmansaleh** [comment]
Screen tests for plugins would be quite nice. However I don't think it needs to be included in neovim. If plenary_test/vusted adds screen test support it will be enough for me .

**Comment by echasnovski** [comment]
As this seems to not have enough support, I'll close this.

**Comment by lewis6991** [comment]
As mentioned above, Gitsigns already does exactly this. Neovim already contains everything a plugin needs.

**Comment by echasnovski** [comment]
> As mentioned above, Gitsigns already does exactly this. Neovim already contains everything a plugin needs.

True, Neovim contains everything plugin needs, but not in "officially" exported way. One day tests might be reorganized without notice, leading to a very tiresome debugging.

After writing a whole bunch of tests with 'plenary.nvim' and custom helpers, I can say that the only thing truly missing in current Neovim plugin development world is indeed the screen tests. Like I would really like to test something along the lines of "this screen cell should be displaying this character with this highlighting".

**Comment by lewis6991** [comment]
>  True, Neovim contains everything plugin needs, but not in "officially" exported way. One day tests might be reorganized without notice, leading to a very tiresome debugging.

Build against a tag (... like Gitsigns).

> After writing a whole bunch of tests with 'plenary.nvim' and custom helpers, I can say that the only thing truly missing in current Neovim plugin development world is indeed the screen tests. Like I would really like to test something along the lines of "this screen cell should be displaying this character with this highlighting".

Already in Neovim.

It's not *officially supported*, but at the same time the core team already has a lot on their plate. It's good a well raising issues and asking for stuff, but someone **actually** needs to put in the work. If you want to champion this, then I'm sure the core team will be happy to review a well put together PR.

I've been using Neovim's test infrastructure for the entirety of Gitsigns development and have literally never had any issues.

**Comment by echasnovski** [comment]
> It's not _officially supported_, but at the same time the core team already has a lot on their plate. It's good a well raising issues and asking for stuff, but someone **actually** needs to put in the work. If you want to champion this, then I'm sure the core team will be happy to review a well put together PR.

I totally understand that, not blaming anyone at all.

For me it was unusual to not be able to test such basic concept purely because it is not deemed important enough. And I actually tried two times to understand how 'test/functional/ui/screen.lua' works but didn't get far in the timespan I had free (around half a day both times). Considerably more time is needed to understand how this works to transform into some well put together PR. Hope I'll have one in the future.

**Comment by clason** [comment]
> And I actually tried two times to understand how 'test/functional/ui/screen.lua' works but didn't get far in the timespan I had free (around half a day both times). Considerably more time is needed to understand how this works to transform into some well put together PR. Hope I'll have one in the future.

And that is exactly what all these requests boil down to, and why there is such a push back: You are asking the Neovim developers to expend additional, significant, effort just(!) to save you (generic you, as in "plugin developers") some time and/or effort in your own software development...
