### ISSUE TITLE
Is vim.diff(a, b, { result_type = "indices" }) producing wrong/corrupted chunks?

### ISSUE THREAD

**Issue by iago-lito** [neovim/neovim#17378]
### Neovim version (nvim -v)

`NVIM v0.7.0-dev+1063-ga7321e37a-dirty`

### Vim (not Nvim) behaves the same?

there is no `vim.diff` in `vim/vim`

### Operating system/version

`Linux etak 5.16.8-arch1-1 #1 SMP PREEMPT Tue, 08 Feb 2022 21:21:08 +0000 x86_64 GNU/Linux`

### Terminal name/version

`# GNOME Terminal 3.42.2 using VTE 0.66.2 +BIDI +GNUTLS +ICU +SYSTEMD`

### $TERM environment variable

`xterm-256color`

### Installation

local build from sources with +1 line addition to `src/nvim/diff.c`

### How to reproduce the issue

```sh
$ git clone https://github.com/neovim/neovim
$ cd neovim
$ nvim src/nvim/diff.c
```
.. add the following line at the top of `xdiff_out` function (line [3165](https://github.com/neovim/neovim/blob/a7321e37a75fff5c0048b0779cf91d504455d6f3/src/nvim/diff.c#L3162) in a7321e37a):
```c
static int xdiff_out(long start_a, long count_a, long start_b, long count_b,
                     void *priv)
{
  smsg("xdiff_out got chunk: [%li(%li)%li(%li)]", start_a, count_a, start_b, count_b);
// ...
```
compile with
```sh
$ make
```

Prepare two files `./file` and `./other` like in https://github.com/neovim/neovim/issues/17207#issue-1115596283.

Prepare minimal `./.vimrc` config file with:
```nvim
let g:diff_algorithm="histogram" " Change to compare various algorithms.

exec "set diffopt+=algorithm:".g:diff_algorithm

lua << EOF

  function buffer_to_string(bufnr)
      local content = vim.api.nvim_buf_get_lines(bufnr, 0, -1, false)
      return table.concat(content, "\n")
  end

  function display_vim_diff_chunks()
    local file = buffer_to_string(1)
    local other = buffer_to_string(2)
    local chunks = vim.diff(file, other, {
      result_type = "indices",
      algorithm = vim.g.diff_algorithm,
      })

    for _, c in ipairs(chunks) do
      print("vim.diff chunk: ["..table.concat(c, " ").."]")
    end
  end

EOF
```
Once everything is set, compare the chunks produced by `vim.chunk` to the chunks actually received by `xdiff_out` during internal diff:
```
$ VIMRUNTIME=runtime ./build/bin/nvim -u .vimrc -d file other
:lua display_vim_diff_chunks()
:messages
```

### Expected behavior

The chunks data displayed from `xdiff_out()` should be the same as the chunks data displayed from `display_vim_diff_chunks()`.

### Actual behavior

Here is what I'm getting instead:

With algorithm `myers` or `minimal`:
```
xdiff_out got chunk: [2(1)2(1)]    | vim.diff chunk: [3 1 3 1]
xdiff_out got chunk: [4(5)4(0)]    | vim.diff chunk: [5 5 4 0]
xdiff_out got chunk: [10(1)5(1)]   | vim.diff chunk: [11 1 6 1]
xdiff_out got chunk: [13(1)8(1)]   | vim.diff chunk: [14 1 9 1]
xdiff_out got chunk: [15(1)10(1)]  | vim.diff chunk: [16 1 11 1]
xdiff_out got chunk: [17(1)12(1)]  | vim.diff chunk: [18 1 13 1]
xdiff_out got chunk: [20(2)15(3)]  | vim.diff chunk: [21 2 16 3]
```

With algorithm `patience` or `histogram`:
```
xdiff_out got chunk: [2(0)2(6)]    | vim.diff chunk: [2 0 3 6]
xdiff_out got chunk: [4(2)10(1)]   | vim.diff chunk: [5 2 11 1]
xdiff_out got chunk: [7(1)12(1)]   | vim.diff chunk: [8 1 13 1]
xdiff_out got chunk: [11(11)16(2)] | vim.diff chunk: [12 11 17 2]
```

(came accross this while investigating a PR to #17210)

**Comment by lewis6991** [comment]
Your test doesn't apply the extra offsets that need to be applied: https://github.com/neovim/neovim/blob/master/src/nvim/lua/xdiff.c#L55

**Comment by iago-lito** [comment]
Okay. IIUC there exists several different representations of "chunks".. But are they named or reified somewhere within the program? For instance there are:
- __A.__ chunks like received by `xdiff_out`, with line numbers starting at 1, where `start_a` means *the first line within the chunk*.
- __B.__ chunks like emitted by `vim.diff`, with line numbers starting at 1, but where the value of `start_a` is altered depending on `count_a`.
- .. any other?

Is there any reason why `vim.diff` would output one type of chunk rather than the other(s?). What is the type of chunk expected to be produced by users if #17210 were to be implemented? In other terms: what exactly is the chunk type "for humans"? :)

From what you write, I understand that it should be __B.__, but then I would need to undo this [mimicking](https://github.com/neovim/neovim/blob/master/src/nvim/lua/xdiff.c#L55) before I forward the user chunks to `xdiff_out`, right? Should this translating logic __A ⇌ B__ be reified somewhere within the program to future-proof against possible future changes in either __A__ or __B__, or is it stable enough that I can just hardcode my own __B → A__ translation on my side?

**Comment by lewis6991** [comment]
> Is there any reason why vim.diff would output one type of chunk rather than the other(s?). 

It outputs the same indices that you would get if indices=false. AFAIK b is the only valid format that all tools use.

> What is the type of chunk expected to be produced by users if #17210 were to be implemented? In other terms: what exactly is the chunk type "for humans"? :)

b. The format used by xdiff_out isn't used by anything. xdiff_out is only one ov several method for getting hunks from xdiff, all other methods use the same format as vim.diff.

**Comment by lewis6991** [comment]
Closing this as there isn't an issue here, but will continue to reply to questions.
