### ISSUE TITLE
Sourcing a `:mksession` file does not respect `set shortmess+=A`

### ISSUE THREAD

**Issue by melkster** [neovim/neovim#17397]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1027-gf02a5a7bd

### Vim (not Nvim) behaves the same?

Yes, Vim 8.2.4106

### Operating system/version

Manjaro Linux x86_64

### Terminal name/version

Terminator 2.1.1

### $TERM environment variable

xterm-256color

### Installation

Arch User Repository (AUR)

### How to reproduce the issue

1. Create the following config file `test.vim`:
   ```vim
   set shortmess+=A
   ```
2. `nvim --clean`
3. `:w foo.txt`
4. `:mksession session.vim`
5. Keep this `nvim` session running and open a new terminal shell instance
6. (in new terminal shell): `nvim -u test.vim`
7. `:source session.vim`

### Expected behavior

Neovim respects `shortmess+=A` and does not give an error message.

### Actual behavior

Neovim gives an error message after sourcing `session.vim`:

```
Error detected while processing /home/melker/.config/nvim/session.vim:
line   14:
E325: ATTENTION
Found a swap file by the name "[...]/foo.txt.swp"
[...]
```

**Comment by rmagatti** [comment]
@melkster do you know if this is also an issue in vim/vim? If so, maybe creating a ticket there would be helpful?

**Comment by melkster** [comment]
@rmagatti I've now created an issue here: https://github.com/vim/vim/issues/10443
