### ISSUE TITLE
*IDEA* Folding customization option

### ISSUE THREAD

**Issue by aliev** [neovim/neovim#1739]
in search of a folding replacement I noticed a wonderful (?) patch. I would very much like to see this feature. I think this will do is not difficult but it would be very nice. patch example: https://groups.google.com/forum/#!msg/vim_dev/LdTv6vVGY7o/260hHkapQNUJ

**Comment by teto** [comment]
customization of fold chars is already possible via fillchars. As for chaning the way the column is displayed, it will be taken care of by some generic abstraction for columns (issues already exist for that), we dont want an option for every behavior. thus closing.
