### ISSUE TITLE
Cursorline not updating as expected in a specific condition

### ISSUE THREAD

**Issue by kyazdani42** [neovim/neovim#17395]
### Neovim version (nvim -v)

0.7 master (happens in 0.6 too)

### Vim (not Nvim) behaves the same?

don't have vim installed

### Operating system/version

linux (nixos) - but happens in macos apparently

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

xterm-256color

### Installation

neovim nightly flake

### How to reproduce the issue

`nvim -u NONE`
`:set cursorline`
write down (in multiple lines)
```
abcd
efghi
jklmn
opqrs
```
`:vsplit`
`:lua vim.api.nvim_win_set_cursor(1000, {4, 0})`
`:lua vim.api.nvim_win_set_cursor(1000, {1, 0})`

### Expected behavior

The cursorline in line 4 should be cleared

### Actual behavior

The cursorline is shown in line 4 and line 1

Note that if the window is scrolled when setting the cursorline, or the 2nd call to set_cursor sets the cursorline below the first one, it will behave properly.

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/api/window.c b/src/nvim/api/window.c
index fc7823a07..c182f65fb 100644
--- a/src/nvim/api/window.c
+++ b/src/nvim/api/window.c
@@ -117,7 +117,7 @@ void nvim_win_set_cursor(Window window, ArrayOf(Integer, 2) pos, Error *err)
   // make sure cursor is in visible range even if win != curwin
   update_topline_win(win);
 
-  redraw_later(win, VALID);
+  redraw_later(win, SOME_VALID);
 }
 
 /// Gets the window height
```

**Comment by seandewar** [comment]
Seems that the ruler isn't updated either. Might also be worth setting `w_redr_status` if the cursor moves?

**Comment by zeertzjq** [comment]
Perhaps the fix for <https://github.com/vim/vim/issues/9766> can be used to fix this.

**Comment by zeertzjq** [comment]
BTW, in Vim (when using `win_execute()`) this is intentional: <https://github.com/vim/vim/issues/9766#issuecomment-1039003419>
