### ISSUE TITLE
`nvim_buf_add_highlight` should be not byte-indexed, because it results to highlight errors

### ISSUE THREAD

**Issue by cpkio** [neovim/neovim#17401]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

vim does not have this

### Operating system/version

Windows x64

### Terminal name/version

ConEmu

### $TERM environment variable

none

### Installation

manually unpack

### How to reproduce the issue

Use `nvim-lint` for example: `vale` linter outputs glyph-column number, which is correct even for Unicode texts. But, when that column number is passed to `nvim_buf_add_highlight` function, it results in incorrect highlighting, because this function is byte-indexed, and Unicode for non-ascii is twice as long.

### Expected behavior

`nvim_buf_add_highlight` should be glyph- or character-based I suppose.

### Actual behavior

The real «errouneous» text and higlight are mismatched if the text is non-ascii (=twice as byte-long)

**Comment by bfredl** [comment]
Fix your plugin.

**Comment by clason** [comment]
Whatever generates the `diag`.

**Comment by cpkio** [comment]
@clason Basically you're saying NVIM now does not care about anything but ascii, and a plugin should parse the file it is sending to the linter, and recalculate linters output to pass correct column values to `vim.diagnostic`?

**Comment by zeertzjq** [comment]
It sound like the plugin not caring about anything but ASCII.

**Comment by clason** [comment]
No, I'm saying that Nvim cares about (multibyte) Unicode characters, and the way that it does this is by having a consistent byte-based handling. This can be improved, especially across the Vim C-code/Lua API boundary, but that's ongoing work. The point is that returning to character-based indexing is _not_ the way to do this.

And, yes, in this case it's the linter's (or "glue plugin's") job to generate byte-based indices, same as for LSP.

**Comment by bfredl** [comment]
@cpkio Correct. Nvim is not an AI which will figure out whatever definition of "character" an external too uses, so it requires the user of its API to put in the correct column values. Is there a LSP wrapper for your linter? It might happen to correctly configured already.

**Comment by cpkio** [comment]
@clason, @bfredl I understood your point, thanks for explanation.
