### ISSUE TITLE
Syntax for Structurizr is not support escape-sequence in string

### ISSUE THREAD

**Issue by yamada-wacul** [neovim/neovim#17413]
### Neovim version (nvim -v)

v0.7.0-dev+1055-g2db0a5207

### Vim (not Nvim) behaves the same?

yes, vim 8.2.4300

### Operating system/version

macOS 12.1

### Terminal name/version

iTerm2 3.4.15

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```
nvim --clean
:ru filetype.vim
:e workspace.dsl
i"foo\"bar"<esc>
:ru syntax/structurizr.vim
:echo synIDattr(synID(1, 7, 1), "name")
```

### Expected behavior

echo `sstring`

### Actual behavior

echo `` (empty)

**Comment by zeertzjq** [comment]
cc @venthur

**Comment by venthur** [comment]
the bugreport is a bit too cryptic for me, can you elaborate a bit what the problem is?
