### ISSUE TITLE
`add_user_command` should immitate `<f-args>` for lua functions

### ISSUE THREAD

**Issue by ObserverOfTime** [neovim/neovim#17419]
### Feature description

When a lua function is given to `add_user_command`, the `args` should be passed as a table.
Currently, they're passed as a string similarly to `<args>` and have to be parsed manually.

Alternatively, there could be an option that controls how they are passed.

**Comment by gpanders** [comment]
Is there some reason you can't just `vim.split` the args string on spaces?

**Comment by ObserverOfTime** [comment]
The arguments might contain spaces.

**Comment by lewis6991** [comment]
Does f-args handle args that contain spaces?

**Comment by gpanders** [comment]
Yes but that's also the case for using `<f-args>` no?

**Comment by muniter** [comment]
To do it in Lua you have to `vim.split(opts.args, "[^%\\] ")` so a space that doesn't have a `\` before it, but looks very weird with the other slash to escape the slash. Seems like a good addition.

**Comment by craigmac** [comment]
Maybe related, but I cannot call an autoload function with <args> passed to it. Here's the link on reddit where I asked for help: https://www.reddit.com/r/neovim/comments/syqb21/trouble_calling_an_autoload_from_lua_with_an/?utm_source=share&utm_medium=web2x&context=3. 

I couldn't find anything in issues here but this seems like the closest possible related thing.

**Comment by gpanders** [comment]
@craigmac Your issue seems unrelated. Can you open a new issue?
