### ISSUE TITLE
Allow `cterm` argument in `nvim_set_hl()` to be an empty table

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#17437]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1101-g3230b3148

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Ubuntu 20.04

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

1. `nvim --clean -u NONE`.
2. `:lua vim.api.nvim_set_hl(0, 'Comment', {foreground = 'blue', cterm = {}})`

### Expected behavior

Works the same as `:lua vim.api.nvim_set_hl(0, 'Comment', {foreground = 'blue'})`.

### Actual behavior

Gives a `E5108: Error executing lua [string ":lua"]:1: 'cterm' must be a Dictionary.` error.

**Comment by shadmansaleh** [comment]
You can use `vim.empty_dict()` instead of `{}` and it'll work the same . You're getting that error because api expects a dictionary. Because in lua dictionary and lists are same empty dictionary are assumed to be empty list. `vim.empty_dict()` returns a table with special meta method so it gets translated correctly to empty dictionary.

**Comment by echasnovski** [comment]
> You can use `vim.empty_dict()` instead of `{}` and it'll work the same . You're getting that error because api expects a dictionary. Because in lua dictionary and lists are same empty dictionary are assumed to be empty list. `vim.empty_dict()` returns a table with special meta method so it gets translated correctly to empty dictionary.

Well, `nil` is also possible, but that requires an extra check for emptiness if highlight arguments are computed programmatically.

**Comment by clason** [comment]
To be perfectly honest, this request sounds like the sole point is shifting the burden for that extra check from the plugin to Neovim -- which sounds mightily convenient (for the plugin dev), I have to admit, but not particularly compelling (to the Neovim dev).

My feeling is that it'd be the job of the plugin to just not create redundant keys.

**Comment by echasnovski** [comment]
> To be perfectly honest, this request sounds like the sole point is shifting the burden for that extra check from the plugin to Neovim -- which sounds mightily convenient (for the plugin dev), I have to admit, but not particularly compelling (to the Neovim dev).
> 
> My feeling is that it'd be the job of the plugin to just not create redundant keys.
> 
> (Note that you're using a Neovim API via Lua, not a Lua API, so stricter rules for argument types apply. In this case, it is explicitly documented in `lua.txt` that "empty table is empty list".)

Sure, if that is not something you think worth adding, no problem. For me it was an honest surprise that this was not allowed, so decided to create an issue. It was a surprise mainly because `nvim_set_hl(0, 'Comment', {})` is allowed, although the third argument is also documented to be `map`, same as `cterm`.

**Comment by clason** [comment]
> It was a surprise mainly because nvim_set_hl(0, 'Comment', {}) is allowed, although the third argument is also documented to be map, same as cterm.

Yeah, consistency is indeed a strong argument for changing this.

**Comment by bfredl** [comment]
Yes, this should be allowed. we already know what the type must be (a dict), so `{}` can only possibly mean "empty dict", so it should be accepted. `vim.empty_dict()` should only be needed when the type is truly unknown, like working with JSON/msgpack data.
