### ISSUE TITLE
Incorrect behavior of Y hotkey according to user manual

### ISSUE THREAD

**Issue by DukeOwlington** [neovim/neovim#17435]
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

Yes, vim 8.2.3741 behaves differently

### Operating system/version

Gentoo Linux

### Terminal name/version

konsole 21.08.3

### $TERM environment variable

xterm-256color

### Installation

portage package manager

### How to reproduce the issue

```
nvim
ianytext<ESC>hhYp
```

### Expected behavior

According to NeoVim user manual, I expected Y hotkey to copy whole line and paste it with line break, like this:
```
anytext
anytext
```

### Actual behavior

Instead it copies only text after the cursor and places it right where the cursor is, like this:
`anyteextxt`

Either user manual needs to be updated or this behavior is not correct.

**Comment by DukeOwlington** [comment]
@zeertzjq What makes you sure that it's a documentation related issue? For me it looks like a bug because behavior is different from VIM, but if NeoVim developers intended Y hotkey to work like this then yes, it's a documentation related issue in my opinion. For my standpoint it looks like it could be either one :eyes:

**Comment by zeertzjq** [comment]
`:h default-mappings`

**Comment by DukeOwlington** [comment]
Oh, I get it. So it looks like usr_04.txt needs to be updated. Maybe I can even update it my self and submit pull request :thinking:. Thank you :)
