### ISSUE TITLE
Windows nvim-qt clipboard is not shared when started with --server

### ISSUE THREAD

**Issue by rijenkii** [neovim/neovim#17436]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows Server 2012R2 (client), Artix Linux (server)

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

.zip from github releases (client), repo (server).

### How to reproduce the issue

1. Launch `nvim --listen 0.0.0.0:<PORT>` on a server;
2. Connect to the instance from a windows PC with `nvim-qt --server <IPADDR>:<PORT>`;
3. Execute `"+gp`.

### Expected behavior

Contents of windows clipboard are pasted.

### Actual behavior

Nothing is pasted.

**Comment by zeertzjq** [comment]
Hmm, I think you should report this to neovim-qt?

**Comment by rijenkii** [comment]
Somehow did not realise that it a separate project.
It seems like it's already reported there as equalsraf/neovim-qt#298, sorry for bothering.
