### ISSUE TITLE
Colorscheme is not applied in conditional

### ISSUE THREAD

**Issue by AbbasSrour** [neovim/neovim#17438]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1101-g3230b31486

### Vim (not Nvim) behaves the same?

I don't use it :p

### Operating system/version

Arch 

### Terminal name/version

kitty and neovide 

### $TERM environment variable

idk what is that

### Installation

Aur

### How to reproduce the issue

I don't know if the issue is only limited to colorschemes , but I have my colorscheme change based on the time of the day via:

```lua
M.setup = function()
	if time.hour > 7 and time.hour < 12 then
		require("user.colorscheme").rose_pine()
		vim.cmd([[
	try
	  colorscheme rose-pine
	  set background=light
	catch /^Vim\%((\a\+)\)\=:E185/
	  colorscheme default
	  set background=light
	endtry
	]])
	end
	if time.hour > 12 and time.hour < 21 then
		require("user.colorscheme").tokyonight()
		vim.cmd([[
	try
	  colorscheme tokyonight
	  set background=dark
	catch /^Vim\%((\a\+)\)\=:E185/
	  colorscheme default
	  set background=dark
	endtry
	]])
	end
	if time.hour > 21 and time.hour < 7 then
		vim.cmd([[
	try
	  colorscheme onedarker
	  set background=dark
	catch /^Vim\%((\a\+)\)\=:E185/
	  colorscheme default
	  set background=dark
	endtry
	]])
	end
end
```

After the update this doesn't work and reverts me to the default color scheme, I reverted back to NVIM v0.7.0-dev+1091-g3449405f38 and everything works fine. 

### Expected behavior

To change scheme based on time of the day.

### Actual behavior

Neovim ignores set scheme and reverts to the default one.

**Comment by clason** [comment]
Please reduce this code to the absolute **minimum** required to reproduce the issue (a simple `:colorscheme onedarker` should suffice, if your description is correct).

**Comment by AbbasSrour** [comment]
Weirdly enough couldn't get issue to reproduce after cleaning the cache, and reinstalling the the theme plugins.
