### ISSUE TITLE
Horizontal Screen tearing (with tmux)

### ISSUE THREAD

**Issue by Davincible** [neovim/neovim#17441]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1063-ga7321e37a7 Build type: RelWithDebInfo LuaJIT 2.0.5 Compilation: /sbin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/tmp/pamac-build-tyler/neovim-git/src/build/config -I/var/tmp/pamac-build-tyler/neovim-git/src/neovim-git/src -I/usr/include -I/var/tmp/pamac-build-tyler/neovim-git/src/build/src/nvim/auto -I/var/tmp/pamac-build-tyler/neovim-git/src/build/include Compiled by tyler@ANGELIQUE  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

-

### Operating system/version

5.15.19-1-MANJARO

### Terminal name/version

Kitty 0.24.2 + Tmux 3.2a

### $TERM environment variable

tmux-256color

### Installation

AUR

### How to reproduce the issue

nvim config: 
https://github.com/Davincible/dotfiles/tree/master/nvim

### Expected behavior

No screen tearing

### Actual behavior

![image](https://user-images.githubusercontent.com/25869544/154476326-cdc5715c-0d90-4e45-b118-e29ce1556ea0.png)

For a few weeks, I have been getting horizontal screen tearing now. I did not always behave like this, and I am not sure what caused it. Lately is has been particularly bad. 

I do experience it on different terminal emulators also, causing me to believe its not about the terminal, but rather an issue with Neovim itself, or the Neovim + Tmux combo.

Whenever I reset my background with wpgtk; `wpg -m`, it fixes all the screen tearing, and resets it back to normal, however then it reappears again after a bit.

I have my full configs of neovim and tmux in [here](https://github.com/Davincible/dotfiles)

Any ideas what could be causing this?

**Comment by zeertzjq** [comment]
It looks like a Unicode character width problem. Can you provide a fuller screenshot?

**Comment by dundargoc** [comment]
> https://github.com/Davincible/dotfiles/tree/master/nvim

I wouldn't call 5000 lines of code minimal. Are those five colorschemes really necessary to recreate the bug?

I couldn't recreate the bug by the way, and I also use manjaro, kitty and tmux.

**Comment by Davincible** [comment]
I have actually not been experiencing it lately, so I wasn't able to provide a screenshot.

I'm not sure what the issue is/was but after a few rebuilds it now seems to have gone away, so I'll just close it for now.


Will open again if it ever comes back.

Thanks for the attention

**Comment by zeertzjq** [comment]
The actual bug may be #17860.
