### ISSUE TITLE
LSP/Treesitter highlight priority change

### ISSUE THREAD

**Issue by jamestrew** [neovim/neovim#17456]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+893-gb455e0179

### Vim (not Nvim) behaves the same?

not sure as this appears to be a LSP/treesitter issue and I have no experience with either in vim

### Operating system/version

5.16.10-arch1-1

### Terminal name/version

kitty 0.24.2

### $TERM environment variable

tmux-256color

### Installation

build from source

### How to reproduce the issue

1. checkout `b455e0179`
2. use [this](https://gist.github.com/jamestrew/7ba588b8c956db8c4829e6784b09f448) to start neovim with `nvim -nu minimal_init.lua test.py`
3. ensure lsp and treesitter are functional (it took several relaunches of nvim)
4. paste into the `test.py` buffer
```python
@cool_decorator
def hello():
    print("hi mom")
```

### Expected behavior

Prior to #16963 (`b455e0179` - got from git bisect) the TS node with lsp diagnostics would utilize the diagnostics highlight colors.

Eg (using `f3193c7b5` - one commit prior to `b455e0179` using the same steps above):
![image](https://user-images.githubusercontent.com/66286082/154785075-1f418af7-9857-4640-aa76-24a3f3a7e724.png)

Having treesitter seems to make a difference. Without it, the highlighting behaviors are the same between the commits with the diagnostic highlight colors taking priority.
Taking out treesitter related stuff in `minimal_init.lua`:
![image](https://user-images.githubusercontent.com/66286082/154785205-fe254aaf-462b-4136-8233-88f170cddc31.png)

### Actual behavior

#16963 by @mjlbach appears to have touched some priority defaults for LSP highlighting and now:
![image](https://user-images.githubusercontent.com/66286082/154784918-72d78476-43e8-4153-a9d0-db4e0a26ffdd.png)

The TS highlighting colors seems to take priority over that of the diagnostics regardless of the order the highlights are set.

**Comment by clason** [comment]
You are only setting `cterm` colors. Could you try setting `termguicolors` and `guifg` as well?

**Comment by lewis6991** [comment]
Is this the same issue as #17358 ?

**Comment by clason** [comment]
Yes, I think so -- the `vim.highlight.range` call for `diagnostic.handlers.underline` is missing the `priority` key. 

(And the default of `50` probably _is_ too low and should be higher than treesitter's `100`.)

**Comment by clason** [comment]
Hmm, no, I can't reproduce this on my side -- I get underlines with and without treesitter (using gui colors).

**Comment by jamestrew** [comment]
Same results using `termguicolors` and `guifg`.
My last two screenshots are without and with TS respectively on `b455e0179`. The underlining does seem to work with and without TS. My issue is related more with the color. Prior to this commit, the color of the diagnostic highlights were used whereas after the commit, the TS highlight color appears to take priority. I'll clarify that in the original comment.

**Comment by clason** [comment]
Ah, I only set the underline color, not the text color for `DiagnosticUnderline` in my scheme.

**Comment by mjlbach** [comment]
@lewis6991 I'm pretty sure it is in the sense that before, we were relying on the order of applying extmarks which was fixed resulting in this . The fix is extremely simple, plugins just need to be careful to always use use a priority when using highlight.range (`nvim-treesitter` currently does not). I've increased the priority of the highlights so it should be good after we merge 17461.
