### ISSUE TITLE
ccls not working with clang on first line of .ccls config file

### ISSUE THREAD

**Issue by AshleighWilson** [neovim/neovim#17457]
### Neovim version (nvim -v)

NVIM v0.6.1

### Language server name/version

ccls version 0.20210330-11-g790daca4

### Operating system/version

Arch Linux

### Steps to reproduce using "nvim -u minimal_init.lua"

Also the same with the minimal_init.lua configuration (though I haven't re-recorded the screencast).

![ccls-error](https://user-images.githubusercontent.com/26031424/154792890-2c7b5ae3-60dc-4b9b-bd81-c4fa4927988c.gif)

### Expected behavior

LSP are diagnostics available. Log attached when clang is removed from .ccls.

### Actual behavior

LSP diagnostics are not available. Log attached when clang is on the first line of ccls.

### Log file

https://gist.github.com/AshleighWilson/d90c08bfc75e4715681fdfb6736edd69

**Comment by mjlbach** [comment]
I can't understand this issue report, if it's an issue isolated to `ccls`( which, as far as I can tell, it is), then the issue is likely with the upstream server, especially if you are configuring it with a `.ccls` config file which we have no role in parsing or conveying to the server.
