### ISSUE TITLE
Floating window title

### ISSUE THREAD

**Issue by adigitoleo** [neovim/neovim#17458]
### Feature already in Vim?

Yes, vim 8.2

### Feature description

It seems that the neovim floating window API doesn't support setting a window title.
From `:h popup_create-arguments` in vim:

```
title           Text to be displayed above the first item in the
                popup, on top of any border.  If there is no top
                border one line of padding is added to put the title
                on.  You might want to add one or more spaces at the
                start and end as padding.
```

Since floating window borders are now supported, I wonder if it would be possible to add a title string inside the border.

**Comment by clason** [comment]
Neovim floating windows are not popups; they're lower-level, and plugins are responsible for setting the contents (including a title if they so prefer). 

A higher-level "popup" API has been requested routinely (I can't find a duplicate here at the moment) and is being worked on in, e.g., https://github.com/nvim-lua/plenary.nvim#plenarypopup.

**Comment by adigitoleo** [comment]
Does this mean that the plan is to move border drawing to that higher level API as well? Or can the border API be considered stable enough for plugins to use?

**Comment by clason** [comment]
The Neovim API (anything starting with `nvim_`) has a very strict contract, so you can rely on it. There are no plans of removing the border option. (The difference to a title is that the border is "external" to the floating window and does not affect the contents.)

**Comment by bfredl** [comment]
if we make the winbar #17336 draggable maybe it can also work as the title.
