### ISSUE TITLE
vim.o.tags is not working

### ISSUE THREAD

**Issue by grezp** [neovim/neovim#17463]
### Neovim version (nvim -v)

v0.6.1

### Vim (not Nvim) behaves the same?

no,

### Operating system/version

CentOS 7.2

### Terminal name/version

Tmux / 3.2

### $TERM environment variable

screen-256color

### Installation

appimage

### How to reproduce the issue

Including additional tags from home directory such as:
`vim.o.tags = vim.o.tags .. ',~/tags/global-tags'`

does not understand the global-tags added.

### Expected behavior

`vim.cmd[[ set tags+=~/tags/global-tags ]]`

works as expected.

### Actual behavior

`:set tags?`

will print out the correct string. Both the `vim.o` and `vim.cmd` methods print the exacts output strings. However, when using `vim.o.tags` I get the following error:

`E426: tag not found: Symbol`

**Comment by seandewar** [comment]
It's due to `~` not being expanded to the home dir. See #15720.

For now, something like:
```lua
vim.o.tags = vim.o.tags .. ',' .. vim.fn.expand('~') .. '/tags/global-tags'
```
should work.
