### ISSUE TITLE
<C-O><C-L> in Insert mode inserts a literal ^L

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#17473]
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

No, Vim does not have the default `<C-L>` mapping

### Operating system/version

macOS 12

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

Homebrew

### How to reproduce the issue

`nvim --clean`

Insert some text.
Go to Normal mode.
Search for some text that is present in the file, using `/`.
The text will be highlighted.
Enter Insert mode.
Type `<C-O><C-L>`.

### Expected behavior

The highlighting is cleared, and you drop back into Insert mode.

### Actual behavior

The highlighting is cleared, and you drop back into Insert mode, but a literal `^L` gets inserted.

**Comment by zeertzjq** [comment]
A solution may be to use `normal! <C-L>` instead of appending `<C-L>`.
