### ISSUE TITLE
'NONE' is not a valid color

### ISSUE THREAD

**Issue by tiagovla** [neovim/neovim#17478]
### Neovim version (nvim -v)

0.7.0 commit g6a3acccd8

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch 5.15.24-1-lts

### Terminal name/version

Alacritty 0.8.0-dev

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```
nvim --clean
:lua vim.api.nvim_set_hl(0, "Normal", {bg="NONE"})
```

### Expected behavior

Transparent `Normal` background.

### Actual behavior

```
E5108: Error executing lua [string ":lua"]:1: 'NONE' is not a valid color
stack traceback:
        [C]: in function 'nvim_set_hl'
        [string ":lua"]:1: in main chunk```

**Comment by tiagovla** [comment]
I think this might have been introduced after https://github.com/neovim/neovim/commit/dc24eeb9febaa331e660e14c3c325fd0977b6b93.

**Comment by lewis6991** [comment]
Note that:

```lua
vim.api.nvim_set_hl(0, "Normal", {bg="NONE"})
```

is exactly equivalent to:

```lua
:lua vim.api.nvim_set_hl(0, "Normal", {})
```
