### ISSUE TITLE
nvim_buf_* api functions treat nil as equivalent to 0 (i.e. current buffer)

### ISSUE THREAD

**Issue by smackesey** [neovim/neovim#17474]
### Neovim version (nvim -v)

0.6.1 (release)

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 11.5

### Terminal name/version

iTerm2

### $TERM environment variable

xterm

### Installation

homebrew

### How to reproduce the issue

nvim --clean
:lua print(vim.api.nvim_buf_is_valid(nil))

### Expected behavior

I would expect this to throw an error, because the docs say that you should pass `0` for current buffer and don't mention `nil`.

### Actual behavior

The cmd above prints `true`.

In general it seems that all the `nvim_buf_*` functions treat `nil` equivalently to `0`. If this is intended behavior, it should be documented.

**Comment by mjlbach** [comment]
This is fixed on master, see https://github.com/neovim/neovim/pull/16745
