### ISSUE TITLE
Returning <Plug> mappings from functions

### ISSUE THREAD

**Issue by noib3** [neovim/neovim#17485]
### Neovim version (nvim -v)

NVIM v0.7.0-dev

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

NixOS 22.05

### Terminal name/version

alacritty 0.10.0

### $TERM environment variable

alacritty

### Installation

Built from source

### How to reproduce the issue

I'm not sure if this is a bug or the intended behaviour. I'm trying to make the following key mappings work:

```lua
-- Intended to be used in a plugin and exposed to the users
vim.keymap.set('i', '<Plug>(hello)', function() print('Hello there') end, { expr = true, silent = true })

-- User configuration
local print_hello = function()
  -- Placeholder for my own logic
  return true and '<Plug>(hello)' or ''
end
vim.keymap.set('i', 'h', print_hello, { expr = true, silent = true })
```

When I type `h` the literal `<Plug>(hello)` string is inserted, while I'd like the function `<Plug>(hello)` is mapped to to be executed instead. If I change

```lua
vim.keymap.set('i', 'h', print_hello, { expr = true, silent = true })
```
to
```lua
vim.keymap.set('i', 'h', '<Plug>(hello)', { silent = true })
```
then `print('Hello there')` is executed and I see the message printed out, but I also get this error:

![2022-02-21_10-23](https://user-images.githubusercontent.com/59321248/154926663-8dcd20b4-950e-43e9-97aa-b2f2d07dc644.png)

### Expected behavior

`h` executes `print_hello`, `print_hello` returns `<Plug>(hello)`, `<Plug>(hello)` executes `print('Hello there')` and I see `Hello there` in the message history.

### Actual behavior

In the first case `<Plug>(hello)` is not expanded further and it just gets inserted into the buffer, in the second one `Hello there` is printed but I also get an error.

**Comment by zeertzjq** [comment]
You need to add `remap = true`.

**Comment by noib3** [comment]
After adding `remap = true` `print('Hello there')` is executed, but I still get that `E5108: Error executing lua: Expected lua string` error.

**Comment by zeertzjq** [comment]
Do not add `expr = true` to the first mapping.

**Comment by noib3** [comment]
Thanks, now everything works. Btw, I thought that `expr = true` was always needed if the rhs of a mapping was a lua function. Is this not true in general or just for `<Plug>` mappings?

**Comment by zeertzjq** [comment]
No, `expr = true` is only for returning a string that is the result of the mapping.

**Comment by noib3** [comment]
Ah I see, that `Expected lua string` error makes sense now.

Maybe

> `expr = true` is only for returning a string that is the result of the mapping.

could be added to the help docs of `vim.keymap.set` or `nvim_set_keymap`?
