### ISSUE TITLE
vim.wo.scrolloff returns wrong values

### ISSUE THREAD

**Issue by mg979** [neovim/neovim#17482]
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Linux Debian 11

### Terminal name/version

xfce4-terminal-emulator

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

nvim --clean
:lua print(vim.wo.scrolloff)

### Expected behavior

It should say `0`

### Actual behavior

It prints `94427460387826` or numbers like this.

**Comment by zeertzjq** [comment]
Already fixed by #15996
