### ISSUE TITLE
autoload function call with an argument from inside nvim_add_user_command odd behaviour

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#17499]
### Neovim version (nvim -v)

0.7.0 commit g30c9c8815

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS 11.6.3

### Terminal name/version

kitty 0.24.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

nvim --clean

```vim
:!mkdir -p ~/.local/tmp/nvim-bugreport/autoload
:cd ~/.local/tmp/nvim-bugreport

:edit ~/.local/tmp/nvim-bugreport/usercommand.lua
```

In there, put:

```lua
vim.api.nvim_add_user_command("Redir", function(cmd)    
  vim.fn['utils#Redir'](cmd.args)          
end, { nargs = 1 })
```

And save, for example `:write`, then source the file with `:source %`

For the autoload function do:

```
:edit autoload/utils.vim
```

And in there put:

```vim
function! utils#Redir(cmd) abort
  echom 'Received: ' .. a:cmd
  let output = execute(a:cmd)
  botright split +enew
  setlocal nobuflisted nonumber norelativenumber buftype=nofile bufhidden=wipe noswapfile
  nnoremap <buffer> q :bwipeout!<CR>
  call setline(1, split(output, "\n"))
endfunction
```

Save, `:write`, and then source it, `:source %`

Call it via vimscript to see it works with:

```vim
:call utils#Redir("ls")
```

Close the scratch window with `q`.

Now call the same function using lua from command-line to test:

```vim
:lua vim.fn['utils#Redir']("ls")
```

You see another scratch window appear with the same buffers listed.
Close it again it `q`

Now try calling the command we create in the usercommand.lua file:

```vim
:Redir
```

You should get a `E471: Argument required`, now try:

```vim
:Redir "ls"
```

Another scratch window will open and you should see `Received: "ls"` echo'd out, but this time the scratch window is empty. It should contain the same buffer listing we saw when we ran called `:lua vim.fn['utils#Redir']("ls")`.

To get around this I've instead used, in usercommand.lua define this at the bottom, save and then source it:

```lua
vim.api.nvim_add_user_command("Redir", "call utils#Redir(<args>)", { nargs = 1 })
```

Now you can call `:Redir "ls"` and it works but isn't very idiomatic lua, and I can't do things like inspect what the args are in the table with a lua function. 

### Expected behavior

Calling `:Redir "ls"` produces the same output and when called manual via `:lua vim.fn['utils#Redir']("ls")`

### Actual behavior

Our lua command defined as:

```lua
vim.api.nvim_add_user_command("Redir", function(cmd)
  vim.fn['utils#Redir'](cmd.args)
end, { nargs = 1 })
```

Opens a scratch window but does not add any content to it.

**Comment by zeertzjq** [comment]
I think you should the remove the double quotes. Use `:Redir ls` instead.

**Comment by craigmac** [comment]
`:Redir ls`

gives:

```
E121: Undefined variable: ls
E116: Invalid arguments for function utils#Redir
```

Have you tried it and got it to work? What am I missing?

**Comment by zeertzjq** [comment]
`:Redir ls` for the Kua one only.
