### ISSUE TITLE
<Plug> expr maps in vim.keymap.set

### ISSUE THREAD

**Issue by dtomvan** [neovim/neovim#17495]
### Neovim version (nvim -v)

v0.7.0-dev+5920-gf5e3c772b

### Vim (not Nvim) behaves the same?

no, neovim specific

### Operating system/version

Arch Linux 5.16.9-arch1-1

### Terminal name/version

st 0.8.3

### $TERM environment variable

xterm-256color

### Installation

AUR neovim-git

### How to reproduce the issue

* `nvim --clean`
* 
```
:inoremap <Plug>PrintHello; <cmd>lua vim.notify("Hello, World")<cr>
:imap <c-k> <Plug>PrintHello;
i<c-k><esc> " works
:iunmap <c-k>
:lua vim.keymap.set('i', '<c-k>', function() return '<Plug>PrintHello;' end, { expr = true })
i<c-k> " doesn't work
```
### Expected behavior

- Does the `vim.notify("Hello, World")`
- "Hello, World" appears in echo area

### Actual behavior

- "<Plug>PrintHello;" is typed
This doesn't happen with normal remaps, such as:
`vim.keymap.set('i', '<c-k>', function() return '<c-r>' end, { expr = true })`

**Comment by zeertzjq** [comment]
You need to add `remap = true`.

**Comment by dtomvan** [comment]
Oh, I guess vim.keymap.set has nore by default. In contradict to :map.

**Comment by clason** [comment]
In this case yes; this is explicitly documented in `:h vim.keymap.set()`:
> • remap: (boolean) Make the mapping recursive.
                   This is the inverse of the "noremap" option from
                    |nvim_set_keymap()|. Default `true` if `lhs` is
                    a string starting with `<plug>`
                    (case-insensitive), `false` otherwise.
