### ISSUE TITLE
html.vim breaks matching feature in php.vim under certain conditions

### ISSUE THREAD

**Issue by sdondley** [neovim/neovim#17496]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

macos 12.2

### Terminal name/version

iterm 3.5.15

### $TERM environment variable

xterm-256color

### Installation

brew

### How to reproduce the issue

Got this line:

add_post_meta($this->cmr_id, 'intro_paragraph', 'Hello');

With:

```
add_post_meta($this->cmr_id, 'intro_paragraph', 'Hello');
                                 ^ cursor here
```
Hitting '%' key jumps to opening paren as expected.

But with:

```
add_post_meta($this->cmr_id, 'intro_paragraph', 'Hello');
                 ^ cursor here
```
Nothing happens. If I remove the $, it works.

See https://vi.stackexchange.com/questions/36865/jumping-to-open-paren-with-doesnt-work-when-open-paren-followed-by-and-curs/36867#36867

### Expected behavior

% should jump to opening paren 

### Actual behavior

does not jump to opening paren.

**Comment by clason** [comment]
This looks like a problem with the bundled runtime files, which we take straight from Vim. Please report it at vim/vim; if it gets fixed there, we will port the fix as part of our runtime file updates.
