### ISSUE TITLE
Assigning $HOME from lua or setenv() does not work

### ISSUE THREAD

**Issue by Kyuuhachi** [neovim/neovim#17501]
### Neovim version (nvim -v)

v0.6.1

### Vim (not Nvim) behaves the same?

~Not applicable; vim does not have lua~ Yes

### Operating system/version

Arch Linux (5.16.9-arch1-1)

### Terminal name/version

MATE Terminal (1.26.0-1)

### $TERM environment variable

xterm-256color

### Installation

`pacman -S neovim`

### How to reproduce the issue

```vim
:echo expand("~")
/home/xxx

:let $HOME = "1"
:echo expand("~")
1

:call setenv("HOME", "2")
:echo expand("~")
1

:lua vim.env.HOME = "3"
:echo expand("~")
1
```

### Expected behavior

All three assignments should have the same effect.

### Actual behavior

Only the `let $HOME` variant affects functions such as `expand`. (`echo $HOME` is affected however.)

`let $HOME` is [special-cased](https://github.com/neovim/neovim/blob/90a43e846d96255b35338e95b5841f913ce2c657/src/nvim/eval.c#L1867-L1875) to update a few internal cache variables, but the other methods [are not](https://github.com/neovim/neovim/blob/726ec7fb17aa8a86b1c2c9adc4c6abfcb350d3a7/src/nvim/eval/funcs.c#L9277) (didn't find where the lua one is implemented).

**Comment by zeertzjq** [comment]
For the `setenv()` case, Vim behaves the same.

**Comment by zeertzjq** [comment]
<https://github.com/vim/vim/commit/7714231bb5b15f7c85453f3945c108478de1d08a> will fix this, but it depends on a previous Vim9 patch.
