### ISSUE TITLE
LSP doesn't gray out unused C code under #ifdef

### ISSUE THREAD

**Issue by nabaco** [neovim/neovim#17508]
### Neovim version (nvim -v)

0.6.1

### Language server name/version

clangd 13.0.0

### Operating system/version

Ubuntu 18.04.1

### Steps to reproduce using "nvim -u minimal_init.lua"

Changes to minimal_init.lua:
```diff
--- minimal_init.lua    2022-02-23 18:05:26.105870744 +0200
+++ min 2022-02-23 18:02:47.391836046 +0200
@@ -21,6 +21,7 @@
     {
       'wbthomason/packer.nvim',
       'neovim/nvim-lspconfig',
+      'nvim-treesitter/nvim-treesitter'
     },
     config = {
       package_root = package_root,
@@ -65,8 +66,8 @@
   end

   -- Add the server that troubles you here
-  local name = 'pyright'
-  local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
+  local name = 'clangd'
+  --local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
   if not name then
     print 'You have not defined a server name, please edit minimal_init.lua'
   end
```
Create compile_commands.json database for the C project you're working on. E.g:
```json
[
    {
        "arguments": [
            "gcc",
            "-DTEST_MACRO"
        ],
        "directory": "/home/nabaco/",
        "file": "test.c"
    }
]
```
Enter a C file that contains an `#ifdef`. E.g:
![image](https://user-images.githubusercontent.com/38861757/155364838-066111db-0f15-4aa3-8091-3919ce519e6b.png)
Notice that the block that under the `#ifdef` is highlighted all the same regardless of the existence of the define.
Enabling TreeSitter doesn't change the behavior (`:TSEnableAll highlight` and `e %`).

To compare, if I replace the `#ifdef` with `#if 0`, this works:
![image](https://user-images.githubusercontent.com/38861757/155365058-9d531428-07cc-438f-9dfb-fb4c5bfec884.png)
The uncompiled is in a different uniform color.
In fact, TreeSitter breaks this default behavior, though that is a different issue.

### Expected behavior

I expect code that is excluded from compilation due to a define to be grayed out. This behavior already exists for code under `#if 0`.
I see that the language server is aware of the defines and knows this code is not part of the compilation. Go to definition works correctly in all cases (given there is a correct compile_commands.json).

### Actual behavior

All the code has the same highlighting regardless of its defines.

### Log file

https://gist.github.com/nabaco/5147b555329e87b6a98accb000550637

**Comment by theHamsta** [comment]
See https://github.com/neovim/neovim/pull/15723 which will add support for semantic tokens but won't do any highlighting. See https://github.com/theHamsta/nvim-semantic-tokens for a plugin that would set highlight groups with the mentioned PR merged.

**Comment by mjlbach** [comment]
See @theHamsta's response. There is already an open feature request for semantic tokens (which IMO is not really what this issue report is about, but would be the only thing LSP adjacent that could be done).
