### ISSUE TITLE
Break CJK lines correctly

### ISSUE THREAD

**Issue by ZhiyuanLck** [neovim/neovim#17504]
### Feature already in Vim?

Vim 8.2.0901

### Feature description

It has been mentioned in #10077 , and there have been an upstream [patch 8.2.0901](https://github.com/vim/vim/commit/e52702f00322c8a8861efd0bd6a3775e685e5685) that fixed the issue.

**Comment by clason** [comment]
That patch has been ported in https://github.com/neovim/neovim/pull/13145 (October 2020) -- you can just search for the patch number in Github.

**Comment by dundargoc** [comment]
I'm not sure this should be closed. I think the issuer means that this problem still exists despite that patch being imported.

**Comment by clason** [comment]
Well, then we need a much better explanation _what_ is not working with the patch merged (reproducing steps with `nvim --clean` and ideally master, expected behavior, minimal behavior, screenshots etc.) The issue template is there for a reason.

**Comment by ZhiyuanLck** [comment]
@dundargoc well, it is my fault. I solve it by add the `m` flag to `formatoptions`. But it does take me some time to find how to set it correctly.
