### ISSUE TITLE
Allow a variance of `vim.lsp.buf.code_action()` where 1st option is automatically selected

### ISSUE THREAD

**Issue by chunleng** [neovim/neovim#17514]
### Feature description

I have recently migrated from coc to neovim's lsp and I really like it a lot.

Coming from coc.nvim, I tried to recreate `coc-fix-current` but failed to, because `vim.lsp.buf.code_action()` does not provide a way to select an action while calling the function.

Is it possible to have code_action to accept an argument to select the index or just having a "selectFirst" boolean argument?

Thank you!

**References:**
The document for coc
https://github.com/neoclide/coc.nvim/blob/0a8033065e8a5bce175dcabb12bf08808c353c1c/doc/coc.txt#L1455

There seems to be similar discussion and it ended up in kind of a hacky solution.
https://stackoverflow.com/questions/67988374/neovim-lsp-auto-fix-fix-current

**Comment by mjlbach** [comment]
It's not first action that you want (there is no guaranteed ordering), but the code action marked isPreferred:

```
	/**
	 * Marks this as a preferred action. Preferred actions are used by the
	 * `auto fix` command and can be targeted by keybindings.
	 *
	 * A quick fix should be marked preferred if it properly addresses the
	 * underlying error. A refactoring should be marked preferred if it is the
	 * most reasonable choice of actions to take.
	 *
	 * @since 3.15.0
	 */
	isPreferred?: boolean;
```

**Comment by chunleng** [comment]
That sounds even better!

**Comment by fredrikekre** [comment]
I started working on this and have a `vim.lsp.buf.preferred_code_action()` function working. However, I am wondering what would be the preferred behavior when there are multiple preferred actions? The [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeAction) doesn't seem to suggest there can only be one, and in the case of Neovim, there can be multiple attached servers which may return preferred actions anyway. I guess the options are:
 1. Error
 2. Query the user, just like `code_action()` does already
 3. Apply the first and re-request actions to check if there are still preferred actions available after the first edit

Since I would guess many (at least I) would like to use `preferred_code_action()` to automatically apply fixes, both 1. and 2. seems like bad options, but 3. doesn't seem ideal either.

Thoughts?

**Comment by mjlbach** [comment]
I don't think it should be a separate function, but a flag to standard code action helper.

My two  suggestions would be:

* preferred_only -> apply preferred action

or:

* action_filter -> function that allows user to automatically choose a code action or fallback behavior

**Comment by fredrikekre** [comment]
Alright, thanks for the input. I will make those changes and put up a PR.

**Comment by chunleng** [comment]
Thank you for the work on this issue.

Coc seems to implement it using option 3.
https://github.com/neoclide/coc.nvim/blob/70f11e074f45bc1bed1c17e3b0c2cf687f5582b6/src/handler/codeActions.ts#L126-L133

I thought maybe sharing the experience from coc will help to explain my use case better. In ESLint, there are many times where all the code action comes together in a single line (js lint + prettier for example), and having all the preferred action handled is a time-saver. The objective of this function is in my opinion, a way to quickly resolve lint errors while working on a piece of code.

**Comment by mjlbach** [comment]
FWIW I do not think this is the correct behavior because, as stated, there is no significance to the first code action in the current protocol

**Comment by chunleng** [comment]
I think we are past the first code action discussion. I am totally on the boat on the preferred action method.

When @fredrikekre suggested option 3, I think he meant to iteratively apply the preferred action.
On closer inspection of coc, the developers also iteratively applied the preferred action. In their case, they named the preferred action "Quickfix" (ref: https://github.com/neoclide/coc.nvim/blob/70f11e074f45bc1bed1c17e3b0c2cf687f5582b6/src/handler/codeActions.ts#L127 )

**Comment by mjlbach** [comment]
What do you mean iteratively apply the preferred code action? Shouldn't there only be one preferred per request/response pair?

**Comment by chunleng** [comment]
From the design of the function `vim.lsp.buf.code_action`, it is possible to have multiple code actions at a particular position
https://github.com/neovim/neovim/blob/a18c9ba2dab6e122e6fecd2353a0568f52d6c80c/runtime/doc/lsp.txt#L972-L974

Quoting from @fredrikekre :

> However, I am wondering what would be the preferred behavior when there are multiple preferred actions? The [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeAction) doesn't seem to suggest there can only be one, and in the case of Neovim, there can be multiple attached servers which may return preferred actions anyway.

**Comment by mjlbach** [comment]
That's not the question, the isPreferred tag description in the protocol states:
```
 	/**
	 * Marks this as a preferred action. Preferred actions are used by the
	 * `auto fix` command and can be targeted by keybindings.
	 *
	 * A quick fix should be marked preferred if it properly addresses the
	 * underlying error. **A refactoring should be marked preferred if it is the
	 * most reasonable choice of actions to take.**
	 *
	 * @since 3.15.0
	 */
	isPreferred?: boolean;

```

Emphasis mine, I think the implication of the protocol is there should only be marked one isPreferred action, so there is not a question of multiple preferred actions.

**Comment by fredrikekre** [comment]
> When fredrikekre suggested option 3, I think he meant to iteratively apply the preferred action.

Yes.

> On closer inspection of coc, the developers also iteratively applied the preferred action. In their case, they named the preferred action "Quickfix"

Right, you can already request a specific action type, like quickfix, with the existing API: `code_action({only = 'quickfix'})`. So with the proposed functionality here you would implement a "apply quickfix" as `preferred_code_action({only = 'quickfix'}, apply_preferred = true)` (or whatever the API ends up like).

> What do you mean iteratively apply the preferred code action? Shouldn't there only be one preferred per request/response pair?

> [...] it is possible to have multiple code actions at a particular position [...]

> That's not the question, the isPreferred tag description in the protocol states: [...]


To clarify what I meant in https://github.com/neovim/neovim/issues/17514#issuecomment-1103951933: even if the protocol suggests there can only be one preferred action (which I don't agree that must be the case and it is not clear from the spec you quote) there can, in Neovim, be multiple servers giving you actions.

I can imagine a case where you have the server giving two errors at the same location, with a preferred fix each for both of them, for example. It could then make sense to apply the first preferred one, the re-request to see if there are still more preferred actions at the same spot. This seem to be what coc.nvim does if I understand the code there correctly.

And again, for Neovim, it could be the case that both server A and server B are attached, and have preferred actions at the same spot, which gives a similar situation.


Now, I think that in the vast majority of cases, if I request 'quickfix' actions, there will only ever be a single preferred action returned, so this discussion might not be very relevant, but it seems nice to be able to have a command for "apply all (quickfix) actions at this position", like coc.nvim.

**Comment by mjlbach** [comment]
Saying it is the "most" reasonable implies not plural. If it intended to refer to multiple good actions it would have said so, but feel free to open an issue upstream at the protocol. The protocol is somewhat an implementation dicated spec anyways.

There's not a good way to apply code actions simultaneously. One code action may (and likely will) invalidate others by altering the buffer state, including the line position of the code action. I don't think the coc implementation is handling multi-server code action joining. I wouldn't support a PR that tries to re-request a code action at some point until all isPreferred code actions are exhausted, but that sounds like a potential small plugin.

**Comment by mjlbach** [comment]
I think, if its not already opened upstream, it would also be worth formalizing an "apply all preferred quickfix commands" upstream in the protocol. Some language servers implicitly do this via formatting requests, but I imagine some things (I think missing imports is a commonly marked preferred request) would be separate. Additionally a fundamental limitation of an "apply all quickfix" with the current protocol is it's restricted to the current cursor position, since code actions are only offered when passed a specific location.
