### ISSUE TITLE
nvim in a pipe

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1751]
use-cases regarding nvim on the "right side" of a pipe:
- [writing to stdout on exit](http://www.reddit.com/r/vim/comments/24ju8p/vidir_a_tool_to_rename_files_with_vi/ch8k9vh?context=3)
- [vimsed](http://www.reddit.com/r/vim/comments/2c47p2)
- [piping stdin to a nvim server](http://www.reddit.com/r/vim/comments/2qlb95) (different concept, but related)

Emacs also does not have this feature: http://lists.gnu.org/archive/html/emacs-devel/2014-07/msg00094.html

[pipe viewer for visualizing pipes](http://www.ivarch.com/programs/pv.shtml)

- Avoid the Vim limitation [mentioned here](http://stackoverflow.com/a/16753568/152142) (LF vs CRLF output)?

**Comment by fwalch** [comment]
Kind of related:

`yes | vim -c "helptags ++t ." -c quit` will give `Vim: Warning: Input is not from a terminal`, but works. `yes | nvim -c "helptags ++t ." -c quit` just hangs. This is a [problem](https://github.com/rmarquis/pacaur/blob/22c00a3d05f6504b44dfbc2f3cbd6ab1291e3c9c/pacaur#L825) when installing neovim with pacaur on Arch Linux, as it causes the helptags generation to hang.

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/7679 and related patches.

**Comment by lihsai0** [comment]
> writing to stdout on exit

Can you show me a demo of this?

I am trying this to clean my git branches with confirmation, but not work.

``` shell
git branch -vv | grep ': gone]' |  grep -v '\*' | awk '{ print $1; }' | nvim | xargs git branch -d
```

**Comment by erw7** [comment]
> Can you show me a demo of this?

Please try using the `-Es` as follows.

```
git branch -vv | nvim -Es -c 'g!/: gone]/d' -c 'g/^*/d' -c '%s/^\s\+\([^ ]\+\).*/\1' -c '%print' | xargs git branch -d
```

**Comment by lihsai0** [comment]
@erw7 Thanks for your reply!

It “works”. However, what I want is I can entry the nvim normal mode to confirm which branches will be deleted.

And, it will be great if I can edit the list to set which branches should be deleted.

**Comment by erw7** [comment]
@lihsai0 I think you can do what you want by doing the following:

```
git branch -vv | grep ': gone]' |  grep -v '\*' | awk '{ print $1; }' | nvim
:w !xargs git branch -d
:q!
```

**Comment by lihsai0** [comment]
@erw7 Yes! It's helpful! Thank you~
