### ISSUE TITLE
nvim: symbol lookup error: nvim: undefined symbol: ts_query_cursor_set_match_limit

### ISSUE THREAD

**Issue by LeisureLinux** [neovim/neovim#17520]
### Neovim version (nvim -v)

0.6.1-3

### Vim (not Nvim) behaves the same?

no. 8.2.3582

### Operating system/version

Ubuntu 2204  Kernel: 5.15.0-22-generic

### Terminal name/version

Gnome Terminal/3.43.90

### $TERM environment variable

screen-256color

### Installation

apt install neovim

### How to reproduce the issue

I am on zpool/zfs, the same OS, same apt install, no such issue on non-zfs file system. 
Here is strace nvim output:

execve("/usr/bin/nvim", ["nvim"], 0x7fff8c1f8340 /* 107 vars */) = 0
brk(NULL)                               = 0x55c00c32c000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffca1804c10) = -1 EINVAL (Invalid argument)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc58a336000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=175329, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 175329, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fc58a30b000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/liblua5.1-luv.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p\263\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=168456, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 170240, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc58a2e1000
mprotect(0x7fc58a2ea000, 122880, PROT_NONE) = 0
mmap(0x7fc58a2ea000, 90112, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x9000) = 0x7fc58a2ea000
mmap(0x7fc58a300000, 28672, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1f000) = 0x7fc58a300000
mmap(0x7fc58a308000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7fc58a308000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libuv.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=198744, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 202448, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc58a2af000
mprotect(0x7fc58a2b6000, 167936, PROT_NONE) = 0
mmap(0x7fc58a2b6000, 126976, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7000) = 0x7fc58a2b6000
mmap(0x7fc58a2d5000, 36864, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7fc58a2d5000
mmap(0x7fc58a2df000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2f000) = 0x7fc58a2df000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libmsgpackc.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340!\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=34808, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 36880, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc58a2a5000
mprotect(0x7fc58a2a7000, 24576, PROT_NONE) = 0
mmap(0x7fc58a2a7000, 16384, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fc58a2a7000
mmap(0x7fc58a2ab000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7fc58a2ab000
mmap(0x7fc58a2ad000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7000) = 0x7fc58a2ad000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libvterm.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300!\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=68400, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 70392, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc58a293000
mprotect(0x7fc58a295000, 57344, PROT_NONE) = 0
mmap(0x7fc58a295000, 40960, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fc58a295000
mmap(0x7fc58a29f000, 12288, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xc000) = 0x7fc58a29f000
mmap(0x7fc58a2a3000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xf000) = 0x7fc58a2a3000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libtermkey.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\2004\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=47312, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 52552, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc58a286000
mprotect(0x7fc58a289000, 32768, PROT_NONE) = 0
mmap(0x7fc58a289000, 20480, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7fc58a289000
mmap(0x7fc58a28e000, 8192, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8000) = 0x7fc58a28e000
mmap(0x7fc58a291000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa000) = 0x7fc58a291000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libunibilium.so.4", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\203\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=79944, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 81936, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc58a271000
mmap(0x7fc58a279000, 20480, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8000) = 0x7fc58a279000
mmap(0x7fc58a27e000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xd000) = 0x7fc58a27e000
mmap(0x7fc58a282000, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x10000) = 0x7fc58a282000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc58a26f000
openat(AT_FDCWD, "/usr/local/lib/libtree-sitter.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240Q\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=190800, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 177280, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc58a243000
mprotect(0x7fc58a247000, 155648, PROT_NONE) = 0
mmap(0x7fc58a247000, 131072, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7fc58a247000
mmap(0x7fc58a267000, 20480, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x24000) = 0x7fc58a267000
mmap(0x7fc58a26d000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x29000) = 0x7fc58a26d000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=944648, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 942360, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc58a15c000
mmap(0x7fc58a16c000, 507904, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x10000) = 0x7fc58a16c000
mmap(0x7fc58a1e8000, 364544, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8c000) = 0x7fc58a1e8000
mmap(0x7fc58a241000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe5000) = 0x7fc58a241000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libluajit-5.1.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=547632, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 545800, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc58a0d6000
mmap(0x7fc58a0dd000, 413696, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7000) = 0x7fc58a0dd000
mmap(0x7fc58a142000, 94208, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6c000) = 0x7fc58a142000
mmap(0x7fc58a159000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x83000) = 0x7fc58a159000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\337\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 48, 848) = 48
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\tJ-\205\367.\211=\f\25\246h\22\325\35T"..., 68, 896) = 68
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2220064, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 2260144, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc589eae000
mmap(0x7fc589eda000, 1658880, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2c000) = 0x7fc589eda000
mmap(0x7fc58a06f000, 344064, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c1000) = 0x7fc58a06f000
mmap(0x7fc58a0c3000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x215000) = 0x7fc58a0c3000
mmap(0x7fc58a0c9000, 52400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fc58a0c9000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=125488, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 127720, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fc589e8e000
mmap(0x7fc589e91000, 94208, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7fc589e91000
mmap(0x7fc589ea8000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a000) = 0x7fc589ea8000
mmap(0x7fc589eac000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1d000) = 0x7fc589eac000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc589e8c000
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc589e89000
arch_prctl(ARCH_SET_FS, 0x7fc589e89740) = 0
set_tid_address(0x7fc589e89a10)         = 985291
set_robust_list(0x7fc589e89a20, 24)     = 0
rseq(0x7fc589e8a0e0, 0x20, 0, 0x53053053) = 0
mprotect(0x7fc58a0c3000, 12288, PROT_READ) = 0
mprotect(0x7fc589eac000, 4096, PROT_READ) = 0
mprotect(0x7fc58a241000, 4096, PROT_READ) = 0
mprotect(0x7fc58a159000, 8192, PROT_READ) = 0
mprotect(0x7fc58a26d000, 4096, PROT_READ) = 0
mprotect(0x7fc58a282000, 12288, PROT_READ) = 0
mprotect(0x7fc58a291000, 4096, PROT_READ) = 0
mprotect(0x7fc58a2a3000, 4096, PROT_READ) = 0
mprotect(0x7fc58a2ad000, 4096, PROT_READ) = 0
mprotect(0x7fc58a2df000, 4096, PROT_READ) = 0
mprotect(0x7fc58a308000, 8192, PROT_READ) = 0
writev(2, [{iov_base="nvim", iov_len=4}, {iov_base=": ", iov_len=2}, {iov_base="symbol lookup error", iov_len=19}, {iov_base=": ", iov_len=2}, {iov_base="nvim", iov_len=4}, {iov_base=": ", iov_len=2}, {iov_base="undefined symbol: ts_query_curso"..., iov_len=49}, {iov_base="", iov_len=0}, {iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 10) = 83
exit_group(127)                         = ?
+++ exited with 127 +++

### Expected behavior

no error

### Actual behavior

error as subject.

**Comment by LeisureLinux** [comment]
Oh, BTW, it worked with snap install without issue.

**Comment by clason** [comment]
Your tree-sitter library is too old. The "official" builds use 0.20.4.

**Comment by clason** [comment]
Try building from source to see if this is a problem with Neovim itself or the distribution build.
