### ISSUE TITLE
Enable `nvim -q /dev/stdin` to read quickfix list from stdin

### ISSUE THREAD

**Issue by devjgm** [neovim/neovim#17523]
### Feature already in Vim?

Yes. Vim 8.2 has it

### Feature description

It's common to run shell commands that output `file:line` format (such as from `grep -n`), which is easily consumed by a quickfix list. It would be nice to be able to pipe that command output to nvim and have it open right away in a quickfix list. For example:

## Desired feature that doesn't work today
```
$ grep -nr fooo | nvim -q /dev/stdin
```
or even more succinctly
```
$ grep -nr fooo | nvim -q -
```

When I run the above command (`nvim -q /dev/stdin`), the input is displayed in a buffer for editing, and the quickfix list is empty.

**Comment by mxngls** [comment]
Not as clean as the first one, but until a a fix is added, that changes how input from `stdin` is read when supplying the `-q` option, the following works as well:

```bash
rg --vimgrep 'preventClick' | nvim -c 'cb | copen'
```

**Comment by n8henrie** [comment]
Very handy @mxngls, thank you!

Expanding for readability and closing the empty buffer:

```console
$ rg --vimgrep foo | nvim -c 'cbuffer | copen | bdelete! 1'
```
