### ISSUE TITLE
Alacritty + Neovim issue with background rendering

### ISSUE THREAD

**Issue by helderburato** [neovim/neovim#17521]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 11.6.2

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

screen-256color

### Installation

Installed via brew

### How to reproduce the issue

You can use my `nvim` configuration colors that are published at the following link:
https://github.com/helderburato/dotfiles/blob/main/nvim/.config/nvim/

Specific colors configuration:
https://github.com/helderburato/dotfiles/blob/main/nvim/.config/nvim/lua/hbb/colors.lua

Loading colors into `init.lua`: https://github.com/helderburato/dotfiles/blob/main/nvim/.config/nvim/lua/hbb/init.lua#L1

And after that, loads `init.lua` in `init.vim`: https://github.com/helderburato/dotfiles/blob/main/nvim/.config/nvim/init.vim#L27

----

Note: This issue started today, and I didn't change anything in my config, just updated my plugins.

### Expected behavior

I would like to have the same background color as my terminal emulator.
![SCR-20220225-fet](https://user-images.githubusercontent.com/862575/155705162-96fa1997-b94c-43e8-969d-00039042e212.png)

### Actual behavior

You can see in detail with the following images:
![SCR-20220225-fet](https://user-images.githubusercontent.com/862575/155705210-b2f8f972-e3c3-4ece-a927-a4729d248dcb.png)
![SCR-20220225-ffr](https://user-images.githubusercontent.com/862575/155705214-d26dad70-bcf6-4de5-808c-86109aceded9.png)

**Comment by smartrejames** [comment]
Same here, I solved it by deleting a folder named `.termxxx` (can't remember) under home directory,
and seems related to Alacritty more than Neovim,  #https://github.com/alacritty/alacritty/issues/5907

**Comment by helderburato** [comment]
Worked like a charm! Thanks @smartrejames 

As you mentioned, I deleted the brew version with `brew uninstall alacritty` and download `.dmg` version from https://github.com/alacritty/alacritty/releaseshttps://github.com/alacritty/alacritty/releases.

After that, I installed version `v0.10.1` and the theme came back to life.

**Comment by ranelpadon** [comment]
@smartrejames Thanks for the tip. There's a new `~/.terminfo` folder indeed that was installed with `alacritty` symlinks:
<img width="274" alt="Screen Shot 2022-03-01 at 2 13 39 PM" src="https://user-images.githubusercontent.com/4292088/156115376-b415339d-370f-4e9d-97ec-f50e4f03ce1f.png">

need to exit `tmux` session (if running) and restart `alacritty` though for it to have effect. Cheers

**Comment by helderburato** [comment]
I tried the steps you mentioned @ranelpadon, but it isn't working, is it needed to delete the `~/.terminfo`?

**Comment by helderburato** [comment]
I installed the `Alacritty` using `brew` again to try your approach @ranelpadon, the problem persists. 

After that, I deleted the `~/.terminfo`, killed `tmux` session, and restarted `Alacritty`, it has the correct background again. :)

**Comment by ranelpadon** [comment]
Right, for some reason I forgot to include/emphasize that I deleted that `~/.terminfo` folder. Updated my comment above. Cheers :)

**Comment by helderburato** [comment]
No problem, thanks for commenting about it. @ranelpadon
