### ISSUE TITLE
Graphical Nvim?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [neovim/neovim#17534]
### Feature already in Vim?

Yes

### Feature description

* it seems that nvim doesnt have a graphical mode right in the box [itself], 
* and I read this [related-projects#gui] page, and none of these seem to be reliable either
* so, i think having a builtin graphical mode will really help me learn nvim faster
* the default one included with vim is fine too, it just require slight improvent to its default font size

[itself]: https://user-images.githubusercontent.com/19423063/155858823-62369a56-d03b-4afa-a5d7-090b6a59583f.png
[related-projects#gui]: https://github.com/neovim/neovim/wiki/Related-projects#gui

----
### Tangential discussion topic:
The gvim has an extremely neat feature that i have never seen in any software before, i'd like to listen to your thoughts on that as well:
1. run `gvim -u NONE` 
(found it via this trail: <-- **vimtutor.bat**:_45:27_ <-- "vimtutor" or "vim tutor" <-- start menu MS win)
2. open any menu option
3. see the list has a scissors item at top of the list --> click that item
4. the list has now become a floating dialog 😱 

Demo vid (play @1.75X - doable from within browser)

https://user-images.githubusercontent.com/19423063/155859687-c095c5c6-36c1-4ed9-8611-9c7765c31ea2.mp4

**Comment by yashpalgoyal1304** [comment]
oops, also : https://github.com/neovim/neovim/issues/511

**Comment by zeertzjq** [comment]
Take a look at <https://github.com/neovim/neovim/wiki/Related-projects>

**Comment by yashpalgoyal1304** [comment]
@zeertzjq i checked some of that, like i said in the description, none of them looked reliable. do you have any specific recomendation from them?

**Comment by clason** [comment]
Just try them out. People seem to be using them just fine.
