### ISSUE TITLE
BufNewFile doesn't work

### ISSUE THREAD

**Issue by mg979** [neovim/neovim#17548]
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

no, it works

### Operating system/version

Linux Debian 11

### Terminal name/version

xfce4-terminal-emulator

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

nvim --clean
au BufNewFile * echom 'newfile'
edit newfile

### Expected behavior

`newfile` appears in `:messages` output

### Actual behavior

no output in `:messages`, autocommand doesn't work.

**Comment by zeertzjq** [comment]
See <https://github.com/neovim/neovim/wiki/FAQ#calling-inputlist-echomsg--in-filetype-plugins-and-autocmd-does-not-work>.

**Comment by mg979** [comment]
I see. But it's not only about `shortmess` here.

In my vimrc I have:

```vim
augroup template_auto
    au!
    au BufNewFile,BufReadPost * lua require'template.expand'.load_default()
augroup END
```
It doesn't work unless I put those lines after:

```vim
filetype on                     " Enable file type detection
filetype plugin on              " Enable loading the plugin files for specific file types
filetype indent on              " Load indent files for specific file types
```

Maybe it's lua calls that don't work unless `filetype` is enabled?
