### ISSUE TITLE
Add `group` and `event` to nvim_get_autocmds

### ISSUE THREAD

**Issue by hkupty** [neovim/neovim#17549]
### Feature already in Vim?

No

### Feature description

Following up on #14661 after brief conversation on matrix, it does feel like we're missing `event` and/or `group`(as a string) depending on the parameters given to `nvim_get_autocmds`. For example, if one requests all autocmds for a plugin/group, it is not clear when those autocmds will trigger:
![image](https://user-images.githubusercontent.com/2695819/156026645-50a952f1-029a-4977-a4d1-41807b9b5c7f.png)
![image](https://user-images.githubusercontent.com/2695819/156026683-1657cd31-3273-47f2-964e-32a1620f2d2c.png)

The same is true if you ask only the `event`:
![image](https://user-images.githubusercontent.com/2695819/156026847-8775da1a-4bb5-439b-a487-bdff5f41158d.png)
![image](https://user-images.githubusercontent.com/2695819/156026882-dfd5ffda-b319-4503-ac6e-33d482ad45cf.png)

Note that for non-lua commands it becomes obvious (accidentaly) because of the references to their own plugins.

The idea then would be to make the return value more complete so it could be presented to the end-user as a complete chunk of information regardless of the parameter given to `nvim_get_autocmds`.

**Comment by clason** [comment]
Could you give a self-contained example somebody else can reproduce? (As a codeblock, not an image, so we can copy&paste...)

**Comment by hkupty** [comment]
Sure!
```lua
  vim.api.nvim_create_augroup({name = "nvimux"})
  vim.api.nvim_create_autocmd{
    group = "nvimux",
    event = "TabLeave",
    pattern = "*",
    callback = function() print("do something") end
  }
end
```

**Comment by clason** [comment]
So the missing `event` looks like a bug; I think (but am happy to be corrected) that the `group` id instead of name is by design since that's what the API works with (although the `create_autocommand` takes a string instead of an id, which is a -- convenient -- inconsistency).

**Comment by clason** [comment]
Yup, `event` is straight-out missing from https://github.com/neovim/neovim/blob/6732cd9e57bf39d1a0f5c4fa08fa54c1561f2d2f/src/nvim/api/autocmd.c#L198-L253

Want to make a PR? 😁
