### ISSUE TITLE
Allow `nvim_create_augroup` to clear only buffer aucommands

### ISSUE THREAD

**Issue by bellini666** [neovim/neovim#17554]
### Feature already in Vim?

No

### Feature description

With the current implemented lua autocmds api, there's no way to clear only the autocmds for a specific buffer.

For example, I register autocmds like this when attaching a LSP server:

```lua
if client.resolved_capabilities.document_formatting then
  vim.cmd([[
    augroup lsp_document_format
      autocmd! * <buffer>
      autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync(nil, 1500)
    augroup END
  ]])
end
```

The `autocmd! * <buffer>` makes sure that it will clear only the buffer's autocmds for that group, not all autocmds for all buffers.

**Comment by tjdevries** [comment]
@bfredl do you think `nvim_clear_autocmd` and `nvim_del_autocmd` can be two different API calls? `nvim_del_autocmd` just takes one argument, an `id`. Then `nvim_clear_autocmd` can take a variety of parameterrs?

Or should I change `nvim_del_autocmd` to take a variety of options, one of them being ID? In general, it seems like `nvim_del` just takes an ID. I am open to suggestions.

**Comment by tjdevries** [comment]
Other alternative is we can also add `clear` option to `nvim_create_autocmd` to clear anything that matches the provided params. This might not be the worst idea. It makes creating the autocmd idempotent.

**Comment by clason** [comment]
You could also add a `buffer` option to `nvim_create_augroup` that in combination with `clear` behaves as desired? It's a bit unintuitive, though, but might be OK for a low-level API?

**Comment by bfredl** [comment]
@tjdevries yea, we usually have both "delete exact this thing" like `nvim_buf_del_extmark` and another more complex api function for clearing a larger set.

**Comment by tjdevries** [comment]
Ok, I prefer `nvim_clear_autocmd` or `nvim_remove_autocmd` (I think clear is nicer cause it seems further away from `del`). This can have more options to replicate each of the things lifted in `:autocmd-remove`

Sound good @bfredl
