### ISSUE TITLE
Multi-cell characters disappear when intersected with floating window boundaries

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#17550]
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

Vim's popup windows have the same issue.

### Operating system/version

Kubuntu 21.10

### Terminal name/version

Konsole 21.08.1

### $TERM environment variable

xterm-256color

### Installation

Appimage

### How to reproduce the issue

Open Neovim and insert a multi-cell character:

```vim
nvim --clean
" Insert a multi-cell character (e.g., '大') followed by a newline
" (the newline is not necessary, but moving the cursor makes the issue clearer)
```

Next create a floating window that partially covers the character:

```vim
:let config = {'relative': 'editor', 'focusable': v:false, 'width': 10, 'height': 3, 'row': 0, 'col': 1, 'style': 'minimal'}
:let buf = nvim_create_buf(v:false, v:true)
:let win = nvim_open_win(buf, v:false, config)
```

Make the floating window partially transparent:

```vim
:call nvim_win_set_option(win, 'winblend', 80)
```

### Expected behavior

When the floating window is opaque, my expectation is that half the character would be visible beyond the floating window or there would be some indication that there is a character if it's not possible to show half of multi-cell characters.

![expected_1](https://user-images.githubusercontent.com/541289/156028773-a074564f-a2bc-45af-9869-213200ab3387.png)

When the floating window is made transparent, my expectation is that the half-character would display beyond the floating window and also the other half of the character would be shown under the floating window (with color changed to reflect the blending).

![expected_2](https://user-images.githubusercontent.com/541289/156028806-0b3db3c5-c085-4943-a19e-daaa9c2ea069.png)

### Actual behavior

The character disappears.

![actual_behavior](https://user-images.githubusercontent.com/541289/156027345-1c6b76e9-9d3f-4584-926b-84b1527fdeba.png)

### Additional Information

This is based on https://github.com/dstein64/nvim-scrollview/issues/67.

**Comment by zeertzjq** [comment]
I don't think this is possible.

**Comment by zeertzjq** [comment]
Currently this is only possible in multigrid UI (e.g. Goneovim), and the behavior is already intended. AFAIK there is zero chance this will be possible in TUI or non-multigrid UI.

**Comment by zeertzjq** [comment]
Maybe it's better to close this.

**Comment by dstein64** [comment]
It appears that Konsole is able to show the left half of wide characters.

![left_half](https://user-images.githubusercontent.com/541289/156079400-ca8066ee-62bc-4ae2-8093-5b4b05b3036d.png)

However, it doesn't appear to be able to show the right half.

![right_half](https://user-images.githubusercontent.com/541289/156079434-7c02d38a-65ce-43a1-8b52-9d29baa759e6.png)

Half characters (neither left nor right) do not display in GNOME Terminal when using the same approaches.
