### ISSUE TITLE
"shellcmdflag=-ic" causes numerous problems (WAS: bash: no job control in this shell)

### ISSUE THREAD

**Issue by xanderdunn** [neovim/neovim#1756]
Mac OSX 10.10.1. I installed NeoVim using Homebrew exactly as described in the Wiki.

When I copy text from the Mac's Messages app and paste it into NeoVim by pressing p, it goes from looking like this:
![screen shot 2014-12-29 at 00 43 54](https://cloud.githubusercontent.com/assets/1313618/5566374/cba654da-8ef3-11e4-96ac-1bd88e785c9a.png)

To this:
![screen shot 2014-12-29 at 00 39 19](https://cloud.githubusercontent.com/assets/1313618/5566375/cfadccf2-8ef3-11e4-980e-a98ed97fd197.png) 

I don't expect to see that bash error, or to have the new lines turned into ^M.  

I'm using Terminal.app that comes with Mac OSX. 

NeoVim :version
```
NVIM 0.0.0-alpha+201412282305 (compiled Dec 28 2014 23:33:40)
Commit: b64b5372fb62b0fddd1533fd845e47266151d103
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovi
m-8K2quU/build/config -I/tmp/neovim-8K2quU/src -I/tmp/neovim-8K2quU/.deps/usr/include -I/tmp/neovim-8K2quU/.deps/usr/include -I/tmp/neovim-8K2quU/.deps/usr/include/luajit-2.0 -I/usr/local/opt/gettext/incl
ude -I/usr/include -I/tmp/neovim-8K2quU/build/src/nvim/auto -I/tmp/neovim-8K2quU/build/include
Compiled by admin@Alex-Dunns-MacBook-Pro.local  Features included (+) or not (-):
+acl             +cmdline_hist    +diff            +farsi           +iconv           +listcmds        -mouse_gpm       +path_extra      +scrollbind      -tag_any_white   +virtualedit     +writebackup
+arabic          +cmdline_info    +digraphs        +file_in_path    +insert_expand   +localmap        +mouse_netterm   +persistent_undo +signs           +terminfo        +visual          -X11
+autocmd         +comments        -dnd             +find_in_path    +jumplist        +menu            +mouse_sgr       +postscript      +smartindent     +termresponse    +visualextra     -xfontset
-browse          +conceal         -ebcdic          +float           +keymap          +mksession       -mouse_sysmouse  +printer         +startuptime     +textobjects     +viminfo         -xsmp
+byte_offset     +cscope          -emacs_tags      +folding         +langmap         +modify_fname    +mouse_urxvt     +profile         +statusline      +title           +vreplace        -xterm_clipboard
+cindent         +cursorbind      +eval            -footer          +libcall         +mouse           +mouse_xterm     +quickfix        +syntax          -toolbar         +wildignore
-clipboard       +cursorshape     +ex_extra        +fork()          +linebreak       -mouseshape      +multi_byte      +reltime         +tag_binary      +user_commands   +wildmenu
+cmdline_compl   +dialog_con      +extra_search    +gettext         +lispindent      +mouse_dec       +multi_lang      +rightleft       +tag_old_static  +vertsplit       +windows
   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "$HOME/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

[My .nvimrc](https://gist.github.com/alexdunn/fd58639734b1a69dbc65)

**Comment by tarruda** [comment]
> Vim (:shell in gvim) and Emacs have both done this (with more success in Emacs) but they're both awful.
The idea has been floated and although I have not much interest in working on it, I'll be happy to see how close others can get. I agree though, eshell, ansiterm, in emacs are unbearable. Maybe it would be better to work on improving integration with tmux.

While implementing a terminal emulator from the scratch would be a bad idea, [libvterm](http://www.leonerd.org.uk/code/libvterm/) implements the most complicated parts of a full featured terminal emulator while exposing a pluggable input/output system. That fits perfectly with Neovim job control system(though it still needs to be enhanced to allow spawning jobs with pty).

 When I'm done fiddling with the UI, integrating libvterm will be my next task, I will use to create an experience similar to [vimshell](http://www.wana.at/vimshell/)

**Comment by alexdunn** [comment]
Yes, it was my desire to run shell commands (including all my many aliases) while in vim that lead me down the path of: 
```
```

**Comment by justinmk** [comment]
Resolved by `:terminal` :)

**Comment by calbertts** [comment]
After set `shellcmdflag=-ic`, `fugitive` plugin stopped working, just saying.

**Comment by justinmk** [comment]
> After set `shellcmdflag=-ic`, `fugitive` plugin stopped working, just saying.

Only `-i` should be removed. Or rather, remove `shellcmdflag=-ic` from your config, because `-c` is the default.
