### ISSUE TITLE
undefined ref to luv_set_thread/cthread at link

### ISSUE THREAD

**Issue by mckellygit** [neovim/neovim#17562]
### Neovim version (nvim -v)

0.7.0 (latest main) commit a7bc3e0f7b253e4aa39955be6745c23a61eab058

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ubuntu 20.04

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

git source, latest main

### How to reproduce the issue

cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
make

### Expected behavior

compiles and links successfully

### Actual behavior

/usr/bin/ld: /tmp/nvim.GsCqjb.ltrans24.ltrans.o: in function `nlua_common_vim_init':
/home/user/Downloads/neovim/src/nvim/lua/executor.c:503: undefined reference to `luv_set_thread'
/usr/bin/ld: /home/user/Downloads/neovim/src/nvim/lua/executor.c:504: undefined reference to `luv_set_cthread'

**Comment by mckellygit** [comment]
Trying to go backwards and find a recent commit that does link ok.

**Comment by mckellygit** [comment]
commit d0f8f76224f501d919ba6c8a5cd717de76903b34 is ok.
commit b87867e69e94d9784468a126f21c721446f080de has issue.  Not sure if I am supposed to add options to cmake now or install some addl pkg, checking.

**Comment by clason** [comment]
You need to a) make sure that you have libluv 1.43.0 installed and b) regenerate the cmake files (`make distclean` before `make`).

**Comment by mckellygit** [comment]
ok, thanks.
I do a wipe clean the build dir and a fresh cmake from zero.

**Comment by clason** [comment]
Yes, if you just `make` from the repo, you'll use the bundled one. I'm having to guess here what may be wrong with your setup.

**Comment by mckellygit** [comment]
ok, I found my error, thank you.
I was always cleaning out the build dir and starting a cmake from zero, but without the parent dir distclean the .deps dir was old and did not have the latest luv.
ty again,
-m
