### ISSUE TITLE
`autocmd!` speed regression with api-autocmds

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#17561]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1155-g991e47288

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 20.04

### Terminal name/version

GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

Startup time:
```
nvim --clean --startuptime log --cmd 'filetype plugin indent on'
```

Profile:
```
nvim --clean --cmd 'profile start profile.log' --cmd 'profile func *' --cmd 'profile file *' --cmd 'filetype plugin indent on' -c 'profdel func *' -c 'profdel file *' -c 'qa!'
```

### Expected behavior

Before #14661
* startup time 15.923 seconds
* `autocmd` 0.00697 seconds, `autocmd!` **0.000242** seconds

The raw data is here: https://gist.github.com/tomtomjhj/84285e43ab95496244bd343d44e3281e

### Actual behavior

#14661
* startup time 039.874 seconds
* `autocmd` 0.005301 seconds, `autocmd!` **0.024399** seconds

**Comment by bfredl** [comment]
Note that `filetype plugin indent on` is already the default, event with `--clean`. adding it explicitly will force the deletion and recreation of a lot of autocmds. I'll suggest to try the same commands for timing and profiling before and after #14661, but **without** `--cmd 'filetype plugin indent on'`, and report the results here.

**Comment by tomtomjhj** [comment]
`--clean` doesn't run `filetype plugin indent on` (`exists('did_load_filetypes') == 0`), and IIUC even if `filetype plugin indent on` is run twice, it won't redo the autocmds due to `'did_load_filetypes'`.

Without `filetype plugin indent on`, the slowdown is less dramatic (about 15x). The output of `:au` is 291 lines. With `filetype plugin indent on`, the output of `:au` is 3852 lines (100x slowdown).

**Comment by clason** [comment]
> --clean doesn't run filetype plugin indent on (not sure if it's a feature or a bug)

It's a feature, because it's no longer necessary (or even recommended). All the necessary bits and pieces are still done in core. The situation without `filetype plugin indent on` is therefore the one we care about.

**Comment by tomtomjhj** [comment]
> It's a feature, because it's no longer necessary (or even recommended). All the necessary bits and pieces are still done in core. 

I meant "All the necessary bits and pieces are still done in core" are not actually done with `--clean`. For example, `--clean` doesn't even enable syntax highlighting.

**Comment by clason** [comment]
Yes, but `filetype plugin indent on` is _not_ how syntax highlighting is enabled normally. (To be clear, I cannot reproduce these slowdowns with my normal config.)

**Comment by tomtomjhj** [comment]
> filetype plugin indent on is not how syntax highlighting is enabled normally

Yeah `filetype plugin indent on` doesn't itself enable syntax highlighting, but `:syntax on` runs `filetype on`. The doc says `--clean` "mimics a fresh install of Nvim", which does this filetype stuff and syntax highlighting. So I think `--clean` is in fact buggy.

>  cannot reproduce these slowdowns with my normal config.

What version of nvim are you using?

**Comment by clason** [comment]
Latest master, of course.

**Comment by tomtomjhj** [comment]
Do you use filetype.lua and disable legacy filetype.vim (`let did_load_filetypes = 1`)? If so, the slowdown would be less noticeable.

**Comment by clason** [comment]
Not for this test, of course. And you can see that the slowdown is from the plugins, not the `filetype.vim`.

**Comment by tomtomjhj** [comment]
`filetype.vim` sets up a lot of autocmds, and this seems to affect the performance of `au!` in plugins.

**Comment by tjdevries** [comment]
Can you get a reproduction case just by running some script instead of the entire startup sequence? that would help narrow it down (and I could try and optimize some hot path / regression)

**Comment by tomtomjhj** [comment]
```vim
" repro.vim
let did_load_filetypes = 1

" controll the number of autocmds
for i in range(12345)
  exe "au FileType type".i." :"
endfor
augroup repro
  au! " this is slow
augroup END
```
Run with
```
nvim -u repro.vim --noplugin -i NONE --cmd 'profile start profile.log' --cmd 'profile file *' -c 'profdel file *' -c 'qa!'
```

In profile.log, search for `augroup repro`. With 12345 autocmds, `au!` takes 0.010976 seconds on my machine. Without #14661, it only takes 0.000143 seconds.

**Comment by clason** [comment]
Sorry, I cannot reproduce these timings with that script:
```
1234568              0.537142 for i in range(1234567)
1234567              3.420519   exe "au FileType type".i." :"
1234568              0.384440 endfor
    1              0.000003 augroup repro
    1              0.000148   au! " this is slow
    1              0.000008 augroup END
```
and the timings for `au!` are pretty much independent of the number of autocommands.

For the record, I'm testing (on macOS, Intel) with
```
NVIM v0.7.0-dev+1168-g4b3f92047
Build type: Release
LuaJIT 2.1.0-beta3
```
(Just to make extra sure: you aren't accidentally testing with a `Debug` build, are you?)

**Comment by tomtomjhj** [comment]
Also tried building it with clang, but it didn't do much change.
```
123457              0.052957 for i in range(123456)
123456              0.299474   exe "au FileType type".i." :"
123457              0.032402 endfor
    1              0.000003 augroup repro
    1              1.119244   au!
    1              0.000015 augroup END
```
```
NVIM v0.7.0-dev+1168-g4b3f92047
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang-10 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/path/to/neovim/build/config -I/path/to/neovim/src -I/path/to/neovim/.deps/usr/include -I/usr/include -I/path/to/neovim/build/src/nvim/auto -I/path/to/neovim/build/include
```

**Comment by zeertzjq** [comment]
I cannot reproduce this on Arch Linux either.

Before #14661:
```
NVIM v0.7.0-dev+1154-g1b5767aa34
Build type: RelWithDebInfo
```
```
count  total (s)   self (s)
                            " repro.vim
    1              0.000003 let did_load_filetypes = 1
                            
                            " controll the number of autocmds
12346              0.007634 for i in range(12345)
12345              0.047197   exe "au FileType type".i." :"
12346              0.004552 endfor
    1              0.000003 augroup repro
    1              0.000191   au! " this is slow
    1              0.000004 augroup END
```

After #14661:
```
NVIM v0.7.0-dev+1160-g01139ec82c
Build type: RelWithDebInfo
```
```
count  total (s)   self (s)
                            " repro.vim
    1              0.000009 let did_load_filetypes = 1
                            
                            " controll the number of autocmds
12346              0.010496 for i in range(12345)
12345              0.061076   exe "au FileType type".i." :"
12346              0.005863 endfor
    1              0.000003 augroup repro
    1              0.000188   au! " this is slow
    1              0.000003 augroup END
```

**Comment by zeertzjq** [comment]
With 1234567:
Before #14661:
```
count  total (s)   self (s)
                            " repro.vim
    1              0.000005 let did_load_filetypes = 1
                            
                            " controll the number of autocmds
1234568              0.597744 for i in range(1234567)
1234567              3.842447   exe "au FileType type".i." :"
1234568              0.364816 endfor
    1              0.000005 augroup repro
    1              0.008663   au! " this is slow
    1              0.000006 augroup END
```
After #14661:
```
count  total (s)   self (s)
                            " repro.vim
    1              0.000014 let did_load_filetypes = 1
                            
                            " controll the number of autocmds
1234568              0.569970 for i in range(1234567)
1234567              3.811501   exe "au FileType type".i." :"
1234568              0.374867 endfor
    1              0.000004 augroup repro
    1              0.008649   au! " this is slow
    1              0.000031 augroup END
```

**Comment by tomtomjhj** [comment]
Flamegraph of Debug build (RelWithDebInfo result was quite similar to this). 
![flamegraph](https://user-images.githubusercontent.com/19489738/156345185-7a087329-50fb-4773-9988-6de169917622.svg)

**Comment by tomtomjhj** [comment]
With 1234 autocmds using the above reproducer (https://github.com/neovim/neovim/issues/17561#issuecomment-1055638003), `au_cleanup()` is called 1365 times in both versions. But the distributions of states (`autocmd_busy` and `au_need_clean`) are different.

| `autocmd_busy`, `au_need_clean` | before #14661 | after #14661 |
|---------------------------------|---------------|--------------|
| 0, 0   (doesn't enter loop)     | 1364          | 1243         |
| 0, 1   (enters loop)            | **0**         | **121**      |
| 1, 0   (doesn't enter loop)     | 1             | 1            |

**Comment by lewis6991** [comment]
An assignment of `au_need_clean = true;` was added to `free_all_autocmds`.  https://github.com/neovim/neovim/blob/0733f72616acca3d1340a33c4b1fee55db2be5b0/src/nvim/autocmd.c#L546-L566

Is this the culprit?

**Comment by lewis6991** [comment]
Line 244 in https://github.com/neovim/neovim/blob/0733f72616acca3d1340a33c4b1fee55db2be5b0/src/nvim/autocmd.c#L234-L244 looks like it should be removed as `aupat_del` will `au_need_clean`.

**Comment by tomtomjhj** [comment]
Yeah, so that the cleanup runs only when there is something to be cleaned up.
