### ISSUE TITLE
Allow clearing an augroup for the buffer only (lua API)

### ISSUE THREAD

**Issue by entropitor** [neovim/neovim#17576]
### Feature already in Vim?

/

### Feature description

Currently it's only possible to clear all autocommands in an autogroup when using lua. However, the following is not supported: (Notice the `<buffer>` part)

```vim
    augroup LspClosing
      autocmd! * <buffer>
      autocmd BufDelete <buffer> lua DetachBufferFromClients(tonumber(vim.fn.expand("<abuf>")))
    augroup END
```

**Comment by clason** [comment]
Duplicate of #17554
