### ISSUE TITLE
`command` and `desc` fields are the same in return of `nvim_get_autocmds()`

### ISSUE THREAD

**Issue by hexium310** [neovim/neovim#17588]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1177-g7211d8ef2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 11.6

### Terminal name/version

iTerm2 Build 3.5.0beta4

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```sh
nvim --clean -u minimal.lua
```

`minimal.lua`
```lua
vim.api.nvim_create_autocmd({ 'InsertEnter' }, {
  callback = function ()
  end,
})
vim.api.nvim_create_autocmd({ 'InsertEnter' }, {
  desc = 'It is desc',
  callback = function ()
  end,
})
print(vim.inspect(vim.api.nvim_get_autocmds({ event = { 'InsertEnter' } })))
```

### Expected behavior

When `nvim_create_autocmd()` with `callback` but without `desc` was called,  the `desc` field of the return of `nvim_get_autocmds()` should be empty. Also, when that with `callback` and `desc` is called the `command` field should be `<Lua function n>` or something else.

```
{ {
    buflocal = false,
    command = "<Lua function 4>",
    desc = "",
    event = "InsertEnter",
    id = 1,
    once = false,
    pattern = "*"
  }, {
    buflocal = false,
    command = "<Lua function 4>",
    desc = "It is desc",
    event = "InsertEnter",
    id = 2,
    once = false,
    pattern = "*"
  } }
```

### Actual behavior

The `command` and `desc` fields are the same.

```
{ {
    buflocal = false,
    command = "<Lua function 4>",
    desc = "<Lua function 4>",
    event = "InsertEnter",
    id = 1,
    once = false,
    pattern = "*"
  }, {
    buflocal = false,
    command = "It is desc",
    desc = "It is desc",
    event = "InsertEnter",
    id = 2,
    once = false,
    pattern = "*"
  } }
```

**Comment by clason** [comment]
@tjdevries is this intentional?

**Comment by tjdevries** [comment]
This seems like bug -- I'm not sure the description field makes 100% sense the way it is today. I'd like it to show more information when typing `:verbose autocmd` as well, but wasn't sure how to implement that.

**Comment by clason** [comment]
Hmm... This seems to be done explicitly in `aucmd_exec_default_desc`?

I'd be great if this could get fixed for 0.7 to show the expected behavior above (maybe it's easy enough so someone else can do it with a bit of help from you?), and leave the more verbose improvements for 0.8 (or later)?

**Comment by tjdevries** [comment]
I am working on it, might push in same PR as the fix for the `nvim_clear_autocmds` to play around with this a bit as well. Or I can separate the commits if we need.

**Comment by clason** [comment]
Note that the second example is purely an issue with `nvim_get_autocmds()`; the autocommand shows up correctly when doing `au InsertEnter`. (The first one, on the other hand, doesn't show up at all, which is a bit worrying.)
