### ISSUE TITLE
LSP: `window/showMessage` handler is not used

### ISSUE THREAD

**Issue by ObserverOfTime** [neovim/neovim#17599]
### Neovim version (nvim -v)

v0.7.0-dev+1161-g37a86a2f9

### Language server name/version

any

### Operating system/version

Arch Linux

### Steps to reproduce using "nvim -u minimal_init.lua"

* Add these lines to `minimal_init.lua`:
```lua
vim.lsp.handlers['window/showMessage'] = function(_, result, ctx)
  local client = vim.lsp.get_client_by_id(ctx.client_id)
  vim.notify('LSP ('..client.name..'): '..result.message)
end
```
* Open a Python file to launch `pyright`
* Type `gi` (`textDocument/implementation`)

### Expected behavior

The error message should be:
```
LSP (pyright): method textDocument/implementation is not supported by any of the servers registered for the current buffer
```
Explicitly calling `vim.lsp.handlers['window/showMessage']` works.

### Actual behavior

The message is:
```
method textDocument/implementation is not supported by any of the servers registered for the current buffer
```

**Comment by ObserverOfTime** [comment]
It seems that the message doesn't even match the format defined in the code. :thinking: 
https://github.com/neovim/neovim/blob/726ec7fb17aa8a86b1c2c9adc4c6abfcb350d3a7/runtime/lua/vim/lsp/handlers.lua#L472-L480

On the other hand, overriding `window/logMessage` works as expected.

**Comment by mjlbach** [comment]
You're looking in the wrong place, this is an internal warning thrown by the client if none of the attached servers support the method:

Defined:
https://github.com/mjlbach/neovim/blob/dba1df63595adb2988f5502561b833201b504cc1/runtime/lua/vim/lsp.lua#L87-L92

Called:
vim.notify(lsp._unsupported_method(method), vim.log.levels.ERROR)](https://github.com/mjlbach/neovim/blob/dba1df63595adb2988f5502561b833201b504cc1/runtime/lua/vim/lsp.lua#L1478)

**Comment by ObserverOfTime** [comment]
So there's no way to customise its output then. :confused:

**Comment by mjlbach** [comment]
You wouldn't want to customize this output, as this is our error message that you are attempting to send a request to a server that doesn't support it. If you don't like the error then you can always avoid buf_request and call client.request directly (so you would need to right your own functions for everything in buf.lua)
