### ISSUE TITLE
python provider: improve sanity checks, user experience

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1760]
see https://github.com/wellle/tmux-complete.vim/issues/49

**Comment by philix** [comment]
The way I solved that problem in my system was uninstalling the non-sytem
Python from my Mac OS X.

If we could solve that at the neovim level (by finding the right one or
simply telling the user what to do) it would be great.

Happy 2015! The year of Neovim!

__
Felipe O. Carvalho (philix)
http://felipe.rs

**Comment by justinmk** [comment]
Happy new year :neckbeard:

**Comment by justinmk** [comment]
`:CheckHealth` covers this now. It can always be improved too, if anyone finds more edge cases to check.
