### ISSUE TITLE
Incorrect range in didChangeTextDocument

### ISSUE THREAD

**Issue by matklad** [neovim/neovim#17605]
### Neovim version (nvim -v)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by nixbld  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: " /nix/store/9lh249lpifh9kg697kky83b66d3kw52m-neovim-unwrapped-0.6.1/share/nvim "  Run :checkhealth for more info

### Language server name/version

rust-analyzer f8329ba98 2022-03-04 dev

### Operating system/version

NixOS

### Steps to reproduce using "nvim -u minimal_init.lua"

```
λ bat -p ~/.config/nvim/init.vim
lua << EOF
    local use = require('packer').use
    require('packer').startup(function()
      use 'wbthomason/packer.nvim' -- Package manager
      use 'neovim/nvim-lspconfig' -- Collection of configurations for the built-in LSP client
    end)
    require('lspconfig').rust_analyzer.setup{}
    vim.lsp.set_log_level("debug")
EOF

function! FormatFile() abort
  let tmpfile = tempname()
  let shellredir_save = &shellredir
  let &shellredir = '>%s 2>'.tmpfile
  silent execute '%!rustfmt --edition 2018 --color never --emit stdout'
  let &shellredir = shellredir_save
  if v:shell_error != 0
    silent undo
  endif
  call delete(tmpfile)
endfunction
```

Open the following rust file (note double `)`!)

```
fn main() {  
    println!("Hello, world!"));                                           
}  
```

`:call FormatFile()`

### Expected behavior

everything works

### Actual behavior

server crashes (to be more precise, it used to crash until we put a work-around to ignore the whole issue)

### Log file

https://gist.github.com/matklad/1370a7c0dc01fb3d9c5e4e98a57f9e83

**Comment by matklad** [comment]
Potentially more useful TL;DR: I observe the following sequence of messages in the log:

```
{ method = "textDocument/didChange",  params = {
  contentChanges = {{
    range = { end = { character = 0, line = 0 }, start = { character = 0, line = 0 } },
    rangeLength = 0,
    text = 'fn main() {\n    println!("Hello, world!"));\n}'
  }}, textDocument = { uri = "main.rs", version = 5 }}}

{ method = "textDocument/didChange",  params = {
  contentChanges = {{
    range = { end = { character = 0, line = 3 }, start = { character = 0, line = 3 } },
    rangeLength = 0,
    text = ""
  }}, textDocument = { uri = "main.rs", version = 6 }}}
```

The first message sets the text of an empty document to the specified string. The second change is a no-op: both the range and the text are empty. However, the range is invalid -- there's no line 3 in the document (the full text of the document is visible in he previous message).

rust-analyzer issue: https://github.com/rust-analyzer/rust-analyzer/issues/11081


I *feel* like I've already seen such a problem around the last `\n` in Vim, but I can't find that discussion anymore.

**Comment by dimbleby** [comment]
> client crashes

_server_ crashes, surely?

(obviously it's still desirable for the client to provide a valid range)

**Comment by mjlbach** [comment]
@matklad You are probably thinking of https://github.com/neovim/neovim/issues/17085 (I think these are the same issues, but not 100% positive)

There's some annoying behavior around empty buffers and newlines in (neo)vim that I need to work around.
