### ISSUE TITLE
`autochdir` directory is overwritten by `getwinvar()` call

### ISSUE THREAD

**Issue by cincodenada** [neovim/neovim#17609]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

No, vim 8.2.3489

### Operating system/version

macOS 12.2

### Terminal name/version

alacritty 0.10.0, nvim-qt

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

Use `demo.vim` as follows. This script:
 - Sets `autochdir`
 - Opens `dir_a/file`
 - Runs `:lcd dir_b`
 - Opens `demo.vim` in a split window to the right (what is opened here isn't significant, just that there is a second window)
 - Switches back to the left-hand window
 - After a delay (allowing `autochdir` to take effect), calls `getwinvar(2, 'blah')`
```
set nocompatible
set autochdir

" Set up left window
e dir_a/file
lcd dir_b

" Move to right window
bot vnew ../demo.vim

" Move back left
wincmd h

" After a delay, get a winvar from the second window
call timer_start(100, 'GetVar')

function! GetVar(...)
  call getwinvar(2, 'blah')
endfunction
```

To reproduce, with `demo.vim` in the current directory, run:
```
mkdir dir_a dir_b
touch dir_a/file

nvim --clean -S demo.vim
:verbose pwd
```

The timer itself isn't actually necessary, it just allows `autochdir` to take effect. You can achieve the same reproduction by commenting out everything after `wincmd h` and running `:call getwinvar(2, 'blah')` interactively yourself.

### Expected behavior

The path at the bottom of the window should simply read `file`, and `:verbose pwd` should show the path that `file` is in, set by `autochdir`:
```
[autochdir] /path/to/dir_a
```

### Actual behavior

The path at the bottom of the window shows an absolute path to `file`, and `:verbose pwd` shows that `pwd` has been reset to the previously-set window-local path in `dir_b`:
```
[window] /path/to/dir_b
```

### Further information

This is causing a bug downstream in `coc.nvim` (https://github.com/neoclide/coc.nvim/issues/3651), and it seems to be triggered by calling `getwinvar` on a window other than the one currently active.

**Comment by zeertzjq** [comment]
Porting <https://github.com/vim/vim/commit/90c317f2246a7fb4bd4e3feb0778b53627bc9fad> may fix this.
