### ISSUE TITLE
nvim_create_autocmd callback is called with argument "aucmd"

### ISSUE THREAD

**Issue by euclidianAce** [neovim/neovim#17619]
### Feature already in Vim?

N/A

### Feature description

It seems like the string `"aucmd"` is passed to the autocmd `callback` but this does not seem to be documented anywhere. Is this intentional?

```lua
vim.api.nvim_create_autocmd("TextChangedI", { callback = print })
```
will print `aucmd` on text changes

**Comment by zeertzjq** [comment]
It looks like debugging code left in source code.

**Comment by fsouza** [comment]
Hmm I noticed this when I first adopted it and thought it was by design 🙈 (weird, but still 🤷)

**Comment by clason** [comment]
I don't think that was meant to be in there ;)
https://github.com/neovim/neovim/blob/5760cf87b6d09165cd08af3e2afa231909e3d2df/src/nvim/eval.c#L7791-L7793

Maybe an artifact of the merge mishap on your PR @tjdevries ?

**Comment by clason** [comment]
Well, the log shouldn't be there, but the behavior seems to be a standard pattern: callbacks are usually (but not always) called with the name of the event as the first argument.

**Comment by clason** [comment]
I'm leaving this open to think about if and where to document this basic callback structure; the behavior is by design.

**Comment by tjdevries** [comment]
Ah, this is a bug -- I didn't realize it. At this point, there should be no expectations about what is passed to the autocmd when executing.

**Comment by tjdevries** [comment]
btw, hey euclidean :) hope you're doing well

**Comment by clason** [comment]
But other callbacks have the same behavior?

If this is not intended, here, just pass `NULL` instead of `"aucmd"` in eval.c:7792.
