### ISSUE TITLE
Scroll past end resetting

### ISSUE THREAD

**Issue by ibraheemdev** [neovim/neovim#17612]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux

### Terminal name/version

Kitty 0.24

### $TERM environment variable

xterm-kitty

### Installation

AUR

### How to reproduce the issue

Use Ctrl+E to scroll past the end of a file. Use `k` to move up one line.

### Expected behavior

The space past the end of the file to be retained, minus one line.

### Actual behavior

The editor jumped up one line, clearing all space below the end.

Before `k`: 
![image](https://user-images.githubusercontent.com/34988408/156867118-16f0fa86-2391-456a-b836-66ca22e8da0b.png)

After: 
![image](https://user-images.githubusercontent.com/34988408/156867121-12371c08-0ce5-4d52-a0c1-cab0e3120be3.png)

**Comment by zeertzjq** [comment]
I cannot reproduce this. Please provide steps to reproduce with `nvim --clean`.

**Comment by ibraheemdev** [comment]
Hm, it seems to be related to lsp.

**Comment by ibraheemdev** [comment]
It's working now, maybe there was an lsp diagnostic that it was jumping to, not sure. One thing that I would also like to know is if there is a way to preserve the spacing after switching away from and back to the buffer (`:bn`), but that's not related to this bug.
