### ISSUE TITLE
`Error executing lua callback: ... attempt to get length of local 'line' (a nil value)` when editting new files

### ISSUE THREAD

**Issue by fsouza** [neovim/neovim#17615]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1192-g8ed9c8448

### Language server name/version

pyright

### Operating system/version

Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64 arm64 MacBookPro18,4 Darwin

### Steps to reproduce using "nvim -u minimal_init.lua"

1. Run `nvim -u minimal_init.lua` (link to the my [minimal_init.lua](https://gist.github.com/fsouza/fcbf926ed67dc6ebbcc05e9ff73ead33))
2. once it's ready, edit a Python file
3. type some code, but do not press enter (for example `while True:`)
4. exit insert mode
5. press `O` to start editing the line above (get an error)
6. exit insert mode again and go to the line below
7. press `o` to start editing a new line below (get a different error)

(note: the issue doesn't always happen, but it happens most of the time)

### Expected behavior

Enter insert mode in the line above, with no errors.

### Actual behavior

On step 5, I get the following error:

```
Error executing lua callback: ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:142: attempt to get length of local 'line' (a nil value)
stack traceback:
        ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:142: in function 'compute_start_range'
        ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:359: in function 'compute_diff'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:427: in function 'incremental_changes'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:460: in function 'fn'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:164: in function 'for_each_buffer_client'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:1184: in function </Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:1176>
```

On step 7, I get two errors: 

```
Error executing lua callback: ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:142: attempt to get length of local 'line' (a nil value)
stack traceback:
        ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:142: in function 'compute_start_range'
        ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:359: in function 'compute_diff'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:427: in function 'incremental_changes'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:460: in function 'fn'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:164: in function 'for_each_buffer_client'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:1184: in function </Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:1176>
Press ENTER or type command to continue
Error executing lua callback: ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:162: attempt to get length of local 'prev_line' (a nil value)
stack traceback:
        ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:162: in function 'compute_start_range'
        ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:359: in function 'compute_diff'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:427: in function 'incremental_changes'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:460: in function 'fn'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:164: in function 'for_each_buffer_client'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:1184: in function </Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:1176>
Error executing lua callback: ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:162: attempt to get length of local 'prev_line' (a nil value)
stack traceback:
        ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:162: in function 'compute_start_range'
        ...souza/opt/neovim/share/nvim/runtime/lua/vim/lsp/sync.lua:359: in function 'compute_diff'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:427: in function 'incremental_changes'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:460: in function 'fn'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:164: in function 'for_each_buffer_client'
        /Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:1184: in function </Users/fsouza/opt/neovim/share/nvim/runtime/lua/vim/lsp.lua:1176>
```

Notice that from now on the file is completely out of sync, and I'll get some weird errors like "break should be used inside a loop" even if I write a break inside a loop, and I get the error on every keystroke in insert mode. To cleanup errors, I have to save the file and run ":e!".

Here's a recording:

https://user-images.githubusercontent.com/108725/156904684-473e5fbf-451c-4519-b62e-28f54e41a869.mp4

(notice that the diagnostic is in the wrong line and I get the error on every keystroke of `break` - I actually struggled to type "break" because some of the errors had to be dismissed before typing lol)

**Comment by fsouza** [comment]
The title says new files, but I just ran into this issue with an existing file. Sorry about that.

**Comment by mjlbach** [comment]
Try reverting https://github.com/neovim/neovim/commit/a5e475fcc269b32a8a487f787af20802cbfabe28?

**Comment by mjlbach** [comment]
@fsouza want to test #17618?

**Comment by fsouza** [comment]
> @fsouza want to test #17618?

On my way to bed now, but will test it first thing in the morning tomorrow!

**Comment by nyngwang** [comment]
I just encountered the same issue when swapping lines.

**Comment by nyngwang** [comment]
The error disappears. Confirmed it works in my case.

**Comment by zijian-x** [comment]
encounters this error upon every `O` action on first line in normal mode in c/cpp file with default clangd setup.

**Comment by fsouza** [comment]
> @fsouza want to test #17618?

Confirmed #17618 fixes the issue for me, thank you very much for the quick fix!

**Comment by av-maslov** [comment]
I have got the same error when entering dap repl

`Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/sync.lua:170: attempt to get length of local 'prev_line' (a nil value)
stack traceback:
        /usr/local/share/nvim/runtime/lua/vim/lsp/sync.lua:170: in function 'compute_start_range'
        /usr/local/share/nvim/runtime/lua/vim/lsp/sync.lua:367: in function 'compute_diff'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:427: in function 'incremental_changes'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:460: in function 'fn'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:164: in function 'for_each_buffer_client'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1184: in function </usr/local/share/nvim/runtime/lua/vim/lsp.lua:1176>`

**Comment by donny-son** [comment]
@av-maslov I had this similar issue due to Github copilot. If you have enabled copilot, be sure to disable it on all buffers by default and enable it only on explicit filetypes.

**Comment by phcerdan** [comment]
@av-maslov , same, faced it using dap through vimspector

**Comment by iserpent** [comment]
> @av-maslov , same, faced it using dap through vimspector
This was also because of copilot in my case, this helped (luckily `Variables` and `Console` views have a distinguished file type):
`g.copilot_filetypes = { ['VimspectorPrompt'] = false }`

**Comment by MohamedOsman1998** [comment]
damn, I kind of liked having copilot on the dap-repl. this is still an issue for me btw in 0.9.1.
any known workarounds?

**Comment by themightyoarfish** [comment]
I am seeing this ever since using coc, coc-clangd and nvim-lspconfig. version 0.9.1 too.

**Comment by themightyoarfish** [comment]
This seems to happen for me every time now after opening and switching to new buffer with `:e <other-file>`. What can I do about this?

**Comment by clason** [comment]
1. test with current release (0.9.4), better yet with nightly (use the releases on our download page)
2. remove coc from the equation; create a minimal(!) `init.lua` (and, if necessary, clangd project) that uses `vim.lsp.start` so we can try to reproduce with `nvim --clean -u init.lua test.c`
