### ISSUE TITLE
JSONC decoding support

### ISSUE THREAD

**Issue by nscotto** [neovim/neovim#17627]
### Feature already in Vim?

No

### Feature description

We have `json_decode` which is very handy, however it doesn't support JSONC format (json with comments).
It would be a nice upgrade to support it, either by updating `json_decode` or adding a new `jsonc_decode`. 

Editors like VSCode use JSONC format (despite calling it .json) for some of their configuration/plugin configurations.
When writing neovim plugin that support some of their features (like the famous remote containers) the support can only partial when using `json_decode`.

I really don't want to be forced to use VSCode by the rest of my team!

**Comment by clason** [comment]
The built-in JSON module is very much driven by the internal needs of Neovim (in particular, the performance of communication with an LSP server). It is also just a wrapper for `lua-cjson` and not an independent implementation. There are therefore no plans for adding features (especially support for JSONC!), rather the opposite.

Your use case seems perfect for a plugin that uses, say, a [tree-sitter parser for jsonc](https://gitlab.com/WhyNotHugo/tree-sitter-jsonc).

**Comment by nscotto** [comment]
Ok, that's also what I was thinking.
Closing this then.

**Comment by clason** [comment]
`vim.treesitter.get_string_parser()`
