### ISSUE TITLE
Getting underline attribute from syntax hl group returns empty string instead of '1'

### ISSUE THREAD

**Issue by kristijanhusak** [neovim/neovim#17624]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1194-g24d56116f

### Vim (not Nvim) behaves the same?

no, vim 8.2.4464

### Operating system/version

Linux

### Terminal name/version

Kitty

### $TERM environment variable

xterm-kitty

### Installation

Built from source

### How to reproduce the issue

nvim --clean
:hi UnderlineTest gui=underline
:echo synIDattr(synIDtrans(hlID('UnderlineTest')), 'underline')

### Expected behavior

Expected to get `1` returned.

This also properly works in stable versions of Neovim since 0.5.0.

Figured this issue from the tests in nvim-orgmode: https://github.com/nvim-orgmode/orgmode/runs/5439299419?check_suite_focus=true#step:7:96

Link to line where the test fails: https://github.com/nvim-orgmode/orgmode/blob/master/tests/plenary/colors/colors_spec.lua#L79

### Actual behavior

Getting the empty string.

**Comment by jamessan** [comment]
Likely fallout from @kchibisov's [PR](https://github.com/neovim/neovim/pull/17589).

**Comment by kchibisov** [comment]
@jamessan I'd assume the tests should go into `functional/terminal/highlight_spec.lua`?

**Comment by jamessan** [comment]
That or `functional/ex_cmds/highlight_spec.lua` would work.
