### ISSUE TITLE
`vim.api.nvim_get_commands` should use a separate field when there is a description set

### ISSUE THREAD

**Issue by mrjones2014** [neovim/neovim#17639]
### Feature already in Vim?

No

### Feature description

Not sure if this counts as a bug or a feature. When you call `vim.api.nvim_get_commands`, if the `desc` option was set, it just overwrites the `definition` field of the returned tables. So there is no way to know if the command has an actual description or not.

For context, I'm working on this: https://github.com/mrjones2014/legendary.nvim/issues/39

And it doesn't make a whole lot of sense to show items that don't have a description in my plugin.

~~Also `vim.keymap.set` should have a `desc` field that returns the description when calling `vim.api.nvim_get_keymap`.~~ @clason pointed out this is already supported, although it's not in the help docs.

**Comment by mrjones2014** [comment]
I don't see anything about adding a description in `:h vim.keymap.set` and `vim.api.nvim_get_keymap` doesn't return any sort of description field.

**Comment by zeertzjq** [comment]
```
In addition to the options listed in |nvim_set_keymap()|
```
That includes `desc`, doesn't it?

**Comment by clason** [comment]
It does.

**Comment by mrjones2014** [comment]
Ah, okay sweet. That's not described in the help docs, at least. But that solves part of the problem.

Now I'd just need a way to determine if commands have an actual description set when loading them via `vim.api.nvim_get_commands`

**Comment by clason** [comment]
And returning to your _actual_ issue:

> Not sure if this counts as a bug or a feature. When you call vim.api.nvim_get_commands, if the desc option was set, it just overwrites the definition field of the returned tables. So there is no way to know if the command has an actual description or not.

The whole `opts` field is currently not supported; you shouldn't be using it and expect something useful to happen.

(That being said, the presence should not have any effect, so that may still be a bug.)

**Comment by clason** [comment]
> Ah, okay sweet. That's not described in the help docs, at least. But that solves part of the problem.

But it is; you just need to actually read what is written there and follow the links ;)

**Comment by mrjones2014** [comment]
>The only option that is supported is {"builtin":false}, so this is not expected to work.

I don't think that's really relevant to the problem. The description is set in the `opts` field of `vim.api.nvim_add_user_command`, but the `{"builtin":false}` option is an option to `vim.api.nvim_get_commands`.

What I'm asking for is that the tables returned by `vim.api.nvim_get_commands` use a separate field for the description, if one is set, so that I can tell if a command actually has a description.

**Comment by clason** [comment]
> Now I'd just need a way to determine if commands have an actual description set when loading them via `vim.api.nvim_get_commands`

The `description` field is not part of the command structure; the `desc` option is only used for Lua commands to replace the (in this case useless) `definition` field.

Note that the Neovim API (`nvim_*`, as opposed to the Lua API `vim.*`) comes with a strong contract, so while adding fields to existing tables is possible, it should not be done lightly.

**Comment by mrjones2014** [comment]
Is there another way to figure out if an actual description is set without adding a new table field?

**Comment by clason** [comment]
No, because as I wrote, there _is_ no "actual description" for commands.

**Comment by mrjones2014** [comment]
Okay I guess what I am asking for then is that the `desc` opt to be part of the command structure, instead of just replacing the `definition` field.

**Comment by clason** [comment]
Why? It's not backward-compatible (in the sense that you would only be able to set it from the Neovim API, and most commands will continue not to have any).

**Comment by mrjones2014** [comment]
>For context, I'm working on this: https://github.com/mrjones2014/legendary.nvim/issues/39
>
>And it doesn't make a whole lot of sense to show items that don't have a description in my plugin.

**Comment by clason** [comment]
Yes, I saw the context; I'm just not convinced by the point you're making. If showing commands without description makes no sense in your plugin, then don't show commands in your plugin?

(Just adding the field in Neovim's API on master will not magically make descriptions appear in commands that are _not_ set via the Neovim API...)

**Comment by mrjones2014** [comment]
I don’t really see how the current implementation of command descriptions is useful if you can’t tell it’s a description.

> (Just adding the field in Neovim's API on master will not magically make descriptions appear in commands that are not set via the Neovim API...)

I know that and I’m not asking for that? I just want a better way to surface descriptions set on commands that _are_ set via the API.

**Comment by clason** [comment]
> I don’t really see how the current implementation of command descriptions is useful if you can’t tell it’s a description.

It's not meant to be a command description -- it's just meant as a stopgap measure for _Lua_ commands, where the output of `:command` is not useful otherwise. Again, let me be clear: these are _not_ generic "command descriptions", because that does not exist at the moment.

What you're asking is therfore a much bigger thing: adding descriptions to commands, period. (I don't think a partial solution is useful, because this would introduce a distinction between "API commands" and "vanilla commands", which we don't want.)

**Comment by mrjones2014** [comment]
> It's not meant to be a command description

It probably shouldn’t have been called `desc` which is short for “description” then, just saying ;)

**Comment by clason** [comment]
Maybe. If it helps, you can pretend it's short for "use this description in place of the command".

**Comment by mrjones2014** [comment]
If the description field is not a description, as you state, then it should probably say that as well.

I mean, maybe it's just me, but when I see a field called `"desc"`, that sounds like a description to me.

**Comment by clason** [comment]
I don't think debating this further will lead to anything. If you have a better suggestion for a (short!) keyword in the options dict, or think the documentation could be improved, please open a PR.

**Comment by mrjones2014** [comment]
I'll close the issue, this has been thoroughly toxic :)

**Comment by clason** [comment]
I'm sorry you feel that way.
