### ISSUE TITLE
Minimum version of Python is inconsistent 

### ISSUE THREAD

**Issue by joy369** [neovim/neovim#17645]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1201-g5760cf87b

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ubuntu

### Terminal name/version

xterm

### $TERM environment variable

xterm-256color

### Installation

Zip

### How to reproduce the issue

nvim
:checkhealth provider

### Expected behavior

Considering the [PR#17274](https://github.com/neovim/neovim/pull/17274#issuecomment-1030167386), 3.6 should be the minimum version yet [checker](https://github.com/neovim/neovim/commit/baec0d3152afeab3007ebb505f3fc274511db434#diff-22bc87ade4f904f69ba9ceba4a86379f95dcc8d3f614a744888767abfe4fa660L31) allows only >= 3.7.

## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          /usr/bin/python3 is Python 3.6 and cannot provide Python >= 3.7.

**Comment by clason** [comment]
That PR is for an external build script, and the minimal version there is determined by our CI environment.

For Neovim itself, we only support Python 3.7+ as Python 3.6 is officially end of life since last year: https://github.com/neovim/neovim/pull/17222
