### ISSUE TITLE
Undefined references in auto/ex_cmds_defs.generated.h after make clean

### ISSUE THREAD

**Issue by splinterofchaos** [neovim/neovim#1765]
```bash
$ rm -rf build .deps
$ make clean
$ make
```
After these steps, everything's fine until it tries to compile `ex_docmd.c`:
```
 Building C object src/nvim/CMakeFiles/nvim.dir/ex_docmd.c.o
In file included from /home/admin/src/neovim/src/nvim/ex_docmd.c:168:
/home/admin/src/neovim/build/src/nvim/auto/ex_cmds_defs.generated.h:812:4: error: use of undeclared identifier 'CMD_helpclose'
  [CMD_helpclose] = {
   ^
/home/admin/src/neovim/src/nvim/ex_docmd.c:1832:10: error: use of undeclared identifier 'CMD_lua'
    case CMD_lua:
         ^
/home/admin/src/neovim/src/nvim/ex_docmd.c:1834:10: error: use of undeclared identifier 'CMD_mzscheme'
    case CMD_mzscheme:
         ^
/home/admin/src/neovim/src/nvim/ex_docmd.c:1837:10: error: use of undeclared identifier 'CMD_perl'
    case CMD_perl:
         ^
/home/admin/src/neovim/src/nvim/ex_docmd.c:1840:10: error: use of undeclared identifier 'CMD_py3'
    case CMD_py3:
         ^
/home/admin/src/neovim/src/nvim/ex_docmd.c:1841:10: error: use of undeclared identifier 'CMD_python3'; did you mean 'CMD_python'?
    case CMD_python3:
         ^~~~~~~~~~~
         CMD_python
/home/admin/src/neovim/src/nvim/ex_cmds_enum.generated.h:319:3: note: 'CMD_python' declared here
  CMD_python,
  ^
/home/admin/src/neovim/src/nvim/ex_docmd.c:1844:10: error: use of undeclared identifier 'CMD_ruby'
    case CMD_ruby:
         ^
/home/admin/src/neovim/src/nvim/ex_docmd.c:1851:10: error: use of undeclared identifier 'CMD_tcl'
    case CMD_tcl:
         ^
/home/admin/src/neovim/src/nvim/ex_docmd.c:1841:10: error: duplicate case value 'CMD_python'
    case CMD_python3:
         ^
/home/admin/src/neovim/src/nvim/ex_docmd.c:1839:10: note: previous case defined here
    case CMD_python:
         ^
```
That's the output from clang. Very similar with gcc, though not as easy to read.

Do I need another step for a clean make, or did the build system change recently?

**Comment by justinmk** [comment]
I added entries to ex_cmds.lua which somehow appears to be either cached or not generating, on your machine.

**Comment by splinterofchaos** [comment]
The file, `build/include/ex_cmds_enum.generated.h` does seem to define the missing values, but `src/nvim/ex_cmds_enum.generated.h` does not. I no longer get a compiler error after copying the `build/...` file to the `src/...` one.

Build systems confuse me. If we generate a file into `build/include/...`, then why does the one in the `src` directory get used?

**Comment by justinmk** [comment]
> I no longer get a compiler error after copying the build/... file to the src/... one.

Do you mean `build/src/nvim/auto/ex_cmds_enum.generated.h`? That doesn't exist at all for me. What happens if you delete it?

What version of cmake do you have?

The fact that it's complaining about `CMD_helpclose` means that even PR #1724 is a problem, so it really seems like something is stale. But you removed `build` and `.deps` so I can't imagine what.

Was your workspace more than 11 days old (when PR #1724 was merged), until today?

**Comment by justinmk** [comment]
If you really do have `src/nvim/ex_cmds_enum.generated.h` (not in `build/...`) then that shoud not exist. Possibly it's left over from running an explicit `cmake` command sometime in the past? If you delete it, and `git clean -fd` to purge your workspace, then run `make` again, does it come back?

**Comment by justinmk** [comment]
> If we generate a file into build/include/..., then why does the one in the src directory get used

`nvim/src` has precedence in the "include path". 

> or should there not actually be any generated headers in the src directory anymore?

Exactly, generated files always go into `build/`, except possibly if you run `cmake` explicitly. I don't know the details of that, however, because I rarely run `cmake` explicitly.

**Comment by splinterofchaos** [comment]
> If you delete it, and git clean -fd to purge your workspace, then run make again, does it come back?

Works like a charm! Thanks.

I guess there's no issue, and it's been over a week since these changes, so I'll close this.
