### ISSUE TITLE
<C-w> only partially deletes word after inserting virtual text

### ISSUE THREAD

**Issue by noib3** [neovim/neovim#17652]
### Neovim version (nvim -v)

v0.7.0-dev

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

NixOS 22.05

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

from source

### How to reproduce the issue

`nvim --clean -u ./init.vim`

where
```vim
" init.vim
normal if

let ns = nvim_create_namespace('foo')
call nvim_buf_set_extmark(
  \ 0,
  \ ns,
  \ 0,
  \ 1,
  \ {'id': 1, 'virt_text': [['oo', 'Comment']], 'virt_text_pos': 'overlay'}
\ )

call nvim_buf_clear_namespace(0, ns, 0, -1)
call feedkeys("aoo\<C-w>")
```

### Expected behavior

`foo` is deleted and the buffer is empty.

### Actual behavior

`f` is still in the buffer.

**Comment by zeertzjq** [comment]
`:set backspace+=nostop`
