### ISSUE TITLE
Compound clipboard option doesn't work

### ISSUE THREAD

**Issue by dumblob** [neovim/neovim#1766]
Setting `clipboard="unnamed"` works well, but `clipboard="unnamed,exclude:cons\|linux"` not any more. Even the following doesn't work:

~~~~viml
set clipboard+=unnamedplus
set clipboard+="exclude:cons\|linux"
~~~~

**Comment by justinmk** [comment]
Yeah, `exclude:` is not supported yet. I'm not even sure it makes sense for Neovim, we should auto-detect whether clipboard is available and handle it gracefully. But maybe I don't understand what `:exclude` is supposed to do?

**Comment by dumblob** [comment]
I understand `exclude:` the same way as you. It's used in the default *vim* configuration (it's also mentioned in vim manual), so *neovim* should definitely handle console as well "by default".

**Comment by justinmk** [comment]
If `exclude:con` is supposed to disable the `clipboard` for linux console, then the only thing we need to do is ignore it.

BTW, I think it would be awesome to fall back to the tmux copy/paste buffer if nothing else is available. What do you think?

**Comment by dumblob** [comment]
>BTW, I think it would be awesome to fall back to the tmux copy/paste buffer if nothing else is available. What do you think?

That'll be handy to support it, but we should provide means to disable this behavior as somebody might want neovim not to corrupt his tmux setup. Also it must not interfere with terminal emulator running tmux/screen running neovim where the X11/Wayland tools should be used.

**Comment by justinmk** [comment]
Speaking of wayland, do we need to be aware of a wayland equivalent to `xsel`/`xclip`?

**Comment by dumblob** [comment]
Well, right now I can't think of any equivalent of `xsel`/`xclip` for Wayland, but e.g. Fedora 21 uses Wayland by default, so we should keep it in mind/TODO.

**Comment by justinmk** [comment]
Neovim does not support `exclude:`. However, `unnamed,unnamedplus` should work now.
