### ISSUE TITLE
Multiple events in single string to nvim_create_autocmd

### ISSUE THREAD

**Issue by AckslD** [neovim/neovim#17664]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1224-ga978d7689

### Vim (not Nvim) behaves the same?

irrelevant

### Operating system/version

arch linux 5.16.13.arch1-1

### Terminal name/version

kitty 0.24.4

### $TERM environment variable

xterm-kitty

### Installation

AUR

### How to reproduce the issue

nvim -u NONE
:lua vim.api.nvim_create_autocmd('BufEnter,BufWritePost,InsertLeave', {command = 'echo "test"'})

### Expected behavior

Having an `InsertLeave` command in `:autocmd InsertLeave`.

At least according to the [docs](https://github.com/neovim/neovim/blob/master/runtime/doc/api.txt#L3136) it seems to indicate that this should be allowed.

### Actual behavior

No `InsertLeave` autocmd

**Comment by clason** [comment]
@tjdevries is that intentional (i.e., the docs are outdated due to the merge kerfuffle)? 

I'd be fine with removing that option (comma-delimited string) and leave the table (which works fine) as the only supported interface -- having multiple ways to do the same thing is not always a plus...

**Comment by clason** [comment]
Plan: multiple events in one string are not (officially) supported, you should use a table. The documentation will be corrected before 0.7.

**Comment by clason** [comment]
closed by #17545 (removes non-working example from docs)
