### ISSUE TITLE
New split behavior for modern monitors

### ISSUE THREAD

**Issue by IzhakJakov** [neovim/neovim#17676]
### Feature already in Vim?

No.

### Feature description

The current split behavior is less useful when using wide monitors. Which is what most people are using nowadays.

Opening `:help` when the width of vim is longer than the height is annoying since it opens horizontally and need to manually move it to the side.

**(1)** Ability to set the default split: `auto`, `horizontal`, `vertical`
 - `horizontal` basically the way things are right now
 - `vertical` commands that split the view will do it vertically without a need to add the `v`/`V` prefix
 - `auto` would depend on whether the height is longer than the width and vice verse.[^suggestion]
 
**(2)** Add `h`/`H` prefix e.g: `:hsplit` to compliment `:vsplit` or `:Hexplore` for `:Vexplore` (also `:hnew` for `:vnew`, etc.)
 - Otherwise without a prefix use the default split behavior defined by (1)

[^suggestion]: I would suggest this to be the new default, however even if it is not, as long as I can set it in my `init.vim` I would be happy :)

**Comment by PascalZh** [comment]
Seconded

**Comment by justinmk** [comment]
```
:help 'splitright'
:help :vertical

**Comment by IzhakJakov** [comment]
> ```
> :help 'splitright'
> :help :vertical
> ```

Hi @justinmk,

I do not understand how is this what I am talking about?

Maybe you can provide the actual settings that will make vim decide automatically whether to split vertically or horizontally?

**Comment by yochem** [comment]
You could look into using a plugin for this, for example [gomadarecats/autosplit](https://github.com/gomadarecats/autosplit). Maybe I'll write one for neovim.

**Comment by justinmk** [comment]
`:vertical help` opens help files vertically. 

If you want even more control over window layout, that's a big topic and is already covered by https://github.com/neovim/neovim/issues/3933

**Comment by yochem** [comment]
https://github.com/yochem/autosplit.nvim I made the plugin that does exactly this. Let me know what you think!

**Comment by IzhakJakov** [comment]
Haven't tested it but reviewed your code.  It looks pretty good.
Thank you @yochem! 🙏 

I still hope this was native functionality, mainly coz I wanna use `:sp` instead of `:Sp` 😅

**Comment by IzhakJakov** [comment]
Haven't tested it yet but reviewed your code and it looks pretty good 😄 
Thank you @yochem! 🙏 

I still hope this was native functionality, mainly coz I wanna use `:sp` instead of `:Sp` 😅

**Comment by bew** [comment]
> I still hope this was native functionality, mainly coz I wanna use `:sp` instead of `:Sp` sweat_smile

You can always do `:cabbrev sp Sp`, and then `:sp` will auto convert to `:Sp` on enter/space :)

**Comment by yochem** [comment]
> You can always do `:cabbrev sp Sp`, and then `:sp` will auto convert to `:Sp` on enter/space :)

Nice! I'll add it to the readme!

I might also add more functions that split, for example `:vnew`etc. If you're missing something, always welcome to open an issue :)

**Comment by IzhakJakov** [comment]
@bew
> You can always do `:cabbrev sp Sp`, and then `:sp` will auto convert to `:Sp` on enter/space :)

I appreciate your comment actually I already have some abbreviations but still native would be better.
