### ISSUE TITLE
Broken cyrillic encoding in a terminal mode

### ISSUE THREAD

**Issue by javeoff** [neovim/neovim#17681]
### Neovim version (nvim -v)

v0.6.1

### Vim (not Nvim) behaves the same?

no, :!Tig works fine, plugin (terminal mode) :Tig has broken encoding

### Operating system/version

Macos 12.0.1

### Terminal name/version

ITerm 3.4.12

### $TERM environment variable

xterm-new

### Installation

homebrew

### How to reproduce the issue

nvim
:Tig

### Expected behavior

Excepted showing normal cyrilic text with graph lines

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/62588539/157935342-01422fa1-7c24-49a6-8879-806acd6f988b.png">

### Actual behavior

I prefer, that terminal mode doesn't transcribe text to utf-8
this options not work
```
    encoding = 'utf-8';
    termencoding = 'utf-8';
    fileencoding = 'utf-8';
    makeencoding = 'utf-8';
```

I have this format on commits preview. It must be a cyrilic.
Default `tig` shell command works fine

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/62588539/157931016-482af25d-7c0f-4c0a-a2f4-7fc0dc0b696e.png">

**Comment by zeertzjq** [comment]
Please provide minimal steps to reproduce. At least mention what plugin `:Tig` comes from.

**Comment by javeoff** [comment]
It is plugin - portable of terminal command tig for neovim
https://github.com/iberianpig/tig-explorer.vim
```
use {
   'iberianpig/tig-explorer.vim',
   requires = 'rbgrouleff/bclose.vim',
}

Plug 'rbgrouleff/bclose.vim'
Plug  'iberianpig/tig-explorer.vim'
```
Same result with the similar project (equal principle - opens tig in a terminal mode)
https://github.com/codeindulgence/vim-tig

**Comment by javeoff** [comment]
And also the same result only with the terminal `tig` command
```
:terminal
i
tig
```

**Comment by zeertzjq** [comment]
What's you `LANG` environment variable?

**Comment by zeertzjq** [comment]
Possibly related: <https://github.com/neovim/neovim/wiki/FAQ#neovim-cant-read-utf-8-characters>

**Comment by javeoff** [comment]
`export LANG=en_US.UTF-8 ` - **works**! Thank you very much!!!
