### ISSUE TITLE
Number column gets displaced when multiple signs are used

### ISSUE THREAD

**Issue by ObserverOfTime** [neovim/neovim#17693]
### Neovim version (nvim -v)

v0.7.0-dev+1242-gab456bc30

### Vim (not Nvim) behaves the same?

no idea

### Operating system/version

Arch Linux 5.16

### Terminal name/version

konsole 21.12.3

### $TERM environment variable

konsole-256color

### Installation

neovim-git (AUR)

### How to reproduce the issue

* `set number signcolumn=auto:3`
* Create a file with 100+ lines
* Go to a line over 100
* Set 2 icon signs on the line

This displaces the number column by one character **only on the line of the signs**.

The issue also occurs with `signcolumn=auto:1-3`.
Presumably it also occurs on files with fewer than 100 lines.

I cannot actually reproduce the issue with `nvim --clean` but reverting #17533 seems to fix it.
That's why I'm submitting it here instead of trying to figure out which plugin was broken by that change.
Feel free to close it if you think everything's working as intended.

### Expected behavior

The number column consistently moves to the right on all lines.

### Actual behavior

The number column is only displaced on a single line.

**Comment by lewis6991** [comment]
I am not able to reproduce this.

**Comment by ObserverOfTime** [comment]
Guess I'll need to find out which plugin is causing it then.

**Comment by lewis6991** [comment]
I think I might know the issue, drafting a PR you can try.

**Comment by clason** [comment]
(always test with `nvim --clean`)

**Comment by lewis6991** [comment]
#17694 should fix the issue. Ideally, I'd like to add a test to it if we can.

**Comment by ObserverOfTime** [comment]
Yep, that works!

**Comment by lewis6991** [comment]
I tried to reproduce with this but no luck:

```lua
vim.o.number = true
vim.o.signcolumn = 'auto:9'

vim.cmd'normal 300ohello'
vim.cmd'normal 200gg'

local buf = vim.api.nvim_get_current_buf()
local row = vim.api.nvim_win_get_cursor(0)[1]

vim.fn.sign_define('mm', { text = 'XX' })

vim.fn.sign_place(0, 'g', 'mm', buf, {lnum=row})
vim.fn.sign_place(0, 'g', 'mm', buf, {lnum=row})
vim.fn.sign_place(0, 'g', 'mm', buf, {lnum=row})
```

**Comment by lewis6991** [comment]
> Set 2 icon signs on the line

Ah, I'm guessing text signs won't reproduce the issue then?

**Comment by ObserverOfTime** [comment]
I'm not sure, I'd have to try that. But I wasn't able to reproduce the issue with either text or icon signs on `nvim --clean`. I'll try to find which plugin is misbehaving.

**Comment by ObserverOfTime** [comment]
Well, I can't reproduce the issue anymore…
It was likely fixed by some plugin update.

I will close this issue and may reopen if it happens again.
