### ISSUE TITLE
executing nvim command in term mode

### ISSUE THREAD

**Issue by wertasy** [neovim/neovim#17700]
### Feature already in Vim?

No

### Feature description

When executing nvim command in term mode, open the file directly in the current nvim instance instead of starting a new process.

**Comment by zeertzjq** [comment]
This is already achievable using something like `nvim --server $NVIM_LISTEN_ADDRESS --remote-tab {file}`, so the question is whether this should be the default behavior.

**Comment by jamessan** [comment]
Duplicate of #1750

https://github.com/neovim/neovim/issues/1750#issuecomment-162002955
