### ISSUE TITLE
Loads of Missing ':' after '?' errors

### ISSUE THREAD

**Issue by khalidchawtany** [neovim/neovim#17715]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1254-g6dc2c8293

### Vim (not Nvim) behaves the same?

Not relevant

### Operating system/version

MacOS 12.1 (21C52)

### Terminal name/version

iTerm Build 3.4.15

### $TERM environment variable

xterm-256color

### Installation

brew install --HEAD neovim

### How to reproduce the issue

:lua   vim.api.nvim_buf_set_option(175, "filetype", "harpoon")
175 is the bufnumber

Or Install Packer and run PackerSync or PackerUpdate.
Many other plugins show this error

### Expected behavior

No error

### Actual behavior

[packer.nvim] [ERROR 10:32:45] async.lua:20: Error in coroutine: ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:822: Vim(let):E109: Missing ':' after '?'

Also opened an issue for packer: https://github.com/wbthomason/packer.nvim/issues/856

Other plugins show the same error like org-mode and vim-projectionist
OrgMode Error

Error executing vim.schedule lua callback: ...opt/orgmode.nvim/lua/orgmode/colors/todo_highlighter.lua:41: Vim(lua):E5108: Error executing lua ...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:8: Vim(let):E109: Missing ':' after '?'
stack traceback:
	[C]: in function '__newindex'
	...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:8: in function 'setf'
	...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:14: in function 'set_filetype'
	...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:65: in function 'try_lookup'
	...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:154: in function 'resolve'
	[string ":lua"]:1: in main chunk
	[C]: in function 'cmd'
	...opt/orgmode.nvim/lua/orgmode/colors/todo_highlighter.lua:41: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
	[C]: in function 'cmd'
	...opt/orgmode.nvim/lua/orgmode/colors/todo_highlighter.lua:41: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
15 lines yanked

**Comment by zeertzjq** [comment]
Please provide minimal steps to reproduce with `nvim --clean`.

**Comment by clason** [comment]
I'm closing this as you already have a duplicate issue in packer. Feel free to reopen if it's determined there that this is actually a Neovim issue (which I doubt).

**Comment by khalidchawtany** [comment]
I nuked my config and reinstalled everything and the error is gone.
Thanks
