### ISSUE TITLE
Port large refactoring patches from vim

### ISSUE THREAD

**Issue by lewis6991** [neovim/neovim#17730]
Whilst trying to tidy up `screen.c`, I noticed vim has now refactored this into 3 files: `screen.c`, `drawscreen.c` and `drawline.c`.

Whilst trying to port this patch I noticed It depended on some other rather large refactoring patches (listed below).

In all of these files, Neovim has diverged quite a bit in places. For example Neovim's  `highlight.c` is 100% different from vim's `highlight.c` as they serve different purposes.

I think these patches are worth porting over here, but given the complexity, shouldn't be treated as normal vim patches as they can't really be automated at all.

This issue serves as a tracking issue for such patches we want to port over.

## Patches

<ul>
<li>
<code>patch 8.1.1693: syntax coloring and highlighting is in one big file</code>

- [x] PR: #17721 
</li>

<li>
<code>patch 8.1.1734: the evalfunc.c file is too big</code>

<code>patch:8.1.1742: still some match functions in evalfunc.c</code>

 <code>patch 8.1.1743: 'hlsearch' and match highlighting in the wrong place</code>
  
- [x] PR: #17760

</li>

<li>
<code>patch 8.2.1078: highlight and match functionality together in one file</code>

- [x] PR: #17805
</li>

<li>
<code>patch 8.1.1608: the evalfunc.c file is too big</code>

- [x] PR: #17807
</li>

<li>
<code>patch 8.1.1687: the evalfunc.c file is too big</code>

- [x] PR: #17949
</li>

<li>
<code>patch 8.1.1763: evalfunc.c is still too big</code>

- [x] PR: #17952
</li>

<li>
<code>patch 8.1.1933: the eval.c file is too big</code>

- [x] PR: #19462
</li>

<li>
<code>patch 8.1.2057: the screen.c file is much too big</code>

- [x] PR: #19802
</li>

<li>
<code>patch:8.1.1076: file for Insert mode is much too big</code>

- [x] PR: #19415
</li>

</ul>

## NA Patches

<ul>

<li>
<details>
  <summary><code>patch 8.1.1584: the evalfunc.c file is getting too big</code></summary>

```
    patch 8.1.1584: the evalfunc.c file is getting too big

    Problem:    The evalfunc.c file is getting too big.
    Solution:   Move channel and job related functions to channel.c.
```

</details>

Reason: Neovim uses a different channel implementation.

</li>

<li>
<details>
  <summary><code>v8.1.1607: the evalfunc.c file is too big</code></summary>

Commit message is for patch 8.1.1607, but change adds popup related stuff.

</details>

Reason: Neovim uses floating windows instead of popups.

</li>

</ul>

## Other changes to consider

_Not investigated relevancy or if already in Neovim_
```
  • v8.1.1763: evalfunc.c is still too big
  • v8.1.1978: the eval.c file is too big
  • v8.1.1981: the evalfunc.c file is too big
  • v8.1.1989: the evalfunc.c file is still too big
  • v8.1.2001: some source files are too big
  • v8.1.2022: the option.c file is too big
  • v8.1.2042: the evalfunc.c file is too big
  • v8.1.2045: the option.c file is too big
  • v8.1.2077: the ops.c file is too big
  • v8.1.2094: the fileio.c file is too big

patch 8.1.1966: some code in options.c fits better elsewhere
https://github.com/vim/vim/commit/e677df8d93772a705f40a94f3c871aee78fe4d99

patch 8.1.2081: the spell.c file is too big
https://github.com/vim/vim/commit/46a426c9acfdd3d6c0fa134a17681634b9325bee

patch 8.2.0660: the search.c file is a bit big
https://github.com/vim/vim/commit/ed8ce057b7a2fcd89b5f55680ae8f85d62a992a5

patch 8.2.0674: some source files are too big
https://github.com/vim/vim/commit/11abd095210fc84e5dcee87b9baed86061caefe4

patch 8.2.0847: typval related code is spread out
https://github.com/vim/vim/commit/367d59e6ba65cf554d167933775fa17e40dcc6a7

patch 8.2.1262: src/ex_cmds.c file is too big
https://github.com/vim/vim/commit/f868ba89039045b25efe83d12ca501d657e170e8

patch 8.2.1269: language and locale code spread out
https://github.com/vim/vim/commit/054f14bbe58fece17f1a74ca63f0b37518f0b4de
```

**Comment by bfredl** [comment]
I think we need to consider screen.c as it has diverged quite significantly. I'd like to separate out `grid.c` from `screen.c` with most of the lowlevel `grid_` functions. Perhaps drawscreen.c and/or drawline.c still makes sense after that tho.

**Comment by bfredl** [comment]
commented over there :]
