### ISSUE TITLE
`synIDattr(synID(line("."),col("."),1)` randomly reports erroneous syntax ID

### ISSUE THREAD

**Issue by jeffschwartz** [neovim/neovim#17746]
### Neovim version (nvim -v)

0.6..1

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macos 12.2.1

### Terminal name/version

iTerm2 Build 3.4.15

### $TERM environment variable

xterm-256color

### Installation

Homebrew

### How to reproduce the issue

1. Add the following to init.vim to be able to see what syntax ID nvim reports for the current cursor location.
```vim
nnoremap <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>

```

2. :touch test.js

3. :nvim test.js

4. Create a comment block as follows:
```javascript
/*

*/
```

3. Position the cursor in the blank line between the opening and closing comment markers.

4. Press function key 10 to see what syntax ID nvim reports.

### Expected behavior

nvim should report the current syntax ID as follows:

```vim
hi<javaScriptComment> trans<javaScriptComment> lo<Comment>
```

### Actual behavior

nvim randomly returns either

```vim
hi<javaScriptComment> trans<javaScriptComment> lo<Comment>
```
or

```vim
hi<> trans<> lo<>
```

**Comment by jeffschwartz** [comment]
I  hit upon this while using the cosco plugin for colon and semi colon line autocompletion. I configured the plugin to ignore comments but it wasn't ignoring them. I then forked the cosco plugin's repo so that I can sherlock the issue, believing it to be responsible. However, the code responsible for ignoring comments was correct. 

I then removed the cosco plugin in order to eliminate it entirely as a possible source of the issue but I still got the same results.

**Comment by jeffschwartz** [comment]
@lfilho same results as I reported [here](https://github.com/lfilho/cosco.vim/issues/28#issuecomment-1069403355).

**Comment by jeffschwartz** [comment]
As per the suggestion from @lfilho I ran nvim using  `nvim -u test.init.vim --noplugin`. The init file only contained the following so I can test what syntax ID nvim reported:
```vim
 nnoremap <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
```
Even with no plugins it reported `hi<> trans<> lo<>` when the cursor was on an empty comment line. I've also seen it do the same when the cursor was on a comment line that contained text.

**Comment by jeffschwartz** [comment]
Thinking that it might be limited to v0.6.1, I upgraded to nightly NVIM v0.7.0-dev+1277-g9e66d27d3. Unfortunately that does not resolve the issue.

**Comment by name-snrl** [comment]
nvim -v
NVIM v0.8.0-dev

I've the same problem for lua, nix, sh languages. But it works fine with vimL, for example. To reproduce run this line - :lua =vim.fn.synID(line, column, 1)

**Comment by jeffschwartz** [comment]
Is this ever going to be addressed?

**Comment by clason** [comment]
I think there might be a misconception here. The `synID` function returns the syntax ID at the given position. However, if you run this on an empty line, you do not get a valid position (the line is empty, after all!), so you do not get a valid ID. So that part is expected, and indeed Vim behaves exactly the same. 

The situation is different if you have have whitespace character at the start of the second line -- so the line is "blank" but not "empty"; then you get a valid position on that character and hence a valid ID. I suspect that is the source of your "randomness", which I cannot reproduce -- for given contents and position, I always get the exact same (and expected) result.
