### ISSUE TITLE
Support environment variables and ~ in create_autocmds patterns

### ISSUE THREAD

**Issue by AckslD** [neovim/neovim#17744]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1260-gaa35d15a0

### Vim (not Nvim) behaves the same?

No

### Operating system/version

arch linux 5.16.14-arch1-1

### Terminal name/version

kitty 0.24.4

### $TERM environment variable

xterm-kitty

### Installation

AUR

### How to reproduce the issue

nvim -u NONE
:lua vim.api.nvim_create_autocmd('BufWritePost', {command = 'echo "test"', pattern = '~/some_file'})
e ~/some_file

### Expected behavior

see "test" printed

### Actual behavior

"test" is not printed.

If you define autocmds in vimscript both `~/some_file` and `$HOME/some_file` works but neither work in the lua api.
From `:h autocmd-pattern`:
```
Environment variables can be used in a pattern: >
	:autocmd BufRead $VIMRUNTIME/doc/*.txt  set expandtab
And ~ can be used for the home directory (if $HOME is defined): >
	:autocmd BufWritePost ~/.config/nvim/init.vim   so <afile>
	:autocmd BufRead ~archive/*      set readonly
The environment variable is expanded when the autocommand is defined, not when
the autocommand is executed.  This is different from the command!
```

Not sure if this is a bug report or feature request though.

**Comment by clason** [comment]
Feature request. As far as I know, such expansion does not happen automatically throughout the API. (And it's easier to opt in via `expand` than to opt out, so I'd be wary about adding such magic.)

**Comment by AckslD** [comment]
One just needs to be careful not doing eg
```lua
pattern = vim.fn.expand('~/some/path/*')
```
since this will also expand the glob, but rather:
```lua
pattern = vim.fn.expand('~') .. '/some/path/*'
```
or
```lua
pattern = vim.fn.expand('~/some/path/') .. '*'
```

Being able to do
```lua
pattern = '~/some/path/*'
```
would be a bit cleaner imo

**Comment by clason** [comment]
I still think this should be left for a (personal) Lua convenience API on top of `nvim_create_autocmd`.

**Comment by jsatt** [comment]
+1 for fixing automatically expansion. Since the standard vim autocmd automatically handles expansion it seems reasonable to expect nvim_create_autocmd to also work the same way. Especially considering the help for nvim_create_autocmd directs you to autocmd-pattern for reference, stating that environment variable and `~` are handled. https://github.com/neovim/neovim/blob/master/runtime/doc/autocmd.txt#L1155-L1157
