### ISSUE TITLE
Semantic versioning with semver.org for neovim.

### ISSUE THREAD

**Issue by vanesyan** [neovim/neovim#1775]
[Semantic versioning](http://semver.org/). I think it's better to switch version from 0.0.0-alpha to 0.1.0 and increment it in the feature:

**The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.**

It allow you make release-circle in feature, when neovim get 1.0. Please, think about it :)

**Comment by fwalch** [comment]
From https://github.com/neovim/neovim/issues/1625#issuecomment-66320618:



>>When you do circle back to discuss versioning

>This is covered by #862.
FYI, the version reported by :version is structured according to http://semver.org:
```
0.0.0-alpha+201412081823
^ ^ ^ ^     ^
| | | |      `build metadata
| | | `pre-release
| | `patch
| `minor
`major
```

**Comment by vanesyan** [comment]
Oh, Okay. Thanks :) I close issue)
