### ISSUE TITLE
segfault with `:function` for Russian locale

### ISSUE THREAD

**Issue by matveyt** [neovim/neovim#17759]
### Neovim version (nvim -v)

v0.7.0-dev+1275-g00effff56; also the same for v0.6.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Kali GNU/Linux 5.16.0

### Terminal name/version

LXTerminal 0.4.0

### $TERM environment variable

xterm256-color

### Installation

no matter

### How to reproduce the issue

    nvim --clean
    :function foobar

### Expected behavior

    E128: Function name must start with a capital or "s:": foobar

### Actual behavior

Application crash.

**Comment by clason** [comment]
I cannot reproduce this, so installation _does_ matter.

**Comment by matveyt** [comment]
@clason 

Really no matter.

```
$ mkdir ~/test
$ cd ~/test
$ wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
$ chmod u+x ./nvim.appimage
$ ./nvim.appimage --clean
:function foobar
```

**Comment by clason** [comment]
Really matter.

**Comment by dundargoc** [comment]
Cannot reproduce either, tested on both nightly and the nvim Appimage on lxterminal. Maybe something specific to Kali Linux?

**Comment by dundargoc** [comment]
Tested on latest kali docker image, couldn't reproduce there either :/.

**Comment by matveyt** [comment]
The only specific thing is that function name cannot start with a small letter (this is why `E128` is expected). The latest build on Win11 crashes as well.

**Comment by clason** [comment]
Yes, but I get exactly the described expected behavior with your example. So something must be wrong with your build, and we need to figure out what.

**Comment by matveyt** [comment]
Okay, this is l10n bug. Occurs only with Russian locale.

```
:let $LANG="ru"
:func foobar
```

**Comment by dundargoc** [comment]
> Okay, this is l10n bug. Occurs only with Russian locale.
> 
> ```
> :let $LANG="ru"
> :func foobar
> ```

Can't reproduce with this either. There's more going on.

**Comment by zeertzjq** [comment]
I can reproduce this after adding `ru_RU.UTF-8 UTF-8` to `/etc/locale.gen` and running `sudo locale-gen`.

**Comment by clason** [comment]
Ah, then this is very likely a broken translation file from an automated runtime file update (mea culpa!)

**Comment by clason** [comment]
stab in the dark, but can you try removing this line: https://github.com/neovim/neovim/blob/0a81a33a9d0fe6c61ab98da0c0212b3b343f3591/src/nvim/po/ru.po#L962
and rebuilding?

**Comment by matveyt** [comment]
@clason 
Yes, it works. Just run `msgfmt ru.po` and moved the resulting file where it belongs. It appears as all fixed.

**Comment by zeertzjq** [comment]
That causes the error message to contain two `%s`, while only one additional argument is passed to `semsg()`, which cause `str_arg` to be an invalid value at the second `%s` here:
<https://github.com/neovim/neovim/blob/0a81a33a9d0fe6c61ab98da0c0212b3b343f3591/src/nvim/strings.c#L982>

**Comment by clason** [comment]
> @clason
> Yes, it works. Just run `msgfmt ru.po` and moved the resulting file where it belongs. It appears as all fixed.

Want to make a PR?

(I didn't see this line in another translation, so it's likely spurious.)

**Comment by matveyt** [comment]
Okay, I'll do it. Have to read through it at first though. I see at least one more message (E883) was truncated.

**Comment by clason** [comment]
If there are other problems you can fix at the same time, go for it!
