### ISSUE TITLE
grep is broken I think?

### ISSUE THREAD

**Issue by frioux** [neovim/neovim#1776]
I use fugitive from tim pope to `git grep` into the quickfix.  I noticed #473 and thought: "cool!  this will be a neat thing to try and see if it's faster!"

In vanilla vim, I go into a project and do `:Ggrep foo`, see a million lines scroll by, press Enter, and then I can iterate over the quickfix list as normal.

In neovim I do `:Ggrep foo`, see exactly a console worth of lines, and nvim is not responsive.  If I Ctrl-C and then hit enter it works as vim did.  This seems to be a pretty clear regression to me.

**Comment by fwalch** [comment]
For me, nvim and vim behave exactly the same with current nvim (050c6515f80b4964d7d9a7b66fa95146a4f38e4c).

**Comment by justinmk** [comment]
@fwalch Try `:Ggrep a` in the neovim source, and wait until the end. Seems like once it gets to multibyte output it starts incorrectly interpreting some byte sequences as terminal codes. It gets unresponsive, then eventually recovers after mashing ctrl-c and enter, but the display is now hosed. Here's what I see, pasted from my terminal:

```

↓ "$CI_SCRIPTS/c⎺└└⎺┼↓⎽▒"

⎽┤d⎺ ⎻☃⎻ ☃┼⎽├▒┌┌ c⎻⎻↑c⎺┴e⎼▒┌┌⎽

☃° [ "$TRAVIS_OS_NAME" = "┌☃┼┤│" ]; ├▒e┼
▸       c┌▒┼±_┴e⎼⎽☃⎺┼=3↓4↓2
▸       c┌▒┼±_⎽┤°°☃│=│86_64↑┤┼┐┼⎺┬┼↑┤b┤┼├┤12↓▮4↓│≥
e┌☃° [ "$TRAVIS_OS_NAME" = "⎺⎽│" ]; ├▒e┼
▸       c┌▒┼±_┴e⎼⎽☃⎺┼=3↓5↓▮
▸       c┌▒┼±_⎽┤°°☃│=└▒c⎺⎽│↑▒⎻⎻┌e↑d▒⎼┬☃┼↓├▒⎼↓│≥
e┌⎽e
▸       ec▒⎺ "U┼┐┼⎺┬┼ OS '$TRAVIS_OS_NAME'↓"
▸       e│☃├ 1
°☃

☃° [ ! ↑d /┤⎽⎼/┌⎺c▒┌/c┌▒┼±↑$c┌▒┼±_┴e⎼⎽☃⎺┼ ]; ├▒e┼
▸       ec▒⎺ "D⎺┬┼┌⎺▒d☃┼± c┌▒┼± $c┌▒┼±_┴e⎼⎽☃⎺┼↓↓↓"
▸       ⎽┤d⎺ └┐d☃⎼ /┤⎽⎼/┌⎺c▒┌/c┌▒┼±↑$c┌▒┼±_┴e⎼⎽☃⎺┼
▸       ┬±e├ ↑─ ↑O ↑ ▒├├⎻://┌┌┴└↓⎺⎼±/⎼e┌e▒⎽e⎽/$c┌▒┼±_┴e⎼⎽☃⎺┼/c┌▒┼±→┌┌┴└↑$c┌▒┼±_┴e⎼⎽☃⎺┼↑$c┌▒┼±_⎽┤°°☃│ \
▸       ▸       ≠ ⎽┤d⎺ ├▒⎼ │J° ↑ ↑↑⎽├⎼☃⎻↑c⎺└⎻⎺┼e┼├⎽=1 ↑C /┤⎽⎼/┌⎺c▒┌/c┌▒┼±↑$c┌▒┼±_┴e⎼⎽☃⎺┼
°☃

e│⎻⎺⎼├ CC=/┤⎽⎼/┌⎺c▒┌/c┌▒┼±↑$c┌▒┼±_┴e⎼⎽☃⎺┼/b☃┼/c┌▒┼±
⎽≤└b⎺┌☃≥e⎼=/┤⎽⎼/┌⎺c▒┌/c┌▒┼±↑$c┌▒┼±_┴e⎼⎽☃⎺┼/b☃┼/┌┌┴└↑⎽≤└b⎺┌☃≥e⎼

⎽e├┤⎻_de⎻⎽ │64

e│⎻⎺⎼├ ASAN_SYMBOLIZER_PATH=$⎽≤└b⎺┌☃≥e⎼
e│⎻⎺⎼├ ASAN_OPTIONS="de├ec├_┌e▒┐⎽=1:┌⎺±_⎻▒├▒=$├└⎻d☃⎼/▒⎽▒┼"
e│⎻⎺⎼├ TSAN_OPTIONS="e│├e⎼┼▒┌_⎽≤└b⎺┌☃≥e⎼_⎻▒├▒=$⎽≤└b⎺┌☃≥e⎼:┌⎺±_⎻▒├▒=$├└⎻d☃⎼/├⎽▒┼"

e│⎻⎺⎼├ UBSAN_OPTIONS="┌⎺±_⎻▒├▒=$├└⎻d☃⎼/┤b⎽▒┼" # ┼⎺├ ⎽┤⎼e ☃° ├▒☃⎽ ┬⎺⎼┐⎽

CMAKE_EXTRA_FLAGS="↑DTRAVIS_CI_BUILD=ON \
▸       ↑DUSE_GCOV=ON \
▸       ↑DBUSTED_OUTPUT_TYPE=⎻┌▒☃┼Te⎼└☃┼▒┌"

# B┤☃┌d ▒┼d ⎺┤├⎻┤├ ┴e⎼⎽☃⎺┼ ☃┼°⎺↓
$MAKE_CMD CMAKE_EXTRA_FLAGS="$CMAKE_EXTRA_FLAGS ↑DSANITIZE=ON" ┼┴☃└
b┤☃┌d/b☃┼/┼┴☃└ ↑↑┴e⎼⎽☃⎺┼

# R┤┼ °┤┼c├☃⎺┼▒┌ ├e⎽├⎽↓
 ↓c☃/c┌▒┼±↑▒⎽▒┼↓⎽▒                                                                                                                                                T⎺⎻▒▒▒▒▒▒▒▒▒▒▒▒▒▒       ┤├°↑8 [⎽▒] 1←1
↓c☃/c┌▒┼±↑▒⎽▒┼↓⎽▒≠1≠ ↓ "$CI_SCRIPTS/c⎺└└⎺┼↓⎽▒"
↓c☃/c┌▒┼±↑▒⎽▒┼↓⎽▒≠12≠ ec▒⎺ "U┼┐┼⎺┬┼ OS '$TRAVIS_OS_NAME'↓"
↓c☃/c┌▒┼±↑▒⎽▒┼↓⎽▒≠13≠ e│☃├ 1
↓c☃/c┌▒┼±↑▒⎽▒┼↓⎽▒≠16≠ ☃° [ ! ↑d /┤⎽⎼/┌⎺c▒┌/c┌▒┼±↑$c┌▒┼±_┴e⎼⎽☃⎺┼ ]; ├▒e┼
↓c☃/c┌▒┼±↑▒⎽▒┼↓⎽▒≠19≠ ┬±e├ ↑─ ↑O ↑ ▒├├⎻://┌┌┴└↓⎺⎼±/⎼e┌e▒⎽e⎽/$c┌▒┼±_┴e⎼⎽☃⎺┼/c┌▒┼±→┌┌┴└↑$c┌▒┼±_┴e⎼⎽☃⎺┼↑$c┌▒┼±_⎽┤°°☃│ \
↓c☃/c┌▒┼±↑▒⎽▒┼↓⎽▒≠2▮≠ ≠ ⎽┤d⎺ ├▒⎼ │J° ↑ ↑↑⎽├⎼☃⎻↑c⎺└⎻⎺┼e┼├⎽=1 ↑C /┤⎽⎼/┌⎺c▒┌/c┌▒┼±↑$c┌▒┼±_┴e⎼⎽☃⎺┼
↓c☃/c┌▒┼±↑▒⎽▒┼↓⎽▒≠29≠ e│⎻⎺⎼├ ASAN_OPTIONS="de├ec├_┌e▒┐⎽=1:┌⎺±_⎻▒├▒=$├└⎻d☃⎼/▒⎽▒┼"
↓c☃/c┌▒┼±↑▒⎽▒┼↓⎽▒≠45≠ e│☃├ 1
↓c☃/c┌▒┼±↑▒⎽▒┼↓⎽▒≠53≠ e│☃├ 1
↓c☃/c┌▒┼±↑▒⎽▒┼↓⎽▒≠57≠ c⎺┴e⎼▒┌┌⎽ ↑↑e┼c⎺d☃┼± ☃⎽⎺↑8859↑1 ≠≠ ec▒⎺ 'c⎺┴e⎼▒┌┌⎽ ┤⎻┌⎺▒d °▒☃┌ed↓'
```

**Comment by justinmk** [comment]
Even when I quit `nvim`, my terminal remains messed up:

```
SSH ┤b┤┼├┤@┤b┤┼├┤ ·/┼e⎺┴☃└ (└▒⎽├e⎼ ┤=)
$
SSH ┤b┤┼├┤@┤b┤┼├┤ ·/┼e⎺┴☃└ (└▒⎽├e⎼ ┤=)
$
```

It *should* look like this:

```
SSH ubuntu@ubuntu ~/neovim (master u=)
$
SSH ubuntu@ubuntu ~/neovim (master u=)
$
```

**Comment by fwalch** [comment]
Hm, it's different for me with `:Ggrep a`: it scrolls till the end, and prompts for ENTER. Pressing enter, the screen turns completely blank. CTRL-C doesn't do anything. After waiting for a while (like a minute), nvim's interface returns and I can iterate over the quickfix list.

Any Git config options that could influence that? Or maybe OS X/Linux difference?

**Comment by frioux** [comment]
For what it's worth I'm on linux (ubuntu 14.10) using the nvim ppa (NVIM 0.0.0-alpha (compiled Jan  6 2015 01:50:50)).

@justinmk by the way, if something leaves your terminal like that (raw mode I think?) you can run the command `reset` and it will fix it.  Might be helpful for debugging this.

**Comment by frioux** [comment]
@fwalch if you wanna check gitconfig stuff, my config is at https://github.com/frioux/dotfiles/blob/master/gitconfig

**Comment by justinmk** [comment]
Not sure. I'm using mintty to ssh to a ubuntu linux console.

Just tried with **vim 7.4.430 and the same display breakage occurs**. And `reset` worked, thanks.

**Comment by frioux** [comment]
Huh!  Well, for what it's worth the vim I have is

      VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 20 2014 16:09:34)
       Included patches: 1-273

from the ubuntu repos.  So maybe one of the 200~ patches caused the issue?

**Comment by fwalch** [comment]
@justinmk So the CI scripts are at the end of your `Ggrep` output? For me, the first entry in the quickfix list is `clang-asan.sh`, and the last matches before it prompts for Enter are in uncrustify.cfg.

**Comment by justinmk** [comment]
@fwalch No, I `Ggrep` jumps to the first result, so that's where that was coming from.

**Comment by fwalch** [comment]
@justinmk Right, that makes sense.

**Comment by fmoralesc** [comment]
For me it behaves just like for @fwalch. Something similar happens even with vim 7.4.560 (latest). For me, `:Ggrep foo` (at the root of neovim repo) and `:Ggrep fo` works the same in both nvim and vim (like @fwalch reports), but `:Ggrep fo` takes a long long time (~30s) to react *after* the prompt to press ENTER. It seems like vim-fugitive chockes on the amount of data it receives (68604 entries in the quickfixlist). I don't get the corruption even with `:Ggrep a` (with 420425 matches), but it becomes entirely unresponsive.

The other issue might come from the interaction of nvim and the terminal. What terminal are you using, and what is the value of $TERM? (I'm using `gnome-terminal` with `xterm-256color`).

**Comment by frioux** [comment]
I'm using `terminator`/`tmux` with `screen-256color`.  FWIW **I** don't see the corruption issue, but that could just be the repo I'm sampling.

**Comment by fmoralesc** [comment]
Can you reproduce outside of tmux? I've noticed some issues with the rendering there: #1669

**Comment by frioux** [comment]
For me, tmux makes no difference either way.

**Comment by justinmk** [comment]
The [original issue](https://github.com/neovim/neovim/issues/1776#issue-53532164) here was resolved by https://github.com/neovim/neovim/pull/5396 combined with Vim's own quickfix patches merged by @jamessan.
