### ISSUE TITLE
Global Status Line should respect SignColumn and LineNr

### ISSUE THREAD

**Issue by shaeinst** [neovim/neovim#17769]
### Feature description

![image](https://user-images.githubusercontent.com/41078534/159058162-9c10ff92-6696-455f-b894-4b18f593d90b.png)

**Comment by mjlbach** [comment]
The issue template isn't optional, you can't draw arrows on a picture and expect anyone to infer what you mean.

**Comment by shaeinst** [comment]
My language is not english, it's very hard  for me to explain things in english. that's why i tried my best to write a good title and attached Screenshot so that it would make sense.
but you could just asked me for proper explanation but no, you just wrote angry replay and clicked on close. this community becoming toxic.
>The issue template isn't optional, you can't draw arrows on a picture and expect anyone to infer what you mean.

**Comment by clason** [comment]
I'm sorry, but the title is not a replacement for the issue description. Even an auto-translated request would have been better; as it is, there's no way of knowing what you mean by "respect".

And issues can always be reopened if they're edited and turn out to be valid.

**Comment by clason** [comment]
(And I can't help but notice that your comment was perfectly fine English, including the idiomatic use of the word "toxic".)

**Comment by mjlbach** [comment]
People did not understand your comment on [reddit](https://www.reddit.com/r/neovim/comments/th52yw/i_think_global_status_line_should_support_to/i16gvui/), why would we be able to infer the meaning of the screenshot anymore here? If you have trouble writing up the description, perhaps ask on the neovim matrix for help with the translation, or use google translate.

My reply was longer than your issue description, and included why I was closing the issue. If you want to call that toxic, so be it.

**Comment by shaeinst** [comment]
@mjlbach your replay wasn't wrong, but closing the issue was totally disrespect.

**Comment by bfredl** [comment]
The issue will be reopened whenever the information in the issue template is provided.

**Comment by shaeinst** [comment]
@bfredl thanks.
