### ISSUE TITLE
"ş" cannot be assigned as leader with the 'vim.g.mapleader' and 'vim.g.maplocalleader' in the related lua file

### ISSUE THREAD

**Issue by HakKet** [neovim/neovim#17764]
### Neovim version (nvim -v)

nvim-qt v0.7.0-dev+727-g326e74 571

### Vim (not Nvim) behaves the same?

No. gvim version 8.2.4567

### Operating system/version

Windows 10 version: 10.0.19043.1586

### Terminal name/version

cmd

### $TERM environment variable

-

### Installation

chocolatey

### How to reproduce the issue

vim.g.mapleader = "ş" 
vim.g.maplocalleader = "ş"

### Expected behavior

Expected behavior is to assign the "ş" as the leader.

### Actual behavior

No leader is assigned.

Any other non-us character can be assigned.

**Comment by clason** [comment]
To be clear, it's _only_ this specific character that is a problem?

**Comment by HakKet** [comment]
> To be clear, it's _only_ this specific character that is a problem? What does `echo mapleader` show?

It shows the character which is "ş" in my case.
Seems like the character is assigned but is not behaving like the leader??

**Comment by clason** [comment]
It would help to state what exactly you mean by "no leader is assigned" (as the leader is clearly assigned...)

**Comment by zeertzjq** [comment]
If you create a mapping directly using `:map`, does it work?

**Comment by clason** [comment]
And, just for the sake of completeness, `let mapleader="ş"` in your `init.vim` _does_ work as expected?

**Comment by HakKet** [comment]
> It would help to state what exactly you mean by "no leader is assigned" (as the leader is clearly assigned...)

It works.
I am closing this.
Thank you very much.

**Comment by HakKet** [comment]
> And, just for the sake of completeness, `let mapleader="ş"` in your `init.vim` _does_ work as expected?

It does. It works without any problem.
Sorry for replying late.
