### ISSUE TITLE
Indent rules from clint.py are inconsistent

### ISSUE THREAD

**Issue by kylo252** [neovim/neovim#17763]
### Feature already in Vim?

NA

### Feature description

The `whitespace/indent` rules specifically appear to be either broken or mis-configured

https://github.com/neovim/neovim/blob/3830960cff2e080b980c283cacf2bcd75afe5454/src/clint.py#L2915-L2921

why would the inner expression indentation be set (hard-coded) to `4` when the global indentation is `2`?
https://github.com/neovim/neovim/blob/3830960cff2e080b980c283cacf2bcd75afe5454/src/clint.py#L2118-L2123

---

**Example**
```console 
src/nvim/shada.c:3319:  Weird number of spaces at line-start.  Are you using a 2-space indent?  [whitespace/indent] [3]
```
```c
#define CHECK_KEY(key, expected) \
  ((key).via.str.size == sizeof(expected) - 1 \
   && STRNCMP((key).via.str.ptr, expected, sizeof(expected) - 1) == 0)
```
while adding two extra spaces for _each_ line fixes it
```c
#define CHECK_KEY(key, expected) \
    ((key).via.str.size == sizeof(expected) - 1 \
     && STRNCMP((key).via.str.ptr, expected, sizeof(expected) - 1) == 0)
```

Neither `clang-format` nor `uncrustify` is able to consistently keep up with this, at least I wasn't able to configure them, so we end up alternating between the two tools for each error, with a mixture of manual editing and trial and error to get around this.

**Comment by zeertzjq** [comment]
Hmm, this entry in `uncrustify.cfg`:
<https://github.com/neovim/neovim/blob/233014f92b5d4d5bf8a6f019241aafd1b05dd383/src/uncrustify.cfg#L1052>
does not match this:
<https://github.com/neovim/neovim/blob/233014f92b5d4d5bf8a6f019241aafd1b05dd383/runtime/doc/dev_style.txt#L868>

**Comment by dundargoc** [comment]
If we set `indent_continue = 4` clint will warn about `Inner expression should be aligned as opening brace + 1`. Not sure how it's possible to satisfy both "this should have an indent of 4" but also "must have 1 space after parenthesis" rule.

**Comment by zeertzjq** [comment]
Oh...

**Comment by dundargoc** [comment]
Hardcoding the exact alignment of inner expression is probably the single most disruptive style rule of neovim. I've had to sacrifice all formatting of ternary operators in order to satisfy this rule.

**Comment by kylo252** [comment]
@dundargoc, semi related, would it be possible to either update or lock `uncrustify.cfg` to an actual version? I keep getting these complaints 

```log
Option<NUM>: at src/uncrustify.cfg:1182: Expected number , for 'indent_shift'; got 'false'
Option<NUM>: at src/uncrustify.cfg:1356: Expected number , for 'indent_comma_brace'; got 'false'
Option<NUM>: at src/uncrustify.cfg:1360: Expected number , for 'indent_comma_paren'; got 'false'
Option<NUM>: at src/uncrustify.cfg:1364: Expected number , for 'indent_bool_paren'; got 'false'
```
this is what I'm using 

```console
$ uncrustify --version
Uncrustify-0.74.0-203-9bdb790e0
```
and this is the rule

https://github.com/neovim/neovim/blob/d7cbb071218307722f5445374b54f4b47b63a4f1/src/uncrustify.cfg#L1

I think these rules are "tuneable" as of late.

**Comment by dundargoc** [comment]
The uncrustify config is "locked" to 0.74, the latest stable. You can update the config file to a newer uncrustify version by using

```
uncrustify -c uncrustify.cfg --update-config-with-doc -o uncrustify.cfg
```

This will update the uncrustify config to a newer version using the options from the old uncrustify config.

**Comment by kylo252** [comment]
> The uncrustify config is "locked" to 0.74, the latest stable. You can update the config file to a newer uncrustify version by using
> 
> ```
> uncrustify -c uncrustify.cfg --update-config-with-doc -o uncrustify.cfg
> ```
> 
> This will update the uncrustify config to a newer version using the options from the old uncrustify config.

thanks for the clarification! I was wondering what the "update" part meant, since I've been basically running this to generate a new file and then merge them manually
```shell
uncrustify --update-config-with-doc -o src/uncrustify_new.cfg
```
even the help output is misleading...

```console
$ uncrustify --help
...
Config/Help Options:
 -h -? --help --usage     : Print this message and exit.
 --version                : Print the version and exit.
 --count-options          : Print the number of available options and exit.
 --show-config            : Print out option documentation and exit.
 --update-config          : Output a new config file. Use with -o FILE.
 --update-config-with-doc : Output a new config file. Use with -o FILE.
 --universalindent        : Output a config file for Universal Indent GUI.
 --detect                 : Detects the config from a source file. Use with '-f FILE'.
                            Detection is fairly limited.
 --set <option>=<value>   : Sets a new value to a config option.
  ...
```

**Comment by justinmk** [comment]
> Hardcoding the exact alignment of inner expression is probably the single most disruptive style rule of neovim. I've had to sacrifice all formatting of ternary operators in order to satisfy this rule.

Personally I'd be in favor of relaxing this, if it significantly helps us automate formatting & linting. @bfredl  @jamessan  ?

**Comment by bfredl** [comment]
Yes. I think it is a good default, but we don't need to strictly enforce it.
