### ISSUE TITLE
Random cursor movement when some window is rendering using `laststatus=3` and `set lazyredraw`

### ISSUE THREAD

**Issue by etrnal70** [neovim/neovim#17765]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1277-g9e66d27d3

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch LInux

### Terminal name/version

alacritty 0.10.1,  kitty 0.24.4 (less observable)

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```lua
local packer_exists = pcall(vim.cmd, [[packadd packer.nvim]])
local packer = require("packer")
local load_plugin = function()
  return packer.startup({
    function(use)
      use({ "wbthomason/packer.nvim" })
      use({
        "rcarriga/nvim-notify",
        config = function()
          vim.notify = require("notify")
          require("notify").setup({
            background_colour = "#000000",
            render = "minimal",
            stages = "fade",
          })
        end,
      })
    end,
  })
end
vim.opt.lazyredraw = true
vim.opt.laststatus = 3
vim.opt.termguicolors = true
load_plugin()
```

1. nvim
2. Split vertical
3. Move to new split
4. Split horizontal
5. Move to new horizontal split
6. `:lua vim.notify("Hello")`
7. Cursor blinking in the intersection

### Expected behavior

Cursor stays on the buffer

### Actual behavior

https://user-images.githubusercontent.com/5826834/159028983-9b55be45-e9e2-4e71-b3ce-2455cec4596e.mp4

I've found out that it's `lazyredraw` that trigger this. Sorry cannot create a more minimal repro

EDIT: Apparently, i can reproduce it to albeit in an extremely rare case (i don't even know what i pressed, just quickly editing some text, and it suddenly blinking and moving for a sec) when `lazyredraw` is disabled.

**Comment by dundargoc** [comment]
Cannot recreate.

**Comment by dundargoc** [comment]
What is that popupwindow in the upper right? It's very sus.

**Comment by etrnal70** [comment]
Yeah it's the nvim-notify plugin. You can notice it that when the fade animation happens, the cursor starts moving, hence why i think the random movement happens where there is a window redrawing fast. I use that plugin since so far it's the easiest way to reproduce this. Before this, there's this issue https://github.com/neovim/neovim/pull/17266#issuecomment-1030713114 too but it's quite hard to reproduce

**Comment by etrnal70** [comment]
Another strange part is that it only happens when this particular layout is created

```
┌───────────┬───────────┐
│           │           │
│           │           │
│           ├───────────┤
│           │           │
│           │           │
└───────────┴───────────┘
```

If i add an extra split like below, the problem gone :/

```
┌───────────┬───────────┐
│           │           │
│           │           │
├───────────┼───────────┤
│           │           │
│           │           │
└───────────┴───────────┘

```

**Comment by etrnal70** [comment]
For context, this issue mentioned in https://github.com/neovim/neovim/pull/17266#issuecomment-1030713114 first. I found out that nvim-notify fade animation make this issue easily reproducible

**Comment by fsouza** [comment]
I've also noticed this happening some times. Will try to spend some time on a small reproducer later this week if no one beats me to it.

**Comment by fsouza** [comment]
I'm able to repro this with my config by simply opening a large enough Python project and getting the flickering as I get $/progress messages from the language server, but only when running in the layout mentioned by @etrnal70 and @lewis6991. Example with black:

https://user-images.githubusercontent.com/108725/159619887-20f0b264-84f3-443b-8793-fa4761320966.mp4

The issue still happens if I remove the logic to print progress in the statusline:

https://user-images.githubusercontent.com/108725/159619951-68c14fca-443c-4d6c-89eb-16a38651ca47.mp4

I'll try to reduce the reproducer.

(I have a larger Python project at work where this becomes reaaaally annoying, but black is close enough)

**Comment by b0o** [comment]
I'm seeing this too. It happens continuously when my statusline (feline) refreshes. I don't have time right now to whittle down my config to a minimal repro, but my config is here for reference.

https://user-images.githubusercontent.com/21299126/164554696-205161d6-6f14-48e2-a628-b61a5fc7017f.mp4

**Comment by b0o** [comment]
Not sure if this is directly related, but there is also some weird behavior with the corner character depending on which window is focused. Note the way the corner changes from `│─` to `├─`


https://user-images.githubusercontent.com/21299126/164558756-3fd17c12-2840-4a4f-a883-bbf279fd9401.mp4

**Comment by par4m** [comment]
Something similar is happening when bg and fg of  NvimTreeVertSplit ([Now NvimTreeWinSeparator](https://github.com/kyazdani42/nvim-tree.lua/pull/1225)) is set to that of NvimTree
![image](https://user-images.githubusercontent.com/68808783/166405637-8a0c64a9-5349-4ec2-abb6-015a4b82642a.png)

OR Even setting vert fillchar to nothing will give the same result

**Comment by c0r73x** [comment]
I did some testing, and setting vert and vertright to a space character removes the blinking. If I change any of them to any other character the blinking starts.

**Comment by ByteDrummer** [comment]
It looks like `vertright` is changing characters from `├` to `│` while switching buffer focus, and in @par4m's case, `NvimTreeWinSeparator` isn't being redrawn.

**Comment by chardskarth** [comment]
> I did some testing, and setting vert and vertright to a space character removes the blinking. If I change any of them to any other character the blinking starts.

Changing it to space seems like a nice workaround. How did you do this please? Thanks! @c0r73x

**Comment by zeertzjq** [comment]
Does this bug still exist?

**Comment by ThaiDuy12345** [comment]
Still have this problem here? Anybody got tricks to fix this?

**Comment by wookayin** [comment]
As far as I can tell, I had this bug before but since some point during 0.10-dev this never happened, so I guess this issue has been resolved. Try 0.10 nightly. If you're still experiencing a similar bug, please provide full relevant details or open a new issue.
