### ISSUE TITLE
Docs for lua-treesitter-highlight out of date

### ISSUE THREAD

**Issue by AckslD** [neovim/neovim#17778]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1275-g00effff56

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

not relevant

### Terminal name/version

not relevant

### $TERM environment variable

not relevant

### Installation

AUR

### How to reproduce the issue

:h lua-treesitter-highlight

### Expected behavior

Up to date docs

### Actual behavior

I wanted to try to understand how one can extend existing treesitter highlight queries with custom ones. I started looking at `lua-treesitter-highlight` to get a better understanding. But it seems like the examples there are out of date. I know that it says that this WIP so not a big issue :) But I guess it would be good if still the docs are up to date with the current code, but maybe I'm missunderstanding something.

I looked a bit in `.../treesitter/highlighter.lua` to try to understand how the calls should now be. For example it seems to me that:
```lua
highlighter = vim.treesitter.TSHighlighter.new(query, bufnr, lang)
```
should instead be something like:
```lua
local parser = ts.get_parser(bufnr, lang)
local highlighter = ts.highlighter.new(parser, {
  queries = {
    [lang] = query
  }
})
```

Furthermore neither `highlighter:get_query` nor `highlighter:set_query` seems to work.

Another small comment is that it says:

> As mentioned above the supported predicate is currently only `eq?`. `match?`
> predicates behave like matching always fails. As an addition a capture which

But from what I can tell this is not mentioned above. Also in the example below, should be predicate not be `#eq?`, ie prefixed with `#`?

**Comment by clason** [comment]
For "user-facing" tree-sitter highlighting, you should look at https://github.com/nvim-treesitter/nvim-treesitter and its (extensive) documentation.

**Comment by clason** [comment]
The `treesitter.txt` documentation has been completely reworked for the 0.8 release, so I'm closing this.

Feel free to open a new issue about specific issues with the current docs.
