### ISSUE TITLE
Homebrew Build Failed on OSX Yosemite 10.10.1

### ISSUE THREAD

**Issue by estebanrules** [neovim/neovim#1778]
Here is the log:

```make[4]: *** [src/mockterm.lo] Error 1
make[3]: *** [build/src/libtickit-stamp/libtickit-install] Error 2
make[2]: *** [CMakeFiles/libtickit.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2
couldn't understand kern.osversion `14.0.0'```

**Comment by alexdunn** [comment]
I just did a NeoVim update using `brew reinstall --HEAD neovim` and it successfully built:
NVIM 0.0.0-alpha+201501060012 (compiled Jan  6 2015 20:57:47)
Commit: 050c6515f80b4964d7d9a7b66fa95146a4f38e4c

**Comment by alexdunn** [comment]
It looks like [other people](http://stackoverflow.com/questions/26486163/gcc-4-9-1-in-os-x-yosemite-gcc-warning-couldn-t-understand-kern-osversion-1) have this issue as well.  It looks like it's caused by having outdated Xcode command line tools installed.

**Comment by estebanrules** [comment]
Well I definitely have the most up to date Xcode cli tools, it may have to do with what which version of gcc I'm using.

**Comment by alexdunn** [comment]
What does `gcc --version` give?  It looks like I'm using the gcc provided with Xcode on all three of my systems that are successfully building NeoVim.  That is, I do not have gcc installed via HomeBrew.

**Comment by jszakmeister** [comment]
I'm pretty sure I had to update my gcc installation (via Homebrew) to fix this particular issue.

**Comment by xu-cheng** [comment]
> I'm pretty sure I had to update my gcc installation (via Homebrew) to fix this particular issue.

It shouldn't be like this. By default, homebrew building on OS X uses clang. And all neovim doesn't depend on `gcc` at all. Unless you run command like `brew install --env=std` or `brew install --env=gcc-4.9`. Gcc doesn't involve this.

**Comment by alexdunn** [comment]
@xu-cheng is completely right.  Output of `brew install -v --HEAD neovim`:

```
-- The C compiler identification is AppleClang 6.0.0.6000056
-- The CXX compiler identification is AppleClang 6.0.0.6000056
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++ -- works
```

Although I do have updated clang installed with `brew install --HEAD llvm`, it doesn't look like NeoVim is making use of it? Above is the path to the system clang.

**Comment by jszakmeister** [comment]
> It shouldn't be like this. By default, homebrew building on OS X uses clang. And neovim doesn't depend on gcc at all. Unless you run command like brew install --env=std or brew install --env=gcc-4.9. Gcc doesn't involve this.

Sorry, I meant that I was seeing the same kind of issue with a version of gcc and I had to update.  Yeah, Homebrew shouldn't have that issue.

@estebanrules Have you run any of the debugging steps listed [here](https://github.com/neovim/homebrew-neovim/blob/master/README.md)?  Also, I'd prefer that this ticket lived in homebrew-neovim project.

**Comment by estebanrules** [comment]
I got it working after going through the debugging steps, thank you.
