### ISSUE TITLE
Padding-issue.

### ISSUE THREAD

**Issue by Srijandev** [neovim/neovim#17789]
### Neovim version (nvim -v)

0.4.3 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows Pro version: 19042.1586, using WSL2

### Terminal name/version

xterm 3.1

### $TERM environment variable

xterm256-color

### Installation

sudo apt-get install nvim 

### How to reproduce the issue

...

### Expected behavior

The actual behaviour - nvim should be touching all the corners of my emulator

### Actual behavior

I am confused why my nvim is not touching my emulator corners? I tried checking everything(padding, column&rows) but the issue still exists.

![image](https://user-images.githubusercontent.com/67185450/159170551-7f130864-590e-4e3a-bcb2-ccacff027a2a.png)

**Comment by clason** [comment]
Your terminal window size is probably not an integer multiple of the cell size. There's nothing to be done about it by Neovim.

**Comment by Srijandev** [comment]
@clason Well? How does I fix that though?

**Comment by zeertzjq** [comment]
Also see #16572

**Comment by clason** [comment]
Make sure your terminal size is correct.

**Comment by Srijandev** [comment]
I am sorry, I tried everything? still don't get yu guys?

**Comment by zeertzjq** [comment]
You can try changing your terminal font or font size.

**Comment by Srijandev** [comment]
Ok cool, lemme try that out! :D

**Comment by Srijandev** [comment]
Sorry, still doesn't work out? @zeertzjq

**Comment by AdhTri001** [comment]
For anyone still struggling, one way to fix this is to set your Display scaling to 100%
Really annoying that it applies scaling across all desktop.
