### ISSUE TITLE
packloadall Not Using PackPath (Or Just Not Respecting It?)

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [neovim/neovim#17812]
### Neovim version (nvim -v)

v0.7.0-dev+1294-g9c92e8a62

### Vim (not Nvim) behaves the same?

N/A this is lua.

### Operating system/version

Fedora GNU/Linux 5.15.9 (kernel version, no idea which distro version I am on)

### Terminal name/version

st 8

### $TERM environment variable

xterm-256color

### Installation

Built from source

### How to reproduce the issue

1. Built the latest release of neovim
2. Run the following:
```
mkdir $XDG_CONFIG_HOME/nvim/pack/start
```
3. Create minimal.lua
```
-- The load.lua file contains all lua related to loading plugins. When this file is loaded the below
-- lua will do the following:
--    1. Configure settings for loading plugins.

local env = vim.env
local opt = vim.opt
local cmd = vim.cmd

-- Add the 'HOME/.config/nvim/' directory to the plugin path.
local home_directory = env.HOME
opt.packpath:append(home_directory .. '.config/nvim')

-- Load all plugins found in the plugin path.
cmd([[ packloadall ]])

-- Load filetype plugins.
cmd([[ filetype plugin on ]])
cmd([[ filetype indent on ]])

-- Enable file type detection.
cmd([[ filetype on ]])
```
5. Install any plugin, example here uses `nvim-autopairs`
```
cd $HOME/.config/nvim/start
git submodule add https://github.com/windwp/nvim-autopairs.git
```
6. Attempt to load the plugin using the minimal file.
```
nvim -u NORC minimal.lua
:lua require('nvim-autopairs')
```

### Expected behavior

I have been using the built-in plugin manager for awhile and it only recently broke when I moved to the latest release for `laststaus=3` as well as Lua autogroups (thank you by the way :D). I expected it to load my plugins no issue, but it seems I found a new bug ;-;

### Actual behavior

Throws this:
```
E5108: Error executing lua [string ":lua"]:1: module 'nvim-autopairs' not found:                                                                                                                                                    
        no field package.preload['nvim-autopairs']
        no file './nvim-autopairs.lua'
        no file '/home/user/.usr/src/source-code/userland/neovim/.deps/usr/share/luajit-2.1.0-beta3/nvim-autopairs.lua'
        no file '/usr/local/share/lua/5.1/nvim-autopairs.lua'
        no file '/usr/local/share/lua/5.1/nvim-autopairs/init.lua'
        no file '/home/user/.usr/src/source-code/userland/neovim/.deps/usr/share/lua/5.1/nvim-autopairs.lua'
        no file '/home/user/.usr/src/source-code/userland/neovim/.deps/usr/share/lua/5.1/nvim-autopairs/init.lua'
        no file './nvim-autopairs.so'
        no file '/usr/local/lib/lua/5.1/nvim-autopairs.so'
        no file '/home/user/.usr/src/source-code/userland/neovim/.deps/usr/lib/lua/5.1/nvim-autopairs.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

**Comment by zeertzjq** [comment]
What version were you using when it worked?

**Comment by FOSSilizedDaemon** [comment]
> What version were you using when it worked?

V0,5,0 (was installed via dnf on Fedora).

**Comment by matveyt** [comment]
The plugin path must be of a form `/prefix/pack/anyname/start/pluginname/` where prefix is registered with packpath; anyname is arbitrary; and pluginname is a specific plugin name. In your example code you are constantly using different paths.

**Comment by FOSSilizedDaemon** [comment]
> The plugin path must be of a form `/prefix/pack/anyname/start/pluginname/` where prefix is registered with packpath; anyname is arbitrary; and pluginname is a specific plugin name. In your example code you are constantly using different paths.

I am unsure what you mean. In the example configuration I only use the one path that is
```
-- Add the 'HOME/.config/nvim/' directory to the plugin path.
local home_directory = env.HOME
opt.packpath:append(home_directory .. '.config/nvim')
```
I only add `HOME/.config/nvim` to packpath.

**Comment by FOSSilizedDaemon** [comment]
> The plugin path must be of a form `/prefix/pack/anyname/start/pluginname/` where prefix is registered with packpath; anyname is arbitrary; and pluginname is a specific plugin name. In your example code you are constantly using different paths.

Aha! When loading plugins `path/` is no longer added by default! I got it working, thank you :D
