### ISSUE TITLE
Setting a virt_line on the last line in a buffer

### ISSUE THREAD

**Issue by dagle** [neovim/neovim#17816]
### Neovim version (nvim -v)

v0.7.0-dev+1292-ge9b53f3fb5

### Vim (not Nvim) behaves the same?

Feature doesn't exist in vim

### Operating system/version

Archlinux

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

neovim-git from aur

### How to reproduce the issue

[debug.txt](https://github.com/neovim/neovim/files/8324364/debug.txt)
nvim --clean
:e debug.txt
:set ft=mail
vim.api.nvim_create_namespace("test_bug")
vim.api.nvim_buf_set_extmark(0, 1, vim.fn.line("$") - 1, 0, {virt_lines = {{{"text", "Comment"}}}})

### Expected behavior

Not yielding an E315: ml_get: invalid lnum: 22 etc.

### Actual behavior

I get a:
E315: ml_get: invalid lnum: 22
and then syntax highlighting isn't reliable.
The virtual line still get set.

**Comment by muniter** [comment]
Are you sure you are not out of range?. Read `:help api-indexing` extmarks don't use the  same tye of indexing that the functions `line` or `col` use.

**Comment by dagle** [comment]
I'm pretty sure I'm not out of range but I don't think the current behavior is correct either way.  If I go out of range, I get an error saying out of range and nothing happens (the line isn't added). What happens now is that the virt_line works but yields an error and turns off syntax. I can't see how that is correct.

**Comment by zeertzjq** [comment]
Also reproducible in v0.6.1, so this is not a recent regression.
