### ISSUE TITLE
Wrong incsearch highlighting when calling nvim_buf_set_lines from timer in cmdline with conceallevel

### ISSUE THREAD

**Issue by gelguy** [neovim/neovim#17810]
### Neovim version (nvim -v)

v0.7.0-dev+1292-ge9b53f3fb

### Vim (not Nvim) behaves the same?

No

### Operating system/version

WSL Ubuntu

### Terminal name/version

wsltty

### $TERM environment variable

xterm-256color

### Installation

Build from source

### How to reproduce the issue

```vim
" init.vim
autocmd CmdlineChanged * call timer_start(0, {-> Foo()})

let s:buf = nvim_create_buf(v:false, v:true)

function! Foo()
  call nvim_buf_set_lines(s:buf, 0, -1, v:true, [])
  redraw
endfunction
```
1. `nvim -u init.vim`
2. `:h<CR>` to open help file
3. `/with<CR>` search for text
4. `/Bar<CR>` search for another text

### Expected behavior

`incsearch` highlight works as expected.

### Actual behavior

When searching for `with`, the incsearch highlighting is missing.
When searching for `Bar`, incsearch highlights `with` instead of `Bar`.

This is similar to #14064 but with the additional step of `nvim_buf_set_lines()`.

Bisected to 5ab122917474b3f9e88be4ee88bc6d627980cfe0: `feat: add support for global statusline `

**Comment by clason** [comment]
Can you test with _latest_ master? The version you list looks quite outdated.

**Comment by gelguy** [comment]
Oops! This occurs on latest `nightly`, `e9b53f3fb56e91a0d4f15bb36d8068bcc6ea88cf`. I pasted the version I bisected to instead of the version on `master`. I've updated the issue accordingly.

**Comment by gelguy** [comment]
I've realised the bug only occurs when `conceallevel` is non-zero. My repro steps unintentionally used a `help` file which sets `conceallevel=2`.

I've updated the title accordingly.

**Comment by folke** [comment]
@bfredl this causes issues with `ext_cmdline` when entering search and rendering the search ui.

To fix this, I currently set `conceallevel=0` when entering the cmdline with `firstc=? or /`, and then setting it back when leaving the commandline, but would be great to also add this to the roadmap for 0.9.0 :)
