### ISSUE TITLE
"Invalid buffer number" when calling ":lua vim.lsp.buf.definition()" when using clangd on C code.

### ISSUE THREAD

**Issue by tristone13th** [neovim/neovim#17817]
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

Not tested.

### Operating system/version

Ubuntu 20.04

### Terminal name/version

Windows Terminal

### $TERM environment variable

Not tested.

### Installation

appimage

### How to reproduce the issue

install clangd as the c language server, then run ":lua vim.lsp.buf.definition()" on printf.

### Expected behavior

Go to definition.

### Actual behavior

Error executing vim.schedule lua callback: ...pack/paqs/start/nvim-lspconfig/lua/lspconfig/configs.lua:185: Vim(autocmd):E680: <buffer=31>: invalid buffer number
stack traceback:
        [C]: in function 'nvim_command'
        ...pack/paqs/start/nvim-lspconfig/lua/lspconfig/configs.lua:185: in function 'cb'
        vim.lua:285: in function <vim.lua:285>

**Comment by mjlbach** [comment]
> Error executing vim.schedule lua callback: ...pack/paqs/start/nvim-lspconfig/lua/lspconfig/configs.lua:185: 
If you read the stack trace, you'll see this is an issue with lspconfig, not neovim.
