### ISSUE TITLE
go1.18 new built-in type `any`

### ISSUE THREAD

**Issue by jackieli-tes** [neovim/neovim#17822]
### Feature description

In the latest go 1.18 release, `any` has become an built-in type: https://go.dev/ref/spec#Interface_types. The syntax should reflect this.

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

`any` should be highlighted so users know it's a special type

**Describe the solution you'd like**

Add `any` to https://github.com/vim/vim/blob/master/runtime/syntax/go.vim#L120

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by clason** [comment]
Syntax files are taken verbatim from upstream, so please 
1. first report this to https://github.com/fatih/vim-go (or check that it hasn't been fixed there already)
2. then make a PR to vim/vim to update their syntax file

We will then pull in the update as part of our routine runtime file update.

**Comment by jackieli-tes** [comment]
Thanks, looks like it's already taken care of: https://github.com/fatih/vim-go/pull/3351
