### ISSUE TITLE
Get error `E121: Undefined variable: errmsg` when following example in documentation

### ISSUE THREAD

**Issue by dundargoc** [neovim/neovim#17849]
### Neovim version (nvim -v)

NVIM v0.7.0-dev

### Vim (not Nvim) behaves the same?

No, VIM 8.2.4295

### Operating system/version

Ubuntu 20.04.1

### Terminal name/version

Kitty with tmux

### $TERM environment variable

screen-256color

### Installation

Apt through PPA

### How to reproduce the issue

1. Generate an error. I wrote a nonsense command `:wat`
This will give the following warning: `E492: Not an editor command: wat`
2. Run `:echo errmsg`

### Expected behavior

`E492: Not an editor command: wat`

### Actual behavior

`E121: Undefined variable: errmsg`

I could list the last error message by using `:echo v:errmsg` so it's not a big deal. It mostly caught my eye because it's listed as an example in `:h errors`.

**Comment by dundargoc** [comment]
@zeertzjq is this just a documentation error? I assumed that there was a vim-patch missing that made the `errmsg` variable not available.

**Comment by zeertzjq** [comment]
IIRC it has been removed.

**Comment by zeertzjq** [comment]
<https://github.com/neovim/neovim/blob/b81c310d49f77c8f92ba2fdd99c7e0e9cb49d498/runtime/doc/vim_diff.txt#L435>

**Comment by dundargoc** [comment]
Fix added to https://github.com/neovim/neovim/pull/17755
