### ISSUE TITLE
Script for bumping dependencies

### ISSUE THREAD

**Issue by clason** [neovim/neovim#17848]
### Feature already in Vim?

N/A

### Feature description

A routine task in maintaining Neovim is upgrading the bundled dependencies in the default build to a newer release. Currently, this is done by hand, but a script that automates the necessary step would make this easier and guarantee consistent commit and PR messages.

Similar to the `brew bump-formula-pr` script, this should work something like one of
```
./bump-deps <dependency> --version=<tag>
./bump-deps <dependency> --commit=<hash>
./bump-deps <dependency> --HEAD
```
where `<dependency>` is one of (currently)
  - [LuaJIT](https://github.com/LuaJIT/LuaJIT)
  - [libuv](https://github.com/libuv/libuv)
  - [Luv](https://github.com/luvit/luv)
  - [tree-sitter](https://github.com/tree-sitter/tree-sitter)

and the options should be self-explaining. (LuaJIT does no releases or tags, hence the necessity of the second option; the third option is for convenience).

This script should:
1. generate and verify a download URL for the release;
2. generate the corresponding SHA;
3. modify the corresponding lines in https://github.com/neovim/neovim/blob/b81c310d49f77c8f92ba2fdd99c7e0e9cb49d498/third-party/CMakeLists.txt#L147-L207

4. create a commit and open a PR with a suitable commit and PR message prefilled (expect some bike-shedding on this).

For the last step, one can ~~steal~~ refactor already existing code in the [`vim-path.sh` script](https://github.com/neovim/neovim/blob/master/scripts/vim-patch.sh).

In a second step, we could think of running this script in a GH Action, Dependabot-style.

**Comment by abrfr** [comment]
Hi, I'd love to take this up

**Comment by clason** [comment]
Sure, go for it!
