### ISSUE TITLE
Can not rebind Tab in insert-mode

### ISSUE THREAD

**Issue by tim-hilt** [neovim/neovim#17847]
### Neovim version (nvim -v)

v0.7.0-dev+1319-gb81c310d49

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux 5.16.16

### Terminal name/version

kitty 0.24.4, alacritty 0.10.1, konsole 21.12.3

### $TERM environment variable

xterm-kitty

### Installation

AUR nvim-git

### How to reproduce the issue

nvim --clean testfile.txt
:lua vim.keymap.set("i", "\<Tab>", function() print("hello") end)\<CR>
i\<Tab>

### Expected behavior

Runs function (print out "hello" in the shown case)

### Actual behavior

Nothing happens

**Additional Info**

- Remapping tab via `vim.keymap.set("n", ...)` or `vim.keymap.set({"i", "n"}, ...)` makes it possible to run in normal mode, no issues there.
- Mapping key via vimscript `imap <Tab> <Cmd>echo 'hello'<CR>` behaves the same (I get an error, when using my config though, error shown below. Most likely not related.)

```
E5108: Error executing lua ...m/site/pack/packer/opt/nvim-cmp/lua/cmp/utils/keymap.lua:148: Vim:E15: Invalid expression: <80><fd>hecho 'hello'
```

**Comment by clason** [comment]
I very much suspect that this error is related ;)

**Comment by zeertzjq** [comment]
Have you `:set noshowmode`?

**Comment by clason** [comment]
What happens if you map `<c-i>` instead? (Nvim used to conflate these two keys, but that was changed recently.)

**Comment by tim-hilt** [comment]
Same thing. Nothing happens in insert mode, works in normal mode. I tested it with `nvim --clean` and `nvim -u NONE`.

**Comment by tim-hilt** [comment]
Never done that before. Also I think I might lack the C/C++-skills to really find a bad commit

**Comment by zeertzjq** [comment]
Can you `:set noshowmode`?

**Comment by clason** [comment]
> Never done that before. Also I think I might lack the C/C++-skills to really find a bad commit

`git bisect` will help you. And you don't need any C/C++ skills, just build, test, mark good/bad, repeat.

**Comment by tim-hilt** [comment]
@zeertzjq yep, that makes the "hello" it show up.

**Comment by zeertzjq** [comment]
This is how 'showmode' behaves in Insert mode. It overrides messages immediately.
