### ISSUE TITLE
vim.opt.clipboard silently discards invalid input

### ISSUE THREAD

**Issue by jarkkojs** [neovim/neovim#17851]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1306-gff82b2785

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Arch Linux

### Terminal name/version

`gnome-terminal`

### $TERM environment variable

`xterm-256-color`

### Installation

`neovim-nightly-bin` from AUR

### How to reproduce the issue

Put `vim.opt.clipboard = unnamedplus` to `init.lua`.

### Expected behavior

Error in startup.

### Actual behavior

No error in startup. Obviously clipboard is not working as it would need to be `vim.opt.clipboard = "unnamedplus"`

**Comment by rvolosatovs** [comment]
That seems like a more general invalid `lua` syntax error reporting issue. Have you checked if the error shows up in `:messages`?

**Comment by jarkkojs** [comment]
> 

Nothing in `:messages`.

**Comment by zeertzjq** [comment]
I cannot reproduce. Please make sure `init.lua` is actually sourced.

**Comment by jarkkojs** [comment]
It is, I even deleted my `init.vim`.

**Comment by clason** [comment]
Yep, this is just the way Lua (and the general API) behaves.

**Comment by clason** [comment]
To be clear, the input is _not_ invalid going by Lua's (admittedly sometimes counterintuitive) rules.

**Comment by dundargoc** [comment]
Yeah, I know. I was just openly wondering if it might be feasible to add an extra check, even if it is perfectly valid lua. I suspect it might not be worth the hassle though.

**Comment by clason** [comment]
I was thinking along similar lines, but I can see good reasons to allow `vim.opt.clipboard = nil` (and similarly for other options), and I don't see a way of allowing explicit `nil` while forbidding (or even warning for) non-existent variables which _are_ `nil` in Lua.

**Comment by clason** [comment]
(And I know you know; I just wanted to explain to the audience why I closed this issue as "invalid".)

**Comment by matveyt** [comment]
> I was thinking along similar lines, but I can see good reasons to allow `vim.opt.clipboard = nil` (and similarly for other options), and I don't see a way of allowing explicit `nil` while forbidding (or even warning for) non-existent variables which _are_ `nil` in Lua.

By implementing `__index` metamethod, no?

```Lua
setmetatable(_G, {__index = function(self, key)
    print(key.." not initialized")
end})

vim.opt.clipboard = unnamedplus --not intialized warning

vim.opt.clipboard = nil
print(vim.opt.clipboard)        --no warning, as vim.opt differs from _G
```
