### ISSUE TITLE
Setting empty virtual text leads to rendering artifacts

### ISSUE THREAD

**Issue by spaarmann** [neovim/neovim#17860]
### Neovim version (nvim -v)

v0.6.1, also tested on v0.7.0-dev+1323-g61205c1de

### Vim (not Nvim) behaves the same?

no (no virtual text support afaik?)

### Operating system/version

Arch Linux in WSL2

### Terminal name/version

Windows Terminal 1.11.3471.0

### $TERM environment variable

xterm-256color

### Installation

0.6 from Arch packages, 0.7-dev built from source

### How to reproduce the issue

Create `virt_test.lua` with contents:
```lua
local namespace = vim.api.nvim_create_namespace("virt-text-testing")

vim.api.nvim_buf_set_extmark(0, namespace, 10, 0, {
    virt_text_pos = "eol",
    virt_text = {
        { "", "Comment" },
    }
})

-- Some test text;
-- foo
-- bar
```

Then:
`nvim --clean virt_test.lua +'set number' +'set colorcolumn=100' +'source %'`
`9jO<ESC>dd`

### Expected behavior

I expect an extmark with virtual text set to the empty string to either have no effect on rendering at all, or produce an error if it is meant to be invalid.

### Actual behavior

The color column gets offset on the line containing the extmark. The `9jO<ESC>dd` edit produces a "phantom" `;`, copied from the line above, on the line with the extmark. Both issues are visible in this screenshot:
![WindowsTerminal_2022-03-25_21-59-43](https://user-images.githubusercontent.com/7349758/160200058-fe65e992-d9d4-4c42-8bed-621ba9f98af7.png)

Note that the `+'set colorcolumn'` on its own is enough to see the issue on the color column; the phantom `;` appears as long as `+'set number'` is included (but does not require the color column).

**Comment by zeertzjq** [comment]
Bisected to <https://github.com/neovim/neovim/commit/25a879dfa2f0795d610833c9552ca48f0cab95fa>.

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
index 41a129dba..0a1599c42 100644
--- a/src/nvim/screen.c
+++ b/src/nvim/screen.c
@@ -1853,6 +1853,9 @@ static int line_putchar(buf_T *buf, LineState *s, schar_T *dest, int maxcells, b
       schar_from_ascii(dest[c], ' ');
     }
     goto done;
+  } else if (*p == NUL) {
+    schar_from_ascii(dest[0], ' ');
+    s->prev_c = ' ';
   } else if (*p < 0x80 && u8cc[0] == 0) {
     schar_from_ascii(dest[0], *p);
     s->prev_c = u8c;
```

**Comment by zeertzjq** [comment]
This seem to fix the bug:
```diff
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
index 41a129dba..195cb58da 100644
--- a/src/nvim/screen.c
+++ b/src/nvim/screen.c
@@ -4333,6 +4333,9 @@ static int draw_virt_text_item(buf_T *buf, int col, VirtText vt, HlMode hl_mode,
         break;
       }
     }
+    if (!*s.p) {
+      continue;
+    }
     int attr;
     bool through = false;
     if (hl_mode == kHlModeCombine) {
```
