### ISSUE TITLE
Neovim really slow with long files ( G, gg, % ) and syntax on

### ISSUE THREAD

**Issue by debianw** [neovim/neovim#17862]
### Neovim version (nvim -v)

v0.7.0-dev+1319-gb81c310d4

### Vim (not Nvim) behaves the same?

no

### Operating system/version

12.2.1

### Terminal name/version

iTerm2 3.4.12

### $TERM environment variable

256

### Installation

build from repo

### How to reproduce the issue

Open a big file and navigate from top to bottom, or % to navigate to the beginning or the end of a function

### Expected behavior

fast navigation

### Actual behavior

Slow

**Comment by zeertzjq** [comment]
Can you test if an older version e.g. v0.6.1 is faster?

**Comment by zeertzjq** [comment]
Also, what options do you have set?

**Comment by debianw** [comment]
@zeertzjq same thing with `v0.6.1`. This is also happening if I open nvim with no config `nvim --clean .`

**Comment by Shougo** [comment]
It seems Vim/neovim syntax parser problem.
I think nvim-treesitter solves the problem.

**Comment by debianw** [comment]
https://user-images.githubusercontent.com/1002407/160215268-c14a54a7-6335-412d-8909-ea49bb3d0af2.mov

**Comment by debianw** [comment]
If I turn off syntax `syntax off` then everything flows really fast

**Comment by debianw** [comment]
> It seems Vim/neovim syntax parser problem. I think nvim-treesitter solves the problem.

I have `nvim-treesitter` but same problem

**Comment by zeertzjq** [comment]
Does `:NoMatchParen` make it faster?

**Comment by debianw** [comment]
> Does `:NoMatchParen` make it faster?

Nop

**Comment by debianw** [comment]
`syntax off` works really fast, BUT I want `syntax on`

https://user-images.githubusercontent.com/1002407/160215655-44343114-a9fb-49b0-8df7-898820e80898.mp4

**Comment by Shougo** [comment]
Have you use `set wrap`?  It is really slow.

**Comment by debianw** [comment]
> Have you use `set wrap`? It is really slow.

No I'm not using `set wrap`

**Comment by Shougo** [comment]
Please upload the big file.  I will test it.

**Comment by debianw** [comment]
@Shougo test with any big file. In my case is a php file with almost 600 lines of code, but it happens with big Javascript files as well or any other file that contains any kind of code in it

**Comment by debianw** [comment]
@Shougo maybe this one could help you test. 
Go to `class Request {` and try to jump to the end of the class and to the beginning of the class `{` `}` using `%`. Do it several times very fast.

Repeat the same with `syntax off`

[class-requests.php.zip](https://github.com/neovim/neovim/files/8355923/class-requests.php.zip)

**Comment by dundargoc** [comment]
Can recreate with vim+nvim without treesitter. Can not recreate with treesitter.

**Comment by dundargoc** [comment]
Do you have a link to your dotfiles? I want to check something.

**Comment by debianw** [comment]
@dundargoc https://github.com/debianw/dotfiles-debianw

**Comment by debianw** [comment]
Hey I just noticed this message from `nvim-treesitter`.

```
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
```

I just set it to `false` and now Neovim is working super fast, I'm able to navigate normally inside big files.

Should I have to `syntax off` when using Treesitter ?

**Comment by clason** [comment]
You should not have `syntax on` in Neovim, period.

But, yes, only enable `additional_vim_regex_highlighting` (for specific languages, never globally!) if you rely on legacy syntax features (like conceal, or VimTeX's `mathzone` functions) that are disabled when enabling tree-sitter-based highlighting.

**Comment by lewis6991** [comment]
Sounds like this issue has been resolved. Can it be closed?

**Comment by debianw** [comment]
@lewis6991 this has been resolved by using `vim-treesitter` and `syntax off`. Would be great to have this somewhere in the documentation

**Comment by clason** [comment]
Do not use `syntax off` in combination with `nvim-treesitter`; this plugin will disable regex-based syntax by itself. Note that tree-sitter support is still experimental and not recommended in general as a replacement for the legacy syntax engine.

The upshot of this is that the `php` syntax files are slow -- but these are maintained by vim/vim, and any improvement has to go through there.

So this indeed leaves nothing actionable for Neovim, hence I'm closing this issue. Feel free to reopen if new information comes to light.
