### ISSUE TITLE
highlight current line in number column

### ISSUE THREAD

**Issue by tsivinsky** [neovim/neovim#17885]
### Feature description

i think it will be really cool if user can change color for current line in numbers column (i mean 'number' option)

![image](https://user-images.githubusercontent.com/48863576/160290618-d28e3d86-09e8-4884-abbe-18a9f65fbf39.png)

something like this

```vim
highlight CurrentNumber guifg=orange gui=italic
```

name for highlight-group can be better of course :)

**Comment by zeertzjq** [comment]
`:set cursorline cursorlineopt=number`, `CursorLineNr`.

**Comment by tsivinsky** [comment]
oh, thank you
