### ISSUE TITLE
Expose LSP uninitialized_clients (or some other method to get access to lsp client ids)

### ISSUE THREAD

**Issue by miversen33** [neovim/neovim#17881]
### Feature already in Vim?

No

### Feature description

There is a method that is exposed in the neovim lsp called [get_client_by_id](https://github.com/neovim/neovim/blob/71b4c30ad6215742ffcb8dfb0fb4df899065cb7a/runtime/lua/vim/lsp.lua#L1344), which proves quite handy for forcing an lsp to connect to a buffer. However, this relies on you as the "user" knowing the client id you wish to use for this connection. 

You could _potentially_ get this id from [get_active_clients](https://github.com/neovim/neovim/blob/71b4c30ad6215742ffcb8dfb0fb4df899065cb7a/runtime/lua/vim/lsp.lua#L1387), but this relies on the client already being bound to another buffer (IE, active). If however, this is not the case, the client id is not accessible externally.

Other tools such as [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/7d5a6dc46dd2ebaeb74b573922f289ae33089fe7/lua/lspconfig/util.lua#L365) actually have to rely on their own shim between the user and the LSP. In lspconfig's case, they actually keep the client_id's stored in a table within its own plugin so it can reference them later. 

For plugins that _aren't_ between the lsp server and the lsp client, this is not an option (without intense hackery/introspection). A much better alternative is to simply expose access to the [`uninitialized_clients`](https://github.com/neovim/neovim/blob/71b4c30ad6215742ffcb8dfb0fb4df899065cb7a/runtime/lua/vim/lsp.lua#L137) variable within the lsp itself (something like `vim.lsp.get_uninitialized_clients` for example) that can be iterated over to pull either clients or the id's associated with them.

This would allow developers that wish to interface with the lspserver without having to sit between the lspserver and lspclients a way to do so.

**Comment by miversen33** [comment]
A more concrete/specific usecase for this would be a situation where you have a plugin that is loading an empty buffer with text. The LSP wont connect to the buffer (I have not quite pinned down why this is yet but I assume its due to the LSP connect event not firing due to the buffer not having a filetype initially). Thus you as the plugin developer need to account for this and manually connect the LSP clients to the buffer. However not having access to the unitialized_clients means you have to (effectively) iterate through all the active clients and hope you get the right ones, peer into lspconfig (assuming its installed, thus making an unrelated plugin a dependency to your project), or just brute force guessing ids until you hit some predefined max limit.

None of these are great ways of dealing with this specific usecase and this _will_ occur if you are the first buffer opened (an example would be using netrw to open a remote file)

A small section of code that can be used to demonstrate this can be found [here](https://github.com/miversen33/netman.nvim/blob/f5768f8e889c1f9bb66db531d9d46b56e59df6c2/lua/netman/init.lua#L66)
```lua
function read(local_file, path)
    -- local_file is a file located somewhere on your filesystem
    -- path is the <amatch> name from the autocommand 
    vim.api.nvim_command('keepjumps sil! 0')
    vim.api.nvim_command('keepjumps execute "sil! read ++edit ' .. some_file .. '"')
    vim.api.nvim_command('keepjumps sil! 0d')
    vim.api.nvim_command('keepjumps sil! 0')
    if execute_post_read_cmd == "buf" then
        vim.api.nvim_command('execute "sil doautocmd BufReadPost ' .. path .. '"')
    elseif execute_post_read_cmd == "file" then
        vim.api.nvim_command('execute "sil doautocmd FileReadPost ' .. path .. '"')
    end
end
```

In this case (using this to open a local `python` file), a registered python lsp (such as pyright or pylsp) will not connect to the buffer.

**Comment by mjlbach** [comment]
If you call `start_client`, `active_clients` will always be populated https://github.com/mjlbach/neovim/blob/ab8f2eb4c9ae461004e8db6fc3cfd7a0cc89b934/runtime/lua/vim/lsp.lua#L1164, so you don't need access to uninitialized_clients.

> A more concrete/specific usecase for this would be a situation where you have a plugin that is loading an empty buffer with text. The LSP wont connect to the buffer (I have not quite pinned down why this is yet but I assume its due to the LSP connect event not firing due to the buffer not having a filetype initially).

This seems more like your real issue. Lspconfig sets up a filetype autocommand for each language server which calls start_client with the cached config table. You can either call `set ft` to trigger it, or manually trigger the autocommand.

**Comment by miversen33** [comment]
Thank you!

It turns out that (as you stated) the issue not with how clients are handled in the lsp. It looks like [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/) does some lazy loading of the lsps on _its_ level (so they never get registered with the core lsp until they are needed).

I figured out my issue here, [and it turns out it was a bit deeper than I had thought](https://github.com/miversen33/netman.nvim/issues/5#issuecomment-1080011664)

I dont know that my issue opened here is actually useful to anyone so its probably best to close this out unless you/another contributor thinks having the requested variable accessible would be useful

**Comment by mjlbach** [comment]
> . It looks like [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/) does some lazy loading of the lsps on its level (so they never get registered with the core lsp until they are needed).

Yes, there are plans to move an lspconfig-like thing into core, but the progress is slow (don't have much time for neovim development currently). I would personally *not* use the lspconfig starter mechanism directly as it assumes the buffer is accessible on the filesystem, which won't be the case remotely. Distant.nvim has a similar issue. Happy to chat more on matrix if you have specific questions/want to discuss how we could better support remote language servers in the lspconfig rewrite (prototype here https://github.com/mjlbach/projects.nvim)
