### ISSUE TITLE
Better Customization of Cursor Location After Operations

### ISSUE THREAD

**Issue by jfelchner** [neovim/neovim#1789]
I'm just opening this up for a brainstorming session.

I think that one of the things that Neovim should provide is better customization for where the cursor ends up after various operations.

By default Vim prefers to move your cursor to the beginning of whatever the block of text was that you manipulated.  While this is fine, and I appreciate Vim being consistent (and I think Neovim's defaults should be the same), there are plenty of times when I'd like different behavior.

In certain situations, this can be accomplished by a mapping, but it's clunky and error prone.

Let's say for example that you yank a block of text and paste it, by default, pasting moves the cursor to the _beginning_ of the block that is pasted.  I'm sure that there are many people who prefer this behavior.  I am not one of those.  I would prefer my cursor be placed at the end of the block being pasted.

Let's talk about another example: reformatting text.  When choose to format a block of text by pressing `gq` I'd prefer to have the cursor _remain_ where it was, but instead it moves to the _end_ of the block.

Obviously these are my own preferences and many people will choose that they either like the Vim default or prefer something other than what I described, but having the option without messy mappings involving marks would be pretty nice.

**Comment by justinmk** [comment]
> pasting moves the cursor to the beginning of the block that is pasted. I'm sure that there are many people who prefer this behavior. I am not one of those. I would prefer my cursor be placed at the end of the block being pasted.

FYI, `gp` and `gP` do this already.

> When choose to format a block of text by pressing gq I'd prefer to have the cursor remain where it was,

The general solution for this and many other applications is to provide more insight into text changes. In the case of `gq`, the semantics of "same place" have a different implementation than, say, a transpose operation.

We could instead, or in addition, re-implement `gq` as a lua function, and allow it to be overridden...

**Comment by jfelchner** [comment]
@justinmk I had no idea about gp and gP. Learn new vim every day. :) thank you. 

In the other situations, I don't know what would be best to do. I just wanted to bring it up for discussion.
