### ISSUE TITLE
cannot copy text to system clipboard in wayland

### ISSUE THREAD

**Issue by cathaysia** [neovim/neovim#17904]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

yes, Vi IMproved 8.2

### Operating system/version

archlinux

### Terminal name/version

kitty, konsole

### $TERM environment variable

xterm-256color in konsole, xterm-kitty in kitty

### Installation

community/neovim

### How to reproduce the issue

nvim --clean
:e foo
vab
"+Y

### Expected behavior

copy text to system clipboard

### Actual behavior

nothing happend

**Comment by cathaysia** [comment]
and my system info is:

Operating System: Arch Linux
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.16.16-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 16 × 11th Gen Intel® Core™ i7-11800H @ 2.30GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics

**Comment by zeertzjq** [comment]
Have you installed optional dependency `wl-clipboard`?

**Comment by cathaysia** [comment]
Thanks, that's the answer I need.

**Comment by Oyinbra** [comment]
> Have you installed optional dependency `wl-clipboard`?

Thanks. was able to fix mine by installing it.
