### ISSUE TITLE
Hang when calling :normal that ends in Insert mode from Ex mode

### ISSUE THREAD

**Issue by Nales0** [neovim/neovim#17924]
### Neovim version (nvim -v)

0.6.1 (commit 5b839ced692230fe582fde41f79f875ee90451e8 (HEAD, tag: v0.6.1, tag: stable))

### Vim (not Nvim) behaves the same?

No, Vim 8.2.4646 (2019 Dec 12) neither Neovim 0.4.3

### Operating system/version

Linux Mint 20.3

### Terminal name/version

Terminal MATE 1.26.0

### $TERM environment variable

xterm-256color

### Installation

Build from repo. (Build type: RelWithDebInfo)

### How to reproduce the issue

Create a file `main.cpp` containing the following.

```cpp
#include <iostream>

int main(int argc, chat* argv[])
{
    std::cout << "Hello World!" << std::endl;
    return 0;
}
```

The file and its content are not that important. The goal is to use Neovim in scripts to generate HTML files from source code files using `:TOhtml`. We use the arguments `-n` to disable swap files, `-Es` or `-E -s` to launch Neovim in silent Ex mode.

In the rest of this bug report, lines starting with a `$` are commands that the tester do in a shell.

### Expected behavior

We check if the arguments used are not causing any problem. We simply make Neovim save a copy of `main.cpp` as `other.cpp`.

```
$ nvim -nEs -c "write! other.cpp" -c 'qa!' "main.cpp"
$ ls
main.cpp  other.cpp
```

We use `:TOhtml` in two ways to write a `main.cpp.html` file. One directly.

```
$ nvim -nEs -c 'noswapfile TOhtml' -c "write! main.cpp.html" -c 'qa!' "main.cpp"
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>~/Code-To-Color/test/main.cpp.html</title>
<meta name="Generator" content="Vim/8.0">
<meta name="plugin-version" content="vim8.1_v1">
<meta name="syntax" content="cpp">
<meta name="settings" content="use_css,pre_wrap,no_foldcolumn,prevent_copy=">
<meta name="colorscheme" content="none">
<style type="text/css">
<!--
$ ls
main.cpp  main.cpp.html
```

Another way by using an adapted version of the command described in `:help TOhtml-performance`.

```
$ nvim -n -E -s -c "let g:html_no_progress=1" -c "syntax on" -c "set ft=c" -c "runtime syntax/2html.vim" -cwqa "main.cpp"
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>~/Code-To-Color/test/main.cpp.html</title>
<meta name="Generator" content="Vim/8.0">
<meta name="plugin-version" content="vim8.1_v1">
<meta name="syntax" content="c">
<meta name="settings" content="no_progress,use_css,pre_wrap,no_foldcolumn,prevent_copy=">
<meta name="colorscheme" content="none">
<style type="text/css">
<!--
$ ls
main.cpp  main.cpp.html
```

The generated file (`main.cpp.html`) looks like that.

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>~/Code-To-Color/test/main.cpp.html</title>
<meta name="Generator" content="Vim/8.0">
<meta name="plugin-version" content="vim8.1_v1">
<meta name="syntax" content="cpp">
<meta name="settings" content="use_css,pre_wrap,no_foldcolumn,prevent_copy=">
<meta name="colorscheme" content="none">
<style type="text/css">
<!--
pre { white-space: pre-wrap; font-family: monospace; color: #ffffff; background-color: #000000; }
body { font-family: monospace; color: #ffffff; background-color: #000000; }
* { font-size: 1em; }
.Type { color: #87ffaf; }
.Statement { color: #ffff00; }
.PreProc { color: #5fd7ff; }
.Constant { color: #ff40ff; }
-->
</style>
</head>
<body>
<pre id='vimCodeElement'>
<span class="PreProc">#include </span><span class="Constant">&lt;iostream&gt;</span>

<span class="Type">int</span> main(<span class="Type">int</span> argc, chat* argv[])
{
    std::cout &lt;&lt; <span class="Constant">&quot;Hello World!&quot;</span> &lt;&lt; std::endl;
    <span class="Statement">return</span> <span class="Constant">0</span>;
}
</pre>
</body>
</html>
<!-- vim: set foldmethod=manual : -->
```

The behaviour described above is the one given by Neovim version 0.4.2 and Vim version 8.2 (when using `vim` instead of `nvim`). When using `:TOhtml`, both Vim and Neovim print on the standard output some HTML code.

Important note: when adding the argument `-u NONE`, the generated file `main.cpp.html` is a simple copy of `main.cpp` since there is no syntax highlighting. I suppose in this case the command `:TOhtml` does not generate HTML.

### Actual behavior

Using Neomvim 0.6.1, the first command works as expected.

```
$ nvim -nEs -c "write! other.cpp" -c 'qa!' "main.cpp"
$ ls
main.cpp  other.cpp
```

When using the two other commands, Neovim hangs forever after displaying some HTML code. The user must press `^C` to stop the process.

```
$ nvim -nEs -c 'noswapfile TOhtml' -c "write! main.cpp.html" -c 'qa!' "main.cpp"
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>~/Code-To-Color/test/main.cpp.html</title>
<meta name="Generator" content="Vim/8.0">
<meta name="plugin-version" content="vim8.1_v1">
<meta name="syntax" content="cpp">
<meta name="settings" content="use_css,pre_wrap,no_foldcolumn,prevent_copy=">
<meta name="colorscheme" content="none">
<style type="text/css">
<!--
^C
$ nvim -n -E -s -c "let g:html_no_progress=1" -c "syntax on" -c "set ft=c" -c "runtime syntax/2html.vim" -cwqa "main.cpp"
<html>
<head>
<meta charset="UTF-8">
<title>~/Code-To-Color/test/main.cpp.html</title>
<meta name="Generator" content="Vim/8.0">
<meta name="plugin-version" content="vim8.1_v2">
<meta name="syntax" content="c">
<meta name="settings" content="no_progress,use_css,pre_wrap,no_foldcolumn,prevent_copy=,use_input_for_pc=fallback">
<meta name="colorscheme" content="none">
<style>
<!--
^C
```

When adding the option `-u NONE`, the program does not hang forever and file `main.cpp.html` is generated as a simple copy of `main.cpp`.

**Comment by glacambre** [comment]
>When adding the option -u NONE, the program does not hang forever and file main.cpp.html is generated as a simple copy of main.cpp.

This likely means that something in your config is causing the hang. Could you remove the content of your init.vim line by line until you figure out what setting is causing the hang?

**Comment by dundargoc** [comment]
I've contacted the maintainer about this issue.

**Comment by Nales0** [comment]
Thank you. By the way, I just tested that in Vim 8.2. Vim uses the exact same file and it parses `normal` commands entering in insert mode without any issue.

**Comment by Nales0** [comment]
I just reinstalled Neovim 0.4.3 and I changed its `runtime/syntax/2html.vim` by the one used in Vim 8.2 and Neovim 0.6.1. Neovim 0.4.3 has no problem.

**Comment by Nales0** [comment]
@fritzophrenic I am convinced that this is a Neovim issue here.

The bug is introduced by the commit 192adfe99f33778a85e11fbfdceb37f347a3d235. From this commit, the script hangs. When applying the fix I described above (changing the `normal` command by a `append()` function call), the script does not hang and the HTML file is generated.

This commit is changing how ex commands are processed when using the arguments `-E` and `-s`. As a proof that this is not a problem caused by `2html.vim`, even the following command hangs forever.

```
nvim -n -E -s -c 'normal!ITest' -cwqa 'test.txt'
```

Can someone else try this command to check if the issue is not only on my machine? Thank you.

**Comment by zeertzjq** [comment]
Removing these two lines seem to fix the issue:
```
diff --git a/src/nvim/getchar.c b/src/nvim/getchar.c
index b12b99b7e..8190c20c1 100644
--- a/src/nvim/getchar.c
+++ b/src/nvim/getchar.c
@@ -2330,8 +2330,6 @@ static int vgetorpeek(bool advance)
           // cmdline window.
           if (p_im && (State & INSERT)) {
             c = Ctrl_L;
-          } else if (exmode_active) {
-            c = '\n';
           } else if ((State & CMDLINE) || (cmdwin_type > 0 && tc == ESC)) {
             c = Ctrl_C;
           } else {
```

**Comment by zeertzjq** [comment]
Actually this should be the correct fix:
```diff
diff --git a/src/nvim/getchar.c b/src/nvim/getchar.c
index b12b99b7e..c944a5ec9 100644
--- a/src/nvim/getchar.c
+++ b/src/nvim/getchar.c
@@ -2330,7 +2330,7 @@ static int vgetorpeek(bool advance)
           // cmdline window.
           if (p_im && (State & INSERT)) {
             c = Ctrl_L;
-          } else if (exmode_active) {
+          } else if ((State & CMDLINE) && exmode_active) {
             c = '\n';
           } else if ((State & CMDLINE) || (cmdwin_type > 0 && tc == ESC)) {
             c = Ctrl_C;
```
