### ISSUE TITLE
Cannot compute diff with slow process substitution (`<(...)`) as parameters

### ISSUE THREAD

**Issue by Nales0** [neovim/neovim#17926]
### Neovim version (nvim -v)

0.6.1 (commit 5b839ce (HEAD, tag: v0.6.1, tag: stable))

### Vim (not Nvim) behaves the same?

No, Vim 8.2.4646 (2019 Dec 12) neither Neovim 0.4.3

### Operating system/version

Linux Mint 20.3

### Terminal name/version

Terminal MATE 1.26.0

### $TERM environment variable

xterm-256color

### Installation

Build from repo. (Build type: RelWithDebInfo)

### How to reproduce the issue

The issue appears when using Bash version 5.0.17 or zsh 5.8. The goal is to use Neovim to make a diff between two directories using the `-d` argument.

We use temporary files:

```
ls -Rla ~ > left
ls -Rla ~ > right
nvim -d left right
```

Or we use use a Process Substitution in Bash and zsh. We use `sleep` to simulate a slow process. We recursively list the content of the home directory (`ls -Rla ~`) so the bug have more chances to appear because it generates a lot of content.

```
nvim -d <(sleep 2 && ls -Rla ~) <(sleep 2 && ls -Rla ~)
```

### Expected behavior

Neovim should starts in diff mode and show the differences. This is the correct behaviour in Vim 8.2.4646 neither Neovim 0.4.3.

### Actual behavior

There is no problem when using temporary files.

When using process substitution, Neovim sometimes displays the diff and "immediately" remove the content of one of the file. Sometimes one file does not have all content or have no content at all. Those behaviours happen even when doing the diff of small output sometimes.

**Comment by Nales0** [comment]
Indeed when using `set noautoread`, Neovim warns me twice when I do `nvim -d <(sleep 2 && ls -Rla ~) <(sleep 2 && ls -Rla ~)`. (Lose translation below since my system is not in English.)

```
W11: Warning: The file "/proc/1372274/fd/11" changed since the beginning of the editing
Check ":help W11" for more information.
[O]k, [L]oad the file: |
```

If I do "ok" the file stays still, if I "load the file" the content disappears.

**Comment by seandewar** [comment]
Thanks for checking! In this case, this looks like the same issue as #16809 :+1:
