### ISSUE TITLE
Appimage metadata of  neovim is broken

### ISSUE THREAD

**Issue by djfos** [neovim/neovim#17931]
### Feature already in Vim?

NO

### Feature description

"https://g.srev.in/get-appimage/neovim/core.json" just return a "false", which prevent downstream tool , like zap, to install neovim.

**Comment by clason** [comment]
And who is maintaining https://g.srev.in? I don't think this is anybody on the Neovim team.

**Comment by djfos** [comment]
Indeed, the website is maintained by [srevinsaju](https://github.com/srevinsaju/get-appimage). I have open an [issue](https://github.com/srevinsaju/get-appimage/issues/6) in that repo, so to close this issue.
