### ISSUE TITLE
Shift selector doesn't work as it used to

### ISSUE THREAD

**Issue by 3v1n0** [neovim/neovim#17945]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

yes, 8.2.3995

### Operating system/version

Ubuntu 22.04

### Terminal name/version

Tilix 1.9.1

### $TERM environment variable

xterm-256color

### Installation

ubuntu repository

### How to reproduce the issue

`nvim -u NONE`

`:noremap <A-C-S-j> w`

Insert some text, move to text beginning, and then try to press `<Ctrl+Shift+Alt+j>`.

Such mapping with neovim 0.4.4 worked perfectly, now it does not. The only way to get this working is to replace `S-w` with `W`.

Note that using just `noremap <S-j> w` works as expected.

### Expected behavior

It's possible to use `S-` to map shifted keys in more complex combinations

### Actual behavior

Nothing is mapped, `:map` shows:

```
   <M-S-NL>    * w
```

**Comment by zeertzjq** [comment]
```
The only way to get this working is to replace S-w with W
```
Do you mean replacing `S-j` with `J`?

**Comment by zeertzjq** [comment]
This is a Tilix's problem. It sends the same escape sequence for `<M-C-J>` and `<M-C-S-J>`. Before #12592 Nvim cannot distinguish these two keys, now it can. I don't think #12592 should be reverted.

**Comment by 3v1n0** [comment]
> Do you mean replacing `S-j` with `J`?

Yes, indeed.. Sorry, I've updated the description.

It looks like also gnome-terminal is affected, so probably it's just a VTE issue...
