### ISSUE TITLE
Strange behaviour for `lua print(vim.o.scrolloff)`

### ISSUE THREAD

**Issue by jghauser** [neovim/neovim#17940]
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Latest Arch Linux

### Terminal name/version

kitty 0.24.4

### $TERM environment variable

xterm-kitty

### Installation

from arch community repo

### How to reproduce the issue

nvim --clean
:lua print(vim.o.scrolloff)

### Expected behavior

Should return scrolloff value. 0 by default or whatever is set. Just as `set scrolloff?` does.

### Actual behavior

Returns a different value every time neovim is started. Something in the vicinity of 1.3987147207818e+14.

We came across this issue when we were debugging a problem with Neorg. See [here](https://github.com/nvim-neorg/neorg/issues/400).

**Comment by clason** [comment]
Doesn't happen here. Can you try on master (build from source, or an appimage)?

**Comment by jghauser** [comment]
I just tried on master (neovim-git package in AUR) and the issue does not arise. I guess we can close this!
