### ISSUE TITLE
nvim - vanilla?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [neovim/neovim#17959]
### Summary
Discussion about making a vanilla version of nvim with least deviations from vim

### Details
* With the modernisation of the code base and using existing available libraries, neovim is gradually gaining more adoption
* I think it's about time that distros start to look at nvim too
* But at the same time, many times people in here talk about on the line of "the deviation is inevitable" , "who cares" , etc as excuse for their feature requests (see the comment containing references below)
* So, having a vanilla version of nvim, that is, the version with maximum compatibility with vim; in the sense that a given action in nvim does what it does in vim; and (most) all actions doable in vim are doable in nvim; will help a lot, and any deviative features shall go to a different version

What do you think??

### Environment
* nvim: v0.6.1

**Comment by yashpalgoyal1304** [comment]
### References for comments
- will post later

**Comment by clason** [comment]
That version exists, it's called Vim.

**Comment by dundargoc** [comment]
To expand upon this a bit further: neovim already has A LOT of flag, so adding a new one should need to solve a crucial problem more than convenience I think.
