### ISSUE TITLE
Show bindings/commands overlay

### ISSUE THREAD

**Issue by yashpalgoyal1304** [neovim/neovim#17960]
### Feature already in Vim?

Yes, in gvim
I think since start

### Summary
Some way to show most common keybindings or commands

### Details
* Some way to show most common (or custom) keybindings or commands 
* Like available in _micro_ TUI editor, or _gvim_ GUI
* That will help begginers like me a lot

### Screenshots for reference

1. micro TUI
<kbd>alt</kbd><kbd>g</kbd>: bindings

2. G-Vim GUI
Shown in the menu lists

![image](https://user-images.githubusercontent.com/19423063/161368086-19f46429-9598-4bc1-b450-1285b17eb57c.png)

![image](https://user-images.githubusercontent.com/19423063/161368235-d60c7652-1f4a-4838-b0ca-f64a4d62b1b2.png)

### Environment
* nvim: 0.6.1

### Duplicate 🔍 
* [commands overlay]
* [show bindings]

[commands overlay]: https://github.com/neovim/neovim/issues?q=is%3Aissue+is%3Aopen+commands+overlay
[show bindings]: https://github.com/neovim/neovim/issues?q=is%3Aissue+is%3Aopen+show+bindings

**Comment by clason** [comment]
https://github.com/folke/which-key.nvim

(not every feature needs to be built in)

**Comment by clason** [comment]
(Unfortunately, #17957 was closed, so we have no way of knowing what the most common keybindings or commands are...)

**Comment by yashpalgoyal1304** [comment]
> most common keybindings or commands

wow, awesome. totally brilliant. didnt know that knowing common keybindings required telemetry. 

thanks a lot for this super depth insightful information.
