### ISSUE TITLE
How should one free global variables?

### ISSUE THREAD

**Issue by doppioandante** [neovim/neovim#1797]
Consider for example the code in os/event.c:

``` C
...
static klist_t(Event) *deferred_events = NULL, *immediate_events = NULL;
static int deferred_events_allowed = 0;
void event_init(void)
{
   // Initialize the event queues
   deferred_events = kl_init(Event);
   immediate_events = kl_init(Event);
...
```

event_init is then called by main(), but I can't find any place where the two lists are freed(using klist_destroy).
The strange thing is that clangasan does not complain: apparanteley everything is freed up if [EXITFREE](https://github.com/neovim/neovim/blob/master/src/nvim/os_unix.c#L514) is defined, but I think this is not the case in the release binary.
I'm writing similar code for my PR and I wasn't sure how to deal with this.
Can somebody enlighten me?

**Comment by oni-link** [comment]
I think this two lists are not freed because they are used nearly until the end of the nvim process.
If you would want to free the two list, it would be done in `event_teardown()`. The call to `event_teardown()` is right before the `exit()` call in `mch_exit()`, so just before all memory is freed for the nvim process. 
Or it was just forgotten. 

@tarruda should know why.

**Comment by tarruda** [comment]
> I think this two lists are not freed because they are used nearly until the end of the nvim process.

:+1: 

Though later I'd like to add a debug function that resets nvim to a clean state, so it won't be necessary to restart the nvim process after each test. This would greatly speed up running tests under valgrind, which spends a lot of time preparing the process(Currently it takes more than 20 minutes, I imagine it could be reduced to less than 10 minutes).

So if you want to send a PR that cleans these functions, it will be welcome.
