### ISSUE TITLE
documentation of tbl_deep_extend does not specify return value 

### ISSUE THREAD

**Issue by danielo515** [neovim/neovim#17972]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

macOS 12.1

### Terminal name/version

iterm

### $TERM environment variable

does not matter 

### Installation

brew

### How to reproduce the issue

Documentation issue 

### Expected behavior

This is just a documentation issue. The definitions of vim.tbl_deep_extend and vim.tbl_deep_extend deep do not specify a return value, wich can make people (like me) think that they are mutating the first table to append the provided properties to it. I had to look at the code to understand that it is not the case, and that it just returns a new map. I think the existing behavior is correct, but should be documented better. 

### Actual behavior

Documentation lacks the return value

**Comment by clason** [comment]
Want to make a PR?

**Comment by danielo515** [comment]
the docs are generated from the comments right? I can open a PR, but maybe it's worth asking the author of some open PR to include this? if it is small enough to be worth adding extra content, if not I can just open one to document this two

**Comment by danielo515** [comment]
This seems to be addressed via #17933

**Comment by clason** [comment]
Well, then you're off the hook ;)

(Still, PRs welcome, if you find other missing return types.)

**Comment by dundargoc** [comment]
This has been fixed.
