### ISSUE TITLE
Upstream utility functions from nvim-treesitter

### ISSUE THREAD

**Issue by gpanders** [neovim/neovim#17974]
### Feature description

Well-tested "utility" style functions from nvim-treesitter (and other projects under the nvim-treesitter umbrella) should be upstreamed into Neovim proper under the `vim.treesitter` namespace.

For example, most (perhaps all) of the functions in [ts_utils.lua](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/ts_utils.lua) are good candidates.

IMO the ultimate goal should be that other plugins that want to make use of Treesitter (such as [vim-matchup](https://github.com/andymass/vim-matchup) or [nvim-treesitter-context](https://github.com/romgrk/nvim-treesitter-context)) can do so without using `nvim-treesitter` as a dependency, instead relying strictly on Neovim's own Treesitter APIs.

**Comment by clason** [comment]
Don't forget https://github.com/nvim-treesitter/playground/blob/master/lua/nvim-treesitter-playground/utils.lua!

**Comment by theHamsta** [comment]
Good idea. It might be a good idea to review to review them. I know some of them are not as efficient as they could be and some do some weird things to get along with what the languagetree provides them (iterating over all trees over and over again because certain information is not exposed). So review which parts should be done in languagetree and which in ts_utils to make both as simple/correct as possible.

**Comment by zbirenbaum** [comment]
> Good idea. It might be a good idea to review them as they wary in quality (but they are at least battle tested that they are doing the correct thing). I know some of them are not as efficient as they could be and some do some weird things to get along with what the languagetree provides them (iterating over all trees over and over again because certain information is not exposed). So review which parts should be done in languagetree and which in ts_utils to make both as simple/correct as possible.

The iterating trees over and over again is very true. I recently refactored an inefficient plugin for highlighting 'unused' diagnostics. I was able to make it better by converting the autocmd groups to an actual handler, and doing some caching, but the biggest issue was and remains treesitter.

The fact that given a precise line and range of characters, I have to iterate the whole language tree of the line, maybe even more than that, just to get the colors (via highlight groups) of the tokens within that range, when treesitter has to have that information already stored somewhere internally to even perform the highlighting is just ridiculous.

**Comment by clason** [comment]
Discussions about improvements should be made on the specific PR upstreaming a relevant function; if there is a **specific** codepath already in Neovim that can be improved, please open a dedicated issue (or, better yet, a PR). General griping about efficiency here is not helpful.

**Comment by qrasmont** [comment]
So the idea would be this: https://github.com/qrasmont/neovim/commit/f4954806db8f70efbc6723a59459660a5c8ac817
Create a new utils table under `vim.treesitter` that exposes all those utility functions ?

**Comment by gpanders** [comment]
I don’t see any reason to put them under a `utils` namespace. Just put the functions under `vim.treesitter` directly. But yes that’s the right idea. Feel free to open a PR.

We don’t need to do everything all at once, an incremental approach is fine and probably even preferable so we can audit the implementations in chunks.

**Comment by dundargoc** [comment]
This looks to be finished on the account of https://github.com/neovim/neovim/pull/18232 being finished. Can reopen if we missed something.
