### ISSUE TITLE
The result of `autocmd {event} {pat}` seems not filtered by `{pat}` from Neovim 0.7.0

### ISSUE THREAD

**Issue by lambdalisue** [neovim/neovim#17973]
### Neovim version (nvim -v)

v0.7.0-dev+1373-g80d4d6b48

### Vim (not Nvim) behaves the same?

no with Vim 8.2.4600 and Neovim 0.6.1

### Operating system/version

macOS 12.3.1

### Terminal name/version

iTerm2 3.4.15

### $TERM environment variable

xterm-256color

### Installation

homebrew (with --HEAD)

### How to reproduce the issue

Create `test.vim` as

```vim
augroup test
  autocmd! *
  autocmd User A echo "A1"
  autocmd User A echo "A2"
  autocmd User A echo "A3"
  autocmd User B echo "B1"
  autocmd User B echo "B2"
  autocmd User B echo "B3"
augroup END

autocmd User A
```

Then

1. `nvim --clean test.vim`
2. `:source %`

### Expected behavior

```
--- Autocommands ---
test  User
    A         echo "A1"
              echo "A2"
              echo "A3"
```

This is the result of Vim and Neovim 0.6.1

### Actual behavior

```
--- Autocommands ---
test  User
    A         echo "A1"
              echo "A2"
              echo "A3"
    B         echo "B1"
              echo "B2"
              echo "B3"
```

This is the result of Neovim 0.7.0-dev.

Note that it seems it does not filter the result with `{event}` as well.

**Comment by dundargoc** [comment]
Bisected. Shockingly enough the culprit is the [3000+ line autocmd PR](https://github.com/neovim/neovim/pull/14661)

**Comment by zeertzjq** [comment]
It is filtered by `{event}`. It is not filtered by `{pat}`.

**Comment by zeertzjq** [comment]
Another regression: behavior of `autocmd * A` is now equivalent to `autocmd *`.
