### ISSUE TITLE
`:normal! gQi` leads to a hang

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#17980]
### Neovim version (nvim -v)

v0.6.0 and HEAD

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.24.4

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean`
2. Type `:normal! gQi` and press Enter

### Expected behavior

Editor does not hang

### Actual behavior

Editor hangs until `CTRL-C` is pressed

**Comment by dundargoc** [comment]
https://github.com/neovim/neovim/pull/14311

**Comment by zeertzjq** [comment]
Yes, I know it is a regression from that PR.
