### ISSUE TITLE
floating window borders do not display properly

### ISSUE THREAD

**Issue by Yggdroot** [neovim/neovim#17996]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+162-g2ae9ff128

### Vim (not Nvim) behaves the same?

no

### Operating system/version

centos 7

### Terminal name/version

gnome terminal

### $TERM environment variable

xterm-256color

### Installation

homebrew 

### How to reproduce the issue

test.vim
```vim
function! NewFloating() abort
    " Open a new floating window.
    let l:buf = nvim_create_buf(v:false, v:true)
    let l:row = &lines / 4
    let l:col = &columns / 4
    let l:height = &lines / 4
    let l:width = &columns / 4
    let l:win = nvim_open_win(
        \l:buf,
        \v:true,
        \{
        \   'relative': 'editor',
        \   'border': 'single',
        \   'row': l:row,
        \   'col': l:col,
        \   'width': l:width,
        \   'height': l:height
        \}
    \)
endfunction

call NewFloating()
```
nvim --clean test.vim

:so %

**Note**: 

### Expected behavior

<img src="https://user-images.githubusercontent.com/32942052/107547681-908cd000-6b82-11eb-8dfa-cb29d9cc26ee.png">

### Actual behavior

<img width="417" alt="x" src="https://user-images.githubusercontent.com/2705841/161668902-5b20e190-89c5-4b80-94dd-54bd553eaa7b.png">

**Comment by zeertzjq** [comment]
I cannot reproduce using either kitty, Konsole, or GNONE Terminal. Does this happen if you use another terminal emulator?

**Comment by Yggdroot** [comment]
xshell and MobaXterm do not have the issue. xshell and MobaXterm display "╔" with 1 character width, my GNOME Terminal 3.14.3 displays "╔" with 2 character width, that is the cause.

**Comment by erw7** [comment]
Some of the default border characters include so-call East Asian Ambiguous characters. Therefore, when `p_ambw` is `double`, borders other than `solid` and `shadow` must be set to error.

**Comment by tvercruyssen** [comment]
I had this issue and resolved it by setting the FloatBorder color to something else.
I assume what you're seeing is just the default which has a guibg set.
Example setting in init.vim: 
```vim
highlight FloatBorder guifg=#021316
```
FloatBorder is relatively new and NeoVim specific so most popular colorschemes for Vim won't have it set.
