### ISSUE TITLE
Incorrect highlighting in markdown when link broken across lines in nested list

### ISSUE THREAD

**Issue by joshtriplett** [neovim/neovim#17990]
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

Yes, 8.2.3995

### Operating system/version

Debian unstable (as of 2022-04-03)

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0

### $TERM environment variable

xterm-256color

### Installation

Debian neovim package

### How to reproduce the issue

Place the following contents in `test.md`:
```
- word
    - [two
      words](https://example.org)
    - another bullet

more text
```

```
nvim --clean test.md
```

```
:syn on
```

Notice that "another bullet" and "more text" are highlighted as though they're a link, while "words" isn't.

### Expected behavior

I'd expect to see the link text highlighted as a link, and non-links not highlighted as links.

### Actual behavior

Link text on the second and subsequent lines of nested bullets not highlighted as a link; subsequent text after the link highlighted as a link.

**Comment by zeertzjq** [comment]
This should be reported to <https://github.com/tpope/vim-markdown>, and there may already be an issue for this there.

**Comment by joshtriplett** [comment]
As far as I can tell, this is https://github.com/tpope/vim-markdown/issues/4 . The workaround in https://github.com/tpope/vim-markdown/issues/4#issuecomment-148392021 works, but it's a workaround, not a fix. It doesn't look like there are any plans to fix that issue.
