### ISSUE TITLE
Neovim set filetype of html files to sh

### ISSUE THREAD

**Issue by gabrielssprog** [neovim/neovim#18004]
### Neovim version (nvim -v)

v0.7.0-dev

### Vim (not Nvim) behaves the same?

no, 8.1.3741

### Operating system/version

ubuntu 20.04

### Terminal name/version

gnome-terminal 3.36.2

### $TERM environment variable

xterm-256color

### Installation

sytem package

### How to reproduce the issue

1. Create a empty html file
2. Open file with neovim
3. Run `:echo &ft`

### Expected behavior

Output of `:echo &ft` should be `html`

### Actual behavior

Output of `:echo &ft` is `sh`

**Comment by clason** [comment]
Cannot reproduce. Are you testing with `nvim --clean`?

**Comment by gabrielssprog** [comment]
sorry, testing with `nvim --clean` actually makes the bug go away, but when I run only with `nvim` (even deleting the `~/.config/nvim` directory) the bug reoccurs.

**Comment by clason** [comment]
check your plugins. (packages are sourced automatically -- which is why testing with `nvim --clean` is mandatory)

**Comment by gabrielssprog** [comment]
ok, thanks

**Comment by clason** [comment]
(removing `.local/share/nvim` will wipe them, unless you have customized the location)

**Comment by clason** [comment]
Feel free to reopen if you can reproduce it with a minimal `init.vim` and no plugins.

**Comment by gabrielssprog** [comment]
> (removing `.local/share/nvim` will wipe them, unless you have customized the location)

thanks for the help, after remove polyglot the bug go away 🤝

**Comment by clason** [comment]
ah, polyglot...
