### ISSUE TITLE
vim.lsp.codelens.refresh does not work if any call to on_codelens has err.

### ISSUE THREAD

**Issue by johnybx** [neovim/neovim#18008]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1380-gaf1b61f34

### Language server name/version

rust-analyzer bc08b8e 2022-04-01 dev

### Operating system/version

Arch linux

### Steps to reproduce using "nvim -u minimal_init.lua"

When you call `vim.lsp.codelens.refresh` there is [flag set](https://github.com/neovim/neovim/blob/233014f92b5d4d5bf8a6f019241aafd1b05dd383/runtime/lua/vim/lsp/codelens.lua#L247) to prevent concurrent calls for same buffer but the problem is that if result contain err than the flag is never cleared [here](https://github.com/neovim/neovim/blob/233014f92b5d4d5bf8a6f019241aafd1b05dd383/runtime/lua/vim/lsp/codelens.lua#L217) so no following `vim.lsp.codelens.refresh` will take effect. This is for example case for rust-analyzer which takes some time to start so even though the autocmd is set in `on_attach` function
```vimscript
autocmd CursorHold,InsertLeave <buffer=%s> lua vim.lsp.codelens.refresh()
```
the first refresh fails. The only workaround is to manually call 
```lua
    vim.lsp.buf_request(
        _bufnr,
        "textDocument/codeLens",
        { textDocument = vim.lsp.util.make_text_document_params(_bufnr) }
    )
```
which will trigger `vim.lsp.codelens.on_codelens` again and clear the flag if set.

I am not sure if there is reason for the assert or it can be changed to:
```lua
function M.on_codelens(err, result, ctx, _)
  if err then
    active_refreshes[ctx.bufnr] = nil
    error(vim.inspect(err))
  end
...
end
```

### Expected behavior

even if client return `err` when `vim.lsp.codelens.refresh` is called I would expect the `active_refreshes[ctx.bufnr]` flag to be cleared.

### Actual behavior

`vim.lsp.codelens.refresh` has no effect if lsp server returned any error.

**Comment by mfussenegger** [comment]
Should get fixed with https://github.com/neovim/neovim/pull/18331
