### ISSUE TITLE
filetype.lua does not detect go.mod files

### ISSUE THREAD

**Issue by wilriker** [neovim/neovim#18001]
### Neovim version (nvim -v)

v0.7.0-dev+1395-ge135adcb8

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux 5.17

### Terminal name/version

tmux 3.2a

### $TERM environment variable

tmux-256color

### Installation

AUR

### How to reproduce the issue

* Start nvim with
```
vim.g.did_load_filetypes = 0
vim.g.do_filetype_lua = 1
```
* Open a `go.mod` file

### Expected behavior

Filetype is set to `gomod`

### Actual behavior

No filetype is set.

**Comment by clason** [comment]
Yes, that is known. `filetype.lua` doesn't have parity with `filetype.vim` yet as it's missing some of the more involved filetype checks that look at the file contents (`.mod` files can be either `gomod`, `lprolog`, or `modsim3` files).

**Comment by zeertzjq** [comment]
Hmm, this means `test_filetype_lua.vim` does not do what it is intended to do. Before #17003 `filetype_spec.lua` also had `['gomod'] = {'go.mod'},`, but it didn't fail either.

**Comment by gpanders** [comment]
> Hmm, this means `test_filetype_lua.vim` does not do what it is intended to do. Before #17003 `filetype_spec.lua` also had `['gomod'] = {'go.mod'},`, but it didn't fail either.

`test_filetype_lua.vim` still uses filetype.vim as a fallback: it checks that filetype.lua doesn’t get anything wrong, *not* that it covers every case.

Disabling filetype.vim with `let g:did_load_filetypes = 0` is still considered experimental.

If we flip the flag for filetype.lua in the 0.8 release cycle and make it opt-out, we can update the test to also check for missing cases.

**Comment by zeertzjq** [comment]
Should be fixed by #18057

**Comment by wilriker** [comment]
I can confirm that it detects a Golang `go.mod` as `ft=gomod` now! :+1: 
Thanks

**Comment by dundargoc** [comment]
@eeeXun cannot recreate. Make sure to test neovim with the `--clean` flag to see if a plugin is interfering, or if there are old runtime files that needs to be removed.

**Comment by clason** [comment]
The filetype check for `.mod` files is also based on the file _contents_ (different filetypes using the same extension), which can never be more than a heuristic. So you'd need to share the exact file (or at least the first ten non-blank lines or so) to see whether this is a bug or just one of the cases where the heuristic fails.

**Comment by eeeXun** [comment]
I've tested with `nvim --clean`

```
module gtt

go 1.19

require (
	github.com/gdamore/tcell/v2 v2.4.1-0.20210905002822-f057f0a857a1
	github.com/hajimehoshi/go-mp3 v0.3.3
	github.com/hajimehoshi/oto/v2 v2.3.1
	github.com/rivo/tview v0.0.0-20220911190240-55965cf21d8e
	github.com/spf13/viper v1.13.0
)

require (
	github.com/fsnotify/fsnotify v1.5.4 // indirect
	github.com/gdamore/encoding v1.0.0 // indirect
	github.com/hashicorp/hcl v1.0.0 // indirect
	github.com/lucasb-eyer/go-colorful v1.2.0 // indirect
	github.com/magiconair/properties v1.8.6 // indirect
	github.com/mattn/go-runewidth v0.0.13 // indirect
	github.com/mitchellh/mapstructure v1.5.0 // indirect
	github.com/pelletier/go-toml v1.9.5 // indirect
	github.com/pelletier/go-toml/v2 v2.0.5 // indirect
	github.com/rivo/uniseg v0.4.2 // indirect
	github.com/spf13/afero v1.8.2 // indirect
	github.com/spf13/cast v1.5.0 // indirect
	github.com/spf13/jwalterweatherman v1.1.0 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/subosito/gotenv v1.4.1 // indirect
	golang.org/x/sys v0.0.0-20220712014510-0a85c31ab51e // indirect
	golang.org/x/term v0.0.0-20210220032956-6a3ed077a48d // indirect
	golang.org/x/text v0.3.7 // indirect
	gopkg.in/ini.v1 v1.67.0 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
```

**Comment by zeertzjq** [comment]
The first line starts with `module`? That seems to be detected as rapid.
