### ISSUE TITLE
A Modern NeoVimdoc

### ISSUE THREAD

**Issue by sisrfeng** [neovim/neovim#18017]
### Feature already in Vim?

No

### Feature description

I have struggled with `:help` for a few weeks and find the format of vimdoc needs to be improved:
1. use tabstop=8 and textwidth=78 makes a line too short, so a sentence often can't fit into a line.

![image](https://user-images.githubusercontent.com/53520949/162165578-e7584357-5c09-4bf0-95db-36e9893119af.png)

2. Many redundant because of the exisit of helptag

![image](https://user-images.githubusercontent.com/53520949/162165391-1b912733-aff8-4858-beb4-1d491a48ef54.png)

3. Table of content seems to only have 2 levels, far from enough for some topics which have many 'if' branches
4. For most (neovim) users (I believe), vi default values are useless and annoying. {not in Vi} clutters up the document.
ref: https://groups.google.com/g/vim_dev/c/v01mzeb2kz4 
![image](https://user-images.githubusercontent.com/53520949/162170026-a8666645-4f86-499c-b6ee-1141847ba0ce.png)
  ( So I ask for neovim's developers  instead of original vim's. T) 

My twick (including ftplugin/help.vim and syntax/help.vim):   https://github.com/sisrfeng/modern_vim_doc
 (Sorry for too busy to translate some comments to English)

**Comment by clason** [comment]
This is a bit broad. First, we deliberately take the documentation from Vim and only change it where Neovim diverges. There are no plans to rewrite the upstream documentation, as the increased cost of pulling in upstream changes would significantly outweigh the benefits of better readability. So if Vim doesn't do this, we won't unfortunately either.

That being said, there are (long-term) plans of better export of vimdoc to https://neovim.io/doc/user/, as well as the possibility to use an easier to parse alternative format for Neovim-specific documentation (but these are tracked elsewhere).

**Comment by sisrfeng** [comment]
>  use an easier to parse alternative format for Neovim-specific documentation

Could you provide more information for that? 

What's more,  for  both upstream vimdoc and neovim-specific documentation, I think the alphabetical order  of help tags/content is unfriendly to readers.
For example,
`*nvim_buf_clear_namespace()*` is before   `*nvim_create_namespace()*`

Original doc (folded): 
![image](https://user-images.githubusercontent.com/53520949/180350232-32ddd117-db02-438c-8808-51e8892dc738.png)


Modified doc (with some annoying notation concealed):
![image](https://user-images.githubusercontent.com/53520949/180349927-d19db63c-1d9b-4c1b-ac39-ee36308724a9.png)

**Comment by sisrfeng** [comment]
My improved version of the doc:  https://gitee.com/llwwff/doc_nvim

**Comment by sisrfeng** [comment]
> It returns 403 ;(

Sorry. It is now accessible.

**Comment by justinmk** [comment]
- `gO` shows the outline of all :help docs
- "modern" docs are rendered in HTML form at https://neovim.io/doc/user/ and some have "flow" layout (instead of fixed-width lines), for example https://neovim.io/doc/user/lua.html
    - we are incrementally enabling "flow" layout for more docs
- the door is open for enhancing `:help` to render flow-enabled docs with soft-wrapping instead of hard-wrapping
