### ISSUE TITLE
Some Shift+key not detected with foot and non-qwerty keyboard layout

### ISSUE THREAD

**Issue by cljoly** [neovim/neovim#18010]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1319-gb81c310d4

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

Arch linux, using Sway 1.7 (a wayland compositor)

### Terminal name/version

foot 1.11.0

### $TERM environment variable

foot

### Installation

build from repo

### How to reproduce the issue

Use foot and sway with a [bepo](https://bepo.fr/wiki/Accueil) keyboard layout. Then, `;` is entered with `Shift+,` (which is on the `g` key of a qwerty layout).

Build neovim from the repo on commit b81c310d49f77c8f92ba2fdd99c7e0e9cb49d498 (and presumably any commit on master after that one at the time of writing) and run:
```
./build/bin/nvim -u NONE +'nmap ; :echo ";"<CR>'  +'nmap , :echo ","<CR>'
```

**Note**: I’m opening this issue here per @gpanders [request](https://codeberg.org/dnkl/foot/issues/1009#issuecomment-417525), it was initially reported to [foot](https://codeberg.org/dnkl/foot/) in [this issue](https://codeberg.org/dnkl/foot/issues/1009), as it is unclear whether this is a foot bug or not.

### Expected behavior

Pressing `,` and `;` should result in `,` and `;` being displayed.

### Actual behavior

Pressing `,` displays `,` but `;` does nothing. Note that `:norm ;` causes `;` to be displayed.

**Comment by gpanders** [comment]
I can't reproduce this, but I am also not using the bepo layout.

@cljoly Can you try the following in your shell:

```bash
$ printf '\x1b[>4;2m'
$ cat -v
```

And then enter `;` and `,` as you would in Neovim, and let me know what is printed out.

**Comment by cljoly** [comment]
@gpanders:
```
$ printf '\x1b[>4;2m'
$ cat -v
^[[27;2;59~,
```
So that would be `CSI 27 ; 2 ; 59 ~`

I think this was also covered [on the foot issue](https://codeberg.org/dnkl/foot/issues/1009#issuecomment-417823)

**Comment by cljoly** [comment]
This seems solved in https://codeberg.org/dnkl/foot/pulls/1017#issuecomment-418560 as far as I can tell, but we might want to wait for this PR to be merged.

**Comment by cljoly** [comment]
Closing as this was solved in foot.
