### ISSUE TITLE
jedi-vim failed to initialize Pythonjedi-vim requires Vim with support for Python 3. (in function jedi#init_python[4]..<SNR>100_init_python, en la línea 4)

### ISSUE THREAD

**Issue by jackdelaguilavilla03** [neovim/neovim#18011]
### Neovim version (nvim -v)

NVIM v0.6.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilado por runneradmin@fv-az152-430  Features: -acl +iconv +tui See ":help feature-compile"       archivo "vimrc" del sistema: "$VIM\sysinit.vim"             predefinido para $VIM: "C:/Program Files/nvim/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 11 Pro  22H2  / 22581.200

### Terminal name/version

Windows Terminal

### $TERM environment variable

powershell 7

### Installation

chocolatey

### How to reproduce the issue

nvim file.py 

### Expected behavior

Normal behavior by coc-python and jedi self-filler

### Actual behavior

```
Se ha detectado un error al procesar function jedi#init_python[11]..<SNR>65_display_exception:
línea   19
Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 3. 
(in function jedi#init_python[4]..<SNR>65_init_python, en la línea 4)
```

**Comment by theHamsta** [comment]
Have you installed `pynvim` via pip? Have you run `:checkhealth` for more info on the Python provider?

**Comment by jackdelaguilavilla03** [comment]
yes, I solved mi problem , because I have two jedi 

` Plug 'davidhalter/jedi-vim' `
`Plug 'pappasam/coc-jedi', { 'do': 'yarn install --frozen-lockfile && yarn build', 'branch': 'main' } `

I have conflict with python interpreter, and I had  coc-jedi , but Uninstall all coc and reinstall all now
