### ISSUE TITLE
:! (bang command) problems using powershell on Windows

### ISSUE THREAD

**Issue by TheLeoP** [neovim/neovim#18014]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1341-g79dcd045d

### Vim (not Nvim) behaves the same?

I can't test

### Operating system/version

Windows 10 Pro. Version: 21H1

### Terminal name/version

Windows terminal 1.11.3471.0

### $TERM environment variable

vtpcon

### Installation

I downloaded the precompiled Windows version from the oficial Github repo

### How to reproduce the issue

1. `nvim --clean`
2. set the following options from `:help powershell`
```vim
	let &shell = 'powershell'
	let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
	let &shellredir = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
	let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
	set shellquote=
	set shellxquote=

```
3. `:new`
4. `:%ls`

### Expected behavior

The output of ls is inserted into the current buffer.

### Actual behavior

The error message `E485: No se puede leer el archivo C:\path\to\temp\file` is displayed. `:help E485` says

```vimhelp
							*E484* *E485*  >
  Can't open file {filename}
  Can't read file {filename}

Vim cannot read a temporary file.  Especially on Windows, this can be caused
by wrong escaping of special characters for cmd.exe; the approach was
changed with patch 7.3.443.  Try using |shellescape()| for all shell arguments
given to |system()|, or explicitly add escaping with ^.  Also see
'shellxquote' and 'shellxescape'.

```

But without any config (`nvim --clean` which uses cmd.exe as default shell) this works properly. Also, I checked the path and the temp file isn't being created.

**Comment by justinmk** [comment]
#15913

**Comment by 3N4N** [comment]
@justinmk I did [find the source of the bug and fixed it](https://github.com/neovim/neovim/pull/16271).
