### ISSUE TITLE
Triggering macro record via custom map fails when executed after playing macro

### ISSUE THREAD

**Issue by svermeulen** [neovim/neovim#18015]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1400-g233014f92

### Vim (not Nvim) behaves the same?

No.  This problem does not exist with vim 8.2

### Operating system/version

macOS 12.2.1

### Terminal name/version

zsh

### $TERM environment variable

xterm-256color

### Installation

Downloaded from the nightly job github releases page

### How to reproduce the issue

* `nvim --clean`
* Open a text file
* `:nnoremap s qa`
* `qa` to begin recording macro
* `jj` to add some content to macro
* `q` to end recording
* `@a` - should execute macro correctly and go down two lines
* `s` - Insert mode is entered.  The `s` mapping above seems to have been executed as if it was just `a`

### Expected behavior

We should be able to add a custom key map to start recording a macro to a custom register.

### Actual behavior

Custom key maps to start recording macros sometimes do not start recording and instead execute as if the `q` was ommitted

**Comment by svermeulen** [comment]
This behaviour is new to vim 0.7.x (or possibly 0.6.x).  Does not occur in neovim 0.5.0

**Comment by zeertzjq** [comment]
Vim seems to have a similar bug when the last character of the macro is a character-find command and the next character comes immediately:
```vim
call setline(1, 'aaa')
nnoremap s qa
let @a = 'fa'
call feedkeys("@asq\<Esc>", 't')
```

**Comment by svermeulen** [comment]
Thank you for this!   It is working again for me.
