### ISSUE TITLE
Separate front-end and back-end

### ISSUE THREAD

**Issue by tristone13th** [neovim/neovim#18028]
### Feature already in Vim?

No

### Feature description

Consider following scenario:

You work in Asia and you have a server in America, the delay between you and your server is high. If you use ssh then launch a new nvim instance in the remote ssh, your will have a laggy experience. The main reason is that for each key stroke, you must wait until the server send the response back, but really you don't need the server to do in this style because instance processing is not needed. For an example, you can edit the file locally then write in one time rather than send the char to the remote file for each keystroke. I think one solution is to  separate the front-end and back-end and design a clear interface.between them like VSCode-remote, what would you say about this?

**Comment by clason** [comment]
I say check out https://github.com/chipsenkbeil/distant

**Comment by clason** [comment]
(Closing this as this much too vague to use as a tracking issue.)

**Comment by justinmk** [comment]
> I think one solution is to separate the front-end and back-end and design a clear interface.between them like VSCode-remote

Do you have a reference / documentation exposition for the vscode architecture?

Many editors have tried CRDT as a solution to this, but I think vscode's architecture hinges on its filesystem abstraction. So the editor is running on the "frontend", and the backend mostly handles file I/O.

For TUI software like Nvim, what @clason mentioned is good, or something like [Mosh](https://mosh.org/).
