### ISSUE TITLE
gopls claims invalid type in some cases in go 1.18, but only when run via neovim lsp

### ISSUE THREAD

**Issue by debugloop** [neovim/neovim#18037]
### Neovim version (nvim -v)

v0.7.0-dev+1275-g00effff56

### Language server name/version

gopls 0.8.2

### Operating system/version

Archlinux

### Steps to reproduce using "nvim -u minimal_init.lua"

1. replace lines 68 and 69 in the minimal config with:
```lua
  local name = 'gopls'
  local cmd = { 'gopls' }
```

2. open test file:
```go
package main

import "reflect"

func main() {
	val := reflect.Value{}
	val.Interface().(uint8) // does not matter what we assert...
}
```

3. observe the error in line 7, check the hover func (`K`) of `.Interface()` too

### Expected behavior

No error, as in VSCode for instance: https://i.imgur.com/ts6mGAg.png

### Actual behavior

An error is detected: https://i.imgur.com/0FCgrHs.png

Note the wrong return type in the hover menu too, it claims `invalid` already. Refactoring fixes the error, but shouldn't if it were an actual error: https://i.imgur.com/r18bDl5.png

### Log file

https://gist.github.com/debugloop/fcaa5b6b03e4f7786b7ce437ec284d42

**Comment by fsouza** [comment]
That error likely means you built gopls with Go 1.17 (or earlier). Try reinstalling gopls (and make sure you're building it with Go 1.18)

**Comment by debugloop** [comment]
Thanks @fsouza, I really ought to have thought of this myself...
