### ISSUE TITLE
HOME and END does not work properly in neovim in tmux in ubuntu

### ISSUE THREAD

**Issue by aik** [neovim/neovim#18034]
### Neovim version (nvim -v)

NVIM v0.4.4

### Vim (not Nvim) behaves the same?

no, Vi IMproved 8.2 (2019 Dec 12, compiled Nov 08 2021 14:19:29)

### Operating system/version

Ubuntu 21.04

### Terminal name/version

tmux 3.1c

### $TERM environment variable

xterm

### Installation

Ubuntu 21.04 packages

### How to reproduce the issue

Home/end keys do not work when nvim runs under tmux. They do in vim (always) and nvim (when no tmux).

### Expected behavior

Home/end should always work.

### Actual behavior

Home/end does not work in nvim under tmux.
https://github.com/neovim/neovim/issues/13292 does not help. I run nvim/vim over ssh.

Update: tried my laptop with Fedora 35 so there is no ssh, the exact same story.
Vi IMproved 8.2 (2019 Dec 12, compiled Mar 01 2022 00:00:00)
NVIM v0.6.1
tmux 3.2a
xterm-256color

**Comment by zeertzjq** [comment]
Does setting `$TERM` to `screen-256color` work?

**Comment by aik** [comment]
> Does setting `$TERM` to `screen-256color` work?

hm, it does.

**Comment by zeertzjq** [comment]
Same issue as #6134. However according to the discussion in #6134 this solution seem to cause problems.
