### ISSUE TITLE
`nvim_win_set_height()` misbehaves when window is not vertically split

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#18039]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1385-g6786b6afa

### Vim (not Nvim) behaves the same?

No, it doesn't have Lua api

### Operating system/version

Xubuntu 20.04

### Terminal name/version

xfce4-terminal 0.8.9.1 (Xfce 4.14)

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

1. `nvim --clean`.
2. `:lua vim.api.nvim_win_set_height(0, 15)`. It updates window height (although documentation said it shouldn't).
3. `:echo cmdheight`. It shows 1.
4. `:set cmdheight=5`. It update `cmdheight` and shows two statuslines.

### Expected behavior

Either updating `cmdheight` or doing nothing as `nvim_win_set_width()`.

### Actual behavior

![neovim-issue-nvim_win_set_height](https://user-images.githubusercontent.com/24854248/162430387-40cd710d-46da-4d2f-932d-89a96c30693f.gif)

**Comment by monkoose** [comment]
There is definitely some difference between vim and neovim

`:15wincmd _` behaves the same as `nvim_win_set_height`, but in vim this second statusline would be removed on cmdline enter and in vim line where you type is always after the statusline, but in neovim it is at the bottom of the neovim it depends on `cmdheight` so with `cmdheight=1` it is always on the last raw of the screen.

**Comment by dundargoc** [comment]
I think this has been fixed in https://github.com/neovim/neovim/pull/17335. cmdheight is correctly updated after that commit.

**Comment by dundargoc** [comment]
Please test the latest master and confirm :)

**Comment by echasnovski** [comment]
Yep, issue itself is fixed in latest nightly build. This makes documentation out of date, though.

**Comment by dundargoc** [comment]
Hmm, yeah, the documentation on `nvim_win_set_height` is a bit suspect, I agree. I'll take a look at it and see if we can come up with something less ambiguous.
