### ISSUE TITLE
Link remaining diagnostic highlight groups

### ISSUE THREAD

**Issue by mvllow** [neovim/neovim#18041]
### Feature description

Currently, it looks like `DiagnosticSign*`, `DiagnosticFloating*`, and `DiagnsticVirtualText*` all link back to their respective simpler form, eg. `Diagnostic<Type>`. The only missing group is `DiagnosticUnderline*`. If this is not intentional I would be happy to attempt a PR 😌

Edit: I now realise the underline is quite different, as it would be `guisp` that needs changed. Feel free to close this if there is not a simple way to inherit these values

**Comment by gpanders** [comment]
> I now realise the underline is quite different, as it would be guisp that needs changed. Feel free to close this if there is not a simple way to inherit these values

This is indeed the reason we don't link them. There is no way to do this kind of linking at present.
