### ISSUE TITLE
<c-6> does not work (c-^ does)

### ISSUE THREAD

**Issue by doubleloop** [neovim/neovim#18046]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1416-g012c055804

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian bullseye

### Terminal name/version

alacritty 0.11.0-dev (6737104)

### $TERM environment variable

alacritty

### Installation

repo

### How to reproduce the issue

ensure propper alacritty mapping in `.config/alacritty/alacritty.yml`:

```
  # http://www.leonerd.org.uk/hacks/fixterms/
  - { key: Key1,           mods: Control,                    chars: "\x1b[49;5u"           }
  - { key: Key2,           mods: Control,                    chars: "\x1b[50;5u"           }
  - { key: Key3,           mods: Control,                    chars: "\x1b[51;5u"           }
  - { key: Key4,           mods: Control,                    chars: "\x1b[52;5u"           }
  - { key: Key5,           mods: Control,                    chars: "\x1b[53;5u"           }
  - { key: Key6,           mods: Control,                    chars: "\x1b[54;5u"           }
  - { key: Key7,           mods: Control,                    chars: "\x1b[55;5u"           }
  - { key: Key8,           mods: Control,                    chars: "\x1b[56;5u"           }
  - { key: Key9,           mods: Control,                    chars: "\x1b[57;5u"           }
```

then run `nvim --clean`, open 2 files, try to toggle visible file using `<c-6>` (:h ctrl-6)

### Expected behavior

`<c-6>` works same as `<c-^>`

### Actual behavior

`<c-6>` works as pressing `6`

the workaround is to explicitly specify mapping:
```
vim.keymap.set('n', '<c-6>', '<c-^>', { noremap = true })
```
which should not be needed.

**Comment by zeertzjq** [comment]
Porting <https://github.com/vim/vim/commit/828ffd596394f714270a01a55fc3f949a8bd9b35> should fix this.
