### ISSUE TITLE
guicursor style hor width adjustment not work

### ISSUE THREAD

**Issue by lost22git** [neovim/neovim#18053]
### Neovim version (nvim -v)

v0.6.1

### Vim (not Nvim) behaves the same?

no vim

### Operating system/version

 Microsoft Windows NT 10.0.22000.0

### Terminal name/version

windows terminal 1.12.220314002-release1.12

### $TERM environment variable

no $TERM

### Installation

scoop

### How to reproduce the issue

vim.cmd("autocmd VimLeave * set guicursor=a:hor**20**-blinkwait700-blinkoff400-blinkon250")

or 

vim.cmd("autocmd VimLeave * set guicursor=a:hor**60**-blinkwait700-blinkoff400-blinkon250")

### Expected behavior

Different values show different widths

### Actual behavior

Different values show the same width

**Comment by zeertzjq** [comment]
I think Windows Terminal doesn't support these?

**Comment by test210820** [comment]
The windows terminal has this (not hot reload) configuration 🤷‍♂️

### config page
![image](https://user-images.githubusercontent.com/65008815/162572419-3996a1a2-a92f-4075-ba5c-4d9ca3ae6e7f.png)

### config json file
![image](https://user-images.githubusercontent.com/65008815/162572515-8da307c6-6759-4acc-9b55-e98a02550d7c.png)

**Comment by erw7** [comment]
In tui, `N` in `hor{N}` or `ver{N}` is ignored. Therefore, this will only work with a GUI that has that functionality. I think the help needs to be modified.

**Comment by justinmk** [comment]
guicursor in terminal is best-effort. Not going to document every little terminal quirk in `:help 'guicursor'`.
