### ISSUE TITLE
set clipboard==unnamed corrupts yank register

### ISSUE THREAD

**Issue by pgdouyon** [neovim/neovim#1806]
Apologies if this is a duplicate or known bug, I haven't seen this reported anywhere.

With the 'clipboard' option set to 'unnamed', delete and change operations write to register 0 (which is supposed to be reserved for the most recent yank), corrupting the most recent yank value which is supposed to be stored there (:h quote0).

Yank register functionality is restored when resetting clipboard back to the default value.

**Comment by bfredl** [comment]
Can confirm. It probably happened in #1182, where the handling of `clipboard=unnamed` was refactored quite a bit.

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/1814
