### ISSUE TITLE
Go to definition does not work in monorepo

### ISSUE THREAD

**Issue by RyanzpLee** [neovim/neovim#18068]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1387-gd73bf3138

### Language server name/version

tsserver 0.9.7

### Operating system/version

macOS monterey v 12.3

### Steps to reproduce using "nvim -u minimal_init.lua"

1. [Setup a minimal config](https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua)
2. Have tsserver installed npm install -g typescript typescript-language-server
3. [Clone this repo](https://github.com/RyanzpLee/test-monorepo-lsp) and rename test_node_modules to `node_modules` to simulate a global node modules that gets shared across all apps in `apps/`
4. Go to apps/app1/src/page1.jsx and put your cursor on <NiceComponentOverlay />
5. Use <cmd>lua vim.lsp.buf.definition()<CR> which should be mapped to gd
6. it will only jump to line 2 where it is imported.
7. Expected behaviour is to jump to apps/app1/src/pages/page1/components/NiceComponentOverlay/NiceComponentOverlay.jsx
8. Remove test-monorepo-lsp/node_modules/typescript
9. Repeat steps 4 - 5 for desired behaviour

When using coc.nvim or vscode and going to definition, it works straight away and I want this function to be working the same.

### Expected behavior

Expect to jump to the correct file defintion

### Actual behavior

Jumps to the line 2 where the component is imported. Pressing `gd` on this line again does not take it to the file either.

When looking for references with `<cmd>lua vim.lsp.buf.references()<CR>` the file definition does show up, so this is a potential workaround but not the expected workflow.

### Log file

https://gist.github.com/RyanzpLee/2eb5621b8b84d2c673460ffb8b584fa4

**Comment by fsouza** [comment]
This is likely an issue for nvim-lspconfig (assuming you're not customizing the root dir function). The language server is starting with the wrong cwd set.

Since it works with coc.nvim, an easy fix is probably to figure out how coc-tsserver determines the root dir and send that as a PR to nvim-lspconfig.

Personally, I've modified my config to pretty much always prefer my current dir as the root dir, and I take care of starting neovim in the right folder.

**Comment by RyanzpLee** [comment]
Hey @fsouza  just wanted to say love the work on prettierd. 

I'll post the issue in nvim-lspconfig too then, I wasn't sure where it was most suitable. I'm not customizing the root_dir field as I'm just using the minimal config. I will have a look at the coc-tsserver and see how it's done, but I'm not too experience with what to look for. Thanks for the advice.

How have you modified your config to prefer the current dir?

**Comment by mjlbach** [comment]
Yep, you need to override the default `root_dir` to a pattern that won't match package.json in the nested folder. These patterns are just best guess attempts, and are intended to be overridden by the end user.
