### ISSUE TITLE
Idea: lazy-load files (f.e. after sourcing a session)

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#1807]
It'd be nice if after sourcing a saved session, files would lazy load, either all files in a tab when you visit it, or just the file in the focused window, configurable with an option.

**Comment by philix** [comment]
This is only for performance, right?

If so, this feature (actually an optimization) would be really hard to get
right. The ability to get close to fully recovering the session state would
be lost since after sourcing the session, the files wouldn't be open.

__
Felipe O. Carvalho (philix)
http://felipe.rs

**Comment by trusktr** [comment]
The reasoning is that some plugins are really awesome, but they might make a session with 85 files take too long to load. It'd be like Firefox's "don't load tabs until selected" feature vs Chrome that just loads all tabs no matter what.

**Comment by fmoralesc** [comment]
Perhaps the TabNew and TabNewEntered (re: PR #1717) can be used in a plugin to provide this? I'm not sure, though, I haven't tried session loading against it.

**Comment by fmoralesc** [comment]
A method to do this:

1. On session loading, a flag could be set (I'm not sure it session loading already sets a flag)
2. if that flag is set, the read of every file after a new tab is opened is interrupted until the end of the session loading (we can use `BufReadCmd` to do this). The unloaded files are appended to a global list, `g:session_lazy_files`
3. After the session has finished loading, we move back to tab page 1.
3. Then, on BufEnter, if the filename matches in `g:session_lazy_files`, it is read again.

**Comment by justinmk** [comment]
This is essentially impossible to do from the bottom-up because of fundamental assumptions in plugins. It can, however, be approximated by

- using the lazy-loading feature of most plugin managers (vim-plug, dein, etc.)
- on a per-plugin basis, make better decisions about when to do work.

**Comment by trusktr** [comment]
If plugins properly rely on autocmds (events), then shouldn't it just be a matter of firing relevant autocmds after a file is lazily loaded?

**Comment by philix** [comment]
I would say that it's much better to just improve raw performance of neovim
than to come up with a clever and fragile lazy loading scheme.
