### ISSUE TITLE
neovim inserts comment on new line after specific code pattern

### ISSUE THREAD

**Issue by dineshKumar777** [neovim/neovim#18078]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1410-g2c7dc648c

### Vim (not Nvim) behaves the same?

no, in vim it behaves correctly

### Operating system/version

Windows 10

### Terminal name/version

cmd

### $TERM environment variable

xterm-256color

### Installation

releases

### How to reproduce the issue

nvim --clean
:set filetype=typescript or javascript
type this code => await page.goto('https://google.co.in');
and click enter for new line

### Expected behavior

new blank line should be inserted

### Actual behavior

new line inserted with doubleslash as prefix. 
Note: In vim, I am not able to reproduce this.

https://user-images.githubusercontent.com/21097695/162738844-3863891f-5d9d-4eb5-a020-e7b95991a7b5.mp4

**Comment by clason** [comment]
Make sure you have the same settings in Vim and Neovim; the defaults are different (`:h vim-differences`).

**Comment by clason** [comment]
Which Vim version have you tested? I get the same behavior with Vim 8.2.4700 (unsurprisingly, since Neovim uses the same syntax files as Vim).

You should report this issue to the Typescript maintainer listed at the top of the `runtime/syntax/typescript.vim` file.

**Comment by zeertzjq** [comment]
I think this bug should be reported to Vim. This means Vim doesn't take syntax into account when formatting a comment.

**Comment by dundargoc** [comment]
Typescript syntax file is maintained by Bram Moolenaar himself. Your chances of getting this resolved just skyrocketed.

**Comment by zeertzjq** [comment]
Oh, this problem doesn't happen in C. Then it may indeed be a runtime problem.
