### ISSUE TITLE
Typo for tui-input topic

### ISSUE THREAD

**Issue by binyomen** [neovim/neovim#18089]
### Neovim version (nvim -v)

Latest master (commit dbd5242d8e10db4ed077547755f0d84aa8261cb5)

### Vim (not Nvim) behaves the same?

No

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

### How to reproduce the issue

nvim --clean
: h tui-input

### Expected behavior

The word "extended" is spelled correctly.

### Actual behavior

Instead it's spelled "exteneded"

**Comment by dundargoc** [comment]
I'll fix it. Thanks.
