### ISSUE TITLE
Several rogue nvim processes at 100% CPU

### ISSUE THREAD

**Issue by xanderdunn** [neovim/neovim#1808]
Mac OSX 10.10.1.  

I was working in NeoVim inside tmux and I heard my fans start revving up, so I checked who was working hard.  It turns out I had two phantom nvim processes running at 100% CPU:
![screen shot 2015-01-13 at 00 06 55](https://cloud.githubusercontent.com/assets/1313618/5717617/a55325e4-9ab8-11e4-81dc-3491038fd3ee.png)

I closed all of my open nvim sessions and even went as far as exiting all my terminal emulators that could possibly be running NeoVim.  Those two processes remained there at 100%.  

Debug files: 
- Sample of the first rogue [nvim process](https://raw.githubusercontent.com/alexdunn/storage/master/nvim_rogue/nvim_sample1.txt)
- Sample of the second rogue [nvim process](https://raw.githubusercontent.com/alexdunn/storage/master/nvim_rogue/nvim_sample2.txt)
- [spindump](https://raw.githubusercontent.com/alexdunn/storage/master/nvim_rogue/Spindump.txt)
- [sysdiagnose](https://github.com/alexdunn/storage/blob/master/nvim_rogue/sysdiagnose_2015.01.13_00-05-42-0800_71861.tar.gz)

I tried looking at the samples to see what the nvim processes were doing but it means little to me, sorry.

I was able to force kill the processes and restart everything just fine.  I have not yet seen it again.

Could this be related to #1611?

**Comment by philix** [comment]
Run: sudo killall nvim

Does the problem persist if you start nvim again? Can you sample the
process clicking on the gear and send the result to us?

--
Felipe

**Comment by alexdunn** [comment]
@philix I've already added everything you requested. Just doesn't show up in the email.

**Comment by justinmk** [comment]
@tarruda Should `nvim` kill itself if it detects that there are no attached UIs or ttys?

**Comment by tarruda** [comment]
> @tarruda Should nvim kill itself if it detects that there are no attached UIs or ttys?

No. With the `--embed` flag it will exit if the parent process closes its stdin, but thats all.

**Comment by alexdunn** [comment]
I encountered this again.  I'm unsure the cause.  This time around, I noticed that I had been doing quite a few [ack.vim](https://github.com/mileszs/ack.vim) searches immediately before I noticed the phantom process.  But, I can't be sure how long the phantom nvim process was around in the background before I noticed it, so I can't really know if this is related.

**Comment by aktau** [comment]
This is a bit annoying, despite the wealth of information I can't see what the cause is in all those stack traces. If it's spinning at 99.9% CPU usage it should at least have a spike of locations where the instruction pointer is often at. I don't understand it. Could you perhaps try attaching to the misbehaving instances with LLDB and poke at them (bt for backtrace, for example) to see if there's a pattern?

Thanks for the awesome bugreport, I hope we can fix this :).

**Comment by alexdunn** [comment]
@aktau Thanks for looking at it.  

Sure, the next time I see it I'll attach with lldb and so what info I can get.

**Comment by benwaffle** [comment]
bump
in my case neovim had a zombie child python process

**Comment by xanderdunn** [comment]
I haven't seen this in many months.  I'd consider closing it.  I can always open a new one if I run into it again.

**Comment by fmoralesc** [comment]
:+1: let's do that.

**Comment by justinmk** [comment]
@xanderdunn Thanks for followup.

**Comment by phcerdan** [comment]
I have found this 100% CPU in one rogue nvim relatively often.
perf:
+   59.22%    59.20%  nvim     nvim              [.] uv__udp_sendmsg
+   19.25%    19.23%  nvim     nvim              [.] uv__udp_run_completed
+    7.88%     7.88%  nvim     nvim              [.] on_csi
+    6.65%     6.65%  nvim     nvim              [.] put_curr_and_l_to_X
+    2.87%     2.87%  nvim     nvim              [.] uv_tty_reset_mode
+    2.74%     2.74%  nvim     nvim              [.] count_syllables
+    1.39%     1.39%  nvim     nvim              [.] soundfold_find

nvim --version
NVIM 0.0.0-alpha+201510282324 (compiled Oct 29 2015 22:52:18)
Commit: 98b5ec565b955687ad7e2914378d999975b841df
Build type: RelWithDebInfo
Optional features included (+) or not (-): +acl   +iconv    +jemalloc

**Comment by tarruda** [comment]
@phcerdan how do you get that output? It is fairly strange since nvim doesn't use udp. Could you provide more information/steps on how to reproduce it?

**Comment by phcerdan** [comment]
Following http://stackoverflow.com/questions/5071665/profiler-that-attaches-to-running-processes
I run:
perf record -p <id_100%CPU_rogue_nvim> -g
perf report
and then copied and pasted all the non-kernel results.

I tested running the same perf command with my browser id, and it shows firefox processes, so it seems to work, but I am not an expert using profilers.

**Comment by romgrk** [comment]
I also get this issue sometimes. It hasn't happened recently, but I feel that it happens often when I'm playing with syntax and highlight, or when reloading runtime files.

It seems to happen a lot less since I turned autocomplete off. (deoplete.vim)

I should also note that when I get this, the rogue processes are called `vim`, not `nvim`.
(I even have `alias kav=killall -9 vim`, for when it pops a lot.)
