### ISSUE TITLE
Remove or replace more mentions about `'encoding'` being non-UTF-8 in help files

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#18088]
### Feature already in Vim?

N/A

### Feature description

Nvim always has `utf-8` as `'encoding'`, and some mentions about `'encoding'` have previously been removed or replaced with a mention of `'encoding'` being always `utf-8`. (e.g. `:h list2str()`). It may reduce confusion for users to remove or replace more mentions about `'encoding'` being non-UTF-8 in help files.

**Comment by justinmk** [comment]
👍
