### ISSUE TITLE
LSP: support InlayHint, a new feature in LSP Spec 3.17

### ISSUE THREAD

**Issue by oxalica** [neovim/neovim#18086]
### Feature description

[The inlay hint feature](https://github.com/microsoft/language-server-protocol/issues/956) is stabilized in latest [LSP Spec 3.17](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/), and implemented in VSCode.

The latest stable version of rust-analyzer 2022-04-11 already changed the inlay hint interface from the experimental one to the finalized one. Thus it no longer work with nvim's builtin LSP and [lsp_extensions.nvim](https://github.com/nvim-lua/lsp_extensions.nvim). Since it's not an experimental feature anymore, I think it's better to be implemented inside nvim rather than plugins.

**Comment by mjlbach** [comment]
My main motivation for not wanting to do this right now is I'd rather wait for [anticonceal ](https://github.com/neovim/neovim/pull/9496) to be merged.

**Comment by oxalica** [comment]
> I'd rather wait for [anticonceal ](https://github.com/neovim/neovim/pull/9496) to be merged, otherwise we're going to have to hack it with virtual text on the right (how the plugins do it)

Personally, I'd like to have a toggle option to show all of them at the end of line like the plugins do, despite they are called "inlay hints", since intrusive hints interleave the code and make it hard to read.

**Comment by mjlbach** [comment]
I think it's likely we would implement that by allowing the user to override the function that places the decorations, similar to how we do with the diagnostic API (by registering a handler). I don't think we'll add a config option.

**Comment by leaxoy** [comment]
LSP 3.17 also has another awesome feature, `type hierarchy`

**Comment by ttys3** [comment]
gopls already support inlay hints:

https://github.com/golang/tools/blob/master/gopls/doc/settings.md#inlayhint

https://github.com/golang/tools/blob/master/gopls/doc/inlayHints.md

**Comment by oxalica** [comment]
Just a note, I found there are plugins implementing inlay hints now, like
https://github.com/lvimuser/lsp-inlayhints.nvim

**Comment by oblitum** [comment]
> ### Feature already in Vim?
> 
> No

This should be changed to "Yes" now: https://github.com/neovim/neovim/pull/9496#issuecomment-1358017708.
