### ISSUE TITLE
Wishlist: autocomplete from syntax items

### ISSUE THREAD

**Issue by phmarek** [neovim/neovim#1809]
More often than not I'm editing a file that has perfectly fine syntax highlightning, but no (or not much) content yet.
If it was possible to get the keywords and/or other strings used for syntax highlightning via autocompletion, my life would be much easier.

Perhaps, in the long run, it might be easier to provide some file grammer and hook syntax highlightning on to that, then even semantically useful autocompletion could be done. (Instead of trying to match strings and put colors on these.)

**Comment by Shougo** [comment]
I think it is completion plugin's work.
Syntaxcomplete and neocomplete(neocomplcache) can complete from syntax items.

**Comment by kdurant** [comment]
@Shougo the latest neocomplete has bugs. Often scan files, must use **<C-c>** to abort it

**Comment by justinmk** [comment]
@phmarek This is covered by `h ft-syntax-omni`, unless I'm mistaken. Anything more sophisticated is covered by https://github.com/neovim/neovim/issues/396

@kdurant This is not really the place to ambush plugin authors.
