### ISSUE TITLE
Tree-sitter based highlight may be inefficient

### ISSUE THREAD

**Issue by vigoux** [neovim/neovim#18108]
The tree-sitter highlighter code has been written a while ago, and it attempts to overcome an issue at that time about some captures not being returned when limiting the range over which the query runs.

Since some time now, this limitation is not true anymore, and we might need to rewrite and refactor some parts of that (for the better).

**Comment by bew** [comment]
> The tree-sitter highlighter code has been written a while ago, and it attempts to overcome an issue at that time about some captures not being returned when limiting the range over which the query runs.

Are there still things to do related to this?
Would be nice to have a list. If this list exists somewhere else, maybe close this issue?

**Comment by justinmk** [comment]
@bew see https://github.com/neovim/neovim/issues/22426
