### ISSUE TITLE
Start Menu and Desktop shortcuts for MSI installer

### ISSUE THREAD

**Issue by rollingmoai** [neovim/neovim#18119]
### Feature already in Vim?

No

### Feature description

I'm opening this up because https://github.com/neovim/neovim/releases/tag/v0.7.0 has reached stable and this hasn't been implemented in the MSI installer yet (https://github.com/neovim/neovim/pull/18069#issuecomment-1095150040).

Ping @RenFraser

**Comment by RenFraser** [comment]
I'm not quite sure how to do this. The furthest I've got is that it appears we may need to add a windows registry entry to modify the context menu.

**Comment by itsmeboy0** [comment]
> I'm not quite sure how to do this. The furthest I've got is that it appears we may need to add a windows registry entry to modify the context menu.

I believe you are talking about #6649 on this one. The issue here is about start menu and desktop shortcuts.

**Comment by RenFraser** [comment]
Yep got my wires crossed 😅. Shortcuts would be nice.
