### ISSUE TITLE
include common tools in Windows build

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1811]
By including common tools such as curl and xxd, we can build things on top of those tools and know that they will work on all platforms. Here's a list (subject to modification and suggestions):
- [x] HTML tidy ~~(this might allow us to remove `runtime/autoload/xml` #1507)~~
  - http://tidybatchfiles.info (?)
- [x] curl.exe
- [x] diff.exe
- [x] cat.exe
- [x] 7-zip (7za.exe)
- [x] xxd.exe
- [x] tee.exe
- ~~[jq](https://stedolan.github.io/jq/])~~
- [x] ~~[gclip](http://unxutils.sourceforge.net/) or [winclip](http://dmst.aueb.gr/dds/sw/outwit/winclip.html)~~  win32yank
- ...

The [vim-single-drop](https://bitbucket.org/kybu/vim-for-windows-single-drop/overview) project may have some useful techniques to look at.

If we cannot include these tools as part of the Windows deliverable, for legal or technical reasons, then they should be available by a single post-installation step.

---

Note: I mention vim-single-drop only as a reference. I think bundling entire runtimes such as python, ruby, etc. with a text editor is not a good idea and adds a huge support burden.

**Comment by tarruda** [comment]
How about distributing it with [msys](http://www.mingw.org/wiki/MSYS)? This is already done by projects such as git for windows.

**Comment by zj-1** [comment]
That would increase the size of the software greatly.
Just some components of [GnuWin32](http://gnuwin32.sourceforge.net/) (like grep, unix2dos, ctags, indent, etc.) might be ok. If needed, the users could install msys by themselves, and that would be more flexible.

**Comment by tarruda** [comment]
> That would increase the size of the software greatly.
Just some components of GnuWin32 (like grep, unix2dos, ctags, indent, etc.) might be ok. If needed, the users could install msys by themselves, and that would be more flexible.

Agreed. Maybe we should just include the tools required by vim commands(bourne shell, diff..)

**Comment by zj-1** [comment]
I'm not sure whether bourne shell is necessary on windows.
As a vim user on windows for many years, I use shell only in vimrc to have a shortcut of invoking `indent`, `ctags` or `pdflatex`. Besides, there is also windows shell.
just personal opinion :)

**Comment by tarruda** [comment]
@zj-1 at least on unix, vim makes a lot of use of bourne shell features:

- Redirection is used by `system()` function and by commands such as `:diff*`
- Command completion is implemented by globbing the shell
- Bang commands are passed directly to the shell

I'm not sure how these are implemented by vim on windows, but if it uses cmd.exe the result could be inconsistent. By shipping a lightweight bourne shell we eliminate many of these inconsistencies.

**Comment by justinmk** [comment]
MSYS (and cygwin) have [major problems](https://github.com/msysgit/git/issues/301), but MSYS2 could be worth looking at. It's a big liability/support risk though.

> Redirection is used by system() function and by commands such as :diff*

cmd.exe actually has redirection and piping (and Vim uses it). I'm not sure about how Vim for Windows handles advanced globbing though, if at all.

Also keep in mind that the MSYS shell is still hosted by cmd.exe, so it won't avoid encoding or terminal-related issues.

**Comment by equalsraf** [comment]
Also something that can be used for clipboard.vim, @fmoralesc pointed out [gclip](http://unxutils.sourceforge.net/) and [winclip](http://dmst.aueb.gr/dds/sw/outwit/winclip.html)

**Comment by sethjackson** [comment]
> Also something that can be used for clipboard.vim

I assume the built-in Windows `clip` command doesn't support all the things we need?

**Comment by justinmk** [comment]
We should use the win32 for Windows clipboard, though we may still want to allow users/plugins to override it with a custom provider.

**Comment by equalsraf** [comment]
> I assume the built-in Windows clip command doesn't support all the things we need?

Only works one way.

winclip was the best I found, but still have issues with newlines and encoding.

**Comment by equalsraf** [comment]
Any idea where one can find windows builds for diffutils/libint/libiconvl, extra points if not hosted by sourceforge (downloads have been flaky for a while now)

**Comment by justinmk** [comment]
>  extra points if not hosted by sourceforge (downloads have been flaky for a while now)

@equalsraf  We can mirror flaky downloads at https://github.com/neovim/deps (`opt/`).

**Comment by paulburlumi** [comment]
If I download the [nightly win64 build](https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip) I still don't see `xxd.exe`.
Is this just some difference between release and nightly builds or an omission from 2fbc42a?

**Comment by justinmk** [comment]
@paulburlumi That was an oversight, https://github.com/neovim/neovim/pull/8241 should fix it. Thanks for mentioning it.
