### ISSUE TITLE
nvim_eval_statusline() should throw an error for invalid statusline

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#18112]
### Feature description

Passing an invalid statusline to `nvim_eval_statusline()` can potentially cause unexpected behavior or a crash (e.g. `nvim_eval_statusline('%{%}', {})`), so `nvim_eval_statusline()` should throw an error for invalid statusline.

**Comment by timweri** [comment]
Hi @zeertzjq

I'm looking to start contributing to nvim. I plan to work on this issue. I'm completely new to the design of nvim and will probably be quite inefficient. Just dropping this message here to see what your advice would be.

If I have the green light I'll start looking at the function in question [here](https://github.com/neovim/neovim/blob/master/src/nvim/api/vim.c)

**Comment by zeertzjq** [comment]
`check_stl_option()` in `option.c` can be used to check for valid statusline. One thing to note is whether to translate the error message returned by `check_stl_option()`. See #18128.

**Comment by timweri** [comment]
> `check_stl_option()` in `option.c` can be used to check for valid statusline. One thing to note is whether to translate the error message returned by `check_stl_option()`. See #18128.

Seems like something I shouldn't decide. But if I follow the guideline to keep code simple, I'll not translate the error.

**Comment by zeertzjq** [comment]
The problem here is that `check_stl_option()` will sometimes return an already translated error message, and that is hard to deal with.

**Comment by zeertzjq** [comment]
I think that can be decided later.

**Comment by timweri** [comment]
So, should I attempt to address this issue by fixing `nvim_eval_statusline()` to handle invalid statusline correctly? Or should this issue be blocked until the error translation (#18128) is decided?

**Comment by zeertzjq** [comment]
Yes you can do it.
