### ISSUE TITLE
Add MPR package to GitHub Wiki

### ISSUE THREAD

**Issue by hwittenborn** [neovim/neovim#18127]
### Feature description

I added Neovim to the [MPR](https://mpr.makedeb.org/packages/neovim) earlier today. The MPR is like the [Arch User Repository](https://aur.archlinux.org), except it's just designed for Debian and Ubuntu based systems instead.

The main benefit over something like the standard Ubuntu and Debian repository packages is that this one can be made up to date whenever a new Neovim release is made, while the ones in the standard repositories cannot. Over something like the debs provided in the releases, this one can also be updated easier through the use of [MPR helpers](https://docs.makedeb.org/using-the-mpr/list-of-mpr-helpers/), and soon to be a prebuilt repository for APT that'll feature all MPR packages included there as well.

I was gonna add this to the Wiki myself as it appears anyone can edit it, but I didn't see any notes on who was allowed to contribute to it, so I thought I'd make an issue here first.

**Comment by zeertzjq** [comment]
You can just edit the wiki.

**Comment by hwittenborn** [comment]
Alright, sounds good. Thanks!
