### ISSUE TITLE
[windows] init.lua and other lua files can't be loaded if there are non-ASCII characters in pathname

### ISSUE THREAD

**Issue by Geniucker** [neovim/neovim#18122]
### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

i don't know. i use neovim only

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal

### $TERM environment variable

I'm not using linux and I'm using powershell

### Installation

downloaded from release page

### How to reproduce the issue

use Windows  
create an user with Chinese characters such as `测试`  
use config file `init.lua`  
open `nvim`  
it'll report errors
```
Error detected while processing C:\Users\测试\AppData\Local\nvim\init.lua:
E5112: Error while creating lua chunk: cannot open C:\Users\测试\AppData\Local\nvim\init.lua: No such file or directory
```

### Expected behavior

config files should be loaded successfully

### Actual behavior

init.lua and other lua files can't be loaded if the username has Chinese characters(there are Chinese characters in pathname)

**Comment by adamency** [comment]
This is actually far more widespread than exclusive to chinese characters, it seems to be the case with **any non-ASCII character**.

I've got an `é` in my name and I've uselessly spent hours trying to solve the issue investigating package management and filesystem permissions/company restrictions, only to understand in the end that it was yet again the same old diacritic issue.

On the same system than @Geniucker but on **nvim 0.8**, i.e. one major version later. Please devs, understand that you're impacting almost all non native-english speakers.

@Geniucker I hight advise you to change your title to "[...] if the username has non-ASCII characters" to greatly increase visibility on this issue. 

System Info:
Windows 11
Windows Terminal
NVIM v0.8.0-1210-gd367ed9b2 (installed with `scoop` package manager)

**Comment by RoyalTwo** [comment]
Same issue. Unfortunately, the only workaround I can find for now is to create an init file in a root directory and manually select it on startup with `-u`

**Comment by JD557** [comment]
Same issue here.
However, I still use `init.vim`, which works fine until I try to load any lua plugins.

**Comment by zeertzjq** [comment]
A possible workaround is to override the `loadfile()` global function to use `loadstring()` and `vim.fn.readfile()` before loading config:
```
nvim --cmd 'lua function loadfile(filename) return loadstring(vim.fn.readfile(filename, "B")) end'
```

**Comment by bfredl** [comment]
lua's `loadfile()` implementation uses `fopen()` internally. On MS WINDOWS, the standard C API can be configured between behaving _either_ like ca 1985 MS-DOS _or_ latin-1-ish ("ANSI"):

> The fopen function opens the file that is specified by filename. By default, a narrow filename string is interpreted using the ANSI codepage (CP_ACP). In Windows Desktop applications, it can be changed to the OEM codepage (CP_OEMCP) by using the SetFileApisToOEM function. You can use the AreFileApisANSI function to determine whether filename is interpreted using the ANSI or the system default OEM codepage.

Thus, the easiest approach would be for us to replace the builtin `loadfile()` with our own function behaving more or less like zeertzjq's snippet, on windows. We should do this early at startup before `--cmd`, so user can still override it.

**Comment by bfredl** [comment]
the `io.open` function of the lua io library will be similarily broken. this cannot as easily be replaced from the outside. Perhaps we should patch luajit on windows to use our `os_fopen()` emulation instead of the CRT `fopen()`

**Comment by JD557** [comment]
FWIW, this seems to solve the problem: https://b.s5.pm/os/2021/08/28/windows-setup.html#using-utf-8-instead-of-latin-1-by-default

I didn't do any extensive testing, though.

**Comment by erw7** [comment]
`UTF-8` can be set in `ucrt` with `setlocale`. The `ucrt` is already used in `MSVC` builds. Therefore, setting the appropriate value in the `LANG` environment variable, such as `set LANG=.UTF-8` or `set LANG=en_us.utf8` etc, will solve this problem.

Ref. https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-170#utf-8-support

It should be possible to remove some of the codes that use `utf8_to_utf16()` by using `manifest` to set encoding to `UTF-8`.

**Comment by justinmk** [comment]
> It should be possible to remove some of the codes that use `utf8_to_utf16()` by using `manifest` to set encoding to `UTF-8`.

Great idea, to be clear that's this file? https://github.com/neovim/neovim/blob/09b6a68c3700aa5d8ae26a62896b091572ae0a8d/src/nvim/os/nvim.manifest

**Comment by erw7** [comment]
> Great idea, to be clear that's this file? 

The relevant file has `main_lib` as `target`. I think we need to create a separate file with `nvim` as the `target`.

Cc: @dundargoc 

> As a first step, we could check for this in :checkhealth nvim.
>
> Later we could consider forcing it at startup? (Though the "manifest" approach is better.)

In the meantime, I think it would be a good idea to call `setlocale(LC_ALL, ".UTF8");` in [`lang_init()`](https://github.com/neovim/neovim/blob/f140175564001cc1ad84128a0147a5d2f7798a63/src/nvim/os/lang.c#L21). That may be sufficient unless we change to use `main` instead of `wmain`.

**Comment by dundargoc** [comment]
Hmm, I don't think there should be any difference between main_lib and nvim, they should both inherit the manifest file. But we can change main_lib to nvim if that solves it.

**Comment by dundargoc** [comment]
Can people who have this problem test this [PR](https://github.com/neovim/neovim/pull/22384) and see if it solves it for them?

**Comment by zeertzjq** [comment]
You can test [this artifact](https://github.com/zeertzjq/neovim/suites/11200235690/artifacts/572715558)
