### ISSUE TITLE
input.c:382: convert_input: Assertion failed.

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1813]
```
nvim: /home/ubuntu/neovim/src/nvim/os/input.c:382: convert_input: Assertion `converted_length <= rbuffer_available(input_buffer)' failed.
```

This happens after `:set paste` and pasting in a 63879-bytes XML string. I'm pasting from mintty terminal SSH'd to an ubuntu guest VM.

**Comment by justinmk** [comment]
Size of `input_buffer` is `0xfff * 4 * 4` => 65520

**Comment by oni-link** [comment]
Converting the input could increase the size. Or the `input_bffer` was not empty.
Could be related to this: https://github.com/neovim/neovim/issues/1714

**Comment by tarruda** [comment]
Should be fixed on master
