### ISSUE TITLE
Patch 8.1.0877 (PR #17702) causes BufAdd autocommands to be misinterpreted in some very specific circumstances

### ISSUE THREAD

**Issue by dmitmel** [neovim/neovim#18135]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.0

### $TERM environment variable

xterm-kitty

### Installation

Built from source

### How to reproduce the issue

When I first discovered this bug and began investigating, it would appear as a conflict between the [vim-airline](https://github.com/vim-airline/vim-airline) and [vim-qf](https://github.com/romainl/vim-qf) plugins (on default settings), but I then minimized the test case to just the relevant code. Bisecting the neovim repository then led me to commit 91ac0088e1a8bdf189bf96066eb8e0d8e632ceac (PR #17702), and, indeed, reverting that commit when the tag v0.7.0 is checked out "fixes" this bug.

This is `test.vim`:

```vim
" filetype indent plugin off
" syntax off
autocmd QuickFixCmdPost grep nested cclose | cwindow
" autocmd FileType qf set nobuflisted
function Something()
  echomsg "Hi!" bufnr() bufname()
endfunction
autocmd BufAdd * call Something()
```

Then, in the directory of the neovim repository:

```
$ VIMRUNTIME=nope build/bin/nvim --noplugin -u test.vim
```

(the error message about `syntax.vim` not existing can be ignored)

In the editor run `:grep -R TestFiletypeFuncs .`. The message is printed and the quickfix list is opened with a single search result, so far so good. Then run the `grep` command again.

### Expected behavior

No errors.

### Actual behavior

The following error is shown:

```
Error detected while processing BufAdd Autocommands for "*":
E16: Invalid range: call Something()
```

Note that not every `grep` command causes this error, I wasn't able to determine the pattern here, and only a `call` command in `BufAdd` seems to do that. The contents of the `Something` function don't matter and can be removed altogether, even the function itself can be removed, but the `Invalid range` error is still displayed, which leads me to believe that the VimL parser is somehow affected.

**Comment by zeertzjq** [comment]
The cursor position seems to be out of the buffer when the autocommand is executed.

**Comment by zeertzjq** [comment]
Porting <https://github.com/vim/vim/commit/b5383b174b2436b556f76f14badb1c1f55d6d8f6> may fix this.

**Comment by zeertzjq** [comment]
Yes, reverting the change to `parse_cmd_address()` in that patch also produces this bug in Vim.
