### ISSUE TITLE
<c-j> gets shown as <NL> instead in mappings

### ISSUE THREAD

**Issue by SuperCuber** [neovim/neovim#18134]
### Neovim version (nvim -v)

release v0.7.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10 64bit

### Terminal name/version

nvim-qt

### $TERM environment variable

n/a

### Installation

msi installer from release

### How to reproduce the issue
```
nvim-qt -- -u NONE
:nmap <c-j> :echo "test"<cr>
:nmap
```

### Expected behavior

a line for `<c-j> :echo "test"<cr>` is shown

### Actual behavior

a line for `<NL> :echo "test"<cr>` is shown

---
I also tried `map <nl> :echo "test"<cr>` and that maps to \<c-j> in practice as well. Strange.

**Comment by zeertzjq** [comment]
I don't think it is useful to make `<C-J>` different from `<NL>`.

**Comment by zeertzjq** [comment]
Also, what do you mean by "doesn't work in insert"?

**Comment by SuperCuber** [comment]
> I don't think it is useful to make `<C-J>` different from `<NL>`, considering [#17236 (comment)](https://github.com/neovim/neovim/pull/17236#issuecomment-1073126751), and the fact the `<NL>` usually doesn't exist on keyboards, making `<C-J>` different from `<NL>` can cause more confusion than it solves.

If `<nl>` doesn't usually exist wouldn't it be better to show `<c-j>`?

> Also, what do you mean by "doesn't work in insert"?

Forgot to delete that - i was debugging a problem with snippets not working and thought it was related, turns out it wasn't

**Comment by zeertzjq** [comment]
Actually making `<C-J>` different from `<NL>` will not break mappings in TUI, because libtermkey never sends `<NL>` and always sends `<C-j>` for Ctrl-J. The only concern is that this may break plugins.
