### ISSUE TITLE
Make `ui.input()` handle `<C-c>`, `<Esc>`, and empty string input

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#18144]
### Feature already in Vim?

No

### Feature description

At the moment, `vim.ui.input()` has to following behavior:
- When typing `<C-c>` during any time of input, it gives `E5108: Error executing lua Keyboard interrupt`.
- When typing `<Esc>` during any time of input, it stops user query and executes `on_confirm(nil)`.
- When typing `<CR>` as first key of input implying an empty string as input, it behaves exactly like `<Esc>`.

This is mainly because `vim.ui.input()` is basically a wrapper around `vim.fn.input()`, which behaves exactly like this: throws error on `<C-c>` and returns empty string on cancel. Technically, by setting `cancelreturn` field in `opts`, it can return specific string on cancel, but then it can't distinguish between `<Esc>` and that string as input.

My suggestion is for `vim.ui.input()` to have this behavior:
- On `<C-c>` execute `on_confirm(nil)`.
- On `<Esc>` execute `on_confirm(nil)`.
- On `<CR>` as first key execute `on_confirm('')`.

Allowing `<C-c>` seems to be an easy fix by using `pcall(vim.fn.input, ...)`, distinguish between `<Esc>` and empty string is not straightforward. I suggest using temporary key listener with `vim.on_key`.

So the [entire `vim.ui.input()`](https://github.com/neovim/neovim/blob/6e6f5a783333d1bf9d6c719c896e72ac82e1ae54/runtime/lua/vim/ui.lua#L85-L97) will become something like this (also fixing the #18143 issue here):
```lua
local input_ns_id = vim.api.nvim_create_namespace('')

function _G.input(opts, on_confirm)
  vim.validate {
    opts = { opts, 'table', true },
    on_confirm = { on_confirm, 'function', false },
  }

  -- Use temporary listener to distinguish between `<Esc>` and empty string
  local was_cancelled = false
  vim.on_key(function(key)
    if key == vim.api.nvim_replace_termcodes('<Esc>', true, true, true) then
      was_cancelled = true
    end
  end, input_ns_id)

  if opts == nil or vim.tbl_isempty(opts) then
    opts = vim.empty_dict()
  end
  -- Use `pcall` to allow cancelling with `<C-c>`
  local ok, input = pcall(vim.fn.input, opts)

  -- Stop listener
  vim.on_key(nil, input_ns_id)

  if not ok or was_cancelled then
    on_confirm(nil)
  else
    on_confirm(input)
  end
end
```

Happy to do PR if this feature is useful.

**Comment by lambtho12** [comment]
Is there a reason this has not been accepted yet? It seems quite an important feature to distinguish between an aborted input and one left empty on purpose.

**Comment by zeertzjq** [comment]
`on_key` is no longer needed. `input()` can now use type as `cancelreturn`.

**Comment by bfredl** [comment]
Sure, someone just needs to do a PR.

**Comment by wookayin** [comment]
I wrote a PR #20833 that would fix this bug -- it will change the behavior for the empty string (and potentially when `<C-C>` is hit).
