### ISSUE TITLE
Updating zindex of a floating window does not work

### ISSUE THREAD

**Issue by rcarriga** [neovim/neovim#18142]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1280-gf2e5f509d Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/cache/aura/vcs/neovim-git/neovim-git/src/build/config -I/var/cache/aura/vcs/neovim-git/neovim-git/src/neovim-git/src -I/usr/include -I/var/cache/aura/vcs/neovim-git/neovim-git/src/build/src/nvim/auto -I/var/cache/aura/vcs/neovim-git/neovim-git/src/build/include Compiled by ronan@XPS15  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

Kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

AUR

### How to reproduce the issue

```lua
local win = vim.api.nvim_open_win(0, false, {
  relative = "editor",
  anchor = "NW",
  width = 50,
  height = 4,
  col = 1,
  row = 1,
  border = "double",
  style = "minimal",
})

vim.schedule(function()
  vim.api.nvim_win_set_config(win, { zindex = 400 })

  vim.api.nvim_open_win(0, false, {
    zindex = 300,
    relative = "editor",
    anchor = "NW",
    style = "minimal",
    width = 40,
    height = 5,
    row = 1,
    col = 1,
    border = "single",
  })
end)
```

### Expected behavior

The first window (double border) should appear above the second.

Remove the schedule to see expected behaviour
```lua
local win = vim.api.nvim_open_win(0, false, {
  relative = "editor",
  anchor = "NW",
  width = 50,
  height = 4,
  col = 1,
  row = 1,
  border = "double",
  style = "minimal",
})

vim.api.nvim_win_set_config(win, { zindex = 400 })

vim.api.nvim_open_win(0, false, {
zindex = 300,
relative = "editor",
anchor = "NW",
style = "minimal",
width = 40,
height = 5,
row = 1,
col = 1,
border = "single",
})
```

### Actual behavior

The second window appears on top despite having a lower zindex.

**Comment by zeertzjq** [comment]
I don't think "zindex updating" has ever been implemented.
