### ISSUE TITLE
The abnormal behavior in neovim when use csharp-ls

### ISSUE THREAD

**Issue by Decodetalkers** [neovim/neovim#18147]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux  kernel 5.17.3-arch1-1

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

archlinux repo

### How to reproduce the issue

put this line into your config
```vim
autocmd FileType cs autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()
```
mkdir test
cd test
dotnet new console --language "C#" 
nvim Program.cs
```cs
namespace Main
{
    class Test {
        static void Main() {
        }
    }
}
```
copy the line above to the file and exit
reopen the file
enter "using System."
the menu will not popup
Then save the file
then the format will wrong

### Expected behavior

Format right and does not report wrong thing when use csharp-ls

### Actual behavior

I use format and cmp here. but cmp work not well. After "System", it should has menu before.But there is no menu. In neovim 0.6.1 it work. and when delete the line where it report bugs, the warning is not fade.

And I use the format. In neovim 0.6.1, the format work well, but It format wrong in neovim 0.7

https://user-images.githubusercontent.com/60290287/163722835-f586a149-cadc-45d7-88f7-e1624eb6c9ee.mp4

**Comment by chen244** [comment]
I don't know if it is the bug of neovim or the server, because before 0.7, it works will..

**Comment by razzmatazz** [comment]
This looks like incremental document sync error (i.e. the editor things the contents of the file are different from what the server does).

- Maybe we could try disabling incremental sync in nvim (or csharp-ls) to see if this fixes the issue?
- Also, is this deterministic? Does it always happen like this, but what happens if you type slower or perform the edits in some other other?

**Comment by chen244** [comment]
> Maybe we could try disabling incremental sync in nvim (or csharp-ls) to see if this fixes the issue?

After I disable the incremental sync, It works, however, the neovim cannot diagnose and format the script

yes this is deterministic, and I type slower,It may works

**Comment by razzmatazz** [comment]
Hmm, I believe csharp-ls has broken behaviour wr.t. incremental sync..

I was trying to replicate the problem and managed to setup packer+nvim-lspconfig and immediately hit the problem where typing things too fast in nvim triggers document sync problems.

My plan here is to:
- [ ] update csharp-ls to properly handle full sync behaviour from the client (via negotation)
- [ ] add a command line param to force full sync
- [ ] add a PR to nvim-lspconfig to set this param until we have this partial sync bug diagnosed (whether this is csharp-ls or nvim at fault)
- [ ] fix the actual problem

**Comment by razzmatazz** [comment]
So apparently were was a bug in csharp-ls that was related to incremental sync which was being hit by nvim (more often by other clients):

I have released a new version of csharp-ls that should fix the bug:
- https://www.nuget.org/packages/csharp-ls/0.5.1

**Comment by Decodetalkers** [comment]
Fixed
