### ISSUE TITLE
Multiple input is broken when `set cmdheight > 1` and redraw

### ISSUE THREAD

**Issue by Shougo** [neovim/neovim#18140]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+1463-gae325e627

### Vim (not Nvim) behaves the same?

Yes, but the redraw problem is different

### Operating system/version

Manjaro Linux

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

From HEAD source

### How to reproduce the issue

```vim
set cmdheight=2
autocmd CmdlineChanged * redraw
```

```
nvim -u test.vimrc
```

Please input below texts.

```
for i in range(4)
  echo 'hello'
endfor
```

### Expected behavior

All previous input lines are shown in the command line like this.

![スクリーンショット_2022-04-17_13-21-16](https://user-images.githubusercontent.com/41495/163700300-752bf4b7-90cd-480d-ac7b-a3ddb9ee3418.png)

### Actual behavior

![スクリーンショット_2022-04-17_13-18-10](https://user-images.githubusercontent.com/41495/163700212-cfde7233-1666-4bc3-a50d-491c64e45ce4.png)

**Comment by zeertzjq** [comment]
The same problem also happen when resizing window with `cmdheight > 1`.

**Comment by zeertzjq** [comment]
Hmm, now Vim's behavior is the same.

**Comment by Shougo** [comment]
OK.  So the main problem is ...

https://github.com/vim/vim/issues/10210#issuecomment-1102487482

Both floating window and popup window are not updated when command line mode in Vim/neovim.

**Comment by Shougo** [comment]
It will be todo listed in Vim later.

**Comment by Shougo** [comment]
I have researched the problem and it is very hard...
I gave up.

> Both floating window and popup window are not updated when command line mode in Vim/neovim.

It is hard, and if it is implemented the redraw problem remains.
