### ISSUE TITLE
Why is regexp_nfa.c treated differently in build?

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#1815]
See `src/nvim/CMakeLists.txt@40`:
```
  if(${f} MATCHES "^(regexp_nfa.c)$")
     list(APPEND to_remove ${sfile})
  endif()
```

??

**Comment by tarruda** [comment]
Its because Bram decided to inline it into regexp.c instead of making it a separate module:https://github.com/neovim/neovim/blob/master/src/nvim/regexp.c#L6916-L6918

**Comment by elmart** [comment]
Ah, ok. Thanks!
