### ISSUE TITLE
nvim_create_autocmd may be dangerous (hard to trace its source) as the callback doesn't show its contents at all

### ISSUE THREAD

**Issue by milanglacier** [neovim/neovim#18153]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS 12.3.1

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256-color

### Installation

homebrew

### How to reproduce the issue

```
local autocmd = vim.api.nvim_create_autocmd
autocmd('VimEnter', {
    callback = function()
        print 'dog'
    end,
})
```

```
put(vim.api.nvim_get_autocmds {event = 'VimEnter'})
```

shows that

```
{ {
    buflocal = false,
    command = "lua _G.__luacache.save_cache()",
    event = "VimEnter",
    group = 5,
    once = false,
    pattern = "*"
  }, {
    buflocal = false,
    command = "<Lua function 5>",
    desc = "<Lua function 5>",
    event = "VimEnter",
    id = 2,
    once = false,
    pattern = "*"
  }, {
    buflocal = false,
    command = 'lua require("treesitter-context").onVimEnter()',
    event = "VimEnter",
    group = 16,
    once = false,
    pattern = "*"
  }}
```

We see that if the autocmd is defined via `vimL`, then its contents is clearly shown. We know what this autocmd is doing.
But if the autocmd is defined in lua callback, then its contents completely not shown.

passing `{desc = "xxx"}` to `nvim_create_autocmd` might be limitedly helpful in some sense, but this only describes what this autocmd wants to do, it doesn't describe what this autocmd is doing. Even though `desc` is passed, it is still hard to trace where/how the autocmd is define.

This potential issue also happens in `vim.keymap.set` (and any other new introduced API that accepts a lua callback), but `vim.keymap.set` is not dangerous: it will not automatically executed,it only makes things hard to trace, and the `desc` would do better in this case compared to autocmd: `desc` would describe what the keymap wants doing (and it is enough most of the time for the purpose of using keymap, but it is still not easy for users to debug keymap written by other plugins)

### Expected behavior

A potential problem in using `nvim_create_autocmd`

### Actual behavior

A potential problem in using `nvim_create_autocmd`

**Comment by milanglacier** [comment]
I would suggest the lua callback function must be traceable function, cannot be anonymous, must be like `a.b.c()`

**Comment by zeertzjq** [comment]
Related: #15079

**Comment by milanglacier** [comment]
> Related: #15079, this requires `nvim -V1` as it is slow.

`nvim -V1` and `:verbose au` now gives me something like

```
gitsigns_blame  BufLeave
    *         <Lua function 59>
        Last set from ~/.local/share/nvim/site/pack/paqs/opt/gitsigns.nvim/lua/gitsigns/async.lua line 71
```

this is great for tracking source.
Just hope `desc` keys could be stressed to be widely used as common to avoid awkward situation like starting with `nvim -V1 -C ':verbose xxx'` to track source.

**Comment by clason** [comment]
Related: #17588

(If you are using plugins, you already trust the developer fully as these have nearly full control over your system. If that worries you, you will have to audit the sources yourself, after which you will know the contents of the autocommands.)

**Comment by milanglacier** [comment]
> Related: #17588
> 
> (If you are using plugins, you already trust the developer fully as these have nearly full control over your system. If that worries you, you will have to audit the sources yourself, after which you will know the contents of the autocommands.)

I may exaggerate about ‘dangerous’. It may be more clear is the ‘debug’ purpose. If there are something unexpected, for example significantly slow down performance (and if I can infer it is from an autocmd, I can inspect all the corresponding commands related to a specific event, and it is easier to infer from the command to be executed about what happens rather than merely a <lua function> and show nothing. 

I once have found that my nvim is slow down by 150 ms, and I found that it is a VimEnter autocmd, and I looked at all the autocmd in VimEnter and found the weird one. If the command is only `<lua function>`, debugging to find out the cause is relatively harder.

**Comment by wookayin** [comment]
Not because being dangerous, it makes debugging really hard because what we can only see is `<function XX>`. Shouldn't we have some way to better inspect functions? I think the gist of this issue/request is how can improve the string representation.

**Comment by zeertzjq** [comment]
> improve the string representation

Does Lua allow that?

**Comment by wookayin** [comment]
@zeertzjq `vim.inspect` does not allow overriding its behavior of how things are written (unless neovim core API modifies `vim.inspect`, a little different from [the original one](https://github.com/kikito/inspect.lua)). That being said, `debug.getinfo` can give some additional information about a function object.

For example `debug.getinfo(require"nvim-treesitter".setup)` gives
```
{                                                                                                                                                                                                                      
  currentline = -1,
  func = <function 1>,
  isvararg = false,
  lastlinedefined = 19,
  linedefined = 14,
  namewhat = "",
  nparams = 0,
  nups = 4,
  short_src = ".../.vim/plugged/nvim-treesitter/lua/nvim-treesitter.lua",
  source = "@/home/USERNAME/.vim/plugged/nvim-treesitter/lua/nvim-treesitter.lua",
  what = "Lua"
}
```
I use this function quite often in my debugging toolbox to inspect anonymous functions. So if we use this somewhere in autocmd/keymaps related APIs or even more agreesively in `vim.inspect`, the output of nvim autocommands/keymaps (when callback is a lua function) could be improved.

I am actually going to propose to modify `vim.inspect` in such a way so `vim.inspect(fn)` prints some useful information other than just `<function X>`. Would you prefer doing this in nvim_get_autocmmands API side or in a more global way (say `vim.inspect`)?

**Comment by milanglacier** [comment]
> @zeertzjq `vim.inspect` does not allow overriding its behavior of how function objects will be printed (unless neovim core API modifies `vim.inspect`, a little different from [the original one](https://github.com/kikito/inspect.lua)). That being said, `debug.getinfo` can give some additional information about a function object.
> 
> For example `debug.getinfo(require"nvim-treesitter".setup)` gives
> 
> ```
> {                                                                                                                                                                                                                      
>   currentline = -1,
>   func = <function 1>,
>   isvararg = false,
>   lastlinedefined = 19,
>   linedefined = 14,
>   namewhat = "",
>   nparams = 0,
>   nups = 4,
>   short_src = ".../.vim/plugged/nvim-treesitter/lua/nvim-treesitter.lua",
>   source = "@/home/USERNAME/.vim/plugged/nvim-treesitter/lua/nvim-treesitter.lua",
>   what = "Lua"
> }
> ```
> 
> It also works well with anonymous functions (e.g., it can tell in which file and in which line the function is defined). I use this function quite often in my debugging toolbox to inspect anonymous functions. So if we use this somewhere in autocmd/keymaps related APIs or even more agreesively in `vim.inspect`, the output of nvim autocommands/keymaps (when callback is a lua function) could be improved.
> 
> I am actually going to propose to modify `vim.inspect` in such a way so `vim.inspect(fn)` prints some useful information other than just `<function X>`. Would you prefer doing this in nvim_get_autocmmands API side or in a more global way (say `vim.inspect`)?

I think it would be helpful in a global way. Since vim.keymap.set would be also get benifit from there. And keymap is something get inspected for more frequent than autocmd.

**Comment by clason** [comment]
I think it would be a better idea to do this as part of the autocommand/keymap API: to fill `desc` with your `source` if empty. Since this incurs some overhead, it should probably be gated behind a `verbose` flag.
