### ISSUE TITLE
inoremap not working correctly in foot(wayland) terminal

### ISSUE THREAD

**Issue by shrik3** [neovim/neovim#18164]
### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

no, 8.2.4651

### Operating system/version

Archlinux, 5.15.34-lts

### Terminal name/version

foot 1.11.0

### $TERM environment variable

foot

### Installation

Arch community package (pacman)

### How to reproduce the issue

`nvim --clean`

and set up a mapping:

```
:inoremap ( ()<left>
```

### Expected behavior

upon inserting a left parentheses, it should be replaced by "()".

### Actual behavior

not working.

Actually the imap for symbols that involves a `SHIFT` key don't work at all, e.g. for `?`, `"`, `{`

the others work  e.g.:
```
:inoremap [ []<left>
```

- nvim in `foot` terminal: issue exists
- nvim in other terminal (st): no issue
- vim in both terminal: no issue
- older version of nvim (NVIM v0.6.1): no issue
- nightly build (v0.8.0-dev+9-g1facad234): issue exists

**Comment by clason** [comment]
Please try the latest master of foot.

**Comment by shrik3** [comment]
@clason  Ah that worked.  Thank you!

**Comment by Shinyzenith** [comment]
I'm experiencing similar issues with nvim 0.7.0 on ArtixLinux and foot terminal with vnoremap along with any and all auto bracket closing plugins.

I'm gonna test with foot-git although I should mention that downgrading neovim to 0.6.1 fixed my problems.

**Comment by Shinyzenith** [comment]
> Yes, Neovim 0.7 changed (improved) the modifier handling, exposing bugs in foot that were quickly fixed.

That's really nice to hear ❤️. Building from master fixed my issue.

**Comment by dundargoc** [comment]
Sounds like this has been fixed then. Closing.
