### ISSUE TITLE
nvim_set_hl doesn't redraw screen like `:highlight` command

### ISSUE THREAD

**Issue by rcarriga** [neovim/neovim#18160]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1280-gf2e5f509d Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/cache/aura/vcs/neovim-git/neovim-git/src/build/config -I/var/cache/aura/vcs/neovim-git/neovim-git/src/neovim-git/src -I/usr/include -I/var/cache/aura/vcs/neovim-git/neovim-git/src/build/src/nvim/auto -I/var/cache/aura/vcs/neovim-git/neovim-git/src/build/include Compiled by ronan@XPS15  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

Kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

AUR

### How to reproduce the issue

Run the following code:
```lua
vim.opt.termguicolors = true

local function blend(fg_hex, bg_hex, alpha)
  local segment = 0xFF0000
  local result = 0
  for i = 2, 0, -1 do
    local fg_seg = bit.rshift(bit.band(fg_hex, segment), i * 8)
    local bg_seg = bit.rshift(bit.band(bg_hex, segment), i * 8)
    segment = bit.rshift(segment, 8)

    local blended = alpha * fg_seg + (1 - alpha) * bg_seg
    result = bit.bor(bit.lshift(result, 8), math.floor((math.min(math.max(blended, 0), 255)) + 0.5))
  end

  return result
end

local buf = vim.api.nvim_create_buf(false, true)

vim.cmd("hi FloatBorder guifg=#0000FF")

local ns = vim.api.nvim_create_namespace("test")

vim.api.nvim_buf_set_extmark(buf, ns, 0, 0, { hl_group = "FloatBorder" })

local win = vim.api.nvim_open_win(buf, false, {
  relative = "editor",
  width = 30,
  height = 10,
  row = 0,
  col = vim.opt.columns:get(),
  anchor = "NE",
  style = "minimal",
  border = "single",
})
vim.api.nvim_win_set_option(win, "winhl", "Normal:Normal")

local function run(alpha)
  if alpha <= 0 then
    vim.cmd("hi FloatBorder")
    return
  end
  local new_fg = blend(0x0000FF, 0, alpha)
  vim.api.nvim_set_hl(0, "FloatBorder", { foreground = new_fg })
  -- vim.cmd("hi FloatBorder guifg=#" .. string.format("%06x", new_fg))
  vim.defer_fn(function()
    run(alpha - 0.01)
  end, 30)
end

run(1)
```

### Expected behavior

A floating window opens and the border fades from blue to black.

Comment out the line with `nvim_set_hl` and uncomment the line below to see expected behaviour.

### Actual behavior

A floating window opens and the border remains the same despite the `FloatBorder` group being updated (as can be seen by the printed value at the end).

The border does seem to update if certain actions are taken when not running with `--clean` such as entering insert mode. I believe this is because of some redraws happening due to treesitter but I could be wrong

**Comment by clason** [comment]
`nvim_set_hl` is not the same as `:highlight`, and not meant to be. I

**Comment by rcarriga** [comment]
Yeah that makes total sense, so in this case how do I trigger a redraw when desired? I tried adding `vim.cmd("redraw!")` after the `nvim_set_hl` call but it doesn't update the border. Is there an API function I should use?

**Comment by bfredl** [comment]
Hmm I think `nvim_set_hl` still needs to do the `redraw_later` for global namespace, at least unless we gain some more fine grained control than `redraw!` .

**Comment by clason** [comment]
Yep, `vim.api.nvim_command("redraw")` is what's used in many places; there's also the (internal) function `nvim__buf_redraw_range({buffer}, {first}, {last})`.
