### ISSUE TITLE
Neovim 0.7 crashes with "vim/_init_packages.lua: cannot load incompatible bytecode"

### ISSUE THREAD

**Issue by madis** [neovim/neovim#18169]
### Neovim version (nvim -v)

0.7.0 333ba6569d833e22c0d291547d740d4bbfa3fdab

### Vim (not Nvim) behaves the same?

no

### Operating system/version

20.04.4 LTS (Focal Fossa) x86-64

### Terminal name/version

GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

brew install neovim

### How to reproduce the issue

Start Neovim with factory defaults

```
$ vim --clean
vim/_init_packages.lua: cannot load incompatible bytecode
stack traceback:
	[C]: at 0x004f11c0
	[C]: at 0x7f6e10a60880
E970: Failed to initialize builtin lua modules
```
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio

```

### Expected behavior

Expected Neovim to start (with factory settings)

### Actual behavior

Neovim 0.7 crashes with the following error:

vim/_init_packages.lua: cannot load incompatible bytecode
stack traceback:
	[C]: at 0x004f11c0
	[C]: at 0x7f6e10a60880
E970: Failed to initialize builtin lua modules
```

Googled a bit and these threads / commits may be useful (although didn't help in my case)
  - https://github.com/kartikynwa/void-packages/tree/update-neovim/srcpkgs/LuaJIT/patches
  - https://neovim.discourse.group/t/has-anyone-been-able-to-get-neovim-0-7-0-to-work-on-aarch64/2386/2

After installing neovim from https://github.com/neovim/neovim/releases/tag/v0.7.0 [nvim-linux64.tar.gz](https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.tar.gz), it started normally. So maybe it's more of a homebrew (/linux) issue?

**Comment by clason** [comment]
Cannot reproduce this (at least on macOS). Neovim should _not_ be built against PUC Lua, and certainly not Lua 5.4 (which is incompatible with Lua 5.1, which Neovim targets). Please open an issue at linuxbrew.

(You can try temporarily uninstalling -- or unlinking -- `lua` and then reinstalling `neovim`.)

**Comment by madis** [comment]
Created relevant issue on homebrew repo: https://github.com/Homebrew/homebrew-core/issues/99630

**Comment by clason** [comment]
Tracked upstream.

**Comment by jeffvandyke** [comment]
I'm getting this issue as well on Manjaro (Arch derivative) after a recent update, removing plugins and neovim's local folder doesn't seem to be helping

**Comment by ayman20-py** [comment]
> @jeffvandyke 
You just have to update the arch system
I did that and it worked 
Hope it will fix yours
