### ISSUE TITLE
[bug]osc 52 don't work on version 0.7.0

### ISSUE THREAD

**Issue by yyb196** [neovim/neovim#18168]
### Neovim version (nvim -v)

v0.7.0

### Vim (not Nvim) behaves the same?

neovim only

### Operating system/version

linux

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-256color

### Installation

compile from source

### How to reproduce the issue

ssh to remote linux node, using following config file put at ~/.config/nvim/init.vim

```
if empty(glob('~/.config/nvim/autoload/plug.vim'))
        silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
                                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


call plug#begin('~/.config/nvim/plugged')
" copy to remote machine clipboard
Plug 'ShikChen/osc52.vim'

call plug#end()

augroup osc52
    " 最初にこのグループのautocmd定義を削除する。
    autocmd!
    autocmd TextYankPost * if v:event.operator ==# 'y' | call SendViaOSC52(getreg(v:event.regname)) | endif
augroup END
```

using nvim to edit one file, when I press `yy`, it should copy the whole line to local clipboard.

when I using nvim 0.5.1 it works, After I change to nvim 0.7.0, it don't work.

### Expected behavior

using nvim to edit one file, when I press `yy`, it should copy the whole line to local clipboard.

### Actual behavior

Nothing copy to local machine's clipboard. It works when I use nvim 0.5.1

**Comment by justinmk** [comment]
You are confused. OSC 52 has never had support in Nvim. Tracked in #3344 

Something in the `SendViaOSC52()` plugin may have broken because of an Nvim bug, but _that bug_ needs a minimal repro.
