### ISSUE TITLE
filetype.vim is always sourced in nvim_main() function and can never be opt out of.

### ISSUE THREAD

**Issue by Enayaaa** [neovim/neovim#18171]
### Neovim version (nvim -v)

0.7.0 although same code is present in master

### Vim (not Nvim) behaves the same?

can't check

### Operating system/version

Pop-os 21.10

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

0.7.0 deb package

### How to reproduce the issue

nvim --clean --startuptime startuplog.txt
:e startuplog.txt
/filetype.vim

### Expected behavior

filetype.vim should not be listed in sourced files. Thus the search for filetype.vim should show no results.

sourcing filetype.vim (and a few more files) is as I have understood the same as having `filetype plugin indent on` in your config file. But using the defaults it should not source filetype.vim or there should be a way to opt out of it.

### Actual behavior

Look at the second column (time it took in ms to source the file).
It takes quite a while for filetype.vim to source and I think there should be a way to opt out of it.

I have tried setting `let g:did_load_filetypes = 1` and `let g:do_filetype_lua = 1` in my config but it filetype.vim is sourced either way.
This only effects only if `filetype plugin indent on` exists in your config and in that case doesn't source filetype.vim.

The file is sourced always in nvim_main() function as I have understood.

**Comment by clason** [comment]
> filetype.vim should not be listed in sourced files. Thus the search for filetype.vim should show no results.

This is _not_ the expected behavior: the file is always sourced but the _contents_ are skipped if `g:did_load_filetypes = 1` is set. This is how all such runtime files work.

**Comment by Enayaaa** [comment]
> 

Can I ask why doing: `:filetype` says `filetype detection:ON plugin:ON indent:ON` ?
when even having the above mentioned global variables set in your config?

I would expect those settings to be off by default.

**Comment by clason** [comment]
Because these are different things (commands vs. variables)? And the mentioned "settings" are enabled by default in Neovim(!) since virtually everybody wants that.

**Comment by clason** [comment]
Basically, the filetype detection is split into a part that lives in core (controlled by `:filetype`) and a part that lives in runtime (controlled by `g:did_load_filetypes`). This allows you to override the bundled filetypes but still allow detection of your own (in your `.config/nvim/ftdetect.vim`).
