### ISSUE TITLE
What to do with `long` and `char_u`.

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#1818]
Now that #1812 has gotten rid of `long_u`, it's time to move on and think what to do with `long` and `char_u`. I still have to explore those to estimate feasability, but my initial thoughts on those are:
- `long`: Similarly to `long_u`, `long` would be replaced by a handful of different types:
  * There are many places where assumptions about size are done (`long` considered to be 4 bytes, which is not true anymore). Those would be a candidate for fixed-width types. 
  * At many other places is used for sizes/indexes. `size_t`would be the one here.
  * At other places is used for naturally unsigned values: conversion to some unsigned type would be in order.

  That is probably worth doing anyway. But I would like to know if we are sure `long` would cause problems on Windows. I mean, we know `long`'s size is different there, but does that produce any real problem? Just to know...
- `char_u` : This seems straightforward: Where used for character strings, replace by plain `char`. Where used to access raw memory in an untyped way, we have some options:
  * continue using `char_u`.
  * replace by `unsigned char`.
  * replace by more descriptive typedef. Eg. `byte`.

  In any case, this will be a gigantic task, probably to be done as an extra change when touching code for some other reason.

That's it by now. Opinions?

**Comment by tarruda** [comment]
> That is probably worth doing anyway. But I would like to know if we are sure long would cause problems on Windows. I mean, we know long's size is different there, but does that produce any real problem? Just to know...

If `long` is always 32-bit on windows then it could cause problems, so it might be good to replace it by `int32_t` or `int64_t`.

> char_u : This seems straightforward: Where used for character strings, replace by plain char. Where used to access raw memory in an untyped way, we have some options:

> continue using char_u.
replace by unsigned char.
replace by more descriptive typedef. Eg. byte.
In any case, this will be a gigantic task, probably to be done as an extra change when touching code for some other reason.

Whenever I modify code containing `char_u`, I replace it by `uint8_t`  which is `unsigned char` but less verbose and also consistent with other C99 fixed integer types.

**Comment by elmart** [comment]
> If long is always 32-bit on windows then it could cause problems, so it might be good to replace it by int32_t or int64_t.

In this front, I' ve got a couple of questions:
- Are we supporting 16bit platforms? Cause if not, plain `int` could also be an alternative where only 32bits are needed. This is questionable, however, as though it's standard behaviour for all 32bit platforms, strictly speaking, it's not standard C (would break for 16bit). Fixed-width types are better in this sense, as they would be future-and-past proof at the same time. My only problem with them is having code mixing fixed-width and non-fixed-width types without a clear reason. I would: 1) Use fixed-width types everywhere. Or 2) Use fixed-width types only where strictly necessary. But I'd prefer not an unclear mix of them. I know that can't be done in one shot, so we would have the mix anyway for a long time. But in any case, it's good if we have a conclusion on that / a direction to follow for all future changes.
- Is `long long` already supported on Windows? Just to know.

> Whenever I modify code containing char_u, I replace it by uint8_t which is unsigned char but less verbose and also consistent with other C99 fixed integer types.

Yes, `uint8_t` is a good candidate for that, too.

**Comment by justinmk** [comment]
> Are we supporting 16bit platforms

No.

> Or 2) Use fixed-width types only where strictly necessary

If I recall, we at least resolved to use fixed width for the public api.

**Comment by elmart** [comment]
> If I recall, we at least resolved to use fixed width for the public api.

I'm considering that case one of "where strictly necessary".

**Comment by elmart** [comment]
In any case, now that we have windows compiling, we can start to check for real problems with windows' long variables. 

I would suggest doing first a one-shot replacement of all longs with long longs. 
That would change nothing for 32bit platforms, as well as for 64bit platforms other than Windows. 
And, for Windows64, it would "fix" the problem with longs. 
Long long is a bit ugly, I know. But it's exactly what we want. 
As I said, that can be easily done as a big, one-shot change. 
Then, in future, we can little by little refactor some of those to more appropriate types (eg. To unsigned type when used for sizes and the like). 
What do you think?

**Comment by justinmk** [comment]
> I would suggest doing first a one-shot replacement of all longs with long longs. 
> That would change nothing for 32bit platforms, as well as for 64bit platforms other than Windows. 
> And, for Windows64, it would "fix" the problem with longs.

After doing some reading (again), yes, that sounds very reasonable.

**Comment by Pyrohh** [comment]
When you say long long do you mean int64_t? I saw #574, so am confused as to why int64_t isn't being used instead.

**Comment by elmart** [comment]
> When you say long long do you mean int64_t?

No, I mean `long long`. That will be 32 bits on every 32bits platform and 64bits on every 64bits platform. 
`int64_t`, on the other hand, would always be 64bits, even on 32bits platform. That can be very poorly performant, as simulating 64bit operations when only 32bits native types/operations are available is expensive.

In the general case (where exact width is not really needed), what we want is "the longest integer type that is a native type". `intmax_t` is near to that, too, but is not perfect because, in theory (while not in practice) could include "extended" types beyond native types, like `__int128_t`. And that is what `long long` exactly offers. The only pity is that weird, verbose name. But it's a fact of modern C. We gain nothing to ignore it.

**Comment by Pyrohh** [comment]
If the primary reason is performance, then why not use `int_fast32_t`? I don't see it in the style guide, so I assume it's an MSVC issue.

**Comment by elmart** [comment]
I haven't said the primary reason is performance. 
I've said we want the longest integer native type, in the general case where no reasons to impose a particular size exists.
I only talked about performance to discard `int64_t` in that case, because that would be slow on 32bits platforms.
Why would you prefer fixed-size types there?

**Comment by Pyrohh** [comment]
> I haven't said the primary reason is performance.
> I've said we want the longest integer native type, in the general case where no reasons to impose a particular size exists.
> I only talked about performance to discard int64_t in that case, because that would be slow on 32bits platforms.
> Why would you prefer fixed-size types there?

I wouldn't anymore, as you have explained the performance issues that would create. 

(from the post before that)
> So, it's only long long that exactly offers what we want here. The only pity is that weird, verbose name. But it's a fact of modern C. We gain nothing to ignore it.

Assuming our supported platforms have sane implementations of it, wouldn't the memory usage of `(u)int_fast32_t` mirror that of `long long`? Anyways, I don't want to over-complicate things so this probably doesn't matter much.

**Comment by elmart** [comment]
> Assuming our supported platforms have sane implementations of it

AFAIK, the only doubt was windows, and it seems `long long` is already supported in recent versions of MSVC. If that's not the case, please warn.

> wouldn't the memory usage of (u)int_fast32_t mirror that of long long?

That only guarantees 32 bits. I mean, AFAIK, you could have a 64bits platform for which `int_fast32_t` maps to just `int` (32 bits). That's not what we want. We want 64bits on 64bits platforms.

Note that all my discourse is based on the assumption that we want 32 bits on every 32bits platform, and 64 bits on every 64bits platform. Because we want not to impose arbitrary limits on value range. But we want it in a native type (to be sure it's fast, though could be not the fastest). If you agree to this assumption, then I think exposed reasons are sound. If you question this assumption, then that's another debate. ;-)

> Anyways, I don't want to over-complicate things so this probably doesn't matter much.

Don't worry. I like discussing these things, and to be proven I'm wrong if I am. It's the only way to learn.
Also, this is admittedly not a terribly important thing. But I think it's in the spirit of neovim to care about details so that, given enough time, we can transform this horrible codebase into the opposite (a great C codebase that sets a quality standard). I just hope that ambition is not too unrealistic. ;-)

**Comment by Pyrohh** [comment]
> That only guarantees 32 bits. I mean, AFAIK, you could have a 64bits platform for which int_fast32_t maps to just int (32 bits)

Yes, I think _could_ is the keyword here. I just compiled using `musl-gcc` and `int_fast32_t` was 4 bytes, while glibc yields 8. We should probably just stick to non-implementation defined types, as C99 mandates that what the implementer considers "fast" can be completely arbitrary.

> Note that all my discourse is based on the assumption that we want 32 bits on every 32bits platform, and 64 bits on every 64bits platform. Because we want not to impose arbitrary limits on value range. But we want it in a native type (to be sure it's fast, though could be not the fastest).

I see, that makes sense.

> Don't worry. I like discussing these things, and to be proven I'm wrong if I am. It's the only way to learn.

Thanks for understanding.

> Also, this is admittedly not a terribly important thing. But I think it's in the spirit of neovim to care about details so that, given enough time, we can transform this horrible codebase into the opposite (a great C codebase that sets a quality standard). I just hope that ambition is not too unrealistic. ;-)

Hopefully it won't take as long as Nvi :)

**Comment by elmart** [comment]
All my reasoning above sits on the assumption that `long long` has 32 bits on 32bits platforms.
I thought that was in fact the case, because at many places in the net it's stated that the only guarantees about `long long` are to have size equal or greater to `long`, and to be a native type. 
But I'm finding contradictory information on other places, where it's said that `long long` is guaranteed by C99 to be at least 64 bits, even on 32bits machines.
If that's true, then my reasoning doesn't hold.
It's really frustrating that such basic things are so ill-defined in C.

Ok, we should then:
1) use `intmax_t`. There's a small drawback with this, because *in theory* it could be an extended type (e.g. __int128_t). This is, AFAIK, it's not guaranteed to be a native type, and so performance could suffer.
2) use a typedef to `int32_t` or `int64_t` depending on the platform. This is the safest thing, but would defeat our purpose not to use typedefs.

Comments?

**Comment by justinmk** [comment]
> long long is guaranteed by C99 to be at least 64 bits

You are right. http://stackoverflow.com/a/2143178/152142

> use intmax_t. There's a small drawback with this, because in theory it could be an extended type (e.g. __int128_t). This is, AFAIK, it's not guaranteed to be a native type, and so performance could suffer. 

If performance could suffer on our primary platforms (32/64 unix, 64 Windows), then let performance regress on 32-bit Windows.

> 2) use a typedef to int32_t or int64_t depending on the platform. This is the safest thing, but would defeat our purpose not to use typedefs.

If this is only to support a feared performance regression on *32-bit* Windows, I think we should choose to let 32-bit Windows have a slight performance regression and continue with our refactoring ideals.

**Comment by elmart** [comment]
The potential problem I'm talking about is not for Win32 only. If confirmed, It could happen *in theory* for any platform (unix/non-unix, 32/64 bits).

Problem is:
- A given platform can define non-standard, implementation-defined extended integer types. For example, gcc defines `__int128_t` on 64bits unixes. This could also happen for a 32bit platform defining a `__int64_t` type, though I don't know about one doing so.
- Now, it's not clear (again) what the standard mandates regarding this extended types and the definition of `intmax_t`.
  * It seems most people agree that the spirit of the standard implies that `intmax_t` should take those extended types into account (thus defining `intmax_t` to be `__int128_t` in the mentioned example).
  * Other people clearly state, though, that such thing can't be done, as that would create problems (breaking ABI contracts and stdlib implementations). This people affirms `intmax_t` should not map to an extended type. In other words, they say `intmax_t` should always be 64 bits on a 64bits platform (same for 32 bits).

I have to check what our target platforms are really doing, but I have the impression that most of them follow the second alternative, even if the correct interpretation for the standard is considered to be the first one. So, not sure what to do. I would like to use `intmax_t`, and it seems it would work by now. But if we really want to make this future-proof, then we should reach a clearer conclusion.

I need some more time to investigate. If someone has a clear understanding of this, please chime in.

Some links I've read, that have contributed to my current confusion: 
http://stackoverflow.com/questions/21265462/why-in-g-stdintmax-t-is-not-a-int128-t
http://www.cplusplus.com/reference/cstdint/
http://www.thecodingforums.com/threads/actual-type-of-intmax_t-and-uintmax_t.556547/
https://gcc.gnu.org/ml/gcc/2010-09/msg00277.html
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=49595

P.D. I often think what the hell committees are useful for...

**Comment by justinmk** [comment]
>  If confirmed, It could happen in theory for any platform (unix/non-unix, 32/64 bits).

I was referring to the `long long` problem. So the question of `intmax_t` would be avoided.

**Comment by elmart** [comment]
Well, the `long long` problem (always being at least 64bits) would affect *all* 32bits platforms, not only Win32.

**Comment by justinmk** [comment]
Isn't `ptrdiff_t` a good fit for the requirements you mention above? It is 32 bit on 32 bit platforms, and 64 on others, and it is signed.

**Comment by elmart** [comment]
In practice, `ptrdiff_t` would behave as you mention.

But, being rigorous, it's not perfect either. In segmented architectures, where a, say, 32bits address is made of a 16bit segment and a 16bit offset, `ptrdiff_t` would be 16bits. This is, it's only guaranteed to hold pointer differences *in the same segment*.  It's not guaranteed to be the machine pointer size.

As I said, that wouldn't matter today for our target platforms. But there's a more important drawback: its name. While it can be natural using `intmax_t`, or `long long` for a general purpose integer with no particular size requirements, using `ptrdiff_t` is kind of a stretch. That name doesn't come naturally at all.

So, before using something that isn't perfect in theory either, and also has a horrible name, then I'd use one of the other options.

**Comment by ZyX-I** [comment]
@elmart In the case you are describing `ptrdiff_t` has to be 17 bits, not 16. It needs one bit to hold sign. Note: I do not think it fits in.

> That only guarantees 32 bits. I mean, AFAIK, you could have a 64bits platform for which int_fast32_t maps to just int (32 bits). That's not what we want. We want 64bits on 64bits platforms.

I do not see why you *not* want to have 32 bits there if there are no particular size constraints. If you are fine with 32 bits on some platforms then just let the compiler decide. If there *are* size constraints that make you want 64 bits on 64 bit platform and 32 bits on 32 bit platform then add `#define` to config.h that will use either `int_fast32_t` or `int_fast64_t`. Name can be something like `natint_t`.

---

About `char_u`: I use either just `char` or in some rather rare cases `uint8_t` if I need to make it unsigned (theoretically `int8_t` if I ever needed a signed character, but I never do).

**Comment by elmart** [comment]
> I do not see why you not want to have 32 bits there if there are no particular size constraints.

Well, when I say  "a type with no particular size contraints", I mean I don't want to impose arbitrary limits on values. This is, I want it as big as possible, but native. I expressed it in a post above:

> Note that all my discourse is based on the assumption that we want 32 bits on every 32bits platform, and 64 bits on every 64bits platform. Because we want not to impose arbitrary limits on value range. But we want it in a native type (to be sure it's fast, though could be not the fastest).

In other words, I just want the "natural" word size on every platform. That sounds like a reasonable thing to ask for, IMO. It's kind of puzzling such a simple requirement is so difficult/impossible to express using only standard types.

**Comment by ZyX-I** [comment]
> In other words, I just want the "natural" word size on every platform. That sounds like a reasonable thing to ask for, IMO. It's kind of puzzling such a simple requirement is so difficult/impossible to express using only standard types.

I see no sense in this request. If compiler authors know that under some circumstances 32-bit integer will be the fastest and you do not have size constraints which make you *require* 64-bit then there is no reason to want 64 bit. 32 and 64 bits in any case are arbitrary limits for an integer that has nothing to do with registers or pointers.

If you have any reasons to want 64-bit integers *other* then it being “natural size” please express them. It is not a reasonable thing to ask for something without a reason. It is still strange that I do not know register-sized standard integer type though.

**Comment by elmart** [comment]
I have stated my reasons: Not wanting to impose arbitrary range limits, I want it as big as possible. This is, I prioritize value range over speed. But not to the point to use extended types. I want it as big as possible, but native (register size). I think that's perfectly reasonable.

**Comment by ZyX-I** [comment]
I completely do not see why do you want “as big as possible”. This is no reason. You are in any case putting arbitrary range limits by not using big integers. Request for something being “register sized” may only originate from the speed or convenience of processing and `int_fast32_t` should be fine for this case.

If 32-bit systems are supported and some value is register sized and it is stated that some type is only guaranteed to be 32-bit then any sane NeoVim developer will assume that it has only 32 bits on *any* system, which is just as good as using fixed-size 32-bit integers instead of register-sized I-do-not-know-how-many-bits integers.

**Comment by hotgloupi** [comment]
Why not define a set of general purpose semantic size and index types ?
It makes the intent of variables clearer and let always the possibility to
change the actual type used.

For every small set of things, I would use a plain 'int', and a specific
type for buffer size/index, file size/position, etc.
In other words, for every indexable type (file, buffer, array, memory) I
would associate the index type, with a meaningful typedef.

The underlying type question can be solved later (or tuned) when coverity
or asan start yelling :)

On Sunday, February 15, 2015, Nikolai Aleksandrovich Pavlov <
notifications@github.com> wrote:

> I completely do not see why do you want “as big as possible”. This is no
> reason. You are in any case putting arbitrary range limits by not using big
> integers. Request for something being “register sized” may only originate
> from the speed or convenience of processing and int_fast32_t should be
> fine for this case.
>
> If 32-bit systems are supported and some value is register sized and it is
> stated that some type is only guaranteed to be 32-bit then any sane NeoVim
> developer will assume that it has only 32 bits on *any* system, which is
> just as good as using fixed-size 32-bit integers instead of register-sized
> I-do-not-know-how-many-bits integers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neovim/neovim/issues/1818#issuecomment-74397089>.
>


-- 
Raphaël Londeix
http://hotgloupi.fr

**Comment by ZyX-I** [comment]
@hotgloupi What is the difference between buffer, array and memory? Usually a “buffer” is an array used for specific purpose and I can’t say whath “memory” in this context means.

It may also appear that file index does not fit into the largest integer on some filesystem: e.g. [this FS](http://en.wikipedia.org/wiki/Unix_File_System) is said to allow files 2<sup>73</sup> bytes large. NeoVim cannot handle such files though.

**Comment by elmart** [comment]
@hotgloupi 
> Why not define a set of general purpose semantic size and index types ?

A decision was made long time ago against using project-defined integer types. In fact, a lot of work has been done to remove existing types of that kind. Only `char_u` remains by now.

@ZyX-I 
> I completely do not see why do you want “as big as possible”. This is no reason.

I don't understand what is it that you don't understand.
As I've said several times, I'm here looking for a type to be used with general-purpose integer variables. By general-purpose I mean there's no natural limit for values of such type. They could have any value. Of course, there must be a limit, as everything is finite within a computer. But it seems the most natural thing trying to push that limit as far as possible. I don't think that needs any other justification.

> You are in any case putting arbitrary range limits by not using big integers.

That's not arbitrary. I'm saying I want to push the value-range limit **as far as it doesn't hurt performance significatively**. Thus the requirement not to use extended types. That is a reasonable tradeoff between representable range and speed, IMO.

> Request for something being “register sized” may only originate from the speed or convenience of processing

I just don't agree. Reasons exposed above (as big as possible while not hurting performance) do in fact lead to asking for register-size, IMO.

> If 32-bit systems are supported and some value is register sized and it is stated that some type is only guaranteed to be 32-bit then any sane NeoVim developer will assume that it has only 32 bits on any system, which is just as good as using fixed-size 32-bit integers instead of register-sized I-do-not-know-how-many-bits integers.

As I'm sure you know, it's a pretty common thing in C dealing with types you don't know the exact size for (if you want to best adapt to each platform). Repeating myself, I want a type that will give me the maximum representable range in each platform, without using extended types not to hurt performance. That leads to non-fixed-width types. Using fixed-with types everywhere is another portability approach, but that has already been discussed and most people don't like it (I wouldn't dislike it, btw).


In any case: even if you don't agree with the desired characteristics for the type I've described, I would like to know if such a type exists. This is, please answer to this question:
¿Do you know of an standard type that would give you register-size integers on every platform?
Then we can continue discussing why such a thing would / would not be desirable.

**Comment by ZyX-I** [comment]
> like to know if such a type exists. This is, please answer to this question:
> ¿Do you know of a standard type that would give you register-size integers on every platform?
> Then we can continue discussing why such a thing would / would not be desirable.

I already said:

> It is still strange that I do not know register-sized standard integer type though.

I there a language where such a thing exists? I know only of three “system” languages (C, C++, Rust) and I know of no register-sized types in any of them (Rust even does not have `size_t` in documentation (`isize` and `usize` [are defined](http://doc.rust-lang.org/reference.html#machine-dependent-integer-types) as equivalents to `intptr_t` and `uintptr_t`)), not even Windows-specific ones (in https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx browser fails to find word `register`).

There should be something in some assembler. But I do not know any.

**Comment by philix** [comment]
Using a register-size type would be less portable. If it's OK for your integer type to be 32 bits wide on a 32 bits machine it should also be 32 bits on a 64 machine.

Types like `size_t` are an exception because they are used to represent offset/pointers in memory which is dependent on register size.
