### ISSUE TITLE
nvim_buf_get_name() inconsistent with bufname()

### ISSUE THREAD

**Issue by Supreeeme** [neovim/neovim#18183]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+15-g245858460

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

Konsole 21.12.13

### $TERM environment variable

xterm-256color

### Installation

AUR

### How to reproduce the issue

nvim --clean
:file test
:lua print(vim.api.nvim_buf_get_name(0)) 
:echo bufname()

### Expected behavior

nvim_buf_get_name(0) and bufname() should produce the same output

### Actual behavior

nvim_buf_get_name(0) appends the home directory to the buffer name. Happens even on non-file buffers (i.e. terminal)

**Comment by fsouza** [comment]
@Supreeeme I'm not a maintainer, but the documentation of nvim_buf_get_name explicitly states that it returns the full path of the "file", which may not necessarily match the name of the buffer (which I agree is confusing given the name of the function, but not sure if it's considered a bug).

**Comment by Supreeeme** [comment]
Hmm, so it does...
It still seems a little weird to me that buffers that are not associated with files (terminal buffers, nvim-tree buffers, etc) still get the home directory prepended to their names.

**Comment by zeertzjq** [comment]
I don't think it is possible to tell if a buffer is associated a file or not if it has a name like `NvimTree_1`. This is also `expand('%:p')`'s behavior.

**Comment by muniter** [comment]
> I don't think it is possible to tell if a buffer is associated a file or not if it has a name like `NvimTree_1`. This is also `expand('%:p')`'s behavior.

There's the option `buftype=nofile` but it's not 100% accurate since. One may have an `acwrite` buffer that is also not a file.

**Comment by zeertzjq** [comment]
I meant `b_p_bt` doesn't affect `b_ffname`.

**Comment by Supreeeme** [comment]
> This is also expand('%:p')'s behavior.

I didn't realize this! I guess this isn't really an issue then since I was really just looking for the name that `expand('%:p')` gives, and I can just strip the preceding slashes from the `nvim_buf_get_name()` output. I think a note in the docs that it will return a full path for "non-file" buffers would be helpful though.
