### ISSUE TITLE
allow use of bsdtar instead of unzip

### ISSUE THREAD

**Issue by HalosGhost** [neovim/neovim#1819]
``vim``-proper offers an incredibly helpful bit of functionality: the ability to view the contents of compressed files and archives with ``unzip``. When doing so, it acts almost the same as if you ran ``vim`` on a directory, it gives you the file list and you can choose one of the files to edit, etc.

However, ``unzip`` only supports a few different kinds of archives. An alternative tool, ``bsdtar`` uses libarchive as a backend and resultingly supports a huge variety of archive types (including many, if not all, of the types supported by ``unzip``). Is there any possibility to allow ``neovim`` to also check for ``bsdtar``, and if present, use it instead of ``unzip``?

**Comment by justinmk** [comment]
AFAIK this is a netrw feature. I think doing anything to prolong the life of netrw is a terrible idea, but if there's something we can do to facilitate un-archiving plugins such that the results are navigable by file browser plugins, we should consider it. Don't know of anything specific yet, though.

**Comment by HalosGhost** [comment]
I have no idea where in ``vim``'s code this bit of functionality lies; I would go check, but thar be dargons in that code. I just know that I enjoy the ability to browse archives in ``vim`` and that I've long wished to be able to uninstall ``unzip`` and use ``bsdtar`` for it instead (since I already use ``bsdtar`` for other things).

**Comment by chrisbra** [comment]
On Do, 15 Jan 2015, Sam Stuewe wrote:

> I have no idea where in ``vim``'s code this bit of functionality lies; I would go check, but thar be dargons in that code. I just know that I enjoy the ability to browse archives in ``vim`` and that I've long wished to be able to uninstall ``unzip`` and use ``bsdtar`` for it instead (since I already use ``bsdtar`` for other things).

That is done by the zip.vim plugin which is distributed together with 
vim. The help (:h zip) event documents how to use a different unzip file 
and handle additional extensions...

Best,
Christian
-- 
Echte dauernde Freude ist nur die Tochter der Weisheit.
		-- J. K. Lavater

**Comment by HalosGhost** [comment]
Ahh! I had no idea that ability already existed. Thank you for pointing this out, and sorry for the noise.
