### ISSUE TITLE
Neovim :Tutor misalignment

### ISSUE THREAD

**Issue by dtomvan** [neovim/neovim#18190]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1455-g4503cb6b6 Build type: Release LuaJIT 2.1.0-beta3 Compiled by tomvd

### Vim (not Nvim) behaves the same?

This issue is neovim specific, as the tutor file only exists on neovim

### Operating system/version

Arch Linux 5.17.3-arch1-1

### Terminal name/version

alacritty 0.10.1 (2844606d)

### $TERM environment variable

alacritty

### Installation

Build from repo on 15 Apr 12:22

### How to reproduce the issue

nvim --clean
:Tutor
:42<cr> // Scroll to lesson 1.1
z<cr>

### Expected behavior

Image of what I would imagine the HJKL explanation arrow to look like:
![image](https://user-images.githubusercontent.com/51440893/164269004-3baa9928-5bec-4151-8d79-b10af0cb0fc1.png)

### Actual behavior

Notice the k not being directly above the j
![image](https://user-images.githubusercontent.com/51440893/164269334-92a94c42-538b-4cb1-bb28-5631eac5b57a.png)

You can see the misalignment on GitHub too: https://github.com/neovim/neovim/blob/6b0d3ae6a83cb0410c16532a367ed8ad9bd093a8/runtime/tutor/en/vim-01-beginner.tutor#L46

**Comment by clason** [comment]
This was deliberate: https://github.com/neovim/neovim/pull/17092/files#r794400778
