### ISSUE TITLE
Paredit and Sexp broken since v0.7.0

### ISSUE THREAD

**Issue by hemantgouni** [neovim/neovim#18198]
### Neovim version (nvim -v)

`>= 0.7.0`

### Vim (not Nvim) behaves the same?

Not tested yet

### Operating system/version

NixOS unstable

### Terminal name/version

foot 1.11.0 +pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Installation

nixpkgs

### How to reproduce the issue

1. Install Neovim v0.6.1 and one of slimv (which comes with paredit.vim) or vim-sexp
2. Start nvim
3. Type an opening parenthesis. It should be closed automatically
4. Install Neovim v0.7.0 and one of slimv or vim-sexp
5. Start nvim
6. Type an opening parenthesis
7. Observe that the parenthesis is not closed automatically

### Expected behavior

These plugins should work for structurally editing lisp code; it appears that they are broken for some reason on nvim versions >= v0.7.0 (I also tested this against the latest commit to master).

### Actual behavior

vim-sexp and slimv do not work, and likely many others like them.

**Comment by zeertzjq** [comment]
Seems like a bug of foot that has recently been fixed.

**Comment by hemantgouni** [comment]
Oh, that'd be great! Do you have an issue I can look at?

**Comment by hemantgouni** [comment]
Ah, found #18164. I'll try building foot from master.

**Comment by hemantgouni** [comment]
That fixes it; thanks!.

**Comment by hemantgouni** [comment]
@zeertzjq It may be worth mentioning this in #14090; I wasn't able to find it there originally (though I don't know if this counts as a breaking change, since it's not nvim's fault).
