### ISSUE TITLE
OSC-8 Support

### ISSUE THREAD

**Issue by timsofteng** [neovim/neovim#18195]
### Feature already in Vim?

No

### Feature description

I've faced up with issue which I describe here:
https://codeberg.org/dnkl/foot/issues/1031

So to parse url from neovim with terminal emulator neovim should support OSC-8 feature.

Is it possible to implement it somehow?

**Comment by gpanders** [comment]
This is a work in progress https://github.com/neovim/neovim/pull/18130.

Duplicate of https://github.com/neovim/neovim/issues/11871.

**Comment by gpanders** [comment]
Duplicate of #11871.

**Comment by gpanders** [comment]
Duplicate of #11871

**Comment by timsofteng** [comment]
Got it 
Thanks
