### ISSUE TITLE
Update `vim.inspect` to latest upstream version

### ISSUE THREAD

**Issue by clason** [neovim/neovim#18207]
Neovim bundles a version of https://github.com/kikito/inspect.lua as `vim.inspect`, forked from version 3.1.2.<sup>1</sup> Upstream has since updated to 3.1.3 with some performance improvements, which would be good to include in our version.

This needs a manual merge since

1. Neovim has made local changes (474d0bcbf724c7eed740f60391a0ed35d651e1d3 and ea4127e9a7a624484f51c21e17f37c766da15da0)
2. Upstream has rewritten the module in Teal, so the generated file lacks formatting and documentation, which should be kept in our version.

(Should also take the opportunity to mention `inspect.lua` in https://github.com/neovim/neovim/blob/master/MAINTAIN.md#third-party-dependencies.)

---
<sup>1</sup>even though the license headers apparently haven't been updated since version 3.1.0

**Comment by kessejones** [comment]
Can I work on this?

**Comment by clason** [comment]
I already started :) But I'm hitting a wall, so how about I open a draft PR and you can take it from there?
