### ISSUE TITLE
Documentation of patterns in vim.filetype.add() is poor

### ISSUE THREAD

**Issue by andrewferrier** [neovim/neovim#18204]
### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

No, feature only in NeoVim

### Operating system/version

macOS 12.1

### Terminal name/version

Kitty

### $TERM environment variable

xterm-kitty

### Installation

Homebrew

### How to reproduce the issue

`:help vim.filetype.add()`

### Expected behavior

The help for `vim.filetype.add()` doesn't really explain what a "pattern" is (for the third section of the object supplied). By examination of the examples, and the `lua/vim/filetype.lua` file, I eventually figured out that these are regexs, with the `%` character used as an escape character for what comes after. However, the help file doesn't link to any explanation on what these 'patterns' are or the syntax (and I don't recognize them from elsewhere in Vim/NeoVim). Maybe a simple hyperlink is all is needed?

Thanks for all the hard work on NeoVim, it's getting better and better! I love this new filetype detection, shaved another 10ms off startup!

### Actual behavior

More detailed docs on patterns.

**Comment by clason** [comment]
Those are standard Lua patterns (not regular expressions!), see https://www.lua.org/manual/5.1/manual.html#5.4.1

We could add a link to that somewhere in the documentation -- I'll have to think where best to put it.

**Comment by andrewferrier** [comment]
Looks good, thanks for the fix.
