### ISSUE TITLE
[FEATURE] expose Lua API equivalent of `:colorscheme`

### ISSUE THREAD

**Issue by jokeyrhyme** [neovim/neovim#18201]
### Feature description

Howdie, thanks for sharing this project, it's just terrific!

I'm slowly working on removing `vim.cmd()` calls from my configuration in favour of Lua API calls, and I don't believe there's a working equivalent of `:colorscheme`, so my last bit of VimScript is (e.g.) `vim.cmd([[ colorscheme rose-pine ]])`

For the Lua-obsessed neovim user, it would be awesome if there could be a Lua API for this

There's a mention of such a thing here ( https://github.com/neovim/neovim/issues/3809#issuecomment-162952019 ) requiring more hooks, but that was 7 years ago, and I'm wondering if this matter is more feasible these days?

Anyhow, thanks! <3

**Comment by clason** [comment]
`:colorscheme foo` does essentially three things:

1. trigger the `ColorSchemePre` event
2. `runtime colors/foo.vim` (or `.lua`)
3. trigger the `ColorScheme` event

With the new Lua autocommand API, this would be fairly trivial to replicate, so the priority is fairly low.

**Comment by justinmk** [comment]
Duplicating Vim's random commands in Lua achieves nothing, except a lot of useless, manually-written code. 

We are working on a generalized interface to call Vim commands: https://github.com/neovim/neovim/issues/14966

**Comment by glanham-jr** [comment]
For anyone wondering what the generalized interface and how to use it, its the [`nvim_cmd`](https://neovim.io/doc/user/api.html#nvim_cmd()) function (which I find easiest) with its relative [`nvim_parse_cmd`](https://neovim.io/doc/user/api.html#nvim_parse_cmd()) function. See the below example on how to use this for setting the color scheme.

```lua
vim.api.nvim_cmd({
  cmd = 'colorscheme',
  args = {'myfavoritecolorscheme'}
}, {})
```
