### ISSUE TITLE
Really confusing unpacking behavior at Lua function invocation

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#18213]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12

### Terminal name/version

iTerm2

### $TERM environment variable

N/A

### Installation

brew

### How to reproduce the issue

(Using https://github.com/bfredl/nvim-luadev)

```
15> function foo()
...   return 1, 2
... end

16> function bar(x, y)
...   print(x)
...   print(y)
... end
... bar(foo())
1
2

17> function baz(x, y, z)
...   print(x)
...   print(y)
...   print(z)
... end
... baz(foo(), 3)
1
3
nil

18> baz(3, foo())
3
1
2

19> baz(3, 4, foo())
3
4
1

20> baz(3, 4, 5, foo())
3
4
5

21> baz(3, 4, 5, 6, foo())
3
4
5

22> baz(foo(), foo())
1
1
2

```

### Expected behavior

I would expect the two return values of `foo()` to either always unpack to two function arguments, or to never unpack at all, or _maybe_ to just always unpack to a single function argument which is either the first return value or a table of the return values.

### Actual behavior

Seems like `foo()` unpacks to a single logical argument if it is anything but the last lexical argument, and unpacks fully if it is the last lexical argument.

I understand this is in the Lua runtime, but is this documented somewhere or something?

**Comment by b0o** [comment]
> Lua always adjusts the number of results from a function to the circumstances of the call. When we call a function as a statement, Lua discards all of its results. When we use a call as an expression, Lua keeps only the first result. We get all results only when the call is the last (or the only) expression in a list of expressions. These lists appear in four constructions in Lua: multiple assignment, arguments to function calls, table constructors, and return statements.

&mdash; https://www.lua.org/pil/5.1.html

**Comment by andmis** [comment]
TYVM.
