### ISSUE TITLE
callback function with not required parameter in nvim_create_autocmd 

### ISSUE THREAD

**Issue by monkoose** [neovim/neovim#18218]
I have found some similar issues with callbacks, but none of them behaves like this issue (or maybe I have missed one).

### Neovim version (nvim -v)

NVIM v0.7.0 Build type: Release

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

pacman -S neovim

### How to reproduce the issue

Open this `min.lua` below as vimrc and try to few `hjkl`.
- nvim --clean -u min.lua min.lua

```lua
-- min.lua
local function wtf(maybe_nil)
    if maybe_nil then
        vim.api.nvim_echo({{vim.inspect(maybe_nil)}}, true, {})
    end
end

local au = vim.api.nvim_create_augroup('wtf', {})
vim.api.nvim_create_autocmd('CursorMoved', {
    group = au,
    callback = wtf,
})
```

### Expected behavior

callback shouldn't print anything and first argument of it shouldn't be polluted with some internal table

### Actual behavior

Tables like this prints into echo area
```
{
  buf = 1,
  event = "CursorMoved",
  file = "/home/monkoose/Downloads/ff.lua",
  group = 24,
  id = 24,
  match = "/home/monkoose/Downloads/ff.lua"
}
```

**Comment by bfredl** [comment]
What is the issue. if you don't want to print something. just remove the print statement.

**Comment by clason** [comment]
Please read the documentation: callbacks take a mandatory argument, which is _not_ `maybe_nil`. If you need to call an existing function, wrap it in `function() ... end`.

**Comment by monkoose** [comment]
It's not actual code. It for representation of the issue.

**Comment by bfredl** [comment]
There is no issue as it is expected and documented behaviour.

**Comment by clason** [comment]
From `:h nvim_create_autocmd()`:

>                              • callback (function|string) optional: if a
>                                string, the name of a Vimscript function to
>                                call when this autocommand is triggered.
>                                Otherwise, a Lua function which is called when
>                                this autocommand is triggered. Cannot be used
>                                with {command}. **Lua callbacks** can return true
>                                to delete the autocommand; in addition, they
>                                **accept a single table argument with the
>                                following keys**:
>                                • id: (number) the autocommand id
>                                • event: (string) the name of the event that
>                                  triggered the autocommand |autocmd-events|
>                                • group: (number|nil) the autocommand group id,
>                                  if it exists
>                                • match: (string) the expanded value of
>                                  |<amatch>|
>                                • buf: (number) the expanded value of |<abuf>|
>                                • file: (string) the expanded value of
>                                  |<afile>|
>
