### ISSUE TITLE
Netrw takes wrong filename

### ISSUE THREAD

**Issue by carlosecp** [neovim/neovim#18224]
### Neovim version (nvim -v)

v0.7.0-dev

### Vim (not Nvim) behaves the same?

yes, vim 8.2.4651

### Operating system/version

EndeavourOS Linux x86_64

### Terminal name/version

kitty 0.25.0

### $TERM environment variable

xterm-kitty

### Installation

aur

### How to reproduce the issue

`nvim --clean`
`:lua vim.g.netrw_liststyle=1`
`:Explore`

Locate a file with a long filename. So long that it colides with the first column of the fileinfo columns set by `vim.g.netrw_liststyle=1`. For example:

![image](https://user-images.githubusercontent.com/47466248/164777007-c2b308bb-2b06-43b3-b2d2-1708c8f87ba7.png)

Hit `Enter` to open to edit the file.

### Expected behavior

When hitting `Enter` the correct file should be openened for editing. In the case of the provided example, if the cursor is positioned over the file named `1_resolucion_de_problemas_con_objetos.md`, this file should be opened for editing.

### Actual behavior

The file information added by the `vim.g.netrw_liststyle=1` option gets appended to the actual filename.
![image](https://user-images.githubusercontent.com/47466248/164778077-ecbd8ea2-1b21-47dc-b55c-d9fc5c827fdf.png)

The message shown in the message area is the return value of `:echo expand('%')`.

The correct file is not opened. This is also an issue in regular Vim, so I don't know if this is the right place to report it.

**Comment by zeertzjq** [comment]
netrw bugs should be reported to Vim, or to netrw's maintainer.

**Comment by chrisbra** [comment]
isn't that the same: https://github.com/vim/vim/issues/10055
