### ISSUE TITLE
WinScrolled not fired with float window that not focused

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#18222]
### Neovim version (nvim -v)

NVIM v0.7.0 release

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MacOS 12.1

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

repo

### How to reproduce the issue

Create minimal vimrc:

``` vim
set mouse=a
function! ShowFloat() abort
  let s:buf = nvim_create_buf(1,1)
  call nvim_buf_set_lines(s:buf, 0, -1, v:false, ['a', 'b', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n'])
  let s:win = nvim_open_win(s:buf, v:false, {
    \ 'height':5,
    \ 'width': 10,
    \ 'col': 0,
    \ 'row': 1,
    \ 'relative': 'editor',
    \ 'style': 'minimal'
    \})
endfunction

call ShowFloat()

autocmd WinScrolled * let g:w = expand('<amatch>')
```

Source the vimrc and scroll the float window by mouse.

### Expected behavior

Fire `WinScrolled` event with float window

### Actual behavior

No `WinScrolled` event is fired when scroll the window by mouse, unless the float window is focused.
Tried scroll the float window with `winrestview()` function, no event fired as well.

**Comment by zeertzjq** [comment]
These are many way to scroll non-current window, so this will be a bit hard to deal with. Vim patches can make scrolling with mouse trigger `WinScrolled`, but other cases need more work. Also I wonder if fixing this may break plugins that depend on `WinScrolled` fired only for current window, since it used to be the documented behavior.

**Comment by chemzqm** [comment]
@kevinhwang91 It makes all `<ScrollWheelUp>` and `<ScrollWheelDown>` scroll specific window, which is not I would expected.

**Comment by kevinhwang91** [comment]
You can save the context and then use `vim.schedule` to compare whether the context is changed.
If the floating window is closed, the event ends.

**Comment by kevinhwang91** [comment]
> The user could be scrolling other window, I need to know which one is scrolling, maybe vim.on_key could provide position information.

You can use `getwininfo(targetWinid)` before `vim.schedule` and inside `vim.schedule`, the context may be changed if scroll up and down.
