### ISSUE TITLE
Error executing lua: /usr/local/share/nvim/runtime/lua/vim/uri.lua:105: URI must contain a scheme: .../About/index.module.css

### ISSUE THREAD

**Issue by nyngwang** [neovim/neovim#18223]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+33-g116a3f468 Build type: Release LuaJIT 2.1.0-beta3

### Language server name/version

cssmodules_ls

### Operating system/version

macOS 12.3.1

### Steps to reproduce using "nvim -u minimal_init.lua"

1. Create any simple ts project that supports ES6 module `import`.
2. Create any simple `ts` file and import the CSS module with this syntax:

```
import styles from './index.module.css'
```

### Expected behavior

I can run `vim.lsp.buf.definition()` at any char of `styles` without error. Same thing for `'./index.module.css'`.

### Actual behavior

Got an error:

```
Error executing lua: /usr/local/share/nvim/runtime/lua/vim/uri.lua:105: URI must contain a scheme: .../About/index.module.css
```

video DEMO link: https://github.com/ibhagwan/fzf-lua/issues/393#issue-1212523536
related comment(current observation): https://github.com/ibhagwan/fzf-lua/issues/393#issuecomment-1106732765

**Comment by glepnir** [comment]
@nyngwang  Hi thanks for report. check the response of `textDocument/definition` from `cssmodules_ls` is

```
{
  [2] = {
    result = {
      range = {
        end = {
          character = 0,
          line = 0
        },
        start = {
          character = 0,
          line = 0
        }
      },
      uri = "/Users/joyce/Workspace/todo/src/component/About/index.module.css"
    }
  }
}

```

the field `uri` miss `file://`  schema so you got an error.  check the [lsp json structure](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#basicJsonStructures), I think you should  report to `cssmodules_ls`

**Comment by nyngwang** [comment]
To @glepnir:

> [...] the field `uri` miss `file://` schema so you [...], I think you should report to `cssmodules_ls`

OK, I will do it this weekend, and thank you for the detailed reply!
