### ISSUE TITLE
Accepting donations via crypto is concerning

### ISSUE THREAD

**Issue by BlueManedHawk** [neovim/neovim#18230]
### Feature description

While I understand that there are benefits to cryptocurrency (anonymity being among the highest), it seems to me that these are all outweighed by the detriments of it, these being primarily the significant pollution released by the blockchain and extreme instability in its value.  In addition to those problems (and in large part because of them), cryptocurrencies are gaining a negative reputation in many parts of the internet, and i'm concerned that if Neovim keeps accepting crypto donations, this negative reputation will spread to it.  However, i recognize that this will take away a method by which certain people donate for good reasons (such as anonymity, as mentioned earlier), so if this change is delayed until a suitable alternative can be found, I would understand.

Regards,

— Blue-Maned_Hawk

**Comment by clason** [comment]
As you write, this possibility is still up for two reasons: anonymity, and (more importantly) availability -- there are places in the world where no other avenue of donation is possible. So it will stay for the foreseeable future.

(And, if I may say so, your public issue here is in fact actively engaged in "spreading the negative reputation of cryptocurrencies" to Neovim, which I do not appreciate.)

**Comment by justinmk** [comment]
Feel free to be "concerned". Worrying about controversy is the mind-killer.
