### ISSUE TITLE
Better autocomplete everywhere, not just with `:b`.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#1823]
With `:b` you can autocomplete buffer names by starting with a letter anywhere in the name, not just at the beginning. It'd be nice to have this everywhere. For example, this doesn't happen with command completion, colorscheme name completion, etc.

**Comment by aktau** [comment]
This would definitely be cool. A bit above an entry-level project, but possibly doable by most interested devs :).

**Comment by lewis6991** [comment]
https://github.com/hrsh7th/nvim-cmp now provides rich command line completion which can be enabled with.

```lua
cmp.setup.cmdline(':', { sources = { { name = 'cmdline' } } })
```

As a solution now exists (via a plugin), I suggest we close this issue.

**Comment by justinmk** [comment]
@lewis6991 👍  see also https://github.com/neovim/neovim/issues/16142
