### ISSUE TITLE
Idea: search current window only.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#1824]
When you do `/searchTerm` and have `set hlsearch` then you'll see it finds all occurrences in all files. An option like `searchall` so you can `set searchall` or `set sall` and `set nosearchall` or `set nosall` to control whether or not to search in all windows (not buffers) would be nice. You could then split a file and have different searches in the same file buffer.

This sort of the idea, but it's just hack and not ideal: http://vim.1045645.n5.nabble.com/highlight-search-limit-to-current-window-td4493920.html.

**Comment by bfredl** [comment]
I've looked into the relevant part of the code (but for different reasons, ref #1817 ), and I think, it would not be  hard to add an option to only show the search highlighting in the current window. To also support out-of-the-box to have _different_ search highlightings in different windows will be a bit more work, but it would "basically" amount to move/duplicate the global variable `search_hl` into `window_T`

**Comment by Asheq** [comment]
@trusktr You might find this mapping useful:

```
nnoremap          <leader>/        :mat Match //<Left>
```
 
Type `<leader>/` and then a regex and then Enter to highlight the matches in the current window only. To clear, hit Enter without typing anything else.

Don't forget to set the highlight group `Match` to your liking, e.g.:

```
highlight Match guibg=green
```

This highlighting is independent of the search register, which can be a pro or con depending on your use case.

**Comment by justinmk** [comment]
> To also support out-of-the-box to have _different_ search highlightings in different windows

And this was implemented with 'winhl'. The request in this issue can be achieved via (where `Foo` is a custom highlight definition):

```
hi clear Search
hi clear IncSearch
setlocal winhl=Search:Foo,IncSearch:Foo
```
