### ISSUE TITLE
build: Windows: remove winpty

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#18252]
### Feature description

https://github.com/neovim/neovim/pull/15889#issuecomment-935836007

winpty might be needed only for Windows 8.1. Removing it could simplify our build and allow us to delete a lot of code.

## Proposal

Remove winpty. Require Windows 10 as minimum version.

cc @erw7 (any objections?)

**Comment by erw7** [comment]
I lost my motivation for Windows-related development. No one is actively developing anything related to Windows, so any reduction in Windows-related code is most welcome.

**Comment by wsdjeg** [comment]
@justinmk ohh, really sad, I am still using win 7 os. does it mean neovim will not support win 7?

**Comment by dundargoc** [comment]
Windows 7 support was dropped since 0.6.0 (since it was dropped by a dependency, LibUV).

**Comment by WhyNotHugo** [comment]
The wording on the [breaking changes issue](https://github.com/neovim/neovim/issues/14090#issuecomment-1110521019) is a bit unfortunate:

> https://github.com/neovim/neovim/issues/18252 Windows 10 is required for :terminal.

This sounds like support for Linux was being dropped, I had to check the PR very worried for a moment there!
