### ISSUE TITLE
Cursor disappears when moving vertically

### ISSUE THREAD

**Issue by mrinterweb** [neovim/neovim#1825]
I noticed that if I hold the j or k buttons down, the cursor disappears. When normally pressing j or k buttons once at a time, the cursor does not disappear. The cursor returns when I release the j or k keys.

**Comment by justinmk** [comment]
Assuming it's on a large file , or one with very long lines. I believe Vim does this too, although the debug build of Neovim tends to do it more often. Try building in Release mode. 

https://github.com/neovim/neovim/wiki/Building-Neovim#release-build-optimized-ndebug

**Comment by mrinterweb** [comment]
I installed neovim using homebrew. The command that it compiled with is:
`make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/usr/local/Cellar/neovim/HEAD" install`

I edited the homebrew formula to add the `Release` flag. After reinstalling, the cursor disappeared less frequently when moving vertically, but it would still disappear pretty regularly. The file I'm editing is only 102 lines long.

**Comment by mrinterweb** [comment]
I just switched to using vim-plug which lazy loads plugins, and I'm seeing the issue less. I also have noticed that there seems to be a difference in this bug behavior when editing different file types. For example I am editing a 169 line coffeescript file, I see now problems, but when editing a 102 line ruby file, I do occasionally. I don't know if syntax highlighting could be interfering with the cursor rendering when traveling vertically.
