### ISSUE TITLE
Allow `nvim_create_autocmd` to receive a table as group

### ISSUE THREAD

**Issue by mracos** [neovim/neovim#18250]
### Feature already in Vim?

Nope

### Feature description

First of all, ty all very much for maintaining and improving neovim 💙 

I have some `autocmd`s that I wrap in an `augroup` just so I can clear it, as to not duplicate when reloading the config, would love a little sugar so I don't need to create an `augroup` and then reference it when creating the `autocmd`.

(If I missed something in the docs, please let me know!)

e.g.

```lua
local group = vim.api.nvim_create_group("highlight_text_after_yank", { clear = true })
vim.api.nvim_create_autocmd("BufWritePre", {
  group = group --[[ or "highlight_text_after_yank" --]],
  pattern = "*",
  command = [[%s/\s\+$//e]]
})
```

It's not the end of the world but I think being able to pass a `table` and creating a group at the time of the creation of the `autocmd` would be nice.

For example, I've created an wrapper around `nvim_create_autocmd` that has an API like this:

```lua
m.api.nvim_create_autocmd("TextYankPost", {
  group = { "highlight_after_yank", clear = true },
  pattern = "*",
  callback = function() vim.highlight.on_yank() end,
})
```

Which has an implementation of (warning, not that well thought of and might have a lot of edge cases haha):

```lua
api.nvim_create_autocmd = function(event, opts)
  local group_opts = opts["group"]
  opts["group"] = nil

  local autocmd_group = nil

  if type(group_opts) == "table" then
    local group_name = table.remove(group_opts, 1)
    autocmd_group = vim.api.nvim_create_augroup(group_name, group_opts)
  else
    autocmd_group = group_opts
  end

  if autocmd_group then
    opts = vim.tbl_deep_extend("force", opts, { group = autocmd_group })
  end

  vim.api.nvim_create_autocmd(event, opts)
end
```

Does it make sense? 👀

**Comment by zeertzjq** [comment]
> `group = { "highlight_after_yank", clear = true }`

I don't think API can accept such a kind of table. It is neither a `Dictionary` nor an `Array`.

**Comment by justinmk** [comment]
> > `group = { "highlight_after_yank", clear = true }`
> 
> I don't think API can accept such a kind of table. It is neither a `Dictionary` nor an `Array`.

That can be fixed though, add a key like `name`:

    group = { name = "highlight_after_yank", clear = true }

The general idea here makes sense to me.  Taking a list of handlers seems natural for `nvim_create_autocmd`. In fact it should have an option to create/clear a group without the preamble of calling `nvim_create_augroup` ...

**Comment by mracos** [comment]
> I don't think API can accept such a kind of table. It is neither a Dictionary nor an Array.

@zeertzjq yep, not that well versed in lua 😅, just tried to mimic the call to `nvim_create_augroup` (first param is the name, second is opts) but totally open to suggestions! I liked @justinmk's idea of just having passing a `Dictionary` that has the `name`.

So this is something that we would want in `neovim`? I can try to come up with a PR based on the implementation above if that's the case... 😄

**Comment by DasOhmoff** [comment]
> In fact it should have an option to create/clear a group without the preamble of calling `nvim_create_augroup`
I think so too. Having to always `nvim_create_augroup` is very inconvenient.

**Comment by lewis6991** [comment]
Or just don't provide a group.

The main reason groups are even a thing is that viml files often get reloaded so groups are a way of keeping track of autocmds and making sure they don't get recreated. This is much less of a problem in Lua, unless you have some hacky reload mechanism.

**Comment by DasOhmoff** [comment]
But I do reload the scripts all the time while I am configuring my config all the time. Not sure if this is not a good way to do it, but I have seen many doing that as well, and also it has instant feedback on my config changes.

**Comment by lewis6991** [comment]
Many people also use `vim.defer_fn` to lazy load plugins. Neither are good.

Most Lua plugins are not designed to be reloaded so I strongly recommend you avoid any weird reloading mechanisms.

**Comment by justinmk** [comment]
> Or just don't provide a group. ... The main reason groups are even a thing is that viml files often get reloaded

Disposing event handlers is common, to avoid leaks. `nvim_create_autocmd()` returns an id so that can be tracked instead--but that is equivalent to an augroup?

Rethinking this issue, I don't see a need for enhancing the RPC API, which is low-level. We should instead think about `vim.on()` for an ergonomic interface to defining event handlers.

Closing this because most of the discussion is not relevant.
