### ISSUE TITLE
Filetype detect bug with filetype lua

### ISSUE THREAD

**Issue by rhcher** [neovim/neovim#18258]
### Neovim version (nvim -v)

NVIM v0.8.0-dev

### Vim (not Nvim) behaves the same?

no, vim doesn't have filetype.lua

### Operating system/version

wsl2 Arch

### Terminal name/version

contour

### $TERM environment variable

xterm-24bits

### Installation

build from source

### mini vimrc
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let g:did_load_filetypes = 0
let g:do_filetype_lua = 1

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'wlangstroth/vim-racket'
call plug#end()
PlugInstall | quit
```

### test file
```racket
#lang racket/base
```

1. nvim -u vimrc.vim test.rkt
2. :set ft

### Expected behavior

filetype=racket

### Actual behavior

filetype=scheme

### additional infomation

I think it's because PR 5c53e29ca9f5e86dd905cae134c78aa341ead157

**Comment by clason** [comment]
> I think it's because PR https://github.com/neovim/neovim/commit/5c53e29ca9f5e86dd905cae134c78aa341ead157

Can you bisect to make sure? And check what `vim-racket` is doing exactly?

**Comment by rhcher** [comment]
Seems recently commit fix it and close this.
