### ISSUE TITLE
No manual entry for nvim

### ISSUE THREAD

**Issue by josefnpat** [neovim/neovim#1826]
I went through the trouble of installing `neovim-git` from the arch linux AUR repository, and I have to say I am very impressed! All my `.vimrc` and `.vim` seems to work well!

I went to check the manual page for `nvim` to check for documentation pertaining to the `.nvimrc` and the `.nvim` configurations hoping I could avoid googling, but was presented with the following message:

    $ man nvim
    No manual entry for nvim

I would like to express an interest in having a man page! I searched through the issue queue, and found no references. If you could add this, that would be fantastic!

Here is the `PKGBUILD` I used:

    # Maintainer: Florian Hahn <flo@fhahn.com>

    pkgname=neovim-git
    pkgdesc="Vim's rebirth for the 21st century"
    license=('custom:neovim')
    pkgver=0.r2528.7231a23
    pkgrel=1
    depends=('libuv' 'ncurses' 'msgpack-git-neovim' 'perl')
    makedepends=('cmake' 'git' 'unzip' 'luajit' 'lua' 'lua-messagepack' 'lua-bitop' 'lua-lpeg')
    provides=('neovim')
    arch=('i686' 'x86_64')
    url=('https://github.com/neovim/neovim')
    source=("$pkgname::git://github.com/neovim/neovim.git")
    md5sums=('SKIP')
    install=neovim-git.install

    pkgver() {
      cd "${pkgname}"
      printf "0.r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
    }

    build() {
      cd "${pkgname}"
      cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_INSTALL_PREFIX=/usr
      make
    }

    package() {
      cd "${pkgname}"
      DESTDIR="${pkgdir}" make install
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
    }

    # vim:set sw=2 sts=2 et:

**Comment by fwalch** [comment]
Instead of a manual page, you can always use `:help`. Neovim specifics are at `:help nvim`.

**Comment by josefnpat** [comment]
Thanks! That seems like a good workaround that I will have to employ in the future.

Unfortunately it does not resolve the issue of a missing man page.

**Comment by Pyrohh** [comment]
I assume this could be done with [GNUInstallDirs](http://www.cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html), but I have no clue how it'd be done.
This might be helpful: https://bitbucket.org/osrf/sdformat/pull-request/64/support-for-gnuinstalldirs/diff
