### ISSUE TITLE
E5113 ...

### ISSUE THREAD

**Issue by dr3cod3** [neovim/neovim#18263]
### Neovim version (nvim -v)

0.8.0-dev+52-g89df042a8

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

Debian Bullseye

### Terminal name/version

xterm-kitty

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen
git clone www.github.com/neovim/neovim
cd neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

### Expected behavior

Didn't expect any Error

### Actual behavior

[mynvim.log](https://github.com/neovim/neovim/files/8558465/mynvim.log)

**Comment by muniter** [comment]
That is an issue with your configuration not neovim. it's there in the logs you're trying to require a non existing `plugin.options`.

**Comment by dr3cod3** [comment]
NO, the module does exist nothin wrong with configuration

**Comment by dr3cod3** [comment]
When I ran nvim from ~/.config/nvim I have no issues when nvim is run from any other directory or from Home I got that error. The package that was required is in ~/.config/nvim/plugin/options.lua

**Comment by andmis** [comment]
It's a problem in your config. Use `require('options')`, not `require('plugin.options')` or whatever you have in your config.

**Comment by dr3cod3** [comment]
@andmis I can share my config I sure has the options module in the plugin directory my init.lua is at the root of my .config/nvim, require('options') does not work either still got same error..... so funny how @muniter just closed this issue without proper investigation. require should be able to read the module either way I'm requiring a module inside a plugin directory require('plugin.options') is a valid lua synthax however I did as you asked still got the same error

**Comment by zeertzjq** [comment]
> `~/.config/nvim/plugin/options.lua`

That's not the right place to put a Lua module. Put it in `~/.config/nvim/lua/plugin/options.lua` instead.

**Comment by dr3cod3** [comment]
@zeertzjq  Thanks buddy. I didn't know all lua module has to be in lua directory, this is a testimony that if we listen with an open mind not thinking someone is dumb or whatever lot of problem will be solved. Consideration is lost in this business no one cares about the emotion of others people just want to proof superiority and how savy they are than others. Thanks again @zeertzjq
