### ISSUE TITLE
Indent-blankline + Coc Segmentation fault

### ISSUE THREAD

**Issue by chriztheanvill** [neovim/neovim#18265]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Fedora 35

### Terminal name/version

kitty 0.24.4 and Terminator 2.1.1

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

* Install coc, Indent-blankline
* Move the cursor for a while / Edit / delete / do something in neovim.

### Expected behavior

Can move the cursor without problems.

### Actual behavior

Neovim breaks if I have installed coc + Indent-blankline. So I've disabled Indent-blankline.

**Comment by justinmk** [comment]
We can't debug your plugins. Need a backtrace. Read the FAQ. https://github.com/neovim/neovim/wiki/FAQ#backtrace-linux

After getting a backtrace, search existing issues for the functions, to see if this is a known issue.
