### ISSUE TITLE
`has('python3')` call leaves `v:shell_error` set

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#18278]
### Neovim version (nvim -v)

55135cea619cd1b8b8d7563c14436c092fa749ab

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS 12

### Terminal name/version

iTerm2

### $TERM environment variable

N/A

### Installation

From source

### How to reproduce the issue

Run `nvim --clean` on a system that does not have the `neovim` Python 3 package installed, then:

```
:call has('python3')
:echom v:shell_error
```

### Expected behavior

The `has('python3')` call returns false, and `v:shell_error` is either falsy (0) or unchanged from before the `has(...)` call (this is how Vim behaves, the value of `v:shell_error` is unchanged by calls to `has`).

### Actual behavior

The `has('python3')` call returns false, and `v:shell_error` is set to 2.

I ran into this because if `:PlugUpdate my-package` is called where `my-package` is pinned to a particular commit, and `my-package` is already checked out to that commit, then `vim-plug`'s code happens not to invoke any other shell commands between a `has('python3')` call ([here](https://github.com/junegunn/vim-plug/blob/be55ec46b5ab031805487a9c3e895db57f53010b/plug.vim#L1192)) and a closing block where it checks whether something went wrong by inspecting `v:shell_error` (somewhere in [here](https://github.com/junegunn/vim-plug/blob/be55ec46b5ab031805487a9c3e895db57f53010b/plug.vim#L1284), I think). (So `vim-plug` reports a spurious error.)

So either
- we need to clear `v:shell_error` at some point in the implementation of `has(...)` -- I looked at this a bit and `v:shell_error` is read-only so I'm not sure how to proceed, or
- if this is "working as intended" then we can close this issue and I can refile as a `vim-plug` bug.

**Comment by andmis** [comment]
It might be good to have in the documentation a comprehensive list of which Neovim-provided functions can affect `v:shell_error`, since it's a priori not really clear -- I think a user would imagine that the purpose of `v:shell_error` is to tell _the user_ when one of _their_ `system(...)`, etc., calls returned an error, not that some system call somewhere returned an error. There may be some Vim legacy here that I'm not familiar with, although at least in the case of `has` Vim's behavior matches my description in the previous sentence.

**Comment by justinmk** [comment]
Can just modify `v_has()` to save/restore `v:shell_error`.

**Comment by andmis** [comment]
Sounds good, I'll take a pass on this.
