### ISSUE TITLE
Highlight on yank doesn't override line highlighting

### ISSUE THREAD

**Issue by gerazov** [neovim/neovim#18270]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+60-ga75efc237

### Vim (not Nvim) behaves the same?

they don't have this feature

### Operating system/version

Manjaro Linux 21.2.6 Qonos

### Terminal name/version

konsole 21.12.3

### $TERM environment variable

xterm-256color

### Installation

AUR neovim-git

### How to reproduce the issue

Include the following line in `init.vim`:
```vim
au TextYankPost * silent! lua vim.highlight.on_yank {higroup="IncSearch", timeout=5000, on_visual=true}
```

### Expected behavior

Highlighting of yanked text.

Recorded with `machakann/vim-highlightedyank`:

![highlight_yank](https://user-images.githubusercontent.com/15214418/165268409-46f49c62-26de-4a28-b8dc-fd5f15927042.gif)

### Actual behavior

Highlighting is overridden by line highlighting of color scheme, i.e. it only shows when I move the cursor off the line.

![highlight_yank_builtin](https://user-images.githubusercontent.com/15214418/165268661-9691aea8-ce5f-426f-a2f4-5517e564720d.gif)

I use `joshdick/onedark.vim` as a color scheme if it helps ...

**Comment by clason** [comment]
Almost certainly a priority issue do changing the `vim.highlight` function to use extmarks.

Please try to create a minimal, self-contained example (config and steps) so we can replicate.

**Comment by gerazov** [comment]
Ok my bad - the following line was messing things up:

```vim
hi CursorLine   cterm=NONE ctermbg=gray ctermfg=white guibg=#2f3546  
```

Thanks :pray:
