### ISSUE TITLE
Resizing causes flicker problems with GNOME terminal

### ISSUE THREAD

**Issue by matze** [neovim/neovim#1827]
At the moment Neovim is unusable for me because any attempt to resize a GNOME terminal with Neovim running inside causes flickering between different terminal sizes which takes up to ten seconds. To trigger the bug, resizing must be fast enough. If I resize so slow that only one new row or column appears then nothing happens.

I am running this on:

* Ubuntu 14.04
* Awesome WM 3.4.15
* GNOME Terminal 3.6.2 (no such problems with xterm or urxvt)

**Comment by aktau** [comment]
@tarruda do you think this is new (i.e.: abstract_ui related)? I remember some problems in the beginning with SIGWINCH.

@matze do you know if this used to be the case with Neovim as well. Would you care to perform a quick bisect to pinpoint the commit? I'm on OSX so I can't reproduce atm.

**Comment by tarruda** [comment]
> @tarruda do you think this is new (i.e.: abstract_ui related)? I remember some problems in the beginning with SIGWINCH.

Could be

@matze Can you report what is the behavior with #1820?

**Comment by matze** [comment]
@aktau: I tried to bisect yesterday but with all those merge commits it quickly didn't work (apart from the very time consuming process because I had to remove `.deps` and `build` due to depedency problems). In any case `HEAD~60` still had the problem.

@tarruda: I try now to compile but currently have some problems with undeclared variables and macros in `term.c` such as this

    /home/matthias/dev/neovim/src/nvim/term.c: In function ‘set_termname’:
    /home/matthias/dev/neovim/src/nvim/term.c:1212:13: warning: implicit declaration of function ‘tgetflag’ [-Wimplicit-function-declaration]
             && tgetflag("ms") > 0)

But in any case, my setup here at home is quite different from what I have at work. So I'll report any changes on Monday.

**Comment by matze** [comment]
@tarruda: Your branch fixes the flickering problem however the UI itself requires a bit of "settle time" until the status bar is at the bottom and worse if I resize in a fast wiggly movement, Neovim crashes. I couldn't copy the stacktrace so here's a screen dump:

![stacktrace](https://cloud.githubusercontent.com/assets/115270/5797029/a613f540-9fb2-11e4-8294-481269a51b2a.png)

**Comment by matze** [comment]
Quick update: the code in master reduced the flickering considerably but it's still not perfect. But I think I can start to use Neovim on a more regular basis.

**Comment by tarruda** [comment]
> Quick update: the code in master reduced the flickering considerably but it's still not perfect. But I think I can start to use Neovim on a more regular basis.

Can you post a video demonstrating the problem?

**Comment by matze** [comment]
The second resize [shows](https://drive.google.com/file/d/0B5fr437ogdTpb0JLYlNpOGJEcE0/view?usp=sharing) what I mean. Default vim is quicker redrawing the status bar correctly. But as I said it is not jumping up and down for seconds anymore, which is a huge improvement.

**Comment by justinmk** [comment]
Problem is almost certainly not as severe as original issue, now. Though some flickering may occur on some terminals still.
