### ISSUE TITLE
Highlight on delete and move

### ISSUE THREAD

**Issue by gerazov** [neovim/neovim#18271]
### Feature already in Vim?

No

### Feature description

Awesome work guys :sunglasses: 

It would be nice to have highlighting on delete, move (cut) or change similarily to highlighting on yank, e.g. using `d3w` would show a brief highlight and then delete. This would be useful as a confirmation that the right range of text was deleted/moved/changed.

By move I mean the following remap:
```vim
Plug 'svermeulen/vim-cutlass'  " delete without affecting yank
nnoremap m d
xnoremap m d
nnoremap mm dd
nnoremap M D
```

**Comment by clason** [comment]
What would be the use case? Yank operations would be invisible otherwise, but you can clearly see what is being deleted without the highlight. (Yank is also special since there's already a `TextYankPost` event that exposes all the necessary info; this is not necessarily the case for other operations.)

**Comment by gerazov** [comment]
It would give a visual cue that you can use to verify that the correct region is deleted. Having the visual cue will let you know immediately how good your `d#w` guess is because you're focused on the end of the range to be deleted. Atm the change is instantaneous and you have to refocus to the beginning of the deleted region and reread the text to check if what you did is ok. 

This visual cuing is something that is benefitial to the approach of Kakoune to invert the editor syntax into object + verb, i.e. to cite their [Improving on the editing model](https://kakoune.org/why-kakoune/why-kakoune.html):

> Kakoune’s grammar is object followed by verb, combined with instantaneous feedback, that means you always see the current object [...] before you apply your change, which allows you to correct errors on the go.
>
> [...] Because of the verb followed by object grammar, vi changes are made in the dark, we don’t see their effect until the whole editing sentence is finished. 5dw will delete to next five words, if you then realize that was one word too many, you need to undo, go back to your initial position, and try again with 4dw. 

Sticking in the right number in the `d#w` is not easily done on the first try if you want to do it fast. If you guess low then you can do a couple of `dw`-s to compensate, but guessing high forces you to `u` and then try again. Although this feature would not change the need to undo and retry when wrong, it will make it easier.

**Comment by gerazov** [comment]
I'm thinking about implementing this as a plugin, can you point me in the right direction on how it can be done?

**Comment by Sam-programs** [comment]
@gerazov 
`:help map-operator`
`:help v:lua`
 You can start visual mode to render the selection and move the cursor with `:help nvim_win_set_cursor`.
 And to make neovim render the visual selection use `:help :redraw`.

**Comment by justinmk** [comment]
`TextYankPost`, or `:help `vim.highlight.on_yank()`
