### ISSUE TITLE
Neovim v0.7.0 not available yet on snap

### ISSUE THREAD

**Issue by Flimm** [neovim/neovim#18289]
### Neovim version (nvim -v)

NVIM v0.6.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 21.10

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

snap

### How to reproduce the issue

The latest release of Neovim (v0.7.0) is not yet available on snap. Running `snap install nvim` installs version v0.6.0

### Expected behavior

I expected to find `v.0.7.0` when running `snap info nvim`

### Actual behavior

```
$ snap info nvim
channels:
  latest/stable:    v0.6.0                       2021-12-01 (1722) 10MB classic
  latest/candidate: v0.6.0                       2021-12-01 (1722) 10MB classic
  latest/beta:      ↑                                                   
  latest/edge:      v0.8.0-70-g521e91e1c-nightly 2022-04-28 (2150) 11MB classic
installed:          v0.6.0                                  (1722) 10MB classic
```

**Comment by clason** [comment]
This is an issue for the Snap maintainers, which are entirely unrelated to the Neovim maintainers.
