### ISSUE TITLE
live substitution will cause performance issue

### ISSUE THREAD

**Issue by tristone13th** [neovim/neovim#18299]
### Neovim version (nvim -v)

NVIM v0.7.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

didn't test

### Operating system/version

Ubuntu 20.04

### Terminal name/version

Windows Terminal

### $TERM environment variable

Not tested.

### Installation

appimage

### How to reproduce the issue

1. open nvim with a large test file (about 30k lines)
2. type `:%s/<a>/<b>/g`
3. when type proceed to `<b>`, nvim will stuck.

### Expected behavior

nvim shouldn't stuck, I suppose it is a performance issue caused by live substitution preview.

### Actual behavior

nvim stuck.

**Comment by clason** [comment]
Needs a lot more context, I'm afraid. Please provide a (link to) a concrete text file and share the (minimal!) config needed to reproduce the hang.

**Comment by tristone13th** [comment]
> Needs a lot more context, I'm afraid. Please provide a (link to) a concrete text file and share the (minimal!) config needed to reproduce the hang.

I found the cause, maybe due to syntax highlight for large files, thanks!
