### ISSUE TITLE
Neovim produces a broken $LANG variable when the user's language and region doesn't "match up" on macOS

### ISSUE THREAD

**Issue by mortie** [neovim/neovim#18292]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

No, vim 8.2 produces a sensible $LANG variable

### Operating system/version

macOS 12.3.1

### Terminal name/version

3.4.15

### $TERM environment variable

xterm-256color

### Installation

Homebrew

### How to reproduce the issue

1. Set your region to some place which doesn't have an English variant (e.g Norway)
2. Set your language to English
3. Start nvim
4. Check the `LANG` env var, e.g by running `:echo $LANG`

### Expected behavior

The $LANG env var should be set to a valid locale, such as `en_US.UTF-8` (or it could be left empty for all I care, it just shouldn't be invalid)

### Actual behavior

The $LANG env var is set to the invalid `en_NO.UTF-8` string. There is no "norwegian-english" language.

This is especially problematic when using the terminal mode (`:terminal`). All perl programs, for example, show a huge ugly locale error.

**Comment by clason** [comment]
Related: https://github.com/neovim/neovim/pull/7704

**Comment by clason** [comment]
Apparently other platforms (like Linux) do _not_ need to set `$LANG` for detecting the language when it is unset. Possibly the same approach can be ported to the macOS-specific code as well.

@jamessan do you remember why you implemented it this way (via setting `$LANG`)? It's not obvious to me from the linked issue that this is strictly necessary.

**Comment by clason** [comment]
Ah, I suspect that it's for interfacing with `pbpaste` when pasting from the system clipboard -- this seems to get the encoding from `$LANG`. You can test this with setting an incorrect (empty or mismatched) `$LANG` and trying to paste `いろは` into Neovim.

This seems hard to fix (without hardcoding a list of admissible locales)... On the other hand, I don't see having to set the `language` explicitly in your `init.vim` (which I may remind fixes all these problems) when you choose to mix and match in your Location Settings as such a great hardship.

**Comment by clason** [comment]
Note that Vim has a somewhat similar locale handling
https://github.com/vim/vim/blob/05c7f5d3d03440da6f69604f8c06c4e3d90d2a26/src/os_mac_conv.c#L565-L594

The behavior is slightly different, though: an invalid locale seems to fall back to `en_US.UTF-8` (which is propagated to their terminal).

**Comment by mortie** [comment]
> On the other hand, I don't see having to set the language explicitly in your init.vim (which I may remind fixes all these problems) when you choose to mix and match in your Location Settings as an unreasonable hardship.

Let me point out that you're suggesting that neovim should be broken out of the box for _all_ mac users who prefer English but don't live in the US or UK. And for _all_ mac users who otherwise have a setup where CoreFoundation doesn't give you a locale which works with "LANG". I don't really think that's as unproblematic as you're claiming it is.

Also, is the current behavior even correct? Does nvim expect pbpaste to return UTF-8 which nvim then converts to the correct encoding, or does nvim just assume that whatever pbpaste returns matches the encoding of the file?

If nvim expects pbpaste to return UTF-8, wouldn't a more targeted solution be to set `LANG="en_US.UTF-8"` when running pbpaste instead of setting it the locale globally for the whole application and all child processes?

Or, maybe we could use another env var? I'm looking at the man page for `pbpaste`, it doesn't mention LANG, just that it uses "environment variables". I would expect it to use LC_CTYPE by default, which on my system is set to UTF-8 out of the box.

**Comment by clason** [comment]
> Let me point out that you're suggesting that neovim should be broken out of the box for all mac users who prefer English but don't live in the US or UK.

No, all I'm saying is that a simple workaround exists, which makes this a less urgent issue than it would have been otherwise.

In particular, it means that one can take the time to actually look at the code and the history to see what is going (what was the rationale to do it this way? where is this value needed? what effects would various mitigation strategies have?) instead of throwing up a bunch of "shoulds" and "why can'ts".

(Which, I have to admit, I'm personally starting to lose the motivation for.)

**Comment by bram98** [comment]
This worked for me:

1.  Change `options.lua` and `init.lua` to be ANSI encoded (basically ascii)
  a. Open those files in notepad++
  b. Click 'Encoding' and press ANSI
2. type `vim.cmd('language en_US')` in your `options.lua` file

I used the .lua versions of init files, but the .vim versions should be easily extrapolated.

Step 1 makes nvim load the `options.lua` file, even though the LANG is not properly set.
Step 2 fixes the issue for good.
