### ISSUE TITLE
docs: generate builtin.txt (formerly eval.txt) from eval.lua

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#18311]
## Proposal

Generate `builtin.txt` (formerly `eval.txt`) from `src/nvim/eval.lua`, similar to `:help api`.

This would involve the following:

1. add the old docs into `eval.lua` or a parallel structure like `eval_docs.lua`
2. update `gen_vimdoc.py` to consume `eval.lua`
    - support annotations like `fast`, see https://github.com/neovim/neovim/pull/18306
4. tradeoff/cost: can't automerge `eval.txt` changes from upstream

**Comment by zeertzjq** [comment]
I guess `builtin.txt` is now more suitable for this?
