### ISSUE TITLE
improper yaml indent on new lines

### ISSUE THREAD

**Issue by asmka** [neovim/neovim#18316]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

no, vim 8.1.3741

### Operating system/version

ubuntu 20.04.4 LTS

### Terminal name/version

wsl2 kernel version 5.10.16

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

nvim --clean
:set filetype=yaml
```
a: b<CR>
```

### Expected behavior

'|' is cursor.
```
a: b
|
```

### Actual behavior

'|' is cursor.
```
a: b
  |
```

**Comment by zeertzjq** [comment]
What is "vim 8.1.3741"? This Vim version doesn't exist.

**Comment by zeertzjq** [comment]
Anyway, Vim 8.2.4827 behaves the same.

**Comment by clason** [comment]
Hardly surprising, since we use the same runtime files :)

**Comment by dundargoc** [comment]
@asmka You can contact the maintainer of the yaml file about this problem by mailing them. The email is at the top of `runtime/indent/yaml.vim`, If they're unresponsive you can escalate it to https://github.com/vim/vim since they're officially responsible for the runtime files.

**Comment by asmka** [comment]
I confirmed the same behavior with Vim 8.2. Thanks.

@dundargoc 
 Thank you for the information.
I will research why it was changed to this behavior and ask them if needed.

**Comment by asmka** [comment]
Relates: https://github.com/vim/vim/issues/8740
