### ISSUE TITLE
CI: failing build

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1831]
two builds of 5c6348e:

- https://travis-ci.org/neovim/neovim/builds/47221480
- https://travis-ci.org/neovim/neovim/builds/47125254

one fails, one does not. I think it is because of this neovim/deps update: https://github.com/neovim/deps/commit/248193441f6f9bd4ae9631974a91d6b3b07ee94b

We probably should pin our lua deps to specific versions. But maybe this uncovered a bug in our unit tests, I haven't investigated.

**Comment by justinmk** [comment]
related upstream lfs PR: https://github.com/keplerproject/luafilesystem/commit/601b4e54981d685d0a3c6049622453e897e55c01

@stefan991 any idea why our tests are failing now? It is complaining about this line:

    lfs.attributes(filepath, 'r'

**Comment by stefan991** [comment]
@justinmk: The PR on luafilesystem Fixed a bug wehre it returned wrong values for blksize and blocks. Prior to this pr they only compared the first letter of the attributes and had some special cases for attributes that start with the same letter. I changed it so that the whole attribute name gets compared in all cases.

I dont have accsess to an computer right now, to check this, but the fix schuld be simple: find the filesystem attribute that starts with 'r' and replace 'r' with the whole name :)

**Comment by justinmk** [comment]
@stefan991 That makes sense, thanks!

**Comment by aktau** [comment]
> I dont have accsess to an computer right now, to check this, but the fix schuld be simple: find the filesystem attribute that starts with 'r' and replace 'r' with the whole name :)

Yes, in fact the second argument of `lfs.attributes` was never meant to be the "open" mode for the file (or the docs where changed where I can't find them). I suppose this erroneous usage stems from this: http://stackoverflow.com/a/12223629/558819

This is the implementation of `lfs.attributes`: https://github.com/keplerproject/luafilesystem/blob/master/src/lfs.c#L805-L838 (also note the [docs](http://keplerproject.github.io/luafilesystem/manual.html)).

Looking at the source, it would probably be easiest to call it without arguments (seem like it would be more portable). In the case the file doesn't exist, it returns `nil` anyway:

```c
        if (st(file, &info)) {
                lua_pushnil (L);
                lua_pushfstring (L, "cannot obtain information from file `%s'", file);
                return 2;
        }
```

I don't think we should specifically stop using the most recent stable version of oft-used Lua (or other) libraries, we might miss important fixes and worse, inadvertently create the legacy system we're trying to run away from. It's not the library that was wrong, it was our usage, and it's time to patch it.

On a related note, my corporate overlords have given me the OK-go on committing to Neovim (I can even keep the copyright so there's no changes there). So I'll celebrate by submitting a patch.

**Comment by justinmk** [comment]
@aktau Ok, good thoughts, and very happy that you are street legal again!
