### ISSUE TITLE
[Nightly] When I run nvim it just gives me a blank screen.

### ISSUE THREAD

**Issue by fgclue** [neovim/neovim#18327]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+78-g7df25a137

### Vim (not Nvim) behaves the same?

No, version 8.2.2824

### Operating system/version

Windows 11

### Terminal name/version

Command Prompt, PowerShell (Core)

### $TERM environment variable

I don't have one.

### Installation

scoop (scoop.sh)

### How to reproduce the issue

How to reproduce:

Step 1:
Install NeoVim
`> scoop install neovim-nightly`

Step 2:
Add the plug package manager to NeoVim
`> cd C:\Users\Name\scoop\apps\neovim\share\neovim\runtime\autoload\`
`> wget https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`

Step 3:
Run NeoVim
`> nvim`

### Expected behavior

I was expecting nvim to open.

~
~
~
~                                            NVIM v0.8.0-dev+78-g7df25a137
~
~                                     Nvim is open source and freely distributable
~                                               https://neovim.io/#chat
~
~                                    type  :help nvim<Enter>       if you are new!
~                                    type  :checkhealth<Enter>     to optimize Nvim
~                                  digite  :q<Enter>             para sair
~                                    type  :help<Enter>            for help
~
~                                           Ajude crianças pobres em Uganda!
~                                  digite  :help iccf<Enter>     para informações
~
~
~
**[Sem nome]                                                                                            0,0-1         Tudo**

### Actual behavior

It doesn't load.

╭─Win Home 54ms                                                                   pwsh CPU 72% Time 12:32:04 
╰─>> nvim

*Screen quickly clears*

╭─Win Home 54ms                                                                   pwsh CPU 72% Time 12:32:04 
╰─>>

**Comment by clason** [comment]
You're supposed to put plugins in your personal config directory, not the bundled runtime!

**Comment by fgclue** [comment]
oh....
