### ISSUE TITLE
NvimTreeVertSplit highlight group stopped working with v0.7 release

### ISSUE THREAD

**Issue by siduck** [neovim/neovim#18325]
### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

void linux

### Terminal name/version

st

### $TERM environment variable

st-256color

### Installation

void linux repo ( xbps package manager )

### How to reproduce the issue

NvimTreeVertSplit highlight group stopped working with v0.7 release, it did work with v0.6

**Minimal config** : https://paste.sh/KaFLd5-r#wtFolWMn1k0fRVU64gqSUi3T

**Test highlight** 

hi NvimTreeVertSplit guibg=#ff0000 guifg=#00FF00

Link to original issue https://github.com/kyazdani42/nvim-tree.lua/issues/1142

### Expected behavior

![image](https://user-images.githubusercontent.com/59060246/166109912-5a58d565-6af7-4111-ba6e-a265a8f7b7e9.png)

It was possible before to color it the same as nvimtree bg but now it just takes the highlight color of vertsplit :/ 
### Actual behavior
 
![image](https://user-images.githubusercontent.com/59060246/166109928-d44f5ef1-54b9-4a51-a4eb-eaa2977811f3.png)

**Comment by clason** [comment]
That's not an issue with Neovim. (#17266 introduced `WinSeparator` in place of `VertSplit`, but the groups are linked by default for backwards compatibility.)

**Comment by siduck** [comment]
> That's not an issue with Neovim. (#17266 introduced `WinSeparator` in place of `VertSplit`, but the groups are linked by default for backwards compatibility.)

Oh, I colored winseparator and then vertsplit, but it seems like vertsplit's taking the winseparator highlight color :(  

![image](https://user-images.githubusercontent.com/59060246/166110169-01b995dc-4797-4bdf-b20e-aeab92556c17.png)

**Comment by clason** [comment]
Yes. That is exactly what I meant. Use `WinSeparator`, not `VertSplit`.

**Comment by siduck** [comment]
> Yes. That is exactly what I meant. Use `WinSeparator`, not `VertSplit`.

oh so vertsplit's depreceated right? so NvimTreeVertSplit will change to NvimTreeWindowSeparator? :think
