### ISSUE TITLE
`FocusLost` and `FocusGained` events will not fire

### ISSUE THREAD

**Issue by EtiamNullam** [neovim/neovim#18330]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

No, vim `8.1.2233`

### Operating system/version

Windows 10

### Terminal name/version

Doesn't seem to be terminal-dependent, as `vim` works on all of them, I've tried:

- Cmd 10.0.19041.1415
- Powershell 7.1.2
- Cmder 1.3.18.1106

### $TERM environment variable

Not applicable

### Installation

scoop

### How to reproduce the issue

1. Start with no config: `nvim -u NORC`
2. Register autocommands for `Focus*` events: 
```viml
autocmd FocusLost * echo 'FocusLost'
autocmd FocusGained * echo 'FocusGained'
```
3. Change focus to another window
4. Notice no message will appear
5. Change focus back to terminal
6. Notice there is still no message displayed

### Expected behavior

Events should fire displaying `FocusLost` and `FocusGained` as terminal windows gains and loses focus, just like it happens in `vim`.

### Actual behavior

`FocusLost` and `FocusGained` events won't fire.

NOTE: It works when ran using some client like `Nvy` or `nvim-qt`, still not in every case like `vim`.

EDIT: Replaced `Alacritty` with plain `Cmd`, because `vim` also won't fire these events when ran on `Alacritty`.
EDIT2: Include `FocusGained`

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by EtiamNullam** [comment]
@justinmk same problem on `NVIM v0.8.0-dev+78-g7df25a137`

**Comment by igorlfs** [comment]
Similarly,  the `cursorHold` event is not firing in my setup (just tested with the latest version). @EtiamNullam can you test it with yours?

**Comment by EtiamNullam** [comment]
@igorlfs `CursorHold` will trigger for me in `Cmder`. I register autocommand like this:
```viml
autocmd CursorHold * echom('CursorHold')
```
Remember that `updatetime` is `4000` (`4` seconds) by default, so `CursorHold` will fire 4 seconds after of inactivity.

I guess its a separate issue that you have.

**Comment by igorlfs** [comment]
> I guess its a separate issue that you have.

Indeed, a quick search lead me to #12587 😅
