### ISSUE TITLE
Allow `nvim_create_user_command` to take function callbacks

### ISSUE THREAD

**Issue by kdheepak** [neovim/neovim#18335]
### Feature already in Vim?

No

### Feature description

Now, that `nvim_create_autocmd`, `nvim_set_keymap` accept functions as the "rhs", it would be nice if `nvim_create_user_command` allowed something similar too.

For example:

```lua
nvim_create_user_command("LspFormat", function() vim.lsp.buf.formatting_sync(nil, 1000) end)
```

Alternatively, if breaking changes in the API are okay, for consistency, it could be made to work the same way as `autocmd` does:

```lua
nvim_create_user_command("LspFormat", { callback = function() vim.lsp.buf.formatting_sync(nil, 1000) end })
nvim_create_user_command("LspLog", { command = "edit " .. vim.lsp.get_log_path()  })
```

I didn't see an issue to track this so I thought I'd make a feature request.

**Comment by fsouza** [comment]
> ### Feature already in Vim?
> 
> No
> ### Feature description
> 
> Now, that `nvim_create_autocmd`, `nvim_set_keymap` accept functions as the "rhs", it would be nice if `nvim_create_user_command` allowed something similar too.
> 
> For example:
> 
> ```lua
> nvim_create_user_command("LspFormat", function() vim.lsp.buf.formatting_sync(nil, 1000) end)

Your example just works.

From the docs (`:h nvim_create_user_command`):

> When called from Lua, the command can also be a Lua function.

**Comment by zeertzjq** [comment]
Isn't this already supported?

**Comment by kdheepak** [comment]
I thought I tried it but maybe I didn’t do it correctly. I’ll look into it again!
