### ISSUE TITLE
Faster Builtin word completion

### ISSUE THREAD

**Issue by z0xyz** [neovim/neovim#18346]
### Feature already in Vim?

No

### Feature description

I've used other editors such as kak and found that offered a more easily configured and faster word completion. 
I've tried to stick with both vim's infamous coc-nvim for buffer and word completion, and after opening an issue, the developer did implement another algorithm that cut off some of the 
- lagging while typing and deleting words
- delay before showing up the completion menu
- constant CPU spikes while scouring and forming the completion menu
 
These traits used to be -and still to some extent- a common place while using the French dictionary (or any dictionary/bloated buffer of this size i.e. ~350,000 words) for word completion. 
Whether it be coc-vim or neovim with the convoluted language server and it's lengthy configuration, they both suffered from the same aforementioned drawbacks. 

I was hoping for both faster and builtin word completion option that gets easily toggled on or off, considering that such a basic feature should be readily available without much hassle or fiddling, and should also take buffers of similar -or even larger- sizes like the French dictionary.

**Comment by clason** [comment]
I'm sorry, but this is more of a rant than an actionable feature request.

**Comment by z0xyz** [comment]
> I'm sorry, but this is more of a rant than an actionable feature request.

I was just describing the current grand scheme of things, to give a better idea or what and why i'm exactly looking for. 

>  If you have specific suggestions how this could be made faster, please open a new issue.

Let me quote me on "*I was hoping for both faster and builtin word completion option that gets easily toggled on or off*"

> And dictionary completion is already builtin (:h compl-dictionary)

Again, let me quote me on  "*should also take buffers of similar -or even larger- sizes like the French dictionary.*"  and also "*or any dictionary/bloated buffer of this size i.e. ~350,000 word*"
