### ISSUE TITLE
API function for getting augroup name from id

### ISSUE THREAD

**Issue by arsham** [neovim/neovim#18343]
### Feature already in Vim?

N/A

### Feature description

The `vim.api.nvim_get_autocmds` call returns the `group`s by their ids in the results. Example:
```
{
    buflocal = false,
    command = "set relative number when focused",
    desc = "set relative number when focused",
    event = "BufEnter",
    group = 8,
    id = 6,
    once = false,
    pattern = "*"
}
```

The `autocmd` can produce the group names. Example:
```
SPECIAL_SETTINGS  BufEnter
    *         set relative number when focused
```

It would be great if there was a way to get the augroup name by its id, or even better, the `nvim_get_autocmds` would provide an extra property for the `group_name`.

Thank you.

**Comment by justinmk** [comment]
> the `nvim_get_autocmds` would provide an extra property for the `group_name`.

👍
