### ISSUE TITLE
$VIM name doesn't match the nvim-data folder name created at runtime

### ISSUE THREAD

**Issue by alfanjui** [neovim/neovim#18349]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10 Home 10.0.19043

### Terminal name/version

Poweshell 5.1.19041.1645

### $TERM environment variable

no

### Installation

Pre-built Packages

### How to reproduce the issue

unzip nvim-win64.zip
cd '.\Program Files\nvim-win64\bin'
nvim-qt.exe

_**INSIDE NEOVIM**_
:version
System-vimrc-Datei: "$VIM\sysinit.vim"
Voreinstellung für $VIM: "C:/Program Files/nvim/share/nvim"

_**IF WE LOOK FOR THE ~\AppData\Local\nvim\ FOLDER IT DOESN'T EXIST**_

### Expected behavior

The name given to the folder from the .zip should automatically be changed to "nvim", since the runtime won't be looking for nvim-data.

### Actual behavior

The folder in **~\AppData\Local\** is named nvim-data after execution of the nvim-qt.exe, causing lots of confusion about the real location for the _**init.vim**_ NeoVim is looking for.

**Comment by alfanjui** [comment]
Just to comment that "nvim-data" gets created anyways after changing the name of the original "nvim-data" folder, this might as well not be a bug, but it sure creates some unexpected behavior if one is reading the documentation on the README

**Comment by justinmk** [comment]
> Voreinstellung für $VIM: "C:/Program Files/nvim/share/nvim"
> 
> _**IF WE LOOK FOR THE ~\AppData\Local\nvim\ FOLDER IT DOESN'T EXIST**_

The `:version` info clearly says what it's looking for. Where are you seeing "AppData"?

No, we're not going to mention every little thing in the README.

**Comment by alfanjui** [comment]
No problem! I just thought that changing the default folder name might be helpful for some people, as I've seen many people with the same problem.
