### ISSUE TITLE
`non-float cannot have 'row'` for `nvim_win_set_config` on floating window

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#18368]
### Neovim version (nvim -v)

a1542b091dd7b919fa8524c1c909ef897dde9299

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

From source

### How to reproduce the issue

```
local buf = vim.api.nvim_create_buf(false, true)
local win = vim.api.nvim_open_win(buf, true, {
  relative = 'editor',
  row = 5, col = 5,
  width = 10, height = 10,
})

vim.api.nvim_win_set_config(win, {
  width = 3, height = 3,
  row = 10, col = 10, -- Runs fine without this line,
                      -- this line gives:
--[[

E5113: Error while calling lua chunk: mwe.lua:8: non-float cannot have 'row'
stack traceback:
        [C]: in function 'nvim_win_set_config'
        mwe.lua:8: in main chunk

--]]
  -- relative = 'editor', -- Adding this fixes it.
})
```

### Expected behavior

You shouldn't have to re-specify `relative` -- the `nvim_win_set_config` docs state that existing config options will be kept:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/5308024/166261454-db88693f-57ed-4ada-b824-4b6e5b3eb25c.png">

See: `parse_float_config` in `win_config.c`.

### Actual behavior

You can't set `row`/`col` without re-specifying `relative`.

**Comment by jackcogdill** [comment]
Ran into this issue today. At the bare minimum, the error message should be updated. It's wrong, since in my case it is indeed a float window.
