### ISSUE TITLE
`print` call in `VimResized` autocmd does not appear in the command line

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#18369]
### Neovim version (nvim -v)

a1542b091dd7b919fa8524c1c909ef897dde9299

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

macOS 12

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

From source

### How to reproduce the issue

- `nvim --clean`
- `:lua vim.api.nvim_create_autocmd("VimResized", {callback=function() print("Resized!") end})`
- (Or in Vim: `autocmd VimResized * :echom "Resized!"`)
- Resize Neovim.

### Expected behavior

`Resized!` appears in the echo area.

### Actual behavior

`Resized!` _does_ appear in `:mess`, but not in the echo area.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/wiki/FAQ#calling-inputlist-echomsg--in-filetype-plugins-and-autocmd-does-not-work

I think there's a PR with recent work on this.

**Comment by gpanders** [comment]
This doesn't seem to be related to `shortmess+=F`, because even with `shortmess-=F` the result is the same.

My guess is that when the window is resized Nvim is doing a redraw, which clears the text in the echo area.

This works:

```lua
vim.api.nvim_create_autocmd("VimResized", {callback=vim.schedule_wrap(function() print("Resized!") end)})
```
