### ISSUE TITLE
Omnisharp Roslyn: Cant go to definition for types imported from other packages

### ISSUE THREAD

**Issue by quantum-booty** [neovim/neovim#18377]
### Neovim version (nvim -v)

v0.8.0-dev+100-g371dfb174

### Language server name/version

omnisharp-roslyn 1.38.2

### Operating system/version

archlinux

### Steps to reproduce using "nvim -u minimal_init.lua"

Trying to go definition on "Dictionary" result in the following error:

```csharp
using System.Collections.Generic;
Dictionary<int, int> test = new();
```

```
Error executing vim.schedule lua callback: ...t_nvimfHRNA0/usr/share/nvim/runtime/lua/vim/lsp/util.lua:997: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...t_nvimfHRNA0/usr/share/nvim/runtime/lua/vim/lsp/util.lua:997: in function 'jump_to_location'
        ...imfHRNA0/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:343: in function 'handler'
        ....mount_nvimfHRNA0/usr/share/nvim/runtime/lua/vim/lsp.lua:1043: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Expected behavior

I expect to be able to see the source code.

### Log file

https://gist.github.com/quantum-booty/3a8b64112c1410397434b161f531bff5

**Comment by fn-bruce** [comment]
I'm running into this issue as well.

**Comment by jakeshoemaker** [comment]
I too am seeing this issue. Nvim 0.7 & Latest version of omnisharp-roslyn

**Comment by DrGGCoolman** [comment]
same here 
![image](https://user-images.githubusercontent.com/33312626/175080000-c61e99df-5ff2-425c-8196-187a8731e8b7.png)

**Comment by piaokorg** [comment]
macos  neovim 0.7  same too

**Comment by pwang2** [comment]
Any update here? Because of this, I have to use Omnisharp-vim instead of the neovim lsp for C# only which results a quite messy configuration.

**Comment by armed** [comment]
Experiencing same issue but with clojure language (macos)

**Comment by quantum-booty** [comment]
This plugin provides the functionality for decompilation.
https://github.com/Hoffs/omnisharp-extended-lsp.nvim
