### ISSUE TITLE
Pynvim segfaults

### ISSUE THREAD

**Issue by Tranquility** [neovim/neovim#1837]
Before I was using the bundled version. Now I build and installed libtickit myself. It only segfaults in some terminals. 

Please describe steps I can do to debug this.

**Comment by tarruda** [comment]
> Before I was using the bundled version. Now I build and installed libtickit myself. It only segfaults in some terminals.

> Please describe steps I can do to debug this.

Libtickit has made some modifications that can result in ABI incompatibility with python cffi bindings, for now only the bundled version can be used. 

BTW did you try #1820?

**Comment by Tranquility** [comment]
Thanks @tarruda installing [this](https://github.com/neovim/neovim/commit/14ebe608e2d26ba352f5abe1c32ce18fcc2eca06) version fixed the problem.

And I will try the tickit-ui branch and report if I see anything noteworthy!
