### ISSUE TITLE
Limitations with jobsend

### ISSUE THREAD

**Issue by bfredl** [neovim/neovim#1838]
(When using `jobsend` in its list form it is not possible to send anything that doesn't end with a newline. I e it is impossible to send the string `"aa\x00\nbb\x00"`, as calling `jobsend(job, ["aa\n","bb\n"]` will add an extra newline to the end `"aa\x00\nbb\x00\n"`. It would be more consistent with `systemlist` if this didn't happen, i.e. one would need to add an empty string to the end of the list to get a final newline. But if too much code already depends on present behavior, an option to change this can be added.) Done in #2073 

Also, AFAIK, there is no way to signal `EOF` to a `job` (at least, it is not documented). `jobsend` could take a flag to signal `EOF` after all its data is sent.

**Comment by justinmk** [comment]
We could add a flags param like https://github.com/neovim/neovim/pull/1584

**Comment by tarruda** [comment]
I suggest enhancing `jobstop` with an optional string argument to close the streams, it should be very easy to implement and could be used have full control over the job stdio, for example:

```vim
call jobstop(id) " kill the job and close its streams
call jobstop(id, 'stdin') " signal to the job that no more data is coming
call jobstop(id, 'stdout') " close the job stdout(no more 'stdout' events)
```

**Comment by bfredl** [comment]
Good suggestios, but wouldn't be clearer with a separate `jobclose(id, 'stdin')`, I think closing a stream is far less drastical than killing a process (and `jobstop` without second arg can close all streams)

**Comment by tarruda** [comment]
> Good suggestions, but wouldn't be clearer with a separate jobclose(id, 'stdin'), I think closing a stream is far less drastical than killing a process (and jobclose without second arg can close all streams)

:+1:

**Comment by justinmk** [comment]
Can this be closed by  #2073 or is the `jobstop()` enhancement still on the table?

**Comment by tarruda** [comment]
#2073 only fixes the mandatory newline, it still needs way to close stdin. I might have a shot at this in the next few days

**Comment by bfredl** [comment]
@tarruda :+1:
