### ISSUE TITLE
clicking on line n moves cursor to line n+1

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#1839]
Steps to reproduce:
1. Open a text file.
2. set mouse=a
3. Click somewhere to move the cursor. Neovim will instead move to the position one line below wherever you clicked.

I'm using the PPA package, current version is 0.0.0+git201501162135+1~ubuntu14.10.1.

**Comment by osa1** [comment]
Can't reproduce with NVIM 0.0.0-alpha+201501161635.

**Comment by belak** [comment]
Mouse support appears spotty at best. I'm getting the same thing but line n-1. I can check the version when I get home.

**Comment by fwalch** [comment]
Can confirm with 0.0.0+git201501162135+1~ubuntu12.04.1. With #1820, it doesn't jump to a different line, but the cursor moves one character to the left when clicking (cc @tarruda).

**Comment by tarruda** [comment]
I can't reproduce this. with master or #1820.

@ghost can you link to your vimrc? Also, what is your terminal emulator?

**Comment by glebtv** [comment]
Also have n+1. Terminal is xterm, arch linux
It was working fine with a previous git build from about two weeks ago

**Comment by andbartol** [comment]
I tried to bisect , apparently the first bad commit is 04c0658024a98a0586997f0ea8af1e3f774cc83e

**Comment by glebtv** [comment]
For me,
62c1daffe028185030d0d8e95dc2c6532457b4fa - mouse works
4c55c34efaabaa151391edf59c59a14411a79d8c - doesnt work

Also, it does not break mouse on urxvt terminal for me, only in xterm

**Comment by glebtv** [comment]
https://github.com/neovim/neovim/commit/04c0658024a98a0586997f0ea8af1e3f774cc83e#diff-1a32cc1056b083197e9462b926958276L3243
https://github.com/neovim/neovim/commit/04c0658024a98a0586997f0ea8af1e3f774cc83e#diff-1a32cc1056b083197e9462b926958276L3249
Here is the problem, it was decremented by one before this commit, apparently a typo.

**Comment by glebtv** [comment]
I've created pull request #1880  for tihs, it fixes it for me

**Comment by elmart** [comment]
I confirm that. My bad. Sorry for that.
