### ISSUE TITLE
Line in commit message that starts with a number confuses the auto indentation

### ISSUE THREAD

**Issue by ericonr** [neovim/neovim#18396]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

I don't have vim installed right now

### Operating system/version

Linux, tested on musl

### Terminal name/version

foot 1.11.0

### $TERM environment variable

screen-256color

### Installation

Void Linux package

### How to reproduce the issue

- Set neovim as your git editor
- Run `git commit`
- Copy the commit message from https://github.com/lnls-dig/openMMC/pull/126/commits/fc56dedffff4781e4b0c06594f358aedb7cfe957
- Select the commit body and press `gq` to auto format it

The commit message in question:

```
fpga_spi: guarantee board_diagnostic_t alignment

fpga_spi.c reads from this struct by aliasing it to an uint32_t pointer
and using that to iterate through it. That means it should be aligned to
4 bytes, to so the reads don't generate faults, and that its size should
be a multiple of 4, otherwise we'd have to deal with defining incomplete
reads for the last element.
```

### Expected behavior

The commit body should be left as is.

### Actual behavior

The commit body is changed to:

```
fpga_spi.c reads from this struct by aliasing it to an uint32_t pointer
and using that to iterate through it. That means it should be aligned to
4 bytes, to so the reads don't generate faults, and that its size should
  be a multiple of 4, otherwise we'd have to deal with defining
  incomplete reads for the last element.
```

**Comment by zeertzjq** [comment]
This is because the ftplugin for `gitcommit` sets `formatoptions+=n` and `formatlistpat` and it comes from <https://github.com/tpope/vim-git/pull/60>. Even if you think this is a bug, you should report this to <https://github.com/tpope/vim-git>.
