### ISSUE TITLE
Formatoption 2 not working correctly within XML comment

### ISSUE THREAD

**Issue by W4RH4WK** [neovim/neovim#18394]
### Neovim version (nvim -v)

v0.7.0

### Vim (not Nvim) behaves the same?

no, even more broken in Vim 8.1 (2018 May 18, Debian 10)

### Operating system/version

Ubuntu 20.04 (WSL)

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

from GitHub source

### How to reproduce the issue

nvim --clean test.xml
:set formatexpr=
:set formatoptions+=2
:set tw=79

Paste this into Vim:
```
<!-- Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras elementum
  ullamcorper quam, sit amet pharetra metus placerat sagittis. Nam condimentum, tellus et rhoncus mollis, quam neque tempor arcu, nec iaculis ante ex ac nibh. Nulla sit amet facilisis urna. Nulla aliquet erat ut pharetra viverra. Nunc dignissim, lectus a commodo finibus, lectus ex placerat arcu, sit amet luctus est velit sed lorem. -->
```

Execute `gqip`

### Expected behavior

```
<!-- Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras elementum
  ullamcorper quam, sit amet pharetra metus placerat sagittis. Nam condimentum,
  tellus et rhoncus mollis, quam neque tempor arcu, nec iaculis ante ex ac
  nibh. Nulla sit amet facilisis urna. Nulla aliquet erat ut pharetra viverra.
  Nunc dignissim, lectus a commodo finibus, lectus ex placerat arcu, sit amet
  luctus est velit sed lorem. -->
```

### Actual behavior

```
<!-- Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras elementum
  ullamcorper quam, sit amet pharetra metus placerat sagittis. Nam condimentum,
tellus et rhoncus mollis, quam neque tempor arcu, nec iaculis ante ex ac nibh.
Nulla sit amet facilisis urna. Nulla aliquet erat ut pharetra viverra. Nunc
dignissim, lectus a commodo finibus, lectus ex placerat arcu, sit amet luctus
est velit sed lorem. -->
```

**Comment by clason** [comment]
Also, _why_ do you expect this behavior? You're disabling the `formatexpr`, after all.

**Comment by W4RH4WK** [comment]
I'll try Vim 8.2.4860 tomorrow, hopefully I can find the time.

After doing a bit more investigating I discovered that the issue might not be related to the `2` `formatoption`, which appears to apply to regular text and not comments. Alas, I do still think there is an issue here.

`formatexpr` is set to `xmlformat#Format()` because of (Neo)Vim's XML runtime scripts and has/had a problem with reflowing comments (https://github.com/chrisbra/vim-xml-runtime/issues/35). That's why I cleared that setting to have the regular Vim behavior.

Why I expect this output: this is what I get in C using `/* */`. Maybe the indentation of my expected result should be a bit more; however, it should be consistent.

When I execute `gqip` on a multiline comment in a C file, I get this:

```c
/* Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras elementum
   ullamcorper quam, sit amet pharetra metus placerat sagittis. Nam
   condimentum, tellus et rhoncus mollis, quam neque tempor arcu, nec iaculis
   ante ex ac nibh. Nulla sit amet facilisis urna. Nulla aliquet erat ut
   pharetra viverra. Nunc dignissim, lectus a commodo finibus, lectus ex
   placerat arcu, sit pamet luctus est velit sed lorem. */
```

(Depending on `formatoptions` with or without leading `*`s.)

Note that `commentstring` is set to `<!--%s-->` for XML, which seems correct as it is set to `/*%s*/` for C.

**Comment by clason** [comment]
Yes, but if you clear the formatexpr, you shouldn't expect to get XML specific formatting.

(C has C specific formatting because it is C.)

If you have an issue with the XML formatting, the right thing to do is to contact the maintainer of the file and have them fix it and make a PR to Vim.

**Comment by clason** [comment]
To be clear: there is no expectation that the 'regular' V behaviour is 'correct', do there is no issue here.

**Comment by W4RH4WK** [comment]
Okay, it seems like I am missing something here:

My assumption is that with `formatexpr` cleared, `gq`'s behavior for reflowing a comment only depends on `formatoptions` (should comments be reflowed) and `commentstring` (how do comments start/end).

However, with the following settings reflowing works as I'd expect (note clearing the file type):

```
ft=
commentstring=<!--%s-->
formatoptions=cqrtj2
formatexpr=
```

When I now set `ft=xml` and clear `formatexpr`, I get the inconsistent indentation as described above.

What other mechanism is there, where the file type influences comment reflowing through `gq` apart from `formatexpr`?

**Comment by clason** [comment]
Look at `runtime/ftplugin/xml.vim`.

**Comment by W4RH4WK** [comment]
Okay. Thanks. Doing even more investigation, it appears that the `comments` is the relevant option here, not `commentstring`.

https://github.com/vim/vim/issues/1696 seems to be the underlying issue.
