### ISSUE TITLE
Combination of `InsertCharPre`, `defer_fn`, `stopinsert`, and `<C-n>` throws `E523` error

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#18395]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

No, it doesn't have Lua api

### Operating system/version

Xubuntu 20.04

### Terminal name/version

xfce4-terminal 0.8.9.1 (Xfce 4.14)

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

Not really sure where is the problem here, hence a long title.

Steps:
1. Create 'init_stopinsert.lua' file with the following content:
```lua
_G.type_ctrl_n = function() vim.api.nvim_input('<C-n>') end
vim.cmd([[au InsertCharPre * ++once lua vim.defer_fn(_G.type_ctrl_n, 500)]])

_G.test = function()
  vim.cmd('startinsert')
  vim.api.nvim_input('a')

  vim.defer_fn(function()
    -- -- This works
    -- vim.api.nvim_input('<Esc>')

    -- This doesn't work, throws `E523: Not allowed here` later
    vim.cmd('stopinsert')
  end, 1000)

  vim.defer_fn(function()
    -- Both ways don't work with `stopinsert`
    -- vim.api.nvim_input('i')
    vim.cmd('startinsert')
  end, 1500)
end
```
2. Run `nvim --clean -u init_stopinsert.lua`.
3. Run `:lua _G.test()`.

### Expected behavior

The same as the following manual actions with `nvim --clean -u NONE`:
1. Type `i` followed by `a`.
2. Wait for 500 ms and type `<C-n>`.
3. Wait for another 500 ms and type `<Esc>`.
4. Wait for another 500 ms and type `i`.

### Actual behavior

Actions up to final start of Insert mode seem to be executed as intended. After that, `E523: Not allowed here` is shown for a brief period of time followed by output of `<C-n>` (`-- Keyword completion (^N^P) Pattern not found` message).

As a side note, having `vim.api.nvim_input('<Esc>')` instead of `vim.cmd('stopinsert')` works as expected. Which is odd, because `:h stopinsert` quite literally says "Works like typing <Esc> in Insert mode".

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/edit.c b/src/nvim/edit.c
index 6a6d43322..c1363aeff 100644
--- a/src/nvim/edit.c
+++ b/src/nvim/edit.c
@@ -553,7 +553,7 @@ static int insert_check(VimState *state)
     Insstart_orig = Insstart;
   }
 
-  if (stop_insert_mode && !pum_visible()) {
+  if (stop_insert_mode && !compl_started) {
     // ":stopinsert" used or 'insertmode' reset
     s->count = 0;
     return 0;  // exit insert mode
```

**Comment by echasnovski** [comment]
@zeertzjq, you are a tireless wizard! Thanks!
