### ISSUE TITLE
Cannot use `Cursor` with `'winhighlight'`

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#18399]
### Neovim version (nvim -v)

a1542b091dd7b919fa8524c1c909ef897dde9299

### Vim (not Nvim) behaves the same?

N/A, Neovim-only setting

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

From source

### How to reproduce the issue

`:set winhighlight=Cursor:Cursor`

### Expected behavior

You can use `Cursor` in `winhighlight`, since it is listed in `highlight-groups`:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/5308024/166515127-0ac7d3c0-3e06-40e3-9b47-f642cbaf22c8.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/5308024/166515153-ed0bd210-2d62-478c-9f0c-1477c2ae75b6.png">

### Actual behavior

<img width="426" alt="image" src="https://user-images.githubusercontent.com/5308024/166515181-46e6a382-14e1-4449-830d-270ee292bc03.png">

NB: This is because `"Cursor"` does not appear as a value of `hlf_names` in `highlights_def.h`.

**Comment by andmis** [comment]
I looked into this a bit. A few things:

- In my Neovim, I can't get `:hi Cursor …` to actually do anything. Is this known/expected? I'm in a recent iTerm2. Neovim is doing _something_ to configure the cursor color, because if I make my cursor red in the iTerm2 preferences then it appears red in my shell, but turns white when I open Neovim. I think https://github.com/neovim/neovim/issues/6591 is related or tracks the bug if this is a bug. But anyway I cannot control my cursor color at all AFAICT.
- Is there a simple way of retrieving (from Lua) the current highlight applied to the current cursor in the current window? For example, if you `:set winhighlight=Normal:Cursor` and then `:hi Normal`, you see the definition/values of the `Normal` HL group, not the `Cursor` group -- not sure if this is as intended.
- Is there a simple way to query the HL group of the cursor from the test code? I looked at `cursor_spec.lua` a little bit but nothing jumped out at me.

I could probably make this bug go away with a small diff in the C code but I think some of the above should get resolved first.

**Comment by Arjun31415** [comment]
Hello, I would like to work on this if possible.

**Comment by sandeepkiran-js** [comment]
Hi , is this PR still open , would like to contribute .

**Comment by andmis** [comment]
Yep, it's still open.

**Comment by Arjun31415** [comment]
How would one work on this. Could you guide me to the respective files or in general how to begin working on this
