### ISSUE TITLE
Support a systemwide lua config file, sysinit.lua

### ISSUE THREAD

**Issue by nyxkrage** [neovim/neovim#18405]
### Feature already in Vim?

No

### Feature description

Since Neovim supports loading `init.lua` from the users local configuration, it would make sense to mirror this behavior for the sytemwide vimrc, `sysinit.vim`. [System-vimrc in the Neovim help](https://neovim.io/doc/user/starting.html#system-vimrc)

**Comment by clason** [comment]
I think a system wide vimrc is a footgun that does more harm than help, and I would prefer not to perpetuate that.

**Comment by justinmk** [comment]
Just call lua from sysinit.vim

This is a rare use-case and not worth adding extra documentation and options for it.
