### ISSUE TITLE
Mechanism for plugin authors to hide the cursor in floating windows

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#18401]
### Feature already in Vim?

N/A

### Feature description

As a plugin author, I would like to be able to pop up windows that (1) have focus (to accept keyboard input for mappings) and (2) have no cursor.

---

One solution could be to apply a highlight group which makes the cursor invisible by matching the background highlight.

This is a hack. For one thing, if you don't disable the cursor motion mappings, the user could (perhaps inadvertently) move the cursor into a row/column cell where the highlight is different, causing the cursor to appear.

It's also a hack by definition because what I want is "no cursor", not "an invisible cursor". I understand that the assumption that there is one ([and only one](https://github.com/neovim/neovim/issues/7257)) cursor may be baked deep into the codebase (I'm not that familiar with Vim internals so IDK). But having a dialog with no cursor is a fundamental capability that would be nice to have.

Using (just) highlights to hide the cursor in a local way (local to a particular window) is also currently not possible AFAICT due to a bug: https://github.com/neovim/neovim/issues/18399.

---

Justin suggests using `blend` in https://github.com/neovim/neovim/issues/3688, but this is not a good solution because it makes my (notional) plugin depend on global settings (the `Cursor` HL group, the `guicursor` setting).

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/is-there-a-way-to-hide-the-cursor-in-a-focused-floating-window/2098/4

**Comment by justinmk** [comment]
> if you don't disable the cursor motion mappings, the user could (perhaps inadvertently) move the cursor into a row/column cell where the highlight is different, causing the cursor to appear.

So what? There needs to be a stronger use-case. 

The flexibility of being able to navigate almost any part of the UI with the usual editor features is one of the things that sets Vim/Emacs apart from other popular applications.

**Comment by andmis** [comment]
> The flexibility of being able to navigate almost any part of the UI with the usual editor features is one of the things that sets Vim/Emacs apart from other popular applications.

Yes, but then IMHO our stance to plugin authors should be more "you generally should not do this (make the cursor disappear)" and less "here are some existing mechanisms (hacks, IMO) that allow you to approximate this". FWIW even some plugin authors are not really conscious of the "everything is a buffer" perspective and it's worth propagating.

**Comment by justinmk** [comment]
Cursor is what drives focus. "No cursor" is an architecture change. There could perhaps be an idea of "locking" the cursor, if that's not already possible, but then what about dialogs that want to scroll? Would we also remove the ability to enter `:` cmdline? That would be jarring...

**Comment by andmis** [comment]
Actually I think it could be a good thing to push a culture of "this is not a GUI, don't make dialogs like this
<img width="302" alt="image" src="https://user-images.githubusercontent.com/5308024/166675338-07a4bf25-68d4-47b7-a8bc-efdeb6fc9efe.png">
but then what I'm saying is maybe we should be a bit more forceful in encouraging plugin authors to look for alternative ways of building their dialogs.

(Modal dialogs like this with fully-custom interfaces are the main use case I can see for "no cursor", and "no cursor" is indeed totally reasonable for dialogs like this, but this dialog could also be expressed as a `Prompt: [yN] |` interaction.)

**Comment by justinmk** [comment]
> "no cursor" is indeed totally reasonable for dialogs like this

For decades you also couldn't select text in such dialogs, which was an anti-feature.

This is kind of like website authors who want to disable source code inspection, the "back" button, etc. It's a step backwards in many ways.
