### ISSUE TITLE
Different tab symbol after update to v0.8.0

### ISSUE THREAD

**Issue by mmsh1** [neovim/neovim#18402]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+121-g192488379

### Vim (not Nvim) behaves the same?

don't have any config for plain vim

### Operating system/version

Ubuntu 20.04.4 LTS x86_64

### Terminal name/version

st 0.8.4

### $TERM environment variable

st-256color

### Installation

build from repo

### How to reproduce the issue

Just open any source code file and try to make a tab. You will see │ symbol.

### Expected behavior

In my init.vim I have this line for unprintable characters:
set listchars=tab:•\ ,trail:•,extends:»,precedes:« 

So the expected char for tab is •

### Actual behavior

When I open nvim without editing any existing file, it works just fine and the tab symbol is •.
But if I try to edit any source code file (I tried with .go, .c files and init.vim itself), the tab symbol is │.
It occured after update to last version. There is no such problems with my previous nvim build (NVIM v0.4.3)

**Comment by clason** [comment]
You skipped quite a few versions there...

Can you please check _which_ version introduced the change?

**Comment by zeertzjq** [comment]
And you didn't have minimal steps to reproduce with `nvim --clean`

**Comment by justinmk** [comment]
Can reopen if repro steps are provided.

**Comment by jamessan** [comment]
> But if I try to edit any source code file (I tried with .go, .c files and init.vim itself), the tab symbol is │.

The first step to debugging this sort of thing is to verify that the last place which set the option -- `:verbose set lcs?` -- is what you expect.

**Comment by mmsh1** [comment]
> And you didn't have minimal steps to reproduce with `nvim --clean`

Yes, because there are no any symbols for tabs or spaces in default nvim and this experiment won't say anything about this problem.

**Comment by clason** [comment]
You can still do `nvim --clean -u minimal.vim` to _only_ load the provided config.

**Comment by mmsh1** [comment]
> > But if I try to edit any source code file (I tried with .go, .c files and init.vim itself), the tab symbol is │.
> 
> The first step to debugging this sort of thing is to verify that the last place which set the option -- `:verbose set lcs?` -- is what you expect.

Thank you for answer. Result of this command: 
  listchars=tab:• ,trail:•,extends:»,precedes:«
        Last set from ~/.config/nvim/init.vim line 42

In init.vim on line 42 I have:
set listchars=tab:•\ ,trail:•,extends:»,precedes:«

**Comment by clason** [comment]
And is that after opening a `.go` file?

**Comment by mmsh1** [comment]
> And is that after opening a `.go` file?
Yes, I have the same result all the time. No matter if I open `.go`, `.c` file or just open nvim without editing existing file.

**Comment by clason** [comment]
If you don't provide a minimal(!) reproducible example we can test with `nvim --clean -u minimal.vim`, there's nothing we can do.

**Comment by zeertzjq** [comment]
How did you open these files?

**Comment by zeertzjq** [comment]
And does `:ls` show any files before you open any files?

**Comment by zeertzjq** [comment]
Do you have some indentline plugin installed?

**Comment by mmsh1** [comment]
> Do you have some indentline plugin installed?

I'm trying to understand if any of my plugins can change indents. But it looks like they have nothing to do with it.
Here is my plugins list:
```
call plug#begin('~/.config/nvim/plugged')

Plug 'dense-analysis/ale'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'jeffkreeftmeijer/vim-numbertoggle'
Plug 'luochen1990/rainbow'• •   " Brackets highlight
Plug 'morhetz/gruvbox'• •   •   " Main highlight
Plug 'ms-jpq/chadtree', {'branch': 'chad', 'do': 'python3 -m chadtree deps'}
Plug 'sheerun/vim-polyglot'
Plug 'vim-airline/vim-airline'• " Status bar

call plug#end()                 " required
filetype plugin indent on       " required
```

**Comment by zeertzjq** [comment]
This is really strange, as none of these plugins seem to change `'listchars'`.
