### ISSUE TITLE
clangd based lsp cannot find "nested" include files

### ISSUE THREAD

**Issue by JacekHoleczek** [neovim/neovim#18412]
### Neovim version (nvim -v)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@fv-az87-780

### Language server name/version

clangd 14.0.0

### Operating system/version

Linux x86_64

### Steps to reproduce using "nvim -u minimal_init.lua"

I am having problems in NVIM with "#include" files that are "not found".

Please find below a minimal "reproducer".

```bash
mkdir -p /tmp/trial/include/XY /tmp/trial/src
echo -e '#include "XY/Y.hxx"' > /tmp/trial/include/XY/X.hxx
touch /tmp/trial/include/XY/Y.hxx # can be completely empty
cd /tmp/trial/src
echo -e '--language=c++\n-I/tmp/trial/include' > compile_flags.txt
echo -e '#include "XY/X.hxx"\nint main() {return 0;}' > main.cxx
clangd --check=main.cxx # no problems here
nvim main.cxx # try to "gd" or "gD" for "XY/X.hxx"
```

While editing the "`main.cxx`" file, when one executes "gd" or "gD" (i.e. "vim.lsp.buf.definition" or "vim.lsp.buf.declaration") for the included `"XY/X.hxx"` file, it will open this file but then it immediately reports an error:
`'XY/Y.hxx' file not found`

### Actual behavior

clangd based lsp cannot find "nested" include files

### Log file

https://gist.github.com/JacekHoleczek/55a6e58d47b538b22abf028c7292a7d1

**Comment by zeertzjq** [comment]
Moving the `compile_flags.txt` from `/tmp/trial/src/` to `/tmp/trial/` fixes the problem. I think `/tmp/trial/src/compile_flags.txt` doesn't apply to files under `/tmp/include/`?

**Comment by JacekHoleczek** [comment]
I'm sorry but this cannot be done for "real applications". The "#include" directories are not user-writable (and will contain many different "packages", e.g. it could be "`/usr/local/include/...`").

**Comment by clason** [comment]
Surely that is an issue with `clangd`, not Neovim?

**Comment by JacekHoleczek** [comment]
I can only say that "`clangd --check=main.cxx`" finds everything it expects (in all my various "trials").

**Comment by clason** [comment]
Yeah, but that is not `clangd` acting as an LSP server, is it? From the help:

>   --check[=<string>]                - Parse one file in isolation **instead of acting as a language server**. Useful to investigate/reproduce crashes or configuration problems. With --check=<filename>, attempts to parse a particular file.

**Comment by JacekHoleczek** [comment]
So, it is just another emanation of the known [clang problems "when opening headers outside of my project directory"](https://clangd.llvm.org/faq#how-do-i-fix-errors-i-get-when-opening-headers-outside-of-my-project-directory).
The solution is to enforce "`--compile-commands-dir=/tmp/trial/src`" when the `clangd` executable is called.
The given directory must be an "absolute path" to where the "`compile_flags.txt`" or "`compile_commands.json`" exist.
Unfortunately, I do not see any foreseen option for it in the chain `NVIM` -> its-builtin-LSP -> `nvim-lspconfig` -> `clangd` server call.

**Comment by mjlbach** [comment]
> Unfortunately, I do not see any foreseen option for it in the chain NVIM -> its-builtin-LSP -> nvim-lspconfig -> clangd server call.

I'm not sure I understand, if all you want to do is add `--compile-commands-dir=/tmp/trial/src` as a flag to the launch command for clangd, why not just override the `cmd` in lspconfig to add the additional argument?

**Comment by lewis6991** [comment]
This is a server problem. Doesn't belong in this tracker.
