### ISSUE TITLE
Provide tab completion (autocompletion) for search with / command

### ISSUE THREAD

**Issue by winkee01** [neovim/neovim#18424]
### Feature already in Vim?

No

### Feature description

When typing `/` in Normal mode, we enter search mode, I can use **`CTRL-L`** to auto-complete the word, or we can use `CTRL-g` or `CTRL-t` to jump matching highlight back and forth in candidates.

but an unfortunate thing is that I can't use **`<Tab>`** key to do the auto-completion, if I type **`<Tab>`**, it will just be replaced with `^I`, which makes it impossible to auto-complete.

<img width="589" alt="CleanShot 2022-05-05 at 14 20 57@2x" src="https://user-images.githubusercontent.com/49930785/166871824-f02e7988-4458-4871-a48b-4b54df7b8157.png">

Can we implement this feature in nvim? because like `ctrl-n` and `ctrl-p` and other auto-completion keys, they both can do the job, and it is very reasonable that we should be able to use **`<Tab>`** or other keys to achieve the same thing.

Thank you!

**Comment by clason** [comment]
What if you want to search for tabs?

In your own config, you can always `cnoremap <tab> <c-l>`.

**Comment by winkee01** [comment]
> What if you want to search for tabs?
> 
> In your own config, you can always `cnoremap <tab> <c-l>`.

How can that be equal? c-l feed one char only at a time, they are not the same thing at all. and what you mean by search for tabs? if you want to seach for tab, you can always escape key.

**Comment by Shougo** [comment]
Hm.  `c_CTRL-L` is not same with auto completion.
@winkee01 says open `wildmenu` completion feature like other command line mode.

**Comment by clason** [comment]
That's not how I read it, though, and would be a much more significant change that I believe should be requested in Vim first -- that way, we can port it, and both projects profit.

**Comment by winkee01** [comment]
@Shougo exactly, and I think `c_CTRL-L` shouldn't exist at all, hardly find any use case for that, and I believe `<Tab>` key does not have any problem to work as a completion trigger key in such situation, and many other keys also should be able to trigger `wildmenu` shown.

**Comment by juniway** [comment]
why did this guy close the issue? I think it's a legitimate feat request, even if him wants to leave it for the vim team to implement.
