### ISSUE TITLE
--api-info output documentation

### ISSUE THREAD

**Issue by osa1** [neovim/neovim#1842]
I know the API is subject to changes and that's why it's not documented. However, at least documentation of some keys used in `--api-info` output would be great. For example, looking at the `--api-info` output, I can't see what do `error_types` and `deferred` fields mean and this is making implementing RPC API in my language of choice impossible.

**Comment by justinmk** [comment]
Having an auto-generated document will probably happen at some point.

**Comment by osa1** [comment]
Just to clarify: I'm not asking for RPC API function documentations. I'm asking for keys used in `--api-info` msgpack output. This should stay same even when API changes so why not document those?

To be more specific: I'm trying to implement the RPC API in another language but I'm stuck because I don't know what does `error_types` and `deferred` fields mean.
