### ISSUE TITLE
Can't resize split windows using mouse drag

### ISSUE THREAD

**Issue by Hettomei** [neovim/neovim#1845]
Hi all,

I compiled commit #c7f4e55 but after ```make && make install``` I cannot redimension windows with my mouse
The last known commit wich I can redim windows was #6bfe0da

Here is an example of my vimrc that can be related : 

```
if has('mouse')
  set mouse=a
endif

"Fix bug : mouse before cannot go to 220 char to the right
"This fix it
"https://code.google.com/p/iterm2/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&groupby=&sort=&id=1830
if has('mouse_sgr')
  set ttymouse=sgr
endif
```
But if I type
```
:vertical resize +5
```
It will resize, it seems to be only with the mouse

Thank you for what you have done, Ciao.

**Comment by Hettomei** [comment]
I m sorry I didn't tested this : 

If I remove 
```
if has('mouse_sgr')
  set ttymouse=sgr
endif
```
Everything works well, and their is no more problem with " "Fix bug : mouse before cannot go to 220 char to the right "

I close this bug.

**Comment by justinmk** [comment]
Maybe we should remove `mouse_sgr` so that `has('mouse_sgr')` returns false.

**Comment by Hettomei** [comment]
I have no idea what is mouse_sgr
But I said :+1: for your proposition

**Comment by Pyrohh** [comment]
It doesn't look like instances of `mouse_*` and `FEAT_MOUSE_*` are hooked up to much of anything, besides some multi-clause ifdefs in `term.c`. It looks like this was going to be done in #500 but it wasn't followed up on, so I assume it's okay to remove these.

**Comment by cvlmtg** [comment]
Removing mouse_sgr is wrong imho. The xterm mouse protocol cannot recognize more than 223 columns. mouse_sgr works in vim, so neovim implementation is not useless, just bugged :)

**Comment by tarruda** [comment]
FWIW this and most terminal options will be no-ops after #1820. @Hettomei can you compile and test #1820? I'm interested in checking if the new UI fixes your problem.

**Comment by Hettomei** [comment]
@tarruda (oh my god the number of branch you have in your repo O_O how you remember which one do what ?)

So after compiling branch tickit-ui

With or without ```if has('mouse_sgr')``` I can click every where (including after 223 char on a line.)

(I checked on vim 7.4.488 and without (mouse_sgr) click doesn't work at all)

**Comment by Pyrohh** [comment]
This could probably be closed now.
