### ISSUE TITLE
E825: Corrupted undo file

### ISSUE THREAD

**Issue by ndavd** [neovim/neovim#18454]
Hi,

On Arch, I get `E825: Corrupted undo file` on opening most (all?) files that have an undo file. It also happens with `nvim -u NONE -i NONE +'set undofile' $file`.

This happens on master and was introduced in 21a31ea9294ef923a9d258c668d2864f4409cf1c.

Switching back to 21a31ea9294ef923a9d258c668d2864f4409cf1c^ makes the issue go away again, so I figure that a function that reads the undo file was subtly changed in that commit above.

If you think it would be helpful, I can provide a file and the corresponding undo file that is known to be corrupt.

**Comment by zeertzjq** [comment]
Can you check if #18455 fixes this?

**Comment by ndavd** [comment]
Sorry for the late reply,
Yup it does, thanks!
