### ISSUE TITLE
LSP servers should not launch attached to TTY

### ISSUE THREAD

**Issue by gotgenes** [neovim/neovim#18475]
### Neovim version (nvim -v)

0.7.0

### Language server name/version

pyright 1.1.245

### Operating system/version

macOS 12.3.1

### Steps to reproduce using "nvim -u minimal_init.lua"

Use `nvim -u minimal_init.lua file.py`, allow packer to install lsp-config, quit, and re-run `nvim -u minimal_init.lua file.py`.

### Expected behavior

LSP servers should launch in a way that they are not attached to the TTY that Neovim is attached to. In this case `pyright-langserver` would not show an attached TTY

```
$ ps Ao ppid,pid,pgid,gid,tty,command
PPID   PID  PGID   GID TTY      COMMAND
[…]
30183  1030  1030    20 ttys001  -zsh
 1030 13203 13203    20 ttys001  nvim -u /Users/chris/minimal_init.lua convert_chase.py
13203 13207 13203    20 ??       node /opt/homebrew/bin/pyright-langserver --stdio
[…]
```

This issue was discovered via [a discussion in Kitty](https://github.com/kovidgoyal/kitty/discussions/4869). From [this reply](https://github.com/kovidgoyal/kitty/discussions/4869#discussioncomment-2496963)

>When you launch a daemon (background) process in unix you should detach it from its environment, including the controlling tty. An editor running in a terminal needs exclusive control over the tty, otherwise other processes can change tty state behind its back, leading to corruption. Therefore, a well designed editor should call setsid before execing binaries that it does not expect to write to the \*TTY\*.

My best understanding is that [when the LSP process is launched](https://github.com/neovim/neovim/blob/c618b314c6a266806edf692122b16ba9ff7a8e10/runtime/lua/vim/lsp/rpc.lua#L327) the [spawn params](https://github.com/neovim/neovim/blob/c618b314c6a266806edf692122b16ba9ff7a8e10/runtime/lua/vim/lsp/rpc.lua#L319-L322) should include `detached = true`, based on the [luv docs](https://github.com/luvit/luv/blob/master/docs.md#uvspawnpath-options-on_exit) and [libuv docs](http://docs.libuv.org/en/v1.x/guide/processes.html#detaching-processes). I believe this means that it will also be Neovim's responsibility to call [`handle:process_kill`](https://github.com/luvit/luv/blob/master/docs.md#uvprocess_killprocess-signum) to shut down the language server, but I'm uncertain how and where this should happen.

This is my best guess at what could be done. The maintainer of Kitty had [these recommendations](https://github.com/kovidgoyal/kitty/discussions/4869#discussioncomment-2424674), but I don't yet see how they correspond to operations in luv:

>Your LSP server process should be calling setsid() so that it is not associated with the original tty. Indeed neovim should in general be calling setsid() after forking when execing processes it does not expect to output to/input from the tty.

And later also [these recommendations](https://github.com/kovidgoyal/kitty/discussions/4869#discussioncomment-2497578):

>Oh and if neovim for some reason doesnt want to cleanup its child processes itself, preferring to rely on SIGHUP, then rather than using setsid() it should instead background them (like running bg in a shell) which it can do by using setpgid() in the forked process and tcsetpgrp() in the parent process.

### Actual behavior

Language servers are launched attached to the TTY:

```
$ ps Ao ppid,pid,pgid,gid,tty,command
PPID   PID  PGID   GID TTY      COMMAND
[…]
30183  1030  1030    20 ttys001  -zsh
 1030 13203 13203    20 ttys001  nvim -u /Users/chris/minimal_init.lua convert_chase.py
13203 13207 13203    20 ttys001  node /opt/homebrew/bin/pyright-langserver --stdio
[…]
```

Here we see pyright is attached to `ttys001`, the same TTY that Neovim is attached to.

**Comment by gpanders** [comment]
>My best understanding is that [when the LSP process is launched](https://github.com/neovim/neovim/blob/c618b314c6a266806edf692122b16ba9ff7a8e10/runtime/lua/vim/lsp/rpc.lua#L327) the [spawn params](https://github.com/neovim/neovim/blob/c618b314c6a266806edf692122b16ba9ff7a8e10/runtime/lua/vim/lsp/rpc.lua#L319-L322) should include detached = true, based on the [luv docs](https://github.com/luvit/luv/blob/master/docs.md#uvspawnpath-options-on_exit) and [libuv docs](http://docs.libuv.org/en/v1.x/guide/processes.html#detaching-processes).

I agree with this assessment. This should be a simple fix -- Neovim already takes care of shutting down the process on exit.

**Comment by gotgenes** [comment]
@gpanders Thank you! Much appreciated.
