### ISSUE TITLE
feedkeys does not work in headless mode

### ISSUE THREAD

**Issue by ipod825** [neovim/neovim#18471]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+31-g6c8a3013a

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

debian

### Terminal name/version

Irrelevant

### $TERM environment variable

Irrelevant

### Installation

appimage

### How to reproduce the issue

nvim --headless -c 'call feedkeys("iabc") | echo getline(1) | quit!'

### Expected behavior

See terminal ouptut "abc".

### Actual behavior

No terminal outputs.
This applies even if we replace `feedkeys("iabc")` with `nvim_feedkeys("iabc", "n", v:false)`.
However,  `nvim_buf_set_lines` will work and the following command give the correct output:
`nvim --headless -c 'call nvim_buf_set_lines(0, 0, -1, v:true, ["abc"]) | echo getline(1) | quit!'`

**Comment by zeertzjq** [comment]
Use `feedkeys("iabc", "x")`
