### ISSUE TITLE
Folds are not drawn when a file is opened in insert mode

### ISSUE THREAD

**Issue by octaltree** [neovim/neovim#18479]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+157-g0d3f17a6c3

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 30 2022 23:54:07)

### Operating system/version

5.10.109-1-MANJARO #1 SMP PREEMPT Mon Mar 28 09:16:20 UTC 2022 x86_64

### Terminal name/version

alacritty 0.11.0-dev (5c51d528)

### $TERM environment variable

tmux-256color

### Installation

aur/neovim-git

### How to reproduce the issue

1. nvim --clean -u min.vim
2. Execute one of those mapping in insert mode

min.vim
```vim
set nocompatible

" folds comments. Implementation is irrelevant
function! MyFold(lnum) abort
  let line = getline(a:lnum)
  if line ==# ''
    return '='
  endif
  let matched = matchlist(line, '^\(\s*\).*')[1]
  let indent = len(matched) / 2
  let is_comment = match(line, '^\(\s*\)//') > -1
  if is_comment
    return indent + 1
  endif
  return !!indent
endfunction

au BufNewFile,BufRead *.c setf c
au FileType c setlocal foldmethod=expr foldexpr=MyFold(v:lnum)

function! Open() abort
  stopinsert
  e min.c
endfunction

function! Open2() abort
  call feedkeys("\<ESC>", "n")
  e min.c
endfunction

inor <buffer>a <cmd>e min.c<CR>
inor <buffer>b <cmd>stopinsert<CR><cmd>e min.c<CR>
inor <buffer>c <cmd>call Open()<CR>
inor <buffer>d <cmd>call Open2()<CR>
```
min.c
```c
#include<stdio.h>

// foo
// bar
int main(void){
  return 0;
}
````

### Expected behavior

The fold should also be drawn when the file is opened in insert mode.

### Actual behavior
Not drawn when insert mode and foldmethod=expr.
| |vim|nvim|
|-|---|----|
|a|folded|NOT folded|
|b|folded|folded|
|c|folded|NOT folded|
|d|folded|NOT folded|

I tried tracing after do_exedit, but it was unexplainable to me.

**Comment by octaltree** [comment]
If it is not folded when opened it's worthless to me. Can you give me a snippet to schedule the drawing when the mode is changed to normal?

**Comment by justinmk** [comment]
what's wrong with doing `stopinsert` in the mapping, then re-entering insert mode?

**Comment by octaltree** [comment]
I understand that this can be achieved with
```
<cmd>stopinsert<CR><cmd>call myfunc<CR><cmd>startinsert<CR>
```
or
```
function! Open3() abort
  stopinsert
  e min.c
  au ModeChanged * ++once e %
endfunction

inor <buffer>e <cmd>call Open3()<CR>
```
I think I can manage to use it.

By the way, it seems that folds are not created in redraw. After executing a,c,d, manual :redraw does not draw fold.
