### ISSUE TITLE
`nvim_command` and `nvim_echo` set `v:errmsg`

### ISSUE THREAD

**Issue by famiu** [neovim/neovim#18481]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+97-g65b4bf055

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Fedora 36 BETA

### Terminal name/version

GNOME Terminal 3.44.0

### $TERM environment variable

xterm-256color

### Installation

Build from repo

### How to reproduce the issue

1. `:call nvim_exec("echo foo", 0)` or `:call nvim_command("echo foo")`
2. `:echo v:errmsg`

### Expected behavior

`v:errmsg` is empty, because the docs specify that `nvim_command()` and `nvim_exec()` do not update `v:errmsg`

### Actual behavior

`v:errmsg` is updated

**Comment by justinmk** [comment]
I think the doc needs to be updated. Sourcing a whole script in nvim_exec without updating v:errmsg seems a bit weird. `nvim_command` will be deprecated.
