### ISSUE TITLE
E5112:  invalid escape sequence

### ISSUE THREAD

**Issue by nobodyatandnothing** [neovim/neovim#18488]
### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

no, all vimscript

### Operating system/version

linux

### Terminal name/version

foot version: 1.12.1 +pgo +ime +graphemes -assertions

### $TERM environment variable

foot-extra

### Installation

manjaro

### How to reproduce the issue

`init.lua`:
```lua
vim.api.nvim_create_autocmd('InsertEnter',
  { desc = 'Enable IME when entering insert mode.',
  callback = vim.fn.chansend(vim.v.stderr, "\e[?737769h") })
vim.api.nvim_create_autocmd('InsertLeave',
  { desc = 'Disable IME when leaving insert mode.',
  callback = vim.fn.charsend(vim.v.stderr, "\e[?737769l") })
```

### Expected behavior

load init.lua on startup

### Actual behavior

E5112:  invalid escape sequence

**Comment by nobodyatandnothing** [comment]
whether it is a valid escape sequence is none of your business. i shall send to my terminal what i shall send to my terminal.

it is a valid escape sequence. https://codeberg.org/dnkl/foot/wiki#user-content-enabling-disabling-ime-when-entering-leaving-insert-mode-in-vim

**Comment by zeertzjq** [comment]
Lua doesn't support `\e`, use `\022` instead.

**Comment by zeertzjq** [comment]
Oops it was `\027`

**Comment by zeertzjq** [comment]
You are also not passing a callback correctly. The correct way should be:
```lua
vim.api.nvim_create_autocmd('InsertEnter',
  { desc = 'Enable IME when entering insert mode.',
  callback = function() vim.fn.chansend(vim.v.stderr, "\027[?737769h") end })
vim.api.nvim_create_autocmd('InsertLeave',
  { desc = 'Disable IME when leaving insert mode.',
  callback = function() vim.fn.chansend(vim.v.stderr, "\027[?737769l") end })
```

**Comment by dnkl** [comment]
>   callback = function() vim.fn.chansend(vim.v.stderr, "\027[?737769h") end })

`\033`, or `\x1b`, but **not** `\027`.

**Comment by gpanders** [comment]
> > callback = function() vim.fn.chansend(vim.v.stderr, "\027[?737769h") end })
> 
> `\033`, or `\x1b`, but **not** `\027`.

I couldn't quite believe this when I first saw it, but Lua uses `\0` prefix for decimal notation.

```lua
print("\033")
```

prints a bang (`!`) character, which is 33 (decimal) in ASCII. All that is to say that `\027` is, in fact, correct.

**Comment by nobodyatandnothing** [comment]
> You are also not passing a callback correctly. The correct way should be:
> 
> ```lua
> vim.api.nvim_create_autocmd('InsertEnter',
>   { desc = 'Enable IME when entering insert mode.',
>   callback = function() vim.fn.chansend(vim.v.stderr, "\027[?737769h") end })
> vim.api.nvim_create_autocmd('InsertLeave',
>   { desc = 'Disable IME when leaving insert mode.',
>   callback = function() vim.fn.chansend(vim.v.stderr, "\027[?737769l") end })
> ```
thank you
