### ISSUE TITLE
unknown conversion type character 'z' in format (msys2)

### ISSUE THREAD

**Issue by kylo252** [neovim/neovim#18495]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+8658e82

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MINGW64_NT-10.0-20348

### Terminal name/version

Windows Terminal v1.13.10984.0

### $TERM environment variable

xterm-256color

### Installation

build from source

### How to reproduce the issue

build with mingw64 toolchain using these instructions https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msys2--mingw

### Expected behavior

Either turn off `-Wformat` or handle the fact that it's missing from `/mingw64/bin/gcc`

semi related #4582

### Actual behavior

The build logs from msys2 are 30k lines long, _yes 30,000 lines ..._, because of these warnings coming from every reference to `WLOG`.

**Comment by kylo252** [comment]
since MSVCRT isn't C99 compatible, I had figured that I just need to switch to another toolchain which uses UCRT, so I did some tests in  [docker container](https://gist.github.com/kylo252/ba8cc89e7e64b90cff4653674a6c160b)

The third-party target __seems__ to build without errors, but then you hit an error about `lpeg` not being found, probably because `LUA_CPATH` needs to be set explicitly for this to work.

what's worse, is how `luarocks` is mixing path separators

<details>
<summary>luarocks' build summary</summary>

```console
You may want to add the following elements to your paths;
Lua interpreter;
  PATH     :   C:/msys64/tmp/neovim/.deps/usr/bin
  PATHEXT  :   .LUA
LuaRocks;
  PATH     :   C:/msys64/tmp/neovim/.deps/usr/luarocks
  LUA_PATH :   C:/msys64/tmp/neovim/.deps/usr/luarocks\lua\?.lua;C:/msys64/tmp/neovim/.deps/usr/luarocks\lua\?\init.lua
Local user rocktree (Note: %APPDATA% is user dependent);
  [...]
System rocktree
  PATH     :   C:/msys64/tmp/neovim/.deps/usr/bin
  LUA_PATH :   C:/msys64/tmp/neovim/.deps/usr/bin/lua\?.lua;C:/msys64/tmp/neovim/.deps/usr/bin/lua\?\init.lua
  LUA_CPATH:   C:/msys64/tmp/neovim/.deps/usr/bin\?.dll
```

</details>


---

Note: I couldn't even manage to build `libtree-sitter` with clang64 because of a linker issue regarding using `lld` with `-soname`, although the same flag work on native Linux

> LLD is faster than LD, but does not support all the features LD supports

<details>
<summary>clang's link error</summary>


```console
$ clang -v -shared -Wl,-soname,libtree-sitter.so.0 lib/src/alloc.o lib/src/get_changed_ranges.o lib/src/language.o lib/src/lexer.o lib/src/node.o lib/src/parser.o lib/src/query.o lib/src/stack.o lib/src/subtree.o lib/src/tree.o lib/src/tree_cursor.o  -
o libtree-sitter.so.0.0
clang version 14.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clang64/bin
 "C:/msys64/clang64/bin/ld.lld" -m i386pep --shared -Bdynamic -e DllMainCRTStartup --enable-auto-image-base -o libtree-sitter.so.0.0 C:/msys64/clang64/lib/dllcrt2.o C:/msys64/clang64/lib/crtbegin.o -LC:/msys64/clang64/x86_64-w64-mingw32/lib -LC:/msys64/clang64/lib -LC:/msys64/clang64/x86_64-w64-mingw32/sys-root/mingw/lib -LC:/msys64/clang64/lib/clang/14.0.0/lib/windows -soname libtree-sitter.so.0 lib/src/alloc.o lib/src/get_changed_ranges.o lib/src/language.o lib/src/lexer.o lib/src/node.o lib/src/parser.o lib/src/query.o lib/src/stack.o lib/src/subtree.o lib/src/tree.o lib/src/tree_cursor.o -lmingw32 C:/msys64/clang64/lib/clang/14.0.0/lib/windows/libclang_rt.builtins-x86_64.a -lunwind -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 C:/msys64/clang64/lib/clang/14.0.0/lib/windows/libclang_rt.builtins-x86_64.a -lunwind -lmoldname -lmingwex -lmsvcrt -lkernel32 C:/msys64/clang64/lib/crtend.o
lld: error: unknown argument: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

</details>

**Comment by justinmk** [comment]
Conclusion from https://github.com/neovim/neovim/issues/18551 is that we will remove msys2 / mingw CI.
