### ISSUE TITLE
multiple functionaltests failures when using bash inside msys2 (windows)

### ISSUE THREAD

**Issue by kylo252** [neovim/neovim#18494]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+8658e82

### Vim (not Nvim) behaves the same?

NA (?)

### Operating system/version

MINGW64_NT-10.0-20348

### Terminal name/version

Windows Terminal v1.13.10984.0

### $TERM environment variable

xterm-256color

### Installation

build from source

### How to reproduce the issue

this will hang without exiting

```sh
# make functionaltest
make functionaltest TEST_FILE=test/functional/terminal/ex_terminal_spec.lua
```

this was also confirmed using a clean install using a [docker container](https://gist.github.com/kylo252/ba8cc89e7e64b90cff4653674a6c160b)

<details>
<summary>Dockerfile</summary>

```dockerfile
# escape=`
# select as base image matching your host to get process isolation
FROM mcr.microsoft.com/windows/servercore:ltsc2022

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# see https://www.msys2.org/docs/package-naming/
ARG flavor=mingw64
ARG target=x86_64

RUN " `
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; `
    Invoke-WebRequest -UseBasicParsing -uri "https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe" -OutFile msys2-installer.exe; `
    .\msys2-installer.exe -y -oC:\ ; `
    Remove-Item msys2-installer.exe ; `
    function msys() { C:\msys64\usr\bin\bash.exe @('-lc') + @Args; }; `
    msys ' ';"

RUN " `
    [Environment]::SetEnvironmentVariable('PATH', 'C:\msys64\usr\bin;' + $env:Path, 'Machine'); `
    function msys() { C:\msys64\usr\bin\bash.exe @('-lc') + @Args; }; `
    msys 'pacman --needed --noprogressbar --noconfirm -Syuu'; `
    msys 'pacman --needed --noprogressbar --noconfirm -Syuu'; `
    msys 'pacman --needed --noprogressbar --noconfirm -S mingw-w64-${target}-{toolchain,cmake,ninja,ccache}'; `
    msys 'pacman --noconfirm -Scc'; "

RUN " `
    $vars=@{`
      'MSYS2_PATH_TYPE' = 'inherit'; `
      'PATH' = 'C:\msys64\usr\bin;' + $env:Path;`
      'MSYSTEM' = ($env:flavor).toUpper();`
    };`
    foreach ($v in $vars.Keys) { `
      [Environment]::SetEnvironmentVariable("$v", "$vars[$v]", 'Machine'); `
    }"

CMD ["bash", "-l"]
```

</details>

See also https://github.com/neovim/neovim/pull/18389

### Expected behavior

It seems to me that the tests have probably never been run using bash from msys2, and in that case, the failing tests should be marked as failing, until they are addressed.

### Actual behavior

Failing tests that are otherwise passing on other platforms (including powershell on an msys2 build)

**Comment by justinmk** [comment]
Conclusion from https://github.com/neovim/neovim/issues/18551 is that we will remove msys2 / mingw CI.
