### ISSUE TITLE
Support `:checkhealth` modules in languages compiled to Lua

### ISSUE THREAD

**Issue by datwaft** [neovim/neovim#18508]
### Feature already in Vim?

No

### Feature description

Hello!

As you can see on https://github.com/rktjmp/hotpot.nvim/issues/58 I tried to create a health module for the `:checkhealth` command using Hotpot and Fennel (for my Neovim configuration, not a plugin) but found an issue that makes it impossible to do it fully on Fennel.

It seems that as `:checkhealth` doesn't use `require` it doesn't pass through Hotpot. Additionally, even if I force Hotpot to make the file it doesn't seem to load it.

I don't know which would be the best approach for this. In https://github.com/rktjmp/hotpot.nvim/issues/58#issuecomment-1121360842 you can see some insights from @rktjmp about the issue.

**Comment by rktjmp** [comment]
Just want to say the comment in that issue was made with only a quick grep for `checkhealth`, I don't want to misrepresent how the core loads checkhealth files, but it did seem to hit the same "autoload files" codepath which AFAIK loads lua code directly since stuff like `ftplugins` (understandably) isn't in the lua `package.path` so require wont ever work for that.

IMO, _guessing_ how it works now by searching the RTP for anything that matches "health.lua" or "health/init.lua" is probably the best method.

Possibly the checkhealth functionality could be extended with a registration hook for non-standard setups (i.e `vim.api.add_health_check("my_plugin_id", "my.module.name")` or something).

> Additionally, even if I force Hotpot to make the file it doesn't seem to load it.

Can you post back on the original Hotpot issue  with what you mean by this? I thought regular lua file was working?

**Comment by justinmk** [comment]
> It seems that as `:checkhealth` doesn't use `require` it doesn't pass through Hotpot.

Could certainly be changed. `:checkhealth` was migrated to Lua from its old Vimscript impl, but maybe there is some remaining tech debt?

**Comment by justinmk** [comment]
why...?

**Comment by muniter** [comment]
> Would it be reasonable to add one or a collection of `CheckHealth` events?

I think a better approach is your previous comment on providing a way to register healthchecks. 

Currently the health module can be accessed at `vim.health`  perhaps a new method `vim.health.register(name, func)` and wire up the discovery and completion accordingly.

**Comment by justinmk** [comment]
registries are an extra complication. What is wrong with the current convention-based, passive approach?

Each plugin has a name that it owns. Even an ftplugin named `hotpot` owns the `lua/hotpot` namespace, as well as `plugin/hotpot`. What is wrong with creating `lua/hotpot/health.lua` ?

**Comment by datwaft** [comment]
The main issue is that language that compile to Lua are not able to easily create health modules without workarounds (cannot create a configuration using purely Fennel, for example), but as you said there are easy workarounds and so this issue is not really that important.

It's mainly a quality of life feature than something really necessary.

For the future, if anyone finds this issue looking for a way to use Hotpot or any Lua-compile language for health modules, the workaround is creating the `health.lua` file and requiring from it the files created in the other language (e.g. Fennel).

Additionally, I think this is not an issue with plugins like Aniseed, as they compile into Lua directly every file and place them on the proper directories.

**Comment by justinmk** [comment]
> The main issue is that language that compile to Lua are not able to easily create health modules without workarounds (cannot create a configuration using purely Fennel, for example), but as you said there are easy workarounds and so this issue is not really that important.

After several comments in this issue, the case hasn't been clearly explained. What is the problem with creating a small `lua/.../health.lua` that points to a full fennel implementation? How does this affect QoL?

Introducing a registry mechanism or special events--complicating or abandoning the existing plugin model--needs a strong reason.

**Comment by datwaft** [comment]
> Introducing a registry mechanism or special events--complicating or abandoning the existing plugin model--needs a strong reason.

I agree!

I created this issue because I wanted to be able to create health modules without using Lua or Vimscript but directly from Fennel, like I currently can't create `after/filetype` plugins directly from Fennel but need a need a workaround (using `require` from the Lua file).

If the solution for this issue is too complex I agree that it's preferable to continue using the current workarounds.
