### ISSUE TITLE
Add `date` to `Compiled by USERNAME@HOSTNAME` byline

### ISSUE THREAD

**Issue by kdheepak** [neovim/neovim#18505]
### Feature already in Vim?

No

### Feature description

Currently `Compiled by USERNAME@HOSTNAME` is added to the version output:

https://github.com/neovim/neovim/blob/03471e292d48283379a397dadf902572de91b359/src/nvim/version.c#L2160-L2168

It would be nice to have it be this instead:

`Compiled by USERNAME@HOSTNAME on 2022-05-09T10:11:12Z`

Thoughts?

**Comment by gpanders** [comment]
This makes builds [non-reproducible](https://reproducible-builds.org) and is generally speaking not a good idea.

You are of course free to add whatever you want if you build from source, however. Just set the `HOSTNAME` environment variable when you build:

```shell
HOSTNAME="$(hostname) at $(date)" make clean nvim
```

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/15424

**Comment by kdheepak** [comment]
Thanks for the suggestion!
