### ISSUE TITLE
WinEnter/WinLeave: provide window info in v:event autocmd args

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#18500]
### Feature already in Vim?

N/A

### Feature description

We should include the window information in the args table passed to `WinEnter` and especially `WinLeave` autocmd Lua function callbacks. Without this I don't think there is a straightforward way to get the window ID in the `WinLeave` CB (if the buffer IDs are the same, say).

```
vim.api.nvim_create_autocmd('WinEnter', {
  pattern = '*',
  callback = function(args) vim.pretty_print(args) end,
})
vim.api.nvim_create_autocmd('WinLeave', {
  pattern = '*',
  callback = function(args) vim.pretty_print(args) end,
})
```

Current result:

```
{
  buf = 10,
  event = "WinLeave",
  file = "/Users/mishchea/dotfiles/nvim/init.vim",
  id = 14,
  match = "/Users/mishchea/dotfiles/nvim/init.vim"
}
{
  buf = 3,
  event = "WinEnter",
  file = "/Users/mishchea/local/share/nvim/runtime/doc/options.txt",
  id = 13,
  match = "/Users/mishchea/local/share/nvim/runtime/doc/options.txt"
}
```

**Proposal:** Include `win = win_id` in the `args` CB for those events. I haven't checked `WinEnter`, `WinScrolled`, etc., but this probably also applies to them.

**Comment by clason** [comment]
And specifically, the proposal or PR should address the generic case; we can't and don't want to "nickel and dime" this for every event separately...

**Comment by zeertzjq** [comment]
Closing in favor of #23581
