### ISSUE TITLE
macos: Code Signature Invalid 

### ISSUE THREAD

**Issue by arslanm** [neovim/neovim#18504]
### Neovim version (nvim -v)

v0.8.0-dev+160-gdbdd58e54

### Vim (not Nvim) behaves the same?

Not tested

### Operating system/version

macOS 12.0.1

### Terminal name/version

iTerm2 3.4.15

### $TERM environment variable

xterm-256color

### Installation

wget && tar xf && nvim-osx64/bin/nvim

### How to reproduce the issue

$> wget https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
$> tar xf ./nvim-macos.tar.gz
$> ./nvim-osx64/bin/nvim

### Expected behavior

Run w/o error

### Actual behavior

$> uname -m
arm64
$> ./nvim-osx64/bin/nvim
dyld[50126]: Library not loaded: @executable_path/../libs/CoreServices
  Referenced from: /opt/nvim-osx64/bin/nvim
  Reason: tried: '/opt/nvim-osx64/bin/../libs/CoreServices' (code signature invalid (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00001C30, codeBlobSize=0x000047E0 for '/opt/nvim-osx64/libs/CoreServices'), '/usr/local/lib/CoreServices' (no such file), '/usr/lib/CoreServices' (no such file)
Abort trap: 6

**Comment by timtyrrell** [comment]
I want to say it started happening around this time: https://github.com/neovim/neovim/pull/18294

**Comment by justinmk** [comment]
@mhinz "CoreServices is damaged and can't be opeend" https://github.com/neovim/neovim/issues/18707

**Comment by joviol** [comment]
Hello,
I am getting the same error (on an M1 mac) os version: 12.4.
Can I get any indication on how to resolve it?

**Comment by roeniss** [comment]
same issue. 
I previously used 0.7.0 by `brew install nvim`.
I uninstalled it by `brew uninstall nvim`, then manually downloaded 0.8.0 from github release.
But when open`nvim` I met an error popup, which is a pretty common situation on macOS. I clicked 'cancel' instead of 'move to trash', open System Preferences - Security - General - Allow nvim.
After that, I faced the above issue.

**Comment by clason** [comment]
I believe this line needs to be changed to include the new library #18294 included:
https://github.com/neovim/neovim/blob/7b2b44bce4bff85d9fd1bef09d294ddb889056e4/.github/workflows/release.yml#L105
