### ISSUE TITLE
Update htmlcomplete.vim for HTML5

### ISSUE THREAD

**Issue by d12bb** [neovim/neovim#18520]
### Feature already in Vim?

No

### Feature description

With `runtime/autoload/htmlcomplete.vim`, we have a great builtin Omnifunc for HTML, which however is stuck in HTML4 land, which is hardly used (save for legacy code) anymore. I think this should be updated to HTML5 / the HTML Living Standard with semantic tags, MathML, new form controls etc. eventually, though this is low priority obviously with LSP and most of the old completion still being useful.

**Comment by clason** [comment]
That is a good suggestion, but one that you should make at vim/vim (or rather, to the maintainer that is listed at the top of this file), since these files are maintained there and just included verbatim.

(Rule of thumb: if it's a `.vim` file, it's a Vim issue!)
