### ISSUE TITLE
`switchbuf=uselast` is the default, but has no effect unless it is set to `uselast` again manually

### ISSUE THREAD

**Issue by AlxHnr** [neovim/neovim#18529]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

Vim 8.2 has no default value for `switchbuf`

### Operating system/version

Fedora 35

### Terminal name/version

gnome-terminal 3.42.2

### $TERM environment variable

xterm-256color

### Installation

Appimage

### How to reproduce the issue

```sh
nvim --clean
```

* Open three splits like this:

```
|-----------------------------------|
|            file_1                 |
|-----------------------------------|
|            file_2                 |
|-----------------------------------|
|            file_3                 |
|-----------------------------------|
```

* Populate your quickfix list with something, but without causing the list to open. E.g. do `:grep!` search
* Navigate to the first split (`file_1`)
* Run `:copen`
* Select any item in the quickfix window

### Expected behavior

Grep search result is opened in the first window (`file_1`)

### Actual behavior

Grep search result is opened in the last window (`file_3`)

**Comment by seandewar** [comment]
Vim also seems to forget to update `swb_flags` in `didset_options`.
In Vim's case, probably means `:set all&` resets the value, but acts like the previous value is still set?

**Comment by seandewar** [comment]
https://github.com/vim/vim/commit/39c46b43780ad00ea27a93d92aadd44753d4c3ea
