### ISSUE TITLE
E5108: Error executing lua ... gZd/nvtmstack traceback:ime/Lua/vim/lsp/util. lua:367: offset_encoding: expected string, got nil 

### ISSUE THREAD

**Issue by myzjy** [neovim/neovim#18521]
### Feature description

- [ ] 
![image](https://user-images.githubusercontent.com/58101943/167833599-727bba40-9276-4367-86d7-14ec8a13d795.png)
My configuration
![image](https://user-images.githubusercontent.com/58101943/167833724-fe007598-8317-435b-b84e-555f348c565a.png)

**Comment by clason** [comment]
Please open an actual issue and fill out the template (which is there for a reason!)

**Comment by myzjy** [comment]
This is an LSP syntax prompt. When auto - complete, select the completion API function appears
