### ISSUE TITLE
Function pointer callback is not evaluated in Lua autocmd

### ISSUE THREAD

**Issue by cbarrete** [neovim/neovim#18530]
### Neovim version (nvim -v)

v0.8.0-dev+2693-g1839a485f

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Debian 12

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

build from repo

### How to reproduce the issue

Yank some text with `vim.api.nvim_create_autocmd('TextYankPost', { callback = vim.highlight.on_yank })` in the config.

### Expected behavior

`vim.highlight.on_yank()` gets called and the yanked text is highlighted.

### Actual behavior

No highlighting.

This worked at some point but it doesn't anymore. I can't bisect to when it happened since it had been a long time since my last build and too many changes were committed since.
Note that by wrapping the function in a lambda, I get the expected behavior: `vim.api.nvim_create_autocmd('TextYankPost', { callback = function() vim.highlight.on_yank() end })`.

**Comment by clason** [comment]
Both your callbacks are identical?

But yes, there was a change: Callbacks are now passed an argument, so functions that already take (different) arguments can no longer be passed directly and have to be wrapped.

**Comment by cbarrete** [comment]
> Both your callbacks are identical?

Yup, messed up my copy paste, sorry about that, I've edited the issue.

> But yes, there was a change: Callbacks are now passed an argument, so functions that already take (different) arguments can no longer be passed directly and have to be wrapped.

Ah, that's a shame, that's not a bug then. Thanks!
