### ISSUE TITLE
lsp: port improvements in code_action to range_code_action / combine the two functions?

### ISSUE THREAD

**Issue by fsouza** [neovim/neovim#18533]
### Feature already in Vim?

N/A

### Feature description

There have been some recent changes to code_action to support filtering and auto-apply, I'm wonder if those could be either ported to `range_code_action`, or better, if `code_action` could optionally take a "range" (then `range_code_action` could be deprecated or something like that).

I'm happy to send a PR if this is something folks think is useful. My goal is to delete my custom codeAction stuff in favor of the new features in core :)

**Comment by justinmk** [comment]
> or better, if `code_action` could optionally take a "range" (then `range_code_action` could be deprecated or something like that).

makes sense to me...

**Comment by fredrikekre** [comment]
As long as there in an easy supported way to compute the range from a visual selection I think it would be good to combine them, then you can bind e.g.
```
vim.lsp.buf.code_action(...)                                    # normal mode
vim.lsp.buf.code_action({range = vim.lsp.util.compute_range()}) # visual mode
```
(Currently there is `vim.lsp.util.make_given_range_params` which does approximately that).

See also https://github.com/neovim/neovim/issues/18371 for discussion about having a specific `range_` function vs combining.

**Comment by justinmk** [comment]
> As long as there in an easy supported way to compute the range from a visual selection

- https://github.com/neovim/neovim/pull/13896

**Comment by fsouza** [comment]
> As long as there in an easy supported way to compute the range from a visual selection I think it would be good to combine them

Oh, I missed this, but I was thinking that `code_action` should just take a range. How that range is calculated doesn't really matter, it's how range_code_action works today. Being able to get the visual range is not a requirement for this feature (though I agree that in other to make it useful people will have to implement a function to grab the current visual range).
