### ISSUE TITLE
When building as non-root in a folder unwritable by root, installation fails with unclear message.

### ISSUE THREAD

**Issue by exhuma** [neovim/neovim#1854]
My home folder is located on an NFS share, so the local `root` user does not have write access. Running `make` works fine, but then running `sudo make install` terminates as follows:

    sudo make install
    make  -C .deps
    make[1]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[2]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    Built target libunibilium
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    Built target libtermkey
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    Built target libtickit
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    Built target libuv
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    Built target luajit
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    Built target luarocks
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    Built target msgpack
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    Built target busted
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    Built target lua-messagepack
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    Built target lpeg
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    Built target nvim-client
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: Entering directory `/home/users/michel/work/public/neovim/.deps'
    make[3]: *** [CMakeFiles/third-party] Error 1
    make[3]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    make[2]: *** [CMakeFiles/third-party.dir/all] Error 2
    make[2]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    make[1]: *** [all] Error 2
    make[1]: Leaving directory `/home/users/michel/work/public/neovim/.deps'
    make: *** [deps] Error 2

As it turns out, this is because the `root` user cannot write into my home folder (nvim was built in a sub-folder of my home). Moving the whole build folder into `/tmp` for example fixes the problem.

My issue with this is, that there is no clear error message which could hint to the permission problem.

**Comment by jszakmeister** [comment]
Did you try running in with `sudo make install VERBOSE=1`?  I'm just curious if that does a better job of leading you to the problem.

**Comment by fwalch** [comment]
FWIW, this should also occur with just `sudo make`, so it's not related to installation.

**Comment by doppioandante** [comment]
Is the folder where you are compiling a virtual box shared folder or something similar?

**Comment by justinmk** [comment]
No reply.
