### ISSUE TITLE
Unexpected line when type # after completion

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#18565]
### Neovim version (nvim -v)

NVIM v0.7.0 release

### Vim (not Nvim) behaves the same?

Yes, Vim 8.2.4710

### Operating system/version

MacOS 12.1

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

repo

### How to reproduce the issue

Issue happens on neovim >= 0.7.0.
Issue happens when `#` is not in `iskeyword`
``` sh
nvim -u NORC t.js
```
``` vim
call setline(1, 'foo foot')
call feedkeys("o  f\<C-n>#")
```

### Expected behavior

Second line should be `   foo#`

### Actual behavior

Second line becomes `#foo`

**Comment by chemzqm** [comment]
A workaround is use a key-mapping like:
```vim
inoremap # <space><backspace>#
```

**Comment by zeertzjq** [comment]
Bug also exists in Vim.

**Comment by zeertzjq** [comment]
This bug was caused by [patch 8.2.4710](https://github.com/vim/vim/commit/ac72c21da696cf6c31630a9e5ff4c0d3e2049c11)
