### ISSUE TITLE
The height of the floating window is always maintained at the maximum.

### ISSUE THREAD

**Issue by peter-lyr** [neovim/neovim#18596]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

no

### $TERM environment variable

no

### Installation

windows 10 release

### How to reproduce the issue

nvim-qt.exe # open nvim-qt, the windows 10 version.
:TranslateW # a plugin voldikss/vim-translator, translate <cword>

### Expected behavior

I hope it can adjust the window size and position adaptively. At least do not always  maximize the floating window. I'd appreciate it if someone could help with this problem.

### Actual behavior

![image](https://user-images.githubusercontent.com/55801796/168652207-b92d60f5-ee24-4c9a-b07a-f232fa72945d.png)

**Comment by zeertzjq** [comment]
No steps to reproduce with `nvim --clean`, and this sounds like a plugin configuration problem.
