### ISSUE TITLE
CMake throws error when building third-party deps with MinGW (from Git Bash)

### ISSUE THREAD

**Issue by DrKJeff16** [neovim/neovim#18597]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+215-g19da1071d

### Vim (not Nvim) behaves the same?

No, Vim 8.2.4960

### Operating system/version

Windows 10.0.19044

### Terminal name/version

MinTTY 3.6.1 x86_64-pc-msys

### $TERM environment variable

xterm-256color

### Installation

Build from repo

### How to reproduce the issue

```bash
mkdir .deps
cd .deps
cmake -G Ninja ../third-party
```

### Expected behavior

Expected successful compilation of third party dependencies, specifically `libuv`, as I'm used to.

### Actual behavior

Error thrown looks as follows:
```
CMake Error at cmake/BuildLibuv.cmake:54 (message):
  Trying to build libuv in an unsupported system Windows/GNU
Call Stack (most recent call first):
  CMakeLists.txt:205 (include)


-- Configuring incomplete, errors occurred!
See also "D:/dev/nvim/.deps/CMakeFiles/CMakeOutput.log".
```

The log file:
[CMakeOutput.log](https://github.com/neovim/neovim/files/8703975/CMakeOutput.log)

**Comment by dundargoc** [comment]
https://github.com/neovim/neovim/pull/18580

**Comment by kylo252** [comment]
you can use the packaged libuv instead

```sh
pacman -S mingw-w64-x86_64-libuv
cmake -GNinja -B.deps -DUSE_BUNDLED_LIBUV=OFF third-party
```

**Comment by DrKJeff16** [comment]
> you can use the packaged libuv instead
> 
> ```shell
> pacman -S mingw-w64-x86_64-libuv
> cmake -GNinja -B.deps -DUSE_BUNDLED_LIBUV=OFF third-party
> ```

While this issue is being resolved, I followed your advice and I ended up having to disable bundled `luarocks` and `luajit` aswell to switch to each dependency installed in the MinGW64 environment:

```bash
mkdir .deps
cd .deps
cmake -G Ninja -DUSE_BUNDLED_LIBUV=OFF -DUSE_BUNDLED_LUAJIT=OFF -DUSE_BUNDLED_LUAROCKS=OFF ../third-party
```

This allows CMake to configure properly the dependencies, but unfortunately building with ninja using the cmake instruction above leads to `tree-sitter` dying mid compilation:

```
...
[0/1] Install the project...
-- Install configuration: "Release"
-- Installing: D:/dev/nvim/.deps/usr/lib/nvim/parser/c.dll
[59/90] Performing download step for 'tree-sitter'
-- file: D:/dev/nvim/.deps/build/downloads/tree-sitter/v0.20.6.tar.gz
-- downloading...
       src='https://github.com/tree-sitter/tree-sitter/archive/v0.20.6.tar.gz'
       dst='D:/dev/nvim/.deps/build/downloads/tree-sitter/v0.20.6.tar.gz'
       timeout='none'
-- downloading... done
-- extracting...
     src='D:/dev/nvim/.deps/build/downloads/tree-sitter/v0.20.6.tar.gz'
     dst='D:/dev/nvim/.deps/build/src/tree-sitter'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean binary dir]
-- extracting... [clean up]
-- extracting... done
[62/90] Performing configure step for 'msgpack'
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Found ZLIB: D:/msys64/mingw64/lib/libz.dll.a (found version "1.2.12")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Doxygen: D:/msys64/mingw64/bin/doxygen.exe (found version "1.9.4") found components: doxygen missing components: dot
-- Configuring done
-- Generating done
-- Build files have been written to: D:/dev/nvim/.deps/build/src/msgpack-build
[65/90] Performing build step for 'tree-sitter'
FAILED: build/src/tree-sitter-stamp/tree-sitter-build D:/dev/nvim/.deps/build/src/tree-sitter-stamp/tree-sitter-build
cmd.exe /C "cd /D D:\dev\nvim\.deps\build\src\tree-sitter && CC=D:\msys64\mingw64\bin\cc.exe "CFLAGS=-O3 -Wall -Wextra" && D:\msys64\mingw64\bin\cmak
e.exe -E touch D:/dev/nvim/.deps/build/src/tree-sitter-stamp/tree-sitter-build"
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find d:\msys64\mingw64\x86_64-w64-mingw3
2\bin\../../../mingw64D:\msys64\mingw64\bin\cc.exe: Invalid argument
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find CFLAGS=-O3 -Wall -Wextra: No such f
ile or directory
collect2.exe: error: ld returned 1 exit status
...
```

So I corrected by using my MinGW64 `tree-sitter` aswell:

```bash
cmake -G Ninja -DUSE_BUNDLED_LIBUV=OFF -DUSE_BUNDLED_LUAJIT=OFF -DUSE_BUNDLED_LUAROCKS=OFF -DUSE_BUNDLED_TS=OFF ../third-party
```

Which compiled succesfully. Then I proceeded to build Neovim as suggested, using the following CMake configuration:

```bash
cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=D:/nvim ..
```

But I had to install at least the following packages on MSYS2 so that the CMake config would pass:

```bash
pacman -S --needed mingw-w64-x86_64-{lua-lpeg,lua51-lpeg,lua-mpack,lua51-mpack,libmpack,lua51}
```

But installing `mingw-w64-x86_64-lua51` conflicts with `mingw-w64-x86_64-luajit`, which is also needed. Also, switching from `CMAKE_BUILD_TYPE` hasn't had a noticeable effect on these errors.

These are my observations as to how the building process seems to fail.

**Comment by kylo252** [comment]
> But installing `mingw-w64-x86_64-lua51` conflicts with `mingw-w64-x86_64-luajit`, which is also needed. 

LuaRocks is indeed the hardest one to solve imo

> Also, switching from `CMAKE_BUILD_TYPE` hasn't had a noticeable effect on these errors.

that should affect `busted` at least, and maybe `lpeg`

> These are my observations as to how the building process seems to fail.

you can see some of the tests I made in https://github.com/neovim/neovim/pull/18389 and https://github.com/neovim/neovim/issues/18495#issuecomment-1126921313
