### ISSUE TITLE
CTRL-R +/* doesn't work in command mode when not first used in insert mode

### ISSUE THREAD

**Issue by LeonB** [neovim/neovim#1860]
When I execute `CTRL-R +` or `CTRL-R *` in command mode it doesn't paste clipboard contents. When I go into insert mode and use `CTRL-R +` and then go into command mode it does work.

So when you're in command mode and you haven't used `CTRL-R +` in insert mode in that session it doesn't work.

Tested with `nvim -u NONE`

```
$ nvim --version
NVIM 0.0.0-alpha+201501210017 (compiled Jan 21 2015 11:32:17)
Commit: c3028e435392a7b647f79be826c054ef76b0d577
```

**Comment by bfredl** [comment]
#2244 attempts to solve this and some similar limitations.

**Comment by bfredl** [comment]
This should be fixed on master now. (reopen if still problems)

**Comment by LeonB** [comment]
Installed version from HEAD and works fine now :+1:

**Comment by elmart** [comment]
Works for me. Thanks!
