### ISSUE TITLE
Failed to run healthcheck for "vim.lsp" plugin. Exception

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/neovim#18602]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+1684-g6613f58ce

### Vim (not Nvim) behaves the same?

no, vim

### Operating system/version

macOS 12.3.1

### Terminal name/version

iTerm2

### $TERM environment variable

screen-256color

### Installation

home brew

### How to reproduce the issue

Start neovim.
run checkhealth.

### Expected behavior

checkhealth does not detect any errors.

### Actual behavior

```
vim.lsp: require("vim.lsp.health").check()
========================================================================
  - ERROR: Failed to run healthcheck for "vim.lsp" plugin. Exception:
    function health#check, line 20
    Vim(eval):E5108: Error executing lua ...m/HEAD-6613f58/share/nvim/runtime/lua/vim/lsp/health.lua:20: attempt to index a nil value
    stack traceback:
    ...m/HEAD-6613f58/share/nvim/runtime/lua/vim/lsp/health.lua:20: in function 'check'
    [string "luaeval()"]:1: in main chunk
```

**Comment by clason** [comment]
This is the check for the size of the log file, which (now) is almost never written to unless you set the log level yourself. You need to replace the mentioned line 20 in `lsp/health.lua` by
```lua
local log_file = vim.loop.fs_stat(log_path)
local log_size = log_file and logfile.size or 0
```

**Comment by nabezokodaikon** [comment]
Where should I place `lsp/health.lua`?

**Comment by clason** [comment]
It's under `runtime/lua`.

**Comment by clason** [comment]
Not really, but you don't _have_ to do it. You'll just have to wait for someone else, then.

**Comment by nabezokodaikon** [comment]
By the way, when I set health.lua, the number of errors increased.
```
lsp: require("lsp.health").check()
========================================================================
  - ERROR: Failed to run healthcheck for "lsp" plugin. Exception:
    function health#check, line 20
    Vim(eval):E5108: Error executing lua [string "luaeval()"]:1: attempt to index a boolean value
    stack traceback:
    [string "luaeval()"]:1: in main chunk
```

**Comment by nabezokodaikon** [comment]
confirmed. Thank you!

**Comment by dat-le-4** [comment]
I believe I got in to kind of the same error. This is the error I got when I ran checkhealth nvim.

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - ERROR: Failed to run healthcheck for "vim.lsp" plugin. Exception:
    function health#check, line 20
    Vim(eval):E5108: Error executing lua Vim:E739: Cannot create directory /Users/datle/.local/state/nvim: permission denied
    stack traceback:
    [C]: in function 'mkdir'
    ...llar/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp/log.lua:44: in main chunk
    [C]: in function 'require'
    ...r/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp/health.lua:8: in function 'check'
    [string "luaeval()"]:1: in main chunk
