### ISSUE TITLE
WinBar and WinBarNC not applied properly when using the new winbar option

### ISSUE THREAD

**Issue by YorickPeterse** [neovim/neovim#18628]
### Neovim version (nvim -v)

8a9ab8894

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Linux

### Terminal name/version

GNOME Terminal

### $TERM environment variable

xterm-256color

### Installation

AUR (neovim-git)

### How to reproduce the issue

Create the following file:

```vim
set termguicolors

hi WinBarNC guibg=#eeeeee gui=none
hi WinBar guibg=red gui=bold

hi StatusLineNC guibg=#eeeeee gui=none
hi StatusLine guibg=red gui=bold

set winbar=\ %f\ %=
set statusline=\ %f\ %=
```

Save this in `repro.vim` then start nvim as follows:

```
nvim -u repro.vim
```

Next, create a new window using `:vne` then switch to it.

### Expected behavior

Both the active statusline and window bar turn red.

### Actual behavior

Only the statusline is updated. To update the winbar one has to run `redrawstatusline`, but this only affects the winbar of the current window, leaving the other one red.

This can be seen here:

[![asciicast](https://asciinema.org/a/ecpgTzff9XqiIMZMzNiJpXxpk.svg)](https://asciinema.org/a/ecpgTzff9XqiIMZMzNiJpXxpk)

**Comment by YorickPeterse** [comment]
@famiu It's working on `master`, thanks for the ping! :smiley:

**Comment by famiu** [comment]
> @famiu It's working on `master`, thanks for the ping! :smiley: 

Should close the issue then
