### ISSUE TITLE
virt_lines are duplicated when end_row is specified in nvim_buf_set_extmark

### ISSUE THREAD

**Issue by ii14** [neovim/neovim#18622]
### Neovim version (nvim -v)

0.8.0, 81f1e33d1

### Vim (not Nvim) behaves the same?

nil

### Operating system/version

ubuntu 18.04

### Terminal name/version

alacritty 0.11.0-dev (f4bdf5fb)

### $TERM environment variable

alacritty

### Installation

ppa

### How to reproduce the issue

Create and evaluate the script:
```lua
vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace('foo'), 0, 0, {
  end_row = 1,
  virt_lines = {{{'VIRT LINE', 'ErrorMsg'}}},
})
```

### Expected behavior

Should render as:
```
vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace('foo'), 0, 0, {
  end_row = 1,
VIRT LINE
  virt_lines = {{{'VIRT LINE', 'ErrorMsg'}}},
})
```

### Actual behavior

Renders as:
```
vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace('foo'), 0, 0, {
VIRT LINE
  end_row = 1,
VIRT LINE
  virt_lines = {{{'VIRT LINE', 'ErrorMsg'}}},
})
```

Sometimes it might not immediately render the second virtual line. Moving the cursor should update the screen.

**Comment by przepompownia** [comment]
Duplicated virt_lines appear also after adding `end_col`, f.e.
```lua
vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace('x'), 0, 2, {id = 1, end_
col = 6, hl_group = 'Comment', virt_lines={{{"E", "Error"}}} })
```
