### ISSUE TITLE
The terminal/prompt is occupied by nvim-qt.exe until you exit from nvim-qt.

### ISSUE THREAD

**Issue by villayer** [neovim/neovim#18643]
### Neovim version (nvim -v)

v0.7.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

Windows terminal, windows powershell terminal

### $TERM environment variable

xterm-256color

### Installation

scoop

### Note!!!
nvim-qt was working fine before i did an update ( `scoop update neovim`), it's only like this after i updated.
### Decription
Running nvim-qt.exe (or an alias to it) will cause the problem for me; otherwise, I'm not sure how I'd describe it.
I'm not sure if it's a bug or something specific to my machine, but I'd appreciate any assistance or feedback on the issue; for the time being, I'll just use the cli nvim.

### Expected behavior

After running nvim-qt.exe from a terminal, the program should launch and the prompt should return. here is an example of another text editor (sublime text).

After running subl.exe the program is launched and a _new prompt is printed_ to the screen and _you can type into it_, this is the expected behavior I want.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/69354448/169360834-e9e984d4-a7ab-4f1d-af51-608565cff663.png">

### Actual behavior

<img width="614" alt="image" src="https://user-images.githubusercontent.com/69354448/169379732-3ed9087d-812a-41f4-bc41-4b1ad94b9dbf.png">

<img width="634" alt="image" src="https://user-images.githubusercontent.com/69354448/169378969-2593531f-ef73-4614-9898-15401447c85b.png">

After running nvim-qt.exe the prompt stays occupied and you can't type anything to it, even Ctrl + c doesn't do anything, the prompt only goes to normal after exiting nvim-qt.exe.

I've test it both in windows terminal and in powershell terminal, also I tried to run it from wsl (Ubuntu's wsl) and it showed the same behavior.

**Comment by erw7** [comment]
If you run the real `nvim-qt.exe` (GUI program), this will not happen. You are probably running a wrapper (console program) installed by scoop. Therefore, I do not believe this is a neovim or nvim-qt issue.

**Comment by villayer** [comment]
Seems it's an issue with `scoop`, I installed neovim from `winget` and it's working fine.
