### ISSUE TITLE
Lag when I leave Neovim

### ISSUE THREAD

**Issue by terroo** [neovim/neovim#18640]
### Neovim version (nvim -v)

NVIM v0.8.0-dev

### Vim (not Nvim) behaves the same?

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2022 19:26:30)

### Operating system/version

Ubuntu 22.04 LTS

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

Build

### How to reproduce the issue

When using `nvim -u NONE` there is no lag, but with the plugins listed below either there is lag when I just open the file or when I close it after making some modification.

I've tested them one by one, I noticed that the lag starts from the `hrsh7th/cmp-buffer'` plugin, that's all the plugins:

```lua
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use 'terroo/vim-simple-emoji'
  use 'navarasu/onedark.nvim'
  use {
    'nvim-telescope/telescope.nvim',
    requires = { {'nvim-lua/plenary.nvim'} }
  }
  use 'kyazdani42/nvim-web-devicons'
  use 'tamton-aquib/staline.nvim'
  use 'lukas-reineke/indent-blankline.nvim'
  use 'tpope/vim-surround'
  use 'windwp/nvim-autopairs'
  use 'neovim/nvim-lspconfig'
  use 'hrsh7th/nvim-cmp'
  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-buffer' -- LAG WHEN CLOSE NVIM
  use 'hrsh7th/cmp-path' -- LAG WHEN CLOSE NVIM
  use 'hrsh7th/cmp-cmdline' -- LAG WHEN CLOSE NVIM
  use 'saadparwaiz1/cmp_luasnip' -- LAG WHEN CLOSE NVIM
  use 'L3MON4D3/LuaSnip'
  use 'rafamadriz/friendly-snippets'
  use 'ray-x/lsp_signature.nvim'
  use {'tzachar/cmp-tabnine', run='./install.sh', requires = 'hrsh7th/nvim-cmp'} -- LAG WHEN CLOSE NVIM
  use 'onsails/lspkind-nvim'

  use {
    'kyazdani42/nvim-tree.lua',
    requires = {
      'kyazdani42/nvim-web-devicons', -- optional, for file icon
    }
  }
  use {'akinsho/bufferline.nvim', tag = "*", requires = 'kyazdani42/nvim-web-devicons'}
  use 'matze/vim-move'
  use 'rcarriga/nvim-notify'
  use 'voldikss/vim-floaterm'
end)

```

### Expected behavior

Does anyone know how I can resolve this?

prompt$ nvim file
2 seconds
prompt$

### Actual behavior

prompt$ nvim file
prompt$

**Comment by clason** [comment]
Intentional: https://github.com/neovim/neovim/pull/17783

(Not the lag; that indicates a bug that should be fixed.)

Use a Release build instead as a workaround.

**Comment by dundargoc** [comment]
For more info, use `:checkhealth` :)

**Comment by terroo** [comment]
I had already seen this option right in `:checkhealth` and thought about recompile with it, but I had already tried so many things that I prefer to come here. But anyway, thanks for the solution, it worked!
