### ISSUE TITLE
Crash when using winbar

### ISSUE THREAD

**Issue by ChrisAmelia** [neovim/neovim#18649]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+253-geb0aa8bb0

### Vim (not Nvim) behaves the same?

no.

### Operating system/version

Ubuntu 18

### Terminal name/version

bash

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

**init.vim**
```vim
source $HOME/.config/nvim/status-line.vim
```

**status-line.vim**
```vim
function! ActiveLine()
    return luaeval("require'status-line'.activeLine()")
endfunction

set statusline=%!ActiveLine()
```

**lua/status-line.lua**
```lua
local Module = {}

--- Statusline active
function Module.activeLine()
	local statusline = ""

	vim.opt.winbar = "hello"

	return statusline
end

return Module
```

Just run nvim with the above config.

### Expected behavior

Not crashing.

### Actual behavior

Crash with message:

> /home/runner/work/neovim/neovim/src/nvim/grid.c:338: grid_puts_line_flush: Assertion `put_dirty_row != -1' failed.

**Comment by zeertzjq** [comment]
The Lua isn't needed to reproduce the assert. This is enough:
```vim
function! ActiveLine()
  set winbar=foo
endfunction

set statusline=%!ActiveLine()
```

**Comment by famiu** [comment]
Seems to be caused by https://github.com/neovim/neovim/commit/17758fe7ad

@bfredl https://github.com/neovim/neovim/commit/17758fe7ad#diff-909f74662e9735298c70bea7938380ca5cac521154fbf6e243d4c54b5ef82ccaR5327 this line causing the assert in `grid_puts_line_flush` to fail, which causes the crash

**Comment by famiu** [comment]
The issue is likely that `win_redr_custom` is called before `win_grid_alloc`, since `win_grid_alloc` is responsible for setting the `row_offset` of the grid.

**Comment by famiu** [comment]
@ChrisAmelia By the way, what you're doing is absurd and should not be done. Winbar and statusline are separate things and you absolutely should not set the value of one inside a function that's called during the evaluation of another. So all we can do is add an out-of-bounds check to prevent a segfault, but it will still not work correctly and you'd have to set the options properly, separate from each other.
