### ISSUE TITLE
winbar does not update when the cursor moves

### ISSUE THREAD

**Issue by rockyzhang24** [neovim/neovim#18645]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+1709-g69853a622 (nightly https://github.com/neovim/neovim/commit/69853a622a1fa9b920171657a255648e532bd444)

### Vim (not Nvim) behaves the same?

`winbar` is neovim specific only

### Operating system/version

macOS 12.3.1

### Terminal name/version

kitty terminal 0.24.3

### $TERM environment variable

xterm-kitty

### Installation

brew install neovim --HEAD

### How to reproduce the issue

Add this piece of code in `init.vim`

```
let g:cnt = 0
function AddOne()
  let g:cnt = g:cnt + 1
  echom g:cnt
endfunction

set winbar=%{AddOne()}
```

Use a counter to test whether `winbar` gets updated when we move the cursor. 

Then open any file and move the cursor. The counter value is unchanged when we move the cursor.

### Expected behavior

The updates of `winbar` should be the same with `statusline`, i.e., when we move the cursor, `winbar` should update. 

When we use `winbar` to display the treesitter context (like nvim-gps) or LSP symbols, it should update along with the cursor movement. Otherwise, we have to use `autocmd CursorMoved * set winbar=...` to update the `winbar`.

### Actual behavior

winbar does not update when the cursor moves.

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/pull/18646/files I think this is the missing link

**Comment by wookayin** [comment]
Somehow even without having #18646, `winbar` automatically updates for me. I'm not sure if any other plugins (like lualine) are triggering appropriate autocmd events for me. But looking forward to have the bug fixed. :)

**Comment by rockyzhang24** [comment]
Hi @wookayin have you tried the test (see "How to reproduce the issue") above. I put that piece of code in an empty `init.vim` and I could confirm that `winbar` didn't get updated when I moved the cursor. Anyway, let's wait for the PR to be merged and I will test again. Thank you 👊

**Comment by wookayin** [comment]
Yes the bug is *reproducible* when no plugin is used (`nvim -u foo.vim`). With other plugins enabled something is triggering redrawing for me, but no idea which one is doing the job.

BTW your reproduce code is somewhat misleading, because it does not return anything. I guess you probably have missed `return g:cnt` in the `AddOne` function.

**Comment by rockyzhang24** [comment]
> but no idea which one is doing the job

Okay. That's interesting.

> BTW your reproduce code is somewhat misleading, because it does not return anything. I guess you probably have missed return g:cnt in the AddOne function.

I just want to check whether AddOne is executed or not, so I use echom to print the cnt in messages instead of the winbar area by return.
