### ISSUE TITLE
Cannot type [ in nvim-qt

### ISSUE THREAD

**Issue by Carlosmape** [neovim/neovim#18652]
### Neovim version (nvim -v)

v0.7.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

none

### $TERM environment variable

none

### Installation

Extracting from release tag zip file and placin in ~\AppData\Local\nvim

### How to reproduce the issue

simply open nvim-qt and typing [ key

### Expected behavior

press [ key should type this character in editing mode (or command line)

### Actual behavior

Does nothing.

**Comment by Carlosmape** [comment]
Update:
I tried #6703 and [https://github.com/equalsraf/neovim-qt/issues/325](https://github.com/equalsraf/neovim-qt/issues/325) proposed solution but keeps not working.

**Comment by markstos** [comment]
@Carlosmape Have you tried this when running Nvim with no init file or plugins loaded? `nvim -u NONE`

**Comment by justinmk** [comment]
need repro steps with `nvim_input()`

**Comment by Carlosmape** [comment]
> @Carlosmape Have you tried this when running Nvim with no init file or plugins loaded? `nvim -u NONE`

Hi, with nvim-qt it does not work by launching it from the PowerShell:
![imagen](https://user-images.githubusercontent.com/5487555/169787756-d2f43b62-d0a6-4bce-9a93-fe81521927c9.png)

But it works if y run nvim.exe instead of nvim-qt (ant typing [ works properly):
![imagen](https://user-images.githubusercontent.com/5487555/169788109-e5a9f6bd-4cf8-4c2c-87c0-5230aebc169d.png)

How it worked, I tried to run again but with my configurations (to discard the problem is in the init.lua (or in any plugin)) and it is working as well:
![imagen](https://user-images.githubusercontent.com/5487555/169788548-057fbcb6-00c2-4ff8-b432-c56774962f41.png)


NOTE: Taking this into account the trouble seems to comes just from nvim-qt executable.

**Comment by zeertzjq** [comment]
Then this should be a bug in neovim-qt.

**Comment by zeertzjq** [comment]
There seems to be already an issue for that: <https://github.com/equalsraf/neovim-qt/issues/720>
