### ISSUE TITLE
feat(lsp): expose logic to query for support LSP method for any buffer client

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#18654]
### Feature already in Vim?

No

### Feature description

Currently this logic works within `lsp.buf_request`: if requested method isn't supported by any client, we get a notification (`lsp._unsupported_method(method)`). It would be good to expose it to some public method. 

Example: suppose that we can some autocommand enabled on attach some client
```lua
api.nvim_create_augroup('LspDocumentHighlight', {clear = true})
```
```lua
-- ... in on_attach
  if client.server_capabilities.documentHighlightProvider then
    api.nvim_create_autocmd({'CursorMoved', 'CursorMovedI'}, {
      group = 'LspDocumentHighlight',
      buffer = bufnr,
      callback = vim.lsp.buf.clear_references
    })
    api.nvim_create_autocmd({'CursorHold', 'CursorHoldI'}, {
      group = 'LspDocumentHighlight',
      buffer = bufnr,
      callback = vim.lsp.buf.document_highlight
    })
  end
```
and we want to clear them if no buffer support highlighting using newly defined `LspDetach`.

**Comment by mfussenegger** [comment]
I'm not Not sure I understand the use case correctly.  Isn't it possible to query the clients in the LspDetach event and check their capabilities? If none has the server capability you can remove the autocmd

**Comment by przepompownia** [comment]
```lua
    api.nvim_create_autocmd({'LspDetach'}, {
      group = 'LspDocumentHighlight',
      buffer = bufnr,
      callback = function (args)
        -- vim.notify('Detached')
        local supported = false
        vim.lsp.for_each_buffer_client(args.buf, function (client, client_id)
          if client.supports_method('textDocument/documentHighlight') then
            -- vim.notify(client.name .. ' supports method')
            method_supported = true
          end
        end)
        if not supported then
          api.nvim_clear_autocmds {
            group = 'LspDocumentHighlight',
            buffer = args.buf,
          }
        end
      end,
    })
```
It's possible to use the part of this logic on the user side. This proposition is only for user convenience. 

btw. this example is only draft - at the moment the callback is not executed for me (on `:LspStop`) :grin:

**Comment by mfussenegger** [comment]
Closing this as this kinda has a solution/workaround - the `client.supports_method()`
In terms of convenience - we may need to do something that also considers dynamic capabilities. There's https://github.com/neovim/neovim/issues/24229 to track that.

**Comment by justinmk** [comment]
> has a solution/workaround - the `client.supports_method()`

We haven't documented that yet, is it still WIP?

**Comment by clason** [comment]
It's in `news.txt`...
