### ISSUE TITLE
LspDetach is not executed at `vim.lsp.stop_client`

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#18677]
### Neovim version (nvim -v)

b3453ea4a

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian sid

### Terminal name/version

kitty

### $TERM environment variable

screen-256color

### Installation

from source

### How to reproduce the issue

Assumming that we have attached LSP client 1 to the current buffer let
```vim
:au LspDetach echom 'Detached'
:lua vim.lsp.stop_client(1)
```
and see no message. 

Currently in `dispatch.on_exit` we have `LspDetach` inside a loop through `all_buffer_active_clients` which is [cleared ](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L1194) from `client_id` for each buffer before. Probably we need to execute `LspDetach` directly in `client.stop`.

### Expected behavior

LspDetach is executed at `stop_client` 

### Actual behavior

LspDetach is not executed at `stop_client`

**Comment by gpanders** [comment]
>Currently in dispatch.on_exit we have LspDetach inside a loop through all_buffer_active_clients which is [cleared ](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L1194)from client_id for each buffer before. Probably we need to execute LspDetach directly in client.stop.

Feel free to open a PR, should be a simple change.
