### ISSUE TITLE
ctrl key based keybindings in normal mode fail 

### ISSUE THREAD

**Issue by benmccormick** [neovim/neovim#1868]
I'm trying out Neovim, and having issues with [vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator/i) in that environment. Calling `:TmuxNavigate` commands directly works fine, the key mappings seem to fail.  My vimrc works fine in the Vanilla OSX vim and mvim, but fails in Neovim.  

Remapping to a different combination works, but the default <ctrl-hjkl> keymappings for tmux navigator all fail.

I was worried about conflicts, so I ran this simplified .vimrc and it still fails:

```
set nocompatible

set shell=bash
set shellpipe=2>/dev/null>
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()
Plugin 'gmarik/vundle'

"Integrate with tmux
Plugin 'christoomey/vim-tmux-navigator'

"End Vundle
call vundle#end()
" "Vundle ended so reenable filetypes
filetype plugin indent on
```

Any ideas what might be causing this?

This is nvim version: NVIM 0.0.0-alpha+201501221728
Tmux Version: 1.8

Corresponding: vim-tmux-navigator issue here: https://github.com/christoomey/vim-tmux-navigator/issues/61

**Comment by benmccormick** [comment]
Expanding on this, I can't seem to get anything To map in normal mode to a `<c-[a-z]>` shortcut.  

Have now tried various iterations of this:

```
nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
```

Mapping to `<leader>h` works fine.

**Comment by benmccormick** [comment]
Was a tmux configuration issue, pulling the <c-*> shortcuts before nvim got to them.  Fixed now.  Thanks.

**Comment by jrhorn424** [comment]
@benmccormick Can you elaborate on what the configuration issue was? I'm trying to debug a similar issue. Works fine with `vim` but fails with `nvim`.
