### ISSUE TITLE
vim.diagnostic should render error codes by default

### ISSUE THREAD

**Issue by mikatpt** [neovim/neovim#18687]
### Feature description

The standard `vim.diagnostic.open_float()` API omits error codes. This is essentially never what you want, as the error code always makes it faster to diagnose unfamiliar problems, with relatively little text added.

While you can use the `format` function exposed by this API, it seems like a less sensible default - I've been using lspsaga, which has [included this by default](https://github.com/tami5/lspsaga.nvim/blob/fafb102bf2966dd44f625ac1dc555ad52d2d729d/lua/lspsaga/diagnostic.lua#L30-L32) for a while. If there's a compelling reason not to do this, please let me know!

sample diagnostic:
```
{ {
    bufnr = 22,
    code = "import/order",
    col = 0,
    end_col = 29,
    end_lnum = 1,
    lnum = 1,
    message = "`next/head` import should occur before import of `../utils/trpc`",
    namespace = 27,
    severity = 1,
    source = "eslint",
    user_data = {
      lsp = {
        code = "import/order",
        codeDescription = {
          href = "https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/order.md"
        }
      }
    }
  } }
```

**Comment by justinmk** [comment]
Don't think anyone is opposed to this, PR welcome...

**Comment by mikatpt** [comment]
sounds good! Will try and tackle it when I have some spare time.

**Comment by gpanders** [comment]
The only thing to keep in mind is that `vim.diagnostic` is not just for LSP diagnostics. Error codes (as your example shows) are something that only specific LSP servers provide, it is not generalizable. That is why they have not been included so far.

**Comment by beardedsakimonkey** [comment]
I'm wondering if, rather than modifying `diagnostic.message` to include the error code, we added a `suffix` option (much like `prefix`) that, by default, renders the `diagnostic.code` (if any).  This would require a bit more logic to implement, but would enable the user to customize the highlighting, which would help distinguish it from the message.

Happy to take a crack at it if it sounds acceptable.

**Comment by gpanders** [comment]
@beardedsakimonkey Sure, please put together a PR and I'll take a look.
