### ISSUE TITLE
error reading from stdin

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1870]
Reading from stdin no longer works.

```
echo 'hi' | nvim -
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...
Vim: preserving files...
Vim: Finished.
```

This happened in the last month or so.

**Comment by Pyrohh** [comment]
It works for me, and my `nvim --version` says I compiled Jan. 16th, but I have the same issue when compiled from HEAD.

**Comment by nrhtr** [comment]
Works for me with NVIM 0.0.0-alpha+201501231816 (compiled Jan 26 2015 12:27:12)
Commit: 65adcc269971b55418769a8eca8e49f3e0191e14

**Comment by Oreolek** [comment]
STDIN read works for me with master/HEAD (d304642) on zsh 5.0.7. I think you should compare your shells.

**Comment by justinmk** [comment]
fixed
