### ISSUE TITLE
Character index function

### ISSUE THREAD

**Issue by jild** [neovim/neovim#18700]
### Feature already in Vim?

Yes

### Feature description

Hi,

in vim i can use the charcol function to return the index of a character.
In neovim I can only find the col function operating byte-wise. But operating byte-wise doesnt make sense for a lot of use cases I think. 

Taken from vim help:

```
Example:
                With the cursor on '세' in line 5 with text "여보세요":
                        charcol('.')            returns 3
                        col('.')                returns 7
```

**Comment by justinmk** [comment]
we merge vim patches reguarly. don't need issues for each vim features.

**Comment by seandewar** [comment]
Neovim already has `charcol()` since 0.7

**Comment by jild** [comment]
thanks, im just getting used to how things work
