### ISSUE TITLE
Status bar sets itself to default after entering the terminal emulator

### ISSUE THREAD

**Issue by mcnuggetsx20** [neovim/neovim#18708]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

Arch Linux 5.17.9

### Terminal name/version

alacritty 0.10.1-1

### $TERM environment variable

alacritty

### Installation

Arch Linux Official Repository

### How to reproduce the issue
Put this in the vimrc file:
```
let g:currentmode={
       \ 'n'  : 'NORMAL ',
       \ 'v'  : 'VISUAL ',
       \ 'V'  : 'V·Line ',
       \ "\<C-V>" : 'V·Block ',
       \ 'i'  : 'INSERT ',
       \ 'R'  : 'R ',
       \ 'Rv' : 'V·Replace ',
       \ 'c'  : 'Command ',
       \}

set laststatus=2

set statusline+=%#keyword#
set statusline+=\ %{(g:currentmode[mode()])}

set statusline+=%#statusline#
set statusline+=\ %F\ %=\ 

set statusline+=%#number#
set statusline+=\ %L\ lines

set statusline+=%#string#
set statusline+=\ %{wordcount().words}\ words

set statusline+=%#function#
set statusline+=\ [NVIM]

  ```

nvim
:term
switch between normal and terminal mode a few times

### Expected behavior

The status line should remain as specified in the vimrc
![image](https://user-images.githubusercontent.com/71185521/169718367-8a911072-3dd6-4967-be57-308bbae0c1c6.png)

### Actual behavior

After entering the terminal emulator with :term, the status line sets itself to the default configuration
![image](https://user-images.githubusercontent.com/71185521/169718393-f1cc2d49-2591-4043-a5fc-8fc7c01a459f.png)

**Comment by bfredl** [comment]
A good starting point would be if you specify how you set statusline in your init.vim.

**Comment by mcnuggetsx20** [comment]
> A good starting point would be if you specify how you set statusline in your init.vim.

I've just updated the issue. Now it includes a chunk of my config responsible for setting my status line.

**Comment by zeertzjq** [comment]
In Terminal mode `mode()` returns `t`, and you do not have a key `t` in `g:currentmode` dictionary, so in Terminal evaluating the statusline will cause an error, and it will be reset to default. You can do this:
```vim
let g:currentmode={
       \ 'n'  : 'NORMAL ',
       \ 'v'  : 'VISUAL ',
       \ 'V'  : 'V·Line ',
       \ "\<C-V>" : 'V·Block ',
       \ 'i'  : 'INSERT ',
       \ 'R'  : 'R ',
       \ 'Rv' : 'V·Replace ',
       \ 'c'  : 'Command ',
       \ 't'  : 'Terminal ',
       \}
```
