### ISSUE TITLE
Mac OS x Catalina nvim.0.8 latest binary is not working

### ISSUE THREAD

**Issue by MyraBaba** [neovim/neovim#18707]
### Neovim version (nvim -v)

0.8

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Mac os x Catalina

### Terminal name/version

iterm 2

### $TERM environment variable

xterm-256

### Installation

repo tar.gz mac binary

### How to reproduce the issue

tar xzvf nvim-macos.tar.gz

and run nvim

### Expected behavior

normal run

### Actual behavior

crash
<img width="768" alt="Screen Shot 2022-05-23 at 00 48 36" src="https://user-images.githubusercontent.com/17505439/169717424-8fb1d7b5-84d3-469c-96eb-c432fa2feb52.png">

**Comment by justinmk** [comment]
#18504
