### ISSUE TITLE
Why do all my files appear executable when they are not in neovim?

### ISSUE THREAD

**Issue by zalvarez23** [neovim/neovim#18714]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+169-ge50b1fe60

### Vim (not Nvim) behaves the same?

vim  8.2

### Operating system/version

12.3.1 (21E258)

### Terminal name/version

iterminal

### $TERM environment variable

--

### Installation

..

### How to reproduce the issue

...

### Expected behavior

<img width="764" alt="image" src="https://user-images.githubusercontent.com/10501721/169772348-15a11788-f343-4680-b005-4c573b792938.png">

The files are displayed correctly without the asterisk and in the normal color.

### Actual behavior

<img width="765" alt="image" src="https://user-images.githubusercontent.com/10501721/169772294-c23bcfb8-ae35-4bf2-b94f-100f47ca4c70.png">

All files appear red and with asterisks.

**Comment by dundargoc** [comment]
This looks like a nerdtree issue. You should send it there: https://github.com/preservim/nerdtree
