### ISSUE TITLE
Winbar conflicts with diagnostics

### ISSUE THREAD

**Issue by ChrisAmelia** [neovim/neovim#18715]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+289-g9e1ee9fb1

### Operating system/version

Ubuntu 18

### Terminal name/version

bash

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

**init.vim**
```vim
set runtimepath^=~/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig/
source $HOME/.config/nvim/winbar.vim

lua << EOF
local lspconfig = require('lspconfig')

lspconfig.gopls.setup{
	cmd = {"gopls", "serve"},
	settings = {
		gopls = {
			analyses = {
				unusedparams = true,
			},
		},
	},
}
EOF

vim.keymap.set("n" , "de"  , vim.diagnostic.open_float)
```

**winbar.vim**
```vim
function! ActiveWinbar()
    return luaeval("require'winbar'.eval()")
endfunction

augroup Winbar
	autocmd!
	autocmd WinEnter,BufEnter * setlocal winbar=%!ActiveWinbar()
augroup END

set winbar=%!ActiveWinbar()
```

**winbar.lua**
```lua
local Module = {}

Module.eval = function ()
	return "hello world"
end

return Module
```

**main.go**
```go
package main

import "fmt"

func main() {
	fmt.Println("hello")
	fmt.Println()

	// watkanda spelling

	if true {
		if true {
			if true {
				if true {
					println("hi")
				}
			}
		}
	}
	// FIXME
	dqsdsd

	bye(d, )
}

// Deprecated: bye is deprecated
func bye(x, newValue string) {
    dqsdq
}
```

1. Open **main.go** (should be the same with any other language server) with: `nvim -u init.vim`.
1. Go to a line presenting a diagnostic.
1. Open diagnostic's floating window with: `vim.diagnostic.open_float` (or `vim.keymap.set("n" , "de"  , vim.diagnostic.open_float)`).

### Expected behavior

Only diagnostics are shown.

### Actual behavior

![image](https://user-images.githubusercontent.com/16366403/169774028-a4eea55f-a1ae-4480-a0ac-9f9f8e503cb4.png)

When opening the diagnostic's floating window, there are two values shown:

1. The winbar's value
1. The string "Diagnostics:"

What is not shown is the actual line's diagnostic.

**Comment by zeertzjq** [comment]
I don't think there is anything that can be changed in Nvim here, since you are explicitly setting winbar for every window. The only solution I can think of is to check if you actually want a winbar on the window before setting it. After #18773 global winbar will never apply to floating windows, so you can also use `setglobal winbar=%!ActiveWinbar()` instead.

**Comment by ChrisAmelia** [comment]
> [...] After #18773 global winbar will never apply to floating windows, so you can also use `setglobal winbar=%!ActiveWinbar()` instead.

Behavior remains the same even when using `setglobal`.

Version:  `v0.8.0-dev+329-gf31a10204`
