### ISSUE TITLE
Script-local functions are highlighted with error in Neovim 0.7.0

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#18724]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

No

### Operating system/version

CentOS 7.9

### Terminal name/version

xfce4-terminal 0.8.7.4

### $TERM environment variable

tmux-256color

### Installation

system package manager

### How to reproduce the issue

```
cat >/tmp/foo.vim <<HERE
call s:Foo()
HERE
nvim /tmp/foo.vim
```

### Expected behavior

No error highlighting should appear on the colon.

### Actual behavior

Error highlighting appears on the colon. Note that this works properly in Neovim 0.6.0.

**Comment by zeertzjq** [comment]
Already fixed by #18480
