### ISSUE TITLE
Bug in Markdown mapping

### ISSUE THREAD

**Issue by ignamartinoli** [neovim/neovim#18736]
### Neovim version (nvim -v)

0.8.0-dev+11-gd3121f1e6-dirty

### Vim (not Nvim) behaves the same?

I'm going to try it and update the issue

### Operating system/version

Gentoo Linux

### Terminal name/version

kitty 0.25.0

### $TERM environment variable

xterm-kitty

### Installation

Gentoo Repository

### How to reproduce the issue

1. Open a **Markdown** file with **Neovim**
2. Run `:lua vim.opt_local.spell = true` and `vim.opt.spelllang = 'en'` to activate spell checking
3. Run ``:lua vim.keymap.set('i', '<C-s>', [[<C-g>u<Esc>[s1z=`]a<C-g>u]])`` to map `<C-s>` to take the nearest spelling error and fix it
4. Hit some random keystrokes to make wrong text
5. Hit `<C-s>`

### Expected behavior

The spelling mistake to be corrected

### Actual behavior

I receive the message `search hit TOP, continuing at BOTTOM` and enter `NORMAL` mode

**Comment by muniter** [comment]
Hello.

I can't reproduce this issue, I tried it with my config, and with `nvim --clean`, manually step by step and with this mouthful.

```bash
./build/bin/nvim --clean test.md +"set spell spelllang=en" +"lua vim.keymap.set('i', '<C-s>', [[<C-g>u<Esc>[s1z=]au]])" +"normal iwrrrongspeeling" +"startinsert" +"call nvim_input('<C-s>')"
```

And it works every time it changes `wrrrongspeeling` to `Wrongs peeling`.

**Comment by ignamartinoli** [comment]
I actually tried it on root and it worked. I would say that maybe some plugin is messing it up, but the mapping is declared in `.config/after/ftplugin/markdown.lua` and on **LaTeX** it works fine. Is there a way to debug this further?

**Comment by zeertzjq** [comment]
What do `maparg("\<C-S>")` and `maparg("\<*C-S>")` show?

**Comment by ignamartinoli** [comment]
`:echo maparg("\<C-S>", "i")` and `:echo maparg('<C-S>', "i")` both shows ``<C-G>u<Esc>[s1z=`]a<C-G>u`` (the "i" parameter is because the mapping is defined only for Insert mode)
