### ISSUE TITLE
lsp sends textDocument/didChange version twice

### ISSUE THREAD

**Issue by mosheavni** [neovim/neovim#18734]
### Neovim version (nvim -v)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@Monterey  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

### Language server name/version

terraform-ls 0.27.0

### Operating system/version

macOS 12.2.1

### Steps to reproduce

1. Create a `minimal-init.lua` file:

```bash
mkdir /tmp/tfls-crash-test/
cd /tmp/tfls-crash-test/
curl -sLO https://gist.githubusercontent.com/mosheavni/4adb8b498e369849a6d301294332fd8e/raw/5ac421a3ca0f4611980630769e046b3b60647f85/minimal_init.lua
```

2. Create a simple terraform with aws provider file, and open that file with neovim >= 0.7 

```bash
cd /tmp/tfls-crash-test/
cat <<EOF > main.tf
resource "aws_alb" "name" {
  name = "test"
  subnets = ["1","2"]
  load_balancer_type = "testt"
  idle_timeout = "900"
  tags_all = {
    env = "prod"
  }
}
EOF
nvim -nu minimal_init.lua main.tf
```

3. Play around with the completion (ctrl+space) inside the aws block, add `tags` and `tags_all` blocks, in about ~5 minutes the server will crash with the above mentioned error logs

### Expected behavior

The language client (neovim) should not send the document version twice.

### Actual behavior

duplicate document versions sent by client in didChange causes terraform-ls to crash

More details on:
https://github.com/hashicorp/terraform-ls/issues/927
I first thought this issue is on terraform-ls's side so I opened a ticket there,
As you can see from the discussion, It's something they want to ignore, but the fact that neovim sends the version twice is a problem on itself.

```
2022/05/23 22:47:55 opts.go:218: Discarding error from notification to "textDocument/didChange": Old version (1015) received, current version is 1015.
Unable to update file:///Users/mavni/Repos/terraform/prod/eu-west-1/redis/data.tf. This is likely a bug, please report it.
```

### Log file

https://gist.github.com/mosheavni/c5914746d4134779c6f3cb1481e2d597

**Comment by mfussenegger** [comment]
If I am not mistaken this was fixed with https://github.com/neovim/neovim/pull/19314
