### ISSUE TITLE
pass window-ID to callbacks of clickable elements statusline/winbar[/tabline]

### ISSUE THREAD

**Issue by rebelot** [neovim/neovim#18741]
### Feature already in Vim?

no

### Feature description

`%@` elements were sought to be used in the tabline, which does not pertain to any specific window.
However, since the addition of clickable elements to statusline and winbar, it makes sense for the callback to know from which window it was clicked from (so some buffer-specific actions can be made, even if the window is not focused!)

one would expect the callback specified after `%@` to be evaluated in the context of the current buffer/window the displayed element belongs to (like what happens for expressions evaluated within `%{%...%}` block). But this is not the case, since `nvim_get_current_window()` called within the callback returns the value of `g:actual_curwin`.

This is expecially crucial for winbar and statusline if laststatus=2

**Comment by luukvbaal** [comment]
You can get the window id of the clicked window with `getmouspos().winid` in the callback.
