### ISSUE TITLE
Can't brew reinstall on OS X because of libtickit

### ISSUE THREAD

**Issue by firedev** [neovim/neovim#1874]
OS X 10.10

```
$ brew doctor
Your system is ready to brew.

$ brew reinstall --HEAD neovim
==> Reinstalling neovim
==> Cloning https://github.com/neovim/neovim.git
Updating /Library/Caches/Homebrew/neovim--git
==> Checking out branch master
==> make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/usr/local/Cellar/neovim
make[4]: *** [src/mockterm.lo] Error 1
make[3]: *** [build/src/libtickit-stamp/libtickit-install] Error 2
make[2]: *** [CMakeFiles/libtickit.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2

READ THIS: http://git.io/brew-troubleshooting
```
Please advise. Thanks.

**Comment by joshhartigan** [comment]
perhaps try `brew uninstall` followed by `brew install` and see if the same error occurs.

**Comment by jszakmeister** [comment]
@firedev You should move this ticket to the [homebrew-neovim](https://github.com/neovim/homebrew-neovim) project.  But first, you should try the debugging steps in the [README](https://github.com/neovim/homebrew-neovim/blob/master/README.md).

**Comment by firedev** [comment]
Okay, sorry.

**Comment by jszakmeister** [comment]
@firedev No worries!  BTW, it looks like the libtickit dependency needs to be updated.  I'm putting up a PR for it real soon.
