### ISSUE TITLE
clickable element in statusline do not work well with vertical splits and lastatus=3

### ISSUE THREAD

**Issue by rebelot** [neovim/neovim#18740]
### Neovim version (nvim -v)

0.8 af2899aee0b2

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

macOS 12.2

### Terminal name/version

kitty 0.25.0

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

```vim
function! Hello1(...)
  echo "hello 1"
endfunction

function! Hello2(...)
  echo "hello 2"
endfunction

set laststatus=3
set statusline=%@Hello1@hello1%X%=%@Hello2@hello2%X%=
wincmd w
```
manually resize the window so that the rightmost button falls past (on the right of) the vertical split line and notice some werid behavior:

### Expected behavior

mouse click position is registered consistently according to the value of laststatus

### Actual behavior

clicking on hello2 has no effect, moreover it seems that clicks still try to work as if there was `laststatus=2`, i.e, if you click on the rightmost window where "hello1" should have been with laststatus=2, "hello 1" is printed.

**Comment by zeertzjq** [comment]
Fixed by #19390
