### ISSUE TITLE
The return values of functions like winheight() or getwininfo() are incompatible with Vim with winbar enabled

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#18753]
### Feature description

In Vim `w_height` excludes winbar height, while in Nvim `w_height` includes winbar height, this causes the return values of functions like `winheight()` or `getwininfo()` to be incompatible with Vim with winbar enabled.

There are several ways to make this compatible:
1. Make `w_height` exclude winbar height instead. This will requires code changes in many places.
2. Subtract winbar height from `w_height` in functions like `winheight()` and `getwininfo()`. This requires fewer code changes, but it is easy to forget this in the future.

The problem here is one may use the return value of `winheight()` or `nvim_win_get_height()` (both return `w_height`) for two different purposes:
1. For window layout: one may want the return value to include winbar height
2. For text inside the window: one may want the return value to exclude winbar height

**Comment by bfredl** [comment]
No idea about vim but in neovim (for a non-float) `w_height` is the space the window occupies in the window layout and `w_height_inner` is the space available for rendering buffer lines. (TBH our naming of these variables are not great but i am gradually improving it along with refractors)

**Comment by zeertzjq** [comment]
Actually I guess in Vim the purpose of these functions are not very clear either.

**Comment by zeertzjq** [comment]
This also matters for LSP:
<https://github.com/neovim/neovim/blob/7b952793d5c46e862a9cdec3d6ac4762370296ed/runtime/lua/vim/lsp/util.lua#L978>
Here it is apparently the height for the text.
