### ISSUE TITLE
Documentation mentions `FormattingOptions`, but does not explain it

### ISSUE THREAD

**Issue by AlxHnr** [neovim/neovim#18755]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

No. Vim has no builtin lsp support.

### Operating system/version

Fedora 35

### Terminal name/version

Gnome Terminal

### $TERM environment variable

xterm-256color

### Installation

Appimage

### How to reproduce the issue

I looked up `vim.lsp.buf.formatting_sync()` in the docs. The documentation says it can be customized by providing `FormattingOptions`, but a description of this option is nowhere to be found:

```
                                               *vim.lsp.buf.formatting_sync()*
formatting_sync({options}, {timeout_ms})
                Performs |vim.lsp.buf.formatting()| synchronously.

                Useful for running on save, to make sure buffer is formatted
                prior to being saved. {timeout_ms} is passed on to
                |vim.lsp.buf_request_sync()|. Example:


    autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()
 

                Parameters: 
                    {options}     (table|nil) with valid `FormattingOptions`
                                  entries
                    {timeout_ms}  (number) Request timeout

                See also: 
                    |vim.lsp.buf.formatting_seq_sync|
```

I am not sure if it means `'formatoptions'`, because that makes no sense in a lsp context. The implementation prodives some details, but contains a link which is not up-to-date anymore ([here](https://github.com/neovim/neovim/blob/c6d6b8c7eb180f56e87e1427958f91a867f5cc8c/runtime/lua/vim/lsp/util.lua#L1970-L1974)).

### Expected behavior

The documentation should be clear about which arguments can be passed there. Add a section for `FormattingOptions` with a tag to make it discoverable.

### Actual behavior

I can only guess what it means and have to dig deeper into Neovim's source code.

**Comment by mfussenegger** [comment]
`formatting_sync` is already deprecated on master and `format` is the replacement which contains a link explaining the formatting options. I also opened up https://github.com/neovim/neovim/pull/19558 to have the link point directly to the right place
