### ISSUE TITLE
Is section 5 of the registers help page correct?

### ISSUE THREAD

**Issue by danielo515** [neovim/neovim#18754]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

I don't know

### Operating system/version

macOS 12.1

### Terminal name/version

iterm

### $TERM environment variable

does not matter 

### Installation

brew

### How to reproduce the issue

```
:h registers
```
Then go to  section 5

### Expected behavior

When you go to section 5 of the registers documentation, the header mentions three registers `": ". "%` but then the first line refers them with a different name for each one? Or I don't know what that second line is referring to.
I think the first line should contain the same values as the header? Please take a look at the actual behaviour section to see the current content

### Actual behavior

This is what the section says

> 5. Read-only registers ":, ". and "%
> These are '%', '#', ':' and '.'.  You can use them only with the "p", "P",
> and ":put" commands and with CTRL-R.

**Comment by dundargoc** [comment]
https://github.com/vim/vim/pull/10485
