### ISSUE TITLE
Can't `syntax enable` on Maverics 

### ISSUE THREAD

**Issue by adamyonk** [neovim/neovim#1876]
Whenever I try to `:syntax enable` I get the following error: `E484: Can't open file nvim/syntax/syntax.vim`. This always worked for me in `vim`/`mvim` - have I been misunderstanding how that setting works, or has it changed in neovim?

```
NVIM 0.0.0-alpha+201501191756 (compiled Jan 20 2015 09:15:59)
Commit: 487d2ce74a009da1954055b3d6b7735895e2b2a1
```

**Comment by oni-link** [comment]
Wrong path to the nvim runtime files (`nvim --version | grep fall-back`)?

 If you compiled from the sources yourself, try to start nvim with `VIM=neovim_source_directory/runtime nvim` . 
Otherwise you can try the fall-back path from vim (`vim --version | grep fall-back`) and use that path in `VIM=vim_fall-back_path nvim`? With this `:syntax enable` should work.

**Comment by adamyonk** [comment]
I installed with homebrew. Is that something that should've been picked up on install?

```
 ✖ adamyonk
 ➔ vim --version | grep fall-back
  fall-back for $VIM: "/usr/share/vim"
 ✖ adamyonk
 ➔ nvim --version | grep fall-back
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
 ➔ brew info neovim
neovim: HEAD
http://neovim.org
/usr/local/Cellar/neovim/HEAD (1370 files, 21M) *
  Built from source
From: https://github.com/neovim/homebrew-neovim/blob/master/Formula/neovim.rb
==> Dependencies
Build: cmake ✔, libtool ✔, automake ✔, autoconf ✔, pkg-config ✔, gettext ✔
```

**Comment by oni-link** [comment]
The fall-back path is given by `"${CMAKE_INSTALL_PREFIX}/share/nvim", so when installing, the path should be adjusted (if building from the sources). But I cannot help you with homebrew, don't know how it works.

**Comment by fwalch** [comment]
The output you posted says `fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"`, which looks alright. The error message in your first post, however, indicates it's looking for `nvim/syntax/syntax.vim`, which is quite strange (I believe it should say `/usr/local/Cellar/neovim/HEAD/share/nvim/runtime/syntax/syntax.vim`). Do you have either `$VIM` or `$VIMRUNTIME` set (try `echo`ing these values)?

Do `VIM=/usr/local/Cellar/neovim/HEAD/share/nvim nvim` or `VIMRUNTIME=/usr/local/Cellar/neovim/HEAD/share/nvim/runtime nvim` work?

**Comment by adamyonk** [comment]
Aha! I had `$VIM` exported in my dotfiles to either `nvim`, `mvim`, or `vim`, based on what was actually installed. Unsetting that fixed this issue. Thanks, @fwalch!
