### ISSUE TITLE
autocompletion for `:make`

### ISSUE THREAD

**Issue by fekir** [neovim/neovim#18779]
### Feature description

When typing "make <tab>" in the bash shell, some targets defined in the makefile are listed
When typing "make <tab>" in the zsh shell, all targets defined in the makefile are listed
When typing ":make <tab>" in neovim, no targets defined in the makefile are listed, only the files in the current directory

For example typing "make a<tab>" in bash and zsh autocompletes in "make all" (if no other targets beginning with a are defined), in nvim ":make a<tab>" does not autocomplete to anything (or to files that begin with a)

Using ":!make" instead of ":make" exhibits the same behavior

It would be nice if nvim, when using ":make", would be able to provide a better integration by autocompleting like bash and zsh (other shells probably too)

If it is already possible through an option, I could not find anything under ":h make"

**Comment by jamessan** [comment]
We're not going to implement a makefile parser.  If someone wants to write a plugin to support this, they're free to do so.

**Comment by fekir** [comment]
@jamessan , @clason 

maybe a makefile parser is an overkill, something like https://dev.to/pbnj/how-to-get-make-target-tab-completion-in-vim-4mj1 might cover most use-cases if not all.

**Comment by jamessan** [comment]
Then you have your solution.  👍🏻

**Comment by fekir** [comment]
No, because the linked solution defines a new command

**Comment by clason** [comment]
I don't see the drawback in that? (`:Make` vs. `:make` can hardly be a deal-breaker.)

**Comment by gpanders** [comment]
`cnoreabbrev make Make`

or define a mapping:

`nnoremap m<space> :Make<space>`

**Comment by jamessan** [comment]
Keep in mind that `:make` is used for more than just Makefiles.  It runs whatever `'makeprg'` tells it to.

**Comment by fekir** [comment]
> I don't see the drawback in that? (`:Make` vs. `:make` can hardly be a deal-breaker.)

No it's not a dealbraker, but it is obviously not the same thing.
This ticket was also a feature request, but a bug ;)


> `cnoreabbrev make Make`

Oh, I'll try it

Nevertheless I believe as default behavior it would be much nicer, just like nvim is already able to autocomplete filenames and other commands.

> Keep in mind that `:make` is used for more than just Makefiles. It runs whatever `'makeprg'` tells it to.

This is IMHO the only argument that speak against implementing something like  https://dev.to/pbnj/how-to-get-make-target-tab-completion-in-vim-4mj1 by default for make, unless neovim can detect if `'makeprg'` is used for makefiles before enabling and disabling auto-completion (unless it could autocomplete for other programs too)
