### ISSUE TITLE
Treesitter: `tsparser:parse()` fails if lua string includes `!` in `vim.cmd`

### ISSUE THREAD

**Issue by notomo** [neovim/neovim#18790]
### Neovim version (nvim -v)

0.8.0-dev+329-gf31a10204

### Vim (not Nvim) behaves the same?

N/A (treesitter)

### Operating system/version

Ubuntu 20.04

### Terminal name/version

wsltty

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

- nvim-treesitter version: `a10b603` (depends lua parser and query)
- minimal.lua
```lua
local path_to_nvim_treesitter = [[/home/notomo/.vim/packages/pack/optpack/opt/nvim-treesitter]]
vim.opt.runtimepath:prepend(path_to_nvim_treesitter)
vim.cmd([[runtime plugin/nvim-treesitter.lua]])
vim.cmd([[TSUpdateSync lua]]) -- assert latest

local str = [[vim.cmd("!echo")]]
local language = "lua"
local tsparser = vim.treesitter.get_string_parser(str, language)
tsparser:parse()
```
- command
```
build/bin/nvim --clean --headless +'luafile ./minimal.lua'
```

### Expected behavior

`tsparser:parse()` does not fail.

### Actual behavior

```
$ build/bin/nvim --clean --headless +'luafile ./minimal.lua'
Parsers are up-to-date!
Error detected while processing command line:
E5113: Error while calling lua chunk: ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:115: Ranges can only be made from 6 element long tables or nodes.
stack traceback:
        [C]: in function 'set_included_ranges'
        ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:115: in function 'parse'
        ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:149: in function 'parse'
        ./minimal.lua:9: in main chunk^C
```

from eab4d03a3

**Comment by lewis6991** [comment]
If this is a serious issue then we may need to revert since I won't be able to look at this for a while.

**Comment by notomo** [comment]
I'm not in much trouble personally.
I can use the following workaround.
```lua
vim.treesitter.get_string_parser(str, language, { injections = { [language] = "" } })
```

**Comment by clason** [comment]
It seems to be specific to the string parser, since the same lua snippet is parsed correctly in a buffer. It's a bit weird since neither the Lua nor the Vim injections make use of the `offset` directive.

**Comment by lewis6991** [comment]
The change modified some of the injection stuff which is why it's broke

**Comment by clason** [comment]
OK, I think I see what's going on: for a string parser, the `self._source` is the string itself rather than a number as in an actual tree, so the region adjustment here is never called:
https://github.com/neovim/neovim/blob/015656abd72b7ccac966f21218c4d7108800237a/runtime/lua/vim/treesitter/languagetree.lua#L267-L282

**Comment by clason** [comment]
Something like
```lua
function LanguageTree:set_included_regions(regions)
  -- Transform the tables from 4 element long to 6 element long (with byte offset)
  for _, region in ipairs(regions) do
    for i, range in ipairs(region) do
      if type(range) == 'table' and #range == 4 then
        local start_row, start_col, end_row, end_col = unpack(range)
        local start_byte = 0
        local end_byte = 0
        if type(self._source) == 'number' then
          -- Easy case, this is a buffer parser
          -- TODO(vigoux): proper byte computation here, and account for EOL ?
          start_byte = a.nvim_buf_get_offset(self._source, start_row) + start_col
          end_byte = a.nvim_buf_get_offset(self._source, end_row) + end_col
        elseif type(self._source) == 'string' then
          -- string parser, single `\n` delimited string
          start_byte = vim.fn.byteidx(self._source, start_col)
          end_byte = vim.fn.byteidx(self._source, end_col)
        end

        region[i] = { start_row, start_col, start_byte, end_row, end_col, end_byte }
      end
    end
  end

  self._regions = regions
  -- Trees are no longer valid now that we have changed regions.
  -- TODO(vigoux,steelsojka): Look into doing this smarter so we can use some of the
  --                          old trees for incremental parsing. Currently, this only
  --                          effects injected languages.
  self._trees = {}
  self:invalidate()
end
```

**Comment by notomo** [comment]
@clason 
Thanks!
I confirmed that the change fixed this issue.

📝 To confirm, I replaced the following lines, rebuilt nvim and execute minimal.lua.
https://github.com/neovim/neovim/blob/015656abd72b7ccac966f21218c4d7108800237a/runtime/lua/vim/treesitter/languagetree.lua#L265-L291

**Comment by clason** [comment]
Thanks! Did you also test it with your actual (non-minimal) code that led you to open this issue?

**Comment by notomo** [comment]
> Did you also test it with your actual (non-minimal) code that led you to open this issue?

Yes.
