### ISSUE TITLE
[RFC]: Use namespaces instead of augroups

### ISSUE THREAD

**Issue by Chromosore** [neovim/neovim#18797]
I'm a namespace lover and I like internal consistency so I think that augroups should become namespaces. I've seen by reading related sources that namespaced autocommands have already been considered (see [autocmd.h]) but I'd like to go even further and basically remove augroups in favour of namespaces.

So my questions are:
- Is this even a good idea?
- If it is, how would the namespaces be named to avoid collision?
  I was thinking of something like `:augroup foo` → `namespace(augroup-foo)` or maybe with a custom character similar to `<Plug>`, maybe `<Auto>`, so `:augroup foo` → `namespace(<Auto>foo)`.

I'm aware that this may be an big task but I'm willing to try to implement this if it is any good.

[autocmd.h]: https://github.com/neovim/neovim/blob/e9803e1de6497ee21f77f45cf2670c2fe4e8ab22/src/nvim/autocmd.h#L80=

**Comment by clason** [comment]
I'm sorry, that would be a hugely breaking change for little benefit. Even with the Neovim API, autocommands have to remain compatible with OG Vim, otherwise we lose the complete vimscript plugin ecosystem (which is one of the main features of Neovim).

**Comment by Chromosore** [comment]
Yeah but my point is to make it transparent enough so vimscript wouldn't even be aware of this.

**Comment by clason** [comment]
Then what would be the point? Having two different APIs is _worse_.

**Comment by Chromosore** [comment]
Ok, fair. I guess letting vimscript use augroups is fine.

**Comment by Chromosore** [comment]
Well I changed my mind and I think that I've explained my idea poorly.

Ok, replacing augroups with namespaces *under the hood* doesn't solve any real problem, but if it is planned to introduce namespaced autocommands, why not make the change right now?

In fact, replacing augroups with namespaces wouldn't introduce any new API (at least on the vimscript side). It would just mean that internally, autocommands use namespaces for grouping instead of augroups. Thus, vimscript would use namespaces while thinking that they use augroups. Basically, merge the two concepts.

This would mean that this code
```vim
augroup foo-bar-baz
  au VimEnter * echo 'foo'
augroup END
```
would roughly translate to this code
```lua
local ns = vim.api.nvim_create_namespace('augroup-foo-bar-baz')
-- or ...namespace(nvim_replace_termcodes('<Auto>foo-bar-baz')) to avoid any collision
vim.api.nvim_define_autocmd('VimEnter', {
  group = ns;
  command = "echo 'foo'";
})
```

Lastly, my main motivation for this is actually very different but the gist of it is that I'd like to be able to tie all the interactions that a plugin has with Neovim to a namespace.

**Comment by clason** [comment]
Sorry, that's impossible, due to the `:h api-contract`. Autogroups are going nowhere, but namespaces can be added. I fail to see how that doesn't address your use case.

**Comment by Chromosore** [comment]
To be clear: what I want to do is to keep the augroup API but make it use namespaces *internally*. That's it. (also, is it the lua snippet that breaks the `api-contract`? it was just an illustration)

**Comment by clason** [comment]
> To be clear: what I want to do is to keep the augroup API but make it use namespaces internally.

How would that help you if you can't access it?

> also, is it the lua snippet that breaks the api-contract?

Yes, since `nvim_create_autocmd` explicitly states
> • group (string|integer) optional: the autocommand group name or id to match against.

**Comment by Chromosore** [comment]
Oh. I believe you misunderstood what I wanted to do. First, no change to vimscript. Second, the function `nvim_create_augroup()` would return a namespace ID, which would be indistinguishable from an augroup ID. Third, if group was provided as a string, it would create a new namespace just as a new autogroup is created  when it doesn't exist.

**Comment by Chromosore** [comment]
If you prefer, I'd like to add support for namespaces to autocmd and at the same time, remove the notion of `augroup` internally. Even `:augroup` would use a namespace.

**Comment by clason** [comment]
Sorry, but you are missing my point: the `nvim_XXX` API is covered by a strong contract, no matter whether you access it from vimscript (via `:call nvim_foo()`), Lua (via `vim.api.nvim_foo()`), or RPC. And what you're asking for is forbidden by that contract.

**Comment by Chromosore** [comment]
What do you mean? The api is the public part of it and the `augroup` ID is basically opaque. What I want is to change the internal workings of neovim. The code that already exists would keep running, it would be just the way it is handled internally that would be different.

**Comment by clason** [comment]
No. The distinction between `augroup` and `namespace` is meaningful, and you cannot remove it without breaking a massive amount of plugins.

Anyway, I am done arguing about this.

**Comment by Chromosore** [comment]
Ok I'll just implement support for namespaces in autocommands then. Is that ok?

**Comment by justinmk** [comment]
Interesting idea. I'm not sure this would be a breaking change, as long as `:au!` (clear) still works. If it ends up as a net reduction of code, this could be worth doing.

**Comment by Chromosore** [comment]
Update for whoever is seeing this: I've given up.

I've tried to replace augroups by namespaces. At first it was going alright (mostly swapping augroups maps with namespace maps) but then I've come across deleted augroups and the completion for the `:augroup` command, which would both require to track extra data (list of deleted / defined augroups), which would end up as duplicated.

With hindsight, I've realised that this wasn't achievable *cleanly* without any loss of feature, and I've thus given up.

Implementing namespaced autocommands is still an option though, but I doubt it would be quite useful anyway, except for my very usecase (tying a plugin to a namespace), which would currently be useless (but I have my reasons).

**Comment by justinmk** [comment]
@Chromosore thanks for the followup, that's valuable anyway! 

> but then I've come across deleted augroups and the completion for the `:augroup` command, which would both require to track extra data (list of deleted / defined augroups), which would end up as duplicated

Adding more "inspection" of namespaces is something we want to do generally. So I wouldn't consider that duplicated, rather it's essential. I don't follow why it would be necessary to track deleted augroups though?

**Comment by Chromosore** [comment]
Tracking deleted augroups is required because of backwards compatibility, I think. See [a comment in autocmd.c][autocmd.c].

The problem is that when an augroup is deleted, if there are autocmds left in it they are kept but they still show up as if they were in a separate group (try to create an autocmd in a group and then delete the group: the autocmd will show up as if it were in the group `--Deleted--`).

A list of deleted augroups must be kept because each deleted augroup with aucmds left creates its own `--Deleted--` group. This is more aesthetic than anything else though because it only impacts the list produced by `:autocmd` I think.

[autocmd.c]: https://github.com/neovim/neovim/blob/6486b0345a69c2bb134f00feacad75852ebeef7e/src/nvim/autocmd.c#L452

**Comment by justinmk** [comment]
> Tracking deleted augroups is required because of backwards compatibility, I think. See [a comment in autocmd.c](https://github.com/neovim/neovim/blob/6486b0345a69c2bb134f00feacad75852ebeef7e/src/nvim/autocmd.c#L452).

Oh, funny. We could consider dropping that.
