### ISSUE TITLE
option 'formatoptions' not work propetly in config file

### ISSUE THREAD

**Issue by n1rdeks** [neovim/neovim#18799]
### Neovim version (nvim -v)

0.7

### Vim (not Nvim) behaves the same?

no, vim 8.2.5xxx

### Operating system/version

gentoo

### Terminal name/version

urxvt

### $TERM environment variable

rxvt-unicode-256color

### Installation

package manager

### How to reproduce the issue

init.lua

>vim.bo.formatoptions = "tcqj"

### Expected behavior

```:verbose set formatoptions```

>formatoptions=tcqj

### Actual behavior

```:verbose set formatoptions```

>formatoptions=jcroql

**Comment by zeertzjq** [comment]
Does changing it to `vim.o.formatoptions = 'tcqj'` work?
