### ISSUE TITLE
`nvim_strwidth` does not work correctly with control characters

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#18801]
### Neovim version (nvim -v)

Latest master

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

From source

### How to reproduce the issue

`:lua = vim.api.nvim_strwidth('^G')`, where `^G` is produced by `<C-v><C-g>`

### Expected behavior

2

### Actual behavior

1

**Comment by zeertzjq** [comment]
`nvim_strwidth` is a very old APi, so I don't think its behavior should be changed.
