### ISSUE TITLE
doxygen.vim: Error detected while processing

### ISSUE THREAD

**Issue by cryptomilk** [neovim/neovim#18806]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

openSUSE

### Terminal name/version

konsole/tmux

### $TERM environment variable

tmux-256color

### Installation

system package manager

### How to reproduce the issue

Open a file C file with doxygen comments e.g.:
https://gitlab.com/samba-team/samba/-/blob/master/source3/rpc_server/rpc_server.c

### Expected behavior

The file opens without an error.

### Actual behavior

```
Error detected while processing /usr/share/nvim/runtime/syntax/doxygen.vim:
line  502:
E12: Command not allowed from exrc/vimrc in current dir or tag search:     aug doxygengroup
Error detected while processing function <SNR>10_SynSet:
line   25:
E171: Missing :endif
```

Commenting out the `aug doxygengroup` in doxygen.vim fixes it temporarily ...

**Comment by zeertzjq** [comment]
This should be reported to the maintainer:
```vim
" DoxyGen syntax highlighting extension for c/c++/idl/java
" Language:     doxygen on top of c, cpp, idl, java, php
" Maintainer:   Michael Geddes <vimmer@frog.wheelycreek.net>
" Author:       Michael Geddes
" Last Change: December 2020
" Version:      1.30
```
