### ISSUE TITLE
Suggestion: swap the names of mapmode-v and mapmode-x

### ISSUE THREAD

**Issue by melkster** [neovim/neovim#18807]
### Feature already in Vim?

No

### Feature description

The name of `mapmode-v` causes a lot of confusion because it maps to both visual _and_ select mode. A lot of people seem to, because of this naming, miss the mapping to select mode. Currently, to map to only visual mode one has to use `mapmode-x` as seen in this table from `:help mapmode-x`:

```help
    COMMANDS                                  MODES
                                          Visual    Select
:vmap  :vnoremap  :vunmap  :vmapclear	    yes      yes
:xmap  :xnoremap  :xunmap  :xmapclear	    yes       -
:smap  :snoremap  :sunmap  :smapclear	    -	     yes
```

I've found many plugins that make this mistake, for instance [vim-indent-object](https://github.com/michaeljsmith/vim-indent-object/pull/28), [bullets.vim](https://github.com/dkarter/bullets.vim/blob/f3b4ae71f60b5723077a77cfe9e8776a3ca553ac/plugin/bullets.vim#L1004), [vim-markdown](https://github.com/preservim/vim-markdown/blob/3a9643961233c2812816078af8bd1eaabc530dce/ftplugin/markdown.vim#L734), etc., etc. In fact, try running `:vmap` right now with your config and you'll likely find several plugins doing `vnoremap`, when they meant to do `xnoremap`.

Select mode is (among other things) very useful when jumping around in snippets.

My suggestion is to simply swap the names of `mapmode-v` and `mapmode-x` because it makes more sense for `v` to represent visual mode and `x` to represent visual and select mode.

**Comment by clason** [comment]
You'll have to convince Bram of that; we don't make such changes to features inherited from Vim -- that would lead to massive confusion and potential breakage of plugins.
