### ISSUE TITLE
[No Name] buffer is created when `hidden` is on

### ISSUE THREAD

**Issue by rockyzhang24** [neovim/neovim#18819]
### Neovim version (nvim -v)

0.8.0 dev (built from repo with commit c632f64e247c672e425f609bb47a9ab0517a4c31)

### Vim (not Nvim) behaves the same?

No. Because vim does not set `hidden` by default

### Operating system/version

macOS 12.4 (the latest)

### Terminal name/version

kitty 0.25.1

### $TERM environment variable

xterm-kitty

### Installation

Built from repo

### How to reproduce the issue

I stumbled across this issue when I use `vim-fugitive`. To reproduce:

1. First of all, open a tracked but unstaged file
2. Execute `:tab Git`
3. In fugitive index, move cursor to this unstaged file and then execute `dd`
4. Run `:ls` and we can find an empty buffer named `[No Name]`

When I set `nohidden`, this issue is gone. 

Also, please see the details here (https://github.com/tpope/vim-fugitive/issues/2004)

Thank you very much. 

### Expected behavior

The `[No Name]` buffer shouldn't be created.

### Actual behavior

The `[No Name]` empty buffer is created.

**Comment by justinmk** [comment]
> No. Because vim does not set `hidden` by default

Compare how Vim behaves with 'hidden' set.

**Comment by rockyzhang24** [comment]
Thank you. So that's the normal behavior when `hidden` is set for both Vim and Neovim, and no approach to prevent Vim/Neovim from creating this empty buffer if `hidden` is set, right?
