### ISSUE TITLE
[WinBar bug?] WinLeave event + Telescope exit = E36 Not enough room

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#18817]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+334-ge9803e1de

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Linux Mint 20

### Terminal name/version

Alacritty 0.9.0

### $TERM environment variable

alacritty

### Installation

Prebuilt nightly from repo

### How to reproduce the issue

**init.vim**

```vim
call plug#begin()
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

augroup Events
    autocmd!
    autocmd WinLeave * setlocal winbar=%f
augroup END
```

1. Start nvim with file `nvim ~/.config/nvim/init.vim`
2. Create a vsplit `vsplit`
3. Start Telescope `:Telescope find_files`
4. Exit Telescope via `ESC` `ESC`

### Expected behavior

Telescope should quietly close.

### Actual behavior

Not enough room error will result:

![Failure](https://user-images.githubusercontent.com/11382509/171317788-6a70dc3e-e8f4-4bf7-b6b6-013a7a33d3b4.png)

**Comment by bluz71** [comment]
This issue can cause segfaults in Neovim.

Why can’t Neovim itself do this check?

**Comment by zeertzjq** [comment]
The segfault is caused by <https://github.com/nvim-telescope/telescope-fzf-native.nvim/>

**Comment by bluz71** [comment]
Ok, that changes the scope of this issue.

Do you recommend I open an issue in the Telescope repository?

**Comment by zeertzjq** [comment]
https://github.com/nvim-telescope/telescope-fzf-native.nvim/issues/71
