### ISSUE TITLE
lua table methods not working

### ISSUE THREAD

**Issue by kflak** [neovim/neovim#18818]
### Neovim version (nvim -v)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Arch Linux 5.15.40.43.realtime1-1-rt-lts

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

xterm-256color

### Installation

pacman

### How to reproduce the issue

nvim --clean
:lua table.pack(1,2,3)

### Expected behavior

Return a table.

### Actual behavior

I get this error:
```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'pack' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

**Comment by zeertzjq** [comment]
Nvim only supports Lua 5.1, which does not have `table.pack()`.

**Comment by kflak** [comment]
Thanks!
