### ISSUE TITLE
No straightforward way to break undo sequence immediately in Insert mode from a script

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#18828]
### Neovim version (nvim -v)

Latest master

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

From source

### How to reproduce the issue

Put this into `mwe.lua`:
```lua
local function feed_keys(s)
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(s, true, true, true), 'n', false)
end

local function working()
  assert(vim.fn.mode() == 'i')
  feed_keys('foo<C-g>ubar')
end

local function insert_text_at_cursor(text)
  local line = vim.fn.line('.') - 1
  local col = vim.fn.col('.') - 1
  vim.api.nvim_buf_set_text(0, line, col, line, col, {text})
end

local function broken()
  assert(vim.fn.mode() == 'i')
  insert_text_at_cursor('foo')
  feed_keys('<C-g>u')
  insert_text_at_cursor('bar')
end

vim.keymap.set('i', '<C-a>', working)
vim.keymap.set('i', '<C-b>', broken)
```

- `nvim --clean`
- `:source mwe.lua`
- `i<C-a><Esc>`
- `u` → deletes "bar" ✅
- `u` → deletes "foo" ✅
- `i<C-b><Esc>`
- `u` → deletes "foobar" ❌

### Expected behavior

`<C-g>u` breaks the undo sequence, including for buffer edits made via API functions.

### Actual behavior

`<C-g>u` is unaware that a change to the buffer has happened after `nvim_buf_set_text`.

**Comment by zeertzjq** [comment]
Does `vim.schedule()`ing the second `insert_text_at_cursor()` work?

**Comment by andmis** [comment]
Yes, if you wrap the second `insert_text_at_cursor` call in a `vim.schedule`, then `u` just gets rid of the "bar". (And the `<C-g>u` is still necessary in this case – I just double-checked.)

**Comment by zeertzjq** [comment]
So that problem here is that you cannot break undo sequence immediately in Insert mode from a script.

**Comment by andmis** [comment]
Yes, I guess the root cause is that the commands passed to `feedkeys` are not executed synchronously/immediately. Maybe this should be documented, as well.

**Comment by matveyt** [comment]
@andmis This all is documented at `:h feedkeys()`. The info is not repeated under `:h nvim_feedkeys()` but it has the link to the original function.

**Comment by andmis** [comment]
https://github.com/vim/vim/pull/10511

**Comment by andmis** [comment]
It looks like Bram thinks this is not worth it, would you like me to port this patch to Neovim?

**Comment by bew** [comment]
> It looks like Bram thinks this is not worth it, would you like me to port this patch to Neovim?

Give him some time, maybe he has a life ^^

**Comment by zeertzjq** [comment]
I don't think anything else will be done regarding this issue, now that the following is present in docs:
```
					*undo-break* *undo-close-block*
To do the opposite, use a new undo block for the next change, in Insert mode
use CTRL-G u.  This is useful if you want an insert command to be undoable in
parts.  E.g., for each sentence.  |i_CTRL-G_u|

Setting the value of 'undolevels' also closes the undo block.  Even when the
new value is equal to the old value: >
	let &undolevels = &undolevels
```

**Comment by Sleepful** [comment]
For posterity, this is what I ended up doing:

```lua
vim.api.nvim_feedkeys(
-- create new "undo" point
  vim.api.nvim_replace_termcodes('<C-g>u', true, true, true),
  'n', false)
-- then continue with whatever is next, even tho it is technically not synchronous:
cmp.confirm()

```

**Comment by Sleepful** [comment]
Not off-topic for this issue 😅
