### ISSUE TITLE
Appimage: Warning message at startup

### ISSUE THREAD

**Issue by Abhinav1217** [neovim/neovim#18826]
### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux (Solus os)

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

Appimage

### How to reproduce the issue

N.B.
 - Running `.nvim --clean` doesn't cause issue.
 - This is a fresh install so no config files have been created.
 - I am using `appimagelauncherd` to manage my appimages. 

When I am running `nvim` I am getting following message:
![Screenshot from 2022-06-01 16-25-37](https://user-images.githubusercontent.com/740584/171390472-646c823d-1661-4cd3-a915-410fc9b4c413.png)

Other that the message, there seems to be no issue in its working as far as I can tell. I just press enter and it brings the nvim default window as expected. But the error is confusing as this is a fresh install and I am yet to configure stuff on my system. 

### Expected behavior

Should start immediately without showing any error or warning message before start.

### Actual behavior

Shows the following warning message before starting 
![Screenshot from 2022-06-01 16-25-37](https://user-images.githubusercontent.com/740584/171390472-646c823d-1661-4cd3-a915-410fc9b4c413.png)

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by Abhinav1217** [comment]
>  Can you try the development version?
Yup, Development version also have same issue.

> The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS.
I usually have nvim from my package manager (solus os uses eopkg) but for my current situation, I would prefer to have appimage version.  BTW this error also shows on my manjaro system, and at my office's ubuntu system .

> Check :version to confirm that you are using the latest version.
I just downloaded the dev release of appimage. And yesterday, I downloaded the latest release of appimage from release page. 
This is the `:version` output on the dev appimage.
```
Error detected while processing /tmp/.mount_nvim.aOzJtyI/usr/share/nvim/runtime/syntax/syntax.vim:
line   42:
E216: No such group or event: filetypedetect BufRead
:version
NVIM v0.8.0-dev+347-gc632f64e2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOC
ATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -W
double-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-att
ribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong
 -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM
_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/s
rc -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/a
uto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az243-604

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
Press ENTER or type command to continue
```

**Comment by justinmk** [comment]
> * Running `.nvim --clean` doesn't cause issue.

Does it happen if you delete/rename your `~/.config/` ?

**Comment by Abhinav1217** [comment]
This was on a fresh install system, so I have not made any configurations either for vim or neovim at that time. It only happens for appimage version. I installed neovim from my distro's package manager and it doesn't have this issue. Appimage on otherhand still shows this issue irrespective of availability of `~/.config/neovim`

**Comment by innerout** [comment]
I am having the same issue with no configuration on CentOS 7.

**Comment by dundargoc** [comment]
Can anyone confirm or recreate this issue? This feels like a build system problem that might've been solved.
