### ISSUE TITLE
Very slow file explorer

### ISSUE THREAD

**Issue by ahmedelgabri** [neovim/neovim#1882]
When I try to open the file explorer using one of these commands `:Lex`, `:Sex` or `:Vex` it takes on avg no less than 8secs to open. Any idea why?

**Comment by ReneFroger** [comment]
As far as I know, Netrw was a plugin delivered with Vim. 
Propably it has something to do with the translation from Vimscript to Lua, which is going wrong.

**Comment by jszakmeister** [comment]
The default build is a debug build, which can be quite slow.  You probably want to do `make CMAKE_BUILD_TYPE=Release` or `make CMAKE_BUILD_TYPE=RelWithDebInfo`.  You'll need to do a `make distclean` first, as CMake caches the build type.

More instruction can be found on the [wiki](github.com/neovim/neovim/wiki/Building-Neovim#release-build-optimized-ndebug).

**Comment by tarruda** [comment]
> When I try to open the file explorer using one of these commands :Lex, :Sex or :Vex it takes on avg no less than 8secs to open. Any idea why?

Could you post a vimrc with detailed steps of how to reproduce this?

**Comment by ahmedelgabri** [comment]
@jszakmeister Thanks, will check.

@tarruda I have a mapping to [`<leader> d`](https://github.com/ahmedelgabri/dotfiles/blob/master/vim/vimrc.local#L516) to toggle file explorer.

**Comment by justinmk** [comment]
@ahmedelgabri do you have clipboard=unnamed?

**Comment by ahmedelgabri** [comment]
@justinmk yes

**Comment by justinmk** [comment]
@ahmedelgabri  try disabling that, as an experiment.

**Comment by ahmedelgabri** [comment]
@justinmk It's faster but still a couple of secs (~3sec) to open.

**Comment by pengux** [comment]
I have the same problem. Using netrw on vim is quick, but on neovim it's very slow. I don't have clipboard set to anything `set clipboard?` returns empty

**Comment by justinmk** [comment]
@ahmedelgabri  @pengux Does this still happen on latest master?

**Comment by pengux** [comment]
Unfortunately no, that didn't solve the issue for me.

**Comment by ahmedelgabri** [comment]
Fixed for me @justinmk :+1: 

@pengux make sure you re-install/update the version you have. Not sure what system you are using, so you can check here on how to update https://github.com/neovim/neovim/wiki/Installing-Neovim

**Comment by pengux** [comment]
Yes, sorry, seems to be fixed for me too. It was OS X El Capitan which was slowing down before, a reinstall of neovim and a restart of Mac OS X seems to fixed it.
