### ISSUE TITLE
Exceptions are silently dropped by runtime! command used inside try/catch

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#18842]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

No, 8.2.4975

### Operating system/version

CentOS 7.9

### Terminal name/version

xfce4-terminal 0.8.7.4

### $TERM environment variable

tmux-256color

### Installation

Downloaded release tarball from Github

### How to reproduce the issue

Create a temporary directory, and inside it create these 3 files:

**init.vim**
```
execute 'set runtimepath +='.expand('<sfile>:p:h')
try
  runtime! throw*.vim
  echomsg "No errors!"
catch
  throw v:exception
endtry
```

**throw1.vim**
```
echomsg "Sourcing throw1"
throw "Exception!"
```

**throw2.vim**
```
echomsg "Sourcing throw2"
```

Now run `nvim -u /path/to/init.vim` (and compare the output against `vim -N --clean -u /path/to/init.vim`)

### Expected behavior

It should print
```
Sourcing throw1
Sourcing throw2
Error detected while processing /path/to/init.vim:
line    6:
E605: Exception not caught: Exception!
```

### Actual behavior

It prints:

```
Sourcing throw1
Sourcing throw2
No errors!
```

**Comment by ddickstein** [comment]
The implication of this issue is pretty bad: if an exception is raised by while an ftplugin is being sourced and that ftplugin is not the last one that is sourced for that filetype, the exception is never reported to the user.

**Comment by zeertzjq** [comment]
Sounds similar to #13490

**Comment by ddickstein** [comment]
It's not reproducible in 8.0.1763, 8.1.1602, 8.2.4975, or 8.2.5053.
