### ISSUE TITLE
No Color? 

### ISSUE THREAD

**Issue by belph** [neovim/neovim#1884]
Hello all, 
I recently decided I would try and help out with Neovim (likely something with the libuv porting, although I'm somewhat unclear about what remains to be done...but that's another issue), so I cloned the repo yesterday and decided to build it to make sure I had all required dependencies and what-not. After this, I decided to actually try out the editor. 

I copied over my `~/.vimrc` and `~/.vim/` folders to new `~/.nvimrc` and `~/.nvim/` folders, respectively. I know that I did that much correctly, since edits to my `.nvimrc` are reflected in Neovim and I am able to open NERDtree (which I have installed) in Neovim without issue. For some reason, however, my color schemes won't work. Even more curious is that, when I change between them, the background of Neovim correctly reflects the color scheme's background. Nonetheless, no matter what I do, the text remains white. Is this a known issue, or am I doing something wrong? 

I'm running Linux Mint 16, and I am trying to open Neovim in the standard MATE terminal (this is the same environment in which I use Vim without issue). 

Here's what I've tried:

1. Made sure that the `filetype` within Neovim was correct. No change. 

2. Ran `:syntax on`. Gave me an error about not being able to access (I'm doing this from memory, so the path may not be exact) `/usr/local/share/nvim/syntax`

Lastly: I understand that this is Pre-alpha. I was just wondering if there is a known fix for this, or if this is a bug which needs fixing.

**Comment by fwalch** [comment]
> Ran :syntax on. Gave me an error about not being able to access (I'm doing this from memory, so the path may not be exact) /usr/local/share/nvim/syntax

This sounds like Neovim can't find the runtime files. Did you use `make install` to install Neovim? Just copying the binary into your `PATH` is not enough, unfortunately.

If you're using Mint, maybe the [Ubuntu PPA](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable) would work as well.

**Comment by oni-link** [comment]
@belph, you could try https://github.com/neovim/neovim/issues/1876#issuecomment-71264610 if you don't use `make install`.

**Comment by justinmk** [comment]
As @fwalch said. We will have sanity checks for this soon.

**Comment by belph** [comment]
I just wanted to confirm that I did not use `make install` to install Neovim and the solution mentioned by @oni-link did the trick.

Thanks for the help.

**Comment by twbmsp** [comment]
Hi,

Just if it can help someone, I had the syntax on, (I could saw it because I was using a colorscheme with bold keywords) but no colours. I had to do... 

    export TERM=xterm

...to get it working. Following the advices given there : http://vim.wikia.com/wiki/Using_GUI_color_settings_in_a_terminal.  

Regards.

**Comment by justinmk** [comment]
@twbmsp That won't be needed after https://github.com/neovim/neovim/issues/2912
