### ISSUE TITLE
Why is BufAdd called after BufEnter?

### ISSUE THREAD

**Issue by lgyin** [neovim/neovim#18853]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

no check

### Operating system/version

macOS 10.15

### Terminal name/version

kitty 0.25.1

### $TERM environment variable

xterm-256

### Installation

homebrew

### How to reproduce the issue

1. Register `BufAdd` and `BufEnter`
2. Use `vim.lsp.buf.definition()` to open another file

### Expected behavior

The document says that `BufAdd` comes before `BufEnter`
![Screen Shot 2022-06-04 at 6 57 02 AM](https://user-images.githubusercontent.com/11213808/171965206-35b9628e-65d5-4aae-a1ba-39be6df55c55.png)
![Screen Shot 2022-06-04 at 6 57 50 AM](https://user-images.githubusercontent.com/11213808/171965215-d804a8d7-5155-4c26-927a-cba4b04095f3.png)

### Actual behavior

![Screen Shot 2022-06-04 at 6 55 41 AM](https://user-images.githubusercontent.com/11213808/171965165-c9ab1298-89bb-4bc0-86d7-881bae12454e.png)

**Comment by zeertzjq** [comment]
The buffer added by `bufadd()` is unlisted:
```
bufadd({name})						*bufadd()*
		Add a buffer to the buffer list with String {name}.
		If a buffer for file {name} already exists, return that buffer
		number.  Otherwise return the buffer number of the newly
		created buffer.  When {name} is an empty string then a new
		buffer is always created.
		The buffer will not have 'buflisted' set and not be loaded
		yet.  To add some text to the buffer use this: >
			let bufnr = bufadd('someName')
			call bufload(bufnr)
			call setbufline(bufnr, 1, ['some', 'text'])
<		Can also be used as a |method|: >
			let bufnr = 'somename'->bufadd()
```

`BufAdd` is triggered when adding a buffer to the buffer list (e.g. when making a buffer listed):
```
							*BufAdd*
BufAdd				Just after creating a new buffer which is
				added to the buffer list, or adding a buffer
				to the buffer list, a buffer in the buffer
				list was renamed.
```

`jump_to_location()` first creates an unlisted buffer using `vim.uri_to_bufnr()` (which calls `bufadd()`), then triggers `BufEnter` using `nvim_set_current_buf()`, then triggers `BufAdd` by making the buffer listed.
