### ISSUE TITLE
'inccommand' too eagerly triggered for ':s'

### ISSUE THREAD

**Issue by gelguy** [neovim/neovim#18857]
### Neovim version (nvim -v)

0.8.0  commit c6d747e6a5227e17556c62e16ed054398eb1a89a

### Vim (not Nvim) behaves the same?

no, vim does not have `inccommand`

### Operating system/version

WSL Ubuntu

### Terminal name/version

wsltty

### $TERM environment variable

xterm-256color

### Installation

Built from source

### How to reproduce the issue

```vim
" test.vim
autocmd CmdlineChanged * call timer_start(0, {-> Update()})

let s:win_opts = {
      \ 'relative': 'editor',
      \ 'height': 10,
      \ 'width': 10,
      \ 'row': 0,
      \ 'col': 0,
      \ 'focusable': 0,
      \ }

let s:buf = nvim_create_buf(v:false, v:true)
let s:win = nvim_open_win(s:buf, 0, s:win_opts)

function! Update()
  call nvim_buf_set_lines(s:buf, 0, -1, v:true, [getcmdline()])
  redraw
endfunction
```

- `nvim -u test.vim`
- Type `:sabcdef`

### Expected behavior

The floating window is updated as the cmdline is typed.

### Actual behavior

The floating window is empty for `:s`, and only updates again after `a` is typed.

I think this is caused by
https://github.com/neovim/neovim/blob/c6d747e6a5227e17556c62e16ed054398eb1a89a/src/nvim/ex_docmd.c#L10137-L10138 in `cmd_can_preview`, where `find_ex_command` returns the `substitute` command for the `:s` cmdline. This triggers the inccommand preview state, which results in `redraw`s from timers being disabled (due to https://github.com/neovim/neovim/pull/9783). The floating window only updates correctly after Neovim's internal redraw from the next cmdline change. This can be further tested with `:snomagicabcdef`.

There's 2 issues at hand here:
- `:s` should not trigger `inccommand` since the user is still typing the command name
- Ideally the behavior in https://github.com/neovim/neovim/pull/9783 can be fixed/updated, so `inccommand` doesn't ignore all `redraw`s from timers/events. This will be more relevant as more commands/user-defined commands receive preview functionality.

**Comment by zeertzjq** [comment]
This may fix the problem:
```diff
diff --git a/src/nvim/ex_getln.c b/src/nvim/ex_getln.c
index 7507932b6..8e3dbc147 100644
--- a/src/nvim/ex_getln.c
+++ b/src/nvim/ex_getln.c
@@ -2517,6 +2517,7 @@ static void cmdpreview_show(CommandLineState *s)
   // If preview callback returned 0, update screen to clear remnants of an earlier preview.
   if (cmdpreview_type == 0) {
     update_screen(SOME_VALID);
+    cmdpreview = false;
   }
 end:
   xfree(cmdline);
```
