### ISSUE TITLE
Pre-built source for neovim in the conda package manager?

### ISSUE THREAD

**Issue by lukelbd** [neovim/neovim#18862]
### Feature already in Vim?

Yes, 8.1.0925

### Feature description

The [conda package manager](https://github.com/conda/conda) currently provides a [conda-forge "feedstock"](https://github.com/conda-forge/vim-feedstock) for vim 8.0+ that permits installing vim without root access on arbitrary operating systems: `conda install -c conda-forge vim`. This package manager is very popular in the data science community (there is also a very speedy C++ reimplementation called [mamba](https://github.com/mamba-org/mamba)). Using `conda search -c conda-forge vim` reveals that the earliest version they offer is 8.1.0925.

I'd love to be able to install neovim in this way. I often use remote servers (e.g. compute clusters) without root access and the inability to manage neovim with conda keeps me from switching. It looks like there is already a [feedstock named "neovim"](https://github.com/conda-forge/neovim-feedstock), so enabling `conda install neovim` would be impossible without taking over/expanding that feedstock (discussed in [this thread](https://github.com/conda-forge/neovim-feedstock/issues/14)). However, someone could start a feedstock named `nvim` to permit `conda install -c conda-forge nvim`.

**Comment by justinmk** [comment]
Would be great. But we don't maintain the numerous external packages. Vim certainly doesn't maintain its conda package, someone else does.
