### ISSUE TITLE
nvim_cmd smods inconsistent with nvim_create_user_command

### ISSUE THREAD

**Issue by novasenco** [neovim/neovim#18876]
### Neovim version (nvim -v)

nvim v0.8.0 4365fa4

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A (arch)

### Terminal name/version

N/A (urxvt)

### $TERM environment variable

N/A (rxvt-unicode-256color)

### Installation

(AUR) neovim-nightly-bin

### How to reproduce the issue

```
vim.api.nvim_create_user_command('MyCmd', function(c)
    vim.api.nvim_cmd({cmd='split', args={c.args}, bang=c.bang, count=c.count, reg=c.reg, split={aboveleft=smods.aboveleft, belowright=smods.belowright, topleft=smods.topleft, botright=smods.botright}, silent=smods.silent, browse=smods.browse, confirm=smods.confirm, hide=smods.hide, keepalt=smods.keepalt, keepjumps=smods.keepjumps, keeppatterns=smods.keeppatterns, lockmarks=smods.lockmarks, noswapfile=smods.noswapfile, tab=smods.tab, vertical=smods.vertical})
end, {nargs='?'})
```

Scroll right for a while ... see how tedious that is ...

### Expected behavior

The expected behavior is that one doesn't have to manually map every sargs value to nvim_cmd's opts. As you can see, it's super tedious to map each arg.

### Actual behavior

One does have to manually map every sargs value to nvim_cmd's opts.

I don't know the solution. I just know it's extremely tedious as it is now.

**Comment by bfredl** [comment]
So, what's missing is that `smods` need to group the `split` attributes in the same way? After fixing that, one could just extend/modify the `smods` dict and send it in.

**Comment by clason** [comment]
I believe there's also an inconsistency with `verbose`, which is set to `0` by default in the callback argument, while `nvim_cmd` expects `-1`.

**Comment by novasenco** [comment]
yeah
