### ISSUE TITLE
Neovim and virtualenv...

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#1887]
I'm not sure there's a good solution to this, but I work with virtualenvs quite often in my Python work, and it's a bit frustrating to get the "No neovim module found" error message.  I use Neovim as my GIT_EDITOR and so I see it pop up rather often.  I know I can install neovim into the virtualenv, but I do like to keep them clean, so I've avoided it out of principle.  But I think there's a larger story to think about here in that these sort of tools are also popping up for other languages (Ruby, for instance).

Again, I'm not sure there's a good solution, but it does show one pain point of launching processes for the language plugins.

**Comment by fwalch** [comment]
I think this problem could  be avoided if `has('python')` wouldn't trigger an error message, but just silently returned `0`. Is it possible to implement that?

**Comment by jszakmeister** [comment]
It also means my Ultisnips plugin doesn't work... which I use to help write commit messages. :-(

**Comment by aktau** [comment]
> Is it possible to implement that?

Yes, (and in my opinion) yes.

**Comment by justinmk** [comment]
Well, what if it just logged the error to `:messages`? See my PR

**Comment by fwalch** [comment]
> Well, what if it just logged the error to :messages? See my PR

Forgot about that.. #1802

**Comment by justinmk** [comment]
@jszakmeister I don't use python too much, but does https://github.com/neovim/python-client/issues/16 help?

>  I know I can install neovim into the virtualenv, but I do like to keep them clean, so I've avoided it out of principle.

Hmm. If you used jedi, you would need to install the jedi python module in the virtualenv, right?

**Comment by equalsraf** [comment]
Would forcing the full python interpreter path in nvimrc help? It should go around the virtualenv.

```
let g:python_host_prog='/usr/bin/python'
```

That seems to work for me. If that is not enough, I think you can try clearing some environment variables before calling python (PYTHONHOME or VIRTUAL_ENV?)

**Comment by jszakmeister** [comment]
@equalsraf That's a very good idea!  I don't know why I didn't think of it.  I've used a similar trick in the past to force a particular virtualenv for a build machine.  And yes, it does help.


@justinmk 
> Hmm. If you used jedi, you would need to install the jedi python module in the virtualenv, right?

Yes, but see @equalsraf trick.  That works just fine for me.

> @jszakmeister I don't use python too much, but does neovim/python-client#16 help?

I generally avoid monkeying with the Python path too much, since it can cause other issues--like unexpectedly using the wrong version of a tool.  Setting `g:python_host_prog` worked well though.

**Comment by fwalch** [comment]
> Setting g:python_host_prog worked well though.

Should we document this somewhere? In the wiki and/or `:h nvim-python`? I can't seem to find documentation for `g:python_host_prog` in general, btw.

**Comment by bosr** [comment]
I had the same problem as @jszakmeister described, and the use of `g:python_host_prog` solved it.
Thanks!

**Comment by xaviergmail** [comment]
I was also looking into this, but setting `g:python_host_prog` seems to me like it would impede the functionality of certain plugins such as python-mode, pyrope, etc.

Instead, look into creating your new virtualenvs with the [`--site-packages`](https://virtualenv.readthedocs.org/en/latest/reference.html?highlight=#cmdoption--system-site-packages) option. 

Alternatively for existing virtual environments, remove `<virtualenv_name>/lib/python<version>/no-global-site-packages.txt` and re-enter your virtualenv if you were already 'working' on it.

This will allow you to install python-neovim with pip into your global packages and let neovim access it without cluttering your local packages. The only downside to this is that any other packages installed globally will also be available to your python environment, but you should be fine as long as you use virtual environments for everything and only install python-neovim into your global packages.

Also for us arch users whose eye got caught by the highlighted `pip install python-neovim` in the docs and completely skipped over [this AUR package](https://aur.archlinux.org/packages/python-neovim), well, there's that.

**Comment by fwalch** [comment]
> Also for us arch users whose eye got caught by the highlighted pip install python-neovim in the docs and completely skipped over this AUR package, well, there's that.

What docs do you mean? `:h nvim-python` says:

```
If you used a package manager to install Nvim, there's a good chance that it also provides the neovim Python package. If it doesn't, follow these steps to install the package with Python's package manager, pip.
```

**Comment by xaviergmail** [comment]
Ah, I meant the wiki. This article in specific: https://github.com/neovim/neovim/wiki/Installing-Neovim#arch-linux

Sorry for the confusion. I'll go ahead and edit my previous post.

**Comment by tbodt** [comment]
An idea which I haven't seen proposed in this issue for some reason is distributing the python client with neovim and adding it to PYTHONPATH when starting python.

**Comment by tweekmonster** [comment]
@tbodt I mentioned something similar to that a while back in chat and the idea was shot down.  The reason is that the the Python module's development is independent of Neovim's.  It's something I agree with now because maintaining a git submodule every time the module is updated would be a pain, and people using stable versions would still need to update the module themselves.

Besides, bundling the module and setting `PYTHONPATH` wouldn't be that simple since it depends on other modules.  Some of them are compiled C modules, so it would only work if the `python` executable is the same version that they're compiled for.

In case somebody is fumbling with virtualenvs and finds this issue, I wrote this a while back: https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim

**Comment by justinmk** [comment]
Can someone write concise advice about what `g:python_host_prog` should be set to, for virtualenv/pyenv/blahblahenv users? Then we can include that in the docs and close this.

**Comment by timeyyy** [comment]
docs as in wiki? tweek's seems pretty spot on, could just push a link to that.

**Comment by justinmk** [comment]
Would like to have a brief note in 'help provider-python'.

**Comment by tweekmonster** [comment]
The note could be along the lines of what I posted in Gitter:

> if you plan on using virtualenvs on a per-project basis often, it's best to assign a virtualenv for neovim and use g:python3_host_prog to hard code the interpreter path.

Even if that isn't the whole "how to", it'll at least get some neurons firing for a Google search.

**Comment by shazow** [comment]
In case this is helpful to anyone, here is what I use instead:

```vim
" Figure out the system Python for Neovim.
if exists("$VIRTUAL_ENV")
    let g:python_host_prog=substitute(system("which -a python3 | head -n2 | tail -n1"), '\n', '', 'g')
else
    let g:python_host_prog=substitute(system("which python3"), '\n', '', 'g')
endif
```

This tries to use the global Python install even if you're inside of a virtualenv.

**Comment by tweekmonster** [comment]
@shazow I'll grant that's a portable way of doing things, but it seems a bit much.  If you're using the system `python`, you should be able to just use `/usr/bin/python3` or something.  Otherwise, you're better off using a dedicated virtualenv and avoiding a potential mystery in the future.

If you want portability, this is what I've done in the past:

```
if filereadable('~/.nvim_python')
  source ~/.nvim_python
else
  ... defaults
endif
```

Then you can add those path variables in `~/.nvim_python` on a per-system basis without needing to mess with your configs if they're source controlled.

Also, you want to use `"\n"`.  `'\n'` is literally `\n` in Vim.  And for Python 3, you want to use the `g:python3_host_prog` variable.

**Comment by shazow** [comment]
Thanks for the tips, I'll tweak my config accordingly! Main reason is that I like to share my configs between linux/macOS and other systems, and it varies between `/usr/bin/python3` and `/usr/local/bin/python3` and maybe other places and so far I've managed to avoid having per-machine configs. :)

**Comment by phcerdan** [comment]
Coming after years, facing Ultisnips problems as well.

First, be sure your virtual environment has neovim: `pip install neovim`
Then, at the start of your `vimrc`, force vim to load python3 before any other plugin tries to load python2.
```vim
" Force vim to load python3 before python2
" You need pip install neovim in any virtualenv for Ultisnips to work
if has('python3')
endif
```

Hope it helps.

**Comment by gauteh** [comment]
For me I had to have the virtualenv activated before starting vim, chechealth showed the provide, but ultisnips still showed no provider. It turned out that I had to set `python3_host_prog` in `init.lua` and not my `vimrc` that I have partially migrated from:

```
HOME = os.getenv("HOME")
vim.g.python3_host_prog = HOME .. "/.mconda3/envs/neovim/bin/python3"
```
