### ISSUE TITLE
Cursorline position jumps between two positions when scrolling down when scrolloff is half the window height

### ISSUE THREAD

**Issue by EtiamNullam** [neovim/neovim#18900]
### Neovim version (nvim -v)

NVIM v0.7.0
NVIM v0.8.0-dev+78-g7df25a137

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

Windows 10

### Terminal name/version

Cmder 1.3.18.1106

### $TERM environment variable

N/A

### Installation

Scoop

### How to reproduce the issue

```
nvim --clean
:help (or open any other file, that is big enough to experience the problem)
:set relativenumber number (optional, useful for diagnose)
:set scrolloff=3
:resize 6
jjjjjjj (hold j or press it several times)
```

### Expected behavior

Cursorline position should be static and not flicker between two positions when scrolling down.

### Actual behavior

When scrolling down and if `scrolloff` is set to exactly half the amount of lines visible in the window then the number of lines before cursorline alternates between number of lines set by `scrolloff` and `scrolloff - 1`.

https://user-images.githubusercontent.com/10875340/172717956-eaf284c6-645b-4172-b4b5-6347a22a29de.mp4

EDIT: add video

**Comment by justinmk** [comment]
related? https://github.com/neovim/neovim/issues/18883

bisect would be very helpful

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/move.c b/src/nvim/move.c
index 8c927d30d..8bfa7a032 100644
--- a/src/nvim/move.c
+++ b/src/nvim/move.c
@@ -1631,10 +1631,6 @@ void scroll_cursor_bot(int min_scroll, int set_topbot)
     if (boff.lnum < curbuf->b_ml.ml_line_count) {
       // Add one line below
       botline_forw(curwin, &boff);
-      used += boff.height;
-      if (used > curwin->w_height_inner) {
-        break;
-      }
       if (extra < (mouse_dragging > 0 ? mouse_dragging - 1 : so)
           || scrolled < min_scroll) {
         extra += boff.height;
@@ -1649,6 +1645,10 @@ void scroll_cursor_bot(int min_scroll, int set_topbot)
           }
         }
       }
+      used += boff.height;
+      if (used > curwin->w_height_inner) {
+        break;
+      }
     }
   }
 
```

This doesn't seem to be the right solution. This function is very hard to understand and seems to be over 20 years old. I suggest you report this bug to Vim.

**Comment by EtiamNullam** [comment]
@zeertzjq: I've just raised this issue on [vim/vim](https://github.com/vim/vim): https://github.com/vim/vim/issues/10545.
