### ISSUE TITLE
Add formatoption for disabling comment continuation on end-of-line comments

### ISSUE THREAD

**Issue by Bulmanator** [neovim/neovim#18906]
### Feature already in Vim?

No, Vim behaves the same way as neovim

### Feature description

It seems that the way comment continuation works was changed at some point meaning comments that occur at the end of a line
containing non-comment code will be continued to the next line.

This didn't used to be the case and the previous way it worked was much more intuitive, so I would love an option to re-enable the old way of comment continuation.

With the default formatoptions `formatoptions=jcroql` from the built-in `c.vim` I will give examples of what currently happens and what I would like to happen/ what previously happened.

This is what currently happens:
```
Some_Structure *ptr = SomeFunction(); // This is an end-of-line comment, from normal mode 'o' is pressed to make a new line                                      
                                      // From this line enter/return is pressed in insert mode to make other lines
                                      //
                                      // Comment is continued
```

What previously happened/ what I would like to happen:
```
Some_Structure *ptr = SomeFunction(); // This is an end-of-line comment. Again 'o' is pressed
Other_Structure *oth = OtherFunction();

// The comment at the end of line 1 is not continued as expected
// However, pressing enter (in insert mode) or 'o' (in normal mode) continues this comment
// as it doesn't have any code in front of it.
//
```

I understand that the current way it works is a common commenting style and thus I think it should be an option to enable/ disable it and not an outright removal. From what I understand `formatoptions` are the options that currently control comment continuation, so maybe it could be added to that. It seems `formatoptions` only allow you to disable comment continuation entirely for each input method.

Thanks.

**Comment by zeertzjq** [comment]
#18463

**Comment by Bulmanator** [comment]
Perfect, nice that it has already been merged. Sorry for the duplicate!
