### ISSUE TITLE
Retry: `FocusLost` and `FocusGained` events will not fire

### ISSUE THREAD

**Issue by EtiamNullam** [neovim/neovim#18901]
New issue as #18330 was closed for apparently no reason.

### Neovim version (nvim -v)

NVIM v0.7.0
NVIM v0.8.0-dev+78-g7df25a137
NVIM v0.8.0-dev+384-g3cd22a348

### Vim (not Nvim) behaves the same?

No, vim `8.1.2233`

### Operating system/version

Windows 10

### Terminal name/version

Doesn't seem to be terminal-dependent, as `vim` works on all of them, I've tried:

- Cmd 10.0.19041.1415
- Powershell 7.1.2
- Cmder 1.3.18.1106

### $TERM environment variable

Not applicable

### Installation

Scoop

### How to reproduce the issue

1. Start with no config: `nvim --clean`
2. Register autocommands for `Focus*` events:
```viml
autocmd FocusLost * echo 'FocusLost'
autocmd FocusGained * echo 'FocusGained'
```
3. Change focus to another window
4. Notice no message will appear
5. Change focus back to terminal
6. Notice there is still no message displayed

### Expected behavior

Events should fire displaying `FocusLost` and `FocusGained` as terminal windows gains and loses focus, just like it happens in `vim`.

### Actual behavior

`FocusLost` and `FocusGained` events won't fire.

NOTE: It works when ran using some client like `Nvy` or `nvim-qt`, still not in every case like `vim`.

**Comment by erw7** [comment]
For this feature to work in neovim, the terminal must support sending `FocusIn`/`FoucsOut` events. No changes will be made that directly use the Windows console API to achieve this, such as vim.

**Comment by justinmk** [comment]
> the terminal must support sending `FocusIn` (`CSI I`)/`FoucsOut` (`CSI O`) events (`DECSET 1004`).

And it looks like newer versions of Windows Terminal do, or will, support that? https://github.com/microsoft/terminal/issues/13238

**Comment by EtiamNullam** [comment]
@justinmk: seems like focus events fire properly in the latest pre-release version of Windows Terminal ([v1.14.145](https://github.com/microsoft/terminal/releases/tag/v1.14.1451.0))!
