### ISSUE TITLE
single-repeat: expected behavior only w/ nvim -u NONE

### ISSUE THREAD

**Issue by ilAYAli** [neovim/neovim#18912]
### Neovim version (nvim -v)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@fv-az316-460

### Vim (not Nvim) behaves the same?

no, vim 7.4.629

### Operating system/version

ubuntu 20.04

### Terminal name/version

iterm2

### $TERM environment variable

screen-256color

### Installation

https://github.com/neovim/neovim/releases/download/stable

### How to reproduce the issue

foo.txt: 

    1111111122222223333333444444445555555566666666777777778888888899999999
    AAAAAAAABBBBBBBCCCCCCCDDDDDDDD22222222EEEEEEEEFFFFFFFFGGGGGGGGHHHHHHHH

`nvim -u /dev/null foo.txt -c 'call feedkeys("ct2@\<esc>j.")'` 
Results in this:

    @22222223333333444444445555555566666666777777778888888899999999
    AAAAAAAABBBBBBBCCCCCCCDDDDDDDD22222222EEEEEEEEFFFFFFFFGGGGGGGGHHHHHHHH

### Expected behavior

`nvim -u NONE foo.txt -c 'call feedkeys("ct2@\<esc>j.")'`
Results in the expected text:

@22222223333333444444445555555566666666777777778888888899999999
    @22222222EEEEEEEEFFFFFFFFGGGGGGGGHHHHHHHH

### Actual behavior

Unexpected result when nvim is executed without `-u NONE`.

**Comment by justinmk** [comment]
works with `nvim --clean` on b7d70de345db

**Comment by ilAYAli** [comment]
`--clean` works as expected both with `v0.7.0` and  `v0.8.0-dev+391-gc5720c722` but is not documented in `--help`
Regardless, The behavior is both inconsistent and incompatible with vim.
