### ISSUE TITLE
Preview callback in `nvim_create_user_command` hides errors

### ISSUE THREAD

**Issue by smjonas** [neovim/neovim#18910]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+359-g9745941ef

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux Mint 20.2

### Terminal name/version

Kitty 0.15

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

- `nvim --clean`
- Define the following user command with a preview function:
```lua
local function prev(_, _, _)
  assert(false)
  return 2
end

-- Create the user command
vim.api.nvim_create_user_command("TestPreview", "", {
  nargs = 0,
  preview = prev,
})
```
- type `:TestPreview`

### Expected behavior

An error similar to the following should be shown:
```
Error executing Lua callback: /home/jonas/.config/nvim/lua/packerinit.lua:9: assertion failed!                      
stack traceback:                                                                                                    
        [C]: in function 'assert'                                                                                   
        /home/jonas/.config/nvim/lua/packerinit.lua:9: in function </home/jonas/.config/nvim/lua/packerinit.lua:8> 
```

### Actual behavior

Nothing happens, the function aborts silently without showing errors to the user. This makes the preview function hard to debug. (cc @famiu)

**Comment by justinmk** [comment]
is the root cause similar to https://github.com/neovim/neovim/issues/13711 ?

**Comment by zeertzjq** [comment]
I think this is intended behavior?

**Comment by smjonas** [comment]
On a similar note, is it also expected that any `print()` or `vim.notify()` calls are ignored, i.e. they have no effect, in the preview callback?

**Comment by justinmk** [comment]
> is it also expected that any `print()` or `vim.notify()` calls are ignored, i.e. they have no effect, in the preview callback?

idk if it's intended, but it's desired. A preview func certainly has no business printing messages.

**Comment by famiu** [comment]
It is in fact intended behavior since the command may still be incomplete, so it's absolutely illogical to show errors during preview.

**Comment by smjonas** [comment]
Understood, just to put this out there, one possible usecase is incremental renaming using LSP: what if you want to tell users that renaming is currently not possible because no LSP server is attached (as they are typing)? The way Neovim handles this now, the user would instead have to type out the full name and press enter, only to realize that the command does nothing.

**Comment by famiu** [comment]
> Understood, just to put this out there, one possible usecase is incremental renaming using LSP: what if you want to tell users that renaming is currently not possible because no LSP server is attached (as they are typing)? The way Neovim handles this now, the user would instead have to type out the full name and press enter, only to realize that the command does nothing.

The preview not showing is already good indication that there is something wrong, isn't it?
