### ISSUE TITLE
:help open file

### ISSUE THREAD

**Issue by techtonik** [neovim/neovim#1891]
E149: Sorry, no help for open file

**Comment by jszakmeister** [comment]
I get the same result in Vim.  It might help to elaborate on what you believe to be the problem and a possible resolution for it.

**Comment by fwalch** [comment]
Yes, there is no help topic "open file". If you're new to Vim, try running `vimtutor` from your terminal to learn the basics.

**Comment by techtonik** [comment]
I that `neovim` is really better? Just NIH?

**Comment by fwalch** [comment]
If you have suggestions how Neovim's user experience can be improved, please share them with us! There are already some discussions going on (e.g. #1692, #1885, #276, #1664).

**Comment by techtonik** [comment]
@fwalch, commented on 1692.
