### ISSUE TITLE
strange behavior when trying to :substitute '\' with '\\'

### ISSUE THREAD

**Issue by ronisbr** [neovim/neovim#18929]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+377-gae02c02f1

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS 12.4

### Terminal name/version

iTerm 3.4.15

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

Open Neovim

Paste the following text:

```
\begin{tabular}{rrrrr}
  \textbf{Col. 1} & \textbf{Col. 2} & \textbf{Col. 3} & \textbf{Col. 4} & \textbf{Col. 5} \\
  0.220362 & 0.436524 & 0.548476 & 0.341173 & 0.954928 \\
  0.994615 & 0.633117 & 0.475656 & 0.227615 & 0.959393 \\
  $\vdots$ & $\vdots$ & $\vdots$ & $\vdots$ & $\vdots$ \\\hline
\end{tabular}
```

Then try to replace `\` with `\\` using:

```
:%s/\\/\\\\/g
```

### Expected behavior

All `\` must be replaced with `\\`.

### Actual behavior

A lot of strange things happen here. Before hitting enter in the replacement command, I see this:

<img width="1136" alt="Captura de Tela 2022-06-11 às 17 45 32" src="https://user-images.githubusercontent.com/1068295/173204296-77e97b3b-6193-4bfb-bd4a-8d80a5d3911b.png">

After hitting enter, I see this:

<img width="1136" alt="Captura de Tela 2022-06-11 às 17 45 46" src="https://user-images.githubusercontent.com/1068295/173204303-3f982b85-a4e9-4e00-8462-0baaf77cdbf5.png">

**Comment by zeertzjq** [comment]
I've notice that this can even cause a crash.

**Comment by ronisbr** [comment]
Yes! Indeed! Neovim crashed once after I hit enter but I could not find a reliable way to reproduce.

**Comment by zeertzjq** [comment]
Reverting either #14317 or #18812

**Comment by ronisbr** [comment]
I just want to mention that everything is working fine in `master`! Thanks @zeertzjq !
