### ISSUE TITLE
LSP: supports_method returns true for non supported standard method

### ISSUE THREAD

**Issue by jemag** [neovim/neovim#18939]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+401-ge15d31b53

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux Linux 5.18.3-arch1-1

### Terminal name/version

alacritty 0.11.0-dev (13b6248d)

### $TERM environment variable

screen-256color

### Installation

build from repo

### How to reproduce the issue

- Install terraform-ls 
- Test supports_method on it : 
```lua 
client.supports_method("textDocument/signatureHelp")
```
- Notice it returns true

---
**Additional details**:

I was previously using the server_capabilities and checking the provider to see if the capability was supported. I then realized that supports_method was available, however it does not seem to behave as expected.

For terraform-ls, `client.server_capabilities.signatureHelpProvider` will return `vim.empty_dict()`, which the current supports_method will consider as `true`. I do not know much about LSP, but I believe it might be a correct response since signatureHelpProvider, should not return a boolean, but rather signatureHelpOptions:
```ts
/**
	 * The server provides signature help support.
	 */
	signatureHelpProvider?: [SignatureHelpOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureHelpOptions);
```
To handle this response, this is how I was previously checking if signatureHelpProvider was supported (before using supports_method):
```lua
local function set_signature_helper(client, bufnr)
  local shp = client.server_capabilities.signatureHelpProvider
  if shp == true or (type(shp) == "table" and next(shp) ~= nil) then
    require("lsp_signature").on_attach(signature_cfg, bufnr)
  end
end
```

### Expected behavior

Returns false

### Actual behavior

Returns true

**Comment by justinmk** [comment]
duplicate of https://github.com/neovim/neovim/issues/18686

I reopened that. It has a bit more info, so closing this

**Comment by jemag** [comment]
@justinmk  I believe these are actually 2 distinct problems. The other issue you linked is about the fact that support_methods returns true for non documented methods, which is actually fine by me.

This is the not the case here, "textDocument/signatureHelp" is a standard method and is already properly documented/listed : 
https://github.com/neovim/neovim/blob/feba56af7d032c948a78c21735502bebe45f8361/runtime/lua/vim/lsp.lua#L41
https://github.com/neovim/neovim/blob/feba56af7d032c948a78c21735502bebe45f8361/runtime/lua/vim/lsp.lua#L1107-L1118

The problem is that the server returns an empty response for `signatureHelpProvider` (`vim.empty_dict()`), which the supports_method seem to evaluate to true.

**Comment by mfussenegger** [comment]
Based on the spec I'd interpret empty as being supported:

```
signatureHelpProvider?: SignatureHelpOptions



export interface SignatureHelpOptions extends WorkDoneProgressOptions {
	/**
	 * The characters that trigger signature help
	 * automatically.
	 */
	triggerCharacters?: string[];

	/**
	 * List of characters that re-trigger signature help.
	 *
	 * These trigger characters are only active when signature help is already
	 * showing. All trigger characters are also counted as re-trigger
	 * characters.
	 *
	 * @since 3.15.0
	 */
	retriggerCharacters?: string[];
}
```

Note that all properties are optional.

**Comment by mfussenegger** [comment]
> To be frank, I feel it is kind of weird to have to interpret SignatureHelpOptions to decide if signatureHelp is implemented, instead of having a proper way to get a straight true/false answer.

Well it's what's in the specification.  Some other capabilities do support boolean values as well.  See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_formatting for an example. That also makes me think that an empty dict must *not* be treated as falsy because DocumentFormattingOptions doesn't even have any properties 

> Given that the response seems to follow the spec and that, from the issue, it seems like terraform-ls does not support `signatureHelp`, could it still be an error for them to be sending an empty

To me it seems as if they're sending a wrong response.

**Comment by jemag** [comment]
Closing as there seems to be agreement on the terraform-ls side that this is not the proper response. Thanks for the clarifications @mfussenegger
