### ISSUE TITLE
Mapping ignored on special shift characters

### ISSUE THREAD

**Issue by DiantArts** [neovim/neovim#18941]
### Neovim version (nvim -v)

v0.7.0

### Vim (not Nvim) behaves the same?

no, 8.2 (2019 Dec 12, compiled Jun 07 2022 00:51:41)

### Operating system/version

Arch linux, Linux 5.18.3-arch1-1

### Terminal name/version

XTerm(372)

### $TERM environment variable

xterm-256color

### Installation

pacman

### How to reproduce the issue
```
# with a dvorak-programer (dvp) keyboard layout
nvim --noplugin -u /dev/null

# inside vim
:nnoremap _ V

# press the binding
_
```

### Expected behavior

It should start the block visual mode (line per line)

### Actual behavior

It goes at the begining of the line like pressing `<HOME>`

It does the same problem with `|` and `^` bindings

**Comment by zeertzjq** [comment]
Does `nnoremap <S-_> V` work?

**Comment by DiantArts** [comment]
I did not even think about it. I don't know why it works but it does, Thanks a lot! you're a genious
