### ISSUE TITLE
Consider vim-surround as a sane default

### ISSUE THREAD

**Issue by lloeki** [neovim/neovim#1895]
[vim-surround](https://github.com/tpope/vim-surround) is so awesome that it's the only vim plugin I truly can't live without, and the one whose lack of presence takes me aback *every* *single* *time* (and often multiple times in a row) I connect to a remote server.

For the sake of countless users foreheads, please consider making it a default.

**Comment by jamezb** [comment]
+1

**Comment by justinmk** [comment]
We're a long way off from ever considering this. There are even competing surround plugins that some people like better, not to mention a non-trivial number of people don't want this plugin at all. 

Furthermore, surround actually provides *no way* to specify alternative mappings.

The general solution to basic problem here is to make installing (and finding) plugins very easy.

**Comment by kdurant** [comment]
how many people know Chinese？
最重要的是一个内置的插件管理器
