### ISSUE TITLE
CMD does not expand in Visual Line selection with cmdheight=0

### ISSUE THREAD

**Issue by eruizc-dev** [neovim/neovim#18957]
### Neovim version (nvim -v)

NVIM v0.8.0-dev

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 11.6.6 & Arch Linux (kernel 5.18.1-arch1-1)

### Terminal name/version

wezterm 20220408-101518-b908e2dd

### $TERM environment variable

xterm-256 color

### Installation

Build from repo (master)

### How to reproduce the issue

 1. Set cmdheight to zero `:set cmdheight=0`
 2. Use visual line to slelect a line `V`
 3. Use replace by pressing `:s/replacethis/withthat`
 4. The cmd would not expand when it should

### Expected behavior

Expected the cmd to expand, like it does when you don't have a section selected

### Actual behavior

Cmd does not expands, the cursor is where it should (I have line 42 selected)

![image](https://user-images.githubusercontent.com/58179604/173407718-66b84727-7ced-4065-b314-c66d6817aa48.png)

**Comment by bew** [comment]
Duplicate of #18955 ?

**Comment by eruizc-dev** [comment]
Absolutely, can't believe I didn't see that one

Closed as duplicate
