### ISSUE TITLE
release url pointing to the wrong place

### ISSUE THREAD

**Issue by jianlingzhong** [neovim/neovim#18959]
### Neovim version (nvim -v)

NA

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

NA

### Terminal name/version

NA

### $TERM environment variable

NA

### Installation

NA

### How to reproduce the issue

`Releases` and `Stable release` on this page https://github.com/neovim/neovim/wiki/Installing-Neovim  is pointing to 

https://www.ps3cfw.com/cool.php?item=26847432

i believe this is not correct.

### Expected behavior

NA

### Actual behavior

NA

**Comment by clason** [comment]
Reverted, thank you!
