### ISSUE TITLE
`nvim_parse_cmd` ignores `:filter`

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#18954]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+406-g502f03fc06

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean`
2. Run `:echo nvim_parse_cmd('highlight', {}) == nvim_parse_cmd('filter /foo/ highlight', {})`

### Expected behavior

`0` is printed and there is no memory leak

### Actual behavior

`1` is printed and there is a memory leak

**Comment by zeertzjq** [comment]
The memory leak has been fixed by #19101.

**Comment by famiu** [comment]
`nvim_parse_cmd` can parse `:filter` just fine for me after #19101

**Comment by zeertzjq** [comment]
Here I mean `:filter` is ignored, which means `:filter` is lost if the result is passed to `nvim_cmd`.
