### ISSUE TITLE
Allow disabling all statuslines

### ISSUE THREAD

**Issue by oredaze** [neovim/neovim#18965]
### Feature already in Vim?

Yes

### Feature description

When we have `laststatus=3` we get nice lines on horizontal splits. There is no reason why `laststatus=0` should not behave the same. It does not right now (nvim 0.7.0). Instead you still get the statusline... but only on some splits... Yuck.
This is almost a bug even...

I was thinking about transitioning to winbar + laststatus=0 when nvim 0.8.0 comes out, but it looks like that won't be as nice as I imagined...

**Comment by Shougo** [comment]
Hi.  I think the configuration solves the problem.

```vim
if &laststatus > 0
  highlight StatusLine    gui=bold guibg=#c8c8d8 guifg=#151505
  highlight StatusLineNC  gui=reverse guibg=#c8c8d8 guifg=#151505
else
  " Disable StatusLine highlights
  highlight StatusLine    gui=NONE guibg=#1c1c1c guifg=#aaaaaa
  highlight StatusLineNC  gui=NONE guibg=#1c1c1c guifg=#1c1c1c
endif
```

Note: `1c1c1c` means bg highlight color.

**Comment by justinmk** [comment]
```
hi! link StatusLine Normal
set statusline=%{repeat('─',winwidth('.'))}
```

**Comment by rodolfoksveiga** [comment]
> ```viml
> set laststatus=0
> hi! link StatusLine Normal
> hi! link StatusLineNC Normal
> set statusline=%{repeat('─',winwidth('.'))}
> ```

Nice..! But would you know how I can achieve this in a lua config file?

**Comment by glepnir** [comment]
```lua
vim.opt.laststatus = 0
vim.api.nvim_set_hl(0 , 'Statusline', {link = 'Normal'})
vim.api.nvim_set_hl(0 , 'StatuslineNC', {link = 'Normal'})
local str = string.repeat('-', vim.api.nvim_win_get_width(0))
vim.opt.statusline = str
```

**Comment by rodolfoksveiga** [comment]
Thanks for the quick answer, but it still doesn't work for me.

![image](https://user-images.githubusercontent.com/41191959/194861672-c63e5462-cd24-49a6-aa92-f9680355f707.png)

**Comment by rodolfoksveiga** [comment]
It still doesn't work for me... Did I do something wrong?

![image](https://user-images.githubusercontent.com/41191959/194861801-a03b03b3-f310-4094-9948-20f693d4fc28.png)

**Comment by zeertzjq** [comment]
A plugin is probably enabling statusline.

**Comment by clason** [comment]
Please ask on Chat for help with your config; this issue tracker is for actual bugs and feature requests.
