### ISSUE TITLE
cmdheight=0: crash with laststatus=0 rulerformat

### ISSUE THREAD

**Issue by octaltree** [neovim/neovim#18970]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+428-g1493efdc14

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux coorie 5.10.121-1-MANJARO #1 SMP PREEMPT Thu Jun 9 09:56:12 UTC 2022 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.11.0-dev (d9c6c8d5)

### $TERM environment variable

tmux-256color

### Installation

aur/neovim-git

### How to reproduce the issue

Execute neovim with min.vim
```
set laststatus=0
set rulerformat=%l,%c%=
set cmdheight=0
```
I got an assertion failure
```
nvim: /home/octaltree/.cache/yay/neovim-git/src/neovim-git/src/nvim/grid.c:335: grid_puts_line_flush: アサーション `put_dirty_row != -1' に失敗しました。
                                                                     zsh: IOT instruction (core dumped)  nvim -u min.vim
```

### Expected behavior

Since the noruler is explicitly stated in the test, I want error messages to users or documentation or automatic noruler settings.

### Actual behavior

Ruler drawing causes panic

**Comment by Shougo** [comment]
I have fixed the problem.  Please test https://github.com/neovim/neovim/pull/18961.

**Comment by octaltree** [comment]
It worked. Errors, statusline, ruler, cmdline were not displayed. Thank you
