### ISSUE TITLE
File content missing

### ISSUE THREAD

**Issue by ignamartinoli** [neovim/neovim#18977]
### Neovim version (nvim -v)

0.8.0-dev+11-gd3121f1e6-dirty

### Vim (not Nvim) behaves the same?

couldn't check

### Operating system/version

Gentoo

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

Gentoo Repository

### How to reproduce the issue

Very sporadically, after I edited a file and `:wq` it. I shut down the laptop. When I turn it back on the content of the file is missing. This has happened to me 2/3 times a month but it's extremely annoying

### Expected behavior

The file content still there

### Actual behavior

All the content missing

**Comment by zeertzjq** [comment]
Is the file content present before you shut down the laptop?

**Comment by ignamartinoli** [comment]
Yes. It was present. It is a file that I edit frequently called `TODO.md`. Before this I used to have it in my `/home/sicro` directory and it got deleted almost always. I moved it into `/home/sicro/Notes` and it lasted 2 months before having it's content missing

**Comment by justinmk** [comment]
try `set fsync` in your config

**Comment by ignamartinoli** [comment]
Did it, I will reopen the issue if it didn't solved the problem, thanks!

**Comment by Safari77** [comment]
The bug has not been fixed, neovim deletes the file being edited instead of writing to a temporary file and restoring modes and ACLs etc, doing fsync to it and then using rename() to overwrite the file being edited (talking about POSIX systems only here).

Maybe renameat2 with `RENAME_EXCHANGE` and/or `RENAME_NOREPLACE` flags could be used in some file operations in neovim.

```
23:19:53.222868 unlink("jee.txt~")      = 0 <0.000024>
23:19:53.222911 rename("jee.txt", "jee.txt~") = 0 <0.000029>
*** bye jee.txt ***
23:19:53.222961 lseek(14, 8192, SEEK_SET) = 8192 <0.000006>
23:19:53.222983 write(14, "ad\0\0\332\17\0\0\372\17\0\0\0\20\0\0\2\0\0\0\0\0\0\0\373\17\0\0\372\17\0\0\365\17\0\0\360\17\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096) = 4096 <0.000014>
23:19:53.223025 epoll_pwait(3, [], 1024, 0, NULL, 8) = 0 <0.000005>
23:19:53.223047 lseek(14, 4096, SEEK_SET) = 4096 <0.000005>
23:19:53.223067 write(14, "tp\1\0\252\0\0\0\2\0\0\0\0\0\0\0\2\0\0\0\1\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096) = 4096 <0.000008>
23:19:53.223101 epoll_pwait(3, [], 1024, 0, NULL, 8) = 0 <0.000006>
23:19:53.223124 fsync(14)               = 0 <0.015986>
23:19:53.239135 openat(AT_FDCWD, "jee.txt", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0664) = 15 <0.000033>
23:19:53.239191 write(15, "wler\n\n", 6) = 6 <0.000017>
23:19:53.239227 fsync(15)               = 0 <0.005719>
*** jee.txt is back! ***
23:19:53.244967 listxattr("jee.txt~", NULL, 0) = 0 <0.000008>
```

**Comment by justinmk** [comment]
@Safari77 do not report things without mentioning the exact version of Nvim and other relevant details. Also, are you using 'fsync' option, or 'nofsync'

**Comment by Safari77** [comment]
This bug report is titled "File content missing", not "nofsync causes missing files". Both `fsync` and `nofsync` cause missing files.

I have latest release 0.11.3 on Fedora 42 x86_64, XFS filesystem.

**Comment by justinmk** [comment]
> Maybe renameat2 with `RENAME_EXCHANGE` and/or `RENAME_NOREPLACE` flags could be used in some file operations in neovim.

If you want to look into that, here's a starting point: https://github.com/neovim/neovim/blob/052126b77ad83b1f26da46dad8c42efacffe7568/src/nvim/bufwrite.c#L1038
