### ISSUE TITLE
Alt + Shift + Key does not work with some keys on kitty

### ISSUE THREAD

**Issue by ciscocarvalho** [neovim/neovim#18991]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+433-g0e8186bdd

### Vim (not Nvim) behaves the same?

no, vim 8.2.4464 

### Operating system/version

Manjaro

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

1 - `nvim --clean`
2 - Enter insert mode
3 - Press `Alt + Shift + ;`

### Expected behavior

nvim should leave insert mode and enter command mode

### Actual behavior

nvim stays in insert mode and inserts a semicolon

It only seems to happen with non-alphabetical keys, e.g. `<M-S-A>` works fine
It also happens in other modes
It only seems to happen on kitty
It doesn't happen when using nvim 0.7 or vim

**Comment by zeertzjq** [comment]
> nvim should leave insert mode and enter command mode

Why?

**Comment by zeertzjq** [comment]
This behavior doesn't happen if:
- You run a Vim GUI
- You run Vim in xterm

So I don't think this should be the intended behavior.

**Comment by justinmk** [comment]
I suspect this is related to 

- https://github.com/neovim/neovim/pull/13042
- https://github.com/neovim/neovim/pull/16222

We've added a reasonable compromise to get this old accidental "feature" of Vim but let's leave it at that.
