### ISSUE TITLE
`vim.api.nvim_eval('{}')` evaluates to `{[true] = 6}`

### ISSUE THREAD

**Issue by hungnguyen94** [neovim/neovim#19004]
### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

No, checked with vim 8.2.3995-1ubuntu2. `vim.eval('{}')` evaluates this to an userdata object.

### Operating system/version

macOS 11.6.7

### Terminal name/version

iTerm2 3.4.15

### $TERM environment variable

xterm-256color

### Installation

brew

### How to reproduce the issue

1. `nvim --clean`
2. `:lua print(vim.inspect(vim.api.nvim_eval('{}')))`

### Expected behavior

I would expect this to evaluate to an empty lua table

### Actual behavior

```
{
  [true] = 6
}
```

**Comment by seandewar** [comment]
This is a special type used to disambiguate an empty VimL dictionary from a list.

See `:h lua-eval` and `:h lua-special-tbl` for more info.
