### ISSUE TITLE
netrw buffer doesn't autoclose

### ISSUE THREAD

**Issue by RuRo** [neovim/neovim#19006]
### Neovim version (nvim -v)

0.6.1 or 0.7.0

### Vim (not Nvim) behaves the same?

no, vim 8.2 (`+'runtime plugin/netrwPlugin.vim'`)

### Operating system/version

Ubuntu 22.04 or Manjaro 5.15.41

### Terminal name/version

none (docker) or guake 3.8.5

### $TERM environment variable

xterm or xterm-256color

### Installation

apt-get install neovim or community/neovim 0.7.0

### How to reproduce the issue

My host system is a bit weird, so I reproduced this in docker to make sure, that it's a universal issue:
```sh
docker pull ubuntu:22.04
docker run -it ubuntu:22.04
```

In docker (or on a Ubuntu 22.04 machine):
```sh
apt-get update
apt-get install -y neovim
touch /tmp/example
nvim --clean +'runtime plugin/netrwPlugin.vim' tmp
```

This should open `netrw` In nvim. Then:
- select `example` file from the list and press enter
- run `:ls`
- run `:bp`
- run `:bd` or `:bw`
- run `:ls`

### Expected behavior

The `:ls` commands should only list the `/tmp/example` buffer.
The `tmp` buffer opened by `netrw` should have closed itself after opening the file.

Note, that

1) This currently works with regular vim `8.2`:
    - Replace `install neovim` with `install vim`
    - Replace `nvim --clean` with `vim -u DEFAULTS`

2) This used to work in older versions of neovim:
    - Replace `ubuntu22.04` with `ubuntu20.04` which has neovim `0.4.3`

### Actual behavior

Instead, the first `:ls` command prints
```
:ls
  1  h   "tmp"                          line 1
  3 %a   "tmp/example"                  line 1
Press ENTER or type command to continue
```

Going back to the extra `tmp` buffer with `:bp` and trying to close it with `:bd` or `:bw` doesn't close it and the second `:ls` shows the same 2 buffers still open.

The `+'runtime plugin/netrwPlugin.vim'` may be required when running with `--clean` or `-u DEFAULTS` to enable `netrw`.

**Comment by zeertzjq** [comment]
`set nohidden`

**Comment by RuRo** [comment]
@zeertzjq adding `+'set nohidden'` to the provided reproduction script leads to
```
Error detected while processing function <SNR>15_NetrwBrowseChgDir[390]..<SNR>15_NetrwOptionsRestore:                                                                 
line    7:
E216: No such group or event: filetypedetect BufRead
Press ENTER or type command to continue
```
after trying to open the example file.

Although it did seem to work on my main machine, so it might be an unrelated issue. Thanks.

**Comment by RuRo** [comment]
Also, I forgot, why the `nohidden` solution didn't work for me. `nohidden` seems to force you to save any modifications to when switching between buffers.

So
```
vim foo bar
# edit the contents of foo without saving it
:bp
```
will trigger a
```
:bp
Save changes to "foo"?                                                                                                                                              
[Y]es, (N)o, (C)ancel: 
```
dialog with `nohidden`.

Just to clarify. It used to work just fine without setting `nohidden` in previous neovim versions and in regular vim. So this seems like a regression.

**Comment by RuRo** [comment]
@zeertzjq can you reopen this issue? As I mentioned, `set nohidden` has undesirable side effects, so it's not a valid solution for this problem.

**Comment by zeertzjq** [comment]
Does Vim behave the same with `set hidden`?

**Comment by RuRo** [comment]
Not quite. Regular vim also doesn't automatically close the netrw buffer on file selection.

But it does allow the user to close the buffer when manually navigating to it and wiping/discarding it:
```
:bp
:bw or :bd
:ls
```

**Comment by zeertzjq** [comment]
Hmm, I cannot reproduce the netrw buffer still being present after `:bw` or `:bd`.

**Comment by RuRo** [comment]
```
docker pull ubuntu:22.04
docker run -it ubuntu:22.04
```
```
apt-get update
apt-get install -y neovim
touch /tmp/example
nvim --clean +'runtime plugin/netrwPlugin.vim' +'set hidden' /tmp
```
- select `example`, press enter (opens empty `tmp/example`)
- `:bp` (opens the `netrw` buffer again)
- `:bw` (switches back to example buffer, but doesn't actually close `tmp`)
- `:ls`

Shows
```
:ls
  1  h   "tmp"                          line 1
  3 %a   "tmp/example"                  line 1
Press ENTER or type command to continue
```

What do you see when following these reproduction steps?
