### ISSUE TITLE
conceal is broken in nvim_buf_set_extmark

### ISSUE THREAD

**Issue by ii14** [neovim/neovim#19007]
### Neovim version (nvim -v)

v0.8.0-dev commit 502f03fc0

### Vim (not Nvim) behaves the same?

-

### Operating system/version

ubuntu 18.04

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

ppa

### How to reproduce the issue

Create a script and run it on itself with `:so%`:
```lua
-- foo
local ns = vim.api.nvim_create_namespace('TEST')
vim.opt_local.conceallevel = 2
vim.api.nvim_buf_set_extmark(0, ns, 0, 3, {
  end_row = 0, end_col = 6,
  hl_group = 'Identifier',
  conceal = '.',
})
```

Failing test case: https://github.com/ii14/neovim/commit/bee17c8f1f104c795d058f7b3ee2a87d1c0fed1a

### Expected behavior

`foo` on the first line should be concealed with `.`.

### Actual behavior

It's not.

**Comment by ii14** [comment]
The original PR #17776 only adds a test with treesitter, where `ephemeral = true` is used.

**Comment by bfredl** [comment]
haven't tested yet but this might be what's missing

```diff
diff --git a/src/nvim/extmark.c b/src/nvim/extmark.c
index b9e0d18f2..1639f7299 100644
--- a/src/nvim/extmark.c
+++ b/src/nvim/extmark.c
@@ -68,6 +68,7 @@ void extmark_set(buf_T *buf, uint32_t ns_id, uint32_t *idp, int row, colnr_T col
   if (decor) {
     if (kv_size(decor->virt_text)
         || kv_size(decor->virt_lines)
+        || decor->conceal
         || decor_has_sign(decor)
         || decor->ui_watched) {
       decor_full = true;
```

**Comment by ii14** [comment]
Yup, it seems to work.

**Comment by fjfnaranjo** [comment]
A valid workaround is defining any virt_text:

```lua
-- foo
local ns = vim.api.nvim_create_namespace('TEST')
vim.opt_local.conceallevel = 2
vim.api.nvim_buf_set_extmark(0, ns, 0, 3, {
  end_row = 0, end_col = 6,
  hl_group = 'Identifier',
  conceal = '.',
  virt_text = {{"", "Conceal"}},
})
```
