### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by leira** [neovim/neovim#1901]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with neovim. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable neovim on @Sourcegraph by going to https://sourcegraph.com/github.com/neovim/neovim and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by justinmk** [comment]
I've been waiting for sourcegraph to add support for C. I enabled it, but still doesn't look like they support C. It would be magic if they did. 

Right now they have navigation for `contrib/ycm_extra_conf.py` .... ;_;

Anyways I enabled, thanks.
