### ISSUE TITLE
`screen*()` functions don't register floating windows

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#19013]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+441-ge651ae586

### Vim (not Nvim) behaves the same?

Yes, with popup windows (8.2.5046)

### Operating system/version

EndeavourOS 5.18.3-arch1-1

### Terminal name/version

xfce4-terminal 1.0.4 (Xfce 4.16)

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

1. Create 'init-floating.lua' file with following content:
```lua
local buf_id = vim.api.nvim_create_buf(true, true)
vim.api.nvim_buf_set_lines(buf_id, 0, -1, true, { 'aaaaaaaaaa' })

vim.api.nvim_open_win(buf_id, false, {
  relative = 'editor',
  width = 10,
  height = 1,
  row = 0,
  col = 0,
})
```
2. `nvim -u init-floating.lua`. Should result in Neovim instance with `aaaaaaaaaa` in floating window in top left corner.
3. Run `:lua print(vim.inspect(vim.fn.screenstring(1, 1)))`. It should be `"a"`, but it is `" "`, which is a character under floating window. The same effect is for `screenchar()`, `screenchars()`, and `screenattr()`.

On the other hand, Vim behaves as expected with its popup windows. Use equivalent 'init-popup.vim' file:
```vimscript
call popup_create("aaaaaaaaaa", {"line": 1, "col": 1})
```

### Expected behavior

All `screen*()` functions respect floating windows, i.e. use them during computation of "what is displayed on the screen".

### Actual behavior

https://user-images.githubusercontent.com/24854248/174443738-e6bf6169-23f7-45fe-ba13-5dd4c91d08be.mp4

**Comment by zeertzjq** [comment]
Is is related to your feature request in #19000?

**Comment by echasnovski** [comment]
Implicitly related, yes. I've built a straightforward `get_screenshot()` function by traversing all cells (within `1, vim.o.lines` x `1, `vim.o.columns`) with `screenstring()` and `screenattr()`. Works like a charm (with couple of design drawbacks), but when testing it, found that it doesn't support floating windows (which is a must for modern plugin testing, unfortunately). As similar works on Vim's side, seems to be an undesirable behavior.

**Comment by zeertzjq** [comment]
This may be impossible because how floating windows are displayed depends on what UIs are attached.

**Comment by clason** [comment]
(Remember that Neovim's floating windows are _very_ different from Vim's popups.)

**Comment by zeertzjq** [comment]
Although duplicating the code for finding mouse click position may make this work.

**Comment by echasnovski** [comment]
> This may be impossible because AFAIK how floating windows are displayed depends on what UIs are attached.

This is sad. 

At least, this means a documentation of these functions are not really up to date. All of them have something like `character ... at position [row, col] on the screen`.

> Although duplicating the code for finding mouse click position may make this work.

And this is better :)
If you, please, could point me to the right direction, I will be trying something. Really want to have the ability to do proper screen tests.

**Comment by bfredl** [comment]
there is also `nvim__inspect_cell()` which is not standardized yet, but allows you to address floating windows.

**Comment by zeertzjq** [comment]
I just noticed this comment:
https://github.com/neovim/neovim/blob/cd9e08cb94663558891fdd46dfa58f662e947be5/src/nvim/eval.c#L6854-L6857

**Comment by echasnovski** [comment]
> there is also `nvim__inspect_cell()` which is not standardized yet, but allows you to address floating windows.

I tried incorporating it and did in fact succeed to get data from both main window and floating ones. But not so smartly: by looping `grid` id from 1 to 100 and seeing if there is a valid output. As I couldn't find a way to match window id to a grid id with exported Lua API (if this even makes sense). It also seem to lead to other hassles: manually computing which floating window is on top through z-index, aligning grids (as coordinates seem to be "per window"), dealing with occasional segfaults... Not as straightforward as I hoped with `screenstring()` and `screenattr()` :(
