### ISSUE TITLE
Make .nvimlog location configurable

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#1903]
I don’t like having my home directory trashed. All files generated by Vim use user-specified paths (see `viminfo`, `directory`, `backupdir` and `undodir`). All plugins I use are similarly well-behaved. nvimlog should follow this tradition. We should either add a `logdir` option, or use the directory given by an existing option, like `directory`.

**Comment by lucastadeu** [comment]
I tackle this as my first entry-level issue (:

**Comment by justinmk** [comment]
`.nvimlog` will not be produced by the release/production build of neovim. Although some day we may want to consider persisting `:messages` in an unobtrusive way for end-users.

**Comment by jdhao** [comment]
@justinmk  I have also met this issue since I am using the nightly version of Neovim. Can we change the directory where `.nvimlog` is stored now?

**Comment by h-michael** [comment]
@jdhao If you set `NVIM_LOG_FILE`, you can change .nvim log path.

**Comment by glacambre** [comment]
On 2020-06-02 05:32, jdhao wrote:
> I am using the nightly version of Neovim. Can we change the directory 
> where |.nvimlog| is stored now?

Isn't it controlled by $NVIM_LOG_FILE?
