### ISSUE TITLE
quickfix number characters limit is 1024, add option to increase it

### ISSUE THREAD

**Issue by tex** [neovim/neovim#19036]
### Feature already in Vim?

No

### Feature description

Add option to increase the limit of number of characters per line in quickfix.
Or increase that limit to something reasonable like 32KiB or more.
For example, using AsyncRun plugin it outputs command line output to quickfix.
Compiling with VERBOSE means that most of the output is just cut and it is useless.

**Comment by clason** [comment]
That seems like something that should ideally be implemented upstream and then ported -- could you open this issue at vim/vim?

**Comment by zeertzjq** [comment]
There's already one: <https://github.com/vim/vim/issues/10266>

**Comment by zeertzjq** [comment]
Fixed by #22532
