### ISSUE TITLE
Add: bang operator for nvim_set_hl()

### ISSUE THREAD

**Issue by tobealive** [neovim/neovim#19034]
### Feature already in Vim?

No

### Feature description

Just like other api functions, _(e.g., `nvim_create_user_command()`)_ have the possibility to add a `bang` operator it would be nice to have that possibility for the highlight api.

currently I couldn't find a way around falling back to a `vim.cmd(hi! ...)`

**Comment by clason** [comment]
`nvim_set_hl` with the `link` option should always behave like `hi! link ...` anyway. Have you actually tested that you can't overwrite a link this way?

**Comment by tobealive** [comment]
Hey, thanks for tackling this issue. Yeah, I had trouble getting some highlights working yesterday and could manage to solve it via the fallback. That's why how it came to this issue being opened. I re-tested just now with the api and it seems to work today. I must have done something wrong, obviously.

**Comment by axieax** [comment]
Sorry for reviving this issue, but is there a Lua syntax for `hi! Twilight guibg=NONE`? I've tried `vim.api.nvim_set_hl(0, "Twilight", { bg = nil })` but that doesn't seem to work because of the lack of the command bang.

**Comment by zeertzjq** [comment]
`bg = 'NONE'`

**Comment by zeertzjq** [comment]
What do you mean by "doesn't seem to work"?

**Comment by axieax** [comment]
`hi! Twilight guibg=NONE` works but `hi Twilight guibg=NONE`, so I'm trying to use the Lua equivalent to force the command bang.

**Comment by clason** [comment]
That's irrelevant. The question is what you expect to happen for `nvim_set_hl` and what you actually observe. (`nvim_set_hl` always behaves like `hi!`, i.e., will completely(!) replace the current definition with what you specify.)

**Comment by clason** [comment]
Also, the bang is only relevant for _linking_, not defining groups. 

Finally, please do not post marginally related questions as comments to closed issues. If you think you have found a bug, open a new issue and fill out the template; if you have a question, ask in the Matrix chat room.
