### ISSUE TITLE
Download of dependencies is failing, could be a github URL format change (302 redirect)

### ISSUE THREAD

**Issue by twhateley** [neovim/neovim#19048]
### Neovim version (nvim -v)

HEAD

### Vim (not Nvim) behaves the same?

yes, (build issue not compat)

### Operating system/version

Amazon Linux 2

### Terminal name/version

putty

### $TERM environment variable

screen

### Installation

git clone ; make

### How to reproduce the issue

cd "$(mktemp -d)"
git clone https://github.com/neovim/neovim.git
cd neovim

make CMAKE_BUILD_TYPE=Release

### Expected behavior

downloads and installs dependencies during make

### Actual behavior

Debugging using CURL at the end

-- Build files have been written to: /tmp/tmp.qMTBy6bJUJ/neovim/.deps
mkdir -p build
touch build/.ran-third-party-cmake
make -C .deps
make[1]: Entering directory `/tmp/tmp.qMTBy6bJUJ/neovim/.deps'
make[2]: Entering directory `/tmp/tmp.qMTBy6bJUJ/neovim/.deps'
make[3]: Entering directory `/tmp/tmp.qMTBy6bJUJ/neovim/.deps'
Scanning dependencies of target libuv
make[3]: Leaving directory `/tmp/tmp.qMTBy6bJUJ/neovim/.deps'
make[3]: Entering directory `/tmp/tmp.qMTBy6bJUJ/neovim/.deps'
[  1%] Creating directories for 'libuv'
[  2%] Performing download step for 'libuv'
-- file: /tmp/tmp.qMTBy6bJUJ/neovim/.deps/build/downloads/libuv/730e07e2f77a4001bdf6894112271c926399f5a8.tar.gz
-- downloading...
       src='https://github.com/libuv/libuv/archive/730e07e2f77a4001bdf6894112271c926399f5a8.tar.gz'
       dst='/tmp/tmp.qMTBy6bJUJ/neovim/.deps/build/downloads/libuv/730e07e2f77a4001bdf6894112271c926399f5a8.tar.gz'
       timeout='none'
CMake Error at /tmp/tmp.qMTBy6bJUJ/neovim/third-party/cmake/DownloadAndExtractFile.cmake:98 (message):
  error: downloading
  'https://github.com/libuv/libuv/archive/730e07e2f77a4001bdf6894112271c926399f5a8.tar.gz'
  failed

      status_code: 1
      status_string: "Unsupported protocol"
      log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1

---

$ curl -v -o test https://github.com/libuv/libuv/archive/730e07e2f77a4001bdf6894112271c926399f5a8.tar.gz
[edited]
> GET /libuv/libuv/archive/730e07e2f77a4001bdf6894112271c926399f5a8.tar.gz HTTP/2
> Host: github.com
> user-agent: curl/7.79.1
> accept: */*
>
[snip]

< HTTP/2 302
< server: GitHub.com
< date: Wed, 22 Jun 2022 06:32:59 GMT
< content-type: text/html; charset=utf-8
< vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
< permissions-policy: interest-cohort=()
< location: https://codeload.github.com/libuv/libuv/tar.gz/730e07e2f77a4001bdf6894112271c926399f5a8
< cache-control: max-age=0, private

**Comment by clason** [comment]
From the error message, sounds like an issue with your local (or server) `libcurl` installation or configuration. Try reinstalling it.

(It works fine on my end, so it's not a regression in Neovim itself.)

**Comment by clason** [comment]
(Feel free to reopen if you can in fact pinpoint this to a problem with the bundled build scripts.)

**Comment by twhateley** [comment]
I was using an old version of cmake, updating to the latest version fixed this for me.  Sorry for wasting your time on this and thankyou for such a quick response!
