### ISSUE TITLE
Enable asserts on release build?

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#1905]
We've been introducing asserts in the code for a while. I don't know if it's been previously discussed, but I think we should talk about enabling asserts in release mode too.

To me, running a bit faster is no reason to let the thing run under abnormal conditions, for two reasons:
- It can cause uncontrolled damage.
- Asserts state assumptions about how the code works. We assert things that we *think* should always be true. If that's not true, and they can be otherwise under some circumstances, we want to know about that.

So, in a sense, asserts in release mode would be even more necessary than in debug mode. To protect our users, and to learn if we're making wrong assumptions about our code. We can't test every possible circumstance users will have. IMO, having some error reports quickly pointing us to the problematic spot is far better than being a bit faster and letting the code explore the unknown...

What do you people think on this?

**Comment by aktau** [comment]
Agreed.

**Comment by justinmk** [comment]
Do we have to enable debug symbols to enable asserts? What's the performance impact? Running in debug mode seems to be noticeably slower.

**Comment by aktau** [comment]
> Do we have to enable debug symbols to enable asserts?

I don't think so. But we might need to fancy up a symbolizer script if that's possible, to make sense of crashes that users report to us.

> Running in debug mode seems to be noticeably slower.

I suspect that's more because of the missed optimization opportunities (inlining, ...), debug output (output to file is always horribly slow) and such. Afaik, assert on gcc/clang compiles down to a branch that's specifically marked as unlikely, so the performance hit should be quite minimal.

**Comment by elmart** [comment]
Please correct me if I'm wrong, but I think including debug symbols should not affect execution speed. They take disk space on the executable, but that's it. Execution flow should be the same with/without them. I also think that debug mode difference of speed is just because of optimization flags.

So, there should be no problem to included asserts *and* debug symbols (so that reports can make sense). Due to optimizations, some symbols won't be used, flow control will jump in an unexpected way at some points, but when hitting symbols they should still be valid.

Am I wrong?

**Comment by justinmk** [comment]
Sounds right to me. If we can enable asserts with optimizations, then great.

**Comment by aktau** [comment]
Yes, @elmart is right on all accounts, I believe.

**Comment by elmart** [comment]
@jszakmeister Any difficulty regarding cmake?

**Comment by fwalch** [comment]
Asserts and debug symbols is basically CMake's `RelWithDebInfo`, I believe (which is used for Arch, Ubuntu and Homebrew packages already). One difference is that we enabled `-Og` for GCC for that.

**Comment by justinmk** [comment]
@fwalch Doesn't the existence of `-Og` imply that optimizations *cannot* normally be applied (and the special `-Og` option was created in GCC to try to address that)? Hence clang won't have optimizations.

**Comment by elmart** [comment]
As far as I understand it, it's not that optimizations are off, and `-Og` is there to solve that. It's that, with `-Og`, you're setting a different optimization level (those optimizations that don't affect debug experience).

So, the question I would do is: why such different optimization level was chosen for gcc?

What we were talking above was using *the same* optimization level as release build would do. Is that not possible for any reason?

As a last thing: Maybe `-Og` for gcc is fast enough, and it gives us better error reports. So, we should probably profile the different configurations (running the full set of tests, for example), to see the real performace differences. Our intuitive guesses may be wrong. It usually happens talking about performance.

**Comment by fwalch** [comment]
`-Og` enables only optimizations that don't interfere with debugging; on Clang we just use `-O2` afair. It's possible to change this to a higher optimization level, but I guess that might mangle back traces in case of a crash or similar. That's the reason for `-Og`.

**Comment by justinmk** [comment]
@fwalch You are right. a1d411f9c991c03488c74c6266eb37cc2bab970e

That commit also has this comment:

> -DNDEBUG purposely omitted because we want assertions

So doesn't that solve this issue? I don't think we need to change the meaning of the `Release` build, that would be pointless. But we can instead choose to ship `RelWithDebInfo` (aren't we already doing that for homebrew)?

**Comment by elmart** [comment]
Well, the purpose of this was starting discussion on this. 
I didn't know we were already shipping that way. 
So, yes, I think this can be closed.

**Comment by justinmk** [comment]
@elmart Ok, I thought maybe you had seen a bug report that was lacking stacktrace info or something.
