### ISSUE TITLE
crash in ts_parser_parse

### ISSUE THREAD

**Issue by avatarnguyen** [neovim/neovim#19068]
### Neovim version (nvim -v)

NVIM v0.7.0, Build type: Release, LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no, vim version 8.2.4113

### Operating system/version

macOS Monterey 12.4

### Terminal name/version

Alacritty (0.10.1), also happened when using kitty

### $TERM environment variable

xterm-256color

### Installation

homebrew, M1 macbook

### How to reproduce the issue

Not sure how to reproduce on other machine. But when I create a new '.dart' file with nvim-tree and then start editing, then nvim crash. 
On my machine nvim crash more often lately. I deleted/switch out plugins but couldn't figure out the reason of the crash.

Here is the crash log:

[nvim_crash_23_06_22.txt](https://github.com/neovim/neovim/files/8967681/nvim_crash_23_06_22.txt)

Here is my current config: 

https://github.com/avatarnguyen/nvim/tree/use_dart_lsc

### Expected behavior

expected to work normally and not crash

### Actual behavior

I often got this 'Segmentation fault' 

![Bildschirmfoto 2022-06-23 um 15 05 38](https://user-images.githubusercontent.com/39520774/175309905-42352979-bce6-4dd2-a9de-7422a0ff3dd9.png)

**Comment by clason** [comment]
It seems you are using treesitter highlighting. Can you try
1. with the latest nightly
2. with nvim-treesitter disabled (for dart files)?

**Comment by avatarnguyen** [comment]
> It seems you are using treesitter highlighting. Can you try
> 
> 1. reinstalling treesitter (`brew reinstall tree-sitter neovim`),
> 
> 2. with the latest nightly (built from source, ideally),
> 
> 3. with nvim-treesitter disabled (for dart files)?
> 
> 

1. and 2. didn't fix the problem for me but 3. did. I deactivated treesitter highlighting for dart and the crash is gone. Thank you for the hints!

Since knowing the caused I dig a bit in treesitter repo and found this fix:

https://github.com/nvim-treesitter/nvim-treesitter/issues/2972#issuecomment-1141515269
