### ISSUE TITLE
`nvim_win_set_cursor()` doesn't redraw for cursorcolumn

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#19063]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+441-ge651ae586

### Vim (not Nvim) behaves the same?

No

### Operating system/version

EndeavourOS 5.18.3-arch1-1

### Terminal name/version

xfce4-terminal 1.0.4 (Xfce 4.16)

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

1. Create 'init-cursorline.lua' with the following content:
    ```lua
    -- Make cursorline and cursorcolumn more visible
    vim.cmd('hi CursorColumn ctermbg=1')
    vim.cmd('hi CursorLine ctermbg=1')

    vim.cmd('belowright wincmd v')

    vim.api.nvim_buf_set_lines(0, 0, -1, true, { 'aaa', 'bbb', 'ccc' })
    for _, win_id in ipairs(vim.api.nvim_list_wins()) do
      vim.api.nvim_win_set_option(win_id, 'cursorline', true)
      vim.api.nvim_win_set_option(win_id, 'cursorcolumn', true)
    end
    ```
2. `nvim -u init-cursorcolumn.lua`
3. Execute `:lua vim.api.nvim_win_set_cursor(1001, {3, 2})`. This changes cursor position in the non-current window, redraws cursorline, but not cursorcolumn. Explicit call `:redraw` places cursorcolumn where it should be.

This seems to be known about (#17414). Decided to make the issue so that this less likely get forgotten.

### Expected behavior

Cursorcolumn is updated immediately. Like with `windo call cursor(3, 3)` but only for specified window.

### Actual behavior

https://user-images.githubusercontent.com/24854248/175272920-bb8d2e14-2d94-415b-989a-fd2011c816e0.mp4

**Comment by Jlll1** [comment]
I'd be happy to tackle this one. Would this be good as a first issue? Any directions to get me going?

**Comment by zeertzjq** [comment]
Probably just need to call `validate_cursor()`

**Comment by Jlll1** [comment]
Well, that seems to be correct. `validate_cursor()` needs to be called in similar fashion to how `update_topline_win` does `update_topline` when the updated window is not current one.
https://github.com/neovim/neovim/blob/2685d27cd65ea255f9bf1fce44a355e235016212/src/nvim/move.c#L337-L343

I'll make sure to have a PR for this tomorrow, then. Thank you!

**Comment by zeertzjq** [comment]
Or maybe just calling `check_cursor_moved()` and `curs_columns()` with `wp`.
