### ISSUE TITLE
`pattern` key of `nvim_exec_autocmds` should take both arrays and strings

### ISSUE THREAD

**Issue by noib3** [neovim/neovim#19089]
### Neovim version (nvim -v)

v0.8.0-dev

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

macOS 12.4

### Terminal name/version

Alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

Nix

### How to reproduce the issue

```
nvim -u NONE
:lua vim.api.nvim_exec_autocmds("BufAdd", {pattern={"*.py"}})
```

### Expected behavior

Autocommands set in python files triggered on `BufAdd` are executed.

### Actual behavior

`E5108: Error executing lua [string ":lua"]:1: 'pattern' must be a string`

The docs [say](https://github.com/neovim/neovim/blob/9f592780b5bb8c69e18784c440c711dc5a4684e2/src/nvim/api/autocmd.c#L768) the `pattern` key can take both a string or an array, but actually [only strings](https://github.com/neovim/neovim/blob/9f592780b5bb8c69e18784c440c711dc5a4684e2/src/nvim/api/autocmd.c#L837) are accepted.

Either the docs or the code should be updated. I'd prefer the latter.

**Comment by clason** [comment]
Looks like this was one of the things left on the table in the effort to get this massive feature shipped.

It's not trivial, but PR very welcome! (You can follow the implementation in `nvim_get_autocmds()` in `src/nvim/api/autocmd.c`.)
