### ISSUE TITLE
Unable to map <C-i>

### ISSUE THREAD

**Issue by eskinderg** [neovim/neovim#19087]
### Neovim version (nvim -v)

0.7

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 20.04

### Terminal name/version

Terminator

### $TERM environment variable

xterm-256color

### Installation

dpkg

### How to reproduce the issue

Upgrade neovim **0.6** to **0.7** and try mapping `<C-i>` and nothing happens

`nmap<C-i> :bn<cr>` nothing happens

### Expected behavior

Should be able to map `<C-i>` to some command

### Actual behavior

Mapping for `<C-i>` not working

**Comment by bew** [comment]
Duplicate of #17867
