### ISSUE TITLE
Neovim does not compile in Debug mode when libintl is turned off

### ISSUE THREAD

**Issue by qvacua** [neovim/neovim#19093]
### Neovim version (nvim -v)

4c7462fdb313a64d6903809ece2d8d564c0ea420

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 12.4

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

build from repo

### How to reproduce the issue

With 4c7462fdb313a64d6903809ece2d8d564c0ea420, when `libintl` is turned off via `-DENABLE_LIBINTL=OFF`, Neovim does not compile in Debug mode with the following error message:

```
...
[201/331] Building C object src/nvim/CMakeFiles/nvim.dir/eval.c.o
FAILED: src/nvim/CMakeFiles/nvim.dir/eval.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DEXITFREE -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -Dnvim_EXPORTS -I/Users/hat/Projects/neovim/build/config -I/Users/hat/Projects/neovim/src -I/Users/hat/Projects/neovim/build/src/nvim/auto -I/Users/hat/Projects/neovim/build/include -I/Users/hat/Projects/neovim/.deps/usr/include/luajit-2.1 -isystem /Users/hat/Projects/neovim/.deps/usr/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -g -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always  -Wno-conversion -MD -MT src/nvim/CMakeFiles/nvim.dir/eval.c.o -MF src/nvim/CMakeFiles/nvim.dir/eval.c.o.d -o src/nvim/CMakeFiles/nvim.dir/eval.c.o -c /Users/hat/Projects/neovim/src/nvim/eval.c
/Users/hat/Projects/neovim/src/nvim/eval.c:473:3: error: implicit declaration of function 'free_locales' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  free_locales();
  ^
/Users/hat/Projects/neovim/src/nvim/eval.c:473:3: note: did you mean 'free_titles'?
/Users/hat/Projects/neovim/build/include/buffer.h.generated.h:58:16: note: 'free_titles' declared here
DLLEXPORT void free_titles(void);
               ^
1 error generated.
[212/331] Building C object src/nvim/CMakeFiles/nvim.dir/eval/funcs.c.o
ninja: build stopped: subcommand failed.
make: *** [nvim] Error 1
```

The previous commit, b1b58020094a2ffa85e40194b8beb2945396610a, to 4c7462f does not have this issue. As you can see in the following, the issue occurs only in Debug mode with `libintl` turned off:

```bash
# No issue
git checkout b1b5802

# The following Debug build works
make distclean; make SDKROOT=$(xcrun --sdk macosx --show-sdk-path) CMAKE_EXTRA_FLAGS="-DENABLE_LIBINTL=OFF"
# The following Release build works
make distclean; make CMAKE_BUILD_TYPE=Release SDKROOT=$(xcrun --sdk macosx --show-sdk-path) CMAKE_EXTRA_FLAGS="-DENABLE_LIBINTL=OFF"

# Compile error when in Debug and libintl turned off
git checkout 4c7462f

# The following Debug build does not work
make distclean; make SDKROOT=$(xcrun --sdk macosx --show-sdk-path) CMAKE_EXTRA_FLAGS="-DENABLE_LIBINTL=OFF"

# The following Debug build works
make distclean; make SDKROOT=$(xcrun --sdk macosx --show-sdk-path)

# The following Release build works
make distclean; make CMAKE_BUILD_TYPE=Release SDKROOT=$(xcrun --sdk macosx --show-sdk-path) CMAKE_EXTRA_FLAGS="-DENABLE_LIBINTL=OFF"
```

I'm using Xcode 13.4 on macOS 12.4. (I'm not sure to whom this issue is relevant other than to me... 😅 I noticed this because I turn `libintl` off when compiling `libnvim` for VimR.)

### Expected behavior

Neovim in Debug mode should compile even when `libintl` is turned off.

### Actual behavior

Neovim in Debug mode does not compile when `libintl` is turned off (with the introduction of 4c7462fdb313a64d6903809ece2d8d564c0ea420).

**Comment by clason** [comment]
I don't think anybody else is using (or even aware of) `libnvim` ;)

Just to be clear: this is happening with the current HEAD of master? Did you see that we now link `libintl` statically on macOS -- does this still require you to turn off `libintl`?

**Comment by qvacua** [comment]
@clason : Yes, it happens on the current master. However, I see that @zeertzjq already created a PR. :) I turned `libintl` off to have less dependency management for building universal binary; I saw that there was a PR regarding this, too. Most probably, I can easily turn it back on.

**Comment by clason** [comment]
Yep, that should definitely be fixed (and @zeertzjq is on point, as always).

As one of the most "professional" consumers of nvim on macOS, I would be interested in hearing from you how these build changes affect you, and whether more can be done to make your life easier.

**Comment by qvacua** [comment]
@clason : The recent changes (d0644fa9bfc3fa3abdd886d2ef13533778317154 by @carlocab) for building universal binary/lib is a life-saver! Until now, I had to build the x86 version of `libnvim` using GitHub actions, the arm64 version locally on my machine, and `lipo` them together locally. These changes will simplify my build process considerably. 😀

Currently, I can't think of any other improvements for building `nvim / libnvim`. It's just one command to build a universal version locally and on GitHub actions!

**Comment by clason** [comment]
That's great to hear! You'll notice that these changes have been backported to the `release-0.7` branch, so should already help with the imminent 0.7.1 release :)
