### ISSUE TITLE
Refactoring shadacat.py 

### ISSUE THREAD

**Issue by blankRiot96** [neovim/neovim#19097]
### Feature already in Vim?

No

### Feature description

<a href="https://github.com/neovim/neovim/blob/master/scripts/shadacat.py">shadacat.py</a> can have some work done on it. Would like to refactor the file. 
Including usage of OOP and cleaner indentation in regards to the using context managers.

**Comment by justinmk** [comment]
Thank you for the help, but please first ask what the use-case is before making a change.

`scripts/shadacat.py` is only used for rare circumstances. If there's a bug, fixes are welcome. Refactoring it isn't wanted, because it could introduce regressions, which would just be a waste of time.
