### ISSUE TITLE
inccommand (command preview): restore multiple buffers

### ISSUE THREAD

**Issue by smjonas** [neovim/neovim#19103]
### Feature already in Vim?

No

### Feature description

Using the command preview feature, when the user exits the command line or executes the command, the buffer state of the current buffer is restored (highlights and text).
If for some reason, one wants to show the command preview in multiple buffers at the same time, this convenience is lost. A workaround is to manage the highlights and changed buffer state manually but this seems pretty hacky. It would be convenient if one could optionally return a list of buffer numbers that indicate which buffers should be reset to their original state after the preview has finished:
```lua
local function trim_space(opts, preview_ns, preview_buf)
  -- ...
  if preview_ns ~= nil then
    return 2, { 0, 1, 2 } -- clear multiple buffers
  end
end
```
Not sure about the API, just thought I'd put this out here for further discussion as @famiu had signaled interest [here](https://github.com/smjonas/inc-rename.nvim/issues/5#issuecomment-1152854287).

**Comment by justinmk** [comment]
> If for some reason, one wants to show the command preview in multiple buffers at the same time, this convenience is lost.

Do we have a use case besides "for some reason"?

**Comment by smjonas** [comment]
> Do we have a use case besides "for some reason"?

Yes, highlighting of variables "in real-time" when renaming across multiple files using LSP. See my plugin [inc-rename.nvim](https://github.com/smjonas/inc-rename.nvim).
