### ISSUE TITLE
automate publishing to winget

### ISSUE THREAD

**Issue by vedantmgoyal2009** [neovim/neovim#19108]
### Feature description

With every new release of Neovim, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

I can create a pull request if the maintainers would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.

* Reference/Continuation of https://github.com/neovim/neovim/issues/12571

**Comment by clason** [comment]
The Neovim project is not involved in managing releasing to distributions, and we can't take on that added burden.

If there are changes we can make to our release workflow that simplify the _distribution maintainer's_ work doing that without adding to ours, let us know, though.

**Comment by vedantmgoyal2009** [comment]
Do you mean https://github.com/neovim/neovim/blob/master/.github/workflows/release.yml file?

**Comment by clason** [comment]
Yes, or build scripts. Note that these are for publishing the binaries to _our_ Releases page, not for pushing to other services. (And the linked issue was concluded by someone adding Neovim to Winget via a PR to that repo, so to my knowledge this issue is solved? What is left to be done here?)

**Comment by vedantmgoyal2009** [comment]
> What is left to be done here?

Currently, the manifests at winget have to be updated with every new release of neovim. I was thinking if an additional step in your release workflow would do the same, it would reduce the manual work of checking and updating manifests manually everytime.

**Comment by clason** [comment]
That is the same for every other distribution on the planet, and the job of the distribution maintainers (or contributors, if they crowdsource this). We cannot take on that job -- even if someone set up a workflow, this will have to be maintained and adapted to future changes.

**Comment by vedantmgoyal2009** [comment]
I don't think so, it will be just an addition of 4-5 lines, and it would do all the things automatically.

**Comment by vedantmgoyal2009** [comment]
It doesn't need a _really_ big workflow to accomplish the same :)

**Comment by vedantmgoyal2009** [comment]
@clason It doesn't need a _really_ big workflow. There will be just an addition of 4-5 lines of code in the existing release workflow, and it would update the manifests at winget-pkgs repo automatically.

**Comment by justinmk** [comment]
We do this for snap, so if there's an easy way to do it for winget then we should. PR welcome

**Comment by vedantmgoyal2009** [comment]
I think I can simply the workflow without making any changes to the process. Shoould I do it?

**Comment by justinmk** [comment]
sure, a PR will be easier to discuss

**Comment by justinmk** [comment]
@vedantmgoyal2009 btw I noticed in https://github.com/flathub/io.neovim.nvim/pull/40 that flatpak has https://github.com/flathub/flatpak-external-data-checker which automates stuff on their end. Are you sure that winget doesn't have something like that or is planning to?

**Comment by vedantmgoyal2009** [comment]
> sure, a PR will be easier to discuss

Okay 👍🏻

> @vedantmgoyal2009 btw I noticed in [flathub/io.neovim.nvim#40](https://github.com/flathub/io.neovim.nvim/pull/40) that flatpak has https://github.com/flathub/flatpak-external-data-checker which automates stuff on their end. Are you sure that winget doesn't have something like that or is planning to?

As of now, there isn't.
