### ISSUE TITLE
Some LSP features not handled properly, memory leak with tailwindcss(example)

### ISSUE THREAD

**Issue by username664** [neovim/neovim#19118]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+468-ge694e5642

### Vim (not Nvim) behaves the same?

in vim with coc-nvim - all is fine and other editors

### Operating system/version

Debian 11

### Terminal name/version

xfce4-terminal 0.8.10 (Xfce 4.16)

### $TERM environment variable

xterm-256color

### Installation

nvim-linux64.deb

### How to reproduce the issue

Just install tailwindcss language server and try to use it some time. You will see that memory growing high (1.3GB process of nvim)  and not handled properly.
i have tried nvim-cmp and ddc.vim.
In another editors and in coc-nvim - memory stable and not growing.
And because of it - i think some features of impl. of nvim native lSP is broken, don't know how to dig more into that.

https://user-images.githubusercontent.com/96973293/175874963-2d2c1992-779e-4709-9d68-02bbd74ba075.mp4

### Expected behavior

Stable memory, no lags.

### Actual behavior

Memory growing over time, not handled properly, lags.

**Comment by justinmk** [comment]
Just for reference, 

can you check that you are using a Release or RelWIthDebInfo build, _not_ Debug. 

    :checkh nvim

what log level is vim.lsp using?

    :lua =require('vim.lsp.log').get_level()

**Comment by username664** [comment]
> Just for reference,
> 
> can you check that you are using a Release or RelWIthDebInfo build, _not_ Debug.
> 
> ```
> :checkh nvim
> ```
> 
> what log level is vim.lsp using?
> 
> ```
> :lua =require('vim.lsp.log').get_level()
> ```

```
nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6203'
  - INFO: $COLORTERM='truecolor'
```

`Log level 3`

**Comment by jones-sam** [comment]
Same issue here, I am switching from Coc and this issue is making the switch impossible, while using tailwind nvim uses way more ram and is laggy.

On v0.7.2 on Macbook m1

**Comment by mfussenegger** [comment]
Is this also reproducable with any other language server? If not it would point to a problem with tailwindcss.

Please also try to deactivate other unrelated plugins like nvim-cmp or ddc.vim. It would need a minimal reproduction to do something about this - if it even is a neovim problem.

**Comment by siblanco** [comment]
I can reproduce the issue and it only happens with tailwind attached + actually suggesting classes. Only being attached won't affect the memory.

**Comment by siblanco** [comment]
> Is this also reproducable with any other language server? If not it would point to a problem with tailwindcss.
> 
> Please also try to deactivate other unrelated plugins like nvim-cmp or ddc.vim. It would need a minimal reproduction to do something about this - if it even is a neovim problem.

@mfussenegger I've tested it with kickstart.nvim (https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua) and unfortunately same results...as soon as the tailwind LSP has been attached and classes get suggested, the memory usage goes up to 1.3gb and neovim is laggy as hell. 

Disabling nvim-cmp fixes this, no more laggs, but also no more suggestions which is what we primarily use the tailwind LSP for.
Looks like nvim-cmp it might be an issue with nvim-cmp?!

To reproduce it:
- install kickstart.nvim and add 'tailwindcss' to the servers table in line 299.
- quit neovim
- mkdir test && touch test/index.html test/tailwind.config.js
- nvim test and start adding classes to an element in index.html -> make sure the tailwind LSP has been successfully installed and attached, you'll know once you get the class suggestions

If you want me to prepare a repo with the edited kickstart.nvim and also a repo to test tailwind let me know.

**Comment by Shougo** [comment]
@siblanco Please create the minimal reproduce repo for tailwindcss.
I don't use tailcss and it is hard to test.

**Comment by Shougo** [comment]
And please test other LSP servers.  If it is reproduce-able in tailwindcss server, it seems server implementation problem.

**Comment by Shougo** [comment]
@username664 Please create the minimal init.vim with ddc.vim.
I will try it.

**Comment by siblanco** [comment]
@Shougo is a minimal reproduce repo still needed? I can prepare everything, let me know

**Comment by Shougo** [comment]
I have tested the completion with ddc.vim.
It works and I don't reproduce the problem.

**Comment by Shougo** [comment]
Hm.  The test of `ddc.vim` seems old.  I think the latest does not have the problem.

**Comment by Shougo** [comment]
I have tested it with nvim-cmp, but I don't reproduce the memory usage problem.

**Comment by username664** [comment]
Some explonations:
https://github.com/hrsh7th/nvim-cmp/issues/1009#issuecomment-1257179645

**Comment by vagnermaltauro** [comment]
i gave the same problem!
