### ISSUE TITLE
Error detected while processing FileType Autocommands for "*" when calling nvim_exec_autocmd("FileType", {})

### ISSUE THREAD

**Issue by fsouza** [neovim/neovim#19113]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+494-g59835e76b

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

macOS 12.4

### Terminal name/version

alacritty 0.10.1 (2844606)

### $TERM environment variable

screen-256color

### Installation

Manually compiled

### How to reproduce the issue

```
nvim --clean
:call nvim_exec_autocmds("FileType", {})
```

### Expected behavior

Autocmds are executed.

### Actual behavior

```
Error detected while processing FileType Autocommands for "*":
E474: Invalid argument: syntax=*
```

**Note 1:** this looks like a regression. I've done this in my dotfiles for some time, but please let me know if I'm doing something wrong 😁 I've been AFK for some time, so I have no idea which change introduced the issue, but I can try to bisect it some time this week.

**Note 2:** the vimscript way (`doautoall FileType *`) also causes the same error.

**Comment by zeertzjq** [comment]
Hmm, Vim behave the same.

**Comment by fsouza** [comment]
> Hmm, Vim behave the same.

Ohh ops, my bad. When filling the form I assumed it was just `nvim_exec_autocmds` and only later I realized that I could also repro with `doautoall`. Edited the description.

**Comment by gpanders** [comment]
`nvim_exec_autocmds` was [recently changed](https://github.com/neovim/neovim/pull/19091) to use `*` as the default pattern when the `pattern` key is omitted. Prior to #19091, omitting `pattern` was equivalent to `pattern=""`. This is probably not correct, as in `:doautoall` the `fname` argument (equivalent to `pattern` in `nvim_exec_autocmds` is optional).

In any case, your snippet `nvim_exec_autocmds('FileType', {})` used to do `:doautoall FileType ""`, but now does `:doautoall FileType *`.

From `:h :doautoall`:

```
			Note that [fname] is used to select the autocommands,
			not the buffers to which they are applied. Example:
				augroup mine
				  autocmd!
				  autocmd FileType * echo expand('<amatch>')
				augroup END
				doautoall mine FileType Loaded-Buffer
			Sourcing this script, you'll see as many
			"Loaded-Buffer" echoed as there are loaded buffers.
```

So `:doautoall FileType *` means you are (essentially) setting the filetype to `*` in each loaded buffer, which is where the error comes from.

For the time being, you should be able to use `pattern=""`.
