### ISSUE TITLE
cmdheight=0: (1) :s unexpectedly scroll screen up by one line; (2) msgArea background color inconsistent

### ISSUE THREAD

**Issue by wang-tc** [neovim/neovim#19112]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+428-g1493efdc1

### Vim (not Nvim) behaves the same?

no, vim does not have this feature

### Operating system/version

Ubuntu 22.04

### Terminal name/version

alacritty Version 0.11.0-dev (ad3ebba5)

### $TERM environment variable

xterm-256color

### Installation

sudo apt install ./nvim-linux64.deb

### How to reproduce the issue

```
nvim --clean
:set cmdheight=0
:set laststatus=0
:hi msgArea ctermbg=red
```
insert many lines (200~)
```
:s
```

### Expected behavior

screen does not scroll, the whole command line is red
![expected](https://user-images.githubusercontent.com/77646015/175836262-99bc195d-f6aa-4ea9-b30d-b09a910ea412.gif)

### Actual behavior

- screen scroll up by 1 line
- command line color is not completely red
![actual](https://user-images.githubusercontent.com/77646015/175836290-9f1881f2-7879-4812-8d79-d95cb463c045.gif)

**Comment by Shougo** [comment]
> screen scroll up by 1 line

I know.  It seems redraw behavior.

> command line color is not completely red

I need to fix it...

**Comment by Shougo** [comment]
`set inccommand=nosplit` seems redraw in command line.

**Comment by Shougo** [comment]
> :s unexpectedly scroll screen up by one line

It is very very hard to fix and I don't think it is fatal.  Any helps are appreciated.

**Comment by Shougo** [comment]
I have fixed the problems in https://github.com/neovim/neovim/pull/18961.
Please test.

**Comment by wang-tc** [comment]
@Shougo Thank you very much for the fix. 
I tested it and found the color problem is solved. 
For the scroll problem, it seems that commandline now always make the screen scroll up by 1 line, however, I originally expect the screen does not scroll in any situation (including `:s`) (I think this is also what I mean in the issue description, apologies if the description is confusing). Please let me know if you intend to make the screen scroll or not to scroll.

**Comment by Shougo** [comment]
The scroll is expected behavior.  It was not redrawn until my fix.

`set cmdheight=0` changes `set cmdheight=1` if you go to command line mode.
And `command_height()` is called when `cmdheight` is changed.
The scroll is executed in it.

**Comment by Shougo** [comment]
You can change `cmdheight` manually and check it scrooll the screen.

**Comment by wang-tc** [comment]
True, that's a valid point and I certainly respect your decision. 

But when we run commands, we normally don't need to know where the cursor is, even if it is behind the command line. I was just wondering if there is any vimscript/lua setting to disable the scrolling behaviour? I tried `autocmd CmdlineEnter * execute 'normal! "\<C-y>"' | redraw` but it does not work. Thanks.

**Comment by rkmiec** [comment]
I've also noticed one issue with `cmdheight=0`.
When in visual mode (any of them), the command is not visible and the cmdline is not extended.
Steps to reproduce:
1. start nvim (-u NONE has the same behavior),
1. `:set cmdheight=0`
1. enter visual mode, line visual mode or block visual mode
1. press colon to enter command
1. command is covered by status line

**Comment by wang-tc** [comment]
@Shougo Just found an issue with your newest patch: it seems that if the cursor is in the upper half of the screen, then entering command line will not make the screen scroll. If the cursor is in the lower half of the screen, then entering command line will make the screen scroll.

**Comment by Shougo** [comment]
> @Shougo Just found an issue with your newest patch: it seems that if the cursor is in the upper half of the screen, then entering command line will not make the screen scroll. If the cursor is in the lower half of the screen, then entering command line will make the screen scroll.

Yes.  It is the known feature of `cmdheight` changes.

**Comment by Shougo** [comment]
> But when we run commands, we normally don't need to know where the cursor is, even if it is behind the command line. I was just wondering if there is any vimscript/lua setting to disable the scrolling behaviour? I tried autocmd CmdlineEnter * execute 'normal! "\<C-y>"' | redraw but it does not work. Thanks.

The PR is wellcome if you can fix/improve the behavior.  It is OSS.
I don't think the fix is easy and it may break other behavior.
You can guarantee it?

The problem is very small and my policy is `just work is than best behavior`.

**Comment by Shougo** [comment]
You can see `update_screen()` -> `win_update()` implementation if you want to fix the behavior.

**Comment by Shougo** [comment]
> @Shougo Just found an issue with your newest patch: it seems that if the cursor is in the upper half of the screen, then entering command line will not make the screen scroll. If the cursor is in the lower half of the screen, then entering command line will make the screen scroll.

I think the behavior is Vim/neovim don't want to hide bottom lines even it is not cursor line.

**Comment by wang-tc** [comment]
@Shougo Thank you for pointing out the right direction. I am still a beginner in neovim/vim, hopefully I am able to contribute to the community one day. For now, I think I am gonna go with `set inccommand= `, which disables the `:s` scrolling. I will close the issue now. Thank you for your contribution again.

**Comment by Shougo** [comment]
OK.

**Comment by xaviervalarino** [comment]
@wang-tc if you use a global statusline with `laststatus=3` you can stop the scroll by toggling between the statusline and the cmdline with an autocommand:

```lua
-- initial setting
vim.opt.cmdheight = 0
vim.opt.laststatus = 3

local cmd_status = vim.api.nvim_create_augroup('CmdlineStatus', { clear = true })

-- Set up a custom User event
------------------------------------------------------------------------------------------------
-- Capture keys that enter Command-line mode
-- "CmdlineEnter" event doesn't happen until after these keys are pressed, which isn't fast enough
-- to counteract the cmdline shift
for _, char in pairs { ':', '/', '?', '!' } do
  vim.keymap.set('', char, function()
    vim.api.nvim_exec_autocmds('User', { pattern = 'CmdlineEnterPre', group = 'CmdlineStatus' })
    vim.fn.feedkeys(char, 'n') -- 'n': do not remap keys, any other option locks up Vim
  end)
end

vim.api.nvim_create_autocmd({ 'CmdlineLeave' }, {
  group = 'CmdlineStatus',
  callback = function()
    vim.api.nvim_exec_autocmds('User', { pattern = 'CmdlineLeavePost', group = 'CmdlineStatus' })
  end,
})

-- Toggle between the statusline and cmdline based on the custom events
------------------------------------------------------------------------------------------------
vim.api.nvim_create_autocmd('User', {
  group = 'CmdlineStatus',
  pattern = { 'CmdlineEnterPre', 'CmdlineLeavePost' },
  callback = function(ctx)
    local separator = vim.opt.fillchars:get().horiz or '─'
    if ctx.match == 'CmdlineEnterPre' then
      vim.opt.cmdheight = 1
      vim.opt.laststatus = 0
      -- make last statusline look like a window separator if there are splits
      vim.opt.statusline = '%#WinSeparator#' .. string.rep(separator, vim.fn.winwidth '.')
    else
      vim.opt.cmdheight = 0
      vim.opt.laststatus = 3
      -- reset your statusline
      vim.opt.statusline = ''
    end
  end,
})

```
