### ISSUE TITLE
Thai language being displayed incorrectly

### ISSUE THREAD

**Issue by grindarius** [neovim/neovim#19126]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

no, vim 8.1.3741

### Operating system/version

WSL2 on Windows 10 21H2

### Terminal name/version

bash terminal 5.0.17(1)-release

### $TERM environment variable

xterm-256color

### Installation

linuxbrew

### How to reproduce the issue

1.  `nvim --clean`
2. type some thai word like `สวัสดีครับ` into neovim (copy and paste will not work)

### Expected behavior

the word will be separated nicely. the travel by keystroke works like expected and the cursor covers the actual character (this is taken from another editor. I apologize if this is not appropriate).
![vscode-counterpart](https://user-images.githubusercontent.com/60266519/175967018-e9b95219-111d-4f12-ad62-e92511ffac7b.gif)

### Actual behavior

When you actually type thai language into `neovim` (with configurations _enabled_, link [here](https://gist.github.com/grindarius/ef7aa954c8eae00510bb5cc6688d724a)), the characters does not line up with the cursor as you type.
![sawasdee](https://user-images.githubusercontent.com/60266519/175961595-2ec403f3-14af-431f-91df-de653fa5b8c2.gif)
in this gif, I type the word `สวัสดีครับ` character by character.

The behavior is different when `neovim` is run with `--clean` flag. What happens is that the top and bottom vowels like `ุ (U+0E38)` or `ั (U+0E31)` will not get rendered.
![nvim-clean](https://user-images.githubusercontent.com/60266519/175962433-c49a8f97-db64-4ca3-9e93-260e3f57059d.gif)
in this gif, I type the word `สวัสดีครับ` character by character, but the behavior is different.

The same behavior that occurred when running `nvim --clean` goes for `vim -u DEFAULTS` too.
![vim](https://user-images.githubusercontent.com/60266519/175962982-f8c98696-a175-4aa0-ab85-fe7a243251f1.gif)

The editor is using `Caskaydia Cove Nerd Font`, I've installed the Windows Compatible version. I have tried opening the `Caskaydia Cove Nerd Font` with FontForge to see if there's any thai characters in it and have found that the font does not contain thai characters. However, I have tried switching Windows Terminal's font to [SOV_monomon](https://www.f0nt.com/release/sov_monomon/) but the problem still persists.

This is the information coming from command `locale`.
```
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

**Comment by grindarius** [comment]
> Maybe it's depend on terminal emulator? I use [kitty](https://sw.kovidgoyal.net/kitty/)(linux and mac only) and it look like thlis: 
> ![test](https://user-images.githubusercontent.com/43566401/176466912-91f48885-403f-4e3d-8e18-2f003732b0d4.png)
> and this with [st](https://st.suckless.org/) 
> ![test](https://user-images.githubusercontent.com/43566401/176467643-d0c0c985-f1d2-4069-8022-b90f0fc8b090.png)
> Kitty is the only one that I think handle it quite well, it's narrow wide character like `ญ`, `ณ`, `ฒ` to fit in one character space. but around the narrow character like `เ`, `ไ`, `า`, still ugly though.
>  the downside is somehow it handle some word like `พี่`, `กู้`  to be one character(it should be 3) so when delete in insert mode it delete whole word, and the hybrid one like `ดำ`(`ด` and `ำ`) become `ดา` (`ด` and `า`), in another program like w3m has this problem too.
> 
> And in iterm, look like they not have any problem. in [this](https://armno.in.th/blog/thai-in-osx-terminal/)
> 
> Our language really complicate, Sadly, it's is only thing that stop me from using neovim on everything, really hope one day we thai people will no longer suffer from anything like this.

May I ask what fonts are you using on both of your examples?

**Comment by spywhere** [comment]
I can doubled the confirmation for @pk-kampanart. While the samples from @pk-kampanart seem to be on Linux system. Here's the sample from both kitty and macOS built-in Terminal on macOS.

kitty

<img width="611" alt="Screen Shot 2565-06-30 at 13 37 48" src="https://user-images.githubusercontent.com/1087399/176609563-0a0cc7ab-0725-44f4-b066-e2a4fd64e3b1.png">

macOS Terminal

<img width="682" alt="Screen Shot 2565-06-30 at 13 38 30" src="https://user-images.githubusercontent.com/1087399/176609605-14650d7e-d6ad-4586-8d02-c1cf10accf3f.png">

I believe both of my terminals are using the fallback font, which is the system monospace font.

**Comment by pk-kampanart** [comment]
> May I ask what fonts are you using on both of your examples?
@grindarius  It's (Jetbrain Mono)[https://www.jetbrains.com/lp/mono/] but I use nerd fonts verrsion.

**Comment by grindarius** [comment]
I have confirmed that each output differs on each emulator, so this is not related to Neovim.
