### ISSUE TITLE
Scrolling to the right makes the highlighting of folded look wrong

### ISSUE THREAD

**Issue by yamam** [neovim/neovim#19123]
### Neovim version (nvim -v)

v0.8.0-dev+500-gf3c8f3e5d

### Vim (not Nvim) behaves the same?

no, vim 8.2.5126

### Operating system/version

Linux 5.10.102.1-microsoft-standard-WSL2 Ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

min.vim
```vim
set nocp
set nowrap
" {{{
set foldmethod=marker
```
nvim --clean -u min.vim min.vim
type `zl`

### Expected behavior

the correct folded highlighting is as follows.
![image](https://user-images.githubusercontent.com/12369962/175943662-e8bdd51d-4a3f-448d-8eba-85c5a41136b9.png)

### Actual behavior

Scrolling to the right with zl will remove the folded background color.
![image](https://user-images.githubusercontent.com/12369962/175943719-6c8ca286-3e36-4b9d-a988-41f4623661e6.png)

**Comment by justinmk** [comment]
related #10789

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
index b9c38d933..0527b284c 100644
--- a/src/nvim/screen.c
+++ b/src/nvim/screen.c
@@ -2909,7 +2909,7 @@ static int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool noc
 
     if (draw_state == WL_LINE
         && has_fold
-        && vcol == 0
+        && col == 0
         && n_extra == 0
         && row == startrow) {
       char_attr = win_hl_attr(wp, HLF_FL);
```
