### ISSUE TITLE
The "lines" indicator when folded is not translated

### ISSUE THREAD

**Issue by yamam** [neovim/neovim#19124]
### Neovim version (nvim -v)

v0.8.0-dev+500-gf3c8f3e5d

### Vim (not Nvim) behaves the same?

no, vim 8.2.5126

### Operating system/version

Linux 5.10.102.1-microsoft-standard-WSL2 Ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

min.vim
```vim
" {{{
set nocp
set foldmethod=marker
```
nvim --clean -u min.vim min.vim

### Expected behavior

"lines" is translated into "行" in vim
![image](https://user-images.githubusercontent.com/12369962/175948894-e015d5a9-8cf0-40c8-9356-5db22da0afef.png)

### Actual behavior

"lines" is not translated in neovim
![image](https://user-images.githubusercontent.com/12369962/175949090-e80bbfc8-1f45-4940-9ca4-2a1c005404d2.png)

**Comment by tomial** [comment]
I'm new to this project, and I tried to fix this by editing the `f_foldtext()` function in `/src/nvim/eval/funcs.c`:
```c
────────────────────────────────────────────────────────────────────────────────────────────────────┐
src/nvim/eval/funcs.c:2578: static void f_foldtext(typval_T *argvars, typval_T *rettv, FunPtr fptr) │
────────────────────────────────────────────────────────────────────────────────────────────────────┘
2578⋮2578│      }
2579⋮2579│    }
2580⋮2580│    unsigned long count = (unsigned long)foldend - foldstart + 1;
2581⋮    │-   txt = NGETTEXT("+-%s%3ld line: ", "+-%s%3ld lines: ", count);
    ⋮2581│+   txt = NGETTEXT(_("+-%s%3ld line: "), _("+-%s%3ld lines: "), count);
2582⋮2582│    r = xmalloc(STRLEN(txt)
2583⋮2583│                + STRLEN(dashes)  // for %s
2584⋮2584│                + 20              // for %3ld

And it worked when there's multiple lines:

![multiple](https://user-images.githubusercontent.com/38778062/177719069-8a6a9c23-ae78-43e6-97a3-93988d8d009d.png)

but it's in English when there's only one line:

![oneline](https://user-images.githubusercontent.com/38778062/177719325-84a50170-eafc-45ec-903e-2a8bfcdb5432.png)

I tried another langauge and it was the same, so I think the reason is lacking the "1 line" translations.

After adding those translations, it would work, it's this correct?

If it worked in this way, I'll fix this.

Thank you! 😄
@justinmk

**Comment by zeertzjq** [comment]
I think this is because the message in the translation file is singular, while this message has been updated to be plural, so the translation no longer works.

The current translation is:
```po
#, c-format
msgid "+-%s%3ld lines: "
msgstr "+-%s%3ld 行: "
```

The latest translation from Vim is:
```po
#, c-format
msgid "+-%s%3ld line: "
msgid_plural "+-%s%3ld lines: "
msgstr[0] "+-%s%3ld 行: "
```
