### ISSUE TITLE
Draw problems.

### ISSUE THREAD

**Issue by fazibear** [neovim/neovim#1914]
Hi,

I've installed neovim with brew on Maverics. Looks like there are some problems with draw.
Here is a screenshot:
![screen shot 2015-01-30 at 21 39 24](https://cloud.githubusercontent.com/assets/687/5982912/871922fe-a8c8-11e4-8169-02d28422f4b9.png)

Thanx!

**Comment by shawndumas** [comment]
+1

**Comment by justinmk** [comment]
what happens if you press CTRL+L (or `:redraw!`) to force a redraw?

**Comment by fazibear** [comment]
After I pressed CTRL+L screen will redraw, status bar will appear, but in the wrong way...

Before:
![screen shot 2015-01-30 at 22 48 44](https://cloud.githubusercontent.com/assets/687/5983982/36927830-a8d2-11e4-8175-976a207e6f1d.png)

After:
![screen shot 2015-01-30 at 22 49 00](https://cloud.githubusercontent.com/assets/687/5983983/3a6a21b0-a8d2-11e4-8879-4909f236616e.png)

**Comment by nemith** [comment]
Same here 

![screen shot 2015-01-30 at 4 42 03 pm](https://cloud.githubusercontent.com/assets/349360/5985417/f92cfe30-a89e-11e4-8908-9098ff8dc238.png)

**Comment by timfeirg** [comment]
I have the same problem just after an update today:

NVIM 0.0.0-alpha+201501301332 (compiled Jan 31 2015 14:32:03)
Commit: 6196cab139b52cd412c198f38626ec7f7688995e
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-nuXM8T/build/config -I/tmp/neovim-nuXM8T/src -I/tmp/neovim-nuXM8T/.deps/usr/include -I/tmp/neovim-nuXM8T/.deps/usr/include -I/tmp/neovim-nuXM8T/.deps/usr/include/luajit-2.0 -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I/tmp/neovim-nuXM8T/build/src/nvim/auto -I/tmp/neovim-nuXM8T/build/include
Compiled by timfeirg@timfeirg-mba.local  Features included (+) or not (-):
+acl             +extra_search    +mouse_dec       +tag_binary
+arabic          +farsi           -mouse_gpm       +tag_old_static
+autocmd         +file_in_path    +mouse_netterm   -tag_any_white
-browse          +find_in_path    +mouse_sgr       +terminfo
+byte_offset     +folding         -mouse_sysmouse  +termresponse
+cindent         -footer          +mouse_urxvt     +textobjects
-clipboard       +fork()          +mouse_xterm     +title
+cmdline_compl   +gettext         +multi_byte      -toolbar
+cmdline_hist    +iconv           +multi_lang      +user_commands
+cmdline_info    +insert_expand   +path_extra      +vertsplit
+comments        +jumplist        +persistent_undo +virtualedit
+conceal         +keymap          +postscript      +visual
+cscope          +langmap         +printer         +visualextra
+cursorbind      +libcall         +profile         +viminfo
+cursorshape     +linebreak       +quickfix        +vreplace
+dialog_con      +lispindent      +reltime         +wildignore
+diff            +listcmds        +rightleft       +wildmenu
+digraphs        +localmap        +scrollbind      +windows
-dnd             +menu            +signs           +writebackup
-ebcdic          +mksession       +smartindent     -X11
-emacs_tags      +modify_fname    +startuptime     -xfontset
+eval            +mouse           +statusline      -xsmp
+ex_extra        -mouseshape      +syntax          -xterm_clipboard
   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "$HOME/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"

**Comment by telemachus** [comment]
I'm having the same issue, and I'm also on OSX (10.9.5). (That may not be important, but a quick look suggests we're all using OSX.) 

    NVIM 0.0.0-alpha+201501301332 (compiled Jan 30 2015 19:23:17)
    Commit: 6196cab139b52cd412c198f38626ec7f7688995e
    Build type: RelWithDebInfo
    Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-AQPkBB/build/config -I/tmp/neovim-AQPkBB/src -I/tmp/neovim-AQPkBB/.deps/usr/include -I/tmp/neovim-AQPkBB/.deps/usr/include -I/tmp/neovim-AQPkBB/.deps/usr/include/luajit-2.0 -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-AQPkBB/build/src/nvim/auto -I/tmp/neovim-AQPkBB/build/include
    Compiled by _homebrew@ithaca  Features included (+) or not (-):
    +acl             +extra_search    +mouse_dec       +tag_binary
    +arabic          +farsi           -mouse_gpm       +tag_old_static
    +autocmd         +file_in_path    +mouse_netterm   -tag_any_white
    -browse          +find_in_path    +mouse_sgr       +terminfo
    +byte_offset     +folding         -mouse_sysmouse  +termresponse
    +cindent         -footer          +mouse_urxvt     +textobjects
    -clipboard       +fork()          +mouse_xterm     +title
    +cmdline_compl   +gettext         +multi_byte      -toolbar
    +cmdline_hist    +iconv           +multi_lang      +user_commands
    +cmdline_info    +insert_expand   +path_extra      +vertsplit
    +comments        +jumplist        +persistent_undo +virtualedit
    +conceal         +keymap          +postscript      +visual
    +cscope          +langmap         +printer         +visualextra
    +cursorbind      +libcall         +profile         +viminfo
    +cursorshape     +linebreak       +quickfix        +vreplace
    +dialog_con      +lispindent      +reltime         +wildignore
    +diff            +listcmds        +rightleft       +wildmenu
    +digraphs        +localmap        +scrollbind      +windows
    -dnd             +menu            +signs           +writebackup
    -ebcdic          +mksession       +smartindent     -X11
    -emacs_tags      +modify_fname    +startuptime     -xfontset
    +eval            +mouse           +statusline      -xsmp
    +ex_extra        -mouseshape      +syntax          -xterm_clipboard
       system vimrc file: "$VIM/nvimrc"
         user vimrc file: "$HOME/.nvimrc"
     2nd user vimrc file: "~/.nvim/nvimrc"
          user exrc file: "$HOME/.exrc"
      fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"

**Comment by jszakmeister** [comment]
FWIW, building directly from the Neovim tree I don't see this problem.  I did see it with the Homebrew install however. :confused:

**Comment by telemachus** [comment]
@jszakmeister Is the commit number for your build any different from mine or timfeirig's? Or is the only difference that you hand-compiled rather than using Homebrew? (If so, that would suggest something about Homebrew's build-options or process may be partly at issue.)

**Comment by jszakmeister** [comment]
@telemachus Nope:

```text
NVIM 0.0.0-alpha+201501301332 (compiled Jan 31 2015 08:50:04)
Commit: 6196cab139b52cd412c198f38626ec7f7688995e
Build type: Release
Compilation: /usr/bin/clang -Wconversion -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/Users/jszakmeister/projects/neovim/neovim/build/release/config -I/Users/jszakmeister/projects/neovim/neovim/src -I/Users/jszakmeister/projects/neovim/neovim/.deps/usr/include -I/Users/jszakmeister/projects/neovim/neovim/.deps/usr/include -I/Users/jszakmeister/projects/neovim/neovim/.deps/usr/include/luajit-2.0 -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -I/Users/jszakmeister/projects/neovim/neovim/build/release/src/nvim/auto -I/Users/jszakmeister/projects/neovim/neovim/build/release/include
Compiled by jszakmeister@sidious.home  Features included (+) or not (-):
+acl             +extra_search    +mouse_dec       +tag_binary
+arabic          +farsi           -mouse_gpm       +tag_old_static
+autocmd         +file_in_path    +mouse_netterm   -tag_any_white
-browse          +find_in_path    +mouse_sgr       +terminfo
+byte_offset     +folding         -mouse_sysmouse  +termresponse
+cindent         -footer          +mouse_urxvt     +textobjects
-clipboard       +fork()          +mouse_xterm     +title
+cmdline_compl   +gettext         +multi_byte      -toolbar
+cmdline_hist    +iconv           +multi_lang      +user_commands
+cmdline_info    +insert_expand   +path_extra      +vertsplit
+comments        +jumplist        +persistent_undo +virtualedit
+conceal         +keymap          +postscript      +visual
+cscope          +langmap         +printer         +visualextra
+cursorbind      +libcall         +profile         +viminfo
+cursorshape     +linebreak       +quickfix        +vreplace
+dialog_con      +lispindent      +reltime         +wildignore
+diff            +listcmds        +rightleft       +wildmenu
+digraphs        +localmap        +scrollbind      +windows
-dnd             +menu            +signs           +writebackup
-ebcdic          +mksession       +smartindent     -X11
-emacs_tags      +modify_fname    +startuptime     -xfontset
+eval            +mouse           +statusline      -xsmp
+ex_extra        -mouseshape      +syntax          -xterm_clipboard
   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "$HOME/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/Users/jszakmeister/.local/neovim-latest/share/nvim"
```

The only difference is that I use the full release build, so I tried RelWithDebInfo, and that worked fine too.  Wiping out my dependencies and rebuilding everything shows the problem.  I'm not quite sure what's going on, but it seems to be dependency-related.

**Comment by jszakmeister** [comment]
Falling back to 6bc8c7be3a808f66d2c47bfe463a1346490da7f4 shows that Neovim works correctly again, so I'm attempting to bisect from there.

**Comment by telemachus** [comment]
I apologize if this is silly ignorance on my part, but I don't quite follow what the relevant difference is between "the full release build" and Homebrew. Does the full release build *include* the dependencies that Homebrew fetches separately? (In any case, thanks for your help. I see now that you're bisecting, so you should feel free to ignore this side question.)

**Comment by jszakmeister** [comment]
> I don't quite follow what the relevant difference is between "the full release build" and Homebrew.

Homebrew does a release build with debug info by default.  AFAIK, there's no real difference outside the fact that debug symbols are emitted by default.

It looks like the upgrade to libuv 1.3.0 busted us on OSX.

**Comment by jszakmeister** [comment]
Dropping libuv back to v1.2.0 seems to make things work again for me.

**Comment by telemachus** [comment]
Yes, that works for me as well. Good temporary fix. Thanks for your help.

**Comment by jwhitley** [comment]
Confirmed that reverting libuv to 1.2.0 fixes this issue on a OS X 10.10.2 build.

**Comment by Pyrohh** [comment]
How about 1.2.1? It'd be great if the issue was introduced between that and 1.2.0.

**Comment by jszakmeister** [comment]
1.2.1 gives us the drawing issues.

**Comment by jszakmeister** [comment]
It looks like commit libuv/libuv@393c1c59a27591d705648919b2d7fb921cba37bc is what broke it for us.  I'm not sure if it's us or them that has the problem though.  It could be our expectations are wrong in some way.

**Comment by Pyrohh** [comment]
Shouldn't you also revert homebrew?

**Comment by jszakmeister** [comment]
I'm getting to it. :-)

**Comment by Pyrohh** [comment]
Heh sorry, I probably should have waited more than 10 seconds to reply.

**Comment by jszakmeister** [comment]
No worries.  It was a good reminder. :-)

**Comment by jonthn** [comment]
I've just tested on OSX Yosemite 10.10.2 with libuv 1.4.0  and the neovim sources of today and the problem seems gone.

**Comment by Pyrohh** [comment]
@jonthn do the tests pass as well?

**Comment by jonthn** [comment]
@Pyrohh On my system, ```make test```and ```make unittest``` report no errors.
