### ISSUE TITLE
Ctrl + / not working in kitty terminal

### ISSUE THREAD

**Issue by joesitton** [neovim/neovim#19154]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

No, vim 9.0

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

Both manual build and pacman

### How to reproduce the issue
```
nvim --clean
:map <C-_> :lua print("hi")<CR>
press Ctrl+/
```

### Expected behavior

Should run the assigned mapping

### Actual behavior

Basically ignores the Ctrl input and starts a search pattern

**Comment by joesitton** [comment]
FWIW, I have tried Alacritty and it doesn't have this issue. Reported to the kitty repo and he said it's not a kitty problem and to report here.

**Comment by justinmk** [comment]
Try Nvim 0.7. and read `:help tui-modifyOtherKeys`. And search existing issues. Not going to troubleshoot every random terminal setup.

**Comment by joesitton** [comment]
Works fine in 0.7. Does not work in 0.7.2+.

So then what do you suspect is the actual issue?

**Comment by joesitton** [comment]
> Press `<C-v>` in insert mode and then press Ctrl + /. What does it print? For me it shows `<C-/>`, not `<C-_>`.

Welp, there we go...

Changing my mapping from `<C-_>` to `<C-/>` works (and actually makes sense with these recent code updates)

Thanks @gpanders
