### ISSUE TITLE
Extract insert behaviour out of completeopt and wildmode into a seperate config

### ISSUE THREAD

**Issue by venthur** [neovim/neovim#19162]
### Feature already in Vim?

No, probably won't :/

### Feature description

Hi,

I noticed that in order to get **consistent** behavior for the various completions (insert- and command-completion), I have to configure two different options: `completeopt` and `wildmode`.

Let's say I want my completion, so that it first completes to the next longest match, and then to the next full match. I'd have to set something like:

```vim
set wildmode=longest:full,full
set completeopt=longest,...  "+some other options
```
Also I noticed that `completeopt` has different things crammed onto the same option, it has the options for **insertion** (i.e. `longest`) next to **visualization** (`menu`, `preview`, ...). `wildmode` looks better as here are only the insert-options and the visualization part is done in `wildoptions`.

So my question is, is there a reason the insert-options are distributed over several configs, would it make sense to replace the insert-configs for `wildmode` and `completeopt` into a common one that effects the insert- and command-completion?

**Comment by justinmk** [comment]
For historical reasons the options are often nonsensical. The workaround is `:help`. We try to think about precedent and ergonomics for _new_ options, but rearranging old options into alternate new options is out of scope, and will also bloat the documentation and community discussions.
