### ISSUE TITLE
Broken Keypad Enter

### ISSUE THREAD

**Issue by isopropyletherperoxide** [neovim/neovim#19174]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no, vim-9.0.0000-1

### Operating system/version

Arch Linux x86-64

### Terminal name/version

kitty 0.25.2 

### $TERM environment variable

xterm-kitty

### Installation

pacman

### How to reproduce the issue

Press keypad (numpad) enter in normal or insert mode with numlock off.

### Expected behavior

Enter keystroke

### Actual behavior

An  (æ) character being printed

**Comment by zeertzjq** [comment]
Oh this looks more serious.
