### ISSUE TITLE
" mark jumps to last buffer ("E92: Buffer 0 not found")

### ISSUE THREAD

**Issue by gpanders** [neovim/neovim#19173]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+528-g3b1423bfa

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

Source

### How to reproduce the issue

Start nvim with `nvim --clean`.

Edit a new file `foo` and put in some contents:

```
:e foo
iHello<CR>world<Esc>
:w
```

Without closing nvim, edit a second file `bar` and put in some contents:

```
:e bar
iGoodbye<Esc>
:w
```

Close `nvim`, then reopen `bar`:

```
nvim --clean bar
```

Now edit `foo` again and use `'"` to move your cursor to the last known position:

```
:e foo
'"
```

### Expected behavior

The cursor should move to the end of the second line, which is the last cursor position in that buffer.

### Actual behavior

The buffer changes back to `bar`.

Bisected to 565f72b9689e0c440ff72c712a090224aaf7631b.

Another (simpler) way to replicate this is to simply open any file and press `'"` in normal mode. The cursor should move to the last position in that file, but instead it shows an error: `E92: Buffer 0 not found`.

I discovered this because it breaks the common pattern of using an autocommand to automatically restore the cursor position when opening a buffer as documented in `:h restore-cursor`.

**Comment by gpanders** [comment]
@muniter

**Comment by zeertzjq** [comment]
Isn't `fnum` always zero for a mark from shada?

**Comment by muniter** [comment]
> Isn't `fnum` always zero for a mark from shada?

It is when loaded, but ideally it should go through `fname2fnum` before being used.

**Comment by muniter** [comment]
Or maybe the issue is in:

https://github.com/neovim/neovim/blob/3b1423bfa7adc5381af641a6e66fa2ca385ecab4/src/nvim/mark.c#L421

We should set the mark fnum to the buffer its already being retrieved from.

**Comment by wookayin** [comment]
Starting from a recent nightly, `line("'\"")` raises `E19: Mark has invalid line number` error and I believe this probably shares the same root cause. Just adding a comment for future/reference.

**Comment by fdelacruz** [comment]
Hi, i would like to add this only happens (for me) in OSX (catalina), Ubuntu 20.04 is fine.

**Comment by ratheesh** [comment]
@fdelacruz, I observe this issue on `Ubuntu 22.04`

**Comment by fdelacruz** [comment]
I'm sorry, yeah, I meant to say `Ubuntu 22.04`. Still good for me.
This is on a raspberry-pi though.
Don't think that makes any difference..
