### ISSUE TITLE
Checkhealth recommends me to break my configs

### ISSUE THREAD

**Issue by Tony-Sol** [neovim/neovim#19176]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

yes, 8.2.4113

### Operating system/version

macOS 12.4

### Terminal name/version

Terminal.app 2.12.7

### $TERM environment variable

screen-256color

### Installation

homebrew

### How to reproduce the issue

All in default macos Terminal.app

Setup tmux configs following `:checkhealth` recommendations, like:
```tmux
set-option -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB' # 'cause xterm-256color is $TERM outside of tmux
```

Setup nvim `termguicolors` as true

Reload tmux and nvim

### Expected behavior

No warnings while `:checkhealth` for Terminal.app($TERM == xterm-256color) + tmux ($TERM screen-256color) runtime environment

### Actual behavior

There are either warning with actual colors or nothing warn but broken color support
<img width="1471" alt="Снимок экрана 2022-06-30 в 21 12 00" src="https://user-images.githubusercontent.com/33671815/176752468-951e6a8c-c19f-4868-a358-4e7a06bcf96a.png">
<img width="1680" alt="Снимок экрана 2022-06-30 в 21 14 10" src="https://user-images.githubusercontent.com/33671815/176752886-50dee255-3000-4b7a-b171-17da42f1dc7d.png">

**Comment by justinmk** [comment]
checkhealth is just giving a best guess. Please send a PR to improve it.
