### ISSUE TITLE
LSP: there should be an option to disable quickfix list open (copen) in LSP handlers

### ISSUE THREAD

**Issue by daliusd** [neovim/neovim#19182]
### Feature description

I see `runtime/lua/vim/lsp/handlers.lua` open quickfix list window quite often (executes `botright copen`). It would be cool if I could disable quickfix list open command as I usually don't look at quickfix list window.

**Comment by justinmk** [comment]
What actions are you taking that result in the quickfix window being opened? If it's `vim.lsp.buf.references`, it sure seems reasonable for quickfix to open, or just add `:cclose` to the mapping/command that triggered `vim.lsp.buf.references`.

The general answer is to override the handler. `vim.lsp.with()` might help there. See also https://github.com/neovim/neovim/pull/17339

**Comment by daliusd** [comment]
I have tried to add `:cclose` but it is not working. I assume it is not working because `references` is async function and my close is called to early:

```
  local function refs()
    vim.lsp.buf.references()
    vim.api.nvim_command('cclose')
  end

  vim.keymap.set('n', '<leader>af', refs, bufopts)
```

I guess I am left with "overriding the handler" option which I will investigate later.

**Comment by justinmk** [comment]
Can setup a `++once` handler to close the quickfix:

    autocmd FileType qf ++once call nvim_input(':cclose<cr>')

The nvim_input hackery could be avoided  if it worked with WinNew or WinEnter... sigh.

**Comment by daliusd** [comment]
Thanks. I will warm up a little bit and will look if can contribute something meaningful. I just switched to neovim LSP from Ale 😄

**Comment by daliusd** [comment]
@justinmk feel free to review my PR https://github.com/neovim/neovim/pull/19213 . I have tried auto-closing quickfix window but this is not good option as it is blinking and is really annoying.
