### ISSUE TITLE
cmdheight=0:  whichkey floating window opened whilst in commandline don't redraw

### ISSUE THREAD

**Issue by akinsho** [neovim/neovim#19184]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+1988-g8f5bcfb0e

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.4

### Terminal name/version

Kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

Apologies, but I don't know how to easily recreate the sequence of events that leads to this bug without using the [whichkey.nvim](https://github.com/folke/which-key.nvim) plugin, but I thought it was better to report it than leave it, as someone might recognize what might be happening better than I do.

https://user-images.githubusercontent.com/22454918/176856986-f2874d72-bdef-4413-9eab-954bb333c733.mov

As the video above shows, if a user uses a plugin like which key that tries to open a sequence of floating window whilst using something I guess like `getchar` the floating windows do not properly get cleared when the next one is triggered.

Reproduction steps:
1. Install whichkey.nvim
2. Add a nested mapping e.g. `<leader>fg` where `g` triggers some action
3. Type `<leader>f` which will open the first floating window
4. Type `g` to trigger the next window, notice the first is not cleared
5. Press `<esc>` which should clear the second window. Note that the remnant of the first window remains

### Expected behavior

Each subsequent window opened should clear the screen of the one that was drawn before it. No half drawn floating windows should appear.

### Actual behavior

As the video shows parts of the window remain visible

**Comment by Shougo** [comment]
Please upload the minimal init.vim.

**Comment by akinsho** [comment]
@Shougo I will try and get a minimal reproduction and post it here

**Comment by Shougo** [comment]
I have created more simple version.

```vim
set rtp+=~/src/which-key.nvim

nnoremap <Leader>aa   <Cmd>echo "hoge"<CR>
nnoremap <Leader>ba   <Cmd>echo "hoge"<CR>
nnoremap <Leader>ca   <Cmd>echo "hoge"<CR>
nnoremap <Leader>da   <Cmd>echo "hoge"<CR>
nnoremap <Leader>ea   <Cmd>echo "hoge"<CR>
nnoremap <Leader>fg   <Cmd>echo "hoge"<CR>

set cmdheight=0
set laststatus=0
```

I will fix it later.

**Comment by akinsho** [comment]
@Shougo that fixes the issue for me
