### ISSUE TITLE
Use locals.scm query of tree sitter parsers

### ISSUE THREAD

**Issue by Kavantix** [neovim/neovim#19181]
### Feature already in Vim?

No

### Feature description

Currently only the `highlights.scm` is used to determine highlighting of a file. Tree-sitter also has a highlight command and that will also use the `locals.scm` queries giving much better syntax highlighting with parsers that support it.

**Comment by clason** [comment]
Please open this issue at `nvim-treesitter`, which handles setting up treesitter-based highlighting right now.

You should also add some more details and examples, since I don't see how the `locals.scm` (that is already used by nvim-treesitter) can improve highlighting in a way that better `highlights.scm` can't.

**Comment by Kavantix** [comment]
@clason I’ll add some examples later today.
Nvim tree sitter uses locals only for other features not highlighting since highlighting is implemented in neovim itself if I understand correctly.

**Comment by clason** [comment]
Nvim-treesitter indeed doesn't use locals for highlighting since it doesn't need to. The query handling (e.g., combining different `highlights.scm`) is done by the plugin, not by Neovim core (hence why adding `locals.scm` into the mix is relevant).

**Comment by Kavantix** [comment]
@clason Sorry if I simply am misreading the code but looking at this line:
https://github.com/nvim-treesitter/nvim-treesitter/blob/1ed2a3cf95150c27c99710424b839a606f1947bb/lua/nvim-treesitter/highlight.lua#L137
Then it seems that the plugin doesnt handle anything with highlighting, it simply enables it.

For the locals extra support would need to be added, tree-sitter has a separate piece of rust code that implements the highlighting which uses the locals in addition to the highlights.

**Examples**

With locals:

<img width="229" alt="image" src="https://user-images.githubusercontent.com/6243755/176882094-ac64165f-8855-432a-b0ae-8151a9532818.png">

Without locals:

<img width="228" alt="image" src="https://user-images.githubusercontent.com/6243755/176882215-1765eb4c-8cee-4cad-814d-ce46683d6165.png">

**Comment by clason** [comment]
That is the missing information here: can you link to some documentation on how this is done? How would this look on the _code_ side?

**Comment by Kavantix** [comment]
[Here](https://github.com/tree-sitter/tree-sitter/blob/01df16ca9faa1635909ebea242deac200624d9ee/highlight/src/lib.rs#L734-L808) is the implementation of how the tree-sitter cli highlight command handles locals

**Comment by clason** [comment]
Does the _library_ support this as well?

Also, how does the CLI know that it should use local information? What happens if there are locals that are _not_ useful for highlighting?

**Comment by Kavantix** [comment]
And the docs of tree sitter highlighting [here](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables)

**Comment by clason** [comment]
Hmm, looking at the docs, this involves modifying queries and highlight groups, which are only(!) managed by nvim-treesitter.

I would therefore still ask you to open this issue (with the additional information from your comments) on `nvim-treesitter` for discussion. If (as is likely) modifications of `vim.treesitter` API are required, a more focused and detailed issue (or PR) can be opened based on that.
