### ISSUE TITLE
cmdheight=0: show recording indicator for macros

### ISSUE THREAD

**Issue by jdsee** [neovim/neovim#19193]
### Feature description

With the new _cmdheight=0_ feature (#1004) the `recording @*` indicator for macros is not visible anymore.
This makes recording macros less intuitive and possibly leads to confusion when _q_ is hit by accident.

I think a good solution would be to expand the command line as long as the macro is being recorded and close it again afterwards.

**Comment by jdsee** [comment]
Thanks for the tip with `reg_recording()`. I considered that solution but thought that it would make sense to solve it without relying on statusbar customization.

To be honest i can't follow your proposal entirely, so sorry if the following is redundant.

Personally i think it would be nice if the cmdline pops up for things like the recording indicator. I had another confusing situation when using `qa` to show the ascii code and it wasn't shown. Maybe i missed something in the other discussions, but i'm not sure how to work around situations like these without handling all the edge cases in my config.

**Comment by Shougo** [comment]
> I think a good solution would be to expand the command line as long as the macro is being recorded and close it again afterwards.

It is complex.  Because neovim needs to save the state and restore it later.
I think `ext_messages` should support the behavior is better.

> with this option , we can remove the !ui_has_messages() check in recording_mode. Then users decide whether to set shortmess=q.

It is possible.  But it does not fix the problem...

> This makes recording macros less intuitive and possibly leads to confusion when q is hit by accident.

**Comment by Shougo** [comment]
> I think a good solution would be to expand the command line as long as the macro is being recorded and close it again afterwards.

I have tested the implementation.  Change `cmdheight` is easy.   But to restore is very very hard.
The PR is wellcome if you can fix.

**Comment by Shougo** [comment]
Please test https://github.com/neovim/neovim/pull/19185.

**Comment by jdsee** [comment]
> Please test #19185.

This works perfect. Thanks a lot for the quick fix!

**Comment by jdsee** [comment]
> I have tested the implementation. Change `cmdheight` is easy. But to restore is very very hard. The PR is wellcome if you can fix.

I would love to help but i'm definitively not experienced enough yet. Hope i can help with easier stuff soon.

**Comment by zeertzjq** [comment]
Reverted in #20188

**Comment by Shougo** [comment]
Hi.  I think it is better.

```vim
autocmd RecordingEnter * set cmdheight=1
autocmd RecordingLeave * set cmdheight=0
```

But if I test the script, recording messages is not displayed sometimes.  I think it is bug.

Please see the screenshots.

![スクリーンショット_2022-10-14_16-37-23](https://user-images.githubusercontent.com/41495/195789921-cb5f5211-a7d4-4966-9e9f-3f624f5187b2.png)

![スクリーンショット_2022-10-14_16-37-43](https://user-images.githubusercontent.com/41495/195789942-8e02eb3a-4fca-494b-8e38-f82bcdc787ce.png)

**Comment by MaMrEzO** [comment]
I take this, till a standard workaround comes up.

https://www.reddit.com/r/neovim/comments/xy0tu1/comment/irfegvd/?utm_source=reddit&utm_medium=web2x&context=3

and it just works.

![Screenshot_20231020_210631](https://github.com/neovim/neovim/assets/1070230/d75c436c-7b9d-4c04-80b2-200c5ff65598)

**Comment by adriel-tech** [comment]
I used Shougo's above suggestion and I also see the bug that causes 'recording @' to fail to appear. For me
It never shows up a second time, but I found a nonsensical work around that allows 'recoding @' to always appear.

```
autocmd("RecordingEnter", {
  callback = function()
    vim.opt.cmdheight = 1
    -- neovim 9:
    -- The below vim.notify allows the 'recording @' message to show up if used more than once. if using cmdheight=0
    vim.notify("this does nothing", vim.log.levels.OFF, {
    })
  end
})
```

**Comment by trevarj** [comment]
> change SHM_RECORDING (shortmess=q) so that it actually shows nothing. The current behavior of shortmess=q is pointless. 

Can this be done? It's kinda annoying when you have a statusbar using `reg_recording()` and want to use cmdheight=1.

```diff
 static void recording_mode(int attr)
 {
-  msg_puts_attr(_("recording"), attr);
   if (shortmess(SHM_RECORDING)) {
     return;
   }

-  char s[4];
-  snprintf(s, ARRAY_SIZE(s), " @%c", reg_recording);
+  char s[13];
+  snprintf(s, ARRAY_SIZE(s), "recording @%c", reg_recording);
   msg_puts_attr(s, attr);
 }
```

**Comment by justinmk** [comment]
# Resolution

See https://github.com/neovim/neovim/issues/19193#issuecomment-1172473714
