### ISSUE TITLE
`set ambiwidth=double` will cause display error

### ISSUE THREAD

**Issue by Alaskra** [neovim/neovim#19191]
### Neovim version (nvim -v)

NVIM v0.7.0 Build type: Release

### Vim (not Nvim) behaves the same?

no, vim8.2

### Operating system/version

manjaro

### Terminal name/version

terminator

### $TERM environment variable

xterm-256color

### Installation

AUR

### How to reproduce the issue

1. nvim --clean
2. paste this line: `因此如果您在网页版的坚果云发现同一个目录下有两个名称为“Nutstore”和“nutstore”（小写的“n”）的文件/文件夹，在Windows/Mac系统上其中一个文件/文件夹后面会加上“大小写冲突”的字样`
3. :set ambiwidth=double
4. mouse drag to change terminal window width, you will see the symbol `>` which break a line misdisplay.
![Peek 2022-07-01 21-52](https://user-images.githubusercontent.com/49367127/176908278-e32c7052-7759-40cc-8698-5f79ddf8bd44.gif)

### Expected behavior

there won't any character in the right of the symbol `>`.

### Actual behavior

there are some character in the right of the symbol `>`.

**Comment by zeertzjq** [comment]
Related: #15898

**Comment by zeertzjq** [comment]
This small change may "fix" the problem:
```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index e2289eb9c..78281470d 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -788,6 +788,7 @@ static void cursor_goto(UI *ui, int row, int col)
 {
   TUIData *data = ui->data;
   UGrid *grid = &data->grid;
+  goto safe_move;
   if (row == grid->row && col == grid->col) {
     return;
   }
```

But this "fix" just disables a bunch of performance improvements.

**Comment by zeertzjq** [comment]
A less drastic solution:
```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index e2289eb9c..2490104b6 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -748,6 +748,9 @@ static void print_cell(UI *ui, UCell *ptr)
   update_attrs(ui, ptr->attr);
   out(ui, ptr->data, strlen(ptr->data));
   grid->col++;
+  if (utf_ambiguous_width(utf_ptr2char(ptr->data))) {
+    grid->row = -1;
+  }
   if (data->immediate_wrap_after_last_column) {
     // Printing at the right margin immediately advances the cursor.
     final_column_wrap(ui);
@@ -1439,6 +1442,9 @@ static void tui_raw_line(UI *ui, Integer g, Integer linerow, Integer startcol, I
     grid->cells[linerow][c].attr = attrs[c - startcol];
   }
   UGRID_FOREACH_CELL(grid, (int)linerow, (int)startcol, (int)endcol, {
+    if (cell->data[0] == NUL && grid->row == -1) {
+      continue;
+    }
     cursor_goto(ui, (int)linerow, curcol);
     print_cell(ui, cell);
   });
```
