### ISSUE TITLE
have trouble copying from Neovim to Windows clipboard using win32yank.exe

### ISSUE THREAD

**Issue by garyzhang2002** [neovim/neovim#19204]
### Neovim version (nvim -v)

v0.7.0

### Vim (not Nvim) behaves the same?

no, vim 8.2.3995

### Operating system/version

Ubuntu 22.04 LTS on Windows 11 (Kernel: 5.10.102.1-microsoft-standard-WSL2)

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

I followed [the instructions](https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl) and installed `win32yank.exe` through
``` shell
curl -sLo/tmp/win32yank.zip https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
unzip -p /tmp/win32yank.zip win32yank.exe > /tmp/win32yank.exe
chmod +x /tmp/win32yank.exe
sudo mv /tmp/win32yank.exe /usr/local/bin/
```
And then I added the following lines in my configuration file
``` lua
vim.cmd [[
    let g:clipboard = {
      \   'name': 'win32yank-wsl',
      \   'copy': {
      \      '+': 'win32yank.exe -i --crlf',
      \      '*': 'win32yank.exe -i --crlf',
      \    },
      \   'paste': {
      \      '+': 'win32yank.exe -o --lf',
      \      '*': 'win32yank.exe -o --lf',
      \   },
      \   'cache_enabled': 0,
      \ }
]]
```
I also tried to run `nvim --clean` then did this clipboard setting via the terminal inside Neovim.
Either way I succeeded in making
```
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank-wsl
```
shown after running `checkhealth`.
I've also tested this on Debian, where Neovim v0.7.0 was installed from the repo release, in my WSL and the results were the same.

### Expected behavior

Neovim copy to and paste from Windows succesfully.

### Actual behavior

I tried to do `"+y` stuff and the outcomes are:
+ If I set `cache_enabled` to 0, then the copy is successful and I can see the content outside WSL in my Win11's clipboard but only after a 10-second or so stuck in Neovim, where no operations can be done, immediately after I did the copy, say `"+yy`.
+ If I set `cache_enabled` to 1, then the copy is perfectly done on occasion, but often the content I copied only show itself in my Win11's clipboard after 10 seconds or so, but without stuck in Neovim. There are also situations where a error `clipboard: error invoking win32yank.exe:` pops out about half a second after the copy.

In either case pasting from Windows clipboard both encounter with a stuck and then the content is correctly pasted.

**Comment by justinmk** [comment]
related https://github.com/neovim/neovim/issues/7021

**Comment by garyzhang2002** [comment]
> related #7021

Is there any workaround for this issue? 😢😭

**Comment by matveyt** [comment]
@garyzhang2002 As you are under W11, WSLg could probably be up and running. Just check for existence of X11 and/or Wayland server:

```
$ echo $DISPLAY $WAYLAND_DISPLAY
:0 wayland-0
```

If it is then you can follow "normal *nix-like" installation instructions with `xclip`, `xsel`, `wl-clipboard` etc. Or you can even build my [plugin](https://github.com/matveyt/neoclip) from source and get access to clipboard by shared library, not spawning any external process.

**Comment by justinmk** [comment]
> Is there any workaround for this issue? 😢😭

@garyzhang2002 can you try `clip.exe` ? see https://github.com/neovim/neovim/issues/6227#issuecomment-501111315

**Comment by garyzhang2002** [comment]
> @garyzhang2002 As you are under W11, WSLg could probably be up and running. Just check for existence of X11 and/or Wayland server:
> 
> ```
> $ echo $DISPLAY $WAYLAND_DISPLAY
> :0 wayland-0
> ```
> 
> If it is then you can follow "normal *nix-like" installation instructions with `xclip`, `xsel`, `wl-clipboard` etc. Or you can even build my [plugin](https://github.com/matveyt/neoclip) from source and get access to clipboard by shared library, not spawning any external process.

I suppose Wayland server exists. But it's weird that these `xclip` or `wl-clipboard` stuff only works inside WSL, by which I mean I installed gedit and it seemed that copying from Neovim to gedit worked fine but not reversely. And there wasn't anything showing up on my Win11 clipboard. Then I tried building your clipboard provider from source and it didn't work either. But thanks anyway.

**Comment by garyzhang2002** [comment]
> > Is there any workaround for this issue? 😢😭
> 
> @garyzhang2002 can you try `clip.exe` ? see [#6227 (comment)](https://github.com/neovim/neovim/issues/6227#issuecomment-501111315)

I'm currently using `clip.exe` but the problem is `"+p` would not work, but it seems that in INSERT mode I can simply use `Ctrl+v` to paste from Win11 in Windows Terminal. So perhaps weird as it is, this should be the best way for now to copy and paste in my case.

**Comment by justinmk** [comment]
> but it seems that in INSERT mode I can simply use `Ctrl+v` to paste from Win11 in Windows Terminal.

That should work in any mode, Nvim detects the paste (assuming that Windows Terminal supports "bracketed paste") and handles it correctly.

**Comment by garyzhang2002** [comment]
> 

Thanks for telling me that. You are absolutely right.

**Comment by garyzhang2002** [comment]
> > but it seems that in INSERT mode I can simply use `Ctrl+v` to paste from Win11 in Windows Terminal.
> 
> That should work in any mode, Nvim detects the paste (assuming that Windows Terminal supports "bracketed paste") and handles it correctly.

Thanks for telling me that. You are absolutely right.

**Comment by numToStr** [comment]
I am also facing this clipboard issue in Win11 + WSL2 and workaround mentioned here (https://github.com/neovim/neovim/issues/6227#issuecomment-501111315) seems to fix the issue. Here is the Lua version of the workaround:

```lua
if vim.fn.has('wsl') == 1 then
    vim.api.nvim_create_autocmd('TextYankPost', {
        group = vim.api.nvim_create_augroup('Yank', { clear = true }),
        callback = function()
            vim.api.nvim_command([[
                call system('clip.exe', @")
            ]])
        end,
    })
end
```

(I am not sure how to write `@"` in lua, thus `nvim_command`)

**Comment by garyzhang2002** [comment]
> (I am not sure how to write `@"` in lua, thus `nvim_command`)

I suppose it should be `vim.fn.getreg('"')`.

I actually added following lines in my configuration and now copying seems to be OK.
``` lua
if vim.fn.has("wsl") then
    vim.g.clipboard = {
        name = "clip.exe (Copy Only)",
        copy = {
            ["+"] = "clip.exe",
            ["*"] = "clip.exe"
        },
        paste = {
            ["+"] = "clip.exe",
            ["*"] = "clip.exe"
        },
        cache_enabled = true
    }
end
```

**Comment by matveyt** [comment]
Actually, the roots of all these difficulties seem unaccountable to me. In W11/WSL/Ubuntu simply doing

```
$ sudo apt install xsel
```

and leaving `g:clipboard` empty should work without any problem. How comes it doesn't?

**Comment by garyzhang2002** [comment]
I don't have a clue. I'm not sure if @numToStr had tried simply installing `xsel` or `xclip` stuff before. I tried and it somehow didn't work. 🤔

**Comment by numToStr** [comment]
In fact, I have `xclip` installed but I highly doubt that will have any effect outside of the WSL distro (It works fine inside WSL).

```markdown
## Clipboard (optional)
  - OK: Clipboard tool found: xclip
```

**Comment by JavaHello** [comment]
```lua
vim.opt.clipboard = "unnamedplus"

if vim.fn.has("wsl") then
  vim.g.clipboard = {
    name = "win32yank-wsl",
    copy = {
      ["+"] = "win32yank.exe -i --crlf",
      ["*"] = "win32yank.exe -i --crlf",
    },
    paste = {
      ["+"] = "win32yank.exe -o --lf",
      ["*"] = "win32yank.exe -o --lf",
    },
    cache_enabled = 0,
  }
end
```
## Neovim version (nvim -v)
```txt
NVIM v0.9.0-dev
```
This configuration works

**Comment by nick4eva** [comment]
This comment https://github.com/neovim/neovim/issues/19204#issuecomment-1327498068 started working for me after uninstalling xclip from WSL (like `sudo apt remove xclip`).

**Comment by justinmk** [comment]
:help clipboard-wsl

**Comment by NGPONG** [comment]
Put win32yank.exe into c/windows/system32 works for me.
