### ISSUE TITLE
nvim crash when sub

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#19201]
### Neovim version (nvim -v)

v0.8.0-dev+406-g502f03fc0

### Vim (not Nvim) behaves the same?

dont know

### Operating system/version

windows 10

### Terminal name/version

windows cmd

### $TERM environment variable

x

### Installation

x

### How to reproduce the issue

1. nvim -u NONE test.txt
2. `:%s/^\<space>\<space>/\<space>\<space><space>`
test.txt
```  
LeaderF = {
    build = "./install.sh",
    hook_add = "let g:Lf_WindowPosition = 'popup'\nlet g:Lf_GtagsAutoGenerate = 1\nlet g:Lf_Gtagslabel = 'native-pygments'\nlet g:Lf_ShortcutB = ''\n\nnnoremap <space>l :<c-u>LeaderfLine<cr>\n",
    lazy = 0,
    merged = 0,
    name = "LeaderF",
    normalized_name = "LeaderF",
    path = "F:/nvim-brew-env/.cache/dein/repos/gitee.com/zgpio/LeaderF",
    repo = "https://gitee.com/zgpio/LeaderF",
    rtp = "F:/nvim-brew-env/.cache/dein/repos/gitee.com/zgpio/LeaderF",
    sourced = true,
    type = "git"
  }
```

### Expected behavior

do not crash

### Actual behavior

crash

**Comment by zeertzjq** [comment]
This has likely already been fixed. Can you test a newer version?
