### ISSUE TITLE
Unable to build on openSUSE 13.2 x64

### ISSUE THREAD

**Issue by whitebyte** [neovim/neovim#1920]
Subj. All prerequisites listed here https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites are installed. "make" spits the following error:

**/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -luv**

    /usr/bin/cc -O2 -fPIC -I/home/anton/neovim/neovim/.deps/usr/include/luajit-2.0 -c nvim/loop.c -o   nvim/loop.o -I/home/anton/neovim/neovim/.deps/usr/include
    /usr/bin/cc -shared -o nvim/loop.so -L/home/anton/neovim/neovim/.deps/usr/lib nvim/loop.o -L/home/anton/neovim/neovim/.deps/usr/lib -Wl,-rpath,/home/anton/neovim/neovim/.deps/usr/lib: -luv -lpthread -lrt -ldl
    /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -luv
    collect2: error: ld returned 1 exit status

**Comment by jszakmeister** [comment]
What is in `/home/anton/neovim/neovim/.deps/usr/lib`?

**Comment by whitebyte** [comment]
libluajit-5.1.a
libmsgpack.a
libtermkey.a
libtermkey.la
libtermkey.so -> libtermkey.so.1.11.0
libtermkey.so.1 -> libtermkey.so.1.11.0
libtermkey.so.1.11.0
libtickit.a
libtickit.la
libtickit.so -> libtickit.so.0.0.0
libtickit.so.0 -> libtickit.so.0.0.0
libtickit.so.0.0.0
libunibilium.a
libunibilium.la
libunibilium.so -> libunibilium.so.0.2.0
libunibilium.so.0 -> libunibilium.so.0.2.0
libunibilium.so.0.2.0
lua/
luarocks/
pkgconfig/

**Comment by jszakmeister** [comment]
Did libuv fail to build?  In should be listed in there. :-(  Or is it somewhere else?  It might be a good idea to do a `find .deps -name libuv.a` and see what turns up.

**Comment by jszakmeister** [comment]
...libuv is a dependency of the lua client, so it should've built libuv before building the client.  Something definitely seems a bit off here.

**Comment by equalsraf** [comment]
Can we get the build logs from .deps/CMakeFiles/*.log and build/CMakefiles/*.log? They should have some more detailed info. The one in .deps should tell us if libuv was built or not and why. And the one in build/, because the build should not even have started if libuv could not be found.

**Comment by whitebyte** [comment]
@jszakmeister, find .deps -name libuv.a gives this:
```
.deps/usr/lib64/libuv.a
.deps/build/src/libuv-build/.libs/libuv.a
```
@equalsraf, deps log is here: https://gist.github.com/whitebyte/63bdb9ac3229c8cfa008
Build directory is empty.

**Comment by jszakmeister** [comment]
> `.deps/usr/lib64/libuv.a`

That's the problem.  We're not expecting it to be in a lib64 directory.  I guess we're going to have to pass `--libdir` to the configure invocation.

**Comment by jszakmeister** [comment]
@whitebyte Can you try the following patch:

```diff
diff --git a/third-party/CMakeLists.txt b/third-party/CMakeLists.txt
index b2160a2..2f4cf85 100644
--- a/third-party/CMakeLists.txt
+++ b/third-party/CMakeLists.txt
@@ -164,7 +164,8 @@ if(USE_BUNDLED_LIBUV)
       -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/DownloadAndExtractFile.cmake
     CONFIGURE_COMMAND sh ${DEPS_BUILD_DIR}/src/libuv/autogen.sh &&
       ${DEPS_BUILD_DIR}/src/libuv/configure --with-pic --disable-shared
-        --prefix=${DEPS_INSTALL_DIR} CC=${DEPS_C_COMPILER}
+        --prefix=${DEPS_INSTALL_DIR} --libdir=${DEPS_INSTALL_DIR}/lib
+        CC=${DEPS_C_COMPILER}
     INSTALL_COMMAND ${MAKE_PRG} install)
   list(APPEND THIRD_PARTY_DEPS libuv)
 endif()
```

**Comment by whitebyte** [comment]
@jszakmeister , nvim is succesfully built and installed with you patch. Thank you very much!
