### ISSUE TITLE
terminal rendering on OS X is broken

### ISSUE THREAD

**Issue by jwhitley** [neovim/neovim#1921]
**Repro steps**

1.  Build using the homebrew formula, neovim commit 6196cab139b52cd412c198f38626ec7f7688995e.
2.  Run neovim as `nvim -u NONE`

**Actual results**

The neovim splash isn't visible, and there's just two broken groups of `~` on the left side.  No status bar is evident.  If I load my normal .vimrc, I get most but not all of the splash, and vim-airline mostly seems to get a status bar up.  If I edit a file, not all of the text is being displayed correctly or at once for a given page's content.  Apologies for not having a more precise report, but things are really busted right now; `nvim` is outright unusable on OS X.

**Expected results**

Terminal rendering works as normal.

**Comment by jwhitley** [comment]
FWIW, I'm not able to repro #1916 right now (my builds always complete), but this is at least as bad.

**Comment by equalsraf** [comment]
@jwhitley could this be a duplicate of #1914?

**Comment by jwhitley** [comment]
Ack, I'm blind. This is definitely a dupe. Closing.
