### ISSUE TITLE
3rd level characters stopped working in Neo keyboard layout

### ISSUE THREAD

**Issue by mapclyps** [neovim/neovim#19219]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

no, vim 8.2.4113

### Operating system/version

macOS 12.4

### Terminal name/version

iTerm2 Build 3.14.15

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

install iTerm2
install Karabiner-Elements
install [neo2 keyboard layout](https://en.wikipedia.org/wiki/Neo_(keyboard_layout)) in osx
activate neo2 adjustments in Karabiner-Elements (to make the keyboard layout being able to use all layers)
start neovim
go into insert mode
type any 3rd level character like, e.g., closing parenthesis (Caps-lock+k on English or German hardware keyboards)

### Expected behavior

Character appears as typed

### Actual behavior

Step out of insert mode and make the current line disappear

**Comment by mapclyps** [comment]
some additions;
It worked in neovim until (including) version 0.7.
Also what is interesting is that it still works in the OSX Terminal.app with neovim version 0.7.2 or when run inside a tmux/byobu session.
Since I only updated neovim, I still think it is a neovim issue. 
For debugging, I tried to figure out what neovim received when I press, e.g. closing parenthesis. So, in insert mode I did <C-V> and then my closing parenthesis, and I got `<M-U>)` while in previous versions it was correct only `)`. Trying a few other layer 3 characters I always find `<M-U>` in front of the expected character.

**Comment by justinmk** [comment]
> install Karabiner-Elements
> install [neo2 keyboard layout](https://en.wikipedia.org/wiki/Neo_(keyboard_layout)) in osx
> activate neo2 adjustments in Karabiner-Elements (to make the keyboard layout being able to use all layers)

This is too much to reproduce. What are the bytes produced and sent to nvim?

**Comment by mapclyps** [comment]
I just know the verbatim insert, CTRL-V, When I do this in the terminal (or nvim <0.7.1) followed by, e.g., closing parenthesis I get just the `)`, If I do this in nvim 0.7.2, I get `<M-U>)`
Is there another way to figure out what was sent to nvim?

**Comment by justinmk** [comment]
Based on your followup comment it seems like karabiner is sending `ESC U )`. Nvim correctly interprets `ESC U` as `<M-u>`.

Likely what happened is that previously Nvim just ignored the `ESC U`. Now it (correctly) handles it. 

You'll have to ask karabiner why they are sending `ESC U`.

**Comment by mapclyps** [comment]
Thank you for the hints where to look for. 
I at least figured out why the karabiner-elements scripts for the neo keyboard layout are doing this: 
The caps-lock is mapped to the option key to work as a modifier. But globally in OSX the option shortcuts are still working, then also for the caps-lock key. There is a fix to prevent this, as another karabiner-elements script, which inserts the `ESC U` before the actual character.  This way, the OS does not detect normal inputs from the 3rd level layer as global command key shortcuts. 
So, deactivating this, resolved the issue for me

It is funny that in neovim this issue only showed up in plain Iterm2 but not with tmux and not in Terminal.app.

**Comment by mapclyps** [comment]
I could not live with the workaround to disable the original workaround in Karabiner-elements for the 3rd layer of the neo2 layout. Not just the system defined shortcuts are using the option key, but many websites define option key shortcuts, e.g. Jupyter lab, which then just does interesting things while I was typing normal characters.

It seems that https://github.com/neovim/neovim/pull/17771/commits/a11ff555557ada858d74d8192badb725d77fdbb0 introduced this automatic changing the input mode  to CSI u if the terminal supports it.
I haven't found a way to prevent this, so I just switch it back like it would be on an unsupported terminal like the above-mentioned Terminal.app with running 
`vim.defer_fn(function() vim.cmd('call chansend(v:stderr, "\x1b[<1u")') end, 20)` 
at startup. Inspiration for this I found in the pr just mentioned.
