### ISSUE TITLE
API/UI: how to resolve `win_viewport` lines against folded lines?

### ISSUE THREAD

**Issue by MDeiml** [neovim/neovim#19227]
### Feature description

Some UIs or at least neovide are using the `win_viewport` event to achieve smooth scrolling. It seems from https://github.com/neovim/neovim/issues/8854 that this is the intendet usage. But that approach runs into some problems for neovide that are discussed in https://github.com/neovide/neovide/issues/1334.

The main issue is, that `win_viewport` supplies position in terms of buffer lines, not displayed lines. These might be different when e.g. using folds, but for the purpose of scrolling only displayed lines are of interest. I propose adding the position in terms of displayed lines as an extra argument to the event.

(There is also a problem with `win_viewport` being emitted to often e.g. when substituting text, but I think that is a different issue)

**Comment by lewis6991** [comment]
Wouldn't a fold API allow you to solve this issue? See #19226

**Comment by lewis6991** [comment]
> Yes, but that would require to call that API after every win_viewport event, which wouldn't be to great performance wise (I would guess). Especially because it would create quite a bit of latency between pressing e.g. j and the screen updating accordingly.

In regard to performance, https://github.com/lewis6991/satellite.nvim needs to know virtual (aka displayed) line numbers, and does so by building a lookup table by calling `foldclosedend()` on every buffer line, for every buffer change. Horribly inefficient, but even so, you don't really notice this whilst using the plugin. Changing the algorithm to query folds would be at least a magnitude more efficient (probably more). So I don't think it would matter for any `win_viewport` application assuming the amount of folds is reasonable. Internally the same calculations will probably be needed anyway due to how folds are implemented, so I don't think you can avoid that cost.

> Since win_viewport will always be followed by querying folds (the information contained in the event is more or less useless without doing so), it would make much more sense to include that data in the event.

You would also need to include a full list of all the displayed line numbers, not just the top and bottom, which is why just querying the folds may be more preferable since that API has more uses.

**Comment by MDeiml** [comment]
> In regard to performance, https://github.com/lewis6991/satellite.nvim needs to know virtual (aka displayed) line numbers, and does so by building a lookup table by calling `foldclosedend()` on every buffer line, for every buffer change. Horribly inefficient, but even so, you don't really notice this whilst using the plugin

That's without the delay of RPC channels for every call. Also this probably scales linearly with file size? Still you're right, it is surely possible to get an efficient implementation, especially using the Folds API.

> You would also need to include a full list of all the displayed line numbers, not just the top and bottom, which is why just querying the folds may be more preferable since that API has more uses.

Not really, to achieve animated scrolling all that is needed is the deltas of the windows top line. Line numbers are transmitted as part of the `grid_line` event.

I'm not saying including virtual line numbers is necessary to be able to implement proper scrolling animations. I just think it's weird that `win_viewport` cannot be used (by itself) to implement scrolling animations when that was the original intent.

**Comment by lewis6991** [comment]
> That's without the delay of RPC channels for every call. Also this probably scales linearly with file size? Still you're right, it is surely possible to get an efficient implementation, especially using the Folds API.

It's only one additional call, and with "fold events" via a proposed `nvim_win_attach`, you could have this information cached beforehand.

> I'm not saying including virtual line numbers is necessary to be able to implement proper scrolling animations. I just think it's weird that win_viewport cannot be used (by itself) to implement scrolling animations when that was the original intent.

Hmm, fair enough.

**Comment by justinmk** [comment]
Is this the complete feature request here?

> to achieve animated scrolling all that is needed is the deltas of the windows top line. Line numbers are transmitted as part of the `grid_line` event.

**Comment by MDeiml** [comment]
I think there is two sensible ways to modify the event:
1. Include deltas in terms of "virtual lines" scrolled
2. Include the "virtual line number" of the top most line

1\. is more useful for animations I think., but it can easily be computed from 2. and vice versa. So the feature request would be either of those.

**Comment by MDeiml** [comment]
It seems (from looking at the source) that 1. is easier to do efficiently. We could remember the last sent `topline`, then the delta can be computed by calling `plines_m_win(wp, last_topline, topline)` (assuming `last_topline < topline`). This might not be accurate if folds changed between `last_topline` and `topline`, but that might not even be possible.

**Comment by justinmk** [comment]
@MDeiml sounds like you are pretty close to a solution. PR very welcome.

**Comment by lewis6991** [comment]
I still don't understand how you are able to render a scroll bar effectively without full knowledge of all virtual line numbers for the entire buffer. For example, how do you handle closed folds below the viewport?

**Comment by bfredl** [comment]
> Not really, to achieve animated scrolling all that is needed is the deltas of the windows top line. Line numbers are transmitted as part of the grid_line event.

Not really in a programmatic form trivially to use from UI:s. I think we should add this (the info is available during painting, we just need to transmit it when emitting lines).

**Comment by tobealive** [comment]
If it's not too much to handle, is there a way to get this promoted from the backlog? The PR is there after all and fits under the major topics flag `Ubiquity. Embed Neovim everywhere`.

**Comment by lewis6991** [comment]
Yes. Raise a PR yourself. Contributions are welcome.

**Comment by justinmk** [comment]
PR is in progress at https://github.com/neovim/neovim/pull/19270
