### ISSUE TITLE
LSP: finding references "index out of range" with mixed LF, CRLF files

### ISSUE THREAD

**Issue by general0000** [neovim/neovim#19237]
### Neovim version (nvim -v)

0.7.0  compiled by runneradmin@fv-az320-113

### Language server name/version

clangd_14.0.3

### Operating system/version

win7

### Steps to reproduce using "nvim -u minimal_init.lua"

I have gotten the reason.

**1  Error**
        When finding references,  failed with error:  
```
        Error executing vim.schedule lua callback: \nvim-win64\share\nvim\runtime/lua/vim/lsp/util.lua:1616: index out of range
stack traceback:
	[C]: in function '_str_byteindex_enc'
	...\nvim-win64\share\nvim\runtime/lua/vim/lsp/util.lua:1616: in function 'locations_to_items'
	...\nvim-win64\share\nvim\runtime/lua/vim/lsp/handlers.lua:192: in function 'handler'
	D:\backup\nvim-win64\share\nvim\runtime/lua/vim/lsp.lua:1025: in function 'cb'
	vim/_editor.lua:256: in function <vim/_editor.lua:256>
```

**2  Reason**
```lua
        **Error occurs here: util.lua **
function M._str_byteindex_enc(line, index, encoding)
  if not encoding then encoding = 'utf-16' end
  if encoding == 'utf-8' then
    if index then return index else return #line end
  elseif encoding == 'utf-16' then
    return vim.str_byteindex(line, index, true)           **##########  invalid index here ######**
  elseif encoding == 'utf-32' then
    return vim.str_byteindex(line, index)                   **##########  or invalid index here ######**
  else
    error("Invalid encoding: " .. vim.inspect(encoding))
  end
end
```

    Because some c files are identified as CRLF format, but some lines in these files end with CR CR LF (0x0d 0d 0a). So the variable 'line' passed to _str_byteindex_enc is not the exact line,  sometime is shorter.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by general0000** [comment]
I tried out the latest release (0.7.2), and unfortunately, the problem is the same.

**Comment by justinmk** [comment]
Hard to read the description but it looks like you narrowed down the issue to:

> Because some c files are identified as CRLF format, but some lines in these files end with CR CR LF (0x0d 0d 0a). So the variable 'line' passed to _str_byteindex_enc is not the exact line,  sometime is shorter.

**Comment by general0000** [comment]
Sorry. For example,   to find reference of the function 'foo'.  When encountering such a file:
line1  void bar()
line2  {^M
line3      foo();
line4  }
the line2 ends with \r\r\n ， the line number referencing foo is 3 (and column is 4), but the line processed by _str_byteindex_enc is line4.  At line 4, there is no column 4, so triggered the error  “ index out of range”。

**Comment by general0000** [comment]
[test_cr.zip](https://github.com/neovim/neovim/files/9052439/test_cr.zip)

In short, when there are mixed \r  \r\n in c files, because the parsing principle of the line number between lsp client and  server is inconsistent, the client gets the wrong row content, and if the row content is shorter, the column number will be invalid,  so vim.str_byteindex produces the error: index out of range.

I have confirmed this conclusion by adding logs.

Using the file in attachment can reproduce the problem. Finding any symbol references after line 7 will produce the problem.

**Comment by MagicRedDeer** [comment]
I am also experiencing the same issue with 

nvim 0.8.1
centos 7.9.2009
python/pyright-langserver 1.1.281

The problem goes away if I just save the file in question after using the 'black' formatter.

Therefore, this is not just a windows platform issue.

**Comment by jbarik** [comment]
I am also facing the same issue with ccls. For some symbols navigation works for some it doesn't.
![Screenshot from 2023-04-12 09-34-49](https://user-images.githubusercontent.com/22386546/231346854-c19714f9-82c0-474d-85f7-360a8f2b5090.png)

**Comment by vricop** [comment]
@jbarik I found out what's causing this. You just need to install the cssmodule_ls server, I'm myself using Mason for that. Then need to pass some specific server settings so it doesn't conflict with 'Go to definition' from the tsserver.

So this doesn't have to do with native Neovim LSP.

This is my config:

```lua
require('mason-lspconfig').setup_handlers({
  function(server_name)
    lspconfig[server_name].setup({
      on_attach = on_attach,
      capabilities = capabilities,
      settings = {
        Lua = {
          diagnostics = { globals = { 'vim' } },
        },
        -- NOTE: For some reason, stylelint isn't loading my config file with 
        -- rules for avoiding false positives when using PostCss plugins.
        css = {
          validate = true,
          lint = {
            unknownAtRules = 'ignore',
          },
        },
        cssmodules = { // <= This is what you need, don't forget to install the server
          capabilities = {
            definitionProvider = false
          }
        }
      },
    })
  end,
})
```

Source: https://github.com/antonk52/cssmodules-language-server#configuration

I hope it helps...

**Comment by schemar** [comment]
That doesn't fix the issue for `tsserver`, though. I use TypeScript and can confirm that the original issue still exists. Though, from what I can tell, I don't have mixed line feeds. Maybe my issue is not related to this issue after all 🧐

**Comment by chipsenkbeil** [comment]
As a heads up, I also ran into this error, but it was due to a bug in my plugin's implementation. I was trying to load a custom scheme in the form of `distant://1234@/path/to/file`, but the buffer was returning empty even though the LSP provided the correct line & column position. When jumping to a definition, it tried to load the file, but that yielded an empty buffer. This resulted in a call to `_str_byteindex_enc` with an empty line while still being provided a valid encoding (UTF-16) and index.

Might be good to catch a disconnect where it's clearly going to error and report a more meaningful error on top of the index issue.

**Comment by jbarik** [comment]
I debugged this issue a little more and this is what I found:

When I try to jump to the header file from a function definition in cpp file, I intercepted the results from ccls(at 
 **/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua, function location_handler**). The result from ccls contained multiple targetUri, namely:

**targetUri = "file://../../../../../../src/sl_lang_blocks/export/include/sl_lang_blocks/ControlPortBlock.hpp" 
targetUri = "file://../../../src/sl_lang_blocks/export/include/sl_lang_blocks/ControlPortBlock.hpp"
targetUri = "file://../../src/sl_lang_blocks/export/include/sl_lang_blocks/ControlPortBlock.hpp"
targetUri = "file://../../src/sl_lang_blocks/export/include/sl_lang_blocks/ControlPortBlock.hpp"
targetUri = "file:///local-ssd/jbarik/ls_eventport2/matlab/src/sl_lang_blocks/export/include/sl_lang_blocks/ControlPortBlock.hpp"**

I was expecting only one, that is the last one which contains the absolute path. Even if I consider the relative path of the hpp from the location of the cpp file, of all the targetUri, one is correct.

Later, in **function M.locations_to_items** (/usr/share/nvim/runtime/lua/vim/lsp/util.lua), some of those Uri which contain relative path(file://../../***) fail to resolve to a proper file and the code ends up sending an empty line to M._str_byteindex_enc which errors out.

**Comment by teocns** [comment]
Facing the same issue invoking `lua vim.lsp.buf.references()` with clangd running on remote index:

```
Error executing vim.schedule lua callback: ...lar/neovim/0.9.4/share/nvim/runtime/lua/vim/lsp/util.lua:1833: index out of range
stack traceback:
	[C]: in function '_str_byteindex_enc'
	...lar/neovim/0.9.4/share/nvim/runtime/lua/vim/lsp/util.lua:1833: in function 'locations_to_items'
	...nvim/lazy/telescope.nvim/lua/telescope/builtin/__lsp.lua:27: in function 'handler'
	...l/Cellar/neovim/0.9.4/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

```

Adding debug prints at `/usr/local/Cellar/neovim/0.9.4/share/nvim/runtime/lua/vim/lsp/util.lua` before the `_str_byteindex_enc` invocation produces the following before raising an error:


```
{ "  // The process should crash when going through abnormal termination, but we", 2, "utf-16" }
{ "    std::size(kNonWildcardDomainNonPortSchemes);", 18, "utf-16" }
{ "", 13, "utf-16" }
```

The issue seems to be `pos.character` being mismatched against an empty line.

## Hotfix


      local ok, col = pcall(M._str_byteindex_enc, line, pos.character, offset_encoding)
      if ok then
        table.insert(items, {
```
local ok, col = pcall(M._str_byteindex_enc, line, pos.character, offset_encoding)
if ok then
  table.insert...
```

**Comment by tamazyanarsen** [comment]
is there any news on this issue?

**Comment by hboon** [comment]
Had problem with LSP definition as well as references. Suggested fix by @teocns works for me. Thanks.

**Comment by YajJackson** [comment]
Encountered with csharp_ls, patch worked for me as well.

**Comment by ranandfigma** [comment]
Also ran into this with `rust-analyzer` on nvim `0.10.0`. The patch worked for me.

**Comment by wojciech-kulik** [comment]
Same here. I checked the exact response from LSP and it is correct:
```
{ {
    result = { {
        range = {
          ["end"] = {
            character = 12,
            line = 8
          },
          start = {
            character = 12,
            line = 8
          }
        },
        uri = "file:///Users/path/Models/MyEnumName.swift"
      }, {
        range = {
          ["end"] = {
            character = 12,
            line = 8
          },
          start = {
            character = 12,
            line = 8
          }
        },
        uri = "file:///Users/path/Models/MyEnumName.swift"
      } }
  } }
```

however, for some reason, I get this error:

```
Error executing vim.schedule lua callback: ...ar/neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/util.lua:1914: index out of range
stack traceback:
        [C]: in function '_str_byteindex_enc'
        ...ar/neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/util.lua:1914: in function 'locations_to_items'
        ...eovim/0.10.0/share/nvim/runtime/lua/vim/lsp/handlers.lua:435: in function 'handler'
        .../neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

when I call

```
:lua vim.lsp.buf.definition()
```

**Comment by wojciech-kulik** [comment]
I found the issue in this file:

```
/opt/homebrew/Cellar/neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/util.lua
```

It turns out that it relies on encoding provided by 
```
vim.lsp.get_clients({ bufnr = 0 })[1].offset_encoding
```

I'm not sure what's the exact purpose of this encoding, but my lsp client returns `utf-16` and all my files are `utf-8`, so I just overrode `offset_encoding` in `M.locations_to_items` with `utf-8` and the same in `M._str_utfindex_enc`.

The problem seems to be fixed. But it's just the workaround. I leave the fix to people who actually understand what's going on there :).

**Comment by lewis6991** [comment]
The offset encoding is reported by the server. Maybe the servers aren't setting this correctly if forcing utf-8 fixes the issue?

**Comment by wojciech-kulik** [comment]
@lewis6991 That's the question. However, in this thread I see that multiple LSPs have the same issue, so I suspect it might be something wrong with Neovim implementation. If someone can confirm that this is LSP issue, then I guess we can report it to relevant repositories.

**Comment by eggers** [comment]
> That doesn't fix the issue for `tsserver`, though. I use TypeScript and can confirm that the original issue still exists. Though, from what I can tell, I don't have mixed line feeds. Maybe my issue is not related to this issue after all 🧐

@schemar I was able to fix it by adding a custom handler to my tsserver to skip the definition if it's matching an scss file:

```lua
local tsHandlers = {
  ["textDocument/definition"] = function(err, result, params, ...)
    if result == nil or vim.tbl_isempty(result) then
      return nil
    end

    if vim.tbl_islist(result) then
      for key, value in pairs(result) do
        -- disable definition for scss files
        if string.match(value.uri, ".scss") then
          print(value.uri)
          return nil
        end
      end
    end
    return vim.lsp.handlers['textDocument/definition'](err, result, params, ...)
  end,
}

lspconfig.tsserver.setup {
  handlers = tsHandlers,
}
```

**Comment by pbdeuchler** [comment]
Getting this with `rust-analyzer` on external libraries with neovim `0.10.1`. Patch does not work, and forcing the lsp offset encoding in config gives me a different error:

```
Error executing vim.schedule lua callback: ...ar/neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/util.lua:1136: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...ar/neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/util.lua:1136: in function 'jump_to_location'
        ...eovim/0.10.1/share/nvim/runtime/lua/vim/lsp/handlers.lua:443: in function 'handler'
        .../neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Neovim will still open the proper file in a new buffer, just blank, after dismissing the error.

Something is definitely wonky with how either the client or the server is reading encoding and calculating offsets

**Comment by tris203** [comment]
Can you try again on nighly following: 882a450a2982caa05fcbbe90e94246a8c2b45b8b

**Comment by pbdeuchler** [comment]
appreciate the quick reply @tris203, unfortunately doesn't seem to work:

```
:version

NVIM v0.11.0-dev-724+g439d03174-Homebrew
Build type: Release
LuaJIT 2.1.1725453128
Run ":verbose version" for more info
Press ENTER or type command to continue
```

```
Error executing vim.schedule lua callback: ...vim/HEAD-439d031/share/nvim/runtime/lua/vim/lsp/util.lua:1013: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...vim/HEAD-439d031/share/nvim/runtime/lua/vim/lsp/util.lua:1013: in function 'jump_to_location'
        ...HEAD-439d031/share/nvim/runtime/lua/vim/lsp/handlers.lua:444: in function 'handler'
        ...m/HEAD-439d031/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

**Comment by tris203** [comment]
is this with the utf override removed? @pbdeuchler

**Comment by pbdeuchler** [comment]
Correct, I get the same error with and without that override. 

I am also getting a treesitter/aerial error on file open with nightly... I do wonder if the new treesitter changes are involved somehow? Might be a red herring though.

```
Error executing vim.schedule lua callback: ...y/aerial.nvim/lua/aerial/backends/treesitter/helpers.lua:13: attempt to call method 'start' (a nil value)
stack traceback:
        ...y/aerial.nvim/lua/aerial/backends/treesitter/helpers.lua:13: in function 'range_from_nodes'
        ...lazy/aerial.nvim/lua/aerial/backends/treesitter/init.lua:103: in function 'fetch_symbols'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:129: in function 'attach'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:149: in function 'get'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:251: in function 'attach'
        .../share/nvim/lazy/aerial.nvim/lua/aerial/autocommands.lua:88: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

**Comment by tris203** [comment]
Can you try again with nightly?

**Comment by pbdeuchler** [comment]
Bizarre, still getting the same error:
```
Error executing vim.schedule lua callback: ...vim/HEAD-648d642/share/nvim/runtime/lua/vim/lsp/util.lua:1014: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...vim/HEAD-648d642/share/nvim/runtime/lua/vim/lsp/util.lua:1014: in function 'jump_to_location'
        ...HEAD-648d642/share/nvim/runtime/lua/vim/lsp/handlers.lua:444: in function 'handler'
        ...m/HEAD-648d642/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

```
:version

NVIM v0.11.0-dev-736+g648d6426c-Homebrew
Build type: Release
LuaJIT 2.1.1725453128
Run ":verbose version" for more info
Press ENTER or type command to continue
```

**Comment by tris203** [comment]
Can you share a minimal reproduction?

**Comment by tris203** [comment]
@pbdeuchler I can't recreate your issue. It gd works fine for me in your example and takes me to the library defs in a .cargo folder.

I am also not convinced that your issue is directly related to the original issue.

I think that this issue can be closed, and could you open a new issue with a reproduction issue, and explicit version numbers
