### ISSUE TITLE
Performance of nvim_set_hl is slow when "link" flag is on

### ISSUE THREAD

**Issue by ray-x** [neovim/neovim#19230]
### Neovim version (nvim -v)

NVIM v0.8.0-dev Build type: Release LuaJIT 2.1.0-beta3 Compiled by ray@ray-xps-arch  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

no, lua API not supported

### Operating system/version

Linux arch

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

from git. make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DMIN_LOG_LEVEL=2"

### How to reproduce the issue

Two scripts

```lua
print(os.clock())
for i = 1, 50000, 1 do
  vim.api.nvim_set_hl(0, "SignifySignAdd", { link = "Normal" })
end

print(os.clock())
```

And this 
```lua
print(os.clock())
for i = 1, 50000, 1 do
  vim.api.nvim_set_hl(0, "Normal", { bg = "white", default = true })
end

print(os.clock())
```

From what I posted on reddit
https://www.reddit.com/r/neovim/comments/vqckbo/nvim_set_hl_is_faster_and_you_may_want_to_use_a/
nvim_set_hl is always faster than vim script version. My test can confirm that.
But vim version of `hi link` is very fast. e.g. ` highlight! link Function Normal`
I assume that lua version of nvim_set_hl with link flag should also faster than none link version.

But the fact is, nvim_set_hl with link flag is slower
Above tests, 
First test, link version: 0.04s
Second test, nonlink version: 0.014s

If I run a pure vim version

```vim
let start = reltime()
for i in range(50000)
 highlight! link Function Normal
endfor
let end = reltimestr(reltime(start))
echom 'vim done vim: ' . end
```
It is 0.035s
That explains I took lots of effort convert the highlight group to link but does not have much startup time improvement.

 

### Expected behavior

`vim.api.nvim_set_hl(0, "SignifySignAdd", { link = "Normal" })` should be faster than ` vim.api.nvim_set_hl(0, "Normal", { bg = "white", default = true })`
In worst case should be similar.

### Actual behavior

`vim.api.nvim_set_hl(0, "SignifySignAdd", { link = "Normal" })` is much slower than ` vim.api.nvim_set_hl(0, "Normal", { bg = "white", default = true })`

**Comment by clason** [comment]
I think your test is flawed -- the times are much too low to be statistically significant. If I do more repetitions like
```lua
local hl = vim.api.nvim_set_hl
local tic = os.clock()
for _ = 1, 200000, 1 do
  hl(0, "Normal", { bg = "white", default = true })
end

print(os.clock()-tic)

tic = os.clock()
for _ = 1, 200000, 1 do
  hl(0, "SignifySignAdd", { link = "Normal" })
end

print(os.clock()-tic)
```
I see  `link` being in fact faster:
```
0.128844
0.094038
```
