### ISSUE TITLE
Option to open LSP results using `tab drop`

### ISSUE THREAD

**Issue by aryan9600** [neovim/neovim#19249]
### Feature already in Vim?

No

### Feature description

It'd be great if the lsp could use `tab drop` to jump to the location, that way if the file is already opened as a tab, a new tab for the file isn't created. `coc.nvim` allows this as well with`"coc.preferences.jumpCommand": "tab drop",`.

**Comment by justinmk** [comment]
I think the discussion in https://github.com/neovim/neovim/pull/19213 would address this.

**Comment by mfussenegger** [comment]
If you're using `vim.lsp.tagfunc` (set by default in neovim master) you can use `CTLR-w ]` to open the definition of the symbol under the cursor in a split and then `CTLR-w T` to move it to a tab. You could create a keymap to combine that.

If you're using something like `vim.lsp.buf.references` which shows the entries in the quickfix list you can use the `switchbuf` option to configure the behavior.

If those two options are not good enough you can customize the behavior either via the `on_list` handler added in https://github.com/neovim/neovim/pull/19213 or if that is too limited you can override the full handlers.

Not sure if another option adds anything useful
