### ISSUE TITLE
marks in command range moves cursor to mark

### ISSUE THREAD

**Issue by IngoMeyer441** [neovim/neovim#19248]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+527-g565f72b96

### Vim (not Nvim) behaves the same?

no, vim 8.2.5046

### Operating system/version

Manjaro Linux 21.3.2 Ruah

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

kitty-xterm

### Installation

build from repo

### How to reproduce the issue

```
nvim --clean
iabc<Esc>
:command! -bar -range Test let pos=getpos('.') | <line1>,<line2>s/^./x/ | call setpos('.', pos)
:'{,'}Test
```

### Expected behavior

`[]` marks the cursor position. When running the newly definied `Test` command, the text

```
ab[c]
```

should be transformed to

```
xb[c]
```

keeping the cursor position.

### Actual behavior

```
ab[c]
```

is tranformed to

```
[x]bc
```

so the text transformation is correct, but the cursor position is not kept as expected.

In this example, `getpos` returns a wrong cursor position (`[0, 1, 1, 0]`). This bug first occurred in commit 565f72b9689e0c440ff72c712a090224aaf7631b (found with `git bisect`). Maybe the commit author @muniter can help here?

**Comment by zeertzjq** [comment]
Oh, there are actually two problems here:
1. Mark in command range moves cursor to mark
2. Getting a `'{` and `'}` mark moves cursor to that mark

**Comment by IngoMeyer441** [comment]
Thanks for the quick fix!
