### ISSUE TITLE
$USER expansion to invalid path for tempname()

### ISSUE THREAD

**Issue by levouh** [neovim/neovim#19240]
### Neovim version (nvim -v)

v0.8.0-dev+555-gd07a39c54

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Fedora 35

### Terminal name/version

Kitty

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

_Prelim_

- I understand that this example is explicitly using `--badname`, but the user on my Linux system is handled by a Windows domain controller for work and there is nothing I can do about it being a "bad name".
- I understand that it is _far_ easier to work with when _not_ using a plugin like `fugitive`, however there are enough things going on that I was not able to easily reproduce this myself without following the path that led me to the issue in the first place.

---

_Repro_

Setup first:
```sh
sudo useradd --badname -m foo\\bar
sudo su - foo\\bar
mkdir tmp-project && cd tmp-project
git init
git config user.email "foo@example.com"
git config user.name "Foo Bar"
echo "foo" > README.md
git add README.md
echo 'local function join_paths(...)
  return table.concat({ ... }, "/")
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "neovim", "site"))

local package_root = join_paths(temp_dir, "neovim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      "tpope/vim-fugitive",
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  })
end

_G.load_config = function()
  vim.notify("Config loaded")
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
  load_plugins()
  require("packer").sync()
  vim.cmd([[autocmd User PackerComplete ++once lua load_config()]])
else
  load_plugins()
  require("packer").sync()
  _G.load_config()
end
' > /tmp/init.lua
```

Once setup completed (same `$PWD` as above):
```sh
nvim --noplugin -u /tmp/init.lua
```

Then when inside `nvim`:
```
:G
```

to pull up the staging area. Hit `cc` to commit the previously staged changes.

### Expected behavior

The usual `fugitive.vim` "edit commit message" buffer pops up such that I can edit a commit message, then `:wq` the buffer and so on.

### Actual behavior

```
sh: /tmp/nvim.foobar/3Q33mx/1.sh: No such file or directory                                                                                                                                                                         
error: There was a problem with the editor 'sh /tmp/nvim.foo\bar/3Q33mx/1.sh'.
Please supply the message using either -m or -F option.
```

**Comment by levouh** [comment]
As far as my `bisect` goes, this was introduced [here](https://github.com/neovim/neovim/commit/f50135a32e11c535e1dc3a8e9460c5b4e640ee86), and the issue comes with how `fugitive` uses `tempname()` to create a `.sh` file (see [here](https://github.com/tpope/vim-fugitive/blob/f809dde0e719f89a6fb5cb80f3be65f5cbc1d1fe/autoload/fugitive.vim#L260)) that is then passed to `git` via the environment as the `GIT_PAGER` (see [here](https://github.com/tpope/vim-fugitive/blob/f809dde0e719f89a6fb5cb80f3be65f5cbc1d1fe/autoload/fugitive.vim#L3828)).

Somewhere along the lines things are getting messed up - and I understand that there are a whole slew of things going on here that make it almost impossible to handle edge-case wise.

---

Raising as issue more-so for feedback on how to reproduce this, as from what I can see the addition of the `$USER` to the return of `tempname()` is not something that can be overridden.

**Comment by levouh** [comment]
Would the change mentioned above and tests in `fileio_spec.lua` be enough for a PR @justinmk? I'm happy to take a stab at it if this is truly that simple.

**Comment by justinmk** [comment]
> Are there already functions to escape strings that could be used to pre-process `user` here?

I think vim_mktempdir should just replace slashes when it is building the path. Can use `memchrsub`. Can you try this patch?

```
diff --git a/src/nvim/fileio.c b/src/nvim/fileio.c
index febde53ce2c3..251e658980e8 100644
--- a/src/nvim/fileio.c
+++ b/src/nvim/fileio.c
@@ -5296,6 +5296,11 @@ static void vim_mktempdir(void)
   char user[40] = { 0 };
 
   (void)os_get_username(user, sizeof(user));
+  // Usernames may contain slashes! #19240
+  memchrsub(user, PATHSEP, '_', sizeof(user));
+#ifdef BACKSLASH_IN_FILENAME
+  memchrsub(user, psepcN, '_', sizeof(user));
+#endif
 
   // Make sure the umask doesn't remove the executable bit.
   // "repl" has been reported to use "0177".
```

**Comment by justinmk** [comment]
btw does the result of `:lua =vim.loop.os_homedir()` match your username or what form does it take? Wondering if `vim_mktempdir` should use `os_homedir` instead of `os_get_username`.

**Comment by levouh** [comment]
>Can you try this patch

Will do ASAP and report back here.

---

>btw does the result of :lua =vim.loop.os_homedir() match your username or what form does it take? Wondering if vim_mktempdir should use os_homedir instead of os_get_username

In the example given above with a user `foo\\bar` (normally printed as `foo\bar`), the output of `:lua print(vim.loop.os_homedir())` is just `bar`, which matches `$HOME`. The `foo` in this example is a "namespace", so using whatever is after the `\` seems like a good solution. Not sure about edge cases, but it seems like that would at least always be a valid path.

**Comment by justinmk** [comment]
you can skip `make install` and just use `./build/bin/nvim` after `make`.

try this patch instead:

```diff
diff --git a/src/nvim/fileio.c b/src/nvim/fileio.c
index febde53ce2c3..251e658980e8 100644
--- a/src/nvim/fileio.c
+++ b/src/nvim/fileio.c
@@ -5296,6 +5296,11 @@ static void vim_mktempdir(void)
   char user[40] = { 0 };
 
   (void)os_get_username(user, sizeof(user));
+  // Usernames may contain slashes! #19240
+  memchrsub(user, '/', '_', sizeof(user));
+  memchrsub(user, '\\', '_', sizeof(user));
 
   // Make sure the umask doesn't remove the executable bit.
   // "repl" has been reported to use "0177".
```

**Comment by levouh** [comment]
>you can skip make install and just use ./build/bin/nvim after make.

It's a bit weird because I have to switch users. I believe my runtime files were super out of date as well (I usually use the `appimage`) as I was getting issues with `vim.lsp` not existing. Now that the runtime stuff is updated via one `make install` though, I imagine newer builds will work? We will see though. Thanks for the advice either way.

---

In the previous set of steps, I was running `nvim` via:

```
rm -rf /tmp/neovim; ~/nvim --noplugin -u /tmp/init.lua
```

noting the use of `~/nvim`, which is just the `appimage` from a few days ago. This should be `/usr/local/bin/nvim` which is the version built locally.

With that in mind (and corrected) @justinmk:

* The first provided patch continues to not solve the problem
* The second provided patch _does_ solve the issue

**Comment by levouh** [comment]
You think the second patch is a viable solution @justinmk? If so, I'm happy to throw that in a PR with some tests and submit it.

**Comment by justinmk** [comment]
> You think the second patch is a viable solution @justinmk? If so, I'm happy to throw that in a PR with some tests and submit it.

@levouh yes, thanks! A test would be great but might be difficult to get working in CI, especially on Windows. idk a way to force a user name. would be easier if we used os_homedir but that should probably be a separate PR. 

can skip the test  if it's too much trouble.

**Comment by levouh** [comment]
I submitted the patch for this one via !19323 @justinmk. If you want to merge it, that is up to you (see below).

>would be easier if we used os_homedir but that should probably be a separate PR.

For this, are you thinking the equivalent of `basename "$HOME"` as we already know that it _has_ to have valid path separators in the first place? This seems like another one I could take stab at. If that is indeed the case, any preferred way to handle the `basename` with functions that already exist in core?

**Comment by justinmk** [comment]
> For this, are you thinking the equivalent of `basename "$HOME"` as we already know that it _has_ to have valid path separators in the first place? This seems like another one I could take stab at.

exactly! in C we have the `os_homedir` function...

> any preferred way to handle the `basename` with functions that already exist in core?

look at usages of `path_tail` in the C code.
