### ISSUE TITLE
Neovim incorrectly considers that an argument is required for `:const`

### ISSUE THREAD

**Issue by jchros** [neovim/neovim#19245]
### Neovim version (nvim -v)

NVIM v0.7.2 release

### Vim (not Nvim) behaves the same?

no, vim 8.2.3455

### Operating system/version

macOS 12.4

### Terminal name/version

iTerm 3.4.15

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

nvim --clean
:const

### Expected behavior

List the values of all variables (the same behavior as `:let`), [as the documentation states](https://github.com/neovim/neovim/blob/606af7887bfccba026b792191b55da15a1b575fc/runtime/doc/eval.txt#L3026-L3029).

### Actual behavior

This error is thrown: `E471: Argument required`.

**Comment by jchros** [comment]
This modification on src/nvim/ex_cmds.lua seems to fix the issue:
```diff
@@ -631,7 +631,7 @@ module.cmds = {
   },
   {
     command='const',
-    flags=bit.bor(NEEDARG, EXTRA, NOTRLCOM, CMDWIN),
+    flags=bit.bor(EXTRA, NOTRLCOM, CMDWIN),
     addr_type='ADDR_NONE',
     func='ex_const',
   },
```

**Comment by zeertzjq** [comment]
It should be this:
```diff
diff --git a/src/nvim/ex_cmds.lua b/src/nvim/ex_cmds.lua
index 69ff37f23..d0dc0ada8 100644
--- a/src/nvim/ex_cmds.lua
+++ b/src/nvim/ex_cmds.lua
@@ -631,7 +631,7 @@ module.cmds = {
   },
   {
     command='const',
-    flags=bit.bor(NEEDARG, EXTRA, NOTRLCOM, CMDWIN),
+    flags=bit.bor(EXTRA, NOTRLCOM, SBOXOK, CMDWIN),
     addr_type='ADDR_NONE',
     func='ex_const',
   },
```
