### ISSUE TITLE
Rename VIM/VIMRUNTIME

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#1924]
Following a post in [r/neovim](http://www.reddit.com/r/neovim/comments/2ucxfc/psa_unset_vimruntime/) - we are still using the environment variables VIM and VIMRUNTIME, but in systems where these variables are set for the Vim runtime folder we end up running into problems because the Vim runtime is not compatible (e.g. python wont work).

I did a quick grep, no doubt this will be a bit of a pain - but it would be better to it earlier rather than later. There is also a VIMRUNTIME related PR #1202.

So how does everyone feel about renaming to NVIM and NVIMRUNTIME?

**Comment by bfredl** [comment]
I agree. If the runtimes are incompatible (and I suppose this will only increase in over time), there makes no sense to have one env variable for both.

**Comment by Pyrohh** [comment]
Sure, we might as well given given how different out runtimes are.

**Comment by justinmk** [comment]
Reason this wasn't done early on is this question must be answered:

If `NVIM[RUNTIME]` is set, should nvim also set `VIM[RUNTIME]` in case plugins use that as a search path? I don't know of any plugins that do so, however.

Anyways, I think the advantages of removing ambiguity outweigh the disadvantages of possible plugin breakage.

:+1:

**Comment by equalsraf** [comment]
@justinmk browsing the tree for a bit:

- A lot of plugins in the runtime use or refer to $VIMRUNTIME - changing all of them would be a pain if we want to merge them later from the Vim tree.
- The same is true for the docs and translations.

Maybe we can get NVIMRUNTIME, and always set VIMRUNTIME=NVIMRUNTIME (for plugins). Have not checked for the VIM case.

**Comment by justinmk** [comment]
> Maybe we can get NVIMRUNTIME, and always set VIMRUNTIME=NVIMRUNTIME (for plugins)

It's a tough call, because we don't want to change the user's environment, yet it would be quite ugly for `$VIMRUNTIME` to not reflect the actual environment variable. I don't see a better option though.

**Comment by fwalch** [comment]
Opened #2977 and closing this, since we don't want to rename VIM/VIMRUNTIME anymore.
