### ISSUE TITLE
Powershell command to call jq broken in 0.7.2

### ISSUE THREAD

**Issue by KiLLeRRaT** [neovim/neovim#19250]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal

### $TERM environment variable

unsure

### Installation

Download portable artifact from github releases

### How to reproduce the issue

Hey all,

Windows 10, Neovim 0.7.2, pwsh set as my shell using:

```
if (has('win32'))
	" let &shell = has('win32') ? 'powershell' : 'pwsh'
	let &shell = 'pwsh'
	let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
	let &shellredir = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
	let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
	set shellquote= shellxquote=
	set noshelltemp " FROM: https://superuser.com/a/1561892/69729, Sorts out the issue with shell returned 1, E485 and temp files
endif

```

I have this mapping, which worked for a long time, and recently stopped working for me:

```
nnoremap <leader>=j :%!jq --tab .<cr>:%s/\r<cr>
```

This sends my file to jq, uses tabs for indent and formats the file, and then I remove `\r` throughout the file.

The problem I'm now having is I get the following error when it's run:

```
:%!jq --tab .
shell returned 1

:%s/\r/e
```

When I press enter, I get the shell error:

```
[91mStart-Process: [91mA positional parameter cannot be found that accepts argument '.'.[0me
```

I run Neovim 0.7.2, in Windows. I've set my Neovim shell to be PowerShell.

This used to work, and I've just verified that this works in Neovim 0.7.0.

Does anyone know of anything that changed that I need to take into account in my mapping? Or do you think that they somehow broke something in 0.7.2?

I have run `set verbose=5` to see the command, and it's showing:
```
Executing command: "Start-Process jq --tab ."

shell returned 1
625 lines filtered
:%s/\r
Press ENTER or type command to continue

```

I have had a brief look at the ex commands file, and found a bunch of changes that COULD maybe impact this?
https://github.com/neovim/neovim/commit/f977f9445f7689fc32a136108ff92b3c2137968c

I hope I gave enough information, let me know if there is anything else I can help with.

Cheers,

### Expected behavior

It should format my json file.

### Actual behavior

It's throwing a shell error

**Comment by zeertzjq** [comment]
The recommended options in `:h shell-powershell` has been changed. Can you try these and see if the error still exists?
```vim
		let &shell = executable('pwsh') ? 'pwsh' : 'powershell'
		let &shellcmdflag = '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
		let &shellredir = '-RedirectStandardOutput %s -NoNewWindow -Wait'
		let &shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
		set shellquote= shellxquote=
```

**Comment by KiLLeRRaT** [comment]
Hi,

I've tried the new suggested method, and still same error. Nothing has changed.

I have also now tried to force either `pwsh` and also `powershell` and both gave the same output and error.  So it's not related to a `pwsh` update or anything like that.

Could it be that somehow something is trying ti expand that `.` that's part of my command instead of passing in a literal `.`?

**Comment by KiLLeRRaT** [comment]
I just tried another thing, if I try to run the command that Neovim runs in the terminal, and append my filename to the end
```
Start-Process jq.exe --tab . .\locations.json
```
I get the same error as Neovim,

```
Start-Process: A positional parameter cannot be found that accepts argument '.'.
```

If I run it as follow, using the -ArgumentList parameter to pass arguments, it works:
```
Start-Process jq -ArgumentList "--tab . .\locations.json"
```

Should Neovim be using the `-ArgumentList` for `Start-Process`?

**Comment by justinmk** [comment]
> Should Neovim be using the `-ArgumentList` for `Start-Process`?

@3N4N thoughts?

**Comment by 3N4N** [comment]
So the problem occurs because `Start-Process` takes the arguments "--tab . locations.json" for itself. I'll look into how we should split the arguments of a command from the whole `cmd` string passed in `make_filter_cmd` and report here.

But first, the whole reason I filed the issue and made the PR is because commands like `:%!jq` weren't working. It produced errors like `E485: Can't read file C:\Users\ACER\AppData\Local\Temp\nvim.0\edLT7L\1`. So if @KiLLeRRaT didn't face this issue, then I have to reassess my PR first. I'll check back. And sorry about the mishaps.

**Comment by KiLLeRRaT** [comment]
> So the problem occurs because `Start-Process` takes the arguments "--tab . locations.json" for itself. I'll look into how we should split the arguments of a command from the whole `cmd` string passed in `make_filter_cmd` and report here.
> 
> But first, the whole reason I filed the issue and made the PR is because commands like `:%!jq` weren't working. It produced errors like `E485: Can't read file C:\Users\ACER\AppData\Local\Temp\nvim.0\edLT7L\1`. So if @KiLLeRRaT didn't face this issue, then I have to reassess my PR first. I'll check back. And sorry about the mishaps.
> 
> **Update**: Oh wow. So, KillerRat worked around the error by using `set noshelltemp`. That is a solution I somehow didn't find. @justinmk , should we revert my commit, then? Or should I write something to split the `cmd` into a command and its arguments?

That `set noshelltemp` did take some research and looking around.  I did reference the site where I found it if you check out my config in the first post.

I'd think that splitting the cmd into the cmd and it's arguments may be the proper way to do it (as suggested by the `Start-Process` help page, however it worked for me up until this PR was made without it.  I'm not sure which is going to be better on different platforms and such.

Thanks for your time looking into this so far.

**Comment by 3N4N** [comment]
By splitting, I meant splitting the `cmd = "jq --tab . .\locations.json"` to something like `cmd_cmd = "jq"` and `cmd_arg = "--tab . .\locations.json"`. I have written an initial fix. I'll send the PR. We can talk in concrete code then.

**Comment by KiLLeRRaT** [comment]
> By the way, @KiLLeRRaT until this is fixed, you could wrap the args in quotes in your keybinding manually.
> 
> ```viml
> nnoremap <leader>=j :%!jq "--tab ."<cr>:%s/\r<cr>
> ```

I've actually tried that before raising the issue.  It leaves me with an open windows running `jq`, and clears out the buffer.  The command Neovim runs is:

```
Executing command: "Start-Process jq.exe "--tab .""
```

I will patiently wait for the fix :)

Thanks!

**Comment by justinmk** [comment]
> By splitting, I meant splitting the `cmd = "jq --tab . .\locations.json"` to something like `cmd_cmd = "jq"` and `cmd_arg = "--tab . .\locations.json"`

Even parsing the command is non-trivial, because command names themselves can be quoted in various ways. A command can be a fullpath containing spaces, etc.

Parsing is not the right approach.

**Comment by 3N4N** [comment]
> Parsing is not the right approach.

You're right. I get so tunnel visioned that I can't see even a slightly modified version of the problem I'm trying to solve. Gimme a few days. Lemme see if I can find how to handle this issue properly.
