### ISSUE TITLE
Lua: vim.fn['bogus'] return nil for nonexistent function

### ISSUE THREAD

**Issue by acarl005** [neovim/neovim#19271]
### Feature already in Vim?

No

### Feature description

Lua config files have the ability to call functions in Vimscript, e.g. `vim.fn.expand("%:p")`.

However, there is no way to check if a function exists before trying to call it.

One use case for that is a config file which degrades gracefully if certain features are not available. For example, if `vim-plug` is installed, setup certain things, otherwise do other things. We could check if the function `vim.fn['plug#']` exists or not.

Currently a workaround is to just attempt to call it, and handle the failure...

```lua
local success, error = pcall(vim.fn['plug#begin'], vim.fn.stdpath('data') .. '/plugged')
if not success then --[[fail gracefully]] end
```

That works for this use case, but might have issues if the function has side effects and is not idempotent. IMHO, it would be cleaner to have a conditional like `if vim.fnexists("plug#") then ...`.

See [this SO post](https://stackoverflow.com/questions/72850062/neovim-check-if-a-vim-function-exists-from-lua/72850145) for original discussion.

**Comment by KillTheMule** [comment]
Wouldn't that just be

```lua
if type(vim.fn['plug#begin']) == 'function'
```
as a check?

**Comment by acarl005** [comment]
@KillTheMule Unfortunately not. Accessing a non-existent function on `vim.fn` still produces a non-nil value.

```lua
-- a function which definitely doesn't exist
print(vim.fn.asdfkjashfoeuwhfoawefhj)
```
```
function: 0x010d76cde0
```

I also tried something like this to see if there is some kind of sentinel value for non-existent functions...

```lua
print(vim.fn.doesnotexist__ == vim.fn["plug#"])
```
```
false
```

I really don't understand what's going on here.

**Comment by justinmk** [comment]
could use `:help exists()`.

but it would be cool if  `vim.fn['bogus']` returned `nil`. not sure if there are downsides except possibly a slight one-time performance cost.

**Comment by acarl005** [comment]
@justinmk Ah I see now! Indeed, I can use `vim.fn.exists("*plug#")`.

**Comment by addcninblue** [comment]
I'd like to help with this. Which files are the relevant ones?

I see that there are a few (`nvim/eval/userfunc.c`, `nvim/eval/funcs.c`, etc.) that deal with functions, but I'm not quite sure where the translation is done between builtin functions and lua.

Thanks!

**Comment by zeertzjq** [comment]
This should be implemented in Lua, not C.

**Comment by justinmk** [comment]
@addcninblue https://github.com/neovim/neovim/blob/6645f59832682e9a3623c2b1e45369529bef201a/runtime/lua/vim/_editor.lua#L267-L283

**Comment by addcninblue** [comment]
I think [this PR](https://github.com/neovim/neovim/pull/19385) fixes this.

I check by using `vim.call("exists", "*" .. key)`, and return `nil` if it doesn't exist.

I tried running tests per the CONTRIBUTING guidelines, but it seems that a bunch of tests related to AddressSanitizer are failing. My guess is that this is unrelated to my change, but I'm not quite sure. Thanks!

**Comment by ii14** [comment]
@acarl005 autoload functions (with the `#` in the name) are lazy loaded vim script functions. When you call `foo#bar()` vim takes the `foo#` part and searches for scripts based on that, in this case `autoload/foo.vim`. To check if the script exists you have to search for it in the runtime path, checking if the function exists might not work:
```lua
if vim.api.nvim_get_runtime_file('autoload/plug.vim', false)[1] then
  -- vim-plug is in the runtime path
end
```

> not sure if there are downsides except possibly a slight one-time performance cost.

@justinmk keep in mind that vim script functions can be deleted, so to get a consistent behavior you'd have to check if the function exists every time you call it.

**Comment by ii14** [comment]
With the way things are working right now, `Unknown function` errors from `vim.call` can't really be fully avoided. Consider this:
```lua
vim.cmd([[
  function Test()
    echomsg 'hello'
  endfunction
]])
local Test = vim.fn.Test
Test() -- ok
vim.cmd('delfunction Test')
Test() -- "Unknown function" error
```
There is no going around it, the second call has to raise this error, because referencing a function in lua will not sustain the life of a vim script function.

The function name is resolved when you call it and that can fail, so an error that can be caught with `pcall` is in this case very much an appropriate thing to do. In my opinion `vim.fn` should not pretend like this is not what's happening by returning `nil` for unknown *at the time* functions. I don't really see any benefit to this.

**Comment by acarl005** [comment]
@ii14 thanks for the explanation. That all makes sense.

**Comment by addcninblue** [comment]
What's the resolution on this? Should we close the issue as "behavior as intended"?

**Comment by justinmk** [comment]
> EDIT: actually, `vim.fn.exists("*plug#")` always returns `0` at first, [...] until _after_ attempting to call `pcall(vim.fn["plug#begin"], vim.fn.stdpath("data") .. "/plugged")` 

That's just how vimscript / autoloading works. Need to load modules before checking if their functions exist.

> @justinmk keep in mind that vim script functions can be deleted, so to get a consistent behavior you'd have to check if the function exists every time you call it.

Good callout. We could just document that. Maybe that's too janky.
