### ISSUE TITLE
Nvim intercepts my iTerm2 mapping of Ctrl-Shift-L, etc

### ISSUE THREAD

**Issue by andersjanmyr** [neovim/neovim#19280]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS 12.4 

### Terminal name/version

iTerm2 3.4.16

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

- Start iTerm2 with 2 split panes (I have mapped Ctrl-Shift-L) to Select Pane Right
- nvim --clean (in the left pane)
- Ctrl-Shift-L (nothing happens, this used to move the focus to the right pane)

### Expected behavior

Neovim should not intercept this key code, so the focus should change to my right pane.
I believe this has to do with the following change. https://neovim.io/news/2022/04#distinguishing-modifier-keys

### Actual behavior

Nothing happens when the key combination, Ctrl-Shift-L, is pressed.

**Comment by zeertzjq** [comment]
This sounds like a bug of iTerm2.

**Comment by andersjanmyr** [comment]
It worked Neovim 0.6 and previous releases.
