### ISSUE TITLE
Error: Installation from linux64 deb package fails

### ISSUE THREAD

**Issue by JoelMon** [neovim/neovim#19291]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Pop!_OS 22.04 LTS

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

Deb file downloaded from https://github.com/neovim/neovim/releases/tag/v0.7.2

#### Sha256sum
I checked the sha256sum to make sure file was fine, it was.

```text
$ sha256sum -c nvim-linux64.deb.sha256sum
nvim-linux64.deb: OK
```

### How to reproduce the issue

$ sudo apt install ./nvim-linux64.deb

### Expected behavior

Should install normally.

### Actual behavior

Installation fails with the following message:

```text
$ sudo apt install ./nvim-linux64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'neovim' instead of './nvim-linux64.deb'
The following packages were automatically installed and are no longer required:
  libmsgpackc2 libtermkey1 libtree-sitter0 libunibilium4 libvterm0 lua-luv
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  neovim
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/10.3 MB of archives.
After this operation, 27.0 MB of additional disk space will be used.
Get:1 /tmp/nvim-linux64.deb neovim amd64 0.7.2 [10.3 MB]
(Reading database ... 545897 files and directories currently installed.)
Preparing to unpack /tmp/nvim-linux64.deb ...
Unpacking neovim (0.7.2) over (0.6.1-3) ...
dpkg: error processing archive /tmp/nvim-linux64.deb (--unpack):
 trying to overwrite '/usr/share/applications/nvim.desktop', which is also in package neovim-runtime 0.6.1-3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /tmp/nvim-linux64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Same problem with 7.0 version.

**Comment by zeertzjq** [comment]
Then it seems you need to uninstall `neovim-runtime` package.

**Comment by JoelMon** [comment]
Issue resolved with @zeertzjq suggestion.

To fix:
```bash
$ sudo apt remove neovim-runtime
```

**Comment by KumaCool** [comment]
Same question

> System: Ubuntu server 22.04.1 LTS (GNU/Linux 5.15.0-1013-raspi aarch64)
> Shell: fish 3.5.1
> Neovim: nightly / stable

```bash
> sudo apt install ./nvim-linux64.deb
Reading package lists... Error!
E: read, still have 8 to read but none left
E: Internal error, could not locate member control.tar{.zst,.lz4,.gz,.xz,.bz2,.lzma,}
E: Could not read meta data from /home/kuma/downloads/nvim-linux64.deb
E: The package lists or status file could not be parsed or opened.
```
Use `apt install neovim` no problem, but the version is too old

**Comment by bedlamzd** [comment]
@KumaCool check if you actually downloaded anything. I've been banging my head on the table for an hour before I discovered that I downloaded 0 bytes. Then I used `wget https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.deb` and actually got the package.
