### ISSUE TITLE
keymap.set() allow pass in helper/doc string when set map to a lua function

### ISSUE THREAD

**Issue by ray-x** [neovim/neovim#19293]
### Feature already in Vim?

keymap.set is unique in neovim

### Feature description

Currently
When I run `nmap <C-k>`  the result is
`n <C-k> * <Lua function 479>`
That does not really help to find out what this `<c-k>` is doing
Maybe we can put some string to indicate, e.g
`n <C-k> * <Lua function myfunc>`

option 1:
pass in a named function:

```lua
vim.keymap.set('n', '<c-k>', function myfun().....end, opts={})
```
option 2 
set doc string
```lua
vim.keymap.set('n', '<c-k>', function().....end, opts={doc='calling myfunc'})
```

**Comment by zeertzjq** [comment]
Can't you already pass `desc=` in optsm

**Comment by ray-x** [comment]
Ok, desc works
I think the `desc` is not documented in
`help vim.keymap.set()`

**Comment by clason** [comment]
It is, but transitively: 

> In addition to the options listed in nvim_set_keymap(),

**Comment by lewis6991** [comment]
> option 1:
> pass in a named function:

Not possible as that wouldn't be valid Lua.

>vim.keymap.set('n', '<c-k>', function myfun().....end, opts={})
> option 2

Already exists, as discussed.
