### ISSUE TITLE
Crashing with assertion when setting keywordprg to an empty string in lua and searching with `*`

### ISSUE THREAD

**Issue by yamam** [neovim/neovim#19298]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+583-g7dbe6b1a4

### Vim (not Nvim) behaves the same?

no, vim 8.2.5126

### Operating system/version

Linux 5.10.102.1-microsoft-standard-WSL2 Ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

min.lua
```lua
vim.o.keywordprg = ""
```
nvim --clean -u min.lua min.lua
hit `*`

### Expected behavior

Search for "vim" by "*".

### Actual behavior

nvim crashes.
```
nvim: src/nvim/normal.c:4263: nv_ident: Asertion `*kp != NUL' failed.
```

**Comment by zeertzjq** [comment]
Also applies to `let &keywordprg = ''`

**Comment by arkaragian** [comment]
Hello guys I would like to tackle this issue if there is no one working on it.

**Comment by arkaragian** [comment]
This seems to have been resolved. I have checked out the repo to the following commit. 09c6ce8c4e4c6415cca9b834539ed0df461373f6

**Comment by zeertzjq** [comment]
No this hasn't

**Comment by arkaragian** [comment]
I cannot reproduce the bug given the initial bug report. Below is the output for `./nvim --version`  for a build from untouched sources from the commit that I mention above.

```
NVIM v0.8.0-dev-968-g09c6ce8c4
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: C:/Users/Aris/bin/msys64/mingw64/bin/gcc.exe -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion
 -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=auto -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -DEXITFREE -IC:/Users/Aris/source/repos/neovim/build/cmake.config -IC:/Users/Aris/source/repos/neovim/src -IC:/Users/Aris/source/repos/neovim/.deps/usr/include -IC:/Users/Aris/bin/msys64/mingw64/include -IC:/Users/Aris/source/repos/neovim/build/src/nvim/auto -IC:/Users/Aris/source/repos/neovim/build/include
Compiled by Aris@DESKTOP-DRB7LC3

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```
