### ISSUE TITLE
Keymap <C-_> not work with neovim+Kitty, but it seems to a problem in neovim.

### ISSUE THREAD

**Issue by owariee** [neovim/neovim#19295]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Arch Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

system package manager (community/neovim)

### How to reproduce the issue

Open nvim:
```nvim```

Set the keymap:
```nnoremap <C-_> <cmd>echo $TERM<cr>```
or
```keymap("n", "<C-_>", "<cmd>echo $TERM<cr>", opts)```

### Expected behavior

Expect the keymap to work and it not! just in Kitty!

### Actual behavior

The keymap not work!

**Another person tried to open a [issue](https://github.com/kovidgoyal/kitty/issues/5244) on Kitty repo, and Kitty author said that its a neovim bug.**

I think this is a regression, this only started happening after i updated my Arch Linux, in the process, both packages, Kitty and neovim, are updated, but before that, everything was working normally. Idk if this is ***really*** a issue in neovim like the Kitty author pointed out, but de facto Kitty or neovim, or maybe both, are dealing with a regression. In my normal daily basis i use this to comment my code,  but for the sake of reproducibility i changed it to just echo an environment variable.

**Comment by zeertzjq** [comment]
Map `<C-/>`
