### ISSUE TITLE
Provide full path for require(...) entries in --startuptime output

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#19303]
### Feature already in Vim?

N/A

### Feature description

PR #19267 added `require(...)` entries to the output of `--startuptime`.

This feature request is for the entries to include full paths instead of names, similar to what's done for the existing `sourcing` entries.

This would make it easier to navigate to the file to see whether there are any possible ways to improve the impact on startuptime.

My motivation is so that a plugin I wrote, [`vim-startuptime`](https://github.com/dstein64/vim-startuptime), can provide a way to jump to the file. I think it would be possible to use `runtimepath` to deduce the path, but having the full path seems like it could be a more reliable approach. I don't think it's likely, but I can imagine a scenario where `runtimepath` changes during startup in a way that makes it not possible to properly deduce the path of an already `require`d file. Also, the environment where `runtimepath` is set when using `--startuptime` may differ from the environment used when inspecting `--startuptime`'s output.

**Comment by ii14** [comment]
We could tell the full path only as long as there are no custom loaders added, like impatient.nvim, fennel or teal. After that we can only guess what those loaders are and what they are doing.

If you need `runtimepath` at each point in time, maybe patch the `require` function again?

**Comment by justinmk** [comment]
The fullpath is determined by 'packpath'.

> If you need `runtimepath` at each point in time, maybe patch the `require` function again?

+1. Other enhancements are tracked in https://github.com/neovim/neovim/issues/15392 and https://github.com/neovim/neovim/pull/15436 , don't need this extra issue.
