### ISSUE TITLE
Unintuitive navigation shortcuts in :e command vertical wildmenu

### ISSUE THREAD

**Issue by sghuang19** [neovim/neovim#19304]
### Feature already in Vim?

Yes

### Feature description

Typing `:e` then typing `Tab` triggers `wildmenu` auto-completion to allow users navigate through files and directories.

In Vim, the `wildmenu` is displayed horizontally, hence using left/right arrows to navigate through files and directories and up/down arrows to go up/down a level of directory is sensible.

In NeoVim, `wildmenu` is displayed vertically, making this shortcut counter-intuitive.

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/58419736/178127869-414739ad-4c7e-461a-97a3-53b93233bfd1.png">

The pane in the left runs NeoVim and that in the right runs Vim.

**Comment by justinmk** [comment]
is this different than https://github.com/neovim/neovim/issues/9953 ?

**Comment by zeertzjq** [comment]
Vim now also has `wildoptions=pum` and supports `<Up>`/`<Down>` navigate, which may or may not make this issue a bit different.

**Comment by sghuang19** [comment]
> is this different than #9953 ?
> 
> see also
> 
> * [Switch arrow key behavior in command mode #14506](https://github.com/neovim/neovim/issues/14506)
> * [[WIP/RFC] Add missing key to wildmenu #11001](https://github.com/neovim/neovim/pull/11001)

Different from #9953, as this issue involves not only navigating the wildmenu items, but also going up/down a level in the directories.

#14506 Provides customized solutions, but I see that PR #11001 is closed.

**Comment by sghuang19** [comment]
> Vim now also has `wildoptions=pum` and supports `<Up>`/`<Down>` navigation, which may or may not make this issue a bit different.

I just tried on both Vim and NeoVim. When `wildoptions=pum` is set, Vim swapped left/right and up/down arrows in this scenario, exactly what I wanted, but NeoVim does not.

**Comment by zeertzjq** [comment]
This is wontfix. Nvim's behavior will not match Vim's.

**Comment by zeertzjq** [comment]
> Different from #9953, as this issue involves not only navigating the wildmenu items, but also going up/down a level in the directories.

This was also mentioned in a comment in #9953
