### ISSUE TITLE
No such group 'preview_window_1002'

### ISSUE THREAD

**Issue by charlie39** [neovim/neovim#19308]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+590-g8f36e538cc

### Language server name/version

tried with  sumneko_lua, jdt.ls and rust_analyzer

### Operating system/version

arch linux rolling release

### Steps to reproduce using "nvim -u minimal_init.lua"

just launch the lsp client/server ( sumneko_lua, rust_analyzer,jdt.ls)
call the the vim.lsp.buf_hover() function and than try moving your cursor up or down,

### Actual behavior

just a short error message so posting it here.

```
Error executing vim.sc
hedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/uti
l.lua:1370: Vim:E367: No such group: "preview_window_1002"
stack traceback:
        [C]: in function 'nvim_del_augroup_by_name'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1370: in function </usr/share
/nvim/runtime/lua/vim/lsp/util.lua:1363>
```

**Comment by clason** [comment]
Please upgrade to latest master; this regression has already been fixed.

**Comment by charlie39** [comment]
just fetched and rebuilt it, yap it's gone. Sorry for the inconvenience
