### ISSUE TITLE
Can I check if I am running vim or neovim?

### ISSUE THREAD

**Issue by andreicristianpetcu** [neovim/neovim#1931]
Hi, 
Can I check if I am running vim or neovim? I have a symlink and run both Vim and Neovim with the same config files. Can I have something like this in my vimrc, nvimrc files? 
```
if neovim
 something
else 
 something else
```
Thank you!

**Comment by equalsraf** [comment]
Sure, try this
```
if has('nvim')
...
```

**Comment by Pyrohh** [comment]
This is mentioned in #1272 and #1608 (not saying you should have seen them given they're practically hidden, just putting them out there).

**Comment by andreicristianpetcu** [comment]
That was fast! Thank you!

**Comment by VTrngNghia** [comment]
Very late, but for anyone interested, this works: `:version`
