### ISSUE TITLE
LspStart crucially slows down UI

### ISSUE THREAD

**Issue by pshvechikov** [neovim/neovim#19312]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+580-g45ba2e147

### Language server name/version

pyright 1.1.258

### Operating system/version

Ubuntu 20.04.4 LTS

### Steps to reproduce using "nvim -u minimal_init.lua"

```
npm install -g pyright

curl -LO https://raw.githubusercontent.com/neovim/nvim-lspconfig/master/test/minimal_init.lua
echo 'vim.lsp.set_log_level("debug")' >> minimal_init.lua

nvim -u minimal_init.lua --startuptime /tmp/bla.py /tmp/bla.py
```

### Expected behavior

Fast user interface, fast speed of a cursor

### Actual behavior

After :LspStop everything works as expected. 
After :LspStart cursor experience 2-3x slow down.

lsp.log is too big for gist, i think, I have uploaded it on google drive. 
[video of the change in behaviour on LspStart](https://drive.google.com/file/d/17sQ45luqafTbK6jjPMvKjdVrtbE07w5W/view?usp=sharing)

### Log file

https://drive.google.com/file/d/1RVDxLaC33awnDRcK4ZwMJEix9oKQyycJ/view?usp=sharing

**Comment by pshvechikov** [comment]
A few observations: 
* It  seems the issue is independent from pyright -- I have exactly the same issue with pylsp 
* The issue is also valid for mac-os-build-from-source  NVIM v0.8.0-dev+538-ga9de89894
* Sometimes the issue is gone and nvim works incredibly fast (with exactly the same config, on exactly the same machine), I did not yet understand why

**Comment by pshvechikov** [comment]
* Actually, coc-nvim shows exactly the same problem. 
* [Profiling](https://stackoverflow.com/a/12216578) shows absolutely nothing (I suppose it is not a vimscript issue)

**Comment by pshvechikov** [comment]
Suddently, the issue does not show up neither in a standard macos Terminal nor in Alacritty 🎉 
But why this is so??

**Comment by lockejan** [comment]
Could you try to reproduce it in a containerized environment?

You could use this image to test it with nightly+pyright:
`podman run --rm -it quay.io/nvim-lsp/try.nvim:nightly-python`

for the latest release-0.7 build:
`podman run --rm -it quay.io/nvim-lsp/try.nvim:stable-python`

**Comment by pshvechikov** [comment]
> nvim --startuptime foo.py foo.py will append it's output into foo.py and open foo.py
The name of the file, as well as its content are irrelevant (that is why it is called in such a way), sorry about that. 
The string is just a method to generate the text output, which is invalid python code. 
Invalid python code generates a lot of language server errors, which, in turn generate a lot of visual elements, that may affect the performance of the terminal at hand. At least this is my hypothesis right now. 
Please, see the video in the description to better understand the problem. 

> You also mention macOs in the end.
The problem does not depend on which machine I am doing the test (that is why I added the point about local mac os machine in addition to the remote Ubuntu one). 
This morning I tried with different terminal on exactly the same remote machine and it worked differenly in iTerm and in terminal / alacritty. 

> Could you try to reproduce it in a containerized environment? 
I will, as soon as the problem shows up again. Usually it happens about 70% of the time. Right now it works more or less smoothly. 

Thank you for your intention to help.

**Comment by lockejan** [comment]
Hmm, ok, I watched your screen recording.
Generating invalid $language files, telling the editor that it's valid and then expecting the lsp to take care of it... 🤨
I understand that the slow down is unwanted, but you could also configure your editor to attach another language server to every python file which doesn't make sense either.

nvim-lspconfig attaches the server and handles the communication part as far as I know.
Neovim itself could detach the lsp if it throttles the editor too much, which is maybe what you are after, but I'm not sure if this is the right place to ask for such feature.
Maybe nvim-lspconfig is a better place IMO.
Have you tested this with other editors that are providing lsp-features?

**Comment by pshvechikov** [comment]
[VIDEO of editing the same file on the same machine with the same nvim, but through different terminals](https://drive.google.com/file/d/1JnVHuWB_GlfL_zM3K-IJl6Co0ZcapkZx/view?usp=sharing).
Please download, if it opens in 360p (dont know why google drive sometimes does not allow to see videos in their original quality).

**Comment by pshvechikov** [comment]
Also, there is absolutely no problem for vscode to process the `bla.py` file.

**Comment by nullchilly** [comment]
@pshvechikov 
Just to be sure, did you build neovim with `CMAKE_BUILD_TYPE=RelWithDebInfo` https://github.com/neovim/neovim/issues/18670
Other than that, my best guess is some issue with gpu acceleration

**Comment by pshvechikov** [comment]
In all installations of neovim I have compiled with RelWithDebInfo, as is shown by `nvim --version`

**Comment by lockejan** [comment]
> > podman run --rm -it quay.io/nvim-lsp/try.nvim:nightly-python
> 
> I do not quite understand the need of that -- the remote machine is the same for both terminals, though the speed of a cursor is different for them. For completeness I conducted the test inside the aforementioned image: I run the `nvim --startuptime /tmp/bla.py /tmp/bla.py` inside the image and find exactly the same I have reported above: nvim + iterm2 slows down, nvim + alacritty works normally.

It was just to make sure not any other plugin interferes, but @nullchilly's find is interesting and maybe the missing piece to fix your issue.

I use a release build and testing your example do makes the lsp startup a tiny bit slower but not afterwards. Speed in general isn't affected in my experience significantly.

**Comment by justinmk** [comment]
>  Actually, coc-nvim shows exactly the same problem.

Sounds like a general perf quesiton. In all of the chatter in this issue there's no minimal repro. Could be a number of things. Open an issue if you find a minimal repro.

**Comment by pshvechikov** [comment]
I have provided  the exact neovim version, the exact command that showcases the problem, checked it in the controllable environment and provided version of iterm2. 
@justinmk  what should I provide in addition for a "minimal repro"?

**Comment by nullchilly** [comment]
@pshvechikov My thoughts:

Providing the exact environment is good but the problem is not everyone owns a mac. In case someone does they should be the first to investigate. 

If 10 issues like this get opened and it would be "Lspstart slows down neovim on kitty/alacritty/iterm2/st".

`nvim-lspconfig` isn't a minimal repo. It's essentially the same as "Doesn't work" issue report on an entire neovim repo.

If it only happens on iterm2 why don't you open an issue on their github to seek a direction?

For example: `Lspstart` open, this function is called

```lua
      function(server_name)
        if server_name then
          if configs[server_name] then
            configs[server_name].launch()
          end
        else
          local buffer_filetype = vim.bo.filetype
          for _, config in pairs(configs) do
            for _, filetype_match in ipairs(config.filetypes or {}) do
              if buffer_filetype == filetype_match then
                config.launch()
              end
            end
          end
        end
      end,
```

Then what happens when `configs.launch()` is called. Tho this is most likely iterm2 performance issue (The same happens when you compile all 118 treesitter queries while moving the cursor) Sometimes it lags out sometimes it doesn't.
