### ISSUE TITLE
vim.diagnostic.setqflist() execution error, E5108: Error executing lua Vim:E92: Buffer 11 not found

### ISSUE THREAD

**Issue by JavaHello** [neovim/neovim#19322]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+596-gac10c0f41

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.4

### Terminal name/version

wezterm 20220705-220116-00fb0c58

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

```sh
# Language server jdt.ls

cd javaProject
nvim
:e xxx.java
:lua vim.diagnostic.setqflist()
# open xxx.java
:bw
:lua vim.diagnostic.setqflist()
```

### Expected behavior

Expect vim.diagnostic.setqflist() to execute correctly
<img width="1012" alt="图片" src="https://user-images.githubusercontent.com/24937965/178285005-cd1366d6-8c88-42cf-bbc6-c142deec13c3.png">

### Actual behavior

```log
E5108: Error executing lua Vim:E92: Buffer 11 not found
stack traceback:
        [C]: in function 'setqflist'
        ...m/HEAD-ac10c0f/share/nvim/runtime/lua/vim/diagnostic.lua:489: in function 'set_list'
        ...m/HEAD-ac10c0f/share/nvim/runtime/lua/vim/diagnostic.lua:1433: in function 'setqflist'
        [string ":lua"]:1: in main chunk
```
![nvim-lsp-bw](https://user-images.githubusercontent.com/24937965/178284443-9bbc53e7-5c0e-4b82-b7d7-ad454ef0ac22.gif)

**Comment by JavaHello** [comment]
> @JavaHello can you provide a min java code that can reproduce this issue :) I don't write java . @justinmk assignees me thanks.
Not limited to Java Code, Lua Code also has such problems
![lua-nvim-bw](https://user-images.githubusercontent.com/24937965/179771690-c6ded74b-30de-4dfc-993f-e6621f148aa3.gif)
Tested with [neovim](https://github.com/neovim/neovim) project

**Comment by glepnir** [comment]
reproduce. thanks for report .
