### ISSUE TITLE
cursor not being hidden inside builtin terminal when `:terminal printf "\e[?25l"` is run

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#19337]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+519-g6f6286e4f9

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

linux 5.15.19-1-MANJARO

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

AUR

### How to reproduce the issue

```
nvim --clean
:set shell=/bin/sh
:terminal printf "\e[?25l";sh
:startinsert
```
(`sh` can be replaced with `fish`, `bash`,...)

### Expected behavior

cursor being hidden

### Actual behavior

curser being shown

**Comment by ii14** [comment]
I can't reproduce it on 6f6286e4f90da25a7d1b6bcc96b79b0ccbaf5c26 with alacritty/alacritty@f4bdf5fb36fdf3b329be8253da39050abe7238a5

**Comment by altermo** [comment]
I am sorry, it seems that i acedently did not clear my testing config
