### ISSUE TITLE
Allow displaying function documentation next to autocomplete suggestions

### ISSUE THREAD

**Issue by cweagans** [neovim/neovim#1934]
When a function or class is autocompleted, there should be some way to display related documentation, a la Intellisense (see http://sapphiresteel.com/IMG/png/intellisense.png for a visual example if you're not familiar with Visual Studio).

Of course, the documentation would need to be provided by a third party plugin. The only thing that Neovim should be concerned with is having somewhere to put that information.

**Comment by justinmk** [comment]
I imagine the general solution is floating regions, or even floating buffers. Something we can think about after the UI API has reached maturity.

**Comment by cweagans** [comment]
Yeah, I figured it wouldn't be an immediate thing. Just wanted to log it. YouCompleteMe is able to provide documentation for completion suggestions to editors that support it, but the only way to do it with vim is to display it in a scratch buffer, which kinda sucks.

**Comment by justinmk** [comment]
Somewhat off-topic: for ctags, I recently discovered `g]` which can be used to quickly see a symbol declaration without jumping to it.

In the long term I think the built-in ctags concepts should be optionally extensible for non-ctags inspection/completion conventions...

**Comment by renstrom** [comment]
For reference, this is what it looks like in Emacs (or Spacemacs to be exact):

![screen shot 2015-02-17 at 9 35 31](https://cloud.githubusercontent.com/assets/177685/6225293/6d7dcb1a-b688-11e4-8671-199536b0f1a7.png)

**Comment by renstrom** [comment]
bpython has pretty sweet completion as well, here's some screenshots: http://www.bpython-interpreter.org/screenshots.html

**Comment by dani-h** [comment]
This is a great feature.

**Comment by cweagans** [comment]
Yeah, that's very likely. I don't think nvim needs to care about the specifics of how to get the documentation - it just needs to provide a way for plugin authors to display that information.

**Comment by Shougo** [comment]
In current Vim, preview feature is already implemented.
So, neovim can add another completeopt option like popup.
It displays "info" attribute in popup window instead of preview window.

**Comment by johnzeng** [comment]
after two years, any progress on this feature? The preview windows is really .... bad.....

**Comment by bfredl** [comment]
"extended" uis should already be able to this. For TUI it will require more work.

**Comment by johnzeng** [comment]
I don't want to use GUI because of some personal reason I want it on tui. I am reading nvim docs to see if I can help. Maybe some tips windows is enough

**Comment by naquad** [comment]
+1 here. While using completion in python mode preview has some helpful information but whole screen is jumping when it (dis)appears which is super crappy experience :(

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/8180 and https://github.com/neovim/neovim/pull/6619 will address this.

**Comment by cweagans** [comment]
![image](https://user-images.githubusercontent.com/101590/98848255-addcc180-240e-11eb-935a-6d4a79e1b735.png)

This works now (both in the TUI and in a GUI).
