### ISSUE TITLE
Winbar highlight cannot be set using winhighlight

### ISSUE THREAD

**Issue by akinsho** [neovim/neovim#19345]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+2060-g0f1b17788 

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.4

### Terminal name/version

Kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

1. `nvim --clean`
2. `:setlocal winbar=test`
3. `:setlocal winhighlight=Winbar:Visual`

See error `E474: Invalid argument: winhighlight=Winbar:Visual`

### Expected behavior

Winbar should adopt the highlight `Visual` in that specific window

### Actual behavior

An error is thrown instead

**Comment by zeertzjq** [comment]
The highlight group name is `WinBar`, not `Winbar`. This is indeed not working and quite easy to fix:
```diff
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
index 9e545fbbf..de837720c 100644
--- a/src/nvim/screen.c
+++ b/src/nvim/screen.c
@@ -5316,7 +5316,7 @@ static void win_redr_custom(win_T *wp, bool draw_winbar, bool draw_ruler)
     }
 
     fillchar = wp->w_p_fcs_chars.wbr;
-    attr = (wp == curwin) ? HL_ATTR(HLF_WBR) : HL_ATTR(HLF_WBRNC);
+    attr = (wp == curwin) ? win_hl_attr(wp, HLF_WBR) : win_hl_attr(wp, HLF_WBRNC);
     maxwidth = wp->w_width_inner;
     use_sandbox = was_set_insecurely(wp, "winbar", 0);
 
```
