### ISSUE TITLE
`vim.fn.input` can only use a string as `cancelreturn`

### ISSUE THREAD

**Issue by kylechui** [neovim/neovim#19356]
### Neovim version (nvim -v)

0.7.2 stable

### Vim (not Nvim) behaves the same?

No, N/A

### Operating system/version

Pop! OS 22.04 LTS

### Terminal name/version

Alacritty 0.10.1-rc1

### $TERM environment variable

xterm-256color

### Installation

Appimage

### How to reproduce the issue

1. Create a test file `test.lua` with the following contents:
```lua
local lua_input = vim.fn.input({ prompt = "Enter a string (Lua): ", cancelreturn = nil })
if lua_input then
    print('"' .. lua_input .. '"')
else
    print("No Lua input")
end

vim.cmd([[
let vim_input = input({ "prompt" : "Enter a value (Vim): ", "cancelreturn" : v:null })
if vim_input != v:null
    echo '"' . vim_input . '"'
else
    echon "No Vim input"
endif
]])
```
2. Save the file and run using `:so %`
3. Press `<Esc>` for both prompts

### Expected behavior

The console should print `No Lua input`, followed by `No Vim input`.

### Actual behavior

The console logs `""`, followed by `No Vim input`.
![image](https://user-images.githubusercontent.com/48545987/178860870-e25688b5-f700-4367-9660-dafb157995c1.png)

**Comment by zeertzjq** [comment]
This is a limitation of Lua. You can use `vim.NIL` instead.

**Comment by kylechui** [comment]
Would this work if I wanted to distinguish a canceled input (`<Esc>`) from an empty one (`""`)? Thanks for the fast response!

**Comment by zeertzjq** [comment]
Wait a minute

**Comment by zeertzjq** [comment]
Oh, this is a limitation of the `input()` function. It can only accept a string as `cancelreturn`.

**Comment by zeertzjq** [comment]
None currently. In Vim script `'null' == v:null` evaluates to true, so if input is `null` `No Vim input` will be printed in the example.

**Comment by kylechui** [comment]
Ok thank you for the insight!

**Comment by zeertzjq** [comment]
Now you can use this:
```lua
local lua_input = vim.fn.input({ prompt = "Enter a string (Lua): ", cancelreturn = false })
```

**Comment by kylechui** [comment]
Thanks for the quick work!
