### ISSUE TITLE
cmake: stop using add_compile_options

### ISSUE THREAD

**Issue by kylo252** [neovim/neovim#19359]
## Description

Any compiler options that are added using [add_compile_options()](https://cmake.org/cmake/help/latest/command/add_compile_options.html) are used when compiling targets from the current directory and below, meaning that external libraries will also built using these 
https://github.com/neovim/neovim/blob/17437dc70ccc0112ed3f2106cf8d6616c97c5e03/CMakeLists.txt#L284-L289 

These additional warning aren't relevant for such libraries, since they are _external_ after all, and only serve to make the build times longer, and add a lot of unnecessary noise to the CI logs.

### Suggested solution

This can fixed either by
- using [target_compile_option()](https://cmake.org/cmake/help/latest/command/target_compile_options.html) with `nvim` as the target
- using a [toolchain file](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html)

---

related #17524

**Comment by justinmk** [comment]
First step is to find previous commits, PRs, and issues where we introduced use of this and explain why the reasoning there is no longer valid or no longer has a net benefit.

**Comment by carlocab** [comment]
Are you referring to external libraries in `cmake.deps`?

**Comment by kylo252** [comment]
> Are you referring to external libraries in `cmake.deps`?

I'm talking about these
https://github.com/neovim/neovim/blob/5ccdf6a88d5790382ad3da6bb908c606765754e0/src/nvim/CMakeLists.txt#L99-L100

but even those from `cmake.deps` are explicitly getting passed `CMAKE_C_FLAGS` for certain [builds](https://github.com/neovim/neovim/blob/5ccdf6a88d5790382ad3da6bb908c606765754e0/CMakeLists.txt#L49-L69).

> First step is to find and reference previous commits, PRs, and issues where we introduced use of this and explain why the reasoning there is no longer valid or no longer has a net benefit.

Agreed, and afterwards it should be fairly straight-forward, with minimal risk, to simply move all these assignments to [target_compile_option()](https://cmake.org/cmake/help/latest/command/target_compile_options.html)

**Comment by dundargoc** [comment]
This has been fixed.
