### ISSUE TITLE
vim.fn.getreg() will misunderstand <Tab> as <C-i>

### ISSUE THREAD

**Issue by tristone13th** [neovim/neovim#19358]
### Neovim version (nvim -v)

NVIM v0.7.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

Not tested.

### Operating system/version

Ubuntu 22.04

### Terminal name/version

Windows Terminal

### $TERM environment variable

Not tested.

### Installation

appimage

### How to reproduce the issue

nvim -u NONE
write some <Tab>s into the buffer
yank these <Tab>s
```
:lua print(vim.fn.getreg())
```

### Expected behavior

Output tabs

### Actual behavior

Output <C-I>s, as the image:
![image](https://user-images.githubusercontent.com/17382962/178912595-59ee0712-60bd-415f-9658-1ae6b2fe91ad.png)

**Comment by justinmk** [comment]
> ### Vim (not Nvim) behaves the same?
> Not tested.

Definitely give it a try.
