### ISSUE TITLE
Improve Autoread to match gvim

### ISSUE THREAD

**Issue by nono** [neovim/neovim#1936]
Hi,

the `autoread` options doesn't seem to work in neovim. If I edit a file and have `autoread` set, I'd expect that, when the file is modified, neovim will open the new version (or, at least, will warn me). It's not the case.

I'm using neovim on ubuntu, installed as explained on [the wiki](https://github.com/neovim/neovim/wiki/Installing#ubuntu):

```
:version                                                                     
NVIM 0.0.0-alpha (compiled Feb  2 2015 14:21:21)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Wer
ror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wex
tra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_D
ECLARATIONS -DHAVE_CONFIG_H -I/build/buildd/neovim-0.0.0+git201502020621+1~ubuntu14.10.1
/build/config -I/build/buildd/neovim-0.0.0+git201502020621+1~ubuntu14.10.1/src -I/build/
buildd/neovim-0.0.0+git201502020621+1~ubuntu14.10.1/.deps/usr/include -I/build/buildd/ne
ovim-0.0.0+git201502020621+1~ubuntu14.10.1/.deps/usr/include -I/usr/include/luajit-2.0 -
I/usr/include -I/build/buildd/neovim-0.0.0+git201502020621+1~ubuntu14.10.1/build/src/nvi
m/auto -I/build/buildd/neovim-0.0.0+git201502020621+1~ubuntu14.10.1/build/include
Compilé par buildd@lgw01-21  Fonctionnalités incluses (+) ou non (-) :
+acl             -ebcdic          +lispindent      +postscript      -toolbar
+arabic          -emacs_tags      +listcmds        +printer         +user_commands
+autocmd         +eval            +localmap        +profile         +vertsplit
-browse          +ex_extra        +menu            +quickfix        +virtualedit
+byte_offset     +extra_search    +mksession       +reltime         +visual
+cindent         +farsi           +modify_fname    +rightleft       +visualextra
-clipboard       +file_in_path    +mouse           +scrollbind      +viminfo
+cmdline_compl   +find_in_path    -mouseshape      +signs           +vreplace
+cmdline_hist    +folding         +mouse_dec       +smartindent     +wildignore
+cmdline_info    -footer          -mouse_gpm       +startuptime     +wildmenu
+comments        +fork()          +mouse_netterm   +statusline      +windows
+conceal         +gettext         +mouse_sgr       +syntax          +writebackup
+cscope          +iconv           -mouse_sysmouse  +tag_binary      -X11
+cursorbind      +insert_expand   +mouse_urxvt     +tag_old_static  -xfontset
+cursorshape     +jumplist        +mouse_xterm     -tag_any_white   -xsmp
+dialog_con      +keymap          +multi_byte      +terminfo        -xterm_clipboard
+diff            +langmap         +multi_lang      +termresponse
+digraphs        +libcall         +path_extra      +textobjects
-dnd             +linebreak       +persistent_undo +title
   fichier vimrc système : "$VIM/nvimrc"
     fichier vimrc utilisateur : "$HOME/.nvimrc"
 2me fichier vimrc utilisateur : "~/.nvim/nvimrc"
      fichier exrc utilisateur : "$HOME/.exrc"
  $VIM par défaut : "/usr/share/nvim"
```

**Comment by jszakmeister** [comment]
It does work, you just have to understand the mechanism.  Terminal vim only detects changes when you save the file, execute shell commands, or run `:checktime`.  gvim also checks when focus has been gained (which is one of the reasons why I use gvim vs. terminal vim).  It may be that moving to libtickit for the terminal UI may allow us to detect focus on more terminals (I haven't checked).  But, as it stands, it's not an automatic in the background thing.  If you google around a bit on the subject, you'll find a number of varying solutions to the problem.

It'd be nice if Neovim could plug into FSEvents (for Mac) and inotify (for Linux) later to help implement changes in files more readily though.

To see it work, try running in one terminal:

```text
echo foo > foo.txt
nvim foo.txt
set autoread
```

Then in another run:
```text
echo bar >> foo.txt
```

Then go back to the first terminal and run `:checktime`.  You should see the file load with the updated contents.  If instead you do `set noautoread`, you should see a prompt asking whether to reload the contents or not.

**Comment by nono** [comment]
Thanks for the explanation. Nvim works as you told. So, this issue is not a bug, just a wish.

**Comment by NoahTheDuke** [comment]
As a work-around, in your init.vim where you have `set autoread`, also put `au FocusGained * :echotime`. This will mirror the functionality of Gvim, at least for right now.

**Comment by gandalf3** [comment]
For the record, the above workaround worked for me (albeit with `:checktime` instead of `:echotime`)
So:
```
set autoread
au FocusGained * :checktime
```

**Comment by phanimahesh** [comment]
If `:checktime` is triggered within a BufWritePost autocommand that reformats the buffer,  it doesn't seem to work. Even later `:checktime` invocations also do nothing, only `:e` works.

Am I doing something wrong, or shouldn't I use external autoformatters on write via BufWritePost ?

**Comment by dead10ck** [comment]
I'm having the same problem @phanimahesh is; I have my vimrc set up with an `au BufWritePost` that auto formats my file, but doing `set autoread` and `au FocusGained,BufEnter * :checktime` does refresh the buffer's contents.

**Comment by justinmk** [comment]
see also `:help file-change-detect` (`:help watch-file` in Nvim 0.5).

**Comment by teto** [comment]
thois should now be possible in terminal

**Comment by albertnetymk** [comment]
> thois should now be possible in terminal

You meant the example in `:help watch-file`? It's kind of on a per-file basis. From an end user's perspective, the ideal case would be that `set autoread` automatically monitors all loaded files, and reload them whenever they are changed externally.

**Comment by teto** [comment]
I meant via https://github.com/neovim/neovim/pull/12531 . It won't check more frequently than every 2 sec though.

**Comment by albertnetymk** [comment]
I see; thank you for the explanation.

**Comment by avemilia** [comment]
For some reason
```
set autoread
au FocusGained * :checktime
```
doesn't work with tabs (in terminal) (it does with buffers). That is, doing `:tabnext` `:tabprevious` doesn't show the change.

**Comment by NightMachinary** [comment]
[**@justinmk**](https://github.com/justinmk) commented on [Feb 5, 2020, 12:09 PM GMT+3:30](https://github.com/neovim/neovim/issues/1936#issuecomment-582299210 "2020-02-05T08:39:42Z - Replied by Github Reply Comments"):
> see also `:help file-change-detect` (`:help watch-file` in Nvim 0.5).

I can't figure out how to go from the example in the doc to a one-liner CLI command that opens a file, and watches for file changes on a timer.

**Comment by hsiaosiyuan0** [comment]
you may need to use `:checktime` to force a check, if the previous command you'v ran is `system`:

```lua
local function prettier()
  local path = vim.api.nvim_buf_get_name(0)
  vim.fn.system(("npx prettier -w %s "):format(path))
  vim.api.nvim_command(":checktime")
end
```
