### ISSUE TITLE
Neovim crashes

### ISSUE THREAD

**Issue by kuator** [neovim/neovim#19371]
### Neovim version (nvim -v)

NVIM v0.8.0-dev 5c3bbb67e7c59b2fa18e37fdd9845a0e7e3381db

### Vim (not Nvim) behaves the same?

I don't know, I don't use Vim

### Operating system/version

Ubuntu 22.04

### Terminal name/version

Version 3.44.0 for GNOME 42

### $TERM environment variable

xterm-256color

### Installation

sudo add-apt-repository ppa:neovim-ppa/unstable; sudo apt-get update; sudo apt-get install neovim

### How to reproduce the issue

Open multiple tabs?

### Expected behavior

Doesn't crash

### Actual behavior

Crashes
![Screenshot from 2022-07-15 11-58-45](https://user-images.githubusercontent.com/25168308/179161730-c97570f3-67e2-4bdc-90e4-20cedeed6136.png)

**Comment by jamessan** [comment]
The crash is in libuv's, from code that's called by uv_fs_poll.

```
timer_cb: Assertion `ctx->parent_handle->poll_ctx == ctx' failed.
```

We don't use that anywhere in Neovim.

If you use gitsigns.nvim, maybe it's https://github.com/lewis6991/gitsigns.nvim/issues/536.  If you don't, then is' probably some other plugin.

**Comment by kuator** [comment]
> The crash is in libuv, from code that's called by uv_fs_poll.
> 
> ```
> timer_cb: Assertion `ctx->parent_handle->poll_ctx == ctx' failed.
> ```
> 
> We don't use that anywhere in Neovim.
> 
> If you use gitsigns.nvim, maybe it's [lewis6991/gitsigns.nvim#536](https://github.com/lewis6991/gitsigns.nvim/issues/536). If you don't, then is' probably some other plugin.

Thanks! I do use gitsigns.nvim
