### ISSUE TITLE
Color scheme darkblue has problems matching parenthesis (pi_paren plugin)

### ISSUE THREAD

**Issue by heldergg** [neovim/neovim#19389]
### Neovim version (nvim -v)

v0.8.0-dev-616-g001f19de2-dirty

### Vim (not Nvim) behaves the same?

no, vim 8.2.4793

### Operating system/version

Debian testing

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

1. nvim --clean some.py
2. `:colorscheme darkblue`
3. Insert some text, for example: print("Hello World")
4. Go to normal mode and place the cursor over one of the parenthesis.

### Expected behavior

The matching paren should be highlighted and the cursor should have no changes or at least it should not disappear.

A workaround is to change the MatchParen highlight (example colors):

`:highlight MatchParen guibg=red ctermbg=red`   

### Actual behavior

Now when we highlight a matching parenthesis the cursor just disappears.

**Comment by zeertzjq** [comment]
This does not sound like a bug.

**Comment by zeertzjq** [comment]
If you think this is a bug, report this at <https://github.com/vim/colorschemes/issues>.
