### ISSUE TITLE
Behavior of $ changed when in visual mode.

### ISSUE THREAD

**Issue by rapan931** [neovim/neovim#19381]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+608-g778541067 Build type: RelWithDebInfo

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 20.04.4(Windows 10 & WSL)

### Terminal name/version

wezterm 20220408-101518-b908e2dd

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```lua
--minimal_init.lua 
function stl() return vim.bo.filetype end
vim.go.stl = '%!v:lua.stl()'
vim.api.nvim_feedkeys(
  vim.api.nvim_replace_termcodes('isome text<Esc>0v$', true, false, true), 'i', false)
```
1. nvim --clean -u minimal_init.lua

(this reproduced way created by @shadmansaleh , Thanks!)

Related
- https://github.com/nvim-lualine/lualine.nvim/issues/741
- https://github.com/neovim/neovim/pull/18743#issuecomment-1185260888

### Expected behavior

selected `some text ` (some text + 1)

### Actual behavior

selected `some text`

**Comment by zeertzjq** [comment]
It seems this bug applies to `setglobal stl=%!v:lua.stl()` as well.

**Comment by rapan931** [comment]
Thank you!
