### ISSUE TITLE
Fedora 36, nvim v0.8.0

### ISSUE THREAD

**Issue by AstroMoon** [neovim/neovim#19398]
### Neovim version (nvim -v)

v.0.8.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Fedora 36

### Terminal name/version

konsole

### $TERM environment variable

konsole

### Installation

curl 

### How to reproduce the issue

E5113: Error while calling lua chunk:
/home/fedora/.config/nvim/init.lua:1:
module 'user.options' not found:

no field package.preload['user.options']
no file './user/options.lua'
no file '/build/nvim/parts/nvim/buiild/.deps/usr/share/luajit-2.1.0-beta3/user/options.lua'
no file '/usr/local/share/lua/5.1/user/options.lua'
no file '/usr/local/share/lua/5.1/user/options/init.lua'
no file '/build/nvim/parts/nvim/build/.deps/usr/share/lua/5.1/user/options.lua'
no file '/build/nvim/parts/nvim/build/.deps/usr/share/lua/5.1/user/options/init.lua'
no file './user/options.so'
no file '/usr/local/lib/lua/5.1/user/options.so'
no file '/build/nvim/parts/nvim/build./deps/usr/lib/lua/5.1/user/options.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './user.so'
no file '/usr/local/lib/lua/5.1/user.so'
no file '/build/nvim/parts/nvim/build/.deps/usr/lib/lua/5.1/user.so'
no file '/usr/local/lib/lua/5.1/loadall.so'

stack traceback:

    [C]: in function 'require'
    /home/fedora/.config/nvim/init.lua:1: in main chunk

### Expected behavior

n/a

### Actual behavior

E5113: Error while calling lua chunk:
/home/fedora/.config/nvim/init.lua:1:
module 'user.options' not found:

no field package.preload['user.options']
no file './user/options.lua'
no file '/build/nvim/parts/nvim/buiild/.deps/usr/share/luajit-2.1.0-beta3/user/options.lua'
no file '/usr/local/share/lua/5.1/user/options.lua'
no file '/usr/local/share/lua/5.1/user/options/init.lua'
no file '/build/nvim/parts/nvim/build/.deps/usr/share/lua/5.1/user/options.lua'
no file '/build/nvim/parts/nvim/build/.deps/usr/share/lua/5.1/user/options/init.lua'
no file './user/options.so'
no file '/usr/local/lib/lua/5.1/user/options.so'
no file '/build/nvim/parts/nvim/build./deps/usr/lib/lua/5.1/user/options.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './user.so'
no file '/usr/local/lib/lua/5.1/user.so'
no file '/build/nvim/parts/nvim/build/.deps/usr/lib/lua/5.1/user.so'
no file '/usr/local/lib/lua/5.1/loadall.so'

stack traceback:

    [C]: in function 'require'
    /home/fedora/.config/nvim/init.lua:1: in main chunk

**Comment by smjonas** [comment]
This is not a Neovim issue. The error clearly says that a `user.options` Lua module could not be found. You need to fix your configuration.
