### ISSUE TITLE
Add description to key mappings, similar to what autocommands have

### ISSUE THREAD

**Issue by j-xella** [neovim/neovim#19397]
### Feature description

`nvim_create_autocmd()` can accept this option:

> **desc** (string) optional: description of the autocommand.

It is my understanding that one of the reasons this option was created is that `<lua: N>` does not explain very well what is going on inside.

IMHO, a very similar situation at the moment is with `vim.keymap.set()` . It can accept lua function, but then the display is ugly. As a matter of fact, the fourth parameter to the `set` function is an option list, which could be enhanced to accept and then show the key mapping description.

**Comment by smjonas** [comment]
This feature already exists. Simply pass `{ desc = "Some description"}` as `opts`, e.g.
```
vim.keymap.set("n", "rn", vim.lsp.buf.rename, { desc = "LSP renaming" })
```
Then `:nmap rn` will print out the description.
