### ISSUE TITLE
tabnew + local 'winbar'

### ISSUE THREAD

**Issue by AckslD** [neovim/neovim#19396]
### Neovim version (nvim -v)

v0.8.0-dev-nightly-2-g711a6a9157

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

5.18.9-arch1-1

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

AUR

### How to reproduce the issue

nvim --clean -u tmp_init.lua tmp_init.lua
where `tmp_init.lua` as:
```lua
local active_win = function()
  pcall(function()
    vim.wo.winbar = '%#LineNrAbove#%=%m %{getcwd()}/%#LineNr#%f %#Comment#(%n)'
  end)
end

local non_active_win = function()
  pcall(function()
    vim.wo.winbar = '%#LineNrAbove#%=%m %{getcwd()}/%f (%n)'
  end)
end

local group = vim.api.nvim_create_augroup('MyActiveWin', {clear = true})
vim.api.nvim_create_autocmd('VimEnter', {callback = active_win, group = group})
vim.api.nvim_create_autocmd('WinEnter', {callback = active_win, group = group})
vim.api.nvim_create_autocmd('WinLeave', {callback = non_active_win, group = group})
```

### Expected behavior

Not the below

### Actual behavior

The first line of the first buffer is shown in the new tab instead of the expected winbar.

See the following screencast, notice especially the first line after `:tabnew`. If I do `:tabnext` twice it looks as expected again.

![winbar_issue](https://user-images.githubusercontent.com/23341710/179370823-1551d56e-e2d4-45cd-a239-91d4231b4fa4.gif)

**Comment by zeertzjq** [comment]
`tmp_init.lua` is empty

**Comment by zeertzjq** [comment]
This single line of Vim script is enough to reproduce the issue:
```vim
setlocal winbar=foo
```

**Comment by zeertzjq** [comment]
This seems to solve the problem:
```diff
diff --git a/src/nvim/option.c b/src/nvim/option.c
index 821c7208e..9ed9293c3 100644
--- a/src/nvim/option.c
+++ b/src/nvim/option.c
@@ -6455,6 +6455,9 @@ void didset_window_options(win_T *wp)
   set_chars_option(wp, &wp->w_p_lcs, true);
   parse_winhl_opt(wp);  // sets w_hl_needs_update also for w_p_winbl
   check_blending(wp);
+  wp->w_winbar_height = wp->w_floating ? ((*wp->w_p_wbr != NUL) ? 1 : 0)
+                                       : ((*p_wbr != NUL || *wp->w_p_wbr != NUL) ? 1 : 0);
+  win_set_inner_size(wp);
   wp->w_grid_alloc.blending = wp->w_p_winbl > 0;
 }
 
```

However it is not clear what the behavior should be when there isn't enough room here.

**Comment by AckslD** [comment]
@zeertzjq I still have the above issue, although your smaller example seems to indeed be fixed.

**Comment by AckslD** [comment]
@zeertzjq The issue with showing the first line from the other buffer seem to be fixed but with the original example above I now instead get no winbar on doing `:tabnew`. Again if I do `:tabnext` twice it is there. Should I open a new issue for this or better to reuse this?

**Comment by zeertzjq** [comment]
It seems local value of global-local window options does not get copied when using `:new` or `:tabnew`, so it shouldn't been shown, and for me `:tabnext` twice doesn't show it either.

**Comment by AckslD** [comment]
I don't expect it to be copied but I have autocmds on `WinEnter` and `WinLeave` (as above) to set the window local winbar.

**Comment by AckslD** [comment]
Let me know if that makes sense. How were you trying it @zeertzjq?

**Comment by zeertzjq** [comment]
This is just how global-local window options work. You get the same behavior with `'fillchars'`.

**Comment by AckslD** [comment]
I'm not sure I understand, why is this how global-local options work? Why are they correctly set on in basically all cases (`:tabnext`, `:split` etc) but not when doing `:tabnew` (or `:new`)? Is the `WinEnter` command somehow treated differently on `:tabnew`? I see that the autocommand is called in this case but the setting is not applied for some reason.

**Comment by AckslD** [comment]
I guess due to
```
				Note: For split and tabpage commands the
				WinEnter event is triggered after the split
				or tab command but before the file is loaded.
```
in `:help WinEnter`? Seems `TabNewEntered` is the only one that works, `TabEnter` and `TabNew` seem to behave the same as `WinEnter`.

**Comment by zeertzjq** [comment]
This is because a new empty buffer replaces the old buffer after `WinEnter` is triggered.

**Comment by AckslD** [comment]
I'm still not sure why the new buffer (`BufEnter`?) replaces the local setting but this is all out of scope for this issue. Thanks a lot for the pointers @zeertzjq!
