### ISSUE TITLE
:vert term does not start terminal in vertical split

### ISSUE THREAD

**Issue by sghuang19** [neovim/neovim#19394]
### Feature already in Vim?

Yes

### Feature description

In NeoVim, running `:vert term` will not, as in VIM, split the screen vertically and launch terminal at the side, but rather, launches a buffer occupying a whole tab.

In addition to this, running `:term` will split the screen horizontally and start terminal at the top half. NeoVim will still start a buffer occupying the whole tab. It's different but acceptable.

I think it would be better if we could mimic the behavior of terminal mode in VIM.

**Comment by gpanders** [comment]
Changing the behavior at this point would break a significant number of plugins that depend on the current behavior. Use `:sp|term` to open a terminal in a split (or `:vs|term` for a vertical split). If that’s too much to remember, make a custom user command or mapping.

**Comment by jamessan** [comment]
Duplicate of #11385

**Comment by justinmk** [comment]
> Use `:sp|term` to open a terminal in a split (or `:vs|term` for a vertical split)

Or `:split +term`.
