### ISSUE TITLE
ci(windows): unable to use incremental builds for cmake.deps 

### ISSUE THREAD

**Issue by kylo252** [neovim/neovim#19405]
### Feature already in Vim?

NA

### Feature description

This error shows up 45 times

from: https://github.com/neovim/neovim/runs/7305083478?check_suite_focus=true#step:4:192 
> The build of 'D:\a\neovim\neovim\nvim-deps\CMakeFiles\ad02b797cca5dab31408d5199875e035\mpack.rule' depends on 'D:\A\NEOVIM\NEOVIM\NVIM-DEPS\USR\LIB\LUAROCKS\ROCKS-5.1\MPACK' which is produced by the build of 'D:\a\neovim\neovim\nvim-deps\CMakeFiles\fa5a8305f77418e169b9aec3a6243e01\mpack.rule'. The items cannot be built in parallel.

It's worth mentioning that we currently cannot use ninja as a replacement for msbuild for cmake.deps, although it works fine for the main project, and is in fact faster by a factor of x3 at minimum (at least on my machine).

**Comment by justinmk** [comment]
cmake.deps/ is where third-party projects live. There's zero reason for us to spend time trying to support incremental builds there.

**Comment by kylo252** [comment]
> cmake.deps/ is where third-party projects live. There's zero reason for us to spend time trying to support incremental builds there.

Is the CI time not taken into account? 

Either way, I wanted to document the issue for visibility, maybe it will save others that are attempting/debugging this a little bit of time.
