### ISSUE TITLE
Signs and virtual texts for diagnostics are not shown

### ISSUE THREAD

**Issue by rockyzhang24** [neovim/neovim#19403]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-nightly-6-g8e2524500

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.4

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

 build from repo

### How to reproduce the issue

1. Open any file
2. Type something with wrong syntax and then back to NORMAL mode

The signs and virtual texts for the errors are not shown. **Confirmed that this issue was introduced by this commit** (https://github.com/neovim/neovim/commit/6b1a8f23d7da60aa2fe53cd66760176d2f589690). Thank you. 

### Expected behavior

After I type something with syntax error and then back to NORMAL, no signs and virtual texts are shown. 

See the demo below

https://user-images.githubusercontent.com/11582667/179384331-7828a262-e406-4a79-a3a3-a771953481d7.mov

### Actual behavior

The signs and virtual texts should be shown.

**Comment by glepnir** [comment]
@rockyzhang24  it works for me . please use min config to confirm and #19283 just use api replace some vim.cmd string format

![image](https://user-images.githubusercontent.com/41671631/179384565-33024560-ecf6-4a40-a585-198e80e1cc11.png)

**Comment by rockyzhang24** [comment]
@glepnir Yes. I tested using min config. That's weird. If I save and close the file and then reopen it, the signs and virtual texts are shown as normal.

I also did a further test: I cloned neovim with the latest commit and then reverted the changes of your commit. Then I built and installed it. The issue is gone.

**Comment by glepnir** [comment]
I can't reproduce your issue .I build neovim with latest commit .pr in diagnostic.lua not take effect of diagnostic virtual text i think.

**Comment by rockyzhang24** [comment]
@glepnir So, when you type something and then go back to NORMAL, the errors will be shown immediately, right?

**Comment by glepnir** [comment]
Oh I will trace this issue.

**Comment by rockyzhang24** [comment]
@glepnir Thank you so much. So you can reproduce it now, right?

**Comment by glepnir** [comment]
yup

**Comment by rockyzhang24** [comment]
Nice! Thank you for the investigating.
