### ISSUE TITLE
fast mouse scroll leads to weird input

### ISSUE THREAD

**Issue by mmlb** [neovim/neovim#1940]
I have one of the logitech infinite scroll wheel mice, and when in normal mode and "fast-scrolling" neovim seems to confuse some of the mouse input as an `i` and then proceeds to  input weird characters along with other "user interactions"

See a demo @ https://asciinema.org/a/16067
Only thing done in neovim is scroll up/down "randomly"

**Comment by Pyrohh** [comment]
You did `cat .vimrc`, so I assume that `.vimrc` is symlinked to `.nvimrc`? Do this an issue in vim as well?

**Comment by mmlb** [comment]
Correct, `.nvimrc` is a symlink to `.vimrc`. This issue does not show up in vimv

**Comment by Pyrohh** [comment]
What terminal and shell are you using? Could you run `cat` and scroll your mouse-wheel?

Scrolling in vim works for me using:
- `st` alone and with `tmux` without `:set mouse=a`
- `xterm` and `uxterm` with `:set mouse=a`

Scrolling my mouse down then up using `cat` in `st` results in `^E^E^E^E^E^E^E^Y^Y^Y^Y^Y^Y^Y`, while (u)xterm results in nothing.

**Comment by mmlb** [comment]
hmm currently using lxterminal, tried with gnome-terminal:

             | lxterminal | gnome-terminal
---         |------------     | -------------
`cat`    | ok    | ok
`nvim` | bad | ok

**Comment by Pyrohh** [comment]
> hmm currently using lxterminal, tried with gnome-terminal:

They both use vte, but gnome-terminal instead uses vte3 as well as [gnome-pty-helper](https://github.com/GNOME/vte/tree/master/gnome-pty-helper) (although it can apparently be disabled).
Could you try what you just did again, but with no nvimrc (as to not `set mouse=a`)? Just run `nvim -u NONE`.

If that doesn't work, would you mind trying out #1820? I have no specific reason, but I've already referred a few users there for mouse issues and it has helped.

**Comment by mmlb** [comment]
@Pyrohh yup #1820 seems to fix this. So I guess I will wait for that then.

**Comment by Pyrohh** [comment]
Good to hear :)

**Comment by mmlb** [comment]
yup thanks

**Comment by justinmk** [comment]
closed by #1820
