### ISSUE TITLE
inconsistent behavior between vmap rhs `:<cr>` and `<cmd><cr>`

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#19414]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

did not test

### Operating system/version

archlinux

### Terminal name/version

alacritty 0.10.1 + tmux 3.3a

### $TERM environment variable

tmux-256color

### Installation

pacman -S neovim

### How to reproduce the issue

nvim -u init.vim

```
" init.vim

lua <<EOF
vim.api.nvim_set_keymap("v", [[<space>e]], [[:lua print('hello')<cr>]], { silent = false })
vim.api.nvim_set_keymap("v", [[<space>t]], [[<cmd>lua print('hello')<cr>]], { silent = false })
EOF
```

open a buffer, try `<space>e` and `<space>t`

### Expected behavior

visual mode `<space>e` and `<space>t` will print 'hello' in status line.

### Actual behavior

visual mode `<space>e` works fine, while `<space>t` does not work.

**Comment by zeertzjq** [comment]
`set noshowmode`

**Comment by haolian9** [comment]
@zeertzjq thanks for reaction, i added anther case that did not work as expect (the reproduce 2)

**Comment by zeertzjq** [comment]
This is because `:` ends Visual mode, while `<Cmd>` does not. This is intended behavior.

**Comment by haolian9** [comment]
ah, i finally read and understood the notes about <cmd> in [here](https://neovim.io/doc/user/map.html#%3CCmd%3E)
> - In [Visual](https://neovim.io/doc/user/visual.html#Visual) mode  you can use `line('v')` and `col('v')` to get one end of the
  [Visual](https://neovim.io/doc/user/visual.html#Visual) area, the cursor is at the other end.
> [<Cmd>](https://neovim.io/doc/user/map.html#%3CCmd%3E) avoids mode-changes (unlike "[:](https://neovim.io/doc/user/cmdline.html#:)")

sorry to bother you
