### ISSUE TITLE
Unable to map <C-_> (Control + /)

### ISSUE THREAD

**Issue by zach-wahrer** [neovim/neovim#19422]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

Yes, 8.1.3741

### Operating system/version

Ubuntu 20.04.4 LTS

### Terminal name/version

Kitty 0.25.0

### $TERM environment variable

xterm-kitty

### Installation

Downloaded release, then used dpkg to install.

### How to reproduce the issue

`nvim --clean`
`:map <C-_> :help<CR>`
Hit Control+/.

### Expected behavior

Neovim should map the Control+/ keypress to display help.

### Actual behavior

Neovim goes into search mode as if the control key wasn't pressed.

**Comment by justinmk** [comment]
search existing issues

**Comment by zach-wahrer** [comment]
Yeah, I tried searching with a bunch of different terms, but didn't find anything related to this keymap. :-(

**Comment by smjonas** [comment]
That one seems to be it: #19295
