### ISSUE TITLE
`brew install neovim` gives E303 by default

### ISSUE THREAD

**Issue by JimmyMinhLee** [neovim/neovim#19444]
### Neovim version (nvim -v)

0.7.2_1

### Vim (not Nvim) behaves the same?

No, 8.2.4113

### Operating system/version

macOs 12.3

### Terminal name/version

iTerm2 3.4.16

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

`brew install neovim` 

### Expected behavior

Opening a file by default shouldn't give any errors.

### Actual behavior

From a brand new installation, `neovim` gives `E303` for me

**Comment by Sekomer** [comment]
same thing, +1
