### ISSUE TITLE
vim exit from session in multi byte typing

### ISSUE THREAD

**Issue by ADLVI** [neovim/neovim#19447]
### Neovim version (nvim -v)

NVIM v0.7.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

i dont know realy

### Operating system/version

Linux  5.4.0-121-generic #137-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux

### Terminal name/version

oh-my-posh 7.69.0

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

i install from this wiki : https://github.com/neovim/neovim/wiki/Building-Neovim

### Expected behavior

screenshot : https://ibb.co/94b7NNN

### Actual behavior

when i typing multi byte characters (persian)
"لطفا ادرس کیف پول ..."
the nvim throw error in the curser location and exit from vim 
error was : "nvim: ../src/nvim/mbyte.c:794: utfc_ptr2char_len: Assertion `maxlen > 0' failed."
the view of screen not change just not any more in nvim
my terminal command line was in next line and the nvim view still in terminal

**Comment by clason** [comment]
Please check the latest version (0.7.2, and ideally the current HEAD of master) as well as Vim (which is surely installed on your system).

**Comment by zeertzjq** [comment]
I found a way to reproduce this:
```vim
let &statusline = 'لطفا ادرس کیف پول'
```
