### ISSUE TITLE
E315 throw out when use vim.wo.winbar

### ISSUE THREAD

**Issue by glepnir** [neovim/neovim#19458]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-nightly-5-g1f1863ed5

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macos 12.5

### Terminal name/version

wezterm

### $TERM environment variable

tmux-256color

### Installation

homebrew

### How to reproduce the issue

1. I found if use  `vim.wo.winbar ` after the winbar local patch , It's possible to get an e315 error. use this min config. about
dashboard or startify. I can reproduce this problem 100% use one of them.  this may be related to cursor position. because i get the error e315 lnum is the line number of the current cursor like .  cc @famiu 

```lua
vim.opt.runtimepath:append('~/Workspace/dashboard-nvim')
or 
 vim.opt.runtimepath:append('~/Workspace/vim-startify')
vim.opt.number = true
vim.wo.winbar = 'test'
```
2. `nvim -u min.lua` then `:e` open a file

![issue](https://user-images.githubusercontent.com/41671631/180156196-62e254f1-4d13-47c9-afc8-c1a6402028be.gif)

### Expected behavior

no error out

### Actual behavior

E 315 with lnum error through out

**Comment by zeertzjq** [comment]
I found a related bug in Vim: #10761

**Comment by shawnyu5** [comment]
I also get this error when using `tabe file.txt`

**Comment by famiu** [comment]
> I also get this error when using `tabe file.txt`

could you be a bit more elaborate and give steps to reproduce with `nvim --clean`? Being able to reproduce this without the use of a plugin would be very helpful

**Comment by shawnyu5** [comment]
Defining an auto command like this in `min.lua`

```lua
-- vim.api.nvim_set_option_value("winbar", "hello world", { scope = "local" })
vim.api.nvim_create_autocmd({ "CursorMoved", "BufAdd", "BufNew", "WinScrolled" }, {
	callback = function()
		update()
	end,
})

update = function()
	vim.api.nvim_set_option_value("winbar", "hello world", { scope = "local" })
end
```

Opening neovim using `nvim -u min.lua min.lua`

Move the cursor around, then run `:tabe hi`

![image](https://user-images.githubusercontent.com/55592708/180790819-750c8f0a-1183-41bf-a624-582a2aa9fe15.png)

Note when entering nvim with the above steps, without moving the cursor around first before doing `tabe` does not cause the error...

**Comment by famiu** [comment]
> ```lua
> vim.api.nvim_set_option_value("winbar", "hello world", { scope = "local" })
> ```

I discovered that there's an easier way tot reproduce the issue:

1. `nvim --clean`
2. `setlocal winbar=foo`
3. Go to insert mode and enter a few lines
4. `:tabe foo.txt`

**Comment by askfiy** [comment]
Painful questions

**Comment by nullchilly** [comment]
For anyone still want to use winbar checkout [this commit](https://github.com/neovim/neovim/tree/2966cfe21f8e19f684caf8e9253f40dad107f5ba)
