### ISSUE TITLE
Shell command via :! piped to pager such as `less` doesn't pause after screenful

### ISSUE THREAD

**Issue by ds26gte** [neovim/neovim#19451]
### Neovim version (nvim -v)

NVIM v0.6.1 

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2022 19:26:30)                                                                                                                             Included patches: 1-3995                                         

### Operating system/version

Ubuntu 22.04 LTS

### Terminal name/version

xfce4-terminal 0.8.10

### $TERM environment variable

tmux-256color

### Installation

sudo apt install neovim

### How to reproduce the issue

nvim --clean
:!ls -R ~ | less

### Expected behavior

It is assumed that `ls -R ~` is sufficiently voluminous that it's more than a screenful. (If not, use any command that's guaranteed to produce more than a screenful of output.)

 It is expected that `less` shall pause at the first screenful.

### Actual behavior

Instead, all the output scrolls to the end without interruption.

**Comment by ii14** [comment]
`:!` is not interactive. #1496
