### ISSUE TITLE
Linebreak becomes temporarily disabled when change motion used

### ISSUE THREAD

**Issue by hemmer** [neovim/neovim#1946]
I have noticed a difference (and possible bug) when switching from Vim to Neovim. When I use `cw` in old vim, the linebreaks (enabled by the setting `linebreak on`) are preserved. In Neovim, after using the change motion the linebreaks become disabled and the cursor will jump position. This can be distracting and breaks the flow. Returning to normal mode the linebreaks reappear. The following screenshot demonstrates this:

![neovim](https://cloud.githubusercontent.com/assets/915048/6078006/888d4812-adec-11e4-87a1-5927a1aef85c.png)

Both vim and neovim preserve linebreaks if insert mode is entered by `i`, it seems only for the change motion that this is an issue.

Both versions are on my Ubuntu linux box, and use the same .vimrc:

```
NVIM 0.0.0-alpha+201502021723 (compiled Feb  3 2015 14:08:14)
Commit: 7751cd21f5ae8952f578a0ccd892e32c95a4ae8a
```
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct  2 2014 14:10:49)
Included patches: 1-463
```

**Comment by chrisbra** [comment]
Hi Ewan!

On Fr, 06 Feb 2015, Ewan wrote:

> I have noticed a difference (and possible bug) when switching from Vim to Neovim. When I use `cw` in old vim, the linebreaks (enabled by the setting `linebreak on`) are preserved. In Neovim, after using the change motion the linebreaks become disabled and the cursor will jump position. This can be distracting and breaks the flow. Returning to normal mode the linebreaks reappear. The following screenshot demonstrates this:
> 
> ![neovim](https://cloud.githubusercontent.com/assets/915048/6078006/888d4812-adec-11e4-87a1-5927a1aef85c.png)
> 
> Both vim and neovim preserve linebreaks if insert mode is entered by `i`, it seems only for the change motion that this is an issue.
> 
> Both versions are on my Ubuntu linux box, and use the same .vimrc:
> 
> ```
> NVIM 0.0.0-alpha+201502021723 (compiled Feb  3 2015 14:08:14)
> Commit: 7751cd21f5ae8952f578a0ccd892e32c95a4ae8a
> ```
> ```
> VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct  2 2014 14:10:49)
> Included patches: 1-463
> ```

That is a vim bug that has been fixed with 7.4.576
https://code.google.com/p/vim/source/detail?r=749fc929da45d07efc5352dd8a0c00f8ed9f2163

Best,
Christian
-- 
[Politiker] Ja, wir bezahlen ja die Leute dafür, daß sie sich
Gedanken machen, sonst könnten wir uns ja selber welche machen.
		-- Dieter Hildebrand

**Comment by fwalch** [comment]
Thanks for pointing that out @chrisbra. I got a bit confused for a second because since @hemmer uses 7.4.463 (and thus doesn't have that bug fix), but I guess that means the bug was only introduced in Vim after 463?

**Comment by chrisbra** [comment]
I think this problem was introduced with v7.4.435, but I am not so sure about it.

**Comment by fwalch** [comment]
Hm... but in any case, I guess that shows Neovim should be faster with porting the Vim patches. @justinmk Is "patch parity" with Vim something that's on the roadmap for the first release? If not, I think it should be.

**Comment by justinmk** [comment]
@fwalch yes. We are not that far behind though. And vim is very far behind us :P

**Comment by fwalch** [comment]
@justinmk Weell.. seems to me that ~100 patches is quite a lot. OTOH, many of them should be fairly small, and I hope #1820 will render some more `NA`.. we'll see.

**Comment by justinmk** [comment]
@fwalch Yeah, but it's more efficient if we do it in batches. There are other blocking things right now I've been trying to get out the door. Migrating the legacy tests is higher priority. Then catching up with vim patches will be a matter of a couple weeks.

Vim's own Windows build is 600 patches behind. Users of neovim are using a *more* up-to-date version of Vim than 90% of vim users, despite being 100 patches behind HEAD.

**Comment by fmoralesc** [comment]
@justinmk So true. For some of my plugins I receive 7.3 compatibility bug reports :/
