### ISSUE TITLE
Allow `<C-0>` through `<C-9>` to be mapped.

### ISSUE THREAD

**Issue by FraserLee** [neovim/neovim#19469]
## Feature description

This seems to be an archaic leftover quirk of vim, described in more technical detail here [here](https://stackoverflow.com/q/4728644/7602154). If it's at all possible I'd love to find a way to map `<ctrl> number`, for things like shortcuts to insert diacritics while typing.

As of right now, attempting to map `<C-number>` appears to work, showing up in the list generated by `:map` - it just doesn't trigger anything when the motion is executed.

**Comment by zeertzjq** [comment]
Depends on terminal emulator

**Comment by FraserLee** [comment]
How so? This hasn't worked on any terminal I've tried.

**Comment by zeertzjq** [comment]
What terminal emulators have you tried?

**Comment by zeertzjq** [comment]
If a terminal emulator doesn't support modifyOtherKeys or CSI u there is nothing Nvim can do about it.

**Comment by FraserLee** [comment]
Fair enough. The apple terminal isn't working and I couldn't find any option for it directly in iterm2, but googling it looks like it has CSI u. Thanks.

**Comment by gpanders** [comment]
iTerm2 has an option somewhere to “let applications change the key encoding”. Make sure that is checked.
