### ISSUE TITLE
OptionSet cmdheight is not triggered when cmdheight is changed by nvim_win_set_height()

### ISSUE THREAD

**Issue by Frederick888** [neovim/neovim#19478]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

N/A. Vim does not have this function.

### Operating system/version

Linux

### Terminal name/version

Kitty 0.25.2 (w/ tmux 3.3a)

### $TERM environment variable

xterm-kitty (tmux-256color)

### Installation

Arch official

### How to reproduce the issue

nvim --clean

```
:autocmd OptionSet cmdheight echo 'cmdheight changed'
:call nvim_win_set_height(0, nvim_win_get_height(0) - 1)
```

### Expected behavior

`OptionSet cmdheight` is triggered and it prints out `cmdheight changed`.

### Actual behavior

Autocmd event is not triggered.

**Comment by Frederick888** [comment]
This is somewhat relevant to https://github.com/neovim/neovim/pull/17335.

I think despite the semantics, users of this autocmd would expect an event whenever `cmdheight` changes, no matter if it was changed by `:set cmdheight=xyz` or by `nvim_win_set_height()`.

One scenario for example, [hydra.nvim](https://github.com/anuvyklack/hydra.nvim) caches its hint position, however it currently can only clear its cache when `VimResized`/`OptionSet cmdheight` events get fired. If `cmdheight` is changed by `nvim_win_set_height()` as mentioned at https://github.com/anuvyklack/hydra.nvim/issues/27#issuecomment-1191414932, I don't think there is currently a way for it to clear the cache.

**Comment by Shougo** [comment]
Well, `p_ch` is changed when other states.  `OptionSet` needs to be called in other points?

> One scenario for example, [hydra.nvim](https://github.com/anuvyklack/hydra.nvim) caches its hint position

I think `hydra.nvim` should check current cmdheight value.

**Comment by Frederick888** [comment]
> Well, p_ch is changed when other states.

Sorry I didn't follow. Did you mean that there are actually a lot of other ways to change cmdheight so 'it is infinite changes'?

**Comment by Shougo** [comment]
Yes.  `p_ch`(cmdheight) is changed automatically.  It is hard to track the changes.
I think `OptionSet` is added for user option set.

**Comment by Frederick888** [comment]
I see. Sounds like something we'll have to do a refactoring to make everything go through a `cmdheight` helper to support, no matter if it's done via `OptionSet` or a new autocmd. I agree this is probably not worth the effort at the moment.

I'll close this for now. Thanks for the explanation @Shougo
