### ISSUE TITLE
Need a way to translate `diagnostic.col` to on-screen column

### ISSUE THREAD

**Issue by WhyNotHugo** [neovim/neovim#19475]
### Feature already in Vim?

No

### Feature description

Diagnostics all have a `col` field which indicates the column where the diagnostic occurs (see: `diagnostic-structure`).

However, in a case where a line has content `\tA`, if there is a diagnostic on the `A`, the API indicates `col=2` (1-indexed!). The diagnostic is on the second _character_, but not on the second column on-screen. It's actually on the ninth (assuming tabs have 8-char width).

It would be very useful to have a function that can convert `(lnum, col)` into the _real_ column. I'm sure neovim has the information already since it's needed to properly render on screen.

Context: I'm in need of this because I want to align virtual text to the on-screen column where the character is rendered, e.g.:

![2022-07-23T10:31:31,669506646+02:00](https://user-images.githubusercontent.com/730811/180597560-70120a8f-9b70-4fd9-babe-3739127876d3.png)

**Comment by zeertzjq** [comment]
Does `screenpos()` work?

**Comment by WhyNotHugo** [comment]
I only have a `bufnr`, not a `winid`. The buffer can also be attached to more than one window, and I'd have to iterate all of them. Even then, the window can also be horizontally scrolled, and the results of that function wouldn't really match the desired value here. 

After reading through `screenpos()`, I realise that perhaps "on screen column" isn't quite the exact term to use, but I'm not sure exactly what to call this.

**Comment by ii14** [comment]
You can get that line, trim it to the diagnostic position and use `strdisplaywidth()` on it to get the column in cells.

**Comment by WhyNotHugo** [comment]
Ah, `cell` is probably the concept I was missing. 

I tried something like:

```lua
local function column_to_cell(bufnr, lnum, col)
    local lines = vim.api.nvim_buf_get_lines(bufnr, lnum, lnum + 1, false)

      -- The line does not exist when a buffer is empty, though there may be
  -- additional situations. Fall back gracefully whenever this happens.
  if not vim.tbl_isempty(lines) then
    local line = lines[1]
      local sub = string.sub(line[1], 1, col)
      return strdisplaywidth(sub, 0)
  end


    return col
end
```

But neither `strdisplaywidth` nor `vim.strdisplaywidth` work. It's listed in the docs tho, so not sure I'm doing wrong.

**Comment by smjonas** [comment]
It's probably `vim.fn.strdisplaywidth`

**Comment by WhyNotHugo** [comment]
Ah, `vim.fn.strdisplaywidth`! That works.

I'm not a huge fan of recalculating this for so many positions -- I assume neovim has already calculated this for rendering. There's no function that converts from a column to a cell for existing buffer lines?

**Comment by ii14** [comment]
As far as I'm aware, I think right now this is the only way.

**Comment by WhyNotHugo** [comment]
Work well enough for me. Thanks!
