### ISSUE TITLE
Statusline doesn't update if it's set in cmdline mode

### ISSUE THREAD

**Issue by shadmansaleh** [neovim/neovim#19472]
### Neovim version (nvim -v)

0.8.0 commit d0ced2a12

### Vim (not Nvim) behaves the same?

No. version 9.0.60
On vim it works correctly.

### Operating system/version

Archlinux

### Terminal name/version

kitty terminal

### $TERM environment variable

screen-256color

### Installation

Built from repo

### How to reproduce the issue

```vim
" file: minimal_init.vim
set ls=2

aug tstl
  au!
  au CmdlineEnter * :setl stl=command
  au CmdlineLeave * :setl stl=nocommand
aug end
```

Open nvim with
```sh
nvim --clean -u minimal_init.vim
```
 Now enter comdline mode with `:` and leave with `<esc>`

### Expected behavior

When in cmdline mode the statusline should say `command`.
And after leaving cmdline mode it should say `nocommand`.

### Actual behavior

When entering cmdline mode the stl option does get set to `command` but it never gets rendered. So we only see nocommand after leaving the cmdline mode. If we enter cmdline mode again nocommand is still shown.

### Notes:
- This same bug occurs for tabline & winbar too.
- It's not like statusline isn't getting redrawn as if you set the statusline to an expression that results in command/nocommand based on current mode it works. Which makes me think in cmdline mode statusline is always getting rendered from older stl option and not the newer updated one.

**Comment by zeertzjq** [comment]
The statusline redraw problem has been fixed by #19474.
The tabline redraw problem has been fixed by #19528.
Now the winbar redraw problem remains. I tried to fix that by extending the statusline check to winbar, but it led to a glitched winbar.

**Comment by shadmansaleh** [comment]
@zeertzjq even after #19474 similar issue still occurs if statusline is set in a scheduled function.

```vim
" file: minimal_init.vim
set ls=2

aug tstl
  au!
  au CmdlineEnter * :lua vim.schedule(function() vim.opt.stl='command' end)
  au CmdlineLeave * :lua vim.schedule(function() vim.opt.stl='nocommand' end)
aug end
```

afaik vim doesn't have anything like `vim.schedule` so can't verify how vim behaves in this case.

**Comment by zeertzjq** [comment]
Can't you just call `redrawstatus`?

**Comment by shadmansaleh** [comment]
I think I was getting several issues with calling `redrawstatus` .

https://github.com/nvim-lualine/lualine.nvim/commit/6fbc35b3e0134ccce3848fef8855a3bb390aa509
After looking at the commit really wish I left more info about what the issues were 🤦‍♂️.

Though I think several of them were part of it being called in autocmd context. Since I'm not updating in autocmd context anymore I can reintroduce redraw commands and see how it goes.

**Comment by shadmansaleh** [comment]
Now I remember if `wildmode` is set to `list` and I keep calling `redrawstatus` it gets cleared immediately https://github.com/nvim-lualine/lualine.nvim/issues/781

**Comment by zeertzjq** [comment]
Even if statusline is changed in cmdline mode, it is not updated. It is only updated on entering cmdline mode.

**Comment by zeertzjq** [comment]
Maybe there needs to be another less drastic way to redraw the statusline. Ref #14303

**Comment by shadmansaleh** [comment]
Calling redraw won't work it causes too many unexpected issues. https://github.com/nvim-lualine/lualine.nvim/issues/788 this one is just absurd I can't think of any way to account for that while still calling redraw.

> Even if statusline is changed in cmdline mode, it is not updated. It is only updated on entering cmdline mode.

Do you know why is that the case ? I'm curious if it's possible to make changed statusline to work after CmdlineEnter . Is there a core vim/nvim feature that prevent us from doing that ?

**Comment by zeertzjq** [comment]
After #20262 `:redrawstatus` has fewer side-effects when `'cmdheight' = 1`. With larger `'cmdheight'` there may still be side-effects.

**Comment by zeertzjq** [comment]
#20266 further reduced `:redrawstatus` side-effects. You can just use `:redrawstatus` now.
