### ISSUE TITLE
vim.keymap.set lua function vs string -> lua function not working correctly

### ISSUE THREAD

**Issue by abenz1267** [neovim/neovim#19482]
### Neovim version (nvim -v)

nightly and stable 0.7.2

### Vim (not Nvim) behaves the same?

nvim only

### Operating system/version

linux, arch

### Terminal name/version

kitty, latest

### $TERM environment variable

yes

### Installation

AUR and official

### How to reproduce the issue

This can be reproduced the following way:

1. install lspconfig
2. setup gopls
3. define `vim.keymap.set('v', '<Leader>ca', vim.lsp.buf.range_code_action)`
4. try extracting a variable or extracting a function

Often times you get:
1. no result
2. previous code-action result

If you define the keymap like that: `vim.keymap.set('v', '<Leader>ca', ':lua vim.lsp.buf.range_code_action()<CR>')` .... no problem.

This can also be observed with tree-sitter unit, see this issue: https://github.com/David-Kunz/treesitter-unit/issues/12. Setting the keybind directly to the lua function results in broken behaviour, instead calling it via `:lua` works.

Regards

### Expected behavior

same behaviour with both keymap definitions.

### Actual behavior

not the same.

**Comment by zeertzjq** [comment]
No, the behavior should not be the same. Lua mapping should not leave Visual mode. The lsp function needs to be fixed, I guess.

**Comment by zeertzjq** [comment]
Related: #13896

**Comment by nghialm269** [comment]
@mfussenegger the mapping suggested in #19551 (`vim.keymap.set({'v', 'n'}, '<a-CR>', vim.lsp.buf.code_action)`) doesn't fix this for me, it's still using the last selection, not the current selection.
I'm using latest master https://github.com/neovim/neovim/commit/7f4c50f8c48a57067147ff49bee84d8f4594159d
