### ISSUE TITLE
version string format changed and it breaks some downstream build

### ISSUE THREAD

**Issue by licy183** [neovim/neovim#19499]
### Feature already in Vim?

no

### Feature description

Hello, I am a maintainer from [Termux Packages](https://github.com/termux/termux-packages/). It seems that `neovim-nightly` has changed the logic of generating version number since https://github.com/neovim/neovim/commit/912dbbdd77f382d90e4d8ef8ffa483037248b83a. But it has broken some downstream build, such as https://github.com/termux/termux-packages/pull/11349 and https://github.com/ScoopInstaller/Versions/issues/577. The reason may be https://github.com/termux/termux-packages/pull/11349#issuecomment-1193986946.

In the past, `neovim-nightly` uses a lua script to get the version number. The script executes `git describe --first-parent --dirty`, gets a string like `v0.7.0-689-g6e9a7e7db`, then submatches this string to get something like `-689-g6e9a7e7db`, and concats it with `v0.8.0-dev-nightly`. Finally, it produces a string like `v0.8.0-dev-nightly-689-g6e9a7e7db`. Because `git describe` actually returns the depth between `the most recent annotated tag` and `current commit`, the version number increases as the commits are committed.

Now, it uses `git describe --first-parent --tags --always --dirty` to get the version string. It returns the depth between `the most recent tag found in refs/tags namespace` (which will always be last `nightly`) and `current commit` and gets something like `nightly-2-g6e9a7e7db`. Obviously, it doesn't increase as the commits are committed.

This issue looks like it should be fixed upstream as it breaks some downstream build (not just termux).

PS: My English is not very good. Please point out if there is any mistake. Thanks!

**Comment by justinmk** [comment]
> Now, it uses `git describe --first-parent --tags --always --dirty` to get the version string. It returns the depth between `the most recent tag found in refs/tags namespace` (which will always be last `nightly`) and `current commit` and gets something like `nightly-2-g6e9a7e7db`. Obviously, it doesn't increase as the commits are committed.

Yes, this is a bug. @kylo252
