### ISSUE TITLE
neovim compiles against Lua 5.1 instead of luajit on aarch64 and cause LuaSnip failed

### ISSUE THREAD

**Issue by goldyard** [neovim/neovim#19495]
### Neovim version (nvim -v)

0.7.2-Release aarch64

### Vim (not Nvim) behaves the same?

I don't know

### Operating system/version

Ubuntu 22.04 arm64

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

ppa:neovim-ppa/stable

### How to reproduce the issue

Under my docker image with ubuntu 22.04 arm64:
```
NVIM v0.7.2
Build type: Release
Lua 5.1
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
and under intel version, should be luajit. This cause my LuaSnip plugin failed. 
And this is my Dockerfile
```
RUN apt-get update && apt-get --no-install-recommends install -y tmux fish luajit python3-neovim \
  software-properties-common gpg-agent nodejs \
  && add-apt-repository -y ppa:neovim-ppa/stable \
  && apt-get update \
  && apt-get --no-install-recommends install -y neovim gcc libc6-dev g++ \
  && rm -rf /var/lib/apt/lists/*
RUN sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
ADD dotfiles/.tmux.* /root/
ADD dotfiles/.config /root/.config/
ADD dotfiles/tree-sitter-0.20.6-1-aarch64.pkg.tar.xz /
```

### Expected behavior

expect link to luajit and make LuaSnip work.

### Actual behavior

nvim with LuaSnip plugin got error message blow:
```
Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua ...ot/.local/share/nvim/plugged/LuaSnip/lua/luasnip/loaders/from_vscode.lua:21: '=' expected near 'continue'
stack traceback:
        [C]: in function 'error'
        ?: in function <?:18>
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

**Comment by goldyard** [comment]
> reproduce

If want reproduce, could use docker under macbook pro M1

```
docker pull goldyard/ubuntu-ssh-arm64:v1.3
docker run --rm -v `pwd`:/docker -it --name ubuntu-ssh-test goldyard/ubuntu-ssh-arm64 zsh

```

**Comment by justinmk** [comment]
`cmake/FindLuaJit.cmake` is where the find logic lives. If there's a bug there send a PR. We aren't in the business of debugging your build scripts.

**Comment by goldyard** [comment]
> `cmake/FindLuaJit.cmake` is where the find logic lives. If there's a bug there send a PR. We aren't in the business of debugging your build scripts.

I didn't compile from the source code , I  just installed apt binary package from 
```
add-apt-repository -y ppa:neovim-ppa/stable
apt-get update
apt-get install -y neovim
```
And I don't thin this is my problem, I think this is the ppa package's bug.  
@justinmk

**Comment by clason** [comment]
PPA package bugs are doubly off-topic here...

**Comment by goldyard** [comment]
Athanks a lot, the problem have been fixed by the plugin team, and it works good with Lua5.1 now. So, this problem is OK.
