### ISSUE TITLE
Restore cursor position fails after `6cee15da7`

### ISSUE THREAD

**Issue by lmburns** [neovim/neovim#19490]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-nightly-2-g ea13dce3b

### Vim (not Nvim) behaves the same?

No, Vim acts correctly. `vim 9.0, included patches: 1-65`

### Operating system/version

Linux archbox 5.18.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 15 Jul 2022 15:33:02 +0000 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

tmux-256color

### Installation

`bob` neovim package manager for one method, and from source another.

### How to reproduce the issue

Create a configuration with the following `autocmd`:

```lua
api.nvim_create_autocmd(
    "BufReadPost",
    {
        pattern = "*",
        callback = function()
            local row, col = unpack(api.nvim_buf_get_mark(0, '"'))
            if {row, col} ~= {0, 0} and row <= api.nvim_buf_line_count(0) then
                api.nvim_win_set_cursor(0, {row, 0})
            end
        end
    }
)
```

Open the file, scroll to any line. Close and reopen the file.

### Expected behavior

The cursor should appear on the same line that you just left off of.

### Actual behavior

The cursor actually starts at the beginning of the file.

Though this does work if the callback is wrapped with `vim.defer_fn`. The delay is not noticeable at all with the minimal configuration, but with the configuration that I have it is noticeable. However, before the commit mentioned in the title it is not noticeable in either configuration.

Edit:
Vim does act correctly, but the this is the autocmd I'm using in `vim`. Note this doesn't work after the commit mentioned above in Neovim:

```vim
  augroup RestoreCursor
    autocmd!
    autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
      \| exe "normal! g'\"" | endif
  augroup END
```

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/window.c b/src/nvim/window.c
index f00d98ca6..bf151dceb 100644
--- a/src/nvim/window.c
+++ b/src/nvim/window.c
@@ -6876,9 +6876,11 @@ static void check_lnums_both(bool do_curwin, bool nested)
         wp->w_topline = curbuf->b_ml.ml_line_count;
       }
 
-      // save the (corrected) cursor position and topline
-      wp->w_save_cursor.w_cursor_corr = wp->w_cursor;
-      wp->w_save_cursor.w_topline_corr = wp->w_topline;
+      if (!nested) {
+        // save the (corrected) cursor position and topline
+        wp->w_save_cursor.w_cursor_corr = wp->w_cursor;
+        wp->w_save_cursor.w_topline_corr = wp->w_topline;
+      }
     }
   }
 }
```
