### ISSUE TITLE
Coveralls: use Github's build status API

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#1949]
@justinmk can you try https://github.com/lemurheavy/coveralls-public/issues/25#issuecomment-73294080? (Created this because I didn't want to take #1910 off-topic even more)

**Comment by nickmerwin** [comment]
Hey quick note: the owner of the repo will need to logout / login so Coveralls can get commit status write access.

Thanks!

**Comment by justinmk** [comment]
@nickmerwin Thanks! Done.

**Comment by keradus** [comment]
I use my personal account, which is linked with several organizations.
@nickmerwin how could I give Coveralls access to my personal account, but not all organizations I'm in?

**Comment by fwalch** [comment]
Doesn't seem to have worked, e.g. #1954 has no coveralls status despite a successful Travis build.

**Comment by justinmk** [comment]
@fwalch Yeah, I don't know what else to do. "coveralls" does not appear in the project Settings > Services list. Do I need to add a webhook?

I logged out of coveralls, and logged in, and authorized it when it asked for permissions. I also logged out of GitHub.

**Comment by nickmerwin** [comment]
hi @justinmk and @fmoralesc, the owner of the repo (@ashleyh) needs to reauthorize with Coveralls for commit statuses to be posted. Is she available to do so?

**Comment by fmoralesc** [comment]
@nickmerwin are you sure you didn't mean to ping @fwalch ? I don't have that authority in any way.

**Comment by justinmk** [comment]
I don't know. @ashleyh disappeared months ago.

**Comment by nickmerwin** [comment]
@justinmk ok can I assign the repo to you?

**Comment by justinmk** [comment]
@nickmerwin Yes, thanks.

**Comment by nickmerwin** [comment]
@justinmk ok you're now the owner; could you login/logout of Coveralls once more to finalize?

Thanks!

**Comment by elmart** [comment]
My PR passed Travis build, but is marked as failed because decreasing coveralls score. Are we sure this is what we want? I think that info should just be informational.

**Comment by elmart** [comment]
Sorry. The mentioned PR: https://github.com/neovim/neovim/pull/1947.

**Comment by justinmk** [comment]
@elmart agreed but I don't think there is a choice. It may be more noise than it's worth...

**Comment by elmart** [comment]
@justinmk Not sure what you mean, then. Leaving it as it is? Removing the coveralls integration in PR's?

**Comment by justinmk** [comment]
@elmart I mean coveralls is basically guaranteed to fail 90% of PRs, so it adds a lot of noise. AFAIK there isn't a way for a github to show "informational" build results for a PR. Do you think we should disable it for now?

**Comment by elmart** [comment]
Well, if we have no way for coveralls to do its thing without marking the PR as failed, then, yes (I'd disable it). As you said, 90% of the PR's would then fail, which undoubtedly is too much unnecessary noise. We want to distinguish "real" failures from just coveralls decreasing.
Pity, cause it was a nice addition.

**Comment by justinmk** [comment]
@elmart Other option is to enable the "comments" feature instead, where coveralls leaves comments. This was annoying in a different way, but perhaps a good compromise.

**Comment by elmart** [comment]
If that's going to add a comment every time we add a commit / repush to an open PR, then I think it would be too much noise too. IMO, having the global coverage counter at the project level is enough, if we can't have an informational per-PR just-in-one-place coverall report. That's only my opinion, though. If others think comments are ok, then I can live with that. What I don't think is acceptable is having to go into a PR to know if it's failed because coveralls or because a real failure.

**Comment by justinmk** [comment]
fair enough

**Comment by justinmk** [comment]
disabled for now

**Comment by nickmerwin** [comment]
@elmart @justinmk there's talk of adding thresholds for success/failure status. i.e. if coverage decreases more than 10% it will fail. Do you think that would cut down on noise enough and still be useful?

**Comment by elmart** [comment]
> Do you think that would cut down on noise enough and still be useful?

Well, yes. That could be perfect. Where's that discussion taking place?

**Comment by justinmk** [comment]
@nickmerwin Yes. Although I understand the concern about the threshold value vs. project size, a typical project does not often grow or shrink dramatically. The threshold can easily be adjusted by maintainers as needed, every few months or so.

**Comment by fwalch** [comment]
@justinmk Looks like they added two settings, "COVERAGE THRESHOLD FOR FAILURE" and "COVERAGE DECREASE THRESHOLD FOR FAILURE".

**Comment by fwalch** [comment]
Thanks!
