### ISSUE TITLE
Neovim turns code into comment after  | (or) symbol in .asm file

### ISSUE THREAD

**Issue by gaddin** [neovim/neovim#19506]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

yes, vim 9.0

### Operating system/version

GNU/Linux 5.18.13-arch1-1

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

xterm-256color

### Installation

system package manager

### How to reproduce the issue

nvim file.asm

dw ( FLAG0  || FLAG1 )

### Expected behavior

NASM has directives for boolean operations and the syntax highlighting should not stop after the use of the " | " and " || " operator.

### Actual behavior

When using " | " and " || " the text turns gray as if it were a comment which isn't the case.

**Comment by zeertzjq** [comment]
This should be reported to the maintainer of asm syntax file:
```vim
" Vim syntax file
" Language:		GNU Assembler
" Maintainer:		Doug Kearns dougkearns@gmail.com
" Previous Maintainers: Erik Wognsen <erik.wognsen@gmail.com>
"			Kevin Dahlhausen <kdahlhaus@yahoo.com>
" Contributors:		Ori Avtalion, Lakshay Garg
" Last Change:		2020 Oct 31
```
