### ISSUE TITLE
getcmdline() result is not empty when cancelled by <Esc> keystroke during search

### ISSUE THREAD

**Issue by rapan931** [neovim/neovim#19500]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-nightly-471-gbb7853a62

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul 26 2022 00:06:14) Included patches: 1-66

### Operating system/version

Ubuntu 20.04.4(Windows 10 & WSL)

### Terminal name/version

wezterm 20220408-101518-b908e2dd

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

```vim
" minimal.vimrc
augroup test
  autocmd!
  autocmd CmdlineLeave / echomsg '[' . getcmdline() . ']'
augroup END
```

1. nvim --clean  minimal.vimrc
2. :source minimal.vimrc\<CR>
3. /auto\<Esc>
4. :messages\<CR>

### Expected behavior

```
[]
(getcmdline() result is empty)
```

### Actual behavior

```
[auto]
```

### Other

Vim not reproduced

```vim
" minimal.vimrc
augroup test
  autocmd!
  autocmd CmdlineLeave / echomsg '[' . getcmdline() . ']'
augroup END
```

1. vim --clean  minimal.vimrc
2. :source minimal.vimrc\<CR>
3. /auto\<Esc>
4. :messages\<CR>

output: 
```
[]
```

**Comment by zeertzjq** [comment]
I'm afraid changing this behavior to be compatible with Vim can be backward-compatibility.

**Comment by zeertzjq** [comment]
You can check `v:event.abort`.

**Comment by rapan931** [comment]
Thanks reply.

> You can check v:event.abort.

OK, I check `v:event.abort` closed
