### ISSUE TITLE
Cannot type double quote (`"`) on v0.7.2 if pressing shift

### ISSUE THREAD

**Issue by WhyNotHugo** [neovim/neovim#19517]
### Neovim version (nvim -v)

v0.7.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ArchLinux

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

Arch packages OR Nix packages

### How to reproduce the issue

I'm using an **English international keyboard layout**. Normally, it works like this:

- Pressing <kbd>"</kbd><kbd>a</kbd> inserts `ä`.
- Pressing <kbd>"</kbd><kbd>Space</kbd> inserts `"`.
- Other combinations yield other characters used in spanish/german/dutch: `äëïöü`, etc.

As of 0.7.2, if I'm holding down <kbd>shift</kbd> when pressing <kbd>space</kbd>, a space is inserted rather than a `"`. Because of the mechanics of the key combinations, I tend to hold <kbd>shift</kbd> when pressing space for this input. It is especially necessary when trying to type `"""` (used for python docstrings and multi-line strings).

Can be reproduced with `nvim -u NONE`.

This issue is not present on reproducible on `alacritty`, only when using `foot` as a terminal. However, on other terminal applications (and non-terminal applications like Firefox) work fine. The only application where I can repro this is on neovim.

This works fine in neovim 0.7.0. I quickly tested 0.7.1, and it's also broken.

### Expected behavior

Should insert `"`.

### Actual behavior

Inserts ` ` (space).

**Comment by zeertzjq** [comment]
What does pressing <kbd>Shift</kbd><kbd>Space</kbd> print after you run this command in a shell in foot:
```sh
printf '\x1b[>25u'; cat
```

**Comment by WhyNotHugo** [comment]
I bisected this and the breaking commit it 9e5cef945aa70078d72c1cbd65b91d09d9c891fa

**Comment by WhyNotHugo** [comment]
Before pressing anything:

```
> printf '\x1b[>25u'; cat
'; cat
```

After pressing (and holding) shift:

```
> printf '\x1b[>25u'; cat
'; cat^[[57441;129u
```

After pressing space (shift still down):

```
> printf '\x1b[>25u'; cat
'; cat^[[57441;129u^[[32;130u
```

**Comment by WhyNotHugo** [comment]
I guess it's worth testing other clients with supports for kitty's extended keyboard protocol, and seeing if they fail. If they do, it would seem it's a `foot` issue.

I've no idea of any such clients tho :sweat_smile:

**Comment by zeertzjq** [comment]
As is listed in that page, it is also supported by WezTerm and kitty.

**Comment by gpanders** [comment]
What does the following show in foot?

```
> printf '\x1b[?u\x1b[c'
```

On kitty, this returns

```
[?0u[?62;c
```

The `[?0u` at the beginning indicates that the progressive enhancement query is supported by this terminal. If foot doesn't respond with `[?Nu` (for some `N`) and only returns the second escape sequence, then it does not support kitty's progressive enhancement query, and Neovim reverts to using the Xterm modifyOtherKeys protocol (which foot also supports IIRC).

**Comment by dnkl** [comment]
This is a bug in foot, related to the handling of dead keys when the kitty keyboard protocol has been enabled. See https://codeberg.org/dnkl/foot/issues/1120 for details.

**Comment by dnkl** [comment]
Foot PR: https://codeberg.org/dnkl/foot/pulls/1121 (please do report any regressions it might have introduced!)

**Comment by WhyNotHugo** [comment]
Closing in favour of https://codeberg.org/dnkl/foot/issues/1120 and  https://codeberg.org/dnkl/foot/pulls/1121

Thanks for helping track this one done!
