### ISSUE TITLE
Jobstop left a large number of suspended processes

### ISSUE THREAD

**Issue by general0000** [neovim/neovim#19520]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no, vim9.0

### Operating system/version

win7

### Terminal name/version

nvim-qt

### $TERM environment variable

nvim-qt

### Installation

github release

### How to reproduce the issue

1、Symptom： When switching buffers quickly,  many suspended git processes are observed from windows task manager。
2、With the steps below, one PC can reproduce, the other cannot。 source test.vim：
let jid = jobstart('git status')
echo jid
exec (":sleep 10m")
let ret = jobstop(jid)
echo ret
3、The reason：
In Windows， the git cmd（c:\Program Files\Git\cmd\git.exe） is a wrapper。 Each execution of the git command derives the child process  c:\Program Files\Git\mingw64\bin\git.exe。 Jobstop killed the parent process, but the child process is still there

### Expected behavior

Jobstop kills the parent process, including the child process

### Actual behavior

Jobstop does not kill the child process

**Comment by justinmk** [comment]
> In Windows， the git cmd（c:\Program Files\Git\cmd\git.exe） is a wrapper。 Each execution of the git command derives the child process c:\Program Files\Git\mingw64\bin\git.exe。 Jobstop killed the parent process, but the child process is still there

Hmm. We use a very similar approach as Vim... https://github.com/justinmk/neovim/blob/a2c68a1e9cedd9cf0ed9a49cde8a065fc23f07bc/src/nvim/os/process.c#L42

**Comment by lsvmello** [comment]
@justinmk Is this still a problem?
I'm not able to reproduce it on Windows 11.
