### ISSUE TITLE
neovim ：  Command not found

### ISSUE THREAD

**Issue by ysdlm** [neovim/neovim#1952]
I am a linux mint operating system, according to the manual installation method Ubuntu system according neovim;
    sudo add-apt-repository ppa: neovim-ppa / unstable
    sudo apt-get update
    sudo apt-get install neovim

But after a successful installation:
     Use neovim command prompt command not found.
     Use witch neovim command, the terminal did not respond.

I want to know why this is, what causes？

**Comment by ntnn** [comment]
Because the command is `nvim`, while the package is called `neovim`.

**Comment by ysdlm** [comment]
Thank you very much。
