### ISSUE TITLE
Some options with scope "win" function as with scope "buf", even with nvim_win_set_option

### ISSUE THREAD

**Issue by katawful** [neovim/neovim#19549]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

Yes - VIM - Vi IMproved 9.0

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

kitty

### Installation

Arch repository via Pacman

### How to reproduce the issue

`nvim --clean`

Via `setlocal`
```vim
:set number
:e file1
:e file2
:setlocal nonumber
:bprev
```

Via API
```vim
:set number
:e file1
:e file2
:call nvim_win_set_option(0, "number", v:false)
:bprev
```

### Expected behavior

In the clean session, when `set number` is set, it will set this option globally. `file1` and `file2` will inherit this option. Doing `:setlocal nonumber` in `file2` would disable number line for the entire window, confirmed by going back to `file1` and printing the scope of this option with `:lua print(vim.api.nvim_get_option_info('number')["scope"])`. `nvim_win_set_option` will also set a window-local option as well

### Actual behavior

While the scope of the option does print `win`, instead of behaving like a window-local option it instead behaves like a buffer-local option

In both reproductions, while `file1` and `file2` do inherit number option from `:set number`, running `:setlocal nonumber` in `file2` only disables the number option for `file2` which is not the behavior expected for a window-local option. It also fails with `nvim_win_set_option` for the window that contains `file2`

**Comment by bfredl** [comment]
`nvim_win_set_option` behaves like `:set` (for most options). use `nvim_set_option_value` which allows you to select the indended sematincs (global or local, or both).
