### ISSUE TITLE
stdpath: follow common implementations

### ISSUE THREAD

**Issue by f3fora** [neovim/neovim#19544]
### Feature already in Vim?

No

### Feature description

Popular libraries, e.g. for [go](https://github.com/adrg/xdg), [rust](https://github.com/dirs-dev/dirs-rs), [zig](https://github.com/ziglibs/known-folders),  which implement "stdpath" dirs, usually follows guidelines for specific OS. In particular, citing [dirs-rs](https://github.com/dirs-dev/dirs-rs),  

- the [XDG base directory](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) and the [XDG user directory](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/) specifications on Linux and Redox
- the [Known Folder](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457.aspx) API on Windows
- the [Standard Directories](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW6) guidelines on macOS

Neovim `stdpath` function does not follow in macOS.

If this is wanted, should neovim provides something similar at least a for Lua?

**Comment by carlocab** [comment]
The macOS guidelines were written with native app bundles installed into `/Applications` or `~/Applications` in mind.

For cross-platform Unix software (particularly ones that are CLI-only and installed into a `/usr`-like tree conforming to some version of the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)), the XDG directory specifications are a much better fit.

That is, the current behaviour of `stdpath` is a much better fit for `nvim` itself. Maybe plugins will want different behaviour, but I'm not sure why they would.
