### ISSUE TITLE
Virtual lines and fold text conflict

### ISSUE THREAD

**Issue by lukas-reineke** [neovim/neovim#19557]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-724-gbdbf84303

### Vim (not Nvim) behaves the same?

No, no virtual lines in Vim

### Operating system/version

Arch Linux

### Terminal name/version

Kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

build from source

### How to reproduce the issue

```init.lua
vim.wo.foldenable = true
vim.wo.foldlevel = 1
vim.wo.foldmethod = "marker"
vim.wo.number = true

vim.api.nvim_create_autocmd("BufEnter", {
    group = vim.api.nvim_create_augroup("folds", {}),
    pattern = "<buffer>",
    callback = function()
        vim.api.nvim_buf_set_text(0, 0, 0, 0, 0, {
            "",
            "{{{",
            "hello",
            "}}}",
        })

        local ns = vim.api.nvim_create_namespace "folds"
        vim.api.nvim_buf_set_extmark(0, ns, 1, 0, {
            virt_lines_above = true,
            virt_lines = { { { "virtual text", "Error" } } },
        })
    end,
})
```

Open Neovim and toggle folding with `zm`

### Expected behavior

The virtual text should be displayed first, it is outside the fold.
Then the fold text should be displayed.

### Actual behavior

Neither the virtual text, nor the fold text is displayed, there is just an empty virtual line.
The cursor is now able to go out of bound of the buffer into the end of buffer section.

![2022-07-28_13-14](https://user-images.githubusercontent.com/12900252/181418997-26010e5c-50fa-47dd-8ce0-7eb105d8a204.png)
![2022-07-28_13-14_1](https://user-images.githubusercontent.com/12900252/181419010-0626f0d7-5754-49ef-b1f8-ab4720c198f6.png)

**Comment by zeertzjq** [comment]
> The virtual text should be displayed first, it is outside the fold.

I don't think it is "outside the fold". I think it should be considered folded as well.

**Comment by zeertzjq** [comment]
This expected behavior conflicts with #17027, where the intended behavior is that the virtual lines are not shown.

**Comment by lukas-reineke** [comment]
I didn't see the other ticket, this is probably the same issue.

But expected behavior should be fine. The other ticket talks about having the ext mark on the first line of the fold, with virt_lines_above=true.
In this ticket, the ext mark is one line above the fold, with virt_lines_above=false.

So the virtual line is in the same place, but should behave differently when the next line is folded.
