### ISSUE TITLE
typing plain text in `nvim --clean` feels slower than other editors like `vim --clean` or `hx`

### ISSUE THREAD

**Issue by marcelbeumer** [neovim/neovim#19550]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-

### Vim (not Nvim) behaves the same?

no, vim 8.2.4113 

### Operating system/version

macOS 12.4

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

- `nvim --clean`
- enter insert mode
- do some fast and wild typing for some lines
- notice responsiveness (feels good until you try others)

do same with vim:

- `vim --clean`
- enter insert mode
- do some fast and wild typing for some lines
- notice responsiveness (feels faster)

do the same with helix:

- `hx`
- enter insert mode
- do some fast and wild typing for some lines
- notice responsiveness (feels faster than nvim; like vim)

if you wouldn't try vim or hx you would think there is nothing wrong with nvim, but when you try the others you notice something is off...

### Expected behavior

clean nvim feels as fast as clean vim or helix when typing text (in a simple text buffer without highlighting)

### Actual behavior

clean nvim feels slower (laggy) compared to a clean vim or helix when typing text (in a simple text buffer without highlighting)

**Comment by marcelbeumer** [comment]
I have no idea how to proof my claims, nor how to debug it (not a C/C++ dev), but I noticed after I had issues with [Go syntax highlighting performance](https://github.com/nvim-treesitter/nvim-treesitter/issues/3187) and started playing around with other editors.

**Comment by gpanders** [comment]
There's nothing actionable here. If you have a specific, reproducible test case that demonstrates some performance issues, then provide those details. But there is nothing we can do about "it feels slow".

**Comment by marcelbeumer** [comment]
I understand you'd rather see hard perf numbers that are easy to reproduce, just don't know how to provide that. 

I'm not familiar with the (n)vim codebase (nor am I a C dev), but I do build nvim from source, so if there's a way to for example log/debug how long a keystroke takes from keypress->render, please let me know.

Regardless, the reproduction above steps are quite easy & fast if you have nvim and vim installed, and I imagined that if there is an issue with neovim, the neovim devs would be more than happy to know.

**Comment by gpanders** [comment]
>but I do build nvim from source

Make sure you are building a release build, and not a debug build. `make CMAKE_BUILD_TYPE=RelWithDebInfo` or `make CMAKE_BUILD_TYPE=Release`.

>Regardless, the reproduction above steps are quite easy & fast if you have nvim and vim installed,

These: 
>- do some fast and wild typing for some lines
>- notice responsiveness (feels good until you try others)

are not reproduction steps. Reproduction steps should be deterministic ("enter this text", "perform these commands", etc.) and have objective results ("an error occurs", "this benchmark is slower", etc.).

In any case, `nvim --clean` and `vim --clean` feel equally snappy to me on macOS 12.4.

**Comment by marcelbeumer** [comment]
Yes I'm using release builds.
Reproduction steps: I know, I understand.
Thanks for checking on your machine.

If anyone knows how to debug/profile this (& comparing to vim) I'd be happy to hear and try.

**Comment by clason** [comment]
> I understand you'd rather see hard perf numbers that are easy to reproduce, just don't know how to provide that.

It's not about hard numbers, but about a specific (minimal!) reproducing example. Without that, there's literally nothing we can do.

**Comment by KillTheMule** [comment]
You might want to check out https://danluu.com/input-lag/ if there's some measuring methodology to be copied that could verify your feelings (note: I did not read that really and not check out the measuring methodology).

**Comment by marcelbeumer** [comment]
I feel like having provided valuable feedback to the clerk selling train tickets, only to hear he's not responsible for the delays and I should have filled out the form better, and not waste his time. 

At the same time I understand what you want to see instead, and you don't want vague bug reports, so I'll resort to other comm channels and see how to get there.

**Comment by justinmk** [comment]
Are `nvim --clean` and `vim --clean` using the same defaults?

> This is a bit like providing feedback to the clerk selling train tickets, only to hear he's not responsible for the delays

It is a bit like telling the clerk "the train feels a bit slower".

**Comment by marcelbeumer** [comment]
> It is a bit like telling the clerk "the train feels a bit slower".

Ha, true!
