### ISSUE TITLE
Pyright LSP Client Fails at Start

### ISSUE THREAD

**Issue by danielgarzaf** [neovim/neovim#19552]
### Neovim version (nvim -v)

NVIM v0.8.0-dev

### Language server name/version

pyright 1.1.264

### Operating system/version

Ubuntu 20.04 (WSL)

### Steps to reproduce using "nvim -u minimal_init.lua"

Open a python file

### Expected behavior

LSP client attached to buffer successfully

### Actual behavior

 `Client 1 quit with exit code 1 and signal 0` appears as an error message. LSP is not attached
![image](https://user-images.githubusercontent.com/58958492/181376274-622d6568-63c6-43f3-a0e0-6598e4b19056.png)

### Log file

https://gist.github.com/danielgarzaf/63d1a6f497611170a3b4d48da0407d15

**Comment by clason** [comment]
This means that the server (pyright) crashed, either due to a bug or due to incorrect configuration. Without any details, there's nothing we can do here.

**Comment by danielgarzaf** [comment]
Is the log file not providing the necessary details?
I've posted on pyright the same information (https://github.com/microsoft/pyright/issues/3754) but it seems like the error is not on their side.

**Comment by clason** [comment]
Did you look at the log file? The last lines clearly point to a permissions issue that `pyright` runs into.

**Comment by danielgarzaf** [comment]
Yes. I mentioned in the pyright issue that it had to do with permissions, and that I had to resort to posting the issue since I wasn't getting anywhere even after giving the relevant binaries and folders the necessary permissions.
I also assumed it had to do with pyright, because the night before it was working fine.

**I don't know what happened, but today it's working again as it was before without having to change anything.**

**Comment by CacaphonicCode** [comment]
Has anyone figured out what the root issue is here? I'm running into the same issue years later with stock Lazyvim on PopOS (with nvim installed via nixpkgs because basically every plugin requires the latest version of nvim that isn't in the PopOS repos since it's an Ubuntu deriv) and these two issues are all I can find, both of them seemingly ending with "it's on them, our side is clean".

**Comment by clason** [comment]
@CacaphonicCode Please open a new issue and provide a minimal(!) reproducing example without LazyVim (and ideally nixpkgs because that can absolutely interfere).
