### ISSUE TITLE
idea: paired programming

### ISSUE THREAD

**Issue by eppineda** [neovim/neovim#1955]
[ apologies for not being able to label this as 'discussion'. let me know if i've broken protocol; i'm a new participant. ]

I've always fancied the idea of vim accommodating paired-programming sessions -- that is, two or more participants using vim to collaborate in programming. I've been monitoring **neovim** for a little while and excited that such a project exists. Has the notion of shared editing sessions ever been considered as a new feature for vim? Imagine allowing remote control of your editor while your partner makes a change, viewing the changes in real-time...

**Comment by fwalch** [comment]
There's the [Floobits plugin](https://floobits.com/help/plugins/nvim), does that do what you want?

**Comment by justinmk** [comment]
Floobits have put a lot of work into this. We try to communicate with them when we make breaking changes.

**Comment by tarruda** [comment]
This is still not polished in terms of usability, but right now it should be possible to connect to a nvim instance running on a different machine using the python client UI prototype
