### ISSUE TITLE
inccommand: 'cursorline' is automatically disabled

### ISSUE THREAD

**Issue by smjonas** [neovim/neovim#19566]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-nightly-10-g1a07044c1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux Mint 20.2

### Terminal name/version

Kitty 0.15

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

1. `nvim --clean`
2. Define the following command which stores the value of `vim.wo.cursorline` inside the preview callback:
```lua
cur_cursorline
vim.api.nvim_create_user_command("Test", "", {
  preview = function(_, _, _)
    cur_cursorline = vim.wo.cursorline
    return 2
  end,
})
```
3. Run `:set cursorline`
4. Run `Test`
5. Run `:lua =cur_cursorline`

### Expected behavior

`true` should be printed since `cursorline` has been set in step 3

### Actual behavior

`false` is printed

### Additional context

The reason I care about this is because I want to disable `cursorline` inside the preview callback and later restore it to whatever value the user has set it to.

**Comment by zeertzjq** [comment]
It's already disabled

**Comment by smjonas** [comment]
Well, I am not sure why this didn't occur to me earlier... Thanks, this solves my problem!

Note to self, it's set here:

https://github.com/neovim/neovim/blob/f254fc67a5c04c6454425df2f2434b52a1f9e949/src/nvim/ex_getln.c#L2453

**Comment by zeertzjq** [comment]
Or otherwise it can be documented better.
