### ISSUE TITLE
nvim_set_keymap can't handle ranges when used with Lua callbacks

### ISSUE THREAD

**Issue by gbrlsnchs** [neovim/neovim#19567]
### Feature already in Vim?

N/A

### Feature description

When using `nvim_set_keymap` with a Lua callback and mode `v`, the command doesn't receive the range passed by the mapping.

Example:
```lua
vim.api.nvim_set_keymap("v", "<Leader>fj", "", {
    noremap = true,
    callback = function(map)
        print(vim.inspect(map)) -- prints nil
    end,
})
```

Then proceed to visual select some lines and activate the registered keymap, `map` is going to be `nil`.

Meanwhile when using a string command
```lua
vim.api.nvim_set_keymap("v", "<Leader>fj", ":echo", {
    noremap = true,
})
```
it will write `'<,'>:echo` accordingly.

---

When using `nvim_create_user_command`, the callback is able to receive ex command data file f-args, range, etc, all stored in a single table. `nvim_set_keymap` could use a similar mechanism in order to handle range and still be future-proof if any other data needs to be received.

**Comment by ii14** [comment]
Key mappings don't have ranges, only count that you can access with `vim.v.count` or `vim.v.count1`.

Your second example does not mean they do, you're entering command line mode from the key mapping with `:`, and here commands can have ranges.

To get current visual selection you can use `line()` and `col()` with arguments `.` and `v`, and get visual mode with `mode()` to determine if it's a normal, line or block mode.

**Comment by matveyt** [comment]
The marks `<` and `>` specify _completed_ selection range. While selection/visual mode is still in progress reading from them is useless (unless you really want to know what _the previous_ selection range was). Hence you need to read current cursor position instead, as explained under `h getpos()`, I believe.

**Comment by gbrlsnchs** [comment]
I see, thank you for the explanations and the workarounds. I'll close this now.
