### ISSUE TITLE
prolog filetype detection

### ISSUE THREAD

**Issue by ignamartinoli** [neovim/neovim#19578]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

no idea

### Operating system/version

Gentoo Base System release 2.8

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

Gentoo Repository

### How to reproduce the issue

```
nvim example.pro
:set ft?
```

### Expected behavior

```
filetype=prolog
```

### Actual behavior

```
filetype=idlang
```

**Comment by clason** [comment]
Please check if Vim behaves the same, as we intentionally follow the same behavior.

**Comment by clason** [comment]
Vim behaves the same (8.2.5125), so please open this issue at vim/vim. We will then port any changes to the filetype detection.

**Comment by ignamartinoli** [comment]
alright, reporting there. thanks!

**Comment by ignamartinoli** [comment]
@clason the Vim issue has been completed: https://github.com/vim/vim/issues/10835
I will check later to report if it works and hope it gets merged

**Comment by clason** [comment]
already merged: https://github.com/neovim/neovim/pull/19684

**Comment by ignamartinoli** [comment]
thanks!
