### ISSUE TITLE
`laststatus=3` not working when specific tab commands are used

### ISSUE THREAD

**Issue by horriblename** [neovim/neovim#19591]
### Neovim version (nvim -v)

v0.7.2

### Vim (not Nvim) behaves the same?

not applicable, 'laststatus=3' only in neovim

### Operating system/version

Arch Linux

### Terminal name/version

konsole

### $TERM environment variable

xterm-256color

### Installation

Arch community repo

### How to reproduce the issue
Run these commands:
```
tabnew
tabprev
set laststatus=3
tabnext
echo 'this wont be printed'
```

### Expected behavior

Statusline and command-line area should be displayed normally

### Actual behavior

- when terminal window is focused, the statusline disappears
- command-line does not seem to be updating, e.g. `:echo 'hi'` doesn't do anything
- the terminal buffer seems to have one more line than it should when it is set to full height

**Comment by zeertzjq** [comment]
I cannot reproduce. Can you provide a screenshot?

**Comment by horriblename** [comment]
sorry, `:terminal` was not the source of the problem, it was a very specific combination of tab commands

```
tabnew
tabprev
set laststatus=3
tabnext
echo 'this won' t be printed'
```

**Comment by horriblename** [comment]
after doing all that and running :terminal, the buffer seems to think the statusline is free for the buffer to use, and the command line area stops working
![image](https://user-images.githubusercontent.com/59727193/182113905-ee6cf0a7-2caf-40dd-881f-2979010e1e1d.png)
