### ISSUE TITLE
Swap file not deleted when tab closed

### ISSUE THREAD

**Issue by kevinoid** [neovim/neovim#19593]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

8.2.4793

### Operating system/version

Debian GNU/Linux bookworm/sid (Linux 5.19.0-rc8)

### Terminal name/version

xfce4-terminal 1.0.4

### $TERM environment variable

xterm-256color

### Installation

Debian

### How to reproduce the issue

Open two files in separate tabs, close one of the tabs:

```sh
nvim -u NONE -p -c quit /tmp/a.txt /tmp/b.txt
```

Observe that swap files for both files still exist:

    ls ~/.local/share/nvim/swap/
    %tmp%a.txt.swp  %tmp%b.txt.swp

In another terminal, attempt to open the file which was closed in step 1:

    nvim /tmp/a.txt
    E325: ATTENTION
    Found a swap file by the name "~/.local/share/nvim/swap//%tmp%a.txt.swp"
              owned by: kevin   dated: Sun Jul 31 10:52:55 2022
             file name: /tmp/a.txt
              modified: no
             user name: kevin   host name: kevinolos
            process ID: 242686 (STILL RUNNING)
    While opening file "/tmp/a.txt"
                 dated: Sun Jul 31 10:49:23 2022
    
    (1) Another program may be editing the same file.  If this is the case,
        be careful not to end up with two different instances of the same
        file when making changes.  Quit, or continue with caution.
    (2) An edit session for this file crashed.
        If this is the case, use ":recover" or "vim -r /tmp/a.txt"
        to recover the changes (see ":help recovery").
        If you did this already, delete the swap file "/home/kevin/.local/share/nvi
    m/swap//%tmp%a.txt.swp"
        to avoid this message.
    
    Swap file "~/.local/share/nvim/swap//%tmp%a.txt.swp" already exists!
    [O]pen Read-Only, (E)dit anyway, (R)ecover, (Q)uit, (A)bort:

### Expected behavior

The swap file would be removed when the tab containing the file is closed and, as a result, the "Swap file ... already exists!" error would not occur.

### Actual behavior

The swap file is not deleted until nvim exits.

**Comment by kevinoid** [comment]
For reference, I am able to reproduce the issue with nvim 0.6.0, but not with 0.5.1 (or 0.5.0) suggesting that it was a regression in 0.6.0.

Also, possibly related: https://github.com/neovim/neovim/issues/4699

**Comment by zeertzjq** [comment]
`set nohidden`
