### ISSUE TITLE
Lua: table.unpack fails with "attempt to call field 'unpack' (a nil value)"

### ISSUE THREAD

**Issue by d3rhans** [neovim/neovim#19599]
### Neovim version (nvim -v)

0.8.0-dev commit 8952def50afa8308e044c0100e6d4fa367d0a9c2

### Vim (not Nvim) behaves the same?

no, vim doesn't have Lua

### Operating system/version

Fedora Linux Workstation 36

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

build from repo

### How to reproduce the issue

```
nvim --clean
:lua print(table.unpack({1,2}))
```

### Expected behavior

Unpack the table into two values and print them to the output

### Actual behavior

Raises the following error:

```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'unpack' (a nil value)  
stack traceback:
        [string ":lua"]:1: in main chunk
```

I can reproduced the error in v0.8.0-dev (latest commit), v0.7.3-dev, the latest prerelase but not in version 0.7.2 (shipped with Fedora). It also works when directly executed in Lua 5.4.4.

No other lua related issues and e.g. `table.insert` works as expected. I use `table.unpack` quite a few times in my config, which didn't casue issues before.

**Comment by zeertzjq** [comment]
Nvim only supports Lua 5.1
