### ISSUE TITLE
vim.lsp.buf.format({async=false}) does not behave as vim.lsp.buf.formatting_sync()

### ISSUE THREAD

**Issue by mateusz834** [neovim/neovim#19594]
### Neovim version (nvim -v)

v0.7.2

### Language server name/version

gopls v0.9.1

### Operating system/version

arch linux

### Steps to reproduce using "nvim -u minimal_init.lua"

I could not get it to work with minimal_init.lua (the vim.lsp.buf.format() was not avaliable there, couldn't figure out why)

1)
```
vim.api.nvim_create_autocmd({ 'BufWritePre' }, {
    pattern = {'*.go'},
    callback = function()
		vim.lsp.buf.format({async=false})
    end,
})
```

2)
```
vim.api.nvim_create_autocmd({ 'BufWritePre' }, {
    pattern = {'*.go'},
    callback = function()
		vim.lsp.buf.formatting_sync()
    end,
})
```

### Expected behavior

variant 1) and 2) (after :w, :wq) should format file, then save it.

### Actual behavior

When I write file (:w, :wq) using the variant 2) it is formatted and saved to disk correctly, but using variant 1) it is saved and after saving it is formatted, so the buffer is in modified state.

**Comment by mfussenegger** [comment]
Neovim 0.7.2 doesn't have the format function yet,  it's only in nightly. Are you sure you're testing the right thing?

**Comment by mateusz834** [comment]
That's weird, when I run nvim with clean config I don't see the vim.lsp.buf.format, but when I run it with my config it is available, and it work
![Screenshot_20220731_221848](https://user-images.githubusercontent.com/19653795/182043837-9609d89b-16e0-4ed6-940a-e1ee3eb9f0df.png)
.

**Comment by mateusz834** [comment]
Oh, it looks like it was polyfilled by one of my plugins.
