### ISSUE TITLE
Feature - Repeat-last-motion

### ISSUE THREAD

**Issue by ChrisPenner** [neovim/neovim#1960]
Certainly not high priority, but something to think about:

Dot-repeat is extremely useful, takes little mental energy, and is adaptable to any situation with no overhead (it automatically sets itself). These are all fantastic things. I often find myself wishing for a similar functionality that applies to motions instead. 

Some of these definitely exist already, for example ; and , for 'find' and 'till' motions, but in some cases it would be great to be able to punch in 5j then just mash a repeat key to scroll slightly faster. Yes I know that you can scroll by full or half pages, but in all of these cases there is increased mental overhead involved. What if I don't really know how far down I need to go until I start scrolling? Etc.

Are the logistics of doing this reasonable? I have no way to tell whether I'd actually use this extensively, but it feels right to me. (Also having dot-repeat work on more complex mappings and plugin-calls would be great, but that's a different issue altogether).

Cheers!

**Comment by justinmk** [comment]
Yes, repeat last "combo thing" (`]c`, `5j`, etc) should be pretty doable. Not sure if I mentioned that explicitly in https://github.com/neovim/neovim/issues/1025 but that issue more or less sits as a reminder of this feature request.

I've been resisting the urge to work on this since there are higher priorities, but I think about it pretty much every time I use n/vim :)

**Comment by ChrisPenner** [comment]
I'd say this is unique from #1025 , that issue is about improving dot-repeat, this one is about adding an analogous function for MOTION-repeat. Currently dot-repeat ignores motions which don't edit text (<c-u>,  f_, 5j, etc). It would be handy to have a key that repeats generic motions like these. 

As I think about it more, I'm not sure this would really have too many practical uses.
