### ISSUE TITLE
Virtual Lines beyond the end of the file cannot easily be shown

### ISSUE THREAD

**Issue by andrewferrier** [neovim/neovim#19605]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

No, vim doesn't have virtual line capability

### Operating system/version

macOS 12.1

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

Homebrew

### How to reproduce the issue

`nvim --clean <some large-ish file certainly longer than screen length>`

`:lua print(vim.api.nvim_create_namespace(''))`

(note the number of the namespace created, it's probably '1')

Also, press `g Ctrl-G`. Then change '137' to the 0-indexed last line of the file (e.g. if it has 138 lines, line 137)

`:lua vim.api.nvim_buf_set_extmark(0, 1, 137, 0, { virt_lines = {{{ 'xyz', 'ErrorMsg' }}}} )`

Press `G`. Note that the virtual text you've created above cannot be seen. 
Press `<Down>`. Note that the virtual text you've created above cannot be seen. 
Press `<Ctrl-D>`. Note that the virtual text you've created above cannot be seen. 
Press `<Ctrl-E>`. Note that the virtual text you've created above can *now* be seen. 

### Expected behavior

It's debatable exactly what scrolling motions should show this text I think, but I would have expected it would be easier to see the virtual text below the last line. For some context, this issue was raised because of this issue on `lsp_lines`: https://todo.sr.ht/~whynothugo/lsp_lines.nvim/16. In that particular case, my code was triggering some diagnostics on the last line of my file, but for ages I could not work out why I could not see them.

I would argue that if virtual text is present in the buffer, it's important to be able to see it. I don't think Ctrl-E/Ctrl-Y are commonly used ways of scrolling, yet they appear to be the only ways to show a diagnostic past the last line.

In my view, virtual lines *are* real lines - at least from the perspective of scrolling, so I would expect all the keymappings above to show them. I don't doubt this probably does complicate things, since in essence `<Down>` in this case would scroll the screen, but not move the line selected in the file. However, this seems like a reasonable thing to do in this case, where I'm at the end of the file and yet 'there is more'.

I'm not 100% certain everyone will agree this is a bug, but wanted to highlight this issue and see if there is a sensible way to address it.

### Actual behavior

Virtual text cannot be seen as described above.

**Comment by justinmk** [comment]
is this related to https://github.com/neovim/neovim/issues/17816 ? Can you try 0.8.x prerelease?

**Comment by andrewferrier** [comment]
Just tried on NeoVim v0.8.0-dev-737-g0b8bade49 on Arch. I see exactly the same behaviour for the same keymappings.

**Comment by andrewferrier** [comment]
It looks like #17816 is related to an error message being shown. I don't see any error and I believe the virtual text is added 'correctly'; it's just not 'useful' because I cannot easily see it.

**Comment by ddickstein** [comment]
Does this issue parallel https://github.com/neovim/neovim/issues/16166?

**Comment by WhyNotHugo** [comment]
@ddickstein Yes. The issue you linked is about virtual lines above the first line. This one is for virtual lines below the last line. I'm not sure how to address either, but ideally a fix could address both issues.

**Comment by WhyNotHugo** [comment]
There are also issues with scrolling. If the screen is 80characters wide, and I insert a 100-character-wide virtual line, scrolling to the right does not scroll the virtual text, making the last 20characters impossible to read.

That issue should probably be linked to these two as well, since they're all part of the same family.

**Comment by zeertzjq** [comment]
> That issue should probably be linked to these two as well, since they're all part of the same family.

No

**Comment by zeertzjq** [comment]
Fixed by #28044

**Comment by ddickstein** [comment]
Does that fix affect #16166?

**Comment by zeertzjq** [comment]
#16166 contains too much information.

**Comment by zeertzjq** [comment]
#16166 contains a lot of information, but yes.
