### ISSUE TITLE
migrate sourcehut builds?

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#19609]
## Problem

We use sourcehut for BSD CI. May need to migrate those jobs because the "dispatch" service of sourcehut is going away:

https://sourcehut.org/blog/2022-08-01-dispatch-deprecation-plans/

> Planned deprecation of dispatch.sr.ht
>
> Options for migration
>
> For GitHub integration, see [hottub](https://sr.ht/~emersion/hottub/).

related: https://github.com/neovim/neovim/issues/14083

"Did you just tell me to go fuck myself?"
"Yes, Bob, I believe I did."

## Solution

- Use the "third-party tool" [hottub](https://sr.ht/~emersion/hottub/) to continue building on sourcehut CI BSD systems.
- Alternatively, discontinue use of sourcehut (which seems to be what sourcehut wants).
    - We are a paying customer, apparently "raising prices" is not an option?

**Comment by arp242** [comment]
You can run BSD in GitHub actions with https://github.com/vmactions; here's what I use for fsnotify: https://github.com/fsnotify/fsnotify/blob/main/.github/workflows/test.yml#L30

Note that this runs as root by default, you may want to create a new local user similar to what I did in this PR: https://github.com/fsnotify/fsnotify/pull/479/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L42 – I created an issue for this, and I'll look into adding an option for this when I have some time.

Of course, fsnotify is a not much smaller and simpler project than NeoVim, but thus far it's worked fairly well for me; no idea if it also will for NeoVim.

**Comment by lewis6991** [comment]
The BSD builds fail all the time and they have never once helped me in development of a patch. I fail to see their value given how the failures are pretty much always ignored.

**Comment by bfredl** [comment]
I, for one, find the availability of the BSD builds to be useful.

> We are a paying customer, apparently "raising prices" is not an option?

getting in touch with drew might be an option. otherwise there are other services for BSD builds like we discussed in chat.

**Comment by dundargoc** [comment]
> However, I have a humble request for those who choose to migrate to these tools: if you are using a non-free platform like GitHub or GitLab (.com/EE) for your project’s primary hosting, please make a plan to migrate from builds.sr.ht. GitHub provides GitHub Actions and GitLab has its own CI system as well. If you’re not comfortable moving to SourceHut or another free-software platform, that’s your choice and we respect it — but it is a bit burdensome for us to accommodate you. Thank you for your understanding.

That pretty much eliminates hottub as a viable alternative in my eyes. It's impolite to stay when you're being shooed away.

**Comment by clason** [comment]
> The BSD builds fail all the time and they have never once helped me in development of a patch. I fail to see their value given how the failures are pretty much always ignored.

It's admittedly rare, but it did catch some changes that broke BSD builds. As long as we still care about those, we should make an effort to test that platform (and check whether failures are genuine of flake).

The alternative is to finally formalize a support matrix, with BSD demoted to a lower tier.

**Comment by dundargoc** [comment]
@clason https://github.com/neovim/neovim/pull/19615

**Comment by XVilka** [comment]
> You can run BSD in GitHub actions with https://github.com/vmactions

Interesting, this looks even better than builds.sr.ht - in addition to the FreeBSD, OpenBSD, and NetBSD, it also supports DragonFlyBSD and Solaris.

**Comment by dundargoc** [comment]
vmactions is decent but not great. I think it could work as a stopgap solution but not entirely convinced we can rely on it long term. See: https://github.com/neovim/neovim/pull/19616#issuecomment-1203185858
