### ISSUE TITLE
Cursor highlights have stopped working

### ISSUE THREAD

**Issue by lervag** [neovim/neovim#19607]
### Neovim version (nvim -v)

v0.8.0-dev-749-g86110ec933

### Vim (not Nvim) behaves the same?

gvim does not, vim does (v9.0.0000)

### Operating system/version

Arch Linux

### Terminal name/version

rxvt-unicode v9.30

### $TERM environment variable

xterm-256color

### Installation

AUR (neovim-git)

### How to reproduce the issue

Do `nvim --clean -u test.vim` with below `test.vim`.

```vim
set nocompatible
syntax enable

set termguicolors

highlight Cursor guibg=green
highlight CursorIM guibg=blue
highlight CursorColumn guibg=grey
highlight CursorLine guibg=pink
highlight CursorLineNr guibg=black
highlight TermCursor guifg=red guibg=green
highlight TermCursorNC guifg=blue guibg=red
highlight iCursor guibg=red
highlight rCursor guibg=yellow
highlight vCursor guibg=blue
highlight link lCursor Cursor
highlight link nCursor Cursor

set guicursor=a:block
set guicursor+=n:Cursor
set guicursor+=o-c:iCursor
set guicursor+=v:vCursor
set guicursor+=i-ci-sm:ver30-iCursor
set guicursor+=r-cr:hor20-rCursor
set guicursor+=a:blinkon0
```

### Expected behavior

The cursor color should respect the highlight rules.

### Actual behavior

The color does not change from the terminal cursor color.

----

This was not an issue for me until a relatively recent system update. I acknowledge that it can be related to my terminal. I also tested with `xterm`, but I have the same problem there.

**Comment by lervag** [comment]
`:checkhealth` reports the following:

```
nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='rxvt-xpm'
```

**Comment by clason** [comment]
You're not setting `termguicolors`, so the `guibg` and friends are not used?

**Comment by lervag** [comment]
True, but that's a typo in the issue description. The problem persists with `set termguicolors`.

**Comment by zeertzjq** [comment]
I cannot reproduce with rxvt-unicode v9.30.

**Comment by lervag** [comment]
Huh, it seems there was an issue with my `TERM` environment variable. I don't know what changed, probably something with rxvt. In any case, when I change from what I used to have, `xterm-256color`, to `rxvt-256color`, things work as expected.

Sorry about the noise!

**Comment by mg979** [comment]
For me it's an issue. `guicursor` is broken with `TERM=xterm-256color`. I'm using `xfce4-terminal-emulator`.

Strange that if I set it to, for example, `xterm-kitty` it works (still when using `xfce4-terminal-emulator`). In kitty it works.

In NVIM 0.7.2 it worked.
