### ISSUE TITLE
api-info uses Dictionary type without declaring it

### ISSUE THREAD

**Issue by osa1** [neovim/neovim#1961]
`--api-info` declares types in `types` list. Previously it was declaring `Buffer`, `Tabpage`, `Window`, and those were used in the API function declarations. It looks like with some of the recent patches the type `Dictionary` is started being used, but it's not declared in `types` part of API info. This is causing our RPC API generator to fail.

Name of the function that uses `Dictionary`: `vim_get_color_map`.

**Comment by osa1** [comment]
RPC functions and `--api-info` is generated automatically using some tools, right? I believe that RPC function is generated from `vim_get_color_map` function added in this commit: https://github.com/neovim/neovim/commit/f468fb70cb6d82dca5b9a23706b4b6b70a3beab6. Could it be because the tool that generates the API is not that smart to add new types to `types` list in `--api-info`?

**Comment by equalsraf** [comment]
Yes the metadata function table is generated in scripts/msgpack-gen.lua and gedeclarations.lua.
It seems right now the "types" are set manually in `src/nvim/api/private/helpers.c init_type_metadata()` and Dictionay is missing.

My own generators just started to fail on this, although I find it fine to skip unsupported functions until I really need them.

**Comment by tarruda** [comment]
The `types` list is just for extension types that don't have a native msgpack representation.

**Comment by bfredl** [comment]
Well, before this commit there already was functions with return types declared  `Array` (and even `Array(Integer, 2)` ), which are note in this metadata dictionary either. I think the purpose of `init_type_metadata` is for nvim extension types (`Buffer` etc) , which might be added at any time, in constast wih Integer/Array/Dictionary etc which map to msgpacks builtin types and therefore are "fixed". 
(As plain `Dictionary` and `Array` are not elementwise type-safe anyway, in my own api client I just treat them like `Object` in return value position)

**Comment by equalsraf** [comment]
So Dictionary is a plain msgpack object. There also seems to be a DictionaryOf macro, would that be preferable in the case of vim_get_color_map?

@tarruda looking at the extended types (Tabpage,Buffer,Window), do we really need extended type wrapping (msgpack serialized inside msgpack)? It is not like we are actually passing anything special in there, all these types map to int64_t.

Does the value for each type in the metadata info match the extended type id?

Are we writing down this stuff somewhere?

**Comment by tarruda** [comment]
> So Dictionary is a plain msgpack object. There also seems to be a DictionaryOf macro, would that be preferable in the case of vim_get_color_map?

The {Dictionary,Array}Of macros are just a helpers to generate API metadata static languages with generic/templates. It doesn't matter for dynamic languages like python, but java for example, might be able to generate a wrapper for `vim_get_buffers` as `Array<Buffer> vimGetBuffers()`. The generated msgpack wrappers are still going to return plain map instances, but the metadata will contain extra information.

> @tarruda looking at the extended types (Tabpage,Buffer,Window), do we really need extended type wrapping (msgpack serialized inside msgpack)? It is not like we are actually passing anything special in there, all these types map to int64_t.

Yes, but using msgpack extended types is better  because without it we would need some other way to distinguish plain integers from Buffer/Window/Tabpage ids.

> Does the value for each type in the metadata info match the extended type id?

Yes. [This](https://github.com/neovim/python-client/blob/master/neovim/api/nvim.py#L56-L62) is how the python client associates type ids with its own classes for Buffer/Window/Tabpage.

> Are we writing down this stuff somewhere?

I have wrote some basic information in the [help](http://neovim.org/doc/user/msgpack_rpc.html#msgpack-rpc), but it needs more details.

**Comment by equalsraf** [comment]
> Yes, but using msgpack extended types is better because without it we would need some other way to distinguish plain integers from Buffer/Window/Tabpage ids

I assumed they would use the metadata type names as hints for this.

> I have wrote some basic information in the help, but it needs more details.

ups, completely missed that, thanks.

**Comment by tarruda** [comment]
> I assumed they would use the metadata type names as hints for this.

While this could be done(it was like that before nvim used msgpack v5), we would lose some flexibility:  it would not be possible to have a function that accepts/returns container with objects of mixed types, for example.

**Comment by equalsraf** [comment]
> While this could be done(it was like that before nvim used msgpack v5), we would lose some flexibility: it would not be possible to have a function that accepts/returns container with objects of mixed types, for example.

That case makes sense, but it just seems over-engineered since the only actual types we have right now are int64.

**Comment by tarruda** [comment]
> That case makes sense, but it just seems over-engineered since the only actual types we have right now are int64.

Not sure what you mean by over-engineered, but using msgpack ext type is actually simpler/cleaner than inferirng deserialization types based on metadata names: All we need is to pass the msgpack library a callback that handles deserialization based on type codes.

At least for the python client, I remember that the deserialization function was much uglier without the ext type, without being flexible as it is now.

**Comment by osa1** [comment]
> I have wrote some basic information in the help, but it needs more details.

Thanks @tarruda , this is really helpful.

With this new help page my problem is solved, feel free to close this.
