### ISSUE TITLE
Mouse enabled by default trhough #19290

### ISSUE THREAD

**Issue by antenore** [neovim/neovim#19625]
More a flame as I don't have a proposal

> - Oceania has always been at war with Eastasia. Nvim has always enabled 'mouse' by default.

…

>    - Right-click shows a popup menu with: `Cut`, `Copy`, `Paste`, `Disable mouse`
        - The `Disable mouse` item shows `:help default-mouse` which explains how to disable mouse permanently.

_Originally posted by @justinmk in https://github.com/neovim/neovim/issues/19290#issuecomment-1186515224_

TL;DR many people like me, don't use the right click, so having a useful tooltip in a context menu, doesn't really help.

Honestly I was quite surprised and frustrated to discover that the mouse was enabled, especially because I almost never use the mouse, except to quickly switch between windows when cycling with other shortcuts, like when using `Alt+Tab` is less convenient.

It wasn't hard to find out how to disable the mouse. But to find out about the right-click 'improvement' I had to search the commit log, read the PR, and learning a bit about the new features around the mouse support, and finally right-click to see the `Disable mouse` menu entry.

I think this would frustrate many normal users that are habit to don't use the mouse, and it's a quite bad usability feature.

Still, it's not clear why you are pushing for mouse support `on` by default and what I'm loosing if I disable it. It's quite intimidating honestly, that is another usability error (never intimidate users).

I don't have a proposal, sorry :-\ but I feel this is quite annoying and wrong in general.

**Comment by bfredl** [comment]
> It wasn't hard to find out how to disable the mouse. But to find out about the right-click 'improvement' I had to search the commit log, read the PR, and learning a bit about the new features around the mouse support, and finally right-click to see the Disable mouse menu entry.

Not sure I see the point here. If you prefer to not use the `'mouse'` feature, which as you say is easy to disable, how is it a problem for you that neovim can displays a right-click menu?

> I think this would frustrate many normal users that are habit to don't use the mouse, and it's a quite bad usability feature.

If your habit is not use the mouse at all, then it doesn't matter if 'mouse' feature is active or not. (If you meant to claim "most users prefer the terminal emulators mouse feature", that is a claim we already have discussed countless times before)

Needs a concrete proposal to stay open.
