### ISSUE TITLE
":lua vim." completion in cmdwin (cmdline window)

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#19623]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

did not test

### Operating system/version

archlinux

### Terminal name/version

alacritty 0.10.1 + tmux 3.3a

### $TERM environment variable

tmux-256color

### Installation

pacman -S neovim

### How to reproduce the issue

* `nvim --clean`
* type `q:` to enter command-line window
* type `lua vim.<c-x><c-v>`

### Expected behavior

when completion starts, the original text remains as is

### Actual behavior

when completion starts, the original text, `vim.`, will be eaten.

**Comment by justinmk** [comment]
ctrl-x ctrl-v is specifically for completing Vimscript. From `:help i_CTRL-X_CTRL-V` is under :help compl-vim`.

That's pretty special case, and it could do something useful in e.g. Lua scripts, but what should it do? Aliasing to omnicompletion isn't useful, and also defeats the use-case where you're writing Vimscript within a Lua string:

```
  local a = [[
    ed
    --^ cursor here, type ctrl-x ctrl-v
  ]]
```

**Comment by haolian9** [comment]
hi, i think you mistook my previous commit, let's ignore it for a while.

the main problem in this issue is the completion in cmdwin is broken, while in cmdline it works fine.
for example, `nvim --clean`, in the cmdline, when type `:lua vim.<tab>` I get `:lua vim.F`; in the cmdwin, type `:lua vim.<tab>` I get `:lua F`. and i think the completion is done by `<c-x><c-v>` either in the cmdline or the cmdwin.

my previous comment is just a workaround to make the lua completion work, and get me `:lua vim.F`

**Comment by zeertzjq** [comment]
The implementation of Lua cmdline completion is a bit hacky. Need to find a way to make it less hacky, but not at the cost of performance.

**Comment by louisroymond91** [comment]
Really
