### ISSUE TITLE
unable to assign vim.fn to local variable in function init.lua

### ISSUE THREAD

**Issue by h4ppyr0gu3** [neovim/neovim#19634]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

unable to check 

### Operating system/version

Arch linux

### Terminal name/version

alakritty

### $TERM environment variable

xterm-256color

### Installation

pacman

### How to reproduce the issue

create lua file and map a key to print function
```lua
vim.api.nvim_set_keymap('n', 'yd', ':lua print(file_path())')

function file_path()
-- this command works fine
  local working_directory = vim.api.nvim_command("pwd")

-- this returns nil
  full_path = vim.fn.expand("%")

-- gsub throws error expected string in argument #2
  local path = string.gsub(full_path, working_directory, "")
end

```

### Expected behavior

should set the variable to the value returned by vim.fn call

### Actual behavior

returns nil

**Comment by clason** [comment]
Your `nvim_set_keymap` is wrong -- it _requires_ four arguments (`nvim_foo` API functions have stronger typing than typical Lua functions as they have to be consistent across all languages they're exposed to).

**Comment by clason** [comment]
I don't think your expectation is correct -- you seem to think that `expand` returns the _absolute_ path, which it doesn't (necessarily). Use `fnamemodify` to convert to absolute path if needed.

**Comment by clason** [comment]
And to be clear: to understand your actual problem, you need to pay attention to the error message, which tells you that your _first_ command is wrong -- which is not surprising, since `pwd` _prints_ the working directory (instead of returning it to be bound by your variable). Use `vim.fn.getcwd()` instead.

**Comment by h4ppyr0gu3** [comment]
thank you for your time and thanks for the correction @clason
