### ISSUE TITLE
Terminal window wont't clear after exiting using Alacritty

### ISSUE THREAD

**Issue by tiagodfer** [neovim/neovim#19633]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

No, 9.0.99

### Operating system/version

Linux, Gentoo, X11, Glibc

### Terminal name/version

Alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

Gentoo main repos

### How to reproduce the issue

nvim --clean
once insiede vim, exit with :q

### Expected behavior

Exit NVIM and clear the terminal window.

### Actual behavior

Nothing is cleared and everything was appearing in NVIM persists in the terminal.
Issue can be mitigated exporting 'xterm-256color' as TERM. But I don't see why it should be done this way if I have the correct alacritty terminfo installed in my system. Programs like Htop, and even vim, clears the window after exiting as expected.

**Comment by justinmk** [comment]
search existing (closed) issues

**Comment by tiagodfer** [comment]
Justin,
I searched before posting and searched again as you told. But, due to my lack of expertise, I couldn't find anything. Could you point me towards the right direction?
