### ISSUE TITLE
vim.cmd.wincmd: Command cannot accept a count

### ISSUE THREAD

**Issue by Supreeeme** [neovim/neovim#19662]
### Neovim version (nvim -v)

0.8.0-dev-782-g85ad0e6b43

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Arch Linux

### Terminal name/version

foot 1.12.1

### $TERM environment variable

foot

### Installation

AUR

### How to reproduce the issue

```
nvim --clean
:lua vim.cmd.wincmd{args={'_'}, count=8}
```

### Expected behavior

`vim.cmd.wincmd` should accept a count just like `:wincmd` does

### Actual behavior

`vim.cmd.wincmd` throws the error `Command cannot accept a count`

**Comment by zeertzjq** [comment]
This is working as intended. `:wincmd` does not accept a count, only a range.

**Comment by Supreeeme** [comment]
That's a bit confusing, when `:h wincmd` explicitly refers to it as a count, not a range.

**Comment by zeertzjq** [comment]
Maybe this can be improved, by, for example, trying `count` as `range` if command doesn't support a count?

**Comment by famiu** [comment]
> Maybe this can be improved, by, for example, trying `count` as `range` if command doesn't support a count?

That honestly seems like an antipattern to me. `nvim_cmd` is explicitly structured and `count` and `range` are different attributes for a reason. I think that using one implicitly in place of the other can lead to unintuitive and unwanted behavior in some cases. Fixing `:wincmd` docs seems like better idea to me.
