### ISSUE TITLE
The mode() function gets the wrong mode

### ISSUE THREAD

**Issue by yyy33** [neovim/neovim#19666]
### Neovim version (nvim -v)

NVIM v0.7.2 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Arch linux

### Terminal name/version

alacritty 0.10.1 ()

### $TERM environment variable

xterm-256color

### Installation

system package manager

### How to reproduce the issue

1. touch a new file `~/test.lua`
```
vim.cmd[[
au BufLeave term://* stopinsert
au TermOpen term://*  echom mode()
]]
vim.keymap.set({'', '!', 't'}, '<c-t>', [[<cmd>exe 'buffer!' '+terminal' nvim_create_buf(v:true, v:false)<cr>]])

```
2. run `nvim --clean` open nvim
3. source the `~/test.lua`
4. type `<c-t>` open a terminal ,At this time, the print mode is `n`, which is correct
5. type `i` into terminal mode
6. type `<c-t>` open a new terminal,The mode printed at this time is `t`, which is wrong, obviously the mode should also be `n`

### Expected behavior

The pattern printed in step 6 should be `n` instead of `t`

### Actual behavior

The message printed in step 6 is `t`

**Comment by zeertzjq** [comment]
`stopinsert` does not stop Terminal mode immediately.

**Comment by yyy33** [comment]
> `stopinsert` does not stop Terminal mode immediately.

thank you
