### ISSUE TITLE
Neovim not building for Mac 

### ISSUE THREAD

**Issue by ulisses-cruz** [neovim/neovim#19675]
### Neovim version (nvim -v)

0.8 commit 18766e74

### Vim (not Nvim) behaves the same?

don't know

### Operating system/version

macOS 12.5 (21G72) M1

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

- git clone https://github.com/neovim/neovim.git
- cd neovim
- make CMAKE_BUID_TYPE=Release

### Expected behavior

Build completed.

### Actual behavior

```sh
-- Using NVIM_VERSION_MEDIUM: v0.8.0-dev-792-g18766e742
[341/345] Linking C executable bin/nvim
FAILED: bin/nvim 
...
ld: warning: ignoring file /opt/local/lib/libintl.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /opt/local/lib/libiconv.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_libiconv", referenced from:
      _readfile in fileio.c.o
      _buf_write_bytes in fileio.c.o
      _my_iconv_open in mbyte.c.o
      _iconv_string in mbyte.c.o
  "_libiconv_close", referenced from:
      _readfile in fileio.c.o
      _buf_write in fileio.c.o
      _my_iconv_open in mbyte.c.o
      _convert_setup_ext in mbyte.c.o
  "_libiconv_open", referenced from:
      _my_iconv_open in mbyte.c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
make: *** [nvim] Error 1
```

**Comment by clason** [comment]
I cannot reproduce that. In particular:
> [341/345] Linking C executable bin/nvim

That number seems wrong; it should be 376 instead of 345. Are you sure you are building from a fresh repo? What are your `clang` and `cmake` versions?

Also, can you make sure your kitty is an ARM build (and maybe test with the native Terminal.app or iTerm2)?

**Comment by clason** [comment]
It looks like you're mixing up (or switching from) homebrew and repo builds. Try removing or unlinking `libiconv` and `libintl` before (re)building.

**Comment by ulisses-cruz** [comment]
> Are you sure you are building from a fresh repo? 

yes

> What are your clang and cmake versions?
```sh
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

```sh
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```sh
cmake version 3.24.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
> maybe test with the native Terminal.app or iTerm2?

Used Terminal.app and got the same result

**Comment by clason** [comment]
Do you have `ninja` installed?

**Comment by ulisses-cruz** [comment]
>  Do you have ninja installed?

```sh
$ which ninja
/opt/homebrew/bin/ninja
```

**Comment by clason** [comment]
Then I can only repeat my earlier recommendation:
> It looks like you're mixing up (or switching from) homebrew and repo builds. Try removing or unlinking libiconv and libintl before (re)building.

**Comment by ulisses-cruz** [comment]
> It looks like you're mixing up (or switching from) homebrew and repo builds. Try removing or unlinking libiconv and libintl before (re)building.

```sh
$ brew remove libiconv 
Error: No such keg: /opt/homebrew/Cellar/libiconv
```

```sh
$ brew remove libintl                                                                                                                       
Error: No available formula with the name "libintl". Did you mean libntlm, libnl, libidl, libmnl, libnsl, libgnt or libical?
```

**Comment by clason** [comment]
OK, where are those coming from then
> ld: warning: ignoring file /opt/local/lib/libintl.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
> ld: warning: ignoring file /opt/local/lib/libiconv.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

**Comment by ulisses-cruz** [comment]
I've renamed those files. Now it is showing:
```sh
[372/376] Linking C executable bin/nvim
FAILED: bin/nvim 
```

and in the end:

```sh
undef: _libiconv_open
undef: _libiconv
undef: _libiconv_close
Undefined symbols for architecture arm64:
  "_libiconv_open", referenced from:
      _my_iconv_open in lto.o
  "_libiconv", referenced from:
      _readfile in lto.o
      _my_iconv_open in lto.o
      _string_convert_ext in lto.o
      _buf_write_bytes in lto.o
  "_libiconv_close", referenced from:
      _readfile in lto.o
      _buf_write in lto.o
      _utf_find_illegal in lto.o
      _my_iconv_open in lto.o
      _convert_setup_ext in lto.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
make: *** [nvim] Error 1
```

Would you like the whole output?

**Comment by clason** [comment]
No, you should find out where they come from and remove those libraries (or the directory from your relevant `PATH`s).

You also need to `make distclean` after such changes before trying to build again.

**Comment by ulisses-cruz** [comment]
Ok @clason. I can confirm that was the problem. Some libraries that were installed by another program were interfering with the build.
Fixing that made de build work. 
Thanks.
You can close this issue if you want.
