### ISSUE TITLE
problem inserting suggested code with github copilot plugin

### ISSUE THREAD

**Issue by dbarrosop** [neovim/neovim#19683]
### Neovim version (nvim -v)

0.8.0-dev commit db6e93c48df551e2906c9e0f4472f9e54cea3dd9

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macos 12.5

### Terminal name/version

tmux

### $TERM environment variable

screen-256color

### Installation

nixpkgs

### How to reproduce the issue

Install copilot and then:

``` lua
    vim.keymap.set('i', '<C-J>', 'copilot#Accept("\\<CR>")', {
        expr = true,
        silent = true,
        script = true,
    })

    vim.g.copilot_no_tab_map = true
```

### Expected behavior

Inserting suggestions in insert mode with <C-J> should work without adding extra noise.

### Actual behavior

Since commit db6e93c48df551e2906c9e0f4472f9e54cea3dd9 inserting a github copilot suggestion with <C-J> inserts some noise if there is trailing text in the same line as the suggestion. For instance, if you start with the following golang code (which isn't correct I know):

``` golang
package main

func main() {
	println("Hello, world.")
	""
}
```

and place the cursor before the quotes and type `if `, copilot will suggest some code but if I press <C-J> it will add some garbage to it:

``` golang
package main

func main() {
    println("Hello, world.")
    if kDkDtrue {
        println("true")
    } else {
        println("false")
    }""
}
```

In the previous commit 9f5d5aa3da30aab40bbb38fddfc70257444d50a8, it works fine and the resulting code looks like:

```go
package main

func main() {
    println("Hello, world.")
    if true {
        println("true")
    } else {
        println("false")
    }
}
```

This issue doesn't occur if the cursor is in the end of the line.

**Comment by bfredl** [comment]
remove the `\\` from the rhs.

**Comment by dbarrosop** [comment]
@bfredl thanks for the quick response. Unfortunately that didn't help. Would you mind reopening the issue?

Thanks!

**Comment by dbarrosop** [comment]
For the sake of completeness and to ensure I didn't misunderstand anything this was the configuration I tested after the suggestion:

``` lua

    vim.keymap.set('i', '<C-J>', 'copilot#Accept("<CR>")', {
        expr = true,
        silent = true,
        script = true,
    })
    vim.keymap.set('i', '<C-k>', '<Plug>(copilot-previous)', {})
    vim.keymap.set('i', '<C-l>', '<Plug>(copilot-next)', {})

    vim.g.copilot_no_tab_map = false
```

**Comment by bfredl** [comment]
hmm, might need `replace_termcodes=false` option, which should restore the old behavior.

**Comment by dbarrosop** [comment]
ok, `replace_keycodes = false` did the trick. Thanks a lot for the help. Really appreciated.
