### ISSUE TITLE
Highlight on yank receives "visual=true" for text object operations

### ISSUE THREAD

**Issue by asmodeus812** [neovim/neovim#19687]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

No

### Operating system/version

WSL

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

Github releases page

### How to reproduce the issue

Having installed and configured treesitter and treesitter text objects plugins only

```Lua
local status_ok, configs = pcall(require, "nvim-treesitter.configs")
if not status_ok then
    vim.notify("Unable to load of find plugin nvim-treesitter", vim.log.levels.ERROR)
    return
end

vim.cmd [[
      augroup GENERAL
        autocmd!
        autocmd TextYankPost * lua require('vim.highlight').on_yank({timeout = 250, on_visual = false})
      augroup END
]]

configs.setup({
    textobjects = {
        select = {
            enable = true,
            keymaps = {
                ["aa"] = "@parameter.outer",
                ["ia"] = "@parameter.inner",
                ["af"] = "@function.outer",
                ["if"] = "@function.inner",
                ["ac"] = "@class.outer",
                ["ic"] = "@class.inner",
            },
        },
    }
})
```

Having the following (dummy) piece of code
```c
int main(int argc, char **argv) {
  int k = 12;
  k++;
  printf("Hello, World!\n");
  printf("Hello, kval! %d\n", k);
  printf("Hello, argc! %d\n", argc);
  for (size_t i = 0; i < argc; i++) {
    printf("%s\n", argv[i]);
  }
  fflush(stdout);
  return 0;
}
```

Executing yaw, this is what vim.highlight reports for vim.v.event
```Lua
{
  inclusive = true,
  operator = "y",
  regcontents = { " main" },
  regname = "",
  regtype = "v",
  visual = false
}
```

Executing yaf, this is what vim.highlight reports for vim.v.event
```Lua
{
  inclusive = true,
  operator = "y",
  regcontents = { "int main(int argc, char **argv) {", "  int k = 12;", "  k++;", '  printf("Hello, World!\\n");', '  pr
intf("Hello, kval! %d\\n", k);', '  printf("Hello, argc! %d\\n", argc);', "  for (size_t i = 0; i < argc; i++) {", '
printf("%s\\n", argv[i]);', "  }", "  fflush(stdout);", "  return 0;", "}" },
  regname = "",
  regtype = "v",
  visual = true
}
```

Note: The only significant difference being the **visual = true** - which is incorrect since no visual mode was ever entered

### Expected behavior

When yanking custom object, the event will not mark the action/operation as if it was being done in visual mode

### Actual behavior

When yanking the function body the highlight is not observed, as compared to yanking the word which does correctly highlight it. **Obviously happening since the auto command configures visual = false but the even data receives visual = true**. The following observations were made - The event received by vim.highlight is as if it was done in visual mode. Excerpt from vim.highlight which demonstrates why **yaf** highlight does not work with the above auto command.

```Lua
opts = opts or {}
  local event = opts.event or vim.v.event
  local on_macro = opts.on_macro or false
  **local on_visual = (opts.on_visual ~= false)**

  if not on_macro and vim.fn.reg_executing() ~= '' then
    return
  end
  if event.operator ~= 'y' or event.regtype == '' then
    return
  end
  **if not on_visual and event.visual then
    return
  end**
```

**Comment by clason** [comment]
So the bug here is that **treesitter** text objects receive `event.visual=true` -- this is unrelated to the "highlight on yank" function, and since builtin text objects behave correctly, this is an issue you should report at https://github.com/nvim-treesitter/nvim-treesitter-textobjects.

(If it turns out after investigation there that this is an upstream bug, we can reopen with more details.)
