### ISSUE TITLE
Add vim.lsp.util.stylize_markdown support for headings and inline code blocks

### ISSUE THREAD

**Issue by nermalneedscoffee** [neovim/neovim#19694]
### Feature already in Vim?

No

### Feature description

Consider this sample of a call to `open_floating_preview` which calls `stylize_markdown` for highlight regions.

![image](https://user-images.githubusercontent.com/35051569/183691989-b1c87253-f96e-4b22-8c89-63cd03e331ba.png)

The heading and inline code remain as is. Instead, headings should use the intense style or something of that fashion provided by a highlight group. Inline code should also have color highlighting as with regular code blocks.

**Comment by justinmk** [comment]
Fixed by https://github.com/neovim/neovim/pull/19377 . Any remaining issues are covered by https://github.com/neovim/neovim/issues/20857
