### ISSUE TITLE
freeo is gone?

### ISSUE THREAD

**Issue by jolux** [neovim/neovim#1969]
The contributor chosen to design and finalize the default color scheme hasn't made any contributions to anything since October. Should we be concerned that they aren't active any more?

https://github.com/freeo

**Comment by justinmk** [comment]
He was active in December. Anyways, we didn't commit to anything...

**Comment by jolux** [comment]
I thought it was decided as the default in the color schemes thread?

**Comment by justinmk** [comment]
I said it would probably be the default, with the assumption that there would be a period of collaboration to fix any outstanding issues. The palette needs some work: it has too many colors, lacks balance, and a vertiginous vacillation between high and low contrast. 

The priority is to choose a default theme that is pleasant and usable for all platforms, in terminal and gui. Matching the Neovim colors is secondary. I would prefer both. If we can work on kalisi to make it a really strong theme, that would be ideal. Creating a strong colorscheme is time consuming, so it would save a lot of time if some people could work on that :)

**Comment by jolux** [comment]
I can help work on it. I program in multiple different languages from day to day so I could test what it looks like and I also have decent visual taste if I do say so myself.

**Comment by justinmk** [comment]
I watch the https://github.com/freeo/vim-kalisi repo, and any issues created there. FYI the `zS` mapping from https://github.com/tpope/vim-scriptease could be useful.

**Comment by jolux** [comment]
I forked the repo and I’m making an attempt to address the current issues.

**Comment by freeo** [comment]
Just wanted to let you know, still there! Been busy lately, but nothing to worry about.

> it has too many colors, and a vertiginous vacillation between high and low contrast. It lacks balance.

It seems you had a closer look at the colorscheme by now. Can you elaborate on the quote by opening an issue?
