### ISSUE TITLE
\<Ignore> turns into gibberish when returned from Lua

### ISSUE THREAD

**Issue by FallenWarrior2k** [neovim/neovim#19706]
### Neovim version (nvim -v)

v0.8.0-dev-809-gb4b22318a1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

AUR: neovim-git

### How to reproduce the issue
```
nvim --clean
inoremap <expr> <F5> luaeval("vim.api.nvim_replace_termcodes('<Ignore>', true, true, true)")
```

### Expected behavior

It should behave the same as in Vimscript, i.e. the above mapping should have the same effect as `inoremap <F5> <Ignore>`.

### Actual behavior

It inserts `<80>ý5` (in hex: `c2 80 c3 bd 35 0a`) into the buffer.

`vim.keymap.set("i", "<F5>", function() return "<Ignore>" end, { expr = true })` does not appear to have this issue. However, in my use case, I'm not creating the `\<Ignore>` sequence myself; it is returned to me by a plugin-provided Vimscript function that I call in my handler.

**Comment by zeertzjq** [comment]
Either escape `<` as `<lt>`, or do not call `nvim_replace_termcodes` ad all.

**Comment by zeertzjq** [comment]
> it is returned to me by a plugin-provided Vimscript function that I call in my handler.

In this case, if you are using `vim.keymap.set()`, pass `replace_keycodes = false` in opts.

**Comment by FallenWarrior2k** [comment]
Ah okay, that worked, thank you.

Did the behavior of this option change since 0.7.2? Because I tried switching to that as a test, and it stopped working. I tested with the following file:
```vim
function! KeycodeTest()
    return "\<Ignore>"
endfunction

inoremap <expr> <F5> KeycodeTest()

lua vim.keymap.set("i", "<F6>", vim.fn["KeycodeTest"], { expr = true })
lua vim.keymap.set("i", "<F7>", vim.fn["KeycodeTest"], { expr = true, replace_keycodes = false })
```

On neovim-git, F5 and F7 work as expected. On neovim 0.7.2, F7 does the same as F6.

**Comment by zeertzjq** [comment]
Oh, it seems `replace_keycodes = false` actually had no effect in v0.7.2, because it was cleared before its value was checked.

**Comment by zeertzjq** [comment]
In this case, you can use `nvim_set_keymap` instead of `vim.keymap.set()` in v0.7.2.

**Comment by FallenWarrior2k** [comment]
All right, thank you for the quick help.
