### ISSUE TITLE
Coverity glitch lost information

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#1970]
Yesterday, coverity builds were being queued up for a long time (seems some kind of maintenance/update was going on at the server side).

Today, **91**! new defects have been reported.
Looking into the details, it seems mostly all already known issues have been retagged as "newly detected".
This is, it appears we have lost "continuity" information from previous situation. It's like we had submitted the project anew. "Eliminated" and "Dismissed" count seem to be ok, but "Fixed" count has gone down to 0.

I've written to them. Let's see what they say.

**Comment by elmart** [comment]
Their response:
```
Hi,

We had an issue with our server, mainly because we upgraded our back-end
APIs.
The issue has been fixed, and updates stats are available at
https://scan.coverity.com/projects/2227?tab=overview


Thanks

Dakshesh Vyas € Technical Manager
dvyas@coverity.com <mailto:jdough@coverity.com> € 185 Berry Street, Suite
6500, San Francisco CA 94017
Office: +1 (415) 935 2957
scancoverity.com <http://www.coverity.com/> www.coverity.com
<http://www.coverity.com/> € Twitter: @coverity @coverityScan
Coverity by Synopsys

```
I've checked it and everything seems to be ok.
Closing.

**Comment by aktau** [comment]
Nice. Thanks for looking into it @elmart :).
