### ISSUE TITLE
xdg-open <url> not working

### ISSUE THREAD

**Issue by pogopaule** [neovim/neovim#19724]
### Neovim version (nvim -v)

v0.7.2 Release

### Vim (not Nvim) behaves the same?

no, vim 9.0.150

### Operating system/version

Ubuntu 22.04.1 LTS

### Terminal name/version

alacritty 0.11.0-dev (b16fe125)

### $TERM environment variable

xterm-256color

### Installation

Linuxbrew

### How to reproduce the issue

nvim --clean

:!xdg-open http://example.org

### Expected behavior

The browser opens http://example.org

### Actual behavior

Just 
```
:! xdg-open http://example.org

Press ENTER or type command to continue
```
is shown an nothing else happens, example.org is not opened in the browser.

Whereas when I type `xdg-open http://example.org` in my terminal, the website is opened.
Also, when I type `:! xdg-open some/dir/some-file.xyz` in nvim the file gets opened in a GUI editor.

**Comment by evanrittenhouse** [comment]
This works for me, maybe it's a versioning issue or something? I'm on NVIM 0.7.2 (release) as well, so not sure why it wouldn't work for you.

**Comment by pogopaule** [comment]
Thank you for your quick reply! Since it has become second nature, I didn't realize that I always work within tmux. Outside of tmux this issue does not exist. Investigating further...

**Comment by evanrittenhouse** [comment]
No problem! Although, I'm seeing that it's working both inside and outside of tmux. Bizarre

**Comment by pogopaule** [comment]
@evanrittenhouse FYI: I made a mistake. xdg-open does not work inside nvim regardless of tmux.

**Comment by evanrittenhouse** [comment]
Mine is also 1.1.3. Maybe it's an Alacritty setting that blocks pop-ups or something?

**Comment by pogopaule** [comment]
Thanks!
Thought so too. But it also happens with the default Ubuntu terminal.
Tested it with Chrome, same result.

**Comment by justinmk** [comment]
Try in `:te` 

`:!` runs in a pipe, see https://github.com/neovim/neovim/issues/1496 . See also

- https://github.com/neovim/neovim/issues/9886 
- https://github.com/neovim/neovim/wiki/FAQ

**Comment by pogopaule** [comment]
@justinmk Thank you! But that does not work either. I guess something is messed up on my machine in a weird way because it works for @evanrittenhouse 

I switched to `x-www-browser` which works.

**Comment by tsakirist** [comment]
xdg-open doesn't work from within neovim in my machine too.

### Neovim version:
NVIM v0.8.0-dev, latest nightly

### Operating System:

Operating System: Ubuntu 22.04.1 LTS
Kernel: Linux 5.15.0-47-generic
Architecture: x86-64

**Comment by jasonhildebrand** [comment]
Same here.  I couldn't get :terminal to work either, but found that jobstart() works. 

Example:

`:call jobstart('xdg-open http://github.com')`

**Comment by Flimm** [comment]
It does not work for me as well. This GitHub issue is closed. I'm not sure which one of the linked issues to follow instead.

**Comment by justinmk** [comment]
@Flimm try `vim.ui.open()` , which uses xdg-open internally. 

Or look at its impl to see how it calls vim.system : https://github.com/neovim/neovim/blob/862679c70fa062e567fd7f720f9fd994fa023101/runtime/lua/vim/ui.lua#L160-L167

**Comment by Flimm** [comment]
I tried to run this: `:lua vim.ui.open('http://example.com')` . Sadly, it also failed silently.

**Comment by Flimm** [comment]
If I run `xdg-open http://example.com` in my terminal, then Firefox opens a new tab with that website open. If I run `vim` and I run the command `:! xdg-open http://example.com` , then Firefox opens a new tab with that website open. However, if I run `nvim --clean` and I run the command `:! xdg-open http://example.com` , then nothing happens. I use Fish, and Bash, I experience the issue on both.

**Comment by justinmk** [comment]
Try the development version? The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.

**Comment by justinmk** [comment]
> running `:lua vim.ui.open('http://example.com')` works, but running `:! xdg-open http://example.com` doesn't.

Great. That's why this issue is closed. The `:!` situation is tracked in another issue, which is also mentioned in the FAQ.
