### ISSUE TITLE
Output of "n substitutions on m lines" is not translated

### ISSUE THREAD

**Issue by yamam** [neovim/neovim#19726]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-817-g33b77eb72

### Vim (not Nvim) behaves the same?

no, vim 9.0.176

### Operating system/version

Linux 5.10.102.1-microsoft-standard-WSL2 Ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

nvim --clean
type `3aa<cr><esc>:%s/a/b<cr>`

### Expected behavior

![image](https://user-images.githubusercontent.com/12369962/184261971-adb8f9ec-f3de-4782-ae6a-e7364e3ef088.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/12369962/184261813-0e53c3d2-87a1-422e-ad3c-2fdfc6b02f34.png)

**Comment by clason** [comment]
We rely on community contributions for our translations. PR welcome!

**Comment by justinmk** [comment]
don't need an issue to track every localized string. Just send a PR.
