### ISSUE TITLE
ERROR: Failed to run healthcheck for "vim" plugin

### ISSUE THREAD

**Issue by yangxingwu** [neovim/neovim#19731]
### Neovim version (nvim -v)

0.7.2 commit e8ee6733926db83ef216497a1d660a173184ff39

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

CentOs 7.8

### Terminal name/version

iterm  3.4.16

### $TERM environment variable

screen-256color 

### Installation

build from repo

### How to reproduce the issue

nvim

:checkhealth

### Expected behavior

no error report

### Actual behavior

vim: require("vim.health").check()
========================================================================
  - ERROR: Failed to run healthcheck for "vim" plugin. Exception:
    function health#check, line 20
    Vim(eval):E5108: Error executing lua [string "luaeval()"]:1: attempt to call field 'check' (a nil value)
    stack traceback:
    [string "luaeval()"]:1: in main chunk

**Comment by zeertzjq** [comment]
It is likely that you installed a later version and didn't uninstall it cleanly.

**Comment by yangxingwu** [comment]
actually, it's bug fixed by [pr 18816](https://github.com/neovim/neovim/pull/18816/files)
