### ISSUE TITLE
Support run some slow function with timeout

### ISSUE THREAD

**Issue by hiberabyss** [neovim/neovim#19742]
### Feature already in Vim?

No

### Feature description

Some vim function (e.g. `getcompletion('Man ', 'cmdline')`) run slowly, could it possible to run these function with timeout in a new thread without block vim?

**Comment by ii14** [comment]
I'd say no, if you're asking for some kind of generic solution. This would have to be implemented for each function that needs it on a case by case basis. Either with a timeout parameter like `search()` or a callback like in `jobstart()`.

If you're asking specifically about `:Man` completion, it's defined in a script. You can follow what it's doing and recreate a non-blocking, async version:
https://github.com/neovim/neovim/blob/b6a963bded749bb47c3b90398009da4ad1e18f68/runtime/autoload/man.vim#L379

**Comment by lewis6991** [comment]
`:Man` completion is slow because it is implemented in vimscript. I ported to Lua once and It made it much faster.

**Comment by justinmk** [comment]
CTRL-c already serves this purpose. We should definitely continue to work on better support for CTRL-c (including at the API level).

**Comment by gregorias** [comment]
Lack of asynchronicity or a timeout [breaks the cmp-cmdline plugin](https://github.com/hrsh7th/cmp-cmdline/issues/85) in case of long-running tasks.

The suggested workflow of using CTRL-C doesn't work, because CTRL-C deletes the entire cmdline, which prevents the user from completing their command. Unless, there's a way to capture CTRL-C to only stop `vim.fn.getcompletion` without clearing the command. Do you know if that's possible? Could we revisit this issue?

**Comment by justinmk** [comment]
`:help wait()` (also `:help vim.wait()`)

**Comment by gregorias** [comment]
Thank you for a quick response, @justinmk. I read about `wait` and experimented with it, and I fail to see how I can use it to help this case. Could you elaborate if I'm missing something?

The reason `wait` doesn't help here is that it can't execute `vim.fn.getcompletion` asynchronously. Calling `vim.fn.getcompletion` anywhere from the main thread will still block that thread as `vim.fn.getcompletion` does not yield control back.

For example, consider this:

```lua
local completion = nil
vim.wait(TIMEOUT, function()
  completion = vim.fn.getcompletion(ARGS)
  return true
end)
```

In that code, Neovim hangs the moment `vim.wait` executes that callback. `vim.wait` can not preempt its callback. 

`vim.wait` would be useful if we did have a callback form of `vim.fn.getcompletion`, e.g., 

```lua
local done = false
vim.fn.getcompletion(ARGS, function() done = true end)
vim.wait(TIMEOUT, function() return done end)
```

**Comment by justinmk** [comment]
Ah, I thought you wanted a way to limit the maximum time used by a function.

I agree that the first CTRL-c shouldn't clear the cmdline if code is executing; it should only stop the code.
