### ISSUE TITLE
"E315: ml_get: invalid lnum" error occurs when a float window is opend in visual mode

### ISSUE THREAD

**Issue by skanehira** [neovim/neovim#19744]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-828-ge23c5fda0
NOTE: Video is v0.7 but head is still reproduce

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS Monterey 12.5

### Terminal name/version

iTerm2 3.4.16

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

- Create a `tmp.vim` with the following contents
  ```vim
  set ve=all
  
  function! s:main(message) abort
    let buf = nvim_create_buf(v:false, v:true)
    call nvim_buf_set_lines(buf, 0, -1, v:true, a:message)
    let winid = nvim_open_win(buf, 1, {
          \ 'relative': 'editor',
          \ 'width': 40,
          \ 'height': 6,
          \ 'row': 1,
          \ 'col': &columns - (40 + 2),
          \ 'style': 'minimal',
          \ 'focusable': v:true,
          \ 'border': map(['╭', '─', '╮', '│', '╯', '─', '╰', '│'], { _, v -> [v, 'Special'] }),
          \ })
    call nvim_win_set_option(winid, 'winhighlight', 'Normal:NONE')
  endfunction
  
  
  vnoremap <silent> * <Cmd>call <SID>main(["hello", "world"])<CR>
  ```
- Run `nvim -u tmp.vim`
- Create 4 or more empty rows
- Move the cursor 4 or more columns to the right from the bottom line
- Start a rectangular selection with <C-v> and move to the first column of the first line
- Press `*`.

https://user-images.githubusercontent.com/7888591/184401387-af649e09-d318-4e85-923e-b797a6e0fa47.mov

### Expected behavior

No errors should occur.

### Actual behavior

"E315: ml_get: invalid lnum" is occured.

**Comment by zeertzjq** [comment]
Same problem applies to `nvim_win_set_buf`:
```vim
set virtualedit=all

function! s:main(message) abort
  let buf = nvim_create_buf(v:false, v:true)
  call nvim_buf_set_lines(buf, 0, -1, v:true, a:message)
  call nvim_win_set_buf(0, buf)
endfunction

vnoremap <silent> * <Cmd>call <SID>main(["hello", "world"])<CR>

let g:buf = bufadd('foo')

call setline(1, ['', '', '', ''])
call cursor(4, 5)
call feedkeys("\<C-V>3k4h*", 'xt')
```

**Comment by zeertzjq** [comment]
To reproduce this in Vim:
```vim
set hidden
set virtualedit=all
call setline(1, 'foo')
let g:buf = bufnr()
enew
call setline(1, ['', '', '', ''])
call cursor(4, 5)
call feedkeys("\<C-V>3k4h", 'xt')
exe 'buffer' g:buf
``
