### ISSUE TITLE
Symlinking .vimrc to .config/nvim/init.vim does not apply config

### ISSUE THREAD

**Issue by spiderforrest** [neovim/neovim#19745]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

no, the opposite (ln -s .config/nvim/init.vim .vimrc) applies configuration to Vim from init.vim, Vim version 8.2.2434

### Operating system/version

Tested on Arch, Void, and Debian Bullsye

### Terminal name/version

tty, alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

System package managers: pacman, xbps-install, apt

### How to reproduce the issue

# <package manager install> vim neovim
$ echo "set number" > ~/.vimrc
$ ln -s ~/.vimrc ~/.config/nvim/init.vim
$ nvim

In my testing, no line numbers would be visible in Neovim. We can verify that nothing is wrong with ~/.vimrc by running Vim and Neovim, using the -u flag on the other to set it to use ~/.vimrc:

$ vim
$ nvim -u ~/.vimrc

Both Vim and Neovim show line numbers here.

The inverse, linking ~/.vimrc to ~/.config/nvim/init.vim, does seem to work:

$ rm ~/.vimrc
$ rm ~/.config/nvim/init.vim
$ echo "set number" ~/.config/nvim/init.vim
$ ln -s ~/.config/nvim/init.vim ~/.vimrc
$ vim

Line numbers are visible in Vim in this example.

### Expected behavior

In the previous example, Neovim to launch with line numbers. 
In https://github.com/neovim/neovim/issues/1674 it is an intended behavior that Neovim does not follow symlinks for internal files. I could not find if that behavior applying to init.vim is intended.

### Actual behavior

Neovim does not read a symlinked init.vim. Running Neovim with -V only says:
could not source "/home/spider/.config/nvim/init.vim"

**Comment by glacambre** [comment]
What do `:echo $MYVIMRC` and `:echo stdpath("config")` print when ran from neovim?

**Comment by spiderforrest** [comment]
$MYVIMRC is blank and stdpath("config") is /home/spider/.config/nvim

**Comment by jamessan** [comment]
> Running Neovim with -V only says:
could not source "/home/spider/.config/nvim/init.vim"

This is what you need to fix, then.  You can increase the verbosity by specifying a number, e.g. `-V10`.

I've been using a symlink for years, and it does work.

```
% ls -l ~/.config/nvim/init.vim
lrwxrwxrwx 1 jamessan jamessan 9 Mar 26  2019 /home/jamessan/.config/nvim/init.vim -> ../.vimrc
```

There's something wrong in your environment.

**Comment by spiderforrest** [comment]
Sorry, I was unclear when I said "running neovim with -V only says [...]".
That was all it said that was relevant. With -V10 the first page of logging:
```chdir(/home/spider)
chdir(/usr/share/nvim/runtime)
chdir(/home/spider)
sourcing "/usr/share/nvim/runtime/ftplugin.vim"
finished sourcing /usr/share/nvim/runtime/ftplugin.vim
chdir(/home/spider)
chdir(/usr/share/nvim/runtime)
chdir(/home/spider)
sourcing "/usr/share/nvim/runtime/indent.vim"
finished sourcing /usr/share/nvim/runtime/indent.vim
chdir(/home/spider)
chdir(/etc/xdg/nvim)
chdir(/home/spider)
sourcing "/etc/xdg/nvim/sysinit.vim"
chdir(/home/spider)
chdir(/usr/share/nvim)
chdir(/home/spider)
line 2: sourcing "/usr/share/nvim/archlinux.vim"
finished sourcing /usr/share/nvim/archlinux.vim
continuing in /etc/xdg/nvim/sysinit.vim
finished sourcing /etc/xdg/nvim/sysinit.vim
chdir(/home/spider)
chdir(/home/spider/.config/nvim)
chdir(/home/spider)
could not source "/home/spider/.config/nvim/init.vim"
chdir(/home/spider)
chdir(/etc/xdg//nvim)
chdir(/home/spider)
could not source "/etc/xdg//nvim/init.vim"
chdir(/home/spider)
chdir(/usr/share/nvim/runtime)
chdir(/home/spider)
sourcing "/usr/share/nvim/runtime/filetype.lua"
finished sourcing /usr/share/nvim/runtime/filetype.lua
chdir(/home/spider)
chdir(/usr/share/nvim/runtime)
chdir(/home/spider)
sourcing "/usr/share/nvim/runtime/filetype.vim"
chdir(/home/spider)
chdir(/usr/share/vim/vimfiles/ftdetect)
chdir(/home/spider)
line 2520: sourcing "/usr/share/vim/vimfiles/ftdetect/firejail.vim"
finished sourcing /usr/share/vim/vimfiles/ftdetect/firejail.vim
continuing in /usr/share/nvim/runtime/filetype.vim
not found in runtime path: "ftdetect/*.lua"
finished sourcing /usr/share/nvim/runtime/filetype.vim
chdir(/home/spider)
chdir(/usr/share/nvim/runtime/syntax)
chdir(/home/spider)```
