### ISSUE TITLE
Clarify documentation about specifics of `vim.keymap.set()` versus `nvim_set_keymap`

### ISSUE THREAD

**Issue by antoineco** [neovim/neovim#19759]
Issue was renamed. Old tittle:

_Mapping with `<Plug>` inside an expression feeds garbage_

### Neovim version (nvim -v)

0.8.0-dev-838-gc1cbe3fb3

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

macOS 12.5

### Terminal name/version

kitty 0.25.2
Terminal.app 2.12.7 (445)

### $TERM environment variable

xterm-kitty
xterm-256color

### Installation

Homebrew (--HEAD)

### How to reproduce the issue

```console
$ nvim --clean
```

```vim
:inoremap <silent> <Plug>(say-hi) <C-u>Hi!<Esc>
:lua vim.keymap.set('i', '<Tab>', [[v:true ? '<Plug>(say-hi)' : '<Tab>']], {remap=true, expr=true})
i<Tab>
```

### Expected behavior

The `<Plug>(say-hi)` mapping is executed: line gets erased, inputs "Hi!".

### Actual behavior

Feeds `<80>ý-hi)` wherever the cursor is.

### Additional information

If instead of creating the mapping using the Lua helper I create it via a Vim command, the mapping works as expected:

```vim
:inoremap <expr> <Tab> v:true ? '<Plug>(say-hi)' : '<Tab>'
i<Tab>
" -> Hi!
```

I'm also going to leave this here for fellow Vim users migrating to Neovim and being confused by similar behaviours:

Maybe the issue is me not being experienced enough with the Lua API to understand exactly what forms the `{rhs}` positional parameter can take based on the documentation, but it seems like `{rhs}` is either
- inserted _untouched_ (**not evaluated as a Vim expression**)
- executed as **Lua code** otherwise

That means the aforementioned mapping works if rewritten with a Lua function:

```vim
vim.keymap.set('i', '<Tab>', function()
  return true and '<Plug>(say-hi)' or '<Tab>'
end, {remap=true, expr=true})
```

**Comment by zeertzjq** [comment]
Add `replace_keycodes = false` to `opts`

**Comment by antoineco** [comment]
@zeertzjq right, it works.

I'm not convinced about the outcome though ("closed:question"?), the docs are clearly outdated:

> values are booleans (default **false**)

_Apparently there are a few exceptions like this one._

> When "expr" is true, "replace_keycodes" (boolean) can be used to replace keycodes in the resulting string.

_Apparently replace_keycodes is now true by default whenever expr is true._

**Comment by zeertzjq** [comment]
You are referring to the docs of `nvim_set_keymap`, not `vim.keymap.set()`. This is only the default behavior of `vim.keymap.set()`.

**Comment by antoineco** [comment]
You're right. And yes the cross referencing is _super confusing_ because on one hand people are prompted to check the parameters from another API, on the other hand the **last** sentence partially invalidates it but users have already navigated / jumped to nvim_set_keymap most likely. 

I would suggest splitting the description of `{opts}` as follows:

> _Accepts the same options as nvim_set_keymap() with a few behaviours specific to this API:_
> <insert a description about how replace_keycodes behave, and any other specifics>
>
> In addition to those options, table also accepts the following keys:
> <insert a description of the additional keys>

I can volunteer to submit a small rewrite of this specific API doc if you'd be OK with that proposal.

**Comment by zeertzjq** [comment]
> I would suggest splitting the description of `{opts}` as follows:
> 
> > _Accepts the same options as nvim_set_keymap() with a few behaviours specific to this API:_
> > <insert a description about how replace_keycodes behave, and any other specifics>
> > In addition to those options, table also accepts the following keys:
> 
> I can volunteer to submit a small rewrite of this specific API doc if you'd be OK with that proposal.

That sounds good. Thanks!

**Comment by zeertzjq** [comment]
Note that the docs are generated from doxygen comments in `keymap.lua`.

**Comment by antoineco** [comment]
Got it 👍  I'm on it.
