### ISSUE TITLE
bad parameters for scroll events in abstract_ui

### ISSUE THREAD

**Issue by coolwanglu** [neovim/neovim#1975]
When scrolling the buffer downwards by `x` lines, `scroll x` is received
However if I scroll the buffer upwards by `x` lines, I got `scroll <x-32>`

I didn't see such behavior is handled in python-client though. Is this intended?

**Comment by coolwanglu** [comment]
On the other hand, it might be something wrong with the msgpack decoding, but I'm not sure yet.

**Comment by tarruda** [comment]
> On the other hand, it might be something wrong with the msgpack decoding, but I'm not sure yet.

I think tha'ts more likely, or else the python client would have the same issue.

**Comment by coolwanglu** [comment]
I found the issue, it looks like a bug in the msgpack5 module: https://github.com/mcollina/msgpack5/issues/14
