### ISSUE TITLE
Markdown indentation bug

### ISSUE THREAD

**Issue by denvaar** [neovim/neovim#19757]
### Neovim version (nvim -v)

v0.8.0-dev+440-g98e2da7d5

### Vim (not Nvim) behaves the same?

yes, 8.2.4113

### Operating system/version

macOS 12.4

### Terminal name/version

iTerm 3.4.12

### $TERM environment variable

xterm-256color

### Installation

Downloaded tar archive and extracted

### How to reproduce the issue

1. nvim --clean demo.md
2. Add the following content:

````markdown
# Demo 

```
# Welcome

![](/img/picture.webp)

[a link](/about.html)
```

more text
````

3. Execute `gg=G`
4. See that the indentation is ruined after the end of the code block. Eg. the content now looks like:

````
# Demo 

```
# Welcome

![](/img/picture.webp)

[a link](/about.html)
	```

	more text

````

### Expected behavior

The indentation should not change. I would expect the content to remain like:

````
# Demo 

```
# Welcome

![](/img/picture.webp)

[a link](/about.html)
```

more text

````

### Actual behavior

Content is unexpectedly indented:

````
# Demo 

```
# Welcome

![](/img/picture.webp)

[a link](/about.html)
	```

	more text

````

**Comment by clason** [comment]
Thank you, but this should be reported upstream at https://github.com/tpope/vim-markdown (the filetype's maintainer). If there is a fix, it should be first added to Vim since we take the runtime files verbatim from there.
