### ISSUE TITLE
Build error: Failed downloading https://luarocks.org/mpack-1.0.8-0.rockspec

### ISSUE THREAD

**Issue by Maltimore** [neovim/neovim#19753]
### Neovim version (nvim -v)

0.7.2 or master

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

KDE Neon 20.04 (basically Ubuntu 20.04)

### Terminal name/version

Alacritty 0.6.0

### $TERM environment variable

tmux-256color

### Installation

n/a

### How to reproduce the issue

I also asked this on the discourse, but so far no answers: `https://neovim.discourse.group/t/build-error-failed-downloading-https-luarocks-org-mpack-1-0-8-0-rockspec/3010`. Anyways I think the build instructions are rather simple so I don't think I made an (obvious) mistake following them, so either way this could be considered a bug (potentially documentation bug).

1. Clone neovim repo, check out either master commit or v0.7.2
2. Install build dependencies `sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen`
3. Execute `make distclean && make CMAKE_BUILD_TYPE=RelWithDebInfo`

### Expected behavior

Builds neovim

### Actual behavior

Observe error (I shortened the build log a bit as github didn't allow the full output. I can paste the entire output somewhere else if required).

```
[...]

==== Successfully built LuaJIT 2.1.0-beta3 ====
==== Installing LuaJIT 2.1.0-beta3 to /home/maltimore/repos/neovim/.deps/usr ====
mkdir -p /home/maltimore/repos/neovim/.deps/usr/bin /home/maltimore/repos/neovim/.deps/usr/lib /home/maltimore/repos/neovim/.deps/usr/include/luajit-2.1 /home/maltimore/repos/neovim/.deps/usr/share/man/man1 /home/maltimore/repos/neovim/.deps/usr/lib/pkgconfig /home/maltimore/repos/neovim/.deps/usr/share/luajit-2.1.0-beta3/jit /home/maltimore/repos/neovim/.deps/usr/share/lua/5.1 /home/maltimore/repos/neovim/.deps/usr/lib/lua/5.1
cd src && install -m 0755 luajit /home/maltimore/repos/neovim/.deps/usr/bin/luajit-2.1.0-beta3
cd src && test -f libluajit.a && install -m 0644 libluajit.a /home/maltimore/repos/neovim/.deps/usr/lib/libluajit-5.1.a || :
rm -f /home/maltimore/repos/neovim/.deps/usr/lib/libluajit-5.1.so.2.1.0 /home/maltimore/repos/neovim/.deps/usr/lib/libluajit-5.1.so /home/maltimore/repos/neovim/.deps/usr/lib/libluajit-5.1.so.2
cd src && test -f libluajit.so && \
  install -m 0755 libluajit.so /home/maltimore/repos/neovim/.deps/usr/lib/libluajit-5.1.so.2.1.0 && \
  ( ldconfig -n 2>/dev/null /home/maltimore/repos/neovim/.deps/usr/lib || : ) && \
  ln -sf libluajit-5.1.so.2.1.0 /home/maltimore/repos/neovim/.deps/usr/lib/libluajit-5.1.so && \
  ln -sf libluajit-5.1.so.2.1.0 /home/maltimore/repos/neovim/.deps/usr/lib/libluajit-5.1.so.2 || :
cd etc && install -m 0644 luajit.1 /home/maltimore/repos/neovim/.deps/usr/share/man/man1
cd etc && sed -e "s|^prefix=.*|prefix=/home/maltimore/repos/neovim/.deps/usr|" -e "s|^multilib=.*|multilib=lib|" luajit.pc > luajit.pc.tmp && \
  install -m 0644 luajit.pc.tmp /home/maltimore/repos/neovim/.deps/usr/lib/pkgconfig/luajit.pc && \
  rm -f luajit.pc.tmp
cd src && install -m 0644 lua.h lualib.h lauxlib.h luaconf.h lua.hpp luajit.h /home/maltimore/repos/neovim/.deps/usr/include/luajit-2.1
cd src/jit && install -m 0644 bc.lua bcsave.lua dump.lua p.lua v.lua zone.lua dis_x86.lua dis_x64.lua dis_arm.lua dis_arm64.lua dis_arm64be.lua dis_ppc.lua dis_mips.lua dis_mipsel.lua dis_mips64.lua dis_mips64el.lua vmdef.lua /home/maltimore/repos/neovim/.deps/usr/share/luajit-2.1.0-beta3/jit
==== Successfully installed LuaJIT 2.1.0-beta3 to /home/maltimore/repos/neovim/.deps/usr ====

Note: the development releases deliberately do NOT install a symlink for luajit
You can do this now by running this command (with sudo):

  ln -sf luajit-2.1.0-beta3 /home/maltimore/repos/neovim/.deps/usr/bin/luajit

make[1]: Leaving directory '/home/maltimore/repos/neovim/.deps/build/src/luajit'
[76/97] Performing download step for 'luv-static'
-- file: /home/maltimore/repos/neovim/.deps/build/downloads/luv/1.44.2-0.tar.gz
-- downloading...
       src='https://github.com/luvit/luv/archive/1.44.2-0.tar.gz'
       dst='/home/maltimore/repos/neovim/.deps/build/downloads/luv/1.44.2-0.tar.gz'
       timeout='none'
-- downloading... done
-- extracting...
     src='/home/maltimore/repos/neovim/.deps/build/downloads/luv/1.44.2-0.tar.gz'
     dst='/home/maltimore/repos/neovim/.deps/build/src/luv'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean binary dir]
-- extracting... [clean up]
-- extracting... done
[79/97] Performing configure step for 'luv-static'
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 9.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (LIBUV) does
  not match the name of the calling package (Libuv).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindLibuv.cmake:33 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:68 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found LIBUV: /home/maltimore/repos/neovim/.deps/build/src/luv-static-build/uv_a
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (LUAJIT)
  does not match the name of the calling package (LuaJIT).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindLuaJIT.cmake:55 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:131 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found LUAJIT: /home/maltimore/repos/neovim/.deps/usr/lib/libluajit-5.1.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/maltimore/repos/neovim/.deps/build/src/luv-static-build
[80/97] Performing download step for 'luarocks'
-- file: /home/maltimore/repos/neovim/.deps/build/downloads/luarocks/v3.8.0.tar.gz
-- downloading...
       src='https://github.com/luarocks/luarocks/archive/v3.8.0.tar.gz'
       dst='/home/maltimore/repos/neovim/.deps/build/downloads/luarocks/v3.8.0.tar.gz'
       timeout='none'
-- downloading... done
-- extracting...
     src='/home/maltimore/repos/neovim/.deps/build/downloads/luarocks/v3.8.0.tar.gz'
     dst='/home/maltimore/repos/neovim/.deps/build/src/luarocks'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean binary dir]
-- extracting... [clean up]
-- extracting... done
[83/97] Performing configure step for 'luarocks'

Configuring LuaRocks version 3.8.0...

Lua version detected: 5.1
Lua interpreter found: /home/maltimore/repos/neovim/.deps/usr/bin/luajit
lua.h found: /home/maltimore/repos/neovim/.deps/usr/include/luajit-2.1/lua.h
unzip found in PATH: /usr/bin

Done configuring.

LuaRocks will be installed at......: /home/maltimore/repos/neovim/.deps/usr
LuaRocks will install rocks at.....: /home/maltimore/repos/neovim/.deps/usr
LuaRocks configuration directory...: /home/maltimore/repos/neovim/.deps/usr/etc/luarocks
Using Lua from.....................: /home/maltimore/repos/neovim/.deps/usr
Lua include directory..............: /home/maltimore/repos/neovim/.deps/usr/include/luajit-2.1

* Type make and make install:
  to install to /home/maltimore/repos/neovim/.deps/usr as usual.
* Type make bootstrap:
  to install LuaRocks into /home/maltimore/repos/neovim/.deps/usr as a rock.

[85/97] Performing install step for 'luarocks'
make[1]: Entering directory '/home/maltimore/repos/neovim/.deps/build/src/luarocks'
mkdir -p "build"
mkdir -p .luarocks
cp ./build/config-5.1.lua .luarocks/config-5.1.lua
rm -f src/luarocks/core/hardcoded.lua
echo "#!/bin/sh" > luarocks
echo "unset LUA_PATH LUA_PATH_5_2 LUA_PATH_5_3 LUA_PATH_5_4 LUA_CPATH LUA_CPATH_5_2 LUA_CPATH_5_3 LUA_CPATH_5_4" >> luarocks
echo 'LUAROCKS_SYSCONFDIR="/home/maltimore/repos/neovim/.deps/usr/etc/luarocks" LUA_PATH="/home/maltimore/repos/neovim/.deps/build/src/luarocks/src/?.lua;;" exec "/home/maltimore/repos/neovim/.deps/usr/bin/luajit" "/home/maltimore/repos/neovim/.deps/build/src/luarocks/src/bin/luarocks" --project-tree="/home/maltimore/repos/neovim/.deps/build/src/luarocks/lua_modules" "$@"' >> luarocks
chmod +rx ./luarocks
./luarocks init

Initializing project 'luarocks' for Lua 5.1 ...
-----------------------------------------------

Checking your Lua installation ...
Adding entries to .gitignore ...
Preparing ./.luarocks/ ...
Wrote .luarocks/config-5.1.lua
Preparing ./lua_modules/ ...
./luarocks already exists. Not overwriting it!
Preparing ./lua for version 5.1...
mkdir -p "/home/maltimore/repos/neovim/.deps/usr/etc/luarocks"
install -m 644 "build/config-5.1.lua" "/home/maltimore/repos/neovim/.deps/usr/etc/luarocks/config-5.1.lua"
./luarocks make --tree="/home/maltimore/repos/neovim/.deps/usr"

No existing manifest. Attempting to rebuild...
luarocks 3.8.0-1 is now installed in /home/maltimore/repos/neovim/.deps/usr (license: MIT)

make[1]: Leaving directory '/home/maltimore/repos/neovim/.deps/build/src/luarocks'
[87/97] Performing build step for 'luv-static'
[1/2] Building C object CMakeFiles/libluv_a.dir/src/luv.c.o
[2/2] Linking C static library libluv.a
[88/97] Performing install step for 'luv-static'
[0/1] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /home/maltimore/repos/neovim/.deps/usr/lib/libluv.a
-- Installing: /home/maltimore/repos/neovim/.deps/usr/include/luv/luv.h
-- Installing: /home/maltimore/repos/neovim/.deps/usr/include/luv/util.h
-- Installing: /home/maltimore/repos/neovim/.deps/usr/include/luv/lhandle.h
-- Installing: /home/maltimore/repos/neovim/.deps/usr/include/luv/lreq.h
[90/97] Generating usr/lib/luarocks/rocks-5.1/mpack
FAILED: usr/lib/luarocks/rocks-5.1/mpack /home/maltimore/repos/neovim/.deps/usr/lib/luarocks/rocks-5.1/mpack
cd /home/maltimore/repos/neovim/.deps && /home/maltimore/repos/neovim/.deps/usr/bin/luarocks build mpack 1.0.8-0 CC=/usr/bin/cc LD=/usr/bin/cc
Warning: Failed downloading. Attempting mirror at https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master//mpack-1.0.8-0.rockspec
Warning: Failed downloading. Attempting mirror at https://luafr.org/luarocks//mpack-1.0.8-0.rockspec
Warning: Failed downloading. Attempting mirror at http://luarocks.logiceditor.com/rocks/mpack-1.0.8-0.rockspec

Error: Error fetching file: Failed downloading https://luarocks.org/mpack-1.0.8-0.rockspec -
failed downloading https://luarocks.org/mpack-1.0.8-0.rockspec
failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master//mpack-1.0.8-0.rockspec
failed downloading https://luafr.org/luarocks//mpack-1.0.8-0.rockspec
failed downloading http://luarocks.logiceditor.com/rocks/mpack-1.0.8-0.rockspec

ninja: build stopped: subcommand failed.
make: *** [Makefile:101: deps] Error 1
```

Edit: Downloading `https://luarocks.org/mpack-1.0.8-0.rockspec` manually or via curl is no problem.

**Comment by clason** [comment]
This is usually an environment issue; check in particular your proxy settings.

**Comment by stewartmmt** [comment]
i've met a similar problem. I sopposed that I didn't install Ninja properly as root. It bothers me ,
'''
sudo make CMAKE_BUILD_TYPE=RelWithDebInfo
mkdir -p build
touch build/.ran-deps-cmake
ninja  -C .deps
ninja: Entering directory `.deps'
[3/3] cd /home/stewart/neovim/.deps && /usr/bin/cmake -E touch .third-party
ninja  -C build
ninja: Entering directory `build'
[0/2] Re-checking globbed directories...
[2/37] Linking C executable bin/nvim
FAILED: bin/nvim 
: && /usr/bin/cc -O2 -g  -Og -g -flto -fno-fat-lto-objects -Wl,--export-dynamic -rdynamic src/nvim/CMakeFiles/nvim.dir/main.c.o src/nvim/CMakeFiles/nvim.dir/auto/lua_api_c_bindings.generated.c.o src/nvim/CMakeFiles/nvim.dir/__/__/cmake.config/auto/pathdef.c.o src/nvim/CMakeFiles/nvim.dir/api/autocmd.c.o src/nvim/CMakeFiles/nvim.dir/api/buffer.c.o src/nvim/CMakeFiles/nvim.dir/api/command.c.o src/nvim/CMakeFiles/nvim.dir/api/deprecated.c.o src/nvim/CMakeFiles/nvim.dir/api/extmark.c.o src/nvim/CMakeFiles/nvim.dir/api/options.c.o src/nvim/CMakeFiles/nvim.dir/api/private/converter.c.o src/nvim/CMakeFiles/nvim.dir/api/private/dispatch.c.o src/nvim/CMakeFiles/nvim.dir/api/private/helpers.c.o src/nvim/CMakeFiles/nvim.dir/api/tabpage.c.o src/nvim/CMakeFiles/nvim.dir/api/ui.c.o src/nvim/CMakeFiles/nvim.dir/api/vim.c.o src/nvim/CMakeFiles/nvim.dir/api/vimscript.c.o src/nvim/CMakeFiles/nvim.dir/api/win_config.c.o src/nvim/CMakeFiles/nvim.dir/api/window.c.o src/nvim/CMakeFiles/nvim.dir/arabic.c.o src/nvim/CMakeFiles/nvim.dir/arglist.c.o src/nvim/CMakeFiles/nvim.dir/autocmd.c.o src/nvim/CMakeFiles/nvim.dir/buffer.c.o src/nvim/CMakeFiles/nvim.dir/buffer_updates.c.o src/nvim/CMakeFiles/nvim.dir/change.c.o src/nvim/CMakeFiles/nvim.dir/channel.c.o src/nvim/CMakeFiles/nvim.dir/charset.c.o src/nvim/CMakeFiles/nvim.dir/cmdexpand.c.o src/nvim/CMakeFiles/nvim.dir/cmdhist.c.o src/nvim/CMakeFiles/nvim.dir/context.c.o src/nvim/CMakeFiles/nvim.dir/cursor.c.o src/nvim/CMakeFiles/nvim.dir/cursor_shape.c.o src/nvim/CMakeFiles/nvim.dir/debugger.c.o src/nvim/CMakeFiles/nvim.dir/decoration.c.o src/nvim/CMakeFiles/nvim.dir/decoration_provider.c.o src/nvim/CMakeFiles/nvim.dir/diff.c.o src/nvim/CMakeFiles/nvim.dir/digraph.c.o src/nvim/CMakeFiles/nvim.dir/drawline.c.o src/nvim/CMakeFiles/nvim.dir/drawscreen.c.o src/nvim/CMakeFiles/nvim.dir/edit.c.o src/nvim/CMakeFiles/nvim.dir/eval.c.o src/nvim/CMakeFiles/nvim.dir/eval/buffer.c.o src/nvim/CMakeFiles/nvim.dir/eval/decode.c.o src/nvim/CMakeFiles/nvim.dir/eval/encode.c.o src/nvim/CMakeFiles/nvim.dir/eval/executor.c.o src/nvim/CMakeFiles/nvim.dir/eval/funcs.c.o src/nvim/CMakeFiles/nvim.dir/eval/gc.c.o src/nvim/CMakeFiles/nvim.dir/eval/typval.c.o src/nvim/CMakeFiles/nvim.dir/eval/userfunc.c.o src/nvim/CMakeFiles/nvim.dir/eval/vars.c.o src/nvim/CMakeFiles/nvim.dir/eval/window.c.o src/nvim/CMakeFiles/nvim.dir/event/libuv_process.c.o src/nvim/CMakeFiles/nvim.dir/event/loop.c.o src/nvim/CMakeFiles/nvim.dir/event/multiqueue.c.o src/nvim/CMakeFiles/nvim.dir/event/process.c.o src/nvim/CMakeFiles/nvim.dir/event/rstream.c.o src/nvim/CMakeFiles/nvim.dir/event/signal.c.o src/nvim/CMakeFiles/nvim.dir/event/socket.c.o src/nvim/CMakeFiles/nvim.dir/event/stream.c.o src/nvim/CMakeFiles/nvim.dir/event/time.c.o src/nvim/CMakeFiles/nvim.dir/event/wstream.c.o src/nvim/CMakeFiles/nvim.dir/ex_cmds.c.o src/nvim/CMakeFiles/nvim.dir/ex_cmds2.c.o src/nvim/CMakeFiles/nvim.dir/ex_docmd.c.o src/nvim/CMakeFiles/nvim.dir/ex_eval.c.o src/nvim/CMakeFiles/nvim.dir/ex_getln.c.o src/nvim/CMakeFiles/nvim.dir/ex_session.c.o src/nvim/CMakeFiles/nvim.dir/extmark.c.o src/nvim/CMakeFiles/nvim.dir/file_search.c.o src/nvim/CMakeFiles/nvim.dir/fileio.c.o src/nvim/CMakeFiles/nvim.dir/fold.c.o src/nvim/CMakeFiles/nvim.dir/garray.c.o src/nvim/CMakeFiles/nvim.dir/getchar.c.o src/nvim/CMakeFiles/nvim.dir/grid.c.o src/nvim/CMakeFiles/nvim.dir/hashtab.c.o src/nvim/CMakeFiles/nvim.dir/help.c.o src/nvim/CMakeFiles/nvim.dir/highlight.c.o src/nvim/CMakeFiles/nvim.dir/highlight_group.c.o src/nvim/CMakeFiles/nvim.dir/indent.c.o src/nvim/CMakeFiles/nvim.dir/indent_c.c.o src/nvim/CMakeFiles/nvim.dir/input.c.o src/nvim/CMakeFiles/nvim.dir/insexpand.c.o src/nvim/CMakeFiles/nvim.dir/keycodes.c.o src/nvim/CMakeFiles/nvim.dir/linematch.c.o src/nvim/CMakeFiles/nvim.dir/locale.c.o src/nvim/CMakeFiles/nvim.dir/log.c.o src/nvim/CMakeFiles/nvim.dir/lua/converter.c.o src/nvim/CMakeFiles/nvim.dir/lua/executor.c.o src/nvim/CMakeFiles/nvim.dir/lua/spell.c.o src/nvim/CMakeFiles/nvim.dir/lua/stdlib.c.o src/nvim/CMakeFiles/nvim.dir/lua/treesitter.c.o src/nvim/CMakeFiles/nvim.dir/lua/xdiff.c.o src/nvim/CMakeFiles/nvim.dir/map.c.o src/nvim/CMakeFiles/nvim.dir/mapping.c.o src/nvim/CMakeFiles/nvim.dir/mark.c.o src/nvim/CMakeFiles/nvim.dir/marktree.c.o src/nvim/CMakeFiles/nvim.dir/match.c.o src/nvim/CMakeFiles/nvim.dir/math.c.o src/nvim/CMakeFiles/nvim.dir/mbyte.c.o src/nvim/CMakeFiles/nvim.dir/memfile.c.o src/nvim/CMakeFiles/nvim.dir/memline.c.o src/nvim/CMakeFiles/nvim.dir/memory.c.o src/nvim/CMakeFiles/nvim.dir/menu.c.o src/nvim/CMakeFiles/nvim.dir/message.c.o src/nvim/CMakeFiles/nvim.dir/mouse.c.o src/nvim/CMakeFiles/nvim.dir/move.c.o src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/channel.c.o src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/helpers.c.o src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/server.c.o src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/unpacker.c.o src/nvim/CMakeFiles/nvim.dir/normal.c.o src/nvim/CMakeFiles/nvim.dir/ops.c.o src/nvim/CMakeFiles/nvim.dir/option.c.o src/nvim/CMakeFiles/nvim.dir/optionstr.c.o src/nvim/CMakeFiles/nvim.dir/os/dl.c.o src/nvim/CMakeFiles/nvim.dir/os/env.c.o src/nvim/CMakeFiles/nvim.dir/os/fileio.c.o src/nvim/CMakeFiles/nvim.dir/os/fs.c.o src/nvim/CMakeFiles/nvim.dir/os/input.c.o src/nvim/CMakeFiles/nvim.dir/os/lang.c.o src/nvim/CMakeFiles/nvim.dir/os/mem.c.o src/nvim/CMakeFiles/nvim.dir/os/process.c.o src/nvim/CMakeFiles/nvim.dir/os/pty_process_unix.c.o src/nvim/CMakeFiles/nvim.dir/os/shell.c.o src/nvim/CMakeFiles/nvim.dir/os/signal.c.o src/nvim/CMakeFiles/nvim.dir/os/stdpaths.c.o src/nvim/CMakeFiles/nvim.dir/os/time.c.o src/nvim/CMakeFiles/nvim.dir/os/tty.c.o src/nvim/CMakeFiles/nvim.dir/os/users.c.o src/nvim/CMakeFiles/nvim.dir/path.c.o src/nvim/CMakeFiles/nvim.dir/plines.c.o src/nvim/CMakeFiles/nvim.dir/popupmenu.c.o src/nvim/CMakeFiles/nvim.dir/profile.c.o src/nvim/CMakeFiles/nvim.dir/quickfix.c.o src/nvim/CMakeFiles/nvim.dir/rbuffer.c.o src/nvim/CMakeFiles/nvim.dir/regexp.c.o src/nvim/CMakeFiles/nvim.dir/runtime.c.o src/nvim/CMakeFiles/nvim.dir/screen.c.o src/nvim/CMakeFiles/nvim.dir/search.c.o src/nvim/CMakeFiles/nvim.dir/sha256.c.o src/nvim/CMakeFiles/nvim.dir/shada.c.o src/nvim/CMakeFiles/nvim.dir/sign.c.o src/nvim/CMakeFiles/nvim.dir/spell.c.o src/nvim/CMakeFiles/nvim.dir/spellfile.c.o src/nvim/CMakeFiles/nvim.dir/spellsuggest.c.o src/nvim/CMakeFiles/nvim.dir/state.c.o src/nvim/CMakeFiles/nvim.dir/statusline.c.o src/nvim/CMakeFiles/nvim.dir/strings.c.o src/nvim/CMakeFiles/nvim.dir/syntax.c.o src/nvim/CMakeFiles/nvim.dir/tag.c.o src/nvim/CMakeFiles/nvim.dir/terminal.c.o src/nvim/CMakeFiles/nvim.dir/testing.c.o src/nvim/CMakeFiles/nvim.dir/textformat.c.o src/nvim/CMakeFiles/nvim.dir/textobject.c.o src/nvim/CMakeFiles/nvim.dir/tui/input.c.o src/nvim/CMakeFiles/nvim.dir/tui/terminfo.c.o src/nvim/CMakeFiles/nvim.dir/tui/tui.c.o src/nvim/CMakeFiles/nvim.dir/ugrid.c.o src/nvim/CMakeFiles/nvim.dir/ui.c.o src/nvim/CMakeFiles/nvim.dir/ui_client.c.o src/nvim/CMakeFiles/nvim.dir/ui_compositor.c.o src/nvim/CMakeFiles/nvim.dir/undo.c.o src/nvim/CMakeFiles/nvim.dir/usercmd.c.o src/nvim/CMakeFiles/nvim.dir/version.c.o src/nvim/CMakeFiles/nvim.dir/viml/parser/expressions.c.o src/nvim/CMakeFiles/nvim.dir/viml/parser/parser.c.o src/nvim/CMakeFiles/nvim.dir/window.c.o src/nvim/CMakeFiles/nvim.dir/__/cjson/fpconv.c.o src/nvim/CMakeFiles/nvim.dir/__/cjson/lua_cjson.c.o src/nvim/CMakeFiles/nvim.dir/__/cjson/strbuf.c.o src/nvim/CMakeFiles/nvim.dir/__/mpack/conv.c.o src/nvim/CMakeFiles/nvim.dir/__/mpack/lmpack.c.o src/nvim/CMakeFiles/nvim.dir/__/mpack/mpack_core.c.o src/nvim/CMakeFiles/nvim.dir/__/mpack/object.c.o src/nvim/CMakeFiles/nvim.dir/__/mpack/rpc.c.o src/nvim/CMakeFiles/nvim.dir/__/xdiff/xdiffi.c.o src/nvim/CMakeFiles/nvim.dir/__/xdiff/xemit.c.o src/nvim/CMakeFiles/nvim.dir/__/xdiff/xhistogram.c.o src/nvim/CMakeFiles/nvim.dir/__/xdiff/xpatience.c.o src/nvim/CMakeFiles/nvim.dir/__/xdiff/xprepare.c.o src/nvim/CMakeFiles/nvim.dir/__/xdiff/xutils.c.o -o bin/nvim  -Wl,--no-undefined  ../.deps/usr/lib/libmsgpackc.a  ../.deps/usr/lib/libluv.a  ../.deps/usr/lib/libtree-sitter.a  ../.deps/usr/lib/libunibilium.a  ../.deps/usr/lib/libtermkey.a  ../.deps/usr/lib/libvterm.a  ../.deps/usr/lib/libluajit-5.1.a  -fstack-protector-strong  -lm  -lutil  /usr/lib/x86_64-linux-gnu/libuv_a.a  -lpthread  -ldl  -lrt  -lnsl  -ldl  -lrt  -lnsl && :
/usr/bin/ld: ../.deps/usr/lib/libluv.a(luv.c.o): in function `luv_available_parallelism':
/home/stewart/neovim/.deps/build/src/luv/src/misc.c:226: undefined reference to `uv_available_parallelism'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make: *** [Makefile:85：nvim] Error 1'''

**Comment by dundargoc** [comment]
@stewartmmt I don't understand. If you think the problem is incorrect installation on Ninja, then shouldn't you fix that then?

Also install neovim with make works fine if you don't want to use ninja.
