### ISSUE TITLE
a no side effect version of getjumplist

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#19765]
### Feature already in Vim?

no

### Feature description

getjumplist has a side effect that when calls this function, it will load several files which in the jumplist into buffers *1, that is a side effect i really dont want to have.

to be clear, *1 means getjumplist will allocate buffers for the files with `bufinfo.loaded = 1`.

(i saw the issue https://github.com/neovim/neovim/issues/18393, i think i'd open an issue to speak out this need instead of adding a comment in there.)

**Comment by haolian9** [comment]
the solution i can imagine in user end is parsing the binary string of jumplist directly which can be got by `nvim_get_context({"jumps")`.

**Comment by haolian9** [comment]
i'm happy with the nvim_get_context approach (yeah, i figured out it's msgpack format to be exactly)

**Comment by haolian9** [comment]
wait, what? nim_get_context also has the same side effect.

**Comment by justinmk** [comment]
> to be clear, *1 means getjumplist will allocate buffers for the files with `bufinfo.loaded = 1`.

What exactly is `bufinfo`? 

jumplists and other buffer data are stored in the buffer. Can't get buffer data without loading the buffer.

Why is this a problem?

**Comment by haolian9** [comment]
the bufinfo i said means the result of `getbufinfo()`.

```
$ nvim
# in nvim
# # should see just one buffer
:echo getbufinfo()
:echo getjumplist()
# # now it's a huge list
:echo getbufinfo()
```
