### ISSUE TITLE
vim.fn.getpos

### ISSUE THREAD

**Issue by mosheavni** [neovim/neovim#19770]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-806-g3ee6c05b4 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.4

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

brew install neovim --HEAD

### How to reproduce the issue

Video to see the problem:
https://asciinema.org/a/514741

<details>
  <summary>bla.lua</summary>
  
  ```lua
local M = {}
function P(msg)
  vim.pretty_print(msg)
end

function M.get_selection()
  -- does not handle rectangular selection
  local s_start = vim.fn.getpos "'<"
  local s_end = vim.fn.getpos "'>"
  local n_lines = math.abs(s_end[2] - s_start[2]) + 1
  P(n_lines)
  local lines = vim.api.nvim_buf_get_lines(0, s_start[2] - 1, s_end[2], false)
  P(lines)
  -- return
  lines[1] = string.sub(lines[1], s_start[3], -1)
  if n_lines == 1 then
    lines[n_lines] = string.sub(lines[n_lines], 1, s_end[3] - s_start[3] + 1)
  else
    lines[n_lines] = string.sub(lines[n_lines], 1, s_end[3])
  end
  return lines
end

vim.keymap.set('v', '<c-r>', function()
  -- local selection = M.get_selection()
  -- local num = tonumber(selection)
  local s_start = vim.fn.getpos "'<"
  local s_end = vim.fn.getpos "'>"
  local n_lines = math.abs(s_end[2] - s_start[2]) + 1
  P(n_lines)
  local lines = vim.api.nvim_buf_get_lines(0, s_start[2] - 1, s_end[2], false)
  P(lines)
  P(selection)
  return '10'
  -- return VisualCalculator()
end, { remap = false })
  ```
</details>

<details>
  <summary>sdf</summary>

  ```
  hiri

  biri 10 niri
  shiri
  kiri
  ```
</details>

Steps:
```
$ nvim -nu bla.lua sdf

# visual select the string `10`
# type <C-R>
# `:echo messages`
# type <ESC>
# visual select the string `10` again
# `:echo messages`
```

### Expected behavior

The first time the keymap is triggered, it should get the line via `vim.fn.getpos`

### Actual behavior

The first time, `vim.fn.getpos "'<"` should return the line that is visually selected, but it returns `{}`.
Note that if invoked from the ex-command, it does return the right value, but from the keymap it refuses to work.

**Comment by zeertzjq** [comment]
This is intended behavior. Lua mapping does not end Visual mode.

**Comment by clason** [comment]
see https://github.com/neovim/neovim/issues/16843 and the linked (stalled) PR. Help welcome!

**Comment by mosheavni** [comment]
> This is intended behavior. Lua mapping does not end Visual mode.

Is there a way to end visual mode from lua?

**Comment by zeertzjq** [comment]
You can try `vim.api.nvim_feedkeys('\027', 'xt', false)`
