### ISSUE TITLE
Windows python provider check failure

### ISSUE THREAD

**Issue by RossSmyth** [neovim/neovim#19788]
### Neovim version (nvim -v)

v0.7.2

### Vim (not Nvim) behaves the same?

no, vim doesn't have checkhealth

### Operating system/version

Windows 10.0.19044

### Terminal name/version

Windows Terminal 1.14.1962.0

### $TERM environment variable

unset

### Installation

extracted Github release build and set $PATH

### How to reproduce the issue

Install [pyenv-win](https://github.com/pyenv-win/pyenv-win) and download some python enviroment. Then launch neovim and run `:checkhealth`

### Expected behavior

It doesn't instantly fail

### Actual behavior

It fails with the exception:
```
provider: health#provider#check
 13 ========================================================================
 14   - ERROR: Failed to run healthcheck for "provider" plugin. Exception:
 15     function health#check[20]..health#provider#check[2]..<SNR>47_check_python[13]..<SNR>47_check_for_pyenv[12]..            <SNR>47_system, line 11
 16     Vim(let):E903: Process failed to start: no such file or directory: "C:\Users\Ross\.pyenv\pyenv-win\bin\pyenv"
 ```
 Indicating that the exception occurs on this line:
 https://github.com/neovim/neovim/blob/c6181a672a2fdb2cb89ddf85b5d6ab15b10a0996/runtime/autoload/health/provider.vim#L298
 Even though that directory does exist on my system. I also have python3_host_prog set to a virtual environment, but whether it is set or not it has the exception as it doesn't even reach checking if it is set.
 
 I have fixed it on my computer though by applying the following patch:
 ```patch
diff --git "a/nvim\share\nvim\runtime\autoload\health\provider.vim" "b/nvim\share\nvim\runtime\autoload\health\provider.vim"
index a01cb96..3c353b9 100644
--- "a/nvim\share\nvim\runtime\autoload\health\provider.vim"
+++ "b/nvim\share\nvim\runtime\autoload\health\provider.vim"
@@ -295,7 +295,7 @@ function! s:check_python() abort
     return
   endif
 
-  let [pyenv, pyenv_root] = s:check_for_pyenv()
+  let [pyenv, pyenv_root] = ['', ''] 
 
   if exists('g:'.host_prog_var)
     call health#report_info(printf('Using: g:%s = "%s"', host_prog_var, get(g:, host_prog_var)))

```
Once applied the provider health check passes:
```
17 ## Python 3 provider (optional)
 18   - INFO: Using: g:python3_host_prog = "C:\dev\nvim\py3nvim\Scripts\python.exe"
 19   - INFO: Executable: C:\dev\nvim\py3nvim\Scripts\python.exe
 20   - INFO: Python version: 3.10.0^M
 21   - INFO: pynvim version: 0.4.3^M
 22   - OK: Latest pynvim is installed.
 ```
 Looking through some PRs, it looks like #12437 may solve this, but has been stalled.

**Comment by RossSmyth** [comment]
Both a report and information for any other people who see this happen.

**Comment by Shougo** [comment]
Please test https://github.com/neovim/neovim/pull/12437.
If it fixes the problem, it should be merged.

**Comment by RossSmyth** [comment]
I have hit this again reinstalling on a new computer.

The pull mentioned may or may not work, but rebasing is not something I want to do. My patch still works though and so that all I did.

**Comment by RossSmyth** [comment]
> The providers/healtchecks were rewritten. Can you try the development version?
> 
>     * The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS.
> 
>     * Check `:version` to confirm that you are using the latest version.

Sorry, I've not used nvim recently. I pulled down the nightly anyways to check. It works better but still not great with pyenv-win.

1. Download nvim
2. Have pyenv-win installed
3. Create a new environment (`pyenv duplicate 3.10.11 nvim`)
4. Set the current shell interpreter to it (`pyenv shell nvim`)
5. Check that it is correct (`pyenv vname` returns "nvim")
6. Install pynvim to the nvim environment (`pyenv exec python -m pip install pynvim`)
7. Run nvim (`nvim --clean`)
8. `:checkhealth`

```
Python 3 provider (optional) ~
- pyenv: Path: C:\Users\Ross\.pyenv\pyenv-win\bin\pyenv.BAT
- pyenv: Root: C:\Users\Ross\.pyenv\pyenv-win\
- `g:python3_host_prog` is not set.  Searching for python3 in the environment.
- WARNING pyenv is not set up optimally.
  - ADVICE:
    - Create a virtualenv specifically for Nvim using pyenv, and set `g:python3_host_prog`.  This will avoid the need to install the pynvim module in each version/virtualenv.
- ERROR "C:\Users\Ross\.pyenv\pyenv-win\versions\nvim\python3.exe
" was not found.
- Executable: Not found
- ERROR Detected pip upgrade failure: Python executable can import "pynvim" but not "neovim": python3
  - ADVICE:
    - Use that Python version to reinstall "pynvim" and optionally "neovim".
      python3 -m pip uninstall pynvim neovim
      python3 -m pip install pynvim
      python3 -m pip install neovim  # only if needed by third-party software
```

Seems to be something with how pyenv-win sets the executable maybe? It seems to have carriage return in it. It still seems to detect something but not quite something that is correct. It does the same thing if I set the interpreter as the global interpreter or the local interpreter instead of shell.

If I do not set a global python interpreter (I normally do not have one set as I do not like global state) nvim python detection doesn't work at all but that is mostly expected, it tries to run a global python but one doesn't exist. I'm not sure what happens on Linux if pyenv doesn't have a Python set when you run nvim.

Obviously if I set `g:python3_host_prog` it works fine. It's been a while, but I think that means it works better. As if I recall correctly it didn't work before even with that set. I'll open an issue on the pyenv-win repo to see if there's something on their end that can be done regarding the carriage return.
