### ISSUE TITLE
Rendering empty message when `cmdheight=0`

### ISSUE THREAD

**Issue by shofel** [neovim/neovim#19782]
### Neovim version (nvim -v)

v0.8.0-dev commit: ac78639de8b89104ee8a360a48ee31a7900fe830

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

linux

### Terminal name/version

kitty 0.25.0

### $TERM environment variable

xterm-256color

### Installation

neovim flake https://github.com/neovim/neovim/blob/master/contrib/flake.nix

### How to reproduce the issue

nvim --clean
:set cmdheight=0
:echo ""'

### Expected behavior

Nothing happens

### Actual behavior

Empty message is rendered and interaction from the user is required.

`Press ENTER or type command to continue`

**Comment by shofel** [comment]
@Shougo thanks for the great feature :)

I experienced this with `vim-fugitive`, when I execute `:Git commit`.

**Comment by Shougo** [comment]
Sorry.  It is expected behavior.

Because `echo ""` means `prints empty line`.
The empty line must be printed.
It is not same with `echo`.

If you have one command line, the empty line is printed in your command line.
But you have set `cmdheight=0`, Vim/neovim must print empty line with `press enter prompt`.

I think `vim-fugitive` should not print empty line.

**Comment by shofel** [comment]
## The essence of an empty message

From the developer's perspective I'm totally agree with you. If someone asks neovim to echo an empty line, then neovim should do exactly this.

But let's look at this from the user's perspective. A program wants to communicate me an empty message, and requires me to prove that I did receive the message by pressing ENTER. What does user gets from this interaction with the computer? What is the useful outcome of this interaction? :thinking_face:

## Backward compatibility

Backward compatibility implementation is most of the time an ugly thing. But it saves others from making even more job, by adapting their stuff, which have become obsolete by some breaking changes.

And yes, it's arguable if we can treat this as a breaking change. Because one can experience it only when deliberately sets his cmdline to zero. Of course, everyone is free not doing it. But maybe it would be nice if there were less observable side-effects of hiding cmdline :thinking:

**Comment by shofel** [comment]
Also I believe there is another related big idea of rethinking the `hit-enter` UX. I mean how the messages can be communicated without blocking the user's attention. Please point me, if there is an ongoing discussion on the topic somewhere

**Comment by shofel** [comment]
Ok, I see there are some thoughts on hit-enter in [the original PR](https://github.com/neovim/neovim/pull/16251). I'll think of it more thoroughly

**Comment by Shougo** [comment]
> Backward compatibility implementation is most of the time an ugly thing. But it saves others from making even more job, by adapting their stuff, which have become obsolete by some breaking changes.

The backward compatibility is applied you have not set `cmdheight=0`, you have changed the value.
The new feature of `set cmdheight=0` is not backward compatible.   You need to understand the trade off.
`set cmdheight=0` is not perfect solution.

> Also I believe there is another related big idea of rethinking the hit-enter UX. I mean how the messages can be communicated without blocking the user's attention. Please point me, if there is an ongoing discussion on the topic somewhere

The messaging is another problem.  I think it should be displayed in another UI.
But it is not related to `set cmdheight=0`.
