### ISSUE TITLE
Better 'define' setting for filetype lua

### ISSUE THREAD

**Issue by ds26gte** [neovim/neovim#19804]
### Feature already in Vim?

No

### Feature description

The inherited `'define'` setting for the `lua` filetype isn't good at all. Perhaps something should be added to `runtime/ftplugin/lua.vim` along the lines of

```
setl def=^\\s*function\\\|^\\s*local\\s\\+\\(function\\)\\?
```

(If folks can come up with something better, that'd be great.)

**Comment by clason** [comment]
Thank you, but we take runtime files verbatim from Vim -- and these take them from the maintainer listed on top of that file. Please contact them, and we will pull in the changes once they are added to Vim.
