### ISSUE TITLE
Statusline fillchars change to ```^```

### ISSUE THREAD

**Issue by marko-cerovac** [neovim/neovim#19803]
### Neovim version (nvim -v)

0.8.0-dev-854-gd334249833

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Arch Linux 5.19.1

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

Arch User Repository

### How to reproduce the issue

nvim foo.txt
:vsp
:echo "Some text"

### Expected behavior

Statusline looking normal.

### Actual behavior

On certain events, the statuline fillchars change from " " to "^". For example, when I split a window or when I enter cmd mode and start typing some text. The issue occurs with the default nvim statusline, and persists with statusline plugins like lualine.nvim.

[Here](https://drive.google.com/file/d/1KsE2zin_W-rVXOBaRXdiHqifD3O65c2d/view?usp=sharing) is a video showcasing the problem and [here](https://github.com/nvim-lualine/lualine.nvim/issues/761) is an issue I submited to lualine.nvim when it first occured.

My settings are:
cmdheight=0
laststatus=3

**Comment by marko-cerovac** [comment]
When I add the --clean flag, the issue doesn't occur. I'm testing to see which setting (or plugin) is causing the issue.

**Comment by marko-cerovac** [comment]
Okay, I've found the source of the issue. Somewhere in my config I had the command:
```vim
highlight StatusLine guibg=#SOME_COLOR
highlight StatusLineNC guibg=#SOME_COLOR
```
This was the source of the issue. 
I'm closing the issue since its an error on my part.

**Comment by ExpandingMan** [comment]
Should this issue have been closed?  I was having the same problem with `StatusLineNC` and I still don't see why it would cause this.  Also the `^` were multiple colors so I don't see how the highlight could have caused that if it were working properly.

This looks to me like a real bug, albeit a minor one.

**Comment by zeertzjq** [comment]
No steps to reproduce

**Comment by gelguy** [comment]
Here's a minimal `init.vim` to reproduce:
```vim
set termguicolors
hi! StatusLine gui=NONE cterm=NONE
hi! StatusLineNc gui=NONE cterm=NONE

call nvim_open_win(0, 0,
      \ {'relative': 'editor', 'height': 1, 'width': 1, 'row': 0, 'col': 0})
```

I will be able to do a git bisect, but not today.

**Comment by zeertzjq** [comment]
This is working as intended. Read `:h 'fillchars'`

**Comment by zeertzjq** [comment]
It seems this feature is usually unwanted and doesn't work properly in Nvim though. Maybe this feature can be removed.

**Comment by ExpandingMan** [comment]
I'm also not sure I understand the doc string... I tried
```
vim.o.fillchars = "stl: "
```
but this does not seem to change the behavior.  Not a big deal, but if I knew how to clear these I would put it in my config to prevent them from showing up again. It's still rather mysterious to me why they appeared exactly when and where they did.

**Comment by zeertzjq** [comment]
I was referring to this:
> 	Any one that is omitted will fall back to the default.  For "stl" and
	"stlnc" the space will be used when there is highlighting, '^' or '='
	otherwise.

> Normally, inversion is used to display the status line.  This can be changed
with the |hl-StatusLine| highlight group.  If no highlighting is used for the
status line, the '^' character is used for the current window, and '=' for
other windows.  If 'mouse' is enabled, a status line can be dragged to resize
windows.

This seems to only work for active window in Nvim, probably because of window-local highlights.

**Comment by justinmk** [comment]
No objection to removing this.

**Comment by punowo** [comment]
> I'm also not sure I understand the doc string... I tried
> 
> ```
> vim.o.fillchars = "stl: "
> ```
> 
> but this does not seem to change the behavior. Not a big deal, but if I knew how to clear these I would put it in my config to prevent them from showing up again. It's still rather mysterious to me why they appeared exactly when and where they did.

Hello. Did you find a way to disable this behavior ? Ever since I updated to 0.8 I'm seeing ^^^ pop up in lualine.

**Comment by zkwinkle** [comment]
> This is working as intended. Read `:h 'fillchars'`

Just wanted to chime in and say that it is not working as intended I don't think.
First of all I'd like to preface by saying that I get an empty status line when until I split my window then the '^' show up.

If I add to my config the line:
```
opt.fillchars = { eob = " ", stl = "u" }
```
then the '^' are changed out for 'u' (and the 'u' show up whether splitting or not splitting), but if I change that very same line to 
```
opt.fillchars = { eob = " ", stl = " " }
```
the '^' show up (only while splitting).

If there's a way to set that config such that the '^' don't show up when I'm splitting (which I'm guessing causes the characters to be highlighted, so the question is more how to setup my config such that the '^' don't show up even when the fillchars are being highlighted) then please do let me know.
