### ISSUE TITLE
Syntax highlighting for Haskell files broken on neovim 0.7.2: Types and functions are both white

### ISSUE THREAD

**Issue by MangoIV** [neovim/neovim#19818]
### Neovim version (nvim -v)

NVIM v0.7.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by nixbld  Features: +acl +iconv +tui

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

NixOS 22.11.20220816.6c6409e (Raccoon)

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

nix; nixpkgs-unstable;  github:nixos/nixpkgs/e9545762b032559c27d8ec9141ed63ceca1aa1ac

### How to reproduce the issue

```bash 
$ nix shell "github:nixos/nixpkgs/e9545762b032559c27d8ec9141ed63ceca1aa1ac"#neovim
``` 
```bash 
$ echo "module A where 
data A = B | C 

f x = x" > A.hs
``` 
```bash 
$ nvim A.hs
```

### Expected behavior

types should highlight in a different colour than functions (similarly to here)
```haskell
data A = B | C 

f x = x
``` 

### Actual behavior

types and functions both are highlighted white (which is horrible wrt readability)

**Comment by clason** [comment]
Please try with the official binaries (ideally nightly) from the Releases page and `nvim --clean`. 

If the issue persists, please open an issue upstream at vim/vim, since we take the syntax files from there verbatim.

**Comment by MangoIV** [comment]
`nvim --clean` behaves the same. If you wish I can report this bug upstream in `vim`; I'm sorry I didn't understand that you're explicitly relying on that with vim.

**Comment by clason** [comment]
Do test with Vim first, though.

**Comment by clason** [comment]
Actually, you should report it to the maintainer of the syntax file, which is the "Haskell Cafe mailing list" (`haskell-cafe@haskell.org`).
