### ISSUE TITLE
Assertion failure on accessing disconnected remote filesystem

### ISSUE THREAD

**Issue by andrewla** [neovim/neovim#19825]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1114-g36362ef0a

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Debian linux 5.17

### Terminal name/version

not relevant

### $TERM environment variable

not relevant

### Installation

not relevant

### How to reproduce the issue

Create a directory, start editing a file inside of it.
In another window, do a `chmod -x` on that directory.
Run `:terminal`

### Expected behavior

Either the terminal opens up or we get an error saying that there is an issue

### Actual behavior

nvim aborts with:

```
nvim: /usr/local/google/home/andrewla/local/packages/neovim/depot/src/nvim/channel.c:313: channel_job_start: Assertion `cwd == NULL || os_isdir_executable(cwd)' failed.
        Aborted
```

**Comment by andrewla** [comment]
Note that the actual issue was caused by a remote filesystem that disconnected, but it is the same assertion. I do not know why this assertion is necessary.

If you rmdir the directory while the editor is open, you'll get a terminal that starts in that now-deleted directory, and probably get some errors from your bashrc or from your shell itself, but nvim will have no issues. In the end I think the assertion is unnecessary for proper functioning; nothing in that function indicates that it relies on the executability of the cwd.

**Comment by zeertzjq** [comment]
See #9204

**Comment by zeertzjq** [comment]
Hmm, reverting #9204 doesn't seem to cause any problems?
