### ISSUE TITLE
Enable LuaJIT for ARM snap builds

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#19837]
### Feature already in Vim?

N/A

### Feature description

LuaJIT is currently disabled for ARM snap builds.
https://github.com/neovim/neovim/blob/a5ed89c972a23c46eb3988fe8c2c8ae0d7ed844f/snap/snapcraft.yaml#L54-L60

Here are some existing related PRs:
https://github.com/neovim/neovim/pull/12815
https://github.com/neovim/neovim/pull/12862

I confirmed that when building from source, Neovim with LuaJIT works on ARM.

Perhaps it would be possible to revert the code that disabled LuaJIT for ARM.

Additional context:

A plugin I created, [nvim-scrollview](https://github.com/dstein64/nvim-scrollview), used a `goto`. This caused an [issue](https://github.com/dstein64/nvim-scrollview/pull/75) on a Neovim snap build on ARM.

**Comment by clason** [comment]
@hurricanehrndz

**Comment by clason** [comment]
> A plugin I created, [nvim-scrollview](https://github.com/dstein64/nvim-scrollview), used a goto. This caused an https://github.com/dstein64/nvim-scrollview/pull/75 on a Neovim snap build on ARM.

I'm sorry, but you can't just assume that Neovim is built with LuaJIT -- we only guarantee PUC Lua, as there are several platforms (not just the snap for ARM) where LuaJIT is not available. Of course, as a plugin, you are free to restrict support further (in general or for specific features), but you will need to document this explicitly and add helpful checks and errors.

**Comment by dundargoc** [comment]
I think this should be reported to https://github.com/neovim/neovim-snap. We're not involved in external package managers anymore due to maintenance concerns.
