### ISSUE TITLE
vim.loop.spawn interactive commands dumping prompts into buffer

### ISSUE THREAD

**Issue by miversen33** [neovim/neovim#19839]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+580-g45ba2e147

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Ubuntu 20.04.4 LTS

### Terminal name/version

NA

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

Use the below configuration
```lua
-- minimal.lua
vim.api.nvim_create_user_command("DoTest",
  function(command_details)
    local hostname = command_details.args
    local stdout = vim.loop.new_pipe()
    local stderr = vim.loop.new_pipe()
    local stdin = vim.loop.new_pipe()
    vim.loop.read_start(stdout, function(_, data)
        print(string.format("STDOUT: %s", data))
    end)
    vim.loop.read_start(stderr, function(_, data)
        print(string.format("STDERR: %s", data))
    end)
    vim.loop.spawn("ssh", {
        args = {hostname},
        stdio = {stdin, stdout, stderr}
    })
  end, {
    nargs = 1,
})
```
Run neovim with this config and execute the loaded `:DoTest` command
```shell
$ nvim --clean -u minimal.lua
```
```
:DoTest somehost
```

### Expected behavior

The minimal config provided should consume all output from the process and print it out (with either the `STDOUT: ` header or the `STDERR: ` header on the message)

### Actual behavior

When the command being ran with [`vim.loop.spawn`](https://github.com/luvit/luv/blob/master/docs.md#uvspawnpath-options-on_exit) requires user interaction, it dumps the prompt into the current buffer. This seems to be incorrect behavior.

As an example, the above `DoTest` function will attempt to `ssh` into the `hostname` provided as an argument. If you do not have preauthentication on the host (IE, you need to input your password/passphrase), the prompt to do so is dumped into your current buffer as opposed to being consumed and printed out in the message area (which is what I would expect as I _am_ consuming the output from `stdout` and `stdin`).

Below is a screenshot showing the behavior in action
![image](https://user-images.githubusercontent.com/2640668/185546439-3dc3d2f1-c7e7-48aa-89f7-a479d985ae4b.png)

**Comment by zeertzjq** [comment]
It seems even if stdin and stdout are redirected, `ssh` still prompts for password, which means it possibly writes directly to pty, so maybe there is not solution to this.

**Comment by miversen33** [comment]
I will explore this outside of ssh to verify, that's an interesting point

**Comment by justinmk** [comment]
This is typical of pipes.
