### ISSUE TITLE
Turn off notification when detaching LSP client from buffer

### ISSUE THREAD

**Issue by mystilleef** [neovim/neovim#19838]
### Neovim version (nvim -v)

v0.8.0-dev-872-gbccb5de89

### Language server name/version

ALL

### Operating system/version

Fedora 36 Linux

### Steps to reproduce using "nvim -u minimal_init.lua"

1. Call `vim.lsp.buf_detach_client({bufnr}, {client_id})` programmatically.

### Expected behavior

LSP client should detach from buffer silently. No alerts or notifications should be displayed to the user.

### Actual behavior

A notification pops up every time an LSP client is programmatically detached from the buffer. 

This is distracting for users who deliberately detach the LSP client in `InsertMode` or `Zen Mode`.

**Comment by mystilleef** [comment]
I'm closing this issue. Binding `vim.notify` to `nvim-notify` causes this issue. Removing the bind solves the problem.

**Comment by mystilleef** [comment]
I'm reopening this. This is not a `vim-notify` issue. The default detach behavior should be silent unless explicitly requested in the API, or an exceptional event occurs.

**Comment by justinmk** [comment]
not another flag.

**Comment by glepnir** [comment]
try `vim.cmd('silent lua vim.lsp.buf_detach_client(0,1)`

**Comment by mfussenegger** [comment]
I think we could just remove the notify call in `buf_detach_client`. It's afaik synchronous so if someone wants feedback if it's done they could add a print call afterwards themselves

**Comment by justinmk** [comment]
That sounds much better!
