### ISSUE TITLE
When neovim startup, it gave 'VimEnter autocmd "*" Error'

### ISSUE THREAD

**Issue by lilx2018** [neovim/neovim#19842]
### Neovim version (nvim -v)

newest 5dc43265b1f966a9653cc552fa5301ee487a8116

### Vim (not Nvim) behaves the same?

not test

### Operating system/version

Windows 10 amd64

### Terminal name/version

cmder 201912 64bit

### $TERM environment variable

not sure

### Installation

build from source code

### How to reproduce the issue

I use leslie255/nvim-config as neovim work envirment, and nvy as GUI front, when I start nvy, it gave me an Error message (Chinese message) something like  'VimEnter autocmd "\*" Error' which autogrup contain invalid character:
处理 VimEnter 自动命令 "*" 时发生错误:
W18: 组名中含有无效字符

after compare each commit, I find it was introduced by commit **41d6b8a6d060a27a4841af678d6c6b2d111937a2** , beacuse commit f38c05bece0948fcadf943bbf80b9d9672da7059 didn't have this message.

### Expected behavior

Neovim with leslie255/nvim-config start with no error.

### Actual behavior

When I start neovim with leslie255/nvim-config, it gave me an Error message (Chinese message) something like  'VimEnter autocmd "\*" Error: autogrup contain invalid character' 
处理 VimEnter 自动命令 "\*" 时发生错误:
W18: 组名中含有无效字符

**Comment by clason** [comment]
Please test with `nvim --clean` (or `nvim --clean -u minimal.vim` if config is needed). Otherwise we have to assume that it's an error in your config that was hidden before.

**Comment by zeertzjq** [comment]
What does `:verbose autocmd VimEnter` show?

**Comment by zeertzjq** [comment]
Have you tried updating you plugins?

**Comment by clason** [comment]
From chat: outdated gitsigns plugin.
