### ISSUE TITLE
Remove PUC Lua 5.1 support

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#19849]
### Feature already in Vim?

N/A

### Feature description

For platforms where LuaJIT is not supported, Neovim can be built with PUC Lua 5.1.

There are some [differences](http://luajit.org/extensions.html) between LuaJIT and PUC Lua 5.1. For example, LuaJIT supports `goto`.

~To reduce the differences, this feature request, if possible, proposes that LuaJIT compiled without its JIT (`-DLUAJIT_DISABLE_JIT`) be used in place of PUC Lua 5.1 where applicable.~ **To reduce the differences, this feature request, if possible, proposes that Neovim's support for PUC Lua 5.1 be removed, and in place that LuaJIT be the only supported Lua engine (assuming it can be compiled without JIT support on unsupported platforms; I don't currently have access to such a platform at the moment to test).** This would be beneficial for plugin developers, who may be unfamiliar with the differences and not realize that some code they're writing may not work across different builds of Neovim. This happened for a plugin I wrote: https://github.com/dstein64/nvim-scrollview/pull/75.

Update: Text in bold was not present in the first draft of this feature request.

**Comment by jamessan** [comment]
> To reduce the differences, this feature request, if possible, proposes that LuaJIT compiled without its JIT (`-DLUAJIT_DISABLE_JIT`) be used in place of PUC Lua 5.1 where applicable.

This is really up to the distributors and whether they decide to build LuaJIT differently on different architectures.

For Neovim itself, we've merged the Lua manual into the built-in documentation, so that should help alleviate the problem of knowing what Lua constructs are supported.

I'm not sure there's anything else actionable here.

**Comment by dstein64** [comment]
> "This is really up to the distributors and whether they decide to build LuaJIT differently on different architectures."

I've changed the feature request to propose removal of PUC Lua support, rather than just propose the distribution be built differently. I think it would be beneficial for plugin development to have a single supported version of Lua, consistent with the goals expressed in `:help feature-compile` (bold added by me):

> USER EXPERIENCE
> 
> **Working intuitively and consistently is a major goal of Nvim.**
> 
> - Nvim always includes ALL features, in contrast to Vim (which ships with
>   various combinations of 100+ optional features). Think of it as a leaner
>   version of Vim's "HUGE" build. **This reduces surface area for bugs, and
>   removes a common source of confusion and friction for users.**
> 
> - **Nvim avoids features that cannot be provided on all platforms**; instead that
>   is delegated to external plugins/extensions. E.g. the `-X` platform-specific
>   option is "sometimes" available in Vim (with potential surprises:
>   http://stackoverflow.com/q/14635295).

**Comment by jamessan** [comment]
> I think it would be beneficial for plugin development to have a single supported version of Lua, consistent with the goals expressed in `:help feature-compile` 

That **is** Lua 5.1. LuaJIT is an implemention of Lua 5.1 that you can opt in to for more performance, at the expense of supporting far fewer platforms.  However, the API that should be targeted is PUC Lua.

**Comment by dstein64** [comment]
> "at the expense of supporting far fewer platforms"

My thought was that LuaJIT could work on whichever platforms you're referring to, but without JIT support. I don't have a way to currently test though. If so, the feature request here is that the LuaJIT API be the only supported target (as opposed to having PUC Lua be the current API that should be targeted). This would add more [functionality](https://luajit.org/extensions.html) and avoid differences between Neovim builds. If LuaJIT could not run on the platforms you're referring to (without JIT), then this feature request is void.

**Comment by clason** [comment]
I'm sorry, but that is a huge and frankly selfish ask: _you_ don't want to support PUC Lua, so you are asking _Neovim_ to drop support for a significant number of platforms where it builds and runs just fine. That is just not going to happen. (Your thought that LuaJIT can build on all(!) these platforms without JIT support is so far completely unsubstantiated.)

So you have two options:
1. make LuaJIT a hard dependency for _your_ plugin (with clear documentation and error handling, e.g., testing for `jit`);
2. help getting LuaJIT to build on these platforms.

**Comment by dstein64** [comment]
> "so you are asking Neovim to drop support for a significant number of platforms where it builds and runs just fine"

My feature request is conditional that LuaJIT run on those platforms, but without its JIT. I am not requesting Neovim drop support for any platforms.

> "frankly selfish ask"

The ticket was inspired by an issue I encountered for my own plugin, but the intent of my feature request had other plugin developers and users in consideration. My thought was that developers may assume that Neovim features available on their development platform are generally available, without realizing this may not be the case. The intent of this feature request is to reduce that gap. It would also impact users, since they could encounter errors when running plugins that have the aforementioned issue.

**Comment by justinmk** [comment]
This is a reasonable request, but out of scope. Lua 5.1 is the target.

**Comment by justinmk** [comment]
Targeting Lua 5.1 is intentional, because it is a smaller target. LuaJit has a bigger surface area (FFI, etc.), which would limit our ability to switch to other Lua 5.1 implementations.

Depending on the (future) momentum of LuaJit we can always revisit this.

**Comment by dstein64** [comment]
I just saw on the LuaJIT [FAQ](https://luajit.org/faq.html) that the interpreter is platform-specific, as it's written in assembler:
> "And the fast interpreter is written in assembler and must be ported, too."

That makes this feature request, as proposed, void, but perhaps there is some other way to narrow the differences in Lua features across platforms (and maintain LuaJIT's speed).

I see that a similar request—but without the conditional stated above—had been [presented](https://neovim.discourse.group/t/calling-neovim-internal-functions-with-luajit-ffi-and-rust/165/7) in a discussion last year:
> "I think neovim should enforce being compiled with luajit that way plugins wonn’t have to worry about what version of lua user has ."
