### ISSUE TITLE
-DCMAKE_INSTALL_PREFIX not working for man pages?

### ISSUE THREAD

**Issue by jdix531** [neovim/neovim#19850]
### Neovim version (nvim -v)

7.2.0

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ubuntu 20.04 wsl

### Terminal name/version

bash 5.0.17

### $TERM environment variable

xterm-256color

### Installation

self-biuld

### How to reproduce the issue

Hi, I expect to be able to run the following script (cat'd below) and have nvim install in home folder without needing to elevate to sudo and install at system level at all, however I get an error about system dir permissions for man files.

```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/josh/code/me/bootstrap/roles/install_nvim/files/neovim/build
touch build/.ran-cmake
ninja  -C build
ninja: Entering directory `build'
[0/2] Re-checking globbed directories...
[153/360] Generating auto/lua/vim_module.generated.h
LUAC_PRG is missing, embedding raw source
[360/360] Generating doc/tags
ninja  -C build install
ninja: Entering directory `build'
[0/2] Re-checking globbed directories...

[1/2] Install the project...
-- Install configuration: "Debug"
CMake Error at cmake_install.cmake:77 (file):
  file cannot create directory: /usr/local/share/man/man1.  Maybe need
  administrative privileges.
 
FAILED: CMakeFiles/install.util
cd /home/josh/code/me/bootstrap/roles/install_nvim/files/neovim/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
make: *** [Makefile:194: install] Error 1
josh@JDASI-PC:~/code/me/bootstrap/roles/install_nvim/files$ cat install_nvim.sh
git clone https://github.com/neovim/neovim
cd neovim
git checkout stable
make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/.local"
make install
```

### Expected behavior

Install to work without error all files being under ~/.local/. This might be just an assumption on my part and may be intended to not work this way.

### Actual behavior

Error described in reproduce stage.

**Comment by dundargoc** [comment]
The `git checkout stable` is sus, the `stable` is the same as the `v0.4.4`. Can you try version `v0.7.2` or even better just `master`?

**Comment by dundargoc** [comment]
We should probably update or remove the `stable` flag.

**Comment by jdix531** [comment]
Let me try that. I could have sworn it said I was on 0.7.2 somewhere but maybe I misread... just a moment!

**Comment by jdix531** [comment]
@dundargoc I just tested on master with same issue. When I run `git checkout stable` output says I'm at e8ee67339 NVIM v0.7.2 FYI. So I think `stable` seems to work still.

**Comment by dundargoc** [comment]
> When I run git checkout stable output says I'm at NVIM v0.7.2

Wut? I must've done something wrong then, I'll need to look into it. Thanks for testing it.

**Comment by dundargoc** [comment]
I forgot to update the `stable` tag in my fork, my bad.

It seems that `CMAKE_INSTALL_PREFIX` isn't being properly passed to `cmake/InstallHelpers.cmake` and it defaults to `/usr/local`. I'm unsure why I don't get the same error you do. I will look further into this.

The "Note: this uses a hidden option of CMake, but it's been shown to work with 2.8.11 thru 3.0.2." comment doesn't inspire a lot of confidence lol.

**Comment by jdix531** [comment]
@dundargoc I'm doing this in ubuntu wsl (mentioned in main post but want to be sure it is seen!) fyi. TYVM for looking into this with me. Can't think of why it would matter either.

**Comment by dundargoc** [comment]
I used ubuntu wsl as well, that's why I'm confused :)

**Comment by jdix531** [comment]
Hi @dundargoc, so not sure why but I tried again today and it seemed to work fine. Seems nothing changed then I'll have to chalk it up to something weird on this work pc?!

Thanks for your time, sorry we weren't able to get a meaningful reproduction!

**Comment by sperezconesa** [comment]
I had this same problem and it fixed itself by redownloading the repository and starting over.

I think it is possible that `make clean` was not enough and I should have had to `make distclean` instead. Possibly `make clean` didn't clean enough.

**Comment by hood** [comment]
`distclean` instead of `clean` solved the issue for me too, after having issue with the build looking for `cmake` in the wrong `homebrew` path.
