### ISSUE TITLE
Improve the `tabclose` Command

### ISSUE THREAD

**Issue by amarakon** [neovim/neovim#19859]
### Feature already in Vim?

No

### Feature description

I can also use `tabclose` followed by a number to close that tab number. These are some things I expected to work but did not:

- `tabclose 2-5` to delete tabs 2, 3, 4, 5
- `tabclose 2,5` to delete tabs 2, 5
- `tabclose left` to close all tabs to the left
- `tabclose right` to close all tabs to the right

The `left` and `right` options are debatable because a plugin called [tabops](https://github.com/vim-scripts/tabops) implements it. But the first two examples I believe should be baked into Neovim. Why should I not be able to specify a comma separated list or a range with hyphens? I think it would be pretty cool.

**Comment by justinmk** [comment]
> a plugin called [tabops](https://github.com/vim-scripts/tabops) implements it



> Why should I not be able to specify a comma separated list or a range with hyphens?

It would be another special-case DSL. Is there precedent for this in other Vim/Ex commands? The "range" part of a command, e.g. `:[range]tabclose` is the quasi-standard DSL already established. Adding more special-cases is generally something we avoid.

From `:help tabclose` I see:

```
:{count}tabc[lose][!]
:tabc[lose][!] {count}
		Close tab page {count}.  Fails in the same way as `:tabclose`
		above. >
		    :-tabclose	    " close the previous tab page
		    :+tabclose	    " close the next tab page
		    :1tabclose	    " close the first tab page
		    :$tabclose	    " close the last tab page
		    :tabclose -2    " close the 2nd previous tab page
		    :tabclose +	    " close the next tab page
		    :tabclose 3	    " close the third tab page
		    :tabclose $	    " close the last tab page
		    :tabclose #     " close the last accessed tab page
```

**Comment by lougreenwood** [comment]
> :tabclose 3	    " close the third tab page

It would be nice to at least close a tab page by id, like is possible with buffers.
