### ISSUE TITLE
Idea: ability to reload a plugin, turn it off, unload it from memory

### ISSUE THREAD

**Issue by cyboflash** [neovim/neovim#1985]
I wasn't able to find it this suggestion anywhere so I decided to post it. 

It would be nice to have the ability to turn off the plugin, i.e. not run it on certain types of files. Maybe even unload it from memory if there is no need for it. And if the need arises reload it. 

This could provide better plugin management for different types of projects, i.e. use plugin set 1 for project 1, plugin set 2 for project 2, etc.

**Comment by dkns** [comment]
There are plugin managers like neobundle or plug that let you load plugins only for specific filetypes (amidst other options) so e.g. you can load emmet.vim only when editing html files.

**Comment by tarruda** [comment]
One of my goals is to provide reloading/unloading support for all remote plugins

**Comment by justinmk** [comment]
I don't think we need an open issue to track this.
