### ISSUE TITLE
Expanding wildcards in directories with several self-referential links is very, very slow

### ISSUE THREAD

**Issue by personalizedrefrigerator** [neovim/neovim#19858]
### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

yes, 8.2.3995

### Operating system/version

PoP OS 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

apt

### How to reproduce the issue

1. In a UNIX shell, create a directory with several self-referential links:
```
$ mkdir foo
$ cd foo
$ ln -s ./ link1
$ ln -s ./ link2
$ ln -s ./ link3
$ ln -s ./ link4
$ ln -s ./ link5
$ ls
link1  link2  link3  link4  link5
```
2. Open `nvim` in that directory:
```
$ vim --clean
```
3. Expand `**`:
```vim
:echom expand('**')
```
4. Press enter

### Expected behavior

Neovim should expand the wildcard within a reasonable amount of time.

### Actual behavior

Neovim attempts to expand `**` for a very, very long time (I haven't let it run long enough to finish).

**Comment by personalizedrefrigerator** [comment]
See also https://github.com/vim/vim/issues/10946

**Comment by justinmk** [comment]
The related vim patch was merged in https://github.com/neovim/neovim/pull/19866

Related:

- https://github.com/neovim/neovim/issues/16272
- https://github.com/neovim/neovim/pull/1043
- https://github.com/neovim/neovim/issues/1035
