### ISSUE TITLE
Statusline doesn't respect winhighlight

### ISSUE THREAD

**Issue by shadmansaleh** [neovim/neovim#19865]
### Neovim version (nvim -v)

0.8.0 commit ff5cfcdea

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Fedora Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

Built from repo

### How to reproduce the issue

```vim
" file: minimal_init.vim
set stl=%#Normal#
hi NormalCustom ctermbg=grey
hi Normal ctermbg=blue
set winhighlight=Normal:NormalCustom
```

```sh
nvim --clean -u minimal_init.vim
```

### Expected behavior

Statusline highlight should respect winhighlight option. So statusline should blend with background and be invisible as it's highlighted with Normal .

### Actual behavior

Statusline get's highlighted with global Normal instead of with NormalCustom as defined in winhighlight of the windows.

**Comment by shadmansaleh** [comment]
ping @famiu

**Comment by lbrayner** [comment]
Highlighting **hl-StatusLine** has no effect if `winhighlight` is set in that window, and it intermittently affects other windows too, but it works againg after a few window changes.

**Comment by justinmk** [comment]
Does it work before https://github.com/neovim/neovim/pull/13457 ?

**Comment by shadmansaleh** [comment]
> Does it work before https://github.com/neovim/neovim/pull/13457 ?

No it didn't work before that pr either .

**Comment by shadmansaleh** [comment]
This seems to fix the issue. But haven't yet checked if it breaks something else
```diff
diff --git a/src/nvim/statusline.c b/src/nvim/statusline.c
index e868a79b9..062f476ac 100644
--- a/src/nvim/statusline.c
+++ b/src/nvim/statusline.c
@@ -1398,7 +1398,7 @@ int build_stl_str_hl(win_T *wp, char *out, size_t outlen, char *fmt, int use_san
       if (*fmt_p == '#') {
         stl_items[curitem].type = Highlight;
         stl_items[curitem].start = out_p;
-        stl_items[curitem].minwid = -syn_name2id_len(t, (size_t)(fmt_p - t));
+        stl_items[curitem].minwid = -syn_get_final_id(syn_name2id_len(t, (size_t)(fmt_p - t)));
         curitem++;
         fmt_p++;
       }
```

**Comment by bfredl** [comment]
> Do we like have 3 separate systems for regular_hl, winhl and namespaced hightlights on top of that exception cases for Normal group also two different structs to store hl info for regular and namespaced hl ?

No we do not. There might be bugs caused by the latest refactor tho.

**Comment by shadmansaleh** [comment]
> No we do not There might be bugs caused by the latest refactor tho.

Good to know that's not the case.
