### ISSUE TITLE
Pointers for compiling neovim to webassembly

### ISSUE THREAD

**Issue by leopsidom** [neovim/neovim#19863]
### Feature already in Vim?

Yes. https://github.com/rhysd/vim.wasm

### Feature description

Trying to compile neovim to webassembly and use it on the web. Following  emscripten compilation process, I need to run cmake on the project  first. After some tweaking, however I'm still getting the following error when running cmake.

>   We only found some files of LibIntl, not all of them.  Perhaps your
  installation is incomplete or maybe we just didn't look in the right place?
  This package is REQUIRED and you need to install it or adjust CMake
  configuration in order to continue building nvim.

>  Relevant CMake configuration variables:

    LibIntl_INCLUDE_DIR=/home/ubuntu/emsdk/upstream/emscripten/cache/sysroot/include
    LibIntl_LIBRARY=<not found>

Wonder if anyone knows what I'm missing ? I'm trying to compile on Ubuntu.

> #21~20.04.1-Ubuntu

Notes: I'm seeing the test for LibIntl  had  failed:

> -- Performing Test HAVE_WORKING_LIBINTL - Failed

But when I actually  compile the testing code on my machine with gcc/emcc. It works.

**Comment by leopsidom** [comment]
Okay I think this has something to do with `emcmake` since `cmake` itself works, hmm.

**Comment by leopsidom** [comment]
Actually this has something to do with neovim configuration as well. Since `emcmake` with the following check succeeds:

```
cmake_minimum_required(VERSION 3.10)

# set the project name
project(LIBINTL_TEST)

include(CheckCSourceCompiles)

check_c_source_compiles("
#include <libintl.h>

int main(int argc, char** argv) {
  gettext(\"foo\");
  ngettext(\"foo\", \"bar\", 1);
  bindtextdomain(\"foo\", \"bar\");
  bind_textdomain_codeset(\"foo\", \"bar\");
  textdomain(\"foo\");
}" HAVE_WORKING_LIBINTL)

message("HAVE_WORKING_LIBINTL: ${HAVE_WORKING_LIBINTL}")
# add the executable
add_executable(main main.c)
```

**Comment by jamessan** [comment]
> ### Feature already in Vim?
> 
> Yes. [rhysd/vim.wasm](https://github.com/rhysd/vim.wasm)

No.  Vim was forked and heavily modified to allow compiling to webassembly.

If that's something you're interested in doing for neovim, go for it.  I don't think that requires anything in neovim proper to happen, though.

**Comment by justinmk** [comment]
First step would be to see if emscripten can compile libuv. https://github.com/libuv/help/issues/128#issuecomment-589284650 suggests not. Related emscripten issue https://github.com/emscripten-core/emscripten/issues/10556 was closed by one of those god forsaken "stale" bots.

**Comment by mikesol** [comment]
I just came across this issue - I've actually had success compiling a small subset of the library that doesn't use libuv, Lua or RPC. So it's possible, and I get a sense that a lot of the core functionality works independently of these dependencies. I'm not sure what a good next step would be as I unfortunately don't have time to pursue it further, but I wanted to report the result as I did this when I was evaluating various options for browser-based editing.

**Comment by naruaway** [comment]
FYI I made the first experimental version of "Neovim in browser using WASM" work!  The deployed one is https://nvim.nry.app and we can continue the discussion in https://neovim.discourse.group/t/compile-to-webassembly/2736 since this issue is already closed

**Comment by justinmk** [comment]
@naruaway NICE! Please feel free to discuss here or at https://github.com/neovim/neovim/discussions . If you want to share build steps or send a PR to adjust things needed to make this easier, that would be very welcome.

**Comment by svermeulen** [comment]
@naruaway Can you share how you achieved this?  In particular, wondering how you avoided the libuv blocker mentioned above
