### ISSUE TITLE
fails to buid: 'msgpack_object_union’ has no member named ‘f64’

### ISSUE THREAD

**Issue by fd0** [neovim/neovim#1986]
The latest version 6e992876ea043fe7fe748d5da5e3b511b60d06a5 fails to build for me, running the latest Arch Linux:

    $ make
    [...]
    [ 81%] Building C object src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/channel.c.o
    [ 81%] Building C object src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/helpers.c.o
    /home/fd0/src/neovim-pkg/neovim/src/nvim/msgpack_rpc/helpers.c: In function ‘msgpack_rpc_to_float’:
    /home/fd0/src/neovim-pkg/neovim/src/nvim/msgpack_rpc/helpers.c:89:18: error: ‘msgpack_object_union’ has no member named ‘f64’
       *arg = obj->via.f64;
                      ^
    /home/fd0/src/neovim-pkg/neovim/src/nvim/msgpack_rpc/helpers.c:90:23: error: ‘MSGPACK_OBJECT_FLOAT’ undeclared (first use in this function)
       return obj->type == MSGPACK_OBJECT_FLOAT;
                           ^
    /home/fd0/src/neovim-pkg/neovim/src/nvim/msgpack_rpc/helpers.c:90:23: note: each undeclared identifier is reported only once for each function it appears in
    /home/fd0/src/neovim-pkg/neovim/src/nvim/msgpack_rpc/helpers.c: In function ‘msgpack_rpc_to_object’:
    /home/fd0/src/neovim-pkg/neovim/src/nvim/msgpack_rpc/helpers.c:123:10: error: ‘MSGPACK_OBJECT_FLOAT’ undeclared (first use in this function)
         case MSGPACK_OBJECT_FLOAT:
              ^
    /home/fd0/src/neovim-pkg/neovim/src/nvim/msgpack_rpc/helpers.c: In function ‘msgpack_rpc_to_float’:
    /home/fd0/src/neovim-pkg/neovim/src/nvim/msgpack_rpc/helpers.c:91:1: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
    src/nvim/CMakeFiles/nvim.dir/build.make:2864: recipe for target 'src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/helpers.c.o' failed
    make[2]: *** [src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/helpers.c.o] Error 1
    CMakeFiles/Makefile2:110: recipe for target 'src/nvim/CMakeFiles/nvim.dir/all' failed
    make[1]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
    Makefile:117: recipe for target 'all' failed
    make: *** [all] Error 2
    [1]    27867 exit 2     make
    make  39.84s user 3.12s system 95% cpu 45.087 total

I did a git bisect against 28dcfcf325d222ae311bf972997c92bc1efd3e8f (known good revision), the bad commit seems to be dd12238329477afb75373c0974230519ebc5c0a9.

**Comment by camponez** [comment]
I also did the bisect and found this commit: ec5e94518e8e631e

**Comment by camponez** [comment]
I solve it!

cd .deps
rm -rf build

and then folow the instructions to build third-parties:

https://github.com/neovim/neovim/wiki/Building-Neovim#controlling-the-build-for-third-party-dependencies-1588

**Comment by justinmk** [comment]
rm -rf build .deps && make
