### ISSUE TITLE
`<C-I>` and `<Tab>` mappings are not separated and act the same

### ISSUE THREAD

**Issue by ghillb** [neovim/neovim#19860]
### Neovim version (nvim -v)

v0.8.0-dev commit 35653e6bc

### Vim (not Nvim) behaves the same?

yes it has, with .vimrc (`nnoremap <C-I> <C-I>` `nnoremap <Tab> :echo 'tab pressed'<cr>`) version (8.2.3995)

### Operating system/version

Windows 10, WSL 2 Ubuntu 22.04

### Terminal name/version

Windows Terminal Version: 1.14.1962.0

### $TERM environment variable

xterm-256color

### Installation

Ubuntu neovim unstable ppa: https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable

### How to reproduce the issue

1. create test `init.lua` that creates mappings:
```lua
vim.keymap.set({ "n", "v" }, "<c-i>", "<c-i>")
vim.keymap.set({ "n", "v" }, "<tab>", ":echo 'tab pressed'<cr>")

```
2. Start neovim with test `init.lua`:
```
nvim --clean -u init.lua
```
3. Try the mappings `<tab>` and `<c-i>`

### Expected behavior

Mappings are separated, as described in PR (https://github.com/neovim/neovim/pull/17932#issue-1188088238):

- Pressing `<tab>` prints 'tab pressed'.
- Pressing `<c-i>` has default behavior (jump list)

### Actual behavior

Mappings are not separated:

- Pressing `<tab>` prints 'tab pressed'.
- Pressing `<c-i>` prints 'tab pressed'.

**Comment by zeertzjq** [comment]
I don't think Windows Terminal supports this.
