### ISSUE TITLE
winhighlight doesn't work for NormalNC

### ISSUE THREAD

**Issue by lbrayner** [neovim/neovim#19871]
### Neovim version (nvim -v)

0.8.0 commit ff5cfcdeab2446459ab59d44ce173ef811902c49

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 20.04

### Terminal name/version

st 0.8.5

### $TERM environment variable

st-256color

### Installation

Neovim PPA unstable

### How to reproduce the issue

nvim --clean
:set termguicolors
:highlight NormalNC ctermbg=236 guibg=#303030
:sp
:set winhighlight=NormalNC:NONE
:wincmd w

### Expected behavior

Window doesn't get highlighted when it becomes not current.

### Actual behavior

Window is highlighted with global NormalNC, completely disregarding local winhighlight.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/13457 ?

**Comment by lbrayner** [comment]
It was definitely working on nightly until exactly a week ago (last Sunday).
