### ISSUE TITLE
inccommand: Weird behavior when using delete on a range

### ISSUE THREAD

**Issue by woosaaahh** [neovim/neovim#19878]
### Neovim version (nvim -v)

v0.8.0-dev-905-g6b9852cc4

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

GNU/Linux - Arch Linux 5.19

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

nightly build

### How to reproduce the issue

```
printf '1\n2\n3\n4\n5 <\n6\n7\n8\n9\n' > test.txt
nvim --clean test.txt
:5
:-1;+3d
```

### Expected behavior

`:-1;+3d` should delete lines from 4 to 7 (included).

### Actual behavior

Most of the time, nvim deletes lines from 1 to 3 (included).
Sometime, nvim deletes lines from 3 to 6 (included).

**Comment by zeertzjq** [comment]
Only happen when `'inccommand'` is set.

**Comment by woosaaahh** [comment]
I don't know if that can help but : 
- I use `inccommand=split`
- The issue start from commit 7e1cf6b7 "fix(inccommand): parse the command to check if it is previewable" 2022-06-28

**Comment by justinmk** [comment]
@famiu

**Comment by woosaaahh** [comment]
Thanks !
