### ISSUE TITLE
":write ++p" should create parent directories (similar to mkdir -p)

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#19884]
1. `:write ++p foo/bar/baz.txt` should create parent directories `foo/bar/` if they do not exist
    - Note: `:foo ++...` is usually for options. No existing options have a single-char abbreviation (presumably by design), so it's safe to special-case `++p` here. 
    - `BufWriteCmd` can see this flag via `v:cmdarg` 
3. same for `writefile(..., 'foo/bar/baz.txt', 'p')`
4. others?

**Comment by jdhao** [comment]
The first case can be easily solved by defining an autocmd, something like this:

```lua
vim.api.nvim_create_autocmd({ "BufWritePre" }, {
  pattern = "*",
  group = vim.api.nvim_create_augroup("auto_create_dir", { clear = true }),
  callback = function(ctx)
    local dir = vim.fn.fnamemodify(ctx.file, ":p:h")
    vim.fn.mkdir(dir, "p")
  end
})
```

This is has been discussed in [reddit](https://www.reddit.com/r/neovim/comments/wtqzi5/hey_you_do_not_need_a_plugin_for_this_feature/) before.

**Comment by vigoux** [comment]
Maybe there could also be an option so that `++p` is the default behavior of `:edit`? That would remove some mental burden for some people (including me).

**Comment by matveyt** [comment]
`:edit` can create a buffer using arbitrary name. It's not a problem if path does not exist (yet). This is `:write` command that will throw `E212`. So maybe we should define instead an option, say, `&automkdir` that will allow silent creation of intermediate directories by `:write` et al.?

**Comment by matveyt** [comment]
As a side note, `BufWritePre` may fail for some "special" buffers using custom `BufWriteCmd`. Yes, `BufWritePre` will not be triggered automatically, but some plugins may force it anyway. So, say, netrw writing into network file may (will?) break the code above. On the other hand, imaginary `&automkdir` should work well.

>same for writefile(..., 'foo/bar/baz.txt', 'p')

Function(s) should probably _not_ obey option(s), so passing extra parameter instead looks right.

**Comment by justinmk** [comment]
> `:edit` can create a buffer using arbitrary name. It's not a problem if path does not exist (yet). This is `:write` command that will throw `E212`. 

Oops, right. Updated the issue.

> So maybe we should define instead an option, say, `&automkdir` that will allow silent creation of intermediate directories by `:write` et al.?

Could be a default autocmd. Probably not a new option. The reason for proposing `++p` is to avoid new options and make the behavior opt-in.

My personal interest in this is so that setting up a new machine can be very easy out-of-the-box:

    :exe 'e' stdpath('config').'/init.vim'
    :write ++p

**Comment by matveyt** [comment]
Autocmd might be not flexible enough. I mean how to switch it on/off for a single write command? And if we are going to have ++p in core anyway then why put its implementation into script?

On the other hand, adding ++p to all of write/update/saveas and implementing it in C source looks legit to me. BufWriteCmd plugins could then read this option through v:cmdarg if they want to.

**Comment by justinmk** [comment]
> And if we are going to have ++p in core anyway then why put its implementation into script?

Wouldn't. Autocmd would only be if we don't want ++p.

**Comment by matveyt** [comment]
So how end-user could adjust it then? Only to delete augroup globally? And how to get it back working w/o restarting application? If autocmd solution is adopted it should be as flexible as ++opt, imo.

**Comment by evanrittenhouse** [comment]
@matveyt @justinmk I'm happy to take this on if/when we decide on an approach. I haven't contributed to Neovim before though, so would appreciate some guidance if you can spare the time!

**Comment by justinmk** [comment]
@evanrittenhouse I updated the main description here based on feedback, and it reflects the decided approach (to start with, at least). Guidance is in https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md

**Comment by evanrittenhouse** [comment]
@justinmk Great, thank you. I was looking at the codebase - it seems like this change would probably occur in `os/fileio.c`. Is that right?

**Comment by justinmk** [comment]
yes
