### ISSUE TITLE
Cannot mutate tables in global vim variables directly

### ISSUE THREAD

**Issue by musjj** [neovim/neovim#19889]
### Neovim version (nvim -v)

v0.8.0-dev-739-ge59bc078d

### Vim (not Nvim) behaves the same?

vim does not provide a Lua API

### Operating system/version

Microsoft Windows [Version 10.0.19043.1889]

### Terminal name/version

alacritty 0.10.1 (2844606)

### $TERM environment variable

xterm-256color

### Installation

scoop

### How to reproduce the issue

```lua
:lua vim.g.var = {}
:lua vim.g.var["foo"] = "bar"
:lua print(vim.inspect(vim.g.var)) -- {}
```
The same behaviour occurs in `vim.b`, `vim.w`, `vim.t`, etc.

### Expected behavior

Like any other Lua variables, values like tables in vim variables should be mutable.

### Actual behavior

Attempting to mutate the table leads to no change to the table.
An alternative solution is to store the value to a different variable, then mutate that:
```lua
:lua vim.g.var = {}
:lua var = vim.g.var
:lua var["foo"] = "bar"
:lua vim.g.var = var
:lua print(vim.inspect(vim.g.var)) -- { foo = "bar" }
```

**Comment by clason** [comment]
This is a known issue: #12544
