### ISSUE TITLE
A removable command line

### ISSUE THREAD

**Issue by aj3423** [neovim/neovim#19893]
### Feature already in Vim?

No

### Feature description

![image](https://user-images.githubusercontent.com/4710875/185917777-aaa562e4-b94c-475f-9373-7f4b0de0a7f9.png)
Maybe this line can be replaced with a floating window or integrated in the status line.

**Comment by clason** [comment]
Please search previous issues and PRs before making such low-effort feature requests.

(Hint: look for `set cmdheight=0` and related discussions.)
