### ISSUE TITLE
Make 'display' lastline (aka @@@) customizable

### ISSUE THREAD

**Issue by doums** [neovim/neovim#19908]
### Feature already in Vim?

No

### Feature description

Hi,
The option `display` is used to configure the way truncated last lines, that do not fit into the editor window, are marked. When `display` includes `lastline` or `truncate`, `@@@` is put to indicate the rest of the line is not displayed.
Currently, customize that string `@@@` is not possible because it's hard-coded.
https://github.com/neovim/neovim/blob/master/src/nvim/drawscreen.c#L1876-L1907

The purpose here is to make it customizable. For example, we could use the `fillchar` option for it.

**Comment by clason** [comment]
I think this is request that should first be made to Vim; if they add it, we can port the patch, and both projects profit (and we avoid a needless divergence in option name).

**Comment by doums** [comment]
https://github.com/vim/vim/issues/10963

**Comment by clason** [comment]
You probably should point to the _Vim_ code in your Vim issue ;) Otherwise it'll get a dim reception.

(It's in the same function, just search for `@`.)

**Comment by doums** [comment]
Hey, just to let you know, a patch just landed into Vim https://github.com/vim/vim/commit/4ba5f1dab656103e8f4a4505452d1816b9e83c1e
