### ISSUE TITLE
Breaking change of API nvim__set_hl_ns renaming

### ISSUE THREAD

**Issue by ray-x** [neovim/neovim#19902]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-920-gd5328ea40

### Vim (not Nvim) behaves the same?

NA. Neovim specific API

### Operating system/version

Linux arch

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

cmake

### How to reproduce the issue

nvim__set_hl_ns was renamed to nvim_set_hl_ns and all the reference to it is invalid now.

### Expected behavior

mentioned in 
https://github.com/neovim/neovim/issues/14090#issuecomment-799285918

### Actual behavior

I am fine with it. Only thing is that it should be metioned in breaking changes.

**Comment by fsouza** [comment]
Not a maintainer, but my understanding is that `nvim__` is by definition unstable, and it breaking shouldn't require a notice? I'll let maintainers chime in though.

**Comment by vigoux** [comment]
@fsouza is right `nvim__` API are unstable thus changes to them don't require any notice.

Closing this issue then.
