### ISSUE TITLE
Can't use custom lua function as expand for vim.ui.input

### ISSUE THREAD

**Issue by danielo515** [neovim/neovim#19907]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

I don't know

### Operating system/version

macOS 12.1

### Terminal name/version

iterm/2

### $TERM environment variable

does not matter 

### Installation

brew

### How to reproduce the issue

Hello, as always thanks for neovim and its lua API.
I noticed that vim.ui.input does not work properly when providing a custom completion function which is a lua require string. It throws an error saying that such function does not exist. However, the same completion definition works when defining a regular command (check below)

Here is a small reproduction example:

```lua
-- lua/user/example.lua
local M = {}

function M.expand()
  ---@diagnostic disable-next-line: missing-parameter
  return vim.fn.expand "<cword>"
end
return M

-- init.vim

  vim.ui.input({
    completion = "custom,v:lua.require'user.example'.expand",
  }, function(text)
    print(text)
  end)
```

### Expected behavior

I want it to work. If I try the same completion mechanism in a command definition it does work without problems:

```vim
command! -nargs=+ -complete=custom,v:lua.require'user.example'.expand Test echo 'Hello'
```

### Actual behavior

If throws the following error:

```
E5108: Error executing lua Vim:E117: Unknown function: v:lua.require'user.telescope.finders'.expand
stack traceback:
	[C]: at 0x0110115110
	...e/pack/packer/start/dressing.nvim/lua/dressing/input.lua:167: in function <...e/pack/packer/start/dressing.nvim/lua/dressing/input.lua:156>
```

**Comment by zeertzjq** [comment]
Works for me?

**Comment by justinmk** [comment]
Try https://vi.stackexchange.com for questions about usage and configuration.

The issue tracker is for bugs and feature requests.
