### ISSUE TITLE
Lua function vim.fn.system doesn't do the same as described in the documentation 

### ISSUE THREAD

**Issue by Xyhlon** [neovim/neovim#19914]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+399-g58323b1fe

### Vim (not Nvim) behaves the same?

lua issue

### Operating system/version

Arch Linux x86_64 5.18.16-arch1-1-surface

### Terminal name/version

alacritty 0.10.1 ()

### $TERM environment variable

xterm-256color

### Installation

manual

### How to reproduce the issue

#add to your shell rc eg. config.fish .bashrc .zshrc something like echo "hello this will be parsed"
:echo system(["echo","hi"])
:lua P(vim.fn.system("echo 'hi'"))

### Expected behavior

hi

### Actual behavior

hello this will be parsed\nhi\n

**Comment by zeertzjq** [comment]
Isn't this exactly what the documented behavior should be?

> 		If {cmd} is a String it runs in the 'shell'

**Comment by Xyhlon** [comment]
yet it does not return the same string as the system non lua function from vim, hence it is a issue. Am I incorrect about that?

**Comment by zeertzjq** [comment]
If you want to the equivalent to that, use `vim.fn.system({'echo', 'hi'})` instead.

**Comment by Xyhlon** [comment]
thank you

**Comment by zeertzjq** [comment]
In Vim script you also used `[]` didn't you?
