### ISSUE TITLE
handle full input buffers by allocating memory and consuming when the buffer is empty

### ISSUE THREAD

**Issue by tarruda** [neovim/neovim#1991]
This will simplify `input_enqueue` by allowing any amount of data(memory-limited) to be written by clients/UIs.

Also fixes some pending issues:

- `input_buffer`(input.c:`input_enqueue`) can lose data when pasting data from the clipboard using the terminal
- `read_buffer`(input.c:`read_cb`) can lose data if `input_buffer` is full.

(This is only valid after #1820 is merged)

**Comment by justinmk** [comment]
are these related?

https://github.com/neovim/neovim/issues/1813

https://github.com/neovim/neovim/issues/1714

**Comment by oni-link** [comment]
@justinmk, yes.

**Comment by justinmk** [comment]
@tarruda Is this still planned? Got another report of paste losing data: https://github.com/neovim/neovim/issues/3377

**Comment by tarruda** [comment]
> @tarruda Is this still planned? Got another report of paste losing data: #3377

Since the UI was refactored to run in a another thread, this is no longer a problem because nvim always allocates memory and input is pushed to a dynamic queue(though we need to stop reading input if the queue size grows too big). I'm closing this and reopening #3377 which is another problem
