### ISSUE TITLE
E319: No "python3" provider found. Run ":checkhealth provider"

### ISSUE THREAD

**Issue by DoctorKnowsBetter** [neovim/neovim#19911]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no, vim 8.1

### Operating system/version

20.04.3 LTS (Focal Fossa)

### Terminal name/version

lxterminal 0.3.2

### $TERM environment variable

xterm-256color

### Installation

Tarball

### How to reproduce the issue

```
:python print('test')
E319: No "python3" provider found. Run ":checkhealth provider"
```

### Expected behavior

The python code should run.

### Actual behavior

Python code not executing as cmd.
Because of what UltiSnips do not work.

**:checkhealth provider**
```
provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: Disabled (g:loaded_python3_provider=1).  This might be due to some previous error.
  - INFO: Using: g:python3_host_prog = "/home/user/venv-home/bin/python3"
  - INFO: Executable: /home/user/venv-home/bin/python3
  - INFO: Python version: 3.8.10
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - INFO: $VIRTUAL_ENV is set to: /home/user/venv-home
  - INFO: Python version: 3.8.10
  - OK: $VIRTUAL_ENV provides :!python.

## Ruby provider (optional)
  - INFO: Disabled (g:loaded_ruby_provider=0).

## Node.js provider (optional)
  - INFO: Disabled (g:loaded_node_provider=0).

## Perl provider (optional)
  - INFO: Disabled (g:loaded_perl_provider=0).
```

**Comment by justinmk** [comment]
Try https://vi.stackexchange.com for questions about usage and configuration.

The issue tracker is for bugs and feature requests.

**Comment by codeprefect** [comment]
Hey @DoctorKnowsBetter,

You can set the value to `nil`.
```[lua]
vim.g.loaded_python3_provider = nil
```
I use Lua, so you can rewrite that in VimScript if you use vim.
