### ISSUE TITLE
CurSearch from vim 9

### ISSUE THREAD

**Issue by ckangnz** [neovim/neovim#19926]
### Feature already in Vim?

Yes Vim 9

### Feature description

I recently migrated from vim and one thing that i loved from vim was having a new highlight group CurSearch which is still missing in neovim.

I used to use a plug-in for this but since it’s native in normal vim i removed it from my plugin list. I don’t want to add it again just for neovim. Can this be please added?

**Comment by clason** [comment]
It _is_ in Neovim -- which version are you looking at?

**Comment by ckangnz** [comment]
@clason i'm on `NVIM v0.7.2` apparently

<img width="548" alt="image" src="https://user-images.githubusercontent.com/17423698/188016405-341743ff-ec3e-449e-9225-6d12321be79c.png">
But i don't see it in my `:highlight`
