### ISSUE TITLE
Make Both `init.lua`  and `init.vim` Work

### ISSUE THREAD

**Issue by amarakon** [neovim/neovim#19948]
### Feature already in Vim?

No

### Feature description

I want to have both `init.vim` and `init.lua`. The workaround I currently use is to create `init.vim` and `lua/config.lua`, and then put `lua require("config")` at the top of my `init.vim`. I think it would be cool that if a user has both an `init.lua` and an `init.vim`, it would source both of them: the `init.lua` first, and the `init.vim` second.

**Comment by bfredl** [comment]
explicitly defining the order as you already do is clearer.
