### ISSUE TITLE
WinScrolled not triggered on a wrapped line

### ISSUE THREAD

**Issue by Akianonymus** [neovim/neovim#19968]
### Neovim version (nvim -v)

v0.8.0-dev-818-g0d9e09bf6

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

EndeavourOS Linux x86_64

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

AUR nightly

### How to reproduce the issue

nvim --clean

`set nu`

`enew`

Copy contents of this file to newly created buffer: https://pastebin.com/raw/5ft6fYnb

`au WinScrolled * :echo getcurpos(0)`

Just to scroll through the wrapped lines

`map j gj` 

Now hold `j` till it scrolls through the last line

### Expected behavior

It should trigger WinScrolled autocmd and print the getcurpos(0)

### Actual behavior

It doesn't do anything on a wrapped line

https://user-images.githubusercontent.com/32216346/187023301-44862687-e3ba-4cde-89a3-d7d0ecda3895.mp4

**Comment by zeertzjq** [comment]
This should fix the issue:
```diff
diff --git a/src/nvim/buffer_defs.h b/src/nvim/buffer_defs.h
index d22ab266f..ab15108fe 100644
--- a/src/nvim/buffer_defs.h
+++ b/src/nvim/buffer_defs.h
@@ -1243,6 +1243,7 @@ struct window_S {
   // four fields that are only used when there is a WinScrolled autocommand
   linenr_T w_last_topline;          ///< last known value for w_topline
   colnr_T w_last_leftcol;           ///< last known value for w_leftcol
+  colnr_T w_last_skipcol;           ///< last known value for w_skipcol
   int w_last_width;                 ///< last known value for w_width
   int w_last_height;                ///< last known value for w_height
 
diff --git a/src/nvim/window.c b/src/nvim/window.c
index ffbb0fa27..5b8a69f6e 100644
--- a/src/nvim/window.c
+++ b/src/nvim/window.c
@@ -5362,6 +5362,7 @@ void may_trigger_winscrolled(void)
   win_T *wp = curwin;
   if (wp->w_last_topline != wp->w_topline
       || wp->w_last_leftcol != wp->w_leftcol
+      || wp->w_last_skipcol != wp->w_skipcol
       || wp->w_last_width != wp->w_width
       || wp->w_last_height != wp->w_height) {
     char winid[NUMBUFLEN];
@@ -5375,6 +5376,7 @@ void may_trigger_winscrolled(void)
     if (win_valid_any_tab(wp)) {
       wp->w_last_topline = wp->w_topline;
       wp->w_last_leftcol = wp->w_leftcol;
+      wp->w_last_skipcol = wp->w_skipcol;
       wp->w_last_width = wp->w_width;
       wp->w_last_height = wp->w_height;
     }
```

**Comment by Akianonymus** [comment]
I can confirm, it does fix the problem.
