### ISSUE TITLE
PATH is wrong when using winget  install

### ISSUE THREAD

**Issue by amkkr** [neovim/neovim#19966]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

windows 11 Pro 22000.918

### Terminal name/version

Windows PowerShell, PSVersion 5.1.22000.832

### $TERM environment variable

n/a

### Installation

winget install Neovim

### How to reproduce the issue

1. Open PowerShell
2. Type the following command to install neovim
```PowerShell
 winget install Neovim
```
3. In the System > About window, click the Advanced system settings link at the bottom of the Device specifications section.
4. In the System Properties window, click the Advanced tab, then click the Environment Variables button near the bottom of that tab.
5.  Incorrect paths have been added and will need to be corrected

### Expected behavior

should be added
```
C:\Program Files\Neovim\bin
```

### Actual behavior

It actually added
```
C:\Program Files\Neovim\/bin
```

windows 11 Pro 22000.918
![image](https://user-images.githubusercontent.com/55781271/187019863-37fad4da-c1c5-4c95-853d-9060812dbb87.png)

Windows 10 Pro 19042.1706
![image](https://user-images.githubusercontent.com/55781271/187019878-ab8a2045-62f5-49ad-94f5-81f1a77cc4c5.jpg)

**Comment by zeertzjq** [comment]
Fixed by #18121
