### ISSUE TITLE
Error loading vim-plug

### ISSUE THREAD

**Issue by jknoetzke** [neovim/neovim#19974]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

No, vim 8.2.5032 works.

### Operating system/version

macOS 12.5.1

### Terminal name/version

iTerm2 3.4.16

### $TERM environment variable

xterm-256color

### Installation

brew

### How to reproduce the issue

With the following in init.lua:

```
call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : '~/.vim/plugged')

Plug 'tpope/vim-sensible'
Plug 'junegunn/seoul256.vim'

call plug#end()
```

### Expected behavior

No error.

### Actual behavior

Results in the following error:

```
Error detected while processing /Users/jfk/.config/nvim/init.lua:
E5112: Error while creating lua chunk: /Users/jfk/.config/nvim/init.lua:1: '=' expected near 'plug'
```

**Comment by clason** [comment]
`init.lua` expects its content to be... Lua

Use `init.vim` instead.
