### ISSUE TITLE
vim.fs.normalize does not work well

### ISSUE THREAD

**Issue by leiserfg** [neovim/neovim#19984]
### Neovim version (nvim -v)

0.7.2  commit  88c32b5

### Vim (not Nvim) behaves the same?

nvim only

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

kitty

### Installation

nix

### How to reproduce the issue

mkdir /tmp/\asdf
nvim
`:lua= vim.fs.normalize[[/tmp/\asdf]]`

### Expected behavior

The path name is valid in unix so it should normalize to itself and print:
`/tmp/\asdf`  

### Actual behavior

prints 
`/tmp//asdf`

**Comment by leiserfg** [comment]
I was planning to fix it but someone has first to decide what is the expected behavior of it, because there is not a system-independent definition of path normalization, so we have to provide an implementation depending on the OS. Maybe the simplest solution is to do the `\` to `/` replacement only in windows :thinking: .

**Comment by gpanders** [comment]
>Maybe the simplest solution is to do the `\` to `/` replacement only in windows.

Lets try that. Can you open a PR?

**Comment by gpanders** [comment]
Alternatively we could leave it as-is but allow `\` characters to be escaped. E.g.

```lua
vim.fs.normalize [[/tmp/\asdf]]
```

returns `/tmp//asdf` but

```lua
vim.fs.normalize[[/tmp/\\asdf]]
```

returns `/tmp/\asdf`.

I like that this avoids a special case based on platform, but may have other drawbacks. Any thoughts?

**Comment by leiserfg** [comment]
> I like that this avoids a special case based on platform, but may have other drawbacks. Any thoughts?

That's not idempotent so it's not a valid normalized form imho.

**Comment by justinmk** [comment]
* platform-specific behavior is probably the most useful and unsurprising behavior here.
* normalize() should also collapse redundant slashes. https://github.com/neovim/neovim/pull/19988/files#r958428911

**Comment by leiserfg** [comment]
Ideally, it should also do dots collapsing, like `here/./i/am` -> `here/i/am/`   and `here/i/am/not/..` -> `here/i/am/` but I'm not sure if we should fix those in the same PR. To be honest I think this requires more complex (correct) handling of the paths than regex manipulations.

**Comment by dundargoc** [comment]
This has been fixed in https://github.com/neovim/neovim/commit/25fa051fa157ca4bce712e61602447a4222581ca
