### ISSUE TITLE
Highlighting "bleeds" into terminal buffer

### ISSUE THREAD

**Issue by camoz** [neovim/neovim#19985]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

(doesn't have TermOpen event)

### Operating system/version

linux 5.19.4-arch1-1

### Terminal name/version

foot version: 1.13.0 +pgo +ime +graphemes -assertions

### $TERM environment variable

foot-extra

### Installation

official arch repos

### How to reproduce the issue

- `nvim --clean`
- `:autocmd  TermOpen * startinsert`
- insert mode, enter `()`, observe how they are highlighted
- `:tabnew | term echo foobar`

### Expected behavior

`foobar` is printed in new terminal tab

### Actual behavior

`foobar` is printed in new terminal tab, but `fo` is highlighted (coordinates where the `()` in the previous tab were highlighted):

![slurp_2022-08-28_195305](https://user-images.githubusercontent.com/6276613/187088049-db271460-070a-4d04-995a-04b26b004eba.png)

**Comment by zeertzjq** [comment]
Workaround: trigger `CursorMoved` on `TermOpen`:
```vim
autocmd TermOpen * doautocmd CursorMoved
```

**Comment by camoz** [comment]
Thanks!

**Comment by andryandrew** [comment]
I'm not 100% sure it's related, but found a similar issue with VimTex a year ago (the relevant comment is https://github.com/lervag/vimtex/issues/1595#issuecomment-731883512 , mid-paragraph) and traced its origin to this Neovim bug: https://github.com/neovim/neovim/issues/11878

**Comment by zeertzjq** [comment]
Actually in Vim the matches also exists in terminal buffer. They are just not drawn in Vim.
