### ISSUE TITLE
Idea: Support sub groups in the Visual highlight group.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#1998]
For example, I'd like to `hi Visual guibg=#444444 guifg=NONE` so that only a background is supplied, and the selection still has it's syntax highlighted. But I'd like for comments specifically to have a different color only when in Visual, so perhaps something like `hi Visual guibg=#444444 guifg=NONE Comment guifg=#222222` would apply the guifg to the comments only when in Visual.

**Comment by justinmk** [comment]
Have you looked into `contains` and friends?

**Comment by trusktr** [comment]
@justinmk Are you talking about the contains as in this example?

```
   :syntax match   Comment "//.*"  contains=Todo
```

Can you use that to change the colors of a comment only while in VISUAL mode, but it returns back to it's original color in NORMAL? Perhaps with an autocmd?

**Comment by justinmk** [comment]
We aren't going to extend the vim syntax engine. Rather, advanced highlighting should be done externally and use `nvim_buf_set_highlight()` and friends.
