### ISSUE TITLE
windows 0.7 release installs 0.5

### ISSUE THREAD

**Issue by ofwinterpassed** [neovim/neovim#20006]
### Neovim version (nvim -v)

0.7

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Windows

### Terminal name/version

NA

### $TERM environment variable

NA

### Installation

winget install Neovim.Neovim

### How to reproduce the issue

1. install neovim 0.7 on windows either downloading the msi and run or via winget install Neovim.Neovim
2. run nvim.exe -v

### Expected behavior

installed version should be 0.7.2

### Actual behavior

installed version is 0.5.1

**Comment by justinmk** [comment]
Duplicate of https://github.com/neovim/neovim/issues/19269 .

Need to know the exact steps you're following, not a pick-list of possibilities. Provide exact commands, URLs, etc.

**Comment by ofwinterpassed** [comment]
I had the same behavior via both alternatives. When downloading the msi I used the link in the release page (https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-win64.msi). And the alternative way I tried was using the exact command I gave `winget install Neovim.Neovim`.

After the install running nvim.exe reports the version to be 0.5.1 both for the start screen and the output from `nvim.exe -v`. The   `Settings->Apps & Features` lists the version as 0.7.2 though.



```
$>winget install Neovim.Neovim
Found Neovim [Neovim.Neovim] Version 0.7.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-win64.msi
  ██████████████████████████████  36.1 MB / 36.1 MB
Successfully verified installer hash
Starting package install...
Successfully installed

$>nvim.exe -v
NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Kompilerad av runneradmin@fv-az152-633

Features: -acl +iconv +tui
See ":help feature-compile"

   system-vimrc-fil: "$VIM\sysinit.vim"
  reserv för $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by ofwinterpassed** [comment]
![image](https://user-images.githubusercontent.com/22168222/187443195-d503c109-30ad-4ca9-aea2-fe95a07cd13f.png)

**Comment by ofwinterpassed** [comment]
The copy from the terminal and the screenshot is from reinstalling again. I.e. I get the same result over and over again.

**Comment by ofwinterpassed** [comment]
Thank you for your time. I found the issue and it was another nvim.exe on my local computer. Sorry for not realizing this before I created an issue.
