### ISSUE TITLE
spaces in `vim.api.nvim_set_hl` will cause Neovim Crash

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#20009]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-985-gf9c183c0ca

### Vim (not Nvim) behaves the same?

NOTTEST

### Operating system/version

Linux VeperX 5.17.15-1-MANJARO #1 SMP PREEMPT Wed Jun 15 07:09:31 UTC 2022 x86_64 GNU/Linux

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

yay -S neovim-git

### How to reproduce the issue

init.lua
```lua
vim.api.nvim_set_hl(0, "Normal      ",     { bg = "#292929", fg = "#666666" })
```

then save and exit, reopen nvim again

```
fish: Job 1, 'nvim ~/.config/nvim/init.lua $a…' terminated by signal SIGSEGV (Address boundary error)
```

### Expected behavior

1

### Actual behavior

fish: Job 1, 'nvim ~/.config/nvim/init.lua $a…' terminated by signal SIGSEGV (Address boundary error)

**Comment by clason** [comment]
Spaces are not valid in highlight group names.

(Still shouldn't crash, of course.)

**Comment by zeertzjq** [comment]
Any invalid character causes a crash
