### ISSUE TITLE
Highlight from extmarks disappear when there is syntax highlight and line highlight with sign

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#20004]
### Neovim version (nvim -v)

NVIM v0.7.2 release

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MacOS 12.1

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

repo

### How to reproduce the issue

Create file t.vim
```vim
function Func() abort
endfunction
```
Edit with `nvim -u NORC t.vim` and execute commands:
```vim
let ns = nvim_create_namespace('test')
call nvim_buf_set_extmark(bufnr('%'), ns, 0, 0, {
      \ 'end_col': 3,
      \ 'hl_mode': 'combine',
      \ 'hl_group': 'MoreMsg',
      \ 'priority': 4096,
      \ })
hi default MyLine ctermbg=237 guibg=#3c3836
sign define CurrentLine linehl=MyLine
call sign_place(6, 'Test', 'CurrentLine', bufnr('%'), {'lnum': 1, 'priority': 0})
```

### Expected behavior

`MoreMsg` highlight should still works like vim's textprop.
I've tried to change the priority and `hl_mode`, still not work.

### Actual behavior

`MoreMsg` highlight not work, only syntax highlight work.

**Comment by zeertzjq** [comment]
Fixed by #23742
