### ISSUE TITLE
Error "E17: is a directory" even when writing to directory with `BufWriteCmd` and `buftype=acwrite`

### ISSUE THREAD

**Issue by elihunter173** [neovim/neovim#20002]
### Neovim version (nvim -v)

Introduced in commit https://github.com/neovim/neovim/commit/0cf5cd1ac9c8ec31c1d2f1b1a6585153a45fc4e9 (NVIM v0.8.0-dev-623-g0cf5cd1ac)

### Vim (not Nvim) behaves the same?

Unsure how to replicate

### Operating system/version

x86_64 GNU/Linux 5.19.4-arch1-1

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

build from repo

### How to reproduce the issue

This issue was discovered with https://github.com/elihunter173/dirbuf.nvim/issues/45, so I use [dirbuf.nvim](https://github.com/elihunter173/dirbuf.nvim) to reproduce the issue. I can produce a smaller reproducible example if necessary.

1. `nvim .` to open a dirbuf
2. add a line of text
3. `:write`

### Expected behavior

The directory buffer writes without error. This is the current behavior on 0.6.0, 0.6.1, and 0.7.0.

### Actual behavior

The command fails with the error message
```
E17: is a directory
```

**Comment by elihunter173** [comment]
A few links for easy access:
* Bug report on `dirbuf.nvim`: https://github.com/elihunter173/dirbuf.nvim/issues/45
* Related earlier issue: https://github.com/neovim/neovim/issues/18295
* Fix for earlier issue: https://github.com/neovim/neovim/pull/18296

**Comment by zeertzjq** [comment]
Not sure if this is really a bug. Can you try using `BufReadCmd` to read the buffer?

**Comment by elihunter173** [comment]
Will do. I'll ping you with a report back once I've tried that
