### ISSUE TITLE
Cursor shape not respected in PuTTY

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#20027]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

No

### Operating system/version

CentOS 7.9

### Terminal name/version

PuTTY 0.76

### $TERM environment variable

putty-256color

### Installation

system package manager

### How to reproduce the issue

When connecting to my Linux machine from a Windows machine using PuTTY, the cursor shape does not change when entering insert mode. TERM is set to putty-256color and the terminfo entry (displayed by `infocmp -x1`) does not have `Ss` or `Se`. I am not using tmux. According to `:h tui-cursor-shape`, Neovim should add constructed "Ss" and "Se" capabilities for PuTTY if these are missing. Is there something more that I need to do to make this work?

FWIW, if I change the cursor shape in PuTTY's Window > Appearance menu to a vertical bar, the cursor shape does change to a vertical bar properly, but it's a vertical bar all of the time, which is not what I want.

### Expected behavior

Cursor shape should change to vertical bar in Insert mode

### Actual behavior

Cursor shape does not change

**Comment by ddickstein** [comment]
If [my understanding](https://github.com/neovim/neovim/issues/21938#issuecomment-1402245908) of why this doesn't work is correct, I'm curious whether it's possible for Neovim to implement some sort of fallback logic to get this support. The user who flagged to me that cursor shape wasn't working in Neovim said it had been working in Vim inside Putty with the following:
```
"set cursor on startup
autocmd VimEnter * let &t_EI="\e[=2c"
"restore cursor on exit
autocmd VimLeave * let &t_me="\e[=1c"
```
Does this suggest that if `Ss` and `Se` are absent from the terminfo and the terminal is not among the list of terminals for which Neovim infers these capabilities, Neovim in theory could fall back to these escape sequences to provide this? And if so, should it? And is there (or should there be) some other terminfo entry that indicates support for them?

**Comment by clason** [comment]
Neovim removed Vim's homegrown `t_xx` options (`:h t_xx`).
