### ISSUE TITLE
'numberexpr' or 'numberfunc' for arbitrary formatting (WAS: localized 'number' column)

### ISSUE THREAD

**Issue by amarakon** [neovim/neovim#20035]
### Feature already in Vim?

No

### Feature description

After enabling the `number` option, I can indeed see line numbers on the left side of the buffer. But I would prefer human-readable line numbers. This means that 1000 should be 1,000 instead. It would be cool if there was an option to use human-readable line numbers as it would be useful for people who work with very large files. vim-airline, a status-line plugin, supports human-readable line numbers in the status-line (See this [issue](https://github.com/vim-airline/vim-airline/issues/1382)). I wish Neovim's line numbering also supported it.

**Comment by matveyt** [comment]
>This means that 1000 should be 1,000 instead.

Actually, it is a locale-dependent thing. So the support (if any) should respect OS settings.

**Comment by jamessan** [comment]
Sounds like it would be addressed by someone resuming work on https://github.com/neovim/neovim/pull/494.

**Comment by dundargoc** [comment]
@jamessan is that the correct issue you linked? It looks kinda unrelated and it seems to have already been merged.

**Comment by amarakon** [comment]
> > This means that 1000 should be 1,000 instead.
> 
> Actually, it is a locale-dependent thing. So the support (if any) should respect OS settings.

Oh, I did not know that. What locales don't make 1000 to 1,000?

**Comment by matveyt** [comment]
@amarakon Well, speaking of standards, one may  count on two of them, at least, "British" and "French". Yet there could be even more than that. If I remember correctly the Windows control panel applet gives four or five choices.

**Comment by bfredl** [comment]
if we implement this the option can just be the separator char directly. no need to invoke the complexity of POSIX locales for something relatively simple like this.

**Comment by matveyt** [comment]
That may be not enough. Just quick googling https://devblogs.microsoft.com/oldnewthing/20060417-06/?p=31513

**Comment by bfredl** [comment]
well, for a completely arbitrary format, something like https://github.com/neovim/neovim/pull/4941 as already mentioned would be needed.
