### ISSUE TITLE
New TUI and :set title not working together

### ISSUE THREAD

**Issue by ugopozo** [neovim/neovim#2003]
When `set title` is enabled, any action that would set the terminal window title instead just prints a control character to the current position followed by the title (such as enabling `set title` itself, or moving to another another via `<C-w> [h,j,k,l]`, or even opening a file with `:e filename`).

Tried it with my full `.nvimrc` configuration and with "naked" Neovim, both displayed the same behavior.

![vim set title](https://cloud.githubusercontent.com/assets/529125/6234069/bee1659e-b6be-11e4-8b2c-18c913bf4ce2.png)

**Comment by justinmk** [comment]
I was seeing this here: https://github.com/neovim/neovim/pull/1820#issuecomment-73724189

Maybe `rm -rf .deps build` before compiling?

**Comment by ugopozo** [comment]
@justinmk I'm not sure if that would be an issue, I compiled the new version from AUR (using AUR's `unibilium` and `libtermkey-git-neovim` packages, not the PKGBUILD provided by @fmoralesc) with yaourt, which mean it clones the entire repository from scratch to a temporary directory, so I didn't have any leftovers of previous builds lying around.

If it should've been fixed by e9ef196, perhaps the issue is in the linked packages?

**Comment by justinmk** [comment]
> perhaps the issue is in the linked packages

Almost certainly. There are many of these package floating around, so we depend on the package maintainers to keep up with changes in master. They usually fall behind, although we at least pay attention to the homebrew formula.

**Comment by fmoralesc** [comment]
@ugopozo Did you try building neovim with my PKGBUILD? That works just like building nvim from master, and it pulls all the dependencies on its own. (BTW: I see what caused my AUR build to fail: I used `libtermkey-git` instead of `libtermkey-git-neovim`)

**Comment by fwalch** [comment]
Compiling with built-in dependencies (`make distclean && make`) from master (66a03a7385dfd11503d22d8cc9dc6a972e27dcc2) and running with `VIMRUNTIME=runtime ./build/bin/nvim -u NONE` shows problems with `:set title` for me.

The AUR dependencies should be alright (unibilium is at 1.1.1, libtermkey-git-neovim is at the same version as `third-party`).

**Comment by justinmk** [comment]
@fwalch Works for me compiled with HEAD. "foo" appears in terminal title and tmux statusline. Using mintty on Windows, ssh'd to ubuntu, running tmux.

```
NVIM 0.0.0-alpha+201502170110 (compiled Feb 17 2015 10:19:52)
Commit: 66a03a7385dfd11503d22d8cc9dc6a972e27dcc2
Build type: RelWithDebInfo
```

**Comment by fwalch** [comment]
@justinmk If I use tmux, it works for me as well, at least for the tmux statusline. The terminal title is never updated. I tried roxterm and gnome-terminal.

**Comment by tarruda** [comment]
@ugopozo Whats your terminal, version and `$TERM` variable value?

@fwalch libtermkey's bzr master branch is up to date so you can use it from the AUR script(I only keep a github mirror for installation by the build system)

**Comment by ugopozo** [comment]
@tarruda I could fully reproduce this issue in xfce4-terminal 0.6.3 and gnome-terminal 3.14.2, and partially on Terminology 0.7.0 (the title is not set, but there are no control characters and artifacts on screen).

My `$TERM` is `xterm-256color`, manually set by `.bashrc`, actually.

@fmoralesc I actually haven't tried your PKGBUILD it, I will as soon as I can.

**Comment by fmoralesc** [comment]
@ugopozo Nevermind. I got back home and just tested it. It happens in my build too. 

![captura de pantalla de 2015-02-17 19 07 14](https://cloud.githubusercontent.com/assets/221465/6238246/34b806c4-b6d8-11e4-8087-399948c48956.png)

![captura de pantalla de 2015-02-17 19 08 53](https://cloud.githubusercontent.com/assets/221465/6238279/778f9110-b6d8-11e4-8e38-aa8836712cd0.png)

**Comment by fmoralesc** [comment]
This is ẁith `gnome-terminal`  3.14.2 and `xterm-256color`. Under tmux everything is fine.

**Comment by tarruda** [comment]
Should be fixed in #2007

**Comment by fmoralesc** [comment]
@tarruda It is. Thanks!

**Comment by tarruda** [comment]
#2007 was merged
