### ISSUE TITLE
Neovim Unable to download spell en-ca.utf-8.spl

### ISSUE THREAD

**Issue by rooster-ninja** [neovim/neovim#20042]
### Neovim version (nvim -v)

latest via brew reinstall

### Vim (not Nvim) behaves the same?

don't know

### Operating system/version

macOS latest

### Terminal name/version

Warp, but iTerm the same

### $TERM environment variable

xterm-256color

### Installation

brew

### How to reproduce the issue

:set spell via F12 keyboard shortcut

No spell file for "en-ca" in utf-8
Download it?
(Y)es, [N]o: Y

Downloading en-ca.utf-8.spl...
:!curl 'https://ftp.nluug.nl/pub/vim/runtime/spell/en-ca.utf-8.spl' -L -o '/var/folders/9w/y_2_1lp10mxbk3
yx664_19fr0000gn/T/nvimmbBaCu/1.spl'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314  100   314    0     0    393      0 --:--:-- --:--:-- --:--:--   396
"/var/folders/9w/y_2_1lp10mxbk3yx664_19fr0000gn/T/nvimmbBaCu/1.spl" 9L, 314B
Could not find it, trying en-ca.ascii.spl...
:!curl 'https://ftp.nluug.nl/pub/vim/runtime/spell/en-ca.ascii.spl' -L -o '/var/folders/9w/y_2_1lp10mxbk3
yx664_19fr0000gn/T/nvimmbBaCu/1.spl'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314  100   314    0     0    354      0 --:--:-- --:--:-- --:--:--   357
"/var/folders/9w/y_2_1lp10mxbk3yx664_19fr0000gn/T/nvimmbBaCu/1.spl" 9L, 314B
Download failed
Warning: Cannot find word list "en-ca.utf-8.spl" or "en-ca.ascii.spl"
Press ENTER or type command to continue

### Expected behavior

expect to download and install ***.spl file.

### Actual behavior

Fails to find file...

**Comment by niess** [comment]
Hello, I had a similar problem on Linux with `fr.utf-8`. In my case, the failure was due to a certificate issue. I could solve it by passing the `--no-check-certificate` option to `wget`. Thus:

```
wget --no-check-certificate 'https://ftp.nluug.nl/pub/vim/runtime/spell/fr.utf-8.spl'
```
(change the filename accordingly). Then, move the file to your `spell` directory.

Note that in my case `wget` is used by `nvim` (0.7.2), not `curl`.
