### ISSUE TITLE
Docs are unclear on difference between `vim.schedule` and `vim.schedule_wrap`

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#20048]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

CentOS 7.9

### Terminal name/version

xfce4-terminal 0.8.7.4

### $TERM environment variable

tmux-256color

### Installation

system package manager

### How to reproduce the issue

The docs for `vim.schedule` and `vim.schedule_wrap` do not clearly outline which should be used when.

```
vim.schedule({callback})				*vim.schedule()*
        Schedules {callback} to be invoked soon by the main event-loop. Useful
        to avoid |textlock| or other temporary restrictions.

schedule_wrap({cb})                                      *vim.schedule_wrap()*
                Defers callback `cb` until the Nvim API is safe to call.
```

These both seem to schedule the callback in question to be run later on the event loop. The documentation should clarify the difference and when to reach for one vs. the other.

**Comment by lewis6991** [comment]
In general any function in Lua that is suffixed with `_wrap` simply returns a function/closure.

Here is the implementation for `schedule_wrap`:

```lua
--- Defers callback `cb` until the Nvim API is safe to call.
---
---@see |lua-loop-callbacks|
---@see |vim.schedule()|
---@see |vim.in_fast_event()|
function vim.schedule_wrap(cb)
  return function(...)
    local args = vim.F.pack_len(...)
    vim.schedule(function()
      cb(vim.F.unpack_len(args))
    end)
  end
end
```
