### ISSUE TITLE
Set `spelllang` to the Locale's Default Language

### ISSUE THREAD

**Issue by amarakon** [neovim/neovim#20049]
### Feature already in Vim?

No

### Feature description

I think it would make more sense to set `spelllang` to the locale's default language instead of `en`. I managed to do it with one line of Vim Script:

```vim
if $LANG != '' | let &spelllang = tolower($LANG[0:4]) | endif
```

I think this should be the default behavior though.

**Comment by lewis6991** [comment]
I don't think we have any options that have dynamic defaults. I guess we could add an `auto` option or something.

**Comment by zeertzjq** [comment]
> I don't think we have any options that have dynamic defaults.

`'shell'`

**Comment by lewis6991** [comment]
Ha, fair enough. Then maybe this makes sense to do.

**Comment by amarakon** [comment]
I submitted a pull request that solves this issue, it is mentioned above.

**Comment by justinmk** [comment]
not worth the trouble. see https://github.com/neovim/neovim/pull/20052
