### ISSUE TITLE
Make result of `nvim_parse_cmd` usable directly by `nvim_cmd`

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#20051]
### Feature description

For some fields, `nvim_parse_cmd` returns a value that is invalid for `nvim_cmd` if the command does not support that field or that field is not specified, so passing the result of `nvim_parse_cmd` to `nvim_cmd` will lead to an error. For example:
```lua
vim.api.nvim_cmd(vim.api.nvim_parse_cmd('echo', {}), {})
```
leads to `Command cannot accept a range`.

There are two ways to make this better:
1. Make `nvim_parse_cmd` omit some fields if they are not specified. This will, however, lead to inconsistency with `nvim_create_user_command`.
2. Make `nvim_cmd` ignore some fields if they have the default value returned by `nvim_parse_cmd`.

Related: <https://github.com/neovim/neovim/pull/20039#issuecomment-1234421987>

**Comment by famiu** [comment]
1 to me seems like by far the better option. And that's probably what I'm going to do unless there's a strong reason not to.
