### ISSUE TITLE
Filetype detection does not receive buffer contents from stdin

### ISSUE THREAD

**Issue by osthomas** [neovim/neovim#20061]
### Neovim version (nvim -v)

NVIM v0.8.0-dev

### Vim (not Nvim) behaves the same?

no, vim 9.0.135

### Operating system/version

Ubuntu 22.04

### Terminal name/version

konsole 21.12.3

### $TERM environment variable

xterm-256color

### Installation

PPA

### How to reproduce the issue

The behaviour is observable by piping git output to nvim, but it probably also happens with other file types.

```bash
TEMPREPO=$(mktemp -d) && cd "$TEMPREPO"  && git init nvim-ft-testrepo && cd nvim-ft-testrepo/ && touch firstfile && git add firstfile && git commit firstfile -m "commit" && git show $(git rev-parse --short HEAD) | nvim --clean - && rm -rf "$TEMPREPO"
```

### Expected behavior

The buffer contents should be detected as the `git` filetype with corresponding highlighting. This works when the output of the above command is first redirected to a file, and then opened with nvim:

```bash
TEMPREPO=$(mktemp -d) && cd "$TEMPREPO"  && git init nvim-ft-testrepo && cd nvim-ft-testrepo/ && touch firstfile && git add firstfile && git commit firstfile -m "commit" && git show $(git rev-parse --short HEAD) > outputfile && nvim --clean outputfile && rm -rf "$TEMPREPO"
```

In vim, piping also results in detection of the filetype.

### Actual behavior

The buffer contents are not detected as a filetype when piped into neovim.

As far as I can tell, this happens because the buffer contents cannot be acquired here:

https://github.com/neovim/neovim/blob/1ffd527c837fb2465c9659273bbe5447a1352db2/runtime/lua/vim/filetype.lua#L2504

When piping, this function (`vim.filetype.match`) is called once and is unable to get the contents. When a file is opened, this function is called twice (is this intended?). The second call acquires the contents.

**Comment by clason** [comment]
Simpler reproducer: `cat <file> | nvim --clean -`, for any recognized file.

**Comment by clason** [comment]
Looks like the autocommand is not defined by the time the piped input is read.

**Comment by clason** [comment]
Note that this is a very specific situation; most piped files will not get detected by Vim, either (since there is no file name).

Can you try to create a simpler reproducing example with a test file that I can just `cat file | nvim -`?

**Comment by osthomas** [comment]
Hello @clason, thanks for looking into this (again)!

Sure:

```bash
echo "commit dd297f5268adc63428652f63a1a8cbcc18d05d75" > testfile
cat testfile | nvim -
```

While not all files may be detectable if piped and no file name is available, there is a subset of file types for which detection by content pattern matching is explicitly supported:

https://github.com/neovim/neovim/blob/ea611c7122470af0e03f4b0a5ae99c0878da2712/runtime/lua/vim/filetype/detect.lua#L1468

The git one is here:

https://github.com/neovim/neovim/blob/ea611c7122470af0e03f4b0a5ae99c0878da2712/runtime/lua/vim/filetype/detect.lua#L1562

**Comment by clason** [comment]
OK, it does detect correctly with `g:do_legacy_filetype` set, so this is in fact a regression. 

Could be an issue with `filetype.vim` relying on `scripts.vim` being run on `StdinReadPost`, while `filetype.lua` triggers `vim.filetype.match` only on `BufReadPost`. It should still fall back to `scripts.vim` in this case, but it would be better not to rely on that even if it worked.

**Comment by clason** [comment]
Indeed, adding `StdinReadPost` to the main detection autocommand makes this work. 

@smjonas do you see any drawback to this?
