### ISSUE TITLE
 richer window API and/or data structures

### ISSUE THREAD

**Issue by lahwran** [neovim/neovim#2006]
I have a little thing in my vimrc that allows me to cut a window with `,u`:

```viml
let g:wingrab_last_buffer = -1
function! Wincp()
    let g:wingrab_last_buffer = bufnr("%")
endfunction
nnoremap ,u :call Wincp()<CR>:hide<CR><C-=><ESC><ESC>
nnoremap ,<S-U> :call Wincp()<CR><ESC><ESC>
```

and to paste it with `,hjkl`:

```viml
nnoremap ,h :aboveleft vnew<CR>:execute "buffer! " . g:wingrab_last_buffer<CR><C-=><ESC><ESC>
nnoremap ,l :rightbelow vnew<CR>:execute "buffer! " . g:wingrab_last_buffer<CR><C-=><ESC><ESC>
nnoremap ,k :aboveleft new<CR>:execute "buffer! " . g:wingrab_last_buffer<CR><C-=><ESC><ESC>
nnoremap ,j :rightbelow new<CR>:execute "buffer! " . g:wingrab_last_buffer<CR><C-=><ESC><ESC>
```

Thoughts on this? seems like a fundamental feature without which windows are nearly useless, but maybe I'm just used to it.

**Comment by justinmk** [comment]
So what does it do?

**Comment by lahwran** [comment]
,u copies the buffer id that is open in a window, and then closes that window. it's like :hide on that window, but saving the buffer that was open. then `,h`, `,j`, `,k`, `,l` all are like the appropriate `:aboveleft vnew`/`:rightbelow vnew`/`:aboveleft new`/`:rightbelow new`, but they then follow it up by opening the buffer that was open in the window you closed with `,u`.

**Comment by justinmk** [comment]
It sounds like you want a "previous buffer" variable. There are some details lacking though. And it's quite a stretch to say that windows are useless without this. Most people don't care so much about the precise position of windows--they are meant to be summoned and discarded quickly, not so much a carefully arranged bonsai tree. But we can always try to make things easier for unusual use cases if it makes sense to do so.

 I'm confused about `<C-=>`, what does that do?

**Comment by fmoralesc** [comment]
> Most people don't care so much about the precise position of windows--they are meant to be summoned and discarded quickly, not so much a carefully arranged bonsai tree. But we can always try to make things easier for unusual use cases if it makes sense to do so.

There are a bunch of requests which together can be reduced to "implement a richer window managment system". This is something that would make a lot of sense as a plugin, but it is probable that nvim would require some infraestructure changes to accomodate this. For example, some ideas require to gather information about the window layout, like what windows exist in the current frame (see #997, #2004), and other might perhaps require the notification of events like "a new window was created", "a window was closed", "vertical split", "horizontal split", "enter frame", "leave frame", etc.

**Comment by firedev** [comment]
FZF or `:term` shifts splits higher and higher until the moment you are left with a single line buffer.

**Comment by justinmk** [comment]
@firedev FYI it is not specific to :term , any split open and close would change the layout.

**Comment by firedev** [comment]
Probably. I am more careful with splits now and always do `Ctrl-w-o` before anything.

**Comment by justinmk** [comment]
Merging into https://github.com/neovim/neovim/issues/3933.

Also @lahwran I am a bit confused about what you're asking. It seems like you have a solution already working, without only 10 lines of vimscript. Are you suggesting there be default mappings for this feature? What would the mappings be? How would some sample documentation description the feature?

**Comment by lahwran** [comment]
I don't remember what I was asking. don't worry about it.
