### ISSUE TITLE
Re-implement LSP client in C

### ISSUE THREAD

**Issue by MurdeRM3L0DY** [neovim/neovim#20060]
### Feature already in Vim?

No

### Feature description

I would just like to put this out there and get your opinions. I would like to know if it would be possible to reimplement and expose the base lsp client under `vim.api`. as this would also be beneficial for interacting with neovim's lsp via external plugins. I would like propose to some basic functionalities like:

- local client_id = vim.api.nvim_lsp_start_client(...)
- vim.api.nvim_lsp_buf_attach(bufnr, client_id, ...)
- vim.api.nvim_lsp_buf_request(bufnr, client_id, ...)
- etc...

**Comment by ii14** [comment]
You can use `nvim_exec_lua`.

**Comment by clason** [comment]
Is there a concrete use case here that is currently not possible?

**Comment by clason** [comment]
To be clear, many things are possible given enough effort. The question that needs to be addressed (by you!) is whether this is _worth_ the effort?

**Comment by justinmk** [comment]
no

**Comment by MurdeRM3L0DY** [comment]
> You can use `nvim_exec_lua`.

Thanks for the suggestion.
