### ISSUE TITLE
inccommand: crash when opening window in preview callback

### ISSUE THREAD

**Issue by smjonas** [neovim/neovim#20078]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-873-g5d8278591

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux Mint 20.2

### Terminal name/version

Kitty 0.15

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

1. `nvim --clean`
2. Define the following command:
```lua
local bufnr
vim.api.nvim_create_user_command("Test", function() end, {
  preview = function()
    if not bufnr then
      bufnr = vim.api.nvim_create_buf(false, true)
      vim.api.nvim_open_win(
        bufnr,
        true,
        { relative = "win", row = 1, col = 1, width = 20, height = 1 }
      )
    end
    return 2
  end,
  nargs = 1,
  addr = "lines",
})
```
3. Type `:Test`

### Expected behavior

No crash and the window should open. The only workaround that I know of is to schedule wrap the call to `nvim_open_win`. This is not what I need because the window will only open on the second keypress.

### Actual behavior

Nvim crashes [abort (core dumped)]

The weird thing is that the crash does not occur when omitting any of the arguments to `nvim_open_win` :thinking:

**Comment by zeertzjq** [comment]
I check a version before the version you mentioned and a version after the version you mentioned, and neither of them crash with the steps to reproduce.

**Comment by smjonas** [comment]
Thanks for looking into this, upgrading to the latest version resolved the issue. I also don't need to use `vim.schedule` anymore so this is perfect!
