### ISSUE TITLE
gI return to the latest global insert position

### ISSUE THREAD

**Issue by kaiphat** [neovim/neovim#20085]
### Feature already in Vim?

No

### Feature description

gI return to the latest global insert position

**Comment by dundargoc** [comment]
I'm not against the suggestion, but this seems exceptionally specific. Is there a specific usecase you have in mind?

Minor nitpick: `gI` is already taken, but that can be changed I suppose.

**Comment by justinmk** [comment]
Randomly changing things without a strong reason is out of scope for the project.
