### ISSUE TITLE
remote UI cannot trigger timestamp check like TUI

### ISSUE THREAD

**Issue by 0x00002a** [neovim/neovim#20082]
### Neovim version (nvim -v)

v0.8.0-dev-859-gd5d6ed311

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux/Arch

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

AUR

### How to reproduce the issue

open the following file in neovide:

```
# vim: set autoread
```
and save it as something (e.g. "hello.txt"), then run
```bash
echo "hello, world" >> hello.txt
```
switch back to neovide and see it has no changed, despite autoread being set. You can verify it should've changed by running `:checktime` and having it show the changes.

### Expected behavior

If neovim knows a file has changed (which it does because it can update itself when running directly) then it should also notify api clients of this

### Actual behavior

When opened directly with `nvim` it _does_ show the changes _and_, as far as I can tell from logging on the neovide side, the fact the file has changed is never sent to it. Neovide does not show the changes to the file until checktime is used.

I have dug into the neovim source a bit, and done some print debugging, and I can't work out how neovim knows the file has changed. `buf_check_timestamp` is called when checktime is used directly, but not when the file changes on its own so I'm presuming theres something at the tui level thats doing this.

**Comment by zeertzjq** [comment]
> If neovim knows a file has changed (which it does because it can update itself when running directly)

Are you sure about this? I don't think Nvim has noticed the file has changed in your case.

**Comment by zeertzjq** [comment]
AFAIK timestamps are only automatically checked when `FocusGained` is triggered, which is only automatically triggered by the TUI.

**Comment by 0x00002a** [comment]
Just tested it with keep above so I could see nvim at the same time as I did the echo and it didn't change till I refoused the window. Even if its only through some event, if it updates the tui it should still also update the clients imo

**Comment by 0x00002a** [comment]
Ah wait, do you mean with clients they need to notify neovim of `FocusGained` because it can't do it itself?

**Comment by zeertzjq** [comment]
No. I just noticed that neovide already triggers `FocusGained`, and that triggering `FocusGained` from `:doautocmd` doesn't actually trigger a timestamp check. With TUI a timestamp check is done the same time as `FocusGained`, but it is not an autocommand callback, but something triggered the same time as the autocommand.

**Comment by zeertzjq** [comment]
#18375 is going to introduce an API `nvim_ui_set_focus` for this, which will trigger a timestamp check.

**Comment by alexventuraio** [comment]
This is a very good feature I'm expecting to have!
I'd love to see any progress on this!

**Comment by zeertzjq** [comment]
Since neovide already triggers `FocusGained`, this can be done by `autocmd FocusGained * checktime`.

**Comment by justinmk** [comment]
I don't see what "remote UI" has to do with this.

> switch back to neovide and see it has no changed, despite autoread being set

As mentioned above, `FocusGained` can be used to opt-in to the behavior you want.

The general story of improving `autoread` is tracked in https://github.com/neovim/neovim/issues/1380

**Comment by zeertzjq** [comment]
There is now `nvim_ui_set_focus`
