### ISSUE TITLE
Global config.lua module for more simple configuration

### ISSUE THREAD

**Issue by gikari** [neovim/neovim#20089]
### Feature already in Vim?

No

## The problem

Currently, configuration of Neovim and its plugins is done using imperative Lua statements in init.lua. This approach has the following drawbacks:

1. When an instruction fails (such as require statement), every other statement in the init.lua is ignored. This makes it so subsequent configuration is not loaded for the user.
2. To set different things you need to learn different syntax. vim.opt.X for some options, vim.g.X for others (setting leader key for example), for keymaps you have a vim.keymap.set, not to mention unported to lua options, like titlestring, colorscheme etc. In general a simple user (not a plugin author) have to learn lua to feel comfortable.
3. In general, user configuration is very verbose, even the vimscript were more apt. There are a lot of repetitions.

## The proposed solution

There is another program, that configures itself in lua - [Wezterm](https://wezfurlong.org/wezterm/). Its config file is simple and wezterm even reloads it after a change. `.wezterm.lua` looks like this:

```lua
local wezterm = require 'wezterm'
return {
  font = wezterm.font 'JetBrains Mono',
  color_scheme = 'Batman',
}
```

I suggest using the same approach with neovim configuration: have an additional `$CONFIG_PREFIX/nvim/config.lua` module, that reloads itself after a change. The module is available to any lua plugin via `require("vim.config")` or similar statement. The module can contain any data, for example:
```lua
return {
    background = "dark",
    colorscheme = "tokyonight",
    cursorline = true,
    number = true,
    relativenumber = true,
    leader = " ",
    localleader = " ",
    plugin = {
        toggleterm = {
            size = 20,
            open_mapping = [[<c-t>]],
            start_in_insert = true,
            direction = "float",
        },
    },
    keymap = {
        normal_mode = {
            {"<C-h>", "<C-w>h", { silent = true, desc = "Focus Window on the Left" }}
            {"<C-j>", "<C-w>j", { silent = true, desc = "Focus Window on the Bottom" }}
            {"<C-k>", "<C-w>k", { silent = true, desc = "Focus Window on the Top" }}
            {"<C-l>", "<C-w>l", { silent = true, desc = "Focus Window on the Right" }}
        },
    },
}
```

Advantages I see in this approach:

1. Even if the value of a map is wrong, it's just ignored (with a warning) instead of failing the entire init.lua.
2. You don't have to learn lua for basic configuration - it's just a key-value map, like in a json, but with flexibility and comment blocks.
1. Streamlined and consistent configuration syntax, where there are as few repetitions as possible.
3. Safe to autoreload, assuming it's just a table.
4. Useful for lua plugins, encourages reading configuration from there, instead of requiring to call a setup function.

Does this proposal sound good? Sorry, if it is too bold of a proposal. Since I am a user, I don't know a lot of technical details about the implementation, but the feature looks not trivial to me.

**Comment by clason** [comment]
>  that reloads itself after a change.

You just snuck that in there, did you :) That is not possible unless you severely restrict the things the config can contain -- which is an unacceptable regression, especially for plugins.

Of course, you can do this yourself if you're fine with this restriction (which, I repeat, Neovim is not!) by having a `.config/nvim/lua/config.lua` module that you can `require('config')` in your `init.lua` together with a `BufWritePost` autocommand.

**Comment by gikari** [comment]
> >  that reloads itself after a change.
> 
> You just snuck that in there, did you :) That is not possible unless you severely restrict the things the config can contain -- which is an unacceptable regression, especially for plugins.
> 

Sorry, but what do you mean? What exactly that config couldn't contain? It's just an alternative way to set things (strings, numbers, boolean values) in a more simple way - the thing plugins already do.

That also doesn't imply that init.lua is going away of course. For simple things - a table, for advanced stuff - plugins and init.lua.
