### ISSUE TITLE
Add Highlight Groups For Even and Odd Lines

### ISSUE THREAD

**Issue by austinliuigi** [neovim/neovim#20092]
### Feature already in Vim?

No

### Feature description

**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

I think it's nice for even and odd lines to have different highlights. It lets me quickly see which number in the line-number column any particular line corresponds to, regardless of how much whitespace is in front of it. It's a nice quality of life improvement when using relative numbers.

Currently, chrisbra's "DynamicSigns" plugin implements this functionality by adding signs to each line and giving them a different highlight whether they're even or odd. However, when a file has a relatively large number of lines, this causes an extreme slowdown and becomes almost unusable. Additionally, there are times when the signs to not update automatically.

**Describe the solution you'd like**

A builtin option of highlighting even and odd lines differently (LineEven and LineOdd hl-groups?). Here is an image using the DynamicSigns plugin:

![image](https://user-images.githubusercontent.com/85013922/185279145-81af27a7-cf5d-4b8e-a5a9-fff992855372.png)

**Additional context**

I have no idea about the feasibility of this, but I'm hoping it's a feature that is reasonable to add.

The highlighting doesn't even necessarily need to be tied to the line; as long as adjacent lines have different highlights, it makes it easier to see what line number each line corresponds to.

**Comment by clason** [comment]
I don't think this needs to be in core; (extmark) signs are much more efficient in Neovim, so a (Lua) plugin still sounds like the right option here. (@lewis6991 ?)

**Comment by zeertzjq** [comment]
A problem with implementing this as highlight groups is that this behavior is not wanted for every window/buffer, so if these highlight groups are added, one need to override more highlight groups to change the background colors of a specific window.

**Comment by lewis6991** [comment]
This appears to work:

```lua
local ns = vim.api.nvim_create_namespace('evenoddlines')

vim.api.nvim_set_decoration_provider(ns, {
  on_win = function()
  end,
  on_line = function(_, _, buf, row)
    if row % 2 == 0 then
      vim.api.nvim_buf_set_extmark(buf, ns, row, 0, {
        end_row = row + 1,
        hl_group = 'Visual',
        hl_eol = true,
        ephemeral = true
      })
    end
  end
})
```

I did try with `line_hl_group`, however that doesn't appear to work with `ephemeral = true`.

**Comment by notomo** [comment]
FYI https://github.com/notomo/zebrazone.nvim

**Comment by clason** [comment]
Looks like there already is a fine plugin, so I'm closing this as not needed in core.

**Comment by austinliuigi** [comment]
Thank you!

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/init-lua-highlight-every-even-lines/3963/2

**Comment by justinmk** [comment]
With `:help 'statuscolumn'` in Nvim 0.9 there is now a more "native" way to achieve this. See also https://github.com/luukvbaal/statuscol.nvim for even more examples.
