### ISSUE TITLE
inccommand: screen is not redrawn immediately 

### ISSUE THREAD

**Issue by smjonas** [neovim/neovim#20094]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1020-gea10e0c10

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux Mint 20.2

### Terminal name/version

Kitty 0.15

### $TERM environment variable

xterm-kitty

### Installation

appimage

### How to reproduce the issue

- `nvim --clean test.lua`
- Paste the following user command and source the file. This creates a "parent" buffer + window and a child window relative to the parent.
```lua
local parent_bufnr
vim.api.nvim_create_user_command("X", function() end, {
  preview = function()
    if not parent_bufnr then
      parent_bufnr = vim.api.nvim_create_buf(false, true)
      local parent_winnr = vim.api.nvim_open_win(
        parent_bufnr,
        true,
        { relative = "win", row = 5, col = 5, width = 20, height = 1, border = "double" }
      )

      local child_bufnr = vim.api.nvim_create_buf(false, true)
      vim.api.nvim_open_win(
        child_bufnr,
        true,
        { relative = "win", win = parent_winnr, row = 2, col = -1, width = 20, height = 1, border = "single", }
      )
    end
    return 2
  end,
  nargs = 1,
  addr = "lines",
})
```
- Type `:X  .` (`:X` followed by a space + any other character `.`)

### Expected behavior

The windows should be drawn at the correct positions immediately after the first invocation of the preview callback.

### Actual behavior

It takes multiple invocations of the preview callback to render the windows correctly.

After typing `X`, both windows appear (though in incorrect positions):

![image](https://user-images.githubusercontent.com/40792180/188604043-68aa280a-2467-4076-ae34-2c8a3e2e15cd.png)

After typing ` `, the second window disappears:
![image](https://user-images.githubusercontent.com/40792180/188604181-80bc6096-0faf-444f-ab25-37a0a32d5247.png)

After typing ` ` again. the windows have moved to the expected positions:
![image](https://user-images.githubusercontent.com/40792180/188604334-8e1ab410-f6ce-4e5b-bcc7-77a675d1e548.png)

**Comment by smjonas** [comment]
Doesn't look like it, as inserting a `vim.cmd("redraw")` does nothing

**Comment by zeertzjq** [comment]
redrawing is not allowed from inccommand callback

**Comment by zeertzjq** [comment]
Closing in favor of #14735
