### ISSUE TITLE
python3.6 support

### ISSUE THREAD

**Issue by melko** [neovim/neovim#20101]
### Neovim version (nvim -v)

v0.8.0-dev-1037-g694ac2694

### Vim (not Nvim) behaves the same?

no

### Operating system/version

centos 8.5.2111

### Terminal name/version

any

### $TERM environment variable

any

### Installation

build from sources

### How to reproduce the issue

`:checkhealth provider`

### Expected behavior

```
## Python 3 provider (optional)
  - INFO: g:python3_host_prog is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.6.8
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
```

### Actual behavior

```
## Python 3 provider (optional)
  - WARNING: No Python executable found that can import neovim. Using the first available executable for diagnostics.
  - WARNING: Could not load Python 3:
    /usr/bin/python3 is Python 3.6 and cannot provide Python >= 3.7.
    python3.10 not found in search path or not executable.
    /usr/bin/python3.9 does not have the "neovim" module.
    python3.8 not found in search path or not executable.
    python3.7 not found in search path or not executable.
    /usr/bin/python is Python 3.6 and cannot provide Python >= 3.7.
```

Looking at the commits log, python3.6 support was removed in baec0d3152afeab3007ebb505f3fc274511db434 but the commit message says: "feat(provider)!: remove support for python2 and python3.[3-5]" so it seems python3.6 was not intended to be removed?

Distros like Centos 8 defaults to python3.6 so it would be nice to have it back.

**Comment by Shougo** [comment]
The commit message seems wrong.
Python 3.6 support is removed.

**Comment by clason** [comment]
Sorry, Python 3.6 has reached end-of-life last year so was removed.

The commit message should have mentioned that; seems like this slipped through. You should always click through to the PR including discussion for details: https://github.com/neovim/neovim/pull/17222
