### ISSUE TITLE
bug(cmdheight=0): floating window above cmdline fails to redraw (using whichkey, cmp-cmdline)

### ISSUE THREAD

**Issue by akinsho** [neovim/neovim#20106]
### Neovim version (nvim -v)

v0.8.0-dev-2497-gfd1595514-dirty 

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 12.4

### Terminal name/version

Kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

1. Install `which-key.nvim` it is hard to reproduce the behaviour of overlapping windows on key press from the commandline without it.

2. run `git checkout 7ee35a7614e34e562fd3f815ad35bd6d7e456093` as the author has added in a workaround which no longer triggers this issue (seems to hide it whilst a fix is being awaited)

Author's workaround 👉🏿 https://github.com/folke/which-key.nvim/commit/c96627900191355e6788629bbf5239d7295221f0

```lua
set rtp+=~/src/which-key.nvim

vim.o.cmdheight = 0

vim.cmd([[
nnoremap <Leader>aa   <Cmd>echo "hoge"<CR>
nnoremap <Leader>ba   <Cmd>echo "hoge"<CR>
nnoremap <Leader>ca   <Cmd>echo "hoge"<CR>
nnoremap <Leader>da   <Cmd>echo "hoge"<CR>
nnoremap <Leader>ea   <Cmd>echo "hoge"<CR>
nnoremap <Leader>fg   <Cmd>echo "hoge"<CR>
]])

```

3. `nvim -u <minimal-config-above>`
4. Press `<leader>a` wait a moment
5. press `a` you should see both windows overlap

### Expected behavior

The second window replaces the first. This is an exact regression of #19184 and reproduces in the same way. The cause is likely related to https://github.com/neovim/neovim/pull/19816#issuecomment-1238284631 i.e. the difference in the redraw mechanism mentioned in that PR.

This issues stems from https://github.com/neovim/neovim/pull/19816#issuecomment-1238822565.

@Shougo there is no actual difference between the previous reproduction from #19184 I just didn't notice that the author added a workaround which hides this issue, so you need to check out a commit before the workaround. I have added it to reproduction instructions

### Actual behavior

https://user-images.githubusercontent.com/22454918/188838488-c3ace672-44c1-4de9-9438-6a045fb468da.mov

**Comment by Shougo** [comment]
OK.  It is reproduced.

@bfredl I think the problem must be fixed.  What do you think?

https://github.com/folke/which-key.nvim/commit/c96627900191355e6788629bbf5239d7295221f0

The workaround exists.  But the fix is very ugly.

**Comment by Shougo** [comment]
Fixed in #20182

**Comment by akinsho** [comment]
FWIW, #20188 does not fix this issue. Rolling which key back to the commit before the workaround whilst using that latest implementation still causes this issue.

**Comment by Shougo** [comment]
I can add UPD_CLEAR, but I don't know it is the right fix.
@bfredl What do you think?

**Comment by bfredl** [comment]
need reproduce with core only. otherwise it is impossible to know what behavior is from core or from the plugin.

**Comment by akinsho** [comment]
Just spent a bit of time trying to reproduce this by opening windows above the commandline on `CmdlineChanged`, but that doesn't actually open windows in sequence for whatever reason, also read through some of the code in which-key, but frankly I can't see the flow from key to key. @folke if you get a chance, would you be able to provide some advice.

This relates to https://github.com/folke/which-key.nvim/commit/c96627900191355e6788629bbf5239d7295221f0. I'm not sure how to reproduce what which key is doing.

This also seems to be affecting https://github.com/hrsh7th/cmp-cmdline and maybe other plugins opening windows in sequence above the commandline. I'll update the title, and maybe someone else using either plugin might be able to reverse engineer a core only reproduction.

**Comment by folke** [comment]
@bfredl  The problem seems to happen when doing  a `redraw` after having used `nvim_echo`. See minimal example below:

```lua
local opts = {
  relative = "editor",
  width = vim.o.columns,
  height = 10,
  focusable = false,
  anchor = "SW",
  border = "single",
  row = vim.o.lines - 2 - vim.o.cmdheight + 1,
  col = 0,
  style = "minimal",
  noautocmd = true,
}

local M = {}

M.buf = vim.api.nvim_create_buf(false, true)
M.win = vim.api.nvim_open_win(M.buf, false, opts)

vim.api.nvim_buf_set_option(M.buf, "bufhidden", "wipe")

vim.cmd([[hi FooBar guibg=#ff007c guifg=white]])
vim.api.nvim_win_set_option(M.win, "winhighlight", "NormalFloat:FooBar,FloatBorder:FooBar")

vim.api.nvim_win_set_height(M.win, 10)
vim.cmd([[redraw]])

vim.api.nvim_win_set_height(M.win, 5)
vim.api.nvim_echo({ { "" } }, false, {})
vim.cmd([[redraw]])

-- vim.fn.getchar()
vim.api.nvim_win_close(M.win, true)
```
After running this code, you'll see the ugly pink bar at the bottom, which should not be there. Removing the `nvim_echo` at line 27 works correctly. Using `mode` instead of `redraw` also fixes this.

![image](https://user-images.githubusercontent.com/292349/190627183-535db02e-af18-4578-90f7-4d8989ba0f7e.png)

**Comment by Shougo** [comment]
Reproduced...

**Comment by zeertzjq** [comment]
Actually the same problem happens without cmdheight=0 if the message needs multiple lines:
```lua
local opts = {
  relative = "editor",
  width = vim.o.columns,
  height = 10,
  focusable = false,
  anchor = "SW",
  border = "single",
  row = vim.o.lines - 2 - vim.o.cmdheight + 1,
  col = 0,
  style = "minimal",
  noautocmd = true,
}

local M = {}

M.buf = vim.api.nvim_create_buf(false, true)
M.win = vim.api.nvim_open_win(M.buf, false, opts)

vim.api.nvim_buf_set_option(M.buf, "bufhidden", "wipe")

vim.cmd([[hi FooBar guibg=#ff007c guifg=white]])
vim.api.nvim_win_set_option(M.win, "winhighlight", "NormalFloat:FooBar,FloatBorder:FooBar")

vim.api.nvim_win_set_height(M.win, 10)
vim.cmd([[redraw]])

vim.api.nvim_win_set_height(M.win, 5)
vim.api.nvim_echo({ { "\n" } }, false, {})
vim.cmd([[redraw]])
```
This causes a similar redraw problem in both HEAD and v0.7.2.

**Comment by zeertzjq** [comment]
Removing this line seems to fix the problem:
```diff
diff --git a/src/nvim/drawscreen.c b/src/nvim/drawscreen.c
index 957e8ae4d..688e98125 100644
--- a/src/nvim/drawscreen.c
+++ b/src/nvim/drawscreen.c
@@ -447,7 +447,6 @@ int update_screen(int type)
       msg_grid.throttled = false;
       // UPD_CLEAR is already handled
       if (type == UPD_NOT_VALID && !ui_has(kUIMultigrid) && msg_scrolled) {
-        ui_comp_set_screen_valid(false);
         for (int i = valid; i < Rows - p_ch; i++) {
           grid_clear_line(&default_grid, default_grid.line_offset[i],
                           Columns, false);
```

**Comment by Shougo** [comment]
I will test it.

**Comment by Shougo** [comment]
![スクリーンショット_2022-09-19_14-29-13](https://user-images.githubusercontent.com/41495/190954627-9dffa575-aff7-4057-ab86-d9e966a2b3a2.png)

It is better but current input is cleared.

**Comment by zeertzjq** [comment]
It seems that `:redrawstatus` in cmdline mode with cmdheight=0 will cause command line to be hidden.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/pull/20249 fixes the problem.
