### ISSUE TITLE
Allow custom `lsp-handler` to return `false` result

### ISSUE THREAD

**Issue by hungpt2702** [neovim/neovim#20111]
### Problem
I'm trying to implement a custom handler for a ls method that expects boolean result. However, currently `lsp-handler` cannot return  `false` (will cause an error) which I suspect is due to these lines of code in `lua/vim/lsp/rpc.lua`:
```lua
if not (result or err) then
  -- TODO this can be a problem if `null` is sent for result. needs vim.NIL
  error(
    string.format(
      'method %q: either a result or an error must be sent to the server in response',
      decoded.method
    )
  )
end
```
### Suggestion
Use a workaround like how `nil` value is handled (using `vim.NIL`) to allow `lsp-handler` to return `false`.

**Comment by mfussenegger** [comment]
It would probably work to change the condition to `if result == nil and err == nil then`
