### ISSUE TITLE
Jump forward with `<C-i>` wont work

### ISSUE THREAD

**Issue by dvogt23** [neovim/neovim#20126]
### Neovim version (nvim -v)

NVIM v0.7.2 release

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 11.15

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

brew

### How to reproduce the issue

1. Open a file with some text
2. jump sometime to next finding
3. Jump back with `<C-o>`
4. Jump forward with `<C-i>` (wont work)

### Expected behavior

Jumps forward to next jumplist as described in https://neovim.io/doc/user/motion.html#CTRL-I as similiar behavior like vim.

### Actual behavior

jumps not

**Comment by zeertzjq** [comment]
Needs steps to reproduce with `--clean`

**Comment by dvogt23** [comment]
Damn, just tried with `nvim -u None` and it didnt work, but with `nvim --clean` it works.

Repro-steps:

1. Open `nvim`
2. `:help lua`
3. Go to `:runtime`
4. `<C-]>` to jump to `:runtime`
5. Jump back with `<C-o>`
6. Jump forward with `<C-i>`

**Comment by zeertzjq** [comment]
`nvim -u None` reads config from a file called `None`. `nvim -u NONE` runs without config.

**Comment by dvogt23** [comment]
Good to know, but if that file `None` didnt exist, shouldnt be the same? 🤔 It isnt... obviously.

BTT how its possible to have no function on `<C-i>`? 🙈 No entry in `:nmap` as well ...

**Comment by dvogt23** [comment]
Ok, did map `<TAB>` and its overwrite the `<C-i>` mapping as well 😞 Thanks for help

**Comment by zeertzjq** [comment]
You can map `<C-I>` to itself to so that jumping forward still works.

**Comment by rbjorklin** [comment]
I'm having the same problem which I have figured out is caused by [this line](https://github.com/rbjorklin/set-me-up/blob/master/files/conf/nvim/after/plugin/bufferline.lua#L36) in my config. Unfortunately adding `keymap("n", "<C-I>", "<C-I>", { noremap = true })` to my config both before and after that line has no effect. How do I go about restoring the original jumplist behaviour of `<C-I>` ?

**Comment by zeertzjq** [comment]
> I'm having the same problem which I have figured out is caused by [this line](https://github.com/rbjorklin/set-me-up/blob/50172a9e1ed13dee28eed06508a51337caac018a/files/conf/nvim/after/plugin/bufferline.lua#L36) in my config. Unfortunately adding `keymap("n", "<C-I>", "<C-I>", { noremap = true })` to my config both before and after that line has no effect. How do I go about restoring the original jumplist behaviour of `<C-I>` ?

It's possible that you terminal emulator sends the same sequence for `<Tab>` and `<C-I>`, and in this case it will be recognized as `<Tab>`. Not all terminal emulators can send different sequences for `<Tab>` and `<C-I>`.

**Comment by rbjorklin** [comment]
> > I'm having the same problem which I have figured out is caused by [this line](https://github.com/rbjorklin/set-me-up/blob/50172a9e1ed13dee28eed06508a51337caac018a/files/conf/nvim/after/plugin/bufferline.lua#L36) in my config. Unfortunately adding `keymap("n", "<C-I>", "<C-I>", { noremap = true })` to my config both before and after that line has no effect. How do I go about restoring the original jumplist behaviour of `<C-I>` ?
> 
> It's possible that you terminal emulator sends the same sequence for `<Tab>` and `<C-I>`, and in this case it will be recognized as `<Tab>`. Not all terminal emulators can send different sequences for `<Tab>` and `<C-I>`.

This does indeed seem to be the case. I just tried `<C-Q><C-I>` in insert mode and I'm getting a `<Tab>` character. Any known workaround for this?

**Comment by zeertzjq** [comment]
> This does indeed seem to be the case.

What terminal emulator are you using?

**Comment by rbjorklin** [comment]
> > This does indeed seem to be the case.
> 
> What terminal emulator are you using?

[alacritty](https://github.com/alacritty/alacritty/)

**Comment by zeertzjq** [comment]
> > > This does indeed seem to be the case.
> > 
> > 
> > What terminal emulator are you using?
> 
> [alacritty](https://github.com/alacritty/alacritty/)

From <https://github.com/neovim/neovim/issues/17867#issuecomment-1089826204>:

```yaml
# ~/.config/alacritty/alacritty.yml
key_bindings:
  - { key: I, mods: Control, chars: "\x1b[105;5u" }
```

**Comment by rbjorklin** [comment]
Thanks, that change combined with `keymap("n", "<C-I>", "<C-I>", { noremap = true })` does indeed fix it. Unfortunately the problem persists when also using tmux but that seems to be a tmux specific issue: https://github.com/tmux/tmux/issues/2705

Thanks a lot for your help @zeertzjq! :heart:

**Comment by mebble** [comment]
I had the same problem where my `<C-I>` would not go forward the same locations that `<C-O>` goes backwards through. I'm using iterm2 and tmux. I realised it was because I remapped `<Tab>` in normal mode to switch buffers, similar to this issue https://github.com/neovim/neovim/issues/20126#issuecomment-1296033889

I decided to just avoid remapping Tab and instead switch buffers with the following mappings, and it now works:

```lua
vim.keymap.set('n', '<leader>n', '<cmd>bnext<CR>', { desc = '[N]ext buffer' })
vim.keymap.set('n', '<leader>p', '<cmd>bprevious<CR>', { desc = '[P]revious buffer' })
```
