### ISSUE TITLE
New terminal UI broke inputing "strange" UTF-8 like …

### ISSUE THREAD

**Issue by nicoe** [neovim/neovim#2013]
I built neovim from commit 66a03a7385dfd11503d22d8cc9dc6a972e27dcc2
Since that time inputing "strange" characters like '…' does not work. Those characters can not be copy / pasted neither.
Opening a file containing such characters is not a problem though.

**Comment by tarruda** [comment]
@nicoe can you test if #2007 fixes your problems?

**Comment by tarruda** [comment]
#2007 was merged and it should fix the issue
