### ISSUE TITLE
Man pages highlighting fails with lua nil value exception

### ISSUE THREAD

**Issue by tbung** [neovim/neovim#20135]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1060-g22a88c425

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 22.04

### Terminal name/version

kitty 0.21.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

```
nvim --clean -c ':Man bash'
```

### Expected behavior

The man page opens without error and is highlighted as before.

### Actual behavior

Nvim shows the following error:
```
Error detected while processing command line..function man#open_page[43]..command line..function man#open_page[38]..BufReadCmd Autocommands for "man://*"..function man#read_page[11]..<SNR>22_put_page:
line   12:
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'highlight_man_page' (a nil value)^@stack traceback:^@^I[string ":lua"]:1: in main chunk
```
and then shows the man page, but with escape codes:
![Screenshot 2022-09-09 at 15 29 19](https://user-images.githubusercontent.com/4084982/189361220-2e73dd64-8e99-4bd4-8e4e-75073bb3d1d7.png)

**Comment by clason** [comment]
You need to manually remove the old Vim plugin from runtime.

**Comment by tbung** [comment]
Thank you!
