### ISSUE TITLE
Define options for every floating window

### ISSUE THREAD

**Issue by datwaft** [neovim/neovim#20146]
### Feature already in Vim?

No

### Feature description

About a year ago I asked [this question](https://neovim.discourse.group/t/is-there-a-way-to-set-options-only-for-a-hover-buffer/959) in the Neovim discourse group about how to define options for a 'hover buffer', which I now know is called a floating window, and couldn't get my issue solved.

I decided to revisit this issue because I don't like how the floating windows inherit the `showbreak`, `breakindent` and `breakindentopt` options, as you can see in the screenshot.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/189497061-be691624-caaf-419e-a7dd-543027c0d090.png">

I have read `:h api-floatwin` and `:h nvim_open_win` and couldn't find a way to define those options for every floating window that is opened.

One the first things I tried when I first found this issue was to find if the floating windows had some filetype or the like that I could use to modify the floating windows.

One easy example is with the following snippet:

```javascript
/**
 * @name hello
 * A function with a veeeeeery long description. I am adding random words so that the description is very and has to be soft-wrapped. Word Word Word Word Word Word Word.
 */
function hello() {
  console.log("Hello World");
}
```

If you have the following vim options set:

```vim
set linebreak
set breakindent
set breakindentopt=shift:2
set showbreak=↳\ 
```

And execute `:lua vim.lsp.buf.hover()` when having the cursor on `hello` the documentation is wrapped using those options.

In `:h api-floatwin` I found a possible way to do that, but I don't know how it could be applied to `vim.lsp.buf.hover` and the like.

> Example: create a float with scratch buffer:  
>
> ```vim
> let buf = nvim_create_buf(v:false, v:true)
> call nvim_buf_set_lines(buf, 0, -1, v:true, ["test", "text"])
> let opts = {'relative': 'cursor', 'width': 10, 'height': 2, 'col': 0,
>     \ 'row': 1, 'anchor': 'NW', 'style': 'minimal'}
> let win = nvim_open_win(buf, 0, opts)
> " optional: change highlight, otherwise Pmenu is used
> call nvim_win_set_option(win, 'winhl', 'Normal:MyHighlight')
> ```

Thanks for your help!

**Comment by glepnir** [comment]
disable wrap by using this 
```lua
vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(
  vim.lsp.handlers.hover, {
     wrap = false
  }
)

```

**Comment by justinmk** [comment]
Should be possible with a `WinNew` autocmd that inspects `nvim_win_get_config()`.

**Comment by datwaft** [comment]
> disable wrap for default hover `vim.lsp.buf.hover` by using this . your screenshot looks like nvim-cmp? it not using default functions and the floatwindow is defined by cmp.
> 
> ```lua
> vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(
>   vim.lsp.handlers.hover, {
>      wrap = false
>   }
> )
> ```

@glepnir Thanks! That helps a little bit, but that leads to not being able to read the information that is wrapped.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/189551704-fbafc201-01c0-463a-a4dd-35c5b15bdb5a.png">

> Should be possible with a WinNew autocmd that inspects nvim_win_get_config() (the relative field indicates "floating").

@justinmk Do you have an example?

I just tried creating the following `autocmd`, but the message is not displayed when executing `vim.lsp.buf.hover`.

```lua
vim.api.nvim_create_autocmd("WinNew", {
  pattern = "*",
  callback = function()
    local config = vim.api.nvim_win_get_config(0)
    print(vim.inspect(config))
  end,
})
```

If execute `:copen` or `:help` the message is displayed, though.

**Comment by glepnir** [comment]
> but that leads to not being able to read the information that is wrapped.

right that mean disable wrap so if the text longer than window . you can't see the text over the window.

`0` is mean the current widow that cursors in . so you can't use 0 for that. use `nvim_list_wins` to find the hover window then do something

**Comment by datwaft** [comment]
> `0` is mean the current widow that cursor in . so you can't use 0 for that. use `nvim_list_wins` to find the hover window then do something

Thanks!

I still have the problem that the `autocmd` is not executed when executing `vim.lsp.buf.hover`, but if I fix that I can iterate over the windows and then set options for every window that is floating.

```lua
-- This is not executed with `vim.lsp.buf.hover`
vim.api.nvim_create_autocmd("WinNew", {
  pattern = "*",
  callback = function()
    local windows = vim.api.nvim_list_wins()
    print(vim.inspect(windows))
  end,
})
```

**Comment by glepnir** [comment]
so it's not winnew . use this way will more easy 

```lua
local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview
function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
  -- also you can override some options like
  -- opts.wrap = false or opts.boder .something lese
  local bufnr,winid = orig_util_open_floating_preview(contents, syntax, opts, ...)
  print(bufnr,winid)
end
```

**Comment by datwaft** [comment]
> so it's not winnew . use this way will more easy
> 
> ```lua
> local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview
> function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
>   -- also you can override some options like
>   -- opts.wrap = false or opts.boder .something lese
>   local bufnr,winid = orig_util_open_floating_preview(contents, syntax, opts, ...)
>   print(bufnr,winid)
> end
> ```

Nice idea!

I cannot use `opts` for any arbitrary option like `showbreak`, so I thought about using `vim.api.nvim_win_set_option`, but it seems that it doesn't work.

```lua
local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview
function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
  local bufnr, winid = orig_util_open_floating_preview(contents, syntax, opts, ...)
  vim.api.nvim_win_set_option(winid, "breakindentopt", "")
  vim.api.nvim_win_set_option(winid, "showbreak", "")
  print(bufnr, winid)
end
```

The option `breakindentopt` works, but `showbreak` doesn't seem to work.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/189564598-e83f9198-b188-4507-8fbd-d762103938ff.png">

If I go inside the floating window and do `setlocal showbreak?` it displays `showbreak=`, which means that the option is properly set for the window, but even then it doesn't seem to work.

Is this a bug? Should I open a new issue for it?

**Comment by glepnir** [comment]
if you want disable it use `showbreak = NONE` not set it to empty string

**Comment by datwaft** [comment]
Thanks a lot! It works now! 😄 

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/189565296-913412f4-071e-4d75-a509-d97c4d6a1193.png">

**Comment by rafaelleyva** [comment]
Which font is this?

**Comment by rafaelleyva** [comment]
May i know the font you were using in the screenshot?
