### ISSUE TITLE
Output of `nvim -r` contains `file name: ~username/file.txt` instead of `file name: ~/file.txt`

### ISSUE THREAD

**Issue by camoz** [neovim/neovim#20156]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

yes, version 7.4.629

### Operating system/version

archlinux, current

### Terminal name/version

foot version: 1.13.1

### $TERM environment variable

foot-extra

### Installation

official arch repos

### How to reproduce the issue

- have some file under "$HOME" open: `nvim ~/file.txt`
- run `nvim -r`

### Expected behavior

output contains `file name: ~/file.txt`

### Actual behavior

output contains `file name: ~username/file.txt` which is not a file

For convenience, the full output looks like this:

```
3.    %home%username%file.txt.swp
          owned by: username   dated: Sat Sep 10 23:29:02 2022
         file name: ~username/file.txt
          modified: no
         user name: username   host name: hostname
        process ID: 247410

```

**Comment by zeertzjq** [comment]
> ### Expected behavior
> output contains file name: ~/file.txt

Why?

**Comment by camoz** [comment]
Ah, I didn't know about tilde expansion, I thought `~` is just a shortcut for $HOME and hence that the filename is invalid... sorry!
