### ISSUE TITLE
vim.highlight.on_yank error with blockwise region and multibyte characters

### ISSUE THREAD

**Issue by wodesuck** [neovim/neovim#20161]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.4

### Terminal name/version

iTerm 3.4.16

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

`nvim --clean`

`:au TextYankPost * lua vim.highlight.on_yank()`

Input text `åå`.

Return to normal mode, type `0<c-v>lly` to blockwise select and yank first line.

### Expected behavior

Highlight yanked text.

### Actual behavior

```
Error detected while processing TextYankPost Autocommands for "*":
E5108: Error executing lua vim/_editor.lua:0: index out of range
stack traceback:
        [C]: in function 'str_byteindex'
        vim/_editor.lua: in function 'region'
        .../neovim/0.7.2_1/share/nvim/runtime/lua/vim/highlight.lua:49: in function 'range'
        .../neovim/0.7.2_1/share/nvim/runtime/lua/vim/highlight.lua:127: in function 'on_yank'
        [string ":lua"]:1: in main chunk
```

**Comment by wodesuck** [comment]
https://github.com/neovim/neovim/blob/master/runtime/lua/vim/_editor.lua#L433-L438

**Comment by clason** [comment]
Blockwise selection with multibyte characters is a known issue with `vim.region` (Lua vs. Vim indexing for such characters), see https://github.com/neovim/neovim/pull/13896.

**Comment by wodesuck** [comment]
https://github.com/neovim/neovim/blob/master/runtime/lua/vim/_editor.lua#L433-L438

```lua
      if c1 < #bufline then
        c1 = vim.str_byteindex(bufline, c1)
      end
      if c2 < #bufline then
        c2 = vim.str_byteindex(bufline, c2)
      end
```

The problem may happen here, `c1 < #bufline` should be `c1 < str_utflen(bufline)` (If some function that calculate utf length of string exist)

**Comment by clason** [comment]
Yes, that sounds reasonable. Can you test it and open a PR if it fixes that?

**Comment by clason** [comment]
We may need to bundle one of the utf8 libraries listed at the end of http://lua-users.org/wiki/LuaUnicode to get this (and other cases) working correctly, either
* https://github.com/alexander-yakushev/awesompd/blob/master/utf8.lua (minimal, pure Lua)
* https://github.com/starwing/luautf8 (full `utf8` library with 5.3 parity, in C)

**Comment by wodesuck** [comment]
I open a PR #20162 to fix it.

I use `vim.str_byteindex(bufline, #bufline)` to cacluate utf length of `bufline`. And if `c1`/`c2` is out of range, set it to `#bufline + 1`
