### ISSUE TITLE
Add @nospell for treesitter queries like @NoSpell for regex syntax highlighting

### ISSUE THREAD

**Issue by akinsho** [neovim/neovim#20174]
### Feature already in Vim?

N/A

### Feature description

Recently `@spell` support was added to treesitter highlighting which is fantastic and very much appreciated. I've noticed it being added in quite a few languages (in nvim-treesitter) which is generally good, however it would be nice to be able to override spelling for a user or plugin author's use case.

There is the existing `contains=@NoSpell` for [regex syntax highlighting](https://vimhelp.org/spell.txt.html?#spell-syntax), and it would be nice if this could also be mirrored for treesitter e.g.

```scheme
(string) @nospell
(specific (complex (substring))) @nospell
```

This way a user can disable upstream spelling in certain circumstances where they don't want it e.g. injections, areas of a code base they know to have loads of gibberish spelling, potentially per project, or simply if they disagree with it in a specific node 🤷🏿‍♂️, I think there are likely plenty more reasons why this could be useful.

**Comment by lf-** [comment]
It seems that this is nearly a complete necessity for languages that are *mostly* text such as LaTeX and Markdown, which let all the text just land in anonymous nodes. For instance, this occurs under an `inline` node in the case of markdown. However, `inline` can have children such as inline code, which should not be spell checked.

There's not any way to write a query for "arbitrary anonymous nodes, but no named nodes at all" in treesitter that I can find.
