### ISSUE TITLE
Treesitter query overrides placed in 'after' no longer function

### ISSUE THREAD

**Issue by AlanWarren** [neovim/neovim#20172]
### Neovim version (nvim -v)

v0.8.0-dev-1077-g5bc0964b9-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.5.1

### Terminal name/version

iterm 3.4.16

### $TERM environment variable

xterm-256color

### Installation

homebrew HEAD

### How to reproduce the issue

Assuming we have nvim-treesitter installed with the javascript parser.   Up until the latest nightly, I've been able to **extend** treesitter queries by placing my own highlights.scm file inside `~/.config/nvim/after/queries/<language>/`

For example, if I create the file `~/.config/nvim/after/queries/javascript/highlights.scm` with the following contents. 

```
   (optional_chain) @constant
```

 I open a javascript file in neovim and inspect a line of code which uses optional chaining under the cursor with :TSHighlightCapturesUnderCursor .   i.e. `const test = foo?.bar` 

```
# Treesitter
 * @punctuation.delimiter
```

I expect to see  
```
# Treesitter
 * @punctuation.delimiter
 * @constant
```
Is there anything I should be doing to properly override highlights now?   

After reading https://github.com/neovim/neovim/pull/20105
and also reading :h lua-treesitter-query as well, I've found that if I move all my old `~/.config/nvim/after/queries` directly into `~/.config/nvim/queries` and append the `; extends` modeline to each one of the individual highlights.scm files then everything works as I would have expected my _after_ highlights to function.  

Is this intentional? 

### Expected behavior

I expect query overrides placed in ~/.config/nvim/after/queries/ to extend the highlights loaded from rtp

### Actual behavior

Any queries placed in ~/.config/nvim/after/queries are ignored.

**Comment by bfredl** [comment]
you need an `extends` modeline, also from an "after" file https://github.com/neovim/neovim/issues/14090#issuecomment-1240357210

**Comment by AlanWarren** [comment]
Thanks for clarifying.  At the time it seemed a bit ambiguous to me since this is the behavior I expect from configuration placed inside 'after'.

**Comment by clason** [comment]
Yes, the documentation is out of date. Neovim moves fast with features...
