### ISSUE TITLE
Typo in installation instructions for macOS / OS X (docs) #WIKI

### ISSUE THREAD

**Issue by flaxflour** [neovim/neovim#20180]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.5.1

### Terminal name/version

Apple Termnal Version 2.12.7 (445)

### $TERM environment variable

xterm-256color

### Installation

curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz

### How to reproduce the issue

https://github.com/neovim/neovim/wiki/Installing-Neovim#pre-built-archives-1

### Expected behavior

nvim should open

### Actual behavior

typo in directory name

current WIKI
```
curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
tar xzf nvim-macos.tar.gz
./nvim-osx64/bin/nvim
```

path to bin should be 

`./nvim-macos/bin/nvim`

<img width="727" alt="Screen Shot 2022-09-13 at 13 46 03" src="https://user-images.githubusercontent.com/31704887/189869637-0d28bfb8-db6d-4f42-90b3-154a3b191964.png">

**Comment by flaxflour** [comment]
Sorry for the wrong issue label? I don't know how to contribute to the this wiki 😬

**Comment by clason** [comment]
Thanks, fixed!
