### ISSUE TITLE
reallocarray()

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#2020]
OpenBSD added this in the last few months, and I thought it would be worth considering for use in Neovim. [Here's an article on it](http://lteo.net/blog/2014/10/28/reallocarray-in-openbsd-integer-overflow-detection-for-free/) which should quickly give you an idea of its purpose, and [a discussion on it](https://www.reddit.com/r/programming/comments/2iwzqs/openbsds_reallocarray_extension_xpost_from_rcprog/) regarding different possible implementations.

I mention this because I've noticed a lot of usage of `xmalloc(nmemb * size);` and `xrealloc(ptr, nmemb * size);` throughout the code-base.

**Comment by justinmk** [comment]
:+1: The reddit discussion is worth reading too. This is generally applicable to any popular function that takes the result of a calculation: let the popular function do the calculation internally and check for overflow.

**Comment by elmart** [comment]
Would be a good way to avoid overflow in a bunch of places. :+1: 
Just two comments, though, about differences between our would-be version and the one in the article:
- We would never return NULL.
- I don't understand the need for `(nmemb >= MUL_NO_OVERFLOW || size >= MUL_NO_OVERFLOW)` checks (and hence the need for `MUL_NO_OVERFLOW` constant. Checking `SIZE_MAX / nmemb < size` is enough and more flexible (doesn't impose artificial limit on operands).

**Comment by oni-link** [comment]
> I don't understand the need for (nmemb >= MUL_NO_OVERFLOW || size >= MUL_NO_OVERFLOW) checks (and hence the need for MUL_NO_OVERFLOW constant. Checking SIZE_MAX / nmemb < size is enough and more flexible (doesn't impose artificial limit on operands).

They try to prevent the (expensive) division, because most of the time `nmemb*size << sqrt(SIZE_MAX+1)*sqrt(SIZE_MAX+1)`.

**Comment by elmart** [comment]
> They try to prevent the (expensive) division

That can be an explanation. But that rules out possible legal cases where one of the factors is bigger than the square root and the other one is smaller. In our case, where we abort instead of returning NULL, I think it's not worth the risk, just to spare a division. Besides, that's a bit of premature optimization, IMO. I would first make it correct, and then, if proved slow, profile it and optimize the hotspots.

**Comment by oni-link** [comment]
>  But that rules out possible legal cases where one of the factors is bigger than the square root and the other one is smaller.

No legal case is marked as illegal. If one factor is bigger than `MUL_NO_OVERFLOW` there is still the division that needs to be checked:

```c
void *
reallocarray(void *optr, size_t nmemb, size_t size)
{
    if ((nmemb >= MUL_NO_OVERFLOW || size >= MUL_NO_OVERFLOW) &&
        nmemb > 0 && SIZE_MAX / nmemb < size) {
            errno = ENOMEM;
            return NULL;
    }
    return realloc(optr, size * nmemb);
}
```

**Comment by aktau** [comment]
A division is about 10x more expensive than an addition/subtraction when I was last benchmarking it (on an early-gen i7, which already does much better on those things than earlier machines afaik). So what @oni-link says sounds like it could be true to me.

**Comment by justinmk** [comment]
reddit suggested this alternative:

```c
void*
reallocarray(void *optr, size_t nmemb, size_t size)
{
    size_t prod;
    if (__builtin_expect(umull_overflow(size, nmemb, &prod),0)) {
        errno = ENOMEM;
        return NULL;
    }
    return realloc(optr, prod);
}
```

**Comment by elmart** [comment]
> No legal case is marked as illegal

Uh, you're right. Sorry for that.

> __builtin_expect(umull_overflow

Isn't that gcc only?

**Comment by ZyX-I** [comment]
`__builtin_expect` is supported by clang as it seems so, but `umull_overflow` is not. CLang has `__builtin_umull_overflow`, gcc does not and neither it has `umull_overflow` (at least not without linking additional libraries). I have found [a topic](http://renren.io/questions/158983/multiplication-of-large-numbers-how-to-catch-overflow) with possible `umull_overflow` implementations and their benchmark.

**Comment by Pyrohh** [comment]
@elmart 

> We would never return NULL.

Then what would we do if the multiplication overflowed? I'm not familiar with the expected semantics of nvim's memory functions.

**Comment by philix** [comment]
@Pyrohh we try to free some memory, try again, and call `preserve_exit()` when OOM to avoid handling OOM everywhere. I guess we could do the same (except for the freeing memory part) when overflowing.

```c
void *xmalloc(size_t size)
  FUNC_ATTR_MALLOC FUNC_ATTR_ALLOC_SIZE(1) FUNC_ATTR_NONNULL_RET
{
  void *ret = try_malloc(size);
  if (!ret) {
    mch_errmsg(e_outofmem);
    mch_errmsg("\n");
    preserve_exit();
  }
  return ret;
}
```

**Comment by philix** [comment]
I would add an `ELOG` since overflow here is probably a programming mistake.

```c
void *xreallocarray(void *optr, size_t nmemb, size_t size)
  FUNC_ATTR_WARN_UNUSED_RESULT FUNC_ATTR_ALLOC_SIZE_PROD(1, 2) FUNC_ATTR_NONNULL_RET
{
  if ((nmemb >= MUL_NO_OVERFLOW || size >= MUL_NO_OVERFLOW) &&
      nmemb > 0 && SIZE_MAX / nmemb < size) {
    ELOG("xreallocarray detected an integer overflow");
    preserve_exit();
  }
  return xrealloc(optr, size * nmemb);
}
```

**Comment by Pyrohh** [comment]
@philix When I create a call which to xreallocarray which causes an overflow, the ELOG doesn't seem to log anything to .nvimlog . I can look into it later, but I assume it's to do with preserve_exit().

**Comment by philix** [comment]
@Pyrohh It's weird since `ELOG` flushes the output file buffer on every call. You can `assert(ELOG(...))` to check if flushing was successful.

**Comment by Pyrohh** [comment]
The assert isn't thrown... do I need to pass something like DEBUG_LEVEL to the build?

**Comment by philix** [comment]
> The assert isn't thrown... do I need to pass something like DEBUG_LEVEL to the build?

`ELOG` should be enabled by default on a debug build. Can you `printf` right before `preserve_exit()`?

**Comment by Pyrohh** [comment]
> Can you printf right before preserve_exit()?

Hmm, that doesn't seem to work.

**Comment by philix** [comment]
@Pyrohh it's weird. Does `fflush(stdout)` help?

**Comment by Pyrohh** [comment]
> it's weird. Does fflush(stdout) help?

Unfortunately, no. I'm using reallocarray calls in syntax.c here:

```patch
diff --git a/src/nvim/syntax.c b/src/nvim/syntax.c
index 20bfbc8..3fe669c 100644
--- a/src/nvim/syntax.c
+++ b/src/nvim/syntax.c
@@ -4660,7 +4660,7 @@ static void syn_combine_list(short **clstr1, short **clstr2, int list_op)
         clstr = NULL;
         break;
       }
-      clstr = xmalloc((count + 1) * sizeof(short));
+      clstr = xreallocarray(NULL, (count + 1), 100000000000);
       clstr[count] = 0;
     }
   }
@@ -5193,7 +5193,7 @@ get_id_list (
     if (failed)
       break;
     if (round == 1) {
-      retval = xmalloc((count + 1) * sizeof(short));
+      retval = xreallocarray(NULL, (count + 1), 100000000000);
       retval[count] = 0;            /* zero means end of the list */
       total_count = count;
     }
```

I assume the screen is being flushed before the UI closes, but I don't know from where...
If it's any consolation, a malignant xreallocarray call prints the error message if it's in main.c:early_init() :smile:

**Comment by justinmk** [comment]
This was the last issue tagged `reopen-later`. So, re-opening it now.

**Comment by justinmk** [comment]
No clear plan here, and we have `xcalloc` at least now.
