### ISSUE TITLE
losing typeahead keys

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#2021]
After the TUI merge, it seems nvim loses typeahead keys if it's busy. E.g. if I do a slow operation (using https://github.com/Shougo/unite.vim) like:

    :Unite -start-insert line 

And quickly type `foo` while unite is loading, only `f` is inserted. `oo` appear to have been discarded.

**Comment by tarruda** [comment]
I'm not familiar with Unite, but for me `:Unite -start-insert line` isn't a slow operation(I have no idea what its supposed to do). Can you reproduce the problem with another command?

**Comment by kopischke** [comment]
> I'm not familiar with Unite, but for me `:Unite -start-insert line` isn't a slow operation(I have no idea what its supposed to do)

That loads **all** lines of a buffer into a Dictionary for filtering / selection in the *Unite* buffer. Depending on the buffer size, that can be quite a costly operation.

**Comment by tarruda** [comment]
> That loads all lines of a buffer into a Dictionary for filtering / selection in the Unite buffer. Depending on the buffer size, that can be quite a costly operation.

Not suprising it was fast for me since I was trying with an empty buffer :)

**Comment by tarruda** [comment]
even after loading a big buffer(eval.c * 4) I don't experience eaten keys. @justinmk can you reproduce this reliably?

**Comment by elmart** [comment]
I think this could be related to #2016, so, #2025 should fix it. @justinmk Have you tried using #2025?

**Comment by tarruda** [comment]
> I think this could be related to #2016, so, #2025 should fix it. @justinmk Have you tried using #2025?

Is @justinmk also using OSX?

**Comment by elmart** [comment]
I think so.

**Comment by khalidchawtany** [comment]
I had this problem and now its solved.

```
NVIM 0.0.0-alpha+201502200943 (compiled Feb 20 2015 15:53:21)
Commit: 9894720a0557cb80e11d33cb3b3a8fbf23827b9c
```

**Comment by Pyrohh** [comment]
Input now has a noticeable delay. Maybe it has something to do with the recent timeout/ttimeout/ttimeoutlen changes.

**Comment by justinmk** [comment]
I am convinced this is fixed. I can reproduce with an older build:

```
NVIM 0.0.0-alpha+201502172248 (compiled Feb 17 2015 23:55:36)                                                                                               
Commit: ad1bfd9dd0b4666cf370f5a9ed37f2b48ec17571 
```

but not with latest / d35820379f57c73e594a0c29713d64ef9e6ada22.

Curiously, to reproduce it seems to require 3 characters. If I blast it with say, 5 or 6 characters it wasn't reproducible.

Great work @tarruda
