### ISSUE TITLE
No syntax highlighting in git commit

### ISSUE THREAD

**Issue by tomashaddad** [neovim/neovim#20226]
### Neovim version (nvim -v)

0.7.2 e8ee673

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Windows 11

### Terminal name/version

Powershell 5.1 Build 22000 Rev 832

### $TERM environment variable

vtpcon/cygwin

### Installation

scoop

### How to reproduce the issue

In a repository with changes to commit:

`$ git config core.editor "nvim --clean" --replace-all`

`$ git commit`

### Expected behavior

The commit editor opens with syntax highlighting.

This is my [config](https://github.com/tomashaddad/nvim/blob/main/lua/options.lua). I'm learning, so it's bare bones. It's the same on both my laptop (Windows 11 Surface laptop 3) and desktop (Windows 11). I have installed no plugins.

On my Surface Laptop 3, where everything works (installed with scoop, equivalent to my desktop setup):

![image](https://user-images.githubusercontent.com/35619571/190841674-3ea51f62-59ac-48d7-8812-b5fa2bfe00bc.png)

Output of `:hi`:

![image](https://user-images.githubusercontent.com/35619571/190841679-73db2375-0a28-43c0-a8b1-9fb05a2559d5.png)

...

![image](https://user-images.githubusercontent.com/35619571/190841688-9a6cca38-b602-494a-a91a-a23fef96baee.png)

Note on my laptop, `:echo $TERM` outputs `vtpcon` if nvim is launched in any terminal with `nvim`, and outputs `xterm-256color` if launched via `git commit`.

### Actual behavior

On my desktop, nvim launched with `git commit` fails to set many colours.

On desktop (Windows 11, same config as expected behaviour):

![image](https://user-images.githubusercontent.com/35619571/190841632-4fb2ec3b-5093-42a5-a177-fd3e0cd4388a.png)

Output of `:hi`:

![image](https://user-images.githubusercontent.com/35619571/190841638-3cbaaac9-7451-4818-a3a8-3a2223b62824.png)

...

![image](https://user-images.githubusercontent.com/35619571/190841645-114661cc-0f8d-4b3d-bc70-553210dad2b9.png)

syntax script successfully run:

![image](https://user-images.githubusercontent.com/35619571/190842067-71b72349-bbbd-41c2-a4af-5e8364b2c42a.png)

Note on my desktop (where the issue is), `:echo $TERM` outputs `vtpcon` if nvim is launched in any terminal with `nvim`, and outputs `cygwin` if launched via `git commit`.

[Corresponding question on vi stackexchange](https://vi.stackexchange.com/questions/38521/no-syntax-highlighting-in-git-commit-with-nvim).

If `core.editor` on my desktop is instead set to `vim` (also installed with scoop), syntax highlighting works correctly as on my laptop, and `$TERM` is still set to `cygwin`, which makes me think this is a problem specific to neovim.

Syntax highlighting on my desktop works if I open a `.gitconfig` file with nvim, i.e. `nvim .gitconfig`, so this is also a problem specific to commit messages.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by tomashaddad** [comment]
Still nothing:

![image](https://user-images.githubusercontent.com/35619571/190859212-980e8c86-7524-41c2-8279-6331b3a52f97.png)

.gitconfig for comparison:

![image](https://user-images.githubusercontent.com/35619571/190859315-c4c17f4c-dd8b-4bc5-a2b7-67b0167ee60e.png)

**Comment by clason** [comment]
If it works on one machine for you but not the other, I suspect that something is messed up with your Neovim installation on the latter.

**Comment by tomashaddad** [comment]
I agree, that's why I created this bug report! :) As I wrote, both installations are neovim out of the box with a very minimal lua config. If I messed up something I'm not sure what that is (hence why I'm here), but if the devs/contributors here don't know the answer, then I'll just use `vim` as my editor. It's a bit strange that `vim` syntax highlighting works and `neovim` correctly displays other git files, though. Hmm ...

**Comment by clason** [comment]
It works for me, is all I can say. I have no way of knowing how things are set up on your machine(s)...

**Comment by tomashaddad** [comment]
Well, good news! The problem was apparently with git! I noticed that if I opened the COMMIT_EDITMSG file directly, i.e., `nvim .git/COMMIT_EDITMSG`, then syntax highlighting worked. This made me think that the problem was actually with git. I tried resetting my git config to no avail, but reinstalling git has fixed the problem.

Sorry for wasting everyone's time!
