### ISSUE TITLE
Every keymap with `silent=false` triggers `more-prompt` when `cmdheight=0`

### ISSUE THREAD

**Issue by folke** [neovim/neovim#20229]
### Neovim version (nvim -v)

72e1041429565c3a592dedc36e8b3004a24cdcc4

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

bob

### How to reproduce the issue

1. Create a mapping like:

```lua
vim.keymap.set("n", "tt", ":noh<cr>")
```

2. Use the mapping.
3. The more-prompt will appear.

### Expected behavior

I'm honestly not sure what the expected behaviour should be.
The nightly from yesterday didn't show the more-prompt all the time.

With today's build, I get the more-prompt everywhere. The only way to fix it for me is to add `{silent = true}` for all my keyboard shortcuts.

### Actual behavior

I get the more-prompt for every keymap that doesn't have `{silent = true}`

**Comment by folke** [comment]
The same happens when writing a file with `w`

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Hm...  But current behavior seems better.    Because the command is displayed when `cmdheight=1`.
You need to use `silent` for the mappings.

**Comment by dstanberry** [comment]
If I understood the documentation for more-prompt, it can be disabled with `set nomore`. But the issue is still present even after disabling the more option.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/pull/20249 fixes the problem.
