### ISSUE TITLE
Mapping <up> and <down> to <c-j> and <c-k> on 0.8 prints some escape codes

### ISSUE THREAD

**Issue by kristijanhusak** [neovim/neovim#20231]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1109-g72e104142

### Vim (not Nvim) behaves the same?

Both nvim 0.7.2 and Vim 9.* doesn't have this issue

### Operating system/version

Archlabs Linux and Manjaro Linux

### Terminal name/version

kitty 0.26.2

### $TERM environment variable

xterm-kitty

### Installation

Bob (https://github.com/MordechaiHadad/bob)

### How to reproduce the issue

```
nvim --clean
:lua vim.keymap.set('c', '<C-j>', 'wildmenumode() ? "<c-j>" : "<down>"', { expr = true })
:lua vim.keymap.set('c', '<C-k>', 'wildmenumode() ? "<c-k>" : "<up>"', { expr = true })
:echo "something to get back to"
```
press `:` and then try `<c-k>` to get last history item (echo above)

### Expected behavior

Expected to get the `:echo "something to get back to"` item in the command line

### Actual behavior

It prints `:<80>ku`.

**Comment by zeertzjq** [comment]
Add `replace_keycodes = false` to `opts`
