### ISSUE TITLE
nvim hangs sometimes at insert mode

### ISSUE THREAD

**Issue by agonzalezro** [neovim/neovim#2023]
Hi,

prerequisites:

- this conf: https://github.com/agonzalezro/.dot
- write something

Sometimes it hangs and doesn't allow me to write unless I hit Ctrl-C. I am just opening this issue to get some help on how to debug it to add more information. I know that at the moment it's kinda pointless, but just let me know how to test it and I will add the needed information.

**Comment by khalidchawtany** [comment]
Look at [issue 2016](https://github.com/neovim/neovim/issues/2016) && [issue 2017](https://github.com/neovim/neovim/issues/2017)

**Comment by tarruda** [comment]
@agonzalezro are you using OSX?

**Comment by agonzalezro** [comment]
@khalidchawtany indeed is kinda similar problem.

@tarruda yep, I am using OSX and I've installed neovim from the brew formula. Does it worth compiling it?

**Comment by tarruda** [comment]
> @tarruda yep, I am using OSX and I've installed neovim from the brew formula. Does it worth compiling it?

No, I only asked to confirm this is a OSX-only issue. I'm already working on a fix and will close this in favor of #2016
