### ISSUE TITLE
Invoke cb of `nvim_set_decoration_provider` over and over in visual mode

### ISSUE THREAD

**Issue by kevinhwang91** [neovim/neovim#20235]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1106-g6cc03b9c9

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ArchLinux

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

build from repo

### How to reproduce the issue

`cat mini.lua`
```lua
local api = vim.api
vim.o.cmdheight = 2
_G.cnt = 0
local ns = api.nvim_create_namespace('test')
api.nvim_set_decoration_provider(ns, {
    on_win = function(...)
        vim.schedule(function() end)
        _G.cnt = _G.cnt + 1
    end
})
api.nvim_feedkeys('v', 'n', false)
vim.defer_fn(function()
    local esc = api.nvim_replace_termcodes('<Esc>', true, false, true)
    api.nvim_feedkeys(esc, 'n', false)
    print(_G.cnt)
end, 3000)
```
1. nvim --clean +'so mini.lua'

### Expected behavior

Small enough cnt to output.

### Actual behavior

![image](https://user-images.githubusercontent.com/17562139/190867972-2eb3d2d3-297d-4228-8287-d981bdef4f69.png)

**Comment by zeertzjq** [comment]
This is similar to #4847 #14303

**Comment by kevinhwang91** [comment]
> This is similar to #4847 #14303

It's weird that the issue only exists in visual mode.

**Comment by zeertzjq** [comment]
That's because
https://github.com/neovim/neovim/blob/3c3f3e7353ba2cb9071183cd05036ca2a98d3672/src/nvim/normal.c#L1285-L1287

**Comment by kevinhwang91** [comment]
Thanks for your tip.
