### ISSUE TITLE
LSP: markdown links in hover content

### ISSUE THREAD

**Issue by jaidetree** [neovim/neovim#20246]
### Feature already in Vim?

Present in at least 7c997dbc5db145ccfa3c4d687b85168819c8b7d2

### Feature description

Looking through the stylize_markdown function used by the hover -> open_floating_preview function:

https://github.com/neovim/neovim/blob/7c997dbc5db145ccfa3c4d687b85168819c8b7d2/runtime/lua/vim/lsp/util.lua#L1185

It seems like the markdown parsing ignores markdown links. Would you be open to a PR for updating that parser to support them?

Any ramifications or other systems that this could cause harm to?

Without the parsing, links are rendered like this:

![image](https://user-images.githubusercontent.com/590297/190975546-7bc4c04a-05f1-43ba-81ed-003c144b8006.png)

I think parsing them fully so they are interactive would be nice to have. Alternatively, just displaying one url if the url and display are the same without the markup would be sufficient.

**Comment by justinmk** [comment]
> Would you be open to a PR for updating that parser to support them?

yes
 
> Any ramifications or other systems that this could cause harm to?

nope, just hasn't captured anyone's interest until now :)

**Comment by LimbicSys** [comment]
This plug may be helpful, which can conceal links and onther markdown elements.
https://github.com/preservim/vim-markdown

**Comment by glepnir** [comment]
maybe can use treesitter .

**Comment by mikehaertl** [comment]
If implemented it would also be nice to have an option to conceal the URL part. Especially with Javadoc the lengthy `jdt:/` links are all over the place and make the text quite noisy and hard to read.

So far I've used a workaround that I found [here](https://github.com/mfussenegger/nvim-jdtls/discussions/124#discussioncomment-1968776):

> You could add some conceal definitions. For example create a file `lsp_markdown.vim` within `.config/nvim/after/syntax/`:
> 
> ```viml
> syn clear markdownLink
> syn region markdownLink matchgroup=markdownLinkDelimiter start="(" end=")" contains=markdownUrl,mkJdtLink keepend contained
> syntax match mkJdtLink /jdt:\/\/.*/ containedin=markdownLink conceal
> ```
>

**Comment by SyedFasiuddin** [comment]
Instead of doing conceal we can have something like this that I have described here. https://github.com/rust-lang/rust-analyzer/issues/14086#issue-1570854619

**Comment by justinmk** [comment]
Fixed by #25073
