### ISSUE TITLE
range_formatting initially not sending the correct line range

### ISSUE THREAD

**Issue by deto** [neovim/neovim#20245]
### Neovim version (nvim -v)

0.7.2 release

### Language server name/version

pylsp 1.5.0

### Operating system/version

Ubuntu 20.04

### Steps to reproduce using "nvim -u minimal_init.lua"

Add the following function to the on_attach block:

```
    vim.keymap.set("v", "gq", vim.lsp.buf.range_formatting, {buffer = true})
```

Also, I changed line 67 to set language server to `pylsp` and I removed the command for pyright on the line after it.

### Expected behavior

Using the following test python file:

```
# Test program

x = [
    'a'     ,
    'b'
]

print('ok')
```

Enter into visual mode and select lines 3-6 (the list definition.  Then hit `gq` which triggers range_formatting.  Expected that this range would be sent to the language server and the lines would be formatted (removing all the extra space before the comma).

### Actual behavior

However, instead nothing happens.  When I check the LspLog I see this:

```
[TRACE][2022-09-19 06:33:40] ...lsp/handlers.lua:488	"default_handler"	"textDocument/rangeFormatting"	{
  ctx = '{\n  bufnr = 1,\n  client_id = 1,\n  method = "textDocument/rangeFormatting",\n  params = {\n    options = {\n      insertSpaces = true,\n      tabSize = 4\n    },\n    range = {\n      end = {\n        character = 1,\n        line = -1\n      },\n      start = {\n        character = 0,\n        line = -1\n      }\n    },\n    textDocument = {\n      uri = "file:///home/ubuntu/test.py"\n    }\n  }\n}',
  result = {}
}
```

The range being sent to the language server is just line -1 to line -1.  (Doesn't appear to be a language server issue as I see the same issue with the R language server)

Oddly, if I try a few more times with the file open, eventually it starts working.

### Log file (captured right after the issue occurred)

https://gist.github.com/deto/6a592aa8f6bffa3fca879d6ec45d4786

**Comment by glepnir** [comment]
can you try the nightly version ?

**Comment by deto** [comment]
Ran it now with `v0.8.0-dev-1117-g7bd4c8e8e` and got the same behavior.  Relevant line in the log (sorry for bad formatting, but I just copied it directly):

```
[TRACE][2022-09-19 07:07:51] ...lsp/handlers.lua:519	"default_handler"	"textDocument/rangeFormatting"	{
  ctx = '{\n  bufnr = 1,\n  client_id = 1,\n  method = "textDocument/rangeFormatting",\n  params = {\n    options = {\n      insertSpaces = true,\n      tabSize = 4\n    },\n    range = {\n      ["end"] = {\n        character = 1,\n        line = -1\n      },\n      start = {\n        character = 0,\n        line = -1\n      }\n    },\n    textDocument = {\n      uri = "file:///home/ubuntu/test.py"\n    }\n  }\n}',
  result = {}
}
```

Also saw the message about range_formatting being deprecated when running in this build.

**Comment by glepnir** [comment]
yup in head the version use `vim.lsp.buf.format` instead .

**Comment by mfussenegger** [comment]
`range_formatting` uses the previous selection, you'd have to exit visual mode to update the marks:

```
vim.keymap.set("v", "gq", '<ESC><Cmd>lua vim.lsp.buf.range_formatting()<CR>', {buffer = true})
```

`vim.lsp.format` (in master/0.8-dev) detects if it is in visual mode and uses the range formatting if so.
