### ISSUE TITLE
cmdheight=0 will cause display error in NVIM v0.8.0-dev-1117-g7bd4c8e8e

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#20247]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1117-g7bd4c8e8e

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch linux

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

aur

### How to reproduce the issue

`nvim test`
`:w<CR>`
![image](https://user-images.githubusercontent.com/97107165/190992677-bd2c6e38-e7b2-46df-893e-0ed08418b31f.png)

if we use the cmdline, the input will be under the statusline.
![image](https://user-images.githubusercontent.com/97107165/190993297-6b5fcd21-5d8a-4cce-bc06-22c60ac1e08d.png)

### Expected behavior

the statusline should move temporarily up to show the cmdline

### Actual behavior

it just not moving up, I don't know wether it's neovim's issue or the lualine's issue.

**Comment by clason** [comment]
This is by design; the commandline now _replaces_ the statusline on master.

**Comment by clason** [comment]
Avoid _what_? If you don't want to remove the command line (and message) space, don't set `cmdheight=0`?

**Comment by Shougo** [comment]
If it is design, replace the statusline is OK.
But the redraw seems broken.
Because the input cannot be displayed.

**Comment by Shougo** [comment]
Please test #20249

**Comment by Shougo** [comment]
Please create the minimal init.vim and report again.
I will test it.

**Comment by aj3423** [comment]
Same problem, it crashes with SIGSEGV at startup, my init.vim only contains 1 line:
`vim.opt.cmdheight = 0`

It doesn't crash if not set `cmdheight` or set it to other values than 0. 

Tested with latest *NVIM v0.8.0-dev-1132-g37a71d1f2*.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/issues/20247#issuecomment-1251716346

**Comment by zeertzjq** [comment]
This has been fixed by #20249
The cmdline redraw problem is tracked in #20281
