### ISSUE TITLE
pyright lsp: ^@ inserted where there should presumably be a newline

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#20250]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Kubuntu 22.04 LTS

### Terminal name/version

Konsole 21.12.3

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

1. `nvim -nu minimal_init.lua`
  `minimal_init.lua` is from [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/):
    https://raw.githubusercontent.com/neovim/nvim-lspconfig/master/test/minimal_init.lua
   `pyright` is already configured
2. Load a new empty Python file (e.g., `:e file.py`)
3.  Enter the following:
```python
class C:
    def __st
```
4. While still in insert mode, press `<c-x><c-o>` for auto completion

### Expected behavior

I expected a newline and proper indentation (instead of `^@` shown in _actual behavior_ below). 

```python
class C:  
    def __str__(self) -> str:
        pass
```

### Actual behavior

The following shows the full file with the completed text. There is a `^@` string inserted where there should presumably be a newline.

```python
class C:  
    def __str__(self) -> str:^@    pass
```

### Additional information

I originally created an [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) issue with this problem:
  https://github.com/neovim/nvim-lspconfig/issues/2028

**Comment by clason** [comment]
This looks like a snippet, which Neovim cannot expand by itself (yet). For that, you need a completion plugin plus a snippet plugin.

As there's already a PR tracking this (#16499), I'm going to close this as "duplicate".

**Comment by heygarrett** [comment]
@dstein64 Here's a snippet plugin that works omnicomplete instead of requiring a separate completion plugin:  
https://github.com/dcampos/nvim-snippy
