### ISSUE TITLE
Does not restore quickfix window from workspace

### ISSUE THREAD

**Issue by aik** [neovim/neovim#20254]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

none

### Operating system/version

Fedora 36

### Terminal name/version

xterm

### $TERM environment variable

xterm

### Installation

Fedora rpm

### How to reproduce the issue

Run `nvim`, then:
```
:copen
:mks! 1
:quit
```
`1` is a name of a file with the workspace.

Run `nvim -c so 1`, it loads 2 windows but when doing anything which outputs to a quickfix window, a new (third one) appears instead of using the existing one.

### Expected behavior

VIM does not open a new window after being started with `-c so 1`

### Actual behavior

An extra window on `make` or `git grep`, etc

**Comment by zeertzjq** [comment]
`:set sessionoptions+=options`
