### ISSUE TITLE
Show summary of lsp diagnostic information on signcolumn when a fold is closed

### ISSUE THREAD

**Issue by rwblokzijl** [neovim/neovim#20251]
### Feature description

It becomes difficult to find the relevant LSP diagnostic errors when the relevant line is within a closed fold.

Ideally, when using signcolumn, a closed fold should hold some "summary" of the diagnostic hints inside it. I think this should be the error of the highest severity.

**Comment by rwblokzijl** [comment]
This is a feature request. I couldn't find anything about the existence of such a feature.

**Comment by lewis6991** [comment]
A plugin already exists for this: https://github.com/lewis6991/foldsigns.nvim
