### ISSUE TITLE
Allow saving winfixwidth and winfixheight in session without all of sessionopts+=localoptions

### ISSUE THREAD

**Issue by cvincent** [neovim/neovim#20268]
### Feature already in Vim?

No

### Feature description

`localoptions` is the only way to save a window's `winfixwidth` and `winfixheight` settings. Unfortunately, `localoptions` also saves all local mappings, including those set up by plugins, and this basically makes `localoptions` unusable if you ever change your plugins or configuration, causing your session to break in ways that can be very difficult to debug.

**Comment by justinmk** [comment]
send this to https://github.com/vim/vim , we aren't going to add random micro-features to vim sessions.
