### ISSUE TITLE
Nvim doesn't resize itself in certain situations

### ISSUE THREAD

**Issue by mreed1** [neovim/neovim#2026]
This affects vanilla vim, so consider this a possible enhancement. This is probably easier to explain visually:

![start](https://cloud.githubusercontent.com/assets/4174345/6281332/6fa723f8-b88d-11e4-835c-1aadc73d2c57.png)

![end](https://cloud.githubusercontent.com/assets/4174345/6281342/9176f49a-b88d-11e4-96ab-bbb0eee98311.png)

I start off with two tmux panes, one on top of the other. When I close the bottom one, the top one retains its dimensions until the enter key is pressed. This doesn't happen unless the `Press ENTER...` prompt is present.

**Comment by justinmk** [comment]
*Nothing* happens if the Press ENTER prompt is displayed, so it isn't surprising that resize doesn't. We may be better off if we look for opportunities to avoid the Press ENTER prompt, rather than try to enhance it.

**Comment by Pyrohh** [comment]
Ohhh, so that's what that PR does, that should be great :)
