### ISSUE TITLE
Problem configuring Perl Provider

### ISSUE THREAD

**Issue by joshcbrown** [neovim/neovim#20275]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Ubuntu 22.04

### Terminal name/version

Gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

- run sudo cpanm -n Neovim::Ext
- enter neovim with nvim --clean and run :checkhealth

### Expected behavior

Perl-provider has no problems

### Actual behavior

The following error is printed:
  - ERROR: Command error (job=18, exit code 2): `/usr/bin/perl '-MApp::cpanminus::fatscript' -e 'my $app = App::cpanminus::script->new; $app->parse_options ("--info", "-q", "Neovim::Ext"); exit $app->doit'` (in \<my home directory\>)
    stderr: Can't locate App/cpanminus/fatscript.pm in @INC (you may need to install the App::cpanminus::fatscript module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl).BEGIN failed--compilation aborted.
  - ERROR: Failed to run: /usr/bin/perl -MApp::cpanminus::fatscript -e my $app = App::cpanminus::script->new; $app->parse_options ("--info", "-q", "Neovim::Ext"); exit $app->doit

Thanks in advance for any help!

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/15130#issuecomment-899322323

It is not clear if anyone is actually maintaining the perl client. If that's the case, perl support will be removed.

**Comment by joshcbrown** [comment]
Ah, thanks very much!

**Comment by sswam** [comment]
I got that error when I used the cpanminus package from Debian.

When I installed cpanminus using cpan, the error went away.

I suppose that the recommended install method would also work:

curl -L https://cpanmin.us | sudo perl - App::cpanminus

See here: https://metacpan.org/pod/App::cpanminus

**Comment by zachliu** [comment]
in addition to this `stderr: Can't locate...` error, i kept getting warnings about lacking of permission to write to the `/usr/local/share/perl/` in neovim's `checkhealth` and none of the suggestions worked :crying_cat_face: 
i ended up using `asdf` to install an isolated `perl` and everything is hunkydory now

**Comment by karenetheridge** [comment]
fatscript was removed in 2018. why is neovim trying to use it? Perhaps use a public api.
