### ISSUE TITLE
Error trying to use :Man or nvim as Man pager

### ISSUE THREAD

**Issue by SanchayanMaity** [neovim/neovim#20279]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1134-g71e70d0c9

### Vim (not Nvim) behaves the same?

Did not check vim

### Operating system/version

Linux

### Terminal name/version

foot version: 1.13.1 +pgo +ime +graphemes -assertions

### $TERM environment variable

tmux-256color

### Installation

Build from repo/source

### How to reproduce the issue

```
nvim --clean
:Man strftime
```

Above gives the error

```
Error detected while processing function man#open_page[43]..function man#open_page[38]..BufReadCmd Autocommands for "man://*"..function man#read_page[11]..<SNR>23_put_page:
line   12:
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'highlight_man_page' (a nil value)^@stack traceback:^@^I[string ":lua"]:1: in main chunk
```
While trying to use neovim as man pager with `nvim +Man!` gives 

```
Error detected while processing command line..function man#init_pager:
line    6:
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'highlight_man_page' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

### Expected behavior

No errors when trying to use `man` with neovim.

### Actual behavior

Errors when trying to use `man` with neovim.

**Comment by zeertzjq** [comment]
It is likely that you didn't uninstall a previous version cleanly. How did you install Nvim?

**Comment by SanchayanMaity** [comment]
> It is likely that you didn't uninstall a previous version cleanly. How did you install Nvim?

```
make distclean && make CC=clang CMAKE_BUILD_TYPE=Release
sudo make install
```

This is what I execute every time.

**Comment by zeertzjq** [comment]
Then try removing `/usr/local/share/nvim/runtime` and installing again.

**Comment by SanchayanMaity** [comment]
> Then try removing `/usr/local/share/nvim/runtime` and installing again.

Ah. That did it. Thank you.

**Comment by sluongng** [comment]
Confirmed that `rm -rf /usr/local/share/nvim/runtime` with a following `sudo make install` solved this problem for me.

Thanks!
