### ISSUE TITLE
vim.wo.foobar behaves differently from vim.opt_local.foobar when foobar is a window-local option

### ISSUE THREAD

**Issue by andrewferrier** [neovim/neovim#20271]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1109-g72e104142

### Vim (not Nvim) behaves the same?

No, Vim does not have lua-based options

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.2

### $TERM environment variable

xterm-kitty

### Installation

nvenv

### How to reproduce the issue

As I understand it, `vim.wo.foobar` is the preferred approach for users to set options in their configuration, and `vim.opt_local` is being slowly phased out/deprecated.

However, `vim.wo.foobar` seems to behave in an unusual/unhelpful way, and differently, at least with some options such as `spell` (confirmed as a window-local option by the help). I think I've managed to document some recreation steps to show the problem:

1. Create an init file called `wo-test.lua` with the following contents:

```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = { "markdown" },
    callback = function()
        print("spell option set")
        vim.opt_local.spell = true
    end,
})
```

2. Open NeoVim with `nvim --clean -u wo-test.lua somemarkdownfile.md`. Note that the spell option is set (this can be tested with `:set spell?`, `lua print(vim.wo.spell)`, or `lua print(vim.opt_local.spell:get())`). Also the `print()` diagnostic should appear in the command-line bar.

3. Switch the same window to a `netrw` buffer by typing `:e ~/` or similar. Note that the `print()` message is not emitted again. Note that the spell option is NOT set (this can be confirmed with the same commands above). This is the behaviour I would expect, and that is most helpful (it's not helpful to have `spell` be the same for all buffers in a window, as it's likely to depend on filetype).

4. Now, quit NeoVim and modify the autocmd logic like this:

```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = { "markdown" },
    callback = function()
        print("spell option set")
        vim.wo.spell = true
    end,
})
```

5. Start NeoVim again with the same command line as in step (2). Note that the spell option is set, as expected (use the same commands to check the value), and note the `print()` diagnostic is emitted.

6. Switch to a `netrw` buffer in the same way with `:e ~/`. Note that although the `print()` diagnostic is not emitted, all three of the commands for checking the `spell` option show it as set (true). This I would NOT expect, and it is not helpful - the value of the `spell` option is 'carrying through' into a different buffer in the same window, which is not helpful, and is not consistent with the way `opt_local` works.

It would seem, doing further testing, that `opt_local` is consistent with `setlocal` in VimL (in other words, this is how these options have always worked in the past). `vim.wo` seems to deviate from this.

### Expected behavior

`vim.wo.foobar` is consistent with `vim.opt_local.foobar`

### Actual behavior

As described above in repro steps.

**Comment by clason** [comment]
No, that is not correct: `vim.wo` (intentionally) behaves like `:set` for window options, not `:setlocal`. This is an error in the documentation that will be fixed in https://github.com/neovim/neovim/pull/20256.

**Comment by andrewferrier** [comment]
@clason so is there a Lua equivalent to `setlocal` for a window-local option? I mean, obviously `opt_local`, but my understanding was that the plan was eventually to remove that? I tried `vim.bo` (for spell) but that seems to be invalid.

**Comment by clason** [comment]
>  I mean, obviously opt_local, but my understanding was that the plan was eventually to remove that? 

No such plan exists (yet), at least not to the extent that people should react to it. So `opt_local` is fine -- even if it were removed, it'd get ample deprecation with clear migration path first.

You can also use the API directly: `vim.api.nvim_set_option_value('spell', value, { scope = local, window = winid })`.

> I tried vim.bo (for spell) but that seems to be invalid.

Yes, because `spell` is a window option (that can be buffer-local. Yes, window options work in an unusual/unhelpful way.)

**Comment by andrewferrier** [comment]
OK, that adds up at least - I read the changed docs in #20256, and I couldn't see the `setlocal` equivalent for a window-local option - which is because there isn't one, by the sounds of things. I do think this is quite a common need, FWIW. My sample above shows (I think) why it might be desirable for `spell`, but many other options fall into this bucket I think, like `foldmethod`, `cursorcolumn`, etc.

Anyway, sounds like for now I'm good to stick with `opt_local`. Thanks for clearing that up and appreciate your patience in explaining this.

**Comment by clason** [comment]
Yes, obviously this will be supported in one way or another. _What_ the best way is is less obvious, so we want to take a bit of time working this out after 0.8 is released (instead of adding something now only to realize it needs to be changed later).

**Comment by andrewferrier** [comment]
Makes sense! I thought I'd stumbled onto some subtle bug but obviously it's a "known" issue, which is reassuring. Again, thanks for clearing it up and for all your hard work on NeoVim.
