### ISSUE TITLE
cmdheight=0: command line is invisible after :redraw

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#20281]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1137-g7fc5f6605

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. `nvim --clean`
2.
```vim
:autocmd CmdlineChanged * lua vim.schedule(function() vim.cmd('redraw') end)
:set cmdheight=0
```
3. Type an Ex command

### Expected behavior

Command line is visible

### Actual behavior

Command line is hidden

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/ex_getln.c b/src/nvim/ex_getln.c
index 2a91e9c67..fe79e2b01 100644
--- a/src/nvim/ex_getln.c
+++ b/src/nvim/ex_getln.c
@@ -3695,7 +3695,7 @@ void compute_cmdrow(void)
     cmdline_row = wp->w_winrow + wp->w_height
                   + wp->w_hsep_height + wp->w_status_height + global_stl_height();
   }
-  if (cmdline_row == Rows) {
+  if (cmdline_row == Rows && p_ch > 0) {
     cmdline_row--;
   }
   lines_left = cmdline_row;
```

**Comment by Shougo** [comment]
I will test it later.

**Comment by Shougo** [comment]
OK.  It has some flicker problem but it is very good.

**Comment by Shougo** [comment]
@zeertzjq Can you create the PR?

**Comment by zeertzjq** [comment]
I'm not sure if this is the correct solution.

**Comment by zeertzjq** [comment]
Seems fixed now, although there is some flicker.

**Comment by Shougo** [comment]
Confirmed.
