### ISSUE TITLE
tabline is not refreshed after nvim_win_close()

### ISSUE THREAD

**Issue by antoinemadec** [neovim/neovim#20285]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1137-g7fc5f6605

### Vim (not Nvim) behaves the same?

Vim does not offer the feature to close a window in a different tab

### Operating system/version

Manjaro Linux 22.0

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

xterm-256color

### Installation

build from repo: make CMAKE_BUILD_TYPE=Release -j4

### How to reproduce the issue

nvim --clean
:e a
:tabe b
:lua vim.api.nvim_win_close(1000, true)

### Expected behavior

The tabline should be updated and disappear after the window in the tab 'a' is closed.

### Actual behavior

The tabline still shows 2 tabs: 'a' and 'b' and considers that it is still on tab 'b'.
This behavior is stuck until:

- we create a new tab (with :tabe for instance)
- we run :mode (make tabline disappear, but a blank line is still present at the top of the window)

The problem does not appear if we close the window of the current tab.
It only appears if we close the last window of a tab that we are not on.

**Comment by zeertzjq** [comment]
This also applies to `nvim_win_hide`.

**Comment by zeertzjq** [comment]
This also happens with this sequence of commands:
```vim
set nohidden
edit Xa
split Xb
tab split
new
autocmd WinClosed * ++once tabprev | bwipe!
close
```

Vim refuses to wipe the buffer in this case. Not sure why.
