### ISSUE TITLE
Regression from vi/vim for H/M/L keys

### ISSUE THREAD

**Issue by snyball** [neovim/neovim#20296]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no, 9.0

### Operating system/version

Arch Linux 5.19.9

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

system package manager

### How to reproduce the issue

`nvim --clean`
`:edit multiline-with-indentation.txt`
`C-D`
`C-D`
move to line with indentation >0
`zz`
`L`
`0`
`M`

### Expected behavior

Cursor should be at soft-bol `^`, like in Vim and Vi.

### Actual behavior

Cursor follows column rule, like movement with `j` / `k`, so ends up at hard-bol.

**Comment by zeertzjq** [comment]
`:set startofline`
