### ISSUE TITLE
Strange characters being displayed when typing in Insert Mode

### ISSUE THREAD

**Issue by dboshardy** [neovim/neovim#2030]
Whenever typing in insert mode, after either pressing a key to enter insert mode (a, o, i, etc.), or, while in insert mode, pressing <Space> and then any character, these strange characters show up that look like a box with numbers in it followed by '112'.  [See the screenshot here.](http://i.imgur.com/r5ADlc1.png)  The first line is after I typed it and minimized the window, then opened it back up and typed in the second line and printscreened.  Note, the first line looked like the second until minimizing.

This issue started showing up very recently when my colorscheme highlighting broke as well. It was fixed by adding ```let TERM = "xterm-256color" ``` to .nvimrc as suggested in the other threads. I've also been able to replicate this issue after removing all plugins.

**Comment by Pyrohh** [comment]
Is this using the latest release? #2025 was merged very recently, which apparently fixed #2017 (I'm not sure if it's the same issue you're experiencing).

**Comment by justinmk** [comment]
Assuming this was fixed by https://github.com/neovim/neovim/pull/2025. Please try latest, and reopen if not fixed (please report `:version`).

**Comment by dboshardy** [comment]
Unless it was done a few hours before I posted, I'm using latest from the repo.

**Comment by Pyrohh** [comment]
IIRC it was done a few hours after you posted. You can check the revision of your build using `nvim --version`; it should be on the top line (along with other stuff).
