### ISSUE TITLE
control the visible cursor with getchar(), vim.ui_attach+ext_cmdline, etc

### ISSUE THREAD

**Issue by folke** [neovim/neovim#20309]
### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

bob

### How to reproduce the issue

I'm building a custom cmdline using `vim.ui_attach`.

Through the API, we get enough information to show a fake cursor at the command prompt, but the original cursor also stays on the screen where it was before entering the cmdline.

See screenshot below.

![image](https://user-images.githubusercontent.com/292349/192063080-ad5525c1-326a-4a32-85c4-726afb550d58.png)

### Expected behavior

When implementing ext_cmdline, the cursor should be hidden between `cmdline_show` and `cmdline_hide` events.

### Actual behavior

The cursor is still there

**Comment by folke** [comment]
Same thing when calling `vim.fn.getchar`

**Comment by folke** [comment]
Its actually possible to use `nvim_win_set_cursor` and `nvim_set_current_win` for the **cmdline** istead of the fake cursor.

Unfortunately that doesn't work when in a `confirm`, `input()`, `getchar()` and others where the ui is **blocking**.

**Comment by bfredl** [comment]
Nah, we need API to control the screen cursor position explicitly before a blocking wait, for the 0.9 cycle.
