### ISSUE TITLE
No intro screen on Konsole or GNOME Terminal

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#20302]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

No (8.2.4919)

### Operating system/version

Kubuntu 22.04

### Terminal name/version

Konsole 21.12.3

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

nvim --clean

### Expected behavior

The intro screen would be displayed

### Actual behavior

No intro screen is displayed

### Additional information

The intro screen also does not display on GNOME Terminal 3.44.0. It does display on xterm 372 and kitty 0.21.2.

**Comment by zeertzjq** [comment]
Cannot reproduce with Konsole 22.08.1 or GNOME Terminal 3.44.1 on Arch Linux

**Comment by dstein64** [comment]
Thanks for running further tests @zeertzjq!

Based on your findings, I ran additional experiments on a MacBook Pro Mid 2015 with macOS Monterey 12.6.

On that system, I could reproduce the issue with Terminal.app Version 2.12.7 (445) and XTerm 373, but not with iTerm2 3.4.16.

xterm provides another example where the reproducibility of the issue is system dependent rather than terminal application dependent.

**Comment by dstein64** [comment]
The issue reported here sounds related to https://github.com/neovim/neovim/issues/3416. I'll close this as a duplicate of that issue.

**Comment by dstein64** [comment]
> "Cannot reproduce with Konsole 22.08.1 or GNOME Terminal 3.44.1 on Arch Linux"

@zeertzjq, did you have a dark background in your terminal? A [comment](https://github.com/neovim/neovim/issues/3416#issuecomment-1216208816) in https://github.com/neovim/neovim/issues/3416 suggests that the background color affects whether the issue occurs. I just confirmed on Terminal.app that if I change to a dark background I no longer encounter the issue.

**Comment by zeertzjq** [comment]
Yes. Changing the `'background'` option causes a redraw, so the intro screen disappears.

**Comment by justinmk** [comment]
> Changing the `'background'` option causes a redraw, so the intro screen disappears.

I wonder if we can add a special case to redo `intro_message()` after a redraw, until CTRL-L or buffer / window change.
