### ISSUE TITLE
Neovim sends negative numbers for cursor grid pos when cmdheight=0

### ISSUE THREAD

**Issue by ad-chaos** [neovim/neovim#20306]
### Neovim version (nvim -v)

This is the commit from which it started `708bd686516b420c2b65f4bc4d2c58fe43fb945e` 

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

macOS 12.5

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

built from source

### How to reproduce the issue

download neovide
then run `neovide --nofork --multigrid -- --clean -u t.vim file`
(note: `--multigrid` is required and `--nofork` so that you can see the panic message that gets printed to stdout)
where `t.vim` has
```vim
set cmdheight=0
```
now press `/p`  and neovide will crash saying `Could not parse event from neovim: invalid u64 format -1`

### Expected behavior

neovide should not crash

### Actual behavior

neovide crashed because neovim sent over the following rpc
`IntoIter([String(Utf8String { s: Ok("grid_cursor_goto") }), Array([Integer(PosInt(3)), Integer(NegInt(-1)), Integer(PosInt(2))])`
which translates to
`['grid_cursor_goto', [3, -1, 2]],`

So, neovim sends a negative row number when `cmdheight=0`, I couldn't track down where exactly why exactly this happens though.

**Comment by mawkler** [comment]
I'm having a very similar issue.

**To reproduce:**

1. `neovide --nofork -- --clean -c 'set cmdheight=0' -c "=vim.keymap.set('n', '/', 'ms/', { silent = true })"`
2. Press `/p`
3. Neovide crashes with the (logged) message: `Could not parse event from neovim: invalid u64 format -1`

**Neovim version**: v0.10.0-dev-735+g8fe9f41f7
**Neovide version**: 0.10.4

I can't reproduce the original issue though so it doesn't seem to be the exact same bug.

**Comment by fredizzimo** [comment]
@bfredl I think this issue should be re-opened. The use case @mawkler reported still sends an invalid event 100% of the time. These are the relevant logs from Neovide
```
ERROR [neovide::error_handling] Could not parse event from neovim: invalid event format for event 'grid_cursor_goto' -
 [Integer(PosInt(3)), Integer(NegInt(-1)), Integer(PosInt(0))] - invalid u64 format -1
Neovide panicked with the message 'Could not parse event from neovim: invalid event format for event 'grid_cursor_goto
' - [Integer(PosInt(3)), Integer(NegInt(-1)), Integer(PosInt(0))] - invalid u64 format -1'. (File: src/error_handling.
```

So, it sends `grid_cursor_goto` with `grid: 2, row: -1, column: 0`, the row is negative, which it shouldn't be.
