### ISSUE TITLE
Turn `set mouse=a` on by default

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#20324]
### Feature already in Vim?

No

### Feature description

I propose to turn `set mouse=a` on by default.
- The wheel scroll behavior (scrolling the screen by a line at a time, as opposed to scrolling the cursor which is the current default) would be more consistent with modern text editor applications (no app I'm aware of scrolls the cursor using the wheel by default except Vim and Emacs).
- Clicking to move the cursor would work by default.

**Comment by zeertzjq** [comment]
The default for `'mouse'` is set to `nvi` in #19290. Does it have to be `a`?

**Comment by justinmk** [comment]
As mentioned, 'mouse' is already enabled in 0.8. It is intentionally not "a" however.
