### ISSUE TITLE
Event `mode_change` does not report terminal mode

### ISSUE THREAD

**Issue by jgehrig** [neovim/neovim#20325]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+1299-g773516365-dirty

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Gentoo

### Terminal name/version

Konsole 21.08.3

### $TERM environment variable

xterm-256color

### Installation

Portage (9999 Nightly)

### How to reproduce the issue

[Running modified nvim-qt frontend to demonstrate issue]

The following patch has been applied to instrument `mode_change` events:
```patch
diff --git a/src/gui/shell.cpp b/src/gui/shell.cpp
index c91097b..1a469d1 100644
--- a/src/gui/shell.cpp
+++ b/src/gui/shell.cpp
@@ -566,6 +566,7 @@ void Shell::handleRedraw(const QByteArray& name, const QVariantList& opargs)
        } else if (name == "mouse_off"){
                handleMouse(false);
        } else if (name == "mode_change"){
+               qDebug() << opargs;
                handleModeChange(opargs);
        } else if (name == "set_title"){
                handleSetTitle(opargs);

```

1. Open GUI frontend: `nvim-qt -- -u NORC`
2. Enter terminal mode with `:terminal`
3. Notice no mode_change is reported for terminal mode.

Here is a trace of all mode_change events:
```
(QVariant(QByteArray, "normal"), QVariant(qulonglong, 0))
(QVariant(QByteArray, "normal"), QVariant(qulonglong, 0))
(QVariant(QByteArray, "normal"), QVariant(qulonglong, 0)) // Occurs during startup
(QVariant(QByteArray, "cmdline_normal"), QVariant(qulonglong, 4)) // : - Command mode entered
(QVariant(QByteArray, "normal"), QVariant(qulonglong, 0)) // :terminal command completes
```

### Expected behavior

There should be a `mode_change` when the user enters and exits terminal mode.

### Actual behavior

There is no `mode_change` event, and the frontend cannot detect when the user is in terminal mode.

Related issues:
https://github.com/equalsraf/neovim-qt/issues/999
https://github.com/neovim/neovim/issues/19265

**Comment by zeertzjq** [comment]
Also related: #3681, #20176

**Comment by jgehrig** [comment]
Also related:
https://github.com/equalsraf/neovim-qt/issues/728
https://github.com/equalsraf/neovim-qt/issues/259
