### ISSUE TITLE
Option to keep visual selection unless the user explicitly exits visual mode

### ISSUE THREAD

**Issue by amarakon** [neovim/neovim#20328]
### Feature already in Vim?

No

### Feature description

Whenever pressing a keybinding in visual mode, like `y` to yank, it exits visual mode and returns to where the caret originally was. Sometimes, I want to do multiple keybindings. It would be cool if there was an option to keep visual mode unless the user explicitly exits visual mode. I know I can go back to the previous selection with `gv`, but I would prefer if it just did not remove the selection to begin with.

**Comment by justinmk** [comment]
this falls under a generic `NormalCmd` event, where you can do the `gv` then

**Comment by amarakon** [comment]
But then that will first deselect, change the cursor position, then select again. Compared to what I am requesting which is just do not deselect in the first place. If I use the `NormalCmd` event, I will probably notice this and it will look weird.

**Comment by amarakon** [comment]
Also, where in the codebase is this implemented so I can comment those lines out, make a `.diff` file and use it for my personal build of Neovim if this feature is not coming to Neovim. Is it done by the `end_visual_mode` function?
