### ISSUE TITLE
cmdheight=0: `winbar` with `mode()` is not updating correctly

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#20336]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1146-g7a70e9587

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Linux Mint 21

### Terminal name/version

Alacritty 0.12.0-dev

### $TERM environment variable

alacritty

### Installation

Prebuilt nightly from repo

### How to reproduce the issue

1. `nvim --clean ~/.config/nvim/init.lua`
2. 
```viml
:set statusline=%!mode()
:set winbar=%!mode()
:set cmdheight=0
```
3. Type an Ex command

### Expected behavior

The `winbar` should display `c` (for command mode).

### Actual behavior

The `winbar` will instead display `n` (for normal mode) or `v` (if a visual selection is in effect).

Note, if `set cmdheight=1` is in effect and an Ex command is entered, then both the `winbar` and `statusline` are correctly updated with `c` mode indicator. This is the desired and correct behaviour.

**Comment by zeertzjq** [comment]
Related: #8461
