### ISSUE TITLE
End of buffer not redrawn when deleting last line

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#20332]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1160-gb0fcdf9f0

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.3

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean`
2. Type `ifoo<Esc>yypdd`

### Expected behavior

One line of `foo` is shown

### Actual behavior

Two lines of `foo` is shown

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/drawscreen.c b/src/nvim/drawscreen.c
index c95f3f355..30cb06499 100644
--- a/src/nvim/drawscreen.c
+++ b/src/nvim/drawscreen.c
@@ -1965,7 +1965,7 @@ win_update_start:
     if (mid_end >= row) {
       lastline = MIN(lastline, mid_start);
     }
-    if (mod_bot > buf->b_ml.ml_line_count + 1) {
+    if (mod_bot > buf->b_ml.ml_line_count) {
       lastline = 0;
     }
 
```

**Comment by zeertzjq** [comment]
Removing this `+ 1` is an easy way to fix this problem:
```diff
diff --git a/src/nvim/drawscreen.c b/src/nvim/drawscreen.c
index c95f3f355..30cb06499 100644
--- a/src/nvim/drawscreen.c
+++ b/src/nvim/drawscreen.c
@@ -1965,7 +1965,7 @@ win_update_start:
     if (mid_end >= row) {
       lastline = MIN(lastline, mid_start);
     }
-    if (mod_bot > buf->b_ml.ml_line_count + 1) {
+    if (mod_bot > buf->b_ml.ml_line_count) {
       lastline = 0;
     }
 
```

But this sounds like a hack.

**Comment by zeertzjq** [comment]
A virtual line at the end of buffer is also drawn twice:
```vim
:lua vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace('ns'), vim.api.nvim_buf_line_count(0), 0, { virt_lines = {{{ 'xyz', 'ErrorMsg' }}}, virt_lines_above = true } )
```

**Comment by bfredl** [comment]
> Removing this + 1 is an easy way to fix this problem

Let's do this for now. This will need more work during the 0.9 cycle anyway (like actual tests for redraw perf, which I plan to work on).
