### ISSUE TITLE
Cannot change file type in neovim 0.8 nightly

### ISSUE THREAD

**Issue by medwatt** [neovim/neovim#20333]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1152-g14610332b

### Vim (not Nvim) behaves the same?

I didn't check.

### Operating system/version

Arch Linux

### Terminal name/version

Kitty

### $TERM environment variable

xterm-256color

### Installation

yay -S neovim-nightly-bin

### How to reproduce the issue

I upgraded today from neovim stable 0.7.2 to the latest nightly version (NVIM v0.8.0-dev-1152-g14610332b). I noticed that autocommands that change the filetype of already recognized filetyples like markdown does not work.

Add the following to your `init.vim`.

```lua
local filetypes = vim.api.nvim_create_augroup("NewFileTypes", {clear = true})
vim.api.nvim_create_autocmd({"BufNewFile", "BufFilePre", "BufRead"}, {
    pattern = "*.md",
    command = "set filetype=markdown.pandoc",
    group = filetypes,
})
```

### Expected behavior

When a `.md` file opens, the filetype should change from `markdown` to `markdown.pandoc`. This doesn't work. The filetype remains `markdown`.

### Actual behavior

When a `.md` file opens, the filetype remains `markdown`.

**Comment by justinmk** [comment]
works for me on 8317b9199edc

steps:

```
nvim --clean
:edit foo.md
:set ft?   " shows   filetype=markdown.pandoc
```

**Comment by zeertzjq** [comment]
Works with `-S`, not with `-u`.

**Comment by medwatt** [comment]
> works for me on [8317b91](https://github.com/neovim/neovim/commit/8317b9199edc6936fec829f4908f9c74dc874ce4). Did you try `nvim --clean`, else check your plugins or other settings.
> 
> Steps I tested:
> 
> ```
> nvim --clean
> :source test.lua
> :edit foo.md
> :set ft?   " shows   filetype=markdown.pandoc
> ```

Why so quick to close the issue?

**Comment by clason** [comment]
The "correct" way to add user filetypes is `vim.filetype.add`, but if this also affects filetype plugins, this should indeed be fixed.
