### ISSUE TITLE
need a way to get the path of a lua script inside a plugin

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#20340]
### Feature already in Vim?

no

### Feature description

i worte a plugin that have some data files need to be accessed by the plugin itself, and i failed to find a reasonable way to get this plugin's root directory.

i have tried these ways, but none of them works as expected.
* `debug.getinfo(2, "S").source`
* `vim.fn.expand('<sfile>')`

**Comment by haolian9** [comment]
i asked this on [neovim#matrix](https://matrix.to/#/!JAfPjWAdLCtgeCAwnS:matrix.org/$1664045492168634YfJyW:matrix.org?via=matrix.org&via=libera.chat&via=gitter.im), from the replies i got, it seems this should be a case worth for an issue.

**Comment by bfredl** [comment]
`debug.getinfo(1, "S").source` (with 1 not 2) works for me. It might break if you use a bytecode cache like impatient tho.

For your general use case, there is also `nvim_get_runtime_file("mydir/my_special.file", false)` if the file path+name within the plugin rtp dir is unique enough.

**Comment by haolian9** [comment]
wow, thanks a lot!
i'm sorry to open a question here, the `2` version i just copied from stackoverflow without any consideration.

then i think this issue is not a problem really

**Comment by haolian9** [comment]
i found another way: https://github.com/sunjon/stylish.nvim/blob/main/plugin/init.lua; of course, i can call `expand('<sfile>')` in a vimscript instead of a lua file.
