### ISSUE TITLE
Checking has(python3) before setting python3_host_prog breaks python provider 

### ISSUE THREAD

**Issue by hwalinga** [neovim/neovim#20358]
### Neovim version (nvim -v)

v0.8.0-dev-1176-g9a5ac0650-dirty

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

CentOS Linux release 7.9.2009 (Core)

### Terminal name/version

rxvt-unicode (urxvt) v9.22 - released: 2016-01-23

### $TERM environment variable

screen-256color

### Installation

brew install --HEAD neovim

### How to reproduce the issue

```
nvim --clean
:echo has('python3')
:let g:python3_host_prog = '/usr/bin/python3'
:py3 import this
```

This result in an error: E319 "No python3 provider found". However skipping the check `has('python3')` results in the expected behavior, and you get the zen of Python. (The python3 provider works.)

### Expected behavior

It shouldn't matter if `has('python3')` has been called already before setting the `g:python3_host_prog`. That check should not break the ability to set the python3 provider program.

### Actual behavior

Now calling `has('python3')` before setting `g:python3_host_prog` breaks the python3 provider interface.

**Comment by Shougo** [comment]
Hm.... I don't reproduce the problem and I have checked the code.
The error message is from `eval_call_provider`.  But `has()` calls `eval_has_provider()`.
So the message should not be displayed.

Please test the latest neovim.

**Comment by Shougo** [comment]
Ah, I get it.

I think it is not the bug.
`has('python3')` load the Python3 interface so you need to set `g:python3_host_prog` before call `has('python3')`.

Please see the documentation.

```
						*g:python3_host_prog*
Command to start Python 3 (executable, not directory). Setting this makes
startup faster. Useful for working with virtualenvs. Must be set before any
check for has("python3").  >
    let g:python3_host_prog = '/path/to/python3'
<
```
