### ISSUE TITLE
Pressing ESC need one second to switch mode in tmux or screen

### ISSUE THREAD

**Issue by bigeagle** [neovim/neovim#2035]
Hi,
With version c48f835, when nvim runs inside tmux or screen, pressing `ESC` needs more than one second to switch mode. If you type `ESC` and press a key quickly, there appears some latin-1 characters in ther terminal. For example, when in insert mode, and i wanna switch to normal mode and switch back, so i type `esc i`, then an `é` was inserted. 

Cheers,
Justin

**Comment by bigeagle** [comment]
By setting `set -sg escape-time 0` in `.tmux.conf` can work around this problem.

**Comment by tarruda** [comment]
@bigeagle what `escape-time` value were you using before?

**Comment by bigeagle** [comment]
It's the default value, I'm not sure but I believe it's near 1 second.

**Comment by bigeagle** [comment]
The default value is 500 milliseconds

**Comment by tarruda** [comment]
Nvim now uses libtermkey for parsing keys, that means alt key combinations are detected by default. So, if you have a 500 ms escape time and press esc+i, tmux will immediately send ^[i which is interpreted by libtermkey as alt+i.

Vim does not detect alt combinations in terminals by default([source](http://vim.wikia.com/wiki/Get_Alt_key_to_work_in_terminal)), so when it receives ^[i which doesn't match any terminfo key sequence, it will parse as the keys esc and i separately.

If you want to avoid this kind of problem, use a low `escape-time` value(I dont recommend 0), personally I use 10 milliseconds.

**Comment by bigeagle** [comment]
Older versions without libtermkey works, there is a delay of mode switching but key sequence is still right (esc i would not be alt-i).  Maybe we need a patch for libtermkey?

Setting `escape-time` is fine but at those who use default conf would be confused.

Cheers,

**Comment by tarruda** [comment]
> Maybe we need a patch for libtermkey?

libtermkey is working correctly, esc+i is just how most terminals represent alt + i. The difference is that alt is now recognized automatically.(The old method doesn't work anymore, you cant use `set <a-i> ^[i` for example).

It would be good if the library had the option to disable alt recognition though(cc @leonerd)

**Comment by mxaddict** [comment]
I had a similar issue with this and I had a really hard time finding this issue that explained what was the cause and the FIX, I would suggest we add this as a known issue somewhere easy to find? maybe readme? or wiki?

NOT for me (I already fixed it of-course), but I think it would help future tmux + vim users that switch to NVIM :smiling_imp:

**Comment by justinmk** [comment]
@mxaddict Added to list of sanity checks https://github.com/neovim/neovim/issues/1202

**Comment by mxaddict** [comment]
Nice :+1:

**Comment by justincampbell** [comment]
I ran into this, and just assumed it was a bug in neovim since it started happening right after upgrading. I had switched backed to vanilla Vim, thinking I would try NeoVim again after this is fixed.

Then, @iamjarvo pointed me to this issue. I'm not sure how I would have found this otherwise, including buried in a README or elsewhere. Maybe a post-install message?

**Comment by philix** [comment]
I ran into this. I press ESC more than I should (paranoid), so everything seemed broken to me.

**Comment by petRUShka** [comment]
Confirm problem with latest git-version of neovim

**Comment by fwalch** [comment]
FWIW, this is listed on the [Troubleshooting page](https://github.com/neovim/neovim/wiki/Troubleshooting#pressing-esc-when-running-nvim-in-tmux-inserts-characters).

**Comment by goerz** [comment]
[Are there any potential drawbacks of the `escape-time 0` tmux setting?](http://superuser.com/questions/942677/consequences-of-escape-time-0-tmux-setting)

**Comment by justinmk** [comment]
This is covered by https://github.com/neovim/neovim/issues/1202. Other than that, this is not actionable unless we change our input logic. That's a larger discussion that is covered by other issues.

**Comment by justinmk** [comment]
tmux is now checked by `:CheckHealth`.

**Comment by fiesh** [comment]
I think setting the escape-time is a workaround, but a buggy one at best.  It can (and does) happen that both the escape key and the following key are sent in the same IP packet.

Also, I sometimes have the escape-not-recognized issue when working locally, without tmux.  Is this related to this or an entirely different issue?

Thanks for the great work!

**Comment by leonerd** [comment]
> It can (and does) happen that both the escape key and the following key are sent in the same IP packet.

It's exactly that sort of timing-related issue that I hope to fix by doing terminal keyboard stuff better. Currently we don't *quite* have the architecture in neovim to support that, but it's definitely on my list of things to get working better. It *can* be done without timing information, provided the application and the terminal can both support it.

**Comment by justinmk** [comment]
For anyone finding this issue in the future, see the FAQ: 

https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed

**Comment by fiesh** [comment]
Is there a ticket that remains open until the problem is actually fixed per what @leonerd said?

**Comment by justinmk** [comment]
No. That requires advanced terminal features.

**Comment by fiesh** [comment]
Sure, but this means the bug that even on local terminal sessions, escape is sometimes ignored, just remains?

**Comment by justinmk** [comment]
I don't know what bug you're talking about.

**Comment by fiesh** [comment]
OK, thanks, I'll keep that in mind!

**Comment by mjkelly** [comment]
@justinmk Is it worth mentioning in the FAQ that you can also use `^C` to get out of insert mode? It's not a fix, but it seems to avoid the issue fairly well.

**Comment by justinmk** [comment]
@mjkelly CTRL-C is different than ESC, e.g. it cancels mappings and autocmds. Why not set the tmux `escape-time` option as mentioned?

**Comment by mjkelly** [comment]
@justinmk Ugh, I didn't realized it cancelled mappings and autocmds. Thanks for clarifying. (I thought it would be a nice way to avoid the tmux issue *and* the fact that the esc key is in different places on different keyboards.)

**Comment by arcseldon** [comment]
Great help, thanks.

**Comment by scoop206** [comment]
I'm running tmux 2.6 and the way to do this now appears to be
```
set-option -sg escape-time 0
```

**Comment by justinmk** [comment]
Explained in the FAQ: https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed
