### ISSUE TITLE
cmdheight=0 with split window problem

### ISSUE THREAD

**Issue by Shougo** [neovim/neovim#20367]
### Neovim version (nvim -v)

v0.8.0-dev-2635-g1d337d4e2

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Manjaro Linux

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

buil from repo

### How to reproduce the issue

```
nvim --clean
:set laststatus=0 cmdheight=0
:vsplit
:split
```

### Expected behavior

![スクリーンショット_2022-09-27_16-04-03](https://user-images.githubusercontent.com/41495/192503530-5d1268fb-fd05-4f1a-928a-3359cac72084.png)

### Actual behavior

![スクリーンショット_2022-09-27_16-03-23](https://user-images.githubusercontent.com/41495/192503446-29753c1c-67b5-4c47-9fcd-4bc329b6aa97.png)

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/window.c b/src/nvim/window.c
index 22c1b7757..5523c3df8 100644
--- a/src/nvim/window.c
+++ b/src/nvim/window.c
@@ -2239,7 +2239,7 @@ static void win_equal_rec(win_T *next_curwin, bool current, frame_T *topfr, int
       // Compute maximum number of windows vertically in this frame.
       n = frame_minheight(topfr, NOWIN);
       // add one for the bottom window if it doesn't have a statusline or separator
-      if (row + height == cmdline_row && p_ls == 0) {
+      if (row + height >= cmdline_row && p_ls == 0) {
         extra_sep = STATUS_HEIGHT;
       } else if (global_stl_height() > 0) {
         extra_sep = 1;
```
