### ISSUE TITLE
Close a tab via middle click

### ISSUE THREAD

**Issue by ObserverOfTime** [neovim/neovim#20372]
### Feature already in Vim?

Yes, Vim 9.0.0597

### Feature description

vim/vim@3bdef10dc1c836e5e5a6fdcc1c21155cbd80d798 added support for closing tabs using the middle mouse button.
That seems like a convenient feature, especially for closing background tabs.

**Comment by zeertzjq** [comment]
This conflicts with existing behavior of creating a new tabpage on double middle-click.

**Comment by badfilms** [comment]
I can tackle this, but right now there is no distinction for mouse clicks on the tab page line. Therefore, the most obvious solution seems to be to restrict all other events to the left and right mouse buttons, leaving the middle mouse button to only be used to close tabs.

**Comment by zeertzjq** [comment]
This can be implemented as a plugin as well.
