### ISSUE TITLE
`nvim_win_set_config()` reapplies `style` if it is not updated

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#20370]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1178-g1d337d4e2

### Vim (not Nvim) behaves the same?

No, Vim doesn't have Lua API

### Operating system/version

EndeavourOS Linux x86_64, 5.19.10-arch1-1

### Terminal name/version

xfce4-terminal 1.0.4 (Xfce 4.16)

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

- `nvim -u NONE`
- `:lua win_id = vim.api.nvim_open_win(0, false, {relative = 'editor', row = 10, col = 10, width = 10, height = 10, style = 'minimal'})`
- `:lua vim.api.nvim_win_set_option(win_id, 'signcolumn', 'yes')`
- `:lua vim.api.nvim_win_set_config(win_id, {width = 20})`

### Expected behavior

Sign column doesn't disappear. This is what happens if floating window is opened without setting `style = 'minimal'`.

### Actual behavior

Sign column disappears.

Demo:

https://user-images.githubusercontent.com/24854248/192528856-46c2c752-ec85-4455-8e00-c1c5f3df05c9.mp4

**Comment by zeertzjq** [comment]
Is this really a bug?

**Comment by clason** [comment]
No, it sets the _full_ window configuration as specified in the table. This is consistent with other APIs (e.g., `nvim_set_hl`) as well.

**Comment by echasnovski** [comment]
> No, it sets the _full_ window configuration as specified in the table. This is consistent with other APIs (e.g., `nvim_set_hl`) as well.

Oh, ok. I assumed that "When reconfiguring a floating window, absent option keys will not be changed." from its help means that `style` option won't be changed (i.e. reapplied) in this case.

If this is all by design, then sorry for the noise and feel free to close this.

**Comment by echasnovski** [comment]
After some further testing, there is at least some inconsistency here.

If instead of `{width = 20}` use config `{relative = 'editor', row = 5, col = 5}` then `style` is not reapplied.

Here is the demo:

https://user-images.githubusercontent.com/24854248/192557296-0a1d743e-a6b2-407b-ba38-4223229ece76.mp4

**Comment by MunifTanjim** [comment]
Talked on matrix about this. Copy-pasting some relevant messages:

@MunifTanjim:

> This is actually the culprit: https://github.com/neovim/neovim/blob/598ff4f7d17791326a5d991c1c947cce6faf1b1a/src/nvim/api/win_config.c#L225-L226
> 
> `win_set_minimal_style` sets the minimal styles (which contains `number=false`) every time `nvim_win_set_config` is called. I feel like `win_set_minimal_style` should only be called when initially creating the window. `nvim_win_set_config` is used for moving/resizing/updating-border for floating windows. But this resetting window options back to minimal style is a bit problematic.

> I didn't know that style config was optional.
>
> https://github.com/neovim/neovim/blob/598ff4f7d17791326a5d991c1c947cce6faf1b1a/runtime/doc/api.txt#L3069-L3070
> I thought "only takes one non-empty value" meant it's required 😂
>
> I still feel like it shouldn't re-apply style="minimal" tho, because of this doc: https://github.com/neovim/neovim/blob/598ff4f7d17791326a5d991c1c947cce6faf1b1a/runtime/doc/api.txt#L3138-L3139
> It says "absent option keys will not be changed". But well, it can be interpreted differently, I guess.
>
> Anyway, looks like the workaround is to pass style="" when calling nvim_win_set_config (which I figured out by looking into the implementation: https://github.com/neovim/neovim/blob/598ff4f7d17791326a5d991c1c947cce6faf1b1a/src/nvim/api/win_config.c#L745-L747). But the documentation says it must be non-empty.
>
> If we can agree on the expected behavior, I can open a PR either to fix the implementation or fix the doc.

@bfredl:

> 'minimal' needs some more work to interact correctly with the schizophrenic nature of window options anyway

> these are supposed to be strictly per-window overrides and not leak into the buffer like window options tend to do

> but yes, we should change it to be more like "apply once" in 0.10 like you expected, and hopefully fix the leak-to-normal-window issue in the same version cycle.
