### ISSUE TITLE
macos release bundled treesitter parsers built for x86 only

### ISSUE THREAD

**Issue by tsaeger** [neovim/neovim#20377]
### Neovim version (nvim -v)

0.7.2 and 0.8.0-dev-1178-g1d337d4e2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.6 (Apple M1 Pro)

### Terminal name/version

iTerm latest

### $TERM environment variable

xterm-256color

### Installation

download github release nvim-macos.tar.gz

### How to reproduce the issue

nvim -clean
:checkhealth

### Expected behavior

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for vim: ABI version 14

### Actual behavior

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - ERROR: Impossible to load parser for c: Failed to load parser: uv_dlopen: dlopen(/Users/macuser/Downloads/nvim-macos/lib/nvim/parser/c.so,        0x0001): tried: '/Users/macuser/Downloads/nvim-macos/lib/nvim/parser/c.so' (mach-o file, but is an incompatible architecture (have (x86_64), need   (arm64e)))
  - ERROR: Impossible to load parser for help: Failed to load parser: uv_dlopen: dlopen(/Users/macuser/Downloads/nvim-macos/lib/nvim/parser/help.     so, 0x0001): tried: '/Users/macuser/Downloads/nvim-macos/lib/nvim/parser/help.so' (mach-o file, but is an incompatible architecture (have           (x86_64), need (arm64e)))
  - ERROR: Impossible to load parser for lua: Failed to load parser: uv_dlopen: dlopen(/Users/macuser/Downloads/nvim-macos/lib/nvim/parser/lua.so,    0x0001): tried: '/Users/macuser/Downloads/nvim-macos/lib/nvim/parser/lua.so' (mach-o file, but is an incompatible architecture (have (x86_64),      need (arm64e)))
  - ERROR: Impossible to load parser for vim: Failed to load parser: uv_dlopen: dlopen(/Users/macuser/Downloads/nvim-macos/lib/nvim/parser/vim.so,    0x0001): tried: '/Users/macuser/Downloads/nvim-macos/lib/nvim/parser/vim.so' (mach-o file, but is an incompatible architecture (have (x86_64),      need (arm64e)))

**Comment by clason** [comment]
@carlocab how hard is it to build these universal, too?

**Comment by carlocab** [comment]
Shouldn't be hard -- the `c.so` parser should have been universal when I first worked on the universal build. Not sure why it no longer is, but I'm guessing the `CMAKE_OSX_ARCHITECTURES` flag got misplaced while refactoring.

I won't have much time to look at this until the weekend, but I can take a quick look at a PR if someone wants to fix it before then.

**Comment by clason** [comment]
@dundargoc ?

**Comment by carlocab** [comment]
> I'm guessing the `CMAKE_OSX_ARCHITECTURES` flag got misplaced while refactoring.

Yea, misplaced in 905dd49fece0903dba4e5a618f503d0237415b14.

The fix should be to do something like this:

https://github.com/neovim/neovim/blob/e6c214033a4fadf60faf99e95f8e9787e3c5e630/cmake.deps/cmake/BuildLibuv.cmake#L10-L11

I suggest updating the handling of `CMAKE_OSX_ARCHITECTURES` in the other `cmake.deps/cmake/*.cmake` files to also use `CMAKE_CACHE_ARGS`.

**Comment by tsaeger** [comment]
@clason thanks! pulled-down nightly NVIM v0.8.0-dev-1194-ga80ab395a and confirmed fixed.
