### ISSUE TITLE
bot cron problem?

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#2038]
@jszakmeister 

Maybe there's a problem with cron job for running bot?
Coverity analysis hasn't fired for 4 days, and clang analysis for 2.

**Comment by justinmk** [comment]
I will check

**Comment by jszakmeister** [comment]
@elmart My cron job has not been responsible for kicking off Coverity for some time now.  IIRC, it's in the bot-ci scripts, and it is possible we've reached our limit for the week the way it is done.

**Comment by elmart** [comment]
@justinmk Did you see anything? It still stays the same.

**Comment by justinmk** [comment]
@elmart I think my duct-taped little server is down. I will address it by tomorrow.

**Comment by justinmk** [comment]
@fwalch I force-started the coverity build on bot-ci, it thinks it's Thursday. Any clue why?

**Comment by fwalch** [comment]
Wrong date configuration on the Travis machine? Other than that, I don't have an idea.. I guess you restarted it once more, because now it reads

> Today is Sunday, not triggering Coverity.
> Next Coverity build is scheduled for Monday.

**Comment by elmart** [comment]
Monday already passed...
May I help with this somehow?

**Comment by justinmk** [comment]
@elmart The cron job is running since last night (and assign-labels is running every 15 minutes). 

> May I help with this somehow?

The bot-ci README provides detailed steps about how to run the scripts locally, if you want to try to debug the coverity script.

**Comment by justinmk** [comment]
@elmart Actually  there may not be problem with the coverity script; the cron job wasn't operational until after 17:00 EST yesterday which is when it usually does the coverity build. So that's why coverity wasn't run yesterday, and I forgot to manually start it.

**Comment by elmart** [comment]
Indeed, coverity seems to be running again.
But clang-analysis is still stuck on Feb 19th.
I've looked at the bot scripts, but I see nothing wrong.

**Comment by justinmk** [comment]
The clang script has a bug when there is exactly 1 defect... it's happened before

**Comment by elmart** [comment]
https://github.com/neovim/bot-ci/pull/49 should fix the failure when only one issue is present.
I'll later send another PR here to fix the clang warning itself.

**Comment by justinmk** [comment]
@elmart Thanks! Restarted clang build.
