### ISSUE TITLE
cmdheight=0: unsuccessful search is prompting for `ENTER` to continue

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#20380]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1183-ge6c214033

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Linux Mint 21

### Terminal name/version

Alacritty 0.12.0-dev

### $TERM environment variable

alacritty

### Installation

Built from Neovim source

### How to reproduce the issue

1. `nvim --clean ~/.config/nvim/init.lua`
2. `set cmdheight=0`
3. `/foobar999`

### Expected behavior

The behaviour should match `set cmdheight=1` which does not prompt to continue as displayed in this screenshot:

![cmdheight1](https://user-images.githubusercontent.com/11382509/192684875-1a1e653a-edd1-4cfb-abd0-b5b08c3f843d.png)

### Actual behavior

We get a prompt to continue with `set cmdheight=0` as displayed in this screenshot:

![cmdheight0](https://user-images.githubusercontent.com/11382509/192685003-d1143c42-9124-40d4-ab23-31aba06d3a39.png)

The prompt to continue is disrupting.

Ideally the behaviour of `cmdheight=0` and `cmdheight=1` should match.

**Comment by bluz71** [comment]
Notice also the screen real-estate difference; `cmdheight=1` is only taking up two lines of the screen (including statusline) whilst `cmdheight=0` is taking up four lines of the screen.

Ideally in this case `cmdheight=0` should only take up one line of space (the statusline area) with the content being the message `E486: Pattern not found: foobar999`.

Cheers.

**Comment by bfredl** [comment]
somehow the error message does not replace the "search continued at TOP" message, which is something which should happen regardless of 'cmdheight' (and would fix the problem)

**Comment by adastx** [comment]
Same issue happens on :file or <ctrl>G

Would it be possible to get a dynamic cmdheight, so that it is set to 0 when empty, and 1 when there is output?

**Comment by Shougo** [comment]
dynamic cmdheight is hard.
To change cmdheight is OK.
But when it is restored?

**Comment by bluz71** [comment]
> Would it be possible to get a dynamic cmdheight, so that it is set to 0 when empty, and 1 when there is output?

This was the behaviour of `cmdheight=0` for a while, but it proved unsatisfactory in that the statusline would move up and done far too often (in very distracting ways); for example in user mappings which invoked the command line (even when `silent` was selected). There probably were other technical issues as well.

The current overwrite statusline behaviour is an improvement (in my opinion). But there is no doubt that `cmdheight=0` is still a work in progress and was clearly (and correctly) marked in the 0.8 release as experimental.

My two main issues, to me, are firstly this issue here, `Press ENTER to continue` occurs far too often, which interrupts workflow where `cmdheight=1` does not incur those same blocks. The second issue is the amount of statusline flicker that occurs due to mappings and plugins invoking Ex commands, basically the statusline will quickly flash away (overwritten by the command line) then come back again; for example hit down arrow in a Telescope file finding window (lots of statusline flickering).

Ideally I would like the following (which may or may not be implementable):

- No `Press ENTER to continue` messages for `cmdheight=0` if not present `cmdheight=1`.
- Compact multi-line messages into a single line similar to how Neovim Diagnostic single-lines multi-line diagnostics for display in virtual lines
- No statusline flicker/redraw for any Ex command invoked via mapping or plugin; only actual interactive command line usage should wipe the statusline for the commandline (I don't know how feasible this issue)

User folke recently introduced the [noice.nvim](https://github.com/folke/noice.nvim) plugin to move the command line into a floating window and emit messages using nvim-notify. Whist a step forward for some users it feels alien to me, not what I ideally want from the `cmdheight=0` feature (I like command line down low in the traditional place).

For now I still use `cmdheight=1`; but I really hope `cmdheight=0` continues to improve since I genuinely love the look; but for now the flicker and `Press ENTER to continue` are deal-breakers.

My 2cents.

**Comment by Shougo** [comment]
@bluz71 Please test #20548.

**Comment by bluz71** [comment]
@Shougo, behaviour is improved.

**Comment by Shougo** [comment]
> No statusline flicker/redraw for any Ex command invoked via mapping or plugin; only actual interactive command line usage should wipe the statusline for the commandline (I don't know how feasible this issue)

It is my older implementation.  But it has very very big problems.
Please see this.

https://github.com/neovim/neovim/issues/18953

**Comment by Shougo** [comment]
It means `what is the interactive`?  User mappings and plugin mappings are same.

**Comment by Shougo** [comment]
I think `<silent>` mappings fix the flicker.

**Comment by amenpunk** [comment]
im trying with ```set.shortmess='nocI' ``` and its working fine for me :godmode:

**Comment by frnsys** [comment]
For anyone still dealing with this issue, so far this has worked:

```
set cmdheight=0

" Temporarily set cmdheight=1 when entering the command line
au CmdlineEnter * setlocal cmdheight=1

" 1ms after leaving, set it back to 0.
au CmdlineLeave * call timer_start(1, { tid -> execute('setlocal cmdheight=0')})
```

Hacky, and haven't thoroughly tested it though, so not sure if messes anything else up.

**Comment by bluz71** [comment]
Closing, this is now a duplicate of another issue.

@justinmk created #22478, _:messages query API, kill "Press ENTER" with fire_; that issue if implemented would also resolve this issue. Closing this one giving preference to Justin's issue.

If/when #22478 is implemented, then `set cmdheight=0` will become a lot more usable.

Cheers.
