### ISSUE TITLE
Side column remains visible after all ALE linter issues addressed

### ISSUE THREAD

**Issue by erquhart** [neovim/neovim#20399]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

macOS 12.4

### Terminal name/version

iterm2 3.4.16

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

Copying [repro case](https://github.com/dense-analysis/ale/issues/4243#issuecomment-1194118279) provided by @hsanson, maintainer of ALE:

To confirm this is a neovim issue I made this test:

1. Edit a new text file with empty configuration:
```
nvim -u NONE /tmp/test.txt
```
2. Write a few line like:
```
this is line 1

this is line 2

this is line 3
```
3. Define a new sign and add it to the first and last line:
```
:sign define piet text=>>
:sign place 10001 line=1 name=piet
:sign place 10002 line=5 name=piet
:sign place    # We can see both signs are present
```
Sign column should be visible and the signs should appear in line 1 and 5:
```
>> this is line 1

   this is line 2

>> this is line 3
```
4. Delete the first line with dd comand and then unplace the sign in line 5:
```
ggdd
:sign place   # We see that the first sign dissapears with the deleted line.
:sign unplace 10002
:sign place   # We see that the second sign dissapears with the unplace command
```
5. There are no signs but the sign column stays demonstrating there is some bug in neovim. According to documentation once there are no more signs the sign column should dissappear.
```
:sign place     # You can see no signs are present
```
My take on this is that when a sign is removed by some edit action (e.g delete line with the sign) a bug is triggered that causes neovim to keep the sign column even after all signs are removed.

### Expected behavior

Side column remains open/visible when all ALE linter errors have been resolved.

### Actual behavior

Side column should collapse when all ALE linter errors have been resolved.

ALE maintainer dug into this in an attempt to fix and determined it was likely an issue within Neovim: https://github.com/dense-analysis/ale/issues/4243#issuecomment-1194070099

**Comment by zeertzjq** [comment]
regressio between v0.6.0 and v0.7.0

**Comment by zeertzjq** [comment]
Also happen when the first sign is removed and a line without sign is deleted before the second sign is deleted.

**Comment by erquhart** [comment]
Well that was fast! Thanks so much for the quick response! 🙇‍♂️
