### ISSUE TITLE
Pasting from Windows clipboard to Ubuntu WSL terminal freezes nvim

### ISSUE THREAD

**Issue by Et9797** [neovim/neovim#20396]
### Neovim version (nvim -v)

0.8.0-dev (0.8.0~ubuntu1+git202209280149-e6c214033-c99271b19-d5ad4b253~ubuntu18.04.1)

### Vim (not Nvim) behaves the same?

no, vim 0.6.1

### Operating system/version

Ubuntu 18.04.5 (WSL 2)

### Terminal name/version

Default Ubuntu terminal from the Microsoft store

### $TERM environment variable

xterm-256color

### Installation

sudo add-apt-repository ppa:neovim-ppa/unstable

### How to reproduce the issue

Paste anything into nvim from windows clipboard

### Expected behavior

Paste windows clipboard 

### Actual behavior

Crashes neovim

**Comment by justinmk** [comment]
> Paste anything into nvim from windows clipboard

What keys exactly did you use? Is it the system paste, i.e. ctrl-shift-v or ctrl-v ?

**Comment by Et9797** [comment]
> > Paste anything into nvim from windows clipboard
> 
> What keys exactly did you use? Is it the system paste, i.e. ctrl-shift-v or ctrl-v ?

Right click -> Pasting

https://i.imgur.com/WiWjuK8.png

Ctrl+shift+v paste works fine. In 0.6.1 the right click paste worked.

**Comment by zeertzjq** [comment]
Does pressing `"+gP` crash?

**Comment by Et9797** [comment]
> Does pressing "+gP crash?

Yes

**Comment by Et9797** [comment]
Also it's not crashing, it just freezes for a good ~1 minute, and then does not paste the output. I checked if it was anything in my init.vim, but it occurs even with an empty file.

**Comment by peienxie** [comment]
Are you using Window Terminal and xclip?
maybe this relates: https://github.com/microsoft/terminal/issues/11945

I had the same issues before, terminal randomly freezes when pasting from windows to WSL2
I tried to remove xclip and have xsel installed for the last week. I have not experienced this problem.

**Comment by georgeanderson** [comment]
I reproduced this in `NVIM v0.8.4-dev-2+gb1ae775de` and can confirm that installing `xsel` seemed to have resolved the issue. I don't have xclip, but I also use `win23yank.exe` per recommend at https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl.

**Comment by justinmk** [comment]
> installing `xsel` seemed to have resolved the issue. I don't have xclip, but I also use `win23yank.exe` per recommend at https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl.

Could you try the suggestion given by `:help clipboard-wsl` ? If that works, I'll update the FAQ to point to that instead. https://neovim.io/doc/user/provider.html#clipboard-wsl

**Comment by georgeanderson** [comment]
Yep, it works, but it's very slow. Doesn't seem like a good solution. Having `win32yank.exe` in the path plus installing `xsel` "just works". No configuration, and it's fast.

By the way, I had to convert the suggestion to `Lua` before adding to my config. Let me know if I messed anything up in the process.

```lua
vim.g.clipboard = {
  name = 'WslClipboard',
  copy = {
    ['+'] = 'clip.exe',
    ['*'] = 'clip.exe',
  },
  paste = {
    ['+'] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
    ['*'] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
  },
  cache_enabled = 0,
}
```

My environment:

```console
wsl --version
WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19042.2604

uname -a
Linux W109WWSD33 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

nvim --version
NVIM v0.8.4-dev-2+gb1ae775de
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/george/code/hub/neovim/build/cmake.config -I/home/george/code/hub/neovim/src -I/home/george/code/hub/neovim/.deps/usr/include -I/usr/include -I/home/george/code/hub/neovim/build/src/nvim/auto -I/home/george/code/hub/neovim/build/include
Compiled by george@REDACTED

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by afifurrohman-id** [comment]
> Yep, it works, but it's very slow. Doesn't seem like a good solution. Having `win32yank.exe` in the path plus installing `xsel` "just works". No configuration, and it's fast.
> 
Does win32yank.exe and xsel still works for now?

I can confirm the `h: clipboard-wsl` work well, but is slow just when paste using `right click` or `p` not if using `Ctrl-Shift-v`.
`Ctrl-Shift-v` seem still faster and yanked (`y`) also still faster.

> 
> ```lua
> vim.g.clipboard = {
>   name = 'WslClipboard',
>   copy = {
>     ['+'] = 'clip.exe',
>     ['*'] = 'clip.exe',
>   },
>   paste = {
>     ['+'] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
>     ['*'] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
>   },
>   cache_enabled = 0,
> }
> ```

But again, need to add above configuration to work.



My environment:
```
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3447
```

**Comment by justinmk** [comment]
Anything remaining here is tracked in https://github.com/neovim/neovim/issues/29712
