### ISSUE TITLE
Haskell comment bug

### ISSUE THREAD

**Issue by RandomGamingDev** [neovim/neovim#20398]
### Neovim version (nvim -v)

v0.7.0

### Vim (not Nvim) behaves the same?

no, 

### Operating system/version

Windows 10 Home 21H1

### Terminal name/version

Command Prompt Version 10.0.19043.2006

### $TERM environment variable

The TERM environment variable isn't declared on my machine

### Installation

winget

### How to reproduce the issue

Write a haskell function like this:
````
{-
-
-}
````
with the cursor at the bottom of the console, and paste a line to the next line.
This will cause the comment highlighting to glitch and it won't highlight anything underneath what you just pasted.

### Expected behavior

<img width="87" alt="ExpectedBehaviorForNVIMHaskellCommentBug" src="https://user-images.githubusercontent.com/83996185/192922195-b260e7f7-7e2e-4ea9-b79f-4c4469f0c1d6.png">

### Actual behavior

<img width="58" alt="ActualBehaviorForNVIMHaskellCommentingBug" src="https://user-images.githubusercontent.com/83996185/192922214-3f148a8c-156c-45d0-ac67-467dc8a7ce5b.png">

**Comment by zeertzjq** [comment]
What is "paste a line to the next line"?

**Comment by zeertzjq** [comment]
It seems that after a `:redraw!` the syntax highlighting is correct, so this may be a syntax bug or a redrawing bug.

**Comment by zeertzjq** [comment]
Reproduced in version from v0.2.2 to HEAD, and also in latest Vim.

**Comment by zeertzjq** [comment]
https://github.com/vim/vim/issues/11247

**Comment by zeertzjq** [comment]
This is a bug in haskell syntax file. Please report this to Haskell Cafe mailinglist.
```vim
" Language:		Haskell
" Maintainer:		Haskell Cafe mailinglist <haskell-cafe@haskell.org>
" Last Change:		2020 Oct 4 by Marcin Szamotulski <profunctor@pm.me>
" Original Author:	John Williams <jrw@pobox.com>
```
