### ISSUE TITLE
file type not detected for ChangeLog

### ISSUE THREAD

**Issue by Jun-T** [neovim/neovim#20401]
### Neovim version (nvim -v)

latest git master

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

macOS, Linux

### Terminal name/version

Apple Terminal, gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

Start editing a ChangeLog file by nvim:
$ nvim --clean ChangeLog

### Expected behavior

&filetype is set to changelog

### Actual behavior

&filetype is not set

This happens if runtime/filetype.lua is used. filetype.vim works OK.
Sorry I have no time now to investigate further.

**Comment by clason** [comment]
Looks like an issue with the `starsetf` function? @smjonas

**Comment by smjonas** [comment]
There's a missing `return` here :smile:
https://github.com/neovim/neovim/blob/d9f5940997d8312c2c1612b0457de17b9720d312/runtime/lua/vim/filetype.lua#L1737
I can create a PR later.
