### ISSUE TITLE
Redraw error without msgsep option

### ISSUE THREAD

**Issue by cysp74** [neovim/neovim#20425]
### Neovim version (nvim -v)

NVIM v0.8.0

### Vim (not Nvim) behaves the same?

No,  9.0

### Operating system/version

Arch linux

### Terminal name/version

XTerm(372)

### $TERM environment variable

xterm-256color

### Installation

system package manager

### How to reproduce the issue

Cannot be reproduced with factory defaults due to the nature of error originated by changing the settings.

Steps:

:se display=lastline
:e (arbitrary file)
:vsplit
:hi

spaces till ends, then enter.

### Expected behavior

Redraw all split w/ valid content.

### Actual behavior

One the vertical splits get fuzzy, not refreshed.

**Comment by bfredl** [comment]
the non-msgsep code paths are going to be deleted for nightly very soon, but this would be a hotfix for `release-0.8` 

```diff
diff --git a/src/nvim/drawscreen.c b/src/nvim/drawscreen.c
index fdf70a081c..4ad8f24e5f 100644
--- a/src/nvim/drawscreen.c
+++ b/src/nvim/drawscreen.c
@@ -486,7 +486,8 @@ int update_screen(int type)
     } else if (type != UPD_CLEAR) {
       if (msg_scrolled > Rows - 5) {  // redrawing is faster
         type = UPD_NOT_VALID;
-        curwin_type = UPD_NOT_VALID;
+        redraw_all_later(UPD_NOT_VALID);
+        must_redraw = 0;
       } else {
         check_for_delay(false);
         grid_ins_lines(&default_grid, 0, msg_scrolled, Rows, 0, Columns);
```

**Comment by zeertzjq** [comment]
It is unlikely that there will be another 0.8.x release.
