### ISSUE TITLE
0.8.0: cmake fails with msgpack-c 4.0.0

### ISSUE THREAD

**Issue by kloczek** [neovim/neovim#20427]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux/x86_64

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

### How to reproduce the issue

- install msgpack-c 4.0.0
- try to build neovim

### Expected behavior

As neovim seems require msgpack >= 1.0.0 it should be OK with 4.0.0.

### Actual behavior

cmake fails with:
```console
-- Found Threads: TRUE
-- Found LibUV: /usr/lib64/libuv.so (Required is at least version "1.28.0")
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Msgpack (missing: MSGPACK_INCLUDE_DIR) (Required is at least
  version "1.0.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindMsgpack.cmake:50 (find_package_handle_standard_args)
  CMakeLists.txt:410 (find_package)
```

**Comment by dundargoc** [comment]
Which linux distribution do you use?

**Comment by kloczek** [comment]
My own. It is relarivelly close to Fedora rawhide.
No .. there is no mspack 4.0.0 in fedora.

**Comment by dundargoc** [comment]
The `cmake/FindMsgpack.cmake` is responsible for finding msgpack. Do you have pkgconfig installed? I think it's better to use that if possible.

**Comment by clason** [comment]
Usually need to install a `<foo>-dev` package to have the headers (which you need to build your own software against the binary library `<foo>`).

**Comment by clason** [comment]
Otherwise you offer too little detail to help with your problem; Neovim builds against `msgpack-c` 4.0.0 just fine (this is the version used for the bundled dependencies when you just `make`).

**Comment by kloczek** [comment]
> The `cmake/FindMsgpack.cmake` is responsible for finding msgpack. Do you have pkgconfig installed? I think it's better to use that if possible.

Yes I have.
However in this case because is used `find_package()` instead `pkg_check_modules()` pkgconfig file is not used and:
```coonsole
[tkloczko@devel-g2v SPECS]$ rpm -ql msgpack-devel | grep lib64
/usr/lib64/cmake/msgpack
/usr/lib64/cmake/msgpack/msgpack-config-version.cmake
/usr/lib64/cmake/msgpack/msgpack-config.cmake
/usr/lib64/cmake/msgpack/msgpack-targets-relwithdebinfo.cmake
/usr/lib64/cmake/msgpack/msgpack-targets.cmake
/usr/lib64/libmsgpackc.so
/usr/lib64/pkgconfig/msgpack.pc
```
As you see in i4.0.0 is not used `Msgpack` cmake module name but `msgpack`.

**Comment by kloczek** [comment]
As side note: IMO it wold be better everywhwere where it is only possible use `pkg_check_modules()` because it is declarative description instead cmake functionale one which relatively often is not correct and/or because it contains some additional checks which sometimes fails.

**Comment by jamessan** [comment]
> As you see in i4.0.0 is not used `Msgpack` cmake module name but `msgpack`.

What does that have to do with anything?  The casing we use for our cmake modules aren't related to what msgpack uses.

Neovim's build is capable of finding and building against msgpack-c 4.0.0.  As was already mentioned, that's what is used for every build run in CI and the automated releases on GitHub.

It's also used in Debian's builds.

```
  Could NOT find Msgpack (missing: MSGPACK_INCLUDE_DIR) (Required is at least
  version "1.0.0")
```

The error is that `MSGPACK_INCLUDE_DIR` isn't set.  We [look for](https://github.com/neovim/neovim/blob/dd1c613d0b47e818b7a6657f3c4bdeb959199628/cmake/FindMsgpack.cmake#L16) `msgpack/version_master.h` to verify what the include directory is.

At a guess, I'd say your package is missing that.

Either way, there are plenty of places that _are_ building neovim successfully against msgpack-c 4.0, so this is something in your environment.
