### ISSUE TITLE
Neovim 0.8 broke `fzf` plugin for Vim

### ISSUE THREAD

**Issue by cpkio** [neovim/neovim#20420]
### Neovim version (nvim -v)

NVIM v0.8.0-1210-gd367ed9b2

### Vim (not Nvim) behaves the same?

not using Vim

### Operating system/version

Windows 10 x64

### Terminal name/version

ConEmu

### $TERM environment variable

xterm

### Installation

manual installation

### How to reproduce the issue

install nvim
install plugin from https://github.com/junegunn/fzf
install https://github.com/junegunn/fzf.vim
try `:History` or any other command

### Expected behavior

Fzf running in a window (worked in 0.7.2 perfectly)

### Actual behavior

It seems like some updates broke process running: `E903: Process failed to start: function not implemented: "cmd.exe"`

Full text:
```
Error detected while processing function <SNR>40_history[3]..fzf#vim#command_history[1]..<SNR>102_fzf[18]..fzf#run[80]..function <SNR>40_history[3]..fzf#vim#command_history[1]..<SNR>102_fzf[18]..fzf#run[63]..<SNR>38_execute_term:
line   69:
E903: Process failed to start: function not implemented: "cmd.exe"
Error detected while processing function <SNR>40_history:
line    3:
E171: Missing :endif
Press ENTER or type command to continue
```

**Comment by justinmk** [comment]
https://github.com/junegunn/fzf/blob/984049586a5e5409131e4cb4600115f4a6b9c669/plugin/fzf.vim#L895-L903

**Comment by 3N4N** [comment]
@cpkio I can't reproduce it. I'm simply invoking `:History` command, without any argument. Did you mean some other command?

**Comment by cpkio** [comment]
I will investigate it further 🤷🏻

**Comment by justinmk** [comment]
@cpkio can you try the development : the [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has a pre-built zip for Windows. 

@3N4N in https://github.com/neovim/neovim/issues/20458 it was suggested that this might be isolated to older Windows versions.

**Comment by erw7** [comment]
See https://github.com/neovim/neovim/issues/14090#issuecomment-1110521019.

**Comment by 3N4N** [comment]
Looks like [ConPTY was introduced in August of 2018](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/#detecting-the-conpty-api). _If_ the version numbers are in `yymm` format, then it's possible that versions before 1809 didn't have ConPTY (I don't have exact citation).

Then what cpkio says is true: "Win 10 minimum" isn't exactly true. Win 10 v1809 is minimum.
