### ISSUE TITLE
Neovim 0.8 broke "foldmethod=marker" for unicode markers

### ISSUE THREAD

**Issue by JohnDoeDoe** [neovim/neovim#20438]
### Neovim version (nvim -v)

NVIM v0.8.0

### Vim (not Nvim) behaves the same?

Not installed.

### Operating system/version

Linux 5.19.12-arch1-1 

### Terminal name/version

Alacritty 0.10.1

### $TERM environment variable

xterm-256color

### Installation

Arch official repositories

### How to reproduce the issue

```
nvim --clean
:set foldmethod=marker
:set foldmarker=«,»
i
bbbbb
bbbbb
bbbbb
<esc>
zfgg
kk
za
```

### Expected behavior

Expect the fold to collapse.

### Actual behavior

Receive the following error:

E490: No fold found

Also noticed now in the clean test that the bottom fold text does not display immediately when on the last line, only displays after the fold attempt is made. However the fold text does display when the fold selection excludes the last line, but I still receive the no fold error regardless.

**Comment by zeertzjq** [comment]
Bisected to bd51ac2a347c0a3efb64e4b09400b7314286844c
