### ISSUE TITLE
`ft=swayconfig` unable to parse multi-line output blocks

### ISSUE THREAD

**Issue by 4e554c4c** [neovim/neovim#20436]
### Neovim version (nvim -v)

NVIM v0.8.0

### Vim (not Nvim) behaves the same?

yes, with `:syntax on`: vim 9.0 (2022 Jun 28, compiled Sep 01 2022 21:10:19)

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.3

### $TERM environment variable

xterm-kitty

### Installation

archlinux community repo

### How to reproduce the issue

```
nvim --clean
:e ~/.config/sway/config
```

example config:
```
output 'HDMI-A-2' {
    position 0 0
    transform 90
}
input "4176:1031:Yubico_YubiKey_OTP+FIDO+CCID" {
    xkb_layout "us"
    xkb_variant ""
    xkb_options ""
}
```
(output block contains errors, input block does not)

### Expected behavior

sway config is properly highlighted (with no errors)

### Actual behavior

sway config contains errors when containing output blocks, but not any other kind of block, such as an input block

![image](https://user-images.githubusercontent.com/4743113/193439227-19c91b3a-4af4-4c26-ac15-39ae7722ee84.png)

source of the error appears to be the original addition of the `swayconfig` filetype to vim: vim/vim#10672

**Comment by zeertzjq** [comment]
Please report this to the maintainer:
```
" Vim filetype plugin file
" Language: sway config file
" Original Author: James Eapen <james.eapen@vai.org>
" Maintainer: James Eapen <james.eapen@vai.org>
" Version: 0.1
" Last Change: 2022 June 07
```

**Comment by zeertzjq** [comment]
It seems you can also report at https://github.com/jamespeapen/swayconfig.vim/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
