### ISSUE TITLE
confirm() doesn't return after user input

### ISSUE THREAD

**Issue by jonthn** [neovim/neovim#2043]
I use ```confirm()``` to validate executing some commands in my vimrc and I noticed today it doesn't work anymore.
After the user answer the question nothing happens.

To reproduce use this .vimrc : 
```
if 1 == confirm("Do you want to see an error ?", "&Yes\n&No", 2)
  echohl ErrorMsg | echomsg "Here you go an error" | echohl NONE
else
  " No error, we're safe :)
endif
```
then launch nvim and press ```Y``` after that it sits there doing nothing.

## environment 

MacOS X 10.10.2
Xcode 6.3 Build version 6D520o  (from ```xcodebuild -version```)
nvim
```
nvim --version
NVIM 0.0.0-alpha+201502221455 (compiled Feb 22 2015 22:27:58)
Commit: 0df6b9168e9dc09d3e0ae6050d67b7c31c603782
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/Users/jonthn/neovim/build/config -I/Users/jonthn/neovim/src -I/Users/jonthn/neovim/.deps/usr/include -I/Users/jonthn/neovim/.deps/usr/include -I/Users/jonthn/neovim/.deps/usr/include/luajit-2.0 -I/Users/jonthn/neovim/.deps/usr/include -I/Users/jonthn/.pkgs/dist/include/gettext -I/usr/include -I/Users/jonthn/neovim/build/src/nvim/auto -I/Users/jonthn/neovim/build/include
Compiled by jonthn@aore.local  Features included (+) or not (-):
+acl             +farsi           -mouse_gpm       +tag_old_static
+arabic          +file_in_path    +mouse_netterm   -tag_any_white
+autocmd         +find_in_path    +mouse_sgr       +termresponse
-browse          +folding         -mouse_sysmouse  +textobjects
+byte_offset     -footer          +mouse_urxvt     +title
+cindent         +fork()          +mouse_xterm     -toolbar
-clipboard       +gettext         +multi_byte      +user_commands
+cmdline_compl   +iconv           +multi_lang      +vertsplit
+cmdline_hist    +insert_expand   +path_extra      +virtualedit
+cmdline_info    +jumplist        +persistent_undo +visual
+comments        +keymap          +postscript      +visualextra
+conceal         +langmap         +printer         +viminfo
+cscope          +libcall         +profile         +vreplace
+cursorbind      +linebreak       +quickfix        +wildignore
+cursorshape     +lispindent      +reltime         +wildmenu
+dialog_con      +listcmds        +rightleft       +windows
+digraphs        +localmap        +scrollbind      +writebackup
-dnd             +menu            +signs           -X11
-ebcdic          +mksession       +smartindent     -xfontset
-emacs_tags      +modify_fname    +startuptime     -xsmp
+eval            +mouse           +statusline      -xterm_clipboard
+ex_extra        -mouseshape      +syntax          
+extra_search    +mouse_dec       +tag_binary      
   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "$HOME/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/nvim"
```

**Comment by jonthn** [comment]
Fixed in recent commits, I don't know exactly which one but I can't reproduce it in NVIM 0.0.0-alpha+201503201819  Commit: a9e6a768c5a59a1ab69ccfbfb37c8939583a0284

**Comment by justinmk** [comment]
Fixed by https://github.com/neovim/neovim/pull/2182

**Comment by tarruda** [comment]
FWIW, I think we should deprecate user prompts at early startup. Plugins can use the `VimEnter` autocommand to peform actions that require user confirmation.

The main reason is that early prompts(when vimrc or plugins are sourced) happen before the UI is loaded, and we can't simply change them to be loaded after because vimrc and plugiins can be used to configure UI parameters.

While #2182 worked around the problem, early user prompts are certainly incompatible with `--headless` or `--embed` options

**Comment by jonthn** [comment]
In my case I only use confirm() in order to ask if I want to install 'vim-plug' and issue a curl/wget command if it's wanted.
I think it makes sense to ask this early and call ```PlugInstall``` on ```VimEnter```
All those steps are (mostly) only done at the first startup on a new machine.

**Comment by justinmk** [comment]
@jonthn Couldn't all of that be done on VimEnter?

**Comment by jonthn** [comment]
I'm not sure that would work as I branch my vimrc depending on the existence of 'vim-plug'.
I guess I should try to rework/refactor my vimrc in order to make the right initialization at ```VimEnter```

**Comment by jonthn** [comment]
FYI I modified my vimrc so the prompt is only done at ```VimEnter``` and it installs and configure the plugins but some plugins need to loaded before ```VimEnter``` otherwise they doesn't work properly (i.e. : vim-better-whitespace  amongst other). So a restart of vim with the plugin initialization done before ```VimEnter``` fix the problem.
