### ISSUE TITLE
Man page is broken?

### ISSUE THREAD

**Issue by ofirgall** [neovim/neovim#20432]
### Neovim version (nvim -v)

NVIM v0.8.0-v0.8.0

### Vim (not Nvim) behaves the same?

no, doesn't exist

### Operating system/version

Ubuntu 22.04

### Terminal name/version

alacritty 0.11.0-dev (ff63344)

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

nvim --clean
:Man tmux

### Expected behavior

Man page to be open and viewed normally.

### Actual behavior

This error:
```
Error detected while processing function man#open_page[43]..function man#open_page[38]..BufReadCmd Autocommands for "man
://*"..function man#read_page[11]..<SNR>22_put_page:
line   12:
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'highlight_man_page' (a nil value)^@stack traceback:
^@^I[string ":lua"]:1: in main chunk

```

With this weird file content:
```
TMUX(1)          BSD General Commands Manual          TMUX(1)

NNAAMMEE
     ttmmuuxx — terminal multiplexer

SSYYNNOOPPSSIISS
     ttmmuuxx [--22CCDDlluuvvVV] [--cc _s_h_e_l_l_-_c_o_m_m_a_n_d] [--ff _f_i_l_e] [--LL _s_o_c_k_e_t_-_n_a_m_e] [--SS _s_o_c_k_e_t_-_p_a_t_h] [--TT _f_e_a_t_u_r_e_s] [_c_o_m_m_a_n_d [_f_l_a_g_s]]

DDEESSCCRRIIPPTTIIOONN
     ttmmuuxx is a terminal multiplexer: it enables a number of terminals to be created, accessed, and controlled from a single screen.  ttmmuuxx may be detached from a screen and continue running in the background, then later reattached.
```
![Screenshot from 2022-10-01 22-49-41](https://user-images.githubusercontent.com/4954051/193425927-fc3ad22b-1ab9-462c-9437-dcb306204618.png)

**Comment by lewis6991** [comment]
You need to clean out your nvim runtime directory. `man.vim` no longer exists.

**Comment by justinmk** [comment]
We should add a :checkhealth check for this.

**Comment by ofirgall** [comment]
Thanks @justinmk! should I delete the runtime directory each time I re-build/install my neovim?

**Comment by lewis6991** [comment]
It certainly wouldn't hurt, but shouldn't be necessary most of the time.

**Comment by lewis6991** [comment]
Does not for me. Most definitely due to your version of `Man`. Please raise an issue with more details.
