### ISSUE TITLE
Screen flickers with remap "<C-d>zz" which centers the screen

### ISSUE THREAD

**Issue by asiryk** [neovim/neovim#20431]
### Neovim version (nvim -v)

v0.7.2, v0.8.0

### Vim (not Nvim) behaves the same?

no, 8.2.5032

### Operating system/version

macOS 12.5

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

xterm-256color

### Installation

v7 - installed from homebrew; v8 compiled from source

### How to reproduce the issue

1. Create ~/.config/nvim/init.lua config file and write there following two lines

```lua
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
```
2. Open any text file with a lot of lines
3. Make sure the cursor is on the first line
4. Press C-d

### Expected behavior

The cursor is moved to the center of the screen and the below lines are not flickering.

The identical Vim config works as expected.

```vim
nnoremap <C-u> <C-u>zz
nnoremap <C-d> <C-d>zz
```

### Actual behavior

The screen is flickering.
The cursor sets to the center of the screen, but for a couple of milliseconds below lines are shown in the place they should not.

https://user-images.githubusercontent.com/61456651/193419243-61b30081-4d22-4e61-b371-ca9f6fe26f40.mp4

**Comment by justinmk** [comment]
UI improvements are ongoing. Do we need an issue for every random flicker?

**Comment by asiryk** [comment]
But that's reproducible for the stable version of Neovim: 0.7.2.
If the issue is fixed with ongoing UI improvements I would be happy. But it's also reproducible for 0.8.0 🤷🏻‍♂️
