### ISSUE TITLE
build error: LIBVTERM 0.1.4 was found but version 0.3 is the minimum requirement

### ISSUE THREAD

**Issue by winkee01** [neovim/neovim#20430]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 22.04 LTS

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

build from repo (master)

### How to reproduce the issue

```
make CMAKE_INSTALL_PREFIX=/usr CMAKE_BUILD_TYPE=RelWithDebInfo
```

### Expected behavior

no errors

### Actual behavior

```
CMake Error at cmake/LibFindMacros.cmake:263 (message):
  REQUIRED PACKAGE NOT FOUND

  LIBVTERM 0.1.4 was found but version 0.3 is the minimum requirement.  This
  package is REQUIRED and you need to install it or adjust CMake
  configuration in order to continue building nvim.

  Relevant CMake configuration variables:

    LIBVTERM_INCLUDE_DIR=/home/winkee/downloads/neovim/.deps/usr/include
    LIBVTERM_LIBRARY=/home/winkee/downloads/neovim/.deps/usr/lib/libvterm.a

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/FindLIBVTERM.cmake:10 (libfind_process)
  CMakeLists.txt:505 (find_package)
```

<img width="728" alt="CleanShot 2022-10-01 at 22 25 33@2x" src="https://user-images.githubusercontent.com/49930785/193414192-d3f34333-707e-4317-a3f8-dcb6f7138e94.png">

**Comment by clason** [comment]
You need to `make distclean` first to regenerate the CMake cache.

**Comment by winkee01** [comment]
@clason Hello, I tried to build neovim on my macOS 12.3, but also encountered errors, how can I resolve it?
<img width="1128" alt="CleanShot 2022-10-01 at 22 47 59@2x" src="https://user-images.githubusercontent.com/49930785/193415146-20610e5c-71cd-4620-8da6-c5a7df2dbbdd.png">

**Comment by dundargoc** [comment]
Did you try `make distclean`?

**Comment by winkee01** [comment]
@dundargoc No, I use command `brew reinstall neovim`, I think it will fetch master branch and build from source for me.

**Comment by clason** [comment]
Then you need to raise this issue with Homebrew, not here.

In any case I would wait until 0.8 got packaged, which should be soon.

**Comment by winkee01** [comment]
@clason Can I just use the same commands as on Linux to build from source on macOS (I haven't tried yet)?

I am a bit confused on this part:
```
make CMAKE_BUILD_TYPE=Release MACOSX_DEPLOYMENT_TARGET=10.13 DEPS_CMAKE_FLAGS="-DCMAKE_CXX_COMPILER=$(xcrun -find c++)"
```

**Comment by clason** [comment]
Where are you getting that from?

It's just `make` (or `make CMAKE_BUILD_TYPE=Release`) even on macOS.

**Comment by winkee01** [comment]
It's from here:
https://github.com/neovim/neovim/wiki/Building-Neovim

please scroll down to the bottom

**Comment by clason** [comment]
That's for cross-compiling. You should just use the snippet from the main README.

**Comment by winkee01** [comment]
sure, I just tried, and it succeeded, cool! thanks a lot
