### ISSUE TITLE
Clickable and customizable sign area 

### ISSUE THREAD

**Issue by leaxoy** [neovim/neovim#20447]
### Feature already in Vim?

No

### Feature description

In some editor, the sign area (aka: gutter) is complex and powerful, so can neovim has the same powerful capability.
In JetbrainsIdea:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/8556349/193451166-357fb08e-73b3-498e-99b5-943e05e9f91e.png">
when click icon:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/8556349/193451177-94d8ca63-bbeb-4a6a-9464-bc56aa5efa86.png">

In vscode:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/8556349/193451202-1f07ace7-851c-405d-994d-0b33a879caee.png">
when click it will debug current test

**Comment by leaxoy** [comment]
Scenarios I can think:
### 1. Jump to super/sub types or jump between interface and implementations.
### 2. Start/Debug/Profile/...
### 3. If diagnostics, act/show codeaction/quickfix if any.

And user should be able to specify callback, for example: show actions  use `vim.ui.select` or show interactive input use `vim.ui.input`

**Comment by luukvbaal** [comment]
Might be covered by https://github.com/neovim/neovim/pull/20621#issuecomment-1326458472.
