### ISSUE TITLE
Detect `gohtml` files

### ISSUE THREAD

**Issue by devkvlt** [neovim/neovim#20443]
### Feature already in Vim?

No

### Feature description

Set filetype to `gohtml` for `*.go.html` and `*.gohtml` files.

**Comment by clason** [comment]
Filetype detection is maintained by Vim -- please open the issue (or, better, a PR) there.

**Comment by devkvlt** [comment]
Thanks for the quick reply. Just a question, isn't filetype detection in Neovim 0.8 done by some `filetype.lua` which is different from how Vim does it? Sorry if I'm not making sense!

**Comment by clason** [comment]
Yes, but the _logic_ (and tests) are still the same, even if the implementation is different.

**Comment by glepnir** [comment]
Go's template files do not have explicit extension definitions. Most of the extensions you pointed out are definitions from some plugins. also you can use `*.tmpl` etc.  so I think some plugins do this will be better .
