### ISSUE TITLE
remapped ctrl-w should show ^W in 'showcmd' area

### ISSUE THREAD

**Issue by bstaint** [neovim/neovim#20452]
### Neovim version (nvim -v)

0.8.0-1210-gd367ed9b2

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Windows 10

### Terminal name/version

neovim-qt

### $TERM environment variable

neovim-qt

### Installation

release

### How to reproduce the issue

`nmap <C-w>w :echo<CR>`
type `<C-w>`

### Expected behavior

NA

### Actual behavior

![image](https://user-images.githubusercontent.com/5853792/193467217-37d5938c-5263-462f-b584-febec57cbd80.png)

**Comment by bstaint** [comment]
neovim-qt `0.2.16.1` work fine, related to https://github.com/vim/vim/commit/77fc0b02e53bdc49213900e0055cb6d678ce180d

**Comment by luukvbaal** [comment]
`git bisect` revealed this is a regression caused by https://github.com/neovim/neovim/commit/7029b4b44a1cea58af3f54a4d62757b29a8e6aeb @zeertzjq.

**Comment by zeertzjq** [comment]
I know.

**Comment by zeertzjq** [comment]
This problem has always existed.

**Comment by luukvbaal** [comment]
Well the repro from this issue shows `^W` before commit https://github.com/neovim/neovim/commit/7029b4b44a1cea58af3f54a4d62757b29a8e6aeb.

**Comment by zeertzjq** [comment]
Try some other key with Alt modifier.

**Comment by luukvbaal** [comment]
I see, I just noticed the regression for Ctrl-W. I guess to fix this properly the transchar() routines would need to be extended to translate to the `<mod-key>` format(for 'showcmd')? Has this ever been brought up with Bram?
