### ISSUE TITLE
Use `vim.ui.select` when more than one LSP client is attached when calling `vim.lsp.buf.format`

### ISSUE THREAD

**Issue by ibhagwan** [neovim/neovim#20468]
### Feature description

Perhaps I'm missing something, I apologize in advance if I do.

I read the help for `vim.lsp.buf.format` and can't find a way to replicate the behavior of `vim.lsp.buf.formatting`, when using the latter, if I have more than one LSP client attached (e.g. `sumneko_lua` and `null-ls`), when calling `formatting` neovim will use `vim.ui.select` to choose which LSP client should execute the formatting:
> screenshot of `fzf-lua` enabled for `vim.ui.select` after running `formatting`
![image](https://user-images.githubusercontent.com/59988195/193664845-9c52a1cb-04e0-4cbf-9754-e5e88f8fa7da.png)

When using `vim.lsp.buf.format` the chosen client seems to be the first client that was attached to the buffer (unless using the `name=...` argument) but I can't seem to find a way to use `vim.ui.select` as was happening with `formatting` - is that possible?

**Comment by mfussenegger** [comment]
It uses all clients if you don't provide a filter. There is no replacement for the prompt because having to decide each time on format which client to use seems a bit tedious. The idea is that in your setup you'd know which one you want to use up-front and provide the name filter.

If you really want to have a prompt, you could create a custom function that calls `vim.ui.select` first, and then `vim.lsp.buf.format` with the selected clients id/name.

**Comment by ibhagwan** [comment]
> It uses all clients if you don't provide a filter. There is no replacement for the prompt because having to decide each time on format which client to use seems a bit tedious. The idea is that in your setup you'd know which one you want to use up-front and provide the name filter.

> If you really want to have a prompt, you could create a custom function that calls `vim.ui.select` first, and then `vim.lsp.buf.format` with the selected clients id/name.

Ty @mfussenegger for the prompt reply.

**Comment by lyonelz96** [comment]
@ibhagwan 

I took a stab at it (A lot of it was essentially taken from when this feature was merged for the old formatting() method)

```lua
local lsp_formatting = function()
		local function on_choice(choice)
			if choice == nil then
				return nil
			end

			print('Formatted with: ' .. choice.name)
			vim.lsp.buf.format({ bufnr = bufnr, name = choice.name })
		end

		local clients = vim.lsp.get_active_clients()
		local clients_with_formatting = vim.tbl_filter(function(client)
			return client['server_capabilities']['documentFormattingProvider']
		end, clients)

		table.sort(clients_with_formatting, function(a, b)
			return a.name < b.name
		end)

		if #clients_with_formatting > 1 then
			vim.ui.select(clients_with_formatting, {
				prompt = 'Select a language server:',
				format_item = function(client)
					return client.name
				end,
			}, on_choice)
		elseif #clients_with_formatting < 1 then
			print('No clients with formatting capabilities attached')
			on_choice(nil)
		else
			on_choice(clients_with_formatting[1])
		end
	end
```

**Comment by ibhagwan** [comment]
Ty @lyonelz96! looks good indeed, I literally just added this to my `on_attac` routine :-)

```lua
      -- format lua specifically using 'sumneko_lua'
      local fmt_opts = vim.bo[bufnr].ft=="lua"
        and 'async=true,bufnr=0,name="sumneko_lua"'
        or 'async=true,bufnr=0'
      map('n', 'gq',
        string.format('<cmd>lua vim.lsp.buf.format({%s})<CR>', fmt_opts),
          { desc = "format document [LSP]" })

```
