### ISSUE TITLE
neovim 0.8.0 broke rust-tools plugin 

### ISSUE THREAD

**Issue by jknoetzke** [neovim/neovim#20465]
### Neovim version (nvim -v)

NVIM v0.8.0-v0.8.0 

### Language server name/version

rls 0.5.2

### Operating system/version

OSX 12.6

### Steps to reproduce using "nvim -u minimal_init.lua"

Simply include the rust-tools plugin:

require('rust-tools').setup(rt)

### Expected behavior

Should load a rust file without error

### Actual behavior

Returns:

```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:289: Cannot serialise function: type not supported
stack traceback:
        [C]: in function 'encode'
        /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:289: in function 'notify'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1333: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
LSP[id=1] client has shut down while creating progress report
```

**Comment by jknoetzke** [comment]
Works as expected in 0.7.2

**Comment by dundargoc** [comment]
You should take it up with rust-tools first then to make sure the problem doesn't come from their code.

**Comment by dundargoc** [comment]
Wait, if it works 0.7.2 then the problem might be on the neovim side. I'll reopen and let someone more knowledgeable handle this.

**Comment by mfussenegger** [comment]
Can't reproduce and I'm farily sure that `vim.json.encode` couldn't serialize functions in 0.7.2 either. Not sure what `rt` is in your reproduction steps (I left it out). It might be what's causing your problems.  Latest rust-tools work fine for me on neovim 0.8

**Comment by dermesser** [comment]
The same happened to me after configuring neovim following this guide by @rsdlt --
https://rsdlt.github.io/posts/rust-nvim-ide-guide-walkthrough-development-debug/

Removing the `on_attach` directive from the server settings in `rt` helped. However, I'm not familiar enough with neovim to be able to propose a fix.

**Comment by mfussenegger** [comment]
There is nothing to fix in neovim. The guide is probably wrong. You _cannot_ send functions as settings to the server.
