### ISSUE TITLE
New `autocmd`s: `BufUpdatePre`, `BufUpdatePost`, etc.

### ISSUE THREAD

**Issue by amarakon** [neovim/neovim#20460]
### Feature already in Vim?

No

### Feature description

There are a few `autocmd`s for when writing to the buffer, including `BufWritePre` and `BufWritePost`. I think these should also exist for using `:update` rather than `:write`, as those will not apply if there are no changes for the file. Therefore, there should be `BufUpdatePre`, `BufUpdatePost`, etc. Or, there should be an option to make `BufWrite` `autocmd`s apply to the `:update` command even if Neovim did not write any changes.

**Comment by justinmk** [comment]
This is somewhat like "emit an event even if nothing happened". The only thing that happened is that the user tried a command. So this is covered by https://github.com/neovim/neovim/issues/11116
