### ISSUE TITLE
:function <lambda>123 syntax not supported but mentioned in docs

### ISSUE THREAD

**Issue by gelguy** [neovim/neovim#20466]
### Neovim version (nvim -v)

0.8

### Vim (not Nvim) behaves the same?

No

### Operating system/version

-

### Terminal name/version

-

### $TERM environment variable

-

### Installation

-

### How to reproduce the issue

Call `:function <lambda>NUM` where `NUM` is the ID of a defined lambda e.g.
```vim
:let A = {-> 1}

" function('<lambda>1')
:echo A

:function <lambda>1
```

### Expected behavior

Function definition is `echo`-ed.

### Actual behavior

`E129: Function name required`

The bracket-less syntax is mentioned in https://github.com/neovim/neovim/blob/16336c486ecb5a60e85a870904316308c7d7fc3f/runtime/doc/eval.txt#L1499-L1502

The doc change was included in commit https://github.com/neovim/neovim/commit/6ab71683d14a408e79f7cbda3a07ab65f76c6b35 but the actual code implementation is in https://github.com/vim/vim/commit/f79d9dd43f6fe05711d7e2616ab4b8bde2ccb089 which wasn't ported as it is a Vim9 patch.

Should `find_func_by_name` be ported? Or the doc reverted back to mentioning `:function {'<lambda>42'}`?

**Comment by zeertzjq** [comment]
It is definitely not implemented in a commit over a year later.
