### ISSUE TITLE
neovim-git wont build cmake deps missing

### ISSUE THREAD

**Issue by abdellatif-temsamani** [neovim/neovim#20464]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-16-g56998feebd

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch linux

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

AUR

### How to reproduce the issue

please replace libvterm-0.1 with libvterm in PKGBUILD of neovim-git

### Expected behavior

nil

### Actual behavior

nil

**Comment by clason** [comment]
That's an issue you need to report at Arch.
