### ISSUE TITLE
redraw doesn't update the UI during substitute

### ISSUE THREAD

**Issue by folke** [neovim/neovim#20463]
When using `vim.ui_attach` with `ext_cmdline`, `:redraw` doesn't update the ui during `substitute`

**Comment by folke** [comment]
The following hack seems to work:

```lua
  if vim.api.nvim_get_mode().mode == "c" and vim.fn.getcmdline():find("s/") then
    -- HACK: this will trigger redraw during substitue
    vim.api.nvim_input("<space><bs>")
  end
```

**Comment by zeertzjq** [comment]
Hmm, this seem to be intentional from #9783

**Comment by folke** [comment]
The `cmdline_show` events also do come in **before** the redraw lock, but it seems the `cmdline_pos` events come in **after** the redraw lock.

Maybe it can be fixes by also sending the `cmdline_pos` events before the redraw lock?

**Comment by folke** [comment]
So, that's why my hack works. I simply get a new `cmdline_show` event

**Comment by folke** [comment]
I was able to fix this for Noice by calling `update_screen()` with **ffi**

```lua
  local ffi = require("noice.util.ffi")
  if ffi.cmdpreview then
    -- HACK: this will trigger redraw during substitute and cmdpreview,
    -- but when moving the cursor, the screen will be cleared until
    -- a new character is entered
    ffi.update_screen()
  end
```

**Comment by AndreM222** [comment]
has there been any news about this issue?
