### ISSUE TITLE
Stop neovim from changing terminal cursor

### ISSUE THREAD

**Issue by notwidow** [neovim/neovim#20477]
### Neovim version (nvim -v)

latest v.0.8.0

### Vim (not Nvim) behaves the same?

not vim user

### Operating system/version

Artix Linux rolling

### Terminal name/version

Alacritty Latest

### $TERM environment variable

xterm-256color

### Installation

pacman

### How to reproduce the issue

set terminal cursor to underline and open and close neovim

### Expected behavior

Neovim should not change terminal cursor and cursor shape should be set to default terminal cursor after exit

### Actual behavior

Changes cursor

**Comment by zeertzjq** [comment]
Duplicate of #4396
