### ISSUE TITLE
Solargraph or LSP bug

### ISSUE THREAD

**Issue by dsisnero** [neovim/neovim#20471]
### Neovim version (nvim -v)

nvim v0.8.0-1210-gd367ed9b2

### Language server name/version

solargraph 0.47.2

### Operating system/version

Windows 10.0.19042 N/A Build 19042

### Steps to reproduce using "nvim -u minimal_init.lua"

vim.lsp.set_log_level("debug")

vim.lsp.start({
    name = 'solargraph',
    cmd = {'cmd.exe', '/C', 'solargraph', '--stdio'},
    root_dir = vim.fs.dirname(vim.fs.find({'Gemfile', 'Rakefile'}, { upward = true })[1]),
})

### Expected behavior

Lsp logs show connected

### Log file

https://gist.github.com/dsisnero/a1380a0797db2f1aa7bb0dfd5d4cc1e0#file-appdata-local-nvim-data-lsp-log

**Comment by justinmk** [comment]
"'C:\\Users\\Dominic' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

just a guess, is there possibly a space in your $HOME path? Need to find out where that path path is coming from.

**Comment by dsisnero** [comment]
Yes - there is a space ,   work computer and for some reason the IT folks gave me a username with spaces

**Comment by dsisnero** [comment]
How can I debug this?

**Comment by erw7** [comment]
```
[ERROR][2022-10-03 18:13:02] .../vim/lsp/rpc.lua:733	"rpc"	"cmd.exe"	"stderr"	"'C:\\Users\\Dominic' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
```

This log is an error read from `stderr`. Therefore, this is not a bug in `neovim`. Therefore, this is closed. If you can prove this is a bug in `neovim`, feel free to reopen this.

> How can I debug this?

Check `solargraph.bat` and `solargraph` in the same directory as `solargraph.bat`.
