### ISSUE TITLE
Type annotations in the neovim lua stdlib

### ISSUE THREAD

**Issue by ehllie** [neovim/neovim#20488]
### Feature already in Vim?

n/a

### Feature description

This is technically not a bug since it has no effect on the functioning of neovim itself, but it does make writing configuration somewhat less convenient. A lot of functions have proper type annotations, however among them, there are also plenty of function that don't. For example:
https://github.com/neovim/neovim/blob/63be7651829f8b77c4974d08ebe09f7775e41a8a/runtime/lua/vim/_editor.lua#L453-L456

Which causes the following lines of configuration:
```lua
vim.defer_fn(function()
  -- Some function definition
end, 100)
```
To be reported as errors ``Lua Diagnostics.: Cannot assign `function` to parameter `Callback`.``, ``Lua Diagnostics.: Cannot assign `integer` to parameter `Number`.``

The official spec for annotations is provided in the [sumneko lua repository](https://github.com/sumneko/lua-language-server/wiki/Annotations) as far as I'm aware. It would be really convenient to have neovim be compliant with them.

**Comment by bfredl** [comment]
any PR to fix incorrect or missing type info in runtime lua code is welcome.

**Comment by clason** [comment]
This is ongoing effort (and PRs welcome); so we don't need to track it.
