### ISSUE TITLE
replace_keycodes breaks mapping if contains `<Cmd>`

### ISSUE THREAD

**Issue by kuuote** [neovim/neovim#20480]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-19-g04f763b20

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux

### Terminal name/version

termux

### $TERM environment variable

screen-256color

### Installation

build from repo

### How to reproduce the issue

1. Execute `nvim --clean` and evaluate following Lua code.
```lua
vim.keymap.set("i", "a", "'<Cmd>echo 42<CR>'", { expr = true })
```
2. Enter insert mode and type `a`.

Note: Works as expected if specify `replace_keycodes = false` to `opts`

### Expected behavior

Prints `42` to echo area.

### Actual behavior

Inserts `<80>ý 42` to buffer.

**Comment by zeertzjq** [comment]
This is the correct behavior.

**Comment by biosugar0** [comment]
## Note
I also had this problem with broken my key mapping.
It works fine with `replace_keycodes = false`.
 
```
vim.keymap.set("i", "a", "'<Cmd>echo 42<CR>'", { replace_keycodes = false,  expr = true })
```
