### ISSUE TITLE
NERDTree menu keeps consuming screen space

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#20486]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Void Linux

### Terminal name/version

Alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

Void repositories

### How to reproduce the issue

- Start Neovim: `nvim -c 'NERDTree'`
- Press `m` in the NERDTree buffer to open the menu
- Press `<esc>` to close the menu

### Expected behavior

The space taken up by the menu should be released again.

### Actual behavior

The space is not released. Looking at the source code of NERDTree shows the following:

```vim
        echo 'NERDTree Menu. ' . navHelp . ', or the shortcuts indicated'
        echo '========================================================='

        for i in range(0, len(self.menuItems)-1)
            if self.selection ==# i
                echo '> ' . self.menuItems[i].text
            else
                echo '  ' . self.menuItems[i].text
            endif
        endfor

```
(file `lib/nerdtree/menu_controller.vim`, line `72`)

It looks like NERDTree is just using regular `echo` commands to draw an interactive menu and something is getting stuck. Interestingly, if I add an `echo ''` after the loop the space is released again.

**Comment by HiPhish** [comment]
Oops, forgot to include a screenshot.

![Screenshot_20221004_195955](https://user-images.githubusercontent.com/4954650/193893711-549ab362-908c-4bca-b310-fde4f3192e89.png)

**Comment by zeertzjq** [comment]
It seems that reverting patch 9.0.0191 fixes the problem:
```diff
diff --git a/src/nvim/window.c b/src/nvim/window.c
index c3806e10f..25f96ee8d 100644
--- a/src/nvim/window.c
+++ b/src/nvim/window.c
@@ -6278,13 +6278,6 @@ void command_height(void)
   // p_ch was changed in another tab page.
   curtab->tp_ch_used = p_ch;
 
-  // If cmdline_row is smaller than what it is supposed to be for 'cmdheight'
-  // then set old_p_ch to what it would be, so that the windows get resized
-  // properly for the new value.
-  if (cmdline_row < Rows - p_ch) {
-    old_p_ch = Rows - cmdline_row;
-  }
-
   // Find bottom frame with width of screen.
   frp = lastwin_nofloating()->w_frame;
   while (frp->fr_width != Columns && frp->fr_parent != NULL) {
```

That patch didn't change anything because of #17335

**Comment by zeertzjq** [comment]
Oh, Vim also has this bug.

**Comment by duanasq** [comment]
I'm not using neovim, I'm just using regular vim and I was getting this error also. Any instructions how to fix this for normal vim users?
> Interestingly, if I add an echo '' after the loop the space is released again.
Doing this for now, as it works for me.
Thanks!

**Comment by zeertzjq** [comment]
Update Vim version.
