### ISSUE TITLE
Funny return value when using `nvim_get_hl_by_name()` from Lua.

### ISSUE THREAD

**Issue by uga-rosa** [neovim/neovim#20504]
### Neovim version (nvim -v)

NVIM v0.8.0
NVIM v0.9.0-dev-4bfbac05c

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 20.04.5 LTS (WSL2)

### Terminal name/version

Windows terminal

### $TERM environment variable

empty

### Installation

build from repo

### How to reproduce the issue

nvim --clean
`:echo nvim_get_hl_by_name('FloatBorder', v:true)`
`:lua vim.pretty_print(vim.api.nvim_get_hl_by_name('FloatBorder', true))`

### Expected behavior

`{}` return even from Lua.

### Actual behavior

```
{}
```

```
{
  [true] = 6
}
```

**Comment by seandewar** [comment]
This is a special value used to disambiguate an empty dictionary from an empty list (both of which can usually be represented by an empty table in Lua).
The actual table you're seeing here is `{[vim.type_idx] = vim.types.dictionary}` (see `:h lua-special-tbl`).

This is important if you then wanted to pass this value over the Lua -> Vim script bridge, for example.
E.g: assuming that `FloatBorder` has been cleared:
```vim
:lua vim.g.foo = vim.api.nvim_get_hl_by_name("FloatBorder",{})
:echo type(g:foo) == v:t_dict " If {} was returned instead, this'd be false
```

However, this behaviour isn't exactly ideal if you're just dealing with the Lua side.
E.g: passing such a special table directly to `nvim_set_hl()` does not work:
```
:lua vim.api.nvim_set_hl(0,"Normal",vim.api.nvim_get_hl_by_name("FloatBorder",{}))
" Error: invalid key:
```
Maybe it would be useful if such a table was treated more like `vim.empty_dict()` (or just `{}`) when passed to the API?

**Comment by uga-rosa** [comment]
I noticed this very error when I tried to pass this return value to nvim_set_hl.

**Comment by justinmk** [comment]
> Maybe it would be useful if such a table was treated more like `vim.empty_dict()` (or just `{}`) when passed to the API?

👍

**Comment by echasnovski** [comment]
`nvim_get_hl_by_name('FloatBorder', true)` is now soft deprecated in favor of `nvim_get_hl(0, { name = 'FloatBorder' })` which doesn't have this problem (returns `vim.empty_dict()` for missing group). This is a result of #22693 and #22737. It seems to be safe to close this issue.
