### ISSUE TITLE
Paste via ssh stopped working after 0.7.2 -> 0.8.0 update

### ISSUE THREAD

**Issue by dibakch** [neovim/neovim#20507]
### Neovim version (nvim -v)

NVIM v0.8.0-v0.8.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian Testing

### Terminal name/version

kitty 0.21.2

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

Connect to remote host `ssh some-host.com`
Run `nvim`
Enter insert mode
Select some test, e.g., in a browser
Press middle mouse button to paste it to the terminal

### Expected behavior

The pasted text is inserted

### Actual behavior

An error appears shortly saying `E353: Nothing in register "`.  Otherwise, nothing is inserted.

However, there is also nothing in register `"*` or in `"+`. (I'm not sure if those registers were properly populated over ssh with nvim 0.7.2 before, but at least pasting to the terminal worked as a workaround).

**Comment by dibakch** [comment]
I figured that 0.8.0 probably has more mouse support.  After `set mouse=`, I got the same behavior as 0.7.2.

**Comment by justinmk** [comment]
Right-click would have given a hint :)

**Comment by dibakch** [comment]
Yes, this was actually how I figured out that there is now a different default behavior for the mouse input :)
