### ISSUE TITLE
seeing rendering artifacts with &laststatus=3

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#20514]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-4179-gde47b4b90

### Vim (not Nvim) behaves the same?

no

### Operating system/version

archlinux

### Terminal name/version

st 0.8.5

### $TERM environment variable

tmux-256color

### Installation

build from source

### How to reproduce the issue

* myinit.vim as below
* nvim -u myinit.vim +'h 41'
* `jjjjjjj` " keep pressing the `j`

```
set splitbelow
set laststatus=3
set cmdheight=1
```

### Expected behavior

scroll down the page without any artifacts

### Actual behavior

![8fb2c7b0-4584-11ed-a0d1-54b203702c9c](https://user-images.githubusercontent.com/6236829/194342822-3e118c44-1e46-466c-b471-f2b7d2953a6e.jpg)

**Comment by haolian9** [comment]
more tests:
* if i remove the `set cmdheight=1`, the problem is gone
* if i put the `set cmdheight=1` upon the `set laststatus=3`, the problem is gone

**Comment by haolian9** [comment]
sure.

i have tried commit f7b175e049db9262a45ee1c5eb41a38bd5b8ac38, this problem remains.
```
> nvim --version
NVIM v0.9.0-dev-4183-gf7b175e04
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by haoliang@eugene

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/nvim-master/share/nvim"

Run :checkhealth for more info
```

**Comment by zeertzjq** [comment]
Oh, I think I know what the problem is/

**Comment by charbelnicolas** [comment]
Can this be related too?

https://github.com/hrsh7th/nvim-cmp/issues/1218

**Comment by zeertzjq** [comment]
No.
