### ISSUE TITLE
gf does not work with filenames containing unicode characters

### ISSUE THREAD

**Issue by medialaxis** [neovim/neovim#20517]
### Neovim version (nvim -v)

v0.8.0-1210-gd367ed9b2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux

### Terminal name/version

xfce4-terminal 1.0.4

### $TERM environment variable

xterm-256color

### Installation

Downloaded  nvim-linux64.tar.gz

### How to reproduce the issue

touch filename_with_unicode_ααα
nvim --clean
Type "filename_with_unicode_ααα"
Type "gf" with cursor on filename.

### Expected behavior

filename_with_unicode_ααα is opened.

### Actual behavior

E447: Can't find file "filename_with_unicode_" in path

**Comment by medialaxis** [comment]
nvim 0.7.2 works

**Comment by dundargoc** [comment]
https://github.com/neovim/neovim/pull/18489
