### ISSUE TITLE
keyboard issue while switch from editor to command

### ISSUE THREAD

**Issue by itwars** [neovim/neovim#2051]
Hi,

I using neovim for awhile now, and since let's say one week, I'm facing a strange keyboard issue on several OS, and different computer:
- in insert mode, when pressing ESC for saving my work (:w), it doesn't handle my key sequence! It only work if I type slowly?! In fact it doesn't "receive" my ESC key!
I'm using Neovim only in console mode.

**Comment by khalidchawtany** [comment]
@itwars put the following in your **.vimrc**, see if it solves the issue?

```
  set timeout
  set timeoutlen=750
  set ttimeoutlen=250

  "NeoVim handles ESC keys as alt+key set this to solve the problem
  if has('nvim')
     set ttimeout
     set ttimeoutlen=0
  endif

```


If you are using **tmux**, put the following in your **.tmux.conf** file:
```
    # Faster Command Sequences
    set -s escape-time 0
```

These are discussed in the following issues:
https://github.com/neovim/neovim/issues/2035, https://github.com/neovim/neovim/issues/2016, https://github.com/neovim/neovim/issues/2017

**Comment by itwars** [comment]
@khalidchawtany Many thanks, it works!

**Comment by bigeagle** [comment]
I found braces matching also has a timeout, better setting `set matchtime=0` in nvimrc.

**Comment by itwars** [comment]
Sorry,
But this trick work perfect on native OS, but in Virtualbox I got the same issue (and with older neovim it works!).
In addition, neovim+tmux sucks : no more reaction when using <end> or <home> key!
Help ....

**Comment by tarruda** [comment]
@itwars as mentioned by @khalidchawtany, you can lower the `escape-time` option in tmux(also needs to be done in virtualbox). Neovim by default has `ttimeout` unset, so if you set that option in your vimrc do it like this:

```vim
if !has('nvim')
  set ttimeout
  set ttimeoutlen=...
endif
```

For tmux, you need to save something like this in your ~/.tmux.conf:

```
set -g escape-time 10
```

**Comment by itwars** [comment]
Hi @tarruda ,

Sorry, it was my mistake: I haven't reload my tmux :(

**Comment by tarruda** [comment]
> But [end] / [home] don't work!

Maybe you are using an old version of the unibilium library, try reinstalling neovim from the scratch, including all dependencies

**Comment by itwars** [comment]
I faced the same issue on both OSX (cmd+arrows to go end or home) and Linux.
I removed neovim on both OS, clean cache, and reinstall using brew for OSX and trusty ppa for linux: same issue;

**Comment by justinmk** [comment]
closing for https://github.com/neovim/neovim/issues/2093
