### ISSUE TITLE
Unable to :wq inside of tutorial (:Tutor) - Cannot write, 'buftype' option is set

### ISSUE THREAD

**Issue by Lasni** [neovim/neovim#20516]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no, 9.0.217

### Operating system/version

macOS 12.6

### Terminal name/version

iTerm2 3.4.16

### $TERM environment variable

TERM=xterm-256color

### Installation

homebrew

### How to reproduce the issue

Following the nvim :Tutor tutorial, at lesson 1.6 when trying to save the changes in text

:wq results in error: _E382: Cannot write, 'buftype' option is set_

### Expected behavior

I should be able to save the changes with :wq

### Actual behavior

_E382: Cannot write, 'buftype' option is set_ error gets thrown and changes are not saved. In Vim :wq works fine.

**Comment by justinmk** [comment]
@fmoralesc

**Comment by Lasni** [comment]
> `:set buftype=""` ?

This seems to work, but only for a single session. After exiting and re-opening nvim, I would have to re-type this in order for :wq to work. Is there a config file I can define this rule in?

**Comment by zeertzjq** [comment]
Did you follow these steps:
2. Run `nvim tutor`
3. Insert and delete text
4. Save and quit with `:wq`

I cannot reproduce with these steps.

**Comment by Lasni** [comment]
@zeertzjq it's the default tutorial file that :Tutor command generates.

**Comment by zeertzjq** [comment]
I don't think that file is meant to be saved. The tutor says:
```
    'nvim' is the command to start the Nvim editor, 'tutor' is the name of
    the file you wish to edit. Use a file that may be changed.
```
So you should edit another file (not with a `.tutor` extension) or a new file.

**Comment by dnaicker86** [comment]
I think maybe update the tutorial to not ask users to type `:wq` 

![image](https://github.com/neovim/neovim/assets/130728803/92473b70-7182-44bb-946b-159ac7f93074)

**Comment by seandewar** [comment]
That is telling users to try `:wq` _outside_ of the tutor, on a real file.

**Comment by dnaicker86** [comment]
Having reference to the command at the start forms part of an instruction and then having the disclaimer second could cause newcommers to try the command before going through the next paragraph of text.

**Comment by ydanneg** [comment]
<img width="983" alt="Screenshot 2023-11-14 at 10 46 29" src="https://github.com/neovim/neovim/assets/459303/d6729e7c-64f0-4c53-8946-a2ca779e769e">
Shouldn't Tutor mention how to resolve this issue? Looks like a Tutorial blocker. Have no idea what to do next and how to save my tutorial progress.

OS: MacOS 13.6
Installation: /usr/local/Cellar/neovim/0.9.4

**Comment by JDoan03** [comment]
I just also ran into this issue when following this video: https://www.youtube.com/watch?v=m8C0Cq9Uv9o&t=1104s while on this repo for some instructions: https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file.

Just to be clear, I have created my own repo by forking from above and followed the instructions in the repo above.

When in nvim, and doing `:Tutor` then `:wq` I run into
`E382: Cannot write, 'buftype' option is set`

Once I set the buftype with `:set buftype=""` I get another error
`E212: Can't open file for writing: operation not permitted`

What else should be tried?

**Comment by zeertzjq** [comment]
> Use a file that may be changed

**Comment by Nukori** [comment]
All of the above is by far correct, but for posterity:
:wq 'example.txt'
This operation is explained a little further into the tutorial

**Comment by HauklandJ** [comment]
Consider renaming the temp file from "tutor" to "my-new-file" or similar to avoid this confusion entirely
