### ISSUE TITLE
CheckHealth fails after `gem install neovim` using `rbenv`

### ISSUE THREAD

**Issue by martin-braun** [neovim/neovim#20529]
### Neovim version (nvim -v)

0.8.0 release

### Vim (not Nvim) behaves the same?

no checkhealth in vim

### Operating system/version

macOS 12.6 (21G115)

### Terminal name/version

iTerm2 Build 3.5.0beta7

### $TERM environment variable

xterm-256color

### Installation

Homebrew (brew.sh)

### How to reproduce the issue

Install rbenv, Ruby and neovim gem:
```sh
brew install rbenv
echo 'export PATH=$HOME/.rbenv/bin:$PATH' >> ~/.zshrc
echo 'eval "$(rbenv init - zsh)"' >> ~/.zshrc
. ~/.zshrc
rbenv install 3.1.2
rbenv global 3.1.2
gem install neovim
ruby -v && gem list ^neovim$ && gem list -ra ^neovim$
```

Last command gives output: 

```
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]

*** LOCAL GEMS ***

neovim (0.9.0)

*** REMOTE GEMS ***

neovim (0.9.0, 0.8.1, 0.8.0, 0.7.1, 0.7.0, 0.6.2, 0.6.1, 0.6.0, 0.5.1, 0.5.0, 0.4.0, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.0, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1)
```

In your Neovim configs:

```lua
vim.g.loaded_ruby_provider = nil
vim.g.ruby_host_prog = os.getenv("HOME") .. "/.rbenv/shims/ruby"
```

Now check the health:

```sh
nvim +CheckHealth
```

### Expected behavior

Ruby provider should be OK.

### Actual behavior

```
## Ruby provider (optional)
  - INFO: Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
  - INFO: Host: /Users/me/.rbenv/shims/ruby
  - WARNING: Gem "neovim" is out-of-date. Installed: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21], latest: 0.9.0
    - ADVICE:
      - Run in shell: gem update neovim
```

**Comment by erw7** [comment]
See `:h g:ruby_host_prog`.

**Comment by martin-braun** [comment]
@erw7 Thank you. It was confusing, because the Python 3 provider was the interpreter itself, but this time it is the `neovim-ruby-host` instead of `ruby` itself. The same pitfall exists for the node.js provider.

I think it would be incredibly useful to display the host binary name Neovim expects when running `:checkhealth`.

Thank you!
