### ISSUE TITLE
Provide some examples about how to set NVIM_LISTEN_ADDRESS to support older RPC plugins

### ISSUE THREAD

**Issue by danielo515** [neovim/neovim#20527]
### Feature already in Vim?

No

### Feature description

According to docs, NVIM_LISTEN_ADDRESS is now deprecated and it is specifically unset on jobstart. The docs also suggest that they can be set using the env option:
https://neovim.io/doc/user/builtin.html#jobstart-env

However, for someone that has no familiarity with this API is hard to know what value should I put there, and where I can get it from. Is neovim always started with a listening server address? If so, how can I get it in order to set the proper ENV?

**Comment by danielo515** [comment]
I made some testing, and it should be as simple as adding an example that looks like this:

```
let opts = { 'env': { 'NVIM_LISTEN_ADDRESS': v:servername  } }
call jobstart(['executable'], opts)
```

However, I'm not sure if this is enough to fulfil all the potential requirements of legacy binaries relying on this.

**Comment by justinmk** [comment]
> Is neovim always started with a listening server address? If so, how can I get it in order to set the proper ENV?

yes, and it is given by `v:servername`.

your example looks correct.

**Comment by danielo515** [comment]
> > Is neovim always started with a listening server address? If so, how can I get it in order to set the proper ENV?
> 
> yes, and it is given by `v:servername`.
> 
> your example looks correct.

That was a super quick documentation update. Thank you very much!
