### ISSUE TITLE
Camel Case support for spell check

### ISSUE THREAD

**Issue by AniAggarwal** [neovim/neovim#20533]
### Feature description

Now that spell checking is integrated with Neovim, I'd love if camel case was respected in comments. 
Currently, the following Java code snippet will mark `newValue` and `camelCase` and `OtherCase` as misspelled:
```java
    /**
     * A comment with camelCase and OtherCases..
     * @param newValue the new value (who would have thought??)
     */
    public void foo(int newValue) {
```
It would be great if the camel/upper case could be detected and have the words be 'split' when analyzed for correct spelling.

**Comment by zeertzjq** [comment]
`:set spelloptions+=camel`
