### ISSUE TITLE
vim.cmd "builder pattern"

### ISSUE THREAD

**Issue by dpacbach** [neovim/neovim#20541]
### Feature already in Vim?

No

### Feature description

I like the new `vim.cmd` indexing support, though I think it might be nice to have one particular enhancement to it to make writing commands with prefix keywords a bit more consistent.  To motivate, let's say that we were previously writing this command:
```lua
vim.cmd[[tabdo wincmd =]]
```
With nvim_cmd indexing we can now write:
```lua
vim.cmd.tabdo{ 'wincmd', '=' }
```
But that lacks consistency since some parts of the command are indexed and others are strings.  For these kinds of commands I would prefer to be able to write the following:
```lua
vim.cmd.tabdo.wincmd{ '=' }
```
I think this would be a straightforward change to the metatable of `vim.cmd`: instead of having its `__index` method return a function, it instead returns a table that can either be called (using `__call`) or can be further indexed; each time it is indexed it builds up an argument list.  Another example:
```lua
-- :silent write
vim.cmd.silent.write()
```

If people think this would be useful I can send a PR (my assumption is that it would be a pure Lua change).

**Comment by lewis6991** [comment]
Sounds interesting, I would maybe restrict it to commands that can be chained (like `silent` , `tabdo`)

**Comment by ranjithshegde** [comment]
@lewis6991 Ever since `nvim_parse_cmd` and subsequently `nvim_cmd`, don't things like `silent`, `botright`, `tab` get treated as mods and/or flags? Similar to `bash` `--flags`? 

With that in mind, `vim.cmd.silent.*` is validating some of vimscript weirdness where flags and mods are also `ex` commands.
Maybe `nvim_parse_cmd` and derivatives are a good opportunities for enforcing these structures.

**Comment by dpacbach** [comment]
@ranjithshegde That's a good point; if all that we could use this proposed feature for are flag-like modifiers then maybe it is not a good idea.

**Comment by lewis6991** [comment]
Here's a summary of which commands currently have a flag/mod in `nvim_cmd`:

| Ex command                                                    | Has mod in nvim_cmd I/F |
| ------------------------------------------------------------- | ----------------------- |
| `:[range]perldo {cmd}`                                        | :x:                     |
| `:[range]rubydo {cmd}`                                        | :x:                     |
| `:leftabove {cmd}`                                            | :white_check_mark:      |
| `:aboveleft {cmd}`                                            | :white_check_mark:      |
| `:rightbelow {cmd}`                                           | :white_check_mark:      |
| `:belowright {cmd}`                                           | :white_check_mark:      |
| `:topleft {cmd}`                                              | :white_check_mark:      |
| `:botright {cmd}`                                             | :white_check_mark:      |
| `:cdo[!] {cmd}`                                               | :x:                     |
| `:cfdo[!] {cmd}`                                              | :x:                     |
| `:ld[o][!] {cmd}`                                             | :x:                     |
| `:lfdo[!] {cmd}`                                              | :x:                     |
| `:autocmd [group] {event} {aupat} [++once] [++nested] {cmd}`  | :x:                     |
| `:noautocmd {cmd}`                                            | :white_check_mark:      |
| `:vertical {cmd}`                                             | :white_check_mark:      |
| `:horizontal {cmd}`                                           | :white_check_mark:      |
| `:hide {cmd}`                                                 | :white_check_mark:      |
| `:[range]windo {cmd}`                                         | :x:                     |
| `:[range]bufdo[!] {cmd}`                                      | :x:                     |
| `:sandbox {cmd}`                                              | :white_check_mark:      |
| `:[count]tab {cmd}`                                           | :white_check_mark:      |
| `:[range]tabdo {cmd}`                                         | :x:                     |
| `:keepalt {cmd}`                                              | :white_check_mark:      |
| `:[range]argdo[!] {cmd}`                                      | :x:                     |
| `:[range]folddoopen {cmd}`                                    | :x:                     |
| `:[range]folddoclosed {cmd}`                                  | :x:                     |
| `:terminal[!] {cmd}`                                          | :x:                     |
| `:!{cmd}`                                                     | :x:                     |
| `:lockmarks {cmd}`                                            | :white_check_mark:      |
| `:keepmarks {cmd}`                                            | :white_check_mark:      |
| `:keepjumps {cmd}`                                            | :white_check_mark:      |
| `:noswapfile   {cmd}`                                         | :white_check_mark:      |
| `:confirm {cmd}`                                              | :white_check_mark:      |
| `:browse {cmd}`                                               | :white_check_mark:      |
| `:filter[!] {pattern} {cmd}`                                  | :white_check_mark:      |
| `:filter[!] /{pattern}/ {cmd}`                                | :white_check_mark:      |
| `:silent[!] {cmd}`                                            | :white_check_mark:      |
| `:unsilent {cmd}`                                             | :white_check_mark:      |
| `:[count]verbose {cmd}`                                       | :white_check_mark:      |
| `:keeppatterns {cmd}`                                         | :white_check_mark:      |

**Comment by dpacbach** [comment]
I guess there is a question also of how to support the `!`s... how about this (open to suggestions):
```lua
-- Option 1
vim.cmd.silent.bang.write()

-- Option 2
vim.cmd.silent['!'].write()

-- Option 3
vim.cmd['silent!'].write()

-- Others?
```
I'm not really a fan of option 3... I'd probably go with either 1 or 2, with a lean more towards 2.

**Comment by lewis6991** [comment]
I don't think we should support any. There is already `vim.fn.system` (sync) or `vim.loop.spawn` (async).

**Comment by lewis6991** [comment]
We already have `vim.cmd.write{ bang = true }`

**Comment by lewis6991** [comment]
`argdo`, `bufdo`, `tabdo` are all driven by `ex_listdo()` which has a fairly messy implementation and not something I want to support/encourage for use in Lua. For now the recommendation is to use basic loops instead of these commands.

For that reason, there is now nothing to action in this issue.
