### ISSUE TITLE
`:h string.gsub` does not work

### ISSUE THREAD

**Issue by beardedsakimonkey** [neovim/neovim#20547]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS

### Terminal name/version

iterm2

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

nvim --clean
:h string.gsub

### Expected behavior

takes you to string.gsub in luaref.txt

### Actual behavior

E149: Sorry, no help for string.gsub

**Comment by justinmk** [comment]
this was fixed on master
