### ISSUE TITLE
Release neovim with code signing

### ISSUE THREAD

**Issue by dclong** [neovim/neovim#20550]
### Feature description

Some companies requires installed software to have code signing so that it can be used. Releasing neovim with code signing enables it to be used in more environments.

**Comment by carlocab** [comment]
Duplicate of #11011.

You also might find that you don't need software to be code-signed if you follow the macOS installation instructions at https://github.com/neovim/neovim/releases/tag/v0.8.0 or https://github.com/neovim/neovim/releases/tag/nightly. (But this depends on how corporate policy is implemented, of course.)
