### ISSUE TITLE
nvim auto close when resizing window

### ISSUE THREAD

**Issue by ttw1018** [neovim/neovim#20569]
### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.6

### Terminal name/version

iterm2 

### $TERM environment variable

xterm-256

### Installation

prebuild file

### How to reproduce the issue

open a file with neovim and then resize the ternimal windows
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/48583236/194847102-279a2674-c00d-45a3-82bf-98b6139ba87b.png">

### Expected behavior

Nothing happens except reszing window.

### Actual behavior

Nvim will auto close and then give a malloc error

**Comment by glepnir** [comment]
I can't reproduce with  `nvim --clean` .

**Comment by ttw1018** [comment]
I remove all my plugins, and that situation doesn't happen again. So, I think it was caused by some bugs in plugins. I'll try to find the bug plugin. 
Thanks for all useful suggestions.
