### ISSUE TITLE
additional signcolumn to the right of the number line

### ISSUE THREAD

**Issue by boltlessengineer** [neovim/neovim#20565]
### Feature already in Vim?

No

### Feature description

There are tones of plugins which use signcolumn. (like gitsigns, lsp-config, todo-comments, nvim-ufo and so on)
But currently, since the SignColumn is located on the left side of the Number Line, the only way to prevent each Sign from overlapping is to increase the width of the SignColumn.

I found that there is one column to the right of the NumberLine, it would be nice to use this space as an additional SignColumn.

This would prevent the Signs getting farther from the NumberLine.

Examples:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/60088301/194818746-97556be6-0abc-4cec-b604-961accc05ea5.png">
Intellij's fold signs right side of the number line

![](https://code.visualstudio.com/assets/docs/editor/codebasics/folding.png)
VSCode's fold signs

**Comment by justinmk** [comment]
covered by https://github.com/neovim/neovim/issues/11212

**Comment by boltlessengineer** [comment]
@justinmk Is it correct that the Issue is related to this?
What I wanted to say was not to put the signcolumn to the right of the content, but to put the signcolumn between the numberline and the content.

(Of course, I may have missed it due to my poor English skills)

**Comment by justinmk** [comment]
It's not exactly the same, but the general idea of putting signcolumn(s) here, there, everywhere, is covered by that issue.

**Comment by boltlessengineer** [comment]
Ok, now I understand. Thank you for your explanation.

**Comment by subnut** [comment]
It looks like #11212 is more focused on having a signcolumn on the extreme right only?

If #11212 covers the general idea of putting signcolumns everywhere, I suggest the title of that issue be updated to reflect the same.
