### ISSUE TITLE
Breaking change neovim 1.0  or 2.0

### ISSUE THREAD

**Issue by notwidow** [neovim/neovim#20564]
### Feature already in Vim?

no

### Feature description

Hi, It's just a suggestion. why not you make neovim free of vimscript and write in lua only?... i would love to have an ide like vim without vimscript ... Rust and lua seems to be best choices for getting rid of vim script.

**Comment by glepnir** [comment]
- there are still many people who like to use vimscript.
- many files in the runtime that use `vimscript`. 
- Compatible with plugins written in `vimscript`.
