### ISSUE TITLE
`:Man` broken on macOS 13

### ISSUE THREAD

**Issue by mathjiajia** [neovim/neovim#20579]
### Neovim version (nvim -v)

v0.9.0-dev-66-g121f052d1

### Vim (not Nvim) behaves the same?

no, 9.0.270

### Operating system/version

macOS 13.0 beta

### Terminal name/version

kitty 0.26.3

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue
```
nvim --clean
:Man g| (here | is the cursor)
and then press `tab` here
```
### Expected behavior

Like vim, a sound feedback to indicate that vim has no completion available.

### Actual behavior

```
E5108: Error executing Lua function: /usr/local/share/nvim/runtime/lua/man.lua:502: /usr/local/share/nvim/runtime
/lua/man.lua:11: man.lua: "command error 'man -w': What manual page do you want?\n"
stack traceback:
        [C]: in function 'error'
        /usr/local/share/nvim/runtime/lua/man.lua:502: in function 'get_paths'
        /usr/local/share/nvim/runtime/lua/man.lua:514: in function </usr/local/share/nvim/runtime/lua/man.lua:513>
```

**Comment by lewis6991** [comment]
What does `man -w` return in your shell?

**Comment by mathjiajia** [comment]
Added:
I tried `man -w git`, which returns:
`/opt/homebrew/share/man/man1/git.1`
and for `man -w man`:
`/usr/share/man/man1/man.1`

**Comment by lewis6991** [comment]
Are you able to provide more information about the `man` version on macos beta? E.g. its own man page?

**Comment by lewis6991** [comment]
macOS 12.6:

```
       -w or --path
              Don't actually display the man pages, but do print the location(s) of the files that would be formatted or displayed. If no argument is given: display (on stdout) the list of
              directories that is searched by man for man pages. If manpath is a link to man, then "manpath" is equivalent to "man --path".
```

macOS 13:

```
  -w      Display the location of the manual page instead of the contents
             of the manual page.
```

Thanks Apple!

**Comment by lewis6991** [comment]
What's the output of `man -v`? For me it is `man, version 1.6g`

**Comment by mathjiajia** [comment]
> What's the output of `man -v`? For me it is `man, version 1.6g`

On my side this is an illegal command:
```
/usr/bin/man: illegal option -- v
Usage:
 man [-adho] [-t | -w] [-M manpath] [-P pager] [-S mansect]
     [-m arch[:machine]] [-p [eprtv]] [mansect] page [...]
 man -f page [...] -- Emulates whatis(1)
 man -k page [...] -- Emulates apropos(1)
```
I have no ideal about how to check the version of `man` using other command.

**Comment by lewis6991** [comment]
For god sake! So Apple has updated `man` to be completely incompatible with the version it had before.

We are going to have to special case this and fallback to `$MANPATH` I think.

I can't fix this myself until I'm running macOS 13.

**Comment by clason** [comment]
I run the beta on my home machine, so can take a look in the evening or tomorrow. I don't recall `:Man` breaking in this way there, though.

**Comment by mathjiajia** [comment]
Thank you @lewis6991 for the information.

Hi @clason, in case you need, my macOS beta is `22A5365d`.
This problem will occur when using the auto-completion,
especially with `cmp-cmdline` since it tries to complete once typed `Man |`.

**Comment by clason** [comment]
You wrote it's reproducible with `nvim --clean`, so let's focus on that and not add complicated plugins into the mix.

**Comment by mathjiajia** [comment]
> You wrote it's reproducible with `nvim --clean`, so let's focus on that and not add complicated plugins into the mix.

Agree. Then you need to press `tab` (after `:Man g`, say) to trigger this problem.

**Comment by lewis6991** [comment]
Side note: this doesn't break in vim because it doesn't implement specific `man` completion (it just uses `shellcmd`), however this issue will still affect it since it also relies on `man -w`

**Comment by mathjiajia** [comment]
Thank you @lewis6991 for the prompt reply.
After a quick test, it has fixed the problem.

**Comment by mathjiajia** [comment]
Wait.

The problem disappeared in kitty.
However, using the `terminal` builtin with macOS, or `Warp`, the bug is still there:
```
E5108: Error executing Lua function: vim/shared.lua:0: s: expected string, got n
il
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'split'
        /usr/local/share/nvim/runtime/lua/man.lua:495: in function 'get_paths'
        /usr/local/share/nvim/runtime/lua/man.lua:508: in function </usr/local/share/nvim/runtime/lua/man.lua:507>
```

**Comment by lewis6991** [comment]
The change only fallsback to `MANPATH`. If `MANPATH` isn't set, then there's no way for this to work.

**Comment by mathjiajia** [comment]
> The change only fallsback to `MANPATH`. If `MANPATH` isn't set, then there's no way for this to work. Unless you can find another way to get the list of all man dirs?

I see. Thank you for the explanation.
The command `echo $MANPATH` gives dirs in `kitty` while it returns nothing in the builtin `terminal` and ``Warp`.

**Comment by lewis6991** [comment]
I've added another fallback. Try the PR again.

**Comment by mathjiajia** [comment]
Confirmed with `kitty`: the problem has been solved.

In `Warp`, the error is
```
E5108: Error executing Lua function: /usr/local/share/nvim/runtime/lua/man.lua:11: man.lua: "Could not determine man directories from 'man -w' or $MANPATH"
stack traceback:
        [C]: in function 'error'
        /usr/local/share/nvim/runtime/lua/man.lua:11: in function 'man_error'
        /usr/local/share/nvim/runtime/lua/man.lua:498: in function 'get_paths'
        /usr/local/share/nvim/runtime/lua/man.lua:513: in function </usr/local/share/nvim/runtime/lua/man.lua:512>
```
So this is a problem of either `Apple` or `Warp`?

Thank you again for your efforts.

**Comment by lewis6991** [comment]
Ok, I've updated again to avoid the error entirely, however completion will only work for known names. E.g. `g` won't complete but `git` will complete to `git(1)`. Not ideal but better than nothing.

**Comment by lewis6991** [comment]
We can try and use `manpath` if it's available!

**Comment by lewis6991** [comment]
Updated to use `manpath`.

**Comment by mathjiajia** [comment]
> Updated to use `manpath`.

Awesome!

Confirmed: it works well in all of terminal simulators I am using.

**Comment by zeertzjq** [comment]
No
