### ISSUE TITLE
Test not passing

### ISSUE THREAD

**Issue by Numkil** [neovim/neovim#2057]
Operating system: fedora 21

![screenshot from 2015-02-25 12 09 37](https://cloud.githubusercontent.com/assets/5604686/6369490/2e5b1978-bce7-11e4-9800-ba1a80a454b7.png)

![screenshot from 2015-02-25 12 06 30](https://cloud.githubusercontent.com/assets/5604686/6369472/0b301f0c-bce7-11e4-9b29-b61a762f3906.png)

**Comment by tarruda** [comment]
These job/pty tests are flawed because there's no telling when the OS will send the chunks of data. In this case the `^C` is sent separately from the `interrupt received, press again to exit`. Can you send a PR that mark these pty tests as pending? I might fix them in my next PR.

**Comment by Numkil** [comment]
Did as you asked, I think. #2058

**Comment by tarruda** [comment]
@Numkil thanks
