### ISSUE TITLE
version `GLIBC_2.29' not found v0.8.0 appimage

### ISSUE THREAD

**Issue by GH-maggio** [neovim/neovim#20581]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Rocky Linux release 8.6 (Green Obsidian)

### Terminal name/version

Windows Terminal Version: 1.15.2713.0

### $TERM environment variable

screen-256color

### Installation

nvim.appimage

### How to reproduce the issue

```
chmod -x nvim.appimage
./nvim.appimage

/tmp/.mount_nvim.a2GzySR/usr/bin/nvim: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_nvim.a2GzySR/usr/bin/nvim)
```

### Expected behavior

nvim runs

### Actual behavior

nvim fails to run due to missing glibc library 2.29

the appimage may have to be re-built on an environment with an older version glibc; rockylinux/centos 8.6 has the following:

```
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by dundargoc** [comment]
I restarted the Release job which failed for some reason. Can you test the latest appimage?

**Comment by dundargoc** [comment]
Eh, I think this is fixed. Let me know if this is still a problem.

**Comment by GH-maggio** [comment]
@dundargoc still getting the same error:

```
❯ ./nvim.appimage --version
/tmp/.mount_nvim.aPikmxe/usr/bin/nvim: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_nvim.aPikmxe/usr/bin/nvim)
```

**Comment by dundargoc** [comment]
Did you try the new appimage?

**Comment by GH-maggio** [comment]
Gotcha, the latest release works great

```
❯ ./nvim.appimage --version
NVIM v0.9.0-dev-64-gd4e749f1b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/__w/neovim/neovim/build/cmake.config -I/__w/neovim/neovim/src -I/__w/neovim/neovim/.deps/usr/include -I/usr/include -I/__w/neovim/neovim/build/src/nvim/auto -I/__w/neovim/neovim/build/include
Compiled by root@ca0207e8d177

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by asagent7** [comment]
I am getting the same error with the nvim 0.8.0 release appimage. Will I need the 0.9 dev mentioned above to get past this?

**Comment by dundargoc** [comment]
Your choices are either using the latest pre-release, use an older version, or wait for `v0.8.1` to come out. Historically the first patch usually comes out pretty fast after a minor version bump.
