### ISSUE TITLE
path separator is not respected in vim.fs.find 

### ISSUE THREAD

**Issue by kylo252** [neovim/neovim#20594]
### Neovim version (nvim -v)

0.9.0-dev-73-gcba05c541

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

windows 11

### Terminal name/version

NA

### $TERM environment variable

NA

### Installation

NA

### How to reproduce the issue

```
:lua =vim.fs.find(".luacheckrc")
```

### Expected behavior

consistent slashes, either:
- `c:\\projects\\neovim\\.luacheckrc`
- `c:/projects/neovim/.luacheckrc`

### Actual behavior

`c:\\projects\\neovim/.luacheckrc`

**Comment by dundargoc** [comment]
Closed by https://github.com/neovim/neovim/pull/22890
