### ISSUE TITLE
Builtin colorschemes don't work with default `&termguicolors` value

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#20597]
### Neovim version (nvim -v)

0.9.0-dev-8-g01721aaa6

### Vim (not Nvim) behaves the same?

no, vim 9.0.049

### Operating system/version

macOS 12.5.1

### Terminal name/version

kitty, iTerm2, wezterm

### $TERM environment variable

xterm-256color, xterm-kitty

### Installation

build from repo

### How to reproduce the issue

```
nvim --clean
colorscheme blue
```

Here's some images done with kitty, iTerm2, and wezterm:

iTerm2

<img width="964" alt="Screen Shot 2022-10-11 at 10 36 48 AM" src="https://user-images.githubusercontent.com/7416158/195121057-98e7ad6d-d70c-40d3-a186-9470f5fa0e06.png">

wezterm (left) and kitty (right)

<img width="1792" alt="Screen Shot 2022-10-11 at 10 21 34 AM" src="https://user-images.githubusercontent.com/7416158/195117935-e60e1797-ed00-42b7-b1f6-4275eaf8628b.png">

The reason is because `termguicolors` is not set by default, so the first set of colors in any of these files don't apply, and nvim doesn't have/produce a `t_Co` value so the next `s:t_Co` check for 256 colors fails as well, and so on, and we are left with no highlighting being applied.

### Expected behavior

When `termguicolors` is off (it is by default), we can run `colorscheme blue` and have highlighting groups applied.

### Actual behavior

Highlights from any of the `$VIMRUNTIME/colors/*.vim` files work when `termguicolors` is off.

Not sure where this should be fixed, or if upstream should be involved or not -- I think once there's a default neovim colorscheme they should be all removed honestly. As of right now they don't work, and we aren't adjusting them for neovim (terminal colors, neovim hl-groups that vim doesn't have, etc.). As a user I'd rather have one colorscheme that is supported well and complete out of the box.

**Comment by craigmac** [comment]
Related patch https://github.com/neovim/neovim/pull/19848

**Comment by craigmac** [comment]
I'd say that's the easiest fix for this issue specifically, yes. Might be easier way, but this is working for me:

```
let s:t_Co = has('nvim') && !&termguicolors ? 256 : 16777216
```

**Comment by craigmac** [comment]
This would make 256 color capable the minimum though and the 16 and 0 color variants could never be reached.

**Comment by clason** [comment]
Still, improvement over the status quo.

> let s:t_Co = has('nvim') && !&termguicolors ? 256 : 16777216

Since we distribute these files with our runtime, the `has('nvim')` check is unnecessary.

**Comment by clason** [comment]
If we seriously want to tackle this, `:h tui-colors` says
> Nvim uses 256 colours by default, ignoring |terminfo| for most terminal types,
including "linux" (whose virtual terminals have had 256-colour support since
4.8) and anything claiming to be "xterm".  Also when $COLORTERM or $TERM
contain the string "256".

> Nvim similarly assumes that any terminal emulator that sets $COLORTERM to any
value, is capable of at least 16-colour operation.

So we don't need to support 0 colors, and can check these variables for 16 colors?

**Comment by clason** [comment]
> nvim doesn't have/produce a `t_Co` value

`:echo &t_Co` works for me, though

**Comment by clason** [comment]
@craigmac can you test what `:echo &t_Co` says for you?
