### ISSUE TITLE
conf on windows: is it _nvimrc?

### ISSUE THREAD

**Issue by jmlucjav** [neovim/neovim#2059]
I am testing how this runs on windows, as https://github.com/coolwanglu/neovim.as already has a UI that runs on it.

I can start nvim and the UI ok, but my _vimrc is not picked up.
I can see neovim has created files like _nvimlog and _nviminfo right by my _vimrc, so I just assume the conf file will just be _nvimrc (the info at https://github.com/neovim/neovim/wiki/Differences-from-vim does not take windows into account)? I tried it but I don't get my mappings and not even any error so I assume it is not picked up.

thanks

**Comment by equalsraf** [comment]
It should be _nvimrc, yes.

I confirm there is something going on with _nvimrc. There are currently issues with file permission checks so that might be related.

**Comment by justinmk** [comment]
There's no need for the underscore on Windows these days... we should change it to .nvimrc

**Comment by jmlucjav** [comment]
oh nice, didn't know that. Just tried and true, .vimrc works. Sure, it is better, the more similar to the standard conf the better.

**Comment by equalsraf** [comment]
@jmlucjav does it also work with directories?

**Comment by jmlucjav** [comment]
@equalsraf can you elaborate?

**Comment by equalsraf** [comment]
Can you create/use directories with a dot in the name (sorry I'm not on Windows right now).

**Comment by jmlucjav** [comment]
yes, I just tried editing a buffer and then:

:w .test

saves the file .test fine.
But now my sessions (I use some session plugin) are not found (after renaming to .vimrc), so there is still some glitch somehere

**Comment by jmlucjav** [comment]
disregard my last comment about the session plugin broken. The session I was trying to load contained _vimrc, that cannot be found now, that is why it didn't work. All works fine apparently.

**Comment by justinmk** [comment]
> Can you create/use directories with a dot in the name

@equalsraf You can create dotfiles from the shell and from Vim. Not from Windows Explorer. I think the gain in consistency is worth it, for documentation and troubleshooting.

When do users ever need to *create* (or rename) a `.vimrc` from Explorer?

**Comment by equalsraf** [comment]
They might need to create the .nvim folder.

**Comment by tbttfox** [comment]
@justinmk  You can create a dotfile in WIndows Explorer (at least in Windows 7),  but it requires a trick to do it. You would name the file `.vimrc.` , and Windows will remove the trailing dot.   Now, whether you can expect people to know that is an entirely different issue.

**Comment by jmlucjav** [comment]
I use alternative explorers so I was unaware of these limitations to create dotfiles...

**Comment by justinmk** [comment]
obviated by XDG support. https://github.com/neovim/neovim/pull/3120
