### ISSUE TITLE
ctrl-f does not work properly

### ISSUE THREAD

**Issue by yamam** [neovim/neovim#20605]
### Neovim version (nvim -v)

v0.9.0-dev-76-g45cc5fd76

### Vim (not Nvim) behaves the same?

no, vim 9.0.176

### Operating system/version

Ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

maxmize terminal window
nvim --clean
:set number
type `100aa<cr><esc>gg<c-f>`

### Expected behavior

If the window height is n lines, move to the nth line.

### Actual behavior

Move to line 22 regardless of window height.

This defect occurs after cce0840.

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/main.c b/src/nvim/main.c
index 5687e0a6a..1b1480fae 100644
--- a/src/nvim/main.c
+++ b/src/nvim/main.c
@@ -315,6 +315,7 @@ int main(int argc, char **argv)
   cmdline_row = (int)(Rows - p_ch);
   msg_row = cmdline_row;
   default_grid_alloc();  // allocate screen buffers
+  win_new_screensize();
   set_init_2(headless_mode);
   TIME_MSG("inits 2");
 
```

**Comment by zeertzjq** [comment]
This is another way to fix the problem:
```diff
diff --git a/src/nvim/option.c b/src/nvim/option.c
index 208112561..0101cb2fa 100644
--- a/src/nvim/option.c
+++ b/src/nvim/option.c
@@ -596,11 +596,6 @@ void set_init_2(bool headless)
   }
   comp_col();
 
-  // 'window' is only for backwards compatibility with Vi.
-  // Default is Rows - 1.
-  if (!option_was_set("window")) {
-    p_window = Rows - 1;
-  }
   set_number_default("window", Rows - 1);
   (void)parse_printoptions();      // parse 'printoptions' default value
 }
```
