### ISSUE TITLE
Emacs (evil) style line highlight

### ISSUE THREAD

**Issue by mtglsk** [neovim/neovim#2060]
Please reference the issue here: https://github.com/tpope/vim-sensible/issues/91

How to reproduce:
    `set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+`

Then visually select lines.

The gist of the issue is that vim makes visual selection of empty lines and knowing when you selected any EOL difficult.

Now, when it comes to solutions, there are some interesting things in emacs going on. Emacs when you visually select lines highlight lines normally, but when you select beyond visible characters (EOL at the end of line), then it highlights the whole line:

![emacs](https://cloud.githubusercontent.com/assets/10101321/6375044/e01fef1c-bd14-11e4-8e06-47655f365aac.png)

On the other hand, here we have vim making the same selection:

![vim2](https://cloud.githubusercontent.com/assets/10101321/6375078/1b79e464-bd15-11e4-8257-09f07e70b95f.png)

As you can see, vim not only is not able to visually show selected empty lines, it also makes it hard to see were the EOL is. This is a major usability concern, because the possible solutions are to set listchars and EOL to some string, then of course you could select those lines (with minuses like VIM making lines longer +1 char, so sometimes you could get wrapped phantom empty lines). I think that this is one of things that Emacs clearly does right.

**Comment by mseeber** [comment]
I am not sure, what I did different...

I ran
    nvim -u NONE

And this is the selection i get:
![nvim_select](https://cloud.githubusercontent.com/assets/6922115/6376131/55cd38f8-bd1c-11e4-9737-a920aecd9469.png)

Normal unix line endings and on line 3, I added a few spaces.

**Comment by mtglsk** [comment]
You probably have `set listchars+=eol:$` and `set nolist`. Then it shows like above, but not when there is no `eol` in listchars. For reference see the issue attached here: https://github.com/tpope/vim-sensible/issues/91

**Comment by mseeber** [comment]
Yes, but these values are set by default. (I assume i get the default, if i run nvim -u NONE)

But I can reproduce what you get, if i do:

    :set listchars=
    :set list

**Comment by mtglsk** [comment]
Yes, those are the defaults. The thing is, many people like to see where are tabs and nbsp's in text and quite useful trails, but not EOL (which really clutter the whole display). As it stands it's impossible to differentiate between empty lines and normal new line chars.

**Comment by mseeber** [comment]
Ah, ok, I think I get it you want to do something like this:
http://vim.wikia.com/wiki/See_the_tabs_in_your_file
and it doesn't highlight the newlines anymore.

**Comment by Grimy** [comment]
I’m not sure why this is tagged “bug”. It looks like the intended behavior to me: highlight selected line endings by default, but not if the user removed `eol` from `list`.

> it's impossible to see selected empty lines without set listchars+=eol:$.

Yes it is. `set listchars+=eol:\ ` will highlight line endings when they are selected, without otherwise causing any visual pollution.

**Comment by justinmk** [comment]
Thanks @Grimy
