### ISSUE TITLE
"Nvim node.js host" not set properly showed in checkhealth:provider

### ISSUE THREAD

**Issue by nimser** [neovim/neovim#20638]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch linux

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

community/neovim

### How to reproduce the issue

type `checkhealth provider` in command mode.

### Expected behavior

No errors, "Nvim node.js host" get sets properly to the cli.js file.

### Actual behavior

"Nvim node.js host" is set to node's executable, which results in the following errors in `checkhealth provider`

```
## Node.js provider (optional)
  - INFO: Node.js: v16.14.2
  - INFO: Nvim node.js host: /home/owner/.nvm/versions/node/v14.15.0/bin/node
  - ERROR: Command error (job=12, exit code 1): `node '/home/owner/.nvm/versions/node/v14.15.0/bin/node' --version` (in '/home/owner')
    stderr: /home/owner/.nvm/versions/node/v14.15.0/bin/node:1ELF^SyntaxError: Invalid or unexpected token    at Object.compileFunction (node:vm:352:18)    at wrapSafe (node:internal/modules/cjs/loader:1032:15)    at Module._compile (node:internal/modules/cjs/loader:1067:27)    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.Module._load (node:internal/modules/cjs/loader:822:12)    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)    at node:internal/main/run_main_module:17:47
  - ERROR: Failed to run: node /home/owner/.nvm/versions/node/v14.15.0/bin/node --version
    - ADVICE:
      - Report this issue with the output of: 
      - node /home/owner/.nvm/versions/node/v14.15.0/bin/node --version

```

The output of `node /home/owner/.nvm/versions/node/v14.15.0/bin/node --version` is: 

```
/home/owner/.nvm/versions/node/v14.15.0/bin/node:1
ELF
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by nimser** [comment]
OK, this was misconfiguration from my part. I somehow had the line:

```vimscript
let g:node_host_prog = expand("~/.nvm/versions/node/v14.15.0/bin/node")
```
in my conf. I removed that and now all the checks are passing smoothly.

**Comment by simonward87** [comment]
I think there may still be a bug here. If `node_host_prog` is set (recommended in the docs to make startup faster), `checkhealth` apparently attempts to run `node path/to/node --version`, which fails (and would be expected to fail, as it isn't a valid command). If I don't set `node_host_prog`, and let Neovim search for the node executable itself (the default) – everything works fine. It's probably a simple fix – I'll have a look and see if I can find the line causing it.

**Comment by RageCPP** [comment]
I can add a little more detail
```bash
rage@ragecpp:~> whereis neovim-node-host
neovim-node-host: /home/rage/.local/share/pnpm/neovim-node-host
```
if you set `g.node_host_prog = "/home/rage/.local/share/pnpm/neovim-node-host"` when you run checkhealth you will still get error
```
  6 - Nvim node.js host: /home/rage/.nvm/versions/node/v20.12.2/bin/node
  5 - ERROR Failed to run: node /home/rage/.nvm/versions/node/v20.12.2/bin/node --version
  4   - ADVICE:
  3     - Report this issue with the output of:
  2     - node /home/rage/.nvm/versions/node/v20.12.2/bin/node --version
```
beacause `neovim-node-host` is bash file, you need run `cat neovim-node-host` file, you will see this line
```bash
...
exec node  "$basedir/global/5/node_modules/neovim/bin/cli.js" "$@"
...
```
you should replace `g.node_host_prog = "/home/rage/.local/share/pnpm/neovim-node-host"` to
`g.node_host_prog = "/home/rage/.local/share/pnpm/global/5/node_modules/neovim/bin/cli.js"`.

finally, run checkhealth again, you will see
```
Node.js provider (optional) ~
- Node.js: v20.12.2
  
- Nvim node.js host: /home/rage/.local/share/pnpm/global/5/node_modules/neovim/bin/cli.js
- OK Latest "neovim" npm/yarn/pnpm package is installed: 5.1.0
```
