### ISSUE TITLE
Neovim breaks in windows

### ISSUE THREAD

**Issue by batmikun** [neovim/neovim#20649]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-85-gb55742faf

### Vim (not Nvim) behaves the same?

Not installed

### Operating system/version

Windows 11

### Terminal name/version

Terminal -> Powershell 7

### $TERM environment variable

xterm-256color

### Installation

From development prereleases

### How to reproduce the issue

This is the config that I'm currently using [Config](https://github.com/batmikun/nvim_config/tree/main/nvim/nvim)

- Open nvim
- Run :PackerSync
- Open explorer with <space>v
- Move around the explorer open directories, and try to open a file [ any file, a lua file or svelte file or whatever ]
- There is a change that either neovim freezes and you have to close the terminal and open again
- or it will exit automatically and the terminal is gonna end up with part neovim part terminal

### Expected behavior

Open a file normally, and work good!

### Actual behavior

When I use any kind of file explorer 

![image](https://user-images.githubusercontent.com/47833971/195852760-7435cc59-18b4-4b12-bbf8-ebfba798ea7c.png)

And try to open a file, this happens 

![image](https://user-images.githubusercontent.com/47833971/195852885-afbaecda-83fb-41f8-8f4f-64d411583c08.png)

Also when I try to do

```console
nvim index.html
```

It opens and close immediately, no errors, no nothing.

I have the same config in mac, and it works fine, so it has to be a Windwos problem

**Comment by zeertzjq** [comment]
Can you provide the exact version from `nvim --version`?

**Comment by batmikun** [comment]
> Can you provide the exact version from `nvim --version`?

Updated!

**Comment by justinmk** [comment]
I don't see a "config" linked, and even so, we need minimal steps to reproduce the issue, not a pile of plugins.

**Comment by batmikun** [comment]
> I don't see a "config" linked, and even so, we need minimal steps to reproduce the issue, not a pile of plugins.
> 
> > When I use any kind of file explorer
> 
> Does `nvim --clean` with `:Ex .` work? (netrw)

I forgot to add text to the link my bad!. The config has 10 plugins I think. 

I use this one as base [Config](https://github.com/brainfucksec/neovim-lua)

And with the second question. Yes if I initialize nvim with not config it works.

So it's a plugin, is there any way I can debug neovim to pintpoint what plugin it is? Because the other issue I have is that it's frozes.

It's running perfectly fine and suddenly it frozes and i have to close the terminal

**Comment by batmikun** [comment]
I added how to reproduce the error!

**Comment by glepnir** [comment]
I can't reproduce it on my config . I don't think it's the neovim issue. you need create a min config to test , not provide a complete config it's hard to debug.
