### ISSUE TITLE
CMake error in PPA build for Ubuntu Precise

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2064]
[Build log](https://launchpadlibrarian.net/198772486/buildlog_ubuntu-precise-i386.neovim_0.0.0%2Bgit201502251005%2B1384%2B6%2B5~ubuntu12.04.1_BUILDING.txt.gz):

```
-- Performing Test HAS_OG_FLAG
-- Performing Test HAS_OG_FLAG - Failed
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:104 (set):
  Syntax error in cmake code at

    /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:104

  when parsing string

    ;/build/buildd/neovim-0.0.0+git201502251005+1384+6+5\~ubuntu12.04.1/.deps/usr/lib

  Invalid escape sequence \~
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:131 (_pkgconfig_set)
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:138 (_pkgconfig_invoke)
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:296 (_pkgconfig_invoke_dyn)
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  cmake/FindLibUV.cmake:14 (pkg_check_modules)
  CMakeLists.txt:177 (find_package)


-- Configuring incomplete, errors occurred!
make[2]: *** [build/.ran-cmake] Error 1
```

Doesn't seem to be a problem for the other Ubuntu versions (trusty, utopic, vivid), but I don't have time to investigate unfortunately. Ping @jszakmeister.

**Comment by jszakmeister** [comment]
This is a result of my fix to make sure the pkg-config files for our deps are being picked.  Apparently, CMake is upset about Launchpad building these packages that have a tilde in the path, and doesn't like the `\~` sequence that is in the name.  I'm not entirely sure what to do here.  Reverting the change is wrong, but we need to fix this somehow too. :-/  I've got work and martial arts today, so it'll probably be tomorrow before I can take a deeper look at it.

**Comment by jszakmeister** [comment]
I should add that it seems a bit odd to me that there's a leading `;` on the path.  It make it seem like it's being used as a list somehow when it's not, but that could be part of what `FindPkgConfig.cmake` does when putting together the paths.

**Comment by jszakmeister** [comment]
It looks like we're running up against this bug: https://bugs.freedesktop.org/show_bug.cgi?id=57078

pkg-config is escaping something that it shouldn't. :-(  I also think the CMake is probably a little overly strict too.  I'm still not quite sure what to do about it yet.  It's happening in a way that's hard to interject ourselves into. :-(

**Comment by jszakmeister** [comment]
Here's the patch that we need to somehow apply to CMake's FindPkgConfig.cmake:

```diff
--- a/FindPkgConfig.cmake
+++ b/FindPkgConfig.cmake
@@ -133,6 +133,10 @@ macro(_pkgconfig_invoke _pkglist _prefix
     string(REGEX REPLACE "[\r\n]"                  " " _pkgconfig_invoke_result "${_pkgconfig_invoke_result}")
     string(REGEX REPLACE " +$"                     ""  _pkgconfig_invoke_result "${_pkgconfig_invoke_result}")

+    # This is our modification to handle broken pkg-config output on Ubuntu
+    # Precise with Launchpad.
+    string(REPLACE       "\\~"                     "~" _pkgconfig_invoke_result "${_pkgconfig_invoke_result}")
+
     if (NOT ${_regexp} STREQUAL "")
       string(REGEX REPLACE "${_regexp}" " " _pkgconfig_invoke_result "${_pkgconfig_invoke_result}")
     endif()
```

I'm thinking that we may have to keep a copy of FindPkgConfig.cmake around that has this fix in it, and only bring it in if we know that either pkg-config is a broken version, or CMake doesn't already clean the output.  I worry about missing out on other fixes or incompatibilities if we take that approach though. :-(

**Comment by jszakmeister** [comment]
Another option could be that we write a wrapper pkg-config, and then use that with broken pkg-config executables to help ensure we get sanitized output.  I think we could probably use a simple shell script to do this.

**Comment by fwalch** [comment]
Hm.. Now that I think of it, to fix the PPA at least, we could add a version of libtool that doesn't have this bug to the repo.

**Comment by jszakmeister** [comment]
@fwalch Oooh, that's an interesting idea.  BTW, it's pkg-config that's broken here, not libtool.  I just wanted to point that out so you don't waste your time with the wrong thing. :-)

**Comment by fwalch** [comment]
Thanks, don't know why I confused that. I'll try adding an updated pkg-config to the repo later on.

**Comment by jszakmeister** [comment]
It looks like the bug mentioned above was fixed in pkg-config 0.28.  So that would be the version to shoot for.

**Comment by fwalch** [comment]
Trusty has pkg-config 0.26, but the bug is manually patched out. So I'll use that version (0.26-1ubuntu4) and try to get a backport from trusty to precise :-)

**Comment by fwalch** [comment]
Backported into https://launchpad.net/~fwalch/+archive/ubuntu/pkg-config and added as dependency to the Neovim PPA.

**Comment by fwalch** [comment]
Seems to work. Thanks for tracking down the error and providing all this information, @jszakmeister!

**Comment by jszakmeister** [comment]
You're welcome!  Happy to help!
