### ISSUE TITLE
`cmdheight=0` causes statusline to be duplicated when scrolling down with `<C-e>` or mouse scroll wheel

### ISSUE THREAD

**Issue by mrjones2014** [neovim/neovim#20653]
### Neovim version (nvim -v)

NVIM v0.8.0 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS 12.6

### Terminal name/version

kitty 0.26.2

### $TERM environment variable

`xterm-kitty`

### Installation

homebrew

### How to reproduce the issue

1. Have a file with enough lines that it is scrollable
2. `:set cmdheight=0`
3. `<C-e><C-e><C-e><C-e><C-e><C-e><C-e><C-e><C-e><C-e><C-e><C-e>`

### Expected behavior

Statusline is not affected

### Actual behavior

Statusline is duplicated upwards. Interestingly, scrolling with `<C-d>` does _not_ cause the issue. Pressing `<Esc>` or changing mode in any way will "reset" the statusline back to normal.

![image](https://user-images.githubusercontent.com/8648891/195899936-f2c98a44-1edc-472e-9515-a5ad9fdb3d9b.png)

**Comment by mrjones2014** [comment]
This is reproducible both in and not in tmux.

**Comment by zeertzjq** [comment]
I cannot reproduce in either v0.8.0 or HEAD. Did you reproduce with `--clean`?

**Comment by Shougo** [comment]
The screenshot seems not minimal init.vim.
Please test it without plugins.

**Comment by mrjones2014** [comment]
Hm, I was able to before on my work computer, but now I'm not able to on my personal one. I'll reopen if I figure out how to reproduce consistently.

**Comment by mrjones2014** [comment]
Just FYI I was able to reproduce, but it seems already fixed on nightly 👍 🙂
