### ISSUE TITLE
CR will reponse what C-m maps when CR is not maped

### ISSUE THREAD

**Issue by yehuohan** [neovim/neovim#20654]
### Neovim version (nvim -v)

v0.8.0-1210-gd367ed9b2

### Vim (not Nvim) behaves the same?

vim doesn't have this feature

### Operating system/version

windows 10

### Installation

nvim-win64.zip

### How to reproduce the issue

**Test with mini config**:

```
nnoremap <C-m> <Cmd>echo 'c-m'<CR>
```

- press `CR`: 'c-m' is displayed
- press `C-m`: 'c-m' is displayed

**But test with**:

```
nnoremap <C-m> <Cmd>echo 'c-m'<CR>
nnoremap <CR> <Cmd>echo 'cr'<CR>
```
- press `CR`: 'cr' is displayed
- press `C-m`: 'c-m' is displayed

### Expected behavior

`CR` won't reponse what `C-m` maps to. (By the way, nvim 0.7.2 doesn't has this issue. If this behaviour is a change in nvim 0.8.0, please let me know and I'll closs this issue)

### Actual behavior

CR dose reponse what C-m maps to.

**Comment by ii14** [comment]
In most terminals `<CR>` and `<C-M>` are equivalent by default, and in the past vim couldn't distinguish between the two. Neovim now can, but to keep the previous behavior both of those keys get remapped if you map only one of them. (someone correct me if I'm wrong)

Try `nnoremap <CR> <CR>` if you want to keep the default `<CR>` behavior.

**Comment by zeertzjq** [comment]
Yes and Vim's behavior is the same.
