### ISSUE TITLE
LSP client provides bogus capabilities in CodeActionKind

### ISSUE THREAD

**Issue by dimbleby** [neovim/neovim#20657]
### Neovim version (nvim -v)

v0.9.0-dev-96-ge6f7e038b

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ubuntu

### Terminal name/version

tmux

### $TERM environment variable

xterm-256color

### Installation

build from source

### How to reproduce the issue

fire up a language server, look at debug logs, note this among the values on the 'initialize' message:
```
...
 codeActionKind = {              valueSet = { "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }
...
```

### Expected behavior

only the values from the `CodeActionKind` table should be presented, not also the keys.

### Actual behavior

as above.

I found a server that is strict about rejecting invalid values, it doesn't like what the neovim client is doing here.

```
:echo luaeval('vim.tbl_values(vim.lsp.protocol.CodeActionKind)')
['refactor.extract', 'RefactorExtract', 'refactor.inline', 'RefactorInline', 'refactor.rewrite', 'RefactorRewrite', 'source', '
source.organizeImports', 'QuickFix', 'SourceOrganizeImports', 'Source', 'Empty', '', 'quickfix', 'refactor', 'Refactor']
```

because https://github.com/neovim/neovim/blob/e6f7e038b8bbca487e78ebfc6fe21d6852330623/runtime/lua/vim/lsp/protocol.lua#L299-#L303 presumably

suggested fix

```patch
index 403475332..7442c8f00 100644
--- a/runtime/lua/vim/lsp/protocol.lua
+++ b/runtime/lua/vim/lsp/protocol.lua
@@ -637,7 +637,7 @@ function protocol.make_client_capabilities()
         codeActionLiteralSupport = {
           codeActionKind = {
             valueSet = (function()
-              local res = vim.tbl_values(protocol.CodeActionKind)
+              local res = vim.tbl_values(constants.CodeActionKind)
               table.sort(res)
               return res
             end)(),
```

**Comment by mfussenegger** [comment]
Could you create a PR?

**Comment by dimbleby** [comment]
if you promise I'm not going to get sucked into rounds of "you've broken the unit test", "please add a new unit test", "please do a similar thing in these similar places", ... sure!

**Comment by dimbleby** [comment]
(fwiw I suspect the code could be cleaned up by making an analogous fix when setting up the `completionItemKind` value set, also `symbolKind` (twice); and it's not clear to me why the completion items are sorted but the others are not.  But this is exactly the sort of thing I prefer to leave to maintainers to worry about)
