### ISSUE TITLE
setcmdline() has no effect

### ISSUE THREAD

**Issue by trmckay** [neovim/neovim#20661]
### Neovim version (nvim -v)

NVIM v0.8.0

### Vim (not Nvim) behaves the same?

no, v9.0.217, appears to not have this function

### Operating system/version

macOS 12.6

### Terminal name/version

iTerm2 3.5.0beta7

### $TERM environment variable

xterm-256color

### Installation

Homebrew

### How to reproduce the issue

```
nvim --clean -c "call setcmdline('test')"
```

Same issue when calling from a binding.

### Expected behavior

The help states:

```
setcmdline({str} [, {pos}])					*setcmdline()*
		Set the command line to {str} and set the cursor position to
		{pos}.
		If {pos} is omitted, the cursor is positioned after the text.
		Returns 0 when successful, 1 when not editing the command
		line.

		Can also be used as a |method|:  
			GetText()->setcmdline()
```

I am expecting this to set the command line and enter command mode, i.e. `call feedkeys(':grep')` and `call setcmdline('grep')` are equivalent.

### Actual behavior

Nothing happens.

**Comment by trmckay** [comment]
If someone can confirm that this is actually a bug I am happy to take this on.

**Comment by zeertzjq** [comment]
As documented, this only works when editing the command line.

**Comment by trmckay** [comment]
> As documented, this only works when editing the command line.

Thanks for the clarification! Is there a reason for this limitation?

**Comment by Shougo** [comment]
Because other command line functions are same behavior and they are not safe if called from outside of command line mode.
