### ISSUE TITLE
add an option to hide the tilde sign on blank lines

### ISSUE THREAD

**Issue by timfeirg** [neovim/neovim#2067]
Dear developers,

I never liked the tilde sign on blank lines that the old vim has been doing, can you add an option so we're finally able to get rid of it? So that there's chance we can display pure code on screen?

![](http://i.stack.imgur.com/zZ6uX.png)

**Comment by fmoralesc** [comment]
Already got you covered (with #1926). Try out

      hi! EndOfBuffer ctermbg=bg ctermfg=bg guibg=bg guifg=bg

**Comment by timfeirg** [comment]
@fmoralesc thanks for the quick response, I've tried setting `bg` and `fg`s before, the tilde sign just get a little darker but it didn't go away, I think it'd has something to do with [solarized](https://github.com/altercation/vim-colors-solarized).

this is how it looks before and after:

![_mosh__vi_before](https://cloud.githubusercontent.com/assets/4319104/6411632/5c61b8f2-beb5-11e4-8dd7-b625e143f42b.png)

after:
![_mosh__fg](https://cloud.githubusercontent.com/assets/4319104/6411633/617acb30-beb5-11e4-800c-baf12e2e9591.png)

**Comment by fmoralesc** [comment]
Did you try adding the 'hi' rule to the solarized colorscheme? It might be overwriting it.

**Comment by jszakmeister** [comment]
I generally override a colorscheme's settings using an autocmd:

```vim
function! AdjustSolarized()
     hi! EndOfBuffer ctermbg=bg ctermfg=bg guibg=bg guifg=bg
endfunction

augroup solarized_colors
    autocmd!
    autocmd ColorScheme solarized call AdjustSolarized()
augroup END
```

Note: I've not tested the above, but it should get you close.  Of course, you'll need this in place when you set the colorscheme.

**Comment by mtglsk** [comment]
NonText should be left as it was, imho, because now every theme that worked around the tilde with fg and bg being the same for NonText, will not work afaik.

**Comment by justinmk** [comment]
Try @jszakmeister suggestion. EndOfBuffer is the solution.

**Comment by timfeirg** [comment]
I tried, I put the function and augroup in my nvimrc and restart, the result is no different from using the `hi` command, the tilde just gets a little darker, here's before and after
![vi](https://cloud.githubusercontent.com/assets/4319104/6424828/14e98a10-bf44-11e4-84ea-72b4a7ebc63f.png)

@justinmk @jszakmeister

**Comment by justinmk** [comment]
@timfeirg Try a different colorscheme.

**Comment by justinmk** [comment]
@timfeirg Actually just run this command directly in your `:` prompt:

    hi EndOfBuffer ctermbg=bg ctermfg=bg guibg=bg guifg=bg

Then what happens?

**Comment by TyOverby** [comment]
Has anyone actually managed to get the `~`s to disappear?  I can set them to whatever color I want, but trying to make them transparent with `ctermfg=None` just makes them white.  Doing  `set bg=dark` followed by `ctermfg=bg` simply changes the color to be darker than usual.

**Comment by justinmk** [comment]
@TyOverby `:hi EndOfBuffer ctermfg=bg` works for me...

**Comment by TyOverby** [comment]
It's easier to see on a window with transparency

<img width="195" alt="screen shot 2016-03-07 at 12 33 52 pm" src="https://cloud.githubusercontent.com/assets/573215/13582377/e1a1e1a0-e460-11e5-8178-e9970b8dede0.png">

**Comment by justinmk** [comment]
@TyOverby The foreground color isn't affected by the transparency feature of your terminal. There's not really anything we can do about that.

**Comment by TyOverby** [comment]
I'm very new to styling customization, but if `ctermfg=None` worked, wouldn't it solve this by simply refusing to paint a foreground character?

**Comment by justinmk** [comment]
@TyOverby Seems like it should. Maybe a new feature request for the `:highlight` command.

**Comment by ndarilek** [comment]
Are all of these solutions just changing the ~ color instead of making it go away entirely?

I'm a blind screen reader user. When I scroll through mostly empty files and reach the end, my screen reader says "tilde tilde tilde..." quite a bit in some instances. I don't want to just change the color, which would just leave the tilde in place. A brief bit of research for regular Vim suggests these can't be disabled. Any chance for a true disabling in Neovim?

**Comment by ZyX-I** [comment]
@ndarilek I am wondering what screen reader will do in case tilde is replaced with space? One of the solutions proposed in some issue was to add &fillchars suboption that allows replacing tilde with something else including space to make it “go away”.

**Comment by ZyX-I** [comment]
Specifically #4181 (BTW, @justinmk why it stays closed?).

**Comment by ndarilek** [comment]
Yeah, I think that might work but can't say for sure.

**Comment by justinmk** [comment]
> Specifically #4181 (BTW, @justinmk why it stays closed?).

Not sure, I think I was expecting a PR. Reopened.

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/blob/ebb1acb3c083e63667c3606233a496b11d3faa83/src/nvim/screen.c#L1555

I won't expect making it a `fillchars` option (#4181) should be too complicated.

**Comment by fmoralesc** [comment]
That is what https://github.com/neovim/neovim/pull/6351 tried to do, was 
it not?

**Comment by bfredl** [comment]
Yes, some unresolved commends there with no reply. I guess it is up for grabs for someone to rebase and fix the remaining tests.

**Comment by justinmk** [comment]
Yep, still waiting on https://github.com/neovim/neovim/pull/6351#issuecomment-290283807

**Comment by audunolsen** [comment]
Ah, well I got a file and a line number, so I'm satisfied. Thanks! 👍

**Comment by bfredl** [comment]
fixed by #8546

**Comment by coder123123** [comment]
I second this as I also want an easy way to remove the tilde permanently in Vim. Guessing there are many other users who don't want it there and suggesting perhaps even disabling it by default. Why should it be there if Nano for example does not need to display the tilde? Get rid of it altogether preferably. If you cannot accept that, then at least make it as easy as possible to hide it.

**Comment by chrisbra** [comment]
> I second this as I also want an easy way to remove the tilde permanently in Vim

Then use the suggested `:hi EOB ...` highlighting. That should also work in normal Vim.

**Comment by bfredl** [comment]
In nvim master there is also  `set fcs=eob:\ ` (backslash whitespace)

**Comment by stu-b-doo** [comment]
@bfredl 's method of fcs=eob worked for me on my Windows version but on Linux I get the following error: 
`E474: Invalid argument: fcs=eob:\ `
I suspect it's a version difference. Any idea how to go about figuring out which versions work/don't work??

**Comment by nhooyr** [comment]
To avoid trailing whitespace you can also do:

```viml
let &fcs='eob: '
```

**Comment by sebasruiz09** [comment]
para ocultarlos en nvim con archivo lua (Nvim 0.5+)
`vim.wo.fillchars='eob: '`
