### ISSUE TITLE
Meta (alt) key combinations not working in insert mode

### ISSUE THREAD

**Issue by critiqjo** [neovim/neovim#2068]
Meta-key combinations in insert mode produces latin characters. For example:
<kbd>Alt</kbd>+<kbd>a</kbd> produces `á`
But in normal mode, I'm able to get Meta-mappings to work.
Meta key worked as expected in insert mode until 6383ea6e8e14350432f1fc7da519b54d0ed67f8c
I wasn't able to test the very next commit (e0e41b30c61922e099a067ac5c137e745699a1aa), because it failed to run in my system. But the commit after that (9a2dd7c4987679106fba24fb7702a11aba6b6ccf) showed the same behavior as explained above.

Current version: 6b7ece6cc89aa35f99d6bd3c078114a7a8a2daa1
Terminal emulators tried: urxvt, gnome-terminal
OS: Arch Linux

**Update:** Tested more commits.

**Comment by strokirk** [comment]
I can confirm this issue. Pressing `å` on a Swedish keyboard in insert mode produces the same output as Alt-e. This is a problem for me, since many plugins use Meta-mappings by default, which occasionally hinders me from typing Swedish text.

**Comment by blueyed** [comment]
This is a general terminal issue (and is the same in Vim (terminal), isn't it?)

See `MySetupAltMapping` and its use in https://github.com/blueyed/dotfiles/blob/master/vimrc#L3258-L3283.  With this, you can then add mappings like `<A-e` or `<M-e>`.

**Comment by strokirk** [comment]
@blueyed No, this problem does not exist in vim. Pressing <kbd>å</kbd> produces an `å` character, like expected.

**Comment by fwalch** [comment]
Ping @tarruda

**Comment by critiqjo** [comment]
Searching around, it seems this can't be resolved. The eighth bit set by the alt key cannot be distinguished from that of normal UTF-8 characters. And the other way is for alt key to be processed as a prefixed esc key. Both are kinda hackish ways of dealing with it, unfortunately inherent to the current implementation of terminal emulators (or consuming input in shell), I think. Close the issue?
Ref: http://vim.1045645.n5.nabble.com/insert-mode-map-alt-keys-and-8-bit-locales-td1200710.html

**Comment by Pyrohh** [comment]
> unfortunately inherent to the current implementation of terminal emulators (or input consumption by shell), I think. Close the issue?

Yes indeed, as these mappings work fine using pangoterm.

**Comment by blueyed** [comment]
With the new use of `libtermkey` this should be possible / better now: http://neovim.org/doc/user/vim_diff.html#nvim-features-new

(via http://neovim.org/news/2015/april/)

**Comment by strokirk** [comment]
@Pyrohh So Swedish users using other terminals should just be left in the open?

**Comment by critiqjo** [comment]
It is possible to manually map, for example, \<M-j\> in any mode (urxvt, gnome-terminal and xterm).
But, if what you want vim-like behaviour (all meta combinations are treated as Esc prefixed keys), you have to map everything manually (which is not a big deal, btw)

**Comment by Pyrohh** [comment]
Do you mean to say that the whole Swedish alphabet must be mapped to work "normally", e.g.

```inoremap <M-[en alphabet] [swe alphabet]```

**Comment by critiqjo** [comment]
No! What I mean is that the following works fine:
```
inoremap <M-j> <Esc>j
```
which will give you vim-like behaviour for \<M-j\> in insert mode...
Sorry for the confusion.

**Comment by Pyrohh** [comment]
Ah, my mistake.

**Comment by wrigleyster** [comment]
I was having trouble with the `å` key because `<M-e>` produces `å`, so I remapped the keybinding from `<M-e>` to `<M-å>`, and now both `e` and `å` work as well as the keybinding. But if Meta simply toggles the 8th bit, how can this be?

**Comment by acornejo** [comment]
seems its now being tracked in #2440
