### ISSUE TITLE
Copying selection from one file to a global mark in another file does not work

### ISSUE THREAD

**Issue by Piotr1215** [neovim/neovim#20686]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1202-g33dd917d7

### Vim (not Nvim) behaves the same?

Vim has the same issue, version VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 13 2022 09:35:02)

### Operating system/version

Pop!_OS 22.04 LTS x86_64

### Terminal name/version

alacritty 0.10.1-rc1

### $TERM environment variable

xterm-256color

### Installation

appimage

### How to reproduce the issue

1. Open file1 and file2
2. Fill with some data
3. Create global mark in file1
4. Copy all form file2 to file 1

nvim --clean
:e file1
:vsp: file2
:windo r !seq 10
GmA
C-w l
ggVG
:marks -- make sure mark is set
:'<,'>t 'A

### Expected behavior

Selection from file1 copied to the global A mark of file2.

### Actual behavior

Nothing happens and error `E20: Mark not set`

**Comment by seandewar** [comment]
Moreso a limitation of `:move` and `:copy` than a bug.
They're hardcoded to work on curbuf, and as such, only accept uppercase mark `{address}`es referring to curbuf.

Would potentially be a nice enhancement.

**Comment by Piotr1215** [comment]
Closing as it's not a bug.
