### ISSUE TITLE
E903: Process failed to start: Function not implemented: "C:\Windows\system32\cmd.exe"

### ISSUE THREAD

**Issue by eeriemyxi** [neovim/neovim#20682]
### Neovim version (nvim -v)

NVIM v0.8.0-1210-gd367ed9b2; Build type: RelWithDebInfo; LuaJIT 2.1.0-beta3; Compiled by runneradmin@fv-az177-603.

### Vim (not Nvim) behaves the same?

No, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 28 2022 13:10:49).

### Operating system/version

Windows 10 Pro, 1803.

### Terminal name/version

Command Prompt.

### $TERM environment variable

Not found.

### Installation

I went to Releases tab of this repository and downloaded nvim-win64, 0.8.0.

### How to reproduce the issue

nvim --clean
:terminal
`E903: Process failed to start: Function not implemented: "C:\Windows\system32\cmd.exe"`

### Expected behavior

For `nvim --clean` to be like `vim -u DEFAULTS` when I execute `terminal` command:
![image](https://user-images.githubusercontent.com/86738916/196045450-6ac375e2-92b9-41c5-97a0-f12c62b54dac.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/86738916/196045490-5c810161-75b7-4e7d-b556-c68bde4c5ac1.png)

**Comment by dundargoc** [comment]
Hmm. Is it possible to check if this happens with older versions of neovim?

**Comment by eeriemyxi** [comment]
> Hmm. Is it possible to check if this happens with older versions of neovim?

Like, as in 0.7.0? Or much older?

**Comment by dundargoc** [comment]
Test 0.7.0. If that doesn't work either then test 0.6.0 etc. If we can pinpoint when this stopped working it'll be much faster to fix this :)

**Comment by eeriemyxi** [comment]
> Test 0.7.0. If that doesn't work either then test 0.6.0 etc. If we can pinpoint when this stopped working it'll be much faster to fix this :)

I downloaded 0.6.0, but the installer is not letting me to install it because I already one installed, what can I do to preserve my configurations and install that version?

**Comment by dundargoc** [comment]
Hmm, I'm not familiar enough with that to answer for sure. Let's skip what I said then to be on the safe side.

**Comment by justinmk** [comment]
duplicate https://github.com/neovim/neovim/issues/20458
