### ISSUE TITLE
nvim_cmd: vim.cmd.win_getid(...) invokes :winsize (resizes the editor)

### ISSUE THREAD

**Issue by MaxVerevkin** [neovim/neovim#20681]
### Steps to reproduce the issue

    :lua vim.cmd.win_getid(30,10)

API equivalent:

    :lua vim.api.nvim_cmd({cmd='win_getid', args={30,10}}, {})

### Expected behavior

Call `win_getid()` vimscript function.

### Actual behavior

The editors resizes. Resizing the terminal restores the correct size.

**Comment by seandewar** [comment]
Looks like it's being interpreted as `:win[size] 30 10`.
This should be an error. Sounds like you wanted to use `vim.fn.win_getid(30, 10)`.

**Comment by zeertzjq** [comment]
It seems there are several cases to consider:
1. A builtin command matches but there are trailing non-alphanumeric characters
2. A builtin command matches but there are trailing digits
3. A user command matches but there are trailing non-alphanumeric characters
4. A user command matches but there are trailing digits

Should `CmdUndefined` be trigger in cases 3 and 4? Or maybe only in case 4?

**Comment by justinmk** [comment]
Haven't tried it, but perhaps we can simply reject any `cmd` if `find_ex_command` treats any part of it as args. We don't support whitespace-delimited `cmd`, right?
