### ISSUE TITLE
splitkeep=screen interferes with c-u and c-d scrolling in floating windows

### ISSUE THREAD

**Issue by jemag** [neovim/neovim#20684]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-109-g0b71960ab

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch Linux 5.19.13-arch1-1

### Terminal name/version

wezterm 20221004-190909-eefd57b8

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

Since this behavior only happens in floating windows, I created the following minimal_init.lua to reproduce the issue and allow starting floating windows easily:
```lua 
local on_windows = vim.loop.os_uname().version:match("Windows")
-- vim.api.nvim_command("!rm -rf /tmp/nvim")

local function join_paths(...)
  local path_sep = on_windows and "\\" or "/"
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
  vim.cmd([[ syntax off]])
  vim.g.ts_highlight_lua = true
  require("packer").init({
    package_root = package_root,
    compile_path = compile_path,
  })
  require("packer").startup({
    function(use)
      use({ "wbthomason/packer.nvim" })
      use({
        "voldikss/vim-floaterm"
      })
      use({
        "akinsho/toggleterm.nvim",
        tag = "*",
        config = function()
          require("toggleterm").setup()
        end,
      })
    end,
  })
end

_G.load_config = function()
  vim.api.nvim_set_keymap("t", "<c-o>", [[<C-\><C-n><esc><cr>]], { noremap = true, silent = true })
  vim.opt.splitkeep = "screen"
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
  load_plugins()
  require("packer").sync()
else
  load_plugins()
  require("packer").sync()
  _G.load_config()
end
```

Steps:
1- Open nvim with : `nvim -u minimal_init.lua test.txt`. (will need to open twice)
2- Create a floating window using either `ToggleTerm direction=float` or `FloatermNew`
3- Spam content in window for scrolling (e.g.: spam a command like `lsblk --help`)
4- Go into the terminal normal mode
5- Scroll using `<C-u>` and `<C-d>` 
6- Notice that it scrolls 1 line at a time

### Expected behavior

`<C-u>` and `<C-d>` scroll half page

### Actual behavior

`<C-u>` and `<C-d>` scroll one line at a time

**Comment by luukvbaal** [comment]
I'll look into it.

**Comment by luukvbaal** [comment]
I wonder why the `window.c:win_comp_scroll()` call is tied to `scroll_to_fraction()`. In my mind it would make more sense to move to `win_set_inner_size()`, that way we wouldn't need it in the `'splitkeep' != "cursor"` code path and I think would resolve this issue. I'll see if I can find any issues/regressions with that approach.
