### ISSUE TITLE
Add "runtime" healthcheck

### ISSUE THREAD

**Issue by clason** [neovim/neovim#20696]
### Feature already in Vim?

N/A

### Feature description

We should add a dedicated "runtime" section in `health#nvim#check`. This could/should

1. list the current value of `$VIMRUNTIME`
2. warn if outdated vimscript files are found: `man.vim` (moved from `man.health.check()`),  `filetype.vim`,  `scripts.vim`, ...
3. ?

**Comment by justinmk** [comment]
This should be a single item in the `nvim` healthcheck. Don't need an entirely new section, that is noisy. The man.vim check can also be checked here rather than having an entire "man.vim" section.

**Comment by clason** [comment]
Yes, that was exactly what I meant with `health#nvim#check` (rather than `:checkhealth`) and "moving from `man.health.check` (which then would be empty).
