### ISSUE TITLE
ui: not redraw screen after run highlight command or call nvim_set_hl to change the  float window background

### ISSUE THREAD

**Issue by glepnir** [neovim/neovim#20695]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-114-g9701c9dc9-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos 12.6

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

brew 

### How to reproduce the issue

- nvim --clean -u min.lua

```
local bufnr = vim.api.nvim_create_buf(false, true)
local winid = vim.api.nvim_open_win(bufnr, true, {
  width = 50,
  height = 2,
  relative = 'cursor',
  row = 5,
  col = 22,
  border = "double",
})

vim.api.nvim_win_set_option(winid, "winhl", "Normal:TestNormal")
```
- run `lua vim.api.nvim_set_hl(0, 'TestNormal, {bg = '#ffffff'})` or `hi TestNormal guibg=#ffffff`

### Expected behavior

change the floatwindow background

### Actual behavior

not work

**Comment by przepompownia** [comment]
With the current master 7718241286315a8099427d42cb83c6532d87a390 and the recent nvim-qt please run 
```sh
nvim-qt --nvim ~/tmp/nvim-from-src/bin/nvim -- -u NONE
```
and inside
```vim
hi Normal guibg=#334455
```
Only one bottom line gets the new background directly after submitting this command
![image](https://user-images.githubusercontent.com/11404453/197397023-f07afd5e-9504-451e-8285-52a11a6694a6.png)
and `<C-l>` is needed to apply the new background on the whole screen. I'm not sure if it's the same bug as mentioned by @glepnir My above case is simple to reproduce but I also encounter outdated cursor position or entered text (until window leave and go back on Wayland) and am still unable to provide as simple example as this.
