### ISSUE TITLE
A background color of floating windows is purple, not black.

### ISSUE THREAD

**Issue by flavono123** [neovim/neovim#20698]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no, 9.0.1-700

### Operating system/version

macOS 12.6

### Terminal name/version

iTerm2(Build 3.4.16), tmux 3.3a

### $TERM environment variable

tmux-256color

### Installation

Homebrew

### How to reproduce the issue

With my [configs](https://github.com/flavono123/dotfiles/tree/master/neovim/.config/nvim)(you can install easily with `stow` following the [REAME](https://github.com/flavono123/dotfiles#installuninstall)), the colors of floating(preview) windows from fzf or mason are purple(maybe inverted?)
- `,p` to open fzf window
- `:Mason` to open mason UI

### Expected behavior

A black background like in Vim([configs](https://github.com/flavono123/dotfiles/tree/99fe67f9d4ca02422dd9c9e7c29e615ee3d05e71/vim)):

![image](https://user-images.githubusercontent.com/20619567/196147792-75c9e2cf-8511-406e-b4e0-dfd4a05b54c3.png)

### Actual behavior

A purple background:
![image](https://user-images.githubusercontent.com/20619567/196148014-ad96598a-bb05-4cd4-9a4a-8de77038766d.png)

**Comment by justinmk** [comment]
what is the bug? Nvim is not Vim. By default we use `Pmenu` highlight for floating windows, this is mentioned in `:help api-floatwin`.

**Comment by clason** [comment]
@justinmk This is a change in Nvim 0.8.0 that's been reported multiple times before. It would be nice to have a neutral explanation of this change in one of these issues rather than just closing them so we can mark others as duplicate.

**Comment by bfredl** [comment]
It is not a change, but has always been the case. The relevant issue would be "better default color scheme"

**Comment by flavono123** [comment]
OK. I can fix it, to be same to Vim, with `hl link NormalFloat Normal`.

**Comment by thalesmello** [comment]
@justinmk @bfredl 

> The relevant issue would be "better default color scheme"

Sorry if this is a naive question, but could you elaborate on why Pmenu is a "better default" for floating windows?

**Comment by bfredl** [comment]
@thalesmello this issue is from before the new color scheme which did ship in 0.10 and no longer relevant
