### ISSUE TITLE
core dump: ui_compositor.c:453 compose_line endcol <= chk_width failed

### ISSUE THREAD

**Issue by jemag** [neovim/neovim#20691]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-109-g0b71960ab

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch Linux 5.19.13-arch1-1

### Terminal name/version

wezterm 20221004-190909-eefd57b8 + tmux

### $TERM environment variable

screen-256color

### Installation

build from repo

### How to reproduce the issue

This one is intermittent and fairly random, so quite hard to reproduce (might happen a couple times per day so far). However it seems to always happen whenever I go from a smaller tmux pane to fullscreen.

Here is the error:
![image](https://user-images.githubusercontent.com/7985687/196080788-4ef1dd36-d669-4c0f-b33b-ffb3733dc168.png)
Full backtrace:
https://gist.github.com/b3990d3205ceef371d21cc6b18d3b721

### Expected behavior

No crash

### Actual behavior

Crashes

**Comment by zeertzjq** [comment]
I suspect this is caused by https://github.com/neovim/neovim/commit/cce0840cbfc3c4ee9ae1d3fc9b283d557d0204ab

**Comment by jemag** [comment]
Haven't been able to make a minimal reproduction so far. However, I was able to catch an example of the workflow that sometimes cause it to happen. Hopefully it can help clarify my original message. Basically it seems to be when I am changing the dimension of a Tmux pane, and often seems to happen when there are a lot happening in the UI (including potentially one or more floating windows).

Here I am just starting a typescript project, triggering fidget UI, then creating a floating minimap to add more to said UI, and switching pane to fullscreen:

https://user-images.githubusercontent.com/7985687/196320855-61e919d6-bbde-4301-ad0c-44161c31eadf.mp4

**Comment by jemag** [comment]
Built Neovim using commit 28e228d60dc1120a56be8757ddf7bc0deedf71da (which is 2 commits prior to the aforementioned cce0840cbfc3c4ee9ae1d3fc9b283d557d0204ab).

I have not been able to  trigger a core dump with that Neovim version (NVIM v0.9.0-dev-30-g28e228d60). I will continue using that version for a while, but it might indeed be related to commit cce0840cbfc3c4ee9ae1d3fc9b283d557d0204ab or at least commits beyond 28e228d60dc1120a56be8757ddf7bc0deedf71da.

**Comment by zeertzjq** [comment]
Does this crash exist on latest HEAD?

**Comment by jemag** [comment]
I will test around this week-end using latest. I was on the old commit these last few days since I needed a stable environment for work.

**Comment by jemag** [comment]
Tested and couldn't make it crash with latest. If I use commit 90138d5ed87cc8dde49ee74e422a5de2191a3f76 (the one right before 2f9b94a26836ecb081c717e23913f5b6576cce99), then it will crash again.

So your commit 2f9b94a26836ecb081c717e23913f5b6576cce99 seems to be fixing the issue for me.

Thanks a lot @zeertzjq !
