### ISSUE TITLE
Cannot use <C-R> to redo when remapping 'R' with langmap

### ISSUE THREAD

**Issue by Dettorer** [neovim/neovim#20705]
### Neovim version (nvim -v)

v0.8.0, introduced in commit 7029b4b44a1cea58af3f54a4d62757b29a8e6aeb

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

archlinux

### Terminal name/version

alacritty 0.12.0-dev (269b6e3d)

### $TERM environment variable

alacritty

### Installation

package manager, also tested and git-bisected from the repo

### How to reproduce the issue

```
nvim --clean
:set langmap=RL
ia<ESC>u<C-R>
```

### Expected behavior

The buffer contains a single character: 'a' (which was inserted, then undone, then redone).

### Actual behavior

The buffer doesn't contain anything.

**Comment by Dettorer** [comment]
I first observed the issue when I updated my system a few weeks ago. Today I reproduced it on the current master, then used git bisect to find the first commit that had this problem and found it to be 7029b4b44a1cea58af3f54a4d62757b29a8e6aeb. During bisect however I tested with `./fake_install/bin/nvim -u weird-langmap.vim`, with `weird-langmap.vim` containing only the line `set langmap=RL`.

I know langmap is usually used to map non-ascii characters from various countries keyboards to the qwerty ones, but I use it to remap my entire keyboard from bépo (a french dvorak-like) to qwerty, so the mapping is almost exclusively ASCII->ASCII (see [the relevant line in my actual config](https://bitbucket.org/Dettorer/configuration/src/1be23520eef739712d525b5dca5976aac3cbc374/config/nvim/bepo.vim#lines-5)).

**Comment by Dettorer** [comment]
The commit I identified with git bisect was merged via this PR: https://github.com/neovim/neovim/pull/17932. I do not fully understand it yet but it might suggest that the correct way of doing what I want to do simply changed. If I find a way to adapt my configuration to restore the `<C-R>` behavior I'll close this issue and mention the fix.

**Comment by zeertzjq** [comment]
It seems that this can also be reproduced in Vim with the following two conditions:
1. Vim is run inside XTerm
2. `<C-L>` is mapped in Normal mode

Meanwhile, in Nvim this doesn't happen if you remove the default `<C-L>` mapping.

**Comment by zeertzjq** [comment]
I've report this to Vim in https://github.com/vim/vim/issues/11395

**Comment by Dettorer** [comment]
Thanks a lot! I confirm that the PR fixes the issue I had, even with my full config.
