### ISSUE TITLE
RPC calls trigger redraws

### ISSUE THREAD

**Issue by carlosdcastillo** [neovim/neovim#2070]
Under what circumstances does .nvimlog get the following line:

2015/02/27 23:18:23 [error @ call_set_error:727] 97577 - Msgpack-RPC error: Channel was closed by the client

I'm not calling ui_detach or disconnect or anything. Also the file .vimlog is multiple GB in size, repeating the same line, several times per second. The client works, but the server keeps printing that to file.

**Comment by carlosdcastillo** [comment]
OK. Here is information for a better bug report:

Each time I send a message to Neovim I do so in a new socket - but I did not think I was sending an infinite amount of messages, definitely not 50 times per second.

The problem is this: I'm trying to call with `vim_eval` the following commands: 
    
    expand('%:p')  

and then in another line a `vim_eval` of
  
    line('$')

and these two things are triggering a screen redraw. Since I need that information for redrawing it is an infinite recursion.

I dug into eval.c and vim_eval and it wasn't clear to me why the redraw. Not sure if you could help me troubleshoot this. If you can point me in the correct direction I'm hopeful I can solve this one myself.

Thanks!

**Comment by justinmk** [comment]
API has `buffer_line_count()`. Why is `expand('%:p')` needed for your redraw calculation?

> I dug into eval.c and vim_eval and it wasn't clear to me why the redraw.

It does seem inefficient, could be an optimization. Other possibility is that something in the eval_expr chain is concluding that our vim_eval call was user-initiated (e.g. at the cmdline), which pretty much always causes a redraw.

**Comment by carlosdcastillo** [comment]
In the client I'm writing the control over the buffer is shared between Atom and Neovim. I need to make sure that when a user types :e filename in Atom, Atom will open a tab with that file or when a user types :bp in Atom Atom changes tabs appropriately. All of it is a consequence of shared buffers, unlike @tarruda's client and @coolwanglu's client which handle fully-owned buffers.

**Comment by justinmk** [comment]
I see, that makes sense.

**Comment by justinmk** [comment]
> I need to make sure that when a user types :e filename in Atom, Atom will open a tab with that file or when a user types :bp in Atom Atom changes tabs appropriately. All of it is a consequence of shared buffers

You can avoid redraws by batching operations with `nvim_call_atomic` or `nvim_execute_lua`.

> 2015/02/27 23:18:23 [error @ call_set_error:727] 97577 - Msgpack-RPC error: Channel was closed by the client
> I'm not calling ui_detach or disconnect or anything. Also the file .vimlog is multiple GB in size, repeating the same line, several times per second. The client works, but the server keeps printing that to file.

`$NVIM_LOG_FILE` is much less noisy at `INFO` log-level since this was reported. And channel activity has more context.
