### ISSUE TITLE
Make documentation more mobile-browser friendly 

### ISSUE THREAD

**Issue by swetepete** [neovim/neovim#20714]
### Feature already in Vim?

no

### Feature description

I don’t find the documentation very readable: https://neovim.io/doc/user/starting.html#starting.txt

It’s like an information overload of plaintext and it doesn’t wrap well on a mobile screen.

Is it possible to improve the “parser” to make it a more modern looking documentation site? 

This is just one example, though there are better examples: https://python.readthedocs.io/en/latest/extending/index.html

Even just GitHub README’s/Wikis are nice to read, the font is big clear and attractive and there’s a table of contents with links and you can search for keywords and so on.

Thank you

**Comment by justinmk** [comment]
> and it doesn’t wrap well on a mobile screen.

The parser and generator already do soft-wrapped output for a few specific pages such as:

https://neovim.io/doc/user/api.html

We mostly "own" starting.txt by now (I've spent a lot of time on it), so it could be another such opt-in case.

Note also that _lists_ are soft-wrapped, even in the legacy hard-wrapped pages. For all other legacy docs, there's nothing we can do short of rewriting all the docs.

There are various CSS improvements needed--much easier, and help is wanted: https://github.com/neovim/neovim.github.io/issues/288
