### ISSUE TITLE
Mapping <Tab> while not mapping <C-i>, shadows the default key action on <C-i>

### ISSUE THREAD

**Issue by lroobrou** [neovim/neovim#20719]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no, this is a neovim feature only.

### Operating system/version

Manjaro Linux

### Terminal name/version

wezterm, kitty

### $TERM environment variable

xterm-256color

### Installation

system package manager

### How to reproduce the issue

1. Neovim can only distinguish between `<Tab>` and `<C-i>` when using a terminal that supports the "CSI" protocol, such as kitty or wezterm (with option enable_csi_u_key_encoding set to true). To reproduce this problem, you have to use a terminal that supports this.

2. Start neovim with no config and map the tab key from the command line.

```nvim -Nu NONE +'nno <Tab> :echom "Tab was pressed"<cr>'```

3. Press control i. This will print the message "Tab was pressed"

### Expected behavior

The expected result is that pressing tab will print the message, but pressing control-i will not. Instead, control-i should execute the default action (go forward in the jump list) associated to that key. This used to be the behavior in 0.7.2.

### Actual behavior

This is a regression that I noticed when I upgraded to nvim 0.8.0, coming from 0.7.2. In 0.7.2, it used to work as described in the expected behavior section. I could map tab and still use the jump list. The somewhat strange thing is that 0.8.0 does handle the difference between the two keys, when both are mapped.

```nvim -Nu NONE +'nno <C-i> :echom "C-i was pressed"<cr>' +'nno <tab> :echom "Tab was pressed"<cr>'```

This works fine. It only seems to conflate the bindings when one is mapped and the other is not.

I went ahead and did a git bisect. 32da3e56cd12210cd567609f2ec7dd4f0c1ee4c6 is the first bad commit.

**Comment by zeertzjq** [comment]
This is the intended behavior and Vim's behavior is the same. Use something like `nnoremap <C-I> <C-I>` to still have the default action on `<C-I>`.

**Comment by lroobrou** [comment]
I don't fully understand your reasoning for closing this, but the workaround does work. Thanks.
