### ISSUE TITLE
Formatting of `msg_show` for `map` is missing newlines with `ext_messages`

### ISSUE THREAD

**Issue by folke** [neovim/neovim#20715]
### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

bob

### How to reproduce the issue

Runnig the code below, you willl see that newlines are missing between each keymap.

```lua
local ns = vim.api.nvim_create_namespace("test")
local messages = {}

vim.ui_attach(ns, { ext_messages = true }, function(event, kind, content)
  if event == "msg_show" and kind == "return_prompt" then
    vim.api.nvim_input("<cr>")
  elseif kind == "" then
    table.insert(messages, content)
  end
end)

vim.cmd([[map]])

vim.defer_fn(function()
  vim.ui_detach(ns)
  vim.pretty_print(messages)
end, 1000)
```

### Expected behavior

The output should be formatted the same as normal

![image](https://user-images.githubusercontent.com/292349/196382827-b368a662-d912-4081-b637-f1117fcf4ebb.png)

### Actual behavior

Newlines are missing between the different mappings.

![image](https://user-images.githubusercontent.com/292349/196382729-925d2edf-9aea-4838-b643-68b505dba83e.png)

See also https://github.com/folke/noice.nvim/issues/77

**Comment by zeertzjq** [comment]
This just prints a blank line for me.

**Comment by folke** [comment]
@zeertzjq check `:mess` after running. It's there

**Comment by folke** [comment]
To see the actual output, use something like this: (hit `:mess` after running)

```lua
local ns = vim.api.nvim_create_namespace("test")

local messages = {}

vim.ui_attach(ns, { ext_messages = true }, function(event, kind, content)
  if event == "msg_show" and kind == "return_prompt" then
    vim.api.nvim_input("<cr>")
  elseif content then
    table.insert(messages, content)
  end
end)

vim.cmd([[map]])

vim.defer_fn(function()
  vim.ui_detach(ns)
  for _, content in ipairs(messages) do
    -- vim.pretty_print(content)
    local text = table.concat(
      vim.tbl_map(function(item)
        return item[2]
      end, content),
      ""
    )
    print(text)
  end
end, 100)

```

**Comment by zeertzjq** [comment]
This fixes the problem:
```diff
diff --git a/src/nvim/mapping.c b/src/nvim/mapping.c
index 001bbf7e4..4ef07846b 100644
--- a/src/nvim/mapping.c
+++ b/src/nvim/mapping.c
@@ -155,7 +155,7 @@ static void showmap(mapblock_T *mp, bool local)
     return;
   }
 
-  if (msg_didout || msg_silent != 0) {
+  if (msg_didout || ui_has(kUIMessages) || msg_silent != 0) {
     msg_putchar('\n');
     if (got_int) {          // 'q' typed at MORE prompt
       return;
```

Not sure if there is a better solution.

**Comment by kkirankk** [comment]
@folke Is there any workaround for this?

**Comment by folke** [comment]
@kkirankk nope, this needs to be fixed in Neovim

**Comment by kkirankk** [comment]
@folke thanks, is it possible to disable the formatting for ext_messages.
