### ISSUE TITLE
CMake config enhancement: add an option to allow using a customized command to download dependent libraries

### ISSUE THREAD

**Issue by bc2009** [neovim/neovim#20725]
### Feature already in Vim?

NA

### Feature description

Right now in the latest code, looks like the cmake scripts in `cmake.deps` directory use the default cmake download (or built-in `curl`) which generally isn't build with `SSL` support by default. This fails to work for `https` urls like `Github`.

Can we add an option to let developers to use customized command such as `wget` or system's `curl` to download the dependencies in `ExternalProject_Add()`?

For example, we can add a customized `DOWNLOAD_COMMAND` that developer provides in `ExternalProject_Add`? Thanks

**Comment by dundargoc** [comment]
I'm hesitant, but not strictly against, this solution as it feels very niche. I did some searching and found the following link that seemed relevant: https://gitlab.kitware.com/cmake/cmake/-/issues/16208. From that issue this seems to be more an issue of improper installation of cmake.

**Comment by justinmk** [comment]
Is the root cause here, that you want to point to a different `cmake` ?

Meanwhile, there is `USE_EXISTING_SRC_DIR` which may be a different approach. See https://github.com/neovim/neovim/pull/20491

**Comment by bc2009** [comment]
> Is the root cause here, that you want to point to a different `cmake` ?
> 
> Meanwhile, there is `USE_EXISTING_SRC_DIR` which may be a different approach. See #20491

We are in a controlled (i.e., non-root user) env where the default cmake is actually not built with SSL support, and we cannot install dependent packages either.

**Comment by dundargoc** [comment]
Are you not able to manually build cmake with SSL-support?

**Comment by justinmk** [comment]
> We are in a controlled (i.e., non-root user) env where the default cmake is actually not built with SSL support

I recently had a similar use-case. The `USE_EXISTING_SRC_DIR` approach works, though somewhat clumsy. https://github.com/neovim/neovim/pull/36610 improves the docs for it ("offline builds").

Note: https://github.com/neovim/deps/tree/master/src is an auto-updated snapshot of the `.deps/build/src/` needed to build offline with `USE_EXISTING_SRC_DIR`.

> Are you not able to manually build cmake with SSL-support?

In some cases, no. And the build environment may not have network access.
