### ISSUE TITLE
Restricting remote connections to neovim

### ISSUE THREAD

**Issue by j-xella** [neovim/neovim#20723]
### Feature description

Neovim can work as a server, with GUI (and eventually TUI) clients connecting to it via TCP. However, there is very little connection security built into neovim itself.

So far, the advice is to tunnel the connection via ssh, and for nvim to listen on the loopback interface only. While this is not a bad advice, in my case it can't be used due to various reasons.

Now, the question is, assuming nvim server is listening to an external interface directly, is there a way to restrict who can connect to my nvim server?

I am a neovim newbie, so my suggestion is probably not the best one, but if channel info structure (returned with `vim_get_chan_info`) could be extended with the remote server name/IP address, wouldn't it be then at least possible to create a `ChanOpen` event that would check where the conenction is coming from and `chanclose` it if the address does not match white/black list?

**Comment by justinmk** [comment]
Can you review https://github.com/neovim/neovim/issues/4443 and add your suggestion there?
