### ISSUE TITLE
nvim_win_get_option doesn't report winbar if it was set with :set

### ISSUE THREAD

**Issue by gorbit99** [neovim/neovim#20739]
### Neovim version (nvim -v)

v0.8.0-dev-1202-g33dd917d7f

### Vim (not Nvim) behaves the same?

isn't relevant to vim

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.3

### $TERM environment variable

xterm-kitty

### Installation

AUR

### How to reproduce the issue

:set winbar=123
:echo nvim_win_get_option(0, "winbar")
:echo nvim_win_set_option(0, "winbar", "abc")
:echo nvim_win_get_option(0, "winbar")

### Expected behavior

prints out
123
abc

### Actual behavior

prints out
nothing (nil)
abc

**Comment by zeertzjq** [comment]
`:set` does not set the local value of a global-local option.
