### ISSUE TITLE
vim.lsp.buf.format is nil

### ISSUE THREAD

**Issue by GMFranceschini** [neovim/neovim#20738]
### Neovim version (nvim -v)

NVIM v0.8.0-1210-gd367ed9b2

### Vim (not Nvim) behaves the same?

(I don't understand this request, sorry)

### Operating system/version

Ubuntu 22.04

### Terminal name/version

alacritty 

### $TERM environment variable

alacritty

### Installation

compiled .tar from release page

### How to reproduce the issue

Executing:
```
nvim -u NONE
:lua print(vim.lsp.buf.format)
```

I obtained `nil` and not a function reference as expected.

### Expected behavior

`vim.lsp.buf.format` should be a function and not `nil`. This function exists in nvim 0.8.0, and I don't understand why I obtain this weird behavior.

### Actual behavior

The function can't be called, causing issues in using LSP instances, as I describe in [this issue](https://github.com/AstroNvim/AstroNvim/issues/1116).

**Comment by zeertzjq** [comment]
How did you install the compiled .tar?

**Comment by GMFranceschini** [comment]
@zeertzjq thank you for your implicit suggestion. Indeed I just copied the `nvim` binary to my `\usr\bin` folder, but executing it from its folder after untar causes no error. I guess I am missing something on why this should not be done, but the issue is solved.

**Comment by adelarsq** [comment]
@GMFranceschini The reason is that Neovim binary should be in the same folder as the others files. There are a lot others files than the `nvim` binary there.
