### ISSUE TITLE
disable diagnostic from a specific source

### ISSUE THREAD

**Issue by winkee01** [neovim/neovim#20745]
### Neovim version (nvim -v)

0.9.0-dev

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

macOS 12.3

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

source

### How to reproduce the issue

```
nvim --clean minimal.lua
```

minimal.lua
```
function disable_diagnostics(client)
  if client.server_capabilities.diagnosticProvider then
    client.server_capabilities.diagnosticProvider = false
  end
  if client.supports_method("textDocument/diagnostic") then
    print('client supports publish diagnostics')
   -- how to disable diagnostic
  end
end
```

### Expected behavior

disable diagnostic from lsp server

### Actual behavior

diagnostics is still shown. 
So now I can only hidden all diagnostic by calling `vim.diagnostic.hide()`, or implementing a very complicated function to disable the specific LSP source to send me diagnostic. At least, I searched the forum and community, but I can't find a way to achieve the objective.

#### My thoughts:
You refactored `vim.lsp.diagnostic` to `vim.diagnostic` in this [pull](https://github.com/neovim/neovim/pull/15585), but I think it has caused some more confusion because as with other Language Server features (formatting, codeAction, codelens, etc.) that are in LSP Protocol, diagnostic should not make its own specific way out, we need to stick to the protocol to make fewer confusions. If some plugins want to show diagnostics, they can either use their own APIs or follow the LSP protocol.

**Comment by winkee01** [comment]
I guess diagnostic also takes CPU time like other analysis tools, but the current API can only do `vim.diagnostic.set()`, `vim.diagnostic.get()` or `vim.diagnostic.show()`, none of them provide a clear way to disable some source to do linting job on the current buffer. Pulling it out of the LSP protocol and implementing a unique API (you think it's more general) isn't a good idea considering the confusion it has caused.

**Comment by winkee01** [comment]
A common way to use `vim.diagnostic` is In my setup() function:
```
vim.api.nvim_create_autocmd('FileType', { pattern = filetypes, group = lsp_group, callback = lsp.setup })
```

I call this:
```
vim.api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {
    buffer = 0,
    callback = lsp.show_diagnostics,
  })

function lsp.show_diagnostics()
  vim.schedule(function()
    local line = vim.api.nvim_win_get_cursor(0)[1] - 1
    local bufnr = vim.api.nvim_get_current_buf()
    local diagnostics = vim.diagnostic.get(bufnr, { lnum = line })
    vim.diagnostic.show(diagnostic_ns, bufnr, diagnostics, { virtual_text = true })
  end)
end
```

As you can see, there is no way to do customizations on any diagnostic source. If I want to filter out the diagnostic messages from some specific source, I have to do logic that could be overly complicated, something might be like:

```
vim.lsp.handlers['textDocument/publishDiagnostics'] = vim.lsp.with(
  function(_, params, ctx, config)
    filter(params.diagnostics, filter_diagnostics)
    vim.lsp.diagnostic.on_publish_diagnostics(_, params, ctx, config) -- vim.lsp.diagnostic is deprecated!
  end,
  {}
  -- pcall(vim.diagnostic.setloclist, { open = false })
)
``` 

and I come back to `vim.lsp.diagnostic` stuff, it's still in lsp realm.

If I do something like this (just like I disable formatting capability for some LSP servers):

```
function disable_diagnostics(client)
  if client.server_capabilities.diagnosticProvider then
    print("server supports diagnostics")
    client.server_capabilities.diagnosticProvider = false
  end
  if client.supports_method("textDocument/diagnostic") then
    print('client supports publish diagnostics')
  end
end
```

There is no effect 😭

**Comment by lvimuser** [comment]
This is already possible.

You can override handlers per client, so this should be enough:
```lua
client.handlers["textDocument/publishDiagnostics"] = function(...)
    local result = select(2, ...)
    result.diagnostics = {}
end
```
See https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/blob/main/lua/nvim-lsp-ts-utils/client.lua#L47-L110 for a filter example.

Also, `vim.diagnostic.enable` (and disable) accepts a `namespace` parameter, so you can toggle sources on the fly with
```lua
local client = vim.lsp.get_active_clients({ name = 'tsserver' })[1]
local ns = vim.lsp.diagnostic.get_namespace(client.id)
vim.diagnostic.disable(nil, ns)
```

**Comment by winkee01** [comment]
FIrst, thanks for the reference, as I said, the filtering stuff could be overly complicated and not clear enough. Simply to put, diagnostic is a feature in LSP Protocol, and deserves a simple way for the client to disable or enable, just like how we disable a client's formatting capability using a simple statement `client.server_capabilities.formattingProvider = false`.


> We don't have control on whether a language server send/publish diagnostics or not (aside from setting some [flags](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#publishDiagnosticsClientCapabilities)); that's the server's responsibility which may be exposed as an option. We don't **pull** diagnostics (a [recent addition](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_pullDiagnostics) to the spec).
> 
> See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_publishDiagnostics

**Comment by lvimuser** [comment]
> Simply to put, diagnostic is a feature in LSP Protocol, and deserves a simple way for the client to disable or enable

Then you should tell Microsoft that.

> just like how we disable a client's formatting capability using a simple statement `client.server_capabilities.formattingProvider = false`.

First, that's a hack/workaround, which is not recommended anymore because we have a better way to handle multi client formatting; this doesn't make sense for a single client because you can simply not call `format`. Again we may **request** a `format` from the server. We **can't/don't** request or pull diagnostics.

If you don't want neovim to 'process' diagnostics, you can override the handlers like shown. However, most of it happens server side, so what you're really __saving__ is https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/diagnostic.lua#L182-L207 and https://github.com/neovim/neovim/blob/master/runtime/lua/vim/diagnostic.lua#L285-L297 (doesn't seem like much 'CPU time' to me).

That's why it should be a option exposed by the language server or whatever plugin is using the `vim.diagnostic` interface.
(fsautocomplete has a `Linter` flag, jsonls has a `validate.enable` flag, and so on).

>  the filtering stuff could be overly complicated and not clear enough.

Maybe. You receive a bunch of diagnostics, then you return whatever you want. What's the interface you're expecting?

Do note that some servers also expose a filter option, eg tsserver has `diagnostics.ignoredCodes`, gopls exposes multiple levels of `analyses`.

**Comment by justinmk** [comment]
> diagnostic is a feature in LSP Protocol, and deserves a simple way for the client to disable or enable, just like how we disable a client's formatting capability using a simple statement `client.server_capabilities.formattingProvider = false`

You're asking for "easy", not "simple". The current approach is simple. Customizing every little bit of behavior is not a simple request, and making it easy complicates documentation, implementation, and the interface.

**Comment by winkee01** [comment]
BTW, what's the better way to handle multi-client formatting? currently, I simply set its capability to false.
> First, that's a hack/workaround, which is not recommended anymore because we have a better way to handle multi client formatting; this doesn't make sense for a single client because you can simply not call format. Again we may request a format from the server. We can't/don't request or pull diagnostics.

**Comment by glepnir** [comment]
get all clients in the buffer. Find the client id you need to format or client name pass to `vim.lsp.buf.format` in `BufWritePre`   cb .  I'm assuming that when you configure multiple servers for the same file type, you explicitly know which client to use for formatting

**Comment by winkee01** [comment]
> get all clients in the buffer. Find the client id you need to format or client name pass to `vim.lsp.buf.format` in `BufWritePre` cb . I'm assuming that when you configure multiple servers for the same file type, you explicitly know which client to use for formatting

Hi，I guess you mean this:

```
vim.lsp.buf.format({
        bufnr = bufnr,
        filter = function(client)
            return client.name == "stylua"
        end
    })
```

**Comment by glepnir** [comment]
`vim.lsp.buf.format( { name = 'client name' or id = 'client id'})` . `stylua` is a format tool not server. for me I use `vim.loop.new_spawn`  https://github.com/glepnir/nvim/blob/main/lua/internal/formatter.lua

**Comment by winkee01** [comment]
@glepnir Great, that's classy, I need more time to digest. Thanks!

**Comment by winkee01** [comment]
@lvimuser hello, do you know when did neovim call `vim.diagnostic.show()`? the diagnostics are shown by default (which means neovim call `vim.diagnostic.show()` at some point of time, maybe as a callback.

**Comment by winkee01** [comment]
> Also, `vim.diagnostic.enable` (and disable) accepts a `namespace` parameter, so you can toggle sources on the fly with
> 
> ```lua
> local client = vim.lsp.get_active_clients({ name = 'tsserver' })[1]
> local ns = vim.lsp.diagnostic.get_namespace(client.id)
> vim.diagnostic.disable(nil, ns)
> ```

Hi, I tested `vim.diagnostic.disable(nil, ns), it looks like there are problems with it. Here is my result:
![image](https://user-images.githubusercontent.com/49930785/197086277-e1682bba-d274-4336-8057-e0ed9d5f505b.png)

I tried `vim.diagnostic.reset(ns, nil)` as the Neovim's doc says it will remove all diagnostics but actually not.

**Comment by glepnir** [comment]
it still in diagnostic cache. so the `stl` still can get the result from it .

**Comment by winkee01** [comment]
@glepnir thank you, now I figured it out after reading its source code and debugging.  I realized that I just have to rewrite the diagnostic handler and filtered out all diagnostics that I don't want. cool!

**Comment by peku-jamf** [comment]
@winkee01 can I ask you how you removed diag messages from the cache? Having same problem here, diag messages are not shown anymore, but they still appear on diag list when I open it

**Comment by winkee01** [comment]
@peku-jamf In my case, I have diagnostic messages from **sumneko_lua** and **selene**, and I want to filter out diagnostics from **sumneko_lua**, so I write a function to achieve that and them override the default diagnostic handler(`vim.lsp.diagnostic.on_publish_diagnostics`), like this:
```
local function filter_diagnostics(diagnostic)
  -- Filter out all diagnostics from sumneko_lua
  if diagnostic.source:find('Lua', 1, true) then
    return false
  end
  return true
end

vim.lsp.handlers['textDocument/publishDiagnostics'] = vim.lsp.with(
  function(_, result, ctx, config)
    filter(result.diagnostics, filter_diagnostics)
    vim.lsp.diagnostic.on_publish_diagnostics(_, result, ctx, config)
  end,
  {}
)
```

Note:
- the filter function is just a mapping function that applies a function to each item of a table, you can use `vim.tbl_filter` or something similar.

**Comment by Mte90** [comment]
A lot of people tried the snippet by @winkee01 but doesn't work (searching on github dotfiles).

That one does:
```
local function filter_diagnostics(diagnostic)
  if diagnostic.source == 'pycodestyle' then
    return false
  end
  return true
end

vim.lsp.handlers['textDocument/publishDiagnostics'] = vim.lsp.with(
  function(_, result, ctx, config)
    result.diagnostics = vim.tbl_filter(filter_diagnostics, result.diagnostics)
    vim.lsp.diagnostic.on_publish_diagnostics(_, result, ctx, config)
  end,
  {}
)
```
