### ISSUE TITLE
json_decode: empty key emits *msgpack-special-dict* 

### ISSUE THREAD

**Issue by Freed-Wu** [neovim/neovim#20757]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

linux 5.19.7

### Terminal name/version

kitty 0.26.2

### $TERM environment variable

tmux-256color

### Installation

pacman

### How to reproduce the issue

```vim
ec json_decode('{"": "1"}')
```

In neovim, it return

```vim
{'_TYPE': [], '_VAL': [['', '1']]}
```

In vim, it return

```vim
{'': '1'}
``` 

### Expected behavior

Same as vim.

### Actual behavior

Different from vim.

**Comment by zeertzjq** [comment]
Surprising it works as intended when used through Lua `vim.call()`:
```vim
:echo v:lua.vim.call('json_decode', '{"": "1"}')
```

**Comment by zeertzjq** [comment]
This seems to come from [`e303ea8` (#4131)](https://github.com/neovim/neovim/pull/4131/commits/e303ea8a19bcd385eb7829beb7f2ef691c064b35)

**Comment by justinmk** [comment]
The _TYPE and _VAL things were designed to support roundtripping. E.g.:

```
:echo json_encode(json_decode('{"": "1"}'))
{"": "1"}
```

and a strict adherence to JSON spec. However, empty keys are allowed in JSON so I'm not sure why this happens here. Looks like we could fix this without issue.
