### ISSUE TITLE
Any (non-readonly) git command forces full rebuild

### ISSUE THREAD

**Issue by bfredl** [neovim/neovim#2078]
Doing any git command that changes some file in workdir (or even just commiting, without changing any workdir file) forces a full rebuild of all c files in neovim (but not in deps), instead of just rebuilding the necessary files. I do not have this behaviour with any other git+cmake build system.

**Comment by justinmk** [comment]
Yes, this is my fault, and I feel super guilty about it. When the last commit hash changes, it changes these variables:

https://github.com/neovim/neovim/blob/master/config/config.h.in#L5-L6

which are used in version.c. I believe there is some way to inject constants without triggering a rebuild, but I didn't do it correctly I guess.

**Comment by justinmk** [comment]
I *think* the problem is that `#include "nvim/version_defs.h"` and `#include "nvim/version.h"` is in many more files than necessary. If we can eliminate that then a full rebuild may not be triggered.

**Comment by bfredl** [comment]
Either that, or have a separate `version_git.h` that is only included in `version.c`

**Comment by justinmk** [comment]
Yes :) But there's really no reason for the various files to need version.h. The relevant methods should be moved to version.c and then they can be called by the files that need to print a version.

**Comment by bfredl** [comment]
I think the problem is really that `config.h` is included by `vim.h` which is included by everything. and thus splitting out a separately generated `version_git.h` is necessary. I'll give it a go.

**Comment by bfredl** [comment]
That reduces the problem to force-rebuilding only 7 files (that include `version_def.h` . `version.h` is no problem) Now the issue is, of these only 3 actually uses NVIM_VERSION, the rest only VIM_VERSION . Now what about moving `VIM_VERSION` to `version.h` and declaring exported strings in `version.h` that are defined in `version.c` ? Then only `version.c` is necessarily recompiled.
