### ISSUE TITLE
LSP: move/rename file and update imports

### ISSUE THREAD

**Issue by renzhamin** [neovim/neovim#20784]
### Feature description

Language servers usually have the ability to 
- move code segment to a new file and update all the imports or 
- automatically update imports on file rename via `:!mv ... ...` 

But I haven't found a way to do it with the built-in lsp

There's no interface like vim.lsp.buf.rename_file, there is vim.lsp.util.rename but that just renames the file and doesnt update any imports

As far as I know vim.lsp.buf.rename doesnt deal with file renames

Another problem : 
Move to a new file code action uses the very first function/variable name as the new filename and doesn't ask for the new filename, so even if I can move some code segment to a new file, I have no control over the new filename
if it did there could be a workaround to achieve file rename by selecting everything and use the move to a new file code action, then deleting the current file.
I'm not sure if this behaviour is language server specific, the one I tested with is tsserver

Note : coc has CocCommand workspace.renameCurrentFile

Expected behaviour should be to prompt the user if imports should be updated after a `:!mv ... ` ,  as is the case with coc

Edit: 
Expected behaviour is vim.lsp.util.rename should update imports if the lsp has that capability

**Comment by renzhamin** [comment]
For those who wants a workaround for now,

Here is an example,

```lua
local function rename_file()
    local source_file, target_file

    vim.ui.input({
        prompt = "Source : ",
        completion = "file",
        default = vim.api.nvim_buf_get_name(0)
    },
        function(input)
            source_file = input
        end
    )
    vim.ui.input({
        prompt = "Target : ",
        completion = "file",
        default = source_file
    },
        function(input)
            target_file = input
        end
    )

    local params = {
        command = "_typescript.applyRenameFile",
        arguments = {
            {
                sourceUri = source_file,
                targetUri = target_file,
            },
        },
        title = ""
    }

    vim.lsp.util.rename(source_file, target_file)
    vim.lsp.buf.execute_command(params)
end


require("lspconfig").tsserver.setup {
    commands = {
        RenameFile = {
            rename_file,
            description = "Rename File"
        },
    }
}
```

You will find the command and arguments from the documentation, in this example I got it from [here](https://www.npmjs.com/package/typescript-language-server#rename-file)

**Comment by ii14** [comment]
I think it should be hooked up to already existing interfaces, `:file` and `nvim_buf_set_name`. `BufFilePost` event might work for that?

`_typescript.applyRenameFile` looks like some non standard thing. LSP defines `workspace/willRenameFiles` and `workspace/didRenameFiles`.

**Comment by mfussenegger** [comment]
Looks like `CocCommand workspace.renameCurrentFile` is using `workspace/willRenameFiles` and `workspace/didRenameFiles`: https://github.com/neoclide/coc.nvim/blob/91abee79ac554a96132fab6b2b5af99d3221ed7c/src/core/files.ts#L270

There is already some logic in the change tracking code to detect a rename: https://github.com/neovim/neovim/blob/dab07be4d14b3d4d94cbab2bdc29d3e6985e21f2/runtime/lua/vim/lsp.lua#L1564-L1575 
maybe that could be modified to emit those notifications.

**Comment by vricop** [comment]
> For those who wants a workaround for now,
> 
> Here is an example,
> 
> ```lua
> local function rename_file()
>     local source_file, target_file
> 
>     vim.ui.input({
>         prompt = "Source : ",
>         completion = "file",
>         default = vim.api.nvim_buf_get_name(0)
>     },
>         function(input)
>             source_file = input
>         end
>     )
>     vim.ui.input({
>         prompt = "Target : ",
>         completion = "file",
>         default = source_file
>     },
>         function(input)
>             target_file = input
>         end
>     )
> 
>     local params = {
>         command = "_typescript.applyRenameFile",
>         arguments = {
>             {
>                 sourceUri = source_file,
>                 targetUri = target_file,
>             },
>         },
>         title = ""
>     }
> 
>     vim.lsp.util.rename(source_file, target_file)
>     vim.lsp.buf.execute_command(params)
> end
> 
> 
> require("lspconfig").tsserver.setup {
>     commands = {
>         RenameFile = {
>             rename_file,
>             description = "Rename File"
>         },
>     }
> }
> ```
> 
> You will find the command and arguments from the documentation, in this example I got it from [here](https://www.npmjs.com/package/typescript-language-server#rename-file)

Thanks for sharing, that so useful. The missing piece is making it work when moving files to another location or renaming a folder in the middle of the path.

**Comment by timsofteng** [comment]
Would be cool to have this feature.

**Comment by Hugobsb** [comment]
Hi, everyone. Excuse me. Any updates on this?

**Comment by faergeek** [comment]
>maybe that could be modified to emit those notifications

This would only work for a simple case of renaming a single file. It's sometimes convenient to rename entire folders as well. Though it's not obvious when Neovim should emit such events, besides from within netrw. File management is often handled by other plugins, so supporting such use cases would require either introducing separate APIs for working with files and folders or wrapping `vim.uv.fs_*` calls to emit those events.

There is a plugin, which currently fills this gap between file-tree plugins and file-related LSP methods
https://github.com/antosha417/nvim-lsp-file-operations

**Comment by crushingCodes** [comment]
@faergeek thanks that led me to find the following plugin which works
https://github.com/antosha417/nvim-lsp-file-operations

**Comment by justinmk** [comment]
Tracked in https://github.com/neovim/neovim/issues/28329
