### ISSUE TITLE
JDTLS go to implementation returns handler error

### ISSUE THREAD

**Issue by soofaloofa** [neovim/neovim#20795]
### Neovim version (nvim -v)

NVIM v0.8.0 Build type: Release

### Language server name/version

jdtls 1.6

### Operating system/version

macOS 12.6

### Steps to reproduce using "nvim -u minimal_init.lua"

1. Open a Java file
2. Execute the "go to implementation" command `gi`
3. Observe the error

```
Error executing vim.schedule lua callback: ...neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/handlers.lua:46: table index is nil
stack traceback:
        ...neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/handlers.lua:46: in function 'handler'
        ...w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:1056: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

If you press enter to clear the error, go to implementation does still work correctly

### Expected behavior

I am correctly taken to the implementation without receiving an error that needs to be cleared.

### Actual behavior

When going to implementation using the `jdtls` language server, I receive the following error in the current nvim window. If I ignore the error (by pressing Enter) I am correctly taken to the implementation.

```
Error executing vim.schedule lua callback: ...neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/handlers.lua:46: table index is nil
stack traceback:
        ...neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/handlers.lua:46: in function 'handler'
        ...w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:1056: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Log file

https://gist.github.com/soofaloofa/34fda4baa7ed825ac4182cfaac618943

**Comment by mfussenegger** [comment]
handlers.lua:46 is progress-report handling code. The implementation in eclipse.jdt.ls is currently bugged. There's a PR that attempts to fix it: https://github.com/eclipse/eclipse.jdt.ls/pull/2258

Workarounds:
-  you can use nvim-jdtls (which sets some flags so it doesn't happen)
- You can use this branch https://github.com/neovim/nvim-lspconfig/pull/2153
- You can set `config.handlers['$/progress'] = function() end` in your config
