### ISSUE TITLE
Upgrading Busted causes our tests to die with an assertion error in LuaJIT

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#2080]
This here to help us track the issue and record some knowledge, since I've spent some time looking at the problem and don't want to see that knowledge lost.

There appear to be several problems in play, but they all end up causing assertions in LuaJIT.  The first that I've been able to track down is the use of `os.exit(code, true)` in Busted.  For some reason, the wreaks havoc on LuaJIT causing an assertion in the GC logic.  This is only seems to be problem when ffi has been required, so I suspect some state information is getting lost, and bad things are happening as a result.

The second problem also seems to be ffi-related.  I haven't tracked down the issue yet, but LuaJIT dies with the following assertion:

> Assertion failed: (id > 0 && id < cts->top), function ctype_check, file ./lj_ctype.h, line 395.

This appears to happen whether on not the JIT is enabled.  I'm currently trying to work with the author of LuaJIT to get to the bottom of it, but I expect it's going to take some time since we don't have a nice, short, reproducable test case yet.  The thread I started on the LuaJIT mailing list can be found here: http://www.freelists.org/post/luajit/Assertion-error.

I will update this with new information as I discover it.

**Comment by jszakmeister** [comment]
Some good news!  I suspected that the ffi module was being reloaded and LuaJIT was unhappy about it.  It turns out that it is indeed true, and @o-lim from the Busted team was able to clarify it: https://github.com/Olivine-Labs/busted/issues/369#issuecomment-76624110

With a couple of fixes in place, it appears we are much closer to running with the latest Busted.  The only bit left (on Linux) is that this trick:

```lua
    -- Since the tests are executed, they are called by an executable. We use
    -- that executable for several asserts.
    absolute_executable = arg[0]
```

no longer works.  `arg[0]` ends up being `nil`. :-(  The also appear to be some cimport-related issues on OS X, but I don't think that has anything to do with the upgrade.  Just things that have been missed while adding new stuff.

**Comment by justinmk** [comment]
We upgraded busted since this issue, so I guess it is resolved. 6cfeea992250faec9654b9ff80108e662ce55704
