### ISSUE TITLE
Joining lines with J swallows characters

### ISSUE THREAD

**Issue by ttrei** [neovim/neovim#20802]
### Neovim version (nvim -v)

0.9.0 commit 40791f8e8

### Vim (not Nvim) behaves the same?

no, vim 9.0.626

### Operating system/version

Linux, Debian testing, kernel 5.19.6-1

### Terminal name/version

xterm 374

### $TERM environment variable

xterm

### Installation

build from repo

### How to reproduce the issue

```
nvim --clean
i*<CR>*<CR>%<CR>@<ESC>ggJJJ
```

### Expected behavior

Buffer content:
```
* * % @
```

### Actual behavior

Buffer content:
```
* @
```

**Comment by dstein64** [comment]
Do your `'formatoptions'` on Neovim include `j`? (`:help fo-j`)

What about on Vim, where you're not encountering the issue?

**Comment by dundargoc** [comment]
@dstein64 nice catch! This does indeed occur on vim as well when `set formatoptions` has a `j`.

**Comment by zeertzjq** [comment]
Duplicate of #16017
