### ISSUE TITLE
Treesitter: better customizability of queries

### ISSUE THREAD

**Issue by AckslD** [neovim/neovim#20805]
### Feature already in Vim?

No

### Feature description

This is a suggestion on how to extend the current query (scm) file structure to make it more powertul and easier to override certain parts.

# Issue
Currently we have files `queries/<lang>/<type>.scm` which are meant to indicate a query to run on a file. For example there is `highlights.scm` defining highlight captures. But it also contains eg `@spell` captures. Even though the `@spell` captures have a somewhat different purpose they are part of the same file as the highlights captures which from discussions on matrix is motivated by not having to run multiple queries on the same file.

However this makes is not ideal when a user for example don't want to have `@spell` captures in strings, since the user then needs to copy the whole highlights.scm and remove the `@spell` capture for strings, even though all the other highlights are the same.

# Suggestion
My suggestion is to be able to define a query as part of multiple scm files which can each individually be overriden, extended inherited. To do this a query definition can either be a single file `queries/<lang>/<type>.scm` (as currently supported) or a directory of such `queries/<lang>/<type>/<subtype>.scm`, which will all be merged to a single query. However all individual sub-query files are first individually handled with the different files in the runtime using the modelines.

So in the above issue we would instead have the files:
* `queries/<lang>/highlights/highlights.scm`
* `queries/<lang>/highlights/spell.scm`
* `queries/<lang>/highlights/conceal.scm`

# Implementation
The changes would be done in `vim.treesitter.query.get_query_files`. If this something that gets agreed upon to do I'd be happy to try to implement it.

**Comment by lewis6991** [comment]
The suggestion here is a drastic change to solve quite a point specific problem.

It is understood there is a need to allow much greater flexibility within queries, but the solution of just splitting into multiple files is suboptimal becuase:

- `highlights.scm` will still continue to be large.
- You still need to copy and paste the contents of query files when making customizations (even if it's too a lesser degree).
- Having multiple queries currently requires each query to be run on the AST, which is less efficient than just running one query.

For the specific case of spell checking strings, my plan was to add a `@spell.string` capture, and provide some way of enabling/disable it from applying spelling extmarks. As a first attempt this could just be a variable (`[gbw]:ts_spell_string`), and when we figure out a more general method for customisation we can migrate the variable to that.

**Comment by clason** [comment]
I agree; this problem is better solved by 
1. customizable captures (which will instantly cover a much wider variety of issues, e.g., optional conceals)
2. a `@nospell` capture.

**Comment by AckslD** [comment]
Thanks for giving feedback on this! Being able to disable specific captures seems indeed like a more powerful and probably better idea in the long-run :+1:

**Comment by AckslD** [comment]
I guess this can maybe be closed now that we have `@nospell` in #20178?

**Comment by clason** [comment]
Note: the more general issue of customizable queries is tracked in https://github.com/nvim-treesitter/nvim-treesitter/issues/2825

I probably should transfer this here since this in fact needs to be handled on the Neovim side.
