### ISSUE TITLE
log module is not included in the vim.lsp table by default?

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#20808]
### Neovim version (nvim -v)

v0.8.0-1210-gd367ed9b2

### Language server name/version

general question, not related to specific LSP server

### Operating system/version

any system

### Steps to reproduce using "nvim -u minimal_init.lua"

Based on code [here](https://github.com/neovim/neovim/blob/c00844aee4d9b607073ff123dfe2e872c9b84954/runtime/lua/vim/lsp.lua#L20), it seems that the `log` module for `vim.lsp` is not included in the `vim.lsp` table by default.

If we run `vim.lsp.log.get_level()`, we get an error that `nil` is not indexable.
Instead we have to do this:

```
lua =require('vim.lsp.log').get_level()
```

This is inconsistent compared to how we call the method under `vim.lsp.buf`, where, e.g., we simply call `vim.lsp.buf.hover()` without explicit require.

Is the current difference by design or something else?

**Comment by clason** [comment]
This is by design; use `vim.lsp.log_levels` instead.

**Comment by clason** [comment]
If you need to check the current level (which a normal user shouldn't have to), then you indeed have to `require` the `log` module.

**Comment by jdhao** [comment]
The style of the current doc for `vim.lsp.log` and `vim.lsp.buf` is the same, making no hint or indication that you should use `require('vim.lsp.log')` in order to use the log module. This confuses the users, unless they check the exact code like me to see the difference between `vim.lsp.buf` and `vim.lsp.log` modules.

**Comment by clason** [comment]
Users should not be using the `vim.lsp.log` module. This could be made more explicit, of course.

**Comment by justinmk** [comment]
> Users should not be using the `vim.lsp.log` module

+1, it's not a public interface. We will add `nvim_log` and `vim.log` soonish.
