### ISSUE TITLE
Normal mode all keys as modifier (modifier/layer mode)

### ISSUE THREAD

**Issue by duarm** [neovim/neovim#20819]
### Feature already in Vim?

No

### Feature description

not sure if #14400 implements release/repeats from the new kitty keyboard protocol, but when that is done, I wonder if, instead of constantly consuming down events (if you keep 'd' pressed, you'll continuously delete every line as per your key rate), you would be able to receive a held/repeat event instead. 

Now if you keep the 'd' key held, you'll not continuously delete every line, 'd' you be treated as a modifier/layer instead, so if you keep 'd' held, and press 'j', you'll delete the line below, without releasing 'd', you can press 'k', and delete the above line.

This would open a whole new keybinding world, and would be welcome as a new mode or perhaps a flag for normal. Maybe GUIs can already hack that, or maybe on TUI through a plugin (when neovim merges the kitty protocol)? not sure, but bringing that to the TUI would be awesome. Only possible on terminals which implement the kitty protocol tho.

**Comment by justinmk** [comment]
- https://github.com/neovim/neovim/issues/992
- https://github.com/neovim/neovim/issues/3253
