### ISSUE TITLE
`:checkhealth` errors on valid $TERM

### ISSUE THREAD

**Issue by barrett-ruth** [neovim/neovim#20837]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-124-gbd7ca10fd

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

arch-linux 5.18 lts

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

AUR nightly bin

### How to reproduce the issue

1. `tmux`
2. `nvim --clean -c checkhealth`

### Expected behavior

neovim acknowledges st-256color as a valid $TERM and doesn't error.

st-256color is also specified as the correct $TERM I should use [here](https://neovim.io/doc/user/term.html#%24TERM)

Note that $TERM is only compared against tmux-256color and screen-256color in [health/nvim.vim](https://github.com/neovim/neovim/blob/bbfc4567dfabc8d4378ad26a2d1020e3b2565107/runtime/autoload/health/nvim.vim#L230), so the solution may (?) just involve comparing $TERM with the rest of the valid specified term values in the documentation.

### Actual behavior

  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ

**Comment by barrett-ruth** [comment]
I'd like to solve this (if actually an issue) as my first PR, so any advice would be appreciated.

**Comment by zeertzjq** [comment]
> The $TERM environment variable must match the terminal you are using!

When you run Nvim inside tmux, The terminal you are using is tmux, not st, so this warning is correct.

**Comment by zeertzjq** [comment]
Maybe this can be better documented.

**Comment by barrett-ruth** [comment]
To clarify, the point I'm trying to make is that st is compiled with $TERM=st-256color. So if I remove the line setting $TERM in my tmux.conf:
```tmux
set -g default-terminal 'st-256color'
```

$TERM is indeed tmux-256color. However, the default terminal $TERM is still st-256color, and the following error results:
  - ERROR: $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
    - ADVICE:
      - $TERM may have been set by some rc (.bashrc, .zshrc, ...).

even though the colors are correct.

**Comment by zeertzjq** [comment]
It seems that according to tmux man page, `default-terminal` should start with `screen` or `tmux`:
```
     default-terminal terminal
             Set the default terminal for new windows created in this session - the default value of the TERM environment variable.  For tmux to work correctly, this must be set to
             ‘screen’, ‘tmux’ or a derivative of them.
```

**Comment by justinmk** [comment]
> Maybe this can be better documented.

checkhealth is the documentation :) What else would we say?



> * ERROR: $TERM differs from the tmux `default-terminal` setting.

If this is happening that suggests that something else is setting $TERM in your shell config... which apparently is hardcoded in `st` :

> st is compiled with $TERM=st-256color

If st is hardcoded to set TERM even in tmux, that is an st bug.
