### ISSUE TITLE
`vim.lsp.util.stylize_markdown` does not return the width and height

### ISSUE THREAD

**Issue by otommod** [neovim/neovim#20836]
### Neovim version (nvim -v)

NVIM v0.8.0 Build type: Release

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

Arch Linux

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

system package manager

### How to reproduce the issue

nvim --clean
:lua print(vim.inspect(vim.lsp.util.stylize_markdown(0, {"# header 1", "## header 2"}, {})))

### Expected behavior

You'd get the width and the height the window containing your buffer should have to fit its new contents, like the docs suggest

### Actual behavior

You get the new contents of the buffer (after trimming and such)

**Comment by glepnir** [comment]
you can overwrite this function in your local.

**Comment by justinmk** [comment]
`vim.lsp.util` is not a public API

**Comment by justinmk** [comment]
> Expected behavior
> You'd get the width and the height the window containing your buffer should have to fit its new contents, like the docs suggest

Not sure why this function is public, but the docs were updated, the return value is now:

```
    Return:  
        (table) stripped content
```
