### ISSUE TITLE
"l·l" Ligature in "Source Code Pro" incorrectly invoked 

### ISSUE THREAD

**Issue by jessehansen** [neovim/neovim#20839]
### Neovim version (nvim -v)

NVIM v0.8.0

### Vim (not Nvim) behaves the same?

yes, vim 9.0.217

### Operating system/version

macOS 12.6

### Terminal name/version

kitty 0.26.4

### $TERM environment variable

xterm-kitty

### Installation

Homebrew

### How to reproduce the issue

1. Ensure you have a SourceCodePro font installed and configured as the current font in kitty. I use SauceCodePro Nerd Font, but this should be reproducible with other SourceCodePro fonts.
Minimal kitty.conf:
```
font_family SauceCodePro Nerd Font
disable_ligatures always
```
2. `nvim --clean`
3. `:set listchars+=space:·`
4. `:set list`
5. Insert `l l` text into a document

### Expected behavior

The font should render with no ligatures.

### Actual behavior

"l·l" replaces the first "l" while displaying.
<img width="196" alt="Screen Shot 2022-10-27 at 14 52 10" src="https://user-images.githubusercontent.com/1916568/198395590-eebc2c37-0930-4d87-9460-4a89276c1eab.png">

VSCode had this same issue - https://github.com/microsoft/vscode/issues/106583 

It looks like they solved it by inserting a U+200C ZERO WIDTH NON-JOINER character before and after each whitespace character. That's not an option with listchars because space must be a single character.

I was able to work around this by disabling ccmp in my kitty.conf:
```
font_features SauceCodeProNerdFontComplete-Regular -ccmp
```

**Comment by zeertzjq** [comment]
Related: #15201

**Comment by zeertzjq** [comment]
The easiest workaround is probably to use `:set listchars+=space:∙` (`:set listchars+=space:\\u2219`) instead. This doesn't trigger the ligature.

**Comment by zeertzjq** [comment]
I don't think this can be fixed without causing performance problems.
