### ISSUE TITLE
incorrect `checkhealth` tmux RGB verification

### ISSUE THREAD

**Issue by barrett-ruth** [neovim/neovim#20841]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-124-gbd7ca10fd

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

arch 5.18 lts

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

AUR nightly bin

### How to reproduce the issue

1. tmux
2. nvim --clean -c checkhealth

### Expected behavior

Tmux shows instance RGB compatability w/ 
```tmux
set -as terminal-overrides ',st-256color:RGB'
```

### Actual behavior

  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

Back at it again with a checkhealth issue (but I think this one is real).

[Here](https://github.com/neovim/neovim/blob/bbfc4567dfabc8d4378ad26a2d1020e3b2565107/runtime/autoload/health/nvim.vim#L238) in health/nvim.vim `tmux server-info` is called to extract system information. However, at least as of tmux 3.3a, server-info is not a recognized command. Resultedly, the above warning is called regardless of how I attempt to add the terminal overrides.

**Comment by justinmk** [comment]
PR welcome

**Comment by barrett-ruth** [comment]
[Done](https://github.com/neovim/neovim/pull/20868).
