### ISSUE TITLE
Update "stable" Ubuntu PPA to neovim 0.8

### ISSUE THREAD

**Issue by arbrauns** [neovim/neovim#20844]
### Feature description

The ["stable" Ubuntu PPA](https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable) still ships neovim 7.2 almost a month after the release of 0.8. Are there plans to update the PPA, and if so, when? A previous issue about this (#20743) was closed and locked without comment.

Maybe I'm just not understanding what "stable" means here - I don't think it's explained anywhere, but I assumed it's simply "not nightly". If it's instead "lagging behind the latest release to ensure as few bugs as possible make it through", I'll just build 0.8 myself until the stable repo gets there.

**Comment by dundargoc** [comment]
We don't maintain the PPA, you should ask them instead.

**Comment by arbrauns** [comment]
Oh, I see, maybe that should be emphasized a bit more on https://github.com/neovim/neovim/wiki/Installing-Neovim#Ubuntu, it seemed like it was an official thing to me.

**Comment by dundargoc** [comment]
Noted. I've clarified it.
