### ISSUE TITLE
hangs while upgrading on Mac Yosemite 10.10.2

### ISSUE THREAD

**Issue by RichardDooling** [neovim/neovim#2084]
Doing 
brew update
brew reinstall --HEAD neovim

Hangs at command line with attached image
![screen shot 2015-03-02 at 7 44 09 am](https://cloud.githubusercontent.com/assets/1476034/6441741/5bceb028-c0b0-11e4-97ac-e124cba2f930.png)

**Comment by illicium** [comment]
:+1:

https://gist.github.com/illicium/9fb7e462162601526599

**Comment by RichardDooling** [comment]
make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/usr/local/C

Yep, and still doing it. Does not inspire confidence.

**Comment by jszakmeister** [comment]
First, homebrew related issues should be filed [here](https://github.com/neovim/homebrew-neovim) where they'll get a little more visibility by those who know homebrew.

Second, have either of you tried uninstalling Neovim and re-installing?

```text
brew uninstall neovim
brew install -v neovim
```

It'd be nice to see which step it's hanging up on, and the `-v` option would help with that.  There also some extra troubleshooting tips [here](https://github.com/neovim/homebrew-neovim#troubleshooting).

> Yep, and still doing it. Does not inspire confidence.

@RichardDooling That's not real helpful. :-(  It runs fine for me and many others.  Helping to track down the issue would be more useful.

**Comment by RichardDooling** [comment]
Okay. I'm no programmer. I'm a writer and heavy MacVim user.

For instance. Trying your recommendation gives me

Error: neovim is a head-only formula
Install with `brew install --HEAD neovim`

So does that mean I'm supposed to try:

brew install -v --HEAD neovim   ?

On Thu, Apr 23, 2015 at 5:56 AM, John Szakmeister <notifications@github.com>
wrote:

> First, homebrew related issues should be filed here
> <https://github.com/neovim/homebrew-neovim> where they'll get a little
> more visibility by those who know homebrew.
>
> Second, have either of you tried uninstalling Neovim and re-installing?
>
> brew uninstall neovim
> brew install -v neovim
>
> It'd be nice to see which step it's hanging up on, and the -v option
> would help with that. There also some extra troubleshooting tips here
> <https://github.com/neovim/homebrew-neovim#troubleshooting>.
>
> Yep, and still doing it. Does not inspire confidence.
>
> @RichardDooling <https://github.com/RichardDooling> That's not real
> helpful. :-( It runs fine for me and many others. Helping to track down the
> issue would be more useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neovim/neovim/issues/2084#issuecomment-95539273>.
>



-- 

rd

**Comment by RichardDooling** [comment]
Uninstalling did the trick!

Thanks for the tip.

> /usr/local/Cellar/neovim/HEAD: 1336 files, 21M, built in 3.6 minutes

**Comment by jszakmeister** [comment]
> brew install -v --HEAD neovim   ?

Yes, that's what I meant for you to try.

> Uninstalling did the trick!

Great!

> Thanks for the tip.

I think this is due to a hang up in generating tags.  It might be interesting for us to remove the runtime directory before installing it, but alas, CMake doesn't provide a good way to do that. :-(
