### ISSUE TITLE
A trailing slash is disappeared from <afile>

### ISSUE THREAD

**Issue by emonkak** [neovim/neovim#20847]
### Neovim version (nvim -v)

v0.8.0

### Vim (not Nvim) behaves the same?

no, vim 9.0.0655

### Operating system/version

Gentoo Linux

### Terminal name/version

Alacritty

### $TERM environment variable

xterm-256color

### Installation

emerge vim

### How to reproduce the issue

NVim:

```
$ nvim -u NONE -es --cmd 'au VimEnter * verbose echo expand("%") expand("<afile>") "\n" | q' foo/
foo/ foo
```

Vim:

```
$ vim -u NONE -es --cmd 'au VimEnter * verbose echo expand("%") expand("<afile>") "\n" | q' foo/
foo/ foo/
```

### Expected behavior

Both `expand('%')` and `expand('<afile>')` should return `'foo/'`. Vim (not Nvim) works as expected.

### Actual behavior

`expand('<afile>')`  returns `'foo'` without a trailing slash.

Related: https://github.com/neovim/neovim/issues/2833

**Comment by zeertzjq** [comment]
Seems a regression between v0.5.0 and v0.6.0.

**Comment by zeertzjq** [comment]
Hmm, Vim also has this bug if the directory exists.
