### ISSUE TITLE
LSP: highlight vim.lsp.buf.hover markdown contents using treesitter

### ISSUE THREAD

**Issue by aspeddro** [neovim/neovim#20857]
### Feature already in Vim?

No

### Feature description

The [noice.nvim](https://github.com/folke/noice.nvim) plugin use the API `vim.treesitter.start` to apply syntax highlight for hover. This feature could be present for LSPs that respond with `kind: "markdown"`

![](https://preview.redd.it/uqkzemqtbkw91.png?width=1052&format=png&auto=webp&s=a87e33895ac21c493696d0e9d57fddfe82404aa6)

Image from: [https://www.reddit.com/r/neovim/comments/yfqtoi/weekly_noice_updates/](https://www.reddit.com/r/neovim/comments/yfqtoi/weekly_noice_updates/)

**Comment by clason** [comment]
Neovim doesn't bundle a Markdown parser (and likely will not for a while at least), so this is not something we can do out of the box. Hence it's better to leave this for a plugin (like noice).

**Comment by justinmk** [comment]
Nvim 0.10 now ships with a markdown parser: https://github.com/neovim/neovim/pull/22481
