### ISSUE TITLE
serverstart does not start in Mac (brew)

### ISSUE THREAD

**Issue by fgr1986** [neovim/neovim#20865]
### Neovim version (nvim -v)

NVIM v0.8.0 Build type: Release, also on HEAD version

### Vim (not Nvim) behaves the same?

No, does not apply

### Operating system/version

macOS 12.6

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

Hombrew

### How to reproduce the issue

nvim --clean
:echo serverstart()

### Expected behavior

No error and 'nvim' server starts (according to documentation)

### Actual behavior

Error: `Failed to start server: no such file or directory`

<img width="800" alt="image" src="https://user-images.githubusercontent.com/10627849/198848024-b02362bc-3d31-4d98-974c-932d2df2b0d7.png">

**Comment by justinmk** [comment]
look for "server_start" lines in the log file

    :edit $NVIM_LOG_FILE


what do the logs say?

**Comment by fgr1986** [comment]
`server_start:166: Failed to start server: no such file or directory: /run/user/501/`

I can manually create it. But my mac does not have `/run/user/$uid` present (linux does, but I am not sure it is the case in MacOS).

**Comment by justinmk** [comment]
well, the Nvim logic to create a tempdir is failing. Do you have a "weird" username on that system? Or anything unusual about the temp dir setup or permissions?

**Comment by fgr1986** [comment]
standard username (no weird characters)

```
 > ll /tmp 
lrwxr-xr-x@ 1 root  wheel    11B 18 Oct 13:36 /tmp@ -> private/tmp
```
And no other message appears in the log but the one I shared above.

**Comment by justinmk** [comment]
what does this show:

```
:echo tempname()
:echo stdpath('run')
```

**Comment by fgr1986** [comment]
Apologies for the late reply:
```
:echo tempname(): 
/var/folders/7r/c604gh5915dg2r8l_bhfvq5h0000gn/T/nvim.fgarcia/kG0kmY/0
:echo stdpath('run'):
/run/user/501
```

Is `stdpath('run')` dependent on any shell variable?
Thanks

**Comment by justinmk** [comment]
> Is `stdpath('run')` dependent on any shell variable?

`$XDG_RUNTIME_DIR`

**Comment by fgr1986** [comment]
Mystery solved then: local program conf was overwritten it.
Apologies for all the trouble!
