### ISSUE TITLE
Spell in strings with language injection

### ISSUE THREAD

**Issue by AckslD** [neovim/neovim#20864]
### Neovim version (nvim -v)

v0.8.0

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

arch linux 6.0.2-arch1-1

### Terminal name/version

kitty 0.26.4

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

I have been trying for a long time to reproduce this with a simple minimal config using packer but have not been able to do so yet. So instead I've taken the relevant parts from the `packer_complied.lua` plugin file which is generated from my config. It is still pretty small and reproduces the issue though.

Also I'm not completely sure if this issue should be open here, in nvim-treesitter or packer.nvim.

Run the following:
```
nvim --clean -u minimal.lua tmp.lua
```

where `minimal.lua` is:
```lua
vim.opt.spell = true

local packpath = vim.fn.expand('/tmp/nvim/site')
local packer_base_path = packpath .. '/pack/packer'
local packer_path = packer_base_path .. '/opt/packer.nvim'
local ts_path = packer_base_path .. '/opt/nvim-treesitter'

vim.opt.packpath:append(packpath)

if vim.fn.isdirectory(packer_path) == 0 then
  print("Cloning packer.")
  print(vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', packer_path })
end
if vim.fn.isdirectory(ts_path) == 0 then
  print("Cloning treesitter.")
  print(vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/nvim-treesitter/nvim-treesitter', ts_path })
end

_G.ts_config = function()
  require'nvim-treesitter.configs'.setup({
    ensure_installed = {'lua', 'vim'},
    highlight = {enable = true },
  })
end

vim.api.nvim_command('packadd packer.nvim')

_G.packer_plugins = {
  ["nvim-treesitter"] = {
    config = { 'ts_config()' },
    loaded = false,
    needs_bufread = false,
    only_cond = false,
    path = ts_path,
    url = "https://github.com/nvim-treesitter/nvim-treesitter"
  },
  ["packer.nvim"] = {
    commands = { "PackerLoad", "PackerStatus", "PackerInstall", "PackerSync", "PackerUpdate", "PackerClean", "PackerCompile", "PackerProfile" },
    loaded = false,
    needs_bufread = false,
    only_cond = false,
    path = packer_path,
    url = "https://github.com/wbthomason/packer.nvim"
  },
}

----------
-- copied from generated packer compile
----------
local module_lazy_loads = {
  ["^nvim%-treesitter"] = "nvim-treesitter",
}
local lazy_load_called = {['packer.load'] = true}
local function lazy_load_module(module_name)
  local to_load = {}
  if lazy_load_called[module_name] then return nil end
  lazy_load_called[module_name] = true
  for module_pat, plugin_name in pairs(module_lazy_loads) do
    if not _G.packer_plugins[plugin_name].loaded and string.match(module_name, module_pat) then
      to_load[#to_load + 1] = plugin_name
    end
  end

  if #to_load > 0 then
    require('packer.load')(to_load, {module = module_name}, _G.packer_plugins)
    local loaded_mod = package.loaded[module_name]
    if loaded_mod then
      return function(modname) return loaded_mod end
    end
  end
end
if not vim.g.packer_custom_loader_enabled then
  table.insert(package.loaders, 1, lazy_load_module)
  vim.g.packer_custom_loader_enabled = true
end
----------

vim.api.nvim_command('packadd nvim-treesitter')
```
and `tmp.lua` is:
```lua
vim.cmd('echo "msg"')
```

### Expected behavior

Correct highlighting, ie something like:

![gscreenshot_2022-10-29-190342](https://user-images.githubusercontent.com/23341710/198844084-a375677c-3d6a-47df-b201-14f605a6c3ae.png)

### Actual behavior

The first letter of each word in the string has the wrong highlight:

![gscreenshot_2022-10-29-190358](https://user-images.githubusercontent.com/23341710/198844106-21a47f7e-2ce5-491f-ac39-726829168339.png)

**Comment by AckslD** [comment]
To add to this. I have the same with f-strings in python and I tried to remove the spell there with
```
((string (interpolation)) @nospell)
```
which does disable the spell checking but then I don't get any injected highlights at all.

**Comment by clason** [comment]
You still need to add the highlight

```lisp
((string (interpolation)) @string @nospell)
```

**Comment by AckslD** [comment]
Hmm, that seems to make no different, it's not about the highlighting of the string but of the injected python. I see the following cases:
1. default queries from nvim-treesitter and `:set spell`:
![gscreenshot_2022-11-21-222413](https://user-images.githubusercontent.com/23341710/203161376-c3ab5e9c-1abc-4a19-a630-e64820da3d11.png)
2. same as above but with `:set nospell`
![gscreenshot_2022-11-21-222452](https://user-images.githubusercontent.com/23341710/203161638-48287b8b-0d7d-4839-93d4-4e8a03a77266.png)
3. using and `after` (extends) query
   ```
   ;; extends
   ((string (interpolation)) @nospell)
   ```
![gscreenshot_2022-11-21-222511](https://user-images.githubusercontent.com/23341710/203161659-69a5ef63-403a-4e85-876d-3f237629b5f0.png)
4. same as above but with `:set nospell`
![gscreenshot_2022-11-21-222452](https://user-images.githubusercontent.com/23341710/203161638-48287b8b-0d7d-4839-93d4-4e8a03a77266.png)

Using the `@string` highlight gives the same behaviour as 3. and 4.

**Comment by AckslD** [comment]
I think finally managed to find a minimal set of things to cause this! It seems to be a combination of three things:
* :set spell`
* `additional_vim_regex_highlighting = true`
* a non-trivial colorsceme (I tried with both `nightfox` and `tokyonight` and both give the same behaviour

If either of the three are not there it does not happen.

See the minimal config below.

Although I'm still not completely sure what is the underlying root cause.

I've been using `additional_vim_regex_highlighting` in `python` to have proper indentation using [vim-python-pep8-indent](https://github.com/Vimjas/vim-python-pep8-indent). However I read that this seems solved now in https://github.com/nvim-treesitter/nvim-treesitter/issues/2947.

I can reproduce this in latest master with for example:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

vim.opt.spell = true

require("lazy").setup({
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    config = function()
      require('nvim-treesitter.configs').setup({
        ensure_installed = {'python'},
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = true,
        },
      })
    end,
  },
  'EdenEast/nightfox.nvim',
}, {
  root = '/tmp/lazy',
  lockfile = '/tmp/lazy-lock.json',
})

vim.cmd(string.format("colorscheme %s", 'terafox'))
```
and running
```
nvim --clean -u ~/dev/config/nvim/minimal.lua tmp.py
```
where `tmp.py` is for example:
```python
f'{True}'
```

**Comment by clason** [comment]
This is not a minimal example. If this is an actual Neovim issue, you should be able to reproduce it with one of the bundled parsers (Lua, Vim, C) and the default colorscheme.

**Comment by AckslD** [comment]
I'll be honest, I got a bit upset by this. I spent a few hours yesterday trying to find a way to reproduce this with a small config, which in your opinion is not a minimal example.

I'm not gonna argue with this but I lost quite some motivation to try to work on this more. I always try to do my best to write clear and thorough issues and help the community with the best of my abilities. But if this is not helpful maybe I just shouldn't.

**Comment by clason** [comment]
I apologize if the tone was too curt, but we really do need a minimal example -- and that means without plugins where these are not necessary. This is the most important piece of information! If it's not clear how to use the built-in functionality to achieve this, you're always welcome to ask.

**Comment by clason** [comment]
OK, I tested this a bit myself, and what you're likely seeing is https://github.com/neovim/neovim/issues/20456 (which is an issue with Vim's syntax engine). Until this gets fixed upstream (and I won't hold my breath), the only recommendation is to _not_ enable regex syntax highlighting for languages with injections.

Out of interest: is there any specific reason you are doing that?

**Comment by AckslD** [comment]
Thanks, I appreciate your reply and your work!

> Out of interest: is there any specific reason you are doing that?

I was previously using it to get proper python indentation with `vim-python-pep8-indent` but this is not needed anymore:
https://github.com/nvim-treesitter/nvim-treesitter/issues/2947

Feel free to close this. At least now without regex highlighting I won't have this issue anymore and maybe it's contained in #20456

**Comment by AckslD** [comment]
After trying out using the indentation from `nvim-treesitter` for `python` I find it's still lacking in some cases. So for now I would still be interested in using additional vim regex highlight together with `spell`. When I find the time I'll try to find a proper minimal example.

**Comment by clason** [comment]
Minimal repro (not using treesitter) in the linked issue, so I'll close this for now in favor of the other one; if that gets fixed but your issue remains, we'll reopen.

**Comment by AckslD** [comment]
Great! :+1:
