### ISSUE TITLE
clipboard: prefer xsel before xclip

### ISSUE THREAD

**Issue by Freed-Wu** [neovim/neovim#20862]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

linux 5.19.7

### Terminal name/version

wezterm

### $TERM environment variable

xterm

### Installation

pacman

### How to reproduce the issue

```sh
$ touch a
$ xsel -ib < a
$ xsel -ob
$ xclip -o -selection clipboard
Error: target STRING not available
```

It will make neovim throw `clipboard: error: Error: target STRING not 
available`:

```vim
  let out = systemlist(a:cmd, (a:0 ? a:1 : ['']), 1)
  if v:shell_error
    if !exists('s:did_error_try_cmd')
      echohl WarningMsg
      echomsg "clipboard: error: ".(len(out) ? out[0] : v:shell_error)
      echohl None
      let s:did_error_try_cmd = 1
    endif
    return 0
  endif
```

It is the bug of xclip. I advise to decrease the priority of xclip to reduce the 
probability of this bug.

```diff
diff --git a/clipboard.vim b/clipboard.vim
index 991bed6..9f357b5 100644
--- a/clipboard.vim
+++ b/clipboard.vim
@@ -97,18 +97,18 @@ function! provider#clipboard#Executable() abort
     let s:copy['*'] = ['wl-copy', '--foreground', '--primary', '--type', 'text/plain']
     let s:paste['*'] = ['wl-paste', '--no-newline', '--primary']
     return 'wl-copy'
-  elseif !empty($DISPLAY) && executable('xclip')
-    let s:copy['+'] = ['xclip', '-quiet', '-i', '-selection', 'clipboard']
-    let s:paste['+'] = ['xclip', '-o', '-selection', 'clipboard']
-    let s:copy['*'] = ['xclip', '-quiet', '-i', '-selection', 'primary']
-    let s:paste['*'] = ['xclip', '-o', '-selection', 'primary']
-    return 'xclip'
   elseif !empty($DISPLAY) && executable('xsel') && s:cmd_ok('xsel -o -b')
     let s:copy['+'] = ['xsel', '--nodetach', '-i', '-b']
     let s:paste['+'] = ['xsel', '-o', '-b']
     let s:copy['*'] = ['xsel', '--nodetach', '-i', '-p']
     let s:paste['*'] = ['xsel', '-o', '-p']
     return 'xsel'
+  elseif !empty($DISPLAY) && executable('xclip')
+    let s:copy['+'] = ['xclip', '-quiet', '-i', '-selection', 'clipboard']
+    let s:paste['+'] = ['xclip', '-o', '-selection', 'clipboard']
+    let s:copy['*'] = ['xclip', '-quiet', '-i', '-selection', 'primary']
+    let s:paste['*'] = ['xclip', '-o', '-selection', 'primary']
+    return 'xclip'
   elseif executable('lemonade')
     let s:copy['+'] = ['lemonade', 'copy']
     let s:paste['+'] = ['lemonade', 'paste']
```

### Expected behavior

No bug.

### Actual behavior

bug.

**Comment by justinmk** [comment]
> I advise to decrease the priority of xclip to reduce the
> probability of this bug.

sure, but this flip-flops https://github.com/neovim/neovim/commit/46bd3c0f77f282b93ca1307c011562243c394306

although the justification in https://github.com/neovim/neovim/pull/4150 is questionable. cc @Shougo

**Comment by Shougo** [comment]
Yes.  It is xsel problem and it will be priority infinite loop.  I think clipboard provider should be set by users like `g:python3_host_prog`.

**Comment by Shougo** [comment]
It seems `xsel` has many problems than `xclip`.  So the restore is OK.

**Comment by justinmk** [comment]
I see https://github.com/astrand/xclip/issues/38 is an open issue. (Please, always reference relevant issues.) So, PR welcome.

**Comment by justinmk** [comment]
oh I got the history wrong. 

- we preferred xsel long ago: https://github.com/neovim/neovim/commit/46bd3c0f77f282b93ca1307c011562243c394306
- but I swapped it here: https://github.com/neovim/neovim/commit/799d9c32157c841c3b8d355fa98a5ace435eef07
    - to work around https://github.com/neovim/neovim/issues/7237#issuecomment-443440633

I agree that now it makes sense to again prefer `xsel`.

**Comment by adrian5** [comment]
Unfortunately using `xsel` introduces a delay in [clipboard.vim](https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/clipboard.vim) during startup which `xclip` doesn't.

I tried replicating the `let g:clipboard = { … }` examples from the docs in Lua replicating [these](https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/clipboard.vim#L106-L111) values but that makes `xsel` hang:

```lua
vim.g.clipboard = {
  name = "xsel",
  copy = {
    ["+"] = "xsel --nodetach -i -b",
    ["*"] = "xsel --nodetach -i -p"
  },
  paste = {
    ["+"] = "xsel -o -b",
    ["*"] = "xsel -o -p"
  },
  cache_enabled = false
}
```

I think the `nodetach` flag might be the problem. But then why is it used in the code?

**Comment by dundargoc** [comment]
Added it to https://github.com/neovim/neovim/pull/23619
