### ISSUE TITLE
Can the patch for https://github.com/vim/vim/issues/10490 be added?

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#20878]
### Feature already in Vim?

Yes, in bf79a4e48d09a5ae08645592885d54230fed30b8

### Feature description

Vim issue https://github.com/vim/vim/issues/10490 has been patched by https://github.com/vim/vim/commit/bf79a4e48d09a5ae08645592885d54230fed30b8. Can this patch be added to Neovim?

**Comment by clason** [comment]
Sure, make a PR! (You can use `scripts/vim-patch.sh` script to help.)

As we plan on porting all (applicable) patches, there's no need to track this.

**Comment by zeertzjq** [comment]
This patch looks hard. It depends on a lot previous patches.

**Comment by zeertzjq** [comment]
Added in #20942
