### ISSUE TITLE
Impossible to install/build NVIM v0.8-0.9 on macOS v10.13.6

### ISSUE THREAD

**Issue by n8an** [neovim/neovim#20877]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-198+g75ec1b720 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no, v8.0.1365

### Operating system/version

macOS v10.13.6

### Terminal name/version

Alacritty v0.12.0-dev (578e0848)

### $TERM environment variable

alacritty

### Installation

prebuild package from repo that says (macOS v10.11+)

### How to reproduce the issue

curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
tar xzf nvim-macos.tar.gz
./nvim-macos/bin/nvim

### Expected behavior

opening of nvim

### Actual behavior

MacBook-Pro-emperor:~ admin$ curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11.8M  100 11.8M    0     0  2519k      0  0:00:04  0:00:04 --:--:-- 2823k
MacBook-Pro-emperor:~ admin$ tar xzf nvim-macos.tar.gz
MacBook-Pro-emperor:~ admin$ ./nvim-macos/bin/nvim
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/admin/./nvim-macos/bin/nvim (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/admin/./nvim-macos/bin/nvim (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
MacBook-Pro-emperor:~ admin$

**Comment by clason** [comment]
We don't support macOS < 10.15 (see https://github.com/neovim/neovim/blob/master/runtime/doc/support.txt). Try installing via `homebrew`, if they have wider support.

**Comment by n8an** [comment]
As a note.
I have tried to:
- brew install nvim
- build 0.8 nvim from source
- run 0.9 prebuild for macOS 10.11+

The only thing that worked at leats somewhat is using some elses prebuilt 0.5 nvim.

**Comment by clason** [comment]
Yes, if you are on an outdated platform, you'll have to live with using outdated software. No two ways about this.

**Comment by n8an** [comment]
> We don't support macOS < 10.15 (see https://github.com/neovim/neovim/blob/master/runtime/doc/support.txt). Try installing via `homebrew`, if they have wider support.

May I ask why?
Also yes, I tried brew and it also doesn't work.

Does that mean that there is 0 official ways of having nvim 0.8 on a 10.13 system?



> Yes, if you are on an outdated platform, you'll have to live with using outdated software. No two ways about this.

Are you trying to tell me that nvim 0.8 can't run on something simply because Apple just decided to drop support for it?

**Comment by clason** [comment]
> May I ask why? If the github repo says it's built for macOS 10.11+?????

Where? That information is outdated then and needs to be changed.

And "why" is because we rely on dependencies like `libuv` or infrastructure like Github Actions runners; if they drop support, we don't have the resources to replace them.

> Does that mean that there is 0 official ways of having nvim 0.8 on a 10.13 system?

That is correct.

> Are you trying to tell me that nvim 0.8 can't run on something simply because Apple just decided to drop support for it?

No, but if even Apple drops support for it, it makes it _much_ harder -- and too hard for many open source projects -- to keep the infrastructure running.

**Comment by n8an** [comment]
> > May I ask why? If the github repo says it's built for macOS 10.11+?????
> 
> Where? That information is outdated then and needs to be changed.
> 
> And "why" is because we rely on dependencies like `libuv` or infrastructure like Github Actions runners; if they drop support, we don't have the resources to replace them.
> 
> > Does that mean that there is 0 official ways of having nvim 0.8 on a 10.13 system?
> 
> That is correct.
> 
> > Are you trying to tell me that nvim 0.8 can't run on something simply because Apple just decided to drop support for it?
> 
> No, but if even Apple drops support for it, it makes it _much_ harder -- and too hard for many open source projects -- to keep the infrastructure running.

![Знімок екрана 2022-10-30 о 13 48 48](https://user-images.githubusercontent.com/28009384/198876868-d2bf6edd-73a0-4bbc-8a45-722172d908b2.png)

Here.

**Comment by clason** [comment]
Thanks, fixed.

**Comment by n8an** [comment]
Yeah, I've been hitting my head agaisnt a wall for couple of days trying to understand why doesn't something work that says it's supposed to work.
Good luck.

**Comment by justinmk** [comment]
> We don't support macOS < 10.15

To be clear, we don't _test against_ older macOS versions, nor provide prebuilt binaries. But building from source should usually work. Nvim 0.7 at least should build on older macOS. If Nvim 0.8 isn't building on older macOS versions, that isn't necessarily intentional.
