### ISSUE TITLE
Make reading from stdin more intuitive

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#2087]
In order for nvim to read from stdin it must be explicitly specified on the command line,
i.e. `ls | nvim -` to open nvim with the buffer's contents being the output of `ls`.

Anyways, here's what I think is a more intuitive approach, as done by [iota](https://github.com/gchp/iota):

```
You can also create buffers from stdin.

# open a buffer with the output of `ifconfig`
ifconfig | ./target/iota
```

If we don't already, I'd guess we can just call `isatty(0)` to determine whether to read the opening buffer's contents from stdin.

**Comment by tarruda** [comment]
I think the reason vim/nvim requires the - argument is because by default stdin is used for commands. For example, you can do something like this:`

```sh
echo "70isome text\n\x1b :w some_text.txt\n:q\n" | nvim
```

**Comment by Pyrohh** [comment]
Does anyone actually use that? That seems a bit hacky, as I thought you can just use the `-c` argument... right?

**Comment by justinmk** [comment]
It's not really a clear win. `-` is a very common idiom in CLI tools.

**Comment by ZyX-I** [comment]
@Pyrohh Now try doing this with too much commands. Though I would actually switch to `-S <(<<< $'cmd1\ncmd2\ncmd3\n…')`, but this or the similar option is available only in zsh (the only one accepting `<<<`, others require `echo` or similar), ksh and bash.

**Comment by justinmk** [comment]
I had assumed `echo foo bar | nvim` was interpreted as a *file list*. `nvim -h` should mention the current behavior...

At any rate, on the unbuntu VM I have, `echo ls | nvim` crashes Vim and Nvim.

**Comment by tarruda** [comment]
> I had assumed echo foo bar | nvim was interpreted as a file list. nvim -h should mention the current behavior...

You need `xargs` for that: `echo foo bar | xargs nvim`

**Comment by ZyX-I** [comment]
Not a surprise. I do not remember reading from stdin working ever on my machine without Vim exiting with the following:

```
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...
Vim: Finished.
```

It does not *crash* though on `ls | vim`, neither on `ls | nvim`, though this time it does not bother giving me some warnings.

**Comment by justinmk** [comment]
> It does not crash though on ls | vim

@ZyX-I I realized my error and deleted that part of my comment :)

**Comment by Pyrohh** [comment]
> It's not really a clear win. - is a very common idiom in CLI tools.

Yes, but reading from a pipe when a pipe is provided is more common (at least in non-interactive programs). Given that, I think the win is clear (but very small).

> @Pyrohh Now try doing this with too much commands

Are you referring to the limit of 10 separate `--cmd` arguments, or something else? I wonder why that limit is there in the first place.

**Comment by ZyX-I** [comment]
> Are you referring to the limit of 10 separate --cmd arguments, or something else? I wonder why that limit is there in the first place.

Yes, this one. Because

```C
  int n_commands;                            /* no. of commands from + or -c */
  char_u      *commands[MAX_ARG_CMDS];       /* commands from + or -c arg. */
  char_u cmds_tofree[MAX_ARG_CMDS];          /* commands that need free() */
  int n_pre_commands;                        /* no. of commands from --cmd */
  char_u      *pre_commands[MAX_ARG_CMDS];   /* commands from --cmd argument */
```

. Who on Earth needs a linked list or a garray here? MAX_ARG_CMDS is enough for everybody. (By the way, `main.c` includes garray.h, but this seems unused.)

**Comment by Pyrohh** [comment]
> . Who on Earth needs a linked list or a garray here? MAX_ARG_CMDS is enough for everybody. (By the way, main.c includes garray.h, but this seems unused.)

A user might have no idea why the limit is 10, but I agree that MAX_ARG_CMDS is enough for the vast majority of cases.

**Comment by ZyX-I** [comment]
@Pyrohh Actually, two (commands, pre_commands) garrays should make the code cleaner because you don’t need to deal with `n_*commands` anymore: this is done “automatically”. Currently strings like `parmp->commands[parmp->n_commands++] ` are rather lengthy. Though `commands` need `struct{bool is_S; const char *arg_pointer;}`.

About `commands`: try `vim -u NONE -i NONE -S '/dev/null | echomsg "abc"'`. It is easier to treat `-S` separately and run `do_source` directly (needs modifications so that no expansions will be performed) rather then do escaping and keep `cmds_tofree`.

**Comment by alerque** [comment]
I love the new more intuitive default of reading stdin, but there are times when it gets in the way. I sometimes work in a subshell inside a loop or pipeline with handing stdin and _don't_ want nvim stealing it. Right now the only hack I have is to run `nvim myfile < /dev/null` to make sure it gets its own stdin and doesn't steal the parent loop's.

Is there an easier way like a argument flag or environment variable I can set to suppress this behavior?

**Comment by bfredl** [comment]
But "surpressing the behavior" must imply enabling some _other_ behavior, and what should that be? I've tested with vim 8 things like `cat | vim` and typically it behaves weirdly or just hangs, so the old behavior/"what vim does" is probably not what we want.

> Right now the only hack I have is to run nvim myfile < /dev/null to make sure it gets its own stdin and doesn't steal the parent loop's.

We could add a flag that is equivalent to that (it gets its "own stdin" by doing `< /dev/stderr` internally more or less).

**Comment by alerque** [comment]
> must imply enabling some _other_ behavior

The behavior I'd like to (explicitly) enable in this case is not attempting to read anything of any kind from STDIN.

I'm fully aware of the oddities of piping something into normal `vim`. I like `nvim`'s default behavior. What I'm saying is that there should be a way to not use the new default behavior and instead just ignore STDIN entirely. This is useful for some scripted sequences that have interactive bits along the way.

**Comment by bfredl** [comment]
> What I'm saying is that there should be a way to not use the new default behavior and instead just ignore STDIN entirely.

But nvim should still be interactive? Then the flag I suggested would be the solution.

**Comment by alerque** [comment]
> But nvim should still be interactive? Then the flag I suggested would be the solution.

Yes, and yes.

Should I open a new issue for this? I started comments here because the discussion of the change that partially led to this need is very relevant, but at the same time it's kind of a new feature.

**Comment by bfredl** [comment]
yes a new issue would be good.
