### ISSUE TITLE
Remapping <C-_> (Control + /) not working on neovim 0.8.0

### ISSUE THREAD

**Issue by nmattia** [neovim/neovim#20881]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no, neovim <0.8.0 does not behave the same

### Operating system/version

macOS Ventura 13

### Terminal name/version

iTerm 2

### $TERM environment variable

xterm-256color

### Installation

Nix

### How to reproduce the issue

```
-- Stop highlighting search on C-/
vim.api.nvim_set_keymap('n', '<C-_>', ':noh<CR>', { noremap = true })
```

### Expected behavior

Hitting Ctrl + / should call `:noh`, which used to work before I upgraded to neovim 0.8.0

### Actual behavior

Just hits `/`. Other `<C-...>` mappings work just fine.

**Comment by dundargoc** [comment]
Does it work if you map `<C-/>` instead of `<C-_>`?

**Comment by nmattia** [comment]
Oh it does! Though I'm pretty sure it didn't work in the past. Thanks a lot!

**Comment by ony** [comment]
Behavior is different between terminal. E.g. in Alacritty and xterm terminal I get `<C-_>` but in Foot terminal I get `<C-/>` in Neovim despite that in `cat` I get old `С-_`.
