### ISSUE TITLE
insert mode:  alt+A_KEY on vim used to send "esc + A_KEY" , on nvim it input a character

### ISSUE THREAD

**Issue by allan-simon** [neovim/neovim#2088]
I think it's related with the recent re-factoring changes , but current vim has an interesting feature which is that alt+ any key in insert mode send the touch escape + the key , which make it very practical to not have to reach for the escape key

but it seems this behaviour is gone on current master of nvim , is it currently broken or is a breaking change 'on purpose' ? if so is there a workaround to bring back the old behaviour ?

**Comment by tarruda** [comment]
Esc+KEY is how most terminals represent a key with the alt modifier and now this is parsed nvim as `<a-KEY>`. If you really want to use alt+KEY for leaving insert mode, you can put something like this in your vimrc: `inoremap <a-KEY> <esc>` where KEY is the key you normally use. I recommend using an easier shortcut such as `jj` or `jk`.(See [this](http://vim.wikia.com/wiki/Avoid_the_escape_key) for more info)

**Comment by allan-simon** [comment]
thanks for inoremap <a-KEY> <esc>

as said, it's the conveniency of  alt+key doing  two things at once in one key combination at the opposite of jj / jk etc. doing  1 things in 2 key stroke, so definitely not a good trade.

**Comment by noahfrederick** [comment]
@allan-simon 

This "interesting feature" that Vim has is not a feature, but an accident of how your terminal works, as explained above. It doesn't work in graphical Vims and its utility is questionable. Being able to map a whole new set of chorded keys consistently in Neovim is an excellent trade. However, you should be able to do what you want with mappings:

```vim
let s:printable_ascii = map(range(32, 93), 'nr2char(v:val)')

for s:char in s:printable_ascii
  execute "inoremap <A-" . s:char . "> <Esc>" . s:char
endfor

unlet s:printable_ascii s:char
```

**Comment by kopischke** [comment]
> This "interesting feature" that Vim has is not a feature, but an accident of how your terminal works, as explained above. It doesn't work in graphical Vims and its utility is questionable.ä

Not to mention platform specific. In OS X terminals, Alt+Key translate to extended characters (a system wide, low level behaviour). As @noahfrederick said, this is not a feature, it’s a quirk.

**Comment by allan-simon** [comment]
ok thanks @noahfrederick  and @kopischke  for these informations, I understand better now thanks.

**Comment by allan-simon** [comment]
@noahfrederick I tried to put your conf in my ~/.nvimrc but nothing happen

**Comment by acornejo** [comment]
reminiscent of #2440

**Comment by ssiccha** [comment]
Since my google search directed me to this post and @noahfrederick 's solution only remaps capital letters: 
This code should remap 'all' alt+letter combinations
```vimscript
" let alt 'send' ESC key
let s:printable_ascii = map(range(32, 126), 'nr2char(v:val)')
call remove(s:printable_ascii, 92)
for s:char in s:printable_ascii
    execute "inoremap <A-" . s:char . "> <Esc>" . s:char
endfor
unlet s:printable_ascii s:char
```
Removing position 92 seems to be necessary, since using this code with the "|" character throws an error.

**Comment by wsdjeg** [comment]
@justinmk I think thant is why right click close message area. also alt+key will close

**Comment by justinmk** [comment]
@ssiccha what version are you using? This issue was fixed 5 days ago on master.

**Comment by yura-pakhuchiy** [comment]
@ssiccha @allan-simon 
Here is version which emulates console Alt behaviour for more closely:
1. It maps Alt key for normal mode as well. It does not harm to continue holding Alt in normal mode in console.
2. Allows to use Alt for remapped normal mode keys 
```
set winaltkeys=no
let s:printable_ascii = map(range(32, 126), 'nr2char(v:val)')
call remove(s:printable_ascii, 92)
for s:char in s:printable_ascii
  execute "imap <A-" . s:char . "> <Esc>" . s:char
  execute "nmap <A-" . s:char . "> <Esc>" . s:char
endfor
unlet s:printable_ascii s:char
```
