### ISSUE TITLE
multiple statuslines with external commandline when resizing windows

### ISSUE THREAD

**Issue by max397574** [neovim/neovim#20888]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-77-gf175ca9f7

### Vim (not Nvim) behaves the same?

not relevant I think

### Operating system/version

macOS 11.4

### Terminal name/version

kitty 0.24.4

### $TERM environment variable

xterm-kitty

### Installation

Download releases

### How to reproduce the issue

I'm reproducing this issue with `noice.nvim` because just writing something with external commandline that doesn't make neovim completely unusable is quite hard.
```lua
-- minimal.lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "folke/noice.nvim",
                requires = {
                    "MunifTanjim/nui.nvim",
                    "rcarriga/nvim-notify",
                },
            },
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. "/plugin/packer_compiled.lua",
            display = { non_interactive = true },
        },
    })
end
_G.load_config = function()
    vim.o.lazyredraw = false
    require("noice").setup({})
end
if vim.fn.isdirectory(install_path) == 0 then
    print("Installing plugins and dependencies.")
    vim.fn.system({
        "git",
        "clone",
        "--depth=1",
        "https://github.com/wbthomason/packer.nvim",
        install_path,
    })
end
load_plugins()
require("packer").sync()
vim.cmd(
    [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
)
```
1. `nvim --clean -u minimal.lua`
2. `2<c-w>-`
3. `<c-w>+`
4. `<c-w>+`

### Expected behavior

statusline goes all the way down again

### Actual behavior

two statuslines above each other

**Comment by luukvbaal** [comment]
Setting watchpoints on relevant variables reveals there is some kind of race condition between `cmdline_row` and clearing the command line that causes issues only prevalent when cmdline is externalized. 

`command_height()` sets it to the correct value, but `compute_cmdrow()` decrements it incorrectly at which point `win_setheight_win()` does not clear the new command line area correctly. 

https://github.com/neovim/neovim/pull/21580/commits/935e538b632ba3cb041fb846d2254d92ef981e71 resolves this issue but the fact that `cmdline_row` is set in different places that can cause race conditions still feels wrong.

**Comment by luukvbaal** [comment]
Actually, `ext_messages` is required to reproduce this. I'll add a testcase in https://github.com/neovim/neovim/pull/21580.
