### ISSUE TITLE
Command-line mode mapping using expr and silent together breaks mapping

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#20892]
### Neovim version (nvim -v)

0.9.0 commit g2f9b94a26

### Vim (not Nvim) behaves the same?

n/a but vimscript version in nvim works fine

### Operating system/version

macOS 12.6

### Terminal name/version

nvim-qt, but also tested in TUI with wezterm and kitty

### $TERM environment variable

n/a

### Installation

build from repo

### How to reproduce the issue

nvim --clean

This keymap works as expected, you can scroll up and down e.g., `:edit ` popup and when it's not active, C-n/p do command-line history recall instead.

```
vim.keymap.set('c', '<C-p>', function()
  return vim.fn.wildmenumode() == 1 and '<C-p>' or '<Up>'
end, { expr = true })

vim.keymap.set('c', '<C-n>', function()
  return vim.fn.wildmenumode() == 1 and '<C-n>' or '<Down>'
end, { expr = true })
```

Source and try it out, works as intended, restart clean again and try out:

```
vim.keymap.set('c', '<C-p>', function()
  return vim.fn.wildmenumode() == 1 and '<C-p>' or '<Up>'
end, { expr = true, silent = true })

vim.keymap.set('c', '<C-n>', function()
  return vim.fn.wildmenumode() == 1 and '<C-n>' or '<Down>'
end, { expr = true, silent = true })
```

### Expected behavior

Silent version works the same as non-silent version

### Actual behavior

Periods are entered on the command-line as you go up and down with <C-n/p> when you open `:edit `.  Command-line history recall doesn't seem to work correctly either.

**Comment by craigmac** [comment]
Closing as duplicate of https://github.com/neovim/neovim/issues/20231 unless there's something else missing

**Comment by craigmac** [comment]
Re-opening, `replace_keycodes = false` in opts doesn't seem to do the trick, it just prints literal strings like '<C-n>' and '<C-n>' to the command-line.

**Comment by zeertzjq** [comment]
The equivalent silent Vim script version seems to also have this problem in Nvim and Vim.

**Comment by zeertzjq** [comment]
I don't think this is a bug. `<silent>` prevent command line redrawing from keys in the mapping, but messages and still printed.

**Comment by craigmac** [comment]
@zeertzjq what equivalent Vim script are you using? I just tried:

```
cnoremap <silent><expr> <C-p> wildmenumode() ? '<C-p>' : '<Up>'
cnoremap <silent><expr> <C-n> wildmenumode() ? '<C-n>' : '<Down>'
```

on neovim `0.9.0-g2f9b94a26` and it isn't inserting the periods like I see when using the Lua version. Is that not equivalent? I might be missing some subtlety.

**Comment by zeertzjq** [comment]
It is for me.

**Comment by zeertzjq** [comment]
Yes. The same mapping as the ones you tried.

**Comment by craigmac** [comment]
Reported upstream: https://github.com/vim/vim/issues/11501
