### ISSUE TITLE
Functional bug: typo (spelling error)

### ISSUE THREAD

**Issue by vaibhavspandey** [neovim/neovim#20898]
### Neovim version (nvim -v)

Nvim v0.8.0

### Vim (not Nvim) behaves the same?

not checked

### Operating system/version

nvim-win64

### Terminal name/version

Microsoft Windows [Version 10.0.22000.1098] (win 11)

### $TERM environment variable

not applicable

### Installation

https://github.com/neovim/neovim/releases/tag/v0.8.0

### How to reproduce the issue

nvim --clean
:Tutor
:819
17l

"look at line 819, column 18"
lesson 6.5: SET OPTION-

### Expected behavior

<img width="680" alt="2022-11-01 19_12_13-1 Introduction - OneNote" src="https://user-images.githubusercontent.com/116900185/199247445-457ec634-0f29-4769-97a0-639dad9a234e.png">

### Actual behavior

<img width="498" alt="2022-11-01 19_06_30-Neovim" src="https://user-images.githubusercontent.com/116900185/199247521-ee177861-8cc0-45a8-8162-618438f828b9.png">

**Comment by dundargoc** [comment]
I think the sentence is correct actually.
