### ISSUE TITLE
Keep neovim runnable on embedded systems

### ISSUE THREAD

**Issue by RedX2501** [neovim/neovim#2089]
I think that one of the reasons VIM is so successfull albeit its age and aging plugin system is that it runs on systems where many other editors would fail.

Systems with low resources (RAM, CPU), small screen sizes or use some unknown processor architecturs for which only some obscure c-compiler exists.

The last point is the one i fear most is being disconsidered in this rewrite of vim.

I have been reading a lot about the plans to transform the vim script and similar to lua and make more of it's internal backed by some libs. This is probably wonderful if you are a mainstream (x86, arm) targets developer. If you are one of those poor souls who have to dwell in more obscure platforms and are lucky to be able to use vim it is a real relief to be able to do so. It would be nice of neovim would also try to keep itself usable on those platforms.

The platfor i work on is not so obscure, a Raspberry Pi and Cygwin. But still i'm afraid that NeoVim might not run on one of those due to the fact that one of the many libs it uses is not compatible. It would be a shame if under cygwin one has to use Vim and under Windows is able to use NeoVim.

Just my 2 cents.

**Comment by tarruda** [comment]
> Systems with low resources (RAM, CPU), small screen sizes or use some unknown processor architecturs for which only some obscure c-compiler exists.

I think such systems would not benefit from Neovim extra features

**Comment by justinmk** [comment]
Android and RPi should be reasonable targets, but I am not sure what compromises you are suggesting we make to support those. I don't think we should make any compromises that complicate our primary goal.

**Comment by justinmk** [comment]
@RedX2501 Can you list the use cases for a cygwin client that are not met by launching (or focusing) the GUI client from the cygwin CLI?

**Comment by RedX2501** [comment]
@justinmk One of them is plugins that do not work under windows but under cygwin. Other ones is opening paths relative to the current file using linux paths. Other one is that you practically loose the ability to use `!command` for pretty much all extra programs you installed under cygwin.

**Comment by justinmk** [comment]
> plugins that do not work under windows but under cygwin

Fair point.

> opening paths relative to the current file using linux paths

If you mean on the CLI, you could use `cygpath`:

    nvim `cygpath.exe -aw /cygdrive/c/Users/foo`

That's a bit cumbersome, but just noting it for reference.

> you practically loose the ability to use `!command`

Isn't this just a matter of setting `&shell`, `&shellcmdflag`, etc., to cygwin? I know of several people using this successfully with gvim.exe.

By the way, are you happy with the performance of vim in cygwin? I find it unbearably slow.

**Comment by RedX2501** [comment]
@justinmk Normal movement speed is fine, i don't have too many plugins that require many file operations (that's slow under cygwin) and i disabled ycm at startup and made a key binding to enable it when i need it. Vim has the same startup time as the one i used under linux. Everything else too.

I don't really understand how setting &shell, &shellcmdflag will allow me to do `!chmod +x %`, `!./%` under windows...
