### ISSUE TITLE
Split misc[12].c, structs.h into many other files

### ISSUE THREAD

**Issue by philix** [neovim/neovim#209]
In every software, a module called `utils`, `misc`... soon became home of many unrelated things. In vim this happened a long time ago.

    $ wc -l src/misc1.c
        9039 src/misc1.c
    $ wc -l src/misc2.c
        5371 src/misc2.c

The size of these files make it almost impossible to know what they offer. `misc2.c`, for example, provides functions for handling growing arrays (`ga_*`). A `garray.c` could be extracted from this.

**Comment by LiamMayfair** [comment]
I'd love to contribute some dev hours to nvim for the first time, so after having a look through misc1.c to see what else could be factored out, I think the following functions could be put in a separate file which I've temporarily named 'buffer_edit.c':

* changed
* changedOneline
* changed_bytes
* changed_common
* changed_int
* changed_lines
* changed_lines_buf
* del_bytes
* del_char
* del_chars
* del_lines
* deleted_lines
* deleted_lines_mark
* ins_bytes
* ins_bytes_len
* ins_char
* ins_char_bytes
* ins_str
* unchanged

**Comment by misterex** [comment]
Is someone actively working on this or can I start with this as my first neovim entry level issue ?

**Comment by justinmk** [comment]
Closing this to avoid confusion for entry-level. The low-hanging fruit has been addressed, and we will of course continue down this path as needed.
