### ISSUE TITLE
A weird paste action in visual-block mode

### ISSUE THREAD

**Issue by Fau818** [neovim/neovim#20905]
### Neovim version (nvim -v)

NVIM v0.8.0

### Vim (not Nvim) behaves the same?

no, version 9.0.270

### Operating system/version

macOS 13.0 (22A380)

### Terminal name/version

iTerm2 3.4.16

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

https://user-images.githubusercontent.com/75115028/199373667-bdfdadc6-0f3c-4466-8cfe-7599780c15cb.mov

As shown in the video, I use the default configuration of neovim. 

When I use `"+y` to yank something in visual-block mode, and then I tried to use `"+p` to paste them in visual-block mode, a weird paste result appeared.

But if I only use `y` to yank, and use `p` to paste, it works well.

---

Then, I tried to set the clipboard to the system's clipboard. `set clipboard=unnamedplus`

I repeat the above operation, using `"+y` and `"+p` to yank and paste. (Yes, I know `y` and `p` could get the same effects, BUT I use `"+y` and `"+p`.)

Something unexpected happened, and it works as I expected.

### Expected behavior

If I just use the default config that I needn't `set clipboard=unnamedplus`, and the `"+y` and `"+p` could work well as I expected.

### Actual behavior

As shown in the above video, it performed strangely.

**Comment by justinmk** [comment]
search existing issues for `unnamedplus` (which is a silly option and should be removed imo)
