### ISSUE TITLE
Solargraph somtimes throws errors when try to format on new files

### ISSUE THREAD

**Issue by otavioschwanck** [neovim/neovim#20901]
### Neovim version (nvim -v)

NVIM v0.8.0

### Language server name/version

solargraph 0.47.2

### Operating system/version

Mac

### Steps to reproduce using "nvim -u minimal_init.lua"

require('lspconfig').solargraph.setup {
  flags = {
    debounce_text_changes = 50,
  },
  settings = {
    solargraph = {
      diagnostics = false,
      formatting = true,
      useBundler = true
    }
  }
}

vim.lsp.set_log_level("debug")

local autocommands = {
  { {'BufWritePre'}, {"*.rb"}, function() vim.lsp.buf.format { async = false, filter = function(client) return client.name == "solargraph" end } end, }
}

local au = vim.api.nvim_create_autocmd

for i = 1, #autocommands, 1 do
  au(autocommands[i][1], { pattern = autocommands[i][2], callback = autocommands[i][3] })
end

### Expected behavior

Format correctly

### Actual behavior

Erro detectado ao processar BufWritePre Autocommands for "*.rb":
Error executing lua callback: ...lar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/util.lua:493: Vim:Error executing lua callback: ...lar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/sync.lua:248: attempt to get length of local 'prev_line' (a nil value)
stack traceback:
	...lar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/sync.lua:248: in function 'compute_end_range'
	...lar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/sync.lua:419: in function 'compute_diff'
	...w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:442: in function 'incremental_changes'
	...w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:635: in function 'send_changes'
	...w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:1554: in function <...w/Cellar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp.lua:1548>
	[C]: in function 'nvim_buf_set_text'
	...lar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/util.lua:493: in function 'apply_text_edits'
	...llar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/buf.lua:278: in function 'format'
	/Users/otavio/.config/nvim/lua/user/config.lua:107: in function </Users/otavio/.config/nvim/lua/user/config.lua:107>
stack traceback:
	[C]: in function 'nvim_buf_set_text'
	...lar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/util.lua:493: in function 'apply_text_edits'
	...llar/neovim/0.8.0/share/nvim/runtime/lua/vim/lsp/buf.lua:278: in function 'format'
	/Users/otavio/.config/nvim/lua/user/config.lua:107: in function </Users/otavio/.config/nvim/lua/user/config.lua:107>
"app/business/chain_api/proxy_admin.rb" 7L, 78B gravado(s)

**Comment by justinmk** [comment]
we don't debug language servers
