### ISSUE TITLE
'hlsearch' for search pattern in command range

### ISSUE THREAD

**Issue by RRethy** [neovim/neovim#20902]
### Feature already in Vim?

No

### Feature description

`:/` is like `/` but it won't move then cursor while searching, I'm looking to have this show search matches in the buffer similar to `/` (with `hlsearch`) as you type.

**Comment by zeertzjq** [comment]
`:/` is not a command. It is a range without a command.

**Comment by justinmk** [comment]
Why not use `/` to do the search, then hit `<c-c>:/` to start the command once you are satisfied with the results?

There is also `:help :command-preview` which allows plugins to show a "live preview" as-you-type in the `:` cmdline.

**Comment by RRethy** [comment]
> Why not use / to do the search, then hit <c-c>:/ to start the command once you are satisfied with the results?

That will move the cursor, and in turn can move the entire viewport of the window. The main goal is to search the text showing in the window with highlighting, and have it ready for `n`/`N` after pressing enter without moving the cursor. I have a [plugin](https://github.com/RRethy/vim-tranquille) for this but was hoping to use something builtin. It may seem like a dumb thing to do, but I find it useful pretty frequently.

> There is also :help :command-preview which allows plugins to show a "live preview" as-you-type in the : cmdline.

👁️ 👁️
