### ISSUE TITLE
Updating single elements of 'shada' option

### ISSUE THREAD

**Issue by j-xella** [neovim/neovim#20909]
### Feature description

Hi,

Let's say I want to increase the number of oldfiles without modifying anything else. If I just add this to my `init.lua`  :

```lua
vim.opt.shada:append( "'300" )
```

This will append `'300` to the shada option, but won't remove the original `'100` from it. I have to manually remove it from shada option, which is both verbose and may become wrong if default shada option changes in a later version of nvim.

Considering the way shada option is configured, shouldn't appending `'{XXX}` to shada replace any previous `'{YYY}` that was there?

Same with many other parameters of the shada option.

**Comment by clason** [comment]
No, `append` does (and should do) exactly what it says on the tin: it _appends_ the specified value to the string option. 

Now, it would be possible to add a _new_ method `replace` (or `update`) that takes two arguments: the "pseudoname" (here `'`) and the new value (here `300`) and internally splits the string, removes the old value, and adds the new value. The trick here is that this _must_ work for other pseudostring options as well, e.g., `listchars` -- we're not going to add special behavior for one single option. But then this becomes very tricky (how do you know where the value ends? removing a known value is easy, but not an unknown value).

So I believe the best option (pun intended) here is to change the internal representation of these pseudostrings to a proper table so you can manipulate them directly. This is already planned but will take some time.

**Comment by clason** [comment]
That being said, you can just leave the old value there; specifying the same value multiple times is valid, and then the last value "wins".  So there is no concrete need to remove the `'100` if you want to change it to `'300`.

**Comment by justinmk** [comment]
> you can just leave the old value there; specifying the same value multiple times is valid, and then the last value "wins"

yes, don't see a strong use-case here.
