### ISSUE TITLE
floating windows is not transparent

### ISSUE THREAD

**Issue by 3l0w** [neovim/neovim#20913]
### Neovim version (nvim -v)

v0.9.0-dev-5e1687e-dirty

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Archlinux Linux 6.0.6-arch1-1

### Terminal name/version

kitty 0.26.4

### $TERM environment variable

xterm-kitty

### Installation

AUR neovim-git

### How to reproduce the issue

nvim --clean
lua << EOF
vim.api.nvim_open_win(0, false,  {relative='win', row=10, col=10, width=120, height=15})
EOF

### Expected behavior

The floating window should be transparent and we will see the background of the terminal

### Actual behavior

The floating window is not transparent
![image](https://user-images.githubusercontent.com/37798980/199593285-b577335f-353e-469d-9282-45c8e7fa7007.png)

**Comment by bfredl** [comment]
it is config issue. try modify your color scheme so that `hi NormalFloat guibg=none` .
