### ISSUE TITLE
More secure .exrc (.nvimrc) handling

### ISSUE THREAD

**Issue by gpanders** [neovim/neovim#20911]
### Feature description

The `'exrc'` option is marked deprecated as it's a security risk (with good reason); however, the fact remains that having project or directory local configuration is a valuable feature.

For example, I use an `.exrc` file in some projects to do things like set a default value for `'makeprg'`, to set project-specific filetype mappings with `vim.filetype.add`, and project-specific autocommands.

Plugins exist to provide a more secure version of this feature. A non-exhaustive list:

- https://github.com/MunifTanjim/exrc.nvim
- https://github.com/ii14/exrc.vim
- https://github.com/embear/vim-localvimrc

This issue serves as both a poll on the desirability of this as an upstream feature as well as a place to discuss design/implementation.

At the very least, any implementation would need to:

1. Prompt the user whether or not they want to execute the `.exrc` file found in the current directory (with an option to view its contents)
2. Remember the user's decision so the user is not prompted every time they open nvim. This requires maintaining some kind of mapping from `.exrc` file location to content hash (if the contents of the `.exrc` file change the user should be re-prompted).

Other considerations:

- ~~Should searching for `.exrc` files happen recursively, or only in the current directory?~~ No, it should not be recursive.
- ~~Should these files be sandboxed or otherwise limited in what they are able to do?~~ No
- Can/should this be done in Lua as a "plugin" file that we ship in the runtime? Or does it need to be in the core editor (in C)?

Formal design proposal: https://github.com/neovim/neovim/issues/20911#issuecomment-1301565509

**Comment by ii14** [comment]
My idea was to make it a generic function, so plugins can use it without having to reimplement everything. Neovim would maintain a shared database of files, and a plugin could just use a function that would validate a path, prompt if necessary and return the content.

> Should these files be sandboxed or otherwise limited in what they are able to do?

When you have to explicitly confirm each file, sandboxing is no longer necessary.

**Comment by gpanders** [comment]
>My idea was to make it a generic function, so plugins can use it without having to reimplement everything. Neovim would maintain a shared database of files, and a plugin could just use a function that would validate a path, prompt if necessary and return the content.

Sure that sounds good. I like the format you use in exrc.vim too, so let's assume we'll use that.

Formal design proposal:

* Maintain a database of trusted or blacklisted "secure" files in `stdpath('state')/trust`
* Introduce a new internal C function `read_secure(const char *path)`. This function:
  1. Checks the database for `path`. If it is marked as blacklisted, return `NULL` and print an error message with `emsg`
  2. If it is not blacklisted or if it does not exist in the file, read the contents of `path` into memory. If an error occurs while trying to read `path` (e.g. because the file does not exist or the user does not have permissions), return `NULL` and print an error message
  3. Calculate the SHA256 hash of the contents of `path`
  4. If `path` already exists in the trust database, compare the hash generated in step 3 against the hash listed in the database. If the hash matches, return a pointer to the in-memory contents of `path`
  5. If the hash does not match, or if `path` is not yet listed in the trust database, prompt the user if they want to trust this file. The user is given four options: (t)rust the file, (b)lacklist the file, (i)gnore the file for now (i.e. do nothing), or (v)iew the file contents in a buffer
  6. If the user chooses to trust the file, write the hash and file path to the trust database and return a pointer to the in-memory contents of `path`
  7. If the user chooses to blacklist the file, write a `!` character and the file path to the trust database. Return `NULL`
  8. If the user chooses to view the contents of the file, create a new empty buffer and fill it with the in-memory contents of `path`. Note that it is important to create a new temporary buffer and fill it with the in-memory file contents rather than opening `path` in a buffer directly to avoid a time of check to time of use (TOCTOU) vulnerability. When this buffer is closed, goto step 5.
  9. If the user chooses to ignore the contents of the file, return `NULL`
* Create a Lua interface to this function, `vim.readsecure(path)` that takes a file path and calls the internal `read_secure` function. It returns a string containing the file contents.
* In the startup code, if an `.exrc` or `.nvimrc` file is found in the current directory call `read_secure`. If a non `NULL` pointer is returned, `source` the contents.

**Comment by gpanders** [comment]
>Should searching for .exrc files happen recursively

With `vim.readsecure()` this is not necessary, as the user can do this themselves:

**.exrc**:
```vim
lua<<
for _, f in ipairs(vim.fs.find(".exrc", { upward = true, limit = math.huge })) do
  vim.api.nvim_exec(vim.readsecure(f))
end
.
```
