### ISSUE TITLE
set pastetoggle only works when set after .vimrc

### ISSUE THREAD

**Issue by fishman** [neovim/neovim#2092]
if i `set pastetoggle=<F6>` nothing happens when pressing f6(i think these are all new tui issues.

`nmap <f6> :set paste<cr>` works fine

**Comment by fishman** [comment]
in vim the f keys produce `[17~` where in neovim new tui they produce a string <F6>

**Comment by fishman** [comment]
actually thats not the problem. 

the problem is that in src/nvim/tui/term_input.inl#275 you override the pastetoggle_key from my .vimrc

**Comment by fishman** [comment]
https://github.com/neovim/neovim/commit/59fb8f81723f88935c3b4c7a1c0df4d6db1c2ff8

the bracketed paste breaks setting pastetoggle. it does work if you set it at a later stage.

**Comment by tarruda** [comment]
if you are using a terminal that supports bracketed paste, things should just work without messing with any paste/pastetoggle settings(you dont need https://github.com/ConradIrwin/vim-bracketed-paste for example). Eventually these options will be removed from neovim, the UI layer should take care of this.

If you share a vimrc between vim and neovim, set the option like this:

```vim
if !has('nvim')
  set pastetoggle=<f6>
endif
```

**Comment by fishman** [comment]
i would keep them. it's very unlikely that machines i ssh into. say cloud infrastructure will run neovim anytime soon or anytime at all for that matter.

basically i can't get consistent behaviour. this way, also if you run vim inside of vm's on mac keyboards chances are you won't even have an insert key to begin with.

and how does it work outside of linux?

lastly set pastetoggle in the vimrc should just work. the bracketed paste should not be using the pastetoggle at all, but should instead add a special handling case because that's what it does

**Comment by tarruda** [comment]
> EDIT: don't forget that while it's called pastetoggle. it's useful not just for pasting

What else would you use it for?

**Comment by fishman** [comment]
it disables input maps for example. so if you have something that you want to temporarily disable you can do that. or if you need certain maps that you have bound differently like `<c-v>` `<c-k>` that you want to use in it's base form temporarily.

**Comment by fishman** [comment]
more importantly. there's no guarantee that bracketed paste hack you did for x11 will work across systems and terminal emulators. whereas this works fine     `inoremap <C-v> <esc>:set paste<cr>a<C-R>+<esc>:set nopaste<cr>`

**Comment by lahwran** [comment]
I am having this issue too. I normally have it set to F2. How do I get it set to F2?

**Comment by tarruda** [comment]
> I am having this issue too. I normally have it set to F2. How do I get it set to F2?

You cannot. If you use a terminal that supports bracketed paste neovim will toggle `paste` automatically when you copy data.

**Comment by lahwran** [comment]
Oh. Are you using new terminal things like that? Don't those things reduce the list of people who'll be able to use neovim substantially? Does neovim gracefully degrade? Why not allow use of pastetoggle on terminals that support it, and print a warning in the ui when someone hits the pastetoggle key manually on a terminal that doesn't need it?

**Comment by tarruda** [comment]
> Why not allow use of pastetoggle on terminals that support it, and print a warning in the ui when someone hits the pastetoggle key manually on a terminal that doesn't need it?

I suppose that is a reasonable approach. Can you tell be if this patch helps you?

```diff
diff --git a/src/nvim/tui/term_input.inl b/src/nvim/tui/term_input.inl
index 9a40a64..4e8598f 100644
--- a/src/nvim/tui/term_input.inl
+++ b/src/nvim/tui/term_input.inl
@@ -6,8 +6,6 @@
 #include "nvim/os/input.h"
 #include "nvim/os/rstream.h"

-#define PASTETOGGLE_KEY "<f37>"
-
 struct term_input {
   int in_fd;
   bool paste_enabled;
@@ -269,11 +267,6 @@ static TermInput *term_input_new(void)
   // initialize a timer handle for handling ESC with libtermkey
   uv_timer_init(uv_default_loop(), &rv->timer_handle);
   rv->timer_handle.data = rv;
-  // Set the pastetoggle option to a special key that will be sent when
-  // \e[20{0,1}~/ are received
-  Error err = ERROR_INIT;
-  vim_set_option(cstr_as_string("pastetoggle"),
-      STRING_OBJ(cstr_as_string(PASTETOGGLE_KEY)), &err);
   return rv;
 }

diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index dec2840..2c86e70 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -18,8 +18,10 @@

 typedef struct term_input TermInput;

+#define PASTETOGGLE_KEY "<f37>"
 #include "term_input.inl"

+
 typedef struct {
   int top, bot, left, right;
 } Rect;
@@ -109,8 +111,15 @@ void tui_start(void)
   // Enter alternate screen and clear
   unibi_out(ui, unibi_enter_ca_mode);
   unibi_out(ui, unibi_clear_screen);
-  // Enable bracketed paste
-  unibi_out(ui, (int)data->unibi_ext.enable_bracketed_paste);
+  if (data->unibi_ext.enable_bracketed_paste >= 0) {
+    // Enable bracketed paste
+    // Set the pastetoggle option to a special key that will be sent when
+    // \e[20{0,1}~/ are received
+    Error err = ERROR_INIT;
+    vim_set_option(cstr_as_string("pastetoggle"),
+        STRING_OBJ(cstr_as_string(PASTETOGGLE_KEY)), &err);
+    unibi_out(ui, (int)data->unibi_ext.enable_bracketed_paste);
+  }

   // setup output handle in a separate event loop(we wanna do synchronous
   // write to the tty)
```

Note that this patch only makes a difference if your $TERM variable does not start with xterm, rxvt and you are not inside tmux: https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c#L713-L718 . Unfortunately bracketed paste does not have a terminfo description and there's no reliable way of knowing if the terminal supports it except by looking at environment variables. Another option is to allow the user to set an environment variable to disable automatic paste toggle.

**Comment by lahwran** [comment]
That's cool! that's about half of what I was thinking - the other half is to still listen for the user-set pastetoggle key when on a terminal that is assumed to have the feature, but if the user hits that key, tell them, on the command line at the bottom, "You appear to be on a terminal that supports bracketed paste, and do not need manual paste mode." That way they know what's going on and don't think anything is broken. Also, I'd still enable paste mode when the user presses that, despite printing the warning - that will take care of the far edge case of terminals that have a $TERM that appears to support bracketed paste, but where the terminal actually does not.

**Comment by fishman** [comment]
by the way pasting pasting differently now causing f37 to be inserted at the end of the paste randomly. this is still using pastetoggle for an edge case use case. as i said not every keyboard even has an insert key nowadays. breaking pastetoggle for this is not the right way to do it. bracketed paste should not need to touch pastetoggle at all

**Comment by pdf** [comment]
Overriding pastetoggle really seems like the wrong way to handle this.  If you want to support bracketed paste, I'd think it should be handled in addition to explicit paste, though I understand the appeal of the approach you've taken as the cheap hack to get it in.

I would also note that currently if I *do* `set paste` and then paste something in, paste mode doesn't appear to actually be in effect, even though it's indicated as such in the status line, and bracketed paste *also* doesn't kick in, so pasted content gets processed and messed up.

**Comment by justinmk** [comment]
@pdf There are plans to rework it. Most likely with some new events, e.g. ClipboardPaste, ClipboardYank.

**Comment by houshuang** [comment]
I keep getting <F37> before and after every time I paste with Cmd+V in an iTerm2, very annoying.

**Comment by unphased** [comment]
Can I put in a vote to at least have an option that brings back vim capability? PuTTY users cannot benefit from bracketed paste mode. I think that having bracketed paste mode work for other terminal clients is a bad reason to break functionality for users who need to use clients that don't support it.

**Comment by uxcn** [comment]
I don't know the status on this issue, but I just wanted to add that I'm not sure `pastetoggle` can be completely superseded by bracketed paste.  Specifically, pasting from the `+` and `*` registers doesn't seem to be bracketed.  Possibly there's an argument to default to `paste` mode when using them, but there are still a number of scenarios where not using it can make more sense (e.g. unformatted code).  So, I think there's still a valid argument for explicit paste toggling.

There are some map alternatives to `pastetoggle`, but they aren't equivalent (i.e. toggling `paste` from insert).

What I'm (unfortunately) currently using..

    inoremap <silent> <f3> <c-o>:set nopaste <cr><c-r>+
    inoremap <silent> <f4> <c-o>:set paste <cr><c-r>+<c-o>:set nopaste<cr>

**Comment by tarruda** [comment]
Should be fixed on master

**Comment by pi314** [comment]
Just for a note, `pastetoggle` behaves different between NeoVim and Vim.

Quote from `:help pastetoggle`:

For gVim 7.3 (Sooooorry for keeping 7.3 from disappearing from the world):
```
When the value has several bytes 'ttimeoutlen' applies.
```

For NeoVim 0.3.1 (latest stable release at this point of time:
```
No timeout is used, this means that a multi-key 'pastetoggle' can not be triggered manually.
```

My setting was `set pastetoggle=<leader>p`, guess I have to replace it with `inoremap`.

**Comment by pi314** [comment]
@justinmk Hey you are right.
It turns out I can't use `Ctrl`+`v` or `Shift`+`Insert` to paste code because Nvim just insert `^V` and `<S-Insert>`, respectively.
So I have to paste it from `*` register and everything works fine :)

(Windows 7 with Nvim-qt)

**Comment by mschilli87** [comment]
> It turns out I can't use Ctrl+v or Shift+Insert to paste code because Nvim just insert ^V and <S-Insert>, respectively.

I remember having to use Ctrl + Shift + V in some cases, not sure when and why.
