### ISSUE TITLE
Error detected while processing function ~ ..BufReadPost Autocommands for "*"

### ISSUE THREAD

**Issue by boltlessengineer** [neovim/neovim#20920]
### Neovim version (nvim -v)

v0.9.0-dev-1423+gcc5b7368d-dirty

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

macOS 13.0

### Terminal name/version

iterm2 3.4.16

### $TERM environment variable

xterm-256color

### Installation

brew install nvim --HEAD

### How to reproduce the issue

nvim --clean init.lua
:Tutor

### Expected behavior

`:Tutor` command should not execute an error.

### Actual behavior

```
Error detected while processing function tutor#TutorCmd[38]..BufReadPost Autocommands for "*":
Error executing lua callback: ...llar/neovim/HEAD-cc5b736/share/nvim/runtime/filetype.lua:21: Error ex
ecuting lua: ...llar/neovim/HEAD-cc5b736/share/nvim/runtime/filetype.lua:22: Vim(let):E158: Invalid bu
ffer name: .
stack traceback:
        [C]: in function 'nvim_cmd'
        ...llar/neovim/HEAD-cc5b736/share/nvim/runtime/filetype.lua:22: in function <...llar/neovim/HE
AD-cc5b736/share/nvim/runtime/filetype.lua:21>
        [C]: in function 'nvim_buf_call'
        ...llar/neovim/HEAD-cc5b736/share/nvim/runtime/filetype.lua:21: in function <...llar/neovim/HE
AD-cc5b736/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...llar/neovim/HEAD-cc5b736/share/nvim/runtime/filetype.lua:21: in function <...llar/neovim/HE
AD-cc5b736/share/nvim/runtime/filetype.lua:10>
```

I don't remember the situation exactly, but I've seen this error quite recent in different situation (before I learned about `:Tutor` command).
So I think this is not `:Tutor`'s problem.

**Comment by boltlessengineer** [comment]
I know there are similar issue (#20505) but "removing runtime dir and reinstall" solution didn't work for me, and error message is bit different.

```
brew uninstall neovim
rm -rf ~/.local/share/nvim
```

**Comment by clason** [comment]
That's not the runtime dir. 

Also, are you sure the reproduction steps are correct? `nvim --clean init.lua` looks incorrect.

**Comment by boltlessengineer** [comment]
I'm sure. Only when I open some file (for example, `nvim --clean test.txt`) before running `:Tutor` prints the error message. I tested `nvim --clean`, but `:Tutor` didn't make any errors in that case.

I checked `/usr/local/share/nvim`, but that folder doesn't exist when I reinstalled my neovim with homebrew.

**Comment by clason** [comment]
OK, can reproduce on HEAD. Would be good to have another reproduction without `:Tutor`, otherwise I'm inclined to blame that script here.

**Comment by clason** [comment]
Curiously, I can _not_ reproduce this when running from the build directory via `VIMRUNTIME=./runtime build/bin/nvim`.

**Comment by erw7** [comment]
I am not sure, but the following changes will fix the problem. The original code specifies a buffer whose `file-pattern` matches `.`, which should not be the intended behavior.

```diff
diff --git a/runtime/autoload/tutor.vim b/runtime/autoload/tutor.vim
index abf5c5e2c..005f8ce38 100644
--- a/runtime/autoload/tutor.vim
+++ b/runtime/autoload/tutor.vim
@@ -104,7 +104,7 @@ function! tutor#CheckLine(line)
     if exists('b:tutor_metadata') && has_key(b:tutor_metadata, 'expect')
         let bufn = bufnr('%')
         let ctext = getline(a:line)
-        let signs = sign_getplaced('.', {'lnum': a:line})[0].signs
+        let signs = sign_getplaced('%', {'lnum': a:line})[0].signs
         if !empty(signs)
             call sign_unplace('', {'id': signs[0].id})
         endif
```

or

```diff
diff --git a/runtime/autoload/tutor.vim b/runtime/autoload/tutor.vim
index abf5c5e2c..4da421382 100644
--- a/runtime/autoload/tutor.vim
+++ b/runtime/autoload/tutor.vim
@@ -104,7 +104,7 @@ function! tutor#CheckLine(line)
     if exists('b:tutor_metadata') && has_key(b:tutor_metadata, 'expect')
         let bufn = bufnr('%')
         let ctext = getline(a:line)
-        let signs = sign_getplaced('.', {'lnum': a:line})[0].signs
+        let signs = sign_getplaced(bufn, {'lnum': a:line})[0].signs
         if !empty(signs)
             call sign_unplace('', {'id': signs[0].id})
         endif
```

> Curiously, I can not reproduce this when running from the build directory via VIMRUNTIME=./runtime build/bin/nvim.


Probably because `VIMRUNTIME` contains `.` and it matches `.` in `file-pattern`. If you specify `VIMRUNTIME` with the full path this problem will occur.
