### ISSUE TITLE
Mapping MacOS keybindings

### ISSUE THREAD

**Issue by hacker-DOM** [neovim/neovim#20974]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

y

### Operating system/version

MacOS 13.0

### Terminal name/version

kitty 0.26.3

### $TERM environment variable

xterm-kitty

### Installation

homebrew

### How to reproduce the issue

As most Mac users, I would like the traditional MacOS keybindings (Cmd/Option+Arrows/Backspace/Delete) to work in Vim. Since Neovim [does not yet](https://github.com/neovim/neovim/issues/14400) have support for Super modifier, I decided to select a code point in the Private Use Area (Unicode `57344` - `63743`). I configured my terminal[1] to send the sequence `^[[57344u` on Cmd+Backspace.

I then configured Neovim

```
nnoremap <C-[>[57344u d^
```

[1] In `kitty.conf`:

```
map cmd+backspace   send_text all \x1b[57344u
```

### Expected behavior

Pressing cmd+backspace deletes the current line to `^`

### Actual behavior

`^[` is briefly displayed on the right corner

**Comment by zeertzjq** [comment]
You can make it send a key in the list https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional-key-definitions that has a notation in Nvim but is not present on you keyboard, and then map that key.

**Comment by zeertzjq** [comment]
Also see `:h tui-input`
```
The kitty keyboard protocol https://sw.kovidgoyal.net/kitty/keyboard-protocol/
is partially supported, including keypad keys in Unicode Private Use Area.
For example, this sequence is recognized by Nvim as <C-kEnter>: >
	CSI 57414 ; 5 u
and can be used differently from <C-CR> in mappings.
```
