### ISSUE TITLE
Installation issue: I'm trying to update to 0.8.0 but I'm getting this error. " Unsupported file ./nvim-linux64.deb given on commandline"

### ISSUE THREAD

**Issue by tacolegs2004** [neovim/neovim#20978]
### Neovim version (nvim -v)

0.4.0

### Vim (not Nvim) behaves the same?

No, 8.2

### Operating system/version

ChromeOS Version 107.0.5304.92 (Official Build) (64-bit)

### Terminal name/version

Debian 11

### $TERM environment variable

I don't know

### Installation

sudo apt-get install neovim

### How to reproduce the issue

sudo apt-get install ./nvim-linux64.deb

### Expected behavior

It should download the lastest version of debian.

### Actual behavior

Reading package lists... Done
E: Unsupported file ./nvim-linux64.deb given on commandline

**Comment by clason** [comment]
This is a distro issue, not with Neovim itself.
