### ISSUE TITLE
Error when triggering make

### ISSUE THREAD

**Issue by Zilleplus** [neovim/neovim#20989]
### Neovim version (nvim -v)

8.0.0 d367ed9b23d481998d297d812f54b950e5511c24 

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux 3.10.0 (Centos)

### Terminal name/version

MATE Terminal 1.16.3

### $TERM environment variable

xterm

### Installation

build from repo

### How to reproduce the issue

make

### Expected behavior

trigger a build

### Actual behavior

I get the following error:
```
cd .deps && \
	cmake -G 'Ninja'   \
	 /cmake.deps
CMake Error: The source directory "/cmake.deps" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [build/.ran-deps-cmake] Error 1
```

The .deps folder is empty after calling make.

**Comment by clason** [comment]
Looks like the `${PROJECT_SOURCE_DIR}` isn't correctly determined, so that variable is empty.

Can you try with the latest HEAD on `master`?

**Comment by clason** [comment]
What is your CMake version?

**Comment by Zilleplus** [comment]
@clason Thank you for the quick response.

- Same proble om the latest HEAD (31ffc360f2a4aab469a95a55c532f376443bd5fe)
- CMake version 3.16.3

**Comment by dundargoc** [comment]
Can you try running `make distclean` and then `make`? Does the same thing happen?

**Comment by Zilleplus** [comment]
@dundargoc yes the same thing happens.

**Comment by dundargoc** [comment]
Which version of centos and make are you using?

**Comment by Zilleplus** [comment]
@dundargoc I am using  "Centos-7.3.1611"

**Comment by dundargoc** [comment]
Last question before I debug this with a docker build, do you happen to have a `local.mk` file in neovim repo root?

**Comment by Zilleplus** [comment]
@dundargoc I do not have a local.mk file in the neovim repo root.

**Comment by dundargoc** [comment]
I cannot recreate this with the following minimal dockerfile:

```dockerfile
FROM centos:7.3.1611
WORKDIR /home

RUN yum -y install git make wget gcc-c++
RUN wget -qO- https://github.com/Kitware/CMake/releases/download/v3.16.3/cmake-3.16.3-Linux-x86_64.tar.gz | tar xvz
ENV PATH="${PATH}:/home/cmake-3.16.3-Linux-x86_64/bin"

RUN git clone --depth=1 https://github.com/neovim/neovim.git
RUN make -C neovim
```

This gives the following output:

```
mkdir -p ".deps"
cd .deps && \
        cmake -G 'Unix Makefiles'   \
         /home/neovim//cmake.deps
```

**Comment by clason** [comment]
try installin ninja

**Comment by dundargoc** [comment]
Same thing.

```dockerfile
FROM centos:7.3.1611
WORKDIR /home

RUN yum -y install epel-release
RUN yum -y install git make wget gcc-c++ ninja-build cmake3
RUN git clone --depth=1 https://github.com/neovim/neovim.git
RUN make -C neovim
```

gives 

```
mkdir -p ".deps"
cd .deps && \
        /usr/bin/cmake3 -G 'Ninja'   \
         /home/neovim//cmake.deps
```

**Comment by Zilleplus** [comment]
@dundargoc  I'l put some prints in the makefile and get back to you if that's fine with you? I should be able to trace back where "PROJECT_SOURCE_DIR" should be set but is not set.

This centos installation is customized (not by me, so not sure where there are more differences).

**Comment by dundargoc** [comment]
Of course. Although I suspect it's the `MAKEFILE_DIR` in the `Makefile` that isn't being set, so make sure to check that as well.

**Comment by Zilleplus** [comment]
@dundargoc thanks for the tip, it was a fault make binary. This is a first for me, but this can be closed, this is not neovim related.
