### ISSUE TITLE
Lua: version string (semver) comparison API

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#20981]
## Problem

We have several places where we do version string comparison manually, especially in health checks and providers like clipboard (e.g. https://github.com/neovim/neovim/pull/20936 ).

## Proposal

- Add `vim.semver` module with a similar interface as https://github.com/npm/node-semver#usage
    - We probably don't need elaborate things like `semver.satisfies()`
- Alternative: inline https://github.com/kikito/semver.lua
    - Overloads operators like `^` and `>`, this is probably unnecessarily magical. We could remove those features.

### Requirements

- Check the edge cases tested by https://github.com/npm/node-semver and make sure we have tests that make an explicit decision about how we want to handle things. 
- Avoid an overwrought interface. Maybe we could get away with just two functions:
    - `vim.semver.cmp() => -1 | 0 | 1`
    - `vim.semver.parse() => table`
- Accept "v" prefix, and whitespace. Or even start parsing at the first digit ?

**Comment by dundargoc** [comment]
cmp would compare two versions and return -1 if first is greater, 0 if the versions are equal, and 1 if the first is lesser. It's a way to squish semver.gt, semver.lt and semver.eq into a single function.

I'm not really a fan though, this feels like interface golfing. Whether a greater than should be -1 or 1 is completely arbitrary so you'd need to look it up every time.

**Comment by max397574** [comment]
the alternative would be to add multiple functions I think

**Comment by alanfortlink** [comment]
Hi @max397574, are you working on this? Could you share what you've been working on?  I hope I'm not bothering but I was thinking of an interface like [this](http://tpcg.io/_D1AJ76) if you haven't started something else already :)

**Comment by justinmk** [comment]
> I was thinking of an interface like [this](http://tpcg.io/_D1AJ76)

I think we'd want to expose a `parse()` function also which returns a dict (table) of the version, as mentioned in the Requirements.

**Comment by justinmk** [comment]
ideally we would start with trying to pass the tests given in https://github.com/kikito/semver.lua/blob/master/spec/semver_spec.lua . We could also start with the implementation there, as I mentioned...

**Comment by kelly-lin** [comment]
> ideally we would start with trying to pass the tests given in https://github.com/kikito/semver.lua/blob/master/spec/semver_spec.lua . We could also start with the implementation there, as I mentioned... is there some reason you didn't use that as a starting point?

I did not use https://github.com/kikito/semver.lua/blob/master/spec/semver_spec.lua as a starting point because there are some behaviours in that code which are not consistent with the specifications published by https://semver.org/. For example, when passed a version string which is not in valid "version core" form: `semver.parse('v2.0)` gets coerced to "2.0.0" when it get parsed.

Do we want this type of "padding" or coercion in our implementation? Or stick strictly to what is outlined by the semver spec?

**Comment by justinmk** [comment]
> For example, when passed a version string which is not in valid semver "version core" form: `semver.parse('v2.0)'` gets coerced to "2.0.0" when it get parsed.
> 
> Do we want this type of "padding" or coercion in our implementation? Or stick strictly to what is outlined by the semver spec and throw an error in this scenario?

This module is intended for a "[situated](https://gwern.net/doc/technology/2004-03-30-shirky-situatedsoftware.html)" use-case, so supporting common cases like "v" prefix and incomplete versions (accept "2.0", don't require "2.0.0") makes sense. Because very often, we need to parse version strings reported by random shell tools. 

We can of course have a `strict` flag, so `parse({version='...', strict=true})` requires the version string to conform to semver.org. Probably should default to `strict=false`.

**Comment by kelly-lin** [comment]
> > For example, when passed a version string which is not in valid semver "version core" form: `semver.parse('v2.0)'` gets coerced to "2.0.0" when it get parsed.
> 
> > 
> 
> > Do we want this type of "padding" or coercion in our implementation? Or stick strictly to what is outlined by the semver spec and throw an error in this scenario?
> 
> 
> 
> This module is intended for a "[situated](https://gwern.net/doc/technology/2004-03-30-shirky-situatedsoftware.html)" use-case, so supporting common cases like "v" prefix and incomplete versions (accept "2.0", don't require "2.0.0") makes sense. Because very often, we need to parse version strings reported by random shell tools. 
> 
> 
> 
> We can of course have a `strict` flag, so `parse({version='...', strict=true})` requires the version string to conform to semver.org. Probably should default to `strict=false`.

That makes sense. Thanks. I'll include these changes.

**Comment by justinmk** [comment]
> cmp would compare two versions and return -1 if first is greater, 0 if the versions are equal, and 1 if the first is lesser. It's a way to squish semver.gt, semver.lt and semver.eq into a single function.
> 
> I'm not really a fan though, this feels like interface golfing. Whether a greater than should be -1 or 1 is completely arbitrary so you'd need to look it up every time.

True, let's add gt/lt/eq then.

**Comment by kelly-lin** [comment]
> > cmp would compare two versions and return -1 if first is greater, 0 if the versions are equal, and 1 if the first is lesser. It's a way to squish semver.gt, semver.lt and semver.eq into a single function.
> > I'm not really a fan though, this feels like interface golfing. Whether a greater than should be -1 or 1 is completely arbitrary so you'd need to look it up every time.
> 
> True, let's add gt/lt/eq then.
> 
> Starting out with the golfed interface makes it clear what is really needed. There are a lot of functions on https://github.com/npm/node-semver#functions

Should I add this in my PR?

Btw, what is interface golfing?

**Comment by justinmk** [comment]
> Should I add this in my PR?

No let's finish that PR since it's getting long :) Then consider gt/lt/eq in a followup PR.

**Comment by kelly-lin** [comment]
> > Should I add this in my PR?
> 
> No let's finish that PR since it's getting long :) Then consider gt/lt/eq in a followup PR.

Whups, I just implemented it before I saw your reply. I updated the PR. I can take it out if required.
