### ISSUE TITLE
`:Man` just spins cpu and eats memory

### ISSUE THREAD

**Issue by euclidianAce** [neovim/neovim#20997]
### Neovim version (nvim -v)

0.9.0-dev commit 8147d3d

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

NixOS 22.05 (Linux 5.15.74)

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

screen-256color

### Installation

`nix run github:neovim/neovim?dir=contrib -- --clean`

### How to reproduce the issue

`nix run github:neovim/neovim?dir=contrib -- --clean`
`:Man 3 printf` or any page really

### Expected behavior

The man page for printf to be opened.

### Actual behavior

Neovim stops responding to input, memory usage climbs. Have to pkill nvim before computer freezes.

**Comment by justinmk** [comment]
cannot reproduce this. Does it happen without the `nix` command?

**Comment by euclidianAce** [comment]
I wasn't able to reproduce this on a pc not using NixOS but using the same `nix run` command. And was able to reproduce this by doing a normal (non `nix` build on NixOS) My current hunch is that the `Man` plugin is getting stuck in a symlink loop due to the way NixOS organizes its files and will, for some reason, have a symlink to a folder inside of itself. Currently bisecting and will report back.

**Comment by euclidianAce** [comment]
cba05c5 appears to be the issue, with [this in particular](https://github.com/neovim/neovim/commit/cba05c541d613dc05916b262c0d7d3a10ec08c67#diff-8239808b4443cc9f4ef2fcf4903309926442d8178a0ca60d2bbb3b9933b78a50L438-L447) changing the man invocation from `env FOO=BAR man ...` to `man ...` with a given environment. Odd.

**Comment by euclidianAce** [comment]
With some quick testing the issue seems to stem from the difference between passing the `env` field in libuv's `spawn` vs using the `env` command. `spawn` will _override_ the environment while `env` will _add_ to it. Not super sure why this causes the behavior it does, but switching back to using the `env` command fixes the issue.
