### ISSUE TITLE
Options from *.lua seems to be not sourced in initial buffer

### ISSUE THREAD

**Issue by arbitrary-dev** [neovim/neovim#21004]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no, vim 9.0.99

### Operating system/version

Gentoo

### Terminal name/version

alacritty 0.10.1

### $TERM environment variable

alacritty

### Installation

https://gitweb.gentoo.org/repo/gentoo.git/tree/app-editors/neovim/neovim-0.8.0-r1.ebuild

### How to reproduce the issue

```
$ cat nvim.lua
vim.opt_global.expandtab = true

$ nvim --clean -u nvim.lua
:set expandtab?
```

Other options are affected as well.

New buffers source options correctly though:
```
:e file.txt
:set expandtab?
expandtab
```

### Expected behavior

```
expandtab
```

### Actual behavior

```
noexpandtab
```

**Comment by seandewar** [comment]
`vim.opt_global` sets the global value of a local option, like `:setglobal`.
Use `vim.opt` (or `vim.o`) instead if you want to `:set`.

**Comment by arbitrary-dev** [comment]
Still... It's a bug, and even Vim have different behaviour.

**Comment by arbitrary-dev** [comment]
As a user, I expect my global settings to be applied immediately on `nvim` startup and not only on subsequently opened buffers.

**Comment by seandewar** [comment]
> Still... It's a bug, and even Vim have different behaviour.

No it doesn't?

test.vim
```vim
setglobal expandtab
```

```
vim --clean -u test.vim
set expandtab?
> noexpandtab
```

**Comment by clason** [comment]
How can you confidently claim that, if Vim has no vim.opt_global, and you were presented with a working approach?

**Comment by clason** [comment]
To he clear, the issue here is that you are using the wrong function: the equivalent of set is vim.opt, not vim.opt_global.

**Comment by seandewar** [comment]
> As a user, I expect my global settings to be applied immediately on `nvim` startup and not only on subsequently opened buffers.

Maybe you misunderstand how `:setglobal` works for buffer-local options?
When a buffer is created, it copies the global value of a buffer-local option.

The first buffer is created before the init file. The global value of `expandtab` is false, it copies this value.
Your init file is read. It sets the _global_ value of `expandtab` only to true. This doesn't affect the `expandtab` value of the first buffer.

**Comment by arbitrary-dev** [comment]
>No it doesn't?
Ah, indeed, I used `set` there.

**Comment by arbitrary-dev** [comment]
Thanks for the clarification!
