### ISSUE TITLE
Use vim.lsp.omnifunc instead of the built-in one

### ISSUE THREAD

**Issue by mliszcz** [neovim/neovim#21001]
### Feature description

PR #19003 introduced a feature which automatically sets `omnifunc` to the one provided by the language server if it is not set.

The goal was to reduce the boilerplate code in user configuration:
> This is boilerplate that we may be able to avoid if we can come up with a choice that is uncontroversial enough. I think it would be acceptable if it removes boilerplate for ~90% of the use-cases, while maybe adding a bit of extra config for the remaining 10%.

The problem is that for many languages the ftplugin already sets the completion function to a built-in one which is (most of the time?) worse than the LSP-based one. For example, C++ has `ccomplete#Complete` which is for C and does not work at all with C++. And in this case the LSP on_attach callback will not set `omnifunc` because it is already set.

List of impacted languages:
```
$ rg -l 'setlocal (omnifunc|ofu)' runtime/ftplugin
runtime/ftplugin/html.vim
runtime/ftplugin/zimbu.vim
runtime/ftplugin/cucumber.vim
runtime/ftplugin/xml.vim
runtime/ftplugin/mp.vim
runtime/ftplugin/mf.vim
runtime/ftplugin/php.vim
runtime/ftplugin/sql.vim
runtime/ftplugin/context.vim
runtime/ftplugin/sass.vim
runtime/ftplugin/haskell.vim
runtime/ftplugin/c.vim
runtime/ftplugin/ada.vim
runtime/ftplugin/python.vim
runtime/ftplugin/debchangelog.vim
runtime/ftplugin/ruby.vim
runtime/ftplugin/less.vim
runtime/ftplugin/javascript.vim
runtime/ftplugin/css.vim
```

Would it be possible/acceptable to change the logic introduced in #19003 and take into account the built-in `omnifunc`s and overwrite them as well?

**Comment by mliszcz** [comment]
Thanks for the input. I think I could give this a shot and send a PR in the coming days. The second option sounds feasible. Unfortunately it seems that we do not have an API function that would give the last set location (at least `nvim_get_option`/`nvim_get_option_info` do not have that) and we would need to parse the output from `verbose set omnifunc?`.

**Comment by justinmk** [comment]
> and we would need to parse the output from `verbose set omnifunc?`.

I think so. `vim.fn.execute('verbose set omnifunc?')` is not too bad.

**Comment by mliszcz** [comment]
Hi, I finally started looking at the implementation. I have one concern that I'd like to discuss here before opening a PR.

Currently we only overwrite empty omnifunc and when the client is detached we set it again to an empty value.

Now if we decide to also overwrite values set by ftplugin, it would make sense to restore them when the client is detached. I created a table in the lsp module for this purpose, basically this:
```lua
  --@private
  local function store_initial_value(bufnr, option)
    local key = tostring(bufnr) .. option
    lsp._initial_option_values[key] = vim.bo[bufnr][option]
  end

  --@private
  local function restore_initial_value(bufnr, option)
    local key = tostring(bufnr) .. option
    vim.bo[bufnr][option] = lsp._initial_option_values[key]
    lsp._initial_option_values[key] = nil
  end
```

The problem is that it works only when the client is attached for the first time after the file was opened, because when the value is restored from a lua module, the 'Last set from' information is not present at all.
1. File is opened
2. ftplugin sets omnifunc, verbose has 'Last set from .../ftplugin/...'
3. lsp set_defaults overwrites omnifunc = 'v:lua.vim.lsp.omnifunc'
4. User types :LspStop
5. lsp unset_defaults restores omnifunc = 'ccomplete:Complete'
6. User types :LspStart
7. lsp set_defaults does not overwrite omnifunc because it does not have 'Last set from'

I think that this behavior is inconsistent and does not make much sense from end user pov. I'd rather not store (and not restore) the original value at all. Would that be acceptable?

**Comment by justinmk** [comment]
> I'd rather not store (and not restore) the original value at all. Would that be acceptable?

yes and that's what I would recommend. over-engineering this may end up worse. Anyone that has a working lsp is unlikely to need the non-lsp omnifunc later in the same session. This can simply be a documented limitation.

**Comment by mliszcz** [comment]
Thanks @justinmk for your input. The PR is ready: https://github.com/neovim/neovim/pull/22267
