### ISSUE TITLE
API: empty lua table in a dictionary is converted to list while dict is expected

### ISSUE THREAD

**Issue by doubleloop** [neovim/neovim#21005]
### Neovim version (nvim -v)

v0.9.0-dev-234+g19729e2136

### Vim (not Nvim) behaves the same?

na

### Operating system/version

na

### Terminal name/version

na

### $TERM environment variable

na

### Installation

na

### How to reproduce the issue

```vim
:lua vim.api.nvim_cmd({cmd='split', mods={}}, {})
```

### Expected behavior

`{}` should be treated as empty dict so no error should be produced

### Actual behavior

```
E5108: Error executing lua [string ":lua"]:1: 'mods' must be a Dictionary
stack traceback:
        [C]: in function 'nvim_cmd'
        [string ":lua"]:1: in main chunk
```

**Comment by justinmk** [comment]
> `vim.empty_dict()`

Yes. Though I believe we are in favor of making the Lua <=> API bridge handle this (I thought it already did). The param is defined as `Dict`, so the bridge should be able to deal with this: https://github.com/neovim/neovim/blob/fae754073289566051433fae74ec65783f9e7a6a/src/nvim/api/command.c#L305

**Comment by nolleh** [comment]
this question helped me. 
thx.

**Comment by justinmk** [comment]
VALIDATE macros were introduced in https://github.com/neovim/neovim/pull/22187 .

Next step is to add something like `VALIDATE_DICT` which treats allows empty Array in Lua.
