### ISSUE TITLE
Update "Building on Windows" section in the Wiki

### ISSUE THREAD

**Issue by 3N4N** [neovim/neovim#21043]
### Feature description

This is a proposal to make a few changes to the [Building on Windows][1] section of Building Neovim wiki. The changes pertain to only the "MSYS2 / MinGW" and "MSVC" parts. Other parts ("Cygwin", "CLion") should remain as is.

The proposed changes START HERE.

### Windows / MSYS2 / MinGW

From the MSYS2 shell, install these packages:

```
pacman -S \
    mingw-w64-x86_64-{gcc,libtool,cmake,make,perl,python2,pkg-config,ninja,diffutils}
```

Now, from the Windows Command Prompt (`cmd.exe`), set up the `PATH` and build.

```cmd
set PATH=c:\msys64\mingw64\bin;c:\msys64\usr\bin;%PATH%
```

You have two options:

- Build using `cmake` and `Ninja` generator:

    ```cmd
    mkdir .deps
    cd .deps
    cmake -G Ninja ..\cmake.deps\
    ninja
    cd ..

    mkdir build
    cd build
    cmake -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo ..
    ninja
    ninja install
    ```

    If you cannot install neovim with `ninja install` due to permission restriction, you can install neovim in a directory you have write access to.

    ```cmd
    mkdir build
    cd build
    cmake -G Ninja -D CMAKE_INSTALL_PREFIX=C:\nvim -D CMAKE_BUILD_TYPE=RelWithDebInfo ..
    ninja
    ninja install
    ```

- Or, alternatively, you can use `mingw32-make`:

    ```cmd
    mingw32-make deps
    mingw32-make CMAKE_BUILD_TYPE=RelWithDebInfo
    :: Or you can do the previous command specifying a custom prefix
    :: (Default is C:\Program Files (x86)\nvim)
    :: mingw32-make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=C:\nvim
    mingw32-make install
    ```

### Windows / MSVC

Note: No one has already confirmed that building with the following steps is possible today. See [build.ps1](https://github.com/neovim/neovim/blob/master/ci/build.ps1) for the confirmed steps.

1. Install [Visual Studio](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community) (2017 or later) with the _Desktop development with C++_ workload.
    - On 32-bit Windows, you will need [this workaround](https://developercommunity.visualstudio.com/content/problem/212989/ninja-binary-format.html).
2. Open the Neovim project. Visual Studio automatically starts the build.
3. **IMPORTANT**: Select `x86-Release` configuration instead of `x64-{Debug,Release}`.
    - You can build with the `x64-Release` configuration if `cmake -G "Visual Studio 15 2017 Win64"` is used to build the dependencies. But the _Debug_ configurations will not work because certain dependencies need to be linked with the release version of the C runtime.
    - If the build fails, it may be because Visual Studio started the build with `x64-{Debug,Release}` before you switched the configuration to `x86-Release`.
      - Right-click _CMakeLists.txt → Delete Cache_.
      - Right-click _CMakeLists.txt → Generate Cache_.

**Note**: If you want to build from the command line (i.e., invoke the `cmake` commands yourself), make sure you have the Visual Studio environment variables properly set, which you can do in one of these ways:
- Using the [Visual Studio Developer Command Prompt or Visual Studio Developer PowerShell](https://learn.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2022)
- Invoking `Import-VisualStudioVars` in PowerShell from [this PowerShell module](https://github.com/Pscx/Pscx)

This is to make sure that `luarocks` finds the Visual Studio installation, and doesn't fall back to MinGW with errors like:
```
'mingw32-gcc' is not recognized as an internal or external command
```

The proposed changes END HERE.

[1]: https://github.com/neovim/neovim/wiki/Building-Neovim#building-on-windows

**Comment by dundargoc** [comment]
Thanks, I'll include it!
