### ISSUE TITLE
Windows: exepath() misses extension in powershell & pwsh

### ISSUE THREAD

**Issue by akriese** [neovim/neovim#21045]
### Neovim version (nvim -v)

0.8.0, gd367ed9b2

### Vim (not Nvim) behaves the same?

no, 9.0.868

### Operating system/version

Windows 11

#### Prepare
Go to a folder which is in PATH, create a file called `test` and one called `test.bat`.
`(Get-Command test).Path` test should return the path to `test.bat`

#### using nvim

nvim --clean
:set shell=powershell
:echo exepath("test")

### Expected behavior

Returns `<path_to_test>\test.bat`.

### Actual behavior

Returns `<path_to_test>\test`.

Further explanation:
Powershell prefers to use the bat file, which can be seen from using `(Get-Command test).Path`. When the shell option is not set to `pwsh` or `powershell` (rather set to `cmd`), exepath('test') outputs `test.bat` as expected. 
This behaviour is different to vim, as there the bat path is returned correctly with each shell.

Maybe, the PATHEXT variable has to be used for powershell / pwsh too?

I've found this issue https://github.com/vim/vim/pull/6115 before actually testing my issue on vim vs neovim. It might be related to the matter.

**Comment by erw7** [comment]
This is the behavior described in `:h executable()`. Therefore, this is a specification.

**Comment by akriese** [comment]
Thanks @erw7 for your answer on this. To my understanding, `shell=cmd` and `shell=powershell` should behave exactly the same in the matter. But they don't (in vim, they do). This behavior is not documented in `:h executable()` if I see it correctly.
> On MS-Windows the ".exe", ".bat", etc. can optionally be included.  Then the extensions in $PATHEXT are tried.  Thus if "foo.exe" does not exist, "foo.exe.bat" can be found.
This does not say, which is preferred, if multiple are found. Also that different Windows shells choose different exe-paths makes no sense, if both shells use the same PATH env variable.

Maybe I just give an example again:
Output of the shells:
- cmd.exe
  - `where.exe test` => `<path-to-test>`, `<path-to-test.bat>`
  - `test` => executes `test.bat`
- powershell/pwsh:
  - `where.exe test` => `<path-to-test>`, `<path-to-test.bat>` 
  - `Get-Command test` => `<path-to-test.bat>`
  - `test` => executes `test.bat`

In Neovim (not correct / not documented correctly):
- `set shell=cmd | echo exepath('test')` => prints `<path-to-test.BAT>`
- `set shell=pwsh | echo exepath('test')` => prints `<path-to-test>`

In vim (correct imho):
- `set shell=cmd | echo exepath('test')` => prints `<path-to-test.BAT>`
- `set shell=pwsh | echo exepath('test')` => prints `<path-to-test.BAT>`

-----
A couple lines down in the helptext comes this:
> When 'shell' looks like a Unix shell, then the name is also tried without adding an extension.

Is `powershell` is interpreted as a Unix-like shell? If that is the case, I understand that they behave differently :)

**Comment by erw7** [comment]
> Is powershell is interpreted as a Unix-like shell? If that is the case, I understand that they behave differently :)

Hmm, it looks like [v8.2.3071](https://github.com/vim/vim/commit/127950241e84c822d3c50f46a00d42a70d2d5cb6) of vim has not been merged yet. Changing the following line in the same way as you changed [os_win32.c](https://github.com/vim/vim/commit/127950241e84c822d3c50f46a00d42a70d2d5cb6#diff-6e09d275741ed4a17372f6e64995645e818d605e41a0591b2c20741f4878d3c1
) in vim should fix it. It is a simple change and you should create your own PR if necessary.
https://github.com/neovim/neovim/blob/f1b88ced07a5dcc62cd847cade2ed97e23fffbf9/src/nvim/os/fs.c#L305
