### ISSUE TITLE
[BUG] duplicate undo-history tree nodes, and undos don't change buffer.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2104]
I'm not sure how to replicate, but the undo tree has many extra nodes in it, so for example I press undo multiple times and nothing changes until finally it goes back to a previous node that is actually different.

**Comment by trusktr** [comment]
The tip of my undo tree for ~/.vimrc looks like this:

```
 •   >1007< S (4 seconds ago)
 •    1006    (11 seconds ago)
 | •    1005    (29 seconds ago)
 | •    1004    (29 seconds ago)
 | •    1003    (29 seconds ago)
 | •    1002    (30 seconds ago)
 | •    1001    (44 seconds ago)
 |/
 •    1000    (59 seconds ago)
```

All those repeat nodes are a single change, and should be just one node.

**Comment by trusktr** [comment]
I just discovered that not only are there extra nodes, but undoing changes isn't actually working. I can go to one state, then back, but when I come back the file hasn't changed to the expected state, still in the state of the change in the other node.

**Comment by trusktr** [comment]
I'm not able to produce consistent reproduction behavior, it's random to me at this point.

The plugin I'm using to view the tree is https://github.com/mbbill/undotree

**Comment by tarruda** [comment]
@trusktr do you think you can bisect the commit that introduced this?

**Comment by justinmk** [comment]
@trusktr does this happen with `nvim -u NONE`? I use nvim a lot and I am very particular about undo behvior, but I have not noticed this issue.

Are you using syntastic to auto-format? Does it happen only with a particular filetype?
 Does it happen in Vim?

**Comment by trusktr** [comment]
I can't reproduce right now. I'll just close and re-open if I notice it again. Not ime to bisect (don't even know how to do that) let alone mess around to reproduce it. I've had problems in Vim before, maybe it's not related to Neovim.
