### ISSUE TITLE
`nvim__get_hl_defs` has incorrect results for some links

### ISSUE THREAD

**Issue by folke** [neovim/neovim#21059]
### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

bob

### How to reproduce the issue

```lua
vim.cmd([[hi clear]])
vim.api.nvim_set_hl(0, "Foo", { fg = "red" })
vim.api.nvim_set_hl(0, "Title", { link = "Foo" })
vim.pretty_print(vim.api.nvim__get_hl_defs(0)["Title"])
```

### Expected behavior

This should print

```lua
{
   link = "Foo"
}
```

### Actual behavior

It prints the attributes of the default `Link` group

```lua
{
  bold = true,
  foreground = 16711935
}
```

`:hi Link` gives `Title        xxx ctermfg=225 gui=bold guifg=Magenta links to Foo`

This is due to https://github.com/neovim/neovim/blob/4541c450812bb5252a63307772add143be1ee9c7/src/nvim/highlight_group.c#L1486

The underlying problem seems to be that default attrs are still present after resetting the group

**Comment by AzerAfram** [comment]
Where can I test the snippet under the "How to reproduce the issue" section? I tried simply copying the snippet line by line into the vim terminal, and also pasted the snippet into a `.vim` file to then run the file from the vim terminal. Neither worked.

**Comment by folke** [comment]
Put it in a file like `test.lua`. Open the file in Neovim. Do `:luafile %`
