### ISSUE TITLE
Lua: vim.ui.confirm()

### ISSUE THREAD

**Issue by gpanders** [neovim/neovim#21058]
### Feature already in Vim?

N/A

### Feature description

Round out `vim.ui` with a `vim.ui.confirm()` function. By default this just uses the builtin `confirm()` function.

This function must:

1. Provide the user with a list of options
2. Accept the user's choice with a single key press (i.e. the user simply presses a single key to make their choice, rather than entering a string and pressing "Enter")
3. Visually indicate how a keypress maps to a choice (e.g. using syntax like `(f)oo, (b)ar` to indicate that pressing `b` selects `bar` and pressing `f` selects `foo`)
4. Optionally provide a default choice that will be selected if the user simply presses "Enter" without pressing any other keys

**Comment by Nero-F** [comment]
Hi, I'm interested, can I go for it?

**Comment by gpanders** [comment]
No permission needed. So long as there isn’t already another open PR then anything is fair game.

**Comment by Nero-F** [comment]
It's good to know, thanks.

**Comment by gpanders** [comment]
Quoting @mfussenegger [here](https://github.com/neovim/neovim/pull/21681#issuecomment-1509573053):

>I should probably also point out that I'm no longer sure if exposing these functions with the intention of overriding them was the best choice. There were a couple of PRs that tried to add additional options for vim.ui.select and each time the fact that existing overrides might not support these options was a bit of a problem. See https://github.com/neovim/neovim/pull/20053 for an example.

I agree, and I don’t think we should continue with this pattern. Closing.

**Comment by justinmk** [comment]
>> I'm no longer sure if exposing these functions with the intention of overriding them was the best choice. ... See #20053 for an example.

For reference, from https://github.com/neovim/neovim/pull/19413#issuecomment-1193927300 : 

> Isn't there a risk that an implementation of `vim.ui.input` is not aware of `secret = true` when implementing this as compatible change?


> I agree, and I don’t think we should continue with this pattern. 

What is the alternative, for allowing UI and other "providers" to be overridden? One idea: require "positive confirmation" from providers that they support all expected capabilities.

**Comment by mfussenegger** [comment]
> What is the alternative, for allowing UI and other "providers" to be overridden?

I'd tend towards a pull pattern similar to `:h health-dev`. The table would not only return the functions, but also their capabilities. A `vim.ui.xy()` Would then try to find a provider, use it if it has the right capabilities and if not use a fallback implementation.

**Comment by justinmk** [comment]
> The table would not only return the functions, but also their capabilities

To declare capabilities we can require a special invocation such as `vim.ui.foo({capabilities=true})` to return capabilities.
