### ISSUE TITLE
`nvim_create_user_command` doesn't accept `buffer` key

### ISSUE THREAD

**Issue by Supreeeme** [neovim/neovim#21063]
### Neovim version (nvim -v)

NVIM v0.9.0-dev

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

AUR

### How to reproduce the issue

`nvim --clean`
`:lua vim.api.nvim_create_user_command('Hello', 'echo "hello"', {buffer = true})`

### Expected behavior

This should successfully create a command `Hello` that only exists for the current buffer. The documentation from `:h nvim_create_user_command` suggests that boolean attributes can be used for user commands by just adding them to the opts table:
> To use boolean attributes (such as |:command-bang| or |:command-bar|) set the value to "true".

This works for `bang` and `bar`, but does not work for `buffer`.
The vimscript version of the command also works without issue: `:command -buffer Hello echo "hello"`

### Actual behavior

This error is emitted:
`E5108: Error executing lua [string ":lua"]:1: invalid key: buffer`

**Comment by zeertzjq** [comment]
`nvim_buf_create_user_command`

**Comment by justinmk** [comment]
what documentation change is needed here?

**Comment by zeertzjq** [comment]
I guess a mention that `buffer` is not supported here:
```
      • {opts}     Optional command attributes. See |command-attributes| for
                   more details. To use boolean attributes (such as
                   |:command-bang| or |:command-bar|) set the value to "true".
                   In addition to the string options listed in
                   |:command-complete|, the "complete" key also accepts a Lua
                   function which works like the "customlist" completion mode
                   |:command-completion-customlist|. Additional parameters:
                   • desc: (string) Used for listing the command when a Lua
                     function is used for {command}.
                   • force: (boolean, default true) Override any previous
                     definition.
                   • preview: (function) Preview callback for 'inccommand'
                     |:command-preview|
```
