### ISSUE TITLE
Broken `vim.api.nvim_buf_get_text`

### ISSUE THREAD

**Issue by kylechui** [neovim/neovim#21069]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-319+g743997385

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Pop! OS 22.04

### Terminal name/version

Alacritty

### $TERM environment variable

xterm-256color

### Installation

Appimage

### How to reproduce the issue

1. Run Neovim using `nvim --clean`
2. Populate the buffer with the following contents
```
multiline_func(
    arg1
)
```
3. Run `:lua =vim.api.nvim_buf_get_text(0, 0, 0, 2, 1, {})`

### Expected behavior

It should output the entire contents of the buffer in a table, with each line as its own string:

```lua
{
    "multiline_func(",
    "    arg1",
    ")",
}
```

### Actual behavior

It somehow overwrites the first element with the second, and leaves the second unpopulated:
```lua
{
    "    arg1",
    [3] = ")",
}
```

**Comment by clason** [comment]
Can you bisect?

**Comment by kylechui** [comment]
I'll try that out right now, although it might take a while since this is my first time using `git bisect`.

**Comment by kylechui** [comment]
It seems that on quite a few versions (currently at commit bd122494c), I'm unable to link the C executable; `/usr/bin/ld` is complaining a lot about undefined references:
* `uv__platform_invalidate_fd`
* `uv__io_check_fd`
* ...

I'm not sure how to continue bisecting, sorry

**Comment by lewis6991** [comment]
I'm sure this is going to be my fault.

I'll look into it.

**Comment by clason** [comment]
Need to `make distclean` and build from scratch then, I'm afraid.

**Comment by lewis6991** [comment]
This is most definitely a bug from #19877

**Comment by kylechui** [comment]
I just tested it, it is indeed that commit that introduces the regression.

**Comment by lewis6991** [comment]
#21071 should fix this. Still need to add a test though.

**Comment by kylechui** [comment]
Thanks to both of you for the quick work!
