### ISSUE TITLE
Brute force removal of cscope support is very stupid

### ISSUE THREAD

**Issue by SunJun8** [neovim/neovim#21062]
### Feature already in Vim?

before NVIM v0.9.0

### Feature description

For embedded C developers, in many cases, lsp can't cover all scenarios, and cscope complements lsp nicely. Removing cscope directly would be very silly.

**Comment by jdhao** [comment]
For anyone interested, the relevant PR that removed `cscope` support completely is #20545.

**Comment by rockyzhang24** [comment]
Please be in a polite manner.

**Comment by SunJun8** [comment]
> Please be in a polite manner.

I have retained due restraint on the issue

**Comment by SunJun8** [comment]
neovim is no longer a niche project, it has a large following, even if these people may rarely follow the community and participate in discussions. The project evolution needs to consider whether the impact on these users is too great, especially the act of removing a feature that is used more frequently and for which there is still not enough of a replacement to cover all user scenarios.

**Comment by Shougo** [comment]
The issue is already discussed in #20545.
You can comment it.
I think it is trade off.
neovim have choosed maintainability.
If you really need the feature, you should use Vim instead.
Vim chooses the compatibility than neovim.

I think to improve LSP is better.

**Comment by kevinhwang91** [comment]
You should pin nvim to 0.8.0 and wait for others to write a tool as a workaround. If no one has done this tool for a long time, you can go back to Vim or change your workflow. I guess the core will never revert that patch IMO.

**Comment by SunJun8** [comment]
> You should pin nvim to 0.8.0 and wait for others to write a tool as a workaround. If no one has done this tool for a long time, you can go back to Vim or change your workflow. I guess the core will never revert that patch IMO.

This feels like I've been laid off by Musk

**Comment by Shougo** [comment]
I think you are awesome C developers.  You can improve the LSP and neovim implementation.
They are OSS.  Why not?

**Comment by clason** [comment]
> The project evolution needs to consider whether the impact on these users is too great, especially the act of removing a feature that is used more frequently and for which there is still not enough of a replacement to cover all user scenarios.

This _has_ been considered, and was deemed to be an acceptable trade-off. Remember that how strongly something impacts you does not correlate at all with how many people it impacts. 

If there is a concrete(!) scenario for cscope that LSP does not cover, ask and people will be happy to help you.

**Comment by SunJun8** [comment]
> This has been considered, and was deemed to be an acceptable trade-off. Remember that how strongly something impacts you does not correlate at all with how many people it impacts.

Agreed

**Comment by bfredl** [comment]
cscope in the _c core_ can be directly replaced by a cscope client as a lua plugin, as an adapter to the internal LSP interfaces (which is already used for things which are not LSP servers). If this _truly_ affects some secret silent majority, I will assume some of them will pick up the torch and write the replacement. Or stick with plain vim or neovim 0.8, those are also alternatives.

**Comment by glacambre** [comment]
>For embedded C developers, in many cases, lsp can't cover all scenarios,

@SunJun8 Just out of curiosity, could you describe what use cases cscope covers that is not covered by LSP?

**Comment by TrimeNSF** [comment]
暴力移除 cscope 支持是非常愚蠢的

**Comment by TrimeNSF** [comment]
cscope is nice, it can quickly locate definitions, but LSP cannot.

**Comment by tcbbd** [comment]
> > For embedded C developers, in many cases, lsp can't cover all scenarios,
> 
> @SunJun8 Just out of curiosity, could you describe what use cases cscope covers and how/why they are not covered by LSP?

Apparently, cscope is useful for navigating linux kernel without compiling it. To use ccls or clangd, you need to first compile the whole kernel to generate compile_commands.json, which is time consuming. Regenerating cscope database feels lightweight when you start to switch among different branches.

**Comment by bfredl** [comment]
There is no need to repeat the already know point that there are individual usecases where cscope are more convenient than clangd (although it is strictly not true you need to compile any c code before using clangd, _configuring_ the project more than well enough).

The decision nvim core has been made is that the **unmaintainable c core implementation** of the ad-hoc cscope protocol has been removed, and this will not be reversed.  we welcome the support of cscope in the form of plugins, the same way as support for servers with extensions beyond LSP is supported by external plugins (which is possible as the LSP protocol implementation is in extendable lua code and not c code frozen inside the binary which cannot be adopted to changes in external processes)
