### ISSUE TITLE
[ Help Wanted ] `nvim_buf_get_mark(0, "<")[1]` can't get current visual-mode position

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#21065]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-312+gc4fcde506

### Vim (not Nvim) behaves the same?

not test

### Operating system/version

Linux UNEXPECTED 6.0.8-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:22 +0000 x86_64 GNU/Linux

### Terminal name/version

Alacritty

### $TERM environment variable

Alacritty

### Installation

AUR

### How to reproduce the issue

Excuse me, I'm trying to write my own comment plugin and I found that `nvim_buf_get_mark(0, "<")[1]` and `nvim_buf_get_mark(0, ">")[1]` getting the last visual row position, I don't know why :sob: 
I've tried `vim.fn.getpos("'<")` but it seems to produce the same result as `nvim_buf_get_mark` too

I wish `nvim_buf_get_mark(0, "<")[1]` can get the current visual mode's line num, can anyone help me?

Appreciate your reply :smile: 

```lua
keymap("v", ";c", function ()

    line_start = api.nvim_buf_get_mark(0, "<")[1]
    line_end   = api.nvim_buf_get_mark(0, ">")[1]

    local lines_table = vim.fn.getline(line_start, line_end)

    for i, line_str in ipairs(lines_table) do
        -- trim space for line_str
        line_str = "-- " .. line_str
        api.nvim_buf_set_lines(0, line_start + i - 2, line_start + i - 1, true, { line_str })
    end

end, { expr = false })
```

### Expected behavior

`nvim_buf_get_mark(0, "<")[1]` can get current viusual mode data

### Actual behavior

1

**Comment by zeertzjq** [comment]
`'<` and `'<` are the last Visual mode position. For the current Visual selection, use `getpos('.')` and `getpos('v')`

**Comment by hinell** [comment]
The problem with `getpos('.')` and `getpos('v')` is that they are flipped and depend on the direction user selects text.  If you start to select from top to bottom, the `.` will have row position  less than `v`. And otherwise if you select bottom to top.

**Comment by hinell** [comment]
The problem with `getpos('.')` and `getpos('v')` is that they depend on the direction that user selects the text (either top to bottom or otherwise).

The `.`  position is always anchored and `v` is being moved around by user.
