### ISSUE TITLE
Switch to SHA256 for 3rdparty bundles

### ISSUE THREAD

**Issue by xu-cheng** [neovim/neovim#2107]
Since https://github.com/Homebrew/homebrew/commit/0223fa1437af76fb4913373fd20b380c9309c51a, Homebrew starts to prefer SHA256 as the default checksum. I will send PR to neovim/homebrew-neovim to reflect such change. 

SHA256 is generally considered as the successor of SHA1 and a much safer hash algorithm.  To make neovim formula consistent with cmake download strategy. I propose to switch to SHA256 for 3rd party bundles. 

I have checked Cmake 1.8.7 has no trouble to handle SHA256. So if no objection, I will send PR to implement such.

**Comment by justinmk** [comment]
Sounds good to me, but @jszakmeister is the cmake expert.

**Comment by jszakmeister** [comment]
It's supported in our minimum CMake version, so switching it should work fine.
