### ISSUE TITLE
vim.lsp.buf.format autocmd stops working when using mutiple buffers

### ISSUE THREAD

**Issue by igorlfs** [neovim/neovim#21098]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-5e1687e-dirty

### Language server name/version

pylsp v1.6.0, lua-language-server v3.6.3

### Operating system/version

Linux 6.0.7

### Steps to reproduce using "nvim -u minimal_init.lua"

<details>
  <summary>minimal_init.lua</summary>

  ```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
	vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
	vim.cmd("packadd packer.nvim")
	install_plugins = true
end

local packer = require("packer")

packer.init({
	package_root = test_dir .. "/pack",
	compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
	use("wbthomason/packer.nvim")
	use("neovim/nvim-lspconfig")

	if install_plugins then
		packer.sync()
	end
end)

local on_attach = function(client, bufnr)
	if client.supports_method("textDocument/formatting") then
		vim.api.nvim_create_autocmd("BufWritePre", {
			group = vim.api.nvim_create_augroup("LspFormatting", {}),
			buffer = bufnr,
			callback = function()
				vim.lsp.buf.format()
			end,
		})
	end
end

require("lspconfig").pylsp.setup({
	on_attach = on_attach,
})

require("lspconfig").sumneko_lua.setup({
	on_attach = on_attach,
})

  ```
</details>

Apologies if this is a misconfiguration issue, but it's been driving me nuts!
1. Open a file, starting the LSP.
2. Open another file. Save it, triggering the automatic formatting.
3. Return to the first file and save it as well. Autoformat won't be triggered.

This behavior is consistent across different LSPs (besides both `pylsp` and `sumneko_lua`, I've also noticed this at least with `jdtls`). Calling `vim.lsp.buf.format()` directly works. There's a [thread](https://neovim.discourse.group/t/lsp-formatting-doesnt-always-work/1884) on neovim's discourse regarding, what I assume to be, a similar issue.

### Expected behavior

Every file should be autoformatted.

### Actual behavior

Only a single file can be autoformatted.

### Log file

https://gist.github.com/igorlfs/f38c1541bc9acfbee448a058aeb4d4ee

**Comment by stasjok** [comment]
> Apologies if this is a misconfiguration issue, but it's been driving me nuts!

I'm pretty sure, that you just clear all your autocommands. You should not use `vim.api.nvim_create_augroup("LspFormatting", {})`. You need something like:
```lua
local augroup = vim.api.nvim_create_augroup("LspFormatting", { clear = false })
vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
```
But it's a bummer that we can't clear only buffer autocommands with `nvim_create_augroup`.

**Comment by igorlfs** [comment]
> I'm pretty sure you're just clearing all your autocommands.

You are correct 😅 
Your suggestion worked, thank you!
Here's my full snippet in case someone comes across this thread:
```lua
    local au = vim.api.nvim_create_autocmd
    local ag = vim.api.nvim_create_augroup
    local clear_au = vim.api.nvim_clear_autocmds

    -- Autoformat on save
    local augroup = ag("LspFormatting", { clear = false })
    if client.supports_method("textDocument/formatting") then
        au("BufWritePre", {
            clear_au({ group = augroup, buffer = bufnr }),
            group = augroup,
            buffer = bufnr,
            callback = function()
                vim.lsp.buf.format()
            end,
        })
    end
```
