### ISSUE TITLE
<esc> is not working properly while in GNU screen

### ISSUE THREAD

**Issue by karoliskoncevicius** [neovim/neovim#21105]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no, vim 9.0.270

### Operating system/version

macOS 13.0.1

### Terminal name/version

Apple terminal 2.13; GNU screen 4.09.00

### $TERM environment variable

screen-256color

### Installation

macports

### How to reproduce the issue

    # 1) pressing escape in insert mode
    screen
    nvim --clean
    ifoobar<esc>

    # 2) pressing escape in insert mode while in :terminal buffer
    screen
    nvim --clean
    :tnoremap <esc> <c-\><c-n>
    :terminal
    ifoobar<esc>

### Expected behavior

    # 1)    
    -- INSERT -- indicator disappears

    # 2)
    :terminal buffer exits insert mode

### Actual behavior

    # 1)
    -- INSERT -- indicator remains visible until another key-press

    # 2)
    terminal buffer is left in insert mode, but can be exited with <c-\><c-n>

    NOTES
    - work as expected if ran without GNU screen
    - VIM works as expected both inside and outside GNU screen

**Comment by zeertzjq** [comment]
For me `vim --clean` behaves the same, and this problem also happens on versions as early as v0.5.1 when mouse is enabled.

**Comment by zeertzjq** [comment]
This seems to be a bug of screen. Esc also does not work properly in screen with:
```sh
printf '\x1b[?1002h\x1b[?1006h'; cat; printf '\x1b[?1002l\x1b[?1006l'
```

**Comment by karoliskoncevicius** [comment]
Everything works after `set mouse =`, @zeertzjq thanks for the tip!

**Comment by justinmk** [comment]
This is in the FAQ. https://github.com/neovim/neovim/wiki/FAQ#esc-in-gnu-screen-is-lost-when-mouse-mode-is-enabled

> This happens because of [a bug in screen](https://savannah.gnu.org/bugs/?60196): in mouse mode, screen assumes that ESC is part of a mouse sequence and will wait an unlimited time for the rest of the sequence, regardless of maptimeout. Until it's fixed in screen, there's no known workaround for this other than double-pressing escape, which causes a single escape to be passed through to Nvim.
