### ISSUE TITLE
Alt- keybindings not working

### ISSUE THREAD

**Issue by akkartik** [neovim/neovim#2112]
In vim I've been relying on `<Esc>x` being triggered when I hold down `Alt` and `x` at once. But this seems to have broken some time between 997892157abcf0b4047ec890520c9f77473d94b9 and 6b7ece6cc89aa35f99d6bd3c078114a7a8a2daa1. I might investigate at some point, but I wanted to give a heads-up. Is anybody able to reproduce? I'm on Ubuntu Linux.

**Comment by noahfrederick** [comment]
Duplicate of https://github.com/neovim/neovim/issues/2088.

**Comment by akkartik** [comment]
:+1:
