### ISSUE TITLE
Lua port for "compiler" command

### ISSUE THREAD

**Issue by ErhanKurnaz** [neovim/neovim#21123]
### Feature already in Vim?

Not in lua

### Feature description

I use the compiler command quite a bit, usually in ftplugins. Currently there is no way to do this through lua. I've just been using a simple ```vim.cmd[[compiler <compiler>]]```, but it would be nice to do this with a simple lua function. It would make sense to put this in the fn submodule, so you would use it like ```vim.fn.compiler('<compiler>')```.

**Comment by clason** [comment]
Note that `vim.fn` is _purely_ for accessing existing vimscript functions from Lua, so we'll never put any new Lua function under it.

**Comment by ErhanKurnaz** [comment]
> 

ah, i didn't know that i could do that. My bad
