### ISSUE TITLE
[LSP] Rename, no matching Language servers with rename capability

### ISSUE THREAD

**Issue by sny-boy** [neovim/neovim#21128]
### Neovim version (nvim -v)

v0.8.1

### Language server name/version

bash-lsp/bash-language-server 3.1.1

### Operating system/version

macos Ventura 13.0.1

### Steps to reproduce using "nvim -u minimal_init.lua"

When modifying the method name, an error message will pop up. Script content:
```
#!/bin/bash

echo "start....."

function waitFinish(){
  if ! "$@"; then
    echo "$* >>> faild"
  else
    echo "$* >>> success"
  fi
}

waitFinish ls -l
echo "Finish -------------"
```

![异常情况](https://user-images.githubusercontent.com/61300279/202881582-8473a152-1624-48c3-b639-3a6410a838aa.gif)

### Expected behavior

The method name can be modified successfully.

### Actual behavior

Method name modification failed, and no LSP exception log is generated

**Comment by glepnir** [comment]
because the bashls does not support rename. https://github.com/bash-lsp/bash-language-server

**Comment by sny-boy** [comment]
> because the bashls does not support rename. https://github.com/bash-lsp/bash-language-server

@glepnir  So that's it. Thank you 🤣
