### ISSUE TITLE
Add Return Characters to `vim.api.nvim_buf_get_lines` or create/expose a Terminal API

### ISSUE THREAD

**Issue by usmcamp0811** [neovim/neovim#21122]
### Feature description

# Summary
I want a way to be able to easily capture properly formatted responses from the Terminal buffer.. or any buffer I guess..

# Current Situation

Sending things to a terminal with the neovim api is pretty nice, but capturing the response is not so. What I mean by this is if I were to do:

```lua
vim.api.nvim_chan_send(job_id, code.."\n")
```

It would perfectly send `code` to my terminal with `job_id`. 

But I have no good way of capturing the response. 

I can run:

```lua
resp = vim.api.nvim_buf_get_lines(bufnr, last_line, -1, false)
```

and get back:

```lua
{ "julia> [3.13", "^2i for i in", " 1:10]", "10-element V", "ector{Float6", "4}:", "      9.7968", "99999999999", "     95.9792", "4960999998", "    940.2991", "105042089", "   9212.0163", "55698683", "  90249.2030", "3514441", " 884162.4172", "150063", "      8.6620", "50785213694e", "6", "      8.4861", "24533766004e", "7", "      8.3137", "71344485215e", "8", "      8.1449", "1864847872e9", "", "julia> " }
```

This is ok but very sub optimal as all the return characters have been stripped and its more or less a jumbled mess. I found that the amount of jumbling is directly correlated with the size of the terminal pane that things are being sent to. I can't seem to find any thing that explicitly states the minimum width of the response so trying to smartly parse the response into a properly formatted response is kind of hard or impossible.  

# Solution Ideas

I don't know what the Terminal or Buffers look like under the hood but it seems like it shouldn't be supper hard to include formatting characters like `\n`, `\t`, `\s` in the response from `vim.api.nvim_buf_get_lines`.

**Comment by justinmk** [comment]
seems like `nvim_buf_attach()` would be more appropriate here, did you try it?

**Comment by bfredl** [comment]
this is an aspect of reflow support #21124 . once the information exists, we could figure a way to expose it.
