### ISSUE TITLE
shellcmdflag default should be smarter on Windows

### ISSUE THREAD

**Issue by emilio** [neovim/neovim#21148]
### Neovim version (nvim -v)

NVIM v0.8.0-1210-gd367ed9b2

### Vim (not Nvim) behaves the same?

No, but note that it's msys2 vim so might be patched etc (VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 23 2022 04:01:15))

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal + msys2

### $TERM environment variable

xterm-256color

### Installation

winget

### How to reproduce the issue

```
$ nvim --clean
```

Type:

```
!ls
```

### Expected behavior

Command executes correctly.

### Actual behavior

```
/usr/bin/bash: /s: No such file or directory
```

This is because `shellcmdflag` is `/s /c` on Windows, even tho the terminal is bash (`shell=C:\msys64\usr\bin\bash.exe`). Maybe this could be detected and the same default as on Unix systems should be applied?

**Comment by emilio** [comment]
There were a fair amount of broken things in my setup even with that fixed, so I had to switch to plain cmd.exe using:

```vim
if has('win32') || has('win64')
  set shell=$COMSPEC
endif
```

in my config. With that the setup works quite nicely.

**Comment by dundargoc** [comment]
@erw7 duplicate of what?

**Comment by erw7** [comment]
> @erw7 duplicate of what?

The title already contains the keywords needed for the search. Thus, @emilio should be able to easily search for duplicate issues. Do you think @emilio is too stupid to search?

Ref. https://github.com/neovim/neovim/issues?q=is%3Aissue+shellcmdflag+label%3Aplatform%3Awindows
Ref. https://github.com/neovim/neovim/issues?q=is%3Aissue+windows+shellcmdflag

**Comment by clason** [comment]
@erw7 I understand the frustration of handling such issues, but that's not really the tone to take with a fellow maintainer who was asking out of genuine interest (so they can mark the next question as duplicate themselves to help you out).

**Comment by emilio** [comment]
Yeah this is a dupe of https://github.com/neovim/neovim/issues/16957. Sorry for filing a bug, I came from another issue which didn't reference that and suggested a new issue for improving the defaults (https://github.com/neovim/neovim/issues/14605#issuecomment-1204109025).

Anyways sorry for filing the duplicate and thanks for all your work on neovim:)
