### ISSUE TITLE
cannot load incompatible bytecode

### ISSUE THREAD

**Issue by DuendeInexistente** [neovim/neovim#21159]
### Neovim version (nvim -v)

I can't tell because -v crashes too

### Vim (not Nvim) behaves the same?

Vim runs fine.

### Operating system/version

ubuntu 22

### Terminal name/version

Not relevant; Crashes in all terminals and with nvim-qt

### $TERM environment variable

xterm-color, but read the above

### Installation

unstable ppa

### How to reproduce the issue

Trying to launch

### Expected behavior

Launching. 

### Actual behavior

Nvim crashes with a bytecode error. Full log output:
```
└─➤ nvim --clean  
vim/_init_packages.lua: cannot load incompatible bytecode
stack traceback:
	[C]: at 0x555ec47fbd74
	[C]: at 0x7fe947aa7ab0
E970: Failed to initialize builtin lua modules
┌─[cammera@HavensNewBase]─[/media/cammera/ExtStor/Juegos/Rimworld/3387]
└─➤ apt show neovim        
Package: neovim
Version: 0.9.0~ubuntu1+git202211220018-5f7560b8d-333b5866f-7a60b4045~ubuntu22.04.1
Priority: optional
Section: editors
Maintainer: Florian Walch <florian+launchpad@fwalch.com>
Installed-Size: 6.352 kB
Provides: editor, vim
Depends: neovim-runtime (= 0.9.0~ubuntu1+git202211220018-5f7560b8d-333b5866f-7a60b4045~ubuntu22.04.1), libc6 (>= 2.34), libluajit-5.1-2 (>= 2.0.4+dfsg)
Breaks: neovim-runtime (<< 0.8.0~~)
Replaces: neovim-runtime (<< 0.8.0~~)
Download-Size: 2.038 kB
APT-Sources: http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu jammy/main amd64 Packages
Description: Fork of Vim aiming to improve user experience, plugins, and GUIs.
 This package is the nightly build from the neovim unstable PPA.

N: There are 3 additional records. Please use the '-a' switch to see them.
```

Running the appimage version works fine.

**Comment by ii14** [comment]
Maybe it links with an incompatible luajit version. `` ldd `which nvim` ``?

**Comment by DuendeInexistente** [comment]
> Maybe it links with an incompatible luajit version. `` ldd `which nvim` ``?

```
└─➤ ldd $(which nvim)
	linux-vdso.so.1 (0x00007ffecb3ac000)
	libgtk3-nocsd.so.0 => /lib/x86_64-linux-gnu/libgtk3-nocsd.so.0 (0x00007f9c1f400000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9c1f319000)
	libluajit-5.1.so.2 => /lib/x86_64-linux-gnu/libluajit-5.1.so.2 (0x00007f9c1f28a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9c1f062000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9c1f65b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9c1f656000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9c1fb45000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9c1f634000)
```

**Comment by ii14** [comment]
`apt show libluajit-5.1-2`?

**Comment by DuendeInexistente** [comment]
└─➤ dpkg -s libluajit-5.1-2
Package: libluajit-5.1-2
Status: install ok installed
Priority: optional
Section: interpreters
Installed-Size: 592
Maintainer: Debian Lua Team <pkg-lua-devel@lists.alioth.debian.org>
Architecture: amd64
Multi-Arch: same
Source: luajit
Version: 2.1.0~beta3+git20220320+dfsg-4.1~bpo22.04.1~ppa1
Replaces: libluajit2-5.1-2
Depends: libluajit-5.1-common (= 2.1.0~beta3+git20220320+dfsg-4.1~bpo22.04.1~ppa1), libc6 (>= 2.34), libgcc-s1 (>= 3.3)
Conflicts: libluajit2-5.1-2
Description: Just in time compiler for Lua - library version
 LuaJIT implements the full set of language features defined by Lua 5.1. The
 virtual machine (VM) is API- and ABI-compatible to the standard Lua interpreter
 and can be deployed as a drop-in replacement.
 .
 This package contains an embeddable version of LuaJIT that can be used as a
 replacement of the standard liblua-5.1 shared library.
Homepage: http://luajit.org
┌─[cammera@HavensNewBase]─[~]

**Comment by ii14** [comment]
Neovim and luajit version looks okay, so maybe neovim was built using some older lua version. Not sure how else to confirm it other than grepping the assembly: `objdump -d --section=.rodata $(which nvim) | grep '1b 4c 4a'`. For this particular luajit version, you should see the exact sequence `1b 4c 4a 02` few times *if* everything is correct.

**Comment by DuendeInexistente** [comment]
Seems correct as well
```
└─➤  objdump -d --section=.rodata $(which nvim) | grep '1b 4c 4a'
  3aa440:	1b 4c 4a 02 02 f2 04 00 04 10 00 1a 00 6a 36 04     .LJ..........j6.
  3aa880:	1b 4c 4a 02 02 bb 01 00 02 07 01 07 00 20 36 02     .LJ.......... 6.
  3b6460:	1b 4c 4a 02 02 96 01 00 02 03 01 07 00 18 39 02     .LJ...........9.
  3b7de0:	1b 4c 4a 02 02 17 00 02 02 00 00 00 04 0b 00 00     .LJ.............
  3b7f80:	1b 4c 4a 02 02 0b 00 01 01 00 00 00 01 4b 00 01     .LJ..........K..
  3b9c60:	1b 4c 4a 02 02 4f 00 01 05 00 05 00 0b 36 01 00     .LJ..O.......6..
  3bc7c0:	1b 4c 4a 02 02 1b 00 00 01 00 01 00 02 27 00 00     .LJ..........'..
  3bdc80:	1b 4c 4a 02 02 c8 04 00 01 0f 00 1a 01 66 12 02     .LJ..........f..

```

**Comment by ii14** [comment]
If you want, as a sanity check you could also check what bytecode version luajit produces. If you have the standalone luajit REPL installed, make sure it links to the same luajit .so library as neovim with `ldd`, and run `luajit -e 'for c in string.dump(function()end):sub(1,4):gmatch"." do print(string.byte(c)) end'`. It should print the sequence `27 76 74 2` (same as `1b 4c 4a 02` but in decimal)

Other than that, I'm not sure what could be wrong here. We are not taking care of that package, so you should probably take it to the people who maintain it.

**Comment by mrreda1** [comment]
If you're still facing this problem
Remove lazy plugins folder `~/.local/share/nvim/lazy/`, then reinstall all your plugins using `:Lazy sync`

**Comment by GhostOps77** [comment]
I had this same issue in ubuntu WSL after compilling luajit locally and installing it. The issue is resolved after installing nvim using appimage file.
