### ISSUE TITLE
Cannot install from .deb package

### ISSUE THREAD

**Issue by OlegGulevskyy** [neovim/neovim#21152]
### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 22.04

### Terminal name/version

Default

### $TERM environment variable

Not sure what this is

### Installation

Deb  package

### How to reproduce the issue

Downloaded .deb package and trying to `sudo apt install <package>`
![image](https://user-images.githubusercontent.com/43781031/203261781-b92140c1-43e2-4e06-8a7c-69d7503d510f.png)
Getting  the error as on the screenshot

### Expected behavior

Able to install the .deb package
I guess I am the only one who gets this, but what can this be related to? I just installed Ubuntu yesterday, there was no changes done apart from it being default.

### Actual behavior

See above

**Comment by zeertzjq** [comment]
It seems that you need to uninstall `neovim-runtime`.

**Comment by OlegGulevskyy** [comment]
Thank you very much! It did the trick exactly, much appreciated!
