### ISSUE TITLE
First invalid {Visual}K freeze neovim for about 30 seconds

### ISSUE THREAD

**Issue by EtiamNullam** [neovim/neovim#21169]
### Neovim version (nvim -v)

v0.9.0-dev-305+g9d7dc5062, v0.8.0-1210-gd367ed9b2

### Vim (not Nvim) behaves the same?

no, 9.0

### Operating system/version

Windows 10

### Terminal name/version

Cmder, Version 1.3.18.1106

### $TERM environment variable

N/A

### Installation

Scoop

### How to reproduce the issue

```
nvim --clean
iaaaa<Esc>
viw
K
```

### Expected behavior

Neovim should quickly report that no help can be found without locking up the editor for such long time, as it happens in vim.

### Actual behavior

Pressing `K` in visual mode will freeze Neovim for about 30 seconds, after which this error is shown:

```
Error executing Lua callback: ...ps\neovim-nightly\current\share\nvim\runtime/lua/man.lua:11: man.lua: "command timed out: man -w man"
stack traceback:
	[C]: in function 'error'
	...ps\neovim-nightly\current\share\nvim\runtime/lua/man.lua:11: in function 'man_error'
	...ps\neovim-nightly\current\share\nvim\runtime/lua/man.lua:76: in function 'system'
	...ps\neovim-nightly\current\share\nvim\runtime/lua/man.lua:291: in function 'get_path'
	...ps\neovim-nightly\current\share\nvim\runtime/lua/man.lua:764: in function 'init'
	...ps\neovim-nightly\current\share\nvim\runtime/lua/man.lua:776: in main chunk
	[C]: in function 'require'
	...neovim-nightly\current\share\nvim\runtime\plugin\man.lua:7: in function <...neovim-nightly\current\share\nvim\runtime\plugin\man.lua:6>
```

Subsequent presses will result in this error:

```
Error executing Lua callback: ...neovim-nightly\current\share\nvim\runtime\plugin\man.lua:7: loop or previous error loading module 'man'
stack traceback:
	[C]: in function 'require'
	...neovim-nightly\current\share\nvim\runtime\plugin\man.lua:7: in function <...neovim-nightly\current\share\nvim\runtime\plugin\man.lua:6>
```

...luckily with no additional delay.

EDIT: Wrapped reproduce instructions in code block, as `<Esc>` is not rendered otherwise.

**Comment by karesztrk** [comment]
Same here on Windows. Neovim v0.8.0-1210-gd367ed9b2

**Comment by 3N4N** [comment]
I can't reproduce with v0.9.0-dev-488 in Windows 11 v22H2.

**Comment by karesztrk** [comment]
It turned out that it happens when you use `tsserver` with Node <v14.

**Comment by 3N4N** [comment]
That's different, though, @karesztrk.  I'm assuming you have `K` mapped to `vim.lsp.buf.hover` in a typescript buffer, and that it's in such a buffer that you're experiencing delay in `K`'s output.  That's a problem with either the LSP server (tsserver) or the client (neovim).  EtiamNullam's issue was about `K`'s delay in a buffer where `K` is not mapped to anything and the `keywordprg` is set to `:Man`.  Two different issues, yours and Etiam's.

**Comment by WillEhrendreich** [comment]
I'm also getting this on windows 10, version 0.9.0-dev-622+g08ebf8d3a

**Comment by EtiamNullam** [comment]
As a workaround you can prevent this freeze by binding `K` to `<Nop>` or anything else, like this:

```vim
map K <Nop>
```

Take note that you won't be able to jump to help files when pressing `K` over a keyword.

**Comment by Raduc4** [comment]
Did someone solve this?
Same error on arch linux
Nvim 0.8.3

**Comment by saffronsnail** [comment]
I am also experiencing this issue on a linux installation which happens not to have man installed (strange I know, but this is where I find myself). Running `:! man` causes a failure to be reported immediately. As expected, the workaround of remapping K works here as well.

**Comment by eyalk11** [comment]
I have this issue on windows. 
```

NVIM v0.9.0-dev-1338+g9e7426718
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info

```

**Comment by omaru-ok** [comment]
im getting the same error on key press 
` K` 
setting
`vim.o.keywordprg = ':help'`  Fix's it? 
but din't Neovim hasn't done anything to fix this for `vanila` nvim ?


```
NVIM v0.9.0
Build type: RelWithDebInfo
```
