### ISSUE TITLE
Switch to alternate file <C-^> broken in Kitty terminal

### ISSUE THREAD

**Issue by MrcJkb** [neovim/neovim#21172]
### Neovim version (nvim -v)

NVIM v0.8.1

### Vim (not Nvim) behaves the same?

yes, 8.2.5172

### Operating system/version

NixOS 22.05

### Terminal name/version

kitty 0.26.2

### $TERM environment variable

xterm-kitty

### Installation

nixpkgs-unstable

### How to reproduce the issue

```
kitty --config NONE
nvim --clean
:e f1
:e f2
<C-^>
```

See also: https://github.com/kovidgoyal/kitty/issues/5702
According to the author, it may be a bug with the way Neovim handles the [kitty keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/).

I am opening this here, because Neovim should support the protocol (#18181) (?)

### Expected behavior

Neovim switches to `f1`

### Actual behavior

Nothing happens

**Comment by page-down** [comment]
You should use `kitty --config=NONE -o clear_all_shortcuts=y` to troubleshoot the issue, because by default there are many `ctrl+shift` shortcuts and they will perform the action without sending it to the program.

Neovim works as expected.

```shell
kitty -o 'map ctrl+shift+6 no_op' nvim -u NONE -c 'edit 1 | edit 2'
# Press Ctrl+Shift+6
```

**Comment by MrcJkb** [comment]
Yes, `map ctrl+shift+6 no_op` seems to solve this issue.
I don't understand how `<C-^>` translates to `<C-Shift-6>`, but I'll take it. 

Thanks for the support!

**Comment by MrcJkb** [comment]
I am having the same issue with <C-}> (for navigating tags)... Does anyone know which kitty keymap could be breaking this?

**Comment by page-down** [comment]
@MrcJkb

> I am having the same issue with <C-}> ...

Not sure if different keyboard layouts affect this, for me the standard US keyboard `shift+]` produces `}`, and this defaults to kitty's `Next Window` action.

**Comment by MrcJkb** [comment]
Ah, thanks. I'm using a keyboard with QMK firmware. Turns out C-} maps to CTRL-LSHIFT(]) under the hood.
