### ISSUE TITLE
Edit visible buffer if exists

### ISSUE THREAD

**Issue by AckslD** [neovim/neovim#21176]
### Feature already in Vim?

No

### Feature description

I sometimes want to edit a file but if it's already visible in some window in some tab instead go there instead of opening the buffer in the current window. For quickfix operations I can do this by setting `switchbuf` to `usetab`. It would be useful to be able to do this similarly for non-quickfix operations such as `edit`. A similar operation exists, `:sbuffer` but acting on buf numbers and therefore only on open files.

I was thinking that it might make sense to add a `sedit` command (or lua api) but wanted to check if others think this makes sense before opening a PR.

In lua I currently do for example:
```lua
local M = {}

--- Same as bufwinid but deals with all tabs.
M.get_global_winid = function(buf)
  local bufinfos = vim.fn.getbufinfo(buf)
  if #bufinfos == 0 then
    return -1
  end
  local windows = bufinfos[1].windows
  if #windows == 0 then
    return -1
  end
  return windows[1]
end

--- Check if a buffer is active.
-- @buf: treated as argument to bufname.
M.is_active = function(buf)
  local winid = M.get_global_winid(buf)
  return winid ~= -1
end

--- Similar to :sbuffer and respects `switchbuf` setting.
-- Edits the @file. If buffer already is active the call sbuffer.
M.sedit = function(file)
  local bufnr = vim.fn.bufnr('^'..file..'$')
  if bufnr == -1 then
    vim.cmd.edit(file)
    return
  end
  if M.is_active(bufnr) then
    vim.cmd.sbuffer(bufnr)
  else
    -- XXX should this call sbuffer also, or alternatively adhere to switchbuf?
    vim.cmd.buffer(bufnr)
  end
end

return M
```

**Comment by seandewar** [comment]
Are you describing `:drop`?

**Comment by AckslD** [comment]
Yes!! Thank you! I would never have guessed that this would be called `drop` but was indeed exactly what I was looking for and of course vim does not disappoint :)
