### ISSUE TITLE
F1-5 on Konsole on Arch Linux Return A-E

### ISSUE THREAD

**Issue by Skipper1931** [neovim/neovim#21187]
### Neovim version (nvim -v)

NVIM v0.8.0

### Vim (not Nvim) behaves the same?

no, vim 9.0.354

### Operating system/version

Arch Linux (6.0.2-arch1-1)

### Terminal name/version

konsole 22.08.2

### $TERM environment variable

xterm-256color

### Installation

Arch User Repository (AUR)

### How to reproduce the issue

nvim --clean
Go into insert mode
Press keys `F1`, `F2`, ..., `F5`

### Expected behavior

Opens help menu when pressing `F1`
Output `<F2>` through `<F5>` when pressing `F2` through `F5`, respectively

This is what happens using xterm. In the below screenshot, the left side is the actual behavior in Konsole, and the right side is the expected behavior in xterm.

![Screenshot from 2022-11-25 02-27-38](https://user-images.githubusercontent.com/19561067/203924760-6722856c-0b96-4392-9338-8031b14d8afd.png)

### Actual behavior

Uppercase letters, `A`, `B`, ... `E` are entered

**Comment by zeertzjq** [comment]
I cannot reproduce.

**Comment by erw7** [comment]
The `konsole` has a setting to change the key input sequence. This will not happen unless you change that setting.

See https://docs.kde.org/stable5/en/konsole/konsole/key-bindings.html.
