### ISSUE TITLE
`WinScrolled` is not emitted in Terminal mode in case of `au TermOpen * startinsert`

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#21197]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-383+g2738f842f

### Vim (not Nvim) behaves the same?

No (see "Expected behavior")

### Operating system/version

EndeavourOS Linux x86_64 (6.0.9-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

### How to reproduce the issue

1. Create init file (called here 'init_terminal-no-winscrolled.vim') with the following content:
```vim
au TermOpen * startinsert

let g:n = 0
au WinScrolled * let g:n = g:n + 1 | echo g:n

set noshowmode
```
2. `nvim -u init_terminal-no-winscrolled.vim`
3. `:vsplit term://bash` . It opens terminal buffer in a split while resizing windows. No echo in command line.
4. Press `<C-\><C-n>`. It leaves Terminal mode and prints 1.

### Expected behavior

`WinScrolled` should be always emitted when windows scroll/resize occurs. 

These situations work as expected:
- Remove `au TermOpen * startinsert` from init file and repeat steps. It prints 1 right after vertical split.
- Replace `au TermOpen * startinsert` with `au TerminalOpen * startinsert` and repeat steps with Vim (using `vertical terminal` instead of `vsplit term://bash`). It also prints 1 right after vertical split while also being in Terminal mode.

### Actual behavior

`WinScrolled` event is emitted right after leaving Terminal mode.

**Comment by zeertzjq** [comment]
This is similar to #19985

**Comment by echasnovski** [comment]
> This is similar to #19985

Maybe.

I tried adding `autocmd TermOpen * doautocmd CursorMoved` both before and after `au TermOpen * startinsert`. It doesn't seem to fix this.

**Comment by zeertzjq** [comment]
I mean, in the case of #19985 the text changed when opening the terminal buffer, but neither `TextChanged` nor `TextChangedI` is triggered, so this case is similar.
