### ISSUE TITLE
Can't resize splitted windows and select text using mouse drag after a random time

### ISSUE THREAD

**Issue by Hettomei** [neovim/neovim#2119]
Hi all,

I always resize my splitted windows using mouse.

When I start neovim : no problem, I can have a lot of splitted windows and resize all with a mouse drag.
But after a random time (I suppose a certain action ?) I can't resize with mouse.

When resize stop working, I cannot select text using mouse (in all mode).

But
+ I can click on different pane to change focus
+ I can click on different tab without problem

Sample of my config : 
 (I have no set ttymouse=.... And I use Terminator on Ubuntu)
```vimrc
if has('mouse')
  set mouse=a
endif
```

This behavior happenned around 2 weeks ago.

Thank you for your work.

**Comment by Hettomei** [comment]
I have more to says  : 

The bug seems to appears when you create a new tab. (:tabnew)

If I never open new tab I never add any problem (with a vim opened for 5 hours)

**Comment by Pyrohh** [comment]
@Hettomei does this still happen now that #2348 was merged? I'm not sure it's related. I'll close this, but please reopen if you can still reproduce the issue.

**Comment by mhinz** [comment]
It's probably https://github.com/neovim/neovim/pull/2383

**Comment by Hettomei** [comment]
Hi,

I just compiled master.

The issue is already present.

Should I reopen ? because it is exactly the same as #2382 

step to reproduce : 
```vim
nvim -u NONE
:set mouse=a
:split
:tabnew
" Then click (with your mouse) on other tabulation, 
" then try to rescale splited windows (with a click and drag)
```

**Comment by mhinz** [comment]
@Hettomei You don't need to reopen, I'll work at it. Updates will be in: https://github.com/neovim/neovim/pull/2383

**Comment by paddor** [comment]
I have this problem in `NVIM v0.2.0`.
