### ISSUE TITLE
Error detected while processing BufReadPost Autocommands for "*"

### ISSUE THREAD

**Issue by 383494** [neovim/neovim#21203]
### Neovim version (nvim -v)

NVIM v0.8.1 (0.8.0 does the same)

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

arch linux

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

system package manager (neovim-git in AUR does the same)

### How to reproduce the issue

`nvim foo`
(`nvim --clean` `:edit foo` doesn't reproduce the issue)

### Expected behavior

the file is opened without errors

### Actual behavior

nvim cannot detect `filetype` if i discard the message.
```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: vim/filetype.lua:0: attempt to call method 'gsub'
 (a nil value)
stack traceback:
        vim/filetype.lua: in function ''
        vim/filetype.lua: in function 'match'
        /usr/share/nvim/runtime/filetype.lua:12: in function </usr/share/nvim/r
untime/filetype.lua:11>
Press ENTER or type command to continue
```
nvim 0.7.2-3 works normally

**Comment by glepnir** [comment]
I think you need provide more information. which filetype you opened and I think you custom something in `BufReadPost` event.

**Comment by 383494** [comment]
filetype: every file that exists, no matter what type

and i did nothing in `BufReadPost`.

**Comment by 383494** [comment]
on another device (arch linux):
```
Error executing lua callback: vim/filetype.lua
:0: attempt to call method 'gsub' (a nil value
)
stack traceback:
        vim/filetype.lua: in function ''
        vim/filetype.lua: in function 'match'
        /usr/share/nvim/runtime/filetype.lua:1
2: in function </usr/share/nvim/runtime/filety
pe.lua:11>
Error executing lua callback: vim/filetype.lua
:0: attempt to call method 'gsub' (a nil value
)
stack traceback:
        vim/filetype.lua: in function ''
        vim/filetype.lua: in function 'match'
        /usr/share/nvim/runtime/filetype.lua:1
2: in function </usr/share/nvim/runtime/filety
pe.lua:11>
```

**Comment by glepnir** [comment]
hmm happen with `nvim --clean` ?  I can't reproduce.

**Comment by 383494** [comment]
You may try `nvim foo` as `nvim --clean` `:edit foo` does not reproduce it.

**Comment by glepnir** [comment]
I mean use `nvim --clean` then open the filetype which you got error. if this way works well then the problem is not neovim I think.

```
1. nvim --clean
2. `:e test.lua` -- or other files that you have.
```

**Comment by zeertzjq** [comment]
`nvim --clean foo`

**Comment by 383494** [comment]
no

**Comment by 383494** [comment]
`nvim --clean foo` doesn't error

**Comment by 383494** [comment]
But does that mean i have to `:source /path/init.vim` every time when i open a file?

**Comment by glepnir** [comment]
something wrong in your config .

**Comment by 383494** [comment]
test config:
```
set cursorline
set number
set ruler
set shiftwidth=4
set tabstop=4
set expandtab
syntax on
```
Is there anything wrong?

**Comment by glepnir** [comment]
test.vim only have your code snippet ,`nvim --clean -u test.vim foo/or some others file`  works fine for me in neovim head version .

**Comment by 383494** [comment]
`nvim --clean -u ~/.config/nvim/init.nvim` works fine

**Comment by clason** [comment]
Please, we need exact reproducing steps. 

(And yes, `syntax on` is wrong: that is not needed in Neovim and usually harmful as it breaks the expected sequence of events -- it's a command, not an option!)

**Comment by 383494** [comment]
I used `/usr/bin/vi` instead of `/usr/bin/nvim` with `alias nvim='vi'`, while I did not install package `vi` and it worked as `nvim` before. When I use `/usr/bin/nvim`, it works normally.
