### ISSUE TITLE
ReviewNinja

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2121]
http://www.review.ninja is a tool that might help with one of the hardest parts of this project, reviewing (*Edit*: see also #2122).

One downside is that it's yet another third-party tool. An advantage is that you can record problems of a PR and individually mark them as fixed (currently the author has to keep track of all issues reported by commenters, and some comments might get lost because of force-pushes).

cc @elmart because this issue has similarities to #1456.

Demo video: http://youtu.be/EUH8P4f803w

Feel free to close anytime, just wanted to share this because I thought it might be useful (for the future, would it be better to use e.g. the mailinglist for stuff like this?).

**Comment by tarruda** [comment]
Looks very interesting, thanks for the link

**Comment by fwalch** [comment]
@Pyroh mentioned gerrithub.io in #2122, at first glance it seems to try to achieve a similar goal.

**Comment by lahwran** [comment]
gerrit is not a nice tool. I would not recommend using it for an open source project where you want to attract reviewers.

**Comment by Pyrohh** [comment]
@lahwran because...?

**Comment by lahwran** [comment]
Its ui is very badly designed, and is confusing and hard to use. It forces a very specific git workflow. It requires special push commands, if you use it directly, though gerrithub probably avoids that.

**Comment by kopischke** [comment]
Having perused [the Gerrit docs](https://gerrit-documentation.storage.googleapis.com/Documentation/2.11/index.html), I tend to agree with @lahwran’s assessment.

**Comment by Pyrohh** [comment]
> Having perused the Gerrit docs, I tend to agree with @lahwran’s assessment

I haven't actually used it, so can't comment on it. I'm generally not a fan of these websites which require a lot of permissions from your GH account, which you need to trust to use. Regardless, this sounds like something that a user can easily do without affecting others.

**Comment by fwalch** [comment]
Looks like ReviewNinja creates a [new Github issue](https://github.com/fwalch/neovim/labels/review.ninja) for each comment a reviewer leaves on a pull request. Not sure if this is what we want.. also, comments posted in the diff on Github unfortunately don't show up in ReviewNinja.

**Comment by Pyrohh** [comment]
That sounds really messy, so unless there's an option to disable that then I don't think it's reasonable to use it.

**Comment by fwalch** [comment]
Yes, unfortunately :-(
It would have been really nice to have something to better keep track of a PR's open issues, but I'll close this for now.. maybe ReviewNinja will be improved at some point.

**Comment by doppioandante** [comment]
@fwalch On servo they use [reviewable](https://reviewable.io/). I've never used it and I don't know whether it has some mechanism to track issues, but they claim that [comment history is preserved](https://github.com/Reviewable/Reviewable/wiki/FAQ#does-reviewable-support-a-git-rebase-workflow)

**Comment by dfarr** [comment]
@fwalch @Pyrohh I am the lead developer of ReviewNinja, in what ways could we improve our service to make it better for for you guys?

**Comment by fwalch** [comment]
Hi @dfarr, thanks for reaching out!

Personally, I think ReviewNinja creating actual Github issues and milestones for a problem with a pull request is a deal breaker. We would have 1500 milestones in this repo by now if we used ReviewNinja from the beginning, and a multiple of that for issues. Having to filter between "real" issues and review comments on a some pull request would make the GH issue tracker very inconvenient to use for developers and probably quite confusing for users.

Also, issues with a pull request are now separated from the actual pull request. Github's "in-diff" (comment attached to line number, e.g. https://github.com/neovim/neovim/pull/2616#discussion-diff-29936314) comments are not used, instead only a link to the line number in question is provided, which is a step backwards IMO.

An alternative I could imagine is to use a special format for comments on Github, adding them at the appropriate locations ("normal" or within diff/attached to line number). Adding comments on commits is not good in our situation, since we often squash commits in a pull request branch, which will cause such a comment to be "lost". Comments on the diff, OTOH, are still shown in Github as "fwalch commented on an outdated diff 8 days ago".

With "special comment format", I mean that there needs to be a way to specify that the indicated issue is now solved.. maybe similar to how Github parses "resolves #XX" in commit messages?

This is just an idea, not sure if it is feasible. But in conclusion, I think as long as ReviewNinja creates new GitHub milestones and issues, we won't use it. That's only my personal view, though, maybe others feel differently.

**Comment by dfarr** [comment]
Thank you so much for your feedback @fwalch!

I have created a proposal incorporating a bunch of your suggestions reviewninja/review.ninja#897 , feel free to check it out and let us know what you think and we could improve even more on.

**Comment by fwalch** [comment]
Reopening this, as the proposed improvements to ReviewNinja sound very promising :-)

**Comment by fwalch** [comment]
ReviewNinja has updated their way of flagging issues, and I like it! I played with it in fwalch/neovim, see e.g. https://github.com/fwalch/neovim/pull/19.

Major plus: You can use it as another "build service", without having to use the ReviewNinja website.

You can post line comments on file diffs on GitHub and use keywords to mark issues, for example "!fix" (see https://github.com/fwalch/neovim/pull/19#discussion_r35017024) if you discovered an issue. The PR author can then resolve this with another keyword, "!fixed" (https://github.com/fwalch/neovim/pull/19#discussion_r35017061). ReviewNinja will flag the build status of the PR as failed if there is an unresolved issue.

The same goes for code reviews. Much as our "LGTM", you can post ":star:", ":+1:", or one of some other keywords in PR comments, and ReviewNinja will count this towards "stars". You can specify how many stars are required until the PR is marked as "reviewed"/"successful".

I think this looks very interesting now; opinions?

**Comment by fmoralesc** [comment]
That looks both useful and unintrusive, I like that.

**Comment by dfarr** [comment]
Hi neovim,

We quietly deployed "review comments" for ReviewNinja a few days ago. You will notice that the documentation (and maybe a few other things) has not yet been updated.  We are working on this now and hope to have a bigger launch later this week or next week.

@fwalch provided a nice summary, we also plan on adding support for removing a ninjastar with a :-1: or -1 comment. This would complete the loop and allow all review to happen in GitHub. 

If you notice any bugs or have an suggestions for improvement please let us know!

**Comment by justinmk** [comment]
GitHub has some review tools now, so I guess we can close this.

**Comment by wsdjeg** [comment]
yeah, keep use github orgin tools, and it will keep all messages or mails together.
