### ISSUE TITLE
Searching for the bar/pipe character | seems to be the same as searching for . (any character)

### ISSUE THREAD

**Issue by nodingneu** [neovim/neovim#21216]
### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

yes, 9.0.2022

### Operating system/version

macOS 12.6.1

### Terminal name/version

Terminal.app 2.12.7

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

`/\|` 

### Expected behavior

Finds "|" characters

### Actual behavior

Finds every character, same behaviour as `/.`

**Comment by zeertzjq** [comment]
Remove the backslash or add `\v` to the beginning.
