### ISSUE TITLE
`vim.keymap.set` disregards `noremap`

### ISSUE THREAD

**Issue by thatvegandev** [neovim/neovim#21248]
### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

n/a (?)

### Operating system/version

maOS 13.0 22A380 arm64

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

explained below

### Expected behavior

More context below, but it seems like `vim.keymap.set` disregards `noremap` entirely? I feel like having `remap` default to false is fine, but only if `noremap` was also not passed. If `noremap` is passed and `remap` isn't, `noremap` preference should be respected.

### Actual behavior

This is the code inside of `vim.keymap.set`
```
if opts.remap == nil then
  -- default remap value is false
  opts.noremap = true
else
  -- remaps behavior is opposite of noremap option.
  opts.noremap = not opts.remap
end

...

vim.api.nvim_set_keymap(m, lhs, rhs, opts)

```

In docs it says:

>  @param opts table - A table of map-arguments such as "silent". In addition to the options listed in vim_set_keymap()

"in addition to the options listed in vim_set_keymap()" suggests that I can pass in `noremap` as well, but it shouldn't if it completely disregards what I pass it. Should I create a PR to update this documentation? Am I missing something?

Also a couple related questions:

1) What's the backstory on why this wrapper to `nvim_set_keymap` was created in the first place? It seems like it just creates more confusion around an already commonly confused topic of `noremap`. 

2) Can anyone example to me the difference between `vim.*` and `vim.api.nvim_*`? For example why is there a `vim.keymap.set` and `vim.api.nvim_set_keymap`. Is the former not part of the neovim API? Why are they namespaced differently?

**Comment by zeertzjq** [comment]
Read a few more lines:
```
                  • noremap: Always overridden with the inverse of "remap"
                    (see below).
```

**Comment by thatvegandev** [comment]
No I saw that, the documentation around it is very fuzzy, though. 

On one end it's telling you `noremap` is an accepted option, but on the other it's telling you it's going to get overridden _by an optional option_ that just _defaults to false._ I think the flaw here is that the documentation shouldn't infer that `noremap` is an accepted option at all.

**Comment by dundargoc** [comment]
@thatvegandev I agree that that sentence is confusing because I was wondering the exact same thing. I'll write an improvement.

> Can anyone example to me the difference between vim.* and vim.api.nvim_*? For example why is there a vim.keymap.set and vim.api.nvim_set_keymap. Is the former not part of the neovim API? Why are they namespaced differently?

I'm explaining the difference and the purpose in an upcoming PR: https://github.com/neovim/neovim/pull/21137
