### ISSUE TITLE
Nvim broken after plugin updates

### ISSUE THREAD

**Issue by ElReyDelJoropo** [neovim/neovim#21258]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-5e1687e-dirty, but first i had v0.8.1

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Arch Linux 6.0.10

### Terminal name/version

st 0.8.5

### $TERM environment variable

st-256color

### Installation

From AUR

### How to reproduce the issue

Opening neovim and trying to use it

### Expected behavior

Before plugin update things works fine

### Actual behavior

Simply after opening a file and try normal workflow nvim populates my screen with a bunch of errors. For example if i insert some lines of code and press escape raise E5108: Error detected while processing InsertLeave Autocommands for "*", if i toggle Nvimtree another E5108 Error: Error for executing lua [string ":lua"]:1: attempt to index a boolean value, and so on

**Comment by clason** [comment]
This very much sounds like an issue with your plugins, not Neovim.
