### ISSUE TITLE
All keymaps of `<M-*>` broken after the last working commit `282dda6`.

### ISSUE THREAD

**Issue by nyngwang** [neovim/neovim#21252]
### Neovim version (nvim -v)

1390e97

### Vim (not Nvim) behaves the same?

Not sure.

### Operating system/version

macOS 13.1

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

build from repo.

### How to reproduce the issue

1. add a `<M-` start keymap, then try to trigger it. E.g.

  ```lua
  vim.keymap.set({'n', 'i', 'x'}, '<M-0>', function () vim.cmd('set nu!') end)
  ```

2. it should fail.

### Expected behavior

the keymap should be trigger by alt + whatever key as per keymap in my config.

### Actual behavior

no reaction.

**Comment by zeertzjq** [comment]
Needs minimal steps to reproduce with `nvim --clean`

**Comment by nyngwang** [comment]
@zeertzjq Closing as I just confirmed that this is caused by some plugin. Sorry about my mis-report!

**Comment by YanniPapandreou** [comment]
@nyngwang out of curiosity which plugin is causing this? I think I might be having the same issue
