### ISSUE TITLE
Eslint vim.lsp.buf.format is not respecting prettier config

### ISSUE THREAD

**Issue by brenoprata10** [neovim/neovim#21254]
### Neovim version (nvim -v)

NVIM v0.8.1

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Nobara 36

### Terminal name/version

GNOME Terminal - Version 3.44.1 for GNOME 42

### $TERM environment variable

Not Applicable

### Installation

sudo dnf install neovim

### How to reproduce the issue

I have just bought a new ssd and decided to try Nobara, so i installed all my config from fresh install. 
I noticed that [eslint LSP](https://github.com/hrsh7th/vscode-langservers-extracted) is not working as expected, my prettier config is not being respected as in neovim v0.7.2.
I tried downgrading my language server, but the result is always the same.
Here is how i configured my LSP:
```
lsp.eslint.setup({
	capabilities = client_capabilities,
	flags = { debounce_text_changes = 500 },
	on_attach = function(client, bufnr)
		client.server_capabilities.document_formatting = true
		if client.server_capabilities.document_formatting then
      			local au_lsp = vim.api.nvim_create_augroup("eslint_lsp", { clear = true })
      			vim.api.nvim_create_autocmd("BufWritePre", {
        			pattern = "*",
        			callback = function()
          				vim.lsp.buf.format(nil)
        			end,
        			group = au_lsp,
      			})
    		end
  	end,
})
```
.eslintrc.js
```
module.exports = {
	env: {
		browser: true,
		es2021: true
	},
	extends: [
		'eslint:recommended',
		'plugin:react/recommended',
		'plugin:@typescript-eslint/recommended',
		'plugin:@typescript-eslint/recommended-requiring-type-checking',
		'prettier'
	],
	ignorePatterns: [".erb/*"],
	overrides: [],
	parser: '@typescript-eslint/parser',
	parserOptions: {
		project: 'tsconfig.json',
		sourceType: 'module'
	},
	plugins: [
		'react',
		'@typescript-eslint',
		'eslint-plugin-import',
		'eslint-plugin-jsdoc',
		'eslint-plugin-prefer-arrow',
		'eslint-plugin-react',
		'react-hooks',
		'prettier'
	],
	rules: {
		indent: 'off',
		'linebreak-style': ['error', 'unix'],
		quotes: ['error', 'single'],
		semi: ['error', 'never'],
		'no-multiple-empty-lines': ['error', {max: 1, maxBOF: 0, maxEOF: 0}],
		'react/react-in-jsx-scope': 'off',
		'react/jsx-filename-extension': [1, {extensions: ['.ts', '.tsx']}],
		"react-hooks/rules-of-hooks": "error",
		"react-hooks/exhaustive-deps": "error",
		'prettier/prettier': 'error',
		'@typescript-eslint/parser': 'off'
	}
}
```

I have a github repo with all my configs and plugins, everything is working fine on my other machines(if i save a buffer, the eslint lsp goes into action respecting my .prettierrc file)

PS: Keep up the great work! I love neovim :smile: 

### Expected behavior

Eslint LSP should not override .prettierrc config on a project

### Actual behavior

Eslint LSP should is overriding .prettierrc config on a project

**Comment by brenoprata10** [comment]
I just tested v0.7.2 on my system and it seems i am still getting the bugged behavior, not really sure what changed from one machine to another, the package versions seems to be quite similar :cry:

**Comment by brenoprata10** [comment]
I just tested 0.8 on my chromebook that was working normally and it seems this bug is not present on 0.7.2. The setup is the same, the only difference if nvim version

**Comment by brenoprata10** [comment]
I have also tested on 0.9 and the same buggy behavior is present

**Comment by mfussenegger** [comment]
Could you run a git bisect to find the commit that introduced the regression? I'm not aware of any changes on the client side that would explain this.

The neovim client isn't aware of any prettier config files. This is something that the language server itself reads.

What the client does do is to provide formatting options based on the `expandtab`, `shiftwidth` and `tabstop` settings.

**Comment by brenoprata10** [comment]
@mfussenegger I decided to do some regression on my own git with nvim config and i noticed this bug started happening after migrating from `client.resolved_capabilities` to `client.server_capabilities` .
In the following video you will notice the following behavior:
v0.7.2 using `server_capabilities` => ESLint does **not** respect prettier
v0.7.2 using `resolved_capabilities` => ESLint respects prettier

v0.8.2 using `server_capabilities` or `resolved_capabilities` => ESLint never respects prettier

I will provide more details once i have more time

[Screen recording 2022-12-04 3.02.04 PM.webm](https://user-images.githubusercontent.com/26099427/205507802-2588d8c1-e7b9-4827-b819-f4007fa1ff60.webm)

**Comment by mfussenegger** [comment]
> will provide more details once i have more time

Did you have some time for that? 

The `resolved_capabilities` change is very unlikely to have had any impact on if a language server uses a config file or not. That's handled by the sever process outside of neovim. But it points towards an issue with your configuration.  Maybe you were actually formatting with null-ls or something and didn't notice it.

**Comment by peterpme** [comment]
:wave: I'm not sure if this is coincidence or not, but I too have recently started experiencing this issue. I'm using null-ls as well. My comment could be noise or, it could be a signal. I just started googling around :)

**Comment by brenoprata10** [comment]
I am not using null-ls in my config BTW

**Comment by diorman** [comment]
You may also have to replace `client.server_capabilities.document_formatting` with `client.server_capabilities.documentFormattingProvider`

https://github.com/neovim/neovim/pull/17814
