### ISSUE TITLE
LSP `untitled` URI scheme

### ISSUE THREAD

**Issue by mskelton** [neovim/neovim#21276]
### Feature already in Vim?

No

### Feature description

VS Code uses a `untitled://` URI scheme for the LSP to enable language servers to know if a file is written to disk or not so that functionality can change if certain operations only work if the file is written to disk.  An example of this is the ESLint language server:

https://github.com/microsoft/vscode-eslint/blob/415526ff31aeb866298514384ad401f2e4d841f5/server/src/eslint.ts#L1057

This came up recently in a pull request I opened in the vscode-eslint project (home of the ESLint language server) where I added some additional code to handle if a file does not exist since Neovim does not implement the same `untitled` URI scheme concept that VS Code does.

https://github.com/microsoft/vscode-eslint/pull/1560

In that PR, the maintainer said this:

> That could lead to strange behavior since the path is used to determine the eslint config file to use.
> 
> IMO catching the exception is not the right approach for this since there are other cases in the code that check for untitled. IMO we should allow the client to announce the untitled scheme and then make the server behave correctly and Neovim should choose the scheme of its liking for unsaved files.

So, with all that context, I wanted to bring up this topic here to understand more about the Neovim maintainers thoughts about the `untitled` URI scheme, is it possible, what are the pros/cons of the approach, etc.

**Comment by justinmk** [comment]
Glancing at https://github.com/microsoft/vscode-eslint/pull/1560 , is the expected behavior that Nvim sends `untitled://` for _every_ never-saved buffer?

**Comment by mskelton** [comment]
So, regarding the LSP spec, it doesn't seem to indicate that `untitled` is "official", but it is mentioned several times in the comments of the spec:

- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentFilter
- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notebookDocumentFilter
- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#fileOperationFilter

> A Uri [scheme](#Uri.scheme), like `file` or `untitled`.

Additionally, I've seen reference to this in the `gopls` language server, though that seems to be more or less a direct copy of the comments from the LSP spec, as I was unable to find an actual use of the `untitled` URI scheme in the source of gopls itself.

https://github.com/golang/tools/blob/f718365b8d687e81808426c2c5eb05c404bd9491/gopls/internal/lsp/protocol/tsprotocol.go#L1886

> Is there actually a reason we need to do that, or it's just an accident? If the LSP protocol expects untitled:// for every never-saved buffer I don't see why Nvim lsp client couldn't do that...

Not sure to be honest, I guess I don't really know enough about the nvim LSP internals to understand a) if it's even possible or b) if it makes sense in the context of nvim.  For my use case of using the ESLint language server I think it would help, my main question is would it somehow have unintended side effects 🤷

**Comment by mfussenegger** [comment]
I think it would be worth creating an issue in the language-server-protocol repository and ask about clarification if clients should use the `untitled` scheme if a file doesn't exist on disk. To me it seems currently kinda undefined, or at least not explicit enough if they are supposed to do that.

There are a couple of language servers which currently don't work well when neovim sends a `didOpen` event for files which don't exist (like eclipse.jdt.ls), while others work well

**Comment by mskelton** [comment]
I found this issue in the LSP specification repo:

https://github.com/microsoft/language-server-protocol/issues/1030#issuecomment-661869686

> Isn't that the same as the untitled:Untitled-1 that is used by vscode?

> Yes, but it is not as a standard in the spec so it might depend on how every client implements this.

**Comment by mskelton** [comment]
https://github.com/microsoft/language-server-protocol/issues/1676

**Comment by justinmk** [comment]
Conclusion from https://github.com/microsoft/language-server-protocol/issues/1676 : 

- Clients should use not use `file:` scheme for in-memory buffers.
    - The choice of client-defined, though [#language-server-protocol/1030](https://github.com/microsoft/language-server-protocol/issues/1030) is requesting it to be defined in LSP.
- If the file for an existing buffer gets deleted, the behavior is undefined. But it's suggested to "not change the URI to an in memory URI since editors usually allow users to save the file again on disk".
    - Caveat: servers  (example: eslint) may crash if we call `textDocument/didOpen` with `file:` scheme for a non-existent file.
