### ISSUE TITLE
Generate docs with treesitter

### ISSUE THREAD

**Issue by ii14** [neovim/neovim#21273]
- Extract docstrings and C attributes with Treesitter
- Parse Doxygen and Emmylua syntax with a handwritten parser
- Format into vimdoc
- Also ship parsed docs as a Lua file, so other tools (like completion plugins) can easily look up documentation for a particular function

One problem is that the C parser neovim ships with can't parse function attributes (`FUNC_API_*`) properly. It parses API functions as a function declaration node with missing semicolon error, then a varying node type for attributes, and lastly the function body as a compound statement. This still can be used to parse all necessary information, but it's relying on invalid syntax. The alternative is to use the https://github.com/nvim-treesitter/tree-sitter-c fork that supports neovim's function attributes.

cc @justinmk @clason

**Comment by clason** [comment]
Just to add to that: I just rebased that parser (which we then would want to pull into the neovim org) on latest upstream master, so it looks like maintaining that fork would not take significant effort.

**Comment by justinmk** [comment]
> The benefit ... would be that we can use standard markdown codeblocks instead of the `<pre>lua` hack we use now

That definitely will be nice, but it's not mentioned in the main description here. Or does "EmmyLua" imply markdown parsing. Helpful to explicitly mention markdown parsing as requirement in any case.

> Parse Doxygen and Emmylua syntax with a handwritten parser

"handwritten" means what exactly? Does that risk something more complicated than the current Doxygen-based solution?

**Comment by ii14** [comment]
> "handwritten" means what exactly? Does that risk something more complicated than the current Doxygen-based solution?

Just processing extracted comments in Lua. Doxygen and emmylua commands can be parsed with simple regexes, and in case of doxygen at least we just need to handle the subset that we're actually using. The slightly more complicated part is the general text processing - splitting text into paragraphs, constructing nested lists, text wrapping - but I don't think it's going to be that bad.

**Comment by lewis6991** [comment]
> Doxygen and emmylua commands can be parsed with simple regexes

This isn't true as emmylua types used by https://github.com/LuaLS/lua-language-server are very non-trivial to parse and do require a dedicated parser. See #22158

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/27480
