### ISSUE TITLE
:terminal size shrinks after opening NERDTree

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2128]
After having a terminal open, then ctrl+n, ctrl+\ to get to normal mode, then opening the NERDTree buffer with leader+f (which is mapped to :NERDTreeToggle) the NERDTree buffer opens and the terminal in the terminal buffer begins to render at the width of the NERDTree buffer. 

Here's a video: http://youtu.be/5x98CHrBQrA

(@tarruda)

**Comment by tarruda** [comment]
I will investigate, thanks

**Comment by justinmk** [comment]
I assume this is a dup of the reflow issue https://github.com/neovim/neovim/issues/2514

**Comment by trusktr** [comment]
@justinmk It seems to be something different. After opening the NERDTree buffer, the width of the rendered part of the terminal buffer becomes the width of the NERD buffer despite the fact that window width of the terminal buffer is much larger.

See the video at about 0:22 where I open the NERDTree buffer, and the terminal content gets squished even though the terminal window is much wider.

**Comment by justinmk** [comment]
I don't know what would be special about NERDtree, but I've never seen this behavior, the video is too small and/or busy to follow, and there are no repro steps.

https://github.com/neovim/neovim/issues/3864 maybe cover it, and https://github.com/neovim/neovim/issues/2514 is about to be fixed, so no need for this issue.

**Comment by trusktr** [comment]
@justinmk repro steps: install NERDTree, open a terminal buffer (no other tabs or Windows), go full screen, make the terminal have some output (for example, run some terminal commands like `ls -la`), run `:NERDTreeToggle`. Now you can see the problem: after the nerd tree window is open, the terminal output gets chopped (even though the terminal window size is bigger).

**Comment by justinmk** [comment]
I'm not going to install NERDTree. We need _reduced_ steps.
