### ISSUE TITLE
using :lua vim.keymap.set to remap <bs> inserts weird text `<80>kb`

### ISSUE THREAD

**Issue by mozzieongit** [neovim/neovim#21289]
### Neovim version (nvim -v)

0.8.0 Release (also tried with v0.9.0-dev-202+g19dab2ead and 0.8.1 Release)

### Vim (not Nvim) behaves the same?

no (there is no vim.keymap)

### Operating system/version

Manjaro Linux 5.15.78-1-MANJARO

### Terminal name/version

Konsole 22.08.3

### $TERM environment variable

tmux-256color

### Installation

system package manager (also tried repo download)

### How to reproduce the issue

`nvim --clean`
insert some text
`:lua vim.keymap.set('i', '<bs>', 'pumvisible() ? "<c-e><bs>" : "<bs>"', {noremap = true, silent = true, expr = true})`
press backspace

### Expected behavior

Expected behavior is that pressing backspace with the keymap created by `:lua vim.keymap.set...` deletes the character in front of the cursor.

When creating the mapping with `:inoremap <silent><expr> <bs> pumvisible() ? "<c-e><bs>" : "<bs>"` it works as expected.

### Actual behavior

when pressing backspace with the mapping created by lua the text `<80>kb` is inserted

**Comment by zeertzjq** [comment]
Add `replace_keycodes = false` to `opts`

**Comment by mozzieongit** [comment]
Awesome, thanks.
