### ISSUE TITLE
range parameter of code_action doesn't work properly or has weird behavior

### ISSUE THREAD

**Issue by linde12** [neovim/neovim#21326]
### Neovim version (nvim -v)

v0.8.0-dev

### Language server name/version

tsserver

### Operating system/version

Void Linux

### Steps to reproduce using "nvim -u minimal_init.lua"

I have setup nvim with lspconfig, mason and setup tsserver so that i can call `vim.lsp.buf.code_action()` to get suggestions, however i'm trying to implement the same behavior that coc.nvim has with its quickfix. E.g. you should only have to keep the cursor on the same line as the problem, not on the exact word.

In my specific test case i have a function called `doIt` which isnt imported, so i want it to be auto-imported with code action. This works fine if i navigate to the exact word (doIt) and call `vim.lsp.buf.code_action()` (without any arguments) but i figured i could do it just by staying on the same line by utilizing the `range` option. This doesn't seem to work with nvims builtin lsp, i just get "No code actions available" while with coc.nvim works.

I put some logging in nvims `buf.lua:code_action_request` function to log the context:

```
{
  bufnr = 1,
  method = "textDocument/codeAction",
  params = {
    context = {
      diagnostics = { {
          code = 2304,
          message = "Cannot find name 'doIt'.",
          range = {
            end = {
              character = 26,
              line = 26
            },
            start = {
              character = 22,
              line = 26
            }
          },
          severity = 1,
          source = "typescript",
          tags = {}
        } },
      only = { "quickfix" }
    },
    range = {
      end = {
        character = 1,
        line = 27
      },
      start = {
        character = 0,
        line = 26
      }
    },
    textDocument = {
      uri = "file:///home/linde/src/bla/src/server.ts"
    }
  }
}
```

I also looked at the range and context passed by coc.nvim:

```
{
    "range": {
        "start": {
            "line": 26,
            "character": 0
        },
        "end": {
            "line": 27,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [
            {
                "range": {
                    "start": {
                        "line": 26,
                        "character": 22
                    },
                    "end": {
                        "line": 26,
                        "character": 26
                    }
                },
                "message": "Cannot find name 'doIt'.",
                "code": 2304,
                "severity": 1,
                "source": "tsserver"
            }
        ],
        "triggerKind": 1,
        "only": [
            "quickfix"
        ]
    }
}
```

The only thing that i can see that differs and might have an impact is the source which is `tsserver` or `typescript` but i know too little.

Apologies if this is in the wrong place, i'm not sure where to turn but to me it seems like some nvim (not plugin) issue.

### Expected behavior

Expecting range parameter to work properly as it does with coc.nvim by, in this case, auto-importing the `doIt` function which is exported from `doIt.ts`

### Actual behavior

I get no suggestions on code actions.

**Comment by mfussenegger** [comment]
Would need a minimal reproduction. The code action request is made correctly as far as I can tell.

**Comment by linde12** [comment]
Sorry for the late response, i really don't have time atm. I went back to coc for now - feel free to close.
