### ISSUE TITLE
Neovim frequently freezes while in insert or normal mode, possibly related to LSP/rust-analyzer

### ISSUE THREAD

**Issue by nerosnm** [neovim/neovim#21329]
### Neovim version (nvim -v)

NVIM v0.8.1, Build type: Release

### Vim (not Nvim) behaves the same?

Difficult to test, sort of N/A

### Operating system/version

NixOS 23.05.20221122.2788904 (Stoat)

### Terminal name/version

wezterm 20220905-102802-7d4b8249

### $TERM environment variable

wezterm

### Installation

nixpkgs

### How to reproduce the issue

I've hesitated to open this issue even though I've been having this problem for a while, because I'm not exactly sure if it's a problem with a plugin or not, and it's difficult to describe how to reproduce. Sorry in advance for the fact that this might be lacking!

I don't think it's possible to reproduce with `nvim --clean`, because I _think_ it only happens when using the builtin LSP implementation with `rust-analyzer`, set up using `rust-tools.nvim`/`nvim-lspconfig`/`nvim-cmp`/`cmp-nvim-lsp`/`fidget-nvim`. With that setup, it's as simple to reproduce for me as to open a Rust file (usually in a large project) and start editing text. It happens whether I wait for the LSP tasks to finish or not, and often continues happening for a long time/indefinitely after the LSP has finished running things and has settled to an idling state.

I'm very happy to provide more details, but I'm not sure what is relevant or helpful.

### Expected behavior

I expect to be able to edit text and get a smooth and uninterrupted response from the editor, perhaps with some slowdown or freezing when I _save_ the file and wait for a language server to do some processing.

### Actual behavior

When I enter insert mode, leave insert mode, type some characters while in insert mode, or try to navigate in normal mode, the editor often completely freezes for periods of 5 to more than 30 seconds. Pressing keys doesn't make any difference, because it doesn't respond to any input. This often happens repeatedly, i.e. after I've tried to type some text, waited for it to unfreeze, and then tried again, it will freeze again. Quitting and reopening the editor doesn't help.

This even happens when I'm only editing comments.

It doesn't appear to be a system load issue, because this happens even when a language server is not actively indexing anything, and running a program like `btop` doesn't show significant CPU or memory usage.

I don't think this used to happen on older (but still bleeding-edge) versions of neovim, like `0.7.*`. I definitely don't think it happened on `0.5.*`.

**Comment by nerosnm** [comment]
I don't expect anyone necessarily to be able to diagnose this issue from the description I've provided, but some help for how to do some profiling or narrow down the issue a bit more would be really helpful! Thanks.

**Comment by etrnal70** [comment]
Please share a minimal configuration. And also maybe a repo example where this problem happens. 

I do got this problem back then in 0.6 but it has never been seen since then

**Comment by hinell** [comment]
Yeah it would be nice to a have list of lsp plugins you are using.

**Comment by nerosnm** [comment]
Ok, I feel a little silly now - I had `set updatetime=100` in my config. I'm not entirely sure why, I think it may even have been in there for years, but only became a problem recently.

I found that in the process of trying to produce a minimal config - sorry I didn't do that up front (I generate my config with Nix, so it's sort of a pain), because it probably would have saved me filing the issue and wasting your time. Thanks for your patience!

**Comment by theHamsta** [comment]
I have the same problem sometimes. This doesn't trigger reliably but I saw it for both rust-analyzer and clangd. It is not very bad but noticeable. I also have `set updatetime=100` in my config. The semantic highlighting wasn't a problem before during typing since I before only invoked it on CursorHold

**Comment by hinell** [comment]
> my config with Nix,

What's that?

**Comment by theHamsta** [comment]
> > my config with Nix,
> 
> What's that?

https://nixos.org/
