### ISSUE TITLE
Case Sensitive Auto Completion in Edit Command (:e)

### ISSUE THREAD

**Issue by aharris88** [neovim/neovim#2133]
When opening a file with `:e`

In vim I can autocomplete file names even if I type it in lower case and the filename is actually in uppercase, but in Neovim, I have to capitalize the filename correctly. Is this a feature, a bug, or a setting?

**Comment by Pyrohh** [comment]
This goes without saying, but is `wildignorecase` set in neovim? Case insensitive completion works fine for me with that set.

**Comment by aharris88** [comment]
No, I didn't have that set in either vim or Neovim, but somehow it was case insensitive in vim.

Setting that works great in Neovim, thanks!

**Comment by kgust** [comment]
Thanks!  This helped me too.

I would argue that this needs to be set by default.

**Comment by Pyrohh** [comment]
> I would argue that this needs to be set by default.

Why? I can't think of many other things in Nvim, if any, which are case insensitive by default. I prefer case insensitivity in some places in Nvim, but I don't agree with it being the default. Regarding computers, case-sensitivity is less surprising than insensitivity (at least in the context of Nvim), IMHO.

**Comment by IanEdington** [comment]
@ghost @kgust I know I'm late to the party but as a user switching over from vim it would be at least nice to list this in the neovim - vim differences section and how to enable it. Little usability issues like this make a big difference when a user has very specific expectations (ie. neovim should work the same as vim out of the box except for the things explicitly listed)

**Comment by justinmk** [comment]
@IanEdington The default didn't change compared to Vim. 

```
nvim --headless -es -u NONE -N -c 'set wildignorecase?' -c q
nowildignorecase

vim -es -u NONE -N -c 'set wildignorecase?' -c q
nowildignorecase
```

**Comment by justinmk** [comment]
@IanEdington Most likely your distro or your system administrator has some defaults set in `/etc/vimrc` which change Vim's defaults. (This is a source of constant confusion for Vim users, which switching between distros, etc.)

**Comment by IanEdington** [comment]
oh OK. Thanks for letting me know.
