### ISSUE TITLE
Segmentation fault when triggering completion in in ins_compl_next(…)

### ISSUE THREAD

**Issue by StanAngeloff** [neovim/neovim#21330]
### Neovim version (nvim -v)

v0.9.0-dev-f92aab5

### Vim (not Nvim) behaves the same?

[Possibly](https://github.com/vim/vim/blob/3fc84dc2c7efecd7c14ce341cd777475058936fd/src/insexpand.c#LL4182C6-L4182C16)

### Operating system/version

Ubuntu 22.04.1 LTS

### Terminal name/version

alacritty-0.11.0+pr-4763-a9335fcb

### $TERM environment variable

alacritty

### Installation

AppImage

### How to reproduce the issue

1. Open a JavaScript file with LSP configured
2. Trigger `omnifunc` several times at different places

### Expected behavior

When there are no completions, a message should appear.
When there are completions, a menu should appear.

### Actual behavior

Segmentation fault. The following is the output of `(gbb) where`:

```gdb
#0  0x00007ffff7d9d97d in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000055555563018a in ins_bytes (p=0x0) at /data/public/neovim/src/nvim/change.c:615
#2  0x00005555556fbdf8 in ins_compl_next (allow_get_expansion=allow_get_expansion@entry=true, count=1, insert_match=insert_match@entry=true,
    in_compl_func=in_compl_func@entry=false) at /data/public/neovim/src/nvim/insexpand.c:3650
#3  0x00005555556fd3b8 in ins_complete (c=14, enable_pum=<optimised out>) at /data/public/neovim/src/nvim/insexpand.c:4348
#4  0x0000555555655cc8 in insert_do_complete (s=s@entry=0x7fffffffd980) at /data/public/neovim/src/nvim/edit.c:1187
#5  0x000055555565d227 in insert_handle_key (s=s@entry=0x7fffffffd980) at /data/public/neovim/src/nvim/edit.c:1104
#6  0x000055555565d803 in insert_execute (state=0x7fffffffd980, key=<optimised out>) at /data/public/neovim/src/nvim/edit.c:674
#7  0x00005555557eceb0 in state_enter (s=0x7fffffffd980) at /data/public/neovim/src/nvim/state.c:99
#8  0x000055555565a3e8 in insert_enter (s=s@entry=0x7fffffffd980) at /data/public/neovim/src/nvim/edit.c:338
#9  0x000055555565a5cc in edit (cmdchar=97, startln=<optimised out>, count=1) at /data/public/neovim/src/nvim/edit.c:1262
#10 0x0000555555757644 in invoke_edit (cap=cap@entry=0x7fffffffdb20, repl=repl@entry=0, cmd=97, startln=startln@entry=0)
    at /data/public/neovim/src/nvim/normal.c:6211
#11 0x000055555575791c in nv_edit (cap=0x7fffffffdb20) at /data/public/neovim/src/nvim/normal.c:6188
#12 0x000055555575376a in normal_execute (state=0x7fffffffdaa0, key=<optimised out>) at /data/public/neovim/src/nvim/normal.c:1180
#13 0x00005555557eceb0 in state_enter (s=0x7fffffffdaa0) at /data/public/neovim/src/nvim/state.c:99
#14 0x000055555574cdce in normal_enter (cmdwin=<optimised out>, noexmode=<optimised out>) at /data/public/neovim/src/nvim/normal.c:477
#15 0x000055555570f066 in main (argc=<optimised out>, argv=<optimised out>) at /data/public/neovim/src/nvim/main.c:595
```

As far as I can tell [`ins_bytes` is called](https://github.com/neovim/neovim/blob/f92aab5f704f6e94e80f2fcbab42acc272a66a29/src/nvim/insexpand.c#L3650) with a NULL pointer. This causes `strlen(NULL)` inside `ins_bytes` to segfault.

I reckon a `if (compl_leader != NULL)` check is needed, much like [the one a few lines above](https://github.com/neovim/neovim/blob/f92aab5f704f6e94e80f2fcbab42acc272a66a29/src/nvim/insexpand.c#LL3614C3-L3614C27).

**Comment by devyhia** [comment]
I am seeing the same issue on Ubuntu 22.04

**Comment by glepnir** [comment]
please provide a more clear reproduce step

**Comment by StanAngeloff** [comment]
I can't provide a more reproducible step. The issue however lies in:

> As far as I can tell [`ins_bytes` is called](https://github.com/neovim/neovim/blob/f92aab5f704f6e94e80f2fcbab42acc272a66a29/src/nvim/insexpand.c#L3650) with a NULL pointer. This causes `strlen(NULL)` inside `ins_bytes` to segfault.

**Comment by glepnir** [comment]
According to backtrace, adding null check can avoid crash, but i more care about why it's NULL. just tried do some edits in js file i can't reproduce it.
