### ISSUE TITLE
Cursor position with conceal

### ISSUE THREAD

**Issue by aloispichler** [neovim/neovim#21343]
### Feature description

Hello,

I am using `conceallevel=2` and `concealcursor=n` (that is, conceal in normal mode).

1) Suppose, in the following example, that \alpha, \beta, are concealed to α, β, and we edit the line “`1+α+β+1`”.
Moving right by pushing ‘cursor right’ gives
`|1+α+β+1`
`1|+α+β+1`
`1+|α+β+1`
`1+α|+β+1` (push ‘cursor right’ 6 times)
`1+α+|β+1`
`1+α+β|+1` (push ‘cursor right’ 5 times)
`1+α+β+|1`, etc.
To surpass one character (as `α`), one needs to push the cursor 6 (!) times, etc.
Everyone would expect that pushing the cursor once moves over the displayed character α, that's the sense of concealing. 

2) The position of the block cursor is strange as well:
`1+\al|pha+2` is displayed as `1+α|+|2`. Instead, the cursor should indicate the correct position `1+|α|+2`.   

It should be corrected.
Thank you!

**Comment by justinmk** [comment]
Feel free to raise this at https://github.com/vim/vim (and link to the issue from here), we aren't going to change this fundamental behavior of vim.
