### ISSUE TITLE
Build Failure on OSX Yosemite

### ISSUE THREAD

**Issue by rocknrollMarc** [neovim/neovim#2135]
```text
make  -C .deps
make[1]: Entering directory '/Users/marc/neovim/.deps'
make[2]: Entering directory '/Users/marc/neovim/.deps'
make[3]: Entering directory '/Users/marc/neovim/.deps'
make[3]: Leaving directory '/Users/marc/neovim/.deps'
[ 13%] Built target libunibilium
make[3]: Entering directory '/Users/marc/neovim/.deps'
make[3]: Leaving directory '/Users/marc/neovim/.deps'
[ 26%] Built target libtermkey
make[3]: Entering directory '/Users/marc/neovim/.deps'
make[3]: Leaving directory '/Users/marc/neovim/.deps'
make[3]: Entering directory '/Users/marc/neovim/.deps'
[ 27%] Performing configure step for 'libuv'
/Users/marc/neovim/.deps/build/src/libuv/autogen.sh: line 28: automake: command not found
/Users/marc/neovim/.deps/build/src/libuv/autogen.sh: line 33: test: : integer expression expected
/Users/marc/neovim/.deps/build/src/libuv/autogen.sh: line 34: test: : integer expression expected
+ glibtoolize
+ aclocal -I m4
+ autoconf
+ automake --add-missing --copy
/Users/marc/neovim/.deps/build/src/libuv/autogen.sh: line 46: automake: command not found
CMakeFiles/libuv.dir/build.make:100: recipe for target 'build/src/libuv-stamp/libuv-configure' failed
make[3]: *** [build/src/libuv-stamp/libuv-configure] Error 127
make[3]: Leaving directory '/Users/marc/neovim/.deps'
CMakeFiles/Makefile2:161: recipe for target 'CMakeFiles/libuv.dir/all' failed
make[2]: *** [CMakeFiles/libuv.dir/all] Error 2
make[2]: Leaving directory '/Users/marc/neovim/.deps'
Makefile:76: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/Users/marc/neovim/.deps'
Makefile:67: recipe for target 'deps' failed
make: *** [deps] Error 2
v0.10.35
```

**Comment by fwalch** [comment]
As the error message indicates, you need to install automake. See https://github.com/neovim/neovim/wiki/Building-Neovim#os-x for a full list of dependencies.

As an aside (in case you didn't know), you can install Neovim with homebrew: https://github.com/neovim/neovim/wiki/Installing#os-x--homebrew

**Comment by rocknrollMarc** [comment]
Ah ok thatnks ill try that
I tryed with homebrew didnt work :)

**Comment by rocknrollMarc** [comment]
automake-1.15 already installed

**Comment by jszakmeister** [comment]
@rocknrollMarc But the build is not finding it: `automake: command not found`

**Comment by jszakmeister** [comment]
> I tryed with homebrew didnt work :)

It does work.  Try out the troubleshooting steps list in the [homebrew-neovim](https://github.com/neovim/homebrew-neovim) repository.  If you are still having problems, file an issue against that repo and we can help you.

**Comment by rocknrollMarc** [comment]
Ok maybe relinking in brew will help Im trying it now

**Comment by Pyrohh** [comment]
Hi @rocknrollMarc, are you still experiencing this issue?

**Comment by kopischke** [comment]
Oh, and if we keep this issue open, could someone correct the OS name in the title, please. This is making my teeth ache every time I see it in a notification :).

**Comment by Pyrohh** [comment]
cc @rocknrollMarc, otherwise this should be closed considering the consensus seems to be it's a local issue (automake missing, or something else).

**Comment by Pyrohh** [comment]
@tarruda this can probably be closed.
