### ISSUE TITLE
on_yank, end_col outside range with virtualedit=all

### ISSUE THREAD

**Issue by jemag** [neovim/neovim#21368]
### Neovim version (nvim -v)

v0.9.0-dev-486+g3cf0131c5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

archwsl

### Terminal name/version

wezterm

### $TERM environment variable

wezterm 20221004-190909-eefd57b8

### Installation

build from repo

### How to reproduce the issue

- Create the following test.yaml file:
```yaml
livenessProbe:
  httpGet:
    path: /health/liveness
    port: 9443
    scheme: HTTPS
```
- Open file with text using `nvim --clean test.yaml`
- Enter `:set virtualedit=all`
- Enter `:lua vim.api.nvim_create_autocmd({ "TextYankPost" }, { pattern = "*", callback = function() vim.highlight.on_yank({ higroup = "Substitute", on_visual = true, timeout = 300 }) end, desc = "Highlight yanked text", })`
- Set your cursor on the last `s` of liveness, i.e.:
![image](https://user-images.githubusercontent.com/7985687/206816923-947be7d0-b020-4b9c-95e2-61bcf72ac0a0.png)
- Do `y2j` to copy current line +2 down
- Notice error
![image](https://user-images.githubusercontent.com/7985687/206817225-fe312a96-5d9d-4045-b8e5-31f8448f295e.png)

### Expected behavior

Highlights on yank without error

### Actual behavior

Triggers error

**Comment by jemag** [comment]
I believe this is different from https://github.com/neovim/neovim/issues/13317 which requires cursor to be beyond the end of the line, and only result in an offset of the highlight

**Comment by clason** [comment]
I think it _is_ the same issue, though. Can you try #21370?

**Comment by jemag** [comment]
You are right, it works great with that PR. I stand corrected.

**Comment by clason** [comment]
No longer reproducible on master.
