### ISSUE TITLE
Build Failure on OSX Yesomite doesnt like the os version

### ISSUE THREAD

**Issue by rocknrollMarc** [neovim/neovim#2136]
make  -C .deps
make[1]: Entering directory '/Users/marc/neovim/.deps'
make[2]: Entering directory '/Users/marc/neovim/.deps'
make[3]: Entering directory '/Users/marc/neovim/.deps'
make[3]: Leaving directory '/Users/marc/neovim/.deps'
[ 13%] Built target libunibilium
make[3]: Entering directory '/Users/marc/neovim/.deps'
make[3]: Leaving directory '/Users/marc/neovim/.deps'
[ 26%] Built target libtermkey
make[3]: Entering directory '/Users/marc/neovim/.deps'
make[3]: Leaving directory '/Users/marc/neovim/.deps'
make[3]: Entering directory '/Users/marc/neovim/.deps'
[ 27%] Performing configure step for 'libuv'
/Users/marc/neovim/.deps/build/src/libuv/autogen.sh: line 28: automake: command not found
/Users/marc/neovim/.deps/build/src/libuv/autogen.sh: line 33: test: : integer expression expected
/Users/marc/neovim/.deps/build/src/libuv/autogen.sh: line 34: test: : integer expression expected
+ glibtoolize
+ aclocal -I m4
+ autoconf
+ automake --add-missing --copy
/Users/marc/neovim/.deps/build/src/libuv/autogen.sh: line 46: automake: command not found
CMakeFiles/libuv.dir/build.make:100: recipe for target 'build/src/libuv-stamp/libuv-configure' failed
make[3]: *** [build/src/libuv-stamp/libuv-configure] Error 127
make[3]: Leaving directory '/Users/marc/neovim/.deps'
CMakeFiles/Makefile2:161: recipe for target 'CMakeFiles/libuv.dir/all' failed
make[2]: *** [CMakeFiles/libuv.dir/all] Error 2
make[2]: Leaving directory '/Users/marc/neovim/.deps'
Makefile:76: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/Users/marc/neovim/.deps'
Makefile:67: recipe for target 'deps' failed
make: *** [deps] Error 2

**Comment by fwalch** [comment]
I guess creating this was an accident, since it's the same as #2135. Can you close it?
