### ISSUE TITLE
Poor clipboard behavior in certain environments

### ISSUE THREAD

**Issue by RomanHargrave** [neovim/neovim#2137]
I recently set up neovim. One feature that I absolutely must have is clipboard interop for ***everything***, as such I was glad to see that this is a feature provided by neovim. I use [fish](/fish-shell/fish-shell) as my usual shell, mainly due to the somewhat better scripting syntax. After configuring clipboard interop in neovim, I noticed that both copy and paste behavior were very slow (~5s per op), and furthermore that pasting resulted in the insertion of ANSI terminal control characters as follows:

```
^[[30m^[(B^[[m
```

This is likely due to a combination of behaviors in the shell as it is configured for my environment, and the implementation of `system_get_output_as_rettv` or potentially the Job API (I cannot say, as I am not familiar with the internals of the command API). A (theoretical) temporary solution is as follows:

```fish
env SHELL=/bin/bash nvim
```

this, however, is impractical as it would require a lot of hacking that would apply to files outside of my own home folder due to my use of vimpager, and having set nvim as the provider for vim,vi,view etc... While it is an option to apply a shim in the form of a launch script such that all instances of nvim are executed with the given `SHELL` variable, I do not wish to do this as this issue is present only in my environment, and I furthermore would like to be able to use the various functions that I have written for fish from within nvim.

In my experience with other applications that spawn a new instance of $SHELL and capture STDOUT, this does not happen, which is what leads me to believe that this is an issue present somewhere in nvim.

I will investigate further (IE: build against nvim and invoke `system_get_output_as_rettv` in order to capture the raw output) and post back later, hopefully I can determine exactly what causes the problem within my shell configuration.

My environment is as follows:

- Linux: 4.0.0-rc3 SMP preempt x86_64 / Intel SSE support / Interrupts 1000Hz 

- fish shell (2.1.1-1219-ge421c12) , oh-my-fish, agnoster theme

- nvim: 0.0.0-alpha+201503111832 , Commit: 032c20078a617252ff9fc5ac03b4c390a6868a4d

- versions: GCC 4.9.2 , LUA 5.2 , LUAJIT 2.0 

- terminal emulator: xterm-compatible via gnome-terminal libs (guake, terminator)

- clipboard interfaces: xsel

- bash shell version: 4.3.30 x86_64 (should not matter)

I would suggest marking this as minor, as it likely affects some %0.01 of users.

**Comment by tarruda** [comment]
Changing your shell to bash fixes the problem? This and the `^[[30m^[(B^[[m` suggests that the fish shell is being spawned in interactive mode.

**Comment by RomanHargrave** [comment]
Yes. That is precisely what I was thinking. That's odd considering that it shouldn't if everything is going well. Furthermore, the lack of such behaviour using a blank config is strange. It should not be possible to make fish go in to interactive mode when it is sourcing its configuration.

**Comment by bfredl** [comment]
@tarruda While `system("string")` perhaps must use `$SHELL` (i e for backwards compability) wouldn't it be nice to be able to use, say, `shell(['cmd', 'arg1', 'arg2'])` to bypass the shell and launch the process directly? (or perhaps this might even be implemented in vimscript as thin wrapper around jobcontrol)

**Comment by RomanHargrave** [comment]
Here is some [ltrace output](https://dpaste.de/tEXQ). It looks like the control sequence is being read separate from the actual `xsel` output, and then glued to the first line. I added some comments and manual folds. The contents of the clipboard were `test`.

**Comment by RomanHargrave** [comment]
Followup: the culprit was OMF's vi-mode plugin (for fish). Thanks for being my [rubber duck](http://en.wikipedia.org/wiki/Rubber_duck_debugging).

**Comment by tarruda** [comment]
> @tarruda While system("string") perhaps must use $SHELL (i e for backwards compability) wouldn't it be nice to be able to use, say, system(['cmd', 'arg1', 'arg2']) to bypass the shell and launch the process directly? (or perhaps this might even be implemented in vimscript as thin wrapper around jobcontrol)

This might be possible after the `jobwait` function is available.
