### ISSUE TITLE
Beep

### ISSUE THREAD

**Issue by davidwoodburn** [neovim/neovim#21384]
### Feature description

I would like a simple built-in command to make the terminal beep.  This would be used in vimscripts for alerts.  It is not related to errors or warnings.  I've tried so many different `echo` commands, like "\x07" and such.  None of these work even with blank `init.vim` files.  I'm using Apple Terminal with the "Audible bell" option turned on.  Outside of nvim, I can make the terminal beep just fine.  This shouldn't be complicated and it shouldn't matter what settings I have for `vb`, `novisualbell`, or `errorbells`; it should just be a simple, built-in command like `beep()`.  Please help.

**Comment by zeertzjq** [comment]
In TUI this may be achieved using `chansend()` or Lua `io.write()`:
```vim
:call chansend(v:stderr, "\x07")
```
```vim
:lua io.write('\7')
```

With LuaJIT FFI this can work in a GUI that has implemented it too:
```lua
local ffi = require('ffi')
ffi.cdef([[void ui_call_bell(void);]])
ffi.C.ui_call_bell()
```

None these solutions work universally though.

**Comment by justinmk** [comment]
> and it shouldn't matter what settings I have for `vb`, `novisualbell`, or `errorbells`

Not sure about that. If plugins were to use a beep() function, I would think users expect it to respect 'errorbells'.

**Comment by davidwoodburn** [comment]
Okay, I can see that.  Still, having a command that beeps would be great.

**Comment by hinell** [comment]
You can also use terminal for that.

**Comment by davidwoodburn** [comment]
True, you can.  However, I think the fact that I’ve done multiple searches over several weeks, posted the question on Reddit and Quora and didn’t get an answer until I posted a feature request, suggests the solution was not easy for the average user to figure out.

**Comment by zeertzjq** [comment]
Vim's if_lua has `vim.beep()`

**Comment by davidwoodburn** [comment]
Thank you all for your help.  In the end, I posted a bug report to the Neovim project, which prompted a solid answer.  The code is `call chansend(v:stderr, "\x07")`.  This works great.  It creates a beep, regardless of other settings.

**Comment by davidwoodburn** [comment]
Thank you all for your help.  The `chansend` approach worked great.
