### ISSUE TITLE
Volar init_options can't be overwritten

### ISSUE THREAD

**Issue by ChazAshley** [neovim/neovim#21381]
### Neovim version (nvim -v)

NVIM v0.8.1, Build type: Release, LuaJIT 2.1.0-beta3

### Language server name/version

volar 1.0.12

### Operating system/version

arch linux 5.15.79-1-lts 

### Steps to reproduce using "nvim -u minimal_init.lua"

Open any *.vue file with Volar installed and you will see an error. To fix the error `tsdk` inside `init_options.typescript` should be set to the right value.
```lua
require("lspconfig").volar.setup({
	filetypes = { "vue", "javascript", "typescript" },
	init_options = {
		typescript = {
			tsdk = "path/to/ts/lib",
		},
	},
})
```
but the value of `tsdk` stays an empty string.

### Expected behavior

`tsdk` value is overwritten with the provided string

### Actual behavior

`tsdk` stays an empty string.

I tried to set the `tsdk` to the correct value by directly changing the `/usr/share/nvim/runtime/lua/vim/lsp.lua` file, and it worked fine.
Overwriting `filetypes` works fine too, so it's specifically `init_options` that can't be overwritten.

### Log file

https://gist.github.com/ChazAshley/6e101381cc015e6f3a3f739bff8d63a2

**Comment by justinmk** [comment]
I wonder if a "deep copy" is missing somewhere?

**Comment by mfussenegger** [comment]
This sounds like a lspconfig issue. Core contains lsp.start/lsp.start_client where you'd pass the init_options directly.
