### ISSUE TITLE
lsp(semantic_tokens): Error `runtime/lua/vim/lsp/semantic_tokens.lua:41: attempt to get length of local 'tokens' (a nil value)`

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#21387]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-497+g3217a31f9 commit 3217a31f9b0eb93a9c4d01f6a15b9a104e4f56f3

### Language server name/version

company internal

### Operating system/version

Linux 5.18, Debian Testing

### Steps to reproduce using "nvim -u minimal_init.lua"

I'm still not sure what's going on, but I reckon it has to do with recent changes (additional actually) of [semantic_tokens.lua
](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/semantic_tokens.lua).
cc @jdrouhard @fsouza @mfussenegger 

```
vim_lsp_semantic_tokens: Error executing lua: ...eovim/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:41: attempt to get length of local 'tokens' (a nil value) 
```

The odd thing is that I can't reproduce this all the time. It just seems to happen after the LSP does some things. I tend to recompile Neovim from HEAD and the last one was from Thursday I think (2022-12-08 [1]). I started seeing this issue today (2022-12-12). Something else that changed in the meantime is that my highlighting gets changed a lot when the LSP activates. Nearly every symbol  (in a Go file) gets colorized. I assume this is related to semantic tokens but am not sure (at first it made me think of when I first tried treesitter and it gave me a christmas tree document with my current colorscheme (OceanicNext).

Just filing this here to see if anyone has an immediate idea of what's going on before I dig in deeper.

[1]: I should start adding tags every time I recompile...

**Comment by jdrouhard** [comment]
The only way you could get that error on that line would be if you saw other errors previously. Are you sure that's the _only_ error you are seeing?

Without more details on the language server or a repro, I'm not sure what to look at. Even misbehaving language servers would have errored out in other parts of the semantic token engine than that particular line. We could probably add some additional checks that the responses from the server make sense before "accepting them" but I'd like to get more information first.

**Comment by LoneExile** [comment]
![image](https://user-images.githubusercontent.com/82561297/207215882-fe560658-7040-4a25-9952-bf9e3914962b.png)

I received the same error. 

NVIM v0.9.0-dev-504+g0b20762c6
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by jdrouhard** [comment]
> I received the same error. 
> 
> NVIM v0.9.0-dev-504+g0b20762c6 Build type: Release LuaJIT 2.1.0-beta3

That’s not the same error and looks more like #21391
