### ISSUE TITLE
Semantic tokens errors when typing

### ISSUE THREAD

**Issue by kuator** [neovim/neovim#21386]
### Neovim version (nvim -v)

NVIM v0.9.0-dev (407eef4)

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Ubuntu 22.04

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256color

### Installation
```
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get install neovim
```
### How to reproduce the issue

Start typing

### Expected behavior

When typing neovim doesn't show errors

### Actual behavior

![Screenshot from 2022-12-12 12-30-51](https://user-images.githubusercontent.com/25168308/206976971-2c4f1ade-0f1a-40c0-98ce-e405e0608ccb.png)

**Comment by clason** [comment]
Looks like the same issue: Incorrect installation. If you see such a problem, always try building from source. We don't have any control over the PPAs.

**Comment by kuator** [comment]
> Looks like the same issue: Incorrect installation. If you see such a problem, always try building from source. We don't have any control over the PPAs.
> 
> Also, reproduction steps should always be with `nvim --clean`.

I built neovim, but the errors still persist. Is there a way to turn off semantic token? I put `client.server_capabilities.semanticTokensProvider = nil` in my `LspAttach` as helpfile says, but semantic tokens still keep applying.

**Comment by kuator** [comment]
https://github.com/neovim/neovim/pull/21462
