### ISSUE TITLE
[builtin-terminal-emulation] Swap/backup files not needed. 

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2139]
Prevent from making swap/backup files for terminal buffers? I opened a new terminal and it complained about an existing swap file. hehe.

**Comment by trusktr** [comment]
I believe this happened after I opened a new buffer (a Startify buffer) without exiting the terminal buffer, causing the terminal buffer to be hidden. Then I opened a new nvim, :term, then it gave the familiar swap existing message.

**Comment by tarruda** [comment]
that shouldn't happen, maybe it was another bug that transformed a terminal buffer into a normal buffer

**Comment by trusktr** [comment]
@tarruda I'm able to reproduce it. I have nvim starting up when iTerm2 starts by setting `zsh -c "nvim +term zsh"` as iTerm's startup command. When I start iTerm, all is fine, and I get into a terminal. Then, if I press `command+n` to open a new iTerm, I get the error:

```
E325: ATTENTION
Found a swap file by the name "~/.vim/swap//%Users%josephpea%zsh.swp"
          owned by: josephpea   dated: Tue Mar 17 09:06:25 2015
         file name: ~josephpea/zsh
          modified: no
         user name: josephpea   host name: I.local
        process ID: 59251 (still running)
While opening file "zsh"

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r zsh"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/Users/josephpea/.vim/swap//%Users%josephpea%zsh.swp"
    to avoid this message.

Swap file "~/.vim/swap//%Users%josephpea%zsh.swp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (Q)uit, (A)bort:
```

**Comment by trusktr** [comment]
Yep, it's because of the "zsh" in `zsh -c "nvim +term zsh"`? Changing it to `zsh -c "nvim +'term zsh'"` fixed it.

**Comment by trusktr** [comment]
Cool, now just `zsh -c "nvim +term"` works, which wasn't before, and that was why I was originally trying `zsh -c "nvim +term zsh"`.
