### ISSUE TITLE
Title not restored after exiting from nvim opened with stdin

### ISSUE THREAD

**Issue by 3N4N** [neovim/neovim#21404]
### Neovim version (nvim -v)

v0.9.0-dev-506+g090048bec9f8

### Vim (not Nvim) behaves the same?

no, vim 9.0.815

### Operating system/version

Windows 11 22H2

### Terminal name/version

Windows Terminal, Conhost

### $TERM environment variable

nil, xterm-256color

### Installation

Built from source

### How to reproduce the issue

```
$ set TERM='xterm-256color' # without setting $TERM, ':h title' doesn't take effect in either cmd or powershell
$ echo foo | nvim --clean --cmd 'set title' -
:q
```

### Expected behavior

The terminal title should be restored to what it was before opening neovim.

### Actual behavior

The terminal title remains what it was set to by neovim.

**Comment by 3N4N** [comment]
I could take a look at it if I knew where and how nvim resets the title.  Any suggestions?

**Comment by zeertzjq** [comment]
https://github.com/neovim/neovim/blob/090048bec9f80c46a6ce6ff05a419b15bc4bf028/src/nvim/tui/tui.c#L401-L402

**Comment by 3N4N** [comment]
Are you sure about that?  If I comment that line, running `$ nvim` (without passing it stdin) sets and restores title properly.  I haven't studied the macro `unibi_out_ext` properly yet, other than learning about title stacking (`\e[22t`, `\e[23t`, etc.), so I may be missing something, but right now it looks like something else is taking care of restoring the title.

**Comment by zeertzjq** [comment]
The shell may restore the title. With `nvim --clean --cmd 'set title'; cat` the title is still `[No Name] - NVIM` when running `cat` after removing these two lines.

**Comment by 3N4N** [comment]
> With `nvim --clean --cmd 'set title'; cat` the title is still `[No Name] - NVIM` when running cat after removing these two lines.

Right.  At least that's what happens in Ubuntu (in both WSL and native) and bash.  But in Windows, with powershell/cmd/msys, the title is restored properly without this line:
https://github.com/neovim/neovim/blob/090048bec9f80c46a6ce6ff05a419b15bc4bf028/src/nvim/tui/tui.c#L402

> The shell may restore the title

This must be the reason why in Windows, nvim doesn't need that line.  And that also suggests the possibility that Windows Terminal doesn't support/recognize xterm title stack codes.  Because even though in Windows, nvim is able to restore the title when exiting, it may not be nvim that's restoring the title: it might be the shell.  If that's the case then: 1) something in Windows shells is failing to restore title, and 2) I don't know how to go about fixing that.

One other thing about point 1): Without the `unibi_out_ext` line, msys shell successfully restores title after exiting nvim (for both `nvim` and `echo 'foo' | nvim`).  So maybe it's the redirection that's messing with native Windows shells (powershell/cmd).

**Comment by justinmk** [comment]
looking at usages of `stdin_isatty`, I don't see anything that looks like it could cause a difference on Windows.

**Comment by 3N4N** [comment]
I don't think ConPTY has implemented xterm's codes 22 and 23.  I tried using those escape sequences directly in command line, with 'Write-Host'; I could only change the title; couldn't push/pop to/from title stack.  And there is no mention of stacking feature in [Console Virtual Terminal Sequences].

I have opened [a ticket][2] requesting this feature, but it didn't get any traction; probably won't be implemented.

[1]: https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences
[2]: https://github.com/microsoft/terminal/issues/14575
