### ISSUE TITLE
Command line lazy updates

### ISSUE THREAD

**Issue by kylechui** [neovim/neovim#21408]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-315+g306043200

### Vim (not Nvim) behaves the same?

vim 8.2.4919

### Operating system/version

Pop!_OS 22.04 LTS

### Terminal name/version

Alacritty

### $TERM environment variable

xterm-256color

### Installation

`apt` package manager

### How to reproduce the issue

Using the following configuration:
```lua
-- minimal_config.lua
vim.keymap.set({ "c", "i" }, "<C-BS>", "<C-w>", { silent = true })
```
1. Run `nvim -u minimal_config.lua`
2. Type `:echo 0`

### Expected behavior

The 0 should be deleted, and the screen should redraw, indicating that this is the case.

### Actual behavior

The screen does not get redrawn, so the command line remains as `:echo 0`. However, if any new text is typed, the 0 disappears and is replaced with the most recently typed text.

**Comment by zeertzjq** [comment]
This is how `<silent>` is intended to behave.

**Comment by kylechui** [comment]
Ah, sorry about the noise, and thanks for the quick response!
