### ISSUE TITLE
add autocmd that will execute once on every CursorHold

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#21401]
### Feature already in Vim?

NO

### Feature description

I think this autocmd will be very useful when implementing some stuff like `nvim-gps` `matchparen` etc. if we use `CursorMoved` we might feel the delay when moving the cursor by holding `j/k`, if we use `CursorHold`, the code will be executed over and over again but the code inside actually it only needs to be executed once.

> for now we can using this nested autocmd but it still execute on every CursorMoved
```lua
vim.api.nvim_create_autocmd("CursorMoved", {
    callback = function ()
        vim.api.nvim_create_autocmd("CursorHold", {
            once = true,
            callback = function ()
                print("Hello")
            end
        })
    end
})
```

**Comment by zeertzjq** [comment]
So what is "once on every CursorHold"?

**Comment by lewis6991** [comment]
> the problem is the inner autocmd will still be create on every cursormoved :

So don't create it every time and use a variable to track if it has been created or not.

```lua
local inner_created = false
vim.api.nvim_create_autocmd("CursorMoved", {
    callback = function ()
        if inner_created then
          return
        end
        inner_created = true
        vim.api.nvim_create_autocmd("CursorHold", {
            once = true,
            callback = function ()
                inner_created = false
                print("Hello")
            end
        })
    end
})
```

**Comment by luukvbaal** [comment]
I don't get the nested autocommands here, isn't this behavior inherent to `CursorHold`? It will not be executed again until the cursor has moved.

**Comment by lewis6991** [comment]
It seems like what you're trying to achieve is already possible with the current API. There is no need to create another autocmd type.

**Comment by luukvbaal** [comment]
> if we use CursorHold, the code will be executed over and over again

> when holding the cursor, the callback will be executed only once. once we move the cursor to another place and holding, the callback will still be executed once, but moving the cursor wont trigger that autocmd

Isn't this exactly what the `CursorHold` autocmd is designed to do? What gives you the notion that it will be executed over and over again/

**Comment by lewis6991** [comment]
> Isn't this exactly what the CursorHold autocmd is designed to do? What gives you the notion that it will be executed over and over again?

Because they've placed it inside a `CursorMoved` autocmd.
