### ISSUE TITLE
omnifunc doesn't provide completions when language server gives back filterText

### ISSUE THREAD

**Issue by tinhajj** [neovim/neovim#21418]
### Neovim version (nvim -v)

0.8.1

### Language server name/version

tsserver 2.0.0 and beyond

### Operating system/version

windows and mac

### Steps to reproduce using "nvim -u minimal_init.lua"

my minimal_init.lua

comment the '--cmd =' line depending on if you're on unix or windows.

```
vim.lsp.set_log_level("debug")

local start = function()
	vim.lsp.start({
		name = 'typescript language server',
		--cmd = {'cmd.exe', '/C', 'typescript-language-server', '--stdio'},
		cmd = {'typescript-language-server', '--stdio'},
		root_dir = vim.fs.dirname(vim.fs.find({'tsconfig.json'}, { upward = true })[1]),
	})
end

vim.api.nvim_create_autocmd({"BufEnter", "BufWinEnter"}, {
	pattern = {"*.ts"},
	callback = start,
})

```

**When I try and do omnifunc completions on a string type or array type I get back no results.**  When I check the LspLogs I do see that tsserver is giving back results.  I think somehow the 'prefix' is getting confused and nvim is inadvertently filtering all the completion items.

Heres a zip that has the minimal_init.lua and the typescript project I was testing with in main.ts on my windows machine
[tstest.zip](https://github.com/neovim/neovim/files/10230780/tstest.zip)

### Expected behavior

Expected the completion items to show up

### Actual behavior

All completion items were filtered out

### Log file

https://gist.github.com/tinhajj/1d9f2f6378cba52d38ee6587e5f1ab71

**Comment by tinhajj** [comment]
Is anyone able to copy my steps and reproduce?

**Comment by tinhajj** [comment]
Reopening misclicked

**Comment by mfussenegger** [comment]
As far as I can tell this is fixed on master. If not, please shout
