### ISSUE TITLE
[builtin-terminal-emulation] temporary alternate buffer in SSH loses cursor.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2142]
It seems like the alternate terminal buffer in an SSH loses the cursor when switching back to the normal buffer. For example, ssh to a server, start vim (alternate buffer replaces command lines), quit vim (command lines returned), cursor no longer moves with input.

**Comment by trusktr** [comment]
Seems like the cursor gets back to where it should be whenever going back into the temp buffer.

**Comment by tarruda** [comment]
The code that controls cursor on/off needs to be refactored for the new UI architecture

**Comment by tarruda** [comment]
@trusktr is this still a problem on the latest version? There have been changes in how cursor on/off is handled

**Comment by trusktr** [comment]
Yep, looks like it works now.
