### ISSUE TITLE
Setting emsg_silent = true without silent = true in nvim_cmd silences all error messages

### ISSUE THREAD

**Issue by comfortablynick** [neovim/neovim#21420]
### Neovim version (nvim -v)

0.9.0-dev-508+g6631df910

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Arch Linux

### Terminal name/version

ssh

### $TERM environment variable

tmux-256color

### Installation

build from repo

### How to reproduce the issue

```vim
nvim --clean
:lua vim.cmd.colorscheme { "default", mods = { emsg_silent = true } }
:lua assert(1==2)
```

### Expected behavior

Should get error message that the assertion failed

### Actual behavior

No error message

The error message will be shown if I add `silent = true` to the command.

**Comment by zeertzjq** [comment]
It hard to decide what the correct behavior should be here, as, for example, when `nvim_parse_cmd` parses a command `silent` is set whenever `emsg_silent` silent. So should `emsg_silent` also imply `silent` in `nvim_cmd`, like `:silent!`?

**Comment by comfortablynick** [comment]
I think that makes sense. That's how I logically expected it to work, and it would match how it works in vimscript.
