### ISSUE TITLE
WARNING: Missing user config file: ~/.config/nvim/init.vim

### ISSUE THREAD

**Issue by realtica** [neovim/neovim#21424]
### Neovim version (nvim -v)

NVIM v0.8.1

### Vim (not Nvim) behaves the same?

no, I don't have vim

### Operating system/version

Debian GNU/Linux 11 (bullseye)

### Terminal name/version

kitty, lxterminal, and more

### $TERM environment variable

xterm-kitty

### Installation

homebrew, but it happend with .deb package also

### How to reproduce the issue

:checkhealth

man: require("man.health").check()
========================================================================
  - OK: plugin/man.vim not in $VIMRUNTIME
  - OK: autoload/man.vim not in $VIMRUNTIME

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: ~/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

### Expected behavior

Configuration without warnings

### Actual behavior

**- WARNING: Missing user config file: ~/.config/nvim/init.vim**

Something rare happens when I set:
`export VIMINIT="$XDG_CONFIG_HOME/nvim/init.vim"`

```
Error detected while processing VIMINIT:
E486: Pattern not found: home
Press ENTER or type command to continue
```
With VIMINIT empty nvim works fine but with the warning:
**- WARNING: Missing user config file: ~/.config/nvim/init.vim**
Is this warning important for plugins or LSP?

**Comment by zeertzjq** [comment]
What does `:echo $MYVIMRC` print?

**Comment by justinmk** [comment]
> How to reproduce the issue
> :checkhealth

That of course is not sufficient.

Does `~/.config/nvim/init.vim` exist or not? Not sure why VIMINIT is mentioned.



> Is this warning important for plugins or LSP?

It's a warning, not an error. If you don't want to use a init.vim, then don't.

**Comment by realtica** [comment]
> > How to reproduce the issue
> > :checkhealth
> 
> That of course is not sufficient.
> 
> Does `~/.config/nvim/init.vim` exist or not? Not sure why VIMINIT is mentioned.
> 
> > Is this warning important for plugins or LSP?
> 
> It's a warning, not an error. If you don't want to use a init.vim, then don't.

All works well, all Env Vars are set correctly of course the init.vim file exists, the question is, why I get that warning?

**Comment by realtica** [comment]
> What does `:echo $MYVIMRC` print?

~/.config/nvim/init.vim

**Comment by justinmk** [comment]
Does the user have permissions to read `~/.config/nvim/init.vim` ?

**Comment by realtica** [comment]
> Does the user have permissions to read `~/.config/nvim/init.vim` ? Any warnings in `$NVIM_LOG_FILE` ?
> 
> ```
> :edit $NVIM_LOG_FILE
> ```
Yes, is owned by the user (~/.config/nvim/init.vim)
The $NVIM_LOG_FILE is empty.
