### ISSUE TITLE
vim.cmd("startinsert") has no effect after setting window

### ISSUE THREAD

**Issue by nmattia** [neovim/neovim#21437]
### Neovim version (nvim -v)

NVIM v0.8.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 13.0.1 Ventura

### Terminal name/version

iterm

### $TERM environment variable

xterm-256color

### Installation

nixpkgs

### How to reproduce the issue

Create a lua script that sets the current buffer to some terminal buffer. If the current window is set too, then `vim.cmd("startinsert")` has no effect and the terminal is left in normal mode (workaround is to use `nvim_input`, see below)

``` lua
local bufs = vim.api.nvim_list_bufs()

for _, bufnr in pairs(bufs) do
    if(string.find(vim.api.nvim_buf_get_name(bufnr), "term://")) then
        -- (ALT) vim.api.nvim_set_current_win(some_win_nr)
        vim.api.nvim_set_current_buf(bufnr)
        vim.cmd("startinsert")
        -- (ALT) vim.api.nvim_input("i")
    end
end
```

### Expected behavior

I would expect `vim.cmd("startinsert")` to start insert mode

### Actual behavior

Terminal is left in normal mode

**Comment by zeertzjq** [comment]
Cannot reproduce. The steps to reproduce look incomplete.

**Comment by nmattia** [comment]
Here are more steps:

``` lua
-- save this to 'test.lua' and run ':luafile %'

local bufs = vim.api.nvim_list_bufs()

-- save current window and create a few dummy windows
local winid = vim.api.nvim_get_current_win()
vim.cmd("new")
vim.cmd("new")
vim.cmd("new")

for _, bufnr in pairs(bufs) do
    if(string.find(vim.api.nvim_buf_get_name(bufnr), "term://")) then
        -- revert back to original window and set buffer
        vim.api.nvim_set_current_win(winid)
        vim.api.nvim_set_current_buf(bufnr)

        -- this has no effect, we're left in normal mode
        vim.cmd("startinsert")
        -- this next call is needed to actually enter insert mode
        -- (ALT) vim.api.nvim_input("i")
    end
end
```

@zeertzjq let me know if you need more info

**Comment by nmattia** [comment]
Here's a more complete example:

```lua
vim.cmd('terminal')
vim.cmd("startinsert")
local bufnr = vim.api.nvim_get_current_buf()
local winid = vim.api.nvim_get_current_win()

vim.cmd("vnew")
vim.fn.termopen(":", {
    on_exit = function()
        vim.api.nvim_set_current_win(winid)
        vim.api.nvim_set_current_buf(bufnr)
        vim.cmd("startinsert")
        --vim.api.nvim_input("i")
    end
})
```

I extracted the first example from a larger piece of code and tried to simplify, but maybe I simplified too much (couldn't reproduce either). After running `:luafile %` on the file above, the new terminal ends up in normal mode if `nvim_set_current_win` is called; although this can be worked around by calling `nvim_input("i")`.

**Comment by zeertzjq** [comment]
I still cannot reproduce. After sourcing the file above the new terminal ends up in Terminal mode for me.

**Comment by clason** [comment]
@nmattia make sure to provide an example that can be reproduced with `nvim --clean` -- only then can it be considered a Neovim issue rather than a plugin or config issue.

**Comment by nmattia** [comment]
Ah, I didn't know of `nvim --clean`, thanks! I can't reproduce then. Will try and figure out which part of my config is causing this. Thanks a lot!

**Comment by AlexSWall** [comment]
Did you work out the issue? I'm running into the same thing.

**Comment by nmattia** [comment]
Haven't been able to narrow it down unfortunately, doesn't seem to happen consistently
