### ISSUE TITLE
Better document nargs in the api docs

### ISSUE THREAD

**Issue by danielo515** [neovim/neovim#21446]
### Feature already in Vim?

No

### Feature description

I was about opening an issue to improve the api docs (all the methods named `vim.api.nvim_xxx`), and I thought that I better create one a little bit more focused.
The part that I'm strugling with now is `nvim_create_user_command({name}, {command}, {*opts})`. The first two arguments are properly documented, and the last one, mostly.
However, the options that are not desc, force or preview are not very nicely documented:

```
      • {opts}     Optional command attributes. See |command-attributes| for
                   more details. To use boolean attributes (such as
                   |:command-bang| or |:command-bar|) set the value to "true".
                   In addition to the string options listed in
                   |:command-complete|, the "complete" key also accepts a Lua
                   function which works like the "customlist" completion mode
                   |:command-completion-customlist|. Additional parameters:
                   • desc: (string) Used for listing the command when a Lua
                     function is used for {command}.
                   • force: (boolean, default true) Override any previous
                     definition.
                   • preview: (function) Preview callback for 'inccommand'
```
As you can see, the `nargs` option is not even named, and it directs you to `command-attributes`. 
This is a bit of a bummer because you have to go to a completely different section of the docs to see the rest of the options, but the worst part is that you also have to play the guess game to figure out which fields are accepted.
I figured out that I can pass `nargs=something` but what something is is not easy for me to figure out:

```
	-nargs=0    No arguments are allowed (the default)
	-nargs=1    Exactly one argument is required, it includes spaces
	-nargs=*    Any number of arguments are allowed (0, 1, or many),
		    separated by white space
	-nargs=?    0 or 1 arguments are allowed
	-nargs=+    Arguments must be supplied, but any number are allowed
```
Are all the options of the same type? Are them all strings? VimScript may not care, or may parse it automatically, but if you need to call this from a more strict language the type is needed. I tried using all strings, but "0" is rejected as not a valid option, where "*" and "?" are accepted. Does this mean that the field can be either a string and an number? Having that type information in the function documentation will be nice.

**Comment by justinmk** [comment]
> and it directs you to `command-attributes`

We need to avoid duplicating documentation. 



> Are all the options of the same type? Are them all strings?

The docstring gives a hint:

> To use boolean attributes (such as |:command-bang| or |:command-bar|) set the value to "true".

Could be adjusted though. And perhaps should mention `nargs`. In general though, creating user commands means being familiar with that part of Vimscript.

**Comment by danielo515** [comment]
> We need to avoid duplicating documentation.

I can understand that, and I am not suggesting the docs should be as detailed or that should not be linked, but I think all the parameters of the option table should be, at least, listed, so you don't have to jump back and forth just to properly complete the list. 

> The docstring gives a hint:

And even that is confusing. How are those supposed to be named? Sems that `command-bang` is just bang, but that is a guess not everybody have to make.

> In general though, creating user commands means being familiar with that part of Vimscript.

I don't see why if someone wants to just use Lua to configure Neovim he/she needs to be familiar with vimscript in any way. A lot of users will come to Neovim as first vim experience, and they may just want to use Lua to configure it, why would they need to be forced to learn vimscript first if Lua is 100% capable of doing the same? But even leaving that apart, even if you are familiar with vimscript, I don't see how that will help you to translate those arguments from VimScript to Lua, given the first are like command-line flags, and the latter are fields on an object.
Also, isn't the api part supposed to be also part of the rpc API? Then, how can someone writing a plugin, for example, in Rust, know what type to assign to something that accepts 0, 1, `*`, `?` etc. Are the 0 and 1 literals? They are strings? Or they must be translated to booleans too?

**Comment by justinmk** [comment]
> why if someone wants to just use Lua to configure Neovim he/she needs to be familiar with vimscript in any way.

User commands are inherently a Vimscript concept. At least that area of knowledge is needed.

**Comment by svermeulen** [comment]
Want to just second this request since it just took me awhile to figure out how to specify nargs.  Even once figuring out that it's explained in command-attributes, it's still not clear what values (and what types) are valid without experimentation
