### ISSUE TITLE
Alternate CI system...

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#2145]
Travis CI is great--it's free and gives you a lot of control.  However, it doesn't support many platforms and this has grown frustrating as we sometimes break things for other operating systems.  This still isn't done, but I've been working on getting an alternate CI system up and running.  Just this week I purchased a VPS and set it all up: http://neovim-qb.szakmeister.net/overview/10

At the moment, I have all 64-bit slaves for Ubuntu 12.04, FreeBSD 10, and Mac OS X Yosemite.  My hope is to add more in the future (perhaps Windows and some 32-bit builds).  It is *not* doing everything that we are on Travis yet (and I'm not entirely sure we want to).  I also need to do a little more work to make sure everything comes up in case of power failures, etc.  I'd also like to have at least one redundant node for each platform, just in case some go offline for some reason (2 of them are currently VMs, so if one goes away, the other is likely to go away too).  Hopefully, I'll get my hands on some more hardware to do this with.

My hope is to tie it in to the pull request and have it test pull requests too (so people know about breaking other platforms).  I'm a bit gun shy at the moment, because once I enable that feature it's going to queue a large number of builds.  I've been working with PMEase to smooth some wrinkles too (for our report processing and what not).  And we have PMEase to thanks for our free license to support our project.

At any rate, I just wanted to share and see what everyone thinks.

**Comment by justinmk** [comment]
Wonderful. Any help you need with hosting costs will be covered by the project funds.

I am reluctant to move totally away from travis. Will the two co-exist?

**Comment by fwalch** [comment]
This is awesome, thank you very much for setting this up!

Just some ideas: What we could do is to use this CI service in addition to (instead of as a replacmenent for) Travis, to test OSes (in particular *BSD) that are not supported there.
We could also set up different Linux distributions, maybe for integration/installation tests (from Ubuntu PPA, additional "official" packages we might provide in the future) or to create (binary) package repositories (i.e. "PPAs" for other distributions), although something like Open Build Service might be better for the latter.

**Comment by ZyX-I** [comment]
You can use http://www.appveyor.com/ for Windows. Note: I have *not* actually used it, just know it is there and it claims to be free for OS projects. Why don’t you want to make existing CI services do what they can do and use your service only for things they can’t do?

**Comment by tarruda** [comment]
> I am reluctant to move totally away from travis. Will the two co-exist?

I suggest to continue using travis normally for PRs and use alternative solutions for testing other platforms when PRs are merged. It shouldn't be a problem if a merge  breaks a platform as long as we identify and fix it quickly

**Comment by ZyX-I** [comment]
@tarruda GH supports using multiple CI services at once, and has a defined API for creating your own one. I think that it is better to use Travis for Ubuntu and Mac OS X, AppVeyor for Windows and @jszakmeister service for what is left, setting up an appropriate hooks for the latter should it appear to be relatively easy (since Ubuntu, Mac OS X and Windows are major platforms and have already existing CI services proper CI<->GH integration is only a nice-to-have feature).

**Comment by tarruda** [comment]
> @tarruda GH supports using multiple CI services at once, and has a defined API for creating your own one. I think that it is better to use Travis for Ubuntu and Mac OS X, AppVeyor for Windows and @jszakmeister service for what is left, setting up an appropriate hooks for the latter should it appear to be relatively easy (since Ubuntu, Mac OS X and Windows are major platforms and have already existing CI services proper CI<->GH integration is only a nice-to-have feature).

If we can integrate alternate CIs into github PR system, all the better

**Comment by ZyX-I** [comment]
https://github.com/blog/1935-see-results-from-all-pull-request-status-checks

**Comment by jszakmeister** [comment]
> Wonderful. Any help you need with hosting costs will be covered by the project funds.

Thanks for the offer, but I'll pick it up for now (it's about $120/yr).  Consider it a contribution to the project. :-)

> I am reluctant to move totally away from travis. Will the two co-exist?

There's no need for it to be a replacement.  GitHub can support both.  I probably should've phrased it better.  My concern with Travis is the limited number of platforms and how slow it is, but I don't intend to replace Travis.

@ZyX-I 
> @tarruda GH supports using multiple CI services at once, and has a defined API for creating your own one. I think that it is better to use Travis for Ubuntu and Mac OS X, AppVeyor for Windows and @jszakmeister service for what is left, setting up an appropriate hooks for the latter should it appear to be relatively easy (since Ubuntu, Mac OS X and Windows are major platforms and have already existing CI services proper CI<->GH integration is only a nice-to-have feature).

I'm not sure I understand what you're suggesting. :-(  Depending on how we structure things, my QB server can get back early and let you know things failed, so I think it's useful in that regard even on platforms being tested by Travis already.  And QB will work with GitHub through the status check API like other services--though it polls PRs rather than integrating with GitHub's web hooks to kick it off.

@tarruda 
> I suggest to continue using travis normally for PRs and use alternative solutions for testing other platforms when PRs are merged. It shouldn't be a problem if a merge breaks a platform as long as we identify and fix it quickly

As others have said, we can have both. :-)  So I'd like QB to eventually run against PRs to help detect the issue before they land.

**Comment by ZyX-I** [comment]
> I'm not sure I understand what you're suggesting. :-( Depending on how we structure things, my QB server can get back early and let you know things failed, so I think it's useful in that regard even on platforms being tested by Travis already. And QB will work with GitHub through the status check API like other services--though it polls PRs rather than integrating with GitHub's web hooks to kick it off.

You mean it runs faster then travis? My concern was the same concern you answered with

> There's no need for it to be a replacement. GitHub can support both. I probably should've phrased it better. My concern with Travis is the limited number of platforms and how slow it is, but I don't intend to replace Travis.

, just I suggested to add Windows CI service (the only one I know) to the list. By the way, first (and the only useful) result in Google for “Windows CI”. It appears that Windows CI services are rather unpopular or hard to setup: I remember at least three \*nix-only services (excluding travis).

**Comment by jszakmeister** [comment]
> You mean it runs faster then travis? My concern was the same concern you answered with

I think Travis is a bit underpowered so things end up taking longer than necessary.  I haven't tried doing everything that we are currently doing in Travis though.  The model is a bit different... QB doesn't reset VMs to an original state like Travis.  It's both a hinderance and a benefit.  There's no need to run updates like what is done in Travis, but then you don't get the benefit of having a clean slate.

> , just I suggested to add Windows CI service (the only one I know) to the list. By the way, first (and the only useful) result in Google for “Windows CI”. It appears that Windows CI services are rather unpopular or hard to setup: I remember at least three *nix-only services (excluding travis).

I can imagine.  Just the licensing alone for the OS and toolchain is probably a pain, much less actually orchestrating the work.

**Comment by ZyX-I** [comment]
> I think Travis is a bit underpowered so things end up taking longer than necessary. I haven't tried doing everything that we are currently doing in Travis though. The model is a bit different... QB doesn't reset VMs to an original state like Travis. It's both a hinderance and a benefit. There's no need to run updates like what is done in Travis, but then you don't get the benefit of having a clean slate.

Why? If I was running ad-hoc CI service I would create a script that creates a VM image once with all necessary dependencies and use the result, rerunning the script rarely.

If speed is much of concern it is logical to do just the same thing, but with a difference: VM is not stopped up until update, but all FSes that can be made read-only are made read-only and other FSes live in different storage then VM image (which is removed once VM image is updated) and are cleared prior to running next build and all processes not in white-list are killed (with kills logged since it is unexpected for the build to leave some running process). This is not entirely “clean environment”, especially if you provide means of running as root, but if NeoVim is not trying to intentionally leave and reuse some state it is rather safe to assume that environment is clean.

**Comment by jszakmeister** [comment]
> Why? If I was running ad-hoc CI service I would create a script that creates a VM image once with all necessary dependencies and use the result, rerunning the script rarely.

I was simply trying to point out that comparing QuickBuild and Travis is a bit like comparing apples and oranges.  They're both fruit, but are different in many ways.

The fact that Travis gives you a clean image each time is nice.  If you screw up badly, it won't affect a build later.  The image is reset and the build can run again fresh and clean.  It also makes it possible to install stuff without a care about how you are affecting the overall system--it'll get cleaned up later.  You have a greater capacity to mess things up and recover from it.

With QuickBuild, we have to make sure to clean up after ourselves--QB doesn't know or care about VMs.  This probably means just cleaning the workspace, but if we start installing things all over the system, then it could get more interesting.  If we bork the system, then we have to rebuild it.

**Comment by jszakmeister** [comment]
> Why don’t you want to make existing CI services do what they can do and use your service only for things they can’t do?

I just realized I never responded to this.  One concern I have is coordinating across many different services.  We already see things being flaky because of sites going down and other issues, and when one of them does, everything fails.  I believe we could have one that's slightly more robust and support more than just one flavor (Fedora, OpenBSD, Mac OS X Mavericks *and* Yosemite, etc.).  We'll have to see how far I can stretch things.

Also, QuickBuild could allow us to do things like build promotions and walk the source through a release process that ends up building release tarballs, and perhaps binaries for a couple of systems (I'm thinking Windows here).  QuickBuild is very rich in what it offers.  I've been using it for 10+ years, and I feel like I still only know half of what it can do. :-)

**Comment by xu-cheng** [comment]
A trivia suggestion. Use http://bot.neovim.org as CI url.

**Comment by jszakmeister** [comment]
For those interested, QB is now building against all open PRs automatically.  I've also filed a bug report with PMEase so that it will stop using "default" as the build system name.  They use egit-client, and that just grew support for changing the name.  Hopefully it won't be too long before I can put something more useful there.

**Comment by justinmk** [comment]
@jszakmeister can this be closed?

**Comment by jszakmeister** [comment]
Yes, definitely.  It was only intended to inform everyone about what I was doing.
