### ISSUE TITLE
Sort diagnostics by column number in quickfix list

### ISSUE THREAD

**Issue by tae-soo-kim** [neovim/neovim#21456]
### Feature description

Diagnostics may contain column numbers. But currently neovim doesn't know about columns and displays them out of order when converted to a quickfix list. The problem is within this function:

https://github.com/neovim/neovim/blob/1c4794944deb734b24b4a424c50b766a96e050dd/runtime/lua/vim/diagnostic.lua#L1666-L1672

A further test `a.col < b.col` is necessary when both `bufnr` and `lnum` compare equal.

**Comment by justinmk** [comment]
@tae-soo-kim PR welcome

**Comment by tae-soo-kim** [comment]
PR https://github.com/neovim/neovim/pull/21457 has been made.

**Comment by tae-soo-kim** [comment]
The commit message has been fixed in the last commit. But the PR still keeps failing on the Commit Linter. I don't know what to do with it. Can I assume you would do a squash merge using the last commit message?

**Comment by alanfortlink** [comment]
You can probably do a `git rebase -i HEAD~3` and use the `reword` command to change the previous commit as well. I think you'll have to `--force` push, hopefully that's not a problem. Anyway, I hope this is of some help :)

**Comment by tae-soo-kim** [comment]
@alanfortlink Thanks I'll see if someone with permission can squash merge. I feel it silly having to re-checkout the entire repository just for a commit message reword yet GitHub doesn't allow user to squash his own commits on the web.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/21457
