### ISSUE TITLE
nvim opened under mosh does not honor the &guicursor="i-ci-ve:ver25"

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#21461]
### Neovim version (nvim -v)

NVIM v0.8.1

### Vim (not Nvim) behaves the same?

not tested

### Operating system/version

archlinux

### Terminal name/version

xterm 377

### $TERM environment variable

xterm

### Installation

system package manager

### How to reproduce the issue

* $ mosh localhost
* $ nvim --clean
* `:echo $guicursor` -> `n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20`
* `i` # enter the insert mode

### Expected behavior

the cursor is a "vert bar" in insert mode.

### Actual behavior

the cursor remains as a block

### extra info

* mosh 1.4.0

**Comment by zeertzjq** [comment]
`normal i` do not end in Insert mode.

**Comment by haolian9** [comment]
sorry, it's been fixed

**Comment by zeertzjq** [comment]
mosh doesn't support cursor shape.
https://github.com/mobile-shell/mosh/issues/352

**Comment by haolian9** [comment]
ah, shame! i could have done some searching on mosh, sorry for the noise.
