### ISSUE TITLE
WSL, ran apt ugrade, win32yank.exe no longer works

### ISSUE THREAD

**Issue by ckp95** [neovim/neovim#21475]
### Neovim version (nvim -v)

0.4.3

### Vim (not Nvim) behaves the same?

idk

### Operating system/version

WSL, Ubuntu 20.04

### Terminal name/version

Alacritty (windows)

### $TERM environment variable

xterm-256color

### Installation

apt

### How to reproduce the issue

I run Neovim within WSL. I use the `win32yank.exe` program to make nvim use the Windows clipboard. When I press `yy` to copy a line, I get the error:

```
clipboard: error invoking xclip: Waiting for selection requests, Control-C to quit   Waiting for selection request number 1 X connection to :0 broken (explicit kill or server shutdown).
```

When I try to paste something from the Windows clipboard using `p`, I get the error:

```
clipboard: error: Error: target STRING not available
```

My `init.vim` has this line:

```
set clipboard=unnamedplus
```

I have the `win32yank.exe` program sitting in a folder on my $PATH:

```
$ which win32yank.exe
/mnt/c/Users/{username}/AppData/Local/Microsoft/WindowsApps/win32yank.exe
```

Running `:checkhealth` says this about the clipboard:

```
 18 ## Clipboard (optional)
 19   - OK: Clipboard tool found: xclip
```

**The win32yank.exe worked until today**, then I ran `sudo apt update && sudo apt upgrade` and now it no longer works. I don't know what apt changed that broke this. Is there some dependency I need?

A few months ago I had a similar problem where `win32yank.exe` broke when I installed `mono-complete` in WSL, I was able to fix it soon after by running `sudo apt remove mono-complete`. But that isn't working right now (I don't have `mono-complete` installed to begin with).

### Expected behavior

-

### Actual behavior

-

**Comment by clason** [comment]
Sorry, that version is massively outdated; current is 0.8.1. We can't support such an outdated version.

Also, this sounds like an issue with `win32yank`, not Neovim?

**Comment by ckp95** [comment]
Oh I thought win32yank was provided by the neovim developers, my mistake

**Comment by clason** [comment]
No, it's a separate project: https://github.com/equalsraf/win32yank

**Comment by ckp95** [comment]
If anyone finds this via search: I solved the problem by upgrading from WSL Ubuntu 20.04 to 22.04 and installing the newer Neovim from the 22.04 repos. I also had to remove `xclip` because Neovim listed it as a recommended dependency when I `apt install`ed it, and it was taking precedence over win32yank.exe.
