### ISSUE TITLE
require relative path doesnt work as expected with `-u`

### ISSUE THREAD

**Issue by sigmaSd** [neovim/neovim#21476]
### Neovim version (nvim -v)

NVIM v0.8.1

### Vim (not Nvim) behaves the same?

nvim specific

### Operating system/version

linux

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

arch  community package

### How to reproduce the issue

```sh
mkdir qsd
echo 'require("b")' > qsd/a.lua
touch qsd/b.lua
vim -u qsd/a.lua
```

### Expected behavior

no errors, a can require b which is next to it

### Actual behavior

require in a fails with can't find module b

If I copy the same structure to ~/.config/nvim and run nvim(without -u) it works

**Comment by sigmaSd** [comment]
a.lua
```lua
require("b")
```

**Comment by clason** [comment]
Yeah, that's not how this works. Require us always relative to Lua's package.path. if you want to change that, you need to bend it explicitly.

**Comment by sigmaSd** [comment]
`vim --cmd "set rtp+=./qsd/" -u qsd/lua/a.lua`
