### ISSUE TITLE
change terminal cursor when quit nvim

### ISSUE THREAD

**Issue by dreistein543** [neovim/neovim#21480]
### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.1

### Terminal name/version

iterm2 v3.4.18

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

``` zsh
nvim

:q
```

### Expected behavior

I hope nothing happens to my iTerm configuration.

### Actual behavior

I have configured my iTerm2 with a _**blinking vertical bar**_ cursor.

However, when I open and quit `nvim`, the cursor will be changed back to an _**unblinking box style**_. 
More worse, it cannot be re-configured through iTerm2 preference even I quit and reopen iTerm2, unless I close and open a new iTerm2 window.

I have tried vim on my Mac and nothing like that happens.

**Comment by zeertzjq** [comment]
In what version did this start happening?

**Comment by dreistein543** [comment]
> In what version did this start happening?

I'm sorry, I have just started to use nvim for a few hours. No idea about which version starts exactly.

**Comment by zeertzjq** [comment]
`xterm-265color` doesn't look right. It should be `xterm-256color`

**Comment by dreistein543** [comment]
> `xterm-265color` doesn't look right. It should be `xterm-256color`. Is it a typo in the issue or is that the actual value of `$TERM`?

sorry, it’s my writing mistake, `xterm-256color` is right.

**Comment by gmr458** [comment]
@dreistein543 I use this:
```lua
vim.cmd([[
    augroup RestoreCursorShapeOnExit
        autocmd!
        autocmd VimLeave * set guicursor=a:ver1
    augroup END
]])
```

This works for me with Alacritty terminal and GNOME terminal, with kitty terminal it's not necessary, kitty keeps the shape of the cursor.

@zeertzjq  Vim doesn't change the shape of the cursor, why does Neovim?

**Comment by zeertzjq** [comment]
You can disable cursor shape change using `:et guicursor=`

**Comment by zeertzjq** [comment]
This is mentioned in FAQ: https://github.com/neovim/neovim/wiki/FAQ#cursor-style-isnt-restored-after-exiting-or-suspending-and-resuming-nvim

**Comment by zeertzjq** [comment]
Duplicate of #4396

**Comment by itse4elhaam** [comment]
> @dreistein543 I use this:
> 
> ```lua
> vim.cmd([[
>     augroup RestoreCursorShapeOnExit
>         autocmd!
>         autocmd VimLeave * set guicursor=a:ver1
>     augroup END
> ]])
> ```
> 
> This works for me with Alacritty terminal and GNOME terminal, with kitty terminal it's not necessary, kitty keeps the shape of the cursor.
> 
> @zeertzjq Vim doesn't change the shape of the cursor, why does Neovim?

I want the vintage cursor
