### ISSUE TITLE
`vim.treesitter.language.require_language('{foo}')` errors with `E219: Missing {`

### ISSUE THREAD

**Issue by 0xAdk** [neovim/neovim#21485]
### Neovim version (nvim -v)

v0.9.0-dev-531+gf04087d8ba

### Vim (not Nvim) behaves the same?

yes-ish, vim 9.0

### Operating system/version

arch

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

AUR (neovim-git)

### How to reproduce the issue

1. nvim --clean
2. `:lua =vim.treesitter.language.require_language('{foo}', nil, true)`

### Expected behavior

```lua
vim.treesitter.language.require_language('{foo}', nil, true)
```
evaluates to `false` since `{foo}` isn't an available language.

### Actual behavior

```lua
vim.treesitter.language.require_language('{foo}', nil, true)
```

generates an error:
```
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:20: Vim:E219: Missing {.
stack traceback:
        [C]: in function 'nvim_get_runtime_file'
        /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:20: in function 'require_language'
        [string ":lua"]:1: in main chunk
```

From what I can tell when looking at `treesitter/language.lua:20`: 
```lua
local fname = 'parser/' .. vim.fn.fnameescape(lang) .. '.*'
local paths = a.nvim_get_runtime_file(fname, false)
```
It seems to be an issue with `fnameescape()` only escaping `{`'s. 
When expanding `\{foo}.*`, the `}` is recognized as a special character which is now missing its `{`.
While when expanding just `\{foo}` without the added `.*`,`}` isn't treated as a special character.

Vim has the same problem.
```vim
echo glob(fnameescape('{foo}'))
```
Is fine, It looks for a file called `{foo}` instead of `foo`.
While
```vim
echo glob(fnameescape('{foo}') .. '.*')
```
results in `E219: Missing {.`

**Comment by imskr** [comment]
Can I work on this?

**Comment by dundargoc** [comment]
No permission needed, go for it.

**Comment by clason** [comment]
This begs the question: _why_ are you using `{foo}` as a literal language and expect this to work?

**Comment by 0xAdk** [comment]
I had some language injection queries  for lua
```scheme
((comment content: _ @language) (string content: _ @content))
; for `func --[[lang]] "content"`
((comment content: _ @language) (_ (string content: _ @content)))
```
with the idea being I'd be able to specify the language a string should be highlighted in using a comment before it
```lua
local vim_code = --[[vim]] [[
	echo "hi"
]]
```
this worked until I opened up a file with something like this in it
```lua
local table = {
	foo = true, -- some text {}
	bar = "str",
}
```
and this query
```
((comment content: _ @language) (_ (string content: _ @content)))
```
inadvertently matched
```
(comment)
(field value: (string))
````
and since the way language injections check if the language is valid is running it through `vim.treesitter.language.require_language` I encountered this issue

**Comment by clason** [comment]
That means that your matching strategy is flawed...

**Comment by clason** [comment]
Sounds more like an issue with `fnameescape` then -- which would be an issue for Vim.

**Comment by justinmk** [comment]
Note that 'isfname' option can be set to change the behavior of `fnameescape()`.
