### ISSUE TITLE
[builtin-term] Blank cursor in corner of ncmpc

### ISSUE THREAD

**Issue by Pyrohh** [neovim/neovim#2149]
Using ncmpc in `st` + `tmux` looks like this:
![ncmpc_term](https://cloud.githubusercontent.com/assets/4174345/6567300/c476311e-c69b-11e4-909b-a1a92beab1f3.png)
In nvim it looks like this:
![ncmpc_nvim](https://cloud.githubusercontent.com/assets/4174345/6567309/df0441b0-c69b-11e4-8fed-9d9e695efb8e.png)

Ignore the difference in the highlighting at the top, the problem is the blank cursor in the lower left.

**Comment by tarruda** [comment]
It should be fixed in the latest version of the terminal branch, can you verify?

**Comment by Pyrohh** [comment]
Thanks @tarruda, my issue is fixed. Just a reminder (given you probably have a lot to cover), `colorcolumn` is still an issue in `:term` if set.
