### ISSUE TITLE
Translation management tool

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2150]
Currently, we handle translations like source code, i.e. PRs are sent by contributors to update the translations (e.g. most recently #2147).

There are a number of third-party tools available to manage translations, e.g. [CrowdIn](https://crowdin.com) (example: [gorhill/uBlock](https://crowdin.com/project/ublock)) and [Transifex](https://www.transifex.com) (example: [whispersystems/textsecure](https://www.transifex.com/projects/p/textsecure-official/)) (both are free for OSS; I'm sure there's other alternatives as well). Compared to PRs, such tools would probably make it easier for translations to be contributed and reviewed.

**Comment by Pyrohh** [comment]
After reading CrowdIn's feature list, I must admit it looks very useful. Would it be much of a hassle to set up?

**Comment by rainerborene** [comment]
Just by looking at their [API documentation](https://crowdin.com/page/api) I think it wouldn't be much of a hassle to set up. It would be great If we could move all translation files to Crowdin and automate its generation.

**Comment by rainerborene** [comment]
If you create an account on CrowdIn I could be responsible for the migration. @tarruda @justinmk

**Comment by fwalch** [comment]
@rainerborene You mean downloading the PO files from the translation service while building? That could be interesting, I didn't consider that.. I think the other projects I mentioned just periodically commit the updated PO files to their main repo.

**Comment by fwalch** [comment]
To get the translations into `neovim/neovim`, we can use an approach similar to neovim/bot-ci#52 and periodically create pull requests with updated PO files.

**Comment by rainerborene** [comment]
I think we should have a single source of truth. If someone wants to contribute with translations just access our CrowdIn profile page instead of sending pull requests like you said. Same with patches from the official vim repository.

**Comment by fwalch** [comment]
I also think that if we use such a translation service, pull requests for PO files shouldn't be accepted anymore. Still, we somehow need to get the translations from the translation service into the neovim repo. The bot would simply help to automate this process. We could also just let it commit the PO files directly, but letting it create a PR first is safer in case something goes wrong.
We can't download the translations during the build process because compiling the same version (from a code/commit perspective) of neovim at different times could give different results (because of different translations).

**Comment by rainerborene** [comment]
Makes sense.

**Comment by fwalch** [comment]
Another translation service: http://weblate.org/en/

**Comment by tarruda** [comment]
I'm reading the Crowdln documentation

**Comment by tarruda** [comment]
The problem with CrowdIn is that we have to upload source files, it doesn't seem to have any sort of integration with github(the github login is just for your email/photo, in fact anyone can create the neovim project there). So each time a source file is updated it needs to be uploaded. Ideally we would setup a web hook that tell crowdIn to download files on each push to master

Is there an alternative that integrates better with github?

**Comment by fwalch** [comment]
@tarruda Maybe weblate? http://docs.weblate.org/en/latest/faq.html#how-to-create-automatic-workflow

**Comment by fwalch** [comment]
From the weblate docu:

```
GitHub includes direct support for notifying Weblate, just enable Weblate service hook in repository settings and set URL to URL of your Weblate installation.
```

Maybe check the webhook list on Github and see if any of the other translation services are in there?

**Comment by tarruda** [comment]
> But we could also create a bot script that basically runs make translations (or whatever its called) and uploads the PO(T?) files to Crowdin using crowdin-cli, I think.

:+1: crowdin-cli seems like a simple way to integrate with github. Maybe I misunderstood CrowdIn, but why would you upload PO files? I was under the impression that you upload the source files and download PO files.

> Maybe check the webhook list on Github and see if any of the other translation services are in there?

Will do, thanks

**Comment by fwalch** [comment]
> I was under the impression that you upload the source files and download PO files.

Oh, I thought you'd upload "empty" PO files and get back PO files with translations..

**Comment by tarruda** [comment]
> Oh, I thought you'd upload "empty" PO files and get back PO files with translations..

I think there may be a way to import existing PO files(which we absolutely need as a feature), but only during the initial setup. After that I think people will just edit using their interface and we can download the po files(possibly as a build target)

**Comment by rainerborene** [comment]
> I think there may be a way to import existing PO files(which we absolutely need as a feature), but only during the initial setup. After that I think people will just edit using their interface and we can download the po files(possibly as a build target)

:+1: 

See here https://crowdin.com/page/gettext-localization-editor

**Comment by fwalch** [comment]
From what I've seen so far, [weblate](http://weblate.org) should be the easiest tool to set up (we only need to add a Git webhook). It could even push the updated PO files directly into our repo -- we probably don't want that, but with nijel/weblate#656 it could send PRs with the updated translations. Instead of spending time writing scripts for `bot-ci` to push/pull translations, we could just try to contribute this PR functionality to weblate (don't know how hard it would be, though).

**Comment by ZyX-I** [comment]
> I think there may be a way to import existing PO files(which we absolutely need as a feature), but only during the initial setup. After that I think people will just edit using their interface and we can download the po files(possibly as a build target)

I have an experience with transfirex as a user (bitbucket translation) and it was good.

Most notable thing is that I can download `*.po` file, edit it and upload it back which is far more convenient then doing translation using any web interface if you need packet changes (used this functionality to change translation of the term “pull request”, though it was not accepted).

Does any of the alternatives provide such feature for a *user*? I do not like that you do not consider PO file uploading a feature that can be used by a user.

**Comment by fwalch** [comment]
> Does any of the alternatives provide such feature for a user? I do not like that you do not consider PO file uploading a feature that can be used by a user after the initial setup.

Weblate seems to support this: [Weblate docu: Export and import](http://docs.weblate.org/en/latest/user/translating.html#export-and-import)

![http://docs.weblate.org/en/latest/_images/export-import.png](http://docs.weblate.org/en/latest/_images/export-import.png)

[Permission-wise](http://docs.weblate.org/en/latest/admin/auth.html#extra-privileges) it should also work for users, not only admins:

> Can upload translation [Users, Managers]
>    Uploading of translation files.

**Comment by fwalch** [comment]
FWIW, I started a PR at weblate to support GitHub pull requests, if somebody wants to help: https://github.com/nijel/weblate/pull/723

**Comment by fwalch** [comment]
Weblate now has support for sending pull requests with updated translations (https://github.com/nijel/weblate/issues/723), which should be available on https://hosted.weblate.org eventually.

**Comment by Pyrohh** [comment]
Thanks @fwalch, that looks very promising. I assume we should put a link in our main README.md for translators once this is all ready.

**Comment by fwalch** [comment]
@Pyrohh It will probably take a while until PRs are supported on hosted weblate, but I'll try to keep an eye on it.

**Comment by justinmk** [comment]
Reopen if needed.

**Comment by rainerborene** [comment]
@tarruda Do you mind if you sign up on CrowdIn [open source request form](https://crowdin.com/page/open-source-project-setup-request)? I'm planning to do some tests next week. Send me the credentials to rainerborene at gmail dot com.

**Comment by tarruda** [comment]
@rainerborene I already tried Crowdln but it couldn't import the existing localization files, and there was no builtin integration with github. We need something that can easily be integrated with our existing tooling.

**Comment by onemanstartup** [comment]
https://poeditor.com/features/ this seems to have github integration
