### ISSUE TITLE
vim.opt_global.foobar:get() fails to get current global option value

### ISSUE THREAD

**Issue by aileot** [neovim/neovim#21506]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-538+gf9c62ce34

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Endeavour OS 

### Terminal name/version

wezterm 20221119-145034-49b9839f, alacritty 0.11.0 (8dbaa0bb)

### $TERM environment variable

xterm-256color

### Installation

AUR, bob, rhysd/action-setup-vim

### How to reproduce the issue

nvim --clean
:setglobal signcolumn=yes
:lua= vim.opt_global.signcolumn:get()

### Expected behavior

Returns "yes".

### Actual behavior

Returns "auto", its default.

Both `:setglobal signcolumn?` and `:lua= vim.go.signcolumn` returns "yes", and the bug doesn't happen on v0.8.1.

It only happens with "local to window" option like "wrap", not with "global or local to window" option like "scrolloff".

**Comment by zeertzjq** [comment]
Regression from #21382

**Comment by clason** [comment]
workaround: use `vim.go.foobar`.

**Comment by herrvonvoid** [comment]
i looked at the regression found by @zeertzjq in #21382 and have the following thoughts:

#21382 closes #18255 which tries to achieve this: global-local options do not have a local value in some cases and then opt_local:append() should copy and extend the global value as vimscript += would. However, as there is no local value, this didn't happen. The patch fixed this by making opt_local fall back to the global value.

The problem with the patch is that now getting options with vim.opt[_local|_global] always ignores the scope info.

Instead it should check whether the passed scope is local and the option a global-local, and only then not pass a scope to vim.api.nvim_get_option_value()

imo

@phelipetls @lewis6991

**Comment by phelipetls** [comment]
Just created a patch to try to address this: https://github.com/neovim/neovim/pull/25196.

> Instead it should check whether the passed scope is local and the option a global-local, and only then not pass a scope to vim.api.nvim_get_option_value()

I'm not sure what by checking if "the option a global-local" but my reasoning was that we should use as initial value a global-local value for `vim.opt` and `vim.opt_local` and global value for `vim.opt_global`.

The previous patch tried to address that `vim.opt_local` ignored local values only when in fact it should have used a global-local value (i.e., should not have passed a `{ scope = "local" }` to `api.nvim_get_option_value`).

But obviously, in hindsight, it was a mistake to not pass `{ scope = "global" }` in the case of `vim.opt_global`.
