### ISSUE TITLE
autocmd nvim_cmdwin doesn't limit syntax highlighting to 1 line

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#21517]
### Neovim version (nvim -v)

0.9.0-dev-82-g0ef6aaa3a

### Vim (not Nvim) behaves the same?

no, doesn't have the autocmd defined in autocmd.c like neovim does

### Operating system/version

macOS 12.5.1

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

source

### How to reproduce the issue

nvim --clean
q:
enter some commands, exit the window C-w q, and renter, see it highlights the entire command-window buffer

### Expected behavior

I thought this default autocmd was supposed to limit the syntax highlighting to 1 line? 

### Actual behavior

Entire command-line-window is highlighted as ft=vim, as :h cmdline.txt VARIOUS mentions it turns on ft=vim.

**Comment by zeertzjq** [comment]
What made you think so? And what is the problem?

**Comment by craigmac** [comment]
@zeertzjq my mistake!
