### ISSUE TITLE
neovim for Windows (nvim-qt.exe) starts with micro-window in Windows Sandbox

### ISSUE THREAD

**Issue by roysubs** [neovim/neovim#21516]
### Neovim version (nvim -v)

NVIM v0.8.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compiled by runneradmin@fv-az30-11

### Vim (not Nvim) behaves the same?

no, vim works properly with normal window size

### Operating system/version

Windows 10

### Terminal name/version

n.a. only when running nvim.exe or nvim-qt.exe

### $TERM environment variable

n.a.

### Installation

Downloaded archive

### How to reproduce the issue

Just start nvim-qt.exe in any way when in a Windows Sandbox

### Expected behavior

Window should start with a normal size, but it does not, it only ever starts micro-sized (the absolute minimum size) so is quite frustrating to work with as this happens every time the Windows Sandbox is started.

### Actual behavior

Starts micro-sized window that is unusable until you resize it, but this does not happen anywhere else i.e. in all non-Sandbox environments, nvim.exe / nvim-qt.exe open normally. This is easily testable and I've tried it on about 6 systems with Windows Sandbox, always the same result.
![neovim](https://user-images.githubusercontent.com/16388699/209402957-8ab9eaad-cf40-451d-914d-889a937d55c3.png)

**Comment by zeertzjq** [comment]
This should he reported to neovim-qt.
