### ISSUE TITLE
TUI: cursor "reverse" does not work in Windows Terminal

### ISSUE THREAD

**Issue by MainEditor** [neovim/neovim#21526]
### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

— IDK

### Operating system/version

Windows 10 22H2 19045.2364

### Terminal name/version

WindowsTerminal 1.15.3465.0

### $TERM environment variable

— IDK

### Installation

Scoop

### How to reproduce the issue

nvim --clean filename

### Expected behavior

Expected a render like in Helix editor. In this picture all editors runned without any config and tweaks with their parameters OOTB. Cursor shape in Terminal settings is setted up to default(Vertical line). Also Helix render cursor corretly with transparent theme.
![изображение](https://user-images.githubusercontent.com/98752769/209445029-a574bc51-f712-4feb-889c-3edebe2bf2b3.png)

### Actual behavior

Cursor rendering wrong.

**Comment by karlronsaria** [comment]
I'm having the same problem. I can't see anything I select in the editor.

### expected

Windows Powershell:

![2022_12_28_154039_expected_WindowsPowerShell](https://user-images.githubusercontent.com/7386802/209886459-26ac2872-782b-42db-866c-0fd635034a44.gif)

### actual

Windows Terminal:

![2022_12_28_154419_actual_WindowsTerminal](https://user-images.githubusercontent.com/7386802/209886509-ce19ded2-f9f5-49e1-833b-858ae2bcb258.gif)

### version

- neovim: ``v0.8.1``

**Comment by justinmk** [comment]
what does `:hi Cursor` say? this might just be a colorscheme issue. Try some other colorscheme, or try `:set bg=light` or `:set bg=dark`

**Comment by MainEditor** [comment]
@justinmk 
```:hi Cursor```:
![изображение](https://user-images.githubusercontent.com/98752769/210127768-f56a9ae4-f427-4fc4-bc92-b8efc2b340d9.png)
In orther colorschemes all the same with error. ```:set bg=light``` and ```:set bg=dark``` don't helps.

**Comment by justinmk** [comment]
have you set `termguicolors` and/or the `guicursor` option? To narrow down the issue, try this:

    :set guicursor=
    :hi Cursor cterm=NONE gui=NONE ctermfg=red ctermbg=black guifg=red guibg=black

After narrowing down the issue, we can think about how to avoid this by default.

**Comment by MainEditor** [comment]
Not helps
![изображение](https://user-images.githubusercontent.com/98752769/210201909-1cf386d1-5ed4-4dd8-a891-707a128b83c1.png)

**Comment by MainEditor** [comment]
@justinmk I'm also found this WT issue exist [link](https://github.com/microsoft/terminal/issues/9610) but for some reason in Helix all works good with any OOTB colorscheme

**Comment by justinmk** [comment]
> For me helped [this](https://github.com/microsoft/terminal/issues/9610#issuecomment-944940268)

Thanks for the reference! It looks like that workaround is setting `set guicursor+=n-v-c-sm:block-WindowsTerminalCursorBg`,  confirms that this is related to `gui=reverse` / `cterm=reverse`.

Though I don't understand why my `hi Cursor` suggestion didn't work for you, since it doesn't use "reverse". 

Anyway, if "reverse" is the issue, maybe we need to fix tui.c to emit whatever Windows Terminal expects.

**Comment by MainEditor** [comment]
>indicates a potential Windows Terminal bug, but maybe we can work around it?
Sure. Windows Terminal has this bug for a long time and it appears not only in (neo)vim. In the issue discussion many (neo)vim users because this bug hinders to work in editor. I'm also found [this solution](https://github.com/microsoft/terminal/issues/9610#issuecomment-944940268) not works in the Windows Terminal preview with new "AtlasEngine" for text

**Comment by 3N4N** [comment]
The bug in ms-terminal may have been fixed by [this upate](microsoft/terminal#9610).  I am not totally sure because I have no idea what is actually going on but I can vouch I can now see the characters clearly under my block cursor.  @MainEditor, do you have any update?

**Comment by mndtr** [comment]
For now works properly and fine at least for me.
