### ISSUE TITLE
Getting ERROR when installing nvim from release page

### ISSUE THREAD

**Issue by DB-db-dron** [neovim/neovim#21528]
### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Kali GNU/Linux 2022.4

### Terminal name/version

GNOME or maybe `sudo -s`

### $TERM environment variable

xterm-256color

### Installation

see `how to reproduce section` information

### How to reproduce the issue

```
 wget https://github.com/neovim/neovim/releases/download/v0.8.1/nvim-linux64.deb
 sudo apt install ./nvim-linux64.deb
```
 

### Expected behavior

It is expected that nvim is installed and starts working.

### Actual behavior

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'neovim' instead of './nvim-linux64.deb'
The following packages were automatically installed and are no longer required:
  libicu71 libluajit-5.1-2 libluajit-5.1-common libmsgpackc2 libtermkey1 libtree-sitter0 libunibilium4 libvterm0
  lua-luv neovim-runtime python3-greenlet python3-msgpack python3-pynvim xclip
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  neovim
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/10.5 MB of archives.
After this operation, 33.1 MB of additional disk space will be used.
Get:1 /root/nvim-linux64.deb neovim amd64 0.8.1 [10.5 MB]
(Reading database ... 65661 files and directories currently installed.)
Preparing to unpack /root/nvim-linux64.deb ...
Unpacking neovim (0.8.1) ...
dpkg: error processing archive /root/nvim-linux64.deb (--unpack):
 trying to overwrite '/usr/share/applications/nvim.desktop', which is also in package neovim-runtime 0.7.2-3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /root/nvim-linux64.deb
N: Download is performed unsandboxed as root as file '/root/nvim-linux64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by zeertzjq** [comment]
Uninstall ``neovim-runtime
