### ISSUE TITLE
`vim.lsp.get_active_clients({bufnr = 0})` can error

### ISSUE THREAD

**Issue by stasjok** [neovim/neovim#21523]
### Neovim version (nvim -v)

v0.8.1

### Vim (not Nvim) behaves the same?

—

### Operating system/version

Linux

### Terminal name/version

Windows Terminal

### $TERM environment variable

tmux-256color

### Installation

Nix

### How to reproduce the issue

I've got an error when testing with mini.nvim. My goal is to wait for lsp to start with something like:

```lua
child.lua_get([[vim.wait(5000, function() return #vim.lsp.get_active_clients({name = "marksman", bufnr=0}) >= 1 end, 50)]])
```

In my case if I didn't guard it with pcall it's pretty much guaranteed to get an error:

```
Error executing lua: ...eovim-unwrapped-0.8.1/share/nvim/runtime/lua/vim/lsp.lua:1796: attempt to index local 'client' (a nil value)
  stack traceback:
        ...eovim-unwrapped-0.8.1/share/nvim/runtime/lua/vim/lsp.lua:1796: in function 'get_active_clients'
```

The code that triggers an error:

https://github.com/neovim/neovim/blob/b840eb694579f64697ed6248ce2884da3ecf7783/runtime/lua/vim/lsp.lua#L1790-L1800

What I think is happening here, is when I filter active clients with `{bufnr = 0}` there is a time frame when `all_buffer_active_clients` is populated with client ids, but `active_clients` not yet. `mini.test` run code via RPC in child neovim. Maybe it's able to execute something in between? Unfortunately I didn't manage to reproduce it with minimal `init.lua`, maybe it is possible with some async calls like vim.schedule.

I think a nil check should be enough, something like:

```lua
    if
      client
      and (filter.id == nil or client.id == filter.id)
      and (filter.name == nil or client.name == filter.name)
    then
```

### Expected behavior

`get_active_clients` shouldn't error, but return empty clients list.

### Actual behavior

```
Error executing lua: ...eovim-unwrapped-0.8.1/share/nvim/runtime/lua/vim/lsp.lua:1796: attempt to index local 'client' (a nil value)
  stack traceback:
        ...eovim-unwrapped-0.8.1/share/nvim/runtime/lua/vim/lsp.lua:1796: in function 'get_active_clients'
```

**Comment by glepnir** [comment]
right should check the client is nil or not.

**Comment by stasjok** [comment]
I was wrong that I couldn't reproduce it. Looking at the code it's not enough to filter by `{bufnr = 0}`, but I need any other filter. I was trying without it. Here is a minimal reproducer:

`minimal_init.lua`:
```lua
vim.api.nvim_create_autocmd("FileType", {
  group = vim.api.nvim_create_augroup("Lsp", {}),
  pattern = "lua",
  callback = function()
    vim.schedule(function()
      vim.lsp.start({
        name = "sumneko_lua",
        cmd = { "lua-language-server" },
        settings = { Lua = { telemetry = { enable = false } } },
        reuse_client = function()
          return true
        end,
      })
    end)

    local function cb()
      local client = vim.lsp.get_active_clients({ name = "sumneko_lua", bufnr = 0 })
      if #client >= 1 then
        vim.notify("Yes!")
      else
        vim.schedule(cb)
      end
    end
    vim.schedule(cb)
  end,
})
```

```bash
wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
chmod +x nvim.appimage
./nvim.appimage --clean -n -u minimal_init.lua minimal_init.lua
```

**Comment by glepnir** [comment]
because you do lsp.start first it's async function  then you run the `get_active_clients`  there has something wrong.

```
  local t = filter.bufnr and (all_buffer_active_clients[resolve_bufnr(filter.bufnr)] or {})
    or active_clients
```

result of t is ` { true }` , then into the for loop the client_id equals to `true` and active_clients is empty table now. so the client is nil value.

**Comment by glepnir** [comment]
this patch should be fix

```diff
diff --git a/runtime/lua/vim/lsp.lua b/runtime/lua/vim/lsp.lua
index dc5008399..a4278dc89 100644
--- a/runtime/lua/vim/lsp.lua
+++ b/runtime/lua/vim/lsp.lua
@@ -1842,6 +1842,11 @@ function lsp.get_active_clients(filter)

   local t = filter.bufnr and (all_buffer_active_clients[resolve_bufnr(filter.bufnr)] or {})
     or active_clients
+
+  if #active_clients == 0 then
+    return clients
+  end
+
   for client_id in pairs(t) do
     local client = active_clients[client_id]
     if
```

**Comment by glepnir** [comment]
this patch should be fix

```diff
diff --git a/runtime/lua/vim/lsp.lua b/runtime/lua/vim/lsp.lua
index dc5008399..a4278dc89 100644
--- a/runtime/lua/vim/lsp.lua
+++ b/runtime/lua/vim/lsp.lua
@@ -1842,6 +1842,11 @@ function lsp.get_active_clients(filter)

   local t = filter.bufnr and (all_buffer_active_clients[resolve_bufnr(filter.bufnr)] or {})
     or active_clients
+
+  if #active_clients == 0 then
+    return clients
+  end
+
   for client_id in pairs(t) do
     local client = active_clients[client_id]
     if
```

**Comment by stasjok** [comment]
> this patch should be fix
> 
> ```diff
> diff --git a/runtime/lua/vim/lsp.lua b/runtime/lua/vim/lsp.lua
> index dc5008399..a4278dc89 100644
> --- a/runtime/lua/vim/lsp.lua
> +++ b/runtime/lua/vim/lsp.lua
> @@ -1842,6 +1842,11 @@ function lsp.get_active_clients(filter)
> 
>    local t = filter.bufnr and (all_buffer_active_clients[resolve_bufnr(filter.bufnr)] or {})
>      or active_clients
> +
> +  if #active_clients == 0 then
> +    return clients
> +  end
> +
>    for client_id in pairs(t) do
>      local client = active_clients[client_id]
>      if
> ```

I may be wrong but I think it's better to check for nil for every client (like in a snippet from my issue). Because I can imagine a situation when there are several clients, one maybe already in `active_clients`, but others are not.

**Comment by glepnir** [comment]
I don't think it's necessary to check if client is nil. but we can get an insurance policy for this check :)

**Comment by stasjok** [comment]
> I don't think it's necessary to check if client is nil. but we can get an insurance policy for this check :)

I still think that your patch is not enough. Just add to minimal_init a second client and I get the same error:

```lua
vim.api.nvim_create_autocmd("FileType", {
  group = vim.api.nvim_create_augroup("Lsp", {}),
  pattern = "lua",
  callback = function()
    vim.lsp.start({
      name = "sumneko_lua",
      cmd = { "lua-language-server" },
      settings = { Lua = { telemetry = { enable = false } } },
    })
    vim.lsp.start({
      name = "sumneko_lua2",
      cmd = { "lua-language-server" },
      settings = { Lua = { telemetry = { enable = false } } },
    })

    local function cb()
      local client = vim.lsp.get_active_clients({ name = "sumneko_lua", bufnr = 0 })
      if #client >= 1 then
        vim.notify("Yes!")
      else
        vim.schedule(cb)
      end
    end
    vim.schedule(cb)
  end,
})
```

**Comment by glepnir** [comment]
this is not correct example , if the server instance support workspace you should reuse client not spawn a new one

**Comment by stasjok** [comment]
> this is not correct example , if the server support workspace you should reuse client not spawn a new one

I did it just for simplicity. It can be completely different client (not sumneko_lua). Also it can be different buffers/filetype.

**Comment by glepnir** [comment]
no, we can check it before the for loop. if there is no elements in this table just return . no need into the for loop
