### ISSUE TITLE
Add fold status in shada

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#21532]
### Feature already in Vim?

NO

### Feature description

can neovim let shada remenber fold stauts?
we can only use `foldenable` now to control fold status `on / off` when entering the neovim, if we fold something and exit neovim, when we re-enter neovim again, the fold is just all folded or unfolded controlled by `foldenable`, if we can let shada-file remember the folding status that would be convenient and great!

**Comment by justinmk** [comment]
folds are window-relative. `:mkview` already serves this purpose, no?
