### ISSUE TITLE
[ Feature Request ] Add time to autocmd `CursorHold`

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#21533]
### Feature already in Vim?

NO

### Feature description

the `CursorHold` autocmd's triggered time is controlled by `updatetime` globally, maybe is great to add a new option `time` to set the `CursorHold` trigger time separately.

```
api.nvim_create_autocmd("CursorHold", {
    time = 100,
    callback = function ()
        ...
    end
})

api.nvim_create_autocmd("CursorHold", {
    time = 200,
    callback = function ()
        ...
    end
})
...
```

**Comment by ii14** [comment]
This would require changing how autocommands work.
I think you can do that by using timers and `vim.on_key`.

**Comment by justinmk** [comment]
I do think it makes sense to enhance `CursorHold` to include the elapsed time as a "pattern". Or introduce a new `Idle` event. Something that allows subscribers to decide which intervals they want to listen to. (timer_start() isn't sufficient here because it doesn't detect "idle".)

**Comment by ii14** [comment]
```lua
local TIMEOUT = 500
local n = 0
local timer = vim.loop.new_timer()
vim.on_key(function()
  timer:start(TIMEOUT, 0, function()
    n = n + 1
    print(n)
  end)
end)
```

**Comment by justinmk** [comment]
@ii14 nice hack (could be worth mentioning at `:help on_key`) but an Idle event would be much more efficient (only triggers on actual idle "edge" instead of checking every key event)

**Comment by lewis6991** [comment]
How else do you think `CursorHold` is implemented in core?

**Comment by justinmk** [comment]
I don't think it's required for CursorHold to be implemented like that in core. We can control when the loop wakes up.
