### ISSUE TITLE
LSP: Consider changing gravity for semantic extmarks

### ISSUE THREAD

**Issue by yioneko** [neovim/neovim#21543]
### Feature already in Vim?

No

### Related

https://github.com/neovim/neovim/blob/738427d4984f13ce5e7cda9cda2face9559ee7e7/runtime/lua/vim/lsp/semantic_tokens.lua#L407-L412

### Expected changes

```diff
diff --git a/semantic_tokens.lua b/semantic_tokens.lua
index 48190b0..fefb976 100644
--- a/semantic_tokens.lua
+++ b/semantic_tokens.lua
@@ -408,6 +408,8 @@ function STHighlighter:on_win(topline, botline)
             hl_group = '@' .. token.type,
             end_col = token.end_col,
             priority = vim.highlight.priorities.semantic_tokens,
+            right_gravity = false,
+            end_right_gravity = true,
             strict = false,
           })
```

### Comparison

<img src="https://user-images.githubusercontent.com/65551246/209560502-600a853e-2fdc-49b2-b913-ec02a8353ccc.gif"  width="400" /> <img src="https://user-images.githubusercontent.com/65551246/209560509-1a2c8a16-d925-4c7b-a524-daef4ba66657.gif" width="400" />

I'm not sure if there is any extra concerns to not change it on the initial implementation, but the changes seem more reasonable to me.

**Comment by jdrouhard** [comment]
There was no specific reason, and I agree that this is definitely better than what I did originally. I can throw up a PR sometime this week unless you want to make one?

**Comment by yioneko** [comment]
Thanks, glad to hear that this is possible. Feel free to create pr for it, and I believe you are better at taking on it.
