### ISSUE TITLE
Cursor doesnt change modes / shape in GNU Screen

### ISSUE THREAD

**Issue by mknurs** [neovim/neovim#21544]
### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

no, vim 9.0.0813

### Operating system/version

Debian 6.0.12-1

### Terminal name/version

foot 1.13.1

### $TERM environment variable

xterm-256color

### Installation

.deb from repo

### How to reproduce the issue

```
$ screen
$ nvim --clean
```

### Expected behavior

I expect the cursor to change between modes (vertical bar vs block) like it does when nvim is not run in GNU Screen.

### Actual behavior

The cursor doesn't change between modes.

**Comment by justinmk** [comment]
can you check if https://github.com/neovim/neovim/wiki/FAQ gives any hints here

**Comment by mknurs** [comment]
Thanks. The document is pretty sparse on GNU Screen and goes more in detail for Tmux, which works fine for me (except I don't use Tmux).

I was thinking it might be possible that screen doesn't know about Ss and Se terminfo definitions. I'm not sure how to go about confirming that.

**Comment by justinmk** [comment]
wouldn't be surprised. Only reason I didn't immediately close this is because your description made me think that you had witnessed this working in screen.

**Comment by mknurs** [comment]
Well I use different cursor shapes for vi modes in the terminal and it works for screen. My inputrc:
```inputrc
set vi-ins-mode-string \1\eP\e[6 q\e\\\2
set vi-cmd-mode-string \1\eP\e[2 q\e\\\2
```

The linked answer fixes the vim cursor in screen with t_XX options which nvim doesn't use:
"Nvim does not have special `t_XX` options nor <t_XX> keycodes to configure terminal capabilities. Instead Nvim treats the terminal as any other UI, e.g. 'guicursor' sets the terminal cursor style if possible." (from h:t_xx)

As for the Ss and Se capabilities `h:tui-cursor-shape` states that nvim does construct them if they're missing.

I have a vague memory of this working once, and not finding discussions about it makes me think users do manage to fix it somehow. Annoyingly there's plenty of troubleshooting tips for tmux (even it's own h tag `h:tui-cursor-tmux`) which works for me out of the box.

**Comment by mknurs** [comment]
Seems to be fixed with an update.

Works as expected with:\
NVIM v0.8.2\
Screen version 4.09.00 (GNU) 30-Jan-22
