### ISSUE TITLE
cmdheight=0 works weirdly with `resize`

### ISSUE THREAD

**Issue by lucario387** [neovim/neovim#21558]
### Neovim version (nvim -v)

v0.9.0-dev-565+gd215dae0e

### Vim (not Nvim) behaves the same?

no

### Operating system/version

linux 6.1.1

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

Build from source

### How to reproduce the issue

nvim --clean
:set cmdheight=0
:resize -1
:resize +1

### Expected behavior

As it's still experimental, I don't know what should the expected behavior be
For me, it's that cmdheight should stay as 0, or to be back to 0 after resize +1

### Actual behavior

cmdheight is now back to 1, and have to be reset to 0

**Comment by lucario387** [comment]
Additional Context: `:redraw` after the sequence above does make cmdheight=0 works again

**Comment by lucario387** [comment]
Additional context, leaving vim through C-z or jumping to a new kitty window -> return to vim does reset cmdheight back to 0.

So maybe not cmdheight not being 0, but rather resize cannot go above (number of rows - 1)

**Comment by luukvbaal** [comment]
I think the question is if `:resize -1` should resize the command window from 1 to 0. If so, the following patch should resolve this issue:
```diff
@@ -5760,9 +5760,8 @@ static void frame_setheight(frame_T *curfrp, int height)
     // topframe: can only change the command line height
     if (height > ROWS_AVAIL) {
       // If height is greater than the available space, try to create space for
-      // the frame by reducing 'cmdheight' if possible, while making sure
-      // `cmdheight` doesn't go below 1.
-      height = (int)MIN((p_ch > 0 ? ROWS_AVAIL + (p_ch - 1) : ROWS_AVAIL), height);
+      // the frame by reducing 'cmdheight' if possible.
+      height = (int)MIN(ROWS_AVAIL + p_ch, height);
     }
     if (height > 0) {
       frame_new_height(curfrp, height, false, false);

```

Or perhaps it should only work like that if `'cmdheight'` was ever actually set to 0 in user config?

**Comment by zeertzjq** [comment]
Maybe use this one in `frame_setheight()` as well:
https://github.com/neovim/neovim/blob/05b6dd6e5f543083ebca581506398a8c263a2db6/src/nvim/window.c#L6093-L6099
