### ISSUE TITLE
Will a PR to add consistency to optional annotations welcome?

### ISSUE THREAD

**Issue by danielo515** [neovim/neovim#21556]
### Feature already in Vim?

NO

### Feature description

Hello.
I noticed that optional annotations are a bit inconsistent across the Lua code.
I found all the following ways of expressing optionals:

```
@param bufnr (optional, number): Buffer handle, or 0 for current
@param opts nil|table Optional keyword arguments:
@param opts (nil|table) keyword arguments:
@param [context] (table) Context for the request
@param query (string, optional)
```

I think the most simple to use, understand and parse is 

```
@param [context] (table) Context for the request
```

Will you be open to a PR that changes those annotations to follow the same format?

**Comment by clason** [comment]
Thank you, but no. The format needs to be parseable (in this order!) by
1. our `gen_vimdoc.py` script (or whatever will replace it down the road)
2. `lua-language-server`

Consistency is nice, but probably not worth the churn -- unless in the context of a PR that fixes actual problems (wrong or incomplete) parsing; those would indeed be welcome.

**Comment by danielo515** [comment]
> Thank you, but no. The format needs to be parseable (in this order!) by
> 
> 1. our `gen_vimdoc.py` script (or whatever will replace it down the road)
> 2. `lua-language-server`
> 
> Consistency is nice, but probably not worth the churn -- unless in the context of a PR that fixes actual problems (wrong or incomplete) parsing; those would indeed be welcome.

Maybe I was not clear, but I am not proposing to use a new/different format. I am proposing to pick one of the three styles that are already used in the code and stick with it. Or is there any feature that requires this different ways of expressing optional parametrers?

I was just suggesting one, but as long as they all look the same I think it will be better.
Or I misunderstood something?

**Comment by clason** [comment]
> I was just suggesting one, but as long as they all look the same I think it will be better.
Or I misunderstood something?

My point is "looks better" is not sufficient reason for changing nearly all of the Lua files. Are there any files where optional arguments are not correctly marked in the documentation?

**Comment by danielo515** [comment]
> My point is "looks better" is not sufficient reason

It is not about it looking better. It is about consistency and easier parsing. This last argument may be valuable given neovim uses a script to parse the lua files to generate the docs (is that correct? Is that the order? `Lua -> docs`?). Having a single format will reduce the complexity of any script parsing those comments, and picking one of the formats that are already used are not going to break it anyway.

So does the gen_vimdoc.py script and lua-language-server correctly parse all the different styles I reported? If that is the case and you are not willing to accept such change, then it is probably nothing more to discuss.

**Comment by clason** [comment]
> It is not about it looking better. It is about consistency and easier parsing. 

Yes, and I'm asking whether there are any instances where this is the case -- those should be fixed and would be a welcome PR. Consistency is nice but not as important, and IMO not worth the cost of such a big "refactor" PR.

**Comment by danielo515** [comment]
This is an extract from the docs, about buf_notify and buf_request_all:

```
buf_notify({bufnr}, {method}, {params})                 *vim.lsp.buf_notify()*
    Send a notification to a server

    Parameters:  
      • {bufnr}   [number] (optional): The number of the buffer
      • {method}  [string]: Name of the request method
      • {params}  [string]: Arguments to send to the server

    Return:  
        true if any client returns true; false otherwise

                                                   *vim.lsp.buf_request_all()*
buf_request_all({bufnr}, {method}, {params}, {callback})
    Sends an async request for all active clients attached to the buffer.
    Executes the callback on the combined result. Parameters are the same as
    |vim.lsp.buf_request()| but the return result and callback are different.

    Parameters:  
      • {bufnr}     (number) Buffer handle, or 0 for current.
      • {method}    (string) LSP method name
      • {params}    (optional, table) Parameters to send to the server
      • {callback}  (function) The callback to call when all requests are
                    finished.
```

Why in the same docs, one type is expressed as `[number]` and the same type is also expressed as `(number)` ? also, seems that `[number]` is not interpreted as optional, which according to luaDoc convention brackets express the argument is optional.

**Comment by teto** [comment]
also [number] looks like a list of numbers. I dont know the emmylua spec but consistency would be welcome. But maybe discuss the method beforehand. Would that be a linter ?

**Comment by danielo515** [comment]
> also [number] looks like a list of numbers. I dont know the emmylua spec but consistency would be welcome. But maybe discuss the method beforehand. Would that be a linter ?

Hello @teto . I was thinking more about plain old manual edit to make them look similar. I am not sure there is a linter for luadoc/emmylua comments. Maybe sumneko_lua is capable of giving warnings (I think it does)

**Comment by danielo515** [comment]
@folke , since you are probably already doing a lot of effort into parsing the wide variety of syntaxes the NeoVim LuaDoc has, maybe you can comment a bit on this consistency discussion?
I'm not talking about making anything break, I'm suggesting to pick one of the already working ones and stick with that.

**Comment by justinmk** [comment]
Appreciate the effort, but this issue is not yielding anything actionable, so closing.
