### ISSUE TITLE
Diagnostics stop working

### ISSUE THREAD

**Issue by sansharma056** [neovim/neovim#21563]
### Neovim version (nvim -v)

v0.8.1

### Vim (not Nvim) behaves the same?

haven't checked

### Operating system/version

Arch Linux (6.1.1-arch1-1)

### Terminal name/version

Alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

Official Arch Repository via pacman

### How to reproduce the issue

1) Use the nvim-lua/kickstart.nvim as your init.lua
2) Open any file where there is an LSP attached to the buffer.
3) Remove any character to cause a syntax error. Now, there should be diagnostic virtual text and signs.
4) Go to insert mode but don't enter any character and leave.
5) Diagnostic messages previously visible are now gone.

### Expected behavior

Diagnostic messages should stay.

### Actual behavior

Diagnostic messages previously visible are gone after the steps written above.

https://user-images.githubusercontent.com/41210361/209759735-5b9cfd3d-55a0-476a-b92c-b979194c336a.mp4

**Comment by glepnir** [comment]
can't reproduce with  min config  in nvim0.8.1 and head version 

![images](https://user-images.githubusercontent.com/41671631/209760710-a1f37c56-13fb-4385-8e4b-d6bbc55edf40.gif)

**Comment by sansharma056** [comment]
Just checked this again, this bug happens mainly when I exit insert mode using <C-c> instead of <Esc>.

**Comment by glepnir** [comment]
because the `CTRL C`   not trigger the `InsertLeave`  event.

**Comment by sansharma056** [comment]
Oh, I guess then not much can be done about this. Thanks! I'll just bind `<C-c> `to `<Esc>` :-(

**Comment by glepnir** [comment]
close then.
