### ISSUE TITLE
`nvim_list_runtime_paths` should be allowed during fast events

### ISSUE THREAD

**Issue by folke** [neovim/neovim#21578]
### Feature already in Vim?

no

### Feature description

`nvim_list_runtime_paths` should be allowed during fast events just like `nvim__get_runtime`.

Would be great if this could be added.

**Comment by glepnir** [comment]
the `nvim_list_runtime_paths` called the `nvim_get_runtime_file` . the `nvim_get_runtime_files` is `api-fast` so I think you can just use `nvim_get_runtime_file`.

**Comment by folke** [comment]
@glepnir that's what I use now indeed, but it still would make sense to have `nvim_list_runtime_paths` to be api-fast as well

**Comment by bfredl** [comment]
or maybe we should deprecate just `nvim_list_runtime_paths()` . using `nvim_get_runtime_file("", true)` is longer, but it immediately suggests the possibility of querying a subset as well.

**Comment by folke** [comment]
that works too
