### ISSUE TITLE
`vim.fn.getline` function's `lnum` parameter is typed as a `number` when it should be `number|string` (or something equivalent)

### ISSUE THREAD

**Issue by macintacos** [neovim/neovim#21575]
### Neovim version (nvim -v)

v0.8.1

### Vim (not Nvim) behaves the same?

Vim doesn't use the Lua API

### Operating system/version

macOS 12.6.2

### Terminal name/version

iTerm2

### $TERM environment variable

3.5.0beta8

### Installation

Homebrew

### How to reproduce the issue

- Install neodev and set up neovim for plugin development such that sumneko_lua linters are linting your lua files
- When calling `vim.fn.getline(".")`, note that you get a linter error telling you that the function only accepts `number`.
- Read the documentation. Documentation says:

```
-- When {lnum} is a String that doesn't start with a
-- digit, |line()| is called to translate the String into a Number.
-- To get the line under the cursor: 
-- ```vim
--   getline(".")
-- ```
```

- From this, I infer that passing the string `"."` should be valid, but the linter does not agree (because it is referencing the documentation).

Please update the docstrings such that `string` is an accepted value (or, better yet, create an alias that allows for any number and then a string whose value can only be `"."`)

### Expected behavior

Linter would accept `"."` as a valid value for `getline()`

### Actual behavior

Linter shows a warning saying that the type doesn't match what is stated in the documentation.

**Comment by seandewar** [comment]
We don't control how neodev obtains that info from the help for its annotations.
See also: https://github.com/folke/neodev.nvim/issues/90

**Comment by macintacos** [comment]
Ah, thanks for the pointer!
