### ISSUE TITLE
[ Feature Request ] Add `cpreview` for quickfix window

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#21579]
### Feature already in Vim?

NO

### Feature description

we can only use `cnext` `cprevious` navigate the quickfix window but can't remain our cursor in the quickfix window and preview the result quickfix result, so adding `cpreview` might be a good idea :raised_hands:

**Comment by ii14** [comment]
Preview how? Like this?: `autocmd FileType qf nnoremap <CR> <CR><C-W>p`

**Comment by ii14** [comment]
Well, the cursor moved. Is that a problem?

**Comment by lewis6991** [comment]
Use something like https://github.com/folke/trouble.nvim instead, which has more features and flexibility than quickfix.

We shouldn't be adding more features to quickfix when there are plugins which do the job much better.
