### ISSUE TITLE
nil semanticTokensProvider causes error when opening multiple source code files if language server was configured with nvim-lspconfig

### ISSUE THREAD

**Issue by Xevnar** [neovim/neovim#21588]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-577+g587fbdd7a

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux 6.1.1-arch1-1

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

Arch User Repository (AUR)

### How to reproduce the issue

Minimal `init.lua`:

```lua
vim.cmd [[packadd packer.nvim]]

require('packer').startup(function(use)
	-- Packer can manage itself
	use 'wbthomason/packer.nvim'

	-- Language Server Configs
	use 'neovim/nvim-lspconfig',
end)
```

Create an `after/ftplugin/lua.lua` file:

```lua
-- Launch language server
require('lspconfig').sumneko_lua.setup {
	settings = {
		Lua = {
			runtime = {
				-- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
				version = 'LuaJIT',
			},
			diagnostics = {
				-- Get the language server to recognize the `vim` global
				globals = {'vim'},
			},
			workspace = {
				-- Make the server aware of Neovim runtime files
				library = vim.api.nvim_get_runtime_file("", true),

				-- Avoid using "Environment Emulation"
				-- @see https://github.com/sumneko/lua-language-server/wiki/Libraries#environment-emulation
				-- @see https://github.com/sumneko/lua-language-server/discussions/1688
				checkThirdParty = false,
			},
			-- Do not send telemetry data containing a randomized but unique identifier
			telemetry = {
				enable = false,
			},
		},
	},

	-- Setup completion engine
	capabilities = vim.lsp.protocol.make_client_capabilities(),

	on_attach = function(client, bufnr)
		client.server_capabilities.semanticTokensProvider = nil
	end,
}

-- Call wrapper since lspstart occurs before sourcing ftplugin??
require('lspconfig').sumneko_lua.manager.try_add_wrapper()
```

Step to get error:

1. nvim
2. :edit test_1.lua
3. :vsplit
4. :edit test_2.lua

### Expected behavior

The following error won't show up every time type in insert mode:

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:253: attempt to index field 'semanticTokensProvider' (a nil value)
stack traceback:
        /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:253: in function 'send_request'
        /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:481: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Actual behavior

https://user-images.githubusercontent.com/65031601/209977699-d7984754-7f8c-4533-b127-a9453f0530c5.mp4

**Comment by glepnir** [comment]
I think you should not config it in `after/ftplugin` folder.

**Comment by Xevnar** [comment]
Why not? I would rather keep the configuration of each language server to it's respective filetype.

Also I forgot to mention that issues occurs in both `ftplugin` and `after/ftplugin`, and that it only shows up if you start editing another file.

**Comment by glepnir** [comment]
server start is async. server need time to do initial and clients and servers need to exchange capabilities and time. you pushed them into after/ftplugin folder it load  fast ?  and what i test is your way will make server exit.  `test_1.lua` spawn server with id 1 , `vs test_2.lua` will make id 1 exit and spawn a new one . the new one not have this provider then you got this error.  so i don't advice pushed them into this folder .   in `lua folder ` is fine.

**Comment by ofirgall** [comment]
The same issue happens to me, I config the server not in `after/ftplugin` folder.

**Comment by glepnir** [comment]
@ofirgall the same reproduce step ?

**Comment by ofirgall** [comment]
@glepnir Yes, it doesn't occurs everytime, I don't know what affects it.
Did you set `client.server_capabilities.semanticTokensProvider = nil` in `on_attach`?

**Comment by glepnir** [comment]
I used it and works fine .

**Comment by apazzolini** [comment]
This also happens for me when I set `client.server_capabilities.semanticTokensProvider = nil` in `on_attach`. I'm using the latest nvim-lspconfig and have it set up not in `after`, but in the same way Lazyvim does it.

Setting `semanticTokensProvider` to `nil` is the recommended way of disabling it according to the Neovim docs, but it looks like `STHighlighter:send_request()` still sends a request to the LSP server even if the provider is disabled.

**Comment by jamestrew** [comment]
I'm experiencing the same issue albeit through a different mechanism https://github.com/sindrets/diffview.nvim/issues/304.

`diffview.nvim` author thinks this is an upstream issue related to either Neovim or the language server. After which I stepped through my "Steps to reproduce" using `tsserver` instead of `lua_ls` (formerly `sumneko`) and viewing the diff for a typescript file and the issue does not occur. This leads me to believe that this issue is related to the language server.

**Comment by megalithic** [comment]
> This also happens for me when I set `client.server_capabilities.semanticTokensProvider = nil` in `on_attach`. I'm using the latest nvim-lspconfig and have it set up not in `after`, but in the same way Lazyvim does it.
> 
> Setting `semanticTokensProvider` to `nil` is the recommended way of disabling it according to the Neovim docs, but it looks like `STHighlighter:send_request()` still sends a request to the LSP server even if the provider is disabled.


Can confirm, this is the issue I'm having as well. Not using LazyVim, but am disabling semanticTokensProvider in the exact same way as @apazzolini.

**Comment by monkoose** [comment]
Can confirm that setting `client.server_capabilities.semanticTokensProvider = nil` cause the error
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:98: attempt to index field 'semanticTokensProvider'
(a nil value)
stack traceback:
        /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:98: in function 'tokens_to_ranges'
        /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:355: in function 'process_response'
        /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:283: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1399: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by 3N4N** [comment]
> I think you should not config it in `after/ftplugin` folder.

I set it in `~/.config/nvim/lua/user/lspconfig.lua`.  Still getting the same error.  Is there any hacky way to disable semantic provider for _all_ ftp?  I need to do some work and the colors are making my eyes water.

**Comment by clason** [comment]
Does anyone have a minimal reproducing example _without_ plugins, i.e., just using `vim.lsp.start()` in a `FileType` autocommand? That would raise priority by making clear it's a Neovim issue and not an nvim-lspconfig (or user config) issue.

**Comment by bfredl** [comment]
nvim-lspconfig adds extra delays to the execution of the user's on_attach:
```
      -- Save the old _on_attach so that we can reference it via the BufEnter.
      new_config._on_attach = new_config.on_attach
      new_config.on_attach = vim.schedule_wrap(function(client, bufnr)
        if bufnr == api.nvim_get_current_buf() then
          M._setup_buffer(client.id, bufnr) -- calls new_config._on_attach
        else
```

This breaks the indented initialization pattern in nvim which assumes the user can run code in `on_attach` right away, not delayed via one or possibly multiple layers of `vim.schedule` or similar.

**Comment by jamestrew** [comment]
Is anybody able to reliably replicate this bug using only `nvim-lspconfig`? If so, please share the steps to reproduce the issue. I can try to reproduce it and I offer to create a bug report for `nvim-lspconfig`.

**Comment by apazzolini** [comment]
> Is anybody able to reliably replicate this bug using only `nvim-lspconfig`? If so, please share the steps to reproduce the issue. I can try to reproduce it and I offer to create a bug report for `nvim-lspconfig`.

I can reliably reproduce this by opening two files in the same TS project in vertical splits and then running `LspStop`, waiting a second, and running `LspStart`. A few seconds after the start command, I'll see the `semanticTokensProvider` error.

**Comment by jamestrew** [comment]
If people can, please follow the issue I created and try out the steps to reproduce. Over two different days, I've had differing experiences. It would be great if people can chime in on whether my steps reliably throws the error.

**Comment by davidecavaliere** [comment]
> Closing as this is a nvim-lspconfig issue and tracked there.

for everyone's future reference this seems to be the link @clason is refering to https://github.com/neovim/nvim-lspconfig/issues/2542
