### ISSUE TITLE
Error opening LaTeX files with precompiled headers.

### ISSUE THREAD

**Issue by gi1242** [neovim/neovim#21594]
### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

no (problem with detect.lua)

### Operating system/version

Arch 6.1.1-arch1-1

### Terminal name/version

Konsole 22.12.0

### $TERM environment variable

xterm-256color

### Installation

pacman (system package manager)

### How to reproduce the issue

Open any latex file that uses pre-compiled headers. The first line of this file will be

    %& preamble

### Expected behavior

File should be opened, and detected as Latex

### Actual behavior

The filetype is not detected, and you get a few error messages from the runtime file `filetype/detect.lua`. (I fixed the problem and am pasting the fix below, so I can't reproduce the error messages, sorry.)

The fix is to edit `filetype/detect.lua` line 1245 (the function `M.tex`), and change the first few lines to:

    function M.tex(path, bufnr)
      local found, idx, format = getlines(bufnr, 1):find('^%%&%s*(%a+)')
      if found then
        format = format:lower():gsub('pdf', '', 1)
        if format == 'plaintex' then
          return 'plaintex'
        else
          return 'tex'
        end
      elseif ... (everything else is unchanged)

Note, in addition to fixing the runtime error messages, it changed the detection logic. `%&plaintex` files get treated as plaintex, and everything else gets treated as LaTeX. This includes `%&tex`, and those with pre-compiled  headers.

**Comment by clason** [comment]
Please raise this issue at vim/vim, since we take the filetype detection logic unchanged from there! If Vim changes it, we'll port the change as a matter of course.

**Comment by gi1242** [comment]
I'll raise the logic change with vim/vim. But your current implementation of the vim logic itself is wrong. If the `find` succeeds, `format` is `1`, and not the matched string. So I'd suggest at least changing the first two lines of the function to

      local found, idx, format = getlines(bufnr, 1):find('^%%&%s*(%a+)')
      if found then

This way you won't get a bunch of error messages when opening such files.

**Comment by clason** [comment]
A PR to fix the current implementation would be welcome!

**Comment by gi1242** [comment]
I just double checked: Vim 9 does the right thing on such files, and opens them as LaTeX. I read the logic of the vim detection, and it's correct. The neovim implementation is wrong. I can submit a PR.

**Comment by clason** [comment]
Great, thanks for checking!

**Comment by gi1242** [comment]
Created a pull request (I think... it said "Merging blocked", but the code is in the above commit).

**Comment by clason** [comment]
That's fine, thank you!
