### ISSUE TITLE
TUI: Terminal cursor blinks after exiting neovim 

### ISSUE THREAD

**Issue by RobbieClarken** [neovim/neovim#21609]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-590+g6ba34e21f

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.5.1

### Terminal name/version

iTerm2 3.4.12

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

1. Have terminal cursor configured to be a solid block (this is the default in macOS Terminal):

    <img width="122" alt="Screen Shot 2023-01-01 at 7 27 08 pm" src="https://user-images.githubusercontent.com/663161/210165680-e5d0fc5b-b90f-4d84-ba2e-c8e695eadbea.png">

2. Install latest neovim from master branch.
3. Open and close vim:

    ```
    nvim --clean
    :q
    ```

The terminal cursor will now be blinking whereas it should be solid:

https://user-images.githubusercontent.com/663161/210165890-3e9003ae-5b48-4d7b-8729-ff517baa8695.mp4

A git bisect indicates this bug was introduced in one of these two commits:

- 24488169564c39a506c235bf6a33b8e23a8cb528
- 43e8ec92de9e0850e7d202cb7ff9051bc408447e

I was unable to compile 24488169564c39a506c235bf6a33b8e23a8cb528.

I can replicate this in iTerm2 3.4.12 and Terminal 2.12.7.

### Expected behavior

The terminal cursor should remain the solid (not blinking) block.

### Actual behavior

The terminal cursor changed to be blinking.

**Comment by ouuan** [comment]
I want to add one point: I use `au VimLeave * set guicursor=a:ver1` to restore to vertical bar cursor style after leaving neovim, but now after exiting neovim the cursor is blinking block. My terminal is konsole 22.08.3.

**Comment by zeertzjq** [comment]
Hmm, this change seems to solve this problem:
```diff
diff --git a/src/nvim/main.c b/src/nvim/main.c
index c20be202e..2082d7e2f 100644
--- a/src/nvim/main.c
+++ b/src/nvim/main.c
@@ -627,8 +627,8 @@ void os_exit(int r)
 {
   exiting = true;
 
-  ui_flush();
   ui_call_stop();
+  ui_flush();
   ml_close_all(true);           // remove all memfiles
 
   if (!event_teardown() && r == 0) {
```

Not sure if this is safe.

**Comment by zeertzjq** [comment]
I tested #21625 and it seems to make the behavior the same as v0.8.2 in Konsole. Can anyone check if #21625 fixes the problem for iTerm2?

**Comment by SanchayanMaity** [comment]
> I tested #21625 and it seems to make the behavior the same as v0.8.2 in Konsole. Can anyone check if #21625 fixes the problem for iTerm2?

Was facing this same problem and this does seem to fix the problem. My test is with the `foot` terminal on Arch Linux.

**Comment by RobbieClarken** [comment]
> Can anyone check if https://github.com/neovim/neovim/pull/21625 fixes the problem for iTerm2?

I can confirm #21625 fixes the problem for iTerm2 and Terminal on mac.

**Comment by ObserverOfTime** [comment]
> I tested https://github.com/neovim/neovim/pull/21625 and it seems to make the behavior the same as v0.8.2 in Konsole.

It's *almost* the same, though possibly more correct.

My terminal cursor is a blinking underline and I was using this to restore it on exit:
```vim
au VimLeave * set guicursor=a:hor25
```
It broke with #18375 and #21625 fixes it, but I had to change that to get the blinking back:
```vim
au VimLeave * set guicursor=a:hor25-blinkon500
```

**Comment by syyyr** [comment]
I can confirm that #21625 fixes the issue for me with Terminator on Arch Linux.
