### ISSUE TITLE
Normal map to delete all paragraph, i.e. `dap`, causes segment fault.

### ISSUE THREAD

**Issue by nyngwang** [neovim/neovim#21613]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-592+gc4942880b

### Vim (not Nvim) behaves the same?

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec  1 2022 04:24:46)

### Operating system/version

macOS 13.2(a)

### Terminal name/version

alacritty 0.11.0 (8dbaa0b)

### $TERM environment variable

alacritty

### Installation

build from repo

### How to reproduce the issue

open any text file with `{ ... }`, and call normal map `dap`. Indeed `da{`, `da}` all have the same issue.

### Expected behavior

delete entire paragraph under cursor

### Actual behavior

close the neovim itself with a segment fault.

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by nyngwang** [comment]
@zeertzjq Thanks for your help. I can confirm that the error disappears after I removed nvim-treesitter.
