### ISSUE TITLE
Ability to find and switch tabs with partial name search like searching buffer with :b 

### ISSUE THREAD

**Issue by fc-asad** [neovim/neovim#21627]
### Feature already in Vim?

No

### Feature description

In both neovim (and vim), we can quickly find and switch to a loaded buffer by typing `:b <partial_name_of_the_buffer>`
It would be nice to have a similar feature for tabs as well, such that one can find and switch to a loaded tab by its partial name

**Comment by lewis6991** [comment]
Tabs don't have names though?

**Comment by zeertzjq** [comment]
You can achieve this by using `:sbuffer` with `:set switchbuf+=useopen,usetab`

**Comment by fc-asad** [comment]
Wow! This worked just as expected and went right into my init file. Thanks!
