### ISSUE TITLE
Segfault msg_ext_chunks holds invalid ptr

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#21638]
### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux

### Terminal name/version

nvim-qt

### $TERM environment variable

N/A

### Installation

from source

### How to reproduce the issue

Originally reported in https://github.com/equalsraf/neovim-qt/issues/1043 I was unable to produce a minimal example that triggers the same behavior. Also I could not reproduce without the UI attached.

I am including the original report from @przepompownia (but see actual behavior for a traceback and some investigation):

----
Having 
- fresh nvim-qt on 2b4cb87 
- fresh neovim on neovim/neovim@39ea662824f6b6e7ff1eaee5e2a169ffe535a244 with binary on `~/tmp/nvim-from-src/bin/nvim`
- fresh Noice minimal config https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue saved in `~/tmp/noice-min.lua` 

I run 
```sh
nvim-qt --nvim ~/tmp/nvim-from-src/bin/nvim -- -u ~/tmp/noice-min.lua
```
and then (after finishing possible installation and closing the installer window)
```vim
lua require("noice").redirect("hi")
```
and get regular crash like on the screencast below (it also shows no error on TUI):

https://user-images.githubusercontent.com/11404453/209232781-1dffa2f8-c8e7-4e2a-8cb9-5c4b41b5c6b6.mp4

---

### Expected behavior

No segfault

### Actual behavior

nvim is crashing (both in master and in 0.8.1 in Linux)

```gdb
Program received signal SIGSEGV, Segmentation fault.
0x00000000005a94ff in msgpack_rpc_from_object ()
(gdb) bt
#0  0x00000000005a94ff in msgpack_rpc_from_object ()
#1  0x00000000005a9a1c in msgpack_rpc_from_array ()
#2  0x0000000000481981 in push_call ()
#3  0x0000000000483332 in remote_ui_event ()
#4  0x0000000000676be1 in ui_composed_call_event ()
#5  0x000000000067b20e in ui_comp_event ()
#6  0x00000000006764b1 in ui_call_event ()
#7  0x0000000000677db4 in ui_call_msg_show ()
#8  0x000000000059f4f2 in msg_ext_ui_flush ()
#9  0x0000000000678cbc in ui_flush ()
#10 0x000000000051bfd5 in ex_redraw.lto_priv ()
#11 0x0000000000512597 in execute_cmd0 ()
#12 0x0000000000512e22 in execute_cmd ()
#13 0x000000000046a38b in nvim_cmd ()
#14 0x0000000000456477 in nlua_api_nvim_cmd ()
#15 0x00007ffff7cf4a46 in ?? () from /gnu/store/2abfc60wk6wgv7dwrl1kp0bc57drw8g8-luajit-2.1.0-beta3-0.6c4826f/lib/libluajit-5.1.so.2
#16 0x00007ffff7d0920f in lua_pcall () from /gnu/store/2abfc60wk6wgv7dwrl1kp0bc57drw8g8-luajit-2.1.0-beta3-0.6c4826f/lib/libluajit-5.1.so.2
#17 0x000000000056239d in nlua_pcall.lto_priv ()
#18 0x000000000056f7f1 in nlua_typval_exec ()
#19 0x000000000056fb6e in ex_lua ()
#20 0x0000000000512597 in execute_cmd0 ()
#21 0x0000000000515ad8 in do_one_cmd ()
#22 0x00000000005165d2 in do_cmdline ()
#23 0x00000000005b66a2 in nv_colon.lto_priv ()
#24 0x00000000005af6ec in normal_execute.lto_priv ()
#25 0x000000000064a7d7 in state_enter ()
#26 0x00000000005ae282 in normal_enter ()
#27 0x0000000000575c98 in main ()
```

I have more details in https://github.com/equalsraf/neovim-qt/issues/1043#issuecomment-1369077698 but ultimately when this function is called the *content* seems to hold an invalid pointer which later causes the segfault: 

```c
void ui_call_msg_show(String kind, Array content, Boolean replace_last)
{
  Array args = call_buf;
  ADD_C(args, STRING_OBJ(kind));
  ADD_C(args, ARRAY_OBJ(content));
  ADD_C(args, BOOLEAN_OBJ(replace_last));
  UI_LOG(msg_show);
  ui_call_event("msg_show", args);
}
```

The caller is *msg_ext_ui_flush* and the argument is msg_ext_chunks

```c
    ui_call_msg_show(cstr_as_string((char *)msg_ext_kind),
                     msg_ext_chunks, msg_ext_overwrite);
```

I have yet to root cause it any further but it looks like the global variable becomes invalid after being released, e.g. the following patch side steps the crash by leaking the memory (FWIW in my system).

```diff
diff --git a/src/nvim/message.c b/src/nvim/message.c
index 041e5ed6c..11fe0e2f9 100644
--- a/src/nvim/message.c
+++ b/src/nvim/message.c
@@ -3174,7 +3174,7 @@ void msg_ext_ui_flush(void)
       msg_ext_visible++;
     }
     msg_ext_kind = NULL;
-    api_free_array(msg_ext_chunks);
+    //api_free_array(msg_ext_chunks);
     msg_ext_chunks = (Array)ARRAY_DICT_INIT;
     msg_ext_cur_len = 0;
     msg_ext_overwrite = false;
@@ -3188,7 +3188,7 @@ void msg_ext_flush_showmode(void)
   if (ui_has(kUIMessages)) {
     msg_ext_emit_chunk();
     ui_call_msg_showmode(msg_ext_chunks);
-    api_free_array(msg_ext_chunks);
+    //api_free_array(msg_ext_chunks);
     msg_ext_chunks = (Array)ARRAY_DICT_INIT;
     msg_ext_cur_len = 0;
   }
```

neovim-qt does not support *ext_messages*. But the plugin noice does use `vim.ui_attach`

https://github.com/folke/noice.nvim/blob/abb5721129b3f54bb6f38713f45029c61c0e5f64/lua/noice/ui/init.lua#L73

A workaround for the plugin would be this to disable ext_messages:

```lua
require("noice").setup({messages = { enabled = false } })
```

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/issues/21604 could be related

**Comment by equalsraf** [comment]
Ups apologies I missed the previous report. Looks identical - the only difference is that I cannot reproduce using the example in https://github.com/neovim/neovim/issues/21604#issuecomment-1368351584. Closing this, the trace and the double free locations all match.
