### ISSUE TITLE
Strange empty print when `cmdheight=0`

### ISSUE THREAD

**Issue by boltlessengineer** [neovim/neovim#21645]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-1826+g89232b8b4-dirty

### Vim (not Nvim) behaves the same?

vim doesn't have cmdheight option

### Operating system/version

macOS 13.1

### Terminal name/version

wezterm 20221122-154621-68c754b1

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

nvim --clean
:set cmdheight=0
:Lexplore

### Expected behavior

`:Lexplore` should run immediately when user type `<CR>` in cmdline.

### Actual behavior

`:Lexplore` prints empty line before executed.

Edit: forgot adding one reproduce step.

**Comment by nwounkn** [comment]
What causes the issue: https://github.com/neovim/neovim/blob/a8fc94a2fdd07edf0679d34f2deaacb25b3fa69f/runtime/autoload/netrw.vim#L1137-L1137
It seems that its there only to clear cmdline. Commenting it fixes the issue, or `:silent Lexplore` can be used.

**Comment by nwounkn** [comment]
fixed 9455f6b17c6d1009af5d37d62884fe3042abdfa0
