### ISSUE TITLE
g:python3_host_prog is ignored

### ISSUE THREAD

**Issue by jpgeek** [neovim/neovim#21641]
### Neovim version (nvim -v)

NVIM v0.8.2

### Vim (not Nvim) behaves the same?

no.  version 9.0.1100

### Operating system/version

macOS 13.1 

### Terminal name/version

iTerm2 Build 3.4.18, under Tmux and without.

### $TERM environment variable

screen-256color

### Installation

homebrew

### How to reproduce the issue

Install pyenv with pyenv-virtualenv.  Then follow steps under
```
:help python-virtualenv
```

> Example using pyenv:
>    pyenv install 3.4.4
>    pyenv virtualenv 3.4.4 py3nvim
>    pyenv activate py3nvim
>    python3 -m pip install pynvim
>    pyenv which python  # Note the path
> The last command reports the interpreter path, add it to your init.vim:
>    let g:python3_host_prog = '/path/to/py3nvim/bin/python'

Ensure pynvim is NOT installed in the base python, but only in the virtual env.
Run nvim without switching to the virtual env.   Run
`:py3 print('foo')`

It blows up with a no Python3 provider found error.
However, running `:checkhealth provider` indicates python 3 is "OK" and is using the virtual environment specified.

Shut down nvim, 
`pyenv activate neovim3`
and open nvim.  Run:
`:py3 print('foo')`
It prints 'foo' as expected.

### Expected behavior

It should use the python3 provider specified in 
`g:loaded_python3_provider`
regardless of whether it is running under a virtual env or not and (print 'foo' in both scenarios).

### Actual behavior

It (apparently) ignores the `g:loaded_python3_provider` and uses the python3 of the environment it is running under .

**Comment by Shougo** [comment]
Please upload the minimal init.vim.

**Comment by jpgeek** [comment]
Awesome quick reply - thank you @Shougo !
It narrows down to only two lines:

```
syntax on
let g:python3_host_prog = '/my/path/to/virtualenv/bin/python'
```

Interesting that the problem resolves if `syntax on` is commented.
Obviously the second line is specific to the installation.

**Comment by Shougo** [comment]
Well, `syntax on` may load Python.
Please set `g:python3_host_prog` before syntax.

**Comment by jpgeek** [comment]
Outstanding @Shougo !  That worked! Thank you!  You rock!
Do you think this should this be added to `:help pyenv-virtualenv`?  It would have saved me many hours.  I can send a PR if so.

**Comment by clason** [comment]
> syntax on

This should _not_ be used in a Neovim `init.vim`, since syntax is automatically enabled (at the correct time in the startup sequence).

**Comment by jpgeek** [comment]
Thank you  @clason.
