### ISSUE TITLE
Command bar at the top

### ISSUE THREAD

**Issue by costincaraivan** [neovim/neovim#21659]
### Problem

Sublime Text/VS Code & co. have the command bar at the top, and frankly it is a better choice since we read top to bottom, and their dropdown... drops down 🙂

![image](https://user-images.githubusercontent.com/1235856/210803611-6523ee6b-8b85-4e96-bc84-7c7a516539a2.png)

### Expected behavior

Can the command bar in Neovim be moved to the top and the command list shown as a drop down (i.e. listing down, not up)?

**Comment by lewis6991** [comment]
This is not something we plan to add into core, but you can use something like https://github.com/folke/noice.nvim

The goal in core is to decouple the UI from nvim, so custom UI's can be created (via plugins or GUI applications).
