### ISSUE TITLE
Project-manage type editor features

### ISSUE THREAD

**Issue by costincaraivan** [neovim/neovim#21658]
### Problem

Sublime Editor added some core editor features that were not super frequent in editors before, and they are extremely useful, especially for folks not going the tmux + bash + (n)vim setup way.

These are:

- the project explorer
- fast, fuzzy recursive folder content search

### Expected behavior

Will Neovim ever integrate these features in the core distribution?

If not, are there are any "blessed" plugins that are easy to install and use on all supported platforms, **especially** on Windows?

The existing search tools just don't cut it, especially on Windows, their integration is clumsy.

**Comment by lewis6991** [comment]
Please don't raise issues for these kinds of questions. Please see https://neovim.io/community/

There are no immediate plans for either of these.

**Comment by justinmk** [comment]
we have tentative but low-priority ideas for improving file browsing. related:

- https://github.com/neovim/neovim/issues/16142
- https://github.com/neovim/neovim/issues/12620

(and I think some vim patches will bring in "fuzzy" features for vim's completion interface)
