### ISSUE TITLE
Message specifications when saved have changed since #21580

### ISSUE THREAD

**Issue by yutkat** [neovim/neovim#21653]
### Neovim version (nvim -v)

v0.9.0-dev-1827+gae64772a8

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux

### Terminal name/version

wezterm 20230102-155114-67896f67

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

1. use this init.lua

```lua
vim.cmd [[syntax enable]]
vim.cmd [[filetype plugin indent on]]

local install_path = vim.fn.stdpath('data')..'/site/pack/packer/opt/packer.nvim'
if vim.fn.empty(vim.fn.glob(install_path)) == 1 then
  vim.api.nvim_command('!git clone https://github.com/wbthomason/packer.nvim '..install_path)
end
vim.cmd [[packadd packer.nvim]]

local function load_plugins()
  return require('packer').startup(function()
    use {'wbthomason/packer.nvim', opt = true}
    use({
      "folke/noice.nvim",
      config = function()
        require("noice").setup({})
      end,
      requires = {
        "MunifTanjim/nui.nvim",
        "rcarriga/nvim-notify",
      }
    })
  end)
end
load_plugins()
```

2. `:PackerSync` and `:qa`
3. open `nvim aaa.lua`
4. `:w`
5. Normally, the file name of the saved file(aaa.lua) should be displayed, but `<` is displayed.

If this added condition is removed, it will be normal. https://github.com/neovim/neovim/pull/21580/files#diff-93eb182156bc96b7817704f1db2a233ebdaf3d90a93979e8bb9ae1d3f5e8757aR3844

```c
&& p_ch > 0
```

Maybe it is a problem on the plugin side(noice.nvim), if so, I'm sorry.

### Expected behavior

Saved file names are displayed correctly.
![swappy-20230105-174251](https://user-images.githubusercontent.com/8683947/210739038-e4992163-32aa-44ca-a4f0-a1b31cee16b7.png)

### Actual behavior

`<` is displayed
![swappy-20230105-174313](https://user-images.githubusercontent.com/8683947/210739058-258f4260-3915-491a-8520-b89a1152974a.png)

**Comment by bfredl** [comment]
>   https://github.com/neovim/neovim/pull/21580/files#diff-93eb182156bc96b7817704f1db2a233ebdaf3d90a93979e8bb9ae1d3f5e8757aR3844

yep, that one line change is invalid and must be reverted. this breaks the last added test in that commit, which can be fixed by making `resize -1` of single window a no-op when ext_messages (if there is no message area, there is nothing that can be given the space)

**Comment by justinmk** [comment]
@luukvbaal

**Comment by luukvbaal** [comment]
Thanks for the ping, missed this.

> which can be fixed by making resize -1 of single window a no-op when ext_messages

I guess that would work although it still feels like circumventing the problem. I just came across your comment here: https://github.com/neovim/neovim/blob/fc2cd28547954e64ef429c83733f06fa3ee75d50/src/nvim/message.c#L208-L213

That and https://github.com/neovim/neovim/issues/20888#issuecomment-1368127089 seem relevant to actually fixing the underlying issue.

**Comment by bfredl** [comment]
> I guess that would work although it still feels like circumventing the problem.

It needs to be changed regardless. we don't want to support having empty space on the main screen which is owned by anything (and thus will need extra logic to clear it separately in various places)

**Comment by luukvbaal** [comment]
An early return in `msg_may_trunc` also resolves this issue:

```
@@ -921,6 +921,10 @@ char *msg_may_trunc(bool force, char *s)
 {
   int room;

+  if (ui_has(kUIMessages)) {
+    return s;
+  }
+
   room = (Rows - cmdline_row - 1) * Columns + sc_col - 1;
   if ((force || (shortmess(SHM_TRUNC) && !exmode_active))
       && (int)strlen(s) - room > 0) {
```

Is there any reason to truncate the message with external messages? Shouldn't it be up to the external ui provider?
