### ISSUE TITLE
typescript-langauge-sever vim.lsp.buf.incoming_calls() not work

### ISSUE THREAD

**Issue by zhoudaxia2016** [neovim/neovim#21654]
### Neovim version (nvim -v)

NVIM v0.8.0-1210-gd367ed9b2

### Language server name/version

typescript-langauge-sever 3.0.1

### Operating system/version

wsl2

### Steps to reproduce using "nvim -u minimal_init.lua"

1. open a typescript file
2. go to a function's name
3. execute vim.lsp.buf.incoming_calls()

### Expected behavior

no error

### Actual behavior

error:
method textDocument/prepareCallHierarchy is not supported by any of the servers registered for the current buffer

I find that the default client_capabilities is 
```lua
{  callHierarchy = { dynamicRegistration = false }
```
But what I saw at lsp spec is
```typescript
{ textDocument: { callHierarchy: { dynamicRegistration: false }}
```
I think this is the reason for the problem.

**Comment by justinmk** [comment]
> But what I saw at lsp spec is
> 
> ```ts
> { textDocument: { callHierarchy: { dynamicRegistration: false }}
> ```

thanks for noting that. can you send a PR? cc @mfussenegger
