### ISSUE TITLE
Coding issues in src/nvim/os/job.c can lead to assertion at uv_close() 

### ISSUE THREAD

**Issue by hi3766691** [neovim/neovim#2165]
--- job.2.c	2015-03-16 13:44:27.895378388 +0000
+++ ../src/nvim/os/job.c	2015-03-16 13:34:07.150378092 +0000
@@ -135,13 +135,13 @@ Job *job_start(JobOptions opts, int *sta
   // Spawn the job
   if (!process_spawn(job)) {
     if (opts.writable) {
-      uv_close((uv_handle_t *)&job->proc_stdin, close_cb);
+      uv_close((uv_handle_t *)job->proc_stdin, close_cb);
     }
     if (opts.stdout_cb) {
-      uv_close((uv_handle_t *)&job->proc_stdout, close_cb);
+      uv_close((uv_handle_t *)job->proc_stdout, close_cb);
     }
     if (opts.stderr_cb) {
-      uv_close((uv_handle_t *)&job->proc_stderr, close_cb);
+      uv_close((uv_handle_t *)job->proc_stderr, close_cb);
     }
     process_close(job);
     event_poll(0);

**Comment by tarruda** [comment]
@oni-link sent a patch for this but I havent merged yet. Can you open a pull request?
