### ISSUE TITLE
Focus change events support is not reported correctly

### ISSUE THREAD

**Issue by EtiamNullam** [neovim/neovim#21655]
### Describe the bug

Checking for `FocusGained` and `FocusLost` with `vim.fn.exists('##FocusGained')` and `vim.fn.exists('##FocusLost')` always returns `1`, even for terminals which do not support them.

### Steps to reproduce

```vim
nvim --clean
:lua=vim.fn.exists('##FocusGained') 
:lua=vim.fn.exists('##FocusLost')
```

### Expected behavior

Should return `0` if focus change events are not supported.

### Neovim version (nvim -v)

v0.9.0-dev-590+g6ba34e21f

### Vim (not Nvim) behaves the same?

no, vim always supports focus change events

### Operating system/version

Windows 10

### Terminal name/version

cmd, Cmder

### $TERM environment variable

N/A

### Installation

scoop

**Comment by justinmk** [comment]
> Checking for `FocusGained` and `FocusLost` with `vim.fn.exists('##FocusGained')` and `vim.fn.exists('##FocusLost')` always returns `1`, even for terminals which do not support them

has nothing to do with the terminal. exists() is statement of what Vim/Nvim supports. exists() is not "dynamic feature detection". 

there is no reason to check this anyway. the FocusGained/FocusLost events are the interface plugins should use. if they don't work, user needs to live with their choice of terminal.

**Comment by EtiamNullam** [comment]
Thank you for making it clear. I have expected that. sorry for taking your time.
