### ISSUE TITLE
editorconfig issue with end_of_line: auto value

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#21669]
### Describe the bug

On latest nightly, with the new editorconfig built-in (happens with the editorconfig.nvim plugin too), if you use the default EmmyLuaCodeStyle editorconfig from here: https://github.com/CppCXY/EmmyLuaCodeStyle/blob/master/lua.template.editorconfig

You'll see when starting Neovim:

```
editorconfig: invalid value for option end_of_line: auto. end_of_line must be one of "lf", "crlf", or "cr"
```

### Steps to reproduce

1. latest nightly nvim build
2. create .editorconfig with contents from link above
3. nvim --clean

### Expected behavior

Not sure? I don't know who is at fault here, emmy lua or us? Personally, I'd like that we do set end_of_line based on the 'auto' value, so one wouldn't need to change that when in Windows-land.

Hoping @gpanders could weigh in?

### Neovim version (nvim -v)

0.9.0 commit g099643039

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 12.5.1

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

source

**Comment by mfussenegger** [comment]
The specification doesn't mention an `auto` value: https://spec.editorconfig.org/#supported-pairs

**Comment by gpanders** [comment]
As @mfussenegger using `auto` is invalid, as it's not in the specification.

We could have a discussion on what the right behavior for an invalid value is, however (showing an error vs silently ignoring). I'm in favor of the former, but willing to hear arguments for the latter.

**Comment by craigmac** [comment]
Ok, thanks for the clarification, I think it works well enough as is now and should show the error. I've just asked LuaCodeStyle author to make it clearer that copy-and-pasting their default config doesn't work OOTB with Neovim (as it stands right now anyway, maybe they'll fix it). I'll close this.
