### ISSUE TITLE
make visual mode default-mappings less fragile

### ISSUE THREAD

**Issue by planet36** [neovim/neovim#21676]
### Problem

https://github.com/neovim/neovim/pull/18538 introduced visual mode default-mappings for `*` and `#`.
```
xnoremap * y/\V<C-R>"<CR>
xnoremap # y?\V<C-R>"<CR>
```

As mentioned in https://github.com/neovim/neovim/pull/18538#pullrequestreview-971039192 these mappings are fragile.

Special characters (back slash, forward slash, question mark) of the selected text aren't escaped, but they should be.

Mappings like these would be less fragile.
```
xnoremap * y/\V<C-R>=escape(@", '/\')<CR>
xnoremap # y?\V<C-R>=escape(@", '?\')<CR>
```

### Expected behavior

Select text that has `/`, `\`, or `?` in visual mode.
Search for it using the visual mode default-mappings `*` or `#`.
The selected text should be matched.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/21677/files#r1064194424

**Comment by planet36** [comment]
This is better if a newline is in the selection.
```
vim.keymap.set("x", "*", [[y/\V<C-R>=substitute(escape(@", '/\'), '\n', '\\n', 'g')<NL>]])
vim.keymap.set("x", "#", [[y?\V<C-R>=substitute(escape(@", '?\'), '\n', '\\n', 'g')<NL>]])
```
