### ISSUE TITLE
Unable to access system clipboard, Neovim snap v0.8.2

### ISSUE THREAD

**Issue by Konglomneshued** [neovim/neovim#21684]
### Describe the bug

Using the system clipboard does not copy to the + register when using Neovim from snap.

Neither setting it `:set clipboard=unnamedplus` in an instance nor in the init.vim file has any effect.

I have installed Neovim from snap with `sudo snap install nvim` and `sudo snap install nvim --classic` and both yield the same result.

### Steps to reproduce

- Install snapd on Fedora 37
- Navigate to https://snapcraft.io/install/nvim/fedora
- Follow instructions for enabling classic support
- Try installed normally and use the system clipboard
- Try installing classic containment and use the system clipboard

### Expected behavior

Copying to the system clipboard allows me to paste what I yanked somewhere else, like another application.

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Fedora 37

### Terminal name/version

Konsole 22.12.0

### $TERM environment variable

bash: xterm-256color: command not found...

### Installation

snapd

**Comment by zeertzjq** [comment]
Have you installed xsel/xclip/wl-clipboard?

**Comment by Konglomneshued** [comment]
> Have you installed xsel/xclip/wl-clipboard?

Why would I need those?

**Comment by zeertzjq** [comment]
They are required for Nvim to access system clipboard.

**Comment by Konglomneshued** [comment]
> They are required for Nvim to access system clipboard.

Why does the snap package not come with them?

Do I need all of them or just one?

**Comment by zeertzjq** [comment]
You need one of xsel or xclip if you are using X11, wl-clipboard if you are using Wayland.

**Comment by justinmk** [comment]
:help clipboard
