### ISSUE TITLE
Autocmd event `TextChangedT` not recognized by `vim.api.nvim_create_autocmd()`

### ISSUE THREAD

**Issue by starptr** [neovim/neovim#21685]
### Describe the bug

Calling `vim.api.nvim_create_autocmd()` with the `TextChangedT` event results in an E5113 error saying "unexpected event".

### Steps to reproduce

Run
```
vim.api.nvim_create_autocmd("TextChangedT", {
  group = vim.api.nvim_create_augroup('foogroup', { clear = true }),
  callback = function()
  end,
})
```

### Expected behavior

The error should not occur

### Neovim version (nvim -v)

v0.8.2 Release

### Vim (not Nvim) behaves the same?

NA (this is a lua issue)

### Operating system/version

macOS 13.1

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

homebrew

**Comment by zeertzjq** [comment]
The autocommand is not present in v0.8.2

**Comment by starptr** [comment]
Can you clarify? The event `TextChangedI` works; why is `TextChangedT` specifically missing?

**Comment by zeertzjq** [comment]
This help page is for nightly version, not v0.8.2.

**Comment by starptr** [comment]
Oh I see, thanks for clarifying!
