### ISSUE TITLE
`confirm` prompt is not helpful when working with dirty unnamed buffers and `nohidden`

### ISSUE THREAD

**Issue by andrewferrier** [neovim/neovim#21682]
### Describe the bug

The 'confirm' prompt is not useful / misleading when working with unnamed buffers and `nohidden`. In these circumstances, it asks whether to save the buffer, but then does nothing. This behaviour is confusing and not helpful. `confirm` should either not prompt in these cases or (preferred) it should prompt for the name of a file to save to, and then carry out the original action.

This bug is also present in Vim, so if you'd prefer I open it there first, I can.

### Steps to reproduce

* `nvim --clean`
* `:set nohidden`
* `:set confirm`
* Enter insert mode and enter anything into the scratch/unnnamed buffer
* `:e ~/any/existing/file.txt<CR>`
* At the confirm prompt, hit 'y'
* (This is the bug) Nothing happens - no switch to new buffer, no prompt for name of file.

### Expected behavior

NeoVim prompts for the name of the file to be saved, saves it, then switches to the new buffer.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-622+g08ebf8d3a

### Vim (not Nvim) behaves the same?

Yes, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 11 2022 13:50:40) Included patches: 1-1046

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

nvenv

**Comment by justinmk** [comment]
> This bug is also present in Vim, so if you'd prefer I open it there first, I can.

yes, and please link to the upstream issue here. thanks!

**Comment by glepnir** [comment]
can't reproduce now.
