### ISSUE TITLE
Execution of autocmd with `startinsert` while pattern shouldn't trigger it.

### ISSUE THREAD

**Issue by jkeDev** [neovim/neovim#21683]
### Describe the bug

When opening a new window from a window where the file matches the pattern autocmds with `startinsert` as command get executed.

### Steps to reproduce

```vim
autocmd WinEnter Xa startinsert
edit Xa
new
```

### Expected behavior

The new window should not be in insert mode as it does not match the pattern of the event.

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

yes, vim 9.0.1046

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

pacman

**Comment by zeertzjq** [comment]
Hmm, this can simply be reproduced by
```vim
autocmd WinEnter Xa startinsert
edit Xa
new
```

**Comment by jkeDev** [comment]
Oh right...
sry I am using neovim as my terminal pager, so I got a bit fixated on that.
I will edit the issue so it's more clear.

**Comment by jkeDev** [comment]
Should I open this issue in vim instead?

**Comment by zeertzjq** [comment]
Probably.

**Comment by jkeDev** [comment]
The issue in vim vim/vim#11789

**Comment by jkeDev** [comment]
Works as intended.
As the wiki states it triggers before the buffer is loaded so the pattern matches on the old file.
```
WinEnter			After entering another window.  Not done for
				the first window, when Vim has just started.
				Useful for setting the window height.
				If the window is for another buffer, Vim
				executes the BufEnter autocommands after the
				WinEnter autocommands.
				Note: For split and tabpage commands the
				WinEnter event is triggered after the split
				or tab command but before the file is loaded.
```
