### ISSUE TITLE
With konsole 22.12.1, blinking cursor block started hiding text

### ISSUE THREAD

**Issue by shmerl** [neovim/neovim#21698]
### Describe the bug

There seems to be some recent regression with konsole 22.12.1, where blinking cursor started hiding underlying symbol.

### Steps to reproduce

The way cursor was configured for me so far:

```
" cursor shapes
set guicursor=n-c:block-Cursor/lCursor-blinkon1,v-i-ci:ver25-Cursor/lCursor-blinkon1,r-cr:hor20-Cursor/lCursor-blinkon1
```

See attached video snippet with this regression:
[neovim_konsole_blinking_bug.zip](https://github.com/neovim/neovim/files/10369716/neovim_konsole_blinking_bug.zip)

### Expected behavior

Cursor shouldn't hide text when it blinks out.

Is it something I should report to konsole as a bug or there are some options that can be adjusted within nvim config?

### Neovim version (nvim -v)

v0.7.2

### Vim (not Nvim) behaves the same?

---

### Operating system/version

Debian testing Linux

### Terminal name/version

Konsole 22.12.1

### $TERM environment variable

xterm-256color

### Installation

Debian repository

**Comment by zeertzjq** [comment]
https://bugs.kde.org/show_bug.cgi?id=463911
