### ISSUE TITLE
title_pos == 1 when you get win config with vim.api.nvim_win_get_config

### ISSUE THREAD

**Issue by Cassin01** [neovim/neovim#21695]
### Describe the bug

title_pos == 1 when you get win config with vim.api.nvim_win_get_config

### Steps to reproduce

vim.api.nvim_set_keymap("n", "<Leader>l", "", {
  callback = function()
    local conf_ = {
      width = 10,
      relative = "editor",
      anchor = "NW",
      style = "minimal",
      border = "rounded",
      title = "Hoge",
      title_pos = "center",
    }
    local conf = vim.fn.extend(conf_, {
        height = 10,
        row = 10,
        col = 10,
      })
    local buf = vim.api.nvim_create_buf(false, true)
    local win =  vim.api.nvim_open_win(buf, true, conf)
    print(vim.inspect(vim.api.nvim_win_get_config(win)))

  end,
  noremap = true,
  silent = true,
  desc = "title_pos == 1",
  nowait = true,
})

### Expected behavior

{
  anchor = "NW",
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  col = {
    [false] = 10,
    [true] = 3
  },
  external = false,
  focusable = true,
  height = 10,
  relative = "editor",
  row = {
    [false] = 10,
    [true] = 3
  },
  title = { { "Hoge", "FloatTitle" } },
  title_pos = 1,
  width = 10,
  zindex = 50
}

### Neovim version (nvim -v)

v0.9.0-dev-633+g904c13e6b-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

13.1

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

brew install --HEAD neovim

**Comment by Cassin01** [comment]
[Here would be STRING_OBJ instead of INTEGER_OBJ](https://github.com/neovim/neovim/blob/904c13e6b572552a676efcaec640dfa8bd199e59/src/nvim/api/win_config.c#L302)

**Comment by justinmk** [comment]
@glepnir

**Comment by glepnir** [comment]
it's `enum type` . so just need a covert.
