### ISSUE TITLE
backspace in insert doesn't work if .nvimrc isn't empty

### ISSUE THREAD

**Issue by phubaba** [neovim/neovim#2169]
I downloaded using the apt-get method I'm running on xubuntu.

if I have a totally empty .nvimrc, the backspace will work in insert mode
if I put even a comment in my .nvimrc, the backspace will stop working in insert mode

I have to add the following line:
set backspace=indent,eol,start

to fix the issue.

**Comment by justinmk** [comment]
That's how it is in Vim as well. We are planning to change some defaults, but already have an issue for that.
