### ISSUE TITLE
Has plan to comment the runtime vim.* functions optional parameters or pr welcome?

### ISSUE THREAD

**Issue by zhoudaxia2016** [neovim/neovim#21692]
### Problem

I use this plugin [neodev](https://github.com/folke/neodev.nvim) and lua-language-server to get the vim lua apis signature help when I write nvim plugins code.
But I always get this diagnostic message when call a api.
Just like this:
```lua
vim.split(a, ' '))  -- This function requires 2 argument(s) but instead it is receiving 0.
```
But according to the nvim doc，the third arugment of vim.split is optional.

----
## reason
The comment of the function does not add parameter optional flag
The vim.split source code
```lua
---@param s string String to split
---@param sep string Separator or pattern
---@param kwargs table Keyword arguments:
---       - plain: (boolean) If `true` use `sep` literally (passed to string.find)
---       - trimempty: (boolean) If `true` remove empty items from the front
---         and back of the list
---@return table List of split components
function vim.split(s, sep, kwargs)
```

### Expected behavior

The vim.split source code should be (Differences is the third line)
```lua
---@param s string String to split
---@param sep string Separator or pattern
---@param[opts] kwargs table Keyword arguments:
---       - plain: (boolean) If `true` use `sep` literally (passed to string.find)
---       - trimempty: (boolean) If `true` remove empty items from the front
---         and back of the list
---@return table List of split components
function vim.split(s, sep, kwargs)
```
The doc is https://github.com/lunarmodules/LDoc/blob/master/doc/doc.md

**Comment by folke** [comment]
This has been fixed on nightly already a while ago.

**Comment by Jlll1** [comment]
Wouldn't this be an issue in other places as well as mentioned in #21556?

**Comment by folke** [comment]
I've made some effort to fix it a a lot of the lua code already.

Check `shared.lua` for examples. The vimdoc parser that we use properly formats the docs, while they can still be parsed correctly by the lua-language-server.

**Comment by zhoudaxia2016** [comment]
> 



> Wouldn't this be an issue in other places as well as mentioned in #21556?

I think is no.
The pr you mentioned is about refactoring code to expressing optionals.
I mean some functions parameters type is not right.

**Comment by zhoudaxia2016** [comment]
> > 
> 
> > Wouldn't this be an issue in other places as well as mentioned in #21556?
> 
> I think is no. The pr you mentioned is about refactoring code to expressing optionals. I mean some functions parameters type is not right. It's all right as this has been fixed
