### ISSUE TITLE
Suggestion: more like a fix, but I think adding these keybindings would help so much.

### ISSUE THREAD

**Issue by segfaulty1** [neovim/neovim#21705]
### Problem

The default behavior of `d`, `c` and `p` is really off.
I know that changing the defaults is not always a good idea. But I couldn't not open this issue.

### Expected behavior

I expect the behavior to be sane. which is explained by the following snippet:
Maybe not the best way to do it. but It might also prove my point :).
```lua
-- stop copying when deleting
keymap('n', 'd', '"_d', opts)
keymap('n', 'D', '"_D', opts)
keymap('v', 'd', '"_d', opts)
-- stop copying when changing
keymap('n', 'c', '"_c', opts)
keymap('v', 'c', '"_c', opts)
keymap('n', 'ci', '"_ci', opts)
keymap('n', 'C', '"_C', opts)
-- stop copying when pasting over
keymap('v', 'p', '"_dP', opts)
-- add a way to cut
keymap('v', 'x', 'y==gvd', opts)
```

**Comment by dundargoc** [comment]
Hmm, not sure why this is more preferable than the default behavior if I'm being honest. Being able to paste the thing you just deleted is convenient when you want to quickly move a code section from one place to another.

**Comment by justinmk** [comment]
no, the existing behavior has a purpose. 

a builtin "yank ring" could address common complaint about the existing behavior, but we definitely aren't going to change this particular behavior.

see also https://neovim.io/charter/

**Comment by segfaulty1** [comment]
Ok understandable.

@dundargoc that is exactly what cut+paste does. I personally map cut to x and never faced a problem and I also think any new user would find it more intuitive.
My idea is that there should be an option for each behavior by default. If I want to delete a line for example while retaining my old copied text I should be able to do so by default.
