### ISSUE TITLE
[bug] [builtin-terminal-emulation] Sometimes size of terminal doesn't resize to window size.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2170]
Not sure how to reproduce it yet, but every once in a while a terminal won't fill the whole window (and there's only one window with that terminal, so it's not limited in size by any other smaller window).

**Comment by tarruda** [comment]
I have updated the terminal branch today, were you using the latest version?

**Comment by trusktr** [comment]
I just updated. I'll see if it still happens.

**Comment by trusktr** [comment]
I haven't been seeing this while playing around with resizing and splitting terminal windows. It might be fixed. I'll just close it and re-open if I run into it again.

Maybe this is related? https://github.com/neovim/neovim/pull/2076#issuecomment-84702792

**Comment by brettanomyces** [comment]
I'm still sometime getting this problem using version:

 (NVIM 0.0.0-alpha+201504131025 (compiled Apr 14 2015 08:29:20)
Commit: d60ae3159ecb2906e53a44241a51dada359d38f0

Unfortunately I haven't been able to find a way to reliably reproce it
