### ISSUE TITLE
Better program exit message.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2171]
When a terminal exits, we see

```
[Program exited, press any key to close]
```

Then I'd instinctually want to type `:` to get into command mode, but I keep messing up because the first `:` closes the terminal, then the next `:` works, so to do something like `:tabnew` I would instead do something like `::tabnew`.

A couple directions to go in:

1. Show this message as a normal message that appears in the command area, like all other messages, and just close the window, unless it's the last window in which case just go to an `enew` buffer. Don't require the user to press a key for this to happen.
2. Add this message at the end of the terminal buffer like currently happens, except don't tell the user to press any key to exit, and pressing a key doesn't close the terminal buffer. `[Program exited]` The buffer will stay there, intact, and the user can then do things like yank contents of the buffer (similar to how the default behavior in Mac OS X's Terminal app leaves the buffer in tact after the terminal has exited). Trying to go back into TERMINAL mode won't do anything (and perhaps that repeats the same message in the command area so the user understands `Program exited, cannot enter TERMINAL mode.`).

I like option 2 much better because currently we lose the buffer when the terminal exits, and so we are not able to interact with the buffer in NORMAL mode to yank, view history, etc. It'd be possible to script vimrc to then apply the behavior of (1) if they want to.

**Comment by tarruda** [comment]
What about this approach?

```diff
diff --git a/src/nvim/terminal.c b/src/nvim/terminal.c
index c657cb3..41f385f 100644
--- a/src/nvim/terminal.c
+++ b/src/nvim/terminal.c
@@ -334,6 +334,9 @@ void terminal_enter(Terminal *term, bool process_deferred)

       default:
         if (term->closed) {
+          if (c == ':') {
+            ins_char_typebuf(c);
+          }
           close = true;
           goto end;
         }
```

**Comment by tarruda** [comment]
> I like option 2 much better because currently we lose the buffer when the terminal exits, and so we are not able to interact with the buffer in NORMAL mode to yank, view history, etc. It'd be possible to script vimrc to then apply the behavior of (1) if they want to.

You can do that if you exit to normal mode instead of pressing other keys

**Comment by tarruda** [comment]
You are right though, it may be better to not close the window automatically and expose a `TermProgramExit` event which can be used to customize the behavior

**Comment by trusktr** [comment]
@tarruda It just popped into my head: what about a setting along the lines of

```viml
set programclose
set noprogramclose
```

One way would be like option (1) and the other way like option (2).

**Comment by trusktr** [comment]
It might be similar to OS X Terminal's "When the shell exits" setting, which has the options

1. Close the window
2. Close if the shell exited cleanly
3. Don't close the window

If you wanted to match that with neovim, I think that might be nice:

```viml
set programclose=always
set programclose=noerror
set programclose=never
```

**Comment by justinmk** [comment]
New options should not be added so lightly.

**Comment by tarruda** [comment]
> New options should not be added so lightly.

As someone who dislike vim option system(#1913) I agree. I plan to use buffer variables to configure terminal instances.

**Comment by justinmk** [comment]
Even so, options should be avoided. In this case, if the user wants some behavior after quitting, let's just make sure it's possible to script it (e.g. with an event as you said, although even that probably isn't necessary for this use case), rather than having an option.

**Comment by tarruda** [comment]
@justinmk There will be a `TermExit` event, which could be used for this purpose

**Comment by trusktr** [comment]
With option (2) the default behavior, a TermProg{ram,}Exit autocommand can make option (1) be the new behavior easily. 

TermProgramExit for anytime any program in the terminal exits, and TermExit for when the root program exits?

**Comment by justinmk** [comment]
Covered by https://github.com/neovim/neovim/issues/2293
