### ISSUE TITLE
Artifacts

### ISSUE THREAD

**Issue by dqvid-git** [neovim/neovim#21713]
### Describe the bug

When the interface is updated or changed, some artifacts appear. It may seem that this is due to AstroNvim, but this problem also exists in simple Neovim. I know that I can just \<C-L\> and screen will redraw, it does not work in AstroNvim, and anyway it's uncomfortable.

![issue](https://user-images.githubusercontent.com/33931619/211409457-60899bcd-cf25-44e5-9ac3-57ba8f318144.gif)

### Steps to reproduce

Run nvim with configured LSP and try to complete code, or create buffers like NerdTree or NeoTree.

### Expected behavior

I really expect there to be no visual artifacts.

### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

can't say, didn't configured vim so I can't see if it behaves same

### Operating system/version

Windows 11, ArchLinux with WSL2

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm=256color

### Installation

pacman

**Comment by dundargoc** [comment]
Can confirm, this is WSL-specific and not related to anstronvim (not even sure why you'd bring that up, this happens on neovim without any plugins).

**Comment by dqvid-git** [comment]
how can i fix this?

**Comment by dqvid-git** [comment]
How can I fix this problem?

**Comment by dundargoc** [comment]
Either send a PR to neovim that fixes it or wait until someone else does :)

**Comment by justinmk** [comment]
no useful info here, and the title is very insufficient. covered by existing "display" issues https://github.com/neovim/neovim/labels/display

**Comment by trev-dev** [comment]
@justinmk  Are we open to more experiences in this thread, or should I open a new issue?

I am having very similar problems as @dqvid-git and can provide some more information.

1.  I am using Windows 10 19044.2486

**Comment by justinmk** [comment]
> it looks like the boundaries of the application are ignored and the text is dropped into the leftmost boundary of the emulator.

that definitely looks like an issue that was reported before. perhaps in "closed" issues.

please also try the latest development version of Nvim.

**Comment by trev-dev** [comment]
@justinmk Thanks for hearing me out.  Among the 7k issues I can't seen to find the issue that most resamples mine and has a solution.  This is of course a me problem, not a you problem.  I used the slick nix flake to install the dev build and after about 4 minutes of doing things that would break my UI yesterday, things seem solid.

**Comment by dantesg** [comment]
just in case someone else lands here searching for a solution. try running `wsl --update` as admin. it seems to have solved for me
cc @dquevid

**Comment by adonespitogo** [comment]
> just in case someone else lands here searching for a solution. try running `wsl --update` as admin. it seems to have solved for me cc @dquevid

Sadly this doesn't work for me.
