### ISSUE TITLE
init.lua isn't loaded

### ISSUE THREAD

**Issue by Cyliann** [neovim/neovim#21728]
### Describe the bug

When I open nvim I get: 
```
Error detected while processing VIMINIT:
E484: Can't open file /home/cylian/.config/nvim/init.vim
Press ENTER or type command to continue
```
but if I open with `nvim -u $XDG_CONFIG_HOME/nvim/init.lua` nvim opens with proper config.

### Steps to reproduce

Open nvim on my machine I guess.

### Expected behavior

Load init.lua

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

No (no support for lua in vim)

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.8.0

### $TERM environment variable

alacritty

### Installation

Arch Repo

**Comment by clason** [comment]
Actually, the first order of business is to check `$VIMINIT`, especially where it is set (e.g., your shell profile). It shouldn't be, normally, so try removing that.

**Comment by Cyliann** [comment]
Ok. I had $VIMINIT set in my `.profile`, but I don't remeber setting it. Removing it solved the problem. Anyway thanks for help.
