### ISSUE TITLE
statuscolumn respects `signcolumn` but not `number`/`nonumber`

### ISSUE THREAD

**Issue by bkoropoff** [neovim/neovim#21745]
### Describe the bug

The new `statuscolumn` feature respects the `signcolumn` option, and will omit signs if they are turned off even if `%s` is present in the format string.  However, it does not respect the `number`/`nonumber` option, so `%l` always renders the line number.  The behavior should be consistent one way or the other.

### Steps to reproduce

```vim
set statuscolumn=%l%s
set signcolumn=no
set nonumber
```

Result: Line numbers are displayed, but no signs
Expected: Neither are displayed

### Expected behavior

Line numbers should not be displayed with `nonumber`, just as signs are not displayed with `signcolumn=no`.  Alternatively, `statuscolumn` should consistently override/ignore both options.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-656+g93d99aefd

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux/Fedora 37

### Terminal name/version

Alacritty/master

### $TERM environment variable

alacritty

### Installation

build from repo

**Comment by luukvbaal** [comment]
> Line numbers should not be displayed with nonumber.

I guess that this could be adopted for the `%l` and `%r` items. `v:lnum` and `v:relnum` will need to be set regardless of `'number'` and `'relativenumber'` however. When evaluating those, it will instead be up to the `'statuscolumn'` expression to "respect" those options:

    set statuscolumn=%{&nu?v:lnum:''}

**Comment by bkoropoff** [comment]
> > Line numbers should not be displayed with nonumber.
> 
> I guess that this could be adopted for the `%l` and `%r` items. `v:lnum` and `v:relnum` will need to be set regardless of `'number'` and `'relativenumber'` however. When evaluating those, it will instead be up to the `'statuscolumn'` expression to "respect" those options:
> 
> ```
> set statuscolumn=%{&nu?v:lnum:''}
> ```

That seems like a good solution.  It means simple uses of `statuscolumn` won't break existing configs/plugins that expect `nonumber` to be enough to turn line numbers off for certain buffers, but you can always customize the exact behavior precisely if needed.

**Comment by rebelot** [comment]
I am adding to this as I struggled to obtain the same behaviour as when both `nu` and `rnu` are set:

```vim
:set stc=%=%4{&nu ? (&rnu ? (v:lnum == line('.') ? v:lnum : v:relnum) : v:lnum) : ''}
```

linenr at cursor position is absoulte, linenr other than cursor position are relative.

**Comment by luukvbaal** [comment]
> Would there be a way to make this more concise?

Yes, check that `v:relnum == 0` instead of `v:lnum == line('.')`, and do a logical AND with `&rnu`:

    :set stc=%=%4{&nu?(&rnu&&v:relnum?v:relnum:v:lnum):''}

**Comment by Bekaboo** [comment]
A better solution that mimic the original behavior related to `number`/`relativenumber` settings:

```
:set statuscolumn=%=%{%v:virtnum?'':(&nu?(&rnu?(v:relnum?v:relnum:printf('%-'.max([3,len(line('$'))]).'S',v:lnum)):v:lnum):(&rnu?v:relnum:''))%}
```
