### ISSUE TITLE
allow using sign to indicate the `signcolumn`

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#21750]
### Problem

we can only set the `signcolumn`'s color, but what if we can use a sign to indicate it, it might be cool!
`vim.o.signcolumn = "140:-"`

like this:
```
    local linecnt = api.nvim_buf_line_count(0)
    for i = 1, linecnt do
        local opts = {
            id = i,
            virt_text = { { '', "signcolumn" }, },
            virt_text_pos = "overlay",
            virt_text_win_col = 140,  -- signcolumn
        }

        api.nvim_buf_set_extmark(0, ns_id, i, 0, opts)
    end
```

### Expected behavior
![image](https://user-images.githubusercontent.com/97107165/211808465-37b45c5f-dd21-4070-8350-846d40cb2bd9.png)

**Comment by lewis6991** [comment]
Not really sure what you're asking for here. You can already apply signs via extmarks.

**Comment by lewis6991** [comment]
Again.... I don't know what you're asking for.

**Comment by justinmk** [comment]
> `vim.o.signcolumn = "140:-"`

overloading the 'signcolumn' option with that syntax would be hard to explain/use: does "140" imply "yes", "auto", ...? We could support another `:` in this 'signcolumn' DSL, but this has overlap with existing functionality as mentioned above.
