### ISSUE TITLE
Display problem with new statuscolumn and fold-related fill characters

### ISSUE THREAD

**Issue by silvercircle** [neovim/neovim#21759]
### Describe the bug

When using a multibyte character for one of the fold-related fillchars, the gutter displaying the folds gets messed up (see screenshot)

This happens only when having multiple nested folds and foldcolumn at 4 or higher. It's reproducible with a --clean config with minimal settings and multiple terminal emulators (alacritty, konsole, kitty) and $TERM settings. **Only tested on Linux**

I'm using a nerd font, maybe that's of importance.

Setting the foldsep fill character to │ (0x2502) (or possible any other multibyte character) triggers the problem. Using a single-byte character like | or ¦ works normally.

![foldbug](https://user-images.githubusercontent.com/815360/211831330-db4e968d-166e-44d7-a420-1bf587e0d957.png)

After setting foldcolumn=3 the gutter looks normal again

![foldbug1](https://user-images.githubusercontent.com/815360/211830954-80759a49-e5d1-4952-be5c-f85edef4a335.png)

When using the pipe character as foldsep, it also displays normally.

![foldbug2](https://user-images.githubusercontent.com/815360/211831847-691b53a9-2df6-4eb2-96e5-353f3310f97f.png)

### Steps to reproduce

nvim --clean -u ./minimal.vim

minimal config required:
* set foldcolumn=4 (or higher)
* vim.o.fillchars = [[eob: ,fold: ,foldopen:-,foldsep:│,foldclose:+]]
* set statuscolumn=%@SignCb@%=%s%=%T%#NumCb#%l\ %C%#Normal#│\ 

* create at least 4 nested folds and open them. Closed folds display normally.

### Expected behavior

properly displayed folding guides in the gutter.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-658+g80a02d1ce

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Linux warpcore 6.0.18-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 7 17:10:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

built from source

**Comment by luukvbaal** [comment]
Right, I hadn't considered multibyte fillchars for 'statuscolumn' (I don't really use folds). `statuscol_t.fold_text` will need to be bigger. I'll make a PR.
