### ISSUE TITLE
Lua << EOF breaks because of tabs

### ISSUE THREAD

**Issue by gilice** [neovim/neovim#21754]
### Describe the bug

A movie is worth a thousand words: 
![nvim-bug](https://user-images.githubusercontent.com/104317939/211905847-2bc40064-654b-4166-8ac8-f45925c514a4.gif)

Basically, a `lua << EOF` block seems to break for no reason on tab indentation.

### Steps to reproduce

- install nvim
- try to source a `lua << EOF` part with tabs at the beginning, like in the example
- nvim can't source it:
   -  ` Error loading lua [string ":lua"]:3: '=' expected near '<eof>'`

Later,
- try without the tabs
- everything works

### Expected behavior

The two cases above behave the same. Adding tab indents at the start of the lua block doesn't impact anything.

### Neovim version (nvim -v)

0.8.2, from NixOS-Unstable

### Vim (not Nvim) behaves the same?

not relevant (vim doesn't have lua)

### Operating system/version

NixOS unstable (23.05.20230110.c07552f (Stoat))

### Terminal name/version

foot 1.13.1

### $TERM environment variable

xterm-256color

### Installation

nixpkgs

**Comment by ii14** [comment]
This is documented in `:lua-heredoc`:
> {endmarker} must NOT be preceded by whitespace.
