### ISSUE TITLE
Buggy `lua.fn.feedkeys(...)`

### ISSUE THREAD

**Issue by hinell** [neovim/neovim#21769]
### Describe the bug

```lua
lua vim.fn.feedkeys([[<CR>]])
```
```lua
lua vim.fn.feedkeys([[\<CR>]])
```
```lua
lua vim.fn.feedkeys("\\<CR>")
```

Weirdly, neither of the above reproduces what the docs (`:help feedkeys`) says for the `feedkeys` builtin. The Second one should trigger action mapped by `<CR>` but it doesn't. In my case it inserts nothing. Even if prepended by `lua vim.cmd("i") ...` it doesn't work.

### Steps to reproduce

```vim
nvim-x --clean ./
:tabnew
lua vim.cmd("i") lua vim.fn.feedkeys([[\<CR>]])
```

### Expected behavior

Inserts `<CR>` as documented?

### Neovim version (nvim -v)

NVIM v0.9.0-dev-9b1112c

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux Kubuntu 22.04

### Terminal name/version

Xterm 3.7.2 (XTerm(372))

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
The documented usage is for Vimscript, not Lua

**Comment by bew** [comment]
Would it be possible to add 'links' to Lua-specific help from the vimscript one?

So that if we know the vimscript name, but want to use it from Lua we can more easily find what we should actually use?

**Comment by clason** [comment]
No, because that part of the documentation is owned by Vim. Conversely, `:h lua-guide` explains exactly how to use vimscript functions (and Nvim API calls) from Lua already.

**Comment by hinell** [comment]
The following seems to be working: 
```lua
local key = vim.api.nvim_replace_termcodes("<CR>", true, false, true)
vim.api.nvim_feedkeys(key, "m", true)
```
@zeertzjq  Builtins are exposed to Lua.  I thought the string escapes are processed internally by C binary
@bew No need. Lua references for internal API is declared clearly but for internal and `nvim_*` api fncs
@clason Neovim maintains its own docs at [`neovim/runtime/doc`](https://github.com/neovim/neovim/tree/master/runtime/doc)

**Comment by clason** [comment]
Yes, but the individual files are taken from Vim. Making changes there makes porting upstream improvements (much) harder.
