### ISSUE TITLE
Mouse Event Enhacement: `drag`

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#21762]
### Problem

Is it possible to make neovim only responds to mouse-drag events, not click events?

here's the reason I want to do this:
1. when we want to resize the window, the mouse is more convenient than using the shortcut, so the most user might set `mouse = "a"`
2. But if we set `mouse = 'a'` click the other system application, then click back neovim, the cursor will jump when `FocusGained`, which is little annoying.

### Expected behavior

adding a mouse-drag event like `set mouse="d"` so we can simply resize the window by draging the mouse but won't get cursor jump when `FocusGained`

**Comment by justinmk** [comment]
> 2\. then click back neovim, the cursor will jump

you can map `<LeftMouse>` to workaround this.

need a stronger use-case.

Note: in the future there will potentially be some way to handle all input "atoms", and handlers could cancel them. So I'm not sure we need a `MouseEvent`.

**Comment by airtonix** [comment]
@NEX-S I'd look into how https://www.reddit.com/r/neovim/comments/lo0xk8/nvimscrollview_scrollbars_can_now_be_dragged_with/

is doing it, because that doesn't have the annoying jump when click back to my neovim terminal to drag the scroll bar.

**Comment by bew** [comment]
> 2. click the other system application, then click back neovim

FYI That could also be handled by the terminal, I know (and use) Wezterm does not send click mouse events to the application when the terminal is being focused, so to focus and then move cursor you need 2 clicks (but scroll events are passed through)
That doesn't solve the drag-only events though
