### ISSUE TITLE
Neovim on Windows hangs after reading from stdin

### ISSUE THREAD

**Issue by 3N4N** [neovim/neovim#21776]
### Describe the bug

Starting neovim with text read from stdin through redirection causes neovim to hang.  Needs `Ctrl-C` to exit to the shell.

### Steps to reproduce

```
echo 'foo' | nvim
```

### Expected behavior

Neovim doesn't hang.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-664+ga5f4ba74472f

### Vim (not Nvim) behaves the same?

no, vim 9.0.815

### Operating system/version

Windows 11 22H2

### Terminal name/version

Windows Terminal, Conhost

### $TERM environment variable

nil, xterm-256color

### Installation

Built from source

**Comment by 3N4N** [comment]
The offending commit is [`244881`][1] (bisected by dundargoc).

[1]: https://github.com/neovim/neovim/commit/24488169564c39a506c235bf6a33b8e23a8cb528

**Comment by justinmk** [comment]
Does it hang immediately, i.e. no UI is shown? Or is `nvim` usable, and it "hangs" after `:q` ?

**Comment by dundargoc** [comment]
Nvim is not usable and hangs immediately. I don't know what you mean by no UI. This is what is shown for me when it hangs:

<img width="1920" alt="crash" src="https://user-images.githubusercontent.com/33953936/212138328-287cb38a-db48-4894-b34f-1b41f62d2a56.png">

<img width="1920" alt="ctrl-c" src="https://user-images.githubusercontent.com/33953936/212138393-c1308602-929b-4ab1-99b1-1a811f14d57a.png">

**Comment by 3N4N** [comment]
To clarify: this behavior isn't dependent on the shell.  It happens on both cmd and powershell.

(Confusion may have risen because I strictly open issues about powershell.)

**Comment by erw7** [comment]
https://github.com/neovim/neovim/blob/4a12372ccf70236c1c23144129984a3629cc45f3/src/nvim/ui_client.c#L51-L54

**Comment by 3N4N** [comment]
Is that codeblock the culprit?  Looks like it's not specifically run on Windows, though.  So how come it's causing problem only in Windows?

**Comment by 3N4N** [comment]
Building with that conditional codeblock commented/removed, this bug disappears.

But using MSVC toolchain and Debug build type, when I exit nvim, I get this error:

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: E:\projects\neovim\master\build-msvc\bin\nvim.exe
File: minkernel\crts\ucrt\src\appcrt\lowio\osfinfo.cpp
Line: 261

Expression: _osfile(fh) & FOPEN

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------
```

With (MSys/MinGW toolchain) or (with MSVC and Release build type), I don't get any error upon exit.

**Comment by dundargoc** [comment]
Debug build on Windows is practically broken. It's possible it's not even related. If it works on release that's fine for now.

**Comment by 3N4N** [comment]
> wait, did you rebuild the dependencies with Debug as well?

I haven't.  Currently doing that.

And this is the change that was needed to "fix" the bug ("fix" in quotes because I don't know if it's a legitimate fix; I don't know what closing 0 file descriptor entails):

```diff
diff --git a/src/nvim/ui_client.c b/src/nvim/ui_client.c
index ff82fd3239c4..d8f039736831 100644
--- a/src/nvim/ui_client.c
+++ b/src/nvim/ui_client.c
@@ -49,7 +49,7 @@ uint64_t ui_client_start_server(int argc, char **argv)
                                        false, true, true, false, kChannelStdinPipe,
                                        NULL, 0, 0, NULL, &exit_status);
   if (ui_client_forward_stdin) {
-    close(0);
+    // close(0);
     dup(2);
   }
```

**Comment by 3N4N** [comment]
> > D: wait, did you rebuild the dependencies with Debug as well?
> 
> 3: I haven't. Currently doing that. I'll update on this.

Rebuilding deps with Debug build type fixed the assertion error.  Nice catch.

**Comment by dundargoc** [comment]
Ye. MSVC doesn't allow mixing libraries of different types (maybe it's possible to work around with a flag? /nostdlib or something?) Anyway, it's unrelated to this, but we could look into preventing this scenario/making the error clearer in the future.

**Comment by bfredl** [comment]
please try again latest master with #21831

**Comment by dundargoc** [comment]
Fixed for me
