### ISSUE TITLE
Fix brew upgrade command for nightly on neovim wiki to not always reinstall neovim

### ISSUE THREAD

**Issue by dagadbm** [neovim/neovim#21770]
### Describe the bug

I have tried to clone the wiki page and do the changes myself but I don't have permission else I wouldn't have opened the issue but it annoys me so much that I just decided to take my time to write about it.

The command `brew reinstall neovim` is unnecessary as it will always reinstall even if no updates have happened.
A better approach for this (which I have tested and it works) is to just call `brew upgrade neovim --fetch-HEAD`.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Neovim version (nvim -v)

N/A

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

**Comment by clason** [comment]
Thanks, I made the change!
