### ISSUE TITLE
[feature] Using etherpad with neovim

### ISSUE THREAD

**Issue by pickfire** [neovim/neovim#2177]
Hi,
There is a [plugin for using vim](https://github.com/guyzmo/vim-etherpad) with etherpad seems that it has stop developing. I hope neovim will be able to use [etherpad](https://github.com/Floobits) as an alternative to [floobits](https://github.com/Floobits). Thanks.

**Comment by Pyrohh** [comment]
I can't comment on the merit of the suggestion itself, but given that neither projects are directly related to neovim, this seems out of scope (at least for now, given how many other things there are to do).

**Comment by jszakmeister** [comment]
Agreed.  This isn't going to be a core Neovim feature.

**Comment by pickfire** [comment]
Yeah, I am just giving a suggestion as using `etherpad` can collaborate with non-vim users. Is there any collaboration tools that will be implemented as `neovim` feature? And is there a list of core `neovim` feature?

**Comment by tarruda** [comment]
>  Is there any collaboration tools that will be implemented as neovim feature ?

Neovim uses a client-server model where the UI and the core nvim processes can be in different computers. In theory that could be used to perform pair programming, but only between neovim users. Collaboration tools that integrate Neovim with other editors need to be implemented as plugins

**Comment by pickfire** [comment]
> Neovim uses a client-server model where the UI and the core nvim processes can be in different computers. In theory that could be used to perform pair programming, but only between neovim users. Collaboration tools that integrate Neovim with other editors need to be implemented as plugins

What about `neovim` with `vim`?

**Comment by tarruda** [comment]
> What about neovim with vim?

As I said, only as a plugin
