### ISSUE TITLE
`nvim_buf_set_extmark` cause crash in `foldtext`'s function

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#21774]
### Describe the bug

using `nvim_buf_set_extmark` in `foldtext` seems will cause nvim crash

### Steps to reproduce

```lua
local api = vim.api
local ns_id = api.nvim_create_namespace("test")
function _G._fold_text ()
    local sline = vim.v.foldstart

    local string = api.nvim_buf_get_lines(0, sline - 1, sline, true)[1]
    local indent = string:find("%S") - 1

    local opts = {
        id = sline,
        virt_text = { { '>', "FoldOpen" }, },
        virt_text_win_col = 3,
        virt_text_pos = "overlay",
        hl_mode = "combine",
    }

    api.nvim_buf_set_extmark(0, ns_id, sline - 1, 0, opts)
    return string
end

vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.foldmethod = "indent"
vim.o.foldtext = "v:lua._fold_text()"
```

### Expected behavior

setting virt text on foldtext

### Neovim version (nvim -v)

NVIM v0.9.0-dev-663+g2aabe9b85

### Vim (not Nvim) behaves the same?

not test

### Operating system/version

Linux UNEXPECTED 6.0.8-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:22 +0000 x86_64 GNU/Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

compile manually

**Comment by lewis6991** [comment]
Setting extmarks in `foldtext` isn't supported. `foldtext` should just return a string and not perform any side effects.

**Comment by clason** [comment]
@NEX-S In the future, I recommend asking on Matrix before opening issues or feature requests here, at least until you've become more familiar with the project.
