### ISSUE TITLE
Can't map `*` (asterisk) anymore

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#21780]
### Describe the bug

I had a `<Leader>*` binding that I was using to grep `<cword>` in the project (using telescope `grep_string()`) that stopped working. Trying to debug it, I found I cannot bind `*` to do anything at all (it will just continue the default behaviour).

### Steps to reproduce

nvim --clean
:nnoremap * :echo 'hi'<CR>

### Expected behavior

'hi' is echo'd whenever you press asterisk. Working in Vim HEAD (compiled a few minutes ago and tried with `vim -u DEFAULTS`).

### Neovim version (nvim -v)

0.9.0 commit 2f1fd15

### Vim (not Nvim) behaves the same?

no, 9.0.1188

### Operating system/version

macOS 12.5.1

### Terminal name/version

Wezterm

### $TERM environment variable

wezterm

### Installation

source

**Comment by zeertzjq** [comment]
Maybe there is change in your terminal emulator?

**Comment by zeertzjq** [comment]
Try mapping `<S-*>` or `<S-8>` instead

**Comment by craigmac** [comment]
It is a Wezterm problem, should've thought of that!

**Comment by craigmac** [comment]
specifically because neovim sees it as `<S-*>` with kitty keyboard protocol settings option turned on in wezterm
