### ISSUE TITLE
Keymap only works if keymap file is manually sourced from within nvim

### ISSUE THREAD

**Issue by samEngineering** [neovim/neovim#21803]
### Describe the bug

I'm having trouble with a particular keymap to implement `:tabnext <Return>`. All other keymaps in my keymap file are working as expected but this one is ignored at launch. My keymaps file is at
`~/.config/nvim/lua/global/keymaps.lua'

and is called from my `init.lua` with the following line:
`require('global/keymaps')`

If I manually source my keymap file from within nvim using `source ~/.config/nvim/lua/global/keymaps.lua`, the keymap starts working. I tried moving that keymap to my init.lua file, but I get the same result and it only works if I `source ~/.config/nvim/init.lua`. The keymap is the following:

`vim.keymap.set('n', '<C-l>', ':tabnext <Return>')`.

I also tried
`vim.keymap.set('n', '<C-l>', 'gt')`
but I got the same result.

This mapping worked fine in the past, but stopped working recently.
If I use a different letter other than `l`, the mapping works automatically. I thought this might be due to the "^L" binding in the shell (zsh) to clear the terminal, so I put 
`bindkey -r "^L"`
in my zsh config. That removed the mapping from my shell, but the issue persists in nvim. 

### Steps to reproduce

1. Put the following mapping in your `init.lua`:
`vim.keymap.set('n', '<C-l>', ':tabnext <Return>')`.

2. launch nvim and open a few tabs.

3. Press 'Ctrl+l' to attempt to go to the next tab.

### Expected behavior

Pressing 'Ctrl+l' goes to the next tab.

### Neovim version (nvim -v)

NVIM v0.8.2

### Vim (not Nvim) behaves the same?

no, vim 9.0.1182

### Operating system/version

archlinux 6.1.5-arch2-1

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

pacman

**Comment by zeertzjq** [comment]
What does `:verbose nmap <C-L>` print?

**Comment by samEngineering** [comment]
Thanks @zeertzjq !
A plugin had sneakily taken that mapping. Thanks for the tip!
