### ISSUE TITLE
Syntax highlight for trailing whitespace not rendering

### ISSUE THREAD

**Issue by nnathan** [neovim/neovim#21816]
### Describe the bug

Inspired by this [vim tip](https://vim.fandom.com/wiki/Highlight_unwanted_spaces) on highlighting trailing whitespace I have created a syntax highlight group to show trailing whitespaces in my init config. However even though the augroup/autocmd/etc. work and the highlight groups get created, the trailing whitespace doesn't seem to work.

To isolate the issue I have created the following init.lua:

```lua
vim.o.termguicolors = true
vim.o.mouse = ''
vim.g.show_whitespace = 1
if vim.g.show_whitespace then
  local ag = vim.api.nvim_create_augroup('show_whitespace', { clear = true })
  vim.api.nvim_create_autocmd('Syntax', {
    pattern = '*',
    command = [[syntax match Tab /\v\t/ containedin=ALL | syntax match TrailingWS /\v\s\ze\s*$/ containedin=ALL]],
    group = ag,
  })
  vim.cmd [[highlight Tab ctermbg=240 ctermfg=240 guibg=Grey50 guifg=Grey50]]
  vim.cmd [[highlight TrailingWS ctermbg=203 ctermfg=203 guibg=IndianRed1 guifg=IndianRed1]]
end
```

The highlight group TrailingWS appears to be created with the appropriate colour. However trailing whitespaces aren't being highlighted. Nor are tabs.

If I just do "match" instead of "syntax match" this appears to work for trailing whitespace but not tabs.

The equivalent vimrc:

```
set mouse=
let g:show_whitespace=1
if exists('g:show_whitespace')
    augroup show_whitespace
        autocmd!
        autocmd Syntax *
            \ syntax match Tab           /\v\t/         containedin=ALL |
            \ syntax match TrailingWS    /\v\s\ze\s*$/  containedin=ALL
    augroup END

    highlight Tab ctermbg=240 guibg=Grey50
    highlight TrailingWS ctermbg=203 guibg=IndianRed1
endif
```

works with vim but not with neovim (as a init.vim).

### Steps to reproduce

1. Create init.lua from above.
2. Start nvim.
3. Create a line with just spaces, or a line with trailing whitespaces.

Notice that the trailing whitespaces doesn't render red.

### Expected behavior

The trailing whitespaces should render red and tabs should render grey.

### Neovim version (nvim -v)

NVIM v0.9.0-dev

### Vim (not Nvim) behaves the same?

no, works on vim 8.2.4919

### Operating system/version

Ubuntu 22.04 LTS and MacOS 13

### Terminal name/version

Terminal.app

### $TERM environment variable

screen-256color

### Installation

Neovim Unstable PPA / brew

**Comment by clason** [comment]
Didn't check the autocmd `command` in detail, but make sure you escape everything correctly (or use a literal string `[[...]]`).

**Comment by nnathan** [comment]
Fair call. I updated the init.lua to use `[[...]]` strings so that they're easier to read. However I tested the highlights and it works if I use naked `match` instead of `syntax match`, so the regexes/strings should be good.

**Comment by clason** [comment]
(I was thinking more of the pipe...)

**Comment by zeertzjq** [comment]
Hmm, this seems to work if you put a `syntax on` anywhere in `init.vim`.

**Comment by clason** [comment]
That's right, since `syntax` is enabled by default in Neovim, you probably don't see the `Syntax` event being emitted.

Try `VimEnter` instead.

**Comment by nnathan** [comment]
@clason thank you, running the autocmd on VimEnter worked.

Maybe I'ma bit of noob when it comes to events, but does the VimEnter event trigger after the vimrc (or init.lua in this case) is processed, and therefore the syntax match commands execute?

**Comment by clason** [comment]
Yes, see `:h VimEnter`.

**Comment by zeertzjq** [comment]
It seems that this autocommand only works if syntax is enabled before it. Without `syntax on` in `init.vim` syntax is enable after sourcing `init.vim` so this autocommand doesn't work.

**Comment by zeertzjq** [comment]
In Vim (which doesn't enable syntax by default), this works:
```vim
set nocompatible
syntax on
let g:show_whitespace=1
if exists('g:show_whitespace')
    augroup show_whitespace
        autocmd!
        autocmd Syntax *
            \ syntax match Tab           /\v\t/         containedin=ALL |
            \ syntax match TrailingWS    /\v\s\ze\s*$/  containedin=ALL
    augroup END

    highlight Tab ctermbg=240 guibg=Grey50
    highlight TrailingWS ctermbg=203 guibg=IndianRed1
endif
```

While this doesn't:
```vim
set nocompatible
let g:show_whitespace=1
if exists('g:show_whitespace')
    augroup show_whitespace
        autocmd!
        autocmd Syntax *
            \ syntax match Tab           /\v\t/         containedin=ALL |
            \ syntax match TrailingWS    /\v\s\ze\s*$/  containedin=ALL
    augroup END

    highlight Tab ctermbg=240 guibg=Grey50
    highlight TrailingWS ctermbg=203 guibg=IndianRed1
endif
syntax on
```

**Comment by nnathan** [comment]
Yep makes sense. I am using the init.lua, so I tried the following:

```
vim.o.termguicolors = true
vim.o.mouse = ''
vim.cmd [[syn on]]
vim.g.show_whitespace = 1
if vim.g.show_whitespace then
  local ag = vim.api.nvim_create_augroup('show_whitespace', { clear = true })
  vim.api.nvim_create_autocmd('Syntax', {
    pattern = '*',
    command = [[syntax match Tab /\v\t/ containedin=ALL | syntax match TrailingWS /\v\s\ze\s*$/ containedin=ALL]],
    group = ag,
  })
  vim.cmd [[highlight Tab ctermbg=240 ctermfg=240 guibg=Grey50 guifg=Grey50]]
  vim.cmd [[highlight TrailingWS ctermbg=203 ctermfg=203 guibg=IndianRed1 guifg=IndianRed1]]
end
```

This Syntax event didn't seem to trigger.

But I am happy with the VimEnter solution.

**Comment by zeertzjq** [comment]
It is triggered, but the syntax groups created by it were removed by another autocommand.

**Comment by nnathan** [comment]
Sorry, my bad, I tested again, and it does work with the `syn on` as the above init.lua.

Looks like everything is working now. Thanks @clason @zeertzjq .
