### ISSUE TITLE
Error message when creating a new python file

### ISSUE THREAD

**Issue by Ethanol48** [neovim/neovim#21824]
### Describe the bug

when creating a new python file outputs this message but everything other than that is fine

<img width="1440" alt="Screenshot 2023-01-15 at 22 17 34" src="https://user-images.githubusercontent.com/96821054/212568323-a9531eb5-a382-42d3-9112-5a35129ef47b.png">

### Steps to reproduce

nvim any_name.py

### Expected behavior

no errors, with any other extension that I tried doesn't happen, but it works fine there's only this message that appears

### Neovim version (nvim -v)

0.8.2 

### Vim (not Nvim) behaves the same?

no, vim 9.0.1050

### Operating system/version

macOS 12.5.1

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by justinmk** [comment]
not a neovim issue
