### ISSUE TITLE
[BUG] I don't seem to get file modified warnings.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2183]
In vim, a warning will appear if a file has been modified outside of vim and ask if you want to reload it. I haven't been seeing these in neovim.

**Comment by Pyrohh** [comment]
I think this is a dupe of #1936. It looks like #1791 aims to improve it.

**Comment by justinmk** [comment]
> In vim, a warning will appear if a file has been modified outside of vim 

Terminal vim or gvim? On what events?

Closing under the assumption this is a dupe of #1936 (thanks @Pyrohh )
