### ISSUE TITLE
Add support for configuring max line length in qflist

### ISSUE THREAD

**Issue by DoDoENT** [neovim/neovim#21835]
### Problem

Currently, the line length in qflist is limited to 1023 characters. All lines longer than that are truncated. This means that long errors, such as those reported by C++ compilers are truncated and I need to invoke build manually from the command line to see the full error message.

This feature has been implemented in regular vim via [this PR](https://github.com/vim/vim/pull/11357), so it would be great if someone could port that here, or implement the same feature differently.

### Expected behavior

I expect to be able to read my error messages, regardless of their length.

This means that either the default line length of the qflist is unlimited or that there is a way to configure that in `init.lua`.

**Comment by zeertzjq** [comment]
The test depends on Vim script string interpolation...

**Comment by DoDoENT** [comment]
The test maybe, but the patch is actually in C.

Maybe it's possible to write a new test here in lua, but just port the C code?

**Comment by justinmk** [comment]
> The test depends on Vim script string interpolation... Which is a lot of patches.

we could mark those patches as N/A (and document that we don't support vimscript string interpolation), and port the test to Lua.

 vimscript features are frozen unless there's something we really need/want.
