### ISSUE TITLE
making the filename part of quickfix buffer configurable

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#21848]
### Problem

it's usual the filename part in the quickfix window occupies 1/2 width of a line (and even more in a big project), so it's hard to spot the most important text part.

senarios I used often:
* show lsp workspace diagnostic
* show grep result

### Expected behavior

I'd like to apply fn.fnamemodify and fn.pathshorten to the filename when they are being showed in the quickfix buffer (not the internal data structure).
So maybe we can register an user provided callback (lua?)  to the quickfix, something like `fn.setqflist({}, 'r', {callback-to-shape-the-filenames = function(filename) return filename end})`

**Comment by haolian9** [comment]
After opened this issue, I somehow figured out a workaround: I could just modify the quickfix buffer after it is showed. emm, that's a nice workaround to me at now and hope it works actually.

**Comment by justinmk** [comment]
> I could just modify the quickfix buffer after it is showed

that's not really a workaround, I would say it's the standard way of controlling buffer names in vim.

**Comment by mfussenegger** [comment]
See also `:h quickfixtextfunc`. You can customize the display of the quickfix list.

**Comment by haolian9** [comment]
great! Thanks you both.
