### ISSUE TITLE
Error when closing Neovim with `VimLeavePre` autocommands that execute shell commands.

### ISSUE THREAD

**Issue by vishalbalaji** [neovim/neovim#21856]
### Describe the bug

I use `kitty` as my terminal emulator and have some autocommands to adjust my padding, similar to [this](https://github.com/kovidgoyal/kitty/issues/1915#issuecomment-915773668). I have had no issues in the past with these, but with the last few  nightly releases, neovim is having some trouble exiting with these autocommands in place.

It is not just these specific commands, but any autocommand with `VimLeave` or `VimLeavePre` that executes shell commands exits with an exit code of `134`. With the latest release, the following error: 

```nvim: /__w/neovim/neovim/.deps/build/src/libuv/src/unix/core.c:116; uv_close: Assertion `!uv__is_closing(handle)` failed.```
![error](https://user-images.githubusercontent.com/36506250/212881965-ed598929-44e2-48e7-a60b-a150d469be40.png)

This does not happen on every single exit, but does happen frequently enough. The last release of neovim where I didn't have this issue was: `v0.9.0-dev-155+g771824128`.

### Steps to reproduce

- Create an autocommand with the `VimLeave` or `VimLeavePre` event that executes a shell command. For example:

```lua
-- init.lua

vim.api.nvim_create_autocmd({ "VimLeave" }, {
  callback = function()
    vim.cmd('!notify-send  "hello"')
  end,
})
```

### Expected behavior

Neovim exits with `0` exit code.

### Neovim version (nvim -v)

v0.9.0-dev-720+gf6929ea51

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch linux

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

appimage

**Comment by sQVe** [comment]
Is there any way to work around this issue until it is fixed? 🤔 🙏🏼

**Comment by KokaKiwi** [comment]
Got the same problem since today (2023-02-22), never encountered the bug before, and i'm on `nightly` build (updated 3-4 times a week)

**Comment by nmsobri** [comment]
Yep encounter the same issue since upgraded to v0.9.. Im using windows terminal.. I'm using `VimLeave` to save session when I close the terminal.. It used to work in v0.8.. but since upgraded to v0.9, it no longer work.. Is there any workaround on this?

**Comment by ragusa87** [comment]
Hello, I have the same issue since my last nvim upgrade.

**Comment by erw7** [comment]
This problem is caused by #18375. This is probably due to the fact that [`loop_poll_event()`](https://github.com/neovim/neovim/blob/4ace9e7e417fe26c8b73ff1d6042e6e4f3df9ebf/src/nvim/ui_bridge.c#L126), which was executed by `ui_bridge_stop()`, is no longer executed. As evidence, changing the `loop_poll_event()` call to twice during `event_teardown()`, as in the following patch, fixes this problem.

```diff
diff --git a/src/nvim/main.c b/src/nvim/main.c
index 698c2dcc4..8c2ccef67 100644
--- a/src/nvim/main.c
+++ b/src/nvim/main.c
@@ -159,6 +159,7 @@ bool event_teardown(void)
   }

   multiqueue_process_events(main_loop.events);
+  loop_poll_events(&main_loop, 0);
   loop_poll_events(&main_loop, 0);  // Drain thread_events, fast_events.
   input_stop();
   channel_teardown();
```

It is not clear if it is necessary to process until there are no more events during `main_loop` as in the following patch (In other words, it is unclear if a procedure exists to make the event that is causing the problem the third or subsequent event).

```diff
diff --git a/src/nvim/main.c b/src/nvim/main.c
index 698c2dcc4..328a83b7e 100644
--- a/src/nvim/main.c
+++ b/src/nvim/main.c
@@ -159,7 +159,13 @@ bool event_teardown(void)
   }

   multiqueue_process_events(main_loop.events);
-  loop_poll_events(&main_loop, 0);  // Drain thread_events, fast_events.
+  int retry = 5;
+  while (retry--) {
+    // Drain thread_events, fast_events.
+    if (loop_poll_events(&main_loop, 10)) {
+      break;
+    }
+  }
   input_stop();
   channel_teardown();
   process_teardown(&main_loop);
```

**Comment by erw7** [comment]
> Is there any way to work around this issue until it is fixed?

```lua
vim.api.nvim_create_autocmd({ "VimLeave" }, {
  callback = function()
    vim.cmd('!notify-send  "hello"')
    vim.cmd('sleep 10m')
  end,
})
```

```lua
vim.api.nvim_create_autocmd({ "VimLeave" }, {
  callback = function()
    vim.fn.jobstart('notify-send "hello"', {detach=true})
  end,
})
```

**Comment by shubham-cpp** [comment]
Can confirm that this happens even if we're executing lua apis.

```lua
--- ~/.config/nvim/lua/user/plugins/sessions.lua 
 {
    'stevearc/resession.nvim',
    enabled = true,
    lazy = true,
    init = function()
      vim.api.nvim_create_autocmd('UIEnter', {
        callback = function()
          if vim.fn.argc(-1) == 0 then
            require('resession').load(get_session_name(), { dir = 'dirsession', silence_errors = true })
          end
        end,
        group = au_session,
      })
    end,
    config = function()
      local resession = require 'resession'
      resession.setup()
      vim.api.nvim_create_autocmd('VimLeavePre', {
        callback = function()
          require('resession').save(get_session_name(), { dir = 'dirsession', notify = false, silence_errors = true })
        end,
        group = au_session,
      })
      -- Without I get the error that's mentioned above 
      -- vim.api.nvim_create_autocmd({ 'VimLeave' }, {
      --   callback = function()
      --     vim.cmd 'sleep 50m'
      --   end,
      --   group = au_session,
      -- })
    end,
  },
```

**Comment by sarmong** [comment]
Seems like there is no more 134 error code on 0.10 nightly.

**Comment by heeen** [comment]
I'll comment here for anyone on ubuntu with neovim 0.9.5-6ubuntu2: this keeps happening especially when using nvim as the git editor and quitting with `:wq`. It does not happen when you `:w` and then `:q`.

So far, after installing the .10 tar.gz release and using update-alternatives to install it as vim replacement has fixed the issue for me.

```
sudo update-alternatives --install $(which vim) vim /opt/nvim-linux64/bin/nvim 10
sudo update-alternatives --config vim
```
