### ISSUE TITLE
Folder permission of `~/.local/state` was set to `drwx——@` instead of `drwxr-xr-x@` 

### ISSUE THREAD

**Issue by nyngwang** [neovim/neovim#21861]
### Describe the bug

In short, I just want to know whether or not the behavior as the title is related to NeoVim and whether it's normal. (Sorry that this problem might be not related to NeoVim, but I really need some experts to help me double-check it.)

---

I'm a NeoVim nightly user and I recently encountered some segment faults when testing with a legacy plugin(can provide more details if needed). So I rebuilt NeoVim frequently to test which version of NeoVim was compatible with that plugin without any segment fault. Then, suddenly, I noticed that the **owner** of the runtime folder `~/.local/state`(I removed this folder each time before I built NeoVim, so I believe this was created after NeoVim had started) was set to `root`, which caused many plugins to fail due to their need to access some files inside it. After hours of debugging, I found a temporary workaround by removing a `sudo` from a line of my NeoVim build script. Now, the owner of `~/.local/state` is set to my username again, but I suspect the file permission pattern is not the default, as I indicated in the title.

The `umask` under `~/.local` always prints `022`.

Really need some helps.

(p.s. you can ignore that `@` sign since I just learned that it is something specific to macOS Ventura and it's probably not related to my question.)

A very old possibly related thread I could find is this one: https://github.com/neovim/neovim/pull/1201

### Steps to reproduce

Build NeoVim with `sudo` commands:

```
sudo make CMAKE_BUILD_TYPE=Release &> /dev/null
sudo make install &> /dev/null
```

my current workaround is removing the first `sudo`, so:

```
make CMAKE_BUILD_TYPE=Release &> /dev/null
sudo make install &> /dev/null
```

### Expected behavior

From current my understanding, the folder created at `~/.local` should always have the file permission regarding the `umask` value, so any folder created there should have the same file permission as that of the one I create with `mkdir foo`. (i.e. it should be `755` instead of `700`)

### Neovim version (nvim -v)

NVIM v0.9.0-dev-726+gddd69a6c8

### Vim (not Nvim) behaves the same?

not related

### Operating system/version

macOS 13.1

### Terminal name/version

alacritty 0.11.0 (8dbaa0b)

### $TERM environment variable

alacritty

### Installation

build from repo

**Comment by justinmk** [comment]
> my current workaround is removing the first `sudo`, so:

that is not a workaround, that's the normal recommended way of building. only `make install` requires superuser.

> From current my understanding, the folder created at `~/.local` should always have the file permission regarding the `umask` value, so any folder created there should have the same file permission as that of the one I create with `mkdir foo`. (i.e. it should be `755` instead of `700`)



from xdg spec https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

> $XDG_RUNTIME_DIR ... MUST be owned by the user, and he MUST be the only one having read and write access to it. Its Unix access mode MUST be 0700.
>
> ... default equal to $HOME/.local/state

**Comment by nyngwang** [comment]
@justinmk Thanks for your concise explanation and the link! Great work maintaining NeoVim core!

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/folder-permission-of-local-state-was-set-to-drwx-instead-of-drwxr-xr-x/3606/2
