### ISSUE TITLE
filetype detection on files named Makefile.inc is wrong

### ISSUE THREAD

**Issue by arielp** [neovim/neovim#21872]
### Describe the bug

when editing a file named `Makefile.inc` the detected `filetype` is `pov` but should be `make`

### Steps to reproduce

```
nvim --clean Makefile.inc
:set ft
```

returns: `filetype=pov`

### Expected behavior

should return: `filetype=make`

### Neovim version (nvim -v)

v0.8.2

### Vim (not Nvim) behaves the same?

No vim returns `make` as expected, Vi IMproved 9.0

### Operating system/version

OpenBSD 7.2-current

### Terminal name/version

kitty 0.26.4

### $TERM environment variable

xterm-kitty

### Installation

OpenBSD package

**Comment by zeertzjq** [comment]
I tested Vim 9.0.0000 and 9.0.1182 and they both have the same behavior. Did you test with `vim --clean Makefile.inc`?

**Comment by zeertzjq** [comment]
Also, what is the content of the file?

**Comment by arielp** [comment]
yes i did `vim --clean Makefile.inc` using vim package from OpenBSD ports. Also the following patch will cause `make oldtest` to fail on the test_filetype.vim test.

```
---                                                                                
 src/nvim/testdir/test_filetype.vim | 2 +-                                         
 1 file changed, 1 insertion(+), 1 deletion(-)                                     
                                                                                   
diff --git a/src/nvim/testdir/test_filetype.vim b/src/nvim/testdir/test_filetype.vim                                                                                  
index b065df68f..8d70d74ed 100644                                                  
--- a/src/nvim/testdir/test_filetype.vim                                           
+++ b/src/nvim/testdir/test_filetype.vim                                           
@@ -342,7 +342,7 @@ let s:filename_checks = {                                      
     \ 'mail': ['snd.123', '.letter', '.letter.123', '.followup', '.article', '.article.123', 'pico.123', 'mutt-xx-xxx', 'muttng-xx-xxx', 'ae123.txt', 'file.eml', 'reportbug-file'],                                                                    
     \ 'mailaliases': ['/etc/mail/aliases', '/etc/aliases', 'any/etc/aliases', 'any/etc/mail/aliases'],                                                               
     \ 'mailcap': ['.mailcap', 'mailcap'],                                         
-    \ 'make': ['file.mk', 'file.mak', 'file.dsp', 'makefile', 'Makefile', 'makefile-file', 'Makefile-file', 'some-makefile', 'some-Makefile'],                       
+    \ 'make': ['file.mk', 'file.mak', 'file.dsp', 'makefile', 'Makefile', 'makefile-file', 'Makefile-file', 'some-makefile', 'some-Makefile', 'Makefile.inc'],       
     \ 'mallard': ['file.page'],                                                   
     \ 'manconf': ['/etc/man.conf', 'man.config', 'any/etc/man.conf'],             
     \ 'map': ['file.map'],                                                        
--                                                                                 
2.39.0 

```
From test_filetype.vim:
        Found errors in Test_filetype_detection():
        command line..script /home/ariel/src/neovim/src/nvim/testdir/runtest.vim[437]..function RunTheTest[44]..Test_filetype_detection[2]..CheckItems line 14: with file name: Makefile.inc: Expected 'make' but got 'pov'
```

**Comment by arielp** [comment]
In this particular situation there is no content in the file yet, but  the same thing happens when I open a Makefile.inc file that does have content.

**Comment by zeertzjq** [comment]
The OpenBSD Vim package has a modified version of `filetype.vim`

**Comment by zeertzjq** [comment]
So this should either be a feature request to Vim, or to the OpenBSD neovim package.
