### ISSUE TITLE
window config and plugin error

### ISSUE THREAD

**Issue by ryannewcomer** [neovim/neovim#21889]
### Describe the bug

hi, i just install using winget install id=Neovim.Neovim -e and i run nvim +checkhealth. nothing big error but it said that i miss my config in ~\AppData\Local\nvim/init.vim. but when i go to AppData/Local, there are no nvim dir.
i have rebort my pc
i am on window 11

### Steps to reproduce

nvim --clean
:checkhealth
see:
![image](https://user-images.githubusercontent.com/88273136/213288537-2cecb9c7-b026-457d-a58d-e4ca60495be1.png)

### Expected behavior

i expect that it had a nvim folder for my in AppData\Local

### Neovim version (nvim -v)

NVIM v0.8.2 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compiled by runneradmin@fv-az28-353  Features: -acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM\sysinit.vim"   fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

window 11 home v 22H2

### Terminal name/version

tabby 1.0.188

### $TERM environment variable

nothing

### Installation

winget

**Comment by seandewar** [comment]
Neovim does not create that directory automatically.
