### ISSUE TITLE
Add possibility to "delete other buffers"

### ISSUE THREAD

**Issue by effinsky** [neovim/neovim#21895]
### Problem

I'd like to be able to close all other buffers except for the one I am currently on in a clean way. Currently the only solution I've found is either a 1) [plugin](https://github.com/Asheq/close-buffers.vim)) that did not work in this regard (and this is so basic to window/tab/buffer management that I think it should be basic to what the editor itself can do); 2) or a hacky [command](https://dev.to/believer/close-all-open-vim-buffers-except-the-current-3f6i.) that fails to do it clean cause there's the scratch pad and nvim-tree and what not that may be open and that I'd like to stay open:  I mean this is very dirty stuff.

Thanks for your consideration--

### Expected behavior

I'd like to be able to delete open buffers except for the on I'm currently on. Absolutely equivalent to the Helix command ":bco", or ":buffer-close-others".

<img width="928" alt="Screenshot 2023-01-19 at 08 49 31" src="https://user-images.githubusercontent.com/54535543/213384678-0f39960c-4540-4650-9522-5f9c27470181.png">

**Comment by zeertzjq** [comment]
> there's the scratch pad and nvim-tree and what not that may be open and that I'd like to stay open

Isn't the nvim-tree buffer also "other buffer"?

**Comment by effinsky** [comment]
technicality! I mean this could be worked around with an "ignore" or something like it added to some more native config.

**Comment by lewis6991** [comment]
This isn't something for core. This functionality should be implemented in a plugin. If such plugin passes the threshold of usefulness and quality, it can then be included in core.

**Comment by clason** [comment]
But as it quickly turned out, it's _not_ basic since you also want to set certain exceptions that should be configurable.

**Comment by effinsky** [comment]
It is basic. It may not be trivial to implement, but it is plainly standard to IDE/editor window/tab/buffer management. JetBrains has it. VSCode has it. VS has it. Sublime... probably has it. No matter. Just found a plugin that does just this and so...

If anyone lands here and is looking for something to solve their problem: 
https://github.com/schickling/vim-bufonly

I do think, in closing, that it is not healthy to have to rely on a plugin that does only this. But here we are.

**Comment by bfredl** [comment]
This already exists. `:set hidden` and then `:only`. Done.
