### ISSUE TITLE
Support for cmd key <D-...>?

### ISSUE THREAD

**Issue by norcalli** [neovim/neovim#2190]
I tried searching if this was answered already, but the answers seemed outdated as the new ui system was pulled recently and I didn't see it mentioned in [the wiki](https://github.com/neovim/neovim/wiki/Differences-from-vim#features). Also, searching for "command key" is pretty useless. So has that support been enabled yet (or will it ever)?

**Comment by tarruda** [comment]
We can add support, but if mac misses one of the standard PC modifier keys such as alt or ctrl then it makes sense to reuse it.

**Comment by norcalli** [comment]
I'm not sure I understand what you mean? Reuse which one?

Also I will mention that if `<D-` isn't implemented, then it should be removed from the docs. runtime/doc/intro.txt references it. I'll look into adding a PR myself, but any starting points would be appreciated. I'm not familiar with the code yet.

**Comment by tarruda** [comment]
> I'm not sure I understand what you mean? Reuse which one?

I meant that if mac didnt have alt or ctrl, we could simply send alt or control when command is pressed. But clearly this is not the case.

If you want to send a PR I recommend looking at keymap.c/keymap.h. I guess is that the code for the command key was removed when I first imported vim source code(due to the cleanup of many OSX-specific `#ifdefs`). If so then its just a matter of restoring the removed code.

**Comment by lazywei** [comment]
I would like to be able to use cmd keymap. How is this going?

**Comment by philix** [comment]
> Also I will mention that if <D- isn't implemented, then it should be removed from the docs. runtime/doc/intro.txt references it. I'll look into adding a PR myself, but any starting points would be appreciated. I'm not familiar with the code yet.

<D- is implemented only in MacVim GUI because it doesn't make much sense to use Cmd on the terminal as the Cmd combinations will probably trigger some terminal emulator action.

**Comment by jamischarles** [comment]
Would love to see this supported. One of the primary reasons I use a native GUI is lack of cmd support on the terminal version.

**Comment by norcalli** [comment]
@philix But if it is not difficult to implement in neovim, then the implementor of the GUI will be able to make the decision to override them while still allowing the use of those keymaps in `init.vim`. And as for me, there are only 2 <D-> keymaps that I have in iTerm, and I chose to set those, so I think that isn't a good argument against this.

**Comment by jordwalke** [comment]
Is this seriously not considered important? I consider the ability to map command keys a critical feature.

**Comment by jamischarles** [comment]
@jordwalke I felt the same way until I remapped my command mappings to <leader>*  (space for me). 

Using leader instead of command has felt much more "vim-like" and more natural. After a few hours I didn't miss cmd at all and actually like it better. 

This may not help you, but just wanted to share my experience.

**Comment by jordwalke** [comment]
Thanks. I still feel that command mappings are important for creating MacVim style keybindings which help make Vim more approachable on platforms (Mac OS X). Vim is good enough in its own right to justify a bit of extra work to make integrating into platform paradigms easier.

**Comment by phiche** [comment]
I've been experimenting and fumbling around with vim, tmux and hammerspoon on OSX for a few days now. 

I use still vim in iTerm2 and have discovered some of its limitations, especially in terms of the modifier keys, like cmd and alt/option/meta/+esc, even using tools like Karabiner and Seil.

Seems like vim really only can manage ctrl and shift and I was hoping that neovim might have better support for modern keyboards. 

For what it's worth, this issue has my vote for supporting <D- (and <M- )!

**Comment by jordwalke** [comment]
@phiche: Have you tried MacVim? It's really good, and somehow supports `D-` mappings. I'm wondering why `neovim` cannot.

**Comment by mhinz** [comment]
@jordwalke Because MacVim is always built on the same foundation. For every user. Unfortunately that's not the case for terminal programs, since they have to handle different implementations of terminal emulators, terminfo files, and whatnot.

It's like web development in a world before jQuery.

**Comment by jordwalke** [comment]
@mhinz : Is nvim really a "terminal program"? My understanding that one goal was to be liberated from any particular UI.

**Comment by jordwalke** [comment]
Are there any updates on this?

**Comment by equalsraf** [comment]
Even if terminal handling for Cmd is not working it is worth having D- handling for the GUI. It doesn't even have to be platform specific, i.e. the GUI can be in a Mac and Neovim can be running in a remote Linux machine and D- mappings should work.

A quick grep shows that MOD_MASK_CMD is gone from the source, but it doesn't seem too hard to bring back by looking at the Vim source.

**Comment by chemzqm** [comment]
Would be really nice to have this feature

**Comment by jordwalke** [comment]
Maybe I'm in some kind of a bubble, but approximately 95% of the developers that I see use Macs. I don't think this reflects the general distribution of Mac vs. Linux vs. Windows, but I think there is an incentive for NeoVim to prioritize this. Would it be outrageous to suggest that people who are more likely to use bleeding edge development tooling (as opposed to fully polished VS style IDEs) use Macs?

**Comment by wsdjeg** [comment]
I think this feature works well,but what the difference between `<M-` and `<D-`?

**Comment by justinmk** [comment]
GUI support would be trivial. Help wanted.

**Comment by wsdjeg** [comment]
ubuntu os use `windows key` as default unity hotkty,open application or just open search tool.maybe it will be conflict

![2016-02-21 09 20 08](https://cloud.githubusercontent.com/assets/13142418/13200379/db7f5f1a-d87f-11e5-8fc5-d90b9ea3e57a.png)

`<D-`1-5 Oopen app on the unity tool,
`<D-`d  switch to desktop
`<D-`s   open work space
if just type `<D` will open search tool
![2016-02-21 09 23 09](https://cloud.githubusercontent.com/assets/13142418/13200298/c7d68590-d87c-11e5-8942-130fa7e0a679.png)

**Comment by justinmk** [comment]
@wsdjeg yes, it's up to the user to configure it.

**Comment by wsdjeg** [comment]
thanks,but if it is impletemented,we also can use other hotkey for neovim ,for example `<D-`x or `<D-`z,it will be great.

**Comment by justinmk** [comment]
> For what it's worth, this issue has my vote for supporting `<D-` (and `<M-` )

`<M-` is _fully_ supported in Neovim (terminal and GUIs).

> A quick grep shows that MOD_MASK_CMD is gone from the source

@equalsraf See https://github.com/neovim/neovim/pull/4317

**Comment by wsdjeg** [comment]
nice work !!

**Comment by jordwalke** [comment]
Thanks!

**Comment by teto** [comment]
Great !

**Comment by norcalli** [comment]
Hooray! Glad I asked for this.

**Comment by mskar** [comment]
Does anyone know the terminal escape code for <D-CR>?
I found all the other <CR> combo escape codes:

| KeyCombo       | EscapeCode |
|----------------|------------|
| \<S-CR\>       | [13;2u     |
| \<M-CR\>       | [13;3u     |
| \<M-S-CR\>     | [13;4u     |
| \<C-CR\>       | [13;5u     |
| \<C-S-CR\>     | [13;6u     |
| \<M-C-CR\>     | [13;7u     |
| \<M-C-S-CR\>   | [13;8u     |
