### ISSUE TITLE
setting breakindentopt "list:-1" stops default bri

### ISSUE THREAD

**Issue by swarn** [neovim/neovim#21907]
### Describe the bug

With the following options:

    :lua print(vim.o.bri)               --> true
    :lua vim.pretty_print(vim.o.briopt) --> ""

Both 0.8 and 0.9 have the same behavior:
![no-briopt](https://user-images.githubusercontent.com/926528/213552535-ff4828c7-14f6-4f5c-b161-a60e5b219d2e.png)

Setting `briopt`:

    :lua vim.o.briopt = "list:-1"

neovim 0.8 shows the expected behavior, where it continues with the normal breakindent and adds list indenting
![v0 8-briopt](https://user-images.githubusercontent.com/926528/213553020-30c31295-30f0-4a97-bea5-b81e2176397c.png)

The 0.9 nightly adds list indenting, but loses the normal breakindent:
![v0 9-briopt](https://user-images.githubusercontent.com/926528/213553291-2aad84be-c128-4f30-9b31-2591755f4ec9.png)

### Steps to reproduce

see description

### Expected behavior

see description

### Neovim version (nvim -v)

NVIM v0.9.0-dev-746+g42e9a09a4

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 13.1

### Terminal name/version

iterm

### $TERM environment variable

xterm-256color

### Installation

nightly release tarball

**Comment by lewis6991** [comment]
Are you able to bisect to a specific commit?

**Comment by swarn** [comment]
Sure! It looks like 3e60b9f1cc7a24e801d1ee38b4d03032cc6962f2 is the first commit with the problem.
