### ISSUE TITLE
Passing information from neovim to UI client.

### ISSUE THREAD

**Issue by coolwanglu** [neovim/neovim#2191]
As discussed in https://github.com/coolwanglu/neovim.as/pull/28#issuecomment-83595836

Is there a way of sending information to the UI through colon-commands. In this particular case, we would like something of `set guifont=xxx`, such that UI would receive and response.

For abstract UI, I think that we don't want to define such variables in neovim, but can we have a namespace or something, such that the messages will be passed to UI.

Some proposals:

```
set gui:some_option=some_value
call gui:some_function arg1 arg2
```

**Comment by tarruda** [comment]
You can define an ex command that sets the font using msgpack-rpc calls to the UI. This is basically how remote plugins work and there's even a set vimscript functions that helps with this task. Here's a small patch on top of neovim.as to get you started(I did not test it so you will have to debug any issues):

```diff
diff --git a/src/nvim/nvim.coffee b/src/nvim/nvim.coffee
index 394efb5..8079e65 100644
--- a/src/nvim/nvim.coffee
+++ b/src/nvim/nvim.coffee
@@ -29,6 +29,20 @@ class NVim
     @session.on 'notification', (method, args) =>
       @ui.handle_redraw args if method == 'redraw'

+    @session.on 'request', (method, args, resp) =>
+      if method == 'get-available-fonts'
+        resp.send(['font1', 'font2', 'font3'])
+      else if method == 'set-font'
+        console.log "setting font to #{args[0]}"
+        resp.send(true)
+      else
+        resp.send("Invalid method #{method}", true)
+
+    @session.request 'vim_get_api_info', [], (err, resp) =>
+      channel = resp[0]
+      @session.request 'vim_command', "call remote#define#FunctionOnChannel(#{channel}, 'get-available-fonts', 1, 'GetAvailableFonts', {})", (err, resp) =>
+        @session.request 'vim_command', "call remote#define#CommandOnChannel(#{channel}, 'set-font', 1, 'SetFont', {'nargs': 1, 'complete': 'customlist,GetAvailableFonts'})", (err, resp) =>
+
     @session.request 'ui_attach', [config.col, config.row, true], =>
       @ui.on 'input', (e) =>
         @session.request 'vim_input', [e], ->
```

The `remote#define#{Function,Command}OnChannel functions are distributed as standard nvim plugins. These functions can be used to define vimscript functions and commands that have their implementation over a msgpack-rpc channel.

In the above example, a command and a function are defined:

- `GetAvailableFonts` is a function implemented by the UI with "get-available-fonts"  and returns a list of fonts
- `SetFont` is a command implemented by the UI with "set-font" and will set the font

For more details on how the remote#define#* functions work, you can see the [tests](https://github.com/neovim/neovim/blob/master/test/functional/runtime/autoload/remote/define_spec.lua)

**Comment by norcalli** [comment]
For anyone else who wants to try out that snippet like I did, this is a working version (the original was missing brackets):
```coffee
    @session.on 'request', (method, args, resp) =>
      if method == 'get-available-fonts'
        resp.send(['font1', 'font2', 'font3'])
      else if method == 'set-font'
        console.log "setting font to #{args[0]}"
        resp.send(true)
      else
        resp.send("Invalid method #{method}", true)

    @session.request 'vim_get_api_info', [], (err, resp) =>
      channel = resp[0]
      @session.request 'vim_command', ["call remote#define#FunctionOnChannel(#{channel}, 'get-available-fonts', 1, 'GetAvailableFonts', {})"], (err, resp) =>
        @session.request 'vim_command', ["call remote#define#CommandOnChannel(#{channel}, 'set-font', 1, 'SetFont', {'nargs': 1, 'complete': 'customlist,GetAvailableFonts'})"], (err, resp) =>
```

**Comment by coolwanglu** [comment]
This is really helpful. Thanks!
