### ISSUE TITLE
docs: Parse error for 'lcs' documentation

### ISSUE THREAD

**Issue by Prince213** [neovim/neovim#21917]
### Problem

Documentation: <https://neovim.io/doc/user/options.html#'lcs'>

Source: https://github.com/neovim/neovim/blob/51d082b466c59f739205a6ec0abeeee1281df68b/runtime/doc/options.txt#L3831-L3927

Part of the content is parsed as being in a code block.

### Expected behavior

Lines rendered correctly.

**Comment by clason** [comment]
Easiest to wrap the example list itself into a codeblock. PR welcome!
