### ISSUE TITLE
docs HTML: clickable anchor permalinks

### ISSUE THREAD

**Issue by Prince213** [neovim/neovim#21911]
### Problem

Generated anchors in documentation are not clickable.

https://github.com/neovim/neovim/blob/ef89f9fd46ab591183b7f59f31f5a2e55f7a526b/scripts/gen_help_html.lua#L566

### Expected behavior

It would be nice if we could have a clickable anchor generated, like the line numbers in https://github.com/neovim/neovim/blob/ef89f9fd46ab591183b7f59f31f5a2e55f7a526b/scripts/gen_help_html.lua.

**Comment by dvrd** [comment]
@Prince213 can you be more precise with this issue? I generated the documentation locally with master and all links seem to be working

**Comment by justinmk** [comment]
@dvrd what's expected is that the user can hover over an anchor and get its URL (by clicking on it, so it's essentially a hyperlink).

**Comment by dvrd** [comment]
@justinmk sorry I'm probably missing something. The anchors do get me the url when I click them so I presume is something else. The route you provided me sends you to a header tag with the specified id. What we want if for those headers to be anchors instead?

**Comment by justinmk** [comment]
Go to any other heading on that page and try to get the anchor URL.

**Comment by Prince213** [comment]
@dvrd @justinmk is right. I'm looking for a way to, say, click on a heading and have its URL copied.
