### ISSUE TITLE
nvim_create_autocmd: Add support to pass userdata to the callback function

### ISSUE THREAD

**Issue by cryptomilk** [neovim/neovim#21923]
### Problem

It would be nice if you could pass down userdata, like some options, to the callback when setting up an autocmd with `vim.api.nvim_create_autocmd`.

### Expected behavior

Example:

```lua
mycallback = function(args)
  opts = args.userdata

  if (opts.do_nothing) then
    return
  end
end

myopts = {
  do_nothing = true,
}

vim.api.nvim_create_autocmd(
  'BufReadPre',
  { callback = mycallback, userdata = myopts })
```

Currently you can only do this using a command :-(

**Comment by mfussenegger** [comment]
You could use closures to achieve that:


```lua
mycallback = function(args, opts)
  if (opts.do_nothing) then
    return
  end
end

myopts = {
  do_nothing = true,
}

vim.api.nvim_create_autocmd('BufReadPre', {
  callback = function(args)
    mycallback(args, myopts)
  end,
})
```

**Comment by cryptomilk** [comment]
This works for me thanks!

Could this example be added to the documentation?

**Comment by justinmk** [comment]
this is a common pattern in Lua. we could _link_ to a pattern in `:help lua-guide` or something like that, but we need to avoid cluttering the docs with examples showing standard patterns, it's repetitive and crowds out the more relevant parts of the docs.
