### ISSUE TITLE
Support create operation for workspaceEdit command

### ISSUE THREAD

**Issue by bo-tato** [neovim/neovim#21925]
### Neovim version (nvim -v)

NVIM v0.8.2

### Language server name/version

clojure-lsp 2022.12.09-15.51.10

### Operating system/version

Ubuntu 22.04.1 LTS

### Steps to reproduce using "nvim -u minimal_init.lua"

I used lunarvim which auto installs and configures lsp with mason.nvim and lsp-config. I've tried for a half hour to make a minimal init.lua and haven't managed to to manually configure nvim with lsp and don't have more time to spend on it. It seems though this is clearly from a feature missing in nvim's core lsp implementation and not some issue with lunarvim/lsp-config's configuration of it

### Expected behavior

When receiving `create` operation for `workspaceEdit` command, it should create the file, or prompt for creation, or at least display a message that that operation is unsupported.

### Actual behavior

Just get a lua stacktrace starting with:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:409: method "workspace/applyEdit":
```
see also https://github.com/clojure-lsp/clojure-lsp/issues/1448

### Log file

https://gist.github.com/bo-tato/c0ea62654e98201bc862015686c40152

**Comment by mfussenegger** [comment]
Neovim supports document creation via workspaceEdit. Would need a minimal reproduction to look into this. 

The logs actually indicate missing `window/showDocument` support which was implemented on master.

**Comment by bo-tato** [comment]
I just tried with nightly build of neovim (NVIM v0.9.0-dev-757+g51d082b46) and I have the same error:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:433: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:409: method "workspace/applyEdit": either a result or an error 
must be sent to the server in response
stack traceback:
        [builtin#36]: at 0x559d970bc950
        /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:433: in function </usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:393>
```
Here is complete lsp with log level debug from right before I run the "create test" action: https://gist.github.com/bo-tato/b9f6c6cf7899070fab9b56834184fb54

Here's how I reproduce:
1. start from clojure docker image `docker pull clojure`
2. apt update && apt install unzip build-essential
3. install neovim: `curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.deb > nvim.deb && apt install ./nvim.deb`
4. make normal user account to not be running lunarvim and all plugins as root: `adduser user` and then `su user`
5. run lunarvim install script `bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)`
6. add lvim (lunarvim) to path: `export PATH=/home/user/.local/bin/:$PATH`
7. in lunarvim <space> l I opens up mason info, /clojure-lsp to get cursor on clojure-lsp and i to install it
8. make structure of basic clojure project:
```
mkdir -p foo/src/foo
cd foo
echo '{}' > deps.edn
cat > src/foo/bar.clj <<EOF
(ns foo.bar)

(defn foo [n] n)
EOF
```
9. open with `lvim foo/src/foo/bar.clj` but cursor somewhere in the (defn foo..) form and type space l a to bring up code actions menu
10. select "create test for 'foo'"

**Comment by mfussenegger** [comment]
With Lunarvim you are mostly on your own because it makes lots of changes.

With a minimal reproduction I don't even get a "create test for 'foo'" code action. Instead I get those:

```
Code actions:
1│ Move to let
2│ Cycle privacy
3│ Extract function
4│ Extract to def
5│ Sort list
6│ Drag forward
7│ Introduce let
8│ Clean namespace
```

Here's what I did:


- Download clojure-lsp from https://github.com/clojure-lsp/clojure-lsp/releases/tag/2022.12.09-15.51.10, unpack and put `clojure-lsp` in my `$PATH`
- Create a `minimal.lua`:

```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'clojure',
  callback = function()
    local root_dir = vim.fs.dirname(vim.fs.find({'.git', 'deps.edn'}, { upward = true })[1])
    vim.lsp.start({
      name = 'clojure-lsp',
      cmd = {'clojure-lsp'},
      root_dir = root_dir
    })
  end
})
```

- Create the folder structure and `bar.clj` as described:

```
↪  tree
.
├── foo
│   ├── deps.edn
│   └── src
│       └── foo
│           └── bar.clj
└── minimal.lua
```


- Open `nvim -u minimal.lua foo/src/foo/bar.clj`
- Move cursor into the `defn foo` block and run `:lua vim.lsp.buf.code_action()`

**Comment by bo-tato** [comment]
cool thanks for minimal lsp config, funny debugging story:
1. I use your nvim -u minimal.lua (in the container where I'd just installed lunarvim) and see fine the "create test" action
2. I create a new user "test2" in the container and repeat, and don't see the "create test" action
3. I think lunarvim stores it's config all separate but just to be safe, I delete absolutely everything in /home/user besides foo and minimal.lua, delete all lunarvim, .cache/clojure-lsp, foo/.lsp, delete absolutely everything besides those three files, and check checksums to make sure it is same
4. still "create test" shows up for user "user" but not user "test2", I am really confused
5. after like 30 minutes I realize if clojure-lsp sees test anywhere in the path, it thinks you're in test folder and not src folder, and doesn't present the "create test" option
6. I make new user "user2" and follow your instructions and "create test" option appears

So check you don't have "test" anywhere in your full path, maybe that is why you don't get "create test" action.
here is my clojure-lsp log file: https://gist.github.com/bo-tato/675cc10012844c3217fbaf56c3b05eee

**Comment by mfussenegger** [comment]
Looks like this is an issue with the server. It doesn't provide any workspace edit to apply:

```
.../vim/lsp/rpc.lua:284	"rpc.send"	{
  id = 5,
  jsonrpc = "2.0",
  method = "workspace/executeCommand",
  params = {
    arguments = { "file:///h/u/dummy/foo/src/foo/bar.clj", 2, 6 },
    command = "create-test" 
  }
}
.../vim/lsp/rpc.lua:387	"rpc.receive"	{
    id = 2,
    jsonrpc = "2.0",
    method = "workspace/applyEdit"
  }
.../lua/vim/lsp.lua:1067	"server_request"	"workspace/applyEdit"	nil
.../lua/vim/lsp.lua:1070	"server_request: found handler for"	"workspace/applyEdit"
```

According to the specification the params are mandatory and must contain an edit: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#applyWorkspaceEditParams

**Comment by bo-tato** [comment]
ok I linked this on the clojure-lsp issue: https://github.com/clojure-lsp/clojure-lsp/issues/1448
it's worth mentioning that the "create test" action does work fine in neovim, if a test file (here `foo/test/foo/bar_test.clj`) exists already. It also works fine both creating a new test file or adding test to existing file in emacs. I don't have visual code installed to try. which is why i thought the issue could be with how neovim handles the case where it needs to create a new file

**Comment by mfussenegger** [comment]
Given that https://github.com/clojure-lsp/clojure-lsp/issues/1448 was closed I assume this is solved.
If not - and if there's a client issue -  please add another comment so I can re-open it.
