### ISSUE TITLE
Holding escape crashes Neovim

### ISSUE THREAD

**Issue by mortenbh** [neovim/neovim#21927]
### Describe the bug

On the latest 0.9 nightly holding escape will crash Neovim.

### Steps to reproduce

Start nvim.
Hold escape for approximately 5 seconds until Neovim crashes.
Neovim crashes with the following error message:

nvim: /home/runner/work/neovim/neovim/src/nvim/tui/input.c:729: handle_raw_buffer: Assertion `consumed <= input->read_stream.buffer->size' failed.

### Expected behavior

Neovim does not crash.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-757+g51d082b46

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Debian 11.6

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

Debian package off Github

**Comment by erw7** [comment]
https://github.com/neovim/neovim/issues?q=is%3Aissue+is%3Aopen+handle_raw_buffer+Assertion
