### ISSUE TITLE
neovim randomly crashing back to the shell with no error message

### ISSUE THREAD

**Issue by klebz** [neovim/neovim#21939]
### Describe the bug

hi folks! lately, neovim has been crashing on me, and I am not quite sure why.  

It seems to happen when I scroll down rapidly, especially when reading text written in parts of unicode outside of typical ascii characters.  I'm not 100% sure whether the problem is related to the fast scrolling or the charater sets in the buffer.  

The crash seems to happen sporadically, but most frequently when reading documents containing lots of non-roman alphabetical characters.

Sometimes, it happens when I try to switch to a new buffer or open a file.

Is there a good way for me to get more visibility into the source of the problem?

### Steps to reproduce

unsure -- perhaps load a long document written in greek and try to speed scroll to the bottom

### Expected behavior

I expect no random crashes back to the terminal

### Neovim version (nvim -v)

NVIM v0.9.0-dev-670+g2f1fd1555-dirty

### Vim (not Nvim) behaves the same?

no, version 9.0.217

### Operating system/version

macOS 12.6

### Terminal name/version

alacritty 0.7.2 (5ac8060)

### $TERM environment variable

screen-256color

### Installation

homebrew

**Comment by lewis6991** [comment]
Can you provide a backtrace?

**Comment by klebz** [comment]
it crashes without any backtrace or message.  I just accidentally lost some work.  

I don't remember it crashing at all until I updated neovim version via the system package manager.  

I suppose it is possible that a plugin is the culprit, though I am not sure how to find out.  

What else should I check? Is there a way to wrap the program somehow and capture an error message?

**Comment by dundargoc** [comment]
[This page may help](https://github.com/neovim/neovim/wiki/FAQ#backtrace-macos--osx)

Also, depending on how consistent the crash is, if you can produce an example text (uploaded in a gist perhaps?) that you can recreate the crash on it would help out a lot I think.

**Comment by klebz** [comment]
I just experienced another crash -- I pasted a large block of ascii text from outside neovim into neovim and it crashed.  

I tried the same thing again with the same block of text -- there was no crash.

**Comment by lewis6991** [comment]
We understand and believe it is crashing for you, however we can't act on this without being able to reproduce the issue.

At the very least a backtrace (which you can find via the Console app, under crash reports), will give us some clue to what is causing the issue.

**Comment by klebz** [comment]
```
Date/Time:        2023-01-21 17:27:26.623 -0500
End time:         2023-01-21 17:30:09.645 -0500
OS Version:       macOS 12.6 (Build 21G115)
Architecture:     x86_64h
Report Version:   35.1
Incident Identifier: 51505141-7B56-4EBB-B0ED-290FB9BDA8CB
Share With Devs:  Yes

Data Source:      Microstackshots
Shared Cache:     73669942-BD8A-3E40-951F-7FBE07B51CB8 slid base address 0x7ff805c55000, slide 0x5c55000

Command:          nvim
Path:             /usr/local/Cellar/neovim/HEAD-2f1fd15/bin/nvim
Architecture:     x86_64
Parent:           UNKNOWN [30007]
PID:              30008

Event:            wakeups
Action taken:     none
Wakeups:          45001 wakeups over the last 163 seconds (276 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
Wakeups limit:    45000
Limit duration:   300s
Wakeups caused:   45001
Wakeups duration: 163s
Duration:         163.02s
Duration Sampled: 0.00s
Steps:            1

Hardware model:   MacBookPro15,3
Active cpus:      16
HW page size:     4096
VM page size:     4096
Boot args:        chunklist-security-epoch=0 -chunklist-no-rev2-dev

Fan speed:        2156 rpm
Advisory levels:  Battery -> 3, User -> 2, ThermalPressure -> 0, Combined -> 2
Free disk space:  46.99 GB/931.55 GB, low space threshold 3072 MB
Low Power Mode:   Enabled

Heaviest stack for the target process:
  1  ??? (libluajit-5.1.2.1.0.dylib + 14006) [0x10884f6b6]
  1  nlua_api_nvim_eval + 334 (nvim + 107177) [0x1082732a9]
  1  api_free_object + 13 (nvim + 236116) [0x108292a54]


Powerstats for:   nvim [30008] [unique pid 228880]
UUID:             8E0313AF-F83E-306C-A96A-6B8E26C959BA
Path:             /usr/local/Cellar/neovim/HEAD-2f1fd15/bin/nvim
Architecture:     x86_64
Parent:           UNKNOWN [30007]
UID:              501
Footprint:        56.28 MB
Start time:       2023-01-21 17:28:32.699 -0500
End time:         2023-01-21 17:28:32.699 -0500
Num samples:      1 (100%)
Primary state:    1 samples Non-Frontmost App, Non-Suppressed, User mode, Effective Thread QoS Default, Requested Thread QoS User Interactive, Override Thread QoS Unspecified
User Activity:    0 samples Idle, 1 samples Active
Power Source:     0 samples on Battery, 1 samples on AC
  1  ??? (libluajit-5.1.2.1.0.dylib + 14006) [0x10884f6b6]
    1  nlua_api_nvim_eval + 334 (nvim + 107177) [0x1082732a9]
      1  api_free_object + 13 (nvim + 236116) [0x108292a54]

  Binary Images:
           0x108259000 -        0x10856cfff  nvim (0)                      <8E0313AF-F83E-306C-A96A-6B8E26C959BA>  /usr/local/Cellar/neovim/HEAD-2f1fd15/bin/nvim
           0x10884c000 -        0x1088b7fff  libluajit-5.1.2.1.0.dylib (0) <001A2D73-12C3-35F1-8BB5-779985511076>  /usr/local/Cellar/luajit/2.1.0-beta3-20221208.2/lib/libluajit-5.1.2.1.0.dylib
```

**Comment by lewis6991** [comment]
> nlua_api_nvim_eval + 334 (nvim + 107177)

My guess is that a plugin is causing this.

Neovim should never crash though so we should try and figure out what's going on.

**Comment by klebz** [comment]
thanks for helping me

**Comment by klebz** [comment]
are there any other logs we might be able to check? I saw this one under `diagnostics` in the console

**Comment by klebz** [comment]
currently, it is crashing every time I try to paste several large blocks of text into the buffer while in insert mode.

I havn't been able to predict *which* paste will cause the crash, but the fact that *a* paste causes a crash is nearly guaranteed.  I just keep on pasting and then the crash gets triggered.

**Comment by klebz** [comment]
i just hit a case where i opened the editor on a certain file, navigated to the bottom of the buffer, entered insert mode, and pasted a block of text.

this crashed.


then, i did the exact same thing again and there was no crash

**Comment by lewis6991** [comment]
It could be a plugin running `vim.cmd(...)` on a `TextChanged` autocmd.

**Comment by lewis6991** [comment]
Can you get a backtrace from the "crash report" section in Console?

**Comment by klebz** [comment]
I actually don't see a backtrace in the `crash report` section of `console`

I bet the culprit is a plugin, though I'm not totally familiar with neovim plugin debugging methods

**Comment by klebz** [comment]
I suppose I may be able to binary toggle my config a few times to try and narrow it down, in case it is a pluign

**Comment by zeertzjq** [comment]
Your version is a week old. Try latest HEAD.

**Comment by klebz** [comment]
ok -- i am currently building and installing neovim from source instead of homebrew

**Comment by klebz** [comment]
great news -- it looks like the latest HEAD may have fixed the problem.

closing for now.  I will give it a test run and see if there is anything else which causes a crash.

thanks all for the help 🙏

**Comment by klebz** [comment]
quick update: everything seems to be working properly now 🎉

Thanks for the help
