### ISSUE TITLE
Problem with BufWinLeave

### ISSUE THREAD

**Issue by unphased** [neovim/neovim#2194]
I have an autocommand

```
au BufWinLeave *.php mkview
```

This does not appear to be called (when it appears like it should be) when I have various php files opened in other tabs and `:qa` neovim.

**Comment by justinmk** [comment]
does it happen in Vim? Also, need more info.

**Comment by unphased** [comment]
Hmm so I think the issue is with this: 

    au BufWinEnter *.php silent loadview

what Vim does is it doesn't error when the view file isn't there.

**Comment by kopischke** [comment]
AFAIK the original report is known and (obliquely) documented Vim behaviour: as noted in [this thread](https://github.com/kopischke/vim-stay/issues/5), `BufWinLeave` can fire when the window has already been destroyed. As `mksession` is window based, it fails in these situations. *vim-stay* also uses `BufLeave` to catch these, but that is not fired on `qa`, so one will have to see if adding `VimLeavePre` to the mix fills the gap.

**Comment by justinmk** [comment]
VimLeavePre should be sufficient.
