### ISSUE TITLE
vim.diagnostic.open_float does not work for lines after first one in multi-line diagnostics

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#21949]
### Describe the bug

If you have a multi-line diagnostic, `vim.diagnostic.open_float` works on the first line but fails on the subsequent lines.

### Steps to reproduce

1. In `nvim --clean`, open a new buffer and paste the following contents.
```
local ns = vim.api.nvim_create_namespace('diagnostics')
vim.diagnostic.reset(ns, 0)
vim.diagnostic.set(ns, 0, { {
  lnum = 0,
  col = 0,
  end_lnum = 2,
  end_col = 0,
  message = 'Two-line diagnostic'
} })
```
2. Save it
3. Source it
4. Observe that the first two lines are underlined
5. Observe that `:lua vim.diagnostic.open_float` works on the first line.
6. Observe that `:lua vim.diagnostic.open_float` does not work on the second line.

### Expected behavior

`vim.diagnostic.open_float` should work anywhere inside the diagnostic.

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux 5.19.9

### Terminal name/version

xfce4-terminal 1.0.4

### $TERM environment variable

tmux-256color

### Installation

system package manager

**Comment by halafi** [comment]
<img width="1100" alt="lsp" src="https://user-images.githubusercontent.com/5550440/230542438-360290e4-9c5d-4880-9a47-b6fb2657e768.png">

I can confirm this, for example https://git.sr.ht/~whynothugo/lsp_lines.nvim plugin does show the whole text

not sure what is going on

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local
```

**Comment by zyriab** [comment]
Hi there, I had the same issue and it turned out that it was a problem coming from `nvim-notify` needing me to specify all of the properties in its `setup` function.
If you are using that plugin, it might be your problem as well. Note that I'm using it with `noice` as well.

Here's a call with all default values specified.

```lua
notify.setup({
    level = vim.log.levels.INFO,
    timeout = 5000,
    max_width = nil,
    max_height = nil,
    stages = "fade_in_slide_out",
    render = "default",
    background_colour = "NotifyBackground",
    on_open = nil,
    on_close = nil,
    minimum_width = 50,
    fps = 30,
    top_down = true,
    time_formats = {
        notification_history = "%FT%T",
        notification = "%T",
    },
    icons = {
        ERROR = "",
        WARN = "",
        INFO = "",
        DEBUG = "",
        TRACE = "✎",
    },
})
```
