### ISSUE TITLE
add vim.clipboard.{get,set} ?

### ISSUE THREAD

**Issue by teto** [neovim/neovim#21952]
### Problem

The vimscript api is a bit terse IMO:
```
vim.cmd("call provider#clipboard#Call('set', [ ['".. content .."'], 'v','\"'])")
```

### Expected behavior

It could be nice to be able to run `vim.clipboard.set({ "toto"})` with the autogenerated help.

**Comment by justinmk** [comment]
`vim.call['provider#clipboard#Call']` ?

**Comment by justinmk** [comment]
Tracked by https://github.com/neovim/neovim/issues/27119
