### ISSUE TITLE
[bug] [vim] Inconsistency with virtualedit=onemore $ and g$ in NORMAL vs VISUAL.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2195]
With `set virtualedit=onemore`, `$` takes me to the last character in NORMAL, not past it, but in VISUAL `$` takes me past the last char just like `g$` does.

Basically, `$` and `g$` work as expected in NORMAL, but in VISUAL `$` behaves like `g$`.

Also, when I `set virtualedit=""`, `$` and `g$` both take me to the last character and it's not possible to move past the last char, but in VISUAL `$` and `g$` still go past the last char.

I feel like the expected behavior would be for VISUAL `$` and `g$` to act just like NORMAL, depending on the virtualedit setting.

**Comment by justinmk** [comment]
Please report to https://code.google.com/p/vim/issues/list.

**Comment by justinmk** [comment]
> I feel like

Is this a bug or a feature request?

**Comment by chrisbra** [comment]
Hi Joseph!

On Do, 19 Mär 2015, Joseph Orbegoso Pea wrote:

> With `set virtualedit=onemore`, `$` takes me to the last character in NORMAL, not past it, but in VISUAL `$` takes me past the last char just like `g$` does.
> 
> Basically, `$` and `g$` work as expected in NORMAL, but in VISUAL `$` behaves like `g$`.
> 
> Also, when I `set virtualedit=""`, `$` and `g$` both take me to the last character and it's not possible to move past the last char, but in VISUAL `$` and `g$` still go past the last char.
> 
> I feel like the expected behavior would be for VISUAL `$` and `g$` to act just like NORMAL, depending on the virtualedit setting.
> 

I believe this is no bug but expected behaviour. I think this was made 
so, to enable the user to selectively select the newline after the line.

Best,
Christian
-- 
Liebe ist ein Zeitwort, ein Verhältniswort, ein Zahlwort oder ein
Umstandswort - je nachdem.
		-- Orson Welles

**Comment by justinmk** [comment]
Thanks @chrisbra

**Comment by trusktr** [comment]
I believe this is a bug in the design, not in the code. But nonetheless, if it's intended, it might be worth keepin gthe same, though I wouldn't mind having consistent behavior at all.

**Comment by trusktr** [comment]
Made an issue there to see what people think. https://code.google.com/p/vim/issues/detail?id=344&thanks=344&ts=1426823426

@chrisbra I understand what you mean, and I feel virtualedit=onemore is the perfect solution for those (rare) people who want to select the new line and want to stay closer to CUA than learn vim maximally.

**Comment by trusktr** [comment]
Also, for those people, `g$` should work just fine. `$` should still go to the last char.

**Comment by justinmk** [comment]
@trusktr The current behavior drives me nuts as well, but changing it will break stuff. I think adding a "line" text object (`yil`, `c_CTRL-R_CTRL-L`) would solve most of the use cases where I don't want the EOL selected.

**Comment by trusktr** [comment]
I could see a line object beneficial when you want to copy/paste a line into an IRC chat, for example, without causing two lines to be sent.
