### ISSUE TITLE
Extend `format` option of `vim.diagnostic.open_float` with highlighting support

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#21954]
Analogous to the `prefix` and `suffix` options of `vim.diagnostic.open_float`, it would be great if the `format` callback could return an array of chunks (similar to `nvim_echo`) that specifies highlights for different parts of the text. If a string is returned, `floating_highlight_map[diagnostic.severity]` is applied (current behavior).

This would be especially helpful for displaying diagnostics that contain things like diffs where you want to apply different highlighting in the diff to make it easier to read.

**Comment by ddickstein** [comment]
Wait is this request just silly actually? Can I just achieve what I want by directly calling `nvim_buf_add_highlight` on the returned buffer?

**Comment by tom-anders** [comment]
@ddickstein What was the solution you came up with?
