### ISSUE TITLE
Ability to mimic client-server architecture of kakoune

### ISSUE THREAD

**Issue by jam1015** [neovim/neovim#21963]
### Problem

In kakoune you can start the text editor and specity a server name; you can then attach to the same server from a different ui and have the same buffers.  This lets us rely on tmux/window managers to deal with multiple files rather than the built-in neovim splits; they are OK but it is more elegant to have fewer tools that do the same thing.

### Expected behavior

In kakoune we can go `kak -s S1 ~/.bashrc ~/.zshrc` and then `kak -c S1 ~/haha.md`

then in both instances `~/.bashrc` `~/.zshrc` and `~/haha.md` are all in the buffer list and you can edit the same file from different sessions and it is updated, and you can also edit different files from the different sessions; but the buffer list is always shared.

I would like similar functionality in neovim.

**Comment by justinmk** [comment]
this is already possible in Nvim 0.9 (unreleased)

     :help --listen
     nvim --server ... --remote-ui

(`--remote-ui` might be removed, then just `--server` will work)

**Comment by jam1015** [comment]
Just tried it in neovim 0.9 [installed from the Arch User Repository] and it does not implement it in the same way that I am requesting; sorry for being a choosing beggar over here I know you all work so hard;

in one tmux split I run `nvim --listen /tmp/nvim.pipe ~/.zshrc ~/.bashrc`  and the two buffers are open as expected. 

then in another  tmux split I run `nvim --server /tmp/nvim.pipe --remote-ui` and yes a vim instance opens up with bashrc and my zshrc as buffers; and here is where it doesn't do what I want; the two tmux panes mirror each other. If I switch buffers in one tmux pane, it switches buffers in the other.  I should be able to enter `:bn` in one split to edit the other file, but the file in the other split should not change; and if I issued the command `:e ~/haha.md` in one split, `haha.md` should be added to the buffer list in the other split, but the file should not come up.

**Comment by zeertzjq** [comment]
This looks similar to #19502

**Comment by jam1015** [comment]
> This looks similar to #19502

yes that seems like what that feature request is about; I'm just more explicit about what each neovim instance acting like a `window` means.  I guess the roadmap for me is to get good enough at coding to see how they do it in kakoune and making a pr here, which I know is a herculean task.  would want to implement this for the TUI rather than find a GUI client that does this (if one exists/if it is possible) because the whole reason I use a command line text editor is to get away from GUIs.

**Comment by glacambre** [comment]
This is actually a very old feature request: https://github.com/neovim/neovim/issues/2161 :)

**Comment by justinmk** [comment]
yes this is a duplicate

**Comment by jam1015** [comment]
Hi! Thanks for everyone's consideration of this issue.   Wondering if you might re-open this or one of the duplicates; one of them is closed as 'off topic' and the other one is closed as 'complete' .

**Comment by glacambre** [comment]
@jam1015 Why isn't #2161 sufficient? It's still open.

**Comment by jam1015** [comment]
the conversation is locked

**Comment by bfredl** [comment]
Maybe because the feature request does not need to be repeated.

**Comment by glacambre** [comment]
No, closed means that there is no action item to do for Neovim's maintainers, open with conversation locked means that there are still things to do but that too many people have asked for updates on the feature's implementation.

**Comment by jam1015** [comment]
Making note that https://github.com/jbyuki/instant.nvim seems to make a start of implementing a feature like this; specifically you can share buffers between separate instances on the same machine through the server; not exactly like different windows being the same instance.
