### ISSUE TITLE
Error detected while processing nvim_exec() | Rose-pine colorscheme

### ISSUE THREAD

**Issue by rahulchahal01** [neovim/neovim#21962]
### Describe the bug

""""  Error detected while processing nvim_exec() called at /home/pirate/.loca
l/share/nvim/site/pack/packer/start/rose-pine/colors/rose-pine.lua:0:
W18: Invalid character in group name
W18: Invalid character in group name 
-----more------    """

I got this error whenever I open nvim or nvim-explorer window and even the default path of nvim-explorer is the top-level directory ( I mean root filesystem " /").  Btw this happens after installing or using the rose-pine colour scheme but the color scheme works as intended. 

And use packer.nvim as a plugin manager
  

### Steps to reproduce

~/.local/share/nvim/site/pack/packer/start/rose-pine/colors/rose-pine.lua

package.loaded['rose-pine.palette'] = nil 
require('rose-pine').colorscheme()

~ /.config/nvim/lua/therahulchahal/packer.lua
  
use({
        'rose-pine/neovim',
         as = 'rose-pine',
         config = function()
             require("rose-pine").setup()
             vim.cmd('colorscheme rose-pine')
        end
  })

### Expected behavior

Am looking forward to solving this program without upgrading nvim version!!!!!!

### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

Not Sure!

### Operating system/version

Wsl2 (Kali linux)

### Terminal name/version

Windows Terminal

### $TERM environment variable

???

### Installation

Kali Linux distribution

**Comment by clason** [comment]
Neovim 0.7.2 is outdated, please try 0.8.2 (or better yet, nightly).

**Comment by rahulchahal01** [comment]
Is there anyway to solve it Or Easy way to install new version of nvim

**Comment by zeertzjq** [comment]
You can also install an older version of the plugin

https://github.com/rose-pine/neovim/issues/103
