### ISSUE TITLE
Possible conflicts in docs of nvim_create_autocmd and nvim_exec_autocmds

### ISSUE THREAD

**Issue by lucario387** [neovim/neovim#21964]
### Problem

`nvim_exec_autocmds()` docs wrote the `data` attribute to be
```
                 • data (any): arbitrary data to send to the autocommand
                   callback. See |nvim_create_autocmd()| for details.
```
Which implies nvim_exec_autocmds will pass data to autocmd callback, and that there is a key of nvim_create_autocmd that will represent the sent data
But `nvim_create_autocmd()` docs wrote that
```
                   • data: (any) arbitrary data passed to
                     |nvim_exec_autocmds()|
```
Which implies the data field here is passing data to nvim_exec_autocmds, and there is no mention in the docs of which key will be receiving the data from `nvim_exec_autocmds` 

### Expected behavior

I suggest the `data` field of `nvim_create_autocmd` to be changed to
```
data (any) arbitrary data received from |nvim_exec_autocmds()|
```

**Comment by clason** [comment]
To my (admittedly non-native) ear, the current description sounds correct, though: you pass an argument _to_ a function (in this case, `nvim_exec_autocmds()`). And the docs make it quite clear that the key is `data`?

**Comment by lucario387** [comment]
Agreed that and it's clear `data` is the key that is responsible for arguments passed to callback, I could've worded it better.
From my viewpoint, I read the `passed to` as `data that is passed to something`, when here it is the one receiving the data, which makes the `passed to` sounded a bit off

**Comment by clason** [comment]
This is short for "data that was passed to".

**Comment by lucario387** [comment]
> This is short for "data that was passed to".

Then shouldn't it be "data that was passed to by nvim_..." to be more clear?
"passed to" in your understanding, I still find it to have more the meaning of "it giving data" than "it receiving data"

**Comment by lewis6991** [comment]
I agree the wording in `nvim_create_autocmd` isn't the best.

Would this be enough?

```diff
- data: (any) arbitrary data passed to
+ data: (any) arbitrary data passed from
|nvim_exec_autocmds()|
```
