### ISSUE TITLE
E5113: Remap the "Ex" cmd and got attempt to index field 'cmd" error!!!

### ISSUE THREAD

**Issue by rahulchahal01** [neovim/neovim#21960]
### Describe the bug

" Error detected while processing /home/pirate/.config/nvim/init.lua:
"""  E5113: Error while calling lua chunk: /home/pirate/.config/nvim/lua/therahulchahal/remap.lua:2: attempt to index field 'cmd' (a function value)
stack traceback:
        /home/pi****/.config/nvim/lua/therahulchahal/remap.lua:2: in main chunk
        [C]: in function 'require'
        /home/pi****/.config/nvim/lua/therahulchahal/init.lua:2: in main chunk
        [C]: in function 'require'
        /home/pirate/.config/nvim/init.lua:1: in main chunk   """

I tried to remap  ":Ex"  cmd with the leader key and "ps" and got this error!

I'm new to this!!!
 

### Steps to reproduce

--  ~/.config/nvim/lua/therahulchahal/remap.lua

vim.g.mapleader  =  "  "
vim.keymap.set("n",  "<leader>pv",  vim.cmd.Ex)

### Expected behavior

So, I can use the leader key("space") + "pv" to execute ":Ex" cmd and reach into nvim explorer window.

### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

Not Sure!

### Operating system/version

Wsl2 (Kali linux)

### Terminal name/version

Windows Terminal

### $TERM environment variable

???

### Installation

Kali Linux distribution

**Comment by zeertzjq** [comment]
You version is too old. You need at least v0.8.0 to index `vim.cmd`.

**Comment by rahulchahal01** [comment]
Thank mate, Btw do I need to remove this version first??

**Comment by zeertzjq** [comment]
In v0.7.2 you can use this instead:
```lua
vim.keymap.set('n', '<Leader>pv', function()
  vim.cmd('Ex')
end)
```

**Comment by rahulchahal01** [comment]
It works! 👍
