### ISSUE TITLE
Different background colour (or other colour settings?) for individual windows

### ISSUE THREAD

**Issue by monotasker** [neovim/neovim#2196]
One thing that I've seen several people trying to do with old vim is set different background colours for different windows. This would allow, for example:

- a "drawer" or "sidebar" window to be quickly recognizable (as in many ide ui's)
- the background colour could be dimmed slightly for inactive windows (again, as in many ide's)

At the moment, though, this is impossible in vim because the background colour is a global setting. Since we're looking at a new vim, could we allow for this?

I assume it would be accomplished by allowing the background colour to be set on a per/window basis. A more far-reaching approach would be to allow setting *all* colours on a per/window basis. This would allow, e.g., using different colour schemes for different languages, since schemes often support some languages better than others.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/1457
