### ISSUE TITLE
Allow setting colours in foldtext

### ISSUE THREAD

**Issue by monotasker** [neovim/neovim#2197]
One thing that has frustrated me is that I can't adjust the colours of the foldtext when I've folded a section. This would make it possible to write plugins that would, e.g.:
- distinguish folded comments from folded code chunks by colour
- distinguish the hierarchical level of the fold in hierarchically structured documents by colouring the foldtext in keeping with the colour of its hierarchical heading level (XML, HTML, Markdown, etc.)
- distinguish folded classes from folded methods by colour
- etc.

In classic vim, though, all I can do is set the background colour for the foldtext line, and it has to be set globally.

**Comment by lewis6991** [comment]
Closing this as a dup of #12649, which whilst newer, has more activity.
