### ISSUE TITLE
Building neovim fails on voidlinux

### ISSUE THREAD

**Issue by baleksa** [neovim/neovim#21982]
### Describe the bug

With and after commit #21926 building deps for neovim on glibc voidlinux fails. Before suceeds.
The last working commit is #21975 ( fca3933 ).
I always `make distclean` before building.
Build error:
```
[84/121] Performing build step for 'libtermkey'
FAILED: build/src/libtermkey-stamp/libtermkey-build /home/baleksa/repositories/neovim/.deps/build/src/libtermkey-stamp/libtermkey-build
cd /home/baleksa/repositories/neovim/.deps/build/src/libtermkey-build && /usr/bin/cmake --build . && /usr/bin/cmake -E touch /home/baleksa/repositories/neovim/.deps/build/src/libtermkey-stamp/libtermkey-build
ninja: error: '/home/baleksa/repositories/neovim/.deps/usr/lib/libunibilium.a', needed by 'test_01base', missing and no known rule to make it
```

### Steps to reproduce

```
git clone https://github.com/neovim/neovim
cd neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
```

### Expected behavior

Building neovim suceeds.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-795+gfca39eeab

### Vim (not Nvim) behaves the same?

i don't have vim installed

### Operating system/version

voidlinux 6.1.7_1

### Terminal name/version

wezterm 20221119-145034-49b9839f

### $TERM environment variable

wezterm

### Installation

build from repo

**Comment by lewis6991** [comment]
@baleksa: Can you confirm this occurs with a clean checkout?

@dundargoc: Could this be caused by the recent cmake change to unibilium?

**Comment by dundargoc** [comment]
Thanks for the report. I can recreate it with docker: https://github.com/dundargoc/docker-neovim/blob/master/void/non-functional/Dockerfile. Will look into it.

**Comment by baleksa** [comment]
You're welcome. Good luck with that!

**Comment by dundargoc** [comment]
Can you test https://github.com/neovim/neovim/pull/21983 and check that it works for you?

**Comment by baleksa** [comment]
Yes, it works! Thank you!
