### ISSUE TITLE
vscode-neovim: Undo and Redo is not consistent

### ISSUE THREAD

**Issue by tyctor** [neovim/neovim#21988]
### Describe the bug

when i do undo with many steps and after i do redo to last version i dont get same code

somewhere is added line, somewhere is added character...

### Steps to reproduce

- open file 
- do lot of changes (pres `u` for about 10 seconds and do redo back)
- undo to start
- redo to end

version will be not same

### Expected behavior

same version after all undo and redo steps

### Neovim version (nvim -v)

nvim -v NVIM v0.8.1

### Vim (not Nvim) behaves the same?

no, vim 9.0.1

### Operating system/version

gentoo linux

### Terminal name/version

vscode

### $TERM environment variable

xterm-color

### Installation

gentoo ebuild

**Comment by justinmk** [comment]
steps provided here are not sufficient. I tried with `nvim --clean` and diff'd the result, it is identical.

**Comment by tyctor** [comment]
ok, may i ask how many undo steps you did, and how fast?

for me it happend when i press `u` and hold for 15 seconds, and after i did redo back

**Comment by justinmk** [comment]
> for me it happend when i press `u` and hold for 10 seconds, and after i did redo back

was that mentioned in the repro steps?

**Comment by bfredl** [comment]
does "terminal: vscode" rather mean embedding nvim using vscode-nvim or similar?

**Comment by tyctor** [comment]
> > for me it happend when i press `u` and hold for 10 seconds, and after i did redo back
> 
> was that mentioned in the repro steps?

updated steps

**Comment by tyctor** [comment]
> does "terminal: vscode" rather mean embedding nvim using vscode-nvim or similar?

yes it is neovim in vscode

**Comment by justinmk** [comment]
@tyctor are you able to reproduce the issue in other terminal(s) (not vscode)?

**Comment by tyctor** [comment]
> @tyctor are you able to reproduce the issue in other terminal(s) (not vscode)?

in terminal i am using only vim, do you think that it is somehow related to vscode ?
probably i should post this to vscode-neovim

**Comment by tyctor** [comment]
created issue on [vscode-neovim](https://github.com/vscode-neovim/vscode-neovim/issues/1139)

**Comment by justinmk** [comment]
> in terminal i am using only vim, do you think that it is somehow related to vscode ?

i don't understand the question. Your system has a terminal that isn't the vscode terminal, right? Can you just run `nvim` in that terminal and check if the issue is present there?

**Comment by justinmk** [comment]
oh, so this was not `nvim` running in the vscode terminal, rather you are reporting an issue with the https://github.com/vscode-neovim/vscode-neovim embedeed nvim integration.

https://github.com/vscode-neovim/vscode-neovim has a known issue with synchronizing input in some cases, _especially_ if you are redoing _insert mode_ edits. 

https://github.com/vscode-neovim/vscode-neovim/issues/269

https://github.com/vscode-neovim/vscode-neovim/pulls?q=is%3Apr+insert+repeat+is%3Aclosed

https://github.com/vscode-neovim/vscode-neovim/pull/948

related: https://github.com/neovim/neovim/issues/19806
