### ISSUE TITLE
Apply CurSearch highlight to single char search

### ISSUE THREAD

**Issue by kassio** [neovim/neovim#21993]
### Describe the bug

When searching for a single char, the `CurSearch` is not applied:

https://user-images.githubusercontent.com/120483/214584486-cb371f25-d312-4481-909b-e43607f8d88d.mp4

### Steps to reproduce

minimal init.lua

```lua
vim.opt.termguicolors = true

vim.api.nvim_set_hl(0, 'Search', { bg = '#ffff00', fg = '#000000' })
vim.api.nvim_set_hl(0, 'IncSearch', { bg = '#ffff00', fg = '#000000' })
vim.api.nvim_set_hl(0, 'CurSearch', { bg = '#ff00ff', fg = '#000000', italic = true, bold = true })
```

### Expected behavior

use the correct `CurSearch`

### Neovim version (nvim -v)

NVIM v0.9.0-dev-801+gc6ab8dfc1-dirty

### Vim (not Nvim) behaves the same?

-

### Operating system/version

macos 13.2

### Terminal name/version

iterm2 (Build 3.4.19)

### $TERM environment variable

xterm-256color

### Installation

brew --HEAD

**Comment by zeertzjq** [comment]
Why should it be applied?

**Comment by kassio** [comment]
I'd expect the `CurSearch`, based on the documentation: `Used for highlighting a search pattern under the cursor` regardless of its size. IMHO it should have higher priority than the cursor, like it seems to have when the search has more than 1 char.

**Comment by justinmk** [comment]
was this an intentional vim decision? please send this request to https://github.com/vim/vim
