### ISSUE TITLE
wiki: existance of latest stable and nightly Debian packages not mentioned in Debian section of Install page

### ISSUE THREAD

**Issue by tim-seoss** [neovim/neovim#21990]
I couldn't see a way to open a PR on the wiki content, so I created a patch instead.  Hope that's OK, if-not, please let me know...

I think it would be useful if the Debian section of the Install page wiki mentioned that binary debs for the latest stable, and also nightly releases are available and built automatically as part of the neovim release process.

Github doesn't seem to want to let me attach my patch (despite saying that it will), so here's the edited markdown, along with a the contents of the patch inline...

```diff
diff --git a/Installing-Neovim.md b/Installing-Neovim.md
index d13dfc6..22f2414 100644
--- a/Installing-Neovim.md
+++ b/Installing-Neovim.md
@@ -170,6 +170,8 @@ Python (`:python`) support is installable via the package manager on Debian unst
 
     sudo apt-get install python3-neovim
 
+Alternatively, Neovim also provides binary Debian packages (currently x86-64 only) - see the [Install from download](#install-from-download) section.
+
 If installing via appimage, the following commands may be helpful in updating default paths:
 
     # CUSTOM_NVIM_PATH=/usr/local/bin/nvim.appimage
```
[Installing-Neovim.md](https://github.com/neovim/neovim/files/10498021/Installing-Neovim.md)
[edit: rework to point to "Install from download" section of the wiki page]

**Comment by dundargoc** [comment]
Added. Thank you.
