### ISSUE TITLE
Mouse click not working on latest version of macbook air M1, ventura 13.1

### ISSUE THREAD

**Issue by toytown** [neovim/neovim#21992]
### Describe the bug

With default settings in NvimTree the mouseclick opens the folder or files . However, this does not work on Macbook Air M1 , Ventura 13.1. Same settings work on Macbook Pro, with OS Monterey v 12.6.2. Settings are described below. Issue should be reproducible 

1. Install nvim on macbook air  M1, Ventura 13.1 with  settings below --> Mouse click wont work
3. Install nvim on macbook pro, Monterey 12.6 with  settings below  --> Mouse click would work with nvimTree

the setting are here https://github.com/toytown/macos/tree/main/nvim

### Steps to reproduce

1. Install neovim on MacOS (Macbook M1) ventura 13.1 using 
    brew install neovim
2. Install NvimTree plugins using settings described https://github.com/toytown/macos/tree/main/nvim
3. Check the mouse-click action on NVimTree
4. Mouse click would have no effect
5. Repeat the same on macos Monterey v 12.6.2.
6. Mouse click would work this time

### Expected behavior

Mouse click should open close folder or files. Although it is seen in Nvimtree it is possibly some OS related issue with Neovim

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

macos ventura 13.1

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256-color

### Installation

brew install neovim

**Comment by justinmk** [comment]
not going to debug your plugins. 

since you're using iterm2, it would be related to some configuration or change there. 

> Vim (not Nvim) behaves the same?
> yes

that is more evidence that this is not a nvim bug.
