### ISSUE TITLE
Open file with line number

### ISSUE THREAD

**Issue by 0guanhua0** [neovim/neovim#22013]
### Problem

```
$ nvim <file>:<line number>
```
open the `<file>:<line number>` instead of jumping to line number

### Expected behavior

jump to line number like [vim-fetch](https://github.com/wsdjeg/vim-fetch)

**Comment by glepnir** [comment]
first please don't broken  issue template.  you can use `nvim file -c 'line number'`

**Comment by justinmk** [comment]
Duplicate of https://github.com/neovim/neovim/issues/1281

I do agree that this feels like it should be a builtin, but someone needs to work out the details. Probably need a handler/provider/'foofunc' interface that handles file fetching.
