### ISSUE TITLE
Flag emojis display as squares

### ISSUE THREAD

**Issue by llimllib** [neovim/neovim#22014]
### Describe the bug

Given this text file as `t.txt`:

```
* 🇺🇸 
* 🇰🇷 
```

on mac ventura, neovim displays the flag emojis incorrectly on `iterm2` and `terminal.app`, but correctly on `kitty`.

`iterm` and `terminal.app` themselves have no trouble displaying the emoji.

`nvim -u none t.txt` (v0.8.2 from homebrew) on `iterm` (3.4.19, the latest as of right now), looks like this:

<img width="110" alt="image" src="https://user-images.githubusercontent.com/7150/214989943-91e6dca8-7a98-4c12-9fe1-3f6e3a3e439c.png">

while `cat t.txt` shows it properly:

<img width="106" alt="image" src="https://user-images.githubusercontent.com/7150/214990370-2b4cfe7f-8754-46b9-bd77-b8d47ca8f1d1.png">

`nvim -u none t.txt` on `terminal.app` looks similarly:

<img width="56" alt="image" src="https://user-images.githubusercontent.com/7150/214990567-853096f2-d693-4a4f-a3bd-184eb8b2d031.png">

but on kitty (0.26.5), it works properly:

<img width="69" alt="image" src="https://user-images.githubusercontent.com/7150/214990961-c7a040a5-1e89-4036-9c4a-1baa978a33a0.png">

I tried a few `TERM` values, as I noticed kitty had `TERM=xterm-kitty`, but nvim on iterm failed with `TERM` set to all of: `ansi-256color`, `xterm-256color`, `xterm-kitty` and `xterm-new`

I reproduced this behavior on a second macbook with the same versions of these softwares.

All of these programs also display the flags correctly in iterm: `bat`, `nano`, `emacs`, `helix`

`TextEdit`, `code` and `VimR` do as well

### Steps to reproduce

1. edit a file with neovim 0.8.2 that contains flag emojis on mac ventura, with iterm 3.4.19

### Expected behavior

I expect it to show flag emojis

### Neovim version (nvim -v)

NVIM v0.8.2

### Vim (not Nvim) behaves the same?

yes, version 9.0

### Operating system/version

macOS 13.1 ventura

### Terminal name/version

iterm 3.4.19, see above for further details

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
Related: #7151

**Comment by llimllib** [comment]
If you have ideas for further information I could get you, by running a beta or debugging, let me know, I'd be happy to dig in further

**Comment by WhyNotHugo** [comment]
Same issue on foot on swaywm/wayland.

FWIW, there's some background in https://github.com/neovim/neovim/issues/16447, though since have changed since.

**Comment by llimllib** [comment]
I'm going to close this in favor of #7151, because I believe that this is an instance of that and there's no need to have a duplicate issue here.

**Comment by zeertzjq** [comment]
No, this is a bit different as a flag emoji consists of two chara of the same type without a separator.

**Comment by llimllib** [comment]
ok, you know better than me! Thanks for all the work on neovim, I appreciate it
