### ISSUE TITLE
Emoji leaves artifacts on next buffer

### ISSUE THREAD

**Issue by wamoyo** [neovim/neovim#22021]
### Describe the bug

Certain emojis leave artifacts (usually the last character of the same line) behind when switching buffers.

### Steps to reproduce

nvim first.txt second.txt

In first.txt put the following:

```
Here is my emoji 🪸 and some follow-up text
```

In second.txt put the following:

```
Second buffer
```

Then run `:bn` and notice the hanging `t` in second.txt

first.txt:
![Screenshot from 2023-01-27 12-05-14](https://user-images.githubusercontent.com/1170326/215149312-a1aa8793-21ef-40a8-b1c3-66381cc03c85.png)
second.txt:
![Screenshot from 2023-01-27 12-05-17](https://user-images.githubusercontent.com/1170326/215149325-2f9404d4-c6b5-4cc7-89ff-257c52d1ddda.png)

### Expected behavior

That hanging `t` in the second buffer shouldn't be there.

This simple example isn't terribly problematic, but it becomes horrible when actually trying to edit text near emojis (same line, sometimes on the next line). You end up deleting the wrong thing. It's a real mess.

(Note: I'm using the 'narrow' option for Gnome Terminal Compatibility options, 'wide' produces much worse results.)

### Neovim version (nvim -v)

NVIM v0.7.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by team+vim@tracker.debian.org

### Vim (not Nvim) behaves the same?

Same issue with nvim -u DEFAULTS (I don't have normal vim)

### Operating system/version

Ubuntu 22.04

### Terminal name/version

Gnome Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

Ubuntu Package Manager

**Comment by zeertzjq** [comment]
Your Nvim version is too old.

**Comment by wamoyo** [comment]
Ubuntu 22.04's package manager won't upgrade it any further. What can I do to keep it up-to-date?

**Comment by dundargoc** [comment]
Either with [PPA](https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu), use one of our provided [releases](https://github.com/neovim/neovim/releases), build neovim yourself or through another package manager such as homebrew.
