### ISSUE TITLE
Restoring or Marking during a yank wipes prefixed register information

### ISSUE THREAD

**Issue by asmodeus812** [neovim/neovim#22037]
### Describe the bug

This one is a strange one, but i have had the following map in my vimrc which aims to retain the yank position by leveraging a mark, and restoring the position of the cursor to the mark after yanking, however if i prefix this with any register and try to do a yank, it always yanks in the default unnamed register ("). If i remove this mapping from my config i can now once again yank fine in any register (works as expected)

### Steps to reproduce

nvim --clean
xnoremap y myy`y
<visual select any text>"ay

### Expected behavior

Restoring a mark should not wipe prefix information about a register

### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

ubuntu 22

### Terminal name/version

alacritty 0.11

### $TERM environment variable

alacritty

### Installation

github release

**Comment by zeertzjq** [comment]
It should.

**Comment by zeertzjq** [comment]
This is the mapping you need:
```vim
xnoremap <expr> y 'my"' .. v:register .. 'y`y'
```
