### ISSUE TITLE
Neovim open wrong directory

### ISSUE THREAD

**Issue by Exprexxo248** [neovim/neovim#22069]
### Describe the bug

I have a problem with my Neovim that I can't open neovim with directory. I am confusing that it's a bug or it comes from my config.  

### Steps to reproduce

```
cd
nvim /learning/django/chat-app-ui
:lua print(vim.fn.getcwd()) 
-> get /home/namdang/
```

### Expected behavior

-> get /home/namdang/learning/django/chat-app-ui

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 22.04

### Terminal name/version

fish shell

### $TERM environment variable

tmux-256colors

### Installation

sudo apt

**Comment by Exprexxo248** [comment]
[Screencast from 31-01-2023 21:12:43.webm](https://user-images.githubusercontent.com/99623677/215785270-120123f3-9bd4-4d40-99e7-57fbbe164e34.webm)

**Comment by lewis6991** [comment]
This is how Neovim (and Vim, despite your report) behaves.

If you want to change directory, either `cd` in your shell or `:cd` in Neovim.

**Comment by lewis6991** [comment]
Yes I understand. Your expectation is incorrect.

**Comment by Exprexxo248** [comment]
Thanks for your messages!

**Comment by Oxyn4** [comment]
do you use nvimtree?

**Comment by Exprexxo248** [comment]
@Oxyn4 thanks for your great help it. I have added the code below into my config and it works
```
local function open_nvim_tree(data)
  -- buffer is a directory
  local directory = vim.fn.isdirectory(data.file) == 1
  if not directory then
    return
  end
  -- change to the directory
  vim.cmd.cd(data.file)
  -- open the tree
  require("nvim-tree.api").tree.open()
end

vim.api.nvim_create_autocmd({ "VimEnter" }, { callback = open_nvim_tree })
```
