### ISSUE TITLE
memory is being corrupted

### ISSUE THREAD

**Issue by magnickolas** [neovim/neovim#22064]
### Describe the bug

Under the conditions described below, Neovim crashes with an output "double free or corruption (out)"

I've already tracked the reason of the problem and am applying a PR #22065 

### Steps to reproduce

nvim -N -u NONE
:set laststatus=0

- Type in some text, let it be `abc`

- Now if one horizontally shrinks the Neovim window to a certain range, try to perform a search for `abc`, the Neovim process crashes with a message "double free or corruption (out)"

### Expected behavior

Neovim should not unexpectedly crash

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

no, vim 9.1.1182

### Operating system/version

Arch Linux 6.1.8-arch1-1

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

xterm-256color

### Installation

system package manager: pacman -S neovim

**Comment by magnickolas** [comment]
The label should actually be `bug-crash`

**Comment by zeertzjq** [comment]
> horizontally shrinks the Neovim window to a certain range

What is "the Neovim window"? What "certain range"?

**Comment by zeertzjq** [comment]
Minimal repro:
```vim
set columns=16
call setline(1, 'abc')
call feedkeys("/abc\<CR>")
```

**Comment by magnickolas** [comment]
@zeertzjq
By "the Neovim window" I actually meant the terminal window, that runs Neovim.

"Certain range" corresponds to when the message buffer is not empty, but of length less than the search stat message being written to in.
