### ISSUE TITLE
can not change the &buftype of a terminal buffer

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#22063]
### Describe the bug

nvim will throw an error: `E474: Invalid argument: buftype=help` on `setl buftype=help` when i run this command against a terminal buffer.

### Steps to reproduce

* nvim --clean +'term luajit test.lua'
* setl buftype=help

### Expected behavior

the step 2 will change the &buftype to `help`.

### Neovim version (nvim -v)

NVIM v0.8.2

### Vim (not Nvim) behaves the same?

no, vim 9.0.1182

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

tmux-256color

### Installation

pacman

**Comment by bfredl** [comment]
Not a bug. Documented and expected behavior:

>  help		help buffer (do not set this manually)

**Comment by haolian9** [comment]
please consider this again. because this error is not triggered by `setl buftype=help` only, in fact any of `<empty>`, `nofile`, `nowrite` will raise the same error.

**Comment by luukvbaal** [comment]
Still intended behavior I think, but perhaps not well documented. The `'buftype'` of a terminal buffer cannot be changed, nor can you set the `'buftype'` of a non-terminal buffer to `"terminal"`:
https://github.com/neovim/neovim/blob/facbb11e050186a13aa5451591f3c53b012f5566/src/nvim/optionstr.c#L1180-L1181

**Comment by haolian9** [comment]
oh thanks for the explanation!
well i do have a need that changing the &buftype of a terminal buffer to help once the corresponding process exited, so that that the windows bound to this terminal buffer can be omited in window.c :: only_one_window() when i calling `:quit`.
so i have to do this use a ffi call to `prepare_help_buffer()`, just like [this](https://gitlab.com/haoliang-terraform/squidward/-/commit/fbbde85da17edd28383ccda944e4e0b08ad2ff8f). since i do not plan to turn this use into a public plugin, it's an acceptable hack to me anyway.

**Comment by bfredl** [comment]
sounds like an AB problem. we would want a settable property of the _window_ indicating it should be implicitly closed if that helps closing a tab/all of vim. This often comes up as an expected behavior of floats, but is something which should be opt-in to by plugins for any kind of window (split/float).

**Comment by haolian9** [comment]
> a settable property of the window indicating it should be implicitly closed if that helps closing a tab/all of vim

yeah that's exactly what i wanted at the very first, but i thought several possible way to do it, and making &buftype=help of a terminal buffer is less time-consuming, and which, i happened to know, just works in **vim**, thus i opened this issue.

but please dont blame me for the laziness, opening a feature request is a too big job to me: maybe i should open it in vim's github repo first, discuss my premature yet very limited usecase out there over months, and most possibly it would be declined as "it seems to be a easy thing but actually a souce of troubles" ...
