### ISSUE TITLE
Changing vim.wo.wrap doesn't work immediately in lua callback function when setting keymap

### ISSUE THREAD

**Issue by regomne** [neovim/neovim#22066]
### Describe the bug

I'm trying to toggle `wrap` in a lua callback function using `vim.keymap.set`. However, there is no effect when the wrap status changes, and effect shows only after I enter any other key.

### Steps to reproduce

In `init.lua` :

```lua
vim.keymap.set('n', '<leader>r', function()
  if vim.wo.wrap then
    vim.wo.wrap = false
    print('Wrap OFF')
  else
    vim.wo.wrap = true
    print('Wrap ON')
  end
end, {expr = true})
```

Then write a long long line and press `<leader>r`.

### Expected behavior

When I enter `<leader>r`, it should toggle wrap status immediately.

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

no, "set wrap" in vimscript works.

### Operating system/version

Win10

### Terminal name/version

Windows Terminal 1.15.3465.0

### $TERM environment variable

None

### Installation

appimage from github release page

**Comment by glepnir** [comment]
does this works for you ?

```lua
  if vim.opt.wrap:get() then
    vim.opt.wrap = false
    print('Wrap OFF')
  else
    vim.opt.wrap = true
    print('Wrap ON')
  end
```

**Comment by glepnir** [comment]
does this works for you ?

```lua
  if vim.opt.wrap:get() then
    vim.opt.wrap = false
    print('Wrap OFF')
  else
    vim.opt.wrap = true
    print('Wrap ON')
  end
```

**Comment by zeertzjq** [comment]
```
In case you want the mapping to not do anything, you can have the expression
evaluate to an empty string.  If something changed that requires Vim to
go through the main loop (e.g. to update the display), return "\<Ignore>".
This is similar to "nothing" but makes Vim return from the loop that waits for
input.
```
