### ISSUE TITLE
Pass custom handler to vim.lsp.buf.rename

### ISSUE THREAD

**Issue by sarmong** [neovim/neovim#22075]
### Problem

I want to extend `vim.lsp.buf.rename` with a custom handler. Currently, I have 3 options listed in `:h lsp-handler-resolution`.

```
1. Handler passed to |vim.lsp.buf_request()|, if any.
2. Handler defined in |vim.lsp.start_client()|, if any.
3. Handler defined in |vim.lsp.handlers|, if any.
```

Option 2 and 3 will not allow me to have two functions - one calling default handler, the second calling custom handler.
With option 1 I will have to duplicate all the logic located in `vim.lsp.buf.rename` function, which is not ideal.

### Expected behavior

```lua
vim.lsp.buf.rename(nil, { handler = my_custom_handler })
```

**Comment by sarmong** [comment]
Actually, for my usecase, it will enough to pass `on_list` just like some other lsp function have, so that it can receive `changes` or `documentChanges`

**Comment by glepnir** [comment]
`:h vim.lsp.with`

**Comment by lewis6991** [comment]
Due to the difficulties with supporting multiple client. Allowing custom handlers for client-to-server requests will no longer be supported.
