### ISSUE TITLE
% jumps to incorrect parens in a lua code

### ISSUE THREAD

**Issue by comiluv** [neovim/neovim#22089]
### Describe the bug

% jumps between incorrect parens in below lua code example which was taken from https://github.com/windwp/nvim-autopairs/wiki/Custom-rules
```lua
autopairs.add_rule(Rule("[%(%{%[]", "")
  :use_regex(true)
  :replace_endpair(function(opts)
    return get_closing_for_line(opts.line)
  end)
  :end_wise(function(opts)
    -- Do not endwise if there is no closing
    return get_closing_for_line(opts.line) ~= ""
  end))
```

### Steps to reproduce

1. Install plugin github.com/nvim-treesitter/nvim-treesitter
2. make example.lua file with its content identical to above
3. ```nvim ./example.lua```
4. Navigate between braces using %
![incorrect jumping](https://user-images.githubusercontent.com/19642705/216087979-2b68f680-274f-483d-bc32-9a3cd4b917e9.gif)

### Expected behavior

Jumps between opening and closings like gif below. Below is run with ```nvim -u NORC```
![correct jumping](https://user-images.githubusercontent.com/19642705/216088157-2a69b4ce-427f-4658-8cfc-512048033c1f.gif)

### Neovim version (nvim -v)

NVIM v0.8.2

### Vim (not Nvim) behaves the same?

n/a as vim doesn't have treesitter

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal 1.15.3466

### $TERM environment variable

n/a

### Installation

choco install neovim

**Comment by clason** [comment]
Why do you think this is a Neovim bug and not an issue with the plugin(s) you use?

**Comment by comiluv** [comment]
Workaround is to have ```highlight.additional_vim_regex_highlighting = true``` in require'nvim-treesitter.configs'.setup{}, but would like jumping with regex highlighting disabled

**Comment by comiluv** [comment]
> Why do you think this is a Neovim bug and not an issue with the plugin(s) you use?

because
1. reproducible on my system with no plugins other than nvim-treesitter installed
2. matchit is part of neovim

**Comment by clason** [comment]
1. nvim-treesitter is an external plugin
2. your repro was using windwp/nvim-autopairs, not matchit
3. matchit is a Vim plugin that relies on Vim syntax and can't use treesitter parsing
