### ISSUE TITLE
sockconnect support for unix domain sockets. 

### ISSUE THREAD

**Issue by tmccombs** [neovim/neovim#22080]
### Problem

Currently the only "modes" supported by `sockconnect` are "pipe" (which doesn't work on linux, see https://github.com/neovim/neovim/issues/9470), and "tcp" which uses a host and port. It seems reasonable to also support unix domain sockets (perhaps with a mode of "unix"), which takes the path to the file for the socket, and behaves similarly to the tcp mode (but using a stream unix domain socket).

### Expected behavior

`sockconnect("unix", "/tmp/my-socket", {on_data: my_func})` would connect to the unix socket at /tmp/my-socket and create a channel for it.

**Comment by bfredl** [comment]
What gave you the idea that "pipe" doesn't work on linux? please actually test things before opening bug reports.

**Comment by clason** [comment]
The first step is to read the LibUV documentation (and `:h luvref`). As this is our main dependency and exposed through `vim.loop`, consistency with their (cross-platform) terminology is much more important for us than matching "10+ years of [experience] working with linux".

**Comment by clason** [comment]
Specifically, `:h luv-pipe-handle` mentions explicitly

> Pipe handles provide an abstraction over local domain sockets on Unix and named pipes on Windows.

**Comment by bfredl** [comment]
> Specifically, :h luv-pipe-handle mentions explicitly

Good, so we should just reference that from `sockconnect()`. That will making migrating between vim script and lua api:s straightforward as well.
