### ISSUE TITLE
`getline` converts null characters in a file into newline characters

### ISSUE THREAD

**Issue by ii41** [neovim/neovim#22093]
### Describe the bug

Functions such as `getline` and `getbufline` convert null characters in a file into newline characters in the list of strings they return. This is probably because of `:h NL-used-for-NUL`.

As neovim inserts null characters instead of newlines for multiline completion (https://github.com/neovim/neovim/issues/7769), today with LSP null characters keep appear in code. Any plugin which does not handle this case specially will get confused on what the actual content of the file is. I encountered this when using [vim-lsp](https://github.com/prabirshrestha/vim-lsp). This LSP client joins the lines returned by `getbufline` by `\n`, and then sends the result to an LSP server. Therefore, after a null appears in the file, both the client and the server think there's an extra `\n`, where there actually is a null, and cannot sync properly with the actual content of the file.

### Steps to reproduce

```
A
B
C
```
If you open a file with such contents, insert a null character after the `B` (this can be done by `CTRL-V CTRL-J` in normal mode, and neovim renders the null character as `^@`), what appears on the screen becomes
```
A
B^@
C
```
Then `:echo getline(1, '$')`, you'll get
```
['A', 'B
', 'C']
```
instead of `['A', 'B^@', 'C']`.

### Expected behavior

`getline` and `getbufline` return the actual content of the file, including of the null characters.

### Neovim version (nvim -v)

0.8.2

### Vim (not Nvim) behaves the same?

yes, vim 9.0

### Operating system/version

Linux 6.1.8-arch1-1

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

Arch Linux official repository (pacman)

**Comment by zeertzjq** [comment]
NUL bytes are not allowed in typval strings.

**Comment by ii41** [comment]
Sorry, as a user I don't understand, what is a typval string?

`:h getline()` does not say anything about the conversion. From a user's perspective it's just a bug. How does the typval string make it not a bug?

**Comment by zeertzjq** [comment]
```
String		A NUL terminated string of 8-bit unsigned characters (bytes).
```
