### ISSUE TITLE
True color support - no colors at all

### ISSUE THREAD

**Issue by michaldarda** [neovim/neovim#2210]
I was really excited to hear about neovim supporting true colors in console, but I've got this weird issue, when running nvim with true colors flag on, I have no colors at all

Here is how I start vim
`NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim`

My OS is Archlinux
` 3.17.6-1-ARCH #1 SMP PREEMPT Sun Dec 7 23:43:32 UTC 2014 x86_64 GNU/Linux`

Nvim is build from AUR, latest version from git https://aur.archlinux.org/packages/neovim-git/

I'm running nvim inside tmux, inside terminator, but it doesn't work either in gnome terminal (with or without tmux, so that is not a case)

My .nvimrc is empty, colorscheme is default, but when I change to some other colorscheme, nothing happens.

Apologize for my ignorance if I don't understand something, but I've done truecolor support test in my terminals and it seems to passed.

Everything works when I run nvim without that ` `NVIM_TUI_ENABLE_TRUE_COLOR=1` env var.

![nvim](https://cloud.githubusercontent.com/assets/1240505/6764458/6e1a811c-cfb0-11e4-8aec-0fd6a08ed6d5.png)

**Comment by ZyX-I** [comment]
Tmux does not support true colors. GNOME terminal may not support this as well (depends on libvte version it uses). What is the “true color support test”?

Also does colorscheme provide `guifg` and `guibg` attributes?

**Comment by tarruda** [comment]
There seems to be a tmux 1.9a patch available, if youre brave enough to try: https://gist.github.com/choppsv1/dd00858d4f7f356ce2cf

**Comment by michaldarda** [comment]
Well, I don't think tmux is a problem, when I'm not running tmux, just pure gnome-terminal, same issue occurs.

I'm talking about that test https://gist.github.com/XVilka/8346728

**Comment by tarruda** [comment]
@michaldarda The only way you can use this feature is if you switch to a terminal that supports it. In any case, this is not a Neovim issue.

**Comment by ZyX-I** [comment]
@tarruda AFAIR GNOME-terminal uses libvte. libvte supports true color. Only question is what version of libvte @michaldarda uses: if it is the version that supports true color it is NeoVim issue, otherwise it is not.

@michaldarda I see what test this is. But you should post a screenshot of “it seems to be passed”: I don’t like “seems”.

**Comment by raichoo** [comment]
I have `gnome-terminal` running on archlinux as well. Works fine.What's your `TERM` environment variable set to? I'm using `xterm-256color`.

Kind regards,
raichoo

**Comment by michaldarda** [comment]
@ZyX-I @raichoo I figured it out, it seems my gnome-terminal does not support true colors. I've switched to Konsole with patched tmux (https://gist.github.com/ArnisL/6156593) and it works fine.

I think we can close this, thanks everybody for help.
