### ISSUE TITLE
Provide Debian packages

### ISSUE THREAD

**Issue by babilen** [neovim/neovim#2211]
It would be wonderful if neovim could provide Debian packages in addition to its Ubuntu PPAs or at least make the packaging available so that people can build packages themselves.

**Comment by w0ng** [comment]
Distro-specific packaging should be the responsibility of the distro's community, not the project itself.

The build instructions are described in https://github.com/neovim/neovim/wiki/Installing#manual-installation with Debian pre-requisites of https://github.com/neovim/neovim/wiki/Building-Neovim#debian

To create a .deb for a build, see https://wiki.debian.org/HowToPackageForDebian

**Comment by Pyrohh** [comment]
Yes indeed, this doesn't seem like a priority right now. We should work to make packaging easier, as @jszakmeister has said, but I don't think we should be doing the actual packaging.

**Comment by fwalch** [comment]
BTW, don't the Ubuntu PPA packages work for Debian? Are there problems with differently named dependencies?

**Comment by babilen** [comment]
@w0ng Yes, I am quite familiar with packaging for Debian, but it would still be *much* easier to create packages if I had access to the packaging (i.e. debian directory) that is being used for the Ubuntu PPA. The packaging is probably almost identical and you simply chose to *not* make Debian packages available just because you aren't familiar with the best way to handle multiple repositories.

**Comment by babilen** [comment]
@fwalch The packages themselves might work. I don't really expect the packages to be too different, but PPAs are Ubuntu specific and I simply wanted to recompile packages *on Debian* with the correct dependencies and release names in place. I have the entire infrastructure to do that already in place, but simply need the `debian` directory (or, preferrably, a git repository that contains the packaging)

**Comment by babilen** [comment]
Just to make it clear: Providing packages for Debian is probably *very* easy, because it almost certainly only boils down to a build in a wheezy or sid chroot as opposed to a build in an Ubuntu one. I am *not* asking you guys to setup a Debian repository even though that would be nice. There simply is very little reason to not provide Debian packages if you already have the packaging done for Ubuntu.

Also, given that Ubuntu is a Debian derivative, I don't quite understand why you wouldn't target the distribution root in your packaging anyway.

**Comment by jszakmeister** [comment]
@babilen Everything is out in the open--we aren't hiding a thing, you just need to know where to look.  We don't keep a Debian folder in the repo because packaging bits don't belong in our repo, it belongs somewhere that a maintainer has control over.  

> There simply is very little reason to not provide Debian packages if you already have the packaging done for Ubuntu.

Please stop accusing people.  We don't have time to provide packages for every OS that someone thinks we should support--even if it is "simple".  It takes time to figure out what the process is, how to get the packages built, the role that we need to play in maintaining, and whether or not it's acceptable to build on their infrastructure (once we discover what it is) since Neovim is still in an alpha stage.

I'd prefer that someone more well informed with the process of maintaining packages to take on that role.  Also, that's the beauty of Open Source--if it's your itch, please scratch it.

The debian folder you seek is here:
   <http://bazaar.launchpad.net/~neovim-ppa/neovim-ppa/neovim-packaging/files>

> Also, given that Ubuntu is a Debian derivative, I don't quite understand why you wouldn't target the distribution root in your packaging anyway.

Because, at the end of the day, there are only so many hours and not enough time to chase down all the answers.

> Also, given that Ubuntu is a Debian derivative, I don't quite understand why you wouldn't target the distribution root in your packaging anyway.

It's there.  You just looked in the wrong place for it.

**Comment by mseeber** [comment]
There are some differences between "simply creating a deb" and "get neovim included into debian" For the second one, you would have to interact with with debian Developers/Maintainer, and compliance to the debian packaging guidelines will require some work.

@babilen 
Well, you could create a repository on github for packaging, so debian developers can review, but before there is a stable release of neovim and before jessie freeze ends, there is not much point in trying to get neovim into debian.
As you are very interested in this, why don't you do that?

**Comment by jszakmeister** [comment]
> There are some differences between "simply creating a deb" and "get neovim included into debian" For the second one, you would have to interact with with debian Developers/Maintainer, and compliance to the debian packaging guidelines will require some work.

Definitely.  My point was that we aren't setting up builds to haul off and provide Ubuntu packages--we're using Launchpad to do that, and they allow for it.  I don't know if Debian has such facilities or not, and it takes time to even discover that.  It's much better if someone who is familiar with the process can look into it.

**Comment by fwalch** [comment]
> @fwalch The Ubuntu packages themselves might work as I don't really expect the packages to be too different, but PPAs are Ubuntu specific and I simply wanted to recompile packages on Debian with the correct dependencies and release names in place. I have the entire infrastructure to do that already in place, but simply need the debian directory (or, preferrably, a git repository that contains the packaging)

All of the packaging code is on https://code.launchpad.net/neovim-ppa. To see how these repos are used, have a look at the [recipe](https://code.launchpad.net/~neovim-ppa/+recipe/neovim-unstable) (Note that the builds are currently failing because of #2189). Also note that currently, the dependencies from https://code.launchpad.net/+branch/~neovim-ppa/neovim-ppa/neovim-deps are not packaged separately, but simply statically linked with the Neovim binary during the build process.

**Comment by babilen** [comment]
@fwalch Thanks for pointing out https://code.launchpad.net/neovim-ppa which is, for now, all I've been looking for. I might consider getting neovim into Debian at a later time, but for now I simply wanted Debian packages to be available. I can build them myself, but given that you've done all the packaging work already it would be trivial to build packages for Debian releases (wheezy? wheezy-backports, jessie or sid) right away.

**Comment by jszakmeister** [comment]
> I can build them myself, but given that you've done all the packaging work already it would be trivial to build packages for Debian releases (wheezy? wheezy-backports, jessie or sid) right away.

Do you mean for us to build them or you are to build them?  If you mean the former, I'd kindly ask you to take it on.  I think there's already plenty on @fwalch's plate.

**Comment by phmarek** [comment]
The WNPP bug got changed to ITP: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=752264

**Comment by phmarek** [comment]
The WNPP bug got changed to ITP: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=752264

**Comment by justinmk** [comment]
@phmarek Is there any way to change (or just remove) the "vim's rebirth for the 21st century" subtitle from that? Will that subtitle appear in the apt package description?

**Comment by phmarek** [comment]
Just write a mail to `752264@bugs.debian.org` with the meta-data you want, I believe there is no problem changing that.

**Comment by dezza** [comment]
A temporary solution is to use checkinstall (also available in official Debian apt-get repos)

Checkinstall is an automated Debian packaging process which creates a dummy package by prefixing the install dir and is supposed to replace the "make install" step for users not willing to use PREFIX=/usr/local to avoid polluting the root / system.
```shell
sudo apt-get install checkinstall
make
checkinstall
dpkg -i neovim_20150825-1_amd64.deb
```

**Comment by nyuszika7h** [comment]
I suggest using this instead: https://github.com/jordansissel/fpm/wiki/PackageMakeInstall

**Comment by mbyt** [comment]
Even though repackaging for debian is the more correct and robust solution, on debian jessie, I simply installed the ubuntu packages with the following commands.

Add  `deb http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu vivid main` to `/etc/apt/sources.list` (debian jessie and ubuntu vivid are both released in april 2015). Then run:

```bash
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 55F96FCF8231B6DD
sudo apt-get update
sudo apt-get install neovim
```

Continue as described in https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu:
```bash
sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
sudo update-alternatives --config vi
sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
sudo update-alternatives --config vim
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
sudo update-alternatives --config editor
```

**Comment by wsdjeg** [comment]
so many kinds of package type ,should we provide all of tham,i think it is not the work of this repo!as if you are using linux ,i think it is easy to compile the src

**Comment by babilen** [comment]
@wsdjeg I don't quite agree with that sentiment as it would mean that you have to compile *everything* manually in the end. I prefer to be able to install well maintained binary packages that adhere to my distribution's policy.

That doesn't mean that users who are inclined to compile from source can't no longer do that either :)

**Comment by langri-sha** [comment]
Agree with @babilen. I appreciate repositories that release Debian packages on GH which I can `curl`, `wget`.

**Comment by justinmk** [comment]
If anyone wants to make a script that creates a debian package, we will add it to the build-bot.

**Comment by langri-sha** [comment]
@justinmk, by that, would you mean you would permit creating a debian package that would be hosted on GH or elsewhere for each release? If so, I would be inclined to scratch at it :muscle:

**Comment by justinmk** [comment]
@langri-sha  Yes, definitely.

**Comment by justinmk** [comment]
Looks like debian has a package now thanks to @jamessan : https://ftp-master.debian.org/new/neovim_0.1.1-1.html

**Comment by jamessan** [comment]
> Is there any way to change (or just remove) the "vim's rebirth for the 21st century" subtitle from that?

@justinmk I welcome any feedback for the package description that ended up being used (or for anything else).

**Comment by Shougo** [comment]
https://jamessan.com/~jamessan//posts/neovim-coming-to-debian/

**Comment by dezza** [comment]
unsubscribe

On Monday, 18 January 2016, Shougo <notifications@github.com> wrote:

> https://jamessan.com/~jamessan//posts/neovim-coming-to-debian/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neovim/neovim/issues/2211#issuecomment-172424470>.
>


-- 
* gplus.to/dza <http://gplus.to/dezzadk> //*
* http://quora.com/Christoffer-Aasted
<http://quora.com/Christoffer-Aasted> // *folding@home
<http://fah-web.stanford.edu/cgi-bin/main.py?qtype=userpage&teamnum=163&username=dezza>

*
<http://fah-web.stanford.edu/cgi-bin/main.py?qtype=userpage&teamnum=163&username=dezza>*

**Comment by sur5r** [comment]
As a friend of mine was asking me for it, I backported neovim from Debian experimental for stretch and jessie (amd64 and i386 only atm).

`deb http://debian.sur5r.net/neovim jessie main`
or
`deb http://debian.sur5r.net/neovim stretch main`

Signing key for this repository is available in package sur5r-keyring
` pub   4096R/941C42E6 2015-01-24 [expires: 2017-02-01]`
`        Key fingerprint = BFD9 0F4D AAEF A72B 67BB  AF48 E3CA 1A89 941C 42E6`
`uid                  debian.sur5r.net Archive Automatic Signing Key 2015 (sur5r) <debian@sur5r.net>`

Please note that this repository also contains backports of the following build dependencies for neovim:

- libtermkey
- libvterm
- libuv1
- lua-messagepack
- msgpack-c
- unibilium

Use at your own risk and please DON'T file bugs at the debian bugtracker for these packages.
The repository contains the source packages as well as the build logs (see pool directory).

I will remove this repository as soon as the relevant packages enter Debian proper.

Feel free to contact me in case you encounter any issues.
