### ISSUE TITLE
`set spelllang` accepts spaces between languages but `vim.bo.spelllang` doesn't

### ISSUE THREAD

**Issue by myrrc** [neovim/neovim#22124]
### Describe the bug

The behavior for setting spelllang with Vimscript (either from .vim files or from Lua via vim.cmd)
and with Lua API is inconsistent.

### Steps to reproduce

```lua
vim.cmd [[set spl="en, ru"]] -- ok
vim.bo.spl = "en, ru" -- E474: Invalid argument
```

### Expected behavior

The behavior is consistent

### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

vim doesn't have LUA api

### Operating system/version

Debian 11

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

apt

**Comment by zeertzjq** [comment]
> `set spl="en, ru"`

This set 'spelllang' to empty. The text starting from the first double quote is treated as a comment.
