### ISSUE TITLE
Current working directory scopes get overridden by precedence 

### ISSUE THREAD

**Issue by asmodeus812** [neovim/neovim#22129]
### Describe the bug

The scope chdir does not work as expected when you use lcd, tcd and cd. At the moment the function `vim.fn.getcwd` always prints whichever directory scope was set last, whereas according to the docs calling getcwd(0) or getcwd(0, 0) means get the local window cwd, for the current window and tab. It would seem like if you change an upper level scope it overrides the lower level scope it was set. For example:
- set cd
- set tcd
- set lcd
- set tcd again
- lcd is lost, tcd and cd are fine
 
Another example:
- set cd
- set tcd
- set cd
- tcd is lost, cd is fine

```
getcwd([{winnr} [, {tabnr}]])				*getcwd()*
		With no arguments, returns the name of the effective
		|current-directory|. With {winnr} or {tabnr} the working
		directory of that scope is returned, and 'autochdir' is
		ignored.
		Tabs and windows are identified by their respective numbers,
		0 means current tab or window. Missing tab number implies 0.
		**Thus the following are equivalent:  
			getcwd(0)
			getcwd(0, 0)**
```

### Steps to reproduce

mkdir -p /home/<user>/.global
mkdir -p /home/<user>/.tab
mkdir -p /home/<user>/.local

nvim -u NONE -U NONE

:cd /home/<user>/.global
:lua print(vim.fn.getcwd()) - prints /home/<user>/.global
:verbose pwd - prints [global] /home/<user>/.global

:tcd /home/<user>/.tab 
:lua print(vim.fn.getcwd()) - prints /home/<user>/.tab
:verbose pwd - prints [tabpage] /home/<user>/.tab

:lcd /home/<user>/.local
:lua print(vim.fn.getcwd()) - prints /home/<user>/.tab
:verbose pwd - prints [window] /home/<user>/.local

:tcd /home/<user>/.tab 
:lua print(vim.fn.getcwd()) - prints /home/<user>/.tab (incorrect)
:lua print(vim.fn.getcwd(0)) - prints /home/<user>/.tab (incorrect, should be .local)
:lua print(vim.fn.getcwd(0, 0)) - prints/home/<user>/.tab (incorrect, should be .local)

:lua print(vim.fn.getcwd(-1, -1)) - prints /home<user>/.global (correct)
:lua print(vim.fn.getcwd(-1, 0)) - prints /home/<user>/.tab (correct)

### Expected behavior

Working directory scopes should be preserved between global, tab and window scopes, regardless of what they point to (as long as they point to valid directories), and should not be overridden by upper level scope chdir action when

### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ubuntu 22

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

github release

**Comment by zeertzjq** [comment]
```
When a |:cd| command is used, the current window and tab will lose their local
current directories and will use the global current directory from now on.
When a |:tcd| command is used, only the current window will lose its local
working directory.
```

**Comment by asmodeus812** [comment]
@zeertzjq, well that is interesting, what is the purpose of the scopes at all  if it works only in one direction top down ? And all information is lost. Another issue is getcwd() returns the tab's tcd directory if set instead of the lcd even when lcd is set.

**Comment by zeertzjq** [comment]
I can't understand you question. Please provide an example.

**Comment by asmodeus812** [comment]
@zeertzjq  after a great deal of debugging, it seems that this is the curprit https://github.com/hrsh7th/nvim-cmp/issues/1425. What is happening is for some reason :verbose pwd and getcwd() keep showing the tcd even after lcd is set with the cmdline extension to cmp enabled. Not sure what is causing this i searched through the code base, they are not really using any of the cd flavours, but i managed to reproduce it with the minimal config. What is stranger yet, is that after setting tcd and then lcd, doing  :verbose pwd, shows [window] <tab directory>, seems odd, not sure how it messes up with the verbose output.
