### ISSUE TITLE
Persist `nvim_echo` highlighting in message log

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#22139]
### Problem

`nvim_echo` has a `history` flag to indicate whether the message should be logged to `:messages`. Currently this highlighting is visible when the message is displayed, but the message is not highlighted when viewed with `:messages`.

### Expected behavior

It would be great if there were an additional flag (or possibly just default behavior?) to persist the highlighting in the message log.

**Comment by zeertzjq** [comment]
Duplicate of #13812
