### ISSUE TITLE
Not all ANSI escape sequences are supported in `te`

### ISSUE THREAD

**Issue by nenikitov** [neovim/neovim#22134]
### Describe the bug

# Issue

Executing a print with an ANSI sequence to get XTerm colors gives empty output.
If the command is ran with `:!` instead of `:te`, it just reprints the string without escape characters.

If the same command is ran in Vim with `:!`, it gives the correct output.

# Images

## Command running in terminal

![image](https://user-images.githubusercontent.com/44075969/216839128-8d654c90-6907-4d62-ad99-4b3eb193ef51.png)

## Command running in Vim

![image](https://user-images.githubusercontent.com/44075969/216839170-25d84b9f-31d4-4e74-b4fb-143f4af94f44.png)
![image](https://user-images.githubusercontent.com/44075969/216839182-9e08cc7e-129e-4c0b-a8ea-436695b2c2db.png)

## Command running in Neovim

![image](https://user-images.githubusercontent.com/44075969/216839229-d04c4d6d-b200-4c53-9a69-4caf20c83484.png)

---

![image](https://user-images.githubusercontent.com/44075969/216839247-665b722c-a137-4836-aa2f-26146daaf5f3.png)
![image](https://user-images.githubusercontent.com/44075969/216839262-2b2a2220-bee4-4482-9939-8ac96fbb7e09.png)

### Steps to reproduce

```vim
:te printf "\033]4;1;?\007"
```

### Expected behavior

`4;1;rgb:/RRRR/GGGG/BBBB` (where `RGB` is the red color reported by the terminal)

### Neovim version (nvim -v)

v0.9.0-dev-873+g4b9bb3a184

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Arch Linux 6.1.7

### Terminal name/version

Alacritty 0.11.0 (8bdaa0bb)

### $TERM environment variable

alacritty

### Installation

Arch User Repository (AUR)

**Comment by erw7** [comment]
This issue contains two different problems, both of which are known issues.

#1496
#15365
