### ISSUE TITLE
an option for auto renaming a buffer when its underlying file has been renamed

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#22138]
### Problem

I saw an issue on vifm.vim that requires an auto renaming buffer feature which exists in rnvimr already.
so I'm wondering whether this feature can be adopted in nvim, thus these file manager plugins dont need to re-implement it again.
and there is already a similar &autoread option, which makes me think why not another option like &autorename, &autobufrename, ...

### Expected behavior

* $ touch foo
* $ nvim foo; `<ctrl-z>`
* $ mv foo bar
* $ fg

as nvim showed in foreground again, nvim will automatically rename the buffer from `foo` to `bar`

**Comment by lewis6991** [comment]
How is nvim supposed to figure what the file has been renamed too?

**Comment by haolian9** [comment]
After several days thought, i think there is no practial way to do it.
Since lsp client has a project and project root concept, maybe I can make use of it, but it's nothing relatived to the nvim core of course.
