### ISSUE TITLE
Colors gets pretty messed up on 0.9

### ISSUE THREAD

**Issue by Ciel-MC** [neovim/neovim#22142]
### Describe the bug

Some colors on 0.9 behave very weirdly
![image](https://user-images.githubusercontent.com/47144701/217014002-822f458d-dc12-4943-8a78-bc192555c134.png)
![image](https://user-images.githubusercontent.com/47144701/217014051-9d68019e-ba83-4e1e-a099-681ec1feeccb.png)

### Steps to reproduce

Get nvim-git from the AUR
Set up LSP
Open any Rust or Lua project and wait for project analysis(only tested with these two, probably any language works)
Look at the mess of colors

### Expected behavior

Screenshots from 0.8.3 for reference:
![image](https://user-images.githubusercontent.com/47144701/217015051-c8942ee8-19ed-47a9-9db1-800141cf99e9.png)
![image](https://user-images.githubusercontent.com/47144701/217015085-0dc33403-c628-4cc6-8568-e8ecc1678aa5.png)

Exact same config by the way

### Neovim version (nvim -v)

0.9.0-dev-880+ge1f03c481a

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux6.1.9-arch1-2

### Terminal name/version

Kitty 0.27.0

### $TERM environment variable

xterm-kitty

### Installation

AUR(neovim-git)

**Comment by clason** [comment]
> Exact same config by the way

Do you maybe want to share that config? Otherwise there's nothing to say here.

**Comment by clason** [comment]
Also, be aware that 0.9 supports LSP semantic highlighting which 0.8 didn't. Make sure to disable that if you want to compare highlighting.

**Comment by Ciel-MC** [comment]
I see... where do I find that? Here's the config btw:
[init.lua.txt](https://github.com/neovim/neovim/files/10664708/init.lua.txt)

**Comment by Ciel-MC** [comment]
> `:h news.txt`

That's a thing that I didn't know existed, checking rn

**Comment by Ciel-MC** [comment]
> Also, be aware that 0.9 supports LSP semantic highlighting which 0.8 didn't. Make sure to disable that if you want to compare highlighting.

Okay, so it does turn out to be semantic tokens causing this, thought it is weird how it's causing inconsistent behaviors

**Comment by Ciel-MC** [comment]
Thank you so much for your help, I was scratching my head for an hour getting more and more frustrated, I'd never have figured this out myself.
