### ISSUE TITLE
Window local option to define which windows to diff against in diffs with more than 2 windows

### ISSUE THREAD

**Issue by tummetott** [neovim/neovim#22144]
### Problem

When doing a 3-way diff with nvim (resolving a git merge conflict), there are usually 3 windows: `ours`, `local` and `theirs`. (N)vim enables the `diff` option for all three windows and every window is diffed against all other windows. However i'd expect that `ours` and `theirs` are not diffed against each other, but are only diffed against `local`. `local` however should be diffed against both, `ours` and `theirs`.

This is also the behaviour of other GUI difftools like e.g. [meld](https://github.com/GNOME/meld).

In this scenario, it does not really make sense that `ours` and `local` are diffed against each other because they only serve as a reference and their buffer content never changes (ideally `modifiable` is turned off like it's done in [diffview](https://github.com/sindrets/diffview.nvim)).
Example: When I jump to the first merge conflict in the `local` window and `:diffget` the codeblock from `ours`, then `ours` and `local` are in sync considering the first conflict. I would expect the codeblock of the first conflict not to be highlighted in `ours`, because it matches `local`. However I'd expect the codeblock of `local` and `theirs` to be highlighted because they are not identical by definition.

### Expected behavior

As far as I know, there is no window local option that allows specifying which windows to diff against for diffs with windows > 2. But it would be super neat to have such an option 🚀

**Comment by justinmk** [comment]
send this to https://github.com/vim/vim/ , this not the kind of thing we want to spend time on.
