### ISSUE TITLE
Cannot create temp file for executing external commands

### ISSUE THREAD

**Issue by rlegendi** [neovim/neovim#22143]
### Describe the bug

It seems a fresh nvim cannot execute external commands and paste the info into the editor.

### Steps to reproduce

Start nvim

Without entering insert mode, simply type: !!date

I get the following error:

```
:.!date
E485 Can't read file C:\Users\<username>\AppData\Local\Temp\<random stuff>\3
Press ENTER or type command to continue
```

### Expected behavior

Print the output of the executed command to the document under cursor position.

### Neovim version (nvim -v)

v0.8.3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Win 11

### Terminal name/version

No term - I just start nvim-qt

### $TERM environment variable

xterm-256color

### Installation

Latest stable release zip download

**Comment by 3N4N** [comment]
What's the output of `:set term?`  Please provide minimal reproduction steps.

**Comment by rlegendi** [comment]
Het @3N4N, 

Hm... Should `:set term` work? I use the latest version of nvim (see above), and it tells me:

`E518: Unknown option: term`

**Comment by zeertzjq** [comment]
`:echo &term`

**Comment by 3N4N** [comment]
My mistake.  I wanted to say `:set shell?`.

**Comment by rlegendi** [comment]
No worries :-) Just was suprised on the command as I didn't know it :D

I'm using neovim both via _nvim-qt.exe_ and through _Cmder_. Both of them gives similar error.

In case of _nvim-qt_, I get the output:

```
shell=cmd.exe
```

In case of _Cmder_, I get the output similar to:

```
shell=C:\...\cmder-1.3.19\vendor\git-for-windows\usr\bin\bash.exe
```

This is coming from my corporate laptop. I'll test it on my home computer later on, as I guess there might be some privilege issues or security rules or stg. I have admin privileges there, that might work.

**Comment by 3N4N** [comment]
If shell is set to cmd, then I can't say what the problem is; I'll take a look tonight.  And as for shell set to bash in cmder, that'll have to be solved by someone else.

**Comment by rlegendi** [comment]
Thansk for checking! Pls don't put any more efforts into it for the time being. I have some updates to share, issue on my end, but need to finish the investigation and consolidate the info. I'll document the findings in this ticket, so if others are in the same shoes, it'll be easier to fix it.

Thx so much for all the efforts @3N4N!

**Comment by rlegendi** [comment]
A bit of updates as promised.

I've spent a lot of time on this in the meantime, and did a lot of experiments on my home/corporate/and even my wife's laptop haha.

I concluded that after several tries with different shells and environments and even with `nvim.exe --clean`/`nvim-qt.exe -- --clean`, that nvim is working perfectly in the standard usecases.

After cleaning up my config, the only thing that didn't work was using nvim through cmder, and I suspect because of a faulty shell variable value - but I wasn't able to make it work.

In the end, I solved the issue with installing wsl and using cmder + neovim with it. [Here are the steps](https://xcafebabe.blogspot.com/2023/02/how-to-make-neovim-cmder-wsl-work.html) I documented. That works :-)

Thx so much for the help and your time, @3N4N! Closing the ticket if you don't mind.

**Comment by weliwita** [comment]
Even though it’s not directly related to the original post, I ran into the same error on wezterm terminal and eventually found the cause:
my TEMP path contained a space because my Windows user profile folder had a space in it.

I fixed it by:

Creating a symlink to my profile folder without spaces.

Updating my TEMP environment variable to point to that space-free path.
