### ISSUE TITLE
functional/ui/cmdline_spec.lua fails or gives warnings

### ISSUE THREAD

**Issue by Jun-T** [neovim/neovim#22155]
### Describe the bug

functional/ui/cmdline_spec.lua fails on macOS Mojave, or gives warning on Linux.

### Steps to reproduce

TEST_FILE=functional/ui/cmdline_spec.lua make test

### Expected behavior

Test succeeds without warnings.

### Actual behavior

On Ubuntu-22.04, it gives the warning
"Screen changes were received after the expected state."
for the following two test:
(1) cmdheight=0 with multigrid
(2) cmdheight=0 can only be resized to 0 if set explicitly:

On macOS (Mojave), the test (1) fails as follows:
Expected:
 |## grid 3
  |*  /p^                       |
Actual:
|## grid 3
  |*  /p                       |

The reason for (1) is simple: since the option 'incsearch' is ON by default, after `feed '/p',` busy_start/stop events is sent to the screen and the cursor '^' is turned off/on.
This can be fixed by adding
`    command('set noincsearch')`
before the line 1247 in functional/ui/cmdline_spec.lua:
`    feed '/p'`
https://github.com/neovim/neovim/blob/8fbe75b3dda7ab3b9e6df0d5406539bde4c80887/test/functional/ui/cmdline_spec.lua#L1247-L1248

I don't know the origin of the problem in test (2), and not sure whether it is related with the issue https://github.com/neovim/neovim/issues/22154.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-877+g228684d2f-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu-22.04, macOS (Mojave etc.)

### Terminal name/version

gnome-terminal, Terminal.app

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
The first test is explicitly for incsearch (#20351), so incsearch shouldn't be disabled.

**Comment by Jun-T** [comment]
With incsearch, the command line will change as

(1) /p^
busy_start
(2) /p
busy_stop
(3) /p^

On most OSes, expect() detects the state (1) and the test passes (but the state (2) causes the warning). But on my macOS Mojave, it seems that expect() detects the state (2) and the test fails (but why doesn't it wait for the state (3)?).

But anyway, it fails only on Mojave (old) and it may be left as is.
Of course removing the warnings is better but I don't know how to do that. I tried  adding expect{} with intermediate state(s) but it seemed it didn't work.

**Comment by justinmk** [comment]
No warnings or errors on macos 14.5:

    TEST_FILE=test/functional/ui/cmdline_spec.lua make functionaltest
