### ISSUE TITLE
files with `#!/bin/dash`, `#!/usr/bin/dash`, `#!/usr/bin/env dash` should have the same filetype as files with `#!/bin/sh`

### ISSUE THREAD

**Issue by OldWorldOrdr** [neovim/neovim#22152]
### Describe the bug

files with `#!/bin/dash` and similar are misidentified as conf files instead of sh files

### Steps to reproduce

open a file with the `#!/bin/dash` shebang
filetype is conf and the syntax highlighting is wrong

### Expected behavior

filetype should be sh and correct syntax highlighting should be used

### Neovim version (nvim -v)

0.8.3 from homebrew and 0.8.3 from arch repos both have this issue

### Vim (not Nvim) behaves the same?

no, 9.0.1182 from arch repos correctly sets filetype and syntax highlighting

### Operating system/version

macOS 11.7.3 and latest Arch Linux

### Terminal name/version

kitty 0.27.0

### $TERM environment variable

xterm-256color

### Installation

homebrew and pacman

**Comment by zeertzjq** [comment]
Fixed by #21174
