### ISSUE TITLE
Colors under Yosemite and iTerm are not right

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#2215]
This is what I get under Neovim:

![screen shot 2015-03-21 at 4 36 45 pm](https://cloud.githubusercontent.com/assets/448087/6766728/7cd2f8be-cfe8-11e4-82de-a3c911c196a6.png)

Here's the same screen under Vim:

![screen shot 2015-03-21 at 4 36 11 pm](https://cloud.githubusercontent.com/assets/448087/6766729/7f728a1c-cfe8-11e4-9f67-595e70406e0f.png)

`TERM` is set to `xterm-256color`, if that helps.  Something has been wrong for a while, but there was a lot of things in the air at the time, so I was hoping it was just the fact that things weren't done yet.

**Comment by tarruda** [comment]
What happens if you reload the colorscheme after startup?

**Comment by jszakmeister** [comment]
It's better, but not correct either.
![screen shot 2015-03-21 at 5 14 37 pm](https://cloud.githubusercontent.com/assets/448087/6766864/d1209610-cfed-11e4-8f20-1309f4ada4e1.png)

**Comment by tmcw** [comment]
I'm seeing a similar issue:

neovim:

<img width="592" alt="2015-12-09 at 10 38 am" src="https://cloud.githubusercontent.com/assets/32314/11689670/fe28b286-9e60-11e5-9263-26acc41540bc.png">

[vibrantink screenshot](http://jozilla.net/images/software/scripts/vibrantink.png)

![image](https://cloud.githubusercontent.com/assets/32314/11689696/13da1bce-9e61-11e5-8288-b5a29197a55f.png)

There's a [stackoverflow ticket discussing this issue with no resolution](http://vi.stackexchange.com/questions/3576/trouble-using-color-scheme-in-neovim).

Info:

```
~〉nvim -v
NVIM v0.1.1-8-gf40c8c4 (compiled Dec  9 2015 10:31:18)
Commit: f40c8c4c23a36147ea39463bea421c5943eea937
...
~〉echo $TERM
xterm-256color
```

My init.vim: https://github.com/tmcw/.vim/blob/master/init.vim

**Comment by tmcw** [comment]
base16-eighties is much wronger as well:

<img width="662" alt="2015-12-09 at 11 07 am" src="https://cloud.githubusercontent.com/assets/32314/11690536/1d4bda04-9e65-11e5-89a9-677affd0c79e.png">

**Comment by tmcw** [comment]
`let $NVIM_TUI_ENABLE_TRUE_COLOR=1` fixed it!

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/pull/4155
