### ISSUE TITLE
nvim prints ";2u" on Shift + Space in terminal mode

### ISSUE THREAD

**Issue by nmattia** [neovim/neovim#22168]
### Describe the bug

Since updating to 0.8, `nvim` prints unwanted characters when I hit Shift + Space (`;2u`) or Shift + Return (`3;2u`) or Ctrl + Return, .... 

### Steps to reproduce

```
nvim --clean
:terminal
<Shift  + Space>, etc
```

https://user-images.githubusercontent.com/6930756/217513490-38fbb2df-a637-482d-bc10-3270ca5c11a8.mov

### Expected behavior

I expect Shift + Space to insert a space character

### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no, older nvim versions don't either

### Operating system/version

macOS 13.2

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

from github releases

**Comment by zeertzjq** [comment]
Your expectation is wrong.

**Comment by zeertzjq** [comment]
Duplicate of #21360

**Comment by leoentersthevoid** [comment]
@nmattia, if you're using iTerm2, you'll have to navigate to `Preferences -> Profiles -> Keys`, and on the `General` tab you'll have to ✅ "**xterm control sequence can enable modifyOtherKeys mode**". Hope this gives anybody a decent starting point in fixing the issue on their machine.

**Comment by nmattia** [comment]
@leoentersthevoid you are a LIFE SAVER! This fixed the issue.

**Comment by DownRangeDevOps** [comment]
> @nmattia, if you're using iTerm2, you'll have to navigate to `Preferences -> Profiles -> Keys`, and on the `General` tab you'll have to ✅ "**xterm control sequence can enable modifyOtherKeys mode**". Hope this gives anybody a decent starting point in fixing the issue on their machine.

Thank you! For weeks I have been trying to figure out why `shift + space` would delete the current line in the Neovim terminal (running zsh).

This fixed it.
