### ISSUE TITLE
some issues about + register

### ISSUE THREAD

**Issue by thinker3** [neovim/neovim#2217]
I mapped ctrl-v to paste the content of + register

:reg not showing + register but the symbol |, even though it works as well in insert mode

but in command mode, I can not use ctrl-v to paste text from command-c

I have to paste once in insert mode, then I can paste in command mode

osx 10.10.2

**Comment by LeonB** [comment]
I thnk this is a duplicate of #1860

**Comment by bfredl** [comment]
#2244 might fix both issues.

**Comment by bfredl** [comment]
Closed as duplicate of #1860 and #1908
