### ISSUE TITLE
Error executing vim.schedule lua callback: vim/shared.lua:0

### ISSUE THREAD

**Issue by vpetro** [neovim/neovim#22197]
### Describe the bug

This happens every edit in a file that has a language for which I have LSP enabled (lua, python, scala, typescript/javascript).

```
Error executing vim.schedule lua callback: vim/shared.lua:0: after the second argument: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'tbl_deep_extend'
        ...w/Cellar/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp.lua:2252: in function 'handler'
        ...w/Cellar/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp.lua:1049: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

This started showing up about a week ago. Upgrading to HEAD didn't resolve this either. 

### Steps to reproduce

 * open a file with LSP enabled
 * try to edit

### Expected behavior

Expected behavior is that the editor doesn't throw an error every edit. 

Note that disabling LSP via `:LspStop` makes the error go away.

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 12.6.2

### Terminal name/version

Alacritty 0.11

### $TERM environment variable

screen-256color

### Installation

homebrew

**Comment by clason** [comment]
Can't help you without a minimal config (and even then I strongly suspect that this is a plugin problem).

**Comment by vpetro** [comment]
It turned out to be the LSP config for a typescript server. I have the following code in a module:

```lua
M = {}


M.diagnostic_config = { virtual_text = false, signs = true, update_in_insert = false, underline = true }

function M.setup_diagnostics()
  vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
      vim.lsp.diagnostic.on_publish_diagnostics, M.diagnostic_config
    )
end

return M

```

and then i called it like this in the my `js.lua` file

```lua
local lh = require("vpetro.lsp_helper")

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').default_capabilities(capabilities)

require'lspconfig'.tsserver.setup{ capabilities = capabilities }

lh.setup_keymaps()
ls.setup_diagnostics()
```

I can't quite see this started not working all of a sudden. But changing the `js.lua` file to have this config:

```lua
local lh = require("vpetro.lsp_helper")

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').default_capabilities(capabilities)

require'lspconfig'.tsserver.setup{
  capabilities = capabilities,
  handlers = {
    ["textDocument/publishDiagnostics"] = vim.lsp.with(
        vim.lsp.diagnostic.on_publish_diagnostics,
        { virtual_text = false, signs = true, update_in_insert = false, underline = true}
    ),
  }
}
lh.setup_keymaps()
```

made the errors go away. The funny thing is that the previous version has been months. I guess, I'll go through the rest of my LSP configs and change to passing the handler into the config rather than setting it up from the outside.

Thanks for the nudge to look at the plugin/config code! :)
