### ISSUE TITLE
Git urls with packadd

### ISSUE THREAD

**Issue by paulfrische** [neovim/neovim#22203]
### Problem

Package/Plugin management in neovim is a mess. There are many plugin managers all doing there thing.

Personally I think package/plugin management is such an essential thing that it should be handled by neovim core(or at least there should be a builtin way of doing it). One could say that it is handled by neovim core via packages and the packadd command but to be honest it isn't used that much (by the user directly) because you still have to clone the plugin repo or download it some other way and add it to your packpath manually which makes it not only inconvenient but harder to reproduce too.

### Expected behavior

I think one solution to the _problem_ would be to add support for git urls to packadd. When running packadd with such a url (or is it an uri?) instead of a file system path it should (shallow) clone the repo to a sensible location and do it's thing.

To enhance the UX there could be an option like `giturlexpansion` (TODO: better name) which contains a list like `{ "https://github.com/$.git", "https://gitlab.com/$.git" }`. Users wouldn't have to write the entire url rather than the `github-username/plugin-name`-pattern we see today with many popular plugin managers. Neovim would iterate through the list and use the first working url-pattern.

Adding this capability to packadd has the potential of making the entire neovim plugin ecosystem more stable.

A config using plugins wouldn't look like this anymore: 
```lua
return require('packer').startup({
  function(use)
    use('kdheepak/lazygit.nvim')
    use('f-person/git-blame.nvim')
    use('lukas-reineke/indent-blankline.nvim')
    use('lvimuser/lsp-inlayhints.nvim')
    use('nvim-telescope/telescope.nvim')
    use('nvim-telescope/telescope-file-browser.nvim')
    use('olacin/telescope-cc.nvim')
    -- ...
  end
})
```

rather than like this:

```lua
vim.o.giturlexpansion:append("https://github.com/$.git")

vim.cmd.packadd('kdheepak/lazygit.nvim')
vim.cmd.packadd('f-person/git-blame.nvim')
vim.cmd.packadd('lukas-reineke/indent-blankline.nvim')
vim.cmd.packadd('lvimuser/lsp-inlayhints.nvim')
vim.cmd.packadd('nvim-telescope/telescope.nvim')
vim.cmd.packadd('nvim-telescope/telescope-file-browser.nvim')
vim.cmd.packadd('olacin/telescope-cc.nvim')
-- ...
```

**Comment by clason** [comment]
> Package/Plugin management in neovim is a mess.

[citation needed]

> There are many plugin managers all doing their thing.

Choice is _good_; the fertile plugin ecosystem is a big part of the value proposition of (Neo)vim.

> I think one solution to the problem would be to add support for git urls to packadd

That would a) require us to bundle and expose a git library that works consistently on all supported platforms and b) bless git as the "one true package format for Neovim". Both have massive drawbacks that have to be weighed against user convenience.

Also, your proposal lacks important details: would you re-clone on every startup? if not, how do you make sure your plugins are up-to-date?

That being said, some built-in way for bootstrapping a proper package manager is something we've been discussing for quite a while; but the correct approach is not obvious for the reasons I mentioned above.

**Comment by paulfrische** [comment]
@clason You can argue about if git is the best "format" for the job but pretending that it is good enough:

> Choice is good; the fertile plugin ecosystem is a big part of the value proposition of (Neo)vim.

Of course choice is good but sometimes having a built-in thing is better than having several third party ones (e.g. LSP support). And even if I am wrong nobody forces you to use it.

> That would a) require us to bundle and expose a git library that works consistently on all supported platforms

For some cloning and pulling you don't need a fully fledged git library.

> Also, your proposal lacks important details: would you re-clone on every startup? if not, how do you make sure your plugins are up-to-date?

Re-cloning would be very wasteful. I thought about running a git pull for every plugin.

PS: I hope this proposal isn't complete bs and thx for investing your time into contributing to this wonderful project

**Comment by ObserverOfTime** [comment]
If you don't want to use a package manager, you can use git submodules and let neovim handle the rest.

**Comment by lewis6991** [comment]
> That being said, some built-in way for bootstrapping a proper package manager is something we've been discussing for quite a while; but the correct approach is not obvious for the reasons I mentioned above.

The bootstrapping for https://github.com/folke/lazy.nvim#-installation is already pretty good. How could we improve on that?

**Comment by clason** [comment]
By not relying on external tools that may or may not be installed in a system or have platform-specific quirks.

**Comment by lewis6991** [comment]
How would one do that without vendoring some form of a `git` (or at the very least a `curl`) implementation?

**Comment by clason** [comment]
That would be one way, indeed. (Not saying it's a good way; I _did_ mention above that there's no good proposal for this yet!)

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/20893#issuecomment-1297870788

closing this issue because the other one has less noise
