### ISSUE TITLE
Clangd client exits with non-zero code and signal 0

### ISSUE THREAD

**Issue by 3N4N** [neovim/neovim#22205]
### Describe the bug

After opening a C/C++ file in a C/C++ project, clangd client exits with error messages like this:

```
Client 1 quit with exit code 3221225477 and signal 0
```

The exit code seems to be the same every time but I'm not sure (I haven't been keeping score).  And the client exits non-deterministically: sometimes right after opening a C/C++ file; sometimes after a couple of minutes.

You can find the `:LspLog` in this link: http://sprunge.us/Mg1FGi.

### Steps to reproduce

1. Go to a C/C++ project
2. Set up nvim-lspconfig as per the plugin readme (look for clangd section)
3. Open a C/C++ file
4. Move around, using LSP functionalities, until the client exits

### Expected behavior

clangd client doesn't exit with error code.

### Neovim version (nvim -v)

v0.9.0-dev-850+g79d7fdc142a1

### Clangd version
15.0.6

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 11 22H2

### Terminal name/version

Windows Terminal

### $TERM environment variable

nil, xterm-256color

### Installation

Built from source

**Comment by 3N4N** [comment]
Why are all the lines marked as `[ERROR]` in my [lsplog](http://sprunge.us/Mg1FGi)?

```
[ERROR][2023-02-10 20:07:23] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[20:07:23.910] Starting LSP over stdin/stdout\r\n"
```

^This shouldn't be ERROR, right?

**Comment by mfussenegger** [comment]
> Why are all the lines marked as `[ERROR]` in my [lsplog](http://sprunge.us/Mg1FGi)?
> 
> ```
> [ERROR][2023-02-10 20:07:23] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[20:07:23.910] Starting LSP over stdin/stdout\r\n"
> ```
> 
> ^This shouldn't be ERROR, right?

Anything output to `stderr` is logged as error. Given that some language servers may really write error messages to stderr it's better to err on making it more visible than not.


The issue itself needs minimal deterministic reproduction steps. Many people use clangd daily without running into any crashes, so "just use it" isn't good enough to look into this.

**Comment by 3N4N** [comment]
I'm not sure how to decide repro steps when a plugin is involved.  Should I transfer this ticket to nvim-lspconfig?

**Comment by mfussenegger** [comment]
> I'm not sure how to decide repro steps when a plugin is involved. Should I transfer this ticket to nvim-lspconfig?

The issue template contains minimal reproduction steps that don't involve lspconfig.

There's also a good chance it's a clangd issue and not a client issue. Servers shouldn't just crash, even if the client would send bogus requests.

**Comment by 3N4N** [comment]
> Anything output to stderr is logged as error. Given that some language servers may really write error messages to stderr it's better to err on making it more visible than not.

Understood.  But that specific line -- should that be written in stderr?  In other words, is that line marked as ERROR in linux?

> The issue template contains minimal reproduction steps that don't involve lspconfig.

How do I use lsp without lspconfig?  Is it logical to figure out a way to use lsp without using lspconfig just for traditional repro steps when we all have nvim-lspconfig installed (that's what the purpose of nvim-lspconfig is: to bootstrap users; it's a repo of neovim org)?

> There's also a good chance it's a clangd issue and not a client issue.

Most probably.  I'm trying out different versions.  Will report on my findings.

**Comment by lewis6991** [comment]
> ```
> Client 1 quit with exit code 3221225477 and signal 0
> ```

Exit codes should be 0-255 so this is sus.

**Comment by lewis6991** [comment]
> Understood. But that specific line -- should that be written in stderr? In other words, is that line marked as ERROR in linux?

I think the error messages in the log are a misnomer. The server appears to be exiting because a signal was send to it.

**Comment by lewis6991** [comment]
> ERROR][2023-02-10 20:07:33] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"Signalled while building preamble\r\n  Filename: ...
> [ERROR][2023-02-10 20:07:33] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"Exception Code: 0xC0000005\r\n #0 0x00007ff60613d59d (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xbd59d)\r\n #1 0x00007ff60613bb98 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xbbb98)\r\n #2 0x00007ff60613d187 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xbd187)\r\n #3 0x00007ff60610fa43 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0x8fa43)\r\n #4 0x00007ff6061c0327 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0x140327)\r\n #5 0x00007ff606f86e77 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xf06e77)\r\n #6 0x00007ff606f87863 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xf07863)\r\n #7 0x00007ff606ec36ed (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xe436ed)\r\n #8 0x00007ff607420dbf (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0x13a0dbf)\r\n #9 0x00007ff606e3ff8d (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xdbff8d)\r\n#10 0x00007ff606e3fdc4 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xdbfdc4)\r\n#11 0x00007ff606e42505 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xdc2505)\r\n#12 0x00007ff606e54748 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xdd4748)\r\n#13 0x00007ff606d76a3c (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xcf6a3c)\r\n#14 0x00007ff606e02e7e (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xd82e7e)\r\n#15 0x00007ff607b5c9b6 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0x1adc9b6)\r\n#16 0x00007ff606e03fe3 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xd83fe3)\r\n#17 0x00007ff606d7cda9 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xcfcda9)\r\n#18 0x00007ff606d805fd (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xd005fd)\r\n#19 0x00007ff606fe9e6e (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xf69e6e)\r\n#20 0x00007ff606fe9bee (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0xf69bee)\r\n#21 0x00007ff607aa3f02 (C:\\Users\\ACER\\scoop\\apps\\clangd\\current\\bin\\clangd.exe+0x1a23f02)\r\n#22 0x00007ffacfdb26bd (C:\\WINDOWS\\System32\\KERNEL32.DLL+0x126bd"

Looks like clangd crashed. Probably isn't built correctly.

**Comment by 3N4N** [comment]
I'd been binary searching my lsp config to narrow in on the problem.  It seems like this line in `on_attach` function was the problem:

```
client.server_capabilities.semanticTokensProvider = nil
```

Issues:
- I'm not sure if this line is _definitely_ the problem
- I really need that line to disable colors, so removing it is not a solution

**Comment by 3N4N** [comment]
I'm currently using the version of clangd provided by msys.  As of being used for a day, it hasn't crashed.  I'll close this issue.
