### ISSUE TITLE
Chafa doesn't work in neovim terminal

### ISSUE THREAD

**Issue by TroySigX** [neovim/neovim#22229]
### Problem

I tried to use chafa image preview to see the image in terminal, but it doesn't work in Neovim.

### Expected behavior

Chafa shows image in neovim terminal.

**Comment by dundargoc** [comment]
It works for me.

You'll need to use the "bug template" for bug reports. Unrelated, but I kinda don't feel like showing gifs with neovim terminal is a high priority.
