### ISSUE TITLE
CursorLineNr highlight disappears when moving up through folds

### ISSUE THREAD

**Issue by mcauley-penney** [neovim/neovim#22232]
### Describe the bug

When using a the statuscolumn option and moving up the buffer line by line over folded text, the CursorLineNr highlight disappears. See the GIF below for an example.

![statuscol_fold](https://user-images.githubusercontent.com/59481467/218292185-0c2b26a8-e6cd-483e-8d6a-59669273a8da.gif)

### Steps to reproduce

I can reproduce this with `o.statuscolumn = "%{v:relnum? v:relnum:v:lnum}"`.

### Expected behavior

The expected behavior is that the CursorLineNr highlight would not disappear when moving across folded text.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-934+g9668c166e, 

### Vim (not Nvim) behaves the same?

No, statuscolumn is not a vim feature

### Operating system/version

Linux 6.1.9-arch1-2

### Terminal name/version

xterm 378

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by luukvbaal** [comment]
Can't seem to reproduce for now, could you try to make a minimal reproducible example including `nvim --clean`?

**Comment by luukvbaal** [comment]
I can reproduce a similar issue but it is present without `'statuscolumn'` set as well:

    nvim --clean +"set nu cul culopt=number fdc=1 | call setline(1, repeat(['aaaa'],10)) | 1,5fold | norm zojzc"

The cursor highlight is gone until the cursor is moved again(also when pressing the normal command keys instead). Can't reproduce a case where moving the cursor back and forth from the folded line keeps omitting the cursorline hightlight.

**Comment by mcauley-penney** [comment]
Okay, so, this is labeled wrong due to my lack of thorough investigation. That's my fault, I apologize. I can reproduce it consistently on HEAD with the below settings using `nvim --clean`:

```
set nu
set cursorline
set foldmethod=indent
nnoremap n gj
nnoremap e gk 
```

The real culprit is those mappings. Without them, the issues disappears. I'd like to relabel this issue, it is NOT the statuscolumn.
