### ISSUE TITLE
Chafa doesn't work in Neovim terminal

### ISSUE THREAD

**Issue by TroySigX** [neovim/neovim#22230]
### Describe the bug

When if call Chafa in Neovim terminal, it doesn't show up any image. It does work in my terminal (Yakuake).

### Steps to reproduce

1. Open nvim
2. :new | term
3. chafa "image-path"
### Expected behavior

Chafa shows the image

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

I dont use Vim.

### Operating system/version

Endeavour OS  6.1.11-arch1

### Terminal name/version

yakuake 22.12.2

### $TERM environment variable

xterm-256color

### Installation

Arch pacman

**Comment by zeertzjq** [comment]
It works after `:unlet $KONSOLE_VERSION`

**Comment by zeertzjq** [comment]
Related: #4349

**Comment by TroySigX** [comment]
will unlet disable any of the feature in konsole?
