### ISSUE TITLE
Error fetching file during 'make' step of homebrew build

### ISSUE THREAD

**Issue by dpathakj** [neovim/neovim#2223]
Ran `brew tap neovim/homebrew-neovim` and `brew install --HEAD neovim` and got this output. Seems odd--mostly, Homebrew packages seem to need to download no more dependencies by the time `make` gets run.

Retrying worked, but I thought I'd report it.

```
==> make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/usr/local/Cellar/neovim/HEAD" install
Error: Error fetching file: Failed downloading https://github.com/Olivine-Labs/luassert/archive/v1.7.2.tar.gz
make[3]: *** [usr/lib/luarocks/rocks/stable-busted-deps] Error 1
make[2]: *** [CMakeFiles/stable-busted-deps.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/neovim/homebrew-neovim/issues
```

**Comment by Pyrohh** [comment]
I'm not sure it makes a difference, but are you running `brew tap neovim/homebrew-neovim; brew install --HEAD neovim` as one line, or separately?

If you ran `brew tap neovim/homebrew-neovim && brew install --HEAD neovim` instead, then `brew` wouldn't try to install if `tap` failed.

Also, it says to report to [homebrew-neovim](https://github.com/neovim/homebrew-neovim).

**Comment by dpathakj** [comment]
I ran them as separate commands and the first succeeded. I've edited the comment to make this clearer.

**Comment by forbesmyester** [comment]
My output looks like this:

    $ brew install  --HEAD neovim
    ==> Installing neovim from neovim/homebrew-neovim
    sudo: unable to resolve host dread
    ==> Cloning https://github.com/neovim/neovim.git
    Updating /home/fozz/.cache/Homebrew/neovim--git
    ==> Checking out branch master
    ==> Downloading https://github.com/libuv/libuv/archive/v1.4.2.tar.gz
    Already downloaded: /home/fozz/.cache/Homebrew/neovim--libuv-1.4.2.tar.gz
    ==> Downloading https://github.com/msgpack/msgpack-c/archive/cpp-1.0.0.tar.gz
    Already downloaded: /home/fozz/.cache/Homebrew/neovim--msgpack-1.0.0.tar.gz
    ==> Downloading http://luajit.org/download/LuaJIT-2.0.3.tar.gz
    Already downloaded: /home/fozz/.cache/Homebrew/neovim--luajit-2.0.3.tar.gz
    ==> Downloading https://github.com/keplerproject/luarocks/archive/0587afbb5fe8ceb2f2eea16f486bd6183bf02f29.tar.gz
    Already downloaded: /home/fozz/.cache/Homebrew/neovim--luarocks-29.tar.gz
    ==> Downloading https://github.com/mauke/unibilium/archive/v1.1.2.tar.gz
    Already downloaded: /home/fozz/.cache/Homebrew/neovim--libunibilium-1.1.2.tar.gz
    ==> Downloading https://github.com/neovim/libtermkey/archive/8c0cb7108cc63218ea19aa898968eede19e19603.tar.gz
    Already downloaded: /home/fozz/.cache/Homebrew/neovim--libtermkey-19603.tar.gz
    ==> Downloading https://github.com/neovim/libvterm/archive/1b745d29d45623aa8d22a7b9288c7b0e331c7088.tar.gz
    Already downloaded: /home/fozz/.cache/Homebrew/neovim--libvterm-7088.tar.gz
    ==> make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/home/fozz/.linuxbrew/Cellar/neovim/HEAD" install
    Makefile:75: recipe for target 'all' failed
    make[1]: *** [all] Error 2
    make[1]: Leaving directory '/tmp/neovim20150327-14084-171elxq/.deps'
    Makefile:68: recipe for target 'deps' failed
    make: *** [deps] Error 2

**Comment by forbesmyester** [comment]
https://gist.github.com/anonymous/e75a1b1d2a1761103f19

**Comment by jszakmeister** [comment]
CMake prefers its bundled version if libcurl.  Did you build CMake yourself?  Is it the system supplied one?  See this [note](https://github.com/neovim/neovim/issues/1469#issuecomment-63058312) to build CMake with SSL support.

**Comment by forbesmyester** [comment]
the curl on the system works with HTTPS.

I did not make CMake except perhaps as part of the neovim install itself. I've not used linuxbrew for anything before and I think it built CMake during that process (though I may be wrong)

**Comment by jszakmeister** [comment]
A recent update to Homebrew's CMake formula broke SSL support.  See Homebrew/homebrew#38147 for more details.
