### ISSUE TITLE
Add ability to viewer pdf and images in Neovim terminal

### ISSUE THREAD

**Issue by TroySigX** [neovim/neovim#22240]
### Problem

When I type nvim "pdf-path", it'd be nice to see the image, not some random binary characters.

### Expected behavior

Be able to view the image/pdf directly in Neovim

**Comment by clason** [comment]
And how exactly would that work in a text-based terminal?

**Comment by TroySigX** [comment]
Maybe you can integrate sixel or kitty protocol? I can see that neovim can actually show images in its terminal with the command viu "image-path", but it's really inconvenient to do that for every image path that I'd rather manually open them myself.

**Comment by clason** [comment]
That's a duplicate of #12991 and #4500.

**Comment by TroySigX** [comment]
The hologram.nvim only shows image when we type the image path in the current file/buffer. So I figure it should be a feature request in hologram?
