### ISSUE TITLE
Execute `vim.lsp.buf.format` while `lua_ls` is loading the workspace will lose changed

### ISSUE THREAD

**Issue by leonasdev** [neovim/neovim#22254]
### Neovim version (nvim -v)

v0.9.0-dev-944+g89722ddfa

### Language server name/version

lua-language-server 3.6.11

### Operating system/version

Ubuntu 22.04

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
local pattern = 'lua'
local cmd = { 'lua-language-server' }
-- Add files/folders here that indicate the root of a project
local root_markers = { '.git', '.editorconfig' }
-- Change to table with settings if required
local settings = {
  Lua = {
    workspace = {
      library = {
        vim.api.nvim_get_runtime_file("", true), vim.fn.stdpath("config")
      }
    },
  }
}

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or vim.NIL
    vim.lsp.start({
      name = 'bugged-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```

### Expected behavior

If you enter a buffer and do some modifications and execute `vim.lsp.buf.format` **while lua_ls is loading the workspace**, all your modifications should not be lost and the buffer should be formatted. 

### Actual behavior

If you enter a buffer and do some modifications and execute `vim.lsp.buf.format` **while lua_ls is loading the workspace**, all your modifications will be lost but the buffer is formatted correctly. 

### Log file

No output

**Comment by mfussenegger** [comment]
If the language server returns a text edit that's removing everything that's a language server but.  The client is only doing that it's told to do

**Comment by leonasdev** [comment]
> If the language server returns a text edit that's removing everything that's a language server bug. The client is only doing what it's told to do

How could I distinguish between Neovim passing a wrong input or language-server returning a wrong output?

**Comment by mfussenegger** [comment]
The format request only contains the document URI and the formatting options. That's the same whether the language server is loading the workspace or not, so there isn't much that could go wrong on the client side.

**Comment by dtomvan** [comment]
Sorry for reviving this thread, but how would I check wether I can format-on-save or not? I would need to know wether lua_ls is done "Loading Workspace", but `vim.lsp` doesn't seem to have an API for it.
