### ISSUE TITLE
enter / exit fullscreen mode causes error

### ISSUE THREAD

**Issue by erf** [neovim/neovim#2226]
When i enter and then exits fullscreen mode in terminal on osx, cursor get's stuck in bottom with numbers showing as i type.

neovim version: NVIM 0.0.0-alpha+201503222117
osx version: 10.10.2 (14C1514)

**Comment by erf** [comment]
ah. it is caused when using 'bling/vim-airline' ..

**Comment by erf** [comment]
It only seems to happens when i syntax is on. Or colors are enabled from plugin like 'bling/vim-airline'.

**Comment by blueyed** [comment]
See also #2322 (duplicate).

**Comment by Pyrohh** [comment]
The other bug report is more descriptive, so I'll close this (thanks @blueyed).

**Comment by blueyed** [comment]
I am seeing "numbers" at the bottom of the window, too - it's the statusline (col/row?!) being (partially redrawn) there.

**Comment by Pyrohh** [comment]
> it's the statusline (col/row?!) being (partially redrawn) there.

That sounds like a side effect of what is described in #2322, no? I'm just making sure, because you initially said these issues were duplicates of each other.

**Comment by blueyed** [comment]
Yes, it's a side effect.
I was just confirming that it's a duplicate.
