### ISSUE TITLE
Neovim freezes after creating new kitty tab

### ISSUE THREAD

**Issue by joelpeapen** [neovim/neovim#22269]
I have a function that opens up a new kitty tab to the current directory of a neovim buffer. The function works fine, but when I switch back to the other tab, it's frozen.

```
function KittyNewTab()
    local command = [[ kitty @launch --type=tab --cwd="{dir}" ]]

    command = command:gsub('{dir}', vim.fn.getcwd())
    os.execute(command)
end
vim.keymap.set("n", "<leader>pt", function() KittyNewTab() end)
```

### Steps to reproduce

Invoke the function

### Neovim version

v0.8.3 129264d

### Operating system/version

Ubuntu 22.04.1 LTS

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

appimage

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by joelpeapen** [comment]
updated kitty but the problem persists.

**Comment by joelpeapen** [comment]
it unfreezes after a couple minutes though
