### ISSUE TITLE
Opening .py files crashes if Python 3.10 is active, but not Python 3.9 or 3.11

### ISSUE THREAD

**Issue by ckp95** [neovim/neovim#22261]
### Describe the bug

OS: Ubuntu 22.04.1 LTS on WSL Windows 10
Neovim version: 0.6.1, installed via apt

When I run `nvim foo.py` or try to save an existing buffer as `:w foo.py`, depending on which version of Python is active, Neovim will crash with the error message:

```
nvim: ./src/unix/core.c:258: uv__finish_close: Assertion `handle->flags & UV_HANDLE_CLOSING' failed.
```

(this also has the side effect of sending some janky terminal escape sequences and screwing up my shell prompt, I have to restart the shell)

**This happens with a fresh install of Neovim, with no config file or plugins.**

I discovered that this only happens when certain versions of Python are found on the PATH. I use pyenv to manage Python versions. Example:

```
$ pyenv global 3.9.16
$ python --version
Python 3.9.16
$ nvim foo.py # works
$ pyenv global 3.10.1
 $ python --version
Python 3.10.1
$ nvim foo.py # crashes
```

It works for Python 3.9.16 and 3.11.1, but not for any Python 3.10 version.

### Steps to reproduce

- have the current version of python be 3.10.x
- open `nvim foo.py`

### Expected behavior

- neovim should not crash

### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

idk

### Operating system/version

Ubuntu 22.04.1 LTS on WSL Windows 10

### Terminal name/version

Alacritty

### $TERM environment variable

screen

### Installation

apt

**Comment by ckp95** [comment]
Update: I have fixed it by adding the following to my `init.vim`, as per [this comment](https://github.com/neovim/neovim/issues/14586#issuecomment-939946909).

```
let g:python3_host_prog = "$PYENV_ROOT/shims/python3"
```

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/20270

**Comment by ckp95** [comment]
>that is years old. always try latest development Nvim

that's what's in the apt repository.

**Comment by Shougo** [comment]
APT package is very old unfortunately.

**Comment by RobertoMaurizzi** [comment]
Just bumped into this on 22.04 on WSL, using neovim 0.9.1 downloaded with bob (because frack snaps)
I can't really get why it should crash with 3.10 while it works with 3.8, 3.9 and 3.11 but the fix does work...

**Comment by cultab** [comment]
> Just bumped into this on 22.04 on WSL, using neovim 0.9.1 downloaded with bob (because frack snaps) I can't really get why it should crash with 3.10 while it works with 3.8, 3.9 and 3.11 but the fix does work...

same, I have a suspicion that the problem in my case is that pylsp finds `pyenv` to be in the PATH but it's from windows (and pyenv is not even officially supported on windows). Testing now..

Yep:
Nuking `C:\Users\<user>\.pyenv` also solves the issue
