### ISSUE TITLE
Arrow keys in insert mode breaks single repeat.

### ISSUE THREAD

**Issue by m4xshen** [neovim/neovim#22280]
### Describe the bug

Using arrow keys in insert mode breaks single repeat. It only repeat the last part of the commands typed after arrow keys.

### Steps to reproduce

nvim --clean
ia\<Left>b\<Esc>.

result: `bba`

### Expected behavior

`baba`

### Neovim version (nvim -v)

v0.9.0-dev-694+g6134c1e8a

### Vim (not Nvim) behaves the same?

yes, vim 9.0.1302

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

Release Build

**Comment by zeertzjq** [comment]
```
2. Special special keys				*ins-special-special*

The following keys are special.  They stop the current insert, do something,
and then restart insertion.  This means you can do something without getting
out of Insert mode.  This is very handy if you prefer to use the Insert mode
all the time, just like editors that don't have a separate Normal mode. You
can use CTRL-O if you want to map a function key to a command.
```
