### ISSUE TITLE
Examine output of external command

### ISSUE THREAD

**Issue by sakhnik** [neovim/neovim#2229]
Previously it was possible to examine output of an external command (make, for instance) in the terminal. With recent changes to neovim, this wouldn't work any more:

1. Start `nvim`
2. Execute `:!for i in $(seq 1 1000); do echo $i; done`
3. Type `^Z`

Expectation: The terminal shows listed numbers.
Reality: No output from external commands launched from neovim.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/1716
