### ISSUE TITLE
If you run a endless-loop program in terminal, you cannot interrupt it by <C-c>

### ISSUE THREAD

**Issue by ysl2** [neovim/neovim#22295]
### Describe the bug

I write a code to test it:

```c
// main.c
#include <stdio.h>

int main()
{
    int i = 1;
    while (i > 0)
    {
        printf("%d", i);
        ++i;
    }
    return 0;
}
```

I compiled it and ran in nvim terminal (powershell 7 as backend), but cannot interrupt it.

I also tried the external terminal, it can interrupt the program normally.

Update:

1. I switched to linux and use bash as nvim terminal beckend, it can interrupt the program.

     So the bug is related to specific terminal, and powershell 7 cannot interrupt c endless-loop program.

2. I rewite the script by python, and both powershell 7 and bash can interrupt.

     So the bug is also related to specific language.

    ```python
    def temp():
        i = 1
        while i > 0:
            print(i)
            i += 1


    if __name__ == '__main__':
        temp()
    ```

### Steps to reproduce

Just follow above steps.

### Expected behavior

The program can be interrupted by `<C-c>` at any time.

### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

Sorry, I don't know that.

### Operating system/version

Windows 10 and Ubuntu 20.02

### Terminal name/version

powershell 7 and bash

### $TERM environment variable

Don't know.

### Installation

Microsoft store

**Comment by glepnir** [comment]
i can not reproduce it on mac

**Comment by 3N4N** [comment]
Is it a pwsh-only bug?  @glepnir did reproduce it on mac with pwsh?

**Comment by zeertzjq** [comment]
Can't reproduce on Linux using pwsh

**Comment by ysl2** [comment]
I think it might be only on windows?

**Comment by 3N4N** [comment]
I cannot reproduce it in Windows either.  Here are the steps I used:

```
PS> nvim --clean main.c
:vs
:te
cmd> pwsh
PS> gcc main.c   # using mingw toolchain
PS> .\a.exe
Ctrl-C
```

@ysl2 provide full repro steps or a GIF reproducing the bug if you can.

**Comment by ysl2** [comment]
I use clang, and in real windows environment, not in mingw or cygwin etc.

**Comment by 3N4N** [comment]
I cannot reproduce with clang either.

**Comment by 3N4N** [comment]
Could you try using command prompt instead of pwsh and report what happens?  Also, try pwsh without your personal configuration (`pwsh -Nop`).

**Comment by 3N4N** [comment]
Maybe this issue can be closed.

**Comment by clason** [comment]
Let's slap a `needs:response` label on it again and let it autoclose (if none of us comment on it afterwards).

**Comment by ysl2** [comment]
Close beacuse I have no time to test more and I have another way to bypass this problem. But the bug was indeed happened. I'm not kidding.
