### ISSUE TITLE
Grey SignColumn in light mode

### ISSUE THREAD

**Issue by fjbaldon** [neovim/neovim#22306]
### Describe the bug

https://imgur.com/a/2SHKDVv

### Steps to reproduce

Use gnome-console and change theme to light mode. SignColumn in dark mode seems fine.

https://imgur.com/a/2SHKDVv

### Expected behavior

SignColumn should be white or should at least be following terminal background.

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

Idk.

### Operating system/version

Fedora 37

### Terminal name/version

gnome-console

### $TERM environment variable

xterm-256color

### Installation

rpm

**Comment by zeertzjq** [comment]
> SignColumn should be white or should at least be following terminal background.
