### ISSUE TITLE
Abbreviation doesn't expand when mapping `<c-c>` to `<Esc>` with `vim.keymap.set`

### ISSUE THREAD

**Issue by pedro757** [neovim/neovim#22305]
### Describe the bug

I have the following keybinding in my config

```lua
vim.keymap.set("i", "<c-c>", "<Esc>")
vim.cmd("abbreviation foo bar")
```

If  I type `foo` and press `<c-c>` right after the last `o`, it will not expand the abbreviation like it does with normal `<Esc>`

This only happens with the new `vim.keymap.set` functionality, if I use vimscript it works `imap <c-c> <Esc>`

## This doesn't work
```lua
vim.keymap.set("i", "<c-c>", "<Esc>")
vim.cmd("abbreviation foo bar")
```

Type `foo` and press `<c-c>` right after
Type `foo` and press `<Esc>` right after, see the difference.

---
## This works
```lua
vim.cmd("imap <c-c> <Esc>")
vim.cmd("abbreviation foo bar")
```

This actually works fine

Type `foo` and press `<c-c>` right after, it works 
Type `foo` and press `<Esc>` right after, it works 

### Expected behavior

It should expand the abbreviation like it does with `<Esc>` because I mapped `<c-c>` to `<Esc>`

### Neovim version (nvim -v)

NVIM v0.9.0-dev-964+g1539f7136

### Vim (not Nvim) behaves the same?

Vimscript works fine

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

AUR

**Comment by zeertzjq** [comment]
`vim.keymap.set("i", "<c-c>", "<Esc>", {remap = true})`

**Comment by pedro757** [comment]
This worked `vim.keymap.set("i", "<c-c>", "<Esc>", {remap = true})`

I forgot now remap is false by default, I'm sorry.
