### ISSUE TITLE
Pluggable tags provider

### ISSUE THREAD

**Issue by benjumanji** [neovim/neovim#2232]
It would be neat if one could write a code search plugin that could be called with the current cursor location and open file name when the tags commands are used. For instance jumping to shadowed bindings in haskell can be a pain, and it should be possible for languages amenable to static analysis to always jump to the right identifier.

I don't think that this is possible as it stands.

To be clear: I am asking for hooks so that one can *override* `:tag` and friends to do smarter things if a plugin is available.

**Comment by tarruda** [comment]
> To be clear: I am asking for hooks so that one can override :tag and friends to do smarter things if a plugin is available.

 YouCompleteMe provides a `GoToDefinitionElseDeclaration` command that one can map to `<c-]>`, effectively replacing the builtin tag  jump. Isn't it simpler for a plugin to implement a custom command? Why is it better to override the builtin `:tag` for this?

**Comment by justinmk** [comment]
I've yet to see a reason that we should open the can of worms that is "override builtin commands and functions". But we will surely add more events where appropriate, and possibly a general (provider) framework for "code inspection". We don't really need yet another issue suggesting this though.

**Comment by benjumanji** [comment]
@tarruda The idea of overrideing tags is just that there are already a bunch of commands there and people will always already have bindings for them, but sure, you can always have a plugin hand have people override them with fall-backs etc like vim-oblique.

@justinmk 

>  We don't really need yet another issue suggesting this though.

I spent a good 10 minutes searching every open and closed issue with the word tags in it. I didn't find anything related to this. Next time you think something is not a good fit for this project, try handling it with a little more grace.

**Comment by chrisbra** [comment]
Am 2015-03-24 06:50, schrieb Justin M. Keyes:
> I've yet to see a reason that we should open the can of worms that is
> "override builtin commands and functions". But we will surely add more
> events where appropriate, and possibly a general (provider) framework
> for "code inspection". We don't really need yet another issue
> suggesting this though.

Note there is a tagfunc() patch floating around (I have cleaned it up
in the past: 
https://github.com/chrisbra/vim-mq-patches/blob/master/tagfunc
but not sure, if it applies cleanly to Vim HEAD).

Cheers,
Christian

**Comment by justinmk** [comment]
@chrisbra Your patch seems to fit in the "provider" pattern. We could adapt it to work our the Neovim provider framework (which isn't finalized), and thus avoid the extra 'tagfunc' option.
