### ISSUE TITLE
checkhealth error

### ISSUE THREAD

**Issue by dat-le-4** [neovim/neovim#22328]
### Describe the bug

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /Users/datle/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|
  - ERROR: shada file is not writeable:
    /Users/datle/.local/state/nvim/shada/main.shada

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='Apple_Terminal'

provider: health#provider#check

### Steps to reproduce

:checkhealth

### Expected behavior

no error

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos 13.2.1

### Terminal name/version

default terminal

### $TERM environment variable

na

### Installation

homebrew

**Comment by dat-le-4** [comment]
Also this:

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - ERROR: Failed to run healthcheck for "vim.lsp" plugin. Exception:
    function health#check, line 20
    Vim(eval):E5108: Error executing lua Vim:E739: Cannot create directory /Users/datle/.local/state/nvim: permission denied
    stack traceback:
    [C]: in function 'mkdir'
    ...llar/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp/log.lua:44: in main chunk
    [C]: in function 'require'
    ...r/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp/health.lua:8: in function 'check'
    [string "luaeval()"]:1: in main chunk

vim.treesitter: require("vim.treesitter.health").check()

**Comment by mfussenegger** [comment]
Check your permissions. Looks like several folders/ files lack write permissions.
