### ISSUE TITLE
(re-)allow hovers from language servers of other buffers

### ISSUE THREAD

**Issue by jmbuhr** [neovim/neovim#22323]
### Describe the bug

I wrote a plugin to enable language features for code embedded in other documents (e.g. markdown code blocks) by maintaining hidden buffers with only the language content and relaying language server requests to those hidden buffers. This enables things like autocompletion, go to definition and hover documentation.

But hover documentation will be broken by https://github.com/neovim/neovim/commit/cfdf5e6f372928c11a2b1459b14c4c2de5f69c51 because it explicitly disables hovers that come from buffers other than the current one.

### Steps to reproduce

See https://github.com/quarto-dev/quarto-nvim/issues/32

### Expected behavior

Hovers from other buffers can still be shown. Some form of opt-in or opt-out via a flag is necessary to serve both usecases.

### Neovim version (nvim -v)

v0.9.0-dev-974+g631775c05d

### Vim (not Nvim) behaves the same?

no

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

apt

**Comment by glepnir** [comment]
try use `api.nvim_buf_call`

**Comment by jmbuhr** [comment]
This does allow me to open up the hover, but the hover won't close again (due to being executed in another buffer) and it breaks the other lsp requests I am handling like go to defintion.

The cleanest solution would be a different solution to https://github.com/neovim/neovim/commit/cfdf5e6f372928c11a2b1459b14c4c2de5f69c51 , as this makes hovers handle differently from other lsp requests and introduces arbitrary constraints. I will try to come up with something as well. In its current form I think this is a regression.

**Comment by glepnir** [comment]
also why you don't try rewrite the default handler in your local ?

```lua
vim.lsp.handler['textDocument/hover'] = function(_, result)
  --your logic.
end
```

**Comment by jmbuhr** [comment]
Thanks for the suggestion! But won't this break or not work for users that configured their handlers e.g. to use a certain type of border for hover windows?

I think the default handler shouldn't make an assumption about the buffer, since all the other handlers don't do so either (this is handled by the request and response content). The commit I linked that introduces this assumption also mentions that it is a workaround for which we would eventually need a better solution. So I would prefer to not release it in in its current form to not break uses of the api. Otherwise I'll end up with a workaround around a workaround in my plugin.

**Comment by glepnir** [comment]
like i said you can use `lsp.buf_request` or `lsp.buf_request_all` to do it in your plugin.  it not break any handlers. 

```lua
 vim.lsp.buf_request(buffernumber, 'textDocument/hover', params, function(_, result, ctx)
         -- your logic
 end)
```

examplay what i do in lspsaga https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/hover.lua

**Comment by jmbuhr** [comment]
Thanks you for your helpful comments! I am indeed already using that and have now added my own handler to handle hovers (just a copy and past of the nvim one without the buffer check) here: https://github.com/jmbuhr/otter.nvim/pull/19/commits/f29a9f303a956c266c19d36598f3f0edb6a23bbc. This works, but can be improved.

By handling the hover in the plugin I am loosing user configuration done with `vim.lsp.with`, e.g. a user may have something like this in their config:

```lua
    vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(vim.lsp.handlers.hover,
      { border = ....... })
```

I tried various debugging functions to get the `config` out of the overwritten handler function, but was unable to to so.
Do you know if this is possible? Thanks for all your help!

**Comment by justinmk** [comment]
> I tried various debugging functions to get the `config` out of the overwritten handler function, but was unable to to so.

With https://github.com/neovim/neovim/pull/22598 you could sniff the `config` via:

```lua
vim.on_fun(vim.lsp.handlers, 'textDocument/hover', function(...)
  return function(err, result, ctx, config)
    -- `config` passed here is the user-specified config,
    -- assuming your plugin called vim.on_fun() after the user.
  end, ...
end)
```

this is kinda hacky though.

**Comment by lewis6991** [comment]
`vim.lsp.handlers["textDocument/hover"]` is no longer used.

To address the requirement here, one needs to implement a custom version of `vim.lsp.buf.hover()`.

**Comment by justinmk** [comment]
> To address the requirement here, one needs to implement a custom version of `vim.lsp.buf.hover()`.

Do we have (or do you plan to) guidance on that in the docs?

**Comment by lewis6991** [comment]
The request here is pretty advanced. It's essentially to enable LSP features in injected languages. What kind of guidance could we suggest? I would have thought it should be fairly straightforward for anyone working in this area to use our source code for guidance.

**Comment by jmbuhr** [comment]
Schema for how this works: https://github.com/jmbuhr/otter.nvim?tab=readme-ov-file#a-group-of-otters-is-called-a-raft

**Comment by jmbuhr** [comment]
I believe it should still work with https://github.com/neovim/neovim/pull/30935 because otter will modify the response before passing it on to the (new) neovim hover handler and pretend it is coming from the current buffer:

https://github.com/jmbuhr/otter.nvim/blob/ca9ce67d0399380b659923381b58d174344c9ee7/lua/otter/lsp/handlers.lua#L21-L37

```lua
--- see e.g.
--- vim.lsp.handlers.hover(_, result, ctx, conf)
---@param err lsp.ResponseError?
---@param response lsp.Hover
---@param ctx lsp.HandlerContext
M[ms.textDocument_hover] = function(err, response, ctx, conf)
  if not response then
    -- no response, nothing to do
    return
  end


  -- pretend the response is coming from the main buffer
  ctx.params.textDocument.uri = ctx.params.otter.main_uri


  -- pass modified response on to the default handler
  return err, response, ctx, conf
end
```

Thanks for tagging me (or this issue) on this! I will test this with the latest nightly.

**Comment by jmbuhr** [comment]
Tested and still works :)
