### ISSUE TITLE
setreg() converts nul (0x00) characters to newlines

### ISSUE THREAD

**Issue by Rich-YoYo** [neovim/neovim#22333]
### Describe the bug

When the string passed to setreg() contains null (0x00) characters, they are converted to newline (0x0a) characters

### Steps to reproduce

:call setreg('r', nr2char(0))

Examination of register 'r' will show that it contains a single newline (0x0a) character and not a nul (0x00)

### Expected behavior

I expect setreg() to not translate any part of the string passed to it, and to preserve it

### Neovim version (nvim -v)

0.8.3 

### Vim (not Nvim) behaves the same?

Almost, but worse - issue #12027 raised with Vim 

### Operating system/version

Void Linux 19/02/2023 (rolling release)

### Terminal name/version

Terminology

### $TERM environment variable

xterm

### Installation

Void Linux binary package

**Comment by zeertzjq** [comment]
Cannot reproduce. And `nr2char(0)` is an empty string.
