### ISSUE TITLE
Config option order changes nvim behavior (cursor shape bug in python files)

### ISSUE THREAD

**Issue by demiler** [neovim/neovim#22331]
### Describe the bug

I use I-beam cursor and keep cursor shape the same no matter vim mode, so I have `set guicursor=` option in my config. I also have option `syntax on` which doesn't look necessary anymore but it's persist since classic .vimrc.

If I open python file (with `nvim file.py` and not `:e file.py`, `:tabe file.py`, etc), then cursor becomes a blinking block and it also hides letter while blinking instead of changing it's color: e.g. `im[p]ort  smth` becomes `im[ ]ort smth` (cursor represented with `[]`)

I haven't tested much, but it seem to affect only python files and only if both `set guicursor=` and `syntax on` are used in config. The more important thing is that order of this options matter in this bug: if `syntax on` comes after `set guicursor=` - bug is not present.

### Steps to reproduce

Bug can be reproduced with this config
```
" Explicitly enable syntax highlighting
syntax on
" Disable cursor shape feature
set guicursor=
```
Open any python file from shell
`nvim something.py`

### Expected behavior

Config option order shouldn't affect nvim behavior.   

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

9.0

### Operating system/version

Arch Linux, 6.1.7-arch1-1

### Terminal name/version

konsole 22.12.1

### $TERM environment variable

xterm-256color

### Installation

pacman

**Comment by clason** [comment]
Do not use `syntax on` in your Neovim config (unless you know _exactly_ what you're doing).

`syntax` is _not_ an option (that would be `:set syntax=fortran`) but a command, so of course order matters.

**Comment by zeertzjq** [comment]
This happens because Python ftplugin calls `has('python3')`, which calls `system()`, which changes cursor shape, so I don't there is anything that can be done about this issue.
