### ISSUE TITLE
 Segfault for buffer command executed with command-line window open

### ISSUE THREAD

**Issue by lervag** [neovim/neovim#22339]
### Describe the bug

There is a segfault (or similar) for buffer command executed with command-line window open.

This is a duplicate of https://github.com/vim/vim/issues/12029 as it affects neovim as well.

### Steps to reproduce

Given this very minimal vimrc file:

```vim
" test.vim
command! -buffer Test edit Test
```

loaded with `nvim --clean -u test.vim`. Now:

1. Do `q:` to open command-line window.
2. Do `:Test<cr>` (note the initial `:`!).
3. Neovim stops with noe message (looks like a segfault).

### Expected behavior

The command uses an `edit`, which is not allowed when we run commands on top of command-line window. If we remove `-buffer` we observe the expected behaviour, which is to issue the following error:

```
E11: Invalid in command-line window; :q<CR> closes the window: edit Test
```

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1009+gf1816f9ee2

### Vim (not Nvim) behaves the same?

Yes (Vim 9.0.1302)

### Operating system/version

Arch Linux

### Terminal name/version

rxvt-unicode (urxvt) v9.31

### $TERM environment variable

rxvt-256color

### Installation

AUR

**Comment by zeertzjq** [comment]
This fixes the crash:
```diff
diff --git a/src/nvim/usercmd.c b/src/nvim/usercmd.c
index 3a5a4c3e9..6869f7eaf 100644
--- a/src/nvim/usercmd.c
+++ b/src/nvim/usercmd.c
@@ -1625,7 +1625,7 @@ int do_ucmd(exarg_T *eap, bool preview)
   if (eap->cmdidx == CMD_USER) {
     cmd = USER_CMD(eap->useridx);
   } else {
-    cmd = USER_CMD_GA(&curbuf->b_ucmds, eap->useridx);
+    cmd = USER_CMD_GA(&prevwin_curwin()->w_buffer->b_ucmds, eap->useridx);
   }
 
   if (preview) {
```

**Comment by lervag** [comment]
I assume this should be applied "upstream" for Vim first? I'll link your reply there.
