### ISSUE TITLE
[bug] Sometimes resizing a windows stops working

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2234]
at which point dragging a status line or a vertical separator causes the current tab to be dragged, repositioning the tab instead of resizing the a window. No drag ever happened on any tab, but the drag happens to drag the current tab to reposition it.

**Comment by mbaschnitzi** [comment]
I experienced the same bug.
Way to reproduce:
Open two tabs, drag one tab around, or only click on it with the mouse.
Now open a split in one tab and try to resize it.

As long as you don't click on the tab bar, resizing works. As soon as you click on the bar the first time resizing of windows/splits doesn't work anymore. Instead the mouse action seems to be caught by the tab bar so the tabs are dragged around instead of window resizing.

**Comment by tarruda** [comment]
are both of you using OSX?

**Comment by tejo** [comment]
same here with OSX

**Comment by mbaschnitzi** [comment]
I am using Debian Testing. I have tested this behaviour with st (suckless terminal) and konsole. I am also using tmux inside of the terminal, but the issue also happens without tmux.
As far as i could test this, this behaviour is reproducible in all those terminals by using an config with only
```viml
set mouse=a
```
and following the above steps.

**Comment by trusktr** [comment]
About the mouse action getting stuck with the tab, true, but I've noticed
it happens at some point even if I've never clicked in the tab bar at all.
I'll come back and comment if I determine this other way to reproduce.

On Tuesday, March 31, 2015, mbaschnitzi <notifications@github.com> wrote:

> I am using Debian Testing. I have tested this behaviour with st (suckless
> terminal) and konsole. I am also using tmux inside of the terminal, but the
> issue also happens without tmux.
> As far as i could test this, this behaviour is reproducible in all those
> terminals by using an config with only
>
> set mouse=a
>
> and following the above steps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neovim/neovim/issues/2234#issuecomment-88059188>.
>


-- 
/#!/JoePea

**Comment by justinmk** [comment]
Hopefully fixed after https://github.com/neovim/neovim/pull/3171
