### ISSUE TITLE
<S-Space> interpreted as space

### ISSUE THREAD

**Issue by Kyran-C** [neovim/neovim#22359]
### Describe the bug

Using Kitty terminal, shift space is still interpreted as a normal space. Other key combinations work fine.

To verify that kitty is interpreting the key properly, run:
```sh
kitty +kitten show_key -m kitty
```
and press shift-space.

### Steps to reproduce

nvim --clean
enter insert mode and press ctrl-v
press shift-space

### Expected behavior

Neovim should insert `<S-Space>` rather than a regular space character.

### Neovim version (nvim -v)

0.9.0-dev-1012+g3264cb294

### Vim (not Nvim) behaves the same?

I can't get vim to recognize any extended modifier keys for some reason

### Operating system/version

Arch Linux (btw)

### Terminal name/version

Kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

AUR (neovim-nightly-bin)

**Comment by zeertzjq** [comment]
Tracked in #14409
