### ISSUE TITLE
[builtin-term] Applications inside :term don't redraw if terminal dimensions change

### ISSUE THREAD

**Issue by Pyrohh** [neovim/neovim#2235]
(copied from https://github.com/neovim/neovim/pull/2076#issuecomment-84741421)

Here's how I reproduced the issue:
- Start a terminal (I'm using `st` from git, but the issue also shows up in `uxterm`)
- Make sure `ncmpc` is using vanilla settings (i.e., `rm -r ~/.ncmpc`, not sure if it makes a difference)
- Start `nvim -u NONE` (you said `-N` but IIRC it's a no-op)
- Run `:term`, then launch `ncmpc`, then press the `3` key to switch to the "Browse" tab in ncmpc

The screen should look similar to this:

![half](https://cloud.githubusercontent.com/assets/4174345/6772472/82a55faa-d0d5-11e4-8d8e-c5b50c310e2e.png)

I then make the `st` window containing `nvim` (which contains `ncmpc`) fullscreen:

![full](https://cloud.githubusercontent.com/assets/4174345/6772489/1b18e69e-d0d6-11e4-8270-edc32aace2df.png)

In order to have everything redrawn, I have to switch to tab 1, then back to tab 3 (just press `1` then `3`). After that, it looks normal:

![full-fixed](https://cloud.githubusercontent.com/assets/4174345/6772527/0a193abe-d0d7-11e4-97a8-f06a09f1ff24.png)

**Comment by jdavis** [comment]
You have good taste in music =]

**Comment by Pyrohh** [comment]
I spend too much time on what.cd...

**Comment by jdavis** [comment]
I don't know what you are talking about. ![rippy](https://cloud.githubusercontent.com/assets/157801/6795555/fb0cd116-d19e-11e4-8dde-4786a5aa3779.png)

**Comment by Pyrohh** [comment]
ayyyyyyyyyyyyyyyyyyyyy

Okay enough of that heh.

**Comment by tarruda** [comment]
@Pyrohh just to be clear, does the resize happens after a few seconds?

**Comment by tarruda** [comment]
@Pyrohh fixed the problem and it was actually caused by a long hidden bug that was only uncovered by the terminal branch. Can you test/confirm?

**Comment by Pyrohh** [comment]
@tarruda Yes, but now I coredump whenever I `:q`, and I coredump whenever I'm generating helptags during `sudo make install`.

**Comment by tarruda** [comment]
@Pyrohh should be fixed now

**Comment by Pyrohh** [comment]
Yes, it's fixed :)
