### ISSUE TITLE
hlsearch selects incorrect range in the presence of unicode characters

### ISSUE THREAD

**Issue by srikumarks** [neovim/neovim#22361]
### Describe the bug

<img width="305" alt="image" src="https://user-images.githubusercontent.com/117721/220519955-b633b5e2-bc5c-46e2-9640-b441007cdb6c.png">
<img width="305" alt="image" src="https://user-images.githubusercontent.com/117721/220520006-328608ae-73e0-4b49-81d7-cbc35e8c974e.png">
<img width="305" alt="image" src="https://user-images.githubusercontent.com/117721/220520042-83b5fca7-b09c-4325-a152-d930f8ab28b6.png">

Using unicode symbols in Julia code is common and the above examples are from a small test snippet that uses a "vector combining character". In this case, it looks like neovim (and vim) counts the vector symbol as a separate character and therefore misplaces its highlight when highlighting a search. It also ends up blanking out a few characters as part of the misplaced highlight.

The search itself isn't a problem as the cursor correctly lands on the first character of the searched word. The problem is only with the highlight. If I turn off hlsearch with `:set nohlsearch`, it is clear and there is no confusion.  

### Steps to reproduce

```
dot(u⃗, v⃗) = sum(u⃗ .* v⃗)
mag(v⃗) = sqrt(dot(v⃗, v⃗))
unit(v⃗) = v⃗ / mag(v⃗)
```

1. Copy paste the above code into a neovim session
2. Ensure hlsearch is on using `:set hlsearch`
3. Place cursor on "dot" on the first line.
4. Press "*" key to search for other occurrences of `dot`.
5. You'll see that the occurrence on the second line is mis-highlighted.

This problem does not occur if the vector combining characters are not present, as with the code below -

```
dot(u,v) = sum(u .* v)
mag(v) = sqrt(dot(v,v))
unit(v) = v / mag(v)
```

### Expected behavior

The correct searched word is highlighted by hlsearch, taking unicode characters into account.

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

yes (vim 9.0.981) but hlsearch is off by default and needs to be turned on

### Operating system/version

macOS 13.2.1

### Terminal name/version

Terminal

### $TERM environment variable

xterm-256color

### Installation

brew install neovim

**Comment by zeertzjq** [comment]
Cannot reproduce. Can you try some other terminal emulator?

**Comment by erw7** [comment]
When checked with the `ga` command, the corresponding character is treated as a compose characters. This is correct handling. Therefore, I think it is a Terminal problem, not a neovim(vim) problem. Does the background color of `dot` turn red when the following command is executed?

```
printf "mag(v⃗) = sqrt(\x1b[41mdot\x1b[m(v⃗, v⃗))"
```
