### ISSUE TITLE
docs: update OpenBSD build prerequisites in the wiki to build successfully

### ISSUE THREAD

**Issue by amalgame21** [neovim/neovim#22370]
### Problem

In the wiki https://github.com/neovim/neovim/wiki/Building-Neovim#openbsd , OpenBSD dependencies are not enough to successfully build neovim.

According to https://github.com/neovim/neovim/issues/12682
`gettext-tools` should also be added to the build prerequisites in the wiki.

### Expected behavior

Build neovim properly.

**Comment by justinmk** [comment]
updated, thanks https://github.com/neovim/neovim/wiki/Building-Neovim/_compare/2101b37aa10016bf0b6a61401e513d0d04b00d43...7fc957715bd3f06271e1fde84f436f2f3d001bcc#diff-19d53059b684fc4ccfc13103ec38a44527df7c807aa8da8bb020b9db7506a318R433
