### ISSUE TITLE
Mixing diagnostic underline styles causes incorrect rendering

### ISSUE THREAD

**Issue by P1n3appl3** [neovim/neovim#22371]
### Problem

When two diagnostics of different severity are emitted and one is contained within the other, the `gui` underline styles (undercurl, underdouble, underdash, underdot, underline) don't render as expected for the inner span. For example here are a few examples with an error contained inside a warning:

- dot containing dash: ![1677116004](https://user-images.githubusercontent.com/9326885/220807893-6d974e80-480d-4065-884f-e99b05140a7a.png) renders correctly.
- dash containing dot ![1677116286](https://user-images.githubusercontent.com/9326885/220807975-8a6aa862-f249-4103-9090-5b0ec5ee6074.png) the inner error is dashed rather than dotted
- curl containing line: ![1677116532](https://user-images.githubusercontent.com/9326885/220808162-658864a3-a90e-456b-ac21-784ccf113f5a.png) the inner error is double instead of single underlined???
- curl containing dash: ![1677116740](https://user-images.githubusercontent.com/9326885/220806944-37c5de98-ae56-421b-b631-b56d02b27446.png) the inner underline has completely disappeared 😧.

### Steps to reproduce

I've written a minimal example using the diagnostics api: `nvim --clean repro.lua -c 'so %'` where `repro.lua` contains:
```lua
-- this line contains overlapping diagnostics

local ns = vim.api.nvim_create_namespace "test_namespace"
vim.diagnostic.set(ns, 0, {
    {
        lnum = 0, col = 10, end_col = 40,
        severity = vim.diagnostic.severity.ERROR, message = "error",
    }, {
        lnum = 0, col = 15, end_col = 30,
        severity = vim.diagnostic.severity.WARN, message = "warning",
    },
})

vim.cmd [[
hi DiagnosticUnderlineError guisp='Red' gui=underline
hi DiagnosticUnderlineWarn guisp='Cyan' gui=undercurl
set termguicolors
]]
```
The settings in ^ produce "line containing curl" underline, which is one of the combinations that actually renders correctly for me. I can switch out the error and warn gui settings and `:so %` to see how the different ones behave.

Also this probably warrants a separate issue but the `:h` docs use "underdotted", "underdashed" etc. but those don't seem to actually work. you have to use "underdot", "underdash", etc.

The real-world usage where I ran into this was with LSP diagnostics. rust-analyzer emits some overlapping diagnostics and I had different underline styles that happened to be some of the combinations that render incorrectly. The easiest example to reproduce I've found is adding `use asdf;` to any rust file with rust-analyzer enabled. You get a warning diagnostic about the unnecessary single-path-component import, and also an error diagnostic with a span completely contained within the former about the unknown crate `asdf`. If the diagnostic-underline-warn/error highlight groups have different styles then the issue occurs.

### Expected behavior

I'd expect arbitrary sequences of underline styles to display correctly. For example outside of neovim the following renders correctly (using kitty):
```sh
echo -e '\e[4mline\e[4:2mdouble\e[4:3mcurl\e[4:4mdot\e[4:5mdash'
```

Within neovim I've manually set some non-diagnostics highlights and they also render correctly when using combinations that the diagnostics mishandled. `nvim --clean repro.vim -c 'so %'` where `repro.vim` contains:
```vim
hi vimEscape gui=undercurl
hi vimString gui=underdash
set termguicolors

let x = "as\n\n\ndf" " note the correct mixing
```

I think the difference here is that those groups aren't actually overlapping, it just switches back from one to the other. I don't know of any cases other than diagnostics underlines where you could have highlight groups that overlap and combine, but if those exist I would guess they have the same problem.

### Neovim version (nvim -v)

v0.9.0-dev-901+g563881306

### Vim (not Nvim) behaves the same?

Haven't checked, but I don't think vim handles diagnostics the same way as neovim so i'm not sure how i'd reproduce

### Operating system/version

Debian 5.19.11

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by zeertzjq** [comment]
In v0.8 this show two underline styles:
```lua
-- this line contains overlapping diagnostics

local ns = vim.api.nvim_create_namespace "test_namespace"
vim.diagnostic.set(ns, 0, {
    {
        lnum = 0, col = 10, end_col = 40,
        severity = vim.diagnostic.severity.ERROR, message = "error",
    }, {
        lnum = 0, col = 15, end_col = 30,
        severity = vim.diagnostic.severity.WARN, message = "warning",
    },
})

vim.cmd [[
hi DiagnosticUnderlineError guisp='Red' gui=underline
hi DiagnosticUnderlineWarn guisp='Cyan' gui=undercurl
set termguicolors
]]
```
![Screenshot_20230223_104024](https://user-images.githubusercontent.com/35768171/220810009-e1f5f3e8-f555-4390-9b6d-76b3d73e1e64.png)

whereas this only shows undercurl:
```
-- this line contains overlapping diagnostics

local ns = vim.api.nvim_create_namespace "test_namespace"
vim.diagnostic.set(ns, 0, {
    {
        lnum = 0, col = 10, end_col = 40,
        severity = vim.diagnostic.severity.ERROR, message = "error",
    }, {
        lnum = 0, col = 15, end_col = 30,
        severity = vim.diagnostic.severity.WARN, message = "warning",
    },
})

vim.cmd [[
hi DiagnosticUnderlineError guisp='Red' gui=undercurl
hi DiagnosticUnderlineWarn guisp='Cyan' gui=underline
set termguicolors
]]
```
![Screenshot_20230223_104204](https://user-images.githubusercontent.com/35768171/220810171-472be271-c46c-408d-a833-4848b67485cf.png)

Is it expected to restore the v0.8 behavior?

**Comment by zeertzjq** [comment]
It's not clear which attribute should take priority.

**Comment by P1n3appl3** [comment]
I was more concerned about the interactions where the inner underline completely disappeared or turned into a style that wasn't what either were set to, but I don't seem to be able to repro those with the minimal example. I still see them with my normal config when using rust analyzer, so it's possible there's something else going wrong in that case.

**Comment by zeertzjq** [comment]
Oh, actually it possible to make priority work here.

**Comment by P1n3appl3** [comment]
Oh that'd be great then. I still feel like in the case of complete overlap you might want to see both, so where E is error and W is warning:
```
Complete overlap:
Error:   ...EEEEEEEE...
Warning: ......WWW.....
Result:  ...EEEWWWEE...

Partial overlap (error takes precedence):
Error:   ...EEEEE......
Warning: ....WWWWW.....
Result:  ...EEEEEW...
```

I haven't thought about his very hard though and I imagine there's plenty of edge cases (like complete overlap with exactly matching spans, or two contiguous errors that have an overlapping warning between them, or more complicated cases where three or more severity levels overwrap) so it may be easier to stick with some simpler rule.

**Comment by P1n3appl3** [comment]
I found a related issue, I didn't know about `severity_sort` in `diagnostic.config` but it's the relevant setting that should control this behavior: #19741
