### ISSUE TITLE
stdpath('run') returns wrong result in the `su` context

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#22387]
### Problem

see the title.

### Steps to reproduce

* we are in a linux tty
* login as user `foo`
  * `$ nvim --clean`
  * `:echo stdpath('run')` -> `/run/user/1000`
  * `:exit`
* still as user `foo`
  * `$ su bar`
  * `$ nvim --clean`
  * `:echo stdpath('run')` -> `/run/user/1000` # the problem
  * `:exit`

### Expected behavior

in the `su` context, `stdpath('run')` should be something like `/run/user/$(id -u bar)`

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

tmux-256color

### Installation

system package manager

**Comment by zeertzjq** [comment]
`unset XDG_RUNTIME_DIR`
