### ISSUE TITLE
Issue with printing MAN page on Shift+K 

### ISSUE THREAD

**Issue by neokril** [neovim/neovim#2238]
Version: a4c3ac2799281b56c1c38d0fdc584e22ac1b3d2f
OS: Ubuntu 12.04.1

Scenario:
1. Move cursor in normal mode to a word "listen"
2. Press Shift+K

Expected: MAN page for corresponding function
Observed: only bottom half of the MAN page is shown. There's no way to scroll it up.

**Comment by noahfrederick** [comment]
This is a known issue. See https://github.com/neovim/neovim/issues/1496.

**Comment by oni-link** [comment]
@tarruda suggested a workaround in the meantime in https://github.com/neovim/neovim/issues/1468#issuecomment-62979169 
```viml
function! Manpage()
  let word = expand('<cword>')
  enew!
  setl nomod nolist nonumber norelativenumber
  nnoremap q :bd!<cr>
  setf man
  exe 'r !man '.word
  normal gg
endfunction
nnoremap K :call Manpage()<cr>
```

**Comment by neokril** [comment]
Thank you for the quick response!
