### ISSUE TITLE
Multiple filetypes for latex

### ISSUE THREAD

**Issue by TroySigX** [neovim/neovim#22396]
### Problem

I have a .tex file. When it's empty, its filetype is plaintex, and when it's filled with some code, the filetype changes to tex. It is super confusing.

### Steps to reproduce

1. Create some .tex file
2. :set ft, it shows "plaintex"
3. Type some code, e.g, ``` \documentclass[a4paper,12pt]{article} ```
4. :set ft, it now shows "tex"

### Expected behavior

Filetype should be consistent.

### Neovim version (nvim -v)

0.8.3, latest stable release

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

6.1.12-arch1

### Terminal name/version

yakuake 22.12.2

### $TERM environment variable

xterm-256color

### Installation

arch pacman repo

**Comment by zeertzjq** [comment]
See `:h g:tex_flavor`

**Comment by clason** [comment]
or install lervag/vimtex.
