### ISSUE TITLE
thread 'main' panicked at 'Failed to spawn child process: Os, when tried to run on Ubuntu aarch64 arm server

### ISSUE THREAD

**Issue by skygunner** [neovim/neovim#22395]
### Problem

`thread 'main' panicked at 'Failed to spawn child process: Os { code: 8, kind: Uncategorized, message: "Exec format error" }', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bob-nvim-2.0.0/src/main.rs:58:14
stack backtrace:
   0:     0xaaaaad180164 - std::backtrace_rs::backtrace::libunwind::trace::h4094424764928517
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xaaaaad180164 - std::backtrace_rs::backtrace::trace_unsynchronized::h66a4d558a047d429
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaaad180164 - std::sys_common::backtrace::_print_fmt::he501a9dfcbc65602
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0xaaaaad180164 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h500c865c023970a8
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xaaaaad1a2738 - core::fmt::write::h746b6837467f52c4
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0xaaaaad17b198 - std::io::Write::write_fmt::h9c3773c135795f84
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0xaaaaad17ff70 - std::sys_common::backtrace::_print::haf80eda742d20a82
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0xaaaaad17ff70 - std::sys_common::backtrace::print::h1af712ffba8f7735
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0xaaaaad181660 - std::panicking::default_hook::{{closure}}::hd82c56e3724f8bd8
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0xaaaaad1813a4 - std::panicking::default_hook::h1f2a94f3a1c1c1aa
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0xaaaaad181ce0 - std::panicking::rust_panic_with_hook::h01eb01a06bf17753
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0xaaaaad181ac0 - std::panicking::begin_panic_handler::{{closure}}::h657c9d34bb6d0855
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
  12:     0xaaaaad1805f4 - std::sys_common::backtrace::__rust_end_short_backtrace::h0b2d3ba55b6e5445
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0xaaaaad18180c - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0xaaaaace1099c - core::panicking::panic_fmt::h29641d0c529764f0
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0xaaaaace10cbc - core::result::unwrap_failed::h058c9a1e58c62fd7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
  16:     0xaaaaacea6848 - tokio::runtime::park::CachedParkThread::block_on::h330a5ba90ef38d09
  17:     0xaaaaace2ded0 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h7be6d86c82d32846
  18:     0xaaaaace5102c - bob::main::h1c860c7dfaf7598f
  19:     0xaaaaace2281c - std::sys_common::backtrace::__rust_begin_short_backtrace::h2f6bd6f9acd9b8e5
  20:     0xaaaaace473bc - std::rt::lang_start::{{closure}}::h5f6dfc07d19369c7
  21:     0xaaaaad1753d0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h529a25abf285dbab
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606:13
  22:     0xaaaaad1753d0 - std::panicking::try::do_call::h660335bd09680bb9
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  23:     0xaaaaad1753d0 - std::panicking::try::h94641ffd91114cda
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  24:     0xaaaaad1753d0 - std::panic::catch_unwind::hb02f598a6506eb1a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  25:     0xaaaaad1753d0 - std::rt::lang_start_internal::{{closure}}::h2bafc04d50d16864
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:48
  26:     0xaaaaad1753d0 - std::panicking::try::do_call::he27a0671832dd909
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  27:     0xaaaaad1753d0 - std::panicking::try::h517b21015b9f6abd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  28:     0xaaaaad1753d0 - std::panic::catch_unwind::hc734f97b8d8dbcc6
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  29:     0xaaaaad1753d0 - std::rt::lang_start_internal::h3fd169391cc4081c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:20
  30:     0xaaaaace511f0 - main
  31:     0xffffa58a73fc - <unknown>
  32:     0xffffa58a74cc - __libc_start_main
  33:     0xaaaaace10e70 - _start
  34:                0x0 - <unknown>
`

### Steps to reproduce

Ubuntu 22.04 LTS 
ampera arm server
installed with bob install 0.8.3
rust and cargo installed with 
curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh
run nvim cause error

### Expected behavior

doesn't seem to work

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

no, 8.2.4919

### Operating system/version

Ubuntu 22.04 LTS

### Terminal name/version

?

### $TERM environment variable

xterm-x256color

### Installation

bob install 0.8.3

**Comment by skygunner** [comment]
rustc 1.67.1 (d5a82bbd2 2023-02-07)

**Comment by zeertzjq** [comment]
This should be reported to bob.
