### ISSUE TITLE
maparg docs out of date: doesn't mention callback

### ISSUE THREAD

**Issue by gregorias** [neovim/neovim#22399]
### Problem

[`maparg`'s documentation](https://github.com/neovim/neovim/blob/5732aa706c639b3d775573d91d1139f24624629c/runtime/doc/builtin.txt#L4819-L4823) (and also [this](https://github.com/neovim/neovim/blob/5732aa706c639b3d775573d91d1139f24624629c/runtime/doc/builtin.txt#L300-L302)) say that the returned Dict contains rhs of the maps. This is incorrect, because they can contain Lua callbacks, e.g., the function can return:

```
{'lnum': 0, 'script': 0, 'replace_keycodes': 1, 'silent': 0, 'callback': function('<lambda>1'), 'noremap': 1, 'lhs': '<C-C>', 'mode': 'n', 'lhsraw': '<80><fc>^DC', 'nowait': 0, 'expr': 1, 'sid': -8, 'buffer': 0, 'lhsrawalt':
 '^C'}
```

### Steps to reproduce

Run 

```vimscript
lua vim.api.nvim_set_keymap('n', 'asdf', '', {callback = function() GlobalCount = GlobalCount + 10 end })
echo maparg('asdf', 'n', 0, 1)
```

You'll see that the returned map doesn't contain `rhs`.

### Expected behavior

Maparg documentation is up-to-date and mentions the callback alternative.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS 13.2.1

### Terminal name/version

kitty 0.26.3

### $TERM environment variable

xterm-kitty

### Installation

Homebrew

**Comment by zeertzjq** [comment]
Closing in favor of #23666 which contains more information
