### ISSUE TITLE
Nvim exits (or crashes) when opening an image

### ISSUE THREAD

**Issue by Coder2195Text** [neovim/neovim#22409]
### Problem

https://user-images.githubusercontent.com/63069499/221379242-c0a03c56-b11e-4a1c-914d-af2e7c01815f.mp4

### Steps to reproduce

open any image in nvim nightly

Edit: Some images seem to work fine

It seems to depend on location, because I tried putting a CoderVim.png image at each level of the directories and testing them.

Nvim opens ~/.config/CoderVim.png just fine, but crashes on ~/.config/nvim/CoderVim.png

Permissions for ~/.config/nvim/CoderVim.png

`-rw-rw-r--  1 coder2195 coder2195 153713 Feb 25 16:07 CoderVim.png`

Permissions for ~/.config/CoderVim.png

`-rw-rw-r--  1 coder2195 coder2195 153713 Feb 25 16:08 CoderVim.png`

It seems to not be perm issues because they are exactly the same

### Expected behavior

Opens without problems

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1045+ga601d0311

### Vim (not Nvim) behaves the same?

no, vi 8.2

### Operating system/version

Ubuntu 22.04

### Terminal name/version

kitty terminal

### $TERM environment variable

xterm-kitty

### Installation

appimage

**Comment by Coder2195Text** [comment]
Seems to be some issue with git because it only happens in git repos

**Comment by clason** [comment]
Always test with `nvim--clean`.

**Comment by Coder2195Text** [comment]
I suspect it might be an issue with git repo images, and this has made me think maybe diff change highlighting could be the cause

**Comment by Coder2195Text** [comment]
https://github.com/lewis6991/gitsigns.nvim/issues/758 resolved
