### ISSUE TITLE
Concealed text longer than one line stays on screen in termux

### ISSUE THREAD

**Issue by beelzebielsk** [neovim/neovim#22406]
### Problem

Neovim concealed text causes visual bugs with termux. It's when the concealed text spans over several lines. Attached is a video example. The latest vim doesn't have this issue on termux. Though, I don't get this issue with neovim on other terminal emulators.

Redraw doesn't help. The only thing that does is suspending neovim and bringing it back using Ctrl Z.

https://user-images.githubusercontent.com/16908019/221376320-b186ece2-4714-48c4-ba65-f78225ffa1c8.mp4

### Steps to reproduce

- Install `preservim/vim-markdown`
- Open a markdown buffer.
- `set conceallevel:2 wrap`
- Paste a long link in. Make sure it wraps past one screen line. Personally I use `[Source](https://xxxxxxxxxx/xxxxxxxxxx/…). Some text after.` repeating units of 10 X's followed by slash until I wrap around past one line.
- Move the cursor on and off the line with the link.

### Expected behavior

There should be no lingering effects from revealing concealed text.

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Android 10

### Terminal name/version

termux 0.118.0

### $TERM environment variable

xterm-256color

### Installation

termux package manager (pkg install neovim)

**Comment by beelzebielsk** [comment]
The lingering text stays there if you switch buffers, and can sometimes completely mess up the screen making concealed text in markdown unusable.

**Comment by bfredl** [comment]
does `:mode` help?

**Comment by beelzebielsk** [comment]
Yeah, it does. I wasn't aware of this command. It returns the screen to what it should be.

**Comment by zeertzjq** [comment]
You must have some other options set, like `'linebreak'`. Please provide steps to reproduce with `nvim --clean`

**Comment by beelzebielsk** [comment]
It's true that I have `linebreak` on in the video, that's an oversight of mine. However, I was able to reproduce it without linebreak, too. I'm not sure how to produce this from `nvim --clean` because I'm not sure how to get a conceal that big without a plugin.

My best idea was to use a few commands to get just enough syntax for concealing, but I couldn't get it to work. I don't know anything about vim syntax files.

Could someone help me write syntax rules to conceal most of the first line of a file? That should be a good first attempt. Either that or point me to a built-in syntax which could conceal something long enough to span several screen lines.

	syntax match Entity '&amp;' conceal cchar=&

If it helps, this was what I tried as a starting point to conceal something, and if it worked I would've changed it to conceal the first line of the file.

**Comment by beelzebielsk** [comment]
I used that command in a buffer with no filetype.

**Comment by beelzebielsk** [comment]
Uh, nevermind! It's working now, somehow.

Steps to reproduce:

1. Run nvim this way:

		nvim --clean \
			-c 'syn match line ".*" conceal cchar=&' \
			-c 'set wrap conceallevel:2'

2. Type up a line long enough to wrap. Looks like 3 screen lines is enough to cause the problem. 2 didn't work when I tried it. I was able to reproduce it with any characters. A long string of `x` worked, too.

**Comment by beelzebielsk** [comment]
I tried the same setup in vim, and it worked as expected, no visual bugs.

	vim --clean \
		-c 'syn match line ".*" conceal cchar=&' \
		-c 'set wrap conceallevel:2'

**Comment by zeertzjq** [comment]
It seems that this has already been fixed by #18375, though not sure how.
