### ISSUE TITLE
CursorColumn ctermfg color is overriden by syntax color

### ISSUE THREAD

**Issue by eddylin0731** [neovim/neovim#22404]
### Problem

When I set ':hi CursorColumn cterm=none ctermg=Gray ctermfg=Black'.
The text color is still the syntax color.
But in the vim.
The text color will change to the ctermfg color.

### Steps to reproduce

nvim
:hi CursorColumn cterm=none ctermg=Gray ctermfg=Black

### Expected behavior

The hi CursorColumn color will show the cterfg's color.

### Neovim version (nvim -v)

0.4.4

### Vim (not Nvim) behaves the same?

no, vim 8.2.2434

### Operating system/version

Debian 11

### Terminal name/version

GNOME terminal 3.38.3

### $TERM environment variable

xterm-256color

### Installation

 system package manager

**Comment by clason** [comment]
I'm sorry, that Neovim version is too ancient to support. Please test with the latest release (0.8.3) or nightly.

**Comment by eddylin0731** [comment]
@clason 
I just try the nvim v0.8.3.
The problem is still exist.

**Comment by clason** [comment]
Are you sure you are not setting `termguicolors`?  Can you reproduce this with `nvim --clean`?

**Comment by zeertzjq** [comment]
I can reproduce this.

**Comment by eddylin0731** [comment]
@clason 
I set 'set termguicolors' in vim v8.2.2434 and nvim v0.8.3.
The CursorColumn ctermfg color and CursorLine ctermfg color are both overwritten by syntax color.

If I set 'set termguicolors' in vim v8.2.2434 and nvim v0.8.3.
My set for hilight the statusline is not working in vim v8.2.2434 and nvim v0.8.3.

**Comment by zeertzjq** [comment]
I can reproduce this. This is similar to #7383, but for `CursorColumn` instead of `CursorLine`.

**Comment by eddylin0731** [comment]
@clason 
So I won't set 'set termguicolors' in my vim and nvim config.

**Comment by eddylin0731** [comment]
![Screenshot from 2023-02-26 22-12-23](https://user-images.githubusercontent.com/126345487/221415846-4f8a56f1-16ca-4c4b-8596-ada74332bb6a.png)

**Comment by eddylin0731** [comment]
![Screenshot from 2023-02-26 22-13-26](https://user-images.githubusercontent.com/126345487/221415894-7f2485ca-93e1-486e-a63e-9ad7b72bd7cc.png)

**Comment by eddylin0731** [comment]
@zeertzjq 
The second picture is my init.vim.
You can see the CursorLine ctermfg color.
That's good for me.
But the CursorColumn ctermfg color isn't what I want.

**Comment by zokeefe** [comment]
FWIW -- I tried the next logical step; building and testing an earlier, stable version (I tried release-0.8 and v0.8.3), but couldn't build:

make[4]: libtool: No such file or directory                                                    
make[4]: *** [Makefile:69: unibilium.lo] Error 127 

I didn't look further.

**Comment by zokeefe** [comment]
Perhaps this is WOI? I just checked on

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

And I see the same behavior.

**Comment by zokeefe** [comment]
One last comment, then I'll leave it to those who understand this codebase: but setting a non-NONE value for CursorLine fg "prevents" CursorColumn bg from stomping over CursorLine bg -- but of course, that's not what I want :)

**Comment by zeertzjq** [comment]
Does it behave as expected if you apply the following diff:
```diff
diff --git a/src/nvim/drawline.c b/src/nvim/drawline.c
index bf8649afe..02f6057d8 100644
--- a/src/nvim/drawline.c
+++ b/src/nvim/drawline.c
@@ -2604,10 +2604,10 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
       if (wp->w_p_cuc && VCOL_HLC == (long)wp->w_virtcol
           && lnum != wp->w_cursor.lnum) {
         vcol_save_attr = char_attr;
-        char_attr = hl_combine_attr(win_hl_attr(wp, HLF_CUC), char_attr);
+        char_attr = hl_combine_attr(char_attr, win_hl_attr(wp, HLF_CUC));
       } else if (draw_color_col && VCOL_HLC == *color_cols) {
         vcol_save_attr = char_attr;
-        char_attr = hl_combine_attr(win_hl_attr(wp, HLF_MC), char_attr);
+        char_attr = hl_combine_attr(char_attr, win_hl_attr(wp, HLF_MC));
       }
     }
 
```

**Comment by zokeefe** [comment]
Thanks for the speedy reply. Unfortunately, applied and built against
master, and the problem persists.

**Comment by erw7** [comment]
This behavior is intended, as is clear from reading vim_diff.txt.

https://github.com/neovim/neovim/blob/ba38f35d3e2f37c2289543e6e0c4451c679c5834/runtime/doc/vim_diff.txt#L472-L473

**Comment by zokeefe** [comment]
Thanks for the link, though I think the documentation is a bit ambiguous:

--8<--
Highlight groups:
  |hl-ColorColumn|, |hl-CursorColumn| are lower priority than most other
  groups
  [..]
  |hl-CursorLine| is low-priority unless foreground color is set
--8<--

What does "lower priority" and "low-priority" mean? Is there somewhere
that specifies these terms unambiguously?

Otherwise, if this is WAI, do you mind pointing me to the code where
these priorities are defined? I don't mind carrying a private patch
for this.

Best,
Zach
