### ISSUE TITLE
Star letter incorrectly shown in help pages

### ISSUE THREAD

**Issue by gitJigit** [neovim/neovim#22412]
### Problem

Text:  '*',  '**' 
is shown as: '', ''

### Steps to reproduce

:help file-searching  opens editing.txt, (/usr/share/nvim/runtime/doc/editing.txt)
in line 1524 you see: Downward search uses the wildcards '', '' and possibly others
in vim you see: Downward search uses the wildcards '*', '**' and possibly others
/usr/share/nvim/runtime/doc/editing.txt contains star letters, checked with less

### Expected behavior

Display as in vim

### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no, gvim 9.0.1337-1 from extra repository

### Operating system/version

archlinux

### Terminal name/version

kitty 0.27.1, XTerm(379)

### $TERM environment variable

xterm-kitty, xterm

### Installation

installed with pacman: community/neovim 0.8.3-1

**Comment by gitJigit** [comment]
nvim --clean does not show this behavior, everything works correctly then

**Comment by clason** [comment]
Yes, you must be using the vimdoc treesitter parser, which is more strict than Vim's syntax file. Most of these issues should be fixed on master.

**Comment by gitJigit** [comment]
Correct. I uninstalled treesitter on a trial basis, then error was gone. Thank you.
