### ISSUE TITLE
Unknown function: indexof, invoked in s:Highlight_Matching_Pair()

### ISSUE THREAD

**Issue by deforde** [neovim/neovim#22465]
### Problem

When I move the cursor over an open or closing parenthesis, brace or bracket, the following error is reported:
```
Error detected while processing CursorMoved Autocommands for "*"..function <SNR>15_Highlight_Matching_Pair[86]..CursorMo
ved Autocommands for "*"..function <SNR>15_Highlight_Matching_Pair:                                                     
line   82:                                                                                                              
E117: Unknown function: indexof
```

It appears to me that this is complaining about the usage of the function `indexof` in `s:Highlight_Matching_Pair`, defined on runtime/plugin/matchparen.vim:39.
The `indexof` function is invoked when the `s_skip` string (built on runtime/plugin/matchparen.vim:111) is executed on runtime/plugin/matchparen.vim:121.

### Steps to reproduce

nvim --clean
i[

### Expected behavior

I do not expect an error to be generated.

### Neovim version (nvim -v)

v0.9.0-dev-383+g2738f842f

### Vim (not Nvim) behaves the same?

No, VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 11 2023 23:53:12) Included patches: 1-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919

### Operating system/version

Ubuntu 22.04

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by clason** [comment]
Your Neovim prerelease build is way too old. If you use nightly, you have to rebuild constantly to keep it updated. (You can't mix and match binary and runtime.)

**Comment by deforde** [comment]
Whoops, that's my mistake, I was rebuilding neovim but not updating the symlink to the binary :man_facepalming: .
Thanks, and apologies.
