### ISSUE TITLE
Set syntaz=zsh in the modeline generate error when opening file

### ISSUE THREAD

**Issue by Etienne-Schmitt** [neovim/neovim#22460]
### Problem

I've trying to create modeline for some zsh files but when adding the modeline:`# vim: syntax=zsh` It fail to load the syntax...

Note than the modeline `# vim: syntax=sh` can load the sh syntax... and even typing `:set syntaz=zsh` after acknowledging the error in the file work...

The Error:
```
Error detected while processing modelines[1]..Syntax Autocommands for "*"..function <SNR>6_SynSet[25]..script /opt/homebrew/Cellar/neovim/0.8.3/share/nvim/runtime/syntax/zsh.vim[37
]..function <SNR>28_ContainedGroup[16]..modelines[1]..Syntax Autocommands for "*"..function <SNR>6_SynSet[25]..script /opt/homebrew/Cellar/neovim/0.8.3/share/nvim/runtime/syntax/zs
h.vim[37]..function <SNR>28_ContainedGroup:
line   10:
E12: Command not allowed from exrc/vimrc in current dir or tag search
Error detected while processing modelines[1]..Syntax Autocommands for "*"..function <SNR>6_SynSet:
line   25:
E171: Missing :endif
Press ENTER or type command to continue
```

### Steps to reproduce

```sh
# No init configuration defined, just a clean install
echo "# vim: syntax=zsh\n\necho 'hello'" > test
nvim test
# Error occur here
```

### Expected behavior

Neovim should load the syntax and open the file

### Neovim version (nvim -v)

0.8.2 & 0.8.3

### Vim (not Nvim) behaves the same?

No error here but still no syntax loaded in 9.0.981 (bundled with macos) but syntax work in 9.0.1350 (installed with homebrew)

### Operating system/version

macOS 13.2.1 (22D68)

### Terminal name/version

Apple Terminal 2.13 (447)

### $TERM environment variable

xterm-256color

### Installation

Homebrew

**Comment by gpanders** [comment]
Don't use `syntax`, use `filetype`

```
# vim: filetype=zsh
```

**Comment by Etienne-Schmitt** [comment]
Really sorry for the trouble then... I'm still learning vi/vim/nvim 😞 

But thanks anyway for your quick reply!
