### ISSUE TITLE
Cannot enable line number with config file while opening an empty file

### ISSUE THREAD

**Issue by tanchihpin0517** [neovim/neovim#22475]
### Problem

I notice the line number is not set by config file while opening an empty file

### Steps to reproduce

nvim -u test.vim

test.vim:
```
set number
```

The result looks like this:
![image](https://user-images.githubusercontent.com/10648553/222455484-aade6889-8c04-4ebc-953f-938acfbb52b1.png)

### Expected behavior

Line number should be enabled like this:
![image](https://user-images.githubusercontent.com/10648553/222452568-ca7a6e9f-39e6-4c3b-b734-fb8df13f41de.png)
rather than:
![image](https://user-images.githubusercontent.com/10648553/222452413-a4aab8d3-3080-4b23-a562-4cf3eed98570.png)

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

no, 9.0.981

### Operating system/version

macOS 13.2.1

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

prebuilt executable file from repo

**Comment by justinmk** [comment]
works for me with `NVIM v0.9.0` 1e37703a74ee

did you try `nvim --clean` (as mentioned in the issue template)?

**Comment by zeertzjq** [comment]
`[Scratch]` means some plugin opened a new scratch buffer, so this is caused by a plugin.

**Comment by tanchihpin0517** [comment]
Oh! Got it. It's my bad. I misunderstand the usage of `--clean`. I considered it would disable *all* config file including my testing config so I didn't try with `--clean`.
Thanks guys.
