### ISSUE TITLE
Entire screen of "E37: No write since last change (add ! to override)"

### ISSUE THREAD

**Issue by hboon** [neovim/neovim#22470]
### Problem

I'm getting an entire screen of "E37: No write since last change (add ! to override)", but no idea how to reproduce it.

Running nvim v0.8.3 in Alacritty 0.11.0 (1). Just a single Alacritty instance with a single window, running only nvim. I've just recently ported most of my vim (Macvim) configuration over entirely to neovim + lua.

I get this a few times over the last week, but not sure if I can get out of this state or if something really is wrong. I had to close the Alacritty window when I encounter this. Any tips to figure out (logs etc) would be helpful. Neovim newbie here.

<img width="2032" alt="Screenshot 2023-03-02 at 7 16 04 AM" src="https://user-images.githubusercontent.com/56189/222288498-b66af74e-cd1c-433f-a6e3-9999e32db6a8.png">

### Steps to reproduce

Day to day usage editing mostly Markdown files and "text", not source code. Can't figure it exact steps to reproduce yet

### Expected behavior

Be able to get out of the state and most importantly avoid it

### Neovim version (nvim -v)

v0.8.3

### Vim (not Nvim) behaves the same?

MacVim is fine

### Operating system/version

macOS 13.2

### Terminal name/version

Alacritty 0.11.0 (1)

### $TERM environment variable

screen-256color

### Installation

Homebrew

**Comment by hboon** [comment]
I have this in `alacritty.yml` so I can use `cmd+w` to close tabs:

```
key_bindings:
  - { key: W, mods: Command, chars: ":tabclose\n" }
```

The error just happened again and I had just did `cmd+w`. I open a new instance of nvim and open a couple of buffers but can't reproduce it immediately. I'll continue to monitor, but any suggestion where to look would be helpful.

**Comment by hboon** [comment]
Ok, I think I can reproduce this reliably with Telescope:

``
--Plugins:
--1. update list of plugins below
--2. source init.lua
--3. run PaqInstall. They are installed in ~/.local/share/nvim/site/pack/paqs/
require "paq" {
    -- Let Paq manage itself
    "savq/paq-nvim",
    --hhh what is this for?
    "neovim/nvim-lspconfig",
    --hhh what is treesitter for?
    { 'nvim-treesitter/nvim-treesitter', run = function() vim.cmd 'TSUpdate' end },
    "nvim-telescope/telescope.nvim",
}
vim.keymap.set('n', '<tab>', '<esc>:tabe<cr>:Telescope find_files<cr>') --this is looking in filenames only
``

And then I do:

1. nvim #start instance
2. Press <tab> #Trigger Telescope
3. Press <esc> #If I press <esc> twice instead, Telescope finder closes; All good
4. Type `:tabclose<enter>` and the error appears

The problem *seems* to be when I do a `:tabclose<enter>` while the Telescope finder is open, it closes the buffer but Telescope doesn't have a chance to clean up properly.

Hope that gives a clue what's wrong and if I should buzz the telescope folks instead?

**Comment by justinmk** [comment]
Check `:au` to see if you have a redundant autocmd handler. 

Check `:help bisect` to bisect your plugins.

Try https://vi.stackexchange.com for questions about usage and configuration.

The issue tracker is for bugs and feature requests.

**Comment by justinmk** [comment]
> I have this in `alacritty.yml` so I can use `cmd+w` to close tabs:
> 
> ```
> key_bindings:
>   - { key: W, mods: Command, chars: ":tabclose\n" }
> ```

Seems like something somewhere is sending "cmd+w" in a loop.

**Comment by hboon** [comment]
Just for posterity in case it helps someone in the future: `:tabclose!` (with the `!`) makes the problem go away.
