### ISSUE TITLE
filetype lost when reloading a file

### ISSUE THREAD

**Issue by nnako** [neovim/neovim#22479]
### Problem

SETTING

I use a specific text file to encode tasks. these files all have the extension `.txt` and after load, I currently set its filetype manually to the desired `ttodo` by typing in the command line: `:set filetype=ttodo` this triggers the respective [ttodo](https://github.com/tomtom/ttodo_vim) ftplugin to color text elements in the desired way.

BUG / EFFECT

After I change the text file using an external (other) text editor like `notepad++` while the text file is still open within `neovim`, I want to update my file buffer within `neovim`. I do this by typing `:e`, which I thought to be the short version of `:edit`, which re-loads the current buffer. fine.

After re-loading the file into the buffer (all the externally made changes are visible), I have suddenly lost my coloring that was previously done by my ftplugin. So, I have to re-enter `:set filetype=ttodo` in order to get my file type colors back.

This seems only to happen for filetypes `neovim` does not know. maybe the installed filetypes are managed at some other location within `neovim` than the built-ins like `bash` or `python` are.

### Steps to reproduce

- read a text file into a buffer
- set an "uncommon" filetype to interpret the syntax
- re-load the current buffer by typing `:e` and the `<RETURN>` key

-> the filetype should have been cleared or overridden to the default

### Expected behavior

EXPECTATION

It would be helpful if the old filetype settings would still be valid / active after a file-reload into the respective buffer, even though the filetypes are not built-ins.

Is this a common behavior? Is it a bug? Are there configurations to cope with this effect?

### Neovim version (nvim -v)

0.9.0-dev-622+g08ebf8d3a

### Vim (not Nvim) behaves the same?

no, there I configured an "autoload-on-change"... not installed anymore

### Operating system/version

Windows 10

### Terminal name/version

"windows command line", nvim started as gui app, not from cmd line

### $TERM environment variable

"standard terminal"

### Installation

standard installer (portable) from website

**Comment by justinmk** [comment]
autoread is tracked in https://github.com/neovim/neovim/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+autoread+

**Comment by bew** [comment]
If it's ok for you to add a little metadata in the file (in a comment for example) you can use modelines thqt allows you to set the filetype from inside the file. (see `:h modeline`)

For example in a file `foo.txt`:
```
Some text here
# here is a comment
# and the modeline here below
# vim:set ft=custom-filetype:
```
Loading it with vim should automatically set the filetype to `custom-filetype`.
