### ISSUE TITLE
`treesitter.get_parser()` should not link empty `filetype` to `lang`

### ISSUE THREAD

**Issue by cairijun** [neovim/neovim#22473]
### Problem

Might caused by #22207.

`treesitter.get_parser()` (which calls `_create_parser`) unconditionally links the buffer `filetype` to `lang`, even if `filetype` is actually empty. Some plugins use TS without setting `filetype` beforehand to have finer control (e.g. [nvim-telescope](https://github.com/nvim-telescope/telescope.nvim/blob/a3f17d3baf70df58b9d3544ea30abe52a7a832c2/lua/telescope/previewers/utils.lua#L134)), causing the empty filetype to be linked to some valid TS parser. That parser might be accidentally triggered when loading a buffer with empty filetype (e.g. a huge log file like `:LspLog`), causing performance issues.

https://github.com/neovim/neovim/blob/a0292b4e5f106482edc5623eef85aa48e2e55bb7/runtime/lua/vim/treesitter.lua#L50

### Steps to reproduce

```bash
nvim --clean --headless \
  '+lua print(vim.treesitter.get_parser(0, "c"))' \
  '+lua print(vim.treesitter.get_lang(""))' \
  '+edit ~/.local/state/nvim/lsp.log' \
  '+lua print(vim.inspect(vim.treesitter.get_node()))' \
  '+q'
```

`get_lang("")` returns `"c"` and `get_node()` succeeds, and if `lsp.log` is large, it hangs for ages doing useless paring.

### Expected behavior

`get_lang("")` should return `nil`, and `get_node()` should fail immediately as `lsp.log` has empty `filetype`.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1092+gbc15b075d

### Vim (not Nvim) behaves the same?

no

### Operating system/version

linux

### Terminal name/version

wezterm

### $TERM environment variable

tmux-256color

### Installation

appimage

**Comment by lewis6991** [comment]
@cairijun can you review #22476 ?
