### ISSUE TITLE
build failed,  ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by syswow** [neovim/neovim#2248]
```
uname -a
Linux omega 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
clone the latest  and run follow:
```
rm -fr build && make clean && 
make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/home/syswow/Omega/Apps/neovim" install
```
out: 
```
 - Child aborted
Call Stack (most recent call first):
  cmake_install.cmake:516 (INCLUDE)


ninja: build stopped: subcommand failed.
```

**Comment by syswow** [comment]
Update:
```
sudo make install
```
also failed.

**Comment by syswow** [comment]
Update:
but if we just run `make`, it will build successful.

Need help, thanks.

**Comment by grtlr** [comment]
I can reproduce this issuse on Ubuntu 14.04. The error seems to occur while installing the files. It last messages before look something like this:

    ...
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/autoload/ccomplete.vim
    -- Installing: /home/goertler/local/share/nvim/runtime/plugin
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/netrwPlugin.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/vimballPlugin.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/matchparen.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/rrhelper.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/gzip.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/README.txt
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/rplugin.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/spellfile.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/tarPlugin.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/getscriptPlugin.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/tohtml.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/plugin/zipPlugin.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/menu.vim
    -- Installing: /home/goertler/local/share/nvim/runtime/keymap
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/keymap/canfr-win.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/keymap/serbian_utf-8.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/keymap/russian-dvorak.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/keymap/hebrew_utf-8.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/keymap/greek_utf-8.vim
    -- Up-to-date: /home/goertler/local/share/nvim/runtime/keymap/hebrewp_iso-8859-8.vim
     - Child aborted
    Call Stack (most recent call first):
      cmake_install.cmake:516 (INCLUDE)
     
     
    ninja: build stopped: subcommand failed.
    make: *** [install] Error 1

Building neovim seems to work fine. I used this command:

    make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=~/local" install

**Comment by BlackEdder** [comment]
For me this seems fixed by #2263

**Comment by grtlr** [comment]
Yes #2263 fixes this for me too.

**Comment by syswow** [comment]
confirm fixed.

**Comment by meokarin01** [comment]
![screenshot from 2017-12-04 08-39-45](https://user-images.githubusercontent.com/21154998/33532727-b74de318-d8ce-11e7-8a6c-111fa34ef40b.png)

**Comment by jamessan** [comment]
@meokarin01 You're building some Java project.  That has nothing to do with Neovim, other than you happened to run into the same (generic) CMake error that someone encountered here.

**Comment by vsushant8421** [comment]
how to fix it then?
