### ISSUE TITLE
Visual bugs when deleting text from a long wrapped line

### ISSUE THREAD

**Issue by beelzebielsk** [neovim/neovim#22489]
### Problem

Deleting from a long wrapped line causes a visual bug. Some text on the following line appears incorrectly afterwards.

The setup is a long wrapped line, followed by another line. The first line must be too large to fit on the screen, even after screen lines of text are deleted from it. `:mode` does not help display things correctly after the bug.

If you move to the start of the next line, it goes away. It doesn't damage the file or cause a crash. But it is confusing.

Neovim behavior:

https://user-images.githubusercontent.com/16908019/222612079-a7c128b6-8103-4fdf-a8dd-a96d17fb83bb.mp4

Vim behavior:

https://user-images.githubusercontent.com/16908019/222614075-e61ab7d6-498c-4282-b929-30950a4f819b.mp4

### Steps to reproduce

1. Run nvim like so:

	    curl -s https://termbin.com/ac094 | nvim --clean

    You have to run it in a terminal that's small enough. My terminal is 14x35 lines x columns.

2. Type the following: `$(hD`.
3. The next line should now slide up into view. It will appear incorrectly. What happens changes with different small terminal sizes. At my size, part of the beginning of the line disappears. At another size, blank lines show.

### Expected behavior

The start of the next line should show underneath the first line.

### Neovim version (nvim -v)

0.9.0-dev-1059+g2c9fbe34b-0 (this is from my package manager, I couldn't find the commit from neovim)

### Vim (not Nvim) behaves the same?

no, vim 9.0.1350

### Operating system/version

Android 10

### Terminal name/version

termux 0.118.0

### $TERM environment variable

xterm-256color

### Installation

pkg (termux package manager)

**Comment by zeertzjq** [comment]
Fixed in Vim in patch 9.0.{0640,0641}

**Comment by luukvbaal** [comment]
Can we get an updated repro for this? The termbin link is expired.

**Comment by beelzebielsk** [comment]
Here's the text from the termbin link.

```
- ggg ggg gggg gggggggg ggggg'g ggggggg. g ggg ggggggg gggggggggg gggg ggg gggggg gggg ggggg gggg. "gggg, g'g gggg ggggg gggg ggggggggg gggggg/ggggggg/ggg. ggggg gggggg ggggggggggggg," ggg gggggggg g gggggg ggg gg, "gg gggg'g gggg ggg ggg gg g ggg ggg, gggg'g gggg ggg ggggggg gg g gggg ggg." ggg ggg gggg gggg ggg ggggg gggg gggg ggggggg. f fff'f fffffff fffff ffffffffff fff fffffffff ffffff ff fffffff ffff. f fff'f fffffff fffff ffffffffff fff fffffffff ffffff ff fffffff ffff. f fff'f fffffff fffff ffffffffff fff fffffffff ffffff ff fffffff ffff.
- a'aaa aaaaa aa aaaaaa aaaaa aa aaa aaaa aaaaa aaa. a aaaaaaaaaa aaaa aaa aaaaaa aaaa aa aa @@@@@@ bbbbbb bbb bbbb bbbb bbbbbb, bbb bbbb'b bbb b bbbbbbb. bb bbbbb'b bbbbbb bbbb b'bbb *bbb*. 
```

**Comment by luukvbaal** [comment]
Thanks, confirmed fixed in https://github.com/neovim/neovim/pull/23320
