### ISSUE TITLE
Treesitter: align with upstream behavior

### ISSUE THREAD

**Issue by clason** [neovim/neovim#22495]
Neovim's treesitter highlighting implementation is different from that in the tree-sitter reference highlighter (which is used by Helix and Github and, it's fair to guess, Zed), which has consequences to how queries are written. This in turn prevents us from sharing highlighting queries across editors, which would be very much desirable for obvious reasons. We should consider changing our behavior to match upstream so the queries can be aligned and shared. (This would mean breaking changes and a good deal of work for nvim-treesitter, but @amaanq has kindly volunteered to spearhead that effort.)

There are two major issues:

## Query order

Right now, we apply highlights for _all_ found matches and rely on extmark ordering to select the "winner". In effect, this means "last match wins", which means that more specific queries need to come _after_ more general queries.

In contrast, the upstream highlighter skips all highlights after the first one:
https://github.com/tree-sitter/tree-sitter/blob/c51896d32dcc11a38e41f36e3deb1a6a9c4f4b14/highlight/src/lib.rs#L824-L832
https://github.com/tree-sitter/tree-sitter/blob/c51896d32dcc11a38e41f36e3deb1a6a9c4f4b14/highlight/src/lib.rs#L853-L865
(The same code is in Helix.)

In effect, this means "first match wins", which means that more specific queries need to come _before_ more general queries.

I think we should implement the same logic. In order for `; extends` and `; inherits` to then still work as expected, we just need to concatenate them in reverse order to the current one.

**EDIT** Upstream seems to like our strategy (and hence order) better, so this may be a case where _they_ align with _us_; many parsers also provide queries in "Neovim order" (being contributed by nvim-treesitter users).

## Injection queries

For some (but not all) injections, we need to manually collect the ranges via the [`#exclude_children!` directive in nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/blob/a0d6c28f893cbbc761cfa7fc7204ba6f3e2710cf/lua/nvim-treesitter/query_predicates.lua#L164-L187), which is not necessary in upstream. Here, too we should change this.

(I believe Helix implements our default behavior by setting an `include-unnamed-children` metadata for injections?)

(@theHamsta needs to explain what this does and why this is needed, though...)

* [x] https://github.com/neovim/neovim/pull/22518

**Comment by justinmk** [comment]
For reference: upstream is considering changing the order of query resolution to match Nvim's original "last wins" approach: https://github.com/nvim-treesitter/nvim-treesitter/issues/3944#issuecomment-1458782497 

> query precedence order - This is fairly minor, but right now, the tree-sitter-highlight crate prefers matches listed earlier in the query, so that you need to list the most specific patterns first. I noticed that Neovim uses the opposite convention, and I think this may be slightly more intuitive, because it matches the behavior of the "cascade" in CSS. Also, in Zed, we also found it slightly easier to implement with the more specific matches occurring later (like Neovim).

**Comment by clason** [comment]
For reference: upstream has decided to indeed change their query order to match Neovim's: https://github.com/tree-sitter/tree-sitter/issues/2396#issuecomment-1641210799

Further alignment concerns capture names to make sharing highlight queries easier, but that is tracked in nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter/issues/4799

So there's nothing more to do here.
