### ISSUE TITLE
preview/documentation  for vim.ui.select

### ISSUE THREAD

**Issue by IndianBoy42** [neovim/neovim#22520]
### Problem

Entries in vim.ui.select have to/should be single line and concise. However for many use cases it would be useful to be able to see a preview of what that selection would do, or a longer description, or a docstring, etc. Any kind of lengthier description that would probably be display in an adjacent floating window

### Expected behavior

Could add a new (optional) key to the `opts` argument to `vim.ui.select` called `preview_item` requiring a similar signature to `format_item` but returning a string or a list of strings (lines). The implementor of `vim.ui.select` would then decide how/when to display that to the user, but generally based on the currently 'selected' but not confirmed entry

**Comment by justinmk** [comment]
> add a new (optional) key ... `preview_item`... The implementor of `vim.ui.select` would then decide how/when to display that to the user,

vim.ui.select provider can already provide preview if they want. Not seeing why a new core interface is needed.

**Comment by IndianBoy42** [comment]
If it's not a file then vim.ui.select wouldn't know what preview to show. For something like code actions or commands the preview/docstring would be provided by whatever is supplying the items
