### ISSUE TITLE
OSC 7 (CWD) in :terminal

### ISSUE THREAD

**Issue by mgedmin** [neovim/neovim#2252]
When I use :term, I get a lot of

> libvterm: Unhandled OSC 7;file://platonas/home/mg/src/neovim

These come from my bash PROMPT_COMMAND, which is set in /etc/profile.d/vte-2.91.sh (and then overriden in my .bashrc, but that doesn't actually matter).

OSC 7 is used by gnome-terminal to determine the current working directory of the terminal tab (so the user can open a new tab in the same place with a single key combination).

Ideally neovim ought to pass this sequence through to the real terminal.

**Comment by mgedmin** [comment]
> Ideally neovim ought to pass this sequence through to the real terminal

Correction: *ideally* neovim would track the current working directory of each buffer internally, and emit the OSC 7 whenever the user switches between windows (or tabs or buffers).  And receiving OSC 7 from a :terminal would treat it like a :lcd and update the internal CWD for that buffer.

**Comment by tarruda** [comment]
> When I use :term, I get a lot of

> libvterm: Unhandled OSC 7;file://platonas/home/mg/src/neovim

You should not be seeing these messages: https://github.com/neovim/neovim/issues/2251#issuecomment-86482985

> Correction: ideally neovim would track the current working directory of each buffer internally, and emit the OSC 7 whenever the user switches between windows (or tabs or buffers). And receiving OSC 7 from a :terminal would treat it like a :lcd and update the internal CWD for that buffer.

That's nice to have, but I think it must be implemented in libvterm first. cc @leonerd

**Comment by leonerd** [comment]
I don't like the idea of `libvterm` actually understanding what `OSC 7;...` means, but I am soon intending to add a set of callback hooks at the `VTermState` and `VTermScreen` layers for unhandled controls/etc.. So the application can always be informed of extra junk like this that `libvterm` itself doesn't understand, and handle them appropriately.

**Comment by tarruda** [comment]
> I don't like the idea of libvterm actually understanding what OSC 7;... means, but I am soon intending to add a set of callback hooks at the VTermState and VTermScreen layers for unhandled controls/etc.. So the application can always be informed of extra junk like this that libvterm itself doesn't understand, and handle them appropriately.

:+1: that would be perfect

**Comment by mgedmin** [comment]
Ah, `make distclean && make` did make these messages go away.

**Comment by leonerd** [comment]
Keep an eye on https://blueprints.launchpad.net/libvterm/+spec/unrecognised-fallback

**Comment by justinmk** [comment]
See also https://gitlab.com/gnachman/iterm2/issues/3939

**Comment by paulreimer** [comment]
> Keep an eye on https://blueprints.launchpad.net/libvterm/+spec/unrecognised-fallback

Was this merged? (that page says "Status: Started" + "Work item: DONE" + "Implementation: Deployment" + "Milestone target: v0.1" and... I'm not sure what that means)

**Comment by leonerd** [comment]
Yes that was finished -years- ago ;)

**Comment by glacambre** [comment]
With https://github.com/neovim/neovim/pull/22159 now being merged, OSC7 support can be implemented like this:

```lua
vim.api.nvim_create_autocmd({ 'TermRequest' }, {
  callback = function(e)
    if string.sub(vim.v.termrequest, 1, 4) == "\x1b]7;" then
      local dir = string.gsub(vim.v.termrequest, "\x1b]7;file://[^/]*", "")
      if vim.fn.isdirectory(dir) == 0 then
        return
      end
      vim.api.nvim_buf_set_var(e.buf, "last_osc7_payload", dir)
      if vim.o.autochdir and vim.api.nvim_get_current_buf() == e.buf then
        vim.cmd.cd(dir)
      end
    end
  end
})
vim.api.nvim_create_autocmd({ 'bufenter', 'winenter', 'dirchanged' }, {
  callback = function(e)
    if vim.b.last_osc7_payload ~= nil
      and vim.fn.isdirectory(vim.b.last_osc7_payload) == 1
    then
      vim.cmd.cd(vim.b.last_osc7_payload)
    end
  end
})
```

**Comment by justinmk** [comment]
In https://github.com/neovim/neovim/pull/24163 I added `:help terminal-events` where we can collect these OSC recipes.
