### ISSUE TITLE
Cursor flashes with lazyredraw

### ISSUE THREAD

**Issue by vheon** [neovim/neovim#2253]
With my current setup [vheon/home](https://github.com/vheon/home) I got cursor flashes when I move around, or in the line below or after the `colorcolumn`. I was not able to track this down fully but:

minivimrc

``` viml
set showcmd
set lazyredraw
```

and doing `nvim -u minivimrc .vim/vimrc` and move the cursor down with `j` then in the below right corner I got the command I pressed (for the `showcmd`) and the cursor right next to it.

Doing this with `vim -u minivimrc .vim/vimrc` I do not get this.

Without `lazyredraw` I do not get this behaviour.

**Comment by justinmk** [comment]
Is there a reason lazyredraw should be optional?

**Comment by Pyrohh** [comment]
@ZyX-I posted this reason a while ago https://github.com/neovim/neovim/pull/1667#issuecomment-67326248

I don't know if it still has the same effect.

**Comment by justinmk** [comment]
@Pyrohh Thanks for digging that up.

> :set lazyredraw causes Command-T to "freeze" Vim if it appears that switching to some buffer or 

I believe command-t plugin uses an interactive shell, so this is the same issue as https://github.com/neovim/neovim/issues/1044 and won't work in neovim anyways.

> opening some file requires some sort of confirmation: YCM question regarding whether to load its configuration file, Vim question regarding whether to load externally changed file, ... these dialogs still require user action, but they are not visible.

Hmm. Any time a confirm() dialog requires input and there is no typeahead, nvim should be able to force a redraw or whatever. I don't see how a `lazyredraw` option is necessary for that.

**Comment by vheon** [comment]
> I believe command-t plugin uses an interactive shell, so this is the same issue as #1044 and won't work in neovim anyways.

No command-t use a normal vim buffer.

**Comment by justinmk** [comment]
Feedback on https://github.com/neovim/neovim/pull/6366 would be helpful.

**Comment by justinmk** [comment]
I have not seen cursor flashes in a long time, even with:

```
set showcmd
set lazyredraw
set cursorline
set colorcolumn=...
```

#6729 covers other lazyredraw issues.
