### ISSUE TITLE
lua script with BOM error on ARM64

### ISSUE THREAD

**Issue by EvanCarroll** [neovim/neovim#22546]
### Problem

I created testing steps here, they requires

* `buildah`
* `podman`
* arm64

https://github.com/EvanCarroll/vim-arm64-failure

The error generated is 

* https://github.com/EvanCarroll/vim-arm64-failure

### Steps to reproduce

In repo,

```shell
sh ./test.sh
```

### Expected behavior

No error about the `<ef>` byte, works like amd64.

### Neovim version (nvim -v)

NVIM v0.7.2.

### Vim (not Nvim) behaves the same?

N/A. Vim doesn't have lua.

### Operating system/version

Debian Bookworm ARM64 on M1.

### Terminal name/version

xterm

### $TERM environment variable

any version

### Installation

Install UTM. Install Debian Bookworm. Install VIM from repo. Try running a lua file with BOM.

**Comment by EvanCarroll** [comment]
Note, nothing about this bug is specific to this test case... You can take any `arm64` install and

```shell
mkdir ~/.config/nvim;
touch ~/.config/nvim/init.lua;
nvim ~/.config/nvim/init.lua;
```

Then `:set bomb` and `:wq`

Run `nvim` again. and you'll get this error.

If you don't get this error, perhaps it's only the version on Debian Bookworm? Not sure.

**Comment by bfredl** [comment]
sounds like a luajit issue (why the behavior is inconsistent between plattforms. they implement a lot of stuff in asm). But setting a bomb is an anti-pattern for plain text fileformats since forever. where is the use case that makes this necessary to support?

**Comment by EvanCarroll** [comment]
@bfredl "plain text" doesn't exist, it has to be encoded. The BOM tells lua that the "plain text" is unicode, and moreover what that encoding is. Even if lua just sees the bytes in the string as a byte-string and the language itself is just an arbitrary sequence of bytes, in this case - for the purposes of Neovim and other utilities that edit and view the file - it tells you that the source code is Unicode and UTF-8.

**Comment by EvanCarroll** [comment]
What do you mean, no it doesn't. Sure it does. Here is the BOM chart: https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding

```
:version
NVIM v0.7.2
Build type: Release
Lua 5.1
Compiled by team+vim@tracker.debian.org
```

**Comment by bfredl** [comment]
It doesn't for lua and not for neovim. Just being valid UTF-8 (which without a BOM, importantly, is functionally a superset of ASCII) is enough to be treated as UTF-8.

> Lua 5.1

Seems like the root issue. somehow neovim gets built with puc lua 5.1 which does not handle the BOM. 

But luajit should be available for your platform https://packages.debian.org/search?suite=bookworm&arch=arm64&searchon=names&keywords=luajit

**Comment by EvanCarroll** [comment]
When you say "puc lua" what do you mean, and is this bug filed upstream if it's on lua?

**Comment by clason** [comment]
"PUC Lua" == "Not LuaJIT"

Any sane build of Neovim should prefer LuaJIT over the original implementation by the Pontifical Catholic University of Rio de Janeiro in Brazil.

**Comment by EvanCarroll** [comment]
Sounds like Debian testing is way out then =(

**Comment by bfredl** [comment]
>  is this bug filed upstream if it's on lua?

The bug upstream would be for debian. @jamessan maybe has some thoughts

**Comment by EvanCarroll** [comment]
Yes, that's the right one. Debian has already got it as a high priority to put out neovim 0.8.3 on the tracker https://tracker.debian.org/pkg/neovim but I don't see a failing build to tell me what the hold up is on it. I want to help out with the Debian stuff but it's hard to wrap my head around how it works.

I also don't understand how you knew Lua wasn't using luajit? It seems to be linked to luajit:

```text
❯ ldd /usr/bin/nvim
	linux-vdso.so.1 (0x00007ffcd833e000)
	liblua5.1-luv.so.0 => /lib/x86_64-linux-gnu/liblua5.1-luv.so.0 (0x00007fb6c53d2000)
	libuv.so.1 => /lib/x86_64-linux-gnu/libuv.so.1 (0x00007fb6c53a2000)
	libmsgpackc.so.2 => /lib/x86_64-linux-gnu/libmsgpackc.so.2 (0x00007fb6c5399000)
	libvterm.so.0 => /lib/x86_64-linux-gnu/libvterm.so.0 (0x00007fb6c5387000)
	libtermkey.so.1 => /lib/x86_64-linux-gnu/libtermkey.so.1 (0x00007fb6c537a000)
	libunibilium.so.4 => /lib/x86_64-linux-gnu/libunibilium.so.4 (0x00007fb6c5365000)
	libtree-sitter.so.0 => /lib/x86_64-linux-gnu/libtree-sitter.so.0 (0x00007fb6c5337000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb6c5258000)
	libluajit-5.1.so.2 => /lib/x86_64-linux-gnu/libluajit-5.1.so.2 (0x00007fb6c51cc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb6c4feb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb6c4fe6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb6c4fe1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb6c58cc000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb6c4fc1000)
```

When I look at the luajit package in Debian it says,

```text
Description-en: Just in time compiler for Lua programming language version 5.1
 LuaJIT implements the full set of language features defined by Lua 5.1. The
 virtual machine (VM) is API- and ABI-compatible to the standard Lua interpreter
 and can be deployed as a drop-in replacement.
 .
 This package contains the standalone interpreter/jitter that can be used
 as a replacement for the standard lua5.1 interpreter.
```

So it seems Lua 5.1 is LuaJIT? How were you able to conclude it's not LuaJIT -- on the version number alone?

**Comment by clason** [comment]
This is getting off-topic for this repo -- read the documentation (`:h lua` is a good starting point) or ask on Matrix.

**Comment by EvanCarroll** [comment]
Thakns @clason you're 100% right that's the difference. I thought it was a bug in Lua for one arch. The problem is on the arm64 that I see this bug in they're **NOT** linked with luajit. Which is really confusing because luajit is in packaged for arm64 in the repo.. And now I see the difference you saw. ;)

When I run `:version` on the one in arm64, I see

```text
:version
NVIM v0.7.2
Build type: Release
Lua 5.1
```

When I run `:version` on the one in amd64, I see

```text
:version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```
Thanks, sorry for being a pita.

**Comment by jamessan** [comment]
> I also don't understand how you knew Lua wasn't using luajit? It seems to be linked to luajit:
> 
> ```text
> ❯ ldd /usr/bin/nvim
> 	liblua5.1-luv.so.0 => /lib/x86_64-linux-gnu/liblua5.1-luv.so.0 (0x00007fb6c53d2000)
> 	libluajit-5.1.so.2 => /lib/x86_64-linux-gnu/libluajit-5.1.so.2 (0x00007fb6c51cc000)
>         ....
> ```

That's for x86_64, not arm64.  Last I checked, Debian's arm64 LuaJIT package wasn't fully functional from nvim's perspective, so PUC Lua is used on that platform.

I can revisit that validation when Trixie development starts.
