### ISSUE TITLE
<C-Left> and <C-Right> are handled incorrectly

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#2254]
The key combinations Ctrl+Left arrow key and Ctrl+Right arrow key don’t work in terminal emulation mode. Surprisingly, Ctrl+Up and Ctrl+Down work just fine.

Tested on:
---
a6e53a3 Merge PR #2076 'Builtin terminal emulation'

Steps to reproduce:
---
From a shell, run `nvim -u NONE term://sh`
Then, inside nvim, type `ich<C-Left>e<C-Right>o<CR>`

Expected results:
---
`<C-Left>` and `<C-Right>` make the cursor jump to previous and next word respectively. The final resulting line is `echo`.

Actual results:
---
`sh: $'ch\375\277\277\272\254\203e\375\277\277\272\250\203o': command not found`

**Comment by Pyrohh** [comment]
As pretext, my shell is `mksh` my terminal is `st`. I can't reproduce this inside tmux, but I can in plain `st`.  Here's the output of `<Ctrl-v>` for some of the keys in `st`:

	<Right>   ^[[D
	<Left>    ^[[C
	<C-Right  ^[OD
	<C-Left>  ^[OC

If I try the same inside `:term`, `<Right>` and `<Left>` work, but the ctrl variants print a [Unicode replacement character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character).

**Comment by Grimy** [comment]
I really don’t think it has anything to do with the application running inside the terminal (shell or otherwise) : I can reproduce the issue with `nvim term://cat`.

On the other hand, I do get different results depending on the terminal. `xterm` gives the behaviour I described above, while `roxterm` and `st` both give the Unicode replacement character.

**Comment by Pyrohh** [comment]
If you haven't already, could you try `uxterm`? I imagine that the replacement char will show up in that.

**Comment by HarmtH** [comment]
It seems like something (libtermkey?) converts the escaped values ('Meta sends Escape') to 8-bit values (or 16-bit in the case of UTF-8) ('Meta sets high-bit').

Example (in both cases pressed alt+b in an UTF-8 gnome-terminal on Ubuntu 12.04):

Normal:
cat | hd
^[b
00000000  1b 62 0a                                          |.b.|
00000003

Inside NeoVim:
cat | hd 
â 
00000000  c3 a2 0a                                          |...|
00000003

**Comment by Grimy** [comment]
> If you haven't already, could you try uxterm? I imagine that the replacement char will show up in that.

uxterm is just an alias for `xterm -u8` (actually, it sets a few other options, but that’s beyond the point). Since my xterm is configured to always run in utf-8 mode, I have no use for uxterm and tend to forget it exists.

Thanks for the reminder that this isn’t an usual config. In my future reports I’ll say uxterm instead of xterm, to make it clear that I’m talking about an utf-8 xterm.

I’ll try different combinations of unicode and meta options to see what happens.

**Comment by HarmtH** [comment]
Until this is 'fixed' (although it isn't really an error), you can add this to your /etc/inputrc (or to your ~/.inputrc, but remember that /etc/inputrc isn't loaded anymore if you do that):

"\xc3\xa6": forward-word 
"\xc3\xa2": backward-word

**Comment by justinmk** [comment]
Merging with https://github.com/neovim/neovim/issues/2440
