### ISSUE TITLE
nvim-winget bot needs to agree to winget-pkgs policy

### ISSUE THREAD

**Issue by russellbanks** [neovim/neovim#22545]
### Problem

See open pull requests for [Neovim.Neovim.Nightly in winget-pkgs](https://github.com/microsoft/winget-pkgs/pulls?q=Neovim.Neovim.Nightly+is%3Aopen).

Neovim can't be accepted to winget-pkgs until @nvim-winget comments `@microsoft-github-policy-service agree` on one of their PRs. I've approved the pull requests but they can't be merged yet because of it. This appears to be a recent change in winget-pkgs to enforce it, which is why it's only started happening recently.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Neovim version (nvim -v)

N/A

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

**Comment by zeertzjq** [comment]
@vedantmgoyal2009

**Comment by vedantmgoyal2009** [comment]
You just need to make a comment `@microsoft-github-policy-service agree company="Neovim"` on any PR from @nvim-winget.

**Comment by zeertzjq** [comment]
Oh, @justinmk

**Comment by justinmk** [comment]
Done, thank you for the note and clear instructions!

https://github.com/microsoft/winget-pkgs/pull/98528#issuecomment-1455686662
