### ISSUE TITLE
Jump to first text in line with 2x Home button

### ISSUE THREAD

**Issue by mrx23dot** [neovim/neovim#22564]
### Problem

When I press Home button it jumps to column1 in line.

### Expected behavior

but if we are already there we could jump to beginning of first text in same line,
otherwise it's a wasted function.

Similarly to VScode, Eclipse.

**Comment by clason** [comment]
Sorry, the behavior of default movements is such a fundamental part of the "Vim experience" -- which Neovim intentionally reproduces as part of its design goals -- that we will not change this.

You are free to rebind `<home>` to a custom function that behaves like you want; ask on vi.stackexchange.com or Matrix if you need help with that.
