### ISSUE TITLE
:checkhealth crashes with code 134 on wsl2 ubuntu

### ISSUE THREAD

**Issue by c01o** [neovim/neovim#22563]
### Problem

roughly 10 seconds after executing `:checkhealth`, nvim crashes with error code 134.
Logs on my display just before crash below.

```
nvim: require("nvim.health").check()

Configuration
- WARNING Missing user config file: /home/username/.config/nvim/init.vim
  - ADVICE:
    - :help nvim-from-vim

Runtime
- OK $VIMRUNTIME: /usr/share/nvim/runtime

Performance
- OK Build type: RelWithDebInfo

Remote Plugins
- OK Up to date

terminal
- key_backspace (kbs) terminfo entry: key_backspace=\177
- key_dc (kdch1) terminfo entry: key_dc=\E[3~

tmux
- OK escape-time: 1
- WARNING focus-events is not enabled. 'autoread' may not work.
  - ADVICE:
    - (tmux 1.9+ only) Set focus-events in ~/.tmux.conf:
      set-option -g focus-events on
- $TERM: screen-256color
- WARNING Neither Tc nor RGB capability set. True colors are disabled. 'termguicolors' won't work properly.
  - ADVICE:
    - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
      set-option -sa terminal-features ',XXX:RGB'
    - For older tmux versions use this instead:
      set-option -ga terminal-overrides ',XXX:Tc'
```

### Steps to reproduce

nvim --clean
:checkhealth
-> [134]

### Expected behavior

Don't crash

### Neovim version (nvim -v)

0.9.0-dev commit f9a463

### Vim (not Nvim) behaves the same?

no :checkhealth available for plain vim

### Operating system/version

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 GNU/Linux

### Terminal name/version

Windows Terminal 1.16.10262.0

### $TERM environment variable

screen-256color

### Installation

https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable

**Comment by c01o** [comment]
`:che nvim` finishes with the same log without crash.
`:che provider` crashes without any log.

**Comment by justinmk** [comment]
great, that narrows it down. to further narrow, try commenting out each of these: https://github.com/neovim/neovim/blob/5800151a1c63effc68ab87858cdc864dac4d4f7c/runtime/autoload/health/provider.vim#L748-L755

then to narrow even more, add a `return` at various places in the problematic function... this will tell us the precise code that causes the issue.

**Comment by c01o** [comment]
Thanks you!
Detected it fails on python environment detection
https://github.com/neovim/neovim/blob/5800151a1c63effc68ab87858cdc864dac4d4f7c/runtime/autoload/provider/pythonx.vim#L63-L72

where `module == neovim` and `prog` iterates over this.
https://github.com/neovim/neovim/blob/5800151a1c63effc68ab87858cdc864dac4d4f7c/runtime/autoload/provider/pythonx.vim#L29

`:checkhealth` crashes on the last iteration `prog == python`, which has `prog_path` == `/path/to/pyenv/shims/python`.

I'm still not sure why it crashes though.
If I run the `system()` command manually from my shell, with either `python` or `/path/to/pyenv/shims/python`, it just prints 3.9 (pyenv global version) and returns with code 2, the same as `python3` or `python3.9`.
These two `prog` successfully passed `s:import_module()` function with output of `[2, 3.9]`, and I can't tell the difference from them to `python`.

**Comment by justinmk** [comment]
since you're using wsl which is just linux,  can you try to get a backtrace: https://github.com/neovim/neovim/wiki/FAQ#backtrace-linux

**Comment by erw7** [comment]
https://github.com/neovim/neovim/issues?q=is%3Aissue+wsl+python+crash
