### ISSUE TITLE
Move line up/down with ALT+up/down

### ISSUE THREAD

**Issue by mrx23dot** [neovim/neovim#22565]
### Problem

Pressing ALT+up/down does the same thing as up/down.

### Expected behavior

So it's a wasted key combo, it could simply move current line (or visually selected ones) up/down by one.

Same way as in VScode.

**Comment by clason** [comment]
Sorry, the behavior of default movements is such a fundamental part of the "Vim experience" -- which Neovim intentionally reproduces as part of its design goals -- that we will not change this.

You are free to rebind `<alt-up>` to a custom function that behaves like you want; ask on vi.stackexchange.com or Matrix if you need help with that. Also make sure that your environment can actually distinguish `alt+arrow key`.
