### ISSUE TITLE
able to inform nvim to update the tabline string immediately

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#22599]
### Problem

I'm trying to implement the same functionality as tmux's `rename-window` to nvim's tab by rolling my own &tabline, and I was half way there.
But I failed to find a way to inform nvim to update the tabline string after I set the name for a tab, I also tried to ask it in the matrix chat room, no answers found; I tried `doautocmd TabEnter` and some other events, but it makes no difference.
So I think there is no decent ways to do that at the moment.

### Expected behavior

I'd like a way to inform nvim to update the tabline string immediately, or maybe there could be a tabpage-scoped option like &tabname.

**Comment by zeertzjq** [comment]
Doesn't `:redrawtabline` do this?

**Comment by haolian9** [comment]
Great, it did! Thank you!
