### ISSUE TITLE
cursorline always highlights the last line in terminal mode

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#2259]
When `cursorline` is set, while in terminal-mode, the bottom-most line in the window is permanently highlighted with `CursorLine` highlighting. Since it might not be easy or sensible to follow the terminal’s cursor, a workaround might be to disable cursorline while in terminal mode.
## Tested on:

a6e53a3 Merge PR #2076 'Builtin terminal emulation'
## Steps to reproduce:

Run `nvim -u NONE +'set cursorline' +startinsert term://sh`
## Expected results:

The first line is underlined (this might depend on the terminal used).
## Actual results:

The last line is underlined.

**Comment by Pyrohh** [comment]
I can reproduce this fine.

**Comment by GregorySchwartz** [comment]
Setting `cursorcolumn` also has this effect where the first column is highlighted.

**Comment by pbogut** [comment]
For ppl who arrived here from google (like I did).

You can use `autocmd` to switch column and line highlight of in a terminal.
I'm also disabling `listchars` as `eol` is always displayed at first column in a terminal.
```
autocmd TermOpen * setlocal listchars= | set nocursorline | set nocursorcolumn
```
