### ISSUE TITLE
An autocmd that trigger everytime a buffer is displayed in a window?

### ISSUE THREAD

**Issue by bew** [neovim/neovim#22597]
Testing the cursor-restore snippet I shared at https://github.com/neovim/neovim/issues/16339#issuecomment-1457394370 , something isn't working as I'd expect:
Starting nvim using the same file in multiple splits/tabs will restore cursor ONLY in the first window, not the others.
(and annoyingly, an immediate `:qa` will loose the last known position because the other windows (where cursor wasn't restored) are closed last)
I think we can generalize this more to the initial opening of a file in multiple splits from CLI or from scripting.

So doing:
```sh
nvim foo.txt foo.txt -p
```
Will open the file `foo.txt` in 2 tabs, but only the first tab will have its cursor restored to last known position :/
_(note: removing `once = true` in the 'nested' autocmd to test this doesn't help)_

This seems to be because `BufWinEnter` is purposefully not triggered if the buffer is already displayed in another window (as per its documentation).

I'd expect `BufWinEnter` with `once=true` to trigger once for each `(buf, win)` tuple. (WDYT?)

:point_right: Any idea what we could do to make this work?

_Aside: I'm not fond of the name `BufWinEnter` for that kind of specific use case, I think I'd like to suggest to rename it to something like `BufFirstWinEnter`. WDYT?_

## IDEA
Introduce another autocmd like `BufWinDisplay` that always triggers when a buffer is (first/again) displayed in a window.
(other name idea, a bit more general, as a window event: `WinBufChanged`)

I think this should trigger even when the window is currently not visible.

That event could even be made specific to a buffer and/or a window with `<buffer[=N]>` & `<window[=N]>`.

That autocmd could have other uses, like having a popup window with some info on the displayed buffer (lsp/..), that change every time the visible buffer changes (like a persistent little popup tied to a window).

_Originally posted by @bew in https://github.com/neovim/neovim/issues/16339#issuecomment-1462917655_

**Comment by justinmk** [comment]
- `BufEnter` already works like this. Even if the buffer is displayed in a window, switching another window to display the same buffer will fire `BufEnter.`
- To also handle the case where a window is split, handle `WinEnter`.
- To also handle the case where a tab is created, handle `TabEnter`.

> Aside: I'm not fond of the name `BufWinEnter` for that kind of specific use case, ... rename it to something like `BufFirstWinEnter`?

This can be mostly addressed by enhancing the autocmd docs, which currently are pretty horrible for understanding "lifecycle". Currently `:help BufEnter` shows lifecycle info ("After x, Before y") but `:help BufWinEnter` does not.

> ```shell
> nvim foo.txt foo.txt -p
> ```
>
> Will open the file foo.txt in 2 tabs, but only the first tab will have its cursor restored to last known position :/
