### ISSUE TITLE
Is custom defined priority for semantic tokens highlighting modifiers possible?

### ISSUE THREAD

**Issue by lucario387** [neovim/neovim#22601]
### Problem

A token may not be of 2 types, but it can be of many modifiers (builtin, readonly, static, ...). 

If some user (in this case, me), defines `@lsp.mod.foo` and `@lsp.mod.bar`, and there exists a variable with multiple modifiers, sometimes neovim doesn't know what hlgroup to use, as they are the same in priority but may be different in color

### Expected behavior

I'd like to either have an extra field in `nvim_set_hl` to define custom priority, or to have some way to set the priority level, so that it's easier to define highlights

**Comment by justinmk** [comment]
Please see if this doc answers your question:

https://gist.github.com/swarn/fb37d9eefe1bc616c2a7e476c0bc0316

**Comment by lucario387** [comment]
> Please see if this doc answers your question:
> 
> https://gist.github.com/swarn/fb37d9eefe1bc616c2a7e476c0bc0316

I'd say the doc answered the problem of not having priority for mods/typemods hlgroups. I also believe that there may be a better, more elegant solution to this issue (of which I know none)

I am more in fear of the complexity that it will take to override 3, or 4 modifiers collision. 


From the code of `:h LspTokenUpdate`, and the docs, I have an example code of

```lua
vim.api.nvim_create_autocmd("LspTokenUpdate", {
  callback = function(args)
    local token = args.data.token
    if token.modifiers.builtin and token.modifiers.readonly then
      vim.lsp.semantic_tokens.highlight_token(
        token, args.buf, args.data.client_id, '@lsp.mod.builtin'
      )
    end
  end,
})
```

to modify `declaration` and `public` modifiers behavior of jdtls
![image](https://user-images.githubusercontent.com/29790821/224369892-9c430609-0014-4a8b-a2be-6d5d635f551b.png)

And this is to override only one case, if one token were to have many modifiers, there will be many more cases to be overridden, and complexity seems to go up a lot? with each case added.


Now, if I expand it to, for example, having 3

**Comment by clason** [comment]
> I am more in fear of the complexity that it will take to override 3, or 4 modifiers collision.

But that is the inherent complexity of the LSP semantic token system; there's no way around that. The design in Neovim (which I strongly believe is correct!) is to offer
1. a convenient API for the simplest case
2. a powerful API for the most complex case
and nothing in between, as that is a very slippery slope. If you have a concrete suggestion how to improve the APIs with these two core aims in mind, we'd be happy to hear it.
