### ISSUE TITLE
libvterm: Unhandled CSI SGR 2

### ISSUE THREAD

**Issue by badeip** [neovim/neovim#2260]
~/wtf/ nvim -u NONE -N +term +'call feedkeys("ls --color=always -la\n")'

![screenshot](https://dl.dropboxusercontent.com/u/321061/libvterm.png)

OS: CentOS Linux release 7.0.1406 (Core)
NVIM 0.0.0-alpha+201503252208 (compiled Mar 26 2015 07:06:16)
Commit: a6e53a3797a93fe060f807fe2e4c6361854b6c97

**Comment by fwalch** [comment]
Does https://github.com/neovim/neovim/issues/2251#issuecomment-86482985 help?

**Comment by badeip** [comment]
@fwalch thanks, I just saw the comment.
I am running:

    make distclean all

but it fails fetching some dependencies now, so I can't tell if it solves my problem yet:

    Warning: Failed searching manifest: Failed fetching manifest for https://rocks.moonscript.org - Failed downloading https://rocks.moonscript.org/manifest

**Comment by Pyrohh** [comment]
`git grep -i  moonscript` in doesn't show any results, and we haven't been using moonscript for a while IIRC. If you haven't already, please try `git fsck --full`.

**Comment by badeip** [comment]
`git fsck --full` did not help, neither does `make distclean` or  `rm -rf * && git reset --hard` 
The moonscript dependencies are located in:
    .deps/usr/share/lua/5.1/luarocks/cfg.lua
    .deps/build/src/luarocks/src/luarocks/cfg.lua

However, I am still stuck on: 

    [ 93%] Generating usr/lib/luarocks/rocks/stable-busted-deps
    Warning: Failed searching manifest: Failed fetching manifest for https://rocks.moonscript.org - Failed     downloading https://rocks.moonscript.org/manifest
    Updating manifest for /home/pwahlman/source/neovim/.deps/usr/lib/luarocks/rocks
    lua_cliargs 2.3-3 is now built and installed in /home/pwahlman/source/neovim/.deps/usr (license: MIT <http://opensource.org/licenses/MIT>)


This might be the result of a network issue on the respective development machine (not administrated by me).
It seems likely that the originally reported problem was the result of not initially running `make distclan`, so I will probably just close this issue.

**Comment by Pyrohh** [comment]
That link (`https://rocks.moonscript.org/manifest`) isn't working for me too, so maybe the luarocks servers are just under maintenance.

**Comment by Pyrohh** [comment]
And if that's the case, then this should be closed.

**Comment by badeip** [comment]
@Pyrohh the reported issue was not related to the network related.
I will close the issue when I can verify if cleaning the repo and rebuilding solves the problem.

**Comment by Pyrohh** [comment]
I deleted that comment already, but it looks like you already saw it :)

**Comment by badeip** [comment]
@Pyrohh no worries ;)
`https://rocks.moonscript.org/manifest` is up now, and I just verified that the problem is solved by doing a clean rebuild
