### ISSUE TITLE
Visual Studio does not support `CMakePresets.json` file version 6

### ISSUE THREAD

**Issue by bluthej** [neovim/neovim#22608]
### Problem

When following the [recommended Windows build process](https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msvc) I get the following error during the initial automatic build:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		Visual Studio supports CMakePresets.json files versions 2 to 5. Please update your CMakePresets.json file. More info: aka.ms/cmakepresetsversion		<path>\Source\Repos\neovim\CMakePresets.json	1	
```

Manually changing the version from 6 to 5 in `CMakePresets.json`  fixes it.

### Steps to reproduce

1. Install [Visual Studio](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community) (2017 or later) with the Desktop development with C++ workload.
2. Open the Neovim project folder.

My installed version of Visual Studio is: `Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.5.1`

### Expected behavior

The build process should work without an error out of the box

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1184+g0ecb4d725

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10 Entreprise 22H2

### Terminal name/version

Windows Terminal 1.16.10261.0

### $TERM environment variable

none

### Installation

build from repo

**Comment by dundargoc** [comment]
Well, that's annoying. Workflow presets was what made presets worth using.

Does the build work correctly if you delete CMakePresets.json? If so, is there a way to instruct visual studio to ignore it?

**Comment by justinmk** [comment]
> Manually changing the version from 6 to 5 in `CMakePresets.json` fixes it.
> 
>> Well, that's annoying. Workflow presets was what made presets worth using.

Are workflow presets not supported by version 5?

**Comment by justinmk** [comment]
@bluthej does this actually prevent the build? darn...

**Comment by bluthej** [comment]
@justinmk it prevents the build as long as you don't manually change the version. After changing it, it works fine.

I'm just reporting it because this was my first time building neovim from source on Windows and I was a bit puzzled at first when this happened. I'm hoping the process can be smoothed out for my fellow Windows users :)
