### ISSUE TITLE
nvim --listen should accept sockets from systemd

### ISSUE THREAD

**Issue by ananthb** [neovim/neovim#22602]
### Problem

If nvim --listen accepted sockets from systemd, this would allow for headless neovim services to be started up on demand.

### Expected behavior

nvim --listen could take a special value like "systemd-socket" or nvim could learn a new flag for enabling socket activation.
This would allow neovim to be started by systemd service and socket units.

**Comment by bfredl** [comment]
> nvim --listen could take a special value like "systemd-socket" 

Likely not impossible at all but is there any reference documentation for what neovim is supposed to _do_ in this situation?

**Comment by ananthb** [comment]
I'd be able to implement this if someone pointed me in the right direction. Neovim creates the listening socket when --listen addr is given, right? To support this, neovim should accept a listening socket from systemd and accept connections on it.

**Comment by clason** [comment]
Well, first we need to decide whether we want this -- can you not explain in more detail what this entails, and how it would be used in an actual (useful) example?

**Comment by bfredl** [comment]
>  To support this, neovim should accept a listening socket from systemd and accept connections on it.

What does this mean? is the socket specified in an environment value? some hard-coded fd-value?

**Comment by justinmk** [comment]
Is the systemd-provided socket already created? Currently `--listen` will fail if the address already exists: https://github.com/neovim/neovim/blob/0ecb4d725e9e2086b045670e4c2fa8962b63d99c/src/nvim/msgpack_rpc/server.c#L40-L42

**Comment by ananthb** [comment]
@clason I run a headless Neovim on one machine and connect to it from another. I'd like to activate this service only when the socket is actually being used. Implementing socket activation allows systemd to manage the socket and start Neovim on demand. It also allows it to shut down Neovim when it's not needed anymore.

**Comment by bfredl** [comment]
We will not link to a systemd shared library. but perhaps these rules are simple enough to implement in plain c code:

> Internally, sd_listen_fds() checks whether the $LISTEN_PID environment variable equals the daemon PID. If not, it returns immediately. Otherwise, it parses the number passed in the $LISTEN_FDS environment variable, then sets the FD_CLOEXEC flag for the parsed number of file descriptors starting from SD_LISTEN_FDS_START. Finally, it returns the parsed number. sd_listen_fds_with_names() does the same but also parses $LISTEN_FDNAMES if set.

**Comment by mfussenegger** [comment]
There would also be https://www.freedesktop.org/software/systemd/man/systemd-socket-proxyd.html to have socket activation for services that don't support it naively.

**Comment by mfussenegger** [comment]
> that defeats the point of socket activation in a sense. It requires the target service to be up all the time

This is not true. It starts the target service ad-hoc if needed and you can set an `--exit-idle-time` to stop the service after it's been idle for some tim.e

See https://unix.stackexchange.com/questions/383678/on-demand-ssh-socks-proxy-through-systemd-user-units-with-socket-activation-does/635178#635178 for a full blown example

**Comment by ananthb** [comment]
Ah. I did not realise it could work that way. It would be neat if Neovim supported this natively, but this should work great in a pinch.

**Comment by ananthb** [comment]
Sure!

**Comment by ananthb** [comment]
@justinmk does it go in this file: https://github.com/neovim/neovim/blob/master/src/man/nvim.1. There's something about sockets on line 334. Is that it?

**Comment by ananthb** [comment]
@justinmk finally figured this out.

I've added very little detail now.
Should I add example config files too?
Or links to documentation that might be helpful.

Or both?
