### ISSUE TITLE
LSP client doesn't delete old buffers after renaming a directory

### ISSUE THREAD

**Issue by ivaaaan** [neovim/neovim#22617]
### Problem

When I'm renaming a directory, LSP client doesn't delete opened buffers from that directory after renaming is done, which causes an error when trying to save renaming result with `wa`. 

I think the problem is in this function https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L776, which is working correctly if you try to rename a single file, but doesn't delete old buffers with `old_fname` is a dir. 

### Steps to reproduce using "nvim -u minimal_init.lua"

```
--- CHANGE THESE
local pattern = 'go'
local cmd = {'gopls'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'pack', 'pack/file.go', 'main.go'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'bugged-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```

```bash
cd /tmp && mkdir -p lsp/pack && cd lsp
go mod init nvim.lua
echo "package pack" > pack/pack.go

````

Try call rename action by placing cursor on `pack` and then `:wa`. 

### Expected behavior

All files open buffers within the renamed directory are deleted. 

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1189+gd3c8d104b-dirty

### Language server name/version

gopls

### Operating system/version

macos

**Comment by ivaaaan** [comment]
#22618 my ugly fix which tries to fix it. if you think it is a viable solution I can try to clean it up and write some tests

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/issues/22075 

> Try call rename action by placing cursor on `pack` and then `:wa`.

what exactly does that mean? rename() is called by `apply_workspace_edit` which happens in several places. To judge the use-case it is important to mention the actions taken.

Though in general the idea makes sense. If `apply_workspace_edit` renamed a bunch of files then the dangerous part already happened, so deleting some buffers seems reasonable.

**Comment by ivaaaan** [comment]
> what exactly does that mean? rename() is called by `apply_workspace_edit` which happens in several places. To judge the use-case it is important to mention the actions taken.

I meant renaming package name in Go. When you rename it, the directory is renamed as well, which is causing problems with old buffers.
