### ISSUE TITLE
Background color is detected late

### ISSUE THREAD

**Issue by antistic** [neovim/neovim#22614]
### Problem

The value of "background" doesn't get set properly until after startup

### Steps to reproduce

nvim --clean -c "set background?" # outputs background=dark
:set background? # outputs background=light

### Expected behavior

Both values to be the same. Ideally I would be able to use this value in my config to set the appropriate colour scheme.

### Neovim version (nvim -v)

v0.8.3

### Vim (not Nvim) behaves the same?

no, 9.0.1337

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

Arch Repository (community)

**Comment by justinmk** [comment]
Depends on if, and when, your terminal responds to the bg color request. This is inherently racy. 

> I would be able to use this value in my config to set the appropriate colour scheme.

If you want your config to actually wait on the bg color, do your config in a `VimEnter` handler.

If Nvim implements an enhanced `TermResponse` event https://github.com/neovim/neovim/issues/6279 then that could also be used in the future.

**Comment by antistic** [comment]
Thanks for the explanation.

For anyone else with the problem:

`VimEnter` and `UIEnter` didn't work for me. `OptionSet` with background worked for the light background (presumably because the default is dark). You could set the dark theme and then change it to the light scheme when the option is set. However, this doesn't work for dark themes which set the background again when they're loaded.

`vim.schedule` worked, though it's probably a little bit hacky and results in some screen flash. I'm okay with this workaround for now.

**Comment by ecnerwala** [comment]
This workaround doesn't quite work for me, I think it's messing with the bufferline which is already rendered by the time the autocmd is called. Is there a way to simply disable the background autodetection? I have an explicit `set background=dark` which should work fine but is just getting clobbered by late autodetection.

**Comment by rozbb** [comment]
Yup. Ran into the same issue after upgrading to 0.9.0. Running iTerm 3.4.19 on a Macbook Air M1

**Comment by bfredl** [comment]
there's a race condition in `set_tty_background` . `option_was_set("bg")` is checked immediately but if `starting` color is not changed until VimEnter. We need to check again _at VimEnter_ if the option was set by the user.

**Comment by youginil** [comment]
https://github.com/neovim/neovim/blame/26cc946226d96bf6b474d850b961e1060346c96f/src/nvim/optionstr.c#L844-L866

The problem maybe caused by `did_set_background`, this function is a callback after setting background, it should not `init_highlight`, I think `init_highlight` should be called only once before user config.
