### ISSUE TITLE
code_action makes unexpected ranges when it called form linewise-visual mode

### ISSUE THREAD

**Issue by kyoh86** [neovim/neovim#22629]
### Problem

If I call `vim.lsp.buf.code_action()` from linewise-visual mode (`V`) without explicit range, it makes a range by `range_from_selection()`.
But it gives not a line-wise range but a characters-wise.

It may makes a buggy behavior like #21326 .

### Steps to reproduce using "nvim -u minimal_init.lua"

It requires a LSP supporting code_action with a range like `gopls`.
(I'm using `gopls` )
So I should prepare a dependencies with like Dockerfile to reproduce it.
I'll do it later.

note for me:

```
require("lspconfig").gopls.setup {}
vim.vim.lsp.set_log_level(vim.log.levels.TRACE)
vim.keymap.set("v", "<leader>lca", vim.lsp.buf.code_action)
```

### Expected behavior

It makes line-wise range.

### Neovim version (nvim -v)

v0.9.0-dev-286777c

### Language server name/version

gopls v0.11.0

### Operating system/version

Ubuntu 22

### Log file

https://gist.github.com/kyoh86/3cbeb80ff07bfee93a84503aedb25e42

**Comment by mfussenegger** [comment]
Could you try with https://github.com/neovim/neovim/pull/22632 ?

**Comment by kyoh86** [comment]
@mfussenegger Thanks for the super fast fix, seriously. It's perfect!!!
