### ISSUE TITLE
Incomplete vim.notify message with set cmdheight=2 during startup

### ISSUE THREAD

**Issue by adoyle-h** [neovim/neovim#22646]
### Problem

When call `vim.notify('123', vim.log.levels.ERROR)` **before** `vim.opt.cmdheight = 2`, it prints only `Error detected while processing`, but no "123" printed.

<img width="809" alt="CleanShot 2023-03-13 at 01 45 37@2x" src="https://user-images.githubusercontent.com/1998490/224562669-10d63d7c-bce2-4a44-b6e6-addad8339fb4.png">

---

Note: When call `vim.notify` **after** `cmdheight=2`, it works as expected.

```lua
vim.opt.cmdheight = 2
vim.notify('123', vim.log.levels.ERROR)
```

<img width="868" alt="CleanShot 2023-03-13 at 01 47 00@2x" src="https://user-images.githubusercontent.com/1998490/224562761-60b1b3bf-e2c9-41ce-a0b6-c22165b6f936.png">

### Steps to reproduce

1. Create a `minimal.lua` file.

```lua
vim.notify('123', vim.log.levels.ERROR)
vim.opt.cmdheight = 2
```

2. `nvim --clean -u ./minimal.lua`. You will see the error message that missing "123".

### Expected behavior

Print the error message includes "123".

<img width="868" alt="CleanShot 2023-03-13 at 01 47 00@2x" src="https://user-images.githubusercontent.com/1998490/224562728-a98e1f68-93bb-4c36-91a2-9ab52155329d.png">

### Neovim version (nvim -v)

v0.8.3

### Vim (not Nvim) behaves the same?

no test

### Operating system/version

MacOS 12.2

### Terminal name/version

iTerm2 3.5.0beta10

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by justinmk** [comment]
In general it's a known issue that during startup, messages are not displayed and/or not highlighted.

- https://github.com/neovim/neovim/issues/16750
- https://github.com/neovim/neovim/issues/8676#issuecomment-487357807
- https://github.com/neovim/neovim/issues/21178


Long-term solution is likely to "queue" messages so that their display does not depend on stale screen state: https://github.com/neovim/neovim/issues/22478

**Comment by justinmk** [comment]
I can't repro this. Try latest development version.

**Comment by justinmk** [comment]
I can't repro this interactively, e.g. if the following is in a mapping:

```
nvim --clean
nn a :lua vim.notify('123', vim.log.levels.ERROR) ; vim.opt.cmdheight = 2<cr>
```

**Comment by adoyle-h** [comment]
Yes. This issue only reproduce on startup.
The `Error detected while processing` message is printed in `do_exrc_initialization`.

https://github.com/neovim/neovim/blob/e5f4394eb7a27a9e5eaab088e6acf5553c64cf59/src/nvim/main.c#L2046-L2061

How about concat `Error detected while processing` and `err.msg` into one line? Like `semsg("Error detected while processing %s: %s", VIMRC_LUA_FILE, err.msg)`.
