### ISSUE TITLE
Call tui_normal_mode from tui_start?

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2265]
With `NVIM_TUI_ENABLE_CURSOR_SHAPE` being set ([ref](https://github.com/neovim/neovim/pull/2007#issuecomment-74863439)), the cursor shape is not initialized when starting nvim.

Calling `tui_normal_mode` from `tui_start` fixes it:

    diff --git i/src/nvim/tui/tui.c w/src/nvim/tui/tui.c
    index 72f9397..8d31c23 100644
    --- i/src/nvim/tui/tui.c
    +++ w/src/nvim/tui/tui.c
    @@ -162,6 +162,7 @@ void tui_start(void)
       ui->set_icon = tui_set_icon;
       // Attach
       ui_attach(ui);
    +  tui_normal_mode(ui);
     }
     
     static void tui_stop(UI *ui)

**Comment by justinmk** [comment]
Fixed by #5419 / eeec0cab5848
