### ISSUE TITLE
`vim.treesitter.inspect_tree()` does not respect `'splitright'`

### ISSUE THREAD

**Issue by yochem** [neovim/neovim#22656]
### Problem

With the option `splitright` set, new window should split to the right of the current window. `vim.treesitter.inspect_tree()` opens on the left.

(nvim-treesitter/playground however works as expected and splits on the right)

### Steps to reproduce

I couldn't get treesitter to start with `nvim --clean`, but:

```
$ nvim +'h news'
:set splitright
:lua vim.treesitter.inspect_tree()
```

### Expected behavior

Inspection tree opens on the right

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1222+gf01f18cdf-dirty

### Vim (not Nvim) behaves the same?

-

### Operating system/version

macOS 13.2.1

### Terminal name/version

iTerm2 3.4.19

### $TERM environment variable

tmux-256color

### Installation

homebrew upgrade --fetch-HEAD neovim

**Comment by yochem** [comment]
Will look into it

**Comment by zeertzjq** [comment]
This is just a question about changing the default value of `command`
```
                • command (string|nil): Vimscript command to create the
                  window. Default value is "topleft 60vnew". Only used when
                  {winid} is nil.
```

**Comment by yochem** [comment]
Yes, I thought about this as a fix:

```diff
diff --git a/runtime/lua/vim/treesitter.lua b/runtime/lua/vim/treesitter.lua
index 56000f99a..834757c4e 100644
--- a/runtime/lua/vim/treesitter.lua
+++ b/runtime/lua/vim/treesitter.lua
@@ -465,7 +465,11 @@ function M.inspect_tree(opts)

   local w = opts.winid
   if not w then
-    vim.cmd(opts.command or 'topleft 60vnew')
+    if vim.opt.splitright:get() then
+      vim.cmd(opts.command or 'botright 60vnew')
+    else
+      vim.cmd(opts.command or 'topleft 60vnew')
+    end
     w = a.nvim_get_current_win()
   end
```

Is that alright?

**Comment by yochem** [comment]
We could also leave out the topleft/botright part. It's a better match with the file of which it is the syntax tree, but I get the desire to have a full-height syntax tree.

**Comment by gpanders** [comment]
No need to have separate, redundant `if` branches:

```lua
if not w then
  vim.cmd(opts.command or ('%s 60vnew'):format(vim.o.splitright and 'botright' or 'topleft'))
end
```

>We could also leave out the topleft/botright part. It's a better match with the file of which it is the syntax tree, but I get the desire to have a full-height syntax tree.

The subjective nature of what is "better" is exactly why we have the ability to specify an arbitrary command. Unfortunately, we cannot satisfy everyone so we provide the user some flexibility.

**Comment by lewis6991** [comment]
What's the rationale for using`topleft` by default?

**Comment by yochem** [comment]
Ah yes, forgot about using `and` and `or` like that.

**Comment by gpanders** [comment]
> What's the rationale for using `topleft` by default?

Do you mean as opposed to `botright`? Arbitrary I suppose. IIRC the `nvim-treesitter/playground` plugin opens to the left too (at least it did when I used it), so I suppose I subconsciously modeled it after that.

If you mean why use `topleft` instead of just `vnew`, it is to have the window take up the full available height.

I'll grant that the default options were chosen for no other reason than "looks good to me". If there's a consensus on better defaults we can change.

**Comment by lewis6991** [comment]
> If you mean why use topleft instead of just vnew, it is to have the window take up the full available height.

Right I see. I think I feel pretty mixed about that. I think it's more predictable to just do `vnew`.

**Comment by yochem** [comment]
> I think it's more predictable to just do vnew.

I agree.

Maybe introduce an option to `vim.treesitter.inspect_tree()` to use the full height? Of course this is already possible using the `command` option, but I suspect not many users know the `topleft` and `botright` commands or other ways to do this.

**Comment by yochem** [comment]
@gpanders what do you think? I can make a PR removing the `topleft` part.

**Comment by clason** [comment]
I am less concerned with `inspect_tree`, which is low-level and should arguably indeed not set any implicit defaults than with (the later addition) `:InspectTree`, which is now the main user interface.

If `inspect_tree` is changed, we shouldn't forget to adapt `InspectTree` accordingly.

**Comment by justinmk** [comment]
Just a plain `:vnew` is fine, or even `:split`. Then user can do `:vertical InspectTree` and similar. That is the standard vim idiom and avoids adding a bunch of options everywhere.



> Maybe introduce an option to `vim.treesitter.inspect_tree()`

no

**Comment by gpanders** [comment]
>Then user can do :vertical InspectTree and similar. 

This is a good idea. The implementation of `:InspectTree` needs to be modified to pass along the `mods` field to `vim.treesitter.inspect_tree()` though.

Plain `:vnew` as the default is fine with me.

**Comment by yochem** [comment]
So if I understand correctly:

- `:lua vim.treesitter.inspect_tree()` --> `:vnew`
- `:InspectTree` --> `:vnew` (?)
- `:horizontal InspectTree` --> `:new`
- `:vertical InspectTree` --> `:vnew`

Is that correct?

**Comment by clason** [comment]
No, the last two should just pass the modifier to `inspect_tree`, see `:h lua-guide-commands-create` and the linked help pages.

And for the first two, it's enough to make the default(!) argument just `:vnew`.

**Comment by yochem** [comment]
> No, the last two should just pass the modifier to inspect_tree

Sorry, that's what I meant to say. I'll implement it like that!

**Comment by yochem** [comment]
Should `:InspectTree` also be able to receive a count? e.g. to do `:50InspectTree`?

**Comment by clason** [comment]
What would that do?

**Comment by yochem** [comment]
> What would that do? Open the tree for the tree (which is tree-sitter highlighted) for the tree for the... you get the idea?

It would specify the width of the window, as it does now currently (set to 60 in the default) and other commands that open windows like `:25Explore` etc.

**Comment by clason** [comment]
Ah, I see. If other commands behave like that, that would be a reasonable thing, yes.

**Comment by yochem** [comment]
Will do. I'll also keep the default `:60vnew` for now, then.

**Comment by clason** [comment]
I think changing that to just `:vnew` is fine, probably less surprising (although no personal preference either way).

**Comment by yochem** [comment]
Okay, away from Explore since that does not have much to do with it, but rather the `:new` command:

`:25new`:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23235841/225709077-2f2910e1-314f-4564-b854-fd6d06ff617b.png">


`:5new`:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23235841/225709148-cff5c5c6-f125-40c6-8572-147b8e9c451f.png">

It would make sense to me that if `:InspectTree` supports mods in front of it, that it would also support these counts, just like `:new` and `:vnew`, but also like other commands that open windows like `:Lexplore` and `:Sexplore` (the explore commands that open splits)

**Comment by gpanders** [comment]
Supporting a count modifier to specify width is a good idea so long as it's not too complex to implement (I don't believe it should be).

**Comment by clason** [comment]
My point:
1. `:10vnew InspectTree` -> supported
2. `:10InspectTree` -> no need to support

**Comment by yochem** [comment]
> My point:
> 
> 1. `:10vnew InspectTree` -> supported
> 2. `:10InspectTree` -> no need to support

But `:10vnew` is not a modifier, so that won't work (it creates a 10-width split with a file named 'InspectTree'), and modifiers can't take a range/count, so `:10vertical InspecTree` is also not possible. If you want to give a range/count, you have to do it like this: `:topleft 10InspectTree`

**Comment by clason** [comment]
(shows how often I use these features...)

**Comment by yochem** [comment]
I think this works like one would expect, while respecting the default value of `vim.treesitter.inspect_tree()` (which _will_ be `:60vnew`) when no mod or count given.

```lua
vim.api.nvim_create_user_command('MyInspectTree', function(cmd)
  if cmd.mods ~= '' or cmd.count ~= 0 then
    local count = cmd.count ~= 0 and cmd.count or ''
    local new = cmd.mods ~= '' and 'new' or 'vnew'

    vim.treesitter.inspect_tree({
      command = ('%s %s%s'):format(cmd.mods, count, new)
    })
  else
    vim.treesitter.inspect_tree()
  end
end, { count = true, desc = 'Inspect treesitter language tree for buffer' })
```

- `:InspectTree` --> `vim.treesitter.inspect_tree()`
- `:10InspectTree` --> `vim.treesitter.inspect_tree({command = '10vnew'})`
- `:topleft InspectTree` --> `vim.treesitter.inspect_tree({command = 'topleft new'})`
- `:topleft 10InspectTree` --> `vim.treesitter.inspect_tree({command = 'topleft 10new'})`
- `:vertical topleft InspectTree` --> `vim.treesitter.inspect_tree({command = 'vertical topleft new'})`

Notice how only providing a count still keeps **v**new, but providing a mod uses new (because then you can specify where the window will go using the mod). I think this implementation comes most close to what the user would expect to happen. Let me know what you think.
