### ISSUE TITLE
Home/End not functioning (Win7, VM: Centos 6.6)

### ISSUE THREAD

**Issue by mikeyjk** [neovim/neovim#2266]
Hey guys. So much love for all of you doing this.
I'm fairly addicted to vim.

I am having issues getting my home/end keys working in neovim though.
It works without issue in terminal / vi / vim. Just not nvim.
Issue #2028 seems likely to be related, but I don't know enough about the project to test this out. Was that fix Mac OS X only?

Top be more specific, the HOME/END keys don't move the cursor in any mode that I know of, as well as insert.

Kind regards.

    mikey  /var/www/case2224  brnch: case2244  nvim --version
    NVIM 0.0.0-alpha+201503261736 (compiled Mar 27 2015 08:41:48)
    Commit: c47e0d6210a82f3c2a88e2bc937e77f8b2a72b64
    Build type: Debug
    Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-  prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -  I/home/mikey/neovim/build/config -I/home/mikey/neovim/src -I/home/mikey/neovim/.deps/usr/include   -I/home/mikey/neovim/.deps/usr/include -I/home/mikey/neovim/.deps/usr/include/luajit-2.0 -I/home/mikey/neovim/.deps/usr/include -I/home/mikey/neovim/.deps/usr/include -I/home/mikey/neovim/.deps/usr/include -I/usr/include -I/home/mikey/neovim/build/src/nvim/auto -  I/home/mikey/neovim/build/include

    Optional features included (+) or not (-): +acl  +iconv
    For differences from Vim, see :help vim-differences

    system vimrc file: "$VIM/nvimrc"
    user vimrc file: "~/.nvimrc"
    2nd user vimrc file: "~/.nvim/nvimrc"
    user exrc file: "~/.exrc"
    fall-back for $VIM: "/usr/local/share/nvim"

    mikey  /var/www/case2224  brnch: case2244  infocmp $TERM
    #       Reconstructed via infocmp from file: /usr/share/terminfo/x/xterm-256color
    xterm-256color|xterm with 256 colors,
          am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
          colors#256, cols#80, it#8, lines#24, pairs#32767,
          acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
          bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
          clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
          csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
          cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
          cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
          cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
          dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K, el1=\E[1K,
          flash=\E[?5h$<100/>\E[?5l, home=\E[H, hpa=\E[%i%p1%dG,
          ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
          ind=^J, indn=\E[%p1%dS,
          initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%  {1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
          invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
          kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
          kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE,
          kbs=\177, kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC,
          kcuu1=\EOA, kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP,
          kf10=\E[21~, kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P,
          kf14=\E[1;2Q, kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~,
          kf18=\E[17;2~, kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~,
          kf21=\E[20;2~, kf22=\E[21;2~, kf23=\E[23;2~,
          kf24=\E[24;2~, kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R,
          kf28=\E[1;5S, kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~,
          kf31=\E[18;5~, kf32=\E[19;5~, kf33=\E[20;5~,
          kf34=\E[21;5~, kf35=\E[23;5~, kf36=\E[24;5~,
          kf37=\E[1;6P, kf38=\E[1;6Q, kf39=\E[1;6R, kf4=\EOS,
          kf40=\E[1;6S, kf41=\E[15;6~, kf42=\E[17;6~,
          kf43=\E[18;6~, kf44=\E[19;6~, kf45=\E[20;6~,
          kf46=\E[21;6~, kf47=\E[23;6~, kf48=\E[24;6~,
          kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q, kf51=\E[1;3R,
          kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
          kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
          kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
          kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
          kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
          kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
          kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
          memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
          rin=\E[%p1%dT, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
          rmir=\E[4l, rmkx=\E[?1l\E>, rmm=\E[?1034l, rmso=\E[27m,
          rmul=\E[24m, rs1=\Ec, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
          setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-  %d%e48;5;%p1%d%;m,
          setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
          sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
          sgr0=\E(B\E[m, smacs=\E(0, smam=\E[?7h, smcup=\E[?1049h,
          smir=\E[4h, smkx=\E[?1h\E=, smm=\E[?1034h, smso=\E[7m,
          smul=\E[4m, tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n,
          u8=\E[?1;2c, u9=\E[c, vpa=\E[%i%p1%dd,

    mikey  /var/www/case2224  brnch: case2244  cat /etc/*release*
    CentOS release 6.6 (Final)
    LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-  amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
    cat: /etc/lsb-release.d: Is a directory
    CentOS release 6.6 (Final)
    CentOS release 6.6 (Final)
    cpe:/o:centos:linux:6:GA
 
    Windows 7 Ultimate, Service Pack 1

**Comment by mikeyjk** [comment]
Okay so out of curiosity I have tested this with a gdb frontend (kdbg) on the centos machine.
It works in the debug output. Frustrating.

**Comment by mauke** [comment]
An `strace` log of neovim startup would be good.

**Comment by mikeyjk** [comment]
Thanks for the response! I've been a bit busy with easter/standard work stuff.
I'm reading about strace now.

**Comment by mikeyjk** [comment]
Hm I tried stepping through with gdb to find what is invoking those functions (indirectly I think? as the strace shows the system library calls?), but I was just stepping through a lot of C without a lot of context in os.c (or similar) and getchar.c. If anyone has any recommended reading that would be cool, otherwise I hope this helps.

**Comment by mauke** [comment]
I don't care about keypresses. I need a log of neovim starting up to see if/how this is related to libunibilium.

**Comment by mikeyjk** [comment]
strace -s300 -o blah.log nvim:
https://gist.githubusercontent.com/mikeyjk/e210cc4c50f7fa253c6f/raw/blah.log

I hope I have done this correctly. I couldn't paste the content here as it exceeds github's limit of 262144 characters.

**Comment by mauke** [comment]
Yes, thank you!
It's detecting your terminal as `xterm-256color` and finding the corresponding terminfo entry in `/usr/share/terminfo/x/`, so it doesn't look like the same issue as #2028 (that issue was caused by nvim not finding any terminfo entries at all).

Digging deeper, `/usr/share/terminfo/x/xterm-256color` says your home key sends `"\eOH"` and your end key sends `"\eOD"`. But your other trace shows they're actually sending `"\e[1~"` and `"\e[4~"`, respectively.

But wait! You said it doesn't work outside of X. So the question is, why does your configuration claim the terminal to be a (256 color) xterm when it isn't (you can't have xterm outside of X)?

New focus: In order for programs like nvim to work, the environment variable `TERM` (see `echo $TERM`) should reflect the terminal (emulator) you're in, e.g. in xterm it should say `xterm` (or a variant thereof), in screen/tmux it should say `screen`, no idea about putty, but in the linux console it should say `linux`. Are you overriding TERM somewhere?

(Another thing to try: At a linux text console (like `Ctrl`+`Alt`+`F1`) run `TERM=linux nvim` and see whether home/end keys work. If they do, `TERM` is definitely the issue.)

**Comment by mikeyjk** [comment]
Ahhhhhh. This is probably a self-created issue. How embarrassing. I'll check this later and post a confirmation. Thank you so much.

**Comment by tarruda** [comment]
@mauke great explanation, I will direct future $TERM related issues to your comment. Thanks.

**Comment by mikeyjk** [comment]
This is what I get for mindlessly using the same $TERM value irrespective of environment!
My .bashrc wasn't handling this correctly.
Setting: 
    TERM='putty-256color'
Resolved this issue.
Also good supplemental reading for noobs such as myself: http://vim.wikia.com/wiki/256_colors_in_vim

Closing as resolved :).
