### ISSUE TITLE
glob() does not list WSL directory (from nvim running in Windows)

### ISSUE THREAD

**Issue by gjm-p** [neovim/neovim#22661]
This was originally filed as an issue about viewing WSL directory contents using e.g. netrw. As the current issue title indicates, it looks as if the underlying problem is that `glob` doesn't (for me, at least) do the right thing on WSL directories. The original issue description is below, but here is a brief description of the `glob`-related misbehaviour.

I am running nvim 0.8.3 (the latest stable version, at the time of writing) on Windows 10 version 21H2. Much of my work happens inside WSL instances (WSL2 not WSL1, if that matters; the misbehaviour I originally observed seems to be exactly the same with both; I have done the testing I am about to describe only on WSL2).

If I launch nvim and do `:echo globpath('C:\Users\[my username]\[one of my directories]', '*')` then I see a list of the files and directories inside the directory I have passed to `globpath`. If I do `glob` instead of `globpath`, I see just that directory name. This is all as expected.

If instead I do `:echo globpath('\\wsl$\Ubuntu-20.04\home\gareth\[one of my directories]', '*')` then nothing is displayed. If I do `glob` instead of `globpath`, then again nothing is displayed. (`Ubuntu-20.04` is the name of one of my WSL2 instances. The directory name I'm passing in is the name of a directory therein, and it does contain files and directories.)

The files in my WSL2 instance are accessible to nvim in at least the following sense: if I do `:e \\wsl$\Ubuntu-20.04\home\gareth\path\to\a\file` then the file is opened correctly. And the directories there are enumerable in at least the following senses: (1) if I edit such a file with `autochdir` on and then do `:e <tab>`, I get offered an appropriate set of completions; (2) when I open one of these directories using the `nvim-tree` directory viewer (which fails to display any directory contents, as does netrw; this is the problem that first led me ton file this issue), `nvim-tree`'s logs show that it _is_ enumerating all the contents of the directory, even though it doesn't display them.

If I do the same things in plain old Vim, version 9.0, `globpath` and `glob` both behave as expected on WSL directories as well as on ordinary Windows directories, so this appears to be a divergence betwen Vim and nvim.

Original directory-viewer-focused issue report follows:

----

### Problem

I'm on Windows 10, using nvim 0.8.3, which right now is the latest stable version. Much of what I do happens inside WSL instances (WSL2 not WSL1, but the behaviour I am about to describe occurs with both). nvim-on-Windows can read and edit files in my WSL instances just fine, but when I :e a _directory_ rather than a _file_ I get a netrw directory listing _with no files or directories in it_. That is, the "header" at the top of the editor window is displayed as usual, including what looks like the right path, but in the place where a normal netrw directory listing shows the contents of the directory there is nothing.

I have tried doing the same thing with nvim-tree rather than vanilla netrw, and that fails in what looks like a possibly similar way; see https://github.com/nvim-tree/nvim-tree.lua/issues/2046 for details.

In original vim, I _don't_ see this behaviour; I get a netrw directory listing _with_ the directory contents shown as normal. Both nvim 0.8.3 and vim 9.0 say they are using netrw v171, so this seems unlikely to be a difference in netrw itself.

To reiterate a couple of things that are (perhaps informatively) _not_ broken: (1) There is no problem about actually editing files in the WSL filesystem. If there's a `foo.txt` in that directory and I do `:e \\wsl$\Ubuntu-20.04\home\gareth\foo.txt` then everything works as it should. (2) It's not that nvim categorically can't read the contents of the directory. For instance, if I have `autochdir` turned on then after `:e \\wsl$\Ubuntu-20.04\home\gareth` shows me a wrongly-empty directory listing I can do `:e <tab>` and I get the correct completions offered to me. (3) netrw works perfectly normally on directories in the ordinary Windows filesystem.

### Steps to reproduce

(prerequisite: have at least one WSL instance; mine is at `\\wsl$\Ubuntu-20.04\home\gareth`, and in that directory there are plenty of files and subdirectories)

1. Launch nvim.
2. `:e \\wsl$\Ubuntu-20.04\home\gareth`

### Expected behavior

Editor should show a netrw directory listing (it does) containing the files and directories in the requested directory (it doesn't).

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

no, vim 9.0 (2022 Jun 28)

### Operating system/version

Windows 10 21H2 19044.2604

### Terminal name/version

n/a, using nvim-qt

### $TERM environment variable

n/a, using nvim-qt

### Installation

nvim-win64.msi installer

**Comment by justinmk** [comment]
What is the exact result reported by `echo expand('%:p')` when viewing the directory? I wonder if it's related to slashes.

Does it work with another dir listing plugin, e.g. https://github.com/justinmk/vim-dirvish ?

**Comment by justinmk** [comment]
> its maintainer reckons this is an nvim issue

yes, trying to determine if this is related to mismatched slashes in the full path, e.g.:

    \\wsl$\Ubuntu-20.04/home/gareth

just for reference, with Nvim (not Vim),

- does this list the directory contents?
  ```
  :echo globpath('\\wsl$\Ubuntu-20.04\home\gareth', '*')
  ```
- can you list the exact (Nvim) results of:
  ```
  :echo fnamemodify('\\wsl$\Ubuntu-20.04\home\gareth', '%:p')
  :echo resolve('\\wsl$\Ubuntu-20.04\home\gareth')
  ```

**Comment by gjm-p** [comment]
`:echo globpath('\\wsl$\Ubuntu-20.04\home\gareth', '*')` produces no output. A similar command with an ordinary Windows filesystem directory path _does_ produce a listing of the directory's contents. (I know you didn't ask, but the same thing in original-Vim with a WSL path _does_ list the directory's contents. For the avoidance of doubt, I'm describing what original-Vim does not because I don't understand the difference nor because I want to make you feel bad about Nvim's behaviour, but just because it feels like it might help with tracking down what's amiss.)

`fnamemodify('\\wsl$\Ubuntu-20.04\home\gareth', '%:p') returns `\\wsl$\Ubuntu-20.04\home\gareth` (i.e., its first argument, apparently unmodified). `resolve` likewise returns its first argument, apparently unmodified, in this situation.

I don't know whether any of this is useful, but: these two things show the same return-first-argument behaviour with (1) ordinary Windows filesystem paths, (2) _nonexistent_ WSL paths, and (3) real WSL paths with forward-slashes in place of the backward-slashes.

The pathname displayed in the "netrw directory listing" always uses forward slashes everywhere, regardless of whether the path I provide to `:e` uses all-/, all-\, or a mix of the two.

**Comment by justinmk** [comment]
> `:echo globpath('\\wsl$\Ubuntu-20.04\home\gareth', '*')` produces no output.

ok that might be the problem :)

**Comment by matveyt** [comment]
>The weird thing is that in other contexts nvim is clearly perfectly well able to enumerate what's in that directory.

Because the bug is about `glob()` function specifically. In Vim/Nvim `glob()` doesn't simply return file list unmodified, but it also performs some other actions, like sorting etc. If you take any other file manager that uses internally, say, `readdir()` but not `glob()`, it will work okay with WSL paths.

The weird thing here is that `glob()` got bugged due to some of Nvim patches. While in Vim `glob()` still works okay.

**Comment by ateoi** [comment]
The issue is caused because Neovim considers '$' as a wildcard. Removing '$' from the line below fixes this issue:

https://github.com/neovim/neovim/blob/339011f59c25937567f1e88d663c22dade5e217a/src/nvim/path.c#L652

It works in Vim because $ is not considered a wildcard for `globpath`. And wildcards in Vim are OS dependent:

https://github.com/vim/vim/blob/bfc7cbd1d44e53e844a079d8ad16ae990dad664d/src/os_mswin.c#L709-L718

https://github.com/vim/vim/blob/bfc7cbd1d44e53e844a079d8ad16ae990dad664d/src/os_unix.c#L7126-L7143

**Comment by gjm-p** [comment]
Interesting! In case anyone else with the same problem as I had reads this before any fix is built into an actual Neovim release, note that this means you can avoid the problem by using `\\wsl.localhost\...` instead of `\\wsl$\...`; for instance, if I enter the path to one of my WSL directories that way then netrw works fine with it.
