### ISSUE TITLE
docs?: terminalscrollback is global option, not buffer local one

### ISSUE THREAD

**Issue by matu3ba** [neovim/neovim#22660]
### Problem

:h scrollback documents:
```
						*'scrollback'* *'scbk'*
'scrollback' 'scbk'	number	(default: 10000)
			local to buffer
	Maximum number of lines kept beyond the visible screen. Lines at the
	top are deleted if new lines exceed this limit.
	Minimum is 1, maximum is 100000.
	Only in |terminal| buffers.
```

However, in `min.lua`:
```lua
  vim.o.scrollback = 100000 -- works
```
and
```lua
  vim.bo.scrollback = 100000 -- does not work
```
With min.vim it works via
```vim
set scrollback = 100000
```

### Steps to reproduce

nvim -u min.lua
nvim -u min.vim
executing err.sh within :terminal spawned terminal:
```sh
#!/usr/bin/env sh

i=1; while [ ${i} -le 100000 ]; do
  echo ${i}
  i=$(( i + 1 ))
done
```

### Expected behavior

Either docs must be updated or wrong behavior must be fixed.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1219+g773febc46

### Vim (not Nvim) behaves the same?

vim has no lua

### Operating system/version

Linux

### Terminal name/version

Windows terminal

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
You didn't set the buffer-local value in a terminal buffer.

**Comment by matu3ba** [comment]
> You didn't set the buffer-local value in the terminal buffer.

Ah, this is interesting behavior and I have no idea why it was designed to be different than regular buffers https://vi.stackexchange.com/questions/36575/how-to-configure-options-in-terminal-neovim.

**Comment by zeertzjq** [comment]
This is how buffer-local options work.
