### ISSUE TITLE
`treesitter` and `lsp` health checks failing

### ISSUE THREAD

**Issue by teddylear** [neovim/neovim#22672]
### Problem

When running `:checkhealth` both `treesitter` and `lsp` are failing with below errors, while `nvim-treesitter`, `vim-lsp`, and `vim-treesitter` are working fine. Also, lsp and treesitter are working as expected for me. So I'm not sure why these are failing or where they are coming from. *NOTE*: I do have an `lsp.lua` and a `treesitter.lua` file in my `after/plugin` directory for their configurations, not sure if that's an issue. If this is something else on my local system, is there an easy way to determine where this is coming from? I would be more than happy to add to the docs if so in case someone else runs into a similar issue. If you need anymore information please let me know. 

Please ignore line numbers
```
  2   ──────────────────────────────────────────────────────────────────────────────
    1 lsp: health#lsp#check
    2
    3 - ERROR Failed to run healthcheck for "lsp" plugin. Exception:
    4   function health#check[25]..health#lsp#check, line 2
    5   Vim(lua):E5108: Error executing lua [string ":lua"]:1: attempt to call field 'check_health' (a nil value)
    6   stack traceback:
    7   [string ":lua"]:1: in main chunk
    8
    9 ──────────────────────────────────────────────────────────────────────────────
   10 treesitter: health#treesitter#check
   11
   12 - ERROR Failed to run healthcheck for "treesitter" plugin. Exception:
   13   function health#check[25]..health#treesitter#check, line 2
   14   Vim(lua):E5108: Error executing lua [string ":lua"]:1: attempt to call field 'check_health' (a nil value)
   15   stack traceback:
   16   [string ":lua"]:1: in main chunk
   17
```

### Steps to reproduce

`:checkhealth treesitter lsp`

### Expected behavior

Health checks pass as both appear to be healthy when using neovim

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1230+gd1e0f7454

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu MATE 22.04.2 LTS x86_64

### Terminal name/version

Alacritty

### $TERM environment variable

screen-256color

### Installation

Build from repo

**Comment by clason** [comment]
Make sure to clean out the runtime directory (`/usr/local/share/nvim/runtime`) before  `make install`, as _uninstall_ files that were removed.

**Comment by teddylear** [comment]
@clason That did the trick thanks! I'll add that to my script prior to new neovim installs.

**Comment by justinmk** [comment]
`:che nvim` checks for this kind of thing: https://github.com/neovim/neovim/blob/d1e0f7454b5fc61d26db5af5ce00c1894e7c49fc/runtime/lua/nvim/health.lua#L22-L30
