### ISSUE TITLE
`nvim_buf_set_lines` does not (fully) load buffer given by `bufnr(..., true)`

### ISSUE THREAD

**Issue by Jlll1** [neovim/neovim#22670]
### Problem

I'm trying to edit a file that might or might not be opened as a buffer, using `nvim_buf_set_lines`. Unfortunately, unless the buffer is visible in a window, it seems that `nvim_buf_set_lines` will only set the first line, instead of the range provided.
This might be related to [#8659](https://github.com/neovim/neovim/issues/8659), although the test circumstances are slightly different.

### Steps to reproduce

`printf "a\nb\nc" > testfile`
`nvim --clean`
`:lua vim.api.nvim_buf_set_lines(vim.fn.bufnr("testfile", true), 0, 4, false, {})`
`:e testfile` - You will see that only the first line was cleared

### Expected behavior

`nvim_buf_set_lines` should set the lines specified in the range even for buffers that are not opened in a window.
The command above should've cleared the whole file.

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

N/A - Lua API

### Operating system/version

Artix Linux 6.1.12

### Terminal name/version

Alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

Pacman

**Comment by justinmk** [comment]
Specifically this looks related to the `create` parameter of bufnr: 

    bufnr([{buf} [, {create}]]) 

There might be an order-of-operations issue, but probably same general issue as https://github.com/neovim/neovim/issues/8659 : `nvim_buf_set_lines` and similar APIs should probably actively load buffers (or at least raise an error) if needed.
