### ISSUE TITLE
api: `nvim_get_hl`

### ISSUE THREAD

**Issue by clason** [neovim/neovim#22679]
### Problem

No easy way to get a table of all current highlight groups in a machine readable format (i.e. in a form that can be directly fed to `nvim_set_hl`). This is useful for storing, manipulating, and restoring colorschemes.

We already have `nvim_get_hl` at home: `nvim__get_hl_defs`, but that
1. only works for `ns = 0`
2. contains undefined groups (e.g., the language-specific treesitter and lsp semantic groups that are autocreated) with the cryptic field `[true] = 6`
3. shows colors in decimal instead of (optionally) RGB hex representation.

### Expected behavior

Having `nvim_get_hl(ns, opts)` where `opts` supports at least `rgb=true` and `undefined=false`. The `opts` dict could also contain `id` and `name` filters, which would allow deprecating `nvim_get_hl_by_id` and `nvim_get_hl_by_name`.

### Alternative

Create this in Lua under `vim.highlight.get_groups`?

**Comment by nullchilly** [comment]
FWIW using `nvim__get_hl_defs(0)`, I wrote a simple script [colorcache.lua](https://github.com/nullchilly/colorcache.nvim/blob/main/plugin/colorcache.lua) that automatically create `${colorscheme}_cached` for the given `colorscheme`, here is the result:

![image](https://user-images.githubusercontent.com/56817415/225405018-38c29e10-e22d-484d-ae0e-b381b5af7c2b.png)

However these also contains the "redundant" highlight groups that wasn't set by colorscheme, `NvimInvalidDivision`, `RedrawDebugNormal` to name a few, which is well over 200 highlight groups

I can do something like this but should we handle this by default?

```lua
local groups = vim.api.nvim__get_hl_defs(0)
vim.cmd [[hi clear]]
local default_groups = vim.api.nvim__get_hl_defs(0)
for group, color in pairs(groups) do
	if not color == default_groups[group] and not color[true] then
		table.insert(lines, string.format([[vim.api.nvim_set_hl(0, "%s", %s)]], group, vim.inspect(color)))
	end
end
```

**Comment by echasnovski** [comment]
> I can do something like this but should we handle this by default?

I can see a value in "Get **all** currently defined highlight group". Maybe under a `compress` option?

Also, this script requires redoing all current highlight groups, which can have problems now. For example, preserving `ctermbg`/`ctermfg`.

That is why I think output of `nvim_get_hl()` for a single highlight group should contain **all** information about that highlight group. In other words, executing the following code should not change current highlight groups:
```lua
local hl_groups = vim.api.nvim_get_hl(0)
for name, spec in pairs(hl_groups) do
  vim.api.nvim_set_hl(0, name, spec)
end
```

**Comment by nullchilly** [comment]
> In other words, executing the following code should not change current highlight groups:

I can see your point about **all** highlight groups, but neovim set those default highlights regardless if you define them or not

**Comment by clason** [comment]
That is why my proposal explicitly mentions having an option for this. If all we're discussing here is what the default value should be, better save that for the PR.

**Comment by clason** [comment]
(and as @echasnovski wrote, the point here is not performance -- that should be handled by the user if they need it -- but being able to save and restore completely the current color definitions.)

**Comment by echasnovski** [comment]
> That is why my proposal explicitly mentions having an option for this. If all we're discussing here is what the default value should be, better save that for the PR.

I don't see this as an option in initial comment... 

> In the script I mentioned above, `:colorscheme catpuccin` and `:colorscheme catppuccin_cache` has the same `vim.api.nvim__get_hl_defs(0)` output.

That both because Catppuccin doesn't use `ctermfg`/`ctermbg` and `nvim__get_hl_defs(0)` doesn't return them.

@clason, do you mind sharing some light about why `rgb=true` is needed?

Can I suggest something like the following.

```lua
vim.cmd('hi AAA guifg=#AAAAAA ctermfg=248 gui=bold,italic')
print(vim.inspect(vim.api.nvim_get_hl(0, 'AAA', {})))
-- {
--   bold = true,
--   ctermfg = 248,
--   foreground = "#AAAAAA",
--   italic = true,
-- }
```

**Comment by clason** [comment]
I thought we were discussing skipping the "empty" highlight groups; that's what I was referring to.

RGB may not be needed if everything nvim__get_hl_defs is used for can handle them. (The point is to graduate and consolidate functions, not add more of them...)
