### ISSUE TITLE
[filetype] Racket files are detected as Scheme, even though vim/neovim support ft=racket out of the box

### ISSUE THREAD

**Issue by kakig** [neovim/neovim#22685]
### Problem

Similar to #18258, but without using any plugins. When opening a file with a .rkt extension, its file type is detected to be Scheme instead of Racket. See https://github.com/neovim/neovim/blob/320cb344c14b30f8c1aa8c2d86803e4c2f971ae9/runtime/lua/vim/filetype.lua#L911.

I filed an issue against vim https://github.com/vim/vim/issues/12162, but I'm filing this here as well because neovim changed the vim filetype detection to be done in lua.

### Steps to reproduce

nvim --clean
:edit test.rkt
set ft?

### Expected behavior

filetype=racket

### Neovim version (nvim -v)

0.9.0 commit g320cb344c1

### Vim (not Nvim) behaves the same?

yes, 9.0.1337

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

Arch User Repository (AUR)

**Comment by clason** [comment]
The filetype detection logic is determined by Vim, so please wait how your upstream issue is resolved. If any changes are made, we will port them as a matter of fact; if upstream declares this as "won't fix", then we won't make any changes either since alignment with Vim is very important for us.
