### ISSUE TITLE
statusline doesn't update to recording state change

### ISSUE THREAD

**Issue by A-Lamia** [neovim/neovim#22683]
### Problem

`vim.fn.reg_recording()` seems to have gotten an issue some time ago where you now need to press a key after initiating and ending a recording to output and clear, this wasn't the case some time ago and still works fine on Neovim V0.8.3, this could have something to do with the `RecordingEnter` and `RecordingLeave` event.

### Steps to reproduce

output `vim.fn.reg_recording()` to you statusline.

### Expected behavior

Instant output when key is pressed to initiate macro recording and then stopped.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1230+gd1e0f7454

### Vim (not Nvim) behaves the same?

no

### Operating system/version

windows 10

### Terminal name/version

Neovide

### $TERM environment variable

xterm-256color

### Installation

scoop

**Comment by zeertzjq** [comment]
Maybe another solution is to redraw the statusline every x milliseconds using a timer.

**Comment by bfredl** [comment]
The intended way to solve problems like this is to set `curwin->w_redr_status` explicitly when the statusline might need to be updated, even internally.  the point of #22547 and #22590 was not that the statusline should not be redrawn to internal events, just that this cannot be done by assuming the statusline on _every single_ event loop tick.

Doing this upon starting and stopping recording sounds like a reasonable builtin behavior. to me it is comparable to entering a (sub-)state, where we _do_ redraw the statusline.

**Comment by luukvbaal** [comment]
> Doing this upon starting and stopping recording sounds like a reasonable builtin behavior.

So do we just store and add `reg_recording` to the list of variables checked in `show_cursor_info_later()`? I could make a PR.
