### ISSUE TITLE
dist: drop .deb, deprecate .tar.gz

### ISSUE THREAD

**Issue by clason** [neovim/neovim#22684]
### Problem

Linux releases come in too many flavors: appimage, `tar.gz` archive, `deb` package. This is confusing and a waste of resources.

### Expected behavior

Only provide a single release format: **appimage**, which is the "blessed" format that Just Works™️ but can also be extracted locally.

As `tar.gz` is used by many downstream projects for their CI, we should leave it for now but make clear that it's only provided for that purpose and that end users are strongly encouraged to use the appimage. Also push downstream to switch to appimages instead so we can remove that for 0.10.

### Plan

1. Drop the `.deb` for the 0.9 release
2. Drop the `.tar` release for nightlies sometime during 0.10

This means that 
* 0.9 will only release as `.appimage` and `.tar`
* 0.10 will release only as `.appimage`
* nightlies will drop `.deb` after 0.9, and `.tar` some time after that (with a longer announcement period).

**Comment by dundargoc** [comment]
I like @glacambre 's suggestion: rename the deb and tar files to `nvim-linux64-deprecated.<extension>` and give it x amounts of time before yeeting it.

**Comment by clason** [comment]
Well, even renaming will instantly break CI, so it's not really a deprecation. And if you manually need to change things, you might as well change them properly. This only encourages bandaid fixes and later complaints.

**Comment by glacambre** [comment]
>if you manually need to change things, you might as well change them properly

You might not have time to change them properly the minute you discover something is breaking though. Renaming the tar is the quick and easy fix you do until you have the time to implement a proper solution.

**Comment by clason** [comment]
The idea would be to provide a snippet you can paste into your action in replacement of `tar -zxf nvim-linux64.tar.gz`... (And nobody should be using the `.deb`.)

To be clear, I'm talking here _only_ of dropping the `.deb`, for now -- the `tar.gz` will stay at least until 0.10 to allow people to switch over. If there's extensive use of the `.deb` in downstream CI, I'd be interested in learning about that.

**Comment by justinmk** [comment]
Example of `.deb` not interacting correctly with apt-installed Nvim: https://github.com/neovim/neovim/issues/22731

**Comment by clason** [comment]
Courtesy of @folke, here's how you can use the appimage in GHA if you need to have `nvim` "installed" (i.e., on your `$PATH`):
```
      - name: Install Neovim
        shell: bash
        run: |
          mkdir -p /tmp/nvim
          wget -q https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage -O /tmp/nvim/nvim.appimage
          cd /tmp/nvim
          chmod a+x ./nvim.appimage
          ./nvim.appimage --appimage-extract
          echo "/tmp/nvim/squashfs-root/usr/bin/" >> $GITHUB_PATH

```

**Comment by to-json** [comment]
fwiw arch quietly depends on the tarball; nix and rpm based distros appear to repackage from sourcetree and it's too early for me to go deep in what the hell debian is doing but at a brief skim it seems that they are also quietly using the tarball despite the provided deb: https://tracker.debian.org/pkg/neovim

the tarball is a nice touch, and if it needs a maintainer somehow (after a brief skim, it seems pretty straightforward) I'd be down, rather than bone the build pipelines for multiple distros

**Comment by clason** [comment]
Thanks for the offer, but the plan is definitely to reduce the options to just one -- and that is the appimage as 1. being the least footgunny and 2. being able to replace the other two use cases fully.

**Comment by to-json** [comment]
mybad, that is rather likely; thanks for the clarification!

**Comment by dundargoc** [comment]
> Example of `.deb` not interacting correctly with apt-installed Nvim: https://github.com/neovim/neovim/issues/22731

Anither one: https://github.com/neovim/neovim/issues/21261

**Comment by rockneverdies55** [comment]
I got used to the convenience of downloading the deb file, running "sudo dpkg -i nvim.deb" ... and being on the latest release in less than a minute :disappointed:

**Comment by clason** [comment]
Just download the appimage now and link it to your PATH, then you can just overwrite the file and you are on the latest release in seconds.

**Comment by opdecirkel** [comment]
Appimage is not universally accepted. Now, Folks that can not or don't want to use appimage, they have build from source them self. ... I am wondering, by how much the world's carbon footprint would increase because of this decision

**Comment by clason** [comment]
@dundargoc note to us: we should replace `rhysd/action-setup-vim` in our scripts (api-docs, lintcommit) with manually installing our own appimage. More robust, more control, and no point in requiring an external script for installing our own app.

**Comment by glacambre** [comment]
@clason 
>More robust

In my experience, rhysd/action-setup-vim has been much more robust than any other installation method thanks to its ability to fall back to building Neovim when a nightly/release build is not available (due to e.g. Github problems or build issues that existed when the neovim nightlies are built but were fixed during the  day).

Can't argue about the other points though :).

**Comment by cizordj** [comment]
Since the _.deb_ package has been removed, are we all supposed to use appimage instead? I know it's a dumb question but still... I used to use this repo to get the latest neovim for debian because of its debian package.

**Comment by to-json** [comment]
It seems the goal was to stop needing to support users of the debian
package, because it was inclined to be messy.

If people want a basically completely unsupported package with absolutely,
positively, incontrovertibly -zero- support, I might could be convinced to
set that up. I'll play with the idea, but, tbc, I will have nothing for you
if it sucks or eats your computer

**Comment by clason** [comment]
> Since the _.deb_ package has been removed, are we all supposed to use appimage instead?

Yes, that is exactly the idea. It's self-contained and runs on the widest possible selection of platforms (not tied to a specific distro).

> I know it's a dumb question but still... I used to use this repo to get the latest neovim for debian because of its debian package.

But Debian packages are the Debian maintainers' job; the Neovim project is not in the business of maintaining distro packages. (The `.deb` was never deliberately added; it kinda snuck in as part of a packaging infrastructure improvement to show that it's possible.)

**Comment by folke** [comment]
A great alternative to using the appimage is to use [bob](https://github.com/MordechaiHadad/bob) instead. With bob it's very easy to always use the latest nightly and you can even use different Neovim versions next to each other.

**Comment by dundargoc** [comment]
I managed to convince the neovim team to not remove the tar.gz, for now at least. That means the tar.gz will *not* be removed for version 0.10. Afterwards I cannot guarantee anything, and I wouldn't be shocked if this issue resurfaces in the future, so I'd probably rely on the appimage if possible just to be safe. The .deb however will not be making a comeback and that is final. Thank you.

**Comment by clason** [comment]
## Resolution

The `.tar.gz` is now created as part of the appimage workflow (hence no longer a separate release), so it will continue to be supported. (Thanks, @dundargoc!)

The `.deb` will **not** come back, as distro-specific packaging formats are the responsibility of distribution maintainers.
