### ISSUE TITLE
random segmentation fault with luv library

### ISSUE THREAD

**Issue by pigeonchk** [neovim/neovim#22694]
### Problem

Neovim segfaults irregularly during normal operation. May take hours after starting up, or a few seconds.

Backtrace was generated according to [FAQ#backtrace-linux](https://github.com/neovim/neovim/wiki/FAQ#backtrace-linux).

pastebin: https://pastebin.com/v3nnfHDQ

### Steps to reproduce

No specific step. Simply start the editor and it will crash anytime.

### Expected behavior

Not crash randomly.

### Neovim version (nvim -v)

0.8.3 Release

### Vim (not Nvim) behaves the same?

N/A - Lua API

### Operating system/version

Fedora Linux 36 (x86-64) Kernel 6.1.14-100.fc36.x86_64

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Installation

system package manager

**Comment by clason** [comment]
First step is to download one of the releases from our GitHub page to make sure it's not a problem with whatever libluv/luv version your distro decided to install.

**Comment by pigeonchk** [comment]
Understood. I'm going to test the release right now. Should have the result by tonight.

**Comment by bfredl** [comment]
The crash seems to be related to the creation of a luv thread. such a thing is caused by some lua plugin which invokes `vim.loop.new_thread`. perhaps you could identify which plugin this is?

**Comment by pigeonchk** [comment]
I've been using the downloaded binary and did not report any crash. It seems the crash is indeed related to the luv supplied by Fedora.

@bfredl I'll try to identify the plugin. Though, the irregularity of the crash will prove it to be difficult.

**Comment by erw7** [comment]
This seems to be a bug in `luv` or the `plugin`. In the code below, the argument to `uv_thread_create_ex` or `uv_thread_create` is passed a pointer to memory allocated by `lua_newuserdata`, but it is not guaranteed that this memory has not already been freed in the main thread when used by `luv_thread_cb`. I don't know if it is a limitation or a bug in `luv` that the `luv_thread_t userdata` returned by `luv.new_thread` must be held until the entry function exits.

https://github.com/luvit/luv/blob/5e1af2f0a273d79a947e5ef069c1e5d77b135f34/src/thread.c#L327-L345

I can't make an example that crashes successfully, but you should be able to observe that the thread entry function may not be executed because `thd->code` is released by `luv_thread_gc` in the following steps.

```vim
nvim -u NORC
:lua local thread=vim.loop.new_thread(function(arg) print(arg) end, "abc") thread=nil collectgarbage('collect')
```

**Comment by PantomInach** [comment]
> I've been using the downloaded binary and did not report any crash. It seems the crash is indeed related to the luv library supplied by Fedora.
> 
> @bfredl I'll try to identify the plugin. Though, the irregularity of the crash will prove it to be difficult.

I also stumbled upon this issue on Void Linux. Therefore, this issue is also present in the Void Linux libraries.

**Comment by erw7** [comment]
The behavior of luv that causes this issue has been documented as a limitation of luv(luvit/luv/pull/639). So it's a problem with plugins that use it that way.

> I'll try to identify the plugin. Though, the irregularity of the crash will prove it to be difficult.

You should be able to find it easily by searching for &rtp in new_thread.

**Comment by bfredl** [comment]
So what a plugin actually needs to do is saving the return value of `uv.new_thread()` into a variable?

**Comment by bfredl** [comment]
@zhaozg Is this meant to imply that `code` needs to be preserved **in addition** to the `thread` object? This definitely sounds like a bug in libluv. At least, this is *not* being clarified in the documentation update https://github.com/luvit/luv/pull/639.

All this hassle for every plugin using `luv.new_thread` is not worth avoiding libluv simply making a copy of the bytes in the `code` object and then freeing it after loading it in the new thread IMHO.

**Comment by zhaozg** [comment]
> Is this meant to imply that code needs to be preserved in addition to the thread object? 

Just need keep `thread`, __gc it when thread after. `code` can release after used.

> This definitely sounds like a bug in libluv. At least, this is not being clarified in the documentation update.

Yes.

**Comment by zhaozg** [comment]
I made a PR https://github.com/luvit/luv/pull/640 to fix the issue.

The simple test code should be pass.

```lua
local uv = require('luv')
uv.new_thread(function(...)
    print(...)
    print('DONE')
  end, 'hello', 'world')
collectgarbage('collect')
collectgarbage('collect')
uv.run()
collectgarbage('collect')
```
