### ISSUE TITLE
Wordwise jump does not work in terminal mode

### ISSUE THREAD

**Issue by Tranquility** [neovim/neovim#2269]
When I press <kbd>alt-b</kbd> or <kbd>alt-f</kbd> it should jump wordwise but it print chars like these instead: ââââææææ

**Comment by Grimy** [comment]
This might be related to #2254 (<C-Left> and <C-Right> are also used for wordwise jump).

**Comment by justinmk** [comment]
Merging into https://github.com/neovim/neovim/issues/2440

**Comment by khughitt** [comment]
I'm still having problems with C-left & C-right in the terminal for a recent nightly of Neovim (NVIM v0.1.3-350-gc94575f) running in urxvt.

All of the relevant issues appear to be closed. Should this be working now?

**Comment by justinmk** [comment]
@khughitt ctrl-left and ctrl-right are not send to terminal programs (unless you configure your terminal to send custom sequences which you then explicitly map to some psuedo-key in Vim/Neovim). What behavior are you expecting?

**Comment by khughitt** [comment]
@justinmk 

I have the following mappings in my `~/.Xresources`:

```
URxvt.keysym.Control-Up:    \033[1;5A
URxvt.keysym.Control-Down:  \033[1;5B
URxvt.keysym.Control-Left:  \033[1;5D
URxvt.keysym.Control-Right: \033[1;5C
```

The left and right mappings make it possible to use c-left and c-right to navigate by words in the terminal. Ideally, I could use the same familiar keystrokes to jump around words in the Neovim terminal.

**Comment by justinmk** [comment]
Install RSI.vim

**Comment by justinmk** [comment]
@khughitt Did you have any success with my last comment?

**Comment by khughitt** [comment]
@justinmk I just tried it out now and that did the trick!

So, `\033[1;5D` and `\033[1;5C` are actually just "Control + left" and "Control + right", respectively.
Using `Control + v` to print the meta-characters for those keystrokes on both vim and rxvt show almost exactly that, e.g. `^[[1;5D`.

Neovim kindly translates this, and displays `Control-left` and `Control-right` when using Control + v for the same keystrokes.

Adding:

```
tnoremap <C-Left> <m-b>
tnoremap <C-Right> <m-f>
```

to my init.vim was was enough to add support to the terminal.

Thanks for the help!
