### ISSUE TITLE
nnoremap is not working as expected

### ISSUE THREAD

**Issue by tribela** [neovim/neovim#22697]
### Problem

I use `nnoremap <space><space> i_<esc>r` to insert one character. But since I updated neovim, It is not working as expected

### Steps to reproduce

nvim --clean
`:nnoremap <space><space> i_<esc>r`

Press space bar twice to invoke nnoremap

### Expected behavior

As described, Insert `_` character and waiting for replacing one character. So press `<space><space>1` will insert `1` on the cursor.
But neovim behaves differently, Not waiting for replacing. Just `_` character is inserted and go to normal mode.

### Neovim version (nvim -v)

0.9.0-dev

### Vim (not Nvim) behaves the same?

No, Vim works fine 8.2.4919

### Operating system/version

Ubuntu 22.04.2 LTS

### Terminal name/version

gnome-terminal 3.44.0

### $TERM environment variable

xterm-256color

### Installation

neovim-ppa/unstable

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by zeertzjq** [comment]
Can you find out which exact commit you are on, or test using [appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage)?

**Comment by tribela** [comment]
Oh, it seems fixed on neovim/jammy 0.9.0~ubuntu1+git202303161835-995196c61-333b5866f-46982e66d~ubuntu22.04.1
I was using 0.9.0~ubuntu1+git202303141837-d1e0f7454-333b5866f-0e6529498~ubuntu22.04.1

**Comment by tribela** [comment]
This problem seems causes again on nvim v0.9.0 and 0.10.0~ubuntu1+git202304192018-706f87101-9b397864c-e25da9562~ubuntu22.04.1

**Comment by zeertzjq** [comment]
Still cannot reproduce. Does it work in some other terminal emulator?

**Comment by tribela** [comment]
Ahh.. I found the problem. it is not nvim's bug
https://github.com/hrsh7th/cmp-buffer/issues/64
If one of these plugin enabled, the problem happens

-  Plug 'hrsh7th/cmp-buffer'
-  Plug 'hrsh7th/cmp-path'
-  Plug 'hrsh7th/cmp-cmdline'
