### ISSUE TITLE
New IDE for

### ISSUE THREAD

**Issue by pullelikunju** [neovim/neovim#22708]
### Problem

Hello community,

I have build an IDE for neovim to make it more mouse friendly. It is similar in features as Atom. Please let me know how to include it as a plugin with next neovim release. Also report any changes fixes would make it more new user friendly.

Here is the repo to the new IDE plugin: https://github.com/pullelikunju/ide

Pulleli

### Expected behavior

*

**Comment by clason** [comment]
That looks nice, but we won't include any user configuration in Neovim -- this is best left to external  plugins, so users can choose among the many (many!) such "IDEs" that exist.
