### ISSUE TITLE
vim-patch: Don't distinguish between applied and NA patches?

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2271]
My line of thought is this: If a patch is not applicable to Neovim, we didn't have the problem the patch fixes in the first place and should already behave "correctly" (whatever that means). So `has('patchXXX')` should return `1` (?), therefore we need to uncomment the version number in `version.c`. We could still have `// NA` as a trailing comment to this version number to distinguish between patches that involved actual code changes and "implicit" patches.

Additionally, we probably applied some patches in parts of the code that were later removed (e.g. by #1820). To be consistent, these patches would now have to be marked `NA` in `version.c`.

**Comment by Pyrohh** [comment]
> So has('patchXXX') should return 1 (?)

Would this cause breakage if the behavior introduced by a patch isn't present in nvim, but `has('patchXXX')` still returned one for it?

**Comment by justinmk** [comment]
This was discussed early in the project, and @jamessan brought up some good points that convinced me to distinguish between "applied" and "N/A": https://github.com/neovim/neovim/pull/445#discussion_r11172532

What are your thoughts on that discussion?

> Additionally, we probably applied some patches in parts of the code that were later removed (e.g. by #1820). To be consistent, these patches would now have to be marked NA

Eek... you're probably right, but I'm ok with a "best effort" approach. It could be very cumbersome to audit that.
