### ISSUE TITLE
FORTIFY_SOURCE=3 overflow when searching help manual

### ISSUE THREAD

**Issue by iteemhe** [neovim/neovim#22718]
### Problem

After typing `:h` and a Tab, NeoVim causes overflow, and crashes.

### Steps to reproduce

0. Compile with overflow protection.
1. `nvim --clean`
2. `:h <Space> <Tab>`
3. `*** overflow detected ***: terminated`

### Expected behavior

Shouldn't crash

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1244+gc6f8af36e1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Archlinux

### Terminal name/version

Xfce Terminal

### $TERM environment variable

xterm-256color

### Installation

AUR

**Comment by zeertzjq** [comment]
What compile flags did you use?

**Comment by iteemhe** [comment]
```bash
CFLAGS="-flto=thin -fuse-ld=mold -march=native -fno-plt -fstack-clash-protection -fstack-protector-all -fcf-protection=full -fsanitize=shadow-call-stack -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=3 -pipe -Wno-macro-redefined"
```

**Comment by dundargoc** [comment]
Gee, I wonder if the "overflow" is caused by -DFORTIFY_SOURCE=3

See also https://github.com/neovim/neovim/issues/223

Can you try without -DFORTIFY_SOURCE=3?

**Comment by iteemhe** [comment]
> Gee, I wonder if the "overflow" is caused by -D_FORTIFY_SOURCE=3
> 
> See also #223
> 
> Can you try without -DFORTIFY_SOURCE=3?

Yes, problem solved after removing `-D FORTIFY_SOURCE=3`. And valgrind does not report an error on overflow.

**Comment by dundargoc** [comment]
-D_FORTIFY_SOURCE triggers on false positives. The problem with errors on -D_FORTIFY_SOURCE=2 is that it's the default on gcc on some build types, which required obscene workarounds, which is why it needed to be fixed. 

-D_FORTIFY_SOURCE=3 is added on your own volition, which makes this not nearly as crucial to fix. I guess it won't hurt to find a fix for for this even if it's a false positive.

**Comment by justinmk** [comment]
Should we not restore the cmake code that forces an "acceptable fortify": https://github.com/neovim/neovim/commit/ebd2372f928c6f1cfe823d36aabf479f6930232f#diff-1f1596d636df8da9babb14a7e4f135458df238e66dcccb4bee2a002eda13ac68L237-L241

```
if(NOT HAS_ACCEPTABLE_FORTIFY)
  message(STATUS "Unsupported _FORTIFY_SOURCE found, forcing _FORTIFY_SOURCE=1")
  # Extract possible prefix to _FORTIFY_SOURCE (e.g. -Wp,-D_FORTIFY_SOURCE).
  string(REGEX MATCH "[^\ ]+-D_FORTIFY_SOURCE" _FORTIFY_SOURCE_PREFIX "${CMAKE_C_FLAGS}")
  string(REPLACE "-D_FORTIFY_SOURCE" "" _FORTIFY_SOURCE_PREFIX "${_FORTIFY_SOURCE_PREFIX}" )
```

That will avoid noise and confusion.

**Comment by dundargoc** [comment]
In that case maybe we should just revert https://github.com/neovim/neovim/pull/22072?

**Comment by dundargoc** [comment]
> Should we not restore the cmake code that forces an "acceptable fortify"

Hmm, it's a lot of cmake code, and something I worked hard to eliminate so I'd be sad if we were to being it back so easily. Could we try to fix this on the C side first in the same manner we did for #22072? I wouldn't mind putting some time on this to fix it.
