### ISSUE TITLE
Question: What internal terminal emulation can bring to a editor that coudn't be done otherwise?

### ISSUE THREAD

**Issue by oblitum** [neovim/neovim#2272]
Late to the terminal emulation discussion, I'd just like to ask some examples of what can terminal emulation bring that coudn't be done otherwise.

Let's imagine an hypothetical environment that offered a nice debug frontend that could connect to a nice nvim plugin. This debug environment is so nice that through some special nvim mappings to emulate something like [cgdb](http://cgdb.github.io/) keybindings, I could navigate the sources and press spacebar to toggle a breakpoint at the current line, the out-of-process debugger would then hear commands and issue a new breakpoint at the given line.

I mean, this is just some nice way of providing some kind of debugging-mode coupled with good extension capabilities and a debugger frontend own its own. There could be a real instance in a tmux pane besides my nvim window that would get in sync automatically, or it could be hidden, N buffers could get output comming from the front end communicating with the plugin, like watch and register windows, whatever. It didn't need to be in terminal too, usable also from GUI.

I can see this feasible without the need for internal terminal emulation, so I ask how better debugging integration can be a valid argument since one would need to get used to this new kind of terminal to use it?

To this day, I've never found a good terminal emulation inside any IDE, all of them coudn't compare with the real ones. I wish neovim good look on this new endeavor. As a tmux user, it's seems I'm inclined to ignore it if it can't bring something as professional. Also thinking whether it's too much for something that could just be a small and extensible _editor_.

**Comment by oblitum** [comment]
Another comment related to the subject is the culture surrounding Vim that **it's just a editor** and in the long room I came to appreciate this b/c I always appreciate one thing done well.

I've seen recent discussion about Ex Mode, you know what, at my Vim level this Ex Mode I think I've used just once and most of time I just have to press "visual" by accident, annoyance huh? But anyway I just find it fun, and I see it's for power users, for power editing capabilities. So it's a power editor feature considered to be removed and now, a non-editor one considered to get in.

**Comment by oblitum** [comment]
I'm closing b/c it's mostly an opinion. Although I'd like to hear answer to the former question. Feel free to provide any insights I coudn't get on this..

**Comment by justinmk** [comment]
@oblitum The "it's just an editor" thing started when Bram sort of gave up on [earlier goals](http://www.a-a-p.org/). You can see to this day that Bram intended a similar framework to the one that Neovim is espousing: make Vim extensible. Here: http://www.a-a-p.org

Neovim does not aim to be a kitchen-sink. Though it ships with a terminal emulator, the boundaries are clearly defined in the source code, unlike Vim's architecture. Anyone who complains about kitchen-sink syndrome is conveniently ignoring the fact that Vim contains a spellchecker, cscope and *netbeans* (wtf?) integration baked-in. Neovim is moving towards true modularization. The claim that Vim is more focused on being "just an editor" doesn't match reality. Rather, it failed at its early (ca. 2000) goals.

I'll also mention again, the `:shell` implementation in Vim is roughly the same SLOC count as the `:terminal` implementation in Neovim. Even if it were half as much, what exactly are people arguing about? A factor of two, and `:terminal` is a full solution whereas `:shell` is a barely-working hack.

**Comment by justinmk** [comment]
> To this day, I've never found a good terminal emulation inside any IDE, all of them coudn't compare with the real ones

So did you try `:terminal`?

**Comment by oblitum** [comment]
@justinmk I'm in the process of trying a new neovim build yet, for a couple of factors I coudn't get a recent build to test this, although I tried. Anyway, I guess it doesn't prevent any judgment from a high level point of view. Also, the features you're talking about looks much more like empowering editing (faster text lookup, better text correction) well, integrated spellcheck is a must for a __editor__ IMO. netbeans? A tentative to have Vim embeddable. For me all this is far from alien terminal emulation.

**Comment by oblitum** [comment]
But anyway, I don't want to bikeshed on this. I'd really like to hear examples of how terminal emulation can empower editing, or even providing better debugging, that coudn't be done as much as powerful just by having good extensibility.

**Comment by justinmk** [comment]
@oblitum You didn't mention `:shell`...

**Comment by oblitum** [comment]
@justinmk ah, well, I never used that thing! I didn't even know it existed. It should be so useless, b/c in my Vim history I have even tried _other_ shell emulations done by plugins.

**Comment by oblitum** [comment]
and almost forgot about them by the way... although they should be still there in my `.vimrc`.

**Comment by oblitum** [comment]
Just tried shell, I'm used to ctrl-z/fg for that.

**Comment by tarruda** [comment]
@oblitum If the arguments presented here and #2076 aren't enough, then you seem to have a couple of options:

- Simply ignore that `:terminal`/`termopen` exists. I've said and repeat: This feature won't affect you if you don't use it.
- If the mere presence of the integrated terminal bothers you too much, then simply continue using Vim. 

I'm sorry to put it out like this, but I simply don't have time to write long posts and try to convince people that already have made up their mind.

If you want to discuss the terminal behavior, feel free to open new issues such as #2257, but the presence of this feature is not open for discussion.

**Comment by oblitum** [comment]
@justinmk it's not a question of fewer code. To be really worth it I guess it will have to have more code and focus? It will also be another alternative to the shells we're already used to. If it won't have more focus/enhancement will it end up subpar to the alternative, not worth being relied on, if so, why have it. Sounds like an appendix.

**Comment by oblitum** [comment]
@tarruda, I'm not asking for long argumentation, just one example to counter what I said, it sure can be shorter than your last post. I can come from anyone.

**Comment by tarruda** [comment]
> @tarruda I'm not asking for long argumentation, just one example to counter what I said, it sure can be shorter than your last post. It can come from anyone.

Keep watching neovim for the next days, I plan to document use cases and even write a plugin or two.

**Comment by oblitum** [comment]
@tarruda OK, better to have demonstration than words. I'll so have room to think whether it could be done just by extensibility.

**Comment by oblitum** [comment]
@justinmk did he gave up? or was it a wise choice... =)

**Comment by bfredl** [comment]
> I'll so have room to think whether it could be done just by extensibility.

I think this is a bit of false dichotomy, as `:terminal` is one extension point among others. And IMHO it fits precisely into neovim's stated vision to communicate better and more easily with external processes.  `msgpack-rpc` requires the external process to "talk nvim" while `:terminal` enables a nvim plugin to talk with a process (shell/repl or similar) in its own command language (while the user still can interact with it directly in the emulated terminal), so the approaches are more or less complimentary.

**Comment by oblitum** [comment]
> > I'll so have room to think whether it could be done just by extensibility.

> I think this is a bit of false dichotomy, as :terminal is one extension point among others. And IMHO it fits precisely into neovim's stated vision to communicate better and more easily with external processes. msgpack-rpc requires the external process to "talk nvim" while :terminal enables a nvim plugin to talk with a process (shell/repl or similar) in its own command language (while the user still can interact with it directly in the emulated terminal), so the approaches are more or less complimentary.

I eager to check this. IMO, the standard extensibility point (`msgpack-rpc`) isn't it enough for a plugin author to build what's necessary to communicate with an external process? I see things doable just from one route as the other. I see the `:terminal` route as easier for hacking things faster and maybe less polished.

**Comment by oblitum** [comment]
Ok, I just tried it.... You know what, it's awesome to have, I thought it would screw up with my lovely zsh setup. I think it may have some room for usage even if I'm used to tmux.

Don't bother, thanks anyway.
