### ISSUE TITLE
Getting errors when pasting into nvim via WSL2 terminal

### ISSUE THREAD

**Issue by mxaddict** [neovim/neovim#22722]
### Problem

![image](https://user-images.githubusercontent.com/1060905/226093991-b51a7488-0117-4d1b-8bf8-105e413bb352.png)

### Steps to reproduce

nvim
open CtrlP plugin (search for file)
paste a file name
you will get error:
```
paste: Error executing lua: vim.lua:243: Vim:E21: Cannot make changes, 'modifiable' is off^@stack traceback:^@^I[C]: in function 'nvim_put'^@^Ivim.lua:243: in function <vim.lua:223>
```

### Expected behavior

Should let me paste the text and search the files in CtrP plugin

### Neovim version (nvim -v)

v0.6.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 11 (Running Ubuntu 22.04 inside WSL2

### Terminal name/version

Windows Terminal

### $TERM environment variable

screen-256color

### Installation

sudo apt install nvim

**Comment by zeertzjq** [comment]
Hmm, fixing this may be a bit complicated, as there is currently no way to check if currently inside `getchar()` from a callback.

**Comment by mxaddict** [comment]
Is the issue on all platforms or just WSL2?

I've not tested this in a native terminal on a Linux box.

**Comment by zeertzjq** [comment]
I haven't tested this, but I think this issue should exist on all platforms.

**Comment by zeertzjq** [comment]
`vim.paste()` in `runtime/lua/vim/_editor.lua`

**Comment by mxaddict** [comment]
Thanks, I'll check it out.

**Comment by erw7** [comment]
This is not a bug. See `:h getchar()`.

```
Get a single character from the user or input stream.
```

In the case of paste, the input stream is not passed through. Therefore, the pasted content cannot be obtained with `getchar()`.

The easiest way to fix this is to disable bracketed paste on the plugin side by doing the following before calling `getchar()`.

```vim
call chansend(v:stderr, "\<ESC>[?2004l")
```

**Comment by mxaddict** [comment]
> 

Noice, so I basically need to look at CtrlP instead of NVim :+1:

Thanks for the help

**Comment by justinmk** [comment]
> there is currently no way to check if currently inside `getchar()` from a callback.

We probably need this, so that `vim.paste` can handle this state automatically.
