### ISSUE TITLE
Why this nvim newbie is giving up

### ISSUE THREAD

**Issue by dankirshner** [neovim/neovim#22726]
### Problem

I think you've got to give users like me (or even less persistent than me) a better experience if you want us to change from the tried-and-true.

Running on Windows 11 from Cygwin64 Terminal.

:vers says NVIM v0.8.3.  Mostly nvim-qt

Problems (in order I ran into them).

set cm=blowfish2 in _vimrc produces "unknown option" error.
> OK, I've found the GitHub issue; you hated the code, and pulled it.  Better feedback needed: "cryptmethod is not available in nvim; see _____".
> But really, backwards compatibility is _everything_, if a pain ("Why was God able to create the world in only six days?"  "He didn't have to make it backwards compatible.")

Fonts do not show, unless do gfn=*; they go away on new-file edit.
> set guifont="Consolas:h10" (in _vimrc or in nvim-qt), for example, has no effect.  set guifont=* shows Consolas, 10pt as default, so hitting return works, and now it shows.  You get to do it again if you :edit a new file.

Cannot get plugins to load.
> Home directory vimfiles - nope.  Home directory .vim - nope.  Home directory _vimrc working, so should find these.  runtimepath includes C:\cygwin64\home\dan_k/.vim -- this doesn't look reassuring (forward slash?)

Final straw: can't debug this.
> -V unknown option 'V'
> It's in :help verbose.

If I've made some stupid wrong turn along the way, I'd be happy to try again.  But I'm at the end of my rope.

### Steps to reproduce

See above

### Expected behavior

See above

### Neovim version (nvim -v)

v0.8.3

### Vim (not Nvim) behaves the same?

No, I'm trying to replicate what works in Vim.  Identified issues do not work in Nvim

### Operating system/version

Windows 11

### Terminal name/version

Cygwin64

### $TERM environment variable

ansi

### Installation

nvim-win64.msi

**Comment by zeertzjq** [comment]
Did you read `:h nvim-from-vim`?

**Comment by zeertzjq** [comment]
> -V unknown option 'V'

Cannot reproduce this.

**Comment by zeertzjq** [comment]
> -V unknown option 'V'

This is a problem of nvim-qt. If you run `nvim -V` it works.

**Comment by dankirshner** [comment]
Yes, implemented nvim-from-vim suggestions.
OK, thanks, -- -V works.  Maybe it will help...

**Comment by dundargoc** [comment]
This is another data point for removing nvim-qt from nvim: to have a clear separation between these.

**Comment by dundargoc** [comment]
- set cm=blowfish2 in _vimrc produces "unknown option" error.

> Better feedback needed: "cryptmethod is not available in nvim; see _____".

Hmm, I kinda like this idea. Unsure how complicated it'd be to implement this, but the idea is solid in my opinion.

Also, please refrain from implying neovim doesn't care about backwards compatibility. That we have a different cost-benefit analysis compared to Vim does not mean we don't take great care to ensure backwards compatibility is respected. Removing cryptmethod was a calculated and (in my opinion) a great decision from neovim.

- Fonts do not show, unless do gfn=*; they go away on new-file edit.

I'm not familiar enough with fonts so someone else will have to chime in on this.

- Cannot get plugins to load.

Neovim doesn't use `~/.vimrc`. Take a look at `:h nvim-from-vim` like @zeertzjq suggested.

- -V unknown option 'V'

This is an unfortunate side effect of bundling nvim-qt with nvim. The separation will become clearer once we stop bundling nvim-qt with nvim.

----

Looking at the list above, only two seem actionable "better feedback" and "fonts not working". Again, someone else will have to take a lool at the fonts thing.

**Comment by 3N4N** [comment]
vi.SE is a better place for newcomers.  In another note, usability is of course paramount, but if a _vim user_ complains an editor is hard to configure then something has gone wrong in the world order.

**Comment by clason** [comment]
and "fonts not working" is irrelevant to _Neovim_, it's an Nvim-qt (usage) issue. This is a different project that is bundled for Windows users' convenience.

(*Ceterum censeo* we should stop doing this. It's confusing, there are now many more good GUIs for Windows, and the terminal experience is much better.)

**Comment by clason** [comment]
Framing usage issues as complaints is not helpful; if you want things to be exactly as they were with Vim, just keep using Vim. We'll keep the suggestion about better error messages for removed options in mind.
