### ISSUE TITLE
Installing  rrhughes 

### ISSUE THREAD

**Issue by Rimann91** [neovim/neovim#22725]
### Problem

Attempt to install neovim 0.8.3 via deb package fails

```
 $ sudo apt install ./nvim-linux64.deb
Reading package lists... Error!
E: read, still have 8 to read but none left
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Could not read meta data from /home/rrhughes/nvim-linux64.deb
E: The package lists or status file could not be parsed or opened.
```

### Steps to reproduce

1. curl download deb package from github
2. follow steps exactly outlined in release page to install deb package using apt

### Expected behavior

Successful installation

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

WSL2 Ubuntu on Windows 10

### Terminal name/version

WIndows Terminal

### $TERM environment variable

xterm-256color

### Installation

deb package

**Comment by clason** [comment]
Looks like a corrupted file. Try downloading again, or use the `appimage` -- which is the preferred distribution on Linux.
