### ISSUE TITLE
Error installing with Linuxbrew on Ubuntu

### ISSUE THREAD

**Issue by ruslanosipov** [neovim/neovim#2273]
brew install --HEAD neovim
    ==> Installing neovim from neovim/homebrew-neovim
    ==> Cloning https://github.com/neovim/neovim.git
    Updating /usr/local/google/home/ruslano/.cache/Homebrew/neovim--git
    ==> Checking out branch master
    ==> Downloading https://github.com/libuv/libuv/archive/v1.4.2.tar.gz
    Already downloaded: /usr/local/google/home/ruslano/.cache/Homebrew/neovim--libuv-1.4.2.tar.gz
    ==> Downloading https://github.com/msgpack/msgpack-c/archive/cpp-1.0.0.tar.gz
    Already downloaded: /usr/local/google/home/ruslano/.cache/Homebrew/neovim--msgpack-1.0.0.tar.gz
    ==> Downloading http://luajit.org/download/LuaJIT-2.0.3.tar.gz
    Already downloaded: /usr/local/google/home/ruslano/.cache/Homebrew/neovim--luajit-2.0.3.tar.gz
    ==> Downloading https://github.com/keplerproject/luarocks/archive/0587afbb5fe8ceb2f2eea16f486bd6183bf02f29.tar.gz
    Already downloaded: /usr/local/google/home/ruslano/.cache/Homebrew/neovim--luarocks-29.tar.gz
    ==> Downloading https://github.com/mauke/unibilium/archive/v1.1.2.tar.gz
    Already downloaded: /usr/local/google/home/ruslano/.cache/Homebrew/neovim--libunibilium-1.1.2.tar.gz
    ==> Downloading https://github.com/neovim/libtermkey/archive/8c0cb7108cc63218ea19aa898968eede19e19603.tar.gz
    Already downloaded: /usr/local/google/home/ruslano/.cache/Homebrew/neovim--libtermkey-19603.tar.gz
    ==> Downloading https://github.com/neovim/libvterm/archive/1b745d29d45623aa8d22a7b9288c7b0e331c7088.tar.gz
    Already downloaded: /usr/local/google/home/ruslano/.cache/Homebrew/neovim--libvterm-7088.tar.gz
    ==> make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/usr/local/google/home/ruslano/.linuxbrew/Cellar/neovim/HEAD" install
    make[2]: *** [CMakeFiles/unibilium.dir/all] Error 2
    make[2]: Leaving directory `/tmp/neovim20150327-8638-fz1ajt/.deps'
    make[1]: *** [all] Error 2
    make[1]: Leaving directory `/tmp/neovim20150327-8638-fz1ajt/.deps'
    make: *** [deps] Error 2

**Comment by Pyrohh** [comment]
Don't take me wrong, but is this the whole log? I wonder if more verbose output is available.

**Comment by ruslanosipov** [comment]
That's the whole log, is there a way to make the output more verbose?

**Comment by ruslanosipov** [comment]
I get a different error if I run `make install`:

```
make install
make  -C .deps
make[1]: Entering directory `/usr/local/google/home/ruslano/neovim/.deps'
make[2]: Entering directory `/usr/local/google/home/ruslano/neovim/.deps'
make[3]: Entering directory `/usr/local/google/home/ruslano/neovim/.deps'
make[3]: Leaving directory `/usr/local/google/home/ruslano/neovim/.deps'
make[3]: Entering directory `/usr/local/google/home/ruslano/neovim/.deps'
[  1%] Performing download step for 'unibilium'
-- file: /usr/local/google/home/ruslano/neovim/.deps/build/downloads/unibilium/v1.1.2.tar.gz
-- downloading...
     src='https://github.com/mauke/unibilium/archive/v1.1.2.tar.gz'
     dst='/usr/local/google/home/ruslano/neovim/.deps/build/downloads/unibilium/v1.1.2.tar.gz'
     timeout='none'
CMake Error at /usr/local/google/home/ruslano/neovim/third-party/cmake/DownloadAndExtractFile.cmake:71 (message):
  error: downloading
  'https://github.com/mauke/unibilium/archive/v1.1.2.tar.gz' failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  



make[3]: *** [build/src/unibilium-stamp/unibilium-download] Error 1
make[3]: Leaving directory `/usr/local/google/home/ruslano/neovim/.deps'
make[2]: *** [CMakeFiles/unibilium.dir/all] Error 2
make[2]: Leaving directory `/usr/local/google/home/ruslano/neovim/.deps'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/google/home/ruslano/neovim/.deps'
make: *** [deps] Error 2
```

**Comment by Pyrohh** [comment]
I'm pretty sure this is another case of curl not being built with SSL, could you run `curl --version | grep https`? Given your error message, grep shouldn't return any results. If that's not the case, then it might be CMake that isn't being built without SSL support, although that's just a guess.

**Comment by ruslanosipov** [comment]
```
curl --version | grep https
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
``` 

Should I rebuild `cmake`?

**Comment by Pyrohh** [comment]
> Should I rebuild cmake?

It seems like it. See here please https://github.com/neovim/neovim/issues/1469#issuecomment-63058312

**Comment by ruslanosipov** [comment]
Compiled `cmake` as suggested above (how can I tell if I'm using the right version?

```
~/neovim $ CC=gcc44 CXX=g++44 make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$HOME/src/nvim"
make  -C .deps
make[1]: Entering directory `/usr/local/google/home/ruslano/neovim/.deps'
make[2]: Entering directory `/usr/local/google/home/ruslano/neovim/.deps'
make[3]: Entering directory `/usr/local/google/home/ruslano/neovim/.deps'
make[3]: Leaving directory `/usr/local/google/home/ruslano/neovim/.deps'
make[3]: Entering directory `/usr/local/google/home/ruslano/neovim/.deps'
[  1%] Performing download step for 'unibilium'
-- file: /usr/local/google/home/ruslano/neovim/.deps/build/downloads/unibilium/v1.1.2.tar.gz
-- downloading...
     src='https://github.com/mauke/unibilium/archive/v1.1.2.tar.gz'
     dst='/usr/local/google/home/ruslano/neovim/.deps/build/downloads/unibilium/v1.1.2.tar.gz'
     timeout='none'
CMake Error at /usr/local/google/home/ruslano/neovim/third-party/cmake/DownloadAndExtractFile.cmake:71 (message):
  error: downloading
  'https://github.com/mauke/unibilium/archive/v1.1.2.tar.gz' failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  



make[3]: *** [build/src/unibilium-stamp/unibilium-download] Error 1
make[3]: Leaving directory `/usr/local/google/home/ruslano/neovim/.deps'
make[2]: *** [CMakeFiles/unibilium.dir/all] Error 2
make[2]: Leaving directory `/usr/local/google/home/ruslano/neovim/.deps'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/google/home/ruslano/neovim/.deps'
make: *** [deps] Error 2
```

**Comment by Pyrohh** [comment]
> (how can I tell if I'm using the right version?

As pretext, you should verify the version of CMake you built does indeed have SSL support, by running `ldd /path/to/cmake_with_ssl | grep ssl`, which should show something like `libssl.so.1.0.0 ...`

If you haven't already, try uninstalling the system version of CMake, and then installing the CMake you built to `/usr/local`. If you can run `cmake` on the command line, then your PATH already contains `/usr/local` and you should be good to go. You might have to clear the CMake cache but I'm doubtful, this can be done with `rm -r build` inside the `neovim` source directory.

**Comment by jszakmeister** [comment]
Have tried any of the debugging steps from [here](https://github.com/neovim/homebrew-neovim)?  In the case of Homebrew, we let Homebrew do the downloading, which uses a different mechanism.  I think there's probably something else going on.  My guess is that something is unavailable right now because of the DDoS attack that's occurring against GitHub.

**Comment by jszakmeister** [comment]
It looks like Homebrew's formula for CMake was [updated](https://github.com/Homebrew/homebrew/commit/47b71a21d9835b8ef0b6ea77fc8b50d31bbfd655) recently and it broke support for SSL.  I put up Homebrew/homebrew#38147 to fix it.
