### ISSUE TITLE
Neovim 0.8.3 can't set completeopt=longest in init.vim

### ISSUE THREAD

**Issue by cklin731** [neovim/neovim#22739]
### Problem

1.
If I set "set completeopt=longest" in the init.vim after the save and quit.
When I type "set completeopt?".
Neovim shows "completeopt=menuone".

2.
If I set "autocmd FileType * set completeopt=longest" in the init.vim after the save and quit.
When I type "set completeopt?".
Neovim shows "completeopt=menuone".

3.
If I am in the Command-line-mode.
I type ":set completeopt=longest".
And I type "set completeopt?".
Neovim shows "completeopt=longest".

### Steps to reproduce

nvim init.vim
set completeopt=longest
:x
nvim init.vim
:set completeopt?
completeopt=menuone

### Expected behavior

nvim init.vim
set completeopt=longest
:x
nvim init.vim
:set completeopt?
completeopt=longest

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

no, vim 8.2.2434

### Operating system/version

Debian 11

### Terminal name/version

GNOME terminal 3.38.3

### $TERM environment variable

xterm-256color

### Installation

system package manager (dpkg)

**Comment by craigmac** [comment]
are you doing step 2 in your init? your repro steps don't match what you seem to be saying you did? I can't reproduce this.

**Comment by zeertzjq** [comment]
Use `:verbose set completeopt?` to see where its value is overridden.
