### ISSUE TITLE
Treesitter: E1502: Lua failed to grow stack to ...

### ISSUE THREAD

**Issue by mangelozzi** [neovim/neovim#22735]
### Problem

Treesitter start to generates blocking errors (press enter to continue) when trying to code. 
After updating via Packer, I started to get the following errors (after using nvim for a session of about 15 mins):

```
E1502: Lua failed to grow stack to 4153
E5108: Error executing lua attempt to call a string value
stack traceback:
```
But there is no traceback. I checked with `:messages`. 

There is no detail in the messages, but on screen noticed this:
![image](https://user-images.githubusercontent.com/19764314/226326618-763005b0-7ab7-4a41-93ac-fb38370fdb42.png)

It's not a lack of RAM, I have plenty of memory left:
```
$ free
               total        used        free      shared  buff/cache   available
Mem:        32649252     6066648    20814172      970648     5768432    25153956
Swap:       47999992           0    47999992
```

I have to keep closing and restarting neovim, use it for a abit, then restart.

### Steps to reproduce

Not sure for now, because one has to use it for a while to mabye use up memory or something. Wanting to see if others have the issue too.

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

Ubuntu 22.04

### Terminal name/version

gnome-terminal

### $TERM environment variable

N/A

### Installation

appimage

**Comment by lewis6991** [comment]
This is not a memory issue but a stack limit issue.

Please provide more information. You've not even provided what parser you are running or the contents of the file. An error on its own is never enough.

**Comment by mangelozzi** [comment]
> This is not a memory issue but a stack limit issue.
> 
> Please provide more information. You've not even provided what parser you are running or the contents of the file. An error on its own is never enough.

Sorry for the vague details, I was just happy to be able to narrow it down to treesitter. I am using the `python`  LSP.

Can see I got an error even file a file that has just `print('hello')` but not the stack error, next time it occurs will post it:
![image](https://user-images.githubusercontent.com/19764314/226438098-9cb33c79-ef74-4187-84d2-a6f167415c95.png)


This is my config:
```
require('nvim-treesitter.configs').setup {
    -- A list of parser names, or "all" (the four listed parsers should always be installed)
    ensure_installed = {
        "bash",
        "c",
        "comment",
        "cpp",
        "c_sharp",
        "css",
        "diff",
        "html",
        "htmldjango",
        "ini",
        "javascript",
        "jsonc",
        "lua",
        "python",
        -- "sql",
        "typescript",
    },

    indent = {
        enable = false,
    },

    incremental_selection = {
        enable = true,
        keymaps = {
            init_selection = "<M-l>",
            node_incremental = "<M-l>",
            scope_incremental = "<M-L>",
            node_decremental = "<M-h>",
        },
    },

    -- Install parsers synchronously (only applied to `ensure_installed`)
    sync_install = false,

    -- Automatically install missing parsers when entering buffer
    -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
    auto_install = true,

    highlight = {
        -- `false` will disable the whole extension
        enable = true,

        -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
        -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
        -- Using this option may slow down your editor, and you may see some duplicate highlights.
        -- Instead of true it can also be a list of languages
        additional_vim_regex_highlighting = false,
    },
}
-- local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
-- parser_config.tsx.filetype_to_parsername = { "javascript", "typescript.tsx" }
```

**Comment by clason** [comment]
This means your parser is out of date with the bundled queries. Make sure `nvim-treesitter` is at the latest commit and that the Python parser is up to date (`:TSUpdate`; if that doesn't help, `:TSUninstall python` followed by `:TSInstall python`.
