### ISSUE TITLE
Command and option key mapping commands cannot be used in nvim in macOS

### ISSUE THREAD

**Issue by rileychc** [neovim/neovim#22748]
### Problem

Command and option key mapping commands cannot be used in nvim in macOS

### Steps to reproduce

don't know.

### Expected behavior

Use the command and option keys in macOS

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.2.1

### Terminal name/version

iterm2 Build 3.4.19

### $TERM environment variable

xterm-256color

### Installation

don't know.

**Comment by rileychc** [comment]
> What mappings are you using?

Command and option keys of macOS，They can't be used on neovim.

**Comment by justinmk** [comment]
Nonsense. This is up to your terminal emulator.

**Comment by rileychc** [comment]
> Nonsense. This is up to your terminal emulator.

I use iterm2iterm2 Build 3.4.19 xterm-256color

**Comment by rileychc** [comment]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/116857974/226618263-5e813803-d5c5-4384-a09e-7758b83a5655.png">
It didn't work.
