### ISSUE TITLE
Colorschemes are wrong with Neovim 0.8 and later

### ISSUE THREAD

**Issue by tnkhanh** [neovim/neovim#22745]
### Problem

Neovim colorschemes look wrong on freshly installed Ubuntu, as if `termguicolors` is on. Turning `termguicolors` on or off does not change the colorscheme much.

### Steps to reproduce

- Install a fresh Ubuntu, 22.04 or 20.04
- Download neovim from https://github.com/neovim/neovim/releases/tag/stable (I get the nvim-linux64.tar.gz file) (this happens in version 0.8 and later)
- Extract and run neovim
- Colorschemes are wrong, for example, colorscheme ron looks like this when `termguicolors` is off, similar to when its on
![nvim-open](https://user-images.githubusercontent.com/4347803/226556286-53f5329c-7474-49ec-8461-69fc54449ebb.png)
![ron-0 8](https://user-images.githubusercontent.com/4347803/226550461-b8c50e10-057d-4d42-9009-f19083c12e3e.png)
- Some other colorschemes behave the same

**Note**
- This does not happen in neovim 0.7.2 and older versions
- Setting `VIMRUNTIME` to 0.7's `VIMRUNTIME` solves the problem (maybe it uses the old colorscheme settings)

### Expected behavior

Colorscheme ron should look like this: (in my neovim 0.7.2)
![ron-0 7](https://user-images.githubusercontent.com/4347803/226554927-3c0aa7a6-b5d1-4f64-8464-6c42910b8dc2.png)

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

no, vim 8.1

### Operating system/version

Ubuntu 22.04

### Terminal name/version

Ubuntu default (# GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD)

### $TERM environment variable

xterm-256color

### Installation

download  nvim-linux64.tar.gz from https://github.com/neovim/neovim/releases/tag/stable

**Comment by zeertzjq** [comment]
They are not wrong.

**Comment by zeertzjq** [comment]
See https://github.com/vim/vim/issues/10449

**Comment by tnkhanh** [comment]
What can I do to make the colorscheme look like before? Is there a simple fix?

**Comment by tnkhanh** [comment]
Oh, ron is a problematic guy, lol. I see it now
