### ISSUE TITLE
MessagePack::RPC timeout when attempting to get current buffer contents

### ISSUE THREAD

**Issue by dphase** [neovim/neovim#2275]
When using ruby msgpack-rpc to communicate with a nvim instance, I'm able to request and receive responses from methods like ```:vim_get_api_info```, ```:vim_command```, and ```:vim_input```.

However, when trying to receive the contents of the current buffer, the client hangs and eventually times out.  I'm unsure if this is a problem on my end, an issue with Ruby's msgpack-rpc lib, or something else.  

Below is a sample of exactly what's happening:

```ruby
transport = MessagePack::RPC::UNIXTransport.new
address   = '/tmp/nvim.sock'
nvim      = MessagePack::RPC::Client.new transport, address

nvim.call :vim_get_api_info
# => API info returns as hash

nvim.call :vim_input, "ihello world\x1b:%s/world/earth\xd"
# => insert mode, text is written, regex sub command sent and exec'd

nvim.call :vim_get_current_buffer
# => MessagePack::RPC::TimeoutError: request timed out
#    (...)/msgpack-rpc-0.5.3/lib/msgpack/rpc/future.rb:59:in `get'
#    (...)/msgpack-rpc-0.5.3/lib/msgpack/rpc/session.rb:54:in `call'
```

**Comment by tarruda** [comment]
Neovim does not handle all events immediately. If you execute a command or do anything that leaves nvim in a "press enter to continue" or "--more--" state, then certain requests will only be processed after the nvim returns to normal. These are called deferred events, and is something I definitely want to remove, but will require some refactoring of old code. Any event that can directly execute vimscript is deferred, examples:

- Modifying a buffer
- Evaluating vimscript expressions
- Executing ex commands

Examples of non deferred events(that can be handled in any state):

- Pushing input(vim_input method)
- Reading buffer contents

**Comment by tarruda** [comment]
Hmm. `vim_get_current_buffer` should not timeout since its not deferred.

Do you think you can reproduce with the [python-client](https://github.com/neovim/python-client) in the python REPL?

**Comment by dphase** [comment]
Using the python-client from the Python REPL appears to work -- ```client.buffers[0]``` returns a ```Buffer``` object and I'm able to receive details on the object from its getter methods.

**Comment by tarruda** [comment]
> Using the python-client from the Python REPL appears to work -- client.buffers[0] returns a Buffer object and I'm able to receive details on the object from its getter methods.

I have not looked into ruby msgpack-rpc lib, but one of the reasons I created my own implementation is that I found the [spec](https://github.com/msgpack-rpc/msgpack-rpc/blob/master/spec.md) to be lacking some details. For example, Neovim requires its clients to be able to handle requests and notifications just like servers normally do, but the spec doesn't say anything related to this. In other words, Neovim sees servers and clients as enpoints, while the spec seems to treat them as distinct entities. I asked a [question](https://github.com/msgpack-rpc/msgpack-rpc-ruby/issues/2) about this but got no response.

A consequence is that the following scenario is perfectly reasonable with Neovim:

- client sends a request
- while handling the request, neovim sends another request to the client
- client responds to neovim request
- neovim responds to the initial request

I'm not sure if this is handled correctly by the msgpack-rpc ruby lib, so if you make a request that results in Neovim sending back another request(required to complete the initial request, for example), the ruby lib could hang the process.  Unfortunately I can't say much more about this without debugging the ruby lib myself.

FWIW I also created a [node.js lib](https://www.npmjs.com/package/msgpack5rpc) that should be able to communicate with Neovim correctly, so you can test it using the node.js REPL.
