### ISSUE TITLE
LSP: docs/hover handler doesn't handle HTML escape sequences

### ISSUE THREAD

**Issue by Kasama** [neovim/neovim#22757]
### Problem

Related to [this issue](https://github.com/redhat-developer/yaml-language-server/pull/844#issuecomment-1480559728)

When the Language server responds a markdown payload for a `textDocument/hover` request containing html escape sequences (in this example, many `&emsp;` sequences), the [stylize_markdown](https://github.com/neovim/neovim/blob/f01f18cdf4ffc3ce035db5fde2f45493eebb7fd9/runtime/lua/vim/lsp/util.lua#L1259) function doesn't handle it, causing it to be written as-is to the floating window's buffer.

Example response:

```json
{
  "contents": {
    "kind": "markdown",
    "value": "&emsp;#&emsp;#&emsp;#&emsp;#&emsp; &emsp;g&emsp;i&emsp;t&emsp;l&emsp;a&emsp;b&emsp;\\&emsp;-&emsp;c&emsp;i&emsp;\n&emsp;\n&emsp;T&emsp;h&emsp;e&emsp; &emsp;n&emsp;a&emsp;m&emsp;e&emsp; &emsp;o&emsp;f&emsp; &emsp;o&emsp;n&emsp;e&emsp; &emsp;o&emsp;r&emsp; &emsp;m&emsp;o&emsp;r&emsp;e&emsp; &emsp;j&emsp;o&emsp;b&emsp;s&emsp; &emsp;t&emsp;o&emsp; &emsp;i&emsp;n&emsp;h&emsp;e&emsp;r&emsp;i&emsp;t&emsp; &emsp;c&emsp;o&emsp;n&emsp;f&emsp;i&emsp;g&emsp;u&emsp;r&emsp;a&emsp;t&emsp;i&emsp;o&emsp;n&emsp; &emsp;f&emsp;r&emsp;o&emsp;m&emsp;\\&emsp;.&emsp;\n&emsp;\n&emsp;S&emsp;o&emsp;u&emsp;r&emsp;c&emsp;e&emsp;:&emsp; &emsp;[&emsp;c&emsp;i&emsp;.&emsp;j&emsp;s&emsp;o&emsp;n&emsp;]&emsp;(&emsp;h&emsp;t&emsp;t&emsp;p&emsp;s&emsp;:&emsp;/&emsp;/&emsp;g&emsp;i&emsp;t&emsp;l&emsp;a&emsp;b&emsp;.&emsp;c&emsp;o&emsp;m&emsp;/&emsp;g&emsp;i&emsp;t&emsp;l&emsp;a&emsp;b&emsp;-&emsp;o&emsp;r&emsp;g&emsp;/&emsp;g&emsp;i&emsp;t&emsp;l&emsp;a&emsp;b&emsp;/&emsp;-&emsp;/&emsp;r&emsp;a&emsp;w&emsp;/&emsp;m&emsp;a&emsp;s&emsp;t&emsp;e&emsp;r&emsp;/&emsp;a&emsp;p&emsp;p&emsp;/&emsp;a&emsp;s&emsp;s&emsp;e&emsp;t&emsp;s&emsp;/&emsp;j&emsp;a&emsp;v&emsp;a&emsp;s&emsp;c&emsp;r&emsp;i&emsp;p&emsp;t&emsp;s&emsp;/&emsp;e&emsp;d&emsp;i&emsp;t&emsp;o&emsp;r&emsp;/&emsp;s&emsp;c&emsp;h&emsp;e&emsp;m&emsp;a&emsp;/&emsp;c&emsp;i&emsp;.&emsp;j&emsp;s&emsp;o&emsp;n&emsp;)&emsp;"
  },
  "range": {
    "end": {
      "character": 9,
      "line": 2377
    },
    "start": {
      "character": 2,
      "line": 2377
    }
  }
}
```

Example hover on neovim
![image](https://user-images.githubusercontent.com/1714520/227105503-db74f612-0655-40e4-8cf1-6087ca04f376.png)

It would be great to have neovim decode those html sequences, similar to what [this luarocks package](https://github.com/TiagoDanin/htmlEntities-for-lua/blob/master/src/htmlEntities.lua#L2349) does.

---

A workaround for me is to use a wrapper function around `vim.lsp.handlers.hover` to remove those sequences manually

```lua
local function hover_wrapper(err, request, ctx, config)
  local bufnr, winnr = vim.lsp.handlers.hover(err, request, ctx, config)
  if (bufnr == nil or winnr == nil) then
    return
  end
  local contents = vim.api.nvim_buf_get_lines(bufnr, 0, -1, false)
  contents = vim.tbl_map(
    function(line)
      return string.gsub(line, "&emsp;", "")
    end,
    contents
  )
  vim.api.nvim_buf_set_option(bufnr, 'modifiable', true)
  vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, contents)
  vim.api.nvim_buf_set_option(bufnr, 'modifiable', false)
  vim.api.nvim_win_set_height(winnr, #contents)

  return bufnr, winnr
end

vim.lsp.handlers["textDocument/hover"] = hover_wrapper
```

Adding this to init.lua fixes the appearance of the hover for this language server, but there are others that probably have similar issues.

### Steps to reproduce using "nvim -u minimal_init.lua"

1. create a new temporary directory `cd $(mktemp -d)` and create an `init.lua` file with the following contents

```lua
local pattern = 'yaml'
local cmd = { 'yaml-language-server', '--stdio' }
-- Add files/folders here that indicate the root of a project
local root_markers = { '.gitlab-ci.yaml' }
-- Change to table with settings if required
local settings = {
  yaml = {
    schemas = {
      ["https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json"] = ".gitlab-ci.y*l",
    },
    hover = true,
  }
}

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'yamlls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})

vim.keymap.set('n', '<space>', vim.lsp.buf.hover, {})
```

2. create a .gitlab-ci.yaml file with the following contents

```yaml
stages:
  - hello
```

3. open it with neovim `nvim --noplugin -u init.lua .gitlab-ci.yaml`
4. wait a couple of seconds for yaml-language-server to be launched and press `<space>` with the cursor over the word `stages`

### Expected behavior

I expected neovim to be able to parse html entities in a markdown hover response to properly display them in the floating buffer.

### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release

### Language server name/version

yaml-language-server 1.12.0 https://github.com/redhat-developer/yaml-language-server/releases/tag/1.12.0

### Operating system/version

Linux Kasama 6.2.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 18 Mar 2023 01:06:36 +0000 x86_64 GNU/Linux

**Comment by Kasama** [comment]
I also volunteer to write a PR for this, but there are a couple of questions I'd like to have answered first.

- Is this something we want to do?
- Do we want to include the [luarocks package](https://github.com/TiagoDanin/htmlEntities-for-lua) that already handles these entities?
  - if not, should we include all entities that it handles, or just a subset of common ones? i.e. `&gt;`, `&lt;`, `&quot;`

**Comment by clason** [comment]
Is that even valid Markdown? Neovim's policy is to strictly implement the specification and not cater to every off-spec quirk that language servers may have "because VS Code handles it fine".

(And the near-term goal is to replace this function with one that uses the tree-sitter Markdown parser.)

**Comment by justinmk** [comment]
> the near-term goal is to replace this function with one that uses the tree-sitter Markdown parser

Yes 👍 

> Do we want to include the [luarocks package](https://github.com/TiagoDanin/htmlEntities-for-lua) that already handles these entities?

No (see above), but a small code change to workaround the issue is fine as a short-term solution, imo.

**Comment by clason** [comment]
Yes, that looks fine.
