### ISSUE TITLE
the signature of uv.new_thread in help is wrong

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#22769]
### Problem

currently it is: `uv.new_thread([{options}, ] {entry}, {...})`, but which actually is `uv.new_thread({entry}, {...})`, according to [its test cases](https://github.com/neovim/neovim/blob/v0.8.3/test/functional/lua/thread_spec.lua).

either on v0.8.3 or master:
* https://github.com/neovim/neovim/blob/v0.8.3/runtime/doc/luvref.txt#L3378
* https://github.com/neovim/neovim/blob/master/runtime/doc/luvref.txt#L3469

maybe there is something wrong in the help generating procedure?

### Steps to reproduce

nvim +'help uv.new_thread'

### Expected behavior

`uv.new_thread({entry}, {...})`

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

system package manager

**Comment by zeertzjq** [comment]
No, it's correct.
