### ISSUE TITLE
Doesn't take up the full area in Konsole

### ISSUE THREAD

**Issue by s1nistr4** [neovim/neovim#22767]
### Problem

I'm not sure if this is an issue with Neovim or Konsole, but when you open Nvim it doesn't take up the full screen in Konsole

https://postimg.cc/7bZRFbzp

### Steps to reproduce

1. Open nvim in konsole

### Expected behavior

For it to take up the screen

### Neovim version (nvim -v)

.

### Vim (not Nvim) behaves the same?

.

### Operating system/version

.

### Terminal name/version

.

### $TERM environment variable

.

### Installation

Official arch repos

**Comment by clason** [comment]
Your terminal window size needs to be an integer multiple of the cell width; otherwise you _have_ to pad as you can't have fractional rows or columns (wouldn't make sense in an editor).
