### ISSUE TITLE
Add `vim.filetype.set_option`

### ISSUE THREAD

**Issue by seblj** [neovim/neovim#22768]
### Problem

After https://github.com/neovim/neovim/pull/22634 we now have an easy way to get an option for a filetype. This got me wishing for an opposite which may set a default option for a filetype.

I have always found setting an option for a specific filetype a bit annoying. One would either have to create a separate file in `after/ftplugin/<ft>.lua,  or create an autocmd like:

```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = "<ft>",
    callback = function()
        -- Options here
    end,
}
```

Creating a separate file just for one line is a bit annoying, and especially when setting options for multiple files. Setting one option for 10 filetypes results in 10 files only containing one line each.

I don't find the second option using an autocmd on `FileType` much better in this case. While it removes the need for a lot of extra files, it will look very verbose.

### Expected behavior

I am proposing to add a new method on `vim.filetype` which serves the opposite purpose of `vim.filetype.get_option`.

I propose the following API which takes inspiration from `vim.api.nvim_buf_set_option` and `vim.api.nvim_buf_get_option`
```lua
---@param ft string
---@param name string
---@value any
function vim.filetype.set_option(ft, name, value)

-- Setting commentstring in C
vim.filetype.set_option("c", "commentstring", "// %s")
```

As one may want to set the same option on several filetypes, the first argument could be a table with filetypes like:

```lua
---@param ft string | string[]
---@param name string
---@value any
function vim.filetype.set_option(ft, name, value)

-- Setting commentstring in both C and C#
vim.filetype.set_option({ "c", "cs" }, "commentstring", "// %s")
```

This would remove the need to create a separate file just for setting a single option, or using autocmds which may be verbose when setting different options for multiple different filetypes

**Comment by clason** [comment]
> I don't find the second option using an autocmd on FileType much better in this case. While it removes the need for a lot of extra files, it will look very verbose.

While I understand the desire here, that is just not enough justification for adding a new API. The two existing methods are reasonable, effective, and above all battle tested. (And both natively support Lua, to boot.) The situation for get_option was fundamentally different as it implemented a functionality that was simply not possible before.

**Comment by to-json** [comment]
> While I understand the desire here, that is just not enough justification for adding a new API. The two existing methods are reasonable, effective, and above all battle tested. (And both natively support Lua, to boot.) 

(I say this while considering picking up the ticket and doing so myself) Would it be objectionable if said filetype method was fundamentally an alias for adding the autocmd? That both satisfies the request and keeps the functionality in the 'reasonable, effective, and above all battle tested' realm

**Comment by clason** [comment]
>  Would it be objectionable if said filetype method was fundamentally an alias for adding the autocmd?

I would say so, yes. This would add API surface and documentation for very little gain.

**Comment by to-json** [comment]
You're a long standing contributor and I'm a newb so I trust your judgement, but please send a ping if it's decided that this is worth doing, I would enjoy to implement it 

unrelated: it's not exactly the place for it, but if you have a ticket that you'd aim a new contributor at, I'd take that too; I just derive too much value from nvim not to try to do something here, but i never hit edge cases myself in it

**Comment by gpanders** [comment]
I know Vimscript is old fashioned and everyone wants to use Lua for everything now, but a benefit of it being a DSL is that these kinds of configurations do not suffer from the verbosity problem that Lua has:

```
autocmd FileType foo setlocal shiftwidth=4 expandtab commentstring=//%s
```

You can set multiple options for a filetype with a single line. If multiple filetypes share options, you can combine the filetypes in the pattern. Vimscript was (literally) made for this. 

IMO adding a new API just to avoid using Vimscript is not sufficient justification.

**Comment by yochem** [comment]
And if you want to do it in Lua, why not just add it as a function to your config:

```lua
local function set_ft_option(ft, option, value)
  vim.api.nvim_create_autocmd("FileType", {
    pattern = ft,
    callback = function()
      vim.opt_local[option] = value
    end
  })
end


set_ft_option({'c', 'c++'}, 'commentstring', '# %s')
```

**Comment by justinmk** [comment]
If creating an event handler is too verbose, let's find a way to fix that rather than adding special-purpose functions. Related: https://github.com/neovim/neovim/issues/19156

**Comment by myarcana** [comment]
Without this, it seems to be impossible to fix issues like: https://github.com/nvim-treesitter/nvim-treesitter/issues/7355

`:help commenting` says


```help
If the filetype of the buffer is associated with a language for which a
|treesitter| parser is installed, then |vim.filetype.get_option()| is called
to look up the value of 'commentstring' corresponding to the cursor position.
(This can be different from the buffer's 'commentstring' in case of
|treesitter-language-injections|.)
```

but `vim.filetype.get_option('htmldjango', 'commentstring')` returns the _incorrect_ value of `<!--%s-->` every time, even though I have tried my hardest to use autocommands and `ftplugin` directory and `after/ftplugin` to change the `commentstring` when `ft=htmldjango` to `{# %s #}`.

We need a way to change what `vim.filetype.get_option` returns.

**Comment by camoz** [comment]
I noticed that (please correct me if I'm wrong) it is currently not possible to dynamically change the `commentstring` option, and have it affect the behavior of `gc*`, on treesitter-backed files. E.g. in C/C++ files, I would find it helpful to be able to change `commentstring`, depending on whether the file uses `// this style` or `/* this style */` for comments. Or in Markdown files, I sometimes want to comment `<!-- like this -->` and sometimes `> like this`.

Could `vim.filetype.set_option` help here? Maybe the above is not enough of a justification for adding it, but in case it is a valid argument, and more of those are found over time, `vim.filetype.set_option` could be added at some point in the future.
