### ISSUE TITLE
[terminal-emulation] passing function <F{1..12}> keys to terminal

### ISSUE THREAD

**Issue by moshen** [neovim/neovim#2277]
This was the same everywhere I attempted it:
+ OS X, iTerm2
+ Xubuntu, urxvt

Open nvim, type `:term htop`.  Can't seem to pass any function key presses to control `htop`.  For example `<F10>` to quit.

Am I missing something?

**Comment by Pyrohh** [comment]
Can you reproduce your issue with `nvim -u NONE`? What's the output of `:verb map F`?

**Comment by moshen** [comment]
Same result.

> What's the output of :verb map F?

    No mapping found

**Comment by Pyrohh** [comment]
Ohhhhh, `F{1..12}`, I thought you meant a capital `F`. I can reproduce this easy, and I'm pretty sure this is the same bug encountered in #2254 and #2269 (we should probably have a master bug report with all three of these key groups mentioned).

**Comment by moshen** [comment]
Oops... should have been more specific initially.  Updated...

**Comment by tarruda** [comment]
shift-tab also isn't being passed to the terminal

**Comment by justinmk** [comment]
Closing in favor of https://github.com/neovim/neovim/issues/2440
