### ISSUE TITLE
ansible-language-server's syntax highlighting for error handling and task naming has changed/broken between nightly releases.

### ISSUE THREAD

**Issue by Whipplash** [neovim/neovim#22785]
### Problem

Hey! Not sure of the best way of explaining this, but upon installing NVIM on a new system I'd just configured, ansible-language-server appears to not be picking up the correct syntax highlighting that it used to. I'm certain at this point that it comes down to NVIM itself, as re-installing the Plugins/Modules/LSP with my latest git-backed-up NVIM configuration on another workstation running an older nightly, it appears the correct highlighting is still present.

### Steps to reproduce using "nvim -u minimal_init.lua"

1. Install latest NeoVim nightly.
2. Installed LSP-Zero/Packer via bootstrap of my backed up NVIM configuration.

Works as intended on older nightly releases.

### Expected behavior

Error handling, and task naming have lost colors. Not theme related, as I've tested with other versions. Here's the current version of NVIM and what I see in terms of syntax highlighting:

![image](https://user-images.githubusercontent.com/35666729/227740791-922ff0ff-f991-4763-95be-9876318a3951.png)

and here's a screenshot from my last workstation where the highlighting had been working as intended before I switched OSes and used the latest nightly:

![image](https://user-images.githubusercontent.com/35666729/227740760-cd4d1046-a738-490c-ade3-a256bbae4353.png)

The nightly in this had been neovim-0.9.0~dev.1137.ged05d38d9-500.fc37.x86_64

### Neovim version (nvim -v)

0.9.0-dev-1278+g063e93864

### Language server name/version

ansible-language-server

### Operating system/version

all/all

**Comment by swarn** [comment]
Is it possible that you were seeing treesitter highlighting before, and that the new semantic highlighting is overwriting it? If you use the `:Inspect` command with your cursor on one of the `name` fields that was red and italic before, what does it show?

**Comment by justinmk** [comment]
Can you bisect to the exact commit ? That will help a lot. Will require building nvim from source.

**Comment by mfussenegger** [comment]
This is very likely related to [1cc23e1109ed88275df5c986c352f73b99a0301c](https://github.com/neovim/neovim/commit/1cc23e1109ed88275df5c986c352f73b99a0301c) which changes the highlight scheme.

Try using `:Inspect` like swarn mentioned:

- It uses `@lsp.type.method` for properties like `src` or `dest` 
-  `@lsp.type.class` for the used modules (`ansible.builtin.file` )
- `@lsp.type.keyword` for stuff like `name:` or `args:`
