### ISSUE TITLE
[help]: how to rediret stdout when using a `.so` lib

### ISSUE THREAD

**Issue by yao-weijie** [neovim/neovim#22788]
### Problem

I'm developing a [plugin](https://github.com/yao-weijie/cmp-rime) to input chinese characters based on [cmp](https://github.com/hrsh7th/nvim-cmp) and [librime](https://github.com/rime/librime).

I used the neovim builtin `ffi` to call the `librime.so` shared library.
```lua
    ...
    ffi.load('librime.so')
    ffi.cdef('/path/to/rime_api.h')
    ...
    self.rime.api.initialize(self.traits) -- will dump log info
    ...
```

 When I set the librime log level to INFO, then load the so lib, the lib will dump the log output both to stdout and logfile, like this:
![Peek 2023-03-26 13-45](https://user-images.githubusercontent.com/36393630/227757783-b741475c-82de-4db5-9c07-f6a3bf7892f9.gif)
then set librime log level to ERROR, the the log info will be disabled in stdout nor logfile. 

Now my plugin doesn't work in some cases, and I want to know how to redirect the stdout from calling a so lib, then I can inspect the log info and debug.

### Steps to reproduce

shown above

### Expected behavior

redirect stdout/warn/err from `so` shared library

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

neovim only

### Operating system/version

debian testing ( not closely related)

### Terminal name/version

not related

### $TERM environment variable

not related

### Installation

deb buid from repo (not related)

**Comment by zeertzjq** [comment]
I don't think this issue belongs to this repository. I think it belongs to https://github.com/google/glog

**Comment by zeertzjq** [comment]
You may need to set `FLAGS_alsologtostderr` to `false`:
```lua
ffi.cdef('bool FLAGS_alsologtostderr;')
ffi.C.FLAGS_alsologtostderr = false
```
