### ISSUE TITLE
Ubuntu PPA is outdated and only providing v0.7.2

### ISSUE THREAD

**Issue by coaxial** [neovim/neovim#22790]
### Problem

The official PPA at https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable only provides neovim v0.7.2 which is 9 months old at the time of reporting this issue.

This is problematic because more and more plugins need at least v0.8.0.

### Steps to reproduce

add-apt-repository ppa:neovim-ppa/stable
apt update
apt install neovim
neovim --version

### Expected behavior

I would expect the official PPA to provide up to date packages and more recent stable neovim versions (i.e. 0.8.3 as of today)

### Neovim version (nvim -v)

NVIM v0.7.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by team+vim@tracker.debian.org

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Mint 20.3

### Terminal name/version

kitty 0.26.4

### $TERM environment variable

tmux-256color

### Installation

https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable

**Comment by dundargoc** [comment]
We're don't maintain that, you need raise the issue to them.

**Comment by dundargoc** [comment]
We provide appimages for the stable versions if you wanna try that.
