### ISSUE TITLE
distinguish Tab, ctrl-i in Terminal mode

### ISSUE THREAD

**Issue by huwqchn** [neovim/neovim#22795]
### Problem

Tab and Ctrl-i is same thing in terminal mode but different in normal mode

### Steps to reproduce

vim.keymap.set("t", "<C-i>", "<C-\\><C-N><C-w>l", { desc = "move to right" })
And press tab will move to right just like C-i

### Expected behavior

distinguish Tab, ctrl-i in Terminal mode

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

Don't know

### Operating system/version

arch linux 6.2.8

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

pacman

**Comment by zeertzjq** [comment]
They behavior differently if both of them are mapped.

**Comment by huwqchn** [comment]
Thanks, it work.
