### ISSUE TITLE
checkhealth: fold "OK" (successful) sections by default

### ISSUE THREAD

**Issue by dundargoc** [neovim/neovim#22796]
### Problem

With more neovim modules and plugins using checkhealth popping up, `:checkhealth` is starting to feel like reading CI logs with the amount of information that is presented to the user.

### Proposed solution

Automatically fold modules/sections that have passed their tests, but not for failed tests. This way the user will be shown the most important parts they need to know and fix, while also being able to inspect the information from the passing tests.

**Comment by austinwhite** [comment]
I'll work on this.

**Comment by zeertzjq** [comment]
How about purely informational health checks that don't have OK/FAIL status? Hiding them goes against their purpose.

**Comment by dundargoc** [comment]
Hmm, that's a good point. Those should probably be shown as well.
