### ISSUE TITLE
Luarocks package installations primary blocker for faster neovim builds

### ISSUE THREAD

**Issue by dundargoc** [neovim/neovim#22797]
### Problem

We're currently installing rocks one by one with forced serialization. By "forced" serialization, I mean that we in `cmake.deps/cmake/BuildLuarocks.cmake` manually specify the following dependency chain:

```
lua/luajit <- mpack <- lpeg <- luabitop <- busted <- luacheck <- coxpcall
```

meaning, that `coxpcall` depends on `luacheck`, `luacheck` depends on `busted` and so on. Of course, these "dependencies" are bogus, it's just to ensure luarocks doesn't install multiple rocks in parallel as it will emit warnings with possibly unpredictable behavior. Luarocks also doesn't (to my knowledge) allow installing multiple packages at once from the command line with something like

```
luarocks build <package A> <version> <package B> <version>
```

### Proposed solutions

Nothing at the moment. Suggestions welcome.

**Comment by lewis6991** [comment]
Surely we need luarocks for lpeg and busted?

**Comment by clason** [comment]
yes, but if remove the other rocks, the whole rocks (not luarocks-the-package-manager) installation will be faster ;)

**Comment by dundargoc** [comment]
> Surely we need luarocks for lpeg and busted?

I suppose dropping luarocks *is* one way to make luarocks installation faster, but I was hoping for a less drastic solution ;). Maybe the title wording is misleading? Edits welcome!

**Comment by dundargoc** [comment]
> Right, this is an old luarocks limitation. Eliminating dependencies is one way to shrink the cost here...

True, and we did remove `penlight` very recently for this very reason. I was hoping for a more long-term solution/perspective, but removing dependencies where possible is always nice of course :).

I should mention that I don't consider the current situation *that* bad, although I would very much like to find a solution for it. By my very rough estimations, parallelizing the luarocks segment would reduce the time of running `cmake.deps/CMakeLists.txt` by around 30%, so probably at most a 10-30 seconds savings on non-potato computers. This isn't really a big deal as building dependencies shouldn't be needed regularly, but it becomes noticible when e.g. bisecting.

**Comment by dundargoc** [comment]
> should we vendor mpack ? https://github.com/libmpack/libmpack-lua

@justinmk @clason this would remove the need for #22805 which would be awesome as the luarocks version upgrade isn't insignificant.

**Comment by clason** [comment]
We could also leave it as an external dependency but just build it ourselves?
