### ISSUE TITLE
Paste a very specific text cause neovim cannot quite edit mode

### ISSUE THREAD

**Issue by zhaowb** [neovim/neovim#22807]
### Problem

Very strange problem: paste test cause neovim displays ESC as raw char '^[' and all other chars like arrows or mouse click, without accepting them.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/3034273/228382246-1945255c-5674-4ffe-b281-0a10d52a41af.png">

Vim has no such problem.

The original text is a piece of normal python code.
I tried to remove feature from the text by replace text with repetitive letters and maintain same length.
In the following example, those with meaningful var names are the ones that if changed to something else, the problem won't reproduce.
In another word, the text with repetitive letters don't matter what the content is, as long as it remain same length, the problem exists.

After the problem is showing, I have to kill the process (or close terminal window) to quit.

### Steps to reproduce

remove all customization (rename ~/.config/nvim to another name)
nvim /tmp/t  (or any new file)
paste this text:
```
    ii = aaaaaaaaaa.UnicodeAttribute()
    ppppppppp_pp = aaaaaaaaaa.UnicodeAttribute()
    dddddddddd_dd = aaaaaaaaaa.UnicodeAttribute()
    ddddddddddd = aaaaaaaaaa.UnicodeAttribute(nnnn=tttt)
    nnnn = aaaaaaaaaa.UnicodeAttribute()
    qqqqqqq_qqqqqqq = aaaaaaaaaa.UnicodeAttribute()

    sssssssss_ssssssss = eeeeeeeeeeeee(eeee=SelectionBehavioreeee)
    iiiiiiiii = eeeeeeeeeeeee(eeee=iiiiiiiiieeee)

    lllll = aaaaaaaaaa.ListAttribute(oo=Link, nnnn=tttt)
    sssss_ssss = ddddddddddddd()
    eee_eeee = ddddddddddddd()
    oooooooo_ooooooo = aaaaaaaaaa.ListAttribute(oo=cccccc, nnnn=tttt)
    ccccccc_ccccc = aaaaaaaaaa.ListAttribute(oo=cccccc, nnnn=tttt)
    f_fffffff_fffff = aaaaaaaaaa.UnicodeAttribute(nnnn=tttt)
    sssssssssss = aaaaaaaaaa.ListAttribute(oo=Suggestion)
    ssssss = ssssss()
    ii_iiiiiii = aaaaaaaaaa.bbbbbbbbbbbbbbbb(ddddddd_ddd_ddd=fffff)
    aaaaaaaaaa_aaaaaaaaaaaaa = aaaaaaaaaa.ListAttribute(oo=dddddddddd, nnnn=tttt)
    eeeeeeee_ee = aaaaaaaaaa.UnicodeAttribute(nnnn=tttt)
```

### Expected behavior

should work

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 16 2022 23:29:16)

### Operating system/version

macOS 13.2.1 

### Terminal name/version

Terminal.app

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by zhaowb** [comment]
@justinmk just tried v0.9.0-dev-1291+gbad218cd6 has same problem

**Comment by zhaowb** [comment]
Update: I have removed all features from text by replacing with repetitive letters. The following text can trigger the problem (with >=3 empty lines at the end)
```text
CCCCiiCDCaaaaaaaaaaEuuuuuuuuuuuuuuuuAB
CCCCpppppppppGppCDCaaaaaaaaaaEuuuuuuuuuuuuuuuuAB
CCCCddddddddddGddCDCaaaaaaaaaaEuuuuuuuuuuuuuuuuAB
CCCCdddddddddddCDCaaaaaaaaaaEuuuuuuuuuuuuuuuuAnnnnDttttB
CCCCnnnnCDCaaaaaaaaaaEuuuuuuuuuuuuuuuuAB
CCCCqqqqqqqGqqqqqqqCDCaaaaaaaaaaEuuuuuuuuuuuuuuuuAB
CCCCsssssssssGssssssssCDCeeeeeeeeeeeeeAeeeeDsssssssssssssssssssssB
CCCCiiiiiiiiiCDCeeeeeeeeeeeeeAeeeeDiiiiiiiiieeeeB
CCCClllllCDCaaaaaaaaaaElllllllllllllAooDllllFCnnnnDttttB
CCCCsssssGssssCDCdddddddddddddAB
CCCCeeeGeeeeCDCdddddddddddddAB
CCCCooooooooGoooooooCDCaaaaaaaaaaElllllllllllllAooDccccccFCnnnnDttttB
CCCCcccccccGcccccCDCaaaaaaaaaaElllllllllllllAooDccccccFCnnnnDttttB
CCCCfGfffffffGfffffCDCaaaaaaaaaaEuuuuuuuuuuuuuuuuAnnnnDttttB
CCCCsssssssssssCDCaaaaaaaaaaElllllllllllllAooDssssssssssB
CCCCssssssCDCssssssAB
CCCCiiGiiiiiiiCDCaaaaaaaaaaEbbbbbbbbbbbbbbbbAdddddddGdddGdddDfffffB
CCCCaaaaaaaaaaGaaaaaaaaaaaaaCDCaaaaaaaaaaElllllllllllllAooDddddddddddFCnnnnDttttB
CCCCeeeeeeeeGeeCDCaaaaaaaaaaEuuuuuuuuuuuuuuuuAnnnnDttttB



```

I tried to paste later block of text, random and normal python code, all worked fine.
Also I tried different shells, zsh, bash, sh all have same problem.

The problem seems to have connection with a specific pattern of line length.
But I tried to replace all chars with same char (C) and failed to reproduce the problem.

**Comment by zhaowb** [comment]
It might be a Terminal.app problem rather than neovim's problem.
I just tried [iTerm2](https://iterm2.com/) and it's working fine.

**Comment by justinmk** [comment]
One improvement we need is to check for CTRL-c so that this state is recoverable. https://github.com/neovim/neovim/issues/10865

**Comment by erw7** [comment]
> One improvement we need is to check for CTRL-c so that this state is recoverable. https://github.com/neovim/neovim/issues/10865

It is problematic to terminate a paste with characters that may be included(`CTRL-c`) in the text being pasted. There are known attacks that paste content other than the user's selected text in a paste-from-browser scenario. Therefore, this attack may succeed if we terminate the paste with `CTRL-c`, etc.

IMO: The preferred solution to this problem is when `tinput_read_cb()` finishes with `input->past != 0`, set a timer that will terminate the paste if the next sequence does not arrive with a long enough timeout(e.g. 5sec).

**Comment by erw7** [comment]
@zhaowb If you have access to a debugger, check that the terminal is sending `\x1b[201~`. If the terminal is not sending the end-of-paste sequence(`\x1b[201~`), then that is the terminal problem, not neovim. I think https://github.com/neovim/neovim/issues/13921#issuecomment-782811093 is a good reference on how to check. However, now you need to look up the pid of tui, not the pid obtained by `:echo getpid()`, by `ps` or other means.

**Comment by justinmk** [comment]
No issue on macos NVIM v0.11.0-dev-840 f2fa4ca97ea3. Possibly fixed by @zeertzjq 's recent fixes.
