### ISSUE TITLE
Extra period inserted when selecting omni completion item from pop-up menu with tsserver

### ISSUE THREAD

**Issue by heygarrett** [neovim/neovim#22803]
### Problem

Triggering omni completion after a `.` and then selecting an item from the pop-up menu inserts an extra `.`:
![](https://user-images.githubusercontent.com/1154912/228121313-c362acc3-5a3a-4c10-a010-5d5e83c4567b.gif)

I can only reproduce this with tsserver, so [I filed an issue over there](https://github.com/typescript-language-server/typescript-language-server/issues/711), but they pointed me back towards Neovim.

### Steps to reproduce using "nvim -u minimal_init.lua"

<details><summary>minimal config</summary>

```lua
vim.opt.completeopt = { "menuone", "noselect" }
vim.keymap.set("i", "<c-space>", "<c-x><c-o>")

--- CHANGE THESE
local pattern = "typescript"
local cmd = { "typescript-language-server", "--stdio" }
-- Add files/folders here that indicate the root of a project
local root_markers = { ".git", ".editorconfig", "package.json" }
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd("FileType", {
	pattern = pattern,
	callback = function(args)
		local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
		local root_dir = match and vim.fn.fnamemodify(match, ":p:h") or nil
		vim.lsp.start({
			name = "bugged-ls",
			cmd = cmd,
			root_dir = root_dir,
			settings = settings,
		})
		vim.lsp.set_log_level("debug")
	end,
})
```
</details>

1. `npm install --global typescript-language-server`
2. Create a new directory and `npm init` with `index.ts` as the entry point
3. Create `index.ts` and add the following

```typescript
const new_object = {
	abc: "test",
	bcd: "test2",
	cde: "test3",
};
```

4. On a new line type `new_object.`
5. Trigger omni completion with `<c-x><c-o>` or the `<c-space>` keymap I included in the minimal config
6. Use `<c-n>` to select the first completion item in the pop-up menu

### Expected behavior

The completion item would be inserted as `abc`, resulting in:

```typescript
new_object.abc
```

The actual behavior is that the completion item is inserted as `.abc`, resulting in:

```typescript
new_object..abc
```

### Neovim version (nvim -v)

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

### Language server name/version

typescript-language-server 3.3.1

### Operating system/version

macOS 13.3

### Log file

https://gist.github.com/heygarrett/019363da1150ef2fc3c5bcbc56ebd7c0

**Comment by Vizualni** [comment]
I can confirm that this is happening to me as well.

**Comment by kennethlee** [comment]
I am currently experiencing this issue as well.
