### ISSUE TITLE
OptionSet autocmd not triggered inside autocmd even if `nested=true` is set

### ISSUE THREAD

**Issue by Bekaboo** [neovim/neovim#22819]
### Problem

When user creates two autocmds with triggering event `OptionSet` for two different options, for example, `colorcolomn` and `textwidth`, and set `colorcolumn` inside the callback function of the autocmd for `textwidth`, the autocmd for `colorcolumn` will not fire even if the autocmd for `textwidth` has set `opts.nested` to `true`.

To clarity, the following is the minimal `init.lua` that can reproduce this issue:

```lua
-- init.lua
vim.api.nvim_create_augroup('Test', {})
vim.api.nvim_create_autocmd('OptionSet', {
    pattern = 'textwidth',
    group = 'Test',
    nested = true,
    callback = function()
        print('textwidth set')
        vim.wo.cc = ''
    end,
})
vim.api.nvim_create_autocmd('InsertEnter', {
    group = 'Test',
    nested = true,
    callback = function()
        print('insert enter')
        vim.wo.cc = ''
    end,
})
vim.api.nvim_create_autocmd('OptionSet', {
    pattern = 'colorcolumn',
    group = 'Test',
    callback = function()
        print('colorcolumn set')
    end,
})
```

If user set `textwidth` in the cmdline, `"textwidth set"` will be printed but `"colorcolumn set"` will not.
But if user enters insert mode, both `"insert enter"` and `"colorcolumn set"` will be printed.

The current behavior is that `OptionSet` will not be triggered by another `OptionSet` autocmd even if `nested` is set to `true`.

The desired behavior is that in both cases the `OptionSet` autocmd for `colorcolumn` will be triggered.

vim behaves the same, minimal `.vimrc`:

```vim
augroup Test
    au!
    au OptionSet    colorcolumn ++nested echom "colorcolumn set"
    au OptionSet    textwidth   ++nested echom "textwidth set" | setlocal cc=
    au InsertEnter  *           ++nested echom "insert enter"  | setlocal cc=
augroup END
```

### Steps to reproduce

1. Save the minimal `init.lua` mentioned above as `init_test.lua`
2. `nvim -u init_test.lua`
3. Set `tw` from cmdline: `:set tw=80` -> `"textwidth set"` printed
4. Enter insert mode -> both `"insert enter"` and `"colorcolumn set"` printed

### Expected behavior

`"colorcolumn set"` should be printed when `tw` is set.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1290+g2257ade3dc

### Vim (not Nvim) behaves the same?

yes, vim 9.0

### Operating system/version

Linux 6.2.8-arch1-1

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

tmux-256color

### Installation

AUR

**Comment by zeertzjq** [comment]
It is documented that `OptionSet` is non-recursive:
```
				Non-recursive: |:set| in the autocommand does
				not trigger OptionSet again.
```

Since `OptionSet` autocommand sets some variables, it isn't straightforward to allow it to be recursive.

**Comment by Bekaboo** [comment]
Thanks
