### ISSUE TITLE
Crash with :tselect and terminal resizing with v0.9.0-dev-1292+geac75a971 appimage

### ISSUE THREAD

**Issue by jbwyatt4** [neovim/neovim#22818]
### Problem

nvim crashes with no input when you maximize the terminal window with the :tselect selection. Does not crash with v0.8.3 native fedora package.

Tested with GNOME Terminal and Foot Terminal on GNOME 43 with Fedora 37.

### Steps to reproduce

Exact test case:
* appimage copied to /usr/local/bin/n
* open a terminal window that occupies a small part of the screen, do not maximize yet
* clone upstream Linux kernel tree: git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git torvalds
* generate tags: cd torvalds && make tags
* n
* :tselect schedule
* with the selection to choose an option, maximize the screen window
* crashes

### Expected behavior

Not crash on terminal window resizing

### Neovim version (nvim -v)

v0.9.0-dev-1292+geac75a971 appimage

### Vim (not Nvim) behaves the same?

no, 9.0.1429 and nvim 0.8.3 does not either

### Operating system/version

Fedora 37 GNOME

### Terminal name/version

Gnome Terminal 3.46.8 and Foot Terminal 1.13.1 -pgo +ine +graphemes -assertions

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
Cannot reproduce. What is the terminal size before and after resizing?

**Comment by zeertzjq** [comment]
Possibly related to #22278

**Comment by jbwyatt4** [comment]
> Cannot reproduce. What is the terminal size before and after resizing? And what does "with the selection to choose an option" mean?

When you have a list of options from :tselect something, before you select one of those matches you resize the terminal window.

I just tried v0.9.0-dev-1312+g908494889 appimage and I can not reproduce it anymore. Sorry for the noise. Closing issue.
