### ISSUE TITLE
recursive key mapping for vim.api.nvim_feedkeys

### ISSUE THREAD

**Issue by ioperations** [neovim/neovim#22822]
### Problem

neovim without any config but following 
```lua 
vim.keymap.set("i", "<c-b>", function()
        local key = vim.api.nvim_replace_termcodes("<c-b>", true, false, true)
        vim.api.nvim_feedkeys(key, "i", false)
end, { silent = true, noremap = true }) 
```
Insert mode, when I hit \<c-b> then neovim get 100% cpu usage ,maybe recursive function call!

actually I want to do key mapping for <c-b> in insert mode, when some condition matches I want to do job1 ,others the keymap fallbacks to default action in neovim. maybe usage error, 

### Steps to reproduce

nvim --clean
load the following config 
```lua
 vim.keymap.set("i", "<c-b>", function()
        local key = vim.api.nvim_replace_termcodes("<c-b>", true, false, true)
        vim.api.nvim_feedkeys(key, "i", false)
end, { silent = true, noremap = true }) 
```
:e test
hit \<c-b>

-- then you can see your neovim has 100% cpu usage rate

### Expected behavior

key maping not recursive

### Neovim version (nvim -v)

v0.8.3 Release

### Vim (not Nvim) behaves the same?

vim do not support lua script

### Operating system/version

macos 10.15

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

aur

**Comment by zeertzjq** [comment]
> actually I want to do key mapping for in insert mode, when some condition matches I want to do job1 ,others the keymap fallbacks to default action in neovim.

Use either `n` flag
```lua
vim.keymap.set("i", "<c-b>", function()
        local key = vim.api.nvim_replace_termcodes("<c-b>", true, false, true)
        vim.api.nvim_feedkeys(key, "ni", false)
end, { silent = true })
```

or `expr` if the condition is safe there
```lua
vim.keymap.set("i", "<c-b>", function()
        return '<c-b>'
end, { silent = true, expr = true })
```
