### ISSUE TITLE
Closing braces highlighted in red in Lua heredocs in Vimscript

### ISSUE THREAD

**Issue by 0xallie** [neovim/neovim#22825]
### Problem

When writing Lua code in a heredoc in a `.vim` file, closing braces are highlighted in red even though there is no actual syntax error:
<img width="163" alt="Screenshot of the issue" src="https://user-images.githubusercontent.com/482367/228883705-0cb46061-feb7-44a2-b453-1268d0779cb9.png">

### Steps to reproduce

```
nvim --clean test.vim
```
```
:syntax on
```
Paste the following code:
```vim
lua <<EOF
print("Hello world")
EOF
```

### Expected behavior

Closing braces should not be highlighted in red.

### Neovim version (nvim -v)

v0.9.0-dev-1280+g36ee10057-dirty

### Vim (not Nvim) behaves the same?

N/A (Vim does not support this, so it just highlights the whole file in red)

### Operating system/version

macOS 13.3

### Terminal name/version

iTerm2 3.4.19

### $TERM environment variable

xterm-256color

### Installation

AppImage

**Comment by clason** [comment]
Duplicate

**Comment by 0xallie** [comment]
Sorry, I didn't find it with a quick search.
