### ISSUE TITLE
Update neovim-stable ppa as soon as neovim-unstable updates the version number

### ISSUE THREAD

**Issue by tijoer** [neovim/neovim#22828]
### Problem

Hi, currently https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable ist at Neovim 0.9. https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable however is at 0.7 and not at 0.8.

### Expected behavior

I would suggest du update the stable version, as soon as there is a new update in the unstable ppa.

**Comment by clason** [comment]
"Neovim 0.9" is a nightly prerelease; there is no official 0.8 release yet, unfortunately (which has been reported *ad nauseam* but is not something the Neovim project is involved in).
