### ISSUE TITLE
LSP: Support `textdocument/diagnostic`

### ISSUE THREAD

**Issue by smarquez1** [neovim/neovim#22838]
### Problem

Neovim implements the `textDocument/publishDiagnostic` specification
for the diagnostics feature. Where the server notifies the client of this event.

[LSP 3.17 implemented the `textDocument/pullDiagnostic` specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_pullDiagnostics),
that expects the client to send `textDocument/diagnostic` requests to the server
when the client wants diagnostics updates.

### Expected behavior

Support `textDocument/diagnostic feature out of the box.

#### Extra information:

* [Related nvim-lspconfig PR](https://github.com/neovim/nvim-lspconfig/pull/2498) that implements a workaround for `ruby-lsp` to send `textDocument/diagnostic` requests to the Server, and treat the response like it was for a `textDocument/publishDiagnostic` event.

**Comment by catlee** [comment]
This should be fixed now, in v0.10.0-dev-695+g58f948614 and later.
