### ISSUE TITLE
Allow user defined motions to work like builtin motions / textobjects

### ISSUE THREAD

**Issue by vypxl** [neovim/neovim#22836]
### Problem

There are the builtin motions and textobjects like `w`, `e`, `it`, ... and they all work fine. There is `g@{motion}` which allows for a custom function to act as an operator over a motion, and is dot repeatable.

What is missing, is a way to define a motion. Yes, we have `nvim_win_set_cursor`, but that is not a motion. It doesn't set marks, it can't be dot-repeated, and just does not work like a motion at all.

**Why is it useful?**

There are amazing projects like [nvim-various-textobjects](https://github.com/chrisgrieser/nvim-various-textobjs) or [nvim-spider](https://github.com/chrisgrieser/nvim-spider) which aim to implement new practical motions. However, both projects struggle with implementation, especially the dot-repeatability, because they have to rely on weird hacks to implement motions.

Also, having motions be repeatable with `;` would be cool too, especially when considering more sophisticated motions.

### Expected behavior

I see two ways of how this could be tackled.

One would be an analog to the vim `opfunc` method. Let us define a `movefunc` method, which is called when the motion needs to be evaluated. It could just return a range `{start, end}`.

The other way would be to introduce something like `nvim_win_motion(callback)` to register a function performing a move.

**Thoughts**
I'd love to have a way to define by scripting to behave in the same way as those written in C. Vim is all about motions, I'm honestly a bit surprised that this has not been a thing for years already, back in old vim times. I hope neovim can improve upon this.

**Comment by vypxl** [comment]
Related issue in the nvim-various-textobjs:
https://github.com/chrisgrieser/nvim-various-textobjs/issues/7

**Comment by ii14** [comment]
There is `:omap`. And you can use command line as a motion and it's repeatable, for example `d:call search('x')<cr>`.

**Comment by vypxl** [comment]
I see I didn't realize you could use ex commands as a motion.
That should solve it. Thank you!!

For anyone running into this problem, here's what solved it for me:

```lua
vim.keymap.set("", "<Plug>(spider-motion-w)", '<cmd>lua require("spider").motion("w")<CR>')
vim.keymap.set({ "n", "o", "x" }, "w", "<Plug>(spider-motion-w)")
```

You could skip the `<Plug>` mapping, but I included it as I think it looks cleaner.
Key insight: **Do not use a plain lua function in the mapping**, that will not work with dot repeat. If you use `<cmd>` to call your function that does the movement via a command line command, then it will work with dot repeat. By mapping it for operator-pending mode as well, it also works with operators like delete and change.

It is weird tho that mapping to a function doesn't work, but calling a function via command line does..
