### ISSUE TITLE
Ability to turn of highlight-spell

### ISSUE THREAD

**Issue by AckslD** [neovim/neovim#22855]
### Problem

As documented in #20864, `:h treesitter-highlight-spell` can mess up highlighting. This seems to go beyond only language injection. For example look at the two screen shots below, where the only difference is that the first has `:set spell` and the second `:set nospell`. Notice in particular the f-string, but also the difference between the decorator and keywords.

![gscreenshot_2023-04-01-095510](https://user-images.githubusercontent.com/23341710/229304211-ed0aabb2-94bf-419f-b8a7-458181015846.png)

![gscreenshot_2023-04-01-095522](https://user-images.githubusercontent.com/23341710/229304219-63f637b3-7a6b-4a45-b1da-58965b2433d8.png)

With this I don't mean the use of `@nospell` capture. Since this seems to happen regardless. For the above I copied the `highlights.scm` file from `nvim-treesitter` and removed any `@spell` capture but I still see this behaviour.

Setting `:set nospell` works to get the highlighting I expect but I would still like to have normal spell checking, even if it's not limited to treesitter regions.

I'm happy to help out with any implementation and discussions but just wanted to first see if anyone has some thoughts if this could be a reasonable thing to be able to completely disable highlight-spell?

### Expected behavior

See above

**Comment by clason** [comment]
Please try to reproduce with `nvim --clean` and no plugins.

**Comment by lewis6991** [comment]
Why is this reported as an enhancement and not a bug?

**Comment by AckslD** [comment]
> Please try to reproduce with nvim --clean and no plugins (and with the latest master). I cannot reproduce your original issue.

I see, I'll try again on latest master. Do you by any chance know if you could reproduce the original issue when I opened it?

> Why is this reported as an enhancement and not a bug?

Sorry if this was wrong. My thinking was that #20864 was the bug and this was an enhancement to disable it.

**Comment by AckslD** [comment]
I also cannot reproduce with the same config in #20864, I'll work on a new minimal config.

**Comment by AckslD** [comment]
I managed to reproduce finally again with minimal config and updated #20864

**Comment by lewis6991** [comment]
I'm struggling to grok this issue. What is the reproducer?

**Comment by clason** [comment]
@lewis6991 I believe this is the same issue as https://github.com/neovim/neovim/issues/23153, which contains a very concise minimal reproducer.

**Comment by AckslD** [comment]
This was a feature request for an ability to disable spellsitter due to #20864 #23153. Feel free to close it that doesn't make sense
