### ISSUE TITLE
issue with vim-fugitive patch command

### ISSUE THREAD

**Issue by pacuna** [neovim/neovim#2285]
the plugin works fine for me except when I try 'add -p' on a file in the status preview window (using p).
The git session for patching starts, and disappear immediately, returning to the status window. 

anyone else having this issue?

Thanks!

**Comment by Pyrohh** [comment]
See #1496, specifically this https://github.com/neovim/neovim/issues/1496#issuecomment-80689005 (ideally that issue could have a better name).

**Comment by pacuna** [comment]
thanks @Pyrohh !

**Comment by justinmk** [comment]
@Pyrohh updated the title
