### ISSUE TITLE
something wrong with luaeval()

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#22863]
### Problem

when use luaeval() to get the lua value, can not change the value.

### Steps to reproduce

create two files:

1. `autoload/testl.vim`

```vim
function! testl#test() abort
  return luaeval('require("testluaeval").test()')
endfunction
```

2. `lua/testluaeval.lua`

```lua
--!/usr/bin/lua

local M = {}


function M.test() -- {{{
  local a = {}
  a.t = true
  function a.change_t() -- {{{
    a.t = false
  end
  return a
  -- }}}
end
-- }}}


return M

```

3. run following command:

```
let wsd = testl#test()
call wsd.change_t()
echo wsd.t
```

you will see `v:true`, but it should be `v:false`

4. it works well in lua:

```
lua wsd = require('testluaeval').test()
lua wsd.change_t()
lua print(wsd.t)
```

then it works well, and you will see `false` printed.

### Expected behavior

in the reproduce step 3,  `echo wsd.t` should be `v:false`.

### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

win 11

### Terminal name/version

neovim-qt

### $TERM environment variable

empty

### Installation

release page

**Comment by bfredl** [comment]
We don't have bindeval for tables. related: https://github.com/neovim/neovim/issues/1898 .

A workaround for your usecase might be to return both setter and a getter functions (closures are bound).

**Comment by wsdjeg** [comment]
no, the main logic function is in lua, currently the `change_t` fucntion do not change the value of `a.t` in lua. for example:


```
local M = {}


function M.test() -- {{{
  local a = {}
  a.t = true
  function a.change_t() -- {{{
    a.t = false
  end
  function a.main()
      if not a.t then
          print(1)
      end
  end
  return a
  -- }}}
end
-- }}}


return M

```


with this function, if I run `change_t` function in vimscript, `print(1)` will nevel called.

**Comment by bfredl** [comment]
are you sure? it works for me. check `:messages` in case the printed message got lost.

**Comment by wsdjeg** [comment]
sorry, I will test it. but I do not know it does not work in my plugin:

https://github.com/wsdjeg/SpaceVim/blob/41095b0fe2daf1bbeded671a7d8f2d35b87d6471/lua/spacevim/logger.lua#L132

**Comment by wsdjeg** [comment]
I have test with following code.

```lua
local M = {}


function M.test() -- {{{
  local derive = {
    _debug_mode = false,
  }

  function derive.debug(msg)
    if derive._debug_mode then
      print(msg)
    end
  end
  function derive.start_debug()
    derive._debug_mode = true
  end
  function derive.stop_debug()
    derive._debug_mode = false
  end
  return derive
end
-- }}}


return M

```

```
let wsd = testl#test()
call wsd.start_debug()
call wsd.debug('hello')
```

and it works ok, you will see `hello` printed in cmdline. but I do not know why it does not work in my plugin. the code is:

```lua
function M.derive(name)
  local derive = {
    origin_name = logger.get_name(),
    _debug_mode = false,
    derive_name = fn.printf('%' .. fn.strdisplaywidth(logger.get_name()) .. 'S', name),
  }

  function derive.info(msg)
    logger.set_name(derive.derive_name)
    logger.info(msg)
    logger.set_name(derive.origin_name)
  end
  function derive.warn(msg)
    logger.set_name(derive.derive_name)
    logger.warn(msg)
    logger.set_name(derive.origin_name)
  end
  function derive.error(msg)
    logger.set_name(derive.derive_name)
    logger.error(msg)
    logger.set_name(derive.origin_name)
  end

  function derive.debug(msg)
    print(1)
    if derive._debug_mode then
      print(msg)
      logger.set_name(derive.derive_name)
      logger.debug(msg)
      logger.set_name(derive.origin_name)
    end
    print(3)
  end
  function derive.start_debug()
    derive._debug_mode = true
  end
  function derive.stop_debug()
    derive._debug_mode = false
  end
  return derive
end

return M
```

with this code, when run debug(msg), only `1` and `3` is printed.

**Comment by wsdjeg** [comment]
@bfredl thanks, I fixed it in my plugin. as a workaroud for this is:

change the lua code in step2 to:

```lua
local M = {}


function M.test() -- {{{
  local a = {}
  a.t = true
  function a.change_t() -- {{{
    a.t = false
  end
  function a.get_t() -- {{{
    return a.t
  end
  -- }}}
  return a
  -- }}}
end
-- }}}


return M

```

and in step 3:

```
let wsd = testl#test()
call wsd.change_t()
echo wsd.get_t()  " use get_t() function instead of value.
```
