### ISSUE TITLE
system() without output does not set string value / E777

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2286]
TEST CASE:

    :cexpr system("")

RESULT:

    E777: String or List expected

The same happens when assigning it to a variable first.

`:cexpr system("").""` works.

This is a regression from Vim, where it's handled correctly.

I would guess that `tv->vval.v_string` is NULL in this case ([ref](https://github.com/neovim/neovim/blob/9d02e5b984bb540567766941cff4d03f0b6e1837/src/nvim/quickfix.c#L3456-3457)).

**Comment by splinterofchaos** [comment]
What happens for you with vim? When I try `system('')` in vim, it spits out `E484: Can't open /tmp/...`.

In any event, I think we can be a little more permissive by just setting `tv.vval.v_string = ""` and `v_type = VAR_STRING` if either `v_string` or `v_list == NULL`.

**Comment by splinterofchaos** [comment]
Nevermind that, I got distracted. In vim, `:cexpr system('exit')` works, but not in nvim for the reasons you say. Trivial fix:
```patch
diff --git a/src/nvim/eval.c b/src/nvim/eval.c
index 3b1b034..ad72db4 100644
--- a/src/nvim/eval.c
+++ b/src/nvim/eval.c
@@ -14849,6 +14849,8 @@ static void get_system_output_as_rettv(typval_T *argvars, typval_T *rettv,
     if (retlist) {
       // return an empty list when there's no output
       rettv_list_alloc(rettv);
+    } else {
+      rettv->vval.v_string = xstrdup("");
     }
     return;
   }
```

**Comment by blueyed** [comment]
#2321 seems to be similar, with regard to how `let foo=$FOO` is handled.
