### ISSUE TITLE
Switching spelllang option doesn't always change the dictionary, where new words are saved

### ISSUE THREAD

**Issue by MagnetizedFreckles** [neovim/neovim#22868]
### Problem

In my workflow I have to use three different languages – English, Russian and Ukrainian.
For that I have a simple lua script in my config, which toggles the spelllang option according to keymap. It has options:
- English/Russian
- Russian/English
- English/Ukrainian
- Ukrainian/English

The in which languages are specified is important, because when you do `zg` or any similar motion, it adds word to the dictionary of the first language in the option. Reasonable enough.
And that worked for me for quite a while.
However, today I noticed that when I do `zg` with one of the languages as first one, then change the "main" spellcheck language to another, words with `zg` are still added to the language, which was set when this motion was first used.
The only way to change the dictionary, to which the word is added, is to restart neovim on the file. And if you want the dictionary for new words again, well, restart again.

### Steps to reproduce

nvim
:set spell
:set spelllang=en
zg (you will see a message that word is added to somewhere like */en.utf-8.add)
:set spelllang=ru (or any other)
zg (you will still see that word is added to */en.utf-8.add, despite the lang being changed)

And you will see that words are still being added to English dictionary. Or whatever dictionary was specified when first word addition was done.

### Expected behavior

Words are just added to the dictionary of first language specified in spelllang.
And if the spelllang option changes, so does the dictionary.

### Neovim version (nvim -v)

0.8.3 (release)

### Vim (not Nvim) behaves the same?

yes, behaves exactly the same (vim 9.0.1420-1)

### Operating system/version

Garuda Linux (Arch-based distribution)

### Terminal name/version

wezterm 20230326.111934.3666303c-1, with tmux. Also tested without it, and on Konsole and Alacritty.

### $TERM environment variable

xterm-256color

### Installation

Arch community repository

**Comment by zeertzjq** [comment]
`zg` sets 'spellfile', so you need to also change the value of 'spellfile'.
