### ISSUE TITLE
vim.lsp.buf.rename does nothing if the input is edited via cmdwin

### ISSUE THREAD

**Issue by WhyNotHugo** [neovim/neovim#22886]
### Problem

If I use `cmdwin` to edit the input provided to `vim.lsp.buf.rename`, the rename operation does nothing.

I've tried this with two LSPs (ruff and rust_analyzer).

### Steps to reproduce

You'll need _some_ LSP configured

1. Position the cursor over some function.
2. `:lua vim.lsp.buf.rename()`
3. `C-f`.
4. Edit a new name

The rename operation does nothing.

### Expected behavior

Rename should work as usual

### Neovim version (nvim -v)

NVIM v0.8.3

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Linux 6.2.8-0-edge x86_64 Linux

### Terminal name/version

foot version: 1.13.1 +pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Installation

Alpine aports

**Comment by WhyNotHugo** [comment]
Odd, I can't imagine anything LSP-specific interfering here. I can repro with `sumneko_lua`.

**Comment by justinmk** [comment]
Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by clason** [comment]
And make sure to have a minimal reproducing example (with `nvim --clean`, and no plugins -- you can and should use `vim.lsp.start` to configure the server).

**Comment by WhyNotHugo** [comment]
I'll produce reproduction instructions that include creating an environment when it happens and report back.
