### ISSUE TITLE
"make test" is should be executed in `LANG=C` environment.

### ISSUE THREAD

**Issue by Shougo** [neovim/neovim#2289]
I tested "make test" in my(Japanese) environment.

```
Failure → ...hougo/src/neovim/test/functional/autocmd/tabnew_spec.lua @ 10
TabNew au TabNew with * as <afile> matches when opening any new tab
...hougo/src/neovim/test/functional/autocmd/tabnew_spec.lua:13: Expected objects to be the same.
Passed in:
(string) '
tabnew:3:2
"test.x" [新ファイル]'
Expected:
(string) '
tabnew:3:2
"test.x" [New File]'

stack traceback:
	...hougo/src/neovim/test/functional/autocmd/tabnew_spec.lua:13: in function <...hougo/src/neovim/test/functional/autocmd/tabnew_spec.lua:10>
```

It prints errors like this.
I think the tests should be executed in `LANG=C` environment.
I should change wiki testing instructions?

https://github.com/neovim/neovim/wiki/Building-Neovim

**Comment by Pyrohh** [comment]
I wonder if this will cause issues with tests containing non-ASCII characters...

**Comment by Shougo** [comment]
Because, it compares system messages...

**Comment by Pyrohh** [comment]
> Because, it compares system messages...

I know, but I thought that if we ran the tests with LANG=C then we would unprintable characters whenever we ran tests that require nvim to parse UTF-8 chars, although that might be wrong.

**Comment by justinmk** [comment]
@Shougo If LANG=C fixes the issue for you then feel free to update the wiki.

**Comment by Shougo** [comment]
OK.  I have updated.
