### ISSUE TITLE
incsearch for user defined commands

### ISSUE THREAD

**Issue by IndianBoy42** [neovim/neovim#22893]
### Problem

This would make it possible to replicate the functionality of `/?`+incsearch+hlsearch as user command. More importantly this would also make it possible to implement different versions of the search command with the same user experience of incremental search and highlighting in the buffer. For example a search command that only goes to lsp symbols or treesitter locals, or a fuzzy searching mode, or anything else a user or plugin author may want to search by.

As it stands these alternate searching modes generally rely on something like telescope and floating windows to visualize the results. The alternative is to manually implement highlighting, moving the window and capturing input keypresses completely from scratch, a complex and error-prone task.

### Expected behavior

My initial idea is to augment the cmdpreview callback with a `win`/`wins` argument which the callback can use for `nvim_win_set_cursor` (or anything else that would change the windows view), and maybe even `nvim_win_set_buf` to change the buffer that the window is looking at. These changes would be shown to the user but undone if the cmdline is cancelled, just like the buffer changes and highlights from the existing preview callback.

**Comment by clason** [comment]
We already have `inccommand` for user commands at home? Why is that not enough?

**Comment by IndianBoy42** [comment]
Can you move the cursor from the command preview callback? In such a way that automatically returns the cursor if the cmdline is cancelled, the same way the edits/highlights are removed? I'm sorry if this is actually already handled correctly, if it is then perhaps the documentation could be clarified in terms of what actions can be made (and will be undone automatically)

**Comment by clason** [comment]
@famiu

**Comment by famiu** [comment]
> Can you move the cursor from the command preview callback? In such a way that automatically returns the cursor if the cmdline is cancelled, the same way the edits/highlights are removed? I'm sorry if this is actually already handled correctly, if it is then perhaps the documentation could be clarified in terms of what actions can be made (and will be undone automatically)

yes, cursor is automatically reset after preview

**Comment by IndianBoy42** [comment]
[After preview ends, Nvim discards all changes to all buffers made during the
preview and clears all highlights in the preview namespace.](https://github.com/neovim/neovim/blob/9d5cbd1b15e9e4da50a7295f6d104fcdbe477f88/runtime/doc/map.txt#L1550)

I don't think this is really that clear that cursor/window changes will be restored. AFAIK cursors are a change to the window, not the buffer.

**Comment by famiu** [comment]
> [After preview ends, Nvim discards all changes to all buffers made during the preview and clears all highlights in the preview namespace.](https://github.com/neovim/neovim/blob/9d5cbd1b15e9e4da50a7295f6d104fcdbe477f88/runtime/doc/map.txt#L1550)
> 
> I don't think this is really that clear that cursor/window changes will be restored. AFAIK cursors are a change to the window, not the buffer.

Fair point. It should be a fairly simple doc change so PR would be welcome if you're willing to contribute. If you have any further inquiries regarding what is and isn't reset during inccommand, feel free to ask

**Comment by IndianBoy42** [comment]
I think I will write up a PR within the next day or so, is there anything besides buffer state, window state (and tabpage state?) that should be mentioned?

**Comment by famiu** [comment]
> I think I will write up a PR within the next day or so, is there anything besides buffer state, window state (and tabpage state?) that should be mentioned?

For buffers Neovim resets:
- All undo-related information (so you can't get to the buffer states that occur due to the preview by undo'ing). To see what these include, just see the output of the `undotree()` function in Neovim, everything in it is reset.
- The `modified` flag (should be self-explanatory)
- `b:changedtick`

For windows Neovim resets the cursor position.

Neovim does not reset anything tabline related.

Additionally, Neovim resets the following things for implementation reasons. Note that these are not covered by the inccommand interface and are reset purely for the implementation, so anything that uses inccommands shouldn't rely on these:
- The `undolevel` option for buffers.
- The `cursorline` and `cursorcolumn` options for windows.

**Comment by IndianBoy42** [comment]
> For windows Neovim resets the cursor position.
> 
> Neovim does not reset anything tabline related.

Would it be possible to also save+restore the shown buffer of the window? so we could call `nvim_win_set_buf` from the preview callback. The window layout and shown tabpage might potentially be useful too

**Comment by famiu** [comment]
> > For windows Neovim resets the cursor position.
> > Neovim does not reset anything tabline related.
> 
> Would it be possible to also save+restore the shown buffer of the window? so we could call `nvim_win_set_buf` from the preview callback. The window layout and shown tabpage might potentially be useful too

what would be the usecase for that?

**Comment by IndianBoy42** [comment]
A command preview might want to switch to another buffer or tab. Like for a command that allows you to navigate to a symbol/definition in all buffers/files. Or other global search style commands 

I'm also imagining a `GotoDefinition` command that would show you the definition before hitting enter, so you could hit esc to go back.

For window layout, there's probably use cases for popping up floating windows to show the preview for whatever that command is doing. It would make sense for commands where the action isn't what it's doing to the visible buffer but something else entirely

**Comment by famiu** [comment]
> A command preview might want to switch to another buffer or tab. Like for a command that allows you to navigate to a symbol/definition in all buffers/files. Or other global search style commands
> 
> I'm also imagining a `GotoDefinition` command that would show you the definition before hitting enter, so you could hit esc to go back.
> 
> For window layout, there's probably use cases for popping up floating windows to show the preview for whatever that command is doing. It would make sense for commands where the action isn't what it's doing to the visible buffer but something else entirely

Make a separate GitHub issue for that and we can talk about it there.
