### ISSUE TITLE
easy mode for neovim

### ISSUE THREAD

**Issue by shrkamat** [neovim/neovim#22897]
### Problem

vim supports easy mode aka `evim`. I see #1656 removed this, however it's a good to have feature. Especially with LSP inbuilt into noevim it can help with easy transition from other editors. I see lot of potential with easy mode for people to experience power of neovim (mainly LSP) without bein overwhelmed with modal editor concepts.

### Expected behavior

Please support easy mode with neovim.

**Comment by clason** [comment]
The decision to remove this has not changed; all the arguments still apply.
