### ISSUE TITLE
`complete_info()` returns incorrect index with behavior that depends on `completeopt`

### ISSUE THREAD

**Issue by d-r-a-b** [neovim/neovim#22892]
### Problem

`vim.fn.complete_info` returns incorrect index programmatically, preventing plugins like `nvim-cmp` from being able to work with native `pumenu` properly. There is some subtle change in behavior depending at least on if `completopt` includes `noselect`.

See hrsh7th/nvim-cmp#1326 for more context on how this bug was discovered

### Steps to reproduce

- Save this file as `neovim_complete_info_vimrc`
  ```vim
  set completeopt=menu,preview
  nmap \\ iaaa<CR>bbb<CR>ccc<CR>ddd<CR>eee<CR>fff<CR>
  imap , <cmd>put =execute('lua print(vim.fn.complete_info({''selected''}).selected)')<CR>
  ```
- `vim --clean -u neovim_complete_info_vimrc`
- normal mode `\\`, which is nmapped to give
  ```
  aaa
  bbb
  ccc
  ddd
  eee
  fff
  ```
  and will put you in insert mode on a newline
- insert mode `<C-X><C-L>` to open lines `pumenu`
      - with default `completeopt=menu,preview` will select "fff"
- insert mode `<C-P>`, to navigate up the list once
      - selecting "eee"
- insert mode `,,,,`, imapped to `put` into the buffer the value of `complete_info` index
      - The `,` was hit multiple times so that the `complete_info` index isn't hidden behind the `pumenu` and you can see the value of the index

**BUG: The inserted index value is `1` when it should be `4`**

The bug behavior is that index counts from the bottom instead of from the top. On it's own, this would be behavior that could be worked around. However, the actual index behavior depends on `completeopt` value. 
- `completeopt=menu,preview`
      - behavior describe above
- if `completeopt=menu,preview,noselect`, then the indexing shows 2 divergent behaviors
      - navigate `pumenu` with `<C-N>` first --> you get the expected index
      - navigate `pumenu` with `<C-P>` first --> you get the reversed index (counting from bottom instead of top), acting like the `menu,preview` case

### Expected behavior

Hitting `,` should insert `4` from it's call to `vim.fn.complete_info({'selected'}).selected`

### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui

### Vim (not Nvim) behaves the same?

yes, requires a modified non-Lua vimrc. Will provide vimrc below

### Operating system/version

Arch LInux, via WSL2 on Win11

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

system package manager (pacman)

**Comment by d-r-a-b** [comment]
Config to repro with vim instead of neovim

```vim
set completeopt=menu,preview
set cpoptions-=<
nmap \\ iaaa<CR>bbb<CR>ccc<CR>ddd<CR>eee<CR>fff<CR>
imap , <Cmd>put =complete_info(['selected'])['selected']<CR>
```

<details>
<summary>VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar 21 2023 20:51:42) [expand to see full version info]</summary>

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar 21 2023 20:51:42)
Included patches: 1-1420
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       +tcl/dyn
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl/dyn          +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby/dyn          +wildignore
+cursorbind        +lua/dyn           +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        +mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/vim/src=/usr/src/debug/vim -flto=auto -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.36/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -L/usr/local/lib -o vim -lm -ltinfo -lelf -lacl -lattr -lgpm -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.36/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -fstack-protector-strong -L/usr/local/lib -L/usr/lib/perl5/5.36/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm
```
</details>

**Comment by d-r-a-b** [comment]
Is there coordination between the vim and neovim projects with respect to issue tracking? Seeing the label `needs:vim-patch` makes me think I should file an issue with `vim/vim` but I also don't want to create unnecessary issue spam if `vim/vim` contributors already look at `needs:vim-patch`.

From the perspective of the `neovim/neovim` developers, should I file a new issue in `vim/vim` for this?

**Comment by clason** [comment]
>  vim/vim contributors already look at needs:vim-patch.

They do not. If you can reproduce this with Vim, opening an issue there would be appreciated.
