### ISSUE TITLE
regression: winhl=xx:yy ignored when yy was cleared

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#22906]
### Problem

When setting `Normal` highlights for a floating window, the window shows `Pmenu` highlight. I used `git bisect` to see that this started at d879331 (cc @bfredl).

### Steps to reproduce

```
nvim --clean example.vim
```

Add the following code, which opens a floating window and sets its highlighting to `Normal`:

```vim
let buf = nvim_create_buf(v:false, v:true)
let popup = nvim_open_win(buf, 0, {
      \   'relative':  'editor',
      \   'row':       15,
      \   'col':       5,
      \   'width':     20,
      \   'height':    5,
      \   'focusable': v:false,
      \   'style':     'minimal',
      \   'border':    'single',
      \ })
call setwinvar(popup, '&winhighlight', 'Normal:Normal')
```

Source the code.

```
:source %
```

A floating window with `Pmenu` highlighting appears.

![actual](https://user-images.githubusercontent.com/541289/230238236-4d21cfdc-a646-48e2-a2dc-5f6872794beb.png)

### Expected behavior

A floating window with `Normal` highlighting would appear. Here's an example using an earlier version of Neovim, 0.7.2.

![expected](https://user-images.githubusercontent.com/541289/230238308-5a7d18d2-092d-4996-acc5-4014875abb24.png)

### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Kubuntu 22.10

### Terminal name/version

Konsole 22.08.2

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by dstein64** [comment]
The issue can be observed when using [context.vim](https://github.com/wellle/context.vim). The context floating window sets its highlight to `Normal` which used to display in a way that matches an ordinary window, but now takes on `Pmenu` highlighting.

**Comment by glepnir** [comment]
try change `NormalFloat` color see what happen.

**Comment by dstein64** [comment]
@glepnir, here's the result with `NormalFloat` (Neovim 0.8.0 on the left and 0.7.2 on the right).

![normal_float](https://user-images.githubusercontent.com/541289/230251294-dd726449-6e06-4e43-a05a-bad09bd4864b.png)

**Comment by glepnir** [comment]
`NormalFloat` link to `Pmenu` in default don't set the winhighlight just change `NormalFloat` background .I think it should work

**Comment by zeertzjq** [comment]
Hmm, `NormalFloat:Normal` behaves the same as `Normal:Normal` in both cases.

**Comment by glepnir** [comment]
I got this in my plugin before then I do something like this way to change it and it works.

```vim
set termguicolors
let buf = nvim_create_buf(v:false, v:true)
let popup = nvim_open_win(buf, 0, {
      \   'relative':  'editor',
      \   'row':       15,
      \   'col':       5,
      \   'width':     20,
      \   'height':    5,
      \   'focusable': v:true,
      \   'style':     'minimal',
      \   'border':    'single',
      \ })
let ns = nvim_create_namespace('TestWin')
call nvim_win_set_hl_ns(popup, ns)
call nvim_set_hl(ns,'NormalFloat', { 'background': 'red'})
```

**Comment by dstein64** [comment]
@glepnir, in your example the background is set specifically to red. In the scenario where I encountered this issue, the intent is to have the floating window styled like an ordinary window without knowing the actual color, but rather just that `Normal` highlighting is used.

**Comment by glepnir** [comment]
you can get normal color by using `nvim_get_hl_by_name` and set it to `NormalFloat`  in this `ns` ?

```vim
let palette = nvim_get_hl_by_name('Normal', v:true)
call nvim_set_hl(ns, 'NormalFloat', { 'background' : palette.background }
```

**Comment by dstein64** [comment]
`nvim_get_hl_by_name('Normal', v:true)` returns `{}` for me (using `nvim --clean`). Perhaps this relates to why `call setwinvar(popup, '&winhighlight', 'Normal:Normal')` is not working as expected. `:highlight` reports `Normal` as being cleared.

**Comment by dstein64** [comment]
It appears that the following workaround results in the desired behavior (`Normal` highlighting in the floating window). Thanks for the help @glepnir!

```vim
let ns = nvim_create_namespace('TestWin')
call nvim_win_set_hl_ns(popup, ns)
call nvim_set_hl(ns, 'Normal', {})
```

**Comment by glepnir** [comment]
when create floatwindow there will set the `NormalFloat` id to the float normal attr.  setwinvar  will changed the `w_hl_attr_normal` but it not redraw screen looks like?  IDK then. 

https://github.com/neovim/neovim/blob/fd32a987520cb132455d61301467182cb58cddf2/src/nvim/highlight.c#L354-L356

**Comment by nyngwang** [comment]
@glepnir @dstein64 Out of curious is this issue related to this one? #21448

**Comment by bfredl** [comment]
`hl_def[HLF_COUNT]` (local value of Normal) needs to be nonzero when it is explicitly set to be empty, looking into a fix #22910

**Comment by dstein64** [comment]
> "Out of curious is this issue related to this one?"

@nyngwang, my guess is that they're not related. The reason I think this is because the issue reported here is present on Neovim 0.8.0, but not on version 0.7.2. For the issue you reported, I observe the same behavior on both 0.8.0 and 0.7.2. If that issue were related to this one, I'd expect the behavior to change across versions in a similar manner.

**Comment by dstein64** [comment]
Thanks @bfredl!
