### ISSUE TITLE
Use travis_retry for Travis

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2290]
`travis_retry` will help with e.g. apt-get timing out etc.
See http://blog.travis-ci.com/2013-05-20-network-timeouts-build-retries/

It can be added to existing commands, e.g.

    travis_retry apt-get install ...

**Comment by Shougo** [comment]
:+1:

**Comment by justinmk** [comment]
I don't think we need this, the remaining "random failures" are gcov-related and for that we should fix the root problem.
