### ISSUE TITLE
stdpath not updated as per NVIM_APPNAME 

### ISSUE THREAD

**Issue by sarvex** [neovim/neovim#22909]
### Problem

I have updated NVIM_APPLICATION variable in init.lua, as shown below. As as per the documentation 

```bash
NVIM_APPNAME					*$NVIM_APPNAME*
The XDG directories used by Nvim can be further configured by setting the
`$NVIM_APPNAME` environment variable. This variable controls the directory
Neovim will look for (and auto-create) in the various XDG parent directories.
For example, setting `$NVIM_APPNAME` to "neovim" before running Neovim will
result in Neovim looking for configuration files in `$XDG_CONFIG_HOME/neovim`
instead of `$XDG_CONFIG_HOME/nvim`.

Note: Similarly to the $XDG environment variables, when
`$XDG_CONFIG_HOME/nvim` is mentioned, it should be understood as
`$XDG_CONFIG_HOME/$NVIM_APPNAME`.
```

but the stdpath ignore the NVIM_APPLICATION name

### Steps to reproduce

```lua
vim.api.nvim_set_var('NVIM_APPNAME', 'neovim')
print(vim.fn.stdpath("data"))
```

### Expected behavior

Instead of using nvim-data, neovim should use neovim.data

### Neovim version (nvim -v)

v0.9.0-dev-1338+g9e7426718

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Windows 11

### Terminal name/version

Windows Termianl

### $TERM environment variable

xterm-256

### Installation

winget install Neovim.Neovim.Preview

**Comment by zeertzjq** [comment]
It's an environment variable.

**Comment by clason** [comment]
> setting `$NVIM_APPNAME` to "neovim" **before** running Neovim
