### ISSUE TITLE
Improve code blocks in documentation

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#22917]
### Problem

Some of the code blocks inside the neovim (and vim) documentation don't have the ending `<`.
There's also the thing about that some code blocks don't have set filetypes.

### Expected behavior

1. Add corresponding `<` to all code blocks (can be done via script)
2. Add a filetype for each code block (like `bash` for sh code blocks)

**Comment by clason** [comment]
Yes, that is deliberate:

1. ending `<` is not required by the vimdoc "spec" (i.e., the legacy Vim parser);
2. we only make such improvements to the **Neovim** help pages, not the **Vim** help pages that are taken directly from Vim as part of the runtime file updates (i.e., those that start with `VIM REFERENCE MANUAL by Bram Moolenaar`).
