### ISSUE TITLE
Expose `dgettext`/`bindtextdomain` for localization of plugins?

### ISSUE THREAD

**Issue by theHamsta** [neovim/neovim#22928]
### Problem

I was wondering whether plugins would have the need for translation via https://www.gnu.org/software/gettext/manual/gettext.html#Libraries. Neovim uses gettext to translate UI messages. Plugins usually present UI messages is English. 

I don't know whether there is interest in having translated UI messages for plugins
- Documentation via vim help files and README is completely in English. So Vim users using plugins are usually able to read English.
- Creating the translations requires a lot more maintainers. Plugins are usually maintained by small number of people
- Developer communication mostly happens in English so we often don't hear from users wishing to have more localization for plugins
- Lua plugins could ship lua binding to gettext if they really need it (too much effort for little gain?)

I've remember seeing plugins that provide bilingual documentation Chinese/English. I would like to have some discussion on this topic, because I absolutely don't know whether people would be interested in this.

### Expected behavior

`dgettext`/`bindtextdomain` could be exposed via Lua API. Plugins could then generate their own translation files and use for displaying user visible messages. Alternatives  could be
- suggesting this feature directly to github.com/vim/vim
- to expose it via `vim.api` 
- plugins could ship getopt themselves (e.g. luarock packages)
- plugins could use the C functions directly via C FFI
- plugins in general don't need translation (?)

**Comment by clason** [comment]
> Neovim uses gettext to translate UI messages

Actually, **Vim** uses `gettext` to translate UI messages. Neovim itself doesn't really officially maintain translations -- for exactly the reasons you mention, in particular the huge increase in maintenance burden.

**Comment by theHamsta** [comment]
> > Neovim uses gettext to translate UI messages
> 
> Actually, **Vim** uses `gettext` to translate UI messages. Neovim itself doesn't really officially maintain translations -- for exactly the reasons you mention, in particular the huge increase in maintenance burden.

I know. The point was whether Lua plugins would like to use Vim's gettext functionality

**Comment by justinmk** [comment]
`:help gettext(()` was added in https://github.com/neovim/neovim/commit/5568267ccb94924b9dcf7bfa5d52da0f16d161e4
