### ISSUE TITLE
Termdebug - gdb frame command does not update source window

### ISSUE THREAD

**Issue by ArnaudD-FR** [neovim/neovim#22929]
### Problem

When debugging with Termdebug some unit test using gtest, the GDB `frame` command does not update the source window to the expected source file.

After some investigation it looks like the Termdebug `s:CommOutput` receives truncated lines. For example when I update termdebug.vim to output the content of msg variable when  `=thread-selected` is found:
```vim
func s:CommOutput(job_id, msgs, event)

  for msg in a:msgs
    " remove prefixed NL
    if msg[0] == "\n"
      let msg = msg[1:]
    endif

    if s:parsing_disasm_msg
      call s:HandleDisasmMsg(msg)
    elseif msg != ''
      if msg =~ '^\(\*stopped\|\*running\|=thread-selected\)'
        echo msg."\n"                                           <-- stupid debug log here
        call s:HandleCursor(msg)
```

The line beginning with `=thread-selected` is truncated, only few bytes after are available, so it is impossible to switch correctly the source window. By the way, no more loop iteration is done and `s:CommOutput` is no more called

When I echo `msg` for each loop iteration the issue is solved... Looks like some race issue.

### Steps to reproduce

Build google test sample
```bash
g++ /usr/src/googletest/googletest/samples/sample1.cc /usr/src/googletest/googletest/samples/sample1_unittest.cc -lgtest_main -lgtest -o /tmp/out -g
```

Edit gtest sample source code
```bash
nvim /usr/src/googletest/googletest/samples/sample1.cc
```

Start debugger
```vim
:Termdebug /tmp/out
```

Add a breakpoint in Factorial function and execute program
```gdb
break Factorial
run
```

Termdebug correctly stop at right line and update source window, then try to change frame with gdb command `up` and source window is not update. Same issue with gdb command `frame 1`

### Expected behavior

Source window should move to `sample1_unittest.cc`

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.0

### Operating system/version

Ubuntu 22.10

### Terminal name/version

Terminator

### $TERM environment variable

xterm-256color

### Installation

Installed from release package

**Comment by zeertzjq** [comment]
I also sometimes get an error message when trying to reproduce this:
```
Error detected while processing function <SNR>28_CommOutput[12]..<SNR>28_HandleCursor[18]..<SNR>28_GetAsmAddr[4]..<SNR>28_DecodeMessage:                                              
line    2:
DecodeMessage(): missing quote in 
```

**Comment by zeertzjq** [comment]
I can reproduce this in a build without ASAN, but hardly in a build with ASAN, so this indeed seems to be a data race.

**Comment by zeertzjq** [comment]
Try #22950

**Comment by ArnaudD-FR** [comment]
Thanks it fixed the issue !
