### ISSUE TITLE
 -Werror is set when CI is set, which might happen in unrelated downstream builds

### ISSUE THREAD

**Issue by WhyNotHugo** [neovim/neovim#22932]
### Problem

When [upgrading the Alpine Linux pacakge to 0.9.0](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/45766), neovim fails to build on all architectures except x86_64 and s390x:

```
/builds/WhyNotHugo/aports/community/neovim/src/neovim-0.9.0/src/nvim/highlight.c: In function 'hl_combine_attr':
/builds/WhyNotHugo/aports/community/neovim/src/neovim-0.9.0/src/nvim/highlight.c:560:27: error: conversion to 'int16_t' {aka 'short int'} from 'int' may change the sign of the result [-Werror=sign-conversion]
  560 |     new_en.rgb_ae_attr &= ((~HL_FG_INDEXED)
      |                           ^
/builds/WhyNotHugo/aports/community/neovim/src/neovim-0.9.0/src/nvim/highlight.c:566:27: error: conversion to 'int16_t' {aka 'short int'} from 'int' may change the sign of the result [-Werror=sign-conversion]
  566 |     new_en.rgb_ae_attr &= ((~HL_BG_INDEXED)
      |                           ^
/builds/WhyNotHugo/aports/community/neovim/src/neovim-0.9.0/src/nvim/highlight.c:572:27: error: conversion to 'int16_t' {aka 'short int'} from 'int' may change the sign of the result [-Werror=sign-conversion]
  572 |     new_en.rgb_ae_attr &= ((~HL_FG_INDEXED)
      |                           ^
/builds/WhyNotHugo/aports/community/neovim/src/neovim-0.9.0/src/nvim/highlight.c:578:27: error: conversion to 'int16_t' {aka 'short int'} from 'int' may change the sign of the result [-Werror=sign-conversion]
  578 |     new_en.rgb_ae_attr &= ((~HL_BG_INDEXED)
      |                           ^
cc1: all warnings being treated as errors
```

The full logs [are available here](https://gitlab.alpinelinux.org/WhyNotHugo/aports/-/jobs/1005655).

### Steps to reproduce

```sh
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=MinSizeRel \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DENABLE_JEMALLOC=FALSE \
		-DENABLE_LTO=TRUE \
		-DCMAKE_VERBOSE_MAKEFILE=TRUE
	cmake --build build
```

### Expected behavior

Should build fine (or fails with the same error on all architectures).

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Linux 6.2.8-0-edge x86_64 Linux

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

n/a

**Comment by WhyNotHugo** [comment]
From the downstream merge request:

> not actually sure why it even builds on x86_64 (would be interesting), the type is int16_t always and it's getting &= with an int(enum) which should give that warning everywhere, no idea how it's avoided..

> my only guess is the compiler doesn't enable -Wint-conversion on x86_64 for -Wconversion, but that is not what is documented..

**Comment by bfredl** [comment]
Those are warnings, not errors. we only support `-Werror` for the set of warnings enabled by neovim CI not by any random C compiler / C library / C platform.

If alpine linux enables `-Werror` by itself for its specific toolchain triple, that is an alpine issue.

**Comment by bfredl** [comment]
and any c compiler which is not stone age old will figure out that doing 16-bit bit arithmetic involving only 16-bit constants is both (1) completely fine from a correctness perspective and (2) generate the optimal machine code, even if the so called "c standard" invokes faux conversions to 32-bit and back to 16-bit along the way.

**Comment by nekopsykose** [comment]
it's not enabled by itself, it's enabled because CI is set by gitlab and the cmakefiles set -Werror when CI is set

**Comment by nekopsykose** [comment]
> and any c compiler which is not stone age old  

the C compiler in this case is gcc 12.2

**Comment by bfredl** [comment]
> the C compiler in this case is gcc 12.2

> it's also not a random warning, you set -Wconversion which implies -Wint-conversion yourself: 

sounds like gcc 12.2 has introduced a bug/regression for aarch64 then? it used to trigger a lot of false warnings when doing uint16 aritmetic which was fixed at some point.

**Comment by nekopsykose** [comment]
that would be likely, yes. it fails everywhere except x86_64 and s390x, which is weird.

in any case, it's not really an actual issue to fix- Werror was only set because of ENV{CI} being present, but that is in itself fixed, so there's nothing to really do.

silencing the warning universally is possible with a few (int16_t) casts if you care about it, but it doesn't really matter :)

**Comment by bfredl** [comment]
> it's not enabled by itself, it's enabled because CI is set by gitlab and the cmakefiles set -Werror when CI is set

Tbh, this seems like the real issue. It is meant for our own CI, not to leak into the CI of any downstream project.

**Comment by nekopsykose** [comment]
> Tbh, this seems like the real issue. It is meant for our own CI, not to leak into the CI of any downstream project.  

if you want my recommendation for that specifically- i know every gitlab-ci platform sets CI, and so does woodpecker (usually used with gitea), etc. it's quite universally set when anyone is doing automated builds themselves...

so, you could either make it an arg (-DWERROR=ON, etc) and pass it in your CI scripts, or make it CI_NEOVIM and set and env in the ci args.
