### ISSUE TITLE
Windows: install has insufficient privileges after admin password

### ISSUE THREAD

**Issue by DeadRobotDev** [neovim/neovim#22933]
### Problem

Tried to update to the latest rebuild from an old nightly. It failed, stating it had insufficient privileges to access `cat.exe`, I think.

Uninstalled the previous version in case that was an issue. Still fails to install, stating it has insufficient privileges to access `C:\Program Files\Neovim`.

I believe it is related to the UAC prompt. In the nightly build, it mentions`nvim-win64.msi` in the UAC prompt. In the release build, it mentions `C:\Windows\Installer\3a5b0f68.msi`. And not always the same string.

### Steps to reproduce

1. Run nvim-win64.msi on a non-admin account.
2. Install to default location, `C:\Program Files\Neovim`.
3. At "Removing applications", it asks for admin privileges for `C:\Windows\Installer\3a5b0f68.msi`. Enter the password.
4. At "Copying new files", it says it has insufficient privileges to access the directory.

![msiexec_xNPJFCXKvN](https://user-images.githubusercontent.com/99739042/230652530-f1a30218-d0d9-4b5e-ab8b-e7592e2c1b83.png)

### Expected behavior

I enter the password for admin privileges, and it installs correctly to `C:\Program Files\Neovim`.

It worked on `NVIM v0.9.0-dev-1166+g06aed7c17`, which is the last nightly I installed before the release build.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Windows 10 Home 19045.2728

### Terminal name/version

alacritty 0.12.0 (5a728195)

### $TERM environment variable

xterm-256color

### Installation

Repo .msi

**Comment by dundargoc** [comment]
May be caused by https://github.com/neovim/neovim/pull/22856

**Comment by RomanoZumbe** [comment]
I just tried to update nvim on a windows machine and encounter this issue with the current release version
![image](https://user-images.githubusercontent.com/16334447/232692603-532542aa-79e3-4c06-a9c9-d046dca7c937.png)

**Comment by dundargoc** [comment]
Does uninstalling and then installing work?

**Comment by RomanoZumbe** [comment]
> Does uninstalling and then installing work?

It did work. Thanks!

**Comment by dundargoc** [comment]
> Thanks, this worked for me. Looks like the install location changed, correct? Is this something to look out for when updating via .msi in the future?

Not intentionally, no.

**Comment by kepplingerstephan** [comment]
Had same issue while updating on windows
![image](https://user-images.githubusercontent.com/101325292/234265601-a2c525da-148d-41f0-af0d-9a5b894dff87.png)
after deinstalling old version, installer worked

**Comment by madjxatw** [comment]
Same issue here, but no admin password asked. Old installation has been removed from the system, please advise how to fix.

**Comment by ikopysov** [comment]
Had the same issue, but there was no option to remove previous version - I was not able to find it under "Add or remove programs" menu.
Also there was no option to run it as admin user.
Compatibility settings also not available (all of them disabled).

Was able to install it using `sudo ii ".\nvim.msi"` in pwsh using `sudo` from https://github.com/lukesampson/psutils

Hope it will help someone.
