### ISSUE TITLE
Treesitter half broken after working for 1s

### ISSUE THREAD

**Issue by JosefLitos** [neovim/neovim#22956]
### Problem

After updating to `0.9` (archlinux), any TS-enabled filetypes display correctly highlighted for a short amount of time (1.5s in lua, 0.1 in cpp/c) and then break:

- working:
![image](https://user-images.githubusercontent.com/54900518/230713026-89929a39-9e83-4776-8e65-a407deb9314a.png)
- broken:
![image](https://user-images.githubusercontent.com/54900518/230713050-7ea89873-97ed-4cc1-82f3-0cfe79ffc060.png)

The `vim` highlight is the only one still working and being correctly highlighted as a variable anything other than the first word of a file that hass a `@variable` match is broken.
This affects only matches captures containing `@variable` (like `@constant` or `@field` often also have).

The issue is only in color, other effect such as `italic` or `bold` work fine (see the `M` still being italic, only without color).

The issue is not present when downgrading neovim back to 0.8.3.

### Steps to reproduce

Open your init.lua and give it a second or two.

### Expected behavior

the `@variable` capture should not make colors disappear.

### Neovim version (nvim -v)

0.9 release

### Vim (not Nvim) behaves the same?

not aplicable

### Operating system/version

ArchLinux

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

pacman

**Comment by zeertzjq** [comment]
You can disable semantic tokens
```
    |vim.lsp.buf_attach_client()|. To opt-out of semantic highlighting with a
    server that supports it, you can delete the semanticTokensProvider table
    from the {server_capabilities} of your client in your |LspAttach| callback
    or your configuration's `on_attach` callback: >lua

       client.server_capabilities.semanticTokensProvider = nil
<
```

**Comment by JosefLitos** [comment]
Why is this enabled by default when it doesn't seem to be available anywhere?
Are there any examples where lsp-side highlighting is already supported?

**Comment by clason** [comment]
It's enabled by default when it's available; that's why you're seeing it. Language servers just need a bit to launch, which is the delay you're seeing.

**Comment by JosefLitos** [comment]
but how do I work with it to highlight the things like they should be, now when the server launches, the result is the highlighting of variables just plain disappears.

**Comment by clason** [comment]
Then disable semantic tokens if you don't want them, like zeertzjq explained.

**Comment by JosefLitos** [comment]
But this doesn't explain how it works. You are saying it is working, but I am asking how to use it when it currently appears to invalidate the highlighting of variables instead of highlight them. Or what is it supposed to do, if not highlighting?

**Comment by clason** [comment]
It just has higher priority than treesitter highlighting. Please read the documentation: `:h lsp-semantic-highlight`.

**Comment by JosefLitos** [comment]
Is there a function that could be used to get the lsp-provided tokens for the variable under cursor, like in TS is `get_captures_at_cursor`?

**Comment by glepnir** [comment]
if your language server support the `semantictoken` then neovim will send the `semantictoken` request by default .the language server will parse the file and return highlight tokens . then neovim highlights these tokens use a higher priority than treesitter.  so that's why you see some highlight changed after  seconds .if you don't like it you can disable it.  you also can link some highlights of tokens to exist groups. avoid it changed .

**Comment by clason** [comment]
> Is there a function that could be used to get the lsp-provided tokens for the variable under cursor, like in TS is `get_captures_at_cursor`?

`:Inspect` will show you _all_ highlighting, including treesitter and semantic tokens. (again, the documentation is your friend: `:h news`.)

**Comment by JosefLitos** [comment]
Oh, I didn't know there are such things as `news` built into neovim itself. I tried to find some news online, but release notes had newsletter unchecked. That's really nice, thanks for the info.

**Comment by jdrouhard** [comment]
I've seen a lot of buzz here and on reddit with people being confused as to why their colors get _worse_ when the semantic tokens kick in. Might make sense to revisit the default links for `@lsp.type...` etc to point to the main `@` groups (which by default link to the main groups). Bypassing the (currently-used-for-treesitter) `@` groups in the default link hierarchy is what is causing the confusion.

All the colorschemes I've seen so far to add support for the new semantic token highlight groups simply link all of them back to the normal `@<type>` groups anyway.

**Comment by JosefLitos** [comment]
Also, it is really confusing, that some types do get linked to defaults (`@lsp.type.function`, `...method,macro`) but other don't (`parameter`,`property`,`variable`).

**Comment by JosefLitos** [comment]
Btw there seems to be lacking a way to specify priority between modifiers, which results in race conditions for highlighting, but I suppose that is already being worked on:
![image](https://user-images.githubusercontent.com/54900518/230764403-4cf8ff07-09da-4878-9f62-133cded7adba.png)
![image](https://user-images.githubusercontent.com/54900518/230764414-cd326a75-f082-4b7d-bf43-74a8404acf9c.png)

**Comment by clason** [comment]
Please read the documentation; that is what the `LspTokenUpdate` is for. And usage questions should be asked on Matrix, not on unrelated issues.
