### ISSUE TITLE
auto-session doesn't work when closing terminal

### ISSUE THREAD

**Issue by nmsobri** [neovim/neovim#22972]
### Problem

Previously on v0.8, i was using Neovim with [autosession](https://github.com/rmagatti/auto-session) and it relies on `VimLeave` event to write the session once I close Neovim.. Last time, if I quit neovim just by closing the terminal, session file will be save, but on v0.9, if I will do the same, the session file will simply not be written to the disk.. If I quit Neovim normally ( ala `:q` or `:qa` ), everything works just fine.. Is this the intended behavior on v0.8 and bug on v0.9 or otherwise

### Steps to reproduce

1. Open terminal
2. Edit file
3. Close the terminal ( don't quit vim )

### Expected behavior

When closing the terminal, session file should be save to the disk

### Neovim version (nvim -v)

NVIM v0.9.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal

### $TERM environment variable

No

### Installation

Build from repo

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by zeertzjq** [comment]
Cannot reproduce on Windows either

**Comment by zeertzjq** [comment]
Oh, I can reproduce auto-session not working now.

**Comment by zeertzjq** [comment]
This is a bug in auto-session caused by https://github.com/rmagatti/auto-session/pull/149
