### ISSUE TITLE
LSP commands TexlabBuild and TexlabForward missing in 0.9.0

### ISSUE THREAD

**Issue by gi1242** [neovim/neovim#22971]
### Problem

  I have `texlab` LSP server setup, and everything was working in 0.8.3. However, now when I upgraded to 0.9.0 I don't see the commands `:TexlabBuild` or `:TexlabForward` anymore.

  The LSP client appears to be working (diagnostics get displayed correctly, and the document builds when I save the file). But the user commands `TexlabBuild` and `TexlabForward` are gone...

### Steps to reproduce

1. Configure `texlab` LSP server
2. Open any `.tex` file.
3. Commands to build and forward search are missing. (They used to be there in 0.8.3).

### Expected behavior

Commands `TexlabBuild` and `TexlabForward` should stilll be there

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch linux 6.2.10-arch1-1

### Terminal name/version

Konsole

### $TERM environment variable

xterm-256color

### Installation

Arch repository (pacman)

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by gi1242** [comment]
Thanks. Since it worked for you I traced the problem down.

Looks like the problem was that `vim.lsp.buf.formatting` got changed to `vim.lsp.buf.format` in 0.9.0. So my `onattach` function threw an error the LSP stuff wasn't fully initialized.

The new recommended LSP config works fine; but would be nice if the user got a heads up about this. (E.g. some message saying `depreciated function` etc, instead of silently throwing an error).

**Comment by zeertzjq** [comment]
You should get a deprecation warning if you are using a v0.8, so it seems that you have somethings that prevents you from seeing deprecation warnings.

**Comment by gi1242** [comment]
I don't actually. A minimal config is

    local on_attach = function(client, bufnr)
      local bufopts = { noremap=true, silent=true, buffer=bufnr }

      vim.keymap.set('n', '<C-space>f', vim.lsp.buf.formatting, bufopts)
    end

    require('lspconfig')['texlab'].setup {
      on_attach = on_attach,
    }

Works with no depreciation warning in 0.8.3, and then in 0.9.0 my `TexlabForward` and `TexlabBuild` commands are gone...

Regardless, it WorksNow™. Thanks for your quick responses!
