### ISSUE TITLE
no parser for 'tex' language of the treesitter fold

### ISSUE THREAD

**Issue by mathjiajia** [neovim/neovim#22974]
### Problem

Error executing vim.schedule lua callback: ...local/share/nvim/runtime/lua/vim/treesitter/language.lua:94: no parser for 'tex' language, see :help treesitter-parsers
stack traceback:
	[C]: in function 'error'
	...local/share/nvim/runtime/lua/vim/treesitter/language.lua:94: in function 'add'
	...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:88: in function 'new'
	/usr/local/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
	/usr/local/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
	/usr/local/share/nvim/runtime/lua/vim/treesitter/_fold.lua:106: in function 'get_folds_levels'
	/usr/local/share/nvim/runtime/lua/vim/treesitter/_fold.lua:196: in function </usr/local/share/nvim/runtime/lua/vim/treesitter/_fold.lua:193>

### Steps to reproduce

1, save the minimal config below as repro.lua
2, nvim -u repro.lua xxx.tex (to open any latex file)
3, key 'gcc' to comment one line

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	-- add any other plugins here
	{ "numToStr/Comment.nvim", config = true },

	{
		"nvim-treesitter/nvim-treesitter",
		config = function()
			vim.opt.foldmethod = "expr"
			vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
			vim.opt.foldenable = false

			require("nvim-treesitter.configs").setup({
				ensure_installed = { "latex" },
				highlight = { enable = true },
			})
		end,
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Expected behavior

No error, just comment one line

### Neovim version (nvim -v)

NVIM v0.10.0-dev-339011f59

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.3.1

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by clason** [comment]
You need to register the `latex` parser for the `tex` filetype.

**Comment by clason** [comment]
Yep, this is an issue with `nvim-treesitter` not registering the "main filetype" for a parser. Please open the issue there.

**Comment by clason** [comment]
Or maybe a race condition. Please try to reproduce the issue without lazy.nvim.
