### ISSUE TITLE
Support Smack introduced in Vim patches 7.4.244 and 7.4.238?

### ISSUE THREAD

**Issue by glts** [neovim/neovim#2297]
You may have noticed that I've been porting patches in the ['Not merged'](http://neovim.org/doc/reports/vimpatch/) column from the bottom up.

The two oldest unported patches 7.4.244 and 7.4.238 add support for Smack. I don't know anything about Smack but a quick search tells me that it's a security module for the Linux kernel.

Is this something that needs to be supported? Sounds like something that could be out of scope for Neovim.

**Comment by Pyrohh** [comment]
Further discussion should probably be in #1253. Regarding Smack: what benefit would there be for adding it? I'm not so sure about it given that it's platform independent, but if there's a tangible benefit for Linux users then it might be worth looking into.

**Comment by glts** [comment]
Oh boy, I forgot to search the issues. I'd say this is a duplicate, closing.
