### ISSUE TITLE
Tabstop and shiftwidth settings ignored for markdown files after updating 0.8.0 to 0.9.0

### ISSUE THREAD

**Issue by davidyoung604** [neovim/neovim#23011]
### Problem

It seems that after updating to 0.9.0, tabstop and shiftwidth are now hardcoded to 4 for markdown (.md) files. I've tested with the following list of extensions, and they're all working fine: go, rb, txt, json (all are either respecting my configured values, or are defaulting to 8 when run with `--clean`).

### Steps to reproduce

`nvim.appimage-0.8.0 --clean test.md`
`:set tabstop?`
`:set shiftwidth?`

The above should return 8 for both commands. Likewise for extensions other than `.md`. It also works properly for 0.8.3 (which I wasn't using, but I just confirmed with to help narrow down when this was introduced).

The following will return 4 for both commands, but not for other extensions.

`nvim.appimage-0.9.0 --clean test.md`
`:set tabstop?`
`:set shiftwidth?`

### Expected behavior

Configured tabstop and shiftwidth values are adhered to, regardless of file extension.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

No. 8.2.4919 works fine.

### Operating system/version

Windows 10, but WSL (Ubuntu 22.04)

### Terminal name/version

Alacritty 0.12, tmux 3.2a

### $TERM environment variable

screen

### Installation

appimage

**Comment by zeertzjq** [comment]
```
MARKDOWN                                                *ft-markdown-plugin*

'expandtab' will be set by default.  If you do not want that use this: >
	let g:markdown_recommended_style = 0
```

**Comment by davidyoung604** [comment]
Sorry, but this has nothing to do with tab expansion, and running the command from the referenced documentation doesn't resolve the problem.

**Comment by zeertzjq** [comment]
Did you run it before editing a markdown file?

**Comment by davidyoung604** [comment]
My mistake. I didn't realize it wouldn't take effect immediately. Thank you for the quick response.
