### ISSUE TITLE
Extend `vim.tbl_contains` to nested tables

### ISSUE THREAD

**Issue by clason** [neovim/neovim#23024]
### Problem

As `vim.tbl_contains(table, value)` uses `table[i] == value`, it cannot be used to check for values that are itself tables. (Lua's `==` checks for identity, not equality.) Example:
```lua
foo = { { 'bar', 'baz' }}
print(vim.tbl_contains(foo, { 'bar', 'baz' })
-- false
```

This is needed, e.g., in https://github.com/neovim/neovim/pull/22784

### Expected behavior

Code snippet should return `true`, either by

1. adding a new function `vim.tbl_deep_contains` that uses `deep_equal` instead of `==`;
2. adding an `opts` table to  `vim.tbl_contains` with boolean key `deep_equal` (default `false`);
3. adding a new function `vim.tbl_contains_func` where `value` can be user-supplied predicate.
(Note that `value` can be anything, even a funcref, so we can't dispatch on type)
4. adding an `opts` table to `vim.tbl_contains` with funcref `predicate` key (in which case `value` is ignored or validated to be `nil`) -- or boolean `funcref` key in which case `value` is validated to be a funcref?

**Comment by clason** [comment]
(*Ceterum censeo*  the API is confusing, with `vim.tbl_` used for list-like tables when `vim.list_` also exists.)

**Comment by theHamsta** [comment]
Just wanted to note that in https://github.com/neovim/neovim/pull/22784 we have dictionary-like table (some state indices missing in table). This could maybe be fixed when construction the `language.inspect` table.

**Comment by clason** [comment]
Yes, `tbl_` functions should work with _all_ tables.
