### ISSUE TITLE
Multiline window titles

### ISSUE THREAD

**Issue by sassanh** [neovim/neovim#23023]
### Problem

This is how I use terminals inside Neovim:

<img width="1587" alt="image" src="https://user-images.githubusercontent.com/1270688/231188066-d4dec544-ff3a-4026-8fad-fb5dfca2d285.png">

There are 10 terminal instances associated to `<d-1>`, `<d-2>`, ... `<d-0>`.

The day floating windows were added to Neovim I implemented this with the help of a background window rendering the border and the header (at the time floating windows didn't support borders).

Over time borders have been added to floating windows and recently we have titles, so I was thinking maybe I can get rid of the background window but I noticed the title can't be multiline. So I'm suggesting adding multiline titles for similar use-cases.

We can change the title type from string to string/string array, we can add an optional title_offset with the default value of 0 or floor(title_lines / 2) too.

### Expected behavior

The expected behavior is basically the image I attached above.

**Comment by glepnir** [comment]
> We can change the title type from string to string/string array,

title not only string . it can be a `{ {title1, highlihg1} {title2, hilight2}` already support?

**Comment by justinmk** [comment]
If you want to go nuts customizing things, create a custom UI. We aren't going to keep adding zillions of options for every random use-case.

**Comment by sassanh** [comment]
I don't want to go nuts customizing things, at least not in this particular case. My intention was to bundle my terminal manager into a plugin and share it with others but its current implementation is not clean because of the background window.
