### ISSUE TITLE
Implement ctermul

### ISSUE THREAD

**Issue by johnnadratowski** [neovim/neovim#23025]
### Problem

Vim added [ctermul](https://vim-jp.org/vimdoc-en/syntax.html#:~:text=%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0%C2%A0highlight%2Dctermbg-,ctermul,-%3D%7Bcolor%2Dnr) to allow for coloring highlighted lines.  

I propose adding the same flag for highlighting.

### Expected behavior

The flag ctermul would accept a color parameter which would then be applied only to the underlined portion of the text.

**Comment by clason** [comment]
We already have this for `termguicolors` (`gui=underline, guisp=<color>`), and `guisp` also applies to `cterm` atttributes. So no new argument is needed.

**Comment by johnnadratowski** [comment]
@clason - My apologies! I was trying to get this working and was unable, so I figured it was because I couldn't find this flag in NeoVim.  It must be an issue with my configuration.

**Comment by net** [comment]
Unless I am mistaken, `guisp` doesn't support `cterm` colors. E.g., while the underlying terminal's red can be used as a foreground color with `ctermfg=1`, `guisp=1` does not work.
