### ISSUE TITLE
Support vimscript null coalescing operator  (aka falsy operator)

### ISSUE THREAD

**Issue by mraveloarinjaka** [neovim/neovim#23033]
### Problem

The null coalescing operator is not supported in vimscript.
The expression `:echo ('test' ?? 'default')` returns `E15: Invalid expression: ? 'default')`.
Will you be open to amend the vimL parser to support that operator?

### Expected behavior

The expression `:echo ('test' ?? 'default')` returns `'test'`.

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/blob/master/src/nvim/viml/parser/expressions.c is not relevant for this. What is needed is porting vim-patch 8.2.1794.

**Comment by bfredl** [comment]
ok it is needed for `i<c-r>=(foo ?? bar)` highlighting, but for actual execution (which would be the first step), we need the patch.

**Comment by mraveloarinjaka** [comment]
Sorry in advance if my question sounds dumb: I am not familiar with neovim codeline.
What do you mean by  vim-patch 8.2.1794? Is it a specific tag I should look up in the vim repository? Is it a patch available somewhere in the neovim repository that could not be merged?

**Comment by mraveloarinjaka** [comment]
never mind I just saw https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim
I should have read the doc

**Comment by zeertzjq** [comment]
It depends on several Vim9 patches.

**Comment by zeertzjq** [comment]
The patch has been merged. However it seems that the command line highlighter doesn't currently support any of the following:
- Blobs
- Method call
- Falsy coalescing operator

**Comment by zeertzjq** [comment]
I think this can be closed as the original request has been resolved.
