### ISSUE TITLE
WinBar highlights not updated properly when 'showcmdloc' is "statusline"

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#23030]
### Problem

Setting `:set showcmdloc=statusline` seems to prevent the WinBar and WinBarNC highlights from applying correctly when switching between windows.

### Steps to reproduce

1. make a tmp lua init with this:

```lua
vim.o.winbar = 'just some text to show'
vim.o.showcmdloc = 'statusline'
vim.cmd[[hi! WinBar ctermfg=black ctermbg=white]]
vim.cmd[[hi! WinBarNC ctermfg=white ctermbg=black]]
```
2. `nvim --clean -u tmp-init.lua`
3. Open several window splits and move between them

If you then do `:set showcmdloc=` the highlighting works again as intended

### Expected behavior

When cursor enters another window, the highlights for WinBar|NC update to the correct highlights

### Neovim version (nvim -v)

0.10.0 commit gf4136c9d4

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 12.6.3

### Terminal name/version

Wezterm nightly

### $TERM environment variable

wezterm

### Installation

build from repo

**Comment by craigmac** [comment]
Related to https://github.com/neovim/neovim/pull/21202 @luukvbaal

**Comment by zeertzjq** [comment]
There are two solutions here:
- Set `w_redr_status` again when showcmdloc=statusline redraws statusline while `w_redr_status` is set and the current window has a winbar, but this is also cause an extra statusline redraw later.
- Make showcmdloc=statusline redraw statusline and winbar together. This looks more consistent as statusline and winbar are redrawn together in other places.

**Comment by luukvbaal** [comment]
I think this issue may be fixed regardless of whether we want to support showing `showcmd` in `winbar` like so:
```diff
// b/src/nvim/drawscreen.c
@@ -121,6 +121,7 @@ typedef enum {
 static bool redraw_popupmenu = false;
 static bool msg_grid_invalid = false;
 static bool resizing_autocmd = false;
+static win_T *cursor_info_win = NULL;

 static char *provider_err = NULL;

@@ -828,6 +829,7 @@ void show_cursor_info_later(bool force)
       || curwin->w_topfill != curwin->w_stl_topfill
       || empty_line != curwin->w_stl_empty
       || reg_recording != curwin->w_stl_recording
+      || curwin != cursor_info_win
       || state != curwin->w_stl_state) {
     if (curwin->w_status_height || global_stl_height()) {
       curwin->w_redr_status = true;
@@ -853,6 +855,7 @@ void show_cursor_info_later(bool force)
   curwin->w_stl_topfill = curwin->w_topfill;
   curwin->w_stl_state = state;
   curwin->w_stl_recording = reg_recording;
+  cursor_info_win = curwin;
 }

 /// @return true when postponing displaying the mode message: when not redrawing
```

This makes it so that `normal_redraw()` redraws the `curwin` statusline/winbar if it has changed.

And if we do want to add `'showcmdloc' = "winbar"` it can stay isolated from statusline redraws.
