### ISSUE TITLE
Cannot build from source with latest cmake on macOS

### ISSUE THREAD

**Issue by howarddo2208** [neovim/neovim#23038]
### Problem

I'm using macOS, installed cmake with homebrew and the version is 3.26.3. When start building neovim 0.9 from source I received an error message. It seems like I need the correct version of cmake
```
mkdir -p build
touch build/.ran-deps-cmake
ninja  -C .deps
ninja: Entering directory `.deps'
[0/1] Re-running CMake...
/bin/sh: /usr/local/Cellar/cmake/3.25.1/bin/cmake: No such file or directory
FAILED: build.ninja
/usr/local/Cellar/cmake/3.25.1/bin/cmake --regenerate-during-build -S/Users/tanhopdo/Developments/neovim/cmake.deps -B/Users/tanhopdo/Developments/neovim/.deps
ninja: error: rebuilding 'build.ninja': subcommand failed
make: *** [deps] Error 1
```

### Steps to reproduce

brew install cmake

make CMAKE_BUILD_TYPE=RelWithDebInfo

### Expected behavior

be able to install from source

### Neovim version (nvim -v)

release-0.9

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.3.1

### Terminal name/version

Iterm

### $TERM environment variable

no env

### Installation

build from repo

**Comment by clason** [comment]
Did you `make distclean` first?

**Comment by howarddo2208** [comment]
> Did you `make distclean` first? (The error occurs because you have cached CMake files from a previous version; you need to clean them after every CMake update.)

Thank you, It works now.
sr, I should've read the whole build doc
