### ISSUE TITLE
Formatting sync doesn't work in neovim version 0.9.0

### ISSUE THREAD

**Issue by abhiyandhakal** [neovim/neovim#23043]
### Problem

`:lua vim.lsp.buf.formatting_sync()` doesn't format the document in neovim v0.9.0, and throws an error saying that this is a nil value.

![Screenshot_20230412_191334](https://user-images.githubusercontent.com/96732471/231474304-622f0975-8bef-46b0-a127-7e72017e5e17.png)

But the same command works in neovim v0.8.3. Here is my [neovim config](https://github.com/abhiyandhakal/nvim-config).

### Steps to reproduce

First [Packer](https://github.com/wbthomason/packer.nvim), a plugin manager for neovim needs to be installed. Then following steps need to be followed to work with my config.

Neovim 0.9.0 needs to be installed to reproduce this error.

``` working with my config
rm -rf ~/.config/nvim/
git clone https://github.com/abhiyandhakal/nvim-config ~/.config/nvim
nvim -c PackerSync -c CHADdeps
```
This will set up all the lsp. Then, you need to open a file and save it with `:w` (formatting_sync() is mapped to `:w`) or you can run `:lua vim.lsp.buf.formatting_sync()`. Then the error appears shown above appears.

### Expected behavior

It should format the document.

### Neovim version (nvim -v)

NVIM v0.9.0

### Vim (not Nvim) behaves the same?

Vim doesn't have an LSP.

### Operating system/version

Arch Linux x86_64, Kernel version 6.2.10-arch1-1

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

Arch Official Repository

**Comment by zeertzjq** [comment]
Use `vim.lsp.buf.format()` instead

**Comment by abhiyandhakal** [comment]
Thanks. Didn't know that it was deprecated. My bad :)
