### ISSUE TITLE
unclear documentation for arguments of `nvim_exec2`

### ISSUE THREAD

**Issue by gennaro-tedesco** [neovim/neovim#23044]
### Problem

With the new release `nvim_exec()` is being deprecated in favour of `nvim_exec2()`; the documentation on the argument types is however a little unclear especially because exception are being thrown if passing the same argument types as in the previous function.

Example:
```lua
vim.api.nvim_exec("echo 'hello'", true)
```
works whilst
```lua
vim.api.nvim_exec2("echo 'hello'", true)
```
excepts with
```
E5108: Error executing lua [string ":lua"]:1: Expected lua table
stack traceback:
	[C]: in function 'nvim_exec2'
```

From the man page `:help nvim_exec2`

```lua
    Parameters:  
      • {src}   Vimscript code
      • {opts}  Optional parameters.
                • output: (boolean, default false) Whether to capture and
                  return all (non-error, non-shell |:!|) output.
```
which hints towards a direction that both arguments must be lua tables, however this is not the case (only the latter must be, the former still needing to be a string). I have made it work after some trial and error, but it is unclear from the docs.

P. S. This is a pattern that exists also in other entries of the manual, namely the syntax `{arg}` sometimes is intended as a string, sometimes as table, sometimes as else. 

### Steps to reproduce

Execute `vim.api.nvim_exec2("echo 'hello'", true)` (as indicated in the paragraph above). This returns an exception and it is unclear from the manual which argument must be a table (it turns out the latter only, not the former).

### Expected behavior

The documentation explicitly states the types of the arguments to be provided.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-48+g37011bc45-Homebrew

### Vim (not Nvim) behaves the same?

not applicable to vim

### Operating system/version

macOS 13.3.1 Ventura

### Terminal name/version

iTerm2 (Version 3.4.19)

### $TERM environment variable

xterm-256color

### Installation

brew install neovim

**Comment by clason** [comment]
`opts` is _always` a table (used for keyword-args style parameters). I agree that this specific function could to with type annotations.

**Comment by clason** [comment]
No, `{...}` is the standard vimdoc format for parameters and do not have anything to do with tables (note that the API is generic and not Lua-specific)! And the documentation is autogenerated from docstrings, so these docstrings (and the documentation generator, ideally) should be improved.

**Comment by gennaro-tedesco** [comment]
Ah, I see, sorry I did not know! Thank you again for the explanation!

**Comment by justinmk** [comment]
Not actionable.

**Comment by gennaro-tedesco** [comment]
Could you expand a little on why this cannot be actionable and moreover whether there are general discussions about improving documentation that we can contribute to?
