### ISSUE TITLE
Can't set t_SI / t_EI

### ISSUE THREAD

**Issue by qstrahl** [neovim/neovim#2304]
See `:help termcap-cursor-shape`.

In xterm, the following lines should change the cursor's shape when entering/leaving insert mode:

```viml
"" change to i-beam cursor when entering insert mode
let &t_SI = "\<Esc>[5 q" 

"" change to block cursor when leaving insert mode
let &t_EI = "\<Esc>[2 q"
```

Works in vim. Has no effect in neovim; even after assignment, `set t_SI` and `set t_EI` say this:

```
E846: Key code not set: t_SI?
E846: Key code not set: t_EI?
```

I believe [this function](/neovim/neovim/blob/f28941b96d6cf69a82f6848afae1803feb530200/src/nvim/keymap.c#l707-729) and [this block](/neovim/neovim/blob/2c7e8c38e0f483cf803eb225720cd11ae370ae75/src/nvim/option.c#l2423-2425) are relevant, but I'm not familiar enough to patch this.

**Comment by Pyrohh** [comment]
Many items in the docs are not applicable anymore due to the terminal update. Regarding the cursor shape, does this work for you? https://github.com/neovim/neovim/pull/2007#issuecomment-74863439

**Comment by qstrahl** [comment]
Well, this is embarrassing.

Yup, that works for me. Thanks!

**Comment by Pyrohh** [comment]
The docs are misleading, so I don't expect anyone to figure this stuff out :)

I'm currently cleaning up the docs, and plan on dealing with the terminal ones soon, which should help clear up confusion.
