### ISSUE TITLE
[terminal-emulation] Global color scheme effects terminal buffer

### ISSUE THREAD

**Issue by moshen** [neovim/neovim#2305]
Since colorschemes are global (per #1457), this isn't really a surprise.  Though, since colorized text looks as expected in a terminal buffer, shouldn't "normal" text and backgrounds?

On the left is a terminal buffer, on the right is a normal buffer:

![nvim demo](http://i.imgur.com/3JsIjWm.png)

The background and default text colors are applied to the terminal buffer.

Term:

![term demo](http://i.imgur.com/1IBFSWw.png)

The workaround is to adjust each color scheme accordingly to work with each other.

**Comment by justinmk** [comment]
Covered by other issues.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/6597 allows per-window colorschemes.
