### ISSUE TITLE
tempname() fails when NVIM_APPNAME is set to subdirectory

### ISSUE THREAD

**Issue by Subjective** [neovim/neovim#23056]
### Problem

When `NVIM_APPNAME` contains a subdirectory, tempname() fails to return anything. For example, I store all of my nvim configs in `$HOME/nvim-profiles` and use an alias to run nvim with the the `NVIM_APPNAME` variable set. However, any plugins that rely on `tempname()` to generate a temporary directory are not able to run properly. 

Before `NVIM_APPNAME`, I just set the various `XDG_HOME` variables using the following shell script, and everything worked fine:
<details>
<summary>Shell Script</summary>

```shell
#!/bin/sh
NVIM_PROFILE_NAME=""
NVIM_COMMAND="nvim"

exec env XDG_CONFIG_HOME="$HOME/.config/nvim-profiles/${NVIM_PROFILE_NAME}" \
         XDG_DATA_HOME="$HOME/.local/share/nvim-profiles/${NVIM_PROFILE_NAME}" \
         XDG_STATE_HOME="$HOME/.local/state/nvim-profiles/${NVIM_PROFILE_NAME}" \
         XDG_CACHE_HOME="$HOME/.cache/nvim-profiles/${NVIM_PROFILE_NAME}" \
         ${NVIM_COMMAND} \
         "$@"
```

</details>

### Steps to reproduce
1. Run the following commands in terminal
```shell
cd $HOME
NVIM_APPNAME="some_directory/TestVim" nvim
```
2. execute "echo tempname()" in neovim
3. Nothing gets returned
4. Run `NVIM_APPNAME="TestVim" nvim`
5. `tempname()` returns a temporary directory path

### Expected behavior

I would expect `tempname()` to return the path to a temporary directory:

![Screen Recording 2023-04-12 at 1 50 51 PM](https://user-images.githubusercontent.com/56745535/231583265-36ff4c32-8636-46f8-bf38-a97bf2245ac3.gif)

Interestingly enough, calling the alias in the `~/.local/state` directory allows tempname() to return a directory. No clue why this happens.

![Screen_Recording_2023-04-12_at_12 39 51_PM](https://user-images.githubusercontent.com/56745535/231585641-d765b420-3350-48df-809d-aa685c78f0e7.gif)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-46+ge23c6ebed

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.3

### Terminal name/version

Kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

bob

**Comment by bfredl** [comment]
as of 0.9, `NVIM_APPNAME` only supports, well, a _name_, not a full path, which was never intended. The simplest solution would be to add a proper error message for this instead of random errors down the line, as you get now.
