### ISSUE TITLE
RFC: Add benchmarks for Neovim

### ISSUE THREAD

**Issue by vegerot** [neovim/neovim#23051]
### Problem

Neovim's [current benchmarks](https://github.com/neovim/neovim/tree/master/test/benchmark) are weak.

Not having a comprehensive set of benchmarks limits our visibility into performance regressions and places to make performance wins.

I want to use this issue as a place to begin discussing a plan to _slowly_ start adding benchmarks for Neovim's core features.

### Expected behavior

I want us to invest in basic benchmarks.  Here are some ideas on where to start benchmarking:

- neovim cold-start time with no file (`nvim`)
- neovim start time with a large file
- syntax highlighting speed
- vimscript performance
- lua API performance (a script that interacts heavily with neovim APIs)

I was disappointed by the attitude in #23028 which was (strawman)

> 🤷‍♀️ well it's probably faster so why not?

For #23028 it would have been very helpful if we just had a few basic benchmarks.  Another reason having benchmarks is nice is because it lets us highlight performance **wins**.  We cannot add an entry to [This Week in Neovim](https://this-week-in-neovim.org/) for [f4136c9](https://github.com/neovim/neovim/commit/f4136c9d42f79c0f2fe3ce6fdc22b1544593692a) because there's nothing to say.  If, on the other hand we could show that `-O3` resulted in a 5% performance increase for opening large files that would be great marketing!  We should also invest in writing comprehensive benchmarks so we can highlight performance wins to the community 🙂

**Comment by vegerot** [comment]
I have only contributed a few things to Neovim so I'm hoping to get perspective from some core neovim contributors on their thoughts as well

**Comment by clason** [comment]
What people care most about is latency and especially input lag, which is _very_ hard to measure and depends a lot on the (terminal) environment. Also, our focus is not "5% faster startup speed", as this is a losing game -- we prefer to put efforts into features and general usability improvements. (I cannot stress this enough: this is _not_ the marketing we are looking for! And the attitude in #23028 was not "it's faster" but "it removes a no longer needed workaround, i.e., removes CMake code -- which _is_ a metric we care about deeply.)

That being said, there are a few specific areas where we very much care about performance; one would be extmark drawing, the other treesitter parsing, and extending the benchmarks for those is very welcome.

**Comment by lewis6991** [comment]
Also note we have no benchmarking infrastructure, i.e., CI hosts that run code in deterministic time. So unless results are in the realm of "runs 2-3x faster on Macbook M1", such results will be hard to compare.

**Comment by vegerot** [comment]
...but honestly maybe I'm prematurely optimizing our development.  Neovim seems to be perfectly snappy even without a robust suite of benchmarks, and performance regressions are rare.

Perhaps the truth is that while benchmarks would be nice, we don't need them and they're not important

**Comment by dundargoc** [comment]
The `-O2` vs `-O3` argument is programmer's horoscope. There's little evidence that `-O3` is much buggier or much faster than `-O2`. In fact, I don't believe it's even solidly concluded it makes *any* difference on average compared to `-O2`. I would like us to spend time on measuring *real* performance benefits instead of reading tea leaves.

But yes, our benchmarking is weak and needs work :)

**Comment by vegerot** [comment]
I would argue (if I wanted to be inflammatory) that the _real_ horoscope is just _saying_ that `-O2` vs. `-O3` doesn't matter for this project without measuring anything.

However, intuition and experience does tell me that you are most likely correct.  That is why in my most recent message I considered that I am getting too worked up and that Neovim doesn't need benchmarks since it's done fine without them so far.  I guess the intuition of contributors like you is sufficient to make sure Neovim stays fast without needing to ever measure anything.

> But yes, our benchmarking is weak and needs work :)

I agree it would be better if we had better benchmarking.  However now I've sorta done a 180 on my opinion.  Does our benchmarking "need" work?  Neovim has been fast for the last decade without writing any comprehensive benchmarks

**Comment by clason** [comment]
As a wise man once said: "Concern is the mind killer." Do not doubt for a second that if and when there is a serious performance regression, Reddit will let us know in a heartbeat.
