### ISSUE TITLE
Treesitter folding error thrown when saving file

### ISSUE THREAD

**Issue by mhanberg** [neovim/neovim#23066]
### Problem

I believe this started when I switched my `foldexpr` to `v:lua.vim.treesitter.foldexpr()`.

Often times I will save a buffer and get this error. It doesn't seem to cause problems other than being annoying.

```
Error executing vim.schedule lua callback: ...neovim/nightly/share/nvim/runtime/lua/vim/treesitter.lua:116: Invalid buffer id: 23065
stack traceback:
	[C]: in function '__index'
	...neovim/nightly/share/nvim/runtime/lua/vim/treesitter.lua:116: in function 'get_parser'
	.../nightly/share/nvim/runtime/lua/vim/treesitter/_fold.lua:106: in function 'get_folds_levels'
	.../nightly/share/nvim/runtime/lua/vim/treesitter/_fold.lua:196: in function <.../nightly/share/nvim/runtime/lua/vim/treesitter/_fold.lua:193>
```

### Steps to reproduce

I will come back with a minimal repro, I just wanted to get the issue opened before I forget.

### Expected behavior

No error

### Neovim version (nvim -v)

NVIM v0.10.0-dev-24+g3c724fe1f

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 13.3

### Terminal name/version

kitty/tmux

### $TERM environment variable

alacritty

### Installation

asdf plugin add neovim; asdf install neovim nightly

**Comment by clason** [comment]
Please try to provide a minimal reproducing example (preferably using `nvim --clean` without other plugins, including nvim-treesitter; you can test with one of the bundled parsers such as Lua).

**Comment by mhanberg** [comment]
@clason i stated in the issue description I would be back with the minimal, don't worry 😄.

**Comment by mhanberg** [comment]
Hmm, I am having trouble reproducing.

The extremely high bufnr in the error makes me wonder if there is a plugin opening and deleting tons of buffers and the fold recalculation is scheduled and the buffer is deleted before that scheduled function is executed.

I'll keep fiddling.

**Comment by mhanberg** [comment]
I have begun to narrow this down.

I think it might be triggered by the [noice.nvim](https://github.com/folke/noice.nvim) plugin, but have still not narrowed it down if it's related to it's usage of vim.ui_attach or just something in the plugin itself.

**Comment by mhanberg** [comment]
I have not seen this in a while (I bump my nightly every few days) so I think it's safe to assume that it was either fixed by some commit since I opened the issue or a plug-in I used patched to not cause the error. 

Will close!
