### ISSUE TITLE
Syntax Highlighting in 0.9.0-1 for basic variable declarations, function args,  show poor contrast

### ISSUE THREAD

**Issue by tomit4** [neovim/neovim#23061]
### Problem

I have thoroughly checked whether treesitter or my particular theme was the culprit for this bug, but found out that by reverting back to 0.8.3-1 was the only way for me to solve this issue currently. I have provided a brief gif and png for your review, but basically the native syntax highlighter in 0.9.0-1 "condenses" its interpretation of various variable declarations, function arguments, etc. into one color.

Please note I did try installing a different theme and uninstalling treesitter and other syntax related plugins in an attempt to remedy this issue before rolling back my neovim installation and coming here to post this issue.

![nord_issue](https://user-images.githubusercontent.com/78219885/231683889-55800373-3d04-48b2-bff3-27cd78ef4323.png)

![nord_issue](https://user-images.githubusercontent.com/78219885/231683943-82e40b9c-8370-4877-9317-10a664e7682a.gif)

### Steps to reproduce

You can see my nvim config here:
https://github.com/tomit4/notes/tree/main/.config/nvim

### Expected behavior

The color contrast should remain as it was in the previous version.

### Neovim version (nvim -v)

0.9.0-1

### Vim (not Nvim) behaves the same?

Don't use vim, only nvim...

### Operating system/version

Artix Linux/Kernel 6.2.9-zen1-1-zen

### Terminal name/version

suckless terminal

### $TERM environment variable

st-256color

### Installation

pacman

**Comment by coockoo** [comment]
Went to help by the link above and it suggested adding

```lua
client.server_capabilities.semanticTokensProvider = nil
```

to the configuration's `on_attach` callback.

And it helped!
Thank you!
