### ISSUE TITLE
DCO (DEVELOPER CERTIFICATE OF ORIGIN)

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#2306]
Just noting this for future reference; I don't think we want to get distracted by another policy change any time soon. 

Recently I learned about [DCO](https://blog.docker.com/2014/01/docker-code-contributions-require-developer-certificate-of-origin/), a more "passive" approach to managing contribution red tape, avoiding the need for a CLA. 

Disadvantages:
- it requires some setup on the contributor's end
  - @elmart's tooling for "commit trailers" could help with this maybe
- we may need to rewrite past commit messages (not certain about this)

other reference: https://blog.chef.io/2016/09/19/introducing-developer-certificate-of-origin/

**Comment by splinterofchaos** [comment]
I don't really have a comment, but I like this idea.

**Comment by jszakmeister** [comment]
FWIW, that's what the Signoff-by trailer is for in the kernel and Git projects.  I like the idea that they label which version, though I could see headaches with that too (folks not updating the line after it's been updated, etc).
