### ISSUE TITLE
--api-info return type misleading for nvim_buf_get_extmark_by_id

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#23074]
### Problem

`nvim_buf_get_extmark_by_id` has a return type of `ArrayOf(Integer)` in the API info, but when `details` is passed the returned array contains a dictionary in the last position.

### Neovim version (nvim -v)

v0.10.0-dev-46+ge23c6ebed

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Rocky Linux 8.6

### Terminal name/version

xfce4-terminal -V

### $TERM environment variable

tmux-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
Duplicate of #21239
