### ISSUE TITLE
netrw: Errors in command window when losing focus

### ISSUE THREAD

**Issue by avimmer** [neovim/neovim#23085]
### Problem

```
Error detected while processing FocusGained Autocommands for "*"..function <SNR>
57_LocalBrowseRefresh:
line   49:
E11: Invalid in command-line window; <CR> executes, CTRL-C quits
```

### Steps to reproduce

1. `nvim --clean +:Explore`
2. Open command prompt with `:`
3. `^F`
4. Alt+Tab or lose focus in the window
5. Get back to the terminal where nvim was
6. Observe errors

### Expected behavior

No errors

### Neovim version (nvim -v)

0.9.0
0.8.3

### Vim (not Nvim) behaves the same?

Don't know.

### Operating system/version

macOS 13.2.1 (22D68)

### Terminal name/version

Terminal Version 2.13 (447)

### $TERM environment variable

xterm-256color

### Installation

Homebrew

**Comment by clason** [comment]
Please give full reproducing steps involving `nvim --clean`; I cannot reproduce the error with these steps.

**Comment by avimmer** [comment]
I have downgraded already, but if I'll get back to it could you suggest any way to debug this? I wasn't using nvim --clean. It could be some of the plugins misbehaving.

<details>
<summary>.config/nvim/init.vim</summary>

```vim
call plug#begin()
if !exists('g:vscode')
  Plug 'dense-analysis/ale'
  Plug 'embear/vim-localvimrc'
  Plug 'honza/vim-snippets'
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'sheerun/vim-polyglot'
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-vinegar'

  let g:coc_disable_transparent_cursor = 1
  let g:localvimrc_persistent = 2
  let g:localvimrc_sandbox = 0
  set synmaxcol=1000

  au BufRead *.git/COMMIT_EDITMSG setl spell
  colorscheme peachpuff
  set clipboard=unnamedplus
  set cmdheight=0
  set fillchars=vert:\ ,eob:\ ,diff:\  listchars=tab:‧\ ,eol:¬
  set noshowcmd noshowmode
  set statusline=%f\ %m
  set title
endif
Plug 'michaeljsmith/vim-indent-object'
call plug#end()
```
</details>

**Comment by clason** [comment]
> I have downgraded already, but if I'll get back to it could you suggest any way to debug this?

As I said, start with `nvim --clean`, and if that doesn't reproduce it, try creating a minimal(!) `init.vim` that will show the problem with `nvim --clean -u init.vim`.

And yes, I suspect a plugin (or, looking at your `init.vim`, `cmdheight = 0`, which is experimental and known to have issues).

**Comment by avimmer** [comment]
I was able to reproduce it in neovim v0.8.3 as well with `nvim --clean`. I have updated the steps above with
1. `nvim --clean +:Explore`
2. Open command prompt with `:`
3. `^F`
4. Alt+Tab or lose focus in the window
5. Get back to the terminal where nvim was
6. Observe errors

@clason @zeertzjq

**Comment by dundargoc** [comment]
I can recreate nightly.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/blob/36fd2fcaae757e8ac64c8ff7a66e4f480a075dcf/runtime/autoload/netrw.vim#L10957

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.
