### ISSUE TITLE
Error trying to use Netrw (Although it's still usable)

### ISSUE THREAD

**Issue by ShadowCreator** [neovim/neovim#2308]
Whenever I use :e ~/PathToFolder I get the following error

clipboard: error: Error: Can't open display: (null)                                                                                        
Error detected while processing function <SNR>20_NetrwBrowseChgDir..<SNR>20_NetrwOptionSave:
line   53:
clipboard: provider returned invalid data
clipboard: error: Error: Can't open display: (null)

I'm on a Chromebook using crouton which could explain why but it doesn't occur in Vim only Neovim.

**Comment by Pyrohh** [comment]
Does crouton use X11? I think you might have xsel or xclip installed, but there's no X server to connect to to retrieve clipboard data.

**Comment by justinmk** [comment]
I do think if we "can't open display", we should not check the clipboard again for the rest of the Neovim session.

**Comment by ShadowCreator** [comment]
@Pyrohh It can, I don't use X11 though since switching from X11 back to Chrome is annoying and using Neovim and the command line means I don't need to.

**Comment by justinmk** [comment]
Should not be a problem now.

**Comment by ViViDboarder** [comment]
I'm getting a similar issue on OSX on master HEAD.

Using a blank nvimrc file If I open a directory and try to navigate to any other directory I get:

```
clipboard: error:
clipboard: error:
```

Nothing else.
