### ISSUE TITLE
modifyOtherKeys support firing when not desired.

### ISSUE THREAD

**Issue by andrew-pickin-epi** [neovim/neovim#23091]
### Problem

Fresh install of 0.8.3 release. XFCE-terminal irrespective of `TERM` setting the buffer opens with `[>4;2m` but this is not the case on a genuine `XTerm`.
Vim allows for the disabling of this feature neovim doesn't (that I can tell).

### Steps to reproduce

`nvim -u NORC` 
Buffer appears to contain
```  
[>4;2m
```

### Expected behavior

No rogue control charaters displayed.

### Neovim version (nvim -v)

0.8.3 Debian

### Vim (not Nvim) behaves the same?

No. Vim is clean, except in some instance of pluging/statusline, but fixes with
```
"let &t_TI = ""
"let &t_TE = ""
```

### Operating system/version

ubuntu 22.04

### Terminal name/version

xfce

### $TERM environment variable

xterm-256color gnome=256-color & ansi-256color

### Installation

Debiam package

**Comment by clason** [comment]
Please test 0.9.0 (using the appimage provided on our release page, if necessary).

**Comment by zeertzjq** [comment]
XFCE terminal should ignore these control escape sequences. What does "setting the buffer opens with `[>4;2m`" mean?

**Comment by zeertzjq** [comment]
What is the value of `VTE_VERSION` environment variable?
