### ISSUE TITLE
add support to Persian ordered list in markdown parser

### ISSUE THREAD

**Issue by ekm507** [neovim/neovim#23095]
### Problem

Hi!
in markdown documents there can be ordered lists with numbers from other languages. such as Persian, Arabic, etc.
is it possible to add a support for them?

it does not support them right now:
![image](https://user-images.githubusercontent.com/13185969/232141039-14ec54b9-4ff7-4e67-8f26-b1feefb907e6.png)

below is a vim regex that matches all English, Arabic and Persian ordered list beginings which is a modified version of [this](https://github.com/neovim/neovim/blob/96cf385a7f4ab29f6987c10b5c3625d99b22f6fc/runtime/syntax/markdown.vim#L90)
```vim
^\%(\t\| \{0,4}\)\<[0-9۰-۹٠-٩]\+\.\%(\s\+\S\)\@=
```
although I know it does not support all languages. like chinese, indian and others.

also something like `\p{N}` exists in [regex](https://www.regular-expressions.info/unicode.html#prop) to match any digit from any language but I don't know how to write it in vim style.

can this feature be added to nvim?

### Expected behavior

ordered lists with Persian numbers (and hopefully numbers from any other language) should be colored.

**Comment by zeertzjq** [comment]
This issue should be reported to <https://github.com/tpope/vim-markdown>
