### ISSUE TITLE
guicursor Not Working

### ISSUE THREAD

**Issue by bray** [neovim/neovim#23094]
### Problem

I'm trying to switch from Macvim to Neovim, but running into an issue. I can't get `guicursor` to fully work. I say fully work because _some_ of it does, e.g. setting `ver25` or `hor25`, changing colors, or setting `blinkon0` to disable blinking.

But the blinking timings aren't working like they do in Macvim. In Neovim, it seems to be the same speed no matter what I try. And the `blinkwait` seems to **change** sometimes. Sometimes it waits longer than other times (you can see this when I do `o` in the demo). This gives the very annoying effect of feeling laggy.

Please see demo: <https://youtu.be/oKruKQ9CESY>

I tried iTerm2 (which I use), Terminal, and kitty - same results.

I tried setting in init.vim, CLI flag, and in nvim's command mode.

I tried the latest stable (0.9.0) and also HEAD:

```
❯ nvim --version
NVIM v0.10.0-dev-1433+gc2e47e7be-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
```

### Steps to reproduce

`nvim --clean`
`:set guicursor=i-ci-ve:ver25-blinkwait50-blinkoff50-blinkon50`

### Expected behavior

When in Insert mode, the cursor should blink in 50ms intervals.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1433+gc2e47e7be-Homebrew

### Vim (not Nvim) behaves the same?

N/A - `guicursor` isn't for terminal vim

### Operating system/version

macOS 13.2.1

### Terminal name/version

iTerm 3.4.19

### $TERM environment variable

xterm-256color

### Installation

Homebrew

**Comment by zeertzjq** [comment]
https://github.com/neovim/neovim/issues/18053#issuecomment-1094302350

**Comment by bray** [comment]
`:help 'guicursor'` says "Works in the GUI and many terminals." You can't get much more popular than iTerm2 on a mac, and you're saying it doesn't work there?  I spent way too much time trying to debug this; I agree with the commenter in the other issue that this should really be modified in help.

**Comment by glepnir** [comment]
> You can't get much more popular than iTerm2 on a mac

For now kitty wezterm better than iterm2.

**Comment by erw7** [comment]
> :help 'guicursor' says "Works in the GUI and many terminals."

See `:h tui-cursor-shape`.

> Nvim will adjust the shape of the cursor from a block to a line when in insert mode (or as specified by the 'guicursor' option), on terminals that support it. 

It is clear from the above description that the terminal must support the feature. You should examine the control sequences supported by the terminal before creating an issue on its functionality. I could only find one for [iTerm2](https://iterm2.com/documentation-one-page.html), but any decent terminal should have a documented control sequence that is supported.

> You can't get much more popular than iTerm2 on a mac, and you're saying it doesn't work there?

As far as I know, there is no terminal that has a control sequence to change the speed of the cursor blink. Therefore, no terminal should be able to use this feature.

> I spent way too much time trying to debug this; I agree with the commenter in the other issue that this should really be modified in help.

PR is welcome.

**Comment by bray** [comment]
Thanks for the response.

> As far as I know, there is no terminal that has a control sequence to change the speed of the cursor blink. Therefore, no terminal should be able to use this feature.

This is very useful info. I didn't find this anywhere in my research/debugging. I guess I'll have to go with a solid non-blinking thin bar :( Thanks.
