### ISSUE TITLE
Virtual text in indented word-wrapped area

### ISSUE THREAD

**Issue by musjj** [neovim/neovim#23108]
### Problem

When `breakindent` is enabled, plugins like [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) is unable to draw virtual text within the indentation area. This causes the rendered guidelines to be broken up:
![image](https://user-images.githubusercontent.com/72612857/232233546-a46d7da1-062c-4ac7-a8d2-2f548eb3663d.png)
Related issue: https://github.com/lukas-reineke/indent-blankline.nvim/issues/149

### Expected behavior

It should be possible to draw virtual text in the indentation area. This will make the guidelines smooth and continuous. This is how it looks when there are no word-wrapping:
![image](https://user-images.githubusercontent.com/72612857/232233806-d6d2dbe6-e225-4048-aac9-861d928d71c0.png)

**Comment by zeertzjq** [comment]
Hmm, maybe `virt_text_win_col` can be extended?

**Comment by zeertzjq** [comment]
After #23759 this is achievable using `virt_text_win_col`:
```vim
40vnew
set breakindent
call setline(1, repeat('  foo bar', 10))
let ns = nvim_create_namespace('')
call nvim_buf_set_extmark(0, ns, 0, 40, {'virt_text': [['|']], 'virt_text_win_col': 1})
call nvim_buf_set_extmark(0, ns, 0, 80, {'virt_text': [['|']], 'virt_text_win_col': 1})
```

**Comment by musjj** [comment]
Thank you!

**Comment by luukvbaal** [comment]
> After https://github.com/neovim/neovim/pull/23759 this is achievable using virt_text_win_col:

I'm not sure how useful this actually is to this end.
I don't think it is feasible for plugins to determine at which columns lines are wrapping, it depends on too many options.
Would it make sense to add a "wrap" option to the API to indicate that the virtual text should be repeated at column "start_col" for each wrapped line?

**Comment by zeertzjq** [comment]
This sounds very special-cased. And what is `start_col`?

**Comment by luukvbaal** [comment]
> This sounds very special-cased.

Indeed, I can't think of another use-case other than indentation markers but who knows.

> And what is start_col?

Just `col` I guess, the column an extmark is placed at. If we were to add a `wrap` or `repeat` option, I think it would make sense that it is repeated at column `col` relative to the start of the (wrapped) screenline.

**Comment by zeertzjq** [comment]
> Just `col` I guess, the column an extmark is placed at. If we were to add a wrap or repeat option, I think it would make sense that it is repeated at column `col` relative to the start of the (wrapped) screenline.

I don't think this makes sense. `col` is a byte index.

**Comment by zeertzjq** [comment]
Related: #19654

**Comment by luukvbaal** [comment]
Indeed, the point is that this use-case can only be handled by `win_line()` itself.
In the case of indentation markers, `col` is simply zero.
Adding an option to repeat the extmark for each wrapped line could solve this problem.

**Comment by luukvbaal** [comment]
> Adding an option to repeat the extmark for each wrapped line could solve this problem.

Any thoughts on this @zeertzjq @bfredl? I think simply not de-activating the virt text extmark results in the desired behavior:

<details><summary>Example repeated indent virt text across wrapped line</summary>

![image](https://github.com/neovim/neovim/assets/31730729/1085f5b6-fde5-4484-8063-157e759cc2fa)
</details>
<details><summary>Patch:</summary>

```diff
diff --git a/src/nvim/api/extmark.c b/src/nvim/api/extmark.c
index 14454b626..905c2f965 100644
--- a/src/nvim/api/extmark.c
+++ b/src/nvim/api/extmark.c
@@ -179,6 +179,7 @@ static Array extmark_to_array(const ExtmarkInfo *extmark, bool id, bool add_dict
       Array chunks = virt_text_to_array(decor->virt_text, hl_name);
       PUT(dict, "virt_text", ARRAY_OBJ(chunks));
       PUT(dict, "virt_text_hide", BOOLEAN_OBJ(decor->virt_text_hide));
+      PUT(dict, "virt_text_wrap", BOOLEAN_OBJ(decor->virt_text_wrap));
       if (decor->virt_text_pos == kVTWinCol) {
         PUT(dict, "virt_text_win_col", INTEGER_OBJ(decor->col));
       }
@@ -687,6 +688,7 @@ Integer nvim_buf_set_extmark(Buffer buffer, Integer ns_id, Integer line, Integer
 
   decor.hl_eol = opts->hl_eol;
   decor.virt_text_hide = opts->virt_text_hide;
+  decor.virt_text_wrap = opts->virt_text_wrap;
 
   if (HAS_KEY(opts, set_extmark, hl_mode)) {
     String str = opts->hl_mode;
diff --git a/src/nvim/api/keysets.h b/src/nvim/api/keysets.h
index 18f6d5368..9c26d673e 100644
--- a/src/nvim/api/keysets.h
+++ b/src/nvim/api/keysets.h
@@ -30,6 +30,7 @@ typedef struct {
   String virt_text_pos;
   Integer virt_text_win_col;
   Boolean virt_text_hide;
+  Boolean virt_text_wrap;
   Boolean hl_eol;
   String hl_mode;
   Boolean ephemeral;
diff --git a/src/nvim/decoration.h b/src/nvim/decoration.h
index fef5ff7c2..bbb7c8e8c 100644
--- a/src/nvim/decoration.h
+++ b/src/nvim/decoration.h
@@ -52,6 +52,7 @@ struct Decoration {
 
   // TODO(bfredl): at some point turn this into FLAGS
   bool virt_text_hide;
+  bool virt_text_wrap;
   bool hl_eol;
   bool virt_lines_above;
   bool conceal;
@@ -71,7 +72,7 @@ struct Decoration {
   bool ui_watched;  // watched for win_extmark
 };
 #define DECORATION_INIT { KV_INITIAL_VALUE, KV_INITIAL_VALUE, 0, kVTEndOfLine, \
-                          kHlModeUnknown, false, false, false, false, kNone, \
+                          kHlModeUnknown, false, false, false, false, false, kNone, \
                           DECOR_PRIORITY_BASE, 0, 0, NULL, 0, 0, 0, 0, 0, false }
 
 typedef struct {
diff --git a/src/nvim/drawline.c b/src/nvim/drawline.c
index e5d2ba755..639efdaa6 100644
--- a/src/nvim/drawline.c
+++ b/src/nvim/drawline.c
@@ -324,7 +324,9 @@ static void draw_virt_text(win_T *wp, buf_T *buf, int col_off, int *end_col, int
       col = draw_virt_text_item(buf, item->draw_col, item->decor.virt_text,
                                 item->decor.hl_mode, max_col, vcol, wp->w_p_rl);
     }
-    item->draw_col = INT_MIN;  // deactivate
+    if (!item->decor.virt_text_wrap) {
+      item->draw_col = INT_MIN;  // deactivate
+    }
     if (item->decor.virt_text_pos == kVTEndOfLine && do_eol) {
       if (wp->w_p_rl) {
         state->eol_col = col - 1;
```
</details>

In this case, indent-blankline would need to make sure to only set this flag to true if `'breakindent'` is enabled.

**Comment by zeertzjq** [comment]
`virt_text_wrap` may not be an accurate name for this, but I can't think of a better name.

**Comment by luukvbaal** [comment]
Yeah not completely accurate. Other names: `repeat`, `repeat_wrap` or `wrap_repeat`.

**Comment by Danielkonge** [comment]
Was there ever any more progress on this? If we don't need much more than an option in `nvim_buf_set_extmark` and code like what @luukvbaal wrote above, then I can look at this and make a pull request. Or is there more details still missing?

**Comment by luukvbaal** [comment]
Don't remember why I didn't get around to opening a PR for this. Just waiting for feedback from @bfredl on the patch/flag name I guess.

**Comment by Danielkonge** [comment]
> Don't remember why I didn't get around to opening a PR for this. Just waiting for feedback from @bfredl on the patch/flag name I guess.

Sounds good! For naming I think something like `repeat_when_wrapped` would be more descriptive, but I don't really care what the name is and would just like the feature. :)
