### ISSUE TITLE
Error running Vundle :PluginInstall

### ISSUE THREAD

**Issue by llimllib** [neovim/neovim#2311]
I'm not sure if this is an error with neovim or Vundle! But somebody on the IRC room said they're successfully running Vundle with nvim, so if you could tell me if the error's on your side or theirs, that would be great. I'll happily report it to them if it's theirs.

Anyway!

On neovim head 201503292107 with this version output: https://gist.githubusercontent.com/llimllib/c5bae01ad8da30b3c6dd/raw/d294d99871dc6add026aeacd0846d0d604f547d5/gistfile1.txt

and a fresh vundle checkout, I get this error:

```
Error detected while processing /Users/llimllib/.vim/bundle/vundle/autoload/vundle/installer.vim:
line  268:
E128: Function name must start with a capital or "s:": g:shellesc_cd(cmd) abort
line  271:
E133: :return not inside a function
line  273:
E133: :return not inside a function
line  275:
E193: :endfunction not inside a function
Error detected while processing function vundle#installer#new:
line    1:
E121: Undefined variable: a:1
E15: Invalid expression: (a:1 == '') ? g:bundles : map(copy(a:000), 'vundle#config#bundle(v:val, {})')
```

here are the full contents of installer.vim: https://gist.github.com/llimllib/c5bae01ad8da30b3c6dd/raw/7fdc5f369dcedc2ebb45e9c18deb2d88258f61e4/installer.vim

Is there anything additional I can tell you to help figure out the source of this problem?

**Comment by llimllib** [comment]
Found it!

I copied over the vundle section from my vimrc but the newest vundle added a required function call `call vundle#begin()` (which, presumably, defines `a:1`).

Fixed, sorry for the noise on the bug tracker! And special thanks to mhi^ for helping me debug on IRC.

**Comment by timini** [comment]
I found you also need to change the bundle location

`call vundle#begin('~/.nvim/bundle') `
