### ISSUE TITLE
ui_events mapping in --api-info is corrupted

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#23110]
### Problem

In the `ui_events` map, there is a dangling integer 10 between the map for `win_extmark` and the map for `popupmenu_show`.

### Steps to reproduce

Examine the msgpack output of `nvim --api-info` (can write it to a file, then read it in and parse it with `msgpackparse`). 

### Expected behavior

The 10 should not be there.

### Neovim version (nvim -v)

v0.10.0-dev-64+g37bb40701

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Rocky Linux 8.6

### Terminal name/version

xfce4-terminal 1.0.4

### $TERM environment variable

tmux-256color

### Installation

appimage

**Comment by bfredl** [comment]
Cannot reproduce. I get a `10` value which is correctly set as the `'since'` field of `win_extmark`, sure you didn't misread that?

**Comment by ddickstein** [comment]
It took me quite a while to figure out what was going wrong here, but I think this ended up being due to an `ssh -t` invocation that caused CRLF line endings, which corrupted the msgpack output.
