### ISSUE TITLE
Suggestion: improve example in lua-guide-autocommands-group

### ISSUE THREAD

**Issue by albertfgu** [neovim/neovim#23113]
### Problem

I was reading the lua-guide and in the "Grouping autocommands" section: https://neovim.io/doc/user/lua-guide.html#lua-guide-autocommands-group.

It provides an example (let's call it `example1`):
```
local mygroup = vim.api.nvim_create_augroup('vimrc', { clear = true })
vim.api.nvim_create_autocmd({ 'BufNewFile', 'BufRead' }, {
  pattern = '*.html',
  group = mygroup,
  command = 'set shiftwidth=4',
})
```
and then says (let's call it `example2`):

--------
Autocommand groups are unique for a given name, so you can reuse them, e.g.,
in a different file:
```
local mygroup = vim.api.nvim_create_augroup('vimrc', { clear = false })
vim.api.nvim_create_autocmd({ 'BufNewFile', 'BufRead' }, {
  pattern = '*.html',
  group = mygroup,
  command = 'set shiftwidth=4',
})
```
---------

I found this very confusing because it suggests that `example2` is something sensible to be used together with `example1`. But since they are defining the same autocommand one would never actually want to do this (I think). I think this section could be a lot more clear if `example2` was simply changed to a different command instead of the same `set shiftwidth=4`.

### Expected behavior

See above.

**Comment by dundargoc** [comment]
I've adjusted the example slightly in https://github.com/neovim/neovim/pull/22953.
