### ISSUE TITLE
Syntax highlighting different between vim and nvim

### ISSUE THREAD

**Issue by 42f87d89** [neovim/neovim#2312]
With the same config files, syntax highlighting works differently whether I use vim or nvim.

I am using archlinux, I installed nvim from the arch user repository, VIMRUNTIME is set correctly, nvim version 0.0.0-alpha+201503270525.

example: http://imgur.com/a/cEVwY (the top one is nvim)

**Comment by tarruda** [comment]
Try loading your colorscheme in the `VimEnter` autocmd

**Comment by 42f87d89** [comment]
That works! I wasn't aware that vim has colorschemes even in the terminal.

**Comment by 42f87d89** [comment]
For future reference, what is the preffered place to ask these sorts of questions?

**Comment by tarruda** [comment]
> For future reference, what is the preffered place to ask these sorts of questions?

I recommend the [gitter channel](https://gitter.im/neovim/neovim).
