### ISSUE TITLE
`wincmd` `g<tab>` doesn't work, while documentation says all <C-W> work with `wincmd`

### ISSUE THREAD

**Issue by shahzadlone** [neovim/neovim#23137]
### Problem

I wanted to initially make an `autocmd` such that when I close a tab, it will take me to the last accessed/used tab.

Normal I can do it with with: `g<Tab>` (in normal mode)

I have seen some mappings like: `autocmd TabClosed * tabprevious` to always go to the previous tab for example.

So naturally I have tried:

(1) `autocmd TabClosed * normal! g<Tab>` (Note: `:normal! g^I` works in command mode but `:normal! g<Tab>` does not)

I noticed there is also a `<C-W>` command for this:
```
<C-Tab>						*CTRL-<Tab>* *<C-Tab>*
CTRL-W g<Tab>					*g<Tab>* *CTRL-W_g<Tab>*
g<Tab>		Go to the last accessed tab page.
```

and saw in documentation:
```
Note: All CTRL-W commands can also be executed with |:wincmd|, for those
places where a Normal mode command can't be used or is inconvenient.
```

So I tried:

(2) `autocmd TabClosed * wincmd g<Tab>`

However (2) doesn't work with the `autocmd` nor from within the command mode (i.e `autocmd TabClosed * wincmd g<Tab>`).
The command mode gives the following error: `E474: Invalid argument`.

I am wondering if I am missing something or this is an actual bug?

Also wondering if there is an option similar to `tabprevious` like perhaps `tabrecent` that achieves this?

### Steps to reproduce

`autocmd TabClosed * wincmd g<Tab>`

### Expected behavior

Do what `g<Tab>` does but in an `autocmd` on tab close.

### Neovim version (nvim -v)

v0.8.1

### Vim (not Nvim) behaves the same?

Yes same issue v9.0 

### Operating system/version

Manjaro

### Terminal name/version

Kitty

### $TERM environment variable

tmux-256color

### Installation

pacman

**Comment by shahzadlone** [comment]
Also I realize there is a problem with even `autocmd TabClosed * tabprevious`.

Consider if 4 tabs are open: `|-1-|-2-|-3-|-4-|` where `(`name`)` marks the current tab I am in (i.e. inside 3 `|-(3)-|`).

Say I have this flow:

State: `|-1-|-2-|-(3)-|-4-|` 
Cmd: `:q<CR>`

State: `|-1-|-(2)-|-4-|`
Cmd `:tabprevious`

State: `|-(1)-|-2-|-4-|`

So the command went +1 `prev` after closing the tab, is there a way to signal to always go a certain direction for this case?

**Comment by zeertzjq** [comment]
`execute "wincmd g\<Tab>"`
