### ISSUE TITLE
There appears to be no way to handle response of swap check on nvim_buf_set_name

### ISSUE THREAD

**Issue by miversen33** [neovim/neovim#23145]
### Problem

I could be missing something but there appears to be not way to handle the response of a swapfile check on `nvim_buf_set_name`.

This is a bit difficult to explain but the long short is, if you try to set the name of a buffer to a name that vim believes is already open (via its "swapfile" checking process), you will be presented with the typical `E325: ATTENTION` error. Something like below

```
		E325: ATTENTION  
	Found a swap file by the name ".main.c.swp"  
		  owned by: mool   dated: Tue May 29 21:09:28 2001  
		 file name: ~mool/vim/vim6/src/main.c  
		  modified: no  
		 user name: mool   host name: masaka.moolenaar.net  
		process ID: 12559 (still running)  
	While opening file "main.c"  
		     dated: Tue May 29 19:46:12 2001  
  
	(1) Another program may be editing the same file.  
	    If this is the case, be careful not to end up with two  
	    different instances of the same file when making changes.  
	    Quit, or continue with caution.  
  
	(2) An edit session for this file crashed.  
	    If this is the case, use ":recover" or "vim -r main.c"  
	    to recover the changes (see ":help recovery").  
	    If you did this already, delete the swap file ".main.c.swp"  
	    to avoid this message. 
Swap file ".main.c.sp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (D)elete it, (Q)uit, (A)bort: 
```

If you are tracking your code through to this point, you will actually hit a full thread block while Neovim waits for a response. The issue is, no matter what response is chose, this will toss a vim E325 error that cannot be handled within lua. So if the user presses `O` for example, we are not given the opportunity to handle that. 

Now you will say "well that's fine, vim will just open that file in read-only mode anyway". 

Well hold on there Buster. Some plugins actually have to fetch the file before it can be loaded into the buffer (for example, that is how [`netman.nvim`](https://github.com/miversen33/netman.nvim) knows what file to remotely fetch and load into the buffer). So in this case, a plugin that _needs_ to be able to set the file name (or handle the user response after an E325) is seemingly unable to.

I want to believe I am doing something wrong here. Can someone point me in the right direction?

### Steps to reproduce

[Steps to reproduce this are a bit tough as they require dynamically loading a file into the buffer and then changing its name to match something that is in swap](https://github.com/miversen33/netman.nvim/issues/133). The easiest way I have found to reliably do this is by opening a remote file with Netman, and then killing vim, then attempting to reopen said remote file.

I will pin the first comment on this issue and see if I can get a more streamlined way to reproduce this

### Expected behavior

Provide some mechanism to handle the response to an `E325`

### Neovim version (nvim -v)

v0.9.0

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Arch Linux

### Terminal name/version

wezterm 20230408-112425-69ae8472

### $TERM environment variable

xterm-256color

### Installation

Downloaded precompiled source

**Comment by miversen33** [comment]
Pinned for edits and more details...

**Comment by justinmk** [comment]
> Provide some mechanism to handle the response to an `E325`

`:help SwapExists`

**Comment by miversen33** [comment]
@justinmk thank you! This wasn't actually the solution to my problem, turns out I am bad at writing code (who knew!). However this did get me pointed in the right direction and I **finally** found the source of a bug in my code which was causing this failure.

For anyone else wondering, if you are in a situation where you _may_ be executing a `read/open` of a file that may have a swap file already, you _must_ wrap that in a pcall. Otherwise the underlying `E325` will cause the JIT to execute your context and the remainder of your code will not be ran (as that's kinda what errors do) .

I appreciate you and the work everyone does on Neovim :)
