### ISSUE TITLE
Due to the fact that exists(":def") returns 2, vim-airline has become inoperable and is generating errors

### ISSUE THREAD

**Issue by yaegassy** [neovim/neovim#23149]
### Problem

After updating Neovim, the following error occurred in `vim-airline`.

```
Error detected while processing BufWinEnter Autocommands for "*"..function <SNR>22_on_window_changed[22]..<SNR>22_init[6]..airline#extensions#load[58
]..script /Users/yaegassy/.local/share/nvim/plugged/vim-airline/autoload/airline/extensions/term.vim[11]..function airline#section#create_left[1]..<S
NR>63_create[51]..<SNR>63_wrap_accent[2]..script /Users/yaegassy/.local/share/nvim/plugged/vim-airline/autoload/airline/highlighter.vim[16]..function
 airline#util#has_vim9_script:
line    2:
E121: Undefined variable: v:versionlong
E121: Undefined variable: v:versionlong
```

The error is occurring because previously the result of `exists(":def")` was `0`, but it is now `2`.

Although the issue has been addressed by adjusting vim-airline, we would like to report it to the Neovim repository just to be sure.

- <https://github.com/vim-airline/vim-airline/issues/2636>

If this behavior is intentional, there is no problem. Please close this issue.

### Steps to reproduce

...omission

### Expected behavior

...omission

### Neovim version (nvim -v)

NVIM v0.10.0-dev-104+g0dbb0419f

### Vim (not Nvim) behaves the same?

...omission

### Operating system/version

macOS 13.3.1

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by clason** [comment]
Vim 9.0.1450 behaves the same.

**Comment by yaegassy** [comment]
OK, it seems that this behavior is intentional, so we will close this issue.

**Comment by clason** [comment]
Not intentional, Neovim should return `1` (as `:def` is short for `:defer` here and not a full match).

**Comment by zeertzjq** [comment]
I think `:def` being short for `:defer` will cause confusing behavior. The best way to solve this is too add some special handling like `:delete`.
