### ISSUE TITLE
v:exiting is not persisted after VimLeave

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#23158]
### Problem

The `on_exit` job handler can run after Neovim runs the VimLeave autocmd, but there isn't a way to detect that Neovim is exiting.

### Steps to reproduce

```lua
local did_vim_leave_pre = false
local did_vim_leave = false
vim.api.nvim_create_autocmd("VimLeavePre", { callback = function() did_vim_leave_pre = true end })
vim.api.nvim_create_autocmd("VimLeave", { callback = function() did_vim_leave = true end })
vim.fn.jobstart({ "cat" }, {
  on_exit = function()
    vim.fn.writefile(
    { "Did VimLeavePre? "..tostring(did_vim_leave_pre)
    , "Did VimLeave? "..tostring(did_vim_leave)
    , "Exiting: "..vim.v.exiting
    , "Dying: "..vim.v.dying
    }, "/tmp/foo.log")
  end
})
```
After sourcing this file and exiting Neovim, the contents of `/tmp/foo.log` are:
```
Did VimLeavePre? true
Did VimLeave? true
Exiting: 0
Dying: 0
```

### Expected behavior

`v:exiting` (and `v:dying` if applicable) are persisted in exit handlers.

### Neovim version (nvim -v)

v0.10.0-dev-86+g54dab9ed9

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Rocky Linux 8.6

### Terminal name/version

xfce4-terminal 1.0.4

### $TERM environment variable

tmux-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
Aren't they persisted? `v:exiting` is 0 instead of `v:null`.

**Comment by ddickstein** [comment]
Oh, I misinterpreted `v:exiting` as a boolean. My mistake, thank you.

**Comment by ddickstein** [comment]
Ah, I realized something about why I had gotten confused here. The original problem I ran into was in VimL, where v:null == 0. But I can do this check by using `json_encode(v:exiting)` to distinguish.
