### ISSUE TITLE
Support for ":tab terminal"

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2315]
I think `:tab term` should open a terminal in a new tab.

From the help:

    :[count]tab {cmd}					*:tab*
        Execute {cmd} and when it opens a new window open a new tab
        page instead.  Doesn't work for |:diffsplit|, |:diffpatch|,
        |:execute| and |:normal|.
        When [count] is omitted the tab page appears after the current
        one.
        When [count] is specified the new tab page comes after tab
        page [count].  Use ":0tab cmd" to get the new tab page as the
        first one.
        Examples: >
          :tab split	" opens current buffer in new tab page
          :tab help gt	" opens tab page with help for "gt"

**Comment by ZyX-I** [comment]
No, it should not. `:terminal` command does *not* open a new window, so there is no reason for `:tab` to work on it. Use `:tabe term://.//zsh` if you need.

**Comment by tarruda** [comment]
See `:h nvim-terminal-emulator-spawning`

**Comment by blueyed** [comment]
Of course, I see.

What do you think about adding `:termsp[lit]`?
It would be a shortcut for `:split term://$SHELL | startinsert`.

When defining the command yourself (`:command Termsplit sp term://$SHELL | startinsert`), `:tab Termsplit` does not work though.
That's probably because of how `:tab` works internally?!

**Comment by Pyrohh** [comment]
> What do you think about adding :termsp[lit]?
> It would be a shortcut for :split term://$SHELL | startinsert.

I might be missing something, but `:split | term` does just that for me.

**Comment by justinmk** [comment]
> When defining the command yourself (:command Termsplit sp term://$SHELL | startinsert), :tab Termsplit does not work though

That's because `:terminal` accepts bar characters as arguments passed to the shell (as it should).

> What do you think about adding :termsp[lit]?

I hope we can avoid special cases like this. @Pyrohh 's solution is reasonable.

**Comment by tarruda** [comment]
@blueyed you can also use `termopen` if you need more control such as when defining custom commands. `:terminal` itself is simply an alias to `enew | call termopen('...') | startinsert`

**Comment by theworldbright** [comment]
+1 @Pyrohh 's solution
