### ISSUE TITLE
Debouncing text changes delays semantic tokens, which in turn delays text input

### ISSUE THREAD

**Issue by yorickpeterse** [neovim/neovim#23164]
### Problem

When using semantic tokens and an LSP debounce is specified using `debounce_text_changes = 500` for example, the user input when typing is extremely laggy. Turning off the debouncing seems to fix this. My guess is that the use of semantic tokens somehow delays processing input, and the debounce delays the processing/requesting of semantic tokens, resulting in the observed lag.

Interesting enough, increasing the debounce delay doesn't actually seem to increase the input delay. For example, there's no clear difference in delay between a debounce time of 500 milliseconds and 5 seconds.

### Steps to reproduce

To reproduce this you'll need a large Rust file. I'll use https://github.com/inko-lang/inko as an example, but any large Rust file should do.

1. `git clone git@github.com:inko-lang/inko.git --branch=native-compiler`
2. `cd inko`
3. `cargo check` to install all the necessary dependencies. You'll need LLVM 15 installed for this.
4. `nvim --clean compiler/src/llvm/passes.rs`
5. `:lua vim.lsp.start({ cmd = { 'rustup', 'run', 'stable', 'rust-analyzer' }, flags = { debounce_text_changes = 500 } })`. Make sure the `cmd` option is correct for your setup (e.g. if you use a system-wide `rust-analyzer` you'll need to change it
6. Wait for rust-analyzer to start
7. `:3529` followed by `o`
8. Start typing `this is a typing test to see what the latency is` (or anything really)
9. Observe the severe latency when typing
10. `:lua vim.lsp.semantic_tokens.stop(1,1)` to disable semantic tokens
11. Repeat step 8 and notice the absence of any latency when typing

A recording of this is found here:

[![asciicast](https://asciinema.org/a/k0DQLMzZzjOGA4aXK7qGAycJl.svg)](https://asciinema.org/a/k0DQLMzZzjOGA4aXK7qGAycJl)

### Expected behavior

No extra latency is introduced by having semantic tokens enabled.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

Not relevant

### Operating system/version

Fedora Silverblue 37

### Terminal name/version

GNOME terminal

### $TERM environment variable

xterm-256color

### Installation

Fedora repository

**Comment by yioneko** [comment]
There is a default 200ms delay for semantic tokens request: https://github.com/neovim/neovim/blob/240c41e1af556cd17329d5c46d26a3ca91be2db8/runtime/lua/vim/lsp/semantic_tokens.lua#L535-L536

So simply changing `debounce_text_changes` won't make a difference. The actual problem is that nvim is busy with processing large semantic token response for large file. 

Related server issue: https://github.com/rust-lang/rust-analyzer/issues/8253
