### ISSUE TITLE
terminal: NeoVim does not take left columns into account when computing terminal width

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2317]
If there are signs for a terminal buffer, Neovim automatically(?) displays them.

This is not reflected in the `$COLUMNS` variable of the terminal, which may report 41, while there are only 39 columns.

(I am using quickfixsigns, which automatically adds signs, also for the terminal buffers - which should get skipped probably by default)

**Comment by ZyX-I** [comment]
Can you check `stty size` which displays a pair `line column`? `$COLUMNS` is just environment (more likely, shell global) variable that is managed by the shell. Depending on what `stty size` reports this issue may either be one of

1. NeoVim did not send SIGWINCH to the shell when you added signs, so shell does not know it should update its size. (`stty size` reports correct size, different from `echo $LINES $COLUMNS`.)
2. NeoVim does not use sign column in width computations. (`stty size` reports the same thing `echo $LINES $COLUMNS` does.)

**Comment by ZyX-I** [comment]
I can confirm this situation and say that in my case it is case 2 (NeoVim did not update terminal width) and not 1 (NeoVim did not report terminal width was updated).

**Comment by blueyed** [comment]
Same with me, `stty size` is the same before and after the signs get displayed.

**Comment by ZyX-I** [comment]
I have checked out how it works with `&foldcolumn` and may say that there is the same error: `&foldcolumn` is not taken into account when computing terminal width.

One additional note: this is exactly “columns not taken into account bug”, not “NeoVim does not recompute terminal width when setting columns” (to verify: add sign/set foldcolumn and do a vertical split: in this case width is recomputed (`stty size` reports lesser number of columns), but columns are still not taken into account).

**Comment by splinterofchaos** [comment]
A little off topic for the PR, I guess, but I added a commit to #2346 that should fix this.
