### ISSUE TITLE
Semantic token highlighing broken for file types containing hyphens

### ISSUE THREAD

**Issue by kevin-sellers** [neovim/neovim#23184]
### Problem

I have a file type that contains a hyphen, so when my language server returns semantic tokens, I see it is trying to create highlight groups such as `@lsp.type.class.foo-bar`. This results in a slew of the following error showing up in `:messages` (one for each semantic token):

```
E5248: Invalid character in group name
```

https://github.com/neovim/neovim/blob/59fed8bb6457eb6c5204dc39a49d7ea0e1781482/runtime/lua/vim/lsp/semantic_tokens.lua#L422-L433

### Steps to reproduce using "nvim -u minimal_init.lua"

```
local lspconfig = require('lspconfig')
local configs = require('lspconfig.configs')

if not configs.kevin then
    configs.kevin = {
        default_config = {
            cmd = {'kevin'};
            filetypes = {'foo-bar'};
            root_dir = function(fname)
                return lspconfig.util.find_git_ancestor(fname)
            end;
        };
    }
end

lspconfig.kevin.setup {}
```

Editing a `*.foo-bar` file then results in the errors above. Changing the logic to build the highlight groups to use the LSP clients name instead of the file type, it works without issue.

### Expected behavior

Semantic token highlighting works as if there were no invalid characters in the highlight group name.

### Neovim version (nvim -v)

0.9.0

### Language server name/version

custom

### Operating system/version

Amazon Linux 2

**Comment by clason** [comment]
Please give us enough details to reproduce this. If the language server returns invalid tokens, there's not much we can do.

**Comment by kevin-sellers** [comment]
I've edited my original to include more information, but without handing you my customer language server, I'm not sure I can provide more information. Changing my supported file types to something that doesn't include a hyphen results in proper semantic token highlighting; the language server is not returning invalid tokens.

**Comment by clason** [comment]
Thank you, the issue is clear now. As you noticed, filetypes with dashes -- which I've never seen before in the wild -- will lead to invalid group names due to the automatic creation of the implicit language-specific highlight group name.

Two options:
1. change the filetype to use an underscore instead
2. add a sanitization step in the token name generation that converts dashes into underscores (may have performance implications)

**Comment by gpanders** [comment]
>change your filetype to use an underscore instead (if that is an option)

I would highly advise doing this in any case. Filetypes are not expected to contain anything other than alphanumeric characters and underscores (i.e. `[A-Za-z0-9_]` in regex), so using characters outside of that set may have all kinds of unintended side effects.

**Comment by mfussenegger** [comment]
Treesitter would have the same problem,  right? I see no point in fixing this exclusively in the semantic tokens layer without a decision to generally support dash in filetypes. As it may break elsewhere as well. 

If we do decide to support it, a fix might better fit in the lower layers?

**Comment by mfussenegger** [comment]
It just occurred to me that I also use a filetype containing a dash in nvim-dap for the repl (`dap-repl`) and I'm thinking that if it is really not supported, there should be some eager validation. `setlocal ft=foo-bar` should fail.

But I never noticed an issue with it so far, so maybe it wouldn't be a problem to support it?

In case we do - would it make sense to widen the allowed highlight group names, or should the semantic token layer just replace it to underscore?


> (which is a significant undertaking)

Are there some limitations you're aware of?

**Comment by clason** [comment]
> Are there some limitations you're aware of?

Not really; I was thinking about the investigation alone.

**Comment by justinmk** [comment]
> Filetypes are not expected to contain anything other than alphanumeric characters and underscores (i.e. `[A-Za-z0-9_]` in regex),

Should `:filetype` and `:set filetype=...` show a warning or error in that case?

**Comment by zeertzjq** [comment]
Hmm, https://github.com/hashicorp/terraform-ls/pull/999/files

**Comment by gpanders** [comment]
>Filetypes are not expected to contain anything other than alphanumeric characters and underscores (i.e. [A-Za-z0-9_] in regex)

Maybe I overstated this. I can at least say that on everything filetype related that I've worked on, I've always implicitly held this assumption. But maybe there aren't any serious side effects other than the one listed in this issue.

**Comment by clason** [comment]
> there needs to be either a way to allow users to map semantic token types to highlight groups

There is, `:h LspTokenUpdate`.

**Comment by ddl-acoleman** [comment]
I am able to replicate this error by enabling `terraformls` language server, and creating a file (without special chars), containing the following:

**help.tfvars**
```
deploy_id             = ""
region                = ""
availability_zone_ids = ["", ""]
k8s_version           = ""
```

Results in:
```
E5248: Invalid character in group name
E5248: Invalid character in group name
Press ENTER or type command to continue
```

Disabling the `terraformls` fixes this problem. 

I am using the following:

- nvim 0.9.1
- terraform-ls 0.31.3

**Comment by rodrigc** [comment]
I encountered the same problem.  Is it possible to update the filetype from `terraform-vars` to `terraform_vars`?
Or is another fix required?

**Comment by pillzu** [comment]
Hm! I am not sure but do we have any updates on this? My `neovim` setup gets spammed with `E5248` message without any stack-traces and I am not sure what's going wrong here.... None of my files have dashes in them and this only happens when opening `terraform.tfvars` file with terraformls enabled. 
Would appreciate some assistance with the same.

**Comment by rodrigc** [comment]
@pillzu My current workaround is, 
1.  open `terraform.tfvars` in neovim
2.   Very quickly do: `set filetype=terraform`

**Comment by gpanders** [comment]
`terraform.tfvars` should work in the next release (more generally, `@` and `.` will be allowed in highlight group names).

There is not yet a change to allow `-` in highlight group names. Anybody is welcome to volunteer to make that change (the change itself is trivial. What is unknown is how many things allowing `-` will break).

**Comment by gpanders** [comment]
`terraform.tfvars` should not be an issue, since `.` has been allowed in highlight group names for [almost a year](https://github.com/neovim/neovim/pull/19830). Are you using an older version?

**Comment by rodrigc** [comment]
I am using:

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

If you look here: https://github.com/teddylear/terraform-ls/blob/main/docs/USAGE.md#usage-of-terraform-language-server

you will see that the terraform language server supports a file type of `terraform-vars`.

But that seems to trigger in neovim the original error reported in this issue:

```
E5248: Invalid character in group name
```

The workaround I mentioned [here](https://github.com/neovim/neovim/issues/23184#issuecomment-1677874755) is what I am currently using

**Comment by gpanders** [comment]
Oh my mistake, I thought the filetype was `terraform.tfvars`, but that is the filename. Disregard my comment.

**Comment by rodrigc** [comment]
Looks like the error is coming from here: https://github.com/neovim/neovim/blob/6d93bdd458a03bd07b1797e43bb11e3be560d340/src/nvim/highlight_group.c#L1948

Do you think it would be OK to add `'-`` to the list of characters we are checking for the group name?

**Comment by gpanders** [comment]
I did just that and am testing to see how many (if any) tests break https://github.com/gpanders/neovim/actions/runs/5859780061/job/15886488470

**Comment by rodrigc** [comment]
I think in [your commit](https://github.com/neovim/neovim/pull/24714/commits/c6899f24f717e9702cca13aa1fe7f1b42cc588de), you need to change `Allow` to `allow` to appease the linter 😄

**Comment by rodrigc** [comment]
As a quick check, I took your branch: https://github.com/gpanders/neovim/tree/highlight-name-dash and built it locally.

I then tried to edit a `terraform.tfvars` file, and did *not* error: `E5248: Invalid character in group name`.

So at least for me, this is an improvment.
Thanks for pushing this forward!

**Comment by rodrigc** [comment]
@gpanders I would like to personally thank you for this fix.
I will be so bold as to thank you on behalf of all people who edit terraform with neovim. 😀

**Comment by jonchines** [comment]
So, I'm not sure how all of this works.  Any idea when this will be in released code?  To get this now, I guess I need to remove my current (package managed) Neovim and move to the packaged nightly or compile myself, correct?

**Comment by rodrigc** [comment]
> So, I'm not sure how all of this works. Any idea when this will be in released code? To get this now, I guess I need to remove my current (package managed) Neovim and move to the packaged nightly or compile myself, correct?

@jonchines Yes, right now, I have my own built version of neovim with this patch.  This fix https://github.com/neovim/neovim/pull/25661 was merged to https://github.com/neovim/neovim/tree/release-0.9 branch, so most likely the next 0.9x or 0.10.x release of neovim will have this.

**Comment by clason** [comment]
It'll be in the next release (0.9.5 or 0.10.0, whichever comes first).
