### ISSUE TITLE
Add vim.schedule() to the API

### ISSUE THREAD

**Issue by lbrayner** [neovim/neovim#23205]
### Problem

With this Vimscript code, I can't see the message "Closed Cmdline-window.":

```vim
function! s:CloseCmdlineWindow()
    quit
    echo "Closed Cmdline-window."
endfunction

augroup CmdwinClose
    autocmd!
    autocmd CmdwinEnter * nnoremap <buffer> <F9> <Cmd>call <SID>CloseCmdlineWindow()<CR>
augroup END
```

I can see it, however, if I use lua's `vim.schedule()`:

```vim
function! s:CloseCmdlineWindow()
    quit
    lua vim.schedule(function() print("Closed Cmdline-window.") end)
endfunction

augroup CmdwinClose
    autocmd!
    autocmd CmdwinEnter * nnoremap <buffer> <F9> <Cmd>call <SID>CloseCmdlineWindow()<CR>
augroup END
```

If this were in the API, let's say `nvim_schedule`, I could call it more cleanly using a funcref. Moreover it exposes it to languages other than lua and Vimscript.

Love lua, though!

### Expected behavior

N/A

**Comment by clason** [comment]
What's wrong with `v:Lua.vim.schedule`?

**Comment by bfredl** [comment]
in vim script you can use `timer_start(0, cb)` with zero timeout to the same effect.

**Comment by lbrayner** [comment]
Thanks @clason, @bfredl. `timer_start` will do!
