### ISSUE TITLE
Random (frequent) segfault on startup

### ISSUE THREAD

**Issue by JCavallo** [neovim/neovim#23217]
### Problem

Since I rebuld Neovim master a few days ago (unfortunately I do not remember the previous commit I was on), Neovim frequently crashes on startup.

Frequently meaning that I sometimes have to try 5 times to get it to run.

I _feel_ that it somehow is more frequent once the system is more memory constrained (I have crashes after a reboot, but at first they are less frequent).

The exact behaviour is that when starting `nvim` from my terminal (`kitty` + `tmux`), the screen is cleared, then it instantly drops back to `bash`.

The syslog indicates a segfault / general protection fault in libc : 
```
kernel: [592406.935047] traps: nvim[1420001] general protection fault ip:7fcae6fc0717 sp:7ffefa5b7a28 error:0 in libc-2.31.so[7fcae6e5a000+178000]
```
or
```
 kernel: [593534.215930] nvim[1429504]: segfault at 20 ip 00007f67cc534717 sp 00007ffe1c280818 error 4 in libc-2.31.so[7f67cc3ce000+178000]
```

Once Neovim successfully starts, I do not recall random crashes even after prolonged use.

### Steps to reproduce

`nvim -u None` is enough to trigger the crash _on my machine_ (sic.)

I have a backtrace for the `general protection fault`

[bt.txt](https://github.com/neovim/neovim/files/11285944/bt.txt)

### Expected behavior

No crashes :)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-110+g07b60efd8

### Vim (not Nvim) behaves the same?

no, 8.1

### Operating system/version

Ubuntu 20.04.6 LTS

### Terminal name/version

kitty 0.15.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by lewis6991** [comment]
This might be fixed with #23155
