### ISSUE TITLE
E5113: Error while calling lua chunk: /home/<username>/.config/nvim/lua/core/init.lua:67: attempt to call local 'autocm d' (a nil value)

### ISSUE THREAD

**Issue by Marcodoro** [neovim/neovim#23223]
### Problem

when i open nvim in my ubunto terminal i get this error: E5113: Error while calling lua chunk: /home/msrcp/.config/nvim/lua/core/init.lua:67: attempt to call local 'autocm
d' (a nil value)
![Screenshot 2023-04-20 163226](https://user-images.githubusercontent.com/118012046/233398702-f3e7f9c0-a14e-4c66-b30d-c28d5a066a34.png)

### Steps to reproduce

.

### Expected behavior

not getting this error

### Neovim version (nvim -v)

nvim 0.6.1

### Vim (not Nvim) behaves the same?

0.6.1

### Operating system/version

windows 11

### Terminal name/version

ubuntu

### $TERM environment variable

i dont know

### Installation

system package manager

**Comment by lewis6991** [comment]
It is a problem in your init.lua

**Comment by luukvbaal** [comment]
Likely you're using a config that requires `vim.api.nvim_create_autocmd` and your version does not support that. I suggest updating...
