### ISSUE TITLE
Vim noequalalways doesn't work at all

### ISSUE THREAD

**Issue by mkschreder** [neovim/neovim#23236]
### Problem

When I have vertical splits and open any other sidebar at the left hand side then all my splits are shifted to the right. When I close the sidebar, the vertical splits are not shifted back equal amount to the left.

### Steps to reproduce

- :vs
- Open any vertical split
- Close vertical split
- Result: all other vertical splits are messed up

### Expected behavior

When I close a vertical split I want all other vertical splits to return to the position where they were before opening the vertical split. **I would also expect noequalalways option to be respected - currently it has zero effect**

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

no, 8.2 handles splits properly

### Operating system/version

Ubuntu 20.04

### Terminal name/version

Tmux

### $TERM environment variable

tmux-256color

### Installation

Compiled from stable branch

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by mkschreder** [comment]
@zeertzjq, this seems to get messed up after reloading my vim config the second time using ":source %". It seems that more than one thing is messed up after that. 

What are the best practices with lua plugins, python plugins and all the other things in Nvim to make sure that the config file can be reloaded without having to restart Nvim?
