### ISSUE TITLE
vim.iter: pass more state to callback functions

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#23251]
### Problem

For callbacks of functions like `Iter:find()`, `Iter:filter()`, (~~future?: `Iter:reduce()`~~  `Iter:fold()`), it's useful to know

1. the "previous" element
2. the result of the previous callback

This allows the callback to compare / reason about observed elements and results.

### Expected behavior

Using [javascript's reduce()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#parameters) as inspiration, we could pass these args:

- `i`: current index
- `prev_val`: previous value (maybe not needed because of `i` ?)
- `result` (or `accum`?): Result of the previous callback. On first call, `initial_val` if specified, otherwise the first value of the iterator (`iter[1]`).

**Comment by gpanders** [comment]
Repeating my comment [here](https://github.com/neovim/neovim/pull/27021#issuecomment-1893875635):

> For callbacks of functions like Iter:find(), Iter:filter(), (future?: Iter:reduce()), it's useful to know
> 
> - the "previous" element
> - the result of the previous callback

Can this not already be achieved with the API that we have? I don't want to pass a bunch of state to every stage of the iterator pipeline if it's not needed. It complicates the API and makes things more cumbersome/verbose/confusing. Instead if these things are needed the iterator itself should be able to support it.

> Using [javascript's reduce()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#parameters) as inspiration, we could pass these args:
> 
> * `i`: current index
> * `prev_val`: previous value (maybe not needed because of i ?)
> * `result` (or accum?): Result of the previous callback. On first call, initial_val if specified, otherwise the first value of the iterator (iter[1]).

We already support this:

- Current index can be injected into the iterator pipeline with `:enumerate()`
- `prev_val` and `result` are already supported by `:fold()`. The "accumulator" in `fold` can be _anything_, including a state table:

  ```lua
  local t = vim.iter({ 1, 2, 3, 4, 5 }):fold({}, function(acc, v)
    local last = acc.last or 0
    acc.last = v
    if not acc.result then
      acc.result = 0
    end
    acc.result = acc.result + last + v
    return acc
  end)
  vim.print(t.result)
  -- 25
  ```

**Comment by justinmk** [comment]
Added an extra accumulator example in #24163 , also added a `Iter:reduce()` help tag.
