### ISSUE TITLE
Incorrect color codes in ':h cterm-colors'

### ISSUE THREAD

**Issue by 3N4N** [neovim/neovim#23253]
### Problem

The color names ascribed to the color codes for 16-color terminals in `:h cterm-colors` aren't what's experienced.  For example, `hi Search ctermbg=11` causes the background to be yellow, but according to the doc it should be cyan.

### Steps to reproduce

N/A

### Expected behavior

Doc should match actual behavior.

### Neovim version (nvim -v)

v0.10.0-dev-138+g05928fe29814

### Vim (not Nvim) behaves the same?

no, vim 9.0.1472

### Operating system/version

Windows 11 22H2

### Terminal name/version

Windows Terminal

### $TERM environment variable

nil, xterm-256color

### Installation

Built from source

**Comment by bfredl** [comment]
below it says:

> Note that for 16 color ansi style terminals (including xterms), the
> numbers in the NR-8 column is used.  Here "*" means "add 8" so that 
> Blue is 12, DarkGray is 8 etc.

docs are very confusing, seems that NR-8 colors are used in practice also for 16 color terminals (which the NR-8 colors repeated twice but bright). Not sure what those NR-16 terminals are, MS DOS console?

Regardless a doc patch would be welcome.

**Comment by 3N4N** [comment]
> Regardless a doc patch would be welcome.

I have no idea what's going on in n/vim when it comes to colors.  I actually found this doc issue last year, tried to find the implementation, and failed.  Yesterday I thought at least a ticket should exist, in case someone else can elucidate.

To show that I really did try to find out what's going on: I thought this (see below) is where the 16 cterm-colors are defined.  But I changed all these colors to black (0,0,0) and nothing changed.  All colors remained as before.  So what's this table for?  I donno.

https://github.com/neovim/neovim/blob/05928fe29814516be5537ffa23e8ba7a1f86e0be/src/nvim/highlight.c#L752-L771

**Comment by 3N4N** [comment]
I just checked with Vim in an Ubuntu machine.  The cterm-colors are the same that in Neovim.  Both are using NR-8 column of the table.  That means Vim is using NR-16 for Windows console (doesn't matter if the terminal emulator is xterm-like Windows Terminal or the old Conhost console).

There is nothing wrong in the doc.  It's merely confusing; that's all.  I'll keep the ticket open for a few more days, as a place to log my findings.  I'll close it after that.

**Comment by 3N4N** [comment]
Seems like in Windows the color codes are different than ANSI terminals: https://learn.microsoft.com/en-us/dotnet/api/system.consolecolor?view=net-8.0.  (It's a dotnet doc link, but I expect color code should be the same for C++ API as well.)
