### ISSUE TITLE
[terminal-emulation] Handle cursor shape in insert mode (TUI)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2326]
`ui->insert_mode` (and `ui->normal_mode`) should get handled for terminal windows, too.

This means that with `NVIM_TUI_ENABLE_CURSOR_SHAPE=1` the cursor shape should get changed according to insert/normal mode.

For the TUI, this uses `tui_insert_mode` / `tui_nomal_mode`.

**Comment by splinterofchaos** [comment]
Shells and programs run through `:term` may want to change the shape of the cursor so nvim should not interfere, ideally. However, the fallowing command should change the cursor shape on xterm-compatible terminals:
```bash
$ echo -e '\x1b[5 q'
```
but it does not.

I've looked into this a bit, but I guess I don't understand how the code works yet. Even when I try to force changing the cursor shape in terminal mode in various ways, it remains the same solid block.

**Comment by tarruda** [comment]
libvterm supports cursor shape customization, but `:terminal` uses a virtual cursor which is simply a set of highlight attributes applied to a cell, so it doesn't support the bar shape. Cursor blinking could be implemented with a libuv timer.

**Comment by rkannan82** [comment]
@tarruda Does that mean the bar/pipe (|) cursor shape can't be supported or it will be supported later?

**Comment by justinmk** [comment]
It can be supported, but isn't a priority right now.

**Comment by tarruda** [comment]
> It can be supported, but isn't a priority right now.

:+1:

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/pull/5556

**Comment by justinmk** [comment]
Merging this with https://github.com/neovim/neovim/issues/3681
