### ISSUE TITLE
build(macos+nix): ld: unknown option: --no-undefined

### ISSUE THREAD

**Issue by nifoc** [neovim/neovim#23262]
### Problem

The latest nightly fails to build on macOS (and only on macOS) using `nix`:

```
ld: unknown option: --no-undefined
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

My assumption is that it was caused by #23106, where `elseif(NOT APPLE)` was changed to just `else()` in `src/nvim/CMakeLists.txt`.

I don't know anything about CMake, but to me this change looks like the following line now applies to all `CMAKE_SYSTEM_NAME`s that are not `SunOS`:

```
target_link_libraries(nvim PRIVATE -Wl,--no-undefined)
```

Whereas it didn't apply specifically to macOS before.

[Entire build log can be found here](https://gist.github.com/nifoc/859a07dd2310c2556783f0d2505721b6).

### Steps to reproduce

`﻿nix build "github:neovim/neovim?dir=contrib"`

### Expected behavior

Building `neovim` should succeed.

### Neovim version (nvim -v)

latest commit on master

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.3.1 (using nix)

### Terminal name/version

wezterm 20230408-112425-69ae8472

### $TERM environment variable

xterm-256color

### Installation

nix

**Comment by clason** [comment]
Build works fine on default macOS, for the record, so this must be Nix specific.

**Comment by clason** [comment]
default clang is `14.0.3` on macOS 13.3.1, fwiw. You might want to use that instead of the outdated `11.1.0` you seem to be using.

**Comment by nifoc** [comment]
> default clang is 14.0.3 on macOS 13.3.1, fwiw. You might want to use that instead of the outdated 11.1.0 you seem to be using.

This is a `nix` thing, though it might point to the actual issue: Could it be that "older" versions of clang/ld do not support the `--no-undefined` flag?

Googling around a bit, I can find quite a few results which look like the same issue. (Not related to `neovim`, but related to `clang-11`).

**Comment by dundargoc** [comment]
I think the clang version is the cause here like you said. As we still support clang 11.1.0, we should fix it. We need to figure out the clang version `-Wl,--undefined` was introduced in so we can document this in form of cmake code.

**Comment by bfredl** [comment]
or if there is an older synonym for `--no-undefined`, we can use that instead. It is essential functionality when working with modules ("bundles" on OS X), so there must be a way to do it on clang 11.

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/pull/23263 maybe this is enough?

I removed the check while trying different workarounds, but I never restored it as it was superfluous on CI (which normally represents our supported set of versions).

**Comment by dundargoc** [comment]
> maybe this is enough?

Yes.

**Comment by teto** [comment]
nixpkgs has all clangs from version 5 to version 15. @nifoc what if you replace the stdenv with llvmPackages_15.stdenv for instance ? I am not sure how to do that not using macOS, I suppose `override { stdenv = llvmPackages_15.stdenv; }` could do it ?

**Comment by dundargoc** [comment]
I don't think this is a nix-specific problem though. This problem should occur without nix as well.

**Comment by teto** [comment]
nevertheless, I would prefer nix to build with a more recent clang so if @nifoc knows how to do that I am interested :)
 I dont know why nixpkgs defaults to clang 11: if that's to follow a macos policy (but clason mentions clang 14.0.3 as a default so it's probably not that) or just that usiner newer clang breaks too much stuff.

**Comment by nifoc** [comment]
First: I can confirm that #23263 solves the immediate issue. 🥳

@teto Overriding the `stdenv` for the derivation (to `pkgs.llvmPackages_15.stdenv`) does work, too. I specifically checked with a commit that does not have #23263 yet.

Is this something you want to change in neovim directly or upstream in nixpkgs?
Can open a PR for this later.

**Comment by barracuda156** [comment]
`--no-undefined` is a Linux flag, it should not be used on macOS.

**Comment by dundargoc** [comment]
@barracuda156 this problem seems to have been solved a year ago. Has this problem resurfaced again or something?

**Comment by barracuda156** [comment]
I bumped into it in an unrelated setting on macOS and checked online if similar cases have been reported earlier.

**Comment by kencu** [comment]
As this Issue comes up when searching this error, there is a similar flag to be used on Apple systems:

`
 -Wl,-undefined,error
`
