### ISSUE TITLE
language-mapping for :substitute

### ISSUE THREAD

**Issue by ces42** [neovim/neovim#23270]
### Problem

currently `language-mapping` only works in command-line mode when doing a search with '/' or '?', but not when entering a search patttern for `:s`.

### Expected behavior

language-mapping is active when entering a search for `:s`, `:g` and `:v`. (the conditions that trigger this seem to be the same conditions that would trigger incsearch, so hopefully the code for that could be reused?)

[link to vim issue](https://github.com/vim/vim/issues/12291)

**Comment by zeertzjq** [comment]
This can cause problems. Ref https://github.com/vim/vim/issues/12291#issuecomment-1520037141

> This is tricky, because a search pattern contains more than text, it
also has special regexp characters.  Automatically switching on language
mappings can be annoying.  We would probably need a way to disable it,
making it more complex.

You can use CTRL-^ to quickly switch between the modes.  Isn't that
sufficient?  You know when you are going to type text where you want to
use a language mapping.  It's a more manual, but predictable.
