### ISSUE TITLE
[TS] Missing tree change event in Markdown

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#23286]
If I have a Markdown file with an embedded language (for example Lua) and I move a line out of the code block no tree change event will be reported for the embedded language. Here is an example Markdown document:

    ```lua
    print 'This is an injected language'
    print({{{{{{{{{{{}}}}}}}}}}})
    ```

Here are the corresponding minimal file type settings (`ftplugin/markdown.lua`) for use with nvim-treesitter:

```lua
local ts = vim.treesitter
ts.start()
local parser = ts.get_parser(nil, nil)

parser:for_each_child(function(p, lang)
	p:register_cbs {
		on_changedtree = function(changes, tree)
			print(lang, vim.inspect(changes))
		end,
	}
end, true)
```

As you can see, whenever a change in one of the trees happens a message with the language and the range of the change is printed. However, when I put my cursor on line `3` and press `dd` the only message I get is `markdown {}`. If I then press `p` to put the line down below the fence I do get the proper message `markdown { { 3, 0, 4, 0 } }`

The same thing happens if I use `:move` to move the line instead of deleting it. I place the cursor again on line `3` and execute `:move 4` to move the line down. The only message I get is `markdown { { 3, 0, 4, 0 } }`.

Putting the line back into the fenced code block does produce the proper messages:

- `:move 2` produces `markdown { { 2, 5, 2, 29 } }` and `lua { { 2, 0, 2, 29 } }`
- pressing `P` on line `3` (after `dd` to delete the second Lua line) produces the same output
- pressing `p` on line `2` (after `dd` to delete the second Lua line) produces the same output

The lack of an event is an issue in my plugin HiPhish/nvim-ts-rainbow2 because `:move` preserves the extmarks which should be cleared when the `on_changedtree` event is fired. However, since no Lua event is fired the Lua the extmarks are preserved. See here: https://github.com/HiPhish/nvim-ts-rainbow2/pull/32#issuecomment-1518943328

**Comment by lewis6991** [comment]
Good timing, already fixed this in #23287

**Comment by HiPhish** [comment]
The issue remains. I have updated the filetype configuration accordingly by adding an extra argument to `register_cbs`:

```lua
local ts = vim.treesitter
ts.start()
local parser = ts.get_parser(nil, nil)

parser:for_each_child(function(p, lang)
	p:register_cbs({
		on_changedtree = function(changes, tree)
			print(lang, vim.inspect(changes))
		end,
	}, true)
end, true)
```

I still only get the Markdown event. Could it be that Neovim is still using the old runtime files? I have checked out your fork, built from source (`make CMAKE_BUILD_TYPE=RelWithDebInfo`) and then launched the new binary (`./build/bin/nvim`). However, `echo $VIMRUNTIME` still points to `/usr/share/nvim/runtime`.

**Comment by clason** [comment]
Yes, you need to explicitly set `VIMRUNTIME`.

**Comment by HiPhish** [comment]
Even with the runtime set I get the same behaviour.

**Comment by lewis6991** [comment]
I think this is because treesitter doesn't report tree changes if nodes are removed. I noticed this while working on #23070.

This could be seen as a bug in upstream or a design feature. In any case, what would you *expect* the changes to be reported as?

**Comment by HiPhish** [comment]
Good point. We only get informed about the range of a change, but not the nature of the change. If a node at the end of the document is removed there is no range to report, so it does not make sense to expect an event.

To be honest I have no idea how this could be solved on the Neovim side. I think I can hack around the problem plugin-side be first clearing all existing extmarks (from my reserved namespace of course) before adding new extmarks. Not pretty, but it should get the job done.

I think this concludes the discussion.
