### ISSUE TITLE
Shipping neovim as deb and tar.gz

### ISSUE THREAD

**Issue by akdevservices** [neovim/neovim#23280]
### Problem

deb packages aren't shipped any longer.

### Expected behavior

Please ship statically compiled deb packages, because a lot of people use neovim in Debian-family stable distros (Ubuntu LTS, internal corporate distros, based on Ubuntu LTS, Debian) for development and administration. Nobody uses crap like appimage for console utilities, it's good to get a look at some program, but not for using software on day to day basis. I understand that a single packaging format is very convinient for neovim developers, but... Guys, it's mostly you who are interested in widespread neovim usage. Yes, I can repackage neovim for personal use so can some companies, but I suspect a lot of people won't do that and your user base will eventually shrink to "BTW I use Arch" and "Unix porno" guys... Your plans to drop linux tar.gz packages are even more weird.

**Comment by clason** [comment]
.deb packages are distro-specific and should be handled by distribution maintainers. The tar.gz is going nowhere now that it's created as part of the appimage workflow.

**Comment by bfredl** [comment]
"BTW I use Arch" userbase sounds fine to me. WONTFIX.

**Comment by justinmk** [comment]
Problems with the `.deb` are described in e.g. https://github.com/neovim/neovim/issues/22684#issuecomment-1475344454
