### ISSUE TITLE
`nvim -r` hangs (or returns nothing)

### ISSUE THREAD

**Issue by camoz** [neovim/neovim#23294]
### Problem

Running `nvim -r` hangs (after clearing terminal screen). On another machine, `nvim -r` returns instantly with exit status 0, but `nvim -r -V` hangs like on the first machine. It does not matter if I have another nvim instance open or not.

### Steps to reproduce

nvim -r

### Expected behavior

List swap files with recovery information.

### Neovim version (nvim -v)

v0.9.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Archlinux up-to-date

### Terminal name/version

foot version: 1.14.0 +pgo +ime +graphemes -assertions

### $TERM environment variable

foot-extra

### Installation

official arch repos

**Comment by zeertzjq** [comment]
Woekaround: using `nvim --headless -r` instead.

**Comment by falsifian** [comment]
I also see this, using neovim 0.9.0 on OpenBSD-current on amd64.

It also sometimes successfully lists some of the swap files but then hangs at a certain point in the list, or it might have sometimes successfully printed the whole list. (I don't know if I was using 0.9.0 when I observed that.)
