### ISSUE TITLE
The use of Ubuntu 15.04.

### ISSUE THREAD

**Issue by ysdlm** [neovim/neovim#2330]
Under Ubuntu 15.04 neovim color is why does not work?

**Comment by Pyrohh** [comment]
Unless someone running Ubuntu 15.04, this would benefit from information. Please see https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md

**Comment by foobacca** [comment]
I use Ubuntu 15.04 and using neovim from the PPA (0.0.0+git201504031205+1477+8+8~ubuntu15.04.1) and the solarized color scheme and colors seem to work fine for me. Running
 
    nvim -u NONE ~/examples.desktop +'syntax on'

also shows me syntax highlighting - does it not for you?

@ysdim: is there a particular problem you are seeing.  Are there any colours?  Are the colours not what you expect to see?

**Comment by pixelr0** [comment]
same here (using PPA)
nvim --version
NVIM 0.0.0-alpha (compiled Apr  6 2015 00:50:10)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/buildd/neovim-0.0.0+git201504060027+1485+8+8~ubuntu15.04.1/build/config -I/build/buildd/neovim-0.0.0+git201504060027+1485+8+8~ubuntu15.04.1/src -I/build/buildd/neovim-0.0.0+git201504060027+1485+8+8~ubuntu15.04.1/.deps/usr/include -I/build/buildd/neovim-0.0.0+git201504060027+1485+8+8~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/buildd/neovim-0.0.0+git201504060027+1485+8+8~ubuntu15.04.1/.deps/usr/include -I/build/buildd/neovim-0.0.0+git201504060027+1485+8+8~ubuntu15.04.1/.deps/usr/include -I/build/buildd/neovim-0.0.0+git201504060027+1485+8+8~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/buildd/neovim-0.0.0+git201504060027+1485+8+8~ubuntu15.04.1/build/src/nvim/auto -I/build/buildd/neovim-0.0.0+git201504060027+1485+8+8~ubuntu15.04.1/build/include
Compiled by buildd@lgw01-30

Optional features included (+) or not (-): +acl  +iconv 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by splinterofchaos** [comment]
@ysdlm, do you by any chance use urxvt? Also, please respond if `'+syntax on'` doesn't turn the color on.

**Comment by Pyrohh** [comment]
This has very little information, so I'll close this.

**Comment by arames** [comment]
I am also seeing issues with colors on a clean 15.04 install, with a neovim commit d9441444afa3e99c8116ad01b11614886aa53524 compiled from source.

Example test case:

~/.nvimrc:

    syntax on
    set nu

Edit a file. Then try

    :set t_Co=256
    :set t_Co
    E846: Key code not set: t_Co

System colors (1 to 15) work, but not other colours.

    " This works fine.
    :hi! LineNr ctermfg=2
    " This doesn't
    :hi! LineNr ctermfg=143

I gave a try to true colors as well, but it doesn't seem to work either.

**Comment by justinmk** [comment]
@arames Guessing your `&term` / `$TERM` do not contain the string "256color".

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/wiki/Troubleshooting#colors-arent-displayed-correctly

**Comment by arames** [comment]
I'll give it a try tomorrow on that machine. But note that vim had no problems with 256 colors in the same terminal.

**Comment by justinmk** [comment]
> But note that vim had no problems with 256 colors in the same terminal.

That's because, based on your code above, you were tweak `t_Co` which is ignored by Neovim (as are all other terminal codes).

**Comment by arames** [comment]
Thanks for the pointers, my `TERM` was indeed missing the `256color` string. I still need to get true colors working now.

**Comment by arames** [comment]
Ok got everything working. Here is what I was getting wrong in the end: with true colors in the terminal, colors should still be specified with the `ctermfg` and `ctermbg` options. I somehow was thinking that neovim with true colors in the terminal would look at the `gui` versions.

So just to recap, on Ubuntu 15.04 with gnome-terminal things work fine. Just make sure that:
- `TERM` contains `256color`
- The colors are specified with the `ctermbg` and `ctermfg` options

**Comment by tnguyen14** [comment]
I am using iTerm on OS X, and my `$TERM` is `xterm-256colors`, but when trying to do `:set t_Co=256`, and then `:set t_Co?`, I get this error `E846: Key code not set: t_Co?`. Sorry for dropping in here, I got here from Google, and didn't find much else on this issue.
