### ISSUE TITLE
bash syntax highlighting with case x in *) and ( ... ) with if ; then

### ISSUE THREAD

**Issue by Mehuge** [neovim/neovim#23322]
### Problem

If a `case ... in *) ...` is used within `( ... )` within an `if`-`then`-`fi` block it shows as a syntax error on the `esac` and following `)`

### Steps to reproduce

```bash
#!/bin/bash
if true; then
  (  
    case x in
    *) : ;;
    esac
  )
fi
```

### Expected behavior

Syntax to be correct.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

macos Ventura 13

### Terminal name/version

Terminal 2.13

### $TERM environment variable

screen-256color && xterm-256color

### Installation

brew install neovim

**Comment by clason** [comment]
Please report this to the maintainer of the bash syntax file (listed at the top of `runtime/syntax/bash.vim`).

**Comment by clason** [comment]
(but try the latest nightly first in case this has already been fixed)
