### ISSUE TITLE
Install neovim 0.8.3(at least) on ish

### ISSUE THREAD

**Issue by EdwardWong1994** [neovim/neovim#23327]
### Problem

I am using ish on ipad to install neovim. Because of the plugin i need at least require neovim 0.8.3. The only version i can find is 0.9 and 0.8.1, the version 0.8.1 can work on my ipad, but can not run the plugin.  I have no choice and try 0.9, but after installing it using package, when enter neovim, it is totally black screen. 

Do you know how to get neovim at least 0.8.3 to let me use the plugin  

### Steps to reproduce

`apk add neovim`

### Expected behavior

the version 0.9 is totally black screen

### Neovim version (nvim -v)

0.9

### Vim (not Nvim) behaves the same?

no, vim is good

### Operating system/version

ipad(M2) using alpine

### Terminal name/version

ish

### $TERM environment variable

xterm-256color

### Installation

apk add neovim

**Comment by clason** [comment]
That's a distribution issue.
