### ISSUE TITLE
TODO,FIXME,XTodo highlight group blacked out in light version of quiet colorscheme when lsp semantic highlighting on

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#23329]
### Problem

TODO,FIXME,XXX are all black boxes when using `set bg=light | colorscheme quiet` and you turn on lsp highlighting for the buffer.

### Steps to reproduce

`nvim --clean` (no lsp semantic highlighting):

<img width="594" alt="Screen Shot 2023-04-26 at 3 55 59 PM" src="https://user-images.githubusercontent.com/7416158/234688101-27e2b973-ec79-444e-99a9-75dd07763d10.png">

`nvim --clean` then`:set bg=light` and `:colorscheme quiet`:
<img width="521" alt="Screen Shot 2023-04-26 at 3 57 14 PM" src="https://user-images.githubusercontent.com/7416158/234688466-841cf06f-e25c-46a7-95c8-efcd8a92991b.png">

`nvim --clean` then `set bg=light | colorscheme quiet` and then `:lua vim.treesitter.start(1)`, notice our TODO highlights are gone.

<img width="579" alt="Screen Shot 2023-04-26 at 4 01 06 PM" src="https://user-images.githubusercontent.com/7416158/234689237-fa903f49-105c-4c81-973c-546e02e57829.png">

Apparently we can get 'em back (not documented) by installing a separate (parser/query?) with `:TSInstall comment`, but this requires installing nvim-treesitter.

Turning on lsp (requires lua-language-server binary on your path):

```
nvim --clean
set bg=light
colorscheme quiet
lua vim.lsp.start({name='lua', cmd={'lua-language-server'}, root_dir=vim.fs.dirname(vim.fs.find('.git', {upward=true})[1])})
```

Results in:

<img width="719" alt="Screen Shot 2023-04-26 at 4 11 19 PM" src="https://user-images.githubusercontent.com/7416158/234691332-e1229481-ff1a-442e-b47b-c347e5419502.png">

### Expected behavior

TODO/XXX/FIXME should be visible, I'm not sure if it can be fixed upstream if it's a lsp highlighting thing.

### Neovim version (nvim -v)

0.10.0 commit g801ac2acc

### Vim (not Nvim) behaves the same?

no, vim 

### Operating system/version

macOS

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

build from repo

**Comment by clason** [comment]
The bundled colorschemes are from Vim runtime and very much do not support treesitter or LSP highlights; you need to extend them yourself.
