### ISSUE TITLE
lsp-extension.txt is undiscoverable

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#23338]
### Problem

The doc `lsp-extension.txt` only has two tags, `lsp-extension.txt` and `lsp-extension-example`, and both of them appear in `lsp-extension.txt`. I happened upon this doc on accident, and it contained answers to some of my questions.

### Expected behavior

 I think given its content this doc deserves a mention in `vim.lsp.start_client` and/or `vim.lsp.buf_attach_client`.

### Neovim version (nvim -v)

v0.10.0-dev-186+g191e8b406

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Rocky Linux 8.6

### Terminal name/version

xfce4-terminal 1.0.4

### $TERM environment variable

tmux-256color

### Installation

appimage

**Comment by dundargoc** [comment]
I don't understand the point of these half-page long help files, the information becomes needlessly scattered. I think we should look into integrating this with lsp.txt or some something else.

**Comment by clason** [comment]
This example is also outdated since it predates `vim.fs`.

**Comment by mfussenegger** [comment]
>  and it contained answers to some of my questions.

What were these questions? The lsp-extension.txt predates vim.lsp.start & vim.fs and is now mostly obsolete.  We should remove it instead of linking to it and see if we can integrate anything useful elsewhere

**Comment by ddickstein** [comment]
Makes sense to me to remove an obsolete doc. What I found helpful on that page wasn't the example so much as this bit of text:

```
For more advanced configurations where just filtering by filetype isn't
sufficient, you can use the `vim.lsp.start_client()` and
`vim.lsp.buf_attach_client()` commands to easily customize the configuration
however you please. For example, if you want to do your own filtering, or
start a new LSP client based on the root directory for working with multiple
projects in a single session.
```

`:h buf_attach_client` does say "Without calling this, the server won't be notified of changes to a buffer," so I guess it does communicate the same thing. I think it might be helpful to have a section, maybe near the bottom, that communicates something like, "here is what infrastructure nvim-lspconfig is providing / if you are not using nvim-lspconfig you will need to do this, this, and this." I'm not saying the docs are incomplete without this, but I think this could be helpful, and was what I understood this text from `lsp-extension` to be discussing (although if I walked away misinformed please correct me). I also ack that it's weird for official docs to contrast what they do and don't provide against what a plugin provides, but I think this might be an exception since the doc already endorses the plugin and makes it sound somewhat official (more similar to netrw).

**Comment by ddickstein** [comment]
My mistake - I was working off of a doc for an older version of Neovim and didn't properly diff it against the newer version before reporting. I just checked that `lsp-extension` was still around, but didn't realize `lsp.txt` had changed significantly.
