### ISSUE TITLE
Error while reading ShaDa file: expected positive integer at position 3173 

### ISSUE THREAD

**Issue by EdwardWong1994** [neovim/neovim#23345]
### Problem

When i open the neovim, it will pop up error message: `E576 : Error while reading ShaDa file: expected positive integer at position 3173`. I search for a while and delete the files in `~/.local/state/nvim/shada/`, but it still occur this error.

How can i solve this? 
![b062dce034b2db0668173ea4abea71f](https://user-images.githubusercontent.com/96438179/234816879-073f65b5-7c94-4d98-8a7a-73b19ac4383b.jpg)

### Steps to reproduce

only this issue not occur, when using `nvim --clean`

### Expected behavior

![b062dce034b2db0668173ea4abea71f](https://user-images.githubusercontent.com/96438179/234817416-17d32848-22ca-4c76-bd84-d8e9743c060a.jpg)

### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ipad(M2) using alpine

### Terminal name/version

ish

### $TERM environment variable

xterm-256color

### Installation

apk add neovim

**Comment by nosvagor** [comment]
I had this issue, turns out the shada file is just in a different location (found solution here: https://github.com/neovim/neovim/issues/12101#issuecomment-1379980289
 
try removing this folder: `~/.local/state/nvim/shada`

**Comment by alerque** [comment]
Cleaning this up is relatively easy, as the linked issue above shows. But the harder question is: how to debug what is corrupting shada files in the first place? I've had it happen on two machines half a dozen times this week alone. I can make it go away by nuking the files, but I don't know where to begin debugging how they are ending up corrupted in the first place. The previous issues about this being locked doesn't help...

**Comment by axelhj** [comment]
I hate to enter a conversation just to notify everyone that I have the same issue, but I do too. This issue has been reoccurring to me for about one half year. I don't know why my ShaDa-file keeps getting corrupted but it is obnoxious. I really need to persist global options and oldfiles and Neovim presents no other way (afaict).

Which is why I have the following questions; how to debug this issue? Do I need to execute neovim with an strace-equivalent on windows? My suspicion is that Neovim does not wait for the ShaDa-file is not completely written before the Neovim process exits on shutdown and thus starts getting corrupted once it is larger than a specific size. Mine is currently 1162 kb large. There are 27 of them with names like `main.shada.tmp.a` etc.

**Comment by Aaronik** [comment]
This is happening to me now too. I recently switched from Linux to MacOS. I nuke `~/.local/state/nvim/shada` and it's fine for the first open, but then it comes back for all subsequent opens until I nuke it again. Something is corrupting it.

```
E576: Error while reading ShaDa file: there is an item at position 8182 that must not be there: Missing items are for
internal uses only
```

**Comment by justinmk** [comment]
@Aaronik what nvim `:version` exactly?

**Comment by Aaronik** [comment]
Yeah true here are my deets, @justinmk:

### Neovim version (nvim -v)
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

### Vim (not Nvim) behaves the same?
no it does not, it opens without complaint about the shada file

### Operating system/version
```sh
uname -a
Darwin m24.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:37 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6031 arm64
```

### Terminal name/version
zsh on iterm2: Build 3.4.23
Also happens with zsh on the built-in macos terminal, Version 2.14 (453)

### $TERM environment variable
```sh
echo $TERM
xterm-256color
```

### Installation
via homebrew:

```sh
brew info nvim
==> neovim: stable 0.9.5 (bottled), HEAD
Ambitious Vim-fork focused on extensibility and agility
https://neovim.io/
Installed
/opt/homebrew/Cellar/neovim/0.9.5 (1,737 files, 26.7MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-04-24 at 19:36:33
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/n/neovim.rb
License: Apache-2.0
==> Dependencies
Build: luarocks ✘, cmake ✘, lpeg ✘
Required: libtermkey ✔, gettext ✔, libuv ✔, libvterm ✔, luajit ✘, luv ✔, msgpack ✔, tree-sitter ✘, unibilium ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 22,477 (30 days), 76,631 (90 days), 343,787 (365 days)
install-on-request: 22,283 (30 days), 75,957 (90 days), 341,188 (365 days)
build-error: 1,054 (30 days)
```

**Comment by justinmk** [comment]
> NVIM v0.9.5

Try 0.10

**Comment by Aaronik** [comment]
I've upgraded to 0.10 but am still seeing errors around writing to the shada file. Don't have an error handy but will update this when I find one.

**Comment by aaronik** [comment]
```sh
$ nvim -V1 -v
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1732813678

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.10.2_1/share/nvim"
```

```
Error detected while processing /Users/aaron/suite/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_editor.lua:0: /Users/aaron/suite/nvim/init.lua..nvim_exec2() called at /Users/aaron/suite/nvim/init.lua:0../opt/homebrew/Cellar/neovim/0.10.2_1/share/nvim/runtime/syntax/syntax.vim[44]..BufReadPost Auto
commands for "*": Vim(append):Error executing lua callback: ...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:35: Error executing lua: ...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:36: /Users/aaron/suite/nvim/init.lua..nv
im_exec2() called at /Users/aaron/suite/nvim/init.lua:0../opt/homebrew/Cellar/neovim/0.10.2_1/share/nvim/runtime/syntax/syntax.vim[44]..BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..script /op
t/homebrew/Cellar/neovim/0.10.2_1/share/nvim/runtime/ftplugin/lua.lua: Vim(runtime):E5113: Error while calling lua chunk: Vim:E576: Error while reading ShaDa file: there is an item at position 33259 that must not be there: Missing items are for
internal uses only
stack traceback:
        [C]: in function 'bufload'
        ...eovim/0.10.2_1/share/nvim/runtime/lua/vim/treesitter.lua:39: in function '_create_parser'
        ...eovim/0.10.2_1/share/nvim/runtime/lua/vim/treesitter.lua:108: in function 'get_parser'
        ...eovim/0.10.2_1/share/nvim/runtime/lua/vim/treesitter.lua:416: in function 'start'
        ...llar/neovim/0.10.2_1/share/nvim/runtime/ftplugin/lua.lua:2: in main chunk
        [C]: in function 'nvim_cmd'
        ...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:36: in function <...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        ...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:35: in function <...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:10>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /Users/aaron/suite/nvim/init.lua:90: in main chunk
stack traceback:
        [C]: in function 'nvim_cmd'
        ...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:36: in function <...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        ...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:35: in function <...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:10>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /Users/aaron/suite/nvim/init.lua:90: in main chunk
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:35: in function <...w/Cellar/neovim/0.10.2_1/share/nvim/runtime/filetype.lua:10>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /Users/aaron/suite/nvim/init.lua:90: in main chunk
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /Users/aaron/suite/nvim/init.lua:90: in main chunk
E576: Error while reading ShaDa file: there is an item at position 33259 that must not be there: Missing items are for internal uses only
```

and

```
E576: Error while reading ShaDa file: there is an item at position 33259 that must not be there: Missing items are for internal uses only
E136: Did not rename /Users/aaron/.local/state/nvim/shada/main.shada.tmp.z because /Users/aaron/.local/state/nvim/shada/main.shada does not look like a ShaDa file
E136: Do not forget to remove /Users/aaron/.local/state/nvim/shada/main.shada.tmp.z or rename it manually to /Users/aaron/.local/state/nvim/shada/main.shada.
```

Still happening unfortunately :/
