### ISSUE TITLE
stop at `built target luv-static`  when build neovim from source on Alpine linux(ipad)

### ISSUE THREAD

**Issue by EdwardWong1994** [neovim/neovim#23341]
### Problem

I want to build neovim from source, which can run on my ipad(M2). Previously i use `apk add neovim` to install neovim and the version is `0.8.1` and one plugin for neovim need version at least `0.8.3`. So i decide to build it from source.  But when i install it, it will stop at `build target luv-static` when i use `make -j4 CMAKE_BUILD_TYPE=RelWithDebInfo`.  

Any suggestion for this??

### Steps to reproduce

- `git clone https://github.com/neovim/neovim`
-  `cd neovim`
-  `make -j4 CMAKE_BUILD_TYPE=RelWithDebInfo`

### Expected behavior

i suppose it should configure well and the next step would `make install`

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ipad(M2) using alpine

### Terminal name/version

ish

### $TERM environment variable

xterm-256color

### Installation

from source

**Comment by dundargoc** [comment]
> But when i install it, it will stop at `build target luv-static`

Uhh, I can't do anything with this. Can you upload the full build log to gist perhaps?

**Comment by clason** [comment]
Please check if your platform is [supported by LibUV](https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md).

**Comment by EdwardWong1994** [comment]
> Please check if your platform is [supported by LibUV](https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md).

I did not found it was supported by apline linux. 
![image](https://user-images.githubusercontent.com/96438179/234818629-a65f6e06-eeea-449a-854d-f137e868269f.png)

Is it the reason?

**Comment by EdwardWong1994** [comment]
> > But when i install it, it will stop at `build target luv-static`
> 
> Uhh, I can't do anything with this. Can you upload the full build log to [gist](https://gist.github.com/) perhaps?
> 
> Edit: actually the real error message should show last if you don't build in parallel. What message do you get if you just run `make`

Because i already stop to compile it and use neovim `0.8.1` instead(even though not support for specified plugin).   I do not have the full log information, but i did take a photo when i am runing. 

![2f5235a19a0dc461565f63cff4e2dfe](https://user-images.githubusercontent.com/96438179/234819767-937eaf5a-fab3-4d3d-8ce9-e9f51a660dbc.jpg)


As shown in figure, the configuration will stop at 97%(also did not give errors) and did not give any progress even waiting two hours.

**Comment by clason** [comment]
Yes, then we can't officially support Alpine, either. Things may work, but as you noticed can break anytime. Your best bet is to check the ish support forums if anybody there can give helpful information.
