### ISSUE TITLE
`compute_diff` doc has missing closing paren

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#23357]
### Problem

Missing closing paren: https://github.com/neovim/neovim/blob/1cb60405548e79f1ec63921540e1c3ebb3ddcc01/runtime/doc/lsp.txt#L2137

**Comment by dundargoc** [comment]
@ddickstein I can fix this, but for minor documentation issues like this don't hesitate to just send a quick PR instead 👍

**Comment by mfussenegger** [comment]
I'm not sure why that method is even documented. Afaik the whole sync module was intended as internal

**Comment by clason** [comment]
Seems intentional: https://github.com/neovim/neovim/pull/16285, but that decision can be revisited. Could even mark the function as internal (`_compute_diff`); it's only used in one place in the code.

@gpanders ?

**Comment by dundargoc** [comment]
Closed by https://github.com/neovim/neovim/pull/23416
