### ISSUE TITLE
Mouse stops working after SIGSTOP/CONT

### ISSUE THREAD

**Issue by yshui** [neovim/neovim#2335]
How to reproduce:

1. enable mouse support
2. open nvim
3. press Ctrl-Z
4. fg
5. mouse stops working in nvim

**Comment by Pyrohh** [comment]
Yep, I can reproduce this using `st` from git. It's worth mentioning that when I `fg` back into nvim, mouse support doesn't work, but `:set mouse?` shows `mouse=a`. If I run `set mouse=a` again, then mouse support resumes working.

**Comment by tarruda** [comment]
This happens because tui_stop doesn't save the mouse state. Should be easy an easy fix

**Comment by splinterofchaos** [comment]
@yshui, could you try #2348 and confirm that it fixes this for you?

**Comment by yshui** [comment]
@splinterofchaos Yes, this fix the problem.
