### ISSUE TITLE
cmake failed: lpeg not found

### ISSUE THREAD

**Issue by Izzette** [neovim/neovim#2336]
cmake failed to configure NeoVim.  It could not find lpeg, despite the fact that it is installed.  After running into this error, I uninstalled and re-installed all lua packages and all dependencies, but the error persisted.

Thinking that perhaps the fault was mine, I tried building neovim-git from the AUR using yaourt.  But, that failed to with the same error.

In addition, I pulled the most recent commit and updated my system.  Of course, this did not fix the problem.

I'm running Arch Linux i686:
```
[izzi@localhost NeoVim]$ uname -a
Linux localhost 3.19.2-1-ARCH #1 SMP PREEMPT Wed Mar 18 16:36:01 CET 2015 i686 GNU/Linux
```

cmake threw this error:
```
[izzi@localhost NeoVim]$ cmake .
-- Found Iconv 
-- Checking Lua interpreter /usr/local/bin/lua
-- [/usr/local/bin/lua] The 'lpeg' lua package is required for building Neovim
CMake Error at CMakeLists.txt:246 (message):
  A suitable Lua interpreter was not found


-- Configuring incomplete, errors occurred!
See also "/home/izzi/Development/NeoVim/CMakeFiles/CMakeOutput.log".
See also "/home/izzi/Development/NeoVim/CMakeFiles/CMakeError.log".
```

**Comment by Pyrohh** [comment]
Do you have LuaJIT installed? I'm not sure it's actually needed, but I'm guessing here.

**Comment by Izzette** [comment]
Yes, I do.

**Comment by Izzette** [comment]
I was also able to successfuly instal lua-luajson, which requires lua-lpeg:

```
[izzi@localhost NeoVim]$ yaourt -S lua-luajson
==> WARNING: problem in pkgbuild.sh library
resolving dependencies...
looking for conflicting packages...

Packages (1) lua-luajson-1.3.3-1

Total Download Size:   0.01 MiB
Total Installed Size:  0.05 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages ...
 lua-luajson-1.3.3-1-any                            14.6 KiB   275K/s 00:00 [##########################################] 100%
(1/1) checking keys in keyring                                              [##########################################] 100%
(1/1) checking package integrity                                            [##########################################] 100%
(1/1) loading package files                                                 [##########################################] 100%
(1/1) checking for file conflicts                                           [##########################################] 100%
(1/1) checking available disk space                                         [##########################################] 100%
(1/1) installing lua-luajson                                                [##########################################] 100%
```

**Comment by fwalch** [comment]
```
-- Checking Lua interpreter /usr/local/bin/lua
```

I guess there's your problem.

**Comment by Pyrohh** [comment]
Oh duh, I just realized you're running `cmake .`. Please see https://github.com/neovim/neovim/wiki/Building-Neovim

**Comment by Izzette** [comment]
I removed the repository, cloned it again, and build using make.  This time it succeeded, and I was able to run the application.  Thank you.

It doesn't fully explain the yaourt's failure to build; I guess someone needs to edit the PKGBUILD.

Issue closed

**Comment by fwalch** [comment]
If you tell me what needs to be edited in the PKGBUILD, I can make that happen :wink:

But seriously, are you sure it's not because of your `/usr/local/bin/lua`? If that's found before your `/usr/bin/lua`, it might be the root cause of the problem. Running `make` downloads its own Lua, that's why it isn't affected.

**Comment by Izzette** [comment]
Yeah, that does explain it.  I removed ``/usr/local/bin/lua``, and was able to get past ``cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr`` in the PKGBUILD:
```
-- Checking Lua interpreter /usr/bin/luajit
-- [/usr/bin/luajit] The 'lpeg' lua package is required for building Neovim
-- Checking Lua interpreter /usr/bin/lua
-- Using the Lua interpreter /usr/bin/lua
```
