### ISSUE TITLE
Lua completion API: `vim._expand_pat` has changed behavior since 0.9.0?

### ISSUE THREAD

**Issue by wookayin** [neovim/neovim#23363]
### Problem

I was running into a bug https://github.com/gelguy/wilder.nvim/issues/187 from some plugin that makes use of lua completion API, and found that the reason is the changed behavior of `vim.expand_pat` since 0.9.0.

Specifically, `vim._expand_pat("^vim.ap")` gives different results:

- 0.9.x: `{"api"}, 5`
- 0.8.x: `{"api"}, 4`

The second argument seems to be the length (or 0-based or 1-based index) of the prefix match: although this function is a private function, has the implementation changed by any chance? I looked at the history and git logs at https://github.com/neovim/neovim/commits/master/runtime/lua/vim/_editor.lua but couldn't find any relevant changes.

By the way lua command-line completion in naive neovim (without plugins such as wilder.nvim) have no issues.

### Steps to reproduce

`:lua= vim._expand_pat("^vim.ap")`

### Expected behavior

Explained above.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS, but agnostic to OS

### Terminal name/version

xterm

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by clason** [comment]
> Vim (not Nvim) behaves the same?

> N/A

Please do test with the latest Vim (9.0.1000+); that template is there for a reason.

**Comment by ii14** [comment]
This is a private function.

**Comment by zeertzjq** [comment]
`vim._expand_pat` is not documented and should not be used.

**Comment by clason** [comment]
(In particular, there _is_ no "Lua completion API" (yet).)

**Comment by wookayin** [comment]
Thanks for fast responses! Yes I know this is a private function but I couldn't find any relevant commit/issues so I asked a question/report.

> Please do test with the latest Vim (9.0.1000+); that template is there for a reason.

Well, I thought this is *indeed* not applicable, because vanilla vim does not have `vim._expand_pat` and this only pertains to neovim.


> (In particular, there is no "Lua completion API" (yet).)

Yes, I know this is not "API". Sorry for the confusion -- I found #13719 and was thinking that this is an internal API for lua completion.

**Comment by zeertzjq** [comment]
It was changed in #13834

**Comment by bfredl** [comment]
In particular, there is no longer a dummy `^` char at the start of the string
