### ISSUE TITLE
missing cursor restore for terminals without altscreen

### ISSUE THREAD

**Issue by nikinbaidar** [neovim/neovim#23361]
### Problem

When alternate screen is disabled in my terminal, using `C-z` to send a neovim instance to the background causes rendering in my terminal to break. What happens is my cursor gets returned to somewhere in the middle of the buffer I was before I pressed `C-z`. Expected behavior is to return the cursor and prompt below the buffer that is currently open. I'm pretty sure this did not used to happen before I made the update (from version 0.8 I think) a few weeks ago. I also know this isn't an issue with my terminal because it does not happen with other terminal apps that use alternate screen. 

Here's what I think is relevant from `checkhealth`

```
terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $TERM_PROGRAM="tmux"

tmux ~
- OK escape-time: 0
- WARNING `focus-events` is not enabled. |'autoread'| may not work.
  - ADVICE:
    - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
      set-option -g focus-events on
- $TERM: st-256color
- default-terminal: tmux-256color
- ERROR $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
  - ADVICE:
    - $TERM may have been set by some rc (.bashrc, .zshrc, ...).
```

And my version info:
```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

Moreover, it isn't anything in my config that's causing the issue because `nvim --clean` faces same thing.

### Steps to reproduce

1. As you can see I'm running neovim in a tmux server and in my tmux config I have `set-option -g alternate-screen on`. 
2. From there on just run `nvim` and press `C-z` to send neovim to background.

This the output:
![send](https://user-images.githubusercontent.com/67516675/235049441-b807aed1-1ab4-405a-a8f8-9b55614afd6a.jpg)

### Expected behavior

What used to happen: 

![send](https://user-images.githubusercontent.com/67516675/235049869-7134475a-ce7f-44f7-b60b-0bb6a227fe34.jpg)

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

Did not try

### Operating system/version

6.2.10-arch1-q

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

System package manger (pacman)

**Comment by zeertzjq** [comment]
Do you have alternate screen disable in your terminal but enabled in tmux?

**Comment by nikinbaidar** [comment]
> Do you have alternate screen disabled in st but enabled in tmux?

Nope. It's enabled at both places. I've tried running it only from st as well.

**Comment by zeertzjq** [comment]
Looks like a regression from #22194
