### ISSUE TITLE
Add possibility to override URLs for bundled dependencies

### ISSUE THREAD

**Issue by tudortimi** [neovim/neovim#23366]
### Problem

We have to build neovim in a firewalled environment. My current solution is to download the dependencies manually (e.g. libtermkey), move them into the Linux environment and to patch the `CMakeList` to point to the locations where I copied the tars. The URLs are configured using `set(NAME, VALUE)`. For example:

```
set(LIBTERMKEY_URL https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/libtermkey/0.22-1/libtermkey_0.22.orig.tar.gz)
```

This means they can't be overridden from the command line, so something like `make CMAKE_EXTRA_FLAGS='-DLIBTERMKEY_URL=<some-location>` won't work.

### Expected behavior

I'm not a CMake expert, but the Internet says that making the variables "cached" will allow them to be overridden from the command line: `set(MY_VAR "foo" CACHE STRING "Description of MY_VAR")`. I'm not sure how this is different to an `option()`, though.

**Comment by dundargoc** [comment]
Can you test https://github.com/neovim/neovim/pull/23391?

**Comment by theHamsta** [comment]
> ### Problem
> 
> We have to build neovim in a firewalled environment. My current solution is to download the dependencies manually (e.g. libtermkey), move them into the Linux environment and to patch the `CMakeList` to point to the locations where I copied the tars. The URLs are configured using `set(NAME, VALUE)`. For example:
> 
> ```
> set(LIBTERMKEY_URL https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/libtermkey/0.22-1/libtermkey_0.22.orig.tar.gz)
> ```
> 
> This means they can't be overridden from the command line, so something like `make CMAKE_EXTRA_FLAGS='-DLIBTERMKEY_URL=<some-location>` won't work.
> ### Expected behavior
> 
> I'm not a CMake expert, but the Internet says that making the variables "cached" will allow them to be overridden from the command line: `set(MY_VAR "foo" CACHE STRING "Description of MY_VAR")`. I'm not sure how this is different to an `option()`, though.

The difference between  `set(MY_VAR "foo" CACHE STRING "Description of MY_VAR")` and an `option` is that the type of an option can only be boolean. So it would be equivalent to `set(MY_VAR "foo" CACHE BOOL)`
