### ISSUE TITLE
homebrew:  "Could NOT find Lpeg (missing: LPEG_LIBRARY)" on MacOS m1

### ISSUE THREAD

**Issue by RAV64** [neovim/neovim#23365]
### Problem

Running `brew upgrade neovim --fetch-HEAD` errors with following output

```
==> Upgrading 1 outdated package:
neovim HEAD-d1bb9bf -> HEAD-521e039
==> Fetching neovim
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/fbc0b
####################################################################### 100.0%
==> Downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0
==> Downloading from https://objects.githubusercontent.com/github-production-r
####################################################################### 100.0%
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.2-1.src.rock
####################################################################### 100.0%
==> Cloning https://github.com/neovim/neovim.git
Updating /Users/miki/Library/Caches/Homebrew/neovim--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 521e039f2 vim-patch:partial:8.2.0425: code for modeless selection not sufficiently tested (#23362)
==> Upgrading neovim
  HEAD-d1bb9bf -> HEAD-521e039

==> luarocks make --lua-dir=/opt/homebrew/opt/luajit --tree=/private/tmp/neovi
==> luarocks make --lua-dir=/opt/homebrew/opt/luajit --tree=/private/tmp/neovi
==> cmake -S . -B build -DLIBLUV_LIBRARY=/opt/homebrew/opt/luv/lib/libluv.dyli
Last 15 lines from /Users/miki/Library/Logs/Homebrew/neovim/03.cmake:
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Libuv: /opt/homebrew/opt/libuv/lib/libuv.dylib (Required is at least version "1.28.0")
-- Found Libluv: /opt/homebrew/opt/luv/lib/libluv.dylib (Required is at least version "1.43.0")
-- Found Iconv: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include
CMake Error at /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Lpeg (missing: LPEG_LIBRARY)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLpeg.cmake:10 (find_package_handle_standard_args)
  src/nvim/CMakeLists.txt:29 (find_package)


-- Configuring incomplete, errors occurred!

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!


==> Running `brew cleanup neovim`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /Users/miki/Library/Caches/Homebrew/neovim--mpack--1.0.10.tar.gz... (17.7KB)
Removing: /Users/miki/Library/Caches/Homebrew/neovim--ruby-source--HEAD.rb... (5.9KB)
Removing: /Users/miki/Library/Caches/Homebrew/neovim--lpeg--1.0.2-1.rock... (71KB)
```

### Steps to reproduce

`brew upgrade neovim --fetch-HEAD`

### Expected behavior

Neovim installs and can be started.

### Neovim version (nvim -v)

HEAD-521e039

### Vim (not Nvim) behaves the same?

?

### Operating system/version

MacOS 13.3.1

### Terminal name/version

wezterm 20230427-063511-9bc7de70

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by clason** [comment]
@carlocab probably due to https://github.com/neovim/neovim/pull/23216, but I didn't see at first glance why this should break the homebrew build.

**Comment by RAV64** [comment]
@clason Just tried that and was about to comment on this fixing the issue 👍🏻

**Comment by carlocab** [comment]
I can reproduce this, but uninstalling first then installing doesn't help. Though, `brew upgrade` basically does `brew uninstall && brew install`, so not sure why that would make a difference.

This patch to the formula gets me through configure:
```diff
diff --git a/Formula/neovim.rb b/Formula/neovim.rb
index 46672eccaf4..2195768c9c1 100644
--- a/Formula/neovim.rb
+++ b/Formula/neovim.rb
@@ -88,6 +88,8 @@ class Neovim < Formula
       r.stage(buildpath/"deps-build/build/src"/r.name)
     end
 
+    ENV.append_path "CMAKE_PREFIX_PATH", buildpath/"deps-build"
+
     # The path separator for `LUA_PATH` and `LUA_CPATH` is `;`.
     ENV.prepend "LUA_PATH", buildpath/"deps-build/share/lua/5.1/?.lua", ";"
     ENV.prepend "LUA_CPATH", buildpath/"deps-build/lib/lua/5.1/?.so", ";"
```

However, I then get the following during compilation:
```
ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file '/tmp/neovim-20230428-61372-1uqf0jn/deps-build/lib/lua/5.1/lpeg.so' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libnlua0.so] Error 1
make[1]: *** [src/nvim/CMakeFiles/nlua0.dir/all] Error 2
```
which ostensibly comes from this compiler invocation (split up for readability)
```
clang -O3 -DNDEBUG \
  -arch arm64 \
  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk \
  -mmacosx-version-min=13.3.1 \
  -bundle \
  -Wl,-headerpad_max_install_names \
  -undefined dynamic_lookup \
  -o ../../lib/libnlua0.so \
  CMakeFiles/nlua0.dir/__/mpack/conv.c.o \
  CMakeFiles/nlua0.dir/__/mpack/lmpack.c.o \
  CMakeFiles/nlua0.dir/__/mpack/mpack_core.c.o \
  CMakeFiles/nlua0.dir/__/mpack/object.c.o \
  CMakeFiles/nlua0.dir/__/mpack/rpc.c.o \
  CMakeFiles/nlua0.dir/__/nlua0.c.o \
  /tmp/neovim-20230428-61372-1uqf0jn/deps-build/lib/lua/5.1/lpeg.so
```
No idea why CMake thinks it can/should link with `lpeg.so`, but it shouldn't do that, not on macOS, at least.

This does very much look like #23216, but I won't be able to dig into this until next week.

**Comment by clason** [comment]
Maybe disable HEAD installs for now? Distro HEAD builds are not something we really want to support, and this change won't become relevant for a release until 0.10 (roughly expected this summer), so no urgency.

**Comment by carlocab** [comment]
Yea, here's why:

https://github.com/neovim/neovim/blob/521e039f27dea42653a31a89f2496a0a9e62c43b/cmake.deps/cmake/LpegCMakeLists.txt#L7

LPeg here is built as a library, but that's not equivalent to the output of `luarocks`.

**Comment by clason** [comment]
Since we're trying to get rid of `luarocks` as much as possible, that's expected. But why does Homebrew's build environment care? What needs to be changed?

**Comment by clason** [comment]
Yeah, looks like homebrew needs to add `lpeg` as a standalone formula. (Neovim now exposes LPeg, so this is a new runtime dependency.)

**Comment by carlocab** [comment]
A quick fix wasn't that hard, so I opened Homebrew/homebrew-core#129618 to fix this.

**Comment by clason** [comment]
Fixed downstream by @carlocab (Thanks! ❤️ )

**Comment by danymat** [comment]
Hello, it seems the quickfix did not suffice.
I updated brew without success, same after uninstalling and reinstalling brew (in order to have latest formula).
You can check if it's working in your end by updating to HEAD.
For information, running `vim /opt/homebrew/opt/neovim/.brew/neovim.rb` on my Mac M1 does include latest quickfix

**Comment by clason** [comment]
I just tested it and the build works fine. There must be some issue with your homebrew (or build system). I suggest removing everything, running `brew doctor`, and starting from scratch.

If that doesn't help, please open a new issue with a lot more details.
