### ISSUE TITLE
With title set, buffer title(?) is drawn over split contents

### ISSUE THREAD

**Issue by PonderingGrower** [neovim/neovim#2337]
Hi,

I've been trying to put neovim to use at work, but one issue has been making it very frustrating. Whenever I move between splits(but not only, sometimes just when I just start inserting text) this title-like thing gets drawn right over where I want to start writing and obscures part of the buffer.

Here's a screenshot:

![nvim_draw_issue](https://cloud.githubusercontent.com/assets/2212681/6974908/f4cc7d6a-d996-11e4-8499-80eaaaac7a76.png)

As you can see on the 33rd line in the left split right on the cursor there is this `c.lua (~/dotfiles/.config/awesome) - VIM` that is the 'title' of the right buffer. Similarly 18th line of the right split we can see `nvimrc (~/dotfiles) - VIM` which also obscures the contents of the buffer.

If you need any more information to diagnose this I'll be happy to provide it.

**Comment by Pyrohh** [comment]
Can you reproduce this with a minimal nvimrc (as few plugins as possible)?

**Comment by PonderingGrower** [comment]
I've narrowed it down to the `lazyredraw` option set in my vimrc. Without it set the problem is gone.

Buy my comment tells me I've enabled it because it improves performance when executing long macros. It works fine in vim.

**Comment by justinmk** [comment]
> I've narrowed it down to the lazyredraw option set in my nvimrc. Without it set the problem is gone.

Unless you can reproduce it with `nvim -u NONE -c 'set lazyredraw'`, lazyredraw is not the problem per se. It could be a combination of `:syntax on`, `:set title`, etc.

**Comment by PonderingGrower** [comment]
Okay, so I was wrong yesterday(and sleepy).

Today I reproduced it with with `nvim -u NONE -c 'set title'`. That's all it took:

![nvim_draw_issue2](https://cloud.githubusercontent.com/assets/2212681/6980190/6a6d8512-d9ee-11e4-8704-9adadfa9e3db.png)

That was on b3f07b2468edb02a3104082f6e9730f2c9221c19.

**Comment by tarruda** [comment]
@PonderingGrower what happens if you enter `echo $(tput tsl)Test title$(tput fsl)` in your shell? Does it changes the terminal title?

**Comment by PonderingGrower** [comment]
@tarruda No it does not. My terminal is `urxvt`.

I have tried to reproduce the problem in two other terminals, `terminology` and `xterm` but I couldn't.

**Comment by tarruda** [comment]
What version of urxvt you are using? I use 9.14 which is packaged by ubuntu 12.04 and it works for me

**Comment by PonderingGrower** [comment]
My version is 9.21, packaged for Debian Jessie. But I just went through my `.Xdefaults` and managed to pin down the problem to this option:

    *termName:             screen-256color

I don't remember why it was there, but without it the problem is gone. I guess this was just an unfortunate combination of settings.
