### ISSUE TITLE
`gq` doesn't format comments in C files in particular cases

### ISSUE THREAD

**Issue by fei6409** [neovim/neovim#23381]
### Problem

When I'm working in the Linux kernel repo ([source]), I found that `gq` doesn't format comments and does nothing inside its source `.c` files.
`gq` formats the code itself just fine, but just not the comments (neither block nor line ones)

Some facts I've noticed:
- Seen with both `filetype=c` (`.c` files) and `filetype=cpp` (`.h` files)
- So far, I only see this happens in the Linux kernel repo, that means
  - Editing the files in the repo reproduce the issue.
  - Moving the files out of the repo (i.e. editing as single files) and editing is fine.
  - Moving the files to other random Git repos (e.g. my own dotfiles/) and editing is fine.
- Seen on macOS and Debian, both with Neovim 0.9.0
- I use `neovim/nvim-lspconfig` to set up `clangd`, and the issue is gone by turning off `nvim-lspconfig`
- Seems irrelevant to the existence of `compile_commands.json` - I have that in my Debian setup but not in macOS, both reproducible
- `gq` doesn't work, but `gw` does!
  - This is interesting and informative. Note that `gw` doesn't respect `formatprg` and `formatexpr`, so I checked and found that `formatexpr=v:lua.vim.lsp.formatexpr()` when the issue happens (and `formatprg` is empty BTW), so it must have something to do with `lua.vim.lsp.formatexpr()`. 

I actually tried to dig a little more into the neovim source, but due to my limited knowledge and time I haven't found more.
Happy to learn and help investigate with some support from the experts  :)
(e.g. how neovim devs do print-debug stuff and check the logs in easier way etc)

[source]: https://github.com/torvalds/linux

### Steps to reproduce using "nvim -u minimal_init.lua"

```
# might take some time, can check out the mirror instead 
# https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux
git clone https://github.com/torvalds/linux.git 
cd linux/
nvim -u minimal_init.lua drivers/clk/clk.c
```

Use `J` to combine the block comments in the beginning of the files, and the `gq` to format the comments.

### Expected behavior

`gq` should format the comments without issue, but it does nothing.

### Neovim version (nvim -v)

NVIM v0.9.0 Release

### Language server name/version

Apple clangd version 14.0.0 (clang-1400.0.29.102)

### Operating system/version

macOS

### Log file

https://gist.github.com/fei6409/2146eef47d498dfa4cb0bf43f331199c

**Comment by Bekaboo** [comment]
What does `:echo &formatexpr` shows? If it is `v:lua.vim.lsp.formatexpr()` and LS for c/cpp is attached, then it should be an issue of the language server. From my experience clangd does not format comments.

**Comment by SethBarberee** [comment]
I have some `C` code I've been working with and my comments are formatted just fine with `clangd`. No matter if I use `gq` or `gw`. Using clang 15.0.7 on Arch linux on nvim 0.9

My config in lspconfig:
```lua
        clangd = {
            cmd = {
                "clangd",
                "--background-index",
                "--clang-tidy",
                "--header-insertion=iwyu",
                "-j=8",
                "--malloc-trim",
                --"--offset-encoding=utf-32", -- defaults to utf-16
                "--limit-results=0",
                "--enable-config",
            },
            init_options = {
                clangdFileStatus = true,
            },
        },
```

**Comment by fei6409** [comment]
> What does :echo &formatexpr shows? If it is v:lua.vim.lsp.formatexpr() and LS for c/cpp is attached, then it should be an issue of the language server. From my experience clangd does not format comments.

Right, it's `v:lua.vim.lsp.formatexpr()` and attached to clangd (checked with `print(vim.inspect(vim.lsp.get_active_clients()))`).

But I don't get why the comment formatting works in general cases on my end, but just not in the Linux repo. Agree that it could be a language server issue like you mentioned.

> I have some C code I've been working with and my comments are formatted just fine with clangd. No matter if I use gq or gw. Using clang 15.0.7 on Arch linux on nvim 0.9

Thanks for sharing the config, but sadly that doesn't seem to fix the problem for me...
Tried both clangd 14.0.0 (native) and 15.0.6 (via mason.nvim).

**Comment by mfussenegger** [comment]
> But I don't get why the comment formatting works in general cases on my end, but just not in the Linux repo. Agree that it could be a language server issue like you mentioned.

If it works in general this is very likely a language server problem. Your log also shows errors from the language server:

```
[ERROR][2023-04-29 01:17:26] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[01:17:26.077] Failed to find compilation database for /Users/fei6409/linux/drivers/clk/clk.c\n"
[ERROR][2023-04-29 01:17:26] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[01:17:26.078] ASTWorker building file /Users/fei6409/linux/drivers/clk/clk.c version 25 with command clangd fallback\n[/Users/fei6409/linux/drivers/clk]\n/Library/Developer/CommandLineTools/usr/bin/clang -resource-dir=/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0 -- /Users/fei6409/linux/drivers/clk/clk.c\n"
```
