### ISSUE TITLE
':normal i' hangs nvim on terminal buffer

### ISSUE THREAD

**Issue by HarmtH** [neovim/neovim#2338]
Steps to reproduce:
- Start a :term
- Run cat (optional)
- Go back to normal mode (C-\ C-n)
- Type :normal i [enter]

The reference manual gives a good pointer to the cause (help :normal):
                        ...
                        {commands} should be a complete command.  If
                        {commands} does not finish a command, the last one
                        will be aborted as if [Esc] or [C-C] was typed.
                        This implies that an insert command must be completed
                        (to start Insert mode, see :startinsert).  A ":"
                        command must be completed as well.  And you can't use
                        "Q" or "gQ" to start Ex mode.
                        ...

It seems that nvim keeps sendings escapes to get back to normal mode, and since this does not work, it hangs.

**Comment by drwx** [comment]
yes, the same problem.

**Comment by justinmk** [comment]
Not present on master. Fixed by 2182cd6081af283d3f08c434d00cc634b492033e
