### ISSUE TITLE
Cannot install v0.8.0+ using apt in Ubuntu

### ISSUE THREAD

**Issue by amkhrjee** [neovim/neovim#23387]
### Problem

The `sudo apt install neovim` installs the  v0.6.x, rather than anything latest, which is a deal-breaker when trying to use lazy-nvim.

The current solution remains to build from source.

### Steps to reproduce

`sudo apt install neovim`

### Expected behavior

The latest stable release version should have been installed.

### Neovim version (nvim -v)

0.6.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu  22.04 LTS running in WSL2

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

apt

**Comment by zeertzjq** [comment]
This is an Ubuntu issue.

**Comment by dundargoc** [comment]
[The PPA:s](https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu) are a convenient way to install newer version of neovim on ubuntu (note: not maintained by neovim team).

**Comment by Emrozgs** [comment]
I had this problem in ubuntu and on a mac.
I just ditched package managers like apt and brew altogether and opted to build from source.
Here are the guidelines:

https://github.com/neovim/neovim/wiki/Building-Neovim
