### ISSUE TITLE
`nvim_set_current_win()` throws error in command-line window

### ISSUE THREAD

**Issue by mawkler** [neovim/neovim#23397]
### Problem

`vim.api.nvim_set_current_win()` throws an error if I run it when inside the command-line window.

### Steps to reproduce

1. `nvim --clean`
2. `q:`
3. `:=vim.api.nvim_set_current_win(0)`

Neovim throws the following error:

```
E5108: Error executing lua [string ":lua"]:1: Vim:E11: Invalid in command-line window; <CR> executes, CTRL-C quits
stack traceback:
        [C]: in function 'nvim_set_current_win'
        [string ":lua"]:1: in main chunk
```

### Expected behavior

Neovim doesn't throw an error

### Neovim version (nvim -v)

NVIM v0.9.0

### Vim (not Nvim) behaves the same?

No, Vim doesn't have `vim.api.nvim_set_current_win`

### Operating system/version

Manjaro Linux x86_64

### Terminal name/version

Neovide v. 0.10.4

### $TERM environment variable

tmux-256color

### Installation

AUR

**Comment by zeertzjq** [comment]
This is correct.

**Comment by mawkler** [comment]
Ok I see!
