### ISSUE TITLE
Function callback in Operator-pending mode mapping is not executed on dot-repeat

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#23406]
### Problem

Creating mapping in Operator-pending mode using Lua function directly is not equivalent to using `'<Cmd>lua ...<CR>'` approach.

### Steps to reproduce

1. Create 'init-dot-repeat.lua` file with the following contents:
```lua
_G.n = 0
_G.f = function()
  vim.cmd('normal! v')
  _G.n = _G.n + 1
end

vim.api.nvim_set_keymap('o', 'go', '<Cmd>lua _G.f()<CR>', {})
vim.api.nvim_set_keymap('o', 'gf', '', { callback = _G.f })
```
1. Open Neovim with `nvim -u init-dot-repeat.lua`.
1. Add line `abcde` and put cursor on first character.
1. Press `dgo`. It should delete a character. Running `:=n` shows 1 meaning `_G.f` was executed.
2. Press `.`. It should also delete a character executing `_G.f` (`:=n` shows 2).
3. Press `dgf`. It also deletes a character and executes `_G.f` (`:=n` shows 3).
4. Press `.`. It deletes single character **but not executed `_G.f`** (`:=n` still shows 3). This seems to indicate that `.` here repeats previous edit operation verbatim. This might not be the case if textobject should be recomputed each time (like comment block textobject).

### Expected behavior

Using `'<Cmd>lua ...<CR>'` and Lua function callback act exactly the same.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-227+gfa20c12ba

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.2.13-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
Hmm, dot-repeat isn't implemented for Lua mapping yet.

**Comment by echasnovski** [comment]
Thanks, @zeertzjq!
