### ISSUE TITLE
Neovim: when I execute CocAction to add missing @param, the function below will automatically indent following phpdoc block,

### ISSUE THREAD

**Issue by truongtd94** [neovim/neovim#23402]
### Problem

Neovim: when I execute CocAction to add missing @param, the function below will automatically indent following phpdoc block. Please help me!

### Steps to reproduce

neovim
phpactor
codeactions
add missing @param tags

### Expected behavior

Neovim: when I execute CocAction to add missing @param, the function below will automatically indent following phpdoc block,
This image info:
https://github.com/truongtd94/errors/blob/master/2023-04-30_17-20.png

### Neovim version (nvim -v)

0.9

### Vim (not Nvim) behaves the same?

8.0

### Operating system/version

debian 11

### Terminal name/version

xfce4-terminal

### $TERM environment variable

xterm-256color

### Installation

nvimimage

**Comment by lucario387** [comment]
Which action lead to it? How to reproduce (without needing external plugins)....

**Comment by zeertzjq** [comment]
Check `:help bisect` to bisect your plugins.

Try https://vi.stackexchange.com for questions about usage and configuration.

The issue tracker is for bugs and feature requests.
