### ISSUE TITLE
Vimdoc freezes without `injection.include-children`

### ISSUE THREAD

**Issue by lucario387** [neovim/neovim#23409]
### Problem

Without `injection.include-children` set, opening help file with treesitter attached to it completely freezes neovim

### Steps to reproduce

- Clone neovim from source
- Go to runtime/queries/vimdoc/injections.scm
- Remove `(#set! injection.include-children)`
- `make install`
- nvim --clean
- `:h nvim_create_autocmd()`
- `:lua vim.treesitter.start()`

### Expected behavior

Neovim to not freeze after the attaching treesitter

### Neovim version (nvim -v)

NVIM v0.10.0-dev-233+g066db5e7c-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux linux 6.2.13-zen-1-zen

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

build from source

**Comment by clason** [comment]
Can reproduce this with https://github.com/neovim/neovim/commit/ddd257f75301a50c177fc24a693d39a45b47a689, so not a regression.
