### ISSUE TITLE
use SIGWINCH also to clear the screen without a resize

### ISSUE THREAD

**Issue by github-olivier-abdesselam** [neovim/neovim#23411]
### Problem

sigwinch is not taken into account.
when using with a detach progam, the window does not get refreshed when re-attaching.
This happens with 0.9.0 (but not with 0.8.3)

### Steps to reproduce

When I run neovim within a detach program like [abduco])(https://github.com/martanne/abduco/), via

```bash
$ abduco -e '^g' -A test nvim -u NONE
```

Then I type CTRL+g to detach

And reattach by re-running the previous command:
```bash
abduco -e '^g' -A test nvim -u NONE
```

on several ocassions (so not all the time, but still most of the time on my machine), the screen does not get redrawn

Also sending SIGWINCH has no effect:, so I suspect 0.9.0 introduced a regression in the way SIGWINCH is handled:

```bash
kill -SIGWINCH $(pgrep -f 'nvim -u NONE')
```

I have to press CTRL+L so that vim refreshes.

### Expected behavior

When reattaching / receiving SIGWINCH, terminal should redraw.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

no (9.0.1420)

### Operating system/version

Linux arch 6.2.12-arch1-1

### Terminal name/version

alacritty 0.12.0

### $TERM environment variable

xterm-256color

### Installation

arch linux package manager (pacman)

**Comment by zeertzjq** [comment]
Why do you want this behavior?

**Comment by zeertzjq** [comment]
Oh, actually this make sense.

**Comment by zeertzjq** [comment]
Related: https://github.com/martanne/abduco/issues/30

**Comment by bfredl** [comment]
Not a bug as SIGWINCH behaves as expected (resize when _window_ size _changed_). We could still do this for client that expect it as a workaround, tho for the usecase of abduco the appropriate signals would really be SIGSTOP (stop doing redraws into nowhere upon detachment) and SIGCONT  (refresh screen after attachment and then continue redrawing).

**Comment by zeertzjq** [comment]
SIGSTOP and SIGCONT stops the process from doing anything, so they only make sense if the process does nothing other than redrawing.

**Comment by bfredl** [comment]
Which is exactly what the nvim TUI process does. (also, ideally nvim's multiprocess UI model should already work as "we have abduco at home" but it needs a bit more polish before we can advertise it as such)

**Comment by github-olivier-abdesselam** [comment]
Thanks,

BTW this dos not only impact abduco, this also impacts dtach (which does the same assumptions in winch redraw mode:

```bash
dtach -A /tmp/test -r winch -e '^G' nvim
```
type `^G`
then relaunch previous command.

**Comment by github-olivier-abdesselam** [comment]
on `diss` (dtach like program), to workaround this issue, on client side, here is what I did:

before detaching, send TIOCSWINSZ with width- 1, height - 1

That way when re-attaching + sending TIOCSWINSZ + SIGWINCH, nvim detects a change in size and reacts to sigwinch

https://github.com/yazgoo/diss/commit/fd75b152acd926955b58a45d993291d3264c18fa

**Comment by bfredl** [comment]
anyway let's merge #23415 as a workaround for now

**Comment by justinmk** [comment]
Nvim now has `:detach` / `--remote-ui` /  `:connect` . 

So what is the remaining use-case here? This "feature" complicates stuff, see https://github.com/neovim/neovim/pull/39803

**Comment by justinmk** [comment]
Given that there was no response to my question, I assume this isn't very important, and we will "regress" this for now.

Not goint to spend time trying to support this until the challenges in https://github.com/neovim/neovim/pull/39803 are addressed in a simple and maintainable way.

**Comment by noib3** [comment]
Also, [this comment](https://github.com/neovim/neovim/pull/39773#issuecomment-5105678770) could be useful to gain context around why we decided to regress this.
