### ISSUE TITLE
Distracting Line jumps during :%s

### ISSUE THREAD

**Issue by ColinKennedy** [neovim/neovim#23437]
### Problem

While editing a markdown file, I noticed the Neovim window and cursor "bounces" while typing `:%s/new/asdfasdf` (see the mp4 in the reproduction).

At first I thought the issue was my configuration but then I realized it occurs even when just sourcing `$VIMRUNTIME/syntax/markdown.vim`

https://user-images.githubusercontent.com/10103049/235599290-bec159a9-f243-4f1b-89c6-d9db7c7cd73b.mp4

In the video above, you should see bouncing occurring during editing. Then I restart using nvim -u NONE (which doesn't source the markdown.vim file) and it's fine again.

### Steps to reproduce

If you want to follow along with the posted video, I've made the example file [available via pastebin, here](https://pastebin.com/7qsPKB7g)

```
nvim -u NONE README.md

start typing and erasing asdfasdf
:%s/new/asdfasdf
```

The window should be stable and predictable.
Now call the markdown syntax highlight

```
:so $VIMRUNTIME/syntax/markdown.vim

begin typing and erasing asdfasdf again
:%s/new/asdfasdf
```

Now the screen bounces

### Expected behavior

The same window to be stable and predictable with and without the markdown.vim sourced.

### Neovim version (nvim -v)

NVIM v0.9.0

### Vim (not Nvim) behaves the same?

no, vim 7.4

### Operating system/version

CentOS Linux release 7.9.2009 (Core)

### Terminal name/version

tmux 2.8

### $TERM environment variable

screen-256color

### Installation

appimage --appimage-extract

**Comment by zeertzjq** [comment]
Seems only reproducible if the terminal is slow enough.

**Comment by ColinKennedy** [comment]
I would not know if that's the case but I'm willing to try other terminals if you have a recommendation and let you know how that goes.

**Comment by ColinKennedy** [comment]
Thank you!
