### ISSUE TITLE
Do not nag about pip install neovim or install it as part of make install

### ISSUE THREAD

**Issue by nagisa** [neovim/neovim#2344]
Currently nvim will always print 

> No neovim module found for Python 2.7.9. Try installing it with 'pip install neovim' or see ':help nvim-python'.

if neovim python module is not installed. If it is necessary for neovim to work properly, perhaps it should be installed by default when `make install` is invoked? Otherwise, it should just stop pointing it out every time neovim is launched.

**Comment by Shougo** [comment]
No.  This module is optional.  It is only needed for if_python plugins.

> Otherwise, it should just stop pointing it out every time neovim is launched.

I think your .vimrc has `:has('python')` line.
Yes, the warning message is neccessary for check python.
I will improve the behavior in https://github.com/neovim/neovim/pull/2208.

**Comment by mhinz** [comment]
This would be awesome, since the warning is a little bit annoying for non-Python users. :-)

**Comment by Shougo** [comment]
I improved the behavior in #2208.
