### ISSUE TITLE
Having `default = true` in `nvim_set_hl()` results into unnecessary `cterm= gui=` in output of `:hi`

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#23474]
### Problem

Having `default = true` in `nvim_set_hl()` always adds `cterm= gui=`, although it probably shouldn't and is relatively harmless.

### Steps to reproduce

1. `nvim --clean`
2. `:lua vim.api.nvim_set_hl(0, 'AAA', { default = true })`
3. `:hi AAA`. It shows `AAA            xxx cterm= gui=`. Although I'd expect it to show `AAA            xxx cleared` as is with Vimscript equivalent `:hi default AAA NONE`. 
    Also, `:=vim.api.nvim_get_hl(0, { name = 'AAA' })` shows `vim.empty_dict()`, as expected.
5. `:lua vim.api.nvim_set_hl(0, 'BBB', { default = true, fg = '#ffffff' })`.
6. `:hi BBB` shows `BBB            xxx cterm= gui= guifg=#ffffff` instead of expected `BBB            xxx guifg=#ffffff`. Again, `:=vim.api.nvim_get_hl(0, { name = 'BBB' })` shows `{ fg = 16777215 }`, as expected.

### Expected behavior

Adding `default = true` to options of `nvim_set_hl()` makes no difference on output of `:hi ...`.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-259+g143a17833

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.2.13-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
I think this is a regression from #13250.

**Comment by zeertzjq** [comment]
Also applies to the undocumented `fg_indexed` and `bg_indexed` keys.

**Comment by zeertzjq** [comment]
Hmm, isn't `nvim_get_hl` not returning the `default` flag a bug?
