### ISSUE TITLE
treesitter documentation mistake

### ISSUE THREAD

**Issue by champignoom** [neovim/neovim#23477]
### Problem

https://github.com/neovim/neovim/blob/fe7cdc7cc0037bb41bd940bee7818a5235ffaa79/runtime/lua/vim/treesitter/languagetree.lua#L884-L886

> It will only be passed one argument

This is false. Two arguments will be passed.

https://github.com/neovim/neovim/blob/fe7cdc7cc0037bb41bd940bee7818a5235ffaa79/runtime/lua/vim/treesitter/languagetree.lua#L176
https://github.com/neovim/neovim/blob/fe7cdc7cc0037bb41bd940bee7818a5235ffaa79/runtime/lua/vim/treesitter/languagetree.lua#L267
https://github.com/neovim/neovim/blob/fe7cdc7cc0037bb41bd940bee7818a5235ffaa79/runtime/lua/vim/treesitter/languagetree.lua#L482

### Steps to reproduce

None

### Expected behavior

None

### Neovim version (nvim -v)

irrelevant

### Vim (not Nvim) behaves the same?

irrelevant

### Operating system/version

irrelevant

### Terminal name/version

irrelevant

### $TERM environment variable

irrelevant

### Installation

irrelevant

**Comment by clason** [comment]
PR welcome, no need to raise an issue.
