### ISSUE TITLE
Bugs in man script

### ISSUE THREAD

**Issue by msva** [neovim/neovim#23485]
### Problem

Hi there!

I've found that man.lua author assumed that man pages sections:
1) can be only number: https://github.com/neovim/neovim/blob/master/runtime/lua/man.lua#L742
2) can be only single character: https://github.com/neovim/neovim/blob/master/runtime/lua/man.lua#L586

Both assumptions are wrong: there are so many variations:

```ShellSession
$  ls /usr/share/man/man* -1d
/usr/share/man/man0p/
/usr/share/man/man1/
/usr/share/man/man1p/
/usr/share/man/man2/
/usr/share/man/man2type/
/usr/share/man/man3/
/usr/share/man/man3const/
/usr/share/man/man3head/
/usr/share/man/man3p/
/usr/share/man/man3type/
/usr/share/man/man4/
/usr/share/man/man5/
/usr/share/man/man6/
/usr/share/man/man7/
/usr/share/man/man8/
/usr/share/man/mann/
```

There is not only "most common" `<num>p` sections (which already fails at both this places), but there is also "n" section (still single char, but not a number), and `<num><word>` sections

And if "n" section is "abused" by only tcl/tk-related manpages,
the "worded" ones is part of "default" `man-pages` package.
and "<num>p" ones is even part of "more standard" `man-pages-posix` package.

So, both assumptions are wrong.

Although, on my system it is enough to fix only `1)` to make man in neovim work as expected, I think `2)` should be fixed a well.

Althouth(2), if fix for `1)` is pretty simple (just remove `tonumber()` around `args[1]`) and I can send PR with it in any moment, I'm not sure if changing `man?/` to `man[^/]+/` would be acceptable fix for `2)` :man_shrugging: 

If yes, I can make PR with both fixes ASAP (maybe, after pause about 4-6 hours after posting this ticket)

### Steps to reproduce

`nvim --clean`
`:Man 1p man`
or
`:Man 3type uint8_t`

### Expected behavior

It should open manpage, but not show error that there is no such man page

### Neovim version (nvim -v)

HEAD

### Vim (not Nvim) behaves the same?

no, 9.0.1403

### Operating system/version

any

### Terminal name/version

any

### $TERM environment variable

any

### Installation

any

**Comment by zeertzjq** [comment]
Regression from #22503 @eriks47

**Comment by msva** [comment]
@zeertzjq well, `tonumber()` is (a regression from #22503).
But `man?/` was there since very #19912 :shrug:
