### ISSUE TITLE
Automate release of snap

### ISSUE THREAD

**Issue by hurricanehrndz** [neovim/neovim#23496]
### Problem

This repo should be able to trigger automated release of snaps. What is required is to trigger the update-readme action on the neovim-snap repo. Additionally, workflows permissions need to be set to read/write.
![image](https://user-images.githubusercontent.com/5804237/236580855-fe2bc653-2c1c-4ba3-9c56-406de67e7d0c.png)

### Expected behavior

Automatically release snaps as part of neovim releases

**Comment by hurricanehrndz** [comment]
@dundargoc  Can you please kindly help?

**Comment by dundargoc** [comment]
Sure. I just need to familiarize myself with snaps.

Is the neovim repo and the neovim-snap repo needed for this? And why is this preferable compared to the current setup?

**Comment by bfredl** [comment]
@hurricanehrndz Not sure why _we_ need to set permissions for anything on neovim/neovim. anyone can just watch events occurring on this repo externally.

**Comment by hurricanehrndz** [comment]
Sure if I was on clear, the screenshot is from the neovim-snap repo not this repo.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dundargoc** [comment]
I think having cross-repo triggers like that isn't a good idea. I think it'll makes things difficult to reason about, and I'm also not entirely sure how to achieve this with github actions either (some sort of webhook?). Can the neovim-snap repo not run a job daily that detects if there is a new tag for the neovim repo instead?

**Comment by hurricanehrndz** [comment]
Hmm, I will give that a shot and good thinking. I still require write permission granted to the webhook in the neovim-snap repo.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dundargoc** [comment]
The "Read and write permissions" button is unclickable. I get a "can't click" icon when I hover my mouse over it. Have you tried this yourself?

**Comment by hurricanehrndz** [comment]
Yeah, I don't have permissions to, and says these types of permission may be controlled at the organization level

**Comment by dundargoc** [comment]
OK, I think you're referring to the workflow scope from personal access tokens, which is needed to modify workflows. Out of curiosity, which specific line from the update readme workflow did you need to modify? I took a quick glance at it but didn't see anything hardcoded.

**Comment by hurricanehrndz** [comment]
> OK, I think you're referring to the workflow scope from personal access tokens, which is needed to modify workflows. Out of curiosity, which specific line from the update readme workflow did you need to modify? I took a quick glance at it but didn't see anything hardcoded.

I update the last line of the readme.md file.



> Yes, the "read and write" in the screenshot refers to the general permissions of GITHUB_TOKEN on workflows, not the "workflow" permission specifically which can only be accessed with a Personal Access Token. You can create a token yourself and request it to be included in the neovim-snap repo.
> 
> That being said, the workflow permission is beyond cursed and I can't get it to work. My advice is to call an external shell script from your workflow and then modify that instead. Would this approach work?

Workflow tokens use to work perfectly for updating the last line until there was security changes at the organization level.

**Comment by dundargoc** [comment]
> I update the last line of the readme.md file.

Wait what? You don't need the workflow tokens for that. Can't you just add the required permissions in the workflow file as per https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs?

**Comment by hurricanehrndz** [comment]
I need to be able to add to the commit history. Without the ability to add a commit launchpad refuses to trigger an automatic build.

**Comment by hurricanehrndz** [comment]
I may be able to use a personal access token

**Comment by hurricanehrndz** [comment]
AH you were right:
![image](https://github.com/neovim/neovim/assets/5804237/52669e08-2b1f-451d-b833-679f8f029c54)

**Comment by dundargoc** [comment]
Is this issue resolved?
