### ISSUE TITLE
Setting buffer in another window changes window title

### ISSUE THREAD

**Issue by epithet** [neovim/neovim#23491]
### Problem

When a floating window is opened, the title of the GUI window (in my case, the X11 window, i.e. not the "neovim window") is set according to the buffer inside the floating window.

Examples:
- when an LSP auto-complete popup is shown, the title becomes "[No Name]...".
  NB: this doesn't happen with the built-in Ctrl+n auto-complete.
- workaround https://github.com/dstein64/nvim-scrollview/issues/84

### Steps to reproduce

When executing the command
```sh
nvim --clean -s <(cat <<EOF
    :set title
    :edit /etc/hostname
    :lua \
        vim.schedule(function() \
            local buf = vim.api.nvim_create_buf(false, true) \
            vim.api.nvim_buf_set_name(buf, "FLOATY") \
            vim.api.nvim_open_win(buf, false, { \
                relative = "win", focusable = false, style = "minimal", \
                height = 5, width = 15, row = 5, col = 15, \
            }) \
        end)
EOF
)
```
the title becomes "FLOATY".

NB: this doesn't happen without `vim.schedule`.

Also note that
- the second argument to `nvim_open_win` is `false` (i.e. don't enter the new window) and
- `focusable = false`.

The title is corrected after some operations like e.g. `:edit<cr>`.

### Expected behavior

The title should reflect the current buffer, not the buffer of the unfocussed floating window.

### Neovim version (nvim -v)

NVIM v0.9.0 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

NixOS 22.11

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

alacritty

### Installation

nix package from unstable channel

**Comment by zeertzjq** [comment]
Also applies to `nvim_win_set_buf`

**Comment by epithet** [comment]
that was quick! thanks!
