### ISSUE TITLE
`smoothscroll` + `wrap` + `wincmd w` can draw a copy of the line below the cursor

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#23495]
### Problem

Screen seems to be not redrawn at the switching between windows.

![image](https://user-images.githubusercontent.com/11404453/236553726-042ec0db-c8d8-4001-81b7-0b3901121a58.png)

 

Probably it happens only for some lines. 

### Steps to reproduce

Having `smswrap.lua` with
```lua
vim.wo.sms = true
vim.g.mapleader = ','
vim.go.mouse = 'a'

vim.cmd.help({args = {'sms'}, mods = {tab = 1}})
vim.cmd.vnew()
vim.cmd.wincmd 'w'
vim.api.nvim_win_set_width(0, 52)
vim.cmd.normal('/wrap' .. vim.keycode('<CR>') .. 'zt' .. vim.keycode('<C-e>'))
```
and nvim under `~/tmp/nvim-from-src/bin/nvim` run `~/tmp/nvim-from-src/bin/nvim --clean -u smswrap.lua`. Inside press `<C-w>w` once or more. 

### Expected behavior

Don't draw redundant content (or redraw the view). 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-273+gc8ebb04e9

### Vim (not Nvim) behaves the same?

not checked

### Operating system/version

Debian Sid

### Terminal name/version

kitty 0.26.5-4 + tmux 3.3a-3

### $TERM environment variable

tmux-256color

### Installation

from source

**Comment by przepompownia** [comment]
https://user-images.githubusercontent.com/11404453/236554283-8e0a9f29-290a-4c5c-8e50-8f6699fbd4c7.mp4

The initial scrrencaset was not correct.

**Comment by przepompownia** [comment]
@luukvbaal I did not check how nvim behaves before be11f80d018797b514ed7d01cde2e4c8f88cc8d2

**Comment by luukvbaal** [comment]
I found and fixed the problem. It is present in vim as well, I'll make a patch (probably tomorrow).

**Comment by luukvbaal** [comment]
https://github.com/vim/vim/pull/12350

**Comment by przepompownia** [comment]
Thanks, fixed for me too.
