### ISSUE TITLE
Unable to build neovim - payment required for libtermkey download

### ISSUE THREAD

**Issue by j-xella** [neovim/neovim#23493]
### Problem

I am trying to build neovim, and get this:

```
[  7%] Performing download step (download, verify and extract) for 'libtermkey'
-- verifying file...
       file='/xxxxx/.home/linux/aj_sources/neovim/.deps/build/downloads/libtermkey/libtermkey_0.22.orig.tar.gz'
-- SHA256 hash of
    /xxxxx/.home/linux/aj_sources/neovim/.deps/build/downloads/libtermkey/libtermkey_0.22.orig.tar.gz
  does not match expected value
    expected: '6945bd3c4aaa83da83d80a045c5563da4edd7d0374c62c0d35aec09eb3014600'
      actual: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
-- File already exists but hash mismatch. Removing...
-- Downloading...
   dst='/xxxxx/.home/linux/aj_sources/neovim/.deps/build/downloads/libtermkey/libtermkey_0.22.orig.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/libtermkey/0.22-1/libtermkey_0.22.orig.tar.gz'
CMake Error at libtermkey-stamp/download-libtermkey.cmake:170 (message):
  Each download failed!

    error: downloading 'https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/libtermkey/0.22-1/libtermkey_0.22.orig.tar.gz' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
          --- LOG BEGIN ---
          Uses proxy env variable https_proxy == 'localhost:3122'
    Trying 127.0.0.1:3122...

  Connected to (nil) (127.0.0.1) port 3122 (#0)

  allocate connect buffer

  Establish HTTP proxy tunnel to launchpad.net:443

  CONNECT launchpad.net:443 HTTP/1.1

  Host: launchpad.net:443

  User-Agent: curl/7.86.0

  Proxy-Connection: Keep-Alive



  HTTP/1.1 402 Payment Required

  Cache-Control: no-cache

  Pragma: no-cache

  Content-Type: text/html; charset=utf-8

  Proxy-Connection: Keep-Alive

  Connection: Keep-Alive

  Content-Length: 1268



  The requested URL returned error: 402

  CONNECT phase completed

  Closing connection 0



          --- LOG END ---




make[3]: *** [build/src/libtermkey-stamp/libtermkey-download] Error 1
make[3]: Leaving directory `/xxxxx/.home/linux/aj_sources/neovim/.deps'
make[2]: *** [CMakeFiles/libtermkey.dir/all] Error 2
make[2]: Leaving directory `/xxxxx/.home/linux/aj_sources/neovim/.deps'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/xxxxx/.home/linux/aj_sources/neovim/.deps'
make: *** [deps] Error 2
```

The above happens when I am trying to build the latest version of neovim on my corporate server, at work. And it wasn't like that before. I tried to build neovim at home, and this problem is not happening.

The above suggests that launchpad.net may have recently introduced so sort of IP checks and requires the commerical entities to pay? While I may understand the reasons behind such decision, this adds the whole new level of complexity to the building process. And, while the amount of payment may be reasonable for my company, the amount of paperwork to make it happen may be prohibitive...

So, the question is, are there any alternatives to launchpad, to be used for neovim building?

### Steps to reproduce

make distclean
CC=/path/to/bin/cc make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=/xxxxxx/linux/local

### Expected behavior

Neovim build process downloads all the required dependencies.

### Neovim version (nvim -v)

Commit c14aa66cc

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

Red Hat Enterprise Linux Server release 7.9

### Terminal name/version

tmux

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by clason** [comment]
There's also 
* https://www.leonerd.org.uk/code/libtermkey/
* https://www.leonerd.org.uk/code/libvterm/
 
 but that is even more likely to be blocked.

**Comment by j-xella** [comment]
The problem itself is solvable. In this particular case, I had to download manually the following files:

- https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/libtermkey/0.22-1/libtermkey_0.22.orig.tar.gz
- https://launchpad.net/libvterm/trunk/v0.3/+download/libvterm-0.3.1.tar.gz'
- http://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.0.2.tar.gz

And copy them to the appropriate folders under `.deps/build/downloads`. Then restart the build. 

If anyone has problems accessing the files at the above links, here are these files attached:

- [lpeg-1.0.2.tar.gz](https://github.com/neovim/neovim/files/11409291/lpeg-1.0.2.tar.gz)
- [libvterm-0.3.1.tar.gz](https://github.com/neovim/neovim/files/11409292/libvterm-0.3.1.tar.gz)
- [libtermkey_0.22.orig.tar.gz](https://github.com/neovim/neovim/files/11409293/libtermkey_0.22.orig.tar.gz)

But I wonder.... Neovim developers go as far as putting required dependency file checksums into the build. And those files are relatively small, ~100K. Why not add the whole dependency files to the repository, making the build process more resilient to the problems like this one?

**Comment by dundargoc** [comment]
> Why not add the whole dependency files to the repository

Because it is not necessary.

Test my PR: https://github.com/neovim/neovim/pull/23494

**Comment by j-xella** [comment]
Building the neovim commit 551cc3a2a (head of master ATM). Same error for these dependencies :

> error: downloading 'https://launchpad.net/libvterm/trunk/v0.3/+download/libvterm-0.3.1.tar.gz' failed

**Comment by dundargoc** [comment]
You probably need to remove the cache. Try `make distclean` before.
