### ISSUE TITLE
Wrong file type for netrw

### ISSUE THREAD

**Issue by akyrey** [neovim/neovim#23515]
### Problem

After opening a file from netrw, switching back to netrw itself using `:Ex` displays netrw using the opened file type, for example opening a `.yml` file will display `filetype=yaml` using command `:set ft`
Attaching a screenshot with the problem
![image](https://user-images.githubusercontent.com/16099003/236648402-0bfa117b-e3e0-4773-9547-39c9192e30a9.png)
Also found this on reddit https://www.reddit.com/r/neovim/comments/12ye5rc/lsp_errors_in_netrw_windows/ that i think is related

Currently using version
NVIM v0.10.0-dev-278+ga72e795ed
Build type: Release
LuaJIT 2.1.0-beta3

The problem arose a couple weeks ago, i usually build daily from nightly tag

### Steps to reproduce

1. open a folder using nvim .
2. enter any file with an extension listed (for example test.yml)
3. use the command `:Ex` to go back to netrw
4. the file type is no longer set to `netrw` and the buffer is used like a normal file

### Expected behavior

Switching back to netrw should work just fine

### Neovim version (nvim -v)

NVIM v0.10.0-dev-278+ga72e795ed

### Vim (not Nvim) behaves the same?

Not sure, I don't have it installed

### Operating system/version

5.15.108-1-MANJARO

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-256color

### Installation

build from repo using tag nightly

**Comment by zeertzjq** [comment]
Hmm, this seems to only happen when passing a directory on the command line, not when using `:edit`

**Comment by zeertzjq** [comment]
This bug is no present in v0.9.0. Maybe it is caused by #23256?

**Comment by zeertzjq** [comment]
Reproduced on Vim 9.0.1510. Seem to be a bug from the latest netrw update.

**Comment by zeertzjq** [comment]
Reported at https://github.com/vim/vim/issues/12353

**Comment by wuilliam321** [comment]
@brattonross works like a charm! I hope they merge it asap :)
