### ISSUE TITLE
Neovim exposes an out of spec 'window/progress' lsp notification api

### ISSUE THREAD

**Issue by sigmaSd** [neovim/neovim#23511]
### Problem

Neovim currently sends this notification to server 'window/progress' 

This doesn't exist on the lsp spec, I looked around and there is an extension with the same name but its opposet to nevoim's its server -> client instead of client -> server https://github.com/microsoft/vscode-languageserver-node/pull/261

The usage in neovim is here https://github.com/neovim/neovim/blob/ca5a810c4a67c9c3f482d0c015270c26aee2c943/runtime/lua/vim/lsp/buf.lua#L35 it seems to be used to ping the servers

The problem with this , is if the server is not expecting it , it can cause issue to it, see for example ols where it had to implement specific neovim workaround https://github.com/DanielGavin/ols/issues/188

### Steps to reproduce

this issue have the steps https://github.com/neovim/nvim-lspconfig/issues/2575 (I don't use odin so I didn't test)

### Expected behavior

maybe neovim should use an alternate way to ping servers

### Neovim version (nvim -v)

NVIM v0.10.0-dev-122+g95c6e1b74

### Vim (not Nvim) behaves the same?

specfic to neovim

### Operating system/version

Windows 10

### Terminal name/version

windows terminal

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by clason** [comment]
Note that this function is never actually called in our codebase. Can you provide a minimal reproducing example (without plugins) that triggers this error?

**Comment by glepnir** [comment]
there is no server_ready function call. and that issue has been solved in ols ?

**Comment by sigmaSd** [comment]
Its "solved" in ols by making a custom neovim workaround to ignore this message

**Comment by glepnir** [comment]
did you try the min config ?

**Comment by sigmaSd** [comment]
just to reiterate , the issue is that nvim exposes a broken api , its true it doesn't use it, but it does expose it officially so any plugin developer will assume he can use it

To test this in clean nvim, 
- set up an lsp server, it could be odin, or maybe an easier one rust-analyzer
- edit a file
- run `lua vim.lsp.buf.server_ready()`

In case of ols it will crash (before the latest patch), in case of rust analyzer it will just log the error
![image](https://user-images.githubusercontent.com/22427111/236663751-e048b5c7-5500-4c0e-917f-e9bb39d48d28.png)


I see 2 options here:
- remove the api
- keep it, but document its broken

**Comment by glepnir** [comment]
when you use this before you should check server support it or not support I think . and this method has been removed in vscode-language-server-node . I don't we should keep this `server_ready` .search on github still have this method references. mark it as `deprecated` and remove in next version .

**Comment by sigmaSd** [comment]
this is not the same as `vscode-language-server-node` the only common part is the name

- vscode-language-server-node the message is from server to client
- neovim the message is from client to server

The neovim implementation doesn't exist anywhere, at least the node one is an actual lsp extension that was discussed on the lsp spec repo before

**Comment by glepnir** [comment]
search that pr code in server-node . I can't find it . so I assume this method deleted ? and client-server communication is bidirectional. The client can actively send messages to the server. The server can also actively send messages to the client. I don't know what one-way message you mean.   my suggest is mark as deprecate because it not a part of lsp spec . and the code very simple  if anybody want use it can write this in his local  just send a buf_notify.

**Comment by sigmaSd** [comment]
It seems to be removed indeed, but. when it was implemented it was server -> client https://github.com/microsoft/vscode-languageserver-node/pull/261

**Comment by glepnir** [comment]
Not part of the specification. We have no reason to keep this handler. Prevent misuse from causing some errors. Direct deletion would destroy some existing uses. Wrong though. Anyone who needs to use it can write these three lines of code into their configuration. or some other place.

**Comment by clason** [comment]
> I see 2 options here:
> * remove the api
> * keep it, but document its broken

No, there's a third, better, option: **fix** it. This requires finding out where and for what purpose it is used, which is why I keep asking where this error actually happened.

**Comment by sigmaSd** [comment]
there is no fix, since the spec doesn't mention this (how to check for server readiness)

You can assume the server is ready after receiving a response to initialize request, but that's not the case in practice 

In practice when you send messages (for example for completion), usually servers will return null until they're ready

But all this is just heuristics

**Comment by glepnir** [comment]
this notify has been mark as deprecated. will remove in next version .
