### ISSUE TITLE
Unable to format file with filename `[id].vue` (with brackets)

### ISSUE THREAD

**Issue by soullpoint** [neovim/neovim#23519]
### Problem

Hi there, I am working on a Nuxt.js project and am having trouble formatting Vue files using the Volar language server.

For some context, in Nuxt, the routing of the pages is controlled via the file directory. As part of this, using file names such as `[id].vue` is required to indicate that this should be a route parameter. (https://nuxt.com/docs/guide/directory-structure/pages)

Formatting files where the file name does not include these square brackets appears to be working as expected, however, it seems to be broken for these particular files.

Is this a known limitation, or is there something else happening here?

(Note that I have tried formatting with Volar inside something like VSCode - it appears to work fine, so that might suggest Neovim might be handling things differently)

Any help would be much appreciated.

### Steps to reproduce

- Create .vue file with name `[id].vue`
- Create some basic code, intentionally misformatted, e.g.
```
<template>
  Test the formatter
        </template>
```
- Attempt to run formatting

### Expected behavior

Expected:
- File is formatted correctly by the language server

Actual
- Nothing happens. Nothing seems to appear in the logs.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

unknown, using lua to set things up. don't know how to set up on vim.

### Operating system/version

macos 13.3.1

### Terminal name/version

iterm2

### $TERM environment variable

-

### Installation

homebrew

**Comment by justinmk** [comment]
Related?: https://github.com/neovim/neovim/issues/24233

**Comment by glepnir** [comment]
did you still get this problem ? I can't reproduce it on nightly version.
