### ISSUE TITLE
Stuck in peekkey_simple()

### ISSUE THREAD

**Issue by kpschoedel** [neovim/neovim#23528]
### Problem

I've had neovim hang at 100% CPU about once a week. I think this started with 0.9.0 but I'm not completely certain. This time I attached and took a backtrace:

```
(gdb) bt
#0  0x00005575f8a9a118 in peekkey_simple ()
#1  0x00005575f8a9a113 in peekkey_simple ()
#2  0x00005575f8a9a113 in peekkey_simple ()
⋮
#214 0x00005575f8a9a113 in peekkey_simple ()
#215 0x00005575f8a9a113 in peekkey_simple ()
#216 0x00005575f8a9abc3 in termkey_getkey ()
#217 0x00005575f8a1c278 in tk_getkeys ()
#218 0x00005575f8a1ca3f in handle_raw_buffer ()
#219 0x00005575f8a1cde8 in tinput_read_cb.lto_priv ()
#220 0x00005575f885ed3c in read_event ()
#221 0x00005575f885fbe6 in invoke_read_cb ()
#222 0x00005575f8b4f041 in uv.read ()
#223 0x00005575f8b4f9a0 in uv.stream_io ()
#224 0x00005575f8b55b84 in uv.io_poll ()
#225 0x00005575f8b4494f in uv_run ()
#226 0x00005575f8a2a752 in ui_client_run ()
#227 0x00005575f877201c in main ()
(gdb) generate-core-file
````

[core.3883052.gz](https://github.com/neovim/neovim/files/11416072/core.3883052.gz)

### Steps to reproduce

 I have not noticed any particular action triggering the problem.

### Expected behavior

Not to hang.

### Neovim version (nvim -v)

NVIM v0.9.0 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Linux (Debian 12.0 6.1.0-7-amd64)

### Terminal name/version

mlterm version 3.9.3 post/2023-04-02

### $TERM environment variable

mlterminal

### Installation

https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz

**Comment by kpschoedel** [comment]
I've switched to a local debug build in hope of collecting more information if/when it happens again.

**Comment by dundargoc** [comment]
The nightlies are built with relwithdebinfo if you wanna go that route
