### ISSUE TITLE
Diagnostics option to display virtual text only in current line

### ISSUE THREAD

**Issue by rafamadriz** [neovim/neovim#23526]
### Problem

Sometimes the screen can get quite cluttered and distracting with virtual text from diagnostics everywhere. It would be nice to show virtual text only in current line. I know I can create an autocmd on `CursorHold` to display diagnostics with `open_float()`, but that's not what I'm looking for. It's basically the same problem as https://github.com/neoclide/coc.nvim/issues/1667 

Both `coc.nvim` and `ale` have this option:

coc.nvim: https://github.com/neoclide/coc.nvim/commit/1e41adb9e615421ecf88ba266645df0713986cc0
ale: https://github.com/dense-analysis/ale/blob/9fe9f115213d7e7bf52d06ebdc69c6df38b1120b/doc/ale.txt#L2324

### Expected behavior

Add option to `vim.diagnostic.config()` to show virtual text only in current line

```lua
vim.diagnostic.config({
	current_line_virtual_text = boolean
)}
```

**Comment by luozhiya** [comment]
I have implemented a small [plugin](https://github.com/luozhiya/lsp-virtual-improved.nvim) for this function. You can try it out if you are interested in it.

**Comment by rafamadriz** [comment]
@luozhiya Thanks! I just tried it and maybe I'm missing something but none of the options for `current_line` did what I'm looking for.

**Comment by luozhiya** [comment]
@rafamadriz  Hi,  If I understand correctly, you want to show diagnostics only current line? you can use the settings below
```
local diagnostics = {
  virtual_text = false, -- Disable builtin virtual text diagnostic
  virtual_improved = {
    current_line = 'only',
  },
}
vim.diagnostic.config(diagnostics)
```

**Comment by glepnir** [comment]
```lua
vim.diagnostic.config( {
  virtual_text = false
})

local ns = vim.api.nvim_create_namespace('CurlineDiag')
vim.opt.updatetime = 100
vim.api.nvim_create_autocmd('LspAttach',{
  callback = function(args)
    vim.api.nvim_create_autocmd('CursorHold', {
      buffer = args.buf,
      callback = function()
        pcall(vim.api.nvim_buf_clear_namespace,args.buf,ns, 0, -1)
        local hi = { 'Error', 'Warn','Info','Hint'}
        local curline = vim.api.nvim_win_get_cursor(0)[1]
        local diagnostics = vim.diagnostic.get(args.buf, {lnum =curline - 1})
        local virt_texts = { { (' '):rep(4) } }
        for _, diag in ipairs(diagnostics) do
          virt_texts[#virt_texts + 1] = {diag.message, 'Diagnostic'..hi[diag.severity]}
        end
        vim.api.nvim_buf_set_extmark(args.buf, ns, curline - 1, 0,{
          virt_text = virt_texts,
          hl_mode = 'combine'
        })
      end
    })
  end
})
```

**Comment by glepnir** [comment]
cc @gpanders  how do you think

**Comment by idbrii** [comment]
This feature is now officially supported! Displaying virtual text only in current line was implemented in https://github.com/neovim/neovim/pull/33517 and works for me on v0.11.1. 🥳 

```lua
vim.diagnostic.config{
    virtual_text = { current_line = true, },  -- floating text only next to current line
}
```

FYI, there's also a similar feature to put the diagnostics on lines below the current line.
```lua
vim.diagnostic.config{
    virtual_lines = { current_line = true, },  -- floating text displayed on line below current line
}
```

Don't set both to true or you'll see diagnostics in both places!
