### ISSUE TITLE
Tests failing with "Process does not own terminal"

### ISSUE THREAD

**Issue by Pyrohh** [neovim/neovim#2354]
Here's the [log for `make test`](https://gist.github.com/Pyrohh/733e8a80e173e887e550). I'm not quite sure what to make of it, but it looks related to [this function](https://github.com/neovim/neovim/blob/master/test/functional/job/tty-test.c#L19-22) (which was previously a no-op). I'm running Arch Linux if that makes a difference (something about systemd's process supervision mechanisms maybe?).

**Comment by splinterofchaos** [comment]
I've been having a problem preventing me from running functional tests locally due to freezing and giving me no diagnostics, and also I've been unable to run `build/bin/test-tty`. In order to work out the issues in #2346, I ended up commenting out that function, but I did not realize suddenly being able to run the functional tests was related until I looked at your log!

Do you just run `make test` to get that output?

**Comment by Pyrohh** [comment]
> I've been having a problem preventing me from running functional tests locally due to freezing and giving me no diagnostics

Freezing, eh? Are you sure it's not just slow? Since a little more than a week ago, functional tests have been significantly slower for me (e.g. from ~5 seconds to ~30 seconds).

> Do you just run make test to get that output?

Yes, that's all.

**Comment by splinterofchaos** [comment]
After commenting it out, the tests take about 45 seconds. Otherwise, six tests complete instantly, then nothing.

**Comment by Pyrohh** [comment]
I use Ninja, which might be related to why my tests complete (no idea).

**Comment by Pyrohh** [comment]
@tarruda do you think it could be related to what was mentioned here? https://github.com/neovim/neovim/pull/2263#issuecomment-87281290

**Comment by tarruda** [comment]
> @tarruda do you think it could be related to what was mentioned here? #2263 (comment)

@Pyrohh no, this error is a basic sanity check from the `tty-test` program. It's simply saying that the process is not the session leader, a requirement for programs spawned by a terminal emulator

**Comment by tarruda** [comment]
@Pyrohh are you experiencing this error on master?

**Comment by Pyrohh** [comment]
Yes, I just tried it again.

**Comment by tarruda** [comment]
So if you apply this patch all tests pass?

```diff
diff --git a/test/functional/job/tty-test.c b/test/functional/job/tty-test.c
index 40ba131..4511542 100644
--- a/test/functional/job/tty-test.c
+++ b/test/functional/job/tty-test.c
@@ -18,7 +18,7 @@ bool owns_tty(void)
 #include <unistd.h>
 bool owns_tty(void)
 {
-  return getsid(0) == getpid();
+  return true;
 }
 #endif


```

**Comment by Pyrohh** [comment]
@tarruda yes, and quite quickly.

**Comment by splinterofchaos** [comment]
Yeah, that patch is similar to what I've been doing manually.

**Comment by tarruda** [comment]
`forkpty` man page says the forked process should be a session leader, I wonder if archlinux's libutil is bugged. Does this patch helps?

```diff
diff --git a/src/nvim/os/pty_process.c b/src/nvim/os/pty_process.c
index 9a2721f..69f652a 100644
--- a/src/nvim/os/pty_process.c
+++ b/src/nvim/os/pty_process.c
@@ -1,4 +1,5 @@
 // Some of the code came from pangoterm and libuv
+#include <assert.h>
 #include <stdbool.h>
 #include <stdlib.h>
 #include <string.h>
@@ -182,6 +183,10 @@ void pty_process_resize(Job *job, uint16_t width, uint16_t height)

 static void init_child(Job *job) FUNC_ATTR_NONNULL_ALL
 {
+  if (getsid(0) != getpid()) {
+    assert(setsid() > 0);
+  }
+
   unsetenv("COLUMNS");
   unsetenv("LINES");
   unsetenv("TERMCAP");

```

**Comment by splinterofchaos** [comment]
Sorry I didn't try this sooner. That patch doesn't trigger an assertion, but I still need to comment out `owns_tty()` for the tests to work.

**Comment by tarruda** [comment]
> Sorry I didn't try this sooner. That patch doesn't trigger an assertion, but I still need to comment out owns_tty() for the tests to work.

Ok, I think I have an idea. What is the value of your &shell?

**Comment by splinterofchaos** [comment]
Just sh. But functional tests shouldn't read the users `.nvimrc`, right? (My login shell is fish.)

**Comment by tarruda** [comment]
Terminals will spawn the program with `&sh -c 'CMD'`, so this assumes the -c flag will exec the program  making it the session leader. if the shell forks and waits, the forked program won't be the session leader.

I think `f_termopen` needs to be refactored so it wont use the shell to run commands(and receive argv like `f_jobstart`)

**Comment by splinterofchaos** [comment]
I'll take a stab at this if you're not working on it currently.

**Comment by tarruda** [comment]
> I'll take a stab at this if you're not working on it currently.

Please :smile:

**Comment by splinterofchaos** [comment]
This was pretty trivial to implement (minus a few tests that needed editing), but is it absolutely necessary to be the session leader? The tests now pass for me, but things like
```vim
:terminal ls *
```
now become
```vim
execute 'terminal ls ' . join(expand("*", 0. 1), ' ')
```
Just a sanity check: is this worth it? It looks like `jobstart()` has already switched from using `p_sh`, so at least consistency isn't an issue.

**Comment by tarruda** [comment]
> execute 'terminal ls ' . join(expand("*", 0. 1), ' ')

I meant to only change `termopen` API. `:terminal` and editing `term://` should still use shell. This is how it should translate internally:

- `:terminal ls *` -> `call termopen([&sh, '-c', 'ls *'])`
- `edit term://python` -> `call termopen([&sh. '-c', 'python'])`

>  It looks like jobstart() has already switched from using p_sh, so at least consistency isn't an issue.

`jobstart` never used `&sh`, it was always a lower level function. Ideally `termopen` would be the analogous to `jobstart` that spawns the program in a terminal.

**Comment by splinterofchaos** [comment]
That makes much more sense.

**Comment by tarruda** [comment]
@splinterofchaos just one note about `f_termopen`: It currently uses the first argument as the command string in the buffer title `term://{CWD}/{CMD}:${PID}`. With this new API we'll have to be a little hacky to maintain compatiblity with the current behavior:

- If argv has 3 items, with the first being `p_sh` and the second being `-c`, use argv[2] as the command string
- In all other cases use `argv[0]`.

Just to remember: the `term://` format is used so scripts created with `mksession` can reliably restore terminal buffers.

**Comment by Pyrohh** [comment]
Thanks for your work @splinterofchaos, being able to run tests again without that hack is great :D

**Comment by splinterofchaos** [comment]
Just sorry I ended up delaying the bugfix due to the new feature. :P
