### ISSUE TITLE
Ctrl-P don't work properly

### ISSUE THREAD

**Issue by desmond-rhodes** [neovim/neovim#23543]
### Problem

From :help
```
<Up>            or                                      *<Up>* *CTRL-P*
CTRL-P                  [count] lines upward |linewise|.
```

However, CTRL-P does not actually makes the cursor go upwards. Instead, it "ghostly" moves upward, but not visually. If I press CTRL-P twice, it moves 2 lines up. If I press CTRL-P then h, it moves diagonally up left. Therefore, it is waiting for another input to update the cursor visual.

### Steps to reproduce

I have tested this inside WSL Ubuntu 22.04.2 LTS
- from Windows Terminal
- from CMD
- using appimage from release version 0.9.0
- using apt-get release 0.6.1

I have tested this on Windows
- from nvim-qt
- from nvim CMD
- using win64 msi from release version 0.9.0

All of this on plain unmodified neovim.

### Expected behavior

It should moves the cursor upwards immediately.

---

I am not a plugin user, so I usually use plain vim and/or neovim with init.vim symbolically linked to .vimrc for trivial configurations.

However, recently I have opened myself to experiment with lsp zero. There I notices the action of selecting the previous option for autocomplete, CTRL-P, do not work properly (as described). I then noticed as I experiment with other plugins, such as telescope, the same problem pertain existing.

I have never used the keybind CTRL-P in plain vim or neovim before, and become curious what its function originally is, and it is as described from :help, similar to arrow up, or k.

When I tried the keybind, apparently the problem is not plugin based, but is inherent to neovim itself. The correct behavior pertains in vim. It is only broken in neovim.

### Neovim version (nvim -v)

0.6.0 and 0.9.0

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

Windows 11 + WSL and Windows 11

### Terminal name/version

Windows Terminal and CMD

### $TERM environment variable

xterm-256color

### Installation

appimage and apt-get

**Comment by zeertzjq** [comment]
> I have tested this

What have you tested?

**Comment by zeertzjq** [comment]
What does `:nmap <C-P>` print?

**Comment by desmond-rhodes** [comment]
> What does `:nmap <C-P>` print?

No mapping found

**Comment by desmond-rhodes** [comment]
> > I have tested this
> 
> What have you tested?

CTRL-P, I have tested it on multiple neovim version, from multiple distribution, on multiple environments, and they are consistently performing "ghostly" move cursor up.

**Comment by desmond-rhodes** [comment]
If there is a need for instruction for the simplest step to reproduce,

On a clean ubuntu installation, run
```
cd /tmp
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
./nvim.appimage --appimage-extract
sudo cp -r squashfs-root/usr /
```

Then open neovim, and type this into the buffer
```
abc
def
```

Then on line 2, column 3, in normal mode, press CTRL-P.

The expected behavior is that cursor moves to the letter c, line 1, column 3.
The observed behavior is that cursor stays on the letter f, line 2, column 3.

**Comment by zeertzjq** [comment]
Cannot reproduce on a fresh Ubuntu 22.04 server.

**Comment by desmond-rhodes** [comment]
I am confused because no matter what neovim I tried, it is consistently reproducible.

I'd like to believe it is Windows. However, it is non reproducible in vim. It only affects neovim.

**Comment by felschr** [comment]
In my case it turned out to be due to a missing function caused by a change in the API of `nvim-tree`:
```diff
-vim.keymap.set("n", "<C-p>", require("nvim-tree").toggle)
+vim.keymap.set("n", "<C-p>", require("nvim-tree.api").tree.toggle)
```

I'd assume similar causes for the other people reporting this.

**Comment by justinmk** [comment]
> caused by a change in the API of `nvim-tree`:

People, use `nvim --clean` as the issue template requires.

**Comment by rlpowell** [comment]
I was writing up a bunch of detail about how this definitely isn't resolved, because I can totally repro it with `vim --clean`.

However.

What *I* was seeing turns out to have been an artifact of Podman ( https://github.com/containers/podman/issues/4208 ).  Docker turns out to have the same issue ( https://forums.docker.com/t/ctrl-p-within-docker-container/5232 ).  I wonder if that's what was happening to @desmond-rhodes was seeing (as opposed to what @felschr was seeing, which is clearly different).

Leaving this here for future searchers.

**Comment by santos-lucasm** [comment]
> I was writing up a bunch of detail about how this definitely isn't resolved, because I can totally repro it with `vim --clean`.
> 
> However.
> 
> What _I_ was seeing turns out to have been an artifact of Podman ( [containers/podman#4208](https://github.com/containers/podman/issues/4208) ). Docker turns out to have the same issue ( https://forums.docker.com/t/ctrl-p-within-docker-container/5232 ). I wonder if that's what [@desmond-rhodes](https://github.com/desmond-rhodes) was seeing (as opposed to what [@felschr](https://github.com/felschr) was seeing, which is clearly different).
> 
> Leaving this here for future searchers.

THANKS SO MUCH!
I was having this problem by using `devcontainers-cli`. You guys can update the `~/.docker/config.json` and add the following to remap the detach key to something else.

```
{
    "detachKeys": "ctrl-e,e"
}
```
