### ISSUE TITLE
neovim how to keep the diagnostic message in insert mode?

### ISSUE THREAD

**Issue by cppcoffee** [neovim/neovim#23552]
### Problem

When I upgrade neovim 0.8.3 to 0.9.0, the plugin https://github.com/junnplus/lsp-setup.nvim diagnostic message disappears when the content is entered in insert mode. after exiting insert mode, the diagnostic message appears again, causing the number line to keep resizing.

set numberwith=6 number line will not change the width constantly, but it will appear again when it exceeds 1000 lines

Is this a bug? how to keep the diagnostic message in insert mode?

insert mode and input ';':

![image](https://github.com/neovim/neovim/assets/6635286/d12710bf-a3c2-43e5-a48c-5a096233cb02)

exit insert mode, show diagnostic message, numberwidth changed

![image](https://github.com/neovim/neovim/assets/6635286/8e4a556e-5467-44ac-8d76-3c20ef495c81)

### Steps to reproduce

the plugin config:

```lua
return {
    'junnplus/lsp-setup.nvim',
    event = 'BufRead',
    dependencies = {
        'neovim/nvim-lspconfig',
        'williamboman/mason.nvim',
        'williamboman/mason-lspconfig.nvim',
        'folke/neodev.nvim'
    },
    init = function()
        local rounded = { border = 'rounded' }
        vim.diagnostic.config({ float = rounded })
        vim.lsp.handlers['textDocument/hover'] = vim.lsp.with(vim.lsp.handlers.hover, rounded)
        vim.lsp.handlers['textDocument/signatureHelp'] = vim.lsp.with(vim.lsp.handlers.signature_help, rounded)
    end,
    opts = {
        mappings = {
            gd = function() require('telescope.builtin').lsp_definitions() end,
            gi = function() require('telescope.builtin').lsp_implementations() end,
            gr = function() require('telescope.builtin').lsp_references() end,
            ['<space>f'] = vim.lsp.buf.format,
        },
        servers = {
            eslint = {},
            pylsp = {},
            lua_ls = {
                settings = {
                    Lua = {
                        workspace = {
                            checkThirdParty = false,
                        }
                    }
                }
            },
        }
    },
}
```

### Expected behavior

show the diagnostic message and `numberwidth` no frequently change.

### Neovim version (nvim -v)

NVIM v0.9.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.3.1

### Terminal name/version

wezterm 20230408-112425-69ae8472

### $TERM environment variable

wezterm

### Installation

brew install neovim

**Comment by zeertzjq** [comment]
`vim.diagnostic.config({update_in_insert = true})`

I don't think there is a behavior change between v0.8.3 and v0.9.9.
