### ISSUE TITLE
Treesitter playground bugs out with certain injections

### ISSUE THREAD

**Issue by lucario387** [neovim/neovim#23553]
### Problem

While using `InspectTree` with the file below, moving the cursor inside the tree sometimes raise errors

### Steps to reproduce

Have a `test.lua` file as below
```lua
vim.rpcrequest(0, "nvim_exec_lua", "")
ffi.cdef([[
int x(int a, int b){
}
]])
local x
```

```
nvim --clean test.lua
:lua vim.treesitter.start()
:InspectTree
```
Move the cursor while in the playground tree, specifically around the `(function_call) ; [2:1-14]` node

The error below will be raised:
```
Error detected while processing CursorMoved Autocommands for "<buffer=3>":                                                                                                            
Error executing lua callback: ...cal/share/nvim/runtime/lua/vim/treesitter/playground.lua:342: Invalid 'end_col': out of range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...cal/share/nvim/runtime/lua/vim/treesitter/playground.lua:342: in function <...cal/share/nvim/runtime/lua/vim/treesitter/playground.lua:338>
```

### Expected behavior

To move around normally without error

### Neovim version (nvim -v)

NVIM v0.10.0-dev-304+g84378c4dd

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Archlinux 6.3.1-zen

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

Build from source

**Comment by clason** [comment]
I can't reproduce this. Are you sure you're using the parser and queries in core, not nvim-treesitter?

**Comment by lucario387** [comment]
Wait, the tree is different from my version, so probably because it's picking the tree in `stdpath('data')/site`...
