### ISSUE TITLE
upgrade neovim 0.8.3 to 0.9.0 and font-hack-nerd-font, the font displayed by number appears overflow

### ISSUE THREAD

**Issue by cppcoffee** [neovim/neovim#23551]
### Problem

Updated neovim 0.8.3 => 0.9.0 and font-hack-nerd-font. use https://github.com/folke/todo-comments.nvim plugin and Hack Nerd Font, config font_size=12, the font displayed by number appears overflow. As shown below, the insertion cursor is positioned in the middle of the tick box.

<img width="223" alt="1" src="https://github.com/neovim/neovim/assets/6635286/b2d32e34-7e32-42c8-85d5-42c0baba88a2">

### Steps to reproduce

config file:

```
return {
    'folke/todo-comments.nvim',
    event = 'VeryLazy',
    dependencies = {
        'nvim-lua/plenary.nvim',
    },
    opts = {
        highlight = {
            -- bg conflects with linehl of gitsigns
            keyword = 'fg',
            after = '',
        },
    }
}
```

### Expected behavior

Display not out of range.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.3.1

### Terminal name/version

wezterm 20230408-112425-69ae8472

### $TERM environment variable

wezterm

### Installation

brew install neovim

**Comment by cppcoffee** [comment]
use neovim 0.8.3:

<img width="174" alt="image" src="https://github.com/neovim/neovim/assets/6635286/d78a82f2-7216-4fb9-9da3-9e39d7a0c843">

**Comment by cppcoffee** [comment]
the lewis6991/gitsigns.nvim plugin has same problem on neovim 0.9.0

**Comment by cppcoffee** [comment]
0.9.0 `:echo &statuscolumn` print:

```
%!v:lua.StatusCol()
```

**Comment by cppcoffee** [comment]
my neovim config in the https://github.com/cppcoffee/dotfiles/tree/main/nvim

**Comment by zeertzjq** [comment]
If you run Nvim v0.9.0 with `nvim -V1`, what does `:verbose set statuscolumn?` print?

**Comment by cppcoffee** [comment]
I run nvim v0.9.0 with `nvim -V1`, `:verbose set statuscolumn?` print:

```
statuscolumn=%!v:lua.StatusCol()
	Last set from ~/.local/share/nvim/lazy/statuscol.nvim/lua/statuscol.lua line 442
```

**Comment by luukvbaal** [comment]
Yes, that plugin expects single cell width characters if you set `colwidth` to 1 for a sign sigment. It is the users' responsibility to make sure that all signs used in a sign segment are indeed single width. (Though I'm not sure what's actually responsible for clipping the double-width character.)
