### ISSUE TITLE
Error when open Neovim in folder contains .editorconfig

### ISSUE THREAD

**Issue by Mcbeany** [neovim/neovim#23554]
### Problem

```
Error detected while processing BufNewFile Autocommands for "*":
Error executing lua callback: root must be either "true" or "false"
stack traceback:
        [C]: in function 'error'
        /usr/share/nvim/runtime/lua/editorconfig.lua:13: in function 'assert'
        /usr/share/nvim/runtime/lua/editorconfig.lua:192: in function 'parse'
        /usr/share/nvim/runtime/lua/editorconfig.lua:218: in function 'config'
        /usr/share/nvim/runtime/plugin/editorconfig.lua:11: in function </usr/share/nvim/runtime/plugin/editorconfig.lua:4>
```

### Steps to reproduce

Change the directory to folder that contains .editorconfig file
Open Neovim

### Expected behavior

Nothing happens

### Neovim version (nvim -v)

v0.10.0-dev

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu

### Terminal name/version

Wezterm

### $TERM environment variable

xterm-256color

### Installation

system package manager (using PPA)

**Comment by VictorGSoutoXP** [comment]
The error you are facing seems to be related to the EditorConfig plugin of Neovim. It appears that there is an issue with the configuration of the .editorconfig file in your current directory.
To solve this error, you can try the following:
Check if the .editorconfig file in your current directory is configured correctly. Check if the root is set to "true" or "false". If you are not sure what this means, refer to the EditorConfig documentation.Try updating the EditorConfig plugin to the latest version. This can be done by running the following command in the terminal: sudo apt-get update && sudo apt-get upgrade neovim. If the issue persists, try temporarily disabling the EditorConfig plugin to see if the error disappears. You can do this by commenting out or removing the corresponding line from the Neovim configuration file (usually init.vim).

**Comment by clason** [comment]
Thank you, ChatGPT!

**Comment by Mcbeany** [comment]
I just realized it was my configuration error, sorry

**Comment by huyz** [comment]
Hmm, I got this error when I tried to do an inline comment:
```ini
root = true  # top-most EditorConfig file
```

I wish there had been a more intelligible error message…

**Comment by deromax** [comment]
I resolved the issue by removing an accidental `;`.

```diff
- root = true;
+ root = true
```
