### ISSUE TITLE
Binary file added by commit

### ISSUE THREAD

**Issue by jalvesaq** [neovim/neovim#2356]
The commit https://github.com/neovim/neovim/commit/34dba3d7cd43b4797d60f636dc9c7c3040a56f3c added the Vim swap file src/nvim/.screen.c.swn

**Comment by jszakmeister** [comment]
Gak!  Fixed in a69e464f70f1f26c352b713f70b627ea07232e79.  I also changed the gitignore rule to help prevent this in the future.  Thanks!

**Comment by bfredl** [comment]
This is what happens when I commit stuff to master before lunch. Thanks @jszakmeister for fixing it.

**Comment by jszakmeister** [comment]
No worries, stuff happens. :-)
