### ISSUE TITLE
expose leftcol of a window

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#23567]
### Problem

hi folks, the usecase is that i want to get the content of current visible region of a window, so the leftcol matters. but i failed to find a way to get it.

### Expected behavior

maybe it can be added into the `fn.getwininfo()`, thus no new api and no break change happen.

**Comment by zeertzjq** [comment]
`winsaveview()` works for current window. For non-current window it's not very convenient.

**Comment by haolian9** [comment]
oh, sorry!
