### ISSUE TITLE
Filetype detection causes file with large indent in first line to hang

### ISSUE THREAD

**Issue by joaomsa** [neovim/neovim#23563]
### Problem

Filetype detection causes file with large indent in first line to use 100% cpu and hang

### Steps to reproduce

python3 -c 'print(" " * (2**19) + "test")' >test

nvim --clean test # hangs

nvim --clean -c "filetype off" -c "edit test" # loads instantly

### Expected behavior

Editor should open quickly instead of hanging
Perhaps timing out filetype detection, and notifying the user so he can at least edit the file

### Neovim version (nvim -v)

0.9.0 Release

### Vim (not Nvim) behaves the same?

no, vim 9.0.1313 loads instantly

### Operating system/version

macOS 13.3.1

### Terminal name/version

terminal.app

### $TERM environment variable

screen-256color

### Installation

nix-env

**Comment by zeertzjq** [comment]
This has already been fixed by #23175
