### ISSUE TITLE
Terminal title is not set correctly when resuming from background

### ISSUE THREAD

**Issue by amarshall** [neovim/neovim#23575]
### Problem

- This is reproducible on recent master (03ca36d1f8d027c95edd46f3127284e9a3577990)
- I have bisected this (v0.8.0..v0.9.0), and identified merge commit 24488169564c39a506c235bf6a33b8e23a8cb528 (https://github.com/neovim/neovim/pull/18375) to be the change that introduced this behavior
- To rule out packaging problem, I have also reproduced this in an archlinux container image running Neovim v0.9.0
- To rule out a terminal emulator specific issue, I have also reproduced this in foot 1.14.0
- To rule out an OS-specific issue, I have reproduced also this on macOS 13.3.1

### Steps to reproduce

1. Ensure terminal emulator shows the “title” in some way
2. `env -i TERM=ansi-256color nvim --clean --cmd 'set title'` (or `env -i TERM=$TERM …`)
3. Observe the terminal title set by nvim
4. Suspend with <kbd>ctrl</kbd><kbd>z</kbd>
5. Resume with `fg`
6. Compare the terminal title set by nvim in ③

### Expected behavior

**Expect**: terminal title is the same as before suspend (e.g. `[No Name] - NVIM`).
**Actual**: terminal title is not expected, and is instead set by terminal emulator (typically to `fg` as that is the running command)

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

no, vim 9.0.1441

### Operating system/version

NixOS

### Terminal name/version

Kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

Nix

**Comment by zeertzjq** [comment]
I can reproduce this when using bash or zsh, but not when using fish.

**Comment by zeertzjq** [comment]
There seems to be a data race. Sometimes the title is set, and with an ASAN build it is always set.
