### ISSUE TITLE
nvim fails to leave insert mode

### ISSUE THREAD

**Issue by Mongey** [neovim/neovim#2358]
![nvim](https://cloud.githubusercontent.com/assets/625787/6997646/65202e30-db78-11e4-9e75-ad408994a666.gif)

* Launched with `nvim -u NONE`
* Enter insert mode
* Type hello world
* Hit `ESC` followed by j ( produces `ê` )
* Subsequent keystrokes are `ESC` followed by another character

NVIM version info
```
NVIM 0.0.0-alpha+201504030905 (compiled Apr  3 2015 22:04:17)
Commit: 94153ab975401572ea6942b4fba8dcfba53ceecc
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused
-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neo
vim20150403-14696-57207/build/config -I/tmp/neovim20150403-14696-57207/src -I/tmp/neovim20150403-1469
6-57207/.deps/usr/include -I/tmp/neovim20150403-14696-57207/.deps/usr/include -I/tmp/neovim20150403-1
4696-57207/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150403-14696-57207/.deps/usr/include -I/tmp/ne
ovim20150403-14696-57207/.deps/usr/include -I/tmp/neovim20150403-14696-57207/.deps/usr/include -I/usr
/local/opt/gettext/include -I/usr/include -I/tmp/neovim20150403-14696-57207/build/src/nvim/auto -I/tm
p/neovim20150403-14696-57207/build/include
```

**Comment by glts** [comment]
Seems to be the same as #2093.

I can easily reproduce this. Any ideas how best to debug this?

**Comment by Mongey** [comment]
@glts whoops, missed that issue in my search. adding `set -g escape-time 20` to my tmux config fixes this. Closing now.

**Comment by glts** [comment]
@Mongey Yep, just finished reading through that issue and `set -g escape-time 20` fixes it for me as well.

**Comment by Mongey** [comment]
@glts :+1: Thanks for pointing me to the correct issue :tada:

**Comment by philix** [comment]
This problem is affecting all tmux users. I had to work around this as well and it took me some time to find that issue. @justinmk what can be done to fix it or to at least inform users?
