### ISSUE TITLE
setting `&modified = false` has no effect in prompt_setcallback()

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#23594]
### Problem

hi folks, the problem is that setting `&modified = true` in the callback passed to fn.prompt_setcallback() does not work as its doc said.

(the `vim.schedule` magic in my previous issue reminds me this problem i met weeks ago, which can also be a workaround for this issue, so i think it's worth to report it.)

### Steps to reproduce

* `nvim --clean +'so test.lua'`

<details>

<summary>the test.lua</summary>

```
local api = vim.api

local bufnr = api.nvim_create_buf(false, true)

local bo = vim.bo[bufnr]
bo.buftype = "prompt"
bo.bufhidden = "wipe"

vim.fn.prompt_setcallback(bufnr, function(cmd)
  api.nvim_buf_set_lines(bufnr, -2, -1, false, { cmd })
  bo.modified = false
end)

api.nvim_open_win(bufnr, true, { relative = "editor", row = 3, col = 3, width = math.floor(vim.o.columns * 0.8), height = math.floor(vim.o.lines * 0.6), style = "minimal" })
vim.cmd.startinsert()
```

</details>

### Expected behavior

`bo.modified = false` will be honored.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

tmux-256color

### Installation

archlinux's community repo

**Comment by zeertzjq** [comment]
I don't think this is bug. The documentation seem to put `set nomodified` in the wrong branch. It should be https://github.com/vim/vim/pull/12382/files

**Comment by haolian9** [comment]
thank! the doc makes sense to me now.

and it would be great if nvim supports `set bufype=prompt,nowrite`.
