### ISSUE TITLE
Cursor movement slow when CurSearch highlight group is set

### ISSUE THREAD

**Issue by MrJulianBlack** [neovim/neovim#23590]
### Problem

When The CurSearch highlighting group is specified, and a search is currently active, cursor movement, even just on the same line, and even on lines not containing a search result will be extremely laggy. 

### Steps to reproduce

- `nvim -u --noplugin --clean someFile`
- `:colorscheme blue`
- `/someWord`

This happens for me without plugins (`nvim -u --noplugin`)  and already on very small files (60 lines for example). 
I can work around the issue by running `:noh`, or `:hi clear CurSearch`.

I first discovered this when noticing some colorschemes had this slowdown while others don't. For example, the default does not, but with "blue" scheme i experience it. 

### Expected behavior

I would not expect a slowdown of this type. Obviously, i can just disable the highlighting, and I will if this is expected, but it seems unintentional. I understand however, that this feature naturally comes with a calculation-overhead.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

not checked

### Operating system/version

6.3.1-arch2-1

### Terminal name/version

Konsole/Alacritty

### $TERM environment variable

xterm-256color

### Installation

System package Manager

**Comment by zeertzjq** [comment]
Can you also observe a similar slow movement with 'cursorcolumn' enabled?

**Comment by mike-lloyd03** [comment]
I am having this same problem. Running with the `--clean` flag doesn't help. The following colorschemes seem to work fine, all others are very slow. 

- default
- quiet

__nvim version__: 0.9.0
__OS__: Linux 6.3.2-arch1-1 x86_64 GNU/Linux
__Terminal emulator__: Happens on alacritty and kitty

__Other relevant info__: This only happens when ssh'd into a Linux VM running on my work Mac laptop. On my personal Linux laptop, when ssh'd onto my Linux homeserver, or when running nvim on the host Mac the problem is not apparent.

**Comment by Gobbel2000** [comment]
I have also observed this, here are some further details:

* It only happens when the CurSearch highlighting group is set, even if it just links to Search, as in `:color blue`. 
* On my PC I only see a CPU usage spike to around 5-10% in htop when moving around. Otherwise it's not noticeable. But on a Raspberry Pi 4 through SSH it causes very significant display stutter.
* The CPU spike happens in the `nvim --embed <filename>` child process. 
* Using treesitter highlighting exacerbates the issue, this could indicate that the syntax highlighting is fully recalculated on every move.
* In vim no CPU usage spike occurs under the same circumstances (hls and CurSearch highlighting set).

**Comment by kaihowl** [comment]
I observe the same behavior (slow scrolling when search highlight is active) in `asciidoc` files. I don't see this behavior in for example larger c++ source files.

This is my `syntime` output for navigating ~10 single lines down with `j` on an `asciidoc` file:

```
TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
  4.291246   4062   2044    0.005350    0.001056  asciidocMacroAttributes \(\\\@<!{\w\(\w\|[-,+]\)*\([=!@#$%?:].*\)\?}\)\@<=\S\{-}\[
  0.137274   2074   112     0.000541    0.000066  asciidocMacroAttributes [\\0-9a-zA-Z]\@<!\w\(\w\|-\)*:\S\{-}\[
  0.053995   2996   0       0.000163    0.000018  asciidocList       \(^[=*]\{4,}$\)\@=
  0.053259   2996   112     0.000095    0.000018  asciidocList       \(^\(+\|--\)\?\s*$\)\@=
  0.038396   1234   0       0.000720    0.000031  asciidocLiteralParagraph \(\%^\|\_^\s*\n\)\@<=\s\+\S\+
 [...]

  4.858304   116182
```

<details>
<summary>Full Output</summary>

```
TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
  4.291246   4062   2044    0.005350    0.001056  asciidocMacroAttributes \(\\\@<!{\w\(\w\|[-,+]\)*\([=!@#$%?:].*\)\?}\)\@<=\S\{-}\[
  0.137274   2074   112     0.000541    0.000066  asciidocMacroAttributes [\\0-9a-zA-Z]\@<!\w\(\w\|-\)*:\S\{-}\[
  0.053995   2996   0       0.000163    0.000018  asciidocList       \(^[=*]\{4,}$\)\@=
  0.053259   2996   112     0.000095    0.000018  asciidocList       \(^\(+\|--\)\?\s*$\)\@=
  0.038396   1234   0       0.000720    0.000031  asciidocLiteralParagraph \(\%^\|\_^\s*\n\)\@<=\s\+\S\+
  0.037466   2018   0       0.000112    0.000019  asciidocEmail      [\\.:]\@<!\(\<\|<\)\w\(\w\|[.-]\)*@\(\w\|[.-]\)*\w>\?[0-9A-Za-z_]\@!
  0.017350   1234   0       0.000129    0.000014  asciidocDoubleDollarPassthrough \\\@<!\(^\|[^0-9a-zA-Z$]\)\@<=\$\$..\{-}\(\$\$\([^0-9a-zA-Z$]\|$\)\@=\|^$\)
  0.016812   3530   1512    0.000111    0.000005  asciidocQuotedMonospaced2 \(^\|[| \t([.,=\]]\)\@<=`\([` \n\t]\)\@!\(.\|\n\(\s*\n\)\@!\)\{-}\S\(`\([| \t)[\],.?!;:=]\|$\)\@=\)
  0.016636   1234   0       0.000132    0.000013  asciidocTriplePlusPassthrough \\\@<!\(^\|[^0-9a-zA-Z$]\)\@<=+++..\{-}\(+++\([^0-9a-zA-Z$]\|$\)\@=\|^$\)
  0.014950   2018   0       0.000058    0.000007  asciidocQuotedSingleQuoted \(^\|[| \t([.,=\]]\)\@<=`\([` \n\t]\)\@!\([^`]\|\n\(\s*\n\)\@!\)\{-}[^` \t]\('\([| \t)[\],.?!;:=]\|$\)\@=\)
  0.012278   2018   0       0.000135    0.000006  asciidocURL        \\\@<!\<\(http\|https\|ftp\|file\|irc\):\/\/[^| \t]*\(\w\|\/\)
  0.009503   2018   0       0.000035    0.000005  asciidocListLabel  \(:\{2,4}\|;;\)$
  0.008753   3362   1344    0.000026    0.000003  asciidocAttributeRef \\\@<!{\w\(\w\|[-,+]\)*\([=!@#$%?:].*\)\?}
  0.008480   2102   84      0.000167    0.000004  asciidocQuotedEmphasized \(^\|[| \t([.,=\]]\)\@<=_\([_ \n\t]\)\@!\(.\|\n\(\s*\n\)\@!\)\{-}\S\(_\([| \t)[\],.?!;:=]\|$\)\@=\)
  0.008095   1234   0       0.000061    0.000007  asciidocList       .\+\(:\{2,4}\|;;\)$
  0.007848   2018   0       0.000352    0.000004  asciidocQuotedSuperscript \\\@<!\^\S\_.\{-}\(\^\|\n\s*\n\)
  0.007780   2018   0       0.000026    0.000004  asciidocQuotedAttributeList \\\@<!\[[a-zA-Z0-9_-][a-zA-Z0-9 _-]*\][+_'`#*]\@=
  0.007774   2018   0       0.000075    0.000004  asciidocMacroAttributes \\\@<!<<"\{-}\(\w\|-\|_\|:\|\.\)\+"\?,\?
  0.007669   2018   0       0.000039    0.000004  asciidocQuotedUnconstrainedEmphasized \\\@<!__\S\_.\{-}\(__\|\n\s*\n\)
  0.007301   2018   0       0.000078    0.000004  asciidocQuotedDoubleQuoted \(^\|[| \t([.,=\]]\)\@<=``\([` \n\t]\)\@!\(.\|\n\(\s*\n\)\@!\)\{-}\S\(''\([| \t)[\],.?!;:=]\|$\)\@=\)
  0.007271   2018   0       0.000027    0.000004  asciidocMacroAttributes \\\@<!\[\{3}\(\w\|-\|_\|:\|\.\)\+
  0.007146   2018   0       0.000028    0.000004  asciidocMacroAttributes \\\@<!(\{2,3}
  0.007122   2018   0       0.000057    0.000004  asciidocMacroAttributes \\\@<!\[\{2}\(\w\|-\|_\|:\|\.\)\+,\?
  0.007026   2018   0       0.000028    0.000003  asciidocQuotedBold \(^\|[| \t([.,=\]]\)\@<=\*\([* \n\t]\)\@!\(.\|\n\(\s*\n\)\@!\)\{-}\S\(\*\([| \t)[\],.?!;:=]\|$\)\@=\)
  0.006993   2018   0       0.000043    0.000003  asciidocQuotedUnconstrainedBold \\\@<!\*\*\S\_.\{-}\(\*\*\|\n\s*\n\)
  0.006913   2018   0       0.000063    0.000003  asciidocEntityRef  \\\@<!&[#a-zA-Z]\S\{-};
  0.006873   2018   0       0.000025    0.000003  asciidocQuotedSubscript \\\@<!\~\S\_.\{-}\(\~\|\n\s*\n\)
  0.006807   2018   0       0.000089    0.000003  asciidocQuotedMonospaced \(^\|[| \t([.,=\]]\)\@<=+\([+ \n\t]\)\@!\(.\|\n\(\s*\n\)\@!\)\{-}\S\(+\([| \t)[\],.?!;:=]\|$\)\@=\)
  0.006730   2018   0       0.000028    0.000003  asciidocQuotedEmphasized2 \(^\|[| \t([.,=\]]\)\@<='\([' \n\t]\)\@!\(.\|\n\(\s*\n\)\@!\)\{-}\S\('\([| \t)[\],.?!;:=]\|$\)\@=\)
  0.006537   2018   0       0.000064    0.000003  asciidocQuotedUnconstrainedMonospaced [\\+]\@<!++\S\_.\{-}\(++\|\n\s*\n\)
  0.005143   1234   86      0.000046    0.000004  asciidocTwoLineTitle ^[^. +/].*[^.]\n[-=~^+]\{3,}$
  0.005101   2018   0       0.000040    0.000003  asciidocLineBreak  [ \t]+$
  0.004100   1346   0       0.000025    0.000003  asciidocCallout    \\\@<!<\d\{1,2}>
  0.003344   1094   0       0.000030    0.000003  asciidocHLabel     \(::\|;;\)\(\s\+\|\\$\)
  0.001029   2914   896     0.000012    0.000000  asciidocListBullet ^\s*\zs\(-\|\*\{1,5}\)\ze\s
  0.000939   2018   0       0.000010    0.000000  asciidocListNumber ^\s*\zs\(\(\d\+\.\)\|\.\{1,5}\|\(\a\.\)\|\([ivxIVX]\+)\)\)\ze\s\+
  0.000616   3138   2158    0.000004    0.000000  asciidocListLabel  ^\s*
  0.000612   784    784     0.000004    0.000001  asciidocMacroAttributes \]\|^$
  0.000602   1234   0       0.000022    0.000000  asciidocList       ^\s*\(\(\d\+\.\)\|\.\{1,5}\|\(\a\.\)\|\([ivxIVX]\+)\)\)\s\+
  0.000512   1234   0       0.000012    0.000000  asciidocFilterBlock ^\w*\~\{4,}$
  0.000507   1234   140     0.000014    0.000000  asciidocList       ^\s*\(-\|\*\{1,5}\)\s
  0.000392   1234   0       0.000008    0.000000  asciidocAdmonition ^\u\{3,15}:\(\s\+.*\)\@=
  0.000365   1402   1234    0.000005    0.000000  asciidocHLabel     ^\s*
  0.000349   2018   114     0.000012    0.000000  asciidocAttributeList ^\[[^[ \t].*\]$
  0.000335   1234   0       0.000004    0.000000  asciidocTable_OLD  ^\([`.']\d*[-~_]*\)\+[-~_]\+\d*$
  0.000255   1234   84      0.000004    0.000000  asciidocOneLineTitle ^=\{1,5}\s\+\S.*$
  0.000232   2018   56      0.000001    0.000000  asciidocListingBlock ^-\{4,}$
  0.000226   2018   0       0.000002    0.000000  asciidocCommentLine ^//\([^/].*\|\)$
  0.000134   1234   0       0.000003    0.000000  asciidocBlockTitle ^\.[^. \t].*[^-~_]$
  0.000121   1234   0       0.000003    0.000000  asciidocOpenBlockDelimiter ^--$
  0.000115   1234   0       0.000003    0.000000  asciidocLiteralBlock ^\.\{4,}$
  0.000112   1234   56      0.000002    0.000000  asciidocExampleBlockDelimiter ^=\{4,}$
  0.000105   1234   0       0.000003    0.000000  asciidocCommentBlock ^/\{4,}$
  0.000087   1234   0       0.000003    0.000000  asciidocSidebarDelimiter ^*\{4,}$
  0.000085   2018   0       0.000001    0.000000  asciidocBackslash  \\
  0.000080   2018   0       0.000001    0.000000  asciidocListContinuation ^+$
  0.000075   1234   0       0.000001    0.000000  asciidocAttributeEntry ^:\w
  0.000062   1234   0       0.000003    0.000000  asciidocIdMarker   ^\$Id:\s
  0.000057   56     56      0.000001    0.000001  asciidocMacroAttributes \]\|^$
  0.000057   1234   0       0.000003    0.000000  asciidocPagebreak  ^<\{3,}$
  0.000055   1234   0       0.000001    0.000000  asciidocPassthroughBlock ^+\{4,}$
  0.000048   1234   0       0.000001    0.000000  asciidocTableBlock ^|=\{3,}$
  0.000043   1234   0       0.000001    0.000000  asciidocQuoteBlockDelimiter ^_\{4,}$
  0.000036   1234   0       0.000001    0.000000  asciidocTableBlock2 ^!=\{3,}$
  0.000031   1234   0       0.000001    0.000000  asciidocRuler      ^'\{3,}$
  0.000029   168    56      0.000000    0.000000  asciidocListingBlock ^-\{4,}$
  0.000029   784    0       0.000000    0.000000  asciidocMacroAttributes \\\]
  0.000001   56     0       0.000000    0.000000  asciidocMacroAttributes \\\]

  4.858304   116182
```

</details>

**Comment by kuon** [comment]
I see this behavior with zig files. What is interesting is that it doesn't happen immediately, I can browse the file smoothly for like 10 minutes then suddenly is becomes very slow and sluggish, `hi clear CurSearch` fixes it.

I do not have a lot of experience debugging nvim, but I'll happily try any suggestion.

**Comment by zeertzjq** [comment]
After #24448 `:colorscheme blue` no longer reproduces this issue. It can instead be reproduced using `:colorscheme quiet`.

**Comment by dubrayn** [comment]
Hello, after being very annoyed by this bug for months, I seem to have found a workaround. Add this line after your colorscheme or highlight definitions (I put it at the end of my `init.lua`) :

```
vim.cmd('hi! link CurSearch Search')
```

For some reason in a lot of colorschemes (even some default ones), the `CurSearch` group is linked to the `IncSearch` one, and this seems to be the cause of the lag when scrolling with `hlsearch` enabled.

**Comment by mike-lloyd03** [comment]
@dubrayn That works for me! Problem solved. Thank you for figuring this out.

**Comment by camoz** [comment]
Can confirm that the workaround `vim.cmd('hi! link CurSearch Search')` works for me, too, but I have `CurSearch` actually set explicitly, not linked to anything.

**Comment by krystalgamer** [comment]
I was experiencing the same problem and @dubrayn comment helped me out!

Using gruvbox btw. Curious to see if this can be fixed a neovim level or is an actual problem with the schemes.

**Comment by krystalgamer** [comment]
hey @zeertzjq is there any reason why mine and mike's comment got deleted? This problem still exists

**Comment by clason** [comment]
Because they added zero new information, just noise. If you want this problem fixed, you will have to do it yourself. (Such is open source.)

**Comment by krystalgamer** [comment]
sure, but it'd be nice to keep the comments in the thread by hiding them instead of deleting.

> If you want this problem fixed, you will have to do it yourself.

appreciate the suggestion but don't have the availability for it. VIM doesn't suffer the same issue so I just went back to it in the meantime.
