### ISSUE TITLE
Quitting Neovim with `:q` hangs forever when `vim._watch.poll` is polling more than 128 files

### ISSUE THREAD

**Issue by nojnhuh** [neovim/neovim#23595]
### Problem

Quitting Neovim with `:q` hangs forever when `vim._watch.poll` is polling more than 128 files, like when LSP `workspace/didChangeWatchedFiles` is engaged on Linux.

I've bisected this behavior to have started occurring at ac1aee99bc76c0036aa0ccf7b9eda48fcf46ac11. I can take a stab at bisecting the libuv changes to see exactly what's causing this. Pasting the steps @clason left at https://github.com/neovim/neovim/pull/22833#issuecomment-1543472986 for my own convenience:
> 1. clone the libuv repo
> 2. edit the `cmake.deps/deps.txt` to point the `LIBUV_URL` to the checked out repo (this will ignore the SHA)
> 3. `git bisect bad` in the libuv repo
> 4. for every step, `rm .deps/build/src/libuv-stamp/download-libuv.cmake; make` in the neovim repo and test.

libuv changes: https://github.com/libuv/libuv/compare/62c2374a8c005ce9e42088965f8f8af2532c177b...15e81386bf9a285cada688c5faf67b3ed1319dcf?expand=1

### Steps to reproduce

init.lua:
```lua
vim._watch.poll('/tmp/nvim-watch-test', {}, function() end)
```
steps:
```
mkdir /tmp/nvim-watch-test
touch /tmp/nvim-watch-test/{1..127}
nvim --clean -u init.lua -c ':q'
# exits immediately
touch /tmp/nvim-watch-test/128
nvim --clean -u init.lua -c ':q'
# hangs forever
```

### Expected behavior

Quitting Neovim always finishes no matter how many files are watched.

### Neovim version (nvim -v)

v0.10.0-dev-312+gac1aee99b

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux, kernel 6.3.1-arch1-1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

Build from source

**Comment by nojnhuh** [comment]
I tested @aktau's theory of setting `UV_USE_IO_URING=0` and that works like a charm :tada:

**Comment by clason** [comment]
From the PR:
> /* TODO(bnoordhuis) teach libuv how to cancel file operations
>  * that go through io_uring instead of the thread pool.

and

> /* TODO(bnoordhuis) make cancellation work with io_uring */

sounds suspiciously related...

**Comment by clason** [comment]
@nojnhuh can you provide a test we can add to our test suite so we can track regressions after I revert the libUV bump?

It would also be helpful to trace into the exact `IORING_OP` that hangs so I can report the bug upstream (unless this is related to canceling file operations).

**Comment by mfussenegger** [comment]
I'm able to reproduce this too with both the steps mentioned in the issue and also with something like this:

```
local function foo()
  log("------------------------")
  local path ="/tmp/nvim-watch-test"
  for i = 1, 150 do
    local poll, err = vim.loop.new_fs_poll()
    log("poll", i, poll, err)
    assert(poll)
    poll:start(path, 2000, function(err1)
      log("cb", err1)
      if err1 == "ENOENT" then
        return
      end
      assert(not err1, err1)
    end)
  end
end
```

(The folder can even be empty, the amount of `poll:start` calls seem to trigger it)

What's interesting is that the logging affects the amount of iterations needed. With logging 128 did the trick, without it, it needs more.

Bisecting libuv pointed to `d2c31f429b87b476a7f1344d145dad4752a406d4` as first bad commit.

What's also interesting is that it appears to only happen if you quit neovim fast enough.

E.g. running the above function, then waiting for a while and then quitting Neovim doesn't trigger the issue. That unfortunately also makes it hard to step through in a debugger to see where it stops.

I once landed at https://github.com/libuv/libuv/blob/15e81386bf9a285cada688c5faf67b3ed1319dcf/src/unix/linux.c#L1162, but that may have been a fluke.

**Comment by nojnhuh** [comment]
> @nojnhuh can you provide a test we can add to our test suite so we can track regressions after I revert the libUV bump?

@clason Yep, I'm able to reproduce this in a test. The test runner reports that the test passes though but the underlying `nvim` fails to quit and hangs like I was seeing interactively. Maybe once we get a clearer idea of what's going on we can make the test fail more gracefully.

The test so far, for reference:

```lua
    it('can be used with a large number of files', function()
      local root_dir = helpers.tmpname()
      os.remove(root_dir)
      mkdir(root_dir)

      local result = exec_lua(
        [[
        local root_dir = ...

        local num_handles = 129 -- 128 will pass

        for i = 1, num_handles do
          vim._watch.poll(root_dir, nil, function() end)
        end
      ]],
        root_dir
      )
    end)
```

> It would also be helpful to trace into the exact `IORING_OP` that hangs so I can report the bug upstream (unless this is related to canceling file operations). Just build against a local libuv clone where you do the following:
> 
> > For a quick binary search, you can `add return 0;` at the top of the `uv__iou_fs_*()` functions `src/unix/linux.c`, that makes them fall back to the thread pool.

I'll give this a shot but might need a bit more hand-holding through it. I'll follow up here if I have more questions.

> Also, are you sure it's hanging forever and not just working through the list of requests that are no longer canceled? (You can disable the `watch.cancel()` function to try to trigger the behavior without io_uring.)

The most I ever waited was a few minutes, but given the difference between that and relatively instantaneous quit is one more call to `poll:start`, that makes me reasonably confident that it stops making any progress at some point.

**Comment by clason** [comment]
@nojnhuh @mfussenegger could you try building with https://github.com/libuv/libuv/pull/3991 and see if that fixes the hang?

**Comment by nojnhuh** [comment]
That appears to fix it for me :+1:

**Comment by mfussenegger** [comment]
Fixes it for me as well
