### ISSUE TITLE
Switch to luajit2 to support more architectures

### ISSUE THREAD

**Issue by julianruess** [neovim/neovim#23603]
### Problem

Can we use luajit2 (https://github.com/openresty/luajit2) instead of luajit? It is supported on more architectures like e.g. s390x. 

### Steps to reproduce

Build neovim on s390x.
Doesn't work because luajit is not supported.

### Expected behavior

Should build

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux on s390x

### Terminal name/version

gnome terminal

### $TERM environment variable

xterm256-color

### Installation

from source

**Comment by clason** [comment]
You are welcome to switch out LuaJIT2 for LuaJIT in your builds; this should be a drop-in replacement. (Homebrew did this for a while, and I tracked it in https://github.com/neovim/neovim/pull/13741).

But we will not switch to a fork, as the original project is better maintained, meaning security fixes are applied faster.

**Comment by julianruess** [comment]
Since neovim is shipped by various Linux distros for this platform, is it possible to edit the CMakeLists.txt to use luajit2 only when processor type is s390x?

**Comment by dundargoc** [comment]
I don't think we can officially take on a third lua alternative (lua, luajit and luajit2) from a maintenance standpoint. Lua is supposed to be the fallback in cases where luajit isn't available.

That said, there is nothing preventing you from building with luajit2 right now. In `cmake.deps/deps.txt`, replace `LUAJIT_URL` and `LUAJIT_SHA256` with appropriate values to build with luajit2 instead:

```
LUAJIT_URL https://github.com/openresty/luajit2/archive/v2.1-20230410.tar.gz
LUAJIT_SHA256 77bbcbb24c3c78f51560017288f3118d995fe71240aa379f5818ff6b166712ff
```

This seems to work fine when I did a quick test. Of course, we can't make any guarantees that this'll continue to work in the future, and any issues with this setup will be instaclosed with "we don't support that, so don't do that". But if this is a risk you're fine with then that is also a possibility.
