### ISSUE TITLE
[bug] [builtin-terminal] Pressing % to match braces while in NORMAL causes infinite loop.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2361]
My command line looks something like this:

```
josephpea@I > ~/src/climate+paul.chang+climate-portal/meteor-react/app > master
❯                                                                    [18:40:02]
```

When I exit terminal into NORMAL mode with `<c-\><c-n>`, then I put the cursor in the empty space between the `❯` and `[18:40:02]`, then press `%`, neovim bvegins to ring the terminal bell repeatedly, forever, and becomes unresponsive. I'm in iTerm2, and the bell rings approximately every 2 seconds.

**Comment by Grimy** [comment]
I can’t reproduce this. Could you please give more details, and ideally a reproduction with `nvim -u NONE`?

**Comment by trusktr** [comment]
I can't reproduce this any more, even with or without `-u NONE`. Seems like the problem went away. Closing for now, unless it re-appears.
