### ISSUE TITLE
Treesitter tree change event when deleting buffer

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#23629]
### Problem

In the current development build deleting a buffer (`:bdelete` or `:bwipeout`) triggers an `on_changedtree` event. In version 0.9 the event is not triggered. I don't know if this is intentional or a bug, but it causes a problem in one of my plugins (https://github.com/HiPhish/nvim-ts-rainbow2/issues/40).

### Steps to reproduce

I have a little script which performs a minimal setup.

```sh
nvim -u NONE -c 'luafile rc.lua`
```

The script is as follows:

```lua
local ts = vim.treesitter

vim.cmd 'edit derp.lua'

local parser = ts.get_parser(0, 'lua')
parser:register_cbs {
	on_changedtree = function()
		print('Changes in buffer')
	end
}
```

It opens a file, gets the parser and sets up the callback. The file in question is just a minimal Lua file:

```lua
print 'derp'
```

### Expected behavior

No message gets printed.

### Neovim version (nvim -v)

v0.10.0-dev-332+gedfa8d6f2

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Void Linux

### Terminal name/version

Alacritty 0.12.0

### $TERM environment variable

alacritty

### Installation

Official AppImage

**Comment by HiPhish** [comment]
I don't quite follow. As far as I understand there are two "trees": the language tree (parser with child parsers) and the document tree (the text buffer parsed to a tree of text nodes) which is produced by the language tree. The `on_changedtree` callback is called when the document tree changes. But if you delete the buffer how can there be a document tree? Whenwould `on_addtree` be called?

**Comment by clason** [comment]
Deleting the buffer deletes the whole tree, doesn't it?

And the trees are added when your edit adds an injected block (like a markdown codeblock).

**Comment by HiPhish** [comment]
> Deleting the buffer deletes the whole tree, doesn't it?

Deleting the buffer deletes the document tree, which in turn deletes the language tree, right? Or can the language tree survive the destruction of its document tree? Anyway, we already have `on_detach`, so what is the purpose of being notified after the buffer has already been deleted? I could understand if the event was just before the buffer gets deleted (unloaded?) so we can perform some last-minute cleanup on the buffer.

> And the trees are added when your edit adds an injected block (like a markdown codeblock).

That's an addition to the language tree that is added, right? In that case I think it makes sense to fire two events: `on_changetree` for the added nodes to the document tree (which would happen even if there was no new language injected), and `on_addtree` for the added language tree.

I find the overloaded meaning of "tree" really confusing. Are what I call the language tree and the document tree distinct or are they two sides of the same coin?

**Comment by HiPhish** [comment]
I think I understand now. My misconception was thinking that each parser `LanugageTree` can only have one `TSTree` associated. The method `LanguageTree:set_included_regions()` is not documented. Let me see if I understand the use-case correctly: Suppose I have a Lua buffer with embedded Vim script:

```lua
print 'Hello from Lua'

vim.cmd 'echo "Hello from Vim"'

print 'Goodbye from Lua'

vim.cmd 'echo "Goodbye from Vim"'
```

- there are two `LanguageTree` objects, one for Lua and one for Vim script
- the Vim `LanguageTree` is a child of the Lua `LanguageTree`
- the Vim `LanguageTree` has an associated `TSTree` for each of the two regions
- the Lua `LanguageTree` has only one associated `TSTree`

Does this mean the Lua `TSTree` has "holes" in it or does the Lua `LanguageTree` know from its child which region should be handled by the child?

Anyway, if a `LanugageTree` can have multiple associated `TSTree` instances it does make sense to emit an `on_changedtree` event. But I still think that event should be emitted while the buffer is still valid. Or would you say that this does not make sense?

**Comment by clason** [comment]
No, that's not quite correct. I think `:h lua-treesitter-language-tree` is quite explicit; if something specific there is unclear, please let me know.

The point is that the `LanguageTree` is a "tree of trees": one document has a single(!) `LanguageTree`, which contains the language-specific(!) `TSTree`s for each region (the root tree for the whole document, and every injected tree. By default, this is one tree _per region_ -- so two `TSTree`s for `vim` in your example -- but this can be changed by directives).

**Comment by HiPhish** [comment]
I think I'm starting to understand. When I inspect the `LanguageTree` of the document it looks like this (I have removed the irrelevant fields):

```
{
  _children = {
    vim = {
      _children = {},
      _has_regions = true,
      _trees = { <userdata 3>, <userdata 4> },
      _lang = "vim",
    },
  },
  _lang = "lua",
  _trees = { <userdata 7> },
}
```

This raises a question: are the three `TSTree` objects related? I would have guessed that the two Vim trees are sub-trees of the larger tree. So let's try to find out.

```lua
p = vim.treesitter.get_parser()
vim.treesitter.is_ancestor(p._trees[1]:root(), p._children.vim._trees[1]:root())
```

The result is actually `false`, the root of the local Vim tree is not a descendant of the root of the global document tree. Yet when I execute `:InspectTree` Neovim knows how to stitch together these three trees into one large tree for me to look at. Where does this information come from?

One more question: in `:h lua-treesitter-languagetree` it says that I must call `parse()` after an edit to get the tree with the changes. It also says that the tree is immutable. Yet when I edit the buffer and then evaluate `p._children.vim._trees[1]:root():range()` I get a different result than before the edit without having to parse first. If I understand correctly this means that `p` did get updated automatically after the edit, and the old `TSTree` object was replaced with a new one (i.e. `p` lost the reference to the old tree instead of mutating it). The only reason I would have to call `parse()` is if I am holding on to such an old reference myself. Correct?

**Comment by lewis6991** [comment]
>  are the three TSTree objects related

No. They are completely independent objects. It is the LanguageTree that contains them into a single object.

> Yet when I execute :InspectTree Neovim knows how to stitch together these three trees into one large tree for me to look at. Where does this information come from?

`:InspectTree` is just a pretty printer for LanguageTree.

> One more question: in :h lua-treesitter-languagetree it says that I must call parse() after an edit to get the tree with the changes. It also says that the tree is immutable. Yet when I edit the buffer and then evaluate p._children.vim._trees[1]:root():range() I get a different result than before the edit without having to parse first.

The highlighter is calling `parse()` in `on_bytes()`, however it is not guaranteed this will be called before other plugins so it's best to call it yourself.
