### ISSUE TITLE
Mouse scroll broken on most plugins

### ISSUE THREAD

**Issue by Zeioth** [neovim/neovim#23630]
### Problem

Using mouse scroll up/down result in window panning instead of the intended plugin behavior.

Tested on:

* Telescope: Scrolling with the mouse causes the buffer in background to scroll instead of telescope.
* Rnvimr: Scrolling with the mouse causes rnvimr to lose focus and do nothing
* ranger.vim: Scrolling with the mouse causes ranger to lose focus and do nothing.

### Steps to reproduce

* Telescope: Run :Telescope and try to scroll up/down.
* Rnvimr: Run :RnvimrToggle and try to scroll up/down.
* ranger.vim: Run :Ranger and try to scroll up/down.

### Expected behavior

* Telescope: Scroll through the files.
* Rnvimr: Scrolling through the files (as in normal ranger).
* ranger.vim: Scrolling through the files (as in normal ranger).

### Neovim version (nvim -v)

v0.9.0

### Vim (not Nvim) behaves the same?

no, VIM 9.0

### Operating system/version

Arch Linux

### Terminal name/version

foot version: 1.14.0

### $TERM environment variable

xterm-256color

### Installation

Astrovim, but also tested with bare neovim from arch community repos

**Comment by Zeioth** [comment]
At least it seems the telescope issue has been partially fixed (if you scroll while telescope is open, the buffer in background doesn't scroll anymore). But telescope still has no support for mouse scroll.

**Comment by ii14** [comment]
Issues with plugins should be reported on their bug trackers.

**Comment by ii14** [comment]
I should probably add that `<ScrollWheelUp>` and `<ScrollWheelDown>` can be remapped if you want mouse wheel to do something else.

**Comment by Zeioth** [comment]
Thank you so much for your answer
