### ISSUE TITLE
after quit a floating window in insert mode, nvim enters insert mode too

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#23634]
### Problem

hi folks, at the first i thought it's a problem caused by prompt buffer only,  but in my later tests, this behavior exists in many `buftype`s.

> for example accessing an option enters aucmd win and runs that code
> whether you access an option or not should not influence the active mode

i got answered by ii14 in the matrix room, but i still think it's another different problem.

### Steps to reproduce

* `nvim --clean +'so nofile.lua` # normal.lua is worth another run
* we are now in a floating window and insert mode
* `<cr>`
* we are in insert mode

nofile.lua
```
local api = vim.api

local bufnr = api.nvim_create_buf(false, true)

local bo = vim.bo[bufnr]
bo.buftype = "nofile"
bo.bufhidden = "wipe"

local winid = api.nvim_open_win(bufnr, true, { relative = "cursor", style = "minimal", row = 1, col = 0, width = 20, height = 1 })

vim.keymap.set("i", "<cr>", function() api.nvim_win_close(winid, false) end, { buffer = bufnr })

api.nvim_put({ "foo" }, "c", true, true)
assert(api.nvim_buf_line_count(bufnr) == 1)

vim.cmd.startinsert()
-- assert(api.nvim_get_mode().mode == "i") -- btw, this will fail! though wrapping with vim.schedule can rescue it.
```

<details>
<summary>normal.lua</summary>
```
local api = vim.api

local bufnr = api.nvim_create_buf(false, true)

local bo = vim.bo[bufnr]
bo.buftype = ""
bo.bufhidden = "wipe"

local winid = api.nvim_open_win(bufnr, true, { relative = "cursor", style = "minimal", row = 1, col = 0, width = 20, height = 1 })

vim.keymap.set("i", "<cr>", function() api.nvim_win_close(winid, true) end, { buffer = bufnr })

api.nvim_put({ "foo" }, "c", true, true)
assert(api.nvim_buf_line_count(bufnr) == 1)

vim.cmd.startinsert()
```
</details>

### Expected behavior

going back from a floating window, nvim will keep in the same mode when the cursor leaves.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

archlinux's community repo

**Comment by Shougo** [comment]
Please see this.

https://github.com/nvim-telescope/telescope.nvim/issues/2501

**Comment by haolian9** [comment]
whoa, never thought it in this way! 
so the mode is a global thing, it makes sense to me now, thank you! and sorry for the noise.

**Comment by haolian9** [comment]
sorry to bother the community again.
i tried the same procedure on 0.8, it behaves different to 0.9, i dont find any mention about this, is that intended?
