### ISSUE TITLE
`.editorconfig`, invalid value for options `charset` and `end_of_line` 

### ISSUE THREAD

**Issue by aarondill** [neovim/neovim#23635]
### Problem

Opening a file with a editorconfig with a `charset` or `end_of_line` set results in the following errors:
```
editorconfig: invalid value for option charset: "utf-8". charset must be one of "utf-8", "utf-8-bom", "latin1", "utf-16be", or "utf-16le"
editorconfig: invalid value for option end_of_line: "lf". end_of_line must be one of "lf", "crlf", or "cr"
```
Additionally, it seems that the configuration is not respected.

### Steps to reproduce

```console
> printf 'root = true
[*]
charset = "utf-8" # or any valid value
end_of_line = "lf" # or any valid value
' > .editorconfig
> # extra clean 🤷‍♂️
> env -i TERM=ansi-256color nvim --clean .editorconfig
editorconfig: invalid value for option charset: "utf-8". charset must be one of "utf-8", "utf-8-bom", "latin1", "utf-16be", or "utf-16le"
editorconfig: invalid value for option end_of_line: "lf". end_of_line must be one of "lf", "crlf", or "cr"
```

### Expected behavior

No errors thrown and configuration respected

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Vim (not Nvim) behaves the same?

No, vim doesn't respect editorconfig natively

### Operating system/version

Ubuntu 22.04.2 LTS

### Terminal name/version

wezterm 20230408-112425-69ae8472

### $TERM environment variable

wezterm

### Installation

APT, using nightly ppa (https://ppa.launchpadcontent.net/neovim-ppa/unstable/ubuntu/)

**Comment by zeertzjq** [comment]
I think valid values should not contain double quotes, and the error message is a bit confusing.

**Comment by aarondill** [comment]
Indeed you are correct, the value should not be quoted. I copied this `.editorconfig` from another project, so I need to fix it there. The error message *is* slightly confusing, but that's mostly my own fault, for not understanding the editorconfig spec well enough

**Comment by aarondill** [comment]
Thank you for the quick reply. I've closed this because Neovim's behavior is actually correct here.
