### ISSUE TITLE
`:Man` ignores `fish` shell overrides.

### ISSUE THREAD

**Issue by AlexSWall** [neovim/neovim#23641]
### Problem

Looking at the `man` page for `complete` in `fish` shell, I receive the `fish`-specific man page for the entry.

However, if I'm in `neovim` with `:!echo $SHELL` giving `fish` (and other commands requiring `fish` shell syntax), `:Man complete` gives the `bash` built-in page for `complete instead of the expected `fish`-specific man page for it.

Notably, if I run `man complete` from my terminal with `nvim +Man!` as my `$MANPAGER`, I receive the `fish`-specific `complete` `man` page, and if I navigate away from it and re-run the command `:Man complete`, it opens back up that buffer instead of opening the `bash` built-ins man page.

I tried to find in the code where this was happening but couldn't find the location of the implementation of `:Man` or similar, so pointers on where to find that would also be helpful.

### Steps to reproduce

fish
nvim --clean
:Man complete

### Expected behavior

Should show the `man` page for `fish` shell's `complete` function. Instead it shows `bash`'s built-ins `man` page.

### Neovim version (nvim -v)

v0.10.0 commit g55d346fc2

### Vim (not Nvim) behaves the same?

N/A (Vim does not have `:Man`)

### Operating system/version

macOS 13.3.1

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

Homebrew

**Comment by zeertzjq** [comment]
`fish` adds paths to `$MANPATH`, therefore it's not possible to replicate this in Nvim.
```fish
# Defined in /usr/share/fish/functions/man.fish @ line 6
function man --description 'Format and display the on-line manual pages'
    # Work around the "builtin" manpage that everything symlinks to,
    # by prepending our fish datadir to man. This also ensures that man gives fish's
    # man pages priority, without having to put fish's bin directories first in $PATH.

    # Preserve the existing MANPATH, and default to the system path (the empty string).
    set -l manpath
    if set -q MANPATH
        set manpath $MANPATH
    else if set -l p (command man -p 2>/dev/null)
        # NetBSD's man uses "-p" to print the path.
        # FreeBSD's man also has a "-p" option, but that requires an argument.
        # Other mans (men?) don't seem to have it.
        #
        # Unfortunately NetBSD prints things like "/usr/share/man/man1",
        # while not allowing them as $MANPATH components.
        # What it needs is just "/usr/share/man".
        #
        # So we strip the last component.
        # This leaves a few wrong directories, but that should be harmless.
        set manpath (string replace -r '[^/]+$' '' $p)
    else
        set manpath ''
    end
    # Notice the shadowing local exported copy of the variable.
    set -lx MANPATH $manpath

    # Prepend fish's man directory if available.
    set -l fish_manpath $__fish_data_dir/man
    if test -d $fish_manpath
        set MANPATH $fish_manpath $MANPATH
    end

    if test (count $argv) -eq 1
        # Some of these don't have their own page,
        # and adding one would be awkward given that the filename
        # isn't guaranteed to be allowed.
        # So we override them with the good name.
        switch $argv
            case :
                set argv true
            case '['
                set argv test
            case .
                set argv source
        end
    end

    command man $argv
end
```

**Comment by AlexSWall** [comment]
Makes sense. Thanks for the speedy response.
