### ISSUE TITLE
incorrect expansion of $HOME

### ISSUE THREAD

**Issue by ljden** [neovim/neovim#23649]
### Problem

on my system $HOME is set to `/home/$username@corperate_network.com/` and is an active directory

running `:echo expand("$HOME")` in nvim results in `/home/username`

vim does not do this

### Steps to reproduce

home directory in format user@network
sudo snap install nvim
nvim
:echo expand("$HOME")`

### Expected behavior

```vim
:echo expand("$HOME")
```
```
/home/username@corperate_network.com
```

### Neovim version (nvim -v)

v0.9.0

### Vim (not Nvim) behaves the same?

no, 8.2.4919

### Operating system/version

Ubuntu 22.04

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

snap

**Comment by zeertzjq** [comment]
Is the user name `$username` or `username`?

**Comment by zeertzjq** [comment]
What does executing `HOME=/home/username@coporate_network.com nvim --clean --headless -c 'echo expand("$HOME") | q'` in shell print? It prints `/home/username@coporate_network.com` for me.

**Comment by ljden** [comment]
> Is the user name `$username` or `username`?
```bash
$ echo $USER
username
```
Eg 
```bash
$ echo $HOME
/home/ljden@corporate.com
```

> What does executing `HOME=/home/username@coporate_network.com nvim --clean --headless -c 'echo expand("$HOME") | q'` in shell print? It prints `/home/username@coporate_network.com` for me.

I will test this at work tomorrow

**Comment by ljden** [comment]
@zeertzjq very odd, it completely ignores it. Does nvim possibly source variables from somewhere else? 
This issue is not present in the apt version of neovim (v0.6.1-3)
```
$ echo $HOME
/home/ljden@corporate.com
$ HOME=/home/username@coporate.com nvim --clean --headless -c 'echo expand("$HOME") | q'
/home/ljden
$ nvim --version
NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/nvim/parts/nvim/build/.deps/usr/include/luajit-2.1 -I/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include -I/build/nvim/parts/nvim/build/build/cmake.config -I/build/nvim/parts/nvim/build/src -I/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by zeertzjq** [comment]
Hmm, that looks strange. What do these two commands print?
```sh
echo 'print(vim.loop.os_getenv("HOME"))' | HOME=/home/username@coporate.com nvim -ll -
```
```sh
echo 'print(vim.loop.os_homedir())' | HOME=/home/username@coporate.com nvim -ll -
```

**Comment by zeertzjq** [comment]
And this one:
```sh
HOME=/home/username@coporate.com nvim --clean --headless -c 'echo $HOME | q'
```

**Comment by ljden** [comment]
```
$ echo 'print(vim.loop.os_getenv("HOME"))' | HOME=/home/username@coporate.com nvim -ll -
/home/ljden
$ echo 'print(vim.loop.os_homedir())' | HOME=/home/username@coporate.com nvim -ll -
/home/ljden
$ HOME=/home/username@coporate.com nvim --clean --headless -c 'echo $HOME | q'
/home/ljden
```
🤷🏼

**Comment by zeertzjq** [comment]
Hmm, can you try appimages from the [Releases](https://github.com/neovim/neovim/releases) and check if they also behave like this?

**Comment by zeertzjq** [comment]
I just noticed that you installed Nvim using snap. Maybe snap overrides the `$HOME` environment variable?

**Comment by ljden** [comment]
Works from the 0.9.0 app image as expected. Yeah that's what I was starting to suspect as well. I'll do a quick search to see if that's the case

**Comment by ljden** [comment]
Confirmed it is an issue with snap setting the environment variables. I'm not sure where it is getting it from but it is not an issue with neovim
```
$ snap run --shell nvim
$ echo $HOME
/home/ljden
```

**Comment by ljden** [comment]
My current work around is to symlink `/home/ljden` to `/home/ljden@corperate.com` or to explicitly set the `XDG_*_HOME` variables
