### ISSUE TITLE
`vim.tbl_deep_extend()` is inconsistent with regards to nesting level

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#23654]
### Problem

`vim.tbl_deep_extend()` is inconsistent in how it treats arrays/lists and general map-like Lua tables: it at least depends on nesting level.

### Steps to reproduce

1. `nvim --clean`
2. `:=vim.tbl_deep_extend('force', { [1] = 'a' }, { b = 'a' })`. It now results into `{ [1] = 'a', b = 'a' }`.
3. `:=vim.tbl_deep_extend('force', { sub = { [1] = 'a' } }, { sub = { b = 'a' } })`. It now results into `{ sub = { b = 'a' } }`.

General idea of not mixing arrays/lists with general maps is in itself questionable, but [seems to be by design](https://github.com/neovim/neovim/pull/15094#discussion_r671663938) (although I don't fully understand its reasoning).

### Expected behavior

Table extend rules are the same for all nesting levels.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-319+g5825d2f6c

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.3.1-arch2-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by lewis6991** [comment]
> General idea of not mixing arrays/lists with general maps is in itself questionable, but https://github.com/neovim/neovim/pull/15094#discussion_r671663938 (although I don't fully understand its reasoning).

Lua has neither, it just has tables. Think of `{[1] = 'a', b = 'c'}` as just a structure with two indexes; `1` and `'b'`. The fact they are different types doesn't particularly matter.

**Comment by justinmk** [comment]
vim.merge https://github.com/neovim/neovim/pull/15124 looks good, we should revisit that.

**Comment by echasnovski** [comment]
> > General idea of not mixing arrays/lists with general maps is in itself questionable, but [#15094 (comment)](https://github.com/neovim/neovim/pull/15094#discussion_r671663938) (although I don't fully understand its reasoning).
> 
> Lua has neither, it just has tables. Think of `{[1] = 'a', b = 'c'}` as just a structure with two indexes; `1` and `'b'`. The fact they are different types doesn't particularly matter.

I do understand that, thanks for explaining. However, it is not me who needs this explanation. The idea of "they are different types doesn't particularly matter" is exactly what doesn't hold with the example in the original comment: the fact that one of the indexes is `[1]` *does* matter.

**Comment by lewis6991** [comment]
Fair enough. I was only replying to the specific comment about mixing lists/arrays with maps.

I can see `:=vim.tbl_deep_extend('force', { sub = { a = 'a' } }, { sub = { b = 'a' } })` does the correct thing, so the integer indexes aren't being treated correctly.

**Comment by echasnovski** [comment]
> ... so the integer indexes aren't being treated correctly.

Yes, it seems to be because [whether a sub-table is an array matters](https://github.com/neovim/neovim/blob/fdd3a9cdf7167ca8fc84ec9a7e583f6410a27188/runtime/lua/vim/shared.lua#L359) and [I *think* it is by initial design](https://github.com/neovim/neovim/pull/15094#discussion_r671789378), but I don't really understand the reasoning.

**Comment by lewis6991** [comment]
From what I can tell, there was no reasoning. See #11969 where the predicate was first added under a different name.

Raised #30251 to remove this predicate.

**Comment by folke** [comment]
My `vim.merge` PR didn't have this issue and worked consistently. That's what I've been using in `lazy.nvim`.

The new `tbl_deep_extend` implementation makes no sense. See my comments on #30251

**Comment by clason** [comment]
@folke If you knew all this time why the function worked like it did, it would have been helpful had you commented here sometime in the year and a half this issue was open, and before it was resolved (quite reasonably given the information at hand).

**Comment by justinmk** [comment]
He wasn't tagged

**Comment by clason** [comment]
But he's a member of the org; one would hope that this would mean following the project to some extent.
