### ISSUE TITLE
Built-in completion affects nearby extmarks

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#23653]
### Problem

Using built-in completion affects nearby extmarks when it probably shouldn't.

The probable suspected culprit for this is that built-in completion initially removes completed region before suggesting results and later restores it.

This affects all extmark-related highlighting, notably LSP semantic tokens (which results in flickering due to debounced updates).

Might be related: #13816.

### Steps to reproduce

- `nvim --clean`.
- Enter text `aaaa`.
- `:lua ns_id = vim.api.nvim_create_namespace('extmark')`
- `:lua mark_id = vim.api.nvim_buf_set_extmark(0, ns_id, 0, 0, { end_col = 2, hl_group = 'Search' })`. This should add extmark at start of the word and highlight first two characters.
- Start Insert mode with `A` and press `<C-n>` (initiates one of built-in completions). Highlighting is removed, but extmark is still there, just squashed to left (`:=vim.api.nvim_buf_get_extmark_by_id(0, ns_id, mark_id, { details = true })` shows that `end_col` is now 0).

### Expected behavior

Initialization of built-in which doesn't visibly modify text should not affect extmarks.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-319+g5825d2f6c

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.3.1-arch2-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by luukvbaal** [comment]
I think we can undo the extmark changes. This patch works for the repro:
```diff
diff --git a/src/nvim/insexpand.c b/src/nvim/insexpand.c
index d6860fff3..1348a6515 100644
--- a/src/nvim/insexpand.c
+++ b/src/nvim/insexpand.c
@@ -25,6 +25,7 @@
 #include "nvim/eval/typval.h"
 #include "nvim/eval/typval_defs.h"
 #include "nvim/eval/userfunc.h"
+#include "nvim/extmark.h"
 #include "nvim/ex_cmds_defs.h"
 #include "nvim/ex_docmd.h"
 #include "nvim/ex_eval.h"
@@ -3447,6 +3448,15 @@ void ins_compl_insert(bool in_compl_func)
   ins_bytes(compl_shown_match->cp_str + get_compl_len());
   compl_used_match = !match_at_original_text(compl_shown_match);

+  if (!compl_used_match) {
+    // Original text is restored, also restore extmarks.
+    ExtmarkUndoObject undo_info;
+    for (long i = (int)kv_size(curbuf->b_u_newhead->uh_extmark) - 1; i > -1; i--) {
+      undo_info = kv_A(curbuf->b_u_newhead->uh_extmark, i);
+      extmark_apply_undo(undo_info, true);
+    }
+  }
+
   dict_T *dict = ins_compl_dict_alloc(compl_shown_match);
   set_vim_var_dict(VV_COMPLETED_ITEM, dict);
   if (!in_compl_func) {
```

I'm not sure if the undo info will always be in `b_u_newhead` here.
