### ISSUE TITLE
Expose a nicer lua API for creating user commands

### ISSUE THREAD

**Issue by chrismit3s** [neovim/neovim#23665]
### Problem

It be nice if there were a nicer API for [`vim.api.nvim_create_user_command`](https://neovim.io/doc/user/api.html#nvim_create_user_command()), similar to `vim.keymap` or `vim.opt`. I'd be willing to write this, if it will be merged.

### Expected behavior

The namespace could be something like `vim.usercmd`, but one needs to ensure it's not confused with `vim.cmd`.

It could be structured fairly similar to `vim.keymap`:
`vim.usercmd.create(name, expr, opts)`
`vim.usercmd.delete(name)`

**Comment by clason** [comment]
What would be the intended benefit? Both vim.keymap and vim.opt were intended to give significant (!) benefits (Lua functions and table options, respectively).

Simply adding a thin wrapper that "looks more like Lua" is not very appealing and would likely not be very well received.
