### ISSUE TITLE
Choco Install on Windows Fails with Checksum Error on download

### ISSUE THREAD

**Issue by NickHirras** [neovim/neovim#23678]
### Problem

![image](https://github.com/neovim/neovim/assets/3911628/0b9a09e7-a3c6-401a-aa3d-594c686c3071)

### Steps to reproduce

choco install neovim

### Expected behavior

Installs package.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Microsoft Windows 10 Pro

### Terminal name/version

Command Prompt

### $TERM environment variable

n/a

### Installation

choco install neovim

**Comment by clason** [comment]
Please report this to the Choco maintainers; we are not involved in downstream packaging.
