### ISSUE TITLE
[LSP]: csharp-ls vim.lsp.buf.definition() index out of range

### ISSUE THREAD

**Issue by ztx-lyghters** [neovim/neovim#23676]
### Problem

Hello. I'm new to vim plugins, as well as I am new to C# language. I'm trying to set up a C# environment in NeoVim and I'm having troubles with the `csharp-ls` engine. First of all, it's difficult for me to understand to which repo I should really write this issue, so do excuse me if I chose wrong and please let me know where should I post this instead.

I have filed an issue on lsp-zero repository before and so far it seems like it's a problem with NeoVim's built-in fuction.
But, of course, it might be the problem with my configuration.

### Steps to reproduce
I created a new "webapi" preset via `dotnet new webapi` and opened `Program.cs` file in NeoVim.
Whenever I hover over almost anything, like, for example, `WebApplication.CreateBuilder(args)`, no matter which part of it exactly, and when I press `gd` in normal mode (which is mapped to `vim.lsp.buf.definition()`) I get this error message:

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.
lua:1828: index out of range
stack traceback:
        [C]: in function '_str_byteindex_enc'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1828: in function 'locations_to_items'
        /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:398: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1394: in function 'cb'
        vim/_editor.lua:263: in function <vim/_editor.lua:262>
```

In some other C# projects it's not guaranteed to get this error, sometimes it works, sometimes it doesn't, but in the new webapi preset pressing `gd` on virtually any method that is within the stock `Program.cs` file results in this.

I have no idea how can I even start debugging this. I'm going to link to my current nvim config files, because I might have done something stupid:
https://git.sr.ht/~ztx/nix-cfg/tree/bedrock-pc/item/files/home/.config/nvim

I did try to uninstall all other plugins with the exception of `lsp-config`, `mason` and `cmp` related stuff, as well as I have tried to reinstall everything several times, I've tried minimal configs, such as this one:
https://paste.sh/4PPgollR#iNvYdoqsTyvfrJa0VGFxgMU4
but the result is always the same.

Any suggestions on what's going on? Any additional info I should provide?
Here's the NVim's `:version` info - https://paste.sh/Z1tT5b5f#h0K3_aRL7s8JSohzJaSjNfLp
The LSP log is empty as of now.

### Neovim version (nvim -v)

0.9.0

### Language server name/version

csharp-ls 0.8.0

### Operating system/version

Void Linux

**Comment by justinmk** [comment]
"index out of range" can happen as a result of a config issue. https://github.com/neovim/neovim/issues/19237#issuecomment-1559985000

**Comment by Spycemyster** [comment]
I'm on LunarVim and this is happening to me

**Comment by sergeypdev** [comment]
@justinmk I have the same issue with csharp_ls and denols. The only common thing between them is the use of virtual file system for library files. This error happens only when trying to open these "virtual" files, jumping to my own code in a real file system works perfectly fine.

Can you please elaborate how to fix this issue? The comment you linked doesn't mention anything specific.

**Comment by eramireziceibm** [comment]
some problem
