### ISSUE TITLE
gk to step to last line of closed fold no longer works

### ISSUE THREAD

**Issue by tipa40** [neovim/neovim#23674]
### Problem

When I create a collapsed fold and then step up into it from below using `gk` the cursor position should be at the last line of the text belonging to that fold.

### Steps to reproduce

1. Place cursor in text with at least 3 following lines.
2. Use normal mode.
3. `zf2j` to create collapsed fold.
4. `j` or arrow to go down to first line following fold.
5. `gk` to step up to the line with the collapsed fold.
6. `za` to toggle it opened/expanded.

### Expected behavior

I expect the cursor at this point to be on the _last_ line of the lines that belong to the fold, which was the case in earlier versions of nvim up to 0.9 something.

Now it is instead placed on the first line(, which, as I'd like it, should only be the case when using `k` or arrow up keys)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-350+gc9f47fca8

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

Ubuntu 22.04.2 LTS

### Terminal name/version

Alacritty 0.12.0-dev (e9ee8dcd)

### $TERM environment variable

xterm-256color

### Installation

Build from repo

**Comment by zeertzjq** [comment]
This behavior is correct. The previous behavior is a bug.

**Comment by tipa40** [comment]
Would you like to help me understand why? The only insight/conclusion I can then see at the moment is that a removed feature in nvim, that exists in regular vim, is called a bugfix.

My usecase is that I am using vimwiki(I know there are other alternatives as welll but I like i) currently where in my configuration my chapters are folded for me. I have mapped my arrow up/down to gk/gj so I easily can navigate to chapter start/end and expand at will. I was sad to discover that it stopped working. Do you know of any better solution to navigate to the last line of a closed fold than expanding it first and then using `]z`? Maybe I will need to make some mapping then because [ involves 2 strokes on my keyboard.

**Comment by luukvbaal** [comment]
gj/gk are supposed to behave the same as j/k on a line that doesn't wrap, which a folded line doesn't. The old behavior was a bug present in both vom and nvim, it was ported here: #22320.

**Comment by tipa40** [comment]
Ok, super, thank you! :) I'll make some mappings instead. :+1:
