### ISSUE TITLE
`nvim_win_get_height` ignores winbar

### ISSUE THREAD

**Issue by T-727** [neovim/neovim#23683]
### Problem

The result of `nvim_win_get_height` does not change according to winbar visiblity

### Steps to reproduce

- `nvim --clean`

- `:=vim.api.nvim_win_get_height(0)`
observe result

- `:set showtabline=2 | =vim.api.nvim_win_get_height(0)`
result changed

- `:set winbar=E | =vim.api.nvim_win_get_height(0)`
result did not change

### Expected behavior

The result of `nvim_win_get_height` should change depending on winbar visiblity

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Windows11 Home

### Terminal name/version

wezterm 20230408-112425-69ae8472

### $TERM environment variable

xterm-256color

### Installation

scoop

**Comment by zeertzjq** [comment]
Use `winheight()` or `getwininfo()`. `nvim_win_get_height` is an API function, so it's behavior must not change.
