### ISSUE TITLE
vim.version.cmp() errors on comparing two vim.version() values

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#23687]
### Problem

Currently `vim.version.cmp(vim.version(), vim.version())` errors because `vim.version.cmp_prerel()` can't compare `prerelease` fields of a `vim.version()` table, because they are boolean values and the comparison is looking for `'([^0-9]*)(%d*)'` in the `prerelease` field.

### Steps to reproduce

`:lua vim.version.cmp(vim.version(), vim.version())` when running a pre-release version of Nvim.

### Expected behavior

Not sure, because there's spec compliancy to think about. Do we just check if it's two boolean values before we get to the `gmatch(...)` part?

### Neovim version (nvim -v)

0.10.0 g9c61f0c53

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 12.6.3

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

build from repo

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/issues/23863

OK to make breaking changes to `vim.version()`.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/23539 added a related workaround.

But probably `vim.version()` should report the actual prerelease string, not a boolean.

**Comment by justinmk** [comment]
> Currently `vim.version.cmp(vim.version(), vim.version())` errors

Now correctly returns 0.

> But probably `vim.version()` should report the actual prerelease string, not a boolean.

Since https://github.com/neovim/neovim/pull/23954 it now returns "dev".
