### ISSUE TITLE
doc generation strips out '%' from format string in example

### ISSUE THREAD

**Issue by blacksails** [neovim/neovim#23698]
### Problem

I wanted to copy paste the example from the docs where an autocmd event is printed using lua `string.format`. I noticed that the format string placeholder didn't have the `%` sign infront of the `s` https://github.com/neovim/neovim/blob/e3e6fadfd82861471c32fdcabe00bbef3de84563/runtime/doc/api.txt#L3296

I went ahead and checked to see if there was an issue in the source code, and there everything looks alright. https://github.com/neovim/neovim/blob/e3e6fadfd82861471c32fdcabe00bbef3de84563/src/nvim/api/autocmd.c#L350

Without having looked more into it I suspect that something in the doc generation, strips out the `%` sign needed for the placeholder in the format string.

### Steps to reproduce

Compare generated docs and source
https://github.com/neovim/neovim/blob/e3e6fadfd82861471c32fdcabe00bbef3de84563/runtime/doc/api.txt#L3296
https://github.com/neovim/neovim/blob/e3e6fadfd82861471c32fdcabe00bbef3de84563/src/nvim/api/autocmd.c#L350

### Expected behavior

I would expect the doc example to resemble the source

### Neovim version (nvim -v)

not relevant

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

not relevant

### Terminal name/version

not relevant

### $TERM environment variable

not relevant

### Installation

not relevant

**Comment by clason** [comment]
Already fixed in https://github.com/neovim/neovim/pull/23619
