### ISSUE TITLE
Add new language detection.

### ISSUE THREAD

**Issue by Dage-Hoo** [neovim/neovim#23693]
### Problem

![image](https://github.com/neovim/neovim/assets/83443827/28b69c7c-c067-4b99-bce4-397ea74f7824)
The language in the picture is [Slint](https://github.com/slint-ui/slint). I have installed a LSP about it but it doesn't works because this language hasn't been detected.

### Expected behavior

![image](https://github.com/neovim/neovim/assets/83443827/17fedc32-b590-4a09-9423-91a7c6d2a020)
I hope it can be detected properly. I set the filetype manually, and it works. I hope Neovim can detect this language correctly although I can use autocmd to set the filetype.

**Comment by clason** [comment]
Filetype detection is taken verbatim from Vim. Please open an issue or -- even better -- a PR at vim/vim explaining _how_ this filetype should be detected (extension, contents, file path, ...).
