### ISSUE TITLE
No color in the urxvt terminal since "Add support for true color terminals".

### ISSUE THREAD

**Issue by splinterofchaos** [neovim/neovim#2370]
To reproduce:

1. Start urxvt
2. `$ nvim -u NONE +'syntax on' <SOME FILE>`

Display is monochromatic.

I did a git bisect and found 8dd415e to be the first commit where this can be observed.

**Comment by tarruda** [comment]
I can only reproduce this if `NVIM_TUI_ENABLE_TRUE_COLOR` is set, but it's expected since urxvt doesn't support true color codes. Perhaps you have a `$TERM` override in your .Xresources?

**Comment by splinterofchaos** [comment]
The entirety of my `.Xresources`:
```bash
$ cat ~/.Xresources
dzen2.font:       -*-fixed-*-*-*-*-*-*-*-*-*-*-*-*
dzen2.foreground: #22EE11
dzen2.background: black
$ echo $TERM
rxvt-unicode-256color
```
You're right, actually unsetting `NVIM_TUI_ENABLE_TRUE_COLOR` does fix this, but setting it to `0` doesn't. Perhaps the code could check not just that the env variable exists, but is also non-zero, but I was mistaken so I'll close the issue.
