### ISSUE TITLE
conceal+extmark+unicode get messed up

### ISSUE THREAD

**Issue by champignoom** [neovim/neovim#23706]
### Problem

Unicode character gets wrongly concealed after inserting extmark.

### Steps to reproduce

`nvim --clean`
`:syntax match Normal 'x' conceal`
`:set conceallevel=2`
`:lua vim.api.nvim_create_namespace('')`
ix口口\<Esc>
`:lua vim.api.nvim_buf_set_extmark(0,1,0,0,{ end_col = 1,  end_row = 0,  hl_mode = "combine",  virt_text = { { "◉" } },  virt_text_pos = "overlay" })`
o\<Esc>
`:lua vim.api.nvim_buf_clear_namespace(0,-1,0,-1)`

Only one 口 remains.

### Expected behavior

Two 口口 should remain.

### Neovim version (nvim -v)

NVIM v0.9.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 13.2.1

### Terminal name/version

iTerm2 build 3.4.19

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
This can actually also happen without conceal with the following steps:
`:lua vim.api.nvim_create_namespace('')`
i口口
`:lua vim.api.nvim_buf_set_extmark(0,1,0,0,{ end_col = 1,  end_row = 0,  hl_mode = "combine",  virt_text = { { "◉" } },  virt_text_pos = "overlay" })`
`:mode`
`:lua vim.api.nvim_buf_clear_namespace(0,-1,0,-1)`

**Comment by zeertzjq** [comment]
Oh, this bug also isn't reproducible in all terminal emulators and GUIs.
