### ISSUE TITLE
Can we do better than "Last set from Lua"?

### ISSUE THREAD

**Issue by textzenith** [neovim/neovim#23719]
### Problem

One thing that was always nice about Vim was being able to use the `verbose` command modifier to find which file had munged one of your settings.

However, in my Neovim config, almost everything is Lua, and all `verbose` gives me is 'Last set from Lua'.

Not only is this a regression, it's a regression in one of Neovim's *main selling points* — that is, configuration. It's the kind of thing that makes me wanna switch back to plain old Vim from Neovim!

Now, obviously, I don't want to do that 😆, so firstly, I'd like to know if there's a reason this information can't be set from Lua?

Lua is powerful, and I'm convinced I could even patch this feature in from within my config files, without altering the source. You'd only need 1) The `debug` library, 2) A bit of metatable wizardry, and then 3) Some way to override the default "set from Lua". In fact, that would make a very useful plugin — has anybody done that yet? Or is this in the source under some setting I haven't yet discovered?

So secondly, would the rest of you see this as useful and/or even essential? I've spent three hours trying to track down why a single setting is changing, and not only is it frustrating, it's an ugly and primitive way of doing things (and it's a bit of a middle finger to the user to make changing a simple setting so damn hard, definitely not the Neovim way, I do believe!)

OK, thanks for hearing me out, and I hope we can start some kind of discussion on this. Looking forward to Neovim getting better and better with each update! 😀

### Expected behavior

```
Last set from foo-plugin/bar.lua, line 76, column 54:
      vim.bo.shiftwidth = 4
```

**Comment by clason** [comment]
Yes, use `nvim -V1`. (This is not enabled by default since tracing through the Lua stack has noticeable performance cost.)

**Comment by clason** [comment]
> For example, even changing the verbose message to Last set from Lua; run Neovim with -V1 for more information would have saved a lot of people a lot of bother.

PR welcome.

**Comment by UnkwUsr** [comment]
Currently `:help :verbose-cmd` have some words about it, but it should be documented properly. Then, I think, link to those help page should be added in verbose output, like ``Last set from Lua; read `:help :verbose-cmd-V1` for more information``
