### ISSUE TITLE
Getting rid of `os_breakcheck` and friends.

### ISSUE THREAD

**Issue by tarruda** [neovim/neovim#2371]
A major obstacle currently blocking Neovim from achieving a better asynchronous model is the `os_breakcheck` function and its friends(`line_breakcheck` and `fast_breakcheck`). These functions are used extensively in the code and have one purpose only: Check if the user typed ctrl+c while running some task that may take too long to complete.

The `*_breakcheck` functions are the biggest reason for the distinction between deferred and immediate events: They are called everywhere, and some parts of the code don't expect vimscript to be executed(notably the regexp engine, which can have strings currently being used freed by vimscript), something that can happen when entering the event loop(which is exactly what `os_breakcheck` does). The deferred queue is there to delay handling "dangerous" events to one of nvim main mode loops(`main_loop`, `edit`, `terminal_enter` and others) where it's safe to run vimscript.

The simplest solution to the problem(as far as I can see) is to run libuv event loop in a IO thread that pushes most events to a queue consumed by the main thread. Some events need to be handled directly in the IO thread, such as code that preprocesses user input and sets `got_int`. With this in place, all calls to `{os,line,fast}_breakcheck` can be removed and `got_int` can be checked directly by loops that uses ctrl+c as a break condition. In the end it will be easier to reason and understand the code  despite the extra thread(which from the main thread POV, is simply producing events)

We already push events received by libuv to queues in order to break `uv_run` recursion(see `event_poll`) so I think this change won't be very big. Some refactoring will be required, but it will mostly consist of synchronizing access to the queues using mutexes and condition variables and making sure no code in libuv callbacks access data used by the main thread. 

I've created this issue now because I've faced the problem directly when trying to use `jobwait` with code that calls the regexp engine(which can crash nvim, ref: https://github.com/junegunn/vim-plug/issues/104#issuecomment-87711295), and wanted to share with other developers to see if better solutions come up.

Moving IO to another thread will also fix #2093

**Comment by splinterofchaos** [comment]
If I understand this issue, `os_breakcheck()` just calls `event_poll(0)` because without running the uv event loop, we can't know if a `ctrl+c` has been received. If we processed input in another thread that set `got_int` to `true` the moment it read `ctrl+c`, then we wouldn't need to run `event_poll(0)` in many places. That would improve the efficiency in many places, like `file_search.c`, `tag.c`, and the regex engine, which call `os_breakcheck()` quite frequently, although it could also mean we don't process certain events during these long-running algorithms. (Is that a good or bad thing?)

> The deferred queue is there to delay handling "dangerous" events to one of nvim main mode loops(main_loop, edit, terminal_enter and others) where it's safe to run vimscript.

You're referring to `K_EVENT`s, right? 

> Some refactoring will be required, but it will mostly consist of synchronizing access to the queues using mutexes and condition variables and making sure no code in libuv callbacks access data used by the main thread.

This is the part I'm a little fuzzy on. What's an example of a situation where an event will not be deferred to the main thread, but the IO thread will be competing for a resource? Things like the input buffer?

Sounds like a good idea to me, on the surface. I'm curious how this will impact the various sub-systems.

**Comment by ZyX-I** [comment]
> Some refactoring will be required, but it will mostly consist of synchronizing access to the queues using mutexes and condition variables and making sure no code in libuv callbacks access data used by the main thread.

What about lock-free queues if you think this is likely? (Though I as well don’t know why this should happen.)

**Comment by tarruda** [comment]
> and the regex engine, which call os_breakcheck() quite frequently, although it could also mean we don't process certain events during these long-running algorithms. (Is that a good or bad thing?)

This is good, it means the program state is more predictable

> You're referring to K_EVENTs, right?

Yes. `K_EVENT` is a temporary hack that I hope to get rid of sooner or later

>  What's an example of a situation where an event will not be deferred to the main thread, but the IO thread will be competing for a resource? Things like the input buffer?

Yes. We still need to separate api/*.c functions that should be handled by the IO thread from those that need to be handled by the main thread. `vim_input` is the only example that comes to mind, since it's what fills the input buffer and sets `got_int`. I will probably use a macro like `FUNC_ATTR_DEFERRED` macro to mark functions that should be handled by the IO thread

Though it's best to keep data sharing to a minimum, with only the event queue being accessed by both threads. Some refactoring will be required for this: input_enqueue will "publish" input events to the main thread instead of filling the input buffer directly.

> What about lock-free queues if you think this is likely? (Though I as well don’t know why this should happen.)

I'm not sure how that's possible since the main thread must be idle in order to wait for events from the IO thread. The only way I know to achieve that is with locks and condition variables, though libuv provides a semaphore API which is more high level and a good fit for this use case.

**Comment by justinmk** [comment]
> Moving IO to another thread will also fix #2093

That seems to be fixed.

> I've faced the problem directly when trying to use jobwait with code that calls the regexp engine(which can crash nvim, ref: junegunn/vim-plug#104 (comment)), 

https://github.com/neovim/neovim/issues/3150 suggests that the regexp crashes are actual regexp bugs. Vim itself has seen 6-8 recent patches in that area.

>  With this in place, all calls to {os,line,fast}_breakcheck can be removed and got_int can be checked directly by loops that uses ctrl+c as a break condition

https://github.com/neovim/neovim/pull/3029 did not remove the breakcheck calls. Is that still needed?

**Comment by bfredl** [comment]
This cannot be done as `os_breakcheck` implements fast events, which are exposed with limitations to plugins (access lua state but not editor state).
