### ISSUE TITLE
A pdf version of the documentation is needed.

### ISSUE THREAD

**Issue by gaoqiangks** [neovim/neovim#23728]
### Problem

I want to print the documentation of neovim. However, no printable version is applicatable.

### Expected behavior

Can you provide a pdf version of the documentation?

**Comment by clason** [comment]
Just use https://github.com/nathangrigg/vimhelppdf

**Comment by justinmk** [comment]
Did you try visiting https://neovim.io/doc/user/index.html and use your browser to "print to PDF"?
