### ISSUE TITLE
TUI bug when building Arch Linux package

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2372]
@tarruda

I think #2025 (or more specifically, bbcddc5; previous revision 20f52f4 works) caused a problem that, at the moment, I can only reproduce when building the Arch Linux package (ref https://github.com/rmarquis/pacaur/issues/325). It might be that an extra character is pushed to the terminal, causing the final "Proceed with installation? [Y/n]" to abort.

Without bug (20f52f4): prompts for user input and waits at the end of the package build process
```
:: Proceed with installation? [Y/n]                             # hit <CR>
==> WARNING: Failed to install built package(s).
```

With bug (bbcddc5): Prompt is automatically "answered".. but no newline inserted.
```
:: Proceed with installation? [Y/n] ==> WARNING: Failed to install built package(s).
```

I don't really know what causes it, because the following doesn't seem to fix it:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4219c69..f45a425 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -276,7 +276,7 @@ foreach(PROG ${RUNTIME_PROGRAMS})
   install_helper(PROGRAMS ${PROG} DESTINATION share/nvim/${BASEDIR})
 endforeach()
 
-install(SCRIPT ${PROJECT_SOURCE_DIR}/cmake/GenerateHelptags.cmake)
+#install(SCRIPT ${PROJECT_SOURCE_DIR}/cmake/GenerateHelptags.cmake)
 
 # Go down the tree.
```

Is `nvim` invoked at any other point during the build/installation process?

The issue is still present on current master (95db8df). I'll try to see if I can find a better way to reproduce it.

**Comment by fwalch** [comment]
Possibly the same problem as #2377.

**Comment by tarruda** [comment]
I just reproduced this locally after reinstalled the bundled dependencies

**Comment by tarruda** [comment]
Actually my problem was this: https://github.com/neovim/neovim/issues/2364#issuecomment-91845325 , sorry for the confusion

**Comment by fwalch** [comment]
Closing as duplicate of #2377.
