### ISSUE TITLE
When I delete the line that has virtual text, the virtual text not being removed

### ISSUE THREAD

**Issue by zhoudaxia2016** [neovim/neovim#23721]
### Problem

When I delete the line that has virtual text, the virtual text not being removed

### Steps to reproduce

- Create a extmark with virtual text at a line
- Delete the line
- The virtual text still exists

### Expected behavior

The virtual text being removed
Is it a feature？

### Neovim version (nvim -v)

NVIM v0.10.0-dev-372+gcb34d0ddd

### Vim (not Nvim) behaves the same?

no

### Operating system/version

wsl2

### Terminal name/version

window terminal 1.15

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by lewis6991** [comment]
steps to reproduce is not sufficient.

**Comment by lewis6991** [comment]
This is the intended behaviour of extmarks. You must manually manage extmarks on text changes.
