### ISSUE TITLE
incorrect loading of colorschemes by `:colorscheme` command

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#23724]
### Problem

It seems that the current `:colorscheme` command is loading colorscheme incorrectly, contrary to what the documentation says.

### Steps to reproduce

Run the following bash script to install two colorschemes

```bash
rm -rf ./repro/
mkdir -p ./repro/pack/debug/opt

git clone https://github.com/olimorris/onedarkpro.nvim ./repro/pack/debug/opt/onedarkpro.nvim
git clone https://github.com/navarasu/onedark.nvim ./repro/pack/debug/opt/onedark.nvim
```

Then run the following vim script `mini.vim` with `nvim --clean -u mini.vim`:

```vim
set packpath+=./repro
packadd onedark.nvim
```

Inside nvim, run command: `color onedark`. Then nvim will error out:

```
Error detected while processing /Users/hao/Projects/toy_code/repro/pack/debug/opt/onedarkpro.nvim/colors/onedark.vim:
line    4:
E5108: Error executing lua [string ":lua"]:1: module 'onedarkpro.config' not found:
        no field package.preload['onedarkpro.config']
        no file './onedarkpro/config.lua'
        no file '/opt/homebrew/share/luajit-2.1.0-beta3/onedarkpro/config.lua'
        no file '/usr/local/share/lua/5.1/onedarkpro/config.lua'
        no file '/usr/local/share/lua/5.1/onedarkpro/config/init.lua'
        no file '/opt/homebrew/share/lua/5.1/onedarkpro/config.lua'
        no file '/opt/homebrew/share/lua/5.1/onedarkpro/config/init.lua'
        no file './onedarkpro/config.so'
        no file '/usr/local/lib/lua/5.1/onedarkpro/config.so'
        no file '/opt/homebrew/lib/lua/5.1/onedarkpro/config.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './onedarkpro.so'
        no file '/usr/local/lib/lua/5.1/onedarkpro.so'
        no file '/opt/homebrew/lib/lua/5.1/onedarkpro.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

### Expected behavior

I can use the colorscheme onedark without error.

According to the doc of command `:colorscheme {name}`:

```
:colo[rscheme] {name}	Load color scheme {name}.  This searches 'runtimepath'
			for the file "colors/{name}.(vim|lua)".  The first one that
			is found is loaded.
			Note: "colors/{name}.vim" is tried first.
			Also searches all plugins in 'packpath', first below
			"start" and then under "opt".
```

I would expect the file `colors/onedark.lua` under the directory `./rerpo/pack/debug/opt/onedark.nvim` is loaded, since we explicitly add that directory to the runtimepath (so it should be searched first). The directory `/rerpo/pack/debug/opt/onedarkpro.nvim` is not even in the runtimepath.

But apparently, it is not what it works in reality. 

### Neovim version (nvim -v)

0.9.0 stable

### Vim (not Nvim) behaves the same?

-- not applicable here

### Operating system/version

macOS 13.3.1

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
Maybe the docs can better reflect current behavior is the `Note:` line is moved to the bottom. The current behavior indeed doesn't seem ideal though.
