### ISSUE TITLE
extmark-highlight does not cover a full tab (`\t`)

### ISSUE THREAD

**Issue by L3MON4D3** [neovim/neovim#23734]
### Problem

highlight applied via extmarks only highlights the first column of a tab, instead of all 2/4/8/whatever.

Pre- efa9b299a:
![screen](https://github.com/neovim/neovim/assets/41961280/83f7f66f-a017-4df1-9b2b-b37ca1c022c2)
Post:
![screen](https://github.com/neovim/neovim/assets/41961280/3e47bbeb-a09c-4e20-8fa6-6884ccec3fa6)

Not completely sure if this should be a bug-report, just seems like a potentially undesired change.

### Steps to reproduce

1. `nvim --clean`
2. Insert some text with tabs into the buffer, for example
```
asdf
	asdf
	asdf
	asdf
asdf
```
(note that the "asdf" are indented by tabs.)
3. Call `:lua vim.api.nvim_create_namespace("") vim.api.nvim_buf_set_extmark(0,1,0,0, {end_row = 5, end_col=0, hl_group = "Visual"})` to highlight the lines.

### Expected behavior

As shown above, only the first column of a tab is highlighted, as opposed to all columns that belong to it.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-373+g07883940b2

### Vim (not Nvim) behaves the same?

not applicable I think

### Operating system/version

Linux 6.3.2

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

AUR

**Comment by zeertzjq** [comment]
It also doesn't cover the second cell of a control character

**Comment by zeertzjq** [comment]
This actually isn't a new bug. In versions as early as v0.6.0 this bug already happens if 'spell' is enabled.

**Comment by zeertzjq** [comment]
Simple fix:
```diff
diff --git a/src/nvim/drawline.c b/src/nvim/drawline.c
index 510731a43..3c9908f19 100644
--- a/src/nvim/drawline.c
+++ b/src/nvim/drawline.c
@@ -1912,6 +1912,9 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
         } else {
           wlv.char_attr = 0;
         }
+        if (extmark_attr != 0) {
+          wlv.char_attr = hl_combine_attr(wlv.char_attr, extmark_attr);
+        }
       }
     }
 
```

**Comment by zeertzjq** [comment]
Another simple fix:
```diff
diff --git a/src/nvim/drawline.c b/src/nvim/drawline.c
index 510731a43..d1be8e785 100644
--- a/src/nvim/drawline.c
+++ b/src/nvim/drawline.c
@@ -1925,6 +1925,14 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
     // "p_extra[n_extra]".
     // For the '$' of the 'list' option, n_extra == 1, p_extra == "".
     if (wlv.n_extra > 0) {
+      if (extmark_attr != 0) {
+        if (!attr_pri) {
+          wlv.char_attr = hl_combine_attr(wlv.char_attr, extmark_attr);
+        } else {
+          wlv.char_attr = hl_combine_attr(extmark_attr, wlv.char_attr);
+        }
+      }
+
       if (wlv.c_extra != NUL || (wlv.n_extra == 1 && wlv.c_final != NUL)) {
         c = (wlv.n_extra == 1 && wlv.c_final != NUL) ? wlv.c_final : wlv.c_extra;
         mb_c = c;               // doesn't handle non-utf-8 multi-byte!
```

**Comment by L3MON4D3** [comment]
Nice fix, thank you for looking into it :+1:

**Comment by clason** [comment]
@luukvbaal since you're on a roll ;)

**Comment by zeertzjq** [comment]
> Simple fix:
> 
> ```diff
> diff --git a/src/nvim/drawline.c b/src/nvim/drawline.c
> index 510731a43..d1be8e785 100644
> --- a/src/nvim/drawline.c
> +++ b/src/nvim/drawline.c
> @@ -1925,6 +1925,14 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool nochange,
>      // "p_extra[n_extra]".
>      // For the '$' of the 'list' option, n_extra == 1, p_extra == "".
>      if (wlv.n_extra > 0) {
> +      if (extmark_attr != 0) {
> +        if (!attr_pri) {
> +          wlv.char_attr = hl_combine_attr(wlv.char_attr, extmark_attr);
> +        } else {
> +          wlv.char_attr = hl_combine_attr(extmark_attr, wlv.char_attr);
> +        }
> +      }
> +
>        if (wlv.c_extra != NUL || (wlv.n_extra == 1 && wlv.c_final != NUL)) {
>          c = (wlv.n_extra == 1 && wlv.c_final != NUL) ? wlv.c_final : wlv.c_extra;
>          mb_c = c;               // doesn't handle non-utf-8 multi-byte!
> ```

This fix depends on a commit in the inline virtual text PR.
