### ISSUE TITLE
autocmd WinScrolled not triggered when pattern is not *

### ISSUE THREAD

**Issue by champignoom** [neovim/neovim#23738]
### Problem

WinScrolled is not triggered by ctrl-y.

### Steps to reproduce

touch test.txt
nvim --clean test.txt
100iabc\<CR>\<Esc>
:autocmd WinScrolled * echom "scrolled"
:autocmd WinScrolled *.txt echom "scrolled-txt"
\<ctrl-y>

then only "scrolled" is printed

### Expected behavior

both "scrolled" and "scrolled-txt" should be printed.

### Neovim version (nvim -v)

NVIM v0.9.0

### Vim (not Nvim) behaves the same?

No(9.0). Neither "scrolled" nor "scrolled-txt" is printed, which is probably more wrong.

### Operating system/version

macOS 13.2.1

### Terminal name/version

iTerm2 build 3.4.19

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
Please read the docs
```
				The pattern is matched against the |window-ID|
				of the first window that scrolled or resized.
				Both <amatch> and <afile> are set to the
				|window-ID|.
```
