### ISSUE TITLE
doc: nvim_set_keymap ignores "rhs" if callback provided

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#23749]
### Problem

A mapping created with `nvim_set_keymap` doesn't execute when a callback option is used.

### Steps to reproduce

```
nvim --clean file.lua
```
Add the following content:
```lua
vim.api.nvim_set_keymap('n', 'x', 'x', {
  noremap = true,
  callback = function()
    print('callback')
  end
})
```
Source the file:
```
:luafile %
```
Type an `x`.

### Expected behavior

I expected that a character would be deleted, the same way it ordinarily would when pressing `x`.

In this case, the callback executes, printing `callback`, but the mapping does not.

### Neovim version (nvim -v)

v0.9.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Kubuntu 23.04

### Terminal name/version

Konsole 22.12.3

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by luozhiya** [comment]
Unable to reproduce bug in version `nightly`

**Comment by zeertzjq** [comment]
`rhs` is ignored if `callback` is specified

**Comment by nyngwang** [comment]
Why not use `vim.keymap.set`, as this is newer and better?

**Comment by dstein64** [comment]
> "Why not use vim.keymap.set, as it is newer?"

@nyngwang, since `vim.keymap.set` [calls](https://github.com/neovim/neovim/blob/aa9d46b6724cf3454aca602e64350856827c3ab8/runtime/lua/vim/keymap.lua#L73) `nvim_set_keymap`, using the latter for a minimal reproducible example seemed suitable.
