### ISSUE TITLE
Existing tab, white spaces getting replaced upon save with no plugins in neovim 0.9

### ISSUE THREAD

**Issue by psglinux** [neovim/neovim#23746]
### Problem

I'm using neovim 0.9. Opened a file with existing tabs and white spaces. On saving this file the whitespaces and tabs got overwritten. Is this some thing recently introduced in 0.9. I was earlier using 0.7 and did not see this issue. 

### Steps to reproduce

Install neovim with snap in ubuntu 22.04, do not have any init.lua or any other configs to initialize neo vim.

open a file with tabs and white spaces
save the file,
Result : the tabs and white spaces gets replaces. 
[neovim-0.9-healthcheck.txt](https://github.com/neovim/neovim/files/11559386/neovim-0.9-healthcheck.txt)

NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Expected behavior

By default without any config neovim should not be replacing existing tab and white spaces.

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

vim 8.2 do not have this issue.

### Operating system/version

Ubuntu 22.04.2 LTS

### Terminal name/version

TMUX on gitbash

### $TERM environment variable

screen-256color

### Installation

snap

**Comment by luukvbaal** [comment]
> Result : the tabs and white spaces gets replaces.

What does this mean? What is it getting replaced with? Any whitespace or just at the end of a line?

The only thing I can think of is that Nvim now respects `.editorconfig` so if you are working on a project that includes this, or have on in parent directories, trailing whitespace may be removed. Other than that IDK.

**Comment by psglinux** [comment]
I see this issue in one of my git work spaces. Any file that is copied to the git repro workspace with spaces and tabs, open the file with neovim (with no init.lua and the plugins uninstalled), upon save the tabs and extra spaces gets replaced by "no-spaces". 
I will try add in more data, if i'm able to figure out what's causing this issue in this git workspace.

**Comment by psglinux** [comment]
Compiled 0.08, 0.09 and latest. I see the issue in both 0.09 and latest, tab and white spaces are getting replaced with no spaces.
Is there a way to get debug logs in neovim to see what's going on when :w! is done. Any compile flags may help here.

**Comment by psglinux** [comment]
> 

This was the issue. there was an editor config that was recently introduced. .. Thanks for your response. Please close this issue.
