### ISSUE TITLE
nvim takes long time to open a large single-line file

### ISSUE THREAD

**Issue by 383494** [neovim/neovim#23756]
### Problem

nvim takes long time to open a large single-line file(> 1M)

### Steps to reproduce

nvim --clean
:edit foo
nvim freezes

### Expected behavior

open the file after seconds(like vim does)

### Neovim version (nvim -v)

0.9.0 but idk what commit it is

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

arch linux

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

system package manager

**Comment by zeertzjq** [comment]
Duplicate of #23563
