### ISSUE TITLE
Inconsistent behavior of scroll position on inter-buffer jumps

### ISSUE THREAD

**Issue by drybalka** [neovim/neovim#23769]
### Problem

Steps to reproduce:
- open a project with more than one source file (I tested it for Lua and for Scala projects, so probably the behavior is lsp-independent).
- move the cursor down without populating the jumplist/tagstack until you find a symbol with a definition in another file. Let's say the scroll position is such that your cursor is on the top of the screen 
- go to the definition of the symbol -> if the definition is sufficiently low the cursor will be at the bottom of the screen (which is in itself a bit annoying)
- click `<c-t>` to go back -> the cursor will be in the center of the screen and no longer at the top like before the jump
- go to the definition again -> now the cursor will be in the middle of the screen
- click `<c-o>` to go back -> the cursor is again will be in the middle 
- finally click `<c-i>` to go forward again -> now the cursor again will be at the bottom of the screen

This is not the bug per se, but still an inconvenience. Especially when one jumps between files often while reading/editing code.

### Expected behavior

It would be cool if the scroll position and behavior on jump was consistent. In an ideal case jumps back and forth in tagstack and jumplist could save the scroll position.

My other idea was to write a plugin that could save the scroll position, but I could not even find the needed nvim lua functions for jumping back and forth in tagstack/jumplist (not even saying about the problem of somehow saving the scroll position on all jumps).

**Comment by muniter** [comment]
Try out `set jumoptions = view`
