### ISSUE TITLE
Diagnostics are not enabled for buffer if globally disabled

### ISSUE THREAD

**Issue by sstallion** [neovim/neovim#23786]
### Problem

I've begun using diagnostics selectively on a per-filetype basis and I've run into an interesting corner case. In my init.lua, I have diagnostics disabled for all buffers (eg. `vim.diagnostic.disable()`. If I attempt to enable them for a given buffer using an `BufEnter` autocommand that calls `vim.diagnostic.enable(0)`/`vim.diagnostic.enable(vim.api.nvim_get_current_buf())`, diagnostics remain disabled.

### Steps to reproduce

nvim
lua vim.diagnostic.disable()
" edit a file of your choice that supports diagnostics
lua vim.diagnostic.enable(0)
" diagnostics will not be shown

### Expected behavior

Diagnostics should be enabled for buffer if requested, even if globally disabled.

### Neovim version (nvim -v)

v0.9.0

### Vim (not Nvim) behaves the same?

No, diagnostics not supported

### Operating system/version

macOS 12.5

### Terminal name/version

iTerm2 3.5.0beta10

### $TERM environment variable

xterm-256color

### Installation

MacPorts

**Comment by glepnir** [comment]
use disable on `DiagnosticChanged` callback

```lua
vim.api.nvim_create_autocmd('DiagnosticChanged', {
  callback = function(opt)
    vim.diagnostic.disable(opt.buf)
  end,
})

```

**Comment by sstallion** [comment]
Thanks! Out of curiosity, should this still be considered a bug? This is a great workaround, but the behavior of enable/disable still seems a little unexpected.

**Comment by justinmk** [comment]
@gpanders is this intentional?

**Comment by gpanders** [comment]
Yes, this is by design, although we could change it.

I did something similar for a while, though I used a `BufEnter` autocommand to first call `vim.diagnostic.disable(0)` for a new buffer, and then later would enable them after some event happened (e.g. writing the buffer). That approach should provide the same effect.

If we did want to change the semantics such that `enable(buf)` overrides `disable()` (global), I think this patch should do it (untested):

```diff
diff --git a/runtime/lua/vim/diagnostic.lua b/runtime/lua/vim/diagnostic.lua
index 0d1d01b39..ffaa74d7c 100644
--- a/runtime/lua/vim/diagnostic.lua
+++ b/runtime/lua/vim/diagnostic.lua
@@ -1593,12 +1593,12 @@ function M.enable(bufnr, namespace)
   else
     bufnr = get_bufnr(bufnr)
     if namespace == nil then
-      diagnostic_disabled[bufnr] = nil
+      diagnostic_disabled[bufnr] = false
     else
       if type(diagnostic_disabled[bufnr]) ~= 'table' then
         return
       end
-      diagnostic_disabled[bufnr][namespace] = nil
+      diagnostic_disabled[bufnr][namespace] = false
     end
   end
 
```

**Comment by glepnir** [comment]
ref https://github.com/neovim/neovim/pull/28227 and now it's can't reproduce
