### ISSUE TITLE
Include a standard parsing library?

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#23784]
### Problem

As a plugin author I want to be able to write robust and reliable text parsers. Neovim already includes Vim regular expressions and Lua regular expressions, but writing anything but the most trivial parsers with these is a major headache. There is also Tree-sitter, but that is for parsing entire buffers, not some piece of text I might have gotten from an external process and want to pick apart into some data structure. I want to be able to specify an ad-hoc parser which might not have any use outside of my own plugin.

Examples where a parser library might be useful:

- Parsing weird file types like GNU Info
- Parsing domain-specific languages like the Vader test files used by [vader.vim](https://github.com/junegunn/vader.vim)
- Parsing binary files
- Parsing output from other applications which is not in JSON format

### Expected behavior

We already use [lpeg](http://www.inf.puc-rio.br/~roberto/lpeg/) at build time, so it would make sense to include the library and expose it (or a facade to it) as `vim.peg`. I don't have a particular opinion about parsing libraries, so maybe there is some better parsing library out there, lpeg is just a library I happen to know about.

**Comment by clason** [comment]
`:h vim.lpeg`  (on master).
