### ISSUE TITLE
Binding <M-S-Tab>?

### ISSUE THREAD

**Issue by fortes** [neovim/neovim#2379]
I'm trying to do the following for easy tab traversal in NeoVim. I've stripped my `.nvimrc` to the following:

```
noremap <M-t> :tabnew<cr>
noremap <M-Tab> :tabn<cr>
noremap <S-M-Tab> :tabp<cr>
```

`<M-t>` and `<M-tab>` work beautifully, but `<S-M-Tab>` does nothing. Am I missing something obvious?

This is NeoVim inside of iTerm2. Here's the `--version` output

```
[10:44] fortes@fair:~ nvim --version
NVIM 0.0.0-alpha+201504081227 (compiled Apr  8 2015 10:40:28)
Commit: e1bac3b84090d07afa669a8b79816c28813c605e
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150408-19200-1h839n0/build/config -I/tmp/neovim20150408-19200-1h839n0/src -I/tmp/neovim20150408-19200-1h839n0/.deps/usr/include -I/tmp/neovim20150408-19200-1h839n0/.deps/usr/include -I/tmp/neovim20150408-19200-1h839n0/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150408-19200-1h839n0/.deps/usr/include -I/tmp/neovim20150408-19200-1h839n0/.deps/usr/include -I/tmp/neovim20150408-19200-1h
```

**Comment by justinmk** [comment]
Alt-tab is a bit of an edge-case, at least on Windows.

**Comment by fortes** [comment]
This is on a Mac, where alt/option-Tab does nothing by default.

**Comment by justinmk** [comment]
Sorry if I'm missing something (I don't use iTerm) but I just downloaded the iTerm2 nightly (Build 2.9.20150417-nightly), and neither `<m-tab>` nor `<m-s-tab>` works for me. `<m-tab>` is sent as `<tab>`. Is there an iTerm preference that needs to be set or something? 

OS X 10.10.3

NVIM 0.0.0-alpha+201504172305 (compiled Apr 17 2015 23:19:35)
Commit: a88e2f4fd4c3e10aabd41e758cc845332be013da

**Comment by fortes** [comment]
Using the following `.vimrc`:
```
nnoremap <Tab> :echom "Tab"<cr>
nnoremap <C-Tab> :echom "C-Tab"<cr>
nnoremap <S-Tab> :echom "S-Tab"<cr>
nnoremap <C-S-Tab> :echom "C-S-Tab"<cr>
nnoremap <M-Tab> :echom "M-Tab"<cr>
nnoremap <M-S-Tab> :echom "M-S-Tab"<cr>
nnoremap <C-M-Tab> :echom "C-M-Tab"<cr>
nnoremap <C-M-S-Tab> :echom "C-M-S-Tab"<cr>

" For comparison
nnoremap p :echom "p"<cr>
nnoremap <S-p> :echom "S-p"<cr>
nnoremap <C-p> :echom "C-p"<cr>
nnoremap <C-S-p> :echom "C-S-p"<cr>
nnoremap <M-p> :echom "M-p"<cr>
nnoremap <M-S-p> :echom "M-S-p"<cr>
nnoremap <C-M-p> :echom "C-M-p"<cr>
nnoremap <C-M-S-p> :echom "C-M-S-p"<cr>
```

The following keystrokes work in iTerm2 & the Mac OS X terminal app if you make sure it is set to send Meta key on Option:

* `Tab`
* `S-Tab`
* `M-Tab`
* `p`
* `S-p`
* `C-S-p`
* `M-p`
* `M-S-p`
* `C-M-S-p`

The following don't work:

* `C-Tab`: Sends `Tab`
* `C-S-Tab`: Nothing sent
* `M-S-Tab`: Nothing on iTerm 2, `Tab` on Terminal
* `C-M-Tab`: Nothing
* `C-M-S-Tab`: Nothing
* `C-P`: Sends `C-S-P`
* `C-M-P`: Sends `C-S-M-P`

**Comment by DirkR** [comment]
Just another kind of `nnoremap` weirdness. I have a similar problem. I have the following mappings defined in .vimrc:

    nnoremap <S-C-j> :cN<CR>
    nnoremap <S-C-k> :cn<CR>

This should map `Control-Shift-j` to go backward in my quicklist and  `Control-Shift-k` to go forward. On OSX ans the builtin Terminal.app it works by pressing `Alt-Control-j` and  `Alt-Control-k`. Im using `NVIM 0.0.0-alpha+201504082319 (compiled Apr  9 2015 10:55:29)`.

PS: I don't want to take over this issue, but maybe both problems have the same origin.

**Comment by gutenye** [comment]
In order for `<M-Tab>` working, iTerm2 needs set: `Preferences -> Profiles -> Keys: Left option key act as +Esc`

**Comment by zeertzjq** [comment]
I don't think this is still a problem.
