### ISSUE TITLE
tests don’t work with the system busted and in the network isolated environment

### ISSUE THREAD

**Issue by mcepl** [neovim/neovim#23814]
### Problem

Neovim insists on downloading luarocks even when lua51-luarocks-3.9.1 has been already installed in the build environment?

[Complete build log describing the situation](https://github.com/neovim/neovim/files/11590945/_log.txt)

@bfredl claimed, that it could be changed with `-DUSE_BUNDLED_LUAROCKS=OFF`, but even with that in the `%build` stage, the situation has not changed.

[neovim.spec](https://github.com/neovim/neovim/files/11590982/neovim.spec.txt)

When the tests are switched off (`%make_build test` line is commented out) the build passes.

@bfredl then commented that running the tests with an external busted install was not supported in the master branch at the moment. It is in the middle of a restructuring of the deps handling.

### Steps to reproduce

run the test suite

### Expected behavior

Uses packages installed on the system

### Neovim version (nvim -v)

0.9.0+git9dd48f783

### Vim (not Nvim) behaves the same?

I don’t think so

### Operating system/version

Linux, openSUSE/Tumbleweed

### Terminal name/version

foot version: 1.14.0 -pgo +ime +graphemes -assertions

### $TERM environment variable

xterm-256color

### Installation

building openSUSE package from sources

**Comment by dundargoc** [comment]
Oof. I was hoping we could avoid `USE_BUNDLED_` option hell in the main build. I can't come up with any other reasonable solution though.

**Comment by mcepl** [comment]
I don't think it helps much. Yes, there are no errors, but the `%check` section doesn't look much hopeful either:

```
[  212s] Executing(%check): /usr/bin/bash -e /var/tmp/rpm-tmp.T7HRZe
[  212s] + umask 022
[  212s] + cd /home/abuild/rpmbuild/BUILD
[  212s] + cd neovim
[  212s] + HOSTNAME=OBS
[  212s] + USERNAME=OBS
[  212s] + pushd build
[  212s] ~/rpmbuild/BUILD/neovim/build ~/rpmbuild/BUILD/neovim
[  212s] ++ readlink -f ../lj-busted.sh
[  212s] + /usr/bin/make -O -j3 V=1 VERBOSE=1 BUSTED_PRG=/home/abuild/rpmbuild/BUILD/neovim/lj-busted.sh test
[  212s] make: Nothing to be done for 'test'.
[  212s] + popd
[  212s] ~/rpmbuild/BUILD/neovim
[  212s] + RPM_EC=0
[  212s] ++ jobs -p
[  212s] + exit 0
```
