### ISSUE TITLE
Performance issue with Pyright: high CPU usage and overall slowdown

### ISSUE THREAD

**Issue by oyarsa** [neovim/neovim#23819]
### Problem

Using `pyright` (and `clojure_lsp`, but I'll focus on `pyright`) leads to high CPU usage and laggy behaviour in the edit.

This happens on a remtoe machine running Ubuntu 20.04, but does not happen on my local Macbook.

### Steps to reproduce using "nvim -u minimal_init.lua"

The issue happens in the suggested minimal config:

Minimal config

```lua
-- minimal_init.lua
local pattern = "python"
local cmd = { "pyright-langserver", "--stdio" }
local root_markers = { ".git", ".editorconfig", "pyproject.toml" }

vim.api.nvim_create_autocmd("FileType", {
	pattern = pattern,
	callback = function(args)
		local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
		local root_dir = match and vim.fn.fnamemodify(match, ":p:h") or nil
		vim.lsp.start({
			name = "pyright",
			cmd = cmd,
			root_dir = root_dir,
			settings = { python = {} },
		})
	end,
})
vim.lsp.set_log_level("debug")
require("vim.lsp.log").set_format_func(vim.inspect)
```

Steps to reproduce:

Create a test file, e.g.:

```py
# test.py
print("hello world")
```

Open it with the second configuration:

```sh
nvim -u minimal_init.lua test.py
```

Just having it open makes the `nvim --embed test.py -u minimal_init.lua` consume 60%+ CPU. Using the editor is very difficult because keypresses might take almost a second to register.

I left neovim opened for about 20 seconds before closing.

### Expected behavior

The editor should be responsive when the LSP is connected, and CPU usage when idle should be minimal.

### Neovim version (nvim -v)

v0.10.0-dev (installed on 2023-05-29 from https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable)

### Language server name/version

1.1.310

### Operating system/version

Ubuntu 20.04.6 LTS (Linux 5.4.0.-149-generic)

### Log file

https://gist.github.com/oyarsa/850466b3116d8f2f39b6f35687a4386d

**Comment by lewis6991** [comment]
This looks the same as https://github.com/neovim/neovim/issues/23725

**Comment by Shougo** [comment]
You can use the workaround.

https://github.com/neovim/neovim/issues/23725#issuecomment-1561364086

**Comment by nyngwang** [comment]
> You can use the workaround.
> 
> [#23725 (comment)](https://github.com/neovim/neovim/issues/23725#issuecomment-1561364086)

Lol, It's so fast that I feel like I'm flying! Thanks for the workaround/solution!
