### ISSUE TITLE
Extmarks stopped being shown over folded lines

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#23831]
### Problem

It now not possible to add extmark on folded line. This is a **very** useful behavior to have for "jump"-like plugins ('hop.nvim', 'mini.jump2d', etc.).

 Works on Neovim 0.9.0. It seems to also have been possible on version `NVIM v0.10.0-dev-387+gd31f7648e`.

### Steps to reproduce

1. `nvim --clean`
2. Add lines `aaa`, `bbb`, `ccc`.
3. `:2,3fold`
4. `:lua ns_id = vim.api.nvim_create_namespace('test')`
5. `:lua vim.api.nvim_buf_set_extmark(0, ns_id, 1, 0, { virt_text = { { 'X', 'Error' } }, virt_text_pos = 'overlay' })`. Nothing is shown over folded region, but extmark is there (its text is shown if fold is expanded).

### Expected behavior

Extmark text `X` shown at first column of folded line.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-415+g55f6a1cab

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.3.4-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
Hmm, allowing virtual text on a folded line can cause crashes.

**Comment by zeertzjq** [comment]
Oh, only inline virtual text can cause crashes.

**Comment by zeertzjq** [comment]
I just realized that the crash I previously tried to fix can also happen without folds. Created a new issue #23848.

**Comment by zeertzjq** [comment]
Are you already treating folded lines differently from non-folded lines? If so I suggest using `virt_text_win_col` instead of `overlay`.

**Comment by echasnovski** [comment]
> Are you already treating folded lines differently from non-folded lines? If so I suggest using `virt_text_win_col` instead of `overlay`.

I treat folded lines differently in that it makes sense to only allow placing extmark on first column (`col = 0`). But I don't treat them differently when placing extmarks.

Using `virt_text_win_col` is a bit tricky because I currently process per buffer and `virt_text_win_col` needs information about the left most visible column. I mean, it can be done if there is no other option, but it seems that `overlay` should be enough (if the issue will be resolved, that is).

**Comment by echasnovski** [comment]
Thanks, @zeertzjq! I'll try the fix for my use case after the Nightly build.
