### ISSUE TITLE
Left/right click not working on terminal, only scrollwheel works

### ISSUE THREAD

**Issue by Zeioth** [neovim/neovim#23849]
### Problem

By running this while I'm on neovim' terminal, I'm able to make the scroll wheel work on my terminal programs (ranger/gitui). 

    vim.api.nvim_set_option("mouse", "")

But my left and right click still do not work:

* Left click do nothing.
* Right click display neovim contextual menu.

I've been looking on the neovim docs and I don't see an option to fix this. There is some way currently?

### Steps to reproduce

* vim.api.nvim_set_option("mouse", "")
* :term
* run ranger, gitui or any other terminal program that uses mouse.

### Expected behavior

Scroll wheel, left click, and right click, should behave like in a norma terminal.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 20 2023 16:56:14)

### Operating system/version

Arch Linux

### Terminal name/version

foot version: 1.14.0

### $TERM environment variable

xterm-256color

### Installation

I've tried both AUR and community

**Comment by zeertzjq** [comment]
Nvim will not receive mouse events if you have disabled mouse.

**Comment by Zeioth** [comment]
It doesn't work with 

    set mouse='a'

either.

**Comment by zeertzjq** [comment]
Duplicate of #21106

**Comment by Zeioth** [comment]
Thank you for the hint zeertzjq. By setting this inside :term

    export TERM=tmux-256color

All mouse features work correctly on my terminal applications. Except for the terminal itself: mouse scroll provokes the terminal to enter into insert mode.
