### ISSUE TITLE
neovim installation instructinos

### ISSUE THREAD

**Issue by jjasghar** [neovim/neovim#23846]
### Problem

The documentation located here: https://github.com/neovim/neovim/wiki/Installing-Neovim#crux is no longer valid. It seems https://github.com/6c37/crux-ports no longer exists.

### Steps to reproduce

Looked at the wiki: https://github.com/neovim/neovim/wiki/Installing-Neovim#crux

### Expected behavior

A link to the ports for CRUX.

### Neovim version (nvim -v)

58618d208acd3827c4e86668529edb619bb9b8dd

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

n/a

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

ports

**Comment by clason** [comment]
The outdated instructions have been removed.

Up-to-date instructions welcome, but must be user-contributed.
