### ISSUE TITLE
Microsoft Defender SmartScreen has blocked unrecognized app startup. Running this application may pose a risk to your computer nvim-win64

### ISSUE THREAD

**Issue by RIKDXHQ11** [neovim/neovim#23855]
### Problem

Microsoft Defender SmartScreen has blocked unrecognized app startup. Running this application may pose a risk to your computer nvim-win64

### Steps to reproduce

As long as I install it, a warning will pop up

### Expected behavior

solve a problem.
Let me install it directly.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

windows 10

### Terminal name/version

ST-0.9

### $TERM environment variable

st-256color

### Installation

system package manager

**Comment by zeertzjq** [comment]
Not an Nvim issue
