### ISSUE TITLE
Treesitter can't find a handler for has-ancestor in 0.9.1

### ISSUE THREAD

**Issue by TheDreadedAndy** [neovim/neovim#23858]
### Problem

As of version 0.9.1, running with `nvim -u NONE` on a C file containing the following:
```
typedef struct foo {
    unsigned char *bar;
} foo_t;
```
Will cause a lua execution error and prevent treesitter from highlighting that definition correctly. This is after running `lua vim.treesitter.start(1, 'c')`.

The error is in runtime/lua/vim/treesitter/query.lua:557: 'No handler for has-ancestor?'. I am unable to see the rest of the error, as it is in virtual text and I wasn't able to figure out how to expand that fully (sorry).

### Steps to reproduce

nvim -u NONE
:lua vim.treesitter.start(1, 'c')

### Expected behavior

Correct syntax highlighting of the structure without errors.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

No (Vim does not have treesitter)

### Operating system/version

Ubuntu 22.04 (WSL), Ubuntu 20.04

### Terminal name/version

ST 0.9 + Tmux 3.2

### $TERM environment variable

screen-256color

### Installation

Appimage

**Comment by lucario387** [comment]
Confirmed as well, #23606 was not backported

**Comment by clason** [comment]
It was, but not completely (mea culpa). I'll remove the offending query in `release-0.9` (which you can do manually as well, just place the new `highlights.scm` in `~/.config/nvim/queries/c/`.

**Comment by zeertzjq** [comment]
Fixed by #28859
