### ISSUE TITLE
lsp: add support for `general.positionEncodings`

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#23865]
Neovim's handling of encodings is currently based on the clangd off-spec extension. Once clangd upgrades to the position encoding negotiation supported in LSP 3.17, Neovim should follow suit. I think this would mean the params passed to `initialize` would advertise `capabilities.general.positionEncodings = { "utf-8", "utf-16", "utf-32" }`, and then changing the uses of `offset_encoding` to instead refer to the encoding chosen by the server.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-422+g68e2d7229

### Language server name/version

Neovim client

**Comment by clason** [comment]
The issue tracker is not for questions; please ask them on Matrix (https://matrix.to/#/#neovim-dev:matrix.org).

**Comment by clason** [comment]
Closed by #23871
