### ISSUE TITLE
get Nvim version string

### ISSUE THREAD

**Issue by ObserverOfTime** [neovim/neovim#23863]
### Problem

`vim.version()` returns version information as a table but it's incomplete and can't easily be converted to a string.

### Expected behavior

`tostring(vim.version())` should return a string that's the same as or similar to
`vim.split(vim.fn.execute('version'), '\n')[3]:sub(6)` (e.g. `v0.10.0-dev-424+g2bdef6dd2a`).

**Comment by treatybreaker** [comment]
When you mention `build` field, do you mean the commit hash, @justinmk?

**Comment by treatybreaker** [comment]
Running some tests now, I'll get a draft open once they pass.
