### ISSUE TITLE
attempt to get length of local 'prev_line' (a nil value)

### ISSUE THREAD

**Issue by shan-weiqiang** [neovim/neovim#23860]
### Problem

![image](https://github.com/neovim/neovim/assets/43443481/28a5dffa-cf13-4418-9bc0-5c44e95ca548)
from now and then when i attempt to edit files, this error pop up, not a clue why this happening

### Steps to reproduce

just edit a file

### Expected behavior

no error

### Neovim version (nvim -v)

nvim v0.9.0

### Vim (not Nvim) behaves the same?

no idea

### Operating system/version

ubuntu 18.04

### Terminal name/version

windows terminal(ssh)

### $TERM environment variable

256color

### Installation

appimage

**Comment by clason** [comment]
Sorry, that's extremely little to go on. Clearly something's happening in the LSP code, so this must require a language server, and be specific to some filetype.

Please open a new issue with the "LSP client bug" template **and fill it out completely**.

**Comment by clason** [comment]
(and test with 0.9.1, which is the latest release)
