### ISSUE TITLE
Pasting unicode characters from clipboard doesn't work

### ISSUE THREAD

**Issue by renstrom** [neovim/neovim#2386]
Basically pasting unicode characters from the clipboard produces some kind of escape sequence (or garbage?).

This is what it looks like in Neovim when I try to paste → for example:

![screen shot 2015-04-09 at 10 15 12](https://cloud.githubusercontent.com/assets/177685/7062829/57211c64-dea1-11e4-9462-5d0a72a4e51d.png)

And this is what regular Vim does:

![screen shot 2015-04-09 at 10 18 14](https://cloud.githubusercontent.com/assets/177685/7062869/c1ed0756-dea1-11e4-9415-7ab95f89e352.png)

This is on OS X (10.10.3). And I used `-u NONE`. You can pull up a table for unicode characters by pressing <kbd>ctrl</kbd><kbd>cmd</kbd><kbd>space</kbd>

**Comment by mhinz** [comment]
I can't reproduce with the latest neovim on neither 10.10.2 nor 10.10.3.

1) If you copy something to the clipboard, what does the output of `:reg` for `"*` and/or `"+` look like? 
2) I'm not sure if this can be an issue, but what's the output of `:echo &clipboard`?

**Comment by renstrom** [comment]
I guess I forgot to mention that I used <kbd>cmd</kbd><kbd>v</kbd> to paste or clicking via the "Emoji & Symbols" menu (see screenshot).

Here's part the output of `:reg`:

```
:reg
--- Registers ---
"-    <path>
"*   →
"+   →
".   â<92><80>kb<80>kb
```

So actually pasting with `"*P` or `"+P` works as intended.

![screen shot 2015-04-09 at 15 14 21](https://cloud.githubusercontent.com/assets/177685/7067391/3fc7ff22-decb-11e4-8ce1-47e060a1ef42.png)

**Comment by yagebu** [comment]
I can reproduce this with the latest homebrew-built neovim on OS X; on Arch Linux I can't reproduce it. This also happens when I type Unicode characters directly (using a non-US keyboard). Typing € or ß for example produces garbage.

**Comment by mhinz** [comment]
Hmm, pasting via `"+p` and just double-clicking an emoticon in that dialog inserts it in Vim just fine for me.

@renstrom How did you install neovim?

**Comment by renstrom** [comment]
>How did you install neovim?

I installed using Homebrew as described in [neovim/homebrew-neovim](https://github.com/neovim/homebrew-neovim).

>This also happens when I type Unicode characters directly (using a non-US keyboard). Typing € or ß for example produces garbage.

I'm also getting this, I'm using a non-US keyboard as well. Typing € prints â¬

**Comment by fwalch** [comment]
Just as an idea if you want to try, does it work with https://github.com/rogual/neovim.app? Or with a different terminal emulator?

**Comment by mhinz** [comment]
As far as I see it, 2 people can reproduce it only with neovim built using that homebrew recipe.

Bruteforce method:

`$ cd /tmp && git clone https://github.com/neovim/neovim.git && cd neovim && make && VIMRUNTIME=/tmp/neovim/runtime build/bin/nvim`

Does it work there?

**Comment by kopischke** [comment]
I cannot reproduce this on OS X 10.10.3 with *NVIM 0.0.0-alpha+201504082319 (compiled Apr  9 2015 16:29:30) Commit: bae1da3f74ec91b8a79c764aa0277d96c932b2aa*, using both a German locale and a German keyboard map. Both using the character picker and inserting extended characters via the usual `alt+<char>` mechanism work just fine in Neovim running in Terminal.app.

**Comment by yagebu** [comment]
I have found the culprit (at least in my setup). The locale was not fully set. Apparently the setting "Set locale variables automatically" doesn't do enough for neovim. It only sets `LC_CTYPE=UTF-8` in iTerm2 (same for a similar setting in Terminal.app). Setting `LC_ALL` to some sensible locale fixed it (More precisely `LC_MESSAGES` did the trick)

I'm not really sure which of the two is the right environment variable to consider, but as standard vim worked as we expected for both myself and @renstrom, it might make sense to consider both.

Thanks for all the quick help here!

**Comment by renstrom** [comment]
It seems you're correct. This is the locale I had before.

```bash
$ locale
LANG="en_US"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

To get stuff running I had to change `LANG`:

```diff
-LANG="en_US"
+LANG="en_US.UTF-8"
 LC_COLLATE="en_US.UTF-8"
 LC_CTYPE="en_US.UTF-8"
 LC_MESSAGES="en_US.UTF-8"
 LC_MONETARY="en_US.UTF-8"
 LC_NUMERIC="en_US.UTF-8"
 LC_TIME="en_US.UTF-8"
 LC_ALL="en_US.UTF-8"
```

**Comment by kopischke** [comment]
@yagebu 

>  (same for a similar setting in Terminal.app)

Nitpick: Terminal.app seems to do the right thing in non-English locales. My `locale` output confirms the diagnosis, BTW:

```bash
LANG="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_ALL=
```

**Comment by renstrom** [comment]
I guess a takeaway from this is that currently Neovim and Vim differ in how they handle locale settings.

**Comment by yagebu** [comment]
@kopischke: after some testing it seems Terminal.app does the right thing if and only if it can set all locale variables to the same locale. If region and language (in OS X prefs) are set to different things, instead of setting the locale accordingly, it just doesn't set it (except for `LC_CTYPE`). The behaviour of iTerm seems to be identical...

**Comment by kopischke** [comment]
@yagebu yikes, that sucks, I’d have expected OS X to be smarter about that. Good research!

**Comment by Pyrohh** [comment]
This is the third issue I've seen related to LANG not being set to a UTF-8 locale, so perhaps it should be mentioned under "Troubleshooting" wiki section.

**Comment by renstrom** [comment]
@Pyrohh or changed to behave like Vim?

**Comment by Pyrohh** [comment]
@renstrom I initially thought that that Nvim should respect `LANG` if it's set, but I'm not so sure after reading http://pubs.opengroup.org/stage7tc1/ (section 8.2). It looks like `LC_ALL` should take precedence over `LANG`, which doesn't seem to be the case according to  https://github.com/neovim/neovim/issues/2386#issuecomment-91278430.

@splinterofchaos @mhinz what do you think?

**Comment by splinterofchaos** [comment]
I think you meant this page: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/locale.html

I know next to nothing about locals, but it does say of `LC_ALL`,

> If set to a non-empty string value, override the values of all the other internationalization variables.

I noted that `LC_ALL` is not set on my machine, but running various commands with `$ env LC_ALL=C <cmd>` does change the behaviour vs just having `LANG` set. 

>  It looks like LC_ALL should take precedence over LANG, which doesn't seem to be happening according to #2386 (comment).

:+1: 

@bfredl, I think this is your territory.

**Comment by Pyrohh** [comment]
> I think you meant this page: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/locale.html

I was referring to the general specification on environment variables, but that's informative as well.

**Comment by bfredl** [comment]
Looking at the docs it looks like the order of precendence should be `LC_ALL > LC_CTYPE > LANG` , and yes `LC_ALL=C` does break vim but doesn't break nvim. I thoght that the C library (or some other system library) was handling the interpretation of all these variables? (At least, every application handling all these itself sounds quite fragile and duplicated work)

**Comment by bfredl** [comment]
And `LC_CTYPE` seems also ignored by nvim, so it won't see a terminal setting a custom encoding, as noted above.

**Comment by yagebu** [comment]
I know practically nothing about the neovim codebase but from greping it seems that a lookup of the locale happens which might be responsible for this happens here (in libtermkey): https://github.com/neovim/libtermkey/blob/master/termkey.c#L392. There, the order in which they are checked is to quite off (and using `LC_MESSAGES` instead of `LC_CTYPE`): `LANG > LC_MESSAGES > LC_ALL` while it should be like in @bfredl's post above.

If that's the part of the code that's responsible, this looks like a bug in libtermkey to me.

**Comment by Pyrohh** [comment]
To have a clean slate, I'll open another issue.

**Comment by bfredl** [comment]
The glibc manual claims this is the POSIX way:
```
#include <locale.h>
#include <langinfo.h>
int main() {
    setlocale(LC_ALL, "");
    printf("%s\n",nl_langinfo(CODESET));
}
```
where `LC_ALL` means "take all environment variables into account" and not just `LC_ALL` . It seem to use the `LC_ALL > LC_CTYPE > LANG` order, at least.

**Comment by Pyrohh** [comment]
@bfredl could you repost your comment in the new issue?

**Comment by bfredl** [comment]
done!
