### ISSUE TITLE
Buffer formate timeout

### ISSUE THREAD

**Issue by MohitNishad** [neovim/neovim#23861]
### Problem

although neovim provide great features compared to vim. But i was requesting to make buffer formate timout to customizable. I have old laptop when i try to formate using prettier and null-ls its most of the time says null-ls timeout 'This is an automatic mechanism and controlled by Neovim' it would be helpful if you reply soon or later

### Expected behavior

this will help get rid of error like null-ls lsp timout

**Comment by clason** [comment]
`:h vim.lsp.buf.format()`:

>      • timeout_ms (integer|nil, default 1000): Time in
>         milliseconds to block for formatting requests. No effect
>         if async=true
