### ISSUE TITLE
Manually run OSC11 query

### ISSUE THREAD

**Issue by Baspar** [neovim/neovim#23870]
### Problem

`background` is currently determined at neovim start time, using a OSC11`?` query.
When changing background color/theme, it would be helpful to have a way to tell neovim to re-query the terminal for a background color.

Vim has a way to do so by executing `:call echoraw(&t_RB)` (Effectively printing the OSC11`?` query to the TTY)

### Expected behavior

Have a way to re-evaluate the background using OSC11`?`

**Comment by Baspar** [comment]
Nope, it keeps the `background` value unchanged

**Comment by gpanders** [comment]
> Nope, it keeps the `background` value unchanged

IIRC the OSC 11 response is only parsed on startup, so if the response is received later it will not update `'background'` automatically.

You would have to parse the response from the terminal yourself, or maybe we could update the code in `input.c` to always handle the OSC 11 response.

**Comment by justinmk** [comment]
> Or option 3 is to introduce a higher level abstraction (a function/option/autocommand) that handles the whole process of issuing OSC 11 -> reading the response -> updating `'background'` that could be triggered by a user at any time.

`TermResponse` was implemented https://github.com/neovim/neovim/issues/25856
