### ISSUE TITLE
Indent gdscript not found

### ISSUE THREAD

**Issue by Cris-lml007** [neovim/neovim#23876]
### Problem

I am programming in godot with your gdscript language, and I realized that I don't understand it nvim, If I force compatibility with python it works well for me but it causes problems with LSP, I was recently seeing some vim stuff and I found that if you have an indentation script for [gdscript](https://github.com/vim/vim/blob/47eec6716b8621fd43bac8ecc9c19089df26705e/runtime/indent/gdscript.vim), and this is not found in nvim 8, I tried to copy the script to the nvim directory but it gives me an error, why is this?

### Steps to reproduce

```
Se ha detectado un error al procesar /home/metallica/.config/nvim/init.vim[4]../home/metallica/.config/nvim/config/global.vim[33]../usr/share/nvim/runtime/syntax/syntax.
vim[43]..BufReadPost Auto-órdenes para "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:22: Error executing lua: /usr/share/nvim/runtime/filetype.lua:23: Vim(vimgrep):E683: Falta el nombre d
el archivo o el patrón no es válido
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:22: Error executing lua: /usr/share/nvim/runtime/filetype.lua:23: Vim(vimgrep):E683: Falta el nombre d
el archivo o el patrón no es válido
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>

```

### Expected behavior

I wish I could add this vim script to neovim for indentation support to gdscript, or how I could get the same result?

### Neovim version (nvim -v)

NVIM v0.8.0-1210-gd367ed9b2

### Vim (not Nvim) behaves the same?

VIM - Vi IMproved 9.0

### Operating system/version

Kali linux

### Terminal name/version

Terminator

### $TERM environment variable

xterm-256color

### Installation

repo

**Comment by zeertzjq** [comment]
Vim9 script is not supported.

**Comment by Cris-lml007** [comment]
how can I get the same result?

**Comment by clason** [comment]
Port the indent file to vimscript and make a PR.
