### ISSUE TITLE
Homebrew build should be in Optimized mode

### ISSUE THREAD

**Issue by lazywei** [neovim/neovim#2387]
Please ref to: https://github.com/neovim/neovim/issues/2219#issuecomment-91152775 and https://github.com/neovim/neovim/issues/2219#issuecomment-91155782

Currently homebrew version doesn't build neovim in optimized version, which causes a little confusion.
I'm wondering should we build the neovim in optimized mode in homebrew formula?

Thanks.

**Comment by demonking** [comment]
Hello @lazywei  you are wrong here ;) 
Try it here https://github.com/neovim/homebrew-neovim

**Comment by lazywei** [comment]
@demonking plz check https://github.com/neovim/homebrew-neovim/blob/master/Formula/neovim.rb#L55

**Comment by fwalch** [comment]
I guess @demonking meant you should report the issue over at the `homebrew-neovim` repository where the formula is hosted.

I can't really reproduce your problem, though.. Homebrew does in fact compile in optimized mode (`RelWithDebInfo` just has additional assertions), as you can also see from the compiler flags shown in `--version`. Even when compiled in debug mode, I have no performance problems with airline (using your [Gist](https://gist.github.com/lazywei/2cbcb9afb9dd49b77c7d)):

```
# Release
328.689  000.004: --- NVIM STARTED ---

# RelWithDebInfo
374.223  000.005: --- NVIM STARTED ---

# Debug
470.547  000.006: --- NVIM STARTED ---
```

**Comment by Pyrohh** [comment]
> I guess @demonking meant you should report the issue over at the homebrew-neovim repository where the formula is hosted.

Indeed, I don't see this is relevant to Neovim. I'll close this, but feel free to reopen if I've missed something.
