### ISSUE TITLE
Enhance jobsend() ?  send EOF to the stdin of the process.

### ISSUE THREAD

**Issue by syswow** [neovim/neovim#2388]
Hi, 
If we run `clang -cc1 -fsyntax-only -code-completion-at -:1:1 ` in terminal, to end input , we have to press `ctrl+d` to send EOF to clang.

let's try to use `jobstart()`, `jobsend()`.
short example:
```viml
function s:JobHandler(job_id, data, event)
  if a:event == 'stdout'
    let str = 'stdout: '.join(a:data)
  elseif a:event == 'stderr'
    let str = 'stderr: '.join(a:data)
  else
    let str = 'exited'
  endif
  call append(line('$'), str)
endfunction
let s:callbacks = {
\ 'on_stdout': function('s:JobHandler'),
\ 'on_stderr': function('s:JobHandler'),
\ 'on_exit': function('s:JobHandler')
\ }
let src = ["#include <", "\<cr>"]
let argv = ['clang', '-cc1', '-fsyntax-only', '-code-completion-at', '-:1:1']
let id = jobstart(argv, s:callbacks)
let sendret = jobsend(id, src)
call append(line('$'), "jobsend() ret: ".sendret)
```
output:
```

jobsend() ret:  1
```
 it seems jobsend() cannot send EOF to clang, clang still wait more data from itself stdin.

Do I understand this correctly?

**Comment by Shougo** [comment]
You cannot use `"\<C-d>"`?
You may have to use pty though.

**Comment by bfredl** [comment]
You need jobclose(jobid) for this
Den 9 apr 2015 12:05 skrev "syswow" <notifications@github.com>:

**Comment by syswow** [comment]
@Shougo  I have try `"\<C-d>"`, it doesn't work. I will try pty late.
@bfredl  jobclose(jobid) just close job, it doesn't end the input of stdin.

**Comment by syswow** [comment]
@bfredl  @Shougo  jobclose(id, 'stdin') do it. thanks

**Comment by bfredl** [comment]
@syswow you mean you tried jobclose after jobsend and it didnt work?
Den 9 apr 2015 12:16 skrev "syswow" <notifications@github.com>:

**Comment by bfredl** [comment]
Sorry didnt see your last message
Den 9 apr 2015 12:28 skrev "Björn Linse" <bjorn.linse@gmail.com>:

**Comment by syswow** [comment]
@bfredl nevermind, thankyou.
