### ISSUE TITLE
`vim.treesitter.language.register` a nil value

### ISSUE THREAD

**Issue by galou** [neovim/neovim#23895]
### Problem

I used to have `xml` filetype using `html` parser with `vim.treesitter.language.register('html', 'xml')` but this doesn't work anymore.

### Steps to reproduce

Configure a specific parser for a filetype with `:lua vim.treesitter.language.register('html', 'xml')`, which used to work.

### Expected behavior

A deprecation notice should be given.

### Neovim version (nvim -v)

NVIM v0.9.0-dev

### Vim (not Nvim) behaves the same?

Not available in Vim

### Operating system/version

Ubuntu 20.04

### Terminal name/version

kitty 0.19.3

### $TERM environment variable

xterm-kitty

### Installation

PPA

**Comment by galou** [comment]
The [official documentation](https://neovim.io/doc/user/treesitter.html#lua-treesitter-language) still mentions `vim.treesitter.language.register`.

**Comment by mon1237** [comment]
Code sent me

**Comment by galou** [comment]
False alarm, the function was not deprecated but on the opposite, not existing yet in 0.9.0. Solved by upgrading to 0.10.0-dev.
