### ISSUE TITLE
matchparen error on rename across multiple files

### ISSUE THREAD

**Issue by seanparsons** [neovim/neovim#23890]
### Problem

If I rename a function that is used in other files, I see the other files get opened and they are updated, but the one I performed the operation in doesn't change and I see this error:
![image](https://github.com/neovim/neovim/assets/217400/47cddcc5-2c03-49f8-96f0-d079b4d69aa6)

### Steps to reproduce using "nvim -u minimal_init.lua"

I wrestled with the `minimal_init.lua` file for an hour to little success in getting the `typescript-language-server` to play ball.

The code I experienced this issue on is however open source at https://github.com/concrete-utopia/utopia

All I did was:
- Open the file `editor/src/core/model/element-metadata-utils.ts`.
- Attempt to rename `getChildrenReordered` (currently at line 628).

### Expected behavior

No errors and the file I'm in should result in the appropriate rename.

### Neovim version (nvim -v)

NVIM v0.9.1

### Language server name/version

typescript-language-server 2.1.0

### Operating system/version

NixOS 23.05

### Log file

https://gist.github.com/seanparsons/6c2c95e7c3555a3728722d4c28cd4b2c

**Comment by justinmk** [comment]
`s:Highlight_Matching_Pair()` is part of the builtin matchparen plugin: https://github.com/neovim/neovim/blob/36fd2fcaae757e8ac64c8ff7a66e4f480a075dcf/runtime/plugin/matchparen.vim#L22

If you disable matchparen does the issue still occur? Put this in your config and restart nvim:

    :let loaded_matchparen = 1

**Comment by t0muxx** [comment]
i'll work on this

**Comment by t0muxx** [comment]
I tried to reproduce this but the error didn't happened.
@seanparsons can you confirm me that you used ` lua vim.lsp.buf.rename()` to rename the function ?
