### ISSUE TITLE
Un-deprecate `'gdefault'`

### ISSUE THREAD

**Issue by famiu** [neovim/neovim#23902]
### Problem

`'gdefault'` has been deprecated a long time ago in #7795 and has stayed deprecated since then. The reasoning stated was that it breaks plugins, which I'm assuming is due to the fact that it changes the behavior of `substitute()`. However, I would argue that if a plugin does not handle options correctly, it is the fault of the plugin. And even if we were to assume that `'gdefault'` was making plugins break, simply deprecating it and keeping it deprecated for 6 years isn't really going to fix that because the option is still there and people are still using it, so plugins are having to deal with it anyway.

### Expected behavior

I suggest one of the following:

1. Un-deprecate `'gdefault'` since keeping it deprecated for so long doesn't really serve much of a purpose. And with the introduction of `vim.regex` and the possibility of extending it for substitution, we shouldn't need to worry about plugins breaking due to it.

2. Fully commit to the previous decision and remove `'gdefault'`. It's been deprecated for 6 years. If it truly does break plugins then there's no point in keeping it around. It's better to remove it entirely than to keep it in the limbo state that it's been in for so long.

Needless to say I would much prefer the former rather than the latter. But I am also admittedly not the most knowledgable when it comes to this part of Neovim, so I'll put my faith in the core team and trust them to make the right decision regarding this.

**Comment by lewis6991** [comment]
I vote to remove.

**Comment by famiu** [comment]
> I vote to remove.

I am curious about your reasoning for preferring to remove it rather than keep it.

**Comment by lewis6991** [comment]
It's pure bloat.

**Comment by famiu** [comment]
> It's pure bloat.

I suppose you're right in the sense that having a full option just to change a single substitute flag is bloat. Once more option types are added (specifically dict options), would you be open to an option that allows setting multiple default substitution flags or configuring substitution in general?

**Comment by lewis6991** [comment]
I don't know, maybe. We have way too many options for random things. A more general solution is obviously more preferable.

For me I would just use an abrrev or keymap or user command.

**Comment by lewis6991** [comment]
Another data point is `/g` makes `inccommand` blow up my CPU so I only insert it when I know my regex's are correct.

**Comment by famiu** [comment]
> I don't know, maybe. We have way too many options for random things.

Fully agree with you on that. I think dict options would solve a lot of those problems + more.

> A more general solution is obviously more preferable.

I'm down for a `'subflags'` option (name chosen tentatively) that completely manages the behavior of `:substitute` and co., personally.

> For me I would just use an abrrev or keymap or user command.

This is purely a personal opinion and you might disagree, but I think that `g` would be the saner default for substitute. I do not see the usecase for only replacing the first occurence of a match when I'm trying to do search/replace. I do not know if the majority of people would agree with me on that, but if they do, then I think that having saner defaults (or at least making it easier to have sane defaults) should be prioritized.

> I would also prefer that :s remains option independent and we simply provide ways to augment it on top.

I can understand your point here. It certainly makes sense for a command like `:substitute` to not change its behavior based on the value of an option. But I would also like to state though that pretty much every other editor has a search/replace behavior similar to `gdefault` in (Neo)vim. I am not saying that Neovim has to be like other editors, just saying that making it easier for people coming over from other editors to migrate to Neovim should certainly be a priority, especially when the way to do it is simple and relatively easy to maintain.

I am not advocating for changing the default behavior of `:s`, obviously, that would be irrational as it would break pretty much every workflow in existence. However, I am wondering what sort of compromise we could reach that preserves old behavior while also giving us the ability to easily have a behavior that's more friendly and intuitive to new users.

**Comment by famiu** [comment]
> Another data point is `/g` makes `inccommand` blow up my CPU so I only insert it when I know my regex is correct.

I don't fully understand how that's an argument against something like `'gdefault'`, as it would be opt-in.

**Comment by lewis6991** [comment]
I probably use `/g` 60% of the time. A lot of the time I like to use general regex to just match one instance on a line and change.

**Comment by famiu** [comment]
> I probably use `/g` 60% of the time. A lot of the time I like to use general regex to just match one instance on a line and change.

Well, I'd like to ask then, in the latter 40% of the cases, how often is it that the single instance you intend to match is also the only instance of that pattern?

**Comment by lewis6991** [comment]
> > Another data point is `/g` makes `inccommand` blow up my CPU so I only insert it when I know my regex is correct.
> 
> I don't fully understand how that's an argument against something like `'gdefault'`, as it would be opt-in.

It's just a data point for why someone wouldn't want to opt in.

**Comment by lewis6991** [comment]
> > I probably use `/g` 60% of the time. A lot of the time I like to use general regex to just match one instance on a line and change.
> 
> Well, I'd like to ask then, in the latter 40% of the cases, how often is it that the single instance you intend to match is also the only instance of that pattern in that line?

I have no idea, but in these cases I explicitly omit `/g` to avoid accidentally over substituting. I only use `/g` for variable substitution which admittedly I'm using less now in favour of LSP.

In fact I probably use `cgn` `.` more than `:s`.

**Comment by justinmk** [comment]
Well-reasoned proposal. But still seems controversial either way, so hard to argue that anything should change, since the gain is very small in all cases?

**Comment by ii14** [comment]
I use it. We can just follow what vim is doing, but in my opinion it should be kept as it is.

1. If you write vim script, you probably want to target both vim and nvim, so you have to handle it either way.
2. Vim9script fixed the problem with options affecting the behavior of scripts by simply ignoring those options. Same thing could be done for lua by providing an alternative to `substitute()` that has a consistent behavior, just like in `vim.regex`.
3. The actual implementation is literally a single line of code in C, so it doesn't make anything any more complicated.

**Comment by famiu** [comment]
> * If you write vim script, you probably want to target both vim and nvim, so you have to handle it either way.

By "kept as it is", do you mean un-deprecating it?

**Comment by famiu** [comment]
> Well-reasoned proposal. But still seems controversial either way, so hard to argue that anything should change, since the gain is very small in all cases?

I think the gain in either un-deprecating or removing it is that we make our intent clear rather than keeping it in a state of limbo. Do we want to keep it (it's literally a single line of C as ii14 said) or do we want to remove it?

**Comment by ii14** [comment]
More in the sense that not doing anything and letting vim decide what to do about it is also an option. It's deprecated in vim, but it's still there. (I was wrong on matrix about it being deprecated only in nvim.) And if I had to guess, I think it's probably unlikely that Bram is actually going to remove it. But if the decision has to be made right now then I'd prefer to undeprecate it or at least have some decent alternative to do the same thing.

**Comment by famiu** [comment]
Following Vim is _fine_ but I also don't understand the point of keeping it deprecated if we're not gonna remove it. If we do eventually wanna remove it, we can just re-deprecate it.

**Comment by clason** [comment]
Well, the point in this case _is_ "following vim" -- which means that _we_ are not doing anything, or losing sleep over it. If Vim decides to keep it deprecated, that's exactly what we'll do, until Vim decides to do something else.

**Comment by justinmk** [comment]
> I also don't understand the point of keeping it deprecated if we're not gonna remove it.

Er, that's a misunderstanding. We can permanently deprecate things, that doesn't mean they will always be removed. 

Closing this since it mostly seems to be a misunderstanding. "Deprecated" doesn't always mean it will be removed, rather in some cases it's just discouraged and no longer supported in the sense of enhancements or non-trivial bugfixes.
