### ISSUE TITLE
deprecate tbl_xx, list_xx functions

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#23913]
### Problem

We have `vim.iter` now, and this is where iterable features should live.

### Expected behavior

```
vim.tbl_extend() => Iter:extend()
vim.tbl_deep_extend()  // why is this a separate function?
vim.tbl_flatten() => Iter:flatten()
vim.tbl_map()
vim.tbl_filter()
vim.tbl_isempty() => Iter:empty()
vim.tbl_count() => Iter:count()
vim.tbl_contains() => Iter:any()
```

Functions that are truly table-specific can continue to live on `vim.tbl_xx`, these are: 

```
vim.tbl_get()
vim.tbl_isarray()
vim.tbl_islist()
vim.tbl_keys()
vim.tbl_add_reverse_lookup()  // ??
vim.tbl_values()  // probably could be in vim.iter ?
```

**Comment by clason** [comment]
I'm not sure `extend` makes sense for an abstract iterable; that's a very (Lua) table specific function. (Under the hood this is one function with a flag `true` or `false`, so these could be combined -- but that would be quite breaking since the signature would have to change.)

**Comment by clason** [comment]
In any case, very much in favor of such a clean-up. However, I would suggest the following approach:

* Anything that reasonably applies to **generic** iterators should go to `vim.iter` (which has special-case implementations for list-like(!) tables; I suspect that the overhead for map-like tables would be negligible -- but that should be tested, of course): `isempty`, `contains`, `count`, `spairs()` (as a flag to `vim.iter(table)`?), and all `list_*` methods.

* Anything that is specific for general (not purely list-like) tables should go to `vim.table` -- that especially concerns functions that _modify_ (increase) the table: `isarray`, `[deep_]extend`, `[deep_]copy` (clone), `keys`, `values`, `add_reverse_lookup`, `get` (possibly implemented using iterators to at least remove _code_ duplication). There's also efficient `insert` and `remove` functions we could add (@lewis6991). 
This module could also be extended with LuaJIT specific additions so users could just do `vim.table.pack` without having to worry about PUC Lua (or even extended with the whole `table` module so you can just do `local table = vim.table` and not worry about it?)

* Anything that is vim specific should go to `vim` -- that's basically `vim.empty_dict()` (and arguably `vim.ringbuf`).

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/24572 has a more completed plan. Also added your notes there.

> On a related note, there's a bunch of string functions that may merit including in a -- to be expanded `vim.string` module

0.10 has `vim.text`, though we also discussed (and rejected?) extending Lua's `string` I believe, but I can't find that issue/PR.
