### ISSUE TITLE
Native ins-completions seem sluggish

### ISSUE THREAD

**Issue by dhruvasagar** [neovim/neovim#2392]
Hi guys,

I have been playing around with neovim recently and I am in love with :terminal! However for some reason I notice that the native ins-completions seem significantly slower in neovim than vim. Now I do have a lot of buffers open so that makes things a bit hard I am sure, however the same completions (<C-n> and <C-X><C-L>) much much slower in neovim as compared to vim.

I think this needs a closer look. Let me know how I could be of help in diagnosing this issue.

Edit: Note, I use vim sessions per directory and load them on launch, with my plugin https://github.com/dhruvasagar/vim-prosession, it works fairly well (at least for me), and that's what allows me to test this scenario pretty accurately in both vim and neovim, since I can launch neovim from that directory and it just loads all the buffers etc.

**Comment by Shougo** [comment]
Please check your neovim is already optimized.

https://github.com/neovim/neovim/issues/2219

**Comment by dhruvasagar** [comment]
@Shougo the problems aren't in starting neovim, the problems are that the completions are taking much longer in neovim. When I hit `<C-n>` or `<C-x><C-l>` it's much slower in neovim than in vim.

**Comment by Shougo** [comment]
Yes.  But if the neovim is not optimized, it may be slower.

**Comment by dhruvasagar** [comment]
@Shougo I understand, but startup time isn't my problem so #2219 doesn't help me...

**Comment by Shougo** [comment]
Please create minimal .vimrc and upload reproduce ways.
I will test it.

**Comment by dhruvasagar** [comment]
@Shougo you need a large number of loaded buffers to replicate the issue. Once you have a large number of buffers open, he completions take a lot of time in neovim as compared to vim. I could try removing all my plugins and try the same I suppose but I doubt that is the problem since I am talking about the native completions here and I am not using any autocomplete plugins or anything.

**Comment by Shougo** [comment]
Please create reproduce ways.  You can create it(the large number of loaded buffers) by using neovim sources.

**Comment by justinmk** [comment]
@dhruvasagar is this still an issue?

**Comment by dhruvasagar** [comment]
@justinmk I haven't been using neovim, so haven't tested. You can close the issue for now, i'll (or someone else) reopen if I feel it is an issue.

**Comment by justinmk** [comment]
@dhruvasagar Thanks
