### ISSUE TITLE
Highlight NONE not working properly

### ISSUE THREAD

**Issue by mtglsk** [neovim/neovim#2394]
```
colorscheme default
hi TabLineFill NONE
hi link TabLineFill TabLine
```

Screenshot:

![bug](https://cloud.githubusercontent.com/assets/10101321/7080296/2a53ed9e-df30-11e4-872b-cad2b156d39e.png)

**Comment by mhinz** [comment]
Confirmed. I'm looking into it.

**Comment by justinmk** [comment]
Seems to be fixed.
