### ISSUE TITLE
Commands  not working

### ISSUE THREAD

**Issue by Sp0-0n** [neovim/neovim#23959]
### Problem

When I enter :Copilot setup or :Tutor I get a message,
E492 not an editor command

### Steps to reproduce

I installed nvim today, then cloned the github copilot, then installed the NVchad plugin. I can't setup my copilot account or learn the hotkeys

### Expected behavior

It should work

### Neovim version (nvim -v)

NVIM v0.9.0

### Vim (not Nvim) behaves the same?

i dont have vim

### Operating system/version

Ubuntu 20.04

### Terminal name/version

alacritty

### $TERM environment variable

xcolorterm=truecolor

### Installation

i used snap

**Comment by clason** [comment]
You need to actually install these plugins (by adding them to runtimepath, and possibly calling setup). But usage questions are not appropriate here; ask on Matrix.
