### ISSUE TITLE
built-in plugin store

### ISSUE THREAD

**Issue by zhangfuwen** [neovim/neovim#23955]
### Problem

people use vim with plugins and install plugins in a new environment is too much work and takes time.

why aren't we publish neovim with a built in plugin store.

### Expected behavior

how to do this? 

we can achieve this by just install a plugin list and plugin manager(bundle for example). we don't need a central server for serving plugin query and download. 

vcpkg manages C++ packages in just a similar way.

**Comment by clason** [comment]
No.
