### ISSUE TITLE
Scroll issue when scrolloff is half the height of window and splitkeep='screen'

### ISSUE THREAD

**Issue by MunifTanjim** [neovim/neovim#23956]
### Problem

- https://github.com/kevinhwang91/nvim-bqf/issues/112#issuecomment-1582145219

### Steps to reproduce

**minimal_init.lua**

```lua
local function dir(root)
  local f = debug.getinfo(1, "S").source:sub(2)
  return vim.fn.fnamemodify(f, ":p:h") .. "/" .. (root or "")
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.opt.runtimepath:append(dir())
vim.opt.packpath = { dir(".repro/site") }
vim.env.XDG_CONFIG_HOME = dir(".repro/config")
vim.env.XDG_DATA_HOME = dir(".repro/data")
vim.env.XDG_STATE_HOME = dir(".repro/state")
vim.env.XDG_CACHE_HOME = dir(".repro/cache")

vim.o.number = true
vim.o.scrolloff = 5
vim.o.splitbelow = true
vim.o.splitkeep = "screen"

vim.cmd("vimgrep v %")

local o_winid = vim.api.nvim_get_current_win()

vim.cmd("copen")

local qf_winid = vim.api.nvim_get_current_win()

vim.api.nvim_create_autocmd("CursorMoved", {
  callback = function()
    vim.cmd("noa call nvim_set_current_win(" .. o_winid .. ")")
    vim.cmd("noa call nvim_set_current_win(" .. qf_winid .. ")")
  end,
})
```

- `nvim -u NORC -u minimal_init.lua minimal_init.lua`
- Try to move cursor down in the quickfix window

### Expected behavior

Should be able to move cursor up and down normally.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1768+gc48f94d1f-Homebrew

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

macOS 13.4

### Terminal name/version

Kitty

### $TERM environment variable

tmux-256color

### Installation

homebrew

**Comment by luukvbaal** [comment]
This was fixed in https://github.com/neovim/neovim/pull/24811
