### ISSUE TITLE
Errors when loading a session with an open terminal

### ISSUE THREAD

**Issue by luizcalliari** [neovim/neovim#23969]
### Problem

I´ve saved a session with a terminal (`:term` or `:terminal`) and an existing file.
Many errors were shown when I tried to load the saved session, and the terminal session was lost.
With Vim, it's working.

> "README.md" 4L, 104B
Error detected while processing /home/luizfilho/t1.vim:
line   56:
E518: Unknown option: balloonexpr=
line   75:
E518: Unknown option: cryptmethod=
line  140:
E518: Unknown option: noshortname
line  162:
E518: Unknown option: termwinkey=
line  163:
E518: Unknown option: termwinscroll=10000
line  164:
E518: Unknown option: termwinsize=
line  173:
E518: Unknown option: wincolor=
line  190:
E518: Unknown option: balloonexpr=
line  209:
E518: Unknown option: cryptmethod=
line  274:
E518: Unknown option: noshortname
line  296:
E518: Unknown option: termwinkey=
line  297:
E518: Unknown option: termwinscroll=10000
line  298:
E518: Unknown option: termwinsize=
line  307:
E518: Unknown option: wincolor=
Press ENTER or type command to continue

### Steps to reproduce

1. Open an existing file:
`nvim some_file_here`
2. Open a terminal
`:term` or `:terminal`
3. Save the session
`:mksession path/filename.vim`
4. Close nvim
`:qa!`
5. Open an empty nvim
`nvim`
6. Load the session
`:source path/filename.vim`

### Expected behavior

The file and the terminal appear on the screen like the moment when the session was created.
The terminal doesn't need to have any preview information/command printed.

### Neovim version (nvim -v)

NVIM v0.9.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 22.04 (using WSL)

### Terminal name/version

Powershell 

### $TERM environment variable

xterm-256color: command not found

### Installation

appimage

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by zeertzjq** [comment]
It seems that you saved the session with Vim and opened it with Nvim.

**Comment by luizcalliari** [comment]
> It seems that you saved the session with Vim and opened it with Nvim.
You´re right!! My mistake!!
