### ISSUE TITLE
JobActivity autocommand missing

### ISSUE THREAD

**Issue by strokirk** [neovim/neovim#2396]
Using `NVIM 0.0.0-alpha (compiled Apr 10 2015 00:50:14)` from the Unstable PPA.

`JobActivity` doesn't seem to have any help information. `:helpgrep JobActivity` references it in two places, but the actual tag is nowhere to be found.

Also, the `JobActivity` autocommand itself seems to be missing. Running `neovim -u NONE -c ':au JobActivity` reproduces the error.

I use the [Neomake](https://github.com/benekastah/neomake) plugin, which relies on `JobActivity`. The line in the plugin calling the autocommand is this: 

```vim
autocmd JobActivity neomake* call neomake#MakeHandler()
```

**Comment by strokirk** [comment]
It seems this was removed in commit 6e7757a by @tarruda.

**Comment by Pyrohh** [comment]
There's also an entry in `{fileio,terminal}.c`

**Comment by Pyrohh** [comment]
And assuming you haven't done so already, try updating your plugins. Neomake should work fine due to this: https://github.com/benekastah/neomake/pull/75

**Comment by Pyrohh** [comment]
Closed by #2398
