### ISSUE TITLE
treesitter foldexpr slow when parser not available

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#23964]
### Problem

**Context**:
After setting foldexpr to treesitter foldexpr, I noticed that [undotree plugin](https://github.com/mbbill/undotree) became much slower. Specifically, a `setline()` loop and `append()` for drawing the tree got slower.

**The problem**:
`vim.treesitter.foldexpr()` tries creating a parser (`vim.treesitter._create_parser()`) if the buffer doesn't have a parser yet. So if there is no parser file for the language of the buffer, it will try creating a parser whenever it's invoked. Normally, this is not a big issue because it doesn't take much time. However, foldexpr can be called very frequently, e.g. in a `setline()` loop, so this can incur significant slowdown (for my case, it takes about 1ms per line set by `setline()`). The following minimized example demonstrates the problem.
```
" NOTE: assuming that there is no parser for markdown
nvim --clean --cmd 'set foldmethod=expr foldexpr=v:lua.vim.treesitter.foldexpr()' README.md
:let start = reltime() | call append(0, range(10000)) | echom reltimestr(reltime(start))
```
The test takes about 280ms on my machine. Without foldexpr, it only takes about 5ms.

There are several approaches for solution.
* Don't let foldexpr option leak into windows that contain a buffer for which I have not explicitly requested foldexpr-folding. Several options for this:
    * Revamp window-local option from ground up so that it behaves better.
    * Make foldexpr buffer-local option.
    * Emulate the above options with some script.
* Make fold computation more lazy. It doesn't need to be triggered every time a line is set.
* Make `vim.treesitter.get_parser` fail quickly, avoiding futile attempts to create a parser. For example, remember that `_create_parser` has failed. But this can be problematic since parsers can be installed later.
* ([FastFold](https://github.com/Konfekt/FastFold/) doesn't help with this problem.)

### Steps to reproduce

see above

### Expected behavior

see above

### Neovim version (nvim -v)

0.10-dev 7c661207c

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

tmux-256color

### Installation

built from the repository

**Comment by lewis6991** [comment]
You should only set `foldexpr` when there is a parser available.

I currently have this in my config.

```lua

  local function enable_foldexpr()
    vim.opt_local.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
    vim.opt_local.foldmethod = 'expr'
    vim.cmd.normal'zx'
  end

  api.nvim_create_autocmd('FileType', {
    callback = function()
      if not pcall(vim.treesitter.start) then
        return
      end

      enable_foldexpr()
      enable_commenstrings()
    end
  })
```

I'm not really sure if this is worth fixing.

**Comment by lewis6991** [comment]
> window-local options are copied to a new `:split`ed window

Not if you use `setlocal` or `vim.opt_local`.

**Comment by tomtomjhj** [comment]
Oh I thought `vim.wo` was like `setlocal`, and this made me believe that window-local options are always copied to split window. Using `vim.opt_local` as you suggested seems to be the correct solution. 

There are still some edge cases, e.g. setlocal-ing those options and then  `:edit`-ing a buffer without a parser in the same window, and fixing it would require revamping window-local stuff. But the current state seems to be good enough for my use cases.

**Comment by clason** [comment]
> Oh I thought vim.wo was like setlocal

No, that is definitely not the case, and the documentation should (now) make that clear! (It's the one thing where the `vim.{,g,b,w}o` accessors still have a gap.)

**Comment by adrian5** [comment]
>  ```lua
>   api.nvim_create_autocmd('FileType', {
>     callback = function()
>       if not pcall(vim.treesitter.start) then
>         return
>       end
>     (…)
>   })

Is this supposed to work when `:source`ing session files? Trying it here it seems the autocmd takes the early return in that case, unlike when `:edit`ing the file.
