### ISSUE TITLE
delete buffer do not trigger tabline redraw

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#23989]
### Problem

In SpaceVim, I have a key binding `SPC b c` to clear other written buffer, after type this key binding, the tabline does not redraw.

the key binding is mapped to this function:

```
function! SpaceVim#mapping#clear_saved_buffers() abort
  call s:BUFFER.filter_do(
        \ {
          \ 'expr' : [
            \ 'buflisted(v:val)',
            \ 'index(tabpagebuflist(), v:val) == -1',
            \ 'getbufvar(v:val, "&mod") == 0',
            \ ],
            \ 'do' : 'noautocmd bd %d'
            \ }
            \ )
endfunction
```

maybe this is because I use `noautocmd` to run `bd` command.

### Steps to reproduce

vim foo fzz bff

type `SPC b c`

### Expected behavior

the tabline should be updated, and only current buffer is listed.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Win11

### Terminal name/version

neovim-qt

### $TERM environment variable

empty

### Installation

scoop repo

**Comment by justinmk** [comment]
> 0.9.1

Try latest master (always worth checking, for display issues)

**Comment by dtcyganok** [comment]
I can confirm this bug in v0.9.1.
To reproduce it just call `bdelete` for not current buffer

Actually this bug appeared since v0.7.0, if i remember it right

**Comment by glepnir** [comment]
emm could you provide a minimal and detailed reproduce step.  i just test set talbine show buffers list and I see same behavior in vim.

**Comment by dtcyganok** [comment]
It seems a bit tricky, but I'll try to describe it simple.

**Steps to reproduce**

1. Create the file `tabline.lua`:

```lua
function _G.render_tabline()
  local result = ''
  local current_buffer = vim.api.nvim_get_current_buf()
  for _, number in ipairs(vim.api.nvim_list_bufs()) do
    if vim.bo[number].buflisted == true then
      local highlight = number == current_buffer and '%#TabLineSel#' or '%#TabLine#'
      local path = vim.api.nvim_buf_get_name(number)
      result = result .. highlight .. ' ' .. path .. ' '
    end
  end
  result = result .. '%#TabLineFill#'
  return result
end

vim.opt.tabline = '%!v:lua._G.render_tabline()'
vim.opt.showtabline = 2
```

2. Create a couple of files:

`touch a.txt b.txt`

3. Run neovim:

`nvim --clen -u tabline.lua a.txt b.txt`

4. You can see the tabline is displaying the two aforementioned files
5. Delete one of the buffers (not current buffer):
`:bdelete b.txt`
6. You can see the tabline is still displaying the two buffers

**Comment by zeertzjq** [comment]
I don't think this is a bug. There is no reason for deleting a buffer to trigger tabline redraw.

**Comment by dtcyganok** [comment]
@zeertzjq, that's surprising. So why is there tabline redraw trigger after deleting a current buffer? And what are the reasons to redraw tabline?

**Comment by zeertzjq** [comment]
Deleting the current buffer changes the current buffer. Deleting another buffer does not.

**Comment by zeertzjq** [comment]
Deleting the current buffer requires redrawing a window. Deleting a hidden buffer does not.
