### ISSUE TITLE
Unable to build neovim - dependencies broken

### ISSUE THREAD

**Issue by j-xella** [neovim/neovim#23997]
### Problem

1. **Libvterm** dependency broken. The build tries to download libvterm 0.3.1, while the checksum for the archive is from libvterm 0.3.2 . I had to manually download libvterm 0.3.2 and rename it as 0.3.1 to work around this issue. Oh, and also the build tries to download libvterm from launchpad. It is my understanding this should have been fixed in #23493 .
2. Problem with **libuv** also:
  > -- Using src='https://github.com/libuv/libuv/archive/62c2374a8c005ce9e42088965f8f8af2532c177b.tar.gz'
-- verifying file...
       file='/...xxx.../neovim/.deps/build/downloads/libuv/62c2374a8c005ce9e42088965f8f8af2532c177b.tar.gz'
-- SHA256 hash of
    /...xxx.../neovim/.deps/build/downloads/libuv/62c2374a8c005ce9e42088965f8f8af2532c177b.tar.gz
  does not match expected value
    expected: '458e34d5ef7f3c0394a2bfd8c39d757cb1553baa5959b9b4b45df63aa027a228'
      actual: 'c7e89137da65a1cb550ba96b892dfeeabea982bf33b9237bcf9bbcd90f2e70a1'

### Steps to reproduce

Building neovim from commit 551cc3a2a

### Expected behavior

The build just works

### Neovim version (nvim -v)

551cc3a2a

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux

### Terminal name/version

urxvt

### $TERM environment variable

urxvt

### Installation

build from repo

**Comment by clason** [comment]
Have you done `make distclean` before building?

**Comment by j-xella** [comment]
distclean helped, thank you. 

I have a clone of nvim master, and from time to time I do pull and then build. From now on I will distclean every time.

However, I was under impression that since it is the same branch, distclean does not have to be invoked often. After all, do the neovim developers do a full rebuild every time a new commit is pulled?

Could you suggest any "rule of thumb" recommendations how often distclean should be invoked? Thank you in advance.

**Comment by clason** [comment]
Every time something in the cmake files (or your cmake itself) changes, you should do a `make distclean`. And you should definitely do a `make distclean` if you see build errors **before opening an issue**.
