### ISSUE TITLE
tree-sitter higlighter

### ISSUE THREAD

**Issue by abdellatif-temsamani** [neovim/neovim#23993]
### Problem

![image](https://github.com/neovim/neovim/assets/69157582/0bec5c12-9fcc-4c40-a655-b7a38da082cb)

### Steps to reproduce

nvim [FILE]

### Expected behavior

to not highlight the code

### Neovim version (nvim -v)

v0.10.0-dev-503+gbde59e8147

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

AUR (neovim-git)

**Comment by clason** [comment]
This does not happen by default, so please check your config and your plugins.

**Comment by abdellatif-temsamani** [comment]
```lua
        highlight = {
            enable = true -- comment
        }
```

when i removed this from config it worked fine

**Comment by abdellatif-temsamani** [comment]
update: i had a problem in Parsers were not compiled properly
