### ISSUE TITLE
Dot subscripts ambiguity

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#240]
Consider the following expression: `1?d.g:v`. Depending on type of `d` it may be parsed as `(1)?((d).(g:v))` or `(1)?((d)['g']):(v)` (which is not). The problem is that I do not know any good way to parse this into a structure that may be resolved as concat or subscript at runtime. As `str.g:var` is very common and correct I cannot prefer the second variant. So now my parser is going to fail to recognize subscript if it is one character length and next character is a colon, but this in generally not correct like shown in the example. I cannot say how many plugins out there have this `[\w\d)"'\]}]\.[gbwtvals]:` pattern meaning `:` as a part of ternary operator, but it looks like the best of the worst.

**Comment by bfredl** [comment]
resolution: Neovim will use vim script with `scriptversion 1` unmodified, with whatever current `.` behavior. for more sane semantics, use lua.
