### ISSUE TITLE
`gv` uses incorrect region after called `nvim_buf_set_lines`

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#24007]
### Problem

with the following steps, `gv` only select the first line of previously selected region at '2.

### Steps to reproduce

* `seq 10 20 | nvim --clean -`
* `ggV2j<esc>`
* `gv<esc>` # '1
* `:lua vim.api.nvim_buf_set_lines(0, 0, 3, false, { "aa", "bb", "cc"})` 
* `gv<esc>` # '2

### Expected behavior

regions in '1 and '2 are the same.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

pacman

**Comment by zeertzjq** [comment]
Looks related to #19571

**Comment by zeertzjq** [comment]
I don't think this is a bug. Replacing text invalidate marks in the range, which includes the start and end of Visual selection.
