### ISSUE TITLE
Control characters printed in initial buffer when using Neovim over ssh

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#24002]
### Problem

When starting up Neovim, I'm seeing control characters printed in the initial buffer.
![nvim-control-characters](https://github.com/neovim/neovim/assets/802511/17f3cbe5-4029-4e47-8a9f-93e2e66933e8)

These look somewhat similar to the [control characters that were emitted on exit](https://github.com/neovim/neovim/issues/17985) in 0.7.0, but with 4;2m instead of 4;0m at the end. Just mentioning this in case the issues have similar causes.

### Steps to reproduce

Open Neovim (still reproduces with `--clean`). See the details below for version information. Please let me know if you need me to check additional information, e.g., something in terminfo.

### Expected behavior

No control characters printed

### Neovim version (nvim -v)

v0.10.0-dev-497+g4229bbe51

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Rocky Linux 8.6

### Terminal name/version

xfce4-terminal 1.0.4

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/18172 mentions that 4;2 is OSC 4

**Comment by gpanders** [comment]
> #18172 mentions that 4;2 is OSC 4
> 
> Posting terminal debug info from `nvim -V1` can be helpful.

OSC codes use `ESC ]`, this is `ESC [` which is a CSI (Control Sequence Introducer). Specifically, `ESC [>4;2m` is the escape sequence to enable the `modifyOtherKeys` Xterm mode.

**Comment by ddickstein** [comment]
I'm not sure if this is what you meant by terminal debug info -- the only output I see from passing `-V1/tmp/debug` is:
```
  1: ~/vim/_editor.lua
  2: ~/neovim/squashfs-root/usr/share/nvim/runtime/ftplugin.vim
  3: ~/neovim/squashfs-root/usr/share/nvim/runtime/indent.vim
  4: ~/neovim/squashfs-root/usr/share/nvim/runtime/filetype.lua
  5: ~/neovim/squashfs-root/usr/share/nvim/runtime/syntax/syntax.vim
  6: ~/neovim/squashfs-root/usr/share/nvim/runtime/syntax/synload.vim
  7: ~/neovim/squashfs-root/usr/share/nvim/runtime/plugin/gzip.vim
  8: ~/neovim/squashfs-root/usr/share/nvim/runtime/plugin/matchit.vim
  9: ~/neovim/squashfs-root/usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
 10: ~/neovim/squashfs-root/usr/share/nvim/runtime/plugin/matchparen.vim
 11: ~/neovim/squashfs-root/usr/share/nvim/runtime/plugin/netrwPlugin.vim
 12: ~/neovim/squashfs-root/usr/share/nvim/runtime/plugin/rplugin.vim
```

I can also confirm that this problem does not happen for me under tmux, nor does it happen with other terminal emulators (xterm, kitty). So maybe that does point in the direction of an xfce4 issue?

**Comment by gpanders** [comment]
>@catern pointed out that both gnome-terminal and xfce4-terminal are based on libvte - maybe the bug is there?

That seems likely. AFAIK libvte is responsible for parsing the terminal codes. We already have [a check](https://github.com/neovim/neovim/blob/a7e5d4238a00d5bfa5809b2860047eca2d565e62/src/nvim/tui/tui.c#L2169-L2172) on the libvte version. Maybe that range needs to be adjusted.

**Comment by ddickstein** [comment]
@TyOverby noticed that we are dropping `VTE_VERSION` over ssh, which is causing us to fall into that check when we otherwise wouldn't. So I think all the behavior we were seeing is now explained!

**Comment by TyOverby** [comment]
I think it's worth re-evaluating the missing vte version check.  If my current reading of the code is correct, it's saying that "if you can't read the vte version, assume that it is is using vte, and that it's using a new version", which may be a mistake.

**Comment by gpanders** [comment]
Terminal emulators _should_ ignore any escape sequence they don't understand, so if a terminal sees `ESC [ > 4 ; 2 m` but does not support `modifyOtherKeys`, it should just ignore the escape sequence without printing it to the terminal.

As far as we know, all terminal emulators do this _except_ for a subset of terminals that use libvte with `VTE_VERSION` < 5400. That is why the check is for that range explicitly.

The `vte_version == 0` is there for terminal emulators which do not define `VTE_VERSION` (and thus do not use libvte). If we remove that condition, then those terminals will not receive the `ESC[>4;2m` sequence at all, so they are not given the chance to enable the `modifyOtherKeys` mode.

**Comment by TyOverby** [comment]
That reasoning makes sense to me, thanks for the clarification
