### ISSUE TITLE
nvim_buf_get_mark() gives wrong values at the first time

### ISSUE THREAD

**Issue by hrcHarry** [neovim/neovim#24011]
### Problem

Version info:
![](https://upload.cc/i1/2023/06/13/HCBotw.png)

I write a simple key mapping as follows
<pre><code>local key_map = vim.keymap.set
local input   = vim.api.nvim_input
local opts    = { noremap = true, silent = true }

key_map('n', '< C-j >', function()
                          input('ma')
                          local row, col  = unpack(vim.api.nvim_buf_get_mark(0, "a"))
                          print(row, col)
                        end, opts)</code></pre>
Then in a buffer, it would be like 
![](https://upload.cc/i1/2023/06/13/EqTDjS.gif)
(Before I type `<C-j>` for the first time, I type `kj` to move the cursor up and down; before I type `<C-j>` for the second time, I type `lh` to move the cursor right and left.)

In this case,
1. at the first position (`5:16`), the mapping `<C-j>` at the first time results in `9 42` (randomly wrong values) while the expected result should be `5 15`, and it gives the expected/correct values at the second time.
2. at the second and third position (`8:12` and `9:29`), it results in the previous value in mark register
   (a) at `8:12`, the first result is `5 15` (the previous values) and the second result is `8 11` (correct values);
   (b) at `9:29`, the first result is `8 11` (the previous values) and the second result is `9 28` (correct values);

### Steps to reproduce

The Lua functions calling `nvim_buf_get_mark()` will get this situation.

### Expected behavior

Hope that `nvim_buf_get_mark()` can give correct values at the first time.

### Neovim version (nvim -v)

0.8.3

### Vim (not Nvim) behaves the same?

Pardon me that I'm not sure what it is. I can/will update this field if anyone generous tell me how to get it.

### Operating system/version

Windows 10/22H2

### Terminal name/version

(PowerShell) Windows Terminal/1.17.11461.0

### $TERM environment variable

nothing

### Installation

repo

**Comment by zeertzjq** [comment]
`nvim_input` does not execute the keys. Use `nvim_feedkeys` with `x` flag to execute the keys.
