### ISSUE TITLE
wrong position of extmark after a <tab> character

### ISSUE THREAD

**Issue by smoka7** [neovim/neovim#24022]
### Problem

when inserting a ext mark on a position after a `<tab>` char NVIM shows the mark on the `<tab>` 
with `virt_text_pos = "overlay"`.
 `virt_text_pos = "inline"` shows the mark on the right spot

### Steps to reproduce

1. run `nvim --clean` .
2. source this file

```
vim.opt.expandtab = false
vim.api.nvim_buf_set_lines(0, 0, 0, false, { "		line 1" })
local ns = vim.api.nvim_create_namespace("")
vim.api.nvim_buf_set_extmark(0,ns,0,2,
{ end_row = 0, end_col = 3, virt_text_pos = "overlay", virt_text = { { "a", "Search" } } })
```
display becomes
`   #    line 1`

### Expected behavior

display becomes
`        #line 1`

### Neovim version (nvim -v)

v0.10.0-dev-509+g6e1fa16dde

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

foot 1.14.0

### $TERM environment variable

foot

### Installation

chaoticaur

**Comment by justinmk** [comment]
related https://github.com/neovim/neovim/issues/23734
