### ISSUE TITLE
Code action with "only" filtering fails if action name contains hyphen (or other Lua pattern magic chars)

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#24039]
### Problem

Using [Lua pattern matching on the code action kind](https://github.com/neovim/neovim/blob/8376e8700b3d4f8ab96751612c3f4439a43b06f4/runtime/lua/vim/lsp/buf.lua#L613) can cause some action kinds to fail to match due to special characters, such as hyphens.

### Steps to reproduce using "nvim -u minimal_init.lua"

Observe that using `only` to filter on a code action with a hyphen in the name does not work properly. Tested with "type-annotate" in ocaml-lsp.

### Expected behavior

 Literal string matching should be supported.

### Neovim version (nvim -v)

0.9.1

### Language server name/version

ocaml-lsp

### Operating system/version

Linux

**Comment by justinmk** [comment]
Do we just need to use `vim.pesc()` here? https://github.com/neovim/neovim/blob/8376e8700b3d4f8ab96751612c3f4439a43b06f4/runtime/lua/vim/lsp/buf.lua#L613

**Comment by ddickstein** [comment]
Sounds like that might do the trick
