### ISSUE TITLE
Minimization behavior difference from vi or htop

### ISSUE THREAD

**Issue by AugustoDeveloper** [neovim/neovim#24035]
### Problem

When i minimize `nvim` , using `C-z`, the neovim goes to background but it's not clearing screen like `vi` or `htop` application

### Steps to reproduce

1. As you can see, neovim is running.
2. So pressing `C-z`, to send neovim to background, the behavior is add new line to cursor.

This is the output:
![image](https://github.com/neovim/neovim/assets/4335700/9acab917-a5b7-4c14-8cb1-59d3d120b85d)
![image](https://github.com/neovim/neovim/assets/4335700/87a1c4ea-4848-4794-9b9c-b6a6a93e2a44)

### Expected behavior

I expected to happen:
![image](https://github.com/neovim/neovim/assets/4335700/f1a7a42f-bb9f-48e2-819d-d00414fe74ef)

I expected similar behavior like the examples below:

`vi`
![image](https://github.com/neovim/neovim/assets/4335700/c54a7b55-f1f5-4afe-9b95-9902f38546ab)

`htop`
![image](https://github.com/neovim/neovim/assets/4335700/25fa2c11-7d1e-4856-8ed5-c16046dfa07c)

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

no, version 8.2.4919

### Operating system/version

Ubuntu 22.04

### Terminal name/version

Contour Terminal Emulator 0.3.12.262

### $TERM environment variable

contour

### Installation

Downloaded Tar file from github releases

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by justinmk** [comment]
Perhaps the terminfo for `TERM=contour` has the wrong entry for the "alternate screen". For troubleshooting, try `TERM=xterm-256color`. 

Not going to debug your system here.
