### ISSUE TITLE
Documents of Pi_netrw and Pi_zip seem broken.

### ISSUE THREAD

**Issue by otakutyrant** [neovim/neovim#24049]
### Problem

When I was [studying internal plugins](https://github.com/neovim/neovim/discussions/24048). I found out documents of [Pi_netrw](https://neovim.io/doc/user/pi_netrw.html) and [Pi_zip](https://neovim.io/doc/user/pi_zip.html#zip-history) seem broken. There are `{{{1` after the `History` title of `Pi_zip` and almost all titles of `Pi_netrw`. And this bug appears in my NeoVim without any configs or plugins too.

I checked some other `Pi_*` documents, although not exhaustly, and they do not have `{{{1`.

### Steps to reproduce

`:h netrw` check all section titles.
`:h zip` check the title of `History` section.

### Expected behavior

No `{{{1`.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.28.1 created by Kovid Goyal

### $TERM environment variable

tmux-256color

### Installation

pacman

**Comment by clason** [comment]
Those are fold markers; they are intentional.
