### ISSUE TITLE
`lsp.buf_attach_client` can return both boolean and nil.

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#24066]
### Problem

`lsp.buf_attach_client` can return `true`/`false` or `nil`, which makes writing a typed binding to it difficult. The return value is also unspecified in the documentation.
https://github.com/neovim/neovim/blob/72a6643b1380cdf6f1153d70eeaffb90bdca30d6/runtime/lua/vim/lsp.lua#L1769-L1773
https://github.com/neovim/neovim/blob/72a6643b1380cdf6f1153d70eeaffb90bdca30d6/runtime/lua/vim/lsp.lua#L1850-L1852
https://github.com/neovim/neovim/blob/72a6643b1380cdf6f1153d70eeaffb90bdca30d6/runtime/lua/vim/lsp.lua#L1862-L1863

### Steps to reproduce using "nvim -u minimal_init.lua"

.

### Expected behavior

Choose semantics for the return value with a consistent type and document them.

### Neovim version (nvim -v)

v0.10.0-dev-533+g7e301ed5b

### Language server name/version

3.17

### Operating system/version

Linux

**Comment by justinmk** [comment]
This is probably just an oversight. Proposal:

- change all `nil` or undefined returns to explicit `false`
- add a type annotation

**Comment by ddickstein** [comment]
Is `false` the right value to return here? The place where we're currently returning `false` indicates a failure to attach, and returning `true` indicates that we attached successfully. If already attached, I think `true` is a more natural return value, letting `false` reflect an error. Or, changing the return type entirely to better model the possibilities (maybe a dictionary).

**Comment by justinmk** [comment]
Sure, whatever matches the semantics that the caller expects is what should be done.
