### ISSUE TITLE
filetype.lua dropped support for /tmp/bash-fc-{id} files.

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#24064]
### Problem

When running readline's `edit-and-execute-command`, Neovim is opened with a temporary file of the form `/tmp/bash-fc-{id}`. This used to be detected as a bash file in `filetype.vim`, but that is no longer true with `filetype.lua`.

### Steps to reproduce

Trigger `edit-and-execute-command` (`C-xC-e` in bash, or if you're using vi mode, `<Esc>v`). Observe that the opened file does not have filetype set.

### Expected behavior

The filetype is bash.

### Neovim version (nvim -v)

v0.10.0-dev-533+g7e301ed5b

### Vim (not Nvim) behaves the same?

No

### Installation

appimage

**Comment by zeertzjq** [comment]
I guess this applies to all of these:
```vim
" Shell scripts ending in a star
au BufNewFile,BufRead .bashrc*,.bash[_-]profile*,.bash[_-]logout*,.bash[_-]aliases*,bash-fc[-.]*,PKGBUILD*,APKBUILD*,*/{,.}bash[_-]completion{,.d,.sh}{,/*} call dist#ft#SetFileTypeSH("bash")
```

**Comment by smjonas** [comment]
This was unnoticed because there are no test cases for this pattern in Vim. I opened https://github.com/vim/vim/pull/12569.
