### ISSUE TITLE
XTerm doesn't properly resize neovim

### ISSUE THREAD

**Issue by mtglsk** [neovim/neovim#2407]
This happens only sometimes, when resizing window nvim stays the old size.

This doesn't tend to happen with a terminal multiplexer though.

Edit: It seems to get triggered on maximize, ie. you can spam maximize button and you will see the old size flashing and nvim resizing to proper size.

**Comment by splinterofchaos** [comment]
This sounds like a duplicate of  #2322, or possibly #2026. Please continue the discussions in those issues, or reopen if I have made a mistake.
