### ISSUE TITLE
feature similar to tmux's key-table

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#24089]
### Problem

there is no easy way to take over all the keyboard inputs from nvim, and remapping all possible keys for a 'custom' mode is not efficient.

### Expected behavior

from what i know, there is no such equivalent in neovim to tmux's key-table.
with it, users can implement their custom mode easily. to me, i want to use it to add an 'IME' mode to nvim as a frontend of librime; and as not nvim is trying to be 'Text editor as a platform'. i think that's worth it to have a consideration.

**Comment by clason** [comment]
There is not, because that is usually (better) handled by the terminal/GUI layer. What would be the benefit from handling this ourselves and bypassing these layers?

**Comment by justinmk** [comment]
There is `vim.on_key()` https://neovim.io/doc/user/lua.html#vim.on_key()

but yes, this is a duplicate of 

- https://github.com/neovim/neovim/issues/992
- https://github.com/neovim/neovim/issues/421

Working towards multicursor may help with this.

**Comment by haolian9** [comment]
great to learn more contexts on this, and sorry for the noise!

weeks later, i got time to try it.
`.on_key()` says '{fn} will receive the keys after mappings have been evaluated', 
and according to [the code](https://github.com/neovim/neovim/blob/release-0.9/src/nvim/getchar.c#L1594), it works just like `tee`, so it could not be the approach i can take.

---
i just know that since 0.11 on_key can consume keys, not just `tee`. so i can continue on my journey.
