### ISSUE TITLE
[Fennel] better table formatting

### ISSUE THREAD

**Issue by alexmozaidze** [neovim/neovim#24080]
### Problem

Currently, in `runtime/indent/fennel.vim`, it simply loads up lisp formatting. In most cases, it works, but when it comes to tables, it stops nesting properly.
```fnl
{1 :gbprod/cutlass.nvim
:opts {:cut_key :x
:exclude [:ns :nS]
:registers {:change :c :delete :d :select :s}}}
```

### Expected behavior

It formats properly
```fnl
{1 :gbprod/cutlass.nvim
 :opts {:cut_key :x
        :exclude [:ns :nS]
        :registers {:change :c :delete :d :select :s}}}
```

**Comment by zeertzjq** [comment]
@gpanders

**Comment by gpanders** [comment]
It'd likely be better to just copy Clojure's indent file than the generic Lisp file.

@alexmozaidze As a test, create a file at `~/.config/nvim/indent/fennel.vim` with the contents:

```vim
runtime! indent/clojure.vim
```

Give that a test drive and let me know if it looks any better or worse. I'll do the same thing. If this looks to be a strict improvement I'll create a PR upstream.

**Comment by gpanders** [comment]
It does work, I've verified it myself (with `nvim --clean`, modifying the Neovim installation, and by creating the `indent/fennel.vim` file in my config as I instructed you to do). Make sure you followed the instructions correctly.

Please paste the output of

```
$ cat $HOME/.config/nvim/indent/fennel.vim
```

and try with all of your plugins disabled.

**Comment by alexmozaidze** [comment]
It still doesn't seem to work, even with `nvim --clean`.
Path to the file: `/data/data/com.termux/files/home/.config/nvim/indent/fennel.vim`
Contents of the file:
```vim

```

**Comment by alexmozaidze** [comment]
It doesn't work. I went as far as to compile Neovim with `runtime/indent/fennel.vim`'s contents changed to
```vim
" Vim indent file
" Language:    Fennel
" Maintainer:  Gregory Anders <greg[NOSPAM]@gpanders.com>
" Last Change: 2022 Apr 20

" Only load this indent file when no other was loaded.
if exists("b:did_indent")
  finish
endif

" Use the Lisp indenting
runtime! indent/clojure.vim
```
`/usr/local/bin/nvim --clean` and still `gg=G` indents are incorrect.

**Comment by gpanders** [comment]
> /usr/local/bin/nvim --clean and still gg=G indents are incorrect.

Ah, I did not realize that is how you were testing.

When using Clojure's indent file the indent on newlines _as you write_ is correct. Example:

```fennel
{1 :gbprod/cutlass.nvim
 :opts {:cut_key :x<Enter>
        |
        ^--- cursor is here
```

But it looks like `gg=G` does not indent correctly. So this is a shortcoming of Clojure's `indentexpr`.

You can try contacting the Clojure indent file's maintainer (listed in the file). They may be interested in improving it. Or even better, you can try and improve it yourself.

Alternatively, you can use an external tool like [`fnlfmt`](https://git.sr.ht/~technomancy/fnlfmt), or a plugin like [nvim-parinfer](https://github.com/gpanders/nvim-parinfer).

**Comment by alexmozaidze** [comment]
Okie, I'll see what I can do, though, I don't expect to be able to do much. Thanks for directions.

**Comment by gpanders** [comment]
>Also, lisp indenting also indents correctly as you type, so changing it to clojure didn't do much.

It does not for me.

Without using the Clojure indent file:

```
{:foo {:bar 1<Enter>
|      | 
^      ^---------------- cursor should be here
└----- but it is here instead
```

**Comment by alexmozaidze** [comment]
Oh, yeah, you're right. Clojure formatting works better.

**Comment by SATBH** [comment]
Had this same issue. For me, setting fennel to use the clojure indenting resulted in the same problem. But removing  the "setlocal lisp" line from /usr/share/nvim/runtime/ftplugin/fennel.vim solved it for me.

**Comment by net** [comment]
Adding `runtime! indent/clojure.vim` to `~/.config/nvim/indent/fennel.vim` improved indentation for me.
