### ISSUE TITLE
Garbled screen after :set laststatus=0 | vnew | new | botright 20new

### ISSUE THREAD

**Issue by mtglsk** [neovim/neovim#2409]
Use this as an example:

```
:set laststatus=0 | vnew | new | botright 20new<CR>
```

Screen gets garbled. I've noted this when using FZF.

Not a big issue, because most people use `laststatus=2`, nevertheless it seems like a bug.

**Comment by mtglsk** [comment]
It seems to be a VIM bug after all. Closing.

**Comment by splinterofchaos** [comment]
Do we not consider bugs in vim bugs in neovim too?

Been looking into this. This patch seems to fix it...
```patch
diff --git a/src/nvim/window.c b/src/nvim/window.c
index 9c56cc5..ee6ed78 100644
--- a/src/nvim/window.c
+++ b/src/nvim/window.c
@@ -2465,8 +2465,9 @@ static void frame_add_statusline(frame_T *frp)
   if (frp->fr_layout == FR_LEAF) {
     wp = frp->fr_win;
     if (wp->w_status_height == 0) {
-      if (wp->w_height > 0)             /* don't make it negative */
-        --wp->w_height;
+      if (wp->w_height > STATUS_HEIGHT) {
+        wp->w_height -= STATUS_HEIGHT;
+      }
       wp->w_status_height = STATUS_HEIGHT;
     }
   } else if (frp->fr_layout == FR_ROW) {
```
but doesn't fix `:set laststatus=0 | vnew | vnew | botright 20new<CR>`.

**Comment by Pyrohh** [comment]
> Do we not consider bugs in vim bugs in neovim too?

Yes, I think we do: [CONTRIBUTING.md#reporting-problems](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#reporting-problems).

**Comment by fwalch** [comment]
cc @chrisbra

**Comment by chrisbra** [comment]
Isn't that the same as that one:
https://groups.google.com/d/msg/vim_dev/fNq8tHTcKfA/7yg4GZ1h8agJ

Best,
Christian
-- 
Man erkennt den Irrtum daran, daß alle Welt ihn teilt.
		-- Jean Giraudoux

**Comment by splinterofchaos** [comment]
@chrisbra thanks, I missed that. 

I can't replicate it in vim, so maybe we changed something, but there's still a problem in neovim:
```vim
set laststatus=0 
botright new
call feedkeys("\<C-w>ki")
```
The screen fails to redraw and every time I enter insert mode the status line creeps up. Maybe I missed it again if there's an existing vim patch...

**Comment by justinmk** [comment]
Cannot reproduce. Similar issue: https://github.com/neovim/neovim/issues/5354
