### ISSUE TITLE
Inlay hints aren't correctly highlighted in visual mode

### ISSUE THREAD

**Issue by igorlfs** [neovim/neovim#24094]
### Problem

Visually selecting a line containing inlay hints doesn't highlight the hint's background:

![image](https://github.com/neovim/neovim/assets/84649544/0cff960a-369f-48c2-86d9-e346f4460062)

### Steps to reproduce

```lua
for name, url in pairs({
	"https://github.com/neovim/nvim-lspconfig",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

require("lspconfig").lua_ls.setup({
	settings = { Lua = { hint = { enable = true } } },
})
```

`:lua vim.lsp.buf.inlay_hint(0, true)`
12ggV

### Expected behavior

The background should be highlighted.

### Neovim version (nvim -v)

v0.10.0-dev-551+ge27377e33e

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Linux 6.3.8

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-256color

### Installation

AUR

**Comment by nyngwang** [comment]
Is it possible to check `supports_method('textDocument/inlayHint')` outside of the `on_attach`?

**Comment by zeertzjq** [comment]
It's possible to make `hl_mode = combine` also work with inline virtual text. But a question arises here: how should inline virtual text with `hl_mode = combine` be highlighted if it is at the start or the end of a Visual selection?

**Comment by lewis6991** [comment]
I kind of see this as a feature since the inlay hints can't be copied or operated on, so the fact they are not visually highlighted effectively conveys that.

**Comment by clason** [comment]
I agre, but it should be consistent with highlight on yank (which currently highlights the whole range, naturally). Ideally, the latter should be taught to ignore inline virtual text, but that is far from trivial...

**Comment by justinmk** [comment]
> the inlay hints can't be copied or operated on, so the fact they are not visually highlighted effectively conveys that.

Agreed but should/can this be decided by setting a "priority" on `LspInlayHint` rather than accidentally doing it in the display layer?

**Comment by zeertzjq** [comment]
The old behavior is stored in #24276. This is wontfix now.
