### ISSUE TITLE
-l does not set _G.arg[0] when there's no extra arguments pass to the script

### ISSUE THREAD

**Issue by Mike325** [neovim/neovim#24110]
### Problem

Executing scripts without any arguments (Ex. `nvim -l args.lua`) does not set _G.arg[0]

### Steps to reproduce

```sh
cat > args.lua<<EOF
vim.print(_G.arg, '')
vim.print(vim.v.argv, '')
EOF

nvim --clean -l args.lua
```

### Expected behavior

`_G.arg[0]` be setted to "args.lua"

### Neovim version (nvim -v)

NVIM v0.10.0-dev-8d4a53fe6

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Red Hat Enterprise Linux Server release 7.7

### Terminal name/version

wezterm 20230619-104421-c1f49509

### $TERM environment variable

screen-256color

### Installation

build from repo

**Comment by justinmk** [comment]
Thanks for catching that. If you can send a PR, should be a small fix here: https://github.com/neovim/neovim/blob/4e6356559c8cd44dbcaa765d1f39e176064526ec/src/nvim/lua/executor.c#L335

And needs a small test update in https://github.com/neovim/neovim/blob/4e6356559c8cd44dbcaa765d1f39e176064526ec/test/functional/core/startup_spec.lua#L146
