### ISSUE TITLE
after nvim_win_set_config, the floatwin moves as the cursor moves

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#24129]
### Problem

it seems after called nvim_win_config to a floatwin, the floatwin's relative target became to itself. so on every cursor movement, it moves itself too.

### Steps to reproduce

* nvim --clean +'so test.lua'
* jkjk

test.lua
```
local api = vim.api

local bufnr = api.nvim_create_buf(false, true)
api.nvim_buf_set_lines(bufnr, 0, -1, false, { "a", "b", "c", "d" })

local winid = vim.api.nvim_open_win(bufnr, true, { relative = "win", row = 3, col = 3, width = 12, height = 3 })

api.nvim_win_set_config(winid, { relative = "win", row = 3, col = 3, width = 12, height = 3 })
```

### Expected behavior

the floatwin still anchors to the window/cursor when it's been created.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

pacman

**Comment by zeertzjq** [comment]
Related #18368

**Comment by zeertzjq** [comment]
Hmm, I don't think this behavior should be changed, as plugins may rely on `relative = 'win'` without `win` implying current window (which is mentioned in the docs of `nvim_open_win` but not `nvim_win_set_config`). But having a way to change `row`/`col` without having `relative` in the new `opts` (#18368) may be fine.

**Comment by glepnir** [comment]
not a feature. `comp_row` of grid increase every times. then `row +=grid->comp_row` also increase.

**Comment by zeertzjq** [comment]
What is missing here is a way to leave `win` unchanged when using `nvim_win_set_config` with `relative = 'win'`. However:
- Leaving `win` unchanged if it is omitted is not backward-compatible
- Leaving `win` unchanged if it is the configured window itself is a bit confusing

**Comment by zeertzjq** [comment]
After #25550 specifying `win = -1` will work, although this is not documented.
