### ISSUE TITLE
Super-slow diagnostics show up character by character

### ISSUE THREAD

**Issue by wzyboy** [neovim/neovim#24133]
### Problem

The issue is very similar to #14161. See screen record below:

https://github.com/neovim/neovim/assets/459384/1cf02af6-e168-4d1b-ae2a-0f9a235ad6da

* The issue exists on my personal laptop (NVIM v0.9.1)
* The issue DOES NOT exist on my work laptop (NVIM v0.7.2)
* Two laptops use the same `init.vim` file

I was able to reproduce this issue with a minimal `init.vim` as follows:

```
call plug#begin('~/.vim/plugged')
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua <<EOF
  require'lspconfig'.terraformls.setup{}
EOF
```

The screen record above is recorded with this minimal `init.vim` config.

I have attached the relatively large `lsp.log` file generated by:

1. delete existing `lsp.log`
2. open nvim
3. type something (like in the screen record)
4. `tail -F lsp.log` until it stops
5. close nvim
6. upload `lsp.log` file to Gist

### Steps to reproduce using "nvim -u minimal_init.lua"

Sample Terraform code used in the screen record:

```terraform
resource "aws_s3_bucket_lifecycle_configuration" "foo" {
}
```

### Expected behavior

The diagnostics info show up quickly and smoothly.

### Neovim version (nvim -v)

NVIM v0.9.1

### Language server name/version

terraform-ls 0.31.3

### Operating system/version

Arch Linux

### Log file

https://gist.github.com/wzyboy/248e70eb2d6a6f105354b7adca07ee32

**Comment by wzyboy** [comment]
I recorded a better clip.


https://github.com/neovim/neovim/assets/459384/12e2ed5c-eb6f-4020-b654-b09f8641d03c

**Comment by justinmk** [comment]
> * The issue exists on my personal laptop (NVIM v0.9.1)
> * The issue DOES NOT exist on my work laptop (NVIM v0.7.2)

Can you bisect to a specific nvim commit by building nvim from source (it's easy).

**Comment by wzyboy** [comment]
Thanks for the guidance. Bisecting reveals that it might not be the issue with Neovim, but with `terraform-ls`.

* My work laptop has Neovim 0.7.2 + terraform-ls 0.28.1
* My personal laptop has Neovim 0.9.1 + terraform-ls 0.31.3

I tried the following combinations of Neovim + terraform-ls on my personal laptop:

```
0.9.1 + 0.31.3 = broken
0.7.2 + 0.31.3 = broken
0.7.2 + 0.28.1 = good
0.9.1 + 0.28.1 = good
```

I'll open a PR with terraform-ls.

**Comment by clason** [comment]
Thanks for checking!
