### ISSUE TITLE
Using Neovim as MANPAGER - can't press K on line-split man links

### ISSUE THREAD

**Issue by mooreye** [neovim/neovim#24146]
### Problem

Neovim has support of being a manpager by using this:

`MANPAGER='nvim -c Man!'`

Once on a manpage, you can go to other mentioned manpages by pressing `K`. However, if a mentioned manpage is split over the line (because of either `MANWIDTH` variable or terminal being of such width that it happens to split this manpage name), it won't work. Example:

https://i.imgur.com/gYznD03.png

Neovim tries to go to `put` instead of  `sway-output(5)` man page because it is split over the next line.

This may be hard to fix since mid-word hyphenation is rather unpredictable, but even with `MANOPT=--nh` (no hyphenation option), it still splits lines if a literal `-` character is encountered, and in this case it will be a full word `output(5)` on the next line, and same error occurs because it is not the full manpage name.

### Steps to reproduce

`MANPAGER='nvim -c Man!' man 5 sway`

### Expected behavior

Neovim goes to `sway-output(5)` manpage correctly

### Neovim version (nvim -v)

v0.9.1

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Fedora 38

### Terminal name/version

GNOME Terminal 3.48.1 using VTE 0.72.2

### $TERM environment variable

xterm-256color

### Installation

dnf

**Comment by zeertzjq** [comment]
I don't think it's possible to know whether the hyphen is actually a part of the link or inserted by `groff` because of `$MANWIDTH`. The only solution here is changing `$MANWIDTH`.

Also see `:h g:man_hardwrap`.
