### ISSUE TITLE
Documentation improvements for vim.diagnostic.get()

### ISSUE THREAD

**Issue by uga-rosa** [neovim/neovim#24143]
### Problem

TL;DL
Can you add that bufnr is not optional in the return value of `vim.diagnostic.get()`?

First, I apologize if my understanding is incorrect.

The return value of `vim.diagnostic.get()` is a list of `diagnostic-structure`.
```help
get({bufnr}, {opts})                                    *vim.diagnostic.get()*
    Get current diagnostics.

    Parameters: ~
      • {bufnr}  (integer|nil) Buffer number to get diagnostics from. Use 0
                 for current buffer or nil for all buffers.
      • {opts}   (table|nil) A table with the following keys:
                 • namespace: (number) Limit diagnostics to the given
                   namespace.
                 • lnum: (number) Limit diagnostics to the given line number.
                 • severity: See |diagnostic-severity|.

    Return: ~
        Diagnostic [] table A list of diagnostic items |diagnostic-structure|.
```

Help says `bufnr` of `diagnostic-structure` is optional.
```help
                                                        *diagnostic-structure*
A diagnostic is a Lua table with the following keys. Required keys are
indicated with (+):

    bufnr: Buffer number
    lnum(+): The starting line of the diagnostic
    end_lnum: The final line of the diagnostic
    col(+): The starting column of the diagnostic
    end_col: The final column of the diagnostic
    severity: The severity of the diagnostic |vim.diagnostic.severity|
    message(+): The diagnostic text
    source: The source of the diagnostic
    code: The diagnostic code
    user_data: Arbitrary data plugins or users can add

Diagnostics use the same indexing as the rest of the Nvim API (i.e. 0-based
rows and columns). |api-indexing|
```

### Expected behavior

`vim.diagnostic.set()`, however, fills bufnr and then creates a cache.
https://github.com/neovim/neovim/blob/cc624fac683ce6dbd01f10781817cd654cceed38/runtime/lua/vim/diagnostic.lua#L702
https://github.com/neovim/neovim/blob/cc624fac683ce6dbd01f10781817cd654cceed38/runtime/lua/vim/diagnostic.lua#L282-L282

It seems that caches cannot be added except by `set()`, and I think it is safe to assume that anything you can get with `get()` will always have bufnr in it.
So I would like to see this documented.

**Comment by gpanders** [comment]
A PR with a suggested change would be welcome.

Note that in the documentation for the diagnostic structure, the required fields refer to fields that are required for *setting* diagnostics.

**Comment by uga-rosa** [comment]
I wasn't sure if my understanding was correct, so I made the issue once.
Since `diagnostic-structure` is also referenced by `vim.diagnostic.set()`, I will keep the changes within `vim.diagnostic.get()`.
