### ISSUE TITLE
Clarify docs around :set< for unsetting the local value of a global-local option

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#24149]
### Problem

https://github.com/neovim/neovim/blob/5ceb2238d3685255cd517ca87fd7edae9ed88811/runtime/doc/options.txt#L299-L310
My reading of this snippet is:
* To unset the local value of number and boolean options, use `:setlocal name<`. The behavior of `:set name<` is not defined.
* To unset the local value of string options, use `:set name<` (or `:setlocal name=`). `:setlocal name<` will instead copy the global value.

This reading is different from these docs:
https://github.com/neovim/neovim/blob/5ceb2238d3685255cd517ca87fd7edae9ed88811/runtime/doc/options.txt#L257-L261

### Expected behavior

The docs on unsetting local values for global-local options should be consistent.

### Neovim version (nvim -v)

v0.10.0-dev-569+gfa0a25dcb

### Vim (not Nvim) behaves the same?

Yes

**Comment by clason** [comment]
As these are Vim docs that are copied verbatim, your best bet is to raise this issue upstream at vim/vim.

**Comment by ddickstein** [comment]
https://github.com/vim/vim/issues/12594
