### ISSUE TITLE
treesitter fold not updated if treesitter hightlight is not active

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#24150]
### Problem

Treesitter folds are not updated correctly if `vim.treesitter.start()` is not used. This is because without activating treesitter highlight, nvim won't call `LanguageTree:parse()` on each update (as in https://github.com/neovim/neovim/blob/5ceb2238d3685255cd517ca87fd7edae9ed88811/runtime/lua/vim/treesitter/highlighter.lua#L317). 

Therefore, the foldexpr itself should call `LanguageTree:parse()` where appropriate if highlighting is not active. Another option would be to make a separate function for activating treesitter highlight, and to change `vim.treesitter.start` to do the minimal jobs required for treesitter-based functionalities to work correctly.

### Steps to reproduce

The following example demonstrates the necessity of `parse()` for foldepxr. Run nvim as follows:
```
nvim --clean -S <(tee << 'EOF'
    set fdc=1 fdm=expr fde=v:lua.vim.treesitter.foldexpr()
    setf lua
    call setline(1, ['function asdf()', '  return', 'end'])
    lua vim.treesitter.get_parser()
EOF
)
```
Despite that the buffer has a parser, folds are not updated:
![image](https://github.com/neovim/neovim/assets/19489738/be70464c-8958-4b23-9285-6eb815f3c29a)

### Expected behavior

If I manually run `parse()`, folds are updated correctly:
```
nvim --clean -S <(tee << 'EOF'
    set fdc=1 fdm=expr fde=v:lua.vim.treesitter.foldexpr()
    setf lua
    call setline(1, ['function asdf()', '  return', 'end'])
    lua vim.treesitter.get_parser():parse()
EOF
)
```
![image](https://github.com/neovim/neovim/assets/19489738/7825e415-08c2-484e-8e36-2ea3c432d100)

### Neovim version (nvim -v)

8182384205d3c222e999ea9a78276cbf685f50fd

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

tmux-256color

### Installation

built from the repository

**Comment by lewis6991** [comment]
I'm not particularly interested in supporting TS foldexpr without highlighting. PR welcome though.

**Comment by justinmk** [comment]
This definitely sounds like a wontfix.

**Comment by justinmk** [comment]
I misinterpreted the details here, this is probably reasonable to implement.
