### ISSUE TITLE
Inconsistent behavior of :Lexplore

### ISSUE THREAD

**Issue by Mattron2000** [neovim/neovim#24165]
### Problem

# Inconsistent behavior of :Lexplore

## Neovim version (nvim -v)

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

## OS
- name: Arch Linux
- kernel: 6.1.35-1-lts
- protocol: wayland
- DE: KDE 5.27.6
- terminal: Konsole

## Installation
Installed by pacman

```bash
sudo pacman -Sy neovim
```

## Premise

After years of VSCode, I wanted to give Neovim a chance for the first time, so I’m very beginning, but I’m putting a lot of time and cure as curious about how I’m able to create/customize my setup. 

PS.
I apologize in advance if this report is stupid because I haven't read the documentation that's right, you can close it as you want. 

## What I wanted to achieve

I wanted to turn the sidebar `:Lex` on and off with a single keymap and I created the following lines for this:

```lua
local keymap = vim.api.nvim_set_keymap
local opts = {noremap = true, silent = true}
 
keymap("", "<Space>", "<Nop>", opts)
vim.g.mapleader = " "
vim.g.maplocalleader = " "

keymap("n","<leader>e", ":30Lex<cr>", opts)
```

After running `:w` and `:so %`, I execute the shortcut and it opens it and closes the sidebar on the left wide 30 columns, perfect! But...

Problems arise when I wanted to open the sidebar in the same folder as the open file, so I modified the code in... 

```lua
-- All the same, except...

keymap("n","<leader>e", ":30Lex %:h<cr>", opts)
```

With this configuration, the sidebar opens in the right position but no longer closes, which forces me to write `:q` to close it.

I noticed a strange thing, maybe it's a bug, while experimenting to solve this problem, when I changed the keymap in... 

```lua
-- tutto uguale, eccetto...

keymap("n","<leader>e", ":30Lex! %:h<cr>", opts)
```

Now it works properly! It opens and closes the sidebar with a single shortcut, but the sidebar is on the right as it is described in the documentation.

All this talk to get to this point... 

## Question

Did you developers foresee the difference in behavior of the two commands or is it actually a bug?

```lua
keymap("n","<leader>e", ":30Lex %:h<cr>", opts)
keymap("n","<leader>e", ":30Lex! %:h<cr>", opts)
```

## Video

https://github.com/neovim/neovim/assets/88315099/538d18ff-ebd4-4318-9dab-84ad21832f51

In the video you can't see, I retry with `nvim --clean` but nothing changed.

### Steps to reproduce

write in keymaps.lua:
keymap("n","<leader>e", ":30Lex %:h<cr>", opts)
-- keymap("n","<leader>e", ":30Lex! %:h<cr>", opts)

try pressing repeately <leader>e with one of two keymaps e compare with other. 

### Expected behavior

I suppose that these commands should behave the same except that `:30Lex %:h` open and close the sidebar on the left and `:30Lex! %:h` open and close the sidebar on the right.

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no, vim 9.0, netrw not exist with -u DEFAULTS 

### Operating system/version

Arch Linux

### Terminal name/version

Konsole Version 23.04.2

### $TERM environment variable

xterm-256color

### Installation

Arch Linux pacman

**Comment by justinmk** [comment]
> Vim (not Nvim) behaves the same?
> no, vim 9.0, netrw not exist with -u DEFAULTS

Find a way to run netrw on vim.

Not going to answer deep questions about netrw here, it's unsupported.
