### ISSUE TITLE
`make install` fails on Archlinux

### ISSUE THREAD

**Issue by raichoo** [neovim/neovim#2416]
Hi,
I get the following error message when running `make install`:

    CMake Error at cmake/GenerateHelptags.cmake:25 (message):
      Generating helptags failed:
  
      - 1
    Call Stack (most recent call first):
      cmake_install.cmake:516 (include)

    Makefile:85: recipe for target 'install' failed
    make: *** [install] Error 1

Previous to that I'm doing `make` to get all the dependencies and `cmake -DCMAKE_INSTALL_PREFIX:PATH=/mynvimpath -DCMAKE_BUILD_TYPE=Release`. This worked fine before but broke after pulling recently.

Kind regards,
raichoo

**Comment by tarruda** [comment]
Some old tags in the runtime directory are causing the `helptags` command(called during install) to fail. If you remove nvim runtime directory and reinstall it should work.

**Comment by raichoo** [comment]
Less then 5 minutes! Thanks for the awesome support. That fixed it ^^
