### ISSUE TITLE
The `:!ls` command in the tutor document does not work on Windows 

### ISSUE THREAD

**Issue by senorL** [neovim/neovim#24166]
### Problem

**Operating system: Windows 11**  
**Version: 0.9.1** 
Content: When I was reading and learning the tutor document, in # Lesson 5.2: MORE ON WRITING FILES, the `:!ls`  command did not work on my system. After searching, I found that `:!dir` would be more appropriate. I know this may be a small issue, but it did cause a lot of confusion for me as a beginner.
<img width="580" alt="屏幕截图 2023-06-26 232942" src="https://github.com/neovim/neovim/assets/110690291/cbd09612-1e1b-4e80-b53e-8a53a5c1e025">

### Expected behavior

After searching, I found that `:!dir` would be more appropriate. I know this may be a small issue, but it did cause a lot of confusion for me as a beginner.

**Comment by alzen8mobile** [comment]
is this problem resolved? Im facing the same issue so you know 🙏...

**Comment by senorL** [comment]
> Is this problem resolved? I'm facing the same issue so you know 🙏, new to vim, as well as nvim, hope it could be fix asap ya, otherwise update the docs for windows ya thx...
I said above to use '!dir' command

**Comment by senorL** [comment]
> Is this problem resolved? I'm facing the same issue so you know 🙏, new to vim, as well as nvim, hope it could be fix asap ya, otherwise update the docs for windows ya thx...

I said above to use '!dir' command
