### ISSUE TITLE
Why is python indentation hard coded to be spaces?

### ISSUE THREAD

**Issue by denppa** [neovim/neovim#24176]
### Problem

https://github.com/neovim/neovim/blob/master/runtime/ftplugin/python.vim#L119 shows that python files are always opened with `expandtab = true`, and this setting even overrides a global `expandtab = false` setting.

Due to this line of code, the user is forced to run an autocmd whenever a python file is opened to set expandtab to be false. Why was this hard coded into neovim? Shouldn't the editor respect the user's settings instead?

### Steps to reproduce

`example.py`:
```python
msg = 'ok'
def main():
	print(msg)

if __name__ == '__main__':
	main()
```

1. `set noexpandtab`
2. `set noexpandtab?` returns `noexpandtab`
3. nvim example.py
4.  `set noexpandtab?` returns `expandtab`

### Expected behavior

neovim should respect the global settings a user has chosen.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

v0.9.1

### Operating system/version

macOS Ventura

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

brew

**Comment by clason** [comment]
These files are taken unchanged from Vim, so you'll have to ask there (or, rather, the maintainer listed at the top of the file.

**Comment by denppa** [comment]
Thank you, I will raise my question there.

**Comment by clason** [comment]
(the answer is very likely to be "just create an `/after/ftplugin/python.vim` that sets it to `false`)

**Comment by denppa** [comment]
That makes sense. I suppose the editor comes with a sane default and then allows the user to configure it the way they want through other means, in this case through the after script or an `autocmd`. Fair enough.

Easier than chasing down whoever committed that line of code.
