### ISSUE TITLE
Treesitter freezes nvim

### ISSUE THREAD

**Issue by Drllap** [neovim/neovim#24171]
### Problem

Not sure if I should post this on this issue tracker or on `nvim-treesitter`.

I have this big header-only library in my project [CImg Library](https://cimg.eu/). It is basically one big header file (40'000 lines).

Every time I use `:Telescope find_files` and type something that makes this big file `CImg.h` pop up into the `File Preview`, nvim stops responding, and the CPU usage skyrockets.

This also happens when I open the file directly with `nvim CImg.h`

I'm fairly sure this has something to do with treesitter because this stops when I disable `nvim-treesitter`

### Steps to reproduce

nvim CImg.h

### Expected behavior

nvim shouldn't stop responding

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 10

### Terminal name/version

wezterm 20230619-104421-c1f49509

### $TERM environment variable

xterm-256color

### Installation

chocolatey

**Comment by Drllap** [comment]
Here is the header file in question: https://www.dropbox.com/s/1b0woj770unawst/CImg.h?dl=0

**Comment by Drllap** [comment]
this is my treesitter config:
```
require('nvim-treesitter.configs').setup {
  ensure_installed = { "c", "cpp", "rust", "cmake", "dockerfile", "lua", "vim", "python",
                       "json", "yaml", "toml", "markdown" },

  highlight = {
    enable = true,
    disable = {},

    custom_captures = {
    },
    additional_vim_regex_highlighting = true,
  },

  indent = {
    enable = true,
    disable = { "python", "cpp", "json", "lua" },
  },
}
```

**Comment by clason** [comment]
Yes, tree-sitter has problems with huge (header) files; this is a known problem and actively being worked on. You can try removing `c` injections for preprocessors (which are already disabled in Neovim, so your issue is actually with the nvim-treesitter queries).

**Comment by Drllap** [comment]
@clason

Thanks.  Is there an issue I can follow to get notified of progress?

> You can try removing `c` injections for preprocessors.
Can you elaborate on this?

**Comment by clason** [comment]
It's tracked across a number of issues and PRs. 

and https://github.com/neovim/neovim/blob/8ea9a70d05d6a7f9bab410101a87e6b184f14634/runtime/queries/c/injections.scm#L1-L2
