### ISSUE TITLE
nightly: crash after requiring *.so file

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#24175]
### Problem

It crashes when I try to require a `*.so` file which uses some functions from `lauxlib.h`.

### Steps to reproduce

```
printf '#include <lua.h>\n#include <lauxlib.h>\nstatic int foo(lua_State *L){return 0;};int luaopen_file(lua_State *L){luaL_Reg reg[]={{"foo",foo}};luaL_newlib(L,reg);return 1;};'>file.c
gcc file.c -shared -llua -o file.so
nvim --clean
:lua require'file'
```

### Expected behavior

It not crashing.

### Neovim version (nvim -v)

v0.10.0-dev-e85e7fc

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Linux 6.3.9-arch1-1

### Terminal name/version

alacritty 0.12.1

### $TERM environment variable

alacritty

### Installation

build from repo

**Comment by clason** [comment]
What's the lauxlib.h from, precisely?

**Comment by clason** [comment]
And basically, as soon as you cross into C, you're on your own, and crashes are _your_ problem.

**Comment by altermo** [comment]
lauxlib is the builtin lua [Auxiliary Library](https://www.lua.org/manual/5.4/manual.html#5)

**Comment by clason** [comment]
Yes, but from which Lua version? Neovim only supports 5.1.

**Comment by altermo** [comment]
Oh, I was using version 5.4.
Was it unintended behavior for this version to work with neovim 9.1?

**Comment by clason** [comment]
Yes.
