### ISSUE TITLE
inlayHints: attempt to index field 'applied'

### ISSUE THREAD

**Issue by caarlos0** [neovim/neovim#24172]
### Problem

After a while, not sure for what reason exactly, I start to get this error when inlay hints are enabled:

```
vim_lsp_inlayhint: Error executing lua: ...d-91aeaee/share/nvim/runtime/lua/vim/lsp/_inlay_hint.lua:249: attempt to index field 'applied' (a nil value)
```

PS: reopening the buffer (`:e`) seems to "resolve" the issue... until it happens again...

### Steps to reproduce

unsure.

### Expected behavior

not error

### Neovim version (nvim -v)

NVIM v0.10.0-dev-91aeaee

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Linux 6.2.6-76060206-generic 

### Terminal name/version

wezterm

### $TERM environment variable

wezterm

### Installation

nix nightly overlay: https://github.com/nix-community/neovim-nightly-overlay

**Comment by jdujava** [comment]
I am able to reproduce this with *some* files consistently:
- open a file and launch a corresponding LSP together with inlayHints
- `git checkout` to the commit where the contents of the file (and also the hints) are different 
   *(or restore old state of the file using `:earlier {count}` or `undotree`, sometimes just launching `undotree` is enough)*
- after Neovim re-reads the file, the errors pop up

**Comment by justinmk** [comment]
cc @p00f

**Comment by p00f** [comment]
#24202
