### ISSUE TITLE
lsp: No `textDocument/inlayHint` request sent to sourcekit-lsp

### ISSUE THREAD

**Issue by uhooi** [neovim/neovim#24183]
### Problem

SSIA
ref: https://github.com/apple/sourcekit-lsp/issues/757#issuecomment-1610068694

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
require('lspconfig').sourcekit.setup()
```

### Expected behavior

`textDocument/inlayHint` request is sent to sourcekit-lsp and inlay hint is displayed

### Neovim version (nvim -v)

v0.10.0-dev-578+g91aeaeef6

### Language server name/version

sourcekit-lsp: Included in Xcode 15.0 Beta

### Operating system/version

macOS Ventura 13.3.1 (a)

### Log file

https://gist.github.com/uhooi/780f9e393c77f46e459e2267b469217d

**Comment by jdrouhard** [comment]
They aren't enabled by default. You have to use `vim.lsp.buf.inlay_hint(<bufnr>)` (use 0 for current buffer) to toggle them on/off. The function is likely moving to `vim.lsp.inlay_hint(...)` soon, though.

**Comment by uhooi** [comment]
Sorry, it showed.
I am concerned that `client.supports_method('textDocument/inlayHint')` is `false` , but it is OK.

**Comment by uhooi** [comment]
I used `client.server_capabilities.inlayHintProvider` instead of `client.supports_method('textDocument/inlayHint')` and it was the same.
I think sourcekit-lsp is started after `LspAttach` is called.

**Comment by bryanboateng** [comment]
Where you able to solve the problem and if so how?
