### ISSUE TITLE
`nvim -l` not adding newline as `nvim -ll` does

### ISSUE THREAD

**Issue by petobens** [neovim/neovim#24180]
### Problem

`nvim -ll` and `nvim-l` don't show the same behaviour regarding newline.

### Steps to reproduce

Consider the following `foo.lua` file:
```lua
print('foo')
```
Now run both `nvim -ll foo.lua` and `nvim -l foo.lua`. Observe, as in the image below, that the output is different. Most notably a newline seems to be missing from `nvim -l` (i.e if add `print('\n')` to the file above and re-run `nvim -l foo.lua` i do get the same behaviour as with `nvim -ll`. 

![Screenshot_2023-06-27_19:44:14](https://github.com/neovim/neovim/assets/2583971/b0219898-4e8a-4384-ac8c-94ea014944b1)

### Expected behavior

Have `nvim -ll` and `nvim -l` behave the same.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-586+g8ea9a70d05

### Vim (not Nvim) behaves the same?

Dunno

### Operating system/version

Arch 

### Terminal name/version

bash 5.1.16

### $TERM environment variable

xterm-256-color

### Installation

AUR

**Comment by zeertzjq** [comment]
I don't think there is a good reason to change this behavior.

The current behavior is consistent with:
- `nvim_exec2`
- `execute()`
- `:redir`

**Comment by petobens** [comment]
@zeertzjq ok I understand. Is there and ad-hoc way/workaround to add such new line in my example? i.e get the newline without modifying the `foo.lua` file. Something along the lines of `nvim {something} -l foo.lua` or `nvim -l foo.lua {something}`?

**Comment by zeertzjq** [comment]
I think you can replace the `print()` function to behave like the original one:
```sh
nvim --clean --headless --cmd 'lua _G.print = function(...) io.stderr:write(table.concat(vim.tbl_map(tostring, {...}), "\t") .. "\n") end' -l foo.lua
```

**Comment by petobens** [comment]
I see. I guess I should also do something like  that for `vim.print` and so on... Thanks

**Comment by justinmk** [comment]
> The current behavior is consistent with:
> 
> * Using `:echo` or Lua `print()` in headless mode (which is mostly the same thing, and it has been like this for a long time)

Question is what is most commonly expected, especially compared to `lua` cli. It's not too late to change `nvim -l`.

**Comment by petobens** [comment]
> Question is what is most commonly expected, especially compared to lua cli. It's not too late to change nvim -l.

I believe that adding the newline is the most common thing (also what `lua foo.lua` does).

**Comment by petobens** [comment]
@zeertzjq can we re-open/reconsider this given @justinmk comment?

**Comment by petobens** [comment]
Thank you!
