### ISSUE TITLE
18 new coverity issues

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#2422]
Probably introduced by #2415. 
@tarruda Please have a look.

**Comment by tarruda** [comment]
A first look doesn't tell me how #2415 could have caused that, the big change introduced was replace `free` by `xfree`.

Could this be an old bug that was only discovered now?

**Comment by tarruda** [comment]
Is there a way to test if this would fix the problem?

```diff
diff --git a/src/nvim/memory.c b/src/nvim/memory.c
index 2d4259a..2c6c0c0 100644
--- a/src/nvim/memory.c
+++ b/src/nvim/memory.c
@@ -103,7 +103,9 @@ void *xmalloc(size_t size)
 /// free wrapper that returns delegates to the backing memory manager
 void xfree(void *ptr)
 {
-  free(ptr);
+  if (ptr != NULL) {
+    free(ptr);
+  }
 }

 /// calloc() wrapper
```

**Comment by elmart** [comment]
Sorry, I'm away from my computer now. Yes, I can test it. Will do when I get back home.  Thanks.

**Comment by tarruda** [comment]
I've added the commit to #2421, if you confirm it fixes I will merge it

**Comment by oni-link** [comment]
Did not see any calls to `xfree()` in the coverity report, so I would be suprised, if the patch would help.
This is the first warning in the coverity report. 
```c
*** CID 109014:    (FORWARD_NULL)
/src/nvim/eval.c: 907 in eval_to_string()
901       else {
902         if (convert && tv.v_type == VAR_LIST) {
903           ga_init(&ga, (int)sizeof(char), 80);
904           if (tv.vval.v_list != NULL) {
905             list_join(&ga, tv.vval.v_list, (char_u *)"\n", TRUE, 0);
906             if (tv.vval.v_list->lv_len > 0)
>>>     CID 109014:    (FORWARD_NULL)
>>>     Passing "&ga" to "ga_append", which dereferences null "ga.ga_data".
907               ga_append(&ga, NL);
908           }
909           ga_append(&ga, NUL);
910           retval = (char_u *)ga.ga_data;
911         } else if (convert && tv.v_type == VAR_FLOAT) {
912           vim_snprintf((char *)numbuf, NUMBUFLEN, "%g", tv.vval.v_float);
/src/nvim/eval.c: 909 in eval_to_string()
903           ga_init(&ga, (int)sizeof(char), 80);
904           if (tv.vval.v_list != NULL) {
905             list_join(&ga, tv.vval.v_list, (char_u *)"\n", TRUE, 0);
906             if (tv.vval.v_list->lv_len > 0)
907               ga_append(&ga, NL);
908           }
>>>     CID 109014:    (FORWARD_NULL)
>>>     Passing "&ga" to "ga_append", which dereferences null "ga.ga_data".
909           ga_append(&ga, NUL);
910           retval = (char_u *)ga.ga_data;
911         } else if (convert && tv.v_type == VAR_FLOAT) {
912           vim_snprintf((char *)numbuf, NUMBUFLEN, "%g", tv.vval.v_float);
913           retval = vim_strsave(numbuf);
914         } else

```
If we follow the function calls for `ga_append()`, we end up at a call `xrealloc(...)` that uses `gap->ga_data`. At this point `gap->ga_data` should be assigned a `NONNULL` value. So I would assume coverity has some problems with the use of `je_realloc()`, if it has anything to do with jemalloc.

**Comment by tarruda** [comment]
> If we follow the function calls for ga_append(), we end up at a call xrealloc(...) that uses gap->ga_data. At this point gap->ga_data should be assigned a NONNULL value. So I would assume coverity has some problems with the use of je_realloc(), if it has anything to do with jemalloc.

makes sense, maybe if we je_realloc is marked wtih FUNC_ATTR_NONNULL_RET?

**Comment by tarruda** [comment]
Actually, this one might fix it:

```diff
diff --git a/src/nvim/memory.c b/src/nvim/memory.c
index 2d4259a..ae3c4f9 100644
--- a/src/nvim/memory.c
+++ b/src/nvim/memory.c
@@ -22,7 +22,7 @@
 #include "jemalloc/jemalloc.h"
 #define malloc(size) je_malloc(size)
 #define calloc(count, size) je_calloc(count, size)
-#define realloc(ptr, size) je_realloc(ptr, size)
+#define realloc(ptr, size) (ptr != NULL ? je_realloc(ptr, size) : je_malloc(size))
 #define free(ptr) je_free(ptr)
 #endif
```

**Comment by elmart** [comment]
> makes sense, maybe if we je_realloc is marked wtih FUNC_ATTR_NONNULL_RET?

`xrealloc` is already marked that way and it's not working.
Coverity is not taking function attributes into account.

So, I think the problem is that Coverity doesn't know that je_malloc and family are malloc and family substitutes. That can be solved by adding function models to coverity project. I can't do it right now, but I'll do it soon. I've already added models before.

**Comment by elmart** [comment]
Also, sorry for not having looked into proposed fix more carefully. As I said, I was away from my computer. Now that I've looked a bit at it, I do agree with @oni-link that problem seems to be in not detecting allocation, and not in freeing.

BTW, doesn't je_free() accept NULL, as free does? It could pose other problems if not.

**Comment by tarruda** [comment]
> BTW, doesn't je_free() accept NULL, as free does? It could pose other problems if not.

It does accept, I proposed that patch because I assumed coverity would report error when passing NULL to a unknown function

**Comment by elmart** [comment]
Ok, they were 18 new defects that were introduced when changing to je_malloc.
I've just uploaded a model file teaching coverity about je_malloc functions being equivalent to malloc ones.
17 defects haven been eliminated by doing that.
So, I still have to find which one is the missing one, and why, but I will include solution for that in my next regular coverity fixes batch.
So, closing this.
