### ISSUE TITLE
Weird graphic glitch on small terminals

### ISSUE THREAD

**Issue by CarloCattano** [neovim/neovim#24239]
### Problem

When the window that contains the terminal with nvim is not bigger than say , half of the screen.
It opens and looks correct, but as soon as you scroll you get weird graphical artifacts.

It only restores once you resize the window 

<details>
<summary>screenshots</summary>

![20230703_13h19m14s_grim](https://github.com/neovim/neovim/assets/17380530/087ccee5-f8e7-46aa-b7fc-fdb2e86f7c33)

![20230703_13h19m31s_grim](https://github.com/neovim/neovim/assets/17380530/30bc83dd-ae10-4924-9819-c229cede2bb8)

![20230703_13h19m37s_grim](https://github.com/neovim/neovim/assets/17380530/01044ad3-430f-44be-9ec4-f8de15fce407)

</details>

### Steps to reproduce

open nvim on a terminal
scroll down on the document
It stays on an infinite glitch until you resize

### Expected behavior

No glitch

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux arch 6.3.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.12.2 (9d9982df) , kitty 0.28.1

### $TERM environment variable

alacritty

### Installation

pacman

**Comment by zeertzjq** [comment]
May be a data race.

**Comment by zeertzjq** [comment]
May be a data race. What does "open nvim on a terminal" exactly refer to? Are the terminal are Nvim opened at the same time, or is Nvim opened in a shell?

**Comment by CarloCattano** [comment]
> What does "open nvim on a terminal" 
open alacritty and type nvim file.sh

Here a video 
![screen](https://github.com/neovim/neovim/assets/17380530/30072e8e-c035-41e4-96be-5fdadfcd19bb)

**Comment by zeertzjq** [comment]
> It stays on an infinite glitch until you resize

Is scrolling also fine after resizing the terminal?

**Comment by CarloCattano** [comment]
Yes after a hit of resize or fullscreen everything works normal

**Comment by kohane27** [comment]
I also have the same issue:

https://github.com/neovim/neovim/assets/57322459/74c679bc-4e34-428b-a188-7c7f2ce0597c

NVIM v0.9.1

System info:

Kernel: Linux 6.1.37-1-lts
Uptime: 2 hours, 55 mins
WM: sway
CPU: AMD Ryzen 7 PRO 5850U with Radeon Graphics (16) @ 1.900GHz
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series

Any input is much appreciated. Thank you.

**Comment by TaylorTrz** [comment]
Same issue seems happened to me...
After I open nvim on windows terminal, resize terminal will cause neovim tui into wired behavior.

**Comment by zeertzjq** [comment]
Does this bug still exist in v0.9.2?

**Comment by TaylorTrz** [comment]
> Does this bug still exist in v0.9.2 or nightly?

Yes, I just tried to build on tag v0.9.2:
```
git checkout v0.9.2
make CMAKE_BUILD_TYPE=RelWithDebInfo
```

And the bug was gone, thanks to your work.

**Comment by CarloCattano** [comment]
It's pretty wild. Very annoying and happening on a variety of different
systems.
Not sure how it didn't get much attention or more people reporting it

**Comment by CarloCattano** [comment]
Just built 
```
NVIM v0.10.0-dev-1117+gbe10d65bfa
Build type: RelWithDebInfo
LuaJIT 2.1.1694285958
```

Bug is still present , even when on fullscreen. Here I start nvim and there is already a missing right side

![image](https://github.com/neovim/neovim/assets/17380530/0bc1a4ea-8fb7-495d-aa62-9a9dcb69df97)

Until I resize or change the zoom level , or any other graphic update trigger, it wont occupy the entire console screen

**Comment by CarloCattano** [comment]
And then the terminal is half the size of this one , the scrolling bug is still present as well

**Comment by CarloCattano** [comment]
Still present

**Comment by justinmk** [comment]
Did you try CTRL-L or `:clear` ?

**Comment by CarloCattano** [comment]
Interestingly , your suggestion show cases 3 different cases when experimenting on it @justinmk 
So :clear just sets the cursor on top but nothing really changes
![image](https://github.com/neovim/neovim/assets/17380530/18d72210-45d5-4b45-b38b-dbee432e3af8)

CTRL + L does the job ... _partially_ and the background takes its place ,  but the status bar doesn't
![image](https://github.com/neovim/neovim/assets/17380530/eaecc052-59af-4c80-9933-379bec80bb40)

And finally , with a fullscreen or resizing event the *normal* screen
![image](https://github.com/neovim/neovim/assets/17380530/f8152a13-f650-481c-81ab-511c24e703d3)

**Comment by CarloCattano** [comment]
Its auto-magically gone , closing
