### ISSUE TITLE
Tnoremap doesn't execute <plug> commands

### ISSUE THREAD

**Issue by hoschi** [neovim/neovim#2423]
I try to replace some tmux panes with these new terminal buffers and it works really nice. But I don't get new 't' version of the mapping commands to work. I tried to remap some commands, so I can use the same keys to trigger a plugin command with the same binding, in normal or terminal mode:

```
nm <c-e>      <plug>(dwm_cursor_clockwise)
tnoremap <C-e> <C-\><C-n><plug>(dwm_cursor_clockwise)
```

But this only works on the second press of <c-e> ... on the first press in a terminal buffer the cursor jumps on the bottom line but isn't really in normal mode, see screenshot: 
![2015-04-13-192705_1714x1409_scrot](https://cloud.githubusercontent.com/assets/163128/7121213/2ead3d88-e213-11e4-9d91-05b49229b10e.png)

After a second or so the red rectange is correctly placed and I'm in normal mode, but `<plug>(dwm_cursor_clockwise)` wasn't executed: 
![2015-04-13-192925_1714x1409_scrot](https://cloud.githubusercontent.com/assets/163128/7121240/69662ade-e213-11e4-8099-9eab7020b147.png)

I'm on Arch Linux and my neovim versin is
NVIM 0.0.0-alpha+201504110910 (compiled Apr 11 2015 18:51:26)
Commit: 8171fc4cbc9cfe368bca7a7e711e198b976bf4f7

**Comment by justinmk** [comment]
That's by design, neither with `nnoremap` and friends. This is because `<Plug>Foo` is itself a mapping. So you must use the non-`nore` variants:

    tmap foo <Plug>bar
    nmap foo <Plug>bar
    ...

**Comment by hoschi** [comment]
Ahhh, thanks this worked!
