### ISSUE TITLE
list/complete directory named with brackets [...]

### ISSUE THREAD

**Issue by kai-patel** [neovim/neovim#24233]
### Problem

In the following directory structure:

```
F:.
│   +layout.svelte
│   +page.svelte
│
├───home
│       +page.svelte
│
├───people
│   │   +page.svelte
│   │   +page.ts
│   │
│   └───[id]
│           +page.svelte
│           +page.ts
│
└───reports
        +page.svelte
```

Neovim fails to recognize that `[id]/+page.svelte` and `[id]/+page.ts` exist. These files *can* be accessed by supplying the exact path to `:e`, but autocomplete on the command fails as soon as `[id]` is reached. If the folder is opened via `netrw`, no files are shown. This issue may be connected to #19976.

### Steps

1. Create a directory structure including a folder named `[...]`
2. Launch Neovim from any point in the structure with `nvim --clean` for factory-config
3. Open the files via `:e <insert path to folder>/` and then attempt to autocomplete
4. Attempt viewing the contents of the `[...]` folder via a file explorer e.g. `netrw` using `:Explore` (if `nvim` launched with `NERDTree` installed, confirm that both explorers agree)

### Expected behavior

Expected behaviour would include autocomplete showing the files inside `[...]`, and file explorer plugins also showing the files

### Neovim version (nvim -v)

NVIM v0.9.1, also failed on v0.7.2

### Vim (not Nvim) behaves the same?

Yes, vim 9.0 (2022 Jun 28)

### Operating system/version

Windows 10 Pro: Version 10.0.19045 Build 19045

### Terminal name/version

Windows Terminal 1.17.11461.0

### $TERM environment variable

N/A

### Installation

chocolatey

**Comment by zeertzjq** [comment]
The docs is a bit unclear. It's mentioned in `:h wildcard` that `[abc]` is a wildcard in cmdline completion:
```
						*wildcard* *wildcards*
Wildcards in {file} are expanded, but as with file completion, 'wildignore'
and 'suffixes' apply.  Which wildcards are supported depends on the system.
These are the common ones:
	`?`	matches one character
	`*`	matches anything, including nothing
	`**`	matches anything, including nothing, recurses into directories
	[abc]	match 'a', 'b' or 'c'
```
But it isn't mentioned here:
```
The 'wildchar' option defaults to <Tab> (CTRL-E when in Vi compatible mode; in
a previous version <Esc> was used).  In the pattern standard wildcards "*" and
'?' are accepted when matching file names.  "*" matches any string, '?'
matches exactly one character.
```

Problems with netrw should be reported to Vim.

**Comment by kai-patel** [comment]
I've opened an issue for Vim (vim/vim#12629), referencing this issue. Unsure whether or not to close this issue pending a response on the Vim issue.

**Comment by kai-patel** [comment]
I came up with a fix for this for `NERDTree` (PR nerdtree/nerdtree#1359, commit https://github.com/preservim/nerdtree/pull/1359/commits/3c305a0f28dbfd447b91d8509c40385a937f6d22).

By default `isfname` contains square brackets and curly-braces, which is correct. The issue is that square brackets are still treated as a wildcard pattern for any expr passed to `glob()` - at least on Windows. This specific bug occurs even if `isfname` is set correctly. The linked PR contains a quote from the docs about this same issue.

**Comment by Rossvold** [comment]
@kai-patel This is only reproducable for me using a windows terminal. If i use WSL the issue goes away.
Not really a fix to not use windows but it's the only way i got it to work for my sveltekit application.

**Comment by romeovs** [comment]
I can reproduce this on an Mac too.

**Comment by lllama** [comment]
@lsvmello could this issue be similar to the one you fixed with #25424 ?

**Comment by zeertzjq** [comment]
This has been documented as of #26484

**Comment by lllama** [comment]
For any fellow SvelteKit users on Windows, I've bodged a fix on my local install. I've put details here: https://github.com/vim/vim/issues/12629#issuecomment-1937596309

**Comment by Koliras** [comment]
Had the same problem with Next.js. Couldn't find a solution, so as an experiment, I tried to run NeoVim in WSL terminal, and it worked perfectly fine. I had Ubuntu installed as WSL, but I don't think it works only on Ubuntu, so you may try some other distro
