### ISSUE TITLE
hash the cache key in vim.treesitter.query.parse() to save some memory

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#24235]
### Problem

hi folks, while reading through a pr about adding cache to treesitter.query.get(), i noticed that the [.parse()](https://github.com/neovim/neovim/blob/4fd852b8cb88ed035203d3f9ae2e6a8258244974/runtime/lua/vim/treesitter/query.lua#L269) uses the `query_string` as the cache key which could be long (as it may contain the content of several `.scm` files) and will not be visible/usable for other purposes.

### Expected behavior

so maybe it's worth to shorten the cache key to save some memory, and of course it comes with more cpu load if a hash function is being used.
as i dont know how frenquently `.parse()` will be called and how long the query_string will be and can not figure out an easy way to verify it, so feel free to close.

**Comment by lucario387** [comment]
The root id can be used instead of the whole query_string, I think :thinking: , as it should be unique

**Comment by justinmk** [comment]
Hashing can make troubleshooting/debugging less obvious. Also not sure this is worth the indirection.

If the root id can be used, no objection there.

**Comment by lewis6991** [comment]
PR's welcome if they can prove to provide benefit, otherwise there are no plans to do this.
