### ISSUE TITLE
getreg("+") disagrees with :registers

### ISSUE THREAD

**Issue by hemantgouni** [neovim/neovim#24257]
### Problem

This is motivated by a possible bug in how `getreg` works. Running the following vimscript demonstrates the issue (you'll need wl-copy or an analogous tool):

```vim
" this comment will be copied into both registers
call system("wl-copy --primary --clear && wl-copy --clear")
normal! "+yy
let primary = getreg("*")
let clipboard = getreg("+")
echo "*: " primary
echo "+: " clipboard
registers
```

The output of `getreg` disagrees with the output of `:registers`. After the clipboard is cleared by an external tool and text is copied into `"+`, the same text appears to have been copied into `"*`, as well. This also works the other way around, if `normal! "+yy` is replaced by `normal! "*yy`. I'm not sure if this is the intended behavior or not, but it would be nice to have a Lua API function for working with registers that coincides with the output of `:registers`.

Screenshot of the script's output:

![](https://github-production-user-asset-6210df.s3.amazonaws.com/68922389/251020382-d76d7240-8018-4e00-82e5-bd8b94ead26c.png)

`"*` is not present in `:registers`, as expected.

### Expected behavior

`"*` should be empty. It would be convenient to have something in the Lua API that makes this apparent.

This happens on Neovim version 0.9.1. I'm using Sway on NixOS. The terminal emulator is `foot 1.14.0`. `$TERM = foot`.

**Comment by zeertzjq** [comment]
What Wayland compositor are you using?

**Comment by hemantgouni** [comment]
Sway version 1.8.1, from nixpkgs unstable

**Comment by justinmk** [comment]
What does this have to do with a "Lua API"? There is already `vim.fn.*` which allows Lua access to all vimscript functions (we aren't going to duplicate them).

**Comment by hemantgouni** [comment]
I wasn't sure if this was intended behavior or not for `getreg`-- if so, adding a function to the Lua API with saner behavior might've been an option. But this does look like a bug, so that's not relevant anymore :)

**Comment by m4xshen** [comment]
At the [line 832 of /src/nvim/ops.c](https://github.com/neovim/neovim/blob/8c9e37cc09f5b79a981c574ab8bcfb0b9ed58ca8/src/nvim/ops.c#L832) there is a comment:
```c
...
  } else if (mode != YREG_YANK
             && (regname == 0 || regname == '"' || regname == '*' || regname == '+')
             && y_previous != NULL) {
    // in case clipboard not available, paste from previous used register
    return y_previous;
  }
...
```
I think this is why the `*` register has the same content of `+` because it is the previous used register.

**Comment by m4xshen** [comment]
I tried to fix it with the following code:
```c
...
  } else if (mode != YREG_YANK
             && (regname == 0 || regname == '"' || regname == '*' || regname == '+')
             && y_previous != NULL) {
    // in case clipboard not available, return a register with empty content
    *reg = *y_previous;
    reg->y_array = NULL;
    reg->y_size = 0;
    return reg;
  }
...
```

I want to return a register with empty content, but my code doesn't work. Can anyone tell me which part went wrong? It's my first time touching the Neovim source code. Any explanation would be greatly appreciated!

**Comment by zeertzjq** [comment]
"paste from previous used register" shouldn't be changed. But something different needs to be done when not actually pasting.
