### ISSUE TITLE
No breaking change note about stricter type checking for options

### ISSUE THREAD

**Issue by strokirk** [neovim/neovim#24250]
### Problem

Since commit e8b3ed74bca4bd6ececcc240f816451bef7fd58c, there is stricter validation of the options set via `vim.o`. 

For example, setting `vim.o.textwidth = "120"` gives you this error:

> ```E5113: Error while calling lua chunk: /Users/danstrokirk/.config/nvim/lua/config/settings.lua:8: Invalid value for option 'textwidth': expected Number, got String "120"```

The related code is here:
https://github.com/neovim/neovim/blob/e8b3ed74bca4bd6ececcc240f816451bef7fd58c/src/nvim/option.c#L3726

### Steps to reproduce

nvim -u NORC --cmd 'lua vim.o.textwidth = "12"'

### Expected behavior

I'm not opposed to this stricter validation, and rewriting my config file was pretty fast, but I was confused about this change at first and tried reading about it in `:help news`. Adding a note about breaking changes for this would be very useful.

It's likely many users are relying on the string coercion behaviour in their config files, so possibly it might make sense to keep some sort of type conversion from strings, but I'm not sure about that, it's not _too_ difficult to update. The only issue might be if seldomly maintained plugins are relying on the old functionality.

(I'm also partly writing this issue for anyone that experiences the same error and is confused from where it came!)

### Neovim version (nvim -v)

e8b3ed74bca4bd6ececcc240f816451bef7fd58c

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

Homebrew + build from repo to bisect

**Comment by strokirk** [comment]
@clason Even a bugfix can introduce breaking changes! Especially if people rely in the unintended behaviour.

**Comment by clason** [comment]
My point is that `news` is reserved for _intentional_ breaking changes. Unintended breaking changes are just bugs that need to be fixed instead of documented.

**Comment by strokirk** [comment]
@clason I think I understand what you mean, but I'm not sure. 

My point is simply that this change will likely cause a bunch of people to have to fix their old string-based configs.

I'm personally already done fixing mine, so I'm perfectly content with this Github issue being the only documentation for anyone searching for the error message, if you decide it's not `news`-worthy. :)

**Comment by zeertzjq** [comment]
How didn't you get an error previously? In v0.9.1 I get the error `E5108: Error executing lua [string ":lua"]:1: Vim:E521: Number required: &textwidth = '120'`.
