### ISSUE TITLE
Windows: Neovim does not load init.lua

### ISSUE THREAD

**Issue by Mazrog** [neovim/neovim#24254]
### Problem

Hi,

I am on Windows 10, installed NeoVim from scoop, version 0.9.1.

I cannot seem to have neovim load my config file init.lua.

Inside of my %localappdata%, I have created "nvim/init.lua", containing just `print("hello")`, but when starting nvim, this simple message does not show.

I looked at the `:help init`, and it showed me that it should be loading it:
```
The config file is located at:
Unix			~/.config/nvim/init.vim		(or init.lua)
Windows			~/AppData/Local/nvim/init.vim	(or init.lua)
|$XDG_CONFIG_HOME|	$XDG_CONFIG_HOME/nvim/init.vim	(or init.lua)
```

Here is the :checkhealth for my nvim, when it comes to the config file part.
```
nvim: require("nvim.health").check()

Configuration ~
- WARNING Missing user config file: $HOME\nvim/init.vim
  - ADVICE:
    - :help |init.vim
```

The $HOME variable resolves to my user folder, so not the app data one, but same behavior there, not loading the init.lua file if I put it inside.

Also weird, the $HOME variable does not resolve to the same path, if launched from the terminal (powershell), or from `:echo $HOME` inside nvim.

So right now, I have three potential paths as where to put the configuration, but none of the them works completely.
Inside of the nvim $HOME, it manages to load my colortheme and some installed plugins, but it does not execute my code with settings nor remaps.

And the other two are just not considered at all (back  to basic black&white vanilla theme).

Would you have any idea on what is happening?

### Steps to reproduce

Tried and looked:

:scriptnames (does not show a path with an init.lua file)
nvim -V (does not show a path with an init.lua file)
nvim --startuptime (does not show a path with an init.lua file)

### Expected behavior

See my configuration be loaded.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

do not have vim installed

### Operating system/version

Windows 10

### Terminal name/version

Powershell

### $TERM environment variable

Powershell

### Installation

scoop

**Comment by justinmk** [comment]
> Here is the :checkhealth for my nvim, when it comes to the config file part.
> 
> ```
> nvim: require("nvim.health").check()
> 
> Configuration ~
> - WARNING Missing user config file: $HOME\nvim/init.vim
> ```

Is $MYVIMRC set? That is checked by checkhealth: https://github.com/neovim/neovim/blob/5f442e1a4a831ed2eb70d5c2dd66c47b0b8aa7e1/runtime/lua/nvim/health.lua#L58

What does `:echo stdpath('config')` say?

**Comment by Mazrog** [comment]
> Is $MYVIMRC set? That is checked by checkhealth: 

No it is not, `:echo $MYVIMRC` does not output anything.

`:echo stdpath('config')`
Ah, I forgot to mention it, but I looked at it as well in my investigation, it ouputs `$HOME\nvim`.

`$HOME` in powershell gives my windows user dir, ie `C:\users\<me>`
but `:echo $HOME` within nvim gives `D:\home`, which was an env variable I set up at one point (maybe related to some WSL tool that needed a $HOME variable to work).

**Comment by justinmk** [comment]
> (maybe related to some WSL tool that needed a $HOME variable to work).

So this is on WSL?

**Comment by Mazrog** [comment]
No, I run everything within Powershell. Installation was done with scoop and my terminal is Windows Powershell.

**Comment by justinmk** [comment]
> `:echo $HOME` within nvim gives `D:\home`, which was an env variable I set up at one point

Did you try unsetting it? Setting $HOME to nonsense will break vim/nvim.

**Comment by Mazrog** [comment]
Ok, that seems to have fixed the issue, now it loads the config I put into %localappdata%.
Even `:echo stdpath('config')` points to this folder now.

Thank you for your help! :)

To be honest, setting a custom `$HOME` as windows does not quite have one, did not seem "nonsense" but it must have broken stuff inside as you said.

**Comment by justinmk** [comment]
> `:echo stdpath('config')`
> Ah, I forgot to mention it, but I looked at it as well in my investigation, it ouputs `$HOME\nvim`.

I don't quite understand that. Maybe Nvim needs to handle custom `$HOME` on Windows better.

But it's also a logical contradiction to set `$HOME` but not set `$LOCALAPPDATA`, `$USERPROFILE`, etc. They all are closely related and if they conflict then apps can't guess what you want.
