### ISSUE TITLE
vim.fn.split() misses newlines while special characters are present

### ISSUE THREAD

**Issue by hemantgouni** [neovim/neovim#24251]
### Problem

[Test files necessary for reproduction here.](https://github.com/neovim/neovim/files/11949514/neovim.zip)

test_file contains a bunch of bytes. It has five lines, as shown by the output of `cat` here. 

```
0 ~/wgs/bug-reports/neovim-1 cat -vET test_file 
M-aM-+M-^E$
M-aM-+M-^E$
M-aM-+M-^E$
M-aM-+M-^E$
M-aM-+M-^E$
```

When I attempt to split the file by line using `vim.fn.split`, however, these newlines appear to be skipped.

```
0 ~/wgs/bug-reports/neovim-1 nvim -l test.lua
{ "᫅\n᫅\n᫅\n᫅\n᫅" }
```

The contents of test.lua is pretty simple, reading the file in as a string and using split() on it:

```lua
local test_file_contents = vim.fn.system("cat test_file")
local split_result = vim.fn.split(test_file_contents, "\n")
vim.print(split_result)
```

### Steps to reproduce

Open the zip file provided. Run test.lua as done above. Observe that the resulting lua array contains only a single entry, where it should instead contain five.

### Expected behavior

The resulting array should have five entries (one for each line).

### Neovim version (nvim -v)

v0.9.1, release build

### Vim (not Nvim) behaves the same?

Possibly, not sure. Vim and Neovim behave the same with the vimscript test script ({n,}vim +source test.vim), but the incorrect result is clearer when pretty printing via lua. Vim version: 9.0.

### Operating system/version

NixOS 23.11 (unstable)

### Terminal name/version

foot 1.14.0 +pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Installation

nixpkgs

**Comment by justinmk** [comment]
Did you try `vim.split()` (pure-Lua alternative)?

Fixing vimscript bugs is not something we should spend time on, though we should continue to merge patches.

**Comment by zeertzjq** [comment]
This is how composing characters work in Vim regexp. You can use `\%C` to skip composing characters.
```lua
local test_file_contents = vim.fn.system("cat test_file")
local split_result = vim.fn.split(test_file_contents, "\n\\ze\\%C")
vim.print(split_result)
```

See `:h patterns-compsing`

**Comment by hemantgouni** [comment]
Ah okay-- thanks for clarifying!

**Comment by lewis6991** [comment]
vimscript doesn't handle non-utf-8 strings so it will never work for the given input and thus isn't a bug but just a limitation of `vim.fn`
