### ISSUE TITLE
Build failure on Ubuntu 20.04

### ISSUE THREAD

**Issue by dllu** [neovim/neovim#24265]
### Problem

On a clean Ubuntu 20.04 machine, building results in:

```
/home/dllu/proj/neovim/src/nvim/message.c: In function ‘msg_puts_display.constprop’:
/home/dllu/proj/neovim/src/nvim/message.c:2166:18: warning: ‘strnlen’ specified bound 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
 2166 |     size_t len = strnlen(str, (size_t)maxlen);  // -V781
      |                  ^
/usr/bin/ld: /tmp/nvim.nYFVHZ.ltrans41.ltrans.o: in function `tree_get_ranges.lto_priv.0':
<artificial>:(.text+0x43d8): undefined reference to `ts_tree_included_ranges'
collect2: error: ld returned 1 exit status
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:4838: bin/nvim] Error 1
make[1]: *** [CMakeFiles/Makefile2:861: src/nvim/CMakeFiles/nvim.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

### Steps to reproduce

* on clean ubuntu 20.04 installation
* clone the repo (on master commit `1de82e16c1216e1dbe22cf7a8ec9ea9e9e69b631`)
* mkdir build
* cmake .. -DCMAKE_BUILD_TYPE=Release
* make

### Expected behavior

Expected behavior: Builds.

Actual behavior: see logs
[wtf.log](https://github.com/neovim/neovim/files/11960849/wtf.log)

### Neovim version (nvim -v)

1de82e16c1216e1dbe22cf7a8ec9ea9e9e69b631

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ubuntu 20.04

### Terminal name/version

alacritty 0.12.2

### $TERM environment variable

alacritty

### Installation

build from repo

**Comment by ii14** [comment]
The actual error comes from treesitter. The dependencies might be out of date, try to clean them with `make distclean` (or `rm -rf .deps`) in the root directory (not the build directory).

**Comment by dundargoc** [comment]
You didn't build the dependencies lol. Look at wiki under Build (or just lool at the readme) for the correct way to install.

**Comment by justinmk** [comment]
using `cmake .. -DCMAKE_BUILD_TYPE=Release` and then `build` does look suspicious.

**Comment by dllu** [comment]
I mean I literally installed the dependencies for Ubuntu listed in https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites and then built it (although I used Release instead of RelWithDebInfo)...

**Comment by clason** [comment]
Those are the _build_ dependencies (i.e., the tools needed to build Neovim). Neovim itself has different libraries ("third-party dependencies") it depends on (such as LibUV, tree-sitter, etc.), which by default are compiled during the build process and then linked into the `nvim` binary, see https://github.com/neovim/neovim/wiki/Building-Neovim#third-party-dependencies

It's these that you failed to build.

**Comment by dllu** [comment]
oh ok. Sorry I can't read...
