### ISSUE TITLE
nvim-treesitter.lua error on last nvim version 

### ISSUE THREAD

**Issue by ynhhoJ** [neovim/neovim#24275]
### Problem

After updating to the latest 0.10.0~dev.616.g203181234-500 version of nevoim, when i open any file, appears this error::

```
Failed to source `/home/ynhhoj/.local/share/nvim/lazy/nvim-treesitter/plugin/nvim-treesitter.lua`

vim/_editor.lua:0: BufReadPost Autocommands for "*"..script nvim_exec2() called at BufReadPost Autocommands for "*":0../home/ynhhoj/.local/share/nvim/lazy/nvim-treesitter/plugin/nvim-treesitter.lua: Vim(source):E5113: Error while calling lua chunk: /usr/share/nvim/runtime/lua/vim/tre
esitter/query.lua:609: Overriding trim!
stack traceback:
^I[C]: in function 'error'
^I/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:609: in function 'add_directive'
^I...nvim-treesitter/lua/nvim-treesitter/query_predicates.lua:252: in main chunk
^I[C]: in function 'require'
^I.../share/nvim/lazy/nvim-treesitter/lua/nvim-treesitter.lua:8: in main chunk
^I[C]: in function 'require'
^I...are/nvim/lazy/nvim-treesitter/plugin/nvim-treesitter.lua:9: in main chunk
^I[C]: in function 'nvim_exec2'
^Ivim/_editor.lua: in function 'cmd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:473: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:472>
^I[C]: in function 'xpcall'
^I.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:110: in function 'try'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:472: in function 'source'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:431: in function 'source_runtime'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:399: in function 'packadd'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:335: in function '_load'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:184: in function 'load'
^I...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:54: in function 'load'
^I/home/ynhhoj/.config/nvim/lua/core/utils.lua:111: in function </home/ynhhoj/.config/nvim/lua/core/utils.lua:93>

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - ~/.config/nvim/lua/core/utils.lua:111
  - 
  ```

This error start appear on 0.10.0~dev.616.g203181234-500 update and i really don't know this is a NvChad (https://github.com/NvChad/NvChad/issues/2179), neovim or a treesitter problem :(
On 606 dev version everything is working good.

- 616: https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/build/6133667/
- 606: https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/build/6131945/

Versions list: https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/package/neovim/

### Steps to reproduce

1. Install last version of nvim
2. Install nvchad
3. Open any file

P.S: Without `.config/nvim`, neovim does not show any error and opens files as always. 
Also i tried to remove all files in ~/.local/share/nvim and reinstall all dependencies again and problem still remain...

### Expected behavior

Files should be opened without any errors

### Neovim version (nvim -v)

v0.10.0-dev+638-g4e34ca8ae

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Fedora 38

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

COPR, agriffis/neovim-nightly

**Comment by lucario387** [comment]
It's already patched since last week with https://github.com/nvim-treesitter/nvim-treesitter/commit/58d4b924ebec182ac76f81f99966eb13a1d87eff

**Comment by ynhhoJ** [comment]
@lucario387 , thank you!

I checked `.local/share/nvim/lazy/nvim-treesitter` git logs and found that i was on commit from 20 may: https://github.com/nvim-treesitter/nvim-treesitter/commit/3d5fe8caf85ff1e18963b0c6ded1cf6d3a648ffa 

After upgrading to last versions with current commits, everything is ok!
