### ISSUE TITLE
BUG: Error opening file: vim/_editor.lua:0: nvim_exec2()..BufReadPost Autocommands for "*"

### ISSUE THREAD

**Issue by linrongbin16** [neovim/neovim#24284]
### Problem

When opening a file, there's an error:

```
[Neo-tree ERROR] Error opening file: vim/_editor.lua:0: nvim_exec2()..BufReadPost Autocommands for "*": Vim(lua):E5108: Error executing lua [string ":lua"]
```

![image](https://github.com/neovim/neovim/assets/6496887/0aae4fd1-7fab-4afa-908d-1e49c600badf)

The error is throwed when I'm using neo-tree.nvim plugin, but actually I think it maybe caused by `filetype.lua` plugin missing.

### Steps to reproduce

1. OS: ubuntu 22.04 LTS desktop x86_64 (running in Windows 10 x86_64).
2. install fuse by: `sudo apt install fuse`.
3. download nvim.appimage: v0.9.1 and install by: `chmod u+x nvim.appimage && mv nvim.appimage /usr/local/bin/nvim`.
4. install lazy.nvim and neo-tree.nvim plugin.
5. open nvim and open a file from neo-tree.

a minimum `init.lua`:

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
    -- Your config here
    -- ...
  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Expected behavior

Open file without any exception.

### Neovim version (nvim -v)

v0.9.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ubuntu 22.04 LTS desktop x86_64

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256

### Installation

https://github.com/neovim/neovim/releases/tag/v0.9.1

**Comment by lewis6991** [comment]
Looks like an issue with your installation. Otherwise it is an issue with one of your plugins.

Nothing here indicates a problem with Neovim.

**Comment by linrongbin16** [comment]
Sorry but I also tried to install nvim from [nvim-linux64.tar.gz](https://github.com/neovim/neovim/releases/tag/stable) provide from releases stable download link.

After `tar zxvf` it, I didn't found any `filetype.lua` file? where can I find this `filetype.lua` file in nvim package?

**Comment by linrongbin16** [comment]
I just re-installed a new ubuntu vm, and it works now
