### ISSUE TITLE
Tabstop is set to 8 when open .h files

### ISSUE THREAD

**Issue by Firestorck** [neovim/neovim#24288]
### Problem

Whenever setting tabstop to 4 and then opening a header file for C (`*.h`), tabstop is set back to 8, even when using an autocmd to set it back to 8.

as seen in previous issue #3786, general language recommendation shouldn't override user settings.

### Steps to reproduce

in my `init.lua`
```lua
vim.api.nvim_create_autocmd({ 'BufNewFile', 'BufRead' }, {
  pattern = '*',
  command = 'lua Colors()',
})
```

in my `Colors.lua` (which is required and works on other filetypes)
```lua
function Colors(color)
	color = color or "rose-pine"
	vim.cmd.colorscheme(color)

	vim.api.nvim_set_hl(0, "Normal", { bg = "None" })
	vim.api.nvim_set_hl(0, "NormalFloat", { bg = "None" })
	vim.api.nvim_set_hl(0, "GitSignsAdd", { bg = "None" })
	vim.api.nvim_set_hl(0, "GitSignsChange", { bg = "None" })
	vim.api.nvim_set_hl(0, "GitSignsDelete", { bg = "None" })
	vim.api.nvim_set_hl(0, "SignColumn", { bg = "None" })
	-- vim.cmd('hi Normal guibg=NONE ctermbg=NONE')
	-- vim.cmd('hi EndOfBuffer guibg=NONE')
end

Colors()
```

Then just open a .h file directly or though `:Ex` and tabstop will be set to 8.

### Expected behavior

Tabstop shouldn't be overriden by neovim upon opening a file, and should be at 4 upon opening a `.h` file

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

No, vim using simply the `set ts=4 sts=4 sw=4 noexpandtab autoindent` does not have the same issue

### Operating system/version

archlinux - 6.3.9

### Terminal name/version

Alacritty

### $TERM environment variable

tmux-256color

### Installation

pacman package manager

**Comment by seandewar** [comment]
With `nvim -V1`, what does `:verb set ts?` show?

**Comment by Firestorck** [comment]
When running `nvim -V1`, the output of `:ver set ts?` is
```
  tabstop=8
        Last set from ~/.local/share/nvim/site/pack/packer/start/vim-sleuth/plugin/sleuth.vim line 660
```
Seems like I got a plugin issue, this isn't the right place to report this!
Sorry for the trouble, and thanks for the help ^^
