### ISSUE TITLE
Neovim gets progressively slower and slower in insert mode

### ISSUE THREAD

**Issue by norcalli** [neovim/neovim#2428]
Over time, my neovim instance will take longer and longer to type characters in insert mode over the span of about 30 minutes. This seems like a relatively new problem (as of about 1-2 weeks ago). I am using it on Mac OS X, but mostly I was wondering if anyone else has noticed this problem, or if it's my .vimrc or a plugin causing problems.

**Comment by Hettomei** [comment]
Did you notice any change when running nvim without vimrc or plugin ?

```
nvim -u NONE
```

**Comment by justinmk** [comment]
@norcalli Please report:

```vim
au InsertChange
au InsertCharPre
au TextChanged
au TextChangedI
au CursorHold▫
au CursorHoldI▫
au CursorMoved▫
au CursorMovedI
```

**Comment by Pyrohh** [comment]
Closing, feel free to open if you have more information.
