### ISSUE TITLE
Some removed options are undocumented

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#24283]
### Problem

The following options have been removed from (or were never implemented in) Neovim, but their removal is not documented:
- completepopup
- keyprotocol
- previewpopup (this still appears in quickref.txt)
- printoptions

### Steps to reproduce

`:helpgrep` any of these options

### Expected behavior

Removal is documented

### Neovim version (nvim -v)

v0.10.0-dev-637+g2afb04758

**Comment by clason** [comment]
Why would they be documented if they were never implemented? Please check first.

**Comment by zeertzjq** [comment]
Being undocumented means it may be implemented in the future.

**Comment by lewis6991** [comment]
They were never implemented.

Remember Neovim is a fork.

**Comment by justinmk** [comment]
completepopup, previewpopup might be worth implementing. But not keyprotocol, printoptions. I'll update vim_diff.txt.

**Comment by ddickstein** [comment]
Yes by undocumented I meant they were also omitted from vim_diff.txt. I think options that aren't implemented but may be in the future should probably still be mentioned in vim_diff.txt.
