### ISSUE TITLE
Neovim freezed when opening a certain c header file

### ISSUE THREAD

**Issue by GangZhuo** [neovim/neovim#24299]
### Problem

Neovim is configured to use treesitter for code highlighting, and when opening [htable2.h](https://github.com/freeswitch/sofia-sip/blob/master/libsofia-sip-ua/su/sofia-sip/htable2.h), neovim freezed, and CPU usage is 100%. Other files are ok. I did a little research when calling [tree:register_cbs()](https://github.com/neovim/neovim/blob/fbeef0d4ef1aadc4e50b9f33946cf4dca8ca6b62/runtime/lua/vim/treesitter/highlighter.lua#L87) recursively, a dead loop occurs.

### Steps to reproduce

```
-- init.lua

-- Enable lua-loader that byte-compiles and caches lua files
vim.loader.enable()

require('packer').startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'

  use {
    'nvim-treesitter/nvim-treesitter',
    run = function()
      local ts_update = require('nvim-treesitter.install').update({ with_sync = true })
      ts_update()
    end,
    config = function()
      require("nvim-treesitter.configs").setup {
        ensure_installed = { "c", },
        ignore_install = {}, -- List of parsers to ignore installing
        -- Automatically install missing parsers when entering buffer
        auto_install = true,
        -- Install parsers synchronously (only applied to `ensure_installed`)
        sync_install = false,
        -- If you need to change the installation directory of the parsers (see -> Advanced Setup)
        parser_install_dir = nil,
        highlight = {
          enable = true, -- false will disable the whole extension
          additional_vim_regex_highlighting = false,
          disable = { 'help' }, -- list of language that will be disabled
        },
      }
    end,
  }
end)
```

Then

```
git clone https://github.com/freeswitch/sofia-sip.git
cd sofia-sip
nvim libsofia-sip-ua/su/sofia-sip/htable2.h # At this point, neovim freezed, and CPU usage is 100%
```

### Expected behavior

Can open the file normally.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-646+gc4df2f08b

### Vim (not Nvim) behaves the same?

Not test

### Operating system/version

Arch Linux updated as of 2023-07-09

### Terminal name/version

alacritty 0.12.2 (9d9982df)

### $TERM environment variable

tmux-256color

### Installation

Download from https://github.com/neovim/neovim/releases/tag/nightly

**Comment by clason** [comment]
This is an issue specific with nvim-treesitter's `cpp` injections. (Note that this file is recognized as `cpp`, not `c`.)

We are aware of performance issues around treesitter parsing and injections.

**Comment by GangZhuo** [comment]
I added the cpp parser and the problem still exists. So there is no solution to this problem?

**Comment by clason** [comment]
Remove the `preprocessor` injection query. (Search through previous issues on this very topic, both here and especially on nvim-treesitter, for details.)

**Comment by GangZhuo** [comment]
Thanks very much, I found https://github.com/neovim/neovim/issues/24171 using your keywords.
