### ISSUE TITLE
`vim.fn.getcompletion('','filetype')` will return empty table if `(` and `)` are added to `isfname`

### ISSUE THREAD

**Issue by cpkio** [neovim/neovim#24292]
### Problem

`vim.fn.getcompletion('','filetype')` will return empty table if `(` and `)` are added to `isfname`. If only `)` is added to `isfname`, you will get
```
E5108: Error executing lua Vim:E54: Unmatched \(
stack traceback:
        [C]: in function 'getcompletion'
        [string ":lua"]:1: in main chunk
```
after `lua=vim.fn.getcompletion('','filetype')`

### Steps to reproduce

* set `isfname = { '@','48-57','/','\\','.','-','_','+',',','#','$','%','{','}','[',']',':','@-@','!','~','=','(',')' }` in your bare neovim nightly
* do `lua=vim.fn.getcompletion('','filetype')`
* get your empty filetypes list

### Expected behavior

registered filetypes list 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-646+gc4df2f08b

### Vim (not Nvim) behaves the same?

no. VIM 9.0 (2022 Jun 28, compiled Jun 28 2022 12:30:17) MS-Windows 32-bit console version fresh from vim.org does not have this 

### Operating system/version

Windows

### Terminal name/version

ConEmu

### $TERM environment variable

nil

### Installation

manual

**Comment by clason** [comment]
Please check `getcompletion` directly (without going through `vim.fn`).

**Comment by cpkio** [comment]
@clason
`echo getcompletion('','filetype')` = `[]`
