### ISSUE TITLE
`:LspRestart` does not start pyright after it is stopped

### ISSUE THREAD

**Issue by denppa** [neovim/neovim#24300]
### Problem

I expect pyright to stop and start again after passing in the command `:LspRestart`, but pyright remains in a halted state after it has stopped. I have to run `:LspStart` to get it to start again.

### Steps to reproduce using "nvim -u minimal_init.lua"

Vanilla neovim seems to have this problem, no extra configs attached to pyright either.

### Expected behavior

pyright should start up after stopping.

### Neovim version (nvim -v)

0.9.1

### Language server name/version

pyright latest

### Operating system/version

macOS Ventura

**Comment by clason** [comment]
`LspRestart` is not provided by Neovim. You need to report this at the https://github.com/neovim/nvim-lspconfig repo.

**Comment by denppa** [comment]
Sorry about that guys, thanks for the info @clason, I will be closing this issue here.
