### ISSUE TITLE
needs nvim_win_get_hl_ns()

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#24309]
### Problem

hi folks, i have a need to get the `hl_ns` value of a window which is set by `nvim_win_set_hl_ns`, but i failed to find a way to do that.

my usecase is that: i have a `foo` plugin that creates floating window with custom `hl_ns` to show the content of a file systems, a `bar` plugin that highlights user-selected keywords and has a different flavor on highlights; so when i run `bar` on a window created by `foo`, i'll run into trouble on highlighting, there are two ways i'm aware of now:
* apply `bar`'s flavor to `foo`'s, and when `bar` finished restore it.
* replace the `hl_ns` from `foo` to `bar`, when `bar` finished restore it.
either way requires me knowing the `hl_ns` first.

yeah, there is another way: `foo` sets a special window-scoped variable to store it's `hl_ns` then `bar` can try to read it, but what if this `foo` is not under my control?

### Expected behavior

an api to get the `hl_ns` of a window.

**Comment by glepnir** [comment]
fixed by https://github.com/neovim/neovim/pull/25455
