### ISSUE TITLE
Toggling inlay hints stops working

### ISSUE THREAD

**Issue by MariaSolOs** [neovim/neovim#24305]
### Problem

I've configured inlay hints so that they're hidden when in insert mode. The toggling initially works, but after a few minutes of switching modes, the inlay hints stop hiding when entering insert mode.

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
-- The attach function I use in require('mason-lspconfig').setup_handlers
local on_attach = function(client, buf)
    -- Enable inlay hints if the client supports it.
    if client.server_capabilities.inlayHintProvider then
        local inlay_hints_group = vim.api.nvim_create_augroup('InlayHints', { clear = true })

        -- Initial inlay hint display.
        local mode = vim.api.nvim_get_mode().mode
        vim.lsp.inlay_hint(buf, mode == 'n' or mode == 'v')

        vim.api.nvim_create_autocmd('InsertEnter', {
            group = inlay_hints_group,
            buffer = buf,
            callback = function()
                vim.lsp.inlay_hint(buf, false)
            end,
        })
        vim.api.nvim_create_autocmd('InsertLeave', {
            group = inlay_hints_group,
            buffer = buf,
            callback = function()
                vim.lsp.inlay_hint(buf, true)
            end,
        })
    end
end
```

### Expected behavior

For inlay hints to hide when I'm on insert mode.

### Neovim version (nvim -v)

v0.10.0-dev-653+gfbeef0d4e

### Language server name/version

rust-analyzer 2023-07-10

### Operating system/version

Mac Ventura 13.4.1

**Comment by zeertzjq** [comment]
Does `:autocmd InlayHints InsertEnter` still show where you define this autocommand after toggling inlay hints stopped working?

**Comment by zeertzjq** [comment]
This happens because you used `clear = true` when creating the augroup, so only the autocommand for the last attached buffer remains. It should be `clear = false` instead.

**Comment by MariaSolOs** [comment]
Yep:

https://github.com/neovim/neovim/assets/62502207/d1357466-0322-41bb-99c4-07703fe3e05e

**Comment by MariaSolOs** [comment]
> This happens because you used `clear = true` when creating the augroup, so only the autocommand for the last attached buffer remains. It should be `clear = false` instead.

Oh. I'm sorry. I'm silly. Thank you for the quick reply!

**Comment by MariaSolOs** [comment]
@nyngwang maybe try attaching those autocommands to the buffer received in your LSP attach function. Kind of what I have in the description of this issue but inverting the toggling.

**Comment by nyngwang** [comment]
I tried that before(IIRC the answer was provided by the maintainer of lsp-saga, I just forgot their name), same result.
