### ISSUE TITLE
attempt to call a nil value on buf.inlay_hint

### ISSUE THREAD

**Issue by codeprefect** [neovim/neovim#24311]
### Problem

While trying out the newly added support for inlay_hints,

Calling `vim.lsp.buf.inlay_hint(bufnr, true)` throws `E5108`

### Steps to reproduce using "nvim -u minimal_init.lua"

- Open a file that attaches an lsp
- Call  `vim.lsp.buf.inlay_hint(bufnr, true)`

### Expected behavior

It should show inlay_hints if correctly configured, and otherwise do nothing.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-4683+g06694203e-Homebrew

### Language server name/version

omnisharp 1.39.7

### Operating system/version

MacOS Ventura (13.4.1 (22F82))

### Log file

https://gist.github.com/codeprefect/a4288d67a593a963b82627818a92a1f9#file-inlay_hint-lsp-log

**Comment by seandewar** [comment]
`vim.lsp.buf.inlay_hint` was moved to `vim.lsp.inlay_hint`.
