### ISSUE TITLE
After paste character gets displayed STILL

### ISSUE THREAD

**Issue by chriskisskiss** [neovim/neovim#24326]
### Problem

I can't believe this is still an issue...

connecting with iTerm2 on macos through ssh to newest ubuntu running a freshly installed nvim v0.6.1. When pasting text from system clipboard, a character gets displaced at the very end, which is a no-go IMO, especially when this issue was already addressed 1-2 years ago.
Does not happen in vim!

### Steps to reproduce

nvim --clean
paste text approx. 900 characters

### Expected behavior

should not displace character

### Neovim version (nvim -v)

0.6.1

### Vim (not Nvim) behaves the same?

VIM - Vi IMproved 8.2

### Operating system/version

ssh to Ubuntu 22.04.2 LTS from iTerm2 in macOS

### Terminal name/version

iTerm2 3.4.16

### $TERM environment variable

xterm-256color

### Installation

apt install

**Comment by clason** [comment]
It's "still" an issue because your Neovim version is years out of date. Please test the latest version (0.9.1 at time of writing).
