### ISSUE TITLE
High CPU consumption while talking to Haskell Language Server

### ISSUE THREAD

**Issue by tchoutri** [neovim/neovim#24325]
### Problem

Hi everyone, and thanks for making Neovim so nice!

I have been tracking down an increasing CPU consumption (more than 100% CPU) when nvim and its native lsp client are talking to the Haskell Language Server (HLS), the LSP server for the Haskell programming language.

In terms of UI, it's very sluggish, scrolling is incredibly painful. Here is a video: https://theophile.choutri.eu/slow_neovim_hls.webm

This behaviour appeared somewhere around the beginning of the week / last week, I think.

It's fairly cryptic to me because I tried to profile nvim with https://github.com/stevearc/profile.nvim and the resulting numbers are not that surprising? 

---

| Name | Wall duration (ms) | Avg Wall duration (ms) | Occurrences |
|:---:|:---:|:---:|:---:|
|  | 6839.051914 |  | 1153591 |
| vim.fs.normalize | 1106.377023 | 0.014352 | 77085 |
| lpeg.match | 1077.16991 | 0.018994 | 56709 |
| vim.shared.validate | 1046.771538 | 0.01074 | 97462 |
| vim._editor.validate | 926.138087 | 0.009502 | 97462 |
| vim.fs.dir | 834.501519 | 0.040953 | 20377 |
| vim.validate | 825.104186 | 0.008465 | 97462 |
| vim.shared.is_callable | 563.195141 | 0.002615 | 215301 |
| vim._editor.is_callable | 330.631591 | 0.001535 | 215301 |
| vim.shared.schedule_wrap | 51.857615 | 0.002544 | 20377 |
| vim.is_callable | 34.375963 | 0.000159 | 215301 |
| vim._editor.schedule_wrap | 32.305972 | 0.001585 | 20377 |
| vim.schedule_wrap | 10.623369 | 0.000521 | 20377 |

---

So I suspect here it's a bad interaction with the language server.

However I'm not sure at all how to profile / trace neovim's core to see which operations are taking a long time and if it's simply waiting on the LSP server that block the UI. May I have some pointers as to what to do next?

### Steps to reproduce

Here is a minimal reproducer for the configuration:

```lua
for name, url in pairs{
      lspconfig = "https://github.com/neovim/nvim-lspconfig"
    , fidget = "j-hui/fidget.nvim"
    , lsp_lines = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

-- haskell-language-server version: 2.0.0.1
require('lspconfig')['hls'].setup{
  filetypes = { 'haskell', 'cabal' },
  settings = {},
}
```

### Expected behavior

The UI should not lag so much.

### Neovim version (nvim -v)

NVIM v0.10.0-dev+658-g06694203e

### Vim (not Nvim) behaves the same?

I don't have vim

### Operating system/version

Fedora 37

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-256color

### Installation

Fedora COPR

**Comment by lewis6991** [comment]
This looks like a dup of #23291

**Comment by tchoutri** [comment]
Okay so interestingly it goes away with your solution. 

However I happen to use [cmp-nvim-lsp](https://github.com/hrsh7th/cmp-nvim-lsp) and I have this configuration:

```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = false
capabilities = require('cmp_nvim_lsp').default_capabilities(capabilities)
```

(this is what is suggested by Kickstart.nvim: https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L448C1-L448C74)

Should I forgo cmp-nvim-lsp for an alternative? If yes, is there something you would recommend? :)

**Comment by lewis6991** [comment]
I use cmp-nvim-lsp too. Use this:

```lua
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  vim.tbl_extend('force', capabilities, require('cmp_nvim_lsp').default_capabilities())

  capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = false
```

**Comment by tchoutri** [comment]
Thanks a lot, this seems to fix it!
