### ISSUE TITLE
Feature request: add `vim.keymap.get`

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#24333]
### Problem

Currently, the only easy way to get a mapping with its callback is using `maparg()` which is not lua.

### Expected behavior

I'm basically suggesting to make `vim.keymap.get` to a wrapper around `maparg()` (or `nvim_get_keymap`)
You can use it as if it was like `maparg()`:
```lua
local map=vim.keymap.get('i','K',{})
if map.lhsraw==':w\rK' then
  --..
end
```
I'm also suggesting an option to have an opt `return_format='map'` which would return the same table as before but extended with such values that unpack it would give the right arguments to `vim.keymap.set` to redefine the map.
```lua
local map=vim.keymap.get('i','K',{return_format='map'})
--...
vim.keymap.set(unpack(map))
```

**Comment by clason** [comment]
> which is not lua

That is **not** a sufficient argument for adding another API -- and certainly not for adding a wrapper. (We already _have_ a wrapper: `vim.fn.maparg`.)

So unless you have a concrete use case where `vim.fn.maparg` does not work (or has *objective* disadvantages), this is a clear `wontfix`.

**Comment by zeertzjq** [comment]
- `vim.keymap.set()` and `vim.keymap.del()` for creating and removing mappings
- `maparg()` and `mapset()` for getting and restoring mappings

There are already multiple ways to manipulate mappings and I think adding another wrapper will only cause more confusion.

**Comment by altermo** [comment]
Okay

**Comment by altermo** [comment]
Found a problem with `maparg()`: it only returns the current buffers keymap.
This means that using `maparg` you can't:
1. Get keymaps from non-current buffers
2. Get a global keymap if buffer has a buffer-local keymap
And requires the usage of `nvim_get_keymap` with filtering.
My biggest problem here is not that you need to do extra but that it is really easy to accidentally create a bug if you don't know the second point.
Thou I don't know if this is enough to create a totally new API function, probably should just add to `nvim_get_keymap` documentation about when not to use `maparg()`.

**Comment by mfussenegger** [comment]
> Get keymaps from non-current buffers

You can combine it with `nvim_buf_call` to get keymaps from other buffers

**Comment by justinmk** [comment]
Working in progress:

- https://github.com/neovim/neovim/pull/29464
