### ISSUE TITLE
Buffers not being forgotten on exit

### ISSUE THREAD

**Issue by marrs** [neovim/neovim#24334]
### Problem

Starting nvim does not start an empty session.  Instead, all previously opened buffers are remembered.  Using v0.9.1

This behaviour is not experienced in vim.

### Steps to reproduce

- start nvim.  Edit some files
- restart nvim. Files still in place

I can't fully test this because I can't delete the buffer list.  Most, if not all, buffers in the list will have been opened using neovide, but they remain when I open nvim directly.

### Expected behavior

nvim should start with and empty buffer list

### Neovim version (nvim -v)

v0.9.1

### Vim (not Nvim) behaves the same?

No, 9.0.1676

### Operating system/version

6.4.1-arch2-1

### Terminal name/version

alacritty 0.12.2

### $TERM environment variable

xterm-256color

### Installation

extra/neovim - arch repo

**Comment by zeertzjq** [comment]
It's a problem with your config.
