### ISSUE TITLE
Neovim downloading version 0.4.3

### ISSUE THREAD

**Issue by adrianatrevinoe** [neovim/neovim#24353]
### Problem

Hello I am installing nvim to a new laptop and with sudo apt-get install neovim i get version 0.4.3 instead of 0.9, my laptop is new so its not because it doesn't support it. I have tried re installing it and uninstalling but nothing works! Help!

which nvim:
~$ which nvim
/usr/local/bin/nvim

### Steps to reproduce

nvim --version

### Expected behavior

It should download latest version 0.9 but it downloads 0.4.3

### Neovim version (nvim -v)

0.4.3

### Vim (not Nvim) behaves the same?

no, vim 8.1

### Operating system/version

Ubuntu 20.04.6 LTS

### Terminal name/version

Terminal

### $TERM environment variable

-

### Installation

debian

**Comment by seandewar** [comment]
This is because of the distribution you're using; Ubuntu 20.04.6 in particular is not the latest LTS release.

You'd be better served using a PPA for a newer version or to compile from source.
