### ISSUE TITLE
replace luaL_error by vim.notify

### ISSUE THREAD

**Issue by cathaysia** [neovim/neovim#24355]
### Problem

Currently, if treesitter has an unknown node, it will directly report an error:

![image](https://github.com/neovim/neovim/assets/42114817/0335671f-b173-4e8e-8eb1-9a1ad3ef5486)

A litany of errors made editing and browsing basically impossible. Is it possible to replace error with notify.

I see these errors are coming from [treesitter](https://github.com/neovim/neovim/blob/33e1a8cd7042816a064c0d2bf32b6570d7e88b79/src/nvim/lua/treesitter.c#L1533), and vim.notify is a lua implementation. Is it possible to offload error handling into lua. And the c side simply returns an Error (like an Error object in Rust)

### Expected behavior

Treesitter errors should not affect actual editing operations

**Comment by justinmk** [comment]
I'm still puzzled why `vim.notify` exists as a separate behavior compared to `:echoerr`. I would expect instead the `vim.notify` "provider" (or whatever) to be used by `:echo`, `:echoerr`, etc.

(Ignoring the fact that `vim.notify` is not an ideal name since it overloads "notify" already long used in RPC contexts.)

**Comment by cathaysia** [comment]
I guess it's a historical issue. The neovim code is written in three languages, among which c provides some basic APIs, vim script writes some other APIs, and finally lua writes another set of APIs.
vim.notify seems to have originally appeared as a hook function, and was implemented in lua (presumably that's easy?). In the end, neovim has three different notification mechanisms.

But there is no doubt that some notification mechanisms are no longer able to meet the current needs. neovim should not block user operations unless a fatal error occurs.

**Comment by cathaysia** [comment]
Sorry, luaL_error should be a function that comes with lua. I'm not very familiar with it, sorry

**Comment by lewis6991** [comment]
vim.notify is not a replacement for `error()`.

`error()` causes an exception and aborts, vim.notify does not do this.

vim.notify should only be used for expected errors that are gracefully handled by the implementation.

**Comment by bfredl** [comment]
Looks like this is a plugin. The plugin should check for the case of an unsupported query and handle it appropriately. like showing the error _once_ so the user knows that something went wrong and then disable itself.
