### ISSUE TITLE
Randomly emptying entire files

### ISSUE THREAD

**Issue by s1nistr4** [neovim/neovim#24352]
### Problem

I would go to work on a coding project, save it, come back to it later and the entire file is empty. I figured it was a plugin, but I don't have that many plugins installed and couldn't find any bug report / post about this issue. If it's from another plugin it has to be from a popular one like nvim-cmp.

I was also able to find a reddit post about this issue 3 months ago, if it helps at all https://www.reddit.com/r/neovim/comments/131dfzz/neovim_is_erasing_my_files_randomly_somehow/

### Steps to reproduce

I could not 100% reproduce it, but it happens randomly when editing files. 

### Expected behavior

For it to not randomly empty files

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

No

### Operating system/version

OpenSuse Tumbleweed

### Terminal name/version

terminator 2.1.3

### $TERM environment variable

xterm-256color

### Installation

Official Tumbleweed repos

**Comment by clason** [comment]
Sorry, but without a (preferably minimal -- even one plugin is enough to mess with stuff if it has a bug) config there's nothing we can do here.

**Comment by justinmk** [comment]
Does it happen if you add this to your config:

    set fsync
