### ISSUE TITLE
More Granular Undo Points in NeoVim

### ISSUE THREAD

**Issue by Innei** [neovim/neovim#24361]
### Problem

VSCode's undo behavior is more granular compared to NeoVim. For example, if I input `const a = () => { }` in VSCode, undoing will step back through each change, like:

```
1. const a = () => {}
2. const a = () =>
3. const a =
4. const a
5. const
6. Empty
```

In contrast, when I perform the same action in NeoVim, the first undo results in `const a = () ` and the next undo clears everything.

NeoVim's undo functionality creates an undo point each time we switch from insert mode to normal mode. Is it possible to implement more granular undo points similar to VSCode?

Additionally, could Tree-sitter, which offers more detailed parsing, be leveraged to improve this undo functionality and make it more fine-grained?

### Expected behavior

Each undo step should remove a smaller, more granular piece of the inserted text, similar to the behavior in VSCode.

**Comment by zeertzjq** [comment]
This seems better implemented as a plugin, because it is hard to satisfy every use case.

**Comment by Innei** [comment]
> This seems better implemented as a plugin, because it is hard to satisfy every use case.

So is there any similar plugin that can solve this problem, probably need to undo it according to AST
