### ISSUE TITLE
Disable auto-format in Zig ftplugin by default

### ISSUE THREAD

**Issue by Spiffyk** [neovim/neovim#24372]
### Problem

The built-in ftplugin for Zig [auto-formats files on save by default](https://github.com/neovim/neovim/blob/f660b794808ac809ee8cafe82ddd824840bc8e2c/runtime/ftplugin/zig.vim#L59C5-L59C5). In my opinion, this is really disruptive, making the editor do extra actions that the user never asked for.

It is also really hard to find the way to disable it since it is hidden in the depths of the pre-installed runtime files, which I personally did not even think to suspect at first.

### Steps to reproduce

* Open a `.zig` file
* Write some code in it
* `:w`
* The file gets inadvertently reformatted

### Expected behavior

I would expect the file not to get reformatted on save by default because I never asked for it to be reformatted.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

yes, vim 9.0.1676

### Operating system/version

Manjaro Linux

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

Manjaro repository

**Comment by clason** [comment]
That plugin is taken from Vim, via the maintainer listed at the top of that file. Please contact them, and we will include any changes they make as a matter of course.
