### ISSUE TITLE
Suspending (ctrl-z) neovim causes system load average to start skyrocketing.

### ISSUE THREAD

**Issue by vjmp** [neovim/neovim#24375]
### Problem

When running nvim (from st+tmux+zsh), and then suspending it with control-z (to do shell work), system loadavg starts to rise and continues rising as long as nvim is suspended. Once resumed, loadavg starts to drop back to normal.

### Steps to reproduce

Running `st` terminal, where `tmux` window is running `zsh` shell.
Start nvim.
Suspend nvim with `ctrl-z`
Start `top` (on other window) and observe loadavg rising.
Resume nvim (with `fg`) on orignal window.
On `top` observe how loadavg starts to fall.

#### Addition

Also tried with just `xterm` and `bash` (so, without st+tmux+zsh combo) and result is same, skyrocketing loadavg.

### Expected behavior

When suspended, neovim should not cause loadavg to start rise (and cause system gradually to slowdown).

### Neovim version (nvim -v)

0.9.1 (release)

### Vim (not Nvim) behaves the same?

Nope, this is just nvim process problem.

### Operating system/version

Arch Linux

### Terminal name/version

st 0.8.4

### $TERM environment variable

screen-256color

### Installation

extra/neovim using pacman

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by vjmp** [comment]
Seems to be Arch Linux distro package related. And now it seems to be fixed with next build. Sorry about disturbance.
