### ISSUE TITLE
crash opening ~3mb text file with YouCompleteMe plugin

### ISSUE THREAD

**Issue by xanderdunn** [neovim/neovim#2438]
Some script I ran generated a text file that was about 3mb.  I tried to open it up in neovim and I would see YouCompleteMe flash a message that the file was too large to process, and then immediately afterward neovim would segfault.  

I got 4 crash logs.  You can find them [here](https://github.com/alexdunn/storage/tree/master/crashes/nvim_large_file).

Unfortunately, I no longer have that large text file.  Let me see if I can generate it again.

**Comment by justinmk** [comment]
Possibly related to https://github.com/neovim/neovim/issues/3150 but I'll keep this open for reference.

**Comment by tarruda** [comment]
@xanderdunn can you reproduce this with a debug build and show a backtrace of the core dump?

**Comment by xanderdunn** [comment]
I wasn't able to reproduce.  I opened an 8.4MB txt file and got no crash even with YouCompleteMe installed.

**Comment by dnmario** [comment]
Dear Xander Dunn,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] crash opening ~3mb text file with YouCompleteMe plugin"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
