### ISSUE TITLE
textwidth regression

### ISSUE THREAD

**Issue by ssh352** [neovim/neovim#24383]
### Problem

textwidth in init.vim not respected

### Steps to reproduce

init.vim has set tw=80

run 

nvim -u init.vim empty

:se tw

it shows textwidth=120 

### Expected behavior

it should show textwidth=80

I tried the something on 0.8.3 without issue.
also tried on vim 9.0 without issue.

### Neovim version (nvim -v)

v0.9.1

### Vim (not Nvim) behaves the same?

no vim 9.0

### Operating system/version

macOS 13.3.1 (22E261)

### Terminal name/version

item Build 3.4.19

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by clason** [comment]
_where_ is your `init.vim`? (If it's in `.config/nvim`, you _don't_ need `nvim -u`.) What does `:verb set tw?` say? What does `:scriptnames` say?

**Comment by zeertzjq** [comment]
Do you have an `.editorconfig` file with `max_line_length = 120`?

**Comment by ssh352** [comment]
> _where_ is your `init.vim`? (If it's in `.config/nvim`, you _don't_ need `nvim -u`.) What does `:verb set tw?` say? What does `:scriptnames` say?

I made a new init.vim with only  set tw=80 ;

verb set tw says
```
  textwidth=120
        Last set from Lua
```

```
:scriptnames
  1: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/ftplugin.vim
  2: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/indent.vim
  3: ~/a.vim
  4: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/filetype.lua
  5: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/syntax/syntax.vim
  6: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/syntax/synload.vim
  7: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/gzip.vim
  8: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/health.vim
  9: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/matchit.vim
 10: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
 11: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/matchparen.vim
 12: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/netrwPlugin.vim
 13: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/rplugin.vim
 14: ~/.local/share/nvim/rplugin.vim
 15: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/shada.vim
 16: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/spellfile.vim
 17: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/tarPlugin.vim
 18: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/tohtml.vim
 19: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/tutor.vim
 20: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/zipPlugin.vim
 21: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/editorconfig.lua
 22: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/man.lua
 23: /usr/local/Cellar/neovim/0.9.1/share/nvim/runtime/plugin/nvim.lua
```

**Comment by ssh352** [comment]
> Do you have an `.editorconfig` file with `max_line_length = 120`?

yes sir

**Comment by zeertzjq** [comment]
Then Nvim is respecting you `.editorconfig` file.

**Comment by ssh352** [comment]
> Then Nvim is respecting you `.editorconfig` file.

so this is a new feature? it did not happen even in 0.9.0

**Comment by zeertzjq** [comment]
It should work in Nvim v0.9.0. Maybe there was something wrong with your installation.
