### ISSUE TITLE
Indentation stop working after ~2100 lines in javascript

### ISSUE THREAD

**Issue by login6** [neovim/neovim#24389]
### Problem

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```
```
function test() {
  let test = "test";
  test = "test"; (yank and paste "2100p" times after that try to press "o" in the end of function)
}
```

### Steps to reproduce

nvim --clean test.js

### Expected behavior

Indentation continue working

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

debian 12

### Terminal name/version

gnome-shell  43.4

### $TERM environment variable

xterm-256color

### Installation

cmake release build

**Comment by zeertzjq** [comment]
https://github.com/pangloss/vim-javascript/issues/1121#issuecomment-381281575
