### ISSUE TITLE
feature flag for terminal

### ISSUE THREAD

**Issue by rstacruz** [neovim/neovim#2439]
It would be nice to be able to do `has("terminal")` to conditionally check for terminal support.

This allows for configurations such as:

```vim
" Ensure that warnings don't happen in normal vim
if has("terminal")
  tmap <C-[> <C-\><C-n>
endif
```

**Comment by Shougo** [comment]
Why don't you use `has('nvim')` ?

**Comment by rstacruz** [comment]
Ah! I was looking for that one myself, but it seems `:help feature-list` doesn't list `nvim` on there.

**Comment by Shougo** [comment]
Yes, it should be described in it and `:help vim-differences` like `TabNew` autocmd.

**Comment by joshaw** [comment]
You can always use `exists()`, interestingly, tpope's vim-fugitive is already making use of neovim features with [this](https://github.com/tpope/vim-fugitive/blob/master/plugin/fugitive.vim#L673).
```viml
if exists(':terminal')
    call Something()
endif
```

**Comment by noahfrederick** [comment]
Or even

```vim
if exists(':tnoremap')
  tnoremap <C-[> <C-\><C-n>
endif
```
