### ISSUE TITLE
Inconsistencies or undocumented behaviors for local options in nvim_set_option_value

### ISSUE THREAD

**Issue by lobre** [neovim/neovim#24398]
### Problem

As of today, and by reading the docs, I cannot say what the two examples below do.

Calling the function with a local-window option and providing the `buf` parameter:

```
nvim_set_option_value('cursorline', 1, {'buf': 2})
```

For this one, it appears that the current behavior is that it sets the window option for the current window if the given buffer is the current one, and otherwise for the first window showing the given buffer.

This is not intuitive nor clearly communicated at all.

---

Calling the function with a local-buffer option and providing the `win` parameter:

```
nvim_set_option_value('filetype', 'json', {'win': 1000})
```

I don't know what this does.

### Steps to reproduce

Just call the above functions.

### Expected behavior

Those weird behaviors should be declared as bugs and prevented, or should be clearly expressed and documented.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

no, at it is lua

### Operating system/version

Ubuntu 22

### Terminal name/version

xfce4-terminal

### $TERM environment variable

xterm-256color

### Installation

nix

**Comment by seandewar** [comment]
In comparison, these are correctly rejected by `vim.wo`, `vim.bo` via the `opt_validate()` checks they do.

**Comment by lewis6991** [comment]
I don't know what these do either and at the moment are officially undefined.

I suggest we disallow these and add the same checks that `vim.wo` and `vim.bo` have.
