### ISSUE TITLE
--server "$NVIM" with --remote-ui inside a running neovim causes a loop

### ISSUE THREAD

**Issue by hemantgouni** [neovim/neovim#24395]
### Problem

When I run `nvim --server "$NVIM" --remote-ui` inside a `:terminal` buffer, there's a bunch of output (which looks like the currently set statusline) that scrolls past, followed by the current tab freezing. This is because `--remote-ui` being used from inside nvim creates a loop.

### Steps to reproduce

1. `$ nvim -u NONE`
2. `:terminal`
3. `(in :terminal) $ nvim -u NONE --server "$NVIM" --remote-ui`

### Expected behavior

Nothing should happen, or an error should be displayed and `nvim` should refuse to start up.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

nixos unstable, fedora 38

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

nixpkgs, fedora 38 repository

**Comment by zeertzjq** [comment]
Why are you doing this?

**Comment by zeertzjq** [comment]
Ok, that makes sense.
