### ISSUE TITLE
Editorconfig properties with dashes are not highlighted

### ISSUE THREAD

**Issue by ObserverOfTime** [neovim/neovim#24404]
### Problem

[Ktlint](https://pinterest.github.io/ktlint/0.50.0/faq/#how-do-i-enable-or-disable-a-rule-set) properties can contain dashes and are not highlighted by editorconfig.

### Steps to reproduce

Open an editorconfig file with these contents:
```ini
[*.kt]
ktlint_experimental = enabled # -> editorconfigUnknownProperty
ktlint_custom-rule-set = enabled # -> dosiniLabel
```

### Expected behavior

 ```ini
 [*.kt]
ktlint_experimental = enabled # -> editorconfigUnknownProperty
ktlint_custom-rule-set = enabled # -> editorconfigUnknownProperty
```

### Neovim version (nvim -v)

v0.10.0-dev-667+ga3f4598226

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

konsole 23.04.3

### $TERM environment variable

konsole-256color

### Installation

build from repo

**Comment by clason** [comment]
Isn't that an issue with the syntax file? Then you need to raise it with the maintainer listed at the top of that file.

**Comment by ObserverOfTime** [comment]
It does seem to be an issue with the syntax file but it's built-in. I'll submit a PR.

**Comment by ObserverOfTime** [comment]
I know, but this syntax file is not the same in Vim.

**Comment by clason** [comment]
Oh, you're right, I'm sorry!

**Comment by ObserverOfTime** [comment]
Should I rewrite it in Lua?

**Comment by clason** [comment]
Maybe better not right now; there could have been a technical reason for that (although zeertzjq fixed an issue about sourcing Lua syntax files recently, so that may have changed).

**Comment by ObserverOfTime** [comment]
Do the `:syntax` and `:runtime` commands have Lua API equivalents?

**Comment by zeertzjq** [comment]
No

**Comment by clason** [comment]
(The only! point of Lua here would be to make it obvious that this file is owned by Neovim, since Vim will never have Lua runtime files. There is no actual benefit otherwise.)
