### ISSUE TITLE
Segfault when resizing window

### ISSUE THREAD

**Issue by benjidial** [neovim/neovim#24417]
### Problem

I am running i3 and using xterm. Under circumstances as in the attached video, when a new window is opened under the terminal that neovim is in, resizing the window, neovim segfaults. I tested this on both a packaged v0.7.2 from Debian, and on v0.10.0-dev-698+g02d859a07 built from source, and it happened on both. The attached ASAN log is from the second one.

https://github.com/neovim/neovim/assets/7697693/8f3cacdd-35f9-4124-959e-8d64a15f08d1

[nvim_asan.53649.txt](https://github.com/neovim/neovim/files/12134979/nvim_asan.53649.txt)

### Steps to reproduce

1. nvim --clean
2. insert text as in the video
3. open a new window that resizes xterm
The amount of text seems to matter, so depending on your resolution and terminal font you may need a different amount of text.

### Expected behavior

neovim doesn't segfault :)

### Neovim version (nvim -v)

tested v0.7.2 and v0.10.0-dev-698+g02d859a07, happens on both

### Vim (not Nvim) behaves the same?

no, vim 9.0.1672

### Operating system/version

Debian sid

### Terminal name/version

xterm 384

### $TERM environment variable

xterm-256color

### Installation

v0.7.2 from apt on Debian sid, v0.10.0-dev-698+g02d859a07 built from the repository

**Comment by Flarp** [comment]
I get the same thing on Xubuntu 23.04 with i3 and neovim 0.10.0, but only on xterm, not alacritty. It seems to be unique to xterm.

**Comment by zeertzjq** [comment]
Duplicate of #22278
