### ISSUE TITLE
Sending of correct escape sequences

### ISSUE THREAD

**Issue by JosefLitos** [neovim/neovim#24416]
### Problem

So far I've encountered only horizontal scroll and <kbd>shift/ctrl+home/end</kbd>, but there may be some more keys that send weird character sequences (all in negative numbers/>127)

### Expected behavior

send the correct escape sequences (<kbd>alt+home/end</kbd> already works fine) for all mentioned key codes (+ send at least something for <kbd>alt+pgup</kbd>).

This is some really strange behaviour - why are only some modifiers resulting in weird values... - so I am not sure how hard it would be, + it is not something used extra often, but it would be nice to have a more complete terminal.

**Comment by JosefLitos** [comment]
you can just run `nvim -c ":term showkey -a"` and press the forementioned keys. I don't think there is much to add as to any context.

**Comment by clason** [comment]
That would have been necessary. It also matters which version of Neovim you're running. Let me be clear: From what you wrote, I had no idea you were talking about the builtin terminal. So, yes, more context is needed. (And if you're talking about the `:terminal` capabilities, you need to report these for `libvterm`, which is a separate project that we just use.)

**Comment by JosefLitos** [comment]
Oh, sorry, I didn't realize I haven't specified the meaning of terminal.
BTW:
You don't use `libtermkey` anymore? Or `libvterm` is used separately for printing the keys back to the terminal?

**Comment by clason** [comment]
We use libtermkey, but that's for the other direction (terminal -> neovim). So it matters a lot _exactly_ what you type and where.

**Comment by clason** [comment]
https://github.com/neovim/neovim/blob/master/MAINTAIN.md#third-party-dependencies

**Comment by JosefLitos** [comment]
I assume bug reports must be sent to him by email or something? This is really weird.

**Comment by zeertzjq** [comment]
Only the horizontal scroll wheel keys are bugs in libvterm. Others are bugs in Nvim.

**Comment by zeertzjq** [comment]
And at least the following change is needed in libvterm for horizontal scrolling to work:
```diff
--- a/src/mouse.c
+++ b/src/mouse.c
@@ -93,7 +93,7 @@ void vterm_mouse_button(VTerm *vt, int button, bool pressed, VTermModifier mod)
   if(button < 4) {
     output_mouse(state, button-1, pressed, mod, state->mouse_col, state->mouse_row);
   }
-  else if(button < 6) {
+  else if(button < 8) {
     output_mouse(state, button-4 + 0x40, pressed, mod, state->mouse_col, state->mouse_row);
   }
 }
```

**Comment by clason** [comment]
@leonerd

**Comment by leonerd** [comment]
Yup, looks good. Shall add + a test.
And also in pangoterm. And libtickit.

**Comment by leonerd** [comment]
FYI this (and a bunch of other stuff) is now in libvterm v0.3.3.

That'll probably be the last of the v0.3 series, as I have a few API-breaking changes to consider next; so likely that'll become v0.4.

**Comment by clason** [comment]
Also the reflow fix from @zeertzjq? 🥺 👉 👈
