### ISSUE TITLE
Netrw can't enter directory when name contains curly {{ }} braces

### ISSUE THREAD

**Issue by crash5** [neovim/neovim#24421]
### Problem

Neovim don't show files and directories in a directory if the parent directory name contains curly braces.

It works under windows-git bash's vim.

### Steps to reproduce

- Setup env. (from bash like command line in a directory):
    - mkdir -p "{{ cookiecutter.project_slug }}/dir1"
    - touch "{{ cookiecutter.project_slug }}/file1.txt"
    - touch "{{ cookiecutter.project_slug }}/file2"
    - echo -e "set nocp\nfiletype plugin on" > vimrc
- Run neovim (from windows command line):
    - nvim-qt.exe -- -u vimrc .
- Try to enter the "{{ cookiecutter.project_slug }}" directory with enter

### Expected behavior

Enter the directory and shows the directory's content like for any other directory.

### Neovim version (nvim -v)

NVIM v0.9.1, Build type: RelWithDebInfo, LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.0, Included patches: 1-1403

### Operating system/version

Windows 10

### Terminal name/version

windows commandline, nvim-qt

### $TERM environment variable

none

### Installation

nvim-win64.zip from github release page

**Comment by lsvmello** [comment]
I was able to reproduce the problem, and seems its a problem with the `glob` function.
Both Vim and Neovim pass the same value to `glob` but Neovim's return an empty list.

Steps to reproduce _(maybe a little to much but I did to add logs to `netrw`)_

Create the following folder structure on C:\temp
```
C:\TEMP\NETRW
│   netrw.vimrc
├───folder
│   └───dir
├───nvim
│       netrw.vim
│       netrwPlugin.vim
├───vim
│       netrw.vim
│       netrwPlugin.vim
└───{{ folder }}
    └───dir
```
_Copy the respectives **autoload/netrw.vim** and **plugins/netrwPlugin.vim** from Neovim's and Vim's repository_

The contents of netrw.vimrc are:
```Vimscript
set nocp
if has('nvim')
  " Align Nvim defaults to Vim.
  set backspace=
  set commentstring=/*%s*/
  set complete=.,w,b,u,t,i
  set define=^\\s*#\\s*define
  set directory^=.
  set display=
  set fillchars=vert:\|,foldsep:\|,fold:-
  set formatoptions=tcq
  set fsync
  set include=^\\s*#\\s*include
  set laststatus=1
  set listchars=eol:$
  set joinspaces
  set mousemodel=extend
  set nohidden nosmarttab noautoindent noautoread noruler noshowcmd
  set nohlsearch noincsearch
  set nrformats=bin,octal,hex
  set shortmess=filnxtToOS
  set sidescroll=0
  set tags=./tags,tags
  set undodir^=.
  set wildoptions=
  set startofline
  set sessionoptions+=options
  set viewoptions+=options
  set switchbuf=
  so C:\Temp\netrw\nvim\netrw.vim
  so C:\Temp\netrw\nvim\netrwPlugin.vim
else
  so C:\Temp\netrw\vim\netrw.vim
  so C:\Temp\netrw\vim\netrwPlugin.vim
endif
```

To add the logs do the following: _(I wasn't able to use Decho)_

On `vim/netrw.vim`:
  - Line 10902 remove `sil!`
  - Before line 5823 (inside the elseif) add:
    ```
     echom "s:ComposePath " . s:ComposePath(fnameescape(a:direntry), a:expr)
     echom "glob size " . len(glob(s:ComposePath(fnameescape(a:direntry),a:expr),0,1,1))
    ``` 
On `nvim/netrw.vim`:
  - Line 10792 remove `sil!`
  - Before line 5781 (inside the elseif) add:
    ```
     echom "s:ComposePath " . s:ComposePath(fnameescape(a:direntry), a:expr)
     echom "glob size " . len(glob(s:ComposePath(fnameescape(a:direntry),a:expr),0,1,1))
    ``` 

Start Neovim with `nvim -u netrw.vimrc --noplugins -i NONE .` and Vim with `vim -u netrw.vimrc --noplugins -i NONE .`.
Then navigate to the `{{ folder }}` you will notice that the result of **s:ComposePath** is the same, but the size of the glob is different.

![image](https://github.com/neovim/neovim/assets/70452831/6c54efff-32d9-48d7-95a1-72bb29136d95)
_Neovim on the left and Vim on the right_
