### ISSUE TITLE
Add documentation about `vim.str_utf_{start,end,pos}`

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#24422]
### Problem

Currently, there's no documentation about `vim.str_utf_{start,end,pos}`.

### Expected behavior

Add documentation about `vim.str_utf_{start,end,pos}` (or mark them as private).

**Comment by lewis6991** [comment]
PR would be welcome.

**Comment by sakshamrai101** [comment]
Hi, I was wondering if I can take this issue. I am looking forward to make my first open source contribution.

**Comment by clason** [comment]
There's already a PR up, so pick something else.
