### ISSUE TITLE
Regression: Vim(syntax):E403: syntax sync: line continuations pattern specified twice

### ISSUE THREAD

**Issue by wookayin** [neovim/neovim#24431]
### Problem

When calling `vim.lsp.util.stylize_markdown` (via lsp_signature or some plugins), the following error happens:

```
Error executing vim.schedule lua callback: ...vim/HEAD-b74262a/share/nvim/runtime/lua/vim/lsp/util.lua:1485: Error executing lua: vim/_editor.
lua:400: nvim_exec2()../opt/homebrew/Cellar/neovim/HEAD-b74262a/share/nvim/runtime/syntax/vim.vim, line 820: Vim(syntax):E403: syntax sync: li
ne continuations pattern specified twice
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua:400: in function 'cmd'
        ...vim/HEAD-b74262a/share/nvim/runtime/lua/vim/lsp/util.lua:1470: in function 'apply_syntax_to_region'
        ...vim/HEAD-b74262a/share/nvim/runtime/lua/vim/lsp/util.lua:1494: in function <...vim/HEAD-b74262a/share/nvim/runtime/lua/vim/lsp/util
.lua:1485>
        [C]: in function 'nvim_buf_call'
        ...vim/HEAD-b74262a/share/nvim/runtime/lua/vim/lsp/util.lua:1485: in function 'stylize_markdown'
        ...vim/HEAD-b74262a/share/nvim/runtime/lua/vim/lsp/util.lua:1699: in function 'open_floating_preview'
        ...im/plugged/lsp_signature.nvim/lua/lsp_signature/init.lua:562: in function 'handler'
        ...r/neovim/HEAD-b74262a/share/nvim/runtime/lua/vim/lsp.lua:1497: in function 'cb'
        vim/_editor.lua:324: in function <vim/_editor.lua:323>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...vim/HEAD-b74262a/share/nvim/runtime/lua/vim/lsp/util.lua:1485: in function 'stylize_markdown'
        ...vim/HEAD-b74262a/share/nvim/runtime/lua/vim/lsp/util.lua:1699: in function 'open_floating_preview'
        ...im/plugged/lsp_signature.nvim/lua/lsp_signature/init.lua:562: in function 'handler'
        ...r/neovim/HEAD-b74262a/share/nvim/runtime/lua/vim/lsp.lua:1497: in function 'cb'
        vim/_editor.lua:324: in function <vim/_editor.lua:323>
```

The line 820 where vim syntax throws an error is:

```
syn sync linecont	"^\s\+\\"
```

Note: the documentation for `vim.fn.has(...)` has **two code blocks** in markdown doc: lua and vim, which results in including both of syntax/lua.vim and syntax/vim.vim.

### Steps to reproduce

A minimal way to reproduce this:

I had a custom syntax for lua that includes vim syntax file, e.g. `~/.config/nvim/after/syntax/lua.vim`:

```vim
let s:vimpath = fnameescape(expand("$VIMRUNTIME")."/syntax/vim.vim")
if !filereadable(s:vimpath)
 for s:vimpath in split(globpath(&rtp, "syntax/vim.vim"),"\n")
  if filereadable(fnameescape(s:vimpath))
   let s:vimpath = fnameescape(s:vimpath)
   break
  endif
 endfor
endif
 
if !filereadable(s:vimpath)
  finish
end
 
unlet! b:current_syntax
 
exe "syn include @vimLuaScript ".s:vimpath

unlet s:vimpath
let b:current_syntax = 'lua'
```

Then

```
$ nvim -u NONE
```

```
:lua vim.lsp.util.stylize_markdown(0, {'```lua', 'function vim.fn.has()', '```', '```vim', 'finish', '```'}, {})
:lua vim.lsp.util.stylize_markdown(0, {'```lua', 'function vim.fn.has()', '```', '```vim', 'finish', '```'}, {})
```

<img width="800" alt="image" src="https://github.com/neovim/neovim/assets/1009873/0e2cfb07-ac5b-4710-8752-dbdc71caf1b3">

### Expected behavior

No error should happen.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-4724+gb74262a33-Homebrew

Note: on nvim 0.9.1 (stable) it works OK. This seems to be a regression in neovim 0.10.x nightly.

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

macOS 12.1

### Terminal name/version

xterm, kitty

### $TERM environment variable

xterm-256color, xterm-kitty

### Installation

Homebrew

**Comment by clason** [comment]
We want to replace that function with tree-sitter parsing anyway (@folke).

**Comment by wookayin** [comment]
The change comes from this commit (ba8f19ebb67ca27d746f4b1cd902ab3d807eace3):

https://github.com/neovim/neovim/blame/master/runtime/lua/vim/lsp/util.lua#L1469

In neovim 0.9.x the line `syntax include vim syntax/vim.vim` would still throw an error, but this is protected by a `pcall` call. In 0.10.x this is no longer protected. 

@glepnir Would this be a deliberate change?

**Comment by glepnir** [comment]
because you do twice `syntax include` for same buffer.

**Comment by wookayin** [comment]
Would updating vim/lua syntax file to ignore E403 errors at the line `syn sync linecont ...` an option? This might need a patch to upstream vim though.
