### ISSUE TITLE
LSP hover/signatureHelp: header divider line wraps at wrong position

### ISSUE THREAD

**Issue by younger-1** [neovim/neovim#24444]
### Problem

When `signcolumn` option is set to `yes` in $MYVIMRC, open hover floating window, the header divider line wraps at wrong position:
![图片](https://github.com/neovim/neovim/assets/45989017/c3d4e7b1-0385-4473-85ec-98d265787d93)

This also effects the diagnostic floating window:
![图片](https://github.com/neovim/neovim/assets/45989017/0491a9a8-8b1d-41f8-932e-47bee4faf144)

Similar issue: https://github.com/neovim/neovim/issues/12998

### Workaround

A workaround for this is to override the handler for `hover` and `signatureHelp` and turn off `signcolumn` option for the floating window. I think this should be solved in neovim itself for user-friendliness.
```lua
vim.lsp.handlers['textDocument/hover'] = vim.lsp.with(function(_, result, ctx, config)
  local _, fwin = vim.lsp.handlers.hover(_, result, ctx, config)
  if fwin then
    vim.wo[fwin].signcolumn = 'no'
  end
end, { border = 'rounded' })

vim.lsp.handlers['textDocument/signatureHelp'] = vim.lsp.with(function(_, result, ctx, config)
  local _, fwin = vim.lsp.handlers.signature_help(_, result, ctx, config)
  if fwin then
    vim.wo[fwin].signcolumn = 'no'
  end
end, { border = 'rounded' })

-- lsp on_attach mapping
vim.keymap.set('n', 'gl', function()
  local _, fwin = vim.diagnostic.open_float { scope = 'line' }
  if fwin then
    vim.wo[fwin].signcolumn = 'no'
  end
end, { desc = 'Show diagnostics', buffer = 0 })
```

### Expected behavior

For hover floating window:
![图片](https://github.com/neovim/neovim/assets/45989017/4529fd9b-fc2e-4e4d-95a9-5cf9d6797207)

For diagnostic floating window:
![图片](https://github.com/neovim/neovim/assets/45989017/1709d9d7-0162-4a5a-9d76-bcc873f44914)

### Neovim version (nvim -v)

NVIM v0.9.1

### Language server name/version

lua-language-server 3.6.23

### Operating system/version

Darwin Kernel Version 22.5.0

**Comment by zeertzjq** [comment]
- https://github.com/chentoast/marks.nvim/issues/65
- https://github.com/chentoast/marks.nvim/issues/79
