### ISSUE TITLE
Open/close floating windows when Command-line window is active

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#24452]
### Problem

Opening (on nightly) and closing (both on 0.9.1 and nightly) floating windows is not possible when Command-line window (`|cmdwin|`) is active.

### Steps to reproduce

To test opening:
- Create config file with the following content:
```lua
local open_floating_win = function()
  vim.api.nvim_open_win(
    vim.api.nvim_create_buf(true, false),
    false,
    { relative = 'editor', row = 0, col = 0, width = 20, height = 10 }
  )
end

vim.keymap.set('n', '<Space>o', open_floating_win)
```
- Open Neovim with that config file.
- Type `q:` (should open Command-line window).
- Type `<Space>o`. It throws an `E11: Invalid in command-line window;` error.

**Note**: This works on Neovim 0.9.1. Seems to be the consequence of #23228 (cc @seandewar).

------
To test closing:
- Create config file with the following content:
```lua
local win_id = vim.api.nvim_open_win(
  vim.api.nvim_create_buf(true, false),
  false,
  { relative = 'editor', row = 0, col = 0, width = 20, height = 10 }
)

vim.keymap.set('n', '<Space>c', function() vim.api.nvim_win_close(win_id, true) end)
```
- Open Neovim with that config file. Should have floating window pre-opened.
- Type `q:` (should open Command-line window).
- Type `<Space>c`. It throws an `E11: Invalid in command-line window;` error.

### Expected behavior

Opening (without setting focus) and closing floating windows with active Command-line window should be possible.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-709+gce56ad2ba and 0.9.1

### Vim (not Nvim) behaves the same?

No, doesn't have Neovim's floating windows

### Operating system/version

EndeavourOS Linux x86_64 (6.4.4-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by echasnovski** [comment]
Possibly related: #11387.

**Comment by zeertzjq** [comment]
Split windows cannot be created in cmdwin, why should floating windows be allowed?
