### ISSUE TITLE
Neovim fails to build in OpenBSD

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#2445]
Two minor issues:

1. nvim-client fails to install for OpenBSD
2. **TAB0** used in pty_process.c is not defined in termios.h for OpenBSD

Eventually I will be starting PRs in neovim/neovim and neovim/lua-client to fix the first issue. A minimal workaround is to disable the nvim-client and busted or patch the nvim-client rockspec with

```diff
--- nvim-client-0.0.1-11.rockspec       Fri Apr 17 17:13:15 2015
+++ nvim-client-0.0.1-11.rockspec-new   Fri Apr 17 17:11:28 2015
@@ -54,6 +54,7 @@
     linux = make_plat('linux'),
     macosx = make_plat('macosx'),
     freebsd = make_plat('freebsd'),
+    openbsd = make_plat('openbsd'),
     solaris = make_plat('solaris')
     }
 }
```

Dirty fix for the second issue was to #define TAB0 as 0x0 :). The `init_termios()` seems be based in code from pangoterm, ping @leonerd would that be ok?

**Comment by equalsraf** [comment]
Also jemalloc failed to build but that can be skipped with -DUSE_BUNDLED_JEMALLOC=FALSE and I am able to build it from master, so it should not be a problem.

**Comment by Pyrohh** [comment]
Did you have no issues with having to define AUTOCONF_VERSION? I defined it manually, which works fine, but it might be a better idea to do [something like this](https://github.com/rvm/rvm/commit/dd5412583431402df1cfbdc55906171eb36f3789) in CMake.

**Comment by equalsraf** [comment]
Likewise I already had a export for AUTOCONF and AUTOMAKE_VERSION.

**Comment by leonerd** [comment]
Latest pangoterm source now just #ifdef-wraps the TAB0 issue.

**Comment by Pyrohh** [comment]
@equalsraf are you encountering this error (or similar)?
```
[ 82%] Performing build step for 'msgpack'
make: don't know how to make sw
Stop in /home/michael/src/neovim/.deps/build/src/msgpack-build
CMakeFiles/msgpack.dir/build.make:108: recipe for target 'build/src/msgpack-stamp/msgpack-build' failed
gmake[3]: *** [build/src/msgpack-stamp/msgpack-build] Error 2
gmake[3]: Leaving directory '/home/michael/src/neovim/.deps'
CMakeFiles/Makefile2:406: recipe for target 'CMakeFiles/msgpack.dir/all' failed
gmake[2]: *** [CMakeFiles/msgpack.dir/all] Error 2
gmake[2]: Leaving directory '/home/michael/src/neovim/.deps'
Makefile:75: recipe for target 'all' failed
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory '/home/michael/src/neovim/.deps'
Makefile:68: recipe for target 'deps' failed
gmake: *** [deps] Error 2
```

**Comment by equalsraf** [comment]
@Pyrohh I cant see that one, at least not from the master branch.

**Comment by justinmk** [comment]
Can this be closed? I thought QB was building openbsd

**Comment by Pyrohh** [comment]
Unless this changed recently, that was FreeBSD, not Open.

**Comment by justinmk** [comment]
My mistake

**Comment by Pyrohh** [comment]
@equalsraf Are you able to build on current, or something else? Anything you put in `local.mk`?

**Comment by equalsraf** [comment]
Not -current, still using 5.6 and I have not touched local.mk

**Comment by equalsraf** [comment]
Now from a fresh install of 5.7

- [ ] **unzip** was not installed and is required for luarocks. Luarocks just fails with `Warning: Failed searching manifest: Failed loading manifest: Failed extracting manifest file`
- [ ] same as before jemalloc wont build

**Comment by Pyrohh** [comment]
If it's not too hard, perhaps we should check for `unzip` via CMake in order to provide a clear warning message.

**Comment by Pyrohh** [comment]
Actually, it's probably a better idea to submit a patch to luarocks.

**Comment by Pyrohh** [comment]
> same as before jemalloc wont build

Could you take a look at #2634? If that gets merged, then we can point users to it. Maybe a note should be added in `local.mk` about jemalloc on OpenBSD.

**Comment by equalsraf** [comment]
Irony is the unzip issue was already reported keplerproject/luarocks#238 :laughing:, we might want to add that unzip check after all.

**Comment by Pyrohh** [comment]
Another thing worth mentioning is that I'm getting a build failure using OpenBSD's libtool.
nvim builds fine with GNU's libtool (installed from ports, has the same name); the failure is happening to one of the deps (it stops after unibilium, but I didn't see any obvious failure signs). I'll try to look into it later as I'd prefer not needing the extra compile time dependency.

Anyways, perhaps this issue should be closed @equalsraf and a new one opened which tracks OpenBSD related problems and possible improvements. It's turning into somewhat of a dumping ground.

**Comment by equalsraf** [comment]
Closing then to revisit later.

**Comment by 4d47** [comment]
@Pyrohh do you still have that `make: don't know how to make sw` error ? and if you have a solution could you add it here please ? I have the same error but don't find workaround.

**Comment by equalsraf** [comment]
Ok now I can replicate this but only when using the toplevel Makefile

```
gmake
(...)
[ 80%] Performing build step for 'msgpack'
make: don't know how to make sw
```

slightly different case happens with

```
gmake VERBOSE=1
(...)
[ 80%] Performing build step for 'msgpack'
cd /home/raf/Code/neovim/.deps/build/src/msgpack-build && /usr/local/bin/cmake --build .
make: don't know how to make w
Stop in /home/raf/Code/neovim/.deps/build/src/msgpack-build
CMakeFiles/msgpack.dir/build.make:106: recipe for target 'build/src/msgpack-stamp/msgpack-build' failed
```

**Comment by jszakmeister** [comment]
Hmmm.  It sounds like somewhere BSD make is being invoked instead of gmake.

**Comment by equalsraf** [comment]
More like a mixture of both. ${CMAKE_MAKE_PROGRAM} is make and ${MAKE_PRG} should be gmake. Which makes some since because CMake can use whatever it wants, provided the third-party recipes that need gmake use ${MAKE_PRG}. It gets a bit confusing because the toplevel makefile is using -C to build .deps

I tried changing the toplevel makefile

```diff
diff --git a/Makefile b/Makefile
index 721474a..b023350 100644
--- a/Makefile
+++ b/Makefile
@@ -65,7 +65,7 @@ build/.ran-cmake: | deps
 
 deps: | build/.ran-third-party-cmake
 ifeq ($(call filter-true,$(USE_BUNDLED_DEPS)),)
-       +$(BUILD_CMD) -C .deps
+       cmake --build .deps
 endif
```

But this caused unibilium to fail, calling make instead of gmake. The following line caused make to be used as MAKE_PRG

```diff
diff --git a/third-party/CMakeLists.txt b/third-party/CMakeLists.txt
index c04e179..0950660 100644
--- a/third-party/CMakeLists.txt
+++ b/third-party/CMakeLists.txt
@@ -42,7 +42,7 @@ endif()
 # When using make, use the $(MAKE) variable to avoid warning about the job
 # server.
 if(CMAKE_GENERATOR MATCHES "Makefiles")
-  set(MAKE_PRG "$(MAKE)")
+#  set(MAKE_PRG "$(MAKE)")
 endif()
```

But then libuv fails to build with 

```
[ 27%] Performing install step for 'libuv'
cd /home/raf/Code/neovim/.deps/build/src/libuv-build && /usr/local/bin/gmake install
gmake[1]: Entering directory '/home/raf/Code/neovim/.deps/build/src/libuv-build'
gmake[1]: install-exec-am: Command not found
```

I'm gonna have to stop digging for now, but setting MAKE=gmake seems to help.

**Comment by Pyrohh** [comment]
@4d47 
> do you still have that make: don't know how to make sw error ? and if you have a solution could you add it here please ? I have the same error but don't find workaround.

Assuming you've [seen the wiki](https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites) (which I just updated, the instructions were wrong). As far as I can see, my problem disappeared when autoconf-2.69 was updated to autoconf-2.69p1... but it might have been something else I missed.
