### ISSUE TITLE
runtime/doc/developing.txt

### ISSUE THREAD

**Issue by mreed1** [neovim/neovim#2446]
Does anyone think we should keep ? It's wildly out of date, so I'm not sure it's worth it to update it, especially since we already have a bunch of docs on the Wiki.

Then again, having a page built in to the docs might be preferred over those in a Wiki, as it's easier to access while developing, and the wiki page could just link to the [generated documentation](http://neovim.org/doc/user/) so we'd have less to maintain.

thoughts?

**Comment by justinmk** [comment]
I've definitely thought about ways to navigate the wiki locally for this reason. But it might be better to move stuff out of the wiki and into developing.txt. E.g., [code differences table](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim#code-differences) would be much more useful if one could pull it up easily in the editor.

**Comment by mhinz** [comment]
:+1: for browsing a help page locally instead of navigating a wiki

**Comment by fwalch** [comment]
If we'd manage to convert Markdown into Vim's help format, we could include the Wiki as a build dependency (it's just another Git repo).
