### ISSUE TITLE
Add `MacroExecutionPre` and `MacroExecutionPost` autocmd events

### ISSUE THREAD

**Issue by Subjective** [neovim/neovim#24475]
### Problem

Movement plugins like sneak, leap, flash, etc. can be used in conjuction with macros for quick editing and are quite convenient in a lot of situations. However, custom hl groups and highlighting patterns (like for underlining urls) make them perform horribly and look ugly compared to using native `f`/`F`.

![Screen Recording 2023-07-24 at 8 00 26 PM](https://github.com/neovim/neovim/assets/56745535/992f9f29-1785-4c82-9f2b-06e12a5d1994)

### Expected behavior

There are already macro events like `RecordingEnter` and `RecordingLeave`. It would be cool if there were also autocmd events for macro execution. This way functionality like hlgroups, highlighting patterns, etc. can be disabled to improve performance when executing a macro that invokes a motion plugin in addition to avoiding visual clutter and flickering on the screen. Maybe an optional regex pattern could be provided to match macros that involve certain keys or sequences of keys. 

Thanks for your consideration!

**Comment by justinmk** [comment]
> This way functionality like hlgroups, highlighting patterns, etc. can be disabled to improve performance when executing a macro

Why can't `reg_executing()` be used for that purpose?

**Comment by Subjective** [comment]
You're right, I didn't even know that was a thing. Closing this issue now.

**Comment by justinmk** [comment]
No. You only need to check reg_executing() in once place if you structure your plugin to use a common handler for the relevant events.

**Comment by tomtomjhj** [comment]
> This way functionality like hlgroups, highlighting patterns, etc. can be disabled to improve performance when executing a macro

See also: `:help lazyredraw`
