### ISSUE TITLE
Resizing the terminal crashes Neovim

### ISSUE THREAD

**Issue by fredizzimo** [neovim/neovim#24471]
### Problem

When, you rapidly resize the built in terminal, Neovim will crash with a call stack like this
```
Stack trace of thread 105357:
#0  0x00007f620db7526c n/a (libc.so.6 + 0x8926c)
#1  0x00007f620db25a08 raise (libc.so.6 + 0x39a08)
#2  0x00007f620db0e538 abort (libc.so.6 + 0x22538)
#3  0x00007f620deed06b n/a (libvterm.so.0 + 0x706b)
#4  0x00007f620def0473 n/a (libvterm.so.0 + 0xa473)
#5  0x00007f620deea27d n/a (libvterm.so.0 + 0x427d)
#6  0x000055b922d8a407 terminal_check_size (nvim + 0x2ae407)
#7  0x000055b922dce60a win_set_inner_size (nvim + 0x2f260a)
#8  0x000055b922dce75d win_new_width (nvim + 0x2f275d)
#9  0x000055b922dbdf94 frame_new_width (nvim + 0x2e1f94)
#10 0x000055b922dbe643 win_new_screen_cols (nvim + 0x2e2643)
#11 0x000055b922dc15ef win_new_screensize (nvim + 0x2e55ef)
#12 0x000055b922bda3de screen_resize (nvim + 0xfe3de)
#13 0x000055b922d9e59f ui_refresh (nvim + 0x2c259f)
#14 0x000055b922b8faaa nvim_ui_try_resize (nvim + 0xb3aaa)
#15 0x000055b922b8327e handle_nvim_ui_try_resize (nvim + 0xa727e)
#16 0x000055b922ccb105 request_event (nvim + 0x1ef105)
#17 0x000055b922c2526b multiqueue_oneshot_event (nvim + 0x14926b)
#18 0x000055b922d706a8 state_handle_k_event (nvim + 0x2946a8)
#19 0x000055b922cd6d73 nv_event (nvim + 0x1fad73)
#20 0x000055b922cd2920 normal_execute (nvim + 0x1f6920)
#21 0x000055b922d7053f state_enter (nvim + 0x29453f)
#22 0x000055b922ccbde5 normal_enter (nvim + 0x1efde5)
#23 0x000055b922b5607c main (nvim + 0x7a07c)
#24 0x00007f620db0f850 n/a (libc.so.6 + 0x23850)
#25 0x00007f620db0f90a __libc_start_main (libc.so.6 + 0x2390a)
#26 0x000055b922b51045 _start (nvim + 0x75045)

Stack trace of thread 105359:
#0  0x0000000000000000 n/a (n/a + 0x0)
ELF object binary architecture: AMD x86-64
```

### Steps to reproduce

1.nvim
2. :terminal
3. Resize the window rapidly, and observe that it crashes very quickly

Or alternatively
1. nvim
2. :terminal
3. :vsplit
4. Grab the splitter and resize rapidly

### Expected behavior

Neovim should not crash.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-715+g5fb4c397a1

### Vim (not Nvim) behaves the same?

no, Vim 9.0

### Operating system/version

Arch Linux

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

AUR

**Comment by clason** [comment]
That's a known issue with long-term reflow; there's more details somewhere else (that I can't link right now on mobile).

**Comment by zeertzjq** [comment]
Duplicate of #23762

**Comment by clason** [comment]
I cannot reproduce this manually, fwiw (and Lord knows I tried...)

**Comment by fredizzimo** [comment]
It usually takes less than 10 seconds for me. But, I just noticed that the trick seems to be to make the window small enough so that the prompt wraps to the next line. I did not manage to make it crash if the prompt is not wrapped, even if the scrollback lines are.

**Comment by clason** [comment]
Well, yes, that part is assumed since we're talking about reflow. I still cannot reproduce this manually.
