### ISSUE TITLE
*feature* open the file in current Vim session by using a Vim terminal

### ISSUE THREAD

**Issue by aliev** [neovim/neovim#2448]
came up with an interesting (in my opinion) an option. made a small script (for code quality not scold, wrote in haste). For example, if you are in a Vim terminal and want to open the file in the current session of Vim you can run "vopen filename" and the file will open in the current session. script source: https://gist.github.com/aliev/ab24f3db9f89bfb86917
demo: http://youtu.be/3cQC7CCSM2I

what do you think about this feature?

**Comment by fwalch** [comment]
See http://www.reddit.com/r/neovim/comments/30kvl3/ive_been_using_the_experimental_terminal_mode_and/ for more scripts that do something similar.

**Comment by tarruda** [comment]
It might be interesting to add some runtime/autoload/*.vim script that does the same using the features introduced by #1446, which don't depend on python.

**Comment by aliev** [comment]
@fwalch wow! thank you!

**Comment by splinterofchaos** [comment]
Hmm, it looks to me like we also need a way of opening an RPC channel from a path

**Comment by fwalch** [comment]
More scripts! http://www.reddit.com/r/neovim/comments/3312tu/manage_the_parent_neovim_instance_from_terminal/

**Comment by justinmk** [comment]
Covered by 

https://github.com/neovim/neovim/issues/4109 

https://github.com/neovim/neovim/issues/3119 

https://github.com/neovim/neovim/issues/1750
