### ISSUE TITLE
Neovim :help page is cutting chars on comments

### ISSUE THREAD

**Issue by thespirit61** [neovim/neovim#24496]
### Problem

I do use Nerd Fonts (Hack) on my Windows Terminal. If I do use neovim and open the :help and look at the comments, the last chars are cutted. For better understanding, I will add picture. I already tried to change the Nerd font and it still happens.

Changing to a different font then a Nerd Font resolves that strange behaviour.
![2023-07-27_13-25-26](https://github.com/neovim/neovim/assets/110129538/8e36e99a-2450-49d8-989f-d50619630163)

This also happens on other files, where I use comments. For example ps1.

### Steps to reproduce

:help 

### Expected behavior

Last chars should not be cutted on comments.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 11 22H2

### Terminal name/version

Windows Terminal

### $TERM environment variable

-

### Installation

Winget

**Comment by seandewar** [comment]
This is a terminal/font issue. It's not rendering italics properly.
