### ISSUE TITLE
Calling `:Ntree` in a terminal buffer gives an error but seems to work as expected

### ISSUE THREAD

**Issue by asperan** [neovim/neovim#24498]
### Problem

Calling `:Ntree` to open netrw while in a terminal buffer gives an error:
![FirstError](https://github.com/neovim/neovim/assets/14941985/2d78a1e8-6e7d-4caf-95ec-5f11e3307882)

after closing the error dialog, a new window is created with another error message (and the cursor):
![SecondError](https://github.com/neovim/neovim/assets/14941985/82e3dfc8-d5d5-474f-8ccd-e2284e92e0fc)

but moving the cursor in the upper window shows netrw:
![ButStillWorking](https://github.com/neovim/neovim/assets/14941985/cb6f9f0d-4290-4d61-9275-0346a211a9e3)

It seems to work "as expected" (i.e. `:Ntree` show the file tree at `cwd`, but maybe it is a fallback) but it still gives an error message.

### Steps to reproduce

nvim --clean
:terminal
:Ntree

### Expected behavior

The command execution does not result in an error message, just in the file tree view.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

No, VIM - Vi IMproved 9.0 Included patches: 1-1632

### Operating system/version

openSUSE Tumbleweed snapshot 20230724-2409.1

### Terminal name/version

alacritty 0.12.2

### $TERM environment variable

alacritty

### Installation

System package manager

**Comment by zeertzjq** [comment]
The help for `:Ntree` doesn't mention anywhere that you can use it in a non-netrw buffer:
```
CHANGING TREE TOP			*netrw-ntree*  *:Ntree*  *netrw-gn* {{{2

One may specify a new tree top for tree listings using >

	:Ntree [dirname]

Without a "dirname", the current line is used (and any leading depth
information is elided).
With a "dirname", the specified directory name is used.

The "gn" map will take the word below the cursor and use that for
changing the top of the tree listing.
```
