### ISSUE TITLE
crashes when opening any file (OpenBSD 7.2)

### ISSUE THREAD

**Issue by WernerDrasche** [neovim/neovim#24514]
### Problem

command "nvim file.txt" crashes immediately.
nvim by itself works but once you open a file with ":e file.txt" it crashes.

### Steps to reproduce

I compiled latest release following the instructions:

cmake ../cmake.deps/ -DUSE_BUNDLED=OFF -DUSE_BUNDLED_LIBUV=ON -DUSE_BUNDLED_LUV=ON -DUSE_BUNDLED_LIBVTERM=ON -DUSE_BUNDLED_TS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=egcc

cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=egcc

I ran into a problem where dependency headers like <vterm.h> were different than the ones provided in .deps and it didn't compile at first (unknown symbol VTStringFragment or something like that). After replacing the includes with this script:

      import os
      
      BASE = os.getcwd()
      DEPS_BASE = ".deps/build/src/"
      SRC_BASE = "src/nvim/"
      
      deps = []
      for dep in os.listdir(DEPS_BASE):
          for path, name, files in os.walk(DEPS_BASE + dep + "/include"):
              for f in files:
                  if f.endswith(".h"):
                      deps.append((f, BASE + "/" + path + "/" + f))
      for path, name, files in os.walk(SRC_BASE):
          for f in files:
              if f.endswith(".c"):
                  contents = ""
                  with open(path + "/" + f, "r") as h:
                      contents = h.read()
                      for dep, p in deps:
                          if f"<{dep}>" in contents:
                              print(f"{f}: <{dep}> -> \"{p}\"")
                              contents = contents.replace(f"<{dep}>", f"\"{p}\"")
                              #print(contents[:500])
                  with open(path + "/" + f, "w") as h:
                      written = 0
                      while written < len(contents):
                          w = h.write(contents)
                          written += w
                          contents = contents[w:]
compilation worked and I got the executable that crashes when you open a file. 
.config/nvim
.local/share/nvim
.cache/nvim
have all been cleared. Also crashes after running :checkhealth eventhough :checkhealth doesn't give any errors. After further testing I can say that it crashes with almost every command. "!" works though.

### Expected behavior

Doesn't crash when opening a file.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

OpenBSD 7.2

### Terminal name/version

terminator 1.92

### $TERM environment variable

xterm-256color

### Installation

cmake

**Comment by dundargoc** [comment]
The crash is a red herring and frankly irrelevant. We should focus on fixing the root problem (compile error) rather than the modified version so other openbsd users can benefit.

Does it compile if you only use bundled dependencies?

**Comment by WernerDrasche** [comment]
The crashes are gone after compiling with all bundled. The only header in /usr/local/include that seems to be problematic is vterm.h, so an easy workaround is to rename it during compilation. Reordering -I/usr/local/include -I/home/x/build/neovim-stable/.deps/usr/include in the Makefile (or wherever it is defined) would probably fix it?

**Comment by dundargoc** [comment]
Unsure how that would help tbh. Also vterm.h isn't part of neovim but a dependency, libvterm. I have a strong suspicion what the problem might be. What version is your system libvterm (aka the non-bundled one)?

**Comment by WernerDrasche** [comment]
libvterm is from neovim 0.7.2 (package).
This is how the compilation error looks like (with -DUSE_BUNDLED_LIBVTERM=ON)

    /home/x/build/neovim-stable/src/nvim/terminal.c: In function 'term_settermprop':
    /home/x/build/neovim-stable/src/nvim/terminal.c:938:5: error: unknown type name 'VTermStringFragment'
      938 |     VTermStringFragment frag = val->string;
              |     ^~~~~~~~~~~~~~~~~~~

This is because the old libvterm header inside /usr/local/include differs from the one in .deps
Workaround: rename vterm.h to .bak inside /usr/local/include
Fix: prioritize headers from .deps before /usr/local/include headers in the makefile (if this is possible)

**Comment by clason** [comment]
Oh god yeah that's too old. You need to remove that.

**Comment by clason** [comment]
(Cmake picking up system headers for bundled dependencies is a known general problem.)

**Comment by dundargoc** [comment]
It should not matter whether a dependency comes from deps or from system. The dependency detection is lacking in this case. Neovim is not able to determine libvterm patch version because this information is not available in libvterm source code, and therefore cannot distinguish between 0.3.0 vs 0.3.2. We will need to send a patch to @leonerd to add a PATCH_VERSION (something like that) variable i vterm.h, as is already done with the major version and minor version.
