### ISSUE TITLE
Keymap containing `*` doesn't work as expected on nightly

### ISSUE THREAD

**Issue by lourenci** [neovim/neovim#24518]
### Problem

It is not possible to use the below keymap on `HEAD`:

```lua
vim.api.nvim_set_keymap("v", "<leader>rp", "*Ncgn", {noremap = false, silent = true})
```

This is not an issue on `stable`.

### Steps to reproduce

Open Neovim, create the keymap (`:lua vim.api.nvim_set_keymap("v", "<leader>rp", "*Ncgn", {noremap = false, silent = true})`) then try to use it.

### Expected behavior

It's expected to `*` the visual selection and then enter insert mode on that selection.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-741+g996dd36c7-Homebrew

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.4.1

### Terminal name/version

iTerm 2

### $TERM environment variable

tmux-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
`:h default-mappings`

**Comment by clason** [comment]
Can you bisect?

**Comment by justinmk** [comment]
`*` is a default mapping. `noremap = false` means you are enabled recursive mapping.

**Comment by clason** [comment]
But the claim is that this is a regression from 0.9.1, so if that is the issue, it shouldn't have worked before either. @lourenci can you verify this? Bisecting to which commit exactly changed the behavior would be helpful (if not necessary).

> (We should name that option remap or recursive...)

That's why we changed it for `vim.keymap.set` ;)

**Comment by clason** [comment]
Let's stick to the actual issue reported here, which is the _regression_ of behavior for the _same_ command. We can talk about what you want to achieve and how in a different (feature request) issue or discussion.

**Comment by justinmk** [comment]
The why is noremap=true part of the repro steps? That is a useless complication.

in vim 9.0.1424 i see the same behavior with:

    vnoremap x *Ncgn

**Comment by clason** [comment]
But the repro steps have `noremap=false`...
