### ISSUE TITLE
Assembly Syntax: Some Vector Register are missing

### ISSUE THREAD

**Issue by GabrielFrigo4** [neovim/neovim#24511]
### Problem

xmm16-xmm31 are missing
ymm16-ymm31 are missing
zmm0-zmm31 are missing
Register List: https://en.wikipedia.org/wiki/Advanced_Vector_Extensions
![image](https://github.com/neovim/neovim/assets/66432268/fa0339d9-802b-45de-93fd-4f8cdaf2ae12)

### Expected behavior

The expectation was that these registers would be included in the assembly syntax in NeoVim

**Comment by clason** [comment]
Syntax files are maintained outside this repo. Please contact the maintainer listed at the top of the respective file.

**Comment by GabrielFrigo4** [comment]
> Syntax files are maintained outside this repo. Please contact the maintainer listed at the top of the respective file.

In which repository is the assembly syntax file for neovim?

**Comment by clason** [comment]
Most are not in repos; you need to contact the maintainer via email then.

**Comment by GabrielFrigo4** [comment]
> Most are not in repos; you need to contact the maintainer via email then. (It's Vim's file, not Neovim's; we just copy them.)

I found the file asm.vim and masm.vim and nasm.vim among others in the repository of neovim, this is the file right? Well if that's it, can I fork it up and change them to add these missing records without contacting their maintainer?

**Comment by clason** [comment]
No. All changes _must_ go through Vim. We do not want to fork these (at least right now).

**Comment by clason** [comment]
...of the syntax file. This is the required (by Vim) first step.

**Comment by GabrielFrigo4** [comment]
The syntaxes have already been updated in the repository vim :)

**Comment by clason** [comment]
And already ported to Neovim.
