### ISSUE TITLE
Crash: marktree.c:744: marktree_itr_next_skip: Assertion failed

### ISSUE THREAD

**Issue by nghialm269** [neovim/neovim#24517]
### Problem

Neovim crashed with `src/nvim/marktree.c:744: marktree_itr_next_skip: Assertion 'itr->node->ptr[itr->i]->parent == itr->node' failed`

Backtrace: [bt.txt](https://github.com/neovim/neovim/files/12209649/bt.txt).

GIF: 
![output](https://github.com/neovim/neovim/assets/13317164/4a0acd25-5386-4d9b-b25e-13a2d6a45e87)

### Steps to reproduce

* Save minimal config to `my_issue.lua`:
```lua
for name, url in pairs({
	-- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
	-- some_plugin = 'https://github.com/author/plugin.nvim'
	plenary = "https://github.com/nvim-lua/plenary.nvim",
	neogit = "https://github.com/NeogitOrg/neogit",
	statuscol = "https://github.com/luukvbaal/statuscol.nvim",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

local builtin = require("statuscol.builtin")
require("statuscol").setup({
	segments = {
		{
			sign = { name = { ".*" } },
			click = "v:lua.ScSa",
		},
		{
			text = { builtin.lnumfunc, " " },
			condition = { true, builtin.not_empty },
			click = "v:lua.ScLa",
		},
	},
})

require("neogit").setup({})
```

* Initialize a git repository and stage `my_issue.lua`:
```sh
git init
git add my_issue.lua
```
* Launch nvim to install plugins from `my_issue.lua`:
```sh
nvim --clean -u my_issue.lua
```
* Quit Neovim: `:q`.
* Launch nvim with `:Neogit`:
```sh
nvim --clean -u my_issue.lua -c 'Neogit'
```
* Go to line `> Added my_issue.lua`, press `Tab` to expand.
* nvim crashed. 

### Expected behavior

Not crashed.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-741+g996dd36c7

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

arch

### Terminal name/version

alacritty 0.12.2

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/22801

**Comment by icholy** [comment]
This appears to be fixed on `master` after pulling these changes:

* https://github.com/neovim/neovim/commit/54225bdb021e64d09f98201bc0a610e2600b6473
* https://github.com/neovim/neovim/commit/79a558277b1b1520ee867fae2a914a2db1d67ec8

**Comment by icholy** [comment]
https://github.com/neovim/neovim/issues/27137

**Comment by searleser97** [comment]
also having this issue

```
nvim: /home/runner/work/neovim/neovim/src/nvim/marktree.c:1529: marktree_itr_next_skip: Assertion `itr->x->ptr[itr->i]->parent == itr->x' failed. 
```

**Comment by zeertzjq** [comment]
Please check out the latest commit and create a new issue if it still happens.
