### ISSUE TITLE
nvim term does not inherit environment variables

### ISSUE THREAD

**Issue by cathaysia** [neovim/neovim#24536]
### Problem

Generally, I use direnv + flake to manage my projects. But unfortunately, nvim term does not inherit the environment variables brought by direnv. After I start term, I have to manually do a direnv reload.

### Steps to reproduce

1. cd a_project_with_direnv_and_nix_flake
2. which cargo
> /nix/store/lnp941j5cghl6lg5ryfl0gnh8795mavn-rust-default-1.72.0-nightly-2023-06-16/bin/cargo
3. open term in nvim
4. which cargo
> ~/.nix-profile/bin/cargo

### Expected behavior

cargo should be on in step 2 and step 4

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

I don't know

### Operating system/version

fedora 38(macos has this behaviour also)

### Terminal name/version

wezterm 20230712-072601-f4abf8fd

### $TERM environment variable

xterm-256color

### Installation

nix-env -i nvim

**Comment by justinmk** [comment]
> open term in nvim

do not write vague things like this, say exactly what you did. E.g.:

```
nvim
:terminal
```

you also did not mention which env vars weren't inherited, but based on `which cargo` I guess direnv sets $PATH.

"env vars aren't inherited" sounds like the wrong diagnosis:  Nvim certainly inherits all env vars, this is a basic behavior.

this is most likely a misconfiguration of your 'shellcmdflag' option or something like that.

**Comment by heygarrett** [comment]
I'm running into the same issue, and I think it's result of the way `:terminal` initiates the value of `$SHELL`.

@cathaysia If you do `echo $PATH` from both your terminal and from an instance of `:terminal` in Neovim, do you see a difference between the two outputs? In my terminal I see the values that direnv added to my path at the front of the list, but from within the Neovim terminal I see them near the middle of the list.

I can reproduce this without Neovim, just by running an instance of my shell from within my terminal:

```
echo $PATH
fish
echo $PATH
```

**Comment by cathaysia** [comment]
this works for me. thanks :)

**Comment by heygarrett** [comment]
I think I found a better solution. It appears that the value of `$fish_user_paths` is added to the PATH in each new shell, so I deleted that universal variable and instead added its contents to my config.fish:

```fish
if status is-login
	fish_add_path --global \
		~/.local/bin \
		$GOPATH/bin \
		/opt/homebrew/bin \
		/opt/homebrew/sbin \
		/opt/homebrew/opt/fzf/bin
end
```

This works for me in that mason.nvim can still add its bin directory to the PATH in `:terminal` _and_ directories added by direnv don't get bumped to the middle of the list.

There seems to be a proposal to get rid of universal variables in fish anyway:
https://github.com/fish-shell/fish-shell/issues/7379

**Comment by ltuijnder** [comment]
@heygarrett  thanks for sharing your solution. I was encountering a similar issue with just purely bash. Even though I added the `eval "$(direnv hook bash)"` in my .bashrc.
Still not sure if this is a bug on nvim side or intended behavior from direnv as described in that one github issue you linked.

**Comment by towry** [comment]
1. set `vim.o.shell='fish'`
2. run `:lua=vim.env.PATH`, the output is correct, same as current shell's `echo $PATH`.
3. run `:!echo $PATH` output different content, not same with current shell's `echo $PATH`.

My attempt solution is to change the `shellcmdflag` to make it use the `vim.env.PATH`.

```
vim.o.shellcmdflag = ('--init-command="set PATH %s" -Pc'):format(vim.env.PATH)
```

`--init-command` is fish's option to run after config loaded and before `-c` is executed.

Now, `:!echo $PATH` output same as current shell's `echo $PATH` and `!cargo` command runs correct.
