### ISSUE TITLE
Bold text in bright color in terminal buffer

### ISSUE THREAD

**Issue by cHoco** [neovim/neovim#2453]
Hello, really enjoy the terminal integration. Unfortunatly I don't get consistent colors between the terminal buffer and the terminal itself.
In particular the text in bold is colored with the "bright" colors. Here's a screenshoot showing the difference
![schermata 2015-04-18 alle 22 19 59](https://cloud.githubusercontent.com/assets/85527/7217117/808c9a68-e619-11e4-9d21-8bb259bb9a4c.png)

My setup, OSX Terminal.app, 16-color scheme

**Comment by splinterofchaos** [comment]
Could you post your test script? Thank you.

**Comment by cHoco** [comment]
Yeah sure, using this https://github.com/blueyed/dotfiles/blob/master/usr/bin/colors-table

**Comment by cHoco** [comment]
Hey just wondering, any update? Is anyone able to reproduce this behavior? 
Simple command  to check the error

```
printf "\033[32;1m BOLD \033[0m - \033[32m NOT BOLD \033[0m\n" 
```

**Comment by Pyrohh** [comment]
I get when running that command:
![lel](https://cloud.githubusercontent.com/assets/4174345/7420615/e375f9a4-ef4b-11e4-9606-a647c5a00b94.png)

This is all in tmux in case you're wondering.

**Comment by cHoco** [comment]
So you get different color just like me. I'd like to note that this doesn't seem happen if the terminal theme has 256 colors

**Comment by aubble** [comment]
@cHoco nothing to really do with this but what colour scheme are you using for OS X? looks really good.

**Comment by cHoco** [comment]
@aubble Hi, the colorscheme is base16 ocean. If you want to use it with OS X official Terminal app instead of iTerm 2 you'll have to tweak it since the colors are defined in the wrong colorspace. The font is Source Code Pro, regular weight. You can find all my configuration here https://github.com/cHoco/dotFiles :)

**Comment by aubble** [comment]
thank you very much :D

**Comment by aubble** [comment]
gonna assume the one in your repo is the tweaked version? Also any vim theme to go with it? Sorry if it seems like I'm copying your config, just trying to find something to start me off on vim, I can't stand how ugly it is default, really bothers me lol. aesthetics are op.

**Comment by cHoco** [comment]
Fixed in https://github.com/neovim/neovim/pull/3333

**Comment by SShrike** [comment]
Sorry for this notification to all subscribers, but what syntax theme are you using? @cHoco

**Comment by nhooyr** [comment]
@SShrike https://github.com/cHoco/dotFiles

**Comment by SShrike** [comment]
@nhooyr Thanks! Had looked in there an hour or two ago but was on my phone so I missed the vimrc at the project root.
