### ISSUE TITLE
Cannot open file whose filename or folder name has parenthesis "(" on Windows

### ISSUE THREAD

**Issue by xarthurx** [neovim/neovim#24542]
### Problem

As the title says, I cannot open files that have "(" or ")" in their file name or folder structure.
It looks like the path `xxx\(abc)\(edf).jsx` will be interpreted incorrectly due to the "escaping" effect.

If I do `:e <file/folder auto-complete>` the file names can be completed if I use `/` instead of `\`. But somehow nvim will change `/` to `\` automatically when opening the file.

Then, all file paths like `xxx\(index)\(index).jsx` will be interpreted to `xxx(index)(index).jsx` due to the "char escaping" mechanism...

![image](https://github.com/neovim/neovim/assets/1921878/169660bb-f949-4581-9356-f2d1351204a9)

### Steps to reproduce

- create a folder/file with path like: `xxx\(index)\(index).jsx`
- Open the file, either by `:e <file path` or drag-and-drop in GUI.
- The file cannot be opened/showing empty file.

### Expected behavior

Open the files correctly.

### Neovim version (nvim -v)

v0.9.1

### Vim (not Nvim) behaves the same?

don't know. I don't have vim.

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal

### $TERM environment variable

don't know what this means

### Installation

winget

**Comment by xarthurx** [comment]
Not sure if this should be the solution:
https://stackoverflow.com/questions/18464038/is-it-possible-to-make-vim-use-forward-slashes-on-windows

**Comment by zeertzjq** [comment]
`:h 'shellslash'`
`:h 'completeslash'`
I don't think there is anything else that can be done about this issue, because this is how filename expansion works.
