### ISSUE TITLE
Freeze on loading too much diagnostics with gopls

### ISSUE THREAD

**Issue by imxyy1soope1** [neovim/neovim#24543]
### Problem

Neovim freeze when loading a workspace which has too many diagnostics with [NvimTree](https://github.com/nvim-tree/nvim-tree.lua) opened.

## Minimal code
`my_issue.lua`:
```lua
for name, url in pairs{
	mason = 'https://github.com/williamboman/mason.nvim',
	['mason-lspconfig'] = 'https://github.com/williamboman/mason-lspconfig',
	['nvim-lspconfig'] = 'https://github.com/neovim/nvim-lspconfig',
	['nvim-tree'] = 'https://github.com/nvim-tree/nvim-tree.lua'
} do
	local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
	end
	vim.opt.runtimepath:append(install_path)
end

require('mason').setup()
require('mason-lspconfig').setup({
	ensure_installed = {
		"gopls"
	}
})
require('lspconfig').gopls.setup({
	capabilities = {}
})

require('nvim-tree').setup({
	diagnostics = {
		enable = true,
		debounce_delay = 0,
		show_on_dirs = true
	}
})
```

## Steps
1. `git clone https://github.com/go-musicfox/go-musicfox  # A example repo`
2. `nvim --clean -u my_issue.lua`
3. `:NvimTreeOpen`
4. Use hjkl in NvimTree to navigate to go-musicfox/pkg/ui
5. Use Tab to open several files in the directory
6. Freeze!

## Behavior
Exactly as described in issue #23740 

### Expected behavior

Not freezing

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux x86_64 6.4.7-zen1-2-zen

### Terminal name/version

alacritty 0.12.2-1

### $TERM environment variable

alacritty

### Installation

system package manager

**Comment by zeertzjq** [comment]
Shouldn't this be reported to nvim-tree?

**Comment by imxyy1soope1** [comment]
> Shouldn't this be reported to nvim-tree?

I know, but this doesn't happen only when using NvimTree; many LSP-related operations can trigger a freeze of the nvim process.
This is just one way to reproduce.

**Comment by imxyy1soope1** [comment]
> How big is the project/workspace? #23291

72K

**Comment by imxyy1soope1** [comment]
![image](https://github.com/neovim/neovim/assets/103114856/39fe3f67-cfea-485e-9631-253c3f54078e)

**Comment by glepnir** [comment]
To better reproduce your problem please use the standard minimal configuration. It is best not to add any third-party plugins.

```lua
vim.lsp.start({
  name = 'gopls',
  cmd = { 'gopls' },
  root_dir = vim.fs.dirname(vim.fs.find({ 'go.mod' }, { upward = true })[1]),
})
```

**Comment by imxyy1soope1** [comment]
OK, here is the minimal config.
min.lua:
```lua
local install_path = vim.fn.fnamemodify('nvim_issue/nvimtree', ':p')
if vim.fn.isdirectory(install_path) == 0 then
        vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/nvim-tree/nvim-tree.lua', install_path }
end
vim.opt.runtimepath:append(install_path)

require('nvim-tree').setup({
        diagnostics = {
                enable = true,
                debounce_delay = 0,
                show_on_dirs = true
        }
})

vim.api.nvim_create_autocmd('FileType', {
        pattern = 'go',
        callback = function()
                vim.lsp.start({
                        name = 'gopls',
                        cmd = { 'gopls' },
                        root_dir = vim.fs.dirname(vim.fs.find({ 'go.mod' }, { upward = true })[1])
                })
        end
})
```
Steps to reproduce:
1. Install `go` and `gopls`
2. `git clone https://github.com/go-musicfox/go-musicfox.git example`
3. `nvim --clean -u min.lua`
4. `:NvimTreeOpen`
5. Use hjkl to navigate to `example/pkg/ui`
6. Use hjkl and Tab to open different files in the directory (in a fast speed)
7. Freeze!

**Comment by zeertzjq** [comment]
Hmm, there seems a be an infinite timer loop.

**Comment by zeertzjq** [comment]
Why are you using `debounce_delay = 0`?

**Comment by ddaniel27** [comment]
Did you resolve this issue @imxyy1soope1 ?

**Comment by imxyy1soope1** [comment]
Certainly.

Sorry that I've forgotten this issue thousands of years ago.
