### ISSUE TITLE
cirrus CI job "external_deps" is broken

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#24544]
### Problem

`external_deps` cirrus job has been broken for several days.

Example: https://cirrus-ci.com/task/4614232793153536

    Failed to start an instance! Failed to pull null image! Repository does not exist or may require authentication.
    Container errored with 'ImagePullBackOff: Back-off pulling image "[gcr.io/cirrus-ci-community/neovim/neovim/ci/dockerfileexternal_deps:a467741fcc2bc142110abf746b36bf60](http://gcr.io/cirrus-ci-community/neovim/neovim/ci/dockerfileexternal_deps:a467741fcc2bc142110abf746b36bf60)"'

can't tell if this is an issue with gcr.io (google artifact registry), cirrus, or something else...

### Expected behavior

I expect `external_deps` not to fail constantly.

**Comment by zeertzjq** [comment]
Seems fixed now.
