### ISSUE TITLE
Cursor shape inside tmux that runs in Konsole (with KONSOLE_DBUS_SESSION variable)

### ISSUE THREAD

**Issue by msva** [neovim/neovim#24546]
### Problem

Hi there!
I'm sometimes using nvim inside tmux that runs inside tmux, which runs in Konsole.
(In some cases I even pass KONSOLE_* variables over ssh to make some nvim-irrelevant things to work).

As far as I understand, `nvim` detects whether it runs in `konsole`/`yakuake` by checking `KONSOLE_DBUS_SESSION` variable.
And, it seems, that check has higher priority over checking for tmux (although, I failed to find an evidence in `src/nvim/tui/tui.c`).

Anyway, the problem is that nvim doestn't change cursor shape when it runs inside tmux (where I have set up overriding of `Se`/`Ss` to `Konsole`'s code) and there is `KONSOLE_DBUS_SESSION` variable in the environment.

If I unset it, it works like a charm.

Also, previously I had following in the config, but it stoped working since one of the last updates:
```Lua
-- hack to stop nvim to detect Konsole when in tmux
-- (I made cursor management stuff in tmux instead).    
if os.getenv("TERM"):match"^tmux*" then    
  cmd([[unlet $KONSOLE_DBUS_SERVICE | unlet $KONSOLE_DBUS_SESSION | ]]    
    .. [[unlet $KONSOLE_PROFILE_NAME | unlet $KONSOLE_VERSION]])    
end
```

Looks like now nvim checks cursor shaping things before reading the config :shrug: 

Anyway, I don't know how to resolve that issue, as I need those variables to be set for other things to work, so I can't unset them in the shell.
And, it seems, there is no way to unset them within nvim anymore.

Maybe nvim need a special handle for that situation (konsole+tmux)?
Or, at least, prioritize check for tmux over check for konsole? :shrug: 

### Steps to reproduce

1. Run Konsole or Yakuake
2. run nvim (even `nvim --clean`) and see it changes cursor shapes between normal and insert modes
4. exit nvim, run tmux (with terminal-overriding set up properly and `KONSOLE_*`-variables in `update-environment`)
5. run nvim (even clean) and see it don't change cursor shape at all
6. exit nvim, unset `KONSOLE_*` variables in the shell
7. run nvim again and see, it changes cursor shapes again pretty well

### Expected behavior

 Cursor shape changing works even without unsetting `KONSOLE_*` vars

### Neovim version (nvim -v)

v0.10.0-dev-729+g74bd4aba5-dirty

### Vim (not Nvim) behaves the same?

irrelevant

### Operating system/version

Gentoo

### Terminal name/version

Konsole 23.04.2

### $TERM environment variable

xterm-256color and konsole-256color

### Installation

Official Gentoo package

**Comment by zeertzjq** [comment]
> where I have set up overriding of Se/Ss to Konsole's code

What does this mean?

**Comment by msva** [comment]
> What does this mean?

```tmux                                                                                                                            
# Konsole
# Cursor shape: Ss=set, Se=reset
set -gas terminal-overrides ',konsole*:Ss=\E]50;CursorShape=%?%p1%{3}%<%t%{0}%e%p1%{5}%<%t%{2}%e%{1}%;%d;BlinkingCursorEnabled=%?%p1%{1}%<%t%{1}%e%p1%{1}%&%;%d\007:Se=\E]50;CursorShape=1;BlinkingCursorEnabled=1\007'
# Cursor colors: Cs=set, Cr=reset
set -gas terminal-overrides ',konsole*:Cs=\E]50;UseCustomCursorColor=1;CustomCursorColor=%p1%s\007:Cr=\E]50;UseCustomCursorColor=0\007'
```

**Comment by msva** [comment]
well, although, current Konsole version annyway supports XTerm's codes, so this is not even needed, and it is enough to just
```tmux
set -gas terminal-overrides ',xterm*:Ss=\E[%p1%d q:Se=\E[2 q'
```

Anyway, it works fine with both ways, if remove `KONSOLE_*` vars

**Comment by zeertzjq** [comment]
Wait... Why is `$TERM` set to `xterm-256color` or `konsole-256color` inside tmux? It should be `tmux-256color`.

**Comment by zeertzjq** [comment]
Cannot reproduce. When using the tmux configs mentioned below, cursor shape either works both inside and outside Nvim, or neither.

**Comment by justinmk** [comment]
> current Konsole version annyway supports XTerm's codes,

Ah right. And we aren't going to spend time supporting the old konsole if we can avoid it.

It turns out when you add a bunch of junk to 3+ layers of terminals, things get weird.

**Comment by msva** [comment]
> > current Konsole version annyway supports XTerm's codes,
> 
> Ah right. And we aren't going to spend time supporting the old konsole if we can avoid it.

Yeah, but now nvim somewhy still trying to detect the Konsole and handle it separately (I guess, it tries to use Konsole's `Ss` inside tmux, while tmux waits for xterm's, and that is why this issue appears.

Because when nvim don't detect Konsole (after unsetting KONSOLE variables), all works fine (I guess, nvim uses codes from tmux terminfo (which are identical to xterm ones))

**Comment by msva** [comment]
> Wait... Why is `$TERM` set to `xterm-256color` or `konsole-256color` inside tmux? It should be `tmux-256color`.

IIRC, no: that terms in `set` commands belongs to the TERM outside of `tmux`. And, AFAIU, it is "which code tmux should send outside, when it receive corresponding codes from aplication.

So, when nvim doesn't recognize Konsole because of variables, it sends correct `Ss` codes to change the shape, and it works.
But when it thinks it runs in Konsole (while actually in tmux, which is in Konsole), and it, I guess, sends Konsole's codes, which tmux doesn't recognize, so don't proxy them outside.

At least, how I imagine the situation.

**Comment by zeertzjq** [comment]
That's what I thought you were trying to mean as well, and I cannot reproduce this.

**Comment by justinmk** [comment]
Ok what about this patch:

```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 0983667695c2..da1173cd9e25 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -289,12 +289,9 @@ static void terminfo_start(TUIData *tui)
   bool iterm_env = termprg && strstr(termprg, "iTerm.app");
   bool nsterm = (termprg && strstr(termprg, "Apple_Terminal"))
                 || terminfo_is_term_family(term, "nsterm");
-  bool konsole = terminfo_is_term_family(term, "konsole")
-                 || os_getenv("KONSOLE_PROFILE_NAME")
-                 || os_getenv("KONSOLE_DBUS_SESSION");
+  bool konsole = terminfo_is_term_family(term, "konsole");
   const char *konsolev_env = os_getenv("KONSOLE_VERSION");
-  long konsolev = konsolev_env ? strtol(konsolev_env, NULL, 10)
-                               : (konsole ? 1 : 0);
+  long konsolev = (konsole && konsolev_env) ? strtol(konsolev_env, NULL, 10) : 0;
 
   patch_terminfo_bugs(tui, term, colorterm, vtev, konsolev, iterm_env, nsterm);
   augment_terminfo(tui, term, vtev, konsolev, iterm_env, nsterm);
```

That changes our "is this konsole" decision to _require_ `TERM=*konsole*`, which makes the logic more intentional and simpler. And removes the sloppy guessing based on `KONSOLE_XX` env vars.

**Comment by justinmk** [comment]
> Maybe look for `ACTUALLY_I_USE_KONSOLE` variable?

That just never works because the layers just pile up.

> But on the other, that will shoot in the legs of the users that set `TERM=xterm-{256color,direct256}` in Konsole for some reasons

The worst case is that their cursor shape might not work? And we gain easier-to-reason-about behavior.

**Comment by zeertzjq** [comment]
Doesn't Konsole set `$TERM` to `xterm-256color` by default?

**Comment by msva** [comment]
> The worst case is that their cursor shape might not work? And we gain easier-to-reason-about behavior.

Yeah. Well, I think, they will anyway be able to find this issue and read the reasoning, if any, so, yes, maybe it is not worth to bothering of supporting that kludges

**Comment by msva** [comment]
> Doesn't Konsole set `$TERM` to `xterm-256color` by default?

Thanks for the point...

It seems, it is: https://github.com/search?q=repo%3AKDE%2Fkonsole+xterm-256color&type=code

**Comment by msva** [comment]
although, again, I think, it will be enough to add a paragraph about that documentation, like it was done for tmux (`:h tui-cursor-tmux`). So, we can add `tui-cursor-konsole` suggest user to setup TERM to `konsole-256color` :shrug:
