### ISSUE TITLE
vim.lsp.buf.implementation doesn't push to tag stack.

### ISSUE THREAD

**Issue by newro** [neovim/neovim#24540]
### Problem

I am developing go language.

In go language, I am using gopls as LSP Server, and when I tried to use 'go to implementation' in neovim through several plugins such as vim-go and coc, I found that tag stack does not work normally. I kept testing to find the cause, and eventually found that vim.lsp.buf.implentation in neovim is an error.
I used the same plugin in vim and the tag stack worked fine in the same situation.

I found that if there is only one implementation of the interface that is the target of the 'go to implementation', the tag stack works fine, but if there is more than one implementation, it jumps to that location, but the tag stack does not stack.

The 'go to definition' works fine, which makes sense when you think about it. I would like the tag stack to work fine for the jump behavior for 2 or more implementations.

### Steps to reproduce using "nvim -u minimal_init.lua"

local pattern = 'go' 
local cmd = {'gopls'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'.git', '.editorconfig'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
▏ pattern = pattern,
▏ callback = function(args)
▏ ▏ local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
▏ ▏ local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
▏ ▏ vim.lsp.start({
▏ ▏ ▏ name = 'bugged-ls',
▏ ▏ ▏ cmd = cmd,
▏ ▏ ▏ root_dir = root_dir,
▏ ▏ ▏ settings = settings
▏ ▏ })
▏ end
})

### Expected behavior

Storing in the tag stack normally

### Neovim version (nvim -v)

NVIM v0.9.1

### Language server name/version

golang.org/x/tools/gopls v0.13.1

### Operating system/version

mac osx 13.4.1 ventura

**Comment by glepnir** [comment]
because when result only have one there ran into `util.jump_to_location` function it will set `tagstck` when have  multiple results it will ran into `setqflist` so the tagstck not set.
