### ISSUE TITLE
Pasting from Windows adds unwanted newlines

### ISSUE THREAD

**Issue by IceSentry** [neovim/neovim#24569]
### Problem

When copying something without any newlines from notepad, I can easily copy it inline in notepad but when in neovim the content of the clipboard always gets pasted to a new line.

When using `clipboard=unnamedplus` this behaviour seems to happen to anything I have in the clipboard including things yanked directly in nvim. If I yank something in nvim and then paste it in notepad it will correctly paste the content inline but in nvim it will always add it to a newline.

At first I thought the issue was me doing something wrong or maybe a config was wrong but the issue also happens with a clean config and doesn't happen when using `gvim`.

I'm very new to the vim world so I apologize if this is expected behaviour.

I'm not sure how to share a minimal reproduction since it involves manually copying from something outside of nvim.

Here's a short video showing what happens:
Left is gvim, middle is neovim inside of windows terminal, right is notepad. I used `p` to paste in vim and neovim. Both vim and nvim have `:set clipboard=unnamedplus`

https://github.com/neovim/neovim/assets/8348954/3fddf865-def1-43b0-beb6-bd3f394a6a69

### Steps to reproduce
```lua
nvim --clean
:set clipboard=unnamedplus

-- copy something from notepad without any newlines

-- move the neovim cursor in the middle of a line of text
-- also happens with `p` or `P`
:put

-- the content will be added to a new line instead of next to the cursor
```
### Expected behavior

I would expect neovim to paste inline when the content of the clipboard doesn't have a newline.

### Neovim version (nvim -v)

v0.9.1

### Vim (not Nvim) behaves the same?

no. vim 9.0

### Operating system/version

Windows 10 Version 22H2

### Terminal name/version

Windows Terminal, Neovide

### $TERM environment variable

empty

### Installation

scoop

**Comment by IceSentry** [comment]
So, I tried it in the 0.10 pre-release and it seems to work as expected without any new lines. So I guess this is fixed? I'll play with it a bit more before closing the issue

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/22566 Thanks for following up.
