### ISSUE TITLE
Add `split` options for `vim.lsp.buf.definition` to allow splitting a window rather than jump

### ISSUE THREAD

**Issue by ofseed** [neovim/neovim#24562]
### Problem

There are many methods in `vim.lsp.buf` to allow users to jump to a specific location,
Eg.
- `vim.lsp.buf.declaration()`
- `vim.lsp.buf.definition()`
- `vim.lsp.buf.type_definition()`

Of course, there is API(`on_list`) to allow users to customize the behavior,
but considering there is another option(`reuse_win`) to customize the specific behavior of the jump, some other options may be needed.

### Expected behavior

Add an option to allow users to split a new window rather than jump to the location,
that is, if I call the function like this:
```lua
vim.lsp.buf.definition { split = true }
```
the result location will be shown In a new window like the `:help` command does.

**I'm willing to implement this feature, but I don't know would the community need it.**

**Comment by mfussenegger** [comment]
If you have tagfunc set to lsp (which is set by default) you can also use `ctrl+w ]` to jump to the definition in a new split window.
