### ISSUE TITLE
Kitty - Pressing enter in netrw does not open files

### ISSUE THREAD

**Issue by Sharkitty** [neovim/neovim#24577]
### Problem

When I use netrw inside neovim from kitty terminal, then press enter to open a file, the cursor moves down instead of opening the file or changing directory. I also have a similar issue in telescope where pressing enter to open the file I chose in the fuzzy finder will move the cursor all the way down and break the prompt instead of opening the file (Although I marked this as a netrw issue as telescope is a third party plugin).

In insert mode I have the expected behavior however.

This issue only happens in kitty, if I use another terminal emulator like the XFCE terminal I have the expected behavior.

I use a French AZERTY keyboard and I suspect this may play a role in this issue as I've never experienced this on my main machine which has a QWERTY keyboard.

I also posted an issue on kitty git, and the maintainer indicated me that it may be related to the implementation of the Kitty Keyboard Protocol in Neovim.
[Kitty issue #6527](https://github.com/kovidgoyal/kitty/issues/6527)

### Steps to reproduce

- Open neovim in kitty terminal.
- Use `:Explore` to open netrw.
- Select a file and press enter to open it.
- The cursor should move down.

### Expected behavior

Pressing enter in netrw should open a file or change directory.

### Neovim version (nvim -v)

0.9.1-1.1

### Vim (not Nvim) behaves the same?

Vim 9.0.1632-2.1. No but it has another issue which was filed here: https://github.com/vim/vim/issues/12731

### Operating system/version

OpenSUSE Tumbleweed

### Terminal name/version

kitty 0.29.2

### $TERM environment variable

xterm-kitty

### Installation

System package manager (zypper, official repositories)

**Comment by zeertzjq** [comment]
Does this work?
```vim
nmap <kEnter> <Enter>
```

**Comment by Sharkitty** [comment]
> Does this work?
> 
> ```viml
> nmap <kEnter> <Enter>
> ```

Yes it does, and `imap <kEnter> <Enter>` fixes telescope.

I also added this to my config so it's permanent and makes the replacement for all modes:
```
-- Fix kitty Enter key
vim.api.nvim_set_keymap("", "<kEnter>", "<Enter>", {})
vim.api.nvim_set_keymap("i", "<kEnter>", "<Enter>", {})
vim.api.nvim_set_keymap("c", "<kEnter>", "<Enter>", {})
```

Thanks you for the help! :cat: 
I think however, that this is just a workaround and doesn't fix its cause. I'm not familiar with this kitty keyboard protocol so I don't know what could be done about it to make a proper fix sadly.

**Comment by zeertzjq** [comment]
If there is only one Enter key on the keyboard, then it sounds more like a bug in the keyboard itself. Does the same thing happen if you use GVim?

**Comment by Sharkitty** [comment]
Yes there is only one Enter key. A keyboard bug is possible but it would be weird that I only encounter it with these specific softwares then.

I haven't tried GVim but as I said it only happens in Kitty. I tried in XFCE terminal and neither vim nor nvim have issues with this key there. I can try GVim tomorrow if you think that's necessary, but I think my test in XFCE terminal already shows that running vim and nvim in a different environment on the same machine provides different results.

**Comment by zeertzjq** [comment]
XFCE doesn't support keypad Enter key, so it just sends it as a normal Enter key. kitty is one of the few terminal emulators that support this, and GVim of course supports this, so comparing Nvim in kitty with GVim is more reasonable.

**Comment by Sharkitty** [comment]
> XFCE terminal doesn't support keypad Enter key, so it just sends it as a normal Enter key. kitty is one of the few terminal emulators that support this, and GVim of course supports this, so comparing Nvim in kitty with GVim is more reasonable.

Ah, I see! Thanks for the explanation. I'll try that tomorrow then and let you know the results then.

**Comment by Sharkitty** [comment]
I just tried gvim, and I have the same behavior as with nvim in kitty. I can enter command, I can create new line from insert mode, but in netrw pressing enter moves the cursor down. Here as well, running `:nmap <kEnter> <Enter>` fixes netrw.

**Comment by justinmk** [comment]
> I just tried gvim, and I have the same behavior as with nvim in kitty.

Thanks for mentioning that @Sharkitty . That makes sense because the entire point of the kitty protocol (and `h tui-modifyOtherKeys`) is to have higher fidelity of keypresses, like a GUI.

So this is most likely just a netrw "bug" or some other netrw choice.

We need a label for all these issues about "I'm using kitty protocol and am surprised by the results that I explicitly requestsed".

**Comment by Sharkitty** [comment]
Considering all the points suggesting a keyboard bug and not really a neovim bug, I think that unless other users report encountering the same problem, it might be best to close this issue. That way I won't take anyone's time looking for a unicorn while it's most likely just my hardware being weird. Thanks everyone for the help.
