### ISSUE TITLE
Wrong filler lines in linematch diff mode

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#24580]
### Problem

In diff mode with `diffopt+=linematch:N`, if a hunk contains a changed line and add lines, and is larger than `N`, then the filler lines that start from the top line of the window are not shown.

### Steps to reproduce

```sh
nvim --clean
```
```vim
call setline(1, range(30))
vnew
call setline(1, ['00', '29'])
windo diffthis
exe "normal! \<C-e>"
```

With `set diffopt+=linematch:10`:
![image](https://github.com/neovim/neovim/assets/19489738/a59eaa3f-d629-4591-a52c-a9783d1b123e)

### Expected behavior

With `set diffopt&vim` or `set diffopt+=linematch:60`:
![image](https://github.com/neovim/neovim/assets/19489738/3ed93873-6a00-4372-805a-59eb2340c7af)

### Neovim version (nvim -v)

0.9 and 0.10-dev 42630923fc00633d806af97c1792b2ed4a71e1cc

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

ubuntu 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

tmux-256color

### Installation

appimage

**Comment by lewis6991** [comment]
@jwhite510
