### ISSUE TITLE
`nvim_get_hl()` creates undefined highlight groups

### ISSUE THREAD

**Issue by Bekaboo** [neovim/neovim#24583]
### Problem

`nvim_get_hl(<ns>, { name = 'Foo' })` creates a cleared highlight group `hl-Foo` if `hl-Foo` does not exist, which is an undocumented side effect.

This affects regions highlighted by non-existing highlight groups in a winbar: consider a winbar set to `%#Foo#abcd%*`, if `hl-Foo` does not exist, highlight of `abcd` will fall back to `hl-WinBar` or `hl-WinBarNC`, however if `hl-Foo` is a cleared highlight group, the color of `abcd` will fall back to `hl-Normal`.

### Steps to reproduce

1. nvim --clean
2. `:echo hlexists('Foo')` --> 0
3. `:call nvim_get_hl(0, { 'name' = 'Foo' })`
4. `:echo hlexists('Foo')` --> 1

### Expected behavior

1. nvim --clean
2. `:echo hlexists('Foo')` --> 0
3. `:call nvim_get_hl(0, { 'name' = 'Foo' })`
4. `:echo hlexists('Foo')` --> 0

### Neovim version (nvim -v)

NVIM v0.10.0-dev-751+gd086bc1e85

### Vim (not Nvim) behaves the same?

no, vim does not have `nvim_get_hl()`

### Operating system/version

Linux 6.1.39-2-lts

### Terminal name/version

wezterm 20230709-182848-f901dfbf

### $TERM environment variable

tmux-256color

### Installation

AUR

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/issues/23474
