### ISSUE TITLE
Invalid winhighlight accepted

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#24586]
### Problem

Invalid `winhighlight` accepted.

### Steps to reproduce

```
nvim --clean
```

```vim
:set winhighlight='Normal:Visual'
:set winhighlight?
```

(outputs `winhighlight='Normal:Visual'`)

### Expected behavior

Since the `winhighlight` is surrounded by quotes, I expected the value to not be accepted, as the following error is produced.
```
E5248: Invalid character in group name
```

Under the actual behavior, the invalid `winhighlight` is set. This eventually becomes a problem (e.g., when splitting the window).

For other options like `textwidth` and `spelloptions`, setting an invalid option results in an error, and the the invalid option is not set.

### Neovim version (nvim -v)

v0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Kubuntu 23.04

### Terminal name/version

Konsole 22.12.3

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by justinmk** [comment]
How can this work if `:silent!` is given, which silences errors?

**Comment by dstein64** [comment]
> "How can this work if :silent! is given, which silences errors?"

I've updated the description and title to better reflect the issue. The original example had similar conditions for which I observed the behavior, but I think the updated version better conveys the issue: using "silent!" doesn't just prevent an error, but rather allows a problematic value to be `:set`.
