### ISSUE TITLE
Neovim bug reports

### ISSUE THREAD

**Issue by davydovanton** [neovim/neovim#2459]
Hello and thanks for neovim :tada: 
After using neovim I found some bugs:

1. Not working line compilation (`<C-x><C-l>`)
2. Not working windows switching mappings (`<C-w><C-j>`, `<C-w><C-h>`, etc)
3. When I open neovim in tmux session all my custom colorchemes work correct, but if I just open neovim in terminal (I use zsh) I will see that only standart colorchemes working correct (I use Vundle for install this. All other plugins work correct).
4. ~~In vim I [overrided](https://github.com/davydovanton/dotfiles/blob/master/vim/vimrc#L337-L343) `&t_SI` and `&t_EI` options, but in neovim it's not work~~ (I found solution [here](https://github.com/neovim/neovim/wiki/FAQ#how-can-i-change-the-cursor-shape-in-the-terminal))

Thanks.

**Comment by glts** [comment]
1. Line completion with `<C-X><C-L>` works fine.
2. Switching to another window with `<C-W>l` or `<C-W><C-L>` etc. works fine.

Just tried it on master. Please always try to reproduce with no vimrc, `nvim -u NONE`. If some plugin is remapping your commands you can find out by running eg `:verbose map <C-X><C-L>`.

**Comment by davydovanton** [comment]
@glts thank you for comment. 

My neovim version:
```
~ » nvim --version                                                                                                                            14:56:48
NVIM 0.0.0-alpha+201504181652 (compiled Apr 19 2015 00:11:20)
Commit: 639504894610361198447ddaaa557b4877136682
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150419-2779-1e7taup/build/config -I/tmp/neovim20150419-2779-1e7taup/src -I/tmp/neovim20150419-2779-1e7taup/.deps/usr/include -I/tmp/neovim20150419-2779-1e7taup/.deps/usr/include -I/tmp/neovim20150419-2779-1e7taup/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150419-2779-1e7taup/.deps/usr/include -I/tmp/neovim20150419-2779-1e7taup/.deps/usr/include -I/tmp/neovim20150419-2779-1e7taup/.deps/usr/include -I/tmp/neovim20150419-2779-1e7taup/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim20150419-2779-1e7taup/build/src/nvim/auto -I/tmp/neovim20150419-2779-1e7taup/build/include
Compiled by anton@MacBook-Pro.local

Optional features included (+) or not (-): +acl  +iconv
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

Mac OS 10.10.3

I tried to call line completion and window switching in default config (`nvim -u NONE`). It's work fine. After that I tried to call this methods with my .nvimrc file and this work fine :open_mouth:

**Comment by Pyrohh** [comment]
@davydovanton could you expand on number 3, specifically with screenshots? It sounds like that's your only remaining issue.

**Comment by davydovanton** [comment]
@Pyrohh of course. 
First image. I open neovim in my `~` directory with custom [colorscheme](https://github.com/davydovanton/dotfiles/blob/master/vim/vimrc#L40) (installed with Vundle)
![screenshot 2015-04-20 23 20 47](https://cloud.githubusercontent.com/assets/1147484/7239610/05906fbe-e7b4-11e4-8195-435a439c8337.jpg)

Next image. I open neovim in my `~` directory with defauld colorscheme(`desert`)
![screenshot 2015-04-20 23 22 30](https://cloud.githubusercontent.com/assets/1147484/7239817/72390454-e7b5-11e4-94cc-e407d1788220.jpg)


Last image. I open neovim in tmux session with custom colorscheme
![screenshot 2015-04-20 23 20 49](https://cloud.githubusercontent.com/assets/1147484/7239617/157abf74-e7b4-11e4-97a2-675af48f2306.jpg)

Also I understood why `<C-w>l`, etc bindings not work for me. I use vim/nvim only with tmux and I [update my tmux config](https://github.com/davydovanton/dotfiles/blob/master/tmux#L20-L26) for switching with stlits. And this confige broke switching in nvim (in vim all works correct).

**Comment by Pyrohh** [comment]
In your `tmux.conf`, I see you have the environment variable `TERM` set to one with `256` in it. What's the output of `echo $TERM` in your terminal (no tmux)?

What happens if you run `export TERM=xterm-256color` in your terminal (no tmux), then launch nvim using the custom colorscheme?

**Comment by davydovanton** [comment]
@Pyrohh 
```
~ » echo $TERM
xterm
```

after `export TERM=xterm-256color` all works fine, than you so much!

**Comment by Pyrohh** [comment]
Excellent, I'll close this and add that to the FAQ.

**Comment by davydovanton** [comment]
Thanks! :tada:
