### ISSUE TITLE
os.getenv doesn't work when nvim launched from desktop file

### ISSUE THREAD

**Issue by joelpeapen** [neovim/neovim#24590]
### Problem

i have this nvim.desktop file that launches nvim directly.

```desktop
[Desktop Entry]
Name=Neovim
GenericName=Text Editor
Exec=kitty --start-as maximized --listen-on unix:/tmp/mykitty --detach "nvim"
Terminal=true
```

the problem is that for some reason `os.getenv()` does it work when launching nvim
this way. it returns a nil value and i cannot concat it.

```lua
dap.adapters.codelldb = {
    type = "server",
    port = "${port}",
    executable = {
        command = os.getenv("XDG_DATA_HOME") .. "/nvim/mason/bin/codelldb",
        args = { "--port", "${port}" },
    },
}
```

there problems aren't there if nvim is started in terminal.

### Steps to reproduce

start nvim. error message:
```
Failed to source `/home/joel/.config/nvim/after/plugin/debug.lua`                                                           
vim/_editor.lua:0: /home/joel/.config/nvim/init.lua..nvim_exec2() called at /home/joel/.config/nvim/init.lua:0../home/joel/.config/nvim/after/plugin/debug.lua:                                                                                
Vim(source):E5113: Error while calling lua chunk: /home/joel/.config/nvim/after/plugin/debug.lua:7: attempt to concatenate a nil value
```

### Expected behavior

`os.getenv` should return the environment variable.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

no, config is in lua

### Operating system/version

Ubuntu 22.04.2 LTS x86_64

### Terminal name/version

kitty 0.29.2

### $TERM environment variable

xterm-kitty, xterm-256color in nvim

### Installation

nvim-linux64.tar.gz and extract.

**Comment by zeertzjq** [comment]
It's not set.

**Comment by joelpeapen** [comment]
no, it is set, `XDG_DATA_HOME="$HOME/.local/share"` it just doesn't work when launched from desktop

**Comment by zeertzjq** [comment]
Doesn't that mean it's not set?

**Comment by zeertzjq** [comment]
> no, it is set, `XDG_DATA_HOME="$HOME/.local/share"`

Then where did you get the value from?

**Comment by joelpeapen** [comment]
from ~/.zshenv. if i open a new tab & start nvim it works.

[getenv.webm](https://github.com/neovim/neovim/assets/67512946/48f79ccb-946e-48d5-9305-9537ecb1c542)

**Comment by zeertzjq** [comment]
How are you launching your window manager?

**Comment by joelpeapen** [comment]
it's just gnome.

**Comment by zeertzjq** [comment]
The it's a bug in GDM.
https://gitlab.gnome.org/GNOME/gdm/-/issues/841
