### ISSUE TITLE
selecting text on nvim does not copy it into the clipboard/current selection

### ISSUE THREAD

**Issue by 2ax3ax5** [neovim/neovim#24591]
### Problem

In a fresh installation with no nvim/vim config files whatsoever, selecting a text in nvim does not copy such text into the "current selection"

By "current selection" I mean what is refered as "current selection" in https://neovim.io/doc/user/usr_09.html  (i.e.: x-windows highlight clipboard).

### Steps to reproduce

$ nvim
# select any text in the terminal running nvim with the mouse
# the text is properly highlighted
# but the text is *not* _pasted_/_copied_ in the "current selection"

### Expected behavior

The text highlighted should be pasted in the "current selection". This is the behavior of vi, vim and also nvim v0.7.2 installed with "apt install neovim" in the same os.

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: RelWithDebInfo (git rev-parse HEAD 7d4bba7aa7a4a3444919ea7a3804094c290395ef)

### Vim (not Nvim) behaves the same?

no (vim version 9.0.1499)

### Operating system/version

linux, debian12

### Terminal name/version

rxvt-unicode (urxvt) v9.30 - released: 2021-11-27; but the same happens for any other terminal I've tried like xterm and so

### $TERM environment variable

rxvt-unicode-256color

### Installation

following the https://github.com/neovim/neovim/wiki/Building-Neovim#quick-start instructions: 'git clone https://github.com/neovim/neovim ; cd neovim ; make CMAKE_BUILD_TYPE=RelWithDebInfo ; make install'

**Comment by zeertzjq** [comment]
`:set mouse=`
