### ISSUE TITLE
Key encoding format

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#246]
If neovim is going to ever solve the long-existing problem with vim not being able to understand some key combinations even in GUI it needs better format then current `0x80 BYTE1 BYTE2`. This format is also essential for new VimL parser because it is how things like `"\<C-a>"` are parsed.

My suggestion (from https://groups.google.com/d/msg/vim_dev/2bp9UdfZ63M/NQl_92bj1EUJ):

1. Have an agreement for new escaping scheme for byte queue. I may suggest taking some unused <80>{C1}{C2} sequence and agreeing that <80>{C1}{C2}{CMod}{Key}<ETX> means that 
  1. User pressed key named {Key} which is either a key name (like Up) or a character in &encoding with the exception that it cannot be control character. Key name obviously must be normalized. 
  2. This key was pressed with modifiers {CMod} which contains a bit field:

      Bit idx | Meaning 
      --------|-----------
      7       | Always 1. Does not allow byte to be zero.
      6       | Shift.
      5       | Control.
      4       | Alt.
      3       | Win.
      2       | Reserved (X11 definitely has something to fill it with, but I do not know what. Super?).
      1       | Reserved.
      0       | Reserved.

  3. <ETX> is simply an end-of-key marker. 
  4. Any key that can be represented with already existing <80>{C1}{C2} sequence *must* be represented with it. Control-{latin letter} without additional modifiers *must* be represented with control character. Latin letter without modifiers except for shift *must* be represented as itself. And so on: existing scheme should be kept for compatibility.

**Comment by justinmk** [comment]
@ZyX-I Does this issue still make sense and is it still needed for VimL translator?

**Comment by ZyX-I** [comment]
@justinmk I did not look into the code, but new UI definitely has something for representing such input or it was not able to use `<C-S-n>`. I think this issue can be closed, but note #2345: `"\<…>"` should also use new representation.
