### ISSUE TITLE
Cannot escape empty string `''` in `vim.fn.jonstart`

### ISSUE THREAD

**Issue by linrongbin16** [neovim/neovim#24604]
### Problem

I want to run command 
```
rg --no-heading -n --column -- ''
```

in `vim.fn.jobstart`, but the character escaping is wrong, and job failed to start.

### Steps to reproduce

start nvim, and type:

```
: jobstart('rg -n --column --no-heading -- \'\'', {on_stdout: {id, data, name -> echo string(data)}})
```

### Expected behavior

correctly run command and get output

### Neovim version (nvim -v)

v0.9.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

manOS 13.5

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256

### Installation

brew

**Comment by clason** [comment]
Wait is it `:jobstart` or `vim.fn.jobstart`? That's a big difference here.

**Comment by justinmk** [comment]
This is a usage question, not a bug.

1. prefer the list form `jobstart(['rg', '-n', '--column', '--no-heading', '--', "''"], ...)`
2. if you really want the shell form (why?), use `shellescape()`

**Comment by linrongbin16** [comment]
> Wait is it `:jobstart` or `vim.fn.jobstart`? That's a big difference here.

that should be a typo, let me try split them into a list.

**Comment by clason** [comment]
No, please keep it in the discussion you opened in parallel.
