### ISSUE TITLE
Undercurl not working anywhere

### ISSUE THREAD

**Issue by simonmandlik** [neovim/neovim#24602]
### Problem

I cannot get undercurl to work. I tested all of the "mainstream" terminal emulators — `iTerm2`, `kitty`, and `alacritty`, with `zsh`. Undercurl works in all terminals, but not in `neovim`.

iTerm2 shell:
<img width="370" alt="image" src="https://github.com/neovim/neovim/assets/16707112/a4fa396e-aa84-4d62-a4bf-4f3b9d26adae">

iTerm2 `neovim`:
<img width="535" alt="image" src="https://github.com/neovim/neovim/assets/16707112/1530aa71-130a-4d34-bf93-89c5d5d8c191">

kitty shell:
<img width="507" alt="image" src="https://github.com/neovim/neovim/assets/16707112/45dcf549-acc0-46e3-bcec-361a485198b3">

kitty `neovim`:
<img width="732" alt="image" src="https://github.com/neovim/neovim/assets/16707112/a9b8dc05-8868-44ee-83fa-857774616fd5">

alacrity shell:
<img width="470" alt="image" src="https://github.com/neovim/neovim/assets/16707112/44fcf452-567f-4b3f-b579-05c66988de34">

alacritty `neovim`:
<img width="679" alt="image" src="https://github.com/neovim/neovim/assets/16707112/43d8ce7f-8d2b-4cd4-845b-9af6978f8c33">

### Steps to reproduce

1. `nvim --clean`
2. `:hi SpellBad`

### Expected behavior

Undercurl line showing up

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

yes, 9.0.1424 (https://github.com/vim/vim/issues/12744)

### Operating system/version

macOS 13.4.1

### Terminal name/version

iterm2, kitty, alacritty

### $TERM environment variable

xterm256-color, xterm-kitty, alacritty

### Installation

homebrew

**Comment by justinmk** [comment]
This is not a support forum.
