### ISSUE TITLE
Treatment of Lua types changed for Boolean fields in API keydicts

### ISSUE THREAD

**Issue by MariaSolOs** [neovim/neovim#24618]
### Problem

In version v0.10.0-dev-772+g0211f889b, some highlight groups have suddenly changed (without updating any plugins or anything else).
EDIT: Read the comments below from @zeertzjq. The problem isn't exclusive to highlighting.

### Steps to reproduce

1. Using the latest nightly release, install [`noice`](https://github.com/folke/noice.nvim). Also install a colorscheme like https://github.com/Mofiqul/dracula.nvim.
2. Run `vim.fn.confirm('This has a weird highlight', 'Bar', 1, 'Baz')`

The resulting dialog looks like this:
<img width="258" alt="image" src="https://github.com/neovim/neovim/assets/62502207/e14c3057-0f14-49f1-948f-cf23e794d7b5">

Versus what it looked like *without changing anything* and rolling back to v0.10.0-dev-766+gef44e5972:
<img width="288" alt="image" src="https://github.com/neovim/neovim/assets/62502207/f14bd616-2e90-4792-a2be-ef7a984c97fa">

### Expected behavior

For highlights to remain unchanged.

### Neovim version (nvim -v)

v0.10.0-dev-772+g0211f889b

### Operating system/version

Mac Ventura 13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

bob

**Comment by MariaSolOs** [comment]
After debugging this a bit, the changed highlight group is `NoiceAttrXXX`, which is created [here](https://github.com/folke/noice.nvim/blob/894db25ec726d32047799d4d0a982b701bec453b/lua/noice/text/highlight.lua#L43). 

In the working version this is set to:
<img width="312" alt="image" src="https://github.com/neovim/neovim/assets/62502207/ada6e818-adf4-4a64-a251-11d68f90be67">

But now it is:
<img width="1070" alt="image" src="https://github.com/neovim/neovim/assets/62502207/46a06bf8-64f5-42c1-a887-1074563c7e47">

How could this happen without changing anything else except for updating `nvim`?

**Comment by zeertzjq** [comment]
This seems to happen because Lua `0` is now treated as `true` for a `Boolean` field in `opts` of an API. Previous it was treated as `false`.

**Comment by zeertzjq** [comment]
The current behavior may be more consistent. Previously, Lua `0` is already treated as `true` when passed as a positional `Boolean` API argument (e.g. second argument of `nvim_open_win`). Now it's also treated as `true` when passed in `opts`.

However, `Boolean` fields in `opts` are much more common than positional `Boolean` API argument, so this change may affect a lot of plugins.

**Comment by MariaSolOs** [comment]
I see... Yeah that does sound kinda bad :/

**Comment by zeertzjq** [comment]
However treating `0` as `true` is not consist with RPC, where `0` is treated as `false`, even if using a Lua RPC client.

**Comment by MariaSolOs** [comment]
Out of curiosity, which commit introduced the change?

This is a tough situation indeed. It sounds like an intended and clean change, but thinking of the amount of plugins that will suddenly break is a bit scary.

**Comment by zeertzjq** [comment]
I think it was https://github.com/neovim/neovim/commit/7bc93e0e2f246dd78026a3472d929a0fe450f70d

**Comment by zeertzjq** [comment]
Oh, another effect of this change is that now any Lua type is allowed for a `Boolean` field on `opts`. Previously `number` and `boolean` are allowed.

**Comment by bfredl** [comment]
I just assumed `nvim_pop_Boolean(L, err)` would, in fact, pop an api Boolean. but it doesn't, it's just a dummy wrapper around lua_toboolean which ignores err :(

I'm surprised there is not a single test that would be affected by this. makes much harder to reason about code.

Anyway, it is easy to change back. If desired, any deliberate change (one way or the other) must be done in a separate PR with doc changes, ecosystem spelunking etc.

**Comment by MariaSolOs** [comment]
@bfredl sounds like a plan. It’s awful because your PR seemed like a great refactor, and it’s a shame that something unexpected like this happens.

I 100% agree about the tests. I’m happy to contribute with adding a couple of tests to prevent this from happening in the future if you want.
Disclaimer that I haven’t done it before, but I want to learn :)
