### ISSUE TITLE
Configuration file location

### ISSUE THREAD

**Issue by robinmoussu** [neovim/neovim#2461]
Hi,
If I'm right, configurations files of nvim are in `~/.nvimrc` and in `~/.nvim`.
I think it can be a good think to use the opportunity of re-creating vim to move those file in `$XDG_CONFIG_HOME/nvim` (or in `~/.config/nvim/*` if $XDG_CONFIG_HOME in unset) like freedesktop recommendation suggest (http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by noahfrederick** [comment]
See https://github.com/neovim/neovim/issues/78.

**Comment by robinmoussu** [comment]
Thanks. I've try to find similar issue before posting without success. Sorry for the nose.
