### ISSUE TITLE
trailing whitespace is automatically removed if write to file

### ISSUE THREAD

**Issue by stumash** [neovim/neovim#24616]
### Problem

If I open a file and add extra newlines at the end of it and then write to the file and quit `:wq`, then when I re-open the file _one of the newlines is gone_. If I repeatedly re-open the file and exit with `:wq`, then one of the newlines will disappear each time a exit the file until there are no trailing newlines left.

I'm pretty sure this shouldn't happen?

### Steps to reproduce

```bash
echo -e "{ 1 : 2 }\n\n" > dank.json
nvim --clean dank.json  # notice the two trailing newlines. now exit with :wq
nvim --clean dank.json  # notice there is only ONE trailing newline. now exit with :wq
nvim --clean dank.json  # notice there are NO trailing newlines left. now exit with :wq
nvim --clean dank.json  # now the file is unchanged since last exit
nvim --clean dank.json  # still unchanged
```

### Expected behavior

trailing newlines should not be removed _automatically_

### Neovim version (nvim -v)

v0.9.1

### Vim (not Nvim) behaves the same?

vim --clean DOES NOT behave the same (vim 9.0)

### Operating system/version

13.4.1

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by zeertzjq** [comment]
Do you are an `.editorconfig` somewhere?

**Comment by stumash** [comment]
nope, no `.editorconfig` anywhere

**Comment by justinmk** [comment]
> maybe neovim is not interpreting the `.editorconfig` `insert_final_newline=false` correctly.
> 
> I don't think it should remove newlines if they exist - it should just not add one if it's not already there.

editorconfig does not agree, unfortunately: https://github.com/editorconfig/editorconfig/issues/475#issuecomment-1466012659

Tracked in https://github.com/neovim/neovim/issues/21648

**Comment by stumash** [comment]
LOL great minds think alike 😂 

I guess the behavior should stay as it is, since neovim following their spec

check this out, their [their docs](https://editorconfig.org/) (quoted below)  aren't even following their spec though!
> `insert_final_newline`: set to true to ensure file ends with a newline when saving and false to ensure it doesn't.
