### ISSUE TITLE
Tab autocomplet randomly stops working in command mode

### ISSUE THREAD

**Issue by Drllap** [neovim/neovim#24611]
### Problem

Quite frequently, a couple of times a day, pressing `<tab>` when in command mode stops triggering autocompletion when in command mode. It just prints `^I` instead.

![image](https://github.com/neovim/neovim/assets/3659986/e1163333-306a-4dec-bd30-bd93756605e9)
![image](https://github.com/neovim/neovim/assets/3659986/10383016-d2c8-4036-a1a3-e2cd410e1eaa)

It both happens when running NeoVIm in the terminal, Wezterm, and when I use NeoVide.

If I restart vim everything works fine again, even if I open up the same session again (I'm using TPops Obsesion)

### Steps to reproduce

Unfortunately I haven't been able to reproduce this consistently,

### Expected behavior

The tab autocomplete shouldn't stop working

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 10

### Terminal name/version

wezterm 20230712-072601-f4abf8fd

### $TERM environment variable

xterm-256color

### Installation

chocolatey

**Comment by justinmk** [comment]
Guessing it doesn't happen with `nvim --clean`

**Comment by Drllap** [comment]
@justinmk I don't know, it isn't really viable to use `nvim --clean` for a full day to check it.

**Comment by Drllap** [comment]
> Bisect your plugins: `:help bisect`.
I have started this effort but it is going to take a while since this happens so seldom.
[Here is a list of pluggings I'm using](https://github.com/Drllap/development_setup/blob/252aaa45e0be25480c26e650f114e451e6180e28/NeoVim/init.vim#L37)
Does anyone have a likely candidate? I already tried disabling `cmp-cmdline` and `leap` but it still happens

**Comment by Andrew15-5** [comment]
@Drllap, hopefully this will help if still relevant: https://github.com/hrsh7th/nvim-cmp/issues/874.
