### ISSUE TITLE
comment operator (included vim-commentary by default)

### ISSUE THREAD

**Issue by leet0rz** [neovim/neovim#24620]
### Problem

Not being able to comment multiple lines

### Expected behavior

Being able to comment multiple lines after selecting them in visual mode. This is a very basic feature that so many other editors have, how is this not in nvim yet by default?

**Comment by justinmk** [comment]
> say, tree-sitter aware commentstrings -- I would say the bar has moved a bit since `vim-commentary` was written).

That's a good point. But "tree-sitter aware commentstrings" would not conflict with an interim such as vim-commentary, i.e. we could "upgrade" or swap out vim-commentary in the future. So why should that block an interim solution?

> that risks becoming encysted and unmaintainable, just like some others I could name

What is the size of the risk, though? We have successfully removed such plugins in many cases. We need to be consider magnitude when putting up objections. I do not think removing or swapping out an interim solution such as vim-commentary would be costly in the future.

**Comment by clason** [comment]
Sure, if it's meant as a stop-gap solution and doesn't lower the priority of adding "native" functionality. (Although if we do bundle plugins, we should cast a wider net -- e.g., @echasnovski's `mini` plugins would be just as suitable and may fit better.)

**Comment by echasnovski** [comment]
Just as note: I am always more than happy to work towards including any of 'mini.nvim' functionality in core, 'mini.comment' or else. What I see necessary for this is an explicit understanding from core team that certain functionality is actually needed in core and at least a vague description of how it is best to be shaped.

For exported `vim.comment` module the very basic functionality can be something like:
- `add_comment(buf_id, start_row, end_row, opts)`.
- `remove_comment(buf_id, start_row, end_row, opts)`.
- `is_comment(buf_id, start_row, end_row, opts)`.
- `get_commentstring(buf_id, row, col, opts)`.

If there is a tendency to actually implement `gc` mapping (as operator in Normal mode and Visual mode), then some dedicated `operator()` function is needed.

**Comment by craigmac** [comment]
if this why not some notion of "surround" manipulation as well? whether it's vim-surround or mini.surround I have no opinion, although vim-surround requires vim-repeat. I think the big 4 of Vim that are least controversial are vim-sensible (Neovim includes most of this by default in Neovim now), vim-commentary (PR closing this issue), vim-surround, vim-repeat. I think repeatability should be in mind, so if we are bringing in vim-commentary we need vim-repeat feature, unless we go mini.comment

**Comment by lewis6991** [comment]
Feature creep guys!

Let's just get vim-commentary in and map it to gc.

We can lua-afy it and turbo charge it with treesitter later.

> For exported vim.comment module the very basic functionality can be something like:

Whilst neat, I don't think this additional surface area is worth the cost. At least right now.

**Comment by justinmk** [comment]
> Feature creep guys!

Right. vim-commentary has no API, it's just a mapping. This is exactly why I mentioned "low-risk micro-plugin". Talking about APIs is the opposite.

Why would we need `add_comment()` if we have treesitter text-objects?

**Comment by echasnovski** [comment]
> Why would we need `add_comment()` if we have treesitter text-objects?

I don't see how tree-sitter text-objects is related to this, because text-objects and operators are more or less orthogonal to each other.

------

For what it is worth, having Neovim add Lua modules for all kinds of non actual text edit related stuff (`vim.lsp`, `vim.diagnostic`) but resorting to adding a Vimscript one for commenting feels kind of inconsistent.

**Comment by justinmk** [comment]
> having Neovim add Lua modules for all kinds of non actual text edit related stuff (`vim.lsp`, `vim.diagnostic`) but resorting to adding a Vimscript one for commenting feels kind of inconsistent.

What matters is that it's a low-maintenance, low surface-area, micro-plugin. If the code is small it doesn't really matter what it's written in. And it's likely temporary, as already discussed.

**Comment by dundargoc** [comment]
Proposal PR for vim-commentary: https://github.com/neovim/neovim/pull/27999

**Comment by clason** [comment]
https://github.com/neovim/neovim/pull/28176
