### ISSUE TITLE
vim.filetype examples use private undocumented functions

### ISSUE THREAD

**Issue by mike325** [neovim/neovim#24644]
### Problem

The `vim.filetype` help examples use `vim.filetype.getlines` and `vim.filetype.matchregex` which are private functions, these examples should be updated with either public functions (like `vim.match`) or just be removed.

```lua
    To add a fallback match on contents, use >lua

     vim.filetype.add {
       pattern = {
         ['.*'] = {
           priority = -math.huge,
           function(path, bufnr)
             local content = vim.filetype.getlines(bufnr, 1)                -- Undocumented/private
             if vim.filetype.matchregex(content, [[^#!.*\<mine\>]]) then    -- Undocumented/private
               return 'mine'
             elseif vim.filetype.matchregex(content, [[\<drawing\>]]) then
               return 'drawing'
             end
           end,
         },
       },
     }
```

Also from the help it's not really clear whether `vim.match` uses vim's regex or lua patterns to perform the matches, I think this should be stated in the help description.

I would be happy to submit a PR with the help changes.

### Steps to reproduce

`:h vim.filetype`

### Expected behavior

Don't use private functions as examples in help

### Neovim version (nvim -v)

v0.10.0-dev-61ed454

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Red Hat Enterprise Linux Server release 7.7

### Terminal name/version

wezterm 20230717-111633-94ab0496

### $TERM environment variable

screen-256color

### Installation

build from repo

**Comment by clason** [comment]
> The vim.filetype help examples use vim.filetype.getlines and vim.filetype.matchregex which are private functions, these examples should be updated with either public functions (like vim.match) or just be removed.

This was changed in a very recent PR https://github.com/neovim/neovim/pull/24573

Maybe those decisions should be revisited, as it's very much intended for people to implement their own detection logic similar to the one in core.  @lewis6991 

> Also from the help it's not really clear whether vim.match uses vim's regex or lua patterns to perform the matches, I think this should be stated in the help description.

It uses both, depending on the filetype. But that is an implementation detail and should not be exposed.
