### ISSUE TITLE
when opening nvim, abnormal display occurs.

### ISSUE THREAD

**Issue by hacqr** [neovim/neovim#24640]
### Problem

When I open nvim in securecrt. the new buffer always display '2m'.
![title](https://github.com/neovim/neovim/assets/3411638/65023a49-1a8b-4d56-9a53-7dec675c4370)

### Steps to reproduce

nvim

### Expected behavior

nvim

### Neovim version (nvim -v)

NVIM v0.8.0

### Vim (not Nvim) behaves the same?

no,vim9.0

### Operating system/version

linux

### Terminal name/version

xterm

### $TERM environment variable

xterm-256color

### Installation

repo

**Comment by zeertzjq** [comment]
Your Nvim or XTerm version is too old.
