### ISSUE TITLE
Add Debian package to releases again

### ISSUE THREAD

**Issue by jhaand** [neovim/neovim#24652]
### Problem

Observed: 
The Debian project can't get their act together on how to package a recent version of Neovim. Therefore they still package the 0.7.2 version of Neovim. This version lacks a lot of features that makes life better. However, up to version 0.8.3 the Neovim project did add a Debian package to the release. 
Now I have to download the source and generate my own Debian package to update to the latest stable release.

### Expected behavior

Requested:
Add a Debian to the list of available downloads for Neovim.

**Comment by clason** [comment]
Distros have different priorities; their maintainers are also volunteers with a life of their own. We offer enough options for you to get the latest and shiniest.

**Comment by antidotejack** [comment]
what about the people that doesn't have a large technology background and are not arch users. I guest I should listen to my classmates and just use VScode.

**Comment by clason** [comment]
I'm sorry, if clicking on a triangle is too much for you, you should indeed just stick to what is installed on your machine. (There's lots of triangles to click in VS Code too, last I looked, though.)

**Comment by bfredl** [comment]
> However, up to version 0.8.3 the Neovim project did add a Debian package to the release.

For full context, neovim did **not** have any such thing. We had a .deb file which was just the .tar.gz file but stuffed into a .deb container which people confused with an actual debian/ubuntu package. all the bigger reason to why it had to be removed.
