### ISSUE TITLE
Segfault in libluajit

### ISSUE THREAD

**Issue by aarondill** [neovim/neovim#24658]
### Problem

While editing a file, Neovim segfaulted. I don't know what caused it, and I don't know how to reproduce it, but I've attached the traceback from the core dump if it helps. 

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nvim --embed xdg-user-dir'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f83e86753af in ?? ()
[Current thread is 1 (Thread 0x7f83dc0cb740 (LWP 95296))]
(gdb) bt full
#0  0x00007f83e86753af in ?? ()
No symbol table info available.
#1  0x0000000041d9dda0 in ?? ()
No symbol table info available.
#2  0x00007f83dc1e6921 in ?? () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
No symbol table info available.
#3  0x00007f83dc1f5f13 in lua_pcall () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
No symbol table info available.
#4  0x00005632542637bc in nlua_pcall ()
No symbol table info available.
#5  0x000056325426884b in nlua_call_ref ()
No symbol table info available.
#6  0x00005632541aa621 in ?? ()
No symbol table info available.
#7  0x00005632541ab0ad in decor_providers_invoke_end ()
No symbol table info available.
#8  0x00005632541bde16 in update_screen ()
No symbol table info available.
#9  0x00005632541be0ef in ins_redraw ()
No symbol table info available.
#10 0x00005632541c0f7d in ?? ()
No symbol table info available.
#11 0x000056325434c955 in state_enter ()
No symbol table info available.
#12 0x00005632541c25ff in ?? ()
No symbol table info available.
#13 0x00005632541c27ec in edit ()
No symbol table info available.
#14 0x00005632542b64d0 in ?? ()
No symbol table info available.
#15 0x00005632542b6792 in ?? ()
No symbol table info available.
#16 0x00005632542b3597 in ?? ()
No symbol table info available.
#17 0x000056325434c985 in state_enter ()
No symbol table info available.
#18 0x00005632542abbca in normal_enter ()
No symbol table info available.
#19 0x0000563254136187 in main ()
No symbol table info available.
```

### Steps to reproduce

:man_shrugging: 

### Expected behavior

No segfault

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 22.04.3 LTS

### Terminal name/version

wezterm 20230712-072601-f4abf8fd

### $TERM environment variable

wezterm

### Installation

Ubuntu Neovim Nightly PPA (https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable)

**Comment by aarondill** [comment]
As I have no reproduction instructions, and it could (possibly) be one of my plugins that caused this, feel free to close this issue if you feel there's no way to track down the original issue.

**Comment by zeertzjq** [comment]
This may be a problem with the LuaJIT version used by the package. Can you try nightly appimage instead and seem if that also crashes?

**Comment by aarondill** [comment]
Sure, I'd be happy to do so, but, just as a friendly reminder, I still have no way to intentionally reproduce this crash, so the only way I'd know if it worked or not is if I got another segfault with the same backtrace.

I'm sorry I can't be of more help, but I was just editing a file as normal when it occurred, and reopening the file does not result in another crash.
