### ISSUE TITLE
Cursor is not redrawn after a `statuscolumn` update

### ISSUE THREAD

**Issue by 33KK** [neovim/neovim#24655]
### Problem

The cursor is not redrawn properly after statuscolumn updates. The actual cursor position in `ruler` and `cursorcolumn` are correct.

`;` in the video is actually `o`

https://github.com/neovim/neovim/assets/23123008/ab3b42ea-527a-4ecd-b7cd-c7580778bd0d

Issue in the plugin repo: https://github.com/luukvbaal/statuscol.nvim/issues/77

### Steps to reproduce

`nvim --clean -u repro.lua repro.lua`:
```lua
for name, url in pairs({
	"https://github.com/neovim/nvim-lspconfig",
	"https://github.com/luukvbaal/statuscol.nvim",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

vim.cmd.colorscheme("habamax")

local lspconfig = require("lspconfig")
lspconfig.lua_ls.setup({})

local builtin = require("statuscol.builtin")

vim.opt.number = true

require("statuscol").setup({
	segments = {
		{
			sign = {
				name = { "Diagnostic" },
				minwidth = 1,
				maxwidth = 1,
				auto = true,
			},
		},
		{ text = { builtin.lnumfunc }, click = "v:lua.ScLa" },
		{ text = { " " } }, -- This is necessary to reproduce, seems like this depends on statuscolumn width?
	},
})
```

1. Make sure the `lua_ls` server is displaying signs
2. Go to the end of the line where `statuscol` is require'd
3. Press `o`
4. The signs should disappear and the cursor should be offset by one column

### Expected behavior

The cursor should be at the correct column

### Neovim version (nvim -v)

v0.10.0-dev-798+g72e619ca92

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.29.2, also tested in uxterm

### $TERM environment variable

xterm-kitty

### Installation

neovim-git from chaotic-aur

**Comment by zeertzjq** [comment]
This can be tested using the following test change:
```diff
diff --git a/test/functional/ui/statuscolumn_spec.lua b/test/functional/ui/statuscolumn_spec.lua
index 35cd479bb..ee235cd6b 100644
--- a/test/functional/ui/statuscolumn_spec.lua
+++ b/test/functional/ui/statuscolumn_spec.lua
@@ -727,6 +727,8 @@ describe('statuscolumn', function()
         end
         return vim.v.lnum .. '%=' .. sign
       end
+      vim.o.number = true
+      vim.o.numberwidth = 2
       vim.o.statuscolumn = "%!v:lua.StatusCol()"
     ]])
     command('sign place 1 line=2 name=sign')
```
