### ISSUE TITLE
Hover from ultisnips does not show

### ISSUE THREAD

**Issue by markuspeloquin** [neovim/neovim#24663]
### Problem

For a while, I've been noticing that the hover during completion from ultisnips does not show (sometimes, it appears for 1/100th of a second). I tried removing plugins except for this minimal set (without any, I would not get the hover):

* prabirshrestha/asyncomplete.vim
* prabirshrestha/asyncomplete-lsp.vim
* prabirshrestha/vim-lsp
* mattn/vim-lsp-settings
* thomasfaingnaert/vim-lsp-ultisnips
* SirVer/ultisnips

I did a git bisect and ended up at the first bad commit: 700cab00680fa25e0dbdf6f91f638f4da5a09909.

### Steps to reproduce

I'm having trouble creating *any* config at all, usable by `nvim -u config`. But I'm using these:

* prabirshrestha/asyncomplete.vim
* prabirshrestha/asyncomplete-lsp.vim
* prabirshrestha/vim-lsp
* mattn/vim-lsp-settings
* thomasfaingnaert/vim-lsp-ultisnips
* SirVer/ultisnips

I have `gopls` in my PATH and type something like `fmt.Printf(`, and I see:
![image](https://github.com/neovim/neovim/assets/75588/28f58cd4-0e3d-4b58-bd32-2534b750f17d)

### Expected behavior

What I see on the previous commit:
![image](https://github.com/neovim/neovim/assets/75588/fb74eb92-fc60-4364-bb81-95466dc4fe2c)

### Neovim version (nvim -v)

v0.10.0-dev-445+g700cab006

### Vim (not Nvim) behaves the same?

no, vim 9.0.1680

### Operating system/version

linux 6.2.0

### Terminal name/version

alacritty 0.12.2

### $TERM environment variable

tmux-256color

### Installation

repo

**Comment by markuspeloquin** [comment]
@zeertzjq

**Comment by zeertzjq** [comment]
What plugin does this hover come from? Ultisnip doesn't seem to create floating windows.

**Comment by zeertzjq** [comment]
I've merge a related PR #24675, please check if the bug still exists.

**Comment by markuspeloquin** [comment]
That fixed it! Yeah, I have a hard time with terminology of little things in Vim. I just learned the name for 'signs'.
