### ISSUE TITLE
I don't like "vim out of the box" as main description of neovim

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#2467]
This is admittedly a non-issue, but one that bothers me periodically, and I just wanted to know if others share my view.

The thing is that I don't like seeing the short, one line description of vim, both in github main page, but also in newsletters, being written as "vim out of the box".

I think that including by default many of the features that were optional in vim is only a secondary characteristic of neovim. It's not *the* defining one, by any means.

I would certainly agree more to something like "vim updated", "vim reborn", "vim for the 21st century", or, making a little word-play, "vim improved".

Suggestions welcome.
Is anybody else bothered by this?

**Comment by fwalch** [comment]
At least on the Github page, I think it would be better to have a real description instead of a "slogan". "vim out of the box", what does it even mean? Is it a Vim plugin, a "distribution" (like MacVim), ...?

FWIW, for the Arch package, I use "Fork of Vim aiming to improve user experience, plugins, and GUIs", which is certainly not perfect, but somewhat descriptive and still fits in a few characters.

**Comment by elmart** [comment]
@fwalch
I do agree to that. :+1: 
Maybe "Vim's fork aiming to improve user experience, architecture (plugins/GUIs) and code quality."?

**Comment by lazywei** [comment]
@elmart I agree with you. I don't really like "vim out of the box" either. It is somewhat misleading to me.

**Comment by justinmk** [comment]
> I think that including by default many of the features that were optional in vim is only a secondary characteristic of neovim.

That's only one meaning of "out of the box". It has at least 3 meanings, explained here: https://github.com/neovim/neovim.github.io/issues/76

I waited a long time for comments on that issue...

> "vim reborn", "vim for the 21st century", or, making a little word-play, "vim improved".

Anything conjuring images of "birth" or "generation" should be discarded. It's a tired cliche which was *also* used by Xemacs.

> MessagePack is an extremely efficient object serialization library. It's like JSON, but very fast and small.

That is *not* the msgpack tagline. Their tagline is: *It's like JSON. but fast and small.*

> Vim's fork aiming to improve user experience, architecture (plugins/GUIs) and code quality

Guys, a tagline is marketing fluff. It doesn't have to make perfect sense, and it definitely is not meant to be a comprehensive, precise description of the project contents. 

And yes, Neovim *is vim*.

**Comment by justinmk** [comment]
If this issue is only in regards to the GitHub description, then, sure, it can be changed. The website and other user-facing materials are a separate matter though.

**Comment by elmart** [comment]
I think we all agree that the GitHub description is kind of opposite to a marketing line. It's browsed by technical people looking for a short but precise description of what's there. So, I'd definitely change at least that.

Regarding user-facing materials, well, I understand what you say, and I don't pretend for that and the GitHub's description to be the same. It's just that the meaning that current tagline conveys to me is not any of those described in the link. Once I read them, I can understand the tagline, but not the other way. If that happens to me, being within the project, I don't know what meaning does it actually convey to people outside the project. It may be that English is not my native language, but that's also the case for many (most) readers. I'm not particularly strong-hearted on this, though, so I won't insist.

**Comment by justinmk** [comment]
I'm all for a better tagline as long as it's "catchy" and has nothing to do with "next generation".

**Comment by hotgloupi** [comment]
@justinmk I agree with you, the "neo" prefix is enough for the "next-gen" stuff
@elmart I think a tag line should just be catchy (according to the targeted audience), I do like something nerdy things like "vim, improved"

My two cents:
 - neovim, eats your laundry
 - neovim, the chosen one
 - neovim, the new vim
 - neovim, what else ?
 - neovim, enlarge your editor
 - neovim is not unix
 - neovim, <insert tag line here>

**Comment by jszakmeister** [comment]
"vim reimagined"?

**Comment by fwalch** [comment]
> And yes, Neovim is vim.

> ambitious Vim-fork focused on extensibility and agility

Borrowing from msgpack : "It's Vim, but extensible and agile". Or any other two adjectives of your choice :grin:

**Comment by bfredl** [comment]
A concurrent vim for the multiprocessing age?
timeless vim ? (asynchronous == timeless if I know my Greek)

**Comment by elmart** [comment]
> Borrowing from msgpack : "It's Vim, but extensible and agile". Or any other two adjectives of your choice 

I do like that one, in fact.
My attempt at it: "It's Vim, polished and extended."

**Comment by Pyrohh** [comment]
> My attempt at it: "It's Vim, polished and extended."

I like that more than `extensible and agile`, because Vim is already very extensible (arguably).

**Comment by starcraftman** [comment]
"Modern Vim" summarizes things best in my opinion. 

The aims of this project are all about modernity. Applying new design idioms & practices on an older though still functional code base. To simple things like removing legacy features & making sane defaults.

**Comment by Pyrohh** [comment]
> "Modern Vim"

Or "Vim modernized", to keep with the current structure. 

> The aims of this project are all about modernity. Applying new design idioms & practices on an older though still functional code base. To simple things like removing legacy features & making sane defaults.

:+1:

**Comment by starcraftman** [comment]
@Pyrohh Up to you guys, but I find "modern vim" to be more succinct and sound better due to one less syllable.

**Comment by justinmk** [comment]
Is any of these significantly more effective than "vim out of the box"? The tagline should also be something that is not nearly a rewording of the word "neo-vim".

**Comment by justinmk** [comment]
Also, yes, I understand that the "out of the box" phrase doesn't translate to all cultures, and that's unfortunate, but if we're going to say anything that has any personality or color to it, it won't translate universally. I'd rather confuse some people but delight others, than dull everyone.

**Comment by critiqjo** [comment]
How about "Vim unchained!" ?
'coz that is what I truly felt... More flexibility, more freedom...

**Comment by lazywei** [comment]
Come on', let's have a recursive naming :smile: 
NeoVim Evolution Of Vim

**Comment by doppioandante** [comment]
As a non native speaker, "out of the box" sounds meaningless enough to me to be cool, moreover I associate it to the idea of software "just working".
For advertisement it surely works.

**Comment by kopischke** [comment]
> As a non native speaker, "out of the box" sounds meaningless enough to me to be cool

Agreed, it sounds meaninglessly cool :). Considering how conservatively we approach default configuration, however, I’d say the actual experience does not really match the received meaning of “out of the box” (“works without customisation”), and the other meaning of that phrase (i.e. “unconventional, creative”) does indeed not translate very well across languages and cultural barriers.

> Come on', let's have a recursive naming.

Begone, foul fiend of the GNU depths.

**Comment by glts** [comment]
'vim out of the box', it's ambiguous, it's got flair -- top marketing material.

Keep in mind that designing marketing fluff by techie committee is often not the best idea. There's a good chance the result will be something plainer than a glass of water at room temperature, at least that's what the suggestions here made me remember (no offence :P).

**Comment by traycerb** [comment]
I was surprised to hear "out of the box" has a cool sound to foreigners, because for at least 10+ years in the US it's one of the many verbose, opaque, and substanceless phrases used because apparently simple clarity is outre.  A thousand apologies to justinmk or whoever came up with it; I value yours and everyone's hard work on NeoVim, but man, that phrase drives me crazy.

Anyway, it's not fair to be so critical without offering my own suggestion up for everyone's criticism:

So, my try:

**NeoVim: The New Normal**

Why I like:

1. "New" mirrors the "Neo" bit, but not in a way to be too redundant
2. Is vague enough to be interesting
3. The phrase is re-appropriated from already existing English idiom, and so sounds familiar to us, but in a new context (though this phrase may also be a little worn at this point, if less so than "out of the box")
4. alliteration!
5. ...and best of all, the little Vim in-joke (which, if you don't get, what are you doing here O_o ???)

The downside is there's no explicit mention of Vim, which, frankly, I don't think is necessary in the tagline.  If you still don't like it, perhaps consider my alternate suggestion:

**NeoVim: Bus-proof Vim**

**Comment by tarruda** [comment]
I wish I had put more thought in the project name :disappointed:

**Comment by dkns** [comment]
I know it's too late to rename the project but I'd like to point out missed opportunity to call it iVim (improved Vim). Think of all the free publicity that Neovim would get following the inevitable lawsuit by apple.

**Comment by jszakmeister** [comment]
> I wish I had put more thought in the project name

Personally, I like it very much. :-)

**Comment by tarruda** [comment]
> I know it's too late to rename the project but I'd like to point out missed opportunity to call it iVim (improved Vim). Think of all the free publicity that Neovim would get following the inevitable lawsuit by apple.

That could never have happened, I'm a hater of apple and all of it's products :laughing:

**Comment by ianks** [comment]
Neovim: old dog, new tricks

**Comment by Pyrohh** [comment]
> Neovim: old dog, new tricks

I like it, but I think it might be lost in translation (no clue).

**Comment by tarruda** [comment]
> Neovim: old dog, new tricks

very clever

**Comment by g21michal** [comment]
**N**ever **E**nough **O**f **Vim**

**Comment by niccnacc** [comment]
Neovim, even more powerful! (unleashed or other, which were mentioned are cool too).
Neovim, yet improved!
Actually marketing for something as neovim is kinda unconventional. I know at least 10 people studiying IT, who think vim in general is freaky and too much for them. What I'm saying is: potential users are a very specific class of people. And even more, since (if) you are refering to vim,.. you actually have to know vim! So be sure to target the right people with that slogan. And, personally I wouldn't refer to vim as first thing in. If I would like to know, what neovim is, I'd still be referred to vim... imagine you'd be referred to vi and then think: "who needs a one-line text editor"...
Which brings me back to: Why is there exactly NO place I can find, with an actual description of what neovim does? I think this is more important, than the catchy phrase.

**Comment by yvaucher** [comment]
**NeoVim: Vim reVimped** :smile:

**Comment by Mudox** [comment]
The initial motivation of this project and much of effort that is being made, I believe,  is to unshackle Vim out of old single processing architecture, and equip it with modern technologies to make it capable of do more things that will unchain users. 
So unchaining vim to unchain users. I would like to borrow a movie name [Django Unchained](http://en.wikipedia.org/wiki/Django_Unchained) -- __Vim Unchained (Unshackled)__.
or directly say: __Old Vim with a Young__(or whatever appropriate word) __Heart__.

**Comment by Mudox** [comment]
The initial motivation of this project and much of effort that is being made, I believe,  is to unshackle Vim out of old single processing architecture, and equip it with modern technologies to make it capable of do more things that will unchain users. 
So unchaining vim to unchain users. I would like to borrow a movie name [Django Unchained](http://en.wikipedia.org/wiki/Django_Unchained) -- __Vim Unchained (Unshackled)__ as @critiqjo previously proposed.
or directly say: __Old Vim with a Young__(or whatever appropriate word) __Heart__.

**Comment by justinmk** [comment]
The original issue here was addressed by changing the GitHub project description to "ambitious Vim-fork..."

**Comment by elmart** [comment]
Had I known, I wouldn't have said anything.
I don't like much current situation. Without discussing what the line should be, I would at least:
- reduce it to a single line
- properly capitalize
- move link to financing campaign down to main body (at Readme).

**Comment by justinmk** [comment]
I didn't add the campaign text. I would also like it to be one line...
