### ISSUE TITLE
Treesitter live query editor

### ISSUE THREAD

**Issue by clason** [neovim/neovim#24678]
### Problem

We have upstreamed nearly every functionality from https://github.com/nvim-treesitter/playground, except for the query editor. Adding a (minimal) version allows archiving this project.

### Expected behavior

We need a function, e.g., `:EditQuery` that

* opens a `nofile` buffer with `ft=query` and the query linter attached;
* runs the contents as a treesitter query (e.g., on `InsertLeave`) on the "base buffer" from which it is opened;
* highlights any matches in the base buffer for the capture under the cursor in the editor buffer;
* (optional) can be opened from `:InspectTree` via, e.g., `o`.

In contrast to `nvim-treesitter/playground`, I don't think we should make these queries persistent (i.e., allow saving them to the user's config directory).

**Comment by MariaSolOs** [comment]
Talking about the query editor, why are rows and columns 1-based instead of 0-based (which is what both [the playground plugin](https://github.com/nvim-treesitter/playground) and the TS APIs use)?

**Comment by clason** [comment]
What query editor? There's none yet.

**Comment by justinmk** [comment]
Should this also happen automatically when `:edit` is used on a `queries/*.scm` file? Perhaps even that could avoid the special `:EditQuery` command.

**Comment by clason** [comment]
No, this is purely meant as a playground; that will simplify things significantly.

(Otherwise you can just edit the file directly; there's already limited reloading.)
