### ISSUE TITLE
AppImage  Issue re Install will not pass Health Check

### ISSUE THREAD

**Issue by thorrrr** [neovim/neovim#24679]
### Problem

I have tried using your AppImage which i expect to install all that is required!
But the health check shows not 1 item as ok or i may be misreading it ?

![image](https://github.com/neovim/neovim/assets/8170673/aaa98d81-d006-461f-ae7f-ed28b9be9292)

### Steps to reproduce

will not pass healthcheck      

### Expected behavior

Install Neovim and show a healthcheck correctly 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-811+g58a1ef8e6

### Vim (not Nvim) behaves the same?

9.0.1678

### Operating system/version

Arch

### Terminal name/version

allacritty

### $TERM environment variable

???

### Installation

AppImage

**Comment by clason** [comment]
Please show the unfolded contents (and paste them as text, not a screenshot!)

**Comment by clason** [comment]
In the absence of further details, I will assume that these are just the standard warnings about missing optional(!) dependencies. Nothing to worry about.

**Comment by thorrrr** [comment]
![image](https://github.com/neovim/neovim/assets/8170673/b3751a56-aba5-476e-b4a2-1cfd82eb30ee)

![image](https://github.com/neovim/neovim/assets/8170673/2306030c-f3c2-4184-9479-3ea4d0df7b74)

**Comment by clason** [comment]
Yep, that's the normal result on a fresh install.

**Comment by thorrrr** [comment]
Is it ok to use or do i need to add anything ?

**Comment by clason** [comment]
It is OK to use.

**Comment by dundargoc** [comment]
To elaborate/give context: neovim can't know whether a user e.g. wants to use the ruby provider or not. The workaround is that a warning is always given if the provider doesn't work, and that people who aren't interested in it can disable it to remove the warning. The text explains how to disable it.

**Comment by thorrrr** [comment]
cheers
