### ISSUE TITLE
Allow getting field name of TSNode

### ISSUE THREAD

**Issue by Kyuuhachi** [neovim/neovim#24674]
### Problem

There appears to be no easy way to get the field name of a TSNode; that is, the name its parent has assigned it. The only way to get it is something like
```lua
function field_of(node)
  for child, field in node:parent():iter_children()
    if child == node then
      return field
    end
  end
end
```

This is awkward and inefficient, being linear to number of siblings. In C, I believe it could be implemented in constant time as
```c
char* field_of(TSNode node) {
  TSTreeCursor cursor = ts_tree_cursor_new(node);
  char* name = ts_tree_cursor_current_field_name(&cursor);
  ts_tree_cursor_delete(&cursor);
  return name;
}
```

(This snippet is untested.)

### Expected behavior

There should exist a function that returns the field name of the TSNode, possibly implemented as above (with some extra Lua wrapping). The most obvious name would be `TSNode:field()`, but unfortunately this name is already taken by the function that returns all children that are the given field, so another name would need to be chosen.

**Comment by clason** [comment]
`TSNode` exposes the tree-sitter API, so what you're asking for needs to be implemented in tree-sitter. (There's been recent additions to the API that have not made a release yet, so check those first.)

**Comment by Kyuuhachi** [comment]
Just tried the equivalent to the above C snippet via luajit's ffi. Turns out TSCursor doesn't want to go above the given start node, including to get field names, so `ts_tree_cursor_current_field_name()` on a newly-created TSCursor just returns null. 

`ts_node_field_name_for_child()` does seem relevant, but I don't see any function to find a child's index in its parent, so even with that we'd have to fall back to a linear scan.

So I guess we might as well close this issue, unless someone wants to file an issue for a `ts_node_index_in_parent()` function.
