### ISSUE TITLE
vim.inspect errors with primitive types

### ISSUE THREAD

**Issue by MariaSolOs** [neovim/neovim#24688]
### Problem

`vim.inspect` cannot handle primitive objects like integers or booleans, resulting in strange errors that might be hard to understand for a beginner. 

### Steps to reproduce

1. Open Neovim with `nvim -u NONE`
2. Run `:lua print(vim.inspect 0)`

### Expected behavior

For `0` to be printed without errors.

### Neovim version (nvim -v)

v0.10.0-dev-811+g58a1ef8e6

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Mac Ventura 13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

bob

**Comment by zeertzjq** [comment]
Doesn't the same thing happen with `print()`?
`print 0` or `vim.inspect 0` errors
`print(0)` or `vim.inspect(0)` works

**Comment by MariaSolOs** [comment]
Oh wow, I'm so sorry.
