### ISSUE TITLE
Unable to paste in command mode with mouse=a

### ISSUE THREAD

**Issue by topaxi** [neovim/neovim#2468]
I am unable to paste commands into command mode with `mouse=a`, I use this very often to open files through `:e <paste file path here>`

Now using `mouse=nvi` as a workaround (or even proper fix?) which works for me.

**Comment by mhinz** [comment]
What system are you on?
Which terminal emulator?
What happens if you try to paste?

**Comment by topaxi** [comment]
Ubuntu 14.10
gnome-terminal (3.6.2); also tested xterm
term gets focus, but nothing happens

Tried with an empty profile, seems to work there.
If i have time next week, i will try to track down which setting / plugin this causes.

**Comment by Pyrohh** [comment]
Closing this for now, but please reopen if you get more info @topaxi.

**Comment by rbelem** [comment]
I'm getting the same bug with the build 0.0.0+git201507270350+1785+10.

**Comment by b21e** [comment]
I have the same problem on ubuntu with the official ppa: Mose does not work.

     nvim -v
    NVIM 0.0.0-alpha (compiled Aug 24 2015 20:13:02)
    Commit: ?
    Build type: RelWithDebInfo
    Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-T8doOE/neovim-0.0.0+git201508240835+1837+12~ubuntu15.04.1/build/config -I/build/neovim-T8doOE/neovim-0.0.0+git201508240835+1837+12~ubuntu15.04.1/src -I/build/neovim-T8doOE/neovim-0.0.0+git201508240835+1837+12~ubuntu15.04.1/.deps/usr/include -I/build/neovim-T8doOE/neovim-0.0.0+git201508240835+1837+12~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-T8doOE/neovim-0.0.0+git201508240835+1837+12~ubuntu15.04.1/.deps/usr/include -I/build/neovim-T8doOE/neovim-0.0.0+git201508240835+1837+12~ubuntu15.04.1/.deps/usr/include -I/build/neovim-T8doOE/neovim-0.0.0+git201508240835+1837+12~ubuntu15.04.1/.deps/usr/include -I/build/neovim-T8doOE/neovim-0.0.0+git201508240835+1837+12~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-T8doOE/neovim-0.0.0+git201508240835+1837+12~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-T8doOE/neovim-0.0.0+git201508240835+1837+12~ubuntu15.04.1/build/include
    Compiled by buildd@lcy01-15    

    Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
    For differences from Vim, see :help vim-differences    

       system vimrc file: "$VIM/nvimrc"
         user vimrc file: "~/.nvimrc"
     2nd user vimrc file: "~/.nvim/nvimrc"
          user exrc file: "~/.exrc"
      fall-back for $VIM: "/usr/share/nvim"

**Comment by bfredl** [comment]
can confirm. `<c-r>*` works in commandline but not middleclick.

**Comment by popkinj** [comment]
My goal was to get back the *highlight* and *middle-click paste* I use so often. I found this worked great.
```
set mouse=v
```
I'm using Ubuntu 16.04. 😃
