### ISSUE TITLE
autocmd TabNewEntered E1155: Cannot define autocommands for ALL events

### ISSUE THREAD

**Issue by FreddieLi** [neovim/neovim#24691]
### Problem

in init.vim
```
function! OnTabEnter(path)    
  if isdirectory(a:path)    
    let dirname = a:path    
  else    
    let dirname = fnamemodify(a:path, ":h")    
  endif    
  echom dirname    
  execute "tcd ". dirname    
endfunction  

```

```
augroup TabNewEntered    
  autocmd!
  autocmd TabNewEntered * :call OnTabEnter(expand("<amatch>"))    
augroup END 
```
it show error `E1155: Cannot define autocommands for ALL events` while open nvim.

However, if I replace **TabNewEntered** with **WinNew**, autocmd won't complain.

> 

### Steps to reproduce

nvim

### Expected behavior

should not have E1155: Cannot define autocommands for ALL events

### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

no,vim8.2

### Operating system/version

Linux 5.19.0-43-generic, ubuntu-22.04

### Terminal name/version

gnome-terminal Version 3.44.0 for GNOME 42

### $TERM environment variable

xterm-256color

### Installation

https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.tar.gz

**Comment by zeertzjq** [comment]
Just use a different augroup name
