### ISSUE TITLE
Missing command line highlights

### ISSUE THREAD

**Issue by MariaSolOs** [neovim/neovim#24710]
### Problem

I use `noice`'s command line UI, and now highlights are missing in the input field.

Now:
<img width="515" alt="image" src="https://github.com/neovim/neovim/assets/62502207/e0d7a89c-f66e-4fa3-99e6-89daf7c18711">

Using `v0.10.0-dev-811+g58a1ef8e6`:
<img width="500" alt="image" src="https://github.com/neovim/neovim/assets/62502207/8e3f48f2-d19e-4146-af2a-1187e58daa28">
 
My suspicion is that something happened with the recent changes around Treesitter injections (Folke is OOF so I discarded a change on `noice` itself). `noice` associates [specific languages based on the prefix of the command](https://github.com/folke/noice.nvim/blob/894db25ec726d32047799d4d0a982b701bec453b/doc/noice.nvim.txt#L145-L150), so it seems like something there isn't working anymore.

### Steps to reproduce

1. Update `nvim` to whatever is on `master` rn.
2. Install `noice` and enable `cmdline` in the plugin's options.
3. Open it and notice the missing highlights.

### Expected behavior

For highlights to be correctly applied.

### Neovim version (nvim -v)

v0.10.0-dev-819+ge551d623d

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Mac Ventura 13.5

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

bob

**Comment by clason** [comment]
Yes, there have been multiple breaking changes regarding injections that plugins need to adapt to. It's unfortunate that Folke is on vacation, but this is purely a noice issue.

**Comment by MariaSolOs** [comment]
Oh okay. It sounds like it’s an expected change then. I’ll try to see if I can fix it :)

I haven’t looked carefully, but are these changes documented somewhere so that plugin maintainers know what to change?

**Comment by clason** [comment]
Of course: `:h news.txt`

**Comment by lewis6991** [comment]
Also note treesitter is still considered experimental and subject to change so we can only guarantee and document so much regarding the API.

**Comment by clason** [comment]
Also, noice is nice, but _very_ aggressive about leveraging unstable Neovim internals. Constant breakage is to be expected; it's not suitable for the faint of heart.

**Comment by MariaSolOs** [comment]
@clason got it. I’ll take that into account in the future. Sorry about that!
