### ISSUE TITLE
Advertise directcolor support in Neovim terminal

### ISSUE THREAD

**Issue by hpjansson** [neovim/neovim#24717]
### Problem

The Neovim terminal (`:terminal`) does not appear to advertise directcolor support anywhere when `termguicolors` is set. This makes it impossible for CLI programs to unambiguously determine whether directcolor sequences can be used when running in the Nvim terminal.

Steps to reproduce:

1. Install `nvim`.
2. Install a program that uses terminal colors, e.g. [`chafa`](https://github.com/hpjansson/chafa), from its master branch.
3. `unset COLORTERM NVIM_TUI_ENABLE_TRUE_COLOR` (the former may not be present, and it's my understanding that the latter is deprecated).
4. `export TERM=vte`. This step probably doesn't matter as long as you indicate an outer terminal that has directcolor support.
5. Start `nvim`.
6. Issue `:terminal` in Nvim and hit `i`.
7. Print something that issues SGR codes, e.g. `chafa test.png`.
8. `chafa` has no way to determine whether the Nvim terminal supports directcolor, so will only use 256 colors. If you try to use directcolor, the output will look corrupted.
9. Exit Nvim.
10. Add `set termguicolors` to `init.vim`.
11. Repeat steps 5-8. Observe that `chafa` will still use only 256 colors, because it can't determine from the environment that directcolor support is now available.
12. Issue `chafa -c full test.png` and observe that correct directcolor output is possible if forced.

Additionally, the inner `TERM` is set to `xterm-256color` in both cases and there appears to be no other environment variables indicating directcolor support. `COLORTERM` almost does the job, but Neovim doesn't set it unconditionally.

### Expected behavior

Neovim should make it possible for CLI programs to differentiate 256-color from directcolor `:terminal` environments. The exact mechanism is of lesser importance, but I guess it could either export a different TERM string or set some other environment variable. The goal is to produce optimal output in Neovim without extra prompting from the user.

It could also be resolved with some policy, e.g. "it's the user's responsibility to ensure `COLORTERM` is set".

A quick test with vim 9.0.1632 showed that it exports `COLORS=16777216` when outer `TERM=xterm-direct2`.

**Comment by hpjansson** [comment]
Great, so the resolution is that it's the user's responsibility, then. Thanks for the clarification.

**Comment by hpjansson** [comment]
https://github.com/neovim/neovim/blob/88887a7be707773f908dd6e597f0293d3c1a0faa/src/nvim/eval/funcs.c#L3985-L3991

The problem is with "only if it was set in the parent terminal at all". Unfortunately, that can't always be relied on. E.g. openssh preserves `TERM` but strips `COLORTERM` from the environment. Then nvim sets `TERM` to `xterm-256color`, and now neither env var is usable. The session would look like this:

```bash
local$ echo $TERM $COLORTERM
vte-direct truecolor
local$ ssh remote
remote$ echo $TERM $COLORTERM
vte-direct
remote$ nvim
# :terminal
remote-nvim$ echo $TERM $COLORTERM
xterm-256color
```

The user can work around it either by setting `COLORTERM` in their remote shell profile or adding it to sshd's `AcceptEnv` list, if they have the permissions to do so.

**Comment by gpanders** [comment]
I'm trying to think of an example where setting `$COLORTERM` regardless of whether or not it is set in the parent terminal would be bad.

If `$COLORTERM` is not set in the parent terminal, it might mean that the terminal does not support 24-bit color. But it could also just mean that the terminal doesn't set it, or the user is in an SSH session (as you said). So you cannot really infer anything about that.

If the user has `'termguicolors'` set then we should trust them that their terminal supports 24 bit color. If it does not, then the colors in Nvim are going to look bad already anyway, so using direct colors in the terminal emulator won't make it any worse.

I didn't see any discussion in https://github.com/neovim/neovim/pull/13315 around the reasoning for only setting `$COLORTERM` if it was already set in the parent terminal, so I'm not sure if there are any gotchas I'm not thinking of.

But we could try it out and see what (if anything) breaks.
