### ISSUE TITLE
Migrate old tests to lua/busted

### ISSUE THREAD

**Issue by etellman** [neovim/neovim#24741]
### Problem

This is related to https://github.com/neovim/neovim/issues/21559

#21559 is about getting the old tests to run with the new build system. I'm guessing that the long-term goal would be to replace the old tests with lua/busted tests, so all tests use the same approach. 

I'm a long-time vim user, but am new to contributing to vim, so I'd be happy to help with this, if there is interest. I did a little experiment with a single test, and I'll attach a PR shortly.

### Expected behavior

This is more of a project than a single issue, but I think the desired end state is that the `test/old` directory is deleted after all the tests are moved to `test/funtional` or similar.

**Comment by lewis6991** [comment]
This is of interested, but should be done in such a way to not increase the difficulty of porting vim patches. I.e. a solution that doesn't touch `test/old` directly, but just a new runner around it.

**Comment by etellman** [comment]
Thanks for the quick response. 

So test/old will always be present, since they come from vim, but it would be nice if those tests are run via busted instead of how they're run now. They've already been moved, as part of https://github.com/neovim/neovim/issues/21559.

 Is the goal is to make sure that neovim always exactly matches vim, so old tests are really compatibility tests and need to stay around indefinitely?

**Comment by etellman** [comment]
that makes sense, but now I'm a bit fuzzy on what, if anything, is left to do for https://github.com/neovim/neovim/issues/21559.

Is the goal to replace things like `test/old/testdir/runvim.sh` with something else that fits better with how the new tests are run? Or, if that's not the goal, can you give a more specific example of some file that would be replaced or something else that needs to change? 

It sounds like the goal is to change as little as possible, and that's pretty easy, since it can be accomplished by changing nothing. :^)

**Comment by etellman** [comment]
I'll close this issue, as it looks like it isn't a good idea, and any work that you actually want done would be covered by https://github.com/neovim/neovim/issues/21559 or some other issue I didn't notice.

**Comment by justinmk** [comment]
We tried this early on: https://github.com/neovim/neovim/issues/1286

But we stopped that to reduce friction of merging from Vim. If Vim tests are converted to Vim9script then we'll be forced to revisit this, both by using https://github.com/tjdevries/vim9jit and by being more selective about what we merge from upstream.
