### ISSUE TITLE
How to install neovim in Windows?

### ISSUE THREAD

**Issue by drozzy** [neovim/neovim#2474]
I am thinking of returning to vim, and seeing as neovim is the future, I wanted to go with it instead.

I use Windows primarily, and it seems like neovim will support better GUI. How can I try it out on Windows? Did anyone have luck making it run?

I'm using Windows 7 64-bit and Windows 8 64-bit on my machines.
Thank you.

**Comment by glts** [comment]
This is still work in progress.
https://github.com/neovim/neovim/wiki/FAQ#when-will-windows-be-supported
