### ISSUE TITLE
vim.iter: faster check for list-like table

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#24746]
_(This is partly to check my understanding, partly to write down rationale, and partly to propose a potential change.)_ @gpanders 

### Problem

Currently to check if a table is a list, we use `pairs()` to iterate (potentially) the entire table. Calls to `Iter.new()` always pay this cost and can't opt-out of it.
https://github.com/neovim/neovim/blob/e928161bde262c238f79bc0fd84e60178ff6a321/runtime/lua/vim/iter.lua#L906-L917

Arguments in favor of the current logic?

- Iter pipelines inherently are O(n) so doing an extra scan is a reasonable cost.
- Handles unusual lists/arrays.

Related: https://github.com/neovim/neovim/issues/24141

### Expected behavior

Instead of using `pairs()`, treat any table where `t[1] == nil or t[#t] == nil` as non-list, and `t[1] ~= nil and t[#t] ~= nil` as list. Change the logic to:

```lua
-- Decide if the source table is a list.
if src[1] == nil and src[#src] == nil then
  return Iter.new(pairs(src))
end
end
return ListIter.new(ipairs(src))
```

**Advantages:**

- easy to document and understand
- fast

**Disadvantages:**

- May treat a non-list as a list, if `t[1]` and `t[#t]` are non-nil in a dict-like table.
    - Callers can workaround this by setting `t[1] = nil`.

**Comment by gpanders** [comment]
A list-like table _must_ have consecutive integer indices starting at 1 if we want to be able to use the length (`#`) operator, which we make heavy use of for the list optimizations.

From the [Lua reference manual](https://www.lua.org/manual/5.1/manual.html#2.5.5) (emphasis added):

>The length of a table t is defined to be any integer index n such that `t[n]` is not nil and `t[n+1]` is nil; moreover, if `t[1]` is nil, `n` can be zero. For a regular array, with non-nil values from 1 to a given `n`, its length is exactly that `n`, the index of its last value. **If the array has "holes" (that is, nil values between other non-nil values), then `#t` can be any of the indices that directly precedes a nil value (that is, it may consider any such nil value as the end of the array).**

It is insufficient to only check that `t[1] ~= nil` to infer that `t` is a list. A table such as `{ 'a', 'b', nil, 'd', 'e' }` might have length 5, or length 2. According to the standard, it's undefined.

The `pairs()` check in the constructor is kind of a bummer, it's obviously slow for large tables, but I don't know of a better way to ensure correct behavior.

**Comment by T-727** [comment]
[this answer](https://stackoverflow.com/a/66370080) from StackOverflow seems promising apart from the last case because of the behaviour gpanders mentioned above.
> A table such as { 'a', 'b', nil, 'd', 'e' } might have length 5, or length 2. According to the standard, it's undefined.
```lua
function isarray(t)
  return #t > 0 and next(t, #t) == nil
end

print(isarray{}) --> false
print(isarray{1, 2, 3}) --> true
print(isarray{a = 1, b = 2, c = 3}) --> false
print(isarray{1, 2, 3, a = 1, b = 2, c = 3}) --> false
print(isarray{1, 2, 3, nil, 5}) --> true (PUC Lua) | false (LuaJIT)
```

**Comment by clason** [comment]
There really is no better way than iterating the table and checking for nils.

Openresty/LuaJIT does the same but compiled; that is the only option for better performance.

**Comment by justinmk** [comment]
> if we want to be able to use the length (`#`) operator, which we make heavy use of for the list optimizations.

Thanks, that's the key info. 

I was thinking that if we document "a list is a table with an item at `t[1]`", then the caller is responsible for checking for that, to avoid undefined behavior of `vim.iter`. Advantages are:

- Gives a way to "opt out" of the current full scan that every `vim.iter` caller pays. With the current impl there's no way to opt-out of that scan.
- Improves performance for the common case. I expect "hetergenous" tables to be unusual for `vim.iter`. Any evidence that I'm wrong?

**Comment by clason** [comment]
Disadvantage: we use a different definition of "list" than everybody else...

**Comment by justinmk** [comment]
Different compared to what? The Lua `#` behavior implies that this definition is a Lua convention.

**Comment by lewis6991** [comment]
`__len` is a lua 5.2 thing.

**Comment by clason** [comment]
> Different compared to what? The Lua # behavior implies that this definition is a Lua convention

Different to the Lua convention everywhere else.

**Comment by justinmk** [comment]
> `__len` is a lua 5.2 thing.

it's our luaref.txt though?

**Comment by lewis6991** [comment]
That shouldn't be in their. Not even LuaJIT enables `__len` by default.

http://www.lua.org/manual/5.2/readme.html

> tables honor the __len metamethod

**Comment by gpanders** [comment]
We could add an optional keyword argument to `vim.iter()` called `skipcheck` or something that always uses `ListIter` for table arguments. This would basically be a "trust me I know what I'm doing" kind of thing. If stuff doesn't work it's explicitly on the user.

Alternatively we could expose the `ListIter` table directly which would allow `vim.iter.ListIter(t)`. Though I don't think this should be broadly advertised as `vim.iter()` should be the main entry point of the API.

**Comment by justinmk** [comment]
> `skipcheck` or something that always uses `ListIter` for table arguments

Would dict-like tables continue to pay the ["is this a list?"](https://github.com/neovim/neovim/blob/e928161bde262c238f79bc0fd84e60178ff6a321/runtime/lua/vim/iter.lua#L906) cost?

**Comment by gpanders** [comment]
>Would dict-like tables continue to pay the ["is this a list?"](https://github.com/neovim/neovim/blob/e928161bde262c238f79bc0fd84e60178ff6a321/runtime/lua/vim/iter.lua#L906) cost?

Dict-like tables can already avoid this with `vim.iter(pairs(t))`, which is what `vim.iter` does anyway if `t` is not list-like.

> Maybe need an arg like `kind='list'|'dict'` ?

If we want to provide a "danger zone/experts only" interface, I think the simplest option would simply be to expose `ListIter` directly.

**Comment by justinmk** [comment]
> Alternatively we could expose the `ListIter` table directly which would allow `vim.iter.ListIter(t)`.

Not in favor of that, it adds lots of new surface area (+docs) compared to an optional `vim.iter('list', ...)` entrypoint.

**Comment by gpanders** [comment]
@justinmk Thinking about this more. I think I'd be in favor of making this change along with clear documentation of how it works. We are sacrificing correctness for performance, but I think that's reasonable, because:

1. In Lua, the fast majority of tables for which `t[1] ~= nil and t[#t] ~= nil` is true _will_ be real lists
2. In the uncommon case where that is not true, it is easy to tell a user to use `pairs()` manually

**Comment by justinmk** [comment]
> majority of tables for which `t[1] ~= nil and t[#t] ~= nil` is true _will_ be real lists

That's my intuition also. 

- Current situation: common case is always slow, and no way to opt-out of the table scan.
- Proposal: common case is always fast, and uncommon case can opt-out of list treatment via `pairs()`.
    - con: caller may accidentally treat dict or sparse array as a dense array.
        - counterargument: the same "con" applies to `#`, so it's reasonable to expect callers to explicitly call `vim.iter(pairs(...))` if they want to be "safe" (and take the performance hit).

**Comment by gpanders** [comment]
Note this change also has another (subtle) effect in that it will now modify the original source table. Currently we make a copy of the `src` table (during the "scan" step) which is passed to `ListIter`, so the original table is unmodified.

We can tell users to `deepcopy()` the list if they don't want it modified, but this also needs to be documented.

**Comment by mfussenegger** [comment]
> In Lua, the fast majority of tables for which t[1] ~= nil and t[#t] ~= nil is true will be real lists

Does this even work? `#` doesn't include all items if there are gaps

```
local buffers = {}

buffers[1] = 'foo'
buffers[3] = 'bar'

print(#buffers)
-- 1
```

(It probably doesn't matter for the discussion here, but there have been a couple of bugs caused by using `ipairs` on tables indexed by buffer, and having it seemingly work because buffers start at 1 and increment by 1)

---

> Note this change also has another (subtle) effect in that it will now modify the original source table

I second the concerns. Modifying table's by iterating over it would be very surprising.

**Comment by justinmk** [comment]
> Does this even work? `#` doesn't include all items if there are gaps

The `t[#t]` check is only a best-effort, and for non-dense arrays caller is expected to opt-out of list-literator behavior.

> Note this change also has another (subtle) effect in that it will now modify the original source table. Currently we make a copy of the `src` table (during the "scan" step) which is passed to `ListIter`, so the original table is unmodified.

Oh, yeah that's a dealbreaker. Could we not maintain separate state to track the current head/tail/etc? But if that complicates the code, probably not worth it.

So it seems like the current status is:

- Caller can opt-out of table-scan by wrapping input with pairs().
- Anyone that _doesn't_ opt out presumably wants "list" behaviors (`rev()`/`slice()`/etc), which requires a copy (and thus a scan) anyway.

**Comment by gpanders** [comment]
>Could we not maintain separate state to track the current head/tail/etc? But if that complicates the code, probably not worth it.

We do do this already, but functions like `map()` can change the actual values in the table, apart from the head/tail position.

>So I think there's nothing left to do here? We don't need to https://github.com/neovim/neovim/issues/24746#issuecomment-1826326033 because list behavior requires a copy so a scan is unavoidable.

Agreed.
