### ISSUE TITLE
Cursor Shape

### ISSUE THREAD

**Issue by DAddYE** [neovim/neovim#2475]
In vim right now I can change the cursor shape in insert mode with:

```vim
" Verical bar in insert mode (for iTerm users only)
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
```

Is that possible in neovim?

**Comment by glts** [comment]
See https://github.com/neovim/neovim/wiki/FAQ#how-can-i-change-the-cursor-shape-in-the-terminal

**Comment by DAddYE** [comment]
Thanks @glts

**Comment by liujoey** [comment]
Sorry to revisit this issue again, but I've tested it in Gnome-terminal and urxvt, neither works. Does it only work in iTerm2? At least from the document I didn't see any limitations. This is a very useful feature.

**Comment by Pyrohh** [comment]
@liujoey perhaps you should open an issue for it, as it doesn't look like many people are subscribed to this issue.

**Comment by critiqjo** [comment]
For me, it works in urxvt v9.21 and gnome-terminal v3.16.1

**Comment by eastwood** [comment]
Yea I don't believe this works in iTerm2 for OSX

**Comment by mhinz** [comment]
@eastwood It should: https://github.com/mhinz/dotfiles/blob/master/vim/vimrc#L349-L359

**Comment by khamer** [comment]
This is pretty specific, but is there a way to switch cursors immediately upon entering insert mode? It appears that in general, hitting 'i' (so the cursor doesn't move) on a non-blank line doesn't trigger swapping the cursor until I type something.

**Comment by eastwood** [comment]
Interesting. I'll try again this morning and let you know both within tmux
and by itself.

**Comment by khamer** [comment]
@eastwood maybe I'll make a new issue and mention that specific glitch, as if you're using the cursor shape as a reminder of what mode you're in, this glitch is noticeable. Even as a someone who has been using vim/gvim for ~6 years, I immediately noticed this - didn't realize how much I like the cursor shape as an indication of mode.

**Comment by khamer** [comment]
Digging further, I can only duplicate this issue with termite, but not with rxvt-unicode, xterm, uxterm, or lxterm. I think the issue might be with termite and not with nvim.

@eastwood what terminal emulator were you using when you duplicated the issue?

**Comment by eastwood** [comment]
Using iterm2 for osx to duplicate.

**Comment by mhinz** [comment]
@eastwood What iTerm2 version using? Stable (`2.1.*`) or beta (`2.9.*`)? The former works for sure.

**Comment by eastwood** [comment]
Turns out I was using `$TMUX_TUI_ENABLE_SHELL_CURSOR=1` without the `NVIM` equivalent.
Sorry for the false positive :)

**Comment by eastwood** [comment]
I can confirm this works on iTerm stable, with and without tmux

**Comment by khamer** [comment]
I opened a separate issue (#4474) to discuss that behavior specifically.

**Comment by codeHatcher** [comment]
heads up, doesn't work with 2.9 on osx

**Comment by alex179ohm** [comment]
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23 (Gentoo linux)
```vim
$NVIM_TUI_ENABLE_CURSOR_SHAPE = 1
" insert mode - line
let &t_SI .= "\<Esc>[5 q"
"replace mode - underline
let &t_SR .= "\<Esc>[4 q"
"common - block
let &t_EI .= "\<Esc>[3 q"
```
This works for me.
