### ISSUE TITLE
Incorrect file type for `.mli` files

### ISSUE THREAD

**Issue by theteachr** [neovim/neovim#24762]
### Problem

The expected file type for `.mli` files is `ocaml_interface`, but when one is opened, the file type is set to `ocaml` which results in broken syntax highlighting (see below).

![image](https://github.com/neovim/neovim/assets/64728420/9e45c762-e8f6-4579-9491-01debda57bbf)

Manually doing a `:se ft=ocaml_interface` fixes it.

![image](https://github.com/neovim/neovim/assets/64728420/a603c3e2-e272-40c7-a08e-209d0ad55865)

### Steps to reproduce

Open any `.mli` file.

```vim
set filetype?
```

will say `ocaml`.

### Expected behavior

Doing

```vim
set filetype?
```

on a(n) `.mli` file should output `ocaml_interface`.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

Yes, but in case of Vim, the syntax highlighting is fine, even with the file type set to `ocaml`, in fact, setting it to `ocaml_interface` breaks, which works in Neovim. 

### Operating system/version

macOS 14.0

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by ObserverOfTime** [comment]
The `ocaml_interface` highlights are provided by nvim-treesitter.
The filetype is not set automatically because Vim uses `ocaml` for both.
You can add an autocmd to your config or submit an issue/PR to Vim.

**Comment by theteachr** [comment]
@ObserverOfTime `ocaml_interface` isn't recognised by Vim. It wouldn't make sense to update the filetype on Vim's runtime for `mli` files, as it would just not have any syntax. I created #29193 instead.

**Comment by clason** [comment]
Sorry, if you don't want to make a PR to Vim, you'll have to do this in your own config (`:h vim.filetype.add`).

**Comment by ObserverOfTime** [comment]
> It wouldn't make sense to update the filetype on Vim's runtime for `mli` files, as it would just not have any syntax.

Many filetypes don't have any syntax but are still added there for plugins or treesitter.

**Comment by clason** [comment]
You can also add a simple syntax file that just calls the `ocaml` syntax; there's precedent for that.

**Comment by theteachr** [comment]
@ObserverOfTime Adding this would break the behaviour on Vim, because without this (with `ft=ocaml`), syntax is correct. It's broken on Neovim with tree sitter. When I add this, it will have no syntax as `ocaml_interface` isn't recognized by Vim.

**Comment by clason** [comment]
And I'm saying it's trivial to teach Vim. This is the (only) way forward here, apart from making the (equally trivial) changes in your config.

**Comment by ObserverOfTime** [comment]
You can just load the `ocaml` syntax from `ocaml_interface` in Vim.
