### ISSUE TITLE
Incomplete build instructions?

### ISSUE THREAD

**Issue by themightyoarfish** [neovim/neovim#24761]
### Problem

I am trying to build neovim `stable` on Ubuntu 20.04, so I follow https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites.

However, when running `cmake ..`:

```
-- CMAKE_INSTALL_PREFIX=/usr/local
-- CMAKE_BUILD_TYPE=Release
-- Replacing -O3 in CMAKE_C_FLAGS_RELEASE with -O2
-- Checking Lua interpreter: /usr/bin/luajit
/usr/bin/luajit: module 'mpack' not found:
	no field package.preload['mpack']
	no file './mpack.lua'
	no file '/usr/share/luajit-2.1.0-beta3/mpack.lua'
	no file '/usr/local/share/lua/5.1/mpack.lua'
	no file '/usr/local/share/lua/5.1/mpack/init.lua'
	no file '/usr/share/lua/5.1/mpack.lua'
	no file '/usr/share/lua/5.1/mpack/init.lua'
	no file './mpack.so'
	no file '/usr/local/lib/lua/5.1/mpack.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/mpack.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: at 0x56040edd9f40
	[C]: at 0x56040ed8d1d0
-- [/usr/bin/luajit] The 'mpack' lua package is required for building Neovim
-- Checking Lua interpreter: /usr/bin/lua5.1
/usr/bin/lua5.1: module 'mpack' not found:
	no field package.preload['mpack']
	no file './mpack.lua'
	no file '/usr/local/share/lua/5.1/mpack.lua'
	no file '/usr/local/share/lua/5.1/mpack/init.lua'
	no file '/usr/local/lib/lua/5.1/mpack.lua'
	no file '/usr/local/lib/lua/5.1/mpack/init.lua'
	no file '/usr/share/lua/5.1/mpack.lua'
	no file '/usr/share/lua/5.1/mpack/init.lua'
	no file './mpack.so'
	no file '/usr/local/lib/lua/5.1/mpack.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/mpack.so'
	no file '/usr/lib/lua/5.1/mpack.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: ?
	[C]: ?
-- [/usr/bin/lua5.1] The 'mpack' lua package is required for building Neovim
-- Checking Lua interpreter: /usr/bin/lua
/usr/bin/lua: module 'mpack' not found:
	no field package.preload['mpack']
	no file './mpack.lua'
	no file '/usr/local/share/lua/5.1/mpack.lua'
	no file '/usr/local/share/lua/5.1/mpack/init.lua'
	no file '/usr/local/lib/lua/5.1/mpack.lua'
	no file '/usr/local/lib/lua/5.1/mpack/init.lua'
	no file '/usr/share/lua/5.1/mpack.lua'
	no file '/usr/share/lua/5.1/mpack/init.lua'
	no file './mpack.so'
	no file '/usr/local/lib/lua/5.1/mpack.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/mpack.so'
	no file '/usr/lib/lua/5.1/mpack.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: ?
	[C]: ?
-- [/usr/bin/lua] The 'mpack' lua package is required for building Neovim
CMake Error at CMakeLists.txt:187 (message):
  Failed to find a Lua 5.1-compatible interpreter
```

I had to `sudo luarocks install mpack` to get around this.

Then the next issue is that it would not find libuv
```
CMake Error at /usr/local/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Libluv (missing: LIBLUV_LIBRARY LIBLUV_INCLUDE_DIR)
  (Required is at least version "1.43.0")
```

I have installed the current master of libuv in `/usr/local`, but apparently the cmake integration does not find it, presumable because it's looking for the wrong name
```
  find_library called with the following settings:

    VAR: LIBLUV_LIBRARY
    NAMES: "luv_a"
           "luv"
           "libluv_a"
           "luv.so"
```
and not `uv`.

Possibly this is also a cmake version problem? (3.24.1)

Anyway, are there build instructions for ubuntu 20.04 somewhere or is this considered an unsupported system?

### Steps to reproduce

clone neovim
mkdir build; cd build
cmake ..

### Expected behavior

Neovim compiles with the documented build requisites installed.

### Neovim version (nvim -v)

7d4bba7aa7a4a3444919ea7a3804094c290395ef

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 20.04.6 LTS

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color inside ssh

### Installation

from source

**Comment by zeertzjq** [comment]
Where does `cmake ..` come from? It's not present in any build instructions for Linux.

**Comment by zeertzjq** [comment]
<https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites> doesn't contain anything related to your steps. Are you trying to link <https://github.com/neovim/neovim/wiki/Building-Neovim#third-party-dependencies>?

**Comment by themightyoarfish** [comment]
actually this is me being stupid. I'm so used to cmake projects that seeing any `CMakeLists.txt` makes me go to `mkdir build; cd build; cmake ..` immediately, so I missed that I'm supposed to use `make` from the root directory.
