### ISSUE TITLE
floatwin breaks display of multibyte characters at window boundary.

### ISSUE THREAD

**Issue by kuuote** [neovim/neovim#24775]
### Problem                                                                                                         

floatwin breaks display of multibyte characters at window boundary.

### Steps to reproduce                                                                                              

1. launch `nvim --clean`

2. Sourcing following lua code

```lua
vim.cmd('tabnew | setlocal buftype=nofile bufhidden=wipe noswapfile')
vim.api.nvim_buf_set_lines(0, 0, -1, false, { 'あ' })
local buf = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_lines(buf, 0, -1, false, { 'あ' })
local win = vim.api.nvim_open_win(buf, false, {
  relative = 'win',
  row = 0,
  col = 2,
  width = 2,
  height = 1,
})
```

Show floating window contains `あ` and base buffer is look empty. 

### Expected behavior

Display properly.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-872+gc54682f75-dirty

### Vim (not Nvim) behaves the same?

No. it is problem of floatwin.

### Operating system/version

Arch Linux

### Terminal name/version

PuTTY

### $TERM environment variable
                                                                                                                      
screen-256color
                                                                                                                      
### Installation
                                                                                                                      
from source

**Comment by zeertzjq** [comment]
This sounds like a problem with PuTTY

**Comment by zeertzjq** [comment]
Does it work if you set `$TERM` to `putty-256color`?

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/ui_compositor.c b/src/nvim/ui_compositor.c
index 59e9f71a6..e9b23d129 100644
--- a/src/nvim/ui_compositor.c
+++ b/src/nvim/ui_compositor.c
@@ -402,7 +402,7 @@ static void compose_line(Integer row, Integer startcol, Integer endcol, LineFlag
       if (col == endcol - 1) {
         skipend = 0;
       }
-    } else if (n > 1 && linebuf[col - startcol + 1][0] == NUL) {
+    } else if (col == startcol && n > 1 && linebuf[1][0] == NUL) {
       skipstart = 0;
     }
 
```
