### ISSUE TITLE
LSP: make stderr handling configurable per server

### ISSUE THREAD

**Issue by bgshacklett** [neovim/neovim#24784]
### Problem

The stderr stream is often used for any output which is not intended for consumption by the calling application. I.e.: messages sent to stderr are not necessarily errors. One good example of this is visible at https://github.com/hashicorp/terraform-ls/issues/1271.

While the `terraform-ls project` is working on their log mechanism, the current treatment of stderr is particularly harsh for language servers which follow common recommendations for outputting diagnostic information to stderr:
https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html

>    Variable: FILE * stderr
>
>       The standard error stream, which is used for error messages **and diagnostics** issued by the program. 

The current behavior has the downside of the LSP Log growing to extremely large sizes in some cases, in addition to confusion as to the true meaning of its contents.

### Steps to reproduce using "nvim -u minimal_init.lua"

1. Configure an affected terraform-ls language server, such as terraform-ls or taplo
2. Edit associated files for a while
4. Run `:LspLog`

### Expected behavior

Minimal: Do not assume every output to stderr is an error.

Stretch goal: Potentially allow for custom handling of stderr output based on its contents to avoid the log file growing out of control.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-376+g677e02be4-Homebrew Build type: Release LuaJIT 2.1.0-beta3

### Language server name/version

Multiple, including terraform-ls, taplo

### Operating system/version

macOS 13

### Log file

Example:
```
[ERROR][2023-08-18 09:33:24] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/bgshacklett/.local/bin/taplo"	"stderr"	' INFO taplo: registered request handler method="initialize"\n INFO taplo: registered request handler method="textDocument/documentSymbol"\n INFO taplo: registered request handler method="textDocument/foldingRange"\n INFO taplo: registered request handler method="textDocument/formatting"\n INFO taplo: registered request handler method="textDocument/completion"\n INFO taplo: registered request handler method="textDocument/hover"\n INFO taplo: registered request handler method="textDocument/documentLink"\n INFO taplo: registered request handler method="textDocument/semanticTokens/full"\n INFO taplo: registered request handler method="textDocument/prepareRename"\n INFO taplo: registered request handler method="textDocument/rename"\n INFO taplo: registered notification handler method="textDocument/didOpen"\n INFO taplo: registered notification handler method="initialized"\n INFO taplo: registered notification handler method="textDocument/didClose"\n INFO taplo: registered notification handler method="textDocument/didChange"\n INFO taplo: registered request handler method="taplo/convertToJson"\n INFO taplo: registered request handler method="taplo/convertToToml"\n INFO taplo: registered request handler method="taplo/listSchemas"\n INFO taplo: registered notification handler method="workspace/didChangeConfiguration"\n INFO taplo: registered notification handler method="workspace/didChangeWorkspaceFolders"\n INFO taplo: registered request handler method="taplo/associatedSchema"\n INFO taplo: registered notification handler method="taplo/associateSchema"\n INFO taplo: registered notification handler method="textDocument/didSave"\n INFO taplo: LSP server listening transport="stdio"\n'
```

**Comment by bfredl** [comment]
> harsh for language servers which follow common recommendations for outputting diagnostic information to stderr:

I do not think it is a common recommendation for unix programs to flood stderr with a lot of unwanted diagnostic data unless _either_ something really got wrong or some kind of `--verbose` flag is supplied.

But regardless, as the usage of stderr is not mandated in the LSP spec, so the reasonable thing for do would be able to specify how it should be handled per server. I don't think the default behavior of storing it in the log is unreasonable tho.

**Comment by bgshacklett** [comment]
Agreed on all counts. The fact that the `terraform-ls` server outputs as much diagnostic output as it does _is_ abnormal, and the default behavior of logging it is likely the a better option than dropping it, unless further flexibility can be made available. Allowing for this output to be treated differently depending upon the language server would certainly be a step in the right direction. The nvim-lspconfig would be a great place to insert "sane" defaults on a per-server basis, IMO.

I maintain, however, that marking all output written to stderr with an "Error" prefix is not an ideal default. In the case of the included output from the `taplo` language server, the output, itself, is marked as "INFO", but it is prefixed with Error by the language server client.

**Comment by mfussenegger** [comment]
I'd rather not remove the ERROR prefix. Some servers if not configured correctly immediately exit after startup - currently the only pieces of information you got is the warning message about the exit, and then the log. Having an `ERROR` prefix for the log messages is useful in that case, as it's most likely to contain some hint of what went wrong. (And the only piece of insight you get)

And I don't think the complexity of making this configurable per server is warranted. As far as I can tell the majority of them doesn't flood stderr.
If the log size is the main concern, we should rather have a log rotation mechanism. That relates a bit to https://github.com/neovim/neovim/pull/7062
