### ISSUE TITLE
Filetype plugin not recognised when using generic filename <filetype>_<name>.vim and plugin starts with the recommended disabling option

### ISSUE THREAD

**Issue by PreciousChicken** [neovim/neovim#24781]
### Problem

Filetype plugins do not appear to be recognised when they are given a generic filename in the format of `<filetype>_<name>.vim` (as per `:help ftplugin-name`) and they additionally include the recommended disabling option `if exists("b:did_ftplugin")` (as per `:help write-filetype-plugin`).  Filetype plugins that follow the naming format `<filetype>.vim` or do not include the disabling option are not affected.

This problem does not exist in Neovim 0.8.3 (as tested using a Nix package) nor Vim 9.0 (1-1678).  I originally thought this was a Vim problem and submitted an issue there, prior to realising it was Neovim only (although admittedly not before thoroughly confusing myself).  I became aware of this after my own filetype plugin, [vim-groff-viewer](https://preciouschicken.com/software/vim-groff-viewer/), stopped working for no apparent reason.

If this is not a problem and it is just my own misunderstanding and / or configuration, then apologies in advance.

### Steps to reproduce

1.  Create a file entitled ***text_a.vim*** within the folder ***~/.local/share/nvim/site/ftplugin***.  You may have to create this folder if it does not exist.

2.  Copy and paste the following text into ***text_a.vim***:

```vimscript
" Disabling option per :help write-filetype-plugin
if exists("b:did_ftplugin")
	finish
endif
let b:did_ftplugin = 1

nnoremap <leader>test :echom "echo from text"<CR>
```

3.  Now returning to your home directory create a generic text file:

```bash
echo "hello world" >> hw.txt
```

4.  Open the text file using neovim (`nvim hw.txt`) and type `<leader>test`.  This will cause neovim to (incorrectly) enter insert mode.

### Expected behavior

Neovim should echo "echo from text."  However it does not as the ftplugin is not recognised.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

No, Vim 9.0 (Patches 1-1678) does not have this issue, the echo statement shows "echo from text".

### Operating system/version

Linux Manjaro 23.0.0 also tested on VM running Ubuntu 22.04.3 LTS

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

Manjaro: Manjaro Extra Repository (`pamac install neovim`); Ubuntu VM: Snap (`sudo snap install nvim --classic`)

**Comment by zeertzjq** [comment]
This has already been fixed.
