### ISSUE TITLE
No way to make extmark conceal behave like :syntax/matchadd() conceal without replacement char

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#24782]
### Problem

From `:h 'conceallevel'`
```
	1		Each block of concealed text is replaced with one
			character.  If the syntax item does not have a custom
			replacement character defined (see |:syn-cchar|) the
			character defined in 'listchars' is used.
			It is highlighted with the "Conceal" highlight group.
	2		Concealed text is completely hidden unless it has a
			custom replacement character defined (see
			|:syn-cchar|).
```

This is respected by `:syntax` and `matchadd()` conceal without a replacement char: show `lcs-conceal` when `&conceallevel = 1`, completely hidden when `&conceallevel = 2`.

However, this is not achievable using extmark conceal, as extmark conceal behaves the same with `&conceallevel = 1` vs. `&conceallevel = 2`:
- If `conceal` is empty string, the text is completely hidden in either case
- If `conceal` is a character, the text is replaced with that char in either cas

### Expected behavior

A way to make extmark conceal behave like `:syntax`/`matchadd()` conceal without replacement char. It may either replace current behavior (if current behavior isn't useful), or be enabled using a new possible value for `conceal` field in `opts` of `nvim_buf_set_extmark`.

**Comment by bfredl** [comment]
I'd say the existing behavior is a bug. if extmark conceal respects cole=0 vs cole=1, it should also respect the user's choice of cole=1 vs cole=2. The intention of adding the feature was to allow concealing in tree-sitter syntax to follow the conceal behavior of the legacy `:syntax` definitions they replaced.
