### ISSUE TITLE
neovim and perforce not playing nice when diffing

### ISSUE THREAD

**Issue by ahshah** [neovim/neovim#2478]
I recently started using nvim at work, where we use Perforce for source control. Perforce has a handy tool for conflict resolution that is invoked via the following:

    $ p4 resolve ...

This causes the Perforce client program to iterate over each file, tagged as needing an integration, and asks how to manage conflicts, here is an example:

    $ p4 resolve
    /home/op/ws/hello_world.1.2/hello_world/src/config.c - merging //projects/syscomm/hello_world-0.0.1/src/config.c
    Diff chunks: 0 yours + 2 theirs + 0 both + 0 conflicting
    Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) at:

At this prompt the user can signal that they want to perform a diff of the changes from the two branches by typing the letter 'd' and hitting enter. This causes the Perforce client to launch the user's diff-ing application. The diff-ing application is set by setting the P4DIFF environment variable.  For the examples given here, the P4DIFF variable is set to this:

    export P4DIFF="nvim -d"

Once Perforce launches the diff-ing application, the user examines the diff, to understand what changes were made and how they differ from the file under source control. When they exit the diffing application of their choosing, Perforce attempts to ask them how the user would like to proceed, now that they have viewed the diff.
It is here where nvim has issues:

    $ p4 resolve
    home/op/ws/hello_world.1.2/hello_world/src/config.c - merging //projects/work_project/hello_world-0.0.1/src/config.c
    Diff chunks: 0 yours + 2 theirs + 0 both + 0 conflicting
    Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) at: d
    2 files to edit
    Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) at: EOF reading terminal.
    

The client then exists and you have to fire up the p4 resolve command all over again. Further, when the Perforce client exists, you don't get to process any of the other files. So the full effect looks something like this:

    $ p4 resolve
    home/op/ws/hello_world.1.2/hello_world/src/config.c - merging //projects/work_project/hello_world-0.0.1/src/config.c#2
    Diff chunks: 0 yours + 2 theirs + 0 both + 0 conflicting
    Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) at: d
    2 files to edit
    Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) at: EOF reading terminal.
    //projects/work_project/hello_world-0.0.1/src/config.c   - Resolve skipped
    home/op/ws/hello_world.1.2/hello_world/src/main.c - merging //projects/work_project/hello_world-0.0.1/src/main.c#6
    Diff chunks: 5 yours + 3 theirs + 0 both + 0 conflicting
    Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) am: EOF reading terminal.
    //projects/work_project/hello_world-0.0.1/src/config.c   - Resolve skipped
    home/op/ws/hello_world.1.2/hello_world/src/main_test.c - merging //projects/work_project/hello_world-0.0.1/src/main_test.c#6
    Diff chunks: 15 yours + 31 theirs + 0 both + 0 conflicting
    Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) am: EOF reading terminal.

The original VIM doesn't have the same issue. It looks like this:

    $ p4 resolve
    home/op/ws/hello_world.1.2/hello_world/src/config.c - merging //projects/work_project/hello_world-0.0.1/src/config.c#2
    Diff chunks: 0 yours + 2 theirs + 0 both + 0 conflicting
    Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) at: d
    2 files to edit
    Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) at: s
    //projects/work_project/hello_world-0.0.1/src/config.c   - Resolve skipped
    home/op/ws/hello_world.1.2/hello_world/src/main.c - merging //projects/work_project/hello_world-0.0.1/src/main.c#6
    Diff chunks: 5 yours + 3 theirs + 0 both + 0 conflicting
    Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) am: s
    //projects/work_project/hello_world-0.0.1/src/config.c   - Resolve skipped
    home/op/ws/hello_world.1.2/hello_world/src/main_test.c - merging //projects/work_project/hello_world-0.0.1/src/main_test.c#6
    Diff chunks: 15 yours + 31 theirs + 0 both + 0 conflicting
    Accept(a) Edit(e) Diff(d) Merge (m) Skip(s) Help(?) am: EOF reading terminal.

Notice how the 'Resolve skipped' is going unchanged when using the original vimdiff.  this is because i am selecting the skip option specifically for this case, where in the neovim case, the resolving is getting skipped because the Perforce client thinks that it cannot print ot the screen (I think)

**Comment by fwalch** [comment]
I can't really read your post, can you use code blocks to [format your comment](https://guides.github.com/features/mastering-markdown)?

Anyway, I think this is the same as #2377.

**Comment by ahshah** [comment]
I've addressed your concerns on the formatting, thanks for taking a look!

**Comment by fwalch** [comment]
Should have been fixed by neovim/neovim#2598, please report back if not.
