### ISSUE TITLE
Ephemeral inline virt-text isn't getting rendered

### ISSUE THREAD

**Issue by PlankCipher** [neovim/neovim#24797]
### Problem

Since ef94fb6, ephemeral inline virt-text stopped being rendered. As far as I could understand, that's because `w_buffer->b_virt_text_inline` (count of inline virt text extmarks in a buffer) doesn't get incremented if the `opts` passed to `nvim_buf_set_extmark()` contain `ephemeral = true` and `virt_text_pos = 'inline'`. However, it does get incremented if the extmark is not ephemeral, because in this case `extmark_set()` is invoked, which is the only place that increments said counter.

https://github.com/neovim/neovim/blob/b263c73b083e43761386d46d62524ea104d7abbd/src/nvim/api/extmark.c#L823-L837

When `ephemeral = true` and `virt_text_pos = inline`:
- `nvim_buf_set_extmark()` -> `decor_add_ephemeral()` -> `decor_add()` -> doesn't increment the counter -> virt-text doesn't get rendered

When `ephemeral = false` and `virt_text_pos = inline`:
- `nvim_buf_set_extmark()` -> `extmark_set()` -> increments the counter -> virt-text gets rendered

I'd be more than happy to try to fix it in a PR, but I am not sure where the counter should be incremented.

### Steps to reproduce

nvim --clean
:e file.txt
:lua local ns = vim.api.nvim_create_namespace('something'); vim.api.nvim_set_decoration_provider(ns, { on_line = function() vim.api.nvim_buf_set_extmark(0, ns, 0, 0, { virt_text = { { 'thing', 'Comment' } }, virt_text_pos = 'inline', hl_mode = 'combine', ephemeral = true }) end });

### Expected behavior

Ephemeral inline virt-text should be rendered correctly. In the example above, the word `thing` should be rendered at row 0 col 0 on each line draw.

### Neovim version (nvim -v)

0.10.0 commit b263c73

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Arch Linux 6.4.11-arch1-1 BTW

### Terminal name/version

kitty 0.29.2

### $TERM environment variable

xterm-kitty

### Installation

AUR (neovim-git)

**Comment by zeertzjq** [comment]
The first question is whether ephemeral inline virtual text should be allowed at all.

**Comment by PlankCipher** [comment]
Why not? I mean, it's useful in things like `nvim-cmp`'s ghost_text.

**Comment by zeertzjq** [comment]
Because they aren't added to `b_marktree`, so cursor position and line wrapping don't work properly with them.

**Comment by PlankCipher** [comment]
Sooo... What's the plan? Are they getting fixed or removed? No pressure. Just asking because I'm trying to find a workaround to get the same effect.

**Comment by bfredl** [comment]
At no point of time has ephemeral inline text (yet) been available as an intentional feature. If it was temporarily available it was a bug that was fixed.
