### ISSUE TITLE
Add nil as a valid types for range in `Query:iter_captures`

### ISSUE THREAD

**Issue by ad-chaos** [neovim/neovim#24795]
### Problem

`Query:iter_captures()` can accept `nil` as arguments for `start` and `stop` but its not documented as such

### Steps to reproduce

```lua
-- works.lua
local ts = vim.treesitter
local bufnr = vim.fn.bufnr()
local lang = "lua"

ts.start(bufnr, lang)
ts.highlighter.active[bufnr]
    :get_query(lang)
    :query()
    :iter_captures(ts.get_parser():trees()[1]:root(), bufnr, nil, nil) -- calling with nil, but call doesn't fail
```
`nvim --clean -u works.lua`
# see no errors

### Expected behavior

nil is accepted, but the types suggest its not

https://github.com/neovim/neovim/blob/b263c73b083e43761386d46d62524ea104d7abbd/runtime/lua/vim/treesitter/query.lua#L707-L716

https://github.com/neovim/neovim/blob/b263c73b083e43761386d46d62524ea104d7abbd/runtime/lua/vim/treesitter/query.lua#L670-L677

### Neovim version (nvim -v)

0.10.0-dev-815+gd617c0ce2

### Vim (not Nvim) behaves the same?

no ts in vim

### Operating system/version

macOS 13.4

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

source

**Comment by lewis6991** [comment]
I'd kindly appreciate that instead of raising issues for these kind of minor things, that you raise a simple PR instead.

Also treesitter is still considered experimental so please don't depend too heavily on the APIs

**Comment by ad-chaos** [comment]
apologies for the noise, my thinking was that instead of troubling you with simple PRs, I'd instead raise an issue and that this could then be picked up in the next round of `docs: misc` PRs.
