### ISSUE TITLE
LSP: search workspace symbols across multiple languages without opening any buffer

### ISSUE THREAD

**Issue by BilderLoong** [neovim/neovim#24799]
### Problem

Currently, `vim.lsp.buf.workspace_symbol()` only searches for workspace symbols from [LSP clients attaching to the current buffer](https://github.com/neovim/neovim/blob/b263c73b083e43761386d46d62524ea104d7abbd/runtime/lua/vim/lsp/buf.lua#L9-L10).

This means:
- The user has to open some buffers to search for workspace symbols.
- And only be able to search the workspace symbols from the LSP clients attaching to the current buffer.

### Expected behavior

Support the functionality to 
- Search the workspace symbols across multiple languages.
- Able to search workspace symbols without opening any buffer.

Like what VSCode can do:
![](https://preview.redd.it/6awfybsnjzib1.png?width=3840&format=png&auto=webp&s=be6e7b6310362333d1ed69498c34114c1b03dcdc)

**Comment by BilderLoong** [comment]
Do any other **workspaces** related to LSP features also have this problem? I only test `workspace/symbol` for now.

**Comment by justinmk** [comment]
>
> Currently, `vim.lsp.buf.workspace_symbol()` only searches for workspace symbols from [LSP clients attaching to the current buffer](https://github.com/neovim/neovim/blob/b263c73b083e43761386d46d62524ea104d7abbd/runtime/lua/vim/lsp/buf.lua#L9-L10).
> 
> This means:  The user has to open some buffers to search for workspace symbols.

Is your expectation that Nvim starts language servers for all file types found in the workspace? I assume vscode waits until the "search workspace" action is requested before doing that.

**Comment by mfussenegger** [comment]
I prefer the current behavior but I guess we could add a `clients` option to the `opts` of `workspace_symbol` to give users the control which clients to use. To use all clients they could then use `vim.lsp.buf.workspace_symbol(query, { clients = vim.lsp.get_clients() })`.

But we also to change the implementation to work with multiple clients. Currently it suffers from the 1-handler-call-per-client problem. It would need to merge the results.
Note that if you've setup lsp.start via FileType events or using lspconfig you'd still need to have opened at least one file per filetype to have all clients initialized.

**Comment by BilderLoong** [comment]
> I prefer the current behavior but I guess we could add a `clients` option to the `opts` of `workspace_symbol` to give users the control which clients to use. To use all clients they could then use `vim.lsp.buf.workspace_symbol(query, { clients = vim.lsp.get_clients() })`.
> 
> But we also to change the implementation to work with multiple clients. Currently it suffers from the 1-handler-call-per-client problem. It would need to merge the results. Note that if you've setup lsp.start via FileType events or using lspconfig you'd still need to have opened at least one file per filetype to have all clients initialized.

Does use the `vim.lsp.buf.workspace_symbol(query, { clients = vim.lsp.get_clients() })` means that I can request clients that aren't attaching to the current buffer?

**Comment by BilderLoong** [comment]
> > Currently, `vim.lsp.buf.workspace_symbol()` only searches for workspace symbols from [LSP clients attaching to the current buffer](https://github.com/neovim/neovim/blob/b263c73b083e43761386d46d62524ea104d7abbd/runtime/lua/vim/lsp/buf.lua#L9-L10).
> > This means:  The user has to open some buffers to search for workspace symbols.
> 
> Is your expectation that Nvim starts language servers for all file types found in the workspace? I assume vscode waits until the "search workspace" action is requested before doing that.
> 
> One big advantage of vscode is that it bundles [ripgrep](https://github.com/BurntSushi/ripgrep) which is just wickedly fast. Perhaps we should enhance `vim.fs.find()` to use `rg` if the system has it.

I think which LSP server to start should be left to the user to decide since it may cause some performance issue.

**Comment by BilderLoong** [comment]
The missing functionality that prevents me from implementing this is the restriction that I thought the neovim only supports sending LSP requests to clients already attached to opened buffers. However, after digging a little deeper, I encountered the below code:
 https://github.com/neovim/neovim/blob/be10d65bfafe056025ffffa2c1131712b9a493a5/runtime/lua/vim/lsp.lua#L2140-L2146
 
I realize that It seems that I could start some LSP clients without attaching them to any buffer and then request them one by one like below:

```
for _, client in ipairs(lsp.get_clients()) do 
   local request_success, request_id = client.request(method, params, handler, bufnr)

```

I will try this; if so, I think this issue can be closed.

**Comment by justinmk** [comment]
> I realize that It seems that I could start some LSP clients without attaching them to any buffer and then request them one by one like below:
> 
> ```
> for _, client in ipairs(lsp.get_clients()) do 
>    local request_success, request_id = client.request(method, params, handler, bufnr)
> ```

👍

**Comment by sakalys** [comment]
I don't get it, so how does one do it?
