### ISSUE TITLE
Get number of inline virtual text characters on a line

### ISSUE THREAD

**Issue by tj-moody** [neovim/neovim#24804]
### Problem

As far as I can tell from reading the documentation and issues, there's no reliable way to tell how much text has been offset by inline virtual text, which has made using my own virtual text in combination with inlay_hints or other inline virtual text impossible.

### Expected behavior

It would be fairly easy to solve this problem if it were possible to get the length and position of piece of inline virtual text on a line, but as far as I'm aware such functionality doesn't exist. The closest to this functionality currently implemented is `vim.api.nvim_buf_get_extmarks()`, where I think the `type` field in `opts` would be a logical place to add an `inline` option. The issue would be how to return the length of inline virtual text from the function, which returns a "list of [extmark_id, row, col] tuples in 'traversal order'." Adding a fourth return value to each tuple with the end column of each piece of inline text is a possible avenue to integrate this functionality into the existing api, but it may be a cleaner solution to simply add a new api function which takes a line number and returns [start, end] or [start, length] tuples of inline virtual text.

**Comment by IndianBoy42** [comment]
> there's no reliable way to tell how much text has been offset by inline virtual text

virtcol() should work, although its a bit awkward to control whether you get the screen position at the beginning or ending of the inline virtual text.

**Comment by tj-moody** [comment]
Thanks so much! I was using regex matching so I figured something like this wouldn't work, but it totally does! Thanks so much—closing the issue.
