### ISSUE TITLE
The position of floating windows is not updated when multigrid is used

### ISSUE THREAD

**Issue by fredizzimo** [neovim/neovim#24801]
### Problem

For more details see https://github.com/neovide/neovide/issues/1641. But, in short, the popup menus are not repositioned to fit inside the screen,

By investigating the code, I'm pretty sure that the problem lies here , it does nto seem to do the size calculations when using multigrid https://github.com/neovim/neovim/blob/996dd36c77321ea91758b5996d152a2f37af99dd/src/nvim/window.c#L986-L1018

### Steps to reproduce

1. Start Neovide with `--multigrid`
2. Open any file which has language support protocol enabled with support for hovering documentation.
3. Either make window small enough (for example splitting) or make sure you have big enough hover documentation available.
4. Open hover e.g. hovering a function / method / struct / class etc. declaration.
5. See if the hover window stays withing the window (and within split window).

### Expected behavior

The hover should stay within the window boundaries and not overflow to the right.

### Neovim version (nvim -v)

Neovim Version 0.8.0 ->

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Any

### Terminal name/version

Any

### $TERM environment variable

Any

### Installation

Any

**Comment by zeertzjq** [comment]
I think this is intentional, as some GUIs may be able to render overflowing floating windows just fine.

**Comment by fredizzimo** [comment]
Shouldn't they use `ext_popupmenu`? In Neovide we let Neovim control everything, and don't have it enabled.

**Comment by Kethku** [comment]
I think it is a break of contract for windows exposed to the gui as floating windows to be positioned differently than in the terminal UI. If a gui decides to interpret the positioning differently or implement the extensions then that makes good sense, but my understanding was that multigrid implemented correctly should act identically to the terminal UI.

**Comment by Kethku** [comment]
@zeertzjq any chance you could take another look here or give some more details? I believe this was closed in error

**Comment by zeertzjq** [comment]
@bfredl

**Comment by fredizzimo** [comment]
I changed the title, since the position of popup windows is updated. It's the position of regular floating windows that is not re-positioned to fit the window. So, Neovim is inconsistent in this regard.
