### ISSUE TITLE
SIGABRT on visual block selection + paste before cursor.

### ISSUE THREAD

**Issue by mikeyjk** [neovim/neovim#2481]
Hey all,

I tried searching but couldn't find anything directly related.
I have an issue where when I select a column of text, then paste before cursor, I get a core dump.

My rough key movements are:

    Ctrl+v
    j
    j
    j
    j
    j
    Shift+p
    (SIGABRT)

It only -seems- to happen when I yank a word prior to the paste. But I'm not 100% on that.
I can't re-create the issue on the first line of the document, i.e. if I column select line 1 to 10 on the first character, I don't seem to experience the same issue.

$TERM is set to putty-256color.

strace capturing the SIGABRT:

https://gist.githubusercontent.com/mikeyjk/15ae543de7ece3441bda/raw/strace%20-s300%20-o%20coredump.log%20nvim

Fingers crossed it isn't some bizarre environment variable I'm setting somewhere this time ;).
Happy to provide more information.

![image](https://cloud.githubusercontent.com/assets/4499975/7266297/1b180f6e-e8da-11e4-976f-2424bbe64191.png)

Cheers.

--

Edit: also get 

    *** glibc detected *** nvim: free(): invalid next size (fast): 0x000000000249d6e0 ***3         }
    *** glibc detected *** nvim: malloc(): memory corruption: 0x000000000249d700 ***

On occasion doing the same thing.

--

    NVIM 0.0.0-alpha+201503261736 (compiled Mar 27 2015 08:41:48)
    Commit: c47e0d6210a82f3c2a88e2bc937e77f8b2a72b64
    Build type: Debug
    Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -    Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/mikey/neovim/build/config -I/home/mikey/neovim/src -I/home/mikey/neovim/.deps/usr/include -I/home/mikey/neovim/.deps/usr/include -I/home/mikey/neovim/.deps/usr/include/luajit-2.0 -I/home/mikey/neovim/.deps/usr/include -I/home/mikey/neovim/.deps/usr/include -I/home/mikey/neovim/.deps/usr/include -I/usr/include -I/home/mikey/neovim/build/src/nvim/auto -I/home/mikey/neovim/build/include
    Compiled by root@mikey.pdonlinedev

    Optional features included (+) or not (-): +acl  +iconv
    For differences from Vim, see :help vim-differences

    system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
    2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
    fall-back for $VIM: "/usr/local/share/nvim"

Will try and replicate on home machine / see if pulling the most recent changes resolves.

**Comment by bfredl** [comment]
The code dealing with visual paste was changed recently. Make sure you are on recent master. If you still can reproduce, please try to make a complete minimal exemple to reproduce (starting with `nvim -u NONE`, adding some text, yanking something and then pasting triggering this abort)

**Comment by Pyrohh** [comment]
I'm closing this for now, but please feel free to reopen if you have more information. Most of the time, `strace` isn't nearly as helpful as using Clang's {address, undefined behavior, memory} sanitizer, or just valgrind. See [this link](https://github.com/neovim/neovim/wiki/Development-tips#debugging-program-errors-undefined-behavior-leaks-) for more information.
