### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by icholy** [neovim/neovim#2484]
I'm trying to build master.

```
...
[ 81%] Building C object src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/channel.c.o
[ 81%] Building C object src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/remote_ui.c.o
[ 81%] Building C object src/nvim/CMakeFiles/nvim.dir/tui/tui.c.o
Linking C executable ../../bin/nvim
../../../.deps/usr/lib/libjemalloc.a(jemalloc.o): In function `malloc_init_hard':
/home/icholy/Code/github.com/neovim/neovim/.deps/build/src/jemalloc/src/jemalloc.c:781: undefined reference to `pthread_atfork'
../../../.deps/usr/lib/libtermkey.a(driver-ti.o): In function `load_terminfo':
driver-ti.c:(.text+0x37d): undefined reference to `setupterm'
driver-ti.c:(.text+0x39e): undefined reference to `strfnames'
driver-ti.c:(.text+0x3d4): undefined reference to `strnames'
driver-ti.c:(.text+0x3e6): undefined reference to `tigetstr'
driver-ti.c:(.text+0x4e6): undefined reference to `strfnames'
driver-ti.c:(.text+0x500): undefined reference to `cur_term'
driver-ti.c:(.text+0x51c): undefined reference to `cur_term'
driver-ti.c:(.text+0x554): undefined reference to `cur_term'
driver-ti.c:(.text+0x570): undefined reference to `cur_term'
collect2: error: ld returned 1 exit status
src/nvim/CMakeFiles/nvim.dir/build.make:3178: recipe for target 'bin/nvim' failed
make[3]: *** [bin/nvim] Error 1
make[3]: Leaving directory '/home/icholy/Code/github.com/neovim/neovim/build'
CMakeFiles/Makefile2:206: recipe for target 'src/nvim/CMakeFiles/nvim.dir/all' failed
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make[2]: Leaving directory '/home/icholy/Code/github.com/neovim/neovim/build'
Makefile:113: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/icholy/Code/github.com/neovim/neovim/build'
Makefile:53: recipe for target 'nvim' failed
make: *** [nvim] Error 2
```

**Comment by equalsraf** [comment]
@icholy can you provide more info? What system are building on, and what commands did you run to get that output?

Wild guess: do you have libncurses or libncurses-dev installed in your system?

**Comment by icholy** [comment]
Ubuntu 14.04 64bit minimal install.

I just cloned and ran `make`.

Yes, I do have `libncurses-dev` installed.

**Comment by fwalch** [comment]
ncurses shouldn't be required, unibilium should be enough.. It looks like you ran make in parallel, can you try `make distclean && make -j1`? Maybe that will give a clearer log.

**Comment by icholy** [comment]
It compiled after I uninstalled `libncurses-dev`.

**Comment by equalsraf** [comment]
```
../../../.deps/usr/lib/libtermkey.a(driver-ti.o): In function `load_terminfo':
driver-ti.c:(.text+0x37d): undefined reference to `setupterm'
```
@fwalch Ah I see, seems something went wrong when building and libtermkey failed to detect unibilium. Still parallel make shouldn't be able to cause it, there is a dependency between the targets in the third-party CMake recipe.

**Comment by equalsraf** [comment]
I'm seeing this in a Ubuntu machine too. Something is going on with the bundled libtermkey build, it is trying to use curses instead of unibilium.

**Comment by fwalch** [comment]
Hmm.. libtermkey's Makefile should prefer unibilium over ncurses, so maybe it's not found.

**Comment by equalsraf** [comment]
My running theory is that it fails because pkg-config is not installed

1. libtermkey uses pkg-config to choose unibilium over curses
2. if pkg-config is not installed libtermkey links with curses
3. Neovim links with libtermkey and unibilium but not curses, and since unibilium is not API compatible with curses the linkage fails

e.g. I'm seeing this in my output
```
[ 14%] Performing install step for 'libtermkey'
/bin/sh: 1: pkg-config: not found
/bin/sh: 1: pkg-config: not found
/bin/sh: 1: pkg-config: not found
/bin/sh: 1: pkg-config: not found
```

Incidentally it seems the libtermkey also depends on pkg-config to define the search path for headers/libs i.e. PREFIX only affects the install path.

Installing pkg-config fixed it for me.

**Comment by mqudsi** [comment]
I think this is broken again in `master`. On a clean debian installation without `pkg-config` but with `libncurses5-dev` installed I ended up in the same situation.
