### ISSUE TITLE
Old v0.7.2-3 for Ubuntu in neovim-ppa stable repo

### ISSUE THREAD

**Issue by vladaman** [neovim/neovim#24845]
### Problem

I've observed a lack of recent updates in the Ubuntu PPA repository for Neovim. The most recent update available dates back a year. You can check the repository here: https://launchpad.net/~neovim-ppa.

The current version present in the repository is `0.7.2-3~bpo20.04.1~ppa1`. Unfortunately, if you choose to install Neovim through the Ubuntu repository, you'll end up with an outdated version.

```
$ aptitude show neovim -V
Package: neovim                   
Version: 0.6.1-3
State: not installed
```

### Expected behavior

Latest stable version available be available in ppa repo

**Comment by clason** [comment]
We are not responsible for that repo.
