### ISSUE TITLE
Intro message stuck on gui applications

### ISSUE THREAD

**Issue by casrass** [neovim/neovim#24856]
### Problem

On GUI applications such as neovide, the intro message stays even after keypresses, or when using a plugin like dashboard-nvim.
<img width="876" alt="image" src="https://github.com/neovim/neovim/assets/113079075/f0fb05bb-eb73-4216-89fc-c3538b92503b">
<img width="904" alt="image" src="https://github.com/neovim/neovim/assets/113079075/3d10757f-5c7d-404a-b804-a4b64814d45d">

### Steps to reproduce

Use neovim with a GUI application

### Expected behavior

The message to not show when using a plugin like dashboard, or dissapear when keys are pressed.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

N.A.

### Operating system/version

macOS 14.0

### Terminal name/version

N.A.

### $TERM environment variable

N.A.

### Installation

Homebrew

**Comment by fredizzimo** [comment]
This is a Neovide issue. There's a bug in the temporary workaround we have for showing the intro message. So I believe the issue can be closed here.
