### ISSUE TITLE
Support 'space' listchar 

### ISSUE THREAD

**Issue by srang** [neovim/neovim#2485]
The official vim repo recently added a patch supporting 'space' as a listchhars; 'space' corresponds to white spaces (including non-trailing/leading). This allows for more sublime-like behavior. ftp://ftp.vim.org/pub/vim/patches/7.4/7.4.710

**Comment by glts** [comment]
It's not done yet, one hunk from my original patch hasn't been included yet.

I can offer to port it as soon as it is complete, probably in patch 712 or so.

**Comment by srang** [comment]
Sounds good. Its not high priority, I just wanted to make sure to track it because it is a cool feature. Thanks for the response!
