### ISSUE TITLE
after neovim opens multiple buffers, edit one of the files, and then save it, the clangd cpu is very high

### ISSUE THREAD

**Issue by paopaol** [neovim/neovim#24868]
### Problem

After neovim opens multiple buffers, edit one of the files, and then save it, the clangd cpu is very high. I opened a total of 4 files, one header file, three source files, and all three source files will refer to this header file. When I edited the header file and saved it, the cpu of clangd was very high at 100%, but when I closed the three source files, only kept the current header file, and then edited the current header file and saved it, the cpu of clangd was very low. What’s the matter? thing.

I have tried to use the eglot of emacs for comparison, and eglot does not have this problem.

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
require("lspconfig").clangd.setup({
  cmd = {
    "clangd",
    "-j",
    "1",
    "--background-index",
    "--background-index-priority=background",
    "--pch-storage=memory",
    "--log=verbose",
    "--clang-tidy",
    "--header-insertion=never",
    "--compile-commands-dir=build",
    "--completion-style=detailed",
    "--limit-results=20",
  },
  handlers = lsphandlers,
  root_dir = util.root_pattern("compile_commands.json", "compile_flags.txt", ".git", ".projectile"),
  on_attach = function(client, bufnr)
    vim.api.nvim_buf_set_option(bufnr, "omnifunc", "v:lua.vim.lsp.omnifunc")
    client.server_capabilities.semanticTokensProvider = nil
  end,
  capabilities = require('cmp_nvim_lsp').default_capabilities(),
})
```

### Expected behavior

clangd' cpu not to high

### Neovim version (nvim -v)

NVIM v0.10.0-dev-657+g19fb573a

### Language server name/version

clangd/18.0.0

### Operating system/version

centos/7

**Comment by lewis6991** [comment]
There's not enough evidence here to suggest the issue is with Neovim.
