### ISSUE TITLE
`'endofline'` does not correctly report when a file does not end with `<EOL>`

### ISSUE THREAD

**Issue by lewis6991** [neovim/neovim#24869]
### Problem

`'endofline'` should be unset when a file does not end with `<EOL>`, however Nvim incorrectly keeps it set.

### Steps to reproduce

Add `.editorconfig`:
```
[*]
insert_final_newline     = true
```

```bash
echo -n x >|bar
nvim --clean -u NONE bar
:set endofline?
```

### Expected behavior

Should report `noendofline`

### Neovim version (nvim -v)

NVIM v0.10.0-dev-948+g0b0d9127

### Vim (not Nvim) behaves the same?

no, vim 9.0.1544

### Operating system/version

macOS 13.5.1

### Terminal name/version

wezterm

### $TERM environment variable

NA

### Installation

Source

**Comment by lewis6991** [comment]
Related: https://github.com/vim/vim/issues/6119

**Comment by zeertzjq** [comment]
You didn't edit the `bar` file.

**Comment by zeertzjq** [comment]
Cannot reproduce on Linux.

**Comment by lewis6991** [comment]
Caused by: `[ab9a2c49253413dbbb31756a3eeddb354a663035] feat(editorconfig): add builtin EditorConfig support`

I would have assumed `--clean -u NONE` would skip editorconfig.
