### ISSUE TITLE
the documentation on option mousescroll is not clear enough

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#24870]
### Problem

The document on option `mousescroll` did not mention that you need to `set nowrap` for it to work. Only in `:h scroll-mouse-wheel`, there is a mention of `nowrap`, but `mousescroll` option is not mentioned there. I do not think any normal user can piece this two info together to figure out how to make `mousescroll` work.

### Steps to reproduce

1. `nvim --clean some-file.txt`
2. try to scroll left and right with your mouse, nothing happens
3. run `:set nowrap`
4. scroll left and right again with your mouse, now horizontal scroll works

### Expected behavior

The doc `mousescroll` can be improved to include the `nowrap` setup.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

macOS 13.3.1

### Terminal name/version

wezterm latest release

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
How is this related to 'mousescroll'?

**Comment by jdhao** [comment]
I just think the doc about mousescroll should include a mention of nowrap setup. Otherwise, the option does not work in itself, which is confusing.
