### ISSUE TITLE
Terminal title/buffer name

### ISSUE THREAD

**Issue by akarl818** [neovim/neovim#2488]
I would like to be able to set the the buffer name for the terminal buffer. When I have more than one running it makes it unconvinent.

That is unless I start the command directly like so `:terminal mycommand`, which is not always what I want to do.

**Comment by justinmk** [comment]
The buffer name is a unique identifier, potentially useful to scripts/plugins. I don't think introducing ambiguity here will be worth the trouble.

**Comment by splinterofchaos** [comment]
As a part of #2424, I'm adding a `'name'` option to `termopen()` so that you can specify what name you want. Though the name still has the `term://{pid}/{dir}/{name}` structure. 

> The buffer name is a unique identifier, potentially useful to scripts/plugins.

That's why.

**Comment by akarl818** [comment]
@splinterofchaos Yes, that's good. That will make it easier to switch to the terminal I wan't from the buffer list. Thanks!

**Comment by Joushou** [comment]
Wouldn't setting the filename with ":file" do the job? I name my terminal buffers "term-1", "term-2", "jenkins", etc., and that seems to me to essentially be what you are looking for.

**Comment by akarl818** [comment]
@Joushou Yes, that's exactly what I want! Thank you!

**Comment by artem-nefedov** [comment]
> Wouldn't setting the filename with ":file" do the job? I name my terminal buffers "term-1", "term-2", "jenkins", etc., and that seems to me to essentially be what you are looking for.

The problem with this approach is that it breaks `:mksession`. If you change terminal window name with `:file` and save the session, upon restore it will no longer create terminal window, but a regular file buffer instead.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/help-managing-terminal-buffers/141/1

**Comment by Sangdol** [comment]
This doesn't change the buffer name but I've created a plugin that shows the directory name of terminal buffers in the tabline: https://github.com/Sangdol/mintabline.vim
