### ISSUE TITLE
TS: Number sign conversion error in node range

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#24884]
### Problem

When I set up a `LanguageTree` callback (via `register_cbs`) for the `on_changedtree` event sometimes I get a weird six-element range that contains the number `4294967295` in the last three entries. 4294967295 is the unsigned equivalent of -1, so I my guess is that at some point in the code a conversion from unsigned to signed or vice-versa got dropped.

### Steps to reproduce

1) Create a Lua test file containing something like `print 'Hello world'`, contents should not really matter. Let's call it `derp.lua`
2) Create the following minimal Lua example script, let's call it `example.lua`
    ```lua
    vim.cmd 'setlocal ft=lua'
    local parser = vim.treesitter.get_parser(0)
    parser:register_cbs {
        on_changedtree = function(changes, tree)
            print(vim.inspect(changes))
        end
    }
    ```
3) Start Neovim: `nvim -u NONE derp.lua`
4) Source the Lua script: `:luafile example.lua`
5) Edit the current buffer to trigger the autocommand: `:edit`

### Expected behavior

The ranges should contain some meaningful numbers. Instead they are shown as `{ { 0, 0, 0, 4294967295, 4294967295, 4294967295 } }`.

### Neovim version (nvim -v)

v0.10.0-dev-944+gcbadb39d1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Void Linux 64bit

### Terminal name/version

Alacritty 0.12.2

### $TERM environment variable

alacritty

### Installation

appimage

**Comment by lewis6991** [comment]
This is what TS reports for the root tree.

**Comment by HiPhish** [comment]
Is it a Tree-sitter bug then? Because my buffer has online one line, not millions of them.

**Comment by lewis6991** [comment]
This is what treesitter does. I don't know if I would call it a bug. It's just a special region that means the entire source, whether that's 1 line or a million.

**Comment by HiPhish** [comment]
OK, I guess that's the way it is then.
