### ISSUE TITLE
Terminal buffers should have a filetype

### ISSUE THREAD

**Issue by Arrowbox** [neovim/neovim#2489]
The quickfix buffer has a filetype of `qf` that allows other autocmds, like `WinLeave` or `WinEnter`, to run.  It would be helpful for the terminal to have a filetype as well. I have added `autocmd TermOpen * setlocal ft=terminal` to my vimrc, but I think it would be reasonable to add a default filetype to the terminal buffer.

**Comment by Arrowbox** [comment]
My mistake, autocmds go off of filename which can use `term:` as the pattern, however, I still think attaching a filetype to the buffer makes sense.

**Comment by justinmk** [comment]
It sets `buftype=terminal`

**Comment by Arrowbox** [comment]
Great! I missed that, sorry.
