### ISSUE TITLE
Swap file not removed when buffer is closed

### ISSUE THREAD

**Issue by terminalmage** [neovim/neovim#24918]
### Problem

When using neovim with default config values for `backup`,`writebackup`, `swapfile`, `backupdir`, and `directory`, and with multiple buffers (either via launching nvim using `-p` or using `:tabedit` to open a new tab), closing a buffer does not delete its swapfile. This causes warnings when trying to open that same file in a different neovim process.

### Steps to reproduce

1. Edit multiple files in tabs
2. Write and quit one of the buffers, closing its tab
3. Try to open the file you just saved and closed in another neovim process.

### Expected behavior

The swap file should be removed on buffer close, allowing you to edit that file again in another nvim instance. Instead, the swap file is not removed until you exit nvim entirely.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

no, vim 9.0.1736

### Operating system/version

Arch Linux

### Terminal name/version

Termite

### $TERM environment variable

xterm-256color

### Installation

Arch Linux "extra" repository

**Comment by zeertzjq** [comment]
`:set nohidden`

**Comment by terminalmage** [comment]
Well that's weird and dumb, but I appreciate the help.
