### ISSUE TITLE
bufnr field of diagnostic tables get ignored by vim.diagnostic.set

### ISSUE THREAD

**Issue by Lattay** [neovim/neovim#24916]
### Problem

Hi,
I am uncertain if I am reporting a bug or something that simply lacks documentation and defies my personal intuition.

In its current state, [vim/diagnostic.lua](https://github.com/neovim/neovim/blob/7c4d317a660c9d241a817faddc28ec6f36e753ad/runtime/lua/vim/diagnostic.lua) ignores the presence of a bufnr field in diagnostics, assuming that the bufnr passed to functions like `vim.diagnostic.show` and `vim.diagnostic.set` is the one to use.

It is not clear to me wether it is intended or not:

- the existence of this field suggest that it should be used, but I don't see where
- `vim.diagnostic.fromqflist` set this field as expected, thus I expected to be able to write this:
```lua
vim.diagnostic.set(ns, 0, vim.diagnostic.fromqflist(bt.getqflist()))
```
- bufnr is ignored in a few places in favor of the parameter:
https://github.com/neovim/neovim/blob/7c4d317a660c9d241a817faddc28ec6f36e753ad/runtime/lua/vim/diagnostic.lua#L281 -> I would have expected something like `diagnostic.bufnr = diagnostic.bufnr or bufnr`
https://github.com/neovim/neovim/blob/7c4d317a660c9d241a817faddc28ec6f36e753ad/runtime/lua/vim/diagnostic.lua#L956 -> again, I suppose `diagnostic.bufnr or bufnr` would behave more like I expect

Again, not sure if this was always intended, and I just misunderstood the API.
In which case, should I have my own filtering logic between `fromqflist` and `diagnostic.set`?

### Steps to reproduce

nvim -o buf1 buf2
:lua vim.diagnostic.set(vim.api.nvim_create_namespace("test"), 0, {{ bufnr = 2, message = "here", lnum = 0, col=1 }})

### Expected behavior

The diagnostic should be marked in "buf2".

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Archlinux

### Terminal name/version

Kitty 0.29.2

### $TERM environment variable

screen-256color

### Installation

Archlinux extra/neovim

**Comment by gpanders** [comment]
This is correct behavior. The `bufnr` field should not be set when passed to `vim.diagnostic.set`. That is what the `bufnr` argument of `set()` is for.

The `bufnr` field is populated when diagnostics are retrieved with e.g. `vim.diagnostic.get`. It should be thought of as a read-only field.

If you have any suggestions to make the documentation more clear, a PR is welcome!
