### ISSUE TITLE
nvim_buf_get_offset misreports the first line offset on one-line buffers that started empty

### ISSUE THREAD

**Issue by pqwy** [neovim/neovim#24930]
### Problem

Starting from a new buffer or a buffer loaded from an empty file, `nvim_buf_get_offset` keeps reporting the offset of the first line (index 0) as -1. This stops after inserting a new line.

### Steps to reproduce

- Create a new buffer (`:new`)
- `vim.api.nvim_buf_get_offset(0, 0)` returns `-1`.
- Start adding characters in the first line, for instance input `Axxx<Esc>`. Insert mode can be entered and exited any number of times.
- After each change, the offset of the first line is still `-1`. This can be verified using `:=` in normal mode, or in a callback as characters are inserted.
- Input `<Enter>`. From this point on, `vim.api.nvim_buf_get_offset(0, 0)` returns `0`.
- The same happens when using `:e` on an empty file.
- Cannot reproduce on non-empty files, including files which do not contain `\n`.

### Expected behavior

`vim.api.nvim_buf_get_offset(0, 0)` should always return `0`; or at least not change its mind.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Linux

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

official Arch extra repository

**Comment by bfredl** [comment]
possible fix:

```diff
diff --git a/src/nvim/memline.c b/src/nvim/memline.c
index 5839061aac..142c6ee4b2 100644
--- a/src/nvim/memline.c
+++ b/src/nvim/memline.c
@@ -3934,7 +3934,7 @@ long ml_find_line_or_offset(buf_T *buf, linenr_T lnum, long *offp, bool no_ff)
   if (buf->b_ml.ml_usedchunks == -1
       || buf->b_ml.ml_chunksize == NULL
       || lnum < 0) {
-    return -1;
+    return (lnum == 1) ? 0 : -1;
   }
 
   if (offp == NULL) {
```

Behavior of `line2byte(1)` is also affected (also in recent vim). but in that case only by completely unchanged buffer, i e inserting on line 1 is enough to return the valid value.

**Comment by pqwy** [comment]
This seems to do it, thanks! After applying to head (97cfee39ee7bf333352975f917e660965609e8cc), my repros no longer work.

(I had a hunch that *someone* will have to special-case line 0 :) )
