### ISSUE TITLE
Window cannot be redrawn

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#24946]
### Problem

I noticed that `:Telescope builtin` does not redraw the result list. It turns out that it occurs since 1bdcb9aaf11e914d4c7af14e8e5be4ed3c5798ae

It looks like a regression for Neovim. Please change the title to something more accurate. 

### Steps to reproduce

- Create `test.lua` with
```lua
local configDir = vim.fn.expand('<sfile>:p:h')

vim.env['XDG_CONFIG_HOME'] = configDir
vim.env['XDG_DATA_HOME'] = configDir .. '/.xdg/data'
vim.env['XDG_STATE_HOME'] = configDir .. '/.xdg/state'
vim.env['XDG_CACHE_HOME'] = configDir .. '/.xdg/cache'
local stdPathConfig = vim.fn.stdpath('config')

vim.opt.runtimepath:prepend(stdPathConfig)
vim.opt.packpath:prepend(stdPathConfig)
local plugins_path = vim.fn.fnamemodify('plugins/', ':p')

for name, url in pairs {
  ['plenary.nvim'] = 'https://github.com/nvim-lua/plenary.nvim',
  ['telescope.nvim'] = 'https://github.com/nvim-telescope/telescope.nvim',
} do
  local install_path = plugins_path .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('telescope').setup { }
```
- run `path/to/nvim --clean -u test.lua`
- run `:Telescope builtin` 
- type some characters, e.g. `lsp` - for me the result list becomes empty
- try to type any additional characters 
- press `<Up>` - for me the result list is redrawn. 

### Expected behavior

Redraw the results list.

### Neovim version (nvim -v)

1bdcb9aaf11e914d4c7af14e8e5be4ed3c5798ae

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Debian Sid

### Terminal name/version

kitty 0.26.5-5 + tmux 3.3a-4

### $TERM environment variable

tmux-256color

### Installation

build from source

**Comment by przepompownia** [comment]
Cc: @bfredl

**Comment by vxpm** [comment]
for me, completion also broke - the selection goes out of the bounds of the window. i can see the options scroll, it's just that the currently selected one is not visible. seems to be the same for telescope.

**Comment by AlexKurisu** [comment]
`NVIM v0.10.0-dev-1002+gee56daebb6` - can reproduce the issue with Telescope, can't reproduce the issue with `nvim-cmp`

**Comment by przepompownia** [comment]
From the Telescope user's perspective https://github.com/nvim-telescope/telescope.nvim/pull/2679 seems to fix missing redraw on the plugin side. 

Can anyone explain me why https://github.com/neovim/neovim/commit/1bdcb9aaf11e914d4c7af14e8e5be4ed3c5798ae required to make some changes in Telescope?

**Comment by lewis6991** [comment]
No one is 100% sure, but it was likely telescope relying on undefined behaviour.
