### ISSUE TITLE
Commit "bec13cf" change the behavior of `line2byte`

### ISSUE THREAD

**Issue by TwIStOy** [neovim/neovim#24951]
### Problem

After commit `bec13cf`, `line2byte` never returns `-1` even the buffer is empty. That breaks [alpha-nvim](https://github.com/goolord/alpha-nvim).

### Steps to reproduce

```lua
for name, url in pairs{
   ["alpha-nvim"] = "https://github.com/goolord/alpha-nvim"
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require'alpha'.setup(require'alpha.themes.startify'.config)
```

Steps:

1. `nvim --clean -u my_issue.lua`

### Expected behavior

`Alpha` should be shown.

### Neovim version (nvim -v)

v0.10.0-dev-993+gbec13cfca

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by bfredl** [comment]
> After commit bec13cf, line2byte never returns -1 even the buffer is empty. 

This was an intentional change. `line2byte(1)` never consistently returned -1 when the buffer is empty, only when it is unloaded. Quoting the documentation

> When {lnum} is invalid -1 is returned

"1" is a valid line buffer even in an completely empty buffer, as long as it is loaded.

**Comment by MariaSolOs** [comment]
I think we can close this. I fixed the issue with `alpha` in https://github.com/goolord/alpha-nvim/pull/239.

**Comment by bfredl** [comment]
Good to know, thanks!
