### ISSUE TITLE
Has `nvim-qt` purposely been removed from Neovim nightly builds?

### ISSUE THREAD

**Issue by gwojan** [neovim/neovim#24964]
### Problem

I installed the most recent nightly build of Neovim on Windows and the `nvim-qt` executable and `dll`s are completely missing. This appears to have started somewhere around 06/01/2023.

### Steps to reproduce

View contents of `.zip` file and you will see no evidence of `nvim-qt`.

### Expected behavior

Expect `nvim-qt.exe` to launch.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1002+gee56daebb

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Microsoft Windows 11 Enterprise, Version 22H2 (OS Build 22621.2134)

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

Expanded .zip file

**Comment by clason** [comment]
Yes.

**Comment by gwojan** [comment]
> Yes. #23668

Thanks. I really did look for other issues -- open issues. Le sigh...
