### ISSUE TITLE
NVIM_APPNAME disallows paths

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#24966]
### Discussed in https://github.com/neovim/neovim/discussions/24954

<div type='discussions-op-text'>

<sup>Originally posted by **doctorfree** August 31, 2023</sup>
Neovim 0.9 introduced `NVIM_APPNAME` as a way to specify the location of the configuration folder, rather than always using `~/.config/nvim`. I maintain a project that installs, initializes, and manages multiple Neovim configurations using this feature.

In version 0.9 it is possible to specify a path like `neovim/my-cool-config` as the `NVIM_APPNAME` environment variable value. This is especially nice if you have a lot of Neovim configurations to manage, put them all in a subdirectory of `~/.config`.

However, nightly Neovim has removed this capability. With nightly if you use a path for `NVIM_APPNAME` then you get an error message and nvim exits. The issue where this was decided indicates that `NVIM_APPNAME` was never intended to support paths, simply and strictly the name of a subdirectory in `~/.config`.

I do not know what the history or reasoning or intent was with implementation of this feature. But it was working pretty nicely and now it's not. What reasons do people have for disallowing support of a path in `NVIM_APPNAME`?</div>

**Comment by justinmk** [comment]
Explained in https://github.com/neovim/neovim/issues/23056#issuecomment-1505996200

The described use-case  is essentially trying to override all the `XDG_XX` vars without actually overriding them. Supporting this would mean reworking our stdpath logic in various places, plus documenting that "XDG_XX vars are ignored if NVIM_APPNAME is set to..."

**Comment by RoryNesbitt** [comment]
Being able to use `../new/path` (which currently does work) let's you overwrite XDG directories without actually overcrowding them. But the desired use case with this, at least for me, is for better organisation when using multiple configs.

Personally I would suggest adding the fix from the discussion (if it really is that simple) and noting in the docs that while paths are possible again it is not a supported option. And maybe also specifically block using `..`
