### ISSUE TITLE
`laststatus=0` puts default statusline into cmdline, ignoring `statusline` formatting

### ISSUE THREAD

**Issue by ivanjermakov** [neovim/neovim#24970]
### Problem

UI when setting `statusline=foo`, as expected:

![image](https://github.com/neovim/neovim/assets/26609879/dd7a0f10-0bd3-4a68-b6c8-396f16bb3d36)

UI when after that setting `laststatus=0`:

![image](https://github.com/neovim/neovim/assets/26609879/67c4c0fa-5edb-41c6-844a-54a19e80930d)

Default statusline appears in the cmdline (`0,0-1 All`)

### Steps to reproduce

nvim --clean
:set statusline=foo
:set laststatus=0

### Expected behavior

Cmdline should not contain statusline, but if so, should respect `statusline` setting.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1011+g7bf0963d48

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Arch Linux 6.4.9-arch1-1

### Terminal name/version

alacritty 0.12.2 (9d9982df)

### $TERM environment variable

alacritty

### Installation

neovim-git AUR

**Comment by zeertzjq** [comment]
`:h 'ruler'`
