### ISSUE TITLE
[bug] [terminal] Autocomplete segmentation fault

### ISSUE THREAD

**Issue by akarl818** [neovim/neovim#2498]
This is what's happening:

    :terminal ./man<tab>

    :terminal ./man...[1]    78639 segmentation fault  nvim

I get a segmentation fault when trying to press tab for autocomplete.

It works well with normal commands but not with files.

My `shell` is set to `/bin/zsh`.

**Comment by justinmk** [comment]
Please report `:version`. May have been related to https://github.com/neovim/neovim/pull/2491

**Comment by justinmk** [comment]
can't reproduce after building VIM 0.0.0-alpha+201504231827 (compiled Apr 24 2015 14:23:16)
Commit: d350d12a00518aa0d9e3a1d49c6815c3398d882f

**Comment by Pyrohh** [comment]
@akarl818 Feel free to reopen this if you do manage to reproduce it, but please see https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#reporting-problems before doing so (we try to keep that list not too long).

**Comment by akarl818** [comment]
Building the latest version worked, the one I hade was from the 21:st, I will try with the latest the next time :)
