### ISSUE TITLE
`vim.system` command stopped with `:kill()` becomes a zombie

### ISSUE THREAD

**Issue by nojnhuh** [neovim/neovim#25000]
### Problem

Running a command with `vim.system()` and then using the object's `:kill()` method with `SIGINT` leaves the process as a zombie, per `ps`. Calling the equivalent `vim.uv.kill()` instead cleans up the process entirely the way I'd expect.

I have a CI run on my fork showing similar repro steps as below failing on all platforms, e.g. https://github.com/nojnhuh/neovim/actions/runs/6062321135/job/16448423425#step:12:3931 

The smallest change I found I can make to fix this particular error is to omit `state.handle` here to skip closing that handle: https://github.com/neovim/neovim/blob/4ea4d72af800c40511afd006ea202d008e653c3f/runtime/lua/vim/_system.lua#L33

I imagine this and the `vim.uv.kill` workaround leak the libuv handle though which is also not ideal.

cc @lewis6991 

### Steps to reproduce

```lua
nvim -l - <<EOF
local cmd = vim.system({ 'cat', '-' }, { stdin = true }) -- run forever

cmd:kill('sigint') -- fails this test
-- vim.uv.kill(cmd.pid, 'sigint') -- using this instead works

-- wait for the process not to exist
local done, err = vim.wait(5000, function()
  return vim.uv.kill(cmd.pid, 0) ~= 0
end, 100)

print(vim.fn.system('ps p ' .. tostring(cmd.pid)))

assert(done, err == -1 and 'process still exists' or 'something else went wrong')
print('ok: process is gone')
EOF
```

```
    PID TTY      STAT   TIME COMMAND
 176064 pts/3    Z+     0:00 [cat] <defunct>
E5113: Error while calling lua chunk: [string "local cmd = vim.system({ 'cat', '-' }, { stdi..."]:13: process still exists
stack traceback:
        [C]: in function 'assert'
        [string "local cmd = vim.system({ 'cat', '-' }, { stdi..."]:13: in main chunk
```

whereas the output when `vim.uv.kill()` is used instead of `:kill()`:
```
    PID TTY      STAT   TIME COMMAND
ok: process is gone
```

### Expected behavior

The process should no longer exist within a reasonable period of time after `:kill()` is invoked, where `vim.uv.kill(pid, 0)` should not return 0, like similar checks in libuv's tests: https://github.com/libuv/libuv/blob/0d78f3c758fdc41019093353a7ff4fed83005ac9/test/test-spawn.c#L105-L111.

### Neovim version (nvim -v)

v0.10.0-dev-1018+g4ea4d72af

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux, kernel 6.4.12-arch1-1

### Terminal name/version

kitty 0.29.2 + tmux 3.3_a

### $TERM environment variable

tmux-256color

### Installation

Build from source

**Comment by lewis6991** [comment]
Thanks for the great report. It made fixing this issue really easy since the repro steps included the solution.

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/issues/24567#issuecomment-1666445471
