### ISSUE TITLE
Neovim freezes when I use the substitute command

### ISSUE THREAD

**Issue by kpovel** [neovim/neovim#25009]
### Problem

When I attempt to substitute a single quote, nvim freezes and doesn't respond to any key presses. 
It also causes a memory leak that grows indefinitely.

### Steps to reproduce

V
24j (if less, this bug doesn't appear)
:'<,'>s/'/ (it happens)

### Expected behavior

Substitution

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no, vim 9.0.1544

### Operating system/version

macOS 13.5.1

### Terminal name/version

ITerm 3.4.20, Terminal (standard) 2.13 (447)

### $TERM environment variable

screen-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
What is the content of the buffer?

**Comment by kpovel** [comment]
It is just React code

https://gist.github.com/kpovel/330e36e61a13096f5124cf8ee8d37c9d

**Comment by kpovel** [comment]
I've also noticed that, to reproduce this bug, you need to select rows that don't contain a single quote.

https://github.com/neovim/neovim/assets/87817350/3ba9de4c-8f75-4273-8c77-651ede2d58f6

**Comment by zeertzjq** [comment]
Cannot reproduce. This is likely caused by a plugin.

**Comment by adrian5** [comment]
Can confirm, but I'm also using plenty plugins. `nvim -u NONE reports.tsx` doesn't hang.

> 24j (if less, this bug doesn't appear)

I think this is simply because you're reaching a line containing `'`, no?

**Comment by kpovel** [comment]
> I think this is simply because you're reaching a line containing `'`, no?

Almost, when each of the selected lines contains a single quote, the issue doesn't occur. However, when a few lines don't contain one, it does. 

Also, when I deleted all of my plugins, the issue is gone

**Comment by kpovel** [comment]
@adrian5 , I found out why this happened. It is somehow related to treesitter. Maybe because I use Packer, maybe for something else ...

**Comment by adrian5** [comment]
@kpovel Good to know! I use lazy.nvim.
