### ISSUE TITLE
The `'backupdir'` option doesn't support full paths.

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#2501]
The `'directory'` and `'undodir'` options support saving backup files based on the files full path. This functionality is missing from `'backupdir'` and this functionality has been sitting in vim's todo list for over 4 years:

> 7   The 'directory' option supports changing path separators to "%" to make
>    file names unique, also support this for 'backupdir'. (Mikolaj Machowski)
>    Patch by Christian Brabandt, 2010 Oct 21.

Here's the forgotten [patch](https://groups.google.com/forum/#!searchin/vim_dev/backupdir/vim_dev/ZJdEbARbB4o/47c_4i6sul4J).

**Comment by robertmeta** [comment]
Glad to see this already sitting here with a patch!  I was coming to request this unification of expectations.

**Comment by Shougo** [comment]
Unfortunatelly, @ghost is removed account.  This PR should be closed.

**Comment by splinterofchaos** [comment]
If you're refering to ["Implement saving full paths for 'backupdir'. #2501"](https://github.com/neovim/neovim/commit/bd551cb6f523e9d82e3641cb85ee501167cc4dc7), it is not on the master branch, and I don't see a PR attached to the commit.

**Comment by Shougo** [comment]
OH....

**Comment by mkoskar** [comment]
Since I've come across this, I'll offer kind of workaround I'm using successfully for quiet a long time:

    autocmd BufWritePre * let &backupext = substitute(expand('%:p:h'), '/', '%', 'g')

**Comment by gobwas** [comment]
Sorry for pinging, but I wonder, is this feature implemented already?

**Comment by KillTheMule** [comment]
Maybe https://github.com/neovim/neovim/pull/11269?

**Comment by gobwas** [comment]
@KillTheMule thanks, yeah, I found that later. Just got confused by the “Open” label.
