### ISSUE TITLE
Missing characters in Neovide with the 0.9 and main branches

### ISSUE THREAD

**Issue by fredizzimo** [neovim/neovim#25011]
### Problem

https://github.com/neovim/neovim/pull/24982 caused a regression, where some characters and highlights are missing. 

The most obvious case is when using the `indent-blankline.nvim` plugin, but I have seen broken up highlights using telescope, and missing characters in the built in terminal for example.

For example several characters at the start of the indentation are missing here
![image](https://github.com/neovim/neovim/assets/9946255/a686450e-e680-4548-9b9d-6886159fc5ec)
 And here's a broken telescope highlight
![image](https://github.com/neovim/neovim/assets/9946255/1b078f58-1925-41d0-bbe6-0e746ddc1aa5)

This happens both with `--multigrid` and without.

### Steps to reproduce

1. Create a file called `missing_chars.lua` with the following contents
```lua
for name, url in pairs{
   blankline = 'https://github.com/lukas-reineke/indent-blankline.nvim'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require 'indent_blankline'.setup({})

vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
```
2. run `neovide --neovim-bin path/to/nvim -- --clean -u missing_chars.lua missing_chars.lua`
3. Observe that it looks like the screenshot above

### Expected behavior

All characters and highlights should be rendered correctly

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1029+gaf899971b

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

Neovide 0.11.1

### $TERM environment variable

N/A

### Installation

build from repo

**Comment by zeertzjq** [comment]
cc @Kethku

What is this branch in Neovide intended to do?
```rust
        if text.is_empty() {
            if let Some(cell) = self.grid.get_cell_mut(*column_pos, row_index) {
                *cell = (text, style.clone());
            }
            *column_pos += 1;
```
https://github.com/neovide/neovide/blob/598f7779a404b729de33d748780e5be0de0197d5/src/editor/window.rs#L137C9-L142C10

It seems to come from <https://github.com/neovide/neovide/commit/f8bc1a2ce44e5e6bda41864bb9a714706a992e0c> which doesn't contain much information.

**Comment by fredizzimo** [comment]
I’m not 100% sure, but I think it deals with double width glyphs. I have a very faint memory that I sometime looked into it, and that neovim sends the rest of the occupied cells as empty, but I could be totally wrong.

**Comment by zeertzjq** [comment]
Oh, right

**Comment by fredizzimo** [comment]
Maybe. I can’t try it myself anymore today. But I can check it tomorrow.

**Comment by fredizzimo** [comment]
@zeertzjq, that seems to fix the issue.

But I wonder what does a cell with `text: " "`  and `repeat: 0` mean? That's what is received, at least in the cases I have seen.

**Comment by zeertzjq** [comment]
In this case it means that the whole call is actual text being drawn, not clearing a part of the line.

**Comment by fredizzimo** [comment]
Is that documented anywhere?

First there's a repeat of spaces to the end of the line according to the documentation:
https://github.com/neovim/neovim/blob/069fad6e2df25e6b079879670cf6c68ae7ddb012/runtime/doc/ui.txt#L377-L380

But after that there's this new repeat with a count of zero, and I don't see any function of it and nothing mentioned in the documentation.


And can we just ignore the repeat of zero times?
In practice changing `if text.is_empty()` to `if text.is_empty() && cell.repeat.is_none()` is the same as ignoring zero count repeats completely.  Since that turns a space into an empty string, which is then not dealt with any further, there's nothing to loop in the other branch.

I can see that technically this is a bug in Neovide, since it threated a repeat of zero as something else. But if it's always a NOP, I don't think it should be sent.

**Comment by zeertzjq** [comment]
It's not an NOP when the previous chunk is all spaces, as it indicates that the previous chunk is in fact actual text, not clearing a part of the line.

**Comment by fredizzimo** [comment]
Ah, I don't think it matters much for us, since spaces and empty cells are rendered the same. Except maybe in the very special case where the style is inverted.

I will fix this in Neovide then and push out a release as quickly as possible. It looks like Neovide 0.9.2 is close to getting finalized, and we want our fix out before that.

I do think that this needs to be documented somehow, because in order to process this correctly, you can't just iterate through the events. You also have to check if it the `grid_line_event` is the last one for the row or not. Or alternatively mutate the previous cells, when you receive a repeat with a zero count.

Maybe I boolean similar to `wrap`, signalling that it's an end of line clear, would be better, and much easier to process?

**Comment by zeertzjq** [comment]
> Maybe I boolean similar to `wrap`, signalling that it's an end of line clear, would be better, and much easier to process?

This can be an extra (the fourth) field in a chunk, but then there will still be GUIs that need changes to handle it. @bfredl thoughts?

**Comment by bfredl** [comment]
Not sure we need to make it more complicated than it is. Most UI:s should be fine to completely ignore this information. It's really only to make the built-in text selection of terminal emulators work 99% of the time one would expect it to rather than 90%. All a third party client might need to adjust is to safely ignore an empty chunk (which is only for the edge case of a screen line with trailing buffer spaces) . 

Even if neovide would make use of it, all it needs to check while processing a chunk is whether there is more chunks after in the same line. The actual contents of a chunk never changes the meaning of an earlier chunk.

**Comment by fredizzimo** [comment]
If we can safely ignore it for all purposes, then it's ok to me as long as it's documented and marked as a breaking change.

Checking for more chunks in the same line, would mean some small architectural changes for us to not modify our internal grid as soon as the message is received, but instead buffer it all up until a flush is received. NOTE, that our internal grid in this case is not the same as the one we render, that one is only updated on flush, so that's why we are able to update it immediately.

Modifying the previous chunk, basically marking the spaces of the previous chunk as empty, would be a slightly easier alternative, since the flow remains the same.

**Comment by bfredl** [comment]
yes, it is going to be clearly noted in the 0.9.2 release notes.
