### ISSUE TITLE
Make v_P work with the dot operator

### ISSUE THREAD

**Issue by seantwie03** [neovim/neovim#25018]
### Problem

The dot operator behaves unexpectedly after `v_P` and `v_p`.

Here is a demonstration of what I mean:

Given a file with these contents:  **file.txt**
```
first
second
third
```

Open the file in Neovim:

```sh
nvim --clean file.txt
```

Perform these actions:

- With cursor on 'first' type `yiw`
- Move cursor to 'second' type `viwP` -> 'second' is replaced with 'first'
- Move cursor to 'third' type `.` -> 'd' is deleted from 'third'

*Note*: The dot operator on 'third' behaves the same whether you use `v_p` or `v_P`.

### Expected behavior

I think this behavior is a bit strange. My expectation when performing these actions is that the dot operator would repeat the last action `viwP` instead of deleting the last character off the current word.

I am suggesting this as a feature and not a bug because the same behavior happens in Vim.

My current workaround is to repeatedly type `viwP` rather than use the dot operator.

**Comment by justinmk** [comment]
> My expectation when performing these actions is that the dot operator would repeat the last action `viwP` instead of

Dot-repeat of visual mode is quite bad currently. Instead it should be changed work like you imply: it should repeat the visual-mode steps, not a fixed range box. This is tracked in https://github.com/neovim/neovim/issues/16296
