### ISSUE TITLE
`background` can not be set using lua during startup

### ISSUE THREAD

**Issue by TheBlob42** [neovim/neovim#25025]
### Problem

Setting the `background` option to "light" during the startup process using lua (`vim.opt` or `vim.o`) does not work.

However using vimscript for the same configuration works fine: `set background=light`.

Other options I tested (for example `number`) work fine,  but I haven't tested them all, so there might be more affected.

After startup setting the `background` option using lua works just fine.

### Steps to reproduce

`nvim --clean --cmd 'lua vim.opt.background="light"'`
OR
`nvim --clean --cmd 'lua vim.o.background="light"'`

Afterwards check the `background` option via `:set background`

### Expected behavior

The `background` option should be set to "light"

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1031+gc431d820e

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Ubuntu 20.04.6 LTS

### Terminal name/version

GNOME Terminal 3.36.2

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
This should fix it:
```diff
diff --git a/src/nvim/option.c b/src/nvim/option.c
index cc3a9c181..ae4e7c1fd 100644
--- a/src/nvim/option.c
+++ b/src/nvim/option.c
@@ -3772,7 +3772,7 @@ static const char *set_option(int opt_idx, void *varp, OptVal *v, int opt_flags,
                                errbuf, errbuflen);
   }
 
-  if (errmsg != NULL) {
+  if (errmsg == NULL) {
     did_set_option(opt_idx, opt_flags, true, value_checked);
   }
 
```
