### ISSUE TITLE
Highlights not applied to group names in help file

### ISSUE THREAD

**Issue by Subjective** [neovim/neovim#25036]
### Problem

I noticed that regular vim (on the left) applies highlights to hl group names in the syntax help docs, while neovim does not. At first I thought that this might be due to a difference between their defaults, but this doesn't appear to be the case. Sorry if this isn't a bug per se, just curious as to why there would be a discrepancy between the two given that I wasn't able to find any prior discussion/justification for this.

<img width="1785" alt="image" src="https://github.com/neovim/neovim/assets/56745535/ec600301-5cfb-4c06-979c-7fba955efe6d">

### Steps to reproduce

```
nvim -u NONE
:h EndOfBuffer
```

### Expected behavior

For highlights to be applied to the corresponding group name in the help file like in vim.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1031+gc431d820e

### Vim (not Nvim) behaves the same?

no, 9.0

### Operating system/version

macOS 13.4

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

bob

**Comment by zeertzjq** [comment]
It seems that Vim loads this from the `help` syntax file, but doing this in Nvim will not work when using treesitter. Perhaps in Nvim this should be an ftplugin instead.

**Comment by clason** [comment]
Indeed, this doesn't work if using treesitter highlighting for help files (which isn't enabled by default).

The legacy syntax feature is neat but in my opinion not worth the complexity. If you _really_ want to see it, just do `:lua vim.treesitter.stop()`.
