### ISSUE TITLE
Customize Syntax Conceal Highlight Group

### ISSUE THREAD

**Issue by tj-moody** [neovim/neovim#25032]
### Problem

Syntax's `conceal` feature has no way to use highlight groups other than Conceal, and `matchadd` has the same problem. Treesitter highlighting through highlights.scm does allow the user to select any highlight group, but the feature isn't nearly as powerful as syntax (no regex before and after the match, for example). 

Relevant: `:h :syn-conceal`

### Expected behavior

An argument like syntax's cchar, such as `syntax match 'pattern' conceal cchar=C cgroup=Group`. This would be incredibly useful, as to the best of my knowledge the only way to achieve the same level of functionality as syntax without being limited to one highlight group is with virtual text, which is significantly more cumbersome. I really see no downside to implementing a feature like this, and frankly I'm surprised it doesn't already exist.

As an edit to the original issue, a potential cost is that the maintainers of syntax files may then feel compelled to examine all of their concealed groups and select a specific highlight group, which could be quite time-consuming for large syntax files with a lot of conceals, such as the runtime/syntax/tex.vim file.

**Comment by bfredl** [comment]
We don't really maintain the `:syntax` feature. If there is a reasonably simple patch to make it work, I'd suggest submitting that patch to _vim_ (the relevant code has not changed in nvim), and we will port it.

**Comment by zeertzjq** [comment]
Issue in Vim: https://github.com/vim/vim/issues/8730

**Comment by clason** [comment]
If you have suggestions (or PRs ;)) for **treesitter** conceal, we would be interested in that. Our goal is very much to make this as robust -- if not more so -- as legacy syntax.

**Comment by tj-moody** [comment]
I'm working on getting a working version of this functionality written in treesitter, but the primary example I had in mind was concealing latex superscripts, with more complex edge cases such as: `n^{n-1}` being concealed to <img width="38" alt="Screenshot 2023-09-11 at 3 51 40 PM" src="https://github.com/neovim/neovim/assets/92702993/8c2b4107-3548-4986-aa14-7d2d37f08429">.

The main difficulty here is scripting the conceal text based on the contents of the superscript and programmatically concealing each character within the same query. If I make significant headway with these issues I'll include it here, but otherwise I suspect it would require a PR with the necessary functionality

**Comment by clason** [comment]
So... you want anticonceal (generalized conceal -- right now, Vim has a limitation that you can replace things only with a single character).

**Comment by clason** [comment]
Also, concealing LateX code is 🤮

**Comment by tj-moody** [comment]
Not necessarily—vim syntax implements it this functionality already—for the case I mentioned, of  `n^{n-1}`, the `n`, `-`, and `1` are all concealed normally using an individual cchar, and `^`, `{`, & `}` are concealed to not be visible.

So I suppose the feature would be along the lines of more sophisticated concealing, most likely regex-based, inside of a match, i.e. programmatically mapping the contents of a capture to a specific conceal based on some regex.

I'm unsure if the treesitter query annotation syntax is even robust enough for this to be possible, but it's the simplest thing I can imagine to achieve parity with vim's syntax in terms of this functionality.

**Comment by clason** [comment]
> I'm unsure if the treesitter query annotation syntax is even robust enough for this to be possible, but it's the simplest thing I can imagine to achieve parity with vim's syntax in terms of this functionality.

It is; I just hate conceal with a passion, which is why the default LaTeX queries in nvim-treesitter don't have any. Doesn't mean you can't add your own.
