### ISSUE TITLE
Syntax highlighting for Scriban

### ISSUE THREAD

**Issue by ranger-turtle** [neovim/neovim#25038]
### Problem

Scriban is the templating engine which provides full-featured programming language. Scriban code can be embedded to files of many types of structured text, such as HTML.

I find it very useful and I have used it for one of my projects. In my opinion, it deserves more attention and syntax highlighting would probably popularize Scriban even more.

Scriban repository is at https://github.com/scriban/scriban.

### Expected behavior

Scriban syntax is highlighted in file types listed here:
https://github.com/scriban/scriban-vscode#features

**Comment by lewis6991** [comment]
Sorry we don't add additional support for languages here.

Someone needs to create a plugin for you.

**Comment by clason** [comment]
To be clear, the process is 
1. someone creates a filetype plugin (either as a standalone plugin or just a set of files)
2. someone submits them to Vim for inclusion in the runtime
3. we port the vim patch that adds them.

We do _not_ make independent changes to runtime files.

**Comment by ranger-turtle** [comment]
> We do not make independent changes to runtime files.

I see.
