### ISSUE TITLE
regression: `keywordprg` is wrongly set to `:Help` and thus `K` does not work if a shell script has shebang

### ISSUE THREAD

**Issue by e-kwsm** [neovim/neovim#25049]
### Problem

If a shell script has shebang, `K` does not open man because `keywordprg` is set to `:Help`.
This bisects to 020d1f626a3fbda84b84b2f57e8a85662a792a1a (#24864).

### Steps to reproduce

Prepare `a.sh`:
```sh
#!/bin/sh
ls
```

Open the above file with `--clean`, and press `K` on the `ls`. `:set kp?` shows `:Help`.
If the shebang is removed, then nvim works as expected (`kp` is `:Man`).

### Expected behavior

`kp` is set to `:Man` and man of `ls(1)` is opened, regardless of existence of shebang.

### Neovim version (nvim -v)

v0.10.0-dev-1049+g6a8b48e24

### Vim (not Nvim) behaves the same?

no, vim 9.0.1378

### Operating system/version

EndeavourOS

### Terminal name/version

GNOME Terminal 3.46.8 using VTE 0.70.6 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by justinmk** [comment]
@gpanders

**Comment by e-kwsm** [comment]
Thanks, I confirmed that the latest vim sets `kp` to `Help`.
