### ISSUE TITLE
FAILED when compiling

### ISSUE THREAD

**Issue by arywz11** [neovim/neovim#25045]
### Problem

FAILED: src/nvim/po/de.mo /xxx/workspace/github/neovim/build/src/nvim/po/de.mo
cd /xxx/workspace/github/neovim/build/src/nvim/po && /usr/bin/msgfmt -o /xxx/workspace/github/neovim/build/src/nvim/po/de.mo /xxx/workspace/github/neovim/src/nvim/po/de.po
[391/398] Generating ca.mo
FAILED: src/nvim/po/ca.mo /xxx/workspace/github/neovim/build/src/nvim/po/ca.mo
cd /xxx/workspace/github/neovim/build/src/nvim/po && /usr/bin/msgfmt -o /xxx/workspace/github/neovim/build/src/nvim/po/ca.mo /xxx/workspace/github/neovim/src/nvim/po/ca.po

$ msgfmt -o /xxx/workspace/github/neovim/build/src/nvim/po/cs.cp1250.mo /xxx/workspace/github/neovim/src/nvim/po/cs.cp1250.po
Segmentation fault (core dumped)

$ msgfmt --version
msgfmt (GNU gettext-tools) 0.21.1
Copyright (C) 1995-2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.

git commit:
(HEAD, tag: v0.9.0)

### Steps to reproduce

make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=/full/path/

### Expected behavior

no errors

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

centos

### Terminal name/version

windows terminal

### $TERM environment variable

tmux-256color

### Installation

centos

**Comment by bfredl** [comment]
v0.9.0 is old by now. You need to test with either latest master or v0.9.2. Also post full logs, not a narrow excerpt.

**Comment by justinmk** [comment]
looks like a `msgfmt` crash, not related to nvim
