### ISSUE TITLE
feature(lsp): interactive inlay hints (`tooltip`, `label[].location`, `textEdits`)

### ISSUE THREAD

**Issue by llllvvuu** [neovim/neovim#25069]
### Problem

There is no API or UI for interactive inlay hints (double click, tooltip, code actions).

### Expected behavior

Given how hover/code actions/etc work in Neovim, I don't expect a UI will happen, but maybe an API? For a plugin to be able to provide the UI, it needs an API to be able to handle a request either via click or cursor.
* Receive click events: We need to receive the `InlayHint` struct of the clicked hint. Sketch:
```lua
vim.lsp.buf.inlay_hint.on_click.register(draw_my_ui)
vim.lsp.buf.inlay_hint.on_click.unregister(draw_my_ui)
vim.lsp.buf.inlay_hint.on_click.unregister_all()

---@param inlay_hint InlayHint https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint
function draw_my_ui(inlay_hint)
```
* Make request for inlay hint info - either all inlay hints, or inlay hint at cursor. Sketch:
```lua
---@return InlayHint[]
vim.lsp.buf.inlay_hint.get_all()

---@return InlayHint[]
vim.lsp.buf.inlay_hint.get_in_range(range)
```

References:
https://github.com/rust-lang/rust-analyzer/pull/15522
https://github.com/rust-lang/rust-analyzer/pull/14533

**Comment by justinmk** [comment]
Provide an example of what you expect, as a concise bit of code. Linking to stuff isn't sufficient.

**Comment by llllvvuu** [comment]
Sure, I don't have a great understanding of Neovim API conventions but I just added some rough sketches/ideas.

**Comment by llllvvuu** [comment]
Another part of the LSP spec is inlay hint hover docs. This is also tricky to implement in Neovim for the same reason as the other inlay hint features: have to figure out how to get cursor over the inlay hint
