### ISSUE TITLE
Add Mojo highlighting

### ISSUE THREAD

**Issue by mahmoudajawad** [neovim/neovim#25063]
### Problem

Mojo is a new language, a superset of Python. Neovim currently doesn't support it.

### Expected behavior

Support syntax highlighting Mojo files.

**Comment by clason** [comment]
1. Legacy syntax requests need to go through Vim (via a maintained syntax plugin).
2. Treesitter syntax requests need to go through nvim-treesitter (there's a dedicated "request" issue, but that only serves as a wishlist for the community; the project itself will not create these).
