### ISSUE TITLE
Make use of fuzzy matching where applicable

### ISSUE THREAD

**Issue by mortezadadgar** [neovim/neovim#25077]
### Problem

Hey,
there are two cases i assume `fuzzymatch()` can be used:
1. omni completion candidates (command line completion already has a option for it)
2. `:find` files and directory (currently mentioned in help page as not supported)

### Expected behavior

to be implemented :)

**Comment by T-727** [comment]
related: https://github.com/vim/vim/issues/13035

**Comment by glepnir** [comment]
resolved by https://github.com/neovim/neovim/pull/29200
