### ISSUE TITLE
Inconsistent error reporting when vim.o option name contains typo (init.lua)

### ISSUE THREAD

**Issue by juliancoffee** [neovim/neovim#25081]
### Problem

If you have typos in your config, it may or may not signal to you about that. For example, if you just open your editor with "broken" config, you don't see any error. If you open your `init.lua` and do `:source %`, you get an error from `__newindex` metafunction.

### Steps to reproduce

Having this file and trying to do different things.
```lua
vim.o.numbers = true -- should be vim.o.number
```
First how to observe zero errors.
* a) No error. Just having file above as `init.lua` where it belongs.
* b) No error. `nvim -u` option
I tried both `nvim -u init.lua` (one that would be loaded by default),  `nvim -u init.new.lua`, `nvim -u new.init.lua` (just to be sure).

Now how to observe errors.
* a) Error `nvim init.lua` and then `:source %`. 
![image](https://github.com/neovim/neovim/assets/42647349/b10bb15e-f71e-4d57-a626-fec1888bdeb8)
(Sorry for screenshot, I still need to learn how to copy-paste in tmux)
* b) Error. `nvim init.lua --cmd ':source %'`
Same error, but without colours.
* c) Error. Change `vim.o.numbers` to `vim.opt.numbers = true`, and just run `nvim`
![image](https://github.com/neovim/neovim/assets/42647349/79b1ebf7-407c-4c13-b883-b492a3b65fd4)
This means that `vim.opt` catches an error in both cases.

From (c) I would guess, we might have some weird behaviour in __newindex for `vim.o`.

### Expected behavior

Every case results in an error from (a).

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.1692616192     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

no, vim doesn't have .lua config

### Operating system/version

ArchLinux, pacman v6.0.2

### Terminal name/version

alacritty + tmux

### $TERM environment variable

tmux-256color

### Installation

pacman

**Comment by zeertzjq** [comment]
The issue looks confusing. Do using `vim.opt` always reports errors, but using `vim.o` sometimes doesn't?

**Comment by juliancoffee** [comment]
> The issue looks confusing. Do you mean using `vim.opt` always reports errors, but using `vim.o` sometimes doesn't?

Yes, `vim.opt` always reports errors, `:source %` always reports errors, `vim.o` reports errors only in combination with `:source %`

**Comment by clason** [comment]
I cannot reproduce this; I get an error if I have a typo in a `vim.o` line in my `init.lua`.


Make sure you test with `nvim --clean`, in case you have plugins (as packages) that interfere with startup.

**Comment by lewis6991** [comment]
This behaviour might have changed since 0.9 when famiu deprecated the old option API methods.

**Comment by clason** [comment]
That is true; I'm on master.

**Comment by juliancoffee** [comment]
`nvim --clean -u init.lua` still doesn't report any errors.

I don't have time rn to build myself a neovim from source to check, but if this issue is fixed on master, I'm fine with closing it.

**Comment by clason** [comment]
Just download the nightly appimage.

**Comment by juliancoffee** [comment]
Yep, fixed in latest appimage.
