### ISSUE TITLE
regression: #24647 with indent+highlight causes injection queries to run on root document

### ISSUE THREAD

**Issue by llllvvuu** [neovim/neovim#25088]
### Problem

This is the result of investigation into #25074 @lewis6991. Tree-sitter queries can return a prohibitively large number of matches if run on the wrong filetype, causing a performance regression and rendering the editor unusable.

regression introduced in: #24647

### Steps to reproduce

`nvim -u init.lua`:
```lua
vim.opt.cursorcolumn = true
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath, }) end
vim.opt.rtp:prepend(lazypath)

local plugins = {
	{
		"nvim-treesitter/nvim-treesitter", build = ":TSUpdate", dependencies = { "nvim-lua/plenary.nvim" }, event = { "BufReadPost", "BufNewFile" },
		opts = { highlight = { enable = true, }, indent = { enable = true }, ensure_installed = "typescript", sync_install = false, auto_install = true, },
		config = function(_, opts) require("nvim-treesitter.configs").setup(opts) end,
	},
}

require("lazy").setup(plugins)
```

Sample file with pathological number of query matches:
https://gist.github.com/llllvvuu/d0e897bd7c3fe1a6daab6861f3dc3001

(Optional) Instrument `runtime/lua/vim/treesitter/query.lua:iter_captures()` to print the query, range, and/or iteration depth; or set up some kind of debugger.

Open the sample file, press O, and start typing.

### Expected behavior

The injection query should only run on the injection.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-814+g2ca076e45

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by clason** [comment]
Sorry, but unless you can reproduce this without any plugins, this looks to me like an nvim-treesitter issue -- why are you reporting this here?

**Comment by llllvvuu** [comment]
> Sorry, but unless you can reproduce this without any plugins, this looks to me like an nvim-treesitter issue -- why are you reporting this here?

The bad query is being called from TSHighlighter which is part of Neovim. It shouldn't be possible for a plugin to mess up Neovim internals like this, so I consider it to quite possibly be a Neovim issue.

**Comment by clason** [comment]
> The bad query is being called from TSHighlighter which is part of Neovim. It shouldn't be possible for a plugin to mess up Neovim internals like this

Oh, you sweet summer child...

Seriously, everything I've seen from you so far points towards nvim-treesitter's indent to need adaptation. 

> tree-sitter queries can return a prohibitively large number of matches if run on the wrong filetype

is also a huge red flag -- _why_ are these matches being run on the wrong filetype in the first place?

**Comment by clason** [comment]
For the record, I cannot reproduce this with the `main` branch of nvim-treesitter.

**Comment by llllvvuu** [comment]
Huh, `main` vs `master` is brutal. Thanks for your pointer, I'm going to port your commit to my `master` since none of my plugins work against `master`.

**Comment by clason** [comment]
`main` is the work-in-progress total rewrite of nvim-treesitter, which will become the default branch when it's finished (at which point `master` will likely be renamed); this was the least disruptive strategy. It's not something you're expected to know about -- in fact, the changes to `indent.lua` were backported to `master`. My comment was meant to indicate that your reproducing example has more going on than it seems to (mentioning the non-default branch for the sake of transparency).
