### ISSUE TITLE
Command-line flag to disable the log file

### ISSUE THREAD

**Issue by log-to-code** [neovim/neovim#25097]
### Problem

neovim tries to create a log file at `~/.local/state/nvim/log`. If you're on a read-only filesystem or a recovery partition neovim has an error: `E739: Cannot create directory /Users/taylorswift/.local/share: permission denied`

You can prevent the creation of that file and its parent directory if you `export NVIM_LOG_FILE="/dev/null"` in your shell and add `let $XDG_DATA_HOME="$TMPDIR"` to your `.vimrc`.

### Expected behavior

Provide a command-line option to disable creation of the log file and its parent directories.

**Comment by log-to-code** [comment]
The XDG specification says:

> When attempting to read a file, if for any reason a file in a certain directory is unaccessible, e.g. because the directory is non-existent, the file is non-existent or the user is not authorized to open the file, then the processing of the file in that directory should be skipped. If due to this a required file could not be found at all, the application may choose to present an error message to the user.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

But I hope you can provide a command-line option to make system recovery easier.

**Comment by justinmk** [comment]
CLI option won't be provided. But log-level will be controllable via the 'verbose' option after I finish https://github.com/neovim/neovim/pull/12503

`let $XDG_DATA_HOME=expand("$TMPDIR")` is a separate topic. If Nvim doesn't choose a _writable_ TMPDIR then that should be fixed.

**Comment by log-to-code** [comment]
Will #12503 prevent creation of the log file and its directories?

**Comment by log-to-code** [comment]
`let $XDG_DATA_HOME=expand("$TMPDIR")` was corrected to `let $XDG_DATA_HOME="$TMPDIR"` (no `expand()`) in the issue description.

**Comment by log-to-code** [comment]
Will #12503 prevent creation of the log file and its directories?

**Comment by log-to-code** [comment]
If you want to prevent an error you can:
1. `export NVIM_LOG_FILE="/dev/null"` in your your shell (or your `.bashrc` or `.zshrc` file)
2. Add `let $XDG_DATA_HOME="$TMPDIR"` to your neovim config

**Comment by log-to-code** [comment]
If you want to prevent an error on a read-only filesystem you can:
1. `export NVIM_LOG_FILE="/dev/null"` in your your shell (or your `.bashrc` or `.zshrc` file)
2. Add `let $XDG_DATA_HOME=expand("$TMPDIR")` to your neovim config

**Comment by clason** [comment]
I was not aware that a RFC process requires <30 minutes response time... 

(You are being massively unfair here; "neovim developers" have been engaging with your request in good faith.)

**Comment by clason** [comment]
> changes to neovim are unpredictable

What does that even mean?
