### ISSUE TITLE
regression(#24647): `LanguageTree:parse()` calls quadruple per character typed, until Neovim freezes

### ISSUE THREAD

**Issue by llllvvuu** [neovim/neovim#25104]
### Problem

The latency increases 4x per keystroke, i.e. the first 5 or so characters inserted feel fine, and then it takes a second, then a few seconds, and eventually it freezes.

The issue bisects to #24647.

### Steps to reproduce

1. Run `nvim --noplugin --clean -u repro.lua sample.lua`, where `repro.lua` is:
```lua
vim.opt.scrolloff = 999 -- not necessary, but just sets up the viewport
vim.api.nvim_create_autocmd('FileType', {
  pattern = { '*' },
  callback = function() vim.treesitter.start() end,
})
```
and `sample.lua` is provided here: https://gist.github.com/llllvvuu/45cf25963ffeab3f88feec196a032953
2. **(IMPORTANT)** resize your terminal so that `:echo winheight(0)` returns exactly 58 and `:echo winwidth(0)` returns at least 79. The issue will not reproduce if your window height is off by even 1.
3. `/vue<CR>o`. At this point, the last line in the window should say "on_initialized", and "taplo" should be the 4th, 5th or 6th line. If not, resize your terminal again and start over.
4. Type `foobarbazfoobarbazfoobarbaz = {}<ESC>`.
5. If you were able to survive step 4 (i.e. typed 5 chars or less), you should observe that each time you press `<C-e>` or `<C-y>`, `LanguageTree:parse()` is called 4^(n+2) times, where n is the number of chars you inserted in step 4.

NOTE: Don't call `:lua vim.treesitter.inspect_tree()` at any point. It will cause the issue to not reproduce.

### Expected behavior

No latency in typing.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-814+g2ca076e45

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MacOS 13.4.1 - MacBook Air M1 2020

### Terminal name/version

kitty 0.28.1, Terminal.app Version 2.13 (447)

### $TERM environment variable

xterm-kitty, tmux-256color, xterm-256color

### Installation

build from repo

### Flamegraph (click for interactive)

![flame](https://github.com/neovim/neovim/assets/5601392/084df3c1-9b89-41cc-98ed-00f541d1887e)

**Comment by lucario387** [comment]
So does this mean nvim-treesitter indents/neovim folds somehow saves neovim from freezing? :smile:
