### ISSUE TITLE
Wrapped lines get rendered as different lines

### ISSUE THREAD

**Issue by k-cross** [neovim/neovim#25139]
### Problem

While moving through a wrapped line in command mode, a duplicate line above or below it will appear in its place instead.

<img width="593" alt="Screenshot 2023-09-13 at 10 31 22 AM" src="https://github.com/neovim/neovim/assets/11242401/5130fd94-1767-4bb0-9b7e-3ddc5dab5dc8">

In addition to the environment specs below, I have tested this in a couple different environments and was able to reproduce this only while using `zellij`.

Does not appear:

- mac native term
- mac native term w/ tmux
- alacritty
- alacritty w/ tmux

Reproduces in:
- mac native term w/ zellij
- alacritty w/ zellij

I will post an issue in zellij too but I started experiencing this issue with the 0.9.2 release.

Thank you for everything, please let me know if there is anything else you need to help triage/fix this issue.

### Steps to reproduce

1. Write a few lines that don't wrap.
2. In the middle of those few lines, write a long line that produces a wrap
3. Change to command mode and move to a line below and observe

### Expected behavior

Wrapped lines do not render different lines in their place.

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 02 2023 19:52:05) macOS version - x86_64 Included patches: 1-1850

### Operating system/version

macOS 13.5.2

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

brew install neovim

**Comment by zeertzjq** [comment]
This is likely a bug in Zellij: https://github.com/zellij-org/zellij/issues/2785#issuecomment-1718858363

**Comment by k-cross** [comment]
i agree, i have no qualms w/ closing here.
