### ISSUE TITLE
docs: Link to `screen.c` is broken in wiki

### ISSUE THREAD

**Issue by kyu08** [neovim/neovim#25137]
### Problem

Link to `screen.c` is broken in [Code overview](https://github.com/neovim/neovim/wiki/Code-overview) within wiki.

This is my first issue to neovim,, so please excuse me if I'm doing it wrong.

### Steps to reproduce

- 

### Expected behavior

The link is not broken.

### Neovim version (nvim -v)

- 

### Vim (not Nvim) behaves the same?

- 

### Operating system/version

- 

### Terminal name/version

- 

### $TERM environment variable

- 

### Installation

-

**Comment by clason** [comment]
removed!

**Comment by kyu08** [comment]
Thank you for your quick response.
