### ISSUE TITLE
Are vim. list_contains deprecated?

### ISSUE THREAD

**Issue by abliger** [neovim/neovim#25176]
### Problem

I tried using gen_ Help_ HTML. lua file to generate an HTML document for neovim
Just use the following command `nvim - V2- es -- clean+' lua require ('scripts. gen_help_html '). gen ('./build/runtime/doc/',' target/dir/')`

Received and found an error:
```
E5108: Error executing lua ./scripts/gen_help_html.lua:536: attempt to call field 'list_contains' (a nil value)
stack traceback:
        ./scripts/gen_help_html.lua:536: in function 'visit_node'
        ./scripts/gen_help_html.lua:454: in function 'visit_node'
        ./scripts/gen_help_html.lua:454: in function 'visit_node'
        ./scripts/gen_help_html.lua:454: in function 'visit_node'
        ./scripts/gen_help_html.lua:788: in function 'gen_one'
        ./scripts/gen_help_html.lua:1126: in function 'gen'
        [string ":lua"]:1: in main chunk
```
Using vim.tbl_contains can only operate normally.
Are vim. list_contains deprecated?

### Steps to reproduce

`make CMAKE_BUILD_TYPE=RelWithDebInfo`
`nvim - V2- es -- clean+' lua require ('scripts. gen_help_html '). gen ('./build/runtime/doc/',' target/dir/')`

### Expected behavior

no error

### Neovim version (nvim -v)

0.9.2

### Vim (not Nvim) behaves the same?

no test

### Operating system/version

macOS 14

### Terminal name/version

item

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by zeertzjq** [comment]
Use nightly version
