### ISSUE TITLE
LSP: completion via omnifunc deletes previous character

### ISSUE THREAD

**Issue by Supreeeme** [neovim/neovim#25177]
### Problem

Using the built in completion (omnifunc) with an LSP server deletes the previous character upon completion.

https://github.com/neovim/neovim/assets/7882157/fe4bb4a6-0a65-4479-8963-e136fadd22cc

### Steps to reproduce

1. Install language server of your choice (I tested with `clangd` and `rust_analyzer`)
2. `nvim -u NONE <test file of your choice>`
3. `:lua vim.lsp.start_client{ cmd = {"/path/to/language/serer"} }`
4. `:lua vim.lsp.buf_attach_client(vim.fn.bufnr(), 1)`
5. Trigger completion via ctrl-x + ctrl-o, notice how the character right before the cursor gets deleted.

### Expected behavior

Character before the cursor is not deleted

### Neovim version (nvim -v)

v0.10.0-dev-1113+gf5a09f1b03

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Arch Linux

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

AUR

**Comment by lucario387** [comment]
this is like the reverse of the tsserver LSP bug :thinking:

**Comment by glepnir** [comment]
known issue try https://github.com/neovim/neovim/pull/24661

**Comment by rafikdraoui** [comment]
The regression seems to have started with https://github.com/neovim/neovim/pull/24646.

**Comment by glepnir** [comment]
before implement also wrong. try the pr. it jut draft now. because it need wait some prs merge.

**Comment by SanchayanMaity** [comment]
Was expecting #24646 to be reverted by now.

**Comment by glepnir** [comment]
revert won't solve the problem either. filterText should not be used here. The problem is that startcol is calculated incorrectly.

**Comment by isaacph** [comment]
Rebuilding to the most recent master, with @mfussenegger's commit, I still get this issue in C on Windows: 

https://github.com/neovim/neovim/assets/37312022/80a547c3-c025-4037-9a1b-76aeb1b91a20

**Comment by glepnir** [comment]
because get startcol not correct I fixed it in #24661 before. can take a look at my implement
