### ISSUE TITLE
Also inject syntax highlighting in `nvim_create_autocmd`'s `command`

### ISSUE THREAD

**Issue by mawkler** [neovim/neovim#25172]
### Problem

nvim-treesitter/nvim-treesitter/pull/1922 added VimScript injection to `vim.cmd`/`nvim_command`/`nvim_exec`. The `command` field in the `opts` dictionary passed to `:h nvim_create_autocmd` is also VimScript, but doesn't currently get VimScript injected.

```lua
vim.api.nvim_create_autocmd({"BufEnter", "BufWinEnter"}, {
  pattern = {"*.c", "*.h"},
  command = "echo 'Entering a C or C++ file'", -- Doesn't currently get syntax highlighting
})
```

```lua
vim.api.nvim_create_autocmd({"BufEnter", "BufWinEnter"}, {
  pattern = {"*.c", "*.h"},
  callback = function()
    vim.cmd "echo 'Entering a C or C++ file'" -- Does get syntax highlighting
  end
})
```

### Expected behavior

The string that the `command` field passed to `nvim_create_autocmd` gets set to should also get VimScript injected.

**Comment by clason** [comment]
Please open this issue at nvim-treesitter; we want to avoid needless divergence.

**Comment by mawkler** [comment]
Oh that's my bad I meant to post it there. Apologies!
