### ISSUE TITLE
assertion failure at unpacker.c:466

### ISSUE THREAD

**Issue by llllvvuu** [neovim/neovim#25184]
### Problem

This assertion fails occasionally while editing code:

https://github.com/neovim/neovim/blob/f67517bba30b6233bea85e1f6a8505171142d4ca/src/nvim/msgpack_rpc/unpacker.c#L467

I can force it to fail by scrolling very quickly.

### Steps to reproduce

`repro.lua`:
```lua
function Repro()
  vim.defer_fn(function()
    local move_direction = math.random(2)
    if move_direction == 1 then
      for i=1,10 do
        vim.api.nvim_feedkeys("5k", "n", false)
      end
    else
      for i=1,10 do
        vim.api.nvim_feedkeys("5j", "n", false)
      end
    end
    Repro()
  end, 0.05)
end
```

```sh
nvim --noplugin --clean -u repro.lua src/nvim/msgpack_rpc/unpacker.c
```

It should crash within 30 seconds. If you get bored you can drag the corner of the terminal around while spamming `<C-c>` to try and mess with it more. Also having plugins (IDK if it matters which ones) seems to make it happen faster / more reliably.

### Expected behavior

No crash.

### Neovim version (nvim -v)

be10d65bf (0.10 nightly)

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MacOS 13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by llllvvuu** [comment]
I'm now getting this at least once a day, so when I find some time I'll see if I can add an ELOG of the full state history of the state machine (if it's not too many bytes per second)

**Comment by llllvvuu** [comment]
The only place we are touching `icells` within the loop is the increment:

https://github.com/neovim/neovim/blob/9ff6f73f838a1f90d09922448c434033ba5e094e/src/nvim/msgpack_rpc/unpacker.c#L509

THat can't break it, so it must be already failing before the loop:

https://github.com/neovim/neovim/blob/9ff6f73f838a1f90d09922448c434033ba5e094e/src/nvim/msgpack_rpc/unpacker.c#L453-L454

Either `ncells` is negative or zero. I am going to instrument my code to find out:

```diff
g->ncells = (int)tok.length;
+ assert(g->ncells >= 0);
+ assert(g->ncells > 0);
```

But I must ask, is is really illegal to have empty `cells` in the [`ui-event-grid_line`](https://neovim.io/doc/user/ui.html#ui-event-grid_line)? Reading the spec, it seems like that should just be a no-op?

**Comment by zeertzjq** [comment]
> it seems like that should just be a no-op?

Yes.

**Comment by llllvvuu** [comment]
So that was not the only issue, it seems this also fails:

```lua
diff --git a/src/nvim/msgpack_rpc/unpacker.c b/src/nvim/msgpack_rpc/unpacker.c
index e32b2fea8..3aa1ba122 100644
--- a/src/nvim/msgpack_rpc/unpacker.c
+++ b/src/nvim/msgpack_rpc/unpacker.c
@@ -318,10 +318,6 @@ bool unpacker_advance(Unpacker *p)
   }
 
   if (p->state >= 10 && p->state != 13) {
-    if (p->state == 15) {
-      GridLineEvent* g = p->grid_line_event;
-      assert(g->icell < g->ncells);
-    }
     if (!unpacker_parse_redraw(p)) {
       return false;
     }
```

Now to figure out: how do we finish parsing a grid line but not exit state 15 (thus re-entering it)? I might be close....

**Comment by llllvvuu** [comment]
> Now to figure out: how do we finish parsing a grid line but not exit state 15 (thus re-entering it)?

OK I found this out. There is actually a control tucked behind a macro, where we can return "unfinished" state after finishing:

https://github.com/neovim/neovim/blob/f67517bba30b6233bea85e1f6a8505171142d4ca/src/nvim/msgpack_rpc/unpacker.c#L513-L514

https://github.com/neovim/neovim/blob/f67517bba30b6233bea85e1f6a8505171142d4ca/src/nvim/msgpack_rpc/unpacker.c#L388-L391

i.e. we're suspending right after parsing the last cell but before parsing `wrap` in:
```
["grid_line", grid, row, col_start, cells, wrap]
```

And now we're stuck thinking we're still parsing `cells` instead of parsing `wrap`.

The easiest way to handle this is just adding a state 16 for `wrap`.

**Comment by megalithic** [comment]
@llllvvuu thank you! this legitimately has been plaguing me for weeks. looking forward to the patch! Thank you @zeertzjq for pointing me to this thread...
