### ISSUE TITLE
LanguageTree:trees() may not be an array

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#25191]
### Problem

With incremental injection parsing, injected languages' parsers parse only the relevant regions and stores the result in `_trees` with the index of the corresponding region. Therefore, there can be holes in `_trees`. 

However, several places assume that `_trees` is an array.
* https://github.com/neovim/neovim/blob/2e92065686f62851318150a315591c30b8306a4b/runtime/lua/vim/treesitter/languagetree.lua#L621
* https://github.com/neovim/neovim/blob/2e92065686f62851318150a315591c30b8306a4b/runtime/lua/vim/treesitter/languagetree.lua#L642
* https://github.com/neovim/neovim/blob/2e92065686f62851318150a315591c30b8306a4b/runtime/lua/vim/treesitter/languagetree.lua#L649
* transitively, all uses of `included_regions()`
* https://github.com/nvim-treesitter/nvim-treesitter/blob/c617560e1b0240e5c1d72b5f1c45f86c8b9b7d7a/lua/nvim-treesitter/ts_utils.lua#L205

### Steps to reproduce

```
nvim --clean README.md
```
```
:$
:lua vim.treesitter.start()
:redraw
:=vim.treesitter.get_parser():children()['markdown_inline']:trees()
```
result is something like this:
```
{  
  [30] = <userdata 1>,
  [31] = <userdata 2>,
  [32] = <userdata 3>,
  [33] = <userdata 4>
}
```

### Expected behavior

* Codes in Neovim core should be fixed
* This point should be documented.

### Neovim version (nvim -v)

0.10 2e9206568

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

**Comment by clason** [comment]
Good catch, PR welcome!
