### ISSUE TITLE
Lsp doc bug

### ISSUE THREAD

**Issue by bmariuszb** [neovim/neovim#25198]
### Problem

I'm reading [Lsp doc](https://neovim.io/doc/user/lsp.html) and point 3 of QUICKSTART  says

> 3. Check that the server attached to the buffer:
> `:lua =vim.lsp.get_clients()`

I tried it and got error:
`E5108: Error executing lua [string ":lua"]:1: attempt to call field 'get_clients' (a nil value)  
stack traceback:
        [string ":lua"]:1: in main chunk`
I think that it should be changed to:
`:lua =vim.lsp.get_active_clients()`

### Steps to reproduce

Just run the command in a fresh neovim.

### Expected behavior

The command should work like
`:lua =vim.lsp.get_active_clients()`

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.1694285958

### Vim (not Nvim) behaves the same?

no, it doesn't support lua at all

### Operating system/version

Artix Linux - runit

### Terminal name/version

kitty 0.29.2

### $TERM environment variable

xterm-kitty

### Installation

pacman

**Comment by tjmblake** [comment]
The docs used to have `get_active_clients()`. 
However, the functionality in 0.10 is now `get_clients()`.

Looks like here it mentions get_active_client() will be removed in 0.12
https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L2057

**Comment by jcarstairs-scottlogic** [comment]
This is still causing issues. `get_clients()` may well be the v0.10 way, but the current stable release is still on v0.9. In the meantime, this documentation has caused me to stumble multiple times (because I always forget about this issue by the next time I read it). Could we re-open this issue until v0.10 is stable?
