### ISSUE TITLE
Cache Directory and other Standard Paths Information Missing From Standard Paths Documentation

### ISSUE THREAD

**Issue by Pxartist** [neovim/neovim#25205]
### Problem

Information on the cache directory and its corresponding environment variable (`$XDG_CACHE_HOME`) is missing from the [Standard Paths documentation](https://neovim.io/doc/user/starting.html#standard-path). It was when I was verifying that I had properly relocated all of my Neovim files through the usage of [`stdpath("cache")`](https://neovim.io/doc/user/builtin.html#stdpath()) that I realized that information regarding the cache directory was not provided. I had to use a [third party website](https://vi.stackexchange.com/questions/21824/how-to-control-cache-folder-location) to resolve my issue due to the cache folder not being properly documented.

If possible, information on the corresponding directories and environment variables of `stdpath("config_dirs")`, `stdpath("data_dirs")`, and `stdpath("log")` should also be provided in the [Standard Paths documentation](https://neovim.io/doc/user/starting.html#standard-path).

### Expected behavior

Information of the cache directory and its corresponding environment variable ($XDG_CACHE_HOME) should be present in the [Standard Paths documentation](https://neovim.io/doc/user/starting.html#standard-path). Information on the corresponding directories and environment variables of `stdpath("config_dirs")`, `stdpath("data_dirs")`, and `stdpath("log")` are also not present as well.

**Comment by eduardorittner** [comment]
I'm in the process of updating the docs but have some questions, are $XDG_DATA_DIRS and $XDG_CONFIG_DIRS defined for windows? in stdpaths.c they are simply defined as null.

![image](https://github.com/neovim/neovim/assets/116819854/bc83a018-7ae9-4f90-b09c-2f1cd520a619)

Also, the log file in unix is simply named "log", is that valid for windows also or would it have an extension like "log.txt" or something? I'm not really familiar with what would change.
And the last thing is I can't seem to find where the $NVIM_LOG_FILE variable is defined, only where it's used, but it seems to default to $XDG_STATE_HOME. This is not really an issue since the docs only need to clarify the default behavior, but I still would like to know this since I've spent quite some time looking for it.

**Comment by MariaSolOs** [comment]
@eduardorittner Good questions and congrats on your first open source contribution :)

You want to always check the [`CONTRIBUTING` docs](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#pull-requests-prs) beforehand. This repo recommends creating a PR right away (it can be a draft if it's not ready yet). In there I would suggest asking your questions to have better visibility.

**Comment by Pxartist** [comment]
> I'm in the process of updating the docs but have some questions, are $XDG_DATA_DIRS and $XDG_CONFIG_DIRS defined for windows? in stdpaths.c they are simply defined as null.
> 
> ![image](https://user-images.githubusercontent.com/116819854/268499505-bc83a018-7ae9-4f90-b09c-2f1cd520a619.png)
> 
> Also, the log file in unix is simply named "log", is that valid for windows also or would it have an extension like "log.txt" or something? I'm not really familiar with what would change. And the last thing is I can't seem to find where the $NVIM_LOG_FILE variable is defined, only where it's used, but it seems to default to $XDG_STATE_HOME. This is not really an issue since the docs only need to clarify the default behavior, but I still would like to know this since I've spent quite some time looking for it.
> 
> Any help would be greatly appreciated since this is my first time trying to contribute to neovim and open source in general. Should I just create a PR with my changes and have these questions be answered there or is here a good place to discuss them?

As far as I am aware, none of the `$XDG` variables are defined for Windows by default. As such, the default directories will always be used if no manual intervention is taken.

For the log file, it is not created with a file extension. Text editors like Notepad can still open it and view its contents. Although it should be noted that log files created by plugins such as lsp, luasnip, and mason have the `.log` file extension. The lack of a the file extension does not pose a significant issue, as it merely makes the user select a program to open it with, rather than automatically open the file with the default text editor if it had a file extension like `.txt` or `.log`.

I can confirm that the log file directory is controlled by `$XDG_STATE_HOME`. In that case, I think it would be appropriate to note that the State Directory, `$XDG_STATE_HOME`, also controls the location of the log files in the documentation.

**Comment by eduardorittner** [comment]
> @eduardorittner Good questions and congrats on your first open source contribution :)
> 
> You want to always check the [`CONTRIBUTING` docs](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#pull-requests-prs) beforehand. This repo recommends creating a PR right away (it can be a draft if it's not ready yet). In there I would suggest asking your questions to have better visibility.

thanks! will do

**Comment by eduardorittner** [comment]
#25227

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/25227
