### ISSUE TITLE
Tutor: how to modify text?

### ISSUE THREAD

**Issue by vsly-ru** [neovim/neovim#25203]
### Problem

I'm just starting with Neovim and I started with :help and then :Tutor. 
It explains in good details which keys to press to navigate the text. But when I got to the editing, it just says "Sometimes you will be required to modify text" and expect me to somehow modify the next line. I have no idea how to do this at this point. I've tried pressing Enter and typing, I've tried navigating to highlighted links Enter and `like this`, I've tried using :help and found :append command (but after entering it, I couldn't exit it, no matter how many times I typed :q).
![image](https://github.com/neovim/neovim/assets/39321074/02abe549-0f31-4913-bfba-43a208ce4624)

### Expected behavior

I expect the Tutor would say how to modify a text before expecting me to be able to do it.

**Comment by zeertzjq** [comment]
It doesn't expect you to modify that text.

**Comment by vsly-ru** [comment]
@zeertzjq yeah, I can see now sections 1.3 & 1.4 about editing the text. 
### Let me explain the cause of this confusion.
1. Tutorial says it's interactive and `It is IMPORTANT to remember that this tutorial is set up to teach by use.`
2. Every point of the list in Lesson 0 (except the last one) expect you to do something (Type <Enter>, type K, close with :q, _modify text_) and suddenly a pure informational statement like "btw you can modify text, but we won't tell you how lol".

**Comment by vsly-ru** [comment]
@zeertzjq your answer reminded me good old stackoverflow days. 
Don't you value here the UX of your project? 
This is a possible cause of confusion for new users, isn't it? 
I have pointed out an area for improvement for new users.
I'm sorry, but why you closed the issue, like it's nothing?

**Comment by zeertzjq** [comment]
I don't think there is any confusion.

**Comment by vsly-ru** [comment]
@zeertzjq I'm a new user and you are an experienced one. What is obvious for you is not obvious for me. Why this line is even there in the first place? What it supposed to teach me about? That in the future I'll be **required** to modify a text? First – nice fact! Second, it's the purpose of a text editor. Oh, the tutorial will require me to modify a text, like **THIS HERE**? 

And then it says
```
Once you have done the changes correctly, the x sign at the left will change to ✅.
```
What is this if not a call to action?

**Comment by zeertzjq** [comment]
Isn't the sign at the left already a ✅? So you don't need to modify it.

**Comment by vsly-ru** [comment]
Oh, so the lines with x or ✅ are just tasks to complete? Omg. Why don't explain this concept first?
I'm keep learning the new stuff about the Tutor from this thread, not from the actual tutor. 
Okay, if you prefer it to keep the Tutor this confusing, i'll better just drop it and watch a YT tutorial instead.

**Comment by vsly-ru** [comment]
@zeertzjq nice work in #25204, thanks a lot!
I think now it must be much easier to understand the introduction.
