### ISSUE TITLE
Shift-mouse starts visual mode in terminal

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2520]
I am using urxvt / rxvt-unicode as a terminal, and have `set mouse=a`.

When I want to select text from the terminal window, I use "Shift" while clicking and dragging the text (or double-clicking it).

With Neovim, this can trigger/start the visual mode, while it gets ignored correctly by vanilla Vim. This appears to only happen after the mouse has been used once to trigger the visual mode.
In this case both Neovim and rxvt-unicode appear to manage their selections - the issue is not that just visual mode is started (as if Shift wasn't used).

TEST CASE:
1. `nvim -u NONE`
2. :set mouse=a
3. use the mouse to start visual mode (click and drag)
4. Escape
5. Use the mouse with Shift pressed to select text

Using "Shift-mouse" before visual mode is being triggered through the mouse works.
It's not a problem with gnome-terminal.

Visual mode should not get triggered again, but it is.

**Comment by mhinz** [comment]
Maybe related: https://github.com/neovim/neovim/pull/2383

**Comment by blueyed** [comment]
Thanks, @mhinz.
I've tried your one-line fix, but is does not help - it's not related to the tabline also.
But the issue is similar indeed.

**Comment by blueyed** [comment]
It turned out to be a bug in rxvt-unicode (see the above commit, https://github.com/blueyed/rxvt-unicode/commit/b5594fc51c6540e390ba304f6c95284f26c03594).

Submitted for rxvt-unicode at: http://lists.schmorp.de/pipermail/rxvt-unicode/2015q3/002145.html

**Comment by justinmk** [comment]
Thanks for the followup.
