### ISSUE TITLE
Opening any Javascript file throws error

### ISSUE THREAD

**Issue by suvasanket** [neovim/neovim#25220]
### Problem

i've not opened any js files from a long time and now suddenly after Upgrading neovim while reviewing some files when i opened a js file it constantly throws errors
`Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: ...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24: Error executing lua: ...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:25: BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ...im/0.9.2/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 478 for language javascript
stack traceback:
	[C]: in function '_ts_parse_query'
	...im/0.9.2/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get_query'
	.../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:108: in function 'get_query'
	...t/.local/share/nvim/lazy/nvim-ts-rainbow/lua/rainbow.lua:8: in function 'is_supported'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:387: in function 'is_enabled'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:507: in function 'attach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
	[C]: in function 'nvim_cmd'
	...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:25: in function <...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24>
	[C]: in function 'nvim_buf_call'
	...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24: in function <...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_cmd'
	...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:25: in function <...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24>
	[C]: in function 'nvim_buf_call'
	...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24: in function <...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_buf_call'
	...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:24: in function <...brew/Cellar/neovim/0.9.2/share/nvim/runtime/filetype.lua:10>
`
this is the error

### Steps to reproduce

nvim anyfile.js

### Expected behavior

should not show any error

### Neovim version (nvim -v)

0.9.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS ventura

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by clason** [comment]
This is an nvim-treesitter problem with your(!) queries; check the pinned issue in that repo.
