### ISSUE TITLE
Add help tags for useful paragraphs on text-obj behavior in object/visual mode

### ISSUE THREAD

**Issue by bew** [neovim/neovim#25224]
### Problem

I just discovered (_by really not understanding what was going on.._) the builtin behavior of repeated usage of text objects in visual mode as described in:
https://github.com/neovim/neovim/blob/71d9b7d15c9b2e0df7db69a172aea0723a40bb71/runtime/doc/motion.txt#L678-L686

This is _very_ interesting behavior !!! :ok_hand:
However there is no way to simply refer to this paragraphs specifically.

<details>
<summary>other paragraph just above would also benefit from a help tag</summary>

https://github.com/neovim/neovim/blob/71d9b7d15c9b2e0df7db69a172aea0723a40bb71/runtime/doc/motion.txt#L663-L676

</details>

### Expected behavior

I'd like to have the ability to refer to these 2 paragraphs **specifically** in my configs via 1+ help tags like `v_text-objects` or `o_object-select`

**Comment by clason** [comment]
We don't own these files; please make this request at Vim. If they update the docs, we'll port the changes as a matter of course
