### ISSUE TITLE
Auto pastetoggle does not work in pangoterm

### ISSUE THREAD

**Issue by Tranquility** [neovim/neovim#2523]
I am using the latest version. Please tell me how I can help to fix this.

**Comment by justinmk** [comment]
Need more info. Are you talking about `'pastetoggle'` setting explicitly, or middle-click paste?

**Comment by Tranquility** [comment]
I mean that if I paste neovim should switch autmatically to pastemode and disable it afterwards. It does work in other terminal emulators I tried but not in pangoterm.

**Comment by tarruda** [comment]
@Tranquility I don't think pangoterm sends the bracketed paste sequences, @leonerd can confirm

**Comment by leonerd** [comment]
Correct. It doesn't yet, that should be added.

**Comment by leonerd** [comment]
Keep an eye on https://blueprints.launchpad.net/libvterm/+spec/bracketed-paste

**Comment by leonerd** [comment]
Now done as of libvterm -r650 + pangoterm -r577

**Comment by leonerd** [comment]
Additionally, now that `libvterm` has added the functions of `vterm_keyboard_start_paste()` and `vterm_keyboard_end_paste()`, you may wish to see if there's anywhere in neovim's own use of `libvterm` that should be calling these, so that bracketed paste mode is correctly sent onwards.

**Comment by tarruda** [comment]
>  you may wish to see if there's anywhere in neovim's own use of libvterm that should be calling these, so that bracketed paste mode is correctly sent onwards.

Yes, we can make use of `vterm_keyboard_start_paste()` when running the paste operator in a terminal buffer

**Comment by justinmk** [comment]
The latest bzr revision at https://code.launchpad.net/libvterm is -r649

**Comment by leonerd** [comment]
@justinmk Yeah - LP only pulls from me every few hours. r650 is up now
