### ISSUE TITLE
Help docs don't mention that 'ignorecase' and 'smartcase' affect insert mode and commandline completion

### ISSUE THREAD

**Issue by asheq-svmx** [neovim/neovim#25253]
### Problem

See `:h 'ignorecase'` and `:h 'smartcase'`

There is no mention of those options affecting insert mode completion or command line completion. But they do.

In general, this seems to be a problem with other options as well. The help docs do not comprehensively list everything an option affects. This can give users dread/anxiety when changing an option because they don't know all the behavior it modifies.

### Steps to reproduce

nvim --clean
:h 'smartcase'
:h 'ignorecase'

### Expected behavior

List everything the option affects. Perhaps in a bulleted or numbered list.

### Neovim version (nvim -v)

NVIM v0.9.1

### Vim (not Nvim) behaves the same?

no, vim -u DEFAULTS

### Operating system/version

macOS 12.6

### Terminal name/version

kitty 0.25.0

### $TERM environment variable

xterm-kitty

### Installation

brew

**Comment by asheq-svmx** [comment]
> 'smartcase' refers to 'ignorecase', so things are not going to be duplicated there. Denormalizing everything in every place isn't maintainable.

That's not what I'm suggesting.

The problem is that _neither_ `:h 'smartcase'` _nor_ `:h 'ignorecase'` mention that that they affect **commandline completion** or **insert mode completion**.

For example, with `ignorecase` on:
`:dir<Tab>` on the commandline will complete to `:Dirvish`. This is not the case with `ignorecase` off.

I discovered this by chance; there is no place in the help docs that mention this.

I think this is a microcosm of a larger problem in the help docs for options: if users can't trust the docs to tell them what an option affects comprehensively, then an underlying anxiety builds up within them about how they are affecting their system. 

(Regarding de-duplication/normalization of information, I am a fan. Duplication is absolutely terrible for maintenance. Information gets quickly out of sync. As much as possible, information should be in one place and one place only and linked to where needed)

**Comment by justinmk** [comment]
`:help 'ignorecase'` was updated:

> Ignore case in search patterns, completion, and when searching the tags file. 


> I think this is a microcosm of a larger problem in the help docs for options: if users can't trust the docs to tell them what an option affects comprehensively, then an underlying anxiety builds up within them about how they are affecting their system.

I agree in general, but I think you are overstating the case. There are some holes, which get patched up, plus going forward both Vim and Nvim are tending to increase "visibility" in the form of `:checkhealth` and programmatic mechanisms such as `mapset()`, which increase trust and reduce anxiety.

I understand the anxiety and experienced it myself in the early days--that was partly what motivated me to join Neovim, which reduces surface area (old options and anti-features) and thus reduces user pain. 

The "coping method" is to be more selective about which options and plugins one enables, and that continues to be important. But it's also a project goal to improve visibility and dynamic "self-checks" (e.g. performance checks, badly-behaving plugins, etc.).

**Comment by asheq-svmx** [comment]
Thanks for the reply. It's good to know that you can relate to my concerns and that things are headed in the right direction.

> I agree in general, but I think you are overstating the case. There are some holes, which get patched up. But also going forward, both Vim and Nvim are tending to increase "visibility" in the form of :checkhealth and programmatic mechanisms such as mapset(), which increase trust and reduce anxiety. 

Automated mechanisms like :checkhealth are great but they are not designed to catch user "ignorance" (for lack of a better term). For example,  `'ignorecase'` being on is not necessarily an error that should be flagged by the automated mechanism. But if a user has it on and is ignorant about some affect that it has, that's still a problem. This is a situation that needs to be resolved in the user's mind, not somewhere else.

Coincidentally, I stumbled upon another thing today that `'ignorecase'` affects: **expressions**.

For example:
- With 'ignorecase' off: 'abc' == 'ABC' evaluates to 0
- With 'ignorecase' on: 'abc' == 'ABC' evaluates to 1

Perhaps the real problem is that some options are overloaded? May be it would have been better to have more options and have options grouped into categories, e.g.,
- `search.ignorecase`
- `cmd_completion.ignorecase`
- `ins_completion.ignorecase`
- `expression.ignorecase`
 
This kind of grouping of options would help remove overloading and also provide a sort of self-documentation.

**Comment by justinmk** [comment]
> I stumbled upon another thing today that `'ignorecase'` affects: **expressions**.

That is mentioned at `:help expr-==`. It's one of many quirks of vimscript. There's no way for us to fix vimscript.

**Comment by ychin** [comment]
I was going to be updating some docs in `:h cmdline-completion` as part of my Vim PR vim/vim#13182. I may take this opportunity to update the case selection logic in that document either in the same PR or a related one. The logic is a little more complicated than just "ignorecase affects completion", because it's only used for regex search, so commands etc are affected by it, whereas runtime-dir searches are not (e.g. `:setfiletype`, `:runtime`). Also, if you have `:set wildoptions+=fuzzy`, then it also doesn't matter at all as fuzzy search ignores that.

**Comment by ychin** [comment]
See https://github.com/vim/vim/pull/13331
