### ISSUE TITLE
bug(treesitter): parse tree in a broken state (wrong lang) after making no-op edit, leading to slow editing until full reparse

### ISSUE THREAD

**Issue by llllvvuu** [neovim/neovim#25252]
### Problem

bisected to d7ae9ae3e. Specifically the combination of https://github.com/tree-sitter/tree-sitter/commit/9564e1706de651cea6df9939b8a5dba02e7dbc71 and https://github.com/neovim/neovim/commit/2ca076e45fb3f1c08f6a1a374834df0701b8d778 causes the full issue. The latter by itself already causes a broken parse tree, but the broken tree changes after the tree-sitter update and this triggers the performance issue (probably a trigger not a cause)

At a particular part of a test file, if you add and remove a new line repeatedly, the parse tree will end up in a broken state:

Before no-op edit:

<img width="1552" alt="Screenshot 2023-09-19 at 7 42 37 PM" src="https://github.com/neovim/neovim/assets/5601392/84092f54-f077-4ff7-82b6-e1dd9e8e22d7">

After no-op edit:

<img width="1552" alt="Screenshot 2023-09-19 at 7 42 59 PM" src="https://github.com/neovim/neovim/assets/5601392/6ba46ca1-0226-464c-88a2-f583ead784c9">

After no-op edit, if tree-sitter not upgraded (still wrong but not lag):

<img width="1552" alt="Screenshot 2023-09-19 at 7 40 44 PM" src="https://github.com/neovim/neovim/assets/5601392/8575c453-c336-442d-87a2-dad2659a9537">

I did some logging and it looks like `self._regions` might be getting wiped out (shows as `nil`)

Note: the inspector will interfere with the repro by doing a full parse, unless you change to false in the following line:

https://github.com/neovim/neovim/blob/c4f4c7a356013c6f1e10b7bf239d9e3c4c0c336e/runtime/lua/vim/treesitter/dev.lua#L102

### Steps to reproduce

`repro.lua` (minimal config):
```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = { "*" },
  callback = function() vim.treesitter.start() end,
})
```
`lspconfig.lua` (the file we are editing): [download (~500 lines)](https://github.com/llllvvuu/dotfiles/blob/9e54b87b4fdb17becef516863ab623756da43ae1/vim/.config/nvim/lua/plugins-tui/lspconfig.lua)
1. `nvim --clean --noplugin -u repro.lua lspconfig.lua`.
2. Adjust winheight to 57 for this demo (`:echo winheight(0)`)
3. `/vue<CR>f}i` should place you in insert mode between the brackets. First line of screen should say "suggest = {" and last line should say "on_initialized = function()" (it's critical that the vimscript injection is just offscreen after this last line, so that it gets parsed)
4. Press `<CR><Backspace><Backspace>` to insert and remove a new line. This should be quite snappy, although the syntax highlighting should be wrong at this point.
5. Repeat step 4 over and over; it should get laggy after a few times.

### Expected behavior

Tree does not break.

### Neovim version (nvim -v)

0.10 commit 28f54a78782318cb9c356a372b9e52a3a6b1f8dd

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by llllvvuu** [comment]
I have confirmed that the issue does not reproduce with incremental highlighting turned off (i.e. change last line of `intercepts_region` to `return true`). So it seems the combination of both ingredients (incremental highlighting + upstream tree-sitter update) are required to produce the full issue (whereas incremental highlighting by itself only produces an aesthetic issue)

**Comment by llllvvuu** [comment]
Attaching the screen recordings of incorrect highlighting (which can be reproduced with steps in the issue description):

Prior to both changes (correct highlighting):

https://github.com/neovim/neovim/assets/5601392/410ad3e4-cb6a-498c-a035-24ec68b9ae03

Incremental injection but no tree-sitter update (incorrect highlighting):

https://github.com/neovim/neovim/assets/5601392/8c6819d5-9726-4dd2-bef7-d53daf7ed97e

Incremental injection and tree-sitter update (different incorrect highlighting):

https://github.com/neovim/neovim/assets/5601392/350c0ad4-e367-49d2-becb-accd4d64437c

**Comment by llllvvuu** [comment]
OK, I got the inspector to work by setting `true` to `false` in:

https://github.com/neovim/neovim/blob/c4f4c7a356013c6f1e10b7bf239d9e3c4c0c336e/runtime/lua/vim/treesitter/dev.lua#L102

There is something funky going on with the parse tree for sure...

Before:

<img width="1552" alt="Screenshot 2023-09-19 at 7 14 59 PM" src="https://github.com/neovim/neovim/assets/5601392/97a0e9d4-df97-4a2c-b07d-cc6a908b4542">

After:

<img width="1552" alt="Screenshot 2023-09-19 at 7 17 51 PM" src="https://github.com/neovim/neovim/assets/5601392/0d16b2e7-33a4-41aa-a4a7-db096b879552">

Possibly a mismatched query. Will do some more logging

**Comment by llllvvuu** [comment]
OK, I have an idea of what's happening. When you edit the tree, `self._regions` is set to `nil`:

https://github.com/neovim/neovim/blob/c4f4c7a356013c6f1e10b7bf239d9e3c4c0c336e/runtime/lua/vim/treesitter/languagetree.lua#L910

Next time the tree is parsed, the regions will be set to `{}`:

https://github.com/neovim/neovim/blob/c4f4c7a356013c6f1e10b7bf239d9e3c4c0c336e/runtime/lua/vim/treesitter/languagetree.lua#L658-L661

Unfortunately for us, we have a convention of `{}` means the whole buffer.

In this particular case, we might be able to solve it by setting `_has_regions = false` when we set `self._regions = nil`. But that doesn't fix the precarity of the code path that leads to this bug; in particular the fact that you can update `self._regions` and `_has_regions` independently ("make illegal states unrepresentable", as they say), as well as the `{}` convention which seems easy to mess up (feels like the opposite of what `{}` should mean).

**Comment by A-Lamia** [comment]
I have currently pinned my neovim to nightly-0aojTTG3 as i have very bad lag when i type past that commit version is this also perhaps because of this ?
