### ISSUE TITLE
Unable to install HEAD on Mac OS with Homebrew

### ISSUE THREAD

**Issue by jaidetree** [neovim/neovim#25255]
### Problem

Encountering a build error trying to build the latest HEAD on Mac OS via Homebrew.

```
[  4%] Building C object src/nvim/CMakeFiles/nlua0.dir/__/mpack/lmpack.c.o
cd /tmp/neovim-20230919-96785-gra7sb/build/src/nvim && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Dnlua0_EXPORTS -I/tmp/neovim-20230919-96785-gra7sb/src -I/tmp/neovim-20230919-96785-gra7sb/build/cmake.config -I/tmp/neovim-20230919-96785-gra7sb/build/include -isystem /usr/local/include/luajit-2.1 -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -mmacosx-version-min=13.5.2 -fPIC  -Wno-conversion -Wno-missing-noreturn -Wno-missing-format-attribute -Wno-double-promotion -Wno-strict-prototypes -Wno-misleading-indentation -MD -MT src/nvim/CMakeFiles/nlua0.dir/__/mpack/lmpack.c.o -MF CMakeFiles/nlua0.dir/__/mpack/lmpack.c.o.d -o CMakeFiles/nlua0.dir/__/mpack/lmpack.c.o -c /tmp/neovim-20230919-96785-gra7sb/src/mpack/lmpack.c
make[1]: *** [src/nvim/CMakeFiles/nlua0.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- Using NVIM_VERSION: v0.10.0-dev-3721+gc4f4c7a35-Homebrew
[  4%] Built target update_version_stamp
make: *** [all] Error 2
```

### Steps to reproduce

1. Run `brew install neovim --HEAD` or `brew upgrade neovim --fetch-head`

### Expected behavior

At one point it was building just fine, the last version I built was `HEAD-74bd4ab`

### Neovim version (nvim -v)

0.9.2 c4f4c7a35

### Vim (not Nvim) behaves the same?

Unknown

### Operating system/version

MacOS Ventura 13.5.2

### Terminal name/version

kitty 0.30.0

### $TERM environment variable

screen-256color

### Installation

homebrew

**Comment by clason** [comment]
Homebrew issue; we do not maintain this.

**Comment by clason** [comment]
But try `brew uninstall lpeg; brew install lpeg`.

**Comment by jaidetree** [comment]
I see, thanks for confirming. Fortunately uninstalling lpeg and reinstalling it did the trick! 🤩

**Comment by jaidetree** [comment]
Also part of my confusion:
https://github.com/neovim/neovim/wiki/FAQ#how-stable-is-the-development-pre-release-version
> We depend on HEAD users to report "blind spots" that were not caught by automated tests.
So where should issues like this be reported?

**Comment by clason** [comment]
Neovim HEAD, not `brew install --HEAD`. If you want to help development (and that's what HEAD is for), you should build neovim from source.

**Comment by jaidetree** [comment]
Ahhh that makes more sense now. Thanks again! I'll give that a shot.
