### ISSUE TITLE
Add `toggle()` method to `vim.opt` api

### ISSUE THREAD

**Issue by Neurognostic** [neovim/neovim#25271]
### Problem

https://github.com/neovim/neovim/pull/13479 introduced the `vim.opt` Lua API. It would be a small enhancement to add a `toggle()` method to boolean options to easily invert the value.

Currently to invert a value a bit of boilerplate is required, such as defining a function like:

```lua
-- Toggle Boolean Options
-- 	scope can be:
-- 		• opt:        behaves like :set
-- 		• opt_global: behaves like :setglobal
-- 		• opt_local:  behaves like :setlocal
local function toggle_opt(opt, scope)
	scope = scope or 'opt' -- use default if no scope passed
	-- type checking
	assert(type(vim[scope][opt]:get()) == 'boolean', 'Only booleans can be toggled!')
	vim[scope][opt] = not vim[scope][opt]:get() -- invert bool
end

-- Toggle spell checking
toggle_opt('spell', 'opt_local')
```

### Expected behavior

Inverting bools could be much simpler with a `toggle()` method added to the `<metatable>` of boolean options, such as:

```lua
vim.opt_local.spell:toggle()
```

**Comment by lewis6991** [comment]
Have you tried:

```lua
vim.opt_local.spell = not vim.opt_local.spell
```

**Comment by clason** [comment]
That was years ago; the current plan is to remove that API in favor of `vim.o` and native table options.

**Comment by Neurognostic** [comment]
> plan is to remove that API in favor of vim.o and native table options.

I am confused. `vim.opt` is the native table API and `vim.o` behaves more like vimscript assignments.

Wouldn't removing `vim.opt` be removing the "native table options"?

**Comment by zeertzjq** [comment]
`vim.opt` are table options, but not native.

**Comment by clason** [comment]
No. None of these are "native"; `vim.opt` is a Lua layer mimicking table options. The plan is to implement these in the C core, at which point  `vim.o` will work with tables for free.
