### ISSUE TITLE
nvim error with `ffi` and `dlsym`

### ISSUE THREAD

**Issue by mathjiajia** [neovim/neovim#25295]
### Problem

E5108: Error executing lua /Users/jia/nvim_issue/statuscol//lua/statuscol.lua:253: dlsym(RTLD_DEFAULT, find_window_by_handle): symbol not fou
nd
stack traceback:
        [C]: in function '__index'
        /Users/jia/nvim_issue/statuscol//lua/statuscol.lua:253: in function </Users/jia/nvim_issue/statuscol//lua/statuscol.lua:247>__

### Steps to reproduce

```lua
for name, url in pairs({
	-- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
	-- some_plugin = 'https://github.com/author/plugin.nvim'
	statuscol = "https://github.com/luukvbaal/statuscol.nvim",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
require("statuscol").setup({})
```

1. save as my_issue.lua
1. `nvim --clean -u my_issue.lua`

### Expected behavior

No error

### Neovim version (nvim -v)

v0.10.0-dev-1174+g5e43a4ce4

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 14

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by mathjiajia** [comment]
cc @luukvbaal

**Comment by bfredl** [comment]
relevant: https://github.com/neovim/neovim/pull/25274

**Comment by clason** [comment]
Note: this is a prerelease version of macOS, and a prerelease version of the compiler which is known to break FFI.
