### ISSUE TITLE
`:lua vim.v.hlsearch = 0` is not the same as `:let v:hlsearch=0`

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#25294]
### Problem

Basically, the title. The Lua approach doesn't work, but Vimscript does.

### Steps to reproduce

1. Search any present word in the buffer. Say, with `/local<CR>`.
2. Execute `:lua vim.v.hlsearch = 0`. Search highlighting doesn't disappear.
3. Execute `:let v:hlsearch=0`. Search highlighting disappears.

### Expected behavior

Both approaches should act the same.

Note: this might be the consequence of a note in `:h v:hlsearch` "Note that the value is restored when returning from a function. |function-search-undo|".

### Neovim version (nvim -v)

NVIM v0.10.0-dev-0aea8fa

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.5.3-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
Vim does have this functionality, and it has this bug a well.

**Comment by echasnovski** [comment]
> Vim does have this functionality, and it has this bug a well if you `:set hlsearch`.

I was more referring to the `:lua vim.v.xxx` part.

**Comment by zeertzjq** [comment]
Yes, if you run `:lua vim.v.hlsearch = 0` in Vim it also doesn't stop search highlighting.

**Comment by echasnovski** [comment]
Thank you, Zeer!
