### ISSUE TITLE
`Missing user config file: $XDG_CONFIG_HOME/nvim/init.lua` in health check even though it's right there

### ISSUE THREAD

**Issue by Futarimiti** [neovim/neovim#25291]
### Problem

1. When running `:healthcheck nvim`, section `Configuration` complains that the user config file is missing:

    ```checkhealth
    ==============================================================================
    nvim: require("nvim.health").check()
    
    Configuration ~
    - WARNING Missing user config file: $XDG_CONFIG_HOME/nvim/init.lua
      - ADVICE:
        - :help |init.vim|
    ```
    
    ...while it lies right there:
    ```
    $ file $XDG_CONFIG_HOME/nvim/init.lua
    /Users/futar/.config/nvim/init.lua: ASCII text
    ```

2. By contrast, the warning *always* goes away when an `init.vim` was present, **even with** `init.lua` showing up at the same time:
    ```
    $ ls $XDG_CONFIG_HOME/nvim
    init.lua init.vim
    ```
    
    ```checkhealth
    ==============================================================================
    nvim: require("nvim.health").check()
    
    Configuration ~
    - OK no issues found
    ```
    As mentioned in the manual (E5422): `...It can be either Vimscript ("init.vim") or Lua ("init.lua"), but not both.`, I don't think "no issues found" should be expected.

### Steps to reproduce

1. Back up `$XDG_CONFIG_HOME/nvim` to somewhere else
2. `touch $XDG_CONFIG_HOME/nvim/init.lua` (shouldn't matter if empty or not)
3. `nvim --cmd 'checkhealth nvim'`
---
4. `touch $XDG_CONFIG_HOME/nvim/init.vim`
5. `nvim --cmd 'checkhealth nvim'`

### Expected behavior

1. No warnings should be raised 
2. A warning should be raised explaining referencing E5422

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.2/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 13.0.1

### Terminal name/version

iTerm2 3.4.20

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by justinmk** [comment]
> ```
> $ ls $XDG_CONFIG_HOME/nvim
> init.lua init.vim
> ```
> 2\. As mentioned in the manual (E5422): `...It can be either Vimscript ("init.vim") or Lua ("init.lua"), but not both.`, I don't think "no issues found" should be expected.

Nvim should already show a warning about that at startup. Does it not? (Try `nvim --clean` also.)

**Comment by Futarimiti** [comment]
@justinmk I haven't updated neovim since I opened this issue.
And even with `--clean`, the problem persists:

```
~ % nvim --version
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.2/share/nvim"

Run :checkhealth for more info
~ % trash $XDG_CONFIG_HOME/nvim
~ % mkdir $XDG_CONFIG_HOME/nvim
~ % cd $XDG_CONFIG_HOME/nvim
nvim % touch init.vim
nvim % touch init.lua
nvim % tree .
.
├── init.lua
└── init.vim

1 directory, 2 files
nvim % nvim --clean --cmd 'checkhealth nvim'
```

```checkhealth
==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found
```

**Comment by justinmk** [comment]
Oops sorry, `nvim --clean` of course won't use your config. Try just `nvim` (not `nvim --cmd ...`).

**Comment by Futarimiti** [comment]
Well, it kind of does, but not the correct error:

```
~ % nvim --version
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.2/share/nvim"

Run :checkhealth for more info
~ % tree $XDG_CONFIG_HOME/nvim
/Users/futar/.config/nvim
├── init.lua
└── init.vim

1 directory, 2 files
~ % nvim
```

Then run `:checkhealth nvim` gives
```checkhealth
==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- WARNING Missing user config file: $XDG_CONFIG_HOME/nvim/init.lua
  - ADVICE:
    - :help |init.vim|
```

Which should really be stating duplicate configs.

Meanwhile, using `--cmd 'checkhealth nvim'` on the command line gives no warnings at all:

```
==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found
```

**Comment by justinmk** [comment]
> any command passed into `--cmd`, according to the manual, will be executed _before_ processing any configs

Oh I didn't notice you were using `--cmd`. Yeah I don't see why one would do that.

Again, if you just start nvim normally (without `--cmd` or `-c`), you should see an error if both init.vim and init.lua exist.

**Comment by Futarimiti** [comment]
No, no errors were shown on startup.

![bug](https://github.com/neovim/neovim/assets/96031125/1961ef6c-910f-4d12-a0c1-03b3d94286a0)

I think at the moment we're already beyond the scope of this issue. Maybe we should open a new issue for this.

**Comment by justinmk** [comment]
> No, no errors were shown on startup.

What about `:messages`?

I suppose we could also add check in `:checkhealth`.

**Comment by Futarimiti** [comment]
> What about `:messages`?
Sorry I didn't check that; `:messages` tells nothing either when both configs are present.
