### ISSUE TITLE
Neovim errors when a file named "subprocess.py" is in the same directory where neovim is started

### ISSUE THREAD

**Issue by doppioandante** [neovim/neovim#2530]
Ditto with "logging.py", I couldn't find any other name.
I can reproduce with 158d26753371c9f9f14957b644c8f9bb9b938ef4
I'm not sure whether the bug is in the provider or the python-client.
This is what I currently get in .nvimlog, before pulling master it gave another error though:
https://gist.github.com/doppioandante/2b6530006693ea171a02

**Comment by gdrooid** [comment]
@doppioandante Check your message, you didn't paste the log.

**Comment by Pyrohh** [comment]
very straightforward to reproduce:
```
~ % touch subprocess.py
~ % nvim
Vim(if):Channel was closed by the client
Failed to load python host. You can try to see what happened by starting Neovim with $NVIM_PYTHON_PYTHON_LOG and opening the generated log file. Also, the host stderr will be available in Neovim log, so it may contain useful information.
Error detected while processing function UltiSnips#bootstrap#Bootstrap..provider#python#Call:
line    9:
E168: :finish used outside of a sourced file
Press ENTER or type command to continue
~ %
```

**Comment by equalsraf** [comment]
Seems like neovim/python-client#55
