### ISSUE TITLE
Build failing on Archlinux

### ISSUE THREAD

**Issue by cacplate** [neovim/neovim#2531]
Since about a week, the build keeps failing from conflicting types in eval.c. I didn't change any behavior as to how I build. I only do `sudo make install`. I'm on Archlinux 64bit and I build from the github repo.

**Comment by justinmk** [comment]
Need the full log.

**Comment by fmoralesc** [comment]
@fwalch mentioned elsewhere there was an issue with `jemalloc` in Arch? I've been compiling from both the AUR and github without issue, though.

**Comment by Pyrohh** [comment]
(obligatory ` git clean -fdx && make`)

**Comment by cacplate** [comment]
I forgot to add the full log, sorry.
Also, I tried removing everything and recloning the git repo and nothing changed.
https://gist.github.com/cacplate/613f4fb617ff24065d80

**Comment by Pyrohh** [comment]
Are you using GCC-5? If so, see #2090.

**Comment by cacplate** [comment]
#2090 is the exact same thing. I will close so no duplicate.
