### ISSUE TITLE
`finddir` and `findfile` returning empty strings for paths with whitespace (on Windows)

### ISSUE THREAD

**Issue by djdv** [neovim/neovim#25324]
### Problem

Screencast demonstrating the problem:
https://youtu.be/oG8lgCJjDn0

Sometime between stable 0.9.2 and the current nightly release (c88bb65) the plugin [git-messenger.vim](https://github.com/rhysd/git-messenger.vim) stopped working for me in certain directories.
After looking into it I found the offending lines to be these:
https://github.com/rhysd/git-messenger.vim/blob/8a61bdfa351d4df9a9118ee1d3f45edbed617072/autoload/gitmessenger/git.vim#L4-L5
Containing calls to `finddir` and `findfile` which return an empty string in nightly, but return a valid path in stable.
Investigating this further, I noticed that these functions return valid path strings on nightly if the working directory does not contain whitespace.

As an aside, I know this worked in a former nightly build, but I did not keep track of which commit that was, and since the CI deletes these I can't do a bisection of the binaries to find out which it was.  Sorry (；´∀｀)

### Steps to reproduce

On Windows, call `findedir` or `findfile` on a path containing whitespace. The return value should be an empty string no matter what.

### Expected behavior

A file path is returned from `finddir` and `findfile` when the argument contains the query.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-c88bb65

### Vim (not Nvim) behaves the same?

Did not check

### Operating system/version

Windows 11 25951.1000

### Terminal name/version

Microsoft Terminal (86ad3c8)

### $TERM environment variable

Not set

### Installation

GitHub release (using custom installer)

**Comment by lsvmello** [comment]
Simplified way to test:

`findfile("file.txt", fnameescape("C:\\temp\\with space\\folder"))`

Works on VIM 9.0.

**Comment by zeertzjq** [comment]
Hmm, I think the first steps is to find out which commit introduced this bug. Can anyone bisect?

**Comment by dundargoc** [comment]
881d17a11393da75a27c072faa3fd45f510175fe

**Comment by dundargoc** [comment]
Reverting [this](https://github.com/neovim/neovim/commit/881d17a11393da75a27c072faa3fd45f510175fe#diff-81ffc7d3eafdb4bb760cb3135ff730ddd79b9ef436a97d47b8f1e641ef456eabR1472) fixes the problem, although I don't know why it was changed to begin with.
