### ISSUE TITLE
Build-in function 'expand' can be affected by the gitignore file

### ISSUE THREAD

**Issue by suglow** [neovim/neovim#25333]
### Problem

If I open Neovim in a project directory that contains a .gitignore file，and
If there is a matching wildcard in my .gitignore file, it can cause the path string for the 'expand' function to return empty" is the translation of your text into English

![image](https://github.com/neovim/neovim/assets/3600041/2e904b1b-be8c-44ab-840e-b1a736e89b20)
![image](https://github.com/neovim/neovim/assets/3600041/c848fbe8-4248-4229-92d6-ec33f6d36a2f)
If I call the buildin function “expand" , it will return empty

### Steps to reproduce

1.open nvim in a project which has .gitignore
2.echo expend(...)   #Expanding a path that matches a path in .gitignore

### Expected behavior

The 'expand' function should not be affected by the ignore file

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.1692716794     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Distributor ID: Ubuntu Description:    Ubuntu 22.04.3 LTS Release:        22.04 Codename:       jammy

### Terminal name/version

windows terminal

### $TERM environment variable

screen-256color

### Installation

download from github releases

**Comment by zeertzjq** [comment]
Please create minimal steps to reproduce following https://github.com/neovim/neovim/wiki/Minimal-reproduction-template

**Comment by justinmk** [comment]
Looks like you have nvchad installed. That is missing from the steps, and has nothing to do with Nvim.

**Comment by suglow** [comment]
> Please create minimal steps to reproduce following https://github.com/neovim/neovim/wiki/Minimal-reproduction-template
> Looks like you have nvchad installed. That is missing from the steps, and has nothing to do with Nvim.

github-linguist/linguist#4039
