### ISSUE TITLE
Neovim Crashes When Opening with No Buffers Due to nvim.api.buf_get_name()

### ISSUE THREAD

**Issue by bozkayasalihx** [neovim/neovim#25338]
### Problem

When opening Neovim with no active buffers and using the Bufdired plugin (similar to Emacs Dired), the application crashes with an error message indicating that it couldn't open the current buffer.

![invalid buffer id ](https://github.com/neovim/neovim/assets/33336001/efb23dff-547e-4fd8-a911-19f01bd64363)

### Steps to reproduce

* Ensure there are no active buffers (empty Neovim session)
* Trigger Bufdired or perform actions that invoke `nvim.api.buf_get_name()`

### Expected behavior

Neovim should handle the absence of a current buffer gracefully without crashing.

### Neovim version (nvim -v)

v0.10.0-dev-304+g84378c4dd

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal Latest stable version 

### $TERM environment variable

xterm-256

### Installation

repo

**Comment by zeertzjq** [comment]
Not an Nvim issue

**Comment by lewis6991** [comment]
Lazy loading takes another casualty

**Comment by bozkayasalihx** [comment]
its not lazy loaded

**Comment by clason** [comment]
`lazyload.lua` is literally the name of the function that throws the error...
