### ISSUE TITLE
has('python3') fails after commit 7bd6bd1 (PR 25316)

### ISSUE THREAD

**Issue by mckellygit** [neovim/neovim#25340]
### Problem

has('python3') 
and
has('python')
return 0 after commit (https://github.com/neovim/neovim/commit/7bd6bd1ef7214942e94c9238e08619adf41f5995)
PR https://github.com/neovim/neovim/pull/25316

### Steps to reproduce

nvim --clean
:echo has('python3')

### Expected behavior

This used to return 1 before this commit

### Neovim version (nvim -v)

latest master

### Vim (not Nvim) behaves the same?

no, vim returns 1

### Operating system/version

ubuntu 22.04

### Terminal name/version

foot, kitty, st - does not matter

### $TERM environment variable

xterm, foot, tmux - does not matter

### Installation

build from repo

**Comment by mckellygit** [comment]
Thanks always for nvim.

**Comment by mckellygit** [comment]
Thanks!
-m

**Comment by wookayin** [comment]
Sorry for my mistake! The behavior seems different across different environments. And thanks for the fix.
