### ISSUE TITLE
{Not in Vi}

### ISSUE THREAD

**Issue by Pyrohh** [neovim/neovim#2535]
We don't care about Vi compatibility, so this seems redundant. Is there any reason to keep it?

If not, removing it shouldn't be too hard: there's 688 instances of it, the vast majority of which can be seemingly removed via search and replace.

**Comment by justinmk** [comment]
No, we always planned to remove it in 1 mega-commit. Go for it :)

**Comment by Pyrohh** [comment]
be back in 5 minutes... :D

**Comment by fmoralesc** [comment]
You will also need to remove it from the help syntax file (noticed last night because it does something I had never seen with syn region....)

**Comment by Pyrohh** [comment]
Thanks @fmoralesc, will do.
