### ISSUE TITLE
`Ctrl+o` and `Ctrl+i` behave unintuitively when deleting buffers

### ISSUE THREAD

**Issue by vE5li** [neovim/neovim#25365]
### Problem

I noticed that navigation with `Ctrl+i/o` is very weird after closing buffers that were part of the jump list.

To be honest, I'm not really sure if this is really a bug since `vim` behaves the same way and it seems to me like someone would have complained about this already if it was not intended behavior, but I couldn't find any issues or posts about this.

Regardless, this is something that really hinders my workflow (I use `oil.nvim` and every time I use it to navigate to a file it basically renders my jump list unusable) so I would really like to find a solution for my problem. 

### Steps to reproduce

I was able to reproduce this behavior with with `nvim --clean` on `0.10.0` and `stable`. I have added screenshots of the output of `:ju` in hopes of making it easier to follow.

**First case:**
- Open three buffers
![2023-09-25_16-09-1695653294](https://github.com/neovim/neovim/assets/24727270/9592ea6b-d445-4e41-81a5-266f9102a2ba)
- `Ctrl+o` to get to the second buffer
![2023-09-25_16-09-1695653276](https://github.com/neovim/neovim/assets/24727270/607c9733-69bb-4003-8024-f23b513fc185)
- `:bw` to close the buffer
![2023-09-25_16-09-1695652210](https://github.com/neovim/neovim/assets/24727270/67147d3d-9c71-47da-887b-eb36affe7452)
     - Would expect `Ctrl+i` to move to the third buffer again, instead does nothing
- Press `Ctrl+o` to move to the first buffer
![2023-09-25_16-09-1695652371](https://github.com/neovim/neovim/assets/24727270/f7b92cfe-4346-4137-b5a9-d20d7b2e8327)
    - For some reason `Makefile` is now in front of `CHANGELOG.md`
    - `:ju` shows we are looking at `Makefile` but the `CHANGELOG.md` buffer is displayed in the window
- Press `Ctrl+i`, index is now on `-invalid-`, still the wrong buffer displayed
![2023-09-25_16-09-1695652436](https://github.com/neovim/neovim/assets/24727270/be23d6ed-5fed-45bd-84fd-3ae4785bc697)
- Press `Ctrl+i` again, index is now at `CHANGELOG.md`
![2023-09-25_16-09-1695653456](https://github.com/neovim/neovim/assets/24727270/e371686c-4446-455c-a91d-74202e4f3dbe)
    - Jump list is now inverted from how it was in the beginning
    - From now on you have to press `Ctrl+o` or `Ctrl+i` twice whenever you want to move between these buffers because the first time the `-invalid-` buffer will be selected

**Second case:**
- Open three buffers
![2023-09-25_16-09-1695653294](https://github.com/neovim/neovim/assets/24727270/9592ea6b-d445-4e41-81a5-266f9102a2ba)
- `Ctrl+o` to get to the second buffer
![2023-09-25_16-09-1695653276](https://github.com/neovim/neovim/assets/24727270/607c9733-69bb-4003-8024-f23b513fc185)
- `:bw` to close the buffer
![2023-09-25_16-09-1695652210](https://github.com/neovim/neovim/assets/24727270/67147d3d-9c71-47da-887b-eb36affe7452)
- Open a fourth buffer
![2023-09-25_17-09-1695655214](https://github.com/neovim/neovim/assets/24727270/26e73acb-6d0b-4ca8-a5ac-ee7174ce8d30)
    - Original jump list entries have switched as in the first case
- Press `Ctrl+o`, goes back to the (previously first) second buffer
![2023-09-25_17-09-1695654629](https://github.com/neovim/neovim/assets/24727270/b46443e3-2937-4231-8223-696b461ddfd4)
- Press `Ctrl+o`, index is at `-invalid-` buffer
![2023-09-25_17-09-1695655446](https://github.com/neovim/neovim/assets/24727270/d3535c34-4e4e-4071-82dd-7d65fe05e36e)
- Press `Ctrl+o` again, index is at `Makefile`
![2023-09-25_17-09-1695655491](https://github.com/neovim/neovim/assets/24727270/0aef409e-8970-4254-8410-2401ab7b8d5a)
- Press `Ctrl+i`
![2023-09-25_17-09-1695655623](https://github.com/neovim/neovim/assets/24727270/e146e8c0-0096-49e6-b18d-6ee6e238e09c)
    - Moves to `README`, completely skipping the `CHANGELOG.md`
    - From now on going from `README` to `Makefile` takes three presses of `Ctrl+o` (because of the invalid buffer) but going from `Makefile` to `README` takes only one press of `Ctrl+i`

I ran into multiple variations of this behavior during normal usage, some of them even making buffers that are in the jump list completely unreachable by using `Ctrl+i/o` , but I sadly I cannot reproduce them.

### Expected behavior

I would expect 
- navigation to always be symmetric (pressing `Ctrl+o` n times followed by `Ctrl+i` n times always gets me back to where I started and vice versa) 
- invalid buffers to either be skipped by `Ctrl+i/o` or removed completely from the jump list, to avoid having to press `Ctrl+i/o` multiple times to get to the next/previous buffer

### Neovim version (nvim -v)

0.10.0 commit 1635c9e75e21e07c4331cf983e14a11c7e09b119

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Arch Linux

### Terminal name/version

foot 1.15.3

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by anhoder** [comment]
Is there an option to go back to the previous behavior (maybe I'm more used to this 😓)

**Comment by justinmk** [comment]
What behavior? You want to see "invalid" messages when jumping?

**Comment by anhoder** [comment]
before: using ctrl+o after deleting buffer will reopen the deleted
now:  will jump to another old buffer instead of reopening the deleted

**Comment by zeertzjq** [comment]
I think this can be changed to another flag of 'jumpoptions' that is enabled by default.

**Comment by paulodiovani** [comment]
+1 to revert the change and have another flag for the desired behavior, keeping compatibility with `vim`.

**Comment by Hacksore** [comment]
dropping a comment here for others, this is working on `NVIM v0.11.0-dev-608+g9d74dc3ac-Homebrew` with `jumpoptions=view`.

**Comment by zeertzjq** [comment]
Or `:set jumpoptions-=unload` (as mentioned in #29347)
