### ISSUE TITLE
LSP Hover highlighting regression?

### ISSUE THREAD

**Issue by AlphaKeks** [neovim/neovim#25366]
### Problem

I haven't updated neovim in a while and after doing so today I noticed that LSP hover windows look strange.

![image](https://github.com/neovim/neovim/assets/85143381/65f3c010-e169-4203-919f-ba5aa48f05a4)

As a reference, this is what they looked like before:

![image](https://github.com/neovim/neovim/assets/85143381/b2419396-2b47-4281-95db-55bae3540038)

There are visible code blocks in the title and highlighting in the description is lost. According to the screenshots in #25073 it should look much better than that.

Using a minimal `init.lua` with only [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) installed (since I need the parsers), it looks like this:

![image](https://github.com/neovim/neovim/assets/85143381/f1e13e50-cc56-4f9b-aadf-495ea1de4661)

### Steps to reproduce using "nvim -u minimal_init.lua"

I modified the `minimal_init.lua` a bit to include a colorscheme that doesn't hurt my eyes as well as a minimal [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) setup for the Rust and Markdown parsers.

Opening a Rust file and running `:lua vim.lsp.buf.hover()` on a symbol will open a floating window that looks worse than it did before.

Reverting to a commit before cfd4a9dfaf5fd900264a946ca33c4a4f26f66a49 "fixes" the issue.

```lua
vim.cmd.colorscheme("habamax")

--- CHANGE THESE
local pattern = "rust"
local cmd = { "rustup", "run", "stable", "rust-analyzer" }
-- Add files/folders here that indicate the root of a project
local root_markers = { "Cargo.toml" }
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd("FileType", {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ":p:h") or nil
    vim.lsp.start({
      name = "bugged-ls",
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})

require("nvim-treesitter.configs").setup({
  ensure_installed = { "rust", "markdown" },
  auto_install = true,
  highlight = { enable = true },
})
```

### Expected behavior

The highlighting should look better, or at least just as good, as before.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-cfd4a9d installed via the flake provided in `contrib/`

### Language server name/version

rust-analyzer 1.72.1 (d5c2e9c 2023-09-13)

### Operating system/version

NixOS Unstable

**Comment by clason** [comment]
Yes, this is as intended, see https://github.com/neovim/neovim/pull/25073 (and `:h news`, which is required reading after every updated).

Make sure that `conceallevel` is set in the hover window.

**Comment by AlphaKeks** [comment]
The only relevant info in `:h news` I can find for this is the following:

```
• LSP hover and signature help now use Treesitter for highlighting of Markdown
  content.
  Note that syntax highlighting of code examples requires a matching parser
  and may be affected by custom queries.
```

which isn't particularly helpful. I updated nvim-treesitter and all my parsers, am on the latest commit on master, tried removing the markdown parser from nvim-treesitter so I only have the one that ships with neovim, but it still looks like that. I don't know how NixOS would be at fault here, if anything it would be your flake. I tried copying the markdown parser from my neovim installation into `nvim-treesitter/parser/markdown.so` but it didn't change anything either, so I don't think it's a loading issue. I also tried [this](https://github.com/nvim-treesitter/nvim-treesitter/issues/4801#issuecomment-1564124267) which works, but looks even worse because now there's a bunch of empty space.

The screenshots in #25073 don't show the backticks or empty space either, so I can't imagine this is intended? If it is intended, is there any way to revert it back to how it looked before?

**Comment by clason** [comment]
It's intended (a current limitation of conceal that is actively being worked on).

And reverting is trivial: just stick to the actual release.

**Comment by ivanjermakov** [comment]
@clason is there a ticket that tracks concealing issue in LSP hover?

**Comment by ivanjermakov** [comment]
@clason v10 is out, and concealing issue is still present.

**Comment by jake-stewart** [comment]
> It's intended (a current limitation of conceal that is actively being worked on).
> 
> And reverting is trivial: just stick to the actual release.

good one

**Comment by ghe0** [comment]
I've been looking through https://github.com/neovim/neovim/issues/25718 and I can't figure how to fix the hover. I am on v0.10.0, which is live in the meantime, and LSP hover has broken syntax highlight. Is there any configuration that can be applied to fix this?
