### ISSUE TITLE
Can not detect empty buffer with nvim_buf_get_offset() or line2byte(); (behaviour changed since 0.9.2)

### ISSUE THREAD

**Issue by lucc** [neovim/neovim#25369]
### Problem

Both `nvim_buf_get_offset(0,0)` and `line2byte(line("$")+1)` can not distiguish between an empty buffer and a buffer with just one newline.

### Steps to reproduce

~~~sh
touch empty
echo > newline
printf ' ' > space
for f in empty newline space; do
  nvim --headless --clean -c 'echo bufname() nvim_buf_get_offset(0,0) line2byte(line("$")+1) "\n"' -c q $f
done
~~~
result for neovim@master:
~~~
empty 0 2
newline 0 2
space 0 3
~~~

### Expected behavior

Result for neovim 0.9.2
~~~
empty -1 -1
newline 0 2
space 0 3
~~~

### Neovim version (nvim -v)

 since b051b13

### Vim (not Nvim) behaves the same?

VIM 9.0 patches 1-1811: 
~~~
vim --clean empty newline space -c 'argdo echo bufname() line2byte(line("$")+1)'
~~~
returns 
~~~
empty -1
newline 2
space 3
~~~

### Operating system/version

Linux / NixOS

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

nix build github:neovim/neovim?dir=contrib

**Comment by lucc** [comment]
Bisecting points to b051b131f5ce99ffe1b1bc22a2032ebc886e4e35, this commit introduced the behaviour change.
Related #24930 #24944

**Comment by zeertzjq** [comment]
Related comment: https://github.com/neovim/neovim/commit/b051b131f5ce99ffe1b1bc22a2032ebc886e4e35#commitcomment-126028751

**Comment by lucc** [comment]
This does not really help because none of these functions can see a difference between an empty buffer and a buffer with just 
 a newline:
~~~sh
for param in rev=62869da11ceeb1309850fe704bae3f29724e454c rev=b051b131f5ce99ffe1b1bc22a2032ebc886e4e35; do
  echo ===== $param =====
  for f in empty newline space ; do
    nix run github:neovim/neovim?dir=contrib'&'$param -- \
      --headless --clean -c 'lua print(vim.fn.bufname(),
				       vim.api.nvim_buf_line_count(0),
				       vim.fn.line("$"),
				       vim.api.nvim_buf_get_offset(0,0),
				       vim.fn.line2byte(vim.fn.line("$")+1),
				       vim.inspect.inspect(vim.api.nvim_buf_get_lines(0,0,1,-1))
			    )' -c q $f
    echo
  done
done
~~~
~~~
===== rev=62869da11ceeb1309850fe704bae3f29724e454c =====
empty 1 1 -1 -1 { "" }
newline 1 1 0 2 { "" }
space 1 1 0 3 { " " }
===== rev=b051b131f5ce99ffe1b1bc22a2032ebc886e4e35 =====
empty 1 1 0 2 { "" }
newline 1 1 0 2 { "" }
space 1 1 0 3 { " " }
~~~

**Comment by lucc** [comment]
Currently I am using lua's io.read as a workaround, this is compatible with v0.9.2 and master
~~~lua
-- Check if the current buffer is empty
local function check_empty()
  if nvim.nvim_buf_get_offset(0, 0) <= 0 then
    local handle = io.open(nvim.nvim_buf_get_name(0))
    local eof = handle:read(0)
    handle:close()
    if eof == nil then
      return true
    end
  end
  return false
end
~~~
