### ISSUE TITLE
vim.lsp.buf.format() scrolls window on nightly

### ISSUE THREAD

**Issue by TymekDev** [neovim/neovim#25370]
Hey, I have just noticed that commit https://github.com/neovim/neovim/commit/9b9030ff2ca820d4c4f4b559f86b0f9a3496645b introduces an unexpected window scrolling. Whenever I call `vim.lsp.buf.format()` I end up with window scrolled as if I used `zb`.

https://github.com/neovim/neovim/assets/38053499/c9b4b9e6-c4ca-4f0f-b258-23849fe4c278

This appears to be affected by both `scrolloff` and window size. If the window contains fewer lines, then it does not necessarily happen.

Config for reproduction:

```lua
-- lazy.nvim bootstrap start
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
-- lazy.nvim bootstrap end

require("lazy").setup({
  {
    "neovim/nvim-lspconfig",
    config = function()
      require("lspconfig").r_language_server.setup({
        cmd = { "R", "--vanilla", "--slave", "-e", "languageserver::run()" },
      })
    end,
  },
})
```

_Originally posted by @TymekDev in https://github.com/neovim/neovim/issues/24889#issuecomment-1735020375_

**Comment by PMassicotte** [comment]
Facing the same situation:

![Peek 2023-10-28 07-09](https://github.com/neovim/neovim/assets/4519221/968e0fc8-29dd-4d60-a945-66c65dbc16f9)

**Comment by Givo29** [comment]
Hi, 

Are there any updates for this issue? I am also experiencing it and it is becoming quite disorienting when it happens after formatting on save.

**Comment by bfredl** [comment]
Some follow-up changes has been merged to the bisected PR. Please try again and see if the behavior makes sense now.

**Comment by TymekDev** [comment]
@bfredl looks good! I cannot reproduce the issue anymore.
