### ISSUE TITLE
Changing cursor shape does not work in libvte

### ISSUE THREAD

**Issue by topaxi** [neovim/neovim#2537]
Tested using gnome-terminal 3.6.2 (libvte-2.90-9 on Ubuntu 14.10)

urxvt doesn't seem to work too, see: https://github.com/neovim/neovim/issues/2475#issuecomment-95986211

**Comment by jck** [comment]
Vte only started supporting cursor shape escape codes recently. You need gnome terminal 3.16

**Comment by Pyrohh** [comment]
Assuming @jck is correct, I'll close this.

**Comment by JonathanSeguin** [comment]
Works after upgrading vte to 0.40.2 on centos7.
