### ISSUE TITLE
Errors in `on_init` and `on_attach` callbacks are not being reported to the user

### ISSUE THREAD

**Issue by A-Babin** [neovim/neovim#25375]
### Problem

Hello neovim team, thanks so much for all your hard work!

I lost a few hours trying to figure out why my lsp config wasn't being used. Turns out the init callback was throwing an error and neovim did not give any indication. 

I did some digging myself and found the problem. The `on_init` callback is called [here](https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1441). There's a `pcall` and the error is ostensibly passed off to a handler via another `pcall`, but that handler doesn't seem to exist and the return value is dropped.

Unfortunately, `pcall(nil)` doesn't throw and only returns `false, "attempt to call a nil value"`  so both errors are dropped and everyone is none the wiser. 😱 This is a good reminder that discarding the return of `pcall` is a _very bad_ idea. Too risky!

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
local pattern = 'lua'
local cmd = {'lua-language-server'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'.git', '.editorconfig'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'bugged-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings,
      on_init = function ()
        print("INIT")
        error("whoops")
      end,
      on_attach = function ()
        print("ATTACH")
        error("my bad")
      end
    })
  end
})
```

### Expected behavior

neovim should indicate somehow that an error has occurred during the callback. 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1203+g0592fd5e-dirty

### Language server name/version

lua-language-server 3.7.1

### Operating system/version

Ubuntu 20

**Comment by gpanders** [comment]
Falling back to `error()` or a `vim.notify()` if `handlers.on_error` doesn't exist seems reasonable. cc @mfussenegger.

**Comment by MariaSolOs** [comment]
I don't understand why [this line](https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1443) is even using `handlers`, since those are supposed to be indexed by LSP method names. Instead it should be using `config.on_error`.

I think it would be a good idea to move the implementation of [`dispatch.on_error`](https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1183-L1193) to a separate shared function and use it as the error handler that's used during initialization.

**Comment by wookayin** [comment]
In addition, there a few more places where errors are silently suppressed:

before_init: https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1395
on_init: https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1443
on_attach: https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1395
on_exit: https://github.com/neovim/neovim/blob/de9348978999aa78f8351b5f55930bb109e742f7/runtime/lua/vim/lsp.lua#L1223

We could have default error handlers (like a xpcall) which can show more stacktrace information via `vim.notify`.

**Comment by MariaSolOs** [comment]
@wookayin right, but do note that all the places you linked make use of handlers provided by `config`, and hence I think that if the user _really_ wants to catch/handle all errors, they can just provide them in the configuration. Hence I believe this issue is more about what a reasonable default error handler should be, since the default silent one doesn't seem appropriate (?).

**Comment by A-Babin** [comment]
[Many examples](https://www.google.com/search?q=%22local+path+%3D+client.workspace_folders%5B1%5D.name%22&rlz=1C1RXQR_enUS939US939&oq=%22local+path+%3D+client.workspace_folders%5B1%5D.name%22&aqs=chrome..69i57j33i160l5j33i299l2.703j0j7&sourceid=chrome&ie=UTF-8) of recommended lsp configs I've found online, particular from `lsp-config`,  look something like this:

```lua
require('lspconfig')["..."].setup {
  on_init = function(client)
    local path = client.workspace_folders[1].name
    -- ...
    -- merge settings into config and notify client
  end
}
```

But `client.workspace_folders` is not defined if `root_dir` isn't defined! Indexing nil throws an error, which is promptly swallowed! People trying to set up neovim with their language servers will be copy-pasting these recommended configs and they're not going to work and they will have no idea why. It will work fine with more matured configs and the minimal repro template so you guys will be left totally confused why people keep saying it doesn't work. Then people will look to blame the language servers and waste their time. I can't speak for everyone, but neovim discarding errors from a user provided callback was the last thing I expected. 

Here is some of the relevant logic:
https://github.com/neovim/neovim/blob/bfdec5b0e71991ebc0a8ad7c12d39f7a9cc56f07/runtime/lua/vim/lsp.lua#L1339-L1359

https://github.com/neovim/neovim/blob/bfdec5b0e71991ebc0a8ad7c12d39f7a9cc56f07/runtime/lua/vim/lsp.lua#L1424

It doesn't seem like a default `workspace_folders` definition was intended. Neither it nor `root_dir` is checked in the [config validation](https://github.com/neovim/neovim/blob/a66b0fdfaa35715c832b98b8941cc5673505e0c2/runtime/lua/vim/lsp.lua#L260C27-L260C27). `lsp-config` defines `root_dir` on all of their default configs, which explains the assumption that `workspace_folders` is defined, but for some reason, it appears to missing by the time the config reaches `start_client`. If I define `workspace_folders` in `setup`, that goes missing too. I assume this is happening on `lsp-config`'s end, but I went back several months of commits, and its seems to be the same story. I'm skeptical that this has gone unnoticed for so long so I feel like I am missing something, but I don't have time to dig any further right now.

**Comment by A-Babin** [comment]
I reproduced the issue with the missing `root_dir`/`workspace_folders` on a new VM and minimal setup with `lsp-config`, confirming that this affects fresh installs. 

I found that `lsp-config` [does indeed](https://github.com/neovim/nvim-lspconfig/blob/68b23c06132cb1ef8d5690111c112388fbcf1c30/lua/lspconfig/manager.lua#L145-L157) remove `workspace_folders` and `root_dir` _in single file mode_.  That code was [committed](https://github.com/neovim/nvim-lspconfig/commit/204f08ea407e4b3b7ad272287e1821f47e52d4b3) a month ago, whereas they [previously](https://github.com/neovim/nvim-lspconfig/commit/204f08ea407e4b3b7ad272287e1821f47e52d4b3#diff-9e30880c16142e9d50a64563fd1260aa9f851b782dd74678163e151b93878568L302) provided a default `workspace_folders`.

That's clearly intentional so I see no real problem there. The issue at hand remains the discarding `pcall`s. I found some in `lsp-config` as well, also on user provided callbacks. 

Can anyone explain to what reasons people might have for doing this? It's equivalent to empty catch blocks in languages with try/catch. If you used it on something you wrote and you knew exactly what errors it might throw, I could understand, but on user code? Async? In a dynamic scripting language? Forget "code smell" -- that's sabotage.  I wouldn't even do it on my own throwaway code because I guarantee I'd forget and it'd eventually ruin my day.

**Comment by MariaSolOs** [comment]
@A-Babin IMO we should continue the specific issue you're describing on a new issue filed in [`nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig), and leave this thread for better error handling during LSP initialization.

I plan on preparing a PR for it soon.

**Comment by A-Babin** [comment]
https://github.com/neovim/nvim-lspconfig/issues/2835

@MariaSolOs Thank you for taking care of it.
