### ISSUE TITLE
editorconfig: fails to parse valid comments

### ISSUE THREAD

**Issue by icholy** [neovim/neovim#25372]
### Problem

The ini parser doesn't support comments at the end of lines. For example:

``` ini
root = true ; comment
```

Outputs the following error:

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: root must be either "true" or "false"
stack traceback:
	[C]: in function 'error'
	/usr/share/nvim/runtime/lua/editorconfig.lua:14: in function 'assert'
	/usr/share/nvim/runtime/lua/editorconfig.lua:206: in function 'parse'
	/usr/share/nvim/runtime/lua/editorconfig.lua:236: in function 'config'
```

From the [spec](http://docs.editorconfig.org/en/master/editorconfig-format.html):

> Comments may be added to the ends of non-empty lines.

### Steps to reproduce

``` sh
echo "root = true ; comment" > .editorconfig
nvim --clean -u NONE .editorconfig --headless +q
```

### Expected behavior

No error.

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Vim (not Nvim) behaves the same?

no, nvim doesn't support 

### Operating system/version

Ubuntu 22.04

### Terminal name/version

alacritty 0.12.2

### $TERM environment variable

xterm-256color

### Installation

Nightly PPA

**Comment by icholy** [comment]
inline comments are not allowed by the spec since 0.15.0 https://spec.editorconfig.org/#no-inline-comments

**Comment by gpanders** [comment]
> inline comments are not allowed by the spec since 0.15.0 https://spec.editorconfig.org/#no-inline-comments

I could have sworn that was the case, but the [link in the original post](http://docs.editorconfig.org/en/master/editorconfig-format.html) threw me off. Thanks for following up.
