### ISSUE TITLE
how to get command output after command (i.e. ! operator)

### ISSUE THREAD

**Issue by rustushki** [neovim/neovim#2538]
If I run:

    :!ls

Vim will show me the contents of the current working directory.  When I hit ENTER, the results disappear.  I used to be able to hit CTRL+Z to see that output again, but now the output again in my terminal.  At some point in the last few months, this behavior changed.

How can I see the results of previously run ! commands?

**Comment by justinmk** [comment]
This is an intentional compromise. Use `:term` instead. 

https://github.com/neovim/neovim/issues/1477

https://github.com/neovim/neovim/issues/1496
