### ISSUE TITLE
'*' disappears: When the first line is % and the second line is *, use shift+j to merge a line and the * disappears.

### ISSUE THREAD

**Issue by zhenggangpku** [neovim/neovim#25382]
### Problem

When the first line is % and the second line is *, use shift+j to merge a line and the * disappears. 
eg:
![image](https://github.com/neovim/neovim/assets/18161030/e8e0183f-e5e4-46d3-ae89-6fc7c9aa9004)

In normal mode, position the cursor on the first line and press shift+j, '*' disappears.

### Steps to reproduce

%
*

### Expected behavior

The second line is merged to the end of the first line

### Neovim version (nvim -v)

v0.10.0-dev-953+g1635c9e75

### Vim (not Nvim) behaves the same?

no

### Operating system/version

docker on mac

### Terminal name/version

iterm2 v0.10.0-dev-953+g1635c9e75

### $TERM environment variable

LC_ALL=C LS_COLORS=rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45: SSH_CONNECTION=172.17.0.1 63832 172.17.0.2 22 LANG=en_US.UTF-8 HISTCONTROL=ignoredups HOSTNAME=docker_dev OLDPWD=/home/work GOPROXY=http://goproxy.intra.xiaojukeji.com GOVIM_LOG=off S_COLORS=auto which_declare=declare -f USER=work GO111MODULE=on GOPATH=/home/work/goOtherSrc PWD=/home/work HOME=/home/work GOROOT=/usr/local/go LC_CTYPE=UTF-8 SSH_CLIENT=172.17.0.1 63832 22 SSH_TTY=/dev/pts/6 MAIL=/var/spool/mail/work TERM=xterm-256color SHELL=/bin/bash GOSUMDB=off SHLVL=1 LOGNAME=work PATH=/usr/local/go/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/work/.local/bin:/home/work/bin PS1=[\[\033[31m\]\u\[\033[0m\]@\[\033[32m\]\h \[\033[33m\]\W\[\033[0m\]]$ HISTSIZE=100000 LESSOPEN=||/usr/bin/lesspipe.sh %s BASH_FUNC_which%%=() {  ( alias;  eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@" } _=/usr/bin/env

### Installation

/home/work/local/neovim/bin/nvim

**Comment by zeertzjq** [comment]
Duplicate of #16017
