### ISSUE TITLE
`nvim_buf_get_offset` returns -1 on loaded buffers

### ISSUE THREAD

**Issue by noib3** [neovim/neovim#25390]
### Problem

According to `nvim_buf_get_offset`'s docs:

> Return:
> Integer byte offset, or -1 for unloaded buffer.

But it seems to also return -1 on newly created buffers.

### Steps to reproduce

`minimal.lua`:

```lua
local buf = vim.api.nvim_create_buf(false, true)
assert(vim.api.nvim_buf_is_loaded(buf))
-- Removing the second "" or the entire line below will cause the assertion to fail.
-- vim.api.nvim_buf_set_lines(buf, 0, -1, true, { "", "" })
assert(vim.api.nvim_buf_get_offset(buf, 0) ~= -1)
```

Steps:

```
nvim -u minimal.lua
```

### Expected behavior

Calling `vim.api.nvim_buf_get_offset(buf, <line>)` on a newly created buffer returns the line's byte offset.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 13.4

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

Nix

**Comment by bfredl** [comment]
Also on master?

**Comment by noib3** [comment]
@bfredl Not sure.

**Comment by bfredl** [comment]
then this is fixed already by https://github.com/neovim/neovim/pull/24944
