### ISSUE TITLE
spellfile setting with lua doesn't work

### ISSUE THREAD

**Issue by dudozermaks** [neovim/neovim#25403]
### Problem

When I set spellfile like this:
`vim.opt.spellfile="~/.config/nvim/spell/en.utf-8.add"`
I receive an error:
E484: Can't open file ~/.config/nvim/spell/en.utf-8.add

BUT, when I do this vim-way:
`vim.cmd('set spellfile=~/.config/nvim/spell/en.utf-8.add')`
I receive no error.
Directory has all needed permissions and file exists.

### Steps to reproduce

nvim --clean
`i` woooord
`esc`
:lua vim.opt.spellfile="\~/.config/nvim/spell/en.utf-8.add"
zg
-- Receive an error
:set spellfile=~/.config/nvim/spell/en.utf-8.add
zg
-- Word 'woooord' added to ~/.config/nvim/spell/en.utf-8.add

### Expected behavior

Both solutions should work.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

no lua support in Vim

### Operating system/version

NixOS 23.05.3759.261abe8a44a7 (Stoat)

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

nix package

**Comment by clason** [comment]
You need to expand the path manually; `vim.opt` doesn't do that for you.

**Comment by dudozermaks** [comment]
Same problem when expanding

**Comment by clason** [comment]
Please update the description then.

**Comment by dudozermaks** [comment]
oh, I'm sorry, it does work... i forgot slash all the time

**Comment by magnusriga** [comment]
In case helpful to others, `vim.fs.abspath` works:

`opt.spellfile = vim.fs.abspath("~/.config/nvim/spell/en.utf-8.add")`
