### ISSUE TITLE
web: nonresponsive documentation layout on mobile

### ISSUE THREAD

**Issue by kaddkaka** [neovim/neovim#25401]
### Problem

Some text is rendered on top of other text in chrome (possibly only on narrow screens). 

### Steps to reproduce

Visit https://neovim.io/doc/user/editorconfig.html on android chrome

### Expected behavior

No overlapping text

![Screenshot_20230928-080331~2](https://github.com/neovim/neovim/assets/4508793/3eed55c6-09c3-4103-8a8e-d84d416495be)

### Neovim version (nvim -v)

-

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Android Chrome 117.0.5938.60 

### Terminal name/version

-

### $TERM environment variable

-

### Installation

-

**Comment by clason** [comment]
That's an issue with the style sheet, not the documentation itself; see https://github.com/neovim/neovim.github.io

We need a more responsive framework if we want to handle this properly.

**Comment by justinmk** [comment]
The tags look wrong, that's just a problem with that one css class.

The rest of the fixed-width layout is unavoidable unless that docs page is converted to "flow layout" ([example](https://neovim.io/doc/user/lua.html)).

**Comment by justinmk** [comment]
> The tags look wrong, that's just a problem with that one css class.

That's fixed. 

Also marked editorconfig.txt as "flow" layout, so it should wrap better.

**Comment by kaddkaka** [comment]
The layout is much better in that it does not have overlapping text 👍However the paragraph text starts squeezed in between the option name and anchor, making it still quite difficult to read, see screenshot:

![Screenshot_20241001-064730](https://github.com/user-attachments/assets/2c6fd890-99b3-46e5-a9cc-93ca520c9a4e)

**Comment by justinmk** [comment]
> the paragraph text starts squeezed in between the option name and anchor

yeah this has bugged me. https://github.com/neovim/neovim/pull/30609 should help a lot.

**Comment by kaddkaka** [comment]
Yes, looks even better now @justinmk, it's still weird to get the paragraph text on the same line as the anchor, but maybe that is the "pseudo heading" problem?

![Screenshot_20241002-134104~2](https://github.com/user-attachments/assets/9fa4d82e-103f-4542-b7eb-21d7df600d9d)

**Comment by justinmk** [comment]
> it's still weird to get the paragraph text on the same line as the anchor, but maybe that is the "pseudo heading" problem?

The 2 in the middle of your screenshot, are extreme cases because the tag name is so long. To "fix" that we would need to add more line breaks. But that should be a rare case, so better to wait until tree-sitter-vimdoc can parse this, or we change the doc source.
