### ISSUE TITLE
Docs: Explicitly mark prerelease Lua API

### ISSUE THREAD

**Issue by clason** [neovim/neovim#25416]
### Problem

Lua functions added during a development cycle are not considered stable and may change at any time before the release, not just in behavior but in name (or may vanish again altogether). However, it is not obvious from the documentation if a function is still unstable or already part of the public API (in which case renaming or removing have to go through a deprecation process). This means that you can often find them used in plugins, with the obvious effects whenever they are changed. (Prerelease versions should only be used for testing and developing, not productive use, but that's a different topic.)

This is different from the Nvim API, which has `NVIM_API_PRERELEASE` annotations.

### Expected behavior

We should explicitly mark newly-added Lua functions as "unstable" in the documentation. As the documentation is automatically generated from docstrings, so should this be.

The simplest approach would be to add an `--- @unstable` annotation and convert this in `gen_vimdoc` to a friendly (but clear) warning; as part of the release process, these annotations would then have to be removed. 

Alternatively, we could integrate the Lua API into our general API versioning (without the strong contract about not removing functions before 2.0, of course) and use the same `NVIM_API` annotations for them (including `FUNC_API_SINCE`, `FUNC_API_DEPRECATED_SINCE`, etc.?) so we could use the same automation as for the C documentation. This would imply (not necessarily, but in practice), that the API version would be bumped at each minor release instead of the first time an `nvim_foo` API function is added.

This would probably be a bit more work to set up, but versioning the Lua API is something we'll need to do for Nvim 1.0 anyway, and there's no reason we can't start earlier.

**Comment by justinmk** [comment]
Either way sounds good but we definitely want this to be programmatic, not manually maintained in the docs.

But `@since` seems better than `@unstable` because it can be used to indicate both "unstable/experimental" as well as "when was this function first released?"

```
@since unstable
@since 0.1.2
```

**Comment by clason** [comment]
That would be the point of the second proposal: `@since 12` would mark this as "unstable" until API level 12 is released (at which point it would automatically not be marked anymore) -- this would be fully controlled by the `NVIM_API_*` in our top `CMakeLists.txt`. (To be clear: the second proposal -- which was @bfredl's -- is to use our Nvim API version numbering for this, _not_ a separate (Neovim version) counter.)

**Comment by llllvvuu** [comment]
> `--- @since unstable`

Does `--- @since 999999` work for this?

**Comment by clason** [comment]
No, we want to use the `NVIM_API_LEVEL` for this, since we already have tooling for that in our release script. 

Follow-up work could mark prerelease Nvim API in our docs in the same way.

**Comment by llllvvuu** [comment]
Ah I misunderstood, I thought Justin was suggesting "make a function that doesn't go into the next release i.e. is unstable indefinitely". My bad.

**Comment by clason** [comment]
Ah, ok, I don't think we want/need to do that. If a Lua function is in a release, it is stable -- in the sense that breaking changes go through a deprecation cycle. It's just that pre-release, we can make any changes to a new function we want, without any heads-up. (Or, rather, the point of this proposal is to add an "unstable" warning as a heads-up.)

"Experimental" API (like `vim.ui_attach` or `vim.treesitter`, to some extent) is treated individually.

**Comment by llllvvuu** [comment]
> that the API version would be bumped at each minor release
> ...
> This would probably be a bit more work to set up

Maybe could be automated in `release.yml` by checking `HEAD`'s `NVIM_API_LEVEL` is less than `master`'s `NVIM_API_LEVEL`? Although it would maybe be noisy if we make minor version bumps that aren't API upgrades, e.g.

> Minor version Y ... MAY be incremented if substantial new functionality or improvements are introduced within the private code.

(although I don't personally know what that means 🤔)

**Comment by clason** [comment]
>  Maybe could be automated in release.yml

No, because the changes need to happen in the code, so it has to be a proper ("bump release") commit.

@bfredl can explain better what he does for the Nvim API, which should be extended to the Lua API.

**Comment by justinmk** [comment]
> If a Lua function is in a release, it is stable -- in the sense that breaking changes go through a deprecation cycle

I don't agree. We need a way to signal "experimental", that is why I suggested `@since unstable` (spiritually equivalent to `@since 9999`).

**Comment by clason** [comment]
Yes, which is why I mentioned those explicitly in the last paragraph. (Since we need to manually mark them as stable, I don't see much value in automation here. MVP only needs to cover the standard situation of new functions.)

**Comment by justinmk** [comment]
> Since we need to manually mark them as stable, I don't see much value in automation here

Hmm, that could work if we _required_ `@since`, and thus auto-generated docs marked everything that _lacks_ a `@since` attribute as "experimental". Having some explicit signal about experimental things will be helpful. Could eventually, also, be programmatic (so `:checkhealth` could warn about the use of experimental features).
