### ISSUE TITLE
bug: buf 1 gets no ft if buf 2 created with ft in `BufReadPost`

### ISSUE THREAD

**Issue by llllvvuu** [neovim/neovim#25436]
### Problem

Opening `hello_world.lua` before repro:
```
:b 1
:set ft?
  filetype=lua
```

after repro:
```
:b 1
:set ft?
  filetype=
:b 2
:set ft?
  filetype=notify
```

([Original source](https://github.com/rcarriga/nvim-notify/blob/e4a2022f4fec2d5ebc79afa612f96d8b11c627b3/lua/notify/service/buffer/init.lua#L103))

Apologies if this is intended behavior.

### Steps to reproduce

`repro.lua`:
```lua
function separate_buf()
  local buf = vim.api.nvim_create_buf(false, true) -- args here don't matter
  vim.api.nvim_set_option_value("filetype", "notify", { buf = buf })
end

vim.api.nvim_create_autocmd("BufReadPost", { -- no issue with BufReadPre or BufEnter
  pattern = "*",
  command = 'lua separate_buf()',
})
```

```sh
vim --clean --noplugin -u repro.lua
```

```vim
:e hello_world.lua " contents of file don't matter, but must be opened with :e
```

### Expected behavior

For filetype of `hello_world.lua` buffer to be `lua`

### Neovim version (nvim -v)

0.10 nightly `5f2d0b932`

### Vim (not Nvim) behaves the same?

couldn't figure out the right equivalent of `nvim_create_buf` + `nvim_set_option_value`

### Operating system/version

macOS 13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by zeertzjq** [comment]
This looks tricky. Repro in Vim script:
```vim
let b1 = bufnr()
new
autocmd BufReadPost * call setbufvar(b1, '&filetype', 'notify')
```
Also reproducible in Vim.

**Comment by zeertzjq** [comment]
Workaround: run `:filetype plugin on` in config before the autocommand is defined.
