### ISSUE TITLE
`vim.cmd.confirm()` always return an error 

### ISSUE THREAD

**Issue by jerome-pouiller** [neovim/neovim#25447]
### Problem

`vim.cmd.confirm()` always return an error 

### Steps to reproduce

The code below work properly:

    :lua vim.cmd('confirm quit')

However, if you cal this one:

    :lua vim.cmd.confirm('quit')

... you get:
```
E5108: Error executing lua [string ":lua"]:1: Vim:E476: Invalid command
stack traceback:
        [C]: in function 'confirm'
        [string ":lua"]:1: in main chunk
```

### Expected behavior

`vim.cmd('confirm quit')` and `vim.cmd.confirm('quit')` should produce the same result

### Neovim version (nvim -v)

v0.8.2

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

Debian bookworm

### Terminal name/version

konsole

### $TERM environment variable

xterm-256colors

### Installation

Debian package

**Comment by seandewar** [comment]
`:confirm` is a command modifier, so it should be specified as`vim.cmd.quit{mods={confirm=true}}`.

**Comment by jerome-pouiller** [comment]
The documentation is a bit difficult to find. Maybe documentation of vim.cmd() should point to https://neovim.io/doc/user/map.html#%3Cmods%3E

Anyway, thank you.
