### ISSUE TITLE
balloon-eval included?

### ISSUE THREAD

**Issue by donnut** [neovim/neovim#2544]
I tried to set the `ballooneval` option but neovim doesn't seemed be be compiled with the `balloon_eval` option. Is that correct and how can I solve this?

**Comment by Shougo** [comment]
I think this is GUI related feature and it is already removed in neovim.

**Comment by justinmk** [comment]
Right, but we should implement a text-only version of this.

**Comment by Tehnix** [comment]
This would be a very nice feature to compliment Neovim, and bring it closer to the IDE feature set. You currently often see it used for type information on hover in other editors.

One thing I was wondering, as far as I remember it only activated on mouse hover, is the text-only version intended to be able to activate via e.g. cursor location?

**Comment by Shougo** [comment]
Related project?
https://github.com/neovim/neovim/pull/6619

**Comment by hasufell** [comment]
> I think this is GUI related feature and it is already removed in neovim.

And I find no reasoning for that.

> Related project?

I don't understand from the PR whether that will enable easy tooltips for GUIs.

**Comment by bfredl** [comment]
#6619 is a bit low-level, we probably want an abstraction for hover info on top of it. (Which very well can be runtime and not more C code)

**Comment by bfredl** [comment]
Also nothing has been removed, rather no one has put forward the interest to port the vim patches for `termballoneval`

**Comment by tterranigma** [comment]
BTW, the fact that balloons are removed is not reflected in the vim-differences help.

**Comment by justinmk** [comment]
## Plan

Now that floating windows are included, there is zero need for the old, awkward, unreliable "balloon" feature. We will focus on making floating windows easier to use instead ("popup API").

**Comment by justinmk** [comment]
float (popupe) windows are well supported in Nvim 0.5

**Comment by bfredl** [comment]
#9534 is the only missing feature and tracked as such
