### ISSUE TITLE
Keeps getting "parse error near `\n'"

### ISSUE THREAD

**Issue by SuXYMC** [neovim/neovim#25445]
### Problem

So, one day, I tried to config nvim with vim script (~/.config/nvim/init.vim) by myself, and ended up getting "init.vim:2: parse error near \`\n'" for an afternoon when I tries to do "source init.vim". I've got no idea about this issue, and looking for help. 
the init.vim I wrote that runs into this bug: 
[init.vim.zip](https://github.com/neovim/neovim/files/12774850/init.vim.zip)
```imap jk <Esc>
nmap <Space> :
set number
set showmatch
set encoding=utf-8
set fenc=utf-8
set mouse=a
set tabstop=2
set expandtab
set scrolloff=5
set hlsearch
set paste
```

### Steps to reproduce

1. install neovim
2. write the code given into ~/.config/nvim/init.vim 
3. run "source ~/.config/nvim/init.vim" in your shell

### Expected behavior

give back something like: 
``init.vim:2: parse error near '\n'``

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

yes, vim 9.0.1313

### Operating system/version

macOS 12.6.7

### Terminal name/version

iTerm 3.4.20

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by clason** [comment]
`init.vim` is a config file that is read by Neovim during startup; you don't source it from the shell.

**Comment by SuXYMC** [comment]
anyway, the second line works(although it send error), but the first line doesn't

**Comment by SuXYMC** [comment]
well, seems the issue isn't there when I used the backup of my older config
