### ISSUE TITLE
macOS 14.0 build failure

### ISSUE THREAD

**Issue by snowmang1** [neovim/neovim#25450]
### Problem

I am using home-brew to manage my neovim instance and the build keeps failing just after I updated to macOS Sonoma 14.0.
the command I am using is:
```brew install neovim --head```
The output can be seen in this [video](https://asciinema.org/a/611344). (apologies for me trying to remember how to use asciinema.

I did see a [commit](https://github.com/neovim/neovim/pull/25448) related to this issue but it looked like it was thought to be resolved.

### Steps to reproduce

given that you are on macOS Sonoma 14.0
```brew rm neovim```
```brew install neovim --head```

### Expected behavior

the expected behavior is for brew to successfully install neovim nightly.

### Neovim version (nvim -v)

nightly 9.0.1964, commit: 248305c

### Vim (not Nvim) behaves the same?

no, vim 9.0.1966

### Operating system/version

macOS 14.0

### Terminal name/version

warp v0.2023.09.26.08.09.stable_00, iterm2 3.5.0beta14

### $TERM environment variable

xterm-256color

### Installation

brew, manual install and build

**Comment by zeertzjq** [comment]
Search existing issues
