### ISSUE TITLE
:Man caches buffer width

### ISSUE THREAD

**Issue by heroin-moose** [neovim/neovim#25457]
### Problem

For some reason `Man()` caches the buffer width after the first command invocation. This results in a scrambled output on a subsequent calls with different buffer width:

`:Man fnmatch`:
![image](https://github.com/neovim/neovim/assets/15263497/404f63b4-a939-42f0-a0ea-29e0e6fcc28d)

`:vertical Man fnmatch`:
![image](https://github.com/neovim/neovim/assets/15263497/45290679-af01-44ef-b9fe-394e9b43b6fe)

### Steps to reproduce

```
nvim --clean
:Man fnmatch
:close
:vertical Man fnmatch
```

### Expected behavior

`:vertical Man fnmatch`:
![image](https://github.com/neovim/neovim/assets/15263497/4a456ec0-39f1-4216-86b7-10b23ccbb4c2)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1257+g9b3045103f

### Vim (not Nvim) behaves the same?

Different plugin

### Operating system/version

Arch Linux

### Terminal name/version

foot 1.15.3

### $TERM environment variable

foot

### Installation

AUR

**Comment by zeertzjq** [comment]
Vim's Man plugin has `bufhidden=hide` as well:
https://github.com/vim/vim/blob/6ee7b521fa7531ef356ececc8be7575c3800f872/runtime/autoload/dist/man.vim#L213

**Comment by heroin-moose** [comment]
Yeah, seems like the root cause. Calling `:Man` width different arguments works as intended.

**Comment by justinmk** [comment]
I don't see "scrambled output" unless you mean the header, which is a minor detail. The default behavior is that the manpage is soft-wrapped, which looks like it's working ok.

**Comment by heroin-moose** [comment]
Yeah, I should've post the table right away:

![image](https://github.com/neovim/neovim/assets/15263497/72f1b29b-f08d-42cd-8efe-f40ff060c613)

**Comment by justinmk** [comment]
That's indeed because the soft-wrapping fails on ascii art. You can opt-out of soft-wrapping via:

    let g:man_hardwrap=1

> If changing the use of 'bufhidden' fixes something, PR welcome.

Still interested in this if there is an easy win here.

**Comment by heroin-moose** [comment]
But it works okay if I just do `:vertical Man fnmatch`.

**Comment by heroin-moose** [comment]
> Still interested in this if there is an easy win here.

Just commenting this option gives me weird results. I'll try to set it to something else.

**Comment by heroin-moose** [comment]
Yep, `bufhidden = unload` works.

**Comment by heroin-moose** [comment]
I'll make a PR later.
