### ISSUE TITLE
clipboard: wl-copy: don't run with `--foreground`

### ISSUE THREAD

**Issue by eNV25** [neovim/neovim#25466]
### Problem

Starting wl-copy with `--foreground` causes https://sw.kovidgoyal.net/kitty/ to hang after the shell exits.

This happens because kitty waits for all processes connected by stdio to die, before it closes. Starting wl-copy with `--foreground` does not redirect stdio to `/dev/null`.

This can be fixed by removing `--foreground` from the wl-copy section in `runtime/autoload/provider/clipboard.vim`.

### Steps to reproduce

\# use kitty terminal emulator in wayland
nvim --clean
\# copy stuff with "+
:q
\# exit shell with CTRL-D

### Expected behavior

Terminal exits.

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.1694285958     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

Arch Linux

**Comment by zeertzjq** [comment]
Related #24470

**Comment by zeertzjq** [comment]
cc @ainola

**Comment by eNV25** [comment]
> Related #24470

No that's not related. In that case neovim hangs, in this case kitty hangs.

**Comment by eNV25** [comment]
The following `init.lua` file makes it work correctly:
```lua
-- init.lua
if vim.env.WAYLAND_DISPLAY and vim.fn.executable("wl-copy") and vim.fn.executable("wl-paste") then
  vim.g.clipboard = {
    name = "wl-copy",
    copy = {
      ["+"] = { "wl-copy", "--type", "text/plain" },
      ["*"] = { "wl-copy", "--primary", "--type", "text/plain" },
    },
    paste = {
      ["+"] = { "wl-paste", "--no-newline" },
      ["*"] = { "wl-paste", "--no-newline", "--primary" },
    },
  }
end
```
```sh
nvim -u init.lua
```

It's the same as in `runtime/autoload/provider/clipboard.vim` but with `--foreground` removed.

**Comment by eNV25** [comment]
@zeertzjq Can I just send a patch?

**Comment by zeertzjq** [comment]
I wanted wait for an some information from @ainola on why `--foreground` was added.

**Comment by ainola** [comment]
Thanks for soliciting my feedback! I had put --foreground in the patch 
for no particular technical reason IIRC - As long as testing doesn't 
break it I don't imagine there's an issue with removing the foreground.
