### ISSUE TITLE
Regression: in diff mode PageUp does not scroll upward when there are many removed lines

### ISSUE THREAD

**Issue by e-kwsm** [neovim/neovim#25479]
### Problem

In diff mode, <kbd>PageUp</kbd> does not scroll upward if the cursor is located below many deleted lines (almost twice as long as the terminal height?).
This bisects to 88d13d2778a4fab3fdcc2bf4c1adf631b38ea3ce (#23320).

### Steps to reproduce

Set the terminal size to 80×24.
Prepare the files:
```shell
> a python3 -c 'print("\n".join(["^^^"] * 2 + ["$$$"] * 2))'
> b python3 -c 'print("\n".join(["^^^"] * 2 + ["###"] * 42 + ["$$$"] * 2))'
```

(The issue happens when `b` has 41 or more `###` lines)
Open the files in diff mode:

```
nvim -d --clean a b
```

Go to the bottom (<kbd>G</kbd>) and then try to scroll up (<kbd>PageUp</kbd>)&mdash;the cursor does not move from the 3rd line. <kbd>k</kbd> works as expected.

![PageUp](https://github.com/neovim/neovim/assets/11627708/bceb62ba-f3a9-430e-addc-49cc63d35f08)

### Expected behavior

<kbd>PageUp</kbd> scrolls upward and the cursor goes to the 2nd line.

### Neovim version (nvim -v)

v0.10.0-dev-1264+geb1f0e8fcca7

### Vim (not Nvim) behaves the same?

no, vim 9.0.1969

### Operating system/version

EndeavourOS

### Terminal name/version

GNOME Terminal 3.48.2 using VTE 0.74.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256cololr

### Installation

build from repo

**Comment by zeertzjq** [comment]
Workaround `:set scrolloff=1`

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/move.c b/src/nvim/move.c
index dd9737ede..3fdbe447e 100644
--- a/src/nvim/move.c
+++ b/src/nvim/move.c
@@ -82,9 +82,6 @@ static int plines_correct_topline(win_T *wp, linenr_T lnum, linenr_T *nextp, boo
   if (lnum == wp->w_topline) {
     n -= adjust_plines_for_skipcol(wp);
   }
-  if (n > wp->w_height_inner) {
-    return wp->w_height_inner;
-  }
   return n;
 }
 
```

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/move.c b/src/nvim/move.c
index dd9737ede..dcafdd607 100644
--- a/src/nvim/move.c
+++ b/src/nvim/move.c
@@ -2455,6 +2455,7 @@ int onepage(Direction dir, long count)
           if (curwin->w_topfill == loff.fill) {
             curwin->w_topline--;
             curwin->w_topfill = 0;
+            curwin->w_valid &= ~VALID_CROW;
           }
           comp_botline(curwin);
           curwin->w_cursor.lnum = curwin->w_botline - 1;
```
