### ISSUE TITLE
vim_err_write might ask "Press ENTER" in the middle of an (async) message

### ISSUE THREAD

**Issue by bfredl** [neovim/neovim#2547]
In a python remote plugin, I wanted to echo traceback on error also from notification handlers. However, when `nvim` recieves `vim_err_write` asynchronously, sometimes, the message is split on every newline, except for the first one. I e
```
import neovim
vim = neovim.attach(...)
vim.err_write("1\n2\n3\n4\n")
```
(from an external python) gives
```
1 
2 
Press ENTER or type command to continue 
3
Press ENTER or type command to continue  
4     
Press ENTER or type command to continue
```
While, a err_write during a blocking request, for instance `:python vim.err_write("1\n2\n3\n4\n")` works as expected (one single interrupt).
 It seems, `emsg()` is very dependent on the "context" of the error to group several messages (and `vim_err_write` must currently split each line to `emsg()`), and during an async event this context is not well defined.

**Comment by bfredl** [comment]
And yes, passing a NL to `emsg()` prints a `^@`.

**Comment by justinmk** [comment]
This is related to https://github.com/neovim/neovim/pull/1802 which I rebased a few days ago. We can provide an internal mechanism (maybe a user-facing option *later*) that disables "Press ENTER" unconditionally. In the current state, it requires[1] [setting a few different flags](https://github.com/neovim/neovim/pull/1802/files#diff-751db613ff406b06a6fab61b0159ca06R160) which may have side effects. 

[1] If someone knows a flag that already exists, I'm happy to be corrected.

**Comment by bfredl** [comment]
With the notation of #1802 you mean all lines but the last should be echoed "passive"? I also thought of, when handling a request, the event logic could detect when handling a request outside of any user action/vimscript, and setup the context correctly, so that all messages from the same API call get displayed at once, but I don't know this part of the code to be sure that makes sense...
There seems to be similar issue in the reverse case, when doing `vim.eval("2+nonexistingvariable")`, it only throws the "failed to evaluate expression" line, and the "E121: Undefined variable" is just lost (not in `:messages` or anywhere)

**Comment by splinterofchaos** [comment]
@mhinz also noted on gitter a problem running unit tests after #1446 due to a unit test I added. It turned out that he receives a warning message every time he starts nvim. Not having an associated GUI, he had little way of knowing this.

It just occured to me that if we have nvim broadcast a notification to all clients that they must `"Press Enter to continue"`, we could configure them to reply with `vim('vim_feedkeys', '\<Cr>')`. There may be times when we want to disable that functionality, but in general it could protect processes without attached GUI's from becoming frozen.

**Comment by bfredl** [comment]
not "Press Enter to continue", but a similar case of blocking before displaying message, when using `a.vim` (jumping `.c` -> `.h` and such), when opening an alternative file (not loaded yet) that has a swap file, `nvim` blocks in the "Found a swap file ... [O]pen Read-Only, ..." state, before this message is actually displayed.

**Comment by justinmk** [comment]
@bfredl Isn't that a bug in a.vim? (btw, https://github.com/tpope/vim-projectionist is a nice alternative to a.vim)
