### ISSUE TITLE
vi_diff.txt

### ISSUE THREAD

**Issue by mreed1** [neovim/neovim#2548]
copied from Gitter:

> Does anyone find it useful? We don't care about vi compatibility, so I'm skeptical.

**Comment by glts** [comment]
Doesn't seem useful to me.

In any case, before deleting this file we should go through it and extract a list of to-dos. For example, I did not know that there was an option `'beautify'`. As `vi_diff.txt` says, that option is not implemented -- but there's still a reference to it in the code. That code needs to go, too.

**Comment by splinterofchaos** [comment]
Also, as I said on gitter:
> I think most neovim users are/will be ex-vim and new-to-vim users, but someone who still uses vi probably won't use neovim.

**Comment by Pyrohh** [comment]
Since this was opened a while ago, I'm going to get started on trimming this down.
