### ISSUE TITLE
More bugs while trace my last issue 'The code of neovim can't be parsed by neovim completely'

### ISSUE THREAD

**Issue by bruce-the-terrible** [neovim/neovim#25486]
### Problem

nvim can't find files in hidden directories

### Steps to reproduce

git clone https://github.com/neovim/neovim
cd neovim && make CMAKE_BUILD_TYPE=Release
nvim （config as git clone https://github.com/LazyVim/starter ~/.config/nvim）
open src/nvim/lua/converter.c
cursor on lua_toltring and type gd , trying 'jump to implementation of lua_tolstring' failed
----------------------------------
so ,let's goes a little more
I write a script like below , generate a fake compile_commands.json , which includes files in hidden directories and make neovim and lsp happy . In this file , all *.c in hidden directory .deps are listed . (lj_api.c and miniua.c)

now ,run nvim in ~/neovim/ 
cursor on lua_toltring and type gd ,  nvim jump to lj_api.c , an implementation of lua_tolstring()

but :
1. another implementation in minilua.c is ignored
2.use telescope.nvim find files , both lj_api.c and minilua.c can't be found
3.type gr on lua_tolstring ,  lsp can find references of lua_tolstring in minilua.c , select one of them , open minilua.c . Format code use gg=G ，nvim stops responding .
 
There are too many exceptions to say 'not my fault' .

----------------
```
#!/bin/zsh
filename="xmake.lua"
projectname="fake_xmake"
rm -rf $filename
rm -rf compile_command.json
touch $filename
touch .git
#echo "set_project(\"$1\")" >> $filename
echo "set_project(\"$projectname\")" >> $filename
echo "set_xmakever(\"2.7.9\")" >> $filename
echo "set_version(\"1.0.0\")" >> $filename
#echo "  target(\"$1\")" >> $filename
echo "  target(\"$projectname\")" >> $filename
echo "      set_kind(\"binary\")" >> $filename
echo "      set_targetdir(\"./build\")" >> $filename

#echo "      add_files(\"./**.c\")" >> $filename
#echo "      add_files(\"./**.s\")" >> $filename
#echo "      add_files(\"./**.cpp\")" >> $filename
#echo "      add_files(\"./**.cxx\")" >> $filename
find . -iname "*.c" |\
    xargs -o dirname |sort|uniq|\
    while read dir_name ;do 
        echo "      add_files(\"$dir_name/**.c\")";
    done >> $filename
find . -iname "*.cc" |\
    xargs -o dirname |sort|uniq|\
    while read dir_name ;do 
        echo "      add_files(\"$dir_name/**.cc\")";
    done >> $filename
find . -iname "*.cpp" |\
    xargs -o dirname |sort|uniq|\
    while read dir_name ;do 
        echo "      add_files(\"$dir_name/**.cpp\")";
    done >> $filename
find . -iname "*.s" |\
    xargs -o dirname |sort|uniq|\
    while read dir_name ;do 
        echo "      add_files(\"$dir_name/**.s\")";
    done >> $filename
# add header path
find . -iname "*.h" -o -iname "*.hpp" -o -iname "*.hxx" |\
    xargs -o dirname |sort|uniq|\
    while read dir_name ;do 
        echo "      add_includedirs(\"$dir_name\")";
    done >> $filename
# create compile_commands.json
xmake project -k compile_commands
```

### Expected behavior

I don't know
There are too many exceptions

### Neovim version (nvim -v)

0.9.2 with lazy starter config

### Vim (not Nvim) behaves the same?

not practic in vim

### Operating system/version

macos 14

### Terminal name/version

iterm2

### $TERM environment variable

xterm-new

### Installation

brew install neovim

**Comment by clason** [comment]
Not a Neovim bug. Please stop opening these "issues"; if you want help setting up tooling for Neovim dev, reach out on Matrix.
