### ISSUE TITLE
vim.fn.simplify not resolving some paths

### ISSUE THREAD

**Issue by lawrence-laz** [neovim/neovim#25504]
### Problem

`vim.fn.simplify` seems to work inconsistently with different addresses.

### Steps to reproduce

1.1. macOS ❌
```vim
:lua =vim.fn.simplify'/Users/llaz/git/neotest-zig/lua/neotest-zig/init.lua/../../../zig/neotest-runner.zig'
/Users/llaz/git/neotest-zig/lua/neotest-zig/init.lua/../../../zig/neotest-runner.zig
```
1.2. Windows ✅
```vim
:lua =vim.fn.simplify'C:/dev/git/neotest-zig/lua/neotest-zig/init.lua/../../../zig/neotest-runner.zig'
C:/dev/git/neotest-zig/zig/neotest-runner.zig
```

### Expected behavior

Path would be simplified in both cases.

### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

-

### Operating system/version

macOS 13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

screen-256color

### Installation

homebrew

**Comment by justinmk** [comment]
works for me on macOS with nvim 0.10 f9b9f62796aa
