### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#2551]
Currently, :python launches python2 and :python3 launches python3. I suggest this : 
:python2 -> python2
:python3 -> python3
:python -> latest version (python3 for  now)
With this change, a user/plugin writer can choose which version to use, with a default to the latest. Python 3 has been released for seven years now, most libraries support it I think. It's time to make it the default.

**Comment by Shougo** [comment]
No.  Because, it breaks plugin compatibilities.

**Comment by Yamakaky** [comment]
At least :python2 could be implemented ? It would help plugin writers to choose the version they need, partially solving the compatibility problem.
I understand the compatibility problem. So we are stuck to an obsolete version by default ? Even in 200 years, when python5 is out ? The problem is the same for others language. I think that for all of them we should put symlinks for every major version, and a version-less command which points to the latest.

**Comment by Shougo** [comment]
> At least :python2 could be implemented ? It would help plugin writers to choose the version they need, partially solving the compatibility problem.

It can be implemented.  But it is not useful.  It is waste of time.
If plugin authors use `:python`(Python2), they don't want to maintain it to support latest Python version(Python3).
Why they want to use command `:python2` instead of `:python3`?
If you want to add `:python2`, you should request it in vim_dev at first.

> Even in 200 years, when python5 is out ?

I think if Python breaks compatilibities again, Python language is disapearred(see Python2-Python3 confusion).

**Comment by bfredl** [comment]
The trouble is, in _vim_, either all python plugins must me py3, or none must be, so it is hard to port just a single plugin, as a "pure" python3 is not easily usable with other plugins (rather it must support both versions for a long time still). This problem disappears with nvim, so we could encourage "new style" plugins to be python3, whenever reasonable. However, while I do think python3 is the ~~future~~present, changing the naming at this point will just be confusing. (either it will be breaking, or inconsistent)

In 200 years, we hopefully program by telepathy or something...

**Comment by Yamakaky** [comment]
You don't think it's a good idea to be able to explicitly choose the version you support ? Changes happens (btw, python did a good job, see 2to3 and dual version compatibility), so we should give stability to plugin devs and up-to-dateness (??? ^^) to the users.

**Comment by bfredl** [comment]
IIRC `pythonx/` is already used to denote a package that is dual version compatible.

**Comment by Yamakaky** [comment]
I don't know this prefix.
BTW, this discussion apply also the other scripting languages, not only to python.

**Comment by tomprince** [comment]
From [PEP-0394](https://www.python.org/dev/peps/pep-0394/#recommendation):

> In order to tolerate differences across platforms, all new code that needs to invoke the Python interpreter should not specify python , but rather should specify either python2 or python3 (or the more specific python2.x and python3.x versions; see the Migration Notes ). This distinction should be made in shebangs, when invoking from a shell script, when invoking via the system() call, or when invoking in any other context. 

That probably isn't directly applicable, but suggests that, even if it is redundant, the version should be specified for new code.

**Comment by fwalch** [comment]
We can't change `:python`, because Vim plugins expect it to be Python 2. We could introduce `:python2`, but as long as Vim doesn't do the same, it won't be of much use.

**Comment by tomprince** [comment]
Certainly it doesn't make sense to remove `:python` (nor does a reading of PEP-0394 suggest that). Regarding adding `:python2`, I think you are perhaps too modest.

**Comment by addisonamiri** [comment]
I agree that `:python` can't be changed at this point without breaking major plugin compatibility but what about other languages. I think the standard should be `:languageX` where X is the version number (possibly using /usr/bin/env for this) with `:python` being the only anomaly.

**Comment by fwalch** [comment]
Not sure if we'll even introduce commands (`:languageX`) for more languages, as [remote plugins](http://neovim.io/doc/user/remote_plugin.html) can be implemented without Neovim knowing about which language they're written in.

**Comment by fmoralesc** [comment]
@fwalch I think at least `:ruby` or `:lua` should be implemented, for backwards compatibility with vim plugins.

**Comment by fwalch** [comment]
@fmoralesc :+1:
