### ISSUE TITLE
bug: `open_floating_preview` position doesn't take into account border

### ISSUE THREAD

**Issue by llllvvuu** [neovim/neovim#25521]
### Problem

w/o border:
<img width="1508" alt="Screenshot 2023-10-06 at 3 54 57 AM" src="https://github.com/neovim/neovim/assets/5601392/d53c1eee-94c7-43a2-bb67-ea514565b590">

w/ border:
<img width="1552" alt="Screenshot 2023-10-06 at 3 57 57 AM" src="https://github.com/neovim/neovim/assets/5601392/db78f2b6-091c-48cf-bb52-4337ceb496ff">

Seems like we just need to add an offset for border width. There's some similar logic in nvim-cmp that handles this correctly.

### Steps to reproduce

No minimal config yet, but it involves

```lua
vim.lsp.handlers["textDocument/hover"] =
  vim.lsp.with(vim.lsp.handlers.hover, {
    border = "single",
  })
```

I was thinking of looking at this myself, but if I don't get around to that then I'll post a full minimal config

### Expected behavior

Floating window should not cover cursor

### Neovim version (nvim -v)

f67517bba

### Vim (not Nvim) behaves the same?

no floating windows i think

### Operating system/version

macOS 13.4.1

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by glepnir** [comment]
need add border height check `local border_height = get_border_size(opts).height` in `_make_floating_popup_size`
