### ISSUE TITLE
Writing any file results in E1509: Error occured when reading or writing extended attribute

### ISSUE THREAD

**Issue by UrNightmaree** [neovim/neovim#25524]
### Problem

Writing any file results in error `E1509: Error occured when reading or writing extended attribute`.

Related to vim/vim#13246 issue.

### Steps to reproduce

nvim foo

### Expected behavior

Successfully writing the file without an error.

### Neovim version (nvim -v)

v0.10.0-dev-1261+g 09a17f91d

### Vim (not Nvim) behaves the same?

No, 9.0.1976

### Operating system/version

Arch Linux ARM

### Terminal name/version

Termux 0.118

### $TERM environment variable

xterm-256color

### Installation

Build from repo

**Comment by justinmk** [comment]
updated nvim https://github.com/neovim/neovim/pull/25478

**Comment by nikklassen** [comment]
I'm still getting this error with the current nightly. Someone just commented on vim/vim#13246 saying the same thing

**Comment by zeertzjq** [comment]
Please create a new issue with enough information.
