### ISSUE TITLE
Raw Markdown underline styling in documentation

### ISSUE THREAD

**Issue by Andrew15-5** [neovim/neovim#25547]
From https://github.com/neovim/doc/issues/45.

---

https://github.com/neovim/neovim/blob/30d311ebcf9433f84bd4d98f9e049b36c9d352ac/runtime/doc/lua-guide.txt#L161

https://neovim.io/doc/user/lua-guide.html:

![image](https://github.com/neovim/doc/assets/37143421/45f5c9b9-e4c4-4586-abdd-cc5d05876235)

I believe this is a bug, since not everyone understands what `__` means and what Markdown is. I don't know if `__` should be just omitted or changed to something else, so I created an issue instead of a PR.

**Comment by clason** [comment]
If you think something can be improved, just make a PR. As much as we welcome the sentiment, these "micro issues" clutter the issue tracker and distract from actual bugs.

**Comment by Andrew15-5** [comment]
But PRs are literally for requesting a merge on already made changes. How should I make a PR if I already noted that I don't know how to fix this exactly?

**Comment by clason** [comment]
I mean, you must have thought something was wrong to open an issue. If you don't know whether something is wrong or not, better as on Matrix.

**Comment by Andrew15-5** [comment]
Oh, so I can write "potential" issues that are found in the Matrix room? There are only "General" (which are just to discuss something general, I assume) and "Support" (for when someone need a support). So I should write in "Genera" room, right?

**Comment by clason** [comment]
Those are not rooms I know. I'm talking about https://matrix.to/#/#neovim-dev:matrix.org

**Comment by Andrew15-5** [comment]
Yeah, sorry, these are from a different project related to Neovim. Thanks for the link!

**Comment by Andrew15-5** [comment]
I will close this as to not "clutter the issue tracker and distract from actual bugs". ;)

**Comment by justinmk** [comment]
> not everyone understands what `__` means and what Markdown is

Then they need to learn. Can't please everyone, and "everyone" is not the target audience.

PR not welcome.
