### ISSUE TITLE
"{}" in a treesitter query gives an error 

### ISSUE THREAD

**Issue by Danielkonge** [neovim/neovim#25552]
### Problem

I noticed that the indentation in Rust when starting a line with "{" is wrong when using the treesitter indentation, and while trying to fix that I wrote a query containing "{}", which immediately gave me an error. Trying a similar query in Lua I still get an error, and I assume this is a problem in the treesitter implementation, unless this is the expected behavior?

The trace looks like this:

```console
Error executing lua callback: .../share/nvim/runtime/lua/vim/treesitter/_query_linter.lua:95: attempt to get length of a nil value
stack traceback:
	.../share/nvim/runtime/lua/vim/treesitter/_query_linter.lua:95: in function 'fn'
	...EAD-28ffd96/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'parse'
	.../share/nvim/runtime/lua/vim/treesitter/_query_linter.lua:144: in function 'lint_match'
	.../share/nvim/runtime/lua/vim/treesitter/_query_linter.lua:182: in function 'fn'
	...6/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:483: in function 'for_each_tree'
	.../share/nvim/runtime/lua/vim/treesitter/_query_linter.lua:174: in function 'lint'
	...-28ffd96/share/nvim/runtime/lua/vim/treesitter/query.lua:804: in function 'lint'
	...AD-28ffd96/share/nvim/runtime/lua/vim/treesitter/dev.lua:556: in function <...AD-28ffd96/share/nvim/runtime/lua/vim/treesitter/dev.lua:555>
```

I am not sure if this is the right place to report the error? So if I am wrong, can someone point me to the correct place?

### Steps to reproduce

Open treesitter playground in a Rust file and type `(block "{}")` or in a Lua file with `(chunk "{}")` or some other valid command (even just `("{}")` in any filetype seems to trigger the error). 

### Expected behavior

I thought treesitter should be fine with a query containing the string "{}”, so it should just treat it like any other query with a string. 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1236+g28ffd96c9-Homebrew

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 14.0

### Terminal name/version

wezterm-nightly

### $TERM environment variable

wezterm

### Installation

Homebrew

**Comment by clason** [comment]
Why do you think this is a valid query?

**Comment by clason** [comment]
also, please always share _exact_, literal, reproducing steps rather than a vague explanation.

**Comment by Danielkonge** [comment]
> Why do you think this is a valid query?

I guess I misunderstood treesitter a bit. I thought it could capture most normal strings (ignoring special symbols). But I have actually just checked this query in the official treesitter playground and it also doesn't work there. 

I guess it would still be better if Neovim just responded that it is an invalid query (as it does for some other queries) instead of throwing an error, but the behavior is actually somewhat expected. 

> also, please always share _exact_, literal, reproducing steps rather than a vague explanation.

For the exact reproducing steps, would this have been fine?

- Open neovim and open any lua file (e.g. your init.lua)
- Press: `:InspectTree<CR>` (which opens and moves your cursor to the treesitter playground).
- Press `o` to open the query editor.
- Write `("{}")` and press `<Esc>`. 

I will leave this open for now in case you want to change the behavior from an error to a warning. But otherwise, feel free to close this issue. (If I get no response I will probably also just close it after a few days.)

**Comment by lucario387** [comment]
Errors are correct here. All strings that are used for pattern matchings needs to be the actual anonymous node's text, and not some random combination of braces. If a language parser allow an anonymous node to have the contents of `{}`, then you can use it for matching. If not, just skip and match opening and closing braces separately

**Comment by Danielkonge** [comment]
Ok, if errors are expected I will just close this issue then. I just started looking at and generally playing around with treesitter recently, so I don't really know what would be the expected behavior. Thanks for the quick responses.
