### ISSUE TITLE
nvim_create_user_command: support `custom` style completion function

### ISSUE THREAD

**Issue by Supreeeme** [neovim/neovim#25565]
### Problem

Currently the `complete` key of `nvim_create_user_command` accepts a lua function reference that should act identical to a `customlist` completion function, but there is no way to give a lua function reference to a function that acts like the simpler `custom` completion function, other than creating a global lua function and using `complete = 'custom,v:lua.my.lua.function'`.

### Expected behavior

Add something to `nvim_create_user_command` to specify a way to add a lua function reference to a function that acts like the `custom` completion function type.

**Comment by justinmk** [comment]
Show example code that shows what you expect, and also compares it to the existing required code, so that we can see what's actually gained. An alternative could be to update the docs to show an example that is easy to copy-paste.

**Comment by Supreeeme** [comment]
### Current flow

```lua
function MyCommandComplete()
    return vim.fn.join({'a', 'b', 'c', 'd'}, '\n'})
end
vim.api.nvim_create_user_command("MyCommand", function()
--blah blah...
end, { nargs = 1, complete = 'custom,v:lua.MyCommandComplete' })
```
- Requires defining a global function
- Is unintuitive when most lua functions can take a lua function reference as an option, and inconsistent with existing `customlist` functionality being able to do so

### Potential solution

```lua
vim.api.nvim_create_user_command("MyCommand", function()
-- blah blah...
end, { nargs = 1, complete = function()
    return vim.fn.join({'a', 'b', 'c', 'd'}, '\n'})
end, complete_customlist = false })
```
- Command and completion can now be coupled, no global function necessary
- Consistent with other lua things that take a function reference
- Not the biggest fan of the `complete_customlist` parameter but not sure how to best address it

Another alternative could be to allow the `complete` parameter to take a list of strings and have it act like the `custom` completion mode in this mode, since I feel like handling the current context is kind of pointless when Nvim will already do it for you and if you don't want that `customlist` is already a thing:
```lua
{ complete = {'a', 'b', 'c', 'd'} }
```
This could be confusing though as it's inconsistent with the existing Vim behavior.

**Comment by faergeek** [comment]
Would it make sense to determine the behavior based on type of value a lua function returns? If it returns list then it behaves like it currently does (like `customlist`), but if it returns string instead then it will behave like `custom`?

I think it's convenient to have support for that case as well, because this way there's no need to implement any custom filtering of completion results in plugins.

**Comment by justinmk** [comment]
From https://github.com/neovim/neovim/pull/26935 : 

 here's the diff of the new way vs the existing way:

<img width="923" alt="image" src="https://github.com/neovim/neovim/assets/1359421/2b2c50a5-d509-40f1-b048-6a9e59d5acaf">

> I'm not really sure why this difference even exists. Usually it's because one is supposed to be replaced by the other. I'd assume `complete` came first and then replaced by `customlist`. Either the lack of filtering is intetional or just a mistake.
> 
> Maybe worth checking with vim what the correct behaviour should be and whether `customlist` is supposed to supersede `custom`.

Yes, exactly. `custom` should be deprecated, not proliferated.

These kinds of localized, minor conveniences are not worth the extra code + docs + tests + explanation + bugs.

> having an ability to make neovim do the filtering for you seems to be quite useful anyway, don't you agree?

That could be a util function. It should not be achieved by adding extra interfaces.

**Comment by Supreeeme** [comment]
Would a utility function for providing basic filtering be accepted then?

**Comment by justinmk** [comment]
Not sure. Would be best to start by proposing what the util function looks like, and how it will be documented. Possibly it could be generalized.
