### ISSUE TITLE
odd behavior with `cc` in a prompt buffer when prompt starts with a space

### ISSUE THREAD

**Issue by 0xAdk** [neovim/neovim#25573]
### Problem

if the prompt buffer's prompt starts with a space when using `cc` instead of just clearing the prompt and entering insert mode on the same line, it moves down a line first.

### Steps to reproduce

`nvim --clean`
```vim
:set buftype=prompt
:call prompt_setprompt(bufnr(), ' % ')
```
enter any text, exit insert mode
`cc`

### Expected behavior

the prompt clears without creating a new line

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1319+gc40a1c0f41

### Vim (not Nvim) behaves the same?

no, vim 9.0.1882-1

### Operating system/version

archlinux

### Terminal name/version

kitty 0.29.2

### $TERM environment variable

xterm-kitty

### Installation

neovim-git AUR

**Comment by zeertzjq** [comment]
`:set noautoindent`
