### ISSUE TITLE
Invalid 'event': 'BufRead,BufNewFile,BufFilePost'

### ISSUE THREAD

**Issue by pebbe** [neovim/neovim#25576]
### Problem

With nvim 0.9.4 I get this error from one of the init files:

    Invalid 'event': 'BufRead,BufNewFile,BufFilePost'

This is the code:

    vim.api.nvim_create_autocmd('BufRead,BufNewFile,BufFilePost', {

This was working fine in nvim 0.9.2

These three events are still valid according to the docs.

### Steps to reproduce

Put thse line in a lua file, and require it:
```lua
vim.api.nvim_create_autocmd('BufRead,BufNewFile,BufFilePost', {
  pattern = { '*.ttl' },
  callback = function()
    vim.cmd.setfiletype('turtle')
  end,
})
```

### Expected behavior

no errors

### Neovim version (nvim -v)

v0.9.4

### Vim (not Nvim) behaves the same?

not tested

### Operating system/version

Linux 6.1.0-13-amd64 / Debian 12

### Terminal name/version

Gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by adriangoransson** [comment]
Is this still supposed to work with multi word events, eg. `Signal`?

These variations all yield errors for me.

`vim.api.nvim_create_autocmd('Signal SIGUSR1', {...})`
`vim.api.nvim_create_autocmd({ 'Signal SIGUSR1' }, {...})`
`vim.api.nvim_create_autocmd({ 'Signal', 'SIGUSR1' }, {...})`

My solution was to filter it out in the callback instead.

```lua
vim.api.nvim_create_autocmd('Signal', {
  callback = function(event)
    if event.match == 'SIGUSR1' then
      -- handle event
    end
  end,
})
```

**Comment by clason** [comment]
This was never supposed to work. The event is a single word, everything after that is part of the pattern:

```
Signal        After Nvim receives a signal. The pattern is
        matched against the signal name. Only
        "SIGUSR1" and "SIGWINCH" are supported.  Example:  
            autocmd Signal SIGUSR1 call some#func()
                      ^       ^
                    event  pattern
```

**Comment by adriangoransson** [comment]
> This was never supposed to work. The event is a single word, everything after that is part of the pattern:
> 
> ```
> Signal        After Nvim receives a signal. The pattern is
>         matched against the signal name. Only
>         "SIGUSR1" and "SIGWINCH" are supported.  Example:  
>             autocmd Signal SIGUSR1 call some#func()
>                       ^       ^
>                     event  pattern
> ```

Ah! I must have misread the documentation. Thanks for the clarification!

For reference again:
```lua
vim.api.nvim_create_autocmd('Signal', {
  pattern = 'SIGUSR1',
  callback = callback_function,
})
```

**Comment by clason** [comment]
Yes, that is how it's _supposed_ to work.
