### ISSUE TITLE
Nvim hangs after `:qall` on `loop_close`

### ISSUE THREAD

**Issue by KostkaBrukowa** [neovim/neovim#25575]
### Problem

Hey! 
I have problem with nvim hanging (sometimes) when I exit with `:qall`. It can hang for few minutes with 20% CPU usage. Unfortunately I cannot give repro steps, because I could not find any way to force this. The only thing I could get is this stack trace:
<details>

```Process 49152 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00000001888bbed0 libsystem_kernel.dylib`semaphore_wait_trap + 8
libsystem_kernel.dylib`semaphore_wait_trap:
->  0x1888bbed0 <+8>: ret    

libsystem_kernel.dylib`semaphore_wait_signal_trap:
    0x1888bbed4 <+0>: mov    x16, #-0x25
    0x1888bbed8 <+4>: svc    #0x80
    0x1888bbedc <+8>: ret    
Target 0: (nvim) stopped.
Executable module set to "/Users/xxx/nvim-nightly/nvim-macos/bin/nvim".
Architecture set to: arm64-apple-macosx-.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00000001888bbed0 libsystem_kernel.dylib`semaphore_wait_trap + 8
    frame #1: 0x00000001006ff910 nvim`uv_sem_wait + 24
    frame #2: 0x0000000100703e1c nvim`uv__fsevents_close + 216
    frame #3: 0x0000000100702a8c nvim`uv_fs_event_stop + 96
    frame #4: 0x00000001006f3738 nvim`uv_close + 104
    frame #5: 0x00000001006f2518 nvim`uv_walk + 172
    frame #6: 0x0000000100833ef8 nvim`loop_close + 260
    frame #7: 0x0000000100704960 nvim`event_teardown + 620
    frame #8: 0x00000001007090e0 nvim`os_exit + 112
    frame #9: 0x0000000100709818 nvim`getout + 1728
    frame #10: 0x000000010085973c nvim`ex_quit_all.llvm.11403118564339431611 + 272
    frame #11: 0x0000000100850214 nvim`execute_cmd0 + 252
    frame #12: 0x000000010084b1ec nvim`do_cmdline + 11380
    frame #13: 0x000000010092dddc nvim`nv_colon.llvm.1921225476992970733 + 472
    frame #14: 0x000000010092a074 nvim`normal_execute.llvm.1921225476992970733 + 9100
    frame #15: 0x0000000100a199f4 nvim`state_enter + 160
    frame #16: 0x00000001007081a8 nvim`main + 13020
    frame #17: 0x00000001885a3f28 dyld`start + 2236
```

</details>

Any ideas what could be wrong here? Anything that I could do locally to fix that or find out what's wrong? Again sorry for no repro steps and if that's deal breaker feel free to close this issue

### Steps to reproduce

sorry but I don't have it :(

### Expected behavior

It should not hang

### Neovim version (nvim -v)

NVIM v0.10.0-dev-5f4f83b and v0.9.2

### Vim (not Nvim) behaves the same?

No

### Operating system/version

MACOS 13.5.1

### Terminal name/version

kitty Version 0.26.4 (0.26.4)

### $TERM environment variable

truecolor

### Installation

homebrew

**Comment by glepnir** [comment]
seems like duplicate #25086

**Comment by glepnir** [comment]
@KostkaBrukowa  did you still get this hang since 25086 has been fixed.

**Comment by glepnir** [comment]
@KostkaBrukowa  could you try the last commit build (or download nightly version) and retry agian if can still reproduce there need reopen issue.
