### ISSUE TITLE
"_FORTIFY_SOURCE redefined" build warnings

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2557]
When building with manually specified `_FORTIFY_SOURCE`, a lot of warnings are produced during the header generation:

```
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<command-line>:0:0: note: this is the location of the previous definition
```

Is there something we can do about this?

To reproduce:

```bash
rm build
make CFLAGS="-D_FORTIFY_SOURCE=2" CMAKE_BUILD_TYPE=RelWithDebInfo
```

**Comment by jszakmeister** [comment]
We do try: https://github.com/neovim/neovim/blob/master/CMakeLists.txt#L99

It turns out that some gcc builds (depends on the distro) set `_FORTIFY_SOURCE` internally, so you need to undefine it first.  So if you used `CFLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2"`, it might go better.

**Comment by fwalch** [comment]
Works :+1:
