### ISSUE TITLE
maybe typo in os_unix_defs.h

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#2558]
os_unix_defs.h:120
```c
#if !defined(USR_EXRC_FILE2)
#    define USR_VIMRC_FILE2     "~/.nvim/nvimrc"
#endif
```
Shouldn't it be `#ifndef USR_VIMRC_FILE2 ...` ?

**Comment by glts** [comment]
I agree, it probably should.

It's the same in Vim though. We could ask on the vim_dev mailing list.

**Comment by justinmk** [comment]
P.S.: We should probably not support `exrc` files anymore.

**Comment by Yamakaky** [comment]
I'm not on vim_dev, could you please ask ?

**Comment by Pyrohh** [comment]
You only need an email address: http://www.vim.org/maillist.php

**Comment by Yamakaky** [comment]
```
Ah, sorry, missed that part.  Yeah, I suppose that has always been
wrong.

- Bram
```

**Comment by Yamakaky** [comment]
Yeay !

```

Patch 7.4.713
Problem:    Wrong condition for #ifdef.
Solution:   Change USR_EXRC_FILE2 to USR_VIMRC_FILE2. (Mikael Fourrier)
Files:      src/os_unix.h


*** ../vim-7.4.712/src/os_unix.h	2015-04-09 22:08:09.183074550 +0200
--- src/os_unix.h	2015-05-03 19:07:22.850147859 +0200
***************
*** 290,296 ****
  #endif
  
  
! #if !defined(USR_EXRC_FILE2)
  # ifdef OS2
  #  define USR_VIMRC_FILE2	"$HOME/vimfiles/vimrc"
  # else
--- 290,296 ----
  #endif
  
  
! #if !defined(USR_VIMRC_FILE2)
  # ifdef OS2
  #  define USR_VIMRC_FILE2	"$HOME/vimfiles/vimrc"
  # else
*** ../vim-7.4.712/src/version.c	2015-04-22 22:18:14.659662668 +0200
--- src/version.c	2015-05-04 09:16:12.477776841 +0200
***************
*** 743,744 ****
--- 743,746 ----
  {   /* Add new patch number below this line */
+ /**/
+     713,
 ```

**Comment by Pyrohh** [comment]
I'll close this so it isn't forgotten. #2580 should be merged soon.

**Comment by glts** [comment]
You're super diligent @Pyrohh  :open_mouth: 

I don't think we need to rush though. I think there's nothing wrong with keeping an issue open until it is actually fixed in master. Just my opinion :).

**Comment by Pyrohh** [comment]
> You're super diligent @Pyrohh

I try :grin: 

I generally agree, but I didn't want to edit the OP in #2580 out of principle (to add `fixes #2558`). Then again, I probably could have asked... heh.

**Comment by Pyrohh** [comment]
I'll make sure to do that in the future.

**Comment by glts** [comment]
There might be a little misunderstanding here ... #2580 isn't directly related to this I think.

**Comment by Pyrohh** [comment]
Oops, i got the two issues confused. #2578 is indeed it, so I'll reopen.

**Comment by Yamakaky** [comment]
Merged.

**Comment by justinmk** [comment]
7.4.713 was not merged, and AFAIK there's no PR for it.

**Comment by Yamakaky** [comment]
Oops.
It's part of #2578

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/2832 Thanks!
