### ISSUE TITLE
0.9.4 can't install on macOS

### ISSUE THREAD

**Issue by fundon** [neovim/neovim#25580]
### Problem

```
$ nvim --version
dyld[5585]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: <90035C11-DFA0-37AB-9CDE-28D74487BBDF> /Users/fundon/.nvim/bin/nvim
  Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
fish: Job 1, 'nvim --version' terminated by signal SIGABRT (Abort)
```

### Steps to reproduce

1. Download nvim-macos.tar.gz
2. unzip it
3. move it to `~/.nvim`
```
$ cd ~/Downloads
$ curl -LO https://github.com/neovim/neovim/releases/download/v0.9.4/nvim-macos.tar.gz
$ tar zxvf nvim-macos.tar.gz
$ rm ~/.nvim
$ mv ~/Downloads/nvim-macos ~/.nvim
$ nvim --version
```

### Expected behavior

works in 0.9.2

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 14

### Terminal name/version

ALACRITTY

### $TERM environment variable

xterm-256color

### Installation

nvim-macos.tar.gz

**Comment by clason** [comment]
Works for me. Make sure that whatever `nvim` is in your path actually points to the downloaded binary.

**Comment by fundon** [comment]
I don't use Homebrew.

**Comment by fundon** [comment]
`dyld[5585]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib` 

The error alert that related to homebrew.

**Comment by llllvvuu** [comment]
Did you install `gettext` and add it to your `LD_LIBRARY_PATH`?

For example I am using homebrew (`brew install gettext`) so my `LD_LIBRARY_PATH` looks like `/opt/homebrew/lib` and I have the library at `/opt/homebrew/opt/gettext/lib/libintl.8.dylib`

**Comment by clason** [comment]
Ah, that's because we stopped downloading and statically linking to homebrew's `libintl` bottle: https://github.com/neovim/neovim/commit/cc398c5b06e191fd90c6927e92e41acea2893cf6

(@dundargoc)

You need to have libintl (and `gettext`) available somehow -- not necessarily through homebrew, that is a red herring.

**Comment by clason** [comment]
We'll definitely consider this for the next version; the previous way was just too hacky and broke without warning.
