### ISSUE TITLE
completion: ctrl-n completes buffer names ("f" in 'complete' option)

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#25598]
### Problem

Insert-mode completion `ctrl-n` / `ctrl-p` doesn't complete buffer names. Very often I want to complete buffer names (which may not exist on disk, or are in a different CWD, thus not found by `ctrl-x ctrl-f`). 

### Expected behavior

With `set complete+=f`, `ctrl-n` completes buffer name tokens just like it completes tokens found in buffer text. 

Example: if the buffer list (`:ls`) contains a buffer named `foo/bar.txt`, invoking `ctrl-n` suggests "foo", "bar", and "txt", same as if a buffer contained the text `foo/bar.txt`,

**Comment by zeertzjq** [comment]
Now this conflicts with Vim: <https://github.com/vim/vim/commit/cbe53191d01926c045a39198b3a9517e3c5077d2> :(

**Comment by justinmk** [comment]
> These new flags extend keyword completion behavior (e.g., via `<C-N>` / `<C-P>`) by allowing function-based sources to participate in standard keyword completion.

What is the point of that feature? If it's important we can replace our current "f", but it seems like a pointless variation of `<c-x><c-u>`, etc.

**Comment by zeertzjq** [comment]
@glepnir Any comments?

**Comment by glepnir** [comment]
`o` flag can close https://github.com/neovim/neovim/issues/16012 about `f` flag might be a nuisance for me maybe. I'm refactoring keyword to async so there might be some impact.
