### ISSUE TITLE
EditorConfig overriding Git commit textwidth

### ISSUE THREAD

**Issue by JaxonWasTaken** [neovim/neovim#25603]
### Problem

When running `git commit` inside a directory governed by an `.editorconfig` file, the specified `max_line_length` overrides the `textwidth` set by [/runtime/ftplugin/gitcommit.vim#L13](https://github.com/neovim/neovim/blob/2fde6295df8cdfb36ed02ef5f9a3b6a523b1ac23/runtime/ftplugin/gitcommit.vim#L13).

### Steps to reproduce

With an `.editorconfig` file containing
```
[*]
max_line_length = 120
```
Run `nvim -V1 COMMIT_EDITMSG`, then `:verbose set tw?`, which should report (exact path to editorconfig.lua may vary):
```
  textwidth=120                                                             
        Last set from /usr/share/nvim/runtime/lua/editorconfig.lua line 80
```
The line referenced: [/runtime/lua/editorconfig.lua#L80](https://github.com/neovim/neovim/blob/2fde6295df8cdfb36ed02ef5f9a3b6a523b1ac23/runtime/lua/editorconfig.lua#L80).

### Expected behavior

`textwidth` is set to 72 for Git commit messages.

I'm aware of #24383, however I'd argue this should at least be considered for exclusion from EditorConfig handling, as the Git commit message file isn't really a part of the project for which one would use EditorConfig. Other ephemeral files to consider for exclusion are the ones used for `git rebase` and `git send-email`. There may be other files outside the scope of Git to consider for exclusion, but these are the ones I can think of off the top of my head.

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

no, 9.0.2002

### Operating system/version

Arch Linux, updated as of 2023-10-12T00:00:00+02:00

### Terminal name/version

Gnome Terminal 3.50.0

### $TERM environment variable

xterm-256color

### Installation

Installed from Arch Linux' extra repository

**Comment by JaxonWasTaken** [comment]
Immediately after submitting this issue it hit me that there might be existing usage of EditorConfig for Git commit messages, and wouldn't you know, Git itself uses it in just this way: [git/git/.editorconfig#L15](https://github.com/git/git/blob/aab89be2eb6ca51eefeb8c8066f673f447058856/.editorconfig#L15).

I guess I'll just have to either add entries for ephemeral files to `.editorconfig` files or create my own ftplugins that set `b:editorconfig = v:false`.

**Comment by justinmk** [comment]
We should probably set `b:editorconfig = v:false` by default in the builtin git ftplugin.

**Comment by JaxonWasTaken** [comment]
Would that entail having to create an `autocmd` or ftplugin to turn EditorConfig handling on for Git commits (and possibly other files), or creating a new variable for enabling/disabling it for ephemeral files? E.g. `g:editorconfig_ephemeral`.

**Comment by justinmk** [comment]
Just adding `let b:editorconfig = v:false` to https://github.com/neovim/neovim/blob/master/runtime/ftplugin/gitcommit.vim should work.

**Comment by JaxonWasTaken** [comment]
While that would make my life easier, such a change could end up going against other users' expectations, especially since using EditorConfig for Git commit messages seems to be at least somewhat established.

**Comment by justinmk** [comment]
True but in the overwhelming common case, editorconfig is currently getting in the way. 

OTOH, adding random overrides in ftplugins somewhat defeats the purpose of editorconfig; technically people should be more specific with their `[*]` directives, or add a `[COMMIT_EDITMSG]` directive.
