### ISSUE TITLE
Build neovim with python/python3 support

### ISSUE THREAD

**Issue by moonstruck** [neovim/neovim#2561]
Default make doesn't build neovim with python or python3 support. Do I need to export/add some CMAKE flags?

I have python-dev, python3-dev and neovim python package for both versions of python installed system wide.

I'm using default vagrant image.

Thanks.

**Comment by ZyX-I** [comment]
Python\* support is no longer compiled in. All necessary code *on the NeoVim* side is *always* present, but you must also install `neovim` Python package. More details at `:h nvim-python`.

**Comment by subhojit777** [comment]
`h: nvim-python` is not available,  but this helped https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim

**Comment by justinmk** [comment]
The help is now located at:

    :help provider-python

Also, run

    :CheckHealth

to get full diagnostics.
