### ISSUE TITLE
Lua: listchars option does not accept table as value

### ISSUE THREAD

**Issue by CrispyBaccoon** [neovim/neovim#25633]
### Problem

When setting the `listchars` option through similar ways as you would with `fillchars` neovim errors.

### Steps to reproduce

```lua
vim.opt.listchars:append { tab = ">", trail = "-", nbsp = "+" }
```
or
```lua
vim.opt.listchars = { tab = ">", trail = "-", nbsp = "+" }
```

### Expected behavior

This should set the appropiate table fields to the expected values.

### Neovim version (nvim -v)

0.10.0-dev-1011+g7bf0963d4

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Arch Linux

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by clason** [comment]
Your format for `tab` is wrong; see `:h 'listchars'`.
