### ISSUE TITLE
Initial draw can be not finished during startup

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#25642]
### Problem

If some other process blocks Neovim inside `vim.schedule()` initiated during startup, initial screen is not drawn fully.

### Steps to reproduce

1. Create config with the following contents:
```lua
vim.schedule(function() vim.loop.sleep(1000) end)
```
2. Start `nvim` with this config. This will result into only partial screen draw (without "welcome" message, for example) which will be completed after 1 second.

### Expected behavior

First initial draw is finished and only then instance is blocked, as it was on `ebe489d` commit.

------

The #25629 seems to be the reason. Applying the following patch fixes this issue:
```patch
diff --git a/src/nvim/getchar.c b/src/nvim/getchar.c
index 5f3b14399..46a786c1d 100644
--- a/src/nvim/getchar.c
+++ b/src/nvim/getchar.c
@@ -2862,9 +2862,7 @@ int inchar(uint8_t *buf, int maxlen, long wait_time)

     // Always flush the output characters when getting input characters
     // from the user and not just peeking.
-    if (wait_time == -1L || wait_time > 10L) {
-      ui_flush();
-    }
+    ui_flush();

     // Fill up to a third of the buffer, because each character may be
     // tripled below.
```

### Neovim version (nvim -v)

NVIM v0.10.0-dev-bf70a33

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.5.6-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
I don't think this is a bug.

**Comment by echasnovski** [comment]
Thanks, Zeer!
