### ISSUE TITLE
Make `make format` work during rebase

### ISSUE THREAD

**Issue by dundargoc** [neovim/neovim#25654]
`make format` does not work during rebasing. This is because it tries to be smart ans only format files which have been changed in PR, but this breaks down during rebase. Ideally it'd still be able to detect which files were changed even on rebase, but a fallback to formatting all files instead is also acceptable.

The formatting logic is in `cmake/Format.cmake`

**Comment by patriciarodrigues151** [comment]
Hi, I'm working on this.
