### ISSUE TITLE
Neovim undodir myseriously changed

### ISSUE THREAD

**Issue by mlindner** [neovim/neovim#25652]
### Problem

My undo dir used to be located at (by default) ~/.local/share/nvim/undo, along with all the other neovim data files in ~/.local/share/nvim, but it suddenly moved to ~/.local/state/nvim/undo. Was this a recent change? How do I make the data dirs (as well as the undofile) stay what it was before?

### Steps to reproduce

Open a file with "set undofile" set. Observe that the path for saving undo files is no longer what it was.

### Expected behavior

The undodir not having changed

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

unknown

### Operating system/version

12.6.1

### Terminal name/version

iTerm 3.4.18

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by mlindner** [comment]
Additionally I observed that undofiles often aren't being saved anymore in most cases. Though it seems to be inconsistent. Perhaps where they are being saved and where they are being attempted to be loaded from are different directories.

**Comment by zeertzjq** [comment]
Just create a symlink from the new directory to the old one.

**Comment by mlindner** [comment]
> Just create a symlink from the new directory to the old one.

That doesn't answer the issue. Was this changed? Symlinks are a hack that I don't want to use.

**Comment by zeertzjq** [comment]
Or set `$XDG_STATE_HOME` to `~/.local/share`

**Comment by mlindner** [comment]
> Or set `$XDG_STATE_HOME` to `~/.local/share`

Yes that is another workaround. Was this a change on neovim's part?

**Comment by zeertzjq** [comment]
Yes. https://github.com/neovim/neovim/issues/14090#issuecomment-1125055183
