### ISSUE TITLE
Loading colorscheme clears messages due to Setting hl group `MsgArea`

### ISSUE THREAD

**Issue by folke** [neovim/neovim#25669]
### Problem

Creating a hl for `MsgArea` when a message is currently shown, clears messages.
Since most colorschemes set this hl group, this will effectively not show some messages during startup to the user.

### Steps to reproduce

`nvim -u repro.lua`

```lua
vim.api.nvim_set_hl(0, "MsgArea", { fg = "red" })
print("foobar")
```

### Expected behavior

`foobar` should be shown, but it's not.
Commenting the `set_hl` line shows the correct behavior

### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

didn't test

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-256-kitty

### Installation

bob

**Comment by nwounkn** [comment]
#17832 duplicate
