### ISSUE TITLE
Log file is empty

### ISSUE THREAD

**Issue by TaihouKai** [neovim/neovim#25664]
### Problem

I'm running NeoVim from Windows, without any environment variables manually set after installation.
I'd like to find some plugin logs in general log file as stated in https://neovim.io/doc/user/starting.html#log
I can find the log in the the directory, but it is empty:
```
C:\Users\<username>\AppData\Local\nvim-data\log
```

I can see "Date modified" of every other file is when I closed NeoVim, but that of log file remains unchanged since it was created.

### Steps to reproduce

(In Win GUI)
Open NeoVIM
Open any text file
`i`
Do some editing
Esc
`:wq`

### Expected behavior

Log file should not be empty.

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

Vim is not installed in Windows by default

### Operating system/version

Windows 10 22H2

### Terminal name/version

Windows Terminal

### $TERM environment variable

Not set

### Installation

MSI installer

**Comment by zeertzjq** [comment]
Because there are no warning or errors to log.

**Comment by TaihouKai** [comment]
> Because there are no warning or errors to log.

May I ask whether NV generates information-level logs, in addition to warnings/errors?

**Comment by zeertzjq** [comment]
Only if Nvim is compiled with `-DNVIM_LOG_DEBUG`.
