### ISSUE TITLE
Double right-click menus on Blackbox, Console.

### ISSUE THREAD

**Issue by naelstrof** [neovim/neovim#25680]
### Problem

Attempting to use mouse support in a few terminal ~~emulators~~ I tried causes both neovim and the terminal ~~emulator~~ to react to the right-click.

I don't know if this is neovim's responsibility! Though I'm struggling to find out how to diagnose the issue or find any information on it.

![image](https://github.com/neovim/neovim/assets/1131571/680ae8db-9cb2-443a-b151-d768944071b3)

### Steps to reproduce

Use nvim in Gnome's Console or Blackbox.

Right-click.

### Expected behavior

Either the terminal ~~emulator~~ should receive the click or Neovim depending on the mouse setting.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-0a3505e

### Vim (not Nvim) behaves the same?

no, vim has no right-click menu.

### Operating system/version

NixOS 22.05, and Arch Linux.

### Terminal name/version

BlackBox version 0.13.1, Gnome 44/45.

### $TERM environment variable

xterm-256color

### Installation

Nix nightly overlay, Arch AUR.

**Comment by zeertzjq** [comment]
> BlackBox version 0.13.1, Gnome 44/45.

Neither of these are terminal emulators.

**Comment by naelstrof** [comment]
Ah yeah, excuse me. Anytime I said terminal emulator, I just meant terminal app.

The one in the screenshot is BlackBox. Though I've had the same happen with Gnome Console, and Kitty. I can provide screenshots for all of them if needed.

**Comment by naelstrof** [comment]
I double checked, and made a mistake with kitty. I used a config that cleared mouse actions, but it never had mouse actions in the first place that interfered. It works great.

Blackout and Gnome Console appear to be the only culprits.

Here's an image of Gnome's Console:
![image](https://github.com/neovim/neovim/assets/1131571/c160490d-0715-4777-8bdc-ac85f11b0539)

gnome-terminal actually works great, and I'm going to switch to that for now.

**Comment by zeertzjq** [comment]
Not an Nvim issue.
