### ISSUE TITLE
lua.vim.treesitter.foldtext() does not highlight captures that span from the folded line to below

### ISSUE THREAD

**Issue by gzagatti** [neovim/neovim#25684]
### Problem

Let's say I have the following Org file:

```org
** Foo
    The sky is blue
```

And the following `queries/org/highlights.scm`.

```scm
;; extends
(headline (stars) @text.title.2.marker (#eq? @text.title.2.marker "**")) @text.title.2
```

The newly added `lua.vim.treesitter.foldtext()` from PR #25391 will not highlight the entire sentence with `@text.title.2` because `(headline)` spans from the title line to the next one.

![image](https://github.com/neovim/neovim/assets/11043156/2d621302-1383-4686-b384-36afaacbc532)

### Steps to reproduce

Create a file `foo.org`.

```org
** Foo
    The sky is blue
```

Add `queries/org/highlights.scm`.

```scm
;; extends
(headline (stars) @text.title.2.marker (#eq? @text.title.2.marker "**")) @text.title.2
```

### Expected behavior

The whole line should be highlighted with the captured highlight as below.

![image](https://github.com/neovim/neovim/assets/11043156/81ecc645-2a91-4a5e-aa69-8ffa34affd4a)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1367+g35f475d0a-Homebrew

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Ubuntu 22.04.3

### Terminal name/version

kitty 0.3

### $TERM environment variable

xterm-kitty

### Installation

Homebrew

**Comment by clason** [comment]
"Fixed" by replacing `vim.treesitter.foldtext()` with https://github.com/neovim/neovim/pull/20750.
