### ISSUE TITLE
Neovim hangs, sometimes

### ISSUE THREAD

**Issue by willruggiano** [neovim/neovim#25691]
### Problem

I realize this isn't a particularly helpful bug report but putting it here in case others run into it and have more time to debug.

I recently bumped neovim to a more recent commit off master and noticed neovim freezing sometimes. I have not dug into it too much, as previously stated, but have noticed it mostly related to `:term` and/or jobstart usage (e.g. toggleterm). This I cannot repro consistently.

What I can repro consistently is doing a `:Lazy` will cause neovim to freeze and I have to pkill it.

I opened [this issue](https://github.com/folke/lazy.nvim/issues/1135) in lazy.nvim, but I don't know for sure that lazy is to blame.

### Steps to reproduce

`:Lazy`

### Expected behavior

Neovim does not freeze

### Neovim version (nvim -v)

v0.10.0-dev-2c9f22e

### Vim (not Nvim) behaves the same?

Not sure

### Operating system/version

NixOS 23.11.20230917.5148520 (Tapir)

### Terminal name/version

kitty 0.29.2

### $TERM environment variable

xterm-kitty

### Installation

nix via willruggiano/neovim.drv

**Comment by clason** [comment]
Sorry, but that is indeed not helpful at all. If you ever find a proper reproducing example (or bisection, or stacktrace from gdb, or -- really -- _anything_ useful for other people), just open a new issue.

**Comment by clason** [comment]
Also, always test the very latest commit on master. What worked or didn't work last week is irrelevant not.

(Yes, that means you are expected to update at least daily, if you insist on using prerelease builds.)

**Comment by willruggiano** [comment]
Yeah, figured. If I get time to debug any more I'll drop details in a new issue.
