### ISSUE TITLE
inccommand: Window scrolls to top unexpectedly

### ISSUE THREAD

**Issue by Asheq** [neovim/neovim#25697]
### Problem

Not sure what exactly is causing the problem, but I can reproduce it reliably using the steps below:

https://github.com/neovim/neovim/assets/4657140/4bbd040c-b565-48f2-be61-adc43b201d19

### Steps to reproduce

```
nvim --clean
:e file.txt
<C-f><C-f>
:vnew
:tabnew
:tabclose
:set number
```

### Expected behavior

No window should scroll when I execute `:set number`

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

no, 9.0.1544

### Operating system/version

macOS 13.5.1

### Terminal name/version

kitty 0.29.0

### $TERM environment variable

xterm-kitty

### Installation

homebrew

**Comment by zeertzjq** [comment]
`gt` is not needed in the steps to reproduce.

**Comment by zeertzjq** [comment]
This seems to be caused by 'inccommand'.

**Comment by Asheq** [comment]
> `gt` is not needed in the steps to reproduce.

That's correct. That was an accident. I've removed it.
