### ISSUE TITLE
—embed with —listen

### ISSUE THREAD

**Issue by georgeharker** [neovim/neovim#25706]
### Problem

Right now —embed will pause waiting for a connection explicitly via stdin. 

I’m trying to get VimR up to date and purge the custom parts so it can talk to a standard neocon install. I have much done. But there’s the obvious startup ordering issues that —embed is designed to solve. 

The issue is that the waiting for ui will never succeed unless I rewrite all code to communicate via stdin which is a lot of work. I am wondering how amenable to a PR you’d all be to alter the condition waiting for ui connection to be on the channel started for listen if —listen is also specified. It seems like only a few lines of code would be needed and would allow clients to either use stdin or socket based connections to embed neovim. Which should be generally useful for flexibility of implementing guis. 

Any thoughts? 

### Expected behavior

—embed with —listen would wait for ui connection on the listen port.

**Comment by georgeharker** [comment]
See #25709

**Comment by georgeharker** [comment]
QQ on this - if we wanted to do a version check using nvim_api_info what release tag should we check for?

**Comment by clason** [comment]
0.10

**Comment by georgeharker** [comment]
thanks!
