### ISSUE TITLE
Can you make a .deb package?

### ISSUE THREAD

**Issue by antidotejack** [neovim/neovim#25708]
### Problem

Installing neovim from source is a headache. the repositories are way behind, I can not find the appimage and I feel that I have to hack this in order to work.

### Expected behavior

At least for debian based distros a .deb package is not asking a lot.

**Comment by zeertzjq** [comment]
Search existing (closed) issues

**Comment by dundargoc** [comment]
We have one: https://github.com/neovim/neovim-releases

**Comment by antidotejack** [comment]
@dundargoc I really apreciate your help. But I didn't find any file to download in that link, maybe I'm skipping some steps that I don't know. What shoul I download.

**Comment by zeertzjq** [comment]
https://github.com/neovim/neovim-releases/releases

**Comment by antidotejack** [comment]
@zeertzjq thanks but there is nothing to download there. I'm feeling like I have to hack my way through.

**Comment by antidotejack** [comment]
finally, Thanks @clason. I will make a video tutorial on this

**Comment by clason** [comment]
I'm sure it will do well on TikTok.

**Comment by antidotejack** [comment]
Guys I don't mean to be toxic, I just want to notify that the .deb DOES WORK. I had to remove some garbage from the previous installation. sorry for  the inconvenience and thank you for your quick support. I'm starring this project right now.
