### ISSUE TITLE
tsserver not working on termux

### ISSUE THREAD

**Issue by sourav-kum** [neovim/neovim#25712]
### Problem

Showing Error: Spawning language server with cmd: `/data/data/com.termux/files/usr/bin/typescript-language-server` failed. The language server is either not installed, missing from PATH
, or not executable.

I am running on Termux android app.

I have installed it by npm i -g typescript-language-server typescript

`/data/data/com.termux/files/usr/bin/typescript-language-server` is available and excutable.

But still is not working.

### Steps to reproduce using "nvim -u minimal_init.lua"

Problem must be in lsp

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/data/data/com.termux/files/usr/share/nvim"  Run :checkhealth for more info

### Language server name/version

typescript-language-server (tsserver) 3.3.2

### Operating system/version

android 14

**Comment by Mrestof** [comment]
I'm having the same issue, but also with pyright, bash language server and vim language server. So I guess it's a general problem with LSP on Android, or Termux specifically.

**Comment by romanovj** [comment]
did you edit shebang in /data/data/com.termux/files/usr/bin/typescript-language-server?

try with
`#!/data/data/com.termux/files/usr/bin/node`

**Comment by Mrestof** [comment]
> did you edit shebang in /data/data/com.termux/files/usr/bin/typescript-language-server?
> 
> try with `#!/data/data/com.termux/files/usr/bin/node`

Okay, that works, thanks. But shouldn't it be fixed by `termux-exec` package? Because it works when I start scripts with `#!/bin/env` shebang or such from my shell.

**Comment by romanovj** [comment]
@Mrestof sometime it doesn't work

**Comment by Mrestof** [comment]
> @Mrestof sometime it doesn't work

Well, yeah. Probably because the language server starts without proper `LD_PRELOAD` env variable, but I do not manage to find a way to run the command with this env var. For now shebang replaement will do. Btw, Termux has a helper script for this: `termux-fix-shebang`.

**Comment by zeertzjq** [comment]
This is a language server installation problem.

**Comment by s1nistr4** [comment]
Please reopen, this is a major issue that affects many users of termux.

https://www.reddit.com/r/neovim/comments/1cx05ws/spawning_lsp_servers_fails_regularly/
https://github.com/williamboman/nvim-lsp-installer/discussions/509
https://github.com/neovim/neovim/issues/17354
https://github.com/williamboman/nvim-lsp-installer/issues/848
https://github.com/LunarVim/LunarVim/discussions/3396
https://github.com/termux/termux-app/issues/3855

**Comment by clason** [comment]
But not a Neovim issue; it must be solved somewhere else.
