### ISSUE TITLE
when i delete a new line nvim delete others empty lines

### ISSUE THREAD

**Issue by dapt4** [neovim/neovim#25713]
### Problem

when i delete a new line nvim delete others empty lines.

when the cursor pos is in a comment line in normal mode and I type "o"
the new line comes with a comment too, but if i delete this comment with backspace, nvim delete the entire line and the next 
empty line too.

see the error in: https://gifyu.com/image/S6tuR

### Steps to reproduce

nvim .vimrc

o
<backspace>

### Expected behavior

just i want to remove the autocomment 

### Neovim version (nvim -v)

NVIM v0.9.1 RELEASE

### Vim (not Nvim) behaves the same?

i don´t know

### Operating system/version

ubuntu 22

### Terminal name/version

kitty term -> kitty 0.21.2 created by Kovid Goyal

### $TERM environment variable

xterm-kitty

### Installation

I download the binary from the releases page

**Comment by clason** [comment]
Please try the latest release (0.9.4), and always test with `nvim --clean`.

**Comment by dapt4** [comment]
ok i try "nvim --clean <filename>" and works, the format works correctly. what could be the problem?

**Comment by dapt4** [comment]
the problem is a plugin: jiangmiao/auto-pairs
