### ISSUE TITLE
Add support for LSP completion side effects (snippet expansion, command execution, additionalTextEdits)

### ISSUE THREAD

**Issue by mfussenegger** [neovim/neovim#25714]
### Problem

The language server protocol specifies that completion items can contain:

- snippets
- `additionalTextEdits` (e.g used to add import statements when selecting a completion candidate)
- A `command` (used to execute client side or server side commands - for all sorts of things). For example, vscode defines a `editor.action.triggerParameterHints` client command to trigger a  signature help immediately after a completion candidate got selected.

Currently neovim core handles none of that, and instead delegates to completion plugins like nvim-cmp, nvim-lsp-compl or others.

### Expected behavior

Have this functionality built-in.

With https://github.com/neovim/neovim/pull/25301 the groundwork for snippet expansion is done.
The next step is to integrate it with the completion, omnifunc. For that we'll need to setup a `CompleteDone` autocmd similar to:

https://github.com/mfussenegger/nvim-lsp-compl/blob/1642f1c57a83a0b630fdf7f339f4a5550a766407/lua/lsp_compl.lua#L565-L668

Open Questions:

- [ ] Opt-in or opt-out. Enabling it by default could conflict with above established completion plugins. On the other hand, opt-in is another hurdle in getting started from scratch
- [ ] Snippet expansion trigger - implicit/explicit? (For me, always implicit expanding would make this unusable)

Proposal:

- Make it opt-in via a `vim.lsp.completion.attach(client, bufnr, [opts])` method that can be called in a `LspAttach` autocmd. It would sets up a `CompleteDone` autocmd for the given buffer and client.
- Add a `vim.lsp.completion.accept()` function that if called causes the next accempted completion candidate to expand a snippet, if the completion item contains one. To be used in a mapping like:

```
vim.keymap.set('i', '<CR>', function()
  return vim.lsp.completion.accept() and '<c-y>' or '<CR>'
end, { expr = true })
```

`opts` relate a bit to the auto-completion aspect and https://github.com/neovim/neovim/issues/25670, and might not be necessary in a first step.

## Related issues

- https://github.com/neovim/neovim/issues/13199
- https://github.com/neovim/neovim/issues/12310

**Comment by justinmk** [comment]
> Currently neovim core handles none of that, and instead delegates to completion plugins like nvim-cmp, nvim-lsp-compl or others.

Can we extend the builtin completion concepts rather than add a LSP-specific interface?

> `vim.lsp.completion.attach(client, bufnr, [opts])`

"Attach to completion" feels like we are overextending the concept of attach. (And "attach" in general is probably a signal that we're missing something in the [events interface](https://github.com/neovim/neovim/issues/19156).)

Would it make sense to "attach to client"? Since LSP clients are the main primitive in LSP, like how buffer/win/tab are the primitives in Nvim.

**Comment by mfussenegger** [comment]
> Can we extend the builtin completion concepts rather than add a LSP-specific interface?

You mean something like adding a `snippet` property to the `complete-items` structure? Or/and an `on_complete` property that's an arbitrary function?
Are we okay with diverging from vim on that?

> "Attach to completion" feels like we are overextending the concept of attach.

In my proposal it was meant as the opt-in trigger, to be used in a `LspAttach` autocmd.

Alternatives:
- Call it `setup` or `config`
- Make opt-in part of the `lsp.start()` opts. Something like `vim.lsp.start({ completion = { enabled = true }})` ? Or more granular `completion = true|{ snippets = true, text_edits = true, commands = true }`

We have client granularity/namespacing here, so using global-/local opts is imho not a good match.

**Comment by justinmk** [comment]
> > Can we extend the builtin completion concepts rather than add a LSP-specific interface?
> 
> You mean something like ... an `on_complete` property that's an arbitrary function? Are we okay with diverging from vim on that?

We could propose it upstream, but otherwise a callback is a generic mechanism that justifies a small divergence.

**Comment by justinmk** [comment]
> Make it opt-in via a `vim.lsp.completion.attach(client, bufnr, [opts])` method

If we enabled it by default, then it could be _opt-out_, by documenting how to delete the `CompleteDone` handler. Any problem with that?

**Comment by mfussenegger** [comment]
> If we enabled it by default, then it could be _opt-out_, by documenting how to delete the `CompleteDone` handler. Any problem with that?

If we handle the `triggerCharacters` as well it also needs `InsertCharPre`, likely `InsertLeave` and if we want to have re-trigger on backspace capability also `TextChangedP` and `TextChangedI`. Deleting all of them would be a bit much to opt-out, no?

**Comment by adamu** [comment]
Was there any documentation added for how to opt out of `editor.action.triggerParameterHints `? I am [seeing a warning](https://github.com/elixir-lsp/elixir-ls/issues/1233) I'd like to avoid, which from the above linked tickets appears others are, too.
