### ISSUE TITLE
Add WSL clipboard configuration in lua to documentation

### ISSUE THREAD

**Issue by robertmonka** [neovim/neovim#25719]
### Problem

There is no official suggestion to set WSL clipboard in lua format.

My suggestion is to add

```
vim.opt.clipboard = {
    name = "WslClipboard",
    copy = {
        ['+'] = "clip.exe",
        ['*'] = "clip.exe"
    },
    paste = {
        ['+'] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
        ['*'] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))'
    },
    cache_enabled = 0
}
```
to documentation and buildin help.

**Comment by clason** [comment]
1. That is actually incorrect, it should be `vim.g.clipboard`.
2. The relevant information is already in `:h clipboard-wsl`; I don't think we should give every single code example twice (once in Vimscript, once in Lua) if the translation is straightforward (as in this case, if you've read `:h lua-guide` -- which is considered required reading).
