### ISSUE TITLE
option to set maximum :messages history length

### ISSUE THREAD

**Issue by mawkler** [neovim/neovim#25723]
### Problem

Currently [the maximum length of `:messages` is 200](https://github.com/neovim/neovim/blob/594ff34581907fed4956d4dc93c033dfdd5f7a69/src/nvim/vim.h#L9) lines, which in my opinion is very low. It makes sense to me to allow the user to set a custom value. I haven't created a PR for Neovim before, but I could give it a try since this seems relatively trivial.

What would be a good name for the option? `maxhistorylength`?

### Expected behavior

The option, let's call it `maxhistorylength` for now, sets the maximum number of history lines.

**Comment by clason** [comment]
Does it need to be configurable? Would it not be sufficient to simply raise the (ancient) value?

**Comment by mawkler** [comment]
@clason I was trying to print debug my LSP config by printing large Lua tables like `vim.lsp.get_clients()` and similar, which quite easilly exceed 200 lines.

**Comment by clason** [comment]
That is useful context, thank you. But for such large output, wouldn't you rather `:put` it in a buffer?

(The long-term goal is to stop unconditionally shoving everything into a single `:messages` area and instead allow different routing for messages depending on type.)

Would it be an alternative to expand the `vim.print` function to optionally specify an output buffer/split?

**Comment by mawkler** [comment]
@clason 

> wouldn't you rather :put it in a buffer

With [noice.nvim](https://github.com/folke/noice.nvim) I already get `:messages` in a buffer, but with less effort.

> The long-term goal is to stop unconditionally shoving everything into a single `:messages` area
>
> Would it be an alternative to expand the `vim.print` function to optionally specify an output buffer/split?

Both of these sound like good ideas but I still think that 200 is way too low, and like you say it is up to personal taste what is _too low_. Therefore it makes sense to me to allow the maximum value to be configured by the user.

**Comment by clason** [comment]
> With [noice.nvim](https://github.com/folke/noice.nvim) I already get :messages in a buffer, but with less effort.

That is not "less effort", noice does _a lot_ of heavy lifting for this, which it shouldn't have to.

And I'm not talking about _all_ messages in a buffer; I'm talking about not (ab)using `:messages` for long-form output in the first place.

> Therefore it makes sense to me to allow the maximum value to be configured by the user.

But options are not free; adding this may be a small number of lines of code, but you also need to
1. document it;
2. ensure that even unreasonable values are handled gracefully (what if someone sets `msghistory=0`?);
3. ensure that it interacts well with other options and plugins (remember `cmdheight=0`?).

Especially 3. implies that adding options adds a superlinear amount of work. So this needs to be worth it, and I am not (yet) convinced of this here. I'm also not convinced that it _is_ a "matter of taste".

So the first step here is to investigate whether just raising the current value to, say, `2000` has any performance implications.

**Comment by mawkler** [comment]
Ok, I see!

**Comment by ColinKennedy** [comment]
I was thinking it'd be nice to have a control for the opposite situation - when you have an error in some autocmd that's super spammy. It'd be nice to, when debugging / troubleshooting, to be able to reduce the total history down so you're not stuck scrolling through the same messages just to find the print echo / message that you needed to see

**Comment by MagicDuck** [comment]
Would love to see this increased. It's super annoying when debugging plugins...

**Comment by justinmk** [comment]
Let's increase the max at least. There is no reason it should be so low.

**Comment by mawkler** [comment]
What's a good number? 1,000 seems too low in my opinion because with three language servers attached (`zk`, `null-ls` and `ltex`) the output of `:=vim.lsp.get_clients()` is 1,120 lines long for me. Is 10,000 too much?

**Comment by Shougo** [comment]
I think the default is 1000 and it is configurable is better.

**Comment by Shougo** [comment]
I will do it.

**Comment by Shougo** [comment]
Done.

https://github.com/vim/vim/pull/16048
