### ISSUE TITLE
Telescope freezes on input with long path in results

### ISSUE THREAD

**Issue by geril2207** [neovim/neovim#25727]
### Problem

Bug was introduced in `bf70a33`(prev commit `9f32deb` doesn't have it). When using `:Telescope find_files` using fd in large projects where there are many folders(long path), input freezing for some time.

Works fine:
https://github.com/neovim/neovim/assets/62308020/ed03561c-832a-4274-b4d9-623c64b2448b

Works not fine:
https://github.com/neovim/neovim/assets/62308020/58d5468d-1bd7-46f9-ac82-b2b66a0944f3

### Steps to reproduce

git clone --depth 1 https://github.com/facebook/react.git
try using telescope find_files

### Expected behavior

Works without freezing

### Neovim version (nvim -v)

v0.10.0-dev-bf70a33

### Vim (not Nvim) behaves the same?

idk

### Operating system/version

Fedora 38

### Terminal name/version

alacritty

### $TERM environment variable

xterm256-color

### Installation

from repo

**Comment by clason** [comment]
That's https://github.com/neovim/neovim/pull/25629, for the record (@zeertzjq)

It would be helpful to have a more detailed _Neovim_ bug report, i.e., which exact call makes Neovim freeze. Ideally, you could construct a minimal reproducing example without the Rube Goldberg machine that is telescope.

**Comment by zeertzjq** [comment]
Is there any actual problem? If view keeping changing when you are typing rapidly you can't see them clearly anyway.

**Comment by zeertzjq** [comment]
Oh, actually this is the problem I described in https://github.com/neovim/neovim/issues/25643#issuecomment-1763376440

> if events are always available, UI is never flushed, even if input is processed.

**Comment by geril2207** [comment]
This will not be visible in all projects. I came across this in a small project but with a lot of subfolders and immediately downgrade nvim, because it ruins the user experience after inputing at least 3 characters with my typing speed ~100wpm.
Maybe we need to wait for another reports, but imho this need to be fixed.

**Comment by geril2207** [comment]
On the left, in some projects most of cases, i can see what i am typing only in the end. On the right i see every inputed char and this make editor more responsive, even if there other loading. https://github.com/neovim/neovim/assets/62308020/bcd3fb0f-0680-41da-8bee-848c389c7e52
