### ISSUE TITLE
os_unix_defs.h split

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#2573]
Currently, all default path (like 'backupdir') seems to be defines is `os_unix_defs.h`. There are the files `os/win_defs.h` and `os/unix_defs.h`, but they only set the tmp path. Maybe we should split `os_unix_defs.h` in those files, so that it would be easier to define os-specific defaults ?

Funfact : 
`os_unix_defs.h:1:  #ifndef NVIM_OS_UNIX_DEFS_LEGACY_H`

**Comment by equalsraf** [comment]
@Yamakaky that was the main idea, to move things out of src/nvim/os_unix_defs.h until it is gone. The header guards changed in #1493.

**Comment by Yamakaky** [comment]
is someone working on it ? If not, I may try.

**Comment by splinterofchaos** [comment]
:+1:

**Comment by equalsraf** [comment]
#696 was the last time I saw any mention of this. A [search](https://github.com/neovim/neovim/search?q=os_unix_defs.h&state=open&type=Code&utf8=%E2%9C%93) shows three files with references. :+1:

**Comment by Yamakaky** [comment]
To be clear: I will put `os_unx_defs` in `os/unix_defs.h` and `os/win_defs.h` and modify the defaults for windows.

**Comment by equalsraf** [comment]
@Yamakaky yes. You can leave win_defs.h alone if you want - or have a look [here](https://github.com/equalsraf/neovim/blob/tb-mingw/src/nvim/os/win_defs.h), but there is no point in copying everything blindly. If there are defines that have the same value for both maybe consider putting them in os_defs.h

**Comment by Yamakaky** [comment]
That's what I meant.

**Comment by Yamakaky** [comment]
Partially done.

**Comment by Yamakaky** [comment]
Two other problems:
- WIN32 -> does it detect windows 64 bit ?
- Maybe we should drop MAXNAMLEN and MAXPATHL, and use PATH_MAX and NAME_MAX instead ?

**Comment by equalsraf** [comment]
I didn't get a chance to have a deep look yet

WIN32 is true for both 32 and 64 bits

> it defaults to unix if not on windows, which could be a problem if a new architecture is added.

True but, most other platforms seem to be Unix-ish, so it should be ok until someone wants to add support to a new system.

> I can't find which os defines DIRSIZ. Is it legacy ?

Good question, cant find it the Vim source either. But it exists on my linux system (linux/coda.h) and in OpenBSD (sys/dir.h) so it must come from system headers.

> Maybe we should drop MAXNAMLEN and MAXPATHL, and use PATH_MAX and NAME_MAX instead ?

I would leave those be for now, I can't be sure without testing in other systems and it is not harmful.
