### ISSUE TITLE
vim.snippet through error and wrong indent 

### ISSUE THREAD

**Issue by glepnir** [neovim/neovim#25743]
### Problem

1. select a snippet and confirm  then visual select the whole snippet delete `index out of bounds` snippet.lua lines:142
2. wrong indent after expand snippet

### Steps to reproduce

1. using lua-ls 
2. type `local` select `local function` index and expand snippet select whole snippet then `d` 
3. type `if some condition then` there will have a snippet `then end` expand it . redundant blankline and `end` have a wrong indent.

![image](https://github.com/neovim/neovim/assets/41671631/3768bd32-00ef-47aa-8bd9-c06e7d0554e0)

### Expected behavior

works fine.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3a3e025

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

build from source.

**Comment by MariaSolOs** [comment]
@glepnir I'm having trouble reproducing this. How are you selecting and removing the snippet?

**Comment by glepnir** [comment]
just visual select them and d. 


https://github.com/neovim/neovim/assets/41671631/57406033-53b3-429b-8503-7ea1a2ff2d73

**Comment by MariaSolOs** [comment]
Just to be sure:

1. The snippet is being expanded with `vim.snippet.expand`.
2. From insert mode you escape to normal mode, CTRL-V to enter visual line mode and select the 3 lines of the snippet.
3. You press `d`.

If those are the steps, I'm still not getting the error. I've disabled `LuaSnip` entirely.

> (notice comletion use my own plugin . but i think this is not important)

Maybe it does. Could you please share your config?

**Comment by glepnir** [comment]
Download [epo](https://github.com/nvimdev/epo.nvim) to somewhere.

```lua
vim.opt.cot = 'menu,menuone,noinsert'
vim.opt.rtp:append('path/toepo.nvim')
require('epo').setup({})
vim.keymap.set('i', '<CR>', function()
  return vim.fn.pumvisible() == 1 and '<C-Y>' or '<CR>'
end, { expr = true })

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'lua',
  callback = function()
    vim.lsp.start({
      name = 'luals',
      cmd = { 'lua-language-server' },
      filetypes = 'lua',
      root_dir = vim.uv.cwd(),
    })
  end,
})
```

1. `nvim --clean -u min.lua test.lua` 
2. type `l` select second index CR confrim
3. `<ESC>` to normal . Visual select three lines `d`

**Comment by MariaSolOs** [comment]
I can reproduce it now. The snippet must be inserted at the end of the file.

**Comment by glepnir** [comment]
> The snippet must be inserted at the end of the file.

confused on this.

**Comment by MariaSolOs** [comment]
> confused on this.

@glepnir I couldn't reproduce it before because I was trying it in the middle of a non-empty file. I'm working on the fix.
