### ISSUE TITLE
Support clipboard in some containers on macos

### ISSUE THREAD

**Issue by waterlens** [neovim/neovim#25753]
### Problem

Currently, the `pbcopy/pbpaste` provider is only enabled on macOS. It might be too conservative since a container or a virtual machine (which are different platforms like Linux) may use the `pbcopy/pbpaste` of the host macOS. It's exactly the case when using OrbStack.

### Expected behavior

 I have a fix for this problem in #25702. After the change, the providers will be
```
							      *clipboard-tool*
The presence of a working clipboard tool implicitly enables the '+' and "*"
registers. Nvim looks for these clipboard tools, in order of priority:
  - |g:clipboard|
  - pbcopy, pbpaste (macOS)
  - wl-copy, wl-paste (if $WAYLAND_DISPLAY is set)
  - waycopy, waypaste (if $WAYLAND_DISPLAY is set)
  - xsel (if $DISPLAY is set)
  - xclip (if $DISPLAY is set)
  - lemonade (for SSH) https://github.com/pocke/lemonade
  - doitclient (for SSH) https://www.chiark.greenend.org.uk/~sgtatham/doit/
  - win32yank (Windows)
  - termux (via termux-clipboard-set, termux-clipboard-set)
  - tmux (if $TMUX is set)
  - pbcopy, pbpaste
 ```

**Comment by clason** [comment]
If there's a PR already, you don't need to open an issue for it. Instead include the rationale in your PR description (the "Problem: ... Solution: ..." format is good for that).
