### ISSUE TITLE
Neovim sometimes scrolls current line to bottom of window after jumping back to file with <C-o>

### ISSUE THREAD

**Issue by Asheq** [neovim/neovim#25759]
### Problem

After jumping back to a file with `<C-o>`, sometimes neovim scrolls the current line to the **center** of the window as far as possible (expected). But other times it scrolls it to the **bottom** of the window (unexpected).

This is annoying because I lose context around the current line.

In contrast, jumping back to a buffer using `:edit`, `:buffer`, or `:find` always seems to scroll the line to the **center** as far as possible (expected).

https://github.com/neovim/neovim/assets/4657140/8f356ffd-fb42-47a6-a004-9bce0c16cd23

### Steps to reproduce

Make terminal 25 cells tall (I don't know if this matters)

```shell
nvim --clean file
```

```vimscript
35G
zz
:edit other
<C-o>
```

[file.txt](https://github.com/neovim/neovim/files/13078619/file.txt)
[other.txt](https://github.com/neovim/neovim/files/13078620/other.txt)

### Expected behavior

Neovim should not scroll the current line to the bottom of the window after jumping back to a file with `<C-o>`

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

yes, 9.0.1544

using `vim --clean file` and `:set scrolloff=0`

### Operating system/version

macOS 13.5.1 (22G90)

### Terminal name/version

kitty 0.29.0

### $TERM environment variable

xterm-kitty

### Installation

homebrew

**Comment by zeertzjq** [comment]
Workaround: `:set jumpoptions+=view`

**Comment by zeertzjq** [comment]
Regression between v0.7.0 and v0.8.0

**Comment by zeertzjq** [comment]
Hmm, this happens with `vim --clean`, but not with `vim -u NONE -i NONE`.

**Comment by zeertzjq** [comment]
Oh, this only happens in Vim because of the default `vimStartup` autocommand, which is not present in Nvim, so this bug doesn't come from Vim.

**Comment by Asheq** [comment]
> Workaround: `:set jumpoptions+=view`

I am aware of this option. However, I don't like its current behavior because I don't like that the window scrolls when I jump back (using `<C-o>`) to a previously visited location that is already visible in the window. For example:

https://github.com/neovim/neovim/assets/4657140/4cfff675-3641-4777-bef3-18e75b7682df

Anyway, this is a separate discussion.
