### ISSUE TITLE
Mapping strings of keys in the terminal emulator doesn't work

### ISSUE THREAD

**Issue by Soares** [neovim/neovim#2575]
I'd like to be able to add the following mappings to the terminal emulator:

    tnoremap <C-b>h <C-\><C-n><C-w>h
    tnoremap <C-b>j <C-\><C-n><C-w>j
    tnoremap <C-b>k <C-\><C-n><C-w>k
    tnoremap <C-b>l <C-\><C-n><C-w>l

But the terminal emulator doesn't seem to handle mappings more than one character long. The above terminal mappings do nothing.

The below variants also do nothing:

    tnoremap jj aoeu
    tnoremap <C-g><C-g> aoeu

But I verified that tnoremap is not completely broken by verifying that the following mapping *does* work:

    tnoremap j x

**Comment by critiqjo** [comment]
All of the mappings you mentioned worked for me... Have you tried those mappings after loading Neovim without `nvimrc` by `nvim -u NONE`. Which commit of Neovim are you using, the terminal emulator and the OS?

**Comment by Soares** [comment]
Opps, you're right, problem was on my end. Sorry for the noise.
