### ISSUE TITLE
E492: Not an editor command: sh

### ISSUE THREAD

**Issue by miklcct** [neovim/neovim#25768]
### Problem

`sh` is not implemented in Neovim as an editor command, while it exists in Vim which launches the default shell.

### Expected behavior

It should launch the default shell, in the exact way Vim does.

**Comment by mike325** [comment]
`:sh[ell]` was removed a legacy command removed from Neovim in the early versions, not sure it's actually needed/useful with the current state of the editor, specially when you can `<C-z>` back to your shell, use `:terminal` inside the editor

[:h nvim-removed](https://neovim.io/doc/user/vim_diff.html#nvim-removed)
