### ISSUE TITLE
dynix/ptx support

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#2576]
Do we support [dynix/ptx](https://en.wikipedia.org/wiki/DYNIX) ? There is a define related to it in os_unix_defs.h (search UFS_MAXNAMLEN). If not, I will remove it.

**Comment by Pyrohh** [comment]
Definitely not. This thread might be of use: https://github.com/neovim/neovim/pull/1491#issuecomment-63591634.

**Comment by Pyrohh** [comment]
The general consensus seems to be that we only support platforms that libuv supports. Note that Open/FreeBSD seems to be supported by libuv as well, although it doesn't state it in their README.md, so support for them shouldn't be removed.

**Comment by Yamakaky** [comment]
Ok. PR incoming !

**Comment by Pyrohh** [comment]
:)
