### ISSUE TITLE
Add gap between action buttons on home page

### ISSUE THREAD

**Issue by ahmod001** [neovim/neovim#25773]
### Problem

On the home page, the two action buttons are too close together. When hovering over one button, it crashes with the neighboring button. Adding a little space between the buttons would enhance the look and feel of the page.

![image](https://github.com/neovim/neovim/assets/121039395/9fc0b0fa-e902-46da-b63d-3eb24cb950bb)
![image](https://github.com/neovim/neovim/assets/121039395/ee30e387-704b-42bd-b63a-5858bb0013e8)

### Steps to reproduce

1.     Go to the home page.
2.     Hover over one of the action buttons.
3.     Observe that the button crashes with the neighboring button.

### Expected behavior

There should be a small gap between the two action buttons, so that they do not crash when hovering.

### Neovim version (nvim -v)

i don't know

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Windows 11

### Terminal name/version

not applicable

### $TERM environment variable

not applicable

### Installation

from source (using spack for convenience)

**Comment by clason** [comment]
Please open this suggestion over at neovim/neovim.github.io.
