### ISSUE TITLE
Problem with RPATH on macOS "Library not loaded: libluv.1.dylib".

### ISSUE THREAD

**Issue by albestro** [neovim/neovim#25770]
### Problem

Since `libluv-1.44` neovim build fails with

```bash
➜  build-1.45 git:(v0.9.4) ✗ make
[  0%] Built target update_version_stamp
[ 92%] Built target nvim
[ 92%] Built target nvim_runtime_deps
[ 92%] Generating nvim.pot
dyld[9773]: Library not loaded: libluv.1.dylib
  Referenced from: <3DE9CF70-55FA-330B-8A0B-BD1AC36221DE> /Users/ialberto/workspace/repos/neovim.git/build-1.45/bin/nvim
  Reason: tried: 'libluv.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibluv.1.dylib' (no such file), 'libluv.1.dylib' (no such file), '/usr/local/lib/libluv.1.dylib' (no such file), '/usr/lib/libluv.1.dylib' (no such file, not in dyld cache), '/Users/ialberto/workspace/repos/neovim.git/build-1.45/src/nvim/po/libluv.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/ialberto/workspace/repos/neovim.git/build-1.45/src/nvim/po/libluv.1.dylib' (no such file), '/Users/ialberto/workspace/repos/neovim.git/build-1.45/src/nvim/po/libluv.1.dylib' (no such file), '/usr/local/lib/libluv.1.dylib' (no such file), '/usr/lib/libluv.1.dylib' (no such file, not in dyld cache)
/bin/sh: line 1:  9773 Abort trap: 6           ../../../bin/nvim -u NONE -i NONE -n --headless --cmd "set cpo+=+" -S /Users/ialberto/workspace/repos/neovim.git/src/nvim/po/tojavascript.vim /Users/ialberto/workspace/repos/neovim.git/build-1.45/src/nvim/po/nvim.pot /Users/ialberto/workspace/repos/neovim.git/runtime/optwin.vim
make[2]: *** [src/nvim/po/nvim.pot] Error 134
make[1]: *** [src/nvim/po/CMakeFiles/translations.dir/all] Error 2
make: *** [all] Error 2
```

Previously, all `neovim` builds were implicitly going for the static version of `libluv`, due to

https://github.com/neovim/neovim/blob/1094d0c0dbd0f37ccc0f1d18c73c6066e5690664/cmake/FindLuv.cmake#L2

Indeed, up to `libluv@1.43` (included) the library names were

```bash
lib
├── libluv.1.43.0.dylib
├── libluv.1.dylib -> libluv.1.43.0.dylib
├── libluv.dylib -> libluv.1.dylib
├── libluv_a.a
├── lua
│   └── 5.1
│       └── luv.so
└── pkgconfig
    └── libluv.pc

4 directories, 6 files
```

So the first entry `luv_a` was matching with `libluv_a.a`, the static library, and it was getting used.

From `libluv-1.44` on, the library names have been changed (see https://github.com/luvit/luv/commit/9d602ab12654d3adb53f34457390f534eb85f5d6) so the situation now is

```bash
lib
├── libluv.1.44.2.dylib
├── libluv.1.dylib -> libluv.1.44.2.dylib
├── libluv.a
├── libluv.dylib -> libluv.1.dylib
├── lua
│   └── 5.1
│       └── luv.so
└── pkgconfig
    └── libluv.pc

4 directories, 6 files
```

So static libraries does not have anymore any name based priority, and the shared library is picked first.

This does not represent a problem on linux, where it still works correctly, but on macOS the RPATH management seems not working correctly.

It is probably due to the custom basic `FindLuv.cmake` CMake module, which should be probably improved in order to deal also with the more requiring RPATH management on macOS (not an expert, but probably it requires @rpath/libluv.dylib` or something like that as library name). Not sure, but if the detection is improved and cmake targets are used, it would be probably easier to let CMake do the right thing also on macOS.

### Steps to reproduce

Just try building on macOS any neovim version (tested with 0.9.0 and 0.9.4) using as dependency `libluv-1.44` (tested with 1.44.2-0, 1.44.2-1, 1.45.0-0) will fail as soon as build starts using the `nvim` executable because it does not find `libluv` dynamic library.

### Expected behavior

It should build 😁

### Neovim version (nvim -v)

commit d772f697a281ce9c58bf933997b87c7f27428a60 (HEAD, tag: v0.9.4, tag: stable)

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

macOS 13.6

### Terminal name/version

not applicable

### $TERM environment variable

not applicable

### Installation

from source (using spack for convenience)

**Comment by dundargoc** [comment]
> if the detection is improved and cmake targets are used, it would be probably easier to let CMake do the right thing also on macOS.

Uh, this kinda sounds like "if we improve the files then the files will have been improved". Do you have any concrete proposals or suggestions?

Also yeah, do try the suggestion from the spack person to see if it solves the problem.

**Comment by dundargoc** [comment]
Thanks for the follow-up. I don't think we need to do something from our side, cmake has deprecated versions 3.4- and our dependencies should be bumping their versions in their upcoming releases.
