### ISSUE TITLE
:terminal generates E475 if $SHELL is set to an absolute path on Windows

### ISSUE THREAD

**Issue by miklcct** [neovim/neovim#25776]
### Problem

`:terminal` generates error E475 if the environment variable `SHELL` is set to an absolute path on Windows. For example, if `SHELL` is `C:\msys64\usr\bin\fish.exe`, the editor throws `E475: Invalid value for argument cmd: 'C:msys64usr^Hin^Lish.exe' is not executable`

### Steps to reproduce

1. set the environment variable `SHELL` to the absolute path of a valid shell.
2. run Neovim
3. enter `:terminal`

### Expected behavior

A terminal should open in the editor.

### Neovim version (nvim -v)

v0.9.4

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal 1.18.2822.0

### $TERM environment variable

xterm-256color

### Installation

Windows Installer

**Comment by zeertzjq** [comment]
Fixed by #25994
