### ISSUE TITLE
Spelling error backwards navigation stuck at first spelling error

### ISSUE THREAD

**Issue by languitar** [neovim/neovim#2577]
When having a document with multiple spelling errors and navigating backwards inside these errors with `[s`, the cursor gets stuck at the end of the first misspelled word and cannot be moved further backwards. This works in usual vim.

**Comment by languitar** [comment]
Oh, as an addition: he cursor ends up after the misspelled word. So you cannot event get a suggestion for that affected word, but only for the one after the cursor.

**Comment by Pyrohh** [comment]
Now that #2813 is merged, is this still an issue @languitar?

**Comment by languitar** [comment]
Thanks, works now.
