### ISSUE TITLE
Support `escape=<char>` parser directive when highlighting Dockerfile for syntax

### ISSUE THREAD

**Issue by lgrosz** [neovim/neovim#25783]
### Problem

When a Dockerfile has an `escape` parser directive...

```
# escape=`
...
```

at its top, it's escape character is now \` instead of  `\`.

Syntax is highlighted improperly when this option is set.

### Expected behavior

Syntax should highlighted as if the escape character is that which is set.

See [Dockerfile reference](https://docs.docker.com/engine/reference/builder/#parser-directives)

**Comment by zeertzjq** [comment]
Please open this request at https://github.com/vim/vim/issues
