### ISSUE TITLE
The command line cannot correctly parse ANSI escape sequences output by pwsh

### ISSUE THREAD

**Issue by matteocoder** [neovim/neovim#25800]
### Problem

When using pwsh as '&shell', if the output generated by an external command contains colours, the command line doesn't correctly parse the escape sequences, which then pollute the output itself. Vim can correctly parse those escape sequences, and shows coloured text.

### Steps to reproduce

Prerequisites:
Create a file called `test.vim` containing the following code:
```
let &shell = executable('pwsh') ? 'pwsh' : 'powershell'
let &shellcmdflag = '-NoLogo -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new();$PSDefaultParameterValues[''Out-File:Encoding'']=''utf8'';Remove-Alias -Force -ErrorAction SilentlyContinue tee;'
let &shellredir = '2>&1 | %%{ "$_" } | Out-File %s; exit $LastExitCode'
let &shellpipe  = '2>&1 | %%{ "$_" } | tee %s; exit $LastExitCode'
set shellquote= shellxquote=
```
and a `Microsoft.PowerShell_profile.ps1` (which should be placed in the appropriate location returned by `$PROFILE`) containing:
```
$PSReadLineOptions = @{
    ContinuationPrompt  = "${pspromptcolour}>> `e[0m"
    ViModeIndicator     = 'Script'
    ViModeChangeHandler = $Function:OnViModeChange
    EditMode            = 'Vi'
    PredictionViewStyle = 'ListView'
    PromptText          = "${pspromptcolour}> ", 'x '
    Colors              = @{
        Selection              = "`e[1;35m"
        ListPredictionSelected = "`e[1;35m"
    }
    AddToHistoryHandler = {
        param($command)
        if ($command -like ' *') {
            return $false
        }
        elseif (@('exit', 'clear') -contains $command) {
            return $false
        }
        else {
            return $true
        }
    }
}

Set-PSReadLineOption @PSReadLineOptions
```

1. `nvim --clean`
2. `:source .\test.vim`
3. ensure that `shell=pwsh`
4. `:!pwd`

This process outputs:

```
^[[31;1mSet-PSReadLineOption: ^[[0mC:\Users\matteocoder\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:260^[[0m
^[[31;1m^[[0m^[[36;1mLine |^[[0m
^[[31;1m^[[0m^[[36;1m^[[36;1m 260 | ^[[0m ^[[36;1mSet-PSReadLineOption @PSReadLineOptions^[[0m
^[[31;1m^[[0m^[[36;1m^[[36;1m^[[0m^[[36;1m^[[0m^[[36;1m     | ^[[31;1m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^[[0m
^[[31;1m^[[0m^[[36;1m^[[36;1m^[[0m^[[36;1m^[[0m^[[36;1m^[[31;1m^[[31;1m^[[36;1m     | ^[[31;1mThe handle is invalid.^[[0m

^[[32;1mPath^[[0m
^[[32;1m----^[[0m
C:\Users\matteocoder
```

This test highlights another problem with the interaction between pwsh and neovim: for some reason, option splatting seems to fail. I don't know what the culprit is in this case, so I guess it would be better to discuss this aspect in a separate issue.

### Expected behavior

The command line should display coloured text.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-9dc4404 Build type: RelWithDebInfo LuaJIT 2.1.1697887905 Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /DWIN32 /D_WINDOWS /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -wd4003 -wd4715 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src     system vimrc file: "$VIM\sysinit.vim"   fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

### Vim (not Nvim) behaves the same?

no, Vim 9.0.2026

### Operating system/version

Microsoft Windows 10.0.22621

### Terminal name/version

PowerShell 7.4.0-preview.6, Windows Terminal 1.18.2822.0

### $TERM environment variable

N/A

### Installation

winget

**Comment by zeertzjq** [comment]
This is not supported.

**Comment by matteocoder** [comment]
@zeertzjq Thank you for the reply. If possible, can you elaborate more on why it is not supported? Also, Is there a workaround that I could use to alleviate this, other than just using another shell?

**Comment by zeertzjq** [comment]
1. See #1496
2. Use `:terminal`

**Comment by matteocoder** [comment]
@zeertzjq I see. Thank you.
