### ISSUE TITLE
doc: unclear doc in treesitter.txt

### ISSUE THREAD

**Issue by xsh005** [neovim/neovim#25803]
### Problem

When browsing vim.treesitter docs I found a weird highlight
https://github.com/neovim/neovim/blob/add1b10b79011d1af61419a63cc8ef4645f45bbf/runtime/doc/treesitter.txt#L1177
I suppose it means boolean OR Range OR nil, but |Range| got parsed into `helpHyperTextJump` which is not intended

### Steps to reproduce

```shell
nvim --clean -c "tab help *LanguageTree:parse()* | norm 11jzz"
```

### Expected behavior

Range is not a link, and it tells me what exactly is a Range

### Neovim version (nvim -v)

NVIM v0.10.0-dev-9dc4404
Build type: RelWithDebInfo
LuaJIT 2.1.1697887905

### Vim (not Nvim) behaves the same?

probably not

### Operating system/version

Fedora

### Terminal name/version

Kitty

### $TERM environment variable

xterm-kitty

### Installation

Github binary release zip version

**Comment by clason** [comment]
This is not intended to be a taglink but a type union. `Range` is an internal type that is not publicly documented.

**Comment by clason** [comment]
(and I don't get any bold text; treesitter is _not_ parsing the `|Range|`, so that must be some other thing on your side)

**Comment by xsh005** [comment]
> (and I don't get any bold text; treesitter is _not_ parsing the `|Range|`, so that must be some other thing on your side)

Sorry, it's prbly my colorscheme making this bold, but nonetheless

**Comment by xsh005** [comment]
Also any idea what exactly is a Range? Is it a table or sth

**Comment by clason** [comment]
Yes, of course (everything is a table), it contains start and end positions as row, column, and (optionally) byte.

**Comment by xsh005** [comment]
Thank you!
> Yes, of course (everything is a table)

Ah but when I try to `vim.print` a TSNode it gives me `<userdata1>`

**Comment by clason** [comment]
That's something completely different.

**Comment by xsh005** [comment]
:cry: kk

**Comment by clason** [comment]
(it's a C object accessible through the tree-sitter API, not a native Lua object)

**Comment by xsh005** [comment]
Oh! Thanks for the explanation :+1:
