### ISSUE TITLE
Terminal: command and current path artifacts printed when using Oh My Zsh

### ISSUE THREAD

**Issue by lynndylanhurley** [neovim/neovim#2581]
I get the following output when I type echo foo and echo bar using the built-in Neovim terminal:

~~~sh
❯ echo "foo"
echofoo
..thbox/dbx-api
~/Code/Healthbox/dbx-api master
❯ echo "bar"
echobar
..thbox/dbx-api
~/Code/Healthbox/dbx-api master
~~~

I've narrowed the issue down to Oh My Zsh. I have posted an issue with that project (robbyrussell/oh-my-zsh#3823), but I thought maybe someone here would be able to help.

[Here](https://gist.github.com/lynndylanhurley/06d4b9913c6c815b6121) is my `nvim --version` info.

**Comment by justinmk** [comment]
What terminal are you using, and what is `$TERM`?

**Comment by lynndylanhurley** [comment]
Hi @justinmk - thanks for the quick response.

I'm using iTerm2, `$TERM` is `screen-256color`.

**Comment by justinmk** [comment]
Does it happen with `nvim -u NONE`? What is `:echo &title &titlestring`?

**Comment by lynndylanhurley** [comment]
@justinmk - I was running `nvim -u NONE +term`.

`:echo &title &titlestring` returns `0`.

**Comment by justinmk** [comment]
If you `:redraw!` does it get corrected?

**Comment by lynndylanhurley** [comment]
@justinmk - no it does not.

**Comment by justinmk** [comment]
Config issue per https://github.com/robbyrussell/oh-my-zsh/issues/3823:

> I can partially reproduce. Looks like this is due to a bad $TERM value being set in your ~/.zshrc, not an OMZ or neovim issue.
> It appears that your ~/.zshrc is forcibly setting the $TERM terminal type when it is run from inside tmux or nvim.

**Comment by lynndylanhurley** [comment]
I was able to fix this by removing `export TERM=screen-256color` from my `.zshrc` file. Sorry, should have closed.
