### ISSUE TITLE
let-heredoc breaks plugin

### ISSUE THREAD

**Issue by MaxGyver83** [neovim/neovim#25810]
### Problem

The plugin [vim-haredoc](https://git.sr.ht/~torresjrjr/vim-haredoc) works fine in vim 9.0.2070 but it fails to load in Neovim 0.9.4.

After installing `vim-haredoc`, when I start Neovim (with or without any file), I get:

```
Error detected while processing /home/max/.dotfiles/vim/.vim/pack/plugins/start/vim-haredoc/plugin/haredoc.vim:
line   83:
E126: Missing :endfunction
```

But `haredoc.vim` contains one `function` and one `endfunction`.

This seems to be the problematic code:

```vim
let resolvecmd =<< trim eval CMD
awk '/use [a-zA-Z:]*{parent};/ {{
	gsub("(use *|;.*)", "");
	print $1 "::" "{base}"
}}' {expand("%")} 2>&-
CMD
```

When I comment out these lines, the error doesn't show up.

### Steps to reproduce

1. Install `vim-haredoc`
2. Start neovim

### Expected behavior

Neovim does not complain about a missing `endfunction`.

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

No, vim 9.0.2070

### Operating system/version

Arch Linux

### Terminal name/version

st

### $TERM environment variable

tmux-256color

### Installation

pacman

**Comment by zeertzjq** [comment]
Already fixed.

**Comment by MaxGyver83** [comment]
But not yet released? Will it be in Neovim 0.9.5?

**Comment by zeertzjq** [comment]
Please try nightly version.

**Comment by zeertzjq** [comment]
And no, it will be in v0.10.0.

**Comment by MaxGyver83** [comment]
It works in v0.10.0-dev-ac353e8. Thank you!
