### ISSUE TITLE
Winbar disappears when Cmdline window is activated

### ISSUE THREAD

**Issue by lbrayner** [neovim/neovim#25829]
### Problem

On the current tab, suppose there are 2 windows visiting different buffers, `'laststatus'` is 3 (always and ONLY the last window). If the user enters the Cmdline window, the statusline shows information for that window, and the only way to know which files the other windows are displaying is to consult the `'winbar'`, but it disappears!

### Expected behavior

In that situation described above, display the `'winbar'`.

**Comment by zeertzjq** [comment]
Please create a bug report.

**Comment by lbrayner** [comment]
My mistake, this happened because when trying to find out if I'm in the Cmdline window, I used `getcmdwintype`, which also returns a value for all other windows in the tab. The intention was to leave the Cmdline window's winbar empty.
