### ISSUE TITLE
neovim is completely frozen when i wake my computer from sleep

### ISSUE THREAD

**Issue by xeros-and-ones** [neovim/neovim#25832]
### Problem

when i have nvim with open file and i put my computer to sleep and bring back up i find nvim completely frozen that i have to force close the terminal window, tab or split.
the terminal itself works fine because I've tested it with kitty and wezterm, it's only neovim that's frozen.

### Steps to reproduce

open a file with nvim
put computer to sleep
wake up computer

### Expected behavior

neovim be fine and i'am able to continue working.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1420+g9dc440400 & NVIM v0.9.4

### Vim (not Nvim) behaves the same?

no, 9.0.2070

### Operating system/version

endeavourOS

### Terminal name/version

kitty 0.30.1 & wezterm 20230712-072601-f4abf8fd

### $TERM environment variable

xterm-256color & (wezterm & kitty terminfos)

### Installation

build from repo

**Comment by Jockey12** [comment]
i have the same problem, and yes it was yanky, from the lazynvim extras. thanks
