### ISSUE TITLE
tui: support 'guicursor' in terminal

### ISSUE THREAD

**Issue by shmerl** [neovim/neovim#2583]
I was trying to change the cursor shape for insert mode in nvim using Konsole, and so far the only way to do that was to call nvim like this:

```
TERM_PROGRAM=iTerm.app NVIM_TUI_ENABLE_CURSOR_SHAPE=1 nvim
```

Since according to this commit: 25ceadab37edba13f5afa78d8b4723da03ef35f0 from issue #2007, terminal detection is hardcoded to either read TERM_PROGRAM as "iTerm.app" or to use xterm extended DECSCUSR sequences otherwise. Konsole doesn't support xterm sequences (I'll probably file a bug about it), but it does support iTerm like sequences. So the example above works.

However it would be useful to allow more flexible terminal detection, and in general instead of hardcoding the shape for both modes, allow the user to define the shape of the cursor for each of them explicitly (for example what if user wants an underscore cursor, and so on).

Another idea is to allow changing cursor shape for more modes than just INSERT / the rest. For example for INSERT, REPLACE, VISUAL etc.

**Comment by splinterofchaos** [comment]
I started a PR, #2391, that would make the code neovim sends customisable, but I actually have this problem on gnome-terminal (at least my version) where I specific command must be run to change the cursor shape. Not certain of the best solution at this point.

**Comment by shmerl** [comment]
I'm not sure if cursor shape can be changed in gnome-terminal with escape sequences at all. It can be changed with some gconf tweaks, but it's very different from what other terminals implement (i.e. escape sequences). Anyway, there is no uniform way of doing it, so not every terminal can be supported even if some methods are implemented.

For xterm these sequences work:

    # blinking block
    printf '\e[1 q'
    # steady block
    printf '\e[2 q'
    # blinking underscore
    printf '\e[3 q'
    # steady underscore
    printf '\e[4 q'
    # blinking bar
    printf '\e[5 q'
    # steady bar
    printf '\e[6 q'

For Konsole these work:

    # blinking block
    printf '\e]50;CursorShape=0;BlinkingCursorEnabled=1\x7'
    # steady block
    printf '\e]50;CursorShape=0;BlinkingCursorEnabled=0\x7'
    # blinking bar
    printf '\e]50;CursorShape=1;BlinkingCursorEnabled=1\x7'
    # steady bar
    printf '\e]50;CursorShape=1;BlinkingCursorEnabled=0\x7'
    # blinking underscore
    printf '\e]50;CursorShape=2;BlinkingCursorEnabled=1\x7'
    # steady underscore
    printf '\e]50;CursorShape=2;BlinkingCursorEnabled=0\x7'

**Comment by shmerl** [comment]
I'll file a but for Konsole to support DECSCUSR sequences too, but it might take a while before anyone would implement that.

**Comment by shmerl** [comment]
According to this, gnome-terminal might work in the future: https://bugzilla.gnome.org/show_bug.cgi?id=720821

**Comment by shmerl** [comment]
Konsole bug: https://bugs.kde.org/show_bug.cgi?id=347323

**Comment by splinterofchaos** [comment]
Just an updated thought on this:

It's really annoying that for gnome-terminal 2.x and below, you have to run an external command to change the cursor shape, and some other terminals don't support the xterm sequences or have alternatives, but I'm thinking right now that having a cursor shape provider that would only be invoked for TUI's might be the most comprehensive solution. Examples (untested):
```vim
function SetCursorShapeGnome(mode)
  let mode_to_shape = { 'normal':'block', 'insert':'ibeam', 'replace':'underline'}
  call system('gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape ' . mode_to_shape[mode])
endfunction
```
And for xterm-based terminals and Konsole, invoking `$ echo <code>` should do if `:echo '<code>'` doesn't.

**Comment by tarruda** [comment]
>  but I'm thinking right now that having a cursor shape provider that would only be invoked for TUI's might be the most comprehensive solution. Examples (untested):

The idea is nice, but there's a problem with using the provider infrastructure: Nvim allows for a UI running in another machine/process, and this function would be executed in the core(server) process.

**Comment by egmontkob** [comment]
@splinterofchaos Re gnome-terminal 2.x (or mate-terminal) and the gconftool hack: Please don't this this, it's broken by design because it does not only alter the current terminal but also all other gnome-terminal windows running now (and in the future) of the same profile. It's unfair from a terminal application to change the look of other terminal tabs/windows (and even breaking the look of other neovim instances running there).

gnome-terminal 3.16+ supports DECSCUSR. IMO people who prefer to get stuck in the past should, well, accept that they are stuck in the past and hence don't get the full functionality.

**Comment by Shougo** [comment]
The terminal cursor should be customize-able by 'guicorsor' option in Vim.

**Comment by teto** [comment]
I've looked quickly at the implementation, how guicursor UI externalization would look like ?
The cursor appareance is described in the structure "cursorentry_T" https://github.com/neovim/neovim/blob/master/src/nvim/cursor_shape.h#L37 . The TUI changes the cursor upon "tui_mode_change" calls https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c#L466 .

I suppose a function "update_cursor" could be added in https://github.com/neovim/neovim/blob/master/src/nvim/ui.h#L17 that passes the different cursorentry_T parameters over RPC. Seems a bit redundant with mode_change though ?!

**Comment by justinmk** [comment]
@teto That sounds right. (I wouldn't say it's redundant, the semantics of `mode_change` are up to the UI).

The general idea is that UIs (including TUI) should respect 'guicursor'. To do that we need a new UI event, `cursor_style_set`. Here's a skeleton (won't compile, but shows the idea):

```diff
diff --git a/src/nvim/api/ui.c b/src/nvim/api/ui.c
index 9178538110d6..d22a7d196415 100644
--- a/src/nvim/api/ui.c
+++ b/src/nvim/api/ui.c
@@ -234,6 +234,14 @@ static void remote_ui_cursor_goto(UI *ui, int row, int col)
   push_call(ui, "cursor_goto", args);
 }
 
+static void remote_ui_cursor_style_set(UI *ui)
+{
+  Array args = ARRAY_DICT_INIT;
+  Dictionary style = cursor_shape_dict();
+  ADD(args, DICTIONARY_OBJ(style));
+  push_call(ui, "cursor_style_set", args);
+}
+
 static void remote_ui_update_menu(UI *ui)
 {
   Array args = ARRAY_DICT_INIT;
diff --git a/src/nvim/cursor_shape.c b/src/nvim/cursor_shape.c
index b50462664c99..e650bb18bc2d 100644
--- a/src/nvim/cursor_shape.c
+++ b/src/nvim/cursor_shape.c
@@ -209,5 +209,14 @@ char_u *parse_shape_opt(int what)
     }
   }
 
+  ui_cursor_style_set();
+
   return NULL;
 }
+
+Dictionary cursor_shape_dict(void)
+{
+  Array d = ARRAY_DICT_INIT;
+  // TODO: convert shape_table to a Dictionary, see remote_ui_highlight_set()
+  return d;
+}
diff --git a/src/nvim/ui.c b/src/nvim/ui.c
index d3784b6cd3cf..96b8daa99e9a 100644
--- a/src/nvim/ui.c
+++ b/src/nvim/ui.c
@@ -155,6 +155,11 @@ void ui_cursor_shape(void)
   ui_mode_change();
 }
 
+void ui_cursor_style_set()
+{
+  UI_CALL(cursor_style_set);
+}
+
 void ui_refresh(void)
 {
   if (!ui_active()) {
diff --git a/src/nvim/ui.h b/src/nvim/ui.h
index d14bc5812c27..86e7d162b3b6 100644
--- a/src/nvim/ui.h
+++ b/src/nvim/ui.h
@@ -22,6 +22,7 @@ struct ui_t {
   void (*clear)(UI *ui);
   void (*eol_clear)(UI *ui);
   void (*cursor_goto)(UI *ui, int row, int col);
+  void (*cursor_style_set)(UI *ui);
   void (*update_menu)(UI *ui);
   void (*busy_start)(UI *ui);
   void (*busy_stop)(UI *ui);
```

The change to `parse_shape_opt()` is what triggers the UI event whenever `'guicursor'` is set.

Notice that this change only sends a dictionary representing the cursor style to the UIs. It's up to each UI to store that and style the cursor appropriately.

For the case of the TUI, the next step would be to add a `tui_cursor_style_set()` handler in `tui/tui.c` which sends termcodes related to cursor shape (factor out the existing logic from `fix_terminfo()` in that same file).

**Comment by teto** [comment]
I will try to propose a PR if no one started working on it (WIP in  https://github.com/teto/neovim/tree/guicursor).

**Comment by teto** [comment]
There is something I don't get:
- I send correctly the dictionary here https://github.com/teto/neovim/blob/guicursor/src/nvim/api/ui.c#L306
(I had to add some more functions than your previous message suggests to account for the bridge)
- but how can I retrieve the dictionary sent over msgpack in tui_cursor_style_set() https://github.com/teto/neovim/blob/guicursor/src/nvim/tui/tui.c#L438 ? all others members of UI retrieve the new data as parameters. Also I am not sure I get how the translation RPC -> UI->calls happens ? I tried :h rpc-remote-ui  but it's too basic.

**Comment by justinmk** [comment]
On master, cursor shape can be controlled via the `'guicursor'` option. 

You can also use this autocmd to change the cursor just before exiting nvim, so the shell cursor will be restored:

    au VimLeave * set guicursor=a:block-blinkon0

(That sets a non-blinking "block" cursor. Change `a:block-blinkon0` as needed.)
