### ISSUE TITLE
Using `:global` commands while `clipboard=unnamed` is very slow.

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#2584]
To reproduce, set `clipboard=unnamed` and then in a new buffer
`5000ia<CR><ESC>:g/a/d`. This global command will take over a minute to execute. However, set `clipboard=`, and it will execute instantly.

I suppose this is because for each line that matches, vim copies the result to the system clipboard, however the only line that needs to get sent to the system clipboard is the last match.

**Comment by justinmk** [comment]
If anyone wants to work on this, here's a hint: https://github.com/neovim/neovim/issues/2155#issuecomment-82001947

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/2809
