### ISSUE TITLE
Inconsistent gx mapping

### ISSUE THREAD

**Issue by backdround** [neovim/neovim#25841]
### Problem

The new default `gx` mapping is still set when a user maps `g`.

If a user sets `g` mappings, other mappings like `gu` / `gU` / `ga` ... are unset. But it doesn't work that way with the new `gx` mapping.

My problem is that I have a map `nmap g i` and now I have to manually disable the mapping (and possibly all future mappings).

### Steps to reproduce

nvim --clean
:map g i

-- gu - isn't working (as expected)
-- gx - is still working (!!!)

### Expected behavior

`gx` doesn't work after `g` has been mapped.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-82b1a38

### Vim (not Nvim) behaves the same?

no (it doesn't have the `gx` mapping)

### Operating system/version

Linux arch 6.5.4-arch2-1

### Terminal name/version

kitty 0.29.2-2

### $TERM environment variable

tmux-256color

### Installation

Arch User Repository (AUR) / neovim-nightly-bin package

**Comment by justinmk** [comment]
> My problem is that I have a map `nmap g i` and now I have to manually disable the mapping (and possibly all future mappings).

`<nowait>` exists for that purpose. I confirmed that this works:

    nnoremap <nowait> g i

**Comment by backdround** [comment]
@justinmk 

I just thought that breaking unspoken consistency with default mappings isn't a good idea. Any other default `g` mappings don't cause problems. Also, there weren't any mappings that showed any description before (`:nmap gx` or `telescope.builtin.keymaps`).

`nowait` is a good solution, but I deleted it by:
```lua
vim.keymap.del({ "n", "x" }, "gx")
```
because it deletes the description along the way

Thanks for the reply!
