### ISSUE TITLE
Implement TermResponse auto command for certain terminal response sequences

### ISSUE THREAD

**Issue by gpanders** [neovim/neovim#25856]
### Problem

The `TermResponse` autocommand is documented but not implemented. This is ported from Vim, which does implement it.

The documentation states that this autocommand fires when `v:termresponse` is set, which is in turn set when the Neovim receives a primary device attributes response. None of this is actually true (today).

### Expected behavior

We can repurpose this event to provide plugins access to certain terminal response sequences. Of particular interest are OSC 52 and OSC 4.

OSC 52 allows Neovim to read the system clipboard. A plugin can write the sequence `OSC 52 ; ; ? ST` and the terminal will respond with `OSC 52 ; ; <base64 encoded contents of clipboard> ST`. We can store this response in `v:termresponse` and fire a `TermResponse` autocommand so that plugins can receive the clipboard contents.

Similarly, OSC 4 allows plugins to request the current terminal palette colors.

The autocommand will fire anytime `v:termresponse` is updated. `v:termresponse` only contains the most recent value, so plugins must read it in a `TermResponse` handler before it is overridden by another response sequence.

**Comment by justinmk** [comment]
> We can repurpose this event to provide plugins access to certain terminal response sequences. Of particular interest are OSC 52 and OSC 4.

Also "request version" to decide if we can use 8-bit key sequences:

- https://github.com/neovim/neovim/issues/6279
