### ISSUE TITLE
Highlight Full Line Background (in Diagnostics)

### ISSUE THREAD

**Issue by tj-moody** [neovim/neovim#25869]
### Problem

In VSCode, diagnostics can be displayed by highlighting the entire line, as shown here:
<img width="902" alt="Screenshot 2023-11-01 at 2 26 30 PM" src="https://github.com/neovim/neovim/assets/92702993/6cc54a79-4044-49fe-b64d-3aee5278854f">
As far as I'm aware, the closest to this neovim has is giving a background highlight to the `DiagnosticUnderlineWarn`, etc. highlight groups. But this doesn't highlight the whole line, just part of it, as shown here:
<img width="599" alt="Screenshot 2023-11-01 at 2 27 48 PM" src="https://github.com/neovim/neovim/assets/92702993/e04ff738-9de0-4131-b094-a1817b0cb0e4">

### Expected behavior

The UI feature that I want is to set some diagnostic option to highlight the whole line, and a highlight group to use to do so. I imagine it looking something like:
```lua
vim.diagnostic.config({
    virtual_text = {
        line_hl = { -- new
            ["Error"] = "#000000",
            ["Info"] = "#000000",
        }
    }
})
```
Where `line_hl` has keys of `Error`, `Warn`, `Hint`, and `Info`, and excluding one will turn off highlights for that severity. So in this example, every line with a diagnostic severity of `Error` or `Info` would be highlighted like in the first screenshot with their respective colors.

Obviously just a concept, names and everything else subject to change.

There's no real cost to this—just another nice UI option

**Comment by tj-moody** [comment]
I actually was able to implement this functionality! Based on the `diagnostic.handler` docs, I came up with
```lua
local diagnostic_lines_ns = vim.api.nvim_create_namespace("Diagnostic Lines")
local orig_signs_handler = vim.diagnostic.handlers.signs
local function severity_highlight(severity)
    return 'DiffDelete'
end
vim.diagnostic.handlers.signs = {
    show = function(_, bufnr, _, opts)
        -- Handle diagnostics for whole buffer for ns convenience
        local diagnostics = vim.diagnostic.get(bufnr)
        for _, diagnostic in ipairs(diagnostics) do
            vim.api.nvim_buf_set_extmark(
                diagnostic.bufnr,
                diagnostic_lines_ns,
                diagnostic.lnum, 0,
                { line_hl_group = severity_highlight(diagnostic.severity) }
            )
        end
        orig_signs_handler.show(diagnostic_lines_ns, bufnr, diagnostics, opts)
    end,
    hide = function(_, bufnr)
        vim.api.nvim_buf_clear_namespace(bufnr, diagnostic_lines_ns, 0, -1)
        orig_signs_handler.hide(diagnostic_lines_ns, bufnr)
    end,
}
```
Where the `severity_highlight` function determines the highlight group to be used.

I feel like I learn new extmark functionality every day.

**Comment by glepnir** [comment]
Fixed by https://github.com/neovim/neovim/pull/26555

**Comment by wookayin** [comment]
#26555 by @gpanders allows setting numhl and linehl highlight groups:

Now one can do like (`:help vim.diagnostic.config()`)

```lua
  vim.diagnostic.config {

    signs = {
      text = { ... },

      linehl = {
        [vim.diagnostic.severity.ERROR] = "DiagnosticErrorLn",
        [vim.diagnostic.severity.WARN]  = "DiagnosticWarnLn",
        [vim.diagnostic.severity.INFO]  = "DiagnosticInfoLn",
        [vim.diagnostic.severity.HINT]  = "DiagnosticHintLn",
      },
      -- or more simply linehl = { "DiagnosticErrorLn", "DiagnosticWarnLn", "DiagnosticInfoLn", "DiagnosticHintLn" }

      numhl = { ... },
    },
  }
```

and add highlight groups such as `hi DiagnosticErrorLn guibg=#501010`.
