### ISSUE TITLE
Assertion failed: count && count <= buf->size

### ISSUE THREAD

**Issue by nikeedev** [neovim/neovim#25863]
### Problem

Happens when i run packer.nvim commands (like `:PackerSync`, `:PackerUpdate`, or `:PackerInstall`). When i run them i get an error

<img width="583" alt="image" src="https://github.com/neovim/neovim/assets/69197950/ba83b42f-48f1-41bf-bd16-b56563daa954">

https://github.com/neovim/neovim/assets/69197950/4c666085-3753-43e6-81ef-62d49f5980c8

https://github.com/neovim/neovim/assets/69197950/34b1db2c-8d45-4dd9-9e3c-7762b04f4876

### Steps to reproduce

Start neovim, write a packer command, for example like :PackerSync, and then after some time when packer is done neovim crashes and right before the crash neovim comments an assertion error:
`Assertion failed: count && count <= buf->size`

related issue: https://github.com/neovim/neovim/issues/23781

I know that this issue is also related to a package manager, but the related issue that i referenced has same issue which is because of neovim, than the package manager.

### Expected behavior

I expected it to **not** crash, after a successfull install of a plugin

### Neovim version (nvim -v)

v0.9.2

### Vim (not Nvim) behaves the same?

no, i dont have vim

### Operating system/version

Windows 11 22621.2506

### Terminal name/version

Windows terminal v1.18.2822.0

### $TERM environment variable

probably xterm-256, i use windows terminal which supports most of modern ones

### Installation

Winget

**Comment by glepnir** [comment]
duplicate https://github.com/neovim/neovim/issues/23781
