### ISSUE TITLE
nvim crashes with many windows on a small terminal

### ISSUE THREAD

**Issue by j-xella** [neovim/neovim#25864]
### Problem

I have a big terminal (approx 100 rows x 500 cols), in which I run nvim with approx 10 windows. When I start shrinking the terminal, nvim gets smaller, smaller, ... until it eventually coredumps. It happens when the terminal is really small and all the windows can't be displayed.

I don't do it on purpose, of course. But I work on a remote PC, and when I disconnect, the remote PC thinks that the display has become smaller, hence all the windows get resized, hence nvim get smaller .... very often, when I reconnect, my nvim session is gone.

Sample stack:
```
#0  0x00007f99e2f39387 in raise () from /lib64/libc.so.6
#1  0x00007f99e2f3aa78 in abort () from /lib64/libc.so.6
#2  0x00007f99e2f7bf67 in __libc_message () from /lib64/libc.so.6
#3  0x00007f99e2f84329 in _int_free () from /lib64/libc.so.6
#4  0x000000000058180d in write_cb.lto_priv ()
#5  0x00000000008d8561 in uv.write_callbacks ()
#6  0x00000000008d89b0 in uv.stream_io ()
#7  0x00000000008cdeb5 in uv_run ()
#8  0x00000000007d9dd0 in vgetorpeek.constprop ()
#9  0x00000000005cea57 in char_avail ()
#10 0x000000000050924b in showmode ()
#11 0x000000000050d3a5 in update_screen ()
#12 0x000000000050edb8 in screen_resize.part ()
#13 0x000000000077b8a4 in ui_refresh ()
#14 0x0000000000495fa8 in handle_nvim_ui_try_resize ()
#15 0x000000000065ca29 in request_event ()
#16 0x000000000057475d in multiqueue_oneshot_event.lto_priv ()
#17 0x0000000000731591 in state_handle_k_event ()
#18 0x00000000005170ed in insert_execute.lto_priv ()
#19 0x0000000000737d0b in state_enter ()
#20 0x00000000007d0ca9 in insert_enter.constprop ()
#21 0x000000000050f28d in edit ()
#22 0x00000000006659c4 in normal_execute.lto_priv ()
#23 0x0000000000737d6d in state_enter ()
#24 0x00000000006626fa in normal_enter ()
#25 0x000000000045510d in main ()
```

And another:
```
#0  0x00007fbbfc01e387 in raise () from /lib64/libc.so.6
#1  0x00007fbbfc01fa78 in abort () from /lib64/libc.so.6
#2  0x00007fbbfc060f67 in __libc_message () from /lib64/libc.so.6
#3  0x00007fbbfc067474 in malloc_printerr () from /lib64/libc.so.6
#4  0x000000000058180d in write_cb.lto_priv ()
#5  0x00000000008d8561 in uv.write_callbacks ()
#6  0x00000000008d89b0 in uv.stream_io ()
#7  0x00000000008cdeb5 in uv_run ()
#8  0x00000000007d9dd0 in vgetorpeek.constprop ()
#9  0x00000000005cea57 in char_avail ()
#10 0x000000000050924b in showmode ()
#11 0x000000000050d3a5 in update_screen ()
#12 0x000000000050edb8 in screen_resize.part ()
#13 0x000000000077b8a4 in ui_refresh ()
#14 0x0000000000495fa8 in handle_nvim_ui_try_resize ()
#15 0x000000000065ca29 in request_event ()
#16 0x000000000057475d in multiqueue_oneshot_event.lto_priv ()
#17 0x0000000000731591 in state_handle_k_event ()
#18 0x00000000005170ed in insert_execute.lto_priv ()
#19 0x0000000000737d0b in state_enter ()
#20 0x00000000007d0ca9 in insert_enter.constprop ()
#21 0x000000000050f28d in edit ()
#22 0x00000000006659c4 in normal_execute.lto_priv ()
#23 0x0000000000737d6d in state_enter ()
#24 0x00000000006626fa in normal_enter ()
#25 0x000000000045510d in main ()
```

### Steps to reproduce

1. Make terminal window with many rows/cols
2. Open nvim there
3. In nvim, create many windows (10+)
4. Start reducing the size of the terminal

### Expected behavior

Nvim does not crash. And when it is resized back to normal size, all the windows are visible again

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1438+g8405649f9

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

RHEL 7.9

### Terminal name/version

wezterm via ssh

### $TERM environment variable

wezterm

### Installation

build from repo

**Comment by clason** [comment]
How is this different from #25837?

**Comment by j-xella** [comment]
> How is this different from #25837?

Apart from call stack being completely different ... this one happens when nvim terminal is getting smaller and smaller, and happens consistently, at least in my case. You keep reducing the terminal size, and nvim eventually crashes. 

In #25837, however, crash happens when the terminal size fluctuates. bigger -> smaller -> bigger -> smaller .... Does not crash every time but quite often, in my case.

**Comment by zeertzjq** [comment]
Can you reproduce this with ASAN (https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#sanitizers-asan-and-ubsan) and provide ASAN logs? They may offer more useful information.

> In nvim, create many windows (10+)

What is the exact layout after creating these windows?
