### ISSUE TITLE
'<80><fd>a' key sequences are recorded by pressing f/t key when recording macro

### ISSUE THREAD

**Issue by umlx5h** [neovim/neovim#25865]
### Problem

When I create a relatively long macro or when I make a mistake on some keys, I often copy the macro from the register to the text and then manually correct it and yank it back into the register before executing it.

When recording macros, keys such as `f` and `t` are usually used frequently, and when these two keys are recorded, a mysterious key sequence is recorded.

The following is the key sequence when the "fal" key is recorded in the macro.

```
fa<80><fd>al
```
The "tal" is as follows
```
ta<80><fd>al
```

`<80><fd>a` is recorded for f and t, not ESC or CTRL+C.

I also checked with regular Vim. f, t and CTRL+C were fine, but ESC recorded a mysterious key sequence in the same way.
For example, typing `qai<ESC>` in vim will record `i^[<80><fd>a` 

I can deal with this by substituting ESC with CTRL+C in Vim, but I am having trouble with Neovim because it is recorded with f and t, making the macro very difficult to read or edit.

### Steps to reproduce

(f pattern)
1. echo 'hello world!' | nvim --clean -
2. record macro to @a by pressing `qa`
3. pressing `fwl`
4. pressing `:put a`
5. `fw<80><fd>al` is inserted to text.

(t pattern)
3. pressing `t!l`
4. pressing `:put a`
5. `t!<80><fd>al` is inserted to text.

### Expected behavior

Each should be recorded as follows (That's how it is in vim.)

fwl -> fwl
t!l -> t!l

### Neovim version (nvim -v)

v0.10.0-dev

### Vim (not Nvim) behaves the same?

no, Vi IMproved 8.2

### Operating system/version

WSL2 and macos

### Terminal name/version

wezterm 20231017-091526-fec90ae0

### $TERM environment variable

xterm-256color

### Installation

apt / homebrew

**Comment by zeertzjq** [comment]
Please see https://github.com/vim/vim/issues/6350

**Comment by umlx5h** [comment]
@zeertzjq 

I reproduced it even with a new vim I put in homebrew on my Mac, so it seems to be a specification.

Sorry for the novice question, but I'm going to deal with this by creating a replace command to remove this <Nop> character instead.

Can I remove the <80> part by substitute command?

I pressed ga to check each key code and found the following.

`<fd>` part
```
<ý> 253, Hex 00fd, Oct 375, Digr y'
```

`<80>` part
```
<<80>> 128, Hex 0080, Oct 200, Digr PA
```

`<fd>a` could be removed by searching by unicode as follows,
```
:s/\%u00fda//g
```
but `<80>` did not match for some reason.
```
s/\%u0080//g
```

Is this `<80>` key unmatchable?

**Comment by zeertzjq** [comment]
Use `\x` instead of `\u`

**Comment by umlx5h** [comment]
Thanks.
For some reason, I don't get any hits when I search right after copying from the register, but when I save it to a file and reopen it in vim, it matches both in \u and in \x.

```
/\%u0080
/\%x80
```

In order to rewrite the register on the fly, I decided to use the following regular expression to deal with the problem.
Even after copying from the register, the use of dots matched properly.
```
:s/\v([ft].).%xfda/\1/g
```
