### ISSUE TITLE
Cursor moves to command line area when it should not (perceived as cursor flicker)

### ISSUE THREAD

**Issue by Asheq** [neovim/neovim#25884]
# Problem

I notice that the cursor sometimes flickers, randomly. Cursor flickering (and flickering in general) is a bit of a pet peeve of mine. I know many of you can relate.

When I look closely, it seems to happen because the cursor moves to the command line area in order to print messages. If I'm not mistaken, drawing in the command line area should be do-able without actually moving the visible cursor there. The cursor should only be there if the _user_ is explicitly _typing_, correct?

PS: This is even more noticeable in Neovide (the GUI) with the animated cursor enabled.

# Steps to reproduce

Unfortunately, I won't be able to easily reproduce using `nvim --clean`, not because it doesn't happen, but because it happens too fast (probably). Here are my dotfiles: https://github.com/Asheq/dotfiles/tree/master/.config/nvim

# Examples
Below are some screen captures, which I've slowed down to 0.05x speed (20 times slower). Notice that the cursor jumps briefly to the command line to print a message and then back up.

### Status: ✅ Fixed in nightly v0.10.0-dev-1461+g468292dcb-Homebrew

https://github.com/neovim/neovim/assets/4657140/2fc44272-eca3-4653-9832-b33fe23da608

### Status: ✅ Fixed in nightly v0.10.0-dev-1461+g468292dcb-Homebrew

https://github.com/neovim/neovim/assets/4657140/a58b685b-0028-4bb0-a1a6-84b66bf49963

### Status: ❌ Still a problem in nightly v0.10.0-dev-1461+g468292dcb-Homebrew

I invoke the `:update` using the following mapping:
```
nnoremap <silent> <leader>w        :up<Enter>
```
I understand that if I didn't have the `<silent>` in the mapping then the cursor is indeed expected move to the command line while `:up` is being "entered" on the user's behalf. But I do have the `<silent>`, and the cursor moves there to print `"temp.md" 9L, 135B written`

https://github.com/neovim/neovim/assets/4657140/d719b943-0a03-4a16-be4f-12f0d39153ed

### Expected behavior

Cursor should not move to command line area

(Unless user is explicitly typing)

### Neovim version (nvim -v)

v0.9.4

### Vim (not Nvim) behaves the same?

Was not able to reproduce with `vim -u DEFAULTS`

### Operating system/version

macOS 13.5.1

### Terminal name/version

kitty 0.29.0

### $TERM environment variable

xterm-kitty

### Installation

homebrew

**Comment by zeertzjq** [comment]
Please try nightly version and see if this bug still exists.

**Comment by Asheq** [comment]
> Please try nightly version and see if this bug still exists.

Thanks for looking into it @zeertzjq 

I was not able to reproduce examples 1 or 2 in nightly. I was, however, able to reproduce example 3. What could the reason be?

Output of `nvim -v`:
```
NVIM v0.10.0-dev-1461+g468292dcb-Homebrew
Build type: Release
LuaJIT 2.1.1697887905
Run "nvim -V1 -v" for more info
```

I'll keep using this version for the next few weeks to keep an eye on examples 1 and 2, and any other cursor flickering I might observe.

**Comment by zeertzjq** [comment]
It may be #25629

**Comment by Asheq** [comment]
Here are some other potentially relevant issues:
- https://github.com/neovim/neovim/pull/20582
- https://github.com/neovim/neovim/pull/25244
- https://github.com/neovim/neovim/issues/11806

**Comment by Asheq** [comment]
Going to close this and open a new one with clean repro steps.
