### ISSUE TITLE
Daily build 0.10 :E results in `Ambiguous use of user-defined command`

### ISSUE THREAD

**Issue by jbwyatt4** [neovim/neovim#25899]
### Problem

This worked in 0.9. Pressing :E from the neovim welcome screen

### Steps to reproduce

nvim
:E
Ambiguous use of user-defined command` will show in the task bar

### Expected behavior

Show netrw editor in the folder neovim was opened in.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-468292d

### Vim (not Nvim) behaves the same?

No, it behaves like 0.9. However vim -u DEFAULTS returns 'Not an editor command'

### Operating system/version

Fedora 38 GNOME

### Terminal name/version

GNOME Terminal Version 3.48.1 for GNOME 44

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by lucario387** [comment]
`EditQuery` is the problem here

**Comment by clason** [comment]
To expand on that: we added a new command, so now just `:E` _is_ ambiguous. Nothing to be done about it.

**Comment by jbwyatt4** [comment]
Why was this changed? It still works in Vim. I am learning (neo)vim and making a bundle for Linux kernel development. I got used to using :E when I wanted to view the files in a directory and now I have to rewrite my documentation for others.

If you are not going to fix it how can I bind EditQuery in my lua config or do you have a better recommendation than typing :Explore?

**Comment by clason** [comment]
Why was what changed? Why did we add a new command? (Because we added a new, useful, feature.)

`:Explore` (or `:Ex`) still works, of course.

**Comment by jbwyatt4** [comment]
Forgot about `:Ex`. Thank you for letting me know.

What feature was added by the way? I am writing documentation.

**Comment by clason** [comment]
:h EditQuery
