### ISSUE TITLE
CmdLine syntax highlighting

### ISSUE THREAD

**Issue by LamprosPitsillos** [neovim/neovim#25897]
### Problem
![2023-11-04_23-23-13_echo](https://github.com/neovim/neovim/assets/61395246/88e82512-c4eb-4c9e-bfe1-47b337390696)
![2023-11-04_23-25-34_lua](https://github.com/neovim/neovim/assets/61395246/b0385291-5d55-4d34-b9b4-513358432a72)
![2023-11-04_23-25-57_reg](https://github.com/neovim/neovim/assets/61395246/2c10d4d3-0ba9-4d33-bc82-da397f2261fb)

### Expected behavior

It would be a nice qol and cosmetic feature to have syntax highlighting in `cmdline` just like [Noice](https://github.com/folke/noice.nvim#-features) has.

![image](https://github.com/neovim/neovim/assets/61395246/e57f824b-02be-4050-b7e5-78c9c9dca1a6)
![image](https://github.com/neovim/neovim/assets/61395246/c64ded0c-03cf-4bcf-959e-29b9388da5c4)

It looks like the `cmdline` is capable of showing highlighted text ( as shown in the screenshot below where the `=` register has highlighting ).

![2023-11-04_22-23-19_highl](https://github.com/neovim/neovim/assets/61395246/d90b43c1-d051-477b-9dfc-7cfd5f4507c4)

**Comment by clason** [comment]
No, this will require much, _much_, more. (We already ship a Lua parser; that's not at all the issue here.)

**Comment by LamprosPitsillos** [comment]
> No, this will require much, _much_, more. (We already ship a Lua parser; that's not at all the issue here.)

Definitely, didn't mean for it to come off as an "easy feature"

**Comment by justinmk** [comment]
> where the `=` register has highlighting

That's driven by nvim_parse_expression https://github.com/neovim/neovim/blob/7ce36b7997bf04b6fafdfec482b1a29629b49bd8/src/nvim/api/vimscript.c#L438

but that doesn't help for cmdline Ex commands, which are parsed differently.

Instead we would want to highlight the cmdline using normal treesitter-based syntax highlighting, perhaps using an internal scratch buffer.
