### ISSUE TITLE
Regularizing vim grammar

### ISSUE THREAD

**Issue by mkschreder** [neovim/neovim#25893]
### Problem

To my knowledge, vim command grammar has never been regularized. I'm not talking about the bindings themselves but rather about the state machine that decides what to do when certain commands are executed. 

I found this presentation that mentions vim inspiring: https://speakerdeck.com/nelstrom/modelling-state-machines-with-ragel

### Expected behavior

It would be interesting to explore to what extent the vim state machine can be regularized into a grammar from which C code can be generated that then executes C actions and vim script actions in response to commands.

**Comment by clason** [comment]
Sorry, but that's something you have to bring up with Vim.
