### ISSUE TITLE
Parser `d` doesn't work with appended text after get_node run on comment

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#25894]
### Problem

When in `d` filetype, `vim.treesitter.get_node` (or `vim.treesitter.get_parser`) gets called while the cursor is on a `line_comment`-node, then any text appended after that after a newline is treated as being in the node.

### init.lua:
```lua
for name, url in pairs{
   treesitter='https://github.com/nvim-treesitter/nvim-treesitter'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end
require'nvim-treesitter.configs'.setup{ensure_installed={'d'}}
```
### action:
```
:setf d
I//<esc>
:lua vim.treesitter.get_node()<cr>
ofoo<esc>
:lua print(vim.treesitter.get_node():type())<cr>
```
It will print `line_comment`

### Expected behavior

It printing `identifier`

### Neovim version (nvim -v)

0.10.0-dev-d3e9cbe

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

linux 6.5.9-arch2-1

### Terminal name/version

kitty 0.30.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by clason** [comment]
If this is unique to D filetypes, this is a parser issue and should be reported there. (The D parser is known to have issues.)

**Comment by clason** [comment]
(and I cannot reproduce this)

**Comment by altermo** [comment]
Using `:InspectTree` solves the issue (so does calling `vim.treesitter.start`).

**Comment by clason** [comment]
https://github.com/neovim/neovim/pull/25387
