### ISSUE TITLE
Lua support for changing the language

### ISSUE THREAD

**Issue by ThomasMader** [neovim/neovim#25904]
### Problem

Running `:checkhealth` in nvim on Windows 10 gave me a configuration error:

`ERROR Locale does not support UTF-8. Unicode characters may not display correctly.
 15   $LANG=nil $LC_ALL=nil $LC_CTYPE=nil
 16   - ADVICE:
 17     - If using tmux, try the -u option.
 18     - Ensure that your terminal/shell/tmux/etc inherits the environment, or set $LANG explicitly.
 19     - Configure your system locale.`
 
 I was able to get rid of it by setting the locale in my config:

`vim.api.nvim_exec('language en_US', true)`

I wondered if it is planned to support setting the language natively via Lua with e.g. `vim.opt.language = en_US` because it seemed strange that such a basic thing is not supported yet.
Or is the locale setting error supposed to be differently on Windows?

### Expected behavior

Adding `vim.opt.language = en_US` to init.lua would resolve the Locale configuration error.

**Comment by clason** [comment]
`:language` is not an option. Use `vim.cmd.language`.

**Comment by ThomasMader** [comment]
If I use `vim.cmd.language = en_US` the locale is not set. I get the error in the healthcheck again. Language is at it's default ('C') again.

**Comment by clason** [comment]
That's not how this works. Please read basic documentation (`:h lua-guide`); the issue tracker is not a support forum.
