### ISSUE TITLE
 Incompatibility issue with vim-fugitive plugin after upgrading to the latest Git Head version

### ISSUE THREAD

**Issue by starwing** [neovim/neovim#25925]
### Problem

Hello,

I recently upgraded from Neovim 0.8.3 to the latest Git Head version and encountered an incompatibility issue. I have been using the [vim-fugitive plugin](https://github.com/tpope/vim-fugitive) for many years to manage Git repositories within Vim. Prior to the upgrade, when executing commands using this plugin, the command output would be displayed line by line in real-time at the bottom of the window. However, after the upgrade, the entire command output is only displayed at the bottom of the window once the command execution is complete. This becomes inconvenient for me as I rely on the immediate feedback of command execution, especially for time-consuming pre-commit operations, as I need to check the execution results before committing.

Upon inspecting the source code of fugitive, I noticed that it utilizes the `jobs` feature to create asynchronous tasks for executing Git commands, and it uses `echomsg` to display the output when there is any. It seems that the `echomsg` within jobs is no longer providing real-time output. I'm wondering if anyone else has encountered a similar issue and if there is a possible solution to this problem.

Thank you for your attention and assistance in resolving this matter.

Best regards,
Xavier Wang

### Steps to reproduce

cd /a/path/to/git/repo
nvim README.md
:G commit
(the pre-commit runs and no any output in window)
![image](https://github.com/neovim/neovim/assets/114483/e0cbc5ff-cdf9-4ebb-81b9-d56ed736e730)

(after the commit finished, all output occurs in window):
![image](https://github.com/neovim/neovim/assets/114483/db6c8e6f-4d57-4e62-b222-ae5f57eaff6e)

### Expected behavior

 the command output would be displayed line by line in real-time at the bottom of the window.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1490+ga935c7531

### Vim (not Nvim) behaves the same?

no, vim 8.2.3548 to Vim 9.0.2092

### Operating system/version

Centos 7

### Terminal name/version

tmux next-3.4, linking using Windows Termianl via ssh

### $TERM environment variable

screen-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
What is the "pre-commit operation" mentioned here and how much output does it produce?

**Comment by mike325** [comment]
I think he is talking about this [pre-commit](https://pre-commit.com/), and regarding the output, it can be pretty long depending on the checks, there's no limit in how much it will output per check

**Comment by zeertzjq** [comment]
> Upon inspecting the source code of fugitive, I noticed that it utilizes the `jobs` feature to create asynchronous tasks for executing Git commands, and it uses `echomsg` to display the output when there is any.

Where did you get that information from? I can't find an `:echomsg` command in `vim-fugitive` that prints process output, only ones that print warning messages.

**Comment by zeertzjq** [comment]
Hmm, `vim-fugitive` uses `:sleep 1m` in Vim, but `jobwait()` with timeout 1 in Nvim. `:sleep` flushes UI, but `jobwait()` doesn't do that. Not sure if this should be fixed in `vim-fugitive` (by using `:sleep 1m` and `jobwait()` with timeout 0 in Nvim as well) or in Nvim (by making `jobwait()` flush UI).

**Comment by zeertzjq** [comment]
Ah, the documentation for `jobwait()` actually mentions this:
```
		The screen will not redraw unless |:redraw| is
		invoked by a callback.
```
So I think this should be fixed in `vim-fugitive`.

**Comment by zeertzjq** [comment]
Hmm, there really needs to be a way to flush UI without doing anything else. `:redraw` is not an option as it clears messages, and `:sleep 1m` is the closest one, but it needs to take at least 1ms.

**Comment by zeertzjq** [comment]
Anyway, @starwing can you check:
1. If applying the following change to Nvim source code fixes this problem:
```diff
diff --git a/src/nvim/eval/funcs.c b/src/nvim/eval/funcs.c
index 505a91813..550d29609 100644
--- a/src/nvim/eval/funcs.c
+++ b/src/nvim/eval/funcs.c
@@ -4187,6 +4187,7 @@ static void f_jobwait(typval_T *argvars, typval_T *rettv, EvalFuncData fptr)
   }
 
   ui_busy_start();
+  ui_flush();
   list_T *args = argvars[0].vval.v_list;
   Channel **jobs = xcalloc((size_t)tv_list_len(args), sizeof(*jobs));
   MultiQueue *waiting_jobs = multiqueue_new_parent(loop_on_put, &main_loop);
```
2. If applying the following change to `vim-fugitive` source code fixes this problem:
```diff
diff --git a/autoload/fugitive.vim b/autoload/fugitive.vim
index 655c174..945f082 100644
--- a/autoload/fugitive.vim
+++ b/autoload/fugitive.vim
@@ -3560,7 +3560,8 @@ endfunction
 
 function! s:RunTick(job) abort
   if type(a:job) == v:t_number
-    return jobwait([a:job], 1)[0] == -1
+    sleep 1m
+    return jobwait([a:job], 0)[0] == -1
   elseif type(a:job) == 8
     let running = ch_status(a:job) !~# '^closed$\|^fail$' || job_status(a:job) ==# 'run'
     sleep 1m
```

**Comment by starwing** [comment]
Thanks! it fixes my issue just like a charm!
