### ISSUE TITLE
[Documentation] Building Neovim Wiki Page says git checkout stable but stable branch doesn't exist

### ISSUE THREAD

**Issue by BozeBro** [neovim/neovim#25939]
### Problem
[Wiki Page](https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites)
Quickstart says 
"If you want the stable release, also run git checkout stable." but the neovim does not have a stable branch, only releases. Would it make more sense to tell people to use the last release version? It should say smth like
"If you want the stable release, also run git checkout release-x.y" 
Devs will get a more info on what to checkout.

### Steps to reproduce

Go to the Neovim Wiki Page, and click on the Build link

### Expected behavior

The building Neovim Wiki page should have more accurate information.

### Neovim version (nvim -v)

N/A

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

**Comment by clason** [comment]
It's a tag, not a branch.

**Comment by dundargoc** [comment]
> Would it make more sense to tell people to use the last release version?

Not really, because then we'd need to update the text every time we make a new release. `git checkout stable` will always checkout the latest stable release, which is much easier to remember.
