### ISSUE TITLE
BufLeave and BufEnter does not trigger.

### ISSUE THREAD

**Issue by geril2207** [neovim/neovim#25947]
### Problem

With the following config after exiting from new window events `BufLeave/BufInsert` does not trigger.
I guess the problem is in create_autocmd "InsertLeave", if trigger ":lua CLOSE_WINDOW()" manually it works as expected
```
local api = vim.api

local winid = nil
local buf = nil

function CREATE_WINDOW()
	buf = api.nvim_create_buf(false, true)

	winid = api.nvim_open_win(
		buf,
		true,
		{ col = 1, row = 0, width = 10, border = "none", height = 1, relative = "cursor", style = "minimal" }
	)

	vim.cmd("startinsert")

	api.nvim_create_autocmd("InsertLeave", {
		callback = CLOSE_WINDOW,
		once = true,
	})
end

function CLOSE_WINDOW()
	if winid then
		api.nvim_win_close(winid, false)
		winid = nil
	end
end

api.nvim_create_autocmd({ "BufEnter", "BufLeave" }, {
	callback = function(opts)
		print("Buf Enter/Leave all", vim.inspect(opts), api.nvim_get_current_buf(), vim.inspect(api.nvim_list_bufs()))
	end,
})

```

### Steps to reproduce

nvim some_file -nu `following_config.lua`(from description)
`:lua CREATE_WINDOW()`
exit insert mode
check messages, you can see one `BufEnter & BufLeave` events, but i think there also should be  another one `BufLeave & BufEnter` after exit window.

### Expected behavior

I think there should be 4 triggered events(not 2)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-43b0e27

### Vim (not Nvim) behaves the same?

idk

### Operating system/version

Fedora

### Terminal name/version

kitty

### $TERM environment variable

term256-color

### Installation

from source

**Comment by zeertzjq** [comment]
`:h autocmd-nested`
