### ISSUE TITLE
man.vim: q does not exit, throws E444 instead, if you jump to another manpage

### ISSUE THREAD

**Issue by name-snrl** [neovim/neovim#25943]
### Problem

As was suggested in #18443:

> Then the ftplugin can check `b:pager` and use `<C-W>c` or `<C-W>q`, respectively.

_Originally posted by @gpanders in https://github.com/neovim/neovim/issues/18443#issuecomment-1119938663_

Ftplugin now checks `b:pager`, but If you open another page inside "pager", mapping will be overridden, just like when you open a man page in a standard nvim instance.

My suggestion is to make `b:pager` a global variable. Then opening nvim with +Man! will globally define the behavior of that instance as a pager, not just for the first buffer.

### Steps to reproduce

1. set `MANPAGER` to `nvim +Man!`
2. `man git`
3. place the cursor to `gittutorial(7)`
4. press `<C-]>` to jump to a tag
5. now try to exit with `q`

### Expected behavior

nvim closed with `q`

### Neovim version (nvim -v)

NVIM v0.10.0-dev-a8fc94a

### Vim (not Nvim) behaves the same?

idk

### Operating system/version

NixOS unstable `ca012a02bf8327be9e488546faecae5e05d7d749`

### Terminal name/version

foot version: 1.16.1 +pgo +ime +graphemes -assertions +ucurl

### $TERM environment variable

foot

### Installation

Nixpkgs

**Comment by name-snrl** [comment]
I would like to do a PR, but something went wrong with gh and I can't fork repo 🙄

cc @arsham @zeertzjq @justinmk

**Comment by bew** [comment]
Wouldn't that break the workflow of opening manpages in an existing instance?
I man's `q` behavior only for windows with a `Man` buffer, `q` in other buffers should still record a macro.

**Comment by name-snrl** [comment]
> `q` in other buffers should still record a macro

`q` mapping is set in the `ftplugin/man.vim`, so it cannot affect other buffers.

**Comment by bew** [comment]
Okay, I think I'm just confused by:
> My suggestion is to make `b:pager` a global variable

The mention of a 'global variable' makes me think it might affect other buffers

**Comment by RandomChugokujin** [comment]
This is issue also seems to be present by opening a man page buffer in a normal text buffer by running `edit man://<MAN_PAGE>`. I don't know if making `b:pager` global would fix it here.

**Comment by name-snrl** [comment]
> I don't know if making `b:pager` global would fix it here

To open manpages in neovim, you must use `:Man` command. And no it shouldn't close neovim instance, if you want global mapping for closing neovim - add it to your config.

And no it should not close the neovim instance, if you need a global mapping to close neovim - add it to your config. The idea of this issue, is to make a global mapping to close neovim only when you open it as manpager `nvim +Man!`, in other cases a local mapping should be added to close only single window.

**Comment by RandomChugokujin** [comment]
I will create a merge request for this

**Comment by name-snrl** [comment]
thanks @RandomChugokujin
