### ISSUE TITLE
InspectTree: wrong file type or output?

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#25958]
### Problem

When I execute `:InspectTree` on a buffer I get a new buffer with a text representation of the document tree. The file type is set to `query`, but the text is not an actual Tree-sitter query syntax. If the file type was actually correct we would get integration with file-type specific settings and plugins.

### Steps to reproduce

Let's take the following piece of Lua code:

```lua
if not success then return end
```

If I execute `:InspectTree` I get the following output:

```
(if_statement) ; [1:1 - 31:0]
 condition: (unary_expression) ; [1:4 - 15:0]
  operand: (identifier) ; [1:8 - 15:0]
 consequence: (block) ; [1:21 - 27:0]
  (return_statement) ; [1:21 - 27:0]
```

### Expected behavior

I would expect either the file type to be set to something else, or this output:

```
(if_statement ; [3:1 - 31:2]
 "if" ; [3:1 - 2]
 condition: (unary_expression ; [3:4 - 15:2]
  "not" ; [3:4 - 7:2]
  operand: (identifier)) ; [3:8 - 15:2]
 "then" ; [3:16 - 20:2]
 consequence: (block ; [3:21 - 27:2]
  (return_statement ; [3:21 - 27:2]
   "return")) ; [3:21 - 27:2]
 "end") ; [3:28 - 31:2]
```

### Neovim version (nvim -v)

0.10, 0.9

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

GNU/Linux

### Terminal name/version

alacritty 0.12.3

### $TERM environment variable

alacritty

### Installation

XBPS (Void package manager)

**Comment by gpanders** [comment]
You can press the `a` key in the tree window to show anonymous nodes. That will give you your expected output.

Using a separate filetype for the tree buffer is something I proposed in https://github.com/neovim/neovim/pull/22887 as well. That PR just lost momentum, but I don’t think we ever decided on it either way.

**Comment by HiPhish** [comment]
This isn't about the anonymous nodes, but the wrong or missing parentheses around named nodes. Tree-sitter query syntax looks like s-expressions, but here indentation is used to represent nesting.

**Comment by clason** [comment]
What is the actual problem here? What harm is done by (ab)using the query filetype here inorder to get a bit of syntax highlighting?

**Comment by HiPhish** [comment]
If I have a file type plugin for the `query` file type and it expects Tree-sitter query syntax while the content is not according to that syntax things will be broken. I noticed this in https://github.com/hiphish/rainbow-delimiters.nvim where the parentheses were not correctly highlighted.

If you just want to reuse the existing highlight definitions you can do `runtime! syntax/query` inside `syntax/tstree.vim` (or whatever you want to call that file type). Or generate actual Tree-sitter query output, but that might be harder.

**Comment by clason** [comment]
Thank you; the fact that there _is_ such a plugin was the missing information. Then we should resurrect @gpanders PR.

**Comment by gpanders** [comment]
Closed by https://github.com/neovim/neovim/pull/26274.
