### ISSUE TITLE
Neovim becomes very slow when opening an ass file

### ISSUE THREAD

**Issue by benqhdri** [neovim/neovim#25950]
### Problem

When I set `syntax on`, even if I opened nvim with `nvim --clean`, editting an ass file would be very slow.

neovim version:
```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```
example ass file I used to test:
https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2001%20%20course_overview.ass
![image](https://github.com/neovim/neovim/assets/80582089/bcdff1da-bb21-4c76-b423-9af4fcb81d18)

### Steps to reproduce

*copy the ass file from https://github.com/EugeneLiu/translationCSAPP/blob/master/subtitle/translation/Lecture%2001%20%20course_overview.ass
*
nvim --clean Lecture\ 01\ \ course_overview.ass

### Expected behavior

Expect neovim not be that slow :)

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

**No(vim would not highlight ass file after `syntax on`).** Vim version: 8.2

### Operating system/version

ubuntu 22(wsl)

### Terminal name/version

windows terminal 1.18.230526002-preview

### $TERM environment variable

screen-256color

### Installation

download the release version

**Comment by duarm** [comment]
Can't reproduce with `nvim -u NONE`, can reproduce with `nvim --clean`,  running `syntax off` fixes the problem.

**Comment by clason** [comment]
You should never use syntax on in Neovim.

**Comment by duarm** [comment]
with `nvim -u NORC`, syntax is set to `ass`, shouldn't syntax off be the default in neovim?

**Comment by clason** [comment]
@zeertzjq feel free to enlighten us.

**Comment by duarm** [comment]
since the ass format is basically an .ini, I made a quick tree-sitter parser for it, since I need it too. It runs much better https://gitlab.com/duarm1/tree-sitter-ass
