### ISSUE TITLE
infinite loop while opening certain files

### ISSUE THREAD

**Issue by GabrielDertoni** [neovim/neovim#25956]
### Problem

When opening some files the editor hangs and starts consuming a lot of memory (gigabytes) which in indication of an infinite loop while registering callbacks in the `LanguageTree`.

### Steps to reproduce

1. Enable nvim-treesitter highlighting and download the C parser
2. Open the following file in nvim

Here is a the file that triggered the RAM explosion on my neovim. It was taken from the [miniaudio](https://github.com/mackron/miniaudio) library.

```c
#define MA_ATOMIC_SAFE_TYPE_IMPL(c89TypeExtension, type) \
    static MA_INLINE ma_##type ma_atomic_##type##_get(ma_atomic_##type* x) \
    { \
        return (ma_##type)ma_atomic_load_##c89TypeExtension(&x->value); \
    } \
    static MA_INLINE void ma_atomic_##type##_set(ma_atomic_##type* x, ma_##type value) \
    { \
        ma_atomic_store_##c89TypeExtension(&x->value, value); \
    } \
    static MA_INLINE ma_##type ma_atomic_##type##_exchange(ma_atomic_##type* x, ma_##type value) \
    { \
        return (ma_##type)ma_atomic_exchange_##c89TypeExtension(&x->value, value); \
    } \
    static MA_INLINE ma_bool32 ma_atomic_##type##_compare_exchange(ma_atomic_##type* x, ma_##type* expected, ma_##type desired) \
    { \
        return ma_atomic_compare_exchange_weak_##c89TypeExtension(&x->value, expected, desired); \
    } \
    static MA_INLINE ma_##type ma_atomic_##type##_fetch_add(ma_atomic_##type* x, ma_##type y) \
    { \
        return (ma_##type)ma_atomic_fetch_add_##c89TypeExtension(&x->value, y); \
    }
```

this file does load in my machine, after ~5s using over 1GB of memory! An even larger portion of the file (with more stuff inside the macro) would grow memory even more and take exponentially longer to open.

### Expected behavior

The file should open without issue and instantly. TreeSitter is able to parse it within milliseconds!

### Neovim version (nvim -v)

v0.10.0-dev commit 798+g72e619ca9

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal

### $TERM environment variable

powershell.exe

### Installation

build from repo

**Comment by GabrielDertoni** [comment]
I investigated this. It happens because [queries/c/injections.scm](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/c/injections.scm) injects C itself within the `(preproc_arg)` treesitter node. This means that when the [treesitter highlighter tries to register callbacks](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/treesitter/highlighter.lua#L90-L99) on the `LanguageTree` recursivelly, it then iterates through the tree. However since C injects itself, the tree is not really a tree at all! It has a loop in it, which means the [traversal code](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/treesitter/languagetree.lua#L1067-L1070) gets stuck in a loop. I honestly have no idea why this even terminates at some point, but for small enough files it does.

**Comment by clason** [comment]
Yes, well-known issue. (It's not a loop, since -- as you noticed -- it terminates.) Please see other (including closed) issues related to this.

**Comment by GabrielDertoni** [comment]
The bundled queries [**does** appear to have the injections](https://github.com/neovim/neovim/blob/master/runtime/queries/c/injections.scm#L1-L4). Sorry for the nvim-treesitter link.

**Comment by clason** [comment]
Where do you see `preproc_arg`? These queries have been tuned to avoid the worst cases, but of course there can still be bad situations. You'll just have to disable treesitter highlighting for those, at least currently.
