### ISSUE TITLE
Toggle bottom bar on execution of command 

### ISSUE THREAD

**Issue by anshiq** [neovim/neovim#25952]
### Problem

Hide the bottom bars
![Untitled design](https://github.com/neovim/neovim/assets/66484628/fadaa5d6-3d45-4c39-9ae6-0e060cdfa57b)

while writting the text / code and when ever user needs to executer something like :something or :!something show them 
The problem i am facing i am using tmux on a verticle split there are 2 nvim session whose botton bars are useless for me and keeping my useable space.

### Expected behavior

make any keybinding or command to hide buttom bar by default and show when user executes any command,

**Comment by zeertzjq** [comment]
`:set cmdheight=0`
