### ISSUE TITLE
Clipboard integration fails to work with large amounts of text

### ISSUE THREAD

**Issue by RomanHargrave** [neovim/neovim#2596]
When yanking (*`<Y>`, `<X>`, `<D>`*, etc...) large amounts of text (e.x. 173L 5459C) , and then attempting to paste (*`<P>`*) them, the following error is displayed:

```
E353: Nothing in register "
```

NVIM version info:

```
NVIM 0.0.0-alpha+201505051704 (compiled May  5 2015 16:08:03)
Commit: b6af1afee6eab0a430533efcbb8af6c6b1ffe585
Build type: RelWithDebInfo
Compilation: /usr/bin/clang -Ofast -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/roman/.local/src/neovim/build/config -I/home/roman/.local/src/neovim/src -I/home/roman/.local/src/neovim/.deps/usr/include -I/home/roman/.local/src/neovim/.deps/usr/include -I/home/roman/.local/src/neovim/.deps/usr/include/luajit-2.0 -I/home/roman/.local/src/neovim/.deps/usr/include -I/home/roman/.local/src/neovim/.deps/usr/include -I/home/roman/.local/src/neovim/.deps/usr/include -I/usr/include -I/home/roman/.local/src/neovim/build/src/nvim/auto -I/home/roman/.local/src/neovim/build/include

Optional features included (+) or not (-): +acl   +iconv    -jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/share/nvim"
```

Plugins:

```
ack.vim            ag.vim            Align                     colorizer
csv.vim            ctrlp.vim         detectindent              drawit
gist-vim           grep.vim          i3-vim-syntax             molokai
neomake            nerdtree          ooc.vim                   syntastic
tabular            tagbar            tcomment_vim              unite.vim
vim-abolish        vim-airline       vim-autoformat            vim-clang-format
vim-coffee-script  vim-colorschemes  vim-colorscheme-switcher  vim-easymotion
vim-eunuch         vim-fish          vim-fugitive              vim-gradle
vim-jsbeautify     vim-kalisi        vim-misc                  vim-operator-user
vim-pencil         vimproc.vim       vim-scala                 vim-session
vim-sprunge        vim-table-mode    vim-vala                  w3m.vim
YouCompleteMe
```

In nvimrc:
```viml
set clipboard=unnamedplus
```

Setting `clipboard` to `unnamed` will not work, either. 

However, setting `clipboard` to `` will. This makes me wonder if the problem is caused by the underlying OS clipboard integration. I am not familiar witch NVIM's means of interacting with the clipboard, so I cannot pass comment thereupon.

**Comment by Pyrohh** [comment]
Can you reproduce this with `nvim -u NONE`? If not, then try to do so with a minimal `.nvimrc`. Also, are you using `clipboard=unnamed` or `clipboard=unnamedplus`?

**Comment by RomanHargrave** [comment]
@Pyrohh please see the end of my issue in regards to clipboard register. I was able to reproduce this with `unnamed` and `unnamedplus`. The issue is not present when `clipboard` is unset.

The issue is present when running `nvim -u NONE` **and** setting `clipboard` to either `unnamed` or `unnamedplus`.

**Comment by Pyrohh** [comment]
> The issue is present when running nvim -u NONE and setting clipboard to either unnamed or unnamedplus.

Ah, in that case it's either an issue on our end or an issue with whatever clipboard utility you're using. What utility is that by the way? And what exactly do you mean by "large amounts" of text?

For me, `xsel` and `xclip` have no trouble copying and pasting `eval.c` quite quickly (20k lines), both when used standalone and inside nvim `with -u NONE` and `clipboard=unnamedplus`.

Additionally, it's probably a good idea to verify that you experience the issue using the latest revision of nvim. Even though your revision corresponds to work being done on the register/clipboard subsystem, it's easier if everyone just uses the latest revision for bug reports. For all I know, this was inadvertently fixed between your revision and the latest.

**Comment by Pyrohh** [comment]
This is with `xsel-1.2.0` by the way.

**Comment by RomanHargrave** [comment]
@Pyrohh I had upgraded nvim while writing the issue, but it looks like I forgot to update the cited version info. I should be at HEAD on nvim/nvim/master. I will update my issue with correct version when I get to my desk.

**Comment by Pyrohh** [comment]
Thanks for the heads up.

**Comment by justinmk** [comment]
Should be fixed on latest master.
