### ISSUE TITLE
Floating window borders do not respect winblend

### ISSUE THREAD

**Issue by j-hui** [neovim/neovim#25978]
### Problem

From here: https://github.com/j-hui/fidget.nvim/issues/117

When `winblend=100` is set for a floating window, the borders don't seem to inherit the background highlight from the window beneath it.

### Steps to reproduce

Evaluate this file:

```lua
-- winblendnt.lua
local b = vim.api.nvim_create_buf(false, true)
local w = vim.api.nvim_open_win(b, false, {
  relative = "editor",
  width = 5,
  height = 2,
  row = 5,
  col = 30,
  style = "minimal",
  border = "single",
})

vim.api.nvim_win_call(w, function()
  vim.cmd "setlocal winblend=100"
end)

vim.api.nvim_buf_set_lines(b, 0, -1, false, {"", " b "})

vim.opt.termguicolors = true
vim.cmd "hi CursorLine guibg=#2a2b3d"

vim.opt.cursorline = true

vim.cmd "8"
```

Run with something like:

```shell
nvim -u NONE winblendnt.lua '+luafile %'
```

![image](https://github.com/neovim/neovim/assets/11800204/29a0f5ad-2dcc-4c9d-b178-9e5209a6d27b)

As shown in the screenshot, the window contents (including text) correctly inherits the underlying background from the cursorline, but the border characters do not.

It looks even worse when the cursorline is aligned with one of the horizontal borders:

![image](https://github.com/neovim/neovim/assets/11800204/d0df4f0e-459f-406b-bf36-4614c2e33644)

I get a similar issue when I highlight a line using visual mode, so it's not unique to `cursorline`.

### Expected behavior

`winblend` should also apply to border characters.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1521+ge9b9a86cd

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 13.4

### Terminal name/version

kitty 0.30.1

### $TERM environment variable

xterm-kitty

### Installation

homebrew

**Comment by glepnir** [comment]
duplicate https://github.com/neovim/neovim/issues/18576

**Comment by glepnir** [comment]
maybe `apply_cursorline_highlight` should combine cursline attr and border character attr when wp is float.
