### ISSUE TITLE
Docs cleanup: Obsolete GUIs and compile-time feature refs

### ISSUE THREAD

**Issue by yagebu** [neovim/neovim#2599]
I want to help cleaning up the docs. I'll try to do the following, which should be desirable.

1. Remove documentation related to really obsolete GUIs like Athena or Motif that won't ever be implemented for neovim. I'll ignore files that should probably deleted or thouroughly cleaned up at some point (e.g. `gui_x11.txt`).
2. Remove `only availabe when compiled with the |+feature_x| feature` where appropriate, meaning those that are always included. Probably one commit per feature and several features per pull request.

I opened this issue to see if anyone opposes these changes or the approach?

@Pyrohh you have been doing a great amount of documentation cleanup and some of 2. on of your branches already. Do you mind if I remove some more feature refs or did you want to do them all at some point? Anyway, I'll start with 1. and don't know how long that's going to take and hence when I'll get to 2.

**Comment by Pyrohh** [comment]
> @Pyrohh you have been doing a great amount of documentation cleanup and some of 2. on of your branches already. Do you mind if I remove some more feature refs or did you want to do them all at some point?

It would be much appreciated. Thanks for taking the initiative, as there's still much to do.

**Comment by yagebu** [comment]
Have been a bit too busy in recent weeks to do any more work on this sadly. So I'm closing this and if I have more time I'll just open PRs.
