### ISSUE TITLE
`'exrc'` file does not run when starting nvim with `-u`

### ISSUE THREAD

**Issue by b0o** [neovim/neovim#26000]
### Problem

Assuming there is an `exrc`-compatible file in the current directory, if neovim is run with `-u <file>` where `<file>` enables `'exrc'`, or with `nvim -u NORC --cmd 'set exrc'`, the `exrc` file is not executed (nor is a trust prompt displayed).

### Steps to reproduce

`init.lua`:

```lua
vim.o.exrc = true
```

`.nvim.lua`:
```lua
print("hi from .nvim.lua")
```

Repro: `nvim -u ./init.lua`

Result: Nothing is printed

### Expected behavior

`"hi from .nvim.lua"` is printed, or a prompt to trust `".nvim.lua"` is displayed

### Neovim version (nvim -v)

v0.10.0-dev-1535+g9ecb43b637

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Arch Linux (`Linux 6.5.11-x64v2-xanmod1-1 GNU/Linux`)

### Terminal name/version

kitty 0.30.1

### $TERM environment variable

tmux-256color

### Installation

AUR neovim-git

**Comment by zeertzjq** [comment]
Looks like it should be `8.` here:
```diff
diff --git a/runtime/doc/starting.txt b/runtime/doc/starting.txt
index 9f7a72957..1415b4c46 100644
--- a/runtime/doc/starting.txt
+++ b/runtime/doc/starting.txt
@@ -466,12 +466,12 @@ accordingly, proceeding as follows:
 	|$XDG_CONFIG_HOME|	$XDG_CONFIG_HOME/nvim/init.vim	(or init.lua)
 
 	If Nvim was started with "-u {file}" then {file} is used as the config
-	and all initializations until 5. are skipped. $MYVIMRC is not set.
+	and all initializations until 8. are skipped. $MYVIMRC is not set.
 	"nvim -u NORC" can be used to skip these initializations without
 	reading a file.  "nvim -u NONE" also skips plugins and syntax
 	highlighting.  |-u|
 
-	If Nvim was started with |-es| all initializations until 5. are
+	If Nvim was started with |-es| all initializations until 8. are
 	skipped.
 						*system-vimrc* *sysinit.vim*
      a. The system vimrc file is read for initializations.  If
```
