### ISSUE TITLE
E16: Invalid range error on executing a command.

### ISSUE THREAD

**Issue by BontaVlad** [neovim/neovim#2600]
Since the last update (NVIM 0.0.0-alpha (compiled May  5 2015 20:38:52)) on the following script
" Close all the buffers
map <leader>ba :1,1000 bd!<cr>

nvim gives a "E16: Invalid range" but vim still works as normal. Bug or some expected outcome?

**Comment by fmoralesc** [comment]
Probably something related to the recent command ranges patches (the implementation might not be complete yet). 

Have you tried
~~~ vim
map ba :1,$bd!
~~~
? It might be that nvim is currently too strict re the acceptable values in ranges (like, if the end of the range exceed the number of buffers, which might be the case here). 

Also, perhaps your vim version doesn't include the command ranges patches, which would also explain the difference.

**Comment by glts** [comment]
Same in current Vim 7.4.728.

**Comment by BontaVlad** [comment]
`map ba :1,$bd!` works as expected. Many thanks @fmoralesc!
@glts Perhaps you are right, my version of vim is `7.4.52`

**Comment by fmoralesc** [comment]
@BontaVlad How doesn't it work? You mean the mapping or the command (`:1,$bd!`)? The mapping needs to be `map ba :1,$bd!<cr>`, I think. That seems to work fine. (`%bd!` should work too).

Yes, the difference is definitely because of your vim version. Command ranges were introduced in 7.4.530, and I believe this was changed intentionally (I ported the patches, but didn't design it), so I wouldn't call it a bug (unless it was too annoying...)

**Comment by BontaVlad** [comment]
@fmoralesc `%bd!` works, `:1, $bd!` still gives `E16: Invalid range`. Btw thank for the quick response!

**Comment by fmoralesc** [comment]
Can you test if any of 
~~~vim
1bd!
~~~
or 
~~~vim
$bd!
~~~
fails with that same error?

**Comment by BontaVlad** [comment]
`1bd!` gives `E16: Invalid range`
`$bd!` deletes the last buffer/tab created after that `E516: No buffers were deleted`

**Comment by trusktr** [comment]
"2wincmd w" appears in my saved session files sometimes, and then while loading such a session Neovim complains

```
E16: Invalid range: 2wincmd w
```

This seems to happen when I've saved a session with a NERDTree buffer open. Then after loading the session that buffer will be blank.

**Comment by mhinz** [comment]
@trusktr Can you gist that session file? That should only happen if it didn't create needed window first.

**Comment by trusktr** [comment]
Sure, I'll post when it happens again. It doesn't happen every time, so I can't reproduce at the moment.

**Comment by daenney** [comment]
Oddly enough this reared its head for me today after I upgraded from 0.2.1 to 0.2.2. Simply opening up neovim with NerdTree and trying to click anywhere in the tree-view yields E16 invalid range and then the cursor jumps to roughly the middle of the tree view. If I then try to click on a folder above where the cursor moved itself, it for some reason pops up the modify menu.

Trying to use the mouse to move focus to a different part of the split view equally results in E16 invalid range. When the cursor isn't in the nerdtree view and I click inside the tree view it'll actually jump and focus that split but then trying to use the mouse to move to a different split won't work anymore. It's like the cursor is trapped in the tree view.

Using keyboard controls everything works.

**Comment by justinmk** [comment]
`:1,$bd!` works fine. 
`:1,1000 bd!` is invalid, same in Vim 8.0.1451.

@daenney Sounds like either a terminfo issue, or https://github.com/neovim/neovim/wiki/Following-HEAD#20170403 . Not related to this issue.
