### ISSUE TITLE
No syntax highligting for Webassembly .wat file

### ISSUE THREAD

**Issue by jhaand** [neovim/neovim#26005]
### Problem

Webassembly text files now use the `.wat` file extension. The current stable release of neovim does not show syntax highlighting for this file extension. It does show syntax highlighting for the old `.wast` file extension. 

Tested on Neovim stable 0.9.4.

Workaround: 
Copy or link the `runtime/syntax/wast.nvim` to .runtime/syntax/wat.vim`.
Or rename the `.wat` file to the old `.wast` extension.

References:
https://webassembly.github.io/spec/core/text/conventions.html
https://webassembly.js.org/docs/contrib-wat-vs-wast.html

### Steps to reproduce

Create a Webassembly with `.wat` extension. Or download it from: https://github.com/eliben/wasm-wat-samples

```
cd wasm-wat-samples/add
vi add.wat # no syntax highligting
cp add.wat add.wast 
vi add.wast  # does syntax highlighting
```

### Expected behavior

Edit a Webassembly file with syntax highlighting that has a `.wat` extension. 

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

yes, 9.0.1894

### Operating system/version

Debian GNU/Linux trixie/sid x86_64 

### Terminal name/version

Konsole 23.08.1

### $TERM environment variable

xterm-256color

### Installation

Flatpak

**Comment by clason** [comment]
We take the filetype detection logic from Vim; please open an issue (or better yet, a PR) at vim/vim.

**Comment by jhaand** [comment]
OK. I will address this issue with Vim.
