### ISSUE TITLE
Decoration provider on_win botline estimation exceeds buffer

### ISSUE THREAD

**Issue by guilhas07** [neovim/neovim#26011]
### Problem

While developing a plugin for 0.9 and 0.10 version I noticed an inconsistency in `vim.api.nvim_set_decoration_provider`. On the 0.9 neovim version the botline was estimated wrongly, exceeding the buffer size. The fix was introduced on neovim 0.10 by this [commit](https://github.com/neovim/neovim/commit/65738202f8be3ca63b75197d48f2c7a9324c035b). 

When using `vim.api.nvim_buf_get_lines` with strict indexing enabled this becomes a problem on the 0.9 neovim version. 

I was wondering if it would make sense to port this fix to Neovim 0.9 version. 

Sorry if this suggestion doesn't make sense or is unachievable. 
Thank you for your amazing work! 

### `my_issue.lua`:
```lua
local Bufnr = vim.api.nvim_create_buf(false, true)
local ns = vim.api.nvim_create_namespace("Test")

vim.api.nvim_set_decoration_provider(ns, {
    on_win = function(_, _, bufnr, topline, botline)
        if Bufnr ~= bufnr then
            return
        end

        print("Topline: " .. topline .. " Botline" .. botline)
        for lnum = topline, botline do
            vim.api.nvim_buf_clear_namespace(bufnr, ns, lnum, lnum + 1)
            -- Get line with strict indexing will error
            vim.api.nvim_buf_get_lines(bufnr, lnum, lnum + 1, true)
        end
    end,
})
vim.api.nvim_open_win(Bufnr, true, {
    relative = "win",
    row = 0,
    col = 0,
    width = 200,
    height = 40,
})
```
### Steps:
1. nvim --clean -u my_issue.lua

### Expected behavior

Equal behavior to Neovim 0.10 after this [commit](https://github.com/neovim/neovim/commit/65738202f8be3ca63b75197d48f2c7a9324c035b), which means correct botline estimation.

### Neovim version (nvim -v)

0.9.4 

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

WSL ubuntu 22.04.2 LTS

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

build from repo ( nightly ) and bob nvim version manager ( 0.9.4 )

**Comment by justinmk** [comment]
> I was wondering if it would make sense to port this fix to Neovim 0.9 version.

Sorry, no.
