### ISSUE TITLE
In a terminal tab, internal vim instance doesn't hear colon command

### ISSUE THREAD

**Issue by rockneverdies55** [neovim/neovim#2601]
In a neovim terminal tab, I was trying to commit to a git repository. `git commit` automatically opens vim, so I ended up having internal vim instance (to write my commit message) in a `:terminal` tab.

But after finished writing my commit message, I can't do `:wq` in the internal vim instance to finalize my commit because neovim captures the input as soon as I press `:` and tells me buffer is not modifiable. 

![nvim-internal-vim-instance-cant-hear-colon-command](https://cloud.githubusercontent.com/assets/4588562/7495657/4c0eed32-f3dd-11e4-8629-bd8453ac2b06.PNG)

**Comment by justinmk** [comment]
Seems like you need to press `i` before sending `:` to the internal Vim. To send input to `:term`-hosted processes, you must enter insert-mode.

**Comment by rockneverdies55** [comment]
Where should I press `i` command? Pressing `i` takes me into insert mode in the internal vim. And pressing `:` takes me into command mode in neovim instance.

**Comment by justinmk** [comment]
> Pressing i takes me into insert mode in the internal vim. And pressing : takes me into command mode in neovim instance.

Can't reproduce. What is the output of `:tnoremap` ?

**Comment by rockneverdies55** [comment]
Hmm, good point; I had some custom mappings for t mode..

![output-of-tnoremap-in-neovim](https://cloud.githubusercontent.com/assets/4588562/7519789/72efdc58-f4b0-11e4-8d67-1af0054d6633.PNG)

**Comment by justinmk** [comment]
:+1: So when you escape, it takes you to the outer nvim host, and `:` there applies to that instance of nvim. You would then need to `i` and `:`. Mapping `<esc>` like that makes it impractical to nest instances of `[n]vim`, so if that is something you want to do often, I would recommend some other mapping such as `jk` or `<esc><esc>`. Actually, I might do that myself:

    tnoremap <esc><esc> <c-\><c-n>

P.S.: `git commit` defaults to `$EDITOR`, so you could `export EDITOR=path/to/nvim` in your bashrc, and it will use nvim instead of vim.

**Comment by rockneverdies55** [comment]
Yeap, that fixed it. And I really like the <esc><esc> idea. 
Taking care of the issue with a solution, very fast responses, additional tip on `$EDITOR` config to use `nvim`... I don't know how to thank... You're great...

**Comment by simonweil** [comment]
If it's interesting for you, this is my mappings to take care of escaping and splits:

```viml
" terminal settings:
if exists(':terminal')
  " allow terminal buffer size to be very large
  let g:terminal_scrollback_buffer_size = 100000

  " map esc to exit to normal mode in terminal too
  tnoremap <Esc><Esc> <C-\><C-n>

  " Jump and Create splits easily
  tnoremap <A-h> <C-\><C-n><C-w>h
  tnoremap <A-j> <C-\><C-n><C-w>j
  tnoremap <A-k> <C-\><C-n><C-w>k
  tnoremap <A-l> <C-\><C-n><C-w>l
  tnoremap <A-c> <C-\><C-n><C-w>c
  nnoremap <A-h> <C-w>h
  nnoremap <A-j> <C-w>j
  nnoremap <A-k> <C-w>k
  nnoremap <A-l> <C-w>l
  nnoremap <A-c> <C-w>c
  tnoremap <A-d>t   <C-\><C-n>:vsp \| term://bash -l<CR>
  tnoremap <A-d>    <C-\><C-n>:vsp<CR>
  tnoremap <A-s-d>t <C-\><C-n>:sp \| term://bash -l<CR>
  tnoremap <A-s-d>  <C-\><C-n>:sp<CR>
  nnoremap <A-d>t   <ESC>:vsp \| term bash -l<CR>
  nnoremap <A-d>    <ESC>:vsp<CR>
  nnoremap <A-s-d>t <ESC>:sp \| term bash -l<CR>
  nnoremap <A-s-d>  <ESC>:sp<CR>

  " go into insert mode when entering the terminal
  au WinEnter term://* startinsert
endif
```

**Comment by rockneverdies55** [comment]
Thanks @simonweil for the mappings.
