### ISSUE TITLE
LSP: support connection via named pipes / unix domain sockets

### ISSUE THREAD

**Issue by TheLeoP** [neovim/neovim#26031]
### Problem

Some language servers (like [Powershell Editor Services](https://github.com/PowerShell/PowerShellEditorServices#named-pipesunix-domain-sockets-recommended)) support connecting to them via named pipes (on Windows) or unix domain sockets (on Unix). Currently, the Neovim LSP client does not support this type of connection for LSPs (it supports using stdio and tcp).

### Expected behavior

The Neovim LSP client would be able to connect to an LSP via named pipes / unix domain sockets.

**Comment by kls1991** [comment]
Wait it for a long time, thank you.
Can you share a demo about powershell lsp after meged?

**Comment by TheLeoP** [comment]
@kls1991 My main use case is [powershell.nvim](https://github.com/theleop/powershell.nvim). It's not really usable yet, though
