### ISSUE TITLE
`vim.diagnostic.get_next` does not accept a list like severity table

### ISSUE THREAD

**Issue by vjrasane** [neovim/neovim#26048]
### Problem

Unlike `vim.diagnostic.get`, `get_next` does not respect a list like severity table.

A single severity value as well as the min/max keys do work similarly.

Version info:

```{
  api_compatible = 0,
  api_level = 11,
  api_prerelease = false,
  major = 0,
  minor = 9,
  patch = 4,
  prerelease = false
}
```

### Expected behavior

It would be more consistent and useful if `get_next` would also accept a list of severities.

**Comment by Kibadda** [comment]
Can you provide a minimal reproduction? 
With following steps this works as expected.

Steps:
1. nvim --clean text.txt -c 'source minimal.lua'
1. `:=vim.diagnostic.get_next { severity = { vim.diagnostic.severity.ERROR, vim.diagnostic.severity.WARN } }`

Result:
```lua
{
  bufnr = 1,
  col = 0,
  end_col = 0,
  end_lnum = 3,
  lnum = 3,
  message = "WARN",
  namespace = 1,
  severity = 2
}
```

With:

text.txt
```
aaa
aaa
aaa
aaa
aaa
aaa
aaa
```

minimal.lua
```lua
local ns = vim.api.nvim_create_namespace "diagnostics"

vim.diagnostic.set(ns, 0, {
  {
    lnum = 1,
    col = 0,
    severity = vim.diagnostic.severity.INFO,
    message = "INFO",
  },
  {
    lnum = 3,
    col = 0,
    severity = vim.diagnostic.severity.WARN,
    message = "WARN",
  },
  {
    lnum = 5,
    col = 0,
    severity = vim.diagnostic.severity.ERROR,
    message = "ERROR",
  },
})
```

**Comment by justinmk** [comment]
OP didn't say what version they are using so I assume this is outdated.

**Comment by vjrasane** [comment]
> OP didn't say what version they are using so I assume this is outdated.

I did say the version. It's 0.9.4.

@Kibadda tested with that approach and my result was: ```lua 
{                                                                                                                                                                                                                                                   
  bufnr = 1,
  col = 0,
  end_col = 0,
  end_lnum = 1,
  lnum = 1,
  message = "INFO",
  namespace = 1,
  severity = 3
}
```
but if it works for you then maybe you're using a more recent version?

**Comment by Kibadda** [comment]
> I did say the version. It's 0.9.4.

Oh I did not see that.
This feature was introduced in 0.10

**Comment by clason** [comment]
(The issue template is there for a reason; delete it at your own peril.)
