### ISSUE TITLE
Neovim can't recreate UNIX socket after SIGKILL

### ISSUE THREAD

**Issue by alopatindev** [neovim/neovim#26053]
### Problem

If nvim (or OS) has crashed, nvim won't be able to rewrite UNIX socket file with the same path as before, so client that expects this socket to be valid can't use it anymore.

Neovim complains `Failed to start server: address already in use` in this case (which is false, because `nvim --remote-send` reports `E247: Failed to connect to '/tmp/test.sock': connection refused. Send failed.`).

I've got a dirty [workaround](https://github.com/alopatindev/cargo-limit/blob/b7b66e7cda58ac818d5570a35e96040dcfcbf4a2/plugin/cargo-limit.vim#L139-L159) that **works on GNU/Linux and macOS**, it'd be great if Neovim behaved something like that out of the box (instead of having _this_ implemented in other plugins in future).

### Steps to reproduce

0. `rm -f /tmp/test.sock`
1. Run `nvim --clean`, `:call serverstart('/tmp/test.sock')`
2. In the other terminal: `nvim --clean --headless --server /tmp/test.sock --remote-send '<Esc>:echo "hello"<Enter>'` and then `killall -9 nvim`
3. Run `nvim --clean` again, `:call serverstart('/tmp/test.sock')`
4. In the other terminal run `nvim --clean` again, `:call serverstart('/tmp/test.sock')`
5. In the other terminal: `nvim --clean --headless --server /tmp/test.sock --remote-send '<Esc>:echo "world"<Enter>'`

### Expected behavior

- Neovim instance **from step 3** should rewrite the socket file **if nobody actually listens** to it and **should print "world"** (this step currently fails with `Failed to start server: address already in use`)
- Neovim instance **from step 4** shouldn't rewrite the socket file (since it's already been listened) and **should not print "world"** (this works as expected)

### Neovim version (nvim -v)

0.9.2

### Vim (not Nvim) behaves the same?

Not applicable: `E117: Unknown function: serverstart`

### Operating system/version

Gentoo GNU/Linux

### Terminal name/version

wezterm

### $TERM environment variable

tmux-256color

### Installation

Gentoo Portage

**Comment by alopatindev** [comment]
Currently `serverstart` seems to be [implemented using libuv](https://github.com/neovim/neovim/blob/d92dd2a0c05148154c353f0e7cd2099b2427308a/src/nvim/event/socket.c#L113).

I'm not familiar with libuv. Does it support UNIX socket state querying? I don't see that from [the documentation](https://docs.libuv.org/en/v1.x/pipe.html).

If it does — I believe all we need to do is check whether existing socket file is not in the `LISTEN` state and then remove it. Otherwise some other API is likely unavoidable if we want to fix this issue.

**Comment by justinmk** [comment]
# Status

https://github.com/neovim/neovim/pull/30237 added validation to `--listen`, so now Nvim will fail to start if the listen address is invalid. However, the request in this issue makes sense and is not yet implemented.

> Otherwise we could simply make connection attempt to existing socket file and remove it if connection was refused.

That seems reasonable, at least as a first pass. Let's use https://github.com/neovim/neovim/issues/30123 to track this, I will add your notes there.
