### ISSUE TITLE
inccommand should default to false in ex mode

### ISSUE THREAD

**Issue by Huluk** [neovim/neovim#26056]
### Problem

In ex mode, I expect the screen to only redraw explicitly when I issue a command.

Because `inccommand` defaults to "nosplit", the view jumps around for live preview while writing a substitution command.

### Steps to reproduce

nvim -E somefile
:%s/example

### Expected behavior

No visual changes while typing.

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

no, 9.0.1894

### Operating system/version

macOS 14.1.1

### Terminal name/version

iTerm 3.4.22

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by clason** [comment]
Sorry, can't please everyone. Most other people appreciate the visual feedback by default.

**Comment by Huluk** [comment]
I appreciate the visual feedback, too! But I think in `ex` mode the behaviour should be different – it's a compatibility mode, and designed among other things for systems with low refresh rate. It should work on a printer, in principle.

I'm not sure if neovim distinguishes `-e` from `-E`, but the behaviour is broken in both, and should work at least in `-e`.

**Comment by justinmk** [comment]
Oh, agreed. I recall looking at this logic in the original 'inccommand' impl, maybe something regressed somehow.
