### ISSUE TITLE
Treesitter indentation breaks in python unclosed  '[' anywhere in file 

### ISSUE THREAD

**Issue by BogdanTheGeek** [neovim/neovim#26067]
### Problem

Automatic indentation inserts way too many indents in python when treesitter highlighting is enabled. 

![image](https://github.com/neovim/neovim/assets/8824186/fbc8d7a5-fe93-4eea-9b9f-ffdfe1fd98a9)

I have isolated the issue to treesitter by disabling all other plugins.
This seems to only happen in python, even if i disable `indent` in the setup function. The only way to get it to not do it is to disable `highlight` in the setup function or to remove the VT100 codes form the current buffer.

Using tree-sitter--0.20.8.arm64_sonoma.bottle.tar.gz
and the latest version of   `https://github.com/nvim-treesitter/nvim-treesitter`

### Steps to reproduce

nvim test.py
i
```py
def RED(string):
    return "\033[31m" + string + "\033[0m"
```
:2
o

### Expected behavior

Indentation is aligned with the `return`

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

idk

### Operating system/version

macOS 14.0

### Terminal name/version

alacritty

### $TERM environment variable

screen-256color

### Installation

built from source stable branch

**Comment by BogdanTheGeek** [comment]
switching to v0.8.3 gives this error:
![image](https://github.com/neovim/neovim/assets/8824186/82f914bd-55ef-4fdf-bd7c-c808c348164c)

no errors in `:messages`, not sure where else to check for it

**Comment by BogdanTheGeek** [comment]
looks like it might not be VT100 codes, but any unclosed open `[` in a string, even in a comment. The indentation continues on the last open `[`.
![image](https://github.com/neovim/neovim/assets/8824186/f1a03367-14dd-48ad-86d4-50b6713d269b)

**Comment by justinmk** [comment]
Is this a problem with the parser or Nvim's treesitter logic? Sounds like a parser issue...

**Comment by BogdanTheGeek** [comment]
> Is this a problem with the parser or Nvim's treesitter logic? Sounds like a parser issue...

could be either, not sure how to check. I would assume it is a parser error, because it thinks its an unclosed list instead of a commet/string

**Comment by justinmk** [comment]
We don't maintain, nor ship, a python parser, yet.

**Comment by clason** [comment]
> We don't maintain, nor ship, a python parser, yet.

Oh but we do.

But we don't maintain or ship tree-sitter indentation logic, so this is an issue for nvim-treesitter (which does).

**Comment by BogdanTheGeek** [comment]
> > We don't maintain, nor ship, a python parser, yet.
> 
> Oh but we do.
> 
> But we don't maintain or ship tree-sitter indentation logic, so this is an issue for nvim-treesitter (which does).

ok, thank you. I will report the bug with them.

**Comment by justinmk** [comment]
> > We don't maintain, nor ship, a python parser, yet.
> 
> Oh but we do.

Huh, forgot.... https://github.com/neovim/neovim/pull/24219

**Comment by BogdanTheGeek** [comment]
For anyone following https://github.com/nvim-treesitter/nvim-treesitter/issues/5679
