### ISSUE TITLE
`cw` should edit till the next word and not until the end of the current word (like `dwi` and not like `ce`)

### ISSUE THREAD

**Issue by robinmoussu** [neovim/neovim#26066]
### Problem

- `w` move the cursor to the next word (after the whitespace)
- `dw` will delete until the next word (including the whitespace)
- `e` move the cursor until the end of the word (before the whitespace)
- `de` will delete until the end of the word (before the whitespace
 
All of those are coherent. However:

- `ce` will change until the end of the current word (before the whitespace), as expected
- `cw` will also change until the end of the current word (before the whitespace) which is unexpected

Given that `cw` behavior was copied from vim, and most probably from vi, I’m not sure if this is a bug or a feature request. I know that this will break the habit of some people, but `Y` was fixed to behave as `y$` to be consistent with `D` and `C`, so I hope that `cw` could also be changed to be consistent with `dw`.

### Steps to reproduce

Put your cursor in a word, press `cw`. The whitespace after the word should be removed.

### Expected behavior

`cw` should do the same as `dwi` and not `ce`.

### Neovim version (nvim -v)

any

### Vim (not Nvim) behaves the same?

any

### Operating system/version

all

### Terminal name/version

all

### $TERM environment variable

all

### Installation

all

**Comment by clason** [comment]
Sorry, but this is way too intrusive to change. Maybe you can convince Vim of this, and then we would port the changes.

**Comment by justinmk** [comment]
This was already implemented? `:help cpo-_`

**Comment by dundargoc** [comment]
For what it's worth I agree that the default behavior should be changed to be more consistent, for the same reasons as `Y` was changed. I don't know why changing `cw` is more intrusive than `Y`.

I'm not really passionate about this subject though so I'm fine with keeping the current behavior. Just wanted to say my piece.

**Comment by robinmoussu** [comment]
> `set cpoptions-=_`

Thansk, I didn’t know about cpoptions. I also think that the default should be changed, but in the meantime cpoptions is good enough.

**Comment by mfussenegger** [comment]
>  don't know why changing cw is more intrusive than Y.

because it's a way more common operation that almost every vi-emulation also supports - and they match the existing behaviour.
And one also has to consider the intent of the user.  If you delete a word you usually don't want to leave an extra whitespace in the line. If you change a word you are likely to keep the whitespace.
Consistency as argument is decent as tie breaker if there are no other compelling arguments, but as a standalone argument it's pretty weak
