### ISSUE TITLE
Proposal: new event/autocmd when Git conflict markers are detected

### ISSUE THREAD

**Issue by DrGo** [neovim/neovim#26060]
### Problem

Would it be reasonable for neovim to fire an event (e.g., GitConflictDetected) when a file is opened and it includes Git conflict markers e.g., 
```
<<<<<<< HEAD:file.txt
Hello world
=======
``` 
It will facilitate automating handling of conflicts e.g., loading an appropriate plugin or aborting certain actions. 

### Expected behavior

event fired when a git conflict marker detected.

**Comment by luukvbaal** [comment]
Seems way to specific for a dedicated autocommand. Just use `BufRead` and detect the conflict markers?

**Comment by zeertzjq** [comment]
No.

**Comment by justinmk** [comment]
You can use `]n` from vim-unimpaired to go to the next conflict marker.
https://github.com/tpope/vim-unimpaired/blob/6d44a6dc2ec34607c41ec78acf81657248580bf1/doc/unimpaired.txt#L55-L61

**Comment by DrGo** [comment]
Thanks Justin,
The idea was to get a hook that will allow triggering certain actions related to the presence of these markers (e.g., after performing a git pull). It can be implemented within a BufRead but that is not efficient for large files. Git being a universal requirements for programming these days, I thought it would make sense to have this hook natively (almost like what neovim does now with FileType; which is another way of implementing this).

**Comment by zeertzjq** [comment]
Then `BufRead` is exactly what is used.
