### ISSUE TITLE
Recent changes made broke cursor in kitty

### ISSUE THREAD

**Issue by leiserfg** [neovim/neovim#26074]
### Problem

Since https://github.com/neovim/neovim/commit/405bad5e085fb359879646b6fd6fbcddae83eac5 the cursor in kitty does not blink (which depending on the color scheme can make it invisible).

### Steps to reproduce

Open kitty and run 
```sh
nvim --clean
```
from that commit or a newer one.

I also noticed that disabling `termsync` makes it blink again.

### Expected behavior

Nvim opens and the cursor blinks

### Neovim version (nvim -v)

405bad5e085fb359879646b6fd6fbcddae83eac5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux

### Terminal name/version

kitty 030.1

### $TERM environment variable

xterm-kitty

### Installation

Build it from master using nix

**Comment by leiserfg** [comment]
I'm invoking  @gpanders :smile:

**Comment by gpanders** [comment]
Your reproduction steps are insufficient, `nvim --clean` does not enable cursor blink in any case. Please provide whatever other configuration you are using (either in kitty or nvim) to enable cursor blink.

**Comment by gpanders** [comment]
I actually think this is now working as intended and that this was a bug that it worked before. Cursor blinking in Neovim is configured with the `'guicursor'` setting, and the default value is `blinkon0` (i.e. no blinking). From `:h cursor-blinking`:

```
		blinkwait{N}				*cursor-blinking*
		blinkon{N}
		blinkoff{N}
			blink times for cursor: blinkwait is the delay before
			the cursor starts blinking, blinkon is the time that
			the cursor is shown and blinkoff is the time that the
			cursor is not shown.  Times are in msec.  When one of
			the numbers is zero, there is no blinking. E.g.:  
				:set guicursor=n:blinkon0
 			- Default is "blinkon0" for each mode.
```

If you add `set guicursor+=n:blinkon100-blinkoff100` then the blinking cursor works correctly.

**Comment by gpanders** [comment]
Technically this makes https://github.com/neovim/neovim/pull/26055 a breaking change. I will add a news entry indicating this.
