### ISSUE TITLE
Easy Motion plugin doesn't work in terminal buffer.  

### ISSUE THREAD

**Issue by wreed4** [neovim/neovim#2607]
`EasyMotion: Vim(call):E21: Cannot make changes, 'modifiable' is off : function EasyMotion#WB..<SNR>142_EasyMotion..<SNR>142_PromptUser..<SNR>142_SetLines, line 2`

I figured this might be an issue with how the terminal mode buffer (when in Normal mode, obviously) is displaying itself to plugins.  This error does not present itself when using EasyMotion in other windows where "modifiable" is off.  Only terminal buffers.

**Comment by smondet** [comment]
@justinmk 
- why is it a bad idea? It otherwise works well, and `vim-sneak` is a very poor replacement.
- breaking vim compatibility (EM does `:set modifiable`) needs more justification than just you thinking it's a bad idea, doesn't it?

**Comment by ZyX-I** [comment]
@smondet 

1. Because

    1. Editing buffer *has* unneeded side-effects. You can avoid running autocommands, changing undo tree, changing change list (though it complicats plugin), but you can never avoid `b:changedtick`. It is not as innocent as it sounds: e.g. powerline caches some segments which are rather long to compute on each statusline update based on `changedtick` value. Also I am not entirely sure that I listed all side-effects and that easymotion plugin authors successfully mitigated all of them.
    2. Terminal buffers need full control over buffer text because buffers here are a mere viewports (buffers, not windows which are considered to be viewports for all buffers) to a terminal screen stored internally and in a separate structure. You cannot have such kind of control and working modifications at the same time. You can make it in a fashion “you can do modifications, but they will be thrown away on next screen update”, but this will result in lots of complains like “I edited my bash command-line in normal mode and executed, but edits were ignored” or “I am creating a plugin which does temporary modifications to the buffer which are reset afterwards and these modifications were reset in the middle of the process because of the output”.

2. Vim does not have `:terminal` at all, not to mention `:terminal` with working `set modifiable`. There is no compatibility to talk about here. Though you may patch Neovim to remove `:terminal` from it to make it more compatible.

**Comment by justinmk** [comment]
@smondet Recent versions of EM don't even need to edit the buffer anymore, since this commit: 

https://github.com/easymotion/vim-easymotion/commit/f5ecb99abe118a829602f0517d9fd182d5ce7604

Not sure if it still does so, but there's no technical reason it's needed anymore.

> breaking vim compatibility (EM does :set modifiable) needs more justification than just you thinking it's a bad idea, doesn't it?

We aren't breaking compatibility, because `:terminal` is a neovim-only feature.

**Comment by tecfu** [comment]
@justinmk _Your statement is incorrect per the maintainer of vim-easymotion_ ("Not sure if it still does so, but there's no technical reason it's needed anymore.")

See https://github.com/easymotion/vim-easymotion/issues/322#issuecomment-280923172.

**Comment by justinmk** [comment]
I don't see a technical reason there.

**Comment by haya14busa** [comment]
@justinmk You just don't understand what easymotion does internally.

EasyMotion cannot show targets at empty line or end of line without modifying buffer, and cannot add padding when displaying target at multi-byte characters.

**Comment by justinmk** [comment]
@tecfu Does #6142 work? @haya14busa With #6142, `:term` buffers have default 'undolevels' of -1. Does easymotion temporarily increase 'undolevels'?

**Comment by tecfu** [comment]
@justinmk Works a treat. Love it.

**Comment by haya14busa** [comment]
easymotion doesn't increase 'undolevels' but sometimes easymotion changes undolevels to -1 temporarily and restore original value. Is it problem? If so, maybe I can check buffer is terminal or not.

**Comment by tecfu** [comment]
@justinmk Great work. Thanks again.
