### ISSUE TITLE
large delay when running `:wq` on zig files while LSP is active

### ISSUE THREAD

**Issue by xdBronch** [neovim/neovim#26077]
### Problem

bisected to 22eb2ba18336df6cd70a88f666818ee5d8ba92d2
if i run `:wq` on a zig file while the language server ([zls](https://github.com/zigtools/zls)) is running there is a very large delay before neovim actually exits, 1-2 seconds.

### Steps to reproduce

with zls installed and active
`nvim any_file.zig`
`:wq`

### Expected behavior

neovim should exit immediately as it did before that commit

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1563+g22eb2ba18

### Vim (not Nvim) behaves the same?

no, 9.0.1882

### Operating system/version

linux 6.5.4

### Terminal name/version

ghostty/any

### $TERM environment variable

xterm-ghostty

### Installation

built from source

**Comment by clason** [comment]
please provide reproducing steps with `nvim --clean -u minimal.lua`.

**Comment by zeertzjq** [comment]
Please provide compile flags from `:verbose version` or `nvim -V1 -v`.

**Comment by zeertzjq** [comment]
Also this may be a duplicate of #19727.

**Comment by xdBronch** [comment]
ill need a minute to get a minimal reproducing lua file but i dont think this can be a duplicate of that, i `git bisected` this and it did not happen before https://github.com/neovim/neovim/commit/22eb2ba18336df6cd70a88f666818ee5d8ba92d2 which is much more recent than that issue

**Comment by zeertzjq** [comment]
Read the comments on that issue.

**Comment by xdBronch** [comment]
apologies for the delay
here is the output of `nvim -V1 -v`
```
NVIM v0.10.0-dev-1563+g22eb2ba18
Build type: Release
LuaJIT 2.1.1699801871

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
and a minimal lua file to reproduce
```lua
for name, url in pairs{
	lspconfig = 'https://github.com/neovim/nvim-lspconfig'
} do
	local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
	end
	vim.opt.runtimepath:append(install_path)
end

require'lspconfig'.zls.setup{}
```

the delay should occur when `:wq`ing any zig file

**Comment by zeertzjq** [comment]
Thanks. Cannot reproduce with a RelWithDebInfo build, but can reproduce with an ASAN build.

**Comment by zeertzjq** [comment]
Thanks. Can reproduce, and this is not a duplicate.

**Comment by gpanders** [comment]
I can reproduce this too. This is all that is needed to reproduce:

```sh
cat >repro.vim <<EOF
autocmd FileType zig lua vim.lsp.start({cmd = {'zls'}})
EOF
nvim --clean -u repro.vim test.zig
```

Then `:wq` inside Nvim.

This only happens when using `:wq`. It does not happen with plain `:q`, `:x`, `ZQ`, or `ZZ`

**Comment by gpanders** [comment]
I am fairly confident this is not zls specific but will happen with any server that implements `textDocument/willSaveWaitUntil`. When Nvim is exiting we make a synchronous request to the server. The RPC layer uses `vim.schedule` to schedule its callback, but because of https://github.com/neovim/neovim/commit/22eb2ba18336df6cd70a88f666818ee5d8ba92d2 that callback is never called, so the synchronous request never receives a response and eventually times out.

**Comment by xdBronch** [comment]
i imagined it wasnt zls specific but its all i found that did it, i appreciate the quick investigation
