### ISSUE TITLE
error building implicit function and incompatible integer to pointer conversion

### ISSUE THREAD

**Issue by karasjoh000** [neovim/neovim#26087]
### Problem

```bash
# CCACHE_DISABLE=true make CMAKE_BUILD_TYPE=Release \
#	CMAKE_INSTALL_PREFIX=$HOME/.neovim.install \
#	CMAKE_EXTRA_FLAGS='-DCMAKE_CXX_COMPILER=/home/jkarasev/intel/oneapi/compiler/2024.0/bin/icpx -DCMAKE_C_COMPILER=/home/jkarasev/intel/oneapi/compiler/2024.0/bin/icx' \
#       DEPS_CMAKE_FLAGS="-DCMAKE_CXX_COMPILER=/home/jkarasev/intel/oneapi/compiler/2024.0/bin/icpx -DCMAKE_C_COMPILER=/home/jkarasev/intel/oneapi/compiler/2024.0/bin/icx"

[ 77%] Building C object src/nvim/CMakeFiles/nvim.dir/os/pty_process_unix.c.o
/home/jkarasev/neovim/src/nvim/os/pty_process_unix.c:232:10: error: call to undeclared function 'ptsname'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  232 |   return ptsname(ptyproc->tty_fd);
      |          ^
/home/jkarasev/neovim/src/nvim/os/pty_process_unix.c:232:10: note: did you mean 'ttyname'?
/usr/include/unistd.h:799:14: note: 'ttyname' declared here
  799 | extern char *ttyname (int __fd) __THROW;
      |              ^
/home/jkarasev/neovim/src/nvim/os/pty_process_unix.c:232:10: error: incompatible integer to pointer conversion returning 'int' from a function with result type 'const char *' [-Wint-conversion]
  232 |   return ptsname(ptyproc->tty_fd);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[3]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:3454: src/nvim/CMakeFiles/nvim.dir/os/pty_process_unix.c.o] Error 1
make[3]: Leaving directory '/home/jkarasev/neovim/build'
make[2]: *** [CMakeFiles/Makefile2:532: src/nvim/CMakeFiles/nvim.dir/all] Error 2
make[2]: Leaving directory '/home/jkarasev/neovim/build'
make[1]: *** [Makefile:156: all] Error 2
make[1]: Leaving directory '/home/jkarasev/neovim/build'
make: *** [Makefile:84: nvim] Error 2
```

### Steps to reproduce

```bash
CCACHE_DISABLE=true make CMAKE_BUILD_TYPE=Release \
	CMAKE_INSTALL_PREFIX=$HOME/.neovim.install \
	CMAKE_EXTRA_FLAGS='-DCMAKE_CXX_COMPILER=/home/jkarasev/intel/oneapi/compiler/2024.0/bin/icpx -DCMAKE_C_COMPILER=/home/jkarasev/intel/oneapi/compiler/2024.0/bin/icx' \
	DEPS_CMAKE_FLAGS="-DCMAKE_CXX_COMPILER=/home/jkarasev/intel/oneapi/compiler/2024.0/bin/icpx -DCMAKE_C_COMPILER=/home/jkarasev/intel/oneapi/compiler/2024.0/bin/icx"
```

### Expected behavior

It should compile without error

### Neovim version (nvim -v)

fe869a8ce25a14497a9bf5ddca0ae11a1c38a22c

### Vim (not Nvim) behaves the same?

Did not try this.

### Operating system/version
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
### Terminal name/version

ubuntu wsl

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
Please provide Ubuntu version. (E.g. from the output of `lsb_release -a`)

**Comment by karasjoh000** [comment]
@zeertzjq added ubuntu version.

**Comment by karasjoh000** [comment]
note a temporary fix seems to be adding this into the CMakeLists.txt: 
```cmake
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-implicit-function-declaration -Wno-int-conversion")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-implicit-function-declaration -Wno-int-conversion")
```

but not permanent fix. It can be an Intel compiler issue, because it seems like the implicit function in question did have included header. idk. Maybe some macro logic for headers.

**Comment by e-kwsm** [comment]
I can reproduce the issue with icx 2023.1.0 on Debian 12.2.

The simplest solution is to add `-D_GNU_SOURCE`, which satisifies the followings:

- `-D_XOPEN_SOURCE=500` for [`ptsname`](https://man7.org/linux/man-pages/man3/ptsname.3.html)
- `-D_POSIX_C_SOURCE=200809L` for [`strnlen`](https://man7.org/linux/man-pages/man3/strnlen.3.html)
- `-D_DEFAULT_SOURCE` for [`htobe64`](https://man7.org/linux/man-pages/man3/htobe64.3.html)

The macros and their required values depend on the glibc version, as specified in the man’s.
See also [feature_test_macros(7)](https://man7.org/linux/man-pages/man7/feature_test_macros.7.html).

Anyway, I believe this is an icx–glibc problem.

**Comment by e-kwsm** [comment]
https://github.com/neovim/neovim/blob/d667e0e4142ba8eb8623971539b0f9eec78b7529/src/nvim/CMakeLists.txt#L197-L209

**Comment by dundargoc** [comment]
@e-kwsm @karasjoh000 does https://github.com/neovim/neovim/pull/26124 solve this problem?

**Comment by e-kwsm** [comment]
Yes, it fixes the issue.
