### ISSUE TITLE
inner word including brackets on some texts like `(???)` `(...)` `(!!!)`

### ISSUE THREAD

**Issue by konosubakonoakua** [neovim/neovim#26088]
### Problem

inner word including brackets on some texts like `(???)` `(...)` `(!!!)`
shouldn't the `iw` only select the inner text `???`, `...`, and `!!!`

### Steps to reproduce

`nvim -u none`
type some text like:
```
(???) (!!!) (...)
```
using `viw` to visual select the inner part.
btw, I can use `vi(` to correctly select the `???`.

### Expected behavior

`viw` on `(???)` only select the word `???`

### Neovim version (nvim -v)

NVIM v0.10.0-dev-a8fc94a

### Vim (not Nvim) behaves the same?

yes, vim 8.2

### Operating system/version

ubuntu 22

### Terminal name/version

gnome terminal

### $TERM environment variable

xterm-256color

### Installation

nightly release

**Comment by zeertzjq** [comment]
'iskeyword'

**Comment by konosubakonoakua** [comment]
`vim.opt.iskeyword:append({ "-", "?", "!", "." })`
