### ISSUE TITLE
Error executing vim.schedule lua callback: Cursor position outside buffer

### ISSUE THREAD

**Issue by WillianFuks** [neovim/neovim#26094]
### Problem

When using the LSP function `goto definition` on certain places I get the error:

```
Error executing vim.schedule lua callback: /home/will/.local/share/nvim/runtime/lua/vim/lsp/util.lua:1157: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        /home/will/.local/share/nvim/runtime/lua/vim/lsp/util.lua:1157: in function 'jump_to_location'
        .../will/.local/share/nvim/runtime/lua/vim/lsp/handlers.lua:405: in function 'handler'
        /home/will/.local/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Curiously, I just downloaded the llama_index python code and most of the class definitions I'm trying to go is returning this error. At times it does work after the failure but sometimes the cursor stays stuck at place.

I recorded the error being thrown, first I execute the `goto` LSP function, the error throws but the cursor still finds the definition in this case. Then I hit `<Ctrl + O>` to go back and it lands in the file `app.py` from another package (don't know why) and hitting `<Ctrl + O>` the cursor returns from where it started which seems to indicate the `goto` is first jumping to the wrong place and then going to the proper one.

https://github.com/neovim/neovim/assets/4665485/be7142b0-97e8-4a45-86ab-e4f8d5aa9aea

### Steps to reproduce

git clone git@github.com:run-llama/llama_index.git
cd llama_index
lvim experimental/splitter_playground/app.py
(take cursor to `Document` class)
run LSP go to definition: `lua vim.lsp.buf.definition()`

### Expected behavior

No errors

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1692716794

### Vim (not Nvim) behaves the same?

haven't tested

### Operating system/version

Ubuntu 20.04

### Terminal name/version

terminator 1.91

### $TERM environment variable

xterm-256color

### Installation

lunarvim script

**Comment by clason** [comment]
Sorry, we don't support LunarVim; it messes too much with Neovim internals. Please provide a minimal example without LunarVim and a standalone config we can test with `nvim --clean -u test.lua`.
