### ISSUE TITLE
E486: Pattern not found: 0000

### ISSUE THREAD

**Issue by hungrybirder** [neovim/neovim#26107]
### Problem

After upgrading neovim to the latest, I got a `E486` Error at startup.

 

### Steps to reproduce

```bash
brew uninstall neovim
brew install --HEAD neovim
```

```bash
nvim -V1 -v
NVIM v0.10.0-dev-1600+ga84b454eb-Homebrew
Build type: Release
LuaJIT 2.1.1699801871

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-a84b454/share/nvim"

Run :checkhealth for more info
```

Start neovim:
`nvim -u NONE`

![CleanShot 2023-11-19 at 14 53 43@2x](https://github.com/neovim/neovim/assets/1021047/d850cc75-f349-4155-8bd8-6de6d15b95b9)
![CleanShot 2023-11-19 at 14 54 04@2x](https://github.com/neovim/neovim/assets/1021047/65cdfb11-2d69-43e9-8847-495e82529794)

### Expected behavior

No E486 Error 

### Neovim version (nvim -v)

a84b454eb

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 14.1.1

### Terminal name/version

iTerm 3.4.22

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
It's likely that your iTerm2 version is too old..

**Comment by zeertzjq** [comment]
And Homebrew HEAD build isn't supported.

**Comment by zeertzjq** [comment]
Duplicate of #26093
