### ISSUE TITLE
the `@Spell` and `@NoSpell` groups are too opinionated 

### ISSUE THREAD

**Issue by buschco** [neovim/neovim#26111]
### Problem

For me, a spell checker should check everything what is **not** a keyword by the language.

### Expected behavior

Maybe some kind of `Spell`-levels could be introduced:

`@Spell` for Comments or strings
`@SpellCode` for Variables function names etc.
`@NoSpell` for keywords

What do you think?

**Comment by clason** [comment]
You are welcome to customize the queries to your heart's content. 

If you have concrete suggestions about specific captures, feel free to make a PR to nvim-treesitter. We are not interested in adding more fine-grained capture types, though.

**Comment by buschco** [comment]
> You are welcome to customize the queries to your heart's content.

I agree this is possible, but it is not very convenient. This means I have to create a `highlights.scm` file for every language supported by `nvim-treesitter`. If one language is added to `nvim-treesitter` I wont get any spell checking until I also add this file to my `queries` folder.

A possible solution without creating "more fine-grained capture types" could look like this:

1. Add a `@NoSpell` to all language keywords in `nvim-treesitter`
2. Add a `spell-syntax-level` option, similar to the [`syn-spell`](https://neovim.io/doc/user/syntax.html#%3Asyn-spell) setting:

```
spell-syntax-level
1.  default		spell check if "contains=@Spell"
2.  nokeyword		spell check if not "contains=@NoSpell"
3.  everywhere		spell check everything
```

**Comment by clason** [comment]
"Global" options are out of scope here; these would -- if at all -- have to be handled by Neovim core.

**Comment by buschco** [comment]
What do you mean with "out of scope here"?
