### ISSUE TITLE
Xcode fails to compile for iOS

### ISSUE THREAD

**Issue by Dario48true** [neovim/neovim#26112]
### Problem

when I try to compile nvim for iOS 17 through Xcode I get a `Command PhaseScriptExecution failed with a nonzero exit code` error
![image](https://github.com/neovim/neovim/assets/118165619/c3f7fdf0-3079-411b-986b-1bb1ffb007a6)
![image](https://github.com/neovim/neovim/assets/118165619/5cad42cc-11d9-4368-a381-da94fc5ecabc)
![image](https://github.com/neovim/neovim/assets/118165619/2cfef46e-5e3e-4567-913b-50d85f60f2dd)

### Steps to reproduce

git clone neovim
`make deps` in the neovim folder
`cmake -G Xcode -T buildsystem=1 neovim` with `neovim` being the folder containing the files cloned
try to compile for iOS 17

### Expected behavior

it compiles correctly

### Neovim version (nvim -v)

n/a

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 14.0. iOS 17.0, Xcode 15.0.1

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

n/a

**Comment by bfredl** [comment]
Need a full textual log or something, cropped screenshots doesn't tell us anything.

**Comment by Dario48true** [comment]
[Build nvim_2023-11-19T13-04-42.txt](https://github.com/neovim/neovim/files/13414815/Build.nvim_2023-11-19T13-04-42.txt)
this?

**Comment by gpanders** [comment]
```
	dlopen(/Users/rgennari/Documents/neovim_build/lib/libnlua0.so, 0x0006): tried: '/Users/rgennari/Documents/neovim_build/lib/libnlua0.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/rgennari/Documents/neovim_build/lib/libnlua0.so' (no such file), '/Users/rgennari/Documents/neovim_build/lib/libnlua0.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
stack traceback:
	[C]: at 0x0102c520d0
	[C]: in function 'require'
	...ents/neovim_build/neovim/src/nvim/generators/preload.lua:7: in main chunk
	[C]: at 0x0102be28d0
make: *** [/Users/rgennari/Documents/neovim_build/src/nvim/auto/api/autocmd.c.generated.h] Error 1
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by dundargoc** [comment]
Xcode has been disabled as an allowed generator for the forseeable future as it cannot handle multiple targets depending on the same command, which is very annoying to comply with and would require a lot of refactoring and boilerplate in order to work.
