### ISSUE TITLE
Feature Request: Add a `SPEC` to get path under cursor with line and column 

### ISSUE THREAD

**Issue by protiumx** [neovim/neovim#26128]
### Problem

Output from compilers, linters and test utilities generally output errors positions as **`<file>:<line>:<column>` but `<cfile>` only expands the file path, it does not consider line and column.
`gF` can be used to jump to file and line number but it doesn't consider the column.

### Expected behavior

Add a new spec like <cfile> to expand the path with path and position.
For instance, consider `<cxfile>` (cursor expanded file) or `<cfilelc>` (cursor file, line and column).
`^` is the position of the cursor
```
undeclared variable at source.c:99:6
                                  ^
```
Running `:echo expand('<cfilelc>')`  prints `source.c:99:6`.
Then a lua utility can be used to open the file at the position
```lua
  local parts = vim.split(vim.fn.expand('<cfilelc>'), ':')
  local pos_cmd = string.format('call cursor(%s, %s)', parts[2], #parts == 3 and parts[3] or '0')

  local cmd = string.format('drop %s | %s', parts[1], pos_cmd)
  vim.cmd(cmd)
```
A further enhancement would be changing the behavior of `gF` to consider the column but a major refactor would be needed.

I could work on this as it seems fairly simply to do based on the current implementation to handle `<cfile>` (https://github.com/neovim/neovim/blob/488038580934f301c1528a14548ec0cabd16c2cd/src/nvim/ex_docmd.c#L6979)
but I'd first like a to get feedback from maintainers and the community.

**Comment by protiumx** [comment]
Hi @Lattay, thank you for the awesome suggestion!
That definitely works as a better solution to support different file and position formats.
I'm closing this in favour of `errorformat`

**Comment by justinmk** [comment]
> further enhancement would be changing the behavior of `gF` to consider the column

See also discussion in https://github.com/neovim/neovim/issues/1281#issuecomment-1594437052
