### ISSUE TITLE
bug: visual star `*` doesn't work for emoji

### ISSUE THREAD

**Issue by mrbeardad** [neovim/neovim#26120]
### Problem

![image](https://github.com/neovim/neovim/assets/54128430/b694cfc5-50cf-4640-be0c-e60799ea8ef2)

### Steps to reproduce

see the picture above

### Expected behavior

cursor should move to next match emoji.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-9af03bc

### Vim (not Nvim) behaves the same?

unknown

### Operating system/version

Microsoft Windows 11 Home 10.0.22621 N/A Build 22621

### Terminal name/version

Windows Terminal

### $TERM environment variable

empty

### Installation

scoop install neovim-nighlty

**Comment by clason** [comment]
Works for me (macOS, iTerm2 3.5beta). 

I suspect you `set clipboard` to a non-default value. Always test with `nvim --clean`!

**Comment by clason** [comment]
Does Nvim 0.9.x behave differently? Can you bisect? And please _do_ test Vim.

**Comment by zeertzjq** [comment]
Vim doesn't not have this mapping.

**Comment by mrbeardad** [comment]
> Works for me (macOS, iTerm2 3.5beta).
> 
> I suspect you `set clipboard` to a non-default value. Always test with `nvim --clean`!

I've test with `nvim --clean`, and `set clipboard` is `clipboard=`

> Does Nvim 0.9.x behave differently? Can you bisect? 

It work in NVIM v0.9.4.

> And please _do_ test Vim.

Neovim has default mapping for visual star `*`, see `:h v_star-default`. Vim doesn't have this mapping.
