### ISSUE TITLE
Include more extensive tests of :terminal mode

### ISSUE THREAD

**Issue by MarkLodato** [neovim/neovim#2612]
I just reported Issue #2611, which is a segfault in the handling of DECSTBM, but I suspect that there are other errors in the VT100 emulation as well.  This is something that should have been caught in a test.

I have written a set of [extensive test cases](https://github.com/MarkLodato/vt100-parser/blob/master/test/) as part of my [vt100-parser](https://github.com/MarkLodato/vt100-parser).  For each `.in` file file in the test directory, I have run [rawcat](https://github.com/MarkLodato/vt100-parser/blob/master/rawcat) on xterm with an 80-column window and copied the result to the `.text` file.  In this way, I have documented exactly how xterm handles a variety of situations (wraparound, invalid arguments, etc.)  I suggest including this set of test cases in NeoVim.  If you need any more info, please let me know!

**Comment by Pyrohh** [comment]
This sounds like a great idea, although I'm not sure nvim directly parses any terminal codes anymore (someone correct me if I'm wrong).

**Comment by fwalch** [comment]
Maybe interesting for @leonerd?

**Comment by leonerd** [comment]
Yeah, most of these things would be more of interest to libvterm, as nvim itself just uses that for the terminal management.

**Comment by MarkLodato** [comment]
Gotcha.  Reported as https://bugs.launchpad.net/libvterm/+bug/1453611.
