### ISSUE TITLE
Diagnostics get stuck after :e! / :edit!

### ISSUE THREAD

**Issue by andrescuco** [neovim/neovim#26131]
### Problem

LSP diagnostics get stuck / stop working after running :e! command on neovim. See screenrecording:

https://github.com/neovim/neovim/assets/36432023/f9cadf18-83a1-4c8c-9518-9dec2d1b327a

_Note: originally reported here_ https://github.com/neovim/nvim-lspconfig/issues/2909

### Steps to reproduce using "nvim -u minimal_init.lua"

init.vim
```
call plug#begin('~/.vim-plugged')
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua <<EOF
  local lspconfig = require('lspconfig')
  require('lspconfig')['tsserver'].setup {}
EOF
```

1. Setup a language server, like shown above
2. Make a file change that triggers a diagnostic
3. Write :e! on neovim command mode and press Enter
4. Now the diagnostic is stuck, it won't work for that particular file until you restart :LspRestart

### Expected behavior

Diagnostics shouldn't be stuck, they should be able to keep working after :e! and be updated based on the latest changes to the buffer.

### Neovim version (nvim -v)

NVIM v0.9.4

### Language server name/version

typescript-language-server@4.1.2

### Operating system/version

Debian GNU/Linux VERSION="10 (buster)"

### Log file

https://gist.github.com/andrescuco/930182635d7acdbbb174eae6a2e5a1e4

**Comment by rudiejd** [comment]
Should this be reported over at https://github.com/typescript-language-server/typescript-language-server? Other language servers don't have this issue

**Comment by wookayin** [comment]
Likely to be a bug of LSP: see #26640 for a similar bug with ruby-lsp. The typescript LSP might be sending an invalid response; so it would be worth checking the response in the `textDocument/diagnostic` handler. See also https://github.com/neovim/neovim/pull/26957#issuecomment-1885774765.

**Comment by andrescuco** [comment]
Thank you for the inputs @rudiejd, @wookayin, just became aware of https://github.com/typescript-language-server/typescript-language-server/pull/851. Updating typescript-language-server to v4.3.1 or above fixes this.
