### ISSUE TITLE
Backspace cannot unindent code

### ISSUE THREAD

**Issue by matze** [neovim/neovim#2613]
To reproduce the problem open a new file with – in this case – Python file format and enter
```python
if foo:
    |
```
where `|` denotes the cursor position. Trying to undo the indentation by pressing backspace does not work. I still can use the arrow keys in insert mode or go back to normal mode to go to the first column. This is regardless of using smart or auto indent.

**Comment by Shougo** [comment]
I think it is Vim's backspace option feature.

```
							*'backspace'* *'bs'*
'backspace' 'bs'	string	(default "")
			global
			{not in Vi}
	Influences the working of <BS>, <Del>, CTRL-W and CTRL-U in Insert
	mode.  This is a list of items, separated by commas.  Each item allows
	a way to backspace over something:
	value	effect	~
	indent	allow backspacing over autoindent
	eol	allow backspacing over line breaks (join lines)
	start	allow backspacing over the start of insert; CTRL-W and CTRL-U
		stop once at the start of insert.

	When the value is empty, Vi compatible backspacing is used.

	For backwards compatibility with version 5.4 and earlier:
	value	effect	~
	  0	same as ":set backspace=" (Vi compatible)
	  1	same as ":set backspace=indent,eol"
	  2	same as ":set backspace=indent,eol,start"

	See |:fixdel| if your <BS> or <Del> key does not do what you want.
	NOTE: This option is set to "" when 'compatible' is set.
```

You should set backspace option like this:

```vim
set backspace=indent,eol,start
```

**Comment by matze** [comment]
> When the value is empty, Vi compatible backspacing is used.

Thanks, that did indeed the trick. Now it worries me, that Vim itself was not working as documented. I didn't had the option set yet Vim was happily backspacing over indents. But anyway, thanks again for the quick reply.

**Comment by ntnn** [comment]
@matze Vim itself is most likely working as documented. Check your systemwide vimrc (on red hat under `/etc/vimrc`, debian probably `/usr/share/vim/vimrc`).

**Comment by matze** [comment]
> @matze Vim itself is most likely working as documented. Check your systemwide
> vimrc (on red hat under /etc/vimrc, debian probably /usr/share/vim/vimrc).

Indeed, Debian sources debian.vim which sets
`backspace=indent,eol,start`. Thanks guys, for the enlightenment ;-)
