### ISSUE TITLE
Using `nvim_echo` inside `VimResized` autocommand can lead to invisible hit-enter prompt

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#26139]
### Problem

When `nvim_echo` is being called directly inside `VimResized` autocommand, it can lead to not updating screen until some forced redraw happens. **But** only after reducing height of terminal emulator.

### Steps to reproduce

1. `nvim --clean`
2. Create the following autocommand: `au VimResized * lua vim.api.nvim_echo({ { vim.fn.strftime('%Y-%m-%d %H:%M:%S') } }, true, {})`.
3. Reduce height of terminal window (even by 1). Screen is not redrawn.
4. Change width and/or height of terminal emulator in any way. Screen is not redrawn.
5. Press `<Esc>`. Screen is redrawn.
6. Type `:messages` to see that all `VimResized` were triggered properly and `nvim_echo` was properly called multiple times.

### Expected behavior

Screen is always redrawn after any change of terminal emulator window dimensions.

------

This does not happen if `nvim_echo()` is wrapped in `vim.schedule()`. So with this everything works as expected: `au VimResized * lua vim.schedule(function() vim.api.nvim_echo({ { vim.fn.strftime('%Y-%m-%d %H:%M:%S') } }, true, {}) end)`.

This also does not happen if not reducing terminal window height. But message is still not shown after every `VimResized`.

------

I've bisected it to #25470: it doesn't work on a9a48d6b5f00241e16e7131c997f0117bc5e9047, but does work on 08aea256c8330f482319b0579944a56707cc5bbe. (@bfredl)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1614+ge89071522

### Vim (not Nvim) behaves the same?

No

### Operating system/version

EndeavourOS Linux x86_64 (6.6.1-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

From source

**Comment by zeertzjq** [comment]
This message seems to cause an invisible hit-enter prompt.

**Comment by echasnovski** [comment]
Thanks, Zeer!
