### ISSUE TITLE
Unittests doesn't work on arm mac

### ISSUE THREAD

**Issue by dundargoc** [neovim/neovim#26145]
Get the following output for basically every `it`:

```
RUN       vim_to_object converts true: 16.00 ms ERR
test/unit/helpers.lua:750: test/unit/helpers.lua:734: (string) '
test/unit/helpers.lua:266: '<identifier>' expected near ':' at line 671'
exit code: 256

stack traceback:
        test/unit/helpers.lua:750: in function 'itp_parent'
        test/unit/helpers.lua:786: in function <test/unit/helpers.lua:776>
```

**Comment by Joaomantovani32** [comment]
Hello! I'm working on this issue

**Comment by clason** [comment]
No licking the cookie, just make a PR!

**Comment by jgouly** [comment]
This is a LuaJIT parsing issue https://github.com/LuaJIT/LuaJIT/issues/951, below is a very hacky work around.

After that, all the unittests are passing.

The best fix would be to support it properly in LuaJIT, I'm not sure of the best way to work around it in neovim.

```
diff --git a/test/unit/testutil.lua b/test/unit/testutil.lua                                                                                                                          
index c90859581..de8bb2f31 100644                                                                                                                                                     
--- a/test/unit/testutil.lua                                                                                                                                                          
+++ b/test/unit/testutil.lua                                                                                                                                                          
@@ -265,6 +265,14 @@ local function _cimportstr(preprocess_cache, path)                                                                                                               
   if body == '' then                                                                                                                                                                 
     return lib                                                                                                                                                                       
   end                                                                                                                                                                                
+  body = body:gsub('typedef enum : uint32_t', 'typedef enum')                                                                                                                        
+  body = body:gsub('typedef enum : uint64_t', 'typedef enum')                                                                                                                        
+  body = body:gsub('typedef enum : uint16_t', 'typedef enum')                                                                                                                        
+  body = body:gsub('mach_vm_range_flags_t flags: 48; mach_vm_range_tag_t range_tag : 8; uint8_t vm_tag : 8; struct mach_vm_range range;', 'mach_vm_range_flags_t flags; mach_vm_range
_tag_t range_tag; uint8_t vm_tag; struct mach_vm_range range;') 
```

**Comment by lewis6991** [comment]
Cool. Want to raise a PR to add that patch as a temporary workaround?

**Comment by jgouly** [comment]
I could, it felt too horrible to use as a hack even, was hoping someone might have some better ideas. A PR could work as a place to try figure out alternatives though.

**Comment by lewis6991** [comment]
A nasty, but small, hack is much better than unittests not working IMO. This also affects all macos builds going forward since x86 is being phased out.

@dundargoc what do you think of the workaround?

**Comment by jgouly** [comment]
Another alternative I tried was to define `_MACH_VM_TYPES_H_` but I think that lead to just a different error later since another header needed one of the types.

It's kinda crazy this low-level of a header is pulled in.

**Comment by lewis6991** [comment]
Where is it being pulled in? Can we avoid it if it isn't strictly needed?

**Comment by dundargoc** [comment]
Yes, PR welcome. This is not any hackier than what we're already doing in unittest, which is straight up ignoring anything we can't parse: https://github.com/neovim/neovim/blob/master/test/unit/testutil.lua#L130-L156

As an example, adding `or string.find(line, 'typedef enum : uint32_t')` instead of `body = body:gsub('typedef enum : uint32_t', 'typedef enum')` works as well. This didn't work for uint64_t for some reason, but my point is that skipping unparsable sections isn't any less hacky than changing the code to be parseable.

Please make a PR :).

**Comment by jgouly** [comment]
@lewis6991 I think through `stdbool.h` but that's just a guess, would be hard to figure out I think.

@dundargoc thanks, I didn't see that bit of code, feel a bit better with my hack now!
