### ISSUE TITLE
`pos` option in `vim.diagnostic.open_float` does not work

### ISSUE THREAD

**Issue by mystilleef** [neovim/neovim#26153]
### Problem

```lua
vim.diagnostic.open_float({scope="c", focus=false, pos={0,0})
```

Assuming there are diagnostic issues in a file, the code above should open the diagnostic floating window at the top leftmost corner of the nvim window.

Unfortunately, this does not work. The diagnostic window does not open at all.

### Steps to reproduce

1. `nvim --clean -u my_issue.lua`
2. `:e foo.lua`
3. edit the file to make a syntax error
4. call `:lua vim.diagnostic.open_float({scope="l", focus=false, pos={0,0}})`

[nviminimal.zip](https://github.com/neovim/neovim/files/13439517/nviminimal.zip)

### Expected behavior

When the `pos` option is present, I expect the diagnostic window to be placed at the row and column specified by the `pos` option

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1588+gdc9f7b814

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Fedora Linux

### Terminal name/version

kitty 0.31

### $TERM environment variable

screen-256color

### Installation

build from repo

**Comment by Sam-programs** [comment]
pos is the position to get the diagnostics from, not the window placement position.
`vim.diagnostics.open_float` returns the window number u can move it from there.
```lua
local _,winnr = vim.diagnostic.open_float()
local config = vim.api.nvim_win_get_config(winnr)
config = vim.tbl_extend('force',config,{
   relative = 'win',
   win = vim.api.nvim_get_current_win(),
   row = 0,
   col = 0,
})
vim.api.nvim_win_set_config(winnr,config)
```
see `:help nvim_open_win` if u want to add more options.

i hope this is the intended purpose of returning the window number.

**Comment by mystilleef** [comment]
@Sam-programs Thank you! That worked! 

Closing this issue.
