### ISSUE TITLE
Nightly regression: neovim returns negative cursor pos to UI

### ISSUE THREAD

**Issue by fredizzimo** [neovim/neovim#26150]
### Problem

This was originally reported here, so see that for the full context
* https://github.com/neovide/neovide/issues/2140

Loading session files can cause Neovim to send a `grid_cursor_goto` event with negative coordinates like -57, 19 in the log given. This only happens with Neovim nightly and not with Neovim 0.9.4.  The terminal mode Neovim is also fine

Note, I did quickly try to create a failing test, but it was harder than I though because apparently it requires the window layout to be changed while the cursor is at the command line, which does not happen when running `helpers.source`.

### Steps to reproduce

1. Create a .vim file containing the following minimised script:
```vim
set shortmess=A
tabnew +setlocal\ bufhidden=wipe
resize 1
tabnext
edit newfile.txt
```
2. Run neovide --multigrid -- --clean
3. `:so` the script

### Expected behavior

Neovim should send valid coordinates

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1623+g8c6b0a5f2, Neovide 0.11.2

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

Alacritty/Neovide

### $TERM environment variable

alacritty

### Installation

Manually built

**Comment by fredizzimo** [comment]
There's a similar issue here https://github.com/neovim/neovim/issues/24988, but that also affects 0.9.4, but involves the cursor being at the command line.

**Comment by fredizzimo** [comment]
It looks like this commit broke it a9a48d6b5f00241e16e7131c997f0117bc5e9047

**Comment by zeertzjq** [comment]
This seems to be also reproducible if the `resize 1` is changed to `let &cmdheight = &lines - 3`. Not sure how it worked before.

**Comment by zeertzjq** [comment]
Hmm, the message is misplaced in Vim as well, but in Vim it disappears immediately and there is no UI event.

**Comment by zeertzjq** [comment]
Created an issue https://github.com/vim/vim/issues/13560
