### ISSUE TITLE
mkview not working with autocmd

### ISSUE THREAD

**Issue by karmicdude** [neovim/neovim#26157]
### Problem

I'm trying to implement autosave folds on buffer write or buffer leave

```lua
...
M.autocmd_group = function(name)
	return vim.api.nvim_create_augroup("user_" .. name, { clear = true })
end

...

vim.api.nvim_create_autocmd({ "BufWritePre" }, {
	desc = "Save folds",
        group = utils.autocmd_group("save_view"),
        pattern = "*",
	callback = function()
		vim.cmd("mkview 1")
	end,
})

vim.api.nvim_create_autocmd({ "BufWinEnter" }, {
        desc = "Restore folds",
        group = utils.autocmd_group("save_view"),
	pattern = "?*",
	callback = function()
		vim.cmd("silent! loadview 1")
	end,
})
```

But nothing happens - view file is not created. But if I manually execute cmd `:mkview 1` file successfully created in path `$HOME/.local/state/nvim/view/<long name>.1.vim`
At first I thought that I didn't set the event correctly (initially it was `BufWinLeave`) or autocmd itself just doesn't work at all. I check this by changing the command to `!touch /tmp/testfile`.
And when writing the buffer, the file is created. So the problem is not in this case. 
There are no error messages.
I read through the documentation and found that I was missing `$XDG_STATE_HOME` in the environment variables (I'm on macOS), I decided to set it via an environment variable.
While before `nvim --clean --headless --cmd 'echo $XDG_STATE_HOME|q'` didn't output anything, now it produces the path `$HOME/.local/state`.
But that doesn't work either and I don't think that's the problem. 
I also try to set custom `vim.opt.viewdir`, but didn't get any results either.

If I save view manually, the second autocmd with `loadview` works.

### Steps to reproduce

fold some blocks,
write buffer

### Expected behavior

`autocmd` with `mkview` command write `.vim` restore view file in filesystem.

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

did't test in vimL implementation

### Operating system/version

macOS 14.1.1

### Terminal name/version

kitty v0.31.0

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by zeertzjq** [comment]
Remove `clear = true`

**Comment by karmicdude** [comment]
@zeertzjq I already tried that - it still doesn't work.

**Comment by zeertzjq** [comment]
Oops, actually you need to change `clear = true` to `clear = false`.
