### ISSUE TITLE
signs with `numhl` are no longer rendered with `signcolumn=no`

### ISSUE THREAD

**Issue by lewis6991** [neovim/neovim#26164]
### Problem

See title

### Steps to reproduce

```lua
vim.o.number = true
vim.o.signcolumn = 'no'
vim.cmd.normal('o')

vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace('test'), 0, 0, {
  number_hl_group = 'Error'
})

vim.fn.sign_define('foo', { text = 'F', numhl = 'Error' })
vim.fn.sign_place(0, '', 'foo', vim.api.nvim_get_current_buf(), { lnum = 2 })
```

`nvim --clean -u min.lua`

### Expected behavior

Signs with `numhl` are always rendered regardless of `signcolumn`.

### Neovim version (nvim -v)

 v0.10.0-dev-879617c

---

Note: this was found via [Gitsigns's CI](https://github.com/lewis6991/gitsigns.nvim/actions/runs/6968414545/job/18962249567?pr=917). It might be a good idea to sanity future sign related PR's with this.

**Comment by luukvbaal** [comment]
Might have already been resolved here? https://github.com/neovim/neovim/commit/585eeacb24e1aa0fed978e46063de100b16b8bdf#diff-6e7593afe2030cd8628b9a5a900e49accd4a9d7f3ff4b73ee022f06b4bd0f237R446

**Comment by lewis6991** [comment]
No `v0.10.0-dev-879617c` already includes that.

**Comment by luukvbaal** [comment]
Then the repro is insufficient? I don't see `numhl` being applied on HEAD.

**Comment by lewis6991** [comment]
Huh, that means the repro is sufficient if you don't see `numhl` being applied.

**Comment by luukvbaal** [comment]
Oh oops.

**Comment by luukvbaal** [comment]
Then we just need to revert https://github.com/neovim/neovim/commit/585eeacb24e1aa0fed978e46063de100b16b8bdf#diff-6e7593afe2030cd8628b9a5a900e49accd4a9d7f3ff4b73ee022f06b4bd0f237R446.
