### ISSUE TITLE
st terminal on nightly 

### ISSUE THREAD

**Issue by monkoose** [neovim/neovim#26179]
### Problem

`nvim --clean` or `nvim -u NONE` on nightly on startup end in commandline with such character sequence `1111/0e0e/0d0d`

Tested on some other terminal emulators, but can't reproduce it. Doesn't happen on stable neovim version either.

### Steps to reproduce

nvim --clean

### Expected behavior

Expect normal behavior.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1634+g4ce3159e24

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ArchLinux

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

AUR neovim-git

**Comment by zeertzjq** [comment]
AUR build is not supported.

**Comment by monkoose** [comment]
> HEAD build with external dependencies is not supported.

Have you time to explain what does this mean.

**Comment by zeertzjq** [comment]
Using `neovim-nightly-bin` should work, for now. `neovim-git` will work after some libtermkey version updates.

**Comment by monkoose** [comment]
`neovim-nightly-bin` works as expected. Thanks for the help.
