### ISSUE TITLE
in visual mode, col(".") returns the start of the visual area

### ISSUE THREAD

**Issue by Big-bros** [neovim/neovim#26191]
### Problem

I try to write a function that process a visual selected block.
![image](https://github.com/neovim/neovim/assets/53227593/b1eed6b9-4abb-467a-87f0-ae9695b197f7)

I write my script in python :

`

    command! -range=% CsvRightAlignNumbers python CsvRightAlignNumbers(<f-line1>,<f-line2>)

    python << EOS
    def CsvRightAlignNumbers(line1, line2):
        import os, os.path, vim
        x1 = int(vim.eval('col(".")'))
        x2 = int(vim.eval('col("v")'))
        y1 = int(line1)
        y2 = int(line2)
        print(f"({x1}, {y1}) ({x2}, {y2})")
    EOS
`
When I call this commant, i have the following result :
![image](https://github.com/neovim/neovim/assets/53227593/ab182d56-ff97-43f1-9e16-437cd57b5042)

col(".") = col("v") = start of the visual block.
The help for col() says : 
		    v       In Visual mode: the start of the Visual area (the cursor is the end).  When not in Visual mode

When I write this in vimscript, it is even worse (??)

`

    command! -range=% CsvRightAlignNumbersTest <line1>,<line2>call s:CsvRightAlignNumbersTest()

    function! s:CsvRightAlignNumbersTest() range
        echo col('.')
        echo col('v')
        echo col('$')
    endfunction
`

result : 
![image](https://github.com/neovim/neovim/assets/53227593/73c17288-7aec-45ca-89f3-8d208a128b72)
There, it's not even the column of the start or end of the visual block. It's 1.

### Steps to reproduce

copy paste the code in an .vim file in the plugin dir
Open vim
open a file in vim
visually select a block (the result is the same with <C-q>v or a simple v select)
execute the commands

CODE :
`

    command! -range=% CsvRightAlignNumbers python CsvRightAlignNumbers(<f-line1>,<f-line2>)
    command! -range=% CsvRightAlignNumbersTest <line1>,<line2>call s:CsvRightAlignNumbersTest()

    function! s:CsvRightAlignNumbersTest() range
        echo col('.')
        echo col('v')
        echo col('$')
    endfunction

    python << EOS
    def CsvRightAlignNumbers(line1, line2):
        import os, os.path, vim
        x1 = int(vim.eval('col(".")'))
        x2 = int(vim.eval('col("v")'))
        y1 = int(line1)
        y2 = int(line2)
        print(f"({x1}, {y1}) ({x2}, {y2})")
    EOS

`

### Expected behavior

I'd like the col(".") to act as mentionned in the help doc and return the column of the cursor (end of visual bloc)

### Neovim version (nvim -v)

0.8.1 (Build type: RelWithDebInfo)

### Vim (not Nvim) behaves the same?

I don't know (i can't install it, since V8, vim is detected as a virus on my machine)

### Operating system/version

Windows 10

### Terminal name/version

cmd

### $TERM environment variable

vtpcon

### Installation

From the .msi file

**Comment by zeertzjq** [comment]
You need to use `col("'<")` and `col("'>")`, because Visual mode has already ended when you execute the command.

**Comment by Big-bros** [comment]
Oups... Thanks for your answer. I've learned something new (did't think to use the command line notation in my scripts...)
