### ISSUE TITLE
Load `.vimrc` when `'exrc'` is enabled

### ISSUE THREAD

**Issue by ArtAndreev** [neovim/neovim#26197]
### Problem

Currently `'exrc'` enables loading of `.nvim.lua`, `.nvimrc` (nvim-way) and `.exrc` (from vi) files, but not `.vimrc` (vim-way).

### Expected behavior

Enabling loading of `.vimrc` would improve compatibility with origin `'exrc'` and allow using the same file.

From `:h 'exrc'` in vim:
> Enables the reading of .vimrc, .exrc and .gvimrc in the current directory.

From `:h 'exrc'` in neovim:
> Automatically execute .nvim.lua, .nvimrc, and .exrc files in the current directory

**Comment by gpanders** [comment]
What about the opposite use case, where someone makes a .vimrc that’s meant to only be used for Vim?

There are two ways to solve this right now, with no changes required:

1. Use `.exrc` instead of `.vimrc`
2. Create `.nvimrc` with a single line: `source .vimrc`

**Comment by ArtAndreev** [comment]
Seems like `if has('nvim')` should be used, like in regular vimrc.

**Comment by clason** [comment]
Remember that Neovim doesn't source your `.vimrc` and uses its own `init.vim`, so why should a project config (which is much more important to be surprise-free) be different? Just link `.nvimrc` to `.vimrc`, same as for `init.vim`.

**Comment by gpanders** [comment]
> Seems like `if !has('nvim')` should be used, like in regular vimrc.

But if a project wishes to include a `.vimrc` file that is meant to be used _specifically_ for Vim, the onus should not be on them to guard against Neovim also including that file.

The argument against this is the exact same as not using `~/.vimrc` as the main Nvim configuration file in the first place (as @clason mentioned).

Thank you for taking the time to put together an issue, but given there are perfectly viable alternatives I'm going to close this as a "won't fix".

**Comment by ArtAndreev** [comment]
Okay, just wanted some transition for rc-files: vi -> vim -> nvim.

**Comment by ArtAndreev** [comment]
Thank you for your time too!
