### ISSUE TITLE
treesitter - error on bufload in _create_parser if swapfile of buffer exists

### ISSUE THREAD

**Issue by sheimer** [neovim/neovim#26192]
### Problem

opening a file in nvim with a treesitter parser enabled leads to error, if a swapfile exists.

First message:

```
Auslagerungsdatei mit folgendem Namen gefunden: "~/.local/state/nvim/swap//%opt%homebrew%Cellar%neovim%0.9.4%share%nvim%runtime%lua%vim%treesitter.lua.swp"
      Eigentum von: shoffmann     vom: Fr Nov 24 09:31:41 2023
         Dateiname: /opt/homebrew/Cellar/neovim/0.9.4/share/nvim/runtime/lua/vim/treesitter.lua
         verändert: nein
     Benutzer-Name: shoffmann   Host-Name: Poteen.local
        Prozess-ID: 2412 (STILL RUNNING)
Beim Öffnen der Datei "treesitter.lua"
               vom: Fr Nov 24 09:31:36 2023
```

Second message:

```
Failed to source `/Users/shoffmann/.config/nvim/after/plugin/treesitter.rc.lua`

vim/_editor.lua:0: /Users/shoffmann/Projects/github/dotfiles/.config/nvim/init.lua..nvim_exec2() called at /Users/shoffmann/Projects/github/dotfiles/.config/nvim/init.lua:0../Users/shoffmann/Projects/github/dotfiles/.config/nvim/after/plugin/treesitter.rc.lua: Vim(source):E5113: Error while calling lua chunk: Vim:E325: ACHTUNG
stack traceback:
^I[C]: in function 'bufload'
^I...r/neovim/0.9.4/share/nvim/runtime/lua/vim/treesitter.lua:59: in function '_create_parser'
^I...r/neovim/0.9.4/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
^I...r/neovim/0.9.4/share/nvim/runtime/lua/vim/treesitter.lua:459: in function 'start'
^I...m/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
^I...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
^I...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:118: in function 'enable_module'
^I...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:155: in function 'enable_all'
^I...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:438: in function 'accumulator'
^I...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:246: in function 'recurse_modules'
^I...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:435: in function 'setup'
^I...
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:481: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:480>
^I[C]: in function 'xpcall'
^I.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:480: in function 'source'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:439: in function 'source_runtime'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:140: in function 'startup'
^I...fmann/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:110: in function 'setup'
^I/Users/shoffmann/.config/nvim/lua/plugins.lua:14: in main chunk
^I[C]: in function 'require'
^I...shoffmann/Projects/github/dotfiles/.config/nvim/init.lua:30: in main chunk

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - ~/.config/nvim/lua/plugins.lua:14
  - ~/Projects/github/dotfiles/.config/nvim/init.lua:30
```

The file can then be edited, and treesitter has parsed the file anyway

The same problem occurs if using nvim nightly NVIM v0.10.0-dev-53cc835

### Steps to reproduce

- install and configure nvim-treesitter
- open a file with treesitter support enabled
- open the same file in another nvim instance

### Expected behavior

the second message `...in function 'bufload'...` should not appear

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

not tested, treesitter support missing in vim

### Operating system/version

macOS 13.5.2

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by clason** [comment]
Does this happen _without_ `nvim-treesitter`, just `vim.treesitter.start()` in a FileType autocommand?

**Comment by clason** [comment]
This was added in #12603. I think a better solution would _not_ to force loading of the buffer and check `bufloaded` and bail if `false`.

**Comment by sheimer** [comment]
> Does this happen _without_ `nvim-treesitter`, just `vim.treesitter.start()` in a FileType autocommand?

No, it does not.

With nvim-treesitter, only if highlight = { enabled = true } is set it happens.

> I think a better solution would not to force loading of the buffer and check bufloaded and bail if false.

Possible. Either way, with my solution as well, highlights are not applied. Only non-treesitter highlights.

To try and load the buffer if not already loaded might be a good thing...and now that i think about it, the error message I reported as a bug is not bad as well. After some more testing I realized that treesitter highlighting is not really applied with my "fix", just default highlighting.

Maybe this is not really a problem of _create_parser, and best would be to figure out, why an existing swap file leads to bufload error...

**Comment by clason** [comment]
> No, it does not.

Then it is not a Neovim issue. (And it won't be an nvim-treesitter issue, either, once the 1.0 rewrite becomes the default branch, which drops the hard-to-maintain modules.)

**Comment by clason** [comment]
(But thanks for bringing this up; this is good to keep in mind.)

**Comment by sheimer** [comment]
> > No, it does not.
> 
> Then it is not a Neovim issue. (And it won't be an nvim-treesitter issue, either, once the 1.0 rewrite becomes the default branch, which drops the hard-to-maintain modules.)

you mean 1.0 of nvim-treesitter, and i dont understand what drops could help,
or 1.0 of neovim, and there wont be treesitter highlighting anyomore?

**Comment by clason** [comment]
> you mean 1.0 of nvim-treesitter

Yes. This will not try to control highlighting but leave it to Neovim's builtin functionality. `vim.treesitter.start()` will be the (only) official way of enabling highlighting.

**Comment by sheimer** [comment]
I see, thank you very much :)

Slowly I start figuring out what does what, and what is needed for me to get the highlights i want ^^

**Comment by sheimer** [comment]
if someone stumbles upon this:

I disabled highlight in `require("nvim-treesitter.configs").setup({...})`
and used an autocommand to enable:
```
-- not using "highlight" in config but autocommand to prevent error on loading files which have a vim swap file
vim.api.nvim_create_autocmd('BufReadPost', {
  group = vim.api.nvim_create_augroup('treesitter', {}),
  callback = function(ev)
    local max_filesize = 100 * 1024 -- 100 KB
    local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(ev.buf))
    if ok and stats and stats.size > max_filesize then
      return true
    end
    vim.treesitter.start(ev.buf)
  end,
})
```

Now everything works fine for me :)

**Comment by clason** [comment]
It's better to do that on a `FileType` autocommand; then you can skip certain languages.

**Comment by sheimer** [comment]
thank you!

so new version:

```
vim.api.nvim_create_autocmd('FileType', {
  group = vim.api.nvim_create_augroup('treesitter', {}),
  callback = function(ev)
    local parsers = require("nvim-treesitter.parsers")
    local lang = parsers.ft_to_lang(ev.match)

    if not parsers.has_parser(lang) then
      return true
    end

    local max_filesize = 100 * 1024 -- 100 KB
    local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(ev.buf))

    if ok and stats and stats.size > max_filesize then
      return true
    end

    vim.treesitter.start(ev.buf)
  end,
})
```

**Comment by clarkwang** [comment]
> thank you!
> 
> so new version:
> 
> ```
> vim.api.nvim_create_autocmd('FileType', {
>   group = vim.api.nvim_create_augroup('treesitter', {}),
>   callback = function(ev)
>     local parsers = require("nvim-treesitter.parsers")
>     local lang = parsers.ft_to_lang(ev.match)
> 
>     if not parsers.has_parser(lang) then
>       return true
>     end
> 
>     local max_filesize = 100 * 1024 -- 100 KB
>     local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(ev.buf))
> 
>     if ok and stats and stats.size > max_filesize then
>       return true
>     end
> 
>     vim.treesitter.start(ev.buf)
>   end,
> })
> ```

This does not always work for me. The behavior is quite depending on the order I open files.  I added `echohl` to the above lua code for debugging:

~~~
vim.api.nvim_create_autocmd('FileType', {
    group = vim.api.nvim_create_augroup('treesitter', {}),
    callback = function(ev)
        local parsers = require("nvim-treesitter.parsers")
        local lang = parsers.ft_to_lang(ev.match)

        vim.cmd(string.format([[echohl WarningMsg | echo "lang: %s" | echohl None]], lang) )

        if not parsers.has_parser(lang) then
            vim.cmd(string.format([[echohl WarningMsg | echo "has_parser(%s) returned false" | echohl None]], lang) )
            return true
        end

        local max_filesize = 10 * 1024 * 1024 -- 10 MB
        local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(ev.buf))

        if ok and stats and stats.size > max_filesize then
            return true
        end

        vim.treesitter.start(ev.buf)
    end,
})
~~~

And in treesitter conf `ensure_installed` includes `bash` and `lua`.

Follow the exact steps to reproduce (2 scenarios) --

First, ceate 2 tmp files under `/tmp/`:

~~~
$ cd /tmp
$ cat foo.tmpl
#!/usr/bin/env bash
# vi:set ft=sh:

function main()
{
    echo hello world
}

main
$ cat foo.lua
local BOOL_0, BOOL_1 = false, true
~~~

Then

~~~
$ cd /tmp/
$ nvim  # without any params
~~~

Next, open `foo.tmpl` with `:e foo.tmpl`.  And nvim will show messages:

~~~
lang: template
has_parser(template) returned false
Press ENTER or type command to continue
~~~

As we can see it does not work though at this time `:set filetype`  would output `filetype=sh`.

Next, open `foo.lua` with `:e foo.lua`.  Here it's weird it even does not output the `lang: lua` line which indicates the autocmd is not invoked at all. But if you directly `nvim foo.lua` it'll work fine.

Any idea how to make it work for the above 2 scenaiors?

**Comment by sheimer** [comment]
Sorry for the late answer!

I could reproduce your scenario, and found the problem. I returned "true" on the two early exits, and even if I dont know why, after retruning true the autocmd is not executed anymore. With simple return like below it works, even for your tmpl-shell file. In that case the autocmd is running twice, once for language "template" and a second time for "bash", when the vim cmd ft=sh is executed in your tmpl.

```
      vim.api.nvim_create_autocmd('FileType', {
        group = vim.api.nvim_create_augroup('treesitter', {}),
        callback = function(ev)
          local lang = parsers.ft_to_lang(ev.match)

          if not parsers.has_parser(lang) then
            return
          end

          local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(ev.buf))

          if ok and stats and stats.size > max_filesize then
            return
          end

          vim.treesitter.start(ev.buf)
        end,
      })
```

**Comment by clarkwang** [comment]
> Sorry for the late answer!
> 
> I could reproduce your scenario, and found the problem. I returned "true" on the two early exits, and even if I dont know why, after retruning true the autocmd is not executed anymore. With simple return like below it works, even for your tmpl-shell file. In that case the autocmd is running twice, once for language "template" and a second time for "bash", when the vim cmd ft=sh is executed in your tmpl.

Cool this works. Thanks a lot!

**Comment by clarkwang** [comment]
> I could reproduce your scenario, and found the problem. I returned "true" on the two early exits, and even if I dont know why, after retruning true the autocmd is not executed anymore.

Just found this in `:h nvim_create_autocmd()`:

> * callback (function|string) optional:
>
>   Lua function (or Vimscript function name, if string) called when the event(s) is triggered. **Lua callback can return true to delete the autocommand,** [..]
