### ISSUE TITLE
no smart indent on tsx files

### ISSUE THREAD

**Issue by mrdomino** [neovim/neovim#26202]
### Problem

When I edit a .tsx file, brackets do not change indentation level. This appears to be because there is no `indent/typescriptreact.vim` file, and `*.tsx` has its filetype set to `typescriptreact`.

There is a `syntax/typescriptreact.vim`, and creating a `indent/typescriptreact.vim` with the following contents appears to resolve the issue:

```vim
runtime! indent/typescript.vim
```

### Steps to reproduce

nvim --clean
:edit foo.tsx
i{<Esc>o

### Expected behavior

New line is indented

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

macOS 14.0

### Terminal name/version

iTerm2 3.4.22

### $TERM environment variable

xterm-256color

### Installation

bob

**Comment by clason** [comment]
Please report that to Vim, where these files are maintained. Any fixes will be ported to Neovim as a matter of course.
