### ISSUE TITLE
Formatting resets some changes

### ISSUE THREAD

**Issue by dominicmeyer** [neovim/neovim#26218]
### Problem

On some files, neovim seems to get 'stuck' on some values and when doing `vim.lsp.buf.format({ async = false })` the changes get undone.

The above is an example from my current vue project. The content after using the command is the previous content of those fields.

Before using the command (pay attention to the `@click` actions):

```vue
<template>
	<div class="d-flex align-center justify-center pa-4">
		<v-btn :disabled="page === 1" icon="mdi-arrow-left" density="comfortable" variant="tonal" rounded
			@click="emit('prevPage')"></v-btn>

		<div class="mx-2 text-caption">
			Page {{ page }} of {{ pageCount }}
		</div>

		<v-btn :disabled="page >= pageCount" icon="mdi-arrow-right" density="comfortable" variant="tonal" rounded
			@click="emit('nextPage')"></v-btn>
	</div>
</template>

<script setup lang="ts">
import { defineProps } from 'vue';

defineEmits(["nextPage", "prevPage"])

defineProps({
  page: {
	  type: Number,
		required: true
	},
  pageCount: {
	  type: Number,
		required: true
	},
  nextPage: {
		type: Function,
		required: true
	},
  prevPage: {
		type: Function,
		required: true
	}
})
</script>
```

After using the command:

```vue
<template>
	<div class="d-flex align-center justify-center pa-4">
		<v-btn :disabled="page === 1" icon="mdi-arrow-left" density="comfortable" variant="tonal" rounded
			@click="prevPage"></v-btn>

		<div class="mx-2 text-caption">
			Page {{ page }} of {{ pageCount }}
		</div>

		<v-btn :disabled="page >= pageCount" icon="mdi-arrow-right" density="comfortable" variant="tonal" rounded
			@click="nextPage"></v-btn>
	</div>
</template>

<script setup lang="ts">
import { defineProps } from 'vue';

defineEmits(["nextPage", "prevPage"])

defineProps({
  page: {
	  type: Number,
		required: true
	},
  pageCount: {
	  type: Number,
		required: true
	},
  nextPage: {
		type: Function,
		required: true
	},
  prevPage: {
		type: Function,
		required: true
	}
})
</script>
```

### Steps to reproduce

Still unknown, seems the happening random.

### Expected behavior

Refactoring not changing the codes content like this

### Neovim version (nvim -v)

0.9.2

### Vim (not Nvim) behaves the same?

unknown

### Operating system/version

macOS 14.1.1

### Terminal name/version

iTerm2 3.4.22

### $TERM environment variable

xterm-256color

### Installation

from github release

**Comment by justinmk** [comment]
a diff would be helpul. here:

![image](https://github.com/neovim/neovim/assets/1359421/e1becf55-8089-4c31-8886-f81bc35170ae)


Neovim obviously isn't doing this, so report it to your lsp server, or plugins or whatever.

no steps to reproduce so closing
