### ISSUE TITLE
vim.treesitter.foldexpr: fold start/end are not always calculated correctly after edits

### ISSUE THREAD

**Issue by vurentjie** [neovim/neovim#26224]
### Problem

After making changes to a file, the start/end lines of the folds are not always correct.  I have attached a screencast demonstrating different cases that I could observe: 

(Updated screencast using `nvim --clean`) 

https://github.com/neovim/neovim/assets/639806/fad1f3b8-e1ee-4234-932b-f87f6897437c

### Steps to reproduce

 1. Copy to `~/Downloads/folds.lua`:
 ```lua 
vim.treesitter.start()

vim.opt.foldlevel = 99
vim.opt.foldlevelstart = 99
vim.opt.foldenable = true 
vim.opt.number = true 
vim.opt.foldcolumn = '1' 
vim.opt.foldmethod = 'expr' 
vim.opt.foldexpr = 'v:lua.vim.treesitter.foldexpr()' 
vim.opt.foldtext = 'v:lua.vim.treesitter.foldtext()'
vim.opt.fillchars = { fold = ' ' }

vim.cmd([[au WinNew,BufWinEnter * exec 'normal! zx'|exec 'normal! zR']])
vim.cmd('normal! zx')
vim.cmd('normal! zR')


function test()
end
```
2.  nvim --clean   
3. e ~/Downloads/folds.lua
4. so % 
5. Watch the recording for different cases

(Updated the above to use `nvim --clean` as per the [comment](https://github.com/neovim/neovim/issues/26224#issuecomment-1826759554))

### Expected behavior

The folds should be correct.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-38e9875

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Linux x86_64 6.2.0-37-generic #38~22.04.1-Ubuntu 

### Terminal name/version

kitty 0.30.0

### $TERM environment variable

xterm-kitty

### Installation

appimage (nightly)

**Comment by clason** [comment]
1. Always test with `nvim --clean`.
2. Do not manually `syntax on` (in general).

**Comment by tomtomjhj** [comment]
Please try #26506

**Comment by vurentjie** [comment]
Thanks for the quick turnaround. The fixes look good. I think you can close the issue once you are satisfied with testing on your end.
