### ISSUE TITLE
UI Attach runs into error

### ISSUE THREAD

**Issue by Huluk** [neovim/neovim#26238]
I'm trying to make an UI attachment in a plugin, but it doesn't seem to work and runs into errors.
I tried various different variations of the code below:

```ruby
Neovim.logger << 'test!'

Neovim.plugin do |plug|
  plug.ui_attach(999, 999, {}) do |*a|
    Neovim.logger << a.inspect
  end
end
```

With and without block argument, with value in the hashmap and entirely without a third argument, but I'm always getting the same error, so I suspect that it's a plugin issue. Otherwise any hints are welcome.

The error appears once I call `:UpdateRemotePlugins` (I'm using https://github.com/junegunn/vim-plug).

## Versions
macOS 14.1.1 Sonoma
Ruby: 3.2.2 (rbenv 1.2.0)
Gem: 3.4.12
Neovim-Ruby: 0.9.1
Neovim: 0.9.4

## Neovim error message
```
function remote#host#UpdateRemotePlugins[6]..<SNR>61_RegistrationCommands[15]..remote#
host#Require[10]..provider#ruby#Require[8]..provider#Poll, line 7
Vim(if):Error invoking 'poll' on channel 5:^@Invalid channel: 5
function remote#host#UpdateRemotePlugins[6]..<SNR>61_RegistrationCommands[15]..remote#
host#Require[10]..provider#ruby#Require[8]..provider#Poll, line 17
Failed to load ruby host. You can try to see what happened by starting nvim with $NVIM
_RUBY_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
remote/host: generated rplugin manifest: /Users/huluk/.local/share/nvim/rplugin.vim
```

## Error logs
```
# Logfile created on 2023-11-25 17:07:28 +0100 by logger.rb/v1.5.3
{"_level":"DEBUG","_time":"2023-11-25T17:07:28.708601","_class":"Neovim::EventLoop","_method":"run","exception":"EOFError","message":"end of file reached"}
{"_level":"DEBUG","_time":"2023-11-25T17:07:28.720948","_class":"Neovim::EventLoop","_method":"run","exception":"EOFError","message":"end of file reached","backtrace":["/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/connection.rb:47:in `readpartial'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/connection.rb:47:in `read'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/connection.rb:47:in `read'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:109:in `read'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:80:in `block in run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:75:in `loop'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/event_loop.rb:75:in `run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/session.rb:35:in `run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/host.rb:29:in `run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/host.rb:17:in `run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/lib/neovim/host/cli.rb:33:in `run'","/usr/local/var/rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/neovim-0.9.1/exe/neovim-ruby-host:5:in `<top (required)>'","/usr/local/var/rbenv/versions/3.2.2/bin/neovim-ruby-host:25:in `load'","/usr/local/var/rbenv/versions/3.2.2/bin/neovim-ruby-host:25:in `<main>'"]}
test!
```

**Comment by Huluk** [comment]
My plan to listen to `msg_show` (of the `ext_messages` extension) does not work because it messes up TUI.
I assume that's what the documentation means with

> By default Nvim requires all connected UIs to support the same capabilities, thus the active capabilities are the intersection of those requested. UIs may specify [ui-override](https://neovim.io/doc/user/ui.html#ui-override) to invert this behavior (useful for debugging). The "option_set" event announces which capabilities are active.

although it also says

> Future versions of Nvim may add new update kinds and may append new parameters to existing update kinds. Clients must be prepared to ignore such extensions, for forward-compatibility.

So I'm confused whether TUI breaking in this case is the expected behaviour or not. For now, I'll proceed assuming it's expected.

**Comment by justinmk** [comment]
> My plan to listen to `msg_show` (of the `ext_messages` extension) does not work because it messes up TUI.

idk what "messes up" means, but I assume it means that messages don't show. That is because the TUI doesn't handle `ext_messages` (yet).

**Comment by alexgenco** [comment]
```ruby
Neovim.plugin do |plug|
  plug.command(:Start) do |nvim|
    nvim.ui_attach(999, 999, {})
    loop do
      msg = nvim.session.next
      next if msg.method_name != 'redraw'
      # my logic
    end
  end
end
```

This will block the main thread, which is definitely not going to work. Try this

```ruby
Neovim.plugin do |plug|
  plug.command(:Start) do |nvim|
    nvim.ui_attach(999, 999, {})
    Thread.new do
      loop do
        msg = nvim.session.next
        next if msg.method_name != 'redraw'
        # my logic
      end
    end
  end
end
```

Or better yet, just spawn off a  separate ruby process using [`jobstart()`](https://neovim.io/doc/user/builtin.html#jobstart()) instead of the rplugin DSL. I think you can connect a client to stdin/stdout using `Neovim.attach(EventLoop.stdio)`.

**Comment by Huluk** [comment]
> idk what "messes up" means, but I assume it means that messages don't show. That is because the TUI doesn't handle `ext_messages` (yet).

The terminal goes completely black and does not react any more, except for a duplicate status bar. Thanks for clarifying!

> This will block the main thread, which is definitely not going to work

It seems to block the plugin thread only, so the basic example works. But I take your point and will switch to `jobstart()`. With just the `Thread.new`, I get "Channel doesn't exist" when running another command registered with this plugin (and with my code, other commands don't work at all, as one would expect).
