### ISSUE TITLE
typescript-language-server highlighting broken

### ISSUE THREAD

**Issue by paskozdilar** [neovim/neovim#26246]
### Problem

The following code gets wrong syntax highlighting:

```typescript
function example(foo: string, bar: (baz: string, foobar: (foobaz: string, foobarbaz: () => void) => void) => void) {
  console.log('foo 1', foo);
  bar(foo, () => {
    console.log('foo 2', foo);
  });
}

function main() {
   example('foo', (baz: string, foobar: (foobaz: string, foobarbaz: () => void) => void) => {
   foobar(baz, () => {
      console.log('baz', baz);
   });
 });
}
```

In my Neovim (v0.10.0-dev) with typescript-language-server I get the following highlighting:

![image](https://github.com/neovim/neovim/assets/53006174/5e548b90-b3ba-45f9-a0bd-8d11d8cc2fc1)

The arrow function callback on the line 10 is not highlighted properly. In contrast, the arrow function callback on line 3 is highlighted properly.

The issue also exists in vanilla Neovim without LSP:

![image](https://github.com/neovim/neovim/assets/53006174/b8a4a033-5b59-43e6-9cf9-ce659ce4cc0c)

However, that is sort-of expected, since Neovim syntax highlighting doesn't do any deeper semantic analysis, which I assume is necessary for correct syntax highlighting in this case.

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
local lspconfig = require('lspconfig')
lspconfig.tsserver.setup {}
```

```typescript
function example(foo: string, bar: (baz: string, foobar: (foobaz: string, foobarbaz: () => void) => void) => void) {
  console.log('foo 1', foo);
  bar(foo, () => {
    console.log('foo 2', foo);
  });
}

function main() {
   example('foo', (baz: string, foobar: (foobaz: string, foobarbaz: () => void) => void) => {
   foobar(baz, () => {
      console.log('baz', baz);
   });
 });
}
```

### Expected behavior

I would expect the highlighting on line 10 to be the same as on line 3.

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Language server name/version

typescript-language-server

### Operating system/version

Linux 5.15.133.1-microsoft-standard-WSL2

**Comment by clason** [comment]
Syntax files are not maintained by Neovim; please contact the maintainer listed at the top of `runtime/syntax/typescript.vim`.

**Comment by paskozdilar** [comment]
Thanks for the quick feedback!

I'll report the issue to the appropriate places.
