### ISSUE TITLE
Allow for easy setup of queries for only `InspectTree` and not all files of filetype `query` 

### ISSUE THREAD

**Issue by Danielkonge** [neovim/neovim#26258]
### Problem

I would like to write queries to highlight `InspectTree` specifically, but I can see that `InspectTree` is of filetype `query` and thus uses the `query` parser. 

I have tried to look through [neovim/runtime/lua/vim/treesitter/dev.lua](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/treesitter/dev.lua) to see if there was anything I could target for setting up my queries. I tried targeting `vim.b.dev_inspect`, but I couldn't get the queries to work as expected. 

If it already possible to easily write queries that will only be checked in `InspectTree`, then I can close this feature request, but I would like to be pointed in the right direction.

If you are open to adding something extra to neovim to make something like this easier, I am also willing to spend some time and implement it myself, but I would first like some guidelines for how you want to implement it, if this is the case.

### Expected behavior

An easy way to do have separate highlighting for files of filetype `query` and highlighting for `InspectTree`. E.g. by something like:
```lua
-- lua code setting up highlights for filetype `query`
if vim.b.is_inspecttree then
  -- my own highlighting
else
  -- standard highlighting
end
```

**Comment by clason** [comment]
#22887

**Comment by Danielkonge** [comment]
> #22887

It seems like the conversation there has stalled? I can work on updating the code if we just want to change the filetype and register the `query` parser correctly (that would easily solve my problem at least). But it seems like that might not be what you want? 

(As an aside: Should I move this conversation to #22887?)

**Comment by clason** [comment]
nah, @gpanders will take care of it when he has time.

**Comment by Danielkonge** [comment]
Okay, I will just close this issue now then, since a solution to #25958 will close this anyways (I just didn't notice that this issue was related to this before opening this one). 

Either way, #22887 should solve this when it is ready. I also wanted this because of `rainbow-delimiters`, where I have a draft setup that can give me highlighting like this to keep track of the indent level:

<img width="340" alt="Screenshot 2023-11-28 at 00 15 28" src="https://github.com/neovim/neovim/assets/7075380/a24e9456-b76e-4c06-b819-c8b00e5fada1">

But this kind of setup doesn't highlight the normal `query` files nicely.
