### ISSUE TITLE
Documentations for `nvim_exec_lua` and `nvim_execute_lua`: the APIs do not exist

### ISSUE THREAD

**Issue by wookayin** [neovim/neovim#26265]
### Problem

The APIs `nvim_exec_lua` and `nvim_execute_lua` do not exist.

```vim
:lua= vim.api.nvim_exec_lua
nil

:lua= vim.api.nvim_execute_lua
nil

:call nvim_exec_lua("print", 1)
E117: Unknown function: nvim_exec_lua

:call nvim_execute_lua("print", 1)
E117: Unknown function: nvim_exec_lua
```

Although documented (`/vim/_meta/api.lua`):

```lua
--- Execute Lua code. Parameters (if any) are available as `...` inside the
--- chunk. The chunk can return a value.
--- Only statements are executed. To evaluate an expression, prefix it with
--- `return`: return my_function(...)
---
--- @param code string Lua code to execute
--- @param args any[] Arguments to the code
--- @return any
function vim.api.nvim_exec_lua(code, args) end

--- @deprecated
--- @param code string
--- @param args any[]
--- @return any
function vim.api.nvim_execute_lua(code, args) end
```

```
nvim_exec_lua({code}, {args})                                *nvim_exec_lua()*
    Execute Lua code. Parameters (if any) are available as `...` inside the
    chunk. The chunk can return a value.
```

Perhaps the only low-level C API is available, or available only through "rpcrequest" (which pynvim uses). Given that one can just use `luaeval` or `:lua` Ex commands this is not a big problem, but at least the documentation doesn't match the runtime behavior.

The function https://github.com/neovim/neovim/blob/master/src/nvim/api/vim.c#L478 is marked as "FUNC_API_REMOTE_ONLY". Therefore, (1) docs should mention that these functions are available through RPC only, and (2) the meta luadoc on `vim.api.nvim_execute_lua` should be removed (but not might be possible because this is the source of auto-docs) or clarified.

Context: I was [debugging `pynvim`'s lua bridge](https://github.com/neovim/pynvim/issues/550) and found that those functions are not available. Currently there seems no way easy to easily execute an arbitrary lua code using python-neovim APIs without string manipulation.

### Steps to reproduce

Straightforward: `nvim --clean` and type the above commands.

### Expected behavior

The low-level API functions should work as documented; or the documentation needs to mention that this won't be exposed as `vim.lua` or vimscript APIs.

### Neovim version (nvim -v)

0.6.3 and above (including 0.10.x-nightly)

(Haven't tested 0.5.x or below)

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 13

### Terminal name/version

xterm

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by wookayin** [comment]
Hmm, sorry, the docs have it clearly documented. The lua docstring part seems to be the only one that is confusing.

```
    Attributes:  
        |RPC| only
```

**Comment by zeertzjq** [comment]
Use `loadstring()` to executing Lua string from Lua.
