### ISSUE TITLE
Case insensitive search with sensitive replace.

### ISSUE THREAD

**Issue by gaoqiangks** [neovim/neovim#26271]
### Problem

I find it's convenient to set case insensitive for searching and case sensitive for replacing.  However, current version of neovim doesn't seem to support this feature.

### Expected behavior

Can you add an option such that we can set  case sensitivity seperately for searching and replacing?

**Comment by justinmk** [comment]
No, unless Vim adds it. But really this should be addressed by a plugin.

**Comment by Sam-programs** [comment]
Maybe something like this would work?
```lua
vim.api.nvim_create_autocmd("CmdlineEnter", {
   pattern = { "/", '?' },
   callback = function()
      vim.o.ignorecase = true
   end
})

vim.api.nvim_create_autocmd("CmdlineEnter", {
   pattern = ':',
   callback = function()
      vim.o.ignorecase = false
   end
})
```
