### ISSUE TITLE
&termencoding is mutable but has no effect

### ISSUE THREAD

**Issue by bfredl** [neovim/neovim#2627]
Broken out from #2469. Right now `&termencoding` can be set but has no effect. Converters `input_conv` and `output_conv` are still constructed but they are not used after #1820 . 

Either the tui code must be prepared to handle `&termencoding != &encoding` (right now the tui input function is called `forward_simple_utf8` but regardless of settings it just forwards bytes) or setting `&termencoding` should be an error. 
There is similar question when using external GUI. in gvim, `&termencoding` is fixed to `utf-8` (and `encoding=utf-8` is "highly recommended"), but right now gui:s of nvim must be prepared to handle `&encoding != utf-8`, but at least `pynvim` don't. I don't know of the others.

**Comment by justinmk** [comment]
The direction we are most likely headed is that `&termencoding` is irrelevant now. I'm pretty sure I asked @tarruda about this around the time of #1820.

> in gvim, &termencoding is fixed to utf-8 (and encoding=utf-8 is "highly recommended"), but right now gui:s of nvim must be prepared to handle &encoding != utf-8, but at least pynvim don't.

Ok, even more reason to head in that direction. Multiple terminals may be connected to a single nvim server, and switching between different encodings on the fly would be insane. Let's remove `'termencoding'`.

**Comment by bfredl** [comment]
> Multiple terminals may be connected to a single nvim server,

Good point :+1:  disabling `&termencoding` it is.

**Comment by bfredl** [comment]
Opened PR #2631, discussion can continue there.
