### ISSUE TITLE
`plugin/osc52.lua` still cannot set `vim.g.clipboard` on tmux under SSH 

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#26288]
### Problem

As in the title, I cannot get `plugin/osc52.lua` working on the remote host inside tmux.
![image](https://github.com/neovim/neovim/assets/11404453/8e0062d5-3873-4a02-8693-40fc83a658fb)

There is no problem if I open nvim in a remote shell without tmux. 
![image](https://github.com/neovim/neovim/assets/11404453/e536cd00-ca16-4069-b961-00d002378d85)

cc @gpanders 

### Steps to reproduce

All on the remote (Debian) host accessed by SSH:

tmux.conf:
```tmux.conf
set-option -g allow-passthrough on
set -g set-clipboard on
set -ga terminal-overrides "screen*:Ms=\\E]52;%p1%s;%p2%s\\007,tmux*:Ms=\\E]52;%p1%s;%p2%s\\007"
```
osc52-tmux.lua (contains manual check because on `UIEnter` was too early to get vim.g.clipboard):
```
local function test()
  vim.print('SSH_TTY: ' .. os.getenv('SSH_TTY'))
  print('clipboard: ' .. vim.inspect(vim.g.clipboard))
  -- vim.cmd([[au TermResponse]])
  vim.print(vim.api.nvim_get_autocmds({event = 'TermResponse'}))
end

vim.api.nvim_create_user_command('Test', test, {})
```

```sh
# without tmux
~/path/to/bin/nvim --clean -u osc52-tmux.lua
# with tmux
tmux kill-server; tmux new-session -- ~/path/to/bin/nvim --clean -u osc52-tmux.lua
```
- run `:Test` inside both nvim instances.

### Expected behavior

 `vim.g.clipboard` is set by plugin on tmux under SSH without need to set it manually. 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1694+gaa9d9cafd

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Debian Sid

### Terminal name/version

tmux 3.3a-5 (on remote host), kitty 0.31.0 (on localhost)

### $TERM environment variable

tmux-256color

### Installation

from repo

**Comment by przepompownia** [comment]
On non-clean nvim:
![image](https://github.com/neovim/neovim/assets/11404453/d228ed1f-81c6-4020-ac91-02c1aa294e0a)

**Comment by przepompownia** [comment]
If I did not any mistake, it looks like
```lua
io.stdout:write('\027Ptmux;\027\027P+q4D73\027\\\027\\') 
```
does not trigger `TermResponse` in effect.

**Comment by gpanders** [comment]
Thanks, I can reproduce this easily in Kitty. All that's needed to reproduce is:

```
kitty --config=NONE
tmux
printf '\ePtmux;\e\eP+q4D73\e\\\e\\'
```

Kitty shows an error:

```
[PARSE ERROR] DCS sequence contained ESC without trailing \ at pos: 7 ignoring the sequence
```

**Comment by gpanders** [comment]
Linked tmux issue here: https://github.com/tmux/tmux/issues/3755

In any case, there is nothing that Neovim can do about this. Please follow the tmux issue.

**Comment by gpanders** [comment]
>In any case, there is nothing that Neovim can do about this. 

I stand corrected, we need an extra escape.

**Comment by przepompownia** [comment]
@gpanders thanks for investigation. Now setting `vim.g.clipboard` simply works for me there! I don't have to set it manually or in my configuration. 

I wasn't sure how sufficient my reproduction condition was, so I'm also glad you were able to reproduce it.
