### ISSUE TITLE
jemalloc is downloaded and built regardless of DUSE_JEMALLOC value

### ISSUE THREAD

**Issue by Pyrohh** [neovim/neovim#2633]
jemalloc 3.6.0 doesn't build on OpenBSD -current for me, so I'm trying to disable it. The following is in my `local.mk`:

```
CMAKE_EXTRA_FLAGS="-DUSE_JEMALLOC=OFF"
```

Regardless, CMake downloads then fails building it as expected. The HEAD of jemalloc master builds fine for me (I can use [this patch][1] for nvim to use it), but I'd think that it shouldn't be built in the first place. What do you think @fwalch?

[1]: https://gist.github.com/Pyrohh/afe35148768df900f0aa

**Comment by justinmk** [comment]
Sure it's not a cmake cache issue?

**Comment by Pyrohh** [comment]
Definitely not, it happens on a freshly cloned repository.

**Comment by jszakmeister** [comment]
That disables using the jemalloc library when building Neovim, but doesn't
tell us not to build it when building the dependencies.  You probably need
to add something like:
    DEPS_CMAKE_FLAGS := -DUSE_BUNDLED_JEMALLOC=OFF

To your local.mk.

**Comment by Pyrohh** [comment]
That worked, thanks! I opened #2634 as `-DUSE_JEMALLOC=OFF` doesn't seem to exist anymore.
