### ISSUE TITLE
preserve extmarks when using folds or other similar (treesitter) features

### ISSUE THREAD

**Issue by Danielkonge** [neovim/neovim#26350]
### Problem

Today I saw an issue in `rainbow-delimiters` about highlighting while using `vim.treesitter.foldtext()` [ HiPhish/rainbow-delimiters.nvim/issues/71 ], and I have also filed a similar issue in `nvim-treesitter-context` some time ago [ nvim-treesitter/nvim-treesitter-context/issues/358 ], so I thought I would collect the idea of what I would want from neovim, if possible, here. (If there is already a way to do something like this, could anyone point me in the right direction?)

The main problem is this: For these types of features, where you reproduce a subset of the characters from multiple lines, is there any easy way to keep the extmarks/highlights with the text?

To be more specific, I will just focus on `vim.treesitter.foldtext()`. Would it be possible to easily keep the highlighting of say `(` and `)` coming from `rainbow-delimiters` if I fold something like this (made up simple example):
```lua
test(
  a,
  b,
  c,
)
```
to this:
```lua
test( ... )
```
(Since not everyone might want this, this probably involves some way to optionally include the highlights.)

### Expected behavior

Optionally keep the extmark highlights of e.g. parentheses when folding (or doing other similar operations).

**Comment by justinmk** [comment]
> Optionally keep the extmark highlights

It's not a matter of doing it "optionally", it's more like we would need to implement a way for the edits to preserve the extmarks.

So to me, the request here is "preserve extmarks in more cases (complex edits)".

**Comment by zeertzjq** [comment]
Obsolete with #20750
