### ISSUE TITLE
:term should not autoscroll when in normal mode

### ISSUE THREAD

**Issue by jwhitley** [neovim/neovim#2636]
**Repro steps**
1.  Open a shell with `:term`
2.  Fire up `tail -f` on a high-volume website log or similar.
3.  Scroll the window up.  I have mouse scroll enabled and used that.

**Expected results:**
Similar to tmux, when backscrolling, the buffer's position doesn't change as new text is added at the head of the backscroll.  This makes it possible to browse, search, etc. through the history until the user returns the terminal to insert mode.

**Actual results:**
Text continues to flow past the cursor point at the same rate as it's being added to the terminal buffer, even after having scrolled upwards into the history.  This is weird behavior and makes the backscroll entirely unusable if there's active output from the terminal's process (such as with tail -f).

**Comment by mattboehm** [comment]
+1, this has bitten me a few times.

**Comment by justinmk** [comment]
What if I want to see tail results while in another window? Seems that instead we need a "freeze" command or something.

**Comment by jwhitley** [comment]
Actually, as I'm already discovering, it's problematic on multiple levels for `:term` to switch its own mode based on the global insert/normal mode.  E.g. it should be possible to move the cursor out of a terminal then back and remain in the same input state.  It's super annoying to be in a terminal, use a keybinding to move to make some edits, then be *out* of insert mode once the cursor is moved back to the terminal.

Likewise, if the terminal is "at head" (i.e. displaying active output) or "in history" (displaying the backscroll), switching active buffers shouldn't really affect that.

**Comment by jwhitley** [comment]
@justinmk offhand, those rules seem like a good start.  My current expecations are set from tmux and other terminal emulators, which have definitely evolved their own notions of terminal window state which are somewhat distinct from vim's modes.

**Comment by wamoyo** [comment]
@jwhitley I expect slightly different results.

When I scroll back up to look at something, I expect he buffer to stay where it is, but (small tweak) if I go to insert mode, or just press `<shift>` + `G` I expect the buffer to keep up with new output, like my server logs or anything else. 

That way, when I switch to code, and switch back to look at output, I don't have to manually scroll down.

**Comment by jwhitley** [comment]
@wamoyo I agree re: `<shift>+G`, and that's exactly the same as the broader tmux behavior I was referencing: once you're at the head of the backscroll, whether by mouse scroll or keyboard navigation, new input takes precedence.  In fact, if you've got tmux's vi bindings in use, `<shift>+G` acts precisely as you state.  re: input mode, that also seems roughly similar to tmux's behavior.  It's worth testing out the input mode idea, just to be sure there aren't unfortunate edge cases.  Cheers!

**Comment by justinmk** [comment]
With #6142, `G` follows output in normal-mode, and otherwise stays puts. However, if scrollback is _full_, it will still appear to scroll as new lines are added. So with #6142 a partial solution to this issue is to `:setlocal scrollback=100000` so that scrollback is unlikely to get full.

I see that you're asking for the tmux behavior where output is ignored while in "navigation mode", but that wouldn't be good for `:terminal` buffers because normal mode is the _most common mode_ in Nvim. Users will wonder why "nothing is happening" when they are in normal-mode.

The difference between tmux and nvim is that in nvim, it's trivial and common to yank the entire buffer and paste it in a dummy buffer to inspect it:

    :%y|new
    P

In tmux that would be awkward and unusual.

**Comment by jwhitley** [comment]
> that wouldn't be good for :terminal buffers because normal mode is the most common mode in Nvim.

That's an interesting argument, but I'll offer up that the above user logic is almost certainly reversed in `:term` buffers.  If you've got a terminal window, you likely want it ready to interact.  E.g. I use zsh with vi bindings, and it defaults to insert mode because that's _far_ more useful than remembering a blank command line needs me to whack `i` before I can do anything.  That logic also extends to nvim `:terminal` buffers; I want it ready to accept a command, and so insert will be my default mode there.
