### ISSUE TITLE
Support for clearing scrollback with :term

### ISSUE THREAD

**Issue by jwhitley** [neovim/neovim#2637]
This is an enhancement request for the (ahem, amazing) new `:term` feature.  I'd like a command that can clear a terminal's backscroll history similarly to tmux's `clear-history` command.

An example use-case from a typical workflow of mine:
1.   Make some project edits in nvim
2.   In a :term window, blow away the backscroll history
3.   Run a large test suite in the :term window
4.   Repeat the above steps.  A lot.

By clearing the backscroll in the test window (which often runs `vagrant ssh` into a project VM) before the run, it's much easier to jump to the beginning of the run, search through it, etc.  For example, I currently have bindings setup in tmux (`<prefix>k`) which clears both the shell window (via `<C-L>`) as well as the backscroll (via tmux `clear-history`).

**Comment by Pyrohh** [comment]
I mentioned this earlier on gitter, but I'm not sure you saw it: Why not just pipe it into a pager?

**Comment by jwhitley** [comment]
@Pyrohh I did see that, but very, very long after you posted it.  Thanks for following up.

To answer your question, sure, I could do that.  I still use pagers all the time, directly and via $PAGER with tools like man.  But there are a few reasons why pagers don't work as well here:

 * After having gotten used to tmux's first-class history with editor-like bindings, I could just as well offer the counter question: *Why should I need a pager?*  With a gesture, I can get back and see what's gone by, and otherwise search and navigate that history just like I would in less, vimpager, etc.
 * With the above point, I find that for "small paging tasks" I often don't bother with a pager.  I'll just use the backscroll history, and that's also wired up for easy retrieval of text to the system clipboard, etc.
 * Pagers play poorly with output streams that rewrite the stream or otherwise do fancy formatting, e.g. some nice test formatters reduce noise by rewriting the same line for passing tests, ala `[104/2055] WombatTest#test_foo_bar_baz`, then *not* rewriting when a test fails, so the net output is only the failed tests.  Love. This. To. Death.  But tmux history?  Absolutely copacetic with fancy terminal stuff like this.

**Comment by Pyrohh** [comment]
Thanks for explaining, I can see why you'd want that.

**Comment by justinmk** [comment]
Why don't we just make `:term` buffers modifiable? We just need to set the expectation that these modifications are cosmetic only, they don't get sent to the child process.

Then, clearing scrollback is trivial...

**Comment by justinmk** [comment]
With #6142 then new buffer-local `'scrollback'` option can be set on the fly. If it is set lower, it will truncate scrollback lines if the existing scrollback is too big. Then you can set it to a higher value again.
