### ISSUE TITLE
[feature:] built-in plugin system with registry as easy as VS Code

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#26374]
### Problem

To use "plugins" or "extensions", we have to manually write code to configure a plugin manager in our rc file and specify where to get plugins/extensions from in a non-standard way (typically from git repos).

While this works,

- it is more cumbersome than something like the built-in plugin manager in VS Code
- it is error prone
- there's no official registry to catalogue plugins out of the box

### Expected behavior

What would be sweet is if Neovim has a built-in plugin manager and a registry, making it as easy to use out-of-the-box as plugins in VS Code.

In VS Code, you activate the plugin UI, search or browse for a plugin, then hit the install button.

Neovim could offer something similar out-of-the-box, but with a TUI by default. GUI frontends for Neovim could hook into the API to offer even better UIs.

The advantages would be:

- easily discover plugins from a registry (or some system that catalogues them from github or somewhere)
  - The (T/G)UI would be able to also offer ways of exploring plugins (like VS Code) such as filters for installed, workspace-only, themes, language-specific, votes, downloads, etc.
- easily install them
- don't worry about programming a plugin manager and making mistakes
- Neovim becomes customizeable in a way that is more approachable and easier out-of-the-box for newcomers to Vim world (while rc configuration would still work as-is).

**Comment by clason** [comment]
Duplicate, and not in scope.

**Comment by justinmk** [comment]
Plugin registry "search" is not in scope. But a builtin, minimal "plugin manager" based on https://github.com/savq/paq-nvim is in scope. Current status/plan is here:

- https://github.com/neovim/neovim/issues/24221#issuecomment-1616009906
- https://github.com/neovim/neovim/issues/20893#issuecomment-1297870788

To solve these use-cases:

- Reduce the steps needed to install plugins (or other plugin managers).
- Establish a provider-like interface for "plugin install" task.

Nothing else is in scope, please don't leave comments on those issues, they'll be deleted.
