### ISSUE TITLE
Visual Mode Preservation when using <Cmd> is broken when calling :move

### ISSUE THREAD

**Issue by Uroc327** [neovim/neovim#26383]
### Problem

When mapping to a `<Cmd>` which includes `:move` in visual mode, then the marks as well as the visual mode selection after executing the mapping seem off.

### Steps to reproduce

```
" write some text


:xmap <C-k> :'<,'>move'<-- <Bar> keepjumps normal! gv<CR>
:xmap <C-j> :'<,'>move'>+ <Bar> keepjumps normal! gv<CR>

" select lines with `V` and move around multiple times using <C-k>/<C-j>


:xmap <C-k> <Cmd>'<,'>move'<--<CR>
:xmap <C-j> <Cmd>'<,'>move'>+<CR>

" moving lines around now can't be done by hitting <C-k> multiple times because the selection changes


:xmap <C-k> <Cmd>'<,'>move'<-- <Bar> keepjumps normal! gv<CR>
:xmap <C-j> <Cmd>'<,'>move'>+ <Bar> keepjumps normal! gv<CR>

" trying manual `gv` reselection also doesn't seem to work
```

### Expected behavior

The visual mode preservation (I believe) should move the new visual mode up to the newly moved lines.

In this example, this means that hitting `<C-k>`/`<C-j>` multiple times should move the initially selected chunk up and down

### Neovim version (nvim -v)

v0.9.4

### Vim (not Nvim) behaves the same?

yes, 9.0.1882

### Operating system/version

Void Linux

### Terminal name/version

alacritty 0.12.3

### $TERM environment variable

alacritty

### Installation

system package manager (xbps)

**Comment by zeertzjq** [comment]
I don't think this is possible. The Visual selection must be contiguous, and the range of `:move` may only be a part of the Visual selection.
