### ISSUE TITLE
Strange white space padding when using  nvim_buf_set_extmark for inlay virtual text

### ISSUE THREAD

**Issue by ray-x** [neovim/neovim#26388]
### Problem

Please refer to the attached video
https://github.com/neovim/neovim/assets/1681295/8fe6b0af-719c-49fa-8398-1ca33a6ea3ba

### Steps to reproduce

install nvim head with brew
open following 1.lua code
```lua
local ns = vim.api.nvim_create_namespace('test')
vim.api.nvim_buf_set_extmark(0, ns, 0, 5, {
              virt_text_pos = 'inline',
              ephemeral = false,
              virt_text = {{'[virtual text]'}},
            })
```

```sh
nvim -u NORC 1.lua
```

Run `1.lua`  with `luafile %`
Change to insert mode, move cursor to `1:7` and press `<BS>`; 
`[virtual text]` shifted to right with space added.
Press `<Right>` the cursor stops on next character after virtual text `[virtual text]n|`

### Expected behavior

TBH, I am not sure what is the expected behavior. But I would expected the virtual text remain it's initial position.
Also If my cursor is around virtual text when press `<left>` and `<right>` it should stop on virtual text boundary   `|[virtual text]|` (the `|` stands for expected cursor position) 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-748eae6

### Vim (not Nvim) behaves the same?

I do not know as the API may be unique to nvim

### Operating system/version

macOS 10.15.2

### Terminal name/version

kitty

### $TERM environment variable

kitty-256

### Installation

brew install --HEAD

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by ray-x** [comment]
There are two problems with this issue
1. `<BS>` was replaced with space, this is similar to https://github.com/neovim/neovim/issues/24075. But what I saw is the virtual text was shifted to the right. https://github.com/neovim/neovim/issues/24075 does not have this issue. If I press `<BS>` fast enough, I can delete the text before virtual text
2. incorrect virtual text boundary when move cursor.  The boundary is the length of virtual text + 1

**Comment by zeertzjq** [comment]
Please provide steps to reproduce with `nvim --clean`.

**Comment by ray-x** [comment]
It not reproducible  with `--clean` nor `-u NONE`. Only reproduce with `-u NORC`. 
But I can not tell which plugin breaks the behavior.

**Comment by Sam-programs** [comment]
setting `'softtabstop'` seems to cause the issue
```lua
-- init.lua
vim.opt.softtabstop = 3
```
```lua
-- repro.lua
local ns = vim.api.nvim_create_namespace('test')
vim.api.nvim_buf_set_extmark(0, ns, 0, 5, {
              virt_text_pos = 'inline',
              ephemeral = false,
              virt_text = {{'[virtual text]'}},
            })
```
run neovim then go to `1:7` and press backspace
```
nvim -u init.lua repro.lua
```

**Comment by Sam-programs** [comment]
https://github.com/neovim/neovim/blob/7f9fc2fbf03e18c1e4033763be4905707d7a84e7/src/nvim/edit.c#L3846-L3847
https://github.com/neovim/neovim/blob/7f9fc2fbf03e18c1e4033763be4905707d7a84e7/src/nvim/edit.c#L3658-L3661
want_col is at the end of the character before the cursor but `ins_bs_one` sets vcol to the start of the character before the cursor? 
Changing vcol to be the end in `ins_bs_one` seems to fix the issue.
```diff
diff --git a/nvim b/nvim
new file mode 100644
index 000000000..e69de29bb
diff --git a/src/nvim/edit.c b/src/nvim/edit.c
index 8984a959d..6728e20f8 100644
--- a/src/nvim/edit.c
+++ b/src/nvim/edit.c
@@ -3658,7 +3658,7 @@ static void ins_del(void)
 static void ins_bs_one(colnr_T *vcolp)
 {
   dec_cursor();
-  getvcol(curwin, &curwin->w_cursor, vcolp, NULL, NULL);
+  getvcol(curwin, &curwin->w_cursor, NULL, NULL, vcolp);
   if (State & REPLACE_FLAG) {
     // Don't delete characters before the insert point when in
     // Replace mode
```
