### ISSUE TITLE
Output in a :term causes immediate message window dismissal

### ISSUE THREAD

**Issue by jwhitley** [neovim/neovim#2638]
**Repro steps:**
 1. Open a terminal via `:vsp | term`
 2. In that term, tun something with continuous output, e.g. a big test suite, `tail -f`, etc.
 3. Move back to an editor pane and run `:map` or similar.

**Expected results:**
The message content from the map command remains until dismissed.

**Actual results:**
It appears that terminal output causes the message content to be dismissed immediately.  If there's active output in the terminal, the results of `:map` will briefly flash then disappear.  This happens even if the active terminal is on a different tab page than the current one.

**Comment by lucc** [comment]
Some more observations:
- The message are is only cleared when input is recieved in the terminal buffer. Try `while sleep 2; do echo foo; done` and see how the message buffer will remain for the time until the next `echo`.
- When there is a "hit enter" prompt and new text coming to the terminal clears the message are, the cursor stays at the same position as it was in the "hit enter" prompt even after the messages where cleared. I have to press enter to get the cursor back.

**Comment by oni-link** [comment]
@jwhitley, @lucc, looks like `:map` output is not dismissed anymore. Can this be closed?

**Comment by lucc** [comment]
Yes, terminal updates are delayed and I can look at the output of `:messages` at the hit-enter prompt. When I hit enter the terminal is updated. In my opinion this can be closed, but keep in mind that I did not report this issue, so @jwhitley might think differently.

**Comment by jwhitley** [comment]
@oni-link Confirmed fixed here.  Closing, thanks!

**Comment by jwhitley** [comment]
For posterity, I did the confirmation test with a `brew` neovim HEAD build at 0595da8d0b9bc9f4ea6f06047d3b25926d72156b.
