### ISSUE TITLE
ninja: build stopped: subcommand failed. make: *** [Makefile:99: deps] Error 1

### ISSUE THREAD

**Issue by FriendsZonn** [neovim/neovim#26405]
### Problem

i was building the neovim source code ,, after taking the command "sudo make install ", it seems like its stucked , and ended with a "_build stopped_ subcommand failed. make_ ___ [Makefile_99_ deps] Error 1"

### Steps to reproduce

MY steps:
1.git clone https://github.com/neovim/neovim.git
2.cd ./neovim 
3.make CMAKE_BUILD_TYPE=RelWithDebInfo 

here is the console output
-- Installing: /home/friends/neovim/.deps/usr/include/luv/lreq.h
[130/136] Performing download step (download, verify and extract) for 'lpeg'
FAILED: build/src/lpeg-stamp/lpeg-download /home/friends/neovim/.deps/build/src/lpeg-stamp/lpeg-download
cd /home/friends/neovim/.deps/build/src && /usr/bin/cmake -P /home/friends/neovim/.deps/build/src/lpeg-stamp/download-lpeg.cmake && /usr/bin/cmake -P /home/friends/neovim/.deps/build/src/lpeg-stamp/verify-lpeg.cmake && /usr/bin/cmake -P /home/friends/neovim/.deps/build/src/lpeg-stamp/extract-lpeg.cmake && /usr/bin/cmake -E touch /home/friends/neovim/.deps/build/src/lpeg-stamp/lpeg-download
-- Downloading...
   dst='/home/friends/neovim/.deps/build/downloads/lpeg/lpeg-1.1.0.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/neovim/deps/raw/d495ee6f79e7962a53ad79670cb92488abe0b9b4/opt/lpeg-1.1.0.tar.gz'
-- Retrying...
-- Using src='https://github.com/neovim/deps/raw/d495ee6f79e7962a53ad79670cb92488abe0b9b4/opt/lpeg-1.1.0.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/neovim/deps/raw/d495ee6f79e7962a53ad79670cb92488abe0b9b4/opt/lpeg-1.1.0.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/neovim/deps/raw/d495ee6f79e7962a53ad79670cb92488abe0b9b4/opt/lpeg-1.1.0.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://github.com/neovim/deps/raw/d495ee6f79e7962a53ad79670cb92488abe0b9b4/opt/lpeg-1.1.0.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/neovim/deps/raw/d495ee6f79e7962a53ad79670cb92488abe0b9b4/opt/lpeg-1.1.0.tar.gz'
CMake Error at lpeg-stamp/download-lpeg.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/neovim/deps/raw/d495ee6f79e7962a53ad79670cb92488abe0b9b4/opt/lpeg-1.1.0.tar.gz' failed
          status_code: 7
          status_string: "Couldn't connect to server"
          log:
          --- LOG BEGIN ---
            Trying 20.205.243.166:443...

  Connected to github.com (20.205.243.166) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  TLSv1.0 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  TLSv1.2 (IN), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.3 (IN), TLS handshake, Server hello (2):

  [122 bytes data]

  TLSv1.2 (IN), TLS header, Finished (20):

  [5 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):

  [19 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (IN), TLS handshake, Certificate (11):

  [2459 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (IN), TLS handshake, CERT verify (15):

  [80 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (IN), TLS handshake, Finished (20):

  [36 bytes data]

  TLSv1.2 (OUT), TLS header, Finished (20):

  [5 bytes data]

  TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (OUT), TLS handshake, Finished (20):

  [36 bytes data]

  SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256

  ALPN, server accepted to use h2

  Server certificate:

   subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
   start date: Feb 14 00:00:00 2023 GMT
   expire date: Mar 14 23:59:59 2024 GMT
   subjectAltName: host "github.com" matched cert's "github.com"
   issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
   SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.

  Using HTTP2, server supports multiplexing

  Connection state changed (HTTP/2 confirmed)

  Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
  len=0

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  Using Stream ID: 1 (easy handle 0x561fd0dfb1a0)

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  GET
  /neovim/deps/raw/d495ee6f79e7962a53ad79670cb92488abe0b9b4/opt/lpeg-1.1.0.tar.gz
  HTTP/2

  Host: github.com

  user-agent: curl/7.81.0

  accept: */*

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):

  [57 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):

  [57 bytes data]

  old SSL session ID is stale, removing

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  HTTP/2 302

  server: GitHub.com

  date: Tue, 05 Dec 2023 13:48:21 GMT

  content-type: text/html; charset=utf-8

  vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding,
  Accept, X-Requested-With

  access-control-allow-origin: https://render.githubusercontent.com

  location:
  https://raw.githubusercontent.com/neovim/deps/d495ee6f79e7962a53ad79670cb92488abe0b9b4/opt/lpeg-1.1.0.tar.gz

  cache-control: no-cache

  strict-transport-security: max-age=31536000; includeSubdomains; preload

  x-frame-options: deny

  x-content-type-options: nosniff

  x-xss-protection: 0

  referrer-policy: no-referrer-when-downgrade

### Expected behavior

want to know how to solve it,and what caused the problem 

### Neovim version (nvim -v)

0.9

### Vim (not Nvim) behaves the same?

no

### Operating system/version

WSL2

### Terminal name/version

zsh

### $TERM environment variable

xterm-256color

### Installation

source code

**Comment by clason** [comment]
Flaky network connection; not much we can do about that. Certainly not a bug in Neovim.
