### ISSUE TITLE
Slow-starting LSP server locks up UI

### ISSUE THREAD

**Issue by rickyelopez** [neovim/neovim#26408]
### Problem

I am trying to get an LSP server that the company I work at built working in neovim. I have written a small plugin that adds it to lspconfig, and that all works great. The problem is that the server takes some time (5-10 seconds) to start up, and during that time neovim is completely frozen.

Is there any way to start the LSP server asynchronously, or otherwise not lock up the UI? It's not the end of the world, but it feels like there should be a way to do this. I tried googling as well as looking through the lspconfig repo to see if any servers implement this, but I found nothing useful.

### Steps to reproduce using "nvim -u minimal_init.lua"

I suppose you could set up a fake lsp server binary that just delays for a few seconds to repro?

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1754+g3159a2c28

### Language server name/version

internal, can't share

### Operating system/version

Ubuntu LTS 22.04

**Comment by justinmk** [comment]
> I have written a small plugin that adds it to lspconfig,

Why use lspconfig at all? nvim-lspconfig is just a collection of configs for existing servers. Your server is totally custom, so nvim-lspconfig is a useless extra layer. See `:help vim.lsp.start()` / `:help vim.lsp.start_client()` which mentions:

                  • detached: (boolean, default true) Daemonize the server
                    process so that it runs in a separate process group from
                    Nvim. Nvim will shutdown the process on exit, but if Nvim
                    fails to exit cleanly this could leave behind orphaned
                    server processes.

I haven't tried this myself, so please confirm if it helps.

**Comment by rickyelopez** [comment]
> Why use nvim-lspconfig at all?

It's still a really nice wrapper layer to handle client/server capabilities, internal commands, mappings, etc.

I'll look into that arg, maybe there's a way I can get lspconfig to use it

**Comment by rickyelopez** [comment]
Looks like lspconfig doesn't support passing args to the `start_client` call here: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/manager.lua#L152C31-L152C31

This should probably be a ticket in their repo, since clearly the functionality exists in nvim.

Thanks!

**Comment by clason** [comment]
No, seriously: nvim-lspconfig is not the right tool for this job. It is _not_ a nice wrapper -- it's a collection of premade configurations, nothing more, nothing less. You should instead write your plugin based on `vim.lsp.start`, which is the officially intended way.

**Comment by rickyelopez** [comment]
>  it's a collection of premade configurations, nothing more, nothing less

but this is exactly what I'm trying to do? I don't understand why I wouldn't just leverage this tool that already does everything I'm trying to do, except for spawning the server in detached mode?

**Comment by clason** [comment]
>  that already does everything I'm trying to do

But it does nothing except call `vim.lsp.start()`?

> for the other people at the company that use this, this will effectively be a pre-made configuration

So you're going to fork nvim-treesitter to add support for a proprietary tool? You're welcome to (as long as you respect the license), but don't expect much interest to help you then. The officially supported way is and remains just using `vim.lsp.start()`, which you can wrap much more easily in a custom plugin.

**Comment by rickyelopez** [comment]
I'm not forking anything, I'm literally just making a plugin that adds a `.lua` file nearly identical to many of the ones in the lspconfig repo. If the lsp server wasn't proprietary, I would just want to merge this into the lspconfig repo. I don't see how this is different from any of the other ones server configurations in that repo?

Forgive my ignorance, I see your point that I could write my own support in the plugin, I just don't understand why I would go down that route and do significantly more development when it seems to me like making a server configuration accomplishes exactly the same objective.

**Comment by clason** [comment]
The point is that it's really not more work (it's literally the same config table; you're just cutting out an unnecessary layer of redirection). People think they _need_ nvim-lspconfig for using language servers, but that is very much not the case, and we're working hard to clear up this misconception. Again, it's in _your_ interest not to rely on nvim-lspconfig for this.

**Comment by rickyelopez** [comment]
Interesting. I just looked at the params to `vim.lsp.start_client` and yeah I see your point, nearly identical to the keys in the lspconfig config.

I guess the only other thing I would have to handle separately is adding the commands? That's not so bad

**Comment by clason** [comment]
No, that is only for the bundled configs. You can use `:=vim.lsp.get_active_clients()` for (much more) details.

**Comment by rickyelopez** [comment]
Neat. So what's the benefit of doing it directly like this? I mean I see your point that lspconfig is not required, but why is this better? Even having to implement the few things that don't seem to be free seems like more work than just using lspconfig?

The way I see it, if I implement it myself I have to:
- call `vim.lsp.start_client` myself (trivial)
- create the commands myself with `nvim_create_user_commands` (also easy, but more steps than just adding them to the config table)
- set up filetype detection myself (also probably trivial)
- maybe something else I'm not seeing?

vs. just writing a table for lspconfig?

**Comment by clason** [comment]
> * call vim.lsp.start_client myself (trivial)

Indeed; it's the same table

> * create the commands myself with nvim_create_user_commands (also easy, but more steps than just adding them to the config table)

No; unless you're down to counting single characters. (And even then you might lose.)

> * set up filetype detection myself (also probably trivial)

nvim-lspconfig does not do this; it relies on builtin Vim filetype detection

> * maybe something else I'm not seeing?

No.

In any case, if you want `detach`, you _cannot_ do this via nvim-lspconfig, so that kinda clinches it, no?

> Plus, doing it myself I lose out on LspLog, LspInfo, LspRestart and other similar functionality provided by lspconfig?

Those are vestigial and not guaranteed to remain in nvim-lspconfig. Really, it's only meant to be a collection of premade configs, nothing else.

**Comment by rickyelopez** [comment]
> In any case, if you want detach, you cannot do this via nvim-lspconfig, so that kinda clinches it, no?

doesn't seem like it would be much work to add, pretty sure I've almost gotten it working since posting the link to the relevant code above

> Those are vestigial and not guaranteed to remain in nvim-lspconfig.

that's a huge bummer for me even when considered separately from this topic. Hope that's not the case.

anyway, I see your point and it seems like it might be interesting to implement it myself. Bummer though, because I would really prefer to focus on the actual functionality of the tool rather than this (seemingly) boilerplate implementation. It would be nice if there was something that did this for you, which is what the lspconfig server configuration seemed like to me.

**Comment by rickyelopez** [comment]
> But you are wrong there; I'm not sure how much clearer I can be about this. Unless you want to use a preconfigured server, nvim-lspconfig literally does not save you any effort.

I understand what you're saying, I'm just not seeing it. Maybe I will agree after understanding all of the steps fully, but right now I have something that works completely (other than the missing `detached` option) without having had to dig into each step and figure out how it works.

> Of course, you are welcome to still do it however you wish; but you will have no support for it since this is not the intended use case.

Of course I want to do it the "right" way, I just want to understand it fully before I tear up everything I've written and make it work without lspconfig

> Obviously that functionality -- if deemed useful given the core API -- will be included in Neovim in some form then.

glad to hear it

**Comment by rickyelopez** [comment]
I implemented everything myself. It wasn't as bad as I was expecting, but it was still definitely more work than the lspconfig implementation I had previously. Agreed that this way is better, though. Thanks for the tips
