### ISSUE TITLE
Trying running on nixos 14.12

### ISSUE THREAD

**Issue by favetelinguis** [neovim/neovim#2640]
Im trying to get neovim working with nixos 14.12. It says in the install notes that neovim is only available in the unstable channel, this is no longer the case. Neovim is available in the stable 14.12 branch also.
https://github.com/NixOS/nixpkgs/blob/release-14.12/pkgs/applications/editors/neovim/default.nix#L59

However im not sure what version of neovim im 14.12 referes to, does the above installation point to the latest build in main of neovim? Also how do I set up python packages. pip3 will fail when installing neovim with the message:

error: command 'gcc' failed with exit status 1

**Comment by fwalch** [comment]
I guess the first question could be better answered by the NixOS developers, as they were the ones that created the package.

Can you post the full output for the installation error?

**Comment by favetelinguis** [comment]
See below for part of the build that fails:

(What are the python packages used for? Im trying to get fireplace for Clojure set up but cant connect to the repl since it complain that python can not be found.)

building 'greenlet' extension

creating build

creating build/temp.linux-x86_64-3.4

gcc -pthread -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/nix/store/hlf8kajdx1zb387d8z6a4811759jn3kg-python3-3.4.2/include/python3.4m -c greenlet.c -o build/temp.linux-x86_64-3.4/greenlet.o

error: command 'gcc' failed with exit status 1

**Comment by Pyrohh** [comment]
I notice that the nix pkg you linked is very old; does it fetch a fixed revision, or the latest revision? Anyways, if it fetches a fixed revision then it needs to be updated. I'm not sure this is relevant to Neovim as opposed to being a packaging issue.

**Comment by favetelinguis** [comment]
Yes it is a old version. Im trying to update it but its not going so god. I need to know every build dependency neovim has.

Also what are the pyton modules used for? They seem to be mandatory for neovim to work properly?

**Comment by Pyrohh** [comment]
> Also what are the pyton modules used for? They seem to be mandatory for neovim to work properly?

This isn't true anymore; a recent PR removed that warning because the Python module isn't actually required anymore. IIRC it used to be needed for the clipboard provider, but that's been migrated to Vimscript.

**Comment by favetelinguis** [comment]
Hmm so I guess i only need to get the latest master commit into the package and all will be fine then. You can close this thread.
