### ISSUE TITLE
Error while using dap with node.js (connection refused).

### ISSUE THREAD

**Issue by dir1337** [neovim/neovim#26419]
### Problem

Hello,
Respected devs,

I am using nvim-dap and while running debugger got an error of connection refused for js files.
dap.lua >
```lua
local dap = require("dap")

dap.adapters["pwa-node"] = {
  type = "server",
  host = "127.0.0.1",
  port = 9229,
  executable = {
    command = "js-debug-adapter",
  }
}

for _, language in ipairs { "typescript", "javascript" } do
  dap.configurations[language] = {
    {
      type = "pwa-node",
      request = "launch",
      name = "Launch file",
      program = "${file}",
      cwd = "${workspaceFolder}",
      runtimeExecutable = "/usr/bin/node",
    },
  }
end
```
The Strange thing is that earlier it was working perfectly but now showing error.

**Error:**
Couldn't connect to 127.0.0.1:9229 ECONNREFUSED 

### Steps to reproduce

Setup nvim-dap,
Setup nvim-dap-ui,
Make the same config file.

### Expected behavior

It should open the debugger.

### Neovim version (nvim -v)

NVIM v0.9.4, Build type: Release, LuaJIT 2.1.1700008891

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Arch linux

### Terminal name/version

Gnome-console (kgx)

### $TERM environment variable

NA

### Installation

AUR

**Comment by clason** [comment]
Please report this with nvim-dap (first).
