### ISSUE TITLE
The link in “https://github.com/neovim/neovim/wiki/Installing-Neovim#Android” is rather obsolete.

### ISSUE THREAD

**Issue by lianzhoulu** [neovim/neovim#26414]
### Problem

It is suggested that the link in https://github.com/neovim/neovim/wiki/Installing-Neovim#Android be updated, as it is rather obsolete, and that https://github.com/termux/termux-app be used instead.

### Expected behaviour

It is requested that the link given in https://github.com/neovim/neovim/wiki/Installing-Neovim#Android be altered to https://github.com/termux/termux-app.

**Comment by zeertzjq** [comment]
Updated, thanks!
