### ISSUE TITLE
'nowrapscan' makes completion strange

### ISSUE THREAD

**Issue by lilydjwg** [neovim/neovim#2641]
For example, run `nvim --noplugin -u NONE`, type `:e` and then press tab several times, what appears in cmdline is:

```
1 earlier
2 echo
3 echoerr
...
```

Do a `set wrapscan` or `set nowrapscan` and then try the same, the result is:

```
1 earlier
2 earlier
3 earlier
4 echo
5 echoerr
...
```

It needs two more tabs.

This behavior won't change back when setting wrapscan to the opposite value.

Commit: af4b0a76a757f44ea7fbfc8e1c863952adc6ac1e

This is different with #1546. My neovim is latest. It doesn't change with 'wildmenu`.

**Comment by fmoralesc** [comment]
Can confirm.

**Comment by msteed** [comment]
Also can be triggered by `set equalalways` or `set noequalalways` and probably other options.

**Comment by justinmk** [comment]
Cannot reproduce. Can you give full, precise steps? Or maybe record a video.

**Comment by msteed** [comment]
```$ nvim -u NONE```

Then `:e<Tab>` shows the following wildmenu and command line as expected:
```
  [earlier]  echo  echoerr  echohl  echomsg  echon [and so on]
  :earlier
```
This step is not necessary to reproduce the problem, but it does show that completion is working correctly at first.

Hit `<Esc>` to dismiss the wildmenu and `:set ea` and hit Enter.

Now try `:e<Tab>` again. After hitting Tab, the `:earlier` completion appears on the command line but there are no completions on the wildmenu. The 2nd and 3rd Tabs produce no visible change. The 4th Tab shows:
```
  earlier  [echo]  echoerr  echohl  echomsg  echon [and so on]
  :echo
```
and then wildmenu navigation works as expected until a selection is made.

However, now every time you use command line tab completion, you will see this initial strangeness requiring four tabs to start cycling through completions. It doesn't matter what you are completing (filenames, options, environment variables, etc.). It affects completion whether `wildmenu` is enabled or not.

**Comment by justinmk** [comment]
I wonder if this is related to https://github.com/neovim/neovim/issues/3374.

**Comment by msteed** [comment]
Yes, the `LDFLAGS` fix mentioned there resolves the problem for me.

**Comment by justinmk** [comment]
@msteed Awesome! Thanks for your help.
