### ISSUE TITLE
Rendering bug when scrolling in kitty term with specific plugins.

### ISSUE THREAD

**Issue by geril2207** [neovim/neovim#26422]
### Problem

I found this problem in nightly with using `incline` or `fidget` plugins. Also tried in kitty and alacritty. Alacritty seems to be ok(i'm not sure for all cases), but kitty not. These plugins make floating windows(i guess) in right up/down corners to display some information, incline filename, fidget lsp info. When some of them on the screen there are weird `cursors`(kind of) through all screen(mostly on the right side) when scrolling.
Nightly:
https://github.com/neovim/neovim/assets/62308020/fc570b6d-a1d8-484e-aad0-6ee17a409eec
0.9.4:
https://github.com/neovim/neovim/assets/62308020/d12de68a-4e4c-44c4-9683-1beef48019c9

Config to reproduce:
```lua
for name, url in pairs({
	-- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
	-- some_plugin = 'https://github.com/author/plugin.nvim'
	"https://github.com/b0o/incline.nvim",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

require("incline").setup()
```

### Steps to reproduce

1.Open kitty term
2. Copy config to reproduce.
3. nvim `some file with ability to scroll` --clean -u `repro_conf.lua`
4. There should be filename in right up corner.
5. Scroll in file.

### Expected behavior

Screen rendering like `0.9.4`

### Neovim version (nvim -v)

v0.10.0-dev-988b472

### Vim (not Nvim) behaves the same?

idk

### Operating system/version

arch

### Terminal name/version

kitty `0.31`

### $TERM environment variable

xterm256-color

### Installation

build from repo

**Comment by clason** [comment]
Can you bisect to the specific commit that introduced this?

**Comment by clason** [comment]
And please always test the _latest_ commit on `master`; 988b472 is already outdated.

**Comment by geril2207** [comment]
> Can you bisect to the specific commit that introduced this?

Maybe later

**Comment by geril2207** [comment]
> And please always test the _latest_ commit on `master`; [988b472](https://github.com/neovim/neovim/commit/988b472d902e6116353fc2ae605bed32a37e6391) is already outdated and missing several possibly relevant fixup commits.

latest(same):
https://github.com/neovim/neovim/assets/62308020/4ba88f3f-1d57-446f-8343-d48147bb40ac

**Comment by geril2207** [comment]
Actually happens in both alacritty and kitty and caused by `f54806fd7f4c0bae273ffcf8a4598a2d872e5a9e`. For best test you should zoom out a lot.

https://github.com/neovim/neovim/assets/62308020/7cd755bd-5622-48c4-a20c-225eab66ddca

**Comment by clason** [comment]
It's better to bisect on `master`, not the release branch.

This commit was backported from https://github.com/neovim/neovim/pull/24982 @zeertzjq

**Comment by zeertzjq** [comment]
Also you `$TERM` value is wrong. For kitty it should be `xterm-kitty` and for Alacritty it should be `alacritty`.

**Comment by geril2207** [comment]
> I can't understand the comments. Does the bug exist in v0.9.4 or not? If the bug doesn't exist in v0.9.4 why were you bisecting the release branch?

@zeertzjq Firstly, I thought that version 0.9.4 did not have this issue. However, after starting bisect, I discovered that 0.9.4 also has artifacts. My bisect was from release branch, after finding backport commit which caused this issue, i checked master branch and for me https://github.com/neovim/neovim/pull/24982 introduces this one.

**Comment by geril2207** [comment]
@zeertzjq  It's so hard to detect which one, because seems to be more than one commit problem, i thinked testing with a lot of zoom out helps me to detect problem easier, but by another bisect i found that kitty starts flickering on `405bad5e085fb359879646b6fd6fbcddae83eac5` with normal zoom. There are some catches that i found :
1. All terms work fine with <30 visible lines;
2. On `405bad5e085fb359879646b6fd6fbcddae83eac5` kitty starts flickering on 37(i guess between 30 and 40) visible lines, alacritty works fine untill 120 visible lines(i guess from `0c86828`).

**Comment by geril2207** [comment]
Wezterm also has flickering

**Comment by geril2207** [comment]
> Hmm, does `:set notermsync` change anything?
> 
> Also, if the bug starts in kitty in [405bad5](https://github.com/neovim/neovim/commit/405bad5e085fb359879646b6fd6fbcddae83eac5), then it doesn't happen in kitty in v0.9.4?

`notermsync` do nothing, maybe change flickering rate a little.
Have you been able to reproduce this? Maybe i am wrong somewhere?

**Comment by geril2207** [comment]
For me in 0.9.4(after https://github.com/neovim/neovim/pull/24982 which is  actually 0.9.2) it appears on tiny font size(~3, or a lot of zoom out), in both. With normal size(12-18) appears only after https://github.com/neovim/neovim/commit/405bad5e085fb359879646b6fd6fbcddae83eac5.
