### ISSUE TITLE
nvim should tell me when it was built

### ISSUE THREAD

**Issue by gongfarmer** [neovim/neovim#26428]
### Problem

I am often trying to determine the age of the nvim software on my systems to decide whether an old build could be the cause of a problem.
There's no great way to do this, currently.

`nvim --version` gives me a build SHA1 which I can look up in the nvim git history, but this is a pain.
Within nvim, there is `:version` which gives the same information.

Nvim should include a build date in the version information to simplify this common task.

This would be especially valuable for people using the nvim packaged by their OS maintainers.  These are typically very old, but since users only see a release number and SHA1, it is not obvious how old the software actually is.

### Expected behavior

Include a build timestamp (or even just a date) in the version information.

Current:
```
❯ nvim --version
NVIM v0.10.0-dev-1896+g91f57723a-Homebrew
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-91f5772/share/nvim"

Run :checkhealth for more info
```

Expected:
```
❯ nvim --version
NVIM v0.10.0-dev-1896+g91f57723a-Homebrew
Build type: Release
Build time: 2023-12-06T17:59:17Z
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-91f5772/share/nvim"

Run :checkhealth for more info
```

Within nvim, the `:version` command should also include the build timestamp

**Comment by gpanders** [comment]
Including build date/time in the compiled output is an antipattern anyway, as this makes builds [non-reproducible](https://reproducible-builds.org).

**Comment by gongfarmer** [comment]
Good point, the commit timestamp would be more useful than the build time.
For the appimage release builds or the debian builds, there is not much difference really.

This is speaking purely as an nvim user.  Nvim gets packaged and put out there as official appimage releases, as debian packages, brew packages, rpm packages.  For a user who is not following nvim developing closely, the current version information is just not good enough to tell at a glance exactly how current the software is.

**Comment by gongfarmer** [comment]
Even if I stick with the packaged nvim version on my Ubuntu system, it is a development release.
Helpfully, the debian packaged versions do include the compilation command, which includes timestamps that tell me how old the software is:

```
$ nvim --version
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/build/neovim-AMRFck/neovim-0.10.0~ubuntu1+git202304222018-1cb46abff-9b397864c/.deps/usr/include -I/build/neovim-AMRFck/neovim-0.10.0~ubuntu1+git202304222018-1cb46abff-9b397864c/build/src/nvim/auto -I/build/neovim-AMRFck/neovim-0.10.0~ubuntu1+git202304222018-1cb46abff-9b397864c/build/include -I/build/neovim-AMRFck/neovim-0.10.0~ubuntu1+git202304222018-1cb46abff-9b397864c/build/cmake.config -I/build/neovim-AMRFck/neovim-0.10.0~ubuntu1+git202304222018-1cb46abff-9b397864c/src -I/usr/include -I/build/neovim-AMRFck/neovim-0.10.0~ubuntu1+git202304222018-1cb46abff-9b397864c/.deps/usr/include -I/build/neovim-AMRFck/neovim-0.10.0~ubuntu1+git202304222018-1cb46abff-9b397864c/.deps/usr/include -I/build/neovim-AMRFck/neovim-0.10.0~ubuntu1+git202304222018-1cb46abff-9b397864c/.deps/usr/include -I/build/neovim-AMRFck/neovim-0.10.0~ubuntu1+git202304222018-1cb46abff-9b397864c/.deps/usr/include -I/build/neovim-AMRFck/neovim-0.10.0~ubuntu1+git202304222018-1cb46abff-9b397864c/.deps/usr/include -I/build/neovim-AMRFck/neovim-0.10.0~ubuntu1+git202304222018-1cb46abff-9b397864c/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
> Even if I stick with the packaged nvim version on my Ubuntu system, it is a development release.

No it is not! It is outdated, unfortunately (but that is actively being worked on by the maintainer). If that's the issue, use a (stable!) PPA, or download an appimage from Github.

If you don't know your way around git DO NOT USE NIGHTLY BUILDS, period. If you do, the information we show is meaningful (and in fact the only meaningful information). Nightlies are meant for testing and helping find and fix errors, not for production use. 

To be clear:

> but have received the advice that "nvim development moves fast, so you should use the nightlies for now

I do not know where you got the advice from, but it is not _our_ advice -- quite the opposite. Feel free to point these people to this issue.
