### ISSUE TITLE
inccommand breaks `:s` when the range is `'[,']`.

### ISSUE THREAD

**Issue by rafikdraoui** [neovim/neovim#26439]
### Problem

When `'inccommand'` is defined (either 'split' or 'nosplit'), it interacts badly with the `:substitute` command when the range is `'[,']`.

For example, if the marks range across the whole buffer, not all matches will be replaced.

The command `'[,']s/pattern/string/` is used by plugins like https://github.com/svermeulen/vim-subversive and https://github.com/gbprod/substitute.nvim to implement a "substitute over range" action.

### Steps to reproduce

With the following content in `file.py`:

<details>

```python
def hello01():
    return "world"


def hello02():
    return "world"


def hello03():
    return "world"


def hello04():
    return "world"


def hello05():
    return "world"


def hello06():
    return "world"


def hello07():
    return "world"


def hello08():
    return "world"


def hello09():
    return "world"


def hello10():
    return "world"


def hello11():
    return "world"


def hello12():
    return "world"


def hello13():
    return "world"


def hello14():
    return "world"


def hello15():
    return "world"


def hello16():
    return "world"
```

</details>

```
$ nvim --clean file.py
:onoremap ie :exec "normal! ggVG"<cr>
yie
:marks  " (1)
:'[,']s/def/DEF/
:marks  " (2)
```

We see that only the first few instances of `def` were replaced by `DEF`.

Here is what the `'[` and `']` marks look like at (1):

```
[      1    0 def hello01():
]     62 2147483647 return "world"
```

Here is what the `'[` and `']` marks look like at (2):

```
[      1    0 DEF hello01():
]     45    0 DEF hello12()
```

It looks like the marks are modified by `'inccommand'` during the execution of the `:substitute` command.

I suspect that the values at (2) (and thus the number of substitutions that end up being made) might vary based on what's actually visible in the window. If the 62 lines of `file.py` all fits within your terminal screen, you'll likely need to add more lines to it to reproduce the issue.

The problem doesn't happen when `'inccommand'` is empty.

### Expected behavior

The substitutions should be made across the whole range that is specified for the `:s` command.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1777+g3198598e6

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

Build from repo

**Comment by zeertzjq** [comment]
It seems that undoing a change moves `'[` and `']` marks.

**Comment by rafikdraoui** [comment]
Thank you for the quick fix!
