### ISSUE TITLE
vim.iter: flat() (flatten), flatMap()

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#26454]
### Problem

vim.iter doesn't have a "flatten" pipeline stage.

For reference, see `flat()` and `flatMap()` in javascript:

- review tradeoffs in https://news.ycombinator.com/item?id=29809977
- https://www.wisdomgeek.com/development/web-development/javascript/flatten-arrays-in-vanilla-javascript-with-flat-and-flatmap/

### Expected behavior

Introduce new pipeline stage(s) in `vim.iter`

```
Iter:flat(depth: number)
Iter:flatMap(depth: number, fn: function)
```

We probably don't need `flatMap()`, it's equivalent to `:map(fn):flat(1)`

### Related

- https://github.com/neovim/neovim/issues/24572

**Comment by OscarCreator** [comment]
Should this not be closed?
