### ISSUE TITLE
`:colorscheme vim`  sets no cterm highlight for `Visual`

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#26468]
### Problem

`:colorscheme vim`  sets wrong cterm highlight for `Visual`

### Steps to reproduce

1. Run `nvim --clean`
2. Run `:colorscheme vim`
3. Run `:hi Visual`
4. No cterm highlight attributes are shown

### Expected behavior

`Visual` should have cterm highlight attributes, as it was present in both Nvim v0.9.4 and Vim (albeit different).

### Neovim version (nvim -v)

v0.10.0-dev-1793+g808fbe67a

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by echasnovski** [comment]
Hmm... It was literally a copy paste from 'src/nvim/highlight_group.c': [here](https://github.com/neovim/neovim/blob/17f3a3ae31d91944a5a4e56aa743745cff7fdf07/src/nvim/highlight_group.c#L342) and [here](https://github.com/neovim/neovim/blob/17f3a3ae31d91944a5a4e56aa743745cff7fdf07/src/nvim/highlight_group.c#L384) `Visual` doesn't have `cterm`. As it is later applied [depending on the terminal capabilities](https://github.com/neovim/neovim/blob/17f3a3ae31d91944a5a4e56aa743745cff7fdf07/src/nvim/highlight_group.c#L671-L673). I guess it better to add `cterm=NONE ctermbg=LightGrey` / `cterm=NONE ctermbg=DarkGrey` directly in the 'runtime/colors/vim.vim' then.
