### ISSUE TITLE
windows save issue

### ISSUE THREAD

**Issue by carlosdcastillo** [neovim/neovim#2646]
In the windows version on appveyor, when you do :w on a file called filename.ext it deletes the current file filename.ext, opens a window with a file called filename.ext~ with the new contents and renames that to filename.ext. 

This isn't what happens on OS X, in OS X the file in the current window is never deleted, just overwritten I presume.

**Comment by equalsraf** [comment]
Seeing something similar, trying to trace this

Lets say I open Neovim and insert some content into the empty buffer
```
2015/05/14 10:58:18 [info @ os_open:234] 34 - [3] Unknown system error 'Z:\home\raf\Code\neovim\build-mingw\.swp'
```
Ignore the "Unknown system error", it means errno is clear. `os_open()` is called to open `.swp` and it succeeds. 

Now If I  call `:w somefile.ext`

```
2015/05/14 11:00:34 [info @ os_remove:438] 34 - -4058 no such file or directory '.somefile.ext.swp' '.somefile.ext.swp'  [0]
2015/05/14 11:00:34 [info @ ml_setname:445] 34 - .somefile.ext.swp
2015/05/14 11:00:34 [info @ os_open:234] 34 - [-4048] operation not permitted '.somefile.ext.swp'
2015/05/14 11:00:35 [info @ os_open:234] 34 - [3] Unknown system error 'Z:\home\raf\Code\neovim\build-mingw\somefile.ext'
```

I also get an error message  `E301: Oops, lost the swap file`. The first call to `os_remove()` doesnt seem to make much sense, the file was not created yet, but maybe its normal.

The strange bit is that while the call to `os_open()` seems to fail to create `.somefile.ext.swp` the file is actually there. The `.swp` however is not there.

**Comment by equalsraf** [comment]
More accurately there is a rename going on, but the call to `os_open()` fails anyway.

**Comment by equalsraf** [comment]
This looks fixed on master.
