### ISSUE TITLE
[builtin-terminal] Letters chopped when line numbers are turned on.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2647]
The line numbers columns push the text of the terminal to the right, causing some of the text to be chopped off.

**Comment by tarruda** [comment]
This is a consequence of resizing the terminal(which is what happens when the number column is added) because we don't support reflow. I'm closing this since it's the same as #2514

**Comment by trusktr** [comment]
@tarruda Could a temporary solution be to resize the terminal width to match `windowWidth - ( numberColumnWidth + gutterColumnsWidth )`?

**Comment by trusktr** [comment]
@justinmk Can you re-open this?

In reality, I would like to [keep line numbers on](https://github.com/neovim/neovim/issues/7398) while in a terminal buffer, and the only reason I turn it off is because of the bug in this issue.

@tarruda Said this is the same as #2514, but in reality it is not quite the same:

1. The other issue is about reflow.
1. This issue is about resizing the terminal so that the terminal size plus any gutters will equal the window size. This doesn't require reflow, it just requires resize, and reflow can be something added later (and it is also much more ideal of course, but for the time being resizing the terminal would at least solve this issue)

**Comment by justinmk** [comment]
@trusktr Please search existing open issues.

**Comment by trusktr** [comment]
I did, maybe I missed it. But from the looks of other issues, looks like this will probably be fixed by 0.3.0.
