### ISSUE TITLE
Add shortcuts for different languages for the builtin markdown treesitter

### ISSUE THREAD

**Issue by dmtrKovalenko** [neovim/neovim#26474]
### Problem

The current markdown parser with treesitter for things like lsp info is amazing, but it always fails to add syntax highlighting if the language name is not full but shortcut. 

e.g. when you put the \```js instead of \```javascript you'll get something like this
<img width="1148" alt="image" src="https://github.com/neovim/neovim/assets/16926049/8b0750df-c8af-4b47-97ef-3f9bd0498dd7">

### Expected behavior

Add the most popular shorthands for the languages like 

- ts -> typescript
- tsx -> typescript react 
- js -> javascript
- jsx -> javascript react

### Version
NVIM v0.10.0-dev-1793+g808fbe67a
Build type: RelWithDebInfo
LuaJIT 2.1.1700008891

**Comment by clason** [comment]
Please share more details, like Neovim version, parsers etc., and reproducing steps (the template is there for a reason).

We will not add custom shorthands (that does not scale) but already support filetype lookups.

**Comment by dmtrKovalenko** [comment]
OK I failed to get the actual version (I have 2 of them) my actual version is and it fails to highlight the \```js but perfectly highlights \```javascipt


```
NVIM v0.10.0-dev-1793+g808fbe67a
Build type: RelWithDebInfo
LuaJIT 2.1.1700008891
```
