### ISSUE TITLE
setting `syntax spell` in lua config is being overridden  

### ISSUE THREAD

**Issue by buschco** [neovim/neovim#26489]
### Problem

https://github.com/neovim/neovim/assets/14929556/6858a7be-76aa-4341-95ed-960b80b878a1

### Steps to reproduce

```lua
-- my_issue.lua
for name, url in pairs{
  -- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
  -- some_plugin = 'https://github.com/author/plugin.nvim'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
vim.cmd([[ syntax spell toplevel ]])
vim.cmd([[ syntax spell ]])
```
1. `nvim --clean -u my_issue.lua test.c`
2. `:syntax spell` from lua config prints out `toplevel`
3. executing `:syntax spell` prints out `default`

### Expected behavior

executing `:syntax spell` should print `toplevel`

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

-

### Operating system/version

macOS 14.1.2 (23B92)

### Terminal name/version

iTerm 2 / 3.4.21

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by clason** [comment]
Please test Vim. I'm not sure your expectation is correct, as these are "syntax local" options to be set in a syntax file, not "global" options you can set in your vimrc. (Same as `syntax keyword` etc.)

**Comment by Sam-programs** [comment]
Vim prints `syntax spell toplevel` but after openning other files it gets reset back to `default`

note:`nvim --clean -u my_issue.lua test.c`
`--clean` doesn't load `my_issue.lua` but removing it doesn't change the behaviour

Neovim is aware of the current buffer having syntax spell be applied to but doesn't keep the setting after the config is loaded?
```vim
" issue.vim
echo bufnr()
ls
syntax spell toplevel
syntax spell
```
Using `nvim -u issue.vim test.c`

**Comment by Sam-programs** [comment]
Never mind a plugin is reseting `syntax spell` setting `noloadplugins` fixes the issue
