### ISSUE TITLE
Performance issue for nvim

### ISSUE THREAD

**Issue by Marskey** [neovim/neovim#26481]
### Problem

After using Neovim for about 3 days, I noticed a significant decrease in performance. Despite closing all 63 buffers and stopping all LSP clients, the issue persisted. I am unsure of the cause. However, upon exiting Neovim and reopening it, the performance problem disappeared

### Steps to reproduce

[sample.log](https://github.com/neovim/neovim/files/13622395/sample.log)

### Expected behavior

none

### Neovim version (nvim -v)

v0.9.4

### Vim (not Nvim) behaves the same?

no, problemly

### Operating system/version

macOS  14.0

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

tmux-256color

### Installation

homebrew

**Comment by glepnir** [comment]
try head version you can install it by using `brew install neovim --HEAD` or build neovim in your local.

**Comment by clason** [comment]
That's very little to work on. Please try reproducing (ideally with a minimal example) and adding context here.

**Comment by Marskey** [comment]
closed until I find a way to reproduct
