### ISSUE TITLE
~/.config/nvim/init.lua does not work

### ISSUE THREAD

**Issue by bojanstef** [neovim/neovim#26480]
### Problem

My autoload is not working. Every time I start nvim I have to source init.lua and every submodule if I want to get their settings enabled. 

I had a much larger config tree but I removed everything to isolate the problem and now I only have the `init.lua` file in my nvim config:
```
cat ~/.config/nvim/init.lua
print("Hello")
```

### Steps to reproduce

`nvim`

### Expected behavior

I expect "Hello" to be printed 

### Neovim version (nvim -v)

v0.9.4

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 14.1.2

### Terminal name/version

Alacritty 0.12.3 (5efb069)

### $TERM environment variable

tmux-256color

### Installation

brew install nvim

**Comment by zeertzjq** [comment]
Does `:checkhealth` show any errors?

**Comment by bojanstef** [comment]
```
:checkhealth
- WARNING Missing user config file: $HOME/.config/nvim/init.vim
  - ADVICE:
    - :help init.vim
```
but that shouldn't be an issue since `init.lua` is supposed to replace `init.vim`

`:echo $MYVIMRC` returns blank

**Comment by zeertzjq** [comment]
Hmm, that's an unexpanded `$HOME`. Maybe you have have a literal unexpanded `$HOME` in `$XDG_CONFIG_HOME` environment variables.

**Comment by bojanstef** [comment]
Thanks for pointing that out. I didn't realize you need to use single quotes to expand variables in shell. 
"Hello" now shows up on my screen.

I still have an issue that it seems that Lazy nor map leader are updated by my init.lua

```
print("Hello init.lua")

-- https://github.com/folke/lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- [[ Basic Keymaps ]]
-- Set <space> as the leader key 
-- See `:help mapleader`
-- NOTE: - Must happen before plugins are required (otherwise wrong leader will be used)
vim.g.mapleader = " "
vim.g.maplocalleader = " "

package.loaded["lazy"] = nil
require("lazy").setup({
	{
		'nvim-telescope/telescope.nvim', tag = '0.1.5',
		-- or                              , branch = '0.1.x',
		dependencies = { 'nvim-lua/plenary.nvim' }
	},
	{ "catppuccin/nvim", name = "catppuccin", priority = 1000 },
	{
		"nvim-treesitter/nvim-treesitter",
		build = function()
			require("nvim-treesitter.install").update({ with_sync = true })()
		end,
	},
	{"nvim-treesitter/playground"},
	{"mbbill/undotree"},
	{"tpope/vim-fugitive"},
	{'VonHeikemen/lsp-zero.nvim', branch = 'v3.x'},
	{'neovim/nvim-lspconfig'},
	{'hrsh7th/cmp-nvim-lsp'},
	{'hrsh7th/nvim-cmp'},
	{'L3MON4D3/LuaSnip'},

})

```

**Comment by clason** [comment]
Probably the same issue with `XDG_DATA_DIR`.

**Comment by bojanstef** [comment]
`$XDG_DATA_HOME` is not set for me

**Comment by clason** [comment]
What does `:echo stdpath('data')` say then?

**Comment by bojanstef** [comment]
`/Users/bojanstef/.local/share/nvim`

**Comment by clason** [comment]
and the "Hello" is printed?

**Comment by bojanstef** [comment]
Yes

**Comment by bojanstef** [comment]
Here's my entire `~/.zshrc` if that helps
```shell
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Programmatically set zsh preferences
source $ZSH/oh-my-zsh.sh

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="powerlevel10k/powerlevel10k"

# Set preferred editor
export EDITOR='nvim'

# You may need to manually set your language environment
export LANG=en_US.UTF-8 

# Set home base config directory
export XDG_CONFIG_HOME="$HOME/.config"

# Disable case sensitive completion
CASE_SENSITIVE="false"

# Programmatically set System Preferences
source $HOME/.config/macos/.macos

# Aliases 

# Delete derived data
alias ddd="rm -rf ~/Library/Developer/Xcode/DerivedData"
# Neovim mistakes
alias vim="nvim"

# Automatically added
export NVM_DIR="$XDG_CONFIG_HOME/nvm/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

**Comment by bojanstef** [comment]
The issue was that `$XDG_CONFIG_HOME` was not expanding `$HOME` due to the use of single-quotes `'` instead of double-quotes `"` in the export. 

It looks like I just wasn't setting the theme like the docs state: https://github.com/catppuccin/nvim#usage
`vim.cmd.colorscheme "catppuccin"`

Theme, mapleader as <Space>, and Lazy are all working for me. 
Thank you @zeertzjq and @clason
