### ISSUE TITLE
WinResized event not triggering when executing lua script via `-l`

### ISSUE THREAD

**Issue by carbon-steel** [neovim/neovim#26498]
### Problem

The `WinResized` event does not trigger when executing a lua script through neovim's commandline interface (via the `-l` flag).

### Steps to reproduce

Example file: `winresized.lua`
```lua
vim.api.nvim_create_autocmd({"WinResized"}, {
    callback = function ()
        print("WinResized")
    end
})

vim.cmd.wincmd('s')
```

Run: `nvim --clean -l winresized.lua`

Observed Output: Nothing gets printed

### Expected behavior

We should see "WinResized" printed since the `winresized.lua` script created the autocmd to do so when the `WinResized` event occurs. The split command at the end of the script should have triggered the `WinResized` event.

To show a related example of how `WinResized` is supposed to work, here is the same thing with the `WinEnter` event (which does work):

winenter.lua:
```lua
vim.api.nvim_create_autocmd({"WinEnter"}, {
    callback = function ()
        print("WinEnter")
    end
})

vim.cmd.wincmd('s')
```

Run: `nvim --clean -l winenter.lua`
Output: "WinEnter" gets printed

### Neovim version (nvim -v)

v0.10.0-dev-1807+g096211a87

### Vim (not Nvim) behaves the same?

Vim does not have the `WinResized` event

### Operating system/version

Fedora

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by zeertzjq** [comment]
```
							*WinResized-event*
The |WinResized| event is triggered after updating the display, several
windows may have changed size then.  A list of the IDs of windows that changed
since last time is provided in the v:event.windows variable, for example:
	[1003, 1006]
```

The display is not updated when using `-l`, so `WinResized` is never triggered.
