### ISSUE TITLE
Strange colors in the newest nightly that was dropped 20 hours ago.

### ISSUE THREAD

**Issue by leet0rz** [neovim/neovim#26496]
### Problem

Syntax highlighting seems off in the newest release.

### Steps to reproduce

Install nightly NVIM v0.10.0-dev-1801+g2ebd328a7
Try to add highlighting with treesitter or lua-language-server, they are both not as before and weird/bland looking.

### Expected behavior

For the colors to match as they used to before the newest release.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1801+g2ebd328a7

### Vim (not Nvim) behaves the same?

Yes, same issue. version 9.0

### Operating system/version

Version	10.0.19044 Build 19044

### Terminal name/version

nwt Version: 1.19.231010001-preview

### $TERM environment variable

unsure about this one

### Installation

msi from repo

**Comment by zeertzjq** [comment]
1. What version were you previously on?
2. The steps to reproduce are too vague.

**Comment by wookayin** [comment]
At least need a screenshot.

Your issue might be just #26378.

**Comment by clason** [comment]
This is the new default colorscheme and very much intended (although treesitter and LSP groups have yet to be adapted; this is already tracked in an issue).

**Comment by leet0rz** [comment]
> 1. What version were you previously on?
> 
>     2. The steps to reproduce are too vague.

the nightly before the one I posted.
I am sure you could see the same different if you install the stable version now then switch over to the newest nightly and try to add treesitter syntax highlighting. Those are all the steps required to see a difference. 

[Before](https://camo.githubusercontent.com/b3bcb4c26e2f26acee5265a9496b3856ec68faa856caf2cc0a7ee6c76ad3916f/68747470733a2f2f692e696d6775722e636f6d2f55306451476e7a2e706e67)
[After](https://i.imgur.com/sX3fJG6.png)

**Comment by leet0rz** [comment]
> This is the new default colorscheme and very much intended (although treesitter and LSP groups have yet to be adapted; this is already tracked in an issue).


I am not referring to the default colorscheme, I know the new one but there is a change in the syntax highlighting as well. Might be an unintended side-effect.

**Comment by clason** [comment]
As I said, this is ongoing (and already tracked) work. Pre-releases are expected to have regressions while important large-scale work is carried out.

**Comment by gpanders** [comment]
Is it possible that `'termguicolors'` is being enabled when it shouldn't be? @leet0rz you put "nwt" as your terminal in the issue, but I've never heard of it. Does it support truecolor? What does `:set termguicolors?` show? If you add `set notermguicolors` to your init.vim/init.lua, does it resolve the issue?

**Comment by leet0rz** [comment]
> As I said, this is ongoing (and already tracked) work. Pre-releases are expected to have regressions while important large-scale work is carried out.

That is how nightly works and I expect that but you should also expect for these kinds of things to be reported by people who use nightly.
