### ISSUE TITLE
vim.cmd can be repeat by `@:`

### ISSUE THREAD

**Issue by gh-liu** [neovim/neovim#26503]
### Problem

Run `vim.cmd.commad()` in a lua script, the `command` can not be repeated by `@:`.

### Expected behavior

`vim.cmd.commad()` support repeat the command by `@:` optional.

```lua
-- maybe like this
vim.cmd.commad({repeatable=true})
```

**Comment by wookayin** [comment]
Is this referring to a bug? If so, please write a more precise reproducible example using the bug report template.

```
:lua vim.cmd.command()
```
and then `@:` works for me OK. (It runs `:command` again)

**Comment by Sam-programs** [comment]
@wookayin what gets repeated is `lua vim.cmd.command` not `command` u can check if with `registers :`
and here is a repro
```lua
if did_run then
   print('you resourced')
   return
end
did_run = true
vim.cmd.command()
```
Source this file and `:so` becomes the last command.

**Comment by wookayin** [comment]
```
							*@:*
@:			Repeat last command-line [count] times.
```

That's what exactly `@:` is supposed to do -- to repeat what was typed in the "command line" (`:`), in your example `:so`.

**Comment by gh-liu** [comment]
> you could save the command into the register explicitly using `vim.fn.setreg(":", command_string)`.

`:h registers` says the `:` register is a read-only register.

**Comment by gh-liu** [comment]
> using `vim.api.nvim_feedkeys()` would be another option.

I have tried this, it did not work as expected.

```lua
-- script.lua
local cr = vim.api.nvim_replace_termcodes("<cr>", true, false, true)
vim.api.nvim_feedkeys(":ls" .. cr, "n", false)
````
Source this file and `:so script.lua` still is the content of `:` register.

**Comment by Sam-programs** [comment]
`'t'` mode works for feedkeys

**Comment by gh-liu** [comment]
> `'t'` mode works for feedkeys.

Thanks, it works.
