### ISSUE TITLE
[New colorscheme] winbar highlights link to statusline

### ISSUE THREAD

**Issue by geril2207** [neovim/neovim#26502]
### Problem

The `WinBar` and `WinBarNC` highlight groups are now linked to `StatusLine` and `StatusLineNC` after new colorscheme refactoring. Can I change the `StatusLine/NC` highlight without affecting `WinBar` and `WinBarNC`(what should we do from plugin)? What are your thoughts on that? I believe there are currently some issues in other plugins because of this, for example, https://github.com/nvim-tree/nvim-tree.lua/issues/2582. Additionally, colorscheme plugins should handle `WinBar` and `WinBarNC`(not a big deal). I don't think it should have the same background as the statusline; what do you think?

### Steps to reproduce

Actually this is a question, i dont think you need to reproduce smth.

### Expected behavior

I should have make it question, but I feel that it does not get answer :)

### Neovim version (nvim -v)

latest master

### Vim (not Nvim) behaves the same?

na

### Operating system/version

Arch

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

from source

**Comment by wookayin** [comment]
```
❯❯❯ nvim-0.9.4 --clean --headless -c 'hi WinBar' -c q

WinBar         xxx cterm=bold gui=bold


❯❯❯ nvim --clean --headless -c 'hi WinBar' -c q 

WinBar         xxx links to StatusLine


❯❯❯ nvim --clean --headless -c 'hi StatusLine' -c q 

StatusLine     xxx ctermfg=251 ctermbg=232 guifg=NvimLightGrey3 guibg=NvimDarkGrey1
```

You can do `highlight WinBar ctermfg=NONE ctermbg=NONE guifg=NONE guibg=NONE cterm=bold gui=bold` to reset to the old defaults in your config or colorscheme. I think this is just a matter of user config or plugins should adopt to the new colorscheme change. See also #26378 and #26369.

**Comment by geril2207** [comment]
Yeah, thanks, agree with this for default theme, but for plugins and themes it provides a little of mess.
