### ISSUE TITLE
Inlay Hints not drawn once they are provided

### ISSUE THREAD

**Issue by jalil-salame** [neovim/neovim#26511]
### Problem

When enabling `inlay_hints` on `LspAttach`, the hints are not shown on text already on screen. Scrolling and revealing more text does show inlay hints in the "new" text. Toggling inlay hints on and off fixes the "stuck" lines and show inlay hints there too. If the file is small enough and you scroll through all of it/can see all of it, no inlay hints will be displayed.

Basically any text seen between `LspAttach` being fired and the lsp server being ready to provide hints causes the "seen" text to not show inlay hints until they are toggled. My assumption is that some caching is being done, but before the lsp is ready to send hints it says there are no hints. Then, once it is ready, this cache is not invalidated.

### Steps to reproduce

<details><summary><code>minimal_init.lua</code></summary>

```lua
local pattern = 'rust'
local cmd = {'rust-analyzer'}
local root_markers = {'.git', '.editorconfig', 'Cargo.toml'}
local settings = vim.empty_dict()


vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(args)
    local bufnr = args.buf
    local client = vim.lsp.get_client_by_id(args.data.client_id)
    if client.server_capabilities.inlayHintProvider then
      vim.lsp.inlay_hint.enable(bufnr, true)
    end
  end,
})


vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'bugged-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```

</details>

<details><summary>Asciicast recording of the bug</summary>

[![asciicast of bug report](https://asciinema.org/a/626154.svg)](https://asciinema.org/a/626154)

</details>

1. Open a rust project (may work with other servers providing inlay hints?) using `minimal_init.lua` (`nvim --clean -u minimal_init.lua src/main.rs`)
2. Wait for `rust-analyzer` to finish starting
3. Verify that everything on screen which should have inlay hints doesn't
4. Scroll down to see that uncovered text does have inlay hints
5. Toggle inlay hints (`:lua vim.lsp.inlay_hint.enable(0, false)`, `:lua vim.lsp.inlay_hint.enable(0, true)`)
6. Verify that inlay hints are now properly shown

### Expected behavior

Inlay hints should be drawn on displayed text once they become available.

My guess is that the same event that causes the syntax highlighting to be redrawn (see asciicast recording at 18s), should also be used to re-request inlay hints (invalidate hint cache(?)).

### Neovim version (nvim -v)

NVIM v0.10.0-dev-096211a

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

NixOS 24.05.20231204.2c7f3c0

### Terminal name/version

wezterm 20230712-072601-f4abf8fd

### $TERM environment variable

xterm-256color

### Installation

nix nix-community/neovim-nightly-overlay

**Comment by snaggen** [comment]
Tested with todays nightly and it is still there. 

This issue creates a quite confusing behavior, basically rendering it unusable for rust development where inlay hints are quite important.

**Comment by Spxg** [comment]
Try this: `https://www.reddit.com/r/neovim/comments/17889r8/rust_show_inlay_hint_with_native_lsp/`

**Comment by snaggen** [comment]
Nice trick, but not sure how to hook that in to the rustaceanvim plugin, so I will probably wait until they fix this issue properly.

**Comment by glepnir** [comment]
I add this request in lspconfig before see https://github.com/neovim/nvim-lspconfig/pull/2658 so you can create  a handler to check rust analyzer status then enable inalyhint. nothing to fix here.

**Comment by justinmk** [comment]
is this server-specific?

**Comment by jalil-salame** [comment]
> is this server-specific? 

I don't know, I only have experience with rust's and latex's lsp, and latex has other issues.

**Comment by snaggen** [comment]
No, it's not server specific. Had to apply same workaround for jdtls.

**Comment by snaggen** [comment]
What I don't get is that this is closed with , not planned, but the lsp-config issue doesn't really aim to solve this, it seems to be about just enabling this workaround.
So, are we happy with this broken behavior by default? Needing to add this workaround to any lsp that needs it, and first experience this bug, and google it to figure out that the wo is needed.

I don't know where in the stack the responsibility for this really belongs, but it feels wrong to close this bug without an issue somewhere to fix this default behavior.

**Comment by glepnir** [comment]
Each server's initialization preparation time is different. There is a known issue https://github.com/rust-lang/rust-analyzer/issues/14258 that rust-analyzer starts slowly. Because it requires a lot of preparation. For some fast-start servers, the server is already ready when on_attach is called. lsp spec has no server status request. I once raised an issue https://github.com/microsoft/language-server-protocol/issues/1764 hoping to add a standard to send a reminder to the client when the server is ready. But Microsoft wants clients to wait. This is kind of bad because you need to constantly poll the server status. Fortunately, some servers provide custom status notify such as rust anaylyzer.  lspconfig is just a basic server configuration collector.I don't know if you are satisfied with this answer.   

 happy coding with neovim

**Comment by jalil-salame** [comment]
Thanks for clarifying this c:

**Comment by snaggen** [comment]
But then, wouldn't the real fix be to add a status event, to Neovim, then have lsp-config hook that up for servers that have support for status evens (both rust-analyzer and jdtls have that). 
Then if server status done is sent after On Attach, re-initialize stuff like inlay hints.

**Comment by glepnir** [comment]
we don't know what time server is ready for request.

**Comment by clason** [comment]
> I don't know where in the stack the responsibility for this really belongs

In this case, rustacean.nvim. The core LSP client is -- very intentionally -- server agnostic, so there will be **no special treatments**. This is different for a server-specific plugin that can handle all manner of off-spec idiosyncrasies. This includes unusually slow startup.
