### ISSUE TITLE
:checkhealth without opening a tabpage

### ISSUE THREAD

**Issue by ndavd** [neovim/neovim#26517]
### Problem

I don't use tabs ever in my setup. When I check an help page it opens a window. Everything either opens a new window or a new floating window. Currently `:checkhealth` seems to be the only place that opens tabs

### Expected behavior

Opening in a new window or at least give an option to specify how it should open.

**Comment by paulodiovani** [comment]
I created a new command to open the `checkhealth` in an unlisted window, similar to what `help` does.

```vim
" open checkhealth in an unlisted window above
command! -nargs=? -complete=checkhealth Checkhealth above checkhealth <args> | setlocal bufhidden=wipe nomodifiable nobuflisted noswapfile nocursorline nocursorcolumn nonumber norelativenumber noruler nolist noshowmode noshowcmd | file <args>\ health
```

This could be default behavior of the command.
