### ISSUE TITLE
Default color scheme is weird when running in tux

### ISSUE THREAD

**Issue by smithshelke** [neovim/neovim#26529]
### Problem

![Screenshot 2023-12-13 at 1 05 07 AM](https://github.com/neovim/neovim/assets/31080954/890bb12e-9671-43fd-afc9-ffc9d6c7fb9c)

### Steps to reproduce

tmux
nvim --clean

### Expected behavior

color scheme should be same as when nvim is opened from outside/without tmux

### Neovim version (nvim -v)

v0.10.0-dev-1816+g2d33a766a

### Vim (not Nvim) behaves the same?

no, vim has the default light theme

### Operating system/version

macOS 14.0 (23A344)

### Terminal name/version

iterm2

### $TERM environment variable

screen-256color

### Installation

by extracting, tar xzvf nvim-macos.tar.gz

**Comment by smithshelke** [comment]
> The screenshot wasn't uploaded successfully.

@zeertzjq uploaded the correct image

**Comment by smithshelke** [comment]
theres some issue with the background color of nvim and my terminal. Will get back once identify if the issue is with my terminal or its nvim

**Comment by veeson41** [comment]
did the problem get resolved @smithshelke
Think I'm having the same issue.

**Comment by jkhsjdhjs** [comment]
@veeson41 I also thought I might have the same issue at first, but it turns out that nvim simply changed the default colorscheme. The old colorscheme can be restored via `:colorscheme vim`. This can also be read in the news `:h news`.
