### ISSUE TITLE
How do you contribute to the Github Wiki

### ISSUE THREAD

**Issue by jalil-salame** [neovim/neovim#26521]
### Problem

I was looking at the installation page and found a method I would like to add, but there is no obvious way to contribute to the wiki:

- [GitHub doesn't support PRs to the Wiki](https://stackoverflow.com/questions/10642928/how-can-i-make-a-pull-request-for-a-wiki-page-on-github)
- [CONTRIBUTING.md doesn't make any mentions](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md)
- Searching for issues and discussions about it doesn't yield any promising results (there are a lot of issues that match the wiki filter and they don't seem relevant?) 

### Expected behavior

[CONTRIBUTING.md](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md) should mention the wiki and how to (not?) contribute to it.

In case someone wants to add what I found missing to the wiki it is in [Installing Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim#nix--nixos), nix/nixos should also mention installing from flakes:

<details><summary>Fixed wiki</summary>

## Nix / NixOS

Neovim can be installed with:

```
nix-env -iA nixpkgs.neovim
```

Or alternatively, if you use [flakes](https://nixos.wiki/wiki/Flakes).

```
nix profile install nixpkgs#neovim
```

</details>

**Comment by dundargoc** [comment]
We had to close wiki for contributions due to too much spam.

Thanks. Added it.

**Comment by bfredl** [comment]
Regarding the general question of "How do you contribute to the Github Wiki". we try to move anything of value to documents which is actually part of the repo. so a contribution would be to add stuff to documents which is part of the repo with updated forms of stuff which currently resides in the "wiki".

**Comment by jalil-salame** [comment]
Thanks for the quick reply and clarification!
