### ISSUE TITLE
build: LTO version fatal error

### ISSUE THREAD

**Issue by mystilleef** [neovim/neovim#26558]
### Problem

I get the following error when I trying to build from head. It looks like an LTO version mismatch.

```bash
...
...
lto1: fatal error: bytecode stream in file ‘src/nvim/CMakeFiles/nvim.dir/__/__/test/unit/fixtures/multiqueue.c.o’ generated with LTO version 13.0 instead of the expected 13.1
compilation terminated.
lto-wrapper: fatal error: /usr/bin/cc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
make: *** [Makefile:84: nvim] Error 1
```

I've tried reinstalling and upgrading the build deps on my machine to no avail.

### Steps to reproduce

```bash
gh repo clone neovim/neovim
cd neovim
make distclean; make clean; make CMAKE_BUILD_TYPE=Release && sudo make install
```

### Expected behavior

Build should complete successfully.

### Neovim version (nvim -v)

v0.10.0-dev-1775+g8bb508997

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Fedora Linux 39 (Workstation Edition) x86_64

### Terminal name/version

kitty 0.31

### $TERM environment variable

screen-256color

### Installation

build from repo

**Comment by dundargoc** [comment]
Hmm, I think I've had this happen to me once. Do you happen to have multiple clangs installed? Something like one from homebrew and one from fedora package manager?

**Comment by mystilleef** [comment]
@dundargoc I only have clang from Fedora installed. Just to be sure, I removed `brew` and `nix` from my machine to eliminate conflicts.

**Comment by dundargoc** [comment]
nix is notorious for not having an uninstaller though, so clang from it won't be removed even if you remove nix. Just to make sure, have you confirmed clang from nix isn't present?

**Comment by mystilleef** [comment]
Correct, no clang from `nix` is present.

**Comment by dundargoc** [comment]
Just to be super duper sure, what's the output of `which -a gcc` and `which -a clang`?

**Comment by mystilleef** [comment]
You're right. The gcc and clang being used where in lib/ccache. Once I removed them, the build compiled successfully. Thanks for your help. Closing this issue.

**Comment by lamnguyenx** [comment]
In my case, it was due to the gcc of Anaconda.
I have to run `conda deactivate` to make sure that the installer use default gcc and g++.
