### ISSUE TITLE
Random areas of the editor are highlighted with a cyan background

### ISSUE THREAD

**Issue by yorickpeterse** [neovim/neovim#26556]
### Problem

I'm using nvim `master` from commit 8097b4a725. In the last few days I started noticing random areas of the editor window being highlighted with a cyan background:

![Screenshot from 2023-12-13 16-36-03](https://github.com/neovim/neovim/assets/86065/231e6b68-d17b-4e7a-a762-bf6100288750)

![Screenshot from 2023-12-12 16-32-45](https://github.com/neovim/neovim/assets/86065/3b57e3da-23ae-485c-88e8-667750912cdb)

![image](https://github.com/neovim/neovim/assets/86065/87b16317-4fd2-477e-9b2b-f4500236ba4b)

At first I thought that this may be the highlight group `RedrawDebugClear` as it uses `guibg=NvimLightCyan`, but I don't have `redrawdebug` set to anything. The output of `hi` shows no other highlight group with this particular style.

The problem doesn't happen often and I'm not sure yet how to reproduce it reliably. Sometimes it happens once or twice within e.g. 15 minutes, other times I can go 2-3 hours without it happening. When it does happen, the only way to seemingly get rid of it is to switch tabs a few times (or possibly another action that essentially redraws the entire screen).

### Steps to reproduce

Still trying to figure this out.

### Expected behavior

The highlights don't show up

### Neovim version (nvim -v)

8097b4a725

### Vim (not Nvim) behaves the same?

Uncertain, my config is nvim specific so I can't test it (combined with it only happening every now and then)

### Operating system/version

Arch Linux in a container, Fedora Silverblue host

### Terminal name/version

Ghostty 0.1.0-main+9b81d57c

### $TERM environment variable

xterm-ghostty

### Installation

AUR

**Comment by yorickpeterse** [comment]
To clarify further: the highlights occur in random places, i.e. the sign column, somewhere in the middle of the buffer, etc. There doesn't appear to be a consistent pattern.

**Comment by yorickpeterse** [comment]
It seems I can semi-reliably reproduce this by switching to a different tab, then switching back:

[Screencast from 2023-12-13 16-51-21.webm](https://github.com/neovim/neovim/assets/86065/e1c7b595-5926-484d-be9b-11df19742256)

In this case opening a split seems to "move" the artifact to a different position in the new split, and closing the new split "fixes" it.

I've been trying to reproduce this in GNOME terminal but without any luck thus far. This suggests that Ghostty is either to blame or plays a role in this, though I'm not sure yet which one it is.

**Comment by yorickpeterse** [comment]
A few other data points:

- It seems to only happen when I have at least 3 vertical splits open
- The syntax of the file is irrelevant, as I've had it happen with different type types (e.g. `inko` and `rust`)
- It always appears to happen in the bottom half or so of the screen, though that may just be coincidence

**Comment by yorickpeterse** [comment]
Using `color default` the artifacts appear to not show up. I'm now wondering if perhaps the new default theme is messing things up somehow :thinking:

**Comment by mitchellh** [comment]
I recommend we move this to the Ghostty issue tracker. This is almost certainly an issue with the terminal and not Neovim.

**Comment by yorickpeterse** [comment]
@mitchellh Will do!

**Comment by yorickpeterse** [comment]
Per https://github.com/mitchellh/ghostty/issues/1076 (only available to beta testers), this issue is also happening in iTerm and Kitty:

@yorickpeterse:

> Here is a side by side recording:
> 
> A recording of the entire desktop where the artifact is visible:
> 
> [Screencast from 2023-12-13 17-24-17.webm](https://github.com/mitchellh/ghostty/assets/86065/779b1dd9-6728-4082-9438-b6dfe70f22fe)
> 
> The corresponding asciinema recording:
> 
> [![asciicast](https://asciinema.org/a/ucPT853ULFZDSxsz7M1dBnnqc.svg)](https://asciinema.org/a/ucPT853ULFZDSxsz7M1dBnnqc)
> 
> The artifact is the "E" in cyan on the right-most split on line 401.

@mitchellh:

> I've plucked it from the terminal inspector and its reading that cell as bg `(0, 242, 242)` (in u8). Looking at the SGR stream I think thats supposed to be 242, 242, 242 so the next question is why this is happening... onwards!
> 
> ![CleanShot 2023-12-13 at 14 38 59@2x](https://github.com/mitchellh/ghostty/assets/1299/72ec94ff-1a80-415c-9715-8e81ecc6576b)

@mitchellh:

> Uhhhh, the program is sending `ESC [ 48:2:0:242:242m` followed by `E` so that color is correct as far as I can tell in the stream. I ran this in iTerm2 and I'm seeing the same result:
> 
> ![CleanShot 2023-12-13 at 14 54 57@2x](https://github.com/mitchellh/ghostty/assets/1299/d06313e5-dbf6-47eb-be5e-f9cdfda42585)

@mitchellh:

> Noting also that the cyan `E` shows up in Kitty as well. Either your cast doesn't reproduce the issue or this is a downstream bug, but the terminal stream you gave me, that `E` is supposed to be cyan.

And per Discord:

> Bad news @Yorick Peterse, see latest comment but your "bug" reproduces in Kitty and iTerm2. I also decoded the direct SGR stream from your cast and that "E" should by cyan.
> This doesn't happen in Gnome terminal because Gnome doesn't appear to support RGB fg colors. So its ignoring the sequence. Asciinema also doesn't appear to support direct RGB setting, that's why it doesn't show up there, either.

---

I didn't experience this issue when I was still running on 0.9.4, so I'm guessing a change introduced to nvim since then may play a role here. I searched through my installed plugins for any references to "cyan" or the color code `#00f3f2` (the color shown in this case), but there are no relevant references to the former and no references at all to the latter.

**Comment by yorickpeterse** [comment]
To see if `NvimLightCyan` is to blame I changed its definition in `highlight_group.c` to the equivalent of `#FFAAAA`. The resulting artifacts are still in cyan, so it's not this highlight group somehow messing things up.

Interesting enough, while I can reliably reproduce this issue on my 27" desktop, I can't reproduce it on my 15" laptop at all, even though they run the same version of Ghostty and Neovim.

**Comment by yorickpeterse** [comment]
I can reliably reproduce this as follows, though this requires using my dotfiles (https://github.com/yorickpeterse/dotfiles):

```
git clone https://github.com/inko-lang/inko.git /tmp/inko
cd /tmp/inko
VIMRUNTIME=path/to/neovim/runtime/ path/to/neovim/build/bin/nvim types/src/check.rs types/src/resolve.rs std/src/std/tuple.inko -c 'vsplit | bn' -c 'vsplit | bn' -c tabnew -c tabprev
```

@gpanders suggested trying out the latest commit before the merge of https://github.com/neovim/neovim/pull/26407. This is commit e057b38e7037808b3593fb1035794595b4e4a45e. Using this commit, I'm unable to reproduce the problem. 

Based on this I ran a `git bisect`, and it suggested c651fb30427a3c645b4b1bd8a9b7e767af51e014 is to blame.

@gpanders also suggested disabling the `termsync` option. Using `set notermsync`, I'm unable to reproduce the problem.

**Comment by yorickpeterse** [comment]
In case it's relevant: the background color of my color scheme is `#f2f2f2`, and `#00f2f2` is a cyan color, which is pretty much the color seen in the screenshots. I'll see what happens if I change the background color to something else.

**Comment by yorickpeterse** [comment]
Using `color default`, the artifacts look like this:

![image](https://github.com/neovim/neovim/assets/86065/ec1e74c2-0f9a-421e-a70c-f588366164c0)

The background of `Normal` in this case is `NvimDarkGrey2` or `#1c1d23` according to GIMP. The background color of the artifact is `#001d23`. 

Similarly, if I use `hi Normal guibg=#424669`, then the background color of the artifact is `#004669`.

Based on this it seems the first two digits of the `guibg`/`ctermbg` of `Normal` are overwritten with `00`.

**Comment by yorickpeterse** [comment]
- Calling `:redraw!` does nothing
- Using `Control+L` _does_ clear the artifacts, though new ones may appear right away

**Comment by yorickpeterse** [comment]
I've been trying out https://github.com/neovim/neovim/pull/26565 and thus far am no longer able to reproduce this using `set termsync`. Thanks!
