### ISSUE TITLE
Single-click not working properly with NERDTree

### ISSUE THREAD

**Issue by fungl164** [neovim/neovim#2656]
Hello,

I'm successfully using Using NVIM.0.0.0-alpha+201505131955 on Yosemite OSX without any major issues.  : )

However, it seems the latest version of neovim does not honor NERDTree's setting for single-click file opening when using <code>let NERDTreeMouseMode=3</code> on my .vimrc.

Is there another way to enable this (e.g. single-click file opening)?  Many thanks!

**Comment by justinmk** [comment]
`:help 'mouse'`

**Comment by KonstantinKo** [comment]
I'd appreciate a bit more help on this issue. If you mean by `:help 'mouse'` that a `set mouse=a` needs to exist, that doesn't change it. While 
```
set mouse=a
let g: NERDTreeMouseMode=3
```
in `.vimrc` works fine in vim, neovim seems to ignore it like OP said.

**Comment by adriaanzon** [comment]
@KonstantinKo Are you using urxvt? This was fixed in https://github.com/neovim/neovim/pull/4873 but it doesn't work in urxvt.
