### ISSUE TITLE
nvim tries to create $XDG_DATA_HOME and $XDG_STATE_HOME directories on a read-only filesystem

### ISSUE THREAD

**Issue by plus-or-minus** [neovim/neovim#26562]
### Problem

nvim tries to create XDG directories before they're needed on launch

### Steps to reproduce

On a read-only filesystem

1. Set XDG_DATA_HOME and XDG_STATE_HOME environment variables

```
export XDG_DATA_HOME="$HOME/xdg/data"
export XDG_STATE_HOME="$HOME/xdg/state"
export NVIM_LOG_FILE=/dev/null
```

2. Run nvim

```
$ nvim -i NONE
```

3. An error occurs

```
Error detected while processing /opt/homebrew/Cellar/neovim/0.9.4/share/nvim/runtime/plugin/rplugin.vim[66]..function <SNR>14_LoadRemotePlugins[1]..<S
NR>14_GetManifest[1]..<SNR>14_GetManifestPath:
line   10:
E739: Cannot create directory /root: read-only file system
Press ENTER or type command to continue
```

### Expected behavior

nvim should have a launch flag that allows opening files on a read-only filesystem, without creating any files or directories.

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

no, vim 9.0.2018

### Operating system/version

macOS 14.2

### Terminal name/version

Apple Terminal.app

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by glepnir** [comment]
```
						*$NVIM_RPLUGIN_MANIFEST*
Unless $NVIM_RPLUGIN_MANIFEST is set the manifest will be written to a file
named `rplugin.vim` at:

	Unix  
	  $XDG_DATA_HOME/nvim/ or ~/.local/share/nvim/

	Windows  
	  $LOCALAPPDATA/nvim/ or ~/AppData/Local/nvim/
```
