### ISSUE TITLE
Curly braces matching fails when a curly brace is in a comment

### ISSUE THREAD

**Issue by Victoriam7** [neovim/neovim#26581]
### Problem

Using '%' to jump between curly braces fails along with any curly brace highlighting if there is a curly brace pair in a comment. This occurs both in nvim running as an appimage and in vim installed from the systems package manager. I also tested on a personal laptop running a completely different setup and found the same issue. A reddit comment mentioned a plugin called matchit that should fix the issue, but also claimed it was already integrated into nvim (I double checked and it shows in the plugins directory).

### Steps to reproduce

1. run nvim with no config
2. :syntax on
3. input the following code: 
```c
int
main()
{
        // test { test

}
```
4. put cursor on the final curly brace and press '%'
5. cursor will jump to the curly brace in comments

### Expected behavior

cursor should jump to the opening curly brace of main

### Neovim version (nvim -v)

NVIM v0.9.1 (also tested on v0.9.4)

### Vim (not Nvim) behaves the same?

This behavior is in both vim and neovim

### Operating system/version

CentOS Linux 7

### Terminal name/version

tmux

### $TERM environment variable

screen

### Installation

appimage

**Comment by zeertzjq** [comment]
This should be reported to https://github.com/chrisbra/matchit
