### ISSUE TITLE
Pyright not working at all.

### ISSUE THREAD

**Issue by aabbccddeeffggj** [neovim/neovim#26593]
### Problem

Hi, for some reason Pyright is not working on my neovim at all, all the other LSPs I use are working, it was working and in the same day it stop doing so.

I tested with a minimal configuration, tested with neovim's stable release, tested in neovim nightly, all of these gives me the same output: All the LSPs are working, except by Pyright.

The LSP gets attached with the lsp-config.nvim, but none of its functionality works, the completion I set doesn't work; holding down TAB (the key I choose to toggle on completion + to browse through the options), I lose control over the cursor and have to use my mouse to click on neovim's window to regain it.

Using the minimal_init.lua configuration with any language servers works, except by Pyright, it returns the following:
```
Spawning language server with cmd: `pyright-langserver --stdio` failed. The language server is either not installed, missing from PATH, or not executable.
```
I have `pyright-langserver` in my PATH, I can use this command on a terminal.
I tested the `pyright` on terminal and it worked.

### Steps to reproduce using "nvim -u minimal_init.lua"

```
local pattern = 'python'
local cmd = {'pyright-langserver --stdio'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'.git', '.editorconfig'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'bugged-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```

### Expected behavior

Work.

### Neovim version (nvim -v)

0.9.4

### Language server name/version

pyright 1.1.340

### Operating system/version

Linux 6.6.7-zen1-1-zen x86_64

**Comment by clason** [comment]
> Spawning language server with cmd: `pyright-langserver --stdio` failed. The language server is either not installed, missing from PATH, or not executable.

This tells you exactly what's wrong; there's no bug here.

**Comment by aabbccddeeffggj** [comment]
I see, I thought it was related to neovim internal's system to call the language server.

**Comment by seandewar** [comment]
The command is not parsed using a shell; you probably meant to specify `cmd` as `{"pyright-langserver", "--stdio"}` instead.
