### ISSUE TITLE
change name of `nvim_terminal` autocommand group to `nvim_terminal_builtin`

### ISSUE THREAD

**Issue by jam1015** [neovim/neovim#26597]
### Problem

It is great that you merged [this pr](https://github.com/neovim/neovim/pull/15440) that makes terminals close automatically.

You do this by adding a new autocommand group in 
  
```vimscript
local nvim_terminal_augroup = vim.api.nvim_create_augroup('nvim_terminal', {})
  vim.api.nvim_create_autocmd('BufReadCmd', {
    pattern = 'term://*',
    group = nvim_terminal_augroup,
    desc = 'Treat term:// buffers as terminal buffers',
    nested = true,
    command = "if !exists('b:term_title')|call termopen(matchstr(expand(\"<amatch>\"), '\\c\\mterm://\\%(.\\{-}//\\%(\\d\\+:\\)\\?\\)\\?\\zs.*'), {'cwd': expand(get(matchlist(expand(\"<amatch>\"), '\\c\\mterm://\\(.\\{-}\\)//'), 1, ''))})",
  })
```

### Expected behavior

A better name would be `nvim_terminal_builtin`.  `nvim_terminal` seems likely to be the name of an augroup that a user might make, accidentally clearing the builtin group.

**Comment by zeertzjq** [comment]
There is already `nvim_cmdwin`

**Comment by gpanders** [comment]
Is this hypothetical or is there an actual plugin that is having trouble with this? The `nvim_` prefix is intended to be used as the "internal" namespace for builtin autocommands. We should document that somewhere.

**Comment by jam1015** [comment]
completely hypothetical.  I'm working on a PR for a plugin and one way to work is to check if this autocommand exists by parsing the output of `:au`.  I'm not sure how robust that is though so I'm looking at other solutions.  I want to make the plugin work with/without the addition of this autocommand.  But I get that you might want to close this if the `nvim_` prefix is standard.

**Comment by vurentjie** [comment]
@jam1015 check `:help exists()` e.g:
``` 
group_exists = vim.fn.exists('#nvim_terminal') == 1  
group_autocmd_exists = vim.fn.exists('#nvim_terminal#TermClose') == 1  
```

**Comment by gpanders** [comment]
I don't think there's anything actionable here, so I'm going to close.

This issue can serve as a reference for anyone else with a similar question.
