### ISSUE TITLE
popup menu flick in the completion menu

### ISSUE THREAD

**Issue by SolaWing** [neovim/neovim#2661]
As title says, I noticed the flick in youcompleteme when using nvim in terminal. it also occurs in terminal vim. But this never happen in my MacVim. And after I tested, I found if the time costed by completion is longer than a frame refresh, the flick occurs. And In the vim's complete example function `CompleteMonths`, I used `sleep` to emulated a slow completion, and found the popup menu disappeared first, then UI blocked and wait for completion result, and last, redisplay the popup menu. when the delay time is not so big, it behaves just like a flick.

Though this is not a bug, but the flick is annoying. and it's very unfriend to eyes. I hope this can be fixed.

**Comment by Shougo** [comment]
Yes, it is current completion menu behavior.
You can look it in `edit.c`.

It is no easy solution though.

**Comment by Shougo** [comment]
You should change the title "popup menu flick in youcompleteme" to "popup menu flick in completion menu".

**Comment by SolaWing** [comment]
May we redraw the old completion list before call the completion function which maybe block?

**Comment by Shougo** [comment]
Well, possible solution.

* Redraw old popup menu
* UI blocked and wait for completion result
* Clear popup menu
* Redraw new popup menu

But it changes current completion behavior.
Users see old popup menu in the blocking.

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/issues/2674

**Comment by roxma** [comment]
It's still flickering when pressing `<c-n>`, `<c-p>` at a long popup menu
