### ISSUE TITLE
Checking reg_executing() inside :normal does not always yield the correct result

### ISSUE THREAD

**Issue by TheBlob42** [neovim/neovim#26612]
### Problem

To check inside `vim.on_key` if we are currently running a macro (and changing behavior or similar) we can use `vim.fn.reg_executing`. This works when were replaying the macro using `@`. If we select multiple lines and execute the macro using `:normal @` this check fails on every "even" line.

### Steps to reproduce

For the reproduction use the following `minimal.lua` file:

```lua
vim.on_key(function(c)
    if c ~= 'x' then
        return
    end

    if vim.fn.reg_executing() ~= '' then
        print('Macro execution')
    else
        print('Regular execution')
    end
end, 0)
```

The idea is whenever we press the character `x` (could be any other one) to log if we are currently executing a register or not.

- open nvim with `nvim --clean -u minimal.lua`
- start recording a macro and writing some text including an `x`
    - e.g. `qqotext<ESC>q`
- check `:messages` to see that "Regular execution" was printed
- execute the macro using `@q`
- check `:messages` to see that "Macro execution" was printed
- now select both lines using `V` and execute the macro using `:normal @q`

The output should be two times "Macro exectution", but it is "Macro executed\nRegular execution" instead

![macro_issue](https://github.com/neovim/neovim/assets/6849129/8eed7a6f-bfb2-486d-a9fa-adad43b8f68e)

### Expected behavior

The `vim.fn.reg_executing()` function should always return the correct register. Also when used via `:normal`.

### Neovim version (nvim -v)

v0.10.0-dev-dc9f7b8

### Vim (not Nvim) behaves the same?

not applicable (no vim.on_key function)

### Operating system/version

Pop!_OS 22.04 LTS

### Terminal name/version

kitty 0.29.1

### $TERM environment variable

xterm-kitty

### Installation

appimage

**Comment by zeertzjq** [comment]
Simpler steps to reproduce:
```vim
call setline(1, range(10))
let g:log = []
nnoremap s <Cmd>let g:log += [reg_executing()]<CR>
let @r = 's'
call feedkeys('qrsq', 'tx')
%normal @r
```
