### ISSUE TITLE
Incorrect result for e.g., luaeval('{[2] = 2}')

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#26626]
### Problem

`luaeval` returns a result that doesn't correspond to its input for e.g., `luaeval('{[2] = 2}')`. This used to raise an error.

The issue started with PR #26329. Cc: @gpanders 

### Steps to reproduce

```
nvim --clean
echo luaeval('{[2] = 2}')
```

### Expected behavior

Either the following error:
```
E5100: Cannot convert given lua table: table should either have a sequence of positive integer keys or contain only string keys
```
Or:
```
{2: 2}
```

### Actual behavior

```
[]
```

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1880+ge164f4c27

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Kubuntu 23.10

### Terminal name/version

Konsole 23.08.1

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
Vimscript dictionary keys can only be strings.

**Comment by zeertzjq** [comment]
Another possible result is `[v:null, 2]`.

**Comment by dstein64** [comment]
> "Another possible result is [v:null, 2]."

I had considered adding something similar under the expected behavior in the issue description, but refrained since the approach seems memory-inefficient, particularly for large keys.

```
luaeval('{[999999] = 2}')
```

```
[v:null, v:null, v:null, ..., 2]
```

**Comment by zeertzjq** [comment]
Returning `{2: 2}` will cause the converted value of `{[2] = 2}` and `{['2'] = 2}` to be indistinguishable because Vimscript Dictionary key are always converted to strings, so `[v:null, 2]` is better.
