### ISSUE TITLE
Colors of other themes getting messed up or changed after the introduction of the new default neovim theme.

### ISSUE THREAD

**Issue by leet0rz** [neovim/neovim#26637]
### Problem

After looking around and finding which highlights were getting changed, I was able to locate these:

highlight @variable.lua
highlight Identifier

There might be more but these too were getting changed in themes getting opened in stable 0.9.4 vs themes getting opened in the nightly versions with the new neovim default theme and beyond. Let me know if you need screenshots.

### Steps to reproduce

Install neovim stable 0.9.4
Install moonlight theme
Open your regular vim.opt. settings file, have a look
Upgrade to neovim nightly and do the exact same thing again, you will find that the colors have changed.

### Expected behavior

For themes to work as intended.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1825+gd65c6a0ba Build type: RelWithDebInfo LuaJIT 2.1.1702233742 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

I have not tested the same theme on regular vim.

### Operating system/version

win Version	10.0.19044 Build 19044

### Terminal name/version

windows terminal Version: 1.19.231010001-preview and Alacritty Version 0.12.3

### $TERM environment variable

xterm-256color

### Installation

msi

**Comment by leet0rz** [comment]
> I'm saying that is work in progress and already tracked elsewhere. Patience, grasshopper.

Thank you, I'll just use what I found in the meantime, good luck!

**Comment by Hund** [comment]
> I'm saying that is work in progress and already tracked elsewhere. Patience, grasshopper.

Where can I follow the progress on this issue?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/26378#issuecomment-1839423239
