### ISSUE TITLE
Neovim doesn't seem to pull diagnostics from Ruby-LSP

### ISSUE THREAD

**Issue by olimorris** [neovim/neovim#26640]
### Problem

When I purposely create an error in a simple Ruby file (`puts "Hello, World!`), I notice that Neovim will initially report a diagnostic error message. If I fix the error, I notice the diagnostic message is still present.

The [Ruby-LSP](https://github.com/Shopify/ruby-lsp) is somewhat unique in that it only supports pull diagnostics and not PublishDiagnostics. Although I'm aware the former was implemented in #24128.

### Steps to reproduce using "nvim -u minimal_init.lua"

Steps to reproduce:

1. Ensure you have Ruby 3.0 or greater installed
2. Install Ruby-LSP with `gem install ruby-lsp` (current version 0.13.2)
3. Open Neovim with the following command: `nvim -u [path to minimal_init.lua file] example.rb`
4. Once in the file, invalidate the code in the `example.rb` file by removing one of the quotation marks from `puts "Hello, World"`. You'll see a diagnostic error
5. Put the quotation mark back. You'll still see the error.

Files outlined below:

minimal_init.lua file:

```lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
  local path_sep = on_windows and "\\" or "/"
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local lspconfig_path = join_paths(package_root, "test", "start", "nvim-lspconfig")

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
  vim.fn.system({ "git", "clone", "https://github.com/neovim/nvim-lspconfig", lspconfig_path })
end

vim.lsp.set_log_level("debug")
require("vim.lsp.log").set_format_func(vim.inspect)

local nvim_lsp = require("lspconfig")
local on_attach = function(_, bufnr)
  local function buf_set_option(...)
    vim.api.nvim_buf_set_option(bufnr, ...)
  end

  buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

  -- Mappings.
  local opts = { buffer = bufnr, noremap = true, silent = true }
  vim.keymap.set("n", "gD", vim.lsp.buf.declaration, opts)
  vim.keymap.set("n", "gd", vim.lsp.buf.definition, opts)
  vim.keymap.set("n", "K", vim.lsp.buf.hover, opts)
  vim.keymap.set("n", "gi", vim.lsp.buf.implementation, opts)
  vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, opts)
  vim.keymap.set("n", "<space>wa", vim.lsp.buf.add_workspace_folder, opts)
  vim.keymap.set("n", "<space>wr", vim.lsp.buf.remove_workspace_folder, opts)
  vim.keymap.set("n", "<space>wl", function()
    print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
  end, opts)
  vim.keymap.set("n", "<space>D", vim.lsp.buf.type_definition, opts)
  vim.keymap.set("n", "<space>rn", vim.lsp.buf.rename, opts)
  vim.keymap.set("n", "gr", vim.lsp.buf.references, opts)
  vim.keymap.set("n", "<space>e", vim.diagnostic.open_float, opts)
  vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, opts)
  vim.keymap.set("n", "]d", vim.diagnostic.goto_next, opts)
  vim.keymap.set("n", "<space>q", vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
local name = "ruby_ls"
local cmd = { "ruby-lsp" } -- needed for elixirls, lua_ls, omnisharp
if not name then
  print("You have not defined a server name, please edit minimal_init.lua")
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
  print([[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]])
end

nvim_lsp[name].setup({
  cmd = cmd,
  on_attach = on_attach,
})
```

example.rb file:

```ruby
puts "Hello, World!"
```

### Expected behavior

Diagnostic messages to be continually updated when the Ruby file is edited.

### Neovim version (nvim -v)

0.10.0-dev-7d279a0

### Language server name/version

ruby-lsp 0.13.2

### Operating system/version

macOS 14.1 (23B74)

### Log file

https://gist.github.com/olimorris/dc262e730c720824701d34c9e01e3748

**Comment by olimorris** [comment]
Hi @catlee. I thought I'd tag you in this as this issue directly corresponds to the awesome new feature you PR'd some time ago.

**Comment by catlee** [comment]
Unfortunately I can't reproduce this. I tried on the revision of nightly that you have, as well as on latest master.

One interesting thing in your logs is this:

```
[DEBUG][2023-12-18 16:40:38] .../vim/lsp/rpc.lua:43	"rpc.send"	{
  id = 6,
  jsonrpc = "2.0",
  method = "textDocument/diagnostic",
  params = {
    range = {
      ["end"] = {
        character = 0,
        line = 3
      },
      start = {
        character = 0,
        line = 0
      }
    },
    textDocument = {
      uri = "file:///Users/Oli/.dotfiles/example.rb"
    }
  }
}
[DEBUG][2023-12-18 16:40:38] .../vim/lsp/rpc.lua:43	"rpc.receive"	{
  id = 6,
  jsonrpc = "2.0"
}
```

`ruby-lsp`'s response to the `textDocument/diagnostic` request here is empty; it doesn't have any `result` field, which causes the code here to exit early:  https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/diagnostic.lua#L301

I'm not sure why `ruby-lsp` isn't responding with any results to the query in this case...

Perhaps we should consider a missing response to be the same as an empty response?

**Comment by olimorris** [comment]
Thanks for looking into this. The fact you can't recreate this makes me wonder whether there are some gems or something elsewhere on my system that's clashing with this.

I'll ask the Ruby Neovim community if they can recreate it too.

> Perhaps we should consider a missing response to be the same as an empty response?

This _looks_ sensible to my unknowledgeable eyes. I'll download the source code, make the change and build it to see.

**Comment by catlee** [comment]
I think I tracked down what's happening.

If you don't have `rubocop` in your project, then `ruby-lsp` returns early from the diagnostics runner here: https://github.com/Shopify/ruby-lsp/blob/main/lib/ruby_lsp/requests/diagnostics.rb#L46

This means that we get a `nil` result instead of `[]`.

`ruby-lsp` probably shouldn't do this, but neovim should also be resilient in case other backends do something similar.

To test this out, maybe something like this will work? https://github.com/neovim/neovim/pull/26957
