### ISSUE TITLE
":colorscheme vim" doesn't properly revert to the old legacy color scheme

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#26650]
### Problem

The documentation under `:help news` has the following:
"Use :colorscheme vim to revert to the old legacy color scheme."

Using this colorscheme results in colors that don't match the old legacy color scheme.

### Steps to reproduce

```vim
nvim --clean
" set termguicolors (or notermguicolors) so it's set consistently for experiments
:set termguicolors
" the following should be omitted for nvim<0.10
:colorscheme vim
" call :help to show text
:help
:only
```

### Expected behavior

The side-by-sides below show Neovim v0.10 (left) versus Neovim 0.9.4 (right). For the top screenshots, `termguicolors` was set. For the bottom screenshots, `notermguicolors` was set. I expected the left side colors would match the right side colors.

### `termguicolors`

![termguicolors](https://github.com/neovim/neovim/assets/541289/3a59ab5b-52ad-4e72-92d4-59e343c398a3)

### `notermguicolors`

![notermguicolors](https://github.com/neovim/neovim/assets/541289/035d4543-97c4-4578-8b5e-be5714f28459)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1880+ge164f4c27

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Kubuntu 23.10

### Terminal name/version

Konsole 23.08.1

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
`:TSBufDisable highlight`

**Comment by dstein64** [comment]
Thanks @zeertzjq. I repeated the procedure described above, using `:lua vim.treesitter.stop()`, which resulted in mostly matching colors; I see that some text ("WHAT", "PREPEND", and "EXAMPLE") doesn't have matching colors (the text appears to be not highlighted in Neovim 0.10 after running `:lua vim.treesitter.stop()`).

### termguicolors

![termguicolors](https://github.com/neovim/neovim/assets/541289/30f9bc0a-9d49-4cc8-86fd-77d5d3c74f4a)

### notermguicolors

![notermguicolors](https://github.com/neovim/neovim/assets/541289/c24e296e-518b-4dbb-bef2-0e5184475464)

**Comment by zeertzjq** [comment]
Hmm, look like there's a bug with treesitter then.

**Comment by clason** [comment]
> Hmm, looks like there's a bug with treesitter then.

What, how do you arrive at that conclusion?

**Comment by zeertzjq** [comment]
`:lua vim.treesitter.stop()` doesn't restore the `helpHeader` highlight.

**Comment by clason** [comment]
No, it only disables the highlighter; it doesn't run `syntax enable`.

**Comment by clason** [comment]
And we're comparing apples and oranges here (treesitter highlight by default and the new default colorscheme). Please bisect to pinpoint what exactly is the issue here. (And supporting the old default scheme as it was is not a priority since it was plain broken; if actually maintained colorschemes are broken, that's a different issue.)

**Comment by zeertzjq** [comment]
`:Inspect` cannot find a syntax group at the header if treesitter has been enabled and disabled, which has nothing to do with the colorscheme.

**Comment by zeertzjq** [comment]
> `:Inspect` cannot find a syntax group at the header if treesitter has been enabled and disabled

Doesn't happen in v0.9.4, so there is a regression somewhere, in syntax or treesitter.

**Comment by clason** [comment]
Again, `treesitter.stop()` does not restart the syntax engine, so there's no bug here.

**Comment by zeertzjq** [comment]
Yes, but the header still isn't highlighted after disabling and enabling syntax after disabling treesitter.

**Comment by clason** [comment]
Did you do `:syntax enable`?

**Comment by zeertzjq** [comment]
Yes, I've tried every `:syntax` command.

**Comment by clason** [comment]
And it's just the column headers on that file? Everything else is working? How does Vim behave?

**Comment by zeertzjq** [comment]
There is no treesitter in Vim to disable.

**Comment by clason** [comment]
And there is no indication (so far) that this has anything to do with treesitter.

**Comment by seandewar** [comment]
Hmm, I see the same in 0.9.4 with `nvim --clean --cmd help`, but not with `nvim --clean -c help`.
Not sure why though. :thinking:

**Comment by clason** [comment]
Yeah, some kind of race condition. `vim.defer_fn`ing the `vim.treesitter.start()` also works. And why it is this _and only this_ syntax group that's affected?

**Comment by seandewar** [comment]
Haha, okay, this is fun. When I diff both files, the one that isn't getting highlighted properly is missing the ending `~` after the headers; it's instead replaced by a tab.

**Comment by seandewar** [comment]
I think the logic in `fix_help_buffer` may be related to that...

**Comment by clason** [comment]
wtf. every time you thought you had plumbed the depths of special cases upon special cases...

Vim just keeps giving 🤗
