### ISSUE TITLE
Weird "double width" terminal cursor in kitty

### ISSUE THREAD

**Issue by TheBlob42** [neovim/neovim#26663]
### Problem

While using Kitty with the latest 0.10 Neovim version the cursor is behaving strangely inside terminal mode:  
At the end of the line its highlighting occupies two spaces and we also need an additional movement (e.g. right arrow) to "really" get to EOL. It is hard to describe in word, so hopefully the following GIFs can clarify what I mean.

![kitty_terminal_nvim](https://github.com/neovim/neovim/assets/6849129/89a3aa4f-499f-473e-96ab-9a58b669979c)

This only happens in the Kitty terminal emulator. I also tested it in the Gnome terminal and there the problem does not exist. Furthermore it only happens with version 0.10. If I go back to the latest stable version of Neovim (0.9.4) the issues does not occur (neither in Kitty nor Gnome terminal).

- no nvim config (using `--clean`)
- not kitty customization (no `kitty.conf`)

### Steps to reproduce

```shell
nvim --clean
:term<CR>
[...start typing]
```

### Expected behavior

The cursor in terminal mode should not look and behave like this

![gnome_terminal](https://github.com/neovim/neovim/assets/6849129/831bf2bd-b617-4d64-ae38-3fc8e1a03d60)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-dc9f7b8

### Vim (not Nvim) behaves the same?

I don't know

### Operating system/version

Pop!_OS 22.04 LTS

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

appimage

**Comment by TheBlob42** [comment]
Since the issue does not occur with the latest stable version I decided to open the issue in the Neovim repository instead of for the Kitty terminal

**Comment by gpanders** [comment]
Please try again with the latest commit and see if the you can still reproduce the issue. I believe this was fixed by #26091.

**Comment by gpanders** [comment]
In general, please make sure you are able to reproduce your issue on the latest commit before filing bug reports.

**Comment by TheBlob42** [comment]
I just had the same idea :see_no_evil: 
It is gone with the latest version, should have checked that before, sorry for the inconvenience
