### ISSUE TITLE
vim.lsp.inlay_hint.enable() doesn't toggle inlay hints

### ISSUE THREAD

**Issue by ChocolateOverflow** [neovim/neovim#26679]
### Problem

The comment for `vim.lsp.inlay_hint.enable()` mentions toggling but nothing in the function actually toggles inlay hints, even the usage comments.

```lua
--- Enable/disable/toggle inlay hints for a buffer
---
--- @param bufnr (integer|nil) Buffer handle, or 0 or nil for current
--- @param enable (boolean|nil) true/nil to enable, false to disable
--- @since 12
function M.enable(bufnr, enable)
```

`vim.lsp.inlay_hint(0, nil)` used to toggle, but the new `enable()` API doesn't do that, nor is there a function for toggling.

For now, I'm using this to toggle:

```lua
local function toggle_inlay_hints()
  vim.lsp.inlay_hint.enable(0, not vim.lsp.inlay_hint.is_enabled(nil))
end
```

It's simple, but I think we should have a `vim.lsp.inlay_hint.toggle()` function or at least "toggle if `nil`" in `enable()` for easier usage.
I can make a PR for that little change, but I'd like to know if there's been discussion on why there's no longer a single function call for toggling inlay hints, and whether it's better to put toggling in its own function or just `enable()`.

### Steps to reproduce using "nvim -u minimal_init.lua"

Use any LSP with inlay hints (I configured with [neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig))

### Expected behavior

There should be a single function call for toggling inlay hints (previously `vim.lsp.inlay_hint(0, nil)`)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1890+g1cf51a07a

### Language server name/version

N/A

### Operating system/version

N/A

**Comment by zeertzjq** [comment]
No. See #25512

**Comment by clason** [comment]
```lua
lsp.inlay_hint.enable(0, not lsp.inlay_hint.is_enabled()) end)
```

**Comment by EvanCarroll** [comment]
Unless I'm missing something it still says it toggles, https://neovim.io/doc/user/lsp.html#lsp-inlay_hint

> enable({bufnr}, {enable}) [vim.lsp.inlay_hint.enable()](https://neovim.io/doc/user/lsp.html#vim.lsp.inlay_hint.enable())Enable/disable/toggle inlay hints for a buffer

I also think a .toggle function would be nice.

**Comment by clason** [comment]
Yes; the linked PR is not yet merged. And we won't add a new wrapper for a one-line snippet.
