### ISSUE TITLE
Obsolete Neovim in WSL APT

### ISSUE THREAD

**Issue by iqnite** [neovim/neovim#26672]
### Problem

<img width="466" alt="image" src="https://github.com/neovim/neovim/assets/50552317/8469e23e-6527-4445-b9e3-934153c7be31">

I want to use GitHub Copilot with Neovim, but when I run the `:Copilot setup` command it says that my Neovim versions is too old. However, APT says that all packages are up-to-date. Please port the newest version to the APT package manager, too.

### Steps to reproduce

`sudo apt update`
`sudo apt upgrade neovim`

### Expected behavior

I should be able to get the latest Neovim release.

### Neovim version (nvim -v)

0.4.4

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

WSL Debian

### Terminal name/version

Windows Terminal Preview

### $TERM environment variable

???

### Installation

APT

**Comment by clason** [comment]
We have no control over that.

**Comment by zeertzjq** [comment]
This should be reported to the package repository.
