### ISSUE TITLE
osc52 copy fails for large payloads due to stdout write failing with EAGAIN

### ISSUE THREAD

**Issue by NobodyNada** [neovim/neovim#26688]
### Problem

(Preface: I'm not sure whether this is considered a Neovim bug or a LuaJIT bug. Since it's causing an end-user visible bug in Neovim I decided to post it here, but I'm happy to move it elsewhere if maintainers believe that's the best thing to do.)

On my machine (macOS 14.2), attempting to use the osc52 clipboard plugin fails when when the encoded OSC52 command is greater than 1024 bytes. Tracing through this in a debugger, I found that:

- `runtim/elua/vim/ui/clipboard/osc52.lua` calls `io.stdout:write()` with the payload: https://github.com/neovim/neovim/blob/0c120307ca1ab613e63865c634d7e10ad67fb0ba/runtime/lua/vim/ui/clipboard/osc52.lua#L16
- This calls `io_file_write` in `LuaJIT/src/lib_io.c`: https://github.com/LuaJIT/LuaJIT/blob/29b0b282f59ac533313199f4f7be79490b7eee51/src/lib_io.c#L228
- `io_file_write` calls `fwrite` with the buffer
- `fwrite` returns 1024 and sets `errno` to `EAGAIN`. I think this means the first 1024 bytes of the payload were written successfully, but that writing further data would block and `stdout` is opened with `O_NONBLOCK`.
- LuaJIT does not handle the `EAGAIN` error and returns failure (which is ignored by `osc52.lua`).

Running kitty in `--dump-commands` mode reveals that kitty does indeed receive the osc52 command truncated to 1024 bytes (cutting off the `ST` sequence to end the command, which often leads to screen corruption.)

### Steps to reproduce

Minimal reproducible configuration:

```lua
vim.opt.clipboard = 'unnamedplus'
local ok, osc52 = pcall(require, "vim.ui.clipboard.osc52")

vim.g.clipboard = {
    name = 'OSC 52',
    copy = {
    ['+'] = osc52.copy('+'),
    ['*'] = osc52.copy('*'),
    },
    paste = {
    ['+'] = osc52.paste('+'),
    ['*'] = osc52.paste('*'),
    },
}
```

- Open some file with `nvim --clean -u minimal.lua`
- Use the `y` command to copy a large chunk of text, (longer than 1024 bytes when base64-encoded)
- Observe that the text is not successfully copied. You may also encounter screen corruption.

### Expected behavior

It seems to me that `io_file_write` within LuaJIT should loop and retry the write upon receiving EAGAIN until the entire buffer is written successfully, but I'm not familiar enough with the internals of Neovim and LuaJIT to be sure that's the best course of action. I can open a LuaJIT PR with this change if maintainers agree.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1909+g0c120307c

### Vim (not Nvim) behaves the same?

N/A, vim does not have osc52 or lua

### Operating system/version

macOS 14.2

### Terminal name/version

kitty 0.30.0

### $TERM environment variable

xterm-kitty

### Installation

Built from source

**Comment by zeertzjq** [comment]
Does this help:
```diff
diff --git a/runtime/lua/vim/_defaults.lua b/runtime/lua/vim/_defaults.lua
index 2627cbcd0..57ce1e514 100644
--- a/runtime/lua/vim/_defaults.lua
+++ b/runtime/lua/vim/_defaults.lua
@@ -310,7 +310,7 @@ if tty then
       query = string.format('\027Ptmux;%s\027\\', query:gsub('\027', '\027\027'))
     end
 
-    io.stdout:write(query)
+    vim.api.nvim_chan_send(2, query)
 
     timer:start(1000, 0, function()
       -- Delete the autocommand if no response was received
@@ -406,7 +406,7 @@ if tty then
       if os.getenv('TMUX') then
         decrqss = string.format('\027Ptmux;%s\027\\', decrqss:gsub('\027', '\027\027'))
       end
-      io.stdout:write(string.format('\027[48;2;%d;%d;%dm%s', r, g, b, decrqss))
+      vim.api.nvim_chan_send(2, string.format('\027[48;2;%d;%d;%dm%s', r, g, b, decrqss))
 
       timer:start(1000, 0, function()
         -- Delete the autocommand if no response was received
diff --git a/runtime/lua/vim/termcap.lua b/runtime/lua/vim/termcap.lua
index ec29acca4..16664baac 100644
--- a/runtime/lua/vim/termcap.lua
+++ b/runtime/lua/vim/termcap.lua
@@ -78,7 +78,7 @@ function M.query(caps, cb)
     query = string.format('\027Ptmux;%s\027\\', query:gsub('\027', '\027\027'))
   end
 
-  io.stdout:write(query)
+  vim.api.nvim_chan_send(2, query)
 
   timer:start(1000, 0, function()
     -- Delete the autocommand if no response was received
```

**Comment by zeertzjq** [comment]
Oh, it seems to still be truncated, but at a different length.

**Comment by NobodyNada** [comment]
I tried that patch, as well as making the same change in `osc52.lua`, and got the same result both times. 

It looks like the channel send function just uses a bare `fwrite` call without handling `EAGAIN` as well: https://github.com/neovim /neovim/blob/0c120307ca1ab613e63865c634d7e10ad67fb0ba/src/nvim/channel.c#L577

**Comment by NobodyNada** [comment]
I can confirm that your PR resolves the issue, thanks for the quick fix!
