### ISSUE TITLE
docs: completepopup is implemented but not reflected in vim_diff

### ISSUE THREAD

**Issue by xsh005** [neovim/neovim#26681]
### Problem

https://github.com/neovim/neovim/blob/99d1e7da28061c2559c523f76b58b8bb113475ff/runtime/doc/vim_diff.txt#L584

But it is actually already implemented #24723 

### Steps to reproduce

nvim --clean -c "tab help completepopup"

### Expected behavior

It is not included in `nvim-missing`

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1873+g8f08b1efb

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

irrelavant

### Terminal name/version

irrelavant

### $TERM environment variable

irrelavant

### Installation

nighly binary

**Comment by seandewar** [comment]
No, `completeopt=popup` is implemented, but not `completepopup`; that's being worked on in #25541.
