### ISSUE TITLE
Nvim doesnt change Normal group background color

### ISSUE THREAD

**Issue by belchushka** [neovim/neovim#26693]
### Problem

Nvim doesnt change Normal group background color if its set in init.lua like `vim.api.nvim_set_hl(0, "Normal", {fg="#FF0000", bg="#0000FF"})`, but works fine if run it manually `:lua vim.api.nvim_set_hl(0, "Normal", {fg="#FF0000", bg="#0000FF"})`. 

<img width="1467" alt="Screenshot 2023-12-21 at 3 48 43 PM" src="https://github.com/neovim/neovim/assets/58639281/7889b725-e37e-4e25-b1e6-faf4bb1761a7">

P.S fg property works fine in both ways

### Steps to reproduce

1. paste vim.api.nvim_set_hl(0, "Normal", {fg="#FF0000", bg="#0000FF"}) into init.lua
2. nvim

### Expected behavior

Background color should be blue but inherits terminal background color instead

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 13.6.3

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by clason** [comment]
Do you have `termguicolors` set?

**Comment by belchushka** [comment]
> Do you have `termguicolors` set?

yes

`vim.opt.termguicolors = true`

**Comment by clason** [comment]
Please share a full (and minimal!) repro with steps and config we can test with `nvim --clean -u test.lua`.

**Comment by zeertzjq** [comment]
Please follow the instruction on minimal steps to reproduce in issue template:

> Use the provided [minimal reproduction template](https://github.com/neovim/neovim/blob/master/contrib/minimal.lua) to create a minimal configuration. After you fill it out with necessary information, run with `nvim --clean -u minimal.lua`.

**Comment by belchushka** [comment]
minimal.lua

```
for name, url in pairs{
  -- no plugins
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

vim.opt.termguicolors = true
vim.api.nvim_set_hl(0, 'Normal', {fg="#FF0000", bg="#0000FF"});
```

Its strange but if i use --clean & -u flags on minimal.lua everything works fine but when i paste the same code in .config/nvim/init.lua and run `nvim` issue is still here.

**Comment by belchushka** [comment]
Its seems like smth overrides my config but i dont have anything else in init.lua

**Comment by clason** [comment]
Then the issue is with your `init.lua` (or plugins, or...); it works fine for me.

**Comment by zeertzjq** [comment]
Maybe you have a colorscheme that is enabled by some other config file? What does `:hi Normal` show if you don't change its highlight in either place?

**Comment by belchushka** [comment]
`:hi Normal` shows `Normal         xxx cleared`
and
`:colorscheme` shows `default`

**Comment by belchushka** [comment]
if i paste minimal.lua content in init.lua results are:

`:hi Normal` - `Normal         xxx guifg=#ff0000`
`:colorscheme` - `default`

**Comment by clason** [comment]
Try `nvim -V1` and `:verb hi Normal`.

**Comment by belchushka** [comment]
I do not insert any plugins in init.lua but somehow `vim-transparent` still has effect on my config

Normal         xxx guifg=#ff0000
        Last set from ~/.local/share/nvim/site/pack/packer/start/vim-transparent/autoload/background.vim line 44

After removal everything works fine.

Thank you so much!

**Comment by clason** [comment]
That's how start packages work, and the reason we insist on reproduction steps with `nvim --clean`.
