### ISSUE TITLE
Error while calling lua chnuk (nvchad)

### ISSUE THREAD

**Issue by MatBerg10** [neovim/neovim#26701]
### Problem

Whenever I try to open neovim (v0.6.1) i get the following error:

Error detected while processing /home/codeany/.config/nvim/init.lua: E5113: Error while calling lua chunk: /home/codeany/.config/nvim/lua/core/init.lua:67: attempt to call local 'autocm d' (a nil value) stack traceback: /home/codeany/.config/nvim/lua/core/init.lua:67: in main chunk [C]: in function 'require' /home/codeany/.config/nvim/init.lua:1: in main chunk Press ENTER or type command to continue

I've tried reinstalling neovim and nvchad and it always gives me this error.
I use v0.6.1 of Neovim.
I don't know if it matters, but I'm installing it in an online Ubuntu environment with zsh using sudo apt install neovim and the standard git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1

### Steps to reproduce

nvim

### Expected behavior

It should open neovim as normal

### Neovim version (nvim -v)

v0.6.1

### Vim (not Nvim) behaves the same?

vim 8.2

### Operating system/version

Ubuntu 22.04

### Terminal name/version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### $TERM environment variable

SHELL=/bin/bash NVM_INC=/usr/local/share/nvm/versions/node/v18.12.1/include/node rvm_prefix=/usr/local HOSTNAME=a9db3c35f762 JAVA_HOME=/usr/local/sdkman/candidates/java/current DOTNET_ROOT=/usr/local/dotnet/current GRADLE_HOME=/usr/local/sdkman/candidates/gradle/current MY_RUBY_HOME=/usr/local/rvm/rubies/default SDKMAN_CANDIDATES_DIR=/usr/local/sdkman/candidates PIPX_BIN_DIR=/usr/local/py-utils/bin PWD=/workspaces/cpp/test-project rvm_version=1.29.12 (latest) GIT_EXEC_PATH=/usr/lib/git-core HOME=/home/codeany LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36: CARGO_HOME=/usr/local/cargo NVM_SYMLINK_CURRENT=true PHP_PATH=/usr/local/php/current THEIA_MINI_BROWSER_HOST_PATTERN={{hostname}} LOCAL_GIT_DIRECTORY=/usr CA_WS_DOMAIN=us2.codeanyapp.com THEIA_WEBVIEW_EXTERNAL_ENDPOINT={{hostname}} DOCKER_BUILDKIT=1 GOROOT=/usr/local/go CA_WS_PROJECT_ROOT=/workspaces CA_WS_ID=codeanywhere-templates-c-8iwz9n5gqp PYTHON_PATH=/usr/local/python/current NVM_DIR=/usr/local/share/nvm rvm_bin_path=/usr/local/rvm/bin GEM_PATH=/usr/local/rvm/gems/default:/usr/local/rvm/gems/default@global GEM_HOME=/usr/local/rvm/gems/default VSCODE_API_VERSION=1.74.2 LESSCLOSE=/usr/bin/lesspipe %s %s TERM=xterm-color RUSTUP_HOME=/usr/local/rustup LESSOPEN=| /usr/bin/lesspipe %s USER=codeany PIPX_HOME=/usr/local/py-utils MAVEN_HOME=/usr/local/sdkman/candidates/maven/current SDKMAN_DIR=/usr/local/sdkman SHLVL=3 NVM_CD_FLAGS=-q GIT__CAN_USE_NO_OPTIONAL_LOCKS=true PROMPT_DIRTRIM=4 SDKMAN_CANDIDATES_API=https://api.sdkman.io/2 PATH=/usr/local/cargo/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/php/current/bin:/usr/local/share/nvm/versions/node/v18.12.1/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/go/bin:/go/bin:/usr/local/dotnet/current:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/codeany/.local/bin:/usr/local/rvm/bin SDKMAN_PLATFORM=linuxx64 NVM_BIN=/usr/local/share/nvm/versions/node/v18.12.1/bin DEBIAN_FRONTEND=noninteractive rvm_path=/usr/local/rvm OLDPWD=/workspaces/cpp/test-project GOPATH=/go _=/usr/bin/printenv LOGNAME=codeany ZSH=/home/codeany/.oh-my-zsh PAGER=less LESS=-R LSCOLORS=Gxfxcxdxbxegedabagacad

### Installation

sudo apt install neovim

**Comment by clason** [comment]
Use a current version. And give a minimal (no NvChad!) config to reproduce with `nvim --clean -u minimal.lua`. Please read the issue template.
