### ISSUE TITLE
UI protocol for graphics

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#26708]
### Problem

Currently, neovim doesn't have a UI protocol for graphics.

### Expected behavior

A new UI protocol for graphics would be added.
There would be three possible graphical elements, buffer-local, window-local, and global:
* The buffer-local one would use extmark for the position of the graphical element. If the graphic is cut off by a window boundary, then only the part in the buffer should be seen.
* The window-local one would use window positioning, including positioning from the bottom/right with negative numbers so that bottom/right graphical elements wouldn't need to be updated every time the window size changes.
* The global one would work similarly to the window-local one, but use global positioning instead.

After implementing the protocol, I suggest implementing a fallback system for the neovim tui: by default, a program that converts graphics to ASCII art would be used. A new option should also be added, that can specify an external program to use to convert graphics to ASCII art. There should also be an option to disable this feature. I also propose that a graphical element could set the ASCII art fallback, instead of relying on a program.

Later on, we could extend the neovim-tui UI handler to work with terminals that implement some sort of graphical rendering.
Related issues: #4500, #12991

**Comment by clason** [comment]
Duplicate. What's needed here is a _concrete_ suggestion (in the form of a PR).
