### ISSUE TITLE
WinResized does not trigger during -S

### ISSUE THREAD

**Issue by carbon-steel** [neovim/neovim#26715]
### Problem

I have lua script that calls `vim.cmd.split` which should trigger the `WinResized` but it doesn't.

# Previous Issue
This issue is a follow-up to https://github.com/neovim/neovim/issues/26498

In that issue, I was asking why the `WinResized` event failed to trigger when I ran a lua script via `nvim -l ...` (which I expected would trigger `WinResized`). It was explained to me that:
> There is no display when using -l, so WinResized is never triggered.

This explanation matches what the documentation also says:
> -l {script} [args]
Executes Lua {script} non-interactively (no UI) with optional
[args] after processing any preceding Nvim |cli-arguments|,
then exits. Exits 1 on Lua error. See |-S| to run multiple Lua
scripts without args, with a UI.

# Current Issue
As I understand, running my script with `-l` does not trigger the `WinResized` event since `-l` runs with no UI. The documentation above says `-S` runs with a UI so running my script with `-S` should trigger the `WinResized` event. However, I found that running my script with `-S` also did not trigger the `WinResized` event.

Issue: Why does running my lua script via `nvim -S ...` fail to trigger the `WinResized` event?  

### Steps to reproduce

winresized.lua
```lua
vim.api.nvim_create_autocmd({"WinResized"}, {
    callback = function ()
        print("WinResized triggered!")
    end
})

vim.cmd.split()
```

Run the file above like so: `nvim --clean -S winresized.lua`

### Expected behavior

`WinResized triggered!` should have been printed due to the `split()` command from the lua script, but it wasn't.

* To make sure that the print statement is working, I tried adding `print("Start")` to the beginning of the script and `Start` did appear.
* If you manually split the windows after running the above command, you'll find that `WinResized triggered!` does get printed. So, it is just during the execution of `winresized.lua` that `WinResized` fails to trigger.
* As a separate note, `WinResized triggered!` does not get printed via `nvim --clean "+luafile /tmp/winresized.lua"` either.

### Neovim version (nvim -v)

0.9.4 commit d772f69

### Vim (not Nvim) behaves the same?

Vim does not have the `WinResized` event

### Operating system/version

Fedora Linux 37

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by zeertzjq** [comment]
Same reason. "updating the display" refers to screen update on the main redraw loop, which cannot be run during a script, so this is not possible.

**Comment by carbon-steel** [comment]
Is there anything you might recommend so that I could have neovim take automated steps while also "updating the display"? The reason why I need this is because I am using it to test my plugin.

**Comment by zeertzjq** [comment]
1. Use `vim.schedule()` or `vim.defer_fn()`.
2. Use an RPC client.
