### ISSUE TITLE
<C-i> are not working correctly

### ISSUE THREAD

**Issue by akarl818** [neovim/neovim#2673]
It will delete the current line and the one below it, then start insert mode. It should go forward in the jump-list.

Tested with `nvim -u NONE`

`NVIM 0.0.0-alpha+201505151628 (compiled May 16 2015 15:20:53)`
`Commit: 6f72f56492c0948371c746356458c1693efa85a3`

When I do `<C-v><C-i>` in insert mode I get `±;2C`.

I have tested in iTerm2 Build 2.1, with and without tmux. In tmux the $TERM is set to screen-256color and without tmux it's set to xterm-256color.

**Comment by justinmk** [comment]
I believe your Iterm2 profile (or terminfo entries) is what matters. For whatever reason your terminal is sending the wrong sequence for ctrl-i (aka TAB). Configure it to send ascii tab (9).

**Comment by justinmk** [comment]
Going to consider this a dup of https://github.com/neovim/neovim/issues/2048 unless proven otherwise. Please see https://github.com/neovim/neovim/issues/2048#issuecomment-98192906 for a hint on how to configure iTerm to send a specific sequence for a given key. (You want ctrl-i to send `0x9` as I mentioned above)

**Comment by akarl818** [comment]
iTerm seems to send the correct sequence.

This is the output of <C-v><C-i> in Vim 7.4: `^[1;2C`
This is the output of <C-v><C-i> in Neovim: `±;2C`

**Comment by justinmk** [comment]
Does it work in Vim?

**Comment by akarl818** [comment]
Yes, it works perfectly in Vim.

**Comment by justinmk** [comment]
@akarl818 Any change here on latest master?

**Comment by akarl818** [comment]
Yes, Neovim now sends `^[1;2C` just like vim.

**Comment by akarl818** [comment]
Is there a workaround I can do for this? Can I bind `±;2C` somehow?

**Comment by justinmk** [comment]
`nnoremap ±;2C ...` should work.

**Comment by akarl818** [comment]
Thank you!

`nnoremap ±;2C <C-i>` worked great!

**Comment by justinmk** [comment]
> This is the output of `<C-v><C-i>` in Vim 7.4: `^[1;2C`
> This is the output of `<C-v><C-i>` in Neovim: `±;2C`

On master ,`<C-v><C-i>` inserts a literal TAB character. CTRL-i should work, so this issue can be closed.
