### ISSUE TITLE
`vim.keymap.set()` unexpected behavior

### ISSUE THREAD

**Issue by Bekaboo** [neovim/neovim#26748]
### Problem

The following two keymaps have different behaviors which is unexpected:

```lua
vim.keymap.set('n', '<Down>', 'v:count ? "<Down>" : "g<Down>"', { expr = true })
```

```vim
nnoremap <expr> <Down>   v:count ? "<Down>" : "g<Down>"
```

The vimscript version works fine, i.e. pressing `<Down>` on a wrapped line will move the cursor down one screen line, but the lua version will not work (pressing `<Down>` will not move cursor)

### Steps to reproduce

1. nvim --clean
2. Insert a long line until it wraps
3. Put cursor at the beginning of the long line
4. `:lua vim.keymap.set('n', '<Down>', 'v:count ? "<Down>" : "g<Down>"', { expr = true })`
5. Press `<Down>` --> cursor does not move
6. `:nnoremap <expr> <Down>   v:count ? "<Down>" : "g<Down>"`
7. Press `<Down>` --> cursor moves down by screen line

### Expected behavior

The lua version of keymap should work and have the same effect as the vimscript version.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1952+gddc8dd187d

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Linux 6.1.60-1-lts

### Terminal name/version

alacritty 0.12.3 (5efb0690) + tmux 3.3a

### $TERM environment variable

xterm-256color

### Installation

AUR

**Comment by zeertzjq** [comment]
`replace_keycodes = false`
