### ISSUE TITLE
Implementing undercurl support in windows terminal 

### ISSUE THREAD

**Issue by ajmandourah** [neovim/neovim#26744]
### Problem

Windows did not support underline syles other than the regular one. no undercurl or double line . but with the latest merge one month ago these has been implemented and planned for  https://github.com/microsoft/terminal/pull/16097.

in the latest canary you can see this in action using powershell >= 6  (Cmd as far as i know does not support escape chars. correct me if i am wrong )

using both 
```
Write-Host "`e[4:3mtest`e[0m"
Write-Host "`e[4:3;58:2::000:255:000mtest`e[0m"
```
will print both colored non colored undercurl 

![image](https://github.com/neovim/neovim/assets/27051374/1c559811-e124-4354-8d67-cacc0f3f78a2)

but neovim in windows won't show these even when modifying the t_Ce and t_Cs variables

```
if vim.fn.has("termguicolors") == 1 then
    vim.o.termguicolors = true
    -- Enable undercurl
    vim.api.nvim_set_var('t_Cs', '\\e[4:3m')
    vim.api.nvim_set_var('t_Ce', '\\e[4:0m')
end
```

Can this be implemented early so when the final release is done this wil be ready?
the latest canary also supports all other styles of underline like dotted and double underlines.

### Expected behavior

to show undercurls and other styles of  underlines

**Comment by tusharsnx** [comment]
Hey, original committer for the mentioned PR here :)

#### Workaround:
I've been testing undercurls in Neovim while developing that feature for Windows Terminal. So, if you set `TERM=tmux` before launching Neovim (and terminfo for tmux is installed), then nvim would treat WT as tmux and enable undercurl and colored underlines for you 😅

**Comment by tusharsnx** [comment]
@ajmandourah 
>I assume you are sshing or using wsl right?

Ohh.. yeah I forgot to mention it only works when using nvim inside wsl.

**Comment by ajmandourah** [comment]
> @ajmandourah
> 
> > I assume you are sshing or using wsl right?
> 
> Ohh.. yeah I forgot to mention it only works when using nvim under wsl.

yeah thought so . this has been the only drawback for windows users. although the windows terminal now should be able to display undercurls correctly. so unless its implemented in neovim i guess we would have to wait .

**Comment by kmoschcau** [comment]
Hi, until neovim adds an extra workaround for Windows terminal, you can add a terminfo override. (See `:h terminfo`).

I just changed my `xterm-256color` entry to look like this:

```
xterm-256color|xterm with 256 colors,
	Smulx=\E[4:%p1%dm,
	use=xterm+osc104, use=xterm+256color, use=xterm-new,
```

Only the second line was added and that already caused shaped and colored underlines to work in WSL. Sadly I don't know how to make this work on Windows itself, as there is no terminfo mechanism there.

**Comment by ajmandourah** [comment]
I don't know if this is related, windows terminal uses ` as an escape characher where unix systems uses \. this is probably to avoid windows paths from being invalid . 
i have already tried modifying my init.lua but with no luck

**Comment by kmoschcau** [comment]
> I don't know if this is related, windows terminal uses ` as an escape characher where unix systems uses . this is probably to avoid windows paths from being invalid . i have already tried modifying my init.lua but with no luck

That's not Windows in general, that's Powershell. Most Linux Shells use a backslash (`\`), Powershell uses a backtick (`` ` ``) and Windows CMD uses a circumflex (`^`) as escape character. The reason I said there's no mechanism on Windows is, that contrary to Linux environments, Neovim doesn't use a terminfo library on Windows to look at those overrides. So even if you put an override file in the same place on Windows as you would on Linux, it just won't be read.

**Comment by tusharsnx** [comment]
Ideally, I would want any `NewTerminal.exe` that is able to draw undercurls to support them in neovim out of the box.

They shouldn't have to request special handling from Neovim (Eg. contributing their terminfo into nvim repo). So, supporting only WT or Conhost (Legacy terminal window, *supports* colorful styled underlines) shouldn't be the end goal.

**Comment by ajmandourah** [comment]
I agree. standarizing is always a better solution.

PS. I am not knowledgable in windows related terminals but if i understand it right all terminal applications in windows uses some sort of proxy , conttpy to handle the translatioins. giving the support to to it will eventually give the support to other terminals. alacritty and wezterm speceficlly. correct me if i am wrong .

**Comment by tusharsnx** [comment]
I should mention that one can _safely_ do feature detection for undercurl and colored underlines support with DECRQSS and DECRPSS. This was taken into consideration while implementing these features for WT.

The steps to detect support for SGR4:X and SGR58/59 would be like:
1. Set undercurl via `\e[4:3m` sequence.
2. and immediately check with the terminal if it was successfully set using DECRQSS `\eP$qm\e\`
3. If the DECRPSS response contains 4:3, it was set and that also means that the terminal supports undercurl.

You could combine it with SGR58 and it should work as well.

**Comment by ajmandourah** [comment]
> I should mention that one can _safely_ do feature detection for undercurl and colored underlines support with [DECRQSS](https://vt100.net/docs/vt510-rm/DECRQSS.html) and [DECRPSS](https://vt100.net/docs/vt510-rm/DECRPSS.html). This was taken into consideration while implementing these features for WT.
> 
> The steps to detect support for SGR4:X and SGR58/59 would be like:
> 1. Set undercurl via `\e[4:3m` sequence.
> 2. and immediately check with the terminal if it was successfully set using DECRQSS `\eP$qm\e\`
> 3. If the DECRPSS response contains 4:3, it was set and that also means that the terminal supports undercurl.
> 
> You could combine it with SGR58 and it should work as well.

Thanks for mentioning that. I will try implementing these and see. This will hopefully fix the issue where old version of WT won't render the underlines. Addetionally if this works, no need to add a new terminfo entry in the builtin terminfo list

**Comment by zeertzjq** [comment]
Please try #28052

**Comment by akthe-at** [comment]
> Please try #28052

@zeertzjq I tried this just now and undercurl now works with Wezterm :) It does not appear to work with Windows Terminal yet based on my current configuration but I came here looking for the Wezterm support :)

**Comment by zeertzjq** [comment]
Now you can try artifacts from this workflow: https://github.com/zeertzjq/neovim/actions/runs/8453375103

**Comment by zeertzjq** [comment]
You can now also try artifacts from this workflow: https://github.com/zeertzjq/neovim/actions/runs/8453875103

**Comment by zeertzjq** [comment]
Sorry, I deleted and recreated a comment, because the previous commit had a bug. But the bug shouldn't affect exit behavior, so something else may be wrong here.

**Comment by akthe-at** [comment]
> Sorry, I deleted and recreated a comment, because the previous commit had a bug. But the bug shouldn't affect exit behavior, so something else may be wrong here.

Mistake was on my end, was using a profile in powershell that had TERM="wezterm". After deleting that it fixed the exiting behavior, sorry! I will note that both Wezterm and Windows Terminal still have undercurl after removing that line from the powershell profile as well. I also tested git-bash shell in Wezterm and Windows terminal with your new artifact, both worked and had undercurls :D

**Comment by ajmandourah** [comment]
I can confirm that undercurl is working in Windows terminal . Legacy terminals renders an underline (the expected behaviour for unsupported terminals) .

I must say this implementation is much cleaner than my approach . Well done.

**Comment by zyd2001** [comment]
> You can now also try artifacts from this workflow: https://github.com/zeertzjq/neovim/actions/runs/8453875103
I tried the artifact and also built from HEAD. It is working in Windows terminal and also through SSH, but it will not work in tmux. I have configured tmux with undercurl support and I can print with undercurl in shell under tmux.

**Comment by zeertzjq** [comment]
You need to have `TERM` set to `tmux-256color` in tmux, because tmux doesn't support DECRQSS.

**Comment by tusharsnx** [comment]
Off topic, but gemini is really quick in picking up answers from github issues
> The steps to detect support for SGR4:X and SGR58/59 would be like:

> Set undercurl via \e[4:3m sequence.
> and immediately check with the terminal if it was successfully set using DECRQSS \eP$qm\e\
> If the DECRPSS response contains 4:3, it was set and that also means that the terminal supports undercurl.

![image](https://github.com/neovim/neovim/assets/55626797/524304ab-6c16-423a-916c-4f90225eadc6)
