### ISSUE TITLE
vim.api.nvim_buf_get_option returns wrong value

### ISSUE THREAD

**Issue by daedroza** [neovim/neovim#26757]
### Problem

The shiftwidth value returned from vim.api.* is wrong.

### Steps to reproduce

The current buffer's shiftwidth value is checked using:
`lua print(vim.fn.shiftwidth())` returns 4 which is appropriately set for the text file.

However, when I use:
`local status_ok, buf_option = pcall(vim.api.nvim_buf_get_option, 0, "shiftwidth")` then buf_option prints value 8.

### Expected behavior

The buf_option should return 4. Even if pass the current buffer using `vim.api.nvim_get_current_buf`, it always returns 8.

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

shiftwidth() when used from .vim file worked correctly

### Operating system/version

Ubuntu 22.04 LTS

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

deb

**Comment by glepnir** [comment]
`:echo nvim_get_option_value('sw', { 'buf': 0})` output is what ?

**Comment by zeertzjq** [comment]
What sets 'shiftwidth' to 4?

**Comment by daedroza** [comment]
> `echo nvim_get_option_value('sw', { 'buf': 0})`

The value return is 4.

> What sets 'shiftwidth' to 4?

It's initially set to 2. There is a plugin called guess-indent that changes it to 4.

```
      vim.g.neoformat_c_clangformat = {
        exe = "clang-format",
        args = {
          '--style="{BasedOnStyle: Google, ColumnLimit: 120, IndentWidth: '
            .. tostring(get_buf_option("shiftwidth"))
            .. '}"',
        },
      }
```

This is how I'm trying to set it. I just checked, even in vimscript, I'm facing this issue. If I try to concat a value inside that json string, it will give 8 instead of 4. However, if I just keep it 4 (static), this doesn't happen.

Interesting issue.

**Comment by wookayin** [comment]
You can check the output of `:verbose setlocal shiftwidth` (If it says "Set from Lua", try `nvim -V1`) to see where it was exactly set.

**Comment by daedroza** [comment]
After further debugging, I found the issue and it was in the plugin itself, thanks all for spending some time on it!
