### ISSUE TITLE
default colorscheme obscures current position on :substitute with confirm flag

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#26760]
### Problem

When doing a substitute with the /c flag, I can’t tell where the cursor/what the current replacement target is. I can fix this by reassigning `:hi! IncSearch guibg=Red` or another colour, so the current replacement is visible.

### Steps to reproduce

nvim —clean
insert `foobar` on several lines
:%s/foobar/replacement/gc

### Expected behavior

Current confirm location is visible, don’t really care what colour we use!

### Neovim version (nvim -v)

HEAD

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Mint

### Terminal name/version

Alacritty 0.12

### $TERM environment variable

alacritty

### Installation

source

**Comment by craigmac** [comment]
@echasnovski can you reproduce?

**Comment by echasnovski** [comment]
> @echasnovski can you reproduce?

Yes, I can. Don't really use this feature much, so missed it.

Does `hi! link IncSearch CurSearch` work better without obvious downsides?
