### ISSUE TITLE
Error with Thrift LSP: Invalid 'end_col': out of range

### ISSUE THREAD

**Issue by xieping5555** [neovim/neovim#26769]
### Problem

```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/highlight.lua:65: Invalid 'end_col': out of range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        /usr/local/share/nvim/runtime/lua/vim/highlight.lua:65: in function 'range'
        /usr/local/share/nvim/runtime/lua/vim/diagnostic.lua:955: in function 'show'
        /usr/local/share/nvim/runtime/lua/vim/diagnostic.lua:1225: in function 'show'
        /usr/local/share/nvim/runtime/lua/vim/diagnostic.lua:654: in function 'config'
        /usr/local/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:256: in function 'on_publish_diagnostics'
        .../nvim/site/pack/packer/start/go.nvim/lua/go/lsp_diag.lua:38: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1148: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to reproduce

just typing i appears

### Expected behavior

no error message

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1974+g714b07519

### Vim (not Nvim) behaves the same?

no use vim

### Operating system/version

maxOS 13.6.1 (22G313)

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by glepnir** [comment]
provide more informations and try min congig there have an error from plugin go.nvim.

**Comment by xieping5555** [comment]
i found that the error only appears when i'm editing thrift files, i tried to uninstall the lsp thriftls, the error disappear

**Comment by lewis6991** [comment]
> just typing i appears

Sorry but this isn't acceptable.

If you want people to help with your issue, you need to put in some effort so the issue can be reasonably reproduced.

**Comment by xieping5555** [comment]
> > just typing i appears
> 
> Sorry but this isn't acceptable.
> 
> If you want people to help with your issue, you need to put in some effort so the issue can be reasonably reproduced.

just edit the thrift file with thriftls LSP, and create a syntax error, it will reproduce.
