### ISSUE TITLE
Formatted man files do not show correctly

### ISSUE THREAD

**Issue by ozogxyz** [neovim/neovim#26775]
### Problem

When inside a formatted man file, for example `fhopen.2` and run `!man %` the output is not rendered correctly. 

<img width="1728" alt="Screenshot 2023-12-28 at 12 37 32" src="https://github.com/neovim/neovim/assets/50372354/a16f7984-5c14-4e86-bac5-cc782843e18f">

The directory is under my `MANPATH`.

### Steps to reproduce

`nvim --clean`

open any formatted `man` file like `fhopen.2`

`:!man %`

### Expected behavior

To be able to read the formatted man page inside neovim like:

<img width="1728" alt="Screenshot 2023-12-28 at 12 39 31" src="https://github.com/neovim/neovim/assets/50372354/82a37e77-43e9-4699-ac98-f0014a980358">

### Neovim version (nvim -v)

0.9.4 Build type: Release LuaJIT 2.1.1700008891

### Vim (not Nvim) behaves the same?

no, version 9.0.2018, standard macOS vim (not brew or macports)

### Operating system/version

macOS 14.2.1

### Terminal name/version

iterm2

### $TERM environment variable

tmux-256color

### Installation

macports

**Comment by clason** [comment]
Use `:Man`.

**Comment by ozogxyz** [comment]
It works with `:Man`, as explained in `:h Man`. I understand the difference comes from running from the shell uses `groff`. It's a design choice then, not a bug, sorry for taking your time.
