### ISSUE TITLE
bug: `nvim_buf_set_extmark` has strange behavior when `set spell`

### ISSUE THREAD

**Issue by mrbeardad** [neovim/neovim#26771]
### Problem

Set extmarks on unicode has strange behavior when `set spell`.

https://github.com/neovim/neovim/assets/54128430/4c02f4ca-c7e1-49a4-878b-4c51cfd18552

### Steps to reproduce

```text
你好

```

1. `nvim --clean test.txt`
2. `:lua ns=vim.api.nvim_create_namespace("test")`
3. `:lua id=vim.api.nvim_buf_set_extmark(0, ns, 0, 0, {end_col=3,hl_group="Search"})`, `你` has 3 bytes so I set the `end_col` to 3
4. Now, only `你` is highlighted
5. `:set spell`
6. Now, both `你好` is highlighted
7. `:lua vim.api.nvim_buf_del_extmark(0, ns, id)`
8. `:lua vim.api.nvim_buf_set_extmark(0, ns, 0, 0, {end_col=2,hl_group="Search"})`, I set the `end_col` to 2 instead of 3
9. Now, both `你好` is highlighted
10. `:set nospell`
11. Now, only `你` is highlighted

### Expected behavior

Only `你` is highlighted in step 6 and 9.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1974+g714b07519

### Vim (not Nvim) behaves the same?

unknown

### Operating system/version

Microsoft Windows 11 Home 10.0.22621 N/A Build 22621

### Terminal name/version

Windows Terminal

### $TERM environment variable

empty

### Installation

scoop install neovim-nighlty --skip

**Comment by glepnir** [comment]
add spell = false should work 
```
vim.api.nvim_buf_set_extmark(0, ns, 0, 0, {end_col=2,hl_group="Search", spell= false})
```

**Comment by zeertzjq** [comment]
This seems to be a regression between 24b60b0f71e0ffbd09c827230ecb5a37e833cade and 07883940b2294e0ab32fb58e6624d18d9dd1715a

**Comment by mrbeardad** [comment]
Can you explain the option `spell` in more detail? The help doc about it is too brief.

> add spell = false should work
> 
> ```
> vim.api.nvim_buf_set_extmark(0, ns, 0, 0, {end_col=2,hl_group="Search", spell= false})
> ```

That works, thanks. The behaivor is different from 0.9, is it expected? I'll close this issue if it is yes.

**Comment by zeertzjq** [comment]
No.
