### ISSUE TITLE
when split kitty terminal window will cause neovim flash

### ISSUE THREAD

**Issue by tumarsh** [neovim/neovim#26770]
### Problem

open neovim in kitty then split a kitty panel. nvim will flash. relate issue https://github.com/kovidgoyal/kitty/issues/6953

### Steps to reproduce

``` 
map ctrl+space>e launch --location=hsplit --cwd=current 
map ctrl+space>i launch --location=vsplit --cwd=current
```
  use these map in kitty then do split neovim will flash

https://github.com/neovim/neovim/assets/112620329/87dd9d2d-d479-4942-88b8-d36d1acd02b1

### Expected behavior

neovim shouldn't flash i think

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

don't use

### Operating system/version

arch linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

aur

**Comment by zeertzjq** [comment]
What does "flash" mean? Can you provide a screen recording?

**Comment by tumarsh** [comment]
oh sry added and original link in kitty

**Comment by zeertzjq** [comment]
I'm not sure what behavior you expect. Can you try nightly version and see if it works as expected?

**Comment by glepnir** [comment]
still flash .. but in tmux it works fine

**Comment by tumarsh** [comment]
I don't know how it works on tmux, i don't use that. @zeertzjq  downloat a binary file and I tried, works same as 0.9.4

**Comment by tumarsh** [comment]
okay  i think it's issue of kitty.

**Comment by tumarsh** [comment]
okay  i think it's issue of kitty. wezterm works fine.
