### ISSUE TITLE
Text fragmentation when pasting in Neovim under WSL 

### ISSUE THREAD

**Issue by HakonHarnes** [neovim/neovim#26789]
### Problem

**Disclaimer:** I'm not sure if this is an issue with Neovim, WSL, or the interaction between them. I'm happy to move this issue elsewhere if this is not the right place for it. 

When pasting (e.g. through `CTRL+SHIT+V` or middle-click) under WSL the text gets fragmented into irregular chunks. This results in multiple `vim.paste()` calls, even for a single paste. The issue persists across multiple terminal emulators (Windows Terminal, Alacritty, Wezterm). The fragmentation is not consistent and varies between pastes. No issues on Windows 11 (non-WSL). Text is fragmented on Ubuntu WSL and Arch WSL.

The output of `:messages` after pasting is: 

```
Neovim is a
project
that seek
s to ag
gressive
ly refac
tor Vim
```

Fragmentation is not consistent:

```
Neov 
im is a 
project 
that see 
ks to aggresive 
ly refac
tor Vim
```

### Steps to reproduce

Under WSL, run `nvim -u minimal_init.lua` and copy a line, e.g.: 

```
Neovim is a project that seeks to aggressively refactor Vim
```

Then paste (e.g. through `CTRL+SHIFT+V` or middle-click) and observe the output of `:messages`.

**minimal_init.lua** 

```lua
vim.paste = (function(overridden)
	return function(lines, phase)
		for _, line in ipairs(lines) do
			print(line)
		end
		overridden(lines, phase)
	end
end)(vim.paste)
```

### Expected behavior

A single paste should result in only one `vim.paste()` call. The output of `:messages` should be: 

```
Neovim is a project that seeks to aggressively refactor Vim
```

### Neovim version (nvim -v)

NVIM 0.9.4 (also tested on nightly)

### Vim (not Nvim) behaves the same?

Not tested

### Operating system/version

Windows 11

### Terminal name/version

Window Terminal

### Installation

AUR

**Comment by zeertzjq** [comment]
I don't think this is a bug. There is nothing wrong with fragmentation.

**Comment by HakonHarnes** [comment]
Do you mind elaborating on why this isn't considered a bug? This fragmentation only occurs on WSL, not Windows, Linux or MacOS. Shouldn't Neovim's behaviour be consistent on all platforms? Why provide the option of overriding vim.paste if the behaviour is not consistent?

This issue is hindering the development of a plugin I am working on, and any insight that could lead to a solution or workaround is highly appreciated.

**Comment by zeertzjq** [comment]
If your plugin cannot handle fragmentation, isn't that a bug of your plugin?

**Comment by HakonHarnes** [comment]
Sure, I can make the plugin handle fragmentation. I guess I would need to check how much time passes between each vim.paste() call and reconstruct the fragmented text from there. 

It just seems like a hacky solution to me that shouldn't be needed, hence the bug report.

**Comment by HakonHarnes** [comment]
Just realized the `phase` parameter is especially useful for handling the fragmented paste. Should be able to make a viable solution now.
