### ISSUE TITLE
Neovim's colorscheme looks much less colorful than helix's in tty

### ISSUE THREAD

**Issue by Bekaboo** [neovim/neovim#26795]
### Problem

Neovim's colorscheme looks worse than helix's inside Linux tty, here is a comparison (neovim using default colorscheme on left, helix with shipped base16_transparent colorscheme on right, both have treesitter enabled)

![tty_neovim_helix](https://github.com/neovim/neovim/assets/76579810/55c10592-459e-40ff-a323-5c25c76c8d4f)

### Expected behavior

Neovim's default colorscheme should be as informative as helix's.

**Comment by clason** [comment]
That is intended. Neovim is minimal.

**Comment by gpanders** [comment]
I'll also add that I think the premise of the issue is questionable:

>Neovim's default colorscheme should be as informative as helix's.

This is a subjective judgment. Personally, I find the explosion of colors in the Helix screenshot to have very little informational content.

No single colorscheme can possibly please everyone, which is why both Neovim and Helix package many choices.

**Comment by Bekaboo** [comment]
Alright, I like Neovim's default colorscheme, just to make sure it is intended to be plain and minimal.

Could we change hl-Comment and hl-NormalFloat in the default colorscheme, specifically using silver/grey for comments and a light background for floating windows, this will make comments and floating window more distinguishable in tty, the following is some comparisons (original default colorscheme on the right):

![tty_neovim_default_colorscheme_00](https://github.com/neovim/neovim/assets/76579810/4f13df9e-087f-4adf-a12c-ea09a20cb370)
![tty_neovim_default_colorscheme_01](https://github.com/neovim/neovim/assets/76579810/a18c16e8-a98b-4675-8c5c-f6eaaa65a821)

**Comment by clason** [comment]
Yes, the scheme is minimal, and not up for debate (sorry).
