### ISSUE TITLE
Install documentation updated?

### ISSUE THREAD

**Issue by favetelinguis** [neovim/neovim#2679]
Is the install documentation up to data? When I try building neovim im failing to find unibilium which I guess is used for the new terminal functionality but this is not mentioned in the documentation?

**Comment by equalsraf** [comment]
@favetelinguis can you provide an error message and some info on your system. unibilium should be compiled as part of the build process, so you should not have to install it.

**Comment by favetelinguis** [comment]
Im current;y trying to package neovim for nixos. The problem is I dont know much about make or nixos :) However the things is that every resource that goes into the build that is not distributed with neovim needs to be explicitly defined. So does unibilium ship with neovi or is it pulled in from unline during the build process?

**Comment by fwalch** [comment]
If you're trying to package it, you can use either CMake (which is what the current, outdated NixOS package does, as far as I can see) or make. With CMake, all dependencies have to be installed systemwide (i.e. there has to be a NixOS package for them). With make, dependencies are downloaded and built, but statically linked into Neovim.

**Comment by Pyrohh** [comment]
I'll close this for now as there doesn't seem to be a specific problem which is mentioned.
