### ISSUE TITLE
`:UpdateRemotePlugins` reports error if *any* plugin host doesn't have plugins.

### ISSUE THREAD

**Issue by tomprince** [neovim/neovim#2680]
`s:RegistrationCommands` reports an error if there are no plugins found for a given host, but there may be plugins for other hosts. This makes it look the command has failed, even if it actually succeeded.

**Comment by Shougo** [comment]
It is just warning message.  Not error.
But, I think the message should be improved.

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/2769
