### ISSUE TITLE
Get Error When piping kitty @ ls to Neovim

### ISSUE THREAD

**Issue by jam1015** [neovim/neovim#26814]
### Problem

The Command `kitty @ ls` can be piped to programs like `cat`, `less`, `more` and `bat`.  When piping to `nvim --clean` I get the error

`Error: i/o timeout`. 

This also occurs when `nvim --clean` is the last in a pipeline.
The issue could be with Kitty and not Neovim. Making a [bug report over there](https://github.com/kovidgoyal/kitty/issues/6960) as well. 

### Steps to reproduce

1. Open a default instance of Kitty with remote control enabled.  From Alacritty I go: `kitty --config NONE -o allow_remote_control=yes`
2. In that instance of Kitty, go `kitty @ ls | nvim --clean` or `kitty @ ls | cat | nvim --clean`
3. After a long pause, that gives the error `Error: i/o timeout`. 
4.  Note that the problem does not occur when piping to other programs like `kitty @ ls | cat`
I can cat other files 

### Expected behavior

Should be pipe to `nvim --clean` normally. 

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1700008891     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"

### Vim (not Nvim) behaves the same?

No, piping is different for Vim

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

pacman

**Comment by zeertzjq** [comment]
It seems that this doesn't happen if kitty's `listen_on` is set to a Unix socket.

**Comment by zeertzjq** [comment]
https://github.com/kovidgoyal/kitty/issues/6960#issuecomment-1872672251
