### ISSUE TITLE
Add 'linewidth' parameter to 'formatting_options'

### ISSUE THREAD

**Issue by pronvis** [neovim/neovim#26820]
### Problem

`vim.lsp.buf.format` ignores `vim.opt.textwidth` value. Also, I could not specify line width with [formatting options](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions). Please add that ability

### Expected behavior

inserting new line after on formatting `vim.opt.textwidth`

**Comment by mfussenegger** [comment]
> Also, I could not specify line width with [formatting options](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions).

This is up to the specification maintainers, you can raise an issue in https://github.com/microsoft/language-server-protocol/ 

Until the specification gets extended, and language servers start using it, there's no way we can make use of `vim.opt.textwidth`

**Comment by pronvis** [comment]
@mfussenegger How about adding line width parameter into https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions - is it possible?
