### ISSUE TITLE
Return type depending on paramater for functions in src/nvim/eval.lua

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#26825]
### Problem

Currently, functions in [`eval.lua`](https://github.com/neovim/neovim/blob/master/src/nvim/eval.lua) can only have one return type, which is independent of parameters. This works for most functions, but there are some, that return different types depending on some parameter, so they use a union type to annotate that. This results in a diagnostic by the LSP when the return value is passed to a function that only takes one of the types.
An example of this is `expand()` which returns `string|string[]`, and thus results in a diagnostic when passed to a function that takes only strings.

### Expected behavior

Make it so that functions can have multiple return types depending on the parameter type. And when the _meta file is generated for these functions, it will generate two copies, basically overloading the function.

For example, let's have a function called `foo(list)` which returns `string` if list is falsy or `string[]` if list is truthy. Then the table for the function in `eval.lua` would look something like this:
```lua
foo={...,returns={{list='false|nil'}='string',{list='true|string|number|...'}='string[]'}},
```
Which would generate the meta file:
```lua
---@param list true|number|string|...
---@return string[]
function vim.fn.foo(list) end

---@param list nil|false
---@return string
function vim.fn.foo(list) end
```

**Comment by lewis6991** [comment]
We already support this. See https://github.com/neovim/neovim/blob/master/runtime%2Flua%2Fvim%2F_meta%2Fvimfn.lua#L2478

**Comment by altermo** [comment]
Ok.
