### ISSUE TITLE
Treesitter regression for c parser?

### ISSUE THREAD

**Issue by Danielkonge** [neovim/neovim#26837]
### Problem

In Neovim 0.9.4 I can capture and highlight parentheses in macros in C code, but it doesn't seem to work in 0.10.

0.9.4:
<img width="160" alt="Screenshot 2024-01-01 at 16 15 45" src="https://github.com/neovim/neovim/assets/7075380/d8694b61-415d-4c0e-b67a-5989d4c833a4">

0.10:
<img width="154" alt="Screenshot 2024-01-01 at 16 14 48" src="https://github.com/neovim/neovim/assets/7075380/6d6b2eda-29be-419f-b7f6-a6401748610c">

I think in general there is a problem with capturing stuff inside a macro in 0.10:
<img width="1702" alt="Screenshot 2024-01-01 at 16 14 22" src="https://github.com/neovim/neovim/assets/7075380/6a2e5d94-cb41-4056-96c2-112a0eda8b16">

Note: The above doesn't capture anything. This shouldn't be because of the ERROR, since we can usually capture inside an ERROR like here:
<img width="1694" alt="Screenshot 2024-01-01 at 16 24 11" src="https://github.com/neovim/neovim/assets/7075380/9d12bc91-5f49-4d5d-aaf5-64b2437f71c9">

I wanted to test something similar for 0.9.4 and show that we can capture it there, but I don't think there is something like the query editor in 0.9.4? Is there some way I could better test this?

Also, is this considered a neovim bug or a parser bug? (Should I report this somewhere else?)

Note: The `c` parser parses macros using language injections, if that helps clarify what might be causing this issue. 

### Steps to reproduce

`nvim test.c`
Write: `#define TEST (-1)`
`:w<CR>`
`:InspectTree<CR>`
`o`
Write `(parenthesized_expression) @test` in the query editor (or `(number_literal) @test`) and place the cursor on `@test` in normal mode.

Note that we can't capture any of the above.

### Expected behavior

Like my last picture above, we should capture the corresponding queries. 

### Neovim version (nvim -v)

v0.10.0-dev-2005+gf69658bc3-Homebrew

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 14.2.1

### Terminal name/version

wezterm

### $TERM environment variable

wezterm

### Installation

homebrew

**Comment by clason** [comment]
Yes, we have tightened up (improved) the self-injections for macros. Feel free to customize the injection queries if you want different highlighting.

(And homebrew nightly "releases" -- as opposed to actual releases -- don't come with treesitter parsers, so make sure this is not the issue you're seeing. Also make sure you're not using the nvim-treesitter queries, which may - intentionally -- differ.)

**Comment by Danielkonge** [comment]
> Yes, we have tightened up (improved) the self-injections for macros. Feel free to customize the injection queries if you want different highlighting.
> 
> (And homebrew nightly "releases" -- as opposed to actual releases -- don't come with treesitter parsers, so make sure this is not the issue you're seeing. Also make sure you're not using the nvim-treesitter queries, which may - intentionally -- differ.)

I have the parsers installed, and I mainly made this issue to see if I could figure out what causes this problem. From what I can tell it was a problem with my queries, but what confused me was that the `c` parser and `rust` parser work differently, so I have to write language specific code that I didn't think would be necessary. (Rust also uses language injections for macros, but they don't work the exact same way.)

**Comment by clason** [comment]
Yes, because macros don't work the exact same way. Queries very much are language-specific.

**Comment by Danielkonge** [comment]
> Yes, because macros don't work the exact same way. Queries very much are language-specific.

I think I was a bit unclear, I know about the difference in the queries. What I needed to do was different behavior in `LanguageTree:register_cbs { on_changedtree = function(changes, tree) ... end }` based on the language, which I hadn't needed for any language other than c/cpp. 

Anyways, thank you for the quick responses.
