### ISSUE TITLE
RFE: please provide lua 5.4 support

### ISSUE THREAD

**Issue by kloczek** [neovim/neovim#26844]
### Problem

Currently neovim do not support lua 5.4 support.

### Expected behavior

It would be good to have updated lua 5.4 support without any compatibility modules likelua-bit32.

**Comment by bfredl** [comment]
Unfortunately there is no luajit support for 5.4 (or any suitable replacement), until that happens this is unrealistic.

**Comment by kloczek** [comment]
Is it really necessary to use luajit?
Why plain lua is not enough?

**Comment by lewis6991** [comment]
Neovim's Lua runtime is written for Lua 5.1. Adding support for 5.4 is not feasible as 5.4 is not backwards compatible with 5.1.

**Comment by kloczek** [comment]
Lua 5.1.x is no longer maintained ad has even many security issues.

**Comment by bfredl** [comment]
> Lua 5.1.x is no longer maintained ad has even many security issues.

Good that luajit is actively maintained then.

**Comment by lewis6991** [comment]
> Lua 5.1.x is no longer maintained ad has even many security issues.
> 

PUC lua 5.1, the implementation, is not maintained. Lua 5.1, the language spec, does not require any maintenance.

**Comment by bfredl** [comment]
Also, the issue tracker is not for resolved issues (the reasons to choose luajit over 5.4 are well documented in the FAQ, and other places). There are other places for open ended discussions and asking for clarifications etc (like reddit, discussions, etc).
