### ISSUE TITLE
Vertical centering when leaving the viewport

### ISSUE THREAD

**Issue by defr0std** [neovim/neovim#26843]
### Problem

The viewport here is the visible lines in the Neovim window. By leaving the viewport I mean any action which moves the cursor outside the viewport, for example:
* Navigating to the next search occurrence (`n` or `N`).
* Navigating to the LSP definition/declaration or any other symbol.
* `C-o` and `C-i`.
* `cnext` and `cprev`
* and many others

The editor behavior when you leave the viewport is quite chaotic - sometimes the cursor is in the top of the window, sometimes in the bottom, other times somewhere in the middle. This is a little disorienting because after each such action, you need a moment to locate the cursor on the screen.

Many folks override mappings for `n` and `N` to do `n` and `zz`, others are also doing this for LSP navigation, [example](https://www.reddit.com/r/neovim/comments/kxoyxt/centering_screen_after_lsp_definition/). 

Could this behavior be provided by Neovim itself? Hopefully, it could be implemented in a single place rather than handled for each case separately in the user configs.

### Expected behavior

When the cursor is moved outside of the current viewport (visible lines in the current window), center the window vertically (`zz`). This should apply to all cases except for certain exclusion list: moving the cursor with `hjkl`, `C-d/C-u`, and some others. If there is a general interest in this behavior, we could compile a full list.

This behavior could be enabled by a new option.

**Comment by Sam-programs** [comment]
Instead of a list of keys to disable, Could it only center when fully leaving the viewport?
In that case an autocmd like this would work:
```lua
vim.api.nvim_create_autocmd("WinScrolled", {
    pattern = "*",
    callback = function()
        local curwin = vim.api.nvim_get_current_win()
        local changes = vim.v.event[tostring(curwin)]
        if(not changes) then
            return
        end
        -- don't center floating windows
        local config = vim.api.nvim_win_get_config(curwin)
        if config.relative ~= "" then
            return
        end
        -- only center when fully leaving the viewport
        local height = vim.api.nvim_win_get_height(curwin)
        if changes.topline >= height then
            vim.api.nvim_input('<cmd>normal! zz<cr>')
        end
    end,
})
```
