### ISSUE TITLE
`syntax [enable|on]` leads to `start` filetype plugins on the `packpath` being sourced prematurely

### ISSUE THREAD

**Issue by mrcjkb** [neovim/neovim#26859]
### Problem

When calling `syntax enable` or `syntax on` (or `vim.cmd.syntax(...)`) in init.lua, Neovim sources filetype plugins on the `packpath` immediately, when starting Neovim with a filetype as an argument.

This behaviour is not reproducible in Vim.

### Steps to reproduce

I have created [a repository](https://github.com/mrcjkb/neovim-syntax-bug) to reproduce this issue.
It contains examples in Lua (`startup-lua` directory) and Vimscript (`startup-vimscript` directory) , which each contains:

- An init file that calls `syntax on` and then sets `vim.g.init_lua_sourced = true`.
- A `pack/debug/start/myPlugin/ftplugin/rust.lua` (and `rust.vim` respectiveley), which prints an error if `vim.g.init_lua_sourced` is not set.

To reproduce, call

```console
# from the startup-lua directory
nvim --cmd "set packpath^=$PWD"  -u init.lua main.rs`
```
or 

```console
# from the startup-vimscript directory
nvim --cmd "set packpath^=$PWD" -u init.vim main.rs`
```

-> This prints an error message, because the filetype plugin is sourced as soon as `syntax on` or `syntax enable` is called, before the init file is sourced.

To confirm that this is a Neovim bug, and not present in Vim, one can run the same command from the startup-vimscript directory (which enables the `filetype` plugin):

```console
# from the startup-vimscript directory
vim --cmd "set packpath^=$PWD"  -u init.vim main.rs`
```

-> Echos `init.vim sourced before ftplugin on packpath/start`; no error message is printed.

Versions used:

- NVIM v0.10.0-dev-eae6727
- NVIM v0.9.4
- vim 9.0 (Huge version without GUI.)

Note: I have reproduced this on NixOS, but the behaviour has also [been observed on MacOS](https://github.com/mrcjkb/rustaceanvim/discussions/77).

### Expected behavior

No error message is printed, because the init file is sourced completely before the filetype plugin.

### Neovim version (nvim -v)

v0.10.0-dev-eae6727

### Vim (not Nvim) behaves the same?

no, vim 9.0 (Huge version without GUI.)

### Operating system/version

NixOS 24.05 unstable + macOS 14.1.1

### Terminal name/version

alacritty 0.12.3 

### $TERM environment variable

alacritty

### Installation

nixpkgs

### Additional info

<details>
<summary>
Stack trace (lua version)
</summary>

```
Error detected while processing BufNewFile Autocommands for "*":
Error executing lua callback: ...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:30: Error executing lua: ...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:31: BufNewFile Au
tocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..script /home/mrcjk/playground/neovim/neovim-syntax-bug/startup-lua/pack/debug/start/myPlugin/ftplugin/rust.
lua: Vim(runtime):E5113: Error while calling lua chunk: .../startup-lua/pack/debug/start/myPlugin/ftplugin/rust.lua:2: init.lua sourced after ftplugin on packpath/start
stack traceback:
        [C]: in function 'error'
        .../startup-lua/pack/debug/start/myPlugin/ftplugin/rust.lua:2: in main chunk
        [C]: in function 'nvim_cmd'
        ...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:31: in function <...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:30>
        [C]: in function 'nvim_buf_call'
        ...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:30: in function <...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        ...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:31: in function <...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:30>
        [C]: in function 'nvim_buf_call'
        ...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:30: in function <...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:30: in function <...neovim-unwrapped-eae6727/share/nvim/runtime/filetype.lua:10>
```

</details>

**Comment by mrcjkb** [comment]
Note: It appears that the order of the CLI arguments is important here.

Setting the packpath last does not reproduce the behaviour (but the order of arguments doesn't matter for Vim).
However, this may be an issue for plugin managers like minpac, where the packpath may be set before plugin configuration globals are set.

[This](https://github.com/mrcjkb/neovim-fork/blob/b3eda5e73f65092d50ccd27a0373e8b9fad076b0/runtime/lua/vim/filetype/options.lua#L5C1-L5C1) is where Neovim's filetype.lua searches for filetype plugins.

**Comment by zeertzjq** [comment]
This sounds similar to #19008

**Comment by mrcjkb** [comment]
Yep, looks like this is a duplicate.
