### ISSUE TITLE
Delete the char will delete the char before in the cmdline window

### ISSUE THREAD

**Issue by gh-liu** [neovim/neovim#26851]
### Problem

When option `foldcolumn`  be set, delete the char  will delete the char before in the cmdline window.
```lua
vim.o.foldcolumn = "1"
```

### Steps to reproduce

1. nvim --clean
2. :lua vim.o.foldcolumn = "1"
3. type `<C-f>` to open the cmdline window
4. delete a char in the cmdline window

### Expected behavior

delete the char befor the cursor, not the char before the char.

### Neovim version (nvim -v)

v0.10.0-dev-2008+g4ee656e4f

### Vim (not Nvim) behaves the same?

no,  8.2.2121

### Operating system/version

5.15.133.1-microsoft-standard-WSL2

### Terminal name/version

WezTerm 20230712-072601-f4abf8fd

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by glepnir** [comment]
`:set fdc=1` then open cmdline-window assertion failed
```
drawline.c:392: draw_foldcolumn: Assertion `wlv->off == 0' failed.
``

relate https://github.com/neovim/neovim/pull/26798
