### ISSUE TITLE
Fallback to vimrc if nvimrc doesn't exist

### ISSUE THREAD

**Issue by FSMaxB** [neovim/neovim#2685]
Many users might just be symlinking `.nvimrc` to `.vimrc` and `.nvim` to `.vim`. Why not use `.vimrc` and `.vim` by default if `.nvimrc` and `.nvim` don't exist?

**Comment by ladislas** [comment]
:+1:

**Comment by syswow** [comment]
:+1:

**Comment by demonking** [comment]
:+1 it would be more familiar, because the software is called neovim not vim ;)
Also maybe change the env variable "VIMINIT" to "NVIMINIT" ?

**Comment by fwalch** [comment]
> the software is called neovim not vim

Isn't that more of an argument for having just `.nvimrc`?

> Also maybe change the env variable "VIMINIT" to "NVIMINIT" ?

See #1927 for that.

**Comment by simonweil** [comment]
:+1:

**Comment by Pyrohh** [comment]
Nvim isn't completely compatible with Vim, so I don't think this is a good idea. I think this change might give off the impression that any `.vimrc` will work as a drop in replacement in Nvim, which isn't true sometimes.

**Comment by justinmk** [comment]
We can show a warning, but silently using vimrc is just a recipe for pain and confusion. Furthermore, per https://github.com/neovim/neovim/issues/78 we may not support [n]vimrc at all, but rather will require a valid XDG config or will fallback to XDG defaults.

> Also maybe change the env variable "VIMINIT" to "NVIMINIT" ?

This definitely will not happen. Discussed to death in #1927.
