### ISSUE TITLE
Add a api to detecte if a normal command is completed, behave like `:normal` but return a boolean

### ISSUE THREAD

**Issue by mrbeardad** [neovim/neovim#26864]
### Problem

I want to write a multi-cursor plugin by using `q` recording, the largest chanllenge is how to detect if the keys that recorded is a completed command. I've noticed that [`:normal`](https://neovim.io/doc/user/various.html#%3Anormal) will interrupt the incomplete command, but it returns nothing, so I can't get if the keys that executed by `:normal` is completed or not.

### Expected behavior

`vim.api.normal(keys)` return true if `keys` is completed, otherwise, return false. Thus, I can re-call `vim.api.normal(keys)` on next key pressing.

**Comment by zeertzjq** [comment]
Do the keys come from your plugin? If yes, you can add a `<Cmd>` ... `<CR>` at the end.

**Comment by mrbeardad** [comment]
The `keys` is what user typed, I get it from recording register, and I want to execute them again by `vim.cmd.normal(keys)` if they are completed.

**Comment by zeertzjq** [comment]
When did you get it from the recording register? During the recording or after user has ended the recording?

**Comment by mrbeardad** [comment]
You could take a glance [here](https://github.com/mrbeardad/nvim-multi-cursor/blob/main/lua/nvim-multi-cursor/init.lua#L174), in brief, I'm trying to end the recording when the keymaps are resolved, but it works not well for now. For example, `ds` is a user customized key map to delete surrounding char, `ds(` is a completed normal command, but the handler in my plugin is triggered when `ds` are typed.

**Comment by zeertzjq** [comment]
You may be interested in the `SafeState` autocommand available in v0.10.0-dev.

**Comment by mrbeardad** [comment]
nice! Thanks!
