### ISSUE TITLE
missing documentation?

### ISSUE THREAD

**Issue by SyedFasiuddin** [neovim/neovim#26863]
### Problem

I just `brew install neovim` and did `:h ft_rust.txt` the help file contains 239 lines while in here the same file contains 450+ lines. 

The release of v0.9.4 and v0.9.5 both contain `ft_rust.txt` file with 239 lines. Which is true for commit: `6884f017b53369d6c9b06ddd3aedeb642dbd24a8` which was two years back. And the file `ft_rust.txt` has been updated since then and before release of v0.9.4 I have not checked if the same is true for other document files.

### Steps to reproduce

`brew install neovim`
`nvim --clean`
`:h ft_rust.txt`

### Expected behavior

Same `ft_rust.txt` file as I can see here with 400+ lines

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS Sanoma

### Terminal name/version

Terminal.app

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by zeertzjq** [comment]
The source code of v0.9.4 is here: https://github.com/neovim/neovim/tree/v0.9.4
