### ISSUE TITLE
API to get abbreviations

### ISSUE THREAD

**Issue by Bekaboo** [neovim/neovim#26867]
### Problem

Related to #19198.

We can now create abbreviations using `vim.api.nvim_set_keymap`/`vim.api.nvim_buf_set_keymap`  using modes `ia`, `ca`, and `!a`, but `vim.api.nvim_get_keymap`/`vim.api.nvim_buf_get_keymap` does not get corresponding abbreviations using these modes, which can be confusing.

### Expected behavior

`vim.api.nvim_get_keymap`/`vim.api.nvim_buf_get_keymap` accepts `ia`, `ca` and `!a` as modes and return corresponding abbreviations.

**Comment by Bekaboo** [comment]
`nvim_del_keymap()` and `nvim_buf_fel_keymap()` may also be related.

**Comment by zeertzjq** [comment]
`maplist()` can get abbreviations, but it always uses the current buffer.
