### ISSUE TITLE
Terminal mode sometimes hogs mouse events

### ISSUE THREAD

**Issue by thialfi17** [neovim/neovim#26889]
### Problem

When using ":terminal" with a program that handles mouse events such as tmux/GNU screen, mouse events are blocked for clicking on the tabline while in Terminal mode. I dug into this slightly more to see if it was an easy fix and traced the source of the problem to the `send_mouse_event` function inside [terminal.c](https://github.com/neovim/neovim/blob/master/src/nvim/terminal.c#L1441) where the column of the mouse event is checked to determine if the click is inside the terminal window, but the row isn't checked. This means that if the terminal window is to the right of the elements in the tabline then the mouse events are correctly ignored by the terminal and the elements are clickable. If the terminal window starts to the left of the elements then the mouse events are forwarded to the terminal and the UI is unresponsive.

I have not investigated how this affects other UI elements that might be clickable.

### Steps to reproduce

nvim --clean
:tabe
:terminal
tmux (might need to perform "<prefix>:set mouse")

try and click the first tab

### Expected behavior

Clicking on the tabline (or any other UI elements) is correctly handled even when in a Terminal buffer in Terminal mode.

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

no, version 9.0.2167

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.12.3 (5efb0690)

### $TERM environment variable

xterm-256color

### Installation

pacman

**Comment by zeertzjq** [comment]
I think the same bug applies to `getmousepos()`: it still finds a window even if the click is on tabline.
