### ISSUE TITLE
Windows: titlestring does not work in cmd.exe

### ISSUE THREAD

**Issue by Passw** [neovim/neovim#26880]
### Problem

titlestring does not work under Windows 10 PowerShell 7.4.0 or cmd.exe

vim
![vim](https://github.com/neovim/neovim/assets/5151456/c28e92aa-8a90-44be-98f6-0770dcdcd27f)

nvim
![nvim](https://github.com/neovim/neovim/assets/5151456/f3c9bbaf-fc02-4c6f-b424-490aa0e55ab7)

### Steps to reproduce

set title
auto BufEnter * let &titlestring = expand("%:p")
set titlestring=%<%F%=%l/%L-%P titlelen=70

### Expected behavior

show `titlestring` correctly

### Neovim version (nvim -v)

NVIM v0.10.0-dev-bdfea2a

### Vim (not Nvim) behaves the same?

Vim works with well , v9.1.0004

### Operating system/version

Windows 10

### Terminal name/version

cmd.exe or PowerShell 7.4.0

### $TERM environment variable

256color

### Installation

build from repo

**Comment by lsvmello** [comment]
I believe this is a terminal issue, not Windows specific. Can anyone on Linux or Mac confirm?
I checked that everything is working as expected until the call to `resettitle()` function.

https://github.com/neovim/neovim/blob/4ffc20c9515294481486e81271a8edeeff203140/src/nvim/buffer.c#L3491-L3495

But `ui_call_set_icon()` and `ui_call_set_title()` are the ones that are not doing anything. If I understand correctly they just emit events that should be handled by whoever is embedding Neovim, right? But the terminal is not aware of that.

**Comment by justinmk** [comment]
Does it work with Windows Terminal? https://github.com/microsoft/terminal

Not sure if we still support titlestring for cmd.exe (aka "console").

**Comment by zeertzjq** [comment]
`256color` doesn't look like a correct `$TERM` environment variable.

**Comment by zeertzjq** [comment]
Can you try the artifact produced in https://github.com/zeertzjq/neovim/actions/runs/7719574557 and see if it works?
