### ISSUE TITLE
`Matchit` malfunctions under specific conditions.

### ISSUE THREAD

**Issue by gen740** [neovim/neovim#26895]
### Problem

`Matchit` malfunctions under specific conditions.

### Steps to reproduce

- Create the following file `minimal.vim`
```vim
call setline(1, [" (", "any text", ")"])
normal f(
call feedkeys("v%")
```
- `nvim --clean -u minimal.vim`

### Expected behavior

Selected the region enclosed by `()`.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2037+ge09adfdcf

### Vim (not Nvim) behaves the same?

yes (but `matchit` enabled)

### Operating system/version

macOS 14.2.1

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

homebrew (with "--head" option)

**Comment by zeertzjq** [comment]
This should be reported to https://github.com/chrisbra/matchit
