### ISSUE TITLE
Command :language "not available in this version" on MacOS

### ISSUE THREAD

**Issue by thirstyice** [neovim/neovim#26894]
### Problem

`:language` gives `E319: The command is not available in this version`

### Steps to reproduce

`nvim --clean`
`:language`

### Expected behavior

Nvim to execute the :language command

### Neovim version (nvim -v)

0.9.5 release

### Vim (not Nvim) behaves the same?

Vim behaves as expected

### Operating system/version

macOS Sonoma 14.2.1

### Terminal name/version

Neovide, macOS Terminal

### $TERM environment variable

xterm-256color

### Installation

Install from download

**Comment by bfredl** [comment]
Ugh this is because we didn't backport https://github.com/neovim/neovim/pull/25602 which was a direct prerequisite for the changes we did packport. So the mac os build is severely broken (amazingly not broken enough to simply fail to compile)

**Comment by clason** [comment]
So the refactor worked :) (Only the -- optional -- functionality that requires libintl fails, not the whole house of cards.)

**Comment by dundargoc** [comment]
This is fixed.
