### ISSUE TITLE
colorscheme not loaded correctly with TRUE_COLOR

### ISSUE THREAD

**Issue by mikkeloscar** [neovim/neovim#2689]
I have the following in my `.vimrc`:

```viml
if has('nvim')
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1

  set background=dark
  let g:solarized_italic=0
  "au VimEnter * colorscheme solarized
  colorscheme solarized
endif
```

When I run nvim it looks like this:
![nvim_3](https://cloud.githubusercontent.com/assets/128566/7672833/51db31de-fd02-11e4-91b3-8933c8efd088.png)

If I uncomment `au VimEnter * colorscheme solarized` and run it, then it looks like this:
![nvim_1](https://cloud.githubusercontent.com/assets/128566/7672835/680914c6-fd02-11e4-9527-cd1ea4a86a48.png)

In the first image the bottom line ([vim-airline](https://github.com/bling/vim-airline)) get the correct colorscheme/styling, but the rest of the UI doesn't get the correct colors. In the second image the UI gets the correct colors, but the styling of vim-airline gets messed up.

If i run `:colorscheme solarized` after nvim is launched then everything looks right:
![nvim_2](https://cloud.githubusercontent.com/assets/128566/7672844/e4285698-fd02-11e4-8a11-7eb2e33098ac.png)

I believe it should work without using `au VimEnter * colorscheme solarized` but something doesn't work when using `TRUE_COLOR=1`. If I don't enable true colors then the colorscheme is loaded (although not looking great) without the `VimEnter` command.

**Comment by bounceme** [comment]
It seems like the true color option is sensitive to some of the gui related things that color schemes use. There is another simpler version of solarized here:
https://github.com/romainl/flattened
that works as it should.

**Comment by justinmk** [comment]
@mikkeloscar  If a colorscheme has *both* `cterm{fg,bg}` and `gui{fg,bg}` properties, nvim has to decide which one to use. Does it work If you remove all the `cterm*` properties from the colorscheme?

**Comment by ZyX-I** [comment]
> In the second image the UI gets the correct colors, but the styling of vim-airline gets messed up.

I do not know whether it is the problem with airline, but if you tried this with powerline (in Vim) you would see similar result because `au VimEnter *` *without* `nested` after pattern is not raising `ColorScheme` event *and* `:colorscheme` command (more specifically `hi clear` statements and at the start of each colorscheme) clears custom powerline highlight groups.

**Comment by mikkeloscar** [comment]
Thanks guys, just tested a bunch of other colorschemes and they don't have this problem.

Since solarized ins't being maintained any longer AFAIK I don't really care to find the issue with that particular colorscheme.

I'll leave this issue open and let you decide whether it is still relevant to neovim in some way or if should be closed.

Thanks for your time and continued work on neovim! :)

**Comment by frankier** [comment]
For anyone else interested I've made a fork of solarized with only the true color version: https://github.com/frankier/neovim-colors-solarized-truecolor-only
