### ISSUE TITLE
Add option to vim.lsp for dynamic validation of _if lsp should connect_ to buffer

### ISSUE THREAD

**Issue by miversen33** [neovim/neovim#26904]
### Problem

I have noticed that certain LSPs (such as [ruff-lsp](https://github.com/astral-sh/ruff-lsp)) fall over when they are attached to a buffer that has no backing file. That lead me to looking at how to "prevent" an LSP from connecting to a buffer if there is no file associated with the buffer. Unless I am missing something, that seems to be (currently) impossible. While we have the ability to _sort of_ specify which file types to associate the lsp with, we have no way of doing stuff like "only attach to a buffer if there is a file" or any other sort of complex logic.

### Expected behavior

In theory this should be pretty easy to add (provided the neovim team is open to a PR for it). Adding a new option to the lspconfig spec for something like `lsp.ClientConfig.pre_connect` and look for true on its return would work. You could put this logic check right here: https://github.com/neovim/neovim/blob/3734519e3b4ba1bf19ca772104170b0ef776be46/runtime/lua/vim/lsp.lua#L534-L535

Note, there is a spot in the LSP for this kind of logic with `lsp.ClientConfig.before_init` however that seems to be being used to allow the user to modify the parameter being passed to the LSP. It doesn't appear that the output of this function is being consumed beyond "did it work" though so we could potentially utilize the the return of this function to indicate if we _should_ connect or abort as well. 

I am not **super** familiar with the LSP spec so I have no idea if this idea goes against that. If however, this is something that neovim is open to, I feel relatively confident I can get it put together :)

**Comment by mfussenegger** [comment]
>  That lead me to looking at how to "prevent" an LSP from connecting to a buffer if there is no file associated with the buffer. Unless I am missing something, that seems to be (currently) impossible

It's very much possible. Currently Neovim provides 3 functions to control clients:

- `vim.lsp.start_client()`
- `vim.lsp.buf_attach_client()`
- `vim.lsp.start()` (combination of both, `start_client()` and `buf_attach_client()`)

You can just _not_ call `buf_attach_client` if you don't want it to attach to a buffer that's not saved on disk.
