### ISSUE TITLE
VIMRUNTIME error

### ISSUE THREAD

**Issue by khezerberg** [neovim/neovim#26906]
### Problem

I followed all the build instructions from the BUILD.md and I have all the required deps.
I haven't changed anything on any of the files after git clone and I even ran and removed the previous nvim version;
```sh
sudo rm -f /usr/local/bin/nvim && sudo rm -rf /usr/local/share/nvim
```

however; after running the final step in the build step: sudo make install
I open nvim only to be greeted by an error message:

**E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim**

when I run: **echo $VIMRUNTIME**
inside nvim I get: **/usr/local/share/nvim**

it seems that nvim is looking for **/usr/local/share/nvim/syntax/syntax.vim** but the real path of syntax.vim is: **/usr/local/share/nvim/runtime/syntax/syntax.vim**

I'm not sure what I did wrong as I followed all the steps as they were in BUILD.md. 

I have already tried to make distclean, delete previous nvim and reinstall nvim and no matter what I do I get the same error after I open nvim.

If anybody could please help me or point me in the right direction, I would highly appreciate it.

### Steps to reproduce

```sh
sudo rm -f /usr/local/bin/nvim && sudo rm -rf /usr/local/share/nvim
```

Then:
```sh
cd neovim/ && make distclean
```

Afterwards:
```sh
make CMAKE_BUILD_TYPE=RelWithDebInfo
```
Finally:
```sh
sudo make install
```
It builds successfully but upon opening nvim:
E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim

### Expected behavior

nvim opens with no error messages.

### Neovim version (nvim -v)

nvim v0.10.0-dev-2039+g583c1de17

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux x86_64

### Terminal name/version

alacritty 0.13.0

### $TERM environment variable

xterm-256color

### Installation

built from source

**Comment by clason** [comment]
> when I run: echo $VIMRUNTIME
> inside nvim I get: /usr/local/share/nvim

That is incorrect; it should be `/usr/local/share/nvim/runtime`.

Do you have write permissions on `/usr/local`?

**Comment by khezerberg** [comment]
> > when I run: echo $VIMRUNTIME
> > inside nvim I get: /usr/local/share/nvim
> 
> That is incorrect; it should be `/usr/local/share/nvim/runtime`.
> 
> Do you have write permissions on `/usr/local`?

I do not. I'm on a fresh install of Arch. I thought it was normal to not have write permission to **/usr/local/** as that path should only have read permission? 

Am I wrong? if so, how do I fix it? 
Thank you for the timely reply.

**Comment by wookayin** [comment]
Is there any other config in your shell in your nvim config that sets `$VIMRUNTIME`? That's sounds very strange that `$VIMRUNTIME` points to a wrong directory even if you did a clean-install.

In your shell, please try:

```bash
env | grep VIMRUNTIME

bash -c 'echo $VIMRUNTIME'

nvim --clean --headless -c 'echo $VIMRUNTIME' -c 'q'
```

**Comment by khezerberg** [comment]
> Is there any other config in your shell in your nvim config that sets `$VIMRUNTIME`? That's sounds very strange that `$VIMRUNTIME` points to a wrong directory even if you did a clean-install.
> 
> In your shell, please try:
> 
> ```shell
> env | grep VIM
> 
> bash -c 'echo $VIMRUNTIME'
> 
> nvim --clean --headless -c 'echo $VIMRUNTIME' -c 'q'
> ```

thank you so much for pointing me in the right direction. It was definetily that. I managed to remove all nvim and did a clean install. Turns out it was my previous config.lua that had incorrectly set the path of VIMRUNTIME, but I'm still not sure why. Problem solved.
