### ISSUE TITLE
Arbitrary data for extramarks

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#26928]
### Problem

Currently, the way to store extra information about an extramark is by creating a separate table and manually adding/deleting extramarks with some data. This makes using extramarks a lot harder.

### Expected behavior

Extramarks would get a new field that could be any vim-type and would only be used by plugins and UIs.

**Comment by clason** [comment]
What would be the use case? Note that extmarks are _extremely_ performance sensitive, so potentially heavy payloads must have a very strong justification.

**Comment by altermo** [comment]
The places that I want to use them:
1. Using extramarks together with UI for graphics; where the information about the graphics could be stored in the extmark.
2. A multi-cursor plugin, where each cursor is an extmark and could be separately controlled to be active or not active.

**Comment by altermo** [comment]
Maybe a field for the extmark which would be called on extmark the deletion would be better, as then managing a separate table with the extmark information would become easier.

**Comment by lewis6991** [comment]
I don't think the extra complexity here is justified and the use cases aren't strong enough. Extmarks are mainly intended for decorations.

I don't see a problem with the current way of storing data.

**Comment by altermo** [comment]
Okay, the points are good, so I'll close this.

The problem of how to keep the table with extmark ids and the extramarks in sync is still a problem, so I'll open up a feature request about adding on_delete for extmarks, which would make it easy to keep the table with extmark ids and the extramarks in sync.
