### ISSUE TITLE
vim.opt don't work correctly for ErrorFormat

### ISSUE THREAD

**Issue by bogado** [neovim/neovim#26923]
### Problem

When I set `ErrorFormat` using lua `vim.opt.errorformat = { 'XXX', 'YYY' }`, the result is `XXX,YYY` and not `XXX:YYY` as expected for `ErrorFormat`. 

### Steps to reproduce

:lua vim.opt.errorformat = { 'XXX', 'YYY' }
:set errorformat
errorformat=XXX,YYY

### Expected behavior

:lua vim.opt.errorformat = { 'XXX', 'YYY' }
:set errorformat
errorformat=XXX:YYY

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: RelWithDebInfo LuaJIT 2.1.1692716794 Compilation: /usr/bin/gcc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include/luv -I/builddir/build/BUILD/neovim-0.9.4/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.9.4/redhat-linux-build/include -I/builddir/build/BUILD/neovim-0.9.4/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.9.4/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

no lua in vim

### Operating system/version

linux fedora 39

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

rpm

**Comment by bogado** [comment]
I think I misunderstood something.

**Comment by wookayin** [comment]
```
vim.opt.errorformat:get() == { 'XXX', 'YYY' }
vim.o.errorformat == XXX,YYY
```

**Comment by bogado** [comment]
I believe that I misunderstood the help on errorformat and therefore thought that there was a bug where there's none.
