### ISSUE TITLE
When v:relnum is used in statuscolumn it doesn't update as often as expected

### ISSUE THREAD

**Issue by blankname** [neovim/neovim#26934]
### Problem

Described along with the reproduction steps.

### Steps to reproduce

`nvim --clean -c 'let &statuscolumn=\'%{v:relnum}\''`
Add some lines, press escape and move between the lines.

I would expect the relative line numbers to update as you move between lines, but they are only updated when you add new lines.
The relative line numbers in the `statuscolumn` start updating if you turn relative line numbers on via `set relativenumber`.

Even when `relativenumber` is set, the relative line numbers only update for the first visual line of a wrapped line.
Setting `relativenumber` or `number` also appears to add `numberwidth` padding after the status column, but while unexpected this is pretty useful.

### Expected behavior

The relative line numbers in the `statuscolumn` to update in the scenarios described above.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2042+g28c183b38c Build type: RelWithDebInfo LuaJIT 2.1.1702233742

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux archlinux 6.6.7-arch1-1

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

Arch User Repository

**Comment by luukvbaal** [comment]
> I would expect the relative line numbers to update as you move between lines, but they are only updated when you add new lines.
The relative line numbers in the statuscolumn start updating if you turn relative line numbers on via set relativenumber.

Without `'relativenumber'` set, moving the cursor will not redraw any lines, and thus the status column doesn't update. I don't think that should change. The user should set `'relativenumber'` if they want it to update on cursor movement, perhaps that should be documented under `:h statuscolumn`.

> Even when relativenumber is set, the relative line numbers only update for the first visual line of a wrapped line.

This may be considered a bug.

> Setting relativenumber or number also appears to add numberwidth padding after the status column, but while unexpected this is pretty useful.

Indeed, this was documented recently: https://github.com/neovim/neovim/pull/26845.

**Comment by blankname** [comment]
> Without `'relativenumber'` set, moving the cursor will not redraw any lines, and thus the status column doesn't update. I don't think that should change. The user should set `'relativenumber'` if they want it to update on cursor movement, perhaps that should be documented under `:h statuscolumn`.

Does this mean that `statuscolumn` doesn't initiate redraws itself, something else has to trigger a redraw for the `statuscolumn` to be redisplayed?

**Comment by luukvbaal** [comment]
Yes, the status column is drawn as part of the buffer text in the window. Anything that causes a redraw for a buffer line, will also redraw the status column for that row. The only exception to that is cursor movement with `'relativenumber'` enabled, which will only redraw the columns.
