### ISSUE TITLE
`textDocument/definition` doesn't send `context` to `on_list` handler

### ISSUE THREAD

**Issue by ss-raicangu** [neovim/neovim#26936]
### Problem

Methods relying on the default `location_handler` don't send `context` object to custom `on_list` handler.

1. `textDocument/declaration`
2. `textDocument/definition`
3. `textDocument/typeDefinition`
4. `textDocument/implementation`

<https://github.com/neovim/neovim/blob/8df37423781493f58de060e1c9219cd1c3768130/runtime/lua/vim/lsp/handlers.lua#L425>
_Ref 1. Other default handlers pass the table element `context = ctx`, which is available in this handler as well._

### Steps to reproduce using "nvim -u minimal_init.lua"

**`minimal-init.lua`**

~~~lua
local pattern = 'lua'
local cmd = {'lua-language-server'}  -- which is in `$PATH`.
local root_markers = {'.git', '.luarc.json'}  -- which is a sufficient subset of `{ ".luarc.json", ".luarc.jsonc", ".luacheckrc", ".stylua.toml", "stylua.toml", "selene.toml", "selene.yml", ".git" }`.
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    print(vim.lsp.start({
      name = 'luals',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    }))
  end
})
~~~

**`test.lua`**

~~~lua
local function test()
  return "Hello world"
end
~~~

After ensuring cursor is pointing to `test()`.

~~~vim
:lua vim.lsp.buf.definition({ on_list = function(what) print(what.context) end })
~~~

### Expected behavior

Expected `context` object to be populated for methods using `location_handler`, similar to other LSP methods such as `textDocument/references`.

### Neovim version (nvim -v)

NVIM v0.9.4; Build type: Release; LuaJIT 2.1.1699524327

### Language server name/version

LuaLS/lua-language-server (v3.7.2) but assuming applies to all servers

### Operating system/version

macOS 14.2.1 (23C71) but assuming applies to all operating systems

### Contributing checklist

Thanks in advance for looking at report 🙂 .

1. Checked FAQ.
1. Searched for issues: `is:issue lsp context method`.
1. Not a usage question.
1. Tried minimal config.
1. Followed `git-blame` for `runtime/lua/vim/lsp/handlers.lua`. `context` never seems to have been passed in.
    1. [First blame for commit `3ded2ab`](https://github.com/neovim/neovim/blame/43cd91a4f4276da2b9cb231032ca63e47e7f32a2/runtime/lua/vim/lsp/handlers.lua#L359) (feat(lsp): allow passing custom list handler to LSP functions that return lists, 2022-06-26)
    1. [Latest blame for commit `adbe7f3`](https://github.com/neovim/neovim/blame/8df37423781493f58de060e1c9219cd1c3768130/runtime/lua/vim/lsp/handlers.lua#L425) (fix(lsp): call `on_list()` even for single location, 2023-11-01)

**Comment by mfussenegger** [comment]
See also the discussion in https://github.com/neovim/neovim/pull/26507#discussion_r1434951201 - going forward with multi client support there likely won't be a `context` property anymore on the `on_list` handler.

**Comment by ss-raicangu** [comment]
Oh, interesting. Thanks for linking that discussion 🙂 .

If it helps, my usecase is deciding whether to open the location list based on the LSP method.

~~~lua
-- Link: `:help lsp-on-list-handler`
local function on_list(what)
	vim.fn.setloclist(0, {}, ' ', what)
	-- Similar to `:lgrep` behaviour.
	vim.cmd.ll()
	-- Link: [`textDocument/definition` doesn't send `context` to `on_list` handler](https://github.com/neovim/neovim/issues/26936)
	if what.context and (
		    what.context.method == 'textDocument/references' or
		    what.context.method == 'textDocument/documentSymbol')
	then
		vim.cmd.lopen()
	end
end
~~~

But I easily see an alternative, by adding another parameter to `on_list`, so wouldn't be a concern if `context` was removed entirely.

~~~lua
-- @type method string
local function on_list(_, method)
    -- ...
end

local function on_attach()
    vim.keymap.set('n', 'gd', function()
        vim.lsp.buf.definition({ on_list = function(what)
            on_list(what, 'textDocument/definition')
        end })
end

**Comment by mfussenegger** [comment]
> If it helps, my usecase is deciding whether to open the location list based on the LSP method.

That's something we can actually keep. It's the `client_id` property that is becoming a problem.

**Comment by ss-raicangu** [comment]
Ah, nice (re: LSP method).

Yea, agreed (re: client_id). I have no good ideas either. To throw out one:

1. On context table, `client_id = (number | nil), client_ids = (table)`
   1. Breaking change for client_id
   2. nil indicates multi-client response
   3. Examples: `client_id = nil, client_ids = { 1, 2, 3 }`, `client_id = 1, client_ids = { 1 }`

**Comment by mfussenegger** [comment]
context with method and bufnr got added with https://github.com/neovim/neovim/pull/30877
