### ISSUE TITLE
Add on_delete for extmarks

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#26930]
### Problem

Currently, there is no easy way to detect when an extmark gets deleted.
This would be useful for two reasons: to sync an extmark_id to a data table with existing extmarks and so that UIs can detect when an extramark they watch gets deleted.

### Expected behavior

A field called on_delete gets added to extmarks which gets called when the extmark gets deleted.

**Comment by lewis6991** [comment]
Extmarks are owned by a specific plugin, and so far they are not designed to act as a generic API for other plugins to read from. They are sort of lower level then that.

I think if you need to know when an extmark is removed you really should be asking when a plugin is removing them. E.g. in Gitsigns a user autocmd is triggered when hunks change.

**Comment by altermo** [comment]
I could think of one (when undo_restore=false and invalidate=true), but that is such a rare case, and with the point you brought up, I came to the conclusion that this is not needed.

**Comment by lewis6991** [comment]
Tbf that was the one situation I hoped you wouldn't mention. However the intention of that feature was so extmarks could clean themselves rather than forcing plugins to track them.
