### ISSUE TITLE
vim.v.ctype seems to be set wrong

### ISSUE THREAD

**Issue by mrdomino** [neovim/neovim#26948]
### Problem

According to POSIX, if `LC_ALL` and `LC_CTYPE` are both unset and `LANG` is `en_US.UTF-8`, `LC_CTYPE` should also be `en_US.UTF-8`. But somehow `vim.v.ctype` is winding up as `C`.

Output from `:checkhealth` follows:

```
nvim: require("nvim.health").check()

Configuration ~
- ERROR Locale does not support UTF-8. Unicode characters may not display correctly.
  $LANG=en_US.UTF-8 $LC_ALL=nil $LC_CTYPE=nil
  - ADVICE:
    - If using tmux, try the -u option.
    - Ensure that your terminal/shell/tmux/etc inherits the environment, or set $LANG explicitly.
    - Configure your system locale.
```

### Steps to reproduce

```
nvim --clean
:checkhealth
```

### Expected behavior

No error output.

### Neovim version (nvim -v)

v0.9.5

### Vim (not Nvim) behaves the same?

no (no checkhealth)

### Operating system/version

Debian bookworm

### Terminal name/version

iTerm 2

### $TERM environment variable

xterm-256color

### Installation

nix

**Comment by mrdomino** [comment]
Weird, this also happens with `LC_CTYPE` set. Maybe it's something wrong with my system.

**Comment by mrdomino** [comment]
Double-checked and on this system `setlocale(LC_CTYPE, "en_US.UTF-8")` returns `"en_US.UTF-8"`. But if I run `:lan cty en_US.UTF-8`, I get `E197: Cannot set language to "en_US.UTF-8"`. So this looks like a neovim bug.

**Comment by wookayin** [comment]
Looks like this is a nixos-specific issue. Does setting `LOCALE_ARCHIVE` or `i18n.defaultLocale` help by any chance? https://nixos.wiki/wiki/Locales

See also #4829

**Comment by mrdomino** [comment]
Setting `LOCALE_ARCHIVE` works. I'm using nix on Debian right now since Debian's neovim package is outdated.

Not sure what the connection with that PR is - maybe wrong number?

**Comment by wookayin** [comment]
Closing as resolved. This would be an issue on the nixos side rather than on nevoid; a proper system configuration will be needed as suggested by checkhealth:

> Configure your system locale.
