### ISSUE TITLE
修复  bug json数据含有 // 或/ 特殊字符处理时 结果会多一个 \

### ISSUE THREAD

**Issue by CLX102030** [neovim/neovim#26958]
### Problem

修复  bug json数据含有 // 或/ 特殊字符处理时 结果会多一个 \

### Steps to reproduce

add json data url http://www.baidu.com/
<img width="238" alt="image" src="https://github.com/neovim/neovim/assets/90083278/3bca7c86-da30-4b39-b954-895a6cb323eb">
bug修复后 
<img width="257" alt="image" src="https://github.com/neovim/neovim/assets/90083278/4af32dc2-ab82-4595-adf9-8451e723f7c8">
邮箱 17538264963@163.com 

### Expected behavior

传入 url 结果为 http://www.baidu.com 正常输出 

bug定位 疑似是在特殊表字符处理时，多增加/
<img width="257" alt="image" src="https://github.com/neovim/neovim/assets/90083278/1a4b536b-9587-4c12-b3d6-89017007cf39">

### Neovim version (nvim -v)

0000

### Vim (not Nvim) behaves the same?

0000

### Operating system/version

0000

### Terminal name/version

3.1

### $TERM environment variable

000

### Installation

代码移植

**Comment by zeertzjq** [comment]
I think this should be reported to https://github.com/openresty/lua-cjson

**Comment by CLX102030** [comment]
这个仓库的内容也有，那这个仓库cjson的部分是不是也要进行修改呀
