### ISSUE TITLE
ConTeXt highlighting is flawed

### ISSUE THREAD

**Issue by gerion0** [neovim/neovim#26966]
### Problem

ConTeXt has highlighting in Neovim. However, when embedding Lua code it correctly switches to Lua hightlighting but does not come back to ConTeXt highlighting correctly.

This problem is fixed already kind of in Vim (and the example is not mine, although I encounter the problem).
See here:
- https://mailman.ntg.nl/archives/list/ntg-context@ntg.nl/thread/4ALVL6LDO5GU6E5X63JOY2MJQ4KOCRBQ/
- https://github.com/vim/vim/pull/13778 (merged)

### Steps to reproduce

Look at this file (example by Damien Thiriet)
```
\starttext

Hello!
\ctxlua{context("does the parser work?")}

-- this should not be highlighted as a comment

\stoptext
```

### Expected behavior

The highlight is correct (the fake Lua comment ist not hightlighted as comment)

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

no, vim newest

### Operating system/version

Gentoo Linux

### Terminal name/version

Kitty 0.31.0

### $TERM environment variable

xterm-256color

### Installation

system package manager

**Comment by clason** [comment]
The "fix" in Vim consisted in a full rewrite of the filetype plugins in Vim9script. We will not backport these changes, so the ConTeXt filetype plugins are essentially frozen. (They're also much too complex for bundled plugins and better belong in a dedicated filetype plugin.)

As we do not maintain any filetype plugins ourselves (in favor of treesitter support, which unfortunately doesn't have a context parser -- yet) I'm afraid this is therefore "wontfix" from us.

**Comment by adityam** [comment]
Would it be okay if a separate pull request is made against the current syntax file for context included in neovim. The key issue is adding `keepend` keyword in `syn region contextBeginEndLua` to fix the highlighting bug.

**Comment by clason** [comment]
If you want to make the effort to manually port the changes to legacy vimscript, then yes, you can do that.

Please find the commit in Vim making these runtime file changes and open a PR with the title
```
vim-patch:partial:<short commit hash>
```

and explain exactly which changes you ported. (I believe it's commit `7dd543246a4c` from August 2022.)

Alternatively, you could try to convert (all) these vim9script runtime files to Lua using https://github.com/tjdevries/vim9jit; that would also be acceptable.

@zeertzjq

**Comment by adityam** [comment]
For now, I was just planning of adding the `keepend` keyword. I'll test if it fixes the bug and then send a pull request.

**Comment by gerion0** [comment]
Thank you for your efforts! The Lua issue is the most annoying one, I did not encounter other obvious highlighting issues, yet. BTW, as mentioned [here](https://github.com/nvim-treesitter/nvim-treesitter/issues/2282#issuecomment-1483976242), there is actually a treesitter grammar but not supported by nvim-treesitter, yet.
