### ISSUE TITLE
Getting GPG issue 403 when apt-get update

### ISSUE THREAD

**Issue by useche** [neovim/neovim#2696]
When trying to install neovim, I get the following errors:

==============================
$ sudo add-apt-repository ppa:neovim-ppa/unstable                                                                                                                                                                                 [5/5]
[sudo] password for useche: 
 Daily builds of Neovim.

Homepage: http://neovim.io
Source/Issues: https://github.com/neovim/neovim
Documentation: http://neovim.io/doc
User Manual: http://neovim.io/doc/user
Neovim features: http://neovim.io/doc/user/nvim_intro.html
Packaging: https://launchpad.net/neovim-ppa
 More info: https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmp54qz6xj_/secring.gpg' created
gpg: keyring `/tmp/tmp54qz6xj_/pubring.gpg' created
gpg: requesting key 8231B6DD from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp54qz6xj_/trustdb.gpg: trustdb created
gpg: key 8231B6DD: public key "Launchpad PPA for Neovim PPA Team" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
$ sudo apt-get update
...
Err http://ppa.launchpad.net trusty/main amd64 Packages
  403  Forbidden [IP: ::ffff:172.16.255.22 3129]
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Err http://ppa.launchpad.net trusty/main i386 Packages
  403  Forbidden [IP: ::ffff:172.16.255.22 3129]
...
W: GPG error: http://archive.ubuntu.com trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
W: Failed to fetch http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu/dists/trusty/main/binary-amd64/Packages  403  Forbidden [IP: ::ffff:172.16.255.22 3129]

W: Failed to fetch http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu/dists/trusty/main/binary-i386/Packages  403  Forbidden [IP: ::ffff:172.16.255.22 3129]

E: Some index files failed to download. They have been ignored, or old ones used instead.
==============================

Any ideas?

**Comment by Pyrohh** [comment]
@fwalch do you manage the PPA?

**Comment by fwalch** [comment]
Yes. I just ran `sudo apt-get update` without any problems.

@useche Maybe it's an ipv6 problem?

**Comment by useche** [comment]
Yes. It could be. Unfortunately, my machine is in a ipv6/proxy environment. There is not much I can do.

**Comment by Pyrohh** [comment]
In that case I'll close this.
