### ISSUE TITLE
Is there any interest in a built-in plugin manager?

### ISSUE THREAD

**Issue by addisonamiri** [neovim/neovim#2697]
When the viml to lua translator comes to fruition I think it'd also be nice to have a built in plugin manager. While I think the variety in the community is good, it's a bit confusing for new users to choose a plugin manager and then figure out how it works. If there was a built in implementation I think it would simplify the whole process a ton.

The only downside I can see is more bloat in an install but I think the convenience of being able to sync a .nvimrc to get the same plugins on multiple computers outweighs that.

**Comment by stefanpenner** [comment]
having a good default here has the potential of laying a really healthy foundation for growth.

**Comment by Pyrohh** [comment]
I think it'd be a great idea as well, but there's already discussion in #247 so I'm not sure this issue is needed.

**Comment by addisonamiri** [comment]
Oops I guess I didn't search hard enough. Go ahead and close this or I will
when I get home.
