### ISSUE TITLE
sqlcomplete#drill_into_table pop-up when using arrows to navigate

### ISSUE THREAD

**Issue by nrydanov** [neovim/neovim#26977]
### Problem

I know that it's not preferred way of using Vim (I mean, arrows), but it's currently a way I use it.

So, when I use clean neovim setup (.config/nvim folder is empty, so no plugins or other extensions installed) and navigate through file using left or right arrows, I get red quickly disappearing`sqlcomplete#drill_into_table` pop-up, which also changes mode from normal to visual for a very little time.

### Steps to reproduce

1. Open NeoVim 0.9.5
2. Use left or right arrows to navigate for some time (it may not reproduce instantly)

### Expected behavior

No any pop-ups or mode changes

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

no, 9.0.2018

### Operating system/version

macOS 14.2.1

### Terminal name/version

iTerm 3.4.23

### $TERM environment variable

zsh: command not found: xterm-256color

### Installation

homebrew

**Comment by clason** [comment]
Not enough details. Are you editing SQL files? Please test with `nvim --clean` to exclude packages that may be installed locally.

**Comment by nrydanov** [comment]
I do not edit any SQL files. To be more accurate, I edit typst file (with .typ extension). I wouldn't think that it will be depend on file extension, but I can't reproduce the same error with extensions: .py and others.

It also seems like I can't reproduce error with `nvim --clean`, but I don't really understand where additional packages can else be installed except .config/nvim.

**Comment by Sam-programs** [comment]
What does `verbose imap <right>` return?

**Comment by clason** [comment]
> I wouldn't think that it will be depend on file extension, but I can't reproduce the same error with extensions: for example, .py or .t.

It certainly does: `.typ` files are recognized by Vim as SQL, depending on the file contents. Please pay attention to the filetype reported (e.g., in the statusline) when the error happens.

**Comment by nrydanov** [comment]
`verbose: imap <right>` returns `No mapping found`.

UPD. I captured error on `nvim --clean`, yes, it is the same error
<img width="730" alt="image" src="https://github.com/neovim/neovim/assets/56316351/5cfa7e0c-8d40-4c38-b9f8-970a4ac2fce0">
<img width="352" alt="image" src="https://github.com/neovim/neovim/assets/56316351/148fa6a3-0280-450a-80d2-74755ade517e">

**Comment by nrydanov** [comment]
I'm sorry, when I opened main.typ `verbose: imap <right>` returned
```
i  <Right>     *@<C-R>=sqlcomplete#DrillIntoTable()<CR>
        Last set from /opt/homebrew/Cellar/neovim/0.9.5/share/nvim/runtime/ftplugin/sql.vim line 528
```

**Comment by Sam-programs** [comment]
I supposed these 2 mappings are the cause:
https://github.com/neovim/neovim/blob/7c66923211c89d2b49a20ca532b9b4506e2ae27c/runtime/ftplugin/sql.vim#L527-L530
They aren't silent.

**Comment by Sam-programs** [comment]
Could you try adding this somewhere in your `init.lua` to disable the mappings?
```lua
vim.api.nvim_create_autocmd("Filetype", {
    pattern = "sql",
    callback = function() 
        vim.keymap.del('i','<left>',{buffer = true})
        vim.keymap.del('i','<right>',{buffer = true})
    end
})
```

**Comment by nrydanov** [comment]
I'll try, thanks

**Comment by nrydanov** [comment]
Yep, with those lines there're no pop-ups left.

**Comment by clason** [comment]
That's not the right solution. You need to make sure that your Typst files are recognized as filetype `typst`. If you know that you'll never work with SQL files with extension `.typ`, you can override the filetype detection via `:h vim.filetype.add()` in your config.

**Comment by Exagone313** [comment]
I stumbled upon this issue when editing a `CREATE TABLE` in a `.sql` file on Neovim 0.12.3. This GitHub issue came first on a search engine.

To disable those mappings you can add this to your config:

```lua
vim.g.omni_sql_no_default_maps = true
```
