### ISSUE TITLE
Opening Context Menu from the Context Menu causes recursive floating window

### ISSUE THREAD

**Issue by Kethku** [neovim/neovim#26973]
### Problem

If you right click in a buffer and then right click inside of the opened context menu when using a gui that supports multigrid, neovim will request that the window for the context menu be anchored to itself which is incorrect.

### Steps to reproduce

1. open nvim in a multigrid gui. I can reproduce this in default neovide
2. Move the mouse (otherwise the next step won't show a context menu at all, presumably related to the above issue).
3. Right click somewhere (not hold) to show the Paste/Select All/etc context menu.
4. Move the mouse to inside the context menu, then click and hold the right mouse button.

At this point neovim will request a recursive floating window anchor. In current neovide stable this crashes but a fix is in progress to ignore this invalid request. However neovim shouldn't send a request like that in the first place.

### Expected behavior

I think ideally the second right click should be ignored.

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 11

### Terminal name/version

neovide

### $TERM environment variable

n/a

### Installation

downloaded from releases

**Comment by zeertzjq** [comment]
Hmm, the second right click is supposed to reposition the menu, so if it's on the menu itself I think it should move it.
