### ISSUE TITLE
Recover.vim hangs Neovim when restoring swap file

### ISSUE THREAD

**Issue by sunaku** [neovim/neovim#2698]
Hello,

The https://github.com/chrisbra/Recover.vim plugin hangs Neovim when opening a crashed file that has a swap file.  This problem does not occur in regular Vim.  Also, without that plugin, Neovim displays the swap file restoration dialog just fine:

```
Swap file ".something.swp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (D)elete it, (Q)uit, (A)bort:
```

Thanks for your consideration.

**Comment by Pyrohh** [comment]
I can reproduce this. The issue seems to have been introduced (more like worsened) in https://github.com/chrisbra/Recover.vim/commit/8a6859f6739f4c2ba2aeb43bf4e78be033c1f4be.

Before that commit, nothing showed up initially, but after resizing the terminal a dialog appears (similar to the one you mentioned). I don't know VimScript, so I haven't looked into it further.

**Comment by fmoralesc** [comment]
See line 116: https://github.com/chrisbra/Recover.vim/commit/8a6859f6739f4c2ba2aeb43bf4e78be033c1f4be#diff-2a355b9c91f582a60349f9211d8c9fe2R116

**Comment by Pyrohh** [comment]
Thanks @fmoralesc. The following allows me to resize again using https://github.com/chrisbra/Recover.vim/commit/18986428fdf33abd33eed074413ee8707904ba4c.

```patch
diff --git a/autoload/recover.vim b/autoload/recover.vim
index 16f81b4..ce752f5 100755
--- a/autoload/recover.vim
+++ b/autoload/recover.vim
@@ -107,8 +107,9 @@ fu! recover#ConfirmSwapDiff() "{{{1
 	  let wincmd = printf('-c "redir > %s|1d|:q!" ', tfile)
 	  let wincmd = printf('-c "call feedkeys(\"o\n\e:q!\n\")"')
 	endif
-	let cmd = printf("%svim -u NONE -es -V %s %s",
+	let cmd = printf("%s%s -u NONE -es -V %s %s",
 	    \ (s:isWin() ? '' : 'TERM=vt100 LC_ALL=C '),
+	    \ v:progpath,
 	    \ (s:isWin() ? wincmd : ''),
 	    \ bufname)
 	let msg = system(cmd)
```

The output is very weird though.

```
chdir(/home/michael/src/neovim)
chdir(cmake)
chdir(/home/michael/src/neovim)
Reading viminfo file "/home/michael/.nviminfo" info oldfiles^[[?1049h^[[H^[[J^[[H^[[J^[[1;1H^[[1;1H^[[24;1Hchdir(/home/michael/src/neovim)^[[24;32H^[[1;1H^[[M^[[24;32H^[[24;32H^[[24;1Hchdir(cmake)^[[1;1H^[[M^[[24;13H^[[24;13H^[[24;1Hchdir(
/home/michael/src/neovim)^[[1;1H^[[M^[[24;32H^[[24;32H^[[24;1Hchdir(/home/michael/src/neovim)^[[1;1H^[[M^[[24;32H^[[24;32H^[[24;1Hchdir(cmake)^[[1;1H^[[M^[[24;13H^[[24;13H^[[24;1Hchdir(/home/michael/src/neovim)^[[1;1H^[[M^[[24;32H^[[24;32H
^[[24;1H"cmake/RunLint.cmake" ^[[24;23H^[[24;1H"cmake/RunLint.cmake" 21L, 702C^[[1;1H^[[M^[[24;32H^[[24;32H^[[24;1HReading viminfo file "/home/michael/.nviminfo" marks ^[[1;1H^[[M^[[24;54H^[[24;54H^[[24;1HEntering Ex mode.  Type "visual" t
o go to Normal mode.^[[1;1H^[[M^[[24;55H^[[24;55H^[[24;1H:^[[24;2H^[[24;2H^[[24;1H^[[1;1H^[[M^[[24;1H^[[24;1HWriting viminfo file "/home/michael/.nviminfo"^[[24;47H^[[24;1H^[[2 q^[[?1002l^[[?1006l^[[0;10m^[[?1049l
Please choose:
D[i]ff, (O)pen Read-Only, (E)dit anyway, (R)ecover, (Q)uit, (A)bort, (D)elete:
```

@sunaku I think that an issue should be opened at the Recover.vim repo, as this doesn't seem to pertain to us.

**Comment by sunaku** [comment]
:+1: Thanks @Pyrohh. Would you mind submitting your patch as a pull request? :sweat_smile: (I don't want to take credit for your work. :blush:)

**Comment by Pyrohh** [comment]
> Would you mind submitting your patch as a pull request?

That's fine, I just submitted one.

**Comment by sunaku** [comment]
Perfect! :+1: Case closed. :hammer:
