### ISSUE TITLE
typo in runtime/tutor/en/vim-01-beginner.tutor

### ISSUE THREAD

**Issue by vilo1839** [neovim/neovim#26985]
### Problem

in # CONCLUSION of vim-01-beginner.tutor it says "Learning Vim in 2013:" when the link is for http://benmccormick.org/learning-vim-in-2014
so I think it should say "2014" instead

### Steps to reproduce

Tutor

### Expected behavior

typo

### Neovim version (nvim -v)

0.7.2 release compiled by team+vim@tracker.debian.org though I checked the source code just now

### Vim (not Nvim) behaves the same?

no, vim 9.1

### Operating system/version

Debian GNU/Linux 12 (bookworm) on Linux 6.1.0-17-amd64

### Terminal name/version

st 0.9

### $TERM environment variable

256color

### Installation

Debian

**Comment by clason** [comment]
For simple typos, it's easier to just make a PR!
