### ISSUE TITLE
Return true and false instead of 1 and 0 for Vim builtin functions (that return booleans) called from Lua

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#26983]
### Problem

This feature request is a breaking change. If it's more suitable for discussion elsewhere (e.g., [Discussions](https://github.com/neovim/neovim/discussions), [Chat](https://app.element.io/#/room/#neovim:matrix.org), [Reddit](https://www.reddit.com/r/neovim)), and this type of change would be considered, I can move it there.

Currently, the following command will print `0.20` even though `has('nvim-0.20')` is false.

```lua
:lua if vim.fn.has('nvim-0.20') then print('0.20') end
```

This is because the Vim builtin functions return 1 for true and 0 for false, both of which are considered true in the Lua context.

### Expected behavior

This feature request is to change the functionality so that builtin functions (that return boolean values) called through `vim.fn` would return `true` and `false` instead of `1` and `0`. This would break existing code that does something like the following to work around the issue:

```lua
:lua if vim.fn.has('nvim-0.20') == 1 then print('0.20') end
```

One way to make this change could be to update the Vim builtin functions themselves to return `v:true` and `v:false` instead of `1` and `0`. That way, when translated to Lua, the returned values would become `true` and `false`. This would presumably not break Vimscript code since `v:true ==# 1` evaluates as true (more specifically, `1`). But the running example would work as-is:

```lua
:lua if vim.fn.has('nvim-0.20') then print('0.20') end
```

I'll close the issue if this wouldn't be considered (e.g., not worth the cost of a breaking change or there is a technical limitation).

**Comment by clason** [comment]
This would be massively breaking, for not a very good reason. Lua's `0` is truthy, and papering over this (admittedly footgun of a) language feature would be extremely confusing and lead to other issues.

Instead, use `vim.version`, which is a native Lua API.

**Comment by dstein64** [comment]
> "And we definitely don't want to touch legacy functions and risk incompatibility with Vim (and the whole Vim ecosystem)."

Thanks for the quick response. I'll close this ticket. 

> "Instead, use vim.version, which is a native Lua API."

`vim.fn.has('nvim-0.20')` was intended as a general example (not the main motivation).

**Comment by dstein64** [comment]
Re-closing as "not planned".
