### ISSUE TITLE
`nvim_win_call()` strange behavior

### ISSUE THREAD

**Issue by Bekaboo** [neovim/neovim#26982]
### Problem

Don't know if it is a design choice or if I missed something important in the doc, but `nvim_win_call()` acts strange to me -- it changes the return value of callbacks that return floating-pointer numbers.

For example:

```vim
:lua =vim.api.nvim_win_call(1000, function() return 1.2 end)
```

shows

```
{
  [false] = 1.2,
  [true] = 3
}
```

instead of 1.2

### Steps to reproduce

1. `nvim --clean`
2. `lua =vim.api.nvim_win_call(1000, function() return 1.2 end)`
3. The output is a table not a number

### Expected behavior

The output should be a number.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2022+ga064ed6229

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Linux 6.6.9-arch1-1

### Terminal name/version

alacritty 0.12.3 (5efb0690) + tmux 3.3a

### $TERM environment variable

xterm-256color

### Installation

AUR

**Comment by clason** [comment]
This is just how return values that are not native to Lua (in this case floats) are encoded across the API bridge.

**Comment by Bekaboo** [comment]
Appreciate your quick response. Is there a function to convert that special table back to lua floating point values? I checked the doc and could not find one.

**Comment by clason** [comment]
There _is_ no "Lua floating point value", that's the whole point. Use `vim.val_idx` to extract the value.

**Comment by Bekaboo** [comment]
I see, thanks for your help!
