### ISSUE TITLE
Automatic de-indenting of closing code statements is dependent on the keypress order of the closing statement.

### ISSUE THREAD

**Issue by iliveinatrashcan** [neovim/neovim#26999]
### Problem

[Text within square braces] is meant to represent typing a non printing character such as [Return], [Space] or [Left Cursor]

When typing a piece of text within neovim, some things are autoindented and autodeintented depending on the statement made, for example in a python file (`:set filetype` results in `  filetype=python`) when typing `if condition:`[Return]`print()`[Return]`else:` the word "else:" deindents automatically (as soon as the word "else" is complete). If you however mess up the order in which you type the word "else", for example mistyping it as "ese:" then going 3 spaces backwards with the arrow key and add the missing letter, it does not automatically deindent.

Similarly with HTML files (`:set filetype` results in `  filetype=html`), when typing `<html>`[Return]`meow`[Return]`</html>` the closing HTML tag deindents automatically. When you however type `<html>`[Return]`meow`[Return]`<>`[Left Cursor]`/html` the closing HTML tag does not automatically deindent.

Simlarly with sh files (`:set filetype` results in `  filetype=sh`), when typing `for i in list; do`[Return]`echo "1"`[Return]`done`, the word "done" deindents correctly, however when typing `for i in list; do`[Return]`echo "1"`[Return]`de`[Left Cursor]`on` the word "done" does not deindent automatically, even more curiously: when typing `for i in list; do`[Return]`echo "1"`[Return]`dne`[Left Cursor][Left Cursor]`o`, the word "done" *does* automatically deindent.

PS: if a correctly typed closing word typed in the wrong order has its last character deleted and then typed in again, the closing word will be correctly deindented. i.e.: when typing `<html>`[Return]`meow`[Return]`<>`[Left Cursor]`/html`[Right Cursor][Backspace]`>` the closing `</html>` tag will be deindented.

### Steps to reproduce

[Text within square braces] is meant to represent typing a non printing character such as [Return], [Space] or [Left Cursor]

In [Kitty Terminal 0.31.0](https://github.com/kovidgoyal/kitty), [XTerm(389)](https://invisible-mirror.net/archives/xterm) or [ddterm 49 revision 73297878ac855f764e27fc2f31886c018419d34d](https://github.com/guilhem/gnome-shell-extension-ddterm) type:  
## For HTML
`nvim test123.html`[Return]

within nvim in INSERT mode type:  
`<html>`[Return]`<>`[Left Cursor]`/html`

The Resulting text (HTML) will look like so:
```
<html>
    </html>
```

## For Python
`nvim test.py`[Return]

within nvim in INSERT mode type:  
`if true:`[Return]`print("")`[Return]`ese:`[Left Cursor][Left Cursor][Left Cursor]`l`

The Resulting text (Python) will look like so:
```
if true:
    print("")
    else:
```

## For sh
`nvim test.sh`[Return]

within nvim in INSERT mode type:
`for i in list; do`[Return]`echo "1"`[Return]`de`[Left Cursor]`on`

The Resulting text (sh) will look like so:
```
for i in list; do
    echo "1"
    done
```

### Expected behavior

The resulting text (For HTML) should look like so:
```
<html>
</html>
```

The resulting text (For Python) should look like so:
```
if true:
    print("")
else:
```

The resulting text (For sh) should look like so:
```
for i in list; do
    echo "1"
done
```

### Neovim version (nvim -v)

NVIM v0.9.5 / Build type: Release / LuaJIT 2.1.1702233742

### Vim (not Nvim) behaves the same?

yes, VIM 9.1

### Operating system/version

6.6.8-arch1-1 GNU/Linux

### Terminal name/version

kitty 0.31.0 created by Kovid Goyal

### $TERM environment variable

xterm-kitty

### Installation

pacman -Sy neovim

**Comment by zeertzjq** [comment]
This is the intended behavior.

**Comment by iliveinatrashcan** [comment]
why does it work this way? (genuine question)

**Comment by zeertzjq** [comment]
See `:h 'indentkeys'` and `:h 'cinkeys'`
