### ISSUE TITLE
LSP: add `buf`, `client_id` parameters to vim.lsp.codelens.refresh()

### ISSUE THREAD

**Issue by abcdefg233** [neovim/neovim#26995]
### Problem

Refresh only work on current buffer, but I want to refesh code lens for all buffers once.
![image](https://github.com/neovim/neovim/assets/32760059/2bb42a54-a23c-43ea-a352-c1b009c95867)
![image](https://github.com/neovim/neovim/assets/32760059/ceb29091-8eee-4a77-86db-1d78514bfb7a)

### Expected behavior

```
refresh({client_id}, {bufnr})                         *vim.lsp.codelens.refresh()*
    Refresh the lenses

    Parameters: ~
      • {client_id}  (`integer?`) filter by client_id. All clients if nil
      • {bufnr}      (`integer?`) filter by buffer. All buffers if nil
```

**Comment by justinmk** [comment]
Do we actually need "refresh"? Does it do anything different than `clear()` followed by re-initializing codelenses?

**Comment by MariaSolOs** [comment]
I think this is a reasonable request, given that the protocol documents [`workspace/codeLens/refresh`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeLens_refresh) as "refreshing the code lenses currently shown in editors" (which IMO would correspond to all open buffers).
