### ISSUE TITLE
neovim crashes on opening multiple sessions

### ISSUE THREAD

**Issue by Justaus3r** [neovim/neovim#26990]
### Problem

Whenever I run multiple sessions of neovim, only the latest session, remains, all the other sessions crash without any error. I am using Powershell and Windows Terminal.

### Steps to reproduce

1: Open multiple neovim sessions.
2: Only the latest session remains, all others crash.
**log:**
```
ERR 2024-01-11T16:17:34.206 nvim.13772.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-11T16:19:20.952 nvim.15156.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-12T00:08:32.682 nvim.14856.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-12T00:09:10.724 nvim.6488.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-12T00:15:55.151 nvim.8936.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-12T00:19:36.821 nvim.9956.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-12T00:20:27.577 nvim.13468.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-12T00:21:09.292 nvim.12472.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-12T00:26:01.191 nvim.15140.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-12T01:05:09.485 nvim.6524.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-12T01:22:15.843 nvim.4544.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-12T01:22:18.027 nvim.7028.0 chan_close_with_error:653: RPC: failed to decode msgpack
ERR 2024-01-12T01:33:22.905 nvim.13760.0 chan_close_with_error:653: RPC: failed to decode msgpack

```

ScreenRecording

https://github.com/neovim/neovim/assets/72691864/11ccf5b8-9426-4d5d-92be-89301d59fef7

### Expected behavior

All neovim sessions should exist concurrently.

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

Don't have vim

### Operating system/version

Windows 10 Pro 22H2 19045.2965

### Terminal name/version

Windows Terminal 1.18

### $TERM environment variable

None

### Installation

winget

**Comment by justinmk** [comment]
does it happen with `nvim --clean` ? If not, could be a plugin, impossible to tell with your steps.

**Comment by Justaus3r** [comment]
After running with ``--clean``, No it doesn't crash on multiple sessions, ig it's some plugin bug. Should have tested for that. Thank you for your response!

**Comment by Justaus3r** [comment]
I don't think it's the problem with nvim, rather with the some plugin. I can't reproduce the crash other than with my plugins

**Comment by wookayin** [comment]
If you could try reproducing the bug with the following template, that'd be appreciated. Also try getting stacktrace if possible

https://github.com/neovim/neovim/blob/master/contrib/minimal.lua
https://neovim.io/doc/user/dev_tools.html

**Comment by justinmk** [comment]
It's not a "crash" if Nvim is exiting intentionally (because of invalid msgpack-rpc). Did Windows say that Nvim crashed? If so , try to get a stacktrace.

**Comment by Justaus3r** [comment]
I apologize for the late response.
I have tried debugging nvim using [official debug guide](https://neovim.io/doc/user/debug.html) but I was not able to produce any stacktrace, meaning this was  probably not a neovim bug but some plugin weirdness(probably a bug, tho this didn't use to happen on previous versions).

Thank you for the response. This issue can be closed now.
