### ISSUE TITLE
Enhance :cquit to take an error code argument

### ISSUE THREAD

**Issue by danielshahaf** [neovim/neovim#2699]
Currently, the :cquit command quits, even if there are modified buffers, regardless of whether a '!' was passed.

Suggestion: make :cquit refuse to quit if there are modified buffers and a '!' was not passed.  Keep ':cquit!' as-is (exiting with code 1 even if there are modified buffers).

**Comment by Pyrohh** [comment]
I think this is intrinsically reasonable, but not sure it should be done given it might break certain scripts.

**Comment by splinterofchaos** [comment]
```
:cq[uit][!]		Quit Vim with an error code, so that the compiler
			will not compile the same file again.
			WARNING: All changes in files are lost!  Also when the
			[!] is not used.  It works like ":qall!" |:qall|,
			except that Vim returns a non-zero exit code.
```
Looks like it works as documented, though I don't understand what it means by "so that the compiler will not compile the same file again." Why does it work the way it does? What are the intended use-cases? Would not exiting with modified buffers be consistent with the existing usage?

**Comment by fmoralesc** [comment]
> Why does it work the way it does? What are the intended use-cases? 

I found this in SO about it: http://unix.stackexchange.com/a/43030: 

> To edit most recently used command in vim and invoke an edited version after editor saves and exits, use fc shell built-in. Without any arguments it will do the following:

> 1)  Creates a temporary file in /tmp and populates it with the most recently typed command
> 2)  After editor exits normally (with exit code 0) it executes command found in that temporary file and removes this file. Edited version is saved in history as a usual command (at least in zsh). It executes nothing if editor exits with code other then zero (in vim this can be achieved by either killing it or using :cquit).

The way it's redacted might be improved. Perhaps:

~~~
 :cq[uit][!]     Quit Vim with an error code (When vim is called from another
                 program, the caller might behave in a special way if the error 
                 code is not 0; e.g. `git commit`, `fc` in bash, some compilers.)
                 WARNING: All changes in files are lost!  Also when the
                 [!] is not used.  It works like ":qall!" |:qall|,
                 except that Vim returns a non-zero exit code.
~~~~

**Comment by danielshahaf** [comment]
Historically, the reason Vim treats :cquit and :cquit! as identical is that the original implementation and documentation both ignored the forceit flag, and then Bram decided to document that behaviour as a feature rather than introduce an incompatibility by making the change suggested here.

Exiting usages that break would all be fixed by changing ":cquit" to ":cquit!", and the fix would work for all versions of Vim and Neovim.  (It'd still be an incompatible change, but affected parties would have an easy and portable fix.)

**Comment by danielshahaf** [comment]
> Looks like it works as documented, though I don't understand what it means by "so that the compiler will not compile the same file again."

The manx compiler can invoke Vim to fix syntax errors, and recompiles the file if the exit code is zero. I guess without using :cquit, the compiler would infinite loop invoking vim each time it exits zero. (I reverse engineered this explanation from :help compiler-manx.)  In short, this sentence is an artifact of one use-case of :cquit.

**Comment by Grimy** [comment]
I vote against changing the behavior of `:cquit`.

* It would be an incompatible change
* The benefits are unclear or non-existent
* When returning an error code makes sense (`git commit`, `fc`…), saving the file before doing so is pointless
* Since the 99% use case of `:cquit` is to discard changes and abort, requiring a `!` to obtain this behavior will hurt usability

On the other hand, I approve fixing the documentation bug.

**Comment by ZyX-I** [comment]
I also vote against. I use `:cquit` either for “discard and abort” or as an equivalent to “qall!”: `:`, `c`, `q`, `<CR>` uses left-right-left-right hand sequence when typing in dvorak layout which is optimal, `:`, `q`, `a`, `<CR>` is left-left-left-right and switching fingers is not so fast compared to switching hands, not to mention the cases when I need `!` after `qa` which is +1 character on the right hand (*programming* dvorak variant) typed using the same finger used for `<CR>`.

**Comment by justinmk** [comment]
@danielshahaf Is there some use-case where a user (rather) than a script would use `:cquit` that could  cause data loss? If `:cquit` is only used by scripts there's not much reason to change it at this point.

**Comment by justinmk** [comment]
P.S. @ZyX-I why not use `ZQ` :)

**Comment by fdinoff** [comment]
@justinmk ZQ doesn't set the return value code to 1. 

One use case a user could use this is during a `git commit --amend`. If someone wants to abort the amend of the commit they can use `:cq` to quit vim. Since the editor exited with a non zero exit code the commit is aborted.

**Comment by ZyX-I** [comment]
@justinmk `qall!`, not `q!`. There is a big difference when more then one window is open and it is *very* common when I use second meaning.

**Comment by ZyX-I** [comment]
@fdinoff In the second case described by me I do not care about exit code. In the first case `cq` is the only “native” variant (there are more: e.g. you can kill editor).

**Comment by danielshahaf** [comment]
> @danielshahaf Is there some use-case where a user (rather than a script) would use :cquit that could cause data loss? If :cquit is only used by scripts there's not much reason to change it at this point (scripts can check modified buffers using other mechanisms before calling :cquit).

I use `:cq` interactively (in normal sessions launched in an interactive shell, no make/git involved) instead of `:qa!` because I find the former easier to type.  I once used `:cq` when the buffer was modified and I lost the changes I was working on.  So, yes, bangless `:cq`'s semantics did cause me to lose data once.

The question is just whether the risk of data loss outweighs the compatibility and convenience factors.

**Comment by danielshahaf** [comment]
Incidentally, I wonder if there is an effective way to make `:cq<CR>` check for modified buffers via user configuration?  Would a `:cnoremap <expr> <CR>` be the way to go (mapping it to a function that checks if there are modified buffers and if so returns "<BS><BS>echoerr")?

**Comment by Grimy** [comment]
```
function! s:cquit() abort
	bufdo if &modified | echoerr 'Cannot cquit, modified' | return | endif
	cquit
endfunction

cnoremap <CR> <C-]><CR>
cnoreabbrev cq    call <SID>cquit()
cnoreabbrev cqu   call <SID>cquit()
cnoreabbrev cqui  call <SID>cquit()
cnoreabbrev cquit call <SID>cquit()
```

**Comment by danielshahaf** [comment]
@Grimy thanks!

**Comment by splinterofchaos** [comment]
I think we've established that `:cquit` should not check for modified buffers, but it does seem unfortunate that we can't currently quit with an error code safely. How about allowing `:quit` to take a numeric argument to use as the exit code? This would be for vanilla vim as well.

**Comment by danielshahaf** [comment]
I don't think the specific error code is important; usually anything non-zero is good enough.  Perhaps all that's needed is a plugin that defines a `:Cquit` command that does check for modified buffers (as in [@Grimy's comment](https://github.com/neovim/neovim/issues/2699#issuecomment-111084789)).

**Comment by justinmk** [comment]
So the conclusion here is:

- update doc: https://github.com/neovim/neovim/issues/2699#issuecomment-103553303
- enhance `:cq` to take an argument: https://github.com/neovim/neovim/issues/2699#issuecomment-111160589
