### ISSUE TITLE
tests: improve test conventions (SUT, helpers.lua)

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#27004]
# Problem

Writing test code requires some "tribal knowledge" that requires the test author to understand which "helper" functions are dispatched to the `nvim` _test session_ (the "[SUT](https://en.wikipedia.org/wiki/System_under_test)") and which functions are handled in the context of the _test runner_.

Contributors must constantly be aware of the difference. Reading and writing tests can be confusing because of this, especially to non-experienced contributors.

# Expected behavior

Make the distinction clear by either extracting SUT functions to `test/sut.lua` or grouping them in a ~~sut~~ `nvim` container.

- [x] Rename `helpers.lua` to `testutil.lua` and change the import convention to (https://github.com/neovim/neovim/pull/28145):
   ```
   local t = require('testutil')
   ...
   t.foo()
   t.bar()
   ```
    - Thus there is no need anymore to do this:
      ```
      local helpers = require('testutil')
      local foo = helpers.foo
      local bar = helpers.bar
      ```
    - Test code can simply use `t.xx()` everywhere to call non-SUT test util functions.
- [ ] SUT functions live on `nvim`. When using SUT functions in test code, the usage looks like:
   ```lua
   nvim.api.nvim_get_commands()  -- instead of helpers.api.nvim_get_commands
   nvim.fn.foo()  -- instead of helpers.fn.foo()
   ```
    - See "Implementation" below.

# Implementation

Almost everything in `test/functional/testutil.lua` involves a "session". So in practice this would mean:

1. Lift any "pure" functionality (functions that don't require the nvim "test session") from `test/functional/testutil.lua` into `test/testutil.lua`.
    - `test/functional/testutil.lua` calls the `nvim` "test session" via RPC.
1. `test/testutil.lua` is no longer "merged" into `test/functional/testutil.lua`.
    - I.e. delete this line: https://github.com/neovim/neovim/blob/fd085d90820149caecf213b299f19e46305043ee/test/functional/testutil.lua#L19
1. Rename `test/functional/testutil.lua` to (e.g.) `…/nvimsession.lua`
1. All test imports now look like:
   ```lua
   -- Test runner functions/utils.
   local t = require('test.testutil')()
   -- Nvim RPC session.
   local nvim = require('test.functional.nvimsession')()
   ```
    - What should the test session be named?
        - ~~nvim? session? sut?~~ We decided on `n`.

# Future

Some questions to consider for the future (out of scope for this issue):

- Should `nvim` be a mirror of the nvim "test session" Lua stdlib? I.e. all `nvim.xx()` calls just dispatch to the Nvim "test session" `vim.xx()` ?
- Currently, we have a global "session": https://github.com/neovim/neovim/blob/f190f758ac58d9cc955368e047b070e0a2261033/test/functional/testutil.lua#L107-L113
    - This makes it less obvious what's going on in the tests.
    - It is weird that "screen" is used as an object in test code while "session" is not. Especially since the "screen" object is strictly tied to a session anyway. You cannot have multiple screens per session.
    - Solution: we could treat the Nvim session same as "screen", so tests would look like:
      ```
      local nvim = require('…/nvimsession.lua')
      local n = nvim.clear()
      n:command(':new foo')
      t.eq(2, n:eval('1+1'))
      ```

# Related

- https://github.com/neovim/neovim/pull/26994
- https://github.com/neovim/neovim/pull/27024

**Comment by dsaenztagarro** [comment]
I'm picking this as my first Neovim contribution.. pretty excited! 

I'm starting with the second point regarding the renaming, that seems to me the most straight forward part, so I become familiar with the test suite.

**Comment by dsaenztagarro** [comment]
**Quick update<sup>tm</sup>:** as a first step, before applying any change, I'm trying to run the specs suite without any errors, but after checking the [test/README.md](https://github.com/neovim/neovim/blob/master/test/README.md) and the [BUILD.md](https://github.com/neovim/neovim/blob/master/BUILD.md#build-prerequisites) guidelines, I'm still getting this trace error when running a simple unit spec:

<details><summary>See unittest error trace</summary>

```bash
❯ BUSTED_ARGS='--no-keep-going' TEST_FILE='test/unit/buffer_spec.lua' make unittest

mkdir -p build
touch build/.ran-deps-cmake
ninja -C .deps
ninja: Entering directory `.deps'
ninja: no work to do.
cmake --build build --target unittest
[0/2] Re-checking globbed directories...
[2/3] cd /Users/dsaenz/Code/neovim/build/test && /opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -D TEST_TYPE=unit -D ...dsaenz/Code/neovim/test -D WORKING_DIR=/Users/dsaenz/Code/neovim -P /Users/dsaenz/Code/neovim/cmake/RunTests.cmake
-------- Global test environment setup.
-------- Running tests from test/unit/buffer_spec.lua
RUN       buffer functions buf_valid should view NULL as an invalid buffer: 12.00 ms ERR
test/unit/helpers.lua:754: test/unit/helpers.lua:738: (string) '
test/unit/helpers.lua:268: '<identifier>' expected near ':' at line 671'
exit code: 256

stack traceback:
        test/unit/helpers.lua:754: in function 'itp_parent'
        test/unit/helpers.lua:792: in function <test/unit/helpers.lua:782>

-------- 1 test from test/unit/buffer_spec.lua (166.00 ms total)

-------- Global test environment teardown.
======== 1 test from 1 test file ran. (166.00 ms total)
PASSED   0 tests.
ERROR    1 error, listed below:
ERROR    test/unit/helpers.lua @ 782: buffer functions buf_valid should view NULL as an invalid buffer
test/unit/helpers.lua:754: test/unit/helpers.lua:738: (string) '
test/unit/helpers.lua:268: '<identifier>' expected near ':' at line 671'
exit code: 256

stack traceback:
        test/unit/helpers.lua:754: in function 'itp_parent'
        test/unit/helpers.lua:792: in function <test/unit/helpers.lua:782>


 1 ERROR
------------------------------------------------------------------------------
$NVIM_LOG_FILE: /Users/dsaenz/Code/neovim/build/.nvimlog
(empty)
------------------------------------------------------------------------------
-- Tests exited non-zero: 1
-- Output to stderr:
E5113: Error while calling lua chunk:

CMake Error at /Users/dsaenz/Code/neovim/cmake/RunTests.cmake:102 (message):
  unit tests failed with error: 1


FAILED: test/CMakeFiles/unittest /Users/dsaenz/Code/neovim/build/test/CMakeFiles/unittest
cd /Users/dsaenz/Code/neovim/build/test && /opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -D TEST_TYPE=unit -D BUILD_DIR=/Users/dsaenz/Code/neovim/build -D CIRRUS_CI= -D CI_BUILD=OFF -D DEPS_INSTALL_DIR=/Users/dsaenz/Code/neovim/build/usr -D NVIM_PRG=/Users/dsaenz/Code/neovim/build/bin/nvim -D TEST_DIR=/Users/dsaenz/Code/neovim/test -D WORKING_DIR=/Users/dsaenz/Code/neovim -P /Users/dsaenz/Code/neovim/cmake/RunTests.cmake
ninja: build stopped: subcommand failed.
make: *** [unittest] Error 1
```
</details>

Any clue from the very experts here would be well appreciated

**Comment by clason** [comment]
you're on an M1 mac, aren't you?  unittests don't work on ARM.

**Comment by dsaenztagarro** [comment]
Quick investigation on the backlog, my issue it seems related with #26145, since I'm using a Macbook with a M1 Pro processor.

I will try to continue from my backup laptop with x86 processor, and let's see..

**Comment by dsaenztagarro** [comment]
@clason ups! I just read your comment, thanks in any case 🤗 . Keep you posted with results on my backup laptop.

**Comment by clason** [comment]
Maybe start with functionaltests instead; unittests are an advanced topic.

**Comment by dsaenztagarro** [comment]
I was finally able to run both unit and acceptance specs so starting now with the proper work.

@clason sorry for the noise, I will keep in mind your suggestions for the future.

**Comment by dundargoc** [comment]
> `sut.api.nvim_get_commands()  -- instead of helpers.api.nvim_get_commands`
`sut.fn.foo()  -- instead of helpers.fn.foo()`

@justinmk  umm, why? It just looks like a random name-change to me.

**Comment by justinmk** [comment]
> > `sut.api.nvim_get_commands()  -- instead of helpers.api.nvim_get_commands`
> > `sut.fn.foo()  -- instead of helpers.fn.foo()`
> 
> @justinmk umm, why? It just looks like a random name-change to me.

Those are just examples. The general idea is to map one-to-one with Nvim stdlib, not have randomly different interfaces in the test util.

**Comment by dundargoc** [comment]
derp, you just mean differentiate between nvim/stdlib code and test code in the tests? OK, that makes sense. `sut` is super sus though, you need more text than you save to explain what it means. Why not `vim` instead? That way it'll be equivalent and IMO intuitive:

```
vim.api.nvim_get_commands()  -- instead of helpers.api.nvim_get_commands
vim.fn.foo()  -- instead of helpers.fn.foo()
```

If there's a naming conflict just call it `nvim` then.

**Comment by justinmk** [comment]
> If there's a naming conflict just call it `nvim` then.

Ok, updated the description.
