### ISSUE TITLE
CursorMoved triggered unexpectively after opening an unfocusable floating window

### ISSUE THREAD

**Issue by Bekaboo** [neovim/neovim#27002]
### Problem

CursorMoved event triggered unexpectedly after opening an unfocusable floating window.

### Steps to reproduce

1. Create the following `minimal.lua` file:

    ```lua
	local win_config = {
		width = 5,
		height = 5,
		row = 1,
		col = 1,
		relative = "editor",
		style = "minimal",
		focusable = false,
		noautocmd = true,
		zindex = 1,
	}

	vim.api.nvim_open_win(vim.api.nvim_create_buf(false, true), true, win_config)

	vim.api.nvim_create_autocmd("CursorMoved", {
		callback = function()
			print("info: " .. vim.inspect(info))
		end,
	})
    ```

2. `nvim --clean -u minimal.lua`
3. Observe the the autocmd info is printed while it shoudn't. We are only opening an unfocustable window, not jumping into it.

### Expected behavior

CursorMoved event should not trigger.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2074+g786089013d

### Vim (not Nvim) behaves the same?

no, vim does not have `nvim_open_win`

### Operating system/version

Linux 6.6.9-arch1-1

### Terminal name/version

alacritty 0.12.3 (5efb0690) + tmux 3.3a

### $TERM environment variable

xterm-256color

### Installation

AUR

**Comment by zeertzjq** [comment]
But you are jumping into it by passing `true` as the second arguments of `nvim_open_win`, which you can see by source the script after Nvim has started.

**Comment by Bekaboo** [comment]
Oops I didn't notice that, thanks!
