### ISSUE TITLE
Performance Sharply Degrades on editing on or close to long wrapped lines. 

### ISSUE THREAD

**Issue by Feel-ix-343** [neovim/neovim#27032]
### Problem

cursor movement and text editing become especially high in latency when editing near (within 2 lines) or on wrapped lines. 

### Steps to reproduce

Create an especialy long wrapped line, try editing near the end of it, and notice the slowness.

### Expected behavior

The editor should maintain low latency!

### Neovim version (nvim -v)

v0.10.0-dev-2060+g63a17322dd

### Vim (not Nvim) behaves the same?

Vim is significantly fastesr

### Operating system/version

Arch linux 6.6.10 zen

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

AUR

**Comment by zeertzjq** [comment]
Please follow the instruction for "Steps to reproduce"

> - Use the provided [minimal reproduction template](https://github.com/neovim/neovim/blob/master/contrib/minimal.lua) to create a minimal configuration. After you fill it out with necessary information, run with `nvim --clean -u minimal.lua`.
> - Please do **not** include a package manager in the reproduction steps.

**Comment by Feel-ix-343** [comment]
Sorry about this. I figured out that the issue is related to the undofile option. Disabiling that fixed this
