### ISSUE TITLE
Exiting floating prompt buffer window over terminal buffer unexpectedly enters terminal mode

### ISSUE THREAD

**Issue by jamestrew** [neovim/neovim#27031]
### Problem

Exiting a floating prompt buffer window **while in insert mode** over terminal buffer unexpectedly returns to the terminal buffer terminal mode despite originally being in normal mode.
The same does not happen when using a floating prompt buffer window over a regular (`buftype=''`) buffer. Instead, exiting a floating prompt buffer window over a regular buffer while in insert mode will return to the original buffer/window in normal mode.

related downstream issue: https://github.com/nvim-telescope/telescope.nvim/issues/2785

### Steps to reproduce

1. Create `repro.lua` with the following
```lua
local function win_fun()
  local bufnr = vim.api.nvim_create_buf(false, true)

  local win_opts = {
    relative = "editor",
    width = 10,
    height = 10,
    row = 10,
    col = 10,
    style = "minimal",
  }

  vim.api.nvim_open_win(bufnr, true, win_opts)
  vim.api.nvim_set_option_value("buftype", "prompt", { buf = bufnr })

  vim.keymap.set({ "n", "i" }, "<esc>", function()
    vim.api.nvim_buf_delete(bufnr, { force = true })
  end, { buffer = bufnr })
end

vim.api.nvim_create_user_command("WinFun", win_fun, {})
```
2. Start neovim with `nvim --clean +"repro.lua"`
3. Enter terminal buffer `:term`
4. Open floating prompt buffer window `:WinFun`
5. Enter insert mode in the floating window buffer
6. Exit the window/buffer with the `<esc>` mapping (while in insert mode)

### Expected behavior

Return to the terminal buffer in normal mode rather than terminal mode. 
This is the observed behavior when the non-floating buffer is a regular buffer.
Or put differently, this behavior of staying in the same mode when exiting floating windows currently only applies to regular buffer type floating windows (ie. try the repro steps without setting `buftype='prompt'` and over a regular buffer, exiting the floating buffer/window in insert mode will keep you in insert mode in the original buffer). Whichever way you put it, I think the current behavior at least feels inconsistent with itself. 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2095+ga34451982

### Vim (not Nvim) behaves the same?

not sure, probably yes but I'm using lua API

### Operating system/version

Linux archlinux 6.6.10-arch1-1

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
Hmm, the same bug applies to `:stopinsert`.
