### ISSUE TITLE
Function for Line Movement

### ISSUE THREAD

**Issue by MoonNight365** [neovim/neovim#27044]
### Problem

Hey there, it would be nice to make a function named Grab, short `Gb` / `gb`.

`Gb` / `gb`: Move to **previous** and grab on the left / Move to **next** and grab on the right.

At the moment, it is hard to decide IN ONE GO, to go to the previous or next line.
I made some examples to further understand the usage...

### Expected behavior

Examples:  

`Gb^` / `gb^` : First char on line to the left or previous / First char on line to the right or next
`Gb_` / `gb_` : First char on line to the left or previous / First char on line to the right or next

`Gbg_` / `gbg_` : Last char on line to the left or previous / Last char on line to the right or next

`Gb0` / `gb0` : Start of line to the left or previous / Start of line to the right or next
`Gb$` / `gb$` : End of line to the left or previous / End of line to the right or next

Maybe there are other creative ideas or other names for a function...

**Comment by bfredl** [comment]
Sorry, but what does "grab" mean in this context?

**Comment by craigmac** [comment]
Previous what, line? Grab as in visually select? Maybe a small example would help understand what you are trying to convey, like a test file and what you do now versus what you'd like to make that easier.

**Comment by MoonNight365** [comment]
At the moment it is just hard to choose the direction of these commands:

- `0` / `$`: Start /End of current line. 
- `_` / `g_`: First/Last Char on current line. 
- `^` and so on...

The function would solve that problem from navigation to the left (previous) or to the right (next). Another reason to make it like this is so you could add numbers like this:

 - `3Gb^` / `3gb^` : First char on 3th previous line / First char on 3th next line  
 - `4Gbg_` / `4gbg_` : Last char on 4th previous line / Last char on 4th next line

@craigmac 
The closest thing i could use as reference is this command:

`1-`/`1+`: First char line down / First char line up

@bfredl 
I meant Grab like this ... "grab first char... " or "grab first blank-space..." there are better names...
Grab is just an idea it don't need to be that..

**Comment by clason** [comment]
> Grab is just an idea it don't need to be that..

But it needs to be _something_, and it is on _you_ to specify that (since we have no idea what you want).

What we need is something _very_ explicit:

1. I have <this text> in a buffer (small example)
2. I press <these keys>
3. Then <this> should happen.

**Comment by bfredl** [comment]
> The closest thing i could use as reference is this command:

> 1-/1+: First char line down / First char line up

So why isn't these (and j/k enough)? they seem to compose like `-$` and `+$` etc in all your provided examples ?

**Comment by MoonNight365** [comment]
@bfredl 
Actually, this is the point...
You can use numbers on all of these `$` / `_` / `g_` / `^`  but you can't go up..
That's the problem I try to solve... but I guess I make it more complicated...

**Comment by MoonNight365** [comment]
@clason 
Basically what I want to say is that there are missing commands...
These symbols define the first Char of line -> `^`/ `_`. Then I guess to be more specific they created this this: 

`1-`/`1+`: First char line down / First char line up

But there is nothing for the last char and so on...

**Comment by lewis6991** [comment]
The ask here isn't compelling as to why this should be in core and not just a plugin.

Closing until a plugin exists and becomes popular enough to justify including in core.
