### ISSUE TITLE
"+yy fails with "clipboard: provider is not available" with xsel/xclip installed

### ISSUE THREAD

**Issue by hiqua** [neovim/neovim#2704]
I have never been able to use the system clipboard with nvim on Debian Jessie, although I have xsel and/or xclip which, according to http://neovim.io/doc/user/nvim_clipboard.html, should be enough. Each time I try `"+yy` or `"*yy` it fails with `clipboard: provider is not available`.

Both xsel and xclip install in `/usr/bin` which is in my `$PATH`, and I install neovim by running `make distclean && make && sudo make install` (which installs nvim in `/usr/local/bin`).

Is there anything else I have to do to make it work?

**Comment by Pyrohh** [comment]
What's the output for both `which -a` and `nvim --version`? Can you run `:!xsel` from inside nvim?

**Comment by bfredl** [comment]
Also check if environment variables`VIM` or `VIMRUNTIME` is set (neovim needs its own runtime for accessing the clipboard)

**Comment by hiqua** [comment]
Thanks @bfredl I looked for what could possibly go wrong with these variables in my .nvimrc, and indeed a long time ago I had sourced some vim files that come included with the Debian package of vim, among which `/usr/share/vim/vim74/debian.vim` which contains the line `set runtimepath=~/.vim,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim74,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,~/.vim/after". Commenting this line out did the trick.

**Comment by flipjs** [comment]
i have the same problem. i have xclip and xsel installed, but its still giving me provider is not available.

:echo has('clipboard') returns 0
:echo executable('xclip') returns 1
:echo executable('xsel') returns 1

I can run :!xclip or :!xsel too at the commandline.

Is there something else I still need to configure? Thanks.

**Comment by justinmk** [comment]
@flipjs what is `echo $DISPLAY` ?

**Comment by flipjs** [comment]
Did you mean :echo $DISPLAY from inside nvim? I get nothing. From the terminal, echo $DISPLAY also returns nothing.

Coincidentally, when I run :!xclip from inside nvim, I get this:

Error: Can't open display: (null)
shell returned 1

With :!xsel, I get this:

xsel: Can't open display: (null)
: Inappropriate ioctl for device
shell returned 1

By the way, I'm running Linux 14.04 Ubuntu (virtual machine). Its my dev machine and work from terminal (using Windows Putty).

**Comment by bfredl** [comment]
well, nvim on linux tries to access the X clipboard, same as vim. If X is not running there is no system clipboard for it to access.

**Comment by flipjs** [comment]
Is there a workaround for this? Maybe Putty can forward an X server or something?

**Comment by bfredl** [comment]
It could, if you run an X server on windows (and it integrates the clipboard, xming has a `-clipboard` option at least).
For paste: I don't know if the PuTTY terminal emulator supports bracketed paste, but you could try pasting some text in the terminal window and see if nvim interprets it as text and not as keystrokes (matters for autoindent, for instance)

**Comment by flipjs** [comment]
@bfredl Thanks for your quick reply. Will try that. Thanks.

**Comment by HarishVangala** [comment]
Just for clarity:

**Problem:** Unable to use system clipboard via + register. Usually people use a command like "+yy which fails with an error message like `clipboard provider is not available neovim` etc

**Solution:** Simply install an application called `xclip` (i.e. run for e.g. `sudo apt-get install xclip`). That's it! Neovim implicitly takes care of the problem. You may have to restart neovim (`nvim`).

**Reasons:**  As taken from `:help clipboard` run from neovim commandline

> Nvim has no direct connection to the system clipboard. Instead it is
> accessible through a |provider| which transparently uses shell commands for
> communicating with the clipboard.
> 
> Clipboard access is implicitly enabled if any of the following clipboard tools
> are found in your `$PATH`.
> 
>   - xclip
>   - xsel (newer alternative to xclip)
>   - pbcopy/pbpaste (Mac OS X)
>   - lemonade (for SSH) https://github.com/pocke/lemonade
>   - doitclient (for SSH) http://www.chiark.greenend.org.uk/~sgtatham/doit/

As on 5 October, 2016 on Ubuntu 16.04LTS, neovim installed via ppa.

**Comment by zhanjh** [comment]
if no  X server try:
https://github.com/cazador481/fakeclip.neovim

**Comment by AIGeneratedUsername** [comment]
What should I set as `$DISPLAY` value? I have `xclip` installed, but this is not enough to fix the warning.
NVIM v0.8.3

**Comment by tirzasrwn** [comment]
Install xclip and using ssh -X command work for me.
```sh
ssh -X user@ip
```

**Comment by Creiwry** [comment]
> Install xclip and using ssh -X command work for me.
> ```sh
> ssh -X user@ip
> ```

This worked for me! Also using a VM, ubuntu
