### ISSUE TITLE
Neovim aborts when nvim_buf_del_extmark() is called on an invalid extmark

### ISSUE THREAD

**Issue by rickhowe** [neovim/neovim#27055]
### Problem

Neovim aborts when nvim_buf_del_extmark() is called on an invalid extmark.

### Steps to reproduce

1. Run the code below. An inline virtual text is displayed on the 1st line.
```
call setline(1, ['11111', '22222', '33333'])
let ns = nvim_create_namespace('test')
let bn = bufnr('%')
call nvim_buf_set_extmark(bn, ns, 0, 5, #{virt_text: [['<-- ERROR!!!', 'Error']], virt_text_pos: 'inline', invalidate: v:true})
```
2. Delete the 1st line (:1d). The inline virtual text is hidden.
3. Show the ID of the extmark. `[[1, 0, 0]]` is echoed.
```
echo nvim_buf_get_extmarks(bn, ns, 0, -1, {})
```
4. Delete the hidden virtual text. Then, neovim suddenly aborts.
```
call nvim_buf_del_extmark(bn, ns, 1)
```
**Note:**
At step 3, try to show the details.
```
echo nvim_buf_get_extmarks(bn, ns, 0, -1, #{details: v:true})
```
echoes:
```
[1, 0, 0, {'virt_text_hide': v:false, 'priority': 4096, 'invalid': v:true, 'virt_text_repeat_linebreak': v:false, 'virt_text': [['<-- ERROR!!!', 'Error']], 'right_gravity': v:true, 'ns_id': 2, 'virt_text_pos': 'inline', 'invalidate': v:true}]
```
`'invalid': v:true` entry is present but this entry is not documented in help.

### Expected behavior

nvim_buf_del_extmark() can delete an invalid extmark and neovim does not abort.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2098+g92672a161

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

download from Github

**Comment by clason** [comment]
A backtrace would be helpful.

**Comment by luukvbaal** [comment]
> 'invalid': v:true entry is present but this entry is not documented in help.

Where did you expect this to be documented? The `invalidate` property is documented. I don't think the exact format of the `details` array is documented anywhere?

**Comment by rickhowe** [comment]
I want to make sure the 'invalid' entry and its value can be used to check the status and to avoid the abort in my plugin. Since all other details entries are documented in `nvim_buf_set_extmark()` as `{*opts}`,  I am worried if the not documented entry would be temporary as of today and would be gone later.
