### ISSUE TITLE
`vim.fs.normalize` does not support Windows UNC paths 

### ISSUE THREAD

**Issue by pysan3** [neovim/neovim#27068]
### Problem

Paths to network storages in Windows starts with double backslashes `\\` but is broken when passed to `vim.fs.normalize`.
I think this issue was introduced in https://github.com/neovim/neovim/pull/22791. Could you give me your opinion @lewis6991 ?

Such examples are as below.

- `\\wsl$\Ubuntu\home\user`
- `\\127.0.0.1\path`

When passed to `vim.fs.normalize`, the first backslash is deleted.

```lua
vim.print(vim.fs.normalize([[\\wsl$\Ubuntu\home\user]]))
--> /wsl$/Ubuntu/home/user
```

### Steps to reproduce

```lua
vim.print(vim.fs.normalize([[\\wsl$\Ubuntu\home\user]]))
--> /wsl$/Ubuntu/home/user
```

### Expected behavior

```lua
vim.print(vim.fs.normalize([[\\wsl$\Ubuntu\home\user]]))
-- This should return //wsl$/Ubuntu/home/user, with double slash at the front.
```

### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

No. It does not have `vim.fs.*`.

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal Preview

### $TERM environment variable

''

### Installation

winget

**Comment by lewis6991** [comment]
I'm not sure if UNC paths should be supported in `vim.fs` since they have no mapping to unix. The most reasonable thing I can think of is the current behaviour of `\\` -> `/`.

Thoughts @gpanders

**Comment by gpanders** [comment]
>The most reasonable thing I can think of is the current behaviour of \\ -> /.

Yep I agree, can't think of much else we could do.

**Comment by pysan3** [comment]
> The most reasonable thing I can think of is the current behaviour of `\\` -> `/`.

This is very unfortunate.

I do need the information that the path starts with a double slash, but I want to evaluate that after `expand_env`, so I can't just check it against the preprocessed path as well.

Could you add an option something like `opts.keep_dup_slashes (default: false)` that does not delete the duplicated slashes, and return the slashes as-is? (don't `:gsub('/+', '/')`).

I'd love to hear your opinions @lewis6991 @gpanders .

**Comment by lewis6991** [comment]
Like I've already said. It's out of scope for`vim.fs` to handle UNC paths like this since they cannot be represented as Unix style paths.

I suggest you handle this specially with custom code.

**Comment by pysan3** [comment]
@lewis6991 

Thanks for your feedback. However, I don't see any doc that states that `fs.normalize` (has to) supports Unix style paths, and even if not, imo I don't see a reason.

Besides, my PR is not meant to support UNC paths (above is just one usecase example) but it is just to add one option to branch out `gsub("/+", "/")` since slashes may include important information. And as the option defaults to true, this does not bring any breaking changes as well.

May I ask you why you want to stick to UNIX paths even though it is not mentioned anywhere in the docs?

PS. It's actually not just a [few lines of code](https://github.com/neovim/neovim/blob/6116495e6e6d3508eb99720faad7e55ba7cbe978/runtime/lua/vim/fs.lua#L321-L370) now. It's become pretty complicated (eg detect `C:/`) that I don't want to reimplement just because of `gsub("/+", "/")`.

**Comment by lewis6991** [comment]
> Thanks for your feedback. However, I don't see any doc that states that fs.normalize (has to) supports Unix style paths, and even if not, imo I don't see a reason.

It's implied as it outputs paths with `/` which are Unix paths. UNC paths use `\`. Therefore paths that begin with `//` don't mean anything.

**Comment by pysan3** [comment]
> It's implied as it outputs paths with `/` which are Unix paths. UNC paths use `\`. Therefore paths that begin with `//` don't mean anything.

Since the user must toggle the option off manually, `//` must mean _something_ important to that user and he must be aware of that. And let me reiterate that my PR is not meant to support UNC paths but it is just to add one option to branch out gsub("/+", "/").

> > PS. It's actually not just a few lines of code now. It's become pretty complicated (eg detect C:/) that I don't want to reimplement just because of gsub("/+", "/").
> 
> I'd prefer we don't make it any more complicated to support something that has no official meaning.

`//home//user//` is a valid Unix style path so I think unix commands have no problems handling them.

Could you advise me if there's a way to workaround `gsub("/+", "/")`? That would be very helpful.

**Comment by justinmk** [comment]
> I'm not sure if UNC paths should be supported in `vim.fs` since they have no mapping to unix.

Where is this requirement coming from? 

> `vim.fs.normaliize` is only a few lines of code anyway.

As it becomes more robust that may change. Normalizing paths has many edge cases that are useful to handle.

**Comment by lewis6991** [comment]
> Where is this requirement coming from?

The requirement is that vim.fs.normalize outputs valid paths and UNC paths must start with double backslash. Normalizing them to begin with double forward slash is ambiguous with no concrete meaning (correct me if I'm wrong). 

> As it becomes more robust that may change. Normalizing paths has many edge cases that are useful to handle.

I think handling every edge case is a fools errand. Normalizing a path shouldn't require a handful of options.

We shouldn't be trying to reinvent how path handling should be done. If a standard popular path library has a good solution for this that we can follow, then maybe that makes sense for us to follow.

**Comment by dundargoc** [comment]
> Normalizing them to begin with double forward slash is ambiguous with no concrete meaning

I did some researching on this as I was curious myself. I have not found a definitive answer, but I'm pretty sure leading double forward slash is defined as UNC based on e.g. [this](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/unc-path-recognition-unix) and [this](https://github.com/PowerShell/PowerShell/pull/17117), indicating that microsoft "tooling" recognizes leading doubleslash as valid.

**Comment by justinmk** [comment]
> I think handling every edge case is a fools errand. Normalizing a path shouldn't require a handful of options.

I don't really agree. Dealing with the dirty stuff is the purpose of providing these utilities in the first place.

**Comment by lewis6991** [comment]
From https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_13

> If a pathname begins with two successive <slash> characters, the first component following the leading <slash> characters may be interpreted in an implementation-defined manner, although more than two leading <slash> characters shall be treated as a single <slash> character.

So we should just preserve any leading double slash.

**Comment by pysan3** [comment]
I've updated the PR to support UNC path! Please check it out. 

https://github.com/neovim/neovim/pull/27202#issuecomment-1919471413

**Comment by pysan3** [comment]
@dundargoc Thanks for working on this. Your work is amazing.

However, I was ordered to add more test cases in my PR which I wonder why they didn't request on your PR.
You can see the diff here: https://github.com/neovim/neovim/pull/27202/files#diff-22260c58f0aad18ee7f70b3ae84f09fe6537b4136a2e0b87952ca560f81f1e7a and the specs they ordered me to follow were

- Change all test string to `[[path/foo/bar]]` instead of single quotes.
- Capitalizes drive name on Windows
  - `eq('C:/foo/bar', vim.fs.normalize([[c:\foo/bar\/]]))`
  - `eq('c/this/is/a/relative/path', vim.fs.normalize([[c\this\is\a\relative\path]]))`
- works with mixed forward and backward slashes
  - `eq('C:/Users/jdoe', vim.fs.normalize([[C:\/Users/\jdoe/\]]))`

I think we should also add test against _drive-specific relative paths_ on Windows just in case according to Windows specifications. (The last example in the table.)

> https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#traditional-dos-paths
> `C:Projects\apilibrary\apilibrary.sln`

What do you think?

**Comment by dundargoc** [comment]
There's this [PR](https://github.com/neovim/neovim/pull/28203) that addresses some (most?) of the points you brought up.

**Comment by pysan3** [comment]
Interesting. Should I reopen this issue?

**Comment by dundargoc** [comment]
Huh? Isn't this issue solved though? `vim.fs.normalize` supports windows unc paths now, which is what this issue was about.

**Comment by dundargoc** [comment]
> Change all test string to [[path/foo/bar]] instead of single quotes.

I can't find where someone said that this was needed. Where was this said?

As for the drive casing, I will make a PR.

**Comment by pysan3** [comment]
They are closed so it is very difficult to find. 

I mentioned you in the discussions and I hope GitHub sent you a notification there.

**Comment by dundargoc** [comment]
Fine. I can add the tests for drive capitalization and mixed backslash and forward slash. I will see about raw strings, I may omit that. @famiu is working on `vim.fs.normalize` right now so either he should tackle this as well or I can work on it after him.

**Comment by pysan3** [comment]
> I can add the tests for drive capitalization and mixed backslash and forward slash. I will see about raw strings, I may omit that. @famiu is working on `vim.fs.normalize` right now so either he should tackle this as well or I can work on it after him.

Fair enough. I don't have any opinion on how the problem is dealt now. 
I'm just complaining that your PR got accepted even though many people criticized my PR and never wanted it to be merged by adding more and more test requirements in my case :'(

I proposed to reopen this issue so that @famiu or you can remember to add the test cases I mentioned above and make a commit with _fixes: #27068_.
