### ISSUE TITLE
[RFC] Introduce a dynamic string lib (kstring.h?)

### ISSUE THREAD

**Issue by philix** [neovim/neovim#2707]
As noticed/commented in #858, #731, #210... (Neo)vim uses `garray_T` as a dynamic string data type and would benefit from a dedicated structure.

An ugly example of `garray_T` as a dynamic string can be found in `charset.c`:

```c
char_u* str_foldcase(char_u *str, int orglen, char_u *buf, int buflen)
  FUNC_ATTR_NONNULL_RET
{
  garray_T ga;
  int i;
  int len = orglen;

#define GA_CHAR(i) ((char_u *)ga.ga_data)[i]
#define GA_PTR(i) ((char_u *)ga.ga_data + i)
#define STR_CHAR(i) (buf == NULL ? GA_CHAR(i) : buf[i])
#define STR_PTR(i) (buf == NULL ? GA_PTR(i) : buf + i)

  // Copy "str" into "buf" or allocated memory, unmodified.
  if (buf == NULL) {
    ga_init(&ga, 1, 10);

    ga_grow(&ga, len + 1);
    memmove(ga.ga_data, str, (size_t)len);
    ga.ga_len = len;
  } else {
    if (len >= buflen) {
      // Ugly!
      len = buflen - 1;
    }
    memmove(buf, str, (size_t)len);
  }

  if (buf == NULL) {
    GA_CHAR(len) = NUL;
  } else {
    buf[len] = NUL;
  }
```
What about using [`kstring.h`](https://github.com/attractivechaos/klib/blob/master/kstring.h) as a dynamic string library? We've been using `klib` for other structures, it's a non-opaque type (i.e. it's OK to use its fields directly as we do with `garray_T`) and has even less fields than `garray_T` (same size because `garray_T` uses `int` for the 4 length fields it has).

**Comment by splinterofchaos** [comment]
`kstring` looks like a good option for `str_foldcase`. My only nit is that it puts the `kstring` as the second parameter in functions like `kputs()`, where usually the destination should be first. 

We also have a `DynamicBuffer`, which this could maybe replace.

**Comment by justinmk** [comment]
How does it compare to sds? Neither klib  nor sds are paying attention to pull requests. sds appears to have actual documentation.

**Comment by philix** [comment]
> We also have a DynamicBuffer, which this could maybe replace.

`DynamicBuffer`, from the code I saw in `shell.c`, seems to be only the struct definition and has to be directly manipulated.

> How does it compare to sds? Neither klib nor sds are paying attention to pull requests. sds appears to have actual documentation.

When I suggested people noticed the tools we use to check the source code wouldn't play well with how `sds` deals with the `char *` pointers.

And the advantage of `kstring` is that it's very small and we can tweak it to use our `x*` functions for memory handling just as we've been doing with the other `klib` structures.

**Comment by philix** [comment]
I created #2709 to show how this looks like.

**Comment by philix** [comment]
@justinmk `klib` ignoring PRs is very unfortunate. I would like to have [this PR](https://github.com/attractivechaos/klib/pull/30/files) implementing `ks_release()` for ownership transfer merged. We will end up implementing it ourselves. We've been changing all the `klib` structures to our needs anyway.

**Comment by justinmk** [comment]
Going to regard https://github.com/neovim/neovim/pull/2709 as the driver for this.
