### ISSUE TITLE
nightly: Error in decoration provider treesitter/highlighter.win

### ISSUE THREAD

**Issue by Kamilcuk** [neovim/neovim#27078]
The problem is reproducible on nightly. The problem is not reproducible on nvim v0.9.5 from archlinux repos.

I posted the issue on nvim-treesitter https://github.com/nvim-treesitter/nvim-treesitter/issues/5917 and @clason recommended to post here, so I am doing it.

### Problem

When editing a `.sh` file the following error comes up:

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:751: Vim:E219: Brak {.                                   
stack traceback:                                                                                                                          
        [C]: in function 'nvim_get_runtime_file'                                                                                          
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:751: in function 'fn'                                                 
        ...vim/install/share/nvim/runtime/lua/vim/func/_memoize.lua:54: in function 'has_parser'                                          
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:760: in function 'resolve_lang'                                       
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:799: in function '_get_injection'                                     
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:844: in function 'f'                                                  
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:192: in function 'tcall'                                              
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:383: in function '_add_injections'                                    
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:446: in function 'parse'                                              
        ...ll/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:350: in function <...ll/share/nv     
```

### Steps to reproduce

1. Create the following file:

```
#!/bin/bash
      config {
        args = [<<-EOF
          exec sleep 60
          ${var.script}
        EOF
        ]
      }
    }
  }
}
```

2. Save it as testfile.sh

3. Open with neovim __nightly__

4. The error just happens on startup and I think happens in a loop. Editor is unusable.

![obraz](https://github.com/nvim-treesitter/nvim-treesitter/assets/15679217/81314492-2e46-4688-a047-3c60298d2d5e)

### Expected behavior

The editor should be usable.

### Output of `:checkhealth nvim-treesitter`

```markdown
1                                                                                                                                   
        1 ──────────────────────────────────────────────────────────────────────────────
        2 nvim-treesitter: require("nvim-treesitter.health").check()
        3 
        4 Installation
        5 - WARNING tree-sitter executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :                   TSInstall)
        6 - OK node found v21.5.0 (only needed for :TSInstallFromGrammar)
        7 - OK git executable found.
        8 - OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
        9   Version: cc (GCC) 13.2.1 20230801
       10 - OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
       11 
       12 OS Info:
       13 {
       14   machine = "x86_64",
       15   release = "6.7.0-zen3-1-zen",
       16   sysname = "Linux",
       17   version = "#1 ZEN SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:36:54 +0000"
       18 } 
       19 
       20 Parser/Features         H L F I J
       21   - bash                ✓ ✓ ✓ . ✓
       22   - c                   ✓ ✓ ✓ ✓ ✓
       23   - cpp                 ✓ ✓ ✓ ✓ ✓
       24   - lua                 ✓ ✓ ✓ ✓ ✓
       25   - markdown            ✓ . ✓ ✓ ✓
       26   - markdown_inline     ✓ . . . ✓
       27   - python              ✓ ✓ ✓ ✓ ✓
       28   - query               ✓ ✓ ✓ ✓ ✓
       29   - vim                 ✓ ✓ ✓ . ✓
       30   - vimdoc              ✓ . . . ✓
       31 
       32   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
       33          +) multiple parsers found, only one will be used
       34          x) errors found in the query, try to run :TSUpdate {lang}
       35 


also:

```
$ git -C .vim/plugged/nvim-treesitter/ log -1
commit 503d0ccdee762bb4b2758c391288768fafe39861 (HEAD -> master, origin/update-readme-pr, origin/master, origin/HEAD)
Author: GitHub <noreply@github.com>
Date:   Thu Jan 18 06:37:49 2024 +0000
```

### Output of `nvim --version`

```text
$ nvim -V1 -v
NVIM v0.10.0-dev-2121+g06aebfa99
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
Compilation: /usr/bin/cc -O2 -g -Og -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always  -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/home/kamil/.cache/,nvim/neovim/.deps/usr/include/luajit-2.1 -I/home/kamil/.cache/,nvim/neovim/.deps/usr/include -I/home/kamil/.cache/,nvim/neovim/build/src/nvim/auto -I/home/kamil/.cache/,nvim/neovim/build/include -I/home/kamil/.cache/,nvim/neovim/build/cmake.config -I/home/kamil/.cache/,nvim/neovim/src -I/usr/include 

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/kamil/.cache/,nvim/install/share/nvim"

Run :checkhealth for more info
```

### Additional context

Thanks! Just a heads up that there may be problems with nvim-nightly. I do not know if report here or upstream to neovim. Disabling nvim-treesitter from vim-plug makes the issue dissapear. Thanks!

### Neovim version (nvim -v)

v0.10.0-dev-2121+g06aebfa99

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ArchLinux

### Terminal name/version

KDE konsole

### $TERM environment variable

xterm-256color

### Installation

git clone https://github.com/neovim/neovim.git && cd neovim && git checkout tags/nightly && make CMAKE_BUILD_TYPE=RealWithDebInfo VERBOSE=1 CMAKE_INSTALL_PREFIX=mydir cmake nvim install

**Comment by clason** [comment]
> I confirm the problem is not reproducible on master or latest stable release.

master _is_ nightly, so can you clarify what this means?

**Comment by clason** [comment]
The issue here is with the language lookup for injections (`resolve_lang`), which gets passed
```
      }
    }
  }
```
for some reason. This is invalid bash, but the language alias resolver needs to be smarter in validating what is passed to `nvim_get_runtime_files`.

**Comment by Kamilcuk** [comment]
> master is nightly, so can you clarify what this means?

Hi. "Master is nightly"! Ok, thansk, good to know. I blindly guessed that nightly is https://github.com/neovim/neovim/tree/nightly and master is https://github.com/neovim/neovim/tree/master and that they differ. So it is reproducible on nightly.

**Comment by clason** [comment]
So you tested both and only `master` throws the error, is that correct?

**Comment by Kamilcuk** [comment]
So to confirm: I tested current today's nightly tag.

I just now recompiled with master NVIM v0.10.0-dev-1249+gdc6d0d2da , and can also reproduce. So both.

**Comment by lucario387** [comment]
This is technically correct :thinking: 
addubg adding some whitespaces and newline before `config ...` and I got this tree
`:InspectTree` results:
```scheme
(comment) ; [1:1 - 11]
(command ; [4:7 - 14]
  name: (command_name ; [4:7 - 12]
    (word)) ; [4:7 - 12]
  argument: (word)) ; [4:14 - 14]
(redirected_statement ; [5:9 - 14:0]
  body: (command ; [5:9 - 16]
    name: (command_name ; [5:9 - 12]
      (word)) ; [5:9 - 12]
    argument: (word) ; [5:14 - 14]
    argument: (word)) ; [5:16 - 16]
  redirect: (heredoc_redirect ; [5:17 - 14:0]
    (heredoc_start) ; [5:20 - 22]
    (heredoc_body ; [6:11 - 10:7]
      (expansion ; [7:11 - 10:7]
        (variable_name) ; [7:13 - 15]
        (ERROR ; [7:16 - 9:9]
          (word) ; [7:16 - 22]
          (word)))) ; [8:9 - 11]
    (heredoc_end))) ; [11:1 - 14:0]
```

So shouldn't this be a bash parser issue

**Comment by Kamilcuk** [comment]
One note to add from my side: I am completely happy with the parser failing with some error message and dying, becuase the shell file is just invalid. From my user perspective, the issue is that the editor becomes unusable, because the error looks like is printed in an endless loop and I can't continue to work. Maybe I should have clarified this with the title of the issue. Doing `:TSDisable sh` doesn't unblock the editor or I do not know how to turn it off.

**Comment by clason** [comment]
`<ctrl-c>` and then `:lua vim.treesitter.stop()` works.

(This doesn't make this less of a bug to be fixed _somewhere_, but if you need a workaround in the meantime, this is it.)

**Comment by clason** [comment]
Short-term fix is to identify the corresponding pattern and make it more robust or remove it.

**Comment by Kamilcuk** [comment]
> if you need a workaround in the meantime

Yes, great, thank you!

**Comment by clason** [comment]
Can you test https://github.com/neovim/neovim/pull/27080?

**Comment by Kamilcuk** [comment]
> Can you test https://github.com/neovim/neovim/pull/27080?

Looks fine. I am not able to reproduce on v0.10.0-dev-2117+g5ee15ef66 .
