### ISSUE TITLE
Remapping with ESC is painfully slow

### ISSUE THREAD

**Issue by ashton-fedler** [neovim/neovim#27081]
### Problem

When in visual/select mode, for a number of commands, I would like to cancel selection immediately execute the command in normal mode.

Example:
```lua
vim.keymap.set("x", "a", "<ESC>a", {})
```

Looking at prior issues it looks like NeoVim is translating some "quick keys" into escape sequences that does not occur in Vim. Is there a Lua alternative for switching modes to enable users to bypass <ESC> in general?

### Steps to reproduce

Add the following remap: 
`vim.keymap.set("x", "a", "<ESC>a", {})`

Make any selection, say current line: 
`Shift + v'

Press `a`
Now wait, ... :^(

### Expected behavior

Just like we have vim.cmd and <cmd>, I would like to have a vim.send_keys with mode options

### Neovim version (nvim -v)

v0.10.0-dev-5aa14e1

### Vim (not Nvim) behaves the same?

no, 9.0 macOS version - arm64

### Operating system/version

macOS 14.2.1

### Terminal name/version

Wezterm, Kitty, and Terminal

### $TERM environment variable

xterm-256color

### Installation

nix profile install 'github:neovim/neovim?dir-contrib#neovim'

**Comment by clason** [comment]
`:h map-nowait`

**Comment by ashton-fedler** [comment]
brilliant! - Thank you, so much!

**Comment by clason** [comment]
(didn't think that would help, since escape sequences were mentioned, but I pointed out `:h map-nowait`)

**Comment by ashton-fedler** [comment]
oh there are definitely still issues with some keys that may combine to control sequences but mostly be mitigated.

[See Issue](https://github.com/neovim/neovim/issues/13086)
```lua
:inoremap <M-;> <ESC>:
:nnoremap ; :
```
In general, I would still love to send a table of keys and modes, but this helps a ton.
