### ISSUE TITLE
64a14026d76ba1798d91e15a941fcb6af7cbc5ad breaks syntax highlighting

### ISSUE THREAD

**Issue by bigcattus** [neovim/neovim#27083]
### Problem

Not using treesitter nor lsp.   Highlighting works fine in 17f3a3ae31d91944a5a4e56aa743745cff7fdf07,  but in 64a14026d it becomes very basic.  Hightlight is limited to language keywords (boldface "if", "then" for example), and green colored string.  No other highlighting visible.    Same happens when I get rid of my initial config file, i.e. run with vanilla nvim.  Thanks.

### Steps to reproduce

Compare versions above.

### Expected behavior

Not sure.

### Neovim version (nvim -v)

64a14026d76ba1798d91e15a941fcb6af7cbc5ad

### Vim (not Nvim) behaves the same?

have not tried

### Operating system/version

linux centos

### Terminal name/version

xterm with tmux and without

### $TERM environment variable

screen-256color

### Installation

build from repo

**Comment by clason** [comment]
This is intentional. Use :colorscheme vim to revert to the legacy colorscheme.

**Comment by bigcattus** [comment]
Thanks!   A followup question, what was achieved by that change? Maybe I am missing some config to take advantage of it?  The colorscheme is not the only thing that was affected; I think a divider between split windows also gone missing.

**Comment by clason** [comment]
It was exactly the colorscheme. (You can search closed issues and PRs about the new "default colorscheme" if you are curious about the reasoning.)

**Comment by bigcattus** [comment]
Thank you. Appreciate the explanation.
