### ISSUE TITLE
Cursor hidden after quitting "ranger" running inside neovim terminal

### ISSUE THREAD

**Issue by BohrShaw** [neovim/neovim#2708]
This occurs when I had opened a file with the editor(nvim) in ranger.

**Comment by justinmk** [comment]
Does https://github.com/neovim/neovim/pull/2598 fix it for you?

**Comment by bohrshaw** [comment]
@justinmk I can't test this now as I don't build neovim myself.

**Comment by Pyrohh** [comment]
If this isn't closed now it'll probably be forgotten for a while, so I'll do so now. When/if you're able to reproduce this @bohrshaw, please re-open this.

**Comment by justinmk** [comment]
@bohrshaw  #2598 was merged so could you please test this again?

**Comment by bohrshaw** [comment]
Cursor is still hidden. (after quitting ranger, but only when I had opened a file with vim or nvim from ranger before quit)

But I'm unsure if I'm using a version with #2598 merged. I'm on neovim compiled May 27 obtained from Ubuntu PPA. I'll test it again later.

**Comment by justinmk** [comment]
@BohrShaw what terminal?

**Comment by BohrShaw** [comment]
@justinmk It was the standard gnome-terminal on Ubuntu 14.04.

**Comment by jszakmeister** [comment]
FWIW, I have a user of vim-togglecursor who is seeing an issue with the cursor disappearing too, who is also using gnome-terminal (though under Arch Linux and based on a different version).  I wonder if this is another VTE bug?  For reference, the bug my user is seeing is jszakmeister/vim-togglecursor#19.

**Comment by justinmk** [comment]
@BohrShaw @jszakmeister That's what I was expecting, it's a libvte bug: https://github.com/neovim/neovim/pull/3110#issuecomment-131276376
