### ISSUE TITLE
how-to-use-the-windows-clipboard-from-wsl url 404 

### ISSUE THREAD

**Issue by 91hm** [neovim/neovim#27089]
### Problem

https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl
I really need this article. Please help me find it. Thank you

### Expected behavior

https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl
I really need this article. Please help me find it. Thank you

**Comment by wookayin** [comment]
[Search Documentation](https://neovim.io/doc/).

`:help clipboard-wsl`

https://neovim.io/doc/user/provider.html#clipboard-wsl

**Comment by ukanuk** [comment]
I've seen that link in many places, including this repo's old issues and on Reddit.

Annoyingly https://neovim.io/doc/user/provider.html#clipboard-wsl provides the config info for `.vimrc` but not `init.lua`. 

I ended up running `winget install win32yank` and that seems to have it working normally now.
