### ISSUE TITLE
switching back and forth from a markdown buffer seems to make the parsing fail when the vim.o.foldmethod is set to "marker"

### ISSUE THREAD

**Issue by lmenou** [neovim/neovim#27094]
### Problem

Hi, thanks for the work on this editor !

I noticed recently that using `markdown` and `markdow_inline` parsers [here](https://github.com/MDeiml/tree-sitter-markdown), the buffer parsing seems to fail when switching back and forth with e.g `ctrl-o` and `ctrl-i`.
The parsing is fine when entering and editing the buffer on the first time. However, when moving away and coming back, the parsing seems to fail, but as soon as an action is performed on the buffer (e.g just saving), everything "synchronizes back" (without even using the command "solving" the issue https://github.com/nvim-treesitter/nvim-treesitter/issues/78, that is why I am opening this one)

I think this is a neovim related issue because the latter bug does not exist anymore when not setting `vim.wo.foldmethod = "marker"`.

Thanks for your time and your attention to this.

### Steps to reproduce

1. Use the following `init.lua` with `nvim-treesitter` plugin installed
```lua
local success, treesitter = pcall(require, "nvim-treesitter.configs")

if not success then
  return
end

treesitter.setup {
  ensure_installed = { "c", "lua", "vim", "vimdoc", "query", "markdown", "markdown_inline" },
  sync_install = false,
  auto_install = false,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = false,
  },
  ignore_install = {},
  modules = {},
}

-- default vim.wo.foldenable = true
vim.wo.foldmethod = "marker"
```

2. Try with the following two markdown notes
```markdown
- Write some things
    - Here some tests
    ```python
    print("hello neovim")


    class NeoVim:

        def __init__(self, great):
            self.great = great
    ```
```

```markdown
- Write some things
    - Here some tests
    ```javascript
    const weak = new WeakSet()
    const obj = { hej: "hej" }
    weak.add(obj)

    if (weak.has(obj) {
        console.log(weak);
    }
    ```
```

3. Try to jumps between the two of them back and forth with `ctrl-o` or `ctrl-i` 
4. One should observe that the highlighting of the code is failing and other niceties of the previous parsers are not working.


### Expected behavior

Even with the latter setting `foldmethod` set to `"marker"`, I would have expected the previous switching to work fine.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2133+g5a8fe0769

### Vim (not Nvim) behaves the same?

no treesitter

### Operating system/version

Ubuntu 22.04.3 LTS

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo (release build type)

**Comment by tomtomjhj** [comment]
I think this could have been fixed by https://github.com/neovim/neovim/pull/28530. Can you still reproduce on the latest version?

**Comment by lmenou** [comment]
Hi ! Woops, @tomtomjhj you are right ! Thanks for pointing on this. Closing this then.
