### ISSUE TITLE
`has(python3') return code differs between two different OS versions

### ISSUE THREAD

**Issue by hyunsooda** [neovim/neovim#27095]
### Problem

Hi,

A print `:echo has('python3')` for the two distiributions below,

Ubuntu 23.10 (`6.5.0-14-generic`)    returns 1
Ubuntu 18.04 (`5.4.0-128-generic`)  returns 0

When attempting both source code build and the provided release binary(appimage), both resulted in a return 0.  Is there a way to get it work on Ubuntu 18.04?

Thank you.

### Steps to reproduce

nvim
:echo has('python3')

### Expected behavior

Should return 1.

### Neovim version (nvim -v)

0.9.0 to 0.9.5

### Vim (not Nvim) behaves the same?

Not checked

### Operating system/version

Ubuntu 18.04 

### Terminal name/version

Alactrtity 0.13.1

### $TERM environment variable

xterm-256color

### Installation

build from repo & release binary (appimage)

**Comment by zeertzjq** [comment]
Install https://github.com/neovim/pynvim

**Comment by hyunsooda** [comment]
Works! thank you :)
