### ISSUE TITLE
Remove default Rust keymaps from the core

### ISSUE THREAD

**Issue by alex35mil** [neovim/neovim#27105]
### Problem

https://github.com/neovim/neovim/blob/8744ee8783a8597f9fce4a573ae05aca2f412120/runtime/ftplugin/rust.vim#L139-L142

These keymaps are hardcoded into the core and AFAICT are not trivially overridable. IMO such keymaps should be set in user space.

### Expected behavior

I can assign my actions to these keymaps without hacks to disable hardcoded ones.

**Comment by clason** [comment]
We don't maintain these plugins; please contact the maintainer listed at the top of the file.

**Comment by alex35mil** [comment]
@clason Thanks for quick reply.

Seems like these bindings were [removed from the source](https://github.com/rust-lang/rust.vim/commit/c2f6ea0906de05285e16a6385452cd0f6b553c6e) long time ago. What needs to be done to pull the latest into the Neovim?

**Comment by clason** [comment]
Have the maintainer update the bundled plugin in Vim. (Any changes to these files in Vim are ported by us.)

**Comment by alex35mil** [comment]
Looks like it was done recently: https://github.com/vim/vim/pull/13075

**Comment by clason** [comment]
Wait, what Neovim version are you on?

**Comment by alex35mil** [comment]
```
❯ nvim -v
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/wf2xdszsi9snfidrcv1hs49ksh0c8xw7-neovim-unwrapped-0.9.5/share/nvim
```

**Comment by clason** [comment]
OK, then I'm afraid you'll have to wait until the next major release (0.10.0); we don't backport runtime file updates. (The changes are already on `master`.)

**Comment by alex35mil** [comment]
Gotcha, thanks for your help!
