### ISSUE TITLE
Parentheses text object `(...)` not recognized correctly in some cases, e.g. if the previous line ends with an opening parenthesis

### ISSUE THREAD

**Issue by camoz** [neovim/neovim#27104]
### Problem

`(...)` don't seem to work consistently and depend on text on other lines.

### Steps to reproduce

`nvim --clean`

Insert into buffer:

```
(
print( myvar )
```

Place cursor on print. Enter e.g. `vi(`

### Expected behavior

`(...)` text object on current line is selected, like when the first line contains no `(` or contains `( text )` etc.

### Neovim version (nvim -v)

v0.9.5

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Archlinux

### Terminal name/version

foot version: 1.16.2

### $TERM environment variable

foot-extra

### Installation

official repos

**Comment by zeertzjq** [comment]
This should be reported to Vim.

**Comment by camoz** [comment]
I see.

It looks like it has already been reported there 8 years ago: https://github.com/vim/vim/issues/915
