### ISSUE TITLE
Support sourcing range of non-lua buffer as lua

### ISSUE THREAD

**Issue by Song-Tianxiang** [neovim/neovim#27103]
### Problem

Nowadays, `:so` only can load lua config if current file name extension is `.lua`. Not support range. Not support load code in a buffer but not in a file.

### Expected behavior

~~Maybe we can have a separate `:luaso` command to support load lua config like `:so` for vimscript.~~

`:[range]lua` can execute selected Lua code regardless of buffer type.

**Comment by Song-Tianxiang** [comment]
I often want to try lua example code in help file, it would be convenient if we have `:so` that support range select and scratch buffer for lua code.

**Comment by clason** [comment]
It can, though.

**Comment by wookayin** [comment]
>  Not support range. Not support load code in a buffer but not in a file.

This is not correct --- `:so` *does* support range on a buffer (try visual block and then `:so` or something like `3,4:so`).

**Comment by wookayin** [comment]
All that said, I think the crux of OP's request is a way to run Lua snippets from *non*-lua-files (e.g. vimdoc), especially when injection is used (which I think is a reasonable request).

I can think of something like `:so ++lua` BTW.

**Comment by Song-Tianxiang** [comment]
> It can, th

> It can, though, as long as the _filetype_ is Lua. I think that's a reasonable constraint.但是，只要文件类型是 Lua，它就可以。我认为这是一个合理的限制。

I have try to `:set filetype=lua` in a [No Name] buffer but it not make `:so` work like in a file with `.lua` extension. `:so` does not recognize `filetype` option.

**Comment by Song-Tianxiang** [comment]
> As a workaround, one can write manually a custom user command or keymap that does the similar job:作为解决方法，可以手动编写执行类似工作的自定义用户命令或键盘映射：
> 
> (Extracted and slightly modified from my config)（从我的配置中提取并稍作修改）
> 
> ```lua
> vim.keymap.set('x', '<leader>so', function()
>   local vstart = assert(vim.fn.getpos("v"))
>   local vend = assert(vim.fn.getpos("."))
>   local line_start = vstart[2]
>   local line_end = vend[2]
>   if line_start > line_end then
>     line_start, line_end = line_end, line_start
>   end
>   local lines = vim.api.nvim_buf_get_lines(0, line_start - 1, line_end, true)
> 
>   local code = table.concat(lines, '\n')
> 
>   -- "evaluate" the lines literally as a Lua script
>   loadstring(code)()
> 
>   -- exit the visual mode
>   return '<Esc>'
> 
> end, { expr = true, remap = false })
> ```
> 
> Note: this is not complete -- it's not a User cmd that doesn't support `<range>`. But it'd be straightforward to make it support them as well.注意：这并不完整 -- 它不是不支持 `<range>` .但是，让它也支持它们也很简单。



> As a workaround, one can write manually a custom user command or keymap that does the similar job:
> 
> (Extracted and slightly modified from my config)
> 
> ```lua
> vim.keymap.set('x', '<leader>so', function()
>   local vstart = assert(vim.fn.getpos("v"))
>   local vend = assert(vim.fn.getpos("."))
>   local line_start = vstart[2]
>   local line_end = vend[2]
>   if line_start > line_end then
>     line_start, line_end = line_end, line_start
>   end
>   local lines = vim.api.nvim_buf_get_lines(0, line_start - 1, line_end, true)
> 
>   local code = table.concat(lines, '\n')
> 
>   -- "evaluate" the lines literally as a Lua script
>   loadstring(code)()
> 
>   -- exit the visual mode
>   return '<Esc>'
> 
> end, { expr = true, remap = false })
> ```
> 
> Note: this is not complete -- it's not a User cmd that doesn't support `<range>`. But it'd be straightforward to make it support them as well.

Thank you, It works for me. I think this custom keymap or command is enough for me.

**Comment by justinmk** [comment]
> OP's request is a way to run Lua snippets from _non_-lua-files (e.g. vimdoc)

Definitely would like that. How about adding range support to `:lua` ?
