### ISSUE TITLE
vim exec command and run by urlview doesn't work 

### ISSUE THREAD

**Issue by kkanas** [neovim/neovim#27108]
### Problem

:!urlview %<cr>

### Steps to reproduce

nvim --clean some-file-with-urls
execute
:!urlview %<cr>
you got ^[[3;3H
show over and over again 

### Expected behavior

urlview can execute 

### Neovim version (nvim -v)

VIM v0.9.5 Build type: Release LuaJIT 2.1.1703358377

### Vim (not Nvim) behaves the same?

no vim works fine 

### Operating system/version

macos Version 14.2.1 (23C71)

### Terminal name/version

iterm2 Build 3.4.23

### $TERM environment variable

xterm-256color

### Installation

brew / and build from sources ba9f86a9cee58dc32ab875da1fd7eac9bc9e88d7

**Comment by clason** [comment]
Use `:term` in Neovim; `:!` does not open a shell.

**Comment by kkanas** [comment]
Thank you @clason  :term! urlview % works - just need to enter insert mode or add autocmd TermOpen * startinsert
