### ISSUE TITLE
when getting extmark with details=true, doesn't return conceal/spell if hl_group=nil

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#27114]
### Problem

When creating a conceal extmark with hl_group=nil, and then trying to get that extmark (with details=true), it won't return the conceal.

### Steps to reproduce

Run with `nvim --clean -l`
```lua
local ns=vim.api.nvim_create_namespace'test'
vim.api.nvim_buf_clear_namespace(0,ns,0,-1)
vim.api.nvim_buf_set_lines(0,0,-1,true,{'test'})
vim.api.nvim_buf_set_extmark(0,ns,0,0,{end_col=1,conceal='a'})
--vim.api.nvim_buf_set_extmark(0,ns,0,0,{end_col=1,conceal='b',hl_group='Conceal'}) --Uncomment this to see what should happen
vim.print(vim.api.nvim_buf_get_extmarks(0,ns,0,-1,{details=true}))
```

### Expected behavior

`nvim_buf_get_extrmarks` (and other similar functions) return `conceal` when `details=true` and `extmark.hl_group=nil`.

### Neovim version (nvim -v)

0.10.0-dev-fa4b02f

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

build from repo

**Comment by zeertzjq** [comment]
Bug also applies to `spell`
