### ISSUE TITLE
Neovim taking too much memory in react project

### ISSUE THREAD

**Issue by Sarthak950** [neovim/neovim#27118]
### Problem

i have a react project and launching that project in instantly takes up all the available memory and makes the system unusable 

### Steps to reproduce

its on my machine 

### Expected behavior

it should not use that much memory

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

no 

### Operating system/version

arch 

### Terminal name/version

alacrity and neovide

### $TERM environment variable

xterm

### Installation

AUR

**Comment by clason** [comment]
We need (minimal!) steps to reproduce it. Can you share that file? What's your config (don't paste it here)! Does it happen with `nvim --clean`?

**Comment by Sarthak950** [comment]
i cant share the project on public domains as its for an organization  
i will share my config https://github.com/Sarthak950/.config
i reinstalled the nvim and it still persist

**Comment by wookayin** [comment]
At least you should try to provide relevant config or information (e.g. which LSP server is used for react/typesript projects). Making a minimal reproduction would be the best but we understand this requires some non-trivial efforts.

This is likely the problem of `tailwindcss` or other language server you are using, not of neovim or nvim-lspconfig. You can try ablating some of the language server and see if that improves, to figure out which LSP is causing a problem for you. Please report your issue to the repository of the specific LSP. If you still believe it's a problem of neovim, then this can be re-opened with more infomration provided.
