### ISSUE TITLE
"verbose map" reports incorrect "Last set" details with "-V1" argument used

### ISSUE THREAD

**Issue by dnebauer** [neovim/neovim#27125]
### Problem

Running `verbose map <Esc>` resulted in a "Last set" message of "Last set from Lua". Starting nvim with the argument `-V1` and running the same command resulted in a "Last set" message of "Last set from ~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/util/init.lua line 167". On my installation that is a "lazy" plugin function that wraps `vim.keymap.set` -- I have added the file.
[init.lua.zip](https://github.com/neovim/neovim/files/14008580/init.lua.zip)

Some grepping found the actual `vim.keymap.set` command in line 43 of `~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/config/keymaps.lua` -- which I have also added.
[keymaps.lua.zip](https://github.com/neovim/neovim/files/14008623/keymaps.lua.zip)

I know nothing about the underlying code, but I note in a [comment](https://github.com/neovim/neovim/issues/23719#issuecomment-1557098635) on #23719 @clason referred to `-V1` resulting in increased stack tracing. It seems possible the stack trace in my case stopped 1 step prematurely.

I have not tested other `verbose` commands on my system.

### Steps to reproduce

Follow steps described in 'Problem' above.

### Expected behavior

For the "Last set" message to give the correct file path and line number.

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

No lua

### Operating system/version

Debian 6.5.13-1 (2023-11-29)

### Terminal name/version

alacritty 0.12.2

### $TERM environment variable

screen-256color

### Installation

appimage

**Comment by dnebauer** [comment]
I may have explained myself poorly. The `verbose map` command in my example did _not_ show me where the `<Esc>` mapping was set with a `vim.keymap.set` function call. It instead showed me a completely different file where the `vim.keymap.set` function was wrapped in another function. I'm not a developer, just a user, but I don't see how that could possibly be correct behaviour.

If this somehow _is_ correct behaviour, perhaps you could provide a short explanation of why that is the case. That way,  any future users wondering why nvim is directing them to files where their mapping is _not_ set, and who find this issue, can undestand why.

**Comment by zeertzjq** [comment]
If the function is wrapped then the only actual `vim.keymap.set` is inside the wrapper function. I don't see how there can possibly be some other correct behavior.

**Comment by dnebauer** [comment]
Clearly I'm missing something blindingly obvious here. I'll try one last time to put my view. When I issue the command `verbose map <Esc>` I expect to be given the file and line where the last mapping for `<Esc>` is defined, that is, where I can find a `vim.keymap.set` command for which `<Esc>` is the lhs -- which in this example is the `keymaps.lua` file I uploaded. What the command actually gave me was an entirely different file (the `utils.lua` file I uploaded) where a function named `safe_keymap_set` is defined, and gives me the line number inside that function where `vim.keymap.set` is called with the parameters passed to the `safe_keymap_set` function. In fact, if I run `verbose map` for _any_ of the mappings defined in the `keymaps.lua` file the "Last set" locations are _all_ the same line in the same `utils.lua` file. There is no way for me to know from the `utils.lua` file which file and line the actual mapping is defined in. When using `verbose map` in classic vim it always took me to the `map` command which defined the mapping, which is the expected behaviour that did not happen here.

I appreciate your suggestion of a workaround using `nvim_set_keymap`. In this case, however, all the files I'm referring to are part of the folke/lazyvim plugin so that is not an option.

If I'm still missing something obvious feel free to ignore this message and hopefully the answer will come into focus for me at some point.

**Comment by clason** [comment]
The trace is performed _by Nvim core_, as far as that is concerned, the option was set by the `vim.keymap.set` command, and that is called inside the utility function. It's not a general purpose Lua debugger than can trace through user code -- and even if it could, where would you know to stop? The utility function? The function calling the utility function? Nvim itself while starting up?
