### ISSUE TITLE
BufWinEnter not called for floating window buffer

### ISSUE THREAD

**Issue by stevearc** [neovim/neovim#27121]
### Problem

When opening a floating window with `nvim_open_win` and `enter = false`, the `BufWinEnter` autocmd is not called for the buffer.

### Steps to reproduce

Here is a minimal repro
```lua
local bufnr = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_lines(bufnr, 0, 1, false, { "Waiting..." })

vim.api.nvim_create_autocmd("BufWinEnter", {
	desc = "Aerial render symbols after buffer loads in window",
	buffer = bufnr,
	once = true,
	callback = function(params)
		vim.api.nvim_buf_set_lines(params.buf, 0, 1, false, { "BufWinEnter called" })
	end,
})

vim.api.nvim_open_win(bufnr, false, {
	relative = "editor",
	row = 2,
	col = 2,
	width = 40,
	height = 20,
	style = "minimal",
})
```
Sourcing this file on nightly produces a floating window that says "Waiting...". Sourcing it in 0.9.x produces a floating window that says "BufWinEnter called". BufWinEnter _is_ called if we pass `enter = true` in `nvim_open_win`. This also does not appear to occur with splits.

### Expected behavior

BufWinEnter should be called when the buffer is first displayed in the floating window

### Neovim version (nvim -v)

v0.10.0-dev-2143+g3f188bc53

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 22.04

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

tmux-256color

### Installation

build from source

**Comment by zeertzjq** [comment]
This seems to be the reverse of #15300

**Comment by justinmk** [comment]
> When opening a floating window with `nvim_open_win` and `enter = false`, the `BufWinEnter` autocmd is not called for the buffer.

If `enter = false` why would you expect `BufWinEnter` to fire?

**Comment by zeertzjq** [comment]
Hmm, the current behavior is inconsistent with `nvim_win_set_buf`

**Comment by stevearc** [comment]
> If enter = false why would you expect BufWinEnter to fire?

I would expect `BufEnter` to not fire, since we're not entering the buffer, but from `:help BufWinEnter`:

```
BufWinEnter			After a buffer is displayed in a window.  This
				may be when the buffer is loaded (after
				processing modelines) or when a hidden buffer
				is displayed (and is no longer hidden).
```

That to me sounds like it should fire even if the window doesn't have focus. Another way to put it: I would expect there to be an invariant that if a buffer is displayed in a window, `BufWinEnter` has been dispatched.

**Comment by glepnir** [comment]
there use `enter` as condition so when it's false . `BufWinEnter` not fired in `win_set_buf`, maybe can trigger it under `win_set_buf`

https://github.com/neovim/neovim/blob/1233ac467de7504b277425988ef9be7f8d3a9626/src/nvim/api/win_config.c#L202-L203

**Comment by asmodeus812** [comment]
@justinmk Not sure if related, but on the contrary, if we create the hover window, and `set focused = false`, `vim.fn.win_gettype()` still returns "popup", if we call it right after the hover is opened. even though the focus stays on the main window, and does not enter the hover (this happens with pretty much all popup windows)
