### ISSUE TITLE
clipboard=unnamedplus without X pastes but throws annoying error

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#2712]
Called put on a remote machine without X (but xsel is installed), and since `set clipboard=unnamedplus` was in my settings I got this error message

![download1](https://cloud.githubusercontent.com/assets/715238/7723942/dd2efdea-fee4-11e4-8f80-bf8a997fbb02.png)

The paste itself worked as expected - and I'm not too surprised there was an error message, but having to press enter there is quite annoying.  The first echo comes from clipboard.vim, the error from `get_clipboard()` in ops.c.

**Suggestion:** remove the echo in clipboard.vim and return the error instead of '', and in `get_clipboard()` use the provider result in the message.

In contrast yank also echos a message but no error

![download1](https://cloud.githubusercontent.com/assets/715238/7724154/e9bc732e-fee6-11e4-9dd1-48f883ce04a7.png)

**Comment by fwalch** [comment]
Could maybe be included in #2703?

**Comment by bfredl** [comment]
I think we need a sentinel value that means "provider failed, use builtin register instead".

**Comment by bfredl** [comment]
I added fix to #2703
