### ISSUE TITLE
Terminal emulator should respect cursor shape configured in shell

### ISSUE THREAD

**Issue by gmankab** [neovim/neovim#27146]
### Problem

how to reproduce:

1. open fish shell in neovim terminal emulator
2. run this:
```shell
fish_vi_key_bindings
set fish_cursor_default block
set fish_cursor_insert line
set fish_cursor_replace_one underscore
set fish_cursor_visual block
```

neovim terminal emulator will not respect this settings and will always render the coursor as block

### Expected behavior

other terminal emulators will render coursor as line in input mode and as block in insert mode, please make neovim terminal emulator behave same way

**Comment by ysftaha** [comment]
see #3681

**Comment by gmankab** [comment]
ok, it's a duplicate

**Comment by zeertzjq** [comment]
Actually it can still count as a duplicate.
