### ISSUE TITLE
`vim.treesitter.inspect_tree()` produces an invalid CST for rust macros

### ISSUE THREAD

**Issue by mkatychev** [neovim/neovim#27159]
### Problem

calling `:lua vim.treesitter.inspect_tree()` with neovim `0.9.5` on the rust code below produces a parse error inside the `macro_invocation` node of the document CST.

#### `lib.rs`:
```rust
fn main() {
    println!("ok");
}
```

---

neovim `0.9.5` `vim.treesitter.inspect_tree()` output:

```scm
(function_item) ; [1:1 - 3:1]
 name: (identifier) ; [1:4 - 7]
 parameters: (parameters) ; [1:8 - 9]
 body: (block) ; [1:11 - 3:1]
  (expression_statement) ; [2:5 - 19]
   (macro_invocation) ; [2:5 - 18]
    macro: (identifier) ; [2:5 - 11]
    (token_tree) ; [2:13 - 18]
     (ERROR) ; [2:13 - 18]
      (unit_expression) ; [2:13 - 18]
     (string_literal) ; [2:14 - 17]
```

---

https://github.com/neovim/neovim/blob/8744ee8783a8597f9fce4a573ae05aca2f412120/cmake.deps/CMakeLists.txt#L199
Using the same version of tree-sitter that was built with neovim `0.9.5` produces a valid CST:
```
$ tree-sitter --version
tree-sitter 0.20.8
```
`tree-sitter parse ./lib.rs` output:
```scm
(source_file [0, 0] - [3, 0]
  (function_item [0, 0] - [2, 1]
    name: (identifier [0, 3] - [0, 7])
    parameters: (parameters [0, 7] - [0, 9])
    body: (block [0, 10] - [2, 1]
      (expression_statement [1, 4] - [1, 19]
        (macro_invocation [1, 4] - [1, 18]
          macro: (identifier [1, 4] - [1, 11])
          (token_tree [1, 12] - [1, 18]
            (string_literal [1, 13] - [1, 17])))))))
```

---

* The parse error is reproducible with neovim `0.9` onward
* Said error manifests in both `:lua vim.treesitter.inspect_tree()`  and `:TSPlayground`
* neovim `0.8.3` produces a fully valid CST of the rust code above (using the same `minimal.lua`).

related issue: https://github.com/nvim-treesitter/nvim-treesitter/issues/5958

---

#### `minimal.lua`:
```lua
for name, url in pairs{
  nvim_treesitter = "https://github.com/nvim-treesitter/nvim-treesitter",
  playground = "https://github.com/nvim-treesitter/playground"
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end
```

1. `nvim --clean -u minimal.lua`
2. `:TSInstall rust`
3.  `:edit ./lib.rs`
4. `:lua vim.treesitter.inspect_tree()` (or `:TSPlayground` for neovim `0.8.3`)

### Expected behavior

The expected behaviour can be found by calling `:TSPlayground` with neovim `0.8.3`:

```
$ nvim_0.8.3/nvim --version

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@Mac-1675344370646.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

```scm
function_item [0, 0] - [2, 1]
  name: identifier [0, 3] - [0, 7]
  parameters: parameters [0, 7] - [0, 9]
  body: block [0, 10] - [2, 1]
    expression_statement [1, 4] - [1, 19]
      macro_invocation [1, 4] - [1, 18]
        macro: identifier [1, 4] - [1, 11]
        token_tree [1, 12] - [1, 18]
          string_literal [1, 13] - [1, 17]
```

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

tree sitter not supported in Vim

### Operating system/version

macos 14.2.1

### Terminal name/version

tmux

### $TERM environment variable

tmux-256color-italic

### Installation

https://github.com/neovim/neovim/releases/tag/v0.9.5

**Comment by lucario387** [comment]
The above errors no matter what, tree-sitter, tree-sitter-rust, helix, or any version of neovim

The minimal test file for rust should be something of
```rust
fn main() {
  println!("{}", returns_string_hello());
}
```

Additionally, the issue is on nvim-treesitter's side for not following upstream queries. Not neovim

**Comment by mkatychev** [comment]
The above rust code does not error using `tree-sitter` 0.20.8 on macOS

**Comment by lucario387** [comment]
> The above rust code does not error using `tree-sitter` 0.20.8 using [tree-sitter/tree-sitter-rust@e0e8b6d](https://github.com/tree-sitter/tree-sitter-rust/commit/e0e8b6de6e4aa354749c794f5f36a906dcccda74) (on macOS), instead it produces the tree below:

You may not know,  but the parsed tree of `tree-sitter` CLI does not account for injections, which is what causing the `(ERROR)` node

**Comment by lucario387** [comment]
Here is the parsed result of `:InspectTree` if I were to disable all injections
```
(function_item ; [1:1 - 4:1]
  name: (identifier) ; [1:4 - 7]
  parameters: (parameters) ; [1:8 - 9]
  body: (block ; [1:11 - 4:1]
    (expression_statement ; [2:3 - 17]
      (macro_invocation ; [2:3 - 16]
        macro: (identifier) ; [2:3 - 9]
        (token_tree ; [2:11 - 16]
          (string_literal)))) ; [2:12 - 15]
```

**Comment by mkatychev** [comment]
resolved by https://github.com/nvim-treesitter/nvim-treesitter/commit/41128a7724ec40a33ce01b133aec1e9928ca4312

thanks for the turnaround @lucario387!
Glad I was initially right! https://github.com/nvim-treesitter/nvim-treesitter/issues/5958#issuecomment-1905243017

Would be helpful if `:InspectTree` returned `ERROR` nodes with data to see the source of the issue since nvim-treesitter overlaps queries from different sources:
```
(function_item) ; [1:1 - 3:1]
 name: (identifier) ; [1:4 - 7]
 parameters: (parameters) ; [1:8 - 9]
 body: (block) ; [1:11 - 3:1]
  (expression_statement) ; [2:5 - 19]
   (macro_invocation) ; [2:5 - 18]
    macro: (identifier) ; [2:5 - 11]
    (token_tree) ; [2:13 - 18]
     (ERROR: injection.scm) ; [2:13 - 18]
      (unit_expression) ; [2:13 - 18]
     (string_literal) ; [2:14 - 17]
```

**Comment by mkatychev** [comment]
resolved by https://github.com/nvim-treesitter/nvim-treesitter/commit/41128a7724ec40a33ce01b133aec1e9928ca4312

thanks for the turnaround @lucario387!
Glad I was initially right! https://github.com/nvim-treesitter/nvim-treesitter/issues/5958#issuecomment-1905243017

Would be helpful if `:InspectTree` returned `ERROR` nodes with data to see the source of the issue since nvim-treesitter overlaps queries from different sources:
```
(function_item) ; [1:1 - 3:1]
 name: (identifier) ; [1:4 - 7]
 parameters: (parameters) ; [1:8 - 9]
 body: (block) ; [1:11 - 3:1]
  (expression_statement) ; [2:5 - 19]
   (macro_invocation) ; [2:5 - 18]
    macro: (identifier) ; [2:5 - 11]
    (token_tree) ; [2:13 - 18]
     (ERROR: injection.scm) ; [2:13 - 18]
      (unit_expression) ; [2:13 - 18]
     (string_literal) ; [2:14 - 17]
```
