### ISSUE TITLE
`LanguageTree:register_cbs { on_changedtree }` reports a lot of false changes for injected languages

### ISSUE THREAD

**Issue by Danielkonge** [neovim/neovim#27155]
### Problem

I closed my earlier issue #27150, since it seems the main problem was not as described there. I think I have narrowed down the issue further now.

The problem is that injected languages report a lot of false changes, when I make changes in the parent language (or even just when I scroll).

To reliably reproduce this, an easy way is to look at a large Lua file with a lot of LuaLS annotations. (I used https://github.com/HiPhish/rainbow-delimiters.nvim/blob/master/lua/rainbow-delimiters/strategy/global.lua, which you can save as `tmp2.lua` and try to edit scroll down to (via <C-d>) line 172 and edit some text under the `on_changedtree` line.

### Steps to reproduce

Make a file called `tmp.lua` with the following:
```lua
-- Install package manager
--    https://github.com/folke/lazy.nvim
--    `:help lazy.nvim.txt` for more info
local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  }
end
vim.opt.rtp:prepend(lazypath)

vim.opt.number = true

require('lazy').setup({
  {
    -- Highlight, edit, and navigate code
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
  },
})

require('nvim-treesitter.configs').setup {
  -- Add languages to be installed here that you want installed for treesitter
  ensure_installed = {
    'lua',
    'luadoc',
  },
}

---@param parser LanguageTree
local function print_helper(parser)
	parser:register_cbs({
		on_changedtree = function(changes, _tree)
			vim.print({parser:lang(), changes})
		end,
		on_child_added = function(child)
			print_helper(child)
		end,
	})
end

---@param parser LanguageTree
---@param thunk fun(p: LanguageTree)
local function for_each_child(parser, thunk)
	thunk(parser)
	local children = parser:children()
	for _, child in pairs(children) do
		for_each_child(child, thunk)
	end
end

local buf_group = vim.api.nvim_create_augroup('MyBufEnter', { clear = true })
vim.api.nvim_create_autocmd("BufEnter", {
  group = buf_group,
  pattern = "*",
  callback = function()
		local parser = vim.treesitter.get_parser()
		for_each_child(parser, print_helper)
  end
})
```

Then do:
`nvim --clean tmp.lua`
`:so<CR>`
`:e tmp2.lua` (or another similar file)

Scroll down via `<C-d>` a few times and write `:messages<CR>`. Note that we get:

<img width="412" alt="Screenshot 2024-01-23 at 17 22 15" src="https://github.com/neovim/neovim/assets/7075380/8661c0eb-df61-434f-a00c-5602815d9deb">

Try to edit some text (without touching comment lines), and note that we get something like:

<img width="409" alt="Screenshot 2024-01-23 at 17 23 37" src="https://github.com/neovim/neovim/assets/7075380/87b34c97-42f2-4178-931e-0e241e03fd41">

### Expected behavior

Don't report changes in the injected language so often, when no changes are happening.

### Neovim version (nvim -v)

0.10.0 commit d994600

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 14.2.1

### Terminal name/version

wezterm

### $TERM environment variable

wezterm

### Installation

build from repo

**Comment by Danielkonge** [comment]
> Does the repo really require tree-sitter-context? (It certainly doesn't require nvim-treesitter.)

No, I thought that might be part of the problem earlier in my debugging, but it doesn't affect this. I have removed it.

**Comment by lucario387** [comment]
I mean, as injections are now handled by whatever is shown on the screen, it makes sense that when an injection goes out of the viewport and new ones are added, the tree is now changed.

**Comment by lewis6991** [comment]
Atm each edit removes all injections.

This is really just an issue with the invalidation logic in the languagetree, which we are already aware of.

**Comment by Danielkonge** [comment]
> Atm each edit removes all injections.

That sounds like a lot of extra work for small code edits (especially since they can register multiple times while writing a short piece of code). Is this a problem with tree-sitter in neovim or more general?

> This is really just an issue with the invalidation logic in the languagetree, which we are already aware of.

Good to know, that you are aware of the issue. Should I close this as a duplicate of some other issue? Or is this the only neovim issue tracking this problem for now?

**Comment by lewis6991** [comment]
> That sounds like a lot of extra work for small code edits (especially since they can register multiple times while writing a short piece of code). Is this a problem with tree-sitter in neovim or more general?

With `runtime/lua/vim/treesitter/languagetree.lua`.

Every text edit will cause the buffer to be reparsed, and then injections will be applied for the visible line range. Every `luadoc` line is a separate injection.

I suggest you use `LuaLS` semantic tokens over the `luadoc` parser.

**Comment by clason** [comment]
Comment parsers are an antipattern (although I understand the argument for language-independent comment highlighting, this would really be better served by a -- treesitter-powered -- plugin that just applies regex-based highlights), especially since for languages without block comments, we need to inject in every comment line individually.

**Comment by clason** [comment]
In any case, this is not a real issue (there's no "false changes", just eager re-parsings that possibly could be avoided), so I'm closing this issue. (The _real_ issue -- performance with many small injections -- is a more general "treesitter performance issue" that is already on our docket.)

**Comment by Danielkonge** [comment]
> In any case, this is not a real issue (there's no "false changes", just eager re-parsings that possibly could be avoided), so I'm closing this issue. 

That's fine with me. I just hope that we can get less eager re-parsing at some point.

> (The _real_ issue -- performance with many small injections -- is a more general "treesitter performance issue" that is already on our docket.)

Is there already an issue or pull request I can watch for changes on this?

**Comment by clason** [comment]
> That's fine with me. I just hope that we can get less eager re-parsing at some point.

Everyone likes free performance...

> Is there already an issue or pull request I can watch for changes on this?

https://github.com/neovim/neovim/issues/22426
