### ISSUE TITLE
[Ubuntu PPA] LuaJIT support not enabled on ARM builds

### ISSUE THREAD

**Issue by awilkins** [neovim/neovim#27162]
### Problem

One for @fwalch 

AFAIK LuaJIT works on ARM (as of [2.1](https://luajit.org/status.html)) - there are `arm64` packages of LuaJIT 2.1 ( Lua 5.1) or both current LTS releases (focal 20.04 and jammy 22.04).

The PPA (nightly) build script turns off LuaJIT for ARM.

```
# Force Lua on architectures where Luajit doesn't work
ifneq (,$(filter arm64,$(shell dpkg-architecture -qDEB_HOST_ARCH 2>/dev/null)))
  CMAKE_EXTRA_FLAGS += -DPREFER_LUA=ON
else
  CMAKE_EXTRA_FLAGS += -DPREFER_LUA=OFF
endif
```

Just manually built on my Pi4 (ARM 8) and it reports LuaJIT support, and LazyVim (which checks and demands LuaJIT) works fine.

Any chance of updating the PPA build scripts so they support ARM on LuaJIT 2.1?

### Steps to reproduce

- Install nvim nightly on your Pi4 running Ubuntu 22.04
- `nvim -V1 -v | grep 'LuaJIT.*'` returns nothing

### Expected behavior

```
$ nvim -V1 -v | grep LuaJIT.*
LuaJIT 2.1.1705947465
```

### Neovim version (nvim -v)

nightly PPA

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 22.04 (arm64)

### Terminal name/version

kitty (but running byobu remotely via ssh)

### $TERM environment variable

screen-256color

### Installation

Ubuntu PPA (unstable)

**Comment by clason** [comment]
We don't maintain the distro builds.

**Comment by zeertzjq** [comment]
PPA issues don't belong to this repository.
