### ISSUE TITLE
Add compatibility for musl / non-glibc distro on released binary.

### ISSUE THREAD

**Issue by lidgnulinux** [neovim/neovim#27168]
### Problem

Couple day ago I tried to download and used the [released binary](https://github.com/neovim/neovim/releases/tag/v0.9.5) on alpine linux. I faced errors when I tried to run it.

```
Error relocating /home/lidg/cmp/nvim/nvim-linux64/bin/nvim: _nl_msg_cat_cntr: symbol not found
```
and when I checked it using ldd, I got :

```
	/lib64/ld-linux-x86-64.so.2 (0x7f6a61504000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f6a61504000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f6a61504000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f6a61504000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f6a61504000)
	libgcc_s.so.1 => /usr/lib//libgcc_s.so.1 (0x7f6a614e0000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f6a61504000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f6a614d9000)
	libutil.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f6a61504000)
Error relocating ./bin/nvim: backtrace: symbol not found
Error relocating ./bin/nvim: gnu_get_libc_version: symbol not found
Error relocating ./bin/nvim: __strncpy_chk: symbol not found
Error relocating ./bin/nvim: __fprintf_chk: symbol not found
Error relocating ./bin/nvim: __printf_chk: symbol not found
Error relocating ./bin/nvim: __register_atfork: symbol not found
Error relocating ./bin/nvim: __memcpy_chk: symbol not found
Error relocating ./bin/nvim: __vsnprintf_chk: symbol not found
Error relocating ./bin/nvim: __strcat_chk: symbol not found
Error relocating ./bin/nvim: __vfprintf_chk: symbol not found
Error relocating ./bin/nvim: __strcpy_chk: symbol not found
Error relocating ./bin/nvim: __memset_chk: symbol not found
Error relocating ./bin/nvim: __fread_chk: symbol not found
Error relocating ./bin/nvim: __cmsg_nxthdr: symbol not found
Error relocating ./bin/nvim: gnu_dev_makedev: symbol not found
Error relocating ./bin/nvim: __sprintf_chk: symbol not found
Error relocating ./bin/nvim: __snprintf_chk: symbol not found
Error relocating ./bin/nvim: __memmove_chk: symbol not found
Error relocating ./bin/nvim: _nl_msg_cat_cntr: symbol not found
```

My random guess is the problem is caused by musl compatibility (alpine's using musl). I use the same binary on slackware and works fine. Would be nice if the released binary will be compatible with musl. Thanks.

### Expected behavior

The released binary has compatibility on distro which using musl instead of gcc (e.g. alpine linux).

**Comment by lidgnulinux** [comment]
Note : Alpine linux indeed has neovim package but downloading and using released binary will be more portable.

**Comment by clason** [comment]
Every different platform must be maintained and tested, so this would add stress to an already thinly-stretched team. Can _you_ provide automation to create such a release? If so, you are welcome to contribute it to https://github.com/neovim/neovim-releases. Otherwise I'm afraid this won't happen.

**Comment by lidgnulinux** [comment]
```
Can you provide automation to create such a release?
```
Alpine linux has apkbuild file to build neovim, I don't know if that will work, I will try.

```
If so, you are welcome to contribute it to https://github.com/neovim/neovim-releases.
```
Sure , I will try.

**Comment by clason** [comment]
If there is already a packaged release from a distro, we're not interested in duplicating that work, though.

**Comment by lidgnulinux** [comment]
Create neovim appimage for musl-based distro.
https://gist.github.com/lidgnulinux/3cab5819353d710c933d4551f1ff8fe2
