### ISSUE TITLE
Command Mode

### ISSUE THREAD

**Issue by zwk5131** [neovim/neovim#27160]
### Problem

Hello 
I run into a problem....
When I try to enter command mode from normal mode with a key binding it's not working...
Here the example:
keymap("n", "eee", "<ESC>:<cr>", opts)

Also not working from other modes...
keymap("i", "eee", "<ESC>:<cr>", opts)

Same happens when trying from visual mode... etc...

### Steps to reproduce

vim.api.nvim_set_keymap("n", "eee", "<ESC>:<cr>", opts)

### Expected behavior

Enter Command Mode

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Ubuntu LTS 22.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim

**Comment by wookayin** [comment]
> Usage or "How to" questions belong on the [stackoverflow](https://vi.stackexchange.com/) and will be closed.

Read :mapmode-c
