### ISSUE TITLE
use nvim-treesitter's formatter as the default formatexpr for query files

### ISSUE THREAD

**Issue by T-727** [neovim/neovim#27175]
### Problem

All queries that ship with Neovim have been formatted using [nvim-treesitter's query formatter](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/scripts/format-queries.lua) in https://github.com/neovim/neovim/commit/f5dc45310941dff6efc02d955fc0c110190e9b85.
Assuming this is the format that core approves of, it would be nice to push/help users to use this format when writing their own queries by having it as the default formatter for query files.

### Expected behavior

Transform [nvim-treesitter's query formatter](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/scripts/format-queries.lua) into a `formatexpr` and apply it in [`ftplugin/query.lua`](https://github.com/neovim/neovim/tree/master/runtime/ftplugin/query.lua)

**Comment by clason** [comment]
That's not possible since the query formatter cannot work on ranges.

**Comment by clason** [comment]
(And queries should be provided to nvim-treesitter first, anyway, which already ships the formatter. If you don't want to run this as an external tool, just define a user command that runs this on the current buffer and reloads.)

**Comment by T-727** [comment]
> That's not possible since the query formatter cannot work on ranges.

Hence the "Transform into a `formatexpr`" part, I assumed it would be possible with some changes, and maybe a fun contribution


> If you don't want to run this as an external tool, just define a user command that runs this on the current buffer and reloads.

That is possible yeah, but I don't think it defeats the point of this issue


> queries should be provided to nvim-treesitter first, anyway, which already ships the formatter. 

I'm talking about query files in general, whether it be for personal use, plugin development or whatever.
I believe a good and endorsed formatter would be nice to have by default for any query.
Plus we already have indenting and linting; formatting seems like the final missing piece :)

**Comment by clason** [comment]
> Hence the "Transform into a formatexpr" part, I assumed it would be possible with some changes, and maybe a fun contribution

Not to this repo, though. If there _is_ a standalone formatter that is suitable for a `formatexpr`, I'd be the first to clamor for upstreaming it.

Until then, you can test https://github.com/lucario387/nvim-ts-format (which is not ready for upstreaming).
