### ISSUE TITLE
Providing an Alternative Color Scheme File for Pre-Update Look

### ISSUE THREAD

**Issue by huangyingw** [neovim/neovim#27183]
### Problem

The recent changes to the default color scheme introduced in commit 64a14026d76ba1798d91e15a941fcb6af7cbc5ad by Evgeni Chasnovski have altered the look and feel of Neovim in ways that don't align with my preference and prior workflow. I have made significant efforts to find a color scheme from the current runtime/colors/*.vim options that would provide a similar experience to the pre-update scheme, but none have fulfilled my requirements. I understand the need for progress and the issues with reverting commits, so I am seeking a solution that doesn't involve rolling back the changes.

### Expected behavior

I propose the introduction or endorsement of a color scheme file that replicates the pre-update default colors, which users could place in their runtime/colors/ directory. This would allow those of us who prefer the old color scheme to continue enjoying Neovim without impacting those who favor the new defaults. I am looking for guidance or a contribution from the Neovim team or the community, including those who were involved in the update, to create such a color scheme file.

An official color scheme file that mirrors the old defaults would be a greatly appreciated addition, providing a seamless transition for users attached to the previous aesthetic without hindering the evolution of Neovim.

Thank you for considering this enhancement.

**Comment by huangyingw** [comment]
I used git bisect to find this commit in question.
I showed the diff on src/nvim/highlight_group.c to ChatGPT, and asked it to generate a color.vim for me, based on this change and old version of highlight_group.c.
But chatgpt failed to do this, so, sorry, I have to ask here.

**Comment by clason** [comment]
:h news

**Comment by huangyingw** [comment]
> :h news
> 
> (Why do you assume such a thing is not provided?)
Then how to do?
I have tried all of files like: runtime/colors/*.vim, none of them is the same like pre-update.
I will try again.

**Comment by huangyingw** [comment]
Then how to do?
I have tried all of files like: runtime/colors/*.vim, none of them is the same like pre-update.
I will try again. @clason

**Comment by clason** [comment]
sigh.

`:colorscheme vim`

**Comment by huangyingw** [comment]
the first one is build with the commit in question, plus colorscheme vim
![467B1FE5-D0E0-475D-932A-C06D5259BACD](https://github.com/neovim/neovim/assets/91757/a15c7b68-de4b-421a-a49f-26e1fa018af9)

the second one is build the parent of the commit in question(), without colorscheme vim.
![BC02E726-F6B1-4147-89DF-8C4E07889DB6](https://github.com/neovim/neovim/assets/91757/d16bcd59-a102-4dd3-976c-380580cc2410)



as you could see, the color schema of the status line is different, 
I did try to make them exactly the same, but failed.

yesterday, I did also see the difference in cursor line,  I didn't see the underline in cursor line. But today I could not repro this.

**Comment by zeertzjq** [comment]
Please use the latest commit.

**Comment by huangyingw** [comment]
this one is with the latest code:
![576EFC64-8CB7-4E7E-B4CA-89882BC5449B](https://github.com/neovim/neovim/assets/91757/685f6c46-5683-4724-8353-962958cd4625)

still difference in the status line color shema

**Comment by huangyingw** [comment]
I just found the turning point:
before running ":colorscheme vim", the status line is light blue, as I like.
after running "colorscheme vim", the status line turned into white.

**Comment by huangyingw** [comment]
the first time launch, the status line is light blue, 
I ran ":colorscheme", it will print default, and the bg of status line is still light blue.
ran ":colorscheme default", with the same default value, but the bg of status line would become grey
hope this informatio is useful for you to debug.

**Comment by zeertzjq** [comment]
There is no bug. You should run `colorscheme vim` whatever changes status line to blue or run Nvim with `nvim --cmd 'colorscheme vim'`

**Comment by huangyingw** [comment]
no.
`colorscheme vim` changes status line to grey

**Comment by justinmk** [comment]
Are you comparing `nvim --clean` in both cases?

**Comment by huangyingw** [comment]
build with the latest commit in master, and 
launch with `nvim --clean /root/loadrc/efficient_file_scanner/main.go`
I got 
<img width="2560" alt="Screenshot 2024-01-28 at 9 59 33 PM" src="https://github.com/neovim/neovim/assets/91757/8f53eed4-cd53-4ee5-8891-eacf7c49305c">

after `:colorscheme vim`
<img width="2560" alt="Screenshot 2024-01-28 at 10 03 40 PM" src="https://github.com/neovim/neovim/assets/91757/c00bb85c-c59a-4a01-963a-fafde1fff7c6">

still issue with status line and cursor line.

**Comment by justinmk** [comment]
> still issue with status line and cursor line.

statusline looks the same in those screenshots.
