### ISSUE TITLE
Treesitter performance in cpp: editing with treesitter highlightning is noticably slow

### ISSUE THREAD

**Issue by kaddkaka** [neovim/neovim#27184]
### Problem

Editing cpp files can be remarkably slower when Treesitter highlighting is enabled.

There seems to a lot of invocation to on_bytes, and a lot of calls to tree:edit because all trees have their `tree:edit` method called, is this necessary? For notice: I'm rather new to neovim/treesitter development.

### Steps to reproduce

Have a cpp file with this content:
```cpp
#define A 0
```
repeated for 2 lines (`tmp_2.cpp`) or 10 000 lines (`tmp_10000.cpp`).

Configuration file with only treesitter and nvim-profiler enabled:
```vim
call plug#begin(stdpath('data') . '/treesitter_plugged')
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'https://github.com/wookayin/nvim-profiler'
call plug#end()

lua require('nvim-treesitter.configs').setup { highlight = {enable=true}}
```

## Scenario 1.
Visually select all 10k lines and perform `<c-a>` to increment the number on each line, notice the significant delay until the command completes.

When profiled from the command line with hyperfine we can see the different in time with treesitter highlight enabled/disabled.

- Treesitter enabled: `239.3 ms`
- Treesitter disabled: `25.8 ms`

### Details treesitter enabled
```console
$ VIMRUNTIME=./runtime hyperfine --ignore-failure 'build/bin/nvim -u ~/.config/nvim/treesitter.vim ~/tmp_10000.cpp -c"normal! V10000j^A" -c"cq"'
Benchmark 1: build/bin/nvim -u ~/.config/nvim/treesitter.vim ~/tmp.cpp -c"normal! V10000j" -c"cq"
  Time (mean ± σ):     258.8 ms ±  15.1 ms    [User: 230.9 ms, System: 17.1 ms]
  Range (min … max):   239.3 ms … 274.4 ms    10 runs
  ```

### Details treesitter disabled:
```console
$ VIMRUNTIME=./runtime hyperfine --ignore-failure 'build/bin/nvim -u ~/.config/nvim/treesitter.vim ~/tmp.cpp -c"normal! V10000j^A" -c"cq"'
Benchmark 1: build/bin/nvim -u ~/.config/nvim/treesitter.vim ~/tmp.cpp -c"normal! V10000j^A" -c"cq"
  Time (mean ± σ):      34.0 ms ±  10.2 ms    [User: 25.6 ms, System: 7.7 ms]
  Range (min … max):    25.8 ms …  59.4 ms    49 runs
  ```

When profiled with `:LuaProfile run 3000` the top of the log says:
```
  181  ./runtime/lua/vim/treesitter/languagetree.lua:908
  <-   180  ./runtime/lua/vim/treesitter/languagetree.lua:947 < ./runtime/lua/vim/treesitter/languagetree.lua:1005 < ./runtime/lua/vim/treesitter.lua:67
  <-     1  ./runtime/lua/vim/treesitter/languagetree.lua:1005 < ./runtime/lua/vim/treesitter.lua:67
```

Looking at the code at line 908, we see:
```lua       
  print("#self._trees", #self._trees)       " < -- this print is inserted by me
  for _, tree in pairs(self._trees) do
    tree:edit(                                              " <--- this is line 908
      start_byte,
      end_byte_old,
      end_byte_new,
      start_row,
      start_col,
      end_row_old,
      end_col_old,
      end_row_new,
      end_col_new
    )
  end
```
  which is called after invoking on_bytes due to an edit (according to `runtime/doc/api.txt:2111`.

## Scenario 2.
Putting some prints in the runtime lua code to instrument number of calls being done and for loop iterations. Then run this
1. open `tmp_10000.cpp`
1. Modify window/textsize to only show 10 lines of code
1. Visually select the first two lines
1. Press  `<ctrl-a>` (only the first two lines are changed, no other line is actually modified or editted)

Output:
```
1
#self._trees 1
#self._trees 11
2
#self._trees 1
#self._trees 11
3
#self._trees 1
#self._trees 11
4
#self._trees 1
#self._trees 11
```

Strangeness:
- Why are there 4 calls and not 2 to `function LanguageTree:_on_bytes()`?
- For each call, all trees visible in the window(?) + 1(why?), is iterated over. Is this necessary when actually onlt the first two lines changed?

The `:InspectTree` output for the `tmp_2.cpp` file looks like this:
```
(preproc_def ; [1:1 - 2:0]
  name: (identifier) ; [1:9 - 9]
  value: (preproc_arg ; [1:11 - 11]
    (ERROR ; [1:11 - 11]
      (number_literal)))) ; [1:11 - 11]
(preproc_def ; [2:1 - 3:0]
  name: (identifier) ; [2:9 - 9]
  value: (preproc_arg ; [2:11 - 11]
    (ERROR ; [2:11 - 11]
      (number_literal)))) ; [2:11 - 11]
```

### Expected behavior

Treesitter should not add much delay to simple editing commands.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2186+gb280d57db

### Vim (not Nvim) behaves the same?

no, related to treesitter

### Operating system/version

Ubuntu 22.04

### Terminal name/version

Wezterm

### $TERM environment variable

xterm-256color

### Installation

RelWithDebInfo build from repo

**Comment by clason** [comment]
Duplicate. Please search open (and closed) issues first.

**Comment by clason** [comment]
(TL;DR: Edits invalidate all injections. Files with many injections -- comments, macros -- have known performance issues. Disable injections for such files as a workaround.)

**Comment by wookayin** [comment]
To provide more explanation: this should be another instance of #27155 (tracked in #22426;  Injection queries are run too often -- Currently we run the full injection query on every edit to a buffer)

Note that "C preprocessors" are made of injections:

```
((preproc_arg) @injection.content
  (#set! injection.language "c"))
```
