### ISSUE TITLE
Replace validation tests in help_spec with separate linter job

### ISSUE THREAD

**Issue by clason** [neovim/neovim#27192]
### Problem

There are several content validations for help files (allowed spellings, valid taglinks, dead URLs, treesitter parsing errors) that are run in as part of the `functionaltest` target (in `test/functional/lua/help_spec.lua`, to be precise).

This is both unnecessary and confusing:
1. it delays what should be very quick feedback;
2. it runs unnecessarily on all platforms;
3. it muddles the CI feedback ("why are functionaltests failing again? I only fixed a typo in the docs!")
4. these checks do not test actual editor functionality (instead just use it for other purposes), so don't actually use the testing harness (in fact, a straight-up `nvim -l` shebang script would be simpler).

(It's also not exactly intuitive that the help file validation function is part of the HTML generator script, but here there's at least the code reuse argument.)

### Expected behavior

Move these checks from the functionaltest target into a separate linting job ("validate help files").

**Comment by justinmk** [comment]
> these checks do not test actual editor functionality (instead just use it for other purposes), so don't actually use the testing harness (in fact, a straight-up `nvim -l` shebang script would be simpler).

OTOH, it seems suboptimal that each lint check has to reinvent script args. I was thinking we may want to move many of the lint checks from `scripts/` into a new `test/lint/` test suite. That allows the lint checks to reuse various testutils and conventions. Thoughts?

**Comment by justinmk** [comment]
Fixed by #27227
