### ISSUE TITLE
Make command fails if path to neovim contains spaces

### ISSUE THREAD

**Issue by PappasBrent** [neovim/neovim#27203]
### Problem

If I clone neovim into a directory with spaces in its path and try to build it with `make`, I receive an error.
For example, if I clone neovim to  `"/home/bpappas/directory name with spaces/"` and run `make`, I receive the following output:
```
~/directory name with spaces/neovim (master)$ make
cmake -S /home/bpappas/ ./ ./ spaces/neovim//cmake.deps -B .deps -G 'Ninja' \
	  
CMake Warning:
  Ignoring extra path from command line:

   "/home/bpappas"


CMake Warning:
  Ignoring extra path from command line:

   "spaces/neovim//cmake.deps"


-- Found GNU Make at /usr/bin/gmake
-- CMAKE_INSTALL_PREFIX=/usr/local
-- CMAKE_BUILD_TYPE=Debug
CMake Error at CMakeLists.txt:188 (message):
  Failed to find a Lua 5.1-compatible interpreter


-- Configuring incomplete, errors occurred!
make: *** [Makefile:95: build/.ran-deps-cmake] Error 1
```

### Steps to reproduce

Create a directory with spaces in the name 
```console
mkdir "directory name with spaces"
```
2. Navigate into that directory
```console
cd "directory name with spaces"/
```
3. Download the latest neovim source
```console
git clone https://github.com/neovim/neovim.git
```
4. Try to build neovim
```console
make
```

The installation instructions say to run `make CMAKE_BUILD_TYPE=Debug` to build neovim, however I run into this issue regardless of the build type I choose (`Release;Debug;MinSizeRel;RelWithDebInfo`), or if I leave the build type out entirely.

### Expected behavior

I expect to be able to build neovim in directories whose paths contain spaces.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2200+g6116495e6, commit 6116495e6e6d3508eb99720faad7e55ba7cbe978

### Vim (not Nvim) behaves the same?

No. I can build vim in a directory whose path has spaces in it. VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan 25 2024 20:28:14)

### Operating system/version

Ubuntu 22.04.3 LTS x86_64

### Terminal name/version

# GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

Build from repo

**Comment by justinmk** [comment]
This is a `make` limitation. The Makefile is just a convenience, so it doesn't really matter. https://github.com/neovim/neovim/issues/4621#issuecomment-560069355

> Neovim is a CMake project, it doesn't depend on `make`. You can use `ninja` or any other generator...
> * ..._unless_ you are also building the "bundled" dependencies. In that case, the workaround is to not build "bundled" dependencies. Nothing we can do about the build systems in third-party projects.
