### ISSUE TITLE
When editing a Markdown file, finding next matching item (`%`) fails in one particular case

### ISSUE THREAD

**Issue by TinusgragLin** [neovim/neovim#27230]
### Problem

I just discovered that when editing a Markdown file, if a `matchpair` starts right after a `<` and the cursor is on the left item of the `matchpair`, `%` fails:
```
 when the cursor is here, % won't move the cursor to the matching item
 |
<()
<(asdasdasdadas  ) >
<[]
<{}
```

### Steps to reproduce

```
nvim --clean whatever.md
```
and type something like `<()`, put the cursor on the left part of the pair right after the `<` and try to use `%`.

I was able to reproduce it both on my Ubuntu server (using nvim 0.10.0 dev) and my Arch home machine (using nvim 0.9.5).

### Expected behavior

`%` brings me to the matching item.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2210+g38bb0e1da

### Vim behaviors

Vim 9.1 on my home machine and Vim 8.2 on my server do **not** have this issue.
`vim --version` in my home machine:
```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan 02 2024 18:36:25)
Compiled by Arch Linux
...
```
`vim --version` in my server:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 05 2023 17:58:57)
Included patches: 1-579, 1969, 580-1848, 4975, 5016, 5023, 5072, 2068, 1849-1854, 1857, 1855-1857, 1331, 1858, 1858-1859, 1873, 1860-1969, 1992, 1970-1992, 2010, 1993-2068, 2106, 2069-2106, 2108, 2107-2109, 2109-
3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919, 213, 1840, 1846-1847, 2110-2112, 2121
```

### Operating system/version

Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

appimage

**Comment by clason** [comment]
Does this happen with `nvim --clean`?

**Comment by clason** [comment]
If Vim behaves the same, that is an issue with the `matchit` plugin -- which we don't maintain. You should contact the maintainer listed at the top of the file.

**Comment by TinusgragLin** [comment]
Wait, vim does not behave the same, and does it correctly! I am so sorry, I thought the vim part of the issue template was "whether vim is doing things correctly"!

**Comment by clason** [comment]
Can you re-add this (important!) information (making explicit that Vim does _not_ behave the same)?

@seandewar could this be related to `scriptversion`?

**Comment by seandewar** [comment]
Same happens in Vim if you enable the matchit plugin , which is enabled by default in Nvim (but not in Vim).

**Comment by TinusgragLin** [comment]
Thanks for the information!
