### ISSUE TITLE
treesitter: noisy "Invalid node type" error

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#27235]
### Problem

"Invalid node type" error is constantly raised, preventing use of the editor.

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ./runtime/lua/vim/treesitter/query.lua:248: Query error at 51:3. Invalid node type "note":
((note) @comment.note
  ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ./runtime/lua/vim/treesitter/query.lua:248: in function 'fn'
        ./runtime/lua/vim/func/_memoize.lua:54: in function 'fn'
        ./runtime/lua/vim/func/_memoize.lua:54: in function 'get'
        ./runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ./runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
        ./runtime/lua/vim/treesitter/highlighter.lua:187: in function 'fn'
        ./runtime/lua/vim/treesitter/languagetree.lua:489: in function 'for_each_tree'
        ./runtime/lua/vim/treesitter/highlighter.lua:174: in function 'prepare_highlight_states'
        ./runtime/lua/vim/treesitter/highlighter.lua:351: in function <./runtime/lua/vim/treesitter/highlighter.lua:345>
```

### Steps to reproduce

1. Place an old vimdoc.so parser (which does _not_ ([define](https://github.com/neovim/tree-sitter-vimdoc/commit/4f8ba9e39c8b3fbaf0bb5f70ac255474a9099359) `(note)`)) at `~/.config/nvim/parser/vimdoc.so` so that it will load when treesitter parses a `:help` file.
2. Open a vimdoc buffer: `:help lua`.
3. The error occurs continually (can't dismiss it, it reappears).
    - `runtime/queries/vimdoc/highlights.scm` references `note`: https://github.com/neovim/neovim/blob/2cd76a758b4511748d9482e5af58162a608516b4/runtime/queries/vimdoc/highlights.scm#L51-L52
    - but the "old" parser from step (1) does not have `note`.

### Expected behavior

- Error for the _same_ parser/node pair, should only be reported _once_. For example in this case, `Invalid node type "note"` should be reported at most once, for the `vimdoc` parser.
- Error should mention the parser _file location_. It wasn't obvious that I had a `~/.config/nvim/parser/` that was overriding the builtin parser.
- `vim.treesitter.get_parser()` should return the parser file location.

### Neovim version (nvim -v)

2cd76a758b45

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS

### Terminal name/version

kitty

### $TERM environment variable

tmux-256color

### Installation

source

**Comment by clason** [comment]
The issue here is that this is happening in the ephemeral decoration provider, which means there are limits to the sort of state you can save. (There's been _very_ heated discussions about proper error handling in the decorator before, triggered by the same issue...)

But sure, better error messages are always a good idea. And _maybe_ we can have proper parser introspection in the next tree-sitter version that would allow catching mismatches _before_ errors are thrown. (A boy can dream...)

Needless to say, this is an issue we've been keenly aware of but currently lack the tools to handle.

**Comment by justinmk** [comment]
> `vim.treesitter.get_parser()` should return the parser file location.

This at least would be a fairly cheap improvement? Or is it already available somewhere I missed?

**Comment by clason** [comment]
> This at least would be a fairly cheap improvement?

As it already has a return value, that requires thought to make things not break everywhere else. (`get_parser()` is only the top of a rather deep stack of functions, with the actual loading etc. being done in C.)

**Comment by clason** [comment]
And for the record: 

> The error occurs continually (can't dismiss it, it reappears).

`<ctrl-c>` followed directly by `:lua vim.treesitter.stop()` works. not a workaround, of course, but at least gets you back to a responsive editor.

**Comment by bfredl** [comment]
It's already supposed to go away after you press enter three times:

```

  if (ERROR_SET(&err)) {
    decor_provider_error(provider, name, err.msg);
    provider->error_count++;

    if (provider->error_count >= DP_MAX_ERROR) {  // DP_MAX_ERROR == 3
      provider->state = kDecorProviderDisabled;
    }
  }
```

If this somehow broke, it is a bug.

**Comment by clason** [comment]
Yes, that broke. Enter does nothing.

**Comment by lewis6991** [comment]
I think it may be because:

```c
  if (!ERROR_SET(&err)
      && api_object_to_bool(ret, "provider %s retval", default_true, &err)) {
    provider->error_count = 0;
    return true;
  }
```

Which means the provider is only disabled if 3 callbacks in a row fail. I think this won't work for `on_win` failing, since it will do something like.

```
->start
->buf
->win (fail)
->end (resets error count)
```

**Comment by clason** [comment]
Is there any scenario where we expect a transient failure that _should_ not disable the provider? If so, how likely is that? (I feel like the current retry-approach is optimizing for the wrong path...)

**Comment by lewis6991** [comment]
The initial goal of the `error_count` thing was do temper down the `line` callback failures, the other callbacks weren't considered.

We could change it so `error_count` is never reset? Or only reset if the whole cycle didn't error?

**Comment by bfredl** [comment]
IMO the `error_count` thing in C should be a last resort thing which _always_ disables the provider, no matter which specific callbacks contributes to the error. it is then up to the specific provider to handle more fine-grained fallbacks (like disabling only a specific query, all highlights for a specific buffer, or whatever makes sense that depends on actual TS semantics).

**Comment by lewis6991** [comment]
So never reset?

**Comment by noghartt** [comment]
Any update on that error? Having a similar error message:

```
Invalid node type "function_expression"
```

**Comment by TarunDaCoder** [comment]
> Invalid node type "function_expression"

Yes, I am also facing this error with an HTML file.

**Comment by clason** [comment]
No, that's something else.

**Comment by justinmk** [comment]
>  Error should mention the parser _file location_. It wasn't obvious that I had a `~/.config/nvim/parser/` that was overriding the builtin parser.
>  `vim.treesitter.get_parser()` should return the parser file location.

Those improvements are still pending, but https://github.com/neovim/neovim/pull/31418 at least fixes the error flooding.
