### ISSUE TITLE
"E475: Invalid arguments: exactly one of {chunk} or {range} required" with TS incremental selection

### ISSUE THREAD

**Issue by MariaSolOs** [neovim/neovim#27234]
### Problem

When building `master`, an error message saying "E475: Invalid arguments: exactly one of {chunk} or {range} required" appears when using [`nvim-treesitter`'s incremental selection](https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#incremental-selection).

### Steps to reproduce

1. Create the following minimal configuration in `minimal.lua`:
```lua
-- Install nvim-treesitter.
local install_path = vim.fn.fnamemodify('nvim_issue/nvim-treesitter', ':p')
if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/nvim-treesitter/nvim-treesitter', install_path }
end
vim.opt.runtimepath:append(install_path)

-- Configure incremental selection.
require('nvim-treesitter.configs').setup {
    incremental_selection = {
        enable = true,
        keymaps = {
            init_selection = '<cr>',
            node_incremental = '<cr>',
            node_decremental = '<bs>',
        },
    },
}
```
2. Open Neovim with `nvim --clean -u minimal.lua minimal.lua`. Try to use the above keybindings inside the incremental selection configuration (they should expand to include the entire `setup` table, the entire file etc).
3. Notice the error message and how the selection isn't expanded or narrowed.

### Expected behavior

For incremental behavior to work as expected with no errors.

### Neovim version (nvim -v)

v0.10.0-dev-2216+g2cd76a758

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

wezterm 20240127-113634-bbcac864

### $TERM environment variable

wezterm

### Installation

Build from source

**Comment by clason** [comment]
Hmm... Can you extract a self-contained minimal example from this?

(Thst function is a dead module walking, so if this is due to incorrect assumptions there, good riddance...)

**Comment by luukvbaal** [comment]
I can reproduce but I'm not sure why `exarg_T->addr_count > 0` here when executing the mapping.
My assumption was that it would be 0 unless a range is supplied. If that is wrong we need a different condition for the ranged :lua.

**Comment by luukvbaal** [comment]
Doesn't look like the two cases can be distinguished from `exarg_T` only, so I guess we need to go further up the callstack...

**Comment by MariaSolOs** [comment]
@clason I updated the repro steps :)

**Comment by luukvbaal** [comment]
Okay nvm the mapping actually provides a {range} and {chunk}. This fixes or at least avoids the issue:

```diff
--- a/lua/nvim-treesitter/incremental_selection.lua
+++ b/lua/nvim-treesitter/incremental_selection.lua
@@ -148,7 +148,7 @@ function M.attach(bufnr)
         mode = "x"
         -- We need to move to command mode to access marks '< (visual area start) and '> (visual area end) which are not
         -- properly accessible in visual mode.
-        rhs = string.format(":lua require'nvim-treesitter.incremental_selection'.%s()<CR>", funcname)
+        rhs = string.format("<cmd>lua require'nvim-treesitter.incremental_selection'.%s()<CR>", funcname)
       end
       vim.keymap.set(
         mode,
```

I suppose the error is correct.

**Comment by MariaSolOs** [comment]
@luukvbaal I've had this configuration for a very long time though, so this looks like a recent change.

**Comment by luukvbaal** [comment]
It is (https://github.com/neovim/neovim/pull/27167), but I'm not sure we can/should do anything about it here.

**Comment by MariaSolOs** [comment]
> It is (#27167), but I'm not sure we can/should do anything about it here. Supplying both {range} and {chunk} to :lua is now an error (and previously {range} was ignored). nvim-treesitter can fix this with the above patch.

Sounds good. I was not suggesting we reverted anything, I was just curious to understand what caused the regression :)

**Comment by zeertzjq** [comment]
I think it actually needs a `<C-U>` after the `:`.

However, I now realized that this restriction caused some inconvenience, as typed `:lua` commands (e.g. typing `:lua vim.lsp.buf.format()`) now requires typing an extra `<C-U>` key, and I've been doing that a lot :)

**Comment by luukvbaal** [comment]
Yep, I guess :{range}lua wasn't as free real estate as assumed.  Though I don't think this is really actionable beyond documenting/mentioning in news.txt? We want :{range}lua to execute the range and return early, not executing the {chunk}. If it is considered too big of an inconvenience it (should have) be(en) a separate command?

**Comment by MariaSolOs** [comment]
So the specific TS incremental selection issue was fixed in https://github.com/nvim-treesitter/nvim-treesitter/pull/6014. I'm fine with closing this one, but it looks that there's a larger discussion going on. Wdy @clason @luukvbaal @zeertzjq?

**Comment by zeertzjq** [comment]
It seems that `:source` also ignores `[range]` when `[file]` is specified, so still allowing `[range]` for `:lua {chuck}` actually does make sense, and so does #7177.
