### ISSUE TITLE
Incorrect Cursor and Status Line Color in macOS with Latest Neovim Build

### ISSUE THREAD

**Issue by huangyingw** [neovim/neovim#27238]
### Problem

When using the latest Neovim build on macOS, I encounter problems with the 'colorscheme vim'. There are two main issues:

The cursor line is not visible. Instead of the expected cursor line, there is only a gray thick line on the active line.
The status line color is gray, which deviates from the expected default light blue color.
These issues are not present on the Ubuntu system, and did not exist in the Neovim codebase prior to the commit 64a14026d76ba1798d91e15a941fcb6af7cbc5ad.

### Steps to reproduce

Compile the latest Neovim code on macOS.
Set the colorscheme to vim.
Observe the cursor line and status line colors.

### Expected behavior

The cursor line should be clearly visible in the active line, and the status line should display in the default light blue color, as it does on other systems and in previous commits.
![0E6A8D53-6F71-4C6A-A61A-8A216BD5063F](https://github.com/neovim/neovim/assets/91757/50346271-d4aa-42ec-b95d-907e6a83eac7)

### Neovim version (nvim -v)

commit: 2cd76a758b4511748d9482e5af58162a608516b4

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macos 14.3

### Terminal name/version

iterm

### $TERM environment variable

xterm-256

### Installation

build from repo

**Comment by wookayin** [comment]
Check:
```
:verbose hi CursorLine
:verbose hi StatusLine
```

Can you please show screenshots before/after the commit 64a1402? to compare both? With `nvim --clean` and `:colorscheme vim` applied.

**Comment by huangyingw** [comment]
```
:verbose hi Cursor
Cursor         xxx cleared
        Last set from Lua
```

```
:verbose hi CursorLine
CursorLine     xxx cterm=underline guibg=Grey40
        Last set from Lua
```

```
:verbose hi StatusLine
StatusLine     xxx cterm=bold,reverse gui=bold,reverse
        Last set from Lua
```

screen shot before 64a14026d76ba1798d91e15a941fcb6af7cbc5ad
<img width="2560" alt="Screenshot 2024-01-27 at 5 36 32 PM" src="https://github.com/neovim/neovim/assets/91757/2d2489e2-2374-4d86-bda8-dd274cecd405">

**Comment by seandewar** [comment]
Start Nvim with `nvim -V1` and run the commands again.

**Comment by seandewar** [comment]
What happens if you try `set notgc`?

**Comment by wookayin** [comment]
Launching `nvim -V1` will make `:verbose hi Cursor` tell where exactly it was set, not from `Last set from Lua`. Are you sure you did use `nvim --clean`?

**Comment by seandewar** [comment]
Those definitions look like they're from `colors/vim.lua`, though `nvim -V1` would be nice to confirm.

My hunch is that this is a result of the `termguicolors` detection added in https://github.com/neovim/neovim/commit/2613ba5000d4c0d9b15e2eec2d2b97615575925e, not the new default color scheme.  Previously it looks like `termguicolors` was not enabled, especially given the underlined CursorLine... :thinking:

**Comment by huangyingw** [comment]
used this command to launch nvim:
```
nvim -V1 --clean -c "colorscheme vim"
```

this screenshot was taken after `:set notgc`
![8C574716-9B82-4244-BAC4-3559DAE0171F](https://github.com/neovim/neovim/assets/91757/15a3ce16-b07f-4870-83fa-0d476037e2f8)

output of the suggested commands:

```
:verbose hi Cursor
Cursor         xxx cleared
        Last set from Lua

:verbose hi CursorLine
CursorLine     xxx cterm=underline guibg=Grey40
        Last set from Lua

:verbose hi StatusLine
StatusLine     xxx cterm=bold,reverse gui=bold,reverse
        Last set from Lua

```

let me know if you need more info

**Comment by seandewar** [comment]
Thanks. It does look like to me that you had `notgc` before, but because you used `--clean` this time, things look different compared to your other screenshots.

Can you please run Nvim _without_ `--clean` and show us what `:set notgc` looks like? Also provide the output of this command: `:echo nvim_eval_statusline(&stl,#{highlights:1}).highlights`.

**Comment by huangyingw** [comment]
ok, this time, I ran `nvim -V1 -c "colorscheme vim" ~/loadrc/neovim/scripts/git-log-pretty-since.sh`

screenshot before `:set notgc`
<img width="2560" alt="Screenshot 2024-01-28 at 4 34 25 PM" src="https://github.com/neovim/neovim/assets/91757/2635cac1-105c-48ef-b5da-e977ec941b4d">

screenshot after `:set notgc`
<img width="2560" alt="Screenshot 2024-01-28 at 4 35 19 PM" src="https://github.com/neovim/neovim/assets/91757/ea08a484-61d5-4f9c-9fc0-21e4fd6fb60b">

so, at least, notgc help with the cursor line.
output of `echo nvim_eval_statusline(&stl,#{highlights:1}).highlights `
```
[{'group': 'StatusLine', 'start': 0}]
```

**Comment by justinmk** [comment]
is `xterm-256` really your TERM or did you mean `xterm-256color` ?

**Comment by huangyingw** [comment]
if I echo from nvim's terminal, I got
```
(base) ➜  neovim git:(colorscheme) echo $TERM
xterm-256color
```

if echo from command line, I got
```
(base) ➜  ~ echo $TERM
screen-256color
```
I am in macos 14.3

**Comment by clason** [comment]
> if echo from command line, I got

That's your problem, then. Your issue doesn't indicate that you're using `screen`, so this value is incorrect and most likely the cause for any issues you're seeing.

**Comment by huangyingw** [comment]
update: 

I am using iTerm, newly open a tab, and I got
```
(base) ➜  ~ echo $TERM

xterm-256color
```

run from a tmux window, I got:

```
/usr/local/bin/tmux
(base) ➜  ~ echo $TERM

screen-256color
```
99.99% of time, I am using tmux, so, I need to change the $TERM value in tmux?

**Comment by wookayin** [comment]
>  so, I need to change the $TERM value in tmux?

You can do:
```diff
-set-option -g default-terminal "screen-256color"
+set-option -g default-terminal "$TERM"
```

**Comment by gpanders** [comment]
> > so, I need to change the $TERM value in tmux?
> 
> You can do:
> 
> ```diff
> -set-option -g default-terminal "screen-256color"
> +set-option -g default-terminal "$TERM"
> ```

No, don't do this. You should only set `default-terminal` to `tmux-256color` (or `screen-256color` if using an ancient system).

**Comment by gpanders** [comment]
The "problem" with the cursor line is indeed that `'termguicolors'` is enabled by default. 

The screenshot in https://github.com/neovim/neovim/issues/27238#issuecomment-1913403064 looks sus, it is clearly a non-default statusline while the other screenshots show the default statusline. The statusline in the screenshot also shows the gray background on the left side. What do you have `'statusline'` set to?

**Comment by huangyingw** [comment]
after setting $TERM and launch nvim
```
(base) ➜  ~ echo $TERM
tmux-256color
(base) ➜  ~ nvim -V1 --clean -c "colorscheme vim" ~/loadrc/neovim/scripts/git-log-pretty-since.sh
```
I got this screen:
<img width="2560" alt="Screenshot 2024-01-29 at 4 21 56 PM" src="https://github.com/neovim/neovim/assets/91757/3c7906ba-4f48-454c-a2ec-bab49c261d8b">

and after `set notgc`, I got
<img width="2560" alt="Screenshot 2024-01-29 at 4 23 32 PM" src="https://github.com/neovim/neovim/assets/91757/7e824a00-b0e8-44ee-9683-f9398f6f92e3">

this time, cursor line mal-function again.

and here is my status line
```
:verbose hi StatusLine
StatusLine     xxx cterm=bold,reverse gui=bold,reverse
        Last set from Lua
```

**Comment by seandewar** [comment]
To be clear, the StatusLine being white is expected behaviour (it shouldn't have been blue) and the reason there's no CursorLine there is because you're using `--clean` (it's not enabled by default).

**Comment by huangyingw** [comment]
thanks for all these useful information.
