### ISSUE TITLE
Build failure since TS minimum version bump to 0.20.9

### ISSUE THREAD

**Issue by MadCatX** [neovim/neovim#27242]
### Problem

I'm sorry if this report comes off as a bit confusing but I'm uncertain what to make of the situation.

Neovim now calls ` ts_query_cursor_set_max_start_depth()` function which appears to have been introduced in tree-sitter 0.20.9. Neovim attempts to check the minimum version of tree-sitter but the check fails to detect whether a recent enough version of tree-sitter is actually available.

AFAICT, Neovim gets the version information from the pkg-config file `tree-sitter.pc`. The file gets generated by tree-sitter's [Makefile](https://github.com/tree-sitter/tree-sitter/blob/master/Makefile). The actual tree-sitter library version set by the Makefile is 0.20.10, a change introduced by commit [0e4ff0b](https://github.com/tree-sitter/tree-sitter/commit/0e4ff0bb27edf37b76fc7d35aa768b02cf4392ad). It seems like the versions of tree-sitter and the tree-sitter library that Neovim checks are not the same thing and Neovim fails to build with no obvious reason.

### Steps to reproduce

1) Get the latest neovim source code
2) Get the latest tree-sitter source code and revert it to the latest commit before v0.20.9 version tag
3) Attempt to build neovim against such tree-sitter

### Expected behavior

Neovim should either build or report that the available version of tree-sitter is too old. Currently, it seems that too old versions of tree-sitter are not detected as such during Neovim's configuration.

### Neovim version (nvim -v)

74e695d22715e52f5561a185583b8c23d4fa0dd6

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

Build from source

**Comment by clason** [comment]
No, this is incorrect. The minimum version is specified in our CMake build scripts, and that version is downloaded and built automatically.

In case of _any_ build errors, the first step is always `make distclean`. Please try that.

**Comment by clason** [comment]
And if tree-sitter mis-specifies its own version, that is a tree-sitter issue and should be reported there.
