### ISSUE TITLE
Virtual text makes line disappear when arabic is set

### ISSUE THREAD

**Issue by Farzat07** [neovim/neovim#27264]
### Problem

![image](https://github.com/neovim/neovim/assets/55144155/a4548e30-146f-436c-baf2-679c374af423)

These are two nvim instances in tmux. Same content, only difference is that only the bottom one has `arabic` set. As you can see, the lines which originally contain virtual text from lsp warnings no longer show.

### Steps to reproduce

1. Start an nvim instance.
2. Paste the source of [this wikipedia article](https://ar.wikipedia.org/wiki/%D8%AA%D9%85%D9%84%D9%83_%D8%A8%D8%A7%D9%84%D8%A7%D8%B3%D8%AA%D9%8A%D9%84%D8%A7%D8%A1)
3. Enter command `:set arabic`

### Expected behavior

Text now shows from right to left, but with warnings still visible.

At the very least, even if the warnings don't show, I should be able to see the original text from the line (or wrapped portion of the line).

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1702233742     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

Didn't try

### Operating system/version

Arch linux

### Terminal name/version

st-git 0.9.r11.g9846a56

### $TERM environment variable

tmux-256color

### Installation

Arch package (pacman)

**Comment by zeertzjq** [comment]
Can you try nightly version?

**Comment by mike325** [comment]
I can confirm virtual text works in the nightly using `vim.diagnostics`, at least with Latin characters

non-arabic
![image](https://github.com/neovim/neovim/assets/4576770/34eed974-e02e-421e-bba6-c8031da6e83d)

arabic
![image](https://github.com/neovim/neovim/assets/4576770/dceaa4ac-9a1c-4cae-89ec-8982d6c91424)

**Comment by zeertzjq** [comment]
Closing as this is likely already fixed.

**Comment by Farzat07** [comment]
> Can you try nightly version?

Sorry I missed that.

I tried the master branch actually, and it worked, so I guess yeah it is already fixed :)
