### ISSUE TITLE
search pattern bug

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#2726]
This was introduced recently, haven't bisected yet.

Given this text, with cursor at (0,0):

```
foo bar
foo bar
foo bar
```

`\c\V\zsoo\%>1v\%<207v` does *not* match any lines. It should match all `oo` strings. However, these patterns *do* match correctly:

```
`\c\V\zsoo\%>2v\%<207v`
`\c\V\zsoo\%>3v\%<207v`
```

It seems the regex engine is using *at-column* logic instead of *greater-than-column* logic.

Latest gvim and old vim 7.3. do not have this problem.

**Comment by Shougo** [comment]
Yes, it is fixed in Vim 7.4.582.
