### ISSUE TITLE
`%` gets removed using the `J` action

### ISSUE THREAD

**Issue by lmaotrigine** [neovim/neovim#27260]
### Problem

Firstly, I apologize in advance if this is a duplicate. I can barely word it properly myself. I searched as best I could using the search bar and didn't find anything similar. If I missed something, please link the original and I'll be happy to close this.

Basically, the problem is, when I have a line beginning with `%`, and I try to join it to the previous one (using `J`), the initial `%` vanishes. This does not occur on the latest release of vim. I'm running version 0.9.5 of Neovim, built from source. I can provide logs if required, but I don't know if they're pertinent.

### Steps to reproduce

consider a text file that looks like this:
```text
%123
%456
```
Open this file in Neovim, with the cursor on line 1, column 1. Do a `J`. The file ends up like so:
```text
%123 456
```

### Expected behavior

Following the above steps should produce a result like so:
```text
%123 %456
```

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 05 2023 17:58:57)

### Operating system/version

Ubuntu 22.04.3

### Terminal name/version

Konsole 21.12.3

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by clason** [comment]
Please test a current version of Vim (9.1.xxxx).

**Comment by lmaotrigine** [comment]
I did test with `nvim --clean`.

I can also see the correct behaviour in vim 9.1.0061 (also built from source, with nothing special)

`:set fo?` shows `jtcroql`, correlating with the table, I don't see anything that might cause this either
`:set fo-=jtcroql` has no effect on this.

**Comment by clason** [comment]
You do know that these options are filetype-dependent? Can you show exact reproducing steps? (I get different `fo` for Vim and Neovim with `--clean`, for the record.)

**Comment by clason** [comment]
`:h vim-differences`

**Comment by lmaotrigine** [comment]
exact repro steps:
- `nvim --clean`
- `i`
- ```
%foo
%bar
```
- `<ESC> 0 k`
- `J`

since this is literally an empty buffer, does file type have any bearing?

> you can only subtract one flag at a time
ah, that's my bad. sorry.

> I get different fo for vim and nvim --clean
yeah, so do I, nvim adds `j`...

and.. you're right. that *is* the difference.

it seems to consider `%` as a comment character, even in plain text files.

this is exactly what happens in vim too. i shall close this as resolved. thank you for your time.
