### ISSUE TITLE
Built-in way to change the cursor behavior on leaving `insert` mode

### ISSUE THREAD

**Issue by BatmanAoD** [neovim/neovim#2727]
There are some people (including me) who feel that the behavior of the cursor upon leaving `insert` mode is counter-intuitive; it jumps to the character to the *left* of the final position of the insertion pointer, rather than to the character to the *right.*

There are some hints for trying to fix and/or work around this on the Vim wiki: http://vim.wikia.com/wiki/Prevent_escape_from_moving_the_cursor_one_character_to_the_left

...but as shown from the comments there, none of these solutions is quite correct (for instance, leaving `insert` mode using `<C-C>` won't call the `autocmd` from the "programmatic" solution).

Is it possible to add a built-in option for NeoVim that would allow some control over this behavior?

**Comment by justinmk** [comment]
autocmd InsertLeave * call feedkeys(' ', 'n')

> leaving insert mode using <C-C> won't call the autocmd from the "programmatic" solution

Right, ctrl-c is not a valid way to leave insert mode, unless you want it to cancel everything, including this preference.

**Comment by justinmk** [comment]
Actually, this tip from the wiki is even better (my tip above doesn't work in `virtualmode=all` if the cursor is in "free space"):

    inoremap <silent> <Esc> <Esc>`^

None of the other crap in the wiki tip is needed in Neovim. It's perfectly fine to map `<esc>` in Neovim, even in the terminal.
