### ISSUE TITLE
`:[horizontal|below|vertical|above] [terminal|checkhealth|` doesnt behave properly on even a `--clean` boot of neovim

### ISSUE THREAD

**Issue by ana-rchy** [neovim/neovim#27279]
### Problem

whenever i try to run for example `:below term`, or any variation of it, it ends up replacing the whole window rather than being a seperate window below. `:[v]split | term` does work, so its weird why the others wouldnt

on regular vim, this issue doesnt exist and the commands function as intended

### Steps to reproduce

nvim --clean
:below term

### Expected behavior

terminal window opens in split window below

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

no, 9.1

### Operating system/version

arch linux, 6.7.2-arch1-1

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

pacman

**Comment by wookayin** [comment]
This is already fixed in #15427 #26714 #26731. Please test on latest neovim nightly.

**Comment by ana-rchy** [comment]
> This is already fixed in #15427 #26714 #26731. Please test on latest neovim nightly.

works on nightly, so ig i just gotta use that until the next stable release
