### ISSUE TITLE
`Ctrl-^` behaves unintuitively when deleting buffers

### ISSUE THREAD

**Issue by Maltimore** [neovim/neovim#27285]
### Problem

This issue is similar to https://github.com/neovim/neovim/issues/25365, but for the `alternate-file`.

It often happens that when deleting a buffer (with `:bd`), say `file1`, that buffer is just unlisted and "invisibly" stays the `alternate-file` for another buffer `file2`. When `file2` is active, pressing `Ctrl-^` will make neovim attempt to re-open `file1`.

Problems:
- some buffers can't be reloaded
- typically, a buffer was deleted for a reason, so it's unlikely that someone would use the `Ctrl-^` command with the intention to reload that buffer (although in certain scenarios this could be a valid use case)

If instead one doesn't just delete the buffer, but wipes it with `:bw`, then doing `Ctrl-^` as above, one gets the error "E23: No alternate file".

### Expected behavior

I believe that for the vast majority of use-cases, it would be practical that when deleting/wiping a buffer, another buffer predictably becomes the alternate buffer. The most obvious candidate would be closest other listed buffer in the jumplist.

**Comment by glepnir** [comment]
please use issue template with all informations that we need. thanks.

**Comment by Maltimore** [comment]
I did use the issue template for "Feature request". This isn't a bug report, as I don't think there's a bug. Just for clarification, do you want me to make a bug report issue?

**Comment by glepnir** [comment]
sound like a bug 🤔
