### ISSUE TITLE
Colors behave differently when opening file at startup vs ":edit" with a light-themed terminal

### ISSUE THREAD

**Issue by yourcelf** [neovim/neovim#27292]
### Problem

With `colorscheme vim`, I get different color results when editing a file at startup using `nvim <file>` than I do when opening nvim first and editing the file using `:edit <file>`.  This behavior only happens for some file types ((it happens with python files, for example, but not php):

### Bad colors:
```
nvim --clean --cmd "colorscheme vim" manage.py
```
![image](https://github.com/neovim/neovim/assets/21318/8dce0ab2-6e52-4fc8-a50a-02bd9d82ccef)

### Good colors:
```
nvim --clean --cmd "colorscheme vim"
:edit manage.py
```
![image](https://github.com/neovim/neovim/assets/21318/f3426063-4135-4eea-a393-f24900a2d36c)

Once started with "bad colors" (e.g. editing a file directly from the command line), I haven't found any way to return to "good colors", other than exiting nvim and starting up again without specifying a file to edit from the command line.

This behavior started in an unstable release from about a week ago.  It only seems to happen when using a "light" colorscheme in my terminal -- dark colorschemes still seem to get consistent colors however I open the file to edit.

### Steps to reproduce

Using a terminal that has a light colorscheme, edit a python file.  Note differences in colorscheme between how the file is opened.
```
nvim --clean --cmd "colorscheme vim" file.py
```
vs
```
nvim --clean --cmd "colorscheme vim"
:edit file.py
```

### Expected behavior

I expect the colors to behave in the way I see when starting nvim without a file, then opening it with `:edit file.py`.

### Neovim version (nvim -v)

v0.10.0-dev

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 22.04.3

### Terminal name/version

terminator 2.1.1-1

### $TERM environment variable

xterm-256color

### Installation

neovim-ppa-ubuntu-unstable

**Comment by zeertzjq** [comment]
The following change fixes this issue:
```diff
diff --git a/runtime/lua/vim/_system.lua b/runtime/lua/vim/_system.lua
index efad3f88c..ee794c44d 100644
--- a/runtime/lua/vim/_system.lua
+++ b/runtime/lua/vim/_system.lua
@@ -94,7 +94,7 @@ function SystemObj:wait(timeout)
 
   local done = vim.wait(timeout or state.timeout or MAX_TIMEOUT, function()
     return state.result ~= nil
-  end)
+  end, nil, true)
 
   if not done then
     -- Send sigkill since this cannot be caught
```

**Comment by lewis6991** [comment]
How does vim.system affect this?

**Comment by zeertzjq** [comment]
The `BufReadPost` autocommand loads Python ftplugin, which loads Python provider, which calls `SystemObj:wait()`, which processes `nvim_ui_term_event`, which tries to trigger `TermResponse`, but the `BufReadPost` didn't allow nested autocommands.
