### ISSUE TITLE
Folding with treesitter no longer working

### ISSUE THREAD

**Issue by jacobrreed** [neovim/neovim#27309]
### Problem

Folding used to work with treesitter, and I was using `vim.opt.foldexpr = "nvim_treesitter#foldexpr()"` but this no longer works, I tried moving to the newer `"v.lua.vim.treesitter.foldexpr()"` which still doesn't work. When i load a file that has treesitter parser installed and attached and i press `zc` to close fold under cursor I get `E409: No fold found`. If i press `zx` to refresh then press `zc` I get no errors anymore but I don't get folding either. No form of folding is working now.
I have also tried setting foldmethod to indent, and using an autocmd:
```
-- Use treesitter based folding if the current buffer has a parser
vim.api.nvim_create_autocmd("FileType", {
  group = vim.api.nvim_create_augroup("treesitter-fold", { clear = true }),
  callback = function()
    if require("nvim-treesitter.parsers").get_parser() then
      vim.opt.foldmethod = "expr"
      vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
    end
  end,
})

```

still no dice.
If I remove the autocmd and just use method = indent, it still gives same error of E409 no fold found

To note: this works in lua files, but not TS files

### Steps to reproduce

```
-- Folding
vim.opt.foldlevel = 99
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.opt.foldenable = false
```

Full config: https://github.com/jacobrreed/nvim

### Expected behavior

I expect folding to work with treesitter parsers installed

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2258+g1405e5c8c

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

MacOS Sonoma 14.2.1

### Terminal name/version

Wezterm 20230712-072601-f4abf8fd

### $TERM environment variable

screen-256color

### Installation

Nightly release from github

**Comment by clason** [comment]
Please provide a minimal reproducible example for us to test with `nvim --clean -u test.lua`. Are you sure that you have fold queries for those languages installed?

**Comment by jacobrreed** [comment]
> Please provide a minimal reproducible example for us to test with `nvim --clean -u test.lua`. Are you sure that you have fold queries for those languages installed?

How do I check if fold queries are installed? I have typescript installed via nvim-treesitter :TSInstall

**Comment by clason** [comment]
`:checkhealth`

**Comment by jacobrreed** [comment]
reinstalling typescript treesitter parser seems to make folding work again, but if i have cursor over a nested object and `zc` it folds the entire parent object/function

**Comment by jacobrreed** [comment]
> `:checkhealth`

  - typescript          ✓ ✓ ✓ ✓ ✓

**Comment by jacobrreed** [comment]
https://github.com/neovim/neovim/assets/25580051/c97d3de7-bad4-4b35-971f-a8c090be3515
