### ISSUE TITLE
Suggestion: Explain linux installation in more detail in INSTALL.md

### ISSUE THREAD

**Issue by JamesC01** [neovim/neovim#27310]
### Problem

I'm really not sure where to put this, since it isn't a bug, but it also isn't a feature. Right now I feel like the INSTALL.md file doesn't explain enough about installing on linux. It doesn't really explain much outside of using the appimage, and running it by typing "./nvim.appimage", and installing it from tarball, and typing "./nvim-linux64/bin/nvim" when you want to run it.
This is not what most users want. The top of the file even mentions that to run neovim, you type "nvim." But if a user follows the installation instructions for tarball or appimage, this just won't work correctly.

When someone follows an installation guide, it should give them all they need to get the program functioning like usual, but at the moment, it leaves off a few steps needed to get the program running by typing "nvim". I've found some workarounds myself, but it's not easy to find out if you're doing something the "right" way (that's why I'm not changing INSTALL.md myself, I'm just not sure of the proper conventional way of doing this), so if it was included in the install instructions, I think it would be very helpful.

It does explain how to expose the _extracted_ appimage globally, but that is noted as an "optional" thing, and it makes it seem like you should only do this if you _can't_ already run the appimage directly.

### Expected behavior

It should explain the exact commands to install the program from tarball or appimage, and get it to run in the expected way, by typing "nvim" anywhere, instead of having to go into the folder, or typing a big long path every time you want to use the program. It should mention how to do this in the conventional way, since there's so many different ways of doing this, just going with the most typical option would be useful (I'm not sure of it.) After a quick search, it seems one convetional way is to put the main folder in /usr/opt and create a symlink from the nvim bin folder to allow starting it with just the command, but I think someone who knows better than me should write it. Maybe for debian systems, converting it to a .deb and using dpkg might be possible?

**Comment by justinmk** [comment]
If #27350 isn't enough then this is "wontfix".

**Comment by justinmk** [comment]
> When someone follows an installation guide, it should give them all they need to get the program functioning like usual, but at the moment, it leaves off a few steps needed to get the program running by typing "nvim".

Mainly because the binaries were never intended, and still aren't intended, and never will be intended, to be the primary install option. They are merely best-effort escape hatches. The primary, recommended way to install is via your system package manager or by building from source.

**Comment by justinmk** [comment]
#27350 may or may not be merged but I'm closing this anyway, for the above reason.
