### ISSUE TITLE
Terminal and split don't play nicely

### ISSUE THREAD

**Issue by frederikvs** [neovim/neovim#2732]
In certain situations, it seems that the terminal and splits don't play nicely. It looks like you're losing some lines, some stuff is muddled up,...
Unsure if this is a neovim problem, or if it comes from libvterm.

To reproduce, open neovim, open term (with a regular bash or sh), and do
```
for i in {1..30} ; do echo $i ; done
```
You screen looks something like 
```
20                                                     
21                                                   
22                                                 
23
24
25
26
27
28
29
30                                                    
sh-3.2$                                      
```

Now do a split. You get : 
```
15
16
17
18
sh-3.2$
term://.//39861:/bin/sh                                
15
16
17
18
sh-3.2$
term://.//39861:/bin/sh                
```

I would have expected 
```
27
28
29
30
sh-3.2$
term://.//39861:/bin/sh                                
27
28
29
30
sh-3.2$
term://.//39861:/bin/sh                
```

**Comment by tarruda** [comment]
Could be a libvterm problem, I can reproduce something similar in pangoterm by quickly reducing the window height. cc @leonerd

**Comment by frederikvs** [comment]
I also noticed that when I give the clear-command in bash, stuff that's currently on screen just disappears. Most terminal emulators shift that stuff to scrollback, which is also more convenient.

I don't know enough about libvterm's internals to know if this could be related or not...

Reason to suspect a possible link with this issue : this issue also involves losing everything that's currently on screen, and then drawing a new prompt...

**Comment by splinterofchaos** [comment]
#2732 fixes this, Please re-open if it's not totally fixed, yet.
