### ISSUE TITLE
Setting abbreviation for `#!!` sometimes fails for `scheme` files

### ISSUE THREAD

**Issue by jdujava** [neovim/neovim#27324]
### Problem

Setting abbreviation for `#!!` (via `:abbr #!! foo`) in cerain scenarios throws `E474: Invalid argument`.
Interestingly, it only happens (as far as I know) for `scheme` files, and only when it is under `.../queries/...` directory.

### Steps to reproduce

- Open file with the path `.../queries/foo.scm` or `.../queries/..../foo.scm` (for example I opened `nvim --clean ~.local/share/nvim/lazy/nvim-treesitter/queries/lua/highlights.scm`)
- Try to create abbreviation as `:abbr #!! foo`
- This throws error `E474: Invalid argument`
- For other filetypes it seems to work, and also for `scheme` files not under `queries` directory..

### Expected behavior

It should be possible to set abbreviation for `#!!` in general, or the exception should be documented.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2210+g38bb0e1da

### Vim (not Nvim) behaves the same?

No, in vim 9.1.0000 it is possible to set the abbreviation

### Operating system/version

Arch Linux @ kernel 6.7.2-arch1-2

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

AUR (`neovim-nightly-bin`)

**Comment by clason** [comment]
`queries/**/*.scm` are recognized as query files, with their own ftplugin -- which sets a different `iskeyword`, including `!` (inherited from Lisp, which this is a dialect of).

This makes `!` illegal; you can test with other Lisp files.

**Comment by jdujava** [comment]
@clason Thanks for the quick explanation!

**Comment by zeertzjq** [comment]
Related https://github.com/vim/vim/issues/5074
