### ISSUE TITLE
Expose default foldtext implementation

### ISSUE THREAD

**Issue by omar25h** [neovim/neovim#27320]
### Problem

Prior to #20750, it was possible to call `vim.treesitter.foldtext()` to get the current foldtext and customize the text shown. I used to have foldtext

```lua
function FoldText()
  local text = vim.treesitter.foldtext() --[[ @as string[] ]]
  local n_lines = vim.v.foldend - vim.v.foldstart
  table.insert(text, { ' 󰁂 ' .. n_lines, { 'Folded' } })
  return text
end

vim.opt.foldmethod = 'expr'
vim.opt.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
vim.opt.foldtext = 'v:lua.FoldText()'
```
 

### Expected behavior

Would it still be possible to expose the default implementation of `foldtext()` as a Lua function?

**Comment by zeertzjq** [comment]
I don't think it's possible to expose it as a function, but maybe it can be exposed as a variable.

**Comment by lewis6991** [comment]
Transparent foldtext can't be exported to Lua without a significant amount of effort.

**Comment by wookayin** [comment]
Well, I think this is a valid request (which I was also thinking about adding) nevertheless, although it would be not trivial to implement. The old `vim.treesitter.foldtext()` can't handle extmarks, etc. so exposing it as a variable, e.g., `v:foldtext` would be a good feature to have.

**Comment by lewis6991** [comment]
We don't need to keep issues open just because they are "valid" if it's not likely to ever get implemented.

We can accept a PR if someone is actually going to implement this. We can even reopen this and assign it to said person. Otherwise this is unplanned.
