### ISSUE TITLE
[flake.nix] undefined reference to `ts_query_cursor_set_max_start_depth'

### ISSUE THREAD

**Issue by grappas** [neovim/neovim#27337]
### Problem

i'm trying to build (on unstable channel) neovim using flake. Unfortunately it drops this error. Funny enough I had the same issue on Arch not a while ago (and has been fixed: https://aur.archlinux.org/packages/neovim-git).

```nix
error: builder for '/nix/store/cayl8rv127hn1s2jhawd71aw1qcl0i92-neovim-unwrapped-6c83870.drv' failed with exit code 2;
       last 10 log lines:
       > /build/srh2xb5d9qpk9hdvx6v99xa4pnb4wgjd-source/src/nvim/message.c:2112:18: warning: 'strnlen' specified bound 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overread]
       >  2112 |     size_t len = strnlen(str, (size_t)maxlen);
       >       |                  ^
       > /nix/store/fzlkaj1ax7gl655blfcr6zzvml1vx3bj-binutils-2.40/bin/ld: /build/ccjL0IvN.ltrans40.ltrans.o: in function `node_rawquery.lto_priv.0':
       > /build/srh2xb5d9qpk9hdvx6v99xa4pnb4wgjd-source/src/nvim/lua/treesitter.c:1452: undefined reference to `ts_query_cursor_set_max_start_depth'
       > /nix/store/fzlkaj1ax7gl655blfcr6zzvml1vx3bj-binutils-2.40/bin/ld: /build/srh2xb5d9qpk9hdvx6v99xa4pnb4wgjd-source/src/nvim/lua/treesitter.c:1476: undefined reference to `ts_query_cursor_set_max_start_depth'
       > collect2: error: ld returned 1 exit status
       > make[2]: *** [src/nvim/CMakeFiles/nvim_bin.dir/build.make:5150: bin/nvim] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:624: src/nvim/CMakeFiles/nvim_bin.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run 'nix log /nix/store/cayl8rv127hn1s2jhawd71aw1qcl0i92-neovim-unwrapped-6c83870.drv'.
```

### Steps to reproduce

nix run "github:neovim/neovim?dir=contrib"

### Expected behavior

Builds and runs

### Neovim version (nvim -v)

latest commit

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

NixOS unstable

### Terminal name/version

GNOME Terminal

### $TERM environment variable

xterm-256color

### Installation

Nix flake

**Comment by clason** [comment]
You need to build against the latest version of tree-sitter (0.20.9) as specified in our cmake build scripts.

**Comment by grappas** [comment]
but shouldn't flake.nix take care of that?

**Comment by clason** [comment]
Who knows; we don't maintain the flake, that's why it's under /contrib.

**Comment by hurricanehrndz** [comment]
> but shouldn't flake.nix take care of that?

No, it is the upstream neovim pkg definition in nixpkgs that defines the buildinputs and their versions. You can override flake attribute to update the buildinputs with the same version as specify cmake.deps

see here: https://github.com/hurricanehrndz/pdenv/commit/0d1fb61e6b0e3b39d49d095e85f7bedfaa6601df
