### ISSUE TITLE
Python 3 module provides +python.

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2734]
Installing only the Python 3 module (and not the Python 2 module) still causes `has('python')` to give a result of `1`. It should only return `1` for `has('python3')`.

This causes a lot of errors with YouCompleteMe on startup.

**Comment by Shougo** [comment]
> Installing only the Python 3 module (and not the Python 2 module) still causes has('python') to give a result of 1. It should only return 1 for has('python3').

Oh, it is the problem.  Thanks.
