### ISSUE TITLE
Virtual text shown on two lines after delete and undo

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#27368]
### Problem

Virtual text shown on two lines after delete and undo:

https://github.com/neovim/neovim/assets/35768171/509dc921-049b-455b-9958-5b01e69146c2

### Steps to reproduce

1. Run `nvim --clean`
2. Source the following file:
```vim
call setline(1, ['aaa', 'bbb', 'ccc', 'ddd'])
let ns = nvim_create_namespace('')
call nvim_buf_set_extmark(0, ns, 1, 0, #{virt_text: [['foo']]})
```
3. Press `j`
4. Press `dd`
5. Press `u`
6. Virtual text is shown on both line 2 and line 3

### Expected behavior

Virtual text is only shown on line 2, which is the behavior after pressing `<C-L>`

### Neovim version (nvim -v)

v0.10.0-dev-2294+gc0b99bb1de

### Vim (not Nvim) behaves the same?

N/A (deletes text property with line)

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by luukvbaal** [comment]
For spell checking, and since recently for signs as well(#27052), we redraw the line below the undo range without checking if it's actually needed. The same could be done in a buffer with virtual text.
