### ISSUE TITLE
Want to confirm that  that `b:terminal_job_id` won't be deprecated

### ISSUE THREAD

**Issue by jam1015** [neovim/neovim#27367]
### Problem

On the [deprecated page](https://neovim.io/doc/user/deprecated.html) it says that `b:terminal_job_pid` is deprecated:

```
VARIABLES
[b:terminal_job_pid](https://neovim.io/doc/user/deprecated.html#b%3Aterminal_job_pid)	PID of the top-level process in a [:terminal](https://neovim.io/doc/user/various.html#%3Aterminal). Use jobpid(&channel) instead.
```

### Expected behavior

I hope that `b:terminal_job_id` (different than `b:terminal_job_pid`) will be kept, not deprecated. It is useful because it appears in `getbufinfo()` so we can see what buffer a certain job is associated with and vice-versa, without the buffer being active, which I believe is necessary when using `&channel`.  I'm using this variable in a PR for a plugin but want to make sure it will be there in the future; or that another way of associating a buffer with a job id, and confirming that it is a terminal, will be implemented.

**Comment by justinmk** [comment]
`b:terminal_job_id` is the same thing as `&channel`

**Comment by bfredl** [comment]
>  without the buffer being active, which I believe is necessary when using &channel. 

That's just one specific syntax. try `vim.bo[bufnr].channel` in lua and `getbufvar(bufnr, '&channel')` in vim script.
