### ISSUE TITLE
Volar LSP Client quit with exit code 1

### ISSUE THREAD

**Issue by lucario387** [neovim/neovim#27381]
### Problem

Since commit 2e982f1aad9f1a03562b7a451d642f76b04c37cb, Volar LSP always exit a few seconds after attached to a Vue buffer.

### Steps to reproduce using "nvim -u minimal_init.lua"

- Do `npx create-vite@latest --template vue-ts bug-volar`
- `minimal_init.lua`:
```lua
local pattern = 'vue'
local cmd = {'vue-language-server' , '--stdio'}
-- Add files/folders here that indicate the root of a project
local root_markers = { 'package.json'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'bugged-volar',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```
- `cd bug-volar && npm i && nvim --clean -u minimal_init.lua src/App.vue`

### Expected behavior

Expect the server not to quit a few seconds after attaching and to not see the error below

```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:254: RPC[Error] code_name = InternalError, message = "Request initialize failed with message: Ca
nnot read properties of undefined (reading 'cancellationPipeName')"                                                                                                                             
stack traceback:                                                                                                                                                                                
        [C]: in function 'assert'                                                                                                                                                               
        /usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:254: in function ''                                                                                                                
        vim/_editor.lua: in function <vim/_editor.lua:0>      
```

### Neovim version (nvim -v)

commit 24d26b4cd1db3d312a6c6e9d025c0016159f99dc

### Language server name/version

Vue language server (volar) v1.8.27

### Operating system/version

Linux 6.7.4-arch1-1

**Comment by wookayin** [comment]
2e982f1aad refers to #27216. I also tried `2e982f1aad^1` (51702e0a) and `nvim-0.9.5` stable, and the bug is still reproducible, so I don't think this has something to do with #27216. This might be a bug due to the different behavior of `vue-language-server` and the LSP messages being sent between nvim and the vue LSP.

```
$ vue-language-server --version
1.8.27
```

**Comment by lucario387** [comment]
I'm testing on the commit before that and I have yet to got the issue :thinking:. Is this a binary executable issue 

I think my initial message is misleading as the issue is 2 fold:
- The LSP detached a few seconds after attaching.
- The LSP showing the error.

**Comment by sid-6581** [comment]
I'm also getting constant crashes with Volar recently. I didn't have these crashes before this week, or maybe last week. 1.8.27 has been out for a while, so it's not caused by any changes in Volar itself. I'm getting different error messages though. This is what's in my LSP log:

```
[WARN][2024-02-08 10:10:29] .../lua/vim/lsp.lua:830	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[ERROR][2024-02-08 10:10:30] .../vim/lsp/rpc.lua:31	"rpc"	"C:\\Users\\sid6581\\AppData\\Local\\nvim-data\\mason\\bin\\vue-language-server.CMD"	"stderr"	"C:\\Users\\sid6581\\AppData\\Local\\nvim-data\\mason\\packages\\vue-language-server\\node_modules\\@vue\\language-server\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:565\r\n                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));\r\n                                               ^\r\n\r\nResponseError: MethodNotFound\r\n    at handleResponse (C:\\Users\\sid6581\\AppData\\Local\\nvim-data\\mason\\packages\\vue-language-server\\node_modules\\@vue\\language-server\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:565:48)\r\n    at handleMessage (C:\\Users\\sid6581\\AppData\\Local\\nvim-data\\mason\\packages\\vue-language-server\\node_modules\\@vue\\language-server\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:345:13)\r\n    at processMessageQueue (C:\\Users\\sid6581\\AppData\\Local\\nvim-data\\mason\\packages\\vue-language-server\\node_modules\\@vue\\language-server\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:362:17)\r\n    at Immediate.<anonymous> (C:\\Users\\sid6581\\AppData\\Local\\nvim-data\\mason\\packages\\vue-language-server\\node_modules\\@vue\\language-server\\node_modules\\vscode-jsonrpc\\lib\\common\\connection.js:334:13)\r\n    at process.processImmediate (node:internal/timers:478:21) {\r\n  code: -32601,\r\n  data: undefined\r\n}\r\n\r\nNode.js v21.6.1\r\n"
```

**Comment by wookayin** [comment]
Can you try the bug is reproducible with 0.9.4? -- I think so; if that's the case Volar LSP itself is the cause of the bug. Also please try with a few other previous releases of vue-language-server.

**Comment by sid-6581** [comment]
Everything works fine for me with 0.9.5 stable. Also as I mentioned, the same version of Volar worked fine up until very recently in nightly builds.

**Comment by wookayin** [comment]
I can certainly reproduce the bug with nvim 0.9.4-stable. How did you rule out the possibility of vue-language-server changing the behavior? Which versions of Volar did you try in the past and now?

**Comment by sid-6581** [comment]
Like I said, I've used Volar 1.8.27 since the day it was released, but I only started having this issue recently. It hasn't changed since December, when it was released, so I'm not sure how it would suddenly change behavior.

I update to a new neovim nightly every day, so it seems likely that it's a neovim issue. I used all the same versions of all my plugins when testing 0.9.5, so it's not likely that it's those either.

**Comment by lucario387** [comment]
I'm very much unsure why :thinking: 
But after the latest LSP commit (the log commit I think), everything now works perfectly fine for me.

I'm closing this until someday in the future where the issue reproduced itself

**Comment by wookayin** [comment]
I can still reproduce the same bug on: NVIM v0.10.0-dev-2318+g171f65a4d (the latest HEAD) with vue-language-server 1.8.27. So something else other than Nvim is causing the bug for you. Probably depending on the file, project, packages installed, etc.

**Comment by ynhhoJ** [comment]
Happens for me too:

```log
[START][2024-02-10 17:32:48] LSP logging initiated
[WARN][2024-02-10 17:32:48] [...lsp/handlers.lua:134](chrome://devtools/content/webconsole/...lsp/handlers.lua:134)	"The language server eslint triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2024-02-10 17:32:49] [...lsp/handlers.lua:134](chrome://devtools/content/webconsole/...lsp/handlers.lua:134)	"The language server volar triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2024-02-10 17:32:49] .../lua/vim/lsp.lua:823	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[ERROR][2024-02-10 17:32:52] .../vim/lsp/rpc.lua:798	"rpc"	"/home/unknown/.local/share/nvim/mason/bin/vue-language-server"	"stderr"	"/home/unknown/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:565
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: MethodNotFound
    at handleResponse (/home/unknown/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)
    at handleMessage (/home/unknown/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)
    at processMessageQueue (/home/unknown/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
    at Immediate.<anonymous> (/home/unknown/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
    at process.processImmediate (node:internal/timers:478:21) {
  code: -32601,
  data: undefined
}

Node.js v20.10.0
```

**Comment by sid-6581** [comment]
It's still crashing for me too with the latest nightly. It works fine in VS Code.

**Comment by wookayin** [comment]
This bug seems to be mainly the bug of Volar LSP side, not neovim. We can have this issue re-opened if we find anything new that should be fixed on Nvim side (e.g. it doesn't crash on nvim stable but only crashes on nvim-nightly), but when you comment here please help us with providing *new* information or insights so we can better diagnose the problem, rather than simply saying "me too" with no contextual information,  --- like how to reproduce, under which config and/or files this happens or does not happen, which nvim/volar versions you are using, etc.
