### ISSUE TITLE
lsp: deleting entire file breaks incremental synchronization

### ISSUE THREAD

**Issue by XeroOl** [neovim/neovim#27383]
### Problem

Neovim generates an invalid `textDocument/didChange` message when deleting and pasting the entire file.
The message references the range {line 0 col 0 - line 1 col 0}, but when you delete the entire file, there is no line 1.

I'm making a language server, and my server gets confused by this range, because it goes past the end of the file.

Every other language server I've tried seems to tolerate the invalid message, but I'm fairly sure Neovim's behavior isn't correct.

### Steps to reproduce using "nvim -u minimal_init.lua"

You should be able to reproduce this really easily with almost any setup, as long as the language supports the `{"change":2}` mode. (pretty much all language servers do this).

At this point, skip down to the Steps section.

# Probably unnecessary details
If you *really* want the exact same setup as me, you can follow these steps:
<details>
<summary>The exact steps to set up the environment</summary>

Download [fennel-ls](https://git.sr.ht/~xerool/fennel-ls/refs/0.1.0) and put it on the path. To run it, you also need need `lua` on the path, because fennel-ls runs in lua.
Then, init.lua:

```lua
--- CHANGED THESE
local pattern = '*.fnl'
local cmd = {'fennel-ls'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'.git', '.editorconfig'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('BufEnter', {
  pattern = pattern,
  callback = function(args)
    print("reached callback")
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'fennel-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```
I know bufenter is the wrong autocmd, but there is no filetype for .fnl.

Then, `touch .editorconfig` so that the current dir is a root dir. `fennel-ls` needs a workspace to run in, so this is important.
Finally, run the following steps, using `broken.fnl` as the filename.
</details>

# Steps
1. Open a new file that starts a language server
2. Type any text. (in my logs, I type the letter `o`)
3. Move the cursor to the start of the file and use `dG` to delete everything
4. Press `p` to paste everything back
5. Observe that the message sent to the language server isn't valid.

# Description of each sync step
For each step, I'll show the `textDocument/didOpen` and `textDocument/didChange` messages that are sent to the server, and what the file should contain.
## Open a new file that starts a language server
```json
{
  "params": {
    "textDocument": {
      "version": 0,
      "text": "\n",
      "uri": "file:///home/xerool/Documents/bug/broken.fnl",
      "languageId": "fennel"
    }
  },
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen"
}
```
Okay, so Neovim starts an "empty" file with a newline. That's fine. The contents of the file are `"\n"`.

## Type any text.
In this instance, I simply typed the letter `o`.
```json
{
  "params": {
    "textDocument": {
      "uri": "file:///home/xerool/Documents/bug/broken.fnl",
      "version": 4
    },
    "contentChanges": [
      {
        "range": {
          "end": {
            "line": 0,
            "character": 0
          },
          "start": {
            "line": 0,
            "character": 0
          }
        },
        "text": "o",
        "rangeLength": 0
      }
    ]
  },
  "jsonrpc": "2.0",
  "method": "textDocument/didChange"
}
```
Okay, so we take the range {line 0 char 0 - line 0 char 0} and replace it with `"o"`. The contents of the file are `"o\n"`.

## Delete everything
```json
{
  "params": {
    "textDocument": {
      "uri": "file:///home/xerool/Documents/bug/broken.fnl",
      "version": 5
    },
    "contentChanges": [
      {
        "range": {
          "end": {
            "line": 1,
            "character": 0
          },
          "start": {
            "line": 0,
            "character": 0
          }
        },
        "text": "",
        "rangeLength": 2
      }
    ]
  },
  "jsonrpc": "2.0",
  "method": "textDocument/didChange"
}
```
Okay, so we replace from {line 0 char 0 - line 1 char 0} with "". Now, the current content of the file is `""`, with no newline. The file is empty.

## Press `p`
```json
{
  "params": {
    "textDocument": {
      "uri": "file:///home/xerool/Documents/bug/broken.fnl",
      "version": 6
    },
    "contentChanges": [
      {
        "range": {
          "end": {
            "line": 1,
            "character": 0
          },
          "start": {
            "line": 0,
            "character": 0
          }
        },
        "text": "\no\n",
        "rangeLength": 1
      }
    ]
  },
  "jsonrpc": "2.0",
  "method": "textDocument/didChange"
}
```
Here's where I've got a problem. According to the previous messages, the file's contents are `""`. It's empty. However, the server is being asked to replace from {line 0 char 0 - line 1 char 0} with some text.

There is no position that corresponds to line 1 char 0, because there is no newline character in the file, and therefore no line 1.

Now, you may argue that [the protocol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#range) says:
>  If you want to specify a range that contains a line including the line ending character(s) then use an end position denoting the start of the next line.

However, this doesn't apply here, because there is no "line ending character(s)" that could possibly be included here. I believe that Neovim's message isn't valid, and that it is correct for the language server to crash.

### Expected behavior

I expected the the content changes to be applicable to the file. For example: I would be okay if the final message did not try to reference line 1:
```json
{
  "params": {
    "textDocument": {
      "uri": "file:///home/xerool/Documents/bug/broken.fnl",
      "version": 6
    },
    "contentChanges": [
      {
        "range": {
          "end": {
            "line": 0,
            "character": 0
          },
          "start": {
            "line": 0,
            "character": 0
          }
        },
        "text": "\no\n",
        "rangeLength": 1
      }
    ]
  },
  "jsonrpc": "2.0",
  "method": "textDocument/didChange"
}
```
It would also be okay if instead, there was an extra "contentChanges" message after the `dP` that re-introduces the newline after telling the server that the newline was deleted. I'm not sure exactly where the server and client are desyncing, but I would like them to stay in sync.

### Neovim version (nvim -v)

0.9.5 Release

### Language server name/version

fennel-ls 0.1.0

### Operating system/version

Arch Linux

### Log file

https://gist.github.com/XeroOl/873a8ab9968861cf33c73f8acea3ab28

**Comment by dylan-chong** [comment]
i get a similar error when `yy`ing some line then `p`ing it somewhere on some other line. there's a chance that `p`ing will make the lsp get very out of sync. (have noticed this on tsx files). often get diagnostics about syntax error or something ridiculous that will go away when `:e`ing

**Comment by XeroOl** [comment]
Yeah, I've seen desyncs happen in various cases, but `dGp` was the first edits I tried that reliably reproduced the issue.
I suspect there are other combinations of edits that causes more serious desyncs

**Comment by dylan-chong** [comment]
This could be related https://github.com/neovim/neovim/pull/16669

cc @rish987 @mjlbach

**Comment by dylan-chong** [comment]
dear god this issue is constant. i'm running neovim `NVIM v0.10.0-dev-1495+g3d8f0cb69`. i have to run `:e` after writing a few lines of code, or pasting anything, otherwise the lsp is way out of sync. ocassionally `:e` doesnt even get the lsp to sync properly

**Comment by rudiejd** [comment]
For what it's worth, I've noticed similar issues with `typescript-language-server` as @dylan-chong. Could be related to https://github.com/neovim/neovim/issues/26483 - is dynamic registration enabled in this case?

**Comment by XeroOl** [comment]
This is a different issue. I can reproduce this one regardless of if didChangeWatchedFiles is on or off.

**Comment by iurimateus** [comment]
Angular language service crashes with
```
[ERROR][2024-03-29 09:21:11] .../vim/lsp/rpc.lua:789    "rpc"   "ngserver"
"stderr"
"/home/iuri/.local/share/nvim/mason/packages/angular-language-server/node_modules/typescript/lib/tsserverlibrary.js:35508\n
Debug.assert(oldText.length - textChangeRange.span.length + textChangeRange.newLength === newText.length);
\n                  ^\n\nError:
Debug Failure. False expression.\n    at checkChangeRange
(/home/iuri/.local/share/nvim/mason/packages/angular-language-server/node_modules/typescript/lib/tsserverlibrary.js:35508:19)\n
at Object.updateSourceFile2 [as updateSourceFile]
(/home/iuri/.local/share/nvim/mason/packages/angular-language-server/node_modules/typescript/lib/tsserverlibrary.js:35213:11)\n
at updateSourceFile
(/home/iuri/.local/share/nvim/mason/packages/angular-language-server/node_modules/typescript/lib/tsserverlibrary.js:27912:45)\n
at updateLanguageServiceSourceFile
(/home/iuri/.local/share/nvim/mason/packages/angular-language-server/node_modules/typescript/lib/tsserverlibrary.js:139642:31)\n
at acquireOrUpdateDocument
(/home/iuri/.local/share/nvim/mason/packages/angular-language-server/node_modules/typescript/lib/tsserverlibrary.js:131539:30)\n
at Object.updateDocumentWithKey
(/home/iuri/.local/share/nvim/mason/packages/angular-language-server/node_modules/typescript/lib/tsserverlibrary.js:131464:14)\n
at Object.getOrCreateSourceFileByPath [as getSourceFileByPath]
(/home/iuri/.local/share/nvim/mason/packages/angular-language-server/node_modules/typescript/lib/tsserverlibrary.js:139868:39)\n
at tryReuseStructureFromOldProgram
(/home/iuri/.local/share/nvim/mason/packages/angular-language-server/node_modules/typescript/lib/tsserverlibrary.js:117260:61)\n
at createProgram
(/home/iuri/.local/share/nvim/mason/packages/angular-language-server/node_modules/typescript/lib/tsserverlibrary.js:116680:25)\n
at synchronizeHostData
(/home/iuri/.local/share/nvim/mason/packages/angular-language-server/node_modules/typescript/lib/tsserverlibrary.js:139809:17)\n\nNode.js
v18.18.2\n"
```

---

Not sure if related but  `buf_state.refs` https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/_changetracking.lua#L204 may be 0 while there's still other clients attached to the (valid, still open) buffer, which causes `buf_state[bufnr]` to be nil on  https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/_changetracking.lua#L174.

---

I've also had  `attempt to get length of a nil value` when `compute_diff` received
```
  curr_lines = { "",
    [351] = "      @if (uploadingVideo) {",
    [352] = "",
    [353] = "      )}"
  },
  firstline = 353,
  prev_lines = { "",
    [351] = "      @if (uploadingVideo) {",
    [352] = ""
  }
}
```
note that `prev_lines[firstline]` is nil. (forgot to log the remain values...)

**Comment by XeroOl** [comment]
Looks like this may be a duplicate of https://github.com/neovim/neovim/issues/16259

**Comment by XeroOl** [comment]
This line seems to be describing the issue, but I can still reproduce the bug.

https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/_changetracking.lua#L101

Perhaps this fixes it internally, but doesn't share with the language servers?
Perhaps my version of Neovim isn't up to date?
At least I have some possibilities to investigate.

**Comment by sudo-tee** [comment]
I also have the same issue, with lua_ls and with tsserver.

once it get out of sync if I try to restart the lsp or execute `:e` I get weird errors like 

`tsserver: -32603: Request textDocument/documentHighlight failed with message: The document should be opened first: file:///some/path/to/file.ts
`
Here are the relevent errors in `:messages`
```
   Error  06:56:50 msg_show.lua_error Error executing lua callback: ...tly/nvim-linux64/share/nvim/runtime/lua/vim/lsp/sync.lua:380: attempt to get length of a nil value
stack traceback:
	...tly/nvim-linux64/share/nvim/runtime/lua/vim/lsp/sync.lua:380: in function 'compute_range_length'
	...tly/nvim-linux64/share/nvim/runtime/lua/vim/lsp/sync.lua:443: in function 'compute_diff'
	...nux64/share/nvim/runtime/lua/vim/lsp/_changetracking.lua:106: in function 'incremental_changes'
	...nux64/share/nvim/runtime/lua/vim/lsp/_changetracking.lua:311: in function 'send_changes_for_group'
	...nux64/share/nvim/runtime/lua/vim/lsp/_changetracking.lua:348: in function 'send_changes'
	.../nightly/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:461: in function <.../nightly/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:448>
```
```
   Error  06:58:27 msg_show.lua_error   e Error executing lua callback: ...nux64/share/nvim/runtime/lua/vim/lsp/_changetracking.lua:202: attempt to index local 'buf_state' (a nil value)
stack traceback:
	...nux64/share/nvim/runtime/lua/vim/lsp/_changetracking.lua:202: in function 'reset_buf'
	.../nightly/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:562: in function <.../nightly/nvim-linux64/share/nvim/runtime/lua/vim/lsp.lua:559>
```

The only ways to "fix it" is to restart teh LspServer 2 ou 3 times. or quit and reopen nvim
