### ISSUE TITLE
Omnisharp Lsp server return "null" not handled in Neovim

### ISSUE THREAD

**Issue by teast** [neovim/neovim#27395]
### Problem

Omnisharp version 1.39.11
Neovim version 0.9.5
Platform: Windows & Linux (not tested on mac)

Omnisharp language server seems to return "null" on some communications.
This are currently not handled in neovim and therefore we see this error.
Would be interesting if someone who is more knowledge regarding LSP's could chime in on this.

There is an issue open in Omnisharp's github too regarding this: https://github.com/OmniSharp/omnisharp-roslyn/issues/2574

I have pinpointed the "error" to Client:handle_body function in rpc.lua
the pcall to vim.json.decode returns ok and therefore the code will continue and start checking underlying properties on decoded (that is nil) variable.

```lua
  local ok, decoded = pcall(vim.json.decode, body, { luanil = { object = true } })
  if not ok then
    self:on_error(client_errors.INVALID_SERVER_JSON, decoded)
    return
  end
  local _ = log.debug() and log.debug('rpc.receive', decoded)

  if type(decoded.method) == 'string' and decoded.id then
  -- ...
```

If we would include an check if decoded is nil and return the error stop happening. But I'm unsure if that is an expected behavior.

```lua
  local ok, decoded = pcall(vim.json.decode, body, { luanil = { object = true } })
  -- ...

  if decoded == nil then
    return
  end
  if type(decoded.method) == 'string' and decoded.id then
  -- ...
```

Would be interesting if someone who is more knowledge regarding LSP's could chime in on this.

Stacktrace:
```text
Error executing luv callback:
C:\opt\nvim\share\nvim\runtime/lua/vim/lsp/rpc.lua:393: attempt to index local 'decoded' (a nil value)
stack traceback:
        C:\opt\nvim\share\nvim\runtime/lua/vim/lsp/rpc.lua:393: in function 'handle_body'
        C:\opt\nvim\share\nvim\runtime/lua/vim/lsp/rpc.lua:743: in function 'handle_body'
        C:\opt\nvim\share\nvim\runtime/lua/vim/lsp/rpc.lua:263: in function <C:\opt\nvim\share\nvim\runtime/lua/vim/lsp/rpc.lua:247>
```

### Steps to reproduce using "nvim -u minimal_init.lua"

open an .cs file. it is a ~70% chance that Omnisharp lsp server will return null

### Neovim version (nvim -v)

0.9.5

### Language server name/version

Omnisharp 1.39.11

### Operating system/version

Windows 11

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by MariaSolOs** [comment]
Note that some servers won't respect the LSP regarding when a null response is allowed, and in those cases we shouldn't accommodate invalid responses. Either we ask the respective language server to follow the protocol, or create an issue in [the specs](https://github.com/microsoft/language-server-protocol) for clarity on how to deal with these scenarios.

We have seen this happen in the past: https://github.com/neovim/neovim/pull/26957

**Comment by MariaSolOs** [comment]
Also it seems like this is related to https://github.com/neovim/neovim/pull/27148, and I think @wookayin gave a great response about our stand here: https://github.com/neovim/neovim/pull/27148#discussion_r1463344910

**Comment by teast** [comment]
> Also it seems like this is related to #27148, and I think @wookayin gave a great response about our stand here: [#27148 (comment)](https://github.com/neovim/neovim/pull/27148#discussion_r1463344910)

I'm sorry I missed that issue when I tried to find related issue.

I agree and I will take a closer look on both Omnisharp and their csharp-language-server-protocol to see if I can find the bug and open an issue there instead

**Comment by zapling** [comment]
Nevermind I was too quick in my reading https://github.com/OmniSharp/omnisharp-roslyn/issues/2574

**Comment by TamaMcGlinn** [comment]
https://github.com/neovim/neovim/pull/27148#discussion_r1463344910 was rightly rejected because it silently ignores the error.

But it seems perfectly reasonable to throw a readable error message here stating the LSP server is erroneously returning nil. The rest of the code in rpc.lua is doing similar sanity checking, for example giving good error messages if the LSP server returns a number, which is clearly also invalid. We should not silently ignore these issues, but we also shouldn't just crash inside a random NeoVim rpc.lua file because of dereferencing a nil.
