### ISSUE TITLE
Ability to pass position parameters to lsp.buf functions

### ISSUE THREAD

**Issue by rudiejd** [neovim/neovim#27400]
### Problem

At the moment, `lsp.buf.references` [requires my cursor to be on the word for which I want to get references (calls the make_position_params function)](https://github.com/rudiejd/neovim/blob/bcf96538143564bc8de26c5db28df7cfbaf8025a/runtime/lua/vim/lsp/util.lua#L1961). If I want to request references for a symbol that isn't under my cursor, I first have to navigate there then navigate back. This also applies to `lsp.buf.implementation`, `lsp.buf.definition`, etc. 

### Expected behavior

In Lua, I should be able to pass my own [TextDocumentPositionParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentPositionParams) to my LSP server so that I can utilize all of these functions for any symbol in the buffer, not just the one under my cursor. 

Right now, my alternative options for this seem to be:
1. Do `lsp.buf_request` in lua and pass whatever parameters I want
2. Change the cursor to the position of my request, make the request, and change it back

If adding the ability to pass position isn't desired for any of the `lsp.buf` module functions, I can go with (1), but to me this seems like a feature that should be standard.

**Comment by justinmk** [comment]
For reference, see https://github.com/neovim/neovim/pull/27447#issuecomment-1942890548 (and comments above it).

> > My use case for this would be searching for referenced of a symbol in my buffer that I'm not moused over, so the position could change every time I want to call the handler.
> 
> Placing the cursor programmatically works there.
> 
> > I'd also like to be able to navigate to the definition of something that isn't under my cursor without polluting the jumplist.
> 
> `:help cursor()` says "Does not change the jumplist."
> 
> In general I agree that APIs should always take a position (#25509) instead of inspecting the cursor, but these `vim.lsp.buf` APIs are mostly for "interactive" tasks (e.g. `rename()` moves the cursor).

**Comment by rudiejd** [comment]
For context, let me describe one of the use cases I would've had for passing a position into the `lsp.buf` handlers. I frequently work in a C# codebase, and I often want to easily switch from inherited classes to the interfaces from which they are inherited. Since this inheritance is often 1:1 (an unfortunate, but common pattern in C#), 9 times out of 10 I can figure out the name of the interface I want to go to from the filename. I want to make a `textDocument/definition` request for the current filename, prefixed with `I`. For example, if I'm in the `FooFactory`, I want to go to the `IFooFactory`.

Here's the code I ended up using. -  note that the LSP handler for `textDocument/references` does add an entry to the jumplist, but this is a minor inconvenience for me. 

```lua
      local inherited_interface_position = function(lsp_request)
          -- find the position of the name of the file with 'I' preprended
          local lnum, col = unpack(vim.api.nvim_eval('searchpos("I" . expand("%:t:r"))'))
          local text_document_identifier = vim.lsp.util.make_text_document_params()
          -- uses zero based indices
          local position = { line = lnum - 1, character = col }

          -- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#referenceParams
          local params = { position = position, textDocument = text_document_identifier, context = { includeDeclaration = true } }

          print(vim.inspect(params))
          vim.lsp.buf_request(0, lsp_request, params)
      end
```

**Comment by lewis6991** [comment]
As mentioned, this is out of scope for `vim.lsp.buf` and it's already possible to implement this by programmatically moving the cursor.

Alternatively, you could monkeypath `util.make_position_params` before calling `vim.lsp.buf.*`

```lua
local f = vim.lsp.util.make_position_params
vim.lsp.util.make_position_params = ...
vim.lsp.buf.references(...)
vim.lsp.util.make_position_params = f
```

We will this use case in mind for the future.
