### ISSUE TITLE
Line with `>` disappears after joining lines with `%` (and vice versa)

### ISSUE THREAD

**Issue by gvjacob** [neovim/neovim#27430]
### Problem

This potential bug is so bizarrely specific and hard to describe. Looking for insight into why this is happening! A line with just `>` disappears when I try to join it with other lines using `J`. This _seems_ to only happen if the other line has `%` in it and if the filetype is set to anything else but `html`.

From my testing, this happens only with `>` and `%`. I tested with regular Vim and things are working fine there. 

https://github.com/neovim/neovim/assets/23367882/3893a4b9-97a2-4ee0-8b39-c0fd0a98b28b

### Steps to reproduce

1. nvim --clean
2. Write `%` in one line and `>` in the next line
3. On the line with `%`, press `J` to join the next line
4. Observe that the `>` has completely disappeared.

### Expected behavior

After pressing `J`, the two lines should be combined to form `% >`

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

no, vim works as expected

### Operating system/version

macOS 13.4.1

### Terminal name/version

iTerm 3.4.23

### $TERM environment variable

xterm-256color

### Installation

Homebrew

**Comment by zeertzjq** [comment]
Search existing issues.

**Comment by wookayin** [comment]
#27260
