### ISSUE TITLE
neovim with `git add --patch` behaves badly

### ISSUE THREAD

**Issue by timheap** [neovim/neovim#2744]
`git add --patch` is a very useful git command that allows a user to add, ignore, or edit changed files to stage a commit in an interactive manner. It has a subcommand, `e`, that allows users to edit a changed hunk in the editor of their choice. This edited hunk is then staged for commit instead of the actual changes to the file on disk.

Using vim 7.4 from Debian Jessie (and all previous versions since I started using `git add -p`), `git add --patch` works as expected. The user can run `git add --patch`, hit `e` to edit a hunk, and vim will open. The user can then edit the hunk, save the file, and quit vim. `git add --patch` will continue by prompting for a response to the next changed hunk.

Using neovim, after pressing `e`, the hunk to edit is opened. The user can modify the file as expected, write, and quit. However, as soon as nvim exits, `git add --patch` will endlessly prompt for a response to the next hunk until it is killed by ^C. The user can not continue with `git add --patch`, and must restart it after killing it if they want to continue staging more hunks.

This is reproducible in a completely new user account with no `~/.gitconfig`, `~/.nvimrc`, or similar files. To reproduce, run the following in a clean environment:

```
$ export EDITOR=nvim
$ export VISUAL=nvim
$ git init repo
$ cd repo
$ touch file1 file2
$ git add file1 file2
$ git commit -m 'Initial commit'
$ cat > file1
Some changes
^D
$ cat > file2
Some other changes
^D
$ git add --patch
diff --git a/file1 b/file1
index e69de29..c02392e 100644
--- a/file1
+++ b/file1
@@ -0,0 +1 @@
+Some changes
Stage this hunk [y,n,q,a,d,/,e,?]? e
[nvim opens up to edit the hunk. Quit nvim to continue]
diff --git a/file2 b/file2
index e69de29..c02392e 100644
--- a/file2
+++ b/file2
@@ -0,0 +1 @@
+Some changes
Stage this hunk [y,n,q,a,d,/,e,?]? @@ -0,0 +1 @@
+Some changes
Stage this hunk [y,n,q,a,d,/,e,?]? @@ -0,0 +1 @@
+Some changes
Stage this hunk [y,n,q,a,d,/,e,?]? @@ -0,0 +1 @@
+Some changes
Stage this hunk [y,n,q,a,d,/,e,?]? @@ -0,0 +1 @@
+Some changes
Stage this hunk [y,n,q,a,d,/,e,?]? @@ -0,0 +1 @@
+Some changes
Stage this hunk [y,n,q,a,d,/,e,?]? @@ -0,0 +1 @@
+Some changes
Stage this hunk [y,n,q,a,d,/,e,?]? @@ -0,0 +1 @@
+Some changes
Stage this hunk [y,n,q,a,d,/,e,?]? @@ -0,0 +1 @@
+Some changes
^C
$
```

A full log of the shell session I ran can be found at: <https://gist.github.com/timheap/5b37161512dd190f3514>. I am running `nvim --version`:

```
NVIM 0.0.0-alpha+201505251630 (compiled May 26 2015 12:34:15)
Commit: a7b5ae37a71dae93f86da3003bf267fc4f4490f0
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/tim/fucking-around/neovim/build/config -I/home/tim/fucking-around/neovim/src -I/home/tim/fucking-around/neovim/.deps/usr/include -I/home/tim/fucking-around/neovim/.deps/usr/include -I/home/tim/fucking-around/neovim/.deps/usr/include/luajit-2.0 -I/home/tim/fucking-around/neovim/.deps/usr/include -I/home/tim/fucking-around/neovim/.deps/usr/include -I/home/tim/fucking-around/neovim/.deps/usr/include -I/home/tim/fucking-around/neovim/.deps/usr/include -I/usr/include -I/home/tim/fucking-around/neovim/build/src/nvim/auto -I/home/tim/fucking-around/neovim/build/include
Compiled by tim@nightjar

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/share/nvim"
```

**Comment by fwalch** [comment]
Does https://github.com/neovim/neovim/pull/2598 fix this for you?

**Comment by timheap** [comment]
#2598 fixes it for me. I'll close this in favour of that pull request. Thanks!
