### ISSUE TITLE
Current master does not build on NixOS

### ISSUE THREAD

**Issue by vE5li** [neovim/neovim#27440]
### Problem

When pulling the latest state of Neovim as a flake input (e.g. `neovim.url = "github:neovim/neovim?dir=contrib";`) it does not compile. Compilation fails during linking with the following error:
```
/nix/store/fzlkaj1ax7gl655blfcr6zzvml1vx3bj-binutils-2.40/bin/ld: /build/ccCNaot3.ltrans39.ltrans.o: in function `node_rawquery.lto_priv.0':
/build/zzwq2v2vw9a98c1ydsdv683sskqxrklf-source/src/nvim/lua/treesitter.c:1456: undefined reference to `ts_query_cursor_set_max_start_depth'
/nix/store/fzlkaj1ax7gl655blfcr6zzvml1vx3bj-binutils-2.40/bin/ld: /build/zzwq2v2vw9a98c1ydsdv683sskqxrklf-source/src/nvim/lua/treesitter.c:1480: undefined reference to `ts_query_cursor_set_max_start_depth'
collect2: error: ld returned 1 exit status
make[2]: *** [src/nvim/CMakeFiles/nvim_bin.dir/build.make:5150: bin/nvim] Error 1
make[1]: *** [CMakeFiles/Makefile2:624: src/nvim/CMakeFiles/nvim_bin.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

I guess that Neovim updated to a newer version of treesitter in the past couple of weeks but the dependency was not updated in the `flake.nix`? I tried to look into it myself to propose a fix but my Nix knowledge is quite limited and I couldn't really find the issue.

### Steps to reproduce

Run `sudo nixos-rebuild switch`

### Expected behavior

It compiles

### Neovim version (nvim -v)

597ecf751603cde2d5f58021d503ae20a12eb2f2

### Vim (not Nvim) behaves the same?

Not relevant

### Operating system/version

NixOS

### Terminal name/version

Not relevant

### $TERM environment variable

Not relevant

### Installation

Nix Flake

**Comment by clason** [comment]
This is a flake issue, which is contributed. PR welcome.

**Comment by WhiteBlackGoose** [comment]
Curious, why is it closed "as not planned"? I understand that maintainers don't plan to fix it but I'd leave it there so it's still a visible issue for others

**Comment by illia-imperva** [comment]
I cannot build it either on redhat8
