### ISSUE TITLE
Kotlin syntax highlighter is present in the codebase but not bundled with the releases

### ISSUE THREAD

**Issue by ni554n** [neovim/neovim#27465]
### Problem

`kotlin.vim` for [/ftplugin](https://github.com/neovim/neovim/blob/master/runtime/ftplugin/kotlin.vim) and [/syntax](https://github.com/neovim/neovim/blob/master/runtime/syntax/kotlin.vim) are not included in the final builds, despite being recognized as a valid file type in [filetype.lua](https://github.com/neovim/neovim/blob/a376d979bda103fa9998d05c3cc4ba56d3c3cece/runtime/lua/vim/filetype.lua#L578-L580).

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal 1.19.10302.0

### $TERM environment variable

xterm-256color

### Installation

Portable ZIP

**Comment by zeertzjq** [comment]
They will be present in v0.10.
