### ISSUE TITLE
bug: blank notifications with `nvim-notify`

### ISSUE THREAD

**Issue by kawre** [neovim/neovim#27467]
### Problem

All I've done is bump my neovim to `NVIM v0.10.0-dev-2359+g9f8c96240d`, and since then my notifications from `nvim-notify` are completely broken. I'm aware it might be an issue with `nvim-notify` but as I said, I've only bumped my neovim version and did not update any plugins, so this makes me think it's not.

https://github.com/neovim/neovim/assets/69250723/9e4f8493-0066-4141-bcdb-5657530a5230

### Steps to reproduce

If you confirm it might be an issue with latest neovim changes, I will try to provide one

### Expected behavior

.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2359+g9f8c96240d

### Vim (not Nvim) behaves the same?

.

### Operating system/version

6.7.4-arch1-1

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

https://aur.archlinux.org/packages/neovim-git

**Comment by dpetka2001** [comment]
@kawre Pls try to see if this [PR](https://github.com/rcarriga/nvim-notify/pull/253) from `nvim-notify` solves your issue.

**Comment by kawre** [comment]
repro:

```lua
-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs({
	-- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
	notify = "https://github.com/rcarriga/nvim-notify",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE)
vim.notify = require("notify")
```

@dpetka2001 It does solve it, but it only does for neovim nightly, if you switch to `0.9.5` for example it will display blank notifications the same way it did on nightly before the fix. This makes me think this is indeed a neovim problem?

**Comment by clason** [comment]
No, it just means that nvim-notify needs to gate the "fix" behind a version guard.

**Comment by clason** [comment]
I suspect that this change (which fixes incorrect behavior!) is responsible: https://github.com/neovim/neovim/commit/f9d81c43d2296d212c9cebcbdce401cd76cf0f1f

(Pro tip: "I updated Neovim and now something broke!" is really less than helpful. If you run `master` and notice a bug, always bisect before opening an issue!)

**Comment by zeertzjq** [comment]
> No, it just means that nvim-notify needs to gate the "fix" behind a version guard.

Or check the types of the `row` and `col` values.

**Comment by kawre** [comment]
> (Pro tip: "I updated Neovim and now something broke!" is really less than helpful. If you run master and notice a bug, always bisect before opening an issue!)

Sorry should've done that at the beginning, but my reasoning for not doing so was because it's either caused by some recent API changes and this issue gets immediately closed and I waste time bisecting this or it is indeed some problem with neovim then if told, I would try to bisect this without any problems.

Should I close this?

**Comment by dpetka2001** [comment]
@kawre Pls check the latest commit in that PR. I believe now it takes both Neovim stable and nightly into account. Not sure if it's the best solution, but once the maintainer of the plugin gets to review this PR, hopefully a more elegant solution will produce the wanted outcome if needed.

**Comment by kawre** [comment]
If anyone has this issue, see https://github.com/rcarriga/nvim-notify/pull/253.

Best to let this issue open until this PR is merged, since if you use `noice.nvim`, you will have `cmdheight` set to `0` thus not get any errors, which might make it hard to find a fix for this.
