### ISSUE TITLE
Cursor horizontal position lost after setting an option

### ISSUE THREAD

**Issue by Bekaboo** [neovim/neovim#27470]
### Problem

The cursor's horizontal position will be lost after an option is set.

This only happens to some options including `spell` and `winhl` but not some other options like `shiftwidth`.

### Steps to reproduce

1. Create `minimal.lua` as described below
1. `nvim --clean -u minimal.lua`
2. Open a random text file with lines with different lengths
3. Move the cursor to the right by hitting `l` several times
4. Move the cursor down by pressing `j`
5. Observe that the horizontal cursor position is not remembered when the cursor moves past lines of different lengths

`minimal.lua`:

```lua
vim.api.nvim_create_autocmd('CursorMoved', {
	callback = function()
		vim.opt.winhl:append('Foo:Bar') -- has bug
                -- vim.opt.spell = true -- has bug
                -- vim.opt.shiftwidth = 4 -- no bug
	end
})
```

### Expected behavior

The horizontal cursor position should be kept across lines with different lengths.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2273+g21df0cdb88

### Vim (not Nvim) behaves the same?

yes, version VIM - Vi IMproved 9.1

### Operating system/version

Linux 6.7.4-arch1-1

### Terminal name/version

alacritty 0.12.3 (5efb0690) + tmux 3.3a

### $TERM environment variable

xterm-256color

### Installation

AUR

**Comment by zeertzjq** [comment]
This can be simply fixed by:
```diff
diff --git a/src/nvim/options.lua b/src/nvim/options.lua
index b993a50b18..deae0fa280 100644
--- a/src/nvim/options.lua
+++ b/src/nvim/options.lua
@@ -9900,7 +9900,7 @@ return {
       expand_cb = 'expand_set_winhighlight',
       full_name = 'winhighlight',
       list = 'onecommacolon',
-      redraw = { 'current_window' },
+      redraw = { 'current_window_only' },
       scope = { 'window' },
       short_desc = N_('Setup window-local highlights'),
       type = 'string',
```

This fix is needed for a lot of options.

**Comment by bew** [comment]
Why is this redraw change responsible for the horizontal position of the cursor? 🤔
