### ISSUE TITLE
Thesaurus and parsing file

### ISSUE THREAD

**Issue by hyde-stevenson** [neovim/neovim#27477]
### Problem

Hello,

When trying to use the thesaurus completion, it works well with some words like :

- abbey[C-x C-t] 

will provide church, convent, monastery for example. 

But, for some word like "spy", you wont get the right synonyms. 
It will grep lines like : 

```
a*spy* rough gruff hoarse husky piercing raucous strident rending ripping splitting noisy
*spy*ing spotting discovery find uncovering contracting acquiring getting
counter*spy* mole spy
cri*spy* crisp
descry spot espy spy sight

```

Couldn't the completion match the full word except just one part of it ? 

### Steps to reproduce

Using the default thesaurus completion should be enough to reproduce this. 

### Expected behavior

Having the right synonym using the completion.

### Neovim version (nvim -v)

v0.9.4

### Vim (not Nvim) behaves the same?

Yes with 9.0.1672

### Operating system/version

Debian 

### Terminal name/version

kitty 0.25.6

### $TERM environment variable

xterm-256color 

### Installation

tarball

**Comment by clason** [comment]
We don't maintain these files, nor the legacy spelling/thesaurus. Please raise this issue at vim/vim.

**Comment by hyde-stevenson** [comment]
Ah okay !  Thanks !
