### ISSUE TITLE
make `:cd` invoke `exrc` files in the current directory. 

### ISSUE THREAD

**Issue by Aman9das** [neovim/neovim#27489]
### Problem

Say one wants to open `~/proj1/` as a project.
The [`exrc`](https://neovim.io/doc/user/starting.html#exrc) option is enabled.
Structure of `proj1`:
```
proj1
├── .nvim.lua
├── index.qmd
└── post1.qmd
```
`.nvim.lua` enables the project specific configurations.

1. They can `nvim ~/proj1` to open the project.
Neovim starts up in `~/proj1`.
As a result `.nvim.lua` configuration file is run.
2. Or they may start neovim as `nvim`.
**Then** switch to the project by running `:cd ~/proj1` command.
But the `.nvim.lua` project configuration isn't run.

This difference makes method 2 unsuitable for opening projects.

### Expected behavior

The benefit of method 2 of opening projects:
- We can create a general Neovim application shortcut.
- We can switch between projects in the same session.

Method 2 should also invoke and get the benefits of `.nvim.lua` exrc configuration file.
There is not much reason to expect this difference in behaviour in my opinion.

**Comment by Aman9das** [comment]
> I don't think this should be the default behavior.

Yes, of course. `vim.opt.exrc` has to be enabled for this, by the user. But once it is enabled, is there any reason

**Comment by clason** [comment]
> But once it is enabled, is there any reason to prevent method 2 from running .nvim.lua.

Security. Any plugin can do `:cd`, and silently, so this is much more sensitive than `nvim <file>` (which can be assumed to be intentional).

**Comment by justinmk** [comment]
If we implement this it should show the `:help trust` prompt before executing `nvim.lua`. So I don't think there is a security issue?

**Comment by gpanders** [comment]
This works:

```lua
vim.api.nvim_create_autocmd("DirChanged", {
    callback = function(args)
        local contents = vim.secure.read(string.format("%s/.nvim.lua", args.file))
        if contents then
            assert(loadstring(contents))()
        end
    end,
})
```

We could add this to `_defaults.lua` (assuming it's something we want). I'm not sure I see a reason not to though?

**Comment by GnikDroy** [comment]
I believe the original intention behind `exrc` was to work like `.bashrc`/ `.pylintrc`/`.vimrc` and the other [runcom](http://www.catb.org/jargon/html/R/rc-file.html) files. It is usually setup to run at the start of a program *once*. Probably also the reason `:h exrc` is placed in the initialization startup part in vim. You do not expect `.bashrc` to run on `cd` for instance.
 
While there is nothing wrong with running `exrc` files on `DirChanged`, it is very easy to do the same thing without using the filenames used by `exrc` in your init file. Just tweaked the above code a bit.

```lua
local PROJECT_CONFIG_FILE_NAME = ".nvim.project.lua"
vim.api.nvim_create_autocmd("DirChanged", {
    callback = function(args)
        local contents = vim.secure.read(string.format("%s/%s", args.file, PROJECT_CONFIG_FILE_NAME))
        if contents then
            assert(loadstring(contents))()
        end
    end,
})
```

**Comment by LunarLambda** [comment]
I don't think this should be added as a default mechanism. The comparison other people have made is correct in my opinion - `exrc` files should work analogous to things like `.bashrc` and other 'rc' files. It should be relegated to a plugin with much more flexibility in its configuration, similar to `direnv` in the shell world.

Especially because in addition to `:cd` (global), there is `:tcd` (tabpage scope) and `:lcd` (window scope), and in my opinion it's unclear (and highly use-case specific) how any automatic sourcing of rc files should work in the face of that.

As an example, just using `DirChanged` like above means potentially *re-sourcing `.nvim.lua` on every window switch* [(docs)](https://neovim.io/doc/user/autocmd.html#DirChanged), and no matter which behaviour Neovim tries to decide to use, inevitably there will be people who need something else and won't be able to make the default behaviour work for them.

**Comment by tricktux** [comment]
@justinmk is there no appetite for extending the `vim.secure` api?

### Problem

There's a worflow partially unaddressed for users who start Neovim from `X` folder and navigate to projects from within the editor. The only tool available for this workflow is `vim.secure.read()`, which handles trust verification but stops there — it returns the file contents as a string and leaves execution entirely to the caller.

Sourcing a trusted `.nvim.lua` correctly requires trivial but mandatory boilerplate:

```lua
local content = vim.secure.read(path)
if content == nil then return end

local chunk, err = load(content, "@" .. path)
if not chunk then
  vim.notify(err, vim.log.levels.ERROR)
  return
end

local ok, run_err = pcall(chunk)
if not ok then
  vim.notify(run_err, vim.log.levels.ERROR)
end
```

Every user who wants this pattern must independently rediscover and reimplement it. The API exposes a low-level primitive where a high-level one is almost always what's needed.

---

### Solution

Add `vim.secure.source(path)` — a thin wrapper that calls `vim.secure.read()` internally, then compiles and executes the result if trusted. Semantically equivalent to `vim.secure.read()` + `load()` + `pcall()`, with proper error reporting and chunk naming.

This would let users (or plugin authors) handle the `DirChanged` use case cleanly:

```lua
vim.api.nvim_create_autocmd("DirChanged", {
  callback = function()
    vim.secure.source(vim.fn.getcwd() .. "/.nvim.lua")
  end,
})
```

`vim.secure.read()` would remain unchanged for callers who need the raw content. `vim.secure.source()` is purely additive.

**Comment by justinmk** [comment]
> [@justinmk](https://github.com/justinmk) is there no appetite for extending the `vim.secure` api?

The door is open to that. I didn't review your proposal but worth opening a new issue.
