### ISSUE TITLE
treesitter: query_linter: bad argument #1 to `ipairs`

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#27497]
### Problem

I get `bad argument` error on using query editor:

![image](https://github.com/neovim/neovim/assets/11404453/d1f51cc8-3a8f-409d-a2b3-288cb7acf5ce)

```
Error detected while processing BufEnter Autocommands for "<buffer=3>":
Error executing lua callback: .../share/nvim/runtime/lua/vim/treesitter/_query_linter.lua:134: bad argument #1 to 'ipairs' (table expected, got userdata)
stack traceback:
        [C]: in function 'ipairs'
        .../share/nvim/runtime/lua/vim/treesitter/_query_linter.lua:134: in function 'lint_match'
        .../share/nvim/runtime/lua/vim/treesitter/_query_linter.lua:184: in function 'fn'
        ...c/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:489: in function 'for_each_tree'
        .../share/nvim/runtime/lua/vim/treesitter/_query_linter.lua:176: in function 'lint'
        ...from-src/share/nvim/runtime/lua/vim/treesitter/query.lua:1010: in function 'lint'
        .../tmp/nvim-from-src/share/nvim/runtime/ftplugin/query.lua:28: in function <.../tmp/nvim-from-src/share/nvim/runtime/ftplugin/query.lua:27>
```

### Steps to reproduce

- `nvim --clean c.c`
- `:InspectTree`
- open query editor
- put `(preproc_def)+ @test` there
- try to switch between windows

### Expected behavior

No error

### Neovim version (nvim -v)

v0.10.0-dev-2381+ga75ef40f4

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Debian Sid

### Terminal name/version

tmux 3.4-1, alacritty 0.14.0-dev (4c0c368e)

### $TERM environment variable

tmux-256color

### Installation

from repo

**Comment by clason** [comment]
Please test #27496
