### ISSUE TITLE
Use vim-javascript for improved JS syntax and indenting

### ISSUE THREAD

**Issue by bronzehedwick** [neovim/neovim#2749]
The [vim-javascript](https://github.com/pangloss/vim-javascript) plugin offers much better syntax and indenting for Javascript files, over Vim's default.

[An issue in that project](https://github.com/pangloss/vim-javascript/issues/177) is open to include it with Vim, and a comment says that a patch has been submitted on the mailing list, however I was unable to find it (admittedly, I am new to navigating the Vim mailing list).

**Comment by justinmk** [comment]
https://groups.google.com/d/msg/vim_dev/EBDKCCBl7F0/WrQOvo8GKwoJ

**Comment by bronzehedwick** [comment]
Thanks @justinmk!

**Comment by justinmk** [comment]
This is fixed in Vim. Not sure if we merged it yet, but we will soon.
