### ISSUE TITLE
Assertion Failure in libuv When Opening .py Files

### ISSUE THREAD

**Issue by edonervo** [neovim/neovim#27506]
### Problem

**Issue Description:**
I am encountering an assertion failure in the libuv library when opening `.py` files in Neovim. The error message is as follows:

```
❯ nvim --headless init.py
nvim: /__w/neovim/neovim/.deps/build/src/libuv/src/unix/core.c:301: uv__finish_close: Assertion `handle->flags & UV_HANDLE_CLOSING' failed.
[1]    8598 IOT instruction  nvim --headless init.py
```

### Steps to reproduce

This issue occurs consistently and seems to be related to libuv.

**Steps to Reproduce:**
1. Open Neovim with a specific `.py` file.
2. Observe the assertion failure in libuv.

**Environment Details:**
- Neovim Version: `v0.9.5`
- Operating System:  Ubuntu 22.04.4 LTS
- libuv Version: 1.43.0-1

**Additional Information:**
It does not seem related to my nvim configuration because using the --flag is causing the same issue:

```
❯ nvim --clean --headless init.py
nvim: /__w/neovim/neovim/.deps/build/src/libuv/src/unix/core.c:301: uv__finish_close: Assertion `handle->flags & UV_HANDLE_CLOSING' failed.
[1]    8824 IOT instruction  nvim --clean --headless init.py
```

### Expected behavior

**Expected Behavior:**
Neovim should open `.py` files without encountering assertion failures in libuv.

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1692716794     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Ubuntu 22.04.4 LTS

### Terminal name/version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### $TERM environment variable

xterm-256color

### Installation

bob packet manager

**Comment by clason** [comment]
Can you please try the release appimage from our website? This libuv version is very old, and we need to make sure it's a Neovim problem and not a distro build issue.

**Comment by edonervo** [comment]
I installed the appimage of 0.9.5 but error persists:
```
❯ ./nvim.appimage --clean --headless init.py
nvim: /__w/neovim/neovim/.deps/build/src/libuv/src/unix/core.c:301: uv__finish_close: Assertion `handle->flags & UV_HANDLE_CLOSING' failed.
[1]    11825 IOT instruction  ./nvim.appimage --clean --headless init.py
```

**Comment by zeertzjq** [comment]
Can you also try the nightly appimage?

**Comment by edonervo** [comment]
Now the error output is different:

```
╰─❯ nvim --headless init.py
Error detected while processing BufNewFile Autocommands for "*":
Error executing lua callback: .../.mount_nvim.aOZwqd9/usr/share/nvim/runtime/filetype.lua:30: Error executing lua: .../.mount_nvim.aOZwqd9/usr/share/nvim/runtime/filetype.lua:31: BufNewFile Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..script /tmp/.mount_nvim.aOZwqd9/usr/share/nvim/runtime/ftplugin/python.vim, line 42: Vim(if):provider: python3: missing required variable g:loaded_python3_provider
stack traceback:
        [C]: in function 'nvim_cmd'
        .../.mount_nvim.aOZwqd9/usr/share/nvim/runtime/filetype.lua:31: in function <.../.mount_nvim.aOZwqd9/usr/share/nvim/runtime/filetype.lua:30>
        [C]: in function 'nvim_buf_call'
        .../.mount_nvim.aOZwqd9/usr/share/nvim/runtime/filetype.lua:30: in function <.../.mount_nvim.aOZwqd9/usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        .../.mount_nvim.aOZwqd9/usr/share/nvim/runtime/filetype.lua:30: in function <.../.mount_nvim.aOZwqd9/usr/share/nvim/runtime/filetype.lua:10>
```
