### ISSUE TITLE
How to append lines to background buffer?

### ISSUE THREAD

**Issue by strrchr** [neovim/neovim#2750]
With async job control, I'd like to append lines to background buffer.
4 choices come to my mind:
a) use python remote plugin
b) use bufdo and a if bufnr == target then append() endif hack
c) sp the buf, append, close
d) Use setbufvar to keep a list of lines to be added. Add them on bufenter event when buffer is shown anyway

I suggest that extend append and more functions so that can pass a bufnr.

**Comment by Shougo** [comment]
Related question in vim_dev.

https://groups.google.com/forum/#!searchin/vim_dev/setbufline/vim_dev/td1mNkW4q3I/p75OgH5f5yEJ

I think to add `setbufline()` in VimL is better choice.

**Comment by justinmk** [comment]
Extending vimscript isn't really an attractive option in most cases. With choice (a) it appears you are aware that this is already possible with the API. The next step, then, is to make the API easier to use from vimscript. We're working on this, though there no specific issue, it is a priority.

> I think to add setbufline() in VimL is better choice.

https://github.com/neovim/neovim/issues/901

**Comment by bfredl** [comment]
setbufline now exists, though with the name `nvim_buf_set_lines`. No docs accessible in `:help` yet, but
`nvim_buf_set_lines(bufnr, lnum-1, lnum, v:true, ['replacing line'])` to replace lnum and 
`nvim_buf_set_lines(bufrn, lnum, lnum, v:true, ['inserted line'])` to insert after lnum (set lnum to 0 or -1 to prepend before first or append after last line respectively). `bufnr` can additionally be 0 to mean the current buffer.
