### ISSUE TITLE
`overlay` extmark not detecting `inline` extmark when the line starts at 0 column

### ISSUE THREAD

**Issue by kristijanhusak** [neovim/neovim#27516]
### Problem

Adding `inline` extmark to the buffer and then adding `overlay` extmark on top of it does not detect the `inline` extmark when the line starts at 0 column. When the starting column is > 0, it works fine.
The images below will explain it better.

### Steps to reproduce

1. Create a test file: `echo "- First item\n  - Second item" > test.txt`
2. Create a `repro.lua` file with this content:
```lua
local ns = vim.api.nvim_create_namespace('repro')
local bufnr = vim.api.nvim_get_current_buf()

-- Add inline extmarks to both lines
vim.api.nvim_buf_set_extmark(bufnr, ns, 0, 0, {
  virt_text = {{'  '}},
  virt_text_pos = 'inline',
})
vim.api.nvim_buf_set_extmark(bufnr, ns, 1, 0, {
  virt_text = {{'  '}},
  virt_text_pos = 'inline',
})

-- Add overlay extmarks to both lines
vim.api.nvim_buf_set_extmark(bufnr, ns, 0, 0, {
  end_col = 1,
  virt_text = {{'x'}},
  virt_text_pos = 'overlay',
  hl_mode = 'combine',
})
vim.api.nvim_buf_set_extmark(bufnr, ns, 1, 2, {
  end_col = 3,
  virt_text = {{'x'}},
  virt_text_pos = 'overlay',
  hl_mode = 'combine',
})
```
3. Open the test file `nvim --clean test.txt`
4. source the repro file `:luafile repro.lua`

Result:
![screenshot_2024_02_18_11_50_32](https://github.com/neovim/neovim/assets/1782860/65c715b5-f9a1-4f28-b596-e59cd831dc4a)

### Expected behavior

First line should have overlay extmark at correct position:

![screenshot_2024_02_18_11_51_19](https://github.com/neovim/neovim/assets/1782860/b627bf10-885d-423f-9c2d-daa017930cd0)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2388+gb12d193b4

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

https://github.com/MordechaiHadad/bob

**Comment by zeertzjq** [comment]
Some may prefer the current behavior. I think the behavior should depend on priority.
