### ISSUE TITLE
Can not type Chinese

### ISSUE THREAD

**Issue by lazywei** [neovim/neovim#2752]
![image](https://cloud.githubusercontent.com/assets/2840571/7852969/664fead0-0539-11e5-856a-e6a3be1cc88f.png)

It looks like only some Chinese words can be shown without problem in NeoVim (latest build).
Do I need to do some extra configuration?

**Comment by justinmk** [comment]
What is &encoding?  Might be a TUI bug.

**Comment by lazywei** [comment]
I type this in command mode:
```
:set encoding
encoding=utf-8
```

**Comment by Shougo** [comment]
Hmmm...   What are you using Input Method to input Chinese?

I use fcitx-mozc for input Japanese in neovim and it works.
It has ambiwidth problem though.

https://github.com/neovim/neovim/issues/2684

**Comment by lazywei** [comment]
I don't think it is the issue of Input Method. The reason is that it doesn't work either if I paste Chinese on NeoVim.

For #2684, I paste the ambiwidth character and get this:
![image](https://cloud.githubusercontent.com/assets/2840571/7853110/1eeafb8c-053c-11e5-8df6-9f7a24b91dfd.png)

My terminal is iTerm 2.

**Comment by justinmk** [comment]
I think we broke ambiwidth. It may be a `#ifdef` feature we need to add back.

**Comment by Shougo** [comment]
> For #2684, I paste the ambiwidth character and get this:

I can get correct displays, but it is broken.
Because, "▽" is recognized as two characters instead of one character.

**Comment by Shougo** [comment]
@lazywei I want to test Chinese characters in neovim.  Can you provide the test characters?

**Comment by lazywei** [comment]
maybe paster this: 中文字當以繁體爲主

it's wired, if i type the Chinese directly in NeoVim, I got this
![image](https://cloud.githubusercontent.com/assets/2840571/7853554/8b5b4da2-0542-11e5-9583-8b81829ff83d.png)

but if i copy and paste, i got this

![image](https://cloud.githubusercontent.com/assets/2840571/7853559/969cbcdc-0542-11e5-815d-fcee16aabd40.png)

and if I do this
```
~/dotfiles ❯❯❯ echo "中文字當以繁體爲主" > test
~/dotfiles ❯❯❯ vim test
```
i can get correct display
![image](https://cloud.githubusercontent.com/assets/2840571/7853560/b01ebd7c-0542-11e5-93ea-78ef0b9308bb.png)

**Comment by Shougo** [comment]
I got correct result in neovim.
I use LilyTerm in Ubuntu 14.04.

![chinese](https://cloud.githubusercontent.com/assets/41495/7853655/3ba74f5e-054c-11e5-8ec4-1ac659f91135.png)

**Comment by lazywei** [comment]
@Shougo How did you do that? By pasting? It's really weird ...

**Comment by lazywei** [comment]
do i need to check xterm or something?

**Comment by Shougo** [comment]
I pasted it.

@lazywei I think you should try it in other terminals.
It seems terminal specific problem.

**Comment by lazywei** [comment]
I tried it on Mac OS X built-in "Terminal.app" and get this ..
![image](https://cloud.githubusercontent.com/assets/2840571/7854089/9c3f64ae-0548-11e5-8f1a-4d3a13e06933.png)

I also tried on bot bash and zsh ... with no luck

**Comment by Shougo** [comment]
@lazywei Can you test LilyTerm?

https://github.com/Tetralet/LilyTerm

**Comment by lazywei** [comment]
I'm using Mac OS X, and I think LilyTerm can't just build on Mac ..

-- Chih-Wei (Bert)

2015-05-28 14:52 GMT+08:00 Shougo <notifications@github.com>:

**Comment by Shougo** [comment]
@lazywei The build is failed?

**Comment by Mudox** [comment]
I can type Chinese, my settings:
Mac OS X 10.10.3
iTerm2 updated nightly build edition
Neovim Version:
  NVIM 0.0.0-alpha+201505191621 (compiled May 19 2015 23:53:02)
  Commit: 5bbd182a3e02cf078e4bede693199c94943f4848
Build type: RelWithDebInfo
Input Method: Sougou Pingyin Input Method
![139692c8-3cf3-4bf5-b287-12736411f5c5](https://cloud.githubusercontent.com/assets/2283394/7857442/fde338ec-0562-11e5-81be-afe3af6e7f76.png)
maybe some of your settings is not right.

**Comment by lazywei** [comment]
OK, it turns out i should comment out this setting -- which is copying from my old vim setting:

```
try
  lang zh_TW
catch
endtry
```

Now the Chinese characters works.

Also, the ambiwidth character looks also work
![image](https://cloud.githubusercontent.com/assets/2840571/7858363/3673588e-056a-11e5-8aff-289280f33f0d.png)

**Comment by bantana** [comment]
18:51 $ locale
LANG=
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
![screen shot 2015-06-02 at 7 03 40 pm](https://cloud.githubusercontent.com/assets/1296107/7934463/3ba6770c-095a-11e5-8800-3481df387c0d.png)

18:52 $ export LANG="en_US.UTF-8"
✔ ~ 
18:53 $ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

![screen shot 2015-06-02 at 7 04 24 pm](https://cloud.githubusercontent.com/assets/1296107/7934464/3bdb6282-095a-11e5-98cd-39a4c01b78a1.png)
now i can type chinese in my neovim.
yosemite 10.10.3
NVIM 0.0.0-alpha+201505240222 (compiled May 24 2015 20:42:00)

**Comment by bfredl** [comment]
with #2469 merged, now it should work without needing to set `LANG`
