### ISSUE TITLE
nvim_get_hl documentation (or behavior?) bug in returned values

### ISSUE THREAD

**Issue by bmendric** [neovim/neovim#27524]
### Problem

Documentation for the return value of `nvim_get_hl()` states:

> Highlight groups as a map from group name to a highlight map as in nvim_set_hl(), or only a single highlight definition if requested by name or id.

Within the `vals` parameter for `nvim_set_hl()`, the documentation reads:

> • fg (or foreground): color name or "#RRGGBB", see note.
    • bg (or background): color name or "#RRGGBB", see note.

**Problem:** returned values from `nvim_get_hl()` are only indexable by  `fg` and `bg` and do not support `foreground` and `background`

I assume this is also a problem with `special` as well? -- not familiar enough with that value to adequately test and report on it

### Steps to reproduce

nvim --clean
:lua vim.api.nvim_set_hl(0, "Normal", { foreground = 1, background = 1 })
:lua print(vim.inspect(vim.api.nvim_get_hl(0, { name = "Normal" })

### Expected behavior

It's not obvious if this is a documentation problem (where the docs could be clearer on the return values of `nvim_get_hl()`) or if this is a behavior problem where we should expect the return value of `nvim_get_hl()` to be something like:

```
{
  fg = 1,
  bg = 1,
  foreground = 1,
  background = 1,
}
```

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

openSUSE Tumbleweed 20240207

### Terminal name/version

alacritty 0.13.1

### $TERM environment variable

screen-256color

### Installation

Unpacking nvim-linux64.tar.gz from GitHub Releases

**Comment by justinmk** [comment]
Try the development version.  The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS.

**Comment by clason** [comment]
Nothing has changed in this regard on master.

**Comment by zeertzjq** [comment]
@rktjmp

**Comment by rktjmp** [comment]
The long keys are supported in `nvim_set_hl` but `nvim_get_hl` always forces short keys when calling hlattrs2dict, which I think is fine. The PR pretends we dont accept the longer keys for `nvim_set_hl`.
