### ISSUE TITLE
Treesitter: Support #is-not? query predicate 

### ISSUE THREAD

**Issue by npezza93** [neovim/neovim#27521]
### Problem

Currently the #is-not? predicate is not supported by neovims treesitter implementation. When viewing the documentation for treesitters locals highlighting as seen here(https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables) it uses #is-not?. Treesitter cli also supports it.

### Expected behavior

I can use the #is-not? query inside treesitter queries.

**Comment by clason** [comment]
You can use `#not-is?`.

**Comment by npezza93** [comment]
Gotcha

> (and upstream is deprecating use for highlighting, too)
@clason Do you mind pointing to me to the issue or pr reference for this? Thanks!

**Comment by clason** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/3944#issuecomment-1458782497
