### ISSUE TITLE
E439: undo list corrupt

### ISSUE THREAD

**Issue by alalfakawma** [neovim/neovim#27531]
### Problem

![2024-02-19-111058_560x237_scrot](https://github.com/neovim/neovim/assets/25346842/5a22d909-cb32-47a6-8e4a-7075e712f33c)

Has anyone else have this issue before? I was just coding and this popped up all of a sudden, whenever I type or try to move the cursor it keeps appearing which is extremely annoying.

### Steps to reproduce

I'm not sure, it was random.

### Expected behavior

Undo file should not be corrupted

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

manjaro i3 23.1.3

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

tmux-256color

### Installation

pacman

**Comment by glepnir** [comment]
Without clean reproduction steps it is difficult to locate where the problem occurs. Please try nightly if it still appears.

> whenever I type or try to move the cursor it keeps appearing which is extremely annoying.

you can check what's callback bind on `TextChangedI CursorMoved CursorMovedI` and try to disable that plugin see what happen.  whati can tell err from `u_get_headentry` function.

**Comment by alalfakawma** [comment]
Not getting this error anymore. Not sure what fixed it, but could be an update from a plugin that i'm using or something. Closing.
