### ISSUE TITLE
BUILDING FROM SOURCE DOCUMENTATION

### ISSUE THREAD

**Issue by elementtest** [neovim/neovim#27546]
### Problem

Please Include in your "prerequisites" section under building from source that you NEED to have "sudo apt-get install build-essential" under Ubuntu and the like in order for your "cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo" instruction to work.  It throws massive errors if you dont have this in place and it DEFINITELY should be listed in the preqs section!

### Steps to reproduce

see above

### Expected behavior

see above

### Neovim version (nvim -v)

current

### Vim (not Nvim) behaves the same?

see above

### Operating system/version

above

### Terminal name/version

above

### $TERM environment variable

above

### Installation

above

**Comment by lewis6991** [comment]
Sorry we don't provide the exact instructions for every  platform.

The clue is also in the name: `build-essential`.

**Comment by dundargoc** [comment]
Added it to https://github.com/neovim/neovim/pull/27364
