### ISSUE TITLE
`g@` cancels previous operator

### ISSUE THREAD

**Issue by rish987** [neovim/neovim#27549]
### Problem

I'm trying to define a "wrapper" on text objects as a prefix that modifies the normal range/behavior of any text object. For this I am setting `vim.o.operatorfunc`, to a callback and then executing `g@` to get the text object's range. For example, here is a module `jump-textobj.lua` that defines mappings to jump to the start/end of text objects in normal mode, and which should also work as expected in operator-pending mode:
```lua
local M = {}

M._jump = function(dir)
  return function (_)
    local spos, epos = vim.api.nvim_buf_get_mark(0, '['), vim.api.nvim_buf_get_mark(0, ']')

    if vim.fn.mode():find("o") ~= nil then
      vim.cmd.normal { "v", bang = true }
    end

    if dir == "start" then
      vim.api.nvim_win_set_cursor(0, spos)
    else
      vim.api.nvim_win_set_cursor(0, epos)
    end
  end
end

M.jump = function (dir)
  vim.o.operatorfunc = ("v:lua.require'jump-textobj'._jump'%s'"):format(dir)
  vim.fn.feedkeys "g@"
end

vim.keymap.set({"n", "o"}, "<c-l>", [[<cmd>lua require"jump-textobj".jump("end")<CR>]])
vim.keymap.set({"n", "o"}, "<c-h>", [[<cmd>lua require"jump-textobj".jump("start")<CR>]])

return M

```
This only works well in normal mode. With operator-pending mode, something like `d<c-h>ap` doesn't delete until the beginning of the next paragraph, it just has the same effect as in normal mode. In this case, it seems that the "second layer" of operator-pending mode overrides the first one, so the initial `d` is forgotten and we have exited operator-pending mode by the time we enter `_jump`. If I replace the contents of `M.jump` with the contents of the inner function of `M._jump` (and fix `spos` and `epos`), it works as expected, leading me to believe that the extra layer of operator-pending mode introduced by `g@` is responsible for the issue.

I suppose this behavior may be "expected" as of now in some sense, but I think that it would be nice for operator-pending mode to "nest" operators in some way.

### Steps to reproduce

Load the module `jump-textobj.lua` above and edit the file:
```
text1
text2
text3

text4
text5
text6
```

With the cursor on "text1", do `d<c-l>ap`. Notice that the cursor jumps to the newline without deleting anything. I know this is a silly example because you could just do `d}` instead, but I couldn't find any interesting built-in text objects -- really, I wanted to use this with a plugin like [nvim-various-textobjs](https://github.com/chrisgrieser/nvim-various-textobjs).

### Expected behavior

`d<c-l>ap` should have the same effect as `d}`.

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

Yes, I think so -- I don't have vim installed and I'm not familiar enough with vimscript to test but I assume this issue originates from vim

### Operating system/version

Ubuntu 22.04.3

### Terminal name/version

Alacritty 0.13.1

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by justinmk** [comment]
> I think that it would be nice for operator-pending mode to "nest" operators in some way.

👀

**Comment by zeertzjq** [comment]
`g@` is an operator, not a motion, and you cannot you any other operators in operator-pending mode either.

**Comment by justinmk** [comment]
"nesting" implies submodes, let's file this under https://github.com/neovim/neovim/issues/16313
