### ISSUE TITLE
Pass current key to function in `vim.tbl_map` and `vim.tbl_filter`

### ISSUE THREAD

**Issue by b0o** [neovim/neovim#27543]
It's common for implementations of `map` and `filter` in other languages/libraries to pass the current key/index to the function along with the value. For example, in JavaScript:

> ### [`Array.prototype.map`](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/array/map) arguments:
>
> - callbackFn: A function to execute for each element in the array. Its return value is added as a single element in the new array. The function is called with the following arguments:
>   - `element`: The current element being processed in the array.
>   - `index`: The index of the current element being processed in the array.
>   - `array`: The array `map()` was called upon.

I've run into a few cases where having the current key would be helpful in the map callback function.

I started working on a PR for this, but adding these arguments causes unrelated tests to fail. I suppose this would be a breaking change, since it could negatively affect callback functions that aren't expecting additional arguments. Is this something you think we can add, or no?

**Comment by justinmk** [comment]
Discussed for `vim.iter` in https://github.com/neovim/neovim/issues/23251 

`tbl_map` and `tbl_filter` are being considered for deprecation: https://github.com/neovim/neovim/issues/24572

**Comment by lewis6991** [comment]
If you need both the key and the value, then I suggest you just use a regular `pairs`/`ipairs` loop. The LOC is usually similarly so I'm not sure what these additional functions are providing.
