### ISSUE TITLE
No help for nvim-python

### ISSUE THREAD

**Issue by lazywei** [neovim/neovim#2754]
Hi,

I found that when I type this in command mode
```
:help nvim-python
```

I'll get

```
Sorry, no help for nvim-python
```

I've checked that the doc is under my runtimepath, and there exists nvim_python.txt.

**Comment by fwalch** [comment]
How did you install Neovim?

**Comment by Shougo** [comment]
@lazywei You should create tags by `:helptags` command.

**Comment by lazywei** [comment]
@fwalch i build it from source with the command

```
make CMAKE_BUILD_TYPE=Release
```

@Shougo 
I will need to do that for every doc file?

**Comment by Pyrohh** [comment]
@lazywei but how do you *install* it? `[sudo] make install` should build helptags.

**Comment by lazywei** [comment]
Oh... OK, i see. I didn't install it. I only assign these two env vars
```
export VIMRUNTIME=~/Projects/neovim/runtime
export PATH=~/Projects/neovim/build/bin:$PATH
```
i didn't do `make install` because i'd like all neovim related files reside in my `~/Projects/neovim` folder. Is there any solution?

**Comment by Pyrohh** [comment]
Ah, well this might work for you.
```
$ make install DESTDIR=~/Projects/neovim
$ export PATH=$PATH:~/Projects/neovim/usr/local/bin
```
Note the `$`, as there's no need to use `sudo` to install to something in your `$HOME`.
Also please make sure to delete your existing nvim installation before you run this.

**Comment by lazywei** [comment]
@Pyrohh thanks for that!
i got one question, here is my current alias for quick build neovim:
```
# for quick build
alias qb_nvim="rm -rf build && make clean && make CMAKE_BUILD_TYPE=Release"
```

how can i modify it? like this?
```
alias qb_nvim="rm -rf build && make clean && make CMAKE_BUILD_TYPE=Release && make install DESTDIR=~/Projects/neovim"
```

**Comment by lazywei** [comment]
also, the flag `DESTDIR` looks a little different from here https://github.com/neovim/neovim/wiki/Installing-Neovim#manual-installation
is the wiki out-dated?

**Comment by Pyrohh** [comment]
I think this should work:
```
alias qb_nvim="rm -rf build && make clean &&
               make install CMAKE_BUILD_TYPE=Release DESTDIR=~/Projects/neovim"
```

> also, the flag DESTDIR looks a little different from here https://github.com/neovim/neovim/wiki/Installing-Neovim#manual-installation
> is the wiki out-dated?

Hmm, maybe you should use the flag mentioned on the wiki instead of DESTDIR. Setting a custom DESTDIR doesn't change the PREFIX, which is why I mentioned `/Projects/neovim/usr/local/bin`.

If you changed PREFIX instead, it would probably be `/Projects/neovim/bin`.
By the way, nvim doesn't even compile for me at the moment, so needless to say I haven't tested any of this just now :-)

**Comment by lazywei** [comment]
@Pyrohh it looks like NeoVim still can't find the "installed" doc (e.g. /Projects/neovim/share/). Do I need to add this path to some env vars?

**Comment by fwalch** [comment]
I guess you want to use ~/Projects... , not /Projects.

**Comment by lazywei** [comment]
@fwalch yeah, it's just the typo. My question is how to make NeoVim aware of the "installed" doc?



> Also, if applicable for your system, you can use e.g. Homebrew to install Neovim to make things easier.

I've tried Homebrew, but it doesn't use RELEASE flag, which will make NeoVim super slow with vim-airline. Also, I'd prefer build with latest commit :smile:

**Comment by fwalch** [comment]
Homebrew will use the latest commit.. And it uses RelWithDebInfo, which will compile optimizations (though not as aggressive as Release).

Anyway, if you run `make install`, it will generate the helptags at the end, which is what Neovim uses to discover the appropriate file when you execute :help. If you use CMAKE_PREFIX, the default runtime directory should be the right one and you don't need to do anything. Make sure you don't set VIMRUNTIME to point to somewhere else.

**Comment by lazywei** [comment]
@fwalch ok, after removing VIMRUNTIME from my zshrc, it works :+1: Thanks
