### ISSUE TITLE
vscode cannot use neovim !!!

### ISSUE THREAD

**Issue by Dssssds** [neovim/neovim#27557]
### Problem

1. 我在vscode 编辑器上,安装了 [vscode-neovim].  (  I installed [VScode-neovim] in the vscode editor.
 )
2. 配置了环境变量,还是无法使用.   (. Environment variables are configured, but they cannot be used. )
3. 无法启动,并且总是弹窗以下错误.   ( Can not start, and always pop-up the following error. )
4. 
![image](https://github.com/neovim/neovim/assets/17268259/a4f897c1-d8d3-471f-870a-fdfa9e83c5ed)
![image](https://github.com/neovim/neovim/assets/17268259/baddf84d-8795-4161-80c0-fd4eb2227c59)

### Steps to reproduce

[Failed to start nvim] Neovim spawn error: spawn nvim ENOENT

### Expected behavior

[Failed to start nvim] Neovim spawn error: spawn nvim ENOENT

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

9.0.2136

### Operating system/version

14.3.1 (23D60)

### Terminal name/version

iterm2

### $TERM environment variable

iterm2

### Installation

homebrew

**Comment by dundargoc** [comment]
I think this should be reported to https://github.com/vscode-neovim/vscode-neovim instead.
