### ISSUE TITLE
Bash syntax highlighting: red `)` sign in if..fi clause

### ISSUE THREAD

**Issue by mooreye** [neovim/neovim#27556]
### Problem

Create a file with contents:
```bash
a() {
    if :; then
        local v=()
    fi
}

# vim: syntax=bash
```
see that the closing `)` is highlighted red:
![2024-02-20T23:17:53,207711358+01:00](https://github.com/neovim/neovim/assets/93423596/f24b4814-f048-43e9-930f-23464c33d316)
although the syntax is correct.

The following example actions remove the red highlight:
* deleting the `local` keyword
* removing the `if` clause

### Steps to reproduce

Create a file with aforementioned content, then run `nvim --clean file`

### Expected behavior

`)` is not highlighted red

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: RelWithDebInfo LuaJIT 2.1.1692716794 Compilation: /usr/bin/gcc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DUSING_UV_SHARED=1 -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include/luv -I/builddir/build/BUILD/neovim-0.9.5/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.9.5/redhat-linux-build/include -I/builddir/build/BUILD/neovim-0.9.5/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.9.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.1 with `:syntax on`

### Operating system/version

Fedora 39

### Terminal name/version

# GNOME Terminal 3.50.1 using VTE 0.74.2 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

dnf

**Comment by zeertzjq** [comment]
This has already been fixed.
