### ISSUE TITLE
Add empty function and a frozen table to Neovim std.

### ISSUE THREAD

**Issue by abcdefg233** [neovim/neovim#27550]
### Problem

Some api requires a function parameter:
```lua
local timer=vim.uv.new_timer()
-- I believe there's more empty function define like this.
local empty_fn=function() end
--- This function needs to wait 1s for every call, otherwise it does nothing.
--- It use timer, but timer needs a callback function.
--- This is a real problem I met.
local function fn_for_second()
 if timer:is_active() then
  return
 end
 timer:start(1000,0,empty_fn)
 --- do somethings that needs to wait a second every time
end
```
And it's quite often that a empty function is needed in lua. (For keep things callable or making lua_ls annotation I assume.)

![image](https://github.com/neovim/neovim/assets/32760059/488a09af-4f1d-445f-8c62-cd079e2f95ab)

The frozen table is for the same purpose, to prevent creating empty table multiple times.
And I think it's more readable because:
```lua
fn(arg,{}) -- This {} is confuse and useless if it will never be accessed.
fn(arg,vim.empty_tbl) -- If this parameter can't be nil, use this empty_tbl will be better.
```

This is just a simple idea come out of my mind that I see multiple empty function definition and table that never be accessed, I think it's may not necessary, but will make things little better.

### Expected behavior

The lua code may seems like this.
```lua
--- Function that does nothing.
vim.empty_f=function() end
--- Table that always empty.
vim.empty_t=setmetatable({},{
 __index=vim.empty_f,
 __newindex=vim.empty_f,
})
```

**Comment by bfredl** [comment]
`function() end` is 14 bytes and self explanatory. `vim.empty_f` is three bytes shorter and has a definition which needs to be looked up. Is it really an improvement?

**Comment by bfredl** [comment]
"frozen dict" might be useful for some things but it has **nothing** to do with using `{}` as a value. there is already a natural spelling for that, which is: `{}` .

**Comment by abcdefg233** [comment]
> function() end is 14 bytes and self explanatory.

My point is to reuse same things, I know it's not a **big usage** for  memories, but it is a improve, a improve for 14 bytes like you said.

> "frozen dict" might be useful for some things but it has nothing to do with using {} as a value. there is already a natural spelling for that, which is: {} .

If it has to come with performance, I would say `{}` to create a new table is slower than `vim.empty_t` to getting a existing one, especially when this happens in a loop, and same to the `function() end`.

> Is it really an improvement?

I don't like extreme scenarios that much. But it is a improvement if the `std` itself is creating `{}` all the time. My point is about reuse although but it sure did some improve:

`test.lua`
```lua
local function testrun(fn,t,...)
 local s=os.clock()
 for _=1,t do
  fn(...)
 end
 local e=os.clock()
 return e-s
end
local t=10000000
std={}
std.empty_f=function() end
std.empty_t=setmetatable({},{
 __index=std.empty_f,
 __newindex=std.empty_f,
})
local fn1=function()
 return {}
end
local fn2=function()
 return std.empty_t
end
print(1,testrun(fn1,t)) ---
print(2,testrun(fn2,t))
```
```
~ luajit test.lua
1       0.54513
2       0.151067
```

This thing is not really necessary, but it's not useless too. In my word: "Will make things little better.".

**Comment by bfredl** [comment]
> I would say {} to create a new table is slower than vim.empty_t to getting a existing one, especially when this happens in a loop, and same to the function() end.

Sure but you can just bind this locally yourself outside the loop. Every trick in the book doesn't need to have a "name" and an official fanfare, you can just use it.
