### ISSUE TITLE
`highlight link Folded` not working

### ISSUE THREAD

**Issue by akkartik** [neovim/neovim#2756]
I'm unable to link Folded like other highlight groups.

```
$ ./build/bin/nvim --version
NVIM 0.0.0-alpha+201505271256 (compiled May 28 2015 10:34:01)
Commit: ee312ca9a4d35132059db80b13153ce71faa4ae6
Build type: Debug
...
$ ./build/bin/nvim -u NONE
```

Then, inside nvim:

```vim
:highlight clear Folded
:highlight Folded
Folded         xxx cleared
:highlight link Folded Normal
E414: group has settings, highlight link ignored
```

Works fine in vim 7.4.608.

I'll investigate further when I get a chance.

**Comment by akkartik** [comment]
Just checked with vim head at 7.4.729 and it works fine. So definitely a neovim issue. Was this maybe deliberate? I see signs that `t_Co` is now readonly and am wondering if this is some systematic cleanup:

```vim
:echo &t_Co
256
:set t_Co
E846: Key code not set: t_Co
```

**Comment by Pyrohh** [comment]
Perhaps we're missing some patches, not sure.

**Comment by splinterofchaos** [comment]
> I see signs that t_Co is now readonly and am wondering if this is some systematic cleanup:

It seems that `:let &t_Co = ###` works. `set_tty_option()` actually handles this, called by `set_option_value()`, but most calls are hardcoded.

**Comment by akkartik** [comment]
But `set t_Co=xxx` works in regular vim. Do we know why it doesn't in
neovim?

**Comment by akkartik** [comment]
(I agree that 'read only' was the wrong prognosis.)

**Comment by splinterofchaos** [comment]
It would require some investigation, but I think it may have been replaced by `$NVIM_TUI_ENABLE_TRUE_COLOR`. Setting it seems to have no effect.

**Comment by akkartik** [comment]
I think it might have been https://github.com/neovim/neovim/commit/3baba1e7bc6698e6bc9f1d37fce88b30d6274bc9. Anyway, this bug isn't about t_Co.

**Comment by justinmk** [comment]
So this issue is about this error: `E414: group has settings, highlight link ignored` ?

**Comment by akkartik** [comment]
Yes. There shouldn't be any settings left after the `highlight clear`.

**Comment by akkartik** [comment]
Confirmed that the problem still exists at HEAD.

**Comment by ggustafsson** [comment]
Still bug is still alive and well in Neovim. My color scheme broke for the exact same reason as stated here.

**Comment by watiko** [comment]
ref: #4236

Same here. d8f3458ec745cf56dc692b55cc76d8323dbbfc53 is relevant to this issue.

**Comment by akkartik** [comment]
:+1: Thanks for the investigation.
