### ISSUE TITLE
Crashes on larger files when scrolling on OpenBSD with sysctl vm.malloc_conf=S

### ISSUE THREAD

**Issue by dante-robinson** [neovim/neovim#27564]
### Problem

When setting vm.malloc_conf=S in sysctl, neovim crashes when scrolling and logs don't seem to issue any error messages it just ends the log while scrolling. The sysctl command performs extra security checks on memory functions. I have tested this on a neovim build with no plugins as well to confirm it's not a plugin issue.

### Steps to reproduce

doas sysctl vm.malloc_conf=S or set vm.malloc_conf=S in /etc/sysctl.conf and reboot.
nvim
open a large file 1000+ lines ideally
scroll up and down to see if it crashes.

### Expected behavior

Program crashes likely due to a memory issue.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

yes, vim 9.0.2035 gives error segmentation fault different error numbers each time

### Operating system/version

OpenBSD 7.4 (not current)

### Terminal name/version

alacritty 0.12.2

### $TERM environment variable

xterm-256color

### Installation

pkg (system package manager)

**Comment by zeertzjq** [comment]
Please describe steps to reproduce more precisely. What exactly is "a neovim build with no plugins"? How did you invoke Nvim?

**Comment by dante-robinson** [comment]
stock neovim is what I mean with no plugins no config etc, I ran neovim from my console running the command 'nvim'

**Comment by clason** [comment]
Try `nvim --clean` (and the latest version, 0.9.5).

**Comment by clason** [comment]
Parallel Vim issue: https://github.com/vim/vim/issues/14070

**Comment by dante-robinson** [comment]
> Try `nvim --clean` (and the latest version, 0.9.5).

The build intructions found [here](https://github.com/neovim/neovim/blob/master/BUILD.md#openbsd) don't work for me  and crashes during the gmake command at [ 40%] Performing install step for 'luarocks'

The only other way to get 0.9.5 would be to upgrade to OpenBSD -current which requires a reinstall of the system for me to come back to stable. You are more than welcome to install OpenBSD 7.4 and then upgrade to current in a vm if you wish to test that version.

**Comment by clason** [comment]
> You are more than welcome to install OpenBSD 7.4 and then upgrade to current in a vm if you wish to test that version.

_You_ are the one with a crash, so getting this fixed relies on your help. Otherwise nothing will happen (OpenBSD is not an officially supported platform.)

**Comment by justinmk** [comment]
Perhaps it's reproducible with asan? Presumably openbsd's `malloc_conf=S` enables similar things.

**Comment by dante-robinson** [comment]
> Perhaps it's reproducible with asan? Presumably openbsd's `malloc_conf=S` enables similar things.

https://man.openbsd.org/reallocarray these are the options it enables if that helps.


> > You are more than welcome to install OpenBSD 7.4 and then upgrade to current in a vm if you wish to test that version.
> 
> _You_ are the one with a crash, so getting this fixed relies on your help. Otherwise nothing will happen (OpenBSD is not an officially supported platform.)

I will have to find some free time to install an OpenBSD VM on current to test and get back to you.
