### ISSUE TITLE
need an option to disable stdin piping in jobstart

### ISSUE THREAD

**Issue by strrchr** [neovim/neovim#2757]
Some program like the_silver_searcher will check the type of stdin, like this:
```c
    rv = fstat(fileno(stdin), &statbuf);
    if (rv == 0) {
        if (S_ISFIFO(statbuf.st_mode) || S_ISREG(statbuf.st_mode)) {
            opts.search_stream = 1;
        }
    }
```
So it would be nice if there is a way to disable stdin piping in jobstart. like this in nodejs:
```js
  var spawn = require('child_process').spawn,
    ag    = spawn("ag", ["var"], { stdio: ['ignore', 'pipe', 'pipe'] });
```

**Comment by Shougo** [comment]
:+1: 

This feature is implemented in vimproc.

**Comment by splinterofchaos** [comment]
We already do this for stdout/err, so we just need an option for stdin. Please let me know if #2763 works for you.

**Comment by strrchr** [comment]
I use https://github.com/equalsraf/neovim to compile on Windows.
I merged https://github.com/splinterofchaos/neovim/tree/job-no-stdin and the compilation is ok.
Then I test ignore_stdin option of jobstart, and it works ok.
```c
S_ISFIFO(statbuf.st_mode): 0
S_ISREG(statbuf.st_mode): 0
S_ISCHR(statbuf.st_mode): 1
```
Without ignore_stdin, the output is:
```c
S_ISFIFO(statbuf.st_mode): 1
S_ISREG(statbuf.st_mode): 0
S_ISCHR(statbuf.st_mode): 0
```
