### ISSUE TITLE
`bufname` returns empty for `[Command Line]` window on master

### ISSUE THREAD

**Issue by fannheyward** [neovim/neovim#27576]
### Problem

`bufname` returns empty for `[Command Line]` window on master

### Steps to reproduce

1. use nvim nightly
2. `nvim --clean`
3. `q:` to open the command-line window
4. `:buffers`
<img width="567" alt="image" src="https://github.com/neovim/neovim/assets/345274/1b9cb69e-8777-429d-a99f-b81fa2d7b7f9">

5. `:echo bufname(2)`, empty result.

With nvim 0.9.5:

<img width="517" alt="image" src="https://github.com/neovim/neovim/assets/345274/2f0d3e69-6429-4018-ba3a-54c25db962ba">

`:echo bufname(2)` returns `[Command Line]`

### Expected behavior

Same result as nvim 0.9.5

### Neovim version (nvim -v)

v0.10.0-dev-2387+g01c15a30c-Homebrew

### Vim (not Nvim) behaves the same?

yes, 9.1.0100

### Operating system/version

macOS 14.3.1

### Terminal name/version

iTerm 3.4.23

### $TERM environment variable

xterm-256color

### Installation

brew install neovim --HEAD

**Comment by zeertzjq** [comment]
Not a bug.

**Comment by clason** [comment]
Or branch on `has('nvim-0.10')`; this makes it easier to drop the obsolete version once Nvim <0.10 is end of life.
