### ISSUE TITLE
OSC 11 request doesn't work in terminal opened by nvim_open_term

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#27587]
### Problem

OSC 11 request doesn't work in terminal opened by `nvim_open_term`. It causes an error and doesn't receive a response.

### Steps to reproduce

1. Run `nvim --clean`
2. Source the following Lua file:
```lua
_G.input = ''
local chan = vim.api.nvim_open_term(0, {
  on_input = function(_, _, _, data)
    _G.input = _G.input .. data
  end,
})
vim.api.nvim_chan_send(chan, '\027]11;?\027\\')
print(_G.input)
```
3. Error:
```
Error detected while processing TermRequest Autocommands for "*":
Error executing lua callback: vim/_defaults.lua:0: E900: Invalid channel id
stack traceback:
        [C]: in function 'nvim_chan_send'
        vim/_defaults.lua: in function <vim/_defaults.lua:0>
```

### Expected behavior

No error and `_G.input` contains an OSC response.

### Neovim version (nvim -v)

v0.10.0-dev-2427+geb4783fb6c

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by zeertzjq** [comment]
Another example that runs Nvim in a terminal opened by `nvim_open_term`:
```lua
local job

local term = vim.api.nvim_open_term(0, {
  on_input = function(_, _, _, data)
    vim.api.nvim_chan_send(job, data)
  end,
})

job = vim.fn.jobstart({ 'nvim', '--clean' }, {
  pty = true,
  on_stdout = function(_, data, _)
    vim.api.nvim_chan_send(term, table.concat(data, '\n'))
  end,
})
```

This error immediately in the default `TermRequest` autocommand when nested Nvim is launched, but after that the nested Nvim works fine.

**Comment by gpanders** [comment]
At the very least we can add a check to make sure `'channel'` is valid: https://github.com/neovim/neovim/blob/cb5ae22eab1fbb3162d0f7440a48ad49c7b3c48e/runtime/lua/vim/_defaults.lua#L160-L161

But what is the expected behavior of sending a OSC 11 request to the embedded instance? Usually it is the other way around. If `'channel'` is invalid, should it write to stdout instead?
