### ISSUE TITLE
Smooth pixel-based scrolling

### ISSUE THREAD

**Issue by NeilGirdhar** [neovim/neovim#27583]
### Problem

Some terminals (like Sakura) support _smooth pixel-based scrolling_.  Kitty may soon support it too: https://github.com/kovidgoyal/kitty/pull/1454

### Expected behavior

It would be amazing if Neovim could work with the terminal so that this occurs whenever a command scrolls, e.g.,
* ctrl-d, ctrl-u (page down and up),
* zz (rehome)
* etc.

I've noticed that the Kitty creator has in various other threads been open to providing the necessary interface for working with various applications.  So I think you could get buy-in from the terminal.

This would be a huge visual improvement for NeoVim over other text editors :smile:

**Comment by bfredl** [comment]
Is there a quick reference for exactly what escape sequences Neovim TUI need to emit in order for this to happen?

**Comment by clason** [comment]
Let's wait for a standard protocol.

 (Also, your "may support soon" is doing _a lot_ of heavy lifting here -- to the point of being misleading, as this PR has been long stalled. This doesn't help your point.)

**Comment by syyyr** [comment]
I think the "smooth scrolling" mentioned in the kitty PR refers to the ability of the terminal to react to touchpad events by the pixel instead of interpreting a certain distance scrolled as mouse scroll wheel events. This is already supported in other terminals and has nothing to do with neovim, it's about how the terminal interprets mouse events.

**Comment by zeertzjq** [comment]
> I've noticed that the Kitty creator has in various other threads been open to providing the necessary interface for working with various applications.

What threads? What interface?

**Comment by NeilGirdhar** [comment]
> Is there a quick reference for exactly what escape sequences Neovim TUI need to emit in order for this to happen?

AFAIK they don't exist yet :smile: 

> Let's wait for a standard protocol.

Fair enough.  But the motivation to create a standard protocol comes from potential users.  Just a show of interest on the NeoVim side might be helpful?

> (Also, your "may support soon" is doing a lot of heavy lifting here -- to the point of being misleading, as this PR has been long stalled. This doesn't help your point.)

Sorry I wasn't trying to mislead anyone.  Maybe I'm a bit too optimistic.

> tty PR refers to the ability of the terminal to react to touchpad scroll events by the pixel instead of interpreting a certain distance scrolled as mouse scroll wheel events. 

The vim use-case is mentioned in the comments.  The touchpad scrolling is simply another use case.  There are multiple use-cases for that feature.

> What threads? What interface?

I just read a bunch of threads recently.  I think it was in some long discussion with the vim people regarding some terminal-vim interaction weirdness.  He seemed quite open to creating various protocols to suit vim's needs.

**Comment by syyyr** [comment]
What I meant to say is that there's nothing that needs to be done from neovim's side - sure, scrolling in neovim is a usecase, but if neovim doesn't have to implement anything, why open an issue here?

**Comment by alba4k** [comment]
The pr you mention for kitty is 5 years old...

**Comment by zeertzjq** [comment]
I can see that something may indeed need to be done on Nvim's side if such a protocol exists: for smooth scrolling, it's necessary to send off-screen content to the terminal before sending scroll events.

**Comment by syyyr** [comment]
I guess pixel based scrolling also means the ability to basically only show a part of some line. Indeed, neovim would have add some support for this. It looks to me that the PR implements both of the "meanings", and that's why I was confused.

**Comment by clason** [comment]
This is indeed too optimistic. Please open a new issue if _and when_ a standard protocol is available we can consider implementing. Otherwise this is a generic and unactionable "letter to Santa" that just clutters the issue tracker.

**Comment by theherk** [comment]
With no intent to necrobump and recognizing there is no work to be done here yet, I wanted to express for posterity that there is other interest in this topic. For starters, there is talk about this in the ghostty test community, and I think they have a pretty good shot at it. Also wez/wezterm#3812 and contour-terminal/contour#145. Yes these issues are old and there is probably not much work happening on it right now, but I think there are many people that see the value in this level of continuity when reading and are champing at the bit to use this feature.

**Comment by clason** [comment]
I'm aware of the ghostty discussion; note that this is about handling this on the _terminal_ level (which is the correct level AFAIAC).
