### ISSUE TITLE
Add set-related digraphs which have a meaning in Julia's standard library

### ISSUE THREAD

**Issue by lverweijen** [neovim/neovim#27597]
### Problem

The Julia programming language and its Base library make use of Unicode. Most of these unicode symbols can be typed in (Neo)vim using digraphs and plugins such as [unicode](https://github.com/chrisbra/unicode.vim) leverage this. However, a few symbols are missing, notably those operating on sets.

Although it's possible to solve this using configuration, I was wondering if perhaps a default should be available. The reason is that Julia is getting more and more popular, so good support out of the box would be helpful. The original list of digraphs seems to be based on [RFC 1345](https://www.rfc-editor.org/rfc/rfc1345), but this list is no longer updated. However, Vim has already made some changes on its own by e.g. adding the euro-symbol.

Here are a few symbols on sets which are already present:

| Existing symbol | Existing Digraph |
|-|-|
| ∈ | `(-` |
| ∋ | `)-` |
| ⊂ | `(=` |
| ⊃ | `)=` |
| ⊆ | `(_` |
| ⊇ | `)_` |

### Expected behavior

Below are the set symbols which are missing, but have a meaning in Julia. I don't know if trigraphs are possible. So I have included default suggestions both for digraphs and trigraphs. The problems with digraphs are that one might eventually run out digraph combinations, no longer has good digraphs available for new symbols and that certain combinations are more difficult to memorize. This might not be a problem for now, but it's good to keep this in mind. I also noticed that `!` is very common for digraphs related to mathematical symbols that have a strikethrough element.

| Missing symbol | Proposed digraph | Proposed trigraph | Meaning |
|-|-|-|-|
| [∉](https://docs.julialang.org/en/v1/base/collections/#Base.:%E2%88%89) | `[-` | `!(-` | Not an element of |
| [∌](https://docs.julialang.org/en/v1/base/collections/#Base.:%E2%88%89) | `]-` | `!)-` | Doesn't contain element |
| [⊊](https://docs.julialang.org/en/v1/base/collections/#Base.:%E2%8A%8A) | `[=` | `!(=` | Proper subset of |
| [⊋](https://docs.julialang.org/en/v1/base/collections/#Base.:%E2%8A%8A) | `]=` | `!)=` | Proper superset of |
| [⊈](https://docs.julialang.org/en/v1/base/collections/#Base.:%E2%8A%88) | `[_` | `!(_` | Not a subset |
| [⊉](https://docs.julialang.org/en/v1/base/collections/#Base.:%E2%8A%88) | `]_` | `!)_` | Not a superset |

The optional extension to trigraphs might have some relation to this ticket: https://github.com/neovim/neovim/issues/22978
It is also related to this discussion: https://github.com/JuliaEditorSupport/julia-vim/issues/309

**Comment by clason** [comment]
We don't maintain these legacy features; please raise the issue (or -- better -- make a PR) at vim/vim; if they implement it, we'll port it.

**Comment by clason** [comment]
(And you know that you -- or indeed a plugin -- can always define your own digraphs?)
