### ISSUE TITLE
vim.treesitter: attempt to call method 'range' (a nil value)

### ISSUE THREAD

**Issue by mathjiajia** [neovim/neovim#27591]
### Problem

```
E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:182: attempt to call method 'range' (a nil value)                             
stack traceback:                                                                                                                                              
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:182: in function 'get_range'                                                                     
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:217: in function 'get_node_text'                                                                 
        [string ":lua"]:1: in main chunk 
```

### Steps to reproduce

save the following Lua code as `repro.lua`.
1. `nvim -u repro.lua repro.lua` (waiting the Lua parser to be installed);
2. press `q` to quit `lazy`;
3. press `:` to enter the command mode;
4. `=vim.treesitter.get_node_text("content",0)`

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",

	-- add any other plugins here
	{
		"nvim-treesitter/nvim-treesitter",
		main = "nvim-treesitter.configs",
		build = ":TSUpdate",
		opts = { auto_install = true },
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Expected behavior

no error

### Neovim version (nvim -v)

NVIM v0.10.0-dev-7e00879

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 14.3.1

### Terminal name/version

kitty 0.32.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by clason** [comment]
You're using the function wrong: the argument needs to be an actual node (i.e., a `TSNode` userdata structure), not a string.

**Comment by mathjiajia** [comment]
> TSNode

could you give me a concrete example?
as I encountered this bug in another place, not easy to copy here.

**Comment by clason** [comment]
`:h TSNode`

**Comment by mathjiajia** [comment]
in fact, I am trying to use this following code for `vim.treesitter.query.add_directive("set-pairs!", setpairs, { force = true, all = true })`, and get that error repeatedly.
```
local function setpairs(match, _, source, pred, metadata)
	-- (#set-pairs! @aa key list)
	local capture_id = pred[2]
	local node = match[capture_id]
	local key = pred[3]
	if not node then
		return
	end
	local node_text = vim.treesitter.get_node_text(node, source)
	for i = 4, #pred, 2 do
		if node_text == pred[i] then
			metadata[key] = pred[i + 1]
			break
		end
	end
end
```

**Comment by clason** [comment]
On nightly? If you follow HEAD, then you must read `:h news` to follow and adapt to breaking changes.

**Comment by clason** [comment]
https://github.com/neovim/neovim/pull/24738

**Comment by gpanders** [comment]
> in fact, I am trying to use this following code for `vim.treesitter.query.add_directive("set-pairs!", setpairs, { force = true, all = true })`, and get that error repeatedly.
> 
> ```lua
> local function setpairs(match, _, source, pred, metadata)
> 	-- (#set-pairs! @aa key list)
> 	local capture_id = pred[2]
> 	local node = match[capture_id]
> 	local key = pred[3]
> 	if not node then
> 		return
> 	end
> 	local node_text = vim.treesitter.get_node_text(node, source)
> 	for i = 4, #pred, 2 do
> 		if node_text == pred[i] then
> 			metadata[key] = pred[i + 1]
> 			break
> 		end
> 	end
> end
> ```

You’re setting `all = true` and then not implementing the directive correctly (`match[capture_id]` is not a `node` but rather a list of `node`s). Please re-read and double check the appropriate docs. If you find that the docs are missing information or incorrect, please let me know.

**Comment by mathjiajia** [comment]
thanks. It solved my issue.
