### ISSUE TITLE
Neovim default settings.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#276]
The thing that scares off people trying out `vim` for the first time (going off of my real-world experiences) is the fact that it comes with default settings that are horrible (e.g. no syntax highlight, no numbers, etc).

In modern times, most people expect basic things like syntax highlight, line numbers, etc.

A project like this one should set some defaults that most people nowadays will end up enabling anyways, and that will attract new users trying the editor for the first time. The following would be good defaults:

* Syntax highlight enabled with a nice and dark colorscheme.
* Line numbers enabled (Mine toggles between relative numbering in NORMAL mode and regular numbering in INSERT mode automatically).
* Search highlight enabled: `set hlsearch`.
* A way to turn off the search highlight easily (I use <c-c> while in NORMAL mode to toggle it on or off).
* ~~Tabs (the "tabline" as it's called in `vim`): `set tabline=2`~~
* A nice status line. ([vim-airline](https://github.com/bling/vim-airline)?)
* Mouse support enabled: `if has('mouse') | set mouse=a | endif`
* Arrow key support in all modes enabled by default (new users will need this is you wish to keep as many as possible, but I believe they will naturally transition to the home row when they learn how convenient it is, and veteran users will feel right at home without even touching the arrow keys anyways).

That's just a basic list of the top of my head. I'll look at my vimrc later to see if there's any more.

**Defaults based on the comments below:**
* ~~Rename "tabs" something else like "spaces" or "views"?~~
* Absolute line numbering: `set number`
* backspace through lines: `set backspace=indent,eol,start`
* Automatic indentation: `filetype plugin indent on`
* Enabled matching of HTML tags, etc, with `%`: `runtime! macros/matchit.vim`
* Updated filetype plugins for indentation, folding and omni-complete:
  * [JavaScript](https://github.com/pangloss/vim-javascript)
* ~~vim-airline~~
* A built in plugin manager
  * [NeoBundle](Tabs are just not the same thing.)?
  * a way to explore community plugins (e.g. view newest, most downloaded, etc)
* Change *Y* to yank to end of line (`map Y y$`)
* `incsearch`
* `wildmode`: list:longest
* Include editorconfig plugin
* Smart <home> key goes first to the first non-white-space character, then to beginning of line, and alternates thereafter.

**Comment by justinmk** [comment]
closing for #1664
