### ISSUE TITLE
The language server is either not installed, missing from PATH, or not executable.

### ISSUE THREAD

**Issue by s1mp7e** [neovim/neovim#27602]
### Problem

Does not work with servers installed via npm. But it works fine with servers installed through the system package manager. The server installation path is "/usr/bin". The servers work if you run them in the terminal command line. But Neovim doesn't want to see them.

### Steps to reproduce using "nvim -u minimal_init.lua"

-- Setup language servers.
local lspconfig = require('lspconfig')

-- Set up lspconfig.
local capabilities = require('cmp_nvim_lsp').default_capabilities()
lspconfig.pyright.setup {capabilities = capabilities}

-- Global mappings.
-- See `:help vim.diagnostic.*` for documentation on any of the below functions
vim.keymap.set('n', '<space>e', vim.diagnostic.open_float)
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev)
vim.keymap.set('n', ']d', vim.diagnostic.goto_next)
vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist)

-- Use LspAttach autocommand to only map the following keys
-- after the language server attaches to the current buffer
vim.api.nvim_create_autocmd('LspAttach', {
  group = vim.api.nvim_create_augroup('UserLspConfig', {}),
  callback = function(ev)
    -- Enable completion triggered by <c-x><c-o>
    vim.bo[ev.buf].omnifunc = 'v:lua.vim.lsp.omnifunc'

    -- Buffer local mappings.
    -- See `:help vim.lsp.*` for documentation on any of the below functions
    local opts = { buffer = ev.buf }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
    vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
    vim.keymap.set('n', '<space>wl', function()
      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, opts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
    vim.keymap.set({ 'n', 'v' }, '<space>ca', vim.lsp.buf.code_action, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<space>f', function()
      vim.lsp.buf.format { async = true }
    end, opts)
  end,
})

### Neovim version (nvim -v)

0.9.5

### Language server name/version

pyright/1.1.351 

### Operating system/version

termux/0.118.0

**Comment by clason** [comment]
Please open this issue at nvim-lspconfig.

**Comment by jrop** [comment]
@clason  This should be reopened. I get the same error when attempting to start the LSP _without_ lspconfig. Notably I'm getting this error in Termux where I hadn't previously (this started happening after upgrading to nvim 0.10):

```
....termux/files/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:800: Spawning la
nguage server with cmd: `{ "vtsls", "--stdio" }` failed. The language server
 is either not installed, missing from PATH, or not executable.
```
