### ISSUE TITLE
Delay When Closing `:terminal` Window

### ISSUE THREAD

**Issue by mesbahamin** [neovim/neovim#27615]
### Problem

- When exiting a shell in a terminal buffer hosted by Neovim on Windows, there is a 4 second delay before the shell process exits.
- The delay seems to be equal to the value of `updatetime`, but only within a certain range of values. Setting `updatetime` to `1`, for example, results in an even longer delay.

I have seen this issue mentioned in a stack exchange post, but found no bug report for it.

- [Delay When Closing `:terminal` Window](https://vi.stackexchange.com/questions/42796/delay-when-closing-terminal-window)

Why I care: I believe this is the root cause of a number of terminal-based plugins exhibiting 4 second pauses during normal use under Neovim on Windows.

### Versions

This was reproduced under the following versions:

https://github.com/neovim/neovim/releases/tag/v0.9.5:

```
nvim.exe -v
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

`71384129f75462f14344df236cf0a22b83da4f4c` built locally with Visual Studio:

```
nvim.exe -v
NVIM v0.10.0-dev-2441+g71384129f
Build type: Debug
LuaJIT 2.1.1707061634
Run "nvim -V1 -v" for more info
```

### Steps to reproduce

1. `nvim --clean`
2. Open terminal: `:terminal`
3. Enter insert mode in terminal: `i`
4. Type "exit" command in terminal: `exit`
5. Press enter key.
6. Wait 4 seconds.
7. See `[Process exited 0]`.
8. Lower update time from default of 4 seconds to 1 second: `:set updatetime=1000`.
9. Do steps 1 through 5 again.
10. Wait 1 second.
11. See `[Process exited 0]`.

### Expected behavior

- Reproduction step 6 expectation: "Wait 0 seconds".
- Reproduction step 10 expectation: "Wait 0 seconds".

Essentially I expect there to be no delay between submitting the `exit` command to the shell and the shell process exiting.

Any of the following alternative activities exhibit the expected behavior:

- Starting a shell in a terminal outside of Neovim exhibits the expected behavior.
- Going through the reproduction steps in Neovim on Linux exhibits the expected behavior.
- Going through the reproduction steps (with `:terminal` replaced by `:term`) in the latest Vim release (mentioned below).

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2441+g71384129f commit 71384129f75462f14344df236cf0a22b83da4f4c

### Vim (not Nvim) behaves the same?

no (substituting `:term` for `:terminal`), 9.1.104

### Operating system/version

Windows 10 Pro 22H2 19045.4046

### Terminal name/version

Windows Command Prompt

### $TERM environment variable

`TERM` is absent from environment. Nvim is being run from Windows Command Prompt

### Installation

Built with Visual Studio from latest master commit.

**Comment by zeertzjq** [comment]
I've noticed this in some tests before. Some terminal tests last 4 seconds on Windows.

**Comment by Daydreamer-riri** [comment]
Hi @zeertzjq, I still encounter this issue (though not as exaggerated as 4 seconds, it's still noticeable), which results in a poor experience with terminal plugins for file navigation (such as fzf-lua, yazi.nvim). The problem manifests as a delay before jumping to the selected file, as shown in the video:

https://github.com/user-attachments/assets/9912ebee-8c76-4702-8160-dd73fe02d811

Here is the effect of the same configuration in my WSL:


https://github.com/user-attachments/assets/ebb2d432-0324-4f28-909f-4efa5e746e14

In WSL, there is no delay when switching files, whereas in Windows, there is a noticeable delay, sometimes close to one second. The same issue occurs with all terminals within nvim, such as fzf-lua, lazygit, and the terminal emulator inside nvim, where delays appear when closing them.

**Comment by Daydreamer-riri** [comment]
Should I open a new issue?

**Comment by zeertzjq** [comment]
Yes
