### ISSUE TITLE
`vim.opt.guicursor = "a:HIDDEN"` produces extra characters "ff" when entering command mode

### ISSUE THREAD

**Issue by gennaro-tedesco** [neovim/neovim#27611]
### Problem

When entering command mode `:` extra characters "ff" show if the following options are active:
```lua
vim.api.nvim_set_hl(0, "HIDDEN", { blend = 100, nocombine = true })
vim.opt.guicursor = "a:HIDDEN"
```
This issue was initially discussed [here](https://github.com/folke/noice.nvim/issues/671) and it seems it is to be addressed to neovim core itself.

### Steps to reproduce

nvim --clean
```lua
vim.api.nvim_set_hl(0, "HIDDEN", { blend = 100, nocombine = true })
vim.opt.guicursor = "a:HIDDEN"
```
produces the flickering effect `ff` as per recording below:

https://github.com/neovim/neovim/assets/15387611/ac41e8f6-e0f0-44b6-8844-6c067e028d6c

### Expected behavior

No extra "ff" appear.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2433+g9418381cc

### Vim (not Nvim) behaves the same?

no, only on nightly

### Operating system/version

MacOs Monterey 12.7

### Terminal name/version

iTerm2 (Version 3.4.23)

### $TERM environment variable

TERM=xterm-256color

### Installation

building from source

**Comment by ssh352** [comment]
same issue here when I use Lazyvim with neovim HEAD. 0.9.5 has no such issue.

**Comment by ssh352** [comment]
> same issue here when I use Lazyvim with neovim HEAD. 0.9.5 has no such issue.

https://www.lazyvim.org/installation

install a fresh lazy vim, then : to enter command mode. This will produce ff.  Neovim is at latest HEAD 970b60aa7c899851973285f9b33f5f49cae55f76
