### ISSUE TITLE
error: [Errno 25] Inappropriate ioctl for device on executing shell command

### ISSUE THREAD

**Issue by agauniyal** [neovim/neovim#2761]
To reporduce : Type `:! cppman string` (you might need cppman) or press `<Shift-k>` to acess man page over a code.

Error : In case of manually typing `:! cppman iostream` , following shows up 

```
error: [Errno 25] Inappropriate ioctl for device
```

and in case of pressing `<Shift-k>` over a piece of code , nothing happens , niether error is shown.

While in vim , both scenarios open the correct man page.
Also note , you'll have to modify your `.vimrc/.nvimrc` with `autocmd FileType cpp set keywordprg=cppman` to use `<Shift-k>`.

**Comment by agauniyal** [comment]
https://asciinema.org/a/7hozn2r647mftw39t9wshatbd

**Comment by jszakmeister** [comment]
I'm pretty certain this is because the system() call in Neovim is no longer attached to a terminal, but a pipe instead.  #1044 is similar in nature, but I think there are a few other tickets that describe this problem too.

**Comment by justinmk** [comment]
Right, this is what `:term` was created for.

    :term cppman iostream

This was a compromise that we made.

**Comment by agauniyal** [comment]
So shouldn't you guys fix ```Shift + K``` behaviour? and change it to ```:term man``` from ```:! man```

**Comment by justinmk** [comment]
@agauniyal `K` already works. I don't see anything in the core runtime files that is setting `cppman`, so there's not much we can do if your vimrc or a plugin is setting that. Correct me if I'm wrong.

**Comment by justinmk** [comment]
Oh, right. We should use `:term` if `set keywordprg=cppman` is used. We need this even for `set keywordprg=man`.

**Comment by justinmk** [comment]
In the meantime you can work around it like this (notice the `:` immediately following the `=`):

    :set keywordprg=:term\ cppman

**Comment by weichm** [comment]
How do you open cppman in another window, e.g. the preview-window?
`:set keywordprg=:ped\ +term\ cppman`
is not working

**Comment by agauniyal** [comment]
No idea, but you can take a look at [zeal](https://github.com/zealdocs/zeal).
