### ISSUE TITLE
Tilda Shortcut Support on Windows

### ISSUE THREAD

**Issue by Rdna123** [neovim/neovim#27624]
### Problem

```nvim ~\AppData\Local\nvim\init.lua```
opens a file at .\~\AppData\Local\nvim\init.lua in the working directory

### Expected behavior

It should open the nvim init file

**Comment by clason** [comment]
The shell is responsible for expanding arguments, not Neovim.

**Comment by Rdna123** [comment]
but the cd commands works as expected on windows

**Comment by clason** [comment]
Then the cd command is handling that, not the shell.
