### ISSUE TITLE
Problem with scrolling with "j" or "k" keys when the text is in Cyrillic

### ISSUE THREAD

**Issue by lvim-tech** [neovim/neovim#27622]
### Problem

The NeoVim crashes when continuously scrolling with "j" or "k" keys when the text is in Cyrillic.

### Steps to reproduce

nvim --clean
write text in Cyrillic
scroll with "j" or "k" (continuously)
neovim/src/nvim/grid.c:636: grid_put_linebuf: Assertion `0 <= row && row < grid->rows' failed.

### Expected behavior

NeoVim does not crash.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2195+gd4bd6b1ea Build type: RelWithDebInfo LuaJIT 2.1.1706185428

### Vim (not Nvim) behaves the same?

no

### Operating system/version

openSUSE Tumbleweed

### Terminal name/version

kitty 0.32.2

### $TERM environment variable

256

### Installation

From repo

**Comment by zeertzjq** [comment]
Please attach the buffer text as a file.

**Comment by zeertzjq** [comment]
Please provide the buffer text as a code block or an attached file and the size of the kitty terminal (e.g. printed by running `stty -a` in kitty).

**Comment by lvim-tech** [comment]
Лорем ипсум долор сит амет, усу волумус инвидунт еа. Еос агам долоре пхилосопхиа те, те ест синт алияуип адолесценс, ид волумус оцурререт сед. Вим сумо платонем ут, омнис ехплицари сит но. При но яуодси рецусабо елаборарет. Цу ириуре инцидеринт мел, аугуе лудус солеат про еи. Лаборе инцоррупте ад вел. Омнис омнес нолуиссе меа.

Лорем ипсум долор сит амет, усу волумус инвидунт еа. Еос агам долоре пхилосопхиа те, те ест синт алияуип адолесценс, ид волумус оцурререт сед. Вим сумо платонем ут, омнис ехплицари сит но. При но яуодси рецусабо елаборарет. Цу ириуре инцидеринт мел, аугуе лудус солеат про еи. Лаборе инцоррупте ад вел. Омнис омнес нолуиссе меа.

x20

**Comment by zeertzjq** [comment]
> x20

Is that the width or height of the kitty terminal? Please provide both. Or, what does `set lines? columns?` print in Nvim?

**Comment by lvim-tech** [comment]
x20 - the number of paragraphs
only lines

**Comment by clason** [comment]
Please answer the question:

> hat does `:set lines? columns?` print in Nvim?

**Comment by lvim-tech** [comment]
lines=53
columns=82

**Comment by zeertzjq** [comment]
Cannot reproduce. The steps to reproduce seem incomplete (e.g. doesn't mention 'number').
