### ISSUE TITLE
Assertion to_scroll >= 0 failed

### ISSUE THREAD

**Issue by theoparis** [neovim/neovim#27638]
### Problem

See https://asciinema.org/a/643221

I got this with the latest nightly commit and it seems to only happen with small tmux panes. 

### Steps to reproduce

Build the latest nightly with `make -j12` and run it in a small tmux pane. It might be plugin-specific but I have no idea how to find out what plugin is causing this since nvim just dies before I can do anything.

### Expected behavior

Neovim opens fine

### Neovim version (nvim -v)

NVIM v0.10.0-dev-a554bb3-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux theo-xps159500 6.6.15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.15-2 (2024-02-04) x86_64 GNU/Linux

### Terminal name/version

foot

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
Can you `git bisect` to find what commit caused this?

**Comment by theoparis** [comment]
I'm not sure how to use git bisect entirely yet, but it seems like I need a good commit to verify against. The problem is I don't have a good commit. 0.9 has the same issue.

**Comment by justinmk** [comment]
This doesn't have any more info than the existing https://github.com/neovim/neovim/issues/21056
