### ISSUE TITLE
Expose LSP _watchfiles exclude_pattern

### ISSUE THREAD

**Issue by alex-ds13** [neovim/neovim#27646]
### Problem

Currently only the `.git`, `node_modules` and `.hg` folders are being excluded from the watch files that LSP checks. This exclude_pattern could be exposed to the user so that other folders could be excluded, for example when attaching a client.

This was commented already on the PR #23500:

            @folke I wonder if exposing a variable like this would make it possible to exclude additional patterns per language, like `target` for rust.

_Originally posted by @nojnhuh in https://github.com/neovim/neovim/pull/23500#discussion_r1222310377_
            
From my experience, when working with rust, if we have cargo building or even sometimes when running an executable from the `target` folder, neovim complains with EPERM errors like this:
```
Error executing luv callback:
...\neovim\nvim-win64\share\nvim\runtime/lua/vim/_watch.lua:68: EPERM: operation not permitted: c:/Projects/Other/Rust/b
udgetLookup/target/release/deps/libunicode_ident-1737a7a6bd2cc11e.rlib.temp-archive-536a548.a
stack traceback:
        [C]: in function 'assert'
        ...\neovim\nvim-win64\share\nvim\runtime/lua/vim/_watch.lua:68: in function <...\neovim\nvim-win64\share\nvim\ru
ntime/lua/vim/_watch.lua:55>
Press ENTER or type command to continue
Error executing luv callback:
...\neovim\nvim-win64\share\nvim\runtime/lua/vim/_watch.lua:68: EPERM: operation not permitted: c:/Projects/Other/Rust/b
udgetLookup/target/release/deps/libunicode_ident-1737a7a6bd2cc11e.rlib.temp-archive-536a548.a
stack traceback:
        [C]: in function 'assert'
        ...\neovim\nvim-win64\share\nvim\runtime/lua/vim/_watch.lua:68: in function <...\neovim\nvim-win64\share\nvim\ru
ntime/lua/vim/_watch.lua:55>
Press ENTER or type command to continue
```
This errors keep showing all the time and I can't seem to find a way to stop them. If I could add the `target` folder to the `exclude_pattern` of watchfiles on the `on_attach` function of the rust-analyzer lsp it could probably fix this.

This is related to rust, but it could help on other situations of other LSPs, like the problem with the `.venv` folders of python mentioned on the PR above.

If someone knows if there is another way of fixing this without exposing this to the user, please tell me.

### Expected behavior

The expected behavior would be no errors of `EPERM` should show for files under `target` folder or any other folder that the LSP shouldn't be watching.

**Comment by alex-ds13** [comment]
So I've tested this with other projects where `rust-analyzer` is not registering any `target` folder as a watcher and this potential fix still doesn't work.

The reason is that on Windows and Mac it is using the `watch` function of the `_watch.lua` file, but on Linux it uses the `poll` function which then calls the `recurse_watch` function. The problem is that the `watch` function completely ignores the `include_pattern` and `exclude_pattern` from the `opts`. Only the `recurse_watch` function actually considers these options.

I've tried adding the check on the `watch` function as well and that actually fixed it for me. Even if I don't add the `+ glob.to_lpeg('**/target/**')` to the `M._poll_exclude_pattern` because now it will only watch the folders that match the `include_pattern` but I'm not entirely sure if that is the intended purpose.

<details>

<summary>Here is the fix I used:</summary>

```lua
--- Initializes and starts a |uv_fs_event_t|
---
---@param path (string) The path to watch
---@param opts (table|nil) Additional options
---     - uvflags (table|nil)
---                Same flags as accepted by |uv.fs_event_start()|
---@param callback (function) The function called when new events
---@return (function) Stops the watcher
function M.watch(path, opts, callback)
  vim.validate({
    path = { path, 'string', false },
    opts = { opts, 'table', true },
    callback = { callback, 'function', false },
  })
  opts = opts or {}

  local function is_included(filepath)
    return opts.include_pattern and opts.include_pattern:match(filepath)
  end
  local function is_excluded(filepath)
    return opts.exclude_pattern and opts.exclude_pattern:match(filepath)
  end

  path = vim.fs.normalize(path)
  if not is_excluded(path) then
    local uvflags = opts and opts.uvflags or {}
    local handle, new_err = vim.uv.new_fs_event()
    assert(not new_err, new_err)
    handle = assert(handle)
    local _, start_err = handle:start(path, uvflags, function(err, filename, events)
      assert(not err, err)
      local fullpath = path
      if filename then
        filename = filename:gsub('\\', '/')
        fullpath = filepath_join(fullpath, filename)
      end
      if is_included(fullpath) and not is_excluded(path) then
        local change_type = events.change and M.FileChangeType.Changed or 0
        if events.rename then
          local _, staterr, staterrname = vim.uv.fs_stat(fullpath)
          if staterrname == 'ENOENT' then
            change_type = M.FileChangeType.Deleted
          else
            assert(not staterr, staterr)
            change_type = M.FileChangeType.Created
          end
        end
        callback(fullpath, change_type)
      end
    end)
    assert(not start_err, start_err)
    return function()
      stop(handle)
    end
  end
  return function () end
end
```
</details>

**Comment by lewis6991** [comment]
Does https://github.com/neovim/neovim/pull/27347 help at all?

**Comment by alex-ds13** [comment]
> Does #27347 help at all?

That does seem to fix it! No more `EPERM` errors showing up so far.

By the way as a side note, do you happen to know why is it that when I build neovim on windows it doesn't create the `share` folder inside `build`? I have to manually copy the one from the nightly release and change the `runtime` folder to the one from my branch.

**Comment by lewis6991** [comment]
> That does seem to fix it! No more EPERM errors showing up so far.

Good to hear. Is this with our without fswatch installed?

> By the way as a side note, do you happen to know why is it that when I build neovim on windows it doesn't create the share folder inside build? I have to manually copy the one from the nightly release and change the runtime folder to the one from my branch.

Sorry, no idea.

**Comment by alex-ds13** [comment]
> Good to hear. Is this with our without fswatch installed?

I'm on windows, so no fswatch. It's using the `watch` function with `uv.new_fs_event()`.

**Comment by lewis6991** [comment]
Ok great.

That PR has a flaky test, but I'll just disable that and push it through.

**Comment by alex-ds13** [comment]
@lewis6991 Should I close this issue since #27347 has been merged and it fixes the issues I was having?

It seems that for now there is no need to expose the `exclude_pattern` to the user or do you think it might still be needed if the issues mentioned on #23291 continue to exist?

**Comment by melMass** [comment]
Sorry to comment on a closed issue but I'm experiencing this exact issue on current nightly / windows and wanted to know how to exclude patterns (`target` like alex) from watch, each time I cargo build from within nvim, I get a lot of these:

```sh
Error executing luv callback:
C:/Users/User/neovim/share/nvim/runtime/lua/vim/_watch.lua:90: EPERM: operation not permitted: C:/Users/User/dev/melmass/nuon-py/target/debug/deps/libpyo3_build_config-487a5fba5ec82b3d.rlib.temp-archive-47f93a4.a
stack traceback:
        [C]: in function 'assert'
        C:/Users/User/neovim/share/nvim/runtime/lua/vim/_watch.lua:90: in function <C:/Users/User/neovim/share/nvim/runtime/lua/vim/_watch.lua:72>
        
Error executing luv callback:
C:/Users/User/neovim/share/nvim/runtime/lua/vim/_watch.lua:90: EPERM: operation not permitted: C:/Users/User/dev/melmass/nuon-py/target/debug/deps/libpyo3_macros_backend-8a062a1cea69b350.rlib.temp-archive-99174ff.a
stack traceback:
        [C]: in function 'assert'
        C:/Users/User/neovim/share/nvim/runtime/lua/vim/_watch.lua:90: in function <C:/Users/User/neovim/share/nvim/runtime/lua/vim/_watch.lua:72>
        
```

**Comment by lewis6991** [comment]
Need a new issue with reproduction steps.

**Comment by brycepg** [comment]
Here with the same issue:

```
Error executing luv callback:                                                                                                                                                                                    ...pps/neovim/current/share/nvim/runtime/lua/vim/_watch.lua:90: EPERM: operation not permitted: c:/Users/Bryce/.persist_cache/acea4bdabe6b319732/923a8b7c614a3c591525864cd53cec38344.msgpack.lock      stack traceback:                                                                                                                                                                                                         [C]: in function 'assert'                                                                                                                                                                                        ...pps/neovim/current/share/nvim/runtime/lua/vim/_watch.lua:90: in function <...pps/neovim/current/share/nvim/runtime/lua/vim/_watch.lua:72>                                                             
```
