### ISSUE TITLE
Building From Source Error with luajit

### ISSUE THREAD

**Issue by boodledot1** [neovim/neovim#27649]
### Problem

mkdir -p build
touch build/.ran-deps-cmake
ninja -C .deps
ninja: Entering directory `.deps'
[1/18] Performing install step for 'luajit'
FAILED: build/src/luajit-stamp/luajit-install 
cd /home/hosts/neovim/.deps/build/src/luajit && /usr/bin/gmake -j CFLAGS=-fPIC CFLAGS+=-DLUA_USE_APICHECK CFLAGS+=-funwind-tables CCDEBUG+=-g Q= CC=/usr/bin/cc PREFIX=/home/hosts/neovim/.deps/usr install && /usr/bin/cmake -E touch /home/hosts/neovim/.deps/build/src/luajit-stamp/luajit-install
gmake[1]: Entering directory '/home/hosts/neovim/.deps/build/src/luajit'
==== Building LuaJIT 2.1 ====
/usr/bin/gmake -C src
gmake[2]: Entering directory '/home/hosts/neovim/.deps/build/src/luajit/src'
LINK      luajit
/usr/bin/cc -g  -Wl,-E   -o luajit luajit.o libluajit.a -lm -ldl  
/usr/bin/ld: libluajit.a(lj_str.o): in function `lj_str_alloc':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_str.c:289: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_str.o): in function `lj_str_init':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_str.c:367: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_state.o): in function `lua_newstate':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_state.c:247: undefined reference to `lj_prng_seed_secure'
/usr/bin/ld: libluajit.a(lj_api.o): in function `cpcall':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_api.c:1163: undefined reference to `lj_lightud_intern'
/usr/bin/ld: libluajit.a(lj_api.o): in function `lua_pushlightuserdata':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_api.c:718: undefined reference to `lj_lightud_intern'
/usr/bin/ld: libluajit.a(lj_api.o): in function `lua_newuserdata':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_api.c:770: undefined reference to `lj_udata_new'
/usr/bin/ld: libluajit.a(lj_parse.o): in function `fs_finish':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_parse.c:1608: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_parse.c:1608: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `lj_trace_flushall':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:306: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:306: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `trace_start':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:469: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:469: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `trace_state':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:689: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:689: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `trace_abort':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:615: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `trace_stop':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:554: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:554: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `trace_abort':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:615: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `penalty_pc':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:396: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `lj_trace_exit':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:914: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:914: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_alloc.o): in function `mmap_probe':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_alloc.c:269: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_gc.o): in function `gc_call_finalizer':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_gc.c:527: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_gc.c:527: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_gc.o):(.data.rel.ro.local+0x40): undefined reference to `lj_udata_free'
/usr/bin/ld: libluajit.a(lj_mcode.o): in function `mcode_alloc':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_mcode.c:238: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_record.o): in function `check_call_unroll':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_record.c:1858: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_clib.o): in function `clib_new':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_clib.c:402: undefined reference to `lj_udata_new'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_clib.c:402: undefined reference to `lj_udata_new'
/usr/bin/ld: libluajit.a(lib_math.o): in function `random_seed':
/home/hosts/neovim/.deps/build/src/luajit/src/lib_math.c:126: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lib_math.o): in function `lj_cf_math_random':
/home/hosts/neovim/.deps/build/src/luajit/src/lib_math.c:137: undefined reference to `lj_prng_u64d'
/usr/bin/ld: libluajit.a(lib_buffer.o): in function `lj_cf_buffer_new':
/home/hosts/neovim/.deps/build/src/luajit/src/lib_buffer.c:316: undefined reference to `lj_udata_new'
/usr/bin/ld: libluajit.a(lj_serialize.o): in function `serialize_get':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_serialize.c:453: undefined reference to `lj_lightud_intern'
/usr/bin/ld: libluajit.a(lj_ir.o):(.data.rel.ro+0x2b0): undefined reference to `lj_prng_u64d'
/usr/bin/ld: luajit: hidden symbol `lj_udata_new' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:739: luajit] Error 1
gmake[2]: Leaving directory '/home/hosts/neovim/.deps/build/src/luajit/src'
gmake[1]: *** [Makefile:125: src/luajit] Error 2
gmake[1]: Leaving directory '/home/hosts/neovim/.deps/build/src/luajit'
ninja: build stopped: subcommand failed.
make: *** [Makefile:87: deps] Error 1

### Steps to reproduce

Rasberrypi 3B+ 
________________
1.
sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen
2.
git clone https://github.com/neovim/neovim.git
3.
cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo

### Expected behavior

mkdir -p build
touch build/.ran-deps-cmake
ninja -C .deps
ninja: Entering directory `.deps'
[1/18] Performing install step for 'luajit'
FAILED: build/src/luajit-stamp/luajit-install 
cd /home/hosts/neovim/.deps/build/src/luajit && /usr/bin/gmake -j CFLAGS=-fPIC CFLAGS+=-DLUA_USE_APICHECK CFLAGS+=-funwind-tables CCDEBUG+=-g Q= CC=/usr/bin/cc PREFIX=/home/hosts/neovim/.deps/usr install && /usr/bin/cmake -E touch /home/hosts/neovim/.deps/build/src/luajit-stamp/luajit-install
gmake[1]: Entering directory '/home/hosts/neovim/.deps/build/src/luajit'
==== Building LuaJIT 2.1 ====
/usr/bin/gmake -C src
gmake[2]: Entering directory '/home/hosts/neovim/.deps/build/src/luajit/src'
LINK      luajit
/usr/bin/cc -g  -Wl,-E   -o luajit luajit.o libluajit.a -lm -ldl  
/usr/bin/ld: libluajit.a(lj_str.o): in function `lj_str_alloc':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_str.c:289: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_str.o): in function `lj_str_init':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_str.c:367: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_state.o): in function `lua_newstate':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_state.c:247: undefined reference to `lj_prng_seed_secure'
/usr/bin/ld: libluajit.a(lj_api.o): in function `cpcall':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_api.c:1163: undefined reference to `lj_lightud_intern'
/usr/bin/ld: libluajit.a(lj_api.o): in function `lua_pushlightuserdata':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_api.c:718: undefined reference to `lj_lightud_intern'
/usr/bin/ld: libluajit.a(lj_api.o): in function `lua_newuserdata':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_api.c:770: undefined reference to `lj_udata_new'
/usr/bin/ld: libluajit.a(lj_parse.o): in function `fs_finish':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_parse.c:1608: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_parse.c:1608: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `lj_trace_flushall':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:306: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:306: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `trace_start':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:469: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:469: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `trace_state':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:689: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:689: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `trace_abort':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:615: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `trace_stop':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:554: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:554: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `trace_abort':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:615: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `penalty_pc':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:396: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_trace.o): in function `lj_trace_exit':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:914: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_trace.c:914: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_alloc.o): in function `mmap_probe':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_alloc.c:269: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_gc.o): in function `gc_call_finalizer':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_gc.c:527: undefined reference to `lj_vmevent_prepare'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_gc.c:527: undefined reference to `lj_vmevent_call'
/usr/bin/ld: libluajit.a(lj_gc.o):(.data.rel.ro.local+0x40): undefined reference to `lj_udata_free'
/usr/bin/ld: libluajit.a(lj_mcode.o): in function `mcode_alloc':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_mcode.c:238: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_record.o): in function `check_call_unroll':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_record.c:1858: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lj_clib.o): in function `clib_new':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_clib.c:402: undefined reference to `lj_udata_new'
/usr/bin/ld: /home/hosts/neovim/.deps/build/src/luajit/src/lj_clib.c:402: undefined reference to `lj_udata_new'
/usr/bin/ld: libluajit.a(lib_math.o): in function `random_seed':
/home/hosts/neovim/.deps/build/src/luajit/src/lib_math.c:126: undefined reference to `lj_prng_u64'
/usr/bin/ld: libluajit.a(lib_math.o): in function `lj_cf_math_random':
/home/hosts/neovim/.deps/build/src/luajit/src/lib_math.c:137: undefined reference to `lj_prng_u64d'
/usr/bin/ld: libluajit.a(lib_buffer.o): in function `lj_cf_buffer_new':
/home/hosts/neovim/.deps/build/src/luajit/src/lib_buffer.c:316: undefined reference to `lj_udata_new'
/usr/bin/ld: libluajit.a(lj_serialize.o): in function `serialize_get':
/home/hosts/neovim/.deps/build/src/luajit/src/lj_serialize.c:453: undefined reference to `lj_lightud_intern'
/usr/bin/ld: libluajit.a(lj_ir.o):(.data.rel.ro+0x2b0): undefined reference to `lj_prng_u64d'
/usr/bin/ld: luajit: hidden symbol `lj_udata_new' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
gmake[2]: *** [Makefile:739: luajit] Error 1
gmake[2]: Leaving directory '/home/hosts/neovim/.deps/build/src/luajit/src'
gmake[1]: *** [Makefile:125: src/luajit] Error 2
gmake[1]: Leaving directory '/home/hosts/neovim/.deps/build/src/luajit'
ninja: build stopped: subcommand failed.
make: *** [Makefile:87: deps] Error 1

### Neovim version (nvim -v)

does not apply 

### Vim (not Nvim) behaves the same?

unknown / doesn't apply 

### Operating system/version

raspbian lite 64bit configured as full desktop

### Terminal name/version

LXTerminal

### $TERM environment variable

dunno

### Installation

build from repo

**Comment by clason** [comment]
Why are you not using the provided build scripts? Just `make` works fine.

**Comment by boodledot1** [comment]
Clason thank you for the feedback I'll go look through again and close the issue if I find the problem is solved

**Comment by boodledot1** [comment]
The best answer will always be shut up look at the docs change my mind thank u clason issue solved did not exist
