### ISSUE TITLE
appimage of unsupported builds seems abnormal (only has 200KB)

### ISSUE THREAD

**Issue by xaljer** [neovim/neovim#27657]
### Problem

appimage of unsupported builds seems abnormal (only has 200KB), but nvim-release repository don't support report issue.

### Steps to reproduce

none

### Expected behavior

none

### Neovim version (nvim -v)

none

### Vim (not Nvim) behaves the same?

no

### Operating system/version

none

### Terminal name/version

none

### $TERM environment variable

none

### Installation

appimage

**Comment by clason** [comment]
> vim-release repository don't support report issue.

Yes, intentionally. That's what "unsupported" means.
