### ISSUE TITLE
snippet: jump and accept placeholder

### ISSUE THREAD

**Issue by zhoudaxia2016** [neovim/neovim#27668]
### Problem

`vim.snippet.jump` will remove current placeholder

It is a bug？

### Steps to reproduce

nvim --clean 1.js
Execute
```vim
lua vim.keymap.set('i', '<c-j>', function() vim.snippet.jump(1) end)
lua vim.snippet.expand(vim.fn.join({"if (${1:condition}) {", "\t$0", "}"}, '\n'));
```
`<c-j>`

### Expected behavior

Do not remove `condition`

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2451+g8b4e26915 Build type: RelWithDebInfo LuaJIT 2.1.1707061634

### Vim (not Nvim) behaves the same?

no

### Operating system/version

wsl2

### Terminal name/version

window terminal

### $TERM environment variable

xterm-256color

### Installation

neovim github release

**Comment by MariaSolOs** [comment]
@zhoudaxia2016 try modifying the keymap to `vim.keymap.set({ 'i', 's' }, '<c-j>', function() vim.snippet.jump(1) end)`.

**Comment by zhoudaxia2016** [comment]
> @zhoudaxia2016 try modifying the keymap to `vim.keymap.set({ 'i', 's' }, '<c-j>', function() vim.snippet.jump(1) end)`.

It works, thanks.
