### ISSUE TITLE
docs: vim.bo is not "equivalent to both :set and :setlocal"

### ISSUE THREAD

**Issue by LunarLambda** [neovim/neovim#27671]
### Problem

Example: `autoread` is global or local to buffer.

`:set noautoread` sets the global value, meaning `:setglobal autoread?` returns `noautoread` and any buffer which hasn't `:setlocal autoread` will have `autoread` turned off.

On the contrary, `vim.bo.autoread = false` does *not* touch the global value of `autoread`. It behaves like `:setlocal`, even for `global-local` options.

### Steps to reproduce

`:h vim.bo`

### Expected behavior

The docs should state that `vim.bo` always behaves like `:setlocal`.

### Neovim version (nvim -v)

master

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

**Comment by LunarLambda** [comment]
In general, I found determining the mapping between the various `vim.o` variants and corresponding `:set` variants pretty confusing (based on reading the documentation)

What I gathered after a lot of testing and comparing:

`vim.o` = `:set`
`vim.go` = `:setglobal`
`vim.bo` = `:setlocal` (buffer options only)
`vim.wo` = `:setlocal` if global-local option, `:set` otherwise (window options only)
`vim.wo[winid][bufid]` = `:setlocal` (window options only)
`vim.opt` = `:set`
`vim.opt_global`= `:setglobal`
`vim.opt_local` = `:setlocal`

Maybe this kind of summary could be included in the documentation? `vim.wo` in particularly really made me struggle with properly wrapping my head around how window options work.

Also, maybe there should be `vim.lo` for a non-magic `:setlocal` equivalent? I found myself reaching for `vim.cmd('setlocal ...')` in autocommands for setting buffer-specific window options (like `number`) since `vim.wo[0][0]` is kind of strange and bothersome to write, and `vim.opt*` is planned for eventual deprecation.

```lua
vim.lo = setmetatable({}, {
  __index = function(_, k)
    return api.nvim_get_option_value(k, { scope = 'local' })
  end,
  __newindex = function(_, k, v)
    return api.nvim_set_option_value(k, v, { scope = 'local' })
  end,
})
```

**Comment by clason** [comment]
Welcome to the wonderful world of Vim options. (`vim.opt` is soft-deprecated and will be removed in the future once we have native dict option support.)

**Comment by LunarLambda** [comment]
> Welcome to the wonderful world of Vim options. (`vim.opt` is soft-deprecated and will be removed in the future once we have native dict option support; but `vim.wo[0][0]` is here to stay because the explicitness is _good_.)

Please don't get me wrong. I think `vim.bo[bufid]` and `vim.wo[winid]`/`vim.wo[winid][bufid]` are good. I just find that for general use, `:setlocal` to be much easier to remember as the "just do the right thing" option, especially since the documentation for `vim.bo` is incorrect, and `vim.wo` has 3 different ways it can behave, one of which isn't mentioned in documentation either (`:setlocal` if the option is global-local, which makes sense of course, but isn't documented. It says it always works like `:set` unless `bufid` is given.)

I did also mention `vim.opt*`'s probable deprecation status, hence why I suggested adding `vim.lo` as a parallel to `vim.o` and `vim.go`.

**Comment by clason** [comment]
> to be much easier to remember as the "just do the right thing" 

Yeah, about that... (It's not, really. It has lead to massive confusion before.)

Sure, documentation can be improved. Do you want to suggest something in a PR?

Regarding new API: We are _really_ conservative about this (now), so there has to be a significant benefit to the new accessor over what is already offered. Just "convenience" is not enough (anymore).

**Comment by LunarLambda** [comment]
I see. For a documentation PR, which places need to be changed? Are the lua docs autogenerated from the comments in _options.lua?

**Comment by clason** [comment]
> I see. For a documentation PR, which places need to be changed? Are the lua docs autogenerated from the comments in _options.lua?

Yes, exactly (via `make doc`).

**Comment by LunarLambda** [comment]
Okay. I'll see about making a PR suggesting new wording. As for the question of `vim.lo`, I think a few points speak for it

1. It provides symmetry with `vim.go`. I find its absence personally strange, especially since `vim.opt_local` exists, but is going to be removed in the future, so there won't be a straightforward replacement for it.
2. Without it, users are required to remember which options are buffer options and which are windows options, and remember how to get the proper `:setlocal` behaviour (`vim.wo[0][0]`), or stick to using `vim.cmd`
3. `:setlocal` is the correct choice for an overwhelming majority of user autocommands that want to set options. It's not immediately obvious how to set options iteratively (e.g. pairs(table)) with the `vim.bo`/`vim.wo` split, and `vim.cmd` would require error-prone string concatenations. I know some plugins currently expose separate configuration keys for window and buffer options for this reason (I'm unsure if there's a way to query the scope of an option in the API)

Yes, Vim options are messy. But I find the lack of a straightforward `:setlocal` analogue has caused me multiple bugs in my own config/plugins and given the functionality already exists in soft-deprecated form without simple replacement the functionality (which amounts to a copy-paste from `vim.go`) pulls it's weight enough to be worth considering.

**Comment by lewis6991** [comment]
There isn't an easy answer here. You may think `setlocal` is straightforward, but it really isn't. This becomes much more apparent when you read the C code.

E.g.
- `setlocal` for buffer options is the same as `set` 
- `setlocal` for windows options is not the same as `set` (most people don't understand this).

And then global-local makes each of these work differently.

If it's easier to you, then just keep using `vim.cmd`. 

> Without it, users are required to remember which options are buffer options and which are windows options

Yes this is intentional. Same applies to the type of the option (`string`/`number`/`boolean`).

> It's not immediately obvious how to set options iteratively (e.g. pairs(table)) with the vim.bo/vim.wo split, and vim.cmd would require error-prone string concatenations. I know some plugins currently expose separate

I suggest you don't set options in a loop. Or if you do make sure buffer and window options are separate. Options have different types anyway, so running this through a loop seems wrong.

**Comment by justinmk** [comment]
> The docs should state that `vim.bo` always behaves like `:setlocal`.

This is the case after all, see https://github.com/neovim/neovim/issues/27671
