### ISSUE TITLE
New (better) workaround for #2325 [middle click paste doesn't work]

### ISSUE THREAD

**Issue by furquan-lp** [neovim/neovim#27675]
### Problem

#2325 has been open for the past ~9 years and while the workaround given in that issue is serviceable, it doesn't replicate the functionality of Vim since it's dependent on mouse release (so it wouldn't work if left mousebutton was double clicked):
```
set mouse=a
vmap <LeftRelease> "*ygv
```
After a bit of discussion on Discord, `@origamiduck` was able to come up with a solution that achieves autoselect very well as far as I have tested:
```lua
vim.api.nvim_create_autocmd("CursorMoved", {
  desc = "Keep * synced with selection",
  callback = function()
    local mode = vim.fn.mode(false)
    if mode == "v" or mode == "V" or mode == "^V" then
      vim.cmd([[silent norm "*ygv]])
    end
  end,
})
```
I wanted to post this workaround here so others can find it since Discord is not indexable by search engines. Thanks again to `origamiduck` for coming up with this. I understand this is a low priority feature but I hope this well help other people searching for a solution until Vim's autoselect is implemented in Neovim.

### Steps to reproduce

The issue is well known and can be replicated as follows
* Select text within neovim using either the mouse or the keyboard (in visual mode) on a graphical (X or Wayland) Linux system
* Middle click in a text field outside of neovim

### Expected behavior

The expected behavior should mirror Vim's `clipboard=autoselect` as described in #2325

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

Vim (9.1) doesn't have this issue

### Operating system/version

Debian GNU/Linux with Xorg 7.7+23

### Terminal name/version

xterm 390-1

### $TERM environment variable

xterm-256color

### Installation

GitHub Releases

**Comment by furquan-lp** [comment]
Please feel free to close this issue, unless any new developments have been made regarding #2325.

**Comment by zeertzjq** [comment]
The `'^V'` should be `'\22'` instead:
```lua
vim.api.nvim_create_autocmd("CursorMoved", {
  desc = "Keep * synced with selection",
  callback = function()
    local mode = vim.fn.mode(false)
    if mode == "v" or mode == "V" or mode == "\22" then
      vim.cmd([[silent norm "*ygv]])
    end
  end,
})
```

**Comment by zeertzjq** [comment]
A solution for v0.10 that doesn't involve mode change:
```lua
vim.api.nvim_create_autocmd('CursorMoved', {
  desc = 'Keep * synced with selection',
  callback = function()
    local mode = vim.fn.mode(false)
    if mode == 'v' or mode == 'V' or mode == '\22' then
      vim.fn.setreg('*', vim.fn.getregion(vim.fn.getpos('.'), vim.fn.getpos('v'), { type = mode }))
    end
  end,
})
```

**Comment by lilydjwg** [comment]
This seems to copy to `"*` on every cursor move? How does it perform when selecting a lot of text (e.g. a few hundreds of pages)? It would be better to hook `FocusLost` event and do the copy there, but I don't know how reliable that event is.

**Comment by andrepatta** [comment]
If you're encountering difficulties with Raycast AI commands in nvim, this code could be helpful.

```lua
local temp_star_reg = ""
vim.api.nvim_create_autocmd("FocusLost", {
  desc = "Keep * synced with selection",
  callback = function()
    local mode = vim.fn.mode(false)
    if mode == "v" or mode == "V" or mode == "\22" then
      temp_star_reg = vim.fn.getreg("*")
      vim.fn.setreg("*", vim.fn.getregion(vim.fn.getpos("."), vim.fn.getpos("v"), { type = mode }))
    end
  end,
})
vim.api.nvim_create_autocmd("FocusGained", {
  desc = "Restore * register from temporary variable",
  callback = function()
    vim.fn.setreg("*", temp_star_reg)
  end,
})
vim.opt.clipboard = "unnamed,unnamedplus"

```

**Comment by furquan-lp** [comment]
> This seems to copy to `"*` on every cursor move? How does it perform when selecting a lot of text (e.g. a few hundreds of pages)? It would be better to hook `FocusLost` event and do the copy there, but I don't know how reliable that event is.

I'm not sure if it's tmux or XTerm, but using FocusLost doesn't seem to work for me.

Currently I'm using a debounced version. Partly helped along by Claude (LLM) so be wary of the usual LLM pitfalls:
```lua
-- Sync visual selection to * register for middle-click paste
-- Works with which-key/mini.clue and handles large selections efficiently
local timer = nil

local function sync_selection()
    local mode = vim.fn.mode()
    if mode == "v" or mode == "V" or mode == "\22" then
        local start_pos = vim.fn.getpos("v")
        local end_pos = vim.fn.getpos(".")
        local lines = vim.fn.getregion(start_pos, end_pos, {type = mode})
        vim.fn.setreg("*", table.concat(lines, "\n"))
    end
end

vim.api.nvim_create_autocmd("CursorMoved", {
    desc = "Keep * register synced with visual selection (debounced)",
    callback = function()
        local mode = vim.fn.mode()
        if mode == "v" or mode == "V" or mode == "\22" then
            if timer then
                vim.fn.timer_stop(timer)
            end
            -- Sync after 200ms of no cursor movement
            timer = vim.fn.timer_start(200, sync_selection)
        end
    end,
})
```
