### ISSUE TITLE
Invalid neovim LSP client capabilties, not able to start rust-analyzer

### ISSUE THREAD

**Issue by lrvdijk** [neovim/neovim#27677]
### Problem

I am running neovim nightly (checked out yesterday, 02/28), and I'm trying to use the rust-analyzer LSP using rustacean.

It is unable to start the LSP, however, and the LSP log shows the following error

```
Error: Failed to deserialize InitializeParams: invalid type: sequence, expected i32
```

I think the incorrect values are the valueSet values for completionItemKind. These values should be integers, but are now a list of [int, String]. It seems that neovim LSP already produces the invalid values for the capabilities (and thus unrelated to rustacean), because when I run `:lua print(vim.inspect(vim.lsp.protocol.make_client_capabilities()))`, the incorrect table values for valueSet already show up:

```
:lua print(vim.inspect(vim.lsp.protocol.make_client_capabilities()))
{
  general = {
    positionEncodings = { "utf-16" }
  },
  textDocument = {
    callHierarchy = {
      dynamicRegistration = false
    },
    codeAction = {
      codeActionLiteralSupport = {
        codeActionKind = {
          valueSet = { "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }
        }
      },
      dataSupport = true,
      dynamicRegistration = true,
      isPreferredSupport = true,
      resolveSupport = {
        properties = { "edit" }
      }
    },
    completion = {
      completionItem = {
        commitCharactersSupport = false,
        deprecatedSupport = false,
        documentationFormat = { "markdown", "plaintext" },
        preselectSupport = false,
        snippetSupport = false
      },
      completionItemKind = {
        valueSet = { { 1, "Text",
            <metatable> = <1>{}
          }, { 2, "Method",
            <metatable> = <table 1>
          }, { 3, "Function",
            <metatable> = <table 1>
          }, { 4, "Constructor",
            <metatable> = <table 1>
          }, { 5, "Field",
            <metatable> = <table 1>
          }, { 6, "Variable",
            <metatable> = <table 1>
          }, { 7, "Class",
            <metatable> = <table 1>
          }, { 8, "Interface",
            <metatable> = <table 1>
          }, { 9, "Module",
            <metatable> = <table 1>
          }, { 10, "Property",
            <metatable> = <table 1>
          }, { 11, "Unit",
            <metatable> = <table 1>
          }, { 12, "Value",
            <metatable> = <table 1>
          }, { 13, "Enum",
            <metatable> = <table 1>
          }, { 14, "Keyword",
            <metatable> = <table 1>
          }, { 15, "Snippet",
            <metatable> = <table 1>
          }, { 16, "Color",
            <metatable> = <table 1>
          }, { 17, "File",
            <metatable> = <table 1>
          }, { 18, "Reference",
          ...
```

Related: https://github.com/rust-lang/rust-analyzer/issues/16713

### Steps to reproduce using "nvim -u minimal_init.lua"

--- CHANGE THESE
local pattern = 'rust'
local cmd = {'rust-analyzer'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'.git', '.editorconfig'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    local capabilities = vim.lsp.protocol.make_client_capabilities()

    vim.lsp.start({
      name = 'bugged-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings,
      capabilities = capabilities,
    })
  end
})

### Expected behavior

rust-analyzer starts properly

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2480+g0eaae1bc0-Homebrew

### Language server name/version

rust-analyzer 1.76.0

### Operating system/version

OSX 14.2

**Comment by clason** [comment]
Already fixed.
