### ISSUE TITLE
Not returning proper color scheme value

### ISSUE THREAD

**Issue by JasonBoyett** [neovim/neovim#27683]
### Problem

when you have your color scheme set to a theme that consists of two words separated by a dash such as ayu-dark, or tokyonight-storm only the first part of the theme is returned when you run 

```vim
:colorscheme
```
or

```vim
:lua print(vim.g.colors_name)
```

It works fine if before the dashes there is a number in the theme name such as base16-onedark

### Steps to reproduce

- in your editor set your theme to a theme that matches the above-mentioned pattern such as tokyonight-storm.
```vim
:colorscheme tokyonight-storm
```
- run a command to print the current color scheme

```vim
:colorscheme
```
or

```vim
:lua print(vim.g.colors_name)
```

### Expected behavior

the editor should print "tokyonight-storm"

instead it will likely print "tokyonight"

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

could not reproduce

### Operating system/version

pop os

### Terminal name/version

kitty 0.21.2

### $TERM environment variable

screen-256color

### Installation

build from repo

**Comment by seandewar** [comment]
That's because those color schemes set `g:colors_name` to that.
