### ISSUE TITLE
nvim-qt.exe <a-c-*> mapping not working, such as <a-c-j> act like capital J.

### ISSUE THREAD

**Issue by peter-lyr** [neovim/neovim#27685]
### Problem

nvim-qt.exe <a-c-*> mapping not working, such as <a-c-j> act like capital J.

### Steps to reproduce

nvim-qt -- -u NONE

### Expected behavior

nnoremap <A-C-j> :ls<CR>
when i type <Alt-Ctrl-j>, it will show the buffer list.
but it actually type capital J.

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

no

### $TERM environment variable

no

### Installation

no

**Comment by peter-lyr** [comment]
nvim.exe is ok.
nvim-qt.exe is not ok.

**Comment by clason** [comment]
nvim-qt is https://github.com/equalsraf/neovim-qt

**Comment by zeertzjq** [comment]
Not an Nvim issue
