### ISSUE TITLE
Nightly appimage missing Neovim binary

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#27691]
### Problem
The nightly appimage appears to be missing the Neovim binary.

### Steps to reproduce
```
curl -L https://github.com/neovim/neovim-releases/releases/download/nightly/nvim.appimage -o nvim.appimage
chmod u+x nvim.appimage
./nvim.appimage --appimage-extract
ls squashfs-root/usr/bin/
```

### Expected behavior
Directory contains nvim binary.

**Comment by clason** [comment]
These are _unsupported_ releases. The ones in this repo work fine.

**Comment by ddickstein** [comment]
Makes sense. For calling this to your attention in case it wasn't something you were aware of, would the IRC be better?

**Comment by clason** [comment]
Dev chat on Matrix, yes.
