### ISSUE TITLE
FEATURE: An option to prioritize `:h clipboard-tool` over OSC 52 clipboard.

### ISSUE THREAD

**Issue by pysan3** [neovim/neovim#27698]
### Problem

As it says in `:h clipboard-osc52`, OSC 52 clipboard kicks in by default when I meet all of the following criteria.

```txt
  • Nvim is running in the |TUI|
  • |g:clipboard| is unset
  • 'clipboard' is not set to "unnamed" or "unnamedplus"
  • $SSH_TTY is set
```

I unfortunately meet all the criteria but I want to go through the clipboard detection listed in `:h clipboard-tool`.
My terminal does not support osc52 and I hop between OSs so I sometimes use `tmux` and sometimes `xsel` / `xlip` so I cannot hardcode something to `g:clipboard` as well.

### Expected behavior

Would it be possible to move ocs52 clipboard to the end of the `:h clipboard-tool` list, or provide an option to disable it manually?

I would appreciate having the clipboard-tools prioritize over osc52 as I said in the title, but simply having the option to disable it would also be helpful.

Considering that it already verifies the `SSH_TTY` envvar, could we add a custom envvar to disable it?

cc @gpanders

**Comment by zeertzjq** [comment]
Why do you have `$SSH_TTY` set?

**Comment by pysan3** [comment]
Sorry I was talking about when I ssh (and that's the case I'm having the problem).

I rely on xsel/xclip <-> ssh X forwarding to transfer the clipboard content, which is detected with `:h clipboard-tool`.

**Comment by gpanders** [comment]
OSC 52 is gated behind a query to the terminal that it is supported. So it should not be enabled by default unless your terminal supports it. What terminal are you using?

**Comment by pysan3** [comment]
To my knowledge, wezterm only supports copying but not pastWVking? https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1371

My client PC is using wayland, but due to [wonky support of IMEs in wayland](https://github.com/wez/wezterm/issues/1772), I run wezterm via xwayland.

This might be why something is false-detecting the ability to do OSC 52 support somewhere.

With my setup, what I observe is...

- copy: _n lines yanked into "+_ -> But nothing happens on client side.
- paste: _Waiting for OSC 52 response ..._ -> freezes for a while.

**Comment by pysan3** [comment]
Sorry, wrong link. Updated.

**Comment by gpanders** [comment]
We should have a way to opt out of OSC 52. Even if the XTGETTCAP query determines that the terminal supports it, the user may have disabled it (and I don't know if terminals consider user configuration in their XTGETTCAP responses, though I would guess not).

This should be an easy change. Update `runtime/plugin/osc52.lua` to include a check for `vim.g.osc52 ~= false`. You can then opt out of OSC 52 support by setting `vim.g.osc52 = false` in `init.lua`.

**Comment by pysan3** [comment]
> We should have a way to opt out of OSC 52. Even if the XTGETTCAP query determines that the terminal supports it, the user may have disabled it (and I don't know if terminals consider user configuration in their XTGETTCAP responses, though I would guess not).
> 
> 
> 
> This should be an easy change. Update `runtime/plugin/osc52.lua` to include a check for `vim.g.osc52 ~= false`. You can then opt out of OSC 52 support by setting `vim.g.osc52 = false` in `init.lua`.

Thank you. I think this is a good idea. 

How about aligning it with other builtin plugins and use the `vim.g.loaded_osc52` method? (Just like `let g:loaded_netrw=1 `) Just a random idea ;)

**Comment by gpanders** [comment]
> How about aligning it with other builtin plugins and use the `vim.g.loaded_osc52` method? (Just like `let g:loaded_netrw=1 `) Just a random idea ;)

For newer builtin plugins we’ve not been following this convention (see also `vim.g.editorconfig`).

**Comment by pysan3** [comment]
@gpanders I hate to ask but may I ask if there's any progress here?

Also will this be done before v0.10 release (added to 0.10 roadmap)?

**Comment by clason** [comment]
You can see the open and merged PRs yourself. The best (only) way of moving this forward is to open a PR yourself; this is not a difficult change.

**Comment by gpanders** [comment]
> @gpanders I hate to ask but may I ask if there's any progress here?

Repeating what @clason said, the quickest way to get this change in would be to do it yourself. I outlined the steps in [this comment](https://github.com/neovim/neovim/issues/27698#issuecomment-1974897420), and I'm happy to review your PR when it's ready.

**Comment by pysan3** [comment]
Thanks for your reply @clason 

I asked @gpanders as he said it would be an easy fix and I know he is very knowledgeable with neovim.
I do not want to contribute to neovim anymore because unfortunately I got the worst treatment by the core devs multiple times and I'm sick of it.

I don't have the permission to add this to the roadmap afaik?

**Comment by gpanders** [comment]
>I do not want to contribute to neovim anymore because unfortunately I got the worst treatment by the core devs multiple times and I'm sick of it.

I'm sorry to hear this, but to make expectations clear: Neovim is a community and volunteer driven project. Most changes happen because someone wants to see that change made. If you're unwilling to make the change yourself, then there is no guarantee it will ever happen.

To state the obvious: working on Neovim is not my full time job. I do not get paid for it. Like every other contributor to the project (both organization members and community members), I work on the issues and features which matter to me personally. This feature does not fall into that category, so it's not a high priority for me.

**Comment by pysan3** [comment]
> > I do not want to contribute to neovim anymore because unfortunately I got the worst treatment by the core devs multiple times and I'm sick of it.
> 
> I'm sorry to hear this, but to make expectations clear: Neovim is a community and volunteer driven project. Most changes happen because someone wants to see that change made. If you're unwilling to make the change yourself, then there is no guarantee it will ever happen.

Okay awesome.

Will this FR be added to https://github.com/neovim/neovim/milestone/36?

**Comment by clason** [comment]
PR first; then we'll see. But I don't see this as a blocker so it doesn't belong on the milestone. If it's ready, it'll get merged and will be in the next (minor) release; nothing more, nothing less.

**Comment by pysan3** [comment]
Thank you @dundargoc @gpanders 

Amazing work!
It's neat that `vim.g.clipboard` accepts `false` which is _set_ but not _applied_ :)

One tiny question: shouldn't this behavior be documented somewhere near `:h g:clipboard` or `:h clipboard-osc52`?

**Comment by dundargoc** [comment]
Eh, sure. I have a PR up.
