### ISSUE TITLE
Semantics highlighting gets shifted

### ISSUE THREAD

**Issue by dainiusm07** [neovim/neovim#27703]
### Problem

Semantics highlighting gets shifted after leaving insert mode on indented line in Dart, tried to reproduce it in Typescript but everything seemed to be working fine.

Disabling Dart client semantics capability stops this behaviour.

https://github.com/neovim/neovim/assets/44223680/c8c840d3-220a-4dc3-a82f-d9c966f177c4

### Steps to reproduce using "nvim -u minimal_init.lua"

1. Create pubspec.yaml
```yaml
name: example
description: A sample command-line application.
version: 1.0.0
``` 
2. Create example.dart file
```dart
class Example {
  final Example? child;
  final Example Function(Example example)? fn;

  Example({this.child, this.fn});

  Example build() => Example(
        fn: (Example example) => Example(
          child: Example(child: example.identity()),
        ),
      );

  Example identity() {
    return this;
  }
}
```
3. Install treesitter & setup Dart (https://dart.dev/get-dart)
```lua
local lazypath = "/tmp/semantics-lazy"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end

vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    {
        "neovim/nvim-lspconfig",
        config = function()
            require("lspconfig").dartls.setup({
                capabilities = vim.lsp.protocol.make_client_capabilities(),
            })
        end
    },
})
```
4. Start new line where created indent would be big enough and go to normal mode

### Expected behavior

Highlighting should not shift.

### Neovim version (nvim -v)

NVIM v0.9.5 (tried to build nvim from master too, same thing)

### Language server name/version

Dart SDK version: 3.3.0 (stable)

### Operating system/version

Macos

### Log file

https://gist.github.com/dainiusm07/e3e43a5499cdda39e9b457caf45aeccc

**Comment by clason** [comment]
Is the nvim-treesitter bit really necessary?

**Comment by dainiusm07** [comment]
You are right, it is not. I thought without it there will be no highlighting at all. My bad

**Comment by lewis6991** [comment]
Unless you can produce the same problem with a different server, this is most definitely an issue with dartls.

**Comment by dainiusm07** [comment]
Tried gopls too, no issue with that. Yeah, will be an dartls issue.
