### ISSUE TITLE
No error notifications from `fswatch`

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#27713]
### Problem

I tried to check if and how `fswatch` works for me - in any way at first but couldn't find any such process. It turned out that it is started for phpactor LS so I got [the command](https://github.com/neovim/neovim/blob/dbf6be296df6da28151afdcb96ceb8ba2076cc65/runtime/lua/vim/_watch.lua#L274-L284) into one-liner and ran it directly from console. I saw the stderr there (it was `Event queue overflow`) but not in nvim. 

### Steps to reproduce

On Linux try to (for example) decrease `/proc/sys/fs/inotify/max_queued_events` enough to get _event queue overflow_ error and see if nvim warns about it. 

### Expected behavior

Notify about errors using `stderr` callback to `vim.system` or in another way.

### Neovim version (nvim -v)

v0.10.0-dev-2500+gdc8c086c7

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Debian Sid

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

from repo

**Comment by lewis6991** [comment]
Does #27717 resolve this?

**Comment by przepompownia** [comment]
Yes, it's enough, although I get additional empty error that probably comes from multi-line stderr:

![image](https://github.com/neovim/neovim/assets/11404453/ae245996-4470-4dc6-81ac-64363dcebf9f)

**Comment by lewis6991** [comment]
I can't easily repro the issue so feel free to suggest any additional formatting or changes.

**Comment by przepompownia** [comment]
At the moment https://github.com/neovim/neovim/pull/27717 seems to be ready to merge.

**Comment by przepompownia** [comment]
Thank you
