### ISSUE TITLE
`nvim_buf_set_lines` adjustment of cursor and of topline is inconsistent

### ISSUE THREAD

**Issue by pysan3** [neovim/neovim#27720]
### Problem

```lua
local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
vim.api.nvim_buf_set_lines(0, 0, #lines, true, lines)
```

I believe the above code should do nothing to the buffer, but with the latest nightly, buffer is scrolled downwards resulting an inconsistent user experience.

I was not able to bisect the exact commit causing this problem, but I'm pretty sure this was caused by the series of refactoring https://github.com/neovim/neovim/pull/24889 done by @bfredl .

I found several similar issues, but they referred to the issue with some plugin or lsp.format, whereas my _steps to reproduce_ is reproducible without any setup (nvim -u NONE).

### Steps to reproduce

**No config file required.** (nvim -u NONE)

1. Open a file that has more lines than nvim's window height.
3. `G` to go to the bottom.
4. `H` to move the cursor to the top of the window.
5. Run the following code.

```lua
local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
vim.api.nvim_buf_set_lines(0, 0, #lines, true, lines)
```

### Result

The buffer and cursor moves down and lands one line above the bottom `scrolloff`. The exact same behavior as doing `zb` after `step 3.`.

### Expected behavior

Do not scroll the buffer, and have no visual change in above case.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2504+g3971797be1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux

### Terminal name/version

Wezterm

### $TERM environment variable

tmux-256color

### Installation

Build from source

**Comment by bfredl** [comment]
> I believe the above code should do nothing to the buffer, but with the latest nightly, buffer is scrolled downwards resulting an inconsistent user experience.

It is/was not, and it cannot be true in general that this code does nothing to the buffer. 

It is a valid open question how it should scroll though. Just as with the other issue, a difference to 0.9.5 _by itself_ does not prove a bug, but it shows a case where it can be discussed if the previous or the current behavior is the one we want moving forward.

**Comment by pysan3** [comment]
@bfredl Thank you for your response. I am glad to see that this issue has been caught on your radar.

I understand that preserving the cursor position while rewriting the buffer content can be challenging. However, I believe it is important to maintain the previous behavior where the cursor position relative to the buffer and window remains the same.

A common scenario is when reformatting a file, where the entire buffer is replaced with for example stylua's output.

It is quite frustrating to have the cursor constantly moving with each format, making the editing experience very unpleasant.

I have also encountered this issue with UI plugins, such as [nui.nvim](https://github.com/MunifTanjim/nui.nvim/blob/main/lua/nui/tree/README.md), where the cursor jumps when the tree is redrawn inside the buffer, even when the content has not changed.

**Comment by pysan3** [comment]
> > I believe the above code should do nothing to the buffer, but with the latest nightly, buffer is scrolled downwards resulting an inconsistent user experience.
> 
> It is/was not, and it cannot be true in general that this code does nothing to the buffer.
> 
> It is a valid open question how it should scroll though. Just as with the other issue, a difference to 0.9.5 _by itself_ does not prove a bug, but it shows a case where it can be discussed if the previous or the current behavior is the one we want moving forward.

@bfredl Could you please share with me what _other behavior_ you are thinking could be a viable option? I cannot think of any other acceptable outcome and I think what I described should be _the_ way `nvim_buf_set_lines` should behave.
I consider this a bug when `nvim_buf_set_lines` moves the cursor position.

**Comment by bfredl** [comment]
> Could you please share with me what other behavior you are thinking could be a viable option?

The current one, which matches the actual semantics of set_lines _replacing_  the entire range of lines with another range of lines. and then for neovim to provide some other mechanism for plugins to say that line numbers are at least "almost" preserved in this operation (i e it is fine to approximate old line numbers with new ones to keep the view almost the same in windows, current or not). 

The key point here is to relay the _semantics_ of the operation, and `nvim_buf_set_lines` doesn't do that by itself.

**Comment by pysan3** [comment]
@bfredl Please correct me if I'm misinterpreting but I'm not complaining about changes in line number. In fact, line number of cursor stays same from before to after `nvim_buf_set_lines` which is awesome.

My issue is that the cursor position **relative to the window** changes after the operation.

As you can see in the record, I start from the 6th line inside the window, but after running `nvim_buf_set_lines`, the cursor position jumps to somewhere around the middle of the screen, where the expected behavior is to keep the cursor on the 6th line.


https://github.com/neovim/neovim/assets/41065736/18349c0d-6690-4690-8e6f-c7a94b6093c8

**Comment by pysan3** [comment]
Does this make sense to you @bfredl ?

**Comment by bfredl** [comment]
yes, it is a bug that cursor position is not handled consistently like topline. I made the mistake of assuming that the title of the issue would describe the issue:)

**Comment by pysan3** [comment]
Thanks for your reply @bfredl !

Do you have any rough estimate on when this can be fixed?

**Comment by bfredl** [comment]
yes, it will be fixed before 0.10 .

**Comment by pysan3** [comment]
@bfredl Thanks. Hope it gets fixed as soon as possible.

FYI, this issue might be caused by the same core problem.

- https://github.com/neovim/neovim/issues/25370

**Comment by bfredl** [comment]
Please try (very) latest master, just merged a fix.

**Comment by pysan3** [comment]
@bfredl Unfortunately, I don't think it is fixed. 

I've tried to detect the pattern of the behavior but I'm not really sure.
(I'm sometimes using `<C-e>, <C-y>` or the mouse to scroll.)


https://github.com/neovim/neovim/assets/41065736/df26ee4b-4ad9-4dfb-8a13-66f4dff1057b

**Comment by pysan3** [comment]
On top of that, I'm getting segfault crashes from commit `08fc1eb`. I cannot detect how or when the crash is happening, but it is happening everytime I open a second buffer.

This is not reproducible with `nvim -u NONE` but it gets fixed if I move back one commit prior so there should be a minor edge case in your code. I'll try to detect the problem, but at least reporting it now to let you know.

![image](https://github.com/neovim/neovim/assets/41065736/69886397-85ab-499c-afa4-827ddd490cad)

**Comment by zeertzjq** [comment]
Is that the full stacktrace you got by typing `bt`?

**Comment by bfredl** [comment]
@pysan3 would you mind trying https://github.com/neovim/neovim/pull/27854 and see if behaves like you expect?

**Comment by pysan3** [comment]
@bfredl Amazing! Your branch `boogalo_lines` works as expected.

However I'm still having a segfault issue with my own config as I reported above.

Here is the full track trace. I managed to figure out how to get the full stack @zeertzjq :)

[bt.txt](https://github.com/neovim/neovim/files/14600654/bt.txt)

I'm still not able to reproduce this with `nvim -u NONE` but I think it happens when you have set a window option in a autocmd? I'm not really sure. I hope the stack trace gives you enough information.

**Comment by seandewar** [comment]
Looking at the bt, it looks like you have some plugin calling `changed_window_setting` via the FFI, but it's assuming the old signature (without the `wp` argument, as it's NULLed out).

Looking at your plugins, it's probably [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo/blob/e29dbf5b2d76ea43f4e585e3deeb6510488eee3f/lua/ufo/wffi.lua#L84), which updated the signatures yesterday; you'll need to update it.

**Comment by pysan3** [comment]
@seandewar THANK YOU!! You saved my day!

I can confirm that it was fixed by the latest commit in nvim-ufo (latest tag/release is too old tho).
@bfredl @zeertzjq Thanks for digging in. It was a plugin related issue and it seems to be fixed now.
