### ISSUE TITLE
Regression bug with `nvim_buf_set_lines` on Neovim nightly

### ISSUE THREAD

**Issue by wojciech-kulik** [neovim/neovim#27723]
### Problem

When using Neovim nightly there is a bug with `nvim_buf_set_lines` when the buffer is not the active one. After calling this function, the buffer is scrolled to top, not preserving the current cursor position. When I switch to the buffer with changed lines, the cursor position is restored and the window is scrolled correctly. It works as expected in Neovim 0.9.5.

Nightly:

https://github.com/neovim/neovim/assets/3128467/b4b0b65a-50cd-413e-8663-53638c721679

0.9.5:

https://github.com/neovim/neovim/assets/3128467/b73476c4-a3d7-4a3b-85db-636823847553

### Steps to reproduce

```lua
local lines = {}
for i = 1, 100 do
  lines[i] = tostring(i)
end

vim.api.nvim_buf_set_lines(OTHER_BUFFER_ID, 0, -1, false, lines)
```

1. Run Neovim nightly
2. Run the provided script for your buffer (use `:luafile` for example)
3. Set your cursor position somewhere in the middle of the file.
4. Create a split and run the provided script for the previously configured buffer (make sure to set the correct buffer id, it can't be 0).

Result: the buffer is scrolled to top.

### Expected behavior

The updated buffer should preserve it's cursor position without scrolling to top.

### Neovim version (nvim -v)

v0.10.0-dev-2501+gdbf6be296

### Vim (not Nvim) behaves the same?

-

### Operating system/version

macOS 14.2.1

### Terminal name/version

iTerm2

### $TERM environment variable

screen-256color

### Installation

repo

**Comment by wojciech-kulik** [comment]
Workaround:

```lua
for i, line in ipairs(lines) do
  vim.api.nvim_buf_set_lines(M.bufnr, i - 1, i, false, { line })
end
```

**Comment by echasnovski** [comment]
I've bisected it to 008154954 which was part of #24824.
cc @bfredl

**Comment by bfredl** [comment]
The instructions above do not uniquely identify a situation. I could easily expand that script myself into _some_ complete reproduction script, but so in multiple different ways. Depending on the missing details, the current behavior might or might not actually be the desired one (a change from 0.9.5 is not enough to identify a regression).

**Comment by wojciech-kulik** [comment]
@bfredl you didn't provide information on what is exactly missing. Reproduction steps have been provided and the video showing the situation is provided, plus you got the specific commit that changes this behavior. I think you have everything you need :).

**Comment by bfredl** [comment]
Trivially: `OTHER_BUFFER_ID` is not defined. and it is not clear at all what that should refer to in your step 2 and 4 respectively.

It is better to just provide a complete script directly, instead of having us guess stuff, to avoid any misunderstanding.

**Comment by pysan3** [comment]
@bfredl Could you please take a moment to review this issue as well? Here is the link: https://github.com/neovim/neovim/issues/27720

Although my issue may not be identical to the one described here, there is a possibility that they share the same root cause.

I have also included steps to reproduce the issue.

**Comment by wojciech-kulik** [comment]
Here is the code to reproduce... the buffer with content doesn't preserve it's scroll offset.

```lua
local lines = {}
for i = 1, 100 do
  lines[i] = tostring(i)
end

vim.cmd(":new")
local newBuf = vim.api.nvim_get_current_buf()

vim.api.nvim_buf_set_lines(newBuf, 0, -1, false, lines)
vim.cmd(":50")

vim.cmd("vnew")
vim.api.nvim_buf_set_lines(newBuf, 0, -1, false, lines)
```

**Comment by bfredl** [comment]
Thanks, it's clear now. 

I cannot reproduce however on master ( 633bf61d3) with `nvim --clean -u path/to/script.lua`. Although the behavior you describe sounds like it _could_ happen (for the same reasons as in https://github.com/neovim/neovim/issues/27720#issuecomment-1976759033 ), am I missing something more?

**Comment by wojciech-kulik** [comment]
Maybe it's a matter of timing.
 
When I call `:luafile path/to/script.lua` after `nvim --clean -u path/to/script.lua` it's reproducible.

**Comment by wojciech-kulik** [comment]
Another related issue: https://github.com/neovim/neovim/issues/25370
