### ISSUE TITLE
QuickFix and LocationList window statusline does not respect global statusline

### ISSUE THREAD

**Issue by dasupradyumna** [neovim/neovim#27731]
### Problem

QuickFix and LocationList windows do not respect the `statusline` option when `laststatus=3` (global statusline).
They show the default statusline information, different from the custom value set by users / plugins.

#### Left: Normal window & Right: QuickFix window
![image](https://github.com/neovim/neovim/assets/45595032/a226dbb5-6333-4c1e-8c0f-74a3fc0eeeb8)![image](https://github.com/neovim/neovim/assets/45595032/f31a3103-3164-4306-a9a4-33993a7450a9)

### Steps to reproduce

1. Open neovim using `$ nvim -u NORC`.
2. Execute `:set laststatus=3 statusline=<testing>`. Notice that the statusline now shows the string "\<testing>".
    Also, `:set winbar=%f` for the same appearance as in the screenshot. Unrelated to bug, just for visualization.
4. Execute `:copen`. Notice that the statusline now shows the default format string, and not the string set in Step 2.
    This behavior can be seen for `:lopen` as well.

### Expected behavior

Custom `statusline` option should apply to the windows with `qf` filetype buffers.

This is caused due to the code (line 13-18 at the time of posting) in ftplugin file for [quickfix](runtime/ftplugin/qf.vim) filetype. This does not check for the global statusline, i.e `laststatus==3` when locally modifying the `statusline` option.

If this is undesirable behavior and a bug, I am more than happy to submit a PR to fix this after the necessary discussion.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2258+g1405e5c8c

### Vim (not Nvim) behaves the same?

no, vim does not have laststatus=3 option

### Operating system/version

Windows 10 AND Ubuntu 20.04

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

nvim-win64.msi nightly release on Windows AND nightly PPA using apt on Linux

**Comment by monkoose** [comment]
Does `vim.g.qf_disable_statusline = 1` helps?

**Comment by zeertzjq** [comment]
I think this is working as intended.

**Comment by zeertzjq** [comment]
`:h ft-qf-plugin`

**Comment by Diegovsky** [comment]
Fantastic, thanks.
