### ISSUE TITLE
Unable to resolve dependency 'memurai-developer.install'

### ISSUE THREAD

**Issue by yqz945** [neovim/neovim#27732]
### Problem

Can't install neovim on windows 11.
> choco install neovim -y ocur the following error

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - neovim - Unable to resolve dependency 'memurai-developer.install'. Source(s) used: 'https://community.chocolatey.org/api/v2/'.

After install memurai-developer, the error still exist. Don't know how to fix the promblem.

### Steps to reproduce

choco install neovim -y

### Expected behavior

Instll neovim successful

### Neovim version (nvim -v)

latest version

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Win11

### Terminal name/version

Powershell

### $TERM environment variable

no

### Installation

chocolate

**Comment by dundargoc** [comment]
We're not responsible for choco, you need to report this to them to solve this instead.

Also no clue wtf memurai-developer is, no clue where they got that from.
