### ISSUE TITLE
Bracketed Paste handling differs in insert mode vs normal mode

### ISSUE THREAD

**Issue by luisjakon** [neovim/neovim#27733]
### Problem

Bracketed paste (sent from terminal) inserts text after the first character in normal mode but works as expected insert mode. 

Kitty is configured with ```map cmd+v paste_from_clipboard``` which enables bracketed paste.

### Steps to reproduce

nvim --clean :edit foo p

### Expected behavior

Neovim should detect a bracketed paste text received over stdin and paste it
correctly

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2284+gf6042d5c3

### Vim (not Nvim) behaves the same?

dont know

### Operating system/version

macOS 14.3.1

### Terminal name/version

Kitty/0.32.2

### $TERM environment variable

screen-256color

### Installation

brew

**Comment by luisjakon** [comment]
kovidgoyal/kitty#7191

**Comment by murtaza64** [comment]
Isn't this behavior expected, matching the behavior of `"+p`? or are you claiming the behavior differs from `"+p` in which case I wasn't able to reproduce on iTerm

**Comment by luisjakon** [comment]
Hi, thanks! It should be +P as far as i understand...or at least should be configurable somehow...no?

**Comment by luisjakon** [comment]
@zeertzjq thnxs! It is very very common to do this at the beginning (and middle) of a line as well...
is there any possibility to have logic to check what position the cursor + mode the editor is in? 
In Insert mode everything works fine. Maybe check the mode and if in normal mode, change to insert mode before pasting or appending? or perhaps there's a better way you can think of since you know best...Many thnxs!

**Comment by zeertzjq** [comment]
> This breaks the expected behavior of most if not all modern text editors...I hope this could be an easy fix...Many Thnxs!

What "all modern text editors" have a Normal mode?

**Comment by luisjakon** [comment]
You got me on that! : )

**Comment by luisjakon** [comment]
Hi! This seems to work with ```virtualedit = "onemore"``` enabled. 

``` Lua
vim.paste = (function(overridden)
      vim.opt.virtualedit = "onemore"

      return function(lines, phase)
        local eol = vim.fn.col "$"
        if 
           phase < 2 
           and vim.api.nvim_get_mode().mode == "n" 
           and vim.api.nvim_win_get_cursor(0)[2] < eol
        then
          overridden({}, 1)
          debug.setupvalue(overridden, 5, true)
          phase = phase == -1 and 3 or 2
        end
        overridden(lines, phase)
      end
    end)(vim.paste)
```

I hope other people find this useful. If there is a more practical solution that can't broken or is future-proof please let me know... 

Thank you so much for your responses and the great work you all have put in to making this fantastic piece of software.
