### ISSUE TITLE
Problem with system() on Windows

### ISSUE THREAD

**Issue by brglng** [neovim/neovim#2773]
I was trying to get `+python` to work on Windows, however I found there was problem with the implementation of the system() function, called by the python provider. The problem can be produced like this:

For the following vim command:
```vim
:echo system('python -c ' . '"print(''a''); print(''b'')"')
```

Vim gives the expected result, but Neovim gives this:
```
  File "<string>", line 1
    "print('a');
               ^
SyntaxError: EOL while scanning string literal
```
I think the problem may be related with quoting.

Thanks & best regards!

**Comment by equalsraf** [comment]
@brglng, yes most likely quoting. For starters the shellxquote and similar options are wrong in Neovim for Windows([comment](https://github.com/neovim/neovim/pull/810#issuecomment-101978017)).

There was a [hack in this comment](https://github.com/neovim/neovim/pull/810#issuecomment-101905994) to work around it.

**Comment by brglng** [comment]
Thanks! Maybe I will just wait for the fix.

**Comment by brglng** [comment]
@equalsraf 
I cloned the code today and did some testing today.
When invoking `system()`, the arguments nvim passes cmd is:
```c
argv[0] = "cmd";
argv[1] = "/c";
argv[2] = "python -c \"print('a'); print('b')\"";
```
However the python.exe received:
```c
argv[0] = "C:\Python27\python.exe";
argv[1] = "-c";
argv[2] = "\"print('a');"
argv[3] = "print('b')\""
```
More specifically, I tried the following python script:
test.py:
```python
from subprocess import call
call(['cmd', '/c', 'test1.py a "b c"'])
```
test1.py:
```python
import sys
print(repr(sys.argv))
```
You will get this after running `test.py`:
```
['test1.py', 'a', '"b', 'c"']
```
However if `test.py` is changed like this:
```python
from subprocess import call
call(['cmd', '/c', 'test1.py', 'a', 'b c'])
```
You will get this after running `test.py`:
```
['test1.py', 'a', 'b c']
```
Thus, it look like if you want to pass an argument containing spaces as a whole to the program following `cmd /c`, you will also have to pass it as a whole to `cmd`.

**Comment by equalsraf** [comment]
@brglng I did not have a lot of time to dig into this, and I'm not sure to what extent Neovim still respects the shell escaping options - but I have pushed a fix into #810, it turns out libuv was also escaping the arguments.

**Comment by brglng** [comment]
@equalsraf 
It turns out to work here.
However, I still found the `shellxescape` and `shellxquote` is not respected when calling `system()`. I tried to fix it by myself. Here is the patch:
```diff
diff --git a/src/nvim/misc2.c b/src/nvim/misc2.c
index d9bc354..ee04390 100644
--- a/src/nvim/misc2.c
+++ b/src/nvim/misc2.c
@@ -312,28 +312,7 @@ int call_shell(char_u *cmd, ShellOpts opts, char_u *extra_shell_arg)
     /* The external command may update a tags file, clear cached tags. */
     tag_freematch();
 
-    if (cmd == NULL || *p_sxq == NUL)
-      retval = os_call_shell(cmd, opts, extra_shell_arg);
-    else {
-      char_u *ecmd = cmd;
-
-      if (*p_sxe != NUL && STRCMP(p_sxq, "(") == 0) {
-        ecmd = vim_strsave_escaped_ext(cmd, p_sxe, '^', FALSE);
-      }
-      ncmd = xmalloc(STRLEN(ecmd) + STRLEN(p_sxq) * 2 + 1);
-      STRCPY(ncmd, p_sxq);
-      STRCAT(ncmd, ecmd);
-      /* When 'shellxquote' is ( append ).
-       * When 'shellxquote' is "( append )". */
-      STRCAT(ncmd, STRCMP(p_sxq, "(") == 0 ? (char_u *)")"
-          : STRCMP(p_sxq, "\"(") == 0 ? (char_u *)")\""
-          : p_sxq);
-      retval = os_call_shell(ncmd, opts, extra_shell_arg);
-      xfree(ncmd);
-
-      if (ecmd != cmd)
-        xfree(ecmd);
-    }
+    retval = os_call_shell(cmd, opts, extra_shell_arg);
   }
 
   set_vim_var_nr(VV_SHELL_ERROR, (long)retval);
diff --git a/src/nvim/os/shell.c b/src/nvim/os/shell.c
index 5859254..631be21 100644
--- a/src/nvim/os/shell.c
+++ b/src/nvim/os/shell.c
@@ -37,6 +37,43 @@ typedef struct {
 #endif
 
 
+/// Process command string with 'shellxescape' (p_sxe) and 'shellxquote'
+/// (p_sxq)
+///
+/// @param cmd Command string
+/// @return A newly allocated command string. It must be freed with
+///         `xfree` when no longer needed.
+static char *cmd_sxe_sxq(const char *cmd)
+{
+  size_t num_xesc_chars = 0;
+  size_t ncmd_len;
+  char *ncmd;
+  size_t i, j, k;
+
+  if (cmd == NULL || *p_sxq == NUL)
+    ncmd = xstrdup(cmd);
+  else {
+    char_u *ecmd = cmd;
+
+    if (*p_sxe != NUL && STRCMP(p_sxq, "(") == 0) {
+      ecmd = vim_strsave_escaped_ext(cmd, p_sxe, '^', FALSE);
+    }
+    ncmd = xmalloc(STRLEN(ecmd) + STRLEN(p_sxq) * 2 + 1);
+    STRCPY(ncmd, p_sxq);
+    STRCAT(ncmd, ecmd);
+    /* When 'shellxquote' is ( append ).
+     * When 'shellxquote' is "( append )". */
+    STRCAT(ncmd, STRCMP(p_sxq, "(") == 0 ? (char_u *)")"
+        : STRCMP(p_sxq, "\"(") == 0 ? (char_u *)")\""
+        : p_sxq);
+
+    if (ecmd != cmd)
+      xfree(ecmd);
+  }
+
+  return ncmd;
+}
+
 /// Builds the argument vector for running the user-configured 'shell' (p_sh)
 /// with an optional command prefixed by 'shellcmdflag' (p_shcf).
 ///
@@ -58,7 +95,8 @@ char **shell_build_argv(const char *cmd, const char *extra_args)
 
   if (cmd) {
     i += tokenize(p_shcf, rv + i);   // Split 'shellcmdflag'
-    rv[i++] = xstrdup(cmd);          // Push a copy of the command.
+    rv[i++] = cmd_sxe_sxq(cmd);      // Process command string with
+                                     //'shellxescape' and 'shellxquote'
   }
 
   rv[i] = NULL;
```
I have never contributed to an open source project, so please forgive me if anything inappropriate. Thanks!

**Comment by equalsraf** [comment]
@brglng nice! Since the shellxquote and shellxescape are system independent can you start a new PR with these changes, and maybe add some unit tests ([PR guidelines](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#submitting-contributions) here).

**Comment by brglng** [comment]
@equalsraf OK, I will start a PR when I finish. But since I do not know Lua before, it would take some time for me to write the unit tests.

**Comment by equalsraf** [comment]
Thats fine, I don't know much about lua either but I think it would be useful to have some tests for those features. Let me know if you need anything or just ping me when you add the PR.

**Comment by fwalch** [comment]
Regarding the tests, maybe https://github.com/neovim/neovim/blob/master/test/unit/os/shell_spec.lua#L50-L71 can help?

**Comment by brglng** [comment]
I think the test should confirm `shellxescape` and `shellxquote` works, that is, the last argument in the returned argv from `shell_build_argv` is processed with 'sxe' and 'sxq'. e.g., under Windows, when `system('python -c "print(''a'')"')` is called, the actual command is `cmd /c (python -c ^"print^('a'^)^")`, if `set shellxquote=( shellxescape=\"\&\|\<\>\(\)\@\^` is used.

**Comment by equalsraf** [comment]
Luckly there is a similar example in shell_spec.lua e.g. something like this (but with the correct check in the returned argv)

```lua
  describe('shell_build_argv', function()
    setup(function()
      shell.p_sxq = to_cstr('(')
      shell.p_sxe = to_cstr('h')
    end)

    it('applies shellxescape', function()
      local argv = ffi.cast('char**',
                          shell.shell_build_argv(to_cstr('echo hello world'), nil))
      eq(ffi.string(argv[0]), '/bin/bash')
      eq(ffi.string(argv[1]), '-c')
      eq(ffi.string(argv[2]), 'echo hello world')
      eq(nil, argv[3])
    end)

    teardown(function()
      shell.p_sxq = to_cstr('')
      shell.p_sxe = to_cstr('')
    end)
  end)
```

**Comment by brglng** [comment]
Thank you @equalsraf ! That's really helpful. I have added the unit test using your code snippet with some modifications and sent out the PR.

**Comment by brglng** [comment]
I would also like to change the default value of shellpipe, shellxescape and shellxquote under Windows, but I wonder where the good place is to put those default values?

**Comment by equalsraf** [comment]
Usually options.c, best place to look is the original Vim source https://github.com/vim/vim/blob/907639eb33be17f3acc5a3fd314d280bcf2eedfd/src/option.c#L2328

**Comment by brglng** [comment]
Thanks. That's helpful.

**Comment by brglng** [comment]
I found on Windows the `&shell` is automatically set to `"cmd.exe"` however cannot find in the code where `p_sh` is set to "cmd.exe". Do you know where it is set? Thanks.

**Comment by equalsraf** [comment]
Its set in option.c - but it is not merged into master yet only in #810 commit 04fcdf37609e999bea6733b774db6a6ac6b5ad93

**Comment by brglng** [comment]
Thanks!

**Comment by brglng** [comment]
Sorry for the close and reopen. It was a wrong click...

**Comment by raghur** [comment]
I think this is also causing python detection to fail. setting `shellcmdflag` also does not help (used to work earlier - https://www.reddit.com/r/neovim/comments/35li6n/neovim_on_windows_details_in_comments/cr6bzli

**Comment by dnmario** [comment]
Dear Raghu,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] Problem with system() on Windows (#2773)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by equalsraf** [comment]
Even with #2789 this still seems to be broken.

Investigating, but `system("cmd arg1 arg2")` is not the same as `system(['cmd', 'arg1', 'arg2')`. In `tv_to_arg` the first calls shell_build_argv, but the second does not, in fact the second doesn't even call the shell (this is intentional from 74aef89).

Earlier in #810 I've removed the libuv argument escaping because Neovim was already doing it, but maybe we need to bring it back for system([....])
