### ISSUE TITLE
Show warning when not able to access config files

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2774]
@elmart https://github.com/neovim/neovim/issues/2772#issuecomment-107150363
> nvim should warn when not capable of reading/writing config files because of permission issues. Mostly always will be an accident that shouldn't go unnoticed.

**Comment by elmart** [comment]
:+1: Thanks, @fwalch.

**Comment by justinmk** [comment]
Added to https://github.com/neovim/neovim/issues/1202. Want to this close this or keep it separate?

**Comment by elmart** [comment]
No need to keep it separate, IMO.
