### ISSUE TITLE
vim.lsp.start on_init/before_init not respecting changes to config settings

### ISSUE THREAD

**Issue by Kibadda** [neovim/neovim#27740]
### Problem

I change the workspace library for lua_ls based on some conditions. For example, if I am inside my neovim config I add `$VIMRUNTIME` and installed plugins.

`lua-language-server --version`: 3.7.4

Somehow this does not work as expected anymore.

I bisected this to [9f8c962](https://github.com/neovim/neovim/commit/9f8c96240dc0318bd92a646966917e8fe0641144)

### Steps to reproduce

`lua-language-server` in `$PATH`

`init.lua`
```lua
local group = vim.api.nvim_create_augroup("LSP", { clear = true })

vim.api.nvim_create_autocmd("FileType", {
  group = group,
  pattern = "lua",
  callback = function(args)
    vim.lsp.start {
      name = "lua-ls",
      cmd = { "lua-language-server" },
      filetypes = { "lua" },
      on_init = function(client)
        client.config.settings = vim.tbl_deep_extend("force", client.config.settings, {
          Lua = {
            workspace = {
              library = {
                vim.env.VIMRUNTIME,
              },
            },
          },
        })
      end,
      settings = {
        Lua = {
          runtime = {
            version = "LuaJIT",
          },
        },
      },
    }
  end,
})
```

`nvim --clean -u init.lua init.lua`
Pressing `K` over any `vim` shows `(global) vim: unknown`

### Expected behavior

Pressing `K` over any `vim` shows correct type information

## Workaround
If I change `on_init` function to: (`Lua` key moved outside of `vim.tbl_deep_extend`)
```lua
      on_init = function(client)
        client.config.settings.Lua = vim.tbl_deep_extend("force", client.config.settings.Lua, {
          workspace = {
            library = {
              vim.env.VIMRUNTIME,
            },
          },
        })
      end,
```
Then this works as expected.

### Neovim version (nvim -v)

v0.10.0-dev-2514+g5b312cd5f

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch linux

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by clason** [comment]
So this _does_ work correctly, and you're just wondering whether the change in interface was intended?

**Comment by Kibadda** [comment]
Yes that is a better way of saying this. Sorry.

**Comment by abeldekat** [comment]
Thanks @Kibadda!

I have also been busy with the problem. See this [Neovim issue](https://github.com/neovim/neovim/issues/27730), and this [nvim-lspconfig issue](https://github.com/neovim/nvim-lspconfig/issues/3052)

Your solution works on both `0.9.5` and `nightly`.
I created a [PR](https://github.com/neovim/nvim-lspconfig/pull/3054) for `nvim-lspconfig`.

**Comment by lewis6991** [comment]
Ah yes, this is a intentional change. `vim.lsp.Client` now has it's own reference to every field in `vim.lsp.ClientConfig` so overwriting the reference in `client.config.settings` will no longer work, instead you should change `client.settings`.

**Comment by clason** [comment]
Please report (and ideally make PR) to nvim-lspconfig.

**Comment by abeldekat** [comment]
@clason, the [PR](https://github.com/neovim/nvim-lspconfig/pull/3054) has been merged.
