### ISSUE TITLE
`WinEnter` event not triggerd after exiting builtin terminal

### ISSUE THREAD

**Issue by Bekaboo** [neovim/neovim#27744]
### Problem

`WinEnter` event not triggerd after exiting builtin terminal.

### Steps to reproduce

1. Create the minimal repro config `minimal.lua`:

    ```lua
    vim.api.nvim_create_autocmd('WinEnter', {
        callback = function(info)
            vim.print(info)
        end
    })
    ```

2. `nvim --clean -u minimal.lua`
3. Use `<C-w>n` to create a new buffer in a new split
4. `:bw` to wipe out new buffer, notice that the callback for `WinEnter` event is triggered
5. `:bel term` to open a terminal in a new split
6. `exit` to close the terminal, notice that the callback for `WinEnter` event is not triggered

### Expected behavior

`WinEnter` event should trigger when a terminal is closed and the cursor enters a new window.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2363+gb76a01055f

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux 6.7.4-arch1-1

### Terminal name/version

alacritty 0.13.1 (fe2a3c56)

### $TERM environment variable

xterm-256color

### Installation

AUR

**Comment by zeertzjq** [comment]
This is already fixed.
