### ISSUE TITLE
Add `SessionWritePost` event

### ISSUE THREAD

**Issue by ColinKennedy** [neovim/neovim#27761]
### Problem

The use-case described below may be solvable already but I wasn't sure how to achieve it. Another idea came to me instead.

Suppose you have 2 plugins, both of which extend the default `:mksession` with extra data. They implement this by appending extra data needed by the plugin to the end of the Session.vim, like so

```vim
function plugin_a#make_session()
    let l:file_path = "Session.vim"
    execute "mksession " . l:file_path
    " Add stuff to l:file_path
endfunction

command PluginAMakeSession call plugin_a#make_session()
```

```vim
function plugin_b#make_session()
    let l:file_path = "Session.vim"
    execute "mksession " . l:file_path
    " Add stuff to l:file_path
endfunction

command PluginBMakeSession call plugin_b#make_session()
```

If the user of both plugins wants to have a Session.vim that contains the contents of both plugin a and b, they can't because the plugins overwrite each other's data. The user could modify the plugins to play nice but I was thinking there could be an alternate, better way - expose an autocmd called `SessionWritePost`.

### Expected behavior

Neovim supports `SessionWritePost`. When triggered, `v:saved_session` (Edit: Update, forgot about `v:this_session`. So no new `v:saved_session` would be required) points to the absolute path on-disk here a session file was written. Then plugin a and b can choose to apply their changes by appending to the created file, like so:

```vim
function plugin_a#append_to_session_path(file_path)
    " Append extra data to a:file_path, below
endfunction

autocmd SessionWritePost * call plugin_a#append_to_session_path(v:saved_session)
```

```vim
function plugin_b#append_to_session_path(file_path)
    " Append extra data to a:file_path, below
endfunction

autocmd SessionWritePost * call plugin_b#append_to_session_path(v:saved_session)
```

With a unified autocmd to trigger from, both plugins can append their relevant data to to the session and then the user can later load the Session.vim file as normal and expect to see Vim's + plugin a's + plugin b's settings.

A possible issue with this idea would be that mksession has a footer at the end of the file e.g. `" vim: set ft=vim :`. If plugin a and b appended to the end, it would move the footer to the middle of the file. Not sure if that footer is important. Though plugin a and b could possibly append to the beginning of Session.vim instead.

**Comment by ColinKennedy** [comment]
A couple more use cases came up since writing this issue to mention

I need a way to broadcast whenever a session is saved so that the saved Session.vim can be collected into a globalized list. Having a `SessionWritePost` would make this much easier to integrate with existing plugins.

I also see that https://github.com/Shatur/neovim-session-manager has to define their own `User` commands, which emits pre-/post- `:mksession`. That works for that plugin but I won't be able able to make a generic solution for all plugins without a standardized autocmd, I think.

If maintainers are up for this, I can make a PR. Maybe worth raising to see if Vim maintainers want this first? Thoughts?

**Comment by justinmk** [comment]
> Maybe worth raising to see if Vim maintainers want this first?

yes

**Comment by ColinKennedy** [comment]
Thank you @zeertzjq!
