### ISSUE TITLE
completeopt=popup crashing neovim

### ISSUE THREAD

**Issue by deathbeam** [neovim/neovim#27768]
### Problem

When using

```lua
vim.o.completeopt = 'menuone,noinsert,popup'
```

vim is sometimes crashing on either free or malloc issues. This issue is not very frequent but it never happens without popup enabled. I have no issues or crashes with any other floating windows. With popup enabled it looks like it is most easily reproducable when completing vim.keymap.set (but still do not happens that often, but after minute or two trying it will).

![image](https://github.com/neovim/neovim/assets/5115805/83f558f5-d5bb-4649-8885-971465f18569)

### Steps to reproduce

How I got this issue:
- Use this plugin - https://github.com/deathbeam/autocomplete.nvim/blob/main/lua/autocomplete/buffer.lua
- Configure:
```
vim.o.completeopt = 'menuone,noinsert,popup'
require('autocomplete.buffer').setup()
```
- Start typing using Lua lsp
```
vim.keymap.set
```
- Repeat/delete chars until bug occcurs

What the plugin does is when completion changes it:
1. Does completionItem/resolve
2. Closes current popup if open (different bug but it do not updates its size,but I saw the bug happen wthout this as well)
3. Calls
```
local wininfo = vim.api.nvim_complete_set(selected, { info = value })
if wininfo.winid and wininfo.bufnr then
    vim.wo[wininfo.winid].conceallevel = 2
    vim.wo[wininfo.winid].concealcursor = 'niv'
    vim.bo[wininfo.bufnr].syntax = 'markdown'
    return true
end
```

I suspect that nvim_complete_set is causing the issue. Im 90% sure the plugin is implemented correctly but even if it isnt opening popup window should not be crashing neovim.

### Expected behavior

No crashing

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2531+gdc2379b89

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux x86_64

### Terminal name/version

st

### $TERM environment variable

tmux-256color

### Installation

repo

**Comment by glepnir** [comment]
a known bug and this pr https://github.com/neovim/neovim/pull/26739 should fix .but i am waiting previewpopup pr..

**Comment by glepnir** [comment]
could you try this pr https://github.com/neovim/neovim/pull/27869.

**Comment by deathbeam** [comment]
> could you try this pr #27869 ? thanks.

Tried it, managed to crash it rather quicly, twice:

![image](https://github.com/neovim/neovim/assets/5115805/c06d10ee-8efe-4cee-a476-d6b53aa7a041)

![image](https://github.com/neovim/neovim/assets/5115805/04a13636-ac9b-4bc3-9a44-c7b4737a82e2)

**Comment by glepnir** [comment]
Oh I know what happen here.. sry for my mistake and please wait for a while .

**Comment by glepnir** [comment]
@deathbeam  could you try https://github.com/neovim/neovim/pull/26739
