### ISSUE TITLE
New regular expression atoms for WORD-boundaries

### ISSUE THREAD

**Issue by jbyler** [neovim/neovim#27782]
### Problem

Regular expressions can use the `\<` and `\>` atoms to match the position at the start or end of a word (using the iskeyword definition), but there is no atom to match at the start or end of a WORD (whitespace-delimited).

### Expected behavior

I would like to request new regex atoms that match at the beginning and end of a whitespace-delimited WORD. The atoms should be zero-width, just like `\<` and `\>`.

I'm not partial to what the atoms are, but for the sake of describing the feature, let's call them `\_<` and `\_>`.

Then, let's use this file for an example:

```
public class Example {
    static final String BOOK = "The Republic";
    static final String pub_sub_url = "http://non-public.server.io";
}
```

The desired behavior is that I can search with the regex `\_<pub` and I should see two matches: the "pub" at the beginning of "**pub**lic" and the "pub" at the beginning of "**pub**_sub_url", because in each case the match is at a WORD boundary. The "pub" in the middle of "Re**pub**lic" and the "pub" in "non-**pub**lic.server" should not match, because there is no WORD boundary.

Similarly for `\_>`, it should match only at the *end* of a WORD.

### Alternatives Considered

Without dedicated atoms for WORD boundaries, it's possible to achieve this behavior in one of three ways:

1. Accurate emulation of the atoms

`\S\@<!\S\@=` matches at the start of a WORD boundary, and `\s\@<!\S\@!` matches at the end. They behave similarly to how `\<` and `\>` behave, but for WORDs. This is the behavior I would like, but it's quite clunky and hard to remember, for something that is a common and straightforward scenario.

2. Less accurate emulation

`\S\@<!` for start of WORD and `\S\@!` for end of WORD work well as part of a larger pattern, but give incorrect results when used alone. They are easier to remember but still fairly clunky.

3. Changing `iskeyword`

Setting the `iskeyword` option to the value `!-~` changes `\<` and `\>` to have the desired behavior. This too is clunky, and needs to be reset afterwards, and cannot be combined in the same pattern with the word-boundary atoms (since it effectively overwrites those atoms with a new definition).

### Additional Context

A detailed discussion of the problem and the existing workarounds are [here](https://stackoverflow.com/q/55522385/2562319) on StackOverflow. I think the workarounds are clunky and that a new dedicated atom for this use case would be a better solution.

I use both NeoVim and vim, and I filed this feature request for both. The corresponding request for vim is [here](https://github.com/vim/vim/issues/14164).

**Comment by lewis6991** [comment]
We don't own, maintain or develop the vim regular expression engine.

Please raise an issue on vim/vim instead.

**Comment by jubilatious1** [comment]
@jbyler apologies in advance you could think about trying out a new Regex Engine. I've tried Perl6 (a.k.a. Raku) and can do some amazing things. It does a great job on Unicode. Word boundaries are well documented:

https://docs.raku.org/language/regexes#Word_boundary    
https://docs.raku.org/language/regexes#Left_and_right_word_boundary

And here's an example:

https://unix.stackexchange.com/a/712339/227738

Run the code at the Vim/Neovim command line thusly:
```
:%!  raku -pe 's:g/<|w> \w**2..3 <|w>/{$/.uc}/;' 
```
HTH.
