### ISSUE TITLE
Explain that the root node is not displayed in InspectTree

### ISSUE THREAD

**Issue by Lattay** [neovim/neovim#27787]
### Problem

When writing a plugin using tree-sitter I found myself looking for the "top level" node under the cursor.
My solution was to repeatedly do `node = node:parent()` until `node:parent()` was nil.
I expected that to give me what the InspectTree shows as top level, but obviously it gave me the root node.
It would be nice to make somehow clearer that the root node is not displayed in InspectTree (or, even better in my opinion, to display the root node).

### Expected behavior

It should be clear to the user that all "top level" nodes displayed in `:InspectTree` are children of the root node.

**Comment by clason** [comment]
#26944
