### ISSUE TITLE
Downloading 'nvim-linux64.tar.gz' by following wiki results corrupt file

### ISSUE THREAD

**Issue by niamotullah** [neovim/neovim#27790]
### Problem

As the documentation describe to install `neovim` on Linux ([here](https://github.com/neovim/neovim/blob/master/INSTALL.md#linux)) are somehow resulting a corrupt binary. So it can't be extracted, hence i get the following error:
```
$ tar xzf nvim-linux64.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

When i downloaded the file through same link but using `axel` it worked just fine. and resulting file matched with the [released](https://github.com/neovim/neovim/releases/tag/v0.9.5) SHA256 Checksums (44ee395d9b5f8a14be8ec00d3b8ead34e18fe6461e40c9c8c50e6956d643b6ca)

To make sure i downloaded using `curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz` 3 times, and they resulted 3 different SHA256 hashes.

![Screenshot from 2024-03-10 03-08-22](https://github.com/neovim/neovim/assets/58494481/ebe57fcd-b003-4aaa-b30d-cc27474bdc7f)

### Steps to reproduce

>```
>curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
>tar -xzf nvim-linux64.tar.gz
>```

### Expected behavior

should successfully extract the file

### Neovim version (nvim -v)

blank

### Vim (not Nvim) behaves the same?

blank

### Operating system/version

Ubuntu 23.10

### Terminal name/version

Nushell V0.91.0

### $TERM environment variable

xterm-256color

### Installation

NeoVim wiki (https://github.com/neovim/neovim/blob/master/INSTALL.md#linux)

**Comment by wookayin** [comment]
Using `curl` on Linux, I can download the correct nvim-linux64.tar.gz with the exactly same SHA256 checksum as expected. The situation you described is probably because `curl` failed to resolve something (e.g. SSL certificate issue), or just an temporary error.

```
44ee395d9b5f8a14be8ec00d3b8ead34e18fe6461e40c9c8c50e6956d643b6ca  nvim-linux64.tar.gz
```

Can you check the content and the size of the downloaded (corrupted) file? You can open the file with vim, e.g. `nvim nvim-linux64.tar.gz`.
