### ISSUE TITLE
provider/python{x,3}.vim load time

### ISSUE THREAD

**Issue by ianks** [neovim/neovim#2780]
I have noticed by running `vim --startuptime vim.log` that the python3 provider takes about 180ms to load on my (very fast) machine. I am worried this may be a bit slow for some users. What do you think? You guys were proably already aware of this, and if there is an issue already I apologize in advance. Cheers!

```
461.818  133.544  133.544: sourcing /usr/share/nvim/runtime/autoload/provider/python3.vim
640.350  313.685  179.885: sourcing /home/ianks/.vim/plugged/ultisnips/autoload/UltiSnips/map_keys.vim
```

**Comment by Shougo** [comment]
Unfortunately, Python3 loading is slower than Python2.
You can disable the check by `g:python3_host_skip_check`.
Or you should use lazy loading for UltiSnips.

**Comment by ianks** [comment]
Awesome. I ended up lazy loading UltiSnips and that helped a lolt. There is still significant overhead with `pythonx.vim` and `python.vim`, is there a way to skip check for that?

**Comment by Shougo** [comment]
You can skip the check by `g:python_host_skip_check`.

**Comment by ianks** [comment]
@Shougo What negative consequences might there be from doing that?

**Comment by Shougo** [comment]
If you enable `g:python_host_skip_check`, your neovim must install neovim python module.
Because, it skips if the module is installed.
