### ISSUE TITLE
Sidebar obscures content on online help docs (neovim.io website)

### ISSUE THREAD

**Issue by adigitoleo** [neovim/neovim#27802]
### Problem

A picture is worth 2^10 words:

![neovim-io-sidebar-ui](https://github.com/neovim/neovim/assets/34595875/4d12114c-39db-4983-8cd3-0dcf1631c3cc)

Probably should make it collapsible?

### Steps to reproduce

Open a doc site from neovim.io e.g. http://neovim.io/doc/user/treesitter.html

### Expected behavior

I can haz online docs.

### Neovim version (nvim -v)

Website accessed 10/03/2024

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

**Comment by clason** [comment]
Website css lives in neovim/neovim.github.io
