### ISSUE TITLE
fswatch: Event queue overflow with pyright lsp in git repo

### ISSUE THREAD

**Issue by deathbeam** [neovim/neovim#27807]
### Problem

![image](https://github.com/neovim/neovim/assets/5115805/c701b356-2c54-4447-b999-ed672f2b16fc)

When opening python file with pyright lsp (im assuming pyright lsp is the cause) I get event queue overflow error twice. I am not sure if it has any implication as after that everything works fine but it must mean something I guess.

### Steps to reproduce

```bash
mkdir test-repro
cd test-repro
git init
touch minimal.lua
touch test.py
nvim --clean -u minimal.lua test.py
```

Contents of minimal.lua
```lua
-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs {
    nvim_lspconfig = 'https://github.com/neovim/nvim-lspconfig',
    mason = 'https://github.com/williamboman/mason.nvim',
    mason_lspconfig = 'https://github.com/williamboman/mason-lspconfig.nvim'
  -- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
  -- some_plugin = 'https://github.com/author/plugin.nvim'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE

require("mason").setup()
require("mason-lspconfig").setup {
    ensure_installed = { "pyright" },
    handlers = {
        pyright = function()
            require('lspconfig').pyright.setup({
              settings = {
                python = {
                    analysis = {
                        diagnosticMode = 'workspace',
                        diagnosticSeverityOverrides = {
                            reportOptionalSubscript = 'none',
                            reportOptionalMemberAccess = 'none',
                            reportOptionalCall = 'none',
                            reportOptionalIterable = 'none',
                            reportOptionalContextManager = 'none',
                            reportOptionalOperand = 'none',
                        },
                    },
                },
              }
            })
        end
    }
}
```

### Expected behavior

No error

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2553+gb465ede2c

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux x86_64

### Terminal name/version

st

### $TERM environment variable

tmux-256color

### Installation

repo

**Comment by deathbeam** [comment]
Looking at fswatch documentation this error should probably not be handled as actual error:

```
The inotify monitor, available on Linux since kernel 2.6.13, may suffer a queue overflow if events are generated faster than they are read from the queue. In any case, the application is guaranteed to receive an overflow notification which can be handled to gracefully recover. fswatch currently throws an exception if a queue overflow occurs. Future versions will handle the overflow by emitting proper notifications.
```

**Comment by lewis6991** [comment]
This is just a limitation of Linux and pyright asking to watch too many files. It's not really a problem we can feasibly solve.

**Comment by deathbeam** [comment]
@lewis6991 Sure but at least adding some documentation or improving the error message might help. For example intellij tells you to increase inotify limits if it detects they are too low. The current behaviour where it just throws error message twice for something that is supposed to be just notification per fswatch docs is not very good.

**Comment by lewis6991** [comment]
Ok. Will review a PR.

**Comment by deathbeam** [comment]
Oh, also another thing, I was looking at the PR that implemented this feature and there is this: https://github.com/neovim/neovim/pull/27347/files#diff-bfeb92628ce760a1e10360bddb9393ad66b5396a26c0cb7fcdcd39bc60eaa194R283

That is supposed to ignore the .git directory I assume but I cannot reproduce this issue when I remove the .git directory so maybe similar check is missing somewhere else or its not working?

**Comment by deathbeam** [comment]
Yea looks like it isnt working, I will make a PR with a fix

**Comment by lewis6991** [comment]
I think that's probably a red herring. Pyright only asks to watch virtual env directories so it shouldn't be watching .git anyway.

**Comment by deathbeam** [comment]
Hmm, found this and it looks like --exclude actually doesnt do anything with --recursive specified:

https://github.com/emcrisostomo/fswatch/issues/151

So the PR isnt as easy as i thought. thought about adjusting the regex, as that one is also slightly wrong but I think as per https://github.com/emcrisostomo/fswatch/issues/151 the change would need to provide list of files beforehand, but that would also break watching for new files I assume.

**Comment by deathbeam** [comment]
Actually I think the real issue was that pyright changed from single file mode to workspace mode when I added .git dir and then it started watching python lib so even if my .git dir was empty same issue, so probs just the documentation is needed, closing again I guess

**Comment by ErickKramer** [comment]
Is there a workaround this behavior?

I just tried out latest master (NVIM v0.10.0-dev-3060+gd26943a6e) and I get similar behavior as reported in here.

Having a simple file in a clean directory /tmp/stuff/dummy.py

```python
print("Hello World")
```

I get pyright running as single file

```console
 Client: pyright (id: 2, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             /home/ekramer/.local/share/nvim/mason/bin/pyright-langserver --stdio
```

However, as soon as I initialize `/tmp/stuff` as a git repository

I encounter the `fswatch: inotify(7) limit reached` error message 

and pyright changes its running mode

```console
 Client: pyright (id: 2, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  /tmp/stuff
 	cmd:             /home/ekramer/.local/share/nvim/mason/bin/pyright-langserver --stdio
```

and if I do any jumping to a third-party library I encounter

```console
inotify_add_watch: No space left on device
```

I followed the recommendation in the fswatch help and added these lines to /etc/sysctl.conf

```conf
sysctl fs.inotify.max_user_watches=100000
sysctl fs.inotify.max_queued_events=100000
```

I have no issues at all working with pyright on nvim-0.9.5.
