### ISSUE TITLE
Make NVIM_TUI_ENABLE_TRUE_COLOR compatible with colourschemes that check has('gui_running')

### ISSUE THREAD

**Issue by frankier** [neovim/neovim#2781]
Previously: https://github.com/neovim/neovim/pull/2198 and https://github.com/neovim/neovim/issues/2140

The suggestion is:

1. Change the colourscheme command to just set an internal variable.
2. Actually execute the colourscheme every time a UI is attached.

This way has('gui_running') will have the correct value when the colourscheme is executed.

**Comment by justinmk** [comment]
We _could_ do this... but it will still have edge cases. `has('gui_running')` is a VimL expression and VimL is executed by the nvim server. Returning a different value at different times is bound to invite other bugs. Let's keep it simple. See https://github.com/neovim/neovim/pull/4155

**Comment by justinmk** [comment]
`has('gui_running')` is now supported in Nvim 0.9 https://github.com/neovim/neovim/pull/22382
