### ISSUE TITLE
`<C-Space>` as mapleader doesn't work and gives unexpected behavior

### ISSUE THREAD

**Issue by bew** [neovim/neovim#27826]
### Problem

Using `<C-Space>` as map leader does not work, see full repro below

### Steps to reproduce

1. In file `repro.vim`:
	```vim
	let g:mapleader = "<C-Space>"
	
	echo "setting keymap via C-Space"
	nnoremap <C-Space>hi <cmd>echo 'hello normally!'<cr>
	echo "checking <C-Space> mappings"
	map <C-Space>
	echo " "
	
	echo "setting keymap via Leader"
	nnoremap <Leader>ho <cmd>echo 'hello via <Leader>!'<cr>
	echo "checking <Leader> mappings"
	map <Leader>
	echo " "
	
	echo "checking <C-Space> mappings again?"
	map <C-Space>
	echo " "
	```

2. Open nvim using `nvim -u repro.vim`, see the following prints:
	```
	setting keymap via C-Space
	checking <C-Space> mappings
	n  <C-Space>hi * <Cmd>echo 'hello normally!'<CR>
	
	setting keymap via Leader
	checking <Leader> mappings
	n  <C-Space>ho * <Cmd>echo 'hello via <C-Space>!'<CR>
	
	checking <C-Space> mappings again?
	n  <C-Space>hi * <Cmd>echo 'hello normally!'<CR>
	```
3. ❌ Notice that checking for `:map <Leader>` & `:map <C-Space>` is different even though `<Leader> == <C-Space>`, even though both show mappings starting with `<C-Space>`.. 👀
4. Dismiss the prints and try to use the keys...
5. ✔ `<C-Space>hi` works and prints `hello normally!`
6. ❌ `<Leader>ho` (`<C-Space>ho`) do not work, as if `<C-Space>` was completely skipped..

### Expected behavior

The following print:
```
setting keymap via C-Space
checking <C-Space> mappings
n  <C-Space>hi * <Cmd>echo 'hello normally!'<CR>

setting keymap via Leader
checking <Leader> mappings
n  <C-Space>hi * <Cmd>echo 'hello normally!'<CR>
n  <C-Space>ho * <Cmd>echo 'hello via <C-Space>!'<CR>

checking <C-Space> mappings again?
n  <C-Space>hi * <Cmd>echo 'hello normally!'<CR>
n  <C-Space>ho * <Cmd>echo 'hello via <C-Space>!'<CR>
```

And both `<C-Space>hi` & `<Leader>ho` mappings to work and print their respective messages.

### Neovim version (nvim -v)

0.9.5 & v0.10.0-dev-2559+g3814750d3

### Vim (not Nvim) behaves the same?

yes for the prints, no when testing keys; vim 9.0

### Operating system/version

Linux (NixOS)

### Terminal name/version

Wezterm 20240203-110809-5046fc22

### $TERM environment variable

tmux-256color

### Installation

Nix

**Comment by zeertzjq** [comment]
You are setting leader to the literal `<C-Space>` string. You should use `:let g:mapleader = "\<C-Space>"`

**Comment by bew** [comment]
Oooh that was it for that repro script!

And for Lua I did:
```lua
vim.g.mapleader = vim.api.nvim_replace_termcodes([[<C-Space>]], true, true, true)
```
❤

I'll let you close it when you want then

**Comment by bew** [comment]
I think it would greatly help to have the keycode `<C-Space>` highlighted specially in `:map` output, to at least visually differentiate the prints

**Comment by justinmk** [comment]
> I think it would greatly help to have the keycode `<C-Space>` highlighted specially in `:map` output, to at least visually differentiate the prints

That sounds like a different issue
