### ISSUE TITLE
[Windows] Nightly release triggers Windows Defender virus detection

### ISSUE THREAD

**Issue by TheLeoP** [neovim/neovim#27838]
### Problem

Trying to download the [nightly release](https://github.com/neovim/neovim/releases/tag/nightly) for Windows (either the `.zip` file or the `.msi`) file triggers the Windows defender virus detection.

Windows defender claims to have found `Trojan:Win32/Wacatac.B!ml` in the `markdown_inline.dll` bundled with the Nightly release of Neovim. This just started happening recently.

### Steps to reproduce

1. Use a recentish (I think?) version of Windows 11
2. Enable Windows Defender
3. Try to download either [nvim-win64.msi](https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.msi) or [nvim-win64.zip](https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip)
4. Windows defender deletes the downloaded file because of the supposed detection of a Trojan on the `markdown_inline.dll`.

### Expected behavior

Windows defender should not flag the latest release of Neovim as a virus.

### Neovim version (nvim -v)

Doesn't apply

### Vim (not Nvim) behaves the same?

Doesn't apply

### Operating system/version

Windows 11 Pro 23H2

### Terminal name/version

Doesn't apply

### $TERM environment variable

Doesn't apply

### Installation

Nightly release page, Github

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/issues/5433
