### ISSUE TITLE
Line numbers not appearing in some terminal buffers.

### ISSUE THREAD

**Issue by TheSoftwareGuy** [neovim/neovim#2784]
to reproduce with `nvim -u NONE`:

    start editor
    :set number
    :vsp (or :sp, should happen for either)
    :term
    <c-\><c-n>
    (switch to the other split with <c-w>l or <c-w>j or whatever is relevant)
    :bn

one of the terminal splits will now display line numbers, while the other does not.

**Comment by equalsraf** [comment]
Confirmed here in Linux, running off 27dc315, it looks like this, also happens with -u NONE

![bug](https://cloud.githubusercontent.com/assets/715238/7955374/d382643a-09cf-11e5-911f-10c82eb61ba0.png)

**Comment by Shougo** [comment]
Confirmed.  But it seems feature.
Line number is disabled in terminal buffers.

**Comment by Shougo** [comment]
*'number'* *'nu'* *'nonumber'* *'nonu'*
'number' 'nu'		boolean	(default off)
			local to window
	Print the line number in front of each line.  When the 'n' option is
	excluded from 'cpoptions' a wrapped line will not use the column of
	line numbers (this is the default when 'compatible' isn't set).
	The 'numberwidth' option can be used to set the room used for the line
	number.
	When a long, wrapped line doesn't start with the first character, '-'
	characters are put before the number.
	See |hl-LineNr|  and |hl-CursorLineNr| for the highlighting used for
	the number.

The 'number' option is window local option.
So in the other windows, line number is displayed.

**Comment by TheSoftwareGuy** [comment]
@Shougo, I am not sure what you mean, if we decide not to show line numbers in terminal panes, we should at least be consistent about it.

**Comment by Shougo** [comment]
Line number is disabled in terminal window.
Unfortunatelly, it is *window* local option.
So other windows line number is displayed.
It is Vim's feature.
I don't know why it is window local option.

**Comment by TheSoftwareGuy** [comment]
Okay, that makes sense.

**Comment by Shougo** [comment]
neovim may change the 'number' option as buffer local.
@tarruda  What do you think?

**Comment by tarruda** [comment]
> neovim may change the 'number' option as buffer local.
@tarruda What do you think?

Not sure if it wise to touch this: Maybe an user wants to see the same file in two windows and one of them without line numbers(doesn't make sense to me, but it's possible in vim)
