### ISSUE TITLE
Command line tools are not install even the CLT are installed.

### ISSUE THREAD

**Issue by deepas393** [neovim/neovim#2785]
I have xcode 6.1 and installed command line tools for xcode 6.1 and it is install in the path "/Library/Developer/CommandLineTools". I am using Appium tool for mobile automation, it is showing CLT are not installed. Please help me to solve this issue.

Do we need to set CLT path as active directory? if so please tell me how can we do this.

**Comment by deepas393** [comment]
![screen shot 1937-03-13 at 10 16 45 am](https://cloud.githubusercontent.com/assets/11499904/7952851/ccdb42aa-09d9-11e5-8dce-e20fd549f9dd.png)

**Comment by deepas393** [comment]
It says  Xcode Command Line Tools are NOT installed: Error: Command failed: /bin/sh -c pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
/bin/sh: pkgutil: command not found

**Comment by fwalch** [comment]
As far as I can see, this has nothing to do with Neovim. You mentioned Appium, perhaps https://github.com/appium/appium is an appropriate place to ask your question?

**Comment by deepas393** [comment]
I got solution for this issue i.e. I set the path of /usr/sbin on bash profile and then enable the dsenableroot, then everything worked fine..:)

**Comment by deepas393** [comment]
when I open Appium inspector and select the element from the hierarchy the corresponding element should enable but the element is not highlighting. Could anyone please what I am missing here?
