### ISSUE TITLE
Allow opening man pages in the current window

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#27860]
### Problem

Currently `:Man` forces using separate window unless the current buffer has alerady `man` filetype. It can be simply achieved by adding simple modifier to `man.open_page`, for example as a fake modifier:

```diff
diff --git a/runtime/lua/man.lua b/runtime/lua/man.lua
index ac15aff60..0657e4e9e 100644
--- a/runtime/lua/man.lua
+++ b/runtime/lua/man.lua
@@ -716,7 +716,7 @@ function M.open_page(count, smods, args)
   local target = ('%s(%s)'):format(name, sect)

   local ok, ret = pcall(function()
-    if smods.tab == -1 and find_man() then
+    if smods.curwin or (smods.tab == -1 and find_man()) then
       vim.cmd.tag({ target, mods = { silent = true, keepalt = true } })
     else
       smods.silent = true
```

In practice I'd like to open man page by nvim from the shell without using `MANPAGER` environment variable. 

By default I run `nvim` inside `systemd-run` container (I hope "container" it's the correct term) and have terminal related issues (probably because `man` is run outside the container, but `nvim` inside it). 

In practice, the number of lines are not correctly refreshed after zooming in and out in tmux window.

### Expected behavior

- allow opening man pages in the current window at least from `man.open_page`
- optionally extend `Man` command to allow use it too

**Comment by neel-kumar** [comment]
In terms of opening the Man pages in a different buffer, neovim already has a command that accomplishes this. `:Man | only` Opens the Man page in a different buffer.

**Comment by przepompownia** [comment]
> In terms of opening the Man pages in a different buffer, neovim already has a command that accomplishes this. `:Man | only` Opens the Man page in a different buffer.

In that case the initial unnamed buffer still exists:
![image](https://github.com/neovim/neovim/assets/11404453/aa2424fa-4fca-41df-bbaf-5febe7062738)

**Comment by neel-kumar** [comment]
Ok, I think this is just how only works. I don't know why it does this. Typing in `:help help | only` also produces some weird behavior for the buffers. Hopefully, using only is good enough for now.
