### ISSUE TITLE
background colors not working

### ISSUE THREAD

**Issue by nschloe** [neovim/neovim#2786]
I'd love to use nvim for my day-to-day work, but one thing is keeping me back for now, namely the background colors: In neovim, they don't appear. This influences the appearance for vim-airline and also some other things.

In vim-legacy:
![legacy](https://cloud.githubusercontent.com/assets/181628/7965748/ceef6ba2-0a1f-11e5-8caa-c94feb7b02c5.png)

In neovim:
![neo](https://cloud.githubusercontent.com/assets/181628/7965755/d459941e-0a1f-11e5-962d-07550a06a112.png)

The long lines are highlighted with
```
" Highlight rows which are too long
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/
```

**Comment by Grimy** [comment]
I can’t reproduce this: running those two lines correctly produced red highlighting for me. My guess is that your terminal isn’t properly supported by libvterm.

* What terminal are you using?
* Can you reproduce this issue with `nvim -u NONE`?

**Comment by nschloe** [comment]
> What terminal are you using?

gnome-terminal

> Can you reproduce this issue with nvim -u NONE?

How can I create a background color then? (I've always put the {n}vim configs in `~/.vimrc`.)

**Comment by Grimy** [comment]
> How can I create a background color then? (I've always put the {n}vim configs in ~/.vimrc.)
Hit `:`, type `highlight OverLength ctermbg=red ctermfg=white guibg=#592929`, hit enter.
Hit `:`, type `match OverLength /\%81v.\+/`, hit enter.

I can’t reproduce the issue on gnome-terminal, so this is almost certainly a problem with your config. You could try bisecting to find out which lines in your vimrc are causing the issue.

**Comment by nschloe** [comment]
Even if I have only 
```
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/
```
in my config, I get background colors in vim and no background colors in nvim. This is with gnome-terminal and xterm. Hm, maybe some environment variable that makes trouble?

**Comment by nschloe** [comment]
Got it.
```
$ echo $TERM
xterm
```
although I am in a gnome-terminal. Now I'll have to find why this gets set...

**Comment by nschloe** [comment]
So, this is apparently a common thing and the default setting in Ubuntu, cf. [ask ubuntu](https://askubuntu.com/questions/233280/gnome-terminal-reports-term-to-be-xterm). Apparently, Ubuntu 15.10 is scheduled to feature vte-0.40 which sets `TERM` not ` xterm` but `xterm-256colors`.

Is terminal detection something that nvim may improve?

**Comment by Grimy** [comment]
Glad you found the problem. Make sure your `$TERM` is always set to `xterm-256colors` when you are using xterm, and to `gnome-terminal` when using gnome-terminal. This way you will have colors with both vim and nvim, and other 

nvim delegates terminal detection to termkey and unibilium, which handle it much better than vim ever did. Case in point, vim was incorrectly displaying colors when it shouldn’t have, which masked the underlying problem in your environment.

This can be closed, since it’s not an issue with Neovim.
