### ISSUE TITLE
nvim_buf_set_extmark with virt_lines messes up the cursor when conceallevel and concealcursor is set

### ISSUE THREAD

**Issue by deathbeam** [neovim/neovim#27887]
### Problem

When using extmark with virt_lines and conceallevel + concealcursor, the cursor gets messed up. It do not skips over virt lines and it also sometimes completely refuses to update and gets stuck. This do not happens in v0.9.5 release where it works correctly with no issues with same config (just opening new window is slightly different ofc from steps to reproduce).

For additional full reproduction, you can also use https://github.com/CopilotC-Nvim/CopilotChat.nvim plugin on commit [55722d7](https://github.com/CopilotC-Nvim/CopilotChat.nvim/commit/55722d7b3131ef6d2441e379d9c64c5991b0cf5c) and simply run `CopilotChatOpen` and notice the messed up cursor. Also works fine on v0.9.5.

### Steps to reproduce

minimal.lua
```lua
-- Run this file as `nvim --clean -u minimal.lua`
vim.api.nvim_create_user_command('Test', function()
    local ns = vim.api.nvim_create_namespace('my_namespace')
    local bufnr = vim.api.nvim_create_buf(false, true)

    local opts = {
        id = ns,
        hl_mode = 'combine',
        priority = 100,
        virt_lines_leftcol = true,
        virt_lines = {
            { { '| Hello', 'DiagnosticInfo' } },
            { { '| World', 'DiagnosticInfo' } },
        },
    }

    vim.api.nvim_buf_set_text(
        bufnr,
        0,
        0,
        0,
        0,
        { '', '' }
    )

    vim.api.nvim_buf_set_extmark(bufnr, ns, 0, 0, opts)

    local winnr = vim.api.nvim_open_win(bufnr, false, {
        vertical = true
    })

    vim.wo[winnr].conceallevel = 2
    vim.wo[winnr].concealcursor = 'niv'
end, {})
```

Run
`nvim --clean -u minimal.lua`

Run
`:Test`

Navigate to new window
Move cursor around, notice its on wrong position. With my own configuration the cursor position even stops completely updating.

### Expected behavior

Cursor should work in identical way as it does in 0.9.5 and also in latest nightly when conceal is not set.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2615+g924a7ef8b

### Vim (not Nvim) behaves the same?

no, but nvim 0.95 release also works

### Operating system/version

Arch Linux x86_64

### Terminal name/version

st

### $TERM environment variable

tmux-256color

### Installation

repo

**Comment by zeertzjq** [comment]
Looks like a `filler_todo` check is needed because Nvim has removed `WL_LINE`:
```diff
diff --git a/src/nvim/drawline.c b/src/nvim/drawline.c
index 90bf6eda5..8d2777c1a 100644
--- a/src/nvim/drawline.c
+++ b/src/nvim/drawline.c
@@ -2443,7 +2443,7 @@ int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, int col_rows, s
     // the cursor column when we reach its position.
     // With 'virtualedit' we may never reach cursor position, but we still
     // need to correct the cursor column, so do that at end of line.
-    if (!did_wcol
+    if (!did_wcol && wlv.filler_todo <= 0
         && wp == curwin && lnum == wp->w_cursor.lnum
         && conceal_cursor_line(wp)
         && (wlv.vcol + wlv.skip_cells >= wp->w_virtcol || mb_schar == NUL)) {
```
Which means such a check may also be needed at some other places where `WL_LINE` was check as well.
