### ISSUE TITLE
use debug.traceback for lua traceback

### ISSUE THREAD

**Issue by jake-stewart** [neovim/neovim#27894]
### Problem

debug.traceback is ignored

### Steps to reproduce

    $ echo "_G.debug.traceback = function() return 'foo' end\nprint(1 + '')" > test.lua && nvim --clean -l test.lua

### Expected behavior

shows "foo" as traceback

### Neovim version (nvim -v)

0.9.5 Release

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macos 13.2.1

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

brew

**Comment by zeertzjq** [comment]
I think this is a limitation of Lua C API. The error handler function of `lua_pcall()` needs to be available before calling `lua_pcall()`, so it's not possible to change it in the middle of a script.
```
lua_pcall                                                          *lua_pcall()*
>c
    lua_pcall (lua_State *L, int nargs, int nresults, int errfunc);
<
        Calls a function in protected mode.

        Both `nargs` and `nresults` have the same meaning as in `lua_call`
        (see |lua_call()|). If there are no errors during the call,
        `lua_pcall` behaves exactly like `lua_call`. However, if there is any
        error, `lua_pcall` catches it, pushes a single value on the stack (the
        error message), and returns an error code. Like `lua_call`,
        `lua_pcall` always removes the function and its arguments from the
        stack.

        If `errfunc` is 0, then the error message returned on the stack is
        exactly the original error message. Otherwise, `errfunc` is the stack
        index of an `error` `handler function`. (In the current
        implementation, this index cannot be a pseudo-index.) In case of
        runtime errors, this function will be called with the error message
        and its return value will be the message returned on the stack by
        `lua_pcall`.

        Typically, the error handler function is used to add more debug
        information to the error message, such as a stack traceback. Such
        information cannot be gathered after the return of `lua_pcall`, since
        by then the stack has unwound.
```

**Comment by zeertzjq** [comment]
This can be achieved by overriding `debug.traceback` from a separate script that is sourced before `-l`, e.g. a script sourced inside a `--cmd` command.

If you are OK with having an extra level in the traceback, you can also invoke the script recursively:
```lua
local function traceback() return 'foo' end
if debug.traceback ~= traceback then
  debug.traceback = traceback
  vim.cmd.luafile(_G.arg[0])
  return
end
print(1 + '')
```

**Comment by jake-stewart** [comment]
> This can be achieved by overriding `debug.traceback` from a separate script that is sourced before `-l`, e.g. a script sourced inside a `--cmd` command.
> 
> If you are OK with having an extra level in the traceback, you can also invoke the script recursively:
> 
> ```lua
> local function traceback() return 'foo' end
> if debug.traceback ~= traceback then
>   debug.traceback = traceback
>   vim.cmd.luafile(_G.arg[0])
>   return
> end
> print(1 + '')
> ```

thanks for all the help
