### ISSUE TITLE
Tree-sitter highlighting no longer takes query range/specificity into account

### ISSUE THREAD

**Issue by amaanq** [neovim/neovim#27895]
### Problem

Before https://github.com/neovim/neovim/pull/27132, queries where a more specific capture appeared earlier than a less specific capture later on used to have a higher precedence, but now that is no longer the case, which is a pretty breaking change really, since I've taken into account specificity of a capture plenty of times when writing queries (especially highlights) for nvim-treesitter. Highlights in certain circumstances will appear off now as a result. I understand this wasn't really documented/obvious, but it was a convenient feature to use.

### Steps to reproduce

config:

```lua
vim.api.nvim_create_autocmd("FileType", {
	pattern = { "c" },
	callback = function(args)
		vim.treesitter.start()
	end,
})

vim.cmd("highlight! @variable.parameter gui=bold guifg=#ff0000 guibg=NONE")
vim.cmd("highlight! @operator gui=bold guifg=#00ff00 guibg=NONE")
```

```sh
nvim --clean -u minimal.lua test.c
```

write `void foo(int *bar)`

Notice that `*` is highlighted the same as `a` because the `@variable.parameter` capture captures the whole `pointer_declarator` node, but the earlier `@operator` capture for `*` ideally would have a higher priority than this

### Expected behavior

I'd expect `*` to be highlighted with `@operator`, not `@variable.parameter`, a possible solution could be to account for the size of the node when applying captures.

It'd also be fine to just not consider specificity anymore, that's totally fine but some queries need to be reworked then (e.g. some of C's highlights) and this should be documented to avoid further confusion

### Neovim version (nvim -v)

v0.10.0-dev-2619+gc52dfb6e8

### Vim (not Nvim) behaves the same?

no (no treesitter)

### Operating system/version

Arch Linux 6.7.9-zen1-1

### Terminal name/version

kitty 0.32.2

### $TERM environment variable

xterm-kitty

### Installation

built from source

**Comment by lewis6991** [comment]
I don't think this is intended. We can add the repro steps as a testcase to prevent this happening again, but I'm surprised our current tests don't capture this in some way.

**Comment by clason** [comment]
- "Mom, can we get more treesitter tests?"
- "We have treesitter tests at home".

[treesitter tests at home](https://github.com/nvim-treesitter/nvim-treesitter)

**Comment by lewis6991** [comment]
> - "Mom, can we get more treesitter tests?"
> - "We have treesitter tests at home".
> 
> [treesitter tests at home](https://github.com/nvim-treesitter/nvim-treesitter)

In that case, would it be worth adding nvim-treesitters CI to Neovim's CI? It would certainly boost coverage.

**Comment by gpanders** [comment]
How did this even work before with `iter_captures`? Does `ts_query_cursor_next_capture` order iterated nodes based on "specificity"? As far as I can tell, we are not doing anything on the Neovim side to do this ordering. The old highlighter that use `iter_captures` just applied extmarks in the exact order returned from the iterator.

**Comment by gpanders** [comment]
>It'd also be fine to just not consider specificity anymore, that's totally fine but some queries need to be reworked then (e.g. some of C's highlights) and this should be documented to avoid further confusion

I do think we should do this too and make the order defined in the query the only thing that influences priority. Having two separate metrics that influence priority is confusing. But in the interest of supporting BWC we should still fix this in the meantime.

**Comment by clason** [comment]
> In that case, would it be worth adding nvim-treesitters CI to Neovim's CI? It would certainly boost coverage.

Actually, I'd claim we should do the converse: add a treesitter highlight test suite (mirroring `tree-sitter test`, but using our highlighter instead of the Rust crate -- either tree-sitter's or theHamsta's) exercising the bundled queries and expose it in a way that nvim-treesitter can ~~steal~~ leverage.

**Comment by lucario387** [comment]
> How did this even work before with iter_captures

iter_captures return the results based on the order of a node in the tree, so the outer appears before the inner and so on

**Comment by lewis6991** [comment]
The repro is the OP acutally caused the highlighter to error when I added it as a testcase. Haven't got time to debug, but using iter_captures as before works fine.
