### ISSUE TITLE
Stale help link provided by `:checkhealth` output for tmux

### ISSUE THREAD

**Issue by WillLillis** [neovim/neovim#27907]
### Problem

When I run `:checkhealth`, I receive the following:

```
tmux ~
- OK escape-time: 50
- OK focus-events: on
- $TERM: xterm-256color
- ERROR $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
  - ADVICE:
    - Set default-terminal in ~/.tmux.conf:
      set-option -g default-terminal "screen-256color"
    - https://github.com/neovim/neovim/blob/docs/install/BUILD.md#building
```

Trying to visit the provided [link]( https://github.com/neovim/neovim/blob/docs/install/BUILD.md#building) results in a 404.

### Steps to reproduce

Run `:checkhealth` while running neovim within tmux, without $TERM set to "screen-256-color" or "tmux-256color". Attempt to visit the provided help link.

### Expected behavior

A valid help link.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2000+g6fa0f303d

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 22.04.3 LTS

### Terminal name/version

Windows Command Prompt

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
Fixed by #27364
