### ISSUE TITLE
The newly released nightly package for macOS(x86-64) automatically exits just a few seconds after opening.

### ISSUE THREAD

**Issue by yangkangnevergiveup** [neovim/neovim#27906]
### Problem

The newly released nightly package for macOS(x86-64) automatically exits just a few seconds after opening. The terminal I use is kitty.
[macOS package](https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz)
![image](https://github.com/neovim/neovim/assets/44560513/db1f6da1-5028-44a9-8058-0d400f577ba6)

### Steps to reproduce

0. Download and use nightly package.
1. `vim .`
2. Just wait a few seconds.

### Expected behavior

Open my project normally as before without exiting.

### Neovim version (nvim -v)

nightly build ( c52dfb6 )

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 14.2.1

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

download from nightly build package.

**Comment by zeertzjq** [comment]
Can you provide a backtrace? https://neovim.io/doc/user/dev_tools.html#dev-tools-backtrace

**Comment by yangkangnevergiveup** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               nvim [16228]
Path:                  /Users/USER/*/nvim
Identifier:            nvim
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        nvim [16227]
Responsible:           kitty [12181]
User ID:               501

Date/Time:             2024-03-18 11:44:45.6648 +0800
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Bridge OS Version:     8.2 (21P2057)
Anonymous UUID:        53C2066F-BB78-0D7B-2325-7D52BC509D36

Sleep/Wake UUID:       64B6B664-0C97-4FAD-BF36-DB78A5CD1D55

Time Awake Since Boot: 600000 seconds
Time Since Wake:       6479 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000250
Exception Codes:       0x0000000000000001, 0x0000000000000250

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [16228]

VM Region Info: 0x250 is not in any region.  Bytes before following region: 140737487273392
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      shared memory            7fffffef8000-7fffffef9000 [    4K] r-x/r-x SM=SHM  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   nvim                          	       0x1096eb494 changed_window_setting + 4
1   nvim                          	       0x10942a049 lj_vm_ffi_call + 132


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007ff7b6b2f610  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x00007ff7b6b2f570  rsp: 0x00007ff7b6b2f570
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x000000010a50d128  r11: 0xfffffffffffffff5
  r12: 0x000000010997cd28  r13: 0x0000000000000000  r14: 0x0000000109afe380  r15: 0x000000000000008a
  rip: 0x00000001096eb494  rfl: 0x0000000000010246  cr2: 0x0000000000000250
  
Logical CPU:     0
Error Code:      0x00000006 (no mapping for user data write)
Trap Number:     14

Thread 0 instruction stream:
  15 00 00 80 8b 00 02 00-00 04 48 83 c4 08 5b 5d  ..........H...[]
  c3 66 66 2e 0f 1f 84 00-00 00 00 00 55 48 89 e5  .ff.........UH..
  53 50 48 8d 1d 53 30 29-00 48 8b 3b 83 bf 98 00  SPH..S0).H.;....
  00 00 00 74 1e e8 d2 fe-ff ff 48 8b 03 8b 88 38  ...t......H....8
  02 00 00 89 88 94 00 00-00 c7 80 98 00 00 00 00  ................
  00 00 00 48 83 c4 08 5b-5d c3 66 90 55 48 89 e5  ...H...[].f.UH..
 [c7]87 50 02 00 00 00 00-00 00 c6 87 00 02 00 00  ..P.............	<==
  00 48 8d 05 78 19 29 00-0f b6 00 24 01 48 85 ff  .H..x.)....$.H..
  75 04 84 c0 74 3c 48 8d-0d 9f 17 29 00 0a 01 75  u...t<H....)...u
  2f 83 bf 8c 02 00 00 27-7f 26 c7 87 8c 02 00 00  /......'.&......
  28 00 00 00 c7 87 50 02-00 00 00 00 00 00 48 8d  (.....P.......H.
  05 e3 17 29 00 83 38 27-7f 06 c7 00 28 00 00 00  ...)..8'....(...

Binary Images:
       0x10a929000 -        0x10a934fff lua.so (*) <cb922b11-3582-32be-91e7-a65ff93d5198> /Users/USER/*/lua.so
       0x10a0a4000 -        0x10a0bbfff luasnip-jsregexp.so (*) <bdf0cf72-947a-3071-92b9-4f9fbda7560e> /Users/USER/*/luasnip-jsregexp.so
       0x1093cf000 -        0x109946fff nvim (*) <191abac2-9b67-3b30-8e17-0a563c019c00> /Users/USER/*/nvim
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 47924
    thread_create: 0
    thread_set_state: 44911

VM Region Summary:
ReadOnly portion of Libraries: Total=312.4M resident=0K(0%) swapped_out_or_unallocated=312.4M(100%)
Writable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                    8K        1 
MALLOC                             1.3G       32 
MALLOC guard page                   24K        6 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                       18.4M      149 
__DATA                            3310K      142 
__DATA_CONST                      6338K      105 
__DATA_DIRTY                       343K       57 
__LINKEDIT                       182.5M        5 
__OBJC_RO                         71.1M        1 
__OBJC_RW                         2169K        2 
__TEXT                           129.8M      157 
dyld private memory                260K        2 
shared memory                       24K        3 
===========                     =======  ======= 
TOTAL                              1.8G      665 



-----------
Full Report
-----------

{"app_name":"nvim","timestamp":"2024-03-18 11:44:45.00 +0800","app_version":"","slice_uuid":"191abac2-9b67-3b30-8e17-0a563c019c00","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 14.2.1 (23C71)","roots_installed":0,"incident_id":"22309445-477E-415E-9EC2-193C8F9D2DB6","name":"nvim"}
{
  "uptime" : 600000,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Macmini8,1",
  "coalitionID" : 95813,
  "osVersion" : {
    "train" : "macOS 14.2.1",
    "build" : "23C71",
    "releaseType" : "User"
  },
  "captureTime" : "2024-03-18 11:44:45.6648 +0800",
  "codeSigningMonitor" : 0,
  "incident" : "22309445-477E-415E-9EC2-193C8F9D2DB6",
  "pid" : 16228,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-03-18 11:44:36.9205 +0800",
  "procStartAbsTime" : 604331295235226,
  "procExitAbsTime" : 604340039271786,
  "procName" : "nvim",
  "procPath" : "\/Users\/USER\/*\/nvim",
  "parentProc" : "nvim",
  "parentPid" : 16227,
  "coalitionName" : "net.kovidgoyal.kitty",
  "crashReporterKey" : "53C2066F-BB78-0D7B-2325-7D52BC509D36",
  "responsiblePid" : 12181,
  "responsibleProc" : "kitty",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 4294967295,
  "wakeTime" : 6479,
  "bridgeVersion" : {"build":"21P2057","train":"8.2"},
  "sleepWakeUUID" : "64B6B664-0C97-4FAD-BF36-DB78A5CD1D55",
  "sip" : "enabled",
  "vmRegionInfo" : "0x250 is not in any region.  Bytes before following region: 140737487273392\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      shared memory            7fffffef8000-7fffffef9000 [    4K] r-x\/r-x SM=SHM  ",
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000250","rawCodes":[1,592],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000250"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":16228},
  "vmregioninfo" : "0x250 is not in any region.  Bytes before following region: 140737487273392\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      shared memory            7fffffef8000-7fffffef9000 [    4K] r-x\/r-x SM=SHM  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":44911,"task_for_pid":47924},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":23923103,"instructionState":{"instructionStream":{"bytes":[21,0,0,128,139,0,2,0,0,4,72,131,196,8,91,93,195,102,102,46,15,31,132,0,0,0,0,0,85,72,137,229,83,80,72,141,29,83,48,41,0,72,139,59,131,191,152,0,0,0,0,116,30,232,210,254,255,255,72,139,3,139,136,56,2,0,0,137,136,148,0,0,0,199,128,152,0,0,0,0,0,0,0,72,131,196,8,91,93,195,102,144,85,72,137,229,199,135,80,2,0,0,0,0,0,0,198,135,0,2,0,0,0,72,141,5,120,25,41,0,15,182,0,36,1,72,133,255,117,4,132,192,116,60,72,141,13,159,23,41,0,10,1,117,47,131,191,140,2,0,0,39,127,38,199,135,140,2,0,0,40,0,0,0,199,135,80,2,0,0,0,0,0,0,72,141,5,227,23,41,0,131,56,39,127,6,199,0,40,0,0,0],"offset":96}},"threadState":{"r13":{"value":0},"rax":{"value":0},"rflags":{"value":66118},"cpu":{"value":0},"r14":{"value":4457489280},"rsi":{"value":0},"r8":{"value":0},"cr2":{"value":592},"rdx":{"value":0},"r10":{"value":4468035880},"r9":{"value":0},"r15":{"value":138},"rbx":{"value":140701898831376},"trap":{"value":14,"description":"(no mapping for user data write)"},"err":{"value":6},"r11":{"value":18446744073709551605},"rip":{"value":4453217428,"matchesCrashFrame":1},"rbp":{"value":140701898831216},"rsp":{"value":140701898831216},"r12":{"value":4455910696,"symbolLocation":0,"symbol":"got_int"},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":3261588,"symbol":"changed_window_setting","symbolLocation":4,"imageIndex":2},{"imageOffset":372809,"symbol":"lj_vm_ffi_call","symbolLocation":132,"imageIndex":2}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4472344576,
    "size" : 49152,
    "uuid" : "cb922b11-3582-32be-91e7-a65ff93d5198",
    "path" : "\/Users\/USER\/*\/lua.so",
    "name" : "lua.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4463411200,
    "size" : 98304,
    "uuid" : "bdf0cf72-947a-3071-92b9-4f9fbda7560e",
    "path" : "\/Users\/USER\/*\/luasnip-jsregexp.so",
    "name" : "luasnip-jsregexp.so"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4449955840,
    "size" : 5734400,
    "uuid" : "191abac2-9b67-3b30-8e17-0a563c019c00",
    "path" : "\/Users\/USER\/*\/nvim",
    "name" : "nvim"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 140703176163328,
  "size" : 25769803776,
  "uuid" : "2a323ece-7dbf-33e2-9ef3-3390c59ddc35"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=312.4M resident=0K(0%) swapped_out_or_unallocated=312.4M(100%)\nWritable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                             1.3G       32 \nMALLOC guard page                   24K        6 \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                       18.4M      149 \n__DATA                            3310K      142 \n__DATA_CONST                      6338K      105 \n__DATA_DIRTY                       343K       57 \n__LINKEDIT                       182.5M        5 \n__OBJC_RO                         71.1M        1 \n__OBJC_RW                         2169K        2 \n__TEXT                           129.8M      157 \ndyld private memory                260K        2 \nshared memory                       24K        3 \n===========                     =======  ======= \nTOTAL                              1.8G      665 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "237ecb537a46573c75cc5928a4a282f40f3ed91a",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "632e3f9c01482c74ed76392d",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "65e7b4feafcca6238e661b42"
      },
      "deploymentId" : 240000424
    },
    {
      "rolloutId" : "632e3df958740028737bffc0",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_NL_OVERRIDES" : "65e878bc12edf62098adc9e8"
      },
      "deploymentId" : 240000652
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "a3f9ec09-b145-49f3-8142-da4a1f338456",
      "experimentId" : "65f21aa774b6f500a45abd7d",
      "deploymentId" : 400000001
    }
  ]
}
}

**Comment by zeertzjq** [comment]
It's likely that your [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo) version is outdated.

**Comment by yangkangnevergiveup** [comment]
Thank you very much, it's working now!
