### ISSUE TITLE
cant build on debian 12

### ISSUE THREAD

**Issue by InvisibleRasta** [neovim/neovim#27900]
### Problem

I am getting the following error:
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Gettext (missing: GETTEXT_MSGMERGE_EXECUTABLE
  GETTEXT_MSGFMT_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.25/Modules/FindGettext.cmake:81 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/nvim/po/CMakeLists.txt:1 (find_package)

### Steps to reproduce

build

### Expected behavior

build without errors

### Neovim version (nvim -v)

latest

### Vim (not Nvim) behaves the same?

 idk

### Operating system/version

debian 12

### Terminal name/version

gnome terminal

### $TERM environment variable

not sure

### Installation

debian

**Comment by clason** [comment]
Please give full and reproducible steps. If you're "not sure", we can't know either.

**Comment by dundargoc** [comment]
You need to install `gettext`.

**Comment by carsonalh** [comment]
Just ran into this issue myself installing from source.

Shouldn't required system libraries be listed in the `BUILD.md`?

`sudo apt install gettext` fixes this on Debian 12.

**Comment by clason** [comment]
It already is: https://github.com/neovim/neovim/blob/master/BUILD.md#ubuntu--debian
