### ISSUE TITLE
E5133: Neovim won't recognise keymap.

### ISSUE THREAD

**Issue by SomeGuyWithGithub** [neovim/neovim#27904]
### Problem

OS: Linux Mint Cinnamon 21.3

I am copying the basic neovim kickstart init.lua file, [this one](https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua), and got this error when i ran the command ```nvim```
```
E5113: Error while calling lua chunk: /home/user/.config/nvim/init.lua:162: attempt to index field 'keymap' (a nil value)
stack traceback:
        /home/user/.config/nvim/init.lua:162: in main chunk
```
I also tried using the command given by the readme from kickstart, 
```
git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
```
only to get the same error message.

When I commented out line 162, ```vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>)```, it only moved the error message down to the next use of vim.keymap, line 165, ```vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, { desc = 'Go to previous [D]iagnostic message' })```

I have no idea if it was something that I did wrong, if I didn't download something crucial, or if it is the fault of neovim. I am not an expert in lua or neovim, so I could not go any further. Any help is much appreciated.

### Steps to reproduce

On Linux Mint Cinnamon 21.3,
Clean install of nvim
```sudo apt install neovim```
```cd ~/.config/```
```mkdir nvim```

Either copy and paste [this file](https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua) to a new file in ~/.config/nvim called init.lua
OR
Enter command ```git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim```

Open nvim: ```nvim```

### Expected behavior

Upon going into nvim, the error message
```
E5113: Error while calling lua chunk: /home/user/.config/nvim/init.lua:162: attempt to index field 'keymap' (a nil value)
stack traceback:
        /home/user/.config/nvim/init.lua:162: in main chunk
```
will appear

### Neovim version (nvim -v)

v0.6.1

### Vim (not Nvim) behaves the same?

no idea

### Operating system/version

Linux Mint Cinnamon 21.3

### Terminal name/version

no idea

### $TERM environment variable

no idea

### Installation

system package manager, apt

**Comment by zeertzjq** [comment]
Your Nvim version is too old.
