### ISSUE TITLE
:call jobstart("nvim -e ...") doesn't trigger nvim -e

### ISSUE THREAD

**Issue by ds26gte** [neovim/neovim#2790]
jobstart fails silently on "nvim -e ...". Other commands work fine. E.g., from the nvim command line:

call jobstart("echo cat > ~/job.touch")

works fine.

call jobstart("nvim -e -s ~/job.touch -c '%s/cat/dog/g' -cx")

does not work!

However, from the Unix command line

nvim -e -s ~/job.touch -c '%s/cat/dog/g' -cx

works.

**Comment by justinmk** [comment]
If you have `job.touch` open in Nvim while doing this, it's likely complaining about the swapfile. Try `:noswapfile`. This works for me:

    :jobstart("nvim -e -s -c 'noswapfile e job.touch' -c '%s/x/A/g' -cx")
