### ISSUE TITLE
LSP intermittent failure to attach due to unstable arguments passed to cmd on Windows.

### ISSUE THREAD

**Issue by Zorkimer** [neovim/neovim#27915]
### Problem

LSP intermittent failure to attach due to unstable arguments passed to cmd on Windows.

I haven't looked at rpc.lua because I probably wouldn't understand it but I think there is a strange bug on Windows whereby the argument passed to some function in rpc.lua is not stable.

It seems to alternate between a path command or the mason CMD containing the literal path to the package binary.

I understand this could be a Mason bug also but I don't know enough about the internals to guess which.

I have been testing with ZLS but this behaviour occurs with all LSPs I have tried to install with Mason.

ZLS

Fail

`[INFO][2024-03-18 15:46:43] .../vim/lsp/rpc.lua:662	"Starting RPC client"	{  args = {},  cmd = "zls",  extra = {    cwd = "C:/Work/Projects/Zig/exercises"  }}`

Success

`[INFO][2024-03-18 13:53:15] .../vim/lsp/rpc.lua:662	"Starting RPC client"	{  args = {},  cmd = "C:\\Users\\Z\\AppData\\Local\\nvim-data\\mason\\bin\\zls.CMD",  extra = {    cwd = "C:/Work/Projects/Zig/exercises"  }}`

Passed "cmd = {"zls"}" to the lspconfig table and added the mason binary to path.

`[INFO][2024-03-18 16:18:23] .../vim/lsp/rpc.lua:662	"Starting RPC client"	{  args = {},  cmd = "C:\\Users\\Z\\AppData\\Local\\nvim-data\\mason\\packages\\zls\\bin\\zls.EXE",  extra = {    cwd = "C:/Work/Projects/Zig/exercises"  }}`

Installed zls via scoop, removed cmd entry from lspconfig table.

`[INFO][2024-03-18 16:26:20] .../vim/lsp/rpc.lua:662	"Starting RPC client"	{  args = {},  cmd = "C:\\Users\\Z\\scoop\\shims\\zls.EXE",  extra = {    cwd = "C:/Work/Projects/Zig/exercises"  }}`

### Steps to reproduce

I guess you'd need to find someone with a Windows machine, get them to install any LSP with mason.nvim, configure with lspconfig and mason-lspconfig.nvim and open files a bunch of times to see the behaviour.

### Expected behavior

It should be passing the correct argument, rather than dithering between the two based on the procession of Venus in the firmament.

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

I have no idea, sorry

### Operating system/version

Microsoft Windows NT 10.0.19045.0

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

I'm on Windows I don't know what this is, bro

### Installation

Executable installer from the interweb sitepage github dot com

**Comment by justinmk** [comment]
another "mason CMD" issue: https://github.com/neovim/neovim/issues/27937

**Comment by mfussenegger** [comment]
This is either a mason/mason-lspconfig or lspconfig issue. neovim core only provides the `lsp.start` and `lsp.start_client` methods, and there the `cmd` parameter needs to be provided. Whoever is setting that, would cause this problem. I'm not familiar with mason-lspconfig so I'm not sure if it is coming from there, or from lspconfig.
