### ISSUE TITLE
Neovim dies when navigating to a specific line on a file

### ISSUE THREAD

**Issue by samuliraty** [neovim/neovim#27916]
### Problem

When navigating to a specific line in a typescript file, Neovim terminates, with the terminal displaying the remnants of Neovim's interface above the active input line. Is this standard crashing behavior for Neovim? Neovim can be rerun normally and nothing shows up if I run :message. How do I debug this?

### Steps to reproduce

Need more information

### Expected behavior

No crash

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2157+g51f783f2f-Homebrew

### Vim (not Nvim) behaves the same?

unsure

### Operating system/version

macOS 14.2.1

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by gpanders** [comment]
>### Steps to reproduce
>
>Need more information

If you can figure out a minimal way to reproduce the issue, someone can take a look at it, but without that there's not much that anybody else can do.

If you're able to reproduce the crash reliably on your own code, you can try building Neovim yourself in debug mode and providing a stack trace.

**Comment by zeertzjq** [comment]
If you are using nvim-ufo, try updating its version.

**Comment by samuliraty** [comment]
I have been unable to reproduce this with the latest version built from source, so I am closing this and will open a new issue should the problem reappear. Thanks for the replies.
