### ISSUE TITLE
Language Servers won't load due to parenthesis in path to batch files being called by rpc (windows)

### ISSUE THREAD

**Issue by terr-steak** [neovim/neovim#27937]
### Problem

I am on windows and set up neovim using lazyvim. I have enabled a few different LSP's and they all seem to throw a similar error. In the UI I get the following notification 
`Warn  3:34:57 PM notify.warn Client 1 quit with exit code 1 and signal 0`
when I look in the lsp.log file I see errors like the following for multiple LSP's:
```
[ERROR][2024-03-19 15:17:48] .../vim/lsp/rpc.lua:734	"rpc"	"C:/Users/FIRSTNAME(STRING)LASTNAME/AppData/Local/nvim-data/mason/bin/lua-language-server.CMD"	"stderr"	"'C:/Users/FIRSTNAME' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
```
Where it appears to truncate the path the exe(?guessing) in the referenced batch script when attempting to run it to before the parenthesis in the path. 

Contents of the batch file mentioned in the error:
``` batch
@ECHO off
GOTO start
:find_dp0
SET dp0=%~dp0
EXIT /b
:start
SETLOCAL
CALL :find_dp0

endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "C:\Users\FIRSTNAME(STRING)LASTNAME\AppData\Local\nvim-data\mason\packages\lua-language-server\bin/lua-language-server.exe" %*
```

I attempted to modify the cmd scripts myself to:
* Leverage a variable in the execution of the exe, replacing part of the fully qualified path with system variables that were listed when running `set` in a CMD terminal (ie. `%HOMEDRIVE%%HOMEPATH%`) in the batch script shared above.
* `cd` to the path first then execute the exe 
* escape the `(` using `^` 
* escape `"` using `^`
* Change all slashes to be the same (ie. `\`) 

However it did not appear that editing these batch files mentioned in the lsp.log errors actually did anything. Even if I restarted the LSP server or my computer. They appeared as if I had made no change to them at all, still giving the same exact error. 

Additionally I tried setting `shellslash` to true in the options.lua along with the settings listed in the [help for shell](https://neovim.io/doc/user/options.html#'shell') to specify using powershell to see if that helped, no effect.

### Steps to reproduce using "nvim -u minimal_init.lua"

I can reproduce the issue by adding a config that defines the lua-language-server as an LSP to use, then trying to edit a lua file (in my case this is generally one of the lazy lua config files. 

### Expected behavior

LSP's load and start working as expected leveraging the cmd scripts and the exe files they are attempting to run. 

### Neovim version (nvim -v)

0.9.5

### Language server name/version

multiple 

### Operating system/version

Edition	Windows 10 Enterprise Version	22H2 Installed on	‎8/‎9/‎2022 OS build	19045.4046 Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by clason** [comment]
I'm sorry, but is this seriously your home directory? Why??!

**Comment by zeertzjq** [comment]
IIRC Windows doesn't allow parentheses in file/directory names.

**Comment by terr-steak** [comment]
> I'm sorry, but is this seriously your home directory? Why??!

Really?! This is a Neovim team members response to a bug ticket? Rude, unprofessional, and unnecessary comments? Really? 

The fact that this is on a company managed computer, of which I have no control over install locations on is one thing... the fact that you think it's ok to use a bug ticket opened trying to help imporove your team's software to try and shame someone for where they choose to install software is a completely separate issue. 

Could you please explain why this shouldn't be in my home directory? I am not as familiar with Windows so please forgive me if I don't fully understand. It's in the AppData directory which seems appropriate to me given this description from the Microsoft Learn Site "Create other miscellaneous files that the user doesn't directly access in the Application Data folder..." and additionally this is from your own (neovim team's) codebase:

 ...from runtime/doc/nvim.txt
>     Because Nvim follows the XDG \|base-directories\| standard, configuration on
>     Windows is stored in ~/AppData instead of ~/.config. But you can still share
>     the same Nvim configuration on all of your machines, by creating
>     ~/AppData/Local/nvim/init.vim containing just this line: >vim
>     source ~/.config/nvim/init.vim


...from runtime/doc/starting.txt 
>             Unix:          "$XDG_STATE_HOME/nvim/shada/main.shada"
>             Windows:  "$XDG_STATE_HOME/nvim-data/shada/main.shada"
>     See also \|base-directories\|.
>         Unix:              ~/.local/share                   ~/.local/share/nvim
>         Windows:      ~/AppData/Local             ~/AppData/Local/nvim-data```

Finally the fact that this is in my home directory does not appear to have any bearing on the crux of the issue (problems handling parenthesis in the batch file calling the lsp's exe on windows)...

**Comment by zeertzjq** [comment]
This should be reported to https://github.com/williamboman/mason.nvim

**Comment by pverghese** [comment]
The issue is still a problem because react native and some other JavaScript frameworks use parentheses for directory names to suggest groups, which fail on windows

**Comment by justinmk** [comment]
@pverghese if Nvim has a problem with those paths then of course we want to fix it. But this doesn't seem to be a Nvim issue.
