### ISSUE TITLE
:shell - E4292: Not an editor command: shell - Ubuntu PPA - Compiled Jun 4, 2015

### ISSUE THREAD

**Issue by JoelMon** [neovim/neovim#2794]
I don't know if this command just has not been implemented yet or if there's a problem.

In any case, `:shell` is not recognized. I tried checking `:help nvim-features-removed` but that raises a `E149: Sorry, no help for nvim-features-removed` error. I've reported the missing help file already, it's issue #2795

> NVIM 0.0.0-alpha (compiled Jun  4 2015 16:21:35)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/build/config -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/src -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/build/include
Compiled by buildd@lcy01-11

>Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

>system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by fmoralesc** [comment]
This was replaced by `:terminal`, which is more powerful. Remember that leaving "insert" mode (actually, terminal mode) is done with the combo `<C-\><C-n>`, although I suggest you add
~~~
tnoremap <Esc><Esc> <C-\><C-n>
~~~
(adjust it to your preferences).

**Comment by fwalch** [comment]
[`:shell`](http://neovim.io/doc/user/various.html#:shell) has been intentionally removed from Neovim. Maybe `:terminal` does what you want.

**Comment by JoelMon** [comment]
Thanks for the help.
