### ISSUE TITLE
delete multiple empty lines, based on a criteria

### ISSUE THREAD

**Issue by bojanmilevski** [neovim/neovim#27948]
### Problem

Hello.

When mentioning whitespace in my text, I am referring to either the space character (` `), a tab (`\t`) or an empty line (`\n`).

This idea is inspired by the JetBrains editors. Whenever you press backspace, one of many actions can happen to whitespaces:

1. If the cursor is on a whitespace character, despite what's behind the cursor, and the previous line is whitespace, the previous one is simply deleted.

2. If the cursor is on a whitespace character, despite what's behind the cursor, and the previous line is not whitespace, the cursor get's placed at the end of the previous line. Whitespaces inbetween get deleted.

These two examples set good grounds for my proposition - implementing an option that enables similar, or even "better" behavior.

First off, I thought that this would be a great idea for a plugin, until the moment I thought about proposing it to the core team, which I think would agree this is a great addition to nvim, or at least as a toggle option. 

To explain my approach, I have written a simple Lua script that demonstrates how this could be implemented. Due to my very limited experience with neovim plugins and the API commands, I have commented out some of the intended behavior:

```lua
-- get current buffer as string
-- local buff_no = vim.api.nvim_get_current_buf()
-- local content = vim.api.nvim_buf_get_lines(buff_no, 0, -1, false)

-- get current cursor position
-- local win = vim.api.nvim_get_current_win()
-- local position = vim.api.nvim_win_get_cursor(win)

local function is_whiteline(line)
	if line == '' then
		return true
	end

	for i = 1, #line do
		local char = line:sub(i, i)
		if char ~= ' ' and char ~= '\t' then
			return false
		end
	end

	return true
end

local function remove_prefix_whitelines(line)
	local start_index = 1

	for i = 1, #line do
		local char = line:sub(i, i)
		if char ~= ' ' and char ~= '\t' then
			start_index = i
			break
		end
	end

	return line:sub(start_index)
end

local whole_buffer = true
local position = {}

local content = {
	'#include <stdio.h>',
	'#include <stdlib.h>',
	'',
	'int main(int argc, char* argv[]) {',
	'\tint x = 1;',
	'',
	'\treturn EXIT_SUCCESS;',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'\t\t  \t    \t',
	'',
	'',
	'',
	'',
	'',
	'',
	'\t\t}',
}

if whole_buffer then
	position = {
		row = #content,
		col = #content[#content],
	}
else
	position = {
		row = 13, -- random
		col = 1,  -- random
	}
end

local new_buffer = {}

for row_no = position['row'], 2, -1 do
	local curr_line = content[row_no]
	local prev_line = content[row_no - 1]

	if not is_whiteline(curr_line) and not is_whiteline(prev_line) then
		curr_line = remove_prefix_whitelines(curr_line)
		local new_line = prev_line .. curr_line
		table.insert(new_buffer, new_line)
		break
	end

	if not is_whiteline(curr_line) then
		table.insert(new_buffer, curr_line)
	end

	if not is_whiteline(prev_line) then
		if #new_buffer == 0 then
			table.insert(new_buffer, prev_line)
		else
			table.insert(new_buffer, #new_buffer, prev_line)
		end
		break
	end
end

-- TODO: variables that keep track of start and end lines affected 

-- print new buffer content, debug purposes
for i = 1, #new_buffer do
	print(new_buffer[i])
end

-- replace buffer content from start_no to end_no
-- vim.api.nvim_buf_set_lines(...)
```

Expected behavior is explained below. Most of the points have been implemented in the lua code above.

__DISCLAIMER__: This is my first time proposing an idea in such a serious project. I have zero experience with the neovim code base, and very little experience writing neovim plugins. Help will be needed if this idea gains attention.

### Expected behavior

# EXPLANATION

- `|` indicates the current position of the cursor
- `.` indicates an empty line

# 1. Current line has a character, no prefix, empty lines before it

```c
#include <stdio.h>
#include <stdlib.h>
.
int main(int argc, char *argv[]) {
    int x = 1;
.
    return EXIT_SUCCESS;
.
.
.
.
.
.
.
.
|}
.
int function() {
    printf("\n");
}
```

after pressing backspace in insert mode or X in normal mode

```c
#include <stdio.h>
#include <stdlib.h>
.
int main(int argc, char *argv[]) {
    int x = 1;
.
    return EXIT_SUCCESS;
|}
.
int function() {
    printf("\n");
}
```

# 2. Current line has a character, no prefix, non-empty line before it

```c
#include <stdio.h>
#include <stdlib.h>
.
int main(int argc, char *argv[]) {
    int x = 1;
.
    return EXIT_SUCCESS;
|}

```

after pressing backspace in insert mode or X in normal mode

```c
#include <stdio.h>
#include <stdlib.h>
.
int main(int argc, char *argv[]) {
    int x = 1;
.
    return EXIT_SUCCESS;|}
.
int function() {
    printf("\n");
}
```

# 3. Current line has a character, whitespace prefix, empty lines before it

```c
#include <stdio.h>
#include <stdlib.h>
.
int main(int argc, char *argv[]) {
    int x = 1;
.
    return EXIT_SUCCESS;
.
.
.
.
.
.
      |} // this line has a tab and 2 spaces in front of the brace
.
int function() {
    printf("\n");
}
```

after pressing backspace in insert mode or X in normal mode

```c
#include <stdio.h>
#include <stdlib.h>
.
int main(int argc, char *argv[]) {
    int x = 1;
.
    return EXIT_SUCCESS;
      |}  // this line still has a tab and 2 spaces in front of the brace
.
int function() {
    printf("\n");
}
```

# 4. Current line has a character, whitespace prefix, non-empty line before it

```c
#include <stdio.h>
#include <stdlib.h>
.
int main(int argc, char *argv[]) {
    int x = 1;
.
    return EXIT_SUCCESS;
      |} // this line has a tab and two spaces in front of the brace
.
int function() {
    printf("\n");
}
```

after pressing backspace in insert mode or X in normal mode

```c
#include <stdio.h>
#include <stdlib.h>
.
int main(int argc, char *argv[]) {
    int x = 1;
.
    return EXIT_SUCCESS;
|}
.
int function() {
    printf("\n");
}
```

# 5. Current line does not have a character, prefix does not matter, empty lines before do not matter

```c
#include <stdio.h>
#include <stdlib.h>
.
int main(int argc, char *argv[]) {
    int x = 1;
.
      // this line has a tab and 2 spaces
.
.
      | // this line has a tab and 2 spaces before the cursor
.
     // this line has a tab
.
.
    return EXIT_SUCCESS;
}
.
int function() {
    printf("\n");
}
```

after pressing backspace in insert mode or X in normal mode

```c
#include <stdio.h>
#include <stdlib.h>
.
int main(int argc, char *argv[]) {
    int x = 1;|
    return EXIT_SUCCESS;
}
.
int function() {
    printf("\n");
}
```

**Comment by justinmk** [comment]
Thanks for the thoughtful proposal. But this should be a plugin.
