### ISSUE TITLE
vim.uv coming up nil

### ISSUE THREAD

**Issue by FedeAbella** [neovim/neovim#27957]
### Problem

Calling the Luv api `vim.uv` returns a nil value on latest stable 0.9.5:

```
E5108: Error executing lua [string ":lua"]:1: attempt to index field 'uv' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

### Steps to reproduce

- Extract latest stable 0.9.5 from tarball
`nvim --clean`
`:lua vim.uv.version()`

### Expected behavior

`vim.uv` is exposed and api methods can be called

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1692716794     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 23.10

### Terminal name/version

alacritty 0.12.2

### $TERM environment variable

xterm-256color

### Installation

tarball from repo

**Comment by seandewar** [comment]
0.10 is needed for `vim.uv`. For 0.9 and older, use `vim.loop`.
