### ISSUE TITLE
vim.lsp.buf.hover() .  'width' key must be a positive Integer

### ISSUE THREAD

**Issue by Piraty** [neovim/neovim#27956]
### Problem

many release versions are affected, including latest stable v0.9.5 .
a mitigation is present on master, see below

`vim.lsp.buf.hover()` may trigger
```
Error executing vim.schedule lua callback: $HOME/.local/share/nvim/runtime/lua/vim/lsp/util.lua:1721: 'width' key must be a positive Integer        
stack traceback:
        [C]: in function 'nvim_open_win'
        $HOME/.local/share/nvim/runtime/lua/vim/lsp/util.lua:1721: in function 'handler'
        $HOME/.local/share/nvim/runtime/lua/vim/lsp.lua:1502: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

related:
* https://github.com/neovim/neovim/discussions/27434
* https://github.com/neovim/nvim-lspconfig/issues/3036

### Steps to reproduce using "nvim -u minimal_init.lua"

`minimal.lua`

```
-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs {
  -- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
  -- some_plugin = 'https://github.com/author/plugin.nvim'
  lspconfig = 'https://github.com/neovim/nvim-lspconfig.git'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE
local lspconfig = require("lspconfig")
lspconfig.pylsp.setup{}

-- condensed from: https://github.com/neovim/nvim-lspconfig#suggested-configuration
vim.api.nvim_create_autocmd('LspAttach', {
  group = vim.api.nvim_create_augroup('UserLspConfig', {}),
  callback = function(ev)
    local opts = { buffer = ev.buf }
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
  end
})
```

`repro.py`

```
from datetime import date

# REPRO
# * go to last line
# * try `vim.lsp.buf.hover()` on parts of right side. works
# * try it on `d`, fails

d = date.fromtimestamp(0)
```

### Expected behavior

empty box is shown or no box at all

the issue is not present on current master, it's fixed (by accident) by cfd4a9dfaf.
with that commit, an empty box is shown.

### Neovim version (nvim -v)

v0.10.0.-dev-763+gc01e624b07

### Language server name/version

python-language-server 1.10.1 / python3.12

### Operating system/version

linux/rolling

**Comment by justinmk** [comment]
> the issue is not present on current master, it's fixed (by accident) by [cfd4a9d](https://github.com/neovim/neovim/commit/cfd4a9dfaf5fd900264a946ca33c4a4f26f66a49).

Is there some other change you can suggest?
