### ISSUE TITLE
:help nvim-features-removed error, help file not found. - Ubuntu PPA - Compiled June 4, 2015

### ISSUE THREAD

**Issue by JoelMon** [neovim/neovim#2795]
Hello,

In the wiki, under [Troubleshooting](https://github.com/neovim/neovim/wiki/Troubleshooting#e518-unknown-option-option) it says to check `:help nvim-features-removed ` to view features that have been removed from nvim but gives a `E149: Sorry, no help for nvim-features-removed` error.

I also clicked the link provided on said Troubleshooting page for the features removed list and a 404 is returned. 

I discovered this after I found `:shell` not to be working. I've already reported the problem, it's issue #2794

>NVIM 0.0.0-alpha (compiled Jun  4 2015 16:21:35)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/build/config -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/src -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-SN4Xqa/neovim-0.0.0+git201506041043+1674+9+10~ubuntu14.04.1/build/include
Compiled by buildd@lcy01-11

>Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

>   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by fwalch** [comment]
The link on the troubleshooting page was wrong, I fixed it.

Regarding the `:help` error, do any of the Neovim help topics work (e.g. `:h nvim`)? If not, you have probably set the `VIMRUNTIME` or `VIM` environment variables, causing Neovim to use a wrong runtime.

**Comment by JoelMon** [comment]
You are right, none of the Neovim help topics work. 

Thanks

**Comment by JoelMon** [comment]
Opps, sorry, I think I accidentally reopened the issue when I left the comment.

**Comment by fwalch** [comment]
@JoelMon No, just make sure neither `$VIM` nor `$VIMRUNTIME` are set.
