### ISSUE TITLE
vim.iter: rename some functions before 0.10 release

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#27953]
### Problem

stub issue to track 0.10 blocker for renaming some `vim.iter` functions. 

### Expected behavior

- let `vim.nth` take a negative index; remove `vim.nthback` 
- `nextback()` => `pop()`, or support negative index to `next()` ? [ref](https://github.com/neovim/neovim/pull/23029#pullrequestreview-1746241433)
- `peekback()` => `peek(-1)` ? `peek('end')` ? 
- rename all "back" functions to something more common (rust doesn't count) https://github.com/neovim/neovim/pull/26169#discussion_r1405125062
    - we have `rfind()`, could we rename the `xxback()` functions to `rxx()` ?
- ...

**Comment by bfredl** [comment]
Could there be some more clarifications what about what parts of this is really blocking?

If this was done _after_ 0.10, we would need to keep some deprecated aliases in 0.11. that doesn't seem like a critical issue to me.

**Comment by justinmk** [comment]
> If this was done _after_ 0.10, we would need to keep some deprecated aliases in 0.11. t

Well, managing all of these aliases is an annoying amount of work. And it's more work than fixing it now. So let's just fix it now.

There is no reason 0.10 can't wait another month.

**Comment by bfredl** [comment]
Sure, I just wanted some more information to be able to plan properly. My tentative first possible release day is 12:th of april (or if we are not ready, a hard freeze for pre-approved PR:s for a release on the 19:th). That sounds like long enough to count as "now" to me. 

Of course, the more complete and concrete the list of things that are "wrong" are, the easier it will be for someone else to contribute :)

**Comment by justinmk** [comment]
Yeah. I will do this soon.
