### ISSUE TITLE
winbar common to all splits

### ISSUE THREAD

**Issue by Zeioth** [neovim/neovim#27959]
### Problem

on [NormalNvim](https://github.com/NormalNvim/NormalNvim) we ship shortcut buttons on the winbar.
![screenshot_2024-03-21_04-31-19_736066824](https://github.com/neovim/neovim/assets/3357792/31c1e919-cbb1-40ff-958d-f1c53699c833)

Because on neovim the winbar is per split by default, opening a split will duplicate the controls.
![screenshot_2024-03-21_04-31-09_250427733](https://github.com/neovim/neovim/assets/3357792/f89d6f4f-99f1-42f6-bab7-0d2ffc280306)

### Expected behavior

It would be great having a option for having a single winbar for the visible area, instead of default per split.

**Comment by zeertzjq** [comment]
Duplicate of #12925
