### ISSUE TITLE
Signature issue on latest macos nightly

### ISSUE THREAD

**Issue by bmichotte** [neovim/neovim#27960]
### Problem

The latest (at least 21/03/24 and 20/03/24) have an issue on macos where there is an alert saying that the "developer can not be verified".

![CleanShot 2024-03-21 at 08 30 32@2x](https://github.com/neovim/neovim/assets/235510/9229f9bc-6d03-4584-b192-f8e67908f60e)
(sorry for the french screenschot)

If you "bypass" this error by allowing the app to be run in the settings, you'll have the same error with "nvim.so"
![CleanShot 2024-03-21 at 08 31 59@2x](https://github.com/neovim/neovim/assets/235510/8ccc53f7-4a13-4ab0-aceb-55bb459dd526)

### Steps to reproduce

download nvim on mac and run it

### Expected behavior

no certificate issue I guess :)

### Neovim version (nvim -v)

v0.10.0-dev-2663+gc1c6c1ee1

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

14.4

### Terminal name/version

iTerm2 Build 3.5.0beta22

### $TERM environment variable

xterm-256color

### Installation

nightly release

**Comment by clason** [comment]
@carlocab

**Comment by carlocab** [comment]
Can't reproduce. Which version of macOS are you on? What is the output of `sw_vers`? If you have `brew` installed, the output of `brew config` would be helpful. (If you don't have it installed, there's no need to install `brew` for it.)

**Comment by bmichotte** [comment]
@carlocab The output of `sw_vers` is 

```
ProductName:		macOS
ProductVersion:		14.4
BuildVersion:		23E214
```

on a macbook m3 max

I don't have brew, using macports instead

**Comment by carlocab** [comment]
How did you download the nightly release?

Do you still have the problem if you do
```sh
cd "$(mktemp -d)"
curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz | 
  tar -x --strip-components 1
bin/nvim -u NONE -i NONE
```
?

**Comment by bmichotte** [comment]
Ok, that's really strange. If I follow your commands, there's no issue but if I download it with Arc then uncompress it with the default macos archiver, it breaks

**Comment by clason** [comment]
> Can't reproduce. Which version of macOS are you on? What is the output of `sw_vers`? If you have `brew` installed, the output of `brew config` would be helpful. (If you don't have it installed, there's no need to install `brew` for it.)

I can reproduce on Sonoma 14.4 (beta) for the record; this seems to be a recent change in macOS. I thought we had solved this problem in our packaging.

**Comment by clason** [comment]
You can do `xattr -c bin/nvim` to break the quarantine.

**Comment by clason** [comment]
Wait, that _is_ already documented in the release notes.

**Comment by bmichotte** [comment]
@clason it's not enough, if you only do the `xattr -c bin/nvim`, you'll end up with one.

![CleanShot 2024-03-21 at 12 30 48@2x](https://github.com/neovim/neovim/assets/235510/3d19d0f2-92cc-49b5-aaa3-09f72d8fcdd8)

It appears if you try to run any command like `:q`, I guess we have to `xattr lib/nvim/parser/vim.so` as well ? (all the *.so in that directoy too ?)

**Comment by clason** [comment]
You need to strip the attribute from the archive before extracting, as it says on the Release page.
