### ISSUE TITLE
python interface "vim.current.line" cannot be edited

### ISSUE THREAD

**Issue by unphased** [neovim/neovim#2796]
Hi, I realize this may be a silly question but I think the python interface is tantalizingly close to allow quick scripting of really intuitive custom behavior, making Vim even more practical than ever before, as writing a keybind quickly into the `.vimrc` can be a lot less effort than writing an entire plugin structure.

For example I wanted to see if there is a really neat way to modify the current line in vim, and I tried this: 

`:py vim.current.line[4] = 'z'`

Unfortunately this throws an error

```
Traceback (most recent call last):                       
  File "<string>", line 1, in <module>                   
TypeError: 'str' object does not support item assignment 
```

So that is a bummer but I found great success with 

`:py vim.current.buffer[0] = 'abc'`

I think I can figure out how to find the current line number and use the `buffer[n]` as a workaround, and this is great because I can finally use python syntax to munge the lines in the current buffer in Vim (which can handle a huge class of specific text manipulation automation tasks), but I just wonder why the `vim.current.line` (which the doc says is RW read write) is not writable?

**Update:** I have now realized that I just have to set the entire line, like this: 

`:py vim.current.line = 'z'`

I think I can close now because this is fine and not being able to twiddle a specific char is not much of a requirement.

**Comment by ZyX-I** [comment]
`vim.current.line[4]` is equivalent to `vim.current.buffer[vim.current.window[0]][4]` and this is *not* writeable. You must use `vim.current.line = vim.current.line[:4] + 'z' + vim.current.line[5:]`, same with `vim.current.buffer[…]`.
