### ISSUE TITLE
windo should not change the current window

### ISSUE THREAD

**Issue by j-xella** [neovim/neovim#27964]
### Problem

Not sure if this is a bug or feature. It has probably been there for ages, both vim and nvim, and everyone lives with it. But...

1. Split vim tab into several windows
2. Perform some windo operation, for example `windo pwd`
3. After the operation, the current window changes to the last window in the tab, no matter which window you executed the command from

Does it make a lot of sense? Seems more natural to me that the current window should not change after that. I am pretty sure there is a way to implement similar functionality in vimscript or lua, but shouldn't core windo behave "properly" out of the box?

### Expected behavior

Current window stays intact after windo.

**Comment by zeertzjq** [comment]
That's not backward-compatible.
