### ISSUE TITLE
--listen --headless displays long messages incorrectly

### ISSUE THREAD

**Issue by williamhCode** [neovim/neovim#27975]
### Problem

I'm making a UI for neovim, and noticed that using `--listen` with `--headless` makes long printed messages display weird. The message window is not focused, and jumps to the end. Happens both with and without multigrid.

Here I run the neovim instance with and without `--headless` and connect my UI to both. I do `lua vim.print(vim.fn.api_info())` to print a long message, and with `--headless` everything is messed up. When I use `k` to scroll up it keeps printing the same thing.

https://github.com/neovim/neovim/assets/83525937/e67c1ea7-9fcc-4ca4-adb0-52163f91a567

### Steps to reproduce

1. Run `nvim --listen localhost:6666 --headless`
2. Connect ui to port
3. Run `:lua vim.print(vim.fn.api_info())`

### Expected behavior

Message displays correctly

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2604+g59aadf33e-Homebrew

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 14.3.1

### Terminal name/version

tmux

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
Can you try latest commit? #27905 and #27913 have changed some behavior related to this.

**Comment by zeertzjq** [comment]
Fixed by #27905
