### ISSUE TITLE
Assertion `buf->osigncols.count[prevwidth -1] >= 0 failed.

### ISSUE THREAD

**Issue by grappas** [neovim/neovim#27982]
### Problem

In new file (not filling whole screen) at the moment inputing any character throws this assertion:

![obraz](https://github.com/neovim/neovim/assets/1036957/a5d8b617-8fc0-4925-8d3c-3f46ffb6b09a)

### Steps to reproduce

`nvim any.c`
Input any text

### Expected behavior

n/a

### Neovim version (nvim -v)

v0.10.0-dev-2672+g849d82b80b

### Vim (not Nvim) behaves the same?

VIMno  - Vi IMproved 9.1 (2024 Jan 02, compiled Mar 05 2024 22:43:21)

### Operating system/version

Arch

### Terminal name/version

foot version: 1.16.2-127-g9fcf5977 (Mar 21 2024, branch 'master') +pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Installation

AUR

**Comment by clason** [comment]
We don't support nightly distro packages. If you can reproduce this with a nightly downloaded from our release page and (important!) `nvim --clean`, please give exact reproducible steps (including a text file and the exact input sequence, if necessary).

**Comment by grappas** [comment]
Standalone build - same result
`nvim --clean` - works

**Comment by luukvbaal** [comment]
Statuscolumn affects it in the sense that it's not possible to reach the assert without it set, or 'signcolumn' set to "auto:x>1". If you can single out the plugin that causes it that would be sufficient if it really crashses as soon as the first character is entered.

**Comment by luukvbaal** [comment]
> If you can single out the plugin(s) that cause it that would be sufficient if it really crashses as soon as the first character is entered. 

And if not. even a complete config that reproduces the issue would be appreciated. I tried your public dotfiles but couldn't reproduce.

**Comment by grappas** [comment]
I can reproduce it every time inside `/tmp` dir `nvim main.c`

**Comment by luukvbaal** [comment]
With the config in your "dotfiles" repo? And nvim built from `master`?

**Comment by grappas** [comment]
> With the config in your "dotfiles" repo? And nvim built from `master`?

`lazyvim` config and yes for `master`

**Comment by grappas** [comment]
and for now... only `dupa.c` is crashing xD

**Comment by luukvbaal** [comment]
What is `dupa.c`?

**Comment by grappas** [comment]
> What is dupa.c?

An example, non existent file. `dupa` means `ass` in polish.

**Comment by luukvbaal** [comment]
OK, but I can't reproduce it in an empty file.

**Comment by clason** [comment]
No, we mean an explicit list of steps we can follow with nvim --clean -up minimal.lua

This is not optional.
