### ISSUE TITLE
`vim.ui.open` locks up Neovim until the opened process closes due to `:wait()`

### ISSUE THREAD

**Issue by folke** [neovim/neovim#27986]
### Problem

As can be seen [here](https://github.com/neovim/neovim/blob/849d82b80b8584fe7918bffc6480f0ec0fda9b9b/runtime/lua/vim/ui.lua#L155), `vim.ui.open` currently opens the process with `detach = true`, **which is good**, but then at the same time waits till it finishes (**is bad**).

This means that Neovim effectively locks up till you close the opened process again.

tbh, I don't really see a lot of cases where this kind of behavior could be useful.

The return value of the function, could still be an error if `vim.ui.open` failed to start the process.
Or even better, just return the task object itself (so `vim.system(cmd, { text = true, detach = true })`), then the caller can still use `:wait()` if they really want to.

I'm willing to make a small PR to fix this, but want to get some input first on wanted behavior.

See also https://github.com/LazyVim/LazyVim/pull/2758

### Steps to reproduce

use `vim.ui.open`

### Expected behavior

should not block

### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256-color

### Installation

bob

**Comment by adelarsq** [comment]
Misbehaviour also confirmed on Windows + Neovim Nightly  + Wezterm.

**Comment by justinmk** [comment]
> Or even better, just return the task object itself

Is there a way we can make it work with `vim.wait()` ? 

Is this bug affecting `gx` ?

**Comment by folke** [comment]
It does indeed also affect `gx`. Makes that also unusable.

> Is there a way we can make it work with vim.wait() ?

There simply shouldn't be a wait for the caller.

I suggest we return the task object itself. The caller can then still decide to wait if they really want to,
but in probably 99% of the cases, you don't want to wait for a running GUI application

**Comment by justinmk** [comment]
> I suggest we return the task object itself. The caller can then still decide to wait if they really want to,

Yeah, that's kind of what I was trying to avoid by "making it work with `vim.wait()` instead". The `vim.system()` task is not really something that should "leak" since it's an implementation detail that may change. 

Not a hill worth dying on in this case, though. We also have the option of returning a wrapper object that only exposes `:wait()`.
