### ISSUE TITLE
ctrl-c get replaced by <80>ü^DC when on .sql file

### ISSUE THREAD

**Issue by dinhquangkhuong** [neovim/neovim#27992]
### Problem

[Screencast from 2024-03-23 16-16-35.webm](https://github.com/neovim/neovim/assets/113097235/76eb8535-7099-47c1-a1c0-687a4e3bd41d)

### Steps to reproduce

nvim --clean <any-file-end-with-.sql>

### Expected behavior

ctrl-c should excape from insert mode to normal mode

### Neovim version (nvim -v)

nvim v0.9.5

### Vim (not Nvim) behaves the same?

yes, vim 9.1

### Operating system/version

Fedora Linux 39 (Workstation Edition) x86_64

### Terminal name/version

alacritty 0.13.1

### $TERM environment variable

tmux-256color

### Installation

dnf install neovim

**Comment by zeertzjq** [comment]
`:h sql-completion-static`
