### ISSUE TITLE
attach current Nvim to peer Nvim server (on-demand / after startup)

### ISSUE THREAD

**Issue by kedom1337** [neovim/neovim#28012]
### Problem

Currently if one wants to attach a client to a server it has to be done on startup via the command line parameter `--server`. This is not sufficient when attaching to a server should be done dynamically by e.g. a plugin.

The main use case where the current functionality is limiting is at the attempt to enable [dev container](https://containers.dev/) support in neovim. The current workaround done by plugin authors is opening a terminal in the already running neovim session which then starts a nested neovim client with the appropriate `--server` parameter to connect to the instance running within the docker container. Having nested clients is clearly not optimal and an ugly workaround.

### Expected behavior

Neovim should expose functionality to dynamically attach an already running instance of neovim to a server.

**Comment by zeertzjq** [comment]
What do you want to do after connecting using `--server`?

**Comment by kedom1337** [comment]
In the specific case I mentioned, controlling the instance running in the docker container with `--remote-ui`. The whole point is having things like dependencies installed in the docker container, yet still getting a fully featured editor experience on the host.

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/issues/28040#issuecomment-2023089081

**Comment by Piotr1215** [comment]
> The whole point is having things like dependencies installed in the docker container, yet still getting a fully featured editor experience on the host.

@kedom1337 I'm looking exactly for the scenario you described, but cannot connect to the container, do you maybe have a working example how to connect to `neovim` instance running in a container using `--remote-ui`?

**Comment by kedom1337** [comment]
[This](https://codeberg.org/esensar/nvim-dev-container) plugin does exactly what I described. It currently has to use nested neovim instances due to the inability to connect a live instance to a server. Here is the relevant issue on the plugin repo [#30](https://codeberg.org/esensar/nvim-dev-container/issues/30).

**Comment by Piotr1215** [comment]
Thanks for the pointer, I was able to attach my local `nvim` to a remote instance in container using `nvim --listen 0.0.0.0:12345` and operate it from my machine with `nvim --remote-ui --server 0.0.0.0:12345` without the plugin. 

However, this is not what I'm looking for. The result is that I can connect to the _bare-bones_  `nvim` instance in the container, and the expected result is that I can edit files in the container from my local `nvim` instance. Running the command from within `nvim` terminal or without the `--remote-ui` flag doesn't work.

A possible workaround could be `scp`, but it's tedious and allows only one file at a time. Am I missing something here?

**Comment by justinmk** [comment]
IIUC, this would be addressed by adding a `:connect [server]` command which "hot swaps" the current UI client to attach to a different server. Tracked in: https://github.com/neovim/neovim/issues/5035#issuecomment-2343537003
