### ISSUE TITLE
Creating a mark modifies reported cursor position

### ISSUE THREAD

**Issue by carlinigraphy** [neovim/neovim#28019]
### Problem

The position of the cursor (reported by `nvim_win_get_cursor()`) is changed by setting a mark.

## Steps

1. Create _tmp.lua_ with the following:

```lua
local c1 = vim.api.nvim_win_get_cursor(0) 
vim.cmd[[ normal! ma ]]                   
local c2 = vim.api.nvim_win_get_cursor(0) 
print(c1[2], c2[2])       
```

2. Run:

```shell
nvim --clean tmp.lua
```

3. Run `:source` . Column reported by `nvim_win_get_cursor()` differs after the `normal! ma` command.

## Additional notes

While the cursor does not move, its reported column is off by 1.

### Expected behavior

Column output should report unchanged, just as setting a mark in normal mode would.

```vim
:h mark
```

```help
						*m* *mark* *Mark*
m{a-zA-Z}		Set mark {a-zA-Z} at cursor position (does not move
			the cursor, this is not a motion command).
```

### Neovim version (nvim -v)

v0.9.5

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.13.1 (fe2a3c56)

### $TERM environment variable

xterm-256color

### Installation

AUR

**Comment by zeertzjq** [comment]
You have a trailing space in the `:normal` command. Remove the trailing space:
```lua
local c1 = vim.api.nvim_win_get_cursor(0) 
vim.cmd[[normal! ma]]
local c2 = vim.api.nvim_win_get_cursor(0) 
print(c1[2], c2[2])
```

**Comment by carlinigraphy** [comment]
Oof. Didn't realize trailing spaces were significant.

Thank you for the prompt reply.
