### ISSUE TITLE
Run treesitter "offline" to not affect performance

### ISSUE THREAD

**Issue by kaddkaka** [neovim/neovim#28017]
### Problem

When treesitter experience slow performance, this carry over to basic vim operations such as simple editing or logging (e.g. `G`), see for example https://github.com/neovim/neovim/issues/24965

### Expected behavior

Would it be possible to do the treesitter work in a separate thread or in some other manor to interfere  less with just moving around?

For example, does scrolling with capital G need to perform treesitter queries at all?

**Comment by clason** [comment]
Performance improvements are already tracked elsewhere. Since the highlighter runs in a fast loop, we cannot just offload this easily to a separate thread.

**Comment by kaddkaka** [comment]
> And, yes, scrolling needs to trigger the parser since we only run injections for the visible region -- for performance reasons.

Is this also the case for code when no injections should be taking place? As in: #30424

**Comment by clason** [comment]
Yes.
