### ISSUE TITLE
A Discord server

### ISSUE THREAD

**Issue by CPU-governor** [neovim/neovim#28026]
### Problem

i think it will be cool if neovim had a discord server, it can be called "The Neovimers".
It can have sub channels like #cpp discussion, java, ...,  so users can talk about their interest and can also ask questions about nvim.
I can help build the discord server, make it fun, interesting and be a moderator if you wish. thanks for reviewing my request

### Expected behavior

A sense of community

**Comment by bfredl** [comment]
https://discord.gg/Cz9J4ZD
