### ISSUE TITLE
"filetype off" in init.vim is not respected after neovim starts

### ISSUE THREAD

**Issue by zrbecker** [neovim/neovim#28039]
### Problem

When `filetype off` is set in the init script, it is overridden after the init script runs.

### Steps to reproduce

```
$ cat <<'EOF' > init.vim
filetype off
filetype plugin off
filetype indent off
EOF

$ nvim --clean -u init.vim
```

When you type `:filetype`, the output is `filetype detection:ON  plugin:OFF  indent:OFF`

### Expected behavior

the expected output is `filetype detection:OFF  plugin:OFF  indent:OFF`

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

no, 8.1.1847

### Operating system/version

Mac OS X

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256color

### Installation

Installed via brew, and built from source. Also tested built from source on Ubuntu LTS.

**Comment by zeertzjq** [comment]
Nvim enables syntax by default, which implicitly enables filetype detection. To disable filetype detection you need to also disable syntax:
```
syntax off
filetype off
filetype plugin off
filetype indent off
```
