### ISSUE TITLE
`vim.fs.normalize` mangles unix paths with backslash

### ISSUE THREAD

**Issue by jamestrew** [neovim/neovim#28061]
### Problem

Backslashes are valid characters in unix paths.
Current implementation of `vim.fs.normalize` converts all backslashes to forward slashes, resulting in invalid/wrong paths.

see: https://github.com/neovim/neovim/issues/27958#issuecomment-2022937067

### Steps to reproduce

`:lua =vim.fs.normalize([[/a/b\c]])` --> becomes `/a/b/c`

### Expected behavior

Backslashes should be untouched for unix paths.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2718+g1bfe6fdce

### Vim (not Nvim) behaves the same?

no, vim.fs

### Operating system/version

Linux archlinux 6.7.5-arch1-1

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by jamestrew** [comment]
My proposal would be to only convert backslashes for forward slashes on Windows. I can put together a PR later today if this sounds good.

**Comment by ObserverOfTime** [comment]
What if someone wants to normalize a Windows path in Unix?

**Comment by clason** [comment]
Why? We don't support cross compilation. 

Please don't let hypotheticals block actual improvements.
