### ISSUE TITLE
Lua: `vim.go` accesses local-only options

### ISSUE THREAD

**Issue by asmodeus812** [neovim/neovim#28079]
### Problem

At the moment there are certain options which are only local to window (such as wrap and list, and others), there are many plugins which implement a `bigfile` feature where when a sufficiently big file is explored certain features are turned off. Those plugins rely, often on restoring some of these options, by simply querying the global options table, however if you modify `vim.wo.wrap = false` it would automatically render `vim.go.wrap` or `vim.o.wrap` useless, (one must save the current window local options on VimEnter i suppose) since the wrap option is window local only, there is no `global` scope for them. Therefore `vim.o.wrap` will always return whatever the value of current `vim.wo.wrap` is.

### Expected behavior

Only Window local options should not pollute the global options object i.e `vim.o.wrap` should result in an error, or window-global options should exist, this is quite a messy topic too.

**Comment by clason** [comment]
Window options are a mess. But the described behavior sounds to me correct _given how these accessors are documented_. We will not make further convenience changes that makes reasoning about these even harder.

**Comment by clason** [comment]
So there's a bug with _one_ specific option; sounds to me like that should be fixed instead of adding yet more cards to the already teetering house?

**Comment by asmodeus812** [comment]
No it is not one specific option the same applies to all window options i tested, 'list' is the same, 'breakindent', 'cc', there are probably more. Some like 'cursor' work fine maybe. 

I am not proposing a behavior change, i thought this was not a bug, but it seems like it is. Some window local options can be accessed from vim.go

**Comment by clason** [comment]
Definitely bug. The intention is documented; if something doesn't match it, it's a bug. (And I did not say it was the only one with a bug...)

**Comment by zeertzjq** [comment]
Window-local options still have global and local values. Global values are for all buffers shown in the window, and local values are for only a single buffer. However, `vim.wo` changes both the global value and the local value, unless using double indexing, in which case it only changes the local value.

**Comment by zeertzjq** [comment]
And I don't think there is a strong enough reason to break backward-compatibility.

**Comment by asmodeus812** [comment]
> Window-local options still have global and local values. Global values are for all buffers shown in the window, and local values are for only a single buffer. However, `vim.wo` changes both the global value and the local value, unless using double indexing, in which case it only changes the local value.

Any chance this gets a documentation ? What double indexing

```md
vim.wo[{winid}]                                                                vim.wo
    Get or set window-scoped options for the window with handle {winid}.
    Like :set. If [{winid}] is omitted then the current window is used.
    Invalid {winid} or key is an error.       
```

**So vim.wo.wrap is different than vim.wo[curwin].wrap ?**

**Comment by zeertzjq** [comment]
It's already documented:
```
vim.wo                                                                *vim.wo*
    Get or set window-scoped |options| for the window with handle {winid} and
    buffer with number {bufnr}. Like `:setlocal` if setting a |global-local|
    option or if {bufnr} is provided, like `:set` otherwise. If {winid} is
    omitted then the current window is used. Invalid {winid}, {bufnr} or key
    is an error.
```

**Comment by zeertzjq** [comment]
It's #20288

**Comment by asmodeus812** [comment]
Was refering to this - However, vim.wo changes both the global value and the local value, unless using double indexing, in which case it only changes the local value..

You implying that setting throught vim.wo is different than vim.wo[0][0] ? 

Vim.wo.wrap = false - will do it for the entire window and any buffer shown, but it will also mutate vim.go.wrap ? 

Vim.wo[0][0] = false - that sets the wrap only for the buffer for the current window ? If buffer is shown in another window, it will inherit that other windows wrap ? This will not change vim.go.wrap ?

**Comment by clason** [comment]
> You implying that setting throught vim.wo is different than vim.wo[0][0] ? (Assume Current window and buffer)

Yes, on `master`. The change is not backported to any 0.9.x release.
