### ISSUE TITLE
neovim 0.10 version crashes when traversing words with 'w' key press

### ISSUE THREAD

**Issue by emailstorbala** [neovim/neovim#28089]
### Problem

> Confirm the problem is reproducible on [master](https://github.com/neovim/neovim/releases/nightly) or [latest stable](https://github.com/neovim/neovim/releases/stable) release
Its reproducible in `master` branch

> Run make distclean when encountering build issues
No build issues.

Command used build nvim:

make CMAKE_BUILD_TYPE=RelWithDebInfo clean
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

Note: Using Astronvim configuration on top of neovim.

### Steps to reproduce

nvim <test.txt> # File contains some texts
Press `w` key 2 to 3 times

### Expected behavior

When pressing `w` key, word traversing forward should happen.

### Neovim version (nvim -v)

0.10

### Vim (not Nvim) behaves the same?

no, vim 9.1.16

### Operating system/version

Debian GNU/Linux trixie/sid

### Terminal name/version

KDE Konsole

### $TERM environment variable

screen-256color

### Installation

make

**Comment by zeertzjq** [comment]
Can you provide a backtrace? https://neovim.io/doc/user/dev_tools.html#dev-tools-backtrace

**Comment by zeertzjq** [comment]
And please follow the instruction for "steps to reproduce":
> Use the provided [minimal reproduction template](https://github.com/neovim/neovim/blob/master/contrib/minimal.lua) to create a minimal configuration. After you fill it out with necessary information, run with `nvim --clean -u minimal.lua`.

**Comment by emailstorbala** [comment]
@zeertzjq I don't know whether I did the steps with gdb properly. I got something like this below:

```
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/nvim...

warning: Can't open file anon_inode:[io_uring] which was expanded to anon_inode:[io_uring] during file-backed mapping note processing

warning: Can't open file anon_inode:[io_uring] which was expanded to anon_inode:[io_uring] during file-backed mapping note processing

warning: Can't open file anon_inode:[io_uring] which was expanded to anon_inode:[io_uring] during file-backed mapping note processing

warning: Can't open file anon_inode:[io_uring] which was expanded to anon_inode:[io_uring] during file-backed mapping note processing

warning: Can't open file anon_inode:[io_uring] which was expanded to anon_inode:[io_uring] during file-backed mapping note processing

warning: Can't open file anon_inode:[io_uring] which was expanded to anon_inode:[io_uring] during file-backed mapping note processing

warning: Can't open file anon_inode:[io_uring] which was expanded to anon_inode:[io_uring] during file-backed mapping note processing

warning: Can't open file anon_inode:[io_uring] which was expanded to anon_inode:[io_uring] during file-backed mapping note processing
[New LWP 63967]
[New LWP 63982]
[New LWP 63983]
[New LWP 63984]
[New LWP 63985]
[New LWP 63969]
[New LWP 63986]

warning: Section `.reg-xstate/63967' in core file too small.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nvim --embed src/main.rs'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/63967' in core file too small.
#0  changed_window_setting (wp=0x0) at /home/balamurugan/SoftwaresAndDrivers/neovim-dbg/src/nvim/move.c:542
542       wp->w_lines_valid = 0;
[Current thread is 1 (Thread 0x7f52e89e1b80 (LWP 63967))]```

[bt.txt](https://github.com/neovim/neovim/files/14800346/bt.txt)

**Comment by emailstorbala** [comment]
[bt.txt](https://github.com/neovim/neovim/files/14800354/bt.txt)

**Comment by zeertzjq** [comment]
It's likely that your [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo) version is outdated. You need to update its version to after this commit: https://github.com/kevinhwang91/nvim-ufo/commit/e29dbf5b2d76ea43f4e585e3deeb6510488eee3f.

**Comment by emailstorbala** [comment]
> It's likely that your [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo) version is outdated. You need to update its version to after this commit: [kevinhwang91/nvim-ufo@e29dbf5](https://github.com/kevinhwang91/nvim-ufo/commit/e29dbf5b2d76ea43f4e585e3deeb6510488eee3f).

@zeertzjq How to update that? Is there any procedure for that? I am just cloning `neovim` repo and did the make steps.
Note: I know 0.10 is not stable yet but just wanted to try it out.

**Comment by zeertzjq** [comment]
Ask Astronvim.

**Comment by emailstorbala** [comment]
Thank you for identifying the issue @zeertzjq . I can confirm that this is an issue caused by `kevinhwang91/nvim-ufo` referred in Astronvim `nvim/lua/plugins/core.lua` file. When I commented the plugin configuration, the issue went away.
