### ISSUE TITLE
Tmux server exits when starting neovim

### ISSUE THREAD

**Issue by jrschenk** [neovim/neovim#28082]
### Problem

As soon as I try to start neovim,  neovim fails to start and the tmux  server exits.

### Steps to reproduce

open a tmux session and start neovim.

The issues first appears with commit 4ee9e58056... from Mar 28.  The previous commit 7168000. didn't have this problem.

### Expected behavior

I expect neovim to start without crashing.

### Neovim version (nvim -v)

commit 4ee9e58056... 

### Vim (not Nvim) behaves the same?

-

### Operating system/version

macOS 14.4.1

### Terminal name/version

item 3.4.23

### $TERM environment variable

screen-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by zeertzjq** [comment]
And I don't think this is solvable on Nvim's side because `TERM` doesn't even contain `tmux`.

**Comment by jrschenk** [comment]
I have set term to tmux-256color and the problem is still there. Tmux version is 3.4.

**Comment by Cnly** [comment]
I guess it might be worth it to cross post this issue from tmux here https://github.com/tmux/tmux/issues/3983, as it seems #28086 should have fixed the problem but it didn't.

**Comment by zeertzjq** [comment]
It seems that the tmux detection doesn't work in Docker either: #28827

**Comment by Cnly** [comment]
@zeertzjq I'm wondering whether the detection is supposed to work in nested tmux? My local tmux still crashes if I do tmux → ssh → tmux → nvim, and my remote tmux's TERM is `tmux-256color`.

**Comment by zeertzjq** [comment]
Nvim can detect your remote tmux but not your local tmux, and is try to send a passthrough sequence. Try disabling `allow-passthrough` in your remote tmux.

**Comment by jby** [comment]
> @zeertzjq I'm wondering whether the detection is supposed to work in nested tmux? My local tmux still crashes if I do tmux → ssh → tmux → nvim, and my remote tmux's TERM is `tmux-256color`.

My tmux doesn't crash if I run locally, i.e. tmux -> nvim, it only crashes if I start nvim on a remote host, i.e. tmux -> ssh -> nvim.

**Comment by blackthorne7** [comment]
@jby what if you `sudo nvim` a file? interestingly enough, I can tmux -> ssh -> nvim just fine - but calling sudo nvim is what crashes my tmux.
