### ISSUE TITLE
Inconsistent spelling of grey/gray in `:h gui-colors`

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#28096]
### Problem

Among the GUI colour names there are various shades of grey. The spelling is inconsistent between the names defined by Vim and those defined by Neovim. Vim uses the spelling "gray" (with an "a"), Neovim uses "grey" (with an "e").

I don't have any opinion on which spelling we should use, but it should be consistent. If I had to pick my vote would go to "gray" because Vim set the precedent. Ideally both should work and produce the same result, but the manual should be consistent regardless of whether both spellings work or only one.

### Steps to reproduce

```vim
hi Herp guibg=NvimLightGrey1
hi Derp guibg=NvimLightGray1

hi Herp | hi Derp
```

The output is

```
Herp           xxx guibg=NvimLightGrey1
Derp           xxx cleared
```

So clearly the "gray" spelling does not work.

### Expected behavior

Both spelling should work. Interestingly, this seems to be the case with the Vim colour names.

```vim
hi Herp guibg=LightGrey
hi Derp guibg=LightGray

hi Herp | hi Derp
```

```
Herp           xxx guibg=LightGrey
Derp           xxx guibg=LightGray
```

They show different text, but the output looks the same on my terminal.

![Screenshot_20240329_120028](https://github.com/neovim/neovim/assets/4954650/f0e76e25-0aef-4ed3-8d77-ed770349dac7)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2739+ge2224a793

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Void Linux

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

AppImage

**Comment by clason** [comment]
We have both, as a treat.
