### ISSUE TITLE
Feat (filetype) - detect Faust programming language: *.dsp

### ISSUE THREAD

**Issue by PowerUser64** [neovim/neovim#28094]
### Problem

Neovim currently detects Faust `.dsp` files ([example](https://github.com/magnetophon/lamb/blob/994fa3b0c30aa3c53d3d28ba1bf37d1b1971194e/lamb.dsp)) as being the C programming language. I think this is because they have similar syntax, or possibly because C is the default. That said, `.dsp` files should be detected instead as the `faust` filetype because `.dsp` is the extension used for the Faust programming language.

### Expected behavior

Neovim should set `filetype=faust` when opening a `.dsp` file. Additionally, Faust uses the `.lib` extension for library files, so it would be nice to have it label those as Faust too. However, I'm not sure if any other languages use `.lib` as an extension too, so it's possible that will have to be excluded if there are conflicts. Right now, `.lib` detected as C too, so I don't _think_ there are any conflicts.

**Comment by clason** [comment]
Please open a pull request at vim/vim; we follow its filetype detection logic exactly and do not deviate.

**Comment by PowerUser64** [comment]
Addressed in vim/vim#12363
