### ISSUE TITLE
Wrong split terminal position

### ISSUE THREAD

**Issue by sytranvn** [neovim/neovim#28091]
### Problem

Openning terminal with `:vertical terminal`, `:belowright terminal`, `:aboveleft terminal` 
doesn't put the terminal at expected location and equal size with existing. Instead it takes the whole buffer space.

### Steps to reproduce

nvim --clean :vertical terminal :belowright terminal :aboveleft terminal

### Expected behavior

3 terminal windows are displayed on screen.

<img width="1302" alt="Screenshot 2024-03-29 at 15 49 09" src="https://github.com/neovim/neovim/assets/13009812/d59eb658-116e-41ac-bf9a-7bbc7f76071d">

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

9.0.1894

### Operating system/version

macOS 14.1

### Terminal name/version

terminal 2.14

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
v0.10-dev is need for `:terminal` with modifiers.

**Comment by sytranvn** [comment]
Just tried it out. Working great!
