### ISSUE TITLE
Wrong extmark position set in nvim_buf_attach on_lines event when entering a newline in insert mode

### ISSUE THREAD

**Issue by TheBlob42** [neovim/neovim#28107]
### Problem

Setting extmarks in the `on_lines` event of `nvim_buf_attach` for the updated lines results in wrong positions (rows) when a newline was "entered" in insert mode (not on paste, not using `o` in normal mode etc.).

The extmark is moved from to newline to the next line instead.  
Additionally for the latest nightly build (`v0.10.0-dev-2739+ge2224a793`) the virtual text is not shown on this line even though the extmark exists and is not invalidated.

The issue seems to be partly related to https://github.com/neovim/neovim/issues/14741, especially since the workaround from [this comment](https://github.com/neovim/neovim/issues/14741#issuecomment-1463201526) also works for this case.

### Steps to reproduce

Use the following `minimal.lua` file:

```lua
local ns = vim.api.nvim_create_namespace('test')
vim.api.nvim_buf_attach(0, false, {
        on_lines = function(_,_,_,fl,_,llu)
            vim.api.nvim_buf_clear_namespace(0, ns, fl, llu)

            for i = fl, llu - 1 do
                local id = vim.api.nvim_buf_set_extmark(0, ns, i, 0, {
                    virt_text = {{ 'A', 'WarningMsg' }},
                })

                vim.print(vim.api.nvim_buf_get_extmark_by_id(0, ns, id, {}))
            end
        end
    }
)
```

- start neovim using `nvim -u NONE minimal.lua`
- source the `minimal.lua` file using `:source %`
- on row 1 enter insert mode with `A` and press `ENTER`
    - the virtual text is visible in row 1 (correct)
    - there is no virtual text on the new empty row 2 (incorrect)
    - virtual text is shown in row 3 (incorrect)
        - this is true for the latest stable `0.9.5`
        - this is false for the latest nightly `v0.10.0-dev-2739+ge2224a793`

![image](https://github.com/neovim/neovim/assets/6849129/7538d79e-6740-4a6b-8cee-a3bca792099f)

Checking the `vim.print` outputs shows that the extmarks have the correct positions during the function execution:

```text
{ 0, 0 }                                                                        
{ 1, 0 }  
```

However checking the extmarks afterwards  shows the wrong positions:  
`:lua= vim.api.nvim_buf_get_extmarks(0,vim.api.nvim_create_namespace('test'), 0, -1, {})`

```text
{ { 1, 0, 0 }, { 2, 2, 0 } }
```

Wrapping the whole extmark creation into a `vim.schedule(function() ... end)` call like proposed in [this comment](https://github.com/neovim/neovim/issues/14741#issuecomment-1463201526) solves the problem.

Additionally using any other method to insert a newline (e.g. using `o` or pasting) places the extmarks in the correct positions as expected.

### Expected behavior

The extmarks are all placed in the correct positions independent how the newline(s) was inserted.
Furthermore for the newest nightly build I would also expect that the virtual text is shown.

### Neovim version (nvim -v)

v0.9.5

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Pop!_OS 22.04 LTS

### Terminal name/version

GNOME Terminal (Version 3.44.0 for GNOME 42)

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
Related #26499 #26501

**Comment by TheBlob42** [comment]
Thank you for the super fast fix :heart:
