### ISSUE TITLE
extending visual selection via single mouse click broken when NOT spanning multiple lines

### ISSUE THREAD

**Issue by aerusso** [neovim/neovim#28104]
### Problem

This is on Debian. Back on 0.7.2, you could place the mouse cursor at a spot, and single right click to enter visual mode and select all text between the cursor location and the right click.

I recently upgraded to 0.9.5, and that behavior has been removed, or at least modified.  Under certain conditions, I can achieve essentially the same thing by first pressing v to enter visual mode, and then Control+Left clicking at a location.  The visual mode then starts at the original cursor location, and ends at the left-click location.

I say "certain conditions" because of the following:

### Steps to reproduce

nvim --clean

press i to enter insert mode

type "asdf asdf"
press escape
press v
control-click on the "s" in the first "asdf"
Get this error:

```
E433: No tags file                                                         
E426: tag not found: sdf asdf
```

### Expected behavior

You can get the expected behavior by (continuing in the same neovim session)

press o
type "asdf asdf"
press Escape
press v
control-click on the "s" in the first "asdf"

The text between the end of the file and the s in the first asdf should now be highlighted.

Given that regular vim behaves this way, is this intended behavior? Why is the control+click behavior so different between selections attempted on the same line vs. selections spanning lines?  Is there another way to use the mouse to select a small section of text that does not span multiple lines?

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

yes, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 04 2023 10:24:44)

### Operating system/version

Debian unstable

### Terminal name/version

konsole 23.08.1

### $TERM environment variable

xterm-256color

### Installation

Debian apt-get (unstable)

**Comment by zeertzjq** [comment]
`:set mousemodel=extend`
