### ISSUE TITLE
Neovim doesn't highlight after 3000 characters on a single line

### ISSUE THREAD

**Issue by JustAPerson** [neovim/neovim#2810]
![primes](http://i.imgur.com/WZ7YtfB.png)

After 3000 characters, neovim stops highlighting the rest of the line. The remainder of the file is highlighted as usual. This is the same behavior as standard vim.

**Comment by ntnn** [comment]
`:h 'synmaxcol'`

**Comment by JustAPerson** [comment]
@ntnn,

Ahh, thank you.
