### ISSUE TITLE
Broken scroll + zz mappings

### ISSUE THREAD

**Issue by MariaSolOs** [neovim/neovim#28106]
### Problem

On master, a mapping like `<C-d>zz` prevents the cursor from moving, while this correctly scrolled and centered the cursor previously.

### Steps to reproduce

1. Write the following config file to `repro.lua`:
```lua
vim.keymap.set('n', '<C-d>', '<C-d>zz', { desc = 'Scroll downwards' })
vim.keymap.set('n', '<C-u>', '<C-u>zz', { desc = 'Scroll upwards' })
```

2. Open Neovim with `nvim --clean -u repro.lua file`, where `file` has enough content to be able to scroll through it.
3. Type `<C-d>` or `<C-u>`. Notice how the cursor stays fixed.

### Expected behavior

For the mappings to scroll and center the cursor.

### Neovim version (nvim -v)

v0.10.0-dev-38e38d1b4

### Vim (not Nvim) behaves the same?

No, vim seems to have the correct behaviour

### Operating system/version

Asahi Fedora Linux 39

### Terminal name/version

wezterm 20240325_093507_e5ac32f2

### $TERM environment variable

wezterm

### Installation

From source

**Comment by echasnovski** [comment]
@luukvbaal, I believe this is a consequence of 2f638c0ac6275bebacd12671481642fa43d7ba10.

**Comment by luukvbaal** [comment]
Uhuh, some regressions are being discussed over at vim/vim as well.

**Comment by wojciech-kulik** [comment]
I confirm, the same behavior on my side. On v0.9.5 everything is ok.

**Comment by leiteg** [comment]
I am also having this problem with Neovim `v0.10.0-dev-2749+g38e38d1b40`.

**Comment by dagadbm** [comment]
glad to know im not the only one who noticed it.

**Comment by dagadbm** [comment]
is there a safer mapping we can use to prevent this issue? that does the same thing?

**Comment by luukvbaal** [comment]
```lua
vim.keymap.set('n', '<C-d>', '<C-d>Mzz', { desc = 'Scroll downwards' })
```

**Comment by wojciech-kulik** [comment]
Any plans to fix it? With this issue nightly is not usable for me anymore, I had to switch to 0.9.5

**Comment by zeertzjq** [comment]
You can checkout or apply the linked PR.
