### ISSUE TITLE
Confusing name and low discoverability for Inspect/InspectTree/EditQuery

### ISSUE THREAD

**Issue by ilan-schemoul** [neovim/neovim#28117]
### Problem

I wanted to debug a treesitter plugin so I type :TS and tab (I think using :prefix + tab is an usual way to try discover commands) and found none of what I was looking for.

What I needed was InspectTree and EditQuery but very surprisingly they were not prefixed by TS. Also it is confusing to have `TSEditQuery` and `EditQuery` both to edit TS queries (I guess one is persistent and the other not. Which is also not obvious from the names)

Discoverability of commands is usually good and seems very important especially as more complex features such as LSP and Treesitter become native. For treesitter it is not the case. 

### Expected behavior

Have explicit name with consistent prefix
For example
TSPlaygroundQuery
TSPlaygroundInspect
TSPlaygroundInspectTree
It could be TSDebugQuery etc. 
Or TSLiveQuery TSLiveInspect TSLiveInspectTree
Or whatever else you can come up with.
Maybe old commands should be kept as aliases.

**Comment by clason** [comment]
Where did your expectation come from? Not from Neovim. You could (and should) have done `:h vim.treesitter.<tab>`, which would have shown you the underlying functions and led you to the right documentation.

**Comment by clason** [comment]
(We never had any TS* commands in Neovim, just to be clear. What other plugins are doing is not our concern.)

**Comment by ilan-schemoul** [comment]
> (We never had any TS* commands in Neovim, just to be clear. What other plugins are doing is not our concern.)
Ok I thought TS* commands were from neovim but yeah it's coming from nvim-treesitter. The prefix can be something else. My point is more about how a prefix might help discoverability and help to understand what the commands do. 

vim.treesiter.<tab> shows a ton of function. These functions seem more for APIs. The editor commands (:InspectTree :Inspect :EditQuery and maybe others IDK) seem clearly more for users than for APIs as they interact with the UI. 

So the problem stands that a prefix might help discoverability of treesitter commands.

**Comment by ilan-schemoul** [comment]
> (We never had any TS* commands in Neovim, just to be clear. What other plugins are doing is not our concern.)
Ok I thought TS* commands were from neovim but yeah it's coming from nvim-treesitter. The prefix can be something else. My point is more about how a prefix might help disoverability 


vim.treesiter.<tab> shows a ton of function. These functions seem more for APIs. The editor commands (:InspectTree :Inspect :EditQuery and maybe others IDK) seem clearly more for users for APIs as they update the UI. So you totally missed my point


So the problem stands : it is not obvious how to find editor commands (the one accessible with ":") for treesitter and a prefix might help.

**Comment by zeertzjq** [comment]
`:Inspect` shouldn't be changed as it's not a treesitter command.

**Comment by ilan-schemoul** [comment]
Alright good point about :Inspect 
I would appreciate your input about prefixing of treesitter commands though (maybe there's other treesitters commands that I don't know btw, I do not know how to search in the help document because ":" is everywhere)

**Comment by clason** [comment]
Then you should learn how to search the help documents. It's a _very_ valuable skill. (Also, there's tab-complete for commands.) The "API" _is_ the intended way of interacting with treesitter, and reading `:h treesitter` is not optional if you want to do anything with it.

**Comment by ilan-schemoul** [comment]
> reading :h treesitter is not optional if you want to do anything with it.

Ok then if the assumptions for UX designing is that every single person reads everything you have to know before using any feature (e.g 1423 lines of help page for treesitter) and absolutely nothing should be done to increase discoverability then ok we can keep the design that way.
Yes I read help pages a lot but no it's not mutually exclusive with design helping discoverability. That's the reason why commands such as :Edit exist otherwise we literally just have :1 :2 :3 and then remember every command by heart.

> Then you should learn how to search the help documents. It's a very valuable skill. (Check out :helpgrep.)

Even with the help grep I still don't know how to find a command. As I said commands in the help page starts with a ":" but there is also like a hundred unrelated things (such as function signature and link to unrelated functions such as :write) in the document. I am sure you and other experienced people know how to do this but I do not know even after reading `:help grep`.
Good UX needs people that understand that most people are not as knowledgeable as the one regularly contributing to the application. Good UX cannot assume that it's always the user's fault if he's lost.  Even though as Neovim is for devs we can still assume informed users doing their research of course but there's limits and good UX can help.

> Also, there's tab-complete for commands.

My point is if there's one common prefix such as :TSInspectTree and :TSEditQuery I can use tab complete like :TS<tab> to find commands. I do not know if I can use tab-complete when I do not know what to search for because I have no prefix

**Comment by clason** [comment]
And my point is that it's precisely for UX reasons that the naming is what it is: you `:Inspect*` anything you want to inspect, and `:Edit*` anything you want to edit. We _don't_ want to make treesitter into a separate subsystem with a common prefix -- same reason we don't have a bunch of `:LSPfoo` commands. (We _do_ have this on the "API" level, which users _are_ expected to interact with. Commands are just some slight convenience sugar on top of it, for some things that don't rely heavily on arguments.)

The issue here is that you came in with a preconceived expectation from a separate plugin; but Neovim itself has a different UX paradigm.

**Comment by ilan-schemoul** [comment]
Ok fair take 👌 thanks for the explanations I like understanding reasoning behind decisions
