### ISSUE TITLE
Default SwapExists autocmd can prevent the buffer's filetype from being set

### ISSUE THREAD

**Issue by AThePeanut4** [neovim/neovim#28110]
### Problem

It's a bit difficult to explain, see the reproduction steps. Basically, the `vim.notify` call in the default `SwapExists` autocmd can "trip" the `did_filetype()` state, which prevents the `filetype` from being set for the buffer that triggered the `SwapExists` in the first place if that buffer was `:edit`ed from inside an autocmd.

### Steps to reproduce

1. Save the below config script as `minimal.lua`
2. Run `nvim --clean -u minimal.lua`
3. Hit Enter until the 'Press ENTER or type command to continue' messages go away
4. Run `:messages`
5. Open a second terminal window, without closing the first one
6. Repeat 2-4 in the second terminal window
7. Observe that "FileType 1" was printed in the first terminal, but not in the second terminal. Also observe that the file in the second terminal doesn't have working syntax highlighting, and that `filetype` is not set.

```lua
-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs {
  ["nvim-notify"] = "https://github.com/rcarriga/nvim-notify",
} do
  local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { "git", "clone", "--depth=1", url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

local notify = require("notify")
notify.setup()
vim.notify = notify

-- this does fix the issue, but not ideal imo
-- vim.notify = function(...)
--   local args = { ... }
--   vim.schedule(function() notify(unpack(args)) end)
-- end

vim.api.nvim_create_autocmd("BufReadPre", {
  callback = function(opts)
    print("BufReadPre", opts.buf)
  end,
})
vim.api.nvim_create_autocmd("FileType", {
  callback = function(opts)
    print("FileType", opts.buf)
  end,
})
vim.api.nvim_create_autocmd("BufReadPost", {
  callback = function(opts)
    print("BufReadPost", opts.buf)
  end,
})

vim.api.nvim_create_autocmd("VimEnter", {
  callback = function()
    vim.cmd.edit("minimal.lua")
  end,
  nested = true,
})

```

### Expected behavior

Both terminals should have `filetype` set successfully - "FileType 1" should be printed in both. 

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2743+gf29c41d66

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 14.4.1

### Terminal name/version

Alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

homebrew, with --HEAD

**Comment by AThePeanut4** [comment]
3 possible solutions:
1. When replacing `vim.notify`, wrap the replacement function in `vim.schedule`. This defers actually displaying the notification until after the buffer has completely loaded in and the `filetype` has already been set.
2. Wrap the `vim.notify` call inside the default `SwapExists` autocmd in `vim.schedule`. This is the same idea as above, just one step higher up the call stack, so it won't affect every place `vim.notify` is used.
3. Make the `did_filetype()` state entirely buffer-specific. The root cause of this bug is that the `did_filetype()` is shared between the original buffer and the notification buffer created by `nvim-notify`, which prevents [runtime/filetype.lua](https://github.com/neovim/neovim/blob/38e38d1b401e38459842f0e4da431e3dd6c2e527/runtime/filetype.lua) from setting the `filetype` on both buffers while inside one "root" autocmd.

The first solution is of course the simplest, and doesn't need any actual changes to neovim. I don't think it's ideal though, because it means that all calls to `vim.notify` will have to go through `vim.schedule`. The second solution fixes that issue, and is a very straightforward change. The third solution is the most general, but is presumably the most complex to actually implement. The docs for `did_filetype()` state "... thus this really checks if the FileType event has been triggered for the current buffer.", so a buffer-local state would make a lot of sense.

**Comment by zeertzjq** [comment]
Repro in Vim script:
```vim
let b1 = bufnr()
new
autocmd SwapExists * let v:swapchoice = 'e' | call setbufvar(b1, '&filetype', 'text')
autocmd VimEnter * ++nested edit <script>
```
I'm not sure why this only happens when `:edit` is run inside `VimEnter`.

**Comment by zeertzjq** [comment]
> Repro in Vim script:
> 
> ```viml
> let b1 = bufnr()
> new
> autocmd SwapExists * let v:swapchoice = 'e' | call setbufvar(b1, '&filetype', 'text')
> autocmd VimEnter * ++nested edit <script>
> ```
> 
> I'm not sure why this only happens when `:edit` is run inside `VimEnter`.

Oh, it actually happens with any nested autocommand.

**Comment by AThePeanut4** [comment]
Thank you for the speedy fix @zeertzjq :heart:
