### ISSUE TITLE
Poor performance typing in .vim file with treesitter highlights

### ISSUE THREAD

**Issue by ColinKennedy** [neovim/neovim#28113]
### Problem

https://github.com/neovim/neovim/assets/10103049/b2dea58a-33e1-413b-abb2-a5e04b7e3fbd

While typing with treesitter highlights enabled in a ~3K vim file, typing speed is slow. In the video above I show typing with the reproduction file, which is slow. Then with `nvim -u NONE`, which is a normal speed.

Note: Not shown in the video but if you do `touch foo.vim; nvim -u foo.vim` then it is normal speed

### Steps to reproduce

<details>
<summary>reproduction.lua</summary>

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"

if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end

vim.opt.runtimepath:prepend(lazypath)

local plugins = {
    {
        -- Useful from the documentation:
        --
        --     A parser can also be loaded manually using a full path: >
        --         vim.treesitter.require_language("python", "/path/to/python.so")
        --
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        config = function()
            require("nvim-treesitter.configs").setup {
                ensure_installed = { "vim" },
                highlight = { enable = true },
            }
        end,
        version = "0.*",
    },
}

require("lazy").setup(plugins, { root = root .. "/plugins" })

vim.cmd("hi! link CurSearch Search")
```
</details>

Using https://github.com/vim/vim/blob/620e85265ce04654053c64f8058914ecafe4eb38/src/testdir/test_winfixbuf.vim ...

1. `nvim -u reproduction.lua test_winfixbuf.vim`
2. Type a lot of `aaaaaa`s

### Expected behavior

Fast responsiveness while typing

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2515+g2cadccabf-dirty

### Vim (not Nvim) behaves the same?

No, even with `:set hlsearch` enabled - VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Mar 26 2024 23:41:57) Included patches: 1-211

### Operating system/version

CentOS Linux 7 (Core)

### Terminal name/version

gnome-terminal - # GNOME Terminal 3.28.2 using VTE 0.52.4 +GNUTLS

### $TERM environment variable

xterm-256color

### Installation

Compiled from source

**Comment by clason** [comment]
Cannot reproduce. Please test with `nvim --clean` (and without nvim-treesitter; the `vim` parser is bundled so `vim.treesitter.start()` is all you need).

**Comment by ColinKennedy** [comment]
I can't seem to reproduce it anymore either. I wonder what changed. Closing.
