### ISSUE TITLE
Please add Linux arm64 packages (native and AppImage)

### ISSUE THREAD

**Issue by btegs** [neovim/neovim#28116]
### Problem

There are currently no native executables or AppImage packages for Arm. This could be arm64, aarch64, arm64v8.

Debian unstable (sid) does have an arm64 package at https://packages.debian.org/sid/arm64/neovim/download that can probably be used as a reference for building and there is another GitHub at https://github.com/matsuu/neovim-aarch64-appimage which builds an AppImage, but it would be nice to have this upstream.

### Expected behavior

Arm downloads for native and AppImage

**Comment by dundargoc** [comment]
Duplicate of https://github.com/neovim/neovim/issues/15143
