### ISSUE TITLE
Auto commands with Lua callbacks that return Lua tables are removed after they are executed

### ISSUE THREAD

**Issue by Olical** [neovim/neovim#28127]
### Problem

Autocommands on the Nightly branch that return something other than `nil` from their Lua callbacks are deleted and not run again. This initially came up in this issue on my project https://github.com/Olical/nfnl/issues/36

### Steps to reproduce

With the following Lua in your plugin / configuration:

```lua
local function callback()
  print("EXECUTED")
  return {foo = true} -- A numerical value also causes the issue, maybe others too but I've only tried table and number so far.
end
vim.api.nvim_create_autocmd({"Filetype"}, {callback = callback})
```

You should see "EXECUTED" printed once then never again, even if you repeatedly `:e` different files.

### Expected behavior

"EXECUTED" should be printed multiple times on every Filetype autocommand execution. You can also see the autocmd under `:autocmd Filetype` initially then see it vanish after the first execution. This does not happen on stable, only on Nightly.

### Neovim version (nvim -v)

v0.10.0-dev-2755+ge1ff2c51c

### Vim (not Nvim) behaves the same?

No, this is only in Neovim nightly.

### Operating system/version

Linux and Windows users have seen this so far.

### Terminal name/version

Kitty 0.33.0

### $TERM environment variable

xterm-256color

### Installation

Manual .appimage download from GitHub, latest build from today

**Comment by clason** [comment]
That's documented though:
>                  • callback (function|string) optional: Lua function (or
>                   Vimscript function name, if string) called when the
>                   event(s) is triggered. Lua callback can return a truthy
>                   value (not `false` or `nil`) to delete the autocommand.

**Comment by Olical** [comment]
Ah okay then, I guess this was added recently. I'll go through my projects and look for any functions that return truthy values that I'm mapping to autocmds. I did look through `:help` trying to see if the default values for `once` or something changed but didn't think about changes to return value behaviour. I'll close this since it's not a bug, just a surprise for me that caused some bugs.

**Comment by clason** [comment]
`:h news`
