### ISSUE TITLE
icon highlight incorrect with --headless

### ISSUE THREAD

**Issue by williamhCode** [neovim/neovim#28120]
### Problem

Hello it's me working on an neovim ui again. I noticed that connecting with `--headless` makes popup menu icons display incorrect colors. Here you can see my completion icons are white when using `--headless` instead of blue.

https://github.com/neovim/neovim/assets/83525937/5b76a021-0ab4-440e-9af6-9c4bfd03e594

### Steps to reproduce

Run nvim --listen localhost:6666 --headless
Connect ui to port
Show popup menu with symbols

### Expected behavior

Colors should be correct

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2752+g35239e977

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 14.3.1

### Terminal name/version

tmux

### $TERM environment variable

xterm-256color

### Installation

tar file in releases

**Comment by zeertzjq** [comment]
Does it work if you `:set termguicolors`?

**Comment by zeertzjq** [comment]
And this may be a plugin problem.

**Comment by williamhCode** [comment]
No, doesn't work with `termguicolors`. It does seem like a plugin problem though, only my popupmenu has this issue and all my other icons are fine.

**Comment by zeertzjq** [comment]
But where do these icons come from?

**Comment by williamhCode** [comment]
I'm using cmp

**Comment by zeertzjq** [comment]
This is obviously a plugin problem.
