### ISSUE TITLE
vim.diff() does not have 'ignore_case' item in the {opts}.

### ISSUE THREAD

**Issue by rickhowe** [neovim/neovim#28124]
### Problem

vim.diff() does not have 'ignore_case' item in the {opts} though &diffopt has.

### Steps to reproduce

`:h vim.diff`
does not mention about 'ignore_case'.

### Expected behavior

vim.diff() supports 'ignore_case' item in the {opts} as &diffopt does.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2755+ge1ff2c51c

### Vim (not Nvim) behaves the same?

No.

### Operating system/version

n/a

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

n/a

**Comment by clason** [comment]
`xdiff` (which `vim.diff` exposes) does not have this option.

**Comment by lewis6991** [comment]
It simply not existing in diffopt isn't enough to justify adding it to vim.diff without a clear use case.
