### ISSUE TITLE
treesitter: For folding, iter_captures does not respect quantifiers like iter_matches

### ISSUE THREAD

**Issue by ayroblu** [neovim/neovim#28132]
### Problem

Building on: https://github.com/neovim/neovim/pull/24738
I thought I would be able to use quantifiers for folds. However, this is not working for me

Specifically referring to code here: 
https://github.com/neovim/neovim/blob/01691c5447d/runtime/lua/vim/treesitter/_fold.lua#L152

I tried stepping through the nodes and it has each import separately

### Steps to reproduce

I set `set foldexpr="v:lua.vim.treesitter.foldexpr()"` and 

```lua
local folds_query = [[
  ((import_statement)+ @fold)
]]

require("vim.treesitter.query").set("typescript", "folds", folds_query)
```

### Expected behavior

I made this work in nvim-treesitter though it is apparently deprecated:
https://github.com/nvim-treesitter/nvim-treesitter/pull/6382

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2754+g12240600f-Homebrew

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 14.3

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by clason** [comment]
It's not meant to work yet. The folding module is yet to adapt to the changes.

**Comment by lewis6991** [comment]
Let's keep this open to track as a specific use case.

**Comment by ribru17** [comment]
@ayroblu This is fixed with https://github.com/neovim/neovim/pull/28430
