### ISSUE TITLE
Idea: default to automatically start insert mode when enter a :terminal

### ISSUE THREAD

**Issue by NLKNguyen** [neovim/neovim#2815]
I read a couple of discussions and not sure if this decision is already made, but it seems like a good idea to automatically start insert mode when entering a :terminal because it will be more natural just like when you switch to an outside terminal.

**Comment by Pyrohh** [comment]
What would happen if there were 5 terminal windows in a horizontal split and I wanted to switch between the one on the far left to the one in the middle? Wouldn't that mean I'd have to do
```
<C-\><C-n>
<C-w>l
<C-\><C-n>
<C-w>l
```
instead of what's currently done:
```
<C-\><C-n>
<C-w>l
<C-w>l
```
I know you can do `2<C-w>l` in the first example, but I still think it would be annoying to make nvim so unforgiving if users forgot to prepend a count.
Besides that, I think this would make `:terminal`s even more different from regular buffers (there's already a few).

**Comment by NLKNguyen** [comment]
Yeah, I agree.

My use case for this idea is that I want to run the last shell command and go back to current file quickly, like this

    <C-w>l     " to the terminal, supposedly enter insert mode automatically
    <C-p><enter> " run previous command
    <C-w>r    " back to the file. I mapped it to <C-\><C-n><C-w>r

The key point is simply that holding Ctrl throughout the steps is smoother. 

Is there a good way to  run the last command while still in the Normal mode?

**Comment by Pyrohh** [comment]
> Is there a good way to run the last command while still in the Normal mode?

I like using Vim, but unfortunately that doesn't mean I'm very good with it :)
Perhaps you should ask on our gitter chat.

**Comment by splinterofchaos** [comment]
To enter insert mode every time you enter a terminal buffer, put this in your vimrc:
```vim
autocmd BufEnter term://* startinsert
```
This little script shows how to send lines to a terminal buffer as commands and remember the last command:
```vim
let s:last_cmd = ''
let s:term = termopen([&shell])

function s:send(cmd)
  let s:last_cmd = a:cmd . "\n"
  call jobsend(s:term, s:last_cmd)
endfunction

function s:repeat()
  call jobsend(s:term, s:last_cmd)
endfunction

command -nargs=+ Send call s:send(<q-args>)
command -nargs=0 Repeat call s:repeat()
```
nvim itself doesn't keep any tabs on what you send to the buffer and can't tell the difference between that and program output, so such a thing can't be a built-in feature right now.

**Comment by NLKNguyen** [comment]
Sweet!!

The script makes the terminal open every time  I open nvim, which is kinda strange. However, the first autocmd is awesome; that's all I need. It should as well be in FAQ. Thank you Thank you :+1:

**Comment by splinterofchaos** [comment]
The idea is just to start the terminal with `termopen()` to give you a channel. This shouldn't be in your vimrc.

**Comment by cup** [comment]
https://github.com/neovim/neovim/issues/8816
