### ISSUE TITLE
Regression: E474 on certain lhs characters in abbreviations

### ISSUE THREAD

**Issue by adigitoleo** [neovim/neovim#28150]
### Problem

On 0.9.5 (latest stable), the error E474: Invalid argument is thrown for certain abbreviation definitions which were previously supported.

### Steps to reproduce

To reproduce, use `nvim -u NORC` and type:
- `:abbrev :foo bar`
- `:abbrev !foo bar`
- `:abbrev ;foo bar`
- `:abbrev %foo bar`

Disallowed characters seem to be: ```:;!%`@#$%^&*()-=+[]\/<>,.?```. They need not appear at the start of the `{lhs}`. Not sure if this is intended, but the error is not raised from e.g. `:map`, only from abbreviation commands as far as I can tell (e.g. `:iabbrev`). Further requirements are that the lhs must contain **at least 2** characters not in the offending set. `:iabbrev #i #include` works, but not `:iabbrev #ii #include`.

### Expected behavior

Abbreviations with arbitrary `{lhs}` excluding `|` work as before.

This vim issue from 2018 looks similar: https://github.com/vim/vim/issues/2810, however it isn't the same. I can't do `:iabbrev @ii @include` even with `@` being present in my `&iskeyword`.

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

yes, 9.1 through patch 250

### Operating system/version

linux x86_64 glibc

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

xbps (Void system package manager)

**Comment by adigitoleo** [comment]
Notably, `:iabbrev _foo bar` always works, this is the only non-alphanumeric character that is not affected it seems.

**Comment by zeertzjq** [comment]
How is this a regression? The behavior is the same in v0.4.0.

**Comment by zeertzjq** [comment]
> I can't do `:iabbrev @ii @include` even with `@` being present in my `&iskeyword`.

This works if you `:set iskeyword+=@-@`. This is because `@` has a special meaning, as mentioned in `:h 'isfname'` which is referenced by `:h 'iskeyword'`:
```
	If the character is '@', all characters where isalpha() returns TRUE
	are included.  Normally these are the characters a to z and A to Z,
	plus accented characters.  To include '@' itself use "@-@".  Examples:
		"@,^a-z"	All alphabetic characters, excluding lower
				case ASCII letters.
		"a-z,A-Z,@-@"	All letters plus the '@' character.
```

And the behavior matches `:h abbreviations`:
```
There are three types of abbreviations:

full-id	  The "full-id" type consists entirely of keyword characters (letters
	  and characters from 'iskeyword' option).  This is the most common
	  abbreviation.

	  Examples: "foo", "g3", "-1"

end-id	  The "end-id" type ends in a keyword character, but all the other
	  characters are not keyword characters.

	  Examples: "#i", "..f", "$/7"

non-id	  The "non-id" type ends in a non-keyword character, the other
	  characters may be of any type, excluding space and tab.

	  Examples: "def#", "4/7$"
```

So this is working as intended.

**Comment by adigitoleo** [comment]
> How is this a regression? The behavior is the same in v0.4.0.

Hmm, perhaps. I've had an `:iabbrev :foo bar` type of thing in my config for a while and this only came up recently (last couple of weeks). I don't mind, I just changed them to `:iabbrev _foo bar`, but that made me think it was a regression. It's possible this was caused by some more complex interaction.
