### ISSUE TITLE
tutor tests become unresponsive on line-number mismatch

### ISSUE THREAD

**Issue by goyalyashpal** [neovim/neovim#28164]
### Problem
The line-gutter's test-decorators in `:Tutor` become unresponsive after their line numbers change i.e. due to removal/addition of lines before them.

while this is perfectly understandable: _of course, the test is line number specific"_
but the issue lies in the fact that the tutorial _demands_ lines to be added/deleted

i.e. there's a contradiction in how the tutorial interacts with users, vs how the tests assume it would stay.

### Minimal Steps to reproduce
<sub>I couldn't get the clipboard to work despite `scoop install win32yank` and restart terminal. So, some steps might feel convoluted.</sub>

**Normal conditions:**

0. `nvim -c ':Tutor'` or equivalently `nvim` > `:Tutor`
1. correct the L`333` 
(say by, `332gg` > paste the following correct line > `jdd`)
    - :-) see test pass responsively

**Trigger and buggy behaviour:**

2. `308gg` `dd` `332gg` or better yet, `kdd` (both are equivalent for our purpose)
3. `0i` `f` `<ESC>` (make any change to try to make test fail): 
    - :-( see that the `✓` stays there unresponsively

**Confirmation of the diagnosis/hypothesized cause:**

4. `ki` `<RET>` `<ESC>` to insert a blank line above (i.e. bring the test line number back to '333')
5. `j0a` `<SPC>` `<ESC>` (force refresh the test):
    - :-) see the test fail responsively
6. `0dw` (neutralise edits from step 5, 7):
    - :-) see the test pass responsively

```
Fix the errors on this line and replace them with undo.
```

### Expected behavior

the test indicator on line-gutter `✗✓` stays responsive during at least the normal flow of test...

[image](https://github.com/neovim/neovim/assets/19423063/ea2d586a-0a88-4185-ad19-88555bc48373)

### Solutions?

I am not sure what an ideal, MVC solution can be. Some thoughts come to mind:

**update:** it seems that the best and minimum viable solution can be this 2nd one:

2. provide a quick shortcut command which restarts the test afresh from the line the user is at at the time of invocation
    * would require: a reminder line in tutorial text (after a deleted line) reminding user to start the test afresh
    - no downsides as far as i can see
    - full flexibility
    - not much is required to change, all the functionality required to make it work already exists
    - i.e. true to `MVC`, simple, cost effective and elegant

[fold-marker]: https://neovim.io/doc/user/fold.html#fold-marker "fold-marker"

<details open><summary>alternate solutions considered:</summary>
<p>

1. _[hash-map + array][only-upfront-cost]_ define "named chunk ranges" somehow, & refer to line numbers relative to chunk's start in tests
   <sub>(dictionaries can solve everything eventually 🤣)</sub>
    + <sub>(inspired from `powershell` config)</sub>
    + neo/vim already has [marker-based folding range][fold-marker] which can fit this purpose very well
      nevertheless, it seems non-trivial to use that in this way
    + but once done; the rest will be easy ride
    + full flexibility of attempting tests in any order
	+ no constraints on what is done to lines outside of the test chunk: i.e. full freedom to experiment _and_ edit
        + no need to make sweeping changes to fix the line locations in tests on any line insertions in the tutor

^

0. _[brute-force][continous-cost]_ hard-coding the expected line numbers after the line deletions through test
    - _requires alll the tests_ and _nothing except the tests_ to be done _sequentially_
    - i.e. would also require to save the tutorial buffer, and resume from there the next time
    - overall, toooo much restrictive

</p>
</details> 

Sample from neo/vim's marker based folding range with `{{{<N> ... }}}<N>`: 

```markdown
<!-- Chapter 1. Navigation {{{3 -->


<!-- Chapter 2. Motions {{{3 -->
```

Sample from powershell's named chunks with `#region <name> ... #endregion` :

```powershell
#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
If (Test-Path "...\mambaforge\Scripts\conda.exe") {
    (& "...\mambaforge\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | ?{$_} | Invoke-Expression
}
#endregion
```

<details>
<summary><h2>Environment</h2></summary>
<p>

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1710088188     system vimrc file: "$VIM\sysinit.vim"   fall-back for $VIM: "/mingw64/share/nvim"  Run :checkhealth for more info

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

windows 10.0.19045 N/A Build 19045

### Terminal name/version

mintty 3.7.1 (x86_64-pc-msys)

### $TERM environment variable

xterm

### Installation

in msys2 `mingw-w64-x86_64-neovim` pkg via command: `pacboy -S neovim:x`

</p>
</details>

**Comment by goyalyashpal** [comment]
also just noticed that absolute line number is not shown at current line. (i.e. it is saying `0` instead of the actual number)

i turned it on via: `:setglobal relativenumber`

**Comment by goyalyashpal** [comment]
it should not have been the case though... i am guessing that something is going on with me making edits. 
probably line ending problem due to it being on msys2 (linux like environment) but input via windows? idk.

https://github.com/neovim/neovim/blob/1b55ed58ecaba96f91a21685b7019362320ea156/runtime/tutor/en/vim-01-beginner.tutor.json#L21
https://github.com/neovim/neovim/blob/1b55ed58ecaba96f91a21685b7019362320ea156/runtime/tutor/en/vim-01-beginner.tutor.json#L26-L31

https://github.com/neovim/neovim/blob/1b55ed58ecaba96f91a21685b7019362320ea156/runtime/tutor/en/vim-01-beginner.tutor#L333
https://github.com/neovim/neovim/blob/1b55ed58ecaba96f91a21685b7019362320ea156/runtime/tutor/en/vim-01-beginner.tutor#L398-L399
https://github.com/neovim/neovim/blob/1b55ed58ecaba96f91a21685b7019362320ea156/runtime/tutor/en/vim-01-beginner.tutor#L419-L420

----
there's nothing special in tests which are behaving expectedly either:

https://github.com/neovim/neovim/blob/1b55ed58ecaba96f91a21685b7019362320ea156/runtime/tutor/en/vim-01-beginner.tutor.json#L9-L11

https://github.com/neovim/neovim/blob/1b55ed58ecaba96f91a21685b7019362320ea156/runtime/tutor/en/vim-01-beginner.tutor#L216
https://github.com/neovim/neovim/blob/1b55ed58ecaba96f91a21685b7019362320ea156/runtime/tutor/en/vim-01-beginner.tutor#L232

**Comment by goyalyashpal** [comment]
hi @ justinmk 

is it possible to reload/revert the tutor?

following this: [edit-a-file], i tried doing `:e!` inside the `:Tutor`, and it showed me blank.
i am positive that reloading tutor is the sure-fire and minimum way to solve this issue.

do you have any other thoughts?

[edit-a-file]: https://neovim.io/doc/user/editing.html#edit-a-file
[restore]: https://neovim.io/doc/user/tips.html#restore-position

**Comment by justinmk** [comment]
Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by goyalyashpal** [comment]
hi!

> * Check `:version` to confirm that you are using the latest version.

yeah, it is the latest version. 😃 
as for the development one, it seems to be not available in `scoop`. i will write manifest file for it (based on neovim stable's manifest) and then only can try it

but i haven't ever done that before. so, it may take a while.

```
:version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "/mingw64/share/nvim"

Run :checkhealth for more info

```

**Comment by justinmk** [comment]
> , it seems to be not available in `scoop`.

don't need scoop, download it from https://github.com/neovim/neovim/releases/tag/nightly

**Comment by goyalyashpal** [comment]
_self hiding as resolved (probably)_

----

i changed the following things:

```jq
# file: changed_elements.jq
{
    bin,
    shortcuts, # Remove as the nightly doesn't seem to have 'bin\nvim-qt.exe'
    urls: {
        architecture_url:.architecture."64bit".url,
        checkver_url:.checkver.url,
        autoupdate_url:.autoupdate.architecture."64bit".url
    }
}
```



[create-manifest]: https://github.com/ScoopInstaller/Scoop/wiki/Creating-an-app-manifest "creating-manifest"
[manifest-ref]: https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests "App Manifests reference"

and ran the following commands: (only `checkurls.ps1` doesn't have `-up`/`-Update` option
Indicatively: `powershell -F .../check{urls,ver,hashes}.ps1 neovim.dev . [-Update]`

```console
$ declare spf=".../scoop/apps/scoop/current/bin"
$ echo -n check{urls,ver,hashes}.ps1 | xargs -ti -d' ' powershell -F $spf/{} neovim-dev .
[U]RLs
 | [O]kay
 |  | [F]ailed
 |  |  |
[1][1][0] neovim-dev
neovim-dev: 0.10.0-dev-2801
nvim-win64.zip (16.6 MB) [========] 100%
neovim-dev: OK

$ scoop install neovim-dev.json
Creating shim for 'nvim-dev'.
'neovim-dev' (0.10.0-dev-2801) was installed successfully!
'neovim-dev' suggests installing 'extras/vcredist2022'.

```

----
<details><summary>Details</summary>
<p>


```console
$ cat neovim-dev.json | jq -f changed_elements.jq
{
  "bin": [
    [
      "bin\\nvim.exe",
      "nvim-dev"
    ]
  ],
  "shortcuts": null,
  "urls": {
    "architecture_url": "https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip",
    "checkver_url": "https://api.github.com/repos/neovim/neovim/releases/tags/nightly",
    "autoupdate_url": "https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip"
  }
}

```

```console
$ scoop cat neovim | diff - neovim-dev.json
```

```diff
2c2
<     "version": "0.9.5",
---
>     "version": "0.10.0-dev-2801",
14,15c14,15
<             "url": "https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-win64.zip",
<             "hash": "de6dc1f0edb45f5f225ee24ce80a4fcbc3a337932037e98ae143975fca2556bf"
---
>             "url": "https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip",
>             "hash": "ac4fe62cfd1c1763929c66bc822f4b94b97da36c18862f41e7bd90569f2638d3"
20,27c20
<         "bin\\nvim.exe",
<         "bin\\nvim-qt.exe"
<     ],
<     "shortcuts": [
<         [
<             "bin\\nvim-qt.exe",
<             "Neovim"
<         ]
---
>         [ "bin\\nvim.exe", "nvim-dev" ]
30c23
<         "url": "https://api.github.com/repositories/16408992/releases/latest",
---
>         "url": "https://api.github.com/repos/neovim/neovim/releases/tags/nightly",
38c31
<                 "url": "https://github.com/neovim/neovim/releases/download/v$version/nvim-win64.zip"
---
>                 "url": "https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip"

```

</p>
</details>

**Comment by goyalyashpal** [comment]
> don't need scoop

sure it doesn't; but scoop makes things easy to manage. i have already faced enough headache with manually managing installs of various things over last couple of yrs.

```
:version
NVIM v0.10.0-dev-2801+g75b80516d
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188
Run ":verbose version" for more info

```

error is reproduced on latest nightly

**Comment by justinmk** [comment]
This is way too much complication for what appears to be a small problem. Either send a PR that fixes it or it's wontfix.

**Comment by goyalyashpal** [comment]
the question is simple, can tutor be reloaded or not.
and u still didn't address it 😞

**Comment by clason** [comment]
No.

**Comment by goyalyashpal** [comment]
okay thanks @clason
