### ISSUE TITLE
Msgpack API: vim_set_var returns null every time

### ISSUE THREAD

**Issue by fdinoff** [neovim/neovim#2816]
I have been playing around with the Msgpack API. According the the documentation comment for [`vim_set_var`](https://github.com/neovim/neovim/blob/e888c479f3d34a1948c63495328b4184ff2ab874/src/nvim/api/vim.c#L294) should return the old value if there was a value set. However this doesn't appear to happen.

The below is an example where the variable 'a' is set to 1. Checks to make sure that the variable was set to 1. Then reassigns it to 2.  (The code uses the session directly to send requests since I wasn't sure how to demonstrate the last line through the python api)

```
import neovim

vim = neovim.attach('child', argv=['nvim', '--embed'])
print(vim._session.request('vim_set_var', 'a', 1))     # vim.vars['a'] = 1
print(vim._session.request('vim_get_var', 'a'))        # print(vim.vars['a'])
 # Don't know how to do this through the python api
print(vim._session.request('vim_set_var', 'a', 2))
```

Output from running
```
None
1
None
```

The last print statement prints None instead of the old value of 1 which seems to go against what the documentation says.

---

version info
NVIM 0.0.0-alpha+201506091331 (compiled Jun  9 2015 23:06:45)
Commit: 6270d431aaeed71e7a8782411f36409ab8e0ee35

**Comment by justinmk** [comment]
`vim_set_var` is marked with `FUNC_ATTR_DEFERRED` so I'm guessing you would need to spin the event loop to get the result.

**Comment by fdinoff** [comment]
This was actually discovered when I was playing around with the [java client](https://github.com/fdinoff/neovim-java-client) I wrote to communicate with neovim.

```java
try (Neovim neovim = Neovim.connectTo(new EmbeddedNeovim("nvim", "-u", "NONE"))) {
    neovim.setVar(new TypeReference<Integer>() {}, "a", 1).thenAccept(System.out::println).join();
    neovim.getVar(new TypeReference<Integer>() {}, "a").thenAccept(System.out::println).join();
    neovim.setVar(new TypeReference<Integer>() {}, "a", 2).thenAccept(System.out::println).join();
}
```

output
```java
null
1
null
```

I don't know if the python code is equivalent (I think it is), but I know that calling join in the java code waits for the result before moving onto the next line. Printing out the msgpack arrays that were sent and received look something like this

```
sent:     [0,0,vim_set_var,[a,1]]
received: [1,0,null,null]
sent:     [0,1,vim_get_var,[a]]
received: [1,1,null,1]
sent:     [0,2,vim_set_var,[a,2]]
received: [1,2,null,null]
```

As you can see the response for the second `vim_set_var` contains null as the response where it should have contained 1. After receiving the response from the request there is nothing more to wait on.

**Comment by justinmk** [comment]
Hmm.  `functional/api/vim_spec.lua` exercise `vim_set_var`, but then use `vim_get_var` to test the result. I would guess that this feature is not tested and should be removed. None of the other `set_foo` API functions (vim_set_current_line, vim_set_option, vim_set_current_buffer, ...) return anything--nor would it  make sense to do so, if they are supposed to be non-blocking.

Do you actually need this feature or just reporting a bug? :)

**Comment by justinmk** [comment]
In fact, **all** of the tests which exercise `set_var`, do not check its return value, but instead use `get_var`:

```
"test/functional/api/vim_spec.lua"
"test/functional/api/buffer_spec.lua"
"test/functional/api/tabpage_spec.lua"
"test/functional/api/window_spec.lua"
"test/functional/job/job_spec.lua"
"test/functional/shell/viml_system_spec.lua"
```

@tarruda Is there any need for set_var to return a value?

**Comment by fdinoff** [comment]
I would prefer that is exists. It would make implementing the [Map#put](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#put-K-V-) method easier in java.

**Comment by justinmk** [comment]
Try deleting `FUNC_ATTR_DEFERRED` from `src/nvim/api/vim.c:vim_set_var`. Does it change the results?

**Comment by fdinoff** [comment]
No change.

**Comment by justinmk** [comment]
Oh, I see the bug. Will send a patch

**Comment by justinmk** [comment]
PR here: https://github.com/neovim/neovim/pull/2899
