### ISSUE TITLE
Certain flag emoji don't render correctly

### ISSUE THREAD

**Issue by gaykitty** [neovim/neovim#28174]
### Problem

Specifically the trans flag, pirate flag, and pride flag emoji don't render correctly. These emoji and encoded differently than the other flag emoji. For example the trans flag emoji is `U+1F3F3 U+FE0F U+200D U+26A7 U+FE0F`.

### Steps to reproduce

Open a file with these emoji in it.

### Expected behavior

The emoji render correctly

### Neovim version (nvim -v)

v0.9.4

### Vim (not Nvim) behaves the same?

yes, vim 9.1

### Operating system/version

NixOS 23.11

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

Nix package manager

**Comment by clason** [comment]
Duplicate #7151

**Comment by bfredl** [comment]
It is not _exactly_ the same issue but the fix is going to be the same anyway (modern utf8 library) so we don't need a separate issue.

**Comment by clason** [comment]
(And to be clear, we absolutely want to have support for these flags, same as any other valid utf8 glyph.)
