### ISSUE TITLE
tutor: raw text not shown while editing element

### ISSUE THREAD

**Issue by goyalyashpal** [neovim/neovim#28172]
### Problem

wherever some data from syntax is hidden in the rendered output, it becomes hard to edit that. it's like editing with a blindfold.

* `*` asterisks disappear while trying to type them - it becomes impossible to know where to end them or where there extent lies
* heading labels, the label is hidden: `# title {label}` 
* links, target is hidden: `[label](target)`

https://github.com/neovim/neovim/blob/e016f5bee6293d126fde9e8d75a3f02f882e2c81/runtime/tutor/tutor.tutor#L82-L83
https://github.com/neovim/neovim/blob/e016f5bee6293d126fde9e8d75a3f02f882e2c81/runtime/tutor/tutor.tutor#L108-L109

![image](https://github.com/neovim/neovim/assets/19423063/61f91744-f19f-48ad-b3a3-9038f1a7570b)

### Steps to reproduce

1. `nvim`
2. `:e <nvim-dir>/share/nvim/runtime/tutor/tutor.tutor`
3. `:let g:tutor_debug = 1` (as instructed at `22gg`)
4. `82gg` or `108gg`
5. try to add a heading label or link target:
    - observe that the label or target becomes hidden; and it's very hard to edit them

### Expected behavior

while editing an element, it should be fully exposed in its raw form.
many markdown editors do this like `typora`

_edit: this showed up by entering unneeded dangling asterisks_
~infact, i don't know how, but nvim inside the `:Tutor`, i did actually saw the underlying markup when editing an element accidently. but i can't figure it out how did i do that.~

### Neovim version (nvim -v)

NVIM v0.9.5 

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

windows 10.0.19045 N/A Build 19045

### Terminal name/version

mintty 3.7.1 (x86_64-pc-msys)

### $TERM environment variable

xterm

### Installation

in msys2 mingw-w64-x86_64-neovim pkg via command: `pacboy -S neovim:x`

**Comment by goyalyashpal** [comment]
jump to 0:17

<br/><br/>

https://github.com/neovim/neovim/assets/19423063/c35d4bf4-058b-4024-97cd-bb59e618a724

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by goyalyashpal** [comment]
hi!

> * Check `:version` to confirm that you are using the latest version.

yeah, it is the latest version. 😃 
as for the development one, it seems to be not available in `scoop`. i will write manifest file for it (based on neovim stable's manifest) and then only can try it

but i haven't ever done that before. so, it may take a while.

```
:version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "/mingw64/share/nvim"

Run :checkhealth for more info

```

**Comment by justinmk** [comment]
> yeah, it is the latest version. 😃

by "latest" I mean the 0.10 dev version which I specifically mentioned. I linked to prebuilt binaries that you can download, you don't need scoop.

**Comment by skepticspriggan** [comment]
The conceallevel should be 0 according to the [filetype plugin](https://github.com/neovim/neovim/blob/master/runtime/ftplugin/tutor.vim#L11) after enabling debug mode by following the instructions in the [tutor.tutor](https://github.com/neovim/neovim/blob/master/runtime/tutor/tutor.tutor#L22) file. However, `:set conceallevel?` shows the conceallevel actually remains at 2.

**Comment by listout** [comment]
I'm guessing that the logic in the [lines](https://github.com/neovim/neovim/blob/2b9d8dc87e84ea9c03eb8852af8fd9fe00a6033a/runtime/ftplugin/tutor.vim#L8C1-L17C1) are not sourced properly? As the values of `buftype` and `concealcursor` remains unaffected as well.

However if you do `:let g:tutor_debug = 1` before `:Tutor tutor` everything looks as intended.

**Comment by zeertzjq** [comment]
I don't think this is a bug. As mentioned in the tutor, this only works if you edit the tutor after setting `g:tutor_debug`:
```
First, you'll need to enable "debug" mode
~~~ cmd
    :let g:tutor_debug = 1
~~~
This will allow saving changes to the tutor files and will disable conceals, so
you can more easily check your changes.

After this, create a new .tutor file (we will be practicing on this very file, so you
don't need to do this now):
~~~ cmd
    :e new-tutorial.tutor
```
