### ISSUE TITLE
Consider adding diagnostics display toggle

### ISSUE THREAD

**Issue by aedificatio** [neovim/neovim#28186]
### Suggestion

Consider adding a toggle for displaying diagnostics. 
Based on how many diagnostics there are you might want to toggle between:
* no diagnostics
* only signcolumn
* virtual text and signcolumn

In my lspconfig I made a toggle that does just that! `<leader>dt` toggles between the various settings. The only 'clunky' bit is the function `refresh_diagnostics_screen()`. To trigger a screen refresh from the lsp without restarting the lsp, I trigger a `InsertLeave` event in the `refresh_diagnostics_screen()` function. Any suggestions how this could be done in a better way?

```lua
vim.g.diagnostics_state = 1

local function refresh_diagnostics_screen()
  -- to refresh lsp diagnostics on screen trigger an InsertLeave event
  -- else use: vim.cmd([[ LspRestart ]]) which is slower
  vim.api.nvim_buf_set_lines(0, 0, 0, false, { " " })
  vim.api.nvim_buf_set_lines(0, 0, 1, false, {})
  vim.diagnostic.show()
end

local function toggle_diagnostics()
  -- toggle vim.g.diagnostics_state between:
  -- 0 no diagnostics
  -- 1 only in signcolumn
  -- 2 virtualtext and signcolumn

  vim.g.diagnostics_state = (vim.g.diagnostics_state + 1) % 3

  if vim.g.diagnostics_state == 0 then
    vim.diagnostic.hide()
    print("Diagnostics: Hidden")
  elseif vim.g.diagnostics_state == 1 then
    vim.lsp.handlers["textDocument/publishDiagnostics"] =
      vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = false,
      })
    refresh_diagnostics_screen()
    print("Diagnostics: Signs only")
  elseif vim.g.diagnostics_state == 2 then
    vim.lsp.handlers["textDocument/publishDiagnostics"] =
      vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = {
	  source = "always",
	  prefix = "●",
	},
      })
    refresh_diagnostics_screen()
    print("Diagnostics: Virtual text and Signs")
  end
end

vim.keymap.set("n", "<leader>dt", toggle_diagnostics, { desc = "Diagnostics [T]oggle" })
```

### Steps to reproduce using "nvim -u minimal_init.lua"

see above

### Neovim version (nvim -v)

NVIM v0.9.5

### Language server name/version

lua-language-server

### Operating system/version

Debian 12

**Comment by justinmk** [comment]
sigh. we have `is_disabled()` (why tf is this not named `is_enabled()`?), and these:

```
disable({bufnr}, {namespace})                       *vim.diagnostic.disable()*
enable({bufnr}, {namespace})                         *vim.diagnostic.enable()*
```

those should be removed/deprecated and replaced with `enable + is_enabled`, just like `vim.lsp.inlay_hint`:

```
vim.lsp.inlay_hint.enable()
vim.lsp.inlay_hint.is_enabled()
```

**Comment by aedificatio** [comment]
Hi @justinmk , Thank you for your response.

My issue is not to `disable()` and `enable()` the diagnostics. 
I would like to keep the diagnostics enabled and only change the way it is displayed (hidden / signcolumn / virtual text). Completely stopping and (re-)starting the diagnostics with `vim.cmd([[ LspRestart ]])` takes longer to process.

In my code-snippet the `vim.diagnostic.config({})` table is modified with a keyboard toggle. This works just fine, except the display is only updated **_after_** an `InsertLeave` event. To make the toggle instant I also trigger an `InsertLeave` event in the `refresh_diagnostics_screen()` function, but this seems like the wrong approach.

Any guidance is highly appreciated.

**Comment by justinmk** [comment]
> Completely stopping and (re-)starting the diagnostics with `vim.cmd([[ LspRestart ]])` takes longer to process.

Just deal with it. We're not going to add zillions of options for every random preference.
