### ISSUE TITLE
fswatch-limitation not found with `:h fswatch-limitation`

### ISSUE THREAD

**Issue by OscarCreator** [neovim/neovim#28191]
### Problem

Problem with #27810. At this line:
https://github.com/neovim/neovim/pull/27810/files#diff-438cabcc877e34fbb948241c7e7e611579449d08085f5e38817a11450214a35bR533

The `*fswatch-limitation*` can't be on an empty line as then it wont be found with `:h`

### Steps to reproduce

build neovim after #27810 was merged

### Expected behavior

`:h fswatch-limitation` should take the user to lua.txt at the position of the tag

### Neovim version (nvim -v)

v0.10.0-dev-2726+g4147302f4-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 22.04.4

### Terminal name/version

Gnome Terminal 3.44.0

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by OscarCreator** [comment]
Closing as I can't replicate this again
