### ISSUE TITLE
Neovim used as git editor freezes when typing commit message

### ISSUE THREAD

**Issue by RomeuG** [neovim/neovim#28197]
### Problem

Hi!

I want to preamble this by saying that I did not find anything from the existing issues. I tried to search for specific keywords that rendered me nothing relevant.

I am having a issue where Neovim freezes when I use it as the editor of Git to insert a commit message.
Basically, I have this in my `.gitconfig`:

```gitconfig
[core]
editor = "nvim --clean"
```

When I want to commit something in a project, I just do `git commit` and it starts Neovim so I can type the message.
When I start typing, suddenly Neovim just freezes and I have to use `kill`.

I did a `git bisect` on the Neovim repository and it said that commit `89a9745a1a55dc9ffd0f8292735e45bae6c7b01e` introduced the problem.

### Steps to reproduce

1. Set Neovim as editor of Git, through `.gitconfig` or `export GIT_EDITOR="nvim --clean"`;
2. In any git repository that has staged changed, just type `git commit`;
3. Neovim will open, go to insert mode and start typing;
4. You will verify that Neovim freezes (hopefully?);

### Expected behavior

Neovim shouldn't freeze at all.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2197+g89a9745a1

### Vim (not Nvim) behaves the same?

no, vim 9.1

### Operating system/version

Linux 6.7.6-zen1-2-zen

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

git repository

**Comment by RomeuG** [comment]
> `git commit` will not just open Nvim in any git repository. At least there needs to be staged changes in the repository.

I apologize, I updated the original post accordingly.

**Comment by zeertzjq** [comment]
Although this is now fixed, can you provide what `:set textwidth?` in Nvim outputs when you run `git commit`?

**Comment by RomeuG** [comment]
> Although this is now fixed, can you provide what `:set textwidth?` in Nvim outputs when you run `git commit`?

Indeed I can: `textwidth=2147483647`

![image](https://github.com/neovim/neovim/assets/2325589/a5f7069e-a97e-4e45-ac7e-f9d889a0d8c2)

**Comment by zeertzjq** [comment]
Oh, I know what's the problem now.
