### ISSUE TITLE
`nvim_buf_call` restores window-local current directory incorrectly

### ISSUE THREAD

**Issue by AThePeanut4** [neovim/neovim#28213]
### Problem

If a tab-local cwd is set, and you run `nvim_buf_call` on a hidden buffer (i.e. making use of the "autocmd window"), the window-local cwd of the current window changes to be the same as the tab-local cwd.

### Steps to reproduce

1. `cd /tmp`
2. Save the below config script as `minimal.lua`
3. Run `mkdir -p a/b/c` to create a folder hierarchy to work with
4. Run `nvim --clean -u minimal.lua`
6. Observe the following output in `:messages`:
   ```
    [global] /tmp
    [global] /tmp/a
    [tabpage] /tmp/a/b
    [window] /tmp/a/b/c
    [window] /tmp/a/b
   ```

```lua
local temp_buf = vim.fn.bufadd("")

vim.api.nvim_create_autocmd("VimEnter", {
  callback = function()
    vim.cmd("verbose pwd")
    vim.cmd.cd("a")
    vim.cmd("verbose pwd")
    vim.cmd.tcd("b")
    vim.cmd("verbose pwd")
    vim.cmd.lcd("c")
    vim.cmd("verbose pwd")
    vim.api.nvim_buf_call(temp_buf, function() end)
    vim.cmd("verbose pwd")
  end,
  once = true,
})
```

### Expected behavior

The window-local cwd should be restored correctly after `nvim_buf_call` - the last line should be `[window] /tmp/a/b/c`.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2824+g9dd112dd48

### Vim (not Nvim) behaves the same?

Unsure how to test it, possibly?

### Operating system/version

Arch Linux

### Terminal name/version

Alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

AUR

**Comment by zeertzjq** [comment]
The window local CWD didn't actually change. If you switch to another window and then switch back, the CWD will be correct.
