### ISSUE TITLE
:checkhealth unclear output

### ISSUE THREAD

**Issue by mAmineChniti** [neovim/neovim#28225]
### Problem

:checkhealth has unclear output that can't be expanded by clicking + or space or leader or anything
![WindowsTerminal_i7M13NXpqJ](https://github.com/neovim/neovim/assets/124379229/bb0358ba-64db-44ab-bea5-de7b04ebae09)

### Steps to reproduce

:checkhealth

### Expected behavior

to have a clear :checkhealth output or one that expands to view the ouput when you click a specific key

### Neovim version (nvim -v)

v0.10.0-dev-2827+g067f51e3a

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Ubuntu 23.10 on Windows 10 x86_64 (WSL 2)

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

built from repo

**Comment by zeertzjq** [comment]
It works if you `:set foldopen=all`. However that's global option and cannot be added to the ftplugin.

**Comment by mAmineChniti** [comment]
@zeertzjq isn't there a way to do that by default like how can i put that in my config?

**Comment by zeertzjq** [comment]
`vim.o.foldopen = 'all'`

**Comment by mAmineChniti** [comment]
@zeertzjq thanks a lot

**Comment by justinmk** [comment]
> can't be expanded by clicking + or space or leader or anything

Is there a reason we shouldn't have left mouse click expand folds by default?
