### ISSUE TITLE
[Feature request] Make t motion match self closed tags

### ISSUE THREAD

**Issue by dmtrKovalenko** [neovim/neovim#28237]
### Problem

Right now `dat` will remove xml-like tags 

```xml
<tag attribute>
  <any-other tag>
</tag>
```

But not tags like this

```xml
<tag attribute />
```

While they are a standard and using in a lot of different languages and framework: React-jsx, html, svg, etc

### Expected behavior

Make `t` motion match the self-closed tags as well.

I will be happy to help and  open a pr for that

**Comment by clason** [comment]
This is provided by a bundled plugin we don't maintain; you should do this at https://github.com/chrisbra/matchit.

**Comment by dmtrKovalenko** [comment]
@clason thanks for quick update. But a quick follow-up: is it ok to do all the matching in vim script? Wouldn't it be faster to part this library to C world?

**Comment by clason** [comment]
No, we do not want to move further functionality into the C layer; this is detrimental to maintainability. At best, we could talk about porting `matchit` and `matchparen` to Lua, but that would mean _we_ would have to maintain it going forward, so that's a tough sell.
