### ISSUE TITLE
Commenting prioritizes treesitter injected languages' filetypes' `'commentstring'`, which may be incorrect

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#28233]
### Problem

Commenting prioritizes treesitter injected languages' filetypes' `'commentstring'` over other sources, which may be incorrect.
For example if one has [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) installed and editing a markdown file and `vim.treesitter.language.get_filetypes('markdown')` returns a table where the filetype `quarto` or `rmd` is after `markdown` then the `'commentstring'` used will be `quarto/rmd`'s `'commentstring'` which is `# %s` instead of `markdown`'s commentstring which is `<!--%s-->`.

### Steps to reproduce

```
nvim --clean foo.md
:lua vim.treesitter.language.add('markdown',{filetype='rmd'})
:lua vim.treesitter.start()
abar<esc>
gcc
```

### Expected behavior

The appropriate `'commentstring'` being used.

One solution for solving this problem would be: if any of a treesitter language's filetypes match the current filetype then use the buffer-local `'commentstring'`.

### Neovim version (nvim -v)

v0.10.0-dev-624de84

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

linux 6.8.4-arch1-1

### Terminal name/version

kitty 0.33.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by clason** [comment]
Not sure I want to add this extra complexity for such a snowflake situation. If two languages share a parser, they should share a syntax, and that includes the syntax for comments.

**Comment by clason** [comment]
Yes, registering the language for the filetype is the wrong thing here; if you want to "force" using a "wrong" parser, just run `vim.treesitter.start(0, 'markdown')` in a, e.g., `FileType rmd` autocommand.

**Comment by seblj** [comment]
Sorry for commenting on a closed issue, but I see they are still registered, so was just wondering if you would accept a PR in nvim-treesitter that removes at least quarto and rmd in nvim-treesitter? If so, main or master branch? Or both? @clason

**Comment by clason** [comment]
Sure, why not. (`master`; they're already gone on `main`).

**Comment by seblj** [comment]
What? When were they removed? I have been running the main branch for a while and I _swear_ I just checked right before commenting🙄 Oh well, then it is fixed for me😄
