### ISSUE TITLE
E5108: Error executing lua: ~/.config/nvim/init.lua:86: attempt to index field 'inlay_hint' (a nil value)

### ISSUE THREAD

**Issue by doupongzeng** [neovim/neovim#28231]
### Problem

```lua
local function test()
   if vim.lsp.inlay_hint.is_enabled(nil) then
    vim.lsp.inlay_hint.enable(nil, false)
  else
    vim.lsp.inlay_hint.enable(nil, true)
  end
end
test()
```
E5108: Error executing lua: ~/.config/nvim/init.lua:86: attempt to index field 'inlay_hint' (a nil value)

and if use `:h inlay_hint` or `:h vim.lsp`, can't find inlay_hint

### Steps to reproduce

download nvim.appimage
add `~/.config/nvim/init.lua
```lua
local function test()
   if vim.lsp.inlay_hint.is_enabled(nil) then
    vim.lsp.inlay_hint.enable(nil, false)
  else
    vim.lsp.inlay_hint.enable(nil, true)
  end
end
test()
```
```bash
# nvim
```

### Expected behavior

can use inlay_hint

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ubuntu 20.04

### Terminal name/version

default

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
inlay_hint release v0.10.0-dev
