### ISSUE TITLE
<C-u>zz does not work on the last line, when the last line is centered, and `scrollof` set to value >0

### ISSUE THREAD

**Issue by NStefan002** [neovim/neovim#28250]
### Problem

When the cursor is on the last line of the buffer, and the line is centered (with `zz`), `<c-u>zz` does not work - the cursor gets stuck on the last line. Preview (for a couple of seconds while the cursor is at line `87` I'm pressing `<c-u>` and nothing happens, only when I move the cursor one line up with `k` it works):

https://github.com/neovim/neovim/assets/100767853/b0809d25-d82d-475d-84fb-2f4cd13d3ecd

**Note:** I'm aware that there were some bugs and some fixes lately regarding `<c-u>` and `<c-d>` (#28160), so I guess that this issue is related.

### Steps to reproduce

minimal.lua:
```lua
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "Scroll down half screen" })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "Scroll up half screen" })
vim.opt.scrolloff = 8 -- or any value larger than 0
```
run: `nvim --clean file.txt -u minimal.lua`

### Expected behavior

Half-page jump.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2840+gc695caa7e

### Vim (not Nvim) behaves the same?

no, vim 8.2.3995 (installed using apt)

### Operating system/version

Ubuntu 22.04.4 LTS

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

wezterm

### Installation

bob (https://github.com/MordechaiHadad/bob)

**Comment by dmun** [comment]
To add, this also happens on the first line, with regular C-u C-d motions as well
