### ISSUE TITLE
C-d and C-u don't move the cursor half the page when viewport collides with the start/end of the file

### ISSUE THREAD

**Issue by dmun** [neovim/neovim#28251]
### Problem

When the start/end of the file is a couple of lines away from the viewport, scrolling to it with C-u or C-d does appropriately scroll the view, but doesn't fully move the cursor.

https://github.com/neovim/neovim/assets/39461169/9b32ea4c-c133-4f64-ae95-9d7af4c428e8

### Steps to reproduce

nvim -u NORC

### Expected behavior

normal half page cursor move/scroll

### Neovim version (nvim -v)

v0.10.0-dev-4946489e2

### Vim (not Nvim) behaves the same?

no, vim 9.0.1544

### Operating system/version

macOS 14

### Terminal name/version

kitty 0.33.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by luukvbaal** [comment]
Is this different from old behavior? This is already listed as a caveat in `:h CTRL-D/U`:

```
The cursor is moved the same number of
lines down in the file (if possible; when lines wrap
and when hitting the end of the file there may be a
difference).
```

**Comment by dmun** [comment]
I think the difference in the caveat is referring to the difference between the window scroll lines and cursor move lines. But yeah that could be interpreted differently.

I think it was originally meant to provide consistency in cursor jump distance, since you can always expect the cursor to jump half a page, independent of the window position.

**Comment by luukvbaal** [comment]
Ah yeah that interpretation probably makes more sense as a help text, and indeed is the old behavior.
