### ISSUE TITLE
Feature request: highlight driven `cpo-$` behaviour

### ISSUE THREAD

**Issue by mawkler** [neovim/neovim#28274]
### Problem

`:help cpo-$` says:

> When making a change to one line, don't redisplay the line, but put a '$' at
> the end of the changed text. The changed text will be overwritten when you
> type the new text.

### Expected behavior

I would love if Neovim instead of placing a `$` at the end of the changed text, gave the changed text a custom highlight. That way I could for instance make the changed text underlined or give it a different background color. This could be a new `cpo` option, like `cpo-h` for instance.

**Desired behaviour:**

1. Press `cw` at the start of the word `foobar`
2. The word `foobar` gets a custom highlight, let's call it `ChangedText`
3. Type `baz`
4. The line now says `bazbar`. `baz` doesn't have the `ChangedText` highlight, but the rest of the word (`bar`) still does
5. Press `<esc>`
6. The rest of the word (`bar`) dissappears, and therefore also its `ChangedText` highlight
7. ...
8. Profit?

**Comment by clason** [comment]
I'm sorry, but we want to _remove_ these ancient legacy options, not add to them! The current modal editing experience is core to (Neo)vim, and we don't want to change it.
