### ISSUE TITLE
Support autocompletion for braces

### ISSUE THREAD

**Issue by spacey-sooty** [neovim/neovim#28280]
### Problem

As of right now there is no native way to have braces autocomplete when editing text. This is supported by a variety of different editors and can be achieved through plugins but isn't natively supported in Neovim.

### Expected behavior

The easiest way to include this would be bundling something like [autoclose.nvim](https://github.com/m4xshen/autoclose.nvim/tree/main) into the project.

**Comment by clason** [comment]
Sorry, we are not looking to bundle more external plugins that need configuration.
