### ISSUE TITLE
why do I startup vim with plugin syntastic slow

### ISSUE THREAD

**Issue by talkw-liu** [neovim/neovim#2828]
After I installed ycm,syntastic,I discovered that the excessively long vim startup times I was experiencing
were caused by the Syntastic bundle.Here is the startup log:
......
120.527  000.016  000.016: sourcing /home/szapp/liujunping/.vim/bundle/syntastic/syntax_checkers/c/splint.vim
120.827  001.384  001.177: sourcing /home/szapp/liujunping/.vim/bundle/syntastic/syntax_checkers/cpp/pc_lint.vim
122.153  000.726  000.726: sourcing /home/szapp/liujunping/.vim/bundle/syntastic/autoload/syntastic/c.vim
2331.598  000.219  000.219: sourcing /home/szapp/liujunping/.vim/bundle/syntastic/autoload/syntastic/postprocess.vim
2334.496  000.095  000.095: sourcing /usr/share/vim/vim74/syntax/qf.vim
2335.041  000.045  000.045: sourcing /usr/share/vim/vim74/ftplugin/qf.vim
2336.252  2239.645: opening buffers
2337.480  000.068  000.068: sourcing /usr/share/vim/vim74/syntax/qf.vim
2338.019  000.039  000.039: sourcing /usr/share/vim/vim74/ftplugin/qf.vim
2338.953  000.065  000.065: sourcing /usr/share/vim/vim74/syntax/qf.vim                                                                                                
2339.478  000.039  000.039: sourcing /usr/share/vim/vim74/ftplugin/qf.vim
......

**Comment by fwalch** [comment]
Correct me if I'm wrong, but it looks like you are using Vim. This is the issue tracker for Neovim.

Since you suspect that your problem is caused by syntastic, maybe ask your question on the syntastic issue tracker.
