### ISSUE TITLE
When applying a macro in visual mode, the visual selection is lost

### ISSUE THREAD

**Issue by yorickpeterse** [neovim/neovim#28287]
### Problem

When applying a macro while in visual mode, the macro _is_ applied but in doing so the visual selection is lost, almost as if applying the macro forces NeoVim into normal mode first. This makes it impossible to use macros for recording jumps (e.g. "jump to the next `)`") and then apply those to a visual selection.

### Steps to reproduce

This reproduces with `nvim --clean`. First, create the file `test.txt` with these contents:

```
foo(100, 200, 300)
foo(100000, 200000, 300000)
foo(1, 2, 3)
```

Then run `nvim --clean test.txt`. Perform the following steps:

1. Place the cursor on the first `f` (the default)
2. Press `v` to enter visual mode, followed by `e` to select the first `foo`
3. Press `qq` to record a macro in the `q` register
4. Press `t)` to jump to the last character before the `)`, note that the visual selection is extended
5. Press `q` to stop recording the macro
6. Exit visual mode
7. Move to `f` on line 2, press `v` to enter visual mode and `e` to select `foo`
8. Press `@q` and observe that while the jump _is_ performed, the visual selection is lost

This can be observed in this recording:

[Screencast from 2024-04-12 01-51-34.webm](https://github.com/neovim/neovim/assets/86065/2ff561d7-4877-4459-8afc-729da7b37c4a)

### Expected behavior

The visual selection is retained.

### Neovim version (nvim -v)

aa56370f

### Vim (not Nvim) behaves the same?

No, it (9.1.264) behaves as expected

### Operating system/version

Fedora 39

### Terminal name/version

Ghostty

### $TERM environment variable

xterm-ghostty

### Installation

Git

**Comment by yorickpeterse** [comment]
@zeertzjq mentioned that NeoVim has a custom mapping for `@`, and indeed unmapping that solves the issue. They mentioned this is a feature (as in, the mapping), but the documentation of `:h v_@-default` makes no mention of it removing the visual selection.

Even if the intent is to somehow remove the selection, it seems super counter-intuitive to map that to `@` as it directly contradicts what Vim has been doing for who knows how long.

**Comment by zeertzjq** [comment]
It seems that these mappings also don't really work properly in blockwise Visual mode: a macro that starts with `A` appends after the end of the line rather than after the Visual selection. Maybe it makes more sense to only do the repeat in linewise Visual mode, but that seems a bit strange.

**Comment by zeertzjq** [comment]
The intention of #21422 is to apply a Normal mode macro on multiple lines, so it's necessary for the mapping to stop Visual mode.

**Comment by bew** [comment]
Wouldn't it also make sense in visual block mode, where each 'line' would start at the block selection?

**Comment by zeertzjq** [comment]
Because it doesn't really work.
