### ISSUE TITLE
paste in iterm2 on mac adds extra indentation

### ISSUE THREAD

**Issue by albertnetymk** [neovim/neovim#2829]
## How to reproduce the problem

1. Open neovim using `nvim -u NONE dummy.py`
2. `:filetype plugin indent on`
3. `:set filetype=python`
4. paste the following snippet into neovim using right-click, then select `paste`:
```
x = 1
if x == 1:
    # indented four spaces
    print "x is 1."
```
The result looks like this:
```
x = 1
if x == 1:
        # indented four spaces
            print "x is 1."
```
## ENV:
nvim: built from be66c0b3570a55671656959203bd5b824f77fde7 using homebrew
iterm2: 2.1.1
OSX: 10.9.5

**Comment by justinmk** [comment]
What happens with cmd-v?

**Comment by albertnetymk** [comment]
They shouldn't make any difference, should they? Tested just now; same behavior.

**Comment by justinmk** [comment]
Correct, they shouldn't.

**Comment by albertnetymk** [comment]
Found out the reason. My bad. Need to set Preferences>Profiles>Terminal>Report Terminal Types to be `xterm-256color`. Mine was mistakenly set to `screen-256color`.

Sorry for the noise. Excellent work done.

**Comment by justinmk** [comment]
Thanks for the followup!
