### ISSUE TITLE
Fix wrong type in documentation of `vim.spell.check()` in `runtime/lua/vim/_meta/spell.lua`

### ISSUE THREAD

**Issue by thomaswuhoileong** [neovim/neovim#28303]
### Problem

In `runtime/lua/vim/_meta/spell.lua`, the documentation of `vim.spell.check()` has `@return {[1]: string, [2]: string, [3]: string}[]`.

### Expected behavior

In `runtime/lua/vim/_meta/spell.lua`, the documentation of `vim.spell.check()` should have `@return {[1]: string, [2]: string, [3]: integer}[]` instead.

**Comment by clason** [comment]
Just make a PR.
