### ISSUE TITLE
omnifunc value gets overriden even when no additional plugins installed

### ISSUE THREAD

**Issue by barunps3** [neovim/neovim#28313]
### Problem

I tried to start lsp client and set buffer option to v:lua.vim.lsp.omnifunc during LspAttach event. 
I have no other configuration (keymaps, options, plugins.. etc) in init.lua other than below:

However, I noticed the omnifunc is getting overriden somewhere when starting up the nvim. After the buffer got its window, I source my init.lua (:source $MYVIMRC)  and the lsp works fine. 
Before sourcing $MYVIMRC:
<img width="681" alt="image" src="https://github.com/neovim/neovim/assets/47608189/d1d82e35-0c92-48b6-9ae6-51fb2f155385">

After sourcing $MYVIMRC
<img width="704" alt="image" src="https://github.com/neovim/neovim/assets/47608189/a5679bb5-8549-4bbf-962b-318942d3a5bb">

### Steps to reproduce

1. nvim init.lua

2. copy the following code into file:
```
-- Configure Language Servers
vim.lsp.start({
  name = "pyright",
  cmd = { "pyright-langserver", "--stdio" },
  root_dir = vim.fs.dirname(vim.fs.find({
    'pyproject.toml', 'setup.py', 'requirements.txt'}, { upward = true })[1]),
})

vim.api.nvim_create_autocmd('LspAttach', {
  group = vim.api.nvim_create_augroup('UserLspConfig', {}),
  callback = function(args)
    -- Enable completion triggered by <c-x><c-o>
    local bufnr = args.buf
    local client = vim.lsp.get_client_by_id(args.data.client_id)
    print("client id")
    if client.server_capabilities.completionProvider then
      vim.bo[bufnr].omnifunc = "v:lua.vim.lsp.omnifunc"
      print("in if function")
      print(tostring(vim.bo[bufnr].omnifunc))
    end
    print("out of if function")
    if client.server_capabilities.definitionProvider then
      vim.bo[bufnr].tagfunc = "v:lua.vim.lsp.tagfunc"
    end
    -- Buffer local mappings.
    -- See `:help vim.lsp.*` for documentation on any of the below functions
    local opts = { buffer = args.buf }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
    vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
    vim.keymap.set('n', '<space>wl', function()
      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, opts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
    vim.keymap.set({ 'n', 'v' }, '<space>ca', vim.lsp.buf.code_action, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<space>f', function()
      vim.lsp.buf.format { async = true }
    end, opts)
  end,
})
```

3. Then save, quit and reopen to see lsp did not attach. You would get no errors pointed out. Running following command```:verbose set omnifunc``` returns ``òmnifunc=```
5. After sourcing with :source $MYVIMRC, lsp gets attached and configured features work. As I have placed few prints in the autocommand for debugging, the following gets printed from which i infer that autocommands ran
<img width="465" alt="image" src="https://github.com/neovim/neovim/assets/47608189/e730cbf4-c22a-46de-bc08-3c75c3b50a15">

Since, the configuration is for language-server pyright. Here is diagnosis for python file:
Folder structure:
<img width="302" alt="image" src="https://github.com/neovim/neovim/assets/47608189/dd95daa9-e6f7-44b8-b4cc-7ef91703417e">
pyright language server is installed as well
<img width="589" alt="image" src="https://github.com/neovim/neovim/assets/47608189/7d7c65e3-2a4c-47dc-a029-054c1d4a0cce">

1. Open file: nvim encode_decode_strings.py 
2. Before sourcing, shows no error and omnifunc is not set
<img width="532" alt="image" src="https://github.com/neovim/neovim/assets/47608189/2542c2e5-e8d3-4c7d-8a0c-c1f39603833a">

3. Upon running ```:source $MYVIMRC```, the LspAttach autocommand does run (as seen from print below status line) but no errors are shown (not sure why it works with lua file). And running ```:verbose set omnifunc?``` returns ```v:lua.vim.lsp.omnifunc```
<img width="594" alt="image" src="https://github.com/neovim/neovim/assets/47608189/15a2c6a5-7371-4908-9491-a520d0788af4">

### Expected behavior

Following the documentation and with no extra plugins installed, I expected the lsp completion would work out of the box. I did not expect it to get overriden. Also I am not sure why errors are shown for Lua file but not for Python file

### Neovim version (nvim -v)

0.9.5 release

### Vim (not Nvim) behaves the same?

no, lsp feature

### Operating system/version

MacOs Sonoma 14.4.1

### Terminal name/version

iTerm2 3.4.3

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
What does `:verbose set omnifunc?` print after it gets overridden?

**Comment by zeertzjq** [comment]
The steps to reproduce don't look right. The only language server you have configured is pyright, but in the screenshot the diagnostic are for Lua.

**Comment by barunps3** [comment]
I have edited the issue with diagnostics for python file next to setup.py and requirements.txt both, though I know only one of them source attach the lsp client based on configuration in init.lua file. However, it is weird, the lsp error detection does not work at all for python file but works for lua file.

**Comment by zeertzjq** [comment]
I think you are not following the documentation. The documentation mentions:
```
    To ensure a language server is only started for languages it can handle,
    make sure to call |vim.lsp.start()| within a |FileType| autocmd. Either
    use |:au|, |nvim_create_autocmd()| or put the call in a
    `ftplugin/<filetype_name>.lua` (See |ftplugin-name|)
```
But you are calling `vim.lsp.start()` directly in `init.lua`.

**Comment by barunps3** [comment]
Thank you for guiding me to right place. I did make the changes and yes when I open a python file the omnifunc is set correctly. 
Current change in init.lua file
<img width="659" alt="image" src="https://github.com/neovim/neovim/assets/47608189/292b3046-7cf1-4167-8150-1a61a9b9fd19">

However, the python file highlights no errors like it did for init.lua and when I press Ctrl+x Ctrl+o it does not open completion drop down
<img width="505" alt="image" src="https://github.com/neovim/neovim/assets/47608189/d202ebf9-6485-49cc-9ecc-a05d3f9ef262">

Can you please tell, why it does not work ? I am new to neovim and lost in documentation.

**Comment by zeertzjq** [comment]
I don't know. I tested it and it works.

**Comment by barunps3** [comment]
It works for me now. All I did was create python file in .config/nvim directory. I am not sure what could have changed. However, I am closing this issue.
