### ISSUE TITLE
Adding git to build prerequisites

### ISSUE THREAD

**Issue by alanifotis** [neovim/neovim#28319]
### Problem

I think is a good idea adding git to build prerequisites
Especially helpful on fresh distro installation

PS. If you think that this is stupid or shouldn’t be requested here sorry for wasting your time 
Thank you 

### Expected behavior

To be able to blindly follow the build instructions and being able to without any extras on fresh installation

**Comment by dundargoc** [comment]
I'm confused. You don't need git to build neovim though. On what distro/os did you build neovim and what error message did you get?

**Comment by OscarCreator** [comment]
Maybe refering to this? https://github.com/neovim/neovim/blob/4ca6e08327496ed5efc3465c42464319302ba22a/BUILD.md?plain=1#L6-L16

**Comment by clason** [comment]
It's not a prerequisite, though; you can just as well download the tarball from github.

**Comment by dundargoc** [comment]
Aha, I see. You don't need it to build neovim, but you do need it to follow the "Quick Start" section. Thanks for the clarification. We could add a small note that the user may need to install git in the "Quick Start" section rather than adding `git` as a build dependency, which isn't true.

**Comment by dundargoc** [comment]
I've added a small snippet in the quick start section in this PR: https://github.com/neovim/neovim/pull/28208

**Comment by alanifotis** [comment]
Yeah I know isn’t necessary to build 
As I stated before I installed debian on my android phone (inside termux terminal emulator) didn’t include git i was copy pasting the commands to build and i hot the error that I needed to install git 
I built the package successfully no problem at all 
I am sorry if I wasted your time 
I am not trying to get a job by opening this request but for someone less experienced than me ( i am a amateur at this stuff) they will think that the guide isn’t complete
thank you in advance
