### ISSUE TITLE
LSP: Support for typescript / typescript-language-server's "Go to Source Definition" command

### ISSUE THREAD

**Issue by ajbuz** [neovim/neovim#28328]
### Problem

It appears this hasn't been discussed here but TypeScript 4.7 adds support for a new  editor command called "Go To Source Definition" `_typescript.goToSourceDefinition` and It would be really helpful if you could also provide support for it.
More info & demo can be found [in release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#go-to-source-definition). 

Thank you.

### Expected behavior

__

**Comment by clason** [comment]
That's not in the **LSP** specification, though, so out of scope for us. @MariaSolOs

**Comment by justinmk** [comment]
We will not add explicit support for server-specific commands. However we do need a general mechanism that makes it easy for users (and nvim-lspconfig) to:

1. iterate through discovered server capabilities / commands
2. define aliases to commands, in a non-verbose way

The current situation with nvim-lspconfig is that 10 lines of code are needed to define commands. That's unsustainable.

See also https://github.com/neovim/nvim-lspconfig/issues/1937

**Comment by justinmk** [comment]
@clason unless we have an existing issue, I'd like to keep this open to track the above idea

**Comment by clason** [comment]
I would strongly prefer a targeted issue about **general** server-specific commands. Adding individual commands is out of scope, and re-using this issue will give the wrong impression.

**Comment by justinmk** [comment]
> I would strongly prefer a targeted issue about **general** server-specific commands

Stubbed in https://github.com/neovim/neovim/issues/28329 , improvements welcome

**Comment by fjouault** [comment]
Although this is not a fully generic solution, I had some success with nvim 0.10.4 by adding the following code in `on_attach`:

```lua
local old_handler = vim.lsp.handlers["workspace/executeCommand"]
vim.lsp.handlers["workspace/executeCommand"] = function(a, result, ctx)
        if ctx.params.command == "_typescript.goToSourceDefinition" then
                vim.lsp.handlers["textDocument/definition"](a, result, ctx)
        else
                old_handler(a, result, ctx)
        end
end

vim.keymap.set("n", "gs", function()
        local params = vim.lsp.util.make_position_params()
        vim.lsp.buf.execute_command({
        command = "_typescript.goToSourceDefinition",
        arguments = {
                params.textDocument.uri,
                params.position
        },
}) end, {buffer=bufnr})
```

The first part makes sure the response will be handled as if it was a "go to definition". 

From this experience, I would suggest adding a way to register command handlers.
This would make that first part simpler, and likely more robust, for instance:
```lua
vim.lsp.handlers.command_handlers["_typescript.goToSourceDefinition"] = vim.lsp.handlers["textDocument/definition"]
```
