### ISSUE TITLE
popup windows should have URI for lsp extensions

### ISSUE THREAD

**Issue by Fildo7525** [neovim/neovim#28332]
### Problem

It would be great to have the popup window with a buff number of URI. This would open a wide variety of extensions. One use case would be implementing GotoDefinition from the popup window.

### Expected behavior

When in the popup window with a cursor the `vim.lsp.util.make_position_params` function would report the position in the temporary file. The file would not be opened as a new buffer but in the popup window.

**Comment by justinmk** [comment]
> have the popup window with a buff number of URI.

Is there a typo here? I don't understand this sentence.
