### ISSUE TITLE
[bug][not in vim] The leading slash is stripped from directory names

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#2833]
This bug is affecting me badly because I’m trying to implement a netrw replacement. When opening a directory with a leading slash (either with `nvim -u NONE /tmp` or from an existing instance with `:edit /tmp`), the leading slash is removed from the name, causing it to be treated like a relative file path. Surprisingly, both `/tmp/` and `//tmp` produce the intended result.

Steps to reproduce
------------------------
    nvim -u NONE +'au VimEnter * echoerr expand("<afile>") . @% . expand("%")' /tmp

Expected result
--------------------
    "/tmp" is a directory
    Error detected while processing VimEnter Auto commands for "*":
    /tmp/tmp/tmp

This is vim’s behavior.

Actual result
----------------
    "/tmp" is a directory
    Error detected while processing VimEnter Auto commands for "*":
    tmptmptmp

Note that although nvim tries to open `/tmp` and realizes it’s a directory, it then incoherently reports the current filename as `tmp`.

**Comment by justinmk** [comment]
> I’m trying to implement a netrw replacement.

https://github.com/justinmk/vim-dirvish might be useful.

**Comment by Grimy** [comment]
Dirvish is nice, but it suffers from this issue as much as I do. After installing dirvish, `nvim /tmp` results in an empty buffer with the message `/tmp is a directory`. `nvim /tmp/` correctly opens a dirvish buffer on /tmp.

**Comment by justinmk** [comment]
> Dirvish is nice, but it suffers from this issue as much as I do

I figured. But I just mentioned it since it could be a useful base for making a netrw replacement: It's 450 SLOC, it solves some nasty edge cases, and does pretty much nothing else.

**Comment by tarruda** [comment]
This bug is old, introduced by @92a0374d7b6b27cb91e51e5cfe735fbde100632c

I will fix on my next PR
