### ISSUE TITLE
Bicep omnifunc completion mismatch between popup menu and inserted selection

### ISSUE THREAD

**Issue by barunps3** [neovim/neovim#28342]
### Problem

When using lsp client with bicep language server, I notice that returned matches in the popup menu and text inserted during selection with Ctrl+N/Ctrl+P after @ character is different (when selecting the api version of resource type in Bicep). Upon selecting the api version the whole text including the resource type (which was already inserted last step) is inserted. This behaviour does not exist on vscode.  

### Steps to reproduce

1. To download the latest release (v0.26.170) and place in /usr/local/bin/bicep-langserver:
```bash
(cd $(mktemp -d) \
    && curl -fLO https://github.com/Azure/bicep/releases/latest/download/bicep-langserver.zip \
    && rm -rf /usr/local/bin/bicep-langserver \
    && unzip -d /usr/local/bin/bicep-langserver bicep-langserver.zip)
```

2. Bicep language server requires the [dotnet-sdk](https://dotnet.microsoft.com/download) to be installed.

3. Create directory and place this Minimal config (minimal_init.lua) in it
```
-- Neovim does not have built-in support for the bicep filetype which is required for lspconfig to automatically launch the language server.
vim.cmd [[ autocmd BufNewFile,BufRead *.bicep set filetype=bicep ]]

local root_dirname = vim.fs.dirname(vim.fs.find({'main.bicep', '.git', '.github'}, { upward = true })[1])
vim.lsp.start({
    name = "bicepls",
    cmd = { "dotnet", "/usr/local/bin/bicep-langserver/Bicep.LangServer.dll" },
    root_dir = root_dirname,
})
```

4. In the same directory: nvim -u minimal_init.lua main.bicep. Follow this video to see the issue

https://github.com/neovim/neovim/assets/47608189/c6c75ae1-c250-4a25-8190-c351e75d75ea

### Expected behavior

The completion item would be inserted as 2023-07-01 after @ as shown in popup menu, resulting in:

`resource keyvault 'Microsoft.KeyVault/vaults@2023-07-01'`

Example from Vscode:

https://github.com/neovim/neovim/assets/47608189/d4870204-c123-4f44-9586-8b3c99a9d358

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MacOs Sonoma 14.4.1

### Terminal name/version

iTerm2 3.4.3

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by justinmk** [comment]
Can you try the development version? 

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.

**Comment by barunps3** [comment]
With the new version, the completion works fine when setting the resource api version as show below:

https://github.com/neovim/neovim/assets/47608189/435f4b70-9717-4b7e-b1bb-410aa14b802e


However, with module where we need ref file path, the issue is that completion doesn't work unless closing `'` is present as shown in this video. I also noticed the pop menu view does not show quotes but upon selection the quote is inserted automatically

https://github.com/neovim/neovim/assets/47608189/3523b479-78a5-4adc-a1f9-10d2cd66c20c

**Comment by justinmk** [comment]
> With the preview version, the completion works fine when setting the resource api version as show below:

Closing then.



> However, with module where we need ref file path, the issue is that completion doesn't work unless closing `'` is present as shown in this video. I also noticed the popup menu view does not show quote `'` at the end or beginning of file path but upon selection the quotes are inserted automatically

Too many details. I don't have time to watch videos.

Provide a minimal repro, or ideally a failing test case, in a separate issue. But first look at existing "lsp" and "completion" issues.
