### ISSUE TITLE
Problem with the wildmenu

### ISSUE THREAD

**Issue by klingberg** [neovim/neovim#2834]
This is a minor issue but there seems to be a problem with the wildmenu.

1. Type the first letters of a command and then hit tab for the wildmenu.
Instead of the wildmenu some sort of unselectable version of the wildmenu turns up.
![screen shot 2015-06-12 at 19 26 00](https://cloud.githubusercontent.com/assets/1440293/8136124/5afdec9a-113c-11e5-81c2-248bb3aaa6f5.png)

2. Hit tab again and the expected wildmenu appears.
![screen shot 2015-06-12 at 19 26 10](https://cloud.githubusercontent.com/assets/1440293/8136487/a5949e8e-113c-11e5-8c89-e1f374f2ce59.png)

Keep up the excellent work!

**Comment by ntnn** [comment]
That behaviour is defined by `wildmode`, which seems to have `list:full` has default. For only wildmode you need `full`.

**Comment by klingberg** [comment]
Aha! You learn something new everyday! :) Thank you!
