### ISSUE TITLE
Python Tree-sitter @spell highlights string prefixes

### ISSUE THREAD

**Issue by ColinKennedy** [neovim/neovim#28365]
### Problem

![image](https://github.com/neovim/neovim/assets/10103049/17e8df8e-65e3-428c-af04-f0df629e6f5d)

Python strings can have prefixes such as r, f, u, etc. These shouldn't be spell checked but they are and are recognized as misspellings (see screenshot).

### Steps to reproduce

Load Neovim with Python tree-sitter parser enabled. Then `:set spell`

### Expected behavior

The "r" in the screenshot is not highlighted as a misspelled word.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2791+g99b3a068d

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

Ubuntu 20.02

### Terminal name/version

Wezterm

### $TERM environment variable

xterm-256color

### Installation

compiled from source

**Comment by clason** [comment]
Queries are maintained in nvim-treesitter.

**Comment by ColinKennedy** [comment]
I thought Neovim is bundled with Python tree-sitter so it'd apply here too. Under `runtime/queries/python/highlights.scm`. Why does that file exist if the query is unused?

PRs:

https://github.com/neovim/neovim/pull/28366
https://github.com/nvim-treesitter/nvim-treesitter/pull/6449

**Comment by clason** [comment]
I'm saying that this file is taken from nvim-treesitter, just as we take syntax files from Vim. So any changes must go through that project.

**Comment by clason** [comment]
And queries are synced periodically (e.g., before a release). No need to make a separate PR for individual changes.

**Comment by Rich107** [comment]
Well, my English is terrible and typing, whilst I understand the benefits of having spelling turned off for certain elements can anyone point me to docs for overwriting this for my local setup? I miss spell function names all the time and strings going into logs etc. 

I was hoping to not have to fork tree-sitter to manually set the @spell

**Comment by ColinKennedy** [comment]
> I was hoping to not have to fork tree-sitter to manually set the @spell

You don't need to fork nvim-treesitter to add / change settings. For example

Make a `{root}/after/queries/your_language_here/highlights.scm`

```scm
; extends

(the_node_that_you_want_to_set) @spell
```

**Comment by clason** [comment]
(not `after`, just `queries`)
