### ISSUE TITLE
Default colorscheme incorrect

### ISSUE THREAD

**Issue by marcin-szmagara** [neovim/neovim#28386]
### Problem

After I type `:colorscheme default` the colors change.
When using tmux, this happens automatically.

### Steps to reproduce

nvim --clean -u minimal.lua
:e ~/.bashrc
:colorscheme
:colorscheme default

### Expected behavior

On `:colorscheme` it should print `default`. It does.

After `:colorscheme default` the colors should remain the same. They change.

In Vim the colors remain the same.

### Neovim version (nvim -v)

0.9.5, also 0.7.2-7 (debian bookworm) 

### Vim (not Nvim) behaves the same?

no, 9.0.1499 

### Operating system/version

debian bookworm

### Terminal name/version

XTerm(379), also tried with xfce4-terminal

### $TERM environment variable

xterm, also tried with xterm-256color and ansi-256color

### Installation

appimage for the 0.9.5

**Comment by glepnir** [comment]
default colorscheme has been changed in head . please try nightly verison.

**Comment by justinmk** [comment]
to get the old colors:

    :colorscheme vim

**Comment by zeertzjq** [comment]
What is the content of `minimal.lua`?

**Comment by justinmk** [comment]
> ### Neovim version (nvim -v)
> 0.9.5, also 0.7.2-7 (debian bookworm)

**Comment by marcin-szmagara** [comment]
> What is the content of `minimal.lua`?

Unchanged https://github.com/neovim/neovim/blob/master/contrib/minimal.lua
Now I can see that it does nothing, sorry for the confusion.

> default colorscheme has been changed in head . please try nightly verison.

In nightly, when I type `:colorscheme vim` it doesn't actually look like vim.

I also checked on a clean debian bookworm installation in a virtual machine using nightly in xfce4-terminal.

**Comment by justinmk** [comment]
> In nightly, when I type `:colorscheme vim` it doesn't actually look like vim.

what does `:set bg?` say in both ? try changing it.

**Comment by marcin-szmagara** [comment]
> what does `:set bg?` say in both ? try changing it.

Indeed that was my original issue. In 0.95 typing `:colorscheme default` changed `background` from `light` to `dark`.

However, in nightly, the `vim` colorscheme is different than `default` in 0.95, even when for both `background=light`.

**Comment by marcin-szmagara** [comment]
> different exactly how? show a screenshot, or say exactly what is different

![left is 0.95, right is nightly](https://github.com/neovim/neovim/assets/58288839/601bcb59-b10d-4d3c-ab27-cb6210834b41)

Left is 0.95, right is nightly.

**Comment by clason** [comment]
Yes. That is an _intentional_ behavior change, as you would have realized had you read `:news` (which is required reading for anyone following HEAD or upgrading to a new version).
