### ISSUE TITLE
The help docs do not work correctly with vimdoc TS parser installed

### ISSUE THREAD

**Issue by JustLinuxUser** [neovim/neovim#28383]
### Problem

I am currently running the latest master commit, and when opening the help menu some elements do not appear.
after `TSUninstall vimdoc` everything works. I don't think its TS'es fault here, because the `:InspectTree` shows everything, also when highlighting the invisible elements in visual mode, they show again.

![image](https://github.com/neovim/neovim/assets/75628709/42c10cdc-201c-4a9b-9e1c-b40be79bdd85)

In this screenshot you can see the TSInspect output, the invisible elements, the invisible elements becoming visible when highlighted.

### Steps to reproduce

```
:TSInstall vimdoc
:help vim.system
```

### Expected behavior

Being able to see everything

### Neovim version (nvim -v)

2f371ad7d0294072d407bb05816425b5694d1935

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

aur

**Comment by clason** [comment]
Works for me. Please share a (minimal!) config we can test with `nvim --clean -u test.lua`. Note that the `vimdoc` parser is bundled and used by default, so no plugins are necessary.

**Comment by JustLinuxUser** [comment]
Thanks for the feedback, I reinstalled nvim directly from the git repo, same issue.
Here is the minimal config that still causes issues:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		config = function()
			local configs = require("nvim-treesitter.configs")

			configs.setup({
				highlight = { enable = true },
				indent = { enable = true },
				incremental_selection = {
					enable = true,
					keymaps = {
						init_selection = "<CR>", -- set to `false` to disable one of the mappings
						node_incremental = "<CR>",
						scope_incremental = "<TAB>",
						node_decremental = "<S-TAB>",
					},
				},
			})
		end,
	},
})
```

**Comment by justinmk** [comment]
does it work with `nvim-treesitter` ? why is this being reported in the Nvim repo?

**Comment by clason** [comment]
Not minimal enough for this repo; no plugins are required to test the bundled vimdoc parser. (If that works, the problem is somewhere else; usually some unrelated plugin shipping outdated queries.)

**Comment by JustLinuxUser** [comment]
Yes, updating nvim-treesitter helped, thanks
