### ISSUE TITLE
Neovim crash almost instantly on MacOS (SEGFAULT)

### ISSUE THREAD

**Issue by kuntau** [neovim/neovim#28396]
### Problem

This has happened to me for a couple of months, but I don't have the time investigate it. I just got time to do fresh pull from github and start to investigate.

1. It didn't crash with `nvim --clear` or `nvim -u NONE`
2. I tried disable all plugins, remove configs file one at a time and still crash
3. I don't know anything about `lldb` but read some issue with crash and try to run with it. Can't run backtrace (invalid thread)
4. In `lldb` `process exited with status 139`
5. Log from `Console`
```
Process:               nvim [19068]
Path:                  /usr/local/bin/nvim
Identifier:            nvim
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        nvim [19065]
Responsible:           nvim [19065]
User ID:               501

Date/Time:             2024-04-18 15:42:31.389 +0800
OS Version:            macOS 11.7.10 (20G1427)
Report Version:        12
Anonymous UUID:        F4B8E738-3769-9066-F773-915080FBC2C9


Time Awake Since Boot: 22000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000250
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [19068]

VM Regions Near 0x250:
--> 
    __TEXT                      100000000-1005bc000    [ 5872K] r-x/r-x SM=COW  /usr/local/bin/nvim

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   nvim                          	0x0000000100360374 changed_window_setting + 4
1   nvim                          	0x000000010006f519 lj_vm_ffi_call + 132
2   nvim                          	0x00000001000cd735 lj_ccall_func + 2069 (lj_ccall.c:1187)

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007ffeefbfd800  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x00007ffeefbfd750  rsp: 0x00007ffeefbfd750
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0xfffffffffffffff5
  r12: 0x0000000000000000  r13: 0x00000001009d7900  r14: 0x00000001009d7900  r15: 0x0000000000000000
  rip: 0x0000000100360374  rfl: 0x0000000000010246  cr2: 0x0000000000000250
  
Logical CPU:     6
Error Code:      0x00000006 (no mapping for user data write)
Trap Number:     14

Thread 0 instruction stream:
  00 00 80 8b 00 02 00 00-04 48 83 c4 08 5b 5d c3  .........H...[].
  66 2e 0f 1f 84 00 00 00-00 00 66 90 55 48 89 e5  f.........f.UH..
  53 50 48 8d 1d 33 b6 29-00 48 8b 3b 83 bf 98 00  SPH..3.).H.;....
  00 00 00 74 1e e8 a2 fe-ff ff 48 8b 03 8b 88 38  ...t......H....8
  02 00 00 89 88 94 00 00-00 c7 80 98 00 00 00 00  ................
  00 00 00 48 83 c4 08 5b-5d c3 66 90 55 48 89 e5  ...H...[].f.UH..
 [c7]87 50 02 00 00 00 00-00 00 c6 87 00 02 00 00  ..P.............	<==
  00 48 8d 05 01 08 29 00-48 8d 0d 7f 05 29 00 8a  .H....).H....)..
  09 0a 08 74 02 5d c3 83-bf 8c 02 00 00 27 7f f5  ...t.].......'..
  c7 87 8c 02 00 00 28 00-00 00 c7 87 50 02 00 00  ......(.....P...
  00 00 00 00 48 8d 05 d5-08 29 00 83 38 27 7f d5  ....H....)..8'..
  c7 00 28 00 00 00 5d c3-0f 1f 40 00 55 48 89 e5  ..(...]...@.UH..
  
Thread 0 last branch register state not available.
```

Please. let me know if you need more information. Thank you.

### Steps to reproduce

run `nvim` or `nvim <file>`

### Expected behavior

Open file normally

### Neovim version (nvim -v)

VIM v0.10.0-dev-4305+ge1ca7a7bf
LuaJIT 2.1.1710088188

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MacOS 11.7.10

### Terminal name/version

Wezterm/Kitty same result

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by clason** [comment]
> Please. let me know if you need more information. Thank you.

You _must_ bisect your config to find out which plugin is responsible (and it _is_ a plugin). Look for uses of FFI.

If you use nvim-ufo (or noice.nvim), make sure these are updated to the latest commit.

**Comment by kuntau** [comment]
> > Please. let me know if you need more information. Thank you.
> 
> You _must_ bisect your config to find out which plugin is responsible (and it _is_ a plugin). Look for uses of FFI.
> 
> If you use nvim-ufo (or noice.nvim), make sure these are updated to the latest commit.

Before reporting this. I deleted the whole plugins folder (lazy) and re-install all from scratch, so I guess it's the latest.

**Comment by zeertzjq** [comment]
Maybe you have locked some plugin versions?

**Comment by clason** [comment]
And plugins can be plain broken. If they use FFI, _any_ commit here can break them and they need to adapt. So there's no alternative to bisecting your plugins and then reporting the issue _to the one that crashes_.

**Comment by kuntau** [comment]
I'll close first until I investigate those plugins. I do have ufo & noice

**Comment by louisroymond91** [comment]
You think so my friend because I’m trying to see what we can do about it.
