### ISSUE TITLE
No colors when compiling YCM through Vim-Plug on Neovim 

### ISSUE THREAD

**Issue by ladislas** [neovim/neovim#2840]
I use vim-plug to manage my plugins and it works great with neovim (that I love)

The only minor issue I have is that when compiling YCM, I don't get the colored output I was used to.

![](https://cloud.githubusercontent.com/assets/2206544/8154049/6664055a-1336-11e5-903d-4175e1ddcea8.png)

It is only aesthetics but I thought you should know :)

**Comment by justinmk** [comment]
Are you compiling it via `:term`, or are you using a vim-plug `"do"` post-install handler? If the latter, then it can be addressed if vim-plug uses `:term` instead of `:!` or `system()`.

**Comment by ladislas** [comment]
via "do". i'll report thanks! :)
