### ISSUE TITLE
vim.ui.open fails to open the URL that contais equal (`=`) in WSL

### ISSUE THREAD

**Issue by kyoh86** [neovim/neovim#28410]
### Problem

Calling `:lua vim.ui.open('https://example.com/?g=')`, it opens explorer.exe.

### Steps to reproduce

```
nvim --clean -c 'lua vim.ui.open("https://example.com/?g=")'
```

### Expected behavior

https://example.com/?g= is shown in the default browser.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-e1ca7a7
(it also fails at v0.10.0-dev-5371ed3)

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux 5.15.146.1-microsoft-standard-WSL2 / Windows 11

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by justinmk** [comment]
explorer.exe is what decides how to handle the given path. What happens if you do this in your WSL terminal?:

     explorer.exe "https://example.com/?g="

We may need to restore use of wslview , or maybe `wsl.exe <subcommand>` ? See https://github.com/neovim/neovim/pull/26947#issuecomment-1974805042

**Comment by kyoh86** [comment]
```
explorer.exe "https://example.com/?g="
```

It does not open web browser but explorer.

I do not know of any solution that does not use wslview.
I don't think replacing the role that wslview plays with vim.ui.open is a very good choice...
https://github.com/wslutilities/wslu

**Comment by justinmk** [comment]
> I don't think replacing the role that wslview does with vim.ui.open is a very good choice...
> https://github.com/wslutilities/wslu

I don't know what that means. vim.ui.open could call wslview, it's not "replacing" it.
