### ISSUE TITLE
travis/tests: random failure for screen_basic test on travis

### ISSUE THREAD

**Issue by lucc** [neovim/neovim#2841]
I have found some of my PRs reporting failure on travis b/c the test `test/functional/ui/screen_basic_spec.lua` failed. These PRs where all new test files (which should not change the outcome of other tests).

I assume that it is an error in the failing test and not in the new test (changes from the PR) b/c the error occurred randomly and sometimes went away after a rebase or was present one some architecture but not on another. The error message also indicates that it could be a race condition in the test.

Examples: [here](https://travis-ci.org/neovim/neovim/jobs/66296046), [here](https://travis-ci.org/neovim/neovim/jobs/66296047), [here](https://travis-ci.org/neovim/neovim/jobs/67012673). There were more like this but the PRs are either closed or the build restarted. I will post new ones as I encounter them.

**Comment by justinmk** [comment]
Yep, and thanks to @bfredl the test tools warn about it:

```
Warning: Screen changes have been received after the expected state was seen.
This is probably due to an indeterminism in the test. Try adding
`wait()` (or even a separate `screen:expect(...)`) at a point of possible
indeterminism, typically in between a `feed()` or `execute()` which is non-
synchronous, and a synchronous api call.
      
stack traceback:
	./test/functional/ui/screen.lua:263: in function 'wait'
	./test/functional/ui/screen.lua:219: in function 'expect'
	...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:493: in function <...d/neovim/neovim/test/functional/ui/screen_basic_spec.lua:490>

```

**Comment by lucc** [comment]
The error does not occur on every test run. I can reproduce it if I run the offending test multiple times:
```sh
.deps/usr/bin/busted --filter 'has minimum width/height values' --repeat 1000 test/functional/ui/screen_basic_spec.lua
```
I get up to 1% failures if I run this. I suspect it also depends on the load of the computer running the tests.

**Comment by lucc** [comment]
I retried this after e85c9966b8b5011e8eda1aef20d00d74d6eec581 (which was merged in #2980).
For 1000 repetitions without grep and wc I get 16 errors (1.6%). Interestingly the error message was shown for *successful* tests as well (3 out of 1000):
```
[...]
Repeating all tests (run 846 of 1000) . . .

●
1 success / 0 failures / 0 errors / 0 pending : 0.012818 seconds

Repeating all tests (run 847 of 1000) . . .

Warning: Screen changes have been received after the expected state was seen.
This is probably due to an indeterminism in the test. Try adding
`wait()` (or even a separate `screen:expect(...)`) at a point of possible
indeterminism, typically in between a `feed()` or `execute()` which is non-
synchronous, and a synchronous api call.

Note that sometimes a `wait` can trigger redraws and consequently generate more
indeterminism. If adding `wait` calls seems to increase the frequency of these
messages, try removing every `wait` call in the test.

If everything else fails, use Screen:redraw_debug to help investigate what is
  causing the problem.
      
stack traceback:
	./test/functional/ui/screen.lua:270: in function 'wait'
	./test/functional/ui/screen.lua:219: in function 'expect'
	test/functional/ui/screen_basic_spec.lua:492: in function <test/functional/ui/screen_basic_spec.lua:490>

●
1 success / 0 failures / 0 errors / 0 pending : 0.013546 seconds

Repeating all tests (run 848 of 1000) . . .
[...]
```

I I pipe 10000 repetitions into grep and wc I get between 470 and 580 failures (5.8%).

@tarruda did you see any improvements after e85c9966b8b5011e8eda1aef20d00d74d6eec581?

**Comment by tarruda** [comment]
Hmm, I thought @e85c996 would have taken care of this test. The problem is that in some cases the `wait` calls themselves result in redraws(some msgpack-rpc are treated as special keys by the main loop). I will have to revisit this after #2371 is fixed.

**Comment by justinmk** [comment]
see 4322021baeefed655ebc345fed8fa019e466728d and e2b031a3423fe34b8a5f0c6a48e4a4db20beda4f
