### ISSUE TITLE
Recursion in vim.keymap despite remap = false

### ISSUE THREAD

**Issue by frangio** [neovim/neovim#28418]
### Problem

Using `vim.keymap` with a function argument for rhs that invokes the lhs of the mapping results in an error due to unbounded recursion.

### Steps to reproduce

minimal.lua:
```lua
vim.keymap.set('n', '*', function () vim.cmd 'normal *' end, { remap = false })
```

`nvim --clean -u minimal.lua`

Press `*`

### Expected behavior

Recursion should be avoided by `remap = false` and the default `*` behavior should trigger.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2954+g13ebfafc9

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Debian GNU/Linux 12

### Terminal name/version

WezTerm 20240203-110809-5046fc22

### $TERM environment variable

wezterm

### Installation

built from source

**Comment by zeertzjq** [comment]
Use `:normal!`
