### ISSUE TITLE
bufload a new buffer then nvim_set_current_buf will trigger BufWinEnter twice

### ISSUE THREAD

**Issue by gh-liu** [neovim/neovim#28439]
### Problem

`bufload` a new buffer then `nvim_set_current_buf` will trigger `BufWinEnter` twice

### Steps to reproduce

```lua
-- test.lua
vim.api.nvim_create_autocmd("BufWinEnter", {
	callback = function(ev)
		vim.print(ev)
	end,
})

vim.api.nvim_create_user_command("LoadFile", function(opts)
	local bufnr = vim.fn.bufadd(opts.fargs[1])
	vim.fn.bufload(bufnr)
	vim.api.nvim_set_current_buf(bufnr)
end, { nargs = 1 })

```

nvim --clean -u test.lua
:LoadFile test.lua

### Expected behavior

trigger `BufWinEnter` once

### Neovim version (nvim -v)

v0.10.0-dev-2971+g6d732ad3c

### Vim (not Nvim) behaves the same?

Not try vim

### Operating system/version

macos

### Terminal name/version

kitty

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
I don't think this should be changed. This is how `bufload()` works.
