### ISSUE TITLE
scp under Cygwin on Windows

### ISSUE THREAD

**Issue by pguerin3** [neovim/neovim#28452]
### Problem

Under Vim 9.0 on Cygwin on Windows, the following command works out of the box:
```
:e scp://ubuntu@<putPublicIPAddressInHere>/
```
The output is the directory of the server, and that is the expected behaviour.

Under NeoVim 0.9.5 on Cygwin on Windows, the same command returns an error:
```
:e scp://ubuntu@<putPublicIPAddressInHere>/
```
The error received is:
```
Error detected while processing BufReadCmd Autocommands for "scp://*"..function netrw#Nread[4]..netrw#NetRead[109]..<SNR>22_NetrwBrowse[252]..<SNR>22_PerformListing[141]..<SNR>22_NetrwRemoteListing:
line  137:
E485: Can't read file C:\cygwin64\tmp\nvim.0\CgbXbu\1
```
However the scp login component seems to work, but the output from the command is blank.

### Steps to reproduce

Doing a trace of Neovim (set verbose=9), I can see that under the covers, the following command is being run:
```
ssh ubuntu@<putPublicIPAddressInHere> ls -FLa >C:\cygwin64\tmp\nvim.0\CgbXbu\1 2>&1
```
I can test that command outside Neowim, and actually it works, but creates a file in my home directory named: C:cygwin64tmpnvim.01XCdEX2.
So the '/' are stripped out, and the file is not created in the C:\cygwin64\tmp.
Therefore Neovim is unable to read the file C:\cygwin64\tmp\nvim.0\CgbXbu\1, because it is named C:cygwin64tmpnvim.01XCdEX2 instead.

I noticed that there is a netrw config in Neovim named g:netrw_cygwin. ie assume scp under windows is from cygwin.
This netrw config is also present in Vim 9.1.
I have set this to various values (ie 0 amd 1), but doesn't seem to make a difference to scp.

### Expected behavior

Scp should return an output to the C:\cygwin64\tmp directory.

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

vim 9.0.2155

### Operating system/version

Windows 10

### Terminal name/version

Cygwin 2.931

### $TERM environment variable

xterm-256color

### Installation

From zip file from the github release page.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS.
