### ISSUE TITLE
`vim.deprecate()` can be significantly slower than deprecated function

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#28459]
### Problem

Adding `vim.deprecate()` to a deprecated function can lead to its relatively significant performance decrease. In particular, this is noticeable after #28440.

### Steps to reproduce

1. Create the following 'init.lua':
    ```lua
    _G.bench_tbl_islist = function()
      local durations, arg = {}, { 'a' }
      for _ = 1, 5 do
        local start_time = vim.loop.hrtime()
        vim.tbl_islist(arg)
        -- Insert duration in milliseconds
        table.insert(durations, 0.000001 * (vim.loop.hrtime() - start_time))
      end
      return durations
    end
    ```
2. `nvim --clean -u init.lua`
3. `:=bench_tbl_islist()`. It gives me the following results:
    -  On current Nightly (`NVIM v0.10.0-dev-2976+g208852126`) it is something like `{ 3.72243, 0.918169, 0.968143, 0.763256, 0.783424 }`.
    - On 0.9.5: `{ 0.002955, 0.000361, 0.000281, 0.000251, 0.00019 }`.

The main slowdown seems to be due to [usage of `vim.version()`](https://github.com/neovim/neovim/blob/ea1c9f60e04429e8472370b59616d069ad7fbc8c/runtime/lua/vim/_editor.lua#L1058-L1059), which in turn seems to be due to [usage of `vim.fn.api_info()`](https://github.com/neovim/neovim/blob/ea1c9f60e04429e8472370b59616d069ad7fbc8c/runtime/lua/vim/version.lua#L455).

### Expected behavior

Deprecating (except hard deprecating) should not significantly impact performance of a deprecated function.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2976+g208852126

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.8.7-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by aleksandersumowski** [comment]
Slowing down deprecated functions is well established approach to pushish people to upgrade  😂
