### ISSUE TITLE
gc Comments C++ incorrectly

### ISSUE THREAD

**Issue by spacey-sooty** [neovim/neovim#28468]
### Problem

the `gc` command comments C++ code incorrectly. 
![image](https://github.com/neovim/neovim/assets/114076356/6570f4d3-5125-4970-b885-9a9794573ad4)

### Steps to reproduce

1. Open a C++ file and write some code.
2. Go into a visual block and highlight some lines.
3. Run `gc`
4. See incorrect comments

### Expected behavior

C++ code should be commented either like this:
```cpp
    /*
    if (strcmp(argv[1], "help")) {
        printf("Commands :\n");
        printf("Help: Prints a list of commands.\n");
    }
    */
```
or like this
```cpp
    // if (strcmp(argv[1], "help")) {
    //     printf("Commands :\n");
    //     printf("Help: Prints a list of commands.\n");
    // }
```
Commenting each line with a multiline comment is not correct

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3305bb9e4 

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

PopOS 22.04

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

screen-256color

### Installation

Build master from source

**Comment by clason** [comment]
_Is_ the file C++? What does `:set filetype?` say?

**Comment by spacey-sooty** [comment]
It echos `filetype=cpp`

**Comment by clason** [comment]
...which also has `/*%s*/` as the commentstring, so this is working as intended. If you want that changed, open an issue (or a PR) at vim/vim.

**Comment by zeertzjq** [comment]
This is working as documented:
```
3. Commenting							*commenting*

Nvim supports commenting and uncommenting of lines based on 'commentstring'.

Acting on a single line behaves as follows:
- If the line matches 'commentstring', the comment markers are removed (e.g.
  `/*foo*/` is transformed to `foo`).
- Otherwise the comment markers are added to the current line (e.g. `foo` is
  transformed to `/*foo*/`). Blank lines are ignored.

Acting on multiple lines behaves as follows:
- If each affected non-blank line matches 'commentstring', then all comment
  markers are removed.
- Otherwise all affected lines are converted to comments; blank lines are
  transformed to empty comments (e.g. `/**/`). Comment markers are aligned to
  the least indented line.
```
