### ISSUE TITLE
make namespaces have global scope by default

### ISSUE THREAD

**Issue by altermo** [neovim/neovim#28469]
### Problem

I originally designed scoped namespaces to only be able to have window scopes. But now I think that having other types of scopes would be a good idea and also to be able to use namespace scopes for other objects like keymaps and autocmds.

The problem is that by default namespaces have no scopes, which means that when you want to apply a namespace scope to an object that has an associated namespace (like extmarks), one needs to set a `scoped` option to `true` to use the namespace scope. Setting an extra option feels a bit cumbersome (especially if scoped namespaces are implemented for other objects like autocmds (https://github.com/neovim/neovim/pull/28436)).

### Expected behavior

The proposed change is to make namespaces have by default a global scope.
(Note that global scoped namespaces haven't yet been implemented)
This means that if you want to only do some window scoped namespace, you first need to remove the global namespace.

If we don't want this to be a BREAKING-CHANGE then we can make it so that the `scoped` option for extmarks just skips the global scope check for namespaces.

What do you think? Is it better to make everything have an extra option to apply namespace scopes or is it better to require the removal of the global scope from a namespace?

**Comment by justinmk** [comment]
See also https://github.com/neovim/neovim/pull/28441
