### ISSUE TITLE
laststatus = 0 doesn't remove statusline from horizontal splits

### ISSUE THREAD

**Issue by paulhersch** [neovim/neovim#28488]
### Problem

I have set laststatus to 0, because i only want to have stuff in a winbar. This works fine, as long as i split vertically, as soon as i have a window split horizontally the statusline shows up on the "top" window (screenshot added).
To me the section in the docs on laststatus indicates, that this is not intended behaviour, which is why i am filing a bug report. I have not found similar issues in the currently open ones.

no horizontal split (all good):
![nohorizontalsplit](https://github.com/neovim/neovim/assets/74120050/4680a3df-32dc-4712-9649-b2092bfe1a4b)

with horizontal split (statusline visible on the right side):
![withhorizontalsplit](https://github.com/neovim/neovim/assets/74120050/f93c7e92-8c9e-42de-bd2b-3550c758e637)

(also another thing that kind of threw me off, was that one had to use vim.g.statusline_winid in the function for drawing the winbar, but thats alright to me, maybe add docs for that somewhere down the road to eliminate confusion?)

### Steps to reproduce

1. put stuff in your winbar globally (like "%t")
2. set laststatus to 0 globally

snippet i used for winbar:
```lua
    _G.winbar = M.winbar
    vim.opt.laststatus = 0
    o.winbar = "%!v:lua.winbar()"
```

### Expected behavior

I would expect the statusline to never show up when laststatus is set to 0

docs (options.txt):
```
	The value of this option influences when the last window will have a
	status line:
		0: never
```

### Neovim version (nvim -v)

NVIM v0.10.0-dev-35e3883 Build type: Release LuaJIT 2.1.1693350652

### Vim (not Nvim) behaves the same?

no idea

### Operating system/version

NixOS

### Terminal name/version

foot 1.16.2

### $TERM environment variable

xterm-256color

### Installation

nix neovim nightly overlay: https://github.com/nix-community/neovim-nightly-overlay

**Comment by zeertzjq** [comment]
This is working as intended. 'laststatus' only affects "last window".

**Comment by paulhersch** [comment]
> This is working as intended. 'laststatus' only affects "last window".

are 2 windows that are split horizontally not considered to be different windows, so shouldn't one of the vert splits not have a statusline as well?

**Comment by Shougo** [comment]
Please see this.
It describes why the statusline cannot be hidden completely.

https://github.com/neovim/neovim/issues/5626#issuecomment-1269189099
