### ISSUE TITLE
Docs: describe priority between editorconfig and autocmd like FileType

### ISSUE THREAD

**Issue by kaddkaka** [neovim/neovim#28484]
### Problem

`:h editorconfig` does not explain when and how the settings are applied, jus that it is automatic (in nvim 0.9.4).

It seems like it applies FileType autocmd first and then editorconfig after that - so that editorconfig has precedence. To override the editorconfig one can explicitly do `:set ft=python` for example.

### Expected behavior

The behavior should be described in the help page.

**Comment by wookayin** [comment]
Related #27425 (stale, closed)
