### ISSUE TITLE
Lsp goto definition loading buffer twice slow in 0.10 

### ISSUE THREAD

**Issue by xzbdmw** [neovim/neovim#28509]
### Problem

With barely lsp setup and nothing else, goto def takes 15~ 20ms in 0.10 and 5~ 8ms in 0.9.5, which is much laggy when treesitter also take part in.

### Steps to reproduce

init.lua
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"

-- vim.o.sessionoptions = "blank,buffers,curdir,help,tabpages,terminal,winsize,winpos,resize"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
	{
		"neovim/nvim-lspconfig",
		config = function()
			require("lspconfig")["rust_analyzer"].setup({})
		end,
	},
})

local start_time = nil

vim.api.nvim_create_autocmd("BufLeave", {
	callback = function()
		start_time = vim.loop.hrtime()
	end,
})
vim.keymap.set("n", "gd", function()
	vim.lsp.buf.definition()
end)

vim.api.nvim_create_autocmd("BufEnter", {
	callback = function()
		if start_time then
			local duration = 0.000001 * (vim.loop.hrtime() - start_time)
			-- __AUTO_GENERATED_PRINT_VAR_START__
			print([==[function duration:]==], vim.inspect(duration)) -- __AUTO_GENERATED_PRINT_VAR_END__
		end
	end,
})
```
2. take rust for example, which has the biggest lag feel
3. mkdir ~/deftest && cd ~/deftest
4. cargo new foo && nvim foo/src/main.rs
5. in function main add `Vec::new`
6. cursor on new and gd and see the print time
perf result 
[profile10.json version 0.10](https://github.com/neovim/neovim/files/15123325/profile.json)
[profile9.json version 0.9.5](https://github.com/neovim/neovim/files/15123328/profile2.json)
based on [profile.nvim](https://github.com/stevearc/profile.nvim)
The time is spend on `vim.lsp.buf_attach_client` and `FileType`
### Expected behavior

The time should not differ 2x

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2987+g3305bb9e4 Build type: RelWithDebInfo LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

don't know

### Operating system/version

macos 14.2 (m1)

### Terminal name/version

kitty latest

### $TERM environment variable

xterm-kitty

### Installation

github release page

**Comment by glepnir** [comment]
emm I tried a simple script result is different...

```lua
vim.api.nvim_create_autocmd("FileType", {
	pattern = "rust",
	callback = function(opt)
		vim.lsp.start({
			cmd = { "rust-analyzer" },
			root_dir = vim.fs.dirname(vim.fs.find("cargo.toml", { upward = true })[1]),
		}, { bufnr = opt.buf })
	end,
})

vim.keymap.set("n", "gd", function()
	local orignal_fn = vim.lsp.buf_attach_client
	vim.lsp.buf_attach_client = function(bufnr, client_id)
		local s = (vim.uv or vim.loop).hrtime()
		orignal_fn(bufnr, client_id)
		-- 0.9.5: 1743042
		-- 0.10 : 111875
		print((vim.uv or vim.loop).hrtime() - s)
	end
	vim.lsp.buf.definition()
end)
```

**Comment by xzbdmw** [comment]
> emm I tried a simple script result is different...
> 
> ```lua
> vim.cmd("syntax off")
> 
> vim.api.nvim_create_autocmd("FileType", {
> 	pattern = "rust",
> 	callback = function(opt)
> 		vim.lsp.start({
> 			cmd = { "rust-analyzer" },
> 			root_dir = vim.fs.dirname(vim.fs.find("cargo.toml", { upward = true })[1]),
> 		}, { bufnr = opt.buf })
> 	end,
> })
> 
> vim.keymap.set("n", "gd", function()
> 	local orignal_fn = vim.lsp.buf_attach_client
> 	vim.lsp.buf_attach_client = function(bufnr, client_id)
> 		local s = (vim.uv or vim.loop).hrtime()
> 		orignal_fn(bufnr, client_id)
> 		-- 0.9.5: 1743042
> 		-- 0.10 : 111875
> 		print((vim.uv or vim.loop).hrtime() - s)
> 	end
> 	vim.lsp.buf.definition()
> end)
> ```

I test it and it shows 249167 in 0.9.5 and 1082250 in 0.10, with nvim -u NORC -u. not sure why.

**Comment by xzbdmw** [comment]
My bad, I try with an old version of 0.10 that is two month ago, with the newest one, it is faster in 
https://github.com/neovim/neovim/issues/28509#issuecomment-2078882150
and with this script without lspconfig
```lua
local start_time = nil

vim.api.nvim_create_autocmd("BufLeave", {
	callback = function()
		start_time = vim.loop.hrtime()
	end,
})
vim.keymap.set("n", "gd", function()
	vim.lsp.buf.definition()
end)

vim.api.nvim_create_autocmd("BufEnter", {
	callback = function()
		if start_time then
			local duration = 0.000001 * (vim.loop.hrtime() - start_time)
			-- __AUTO_GENERATED_PRINT_VAR_START__
			print([==[function duration:]==], vim.inspect(duration)) -- __AUTO_GENERATED_PRINT_VAR_END__
		end
	end,
})
```
their time is the same

but the orignal script with lspconfig is still 2x slower, so the problem is in lspconfig.

**Comment by glepnir** [comment]
lspconfig has an extra check here. Since the jump to stdlib needs to check some paths and workspace clients reuse.
