### ISSUE TITLE
After attaching ext_messages, `'cmdheight'` is set to zero for current tabpage only

### ISSUE THREAD

**Issue by Sam-programs** [neovim/neovim#28526]
### Problem

After attaching ext_messages, `'cmdheight'` is set to zero for current tabpage only. And When switching to other tabpages, The statusline becomes duplicated (one on the bottom row and one above that).

Ref https://github.com/folke/noice.nvim/issues/775

### Steps to reproduce

nvim --clean -u minimal.lua

```lua
-- minimal.lua
vim.cmd("tabnew")
vim.ui_attach(vim.api.nvim_create_namespace("a"), { ext_messages = true }, function() end)
vim.schedule(function()
    vim.cmd("tabNext")
end)
```

### Expected behavior

When attaching ext_messages `'cmdheight'` is set to 0 in every tab.

Context:
This is the code for setting `'cmdheight'`.
https://github.com/neovim/neovim/blob/688860741589b4583129e426f4df0523f9213275/src/nvim/ui.c#L231-L234

https://github.com/neovim/neovim/blob/688860741589b4583129e426f4df0523f9213275/src/nvim/option.c#L174-L178

### Neovim version (nvim -v)

current master (https://github.com/neovim/neovim/commits/688860741589b4583129e426f4df0523f9213275))

### Vim (not Nvim) behaves the same?

No external ui in vim.

### Operating system/version

Linux ArchLinux 6.8.1-arch1-1

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

wezterm

### Installation

`make` on master

**Comment by luukvbaal** [comment]
Thanks for the clear repro steps, #28522 should fix this.
