### ISSUE TITLE
New lsp keybindings: `crr` in visual mode breaks visual selection -> `c` workflow

### ISSUE THREAD

**Issue by p00f** [neovim/neovim#28528]
### Problem

The new lsp keybindings include `crr` in visual mode for code actions. This breaks the visual mode -> `c` workflow because the user now has to wait for `timeoutlen`.

### Steps to reproduce

After a server has attached, select some text, then press `c`

### Expected behavior

Selected text is gone and nvim is in insert mode immediately

### Neovim version (nvim -v)

0.10.0 commit 9b8a0755390b7eb3ad369f3a0a42eb9aecb8cbe2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

**Comment by gpanders** [comment]
Probably should at the very least revert the visual mode `crr` mapping. @mfussenegger pointed out that not being able to use the same mapping for normal and visual modes is not great, so perhaps we need a separate mapping for code actions.

**Comment by mfussenegger** [comment]
Some options mentioned in chat:

- Don't map visual mode, but that means users have to map it themselves to a different key and they're left with the asymmetry
- `ga` (current function is redundant with `:ascii`)
- `gb`, `gz` or `g.`, but all lack mnemonic 
- `<alt-cr>` (used by some, it's the default keymap for quick-fix in intellij, which behaves similar)
- `<c-g>` (currently `:file`)

**Comment by gpanders** [comment]
`<M-CR>` would be my preference (it's what I use today, no I am not biased). We have never added a default Alt binding before so this would be a new precedent, but I'm not aware of any compelling argument against it. Helix and Kakoune have both demonstrated that using Alt mappings works perfectly well.

The only risk I can think of is that the default value of `'ttimeoutlen'` might be too low on some very slow network connections. But I don't have any data to support that this is a real potential issue, it's just the only thing I can think of.

**Comment by justinmk** [comment]
why not `ctrl-r` ?

**Comment by p00f** [comment]
ctrl-r is for redo, unless you mean only for visual mode, which would be assymetric

**Comment by ofseed** [comment]
IMAO `z` as a prefix, e.g. `z-` or `zd` would be great.

`z=` and `zw` are used for the builtin spelling check, in some aspects it can be said to be very similar to code action because code actions usually be used to fix diagnostic errors.

If we use `z-`, its function and key position could be similar to `z=`; and if we use `zd`, then we have the mnemonic d for diagnosis.

Most importantly, in this way, we can unify the key mapping in insert and visual modes.

**Comment by justinmk** [comment]
>> why not `ctrl-r` (mnemonic: "refactor")? The builtin `:help v_CTRL-R` is only for select-mode, not visual mode.
>
> ctrl-r is for redo, unless you mean only for visual mode, which would be assymetric

Almost all visual mappings are "asymmetric". `cr` is an excellent mnemonic because this mapping family is related to "change". Throwing out `cr` just because of visual mode is not a good tradeoff.
