### ISSUE TITLE
Lua: vim.keymap.set(mode, opts, lhs, rhs)

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#28536]
## Problem

keymap.set has a suboptimal signature, it could be improved

## Expected behavior

- add an overloaded signature so that the `rhs` can be the last arg. ~~function keymap.set(mode, lhs, opts, rhs)~~ **Update:** `function keymap.set(mode, opts, lhs, rhs)`
    - Callback should always be the last arg, where possible. That is a readability enhancement and a project standard.
    - The old signature is still supported.
- ~~`lhs` can be a list. This reduces boilerplate when defining aliases for a mapping.~~

### Comparison

Before:

    vim.keymap.set('n', 'crr', function()
      vim.lsp.buf.code_action()
    end, { desc = 'vim.lsp.buf.code_action()' })

After (opts is now arg 2 instead of arg 4):

    vim.keymap.set('n', { desc = 'vim.lsp.buf.code_action()' }, 'crr', function()
      vim.lsp.buf.code_action()
    end)

**Comment by justinmk** [comment]
What is the objection to this?

**Comment by clason** [comment]
Personally, I don't see the benefit, so the churn seems not worth it. And it conflicts with the (in my opinion stronger) project standard of "optional keyword-style arguments last".

**Comment by mfussenegger** [comment]
No objection from my side, but I suspect part of the objection is that in most personal keymaps people just don't set a description, so they already have:

```lua
vim.keymap.set('n', 'crr', function()
  vim.lsp.buf.code_action()
end)
```

And with this change they'd have to write:

```lua
vim.keymap.set('n', 'crr', nil, function()
  vim.lsp.buf.code_action()
end)
```


The nudge towards adding a description might not be the worst, but imho there's no clear advantage to the proposed change for most users.
Besides, in this particular case one could just write:

```lua
vim.keymap.set('n', 'crr', vim.lsp.buf.code_action, { desc = 'vim.lsp.buf.code_action()' })
```

Opposed to autocmds, keymaps don't (yet?) provide a context as arguments, so using the function reference is currently save.

**Comment by justinmk** [comment]
> And with this change they'd have to write:
> 
> ```lua
> vim.keymap.set('n', 'crr', nil, function()
>   vim.lsp.buf.code_action()
> end)
> ```

good point. so instead, I have updated the proposal to be an overload instead of deprecating the old form.

**Comment by fishioon** [comment]
> Opposed to autocmds, keymaps don't (yet?) provide a context as argument to the called function, so using the function reference is currently save.

Good idea. Now When 'rhs' need to pass argument, we have to define new functions, which is very verbose and inelegant.

**Comment by justinmk** [comment]
Revised to make `opts` parameter 2, and this is just an overload so the old signature is still supported.

**Comment by justinmk** [comment]
Decided to reject this based on:

- https://github.com/neovim/neovim/pull/30511#discussion_r1775105985
- https://github.com/neovim/neovim/pull/30511#discussion_r1775162597

**Comment by dundargoc** [comment]
> It bugs me that the order is different than :nnoremap, but it doesn't seem to bother anyone else...

I think you're underestimating the mental context switch cost between vimscript and lua for most people. I think we discussed something similar with the `vim.echo` vs `vim.print` discussion: constistency per language (lua and lua API) is stronger/more important than consistency between vimscript and lua in my opinion. This is of course personal (because I would not be writing this otherwise), but I'm willing to wager many others feel this way as well. I think you overestimate people's vimscript know-how.

**Comment by justinmk** [comment]
I only mention `:nnoremap` in this case because its argument order has some logic to it. It's a case where being different isn't necessarily better.

**Comment by dundargoc** [comment]
> I never insist that we match vimscript everywhere

I know, just wanted to provide a perspective since it seemed you were somewhat taken aback why the discrepancy with `:noremap` didn't seem to bother people much.
