### ISSUE TITLE
vim.snippet: merge jumpable() with active()

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#28548]
### Problem

`vim.snippet.jumpable()` is a strange name and overlaps with `active()`.

### Expected behavior

change the signature of `vim.snippet.active()` to accept an optional `filter: { jump_dir: vim.snippet.Direction }` parameter which constrains the search to "jumpable" active snippet in the given direction.

@MariaSolOs is there any reason this would not make sense?

**Comment by justinmk** [comment]
Is it likely that we will want `vim.snippet.get()` in the future?

**Comment by clason** [comment]
> vim.snippet.jumpable() is a strange name and overlaps with active().

These are very different things. I feel we are rehashing discussions we've already had on the original PR.

**Comment by justinmk** [comment]
> > vim.snippet.jumpable() is a strange name and overlaps with active().
> 
> These are very different things.

How is anyone supposed to figure that out based on the documentation? The documentation doesn't imply any difference, it simply uses the word "active" for both cases.

```
vim.snippet.active()                                    *vim.snippet.active()*
    Returns `true` if there's an active snippet in the current buffer.

vim.snippet.jump({direction})                             *vim.snippet.jump()*
    Jumps within the active snippet in the given direction. If the jump isn't
    possible, the function call does nothing.
```


> I feel we are rehashing discussions we've already had on the original PR.

Yes, I thought so too. But the docs need to be improved then.

**Comment by MariaSolOs** [comment]
@justinmk We can indeed merge `jumpable` into `active`. However I feel like it might not change with the ease of use around the API because of some cases like: If the cursor is modifying the one and only tabstop in a snippet, then `jumpable(1)` and `jumpable(-1)` are both false but `active()` should return true. So here the union of `jumpable(d) for each d in direction` is not equal to `active()`, which feels a bit odd imo.

**Comment by justinmk** [comment]
> If the cursor is modifying the one and only tabstop in a snippet, then `jumpable(1)` and `jumpable(-1)` are both false but `active()` should return true. 

in that case the results would be:

```lua
active()   -- true
active(-1) -- false
active(1)  -- false
```

right? seems clear to me. `active()` gives a different result when its search space is filtered. That works like any other filter.

**Comment by MariaSolOs** [comment]
> right? seems clear to me. `active()` gives a different result when its search space is filtered. That works like any other filter.

Right, but there's no filter combination that matches the unfiltered result, which I find a bit odd. I might be overthinking it though, I'm truly indifferent about removing `vim.jumpable` or not.
