### ISSUE TITLE
Executing `:highlight clear` in headless process can lead to not proper screen state

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#28549]
### Problem

After 7626f431d84fc3a6eb82d0d23d436e3e31e991ce executing `:highlight clear` inside a headless process can lead to not proper screen state.

### Steps to reproduce

1. Source the following script with `nvim` executable pointing to the latest `main`:
```lua
-- Set up headless child process
local pipe = vim.fn.tempname()
local args = { 'nvim', '--clean', '-n', '--listen', pipe, '--headless', '--cmd', 'set lines=10 columns=40' }
vim.fn.jobstart(args)

vim.loop.sleep(100)
local channel = vim.fn.sockconnect('pipe', pipe, { rpc = true })

-- Execute `hi clear` command
vim.rpcrequest(channel, 'nvim_command', 'highlight clear')

-- Get screenshot
local get_screenshot_lua_cmd = [[
  local text = {}
  for i = 1, vim.o.lines do
    local text_line = {}
    for j = 1, vim.o.columns do
      table.insert(text_line, vim.fn.screenstring(i, j))
    end
    table.insert(text, table.concat(text_line))
  end
  return text
]]
local screenshot = vim.rpcrequest(channel, 'nvim_exec_lua', get_screenshot_lua_cmd, {})

-- Close child process
vim.rpcnotify(channel, 'nvim_command', 'qall!')

-- Show screenshot lines
vim.cmd('enew')
vim.api.nvim_buf_set_lines(0, 0, -1, false, screenshot)
```

On `main` (4625394a767fab311f75ef40f4f15c661156e071) this gives me the following output:
```
                                        
~                                       
~                                       
~                                       
~                                       
~                                       
~                                       
~                                       
[No Name]             0,0-1          All
[No Name]             0,0-1          All
```

------

Applying the following patch (basically negating the change in 7626f431d84fc3a6eb82d0d23d436e3e31e991ce) fixes this issue:

```patch
diff --git a/src/nvim/ui.c b/src/nvim/ui.c
index 27458d588b..af6fc1b503 100644
--- a/src/nvim/ui.c
+++ b/src/nvim/ui.c
@@ -194,6 +194,10 @@ void ui_refresh(void)
     abort();
   }
 
+  if (!ui_active()) {
+    return;
+  }
+
   int width = INT_MAX;
   int height = INT_MAX;
   bool ext_widgets[kUIExtCount];
@@ -232,10 +236,6 @@ void ui_refresh(void)
     }
   }
 
-  if (!ui_active()) {
-    return;
-  }
-
   if (updating_screen) {
     ui_schedule_refresh();
     return;
```

Now the script output is as expected (there is an empty line in place of Command line):
```
                                        
~                                       
~                                       
~                                       
~                                       
~                                       
~                                       
~                                       
[No Name]             0,0-1          All
                                        
```

### Expected behavior

Executing `:highlight clear` never results into an improper screen state.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3026+ga41546d4a

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.8.7-arch1-2)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

Both appimage and from source

**Comment by luukvbaal** [comment]
Right, https://github.com/neovim/neovim/commit/7626f431d84fc3a6eb82d0d23d436e3e31e991ce incorrectly assumed the 2 for loops for remote UIs would have no effect with `ui_count == 0`.
I think this should fix the issue:

```diff
--- a/src/nvim/ui.c
+++ b/src/nvim/ui.c
@@ -198,7 +198,7 @@ void ui_refresh(void)
   int height = INT_MAX;
   bool ext_widgets[kUIExtCount];
   for (UIExtension i = 0; (int)i < kUIExtCount; i++) {
-    ext_widgets[i] = true;
+    ext_widgets[i] = ui_active();
   }

   bool inclusive = ui_override();
```

**Comment by echasnovski** [comment]
> Right, [7626f43](https://github.com/neovim/neovim/commit/7626f431d84fc3a6eb82d0d23d436e3e31e991ce) incorrectly assumed the first 2 for loops for in `ui_refresh()` would have no effect with `ui_count == 0`. I think this should fix the issue:
> 
> ```diff
> --- a/src/nvim/ui.c
> +++ b/src/nvim/ui.c
> @@ -198,7 +198,7 @@ void ui_refresh(void)
>    int height = INT_MAX;
>    bool ext_widgets[kUIExtCount];
>    for (UIExtension i = 0; (int)i < kUIExtCount; i++) {
> -    ext_widgets[i] = true;
> +    ext_widgets[i] = ui_active();
>    }
> 
>    bool inclusive = ui_override();
> ```

I can (cautiously) confirm that this patch fixes the reported issue and all the real ones I have on current Nightly.

**Comment by echasnovski** [comment]
Thanks, Luuk! Latest Nightly build indeed does not have the "real world" issues I saw earlier.
