### ISSUE TITLE
Using clip in wsl2 can cause problems

### ISSUE THREAD

**Issue by ipsfsw** [neovim/neovim#28567]
### Problem

if vim.fn.has("wsl") == 1 then
  vim.g.clipboard = {
    name = "win-clip.exe",
    copy = {
      ["+"] = "clip.exe",
      ["*"] = "clip.exe",
    },
    paste = {
      ["+"] = 'powershell.exe -NoProfile -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
      ["*"] = 'powershell.exe -NoProfile -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
    },
    cache_enable = 0,
  }
end

This is my neovim clip configuration, if possible, please also add a parameter of -NoProfile -c to the pwsh command in wsl, because the default version of pwsh in windows is 5.x, but the latest pwsh is 7.x, if you use some plug-ins, do not support 5.x. Loading the configuration will fail, so replication will fail at this time.

### Steps to reproduce

sudo nvim /etc/bash..bashrc

key : yy 
result : error , not clip 

### Expected behavior

copy 

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

windows 11 

### Terminal name/version

wsl2

### $TERM environment variable

xxx

### Installation

ubuntu 22.04

**Comment by justinmk** [comment]
> 0.9.1

the latest stable release is 0.9.5

try 0.10 also

**Comment by xudyang1** [comment]
@ipsfsw 

If `clip.exe` is not detected in WSL2, you may have `appendWindowsPath=false` in your `/etc/wsl.config`. To use executable on Windows host, you have to use the full path from '/mnt/c/':

```lua
if vim.fn.has("wsl") == 1 then
  local copy = { "/mnt/c/Windows/System32/clip.exe" }
  local paste = {
    "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe",
    "-NonInteractive",
    "-NoProfile",
    "-NoLogo",
    "-c",
    '[Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
  }
  -- Linux (WSL2) using host clipboard
  vim.g.clipboard = {
    name = "WslClipboard",
    -- use win32yank.exe from windows neovim
    copy = {
      ["+"] = copy,
      ["*"] = copy,
    },
    paste = {
      ["+"] = paste,
      ["*"] = paste,
    },
    cache_enabled = false,
  }
end
```
