### ISSUE TITLE
Improve spell checking by ignoring identifiers. 

### ISSUE THREAD

**Issue by s4my** [neovim/neovim#28583]
### Problem

Currently, [`identifiers`](https://en.wikipedia.org/wiki/Identifier_(computer_languages)) are flagged as misspellings if they are inside a comment. For example, if we have the following code:
```c
#include <stdio.h>

int main()
{
    int my_var; // my_var is used for blah
}
```
`my_var` in the comment will be flagged as a misspell.

### Expected behavior

It would be really nice if the spell checker ignored `identifiers`.

**Comment by clason** [comment]
How would the spell checker know that this is an identifier and not a misspelled actual word?

**Comment by justinmk** [comment]
This can work when the identifier is marked up as a reference, e.g. `{@link foo}`. That might already work, with `:help treesitter-highlight-spell`

**Comment by s4my** [comment]
> This can work when the identifier is marked up as a reference, e.g. `{@link foo}`. That might already work, with `:help treesitter-highlight-spell`

OK, I didn't event had a chance to respond, holy shit.

**Comment by s4my** [comment]
> How would the spell checker know that this is an identifier and not a misspelled actual word?

I was thinking what if we support markdown code blocks, so if you have the identifier surrounded by back ticks, it'll be ignored.

**Comment by clason** [comment]
That's not how tree-sitter works, sorry.
