### ISSUE TITLE
resolv doesn't recognise `search .` and `trust-ad`

### ISSUE THREAD

**Issue by Mikaela** [neovim/neovim#28588]
### Problem

My `/etc/resolv.conf` is:

```resolv.conf
nameserver ::1
nameserver 127.0.0.1
nameserver 127.0.0.53
search .
options timeout:2 attempts:2 rotate edns0 trust-ad
```

Neovim paints the `.` and `trust-ad` as red.

![Screenshot](https://github.com/neovim/neovim/assets/831184/9b9ac89e-ab3a-4f20-b84d-b487204b5957)

### Steps to reproduce

Edit `/etc/resolv.conf` including `search .` or `options trust-ad` 

### Expected behavior

- The `search .` won't have the `.` painted as red as it's valid for avoiding having search domains and possibly sending queries such as `example.nett.example.com` to upstream resolver.
- The `options` line won't have the `trust-ad` painted as red as it has been around for years.

### Neovim version (nvim -v)

v0.9.5

### Vim (not Nvim) behaves the same?

yes, VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Apr 19 2024 00:00:00)

### Operating system/version

Fedora Linux 40 (Forty)

### Terminal name/version

foot version: 1.17.2 -pgo +ime +graphemes -assertions

### $TERM environment variable

tmux-256color (tmux 3.4)

### Installation

system package manager

**Comment by clason** [comment]
Please check `set filetype?` and then contact the maintainer listed at the top of `runtime/syntax/<filetype>.vim`.
