### ISSUE TITLE
No colours when using command filter

### ISSUE THREAD

**Issue by carbolymer** [neovim/neovim#28589]
### Problem

Neovim does not display colours when rendering output from filter command.

### Steps to reproduce

1. Start clean neovim: `nvim --clean`
2. Run the command `:!echo -e "\033[31mfoo\033[0m"`
3. Neovim prints: 
  ```
  :!echo -e "\033[31mfoo\033[0m"                                                                                                           
    ^[[31mfoo^[[0m
  ```

### Expected behavior

Neovim prints `foo` in red.

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release

### Vim (not Nvim) behaves the same?

No, vim prints colours. VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Apr 18 2024 16:54:46) Included patches: 1-346

### Operating system/version

Archlinux

### Terminal name/version

kitty 0.33.1

### $TERM environment variable

xterm-256color

### Installation

arch extra repository

**Comment by clason** [comment]
`:!` is not a full-featured terminal emulator. Use `:term` instead.

**Comment by carbolymer** [comment]
The issue is that I'm not seeing colours in fugitive, which I imagine is using filter underneath. For example I have a `git hist` alias which prints coloured git log for me. So `:Git hist` prints just text, without colouring.

**Comment by clason** [comment]
That's a different issue, and one you have to raise with fugitive. Neovim's `:!` is (intentionally, for technical reasons) different from Vim's. If you need a full terminal emulator for things like escape sequences, you _need_ to use `:term`.
