### ISSUE TITLE
mksession does not work with split terminal buffers

### ISSUE THREAD

**Issue by rkannan82** [neovim/neovim#2861]
1. Launch nvim on Mac and create terminal buffer using -> :terminal
2. Create a split window using -> :sp term://bash
3. Save session using -> :mksession test.vim
4. Exit nvim and launch using -> nvim -S test.vim
You will see an error for the terminal buffer.

On a related note, a terminal buffer can only be deleted by overriding with !. This is causing problems for plugins that are used to manage buffers. For e.g., I use bufexplorer. I can view list of buffers and press 'd' to delete a buffer. But, this won't work for terminal buffer. Need some inputs.

**Comment by vito-c** [comment]
+1 I am having issues with named terminal buffers and window splits.
steps to reproduce

1. Launch neovim
2. set my sessionopts-=tabpages
3. tabnew | call termopen('bash',{"name","foo-one"})
3. vnew | call termopen('bash',{"name","foo-two"})
4. :mksession ~/session.vim
5. Change the window layout
   * :tabclose 
   * `<c-w>o`
6. source ~/session.vim

Result:
One of the terminals fails to load correctly:

    /usr/local/bin/bash: foo-one: command not found
    [Program exited, press any key to close]

Expected:
The window layout should be restored and terminal buffers should not be closed.

**Comment by justinmk** [comment]
"name" is not a supported feature anymore. See https://github.com/neovim/neovim/pull/3181

Maybe worth discussing some other convention for showing a "friendly" name in the statusline, but the buffer name itself should be an actual URI just like any other buffer.

Should be fixed on latest master.

**Comment by vito-c** [comment]
The buffer name was still a uri with the name feature. I don't understand why this feature was removed. I will comment on the corresponding ticket.

**Comment by justinmk** [comment]
> it was still a uri with the buffer name feature.

It was not a URI in the sense that a `['zsh', '-c', 'ls']` invocation named "ls" loses information: when the buffer is restored it will use the default `&shell` instead of `'zsh'`.
