### ISSUE TITLE
vim.json.decode(..., {luanil={object=false, array=false}}) replaces vim.NIL

### ISSUE THREAD

**Issue by aktersnurra** [neovim/neovim#28619]
### Problem

When you provide the luanil table to the vim.json.decode function, irrespective of the boolean value provided, all key-value pairs with value null are removed in the output. See examples below:

```lua
vim.json.decode('{"bar":[],"foo":{},"zub":null}', { luanil = { object = true, array = true }})
```

outputs:

```lua
{
  bar = {},
  foo = vim.empty_dict()
}
```

```lua
vim.json.decode('{"bar":[],"foo":{},"zub":null}', { luanil = { object = true, array = false }})
```

outputs:

```lua
{
  bar = {},
  foo = vim.empty_dict()
}
```

```lua
vim.json.decode('{"bar":[],"foo":{},"zub":null}', { luanil = { object = false, array = true }})
```

outputs:

```lua
{
  bar = {},
  foo = vim.empty_dict()
}
```

```lua
vim.json.decode('{"bar":[],"foo":{},"zub":null}', { luanil = { object = false, array = false }})
```

outputs:

```lua
{
  bar = {},
  foo = vim.empty_dict()
}
```

```lua
vim.json.decode('{"bar":[],"foo":{},"zub":null}', { luanil = { }})
```

outputs:

```lua
{
  bar = {},
  foo = vim.empty_dict(),
  zub = vim.NIL
}
```

### Steps to reproduce

```lua
:lua vim.json.decode('{"bar":[],"foo":{},"zub":null}', { luanil = { object = true, array = true }})
```

### Expected behavior

Expected behavior is:

```lua
vim.json.decode('{"bar":[],"foo":{},"zub":null}', { luanil = { object = true, array = true }})
```

outputs:

```lua
{
  zub = nil,
  bar = {},
  foo = vim.empty_dict()
}
```

### Neovim version (nvim -v)

v0.10.0-dev-3070+gcf9f002f3

### Vim (not Nvim) behaves the same?

idk

### Operating system/version

14.3.1 (23D60)

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

n/a

### Installation

build from repo

**Comment by zeertzjq** [comment]
`:h lua-table`
```
The type `table` implements associative arrays, that is, arrays that can be
indexed not only with numbers, but with any value (except `nil`). Tables can
be heterogeneous; that is, they can contain values of all types (except
`nil`).
```

**Comment by aktersnurra** [comment]
Then the documentation needs to be updated since it states:

```
{opts} [is](https://neo.vimhelp.org/motion.txt.html#is) [a](https://neo.vimhelp.org/insert.txt.html#a) table with the key `luanil [=](https://neo.vimhelp.org/change.txt.html#%3D) { object: bool, array: bool }`
    that controls whether null in JSON [objects](https://neo.vimhelp.org/index.txt.html#objects) or arrays should be converted
    to [Lua](https://neo.vimhelp.org/lua.txt.html#Lua) nil instead of vim.NIL.
```

**Comment by justinmk** [comment]
> Then I suppose the documentation needs to be updated since it states:

Which part of the doc is wrong? 

You can try your expected result directly in Lua, without involving vim.json.decode():

    lua vim.print({ zub = nil, bar = {}, foo = vim.empty_dict() })

that prints:

    {                                                                                                                                                                                                                    
      bar = {},                                                                                                                                                                                                          
      foo = vim.empty_dict()                                                                                                                                                                                             
    }

**Comment by justinmk** [comment]
> But is it not strange that if I run this configuration:
> 
> ```lua
> vim.json.decode('{"bar":[],"foo":{},"zub":null}', { luanil = { object = false, array = false }})
> ```
> 
> I still get:
> 
> ```
> {
>   bar = {},
>   foo = vim.empty_dict()
> }
> ```

that does seem like a bug

**Comment by zeertzjq** [comment]
It seems that these aren't actually boolean keys. Setting them to any value except `nil` behaves like `true`.

**Comment by clason** [comment]
Yep, they're `int`s under the hood: https://github.com/neovim/neovim/blob/40ce8577977fcdce8ad76863c70eb522e4cefd4d/src/cjson/lua_cjson.c#L152-L173

It Is The (Vim) Way. Since we have vendored this and made changes already, should we refactor?

**Comment by zeertzjq** [comment]
> Yep, they're `int`s under the hood:
> 
> https://github.com/neovim/neovim/blob/40ce8577977fcdce8ad76863c70eb522e4cefd4d/src/cjson/lua_cjson.c#L175-L180
> 
> It Is The (Vim) Way. Since we have vendored this and made changes already, should we refactor?

This has nothing to do with the behavior.

**Comment by zeertzjq** [comment]
Upstream doesn't have `luanil`. It's an Nvim addition.

**Comment by clason** [comment]
Yes, that was my point. But never mind.
