### ISSUE TITLE
OSC52 very slow in Windows Terminal (workaround provided)

### ISSUE THREAD

**Issue by tgbrooks** [neovim/neovim#28611]
### Problem

Windows Terminal supports OSC52-base copying but not pasting (for security reasons). Using the new OSC52 support in nvim 0.10 works in Windows Terminal however it is very slow (over 10 seconds). The apparent cause of this is that yanking actually first attempts a *paste*, which isn't supported and so times out, and only afterwards performs the copy.

Therefore, there is a simple way to resolve this problem for users. Instead of the currently recommended configuration to force OSC52 to be used, instead do the following which makes pasting a no-op (since it wouldn't work anyway):

``` lua
function no_paste(reg)
    return function(lines)
        -- Do nothing! We can't paste with OSC52
    end
end

vim.g.clipboard = {
    name = "OSC 52",
    copy = {
         ["+"] = require("vim.ui.clipboard.osc52").copy("+"),
         ["*"] = require("vim.ui.clipboard.osc52").copy("*"),
    },
    paste = {
        ["+"] = no_paste("+"), -- Pasting disabled
        ["*"] = no_paste("*"), -- Pasting disabled
    }
}
```

After doing this, copying is immediate. This seems counter intuitive and I don't understand why the paste function is called when yanking (it appears to be called twice: if you replace my `no_paste` function with something that prints out, you'll see it).

Presumably, this work around would help any other terminal that supports OSC52 copying but not pasting, apparently including wezterm/alacritty, but I have not tested. See also this discussion: #28010 I have also seen this problem [mentioned elsewhere](https://www.reddit.com/r/neovim/comments/17rbbec/neovim_nightly_now_you_can_copy_via_ssh_with/).

### Steps to reproduce

Using Windows Terminal, ssh to a machine with neovim 0.10. (Or any other situation where OSC52 is used.) Run nvim and yank a line of text, `"+yy`. Neovim then hangs for a second and eventually displays a message that it timed out waiting for a response from the terminal.

### Expected behavior

Yanking to clipboard should be instantaneous even if paste is not available.

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Windows 11 (Terminal) / Linux (nvim)

### Terminal name/version

Windows Terminal Version: 1.19.10821.0

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by justinmk** [comment]
> This seems counter intuitive and I don't understand why the paste function is called when yanking

Hmm. And this happens with `nvim --clean` ?

**Comment by tgbrooks** [comment]
No, it doesn't! Apologies for not checking that before submitting. Must be something in LazyVim then.

**Comment by MrZLeo** [comment]
@tgbrooks I don't use which-key plugin, but I met the same problem

**Comment by zevelix** [comment]
I ran into this problem as well with WezTerm and Windows Terminal both using --clean(though I had to make a minimal init for Windows Terminal to force OSC52).

**Comment by tgbrooks** [comment]
And this happens when yanking not just when pasting? If so, I would recommend modifying the `no_paste` function in my example so that a traceback is printed out whenever paste is performed. That way you can find what's calling `paste`. That's how I figured out it was `which-key` for me.

**Comment by zevelix** [comment]
No, sorry, I didn't read your issue thoroughly enough. My issue is just with things like the :registers command and which-key's `"` keybind. Since the '+' and '*' registers are automatically enabled if a working clipboard tool is found, and, as you mentioned, not all terminals permit querying with OSC 52, I've been experiencing the timeouts. I figure you could get which-key to behave as the registers.lua module sets a string of all register names and then loops through it calling getreg(). Then maybe a workaround would be to just omit those two registers from the string. The :registers command though I don't know as it seems to try to read '+' and '*' even when you specify other registers like `:reg 1`

**Comment by cycode0527** [comment]
Thanks for the useful idea! But when I use your function, it will echo a red error like `clipboard: provider returned invalid data ` . I have to return a valid param to nvim, but I cannot return an empty string like `""` simply. So I return the content from the default register: `"`.
The following is my config:
```lua
function my_paste(reg)
    return function(lines)

        --[ 返回 “” 寄存器的内容，用来作为 p 操作符的粘贴物 ]
        local content = vim.fn.getreg('"')
        return vim.split(content, '\n')
        
    end
end

if (os.getenv('SSH_TTY') == nil)
then
    --[ 当前环境为本地环境，也包括 wsl ]
    opt.clipboard:append("unnamedplus")
else
    opt.clipboard:append("unnamedplus")
    vim.g.clipboard = {
      name = 'OSC 52',
      copy = {
        ['+'] = require('vim.ui.clipboard.osc52').copy('+'),
        ['*'] = require('vim.ui.clipboard.osc52').copy('*'),
      },
      paste = {
        --[ 小括号里面的内容可能是毫无意义的，但是保持原样可能看起来更好一点 ]
        ["+"] = my_paste("+"),
        ["*"] = my_paste("*"),


    },
}
end
```

**Comment by allpan3** [comment]
Does anyone use [yanky.nvim](https://github.com/gbprod/yanky.nvim) out here? The workaround above apparently breaks the plugin - I'm no longer able to cycle through the history. After some debugging I found that `setreg` function isn't able to set the `"+` register, which isn't the case when I use the osc52 paste.

But I'm having trouble figuring the out the issue beyond this observation.
