### ISSUE TITLE
inlay_hint `enable(<no args>)` does not activate inlay hints on open buffers

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#28624]
### Problem

regression from https://github.com/neovim/neovim/pull/28523 or https://github.com/neovim/neovim/pull/28543

```lua
vim.lsp.inlay_hint.is_enabled()  -- false (this is expected ✅)
vim.lsp.inlay_hint.enable()  -- enable globally. But inlay hints are not shown (wrong ❌)
vim.lsp.inlay_hint.is_enabled()  -- true (ok ✅)
vim.lsp.inlay_hint.is_enabled({bufnr=0}) -- true (ok ✅)
```

### Workarounds

- passing an explicit bufnr activates inlay hints in existing visible buffers: `vim.lsp.inlay_hint.enable(true, {bufnr=0})`
- reloading a buffer with `:edit` activates the hints

### Expected behavior

`vim.lsp.inlay_hint.enable(nil|true)` should activate inlay hints for open buffers

**Comment by mehalter** [comment]
Ah it looks like we opened issues separately regarding similar things with `vim.lsp.inlay_hint` (#28625). I actually didn't even see if the inlay hints actually get displayed in my issue and just referred to the incorrect state behavior of the enabling. Let me know if we should consolidate my issue into this to centralize bugs with the new API.

**Comment by mehalter** [comment]
I will move over the case I found here:

```lua
vim.lsp.inlay_hint.is_enabled() -- false (ok ✅)
vim.lsp.inlay_hint.enable(true) -- enable globally
vim.lsp.inlay_hint.is_enabled() -- true (ok ✅)
vim.lsp.inlay_hint.is_enabled({ bufnr = 0 }) -- true (ok ✅)
vim.lsp.inlay_hint.enable(false, { bufnr = 0 })
vim.lsp.inlay_hint.is_enabled({ bufnr = 0 }) -- true (wrong ❌)
```

**Comment by ofseed** [comment]
https://github.com/neovim/neovim/pull/28627 should fix the case @mehalter provided, I'm not sure if it fixes the problem @justinmk is having.

**Comment by ofseed** [comment]
@justinmk I still can't find how to reproduce, can you please provide a more detailed use case?

**Comment by justinmk** [comment]
> can you please provide a more detailed use case?

1. open a file which has a LSP server that provides inline hints.
2. run `lua vim.lsp.inlay_hint.enable()`
3. inlay hints not displayed.
4. reload the buffer with `:edit`, now the inlay hints are displayed.

**Comment by mehalter** [comment]
Hm, I can't replicate this at all either, tested with https://github.com/neovim/neovim/commit/52823616bc4d77898ddc03da7629280841d3bced as well

As soon as I run `lua vim.lsp.inlay_hint.enable()` it shows the inlay hints (assuming the language server is fully loaded). What language server are you testing it with @justinmk ?

**Comment by justinmk** [comment]
`clangd`, opening `main.c` from Nvim source tree. This didn't happen until the recent changes.

**Comment by ofseed** [comment]
> This didn't happen until the recent changes.
This may be important information. Rather than reload the buffer by `:edit`, do inlay hints appear when you modify the document?

**Comment by justinmk** [comment]
> Rather than reload the buffer by `:edit`, do inlay hints appear when you modify the document?

yes

**Comment by sergeken** [comment]
Also, it might take time before the inlay hints are shown.  I've this experience with a rust project that has a few "heavy" dependencies and rust_analyzer is "chewing" on the code for some minutes.  And until then nothing is shown.  Inlay hints are the last thing that seems to be performed.  I've observed the same behavior in vscode.
Can you check with top to see that clangd is indeed "done".

**Comment by ofseed** [comment]
This is a bug that needs to meet certain conditions to occur, and it does exist. #28629 will fix it.
