### ISSUE TITLE
Disable spell checking in terminal buffers

### ISSUE THREAD

**Issue by languitar** [neovim/neovim#2862]
I have enabled spell checking per default. This makes sense for nearly all file types but in the current terminal buffers, nearly everything is marked as a spelling error. Maybe it would be good to disable spell checking per default in these buffers?

How can this be done as a user setting? There is no filetype for terminal buffers where I could base an autocmd on.

**Comment by ajpaulson** [comment]
You could try `au TermOpen * setlocal nospell`

I currently use a similar approach to turn of list, cursorline, and cursorcolumn for `:term` buffers

**Comment by justinmk** [comment]
As @ajpaulson mentioned, window-local options in general must be handled like this. Terminal buffers are just one example.
