### ISSUE TITLE
Local and global inlay hints not interacting correctly together

### ISSUE THREAD

**Issue by mehalter** [neovim/neovim#28625]
### Problem

When using the new `vim.lsp.inlay_hint.enable` and `vim.lsp.inlay_hint.is_enabled` I am getting some strange behavior that doesn't seem correct in terms of how buffer local and global state should work. The steps below document the problem

### Steps to reproduce

1. `nvim --clean`, open a completely clean neovim
2. `:lua =vim.lsp.inlay_hint.is_enabled()`, check the global inlay hints and see that they are disabled
3. `:lua vim.lsp.inlay_hint.enable(true)`, set the global inlay hints to being enabled by default for buffers
4. `:lua =vim.lsp.inlay_hint.is_enabled()`, check again and see that it returns true because they were just enabled
5. `:lua =vim.lsp.inlay_hint.enable(false, { bufnr = 0 })`,  disable inlay hints for a buffer 0 being the easiest for reproducing
6. `:lua =vim.lsp.inlay_hint.is_enabled({ bufnr = 0 })`, check to see the current state of the buffer's inlay hints and see _true_

### Expected behavior

If I run `vim.lsp.inlay_hint.enable` the changes should be reflected. When I go to disable the inlay hints in a specific buffer, they should become disabled regardless of the current global default

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3070+gcf9f002f3

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.33.1

### $TERM environment variable

xterm-kitty

### Installation

From repo (nightly build downloaded from releases)

**Comment by mehalter** [comment]
Centralize discussion to issue mentioned above

**Comment by mehalter** [comment]
Reopening as this is not a duplicate after investigation

**Comment by justinmk** [comment]
fixed by https://github.com/neovim/neovim/pull/28627

**Comment by mehalter** [comment]
Awesome, just tested and inlay hints seem to be working fully both toggling globally and locally and the combination of the two. Thanks again!
