### ISSUE TITLE
A syntax for Typescript is broken.

### ISSUE THREAD

**Issue by kyoh86** [neovim/neovim#28639]
### Problem

Viewing Typescript file without Tree-sitter, highlighting for the import-type part is broken.
![image](https://github.com/neovim/neovim/assets/5582459/6715c6eb-7546-4d22-ac7e-a9999b7dbc92)

### Steps to reproduce

There's no way to stop tree-sitter without dirty way.

### Expected behavior

Highlight them right.

### Neovim version (nvim -v)

v0.10.0-dev-cf9f002

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux

### Terminal name/version

WezTerm

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by kyoh86** [comment]
It may be judged as a `typescriptAliasKeyword` element.

**Comment by clason** [comment]
We don't maintain these syntax files; please contact the maintainer listed at the top of the file.

**Comment by kyoh86** [comment]
If I reported it to maintainer, and someone fix it in their repository, is this resolved automatically?

**Comment by clason** [comment]
Not automatically, but we port all changes to Vim's runtime files when they are made, yes. And Vim requires such changes to come from the maintainer.

**Comment by kyoh86** [comment]
OK, I see. I couldn't reproduce it in my Vim, so I confused it.

**Comment by clason** [comment]
Then something else must be going on since the syntax files are fully up to date.

**Comment by kyoh86** [comment]
Yes, thanks. But now I can reproduce it in Vim
