### ISSUE TITLE
TUI doesn't resize on `:set columns`, `:set lines`, `:winsize`.

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#2863]
I'm not sure if this is a side effect of my configuration,  but these are not respected by the tui:
~~~ vim
set colums=120
set lines=20
winsize 120 20
~~~
This doesn't seem to happen in pynvim, so I'm thinking something is missing in the TUI. I took a look, but I'm not sure what I should be seeing.

Update/clarification: The TUI won't resize the terminal window, it only updates the size of the grid, which leads to corruption of the display, as seen here:

![captura de pantalla de 2015-07-18 19-29-26](https://cloud.githubusercontent.com/assets/221465/8763754/55c9db2c-2d83-11e5-87d5-857f3ee53f9c.png)

This affects the usage of the `columns` and `lines` options, and the `winsize` command.

It should use the control sequences so the terminal window is resized when a new size is requested. With #3048, it does just that.

**Comment by Pyrohh** [comment]
Just wondering: what's the point of these options?

**Comment by fmoralesc** [comment]
I like my vim to start up in a 120x40 pane, which is a default I like when editing text (I use smaller terminals for shell usage though).
