### ISSUE TITLE
incorrect detection of ruby neovim in checkhealth

### ISSUE THREAD

**Issue by RageCPP** [neovim/neovim#28642]
### Problem

![image](https://github.com/neovim/neovim/assets/45113206/045c5e33-2a76-4bd0-a826-9b19c91b9d3c)
![image](https://github.com/neovim/neovim/assets/45113206/9b5dede4-c114-45ea-94c2-ff1e3aaa3992)
![image](https://github.com/neovim/neovim/assets/45113206/d45b9130-33d6-42e0-a658-0cb42988b362)
I alse try set `g.ruby_host_prog = "/home/rage/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/neovim-0.9.1/exe/neovim-ruby-host"` but still not work

### Steps to reproduce

:checkhealth

### Expected behavior

like node
```
...
Node.js provider (optional) ~
- Node.js: v20.12.2
  
- Nvim node.js host: /home/rage/.local/share/pnpm/global/5/node_modules/neovim/bin/cli.js
- OK Latest "neovim" npm/yarn/pnpm package is installed: 5.1.0
...
```

### Neovim version (nvim -v)

v0.10.0-dev-efb44e0

### Vim (not Nvim) behaves the same?

VIM - Vi IMproved 9.1 (2024 Jan 02)

### Operating system/version

wsl - open suse leap 15.5

### Terminal name/version

windows terminal

### $TERM environment variable

screen-256color

### Installation

repo

**Comment by justinmk** [comment]
Just for reference: after https://github.com/neovim/neovim/issues/27949 , `neovim-ruby-host` and `cli.js` will be obsolete and unnecessary. Instead, `g:ruby_host_prog` and `g:node_host_prog` will point to `ruby` and `node` interpreters directly (as `g:python3_host_prog` already does).
