### ISSUE TITLE
nnoremap c s dont work anymore

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#28653]
### Problem

nnoremap c s has timeout in bleeding edge neovim version

### Steps to reproduce

1

### Expected behavior

1

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3086+g783c1e596

### Vim (not Nvim) behaves the same?

not tested

### Operating system/version

Linux

### Terminal name/version

Kitty

### $TERM environment variable

xterm256

### Installation

Compiled manually

**Comment by clason** [comment]
Already fixed on master.

**Comment by justinmk** [comment]
Even before the "fix", this could be avoided with `<nowait>`.
