### ISSUE TITLE
User guide usr_01.txt has links to invalid/outdated URL?

### ISSUE THREAD

**Issue by krishnakumarg1984** [neovim/neovim#28687]
### Problem

In section 1.4 of `doc/usr_01.txt` (the copyright section), it points to a URL [https://www.opencontent.org/openpub/](https://www.opencontent.org/openpub/). But following this URL leads to a page with http response code 500 Internal Server Error.

### Steps to reproduce

`nvim --clean` followed by `:help usr_01.txt`.  Navigate to the copyright section and use `gx` to try and open the aforesaid URL.

### Expected behavior

The URL given in the documentation should point to a valid hyperlink on the web with the correct license.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3103+gca735c755

### Vim (not Nvim) behaves the same?

yes, vim 9.1.0200

### Operating system/version

Linux Ubuntu 22.04

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

bob (package manager) nightly

**Comment by zeertzjq** [comment]
It seems that the URL in https://opencontent.org/openpub is invalid too.
> Copyright (c) <year> by <author’s name or designee>.
This material may be distributed only subject to the terms and conditions set forth in the Open Publication License, vX.Y or later (the latest version is presently available at https://www.opencontent.org/openpub/).
