### ISSUE TITLE
search function

### ISSUE THREAD

**Issue by lasypig** [neovim/neovim#28686]
### Problem

when I type ``:map`` to see the keybinds, the output has too much lines, This is annoying.

### Expected behavior

Add search function to the output of the commands like ``:map``, ``:highlight`` ...
such as type ``/keyword`` to jump to the postion that **contain** keyword

**Comment by wookayin** [comment]
:help filter

e.g. `:filter Tab map`

would this suffice for you?

**Comment by zeertzjq** [comment]
Duplicate of #5054

**Comment by lasypig** [comment]
`` :put =execute('map') ``
