### ISSUE TITLE
Viewport/scroll position not remembered on buffer :bn/:bp switch

### ISSUE THREAD

**Issue by tipa40** [neovim/neovim#28707]
### Problem

The content in the viewport, viewport position, is not the same as I left it when switching back to previous buffer. Instead it seems to be centered as much as possible.

### Steps to reproduce

nvim --clean
:edit foo (which is a scrollable document)
Put the cursor in, for instance, the second last line in the viewport.
:edit bar
:bn
The cursor is on the correct line, but the viewport has been scrolled to show it at the vertical center/middle.

### Expected behavior

I would like to keep the viewport position not having to readjust it.

### Neovim version (nvim -v)

0.10.0-dev-2795+g1b55ed58e

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Ubuntu 24.04 LTS

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

build from repo

**Comment by zeertzjq** [comment]
Duplicate of #26828

**Comment by jrocha-method** [comment]
This worked for me:
```lua
vim.o.jumpoptions = "view"
```

**Comment by jtherrmann** [comment]
@jrocha-method Did `vim.o.jumpoptions = "view"` resolve this issue when using `:bn`/`:bp`? For me it only resolves the issue when switching between the last two buffers with Ctrl-6.

Edit: This has been resolved by https://github.com/neovim/neovim/issues/26828
