### ISSUE TITLE
`nvim_buf_get_text()` segfault with large negative column

### ISSUE THREAD

**Issue by vanaigr** [neovim/neovim#28729]
### Problem

Neovim crashes when calling `nvim_buf_get_text()` with a large negative `start_col`

### Steps to reproduce

nvim --clean
:call nvim_buf_get_text(0, 0, -123456789, 0, 0, {})\<cr>

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3119+gc7958356b

### Operating system/version

Ubuntu 22.04.3 LTS

### Terminal name/version

N/A

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by vanaigr** [comment]
[`buf_get_text()`](https://github.com/neovim/neovim/blob/c7958356bef304320d86cd541d0de8db968c6cc8/src/nvim/api/private/helpers.c#L517) doesn't check for negative starting column.

**Comment by osesantos** [comment]
Also happening in **Void Linux** with version **Nvim v0.10.0**.
