### ISSUE TITLE
Setting a float value in a table in a table using `vim.api.nvim_win_set_var` results in the inner table have values as a table with `true` and `false` as the indexes

### ISSUE THREAD

**Issue by EpicBirb** [neovim/neovim#28738]
### Problem

![image](https://github.com/neovim/neovim/assets/68750348/3540220d-ea9f-4cec-b323-7e82d8ad939b)
Here we have a table that has the following values
```
{
 origin = {
  x = 50.5,
  y = 6.20
 }
}
```
This is assigned to the current window using `vim.api.nvim_win_set_var`. However, after fetching the value again with the respective command:
![image](https://github.com/neovim/neovim/assets/68750348/001a129d-90d5-4d8f-91ec-68afb59bf158)

Results in this: 
![image](https://github.com/neovim/neovim/assets/68750348/530a1221-9902-4558-a8a1-014aa8c061f1)

### Steps to reproduce

1. Open up neovim using `nvim --clean`
2. On the command line, run `:lua vim.api.nvim_win_set_var(vim.fn.win_getid(), "test", {origin={x = 50.5, y = 60.023}})`
3. Then run `:lua vim.print(vim.api.nvim_win_get_var(vim.fn.win_getid(), "test"))`

### Expected behavior

I expect that the value I have assigned to the window be returned in the same way I had assigned it

### Neovim version (nvim -v)

NVIM v0.9.5

### Vim (not Nvim) behaves the same?

not tested

### Operating system/version

Windows 10 22H2

### Terminal name/version

Windows Terminal 1.19.11213.0

### $TERM environment variable

none (ran using echo $Env:TERM)

### Installation

repo using the zip file

**Comment by zeertzjq** [comment]
This behavior is necessary to distinguish a `Float` from a `Number`. In Lua these are the same type, while in Vimscript they are different. See `:h lua-special-tbl`
```
                                                              *lua-special-tbl*
4. Table with `vim.type_idx` key may be a dictionary, a list or floating-point
   value:
   - `{[vim.type_idx]=vim.types.float, [vim.val_idx]=1}` is converted to
     a floating-point 1.0. Note that by default integral Lua numbers are
     converted to |Number|s, non-integral are converted to |Float|s. This
     variant allows integral |Float|s.
   - `{[vim.type_idx]=vim.types.dictionary}` is converted to an empty
     dictionary, `{[vim.type_idx]=vim.types.dictionary, [42]=1, a=2}` is
     converted to a dictionary `{'a': 42}`: non-string keys are ignored.
     Without `vim.type_idx` key tables with keys not fitting in 1., 2. or 3.
     are errors.
   - `{[vim.type_idx]=vim.types.array}` is converted to an empty list. As well
     as `{[vim.type_idx]=vim.types.array, [42]=1}`: integral keys that do not
     form a 1-step sequence from 1 to N are ignored, as well as all
     non-integral keys.
```

**Comment by wookayin** [comment]
Question: I recall #24430 had the similar issue before. If nvim 0.10 has fixed the behavior on `nvim_win_{get,set}_config` (see #27284), `nvim_win_{get,set}_var` should deserve the same fix, or shoudn't it? If not, what's special about `nvim_win_{get,set}_config`?

**Comment by zeertzjq** [comment]
`row` and `col` in `nvim_win_get_config` can only be `Float`. Vimscript variables can be either `Integer` or `Float`.
