### ISSUE TITLE
Problem with the “enter” key in alacritty terminal

### ISSUE THREAD

**Issue by Edgar200021** [neovim/neovim#28732]
### Problem

The problem is related to the key enter, the fact that when I go to neovim through the terminal alacritty, does not work correctly key enter (exactly enter, ctrl + j works) for plugins neotree, telescope and in plugins, but with other terminals there is no such problem, in the video all clearly visible.

https://github.com/neovim/neovim/assets/105574762/521bf7ce-d85b-4606-bc0d-8da5630a4d8f

### Steps to reproduce

nvim --clean 

### Expected behavior

Correct operation of the “enter” key in neovim in alacritty terminal

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

no, 9.1

### Operating system/version

Arch Linux x86_64

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

sudo pacman -S neovim

**Comment by justinmk** [comment]
The video doesn't show `nvim --clean`, and you did not say steps to reproduce the issue. Not even sure what the video is supposed to demonstrate.

Try 0.10 : https://github.com/neovim/neovim/releases/tag/nightly
