### ISSUE TITLE
Press ESC once to exit insert mode, cursor display issue

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#28731]
### Problem

Press ESC once to exit insert mode, cursor display issue

### Steps to reproduce

init.vim
```vim
let &g:statusline="%#Visual#%{'['.winnr().']'}%#Normal#
      \ %{(&previewwindow?'[preview] ':'').expand('%:p:~:.')}%m
      \ %=%{(winnr('$')==1 || winnr('#')!=winnr()) ? '['.(&filetype!=''?&filetype.',':'').(&fenc!=''?&fenc:&enc).','.&ff.']' : ''}
      \ %{printf('%'.(len(line('$'))+2).'d/%d',line('.'),line('$'))}"

" If you annotate this line, there won't be this problem
set noshowmode
```
vim -u init.vim

### Expected behavior

Press ESC once to exit insert mode, cursor display issue

### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

dontknow

### Operating system/version

windows 10

### Terminal name/version

windows  terminal  1.21.1272.0

### $TERM environment variable

x

### Installation

x

**Comment by zeertzjq** [comment]
Can you provide a screen recording?

**Comment by zgpio** [comment]
sorry,  i cant

**Comment by zeertzjq** [comment]
What cursor display issue? It is displayed at the wrong position or with a wrong shape?

**Comment by zgpio** [comment]
wrong shape

**Comment by zgpio** [comment]
seems  regression ，I remember there was no problem before

**Comment by glepnir** [comment]
you can try bisect to find out which commit break..
