### ISSUE TITLE
The new comment feature uncomments comments when a bigger block is selected instead of leaving them commented as they should be.

### ISSUE THREAD

**Issue by leet0rz** [neovim/neovim#28750]
### Problem

If you comment out any line that goes something like this:
```
code 
code
comment
code
code
```

It will become:
```
comment
comment
code/text
comment
comment
```
when it should become:
```
comment
comment
comment
comment
comment
```

### Steps to reproduce

Open a .lua file with some comments anywhere, try to comment out that entire block with one comment already in the block and you will see whats up.

### Expected behavior

For comments to stay comments when commenting out a big block of code with a few comments in that block.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3122+ga0a189a8e

### Vim (not Nvim) behaves the same?

Vim doesnt not have this feature.

### Operating system/version

Windows 10

### Terminal name/version

New windows terminal nightly

### $TERM environment variable

None

### Installation

neovim msi from github

**Comment by clason** [comment]
This is intended.

**Comment by leet0rz** [comment]
> Cannot reproduce. Please make sure to always test with `nvim --clean`.

I tried to remap gcc to be able to use it with one key in visual mode, I think that caused the problem. Any idea how I might do that? Thanks. What I tried was `norm gc` but the outcome was this thread. Sorry that I did not state that initially.
