### ISSUE TITLE
Online documentation contains strange wrapping

### ISSUE THREAD

**Issue by rphodges** [neovim/neovim#28754]
### Problem

Online documentation  is wrapped strangely.  For example on this page: 

https://neovim.io/doc/user/

you see text jumbled together in a paragraph.  For instance, each section should be formatted like a table.  In the 'Basic Editing' section 'starting' should be in the first column and its corresponding description is in the second column.  In the next line you should see 'edit-files' and its corresponding description. Instead all the subsections are joined together in a paragraph.

Pages like https://neovim.io/doc/user/insert.html#insert.txt are also hard to read.

I didn't take the time to examine the script that generates the online manuals.  However, I did see a recent commit to it in regards to word wrapping.

### Steps to reproduce

View the reference manual online.

### Expected behavior

I expect the the contents of the online user manual to be formatted/wrapped similarly to the how neovim shows the same manual.

### Neovim version (nvim -v)

Not applicable

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Not applicable

### Terminal name/version

Not applicable

### $TERM environment variable

Not applicable

### Installation

Not applicable

**Comment by wookayin** [comment]
Current behavior:

![before](https://github.com/neovim/neovim/assets/1009873/c8258908-03c4-4e40-9c77-8f5e413dc12b)


Expected behavior:

![after](https://github.com/neovim/neovim/assets/1009873/d0a890a9-17fb-45a4-a04c-9191ef1916e7)

This is a regression from #28678.

```diff
 .old-help-para {
-    white-space: word-wrap;
+    white-space: pre;
 }
```
would fix the problem.

**Comment by BBboy01** [comment]
https://github.com/neovim/neovim/blob/7acf39ddab8ebdb63ebf78ec980149d20783fd4b/scripts/gen_help_html.lua#L1094

this already makes long word will not overflow the container

**Comment by wookayin** [comment]
No, `word-wrap: break-word` alone doesn't fix the overflow. I will submit a PR soon.
