### ISSUE TITLE
`vim.buf.nvim_buf_get_text` includes text in overlaid notification messages

### ISSUE THREAD

**Issue by rwijtvliet** [neovim/neovim#28752]
### Problem

I'm trying to detect if a buffer is empty and am using `lines = vim.api.nvim_buf_get_lines(bufnr, 0, -1, false)` for this. However, even if the buffer is empty, this returns a 3-element table if there happens to be a notification showing.

### Steps to reproduce

```lua
    vim.keymap.set('n', '<leader>S', function()
      local all = ''
      for _, bufnr in ipairs(vim.api.nvim_list_bufs()) do
        all = all .. 'bufnr: ' .. bufnr .. '\n'
        local lines = vim.api.nvim_buf_get_lines(bufnr, 0, -1, false)
        for i, line in ipairs(lines) do
          all = all .. string.format('Line %d: %s', i, line) .. '\n'
        end
        all = all .. '\n'
      end
      vim.notify(all)
    end)
```

If a single empty buffer is open, with an overlaid notification like so...

<img width="1617" alt="image" src="https://github.com/neovim/neovim/assets/4106013/8e4a6243-18d4-40cb-9e7b-29bc63588cf0">

...pressing `<leader>S` will include the text of the notification shown at the time:

<img width="395" alt="image" src="https://github.com/neovim/neovim/assets/4106013/9ae13827-730c-4be0-b656-a4d524f5244b">

### Expected behavior

That `vim.buf.nvim_buf_get_lines()` only returns the lines of text in the actual buffer.

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1713773202

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 14.5

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

homebrew

**Comment by zeertzjq** [comment]
The notification is an actual buffer and the notification text is the text in that buffer.

**Comment by rwijtvliet** [comment]
Ahhhh thanks. I was wondering why there were more than 1 buffer anyway. Thanks for clearing that up; I'll have to filter the buffers somehow; I'll look into it.
