### ISSUE TITLE
Opening multiple files with -p with nightly neovim has different tabstop & expandtab values on second tab

### ISSUE THREAD

**Issue by jthemenace** [neovim/neovim#28759]
### Problem

When running on neovim nightly and nvim-treesitter is enabled, when I open 2 files using the -p command, the second tab doesn't have my configured tabstop & expandtab values from my config, however the first tab does. If I don't load nvim-treesitter it works perfectly fine.

### Steps to reproduce

nvim -p file1.php file2.php
go to second tab, view settings of expandtab and tabstop
:set expandtab?
:set tabstop?

compare them with values from first tab, see that they are different

### Expected behavior

I expect all tabs to have the same value from my config for expandtab & tabstop

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3122+ga0a189a8e

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian Linux 12.5

### Terminal name/version

iTerm 2 3.5

### $TERM environment variable

tmux-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
How did you set these options in your config?

**Comment by jthemenace** [comment]
In my lua config, I have the following 2 lines
```
vim.opt.tabstop = 2
vim.opt.expandtab = true
```

I use the "lazy" plugin manager.  I have this line in my main plugin lua file
```
{'nvim-treesitter/nvim-treesitter', build = ":TSUpdate"},
```
Then my setup for treesitter is
```
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "c", "lua", "vim", "vimdoc", "query", "php", "javascript", "json5", "tsx",
                       "typescript", "html", "vue", "json", "bash", "python", "diff", "markdown", "sql"},
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = true
  }
}
```

**Comment by wookayin** [comment]
Run nvim with the `-V1` option and try:
```
:verbose set expandtab?
:verbose set tabstop?
```
and see where this option is set.

**Comment by jthemenace** [comment]
When I run nvim -V1 -p file1.php file2.php
when in the first tab for the first file it says
  expandtab
        Last set from ~/.config/nvim/lua/options.lua line 8
  tabstop=2
        Last set from ~/.config/nvim/lua/options.lua line 7

when in the second tab for the second file it says
noexpandtab
tabstop=8

**Comment by wookayin** [comment]
You think you want to look at `~/.config/nvim/lua/options.lua` line 7 and 8. Is it `setlocal` instead of `set`?  Please remember to provide full reproducible steps as instructed in the issue template.

**Comment by jthemenace** [comment]
In my lua config, I have the following 2 lines, for line numbers 7 & 8.
```
vim.opt.tabstop = 2
vim.opt.expandtab = true
```
This problem doesn't exist with the exact same config files and neovim version 0.9.5

**Comment by clason** [comment]
Can you reproduce this with a file containing only these two lines and `nvim --clean -u test.lua ...`?

**Comment by jthemenace** [comment]
when running the following with the nightly
```
vi -V1 -p --clean -u ~/test.lua file1.php file2.php
```
it works as expected, the issue isn't present

**Comment by clason** [comment]
Then your problem lies somewhere in your config. Add stuff to the minimal test file until you can reproduce. (The issue is usually some plugin.)

**Comment by jthemenace** [comment]
If I don't load the nvim-treesitter plugin it works fine.  I tried opening a bug with nvim-treesitter and they closed it saying it can't be caused by that...

**Comment by clason** [comment]
But is nvim-treesitter the only plugin you load? What is your configuration for thst plugin? (Don't install all languages blindly.)

**Comment by jthemenace** [comment]
I use the "lazy" plugin manager and install the following plugins
```
return {
  {'folke/tokyonight.nvim', lazy = false, priority = 1000},
  {'neovim/nvim-lspconfig', lazy = true},
  {'nvim-treesitter/nvim-treesitter', build = ":TSUpdate"}, 
  {'lewis6991/gitsigns.nvim', lazy = true},
  {'stevearc/aerial.nvim', lazy = true},
  {'tpope/vim-fugitive', cmd = "Git", lazy = true},
  { 'nvim-lualine/lualine.nvim',
    dependencies = { 'nvim-tree/nvim-web-devicons', lazy = true }
  },
  {
    'nvim-telescope/telescope.nvim',
    dependencies = { {'nvim-lua/plenary.nvim', lazy = true} },
  },
}
```

My config for tree-sitter is
```
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "c", "lua", "vim", "vimdoc", "query", "php", "javascript", "json5", "tsx",
                       "typescript", "html", "vue", "json", "bash", "python", "diff", "markdown", "sql"},
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  --indent = {
  --  enable = true
  --}
}
```

**Comment by clason** [comment]
Yeah, that's too many. Reduce to the absolute minimum.

**Comment by wookayin** [comment]
I still can't reproduce the issue OP is describing, with and without nvim-treesitter. Once you manage to find a full, self-contained, clear reproduction steps based on https://github.com/neovim/neovim/blob/master/contrib/minimal.lua (*please don't use lazy.nvim*), please feel free to ask further help.

**Comment by jthemenace** [comment]
I tried some more things this morning to try and get it to happen on the nightly without using lazy and very minimal config, but wasn't able to get it to happen that way.  I'm just going to go back to neovim 0.9.5 for now where this problem doesn't occur and hope that whatever the underlying issue is gets fixed when 0.10 gets fully released.

**Comment by clason** [comment]
Neovim 0.10 is being released _right now_. So keep testing.

**Comment by fczuardi** [comment]
@jthemenace have you tried adding:

```lua
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
```

**Comment by gonzaloserrano** [comment]
I have the same or similar issue but the way to reproduce it is different. I'm on macOS, neovim 0.10.0 installed with brew and many plugins for Go dev.

So if I open 2 Go files, i.e `nvim -V1 -p f1.go f1_test.go`, `ts` is correctly set to `4` as per my `~/.config/nvim/init.lua` definition of `vim.opt.tabstop = 4`.

But if I navigate to a different file via LSP go to definition `vim.lsp.buf.definition()`, the opened file has the `ts` set to `2` as per `/opt/homebrew/Cellar/neovim/0.10.0/share/nvim/runtime/lua/editorconfig.lua`.

This was not happening in neovim 0.9.5.

**Comment by jthemenace** [comment]
After this issue was closed, I opened one with lazy.nvim [here](https://github.com/folke/lazy.nvim/issues/1461)

Someone mentioned it was a duplicate of [this one](https://github.com/folke/lazy.nvim/issues/1435) that had the fix / answer.

I had to put my expandtab / tabstop setting(along with a few others) in my config BEFORE the lazy plugin manager is loaded.  Once I did that it started working fine.
