### ISSUE TITLE
DECRQSS +q5463;524742;73657472676266;73657472676262$qm appears in terminal

### ISSUE THREAD

**Issue by lpar** [neovim/neovim#28776]
### Problem

When I start nvim 0.10.0 I see `+q5463;524742;73657472676266;73657472676262$qm` appear at the top left of the terminal window, with the `$qm` in italic and darker. After a fraction of a second it disappears and the regular initial window contents appear.

Using a terminal to a remote Mac, I see `p$qm+q5463;524742;73657472676266;73657472676262$qm+q4D73` with the `$qm+q4D73` in dark italic.

I didn't see this with 0.9.5.

It still does it with `nvim --clean`.

I'm guessing this is due to DECRQSS terminal escapes that aren't implemented by macOS terminal. Apparently [they aren't implemented for alacritty either](https://github.com/alacritty/alacritty/issues/7184).

### Steps to reproduce

`nvim --clean`

### Expected behavior

Initial `NVIM v0.10.0` blank window appears.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

no, 9.0.2142

### Operating system/version

macOS 14.5

### Terminal name/version

macOS terminal

### $TERM environment variable

xterm-256color

### Installation

Homebrew

**Comment by justinmk** [comment]
I'm certain this is discussed in existing, closed issues.

**Comment by clason** [comment]
Don't use Apple Terminal, it's plain broken. iTerm2 (3.5, the betas are release candidates now) will do in a pinch.

**Comment by gpanders** [comment]
>I'm guessing this is due to DECRQSS terminal escapes that aren't implemented by macOS terminal. Apparently https://github.com/alacritty/alacritty/issues/7184.

The terminal should not print an escape sequence just because it's unimplemented. This is just Apple Terminal being terrible, as usual.

We disabled DECRQSS for Apple Terminal in https://github.com/neovim/neovim/pull/28453, but you're also seeing the XTGETTCAP sequence to determine OSC 52 support.

Setting `vim.g.clipboard = false` in your `init.lua` (or `let g:clipboard = v:false` in Vimscript) _should_ disable the XTGETTCAP query, but I can still reproduce this with that.

**Comment by zgpio** [comment]
Same issue on windows cmd.exe

**Comment by tronboto** [comment]
I'm also seeing this on PuTTY 0.81

**Comment by gpanders** [comment]
If https://github.com/neovim/neovim/pull/29197 then you can opt out of the DECRQSS/XTGETTCAP queries by setting `$COLORTERM` to any value other than `truecolor` or `24bit` (e.g. `256` or `16`).

**Comment by tronboto** [comment]
Thanks for that PR, @gpanders . I see the PR mentions that setting `$COLORTERM` to `truecolor` or `24bit` should prevent the terminal from being queried. However, I've found that when setting that, I no longer see `$qm463;524742;73657472676266;73657472676262`, which is great, but I still see `+q4D73` pop up briefly. This is on PuTTY 0.81.

**Comment by zeertzjq** [comment]
You should set `$TRUECOLOR` to `256`.

**Comment by gpanders** [comment]
> Thanks for that PR, @gpanders . I see the PR mentions that setting `$COLORTERM` to `truecolor` or `24bit` should prevent the terminal from being queried. However, I've found that when setting that, I no longer see `$qm463;524742;73657472676266;73657472676262`, which is great, but I still see `+q4D73` pop up briefly. This is on PuTTY 0.81.

That is the OSC 52 query. Set `vim.g.clipboard = false` in your init.lua to disable it.

**Comment by califyn** [comment]
Hi, thanks so much for the help so far. Both solutions have reduced the amount of characters being printed. Even after these two fixes, however, I still notice a `p$qm` being printed at the top left of the terminal. For reference, I am logged into a remote server running Linux from my Mac. If there is any way to get rid of it, I would appreciate that very much.

**Comment by gpanders** [comment]
FYI with https://github.com/neovim/neovim/pull/31730 merged, the process for disabling the OSC 52 query has changed. Instead, use:

```lua
local termfeatures = vim.g.termfeatures or {}
termfeatures.osc52 = false
vim.g.termfeatures = termfeatures
```

**Comment by otomn** [comment]
To add, if the weird string is only appearing when using SSH, you can forward `$TERM_PROGRAM` to the remote machine, either by setting SSH to forward Env or by setting `TERM_PROGRAM` in `~/.profile` directly.

And you might also need to set `COLORTERM`

**Comment by lpar** [comment]
> FYI with [#31730](https://github.com/neovim/neovim/pull/31730) merged, the process for disabling the OSC 52 query has changed. Instead, use:
> 
> local termfeatures = vim.g.termfeatures or {}
> termfeatures.osc52 = false
> vim.g.termfeatures = termfeatures

I've got this in my init.lua with neovim v0.11.0 and I'm still getting `+q5463;524742;73657472676266;73657472676262$qm` at the top of the terminal when I start neovim. Same with v0.12.0-dev-60+g8a40213eb3.

**Comment by rcmdnk** [comment]
@irr123 
I have same `+q4D73` problem on v0.11.0 and GNU screen 5.0.0.
It appears when I split windows vertically and horizontally and launch Neovim in the left windows.
In the upper window, `+q4D73` does not appear, but the layout is messed up.

I could fix this by disabling osc52 like:

```
local tf = vim.g.termfeatures or {}
tf.osc52 = false
vim.g.termfeatures = tf
```

**Comment by justinmk** [comment]
@rcmdnk there were some related fixes in Nvim 0.11.1, the latest stable release. Do not report things without testing latest.

**Comment by rcmdnk** [comment]
@justinmk 
I tested on Nvim 0.11.1 and GNU screen 5.0.0.

This problem still happens if `truecolor on` is set in .screenrc.
`termfeatures` setting in init.lua fixes this problem on v0.11.1,
while `vim.g.clipboard = false` does not work on v0.11.1.
For v0.10.X, only `vim.g.clipboard = false` works.

If `$COLORTERM` is not set, `+q5463;524742;73657472676266;73657472676262$qm` is also still shown on v0.11.1.

**Comment by golanguage** [comment]
MobaXterm v26.1 build 5456 have this issue --- +q4D73

**Comment by justinmk** [comment]
see

- https://github.com/neovim/neovim/pull/38699
