### ISSUE TITLE
Render hyperlinks (OSC 8) in embedded terminal

### ISSUE THREAD

**Issue by bluss** [neovim/neovim#28789]
### Problem

Make hyperlinks in command outputs clickable in the embedded terminal (:term) in neovim if the hosting terminal or UI supports it.

Commands such as ls --hyperlink=always (GNU coreutils) and ripgrep are examples of utils that can output hyperlink escapes.

### Expected behavior

ls -l --hyperlink=always should produce clickable links when used inside neovim's embedded terminal (:term). Compare with how this works in standalone terminals (such as gnome-terminal, kitty, or others, also in tmux) which make these links clickable. Use the existing neovim 0.10 support for OSC 8 (in extmarks in that case) to accomplish this.

### Discussion

Briefly discussed here https://github.com/neovim/neovim/discussions/28620#discussioncomment-9459364 where @gpanders shared a thought

**Comment by unphased** [comment]
I wanted to be able to use nvim as a poor man's tmux (from neovide) and this is needed for hyperlinks to work.
