### ISSUE TITLE
vim.lsp.buf.definition() adds extra entry to jumplist when definition file not opened yet

### ISSUE THREAD

**Issue by mikehaertl** [neovim/neovim#28784]
### Problem

When `vim.lsp.buf.definition()` is called and the file with the definition is not yet available in a buffer I find an extra entry in the jumplist. It points to the top of the file that contains the definition.

### Steps to reproduce

1. Open any file with references to a definition in another file. 
2. Make sure the other file is not opened in a buffer.
3. call `:lua vim.lsp.buf.definition()`

### Expected behavior

The jumplist should only have one entry. So a single `<C-O>` should take you back to where you called `vim.lsp.buf.definition()`.

Instead the first `<c-o>` takes me to the top of the definition file and I need a second `<c-o>` to get back to the initial location.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Linux Mint 21.3

### Terminal name/version

Gnome Terminal 3.44.0

### $TERM environment variable

screen-256-color

### Installation

build from repo

**Comment by icholy** [comment]
I'm not able to reproduce this with gopls:
![no-extra-jump](https://github.com/neovim/neovim/assets/943597/61162d79-6255-45bd-bc5a-403a7f996455)

**Comment by mikehaertl** [comment]
I will investigate further and try to provide a minimal config to reproduce the issue.

**Comment by icholy** [comment]
@mikehaertl btw I was testing on nightly, not 0.10.1

**Comment by mikehaertl** [comment]
Issue was actually caused by this little config that I've probably copied from somewhere a long time ago and never reconsidered:

```vim
" When editing a file, always jump to the last cursor position.
autocmd BufReadPost * if line("'\"") && line("'\"") <= line("$") | exe "normal `\"" | endif
```
The fix was easy: use [g'"](https://neovim.io/doc/user/motion.html#g') instead of [\`"](https://neovim.io/doc/user/motion.html#')

```vim
autocmd BufReadPost * if line("'\"") && line("'\"") <= line("$") | exe "normal! g'\"" | endif
```

Source: https://stackoverflow.com/a/774599
