### ISSUE TITLE
solarized colorscheme doesn't load in neovim 0.10.0, works in 0.9.5

### ISSUE THREAD

**Issue by vmchale** [neovim/neovim#28791]
### Problem

I have the following in my init.lua:

```
vim.cmd [[
colorscheme solarized
]]
```

After the plugin is loaded: https://github.com/altercation/vim-colors-solarized

### Steps to reproduce

Open nvim version 0.10.0; colorscheme is not loaded and has blue.

### Expected behavior

I should open nvim 0.10.0 and see the solarized colorscheme being used, like nvim 0.9.5 or vim.

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1692716794     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"

### Vim (not Nvim) behaves the same?

Vim 9.0.639 works correctly, as does 

### Operating system/version

MacOS 14.5

### Terminal name/version

Iterm 2

### $TERM environment variable

xterm-256color

### Installation

Github tarball

**Comment by clason** [comment]
please provide a reproducible example with `nvim --clean -u test.lua`.

**Comment by wookayin** [comment]
See #26378.

**Comment by justinmk** [comment]
> See #26378.

Yes. https://github.com/altercation/vim-colors-solarized likely needs a small adjustment. But it hasn't been updated for 13 years.

**Comment by MonkeysAreEvil** [comment]
FYI NeoSolarized works for me in v0.10.0. In tmux I did have to add

```
set-option -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
```

I think `screen-256color` would also work.

**Comment by vmchale** [comment]
> > See #26378.
> 
> Yes. https://github.com/altercation/vim-colors-solarized likely needs a small adjustment. But it hasn't been updated for 13 years.

Thank you!

**Comment by candidtim** [comment]
If this is of any help, I have found the "solarized8" plugin to be a suitable replacement (for some reason NeoSolarized didn't work as expected, all colors are too bright; might spent more time fixing the configuration, but "solarized8" worked out of the box): https://github.com/lifepillar/vim-solarized8/tree/neovim . Make sure to use the `neovim` branch.
