### ISSUE TITLE
Syntax highlighting needs to be turned on manually for certain languages

### ISSUE THREAD

**Issue by vmchale** [neovim/neovim#28793]
### Problem

Syntax highlighting isn't there when I open a file on the command-line. I have to pull it up by `:syntax enable`; after that it works.

### Steps to reproduce

The syntax highlighting plugin in question is here: https://github.com/vmchale/jacinda-vim

As an example, open a `*.jac` file, e.g.: https://github.com/vmchale/jacinda/blob/main/examples/nmCtx.jac

Running `nvim nmCtx.jac` opens the file but with no syntax highlighting until `:syntax enable`. Curiously, running `nvim` following by `:edit nmCtx.jac` works.

Many other languages do work, e.g. Haskell syntax highlighting, Rust syntax highlighting, but occasionally others fail.

### Expected behavior

I would expect syntax highlighting to be on when opening a file from the command-line. 

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

Vim 9.0.639 works correctly, syntax is turned on in my .vimrc

### Operating system/version

MacOS 14.5

### Terminal name/version

Iterm2

### $TERM environment variable

xterm-256color

### Installation

Github tarball

**Comment by clason** [comment]
You need to provide a reproducible config with `nvim --clean -u test.lua`.

**Comment by vmchale** [comment]
The problem happens even with vim-plug

Seems to have been around at least a year: https://www.reddit.com/r/neovim/comments/11banfa/cant_get_syntax_highlighting_to_work_correctly/ja0ptzq/

**Comment by justinmk** [comment]
> Vim 9.0.639 works correctly, syntax is turned on in my .vimrc

Depends on when your config calls `:syntax enable`.

A workaround might be to put your syntax file in `after/syntax/` instead of `syntax/`. Example: https://github.com/justinmk/vim-syntax-extra/tree/master/after/syntax

**Comment by icholy** [comment]
@vmchale I cannot reproduce issue on `0.10.0` or `master`. https://github.com/icholy/nvim-bug-28793

**Comment by teocns** [comment]
Can reproduce with `0.10.0`, whilst `0.9.5` works just fine. As OP mentions, I've gotta manually turn on syntax to get the correct highlights.

I am using a high-level custom astronvim v3. Using [this toggle](https://github.com/AstroNvim/AstroNvim/blob/c699c7ace37093b5e73206c67fc394a5e1b5f58c/lua/astronvim/utils/ui.lua#L235) post launch gets syntax working
