### ISSUE TITLE
calling setreg cause cursor to blink

### ISSUE THREAD

**Issue by xzbdmw** [neovim/neovim#28797]
### Problem

https://github.com/neovim/neovim/assets/97848247/951812e5-0457-41fb-ab11-3945d3101211

typing dd and cursor will filker if  `vim.fn.setreg("+", now)` is called

### Steps to reproduce

```repro.lua
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "--single-branch",
        "https://github.com/folke/lazy.nvim.git",
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)
-- install plugins
local plugins = {
    -- do not remove the colorscheme!
    "folke/tokyonight.nvim",
    -- add any other pugins here
}

require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

-- add anything else here
-- vim.opt.termguicolors = true
-- do not remove the colorscheme!
vim.cmd([[colorscheme tokyonight]])
vim.keymap.set("n", "d", function()
    vim.defer_fn(function()
        local now = vim.fn.getreg('"')
        vim.fn.setreg("+", now)
    end, 1000)
    return "d"
end, { expr = true })
```
1. touch ~/.config/nvim/repro.lua
2. nvim -u ~/.config/nvim/repro.lua ~/.config/nvim/repro.lua
3. dd
4. see the cursor blinking(flikering)

### Expected behavior

cursor will not fliker

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3101+gc18d7941e-dirty Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

don't know

### Operating system/version

macos 14.2

### Terminal name/version

kitty, neovide

### $TERM environment variable

xterm-kitty

### Installation

build from source

**Comment by justinmk** [comment]
> vim.fn.setreg("+", now)

I knew without looking this would involve clipboard. The cursor flicker indicates that a job/process invocation.

Also just the fact that your repro involves extra plugins, is a signal that some sort of event handler is listening to something.
