### ISSUE TITLE
When `ext_cmdline` is enabled, the event `grid_cursor_goto` will not be sent during incsearch

### ISSUE THREAD

**Issue by xiyaowong** [neovim/neovim#28800]
### Problem

```
$ ./venv/bin/python3 test.py 
==== Disable ext_cmdline ===
### Start incsearch ###
grid_cursor_goto
grid_cursor_goto
==== Enable ext_cmdline ===
### Start incsearch ###
```

### Steps to reproduce

- `pip install pynvim`
- Install `NVIM v0.10.0`
- Run `test.py`
```python
import threading

from pynvim import attach
from pynvim.api.buffer import Buffer


def test(ext_cmdline):
    print("====", "Enable" if ext_cmdline else "Disable", "ext_cmdline", "===")

    start_incsearch = False

    def event_handler(_, data):
        if not start_incsearch:
            return
        for ev in data:
            ev_name = ev[0]
            if 'cursor' in ev_name:
                print(ev_name)

    nvim = attach('child', argv=["nvim", "--embed", "--clean"])
    nvim.ui_attach(40, 20, True, ext_cmdline=ext_cmdline, ext_linegrid=True)

    buf: Buffer = nvim.api.create_buf(False, True)
    buf.append(['a', 'b', 'c', *[''] * 20, 'd', 'e', 'f'])
    nvim.api.open_win(
        buf,
        True,
        {
            'relative': 'win',
            'row': 3,
            'col': 3,
            'width': 30,
            'height': 15,
        },
    )

    def incsearch():
        nonlocal start_incsearch
        start_incsearch = True
        print('### Start incsearch ###')
        nvim.input('gg/e')

    timer = threading.Timer(1, lambda: nvim.async_call(incsearch))
    timer.start()

    quit = threading.Timer(2, lambda: nvim.async_call(lambda: nvim.quit()))
    quit.start()

    nvim.run_loop(event_handler, event_handler)


test(False)
test(True)
```

### Expected behavior

Should the events be the same? Or is this expected behavior?

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal

### $TERM environment variable

-

### Installation

Scoop

**Comment by xiyaowong** [comment]
```
==== Disable ext_cmdline ===
### Start incsearch ###
['grid_cursor_goto', [1, 19, 2]]
['grid_scroll', [1, 3, 18, 3, 33, 11, 0]]
['win_viewport', [4, <Window(handle=1001)>, 11, 27, 25, 1, 27, 11]]
['grid_cursor_goto', [1, 19, 2]]
==== Enable ext_cmdline ===
### Start incsearch ###
['grid_scroll', [1, 3, 18, 3, 33, 11, 0]]
['win_viewport', [4, <Window(handle=1001)>, 11, 27, 25, 1, 27, 11]]
```

I printed out events related to scroll and viewport. It seems like this behavior is an intentional change in version 0.10? incsearch scrolls the window but doesn't move the cursor.

**Comment by luukvbaal** [comment]
> I forgot that the current issue is that ext_cmdline is causing event inconsistencies, which should not be the expected behavior.

Why not? This event was intentionally removed in [`d41b8d4` (#27858)](https://github.com/neovim/neovim/pull/27858/commits/d41b8d47587bd4c300420fa76f517298e97af513). All it did is send an event placing the cursor in the current window. Which is unhelpful, because the cursor should be in the cmdline which is unknown to Nvim. Unlike when ext_cmdline is disabled where this event does place the cursor in the cmdline(message grid).

**Comment by xiyaowong** [comment]
But the cursor changed:
```
==== Disable ext_cmdline ===
cursor (1, 0)
### Start incsearch ###
grid_cursor_goto
grid_cursor_goto
cursor (26, 1)
==== Enable ext_cmdline ===
cursor (1, 0)
### Start incsearch ###
cursor (26, 1)
```
```python
    def incsearch():
        nonlocal start_incsearch
        start_incsearch = True
        print('cursor', win.cursor)
        print("### Start incsearch ###")
        nvim.input("gg/e")
        print('cursor', win.cursor)
```

**Comment by luukvbaal** [comment]
Well yes the cursor position in the current window changes for incsearch but the cursor position on the grid does not and should not(implicitly). What problem does this cause?

**Comment by xiyaowong** [comment]
The potential issues may be related to the way UI events are handled. vscode-neovim currently only can **adjust** viewport based on cursor position rather than **drawing**.
