### ISSUE TITLE
nvim.appimage  not work on old system

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#28805]
### Problem

 ./squashfs-root/usr/bin/nvim
./squashfs-root/usr/bin/nvim: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./squashfs-root/usr/bin/nvim)

### Steps to reproduce

*

### Expected behavior

*

### Neovim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

dontknow

### Operating system/version

Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

### Terminal name/version

x

### $TERM environment variable

x

### Installation

x

**Comment by clason** [comment]
Duplicate. Try the unsupported legacy builds at https://github.com/neovim/neovim-releases.
