### ISSUE TITLE
Hover window shows markdown syntax

### ISSUE THREAD

**Issue by frolvanya** [neovim/neovim#28803]
### Problem

Starting from neovim 0.10, hover window started to show markdown syntax. This works in rust, python, lua (I haven't tested more files, but I suppose it will work in all languages). Is it an expected behaviour?

Neovim 0.10:
<img width="386" alt="image" src="https://github.com/neovim/neovim/assets/59515280/49f393c6-21ff-4418-9883-7fe03ca1da94">
When entering window:
<img width="383" alt="image" src="https://github.com/neovim/neovim/assets/59515280/50be8592-6516-4989-bf4d-ca4e791ce3be">

Neovim 0.9.5:
<img width="400" alt="image" src="https://github.com/neovim/neovim/assets/59515280/297ba412-8fab-4c4d-bbb3-f7bf98bf3281">

### Steps to reproduce using "nvim -u minimal_init.lua"

It works with raw neovim 0.10 (stable)
Can be triggered via `:lua vim.lsp.buf.hover()`

### Expected behavior

Small window without "```rust" and other markdown symbols like "*" and etc.
<img width="400" alt="image" src="https://github.com/neovim/neovim/assets/59515280/34e12283-75d5-488f-a492-9c73e7d7a9d3">

### Neovim version (nvim -v)

0.10.0

### Language server name/version

rust-analyzer 2024-05-13 

### Operating system/version

MacOS

**Comment by wookayin** [comment]
Yes. Please see #25073.
