### ISSUE TITLE
No OSC-8 being emmitted for wrapped hyperlink

### ISSUE THREAD

**Issue by WhyNotHugo** [neovim/neovim#28817]
### Problem

It doesn't seem that neovim is emmitting OSC8 escapes for hyperlinks when they wrap.

### Steps to reproduce

1. Run nvim --clean -u /dev/null
2. In the empty buffer, type a link (e.g.: `https://ddg.gg`)
3. Run `set number`
4. Prepend enough spaces so that the link wraps to the next line (e.g.: one line renders `https:` and the next renders the rest).

### Expected behavior

There are no OSC-8 escape sequences for this hyperlink.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Alpine Linux

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

Built from source

**Comment by zeertzjq** [comment]
OSC 8 requires setting extmarks

**Comment by WhyNotHugo** [comment]
> OSC 8 requires setting extmarks

I'm using neovim 0.10.0, which does support extmarks.

**Comment by zeertzjq** [comment]
Extmarks will not appear out of nowhere, some plugin needs to set them.

**Comment by WhyNotHugo** [comment]
A plugin needs to recognise hyperlinks and add extmarks, and neovim will then add the OSC-8 escape codes?

That makes sense, thanks for the clarification.
