### ISSUE TITLE
Dart commentstring is empty

### ISSUE THREAD

**Issue by RobertBrunhage** [neovim/neovim#28812]
### Problem

With the new commenting builtin to neovim I would expect to be able to do it in .dart files.

Currently this is the output

"Option 'commentstring' is empty"

### Expected behavior

It would put comments such as other languages.

**Comment by clason** [comment]
Please don't abuse the "feature request" template to bypass requested information for a bug report.

And the comment plugin works with the `commentstring` option set in bundled filetype plugins; either add your own or -- even better -- contribute one to Vim (which we will then port).

**Comment by clason** [comment]
Easiest would be to install https://github.com/dart-lang/dart-vim-plugin, and/or ask there to upstream the base part of it to Vim.

**Comment by nank1ro** [comment]
@RobertBrunhage how did you fixed it on NeoVim?
