### ISSUE TITLE
Windows release 0.10.0 does not include nvim-qt

### ISSUE THREAD

**Issue by thomas-haslwanter** [neovim/neovim#28813]
### Problem

The "stable" Windows version does not include nvim-qt. This is the case for the ZIP-file, as well as for the MSI-file.

### Steps to reproduce

download [https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-win64.zip](https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-win64.zip)
or [https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-win64.msi](https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-win64.msi)

### Expected behavior

nvim-qt.exe should be included after unzipping / running msi-installer.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Win 11

### Terminal name/version

wt

### $TERM environment variable

None

### Installation

from (precompiled) binary version

**Comment by clason** [comment]
This is intentional.
