### ISSUE TITLE
Starting nvim-0.10 in docker crashes tmux

### ISSUE THREAD

**Issue by joshuali925** [neovim/neovim#28827]
### Problem

Starting nvim inside docker inside tmux crashes tmux. This seems wezterm specific, trying on default Mac terminal it does not happen.

### Steps to reproduce

1. `tmux` (pre-installed version is 3.4)
2. install docker
3. `docker run -it --rm ubuntu bash -c 'apt update; apt install -y wget; bash'`
4. in docker, run `wget https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz; tar xzf nvim-linux64.tar.gz; ./nvim-linux64/bin/nvim`
5. see tmux crash with `[server exited unexpectedly]`

### Expected behavior

same as 0.9.5 where it runs normally

### Neovim version (nvim -v)

v0.10.0

### Vim (not Nvim) behaves the same?

no, vim 9.1

### Operating system/version

mac 13.6 ssh to Ubuntu 24.04 x64

### Terminal name/version

wezterm 20240212-073805-217dfb30

### $TERM environment variable

tmux-256color

### Installation

tarball from github release

**Comment by wookayin** [comment]
Can you please attach tmux log if possible?

**Comment by zeertzjq** [comment]
Hmm, according to https://github.com/tmux/tmux/issues/3983 this seems to happen because DECRQSS conflicts with tmux's handling of sixel, while detecting tmux in Docker using environment variables does not work.

**Comment by joshuali925** [comment]
[tmux-logs.tar.gz](https://github.com/neovim/neovim/files/15358971/tmux-logs.tar.gz)

Also if i start tmux on Mac, then ssh and run nvim, tmux also crashes

**Comment by joshuali925** [comment]
I can confirm rebuilding tmux from HEAD on master branch fixes it.

On tmux 3.4 (host) setting the `TMUX` environment variable (in docker) before opening nvim could prevent crashing tmux, but setting `TERM=tmux-256color` does not work. I also tried to comment out `tui_query_extended_underline(tui);` but tmux still crashes, so I'm not sure if it's this

https://github.com/neovim/neovim/blob/27fb62988e922c2739035f477f93cc052a4fee1e/src/nvim/tui/tui.c#L1916
https://github.com/neovim/neovim/blob/27fb62988e922c2739035f477f93cc052a4fee1e/src/nvim/tui/tui.c#L429-L434

**Comment by zeertzjq** [comment]
There is another use of DECRQSS in runtime/lua/vim/_defaults.lua

**Comment by GNITOAHC** [comment]
I use iterm2 + tmux version 3.4 on MacOS.
When ssh to a Ubuntu 22.04.4 LTS with nvim v0.10.0 it crash my tmux, too.

**Comment by splooge** [comment]
Similar issue
```
localhost$ tmux -V
tmux 3.4
```
```
localhost$ tmux
localhost$ ssh remotehost
remotehost$ nvim -v
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```
```
remotehost$ nvim --clean
[server exited unexpectedly]
```
[tmux-logs.tar.gz](https://github.com/neovim/neovim/files/15393006/tmux-logs.tar.gz)

**Comment by fallenbeck** [comment]
There is a fix on the `tmux` side:
[https://github.com/tmux/tmux/issues/3983](https://github.com/tmux/tmux/issues/3983}

**Comment by xvzc** [comment]
Thanks to @fallenbeck, installing `tmux 3.5` fixed it for me.

**Comment by farzadmf** [comment]
Question: how is this "completed"? Is the solution installing `tmux 3.5`??

**Comment by dundargoc** [comment]
> Question: how is this "completed"? Is the solution installing `tmux 3.5`??

Yeah. Tmux has already made a fix for this so there's no reason for us to keep track if this anymore.
