### ISSUE TITLE
No nvim-qt found in the newest release version v0.10.0

### ISSUE THREAD

**Issue by lifei** [neovim/neovim#28834]
### Problem

No nvim-qt.exe found in the newest version of neovim.

### Steps to reproduce

Download the release zip file and open it. one can find no nvim-qt.exe file in it.

### Expected behavior

Find nvim-qt.exe file

### Neovim version (nvim -v)

v0.10.0

### Vim (not Nvim) behaves the same?

v0.9.5

### Operating system/version

Windows 11 Pro

### Terminal name/version

MSYS2

### $TERM environment variable

xterm-256color

### Installation

repo

**Comment by clason** [comment]
Duplicate, and intentional.
