### ISSUE TITLE
Fedora COPR repository no longer exists...

### ISSUE THREAD

**Issue by alxgrtnstrngl** [neovim/neovim#2883]
> Fedora / RHEL
> See http://copr.fedoraproject.org/coprs/gaurdro/neovim/. It's built using the Copr automated build system, which is unsupported. There's no guarantee of how long your package will be available after the build finishes.

This URL leads to: "Copr with name neovim does not exist."

Please update it to this:

http://copr.fedoraproject.org/coprs/dperson/neovim/

Or if possible and better have an official COPR:

http://copr.fedoraproject.org/coprs/neovim/neovim/

**Comment by fwalch** [comment]
It's a Wiki, so everybody can update the URL. If the old one doesn't work anymore and the new one is the best way for Fedora users to install Neovim, just go ahead! :-)

**Comment by alxgrtnstrngl** [comment]
Updated the wiki, doing an official COPR might be interesting so you could support CentOS 7 as well...

**Comment by fwalch** [comment]
Well, I think there's nobody inherently against "official" packages, but somebody has to maintain them.. for Homebrew, it works really nicely because it just requires a repository: https://github.com/neovim/homebrew-neovim
