### ISSUE TITLE
rectangle in front of Normal

### ISSUE THREAD

**Issue by mictadlo** [neovim/neovim#28844]
### Problem

I have, for example, in front of a `Normal` a rectangle. 

![image](https://github.com/neovim/neovim/assets/588297/d7a55c86-cb0f-4f01-8523-29d8660dfa22)

### Steps to reproduce

I follow these [steps](https://carlosahs.medium.com/how-to-install-neovim-from-source-on-ubuntu-20-04-lts-524b3a91b4c4) to install neovim on Debian 12.

### Expected behavior

I assume to remove the rectangles.

### Neovim version (nvim -v)

 v0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

debian 12

### Terminal name/version

Terminal

### $TERM environment variable

Dark

### Installation

build from repo

**Comment by zeertzjq** [comment]
Please find the plugin that shows the statusline and make sure you have followed its instructions.

**Comment by wookayin** [comment]
It's a font issue. Learn about https://www.nerdfonts.com/
