### ISSUE TITLE
Lua cmdline completion leaves duplicated prefix at end of options

### ISSUE THREAD

**Issue by frangio** [neovim/neovim#28840]
### Problem

In the command line, completion for the `:lua` command leaves behind a duplicated prefix after traversing all completions options with `<Tab>` or going back from the first one with `<S-Tab>`.

### Steps to reproduce

```
nvim --clean
:lua vim.<Tab><S-Tab>
```

### Expected behavior

The command line should read `:lua vim.` but it reads `:lua vim.vim.`

### Neovim version (nvim -v)

v0.10.0

### Vim (not Nvim) behaves the same?

no (no :lua completion)

### Operating system/version

macOS 14.4.1

### Terminal name/version

Wezterm 20240203-110809-5046fc22

### $TERM environment variable

wezterm

### Installation

build from repo

**Comment by glepnir** [comment]
fixed by https://github.com/neovim/neovim/pull/29587

**Comment by zeertzjq** [comment]
No, this was fixed by #29384.

**Comment by glepnir** [comment]
Aha I mixed up the commits
