### ISSUE TITLE
TUI Cursor color should follow hi-Cursor

### ISSUE THREAD

**Issue by borring** [neovim/neovim#2884]
This will bring nvim one step closer to gvim in terms of color support.

**Comment by justinmk** [comment]
I'm not sure there is even a term code for cursor color. Terminal.app certainly doesn't support it. Can you name a terminal that does?

**Comment by bfredl** [comment]
urxvt and `gnome-terminal` has it at least, but I don't think it has been "standardized" anywhere.

**Comment by smasher816** [comment]
Perhaps this will help. http://ass.kameli.org/cursor_tricks.html

**Comment by vheon** [comment]
I change the cursor color based on the mode [vheon/vim-cursormode](/vheon/vim-cursormode) but it is not perfect surely.

**Comment by zhou13** [comment]
When using TUI and `list` together, your cursor color will be come the color of `NonText` because of the existance of EOL.  If that is a low-contrast color and you are using vertical line cursor, it is really hard to see where your cursor is.

**Comment by justinmk** [comment]
This was partially implemented in the TUI support for 'guicursor'. https://github.com/neovim/neovim/pull/6044

Currently IIRC only iTerm is supported. Support for other specific terminals should be requested in a new ticket, with link to documentation of the terminal capability.
