### ISSUE TITLE
'Invalid node type "modeline"' query error in decoration provider treesitter/highlighter.win when viewing helpfiles

### ISSUE THREAD

**Issue by afh** [neovim/neovim#28846]
### Problem

Any key strokes the navigate the help switch focus to the error buffer showing the error below, rending the help buffer useless as it cannot be explored

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...d-0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error
at 58:2. Invalid node type "modeline":
(modeline) @keyword.directive
 ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...d-0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...pped-0.10.0/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...pped-0.10.0/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
        ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tre
e'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prepare_high
light_states'
        ....0/share/nvim/runtime/lua/vim/treesi
```

### Steps to reproduce

nvim --clean +help

### Expected behavior

If errors during rendering of help pages occur the errors are only displayed once or are shown in a manner where the keyboard focus is kept on the original buffer

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1693350652

### Vim (not Nvim) behaves the same?

no, vim 9.0.2136

### Operating system/version

ProductName:            macOS ProductVersion:         14.4.1 BuildVersion:           23E224

### Terminal name/version

tmux 3.4 running in alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

nixpkgs

**Comment by afh** [comment]
Closing as this cannot be reproduced with the ["official" neovim build](https://github.com/neovim/neovim/releases/tag/v0.10.0)

**Comment by wookayin** [comment]
FYI, this is because the vimdoc TS parser is outdated and not compatible with the runtime query file. A "Nix" installation issue.

**Comment by afh** [comment]
Thank your for chiming in, @wookayin, that's helpful to know.

I guess out of excitement about 0.10.0, eagerness to install and use it and the frustration that it appeared so broken for me I hastily created this issue. I should've been more level headed and analysed the issue more thoroughly and narrowed it down before opening an issue.
Applying some common sense would've been helpful too, _if_ the latest official neovim release or neovim nixpkgs was "so broken" others would've very likely caught it already.

The good news: the issue is resolved; the bad news: I'm not sure why… Running `nix run nixpkgs#neovim -- --clean +help` is enough proof for me that the issue must've been with some oddity in my setup even thought "nothing changed" apart from installing new nixpkgs generations…

**Comment by bew** [comment]
> The good news: the issue is resolved; the bad news: I'm not sure why… Running `nix run nixpkgs#neovim -- --clean +help` is enough proof for me that the issue must've been with some oddity in my setup even thought "nothing changed" apart from installing new nixpkgs generations…

"nothing changed" that's not true, I made a PR to update the bundled tree-sitter parsers for neovim 0.10
https://github.com/NixOS/nixpkgs/pull/312312
And it recently hit the unstable branch, hence you're getting the new parsers which are compatible with nvim' queries 🙃

**Comment by afh** [comment]
I see… Thanks for clarifying, @bew, and thanks for the update 🙂
Maybe that's what I came across. A positive side-effect of this is that I'm spending some time with my vim setup, tailoring it to my needs and preferences.
