### ISSUE TITLE
Parse snippet failures

### ISSUE THREAD

**Issue by folke** [neovim/neovim#28858]
### Problem

This is a tracking issue for snippets I encountered that fail to parse using `vim.snippet.expand`

# Snippets

- [ ] Recursive placeholders don't seem to be supported
  ```lua
  f = io.open(${1:"${2:filename}"}, "${3:r}")
  
  while true do
	  line = f:read()
	  if line == nil then break end
  
	  ${0:-- code}
  end
  ```

### Neovim version (nvim -v)

nightly

**Comment by MariaSolOs** [comment]
Yes, this is part of the snippet roadmap: https://github.com/neovim/neovim/issues/25696

I’m confused about the title of this issue though. Wdym with parsing snippet failures @folke?

**Comment by folke** [comment]
I wasn't aware of the roadmap and current limitations, so thank you for pointing that out.

I've added a work around for nested placeholders in LazyVim.

Closing...
