### ISSUE TITLE
CheckHealth fails after gem install neovim using asdf

### ISSUE THREAD

**Issue by npearson72** [neovim/neovim#28859]
### Problem

I've tried setting the following, but it hasn't helped:

```
let g:ruby_host_prog="$HOME/.asdf/shims/neovim-ruby-host"
```

The ASDF Ruby is set globally and works just fine.
```
➜ ruby -v
ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-darwin23]
```

The gem is installed
```
➜ gem list | grep neovim
neovim (0.9.1)
```

I'm able to access the `neovim-ruby-host`
```
➜ $HOME/.asdf/shims/neovim-ruby-host
Can't run neovim-ruby-host interactively.
```

But when I do a `:checkhealth` I get:
```
provider.ruby: require("provider.ruby.health").check()

Ruby provider (optional) ~
- Ruby: ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-darwin23]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim
```

### Steps to reproduce

Call `:checkhealth`

### Expected behavior

I would expect that `neovim-ruby-host` would be found.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no such command

### Operating system/version

macOS 14.5 (23F79)

### Terminal name/version

alacritty 0.14.0-dev

### $TERM environment variable

tmux-256color

### Installation

homebrew

**Comment by matthewrosse** [comment]
I have same issue. Anyone got some clue?

**Comment by npearson72** [comment]
Thanks @wookayin. Confirm that it works in 11.0-dev
