### ISSUE TITLE
Neovim Qt is is not included in the Neovim `0.10.0` stable release for Windows

### ISSUE THREAD

**Issue by kalocsaibotond** [neovim/neovim#28864]
### Problem

I downloaded the latest stable Neovim released, and when I looked into the its directory, I could not find an `nvim-qt.exe`.
I looked around in the [official "change log"](https://neovim.io/doc/user/news-0.10.html) and I could not found any explicit indication that Neovim Qt was deliberately removed. Hencewhy I considered it a bug.

### Steps to reproduce

Set-Location ~\Downloads\
Invoke-RestMethod https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-win64.zip -OutFile nvim-win64.zip
Expand-Archive nvim-win64.zip .
Set-Location .\nvim-win64\
Get-Childitem . -Include nvim-qt.exe -Recurse

### Expected behavior

`nvim-qt.exe` is not found and is not listed.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

Wezterm / 20240203-110809-5046fc22

### $TERM environment variable

""

### Installation

scoop / manual zip download, extract

**Comment by clason** [comment]
Duplicate. Please search closed issues.

**Comment by dundargoc** [comment]
https://github.com/neovim/neovim/pull/23668
