### ISSUE TITLE
With ext_cmdline activated the buffer used for incsearch and command-preview is not the last buffer before entering cmdline_mode

### ISSUE THREAD

**Issue by smilhey** [neovim/neovim#28868]
### Problem

When using activating ext_cmdline, if I put the cursor in a float window during a substitution command, command-previews uses the buffer in the float instead of the current buffer. You see the effect when setting the enter field in nvim_open_win to true and then entering :%s/ ...

### Steps to reproduce

```lua
local function on_cmdline_show()
	local buf = vim.api.nvim_create_buf(false, true)
	local win = vim.api.nvim_open_win(buf, false, {
		relative = "editor",
		width = 50,
		height = 10,
		row = 1,
		col = 10,
		style = "minimal",
	})
	vim.api.nvim__redraw({ flush = true, cursor = true })
end

local function handler(event, ...)
	if event == "cmdline_show" then
		on_cmdline_show()
	else
		return
	end
end

local namespace = vim.api.nvim_create_namespace("cmdline")
local function attach()
	vim.ui_attach(namespace, { ext_cmdline = true }, function(event, ...)
		handler(event, ...)
		if event:match("cmd") ~= nil then
			return true
		end
		return false
	end)
end

attach()
```

### Expected behavior

I would expect the current buffer to be the last buffer before entering cmdline mode. 

### Neovim version (nvim -v)

0.11.0-dev-19+g0f4f7d32c

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Fedora Linux 40

### Terminal name/version

kitty 0.34.1

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by luukvbaal** [comment]
Why are are you providing a minimal init.lua and then giving another condition in the problem description. Is there a problem with this init.lua or is there just a problem when setting `enter == true`?

The point of `nvim__redraw->cursor == true` is that it allows moving the cursor to a window that is **not** the actual current window. Entering the cmdline window seems ill advised and changing the current window/buffer should probably be disallowed during cmdline callbacks.

**Comment by smilhey** [comment]
Just when setting enter == true. 
That part was not clear to me in the doc but i guess it explains the distinction that you make "win or the current window". Changing to this does not draw the cursor in the float. Is that expected ? 

```lua
local function on_cmdline_show()
	local buf = vim.api.nvim_create_buf(false, true)
	local win = vim.api.nvim_open_win(buf, false, {
		relative = "editor",
		width = 50,
		height = 10,
		row = 1,
		col = 10,
		style = "minimal",
	})
	vim.api.nvim_win_set_cursor(win, { 1, 0 })
	vim.api.nvim__redraw({ flush = true, cursor = true })
end
```

**Comment by luukvbaal** [comment]
Uhm not sure, but you shouldn't create a buffer and open a window on each `cmdline_show` event. Try creating them once(hiding/showing as needed), and your `nvim__redraw` call should target `win = win`; then it does work:

```lua
local buf = vim.api.nvim_create_buf(false, true)
local win = vim.api.nvim_open_win(buf, false, {
	relative = "editor",
	width = 50,
	height = 10,
	row = 1,
	col = 10,
	style = "minimal",
})

local function on_cmdline_show()
	vim.api.nvim_win_set_cursor(win, { 1, 0 })
	vim.api.nvim__redraw({ win = win, cursor = true })
end
```

**Comment by smilhey** [comment]
Obviously I'm not doing that for real use ! Still it seems the window needs to be explicitly drawn before the cursor drawing which I guess is quite logical. 
This also works 

```lua 
	local buf = vim.api.nvim_create_buf(false, true)
	local win = vim.api.nvim_open_win(buf, false, {
		relative = "editor",
		width = 50,
		height = 10,
		row = 1,
		col = 10,
		style = "minimal",
	})
	vim.api.nvim__redraw({flush = true})
	vim.api.nvim_win_set_cursor(win, { 1, 0 })
	vim.api.nvim__redraw({ win = win, cursor = true })

```
Thanks for your help !

**Comment by luukvbaal** [comment]
> Still it seems the window needs to be explicitly drawn before the cursor drawing which I guess is quite logical. 

Not "drawn" necessarily, what needs to happen is for the grid to be allocated(which happens to be done in `flush->update_screen()`. Probably should be done with `cursor == true` as well to avoid unexpected behavior.
