### ISSUE TITLE
distinguish certain CTRL chords (<c-n> and <c-s-n>)

### ISSUE THREAD

**Issue by borring** [neovim/neovim#2886]
One of neovim's new features is the use of key chords even within terminals. I'm
using a mapping `<c-n>` and another mapping `<c-s-n>` and nvim can't seem to
tell the difference. It defaults to the `<c-s-n>` mapping (it's declared later
in the .nvimrc)

```
    NVIM 0.0.0-alpha+201506222256 (compiled Jun 23 2015 18:48:05)
    Commit: 20a57c497b55bb3632f0d4bcd76c18628cfa5f43
    Build type: Debug
    Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/moymoy/neovim/build/config -I/home/moymoy/neovim/src -I/home/moymoy/neovim/.deps/usr/include -I/home/moymoy/neovim/.deps/usr/include -I/home/moymoy/neovim/.deps/usr/include/luajit-2.0 -I/home/moymoy/neovim/.deps/usr/include -I/home/moymoy/neovim/.deps/usr/include -I/home/moymoy/neovim/.deps/usr/include -I/home/moymoy/neovim/.deps/usr/include -I/usr/include -I/home/moymoy/neovim/build/src/nvim/auto -I/home/moymoy/neovim/build/include
    Compiled by moymoy@navi-laptop

    Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
    For differences from Vim, see :help vim-differences

         system vimrc file: "$VIM/nvimrc"
             user vimrc file: "~/.nvimrc"
     2nd user vimrc file: "~/.nvim/nvimrc"
                user exrc file: "~/.exrc"
        fall-back for $VIM: "/usr/local/share/nvim"
```

**Comment by borring** [comment]
> added this to the **wishlist** milestone

Shouldn't this be marked as a bug instead? This feature is supposed to already
be in nvim as per `:help nvim-features-new`

**Comment by justinmk** [comment]
Meta/alt bindings are pretty much complete (isn't that enough?! :grin: ), but many `ctrl` chords are not possible out-of-the-box. 

The issue with ctrl-shift in particular is discussed at length here: https://github.com/neovim/neovim/pull/1820#issuecomment-73575112

> Shouldn't this be marked as a bug instead? This feature is supposed to already
be in nvim as per :help nvim-features-new

It's not totally clear from that doc (I'll update it), but only the explicitly listed chords are known (by me, at least) to work:

```
  <C-Tab>, <C-S-Tab>  
  <C-BS>, <C-S-BS>
  <C-Enter>, <C-S-Enter>
```

`ctrl-shift-[a-zA-Z]` in particular do *not* (and cannot) work in the terminal unless (1) the user configures the terminal to send extended CSI sequences and (2) Neovim defines `<C-S-foo>` key formats which has some unpleasant compatibility concerns.

Again, @ZyX-I explains it well in https://github.com/neovim/neovim/pull/1820#issuecomment-73575112 , he may correct anything I have said here.

**Comment by borring** [comment]
I just tried the rest of the CTRL- examples in the docs.
Actually, none of them work.

I tried them with and without Shift.
`<C-Tab>, <C-BS>, <C-Enter>`

**Comment by borring** [comment]
I just tried the rest of the CTRL- examples in the docs. Actually, none of them
work.

I tried them with and without Shift.
`<C-Tab>, <C-BS>, <C-Enter>`

**Comment by justinmk** [comment]
That's really dependent on your terminal. They work for me in mintty, and they will work in any terminal that sends the expected sequences.

**Comment by borring** [comment]
I'm using gnome-terminal. It also doesn't seem to be working in Konsole, Xterm, rxvt-unicode either.

What mappings did you test with? I'm doing a simple: `nnoremap <C-Tab> i` to see if nvim goes into insert mode.

**Comment by borring** [comment]
I'm using gnome-terminal. It also doesn't seem to be working in `Konsole`, `Xterm`, `rxvt-unicode` either.

What mappings did you test with?
I'm doing a simple: `nnoremap <C-Tab> i` to see if nvim goes into insert mode.

I also noticed that the mappings are case-sensitive when using Alt
`nnoremap <a-b> i` takes Alt + b to get into insert mode
`nnoremap <a-B> i` takes Alt + Shift + b to get into insert mode
The same isn't true for Ctrl. That seems kinda arbitrary.

**Comment by justinmk** [comment]
I tested with all of the mappings that are listed, with `mintty`. I'll verify later.

**Comment by strokirk** [comment]
@justinmk If you are updating `runtime/doc/vim_diff.txt`, could you add a note on how `nvim` handles <kbd>Alt</kbd>-chords? I believe that it sets the eight bit on the character typed, which means that for example `e` (0x65) becomes `å` (0xE5). So <kbd>Alt</kbd>-chords have the risk of conflicting with normal characters on the user's keyboard, and can only be mapped for codepoints in the ascii range. 

It would probably be good to have this information in the docs, since I remember having trouble with it myself.

**Comment by justinmk** [comment]
> I tested with all of the mappings that are listed, with mintty. I'll verify later.

Verified. All of these work in `mintty`:

```
:nn <c-s-tab> :echo 'cstab'<cr>
:nn <c-tab> :echo 'ctab'<cr>
:nn <tab> :echo 'tab'<cr>
:nn <s-tab> :echo 'stab'<cr>
```

**Comment by borring** [comment]
:nn <c-s-tab> :echo 'cstab'<cr>
stab

:nn <c-tab> :echo 'ctab'<cr>
tab

:nn <tab> :echo 'tab'<cr>
tab

:nn <s-tab> :echo 'stab'<cr>
stab

**Comment by justinmk** [comment]
@borring Thanks for the data point. Shift-Tab seems to work everywhere, even in Vim, so it's not really related to this issue I guess.

**Comment by borring** [comment]
@justinmk I just tried the test again:

	:nn <c-s-tab> :echo 'cstab'<cr>
	:nn <c-tab> :echo 'ctab'<cr>
	:nn <tab> :echo 'tab'<cr>
	:nn <s-tab> :echo 'stab'<cr>

It still doesn't work in the terminal with the newest nvim. I did however, try it with a QT gui [equalsraf/neovim-qt](https://github.com/equalsraf/neovim-qt) and every single mapping worked.

I guess we can safely assume it's not my window manager catching the keys. It's something to do with the TUI.

**Comment by thinker3** [comment]
There can be an option to enable case-sensitive ctrl-chords, or not for legacy plugins

**Comment by justinmk** [comment]
"Make it an option" is not really worth mentioning, it is an ever-present possibility, always a last resort, and adds complexity to the codebase.

**Comment by tombh** [comment]
Just wanted to check if this is the official issue for case sensitive CTRL chords (eg; CTRL+SHIFT+n)? Would love to see this implemented. I don't imagine `<c-s-n>` breaking backwards compatibility, but it's also weird that the syntax isn't the same as for META, ie `<a-N>`. Oh Vim!

**Comment by mallochine** [comment]
Can we have a clarification on the escape sequences that Neovim is expecting? I tried "\x1b[27;5;6~" for ctrl-tab and neovim doesn't fire the mapping. So right now I'm guessing Neovim must be looking for the CSI escape sequences instead.

**Comment by mallochine** [comment]
Hm I just realized -- is Ctrl-Tab not supported in linux terminals? I'm using neovim via SSH

**Comment by ZyX-I** [comment]
@mallochine Some terminals may be configured to emit `\e[27;5;9~` for `<C-Tab>`. E.g. I can configure konsole to do that so I get `<C-Tab>` when typing `<C-v><C-Tab>`.

**Comment by ZeroKnight** [comment]
>Some terminals may be configured to emit \e[27;5;9~ for <C-Tab>. E.g. I can configure konsole to do that so I get <C-Tab> when typing <C-v><C-Tab>.

@ZyX-I What is the general way to go about this? I've [seen elsewhere](https://www.staldal.nu/tech/2009/01/10/how-to-use-ctrl-tab-in-gnu-screen/) that it's possible by tweaking .Xresources, but is that only for xterm? How do you do this with vte-based terminal emulators?

For what it's worth, I currently use termite, but at this point I'm willing to switch to any minimal terminal emulator that can actually send `<C-Tab>` and the like.

**Comment by ZyX-I** [comment]
@ZeroKnight I know only about konsole. And what I know is not actually good: you can configure `<C-Tab>`, `<C-S-n>` or whatever. But you should configure *one* shortcut at a time, yielding a big list.

**Comment by justinmk** [comment]
@mallochine @ZeroKnight when talking about terminal features it is important to mention `$TERM` and whether it really matches your actual terminal. See `:h $TERM` in the latest master version of Nvim.  Currently we listen to terminfo so if your terminfo is wrong that's also a problem.

**Comment by ZeroKnight** [comment]
@justinmk Right, sorry. I should have been more clear, but `<C-Tab>` not working in Termite isn't so much related to terminfo as it is that Termite itself uses various chords to do things like copy/paste, with `<C-Tab>` bound to "scrollback completion". As far as I know, there's currently no way to change or disable these keybinds, so Termite simply *cannot* send `<C-Tab>` in its current state.

For what it's worth, my `$TERM` was `tmux-256color`, originally set to `xterm-256color` outside of tmux.

Doing some more research since my initial message, I stumbled upon *pangoterm*, which *does* send chords like `<C-Tab>` and similar that Nvim supports, and they do indeed work: `:nmap <C-Tab> :echo 'Hooray!'<CR>` does what you would expect. This is basically all I wanted out of Termite, and given that both are very light without unnecessary features like tabs, I've found my new TE, and my chord usage troubles are now over. Thank you, leonerd!

**Comment by luxmeter** [comment]
Hi guys. I'm not sure if I can follow the thread. I have here an issue that might be related.
I configured my ITerm2 to send `^[[68;5u` when I press `Ctrl-Shift-D`. It looks like that Neovim ignores the sequence and pretend to got `^D` (`Ctrl-D`).
I tested it in VIM and there it works.
Is this a bug?

**Comment by zeertzjq** [comment]
After #12592 #17771 #18181 I don't think there is anything else in Nvim that needs to be done about this issue.

Changing case sensitivity for `<C-` will break a lot of plugins, including many new plugins.

For terminal emulators that don't support modifyOtherKeys or CSI u but support configuring keys to emit different escape sequences, these sequences can be used (where `\x1b` is the ESC character):
- `<C-Tab>`: `\x1b[9;5u`
- `<C-S-Tab>`: `\x1b[9;6u`
- `<C-CR>`: `\x1b[13;5u`
- `<C-S-CR>`: `\x1b[13;6u`
- `<C-BS>`: `\x1b[127;5u`
- `<C-S-BS>`: `\x1b[127;6u`
