### ISSUE TITLE
Priorotise ambiguous ex commands

### ISSUE THREAD

**Issue by noahgitsham** [neovim/neovim#28869]
### Problem

I used to use `:E` for `:Explore`, however in the 0.10 release, Neovim now also provides `:EditQuery` with an update to treesitter, meaning I cannot now use this by default. This is essentially a breaking change for my workflow.

A simple fix in my use case was to create my own command:
`vim.api.nvim_create_user_command("E", function () vim.cmd("Explore") end, {})`, however it still feels wrong that the default behaviour has changed.

### Expected behavior

I'm not sure on the details of how this would be best implemented, however I don't like that essential Vim built-in commands are conflicting with new additions.

Perhaps Vim built-in ex commands should automatically take priority over ones provided by Neovim.

**Comment by clason** [comment]
`:Explore` is _not_ an "essential Vim built-in command"; it's a command provided by the (bundled) plugin netrw (which we plan to remove and replace with a more suitable, modern, alternative anyway).

("Proper" built-in commands do not start with upper-case letters, for precisely this reason.)
