### ISSUE TITLE
Disable built-in formatting for zig

### ISSUE THREAD

**Issue by flexagoon** [neovim/neovim#28878]
### Problem

By default, nvim's Zig ftplugin will format zig files on save:

https://github.com/neovim/neovim/blob/666911be917d60ba3a19a4b56bbf1e8c16da5297/runtime/ftplugin/zig.vim#L61

This is very confusing, since this behavior is not documented anywhere, and users expect nvim not to format anything unless they configure it to do so.

### Steps to reproduce

Have `zig` installed

`nvim --clean test.zig`

```zig
pub const Test= enum { Foo,
    Bar};
```

Save the file and it will be automatically formatted

### Expected behavior

Nvim should not do any automatic formatting by default which requires an undocumented global variable to disable.

At least the default value should be changed to `0` to disable this setting by default.

### Neovim version (nvim -v)

NVIM v0.11.0-dev+18-g63e3a63d2

### Vim (not Nvim) behaves the same?

Yes, vim 9.1

### Operating system/version

Fedora Silverblue 40

### Terminal name/version

Wezterm

### $TERM environment variable

xterm-256color

### Installation

Occurs with any installation method

**Comment by zeertzjq** [comment]
It seems that this only documented in the README of https://github.com/ziglang/zig.vim

**Comment by flexagoon** [comment]
@zeertzjq it is absolutely not clear that you have to look in a readme of some third-party repo for a solution to the issue. If this behavior is to be kept, it should at least be added as a `:h` file. Though I still think that it should not be on by default.

**Comment by zeertzjq** [comment]
There seems to be some ongoing effort:
- https://github.com/vim/vim/pull/13803
- https://github.com/ziglang/zig.vim/issues/51

But it's not clear where it is going.

**Comment by flexagoon** [comment]
@zeertzjq the https://github.com/ziglang/zig.vim/issues/51 issue was closed due to not enough interest, but since then, many people have commented on it saying that this behavior is annoying. I think even if this change won't be made in upstream zig.vim, it should be made in Neovim to have better defaults.

**Comment by clason** [comment]
We do not maintain these files; please contact the maintainer listed at the top of the file and propose the change; if there is no response, you may raise an issue at vim/vim directly. If they make the change, we will port it; otherwise not.

**Comment by flexagoon** [comment]
@clason why can't nvim change ftplugins independently of vim? Is that for compatibility reasons?

**Comment by clason** [comment]
Yes (and to make sure that any improvements benefit both projects). This is an ironclad project policy.

**Comment by gpanders** [comment]
I've opened a PR with Vim to change the default https://github.com/vim/vim/pull/14820.

**Comment by flexagoon** [comment]
@gpanders perhaps you could continue the work in the existing PR?

https://github.com/vim/vim/pull/13803

It is a full refactor of the zig ftplugin, so I think it'd be better to merge that, seems like the only thing it misses is documentation for one variable.

**Comment by flexagoon** [comment]
@clason vim merged the PR with the fix. Will it be downstreamed into nvim automatically?

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/how-should-i-troubleshoot-an-issue-causing-neovim-to-freeze-when-saving/4881/4
