### ISSUE TITLE
vsp term:// does not work as expected

### ISSUE THREAD

**Issue by badeip** [neovim/neovim#2887]
1) I expect a shell to be executed, similar to `:term`
2) The terminal split is not in insert mode, so it is not possible to close the split according to the printed message  `[Program exited, press any key to close]`

    NVIM 0.0.0-alpha+201506240043 (compiled Jun 24 2015 08:38:49)
    Commit: 91fcd3378750080fb94d3030a6fc29a4f86b15e8
    Build type: Release

**Comment by mhinz** [comment]
Is this really a bug?

Actually I don't expect `:edit` and friends to switch to insert mode. What is `term://` anyway apart from being a pattern that matches all terminal buffers? `:h nvim-terminal-emulator-spawning` gives this regexp: `term://(.{-}//(\d+:)?)?\zs.*`. `term://` doesn't fulfill this.

I think that's exactly what `:terminal` is for, so `:vs +term` should have been used in the first place.

IMHO, this behaviour is correct.

**Comment by badeip** [comment]
Call it what you want, just expect similar reports when people are unable to close the terminal buffer according to the printed message.
Besides, `:edit` is useful `:term` isn't

**Comment by justinmk** [comment]
Ok, I didn't read this carefully when I triaged it.

> The terminal split is not in insert mode, so it is not possible to close the split according to the printed message [Program exited, press any key to close]

That message/feature is going to be removed anyways. Use normal window commands to close a term:// buffer/window.
