### ISSUE TITLE
feedkeys with esc no behaving as expected in cmdline mode 

### ISSUE THREAD

**Issue by smilhey** [neovim/neovim#28877]
### Problem

When remapping to ESC in commandline mode, using nvim_feedkeys the new mapping behaves as execute command. 

### Steps to reproduce

```lua
local ESC = vim.api.nvim_replace_termcodes("<esc>", true, false, true)
vim.keymap.set("c", "<F1>", function()
	vim.api.nvim_feedkeys(ESC, "n", false)
end, {})
```

### Expected behavior

<F1> should exit commandline 

### Neovim version (nvim -v)

0.11.0-dev-34+g91892f56b

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Fedora Linux 40

### Terminal name/version

kitty 0.34.1

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
Add the `t` flag
