### ISSUE TITLE
autocmd only works once after upgrade to 0.10.0

### ISSUE THREAD

**Issue by telbizov** [neovim/neovim#28874]
### Problem

Hello,

I have the following setup:

```
vim.api.nvim_create_autocmd("CursorHold", {
    once = false,
    callback = vim.diagnostic.open_float,
})
```

This used to work just fine before I upgraded to 0.10.0. It used to show the diagnostic float window *every time* when I positioned the cursor over the line of code that had the problem. If I moved out and back in it would show it again. After upgrade it now only pops up once after starting neovim. It seems like a regression. Or perhaps I need to modify the config somehow?

Thanks

### Steps to reproduce

Try the config above

### Expected behavior

Show the diagnostic float window every time. I.e. trigger the callback repeatedly not, only once!

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

N/A because I need LSP

### Operating system/version

macOS 14.4.1

### Terminal name/version

iTerm2 3.4.23

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by clason** [comment]
Any return value will delete the callback, see :h news.

**Comment by telbizov** [comment]
Roger that.
I had this code piece before and it used to work but I am far from an expert in neovim and Lua. Now that I took a closer look the following is what it should be:

```
vim.api.nvim_create_autocmd("CursorHold", {
    callback = function(ev)
        vim.diagnostic.open_float()
        return false
    end,
})
```

This works now!

Thanks for the pointers
