### ISSUE TITLE
Loading plugin jalcine/cmake.vim takes > 30 seconds with current master

### ISSUE THREAD

**Issue by languitar** [neovim/neovim#2888]
I just updated to the current master version of neovim and noticed that startup suddenly takes ages with the screen being blank for > 30 seconds. After commenting things out I can tell that this delay is caused by adding jalcine/cmake.vim (via NeoBundle). With a master version from approximately 2 weeks ago this does not happen.

A startup time file can be found here:
https://gist.github.com/languitar/7543cd8457449b3366af

**Comment by Pyrohh** [comment]
Could you try bisecting said plugin to see if the issue is there? Also you haven't provided version information, although if you're using a package manager to update you're probably not using a debug version of nvim.

**Comment by languitar** [comment]
```
jwienke@cinnabar ~> nvim --version
NVIM 0.0.0-alpha+201506240043 (compiled Jun 24 2015 10:40:38)
Commit: 91fcd3378750080fb94d3030a6fc29a4f86b15e8
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/homes/jwienke/local/trusty/x86_64/src/neovim/build/config -I/homes/jwienke/local/trusty/x86_64/src/neovim/src -I/homes/jwienke/local/trusty/x86_64/src/neovim/.deps/usr/include -I/homes/jwienke/local/trusty/x86_64/src/neovim/.deps/usr/include -I/homes/jwienke/local/trusty/x86_64/src/neovim/.deps/usr/include/luajit-2.0 -I/homes/jwienke/local/trusty/x86_64/src/neovim/.deps/usr/include -I/homes/jwienke/local/trusty/x86_64/src/neovim/.deps/usr/include -I/homes/jwienke/local/trusty/x86_64/src/neovim/.deps/usr/include -I/homes/jwienke/local/trusty/x86_64/src/neovim/.deps/usr/include -I/usr/include -I/homes/jwienke/local/trusty/x86_64/src/neovim/build/src/nvim/auto -I/homes/jwienke/local/trusty/x86_64/src/neovim/build/include
Compiled by jwienke@cinnabar

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/homes/jwienke/local/trusty/x86_64/share/nvim"
```

I did not update the plugin and with a previous version of nvim it was working correctly. Last commit in my plugin git repo for the cmake plugin is from June 10. So nothing changed there within the last days.

**Comment by languitar** [comment]
Ok, I have to withdraw the issue. Maybe this was caused by some other general problem in our NFS setup. Today everything works again.

**Comment by jszakmeister** [comment]
> Build type: Debug

FWIW, if you want faster performance, you should use a release build.  See [Optimized Builds](https://github.com/neovim/neovim/wiki/Building-Neovim#optimized-builds) for more information.

**Comment by languitar** [comment]
Sure, but in case of crashes I'd like to be able to generate useful reports ;)

**Comment by jszakmeister** [comment]
RelWithDebInfo is still useful in that case.  You get some optimizations (if the compiler supports -Og, or full -O2 optimizations if it doesn't) but debug info is still present, so you can get stacktraces, etc.  There's always the possibility of recompiling elsewhere and reproducing it with debug too.  It's a little more trouble, but if you're using it everyday it may be a good idea.  The release build is substantially faster than the debug build. :-)

**Comment by languitar** [comment]
Actually I do not specify any build type option and the cmake default is RelWithDebInfo. So building Debug per default must be a setting somewhere in the wrapper Makefile or the CMake scripts of neovim themselves. Any reason for this?

**Comment by jszakmeister** [comment]
Do you have a local.mk file?

**Comment by jszakmeister** [comment]
Also, if you're just rebuilding and not doing a distclean and rebuilding, then CMake will reuse the cached value.

**Comment by languitar** [comment]
No, the default is in the utility makefile:
```
CMAKE_BUILD_TYPE ?= Debug

CMAKE_FLAGS := -DCMAKE_BUILD_TYPE=$(CMAKE_BUILD_TYPE)
```
To preserve CMake defaults one should only set `CMAKE_BUILD_TYPE` it is specified by the user.

**Comment by jszakmeister** [comment]
Hah, that's right!  I wonder if we should switch the default there... or simply remove the defaulting that is being done for the build type?  For now, you can use a local.mk and specify what you want in there.

**Comment by languitar** [comment]
actually I don't even understand why there is a Makefile with CMake being the build system. In any way, I would always favor keeping the defaults CMake provides just to be consistent with expectations.

**Comment by languitar** [comment]
Actually, I am also back at the longish start time here now that I compiled with RelWithDebInfo. Might be unrelated to that, but still I am experiencing this issue.

What is strange is that I can cancel the blocking of nvim with Ctrl+C and then continue to work as normal.

**Comment by jszakmeister** [comment]
> actually I don't even understand why there is a Makefile with CMake being the build system.

CMake is foreign to many people, so make is used to help keep things simple.

**Comment by jszakmeister** [comment]
> Actually, I am also back at the longish start time here now that I compiled with RelWithDebInfo. Might be unrelated to that, but still I am experiencing this issue.

:-(  Hopefully one of the other developers can chime in and help.

**Comment by fwalch** [comment]
Just installed the plugin, and my startup time is fine..

```
129.712  000.947: BufEnter autocommands                                                                                                                    
129.716  000.004: editing files in windows                                                                                                                 
131.612  000.226  000.226: sourcing /home/florian/.vim/plugged/cmake.vim/autoload/cmake/targets.vim                                                        
131.988  000.138  000.138: sourcing /home/florian/.vim/plugged/cmake.vim/autoload/cmake/util.vim                                                           
132.623  000.217  000.217: sourcing /home/florian/.vim/plugged/cmake.vim/autoload/cmake/commands.vim                                                       
132.823  002.526: VimEnter autocommands                                                                                                                    
132.826  000.003: before starting main loop                                                                                                                
133.882  001.056: first screen update                                                                                                                      
133.885  000.003: --- NVIM STARTED ---
```

nvim version:

```
NVIM 0.0.0-alpha+201506222256 (compiled Jun 23 2015 13:03:43)
Commit: 20a57c497b55bb3632f0d4bcd76c18628cfa5f43
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=native -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTI
FY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFI
G_H -I/home/florian/Projects/Arch4/neovim-git/src/neovim-git/build/config -I/home/florian/Projects/Arch4/neovim-git/src/neovim-git/src -I/usr/include -I/usr/in
clude -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/florian/Projects/Arch4/neovim-git/src/neovim
-git/build/src/nvim/auto -I/home/florian/Projects/Arch4/neovim-git/src/neovim-git/build/include                                                                                                                                              
```

From your log, it looks like most time is spent in `VimEnter`? Do you have a custom autocmd set up for that in your `.nvimrc`?

**Comment by languitar** [comment]
No, nothing defined in my `.nvimrc`. But to reproduce this, here's the full config file:
https://gist.github.com/languitar/4519fab1a2c96dfd3a4f

**Comment by languitar** [comment]
The cmake plugin defines a single VimEnter autocommand:
```
autoload/cmake/augroup.vim:20:    au VimEnter      *  call cmake#augroup#on_vim_enter()
```
After looking at this a bit I think this might actually be caching by the cmake plugin going on here, which is causing the load. It might be that I always encountered this issue when starting nvim with PWD being the home directory.

**Comment by justinmk** [comment]
`cmake#augroup#on_vim_enter()` could be a good use-case for Neovim job control. What do you think @jalcine ?

**Comment by jalcine** [comment]
@languitar I'll open an issue on jalcine/cmake.vim about this.
@justinmk Definitely a chance to check it out; though most of the crunching is done in Vimscript (for portability).

**Comment by justinmk** [comment]
@jalcine I didn't realize the bottleneck was vimscript. In that case, you should probably wait until we finish an upcoming feature which will allow `nvim` to act as a client to another `nvim` instance (which would allow a plugin like cmake.vim to offload processing to the child `nvim` instance, and unblock the parent UI).

**Comment by jalcine** [comment]
Hey @justinmk is there a particular issue where I can track said feature? It'd help me plan when I can start using it as well as give users for `cmake.vim` something to use in the interim.

**Comment by justinmk** [comment]
@jalcine  I created https://github.com/neovim/neovim/issues/3119 to track the key feature needed. Target is 0.2 milestone, which is probably end of the year, based on 0.1 progress.

**Comment by jalcine** [comment]
Thanks for the heads up! I'll see what I can do re: making plug-in faster.
