### ISSUE TITLE
Syntax highlighting can't be disabled

### ISSUE THREAD

**Issue by qbit** [neovim/neovim#28893]
### Problem

With `--clean`, `:syntax off` is inconsistently applied depending on the file type opened.

For example:
`nvim --clean -O /tmp/wat.lua /tmp/wat.sh`

When this starts up, highlighting is enabled. As expected. Now if you run `:syntax off`, the shell script un-highlights as expected, but the lua script does not.

where:

## `/tmp/wat.lua`:
```         
print("But we have highlighting here.")
```

## `/tmp/wat.sh`
```
echo "no highlighting here.";
```

### Steps to reproduce

nvim --clean -O /tmp/wat.lua /tmp/wat.sh
:syntax off

### Expected behavior

Highlighting should be disabled consistently.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

NixOS/24.05.20240520.baed31d

### Terminal name/version

Konsole 24.02.2

### $TERM environment variable

tmux-256color

### Installation

nix

**Comment by clason** [comment]
`:h news` (treesitter highlighting is now enabled by default for Lua files)

**Comment by zeertzjq** [comment]
Treesitter is not syntax.

**Comment by qbit** [comment]
> treesitter highlighting is now enabled by default for Lua files

Well how do I disable it?

**Comment by zeertzjq** [comment]
`:lua vim.treeesitter.stop()`
