### ISSUE TITLE
[refactor] create types and format modules

### ISSUE THREAD

**Issue by TheSnakeWitcher** [neovim/neovim#28892]
### Problem

I wonder if would be helpful to create the mentioned modules to group some functions in a similar way to those in the `vim.treesitter` module

### Expected behavior

For example, a `vim.fmt.{format}` or `vim.format.{format}` like

```lua
vim.fmt.base64.{method}
vim.fmt.json.{method}
vim.fmt.text.{method}
vim.fmt.mpack.{method}
```

A `vim.types.{type}` like

```lua      
vim.types.tbl.{method}  -- for all vim.tbl_* methods
vim.types.list.{method} -- for all vim.list_* methods
vim.types.str.{method}  -- for all vim.str_* methods
```

**Comment by clason** [comment]
This is deliberate: We prefer a "flat" hierarchy; that simplifies a few things (for example, you don't have to export local functions across modules).
