### ISSUE TITLE
Default :terminal palette colors could have better contrast in GUIs

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#28916]
_Originally posted by @craigmac in https://github.com/neovim/neovim/issues/26857#issuecomment-2123068602_

The current `:terminal` palette colors when using neovim from a gui results in poor contrast, in particular the blue on black combination is difficult to read. 

Can we improve the `nvim --clean` experience for GUI users, like in neovide, and _only_ when `has('gui_running')` (or however we detect that a GUI is attached/shown). My preference would be to use the default colorscheme shipped with 0.10 as the palette, as it provides a unified look and it has a better readability. Barring that, something like Chris Kempson's 'default dark' (recent Alacritty's switched to this from Tomorrow Night) is battle-tested and works better than the default xterm palette.

**Comment by craigmac** [comment]
Some images from Neovide 0.13 running Nvim 0.10 branch on macOS latest:

![Screenshot 2024-05-22 at 11 05 00 AM](https://github.com/neovim/neovim/assets/7416158/c8381254-9d8d-4f1a-b24b-6c9a8fab46d2)

Blue on black here isn't good, neighter is the white on green combo:

![Screenshot 2024-05-22 at 11 05 56 AM](https://github.com/neovim/neovim/assets/7416158/ae5120d2-f0f7-4e64-aa87-b604140662d0)

**Comment by justinmk** [comment]
Isn't that controlled by `$LSCOLORS` or some other shell-related env var?

**Comment by clason** [comment]
I agree that my "terminal colors should match parent shell" objection does not apply here, I am still hesitant to use the Neovim colors for terminal colors, for the following reason: Unlike Vim highlight groups, these colors (at least the first eight) are **named** by the ANSI standard (black, red, green, yellow, blue, magenta, cyan, white). And since the official Neovim branding is so minimal, we can't match these expectations.

**Comment by justinmk** [comment]
> And since the official Neovim branding is so minimal, we can't match these expectations.

Nonsense. There is no requirement that the colors match the names, only that they are distinguishable.

**Comment by justinmk** [comment]
What part are you quoting? I don't see any requirement on those pages about the colors needing to match the names. Otherwise they would not be configurable.

**Comment by clason** [comment]
The named list of colors. I never said anything about hard requirements, only about expectations. (And I already regret saying anything at all.)
