### ISSUE TITLE
All text is search-highlighted at startup

### ISSUE THREAD

**Issue by markuspeloquin** [neovim/neovim#28928]
### Problem

I usually update Neovim from master daily. Today when I start Neovim, it behaves as if I searched for `.`.

Debugging notes:
* Tried removing ~/.viminfo
* If I type `/`+Up, I don't see this in my search history.

![image](https://github.com/neovim/neovim/assets/75588/47c4c9ba-5fc5-4fbf-bf88-0c6c50977fee)

I think it might be related to this change. I see the problem on this commit but not the parent:
https://github.com/neovim/neovim/commit/b86381f425223adf0ff91fa0746914a5774ddabb
@zeertzjq @basilisk0315

### Steps to reproduce

```sh
nvim --clean -u minimal.lua ~/.vimrc
```

Either happens every time ... or not at all. Like restarting won't help the problem, but it might randomly flip.

### Expected behavior

Nothing is highlighted.

### Neovim version (nvim -v)

v0.11.0-dev-45+ge8f7025de (not sure about the 45, but the commit is correct ... I don't want to go back to a broken version)

### Vim (not Nvim) behaves the same?

no, vim 9.1.432

### Operating system/version

linux 6.8.0

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

tmux-256color

### Installation

source

**Comment by markuspeloquin** [comment]
The random flipping (always one or always the other) suggests to me that there's a race on uninitialized memory. The problem is the uninitialized memory, not the race.

**Comment by zeertzjq** [comment]
1. Nvim doesn't use `~/.viminfo`
2. What is the content of `minimal.lua`?
3. What is the content of `~/.vimrc`?

**Comment by zeertzjq** [comment]
Actually I may know what the problem is. This seems to be a shada problem.
