### ISSUE TITLE
Colorscheme without "gui" colors does not load on startup

### ISSUE THREAD

**Issue by angles-n-daemons** [neovim/neovim#28927]
### Problem

My preferred colorscheme is no longer loading in nvim 0.10.0 (worked in 0.9.5). The issue seems identical to #28791, though I believe the root cause wasn't addressed. Having read through #26378, the [recommended steps](https://github.com/neovim/neovim/commit/d431a4d410f02af2039d7c98e4e33136fd1e4849) for remediation don't seem to be applicable.

Looking for verification that this issue isn't related to the difference in highlight groups between the legacy and new defaults.

### Steps to reproduce

Using this configuration:
```lua
for name, url in pairs {
  papercolor = 'https://github.com/NLKNguyen/papercolor-theme'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

vim.cmd [[colorscheme PaperColor]]
```

Run vim and verify the colorscheme is not loaded:
`nvim --clean -u minimal.lua`

Optionally, if you want to manually source the vim colors within the colorscheme you can do so with the following command:
```bash
➜  nvim git:(main) ✗ sed -i='' '/hi clear/a \
source $VIMRUNTIME/colors/vim.lua \
' ./nvim_issue/papercolor/colors/PaperColor.vim
```

### Expected behavior

Expect colorscheme to be set on initial load

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no, vim 9.1

### Operating system/version

Mac OS 13.3

### Terminal name/version

iterm2 3.4.23

### $TERM environment variable

screen-256color

### Installation

from release tar

**Comment by leesmith** [comment]
I've been using solarized forever and now it stopped working with 0.10.0. I notice there's a lot mentioned about colors in the [release notes](https://neovim.io/doc/user/news-0.10.html#news-0.10).

**Comment by mustafaergul** [comment]
Same for me using kanagawa colors, here is the minimal config;
```
require('kanagawa').setup({
    compile = false,             -- enable compiling the colorscheme
    undercurl = true,            -- enable undercurls
    commentStyle = { italic = true },
    functionStyle = {},
    keywordStyle = { italic = true},
    statementStyle = { bold = true },
    typeStyle = {},
    transparent = false,         -- do not set background color
    dimInactive = false,         -- dim inactive window `:h hl-NormalNC`
    terminalColors = true,       -- define vim.g.terminal_color_{0,17}
    colors = {                   -- add/modify theme and palette colors
        palette = {},
        theme = { wave = {}, lotus = {}, dragon = {}, all = {} },
    },
    overrides = function(colors) -- add/modify highlights
        return {}
    end,
    theme = "wave",              -- Load "wave" theme when 'background' option is not set
    background = {               -- map the value of 'background' option to a theme
        dark = "wave",           -- try "dragon" !
        light = "lotus"
    },
})

-- setup must be called before loading
vim.cmd("colorscheme kanagawa")

```

**Comment by angles-n-daemons** [comment]
It doesn't appear this is related to the default colors, does it? The recommended adjustment doesn't address the issue. Could you try to run the sed command which applies the recommendation with the minimal configuration?

Let me know if I'm missing something else, my understanding of the issue is only at the surface.

**Comment by tomtomjhj** [comment]
It seems that
1. when loading init file, termguicolors is not set
2. so papercolor doesn't define colors for gui (maybe an optimization)
3. nvim 0.10's truecolor support detection kicks in, setting termguicolors
4. you see the default nvim gui colors

to avoid this, you can explicitly set or unset termguicolors before :colorscheme.

**Comment by angles-n-daemons** [comment]
Confirmed, adding the command to the above configuration fixes the issue. Thanks for the help!

```
for name, url in pairs {
  papercolor = 'https://github.com/NLKNguyen/papercolor-theme'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

vim.cmd[[set termguicolors]] -- this command fixes the issue
vim.cmd [[colorscheme PaperColor]]
```

Confirmed that the same fix works if it's added to the colorscheme:

```bash
$ sed -i='' '/hi clear/a \
set termguicolors \
' ./nvim_issue/papercolor/colors/PaperColor.vim
```

**Comment by angles-n-daemons** [comment]
What's the guidance to colorscheme developers to maintain compatibility with nvim going forward?

**Comment by clason** [comment]
Same as before: apply both `cterm*' and `gui*` variants for your highlight groups, and make sure you define (override) all default groups without relying on default links.
