### ISSUE TITLE
Failed to open .gitconfig

### ISSUE THREAD

**Issue by kneep** [neovim/neovim#28930]
### Problem

**Failed to open .gitconfig, even it's empty.**

Reproduce steps:
```
cd
touch .gitconfig
nvim .gitconfig
```

Error msg:
```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 28:2. Invalid node type "escape_sequence":
(escape_sequence) @string.escape
 ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...ovim/0.10.0/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...ovim/0.10.0/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
        ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prepare_highlight_states'
        ....0/share/nvim/runtime/lua/
```

Version:
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
```

### Steps to reproduce

```
cd
touch .gitconfig
nvim .gitconfig
```

### Expected behavior

Open with no error.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

no, vim 9.0.2142

### Operating system/version

macOS 14.5 (23F79)

### Terminal name/version

iTerm2 3.5.0

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
This seems to be a Homebrew problem.

**Comment by kneep** [comment]
> This looks like a Homebrew problem.

Just reinstalled neovim via homebrew, noting changed.

**Comment by kneep** [comment]
The weird thing is that ```.gitconfig``` is the only file I can find that can trigger this issue.

**Comment by wookayin** [comment]
You should reproduce using `nvim --clean`. Please read the minimum reproduction template. If you have a relevant config or plugins you're using, this should be posted as well. On a factory default `gitconfig` won't be highlighted using treesitter.

On the problematic buffer, what does the following print?

```
:echo &filetype
:lua= vim.treesitter.get_parser():lang()
:lua= vim.api.nvim_get_runtime_file('parser/git_config.so', true)
```

**Comment by kneep** [comment]
> You should reproduce using `nvim --clean`. Please read the minimum reproduction template. If you have a relevant config or plugins you're using (e.g. nvim-treesitter), this information should be posted as well. On a factory default `nvim --clean`, `gitconfig` won't be highlighted using treesitter.
> 
> On the problematic buffer, what does the following print?
> 
> ```
> :echo &filetype
> :lua= vim.treesitter.get_parser():lang()
> :lua= vim.api.nvim_get_runtime_file('parser/git_config.so', true)
> ```

Yes, more likely a tree-sitter issue. Thanks.
