### ISSUE TITLE
Italic property for other groups is forcedly ignored in italic string

### ISSUE THREAD

**Issue by sharpchen** [neovim/neovim#28945]
### Problem

Italic boolean property for highlight group(like `@punctuation.special`, `@punctuation.bracket`) are ignored inside a italic string. They are forcedly styled as italic.

![image](https://github.com/neovim/neovim/assets/77432836/42fa0533-1fea-4c9c-8403-b56176ad7265)

### Steps to reproduce

- make sure install treesitter parser for javascript
- create a js file and paste code sample

```js
testEmails.forEach(email => {                                                                                    
    console.log(`Is "${email}" a valid email? ${isValidEmail(email)}`);                                            
});
```
- switch to a colorscheme that have string non-italic
- `:hi @string gui=italic`

### Expected behavior

style as it is

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

no idea how to reproduce in vim

### Operating system/version

windows 10

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

xterm-256color

### Installation

scoop

**Comment by zeertzjq** [comment]
Use `nocombine`
