### ISSUE TITLE
UTF-8 Locale under Plasma has checkhealth reports UTF-8 not supported

### ISSUE THREAD

**Issue by SpookyYomo** [neovim/neovim#28948]
### Problem

I've found a similar issue in https://github.com/neovim/neovim/issues/26948 but I've reproduced differently.

## Setup
Neovim 0.10.0, Archlinux 6.9.1, KDE Plasma 6.0.4, kitty 0.33.1.

## Description of issue
I've set `/etc/locale.conf` to 
```
en_GB.UTF-8 UTF-8
en_US.UTF-8 UTF-8
```
and `/etc/locale.gen` to 
```
LANG=en_GB.UTF-8
```
and deleted `~/.config/plasma-localerc`, ran `sudo locale-gen`, rebooted, entered neovim, ran checkhealth, no issue with locale.
With the KDE plasma setting, I've added KDE specific locale config, now giving `~/.config/plasma-localerc` to be
```
[Formats]
LANG=en_GB.UTF-8
LC_ADDRESS=en_HK.UTF-8
LC_MEASUREMENT=en_HK.UTF-8
LC_MONETARY=en_HK.UTF-8
LC_NAME=en_HK.UTF-8
LC_PAPER=en_HK.UTF-8
LC_TELEPHONE=en_HK.UTF-8
LC_TIME=en_HK.UTF-8

[Translations]
LANGUAGE=en_HK:ja
``` 
then rebooted, enterd neovim, and then gotten 
```
nvim: require("nvim.health").check()

Configuration ~
- ERROR Locale does not support UTF-8. Unicode characters may not display correctly.
  $LANG=en_GB.UTF-8 $LC_ALL=nil $LC_CTYPE=C.UTF-8
  - ADVICE:
    - If using tmux, try the -u option.
    - Ensure that your terminal/shell/tmux/etc inherits the environment, or set $LANG explicitly.
    - Configure your system locale.
```

### Steps to reproduce

Using KDE, write into `~/.config/plasma-localerc`:
```
[Formats]
LANG=en_GB.UTF-8
LC_ADDRESS=en_HK.UTF-8
LC_MEASUREMENT=en_HK.UTF-8
LC_MONETARY=en_HK.UTF-8
LC_NAME=en_HK.UTF-8
LC_PAPER=en_HK.UTF-8
LC_TELEPHONE=en_HK.UTF-8
LC_TIME=en_HK.UTF-8

[Translations]
LANGUAGE=en_HK:ja
``` 
reboot and open neovim to checkhealth.

### Expected behavior

The locale inherited from additional plasma configuration should not have had an impact on locale in checkhealth.

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713773202

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux hostname 6.9.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000 x86_64 GNU/Linux

### Terminal name/version

kitty-0.33.1

### $TERM environment variable

xterm-kitty

### Installation

system package manager - pacman

**Comment by SpookyYomo** [comment]
I forgot to mention in the initial report that `plasma-localerc` was generated via a Plasma control panel setting under `Region & Language`.
I've read on https://bbs.archlinux.org/viewtopic.php?id=292901 prior to posting, so I've made the amendment to `~/.config/plasma-localerc` by having
```
[Translations]
LANGUAGE=en_HK.UTF-8:ja_JP.UTF-8
```
but I've now instead basically still have
```
- ERROR Locale does not support UTF-8. Unicode characters may not display correctly.
  $LANG=en_GB.UTF-8 $LC_ALL=nil $LC_CTYPE=C.UTF-8
  - ADVICE:
    - If using tmux, try the -u option.
    - Ensure that your terminal/shell/tmux/etc inherits the environment, or set $LANG explicitly.
    - Configure your system locale.
```

**Comment by zeertzjq** [comment]
It's strange that checkhealth uses `v:ctype` and only `v:ctype` for checking local.e

**Comment by hubcio2115** [comment]
@SpookyYomo does any other programs log that you might not have locales set correctly? eq:
```bash
bsdtar: Failed to set default locale # when installing a package with pacman
```

**Comment by justinmk** [comment]
> It's strange that checkhealth uses `v:ctype` and only `v:ctype` for checking locale.

That was more of a placeholder or starting point, not an intentional decision.

**Comment by hubcio2115** [comment]
Issue with my locales brought me here actually. I probably have my locales set wrong. So I get a lot of warning, but it all workes fine because of fallbacks. Here's my configs:

```
# ~/.config/plasma-localerc
[Formats]
LANG=en_US.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_MONETARY=pl_PL.UTF-8
LC_PAPER=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
```
```
# /etc/locale.conf
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
```
``` 
# /etc/locale.gen
en_US.UTF-8 UTF-8  
pl_PL.UTF-8 UTF-8
```

I've run `sudo locale-gen` and restarted but the issue still persists. Maybe someone could tell me what I'm doing wrong. I've read the entire [guide](https://wiki.archlinux.org/title/Locale) on Arch Wiki with no help.

**Comment by SpookyYomo** [comment]
> Issue with my locales brought me here actually. I probably have my locales set wrong. So I get a lot of warning, but it all workes fine because of fallbacks. Here's my configs:
> 
> ```
> # ~/.config/plasma-localerc
> [Formats]
> LANG=en_US.UTF-8
> LC_MEASUREMENT=pl_PL.UTF-8
> LC_MONETARY=pl_PL.UTF-8
> LC_PAPER=pl_PL.UTF-8
> LC_TELEPHONE=pl_PL.UTF-8
> LC_TIME=pl_PL.UTF-8
> ```
> 
> ```
> # /etc/locale.conf
> LANG=en_US.UTF-8
> LANGUAGE=en_US.UTF-8
> ```
> 
> ```
> # /etc/locale.gen
> en_US.UTF-8 UTF-8  
> pl_PL.UTF-8 UTF-8
> ```
> 
> I've run `sudo locale-gen` and restarted but the issue still persists. Maybe someone could tell me what I'm doing wrong. I've read the entire [guide](https://wiki.archlinux.org/title/Locale) on Arch Wiki with no help.

I took some inspiration from this and added `LANGUAGE` to `plasma-localerc`, rebooted. Everything works now.... Now wondering how to file this with bugs.kde....

**Comment by hubcio2115** [comment]
> I took some inspiration from this and added `LANGUAGE` to `plasma-localerc`
That fixed it for me, thank you.
