### ISSUE TITLE
nvim_buf_set_extmark with inline text doesn't seem unicode-safe

### ISSUE THREAD

**Issue by emmanueltouzery** [neovim/neovim#28944]
### Problem

I believe inline extmarks are not positioned properly for unicode text in neovim 0.10. The position that I give for the inline text to appear doesn't seem to be correctly taken into account for multibyte text

### Steps to reproduce

create an empty file, enter the text:
0123456789

then run this lua command:
```
:lua vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace(''), 0, 5, {virt_text={{"<--5", "TestHl"}}, virt_text_pos="inline"})
```

You see 01234<-556789

This is correct.

Now open a new file, containing:
šššššššššššš

run the same lua command. The inline text does not appear at all.

### Expected behavior

the behavior should be consistent whether it's multibyte text or not.

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713484068

### Vim (not Nvim) behaves the same?

no application

### Operating system/version

linux fedora 40

### Terminal name/version

kitty, same in neovide

### $TERM environment variable

xterm-kitty

### Installation

github release binary

**Comment by zeertzjq** [comment]
Virtual text won't work if you place in the middle of a multibyte char. Use `virtcol2col()`:
```lua
local col = vim.fn.virtcol2col(0, 1, 6) - 1
vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace(''), 0, col, {virt_text={{"<--5", "TestHl"}}, virt_text_pos="inline"})
```
