### ISSUE TITLE
lua support in neovim

### ISSUE THREAD

**Issue by albertnetymk** [neovim/neovim#2895]
On my neovim, `:echo has('lua')` return 0. Couldn't find any doc covering it, so asking it here: Is it expected? If so, what's the schedule for adding lua support?

I am using the daily build on PPA for 14.04 ubuntu.

**Comment by Pyrohh** [comment]
It's documented in `vim_diff.txt` that it's not supported right now. I'll open a PR which makes it a little more obvious (there's currently no help entries for `if_lua`).

**Comment by albertnetymk** [comment]
Thank you very much for the quick response.

**Comment by Pyrohh** [comment]
You're welcome; highlighting any problem spots in the docs is appreciated.
