### ISSUE TITLE
"Ambiguous use of user-defined command" when running `:E`

### ISSUE THREAD

**Issue by Haugen** [neovim/neovim#28959]
### Problem

I recently installed Neovim (version `0.9.0`) and got kicked off using https://github.com/nvim-lua/kickstart.nvim. One command I started using now and then was `:E`, which I learned was short for `:Explore`. A couple of days ago I updated to Neovim `0.10.0` and immediately `:E` resulted in an error: `E464: Ambiguous use of user-defined command`. `:Explore` still works to open the file explorer.

### Steps to reproduce

- Install Neovim `v0.10.0`
- Open Neovim and run command `:E`

### Expected behavior

Running `:E` I would expect the file explorer to open, like it did in version `0.9.0`.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

`vim -u DEFAULTS` results in `E492: Not an editor command: E`, but when running just `vim` the command `:E` works to open the file explorer. Vim version `9.0`

### Operating system/version

macOS 14.3.1

### Terminal name/version

Alacritty 0.13.2

### $TERM environment variable

screen-256color

### Installation

homebrew

**Comment by clason** [comment]
This is expected, because Nvim 0.10 added the new user command `:EditQuery`.
