### ISSUE TITLE
After closing a buffer, `Ctrl-o` no longer re-opens the buffer

### ISSUE THREAD

**Issue by tschafer-gc** [neovim/neovim#28968]
### Problem

In v0.9.5, closing a buffer and then pressing `ctrl-o` re-opened the closed buffer. In v0.10.0, this is no longer the case, and `ctrl-o` jumps back to the previous position only in currently open buffers.

### Steps to reproduce

Assuming you have binaries for both v0.10.0 and v0.9.5 named `nvim-0.10.0` and `nvim-0.9.5` respectively:

```sh
nvim-0.9.5 --clean file1 file2
:bdelete
<C-o> # opens buffer that was just deleted
```

```sh
nvim-0.10.0 --clean file1 file2
:bdelete
<C-o> # does not open buffer that was just deleted
```

### Expected behavior

`<C-o>` should presumably behave as it did in 0.9.5, by opening deleted buffers

### Neovim version (nvim -v)

0.10.0 release, and latest prerelease 0e9c92a

### Vim (not Nvim) behaves the same?

Vim 9.1.400 does not have this issue

### Operating system/version

macOS 14.5

### Terminal name/version

Alacritty 0.13.2

### $TERM environment variable

tmux-256color

### Installation

Homebrew

**Comment by tschafer-gc** [comment]
> I think this is caused by #25461

Ah yes you're right - I'm assuming there's no way of reverting to the old behaviour, or opening a recently closed buffer by any other means?

**Comment by zeertzjq** [comment]
Also adding a link to my comment in <https://github.com/neovim/neovim/issues/25365#issuecomment-1921529624>:
> This may be changed to another flag of 'jumpoptions' that is enabled by default, so that the old behavior may still be achievable by removing the flags.

**Comment by abilkhan024** [comment]
> Adding a link to my comment in [#25365 (comment)](https://github.com/neovim/neovim/issues/25365#issuecomment-1921529624):
> 
> > This may be changed to another flag of 'jumpoptions' that is enabled by default, so that the old behavior may still be achievable by removing the flag.

Didn't quite get it what do you mean by "old behavior may still be achievable by removing the flag", how do I remove flag, I've tried:
```
set jumpoptions=stack
```
But it only opens buffer one time after closing but, and stops after that.
Any help would be highly appreciated.

**Comment by zeertzjq** [comment]
The flag hasn't been implemented yet.

**Comment by Gremious** [comment]
Uscase: Yeah, _very_ often, I edit a buffer, then close (delete) it thinking I don't need it anymore, only to realize "wait, I need to fix a line"

I then tap ctrl-o and it re-openes that buffer on the line i was editing. It's very nice.

Second usecase: I start vim and press ctrl-o and immediately have the buffer I was editing last ready to go.

I would absolutely like to have the option to use a "global" jumplist again

**Comment by paulodiovani** [comment]
+1
I also used to type `C-o` to reopen a closed buffer.

For whoever have this same issue, `C-^` (or maybe `C-6`) can still reopen a closed buffer.
I have `gb` mapped for this (to match `gt`): `noremap gb <C-^>`

**Comment by rodhash** [comment]
+1

Miss the old `C-o` used to be so useful.. btw `:e#` also do the trick
