### ISSUE TITLE
nightly build errors when trying to open on Windows.

### ISSUE THREAD

**Issue by WillEhrendreich** [neovim/neovim#28965]
### Problem

updated today's latest nightly using bob, it complained about a file missing, and didn't load any config. 
![image](https://github.com/neovim/neovim/assets/55286472/41ff9698-f8a2-4d76-b8e2-5b9b0d66aaa3)
![image](https://github.com/neovim/neovim/assets/55286472/2a937a73-648d-4793-9145-b37801b2c60a)

### Steps to reproduce

be windows pleb, update to nightly, run neovim, see classic neovim screen load up instead of your own config. 

### Expected behavior

just that it would open and load config like normal.

### Neovim version (nvim -v)

v0.11.0-dev-57+gcd48b72b6

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Win 11

### Terminal name/version

windows terminal running pwsh

### $TERM environment variable

no term envrionment variable set that I can see. 

### Installation

bob. glorious bob.

**Comment by justinmk** [comment]
`vim.uri` is not something that Nvim ships (yet). The stacktrace gives some hints about what might be callling that. Start with the given line in your init.lua, which appears to be triggering lazy.lua, etc...

**Comment by WillEhrendreich** [comment]
thanks so much, there was an issue in lazy, if iirc, which has been addressed.
