### ISSUE TITLE
Docs on setting terminal colors?

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2897]
Where might those be? Are there any colorschemes alreay handling terminal colors?

For example, here's what it looks like in neovim with the [hybrid](https://github.com/w0ng/vim-hybrid) colorscheme applied, a terminal window (ugly) next to a javascript window (nice), in the [neovim-e](https://github.com/coolwanglu/neovim-e) UI:

![screen shot 2015-06-24 at 5 15 06 pm](https://cloud.githubusercontent.com/assets/297678/8344291/a04332a4-1a94-11e5-9414-71f1d2017d9c.png)

**Comment by justinmk** [comment]
I think that is controlled by your shell. E.g., the `$LS_COLORS` env var.

**Comment by Pyrohh** [comment]
> Adding nvim-driven syntax highlighting beyond what already exists is out of scope.

Yes, I agree. I'll close this, but on the off-chance that this isn't what you're talking about @trusktr then please reopen.

**Comment by tarruda** [comment]
If you mean the terminal color palette, you can use the `terminal_color_N` variables where N is a number between 0 and 255. For example,  here's what I have in my nvimrc:

```vim
let g:terminal_color_0  = '#2e3436'
let g:terminal_color_1  = '#cc0000'
let g:terminal_color_2  = '#4e9a06'
let g:terminal_color_3  = '#c4a000'
let g:terminal_color_4  = '#3465a4'
let g:terminal_color_5  = '#75507b'
let g:terminal_color_6  = '#0b939b'
let g:terminal_color_7  = '#d3d7cf'
let g:terminal_color_8  = '#555753'
let g:terminal_color_9  = '#ef2929'
let g:terminal_color_10 = '#8ae234'
let g:terminal_color_11 = '#fce94f'
let g:terminal_color_12 = '#729fcf'
let g:terminal_color_13 = '#ad7fa8'
let g:terminal_color_14 = '#00f5e9'
let g:terminal_color_15 = '#eeeeec'
```

This is similar to the gnome terminal tango palette, which should look nicer(IMO) than the screenshot you posted. Note that these variables won't affect the terminal UI, which simply passes the color numbers to the real terminal.

**Comment by tarruda** [comment]
BTW the docs are here: http://neovim.io/doc/user/nvim_terminal_emulator.html#nvim-terminal-emulator-configuration

**Comment by trusktr** [comment]
That's exactly what I needed. Thanks @tarruda!
