### ISSUE TITLE
Flatpak build fails to launch

### ISSUE THREAD

**Issue by Hejtmus** [neovim/neovim#28978]
### Problem

I installed neovim from Flathub according to [documentation](https://github.com/neovim/neovim/blob/master/INSTALL.md#flatpak), but launching always fails with:
```
/app/bin/nvim: error while loading shared libraries: libluv.so.1: cannot open shared object file: No such file or directory
```

I don't know whether previous version was having the same behavior, as I was using version from fedora repos.

Also, I'm not sure whether that build is official, but it has unverified badge on Flathub, so if someone creates broken builds, which could hurt nvim's reputation, I would report the app to Flathub.

### Steps to reproduce

flatpak install flathub io.neovim.nvim
flatpak run io.neovim.nvim

### Expected behavior

Launching neovim

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no, there is no flatpak vim, just gvim

### Operating system/version

Fedora 40

### Terminal name/version

gnome-terminal 3.50.1 for GNOME 45 or empty tty

### $TERM environment variable

 xterm-256color

### Installation

flatpak

**Comment by CleoMenezesJr** [comment]
Hello, I maintain Neovim Flatpak. Take a look here: https://github.com/flathub/io.neovim.nvim/issues/76#issuecomment-2131423957
