### ISSUE TITLE
LSP Error: _changetracking.lua:305: attempt to index local 'buf_state'

### ISSUE THREAD

**Issue by gepbird** [neovim/neovim#28987]
### Problem

This error comes up on every change to the buffer when it is in a "broken state". Doing `:e` fixes this issue.
```
Error executing lua callback: ....10.0/share/nvim/runtime/lua/vim/lsp/_changetracking.lua:305: attempt to index local 'buf_state' (a nil value)   
stack traceback:                                                                                                                                  
        ....10.0/share/nvim/runtime/lua/vim/lsp/_changetracking.lua:305: in function 'send_changes_for_group'                                     
        ....10.0/share/nvim/runtime/lua/vim/lsp/_changetracking.lua:348: in function 'send_changes'                                               
        ...ovim-unwrapped-0.10.0/share/nvim/runtime/lua/vim/lsp.lua:553: in function <...ovim-unwrapped-0.10.0/share/nvim/runtime/lua/vim/lsp.lua:
548>  
```

### Steps to reproduce

Most likely after doing file operations with git (fugitive), opening a previously opened file will put the buffer in a "broken state". At least this is what seems to cause it, I'll try to make it consistently reproducible later.

### Expected behavior

No error

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

Most likely not

### Operating system/version

NixOS

### Terminal name/version

xfce4-terminal

### $TERM environment variable

xterm-256color

### Installation

nixpkgs/nixos-unstable

**Comment by icholy** [comment]
This is fixed on master.

**Comment by gepbird** [comment]
@icholy Thanks! I'll try it.

**Comment by icholy** [comment]
FYI @mfussenegger your refactor had some type of behaviour change which fixed this https://github.com/neovim/neovim/commit/2908f71dc9e9591f97e0f9d70dbc8d8b18f9e475

**Comment by dylan-chong** [comment]
is this fix  going to be released any time soon?

**Comment by icholy** [comment]
@dylan-chong the fix will be included in 0.10.1

**Comment by caarlos0** [comment]
any workarounds besides using nightly?

**Comment by chrisgrieser** [comment]
I am on 0.10.1 and the issue still occurs for me

**Comment by icholy** [comment]
@chrisgrieser can you reproduce this consistently?

**Comment by thomas-hiron** [comment]
For my part, `0.10.1` fixed the issue! Many thanks!

**Comment by chrisgrieser** [comment]
@icholy Sorry, forgot to respond. 

No, I cannot reproduce it anymore. Maybe it was some weird interaction with some other plugin that I uninstalled by now… Anyway, on my end the problem does not occur anymore.
