### ISSUE TITLE
speed up check for pynvim

### ISSUE THREAD

**Issue by arcxio** [neovim/neovim#29004]
### Problem

neovim has a bad startup time by default (no config) which can be improved 4x on my laptop just by disabling the python provider (see steps to reproduce).

the culprit is [this line of code](https://github.com/neovim/neovim/blob/b280d57db9845359186bfb5167e1559b6184f8d5/runtime/lua/vim/provider/python.lua#L29), which runs python to get its version and find importable `neovim` module.

the problem is that firing up python interpretator is just slow by itself even with no code:
```fish
~> time python -c ""

________________________________________________________
Executed in   20.45 millis    fish           external
   usr time   13.57 millis  167.00 micros   13.41 millis
   sys time    6.79 millis   68.00 micros    6.72 millis
```

I believe it's not neccessary to do it. we can vastly improve performance by only checking what we actually care about here - whether `{prefix}/lib/python{version}/site-packages/neovim` exists in the filesystem (in fact, that's essentially what importlib does), where `prefix` can be defined as `$(which python{version})/../..` to account for various python installations - and we can also get python version right from the path without having to run `python`.

I couldn't find any discussion on this, let me know if I missed anything.

### Steps to reproduce

```fish
~> python -m timeit '__import__("os").system("nvim +q")'
5 loops, best of 5: 83.3 msec per loop
~> echo 'vim.g.loaded_python3_provider = 0' > .config/nvim/init.lua
~> python -m timeit '__import__("os").system("nvim +q")'
10 loops, best of 5: 19.3 msec per loop
```

### Expected behavior

no python bottleneck in startup time

### Neovim version (nvim -v)

NVIM v0.11.0-dev-85+g93c55c238

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux

### Terminal name/version

foot 1.17.2

### $TERM environment variable

foot

### Installation

AUR

**Comment by bfredl** [comment]
> rm ~/.config/nvim/init.lua

Hmm, python provider is supposed to only be loaded on demand, not with (really) empty config. You might have some plugin in your runtimepath which checks `has("python3")` on startup.  This can be disabled with `nvim --clean +q`

**Comment by arcxio** [comment]
> You might have some plugin in your runtimepath which checks `has("python3")` on startup.

you're right, it seems that the AUR package `neovim-nightly-bin` which I use includes a bunch of vim plugins to runtimepath, including black.vim which triggers python provider, I may suggest them to fix it there. but I still think it's worth fixing the performance issue with calling python to check if pynvim is available so that it lowers startup time when using python plugins anyway.

**Comment by justinmk** [comment]
Has been discussed many time before. The search doesn't happen unless your config triggers it.

**Comment by clason** [comment]
> it seems that the AUR package neovim-nightly-bin which I use includes a bunch of vim plugins to runtimepath

Wow. Please complain to them _very loudly_.

**Comment by arcxio** [comment]
> The search doesn't happen unless your config triggers it

the issue is not really that the search happens, the issue is that the search is much slower that it has to be

**Comment by clason** [comment]
The search is the way it is for a reason, though: robustness (venv, pip, etc.).

**Comment by bfredl** [comment]
> but I still think it's worth fixing the performance issue with calling python to check if pynvim is available so that it lowers startup time when using python plugins anyway.

such a check would just be an approximation. the only way to check if python can import a package is to invoke python and try to import the package. any external reimplementation of importlib/virtualenv/etc/etc is going to be out of date pretty much instantly given the frequent changes to the python tooling ecosystem. 

Instead, a _well-behaved_ python plugin should defer to check `has("python3")` until it actually needs to know that, not haphazardly at neovim startup.
