### ISSUE TITLE
Can't nested use native vim.snippet

### ISSUE THREAD

**Issue by Old-Farmer** [neovim/neovim#29023]
### Problem

As title.

For example：

expand a snippet, like "${1:a}, ${2:b}, ${3:c}, $0"
expand another snippet "${1:d}, ${2:e}, ${3:f}, $0" at "${1:a}", like "${1:d}, ${2:e}, ${3:f}, $0, ${2:b}, ${3:c}, $0"
then ${2:b}, ${3:c} cannot be jumped to any more.

I have no idea this is a bug, or hasn't been supported by neovim(means feature)?

Thanks.

### Steps to reproduce

1. nvim --clean
2. :lua vim.snippet.expand("${1:a}, ${2:b}, ${3:c}, $0") 
3. \<esc\>
4. :lua vim.snippet.expand("${1:d}, ${2:e}, ${3:f}, $0") 
5. \<esc\>
6. :lua vim.snippet.jump(1)
7. \<esc\>
8. :lua vim.snippet.jump(1)
9. \<esc\>
10. :lua vim.snippet.jump(1)
11. \<esc\>
12. :lua vim.snippet.jump(1)

### Expected behavior

Jump to ${2:b}, but Stop at $0 in the middle.

### Neovim version (nvim -v)

0.10.0 release

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

Linux Mint 21.3

### Terminal name/version

kitty 0.35.0

### $TERM environment variable

xterm-kitty

### Installation

official binary

**Comment by mfussenegger** [comment]
This is a know limitation and tracked in https://github.com/neovim/neovim/issues/25696
