### ISSUE TITLE
`BUILD.md` file mentions non-existent `stable` branch of repository

### ISSUE THREAD

**Issue by maxmahlke** [neovim/neovim#29025]
### Problem

In the `Quickstart` section of the [BUILD.md](https://github.com/neovim/neovim/blob/master/BUILD.md) file, it says

> If you want the stable release, also run `git checkout stable`

I have been doing this since version `0.5`, however, now, the branch no longer seems to exist. What is the recommended branch for a stable build now?

### Steps to reproduce

n/a

### Expected behavior

n/a

### Neovim version (nvim -v)

n/a

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

n/a

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

n/a

**Comment by wookayin** [comment]
https://github.com/neovim/neovim/releases/tag/stable

The `stable` tag exists. Try `git fetch --tags`

**Comment by maxmahlke** [comment]
Ah ok I see, thanks for the explanation! This works well:

```
git fetch --tags --force
git checkout stable
```
