### ISSUE TITLE
Cannot match termcodes of `<M-]>` from config vs from input

### ISSUE THREAD

**Issue by bew** [neovim/neovim#29034]
### Problem

My terminal sends `^[]` (escape char + `]`), checked in `cat`.
Neovim correctly detects this input as `<M-]>` when doing it in cmdline after a `<C-v>`.

However when using `getcharstr()` the resulting codes after termcodes have been replaced is different than when replacing termcodes of the `"<M-]>"` string (coming from configs).

### Steps to reproduce

```
nvim --clean
:lua =vim.api.nvim_replace_termcodes("<M-]>", true, true, true)
#GIVES: <80><fc>^H]
:lua =vim.api.nvim_replace_termcodes(vim.fn.getcharstr(), true, true, true)
#Input <M-]> on keyboard
#GIVES: <80><fe>X<fc>^H]
```

### Expected behavior

I expect both calls to `nvim_replace_termcodes` to be equal

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

(don't know how to check..)

### Operating system/version

Linux (NixOS)

### Terminal name/version

Wezterm 20240203-110809-5046fc22

### $TERM environment variable

tmux-256color

### Installation

Nix

**Comment by zeertzjq** [comment]
Don't double-escape.

**Comment by bew** [comment]
what do you mean?

**Comment by zeertzjq** [comment]
Don't use `nvim_replace_termcodes` on raw keycodes.

**Comment by bew** [comment]
ah yes `getcharstr()` is actually already the raw termcodes, thx.
(found via some debugging around `nvim-surround` plugin not detecting my custom surrounds)
