### ISSUE TITLE
Crash while opening large log file

### ISSUE THREAD

**Issue by amarud** [neovim/neovim#29037]
### Problem

nvim crashes while opening large log file. 

"realloc(): invalid next size" is visible 

![image](https://github.com/neovim/neovim/assets/165153883/55797e68-21b8-4e1a-b617-adbc43ea7875)

### Steps to reproduce

Not reproducable. Same large file can either crash nvim, or be open without issue.

### Expected behavior

No crash

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 22.04

### Terminal name/version

Kitty

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
Can you use a Debug build and provide a backtrace? https://neovim.io/doc/user/dev_tools.html#dev-tools-backtrace

**Comment by amarud** [comment]
I found that copilot plugin is the problem.  
Closing the ticket.
