### ISSUE TITLE
SHA256 sums for multiple dependencies in deps.txt are not stable

### ISSUE THREAD

**Issue by thestr4ng3r** [neovim/neovim#29049]
### Problem

https://github.com/neovim/neovim/blob//cmake.deps/deps.txt specifies URLs for downloading tarballs of bundled dependencies, along with their SHA256s.
Some of them point to auto-generated tarballs from GitHub, like https://github.com/libuv/libuv/archive/v1.48.0.tar.gz, but these are known to not be stable and have already changed in the past.

GitHub claim to not change them too frequently in the future, but there is no guarantee: https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/
Unfortunately, not all of the necessary projects ship non-autogenerated tarballs. One way to work around this is to mirror the files oneself somewhere.

### Expected behavior

Build should not break unexpectedly because GitHub changed their tarball generation strategy in the future.

**Comment by clason** [comment]
I am sorry, but is this an actual problem, or just a hypothetical? There have been literally dozens of people downloading and building these successfully without any reports of problems.

**Comment by dundargoc** [comment]
> Build should not break unexpectedly because GitHub changed their tarball generation strategy in the future.

Meh. From end user perspective this is a non-issue. Github changes tarball strategy -> neovim doesn't work for an hour -> we update SHA's -> everyone lives happily ever after. We're not saving lives here and don't require 99.999% uptime, so I'd consider this a non-problem.

What is problematic with this though is that bisecting might break in the future, which I think is a much more relevant and realistic problem. It's not really something users need to worry about, but it is definitely something we need to worry about. I'm unsure if this problem is tracked somewhere else, so I'll let this issue open for the time being (although this could use a real dedicated problem statement instead of me just latching onto this issue). We could switch from checking the tarball SHA to instead rely on the the commit SHA instead. @justinmk @bfredl @jamessan thoughts?

**Comment by thestr4ng3r** [comment]
> I am sorry, but is this an actual problem, or just a hypothetical? There have been literally dozens of people downloading and building these successfully without any reports of problems.

It is practical in the sense that this has happened in the past (iirc even multiple times) and many projects were broken. I would not expect this to happen very often in the future, but it is still a possibility.
So I don't think this is urgent to be addressed immediately but certainly something one must be at least aware of.

> From end user perspective this is a non-issue. Github changes tarball strategy -> neovim doesn't work for an hour -> we update SHA's -> everyone lives happily ever after. We're not saving lives here and don't require 99.999% uptime, so I'd consider this a non-problem.

This is true for the HEAD of development, but as you mentioned it is not for previous commits and especially not for any previously released version. Even if a new version is released, older release tags/tarballs, which are integrated in distributions or used by users holding back updates because of breaking changes, will still be broken.

> We could switch from checking the tarball SHA to instead rely on the the commit SHA instead.

This only works if you clone dependencies directly with git, which could be inconvenient. If on the other hand you download a tarball from e.g. https://github.com/libuv/libuv/archive/541329d51f82bce83bd81ff7640edabfc32d149c.tar.gz, you lose the entire security benefit of checking the hashes in case e.g. the user sits behind a proxy that alters the download, and they have its root ca cert installed.

**Comment by dundargoc** [comment]
> If on the other hand you download a tarball from e.g. https://github.com/libuv/libuv/archive/541329d51f82bce83bd81ff7640edabfc32d149c.tar.gz, you lose the entire security benefit of checking the hashes in case e.g. the user sits behind a proxy that alters the download, and they have its root ca cert installed.

Wait, I don't follow. I'm pretty sure cmake checks the SHA of the downloaded tarball locally, so I don't think this should be a problem. I assume you mean this could be a problem if we rely on the git hash instead? If we go with the git hash route then cmake won't download the tarball of the hash, it will clone the git repo and locally check out the commit. Unsure if this is more secure or not, I'm not a security expert. To me this seems like this attack might just as likely occur when git cloning a repo.

Honestly, this is a high ask. Are there any other FOSS projects (except maybe nix?) that is prepared for the complete collapse of society? Is this a problem most projects have attempted to solve, and if so, how have they achieved it?

**Comment by thestr4ng3r** [comment]
> Wait, I don't follow. I'm pretty sure cmake checks the SHA of the downloaded tarball locally, so I don't think this should be a problem. I assume you mean this could be a problem if we rely on the git hash instead? If we go with the git hash route then cmake won't download the tarball of the hash, it will clone the git repo and locally check out the commit. Unsure if this is more secure or not, I'm not a security expert.

Maybe I should clarify a bit more the options I was trying to argue about, following the suggestion of using the git hash instead, because I think I didn't fully understand your suggestion about that either. One could:
* Download commit-specific tarballs like https://github.com/libuv/libuv/archive/541329d51f82bce83bd81ff7640edabfc32d149c.tar.gz + checking its SHA256: same issue as before as tarballs are volatile
* Download commit-specific tarballs without explicit SHA256-check: clear loss of security
* Clone with git and checking out a specific commit hash: Will be stable and should work fine, but a bit more complex as e.g. git is needed, cloning is perhaps slower than a single download, etc. Also git uses SHA-1 which is broken wrt. security, but I'm not too deep into that topic myself either.

> To me this seems like this attack might just as likely occur when git cloning a repo.

There is a small but significant difference between manually cloning a repo from an url and having a build process download dependencies behind the scenes:
* When you manually clone a repo by typing a command like `git clone https://abc`, you explicitly express that at this point in time you trust the URL `https://abc` and your network configuration.
* When you build a package like neovim, which you might have obtained e.g. as a tarball and saved locally before, you don't necessarily have inspected every line of code of that tarball for possible downloads and checked that you trust every URL and the way they are downloaded. Instead, you trust neovim to only download what is already known and trusted by it.

This is why the SHA256-checks (as they are already implemented) are critical to have.

> Are there any other FOSS projects (except maybe nix?) that is prepared for the complete collapse of society? Is this a problem most projects have attempted to solve, and if so, how have they achieved it?

I think this is a twofold question.

About the concrete case of GitHub-generated tarballs I would say most projects using them have not solved it at all. You can google something like "github tarball sha256" and will find many cases where this became an unexpected issue.

However, normally it is solved upstream by projects providing immutable tarballs per version, either built manually or in CI. As a concrete example, here are the source and binary downloads for current OpenBSD, along with the SHA256 hashes, which are also signed: https://cdn.openbsd.org/pub/OpenBSD/7.5/arm64/ They will never change, you can mirror them yourself and 10 years from now, even if the internet collapsed, you can still upgrade OpenBSD 7.4 to 7.5 securely without skipping any signature checks (unless the public key expired of course)

In our case unfortunately many of those projects used don't provide tarballs, like the tree-sitter parsers for example. But I see it is planned to move generated files to github releases eventually so perhaps this is already the solution for those: https://github.com/tree-sitter/tree-sitter/issues/930 ("CLI commands - Add new pack and publish subcommands to the Tree-sitter CLI, for uploading tarballs and compiled .wasm files to the GitHub releases API.")
Other projects actually do provide stable tarballs like libuv: https://dist.libuv.org/dist/v1.48.0/ 

So maybe the solution here is to simply replace the URLs where a stable tarball is available with that, and wait for tree-sitter to publish the parsers in github releases.

**Comment by clason** [comment]
So this is simply about _where_ the links in `deps.txt` point on Github?

**Comment by thestr4ng3r** [comment]
> So this is simply about _where_ the links in `deps.txt` point on Github?

Basically yes, whether the tarballs behind the links are volatile, or known to stay the same.

> The tree-sitter parsers absolutely provide tarballs; what do you think we are using during our own build?

Do you mean the ones like https://github.com/tree-sitter/tree-sitter-c/archive/v0.21.3.tar.gz? These are auto-generated and volatile, as explained previously. Or are there also others that I have not found yet? The releases like https://github.com/tree-sitter/tree-sitter-c/releases/tag/v0.20.3 do not have anything attached to them.

**Comment by clason** [comment]
> Basically yes, whether the tarballs behind the links are volatile, or known to stay the same.

So do you have a better link to suggest?

**Comment by thestr4ng3r** [comment]
> So do you have a better link to suggest?

For the parsers, not yet, unless they are manually mirrored. But as mentioned above, it is apparently on their roadmap.
For libuv for example, yes: https://dist.libuv.org/dist/v1.48.0/libuv-v1.48.0.tar.gz

> > The releases like https://github.com/tree-sitter/tree-sitter-c/releases/tag/v0.20.3 do not have anything attached to them
> 
> Of course they do -- tar.gz _and_ zip.

This is not a real attachment, just a GitHub-generated link. It is a bit misleading what GitHub shows there. What I mean is actual files like the ones marked here:
![Bildschirmfoto 2024-05-31 um 14 49 39](https://github.com/neovim/neovim/assets/1460997/c6886165-650c-4bc6-b64d-c8434aa3f074)

**Comment by dundargoc** [comment]
@thestr4ng3r for clarification, do the tarballs from manual releases not have the problem you described with the automatically generated tarballs?

**Comment by thestr4ng3r** [comment]
> @thestr4ng3r for clarification, do the tarballs from manual releases not have the problem you described with the automatically generated tarballs?

Not sure if I understand what you mean by "manual releases". But if you manually upload a file to attach it to a release, it will stay that file forever, hence it will not be affected by this issue.

**Comment by dundargoc** [comment]
I checked: most of our dependencies do now have their source code manually updated. I think this is a wontfix for the time being, this feels like a systematic problem github or some other entity needs to fix rather rely on every project hosting their dependencies on another platform.
