### ISSUE TITLE
Perl syntax highlighting of named sub signatures highlights as a possible error

### ISSUE THREAD

**Issue by cliveholloway** [neovim/neovim#29046]
### Problem

When opened in neovim, named subroutine signature args highlight as possible errors. I took a quick look at the regex for perlSubPrototypeError in /usr/share/nvim/runtime/syntax/perl.vim and couldn't work out exactly what needs changing. For now, I have just commented out this line in my install as a quick fix:

`" hi def link perlSubPrototypeError   Error`

### Steps to reproduce

Sample Perl. Open in Neovim to see what I mean - $arg is marked as an error.

`#!/usr/bin/perl
use v5.36;

sub whatever($arg) {
    ...
}`

### Expected behavior

Not highlight the $arg as an error

### Neovim version (nvim -v)

0.7.2 2.1.0-beta3

### Vim (not Nvim) behaves the same?

No - vim has correct highlighting

### Operating system/version

Kubuntu

### Terminal name/version

Konsole

### $TERM environment variable

xterm-256color

### Installation

apt, I think

**Comment by clason** [comment]
Please report this to the Perl syntax file maintainer listed at the top of the file; we don't maintain these files and include them from Vim as-is.
