### ISSUE TITLE
stylus syntax file: Undefined variable: main_syntax

### ISSUE THREAD

**Issue by samuzora** [neovim/neovim#29055]
### Problem

When opening a .styl file, Neovim emits an error message `Undefined variable: main_syntax`. The variable at <https://github.com/neovim/neovim/blob/7b16c1fa8451880c72769f6d3c311f24c74f4fc7/runtime/syntax/stylus.vim#L9> isn't defined prior.

### Steps to reproduce

nvim --clean test.styl

Error detected while processing BufNewFile Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:35: Error executing lua: /usr/share/nvim/runtime/filetype.lua:36: BufNewFile Autocommands for "*"..FileType Autocommands for "*"..Synt
ax Autocommands for "*"..function <SNR>5_SynSet[26]..script /usr/share/nvim/runtime/syntax/stylus.vim, line 9: Vim(if):E121: Undefined variable: main_syntax
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:36: in function </usr/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10>
Press ENTER or type command to continue

### Expected behavior

Error should not be emitted

### Neovim version (nvim -v)

NVIM v0.11.0-dev-57+gcd48b72b6

### Vim (not Nvim) behaves the same?

yes, 9.1.2024

### Operating system/version

Arch Linux 5.15.146 (WSL)

### Terminal name/version

Windows Terminal 1.21.1272.0

### $TERM environment variable

xterm-256color

### Installation

Arch User Repository (AUR)

**Comment by zeertzjq** [comment]
It seems that this fixup got forgotten: https://github.com/vim/vim/commit/2d919d2744a99c9bb9e79984e85b8e8f5ec14c07#r141568461
