### ISSUE TITLE
"Option 'commentstring' is empty" in .cpp files

### ISSUE THREAD

**Issue by archiedwest** [neovim/neovim#29052]
### Problem

When I try to use `gcc` to comment or uncomment a line in a C++ file, it doesn't work at all. I thought that, by default, the `commentstring` option which C uses (`/*%s*/`)  was supposed to be used in C++ files, but I get nothing but the message "Option 'commentstring' is empty." I only get this problem on Windows. On macOS it works as I expected.

### Steps to reproduce

`nvim --clean`
`:e test.cpp`
Type something.
`gcc`
Produces: "Option 'commentstring' is empty."

### Expected behavior

I was under the impression that C++ used the same `commentstring` option as C, but it doesn't seem to be the case for some reason.

### Neovim version (nvim -v)

Neovim version v0.10.0

### Vim (not Nvim) behaves the same?

No, Vim sets `commentstring` in the way I expected it to.

### Operating system/version

Windows 10

### Terminal name/version

Alacritty version 0.13.2 (bb8ea18)

### $TERM environment variable

xterm-256color

### Installation

Installed with winget

**Comment by zeertzjq** [comment]
This seems strange. Maybe there is a bug in the `:runtime` Ex command?

**Comment by archiedwest** [comment]
I haven't messed with any of the files in `C:\Program Files\Neovim\share\nvim\runtime` if that's what you mean.

**Comment by clason** [comment]
I think the suspicion is that your installation is broken (outdated runtime files). Please try installing the release directly from our Github release page.

**Comment by zeertzjq** [comment]
No, this is a bug in Nvim.
