### ISSUE TITLE
`synIDattr` returns GUI color names with `notermguicolors`

### ISSUE THREAD

**Issue by vlncheme** [neovim/neovim#29056]
### Problem

When opening a R markdown file (filetype rmd), receiving the following E421 color error tracing back to the SetupPandocHighlights function in runtime/syntax/pandoc.vim:

Error message:

```
Error executing lua callback: /opt/nvim-linux64/share/nvim/runtime/filetype.lua:35: Error executing lua: /opt/nvim-linux64/share/nvim/runtime/filetype.lua:36: BufReadPost Autocommands for "*"..FileType A
utocommands for "*"..Syntax Autocommands for "*"..function <SNR>5_SynSet[26]..script /opt/nvim-linux64/share/nvim/runtime/syntax/rmd.vim[41]../opt/nvim-linux64/share/nvim/runtime/syntax/pandoc.vim[697]..
function <SNR>25_SetupPandocHighlights, line 111: Vim(highlight):E421: Color name or number not recognized: ctermfg=NvimLightGreen                                                                         
stack traceback:                                                                                                                                                                                           
        [C]: in function 'nvim_cmd'                                                                                                                                                                        
        /opt/nvim-linux64/share/nvim/runtime/filetype.lua:36: in function </opt/nvim-linux64/share/nvim/runtime/filetype.lua:35>                                                                           
        [C]: in function 'nvim_buf_call'                                                                                                                                                                   
        /opt/nvim-linux64/share/nvim/runtime/filetype.lua:35: in function </opt/nvim-linux64/share/nvim/runtime/filetype.lua:10>                                                                           
stack traceback:                                                                                                                                                                                           
        [C]: in function 'nvim_buf_call'                                                                                                                                                                   
        /opt/nvim-linux64/share/nvim/runtime/filetype.lua:35: in function </opt/nvim-linux64/share/nvim/runtime/filetype.lua:10>     
```

**Repeating same in 0.9.5 does not produce this behavior.**

### Steps to reproduce

nvim --clean foo.Rmd

### Expected behavior

File open and with proper syntax highlighting

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no, vim 8.2.2121

### Operating system/version

ubuntu 22,.04

### Terminal name/version

GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

repo

**Comment by clason** [comment]
The pandoc syntax script does some fancy highlight group manipulations that seem to be broken on Neovim.

**Comment by clason** [comment]
Ah, yes, that can't work; `ctermfg` only accepts the ANSI color names -- which the new Neovim default color names are not.

**Comment by clason** [comment]
Workaround in the meantime: explicitly set `termguicolors` in your `init.vim`.

**Comment by clason** [comment]
There's a bunch of runtime files (syntax and colors) that check `&termguicolors` which will likely have similar issues on startup.

**Comment by wookayin** [comment]
> Workaround in the meantime: explicitly set termguicolors in your init.vim.

or another one: `let g:pandoc#syntax#style#emphases = 0`.


But it looks like the real problem is --- `synIDattr(synIDtrans(hlID('string')), 'fg')` (during startup?) returning "NvimLightGreen" (for gui) instead of cterm colors (integer) even when `&termguicolors = 0`.

https://github.com/neovim/neovim/blob/v0.10.0/runtime/syntax/pandoc.vim#L670-L671

```
              let s:tmp_val = synIDattr(synIDtrans(hlID('String')), s:i)
              let s:tmp_ui =  has('gui_running') || (has('termguicolors') && &termguicolors) ? 'gui' : 'cterm'
```

where `s:tmp_ui` being `'cterm'` because at this point `&termguicolors = 0`. Indeed, `synIDattr(synIDtrans(hlID('String')), 'fg')` returns integer after `:set notermguicolors`.

**Comment by clason** [comment]
Minimal reproducer: `nvim --clean --cmd "echo synIDattr(synIDtrans(hlID('string')),'fg')"` shows the GUI color name. The wrong output also happens on 0.9.5 (different color, of course, but still truecolor hex) but not on 0.8.4 (or Vim).

**Comment by clason** [comment]
Bisected to 24488169564c39a506c235bf6a33b8e23a8cb528 (or the child commit since that one doesn't build for me). @bfredl

**Comment by bfredl** [comment]
the documentation for 'termguicolors' is actively misleading, the option defaults to on and not off.

> nvim --clean --cmd "echo synIDattr(synIDtrans(hlID('string')),'fg')" shows the GUI color name.

This is the **expected** behavior since https://github.com/neovim/neovim/pull/26407 . if we don't want that that change would need to be reverted. (I don't have any opinion either way, but you get what is in fact implemented)

It has nothing to do with the change to separate the TUI to a separate process.

**Comment by clason** [comment]
But shouldn't the value of `&termguicolors` reflect that? The issue here is the inconsistency.  Try
```
nvim  --clean --cmd "echo synIDattr(synIDtrans(hlID('string')),'fg')" --cmd "echo &tgc"
```
which will print `NvimLightGreen` and `0`, which I do believe _is_ a bug.

**Comment by bfredl** [comment]
That would be from https://github.com/neovim/neovim/pull/26579 . Why the option had to take an incorrect value instead of simply just implementing the intended effect of deferring OptionSet, I have no idea.
