### ISSUE TITLE
[Question]: nvim with ultisnips

### ISSUE THREAD

**Issue by danielb2** [neovim/neovim#2906]
Starting nvim with [UltiSnips] gives the following error message:

[UltiSnips]: https://github.com/sirver/ultisnips

```
[~]$ nvim
UltiSnips requires py >= 2.7 or any py3
```

Looking at the docs it looks like python should always be available. What's amiss?

**Comment by ZyX-I** [comment]
It is only available if `neovim` PyPI package is installed.

**Comment by danielb2** [comment]
Thanks. How do I install that?

**Comment by brcolow** [comment]
Should be 'pip install neovim' or 'pip3 install neovim'

**Comment by danielb2** [comment]
will easy_install work?

**Comment by danielb2** [comment]
trying now anyway

**Comment by danielb2** [comment]
worked! thanks much :)

**Comment by danielb2** [comment]
btw, I didn't see this in the read me. Maybe it could be made more obvious since python seems to be the only language that's supported now?

**Comment by Pyrohh** [comment]
> btw, I didn't see this in the read me. Maybe it could be made more obvious since python seems to be the only language that's supported now?

Do you mean `README.md`? It's already documented in `:h vim-differences` and `:h nvim_python.txt`, both of which are under `:h nvim` (which should be shown when you open vim if `'shortmess'` doesn't contain `I`).

**Comment by danielb2** [comment]
I had seen : https://github.com/neovim/neovim/wiki/Differences-from-Vim

which is quite buried, but saw no mention of needing to do pip, or easy_install

**Comment by Pyrohh** [comment]
Hmm, there is indeed no explicit mention of `pip` under there.
The equivalent `:help` document ([`vim-differences`](http://neovim.io/doc/user/vim_diff.html#vim-differences)) links to `:h nvim_python`, which has a bunch of instructions, so it seems our wiki version is just outdated.

I'm no fan of maintaining two copies of these, so perhaps that whole page could just link to `:h vim_differences`.

**Comment by danielb2** [comment]
Since this ticket is closed, and it's digressed into a documentation issue, perhaps a new issue is in order?

**Comment by fwalch** [comment]
I think @Pyrohh already fixed the Wiki page. Is a new issue still needed?

**Comment by dikun** [comment]
https://www.archlinux.org/packages/community/any/python2-neovim/ - Python 2 client for neovim
https://www.archlinux.org/packages/community/any/python-neovim/   - Python 3 client for neovim

**Comment by danielb2** [comment]
Btw, for me `easy_install` is much easier than `pip` which does not exist on all systems while easy_install does. Not sure why documentations always refer to pip

**Comment by justinmk** [comment]
Isn't `easy_install` deprecated?

**Comment by ZyX-I** [comment]
@danielb2 I do not have easy_install installed system-wide. It was installed into ~/.local *by pip* for some reason though, but if I was not installing something locally it would not exist, so I would not say about “on all systems”. This is Gentoo.

Also note that some of the “all systems” do not have Python *at all*, as well as easy_install.

**Comment by dutao1992** [comment]
You can learn from this website.http://www.sunzhongwei.com/vim-snippets.html.This solved my problem.

**Comment by luisliuchao** [comment]
try `sudo pip uninstall neovim` and `sudo pip install --user neovim`

**Comment by justinmk** [comment]
> try sudo pip uninstall neovim and sudo pip install --user neovim

Or `--upgrade`, as recommended in `:help provider-python`.
