### ISSUE TITLE
15 Month Anniversary of BountySource Campaign Reevaluation

### ISSUE THREAD

**Issue by jfelchner** [neovim/neovim#2907]
As we cross over 15 months since the BountySource campaign was successfully funded for an amazing $34,000 I think it's important to evaluate where we are as a community and possibly rethink the goals that have been set thus far.

I think that getting Neovim to a stable place, even if it doesn't have absolutely everything that we want is extremely important.  Vim was stable when Neovim forked it and although it's certain that Vim had bugs which had never been addressed, it's not the case that every bug needs squished before a stable Neovim is released.

It's also not necessary that Neovim has every feature that we want in order to hit `1.0`.  I think that it could be released with small incremental changes towards the goal rather than waiting years for some huge set of features to be released.

It's been 15 months and this is a _huge_ undertaking.  There has been massive progress thus far, but not releasing a `1.0` is also affecting adoption.  Neovim will only ever be great if people start migrating from Vim to Neovim.  And the majority of people aren't going to do that until it hits `1.0`.

I'm not saying that Neovim should release `1.0` before it's ready.  I'm saying that I think the core team needs to reevaluate what "ready" means.  The needle on the [first release](https://github.com/neovim/neovim/milestones/first%20release) milestone barely moves.

I also realize that I'm saying this as someone who hasn't written a line of code toward Neovim's completion.  This is simply because I know zero about C.  (Although I did back the original BountySource campaign)  However I do say this as someone who uses Vim every day and I see what it _can_ be and I think that Neovim is its best hope at becoming even more amazing than it already is.

I'm going to throw out that I think getting `1.0` out the door by the end of the year would be an excellent step.  And at that point releasing a minor release every month (with whatever features are complete at the end of the four weeks) until we hit `2.0` and we deprecate some Vim backwards compatibility.

**Comment by justinmk** [comment]
I've been working on a roadmap and a clear path to `v0.1` (not `1.0`, sorry, not going to happen). The goal is to have a stable branch in 2 months, and thereafter continue targeting milestones `v0.2`, `v0.3`, etc., with concrete tasks being assigned to each release.

I'll be happy to go into details after I publish the roadmap in a few days.

**Comment by jfelchner** [comment]
@justinmk :tada: :grinning: 

Actually the only reason I brought up compatibility is that I believe @tarruda had mentioned how important he thought it was to be as backwards compatible with Vim as possible so that adoption was easier.

It may be that you all have reevaluated that decision for certain things.  I'm personally fine with you all pushing the "incompatibility" needle forward a little bit.

While you all are having discussions about versioning, the only thing I would say there is that, to the public, a `1.0` means a lot more than a `0.1`, but from a development perspective, it makes little difference (even if you're following SemVer :+1:)  So if you're stable, I'd say shoot for the `1.0`.  There's already a _ton_ of amazing new stuff in Neovim that makes it worthy IMO.  `1.0` to me says "We're stable.  Use us every day.".  And I think that's the sentiment felt by a lot of people.

Either way, a stable version (whether `0.1` or `1.0`) in 2 months-ish sounds fantastic to me and I'll look forward to adding Neovim to my daily workflow. :sunglasses:

Thank you all for the hundreds of hours you've put into this.

**Comment by justinmk** [comment]
Back-compat with Vim will continue to be a cornerstone of Neovim. I am more referring to breaking back-compat with our *own* features. E.g., the API may change slightly (unlikely), the provider design may change before 1.0, some method signatures may change.

**Comment by Pyrohh** [comment]
One thing I'm curious about (and probably others too): is there some sort of contractual obligation to implement the VimL->Lua translator? I noticed it was a stretch goal.

**Comment by jfelchner** [comment]
Really excited to see this release getting closer :grinning: 

I also love that you all don't close issues that aren't done just to keep the tracker "clean".

**Comment by justinmk** [comment]
Published roadmap and vision:

https://neovim.io/roadmap/

https://neovim.io/charter/

There's still work to do outlining the official lifecycle, but that is covered by https://github.com/neovim/neovim/issues/862 and I am still working on it.
