### ISSUE TITLE
Getting two tab characters for one keypress

### ISSUE THREAD

**Issue by define-private-public** [neovim/neovim#2908]
I'm using the nightly ubuntu neovim builds.  About two days ago I noticed when I press the tab key once that two tab characters. If I press backspace once it will delete two tab characters. My tabstop value is normally `tabstop=4`.  When I set `tabstop=8` this doesn't happen and it functions as I expect it to.  This did not happen a few days ago.  Is there any other information I can provide?

This is not the version where I first saw the issue, but the one I just got, and it still persists.

        NVIM 0.0.0-alpha (compiled Jun 26 2015 17:08:58)
        Commit: ?
        Build type: RelWithDebInfo
        Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-JYUK5m/neovim-0.0.0+git201506260226+1718+9+10~ubuntu15.04.1/build/config -I/build/neovim-JYUK5m/neovim-0.0.0+git201506260226+1718+9+10~ubuntu15.04.1/src -I/build/neovim-JYUK5m/neovim-0.0.0+git201506260226+1718+9+10~ubuntu15.04.1/.deps/usr/include -I/build/neovim-JYUK5m/neovim-0.0.0+git201506260226+1718+9+10~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-JYUK5m/neovim-0.0.0+git201506260226+1718+9+10~ubuntu15.04.1/.deps/usr/include -I/build/neovim-JYUK5m/neovim-0.0.0+git201506260226+1718+9+10~ubuntu15.04.1/.deps/usr/include -I/build/neovim-JYUK5m/neovim-0.0.0+git201506260226+1718+9+10~ubuntu15.04.1/.deps/usr/include -I/build/neovim-JYUK5m/neovim-0.0.0+git201506260226+1718+9+10~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-JYUK5m/neovim-0.0.0+git201506260226+1718+9+10~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-JYUK5m/neovim-0.0.0+git201506260226+1718+9+10~ubuntu15.04.1/build/include
        Compiled by buildd@lgw01-05
        
        Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
        For differences from Vim, see :help vim-differences
        
           system vimrc file: "$VIM/nvimrc"
             user vimrc file: "~/.nvimrc"
         2nd user vimrc file: "~/.nvim/nvimrc"
              user exrc file: "~/.exrc"
          fall-back for $VIM: "/usr/share/nvim"

**Comment by justinmk** [comment]
What's `set sw?` ? Does it happen with `nvim -u NONE`?

**Comment by define-private-public** [comment]
`echo &sw` reports `8`.

If I do start with `-u NONE`, this happens when i set `tabstop=4`.  I tested this in regular old vim too and it works as I expect it to.

**Comment by justinmk** [comment]
It's because we now set `'smarttab'` by default. https://github.com/neovim/neovim/issues/2676

Add `set nosmarttab` to your vimrc if you don't want this. Though this may seem inconvenient, I think you might find you can actually remove many other lines in your vimrc, with the new defaults detailed in https://github.com/neovim/neovim/issues/2676.
