### ISSUE TITLE
[Idea] Test for known vim bugs from the todo.txt list

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#2911]
I think it could be useful to add tests for known bugs from the `todo.txt` lists, to check for regressions and possible fixes as side-effects of the work in neovim. When working on #2872 I rediscovered one of such bugs masked by one of our tests. 

These tests should fail by default, so they shouldn't be made to interfere with the CI builds, although care should be had in checking for changes before merges.

Of course, this is low priority for now, but it might be something to consider in the future.

**Comment by Pyrohh** [comment]
IMHO I think the amount of time it would require compared to the benefits would be minimal.

> These tests should fail by default, so they shouldn't be made to interfere with the CI builds, although care should be had in checking for changes before merges.

This doesn't sound like it would work. As it is, I forget to check the tests (thankfully, we have a CI infrastructure). If the tests aren't built in to the main infrastructure, what's the point in having them?

**Comment by fmoralesc** [comment]
> IMHO I think the amount of time it would require compared to the benefits would be minimal.

Yeah, probably. I might have been just too paranoid when I proposed this.

**Comment by Pyrohh** [comment]
Okey dokey, I'll close this.
