### ISSUE TITLE
Terminal: assume 256 color support by default.

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2912]
@justinmk on Gitter:

> we should probably change the logic to assume 256 minimum, unless we see some very specific terminal that definitely is not 256, e.g. msysgit

**Comment by dumblob** [comment]
+1

**Comment by justinmk** [comment]
Along with this, the doc for `:help 'term'` should be updated (or restored) and should mention that it is always set to "nvim", and that `$TERM` is used only as a hint to decide if the terminal is unlikely to support 256 colors.

**Comment by Pyrohh** [comment]
> Along with this, the doc for :help 'term' should be updated to mention that it is always set to "nvim", and that $TERM is used only as a hint to decide if the terminal is unlikely to support 256 colors.

:+1: I have `term.txt` on my list next, so I'll include `'term'` there too.
Of course it's fine if someone else does it, just putting it out there.

**Comment by Pyrohh** [comment]
In terms of reduced complexity, what's the benefit to doing this? I use nvim without X sometimes (rarely), so how nvim would behave in such a situation if this change were made.

**Comment by dumblob** [comment]
>In terms of reduced complexity, what's the benefit to doing this?

IMHO this change will actually reduce the complexity - on the side of *nvim* (e.g. the most widespread themes use 256 colors) as well as on the side of the user environment and configuration (majority of users uses terminals with 256 color support switched on).

>I use nvim without X sometimes (rarely), so how nvim would behave in such a situation if this change were made?

The goal is to behave identically - detect only reduced N color support and use appropriate theme (maybe including something like http://www.vim.org/scripts/script.php?script_id=1809).

**Comment by Pyrohh** [comment]
@dumblob 

> IMHO this change will actually reduce the complexity - on the side of nvim (e.g. the most widespread themes use 256 colors) as well as on the side of the user environment and configuration (majority of users uses terminals with 256 color support switched on).

Do you have anything specific in mind?

In terms of user configuration, I haven't had to do anything but `colorscheme=blablabla`, sometimes with `background=(dark|light)` for any colorscheme I've used for them to work. I've looked through a few of them, and besides solarized, there wasn't much logic used for dealing with terminal capabilities (at least in the few I tried).

...or perhaps you're referring to something else?

> The goal is to behave identically - detect only reduced N color support and use appropriate theme (maybe including something like http://www.vim.org/scripts/script.php?script_id=1809).

To be blunt, that's not assuming 256 colors, at least that's what I got from reading the OP.

If this was discussed on Gitter then I certainly missed it, because I'm a bit confused.

**Comment by dumblob** [comment]
>Do you have anything specific in mind?

In *vim*, most colorschemes are broken at least in one of the 3 most important outputs - GVim, 256 color terminal, 8 color console (16 color if you count in the bright/bold versions). Very often, both 256 color terminal and 8 color console are broken (except for the few widespread themes, which have at least 256 color support). Once we make 256 default, theme makers will hopefully not say "*hey, 8 color is not enough, I'm using GVim, I'll create just RGB theme*" ever again, but rather "*hey, 256 colors is pretty cool - it's sufficient, so I'll use it*". In my opinion, 256 colors is a very good middle step and thus convenient for making themes.

In general, this change is more about a "psychological" switch in mind rather then about something technical.

>To be blunt, that's not assuming 256 colors, at least that's what I got from reading the OP.

The script is about GVim -> 256/88 color terminal conversion - I've mentioned it just as an example.

>If this was discussed on Gitter then I certainly missed it, because I'm a bit confused.

I don't follow Gitter, so I can't tell.

**Comment by Pyrohh** [comment]
> Once we make 256 default, theme makers will hopefully not say "hey, 8 color is not enough, I'm using GVim, I'll create just RGB theme" ever again, but rather "hey, 256 colors is pretty cool - it's sufficient, so I'll use it". In my opinion, 256 colors is a very good middle step and thus convenient for making themes.

Ah, I see; thanks for explaining. I suppose this will take a while to have a meaningful effect, assuming that colorscheme creators will want to maintain compatibility with Vim, at least for the time being.

**Comment by justinmk** [comment]
Currently we look at TERM and if it doesn't match a know 256 color terminal we assume 16 colors I believe.

 > I use nvim without X sometimes (rarely)

Do you mean a raw Linux console, or via ssh? Either way 256 colors should be fine.

**Comment by Pyrohh** [comment]
> Do you mean a raw Linux console, or via ssh?

I mean the OpenBSD console, which behaves similar to the Linux one (at least in my experience).

> Either way 256 colors should be fine.

Yes, indeed.

**Comment by justinmk** [comment]
@Pyrohh What TERM does the OpenBSD console report?

**Comment by Pyrohh** [comment]
@justinmk VT100 IIRC. In any case color seems to work fine (as opposed to the last time I tried it), so no worries.

**Comment by justinmk** [comment]
@Pyrohh Ok, but I'm pretty certain that the non-X linux console (`TERM=linux`) does not support 256 colors, so we can just check for that.

**Comment by akavel** [comment]
(Related: #3428)
