### ISSUE TITLE
Neovim doesn't respect my colorscheme in version 0.10.0

### ISSUE THREAD

**Issue by Hund** [neovim/neovim#29127]
### Problem

When I updated to version 0.10.0, my colourscheme (the default with some of my own changes) stopped working.

I have included a before and after:

![nvimbugg](https://github.com/neovim/neovim/assets/320498/d0884318-36ed-4c55-b137-572ab9c86529)

What's up?

### Steps to reproduce

Update to Neovim 0.10.0.

### Expected behavior

That Neovim would not mess with my colorscheme or my changes.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux Mint

### Terminal name/version

GNOME Terminal 3.44

### $TERM environment variable

xterm-256color

### Installation

AppImage

**Comment by clason** [comment]
`:h news` (TL;DR: explicitly set `:colorscheme vim` before making your own changes.)

**Comment by zeertzjq** [comment]
Or `:set notermguicolors`

**Comment by Hund** [comment]
Setting  the colourscheme  to `vim` and adding the setting `set notermguicolors` seem to solve the issue.

Thanks!

**Comment by Hund** [comment]
I need to open this issue again. This was originally on Linux Mint. I'm now back on Gentoo, and I just upgraded to 0.10.1. Which broke my Solarized colourscheme.

How do I fix this mess this time?

**Comment by Hund** [comment]
I can't open this issue?

**Comment by Hund** [comment]
Anyone?

**Comment by dundargoc** [comment]
> Which broke my Solarized colourscheme.

This seems like a new issue because it is not the default theme like you wrote in the description. You should create a new issue since it's an unrelated problem.

**Comment by clason** [comment]
> You should create a new issue since it's an unrelated problem.

Please don't; this sounds like a usage question, not a Neovim bug. Open a discussion, or (better) ask on #neovim.

**Comment by Hund** [comment]
> > You should create a new issue since it's an unrelated problem.
> 
> Please don't; this sounds like a usage question, not a Neovim bug. Open a discussion, or (better) ask on #neovim.

What makes you think that? The theme stops working if I upgrade to a newer version of Neovim. If I downgrade it, it starts working again.
