### ISSUE TITLE
Disable logging for release builds.

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2913]
`CMAKE_BUILD_TYPE=Release` defines `NDEBUG` (which disables logging) by default, so no action required here. For our default build type `RelWithDebInfo`, we want assertions, so we can't use `NDEBUG`. Looking at `log.h`, we can define `DISABLE_LOG` instead.

cc @justinmk

**Comment by Pyrohh** [comment]
I'd imagine we should also remove some things from the `--version` output if building in release mode, namely `Commit: ` and the compilation date on the top line, which would get in the way of deterministic builds.

**Comment by justinmk** [comment]
I think we need a separate build, ReleaseWithDevInfo, which still writes the log.

**Comment by fwalch** [comment]
We could repurpose the existing CMake build types. Since our intention is to have assertions in release builds, our "Release" would be what is now "RelWithDebInfo" and "RelWithDebInfo" would have the logging as well.

As a side note, keeping debug info might not always work. Arch Linux does some "stripping debug info from binary" stuff during packaging.

**Comment by justinmk** [comment]
I'd prefer to leave Release as it is. It's been discussed ad nauseam in previous issues. And, there are valid reasons for wanting a small image size: in the future I would like to explore the idea of spawning several `nvim` child processes for concurrent work. E.g., for `:vimgrep`.

Does cmake allow defining a custom build type like `ReleaseWithDevInfo`?

Please don't remove `Commit:` unless there's a really good reason.

**Comment by Pyrohh** [comment]
> Please don't remove Commit: unless there's a really good reason.

When a release is tagged, it will correspond to a commit, right? I'm only talking about doing this in Release mode, i.e., after a release has been tagged.

**Comment by fwalch** [comment]
> I'd prefer to leave Release as it is. It's been discussed ad nauseam in previous issues.

Sorry for bringing it up again.

> Does cmake allow defining a custom build type like ReleaseWithDevInfo?

Yes.

> When a release is tagged, it will correspond to a commit, right?

You can't create a tag without an associated commit, so yes. However, this information is not always available that easily. For example, if you download a `master` tarball, you don't know the commit. The Ubuntu PPA has a similar problem at the moment (`nvim --version` has `Commit: ?`).

**Comment by justinmk** [comment]
> Small size would probably be MinSizeRel build type in CMake.

Ok, so that seems like a fine alternative. Is it agreed then that `MinSizeRel` will be this:

- does not contain debug info
- does not write `~/.nvimlog`
- what optimization level does it use? what is the tradeoff compared to Release?

> (nvim --version has Commit: ?)

If Commit=? then I agree we might as well omit it entirely.

**Comment by fwalch** [comment]
> what optimization level does it use? what is the tradeoff compared to Release?

By default, it uses (at least on GCC) `-Os`, which is

```
       -Os Optimize for size.  -Os enables all -O2 optimizations that do not typically increase code size.  It also performs further optimizations designed
           to reduce code size.

           -Os disables the following optimization flags: -falign-functions  -falign-jumps  -falign-loops -falign-labels  -freorder-blocks
           -freorder-blocks-and-partition -fprefetch-loop-arrays
```

**Comment by justinmk** [comment]
> `-Os disables the following optimization flags: -falign-functions  -falign-jumps  -falign-loops -falign-labels  -freorder-blocks -freorder-blocks-and-partition -fprefetch-loop-arrays`

Would it be "bad cmake practice" to change our `MinSizeRel` to use `-O2` instead of `-Os`? Then, for our purposes, "Minimum size" simply means "doesn't have debug info".

**Comment by jszakmeister** [comment]
> Would it be "bad cmake practice" to change our MinSizeRel to use -O2 instead of -Os?

I would say "yes, it's not a good practice."  We could add a way to enable/disable logging though, or create our own build type.  The downside is that we lose some abstraction with other compilers because they don't know about our custom build type.  I think we could grab some settings another way though (use `CMAKE_C_FLAGS_RELEASE` or `CMAKE_C_FLAGS_RELEASE_INIT` and the like, for example).

**Comment by fwalch** [comment]
Okay, so to summarize, these are our build types:

* `Debug`: developer build, default for top-level `Makefile`. `-O0`, assertions, debug info, log.
* `RelWithDebInfo`: release builds, default for `CMakeLists.txt`. `-Og`, assertions, debug info, no log.
* `MinSizeRel`: special applications. `-Os`, assertions, no debug info, no log.
* `RelWithDevInfo`: unstable builds. `-Og`, assertions, debug info, log.
* `Release`: ??. `-O3`, no assertions, no debug info, no log.

Packagers (e.g. Ubuntu PPA) should use `RelWithDebInfo` for released versions (e.g. upcoming 0.1) and `RelWithDevInfo` for unstable "daily" builds (is that correct?).

---

Looking at `man gcc`, we could actually enable `Og` for `Debug`:

```
-Og enables optimizations that do not interfere with debugging.
It should be the optimization level of choice for the standard
edit-compile-debug cycle
```

**Comment by elmart** [comment]
> Packagers (e.g. Ubuntu PPA) should use RelWithDebInfo for released versions (e.g. upcoming 0.1) and RelWithDevInfo for unstable "daily" builds (is that correct?).
> 

Naming is unfortunate here. Only one different letter (RelWithDebInfo vs RelWithDevInfo), and with similar sounding, is not a good idea, IMO.

**Comment by justinmk** [comment]
@elmart Valid point. Then `ReleaseDev` or `DevRelease`.

**Comment by tarruda** [comment]
Should we also change the default location of the log file? I think the user home is a poor default due to the eventual sizes a log file can have.

**Comment by justinmk** [comment]
@tarruda I have the impression that users just don't want the log file at all. That's why for end-user release I do not think we should write it.

**Comment by fwalch** [comment]
Just a reminder that the Gentoo package already uses CMAKE_BUILD_TYPE=Release, which we eventually want them to change to `RelWithDebInfo`: http://data.gpo.zugaina.org/funtoo/app-editors/neovim/neovim-0.0.0_pre20150727.ebuild

**Comment by Tranquility** [comment]
> Just a reminder that the Gentoo package already uses CMAKE_BUILD_TYPE=Release, which we eventually want them to change to RelWithDebInfo: http://data.gpo.zugaina.org/funtoo/app-editors/neovim/neovim-0.0.0_pre20150727.ebuild

@fwalch I added a new snapshot to Gentoo today and changed the build type to `RelWithDebInfo`.
