### ISSUE TITLE
color differences between nvim and vim

### ISSUE THREAD

**Issue by danielb2** [neovim/neovim#2915]
![screen shot 2015-06-27 at 13 55 31](https://cloud.githubusercontent.com/assets/26678/8393792/3ea1dca2-1cd4-11e5-9ddf-4181777ed447.png)

It seems that nvim does not color the properties in this javascript hash whereas vim does. Also seems like nvim colors the open and closing brackets (this is better) which vim does not.

Why the differences? Am I doing something wrong?

**Comment by Pyrohh** [comment]
> It seems that nvim does not color the properties in this javascript hash whereas vim does

We're missing a few runtime patches from vim, so that might be the reason for the difference.

> Also seems like nvim colors the open and closing brackets (this is better) which vim does not.

In nvim, the `matchit` plugin is loaded by default (see `:help pi_matchit`), so that might be the reason. Try adding this to the top of your `.vimrc` (it's not needed in nvim):
```
runtime! macros/matchit.vim
```

**Comment by ZyX-I** [comment]
@Pyrohh How is matchit related? It is for redefining `%` motion and defining some other related ones, not for doing *anything* with coloring.

**Comment by Pyrohh** [comment]
@ZyX-I I assumed it was also responsible for highlighting the corresponding `}` if the cursor is on `{` (and vice versa), but I haven't verified that.

**Comment by danielb2** [comment]
That didn't work, but I'm actually more interested in getting the properties colored in neovim ;)

**Comment by ZyX-I** [comment]
@Pyrohh On the screenshot there are *two* pairs of braces. Cursor was *near* the one, but not *on* any of them.

I think that this is because of default colorscheme differences.

**Comment by Pyrohh** [comment]
> Cursor was near the one, but not on any of them.

Yes, I know. I did not notice that the braces themselves were colored differently, at least until now when I zoomed into the image, so when @danielb2 said

> Also seems like nvim colors the open and closing brackets (this is better) which vim does not

I assumed that he was talking about something *not* in the screenshot, i.e., highlighting of corresponding brackets. So my mistake.

**Comment by danielb2** [comment]
@Pyrohh no problem at all. Do you have any ideas now that you know what I'm looking for?

**Comment by fmoralesc** [comment]
Try copying the vim provided syntax file for javascript over the one neovim uses. If that fixes the issue, we'll need to update the runtime files.

**Comment by danielb2** [comment]
I added `au BufNewFile,BufReadPost *.js so  ~/.vim/syntax/javascript.vim` to my .nvimrc and .vimrc files and I end up with the same result. However, I also changed it to: `au BufNewFile,BufReadPost *.js so  ~/.vim/syntax/ruby.vim` with still the same results with both, so I must be doing something wrong. 

Finally I just copied over the files in:

```
/usr/local/Cellar/vim/7.4.488/share/vim/vim74/ftplugin/javascript.vim
/usr/local/Cellar/vim/7.4.488/share/vim/vim74/indent/javascript.vim
/usr/local/Cellar/vim/7.4.488/share/vim/vim74/syntax/javascript.vim
```

to 

```
/usr/local/Cellar/neovim/HEAD/share/nvim/runtime/ftplugin/javascript.vim
/usr/local/Cellar/neovim/HEAD/share/nvim/runtime/indent/javascript.vim
/usr/local/Cellar/neovim/HEAD/share/nvim/runtime/syntax/javascript.vim
```

and still get the same results

**Comment by fmoralesc** [comment]
I get the same highlighting on vim, so 7.4.738, so perhaps a plugin you have installed is injection extra highlighting? Do you have any plugin related to javascript enabled?

**Comment by jojoyuji** [comment]
same issue for me as well :(

**Comment by danielb2** [comment]
@fmoralesc I tried loading no plugins at all with just default settings.

That's doing `vim -u noconfig -c 'syntax on' test.js` and `nvim -u noconfig -c 'syntax on' test.js`

**Comment by justinmk** [comment]
This is probably a runtime issue, should be fixed after we catch up to Vim.

**Comment by danielb2** [comment]
@justinmk  If it's an issue that's not been fixed, should it not stay an open issue regardless ? Maybe use a different label?

**Comment by justinmk** [comment]
Oh, it's not runtime related since someone above gets the same behavior in 7.4.738. Can you run Vim and then write down the value of VIMRUNTIME, then run Neovim with

     VIMRUNTIME=/path/to/vim/runtime nvim

And see if the problem still happens. This seems like a difference with the homebrew version of Vim.

**Comment by danielb2** [comment]
How do I get the value of VIMRUNTIME?  ?

**Comment by danielb2** [comment]
nevermind, `:! echo $VIMRUNTIME`  worked

**Comment by danielb2** [comment]
Still the same issue with colors for me.

**Comment by justinmk** [comment]
At this point we have no details about how to reproduce this issue, so I'm not sure what can be done.

**Comment by justinmk** [comment]
@danielb2 What was the exact command you used to install Vim with homebrew? Also, what version of OS X are you using?

**Comment by danielb2** [comment]
`brew install --HEAD neovim/neovim/neovim`
10.10.5

I've tried various runtime options before to try to figure out the difference. I thought there would be some difference in how it handles TERM or some such myself. 

What OS are you running it on?

**Comment by justinmk** [comment]
*Vim*, not Neovim.

**Comment by danielb2** [comment]
`brew install vim`

**Comment by danielb2** [comment]
I just compiled the source code on FreeBSD from the github repo, and I'm seeing the same color differences on FreeBSD

**Comment by justinmk** [comment]
@danielb2 Vim in FreeBSD does *not* exhibit this issue?

**Comment by danielb2** [comment]
I'm seeing the _same_ color differences, i.e. it is exhibiting this issue as well

**Comment by danielb2** [comment]
Btw, in my screenshot above, vim is to the left, and nvim is to the right

**Comment by justinmk** [comment]
Ok. That's a useful data point, but that still leaves us where we started :)

**Comment by danielb2** [comment]
Can you try virtualbox perhaps with freebsd, and see if you can repro there?

**Comment by danielb2** [comment]
vagrant should make that pretty simple

**Comment by justinmk** [comment]
You just said yourself that Vim does not exhibit this issue on FreeBSD. And I have no idea *how* to repro this issue in the first place...

**Comment by danielb2** [comment]
The problem is that there's a difference between the color schema between vim AND neovim.  It's not an issue of vim or neovim exhibiting an issue.   They produce different results as far as color schema.

_neovim_ is not showing syntax colors of object properties, and it's not showing different colors for `var` vs `function` keywords in my example. 

My original question was, and remains:  Why is there a difference between the color output using the same color schema?

**Comment by justinmk** [comment]
What colorscheme? Here is what I see:

![image](https://cloud.githubusercontent.com/assets/1359421/9337180/c7666512-45ab-11e5-9115-8fea5db1fc89.png)

`function` is recognized as `jsFunction`, `key` is recognized as `jsObjectKey jsBlock`, and `value` is recognized as `jsBlock`.

**Comment by danielb2** [comment]
I finally figured it out. There was a .vim/syntax/javascript.vim file that wasn't being read and somehow I missed it in all my attempts :/  sorry for the waste of time

**Comment by justinmk** [comment]
No problem, thanks for the followup.

**Comment by migore** [comment]
I was facing the same issue of having different colors in nvim and vim. After soe diggin I realized it was happening only inside tmux. In fact, my vim colors inside tmux was different from my vim colors directly from bash.

[This link](http://stackoverflow.com/questions/10158508/lose-vim-colorscheme-in-tmux-mode) helped me to fix my problem.

It was not related to nvim but it might help someone in the future. This thread was my first result when searching.
