### ISSUE TITLE
Unsupported method warning issued when calling `vim.lsp.codelens.run`

### ISSUE THREAD

**Issue by sykesm** [neovim/neovim#29156]
### Problem

The following warning is emitted when calling `vim.lsp.codelens.run`:

> method textDocument/codeLens is not supported by any of the servers registered for the current buffer

Neovim 0.10 changed the behavior of `vim.lsp.codelens.refresh` to refresh all buffers by default in https://github.com/neovim/neovim/pull/27253. The warning is written when an LSP client that does not support code lenses is attached to a different buffer at the time the code lens executes.

The source appears to be a call to `vim.lsp.codelens.refresh` out of the [`execute_lens` handler](https://github.com/neovim/neovim/blob/27fb62988e922c2739035f477f93cc052a4fee1e/runtime/lua/vim/lsp/codelens.lua#L53). Prior to 0.10, this would only refresh lenses for the current buffer but now it attempts to refresh lenses for all buffers.

### Steps to reproduce using "nvim -u minimal_init.lua"

1. Open a file and attach an LSP that does not support code lenses (e.g. dockerls)
2. Open a different file in another buffer and attach an LSP that does support code lenses
3. Execute a code lens in the second buffer
4. Observe that a warning is written

### Expected behavior

Running a code lens should not result in warnings associated with unrelated clients that are not attached to the current buffer.

### Neovim version (nvim -v)

NVIM v0.10.0

### Language server name/version

gopls v0.15.3 and dockerls v0.12.0

### Operating system/version

macOS Sonoma and Ubuntu Linux 22.04

### Log file

https://gist.github.com/sykesm/55a67323b8af9bea59d61ee7d9a0d7fe

**Comment by crwebb85** [comment]
Im not at my computer, but doesn't the refresh function now let you pass in the buffer number? Would adding that fix the issue?

**Comment by tmtd4c93aac** [comment]
@crwebb85 That's the "fix" to go back to the previous behaviour but why have the new behaviour if it's not usable as is? It feels like a pretty standard workflow to have more than one type of file opened in the same session.

Could it instead refresh only the buffers with the right capability?

**Comment by yimincai** [comment]
same problem here

**Comment by alduro** [comment]
receiving this in my case 

```
Error detected while processing InsertLeave Autocommands for "*.go":
method textDocument/codeLens is not supported by any of the servers registered for the current buffer
```

**Comment by osleg** [comment]
`refresh` is now accepting bufnr, so the only thing you have to do is to tell it refresh only the buf you are interested in, for example
```
        local function setup_codelens_refresh(client, bufnr)
          local status_ok, codelens_supported = pcall(function()
            return client.supports_method("textDocument/codeLens")
          end)
          if not status_ok or not codelens_supported then
            return
          end
          local group = "lsp_code_lens_refresh"
          local cl_events = { "BufEnter", "InsertLeave" }
          local ok, cl_autocmds = pcall(vim.api.nvim_get_autocmds, {
            group = group,
            buffer = bufnr,
            event = cl_events,
          })
          if ok and #cl_autocmds > 0 then
            return
          end
          local cb = function()
            if vim.api.nvim_buf_is_loaded(bufnr) and vim.api.nvim_buf_is_valid(bufnr) then
              vim.lsp.codelens.refresh({ bufnr = bufnr })
            end
          end
          vim.api.nvim_create_augroup(group, { clear = false })
          vim.api.nvim_create_autocmd(cl_events, {
            group = group,
            buffer = bufnr,
            callback = cb,
          })
        end
```
and then  call this function in your `onattach`, it will check for the buffer availability, for codelens for availability for the lsp and created `au`s to automatically refresh only the specified buffers

**Comment by tmtd4c93aac** [comment]
@osleg As I said before that is fine if what you want is reverting to the previous behaviour, but I still question the usefulness of the default behaviour.

The reasoning for the change in https://github.com/neovim/neovim/pull/27253 is the following:
> ... given that the protocol documents [workspace/codeLens/refresh](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeLens_refresh) as "refreshing the code lenses currently shown in editors"

I think it's fair to say that "refreshing the code lenses currently shown in editors" would be more useful if it meant it only refreshed the buffers with the right capabilities rather than raising a lot of warnings for the buffers without.

**Comment by damccull** [comment]
I just discovered this very issue. I'd rather not, as a neovim newb, have had to figure this out, and have it just work. Makes sense to me to only refresh codelenses per buffer that are _attached_ to that buffer and _support codelenses_.

**Comment by stocks29** [comment]
If anyone is hitting this with lunarvim and just wants the errors to go away add this to your config:

```
lvim.lsp.code_lens_refresh = false
```
