### ISSUE TITLE
Programmatic way of getting spelling errors

### ISSUE THREAD

**Issue by ravibrock** [neovim/neovim#29167]
### Problem

The neovim spell checker is very useful, but there doesn't seem to be any straightforward way to get all spelling mistakes in a buffer with Lua without iterating through them with `]s`. Ideally, there would be a function like `vim.fn.get_spelling_errors(bufnr)` that would return all errors in a buffer as a table (while preserving things like Treesitter context-dependence that are ignored by `vim.spell.check()`.

### Expected behavior

The new feature would look like a function that returns the same result that would be provided by iterating through the buffer with `]s` and writing down each mistake found. This would solve the problem, and it would be useful because it would (probably) be faster than iterating through, would definitely be more elegant, and would be simpler to run in the background as it wouldn't require moving and then resetting the cursor. Something like:
```lua
{
  {
    word = "tset",
    severity = "bad",
    linenr = 20,
    colnr = 10,
  },
  {
    word = "grey",
    severity = "local",
    linenr = 15,
    colnr = 5,
  },
}
```

**Comment by lewis6991** [comment]
You can use `vim.spell.check` and pass in each line of the buffer manually. I don't think we need to provide a first class function for this.

**Comment by ravibrock** [comment]
Thanks for the reply. I was thinking it could be useful to have something that would integrate with things like Treesitter automatically (whereas `vim.spell.check` is strictly strings), but it might be too niche.

**Comment by lewis6991** [comment]
I guess the main point is that Neovim already exposes everything needed for this to be implemented so there isn't anything that can't be done via a custom function or plugin.

**Comment by ravibrock** [comment]
How does it expose something like "get next spelling error"? I went through the source code and it looks like `]s` is hardcoded in C--there isn't an API for getting the location of the next spelling error. I guess my suggestion is to expose whatever method(s) Neovim uses internally to jump to the next spelling error in such a way that they can be called directly in Lua, since presumably they exist in the C codebase.

**Comment by lewis6991** [comment]
- You can get the buffer text
- You can iterate words using a pattern. 
- You can check if a certain position has a `@spell` capture
- You can check the spelling of a string.

It isn't exactly the same as what the C codebase does, but I'm not sure it needs to be. And I'm not sure it's even feasible given how it is implemented in C. Last time I checked I remember being quite ad-hoc.

We can, if need be, improve the API for any one of these points.

**Comment by ravibrock** [comment]
That makes sense, thanks. I'll try to implement iteration through `@spell` groups tomorrow and see how it goes. If I can get that working it would probably be as close to an ideal solution as is necessary.

**Comment by asmodeus812** [comment]
> You can use `vim.spell.check` and pass in each line of the buffer manually. I don't think we need to provide a first class function for this.

Why would we want to do the work again ? The spelling checks are already processed and obtained from vim in the buffer, there is no reason to do the same work again, simply to obtain the same information because there is no public api to do so. I think this is a flawed approach. This makes only sense if the user has not enabled spell checking for the buffer and wants to manually compute them and do something else. So both the vim.spell.check and a dedicated api to extract already processed spelling errros, have their applications

**Comment by lewis6991** [comment]
> It does some work for the visible part, so visible spelling errors are processed at least. 

Yes which is usually a very small fraction of the buffer.

And to repeat it does this **every single screen redraw** (not on reading the buffer) and the results are never cached, so it's not expensive to run and there is no problem doing this again in an interactive context for the whole buffer.
