### ISSUE TITLE
<afile> cannot be expanded when running with -V1

### ISSUE THREAD

**Issue by stevearc** [neovim/neovim#29175]
### Problem

If running Neovim with the `-V1` flag, expanding `<afile>` inside an autocmd produces an error:

```
Error executing vim.schedule lua callback: [string ":source (no file)"]:10: BufNew Autocommands for "*": Vim(append):Error executing lua callback: Vim:E495: No autocommand file name to substitute for "<afile>"
stack traceback:
        [C]: in function 'expand'
        [string ":source (no file)"]:5: in function <[string ":source (no file)"]:4>
        [C]: in function 'tabnew'
        [string ":source (no file)"]:10: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'tabnew'
        [string ":source (no file)"]:10: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to reproduce

```lua
-- bug.lua
local aug = vim.api.nvim_create_augroup("bug", {})
vim.api.nvim_create_autocmd("BufNew", {
  group = aug,
  callback = function()
    print(vim.fn.expand("<afile>"))
  end,
})

vim.defer_fn(function()
  vim.cmd.tabnew()
end, 500)
```

1. nvim --clean -V1 bug.lua
2. `:source`

Note that this _only_ reproduces with `-V1`. Running `nvim --clean bug.lua` produces the expected result. I was also able to get this to reproduce with vimscript, which was how I was able to test this with vanilla vim.

```vim
" bug.vim
aug foo
  autocmd BufNew * echomsg expand('<afile>')
aug END

tabnew
```

### Expected behavior

No error

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713773202

### Vim (not Nvim) behaves the same?

yes, 9.0 

### Operating system/version

macOS 14.5

### Terminal name/version

kitty 0.34.1

### $TERM environment variable

tmux-256color

### Installation

homebrew

**Comment by wookayin** [comment]
From `:help expand()`

>		When 'verbose' is set then expanding '%', '#' and <> items
>		will result in an error message if the argument cannot be
>		expanded.

Per the documentation, it is not quite clear whether printing error message should result in the Lua executor throwing Error (which is the current implementation) or shouldn't interfere with the control flow. So I assumed this is by design (from upstream vim). See also https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1145#issuecomment-1769026842

For the record, this behavior has been there since Neovim 0.8.0 -- it was not throwing an error. See #19905 (a9e6cf0e64ede3fc26226fed3a5f94a7f5020918)

**Comment by stevearc** [comment]
Ah, so the idea is that expanding `<afile>` is actually "failing" in the normal case by expanding to the empty string, and that with `-V1` it is intentionally throwing an error instead. I don't love that changing the verbosity affects control flow, but agree that it makes sense to align with upstream vim.

Thanks for the clarification!
