### ISSUE TITLE
nvim -l does not support reading from stdin

### ISSUE THREAD

**Issue by xsh005** [neovim/neovim#29179]
### Problem

`nvim -l` does not read from stdin, which is inconsistent with `lua` and `luajit`
```
❯ echo "print('hello')" | lua
hello
❯ echo "print('hello')" | luajit
hello
❯ echo "print('hello')" | nvim -l
nvim: Argument missing after: "-l"
More info with "nvim -h"
```

### Expected behavior

If a script path was not given, `nvim -l` tries reading from stdin.

**Comment by justinmk** [comment]
> If a script path was not given, `nvim -l` tries reading from stdin.

Pass `-` as the script path. This is documented at `:help -l` .

    echo "print('hello')" | nvim -l -

**Comment by mfussenegger** [comment]
There's also [nlua](https://github.com/mfussenegger/nlua) which is a smallish wrapper around nvim -l to provide the lua command line interface, so that it can work with tools like busted or luarocks which support alternative interpreter implementations.
