### ISSUE TITLE
Allow registering additional sources for `vim.lsp.completion`

### ISSUE THREAD

**Issue by GoldsteinE** [neovim/neovim#29183]
### Problem

`vim.lsp.completion` is essentially a completion engine upstreamed into core. Right now it can’t really replace external completion engines like nvim-cmp since it doesn’t allow other plugins to register new completion sources. That’s really unfortunate, since unified API for providing completions could solve the N*M problem here (N completion providers communicating with M completion engines).

### Expected behavior

- `vim.lsp.completion` gains an API that allows plugins to register their own completion sources. Probably a couple of them (like “buffer words” or “FS paths”) could be provided with default runtime.
- Ideally it also provides an API to allow an external completion engine to query all registered completion sources or register itself as a “completion UI”, similar to `vim.ui` APIs. That would allow completion UIs that are too complex to be accepted into core to benefit from the unified API.
- It probably makes sense to move `vim.lsp.completion` to `vim.completion`, as it happened with `vim.lsp.diagnostics`.

**Comment by clason** [comment]
>  Right now it can’t really replace external completion engines like nvim-cmp since it doesn’t allow other plugins to register new completion sources.

And it's not intended to; the module relies on trigger characters according to the LSP spec. It is planned to expose parts of this (where it makes sense) for other plugins to build on, but (at this moment) _not_ to turn this into an autocomplete plugin like nvim-cmp.

The general issue around completion is already tracked in https://github.com/neovim/neovim/issues/16488.

**Comment by mfussenegger** [comment]
Additional sources can also be implemented as additional language server. It's still questionable if a additional separate abstraction would add anything over that. 

Relates a bit to https://github.com/neovim/neovim/pull/24338

**Comment by glepnir** [comment]
there have a new server do the same thing https://github.com/antonk52/basics-language-server/

**Comment by FelipeLema** [comment]
you can also leverage https://github.com/nvimtools/none-ls.nvim

```lua
local null_ls = require "null-ls"
null_ls.setup {
  log_level = "off",
  sources = {
    null_ls.builtins.diagnostics.tidy,
    {
      name = "basic_snippets",
      filetypes = { "lua" },
      method = null_ls.methods.COMPLETION,
      generator = {
        async = true,
        --- @param params NullLsParams
        --- @param done fun(lsp.CompletionList)
        fn = function(params, done)
          ---@type lsp.CompletionItem[]
          local item_candidates = {
            {
              label = "todo",
              kind = vim.lsp.protocol.CompletionItemKind.Snippet,
              insertTextFormat = vim.lsp.protocol.InsertTextFormat.Snippet,
              detail = "-- TODO …",
              insertText = "-- TODO $0",
            },
            {
              label = "fun",
              kind = vim.lsp.protocol.CompletionItemKind.Snippet,
              insertTextFormat = vim.lsp.protocol.InsertTextFormat.Snippet,
              detail = "function() … end",
              insertText = "function($1)\n\t$0\nend\n",
            },
          }
          ---@type lsp.CompletionItem[]
          local items = vim
            .iter(item_candidates)
            :filter(
              ---@param i lsp.CompletionItem
              ---@return boolean
              function(i)
                return #vim.fn.matchfuzzy({ i.label }, params.word_to_complete or "") > 0
              end
            )
            :totable()
          done {
            { items = items, isIncomplete = #items == 0 },
          }
        end,
      },
    },
  },
}
```

do mind that you'll probably need to use `autotrigger = true` and add chars to trigger chars:

```lua
vim.api.nvim_create_autocmd("LspAttach", {
  group = vim.api.nvim_create_augroup("My LSP completion", { clear = true }),
  callback = function(args)
    local cliente = assert(vim.lsp.get_client_by_id(args.data.client_id))
    local bufnr = args.buf
    if cliente:supports_method "textDocument/completion" then
      -- :he lsp-completion
      -- :he lsp-format
      local chars = {}
      for i = 32, 126 do
        table.insert(chars, string.char(i))
      end
      cliente.server_capabilities.completionProvider.triggerCharacters = chars
      vim.lsp.completion.enable(true, cliente.id, bufnr, { autotrigger = true })
    end
  end,
})
```
