### ISSUE TITLE
ShaDa file corruption on nightly

### ISSUE THREAD

**Issue by yngwi** [neovim/neovim#29186]
### Problem

Neovim Nightly seems to randomly corrupt the ShaDa File. See the attachment for the corrupted file (remove the .txt extension)
[main.shada.txt](https://github.com/user-attachments/files/15551731/main.shada.txt)

### Steps to reproduce

1. Create test folder with init.lua following the template and a markdown file with some text
2. Edit `nvim -u init.lua test.md`
3. Make some edits
4. Save & close with `:x`
5. Repeat `2` - `4` until the corruption appears
6. Error message `E576: Failed to parse ShaDa file: extra bytes in msgpack string at position 4083` appears on start

### Expected behavior

No corruption occurs.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-168+ge20c5fba2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 11

### Terminal name/version

Windos Terminal

### $TERM environment variable

?

### Installation

Download nightly from GitHub

**Comment by tris203** [comment]
I am seeing similar issues on Ubuntu. I had had to clear the ShaDA folder multiple times since around a week or so ago

**Comment by axelhj** [comment]
I've seen the same error message frequently since around v0.11 (nightly/build from master) but also before that. A plugin that I use write shada on VimLeave. I see https://github.com/neovim/neovim/issues/8587 when running Neovim on Windows 11 and wonder if there is a link with that shada error at least in some instances. I am not sure why those tmp-files are used in the first place.

**Comment by metiftikci** [comment]
for me, removing `AppData/Local/nvim-data/shada` folder resolved the problem

**Comment by AThePeanut4** [comment]
I'm also getting this, but only on Windows, and it seems to be a _read_ issue not a _write_ issue - if I copy the `main.shada` file that was giving E576 errors over to WSL, it works without issue. Reverting to the v0.10 release also works correctly, with that same `main.shada` file.

I'm using the latest git commit on WSL (f69937f) and the latest nightly on Windows (f69937fdb).

**Comment by AThePeanut4** [comment]
@bfredl Just did a bisect, and I can confirm the first bad commit is indeed 7e44ab696a0488ad234b0915a8cf804fd6d79156 (#29093).

**Comment by bfredl** [comment]
@AThePeanut4 would you mind try https://github.com/neovim/neovim/pull/29221 and see if it helps?

**Comment by AThePeanut4** [comment]
@bfredl Can confirm #29221 fixes it, thanks!

**Comment by melMass** [comment]
I think this issue also affects stable 0.10.0....
I was experiencing it a lot but haven't since I'm building from source

**Comment by adelarsq** [comment]
@melMass This issue did begin around a week ago (after 0.10 release), so I think that there is another issue on 0.10. Do you have any logs?

**Comment by melMass** [comment]
Sorry I don't, I wiped everything in nvim-data multiple time to isolate the issue and don't have it since I'm using nightly. I had the bug since I updated to 0.10 but just got the habit to remove those extra shada when it happened!
