### ISSUE TITLE
vim.highlight.range does not support -1 as column value

### ISSUE THREAD

**Issue by asmodeus812** [neovim/neovim#29194]
### Problem

It could be a possible regresssion, for `vim.highlight.range` can not highlight the whole line. Tried with regtype = V or regtype = l, as mentioned in setreg.

### Steps to reproduce

nvim -U none

populate the file with at least one line, changing inclusive makes no difference

    :lua vim.highlight.range(0, vim.api.nvim_create_namespace("user"), "IncSearch", { 0, 0 }, { 0, -1 }, { regtype = "V", inclusive = false | true })

populate the file with a few lines, that works, highlights linewise, between the lines

    :lua vim.highlight.range(0, vim.api.nvim_create_namespace("user"), "IncSearch", { 0, 0 }, { 1, -1 }, { regtype = "V", inclusive = false | true })

Note that the highlight works in case the end range is on a different line instead, i.e the row is not the same as in the start opts.

### Expected behavior

The entire line in the buffer should be highlighted.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ubuntu 22

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

github

**Comment by zeertzjq** [comment]
This sounds like a feature request rather than a bug report.

**Comment by justinmk** [comment]
IIRC, `-1` used to be accepted, but now it's not. If you change the `-1` column specification to `vim.v.maxcol`, it works.

I guess this is technically a regression.

**Comment by zeertzjq** [comment]
That seems to be a different issue.

**Comment by asmodeus812** [comment]
Yeah, it indeed used to be possible. i had it used like that, with -1, with 0.9.5

**Comment by zeertzjq** [comment]
I compared the behavior of v0.9.5 and v0.10.0 and they seem to be the same.

**Comment by asmodeus812** [comment]
For me i see different behaviour, i tested with both 9.4 and 9.5 and i can highlight the entire line using `-1`. 

9.5
![image](https://github.com/neovim/neovim/assets/15955811/06435eb8-1c63-4301-9cc7-87966f2b91af)

```lua
:lua vim.highlight.range(0, vim.api.nvim_create_namespace("user"), "IncSearch", { 0, 0 }, { 0, -1 }, { regtype = "V" })
```

**Comment by zeertzjq** [comment]
I misunderstood what you meant by "highlighting the whole line". I tested in v0.10.0 and it still works. It doesn't work in nightly.

**Comment by asmodeus812** [comment]
Strange, my verbose `--version` shows this 

```txt
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202

  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/0.10.0/share/nvim"

Run :checkhealth for more info
```

But i can not make highlight work linewise in 0.10.0, i am not using nightly.
