### ISSUE TITLE
`vim.keymap.del(mode, keymap, {buffer=true})` is broken on 0.10.0

### ISSUE THREAD

**Issue by Alex23rodriguez** [neovim/neovim#29191]
### Problem

when attempting to unset a key for a single buffer one gets the error:

```txt
E5108: Error executing lua vim/keymap.lua:0: E31: No such mapping
stack traceback:
        [C]: in function 'nvim_buf_del_keymap'
        vim/keymap.lua: in function 'del'
        [string ":lua"]:1: in main chunk
```

### Steps to reproduce
```
nvim --clean test.txt
:lua vim.keymap.set("n", "<CR>", "i")
:lua vim.keymap.del("n", "<CR>", { buffer = true })
```

### Expected behavior

for the keymap to be deleted for the current buffer.

calling without `buffer=true` works as expected

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release

### Vim (not Nvim) behaves the same?

no. this is the lua api

### Operating system/version

MacOS 14.1.1

### Terminal name/version

alacritty 0.12.2

### $TERM environment variable

screen-256color

### Installation

homebrew

**Comment by justinmk** [comment]
why does the title mention "on 0.10.0", as if this "worked" in previous versions?

    :lua vim.keymap.set("n", "<CR>", "i")

that is not a buffer-local mapping. thus the error message is correct. same happens in vim:

```
nn <cr> i
unmap <buffer> <cr>

E31: No such mapping
```

**Comment by Alex23rodriguez** [comment]
I apologize for the confusion. I can see this is indeed the intended behavior.
I was trying to remove a global mapping in the local buffer depending on the filetype.
I found a workaround by mapping the key to itself in the intended buffer, instead of trying to remove the mapping
