### ISSUE TITLE
Middle mouse button pastes wrong register.

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2919]
With `mouse=a` (which is now a default: #2860), middle mouse button in Neovim does not paste the contents of the `*` register (which is what Vim does).

As @fmoralesc figured out, it instead pastes the contents of the `"` register, and expected behavior in this case can be restored by setting `clipboard=unnamed`.

See also discussion starting at https://github.com/neovim/neovim/pull/2860#issuecomment-116131481.

**Comment by skawouter** [comment]
Would it be a good solution to just set the default of clipboard to unnamed?

Or should nvim use the * register if clipboard is not set?

**Comment by bfredl** [comment]
Seems the following got "lost in translation" in `normal.c:do_mouse()`
```
#ifdef FEAT_CLIPBOARD
		if (clip_star.available && regname == 0)
		    regname = '*';
#endif
```

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/3014
