### ISSUE TITLE
Incorrect conceal in help

### ISSUE THREAD

**Issue by kaddkaka** [neovim/neovim#29204]
### Problem

The source code `'*'` triggers the same concealmeant as labels.

For example 
* label `*autocmd-pattern*` shows up as `autocmd-pattern`.
* `'*'` inocrrectly shows up as `''`

### Steps to reproduce

in `autocmd.txt` check the line with text `Note:  To match part of a path,`... with `set conceallevel=1`

### Expected behavior

the `'*'` to show up as a literal, not concealed.

### Neovim version (nvim -v)

0.9.4

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu

### Terminal name/version

-

### $TERM environment variable

-

### Installation

package manager

**Comment by clason** [comment]
I don't see an issue. Please always test with the latest version (0.10.0, or ideally nightly).

**Comment by clason** [comment]
> Seems to be a matter of treesitter capture,

No, because 0.10 enables treesitter highlighting is enabled by default for help files. (`:TS*` commands are specific to nvim-treesitter so irrelevant here.)

**Comment by samharju** [comment]
Relevant for original issuer though. I updated nvim-treesitter from 0.9.2 to latest commit and conceal seems to work correctly for help files regardless of :TS*.

**Comment by hinell** [comment]
A bit late, but after updating `nvim-treesitter` you  may also want to `TSUpdate vimdoc` module. Otherwise there are errors. 


I'm using `NVIM v0.11.0-dev-169f37b94f` and https://github.com/nvim-treesitter/nvim-treesitter/commit/cfd2095e66e49ea0dfbef6b41be2efd0ba6cc4ee
