### ISSUE TITLE
Text edits with the same start position are applied in reverse

### ISSUE THREAD

**Issue by alcolmenar** [neovim/neovim#29202]
### Problem

Text edits returned from the LSP that have the same start position are being applied in reverse. For example:

For the following dummy text,
```elixir
defmodule Dummy do
  alias B
  alias A

  def hello do
  end
end
```

and following edits:
```
[DEBUG][2024-06-02 08:39:45] .../vim/lsp/rpc.lua:387	"rpc.receive"	{
  id = 10,
  jsonrpc = "2.0",
  result = { {
      edit = {
        changes = {
          ["file:///Users/scottming/Code/dummy/lib/dummy.ex"] = { {
              newText = "",
              range = {
                ["end"] = {
                  character = 0,
                  line = 3
                },
                start = {
                  character = 0,
                  line = 2
                }
              }
            }, {
              newText = "\n",
              range = {
                ["end"] = {
                  character = 0,
                  line = 2
                },
                start = {
                  character = 0,
                  line = 1
                }
              }
            }, {
              newText = "  alias A\n  alias B",
              range = {
                ["end"] = {
                  character = 0,
                  line = 1
                },
                start = {
                  character = 0,
                  line = 1
                }
              }
            } }
        }
      },
      kind = "source.organizeImports",
      title = "Organize aliases"
    } }
}
```

Results in the following:
```elixir
defmodule Dummy do

  alias B  alias B

  def hello do
  end
end
```

According to the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEditArray), text edits with the same start position should be applied in the order received.

Also, in the [vscode implementation](https://github.com/microsoft/vscode-languageserver-node/blob/main/textDocument/src/main.ts#L371), similar start position text edits aren't sorted in reverse order

Additional context can be found on an issue filed on the lexical repo
https://github.com/lexical-lsp/lexical/issues/765

### Steps to reproduce using "nvim -u minimal_init.lua"

Using this minimal init,
```lua
--- CHANGE THESE
local pattern = { 'elixir', 'eelixir' }
local cmd = { '/path/to/lexical/_build/dev/package/lexical/bin/start_lexical.sh' }
-- Add files/folders here that indicate the root of a project
local root_markers = { '.git', '.editorconfig' }
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'bugged-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings,
    })
  end,
})
```

and this dummy file:
```elixir
# dummy.exs
defmodule Dummy do
  alias B
  alias A

  def hello do
  end
end
```

1. Open up the dummy file with the command `nvim -u minimal_init.lua dummy.exs`
2. Navigate to the first alias and run the command `:lua vim.lsp.buf.code_action()`
3. Run the `Organize aliases` code action to sort the aliases

### Expected behavior

The code action should result in the file:
```elixir
# dummy.exs
defmodule Dummy do
  alias A
  alias B

  def hello do
  end
end
```

### Neovim version (nvim -v)

v0.10.0 release

### Language server name/version

lexical v0.6.1

### Operating system/version

macos 14.4.1

### Log file

https://gist.github.com/alcolmenar/fd784a80a8f91c6a254e74cb3c1ed3b6

**Comment by alcolmenar** [comment]
I'd like to take this issue on if the team decides, it should be fixed

**Comment by mfussenegger** [comment]
> If possible, I'd like to take this issue on if the team decides that it should be fixed.

Sounds like a bug so yes, a PR with a fix and a test case would be great

**Comment by scohen** [comment]
Hi there, I'm the author of an LS for elixir, and I'm actually wondering why you're sorting the edits at all, since the spec declares that the order of the edits is important.  Sorting the text edits seems incorrect to me, since language servers are putting them in the order they send them for a reason.

**Comment by scohen** [comment]
@mfussenegger Can you please explain the thinking behind reordering the list of changes the language servers send you?

**Comment by hrsh7th** [comment]
Thank you. @alcolmenar 
It seems that was my mistake.

As far as I know, neovim has a policy of complying with the LSP specifications, but TextEdit is implemented based on the behavior of VSCode.

**Comment by kyoh86** [comment]
:memo: This change causes the line positions in the formatting results by efm-langserver to be swapped.
It needs to research where is a bug...

**Comment by scohen** [comment]
The changes should be applied as given by the language server. You shouldn’t reorder them

**Comment by kyoh86** [comment]
@mfussenegger @alcolmenar 
I'm having trouble #29392 with this change affecting the behavior of the other ls, but I don't know what's right, so please give us your opinion.

**Comment by bangalcat** [comment]
I'm wondering the same thing, is reordering really necessary here?

**Comment by iurimateus** [comment]
fwiw, I've been running without reordering with no issues on either Lexical or typescript-tools (tsserver).

```patch
diff --git a/runtime/lua/vim/lsp/util.lua b/runtime/lua/vim/lsp/util.lua
index b0fd25af3..f59674059 100644
--- a/runtime/lua/vim/lsp/util.lua
+++ b/runtime/lua/vim/lsp/util.lua
@@ -396,9 +396,6 @@ function M.apply_text_edits(text_edits, bufnr, offset_encoding)
     if a.range.start.character ~= b.range.start.character then
       return a.range.start.character > b.range.start.character
     end
-    if a._index ~= b._index then
-      return a._index < b._index
-    end
     return false
   end)
 
diff --git a/test/functional/plugin/lsp_spec.lua b/test/functional/plugin/lsp_spec.lua
index 2b8a7aed9..a7e1f5f3f 100644
--- a/test/functional/plugin/lsp_spec.lua
+++ b/test/functional/plugin/lsp_spec.lua
@@ -1794,9 +1794,9 @@ describe('LSP', function()
       }
       exec_lua('vim.lsp.util.apply_text_edits(...)', edits, 1, 'utf-16')
       eq({
-        '3',
-        'foo',
-        '12Fbar',
+        '',
+        '123',
+        'fooFbar',
         '123irst guy',
         'baz line of text',
         'The next line of text',
@@ -1818,9 +1818,9 @@ describe('LSP', function()
       }
       exec_lua('vim.lsp.util.apply_text_edits(...)', edits, 1, 'utf-16')
       eq({
-        '3',
-        'foo',
-        '12Fbar',
+        '',
+        '123',
+        'fooFbar',
         '123irst guy',
         'baz line of text',
         'The next line of text',
```

**Comment by Rid1FZ** [comment]
Hi there. I was also having some issues with `basedpyright` language server. I totally forgotten about this until I re encountered the same issue. Seems like swapping the order of sorting fixes the issue. But I am pretty sure it may will introduce new issues. Could anyone please check this? [#31655](https://github.com/neovim/neovim/issues/31655)

**Comment by objectuser** [comment]
I'm also encountering reordering issues only with Neovim (compared to VSCode).

**Comment by objectuser** [comment]
Just confirmed on `master`, removing these lines fixes at least the ordering issue for me.

https://github.com/neovim/neovim/blob/9ff12396347b0356b856b68b0e3010b3c8ec2e00/runtime/lua/vim/lsp/util.lua#L325-L337
