### ISSUE TITLE
nvim reports error when using "help".

### ISSUE THREAD

**Issue by cbmeeks** [neovim/neovim#29213]
### Problem

I just installed a clean copy of neovim and when I launch the :help system, I get the error below.

My OS is Fedora 40 with GNOME.  Everything on my machine is pretty vanilla so I don't think any extensions would be causing issues.

Thanks for any help.

![image](https://github.com/neovim/neovim/assets/49341/d8dd6377-7fab-4f60-8f1d-8e43ed43d076)

My version information:

![image](https://github.com/neovim/neovim/assets/49341/77b79c1b-2a46-4af4-bf1a-16c7092a3bb5)

### Steps to reproduce

Launch nvim and type :help.

### Expected behavior

Should launch help 

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

No, vim works.

### Operating system/version

Fedora 40

### Terminal name/version

GNOME terminal

### $TERM environment variable

None at the moment

### Installation

sudo dnf install neovim

**Comment by zeertzjq** [comment]
This is a problem with the Fedora package.

**Comment by cbmeeks** [comment]
OK, so I will reach out to the Fedora community.  lol
Thanks
