### ISSUE TITLE
E5113 error during install

### ISSUE THREAD

**Issue by spinkyspider** [neovim/neovim#29228]
### Problem

Alpine Linux v3.21
neovim v.0.10.0
Installing using the Bootstrap script

Downloading luarocks...                                                                                          
Configuring luarocks...                                                                                          
Error detected while processing /home/churk/.config/nvim/init.lua:                                               
E5113: Error while calling lua chunk: /home/churk/.config/nvim/init.lua:53: Vim:Configuring luarocks failed.     
stack traceback:                                                                                                 
        [C]: in function 'source'                                                                                
        /home/churk/.config/nvim/init.lua:53: in main chunk  
```

[init.lua.zip](https://github.com/user-attachments/files/15722050/init.lua.zip)



### Steps to reproduce

put the bootstrap script in ~/.config/nvim/init.lua
then run 'nvim'

### Expected behavior

I had hoped luarocks would have installed and worked. :-/

NVIM v0.10.0
Build type: MinSizeRel
LuaJIT 2.1.1710398010

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: MinSizeRel

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Alpine Linux v3.21

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

~ $ echo $TERM --> xterm-kitty

### Installation

Alpine Linux Package manager

**Comment by clason** [comment]
Not a Neovim issue (we don't use luarocks).

**Comment by spinkyspider** [comment]
Oh geez. wrong repository.  Can somebody whack this?  I was on the wrong tab in my browser. :-(
