### ISSUE TITLE
nvim_set_hl does not work in (v0.9.4 / macOS v14.4.1)

### ISSUE THREAD

**Issue by nolleh** [neovim/neovim#29237]
### Problem

in init.lua, 
I've tried put  
```lua
vim.cmd([[
  set termguicolors
]])

vim.api.nvim_set_hl(0, "Visual", { ctermbg = 0, guifg = Black, guibg = LightGrey })
```

but when command :hi Visual,   
it doesn't changed.

if you put it as 
```lua 
vim.cmd([[
  set termguicolors
  hi Visual ctermbg = 0 guifg = Black guibg = LightGrey
]])

```
then work as expected.

### Steps to reproduce

put below code snippet as init-test.lua

```lua
vim.cmd([[
  set termguicolors
  " this works as expected
  " hi Visual ctermbg = 0 guifg = Black guibg = LightGrey
]])
" this doesn't works as expected
vim.api.nvim_set_hl(0, "Visual", { ctermbg = 0, guifg = Black, guibg = LightGrey })
print("test")
```

and run 

```sh
$ nvim --clean -u init-test.lua
```

in nvim, when `:hi Visual` shows

```
:hi visual
Visual         xxx ctermbg=0
Press ENTER or type command to continue
```

### Expected behavior

should be hi Visual as..

```
:hi Visual
Visual         xxx ctermbg=0 guifg=Black guibg=LightGrey
Press ENTER or type command to continue
```

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1700008891

### Vim (not Nvim) behaves the same?

this api exists for nvim

### Operating system/version

macOS 14.4.1

### Terminal name/version

alacritty 0.12.3 (1)

### $TERM environment variable

screen-256color

### Installation

homebrew

**Comment by clason** [comment]
Please try the latest version 0.10.0 (or a nightly).

**Comment by nolleh** [comment]
sorry for not reading doc and bother you. 
after changed the parameter map, it work fine.
thanx. :)
