### ISSUE TITLE
Missing optional for `vim.lsp.inlay_hint.is_enabled` parameter

### ISSUE THREAD

**Issue by VlaDexa** [neovim/neovim#29230]
### Problem

In the `vim.lsp.inlay_hint.is_enabled` the parameter `filter` isn't marked as being optional in the `@param` comment , but `vim.validate` validates it as being optional.

### Steps to reproduce

It's an API documentation issue

### Expected behavior

Please either mark `filter` parameter as optional or fix 'vim.validate' inside that function to error on nil.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

There is no such API in vim

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 

### $TERM environment variable

alacritty

### Installation

system package manager

**Comment by dundargoc** [comment]
Added a fix in https://github.com/neovim/neovim/pull/29229 which will be merged after a while.
