### ISSUE TITLE
glibc 2.29 not found error in v0.10.0+

### ISSUE THREAD

**Issue by fthycl** [neovim/neovim#29243]
### Problem

AppImage provided in releases gives the following error message when trying to launch on RHEL8:

`version GLIBC_2.29 not found (required by /tmp/.mount_nvim.aH706D8/usr/bin/nvim)`

AppImages from the previous versions work fine.

### Steps to reproduce

Download the nightly AppImage, and run on RHEL8 (directly, or after extracting).

### Expected behavior

The error above goes away, and nvim starts.

### Neovim version (nvim -v)

0.10.0 and 0.11.0

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

RHEL8

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

AppImage

**Comment by zeertzjq** [comment]
Search existing issues
