### ISSUE TITLE
A restored terminal buffer from a session is named "null"

### ISSUE THREAD

**Issue by BohrShaw** [neovim/neovim#2924]
Why the command(like `/bin/zsh`) to start the terminal is not remembered?

**Comment by justinmk** [comment]
Possibly related: https://github.com/neovim/neovim/issues/2861

**Comment by blanham** [comment]
Not sure if this should be separate or not, but if you rename a terminal buffer and then save and reopen a session, it tries to open a file with that name instead of the terminal command that was open.
