### ISSUE TITLE
Please bring back `diff` in nvim windows binary 

### ISSUE THREAD

**Issue by hornyjailfish** [neovim/neovim#29246]
### Problem

From 0.10 anything reliable on `diff.exe` (included in binary release before) is not working because windows doesnt have coreutils

### Expected behavior

:!diff is valid command

**Comment by lewis6991** [comment]
Nvim ships with a version of xdiff built-in so there is no reason to also include an external diff binary. We also didn't include this for any other platform so I don't see why Windows should be treated differently.

**Comment by dundargoc** [comment]
Tbh just install it? Scoop has coreutils which works as expected as an example.

**Comment by justinmk** [comment]
> so I don't see why Windows should be treated differently.

Because Windows is different. We intentionally included diff.exe and other tools (such as cat.exe) on Windows if they are used by builtin features. 

We removed diff.exe because we included xdiff, as mentioned.
