### ISSUE TITLE
Bundled parsers are not rebuilt after update

### ISSUE THREAD

**Issue by dundargoc** [neovim/neovim#29271]
### Problem

Building neovim does not rebuild the latest parser version.

### Expected behavior

Rewrite cmake parser copy code to build time and not configure time

**Comment by dundargoc** [comment]
This might not be a problem in hindsight. Idk, test it

**Comment by KorigamiK** [comment]
I've getting this error on any of the help pages.
running `:help <anything>` gives a wall of these errors that don't go away:

```lua
Error in decoration provider treesitter/highlighter.win:
Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 2:4. Invalid node type "delimiter":                                           
  (delimiter) @markup.heading.1                                                                                                                                             
   ^                                                                                                                                                                        
                                                                                                                                                                            
stack traceback:                                                                                                                                                            
        [C]: in function '_ts_parse_query'                                                                                                                                  
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'                                                                                          
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'                                                                                              
        /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'                                                                                             
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'                                                                                    
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'                                                                             
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'                                                                                    
        /usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'                                                                        
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prepare_highlight_states'                                                              
        /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:398: in functi           
```

**Comment by clason** [comment]
Yes, but how did you install Neovim? The error is not the issue here; it's expected if you don't have the correct parser installed. 

Please don't just "me too" issues; that just adds noise and doesn't help at all. Try to add _new_ information that helps tracking down the _cause_.

**Comment by KorigamiK** [comment]
> Yes, but how did you install Neovim? The error is not the issue here; it's expected if you don't have the correct parser installed. 
> 
> Please don't just "me too" issues; that just adds noise and doesn't help at all. Try to add _new_ information that helps tracking down the _cause_. 

It's the fact that I had this issue and I can't figure out what parser is broken here. I tried to write how I got the error and at least paste the full log. 
The error only occurs on help files as far as I can tell and I don't think I've installed any parser for that

**Comment by dundargoc** [comment]
I'm locking this thread. This is a glorified personal todo that is unrelated to basically any issues user have. Go create another issue if you need.

**Comment by beardwin** [comment]
> Yes, but how did you install Neovim? The error is not the issue here; it's expected if you don't have the correct parser installed.

I'm new to neovim, so don't know a whole lot. I started receiving this error after I upgraded via homebrew from 0.9.5 -> 0.10.0. Not sure what a "parser" is in this context, so not sure if this helps at all. 

Cheers!

**Comment by gmmyung** [comment]
> Please don't just "me too" issues; that just adds noise and doesn't help at all. Try to add new information that helps tracking down the cause.

Well, another "me too" comment here :(
The thing is that this only happens with nvim-treesitter installed.

**Comment by beardwin** [comment]
@gmmyung - that fixed it. Thanks for the hot tip.

**Comment by dundargoc** [comment]
I can't really recreate this problem. If it happens again I can reopen or create a new one in the future.
