### ISSUE TITLE
Online doc strange highlights and offset display

### ISSUE THREAD

**Issue by NourNuxeo** [neovim/neovim#29277]
### Problem

Online doc pages have this strange highlight / offset happening. Noticed today at 9:30 CEST.
Already cached pages from yesterday were fine.
Seen in Chrome & FF
<img width="813" alt="image" src="https://github.com/neovim/neovim/assets/47983949/813ecaed-c2ce-46a2-b7ca-600b37e8b391">

### Steps to reproduce

Go to a doc page, like https://neovim.io/doc/user/usr_21.html#21.4

### Expected behavior

Beautiful display

### Neovim version (nvim -v)

37bf4c572a8fa20dc4a8433524ecc8c8d68fe53c

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

macOS 14.5

### Terminal name/version

not relevant

### $TERM environment variable

not relevant

### Installation

Juste the online website

**Comment by clason** [comment]
Guess the `gen_help_html` script needs an update to adjust to the vimdoc parser changes @justinmk

**Comment by justinmk** [comment]
Working on this
