### ISSUE TITLE
Don't send "no information available" on `vim.lsp.buf.hover` if at least one attached server has information

### ISSUE THREAD

**Issue by mawkler** [neovim/neovim#29282]
### Problem

Currently, if you have multiple language servers attached to a buffer and at least one of them responds with no information on `vim.lsp.buf.hover` the message "no information available" is sent.

### Expected behavior

The message "no information available" is only sent if **none** of the servers responded with hover information.

**Comment by crwebb85** [comment]
I was looking at the hover code the other day, and it appeared to me it would send the request to both, and based on the look, I expected the last response to win

**Comment by glepnir** [comment]
set config.silent  to true.

**Comment by mawkler** [comment]
@glepnir Do you mean that I should set `client.config.silent = true` for each LSP client? Or is there a built-in function to easily set it for every client like `:help vim.diagnostic.config()` for diagnostics? 🙂

**Comment by glepnir** [comment]
I remember there a  pr to set https://github.com/neovim/neovim/pull/22763 .seems like not doucmented.
