### ISSUE TITLE
Can't run tests on OpenBSD

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#2930]
If it means anything, this has been happening as long as I can remember (2-3 months), and this is on OpenBSD current. This log shows what happens when I run `gmake test`:
https://gist.github.com/Pyrohh/5d39b5a0eaf1ffa50cbf

Is there any sort of debug mode for busted or Lua which would help? I'd love to provide more information, I'm just not sure what is needed.

cc @equalsraf, in case you're experiencing this too.

**Comment by justinmk** [comment]
> error loading module 'nvim.loop' from file '/home/michael/src/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so':
>	Cannot load specified object

Maybe this thread could help: http://lua-users.org/lists/lua-l/2013-05/msg00234.html

What is the output of `ldd loop.so` ?

**Comment by Pyrohh** [comment]
> What is the output of ldd loop.so ?

```
loop.so:
	Start            End              Type Open Ref GrpRef Name
	00001c27a20d0000 00001c27a24ee000 dlib 1    0   0      /home/michael/src/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so
	00001c279f79f000 00001c279fbb1000 rlib 0    2   0      /usr/lib/libpthread.so.19.0
```

Not sure if it's important, but `Start` and `End` are different for each call of ldd; something to do with ASLR I suppose.

I tried `export LD_DEBUG=1 && gmake test`, but wasn't able to gather much from the output.
Here's the log for anyone who might find it useful: https://gist.github.com/Pyrohh/a66fd218e3d1000d4ed3

**Comment by justinmk** [comment]
> I tried export LD_DEBUG=1 && gmake test, but wasn't able to gather much from the output.

Can you attach a debugger to the lua process and add breakpoints to [loop.c](https://github.com/neovim/lua-client/blob/master/nvim/loop.c)?

**Comment by equalsraf** [comment]
With LD_DEBUG=1 && luajit -e "require('nvim.loop')"

```
dlopen: loading: /home/raf/Code/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so
 flags /home/raf/Code/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so = 0x0
head /home/raf/Code/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so
obj /home/raf/Code/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so has /home/raf/Code
/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so as head
linking /home/raf/Code/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so as dlopen()ed
head [/home/raf/Code/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so]
examining: '/home/raf/Code/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so'
loading: libpthread.so.19.0 required by /home/raf/Code/neovim/.deps/usr/lib/lua
/5.1/nvim/loop.so
 flags /usr/lib/libpthread.so.19.0 = 0x68
dlopen: failed to open libpthread.so.19.0

```unload_shlib called on /home/raf/Code/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so
unload_shlib unloading on /home/raf/Code/neovim/.deps/usr/lib/lua/5.1/nvim/loop
.so
dlopen: /home/raf/Code/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so: done (failed)
.
/home/raf/Code/neovim/.deps/usr/bin/luajit: error loading module 'nvim.loop' fr
om file '/home/raf/Code/neovim/.deps/usr/lib/lua/5.1/nvim/loop.so':
        Cannot load specified object
stack traceback:
        [C]: at 0x03f41083c430
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x03f4108068c0
```

Maybe linking with -pthread would help here - but I have no been able to change the luarocks recipe to do this.

**Comment by equalsraf** [comment]
I've been pushing some OpenBSD patches into https://github.com/luvit/luv/pull/232 setting LD_PRELOAD=/usr/lib/libpthread.so might help with this issue.

**Comment by equalsraf** [comment]
The following diff works around the issue.

```diff
diff --git a/third-party/cmake/BuildLuajit.cmake b/third-party/cmake/BuildLuajit.cmake
index c8eee28..cf5ed40 100644
--- a/third-party/cmake/BuildLuajit.cmake
+++ b/third-party/cmake/BuildLuajit.cmake
@@ -39,6 +39,7 @@ set(INSTALLCMD_UNIX ${MAKE_PRG} CFLAGS=-fPIC
                                 CFLAGS+=-DLUAJIT_DISABLE_JIT
                                 CFLAGS+=-DLUA_USE_APICHECK
                                 CFLAGS+=-DLUA_USE_ASSERT
+                                LDFLAGS+=-pthread
                                 CCDEBUG+=-g
                                 Q=
                                 install)

```

**Comment by justinmk** [comment]
We worked around this by disabling jemalloc for openbsd. https://github.com/neovim/neovim/pull/5318
