### ISSUE TITLE
Error opening Astro files from tree

### ISSUE THREAD

**Issue by juanjomarcal** [neovim/neovim#29300]
### Problem

```
Error detected while processing function <SNR>21_NetrwBrowseChgDir[194]..<SNR>21_NetrwEditFile[7]..BufReadPost Autocommands for "*":
Error executing lua callback: ...rew/Cellar/neovim/0.10.0/share/nvim/runtime/filetype.lua:35: Error executing lua: ...rew/Cellar/neovim/0.10.0/share/nvim/runtime/filetype.lua:36: function <SNR>21_NetrwBrowseChgDir[194]..<SNR>21_NetrwE
ditFile[7]..BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..script /opt/homebrew/Cellar/neovim/0.10.0/share/nvim/runtime/ftplugin/astro.vim[163]..function <SNR>24_CollectPathsFromConf
ig, line 11: Vim(let):E474: Trailing comma: }   } }
stack traceback:
        [C]: in function 'nvim_cmd'
        ...rew/Cellar/neovim/0.10.0/share/nvim/runtime/filetype.lua:36: in function <...rew/Cellar/neovim/0.10.0/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        ...rew/Cellar/neovim/0.10.0/share/nvim/runtime/filetype.lua:35: in function <...rew/Cellar/neovim/0.10.0/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...rew/Cellar/neovim/0.10.0/share/nvim/runtime/filetype.lua:35: in function <...rew/Cellar/neovim/0.10.0/share/nvim/runtime/filetype.lua:10>
```

### Steps to reproduce

Fresh OS install.
Tried nvim installed from brew and downloaded binary from github.

### Expected behavior

Working properly in other projects, but not in Astro projects

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no, 9.0.2142

### Operating system/version

macOS Sonoma 14.5

### Terminal name/version

warp, v0.2024.06.04.08.02.stable_04

### $TERM environment variable

xterm-256color

### Installation

homebrew and binary download

**Comment by zeertzjq** [comment]
What did you do after installing Nvim?

**Comment by K4YN5** [comment]
Same error here, previous version worked flawlessly.

Steps to reproduce are as simple as they seam:
- Install neovim 10.0
- Open an Astro js file

Then the error appears.

**Comment by zeertzjq** [comment]
Hmm, I think this happens because your tsconfig.json or jsconfig.json is not valid JSON: it contains trailing commas.

**Comment by K4YN5** [comment]
Yeah, found it, thank you very much. Now it works like before.

However, I don't understand how VS Code did not mark it as an error and Neovim didn't either until now.

**Comment by juanjomarcal** [comment]
@zeertzjq thank you! Was the jsconfig.

Pretty weird error. Says nothing about the file with the error, just that thing about trailing commas. Indeed I reported this as a 
bug, because I thought it was a trailing comma in some of this lua files.

Anyway, thank you for your time.
