### ISSUE TITLE
nvim -S doesn't load Session.vim (generated by Obsession)

### ISSUE THREAD

**Issue by sunaku** [neovim/neovim#2931]
Hello,

I use nvim from the daily builds for Ubuntu.  Since a few weeks ago, `nvim -S` has stopped loading `Session.vim` files generated by [the Obsession plugin](https://github.com/tpope/vim-obsession).  :scream:  Here is how to reproduce this issue:

1. Run `nvim -c Obsession`
2. Open a file, split the window, open another file, etc.
3. Run `:qa` inside nvim to auto-save session and quit.
4. Observe that there is now a `Session.vim` file in the current folder.
5. Run `nvim -S`
6. Observe that the session was not restored.

Repeat this process with traditional vim :older_man: (s/nvim/vim/g above) and observe that the session is _indeed_ restored correctly :sparkling_heart: in step 6.

Thanks for your consideration.

**Comment by justinmk** [comment]
Works for me with:

- NVIM 0.0.0-alpha+201506222256 20a57c497b55bb3632f0d4bcd76c18628cfa5f43
- NVIM 0.0.0-alpha+201506301836 bfadf5a28b550bf99101c17244d5ea1b926e40c3

Steps taken:

```
nvim -u NONE -c ':set runtimepath+=~/.vim/bundle/vim-obsession/' -c ':runtime plugin/obsession.vim' -c Obsession
<open files and splits>
:qa
nvim -u NONE -S
```

Can you try with `nvim -u NONE` as above?

We made a change to `'sessionoptions'` default: https://github.com/neovim/neovim/pull/2871 but that should not cause the issue reported here.

**Comment by fmoralesc** [comment]
> We made a change to 'sessionoptions' default: #2871 but that should not cause the issue reported here.

Indeed. vim-obsession also removes `options` from `sessionoptions`.

**Comment by sunaku** [comment]
You're right, it works fine with `nvim -u NONE` :facepunch: so the problem is on my end. :disappointed_relieved:  Sorry for the noise. :bow:
