### ISSUE TITLE
can't detect python provider in Windows 10

### ISSUE THREAD

**Issue by JDCerberus** [neovim/neovim#29336]
### Problem

Describe the bug
I am not able to get neovim to detect python 3 on Windows 10 pro. I made several attempts.

installed python 3.12 from the official site (before tried several times with 3.10, 3.11. 3.12 from the official site, winget and chocolatey)
installed neovim 0.10 via winget 
followed the guide https://neovim.io/doc/user/provider.html . I am sure I used correct path, keys, etc.
nvim has never detected a python provider able to import neovim (tested within several shells)

Every time I ran :checkhealth and got this:
```
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set. Searching for python in the environment.
- Executable: C:\Users\ASUS\AppData\Local\Programs\Python\Python312\python.EXE
- Python version: 3.12.4
- pynvim version: 0.5.0
- WARNING Could not contact PyPI to get latest version.
- ERROR HTTP request failed: error: curl error with https://pypi.python.org/pypi/pynvim/json: 35

Python virtualenv ~
- OK no $VIRTUAL_ENV
```
NOTE: the Json problem gives 404 error 
Later I tried to config with the path but nvim can't detect the executable : 
```
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- Using: g:python3_host_prog = "C:\Users\ASUS\AppData\Local\Programs\Python\Python312\"
- Executable: Not found
- ERROR Detected pip upgrade failure: Python executable can import "pynvim" but not "neovim": 
  - ADVICE:
    - Use that Python version to reinstall "pynvim" and optionally "neovim".
    -  -m pip uninstall pynvim neovim
    -  -m pip install pynvim
    -  -m pip install neovim  # only if needed by third-party software
``` 

### Steps to reproduce

- install neovim with winget
- install python with different way ( winget, chocolatey, official site intaller)
- use CMD,  powershell
- checkhealth

### Expected behavior

I would expect neovim to detect the provider 

### Neovim version (nvim -v)

0.10

### Vim (not Nvim) behaves the same?

not installed

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal, CMD, powershell

### $TERM environment variable

None

### Installation

Winget, Chocolatey, Installler

**Comment by justinmk** [comment]
> ERROR HTTP request failed: error: curl error with https://pypi.python.org/pypi/pynvim/json: 35

Why is that HTTP request failing? https://github.com/neovim/neovim/blob/20a7eebec086129e605041d32916f36df50890de/runtime/lua/vim/provider/health.lua#L439

Does `curl https://pypi.python.org/pypi/pynvim/json` work for you?

> Using: g:python3_host_prog = "C:\Users\ASUS\AppData\Local\Programs\Python\Python312\"

`g:python3_host_prog` must point to the exe, not the directory.

**Comment by JDCerberus** [comment]
> ok so now I set in init.lua ( let g:python3_host_prog = 'C:\Users\ASUS\AppData\Local\Programs\Python\Python312\python.exe and python.EXE' in both cases appeared this:
```
- g:python3_host_prog is not set. Searching for python in the environment.
- Executable: C:\Users\ASUS\AppData\Local\Programs\Python\Python312\python.EXE
``` 
as for   ```curl https://pypi.python.org/pypi/pynvim/json``` it gives me:
 
```
 curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
```

**Comment by JDCerberus** [comment]
> > ok so now I set in init.lua ( let g:python3_host_prog = 'C:\Users\ASUS\AppData\Local\Programs\Python\Python312\python.exe and python.EXE' in both cases appeared this:
> 
> ```
> - g:python3_host_prog is not set. Searching for python in the environment.
> - Executable: C:\Users\ASUS\AppData\Local\Programs\Python\Python312\python.EXE
> ```
> 
> as for `curl https://pypi.python.org/pypi/pynvim/json` it gives me:
> 
> ```
>  curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
> ```

So this is a little after, I looked to understand the problem and I found that the connection may be due problems with  ```network restrictions or firewalls``` , then I thought **_Antivirus_** I disabled it,  and no more HTTP.

But the first problem still exist

**Comment by justinmk** [comment]
> here I'm using vim.g.python3_host_prog and formatted the direction without `\`

wtf does this mean?

I'm guessing that your config has something like this:

    vim.g.python3_host_prog = "C:\Users\ASUS\AppData\Local\Programs\Python\Python312\"

1. on Windows you don't need to use `\` slashes. `/` slashes work just fine, except for some cmd.exe commands.
   ```
   vim.g.python3_host_prog = "C:/Users/ASUS/AppData/Local/Programs/Python/Python312/"
   ```
2. if you really want to use `\` slashes you need to escape them:
   ```
   vim.g.python3_host_prog = "C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python312\\"
   ```

**Comment by JDCerberus** [comment]
Hi, that resolved the problem, I'm sorry for the inconvenience, this is the first time I use github and lot of  similar problems had ```\``` so I didn't know.
Sorry again if I made you lost time and thanks again.
