### ISSUE TITLE
Neovim v0.10.0 removes trailing whitespace on save

### ISSUE THREAD

**Issue by vito-c** [neovim/neovim#29334]
### Problem

Neovim is removing whitespace automatically when saving a file

### Steps to reproduce
```
nvim --clean 
:e foo
ihello there                     <ESC>
:w
```
### Expected behavior

Text file should be written with the contents:
"`hello there                     `"

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux

### Terminal name/version

iterm,

### $TERM environment variable

xterm-256color

### Installation

Arch User Repo

**Comment by clason** [comment]
Can't reproduce, so this must be some system-wide default.

**Comment by vito-c** [comment]
no this is on an empty directory

**Comment by gpanders** [comment]
Then you likely have an `.editorconfig` in a parent directory.

**Comment by vito-c** [comment]
Ah yah there was one in the parent dir. Thank you

**Comment by gegoune** [comment]
Would adding  health check for `editorconfig` be an option at all? It could print what settings were set and what `.editorconfig` file from.

**Comment by gpanders** [comment]
Please read `:h editorconfig`. You can disable Neovim's EditorConfig integration by setting the `g:editorconfig` global variable.

**Comment by eth3lbert** [comment]
@gpanders I think this is still an issue if you just want to temporarily disable `editorconfig` (via `:lua vim.b.editorconfig = false` or similar). The `autocmd` is already created.

**Comment by zeertzjq** [comment]
> To disable it, add to your config

**Comment by eth3lbert** [comment]
> > To disable it, add to your config

Thanks, and that's indeed a valid choice! However, since changing the config isn't a viable option for some reason, I think I'll temporarily disable it by using `:lua require('editorconfig').properties.trim_trailing_whitespace(0, 'false')` instead.
