### ISSUE TITLE
Any key return messy codes

### ISSUE THREAD

**Issue by LSTM-Kirigaya** [neovim/neovim#29353]
### Problem

When I code for a while in neovim, any key enter will return messy codes like `^?`, `^[OD`, `^[OC` in the editor 🤔, when I enter `→`, effect is like this

![image](https://github.com/neovim/neovim/assets/59416203/baf92df5-1a7a-4da6-95f4-96588b405bff)

### Steps to reproduce

write code with neovim for about 30 minutes.

### Expected behavior

`<BS>`, `<C>` interpreted as correct key map in editor.

### Neovim version (nvim -v)

0.11.0-dev commit 199d852d9f8584217be38efb56b725aa3db62931

### Vim (not Nvim) behaves the same?

I don't know

### Operating system/version

Debian GNU/Linux 12

### Terminal name/version

zsh 5.9

### $TERM environment variable

xterm-256color

### Installation

compile and install from source 199d852d9f8584217be38efb56b725aa3db62931

**Comment by justinmk** [comment]
That looks like terminal code sequences. Perhaps Nvim is stuck in bracketed paste mode, or your terminal is stuck in some sort of mode. 

Without minimal steps it's hard to say, so this will be closed if that is not provided.
