### ISSUE TITLE
Weird tab chars when setting `listchars` only to `trail:.`

### ISSUE THREAD

**Issue by fszymanski** [neovim/neovim#29359]
### Problem

![bad](https://github.com/neovim/neovim/assets/25827968/72ba55c2-60f0-4d50-b7d5-c2d9d118c4f8)

### Steps to reproduce

nvim --clean
:set list listchars=trail:.
:edit main.go

### Expected behavior

![good](https://github.com/neovim/neovim/assets/25827968/780b97df-312a-4e2e-b1dd-5a929650cb23)

### Neovim version (nvim -v)

NVIM v0.11.0-dev

### Vim (not Nvim) behaves the same?

I don't know

### Operating system/version

Ubuntu 24.04

### Terminal name/version

kitty 0.32.2

### $TERM environment variable

xterm-kitty

### Installation

Ubuntu PPA (Neovim Unstable)

**Comment by zeertzjq** [comment]
This is working as intended. It seems that this used to be documented, but the documentation has been removed.

**Comment by fszymanski** [comment]
Oh I see, thank you @zeertzjq
