### ISSUE TITLE
neovim-qt shows "no notification handler registered" warnings (since Nvim 0.11)

### ISSUE THREAD

**Issue by eyalk11** [neovim/neovim#29363]
### Problem

Those come every two seconds from the moment I open nvim . It comes in two flavors  Dir and Gui  errors. 

Everything (i.e. the same profile)  works well in nvim 0.10 . 

```

01:28:04 msg_show Error detected while processing VimEnter Autocommands for "*"..function LoadBaseInserts[35]..provider#python3#Call:
01:28:04 msg_show line    1:
01:28:04 msg_show E5108: Error executing lua Vim:no notification handler registered for "Dir"
stack traceback:
	[C]: at 0x7ff7ea9d6840
   Error  01:28:04 msg_show.emsg no notification handler registered for "Gui"
Run ":verbose version" for more info
01:28:20 msg_show   NoiceHistory "[Scratch]" 11 lines --9%--
   Error  01:28:20 msg_show.emsg   NoiceHistory no notification handler registered for "Dir"
01:28:20 msg_show   NoiceHistory no notification handler registered for "Dir"
01:28:20 msg_show   NoiceHistory no notification handler registered for "Gui"
01:28:20 msg_show "[Scratch]" 11 lines --9%--
   Error  01:28:21 msg_show.emsg no notification handler registered for "Gui"
01:28:21 msg_show "[Scratch]" 11 lines --18%--
   Error  01:28:21 msg_show.emsg no notification handler registered for "Gui"


It is really not debugable this way. 


01:28:06 msg_show   version NVIM v0.11.0-dev-250+g61aabe073
01:28:06 msg_show   version Build type: RelWithDebInfo
01:28:06 msg_show   version LuaJIT 2.1.1716656478
```

### Steps to reproduce

my neovim profile 

### Expected behavior

Works

### Neovim version (nvim -v)

NVIM v0.11.0-dev-250+g61aabe073

### Vim (not Nvim) behaves the same?

no idea

### Operating system/version

Windows

### Terminal name/version

nvim-qt

### $TERM environment variable

unk

### Installation

nightly

**Comment by eyalk11** [comment]
https://github.com/neovim/neovim/issues/8053
I tried UpdateRemotePlugins

**Comment by eyalk11** [comment]
After removing `neovim-gui-shim ` it seems to be solved.

**Comment by justinmk** [comment]
This is because something is broadcasting an event via `rpcnotify(0, ...)` and neovim-qt is showing this warning. https://github.com/equalsraf/neovim-qt/issues/1112

Nvim-qt should just not show that warning.

For reference, this was indirectly caused by https://github.com/neovim/neovim/pull/28487 . I expected some issues like this, but so far only nvim-qt seems to be doing this kind of thing (complaining when it sees an unknown event). So I'm hoping that nvim-qt will change its behavior to quietly ignore unknown events.

**Comment by equalsraf** [comment]
The notifications come from nvim-qt but the messages themselves come from pynvim

https://github.com/neovim/pynvim/blob/f9e56f8ef2a0d93da4ad1c64e82066be77ecde64/neovim/plugin/host.py#L110

You can verify this by disabling all python plugins.

FWIW I'm planning to change the vimscript in nvim-qt to stop using `rpcnotify(0`.

**Comment by justinmk** [comment]
Fixed https://github.com/equalsraf/neovim-qt/pull/1121
