### ISSUE TITLE
Percent sign (%) for jumping to matching parenthesis doesn't regard comments and work properly 

### ISSUE THREAD

**Issue by mohammadfs243** [neovim/neovim#29369]
### Problem

Hi there,
I have a fresh installment of _NeoVim_ and _kickstart_ and expect to use `%` to jump between matching pairs of parentheses and brackets, but I opened the `init.lua` file and it's not working.

### Steps to reproduce

Steps to reproduce:
  1. Open `init.lua` config file
  2. wait for `LSP` and other stuffs to load
  3. Jump around end of the file (currently line 909)
  4. Put the cursor on top of the closing `)`
  5. Press `%`

Even trying the other way around doesn't work properly; To check:
  1. Jump to `lazy` setup line (Currently 227)
  2. Put the cursor on opening `(` after setup
  3. Press `%`

It jumps to a commented line (803) `va)`!

### Expected behavior

I expect it to regard commented lines according to language and _LSP_ but it does not.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

yes, 9.0.749

### Operating system/version

Ubuntu 20.04 LTS

### Terminal name/version

gnome-terminal-server

### $TERM environment variable

xterm-256color

### Installation

Ubuntu Snap

**Comment by clason** [comment]
This is just a limitation of `matchit; it's basic algorithm cannot handle parens spanning too many lines. There's extended support using legacy regex syntax, but that is disabled when treesitter highlighting is enabled (by default for Lua).

Either 
1. set `:syntax on` or
2. install a more full-featured matchit plugin with treesitter support (such as `matchup`).
