### ISSUE TITLE
nvim ... --remote-expr execute("tabs") does not work anymore

### ISSUE THREAD

**Issue by nnako** [neovim/neovim#29376]
### Problem

I am using e.g. the following terminal command line (on Windows 10):

```batch
nvim --headless --server \\.\pipe\nvim.1973.0 --remote-expr execute("tabs")
```

to **print out the list of current tabs** within a running neovim server instance which I started using this command:

```
nvim --listen \\.\pipe\nvim.1973.0
```

Until  `neovim v0.9.1` this worked great. But as I upgraded to `v0.10.0` and even then to `v0.11.0` this causes the following error printed to my terminal:

```
Error executing lua: Vim:E121: Undefined variable: tabs
stack traceback:
        [C]: in function 'rpcrequest'
        vim/_editor.lua:1008: in function <vim/_editor.lua:965>
```

The `remote-send` command still works, but the `remote-expr` in combination with the `execute` function does not in the expected way.

**What did change concerning the remote command specification for `--remote-expr execute(...)` to be used? how can I retrieve the return from a nvim server within a calling terminal window?**

### Steps to reproduce

nvim --listen \\.\pipe\nvim.1973.0
nvim --headless --server \\.\pipe\nvim.1973.0 --remote-expr execute("tabs")

### Expected behavior

print the current tab names and further metadata to the terminal window

### Neovim version (nvim -v)

NVIM v0.11.0-dev-267+g20a7eebec

### Vim (not Nvim) behaves the same?

?

### Operating system/version

Windows 10

### Terminal name/version

command.com

### $TERM environment variable

?

### Installation

MSI installer

**Comment by zeertzjq** [comment]
Does it work if you use this:
```
nvim --headless --server \\.\pipe\nvim.1973.0 --remote-expr "execute('tabs')"
```

**Comment by luozhiya** [comment]
> nvim --headless --server \\.\pipe\nvim.1973.0 --remote-expr "execute('tabs')"

This command works, the output is as follows
```


Tab page 1
>   [No Name]
```

**Comment by nnako** [comment]
hi @zeertzjq , thanks. That works.

How come? Did the format change between `nvim v0.9.1` and later versions in this respect? So, the initial implementation was faulty?

**Comment by nnako** [comment]
could somebody give me a link into the code base where I could roughly start studying the respective implementation / implementation changes?

**Comment by zeertzjq** [comment]
IIUC there hasn't been any implementation changes regarding this, so I don't know why behavior changed.

**Comment by nnako** [comment]
strange, as I had to change API access format within my scripts as well as output evaluation functionality...

Anyway, thank you for your support.
