### ISSUE TITLE
When grepprg is set, grep results are not displayed in quickfix window

### ISSUE THREAD

**Issue by yamam** [neovim/neovim#29408]
### Problem

Even if it is the default value, if grepprg is set, the results of grep are not displayed in quickfix window.

### Steps to reproduce

nvim --clean
`:se gp&`
`aa<ESC>`
`:w tmp.txt`
`:gr a %`
`:cw`

### Expected behavior

quickfix window appears.

### Neovim version (nvim -v)

NVIM v0.10.1-dev-54+g3b8d0721a~/

### Vim (not Nvim) behaves the same?

no, vim 9.1

### Operating system/version

Ubuntu 24.04

### Terminal name/version

GNOME Terminal 3.52.0 using VTE 0.76.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
You need to also `:set grepformat&`
