### ISSUE TITLE
Contradiction in helpfiles :help design-not

### ISSUE THREAD

**Issue by Darksonn** [neovim/neovim#2940]
In `:help design-not`, the following phrase is found.

> You will not be able to run a shell inside Vim

This is a contradiction since we can do just that with `:term`. It even works really well. I propose we change the help file.

**Comment by justinmk** [comment]
It's in one of my branches.

**Comment by Grimy** [comment]
Actually, most of this file is outdated. I think it calls for a complete rewrite.

**Comment by justinmk** [comment]
Yep, I'm working on it.
