### ISSUE TITLE
Cannot paste from '+' register when using unnammedplus and a visual selection

### ISSUE THREAD

**Issue by brettanomyces** [neovim/neovim#2942]
vim -u NONE
    :set clipboard=unnamedplus
    <insert some text>
    <shift-v>
    "+p

Expected behavior: selected text is overwritten with the text from the clipboard.
Actual behavior: selected text is copied to the clipboard, and then pasted over itself.

Note that vim's behavior is as expected, this is only an issue in Neovim

Issue does not occur when `clipboard=` or when `clipboard=unnamed`

**Comment by bfredl** [comment]
opened PR #2945

**Comment by justinmk** [comment]
LGTM, thanks!

**Comment by bfredl** [comment]
Should be fixed on master, reopen if still problem.
