### ISSUE TITLE
'termsync' : cursor rendering issue on zellij with floating window

### ISSUE THREAD

**Issue by pierregoutheraud** [neovim/neovim#29427]
### Problem

Hello,

I started using `zellij` instead of `tmux` recently and I noticed an annoying bug with `zellij`, the cursor flickering/incorrectly rendering when using any kind of floating window: there is sometimes 1 frame where the cursor is rendered somewhere else in the terminal or completely gone while the window is being rendered.

I posted a comment on zellij github (https://github.com/zellij-org/zellij/issues/3208#issuecomment-2176070994) and the main contributor/creator is telling me that "This issue is 99% a misimplementation of CSI 2026 (synchronized renders) by ... nvim".

Is this the case?

https://github.com/neovim/neovim/assets/1341781/1eaf7829-cf7a-40fa-8914-f0b6a1f7e8a8

### Steps to reproduce

1. `zellij`
2. `nvim --clean -u minimal.lua`
3. Then try spamming the `f` key, you should see the cursor blinking.

I am using `nvim 0.10.0` and `zellij 0.40.1`.
This is reproducible on `Kitty 0.35.1`, `Alacritty 0.13.2` and `Wezterm`.

`minimal.lua`:
```lua
function open_floating_window()
  -- Get the current buffer handle
  local buf = vim.api.nvim_create_buf(false, true)

  -- Define the window options
  local opts = {
    relative = "editor",
    width = math.floor(vim.o.columns * 0.8),
    height = math.floor(vim.o.lines * 0.8),
    col = math.floor(vim.o.columns * 0.1),
    row = math.floor(vim.o.lines * 0.1),
    anchor = "NW",
    style = "minimal",
  }
  
  -- Create the window
  vim.api.nvim_open_win(buf, true, opts)
end

-- Open the window with "f" key in normal mode
vim.api.nvim_set_keymap(
  "n",
  "f",
  ":lua open_floating_window()<CR>",
  { noremap = true, silent = true }
)
```

### Expected behavior

On zellij, the cursor should not blink and its position should always be at the start of the floating window.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

Could not test floating window in vim

### Operating system/version

macOS 14.3.1

### Terminal name/version

`Kitty 0.35.1`, `Alacritty 0.13.2`

### $TERM environment variable

xterm-kitty

### Installation

homebrew

**Comment by justinmk** [comment]
> "This issue is 99% a misimplementation of CSI 2026 (synchronized renders) by ... nvim".

Does the issue occur if you disable 'termsync'?

For reference:

- https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036
- 'termsync' implemented in https://github.com/neovim/neovim/commit/c651fb30427a3c645b4b1bd8a9b7e767af51e014

**Comment by pierregoutheraud** [comment]
@justinmk Yes, the issue still occurs but is less obvious as the cursor only flickers but stays at the same position.
With tmux or without multiplexer it does not blink/flickers.

https://github.com/neovim/neovim/assets/1341781/36bd390b-43a2-4fbd-94ae-3a2c419153e8

This doesn't sound like a huge deal but it becomes quite annoying when you have a bunch of plugins, opening a bunch of windows as you are typing (For example autocompletion windows etc.).

**Comment by gpanders** [comment]
> I posted a comment on zellij github ([zellij-org/zellij#3208 (comment)](https://github.com/zellij-org/zellij/issues/3208#issuecomment-2176070994)) and the main contributor/creator is telling me that "This issue is 99% a misimplementation of CSI 2026 (synchronized renders) by ... nvim".

From your linked issue:

>Hey, for the record: I looked at the dump and the CSI 2026 appears at the beginning and end properly (this is a dump of the whole terminal state, not just one frame - indeed the CSI 2026 serves as the definition of the frame start and end).

**Comment by pierregoutheraud** [comment]
@gpanders I was referring to one of his previous comment:

```Thanks to everyone for pointing out their reproductions and experiences here, but at this point I don't think this adds anything to the discussion. This issue is 99% a misimplementation of CSI 2026 (synchronized renders) by either noice or nvim (as demonstrated by shutting them down mitigating this issue).```

Are you by any chance reproducing this weird behaviour?

**Comment by gpanders** [comment]
> @gpanders I was referring to one of his previous comment

Yes, but I was pointing out that later in the same thread the Zellij maintainer seems to have absolved Neovim by pointing out that our implementation is correct.

**Comment by gpanders** [comment]
Resolved in Zellij https://github.com/zellij-org/zellij/issues/3208#issuecomment-2182554099
