### ISSUE TITLE
lsp.util.apply_workspace_edit should restrict file manipulations according to client.workspace_folders

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#29424]
### Problem

firstly i'm sorry, it's just my imagination. language servers could be malicious, applying [change.kind={create,delete}](https://github.com/neovim/neovim/blob/release-0.10/runtime/lua/vim/lsp/util.lua#L820) without any checking could cause security issues, for instance, `rm -rf $HOME`.

### Steps to reproduce using "nvim -u minimal_init.lua"

[the implementation of lsp.util.apply_workspace_edit](https://github.com/neovim/neovim/blob/release-0.10/runtime/lua/vim/lsp/util.lua#L819)

### Expected behavior

IMHO, any changes in a workspace_edit response should only happen under the client.workspace_folders, maybe it's worth to ask user's confirmation or log or idk (sometime client.workspace_folders could be nil).

### Neovim version (nvim -v)

nvim 0.10

### Language server name/version

pyright

### Operating system/version

archlinux

**Comment by mfussenegger** [comment]
If the language server is malicious, what's preventing it from deleting your home directory directly? There's no need for it to go through the client to wreck havoc
