### ISSUE TITLE
filetype.lua scripts.vim is sourced  before the scripts in the ftdetect directory

### ISSUE THREAD

**Issue by rphodges** [neovim/neovim#29444]
### Problem

While comparing the filetype.vim script with filetype.lua script I noticed that filetype.vim sources ftdetect scripts at the very end of the file after the scripts.vim files are sourced.

The reference manual does advertise the ftdetect scripts as being able to overrule any previously detected filetypes.  Thus I think filetype.lua should keep the same order by sourcing the ftdetect scripts after the scripts.vim files.

Lastly, the ftdetect is executed in this if conditional:

```lua
if not vim.g.did_load_ftdetect then
  vim.cmd([[
  augroup filetypedetect
  runtime! ftdetect/*.{vim,lua}
  augroup END
  ]])
end
```
vim.g.did_load_ftdetect is never set to 1.  I believe the variable vim.g.did_load_ftdetect was used during a time when both filetype.lua and filetype.vim were present and the conditional prevented filetype.vim from sourcing the ftdetect scripts a second time.  Now that filetype.vim has been removed, there's no need for the conditional.   

### Steps to reproduce

Implement filetype detection logic for an arbitrary file in a scripts.vim file in the runtime path.
Put conflicting logic for the same file in a ftdetect file in the runtime path.  Ensure it sets the filetype in a way that it can overrule the filetype set in the scripts.vim file.

### Expected behavior

The logic in the ftdetect script should take precedence and overrule the filetype set in the scripts.vim file.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

**Comment by zeertzjq** [comment]
> While comparing the filetype.vim script with filetype.lua script I noticed that filetype.vim sources ftdetect scripts at the very end of the file after the scripts.vim files are sourced.

I don't think this is correct. `ftdetect/*` is sourced directly in `filetype.lua`, while `scripts.vim` is sourced in autocommands.

**Comment by rphodges** [comment]
> I don't think this is correct. `ftdetect/*` is sourced directly in `filetype.lua`, while `scripts.vim` is sourced in autocommands.

I was little bit loose with my terminology. If I'm reading the code directly there's still a change in behavior.   In most cases it may not matter.  The autocmd that sources the scripts.vim file only does so if did_filetype() returns false.  That being the case, the code inside a scripts.vim will probably never overrule a filetype detection done by autocmds established by ftdetect scripts.  However, there may be other side effects.

In Vim, you can have a situation where the autocmd for scripts.vim fires.  Then regardless of whether scripts.vim detects a filetype, the autocmds setup by ftdetect scripts are fired.

However in Neovim, the autocommands for the ftdetect  scripts are fired first.  If they detect a filetype, then the code in scripts.vim is never fired.  On the other hand, If the code in the scripts.vim files is executed, because the ftdetect scripts don't set a filetype, then it may overrule  the decision by the ftdetect scripts. 

In any case,  if the ftdetect scripts are supposed to have the final decision, it makes a lot of sense for that code to be executed at the very end of filetype.lua so there's no confusion about what can override what.
