### ISSUE TITLE
calling user commands with `'<,'>` range will change cursor to line1, 0

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#29448]
### Problem

i'm seeing no mention about that behavior in documents, and no user-land functionality relying on it. but this behavior make it impossible to know what the original cursor is just before calling an usercmd, so i think it's a bug.

the reason i need the original cursor in an usercmd is i want to open a floating window based on the cursor.
the workaround i'm currently using is binding the callback to a keymap rhs instead, but personally i prefer to use an usercmd with meaningful name rather than a lhs which is hard to remember relatively.

### Steps to reproduce

* test.lua
```
--[[
  2
  3
  4
  5
  6
  7
  8
  9
  10
]]

local api = vim.api

vim.go.showmode = false

api.nvim_create_user_command("Foo", function(args)
  local cursor = api.nvim_win_get_cursor(0)
  print(string.format("cursor=%d,%d, line1=%d, line2=%d, range=%s", cursor[1], cursor[2], args.line1, args.line2, args.range))
end, { nargs = 0, range = true })

api.nvim_set_keymap("x", "foo", "", {
  noremap = true,
  callback = function()
    local cursor = api.nvim_win_get_cursor(0)
    print(string.format("cursor=%d,%d", cursor[1], cursor[2]))
  end,
})
```
* nvim --clean -u NONE +'source test.lua' test.lua
* `2ggVwjj` # cursor's at 4,2 now
* `foo` says cursor's at 4,2
* `:'<,'>Foo` says cursor's at 2,0

### Expected behavior

calling an usercmd with range wont change the cursor

### Neovim version (nvim -v)

nvim 0.10

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9.2

### $TERM environment variable

st-256color

### Installation

pacman

**Comment by zeertzjq** [comment]
`:h operator`
```
After applying the operator the cursor is mostly left at the start of the text
that was operated upon.
```
