### ISSUE TITLE
The issue #29271 should be closed.

### ISSUE THREAD

**Issue by korantu** [neovim/neovim#29451]
### Problem

I have experienced https://github.com/neovim/neovim/issues/29271 issue symptom:

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...im-macos/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 2:4. Invalid node type "delimiter":
  (delimiter) @markup.heading.1
   ^

stack traceback:
        [C]: in function '_ts_parse_query'
```

The problematic line `(delimiter) @markup.heading.1` is in `~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/vimdoc/highlights.scm` which is not packaged with vim, AFAIK.

If you comment out the problematic lines in the file: 
[highlights.scm](https://github.com/user-attachments/files/15937272/highlights.txt) then the treesitter would be happy and big part of highlight will work:

```
; (h1
;   (delimiter) @markup.heading.1
;   (heading) @markup.heading.1)
;
; (h2
;   (delimiter) @markup.heading.2
;   (heading) @markup.heading.2)
;
; (h3
;   (heading) @markup.heading.3)
;
; (column_heading
;   (heading) @markup.heading.4)
;
; (column_heading
;   (delimiter) @markup.heading.4
;   (#set! conceal ""))

```

and

```

; (modeline) @keyword.directive
;
; ((note) @comment.note
;   (#any-of? @comment.note "Note:" "NOTE:" "Notes:"))
;
; ((note) @comment.warning
;   (#any-of? @comment.warning "Warning:" "WARNING:"))
;
; ((note) @comment.error
;   (#any-of? @comment.error "Deprecated:" "DEPRECATED:"))
```

This would fix the issue https://github.com/neovim/neovim/issues/29271.

(This should have been better as comment there, but the issue is locked)

### Steps to reproduce

`:help TSDisable` , for example, will cause the symptoms

### Expected behavior

`:help TSDisable`  would just show help

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

dont have vim and it will not pick up the configuration

### Operating system/version

macOS 11.5

### Terminal name/version

Alacritty

### $TERM environment variable

xterm-256color

### Installation

https://github.com/neovim/neovim/releases/tag/v0.10.0 from releases on github repo

**Comment by clason** [comment]
That issue is about something different; the issue description is a bit misleading. _Your_ issue is a misconfiguration on your side (if you install nvim-treesitter, you _must_ install all bundled parsers with it).
