### ISSUE TITLE
Call `vim.lsp.util.jump_to_location` to jump to an unloaded buffer, where the buffer name is not shortened

### ISSUE THREAD

**Issue by gh-liu** [neovim/neovim#29457]
### Problem

Call the `jump_to_location` function to jump to an unloaded buffer, where the buffer name is not shortened, it is the full path of the file, this could be quite verbose and hard to read in the result of `:buffers` command.

### Steps to reproduce

1. open a project in nvim with lsp started
2. call `vim.lsp.buf.definition()` on a symbol which defined in other file that no loaded
3. see the result in the `:buffers` command

### Expected behavior

The bufname is shortened.

### Neovim version (nvim -v)

v0.11.0-dev-298+gd82efeccc

### Vim (not Nvim) behaves the same?

vim has no lsp

### Operating system/version

macos

### Terminal name/version

kitty

### $TERM environment variable

xterm-color256

### Installation

build from repo

**Comment by glepnir** [comment]
because uri_to_bufnr use full path . if you want use relative path i think you can modified in your local . this is not bug.

```lua
vim.uri_to_bufnr = function(uri)
  local fname = vim.uri_to_fname(uri)
  fname = vim.fn.fnamemodify(fname, ':p:.')
  return vim.fn.bufadd(fname)
end
```

**Comment by gh-liu** [comment]
> because uri_to_bufnr use full path . if you want use relative path i think you can modified in your local . this is not bug.
> 
> ```lua
> vim.uri_to_bufnr = function(uri)
>   local fname = vim.uri_to_fname(uri)
>   fname = vim.fn.fnamemodify(fname, ':p:.')
>   return vim.fn.bufadd(fname)
> end
> ```

Thanks, but I have tried the code and it doesn't work.

**Comment by glepnir** [comment]
just a simply code you may also need check fname include the root of cwd. then modify it and make sure the override before you call vim.lsp.buf.definition()

**Comment by miduddin** [comment]
I just noticed this issue on latest commit in master; I find the "not a bug" resolution to be unsatisfying.

Consider these 2 scenarios:

1. Call `vim.lsp.buf.definition()` on a symbol that would then opens up a new buffer. The default statusline will show an unshortened buffer name.
2. Call `vim.lsp.buf.references()` on a symbol that would then list all references in qflist. Pressing enter on any qf item opens up a new buffer, the default statusline will show a shortened buffer name (relative to cwd).

Is it not normal to expect these 2 LSP operations to at least have consistent result? (preferably shortened)

Additionally, it seems that the new buffer name in scenario 1 would automatically get shortened after I call `:buffers`, which is also weird.
