### ISSUE TITLE
Vim colorscheme doesn't restore the old behavior

### ISSUE THREAD

**Issue by YanDoroshenko** [neovim/neovim#29466]
### Problem

Default colorscheme is different on 0.10 even with `colorscheme vim`.

0.9.5:
![image](https://github.com/neovim/neovim/assets/13915536/0c3b57e8-da39-435d-9a17-23d16c1a4a8b)

0.10.0:
![image](https://github.com/neovim/neovim/assets/13915536/a6c4ab92-8ce4-4445-ae40-20570e15c4a5)

### Steps to reproduce

Open any code file with 0.9.5, open the same file with 0.10.0, see the difference.

### Expected behavior

I would expect the colorscheme not being broken or there being a way to bring it to the exact state it was in before.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Arch Linux

### Terminal name/version

st

### $TERM environment variable

st-256color

### Installation

System package manager (pacman)

**Comment by clason** [comment]
`:h news-10`

**Comment by YanDoroshenko** [comment]
Setting the colorscheme in `.init.vim` (as opposed to runtime `colorscheme` command) together with
```
hi Visual ctermfg=none ctermbg=242
```

Restored the previous state of affairs.
