### ISSUE TITLE
Updating nvim to latest version breaks theme and fonts.

### ISSUE THREAD

**Issue by fuiosa** [neovim/neovim#29474]
### Problem

Recently i was updating my system and after new nvim version was installed i noticed that it ignores theme and font which are applied in terminal emulator config. Downgrading the package solved the issue.

### Steps to reproduce

Update to 0.10.0 version of nvim.

### Expected behavior

Theme and font applied in terminal emulator config should apply to nvim too.

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Vim (not Nvim) behaves the same?

no, vim 9.1.0496-1

### Operating system/version

Archlinux [Hyprland]

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

pacman

**Comment by clason** [comment]
`:h news`

**Comment by justinmk** [comment]
Try `:set notermguicolors`. Nvim now sets truecolor by default
