### ISSUE TITLE
Support Neovim plugins natively with Wasm

### ISSUE THREAD

**Issue by liamwh** [neovim/neovim#29489]
### Problem

Would love for first-class support for Neovim plugins to be written in any language. Something like [wRPC](https://github.com/bytecodealliance/wrpc) might be very useful here.

### Expected behavior

This would future-proof Neovim's plugin ecosystem and open up many new possibilities

**Comment by clason** [comment]
Duplicate. Not planned currently but can be revisited once wasmtime is bundled.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/23579
