### ISSUE TITLE
Perl syntax highlighting very slow in 0.10

### ISSUE THREAD

**Issue by mecirt** [neovim/neovim#29486]
### Problem

Since upgrading to 0.10, editing syntax-highlighted perl files became much slower, and rapid scrolling (by holding pageup/pagedown) is very laggy and causes a spike in CPU usage.

This problem seems to be restricted to Perl files - Python and Javascript behave correctly.

This occurs with vanilla neovim --clean

Profiling indicates that the main CPU usage is in win_line and get_syntax_attr calls.

BUILD INFO:

NVIM v0.10.0
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Compilation: /usr/bin/cc -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fcommon  -Og -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -Wno-conversion -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto  -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -I/usr/include/luajit-5_1-2.1 -I/usr/include -I/home/abuild/rpmbuild/BUILD/neovim-0.10.0/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.10.0/build/include -I/home/abuild/rpmbuild/BUILD/neovim-0.10.0/build/cmake.config -I/home/abuild/rpmbuild/BUILD/neovim-0.10.0/src 

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

### Steps to reproduce

Edit a bigger (40KB+) Perl file, hit page up/down.

### Expected behavior

No CPU spike/lag.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

OpenSuSE Tumbleweed

### Terminal name/version

Konsole

### $TERM environment variable

xterm-256color

### Installation

packages

**Comment by NeddM** [comment]
Have you tried with another terminal?

**Comment by mecirt** [comment]
Yes. Xterm mostly avoids the issue by being rather slow with scrolling. Gnome-terminal has this problem too, even if less visible. The high CPU usage persists with both.

**Comment by privorka** [comment]
I have the same issues with Ruby files.
Tried iterm and kitty - both have the same issue - both with custom setup and `nvim --clean`.
Disabling the syntax highlight resolves the issue (`:syntax off`).

**Comment by justinmk** [comment]
what exact version of vim did you try?

also try the latest Nvim  development version. The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.
