### ISSUE TITLE
Update the Danish spellfile

### ISSUE THREAD

**Issue by andreasio** [neovim/neovim#29485]
### Problem

The spellfile used when `spelllang=da` is very old and not very good. Libre/openoffice uses a free and updated file from the excellent [stavekontrolden.dk](https://stavekontrolden.dk) project.  

Mkspell can't convert the dic or aff files. Instead I get `unrecognized flags`  or `invalid region`

Maybe this is because stavekontrolden is based on hunspell? https://github.com/neovim/neovim/pull/20131#pullrequestreview-1103362634  - I really cant figure it out, as the documentation also seems to suggest that an oxt file from office can be converted.

### Steps to reproduce

# prerequisite
* Download the file from https://sourceforge.net/projects/aoo-extensions/files/1429/12/da_dk-2.8.001.oxt/download
* Save to ~/Downloads/from_oo
* unzip the oxt file

# input (in nvim 0.10)
:mkspell ~/temp/da.spl ~/Downloads/from_oo/da_DK.aff

# Output
```
Reading word file /home/andreas/Downloads/from_oo/da_DK.aff...                                                                                              
Invalid region nr in /home/andreas/Downloads/from_oo/da_DK.aff line 280: 34,22 e^I+DATID    
```                 
No file is saved

### Expected behavior

The spellfile is generated,

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: RelWithDebInfo LuaJIT 2.1.1713773202

### Vim (not Nvim) behaves the same?

yes, 9.1.452

### Operating system/version

Fedora 40

### Terminal name/version

fish

### $TERM environment variable

xterm-256color

### Installation

dnf

**Comment by clason** [comment]
We don't maintain the spellfiles; please contribute a better one to Vim.
