### ISSUE TITLE
can not change cursor color in st(suckless simple terminal)

### ISSUE THREAD

**Issue by aidancz** [neovim/neovim#29498]
### Problem

st terminal, 'guicursor' option can not change cursor color

![pic-selected-240627-2230-54](https://github.com/neovim/neovim/assets/97080720/7eca9ba0-3f05-4c26-955a-6df104f8b912)

![pic-selected-240627-2231-09](https://github.com/neovim/neovim/assets/97080720/287f58d6-e214-4e74-9f70-de3b71164cef)

![pic-selected-240627-2231-20](https://github.com/neovim/neovim/assets/97080720/e4b4ec08-e0bd-46b5-81a4-cec60e5ec85a)

### Steps to reproduce

1. copy the example code from the FAQ page as `abc.vim` (HOW TO CHANGE CURSOR COLOR IN THE TERMINAL?)

```
:set termguicolors
:hi Cursor guifg=green guibg=green
:hi Cursor2 guifg=red guibg=red
:set guicursor=n-v-c:block-Cursor/lCursor,i-ci-ve:ver25-Cursor2/lCursor2,r-cr:hor20,o:hor50
```

2. open st terminal

3. `nvim --clean -u abc.vim abc.vim`

cursor color **not changes** (picture 1)

4. `:q` quit nvim, enter `TERM=xterm-256color`

5. `nvim --clean -u abc.vim abc.vim`

cursor color **changes** (picture 2)

6. `:q` quit nvim, but cursor color remain green

(picture 3)

### Expected behavior

change cursor color using 'guicursor' option

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

6.9.5-arch1-1

### Terminal name/version

st 0.9.2

### $TERM environment variable

st-256color

### Installation

AUR

**Comment by clason** [comment]
What does `:set tgc?` show?

**Comment by xvim64** [comment]
# Windows 11 23h2 (64bit) + nvim-win64 v0.10.0

# steps to reproduce

// in cmd.exe
nvim.exe --clean test.txt

// in nvim in cmd.exe
"hi normal ctermfg=1" // also changes "vertsplit ctermfg".
"hi vertsplit ctermfg=2" // does not change "vertsplit ctermfg".

// also in Neovim-qt, Neovide, Nvy,
"hi normal guifg=1" // also changes "vertsplit guifg".
"hi vertsplit guifg=2" // does not change "vertsplit guifg".

**Comment by justinmk** [comment]
Did you try a sample `printf` in your shell to confirm that your suckless terminal actually supports termcodes to change the cursor color? Suckless often requires [patches](https://st.suckless.org/patches/dynamic-cursor-color/) to get such behavior.

>  This also affects gui-frontends like Neovim-qt and Neovide.

@xvim64 not the same issue at all.
