### ISSUE TITLE
Cannot Use Help, constant `treesitter/highlighter.win` error messages

### ISSUE THREAD

**Issue by mangelozzi** [neovim/neovim#29492]
### Problem

When trying to use the built in help it constantly throws this error (if one presses a key a new error pops up until one closes the help):

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...L47j/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 2:4. Invalid node type "delimiter":
  (delimiter) @markup.heading.1
   ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...L47j/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...mmkL47j/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...mmkL47j/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        ...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
        ...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
        ...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:473: in function 'for_each_tree'
        ...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prepare_highlight_states'
        ...sr/share/nvim/runtime/lua/vim/tr
```

### Steps to reproduce

nvim --clean
:h subst

### Expected behavior

Be able to read the help

### Neovim version (nvim -v)

NVIM v0.11.0-dev-311+g9dc09a4cd Build type: RelWithDebInfo LuaJIT 2.1.1716656478 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

No

### Operating system/version

WSL2 Debian 12

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

appImage

**Comment by clason** [comment]
This should not happen with --clean. Are you sure?

**Comment by mangelozzi** [comment]
Thanks for looking into this, yes I was surprised to see it not working with clean as well, here's a screen recording:

![cant_use_help](https://github.com/neovim/neovim/assets/19764314/f5f48b6f-cd8c-469e-bef2-59977db46e34)

**Comment by clason** [comment]
And are you sure you are using the latest(!) appimage?

**Comment by yochem** [comment]
I have the same, but with the release version*. Doesn't happen with `--clean`, though.



```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.10.0/share/nvim"
```

**Comment by clason** [comment]
That doesn't imply it's the appimage. To be clear: we can't reproduce this, and I don't see how this error _can_ occur with a nightly appimage and `--clean`. Something weird is going on.

**Comment by mangelozzi** [comment]
> :TSUpdateSync

Thank you!! This did solve the problem. Ideally tree sitter would fail a bit more gracefully than blocking viewing the file. Should I close the issue out, or should it have not happened with clean?

**Comment by mangelozzi** [comment]
> That doesn't imply it's the appimage. To be clear: we can't reproduce this, and I don't see how this error _can_ occur with a nightly appimage and `--clean`. Something weird is going on.

```
$ which nvim
/usr/bin/nvim
$ ll /usr/bin/nvim
lrwxrwxrwx 1 root root 37 Jun 19 11:18 /usr/bin/nvim -> /home/michael/appimages/nvim.appimage
```

**Comment by towry** [comment]
I think this happens maybe because you are build from source with different build type in multiple times.

Try clean the build and build with release type again.

**Comment by TheFrankyDoll** [comment]
Found the same issue while on NixOS, installing `vimdoc` parser fixed the issue for me.

**Comment by Domain-Of-Wheat** [comment]
what was the solution to this, i have the same problem and ive tired TSUpdateSynce but it still won't work, and i ran command:
```
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
./nvim.appimage
./nvim.appimage --appimage-extract
./squashfs-root/AppRun --version
sudo mv squashfs-root /
sudo ln -s /squashfs-root/AppRun /usr/bin/nvim
nvim
```

to install neovim?

**Comment by mangelozzi** [comment]
> what was the solution to this, i have the same problem and ive tired TSUpdateSynce but it still won't work, and i ran command:
> 
> ```
> curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
> chmod u+x nvim.appimage
> ./nvim.appimage
> ./nvim.appimage --appimage-extract
> ./squashfs-root/AppRun --version
> sudo mv squashfs-root /
> sudo ln -s /squashfs-root/AppRun /usr/bin/nvim
> nvim
> ```
> 
> to install neovim?

`:TSUpdateSync` Did the trick for me, sorry it sounds like it doesnt fix your issue.

**Comment by CAESIUS-TIM** [comment]
# `:TSUninstall vimdoc`, `:TSInstall vimdoc`

After `:checkhealth`, found vimdoc got a "x" in H (Highlight).

```
Parser/Features         H L F I J
...                     ...
 - vimdoc               X . . . ✓
...                     ...
```

> x) errors found in the query, try to run :TSUpdate {lang} ~

But `:TSUpdate vimdoc` said "Parsers are up-to-date!".

So my solution is `:TSUninstall vimdoc` and `:TSInstall vimdoc` to reinstall vimdoc.

**Comment by mcp292** [comment]
On Fedora 40 running LunarVim, [`:TSUpdate`](https://github.com/LunarVim/LunarVim/issues/3680#issuecomment-1372345560) worked for me.
