### ISSUE TITLE
Document the 0.10 behavior regarding termguicolors

### ISSUE THREAD

**Issue by EvanCarroll** [neovim/neovim#29505]
### Problem

I'm sure you have a reason for doing this, I do not understand that reason and want to. Moreover, the lack of documentation on this makes this very difficult to troubl shoot. CORE neovim is the _last_ thing someone will troubleshoot to find this. First they will destroy their plugins, configuration, distribution configurations, etc before they get down to neovim and suspect the neovim project itself for doing it.

Here is the area of confusion,

* User adopts kitty.
* User selects a kitty color scheme.
* User launches vim and sees the color scheme is broken? What did it?

This is where I was when I asked this question: https://vi.stackexchange.com/q/45122/5078 

From what I can ascertain the reason is because you want a more complete color scheme, and you don't feel you can provide that if you can't depend on a background color. That's fine. 

What I don't understand is the purported fix for people that were fine before, and want the experience from 0.9. For us, we're told to run `notermguicolors`. And if that's weird because that option is documented as

> Enables 24-bit RGB color in the TUI.  Uses "gui" :highlight attributes instead of "cterm" attributes. Requires an ISO-8613-3 compatible terminal.

And that sounds like what I want.... What I don't want is the one background-set to override the terminal.

I mean `set bg=noclear` or something is where I would look for this problem if you told me it was in neovim. I would never assume that before pulling my hair out for many hours. I live in tuis. I run 20 of them at least. This is the only one that overrides my terminal background color.

All this to say, consider the user experience. This is likely not what a lot of people want, even if it is a minority. And the documentation for `termguicolors` and the Changelog doesn't at all indicate where the problem is.

A note like this in the Changelog would go a long way to helping us find a solution,

> Is your background color wrong on 0.10? Do you want to see your terminal's background color rather than the vim theme's background color? Do you see bars around you terminal? We did it! We changed the long standing behavior here. Read more about the reasoning [AT THIS LINK] which documents potential workarounds. 

Thanks for neovim.

### Expected behavior

Some direction...

**Comment by kovidgoyal** [comment]
Here is what I use in my nvim config
```lua
local fg = "#e0e0e0"
local bg = "#242424"
local set_terminal_default_colors = "\x1b]10;" .. fg .. "\a\x1b]11;" .. bg .. "\a"
local reset_terminal_colors = "\x1b]110\a\x1b]111\a"

-- Change terminal default colors to avoid having to highlight the normal group for performance
vim.cmd('highlight Normal guibg=NONE guifg=NONE ctermbg=NONE ctermfg=NONE')
io.stdout:write(set_terminal_default_colors)
vim.api.nvim_create_autocmd({ "VimEnter", "VimResume" }, {
    group = vim.api.nvim_create_augroup("KittySetNormalColors", { clear = true }),
    callback = function()
        io.stdout:write(set_terminal_default_colors)
    end,
})

vim.api.nvim_create_autocmd({ "VimLeave", "VimSuspend" }, {
    group = vim.api.nvim_create_augroup("KittyUnsetNormalColors", { clear = true }),
    callback = function()
        io.stdout:write(reset_terminal_colors)
    end,
})
```
This has the added benefit that nvim doesn't need to style Normal style cells at all, which at least in theory means it can send less bytes to draw the screen, whether it actually does so I haven't got around to checking.

**Comment by clason** [comment]
> A note like this in the Changelog would go a long way to helping us find a solution,

It's mentioned at the very top of `:h news`.

**Comment by gwerbin** [comment]
Maybe the OP's confusion would be alleviated by a note that you can run `:hi Normal guigb=NONE` to get a "transparent" background in the terminal when `termguicolors` is set.

**Comment by EvanCarroll** [comment]
> This has the added benefit that nvim doesn't need to style Normal style cells at all, which at least in theory means it can send less bytes to draw the screen, whether it actually does so I haven't got around to checking.

When you do that investigation please keep us updated. I prefer just the `vim.cmd('highlight Normal guibg=NONE guifg=NONE ctermbg=NONE ctermfg=NONE')` otherwise I have to keep my fg and bg in sync with my kitty theme manually
