### ISSUE TITLE
extmarks wont get restored with {right_gravity=true,invalidate=true,undo_restore=true} opts

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#29509]
### Problem

the extmark remains `.invalid=true` and no highlighting, after undo.

### Steps to reproduce

* test.lua
```
local api = vim.api

local ns = api.nvim_create_namespace("xxx")
local bufnr = api.nvim_get_current_buf()

api.nvim_buf_set_lines(bufnr, 0, -1, false, { "abcdefgh" })

local lnum = 0

local ids = {}
for i, col in ipairs({ 2, 5 }) do
  --stylua: ignore start
  local id = api.nvim_buf_set_extmark(bufnr, ns, lnum, col, {
    end_row = lnum, end_col = col + 2,
    hl_group = "Search", hl_mode = "replace", --to spot the problem easily
    right_gravity = false,
    invalidate = true, undo_restore = true,
  })
  --stylua: ignore start
  ids[i] = id
end
print("ns", ns, "ids", table.concat(ids, ","))
```
* nvim --clean -u NONE +'so test.lua' # it happend to be 'ns=1, ids=1,2' on my side
* `:lua =vim.api.nvim_buf_get_extmark_by_id(0, 1, 1, {details=true}`
```
{ 0, 2, {
    end_col = 4,
    end_right_gravity = false,
    end_row = 0,
    hl_eol = false,
    hl_group = "Search",
    invalidate = true,
    ns_id = 1,
    priority = 4096,
    right_gravity = false
  } }
```
* `xxxx`, `:lua =vim.api.nvim_buf_get_extmark_by_id(0, 1, 1, {details=true})
```
{ 0, 0, {
    end_col = 0,
    end_right_gravity = false,
    end_row = 0,
    hl_eol = false,
    hl_group = "Search",
    invalid = true,
    invalidate = true,
    ns_id = 1,
    priority = 4096,
    right_gravity = false
  } }
```
* `4u`, `:lua =vim.api.nvim_buf_get_extmark_by_id(0, 1, 1, {details=true})`
```
{ 0, 2, {
    end_col = 4,
    end_right_gravity = false,
    end_row = 0,
    hl_eol = false,
    hl_group = "Search",
    invalid = true,
    invalidate = true,
    ns_id = 1,
    priority = 4096,
    right_gravity = false
  } }
```

### Expected behavior

after `4u`, the extmark is valid and gets highlight back.

### Neovim version (nvim -v)

nvim 0.10

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

tmux-256color

### Installation

pacman

**Comment by luukvbaal** [comment]
Looks like we need to handle this case, this repro hits the assert:
https://github.com/neovim/neovim/blob/aa6b9c677d83d76d448c3bb0973bf8d14bfdf922/src/nvim/extmark.c#L120-L121
