### ISSUE TITLE
LSP: vim.lsp.rpc.connect() with hostname instead of IP address

### ISSUE THREAD

**Issue by tris203** [neovim/neovim#29513]
### Problem

Does anyone know if vim.lsp.rpc.connect() should work with a hostname or is it IP only.

It works perfectly with 127.0.0.1 but localhost returns the below. In the docs the field is called host, so I don't see anything that suggests it should be IP only. 

Anybody more familiar with the LUV TCP stuff?

Perhaps there should be a resolution step in rpc.lua to be able to function with hostnames too?

```/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:706: Invalid IP address or port [localhost:5000]```

### Steps to reproduce using "nvim -u minimal_init.lua"

No

### Expected behavior

To connect via hostname 

### Neovim version (nvim -v)

0.11 dev

### Language server name/version

Any LSP over tcp

### Operating system/version

Ubuntu 22.04

**Comment by justinmk** [comment]
Give a minimal yet complete example, showing the exact code you tried.

**Comment by tris203** [comment]
Sure, i am using the code from this PR #19916 

<details>
  <summary>an example of a minimal TCP LSP in go</summary>

```go
package main

import (
	"github.com/tliron/commonlog"
	"github.com/tliron/glsp"
	protocol "github.com/tliron/glsp/protocol_3_16"
	"github.com/tliron/glsp/server"

	// Must include a backend implementation
	// See CommonLog for other options: https://github.com/tliron/commonlog
	_ "github.com/tliron/commonlog/simple"
)

const lsName = "my language"

var (
	version string = "0.0.1"
	handler protocol.Handler
)

func main() {
	// This increases logging verbosity (optional)
	commonlog.Configure(1, nil)

	handler = protocol.Handler{
		Initialize:  initialize,
		Initialized: initialized,
		Shutdown:    shutdown,
		SetTrace:    setTrace,
	}

	server := server.NewServer(&handler, lsName, false)

	err := server.RunTCP(":5000")
	if err != nil {
		panic(err)
	}
}

func initialize(context *glsp.Context, params *protocol.InitializeParams) (any, error) {
	capabilities := handler.CreateServerCapabilities()

	return protocol.InitializeResult{
		Capabilities: capabilities,
		ServerInfo: &protocol.InitializeResultServerInfo{
			Name:    lsName,
			Version: &version,
		},
	}, nil
}

func initialized(context *glsp.Context, params *protocol.InitializedParams) error {
	return nil
}

func shutdown(context *glsp.Context) error {
	protocol.SetTraceValue(protocol.TraceValueOff)
	return nil
}

func setTrace(context *glsp.Context, params *protocol.SetTraceParams) error {
	protocol.SetTraceValue(params.Value)
	return nil
}
```
</details>

and the code to connect

```lua
vim.lsp.start({ name = "example", cmd = vim.lsp.rpc.connect("localhost", 5000) })
```
Replacing localhost with either 127.0.0.1 or my LAN IP works. But localhost does not, it gives the message:

```
/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:706: Invalid IP address or port [localhost:5000]
```
Relevant docs here:
https://neovim.io/doc/user/lsp.html#vim.lsp.rpc.connect()

I would be happy to either PR functionality for DNS lookup, or a documentation change to make this clearer depending on what the correct direction should be

**Comment by justinmk** [comment]
Confirmed by these steps:

1. start a tcp server as described at `:help tcp-server`
2. `lua =vim.lsp.rpc.connect('localhost', 57945)()` fails
    ```
    E5108: ... lsp/rpc.lua:706: Invalid IP address or port [localhost:57945]
    ```
3. `lua =vim.lsp.rpc.connect('0.0.0.0', 57945)()`

In fact, it's not necessary to start a TCP server. It seems that the "Invalid IP address or port" message is coming from a validation step.

> I would be happy to either PR functionality for DNS lookup, or a documentation change to make this clearer depending on what the correct direction should be

For now we should document it.

**Comment by justinmk** [comment]
"localhost" would work if we used [tcp_connect](https://github.com/luvit/luv/blob/ae0387742b460bc89ebddce33214ad65fffddba2/examples/echo-server-client.lua#L42), but that will require changes to [vim.lsp.rpc.connect](https://github.com/neovim/neovim/blob/318c0415d5b10b44fee4afa06994734f1beb7e71/runtime/lua/vim/lsp/rpc.lua#L638).

**Comment by justinmk** [comment]
> I would be happy to either PR functionality for DNS lookup

PR for that would also be welcome!

"localhost" would work if we used [tcp_connect](https://github.com/luvit/luv/blob/ae0387742b460bc89ebddce33214ad65fffddba2/examples/echo-server-client.lua#L42), but that will require changes to [vim.lsp.rpc.connect](https://github.com/neovim/neovim/blob/318c0415d5b10b44fee4afa06994734f1beb7e71/runtime/lua/vim/lsp/rpc.lua#L638).

**Comment by tris203** [comment]
Thanks @justinmk
