### ISSUE TITLE
Support for attaching popup window to an LSP for limited calls

### ISSUE THREAD

**Issue by Fildo7525** [neovim/neovim#29515]
### Problem

Currently, we are not able to attach a popup window to any LSP client. The function `vim.lsp.buf_attach_client` always returns `false`. Thus, we cannot invoke gotoDefinition/Declaration/Implementation on anything.

### Expected behavior

After opening a popup window (e.g.: with a hover message) and adding the window to the LSP server, we could invoke some LSP functions, mostly goto.... functions. It would make sense to disable diagnostics. This would make transitioning between files much easier and improve better control flow following when debugging or when a programmer is getting used to an API.

This sparks a question of whether it would be possible to create a range-based enabled region for some of the LSP functions. This would be helpful in helpers e.g.: also goto..... methods

**Comment by mfussenegger** [comment]
There is nothing in 'vim.lsp.buf_attach_client` that would prevent it from attaching to buffers that happen to be displayed in floating windows.

E.g. something like:

```lua
api.nvim_create_user_command("Test", function(args)
  local bufnr = api.nvim_create_buf(true, true)
  vim.bo[bufnr].buftype = "acwrite"
  vim.bo[bufnr].bufhidden = "wipe"
  vim.bo[bufnr].filetype = "lua"
  local opts = {
    relative='win',
    row=3,
    col=3,
    width=80,
    height=10
  }
  api.nvim_open_win(bufnr, true, opts)
end, {})
```

works just fine coupled with a lua FileType that calls `vim.lsp.start({ name = "luals", cmd = {"lua-language-server"}, ...})`


> This sparks a question of whether it would be possible to create a range-based enabled region for some of the LSP functions. This would be helpful in helpers e.g.: also goto..... methods

This sounds a bit like https://github.com/neovim/neovim/issues/26783

**Comment by Fildo7525** [comment]
I actually thought of something else:

```lua
local M = {}
M.bufnr, M.winnr = vim.lsp.util.open_floating_preview(tbl, 'markdown', {
	border = config.border,
	focusable = true,
	focus = true,
	focus_id = "pretty-hover",
	wrap_at = config.max_width,
	max_width = config.max_width,
	max_height = config.max_height,
})

vim.wo[M.winnr].foldenable = false
vim.bo[M.bufnr].modifiable = false
vim.bo[M.bufnr].bufhidden = 'wipe'
```

I wanted to start LSP client in a buffer created like this. Setting filetype to this buffer destroys the markdown formatting.

**Comment by mfussenegger** [comment]
Why would it destroy the markdown formatting?

**Comment by Fildo7525** [comment]
I could only start the lsp server for the filetype that I have declared in the setup. Therefore, I needed to change the filetype and the highlight of the hover message changed to the new filetype.
