### ISSUE TITLE
snippet: Visual Highlights Get Stuck (snippet.lua:101: attempt to index a nil value)

### ISSUE THREAD

**Issue by alivault** [neovim/neovim#29525]
### Problem

Visual highlights keep getting stuck. Happens often when I use a snippet like `rfcv` to generate a component inside of a new file. The snippet fails to include the name of the file. When I visually highlight something in the file and try to paste over it, the highlights get stuck. I then have to close and reopen the buffer to clear it. But when I reopen the buffer and begin to make changes, I get an error: `Error executing lua callback: ... lar/neovim/0.10.0/share/nvim/runtime/lua/vim/snippet.lua:101: attempt to index a nil value`

Video of the stuck visual highlight:

https://github.com/neovim/neovim/assets/48610822/8faee8e9-ffbd-47ff-8054-cf253e9636ad

Screenshot of errors once I close the buffer, reopen and begin to make changes to the buffer:
<img width="1728" alt="Screenshot 2024-06-28 at 7 46 09 PM" src="https://github.com/neovim/neovim/assets/48610822/ed4a78f9-5708-45e7-ab4e-b301ed0ea093">

As I start typing I get these errors on each keystroke: `Error detected while processing CursorMovedI Autocommands for "<buffer=268>":` `Error detected while processing TextChangedI Autocommands for "<buffer=268>":`

### Steps to reproduce

1. Create a new file
2. Use `rfcv` to generate a component
3. Notice that the file name is missing from the snippet
4. Type in a component name
5. Visually highlight the contents of the render and paste over it
6. Notice that the text and highlight gets stuck. Escaping fails to clear the highlight.
7. Close the buffer and reopen
8. Make changes to some text
9. Notice the error: `Error executing lua callback: ... lar/neovim/0.10.0/share/nvim/runtime/lua/vim/snippet.lua:101: attempt to index a nil value`

### Expected behavior

There should be no error `Error executing lua callback: ... lar/neovim/0.10.0/share/nvim/runtime/lua/vim/snippet.lua:101: attempt to index a nil value`

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

MacOS 14.4.1 

### Terminal name/version

Kitty 0.35.2

### $TERM environment variable

xterm-kitty

### Installation

homebrew

**Comment by chrisliaw** [comment]
I've been bother by this issue too but unfortunately it is not consistent.

It some times will go away after few saves but some time it keep throwing out. Sometime restart the neovim it will be gone for a while and after a while, it come back on different source file. I'm not sure how to reproduce this. How can we support this? Anything else to look for?

**Comment by chrisliaw** [comment]
![Screenshot 2024-08-01 at 11 46 56 AM](https://github.com/user-attachments/assets/9974148d-b35c-4891-ab6d-91c871291573)

Some screenshot on the output sorry have to mask the background due to IP issue...

**Comment by maxkemzi** [comment]
The neovim 0.10.1 update seems to have solved the problem. If the problem occurs again, I will report it. Share if the 0.10.1 update solved the problem for you as well.
