### ISSUE TITLE
TextChanged event gets triggered with not changed b:changedtick

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#29526]
### Problem

sometimes TextChanged events get triggered with not changed b:changedtick which beats the meaning of its name.

### Steps to reproduce

* main.lua
```
local api = vim.api

local bufnr = api.nvim_get_current_buf()

local function tick() return api.nvim_buf_get_changedtick(bufnr) end

print("t0 tick=" .. tick())
api.nvim_buf_set_lines(bufnr, -1, -1, false, { "-- hello world" })
print("t1 tick=" .. tick())

local aug = api.nvim_create_augroup("xxx", { clear = true })
api.nvim_create_autocmd("textchanged", {
  group = aug,
  buffer = bufnr,
  callback = function(args) print(string.format("event=%s tick=%d", args.event, tick())) end,
})

print("t2 tick=" .. tick())
```
* nvim --clean -u main.lua
* seeing messages
```
t0 tick=1
t1 tick=3
t2 tick=3
event=TextChanged tick=3
```

### Expected behavior

textchanged event should not get triggered in this very snippet, as there is no change to b:changedtick

### Neovim version (nvim -v)

nvim 0.10

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9.2

### $TERM environment variable

tmux-256color

### Installation

pacman

**Comment by zeertzjq** [comment]
This is working as intended. See vim/vim#3772
