### ISSUE TITLE
Add alternatives to deprecated functions to doc comments

### ISSUE THREAD

**Issue by alichtman** [neovim/neovim#29524]
### Problem

![image](https://github.com/neovim/neovim/assets/20600565/64370958-6522-46bb-a6cd-b58ac593b623)

I get a warning about `vim.diagnostic.goto_prev` being deprecated in `nvim`, and I see two issues:

1. `:checkhealth vim.deprecated` does not flag this. Here is my current output:

```
==============================================================================
vim.deprecated: require("vim.deprecated.health").check()

 ~
- WARNING vim.tbl_flatten is deprecated. Feature will be removed in Nvim 0.13
  - ADVICE:
    - use vim.iter(…):flatten():totable() instead.
    - stack traceback:
        /home/alichtman/.local/share/nvim/lazy/nvim-colorizer.lua/lua/colorizer/nvim.lua:96
        /home/alichtman/.local/share/nvim/lazy/nvim-colorizer.lua/lua/colorizer.lua:588
        /home/alichtman/.config/nvim/lua/plugins/nvim-colorizer.lua:4
        /home/alichtman/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:376
        [C]:-1
        /home/alichtman/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:131
        /home/alichtman/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:391
        /home/alichtman/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:358
        /home/alichtman/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:197
        /home/alichtman/.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:127
        /home/alichtman/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:112
        /home/alichtman/.config/nvim/lua/lazy-config.lua:16
        [C]:-1
        /home/alichtman/.config/nvim/init.lua:6
```

2. No suggested migration path is present in `nvim`. In https://neovim.io/doc/user/deprecated.html, the suggested migration path is found:

- [vim.diagnostic.goto_next()](https://neovim.io/doc/user/deprecated.html#vim.diagnostic.goto_next())	Use [vim.diagnostic.jump()](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.jump()) with {count = 1} instead.
- [vim.diagnostic.goto_prev()](https://neovim.io/doc/user/deprecated.html#vim.diagnostic.goto_prev())	Use [vim.diagnostic.jump()](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.jump()) with {count = -1} instead.

### Expected behavior

`checkhealth` should flag this issue, and tell me what to do

**Comment by zeertzjq** [comment]
You have never invoked the function, so it's not possible to add it to `:checkhealth`.

**Comment by alichtman** [comment]
But I do get a warning in nvim? See the screenshot in my issue.

**Comment by zeertzjq** [comment]
Right, the alternative can be added to doc comments.

**Comment by dundargoc** [comment]
On 1: it's likely because you haven't used the function before running `:checkhealth vim.deprecated`. `:checkhealth vim.deprecated` can only list functions that has been called, it does not recursively scan files or anything fancy like that. So I suspect the current behavior is not incorrect.

**Comment by justinmk** [comment]
`:help deprecated` is the usual, expected approach.
