### ISSUE TITLE
.css file extensions add extra asterisks (*) when not supposed to

### ISSUE THREAD

**Issue by elementtest** [neovim/neovim#29538]
### Problem

did nvim --clean file_name.css.  entered * { and pressed enter.   The * was meant to target all, instead it would generate more *'s.  maybe it's thinking it's a comment?  (it's not)

### Steps to reproduce

nvim --clean file_name.css
type * {
press enter

### Expected behavior

type * {
press enter.  
No more *'s are generated

### Neovim version (nvim -v)

0.11.0-dev-110+gffbd09ef6

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Linux Mint 21.3

### Terminal name/version

xterm 3.1

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by clason** [comment]
It looks like the `commentstring` in the recently `css.vim` is missing some escaping. Please open the issue at vim/vim; we'll port any fix as a matter of course.

**Comment by elementtest** [comment]
> vim/vim

Correct me if I'm wrong but this is a neovim issue.  It happened after I updated.  nvim --clean file.css (with css extension), then using the universal operator * { will generate extra *'s.  It did not use to do this in neovim.
