### ISSUE TITLE
Add support for word-diff to diff mode

### ISSUE THREAD

**Issue by briandipalma** [neovim/neovim#29549]
### Problem

Vim's diff mode, for me at least, isn't as easy to read as git's word-diff mode. I realize this is a huge ask as it's changing diff mode to a single window from multiple ones but it would be amazing if such a feature was available.

![image](https://github.com/neovim/neovim/assets/1597820/987fa50a-3aaf-4c7c-b078-df3a174e0bff)

this screenshot from lazygit, using git word-diff=color mode shows clearly that the `async` keyword has been removed

compared to this

![image](https://github.com/neovim/neovim/assets/1597820/3d900332-1e40-42d9-8f82-f8be72f0d970)

which had me look through the string for differences before I opened up lazygit to see what the actual difference was.

I find myself constantly switching between the two programs in different terminal windows to review diffs, I'd prefer to just stay in neovim.

### Expected behavior

Some sort of option that enables word-diff mode, puts the diffs in the same window instead of side by side buffers.

**Comment by clason** [comment]
Why is using a plugin such as https://github.com/kdheepak/lazygit.nvim or https://github.com/lewis6991/gitsigns.nvim (which support this) not an option?

**Comment by briandipalma** [comment]
I'm not really talking about when I'm developing code, I'm more considering when the workflow when reviewing other peoples code.

I use https://github.com/harrisoncramer/gitlab.nvim to code review PRs, this in turn makes use of https://github.com/sindrets/diffview.nvim to display the diff, which uses nvim's diff view. Sometimes this makes it hard to spot small changes as word diffs aren't present. So I open lazygit either in another terminal window or using a neovim plugin. I'd prefer to stay inside neovim as I have access to the LSPs and diagnostics in the diff and I can more seamlessly navigate the code from a diff.

**Comment by lewis6991** [comment]
I don't think there's scope for this to implement in core. Should be done in a plugin.
