### ISSUE TITLE
Netrw: missing '..' and '.' lines.

### ISSUE THREAD

**Issue by IvanGoncharov** [neovim/neovim#2954]
I run neovim as follow:
>$ nvim .

Behaviour is the same with `Ex`.

I renamed my `.nvimrc' and have latest nvim:
>nvim --version
NVIM 0.0.0-alpha (compiled Jul  3 2015 20:38:28)

For me it's very important issue, because it makes Netrw useless.

**Comment by fwalch** [comment]
Confirmed. I thought it might be related to a runtime update that is not yet in Neovim (https://github.com/vim/vim/commit/90de9e20987cb752a9acafd9ac7d919a4b79de5d), but this is not the case.

**Comment by IvanGoncharov** [comment]
I track it down to bug in `glob` function:
Vim output:
>:echo glob(".*", 0, 1)
['.', '..', '.netrwhist']

Neovim:
>:echo glob(".*", 0, 1)
['.netrwhist']

**Comment by IvanGoncharov** [comment]
I traced problem down to `gen_expand_wildcards` function.
Both `vim` and `nvim` call this function with `".*"` pattern.
`vim` found three files and `nvim` only one.

**Comment by IvanGoncharov** [comment]
@fwalch I found root cause of this problem.
`libuv` deliberately filter out '.' and '..', see [this](https://github.com/libuv/libuv/blob/master/src/unix/fs.c#L323)
Should it be fixed?

It looks like `libuv` done this on purpose to unify file listing between platforms.
Maybe `netrw` should be changed?

**Comment by fwalch** [comment]
Thanks for tracking this down! I guess the output `glob` should be consistent with Vim.. @justinmk is this a known difference in behavior?

**Comment by justinmk** [comment]
> is this a known difference in behavior?

No. If `glob(".*", 0, 1)` does not return `.` and `..` then technically it is broken.

**Comment by IvanGoncharov** [comment]
According to libuv/libuv/issues/426 this can't be fixed inside `libuv`.
I can implement ugly hack with injecting `.` and `..` into `os_scandir_next`.

Algorithm could be following:
 - inside `os_scandir` check that directory not root
 - set special variable `inject_dot_links` , inside `Directory` structure, to have `2` as value.
 - when `os_scandir_next` is called check `inject_dot_links`
 - if it equals `2` than decrements it and return `..`
 - if it equals `1` than decrements it and return `.`
 - if it equals `0` pass value from `uv_fs_scandir_next`

I really don't like this solution but I can't think of anything better :disappointed: 
@fwalch @justinmk Should I implement this solution?

**Comment by IvanGoncharov** [comment]
I also agree with arguments from libuv/libuv#426 about compatibility.
Node.js and Rust both use `libuv` and they don't have problems with such behaviour.
And it should make cross-platform plugins simpler to write.

In long run, maybe such issues can be fixed directly in VimL.
Something like compatibility layer for old plugins(`compatibility.vim`), which is enabled by default.
It doesn't make sense to do it only for this particular issue.
But could be done as general solution if similar bugs will occur in the future.

**Comment by splinterofchaos** [comment]
@ivangoncharov I don't like the idea of injecting logic into `os_scandir` like this, but it actually seems like the most sane approach.

If you implement this, please make sure that the logic of the affected functions handle `.` and `..` correctly.

**Comment by justinmk** [comment]
> I can implement ugly hack with injecting . and .. into `os_scandir_next`.

@IvanGoncharov  @splinterofchaos That's close to what I was thinking, but I think `os_scandir_next` might be too low-level. We should only "fix" this for user-facing interfaces, `glob()`. `globpath()`. (Note: also check [glob2regpat()](https://github.com/vim/vim/blob/80d998cccf1b473cc3c68eb9a7dfd07a1c261074/runtime/doc/eval.txt#L3685) which hasn't been merged yet from Vim).

Start with `f_glob{path}()`/`f_globpath()`. Maybe see if there's a common "middle layer" somewhere between `f_glob` them and `os_scandir_next`...

**Comment by fmoralesc** [comment]
Chiming in just to mention that glob2regpat() is implemented in #2941, so you might want to include that in the 0.1 milestone.

**Comment by fmoralesc** [comment]
Does this needs to work this way only in *nix? I'm exploring the codebase to see if I can fix this.
