### ISSUE TITLE
Missing heading for "REFERENCE MANUAL" TOC

### ISSUE THREAD

**Issue by wolfv6** [neovim/neovim#29543]
### Problem

This issue is on the help.txt page.

In Vim, the reference-manual TOC follows the "REFERENCE MANUAL" heading.
Thus the reader understands that the TOC is for the reference manual.

In Nvim, the reference-manual TOC starts at the "GENERAL" heading.
A noob has no way of knowing that the TOC is for the reference manual.

Possible solution:
Move the reference-manual TOC to a separate file, as was done for the user-manual TOC.
And add a link (tag) to the ABOUT NVIM section:
- user-manual       User manual: How to accomplish editing tasks.
- reference-manual  Reference manual: Precise description of how everything in Vim works.

### Steps to reproduce

:help to read the help.txt page

### Expected behavior

A "REFERENCE MANUAL" heading above the reference-manual TOC.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

no, vim 9.1

### Operating system/version

Fedora 40

### Terminal name/version

terminal Version 3.50.1 for GNOME 45

### $TERM environment variable

bash: xterm-256color: command not found

### Installation

dnf install -y neovim python3-neovim

**Comment by clason** [comment]
`gO`

**Comment by zeertzjq** [comment]
Maybe the `reference_toc` tag just needs to be moved to `GENERAL`?
```diff
diff --git a/runtime/doc/help.txt b/runtime/doc/help.txt
index fefead7fc9..53fa043814 100644
--- a/runtime/doc/help.txt
+++ b/runtime/doc/help.txt
@@ -42,7 +42,7 @@ through the help of many others.  See |credits|.
 NVIM DOCUMENTATION
 
 ------------------------------------------------------------------------------
-ABOUT NVIM				*reference_toc* *doc-file-list* *Q_ct*
+ABOUT NVIM						*doc-file-list* *Q_ct*
 
 |news|			News since the previous release
 |nvim|			Transitioning from Vim
@@ -59,7 +59,7 @@ ABOUT NVIM				*reference_toc* *doc-file-list* *Q_ct*
 |support|		Supported platforms
 
 ------------------------------------------------------------------------------
-GENERAL
+GENERAL							*reference_toc*
 
 |intro|			Introduction to Vim; notation used in help files
 |helphelp|		Using the :help files
```

When a user is reading help.txt, they may not know what "reference manual" means, so mentioning "reference manual" out of nowhere may actually cause confusion. It is already stated in usr_toc.txt that the reference manual TOC starts at the `reference_toc` tag:
```
Reference manual
|reference_toc|     More detailed information for all commands
```

**Comment by wolfv6** [comment]
@zeertzjq
A noob, with no awareness how the vim manuals are divided, would be confused.
Maybe they haven't even read the usr_toc.txt page yet.
Even if they did, it would be hard to connect the dots.
The following solution makes it easy for a noob to see how the manuals are divided.

Add a link (tag) to the reference-manual TOC, as was done for the user-manual TOC:
```
user-manual       User manual: How to accomplish editing tasks.
reference-manual  Reference manual: Precise description of how everything in Vim works.
```

And move the reference-manual TOC to a separate file.

**Comment by justinmk** [comment]
help.txt is the "homepage" of the help. It lists a table of contents, how is that confusing?

I do plan to make a lot of changes to this page, but moving the TOC somewhere else doesn't solve anything. If anyone is confused that help.txt has a TOC on it, they are in for a bumpy ride.
