### ISSUE TITLE
too low contrast and too dark background of default colorscheme

### ISSUE THREAD

**Issue by jorsn** [neovim/neovim#29562]
### Problem

Thanks for making neovim, which is by far my favorite editor. But after the update to 0.10.0 I found myself in the fog: The contrast was gone.

In the default configuration and a light terminal, the new terminal colors have horribly low contrast.
The contrast is even lower since the background is very dark.
I call it horrible, because I sometimes have to take a close look to distinguish them, and thus they slow down very much parsing/scanning code with my eyes. I have normal eyesight. So, if someone has any issue with their eyes, it is basically like viewing through the fog and trying to read.

For the background, why should I artificially constrain the dynamic range of my screen in software? If I want my screen to be darker (and have less contrast), I can dim it and save energy.

#### Examples

![nvim colors default](https://github.com/neovim/neovim/assets/4646725/5e55f319-233d-4419-a160-03f5a04b5452)
![nvim colors default config](https://github.com/neovim/neovim/assets/4646725/f5a2e467-2023-452f-b01f-a7b4abfbbeb6)

In the first two lines of the second example, is `zathura` the same type of thing as the comment? No. Are the colors distinguishable? No.

In comparison, the `nvim-qt` colors are much better.
![nvim colors default nvim-qt](https://github.com/neovim/neovim/assets/4646725/90ae08ee-1b36-458b-bdbd-a01215bed07d)
![nvim-qt colors default config](https://github.com/neovim/neovim/assets/4646725/916afd83-e2cb-42e3-830d-27453e704899)

`:colorscheme vim` has a similar effect. Of course, colorscheme vim has its weaknesses, e.g. it is unusable with light background and vimdiff.

### Steps to reproduce

nvim --clean
in nvim, type `:help`

For comparison, run nvim-qt, e.g. or set `:colorscheme vim`

### Expected behavior

The default should rather be high contrast than low contrast for accessibility reasons.

Colors should be clearly distinguishable and everything have sufficient contrast (brightness and color contrast) so that reading and scanning is easy.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no, the default color scheme is different there anyway

### Operating system/version

NixOS 24.05

### Terminal name/version

xterm 390

### $TERM environment variable

xterm/xterm-256color

### Installation

install with home-manager from nixpkgs-unstable

**Comment by clason** [comment]
> I call it horrible

Such hyperbole will get you nowhere. The colors were chosen (under hard constraints) with objectively(!) maximal contrast, so this is the best we can do. You are welcome to use another colorscheme you like better (or, indeed, the old one via `:colorscheme vim`).

**Comment by jorsn** [comment]
I'm sorry for the wording, I must admit I was a bit shocked by the experience.

However, stating that my two examples have “objectively(!) maximal contrast” is quite a hyperbole, too. Especially the color contrast between strings and comments in the second example – it is almost zero.

Of course I use a different colorscheme now, but having such bad contrast would seriously put me off if I were a new user. Of course the defaults are your choice.

**Comment by clason** [comment]
> Especially the color contrast between strings and comments in the second example – it is almost zero.

It is not, and you can measure it. If you are interested, there are long issue and PR discussions accompanying this change. 

Now that you've hopefully gotten over your shock with this "bug report", I will close this as not adding anything over the previous discussions.

**Comment by justinmk** [comment]
You can get high contrast by `:set notermguicolors`.

I do agree that it looks like we could bump up the blackness of the Normal fg for bg=light, and vice versa for bg=dark.
