### ISSUE TITLE
vim.ui.open can't handle all file names

### ISSUE THREAD

**Issue by XeroOl** [neovim/neovim#29579]
### Problem

The Lua function `vim.ui.open()` can't open all files. Some filenames with `[]` characters don't work. Here's what happens when I open `foo[2024-01-01].txt`:
```
E5108: Error executing lua Vim:E944: Reverse range in character class
stack traceback:
        [C]: in function 'expand'
        /usr/share/nvim/runtime/lua/vim/ui.lua:139: in function 'open'
        [string ":lua"]:1: in main chunk
```
The documentation at `:help vim.ui.open()` seems to imply that any filename works.

### Steps to reproduce

```
touch "foo[2024-01-01].txt"
nvim --clean
:lua vim.ui.open("foo[2024-01-01].txt")
```

### Expected behavior

the file is opened, with whatever xdg-open decides is the right program.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux x86_64

### Terminal name/version

qterminal 2.0.1 + tmux 3.4

### $TERM environment variable

tmux-256color

### Installation

Arch Repository neovim-0.10.0-5

**Comment by zeertzjq** [comment]
This change will fix this problem:
```diff
diff --git a/runtime/lua/vim/ui.lua b/runtime/lua/vim/ui.lua
index ec5c5c5ba0..9a649ab302 100644
--- a/runtime/lua/vim/ui.lua
+++ b/runtime/lua/vim/ui.lua
@@ -136,7 +136,7 @@ function M.open(path)
   })
   local is_uri = path:match('%w+:')
   if not is_uri then
-    path = vim.fn.expand(path)
+    path = vim.fn.fnamemodify(path, ':p')
   end
 
   local cmd --- @type string[]
```
but it doesn't support environment variables.
