### ISSUE TITLE
cnext/cprev prints (n of m): filename

### ISSUE THREAD

**Issue by catgoose** [neovim/neovim#29597]
### Problem

Since https://github.com/neovim/neovim/commit/aa6b9c677d83d76d448c3bb0973bf8d14bfdf922 when I use `cnext` or `cprev` with a populated quickfix, I get a printout like:

![image](https://github.com/neovim/neovim/assets/21010072/0b20a41c-0218-4705-9d10-2010cf75d123)

I use `kevinhwang91/nvim-bqf` so this printout is different than with minimal config, which produces something like:

![image](https://github.com/neovim/neovim/assets/21010072/4bfa4f19-5fb4-42a8-89af-4b255419b06a)

I've tried playing with shortmess +O, but I don't think it is related.

### Steps to reproduce

nvim --clean  -u minimal.lua

:set cmdheight=0
:vimgrep /pattern/gj **/*
:cnext

### Expected behavior

This print message should not be displayed.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-359+g5b778a64e

### Vim (not Nvim) behaves the same?

yes, VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 03 2024 02:37:51)

### Operating system/version

Ubuntu 22

### Terminal name/version

kitty 0.21.2

### $TERM environment variable

tmux-256color

### Installation

repo

**Comment by zeertzjq** [comment]
This is working as intended.

**Comment by catgoose** [comment]
Why did it suddenly start printing that message?  Is there a way to disable this output?

**Comment by zeertzjq** [comment]
> Why did it suddenly start printing that message?

It's always been like this. I don't know why it didn't previously happen for you.

> Is there a way to disable this output?

Add `:silent` before the command.

**Comment by zeertzjq** [comment]
Wait, something may indeed have changed.

**Comment by catgoose** [comment]
![image](https://github.com/neovim/neovim/assets/21010072/23b131f4-9354-4398-9b9c-199cb4171368)

This is with `silent! cnext` with minimal.lua

**Comment by zeertzjq** [comment]
Hmm right, `:silent` doesn't work. However, `:redraw | cnext` seems to work.
