### ISSUE TITLE
Bug in command mode => :!nvim file

### ISSUE THREAD

**Issue by testware73** [neovim/neovim#29603]
### Problem

nvim freezes after that

### Steps to reproduce

:!nvim file

### Expected behavior

nvim freezes after that

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1720049189 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

i don't know

### Operating system/version

6.9.7-arch1-1

### Terminal name/version

foot version: 1.17.2 +pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Installation

over the AUR

**Comment by zeertzjq** [comment]
Duplicate of #1496
