### ISSUE TITLE
LSP handlers do not consistently check if the buffer is still valid

### ISSUE THREAD

**Issue by Parsifa1** [neovim/neovim#29614]
### Problem

When an lsp is loading, use `lua vim.api.nvim_buf_delete(0, { force = true })` to delete the buffer, and the following error will appear:
```
Error executing vim.schedule lua callback: ...ed-nightly/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:73: Invalid buffer id: 17

Error executing vim.schedule lua callback: ...ghtly/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:309: ...ghtly/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:102: Invalid buffer id: 26

```

### Steps to reproduce

1. Open a buffer and load lsp (choose the one with longer loading time)
1. Execute `:lua vim.api.nvim_buf_delete(0, { force = true })`
1. An error will be thrown

### Expected behavior

at [this](https://github.com/neovim/neovim/blob/b3d94b10870ce494941279f78387e1d98a7e48e7/runtime/lua/vim/lsp/inlay_hint.lua#L73C3-L73C60) place:

```lua
local lines = api.nvim_buf_get_lines(bufnr, 0, -1, false)
```
Maybe we can use `vim.api.nvim_buf_is_valid` before calling `api.nvim_buf_get_lines` to check whether the buffer is still valid at this time

### Neovim version (nvim -v)

NVIM v0.11.0-nightly+3c53e8f

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 11 WSL2 nixos

### Terminal name/version

Wezterm

### $TERM environment variable

xterm-256color

### Installation

nix package

**Comment by lewis6991** [comment]
I was able to produce a similar error using the steps in the OP, though I had to time it precisely.

```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/uri.lua:82: Invalid buffer id: 1
stack traceback:
        [C]: in function 'nvim_buf_get_name'
        /usr/local/share/nvim/runtime/lua/vim/uri.lua:82: in function 'uri_from_bufnr'
        /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:212: in function 'get_lines'
        /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:275: in function 'get_line'
        /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:289: in function 'get_line_byte_from_position'
        /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1636: in function 'buf_highlight_references'
        /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:468: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:681: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I think the problem is that all the async handlers don't check if the buffer is still valid. This will be in a bunch of places. We may be able to fix this centrally in `client.request`.

**Comment by Parsifa1** [comment]
due to the pr https://github.com/neovim/neovim/pull/30330 , this can be closed
