### ISSUE TITLE
replacing text with the same range of an extmark makes that extmark invalid

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#29611]
### Problem

hi folks, this is somehow related to #29509, but since that's about 'restoring&invalid', i feel i should open another issue.

replacing text with the same range of an extmark makes that extmark `.invalid=true`, but it does know the correct range after replacing, so i think that extmark should just be `.invalid=nil`.

### Steps to reproduce

* test.lua
```
local api = vim.api

local ns = api.nvim_create_namespace("xxx")

local bufnr = api.nvim_get_current_buf()

api.nvim_buf_set_lines(bufnr, 0, -1, false, { "", "abcd", "" })

--stylua: ignore start
local xmid = api.nvim_buf_set_extmark(bufnr, ns, 1, 1, {
  end_row = 1, end_col = 3,
  hl_group = "Search",
  right_gravity = false, end_right_gravity = true,
  invalidate = true, undo_restore = true,
})
--stylua: ignore end

api.nvim_create_autocmd("textchanged", {
  buffer = bufnr,
  callback = function()
    local xm = api.nvim_buf_get_extmark_by_id(bufnr, ns, xmid, { details = true })
    print(string.format("(%s:%s,%s:%s) invalid=%s", xm[1], xm[2], xm[3].end_row, xm[3].end_col, xm[3].invalid))
  end,
})

api.nvim_buf_set_keymap(bufnr, "n", "<F1>", "", {
  noremap = true,
  callback = function()
    local timestamp = tostring(os.time())
    local xm = api.nvim_buf_get_extmark_by_id(bufnr, ns, xmid, { details = true })
    -- api.nvim_buf_set_text(bufnr, xm[1], xm[2] + 1, xm[3].end_row, xm[3].end_col - 1, { timestamp })
    api.nvim_buf_set_text(bufnr, xm[1], xm[2], xm[3].end_row, xm[3].end_col, { timestamp })
  end,
})
```
* `nvim --clean -u test.lua`
* `<F1>` # text replaced correctly, seeing '(1:1,1:11) invalid=true', the highlight is gone
* `<F1>` #text replaced correctly

### Expected behavior

i think in this case the extmark should remain valid (`.invalid=nil`), and have highlighted.

### Neovim version (nvim -v)

nvim 0.10

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9.2

### $TERM environment variable

tmux-256color

### Installation

pacman

**Comment by luukvbaal** [comment]
This doesn't look like a bug, the `invalidate/invalid` properties are also not really relevant. This is just about the splice for replacing a word (through `nvim_buf_set_text` or otherwise), on a mark that spans that word, yielding a zero-range mark. I don't think that is subject to change.

**Comment by haolian9** [comment]
thanks for your reply. it's been a week, i believe that's the conclusion.

**Comment by luukvbaal** [comment]
I believe so as well, but left it open in case someone(@bfredl) had different thoughts on the issue.
