### ISSUE TITLE
Webpage showing breaking changes, make following Nvim easier

### ISSUE THREAD

**Issue by Pyrohh** [neovim/neovim#2962]
OpenBSD [uses this webpage](http://www.openbsd.org/faq/current.html) to show breaking changes, sorted by most recent at the bottom, which I find very helpful to follow `-current`.

We don't make breaking changes very often, but I think it would be very helpful for some users if Neovim adopted this. It would make it easier for anyone who wants to run a development version of Neovim, but doesn't necessarily want to follow every happening.

I know this should be under the `neovim.github.io` repository, but not much people actually follow that repo compared to this.

**Comment by fwalch** [comment]
I had the idea of writing up a Gist of this at some point, but didn't follow up on it because we didn't make breaking changes at that time.

Maybe just add a Wiki page?

**Comment by Pyrohh** [comment]
> Maybe just add a Wiki page?

Oh... duh :grin:
I'll try to do that later today.

**Comment by Pyrohh** [comment]
Okey, I created https://github.com/neovim/neovim/wiki/Following-HEAD
Feel free to revise it, the intro might be a bit rough, and it's obviously lacking entries. Perhaps I'll retroactively add some...

Anyways, closing this.
