### ISSUE TITLE
Remove phpcomplete

### ISSUE THREAD

**Issue by Pyrohh** [neovim/neovim#2963]
[It's outdated by a few months](https://github.com/shawncplus/phpcomplete.vim), and judging by how long it took to deal with #1992, not many people seem to care about it.

Why not just remove it and instruct users to install [shawncplus/phpcomplete.vim](https://github.com/shawncplus/phpcomplete.vim) with a package manager?

refs #2962

**Comment by mtglsk** [comment]
Why not distribute all syntax / ftplugin / plugins as addons?

**Comment by MarcWeber** [comment]
I often had the idea to just move official $RTP into a github repository. https://github.com/MarcWeber/vim-addon-errorformats is an addon which extracts error format descriptions - eg I had a project I worked on a ruby build system compiling ocaml. That code allows to concatenate error descriptions to catch multiple formats easily. Making things modular runs the risk of breakage - but also allows for improvements.

**Comment by raichoo** [comment]
+1 for removing these things from base. I myself maintain a syntax highlighter for Haskell and other tools I'm using. The Haskell support that is shipped with Vim is simply atrocious. Even though I'm not using Atom I like the way they handle things: Oh I need a plugin for X, fire up package manager, search, install, initiate happy dance. It would be awesome to have a similar workflow in Neovim.

**Comment by ZyX-I** [comment]
The problem is that there is no official plugin manager. And no official repository format for the plugin manager. (And most of plugin managers have no centralized repository with plugin descriptions at all.)

**Comment by norcalli** [comment]
@ZyX-I http://vimawesome.com/ is about the closest you can get to someone having compiled all the information together and `vim-plug` is my favorite manager. There are plenty to choose from and they're fairly easy to install.

+1 I too agree that default syntax stuff can be annoying. I recently had to disable all of the mappings for `sql` as they mapped to `<c-c>*` in insert mode. Advocating for a single official plugin manager would be a good move to solve this.

**Comment by torpak** [comment]
@ZyX-I vim doesn't have an official plugin manager and will likely never have one but neovim could get one or at least an official default. Don't you have commit access?

**Comment by Pyrohh** [comment]
@torpak This is discussed in #247.

**Comment by justinmk** [comment]
Let's conflate this with #247
