### ISSUE TITLE
[Termdebug] :Break command fails if there is " " (space) in program path

### ISSUE THREAD

**Issue by dimitry-ishenko** [neovim/neovim#29635]
### Problem

Trying to execute `:Break` command on a program that has space(s) in its path fails with following error:

```
Error detected while processing function <SNR>11_JobOutCallback[10]..<SNR>11_CommOutput[24]..<SNR>11_HandleError:           
line    8:
-break-insert: Garbage following <location>^M
Press ENTER or type command to continue
```

### Steps to reproduce

In terminal execute:
```shell
mkdir "foo bar"
cd "foo bar"
echo "int main() { }" > main.c
vim main.c
```

Inside neovim execute:
```vim
:packadd termdebug
:Termdebug
:Source
:Break
```

You will be greeted with:
```
Error detected while processing function <SNR>11_JobOutCallback[10]..<SNR>11_CommOutput[24]..<SNR>11_HandleError:           
line    8:
-break-insert: Garbage following <location>^M
Press ENTER or type command to continue
```

### Expected behavior

Break point set at line 1.

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

Don't have vim

### Operating system/version

Ubuntu 24.04 LTS

### Terminal name/version

GNOME Terminal 3.52.0 using VTE 0.76.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

apt install neovim

**Comment by zeertzjq** [comment]
Related https://github.com/vim/vim/issues/12357
