### ISSUE TITLE
Invoking -V Spits Out Unexpected Output

### ISSUE THREAD

**Issue by histamineblkr** [neovim/neovim#29636]
### Issue description
When running `nvim -V` you get strange output like this:
![tmux-3 5-nvim-V-bug](https://github.com/neovim/neovim/assets/5628330/10f5592a-983b-4176-a71e-ee98e6994ce9)

### Information
Used the stable release from [here](https://github.com/neovim/neovim/releases/stable)
This has happened on: `6.3.13-1-MANJARO` and on a GCP `Ubuntu 24.04 LTS` instance.

I have described the problem quite thoroughly in another post:
 * [here](https://github.com/tmux/tmux/issues/3983#issuecomment-2215265760)
 *  [here](https://github.com/tmux/tmux/issues/3983#issuecomment-2218332627)

where I found this problem on top of a tmux issue.

### Steps to reproduce

Install nvim from the tarball and run:
`nvim -V`

### Expected behavior

Give the version and not a bunch of strange output where I have to press some mixture of keys to finally exit out of the application.

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713484068

### Vim (not Nvim) behaves the same?

yes, version 9.1.16

### Operating system/version

Manjaro and Ubuntu

### Terminal name/version

konsole 24.051, bash 5.2.21, zsh 5.9

### $TERM environment variable

xterm-256color screen-256color

### Installation

other: tarball

**Comment by zeertzjq** [comment]
Please read the documentation.

**Comment by histamineblkr** [comment]
Oh I mixed up `-V` from when I was troubleshooting `tmux` with `-v` that `nvim` uses for version. Next time, instead of the age old dickhead response of "rtfm" you could have just said, "hey you mixed up `-V` with `-v` since you were looking for version.".

I get that you are busy, but it would have been about the same effort as typing your rtfm.
