### ISSUE TITLE
cpp comments don't continue next line

### ISSUE THREAD

**Issue by Drllap** [neovim/neovim#29637]
### Problem

In files with filetype=cpp, when pressing <CR> in a commented-out line, nvim/vim has always continued by commenting out the next line. It doesn't do that anymore. It also used to add a`*` on the line when writing Doxygen style block comments:
```
/**
 *
 *
 */
```

### Steps to reproduce

nvim --clean
set filetype=cpp
//`<CR>`
or
/**`<CR>`

### Expected behavior

```
//
//
```
or
```
/**
 *
```

### Neovim version (nvim -v)

v0.10.0

### Vim (not Nvim) behaves the same?

no, vim 9.1

### Operating system/version

Windows 10

### Terminal name/version

WezTerm

### $TERM environment variable

xterm-256color

### Installation

chocolatey

**Comment by Drllap** [comment]
This actually workes fine on my Linux box

**Comment by zeertzjq** [comment]
Already fixed by #29053
