### ISSUE TITLE
g:clipboard can only be set once

### ISSUE THREAD

**Issue by fredizzimo** [neovim/neovim#29644]
### Problem

Like the description says, `g:clipboard` can only be set once. The variable itself is updated but the changed code is not executed. 

NOTE: settings `set clipboard=unnamedplus` also stops the `g:clipboard` from updating, and this together with https://github.com/neovim/neovim/issues/29634, makes it impossible to Neovide to setup a remote clipboard if the user configuration specifies `clipboard=unnamedplus`.

A third way to make it stop working is to use the clipboard before setting `g:clipboard`

NOTE: I tested down to Neovim 0.8, and all versions are broken.

### Steps to reproduce

1. Create a file named `clipboard.lua`
```lua
local function set_clipboard(register)
    return function(lines)
    end
end

local function get_clipboard(register)
    return function()
        return {{"something.."..math.random()}, "V"}
    end
end

vim.g.clipboard = {
    name = "neovide",
    copy = {
        ["+"] = set_clipboard("+"),
        ["*"] = set_clipboard("*"),
    },
    paste = {
        ["+"] = get_clipboard("+"),
        ["*"] = get_clipboard("*"),
    },
    cache = false,
}
```

Alternative 1.
1. Launch nvim
2. `:luafile clipboard.lua`
3. `"+p` -> pastes correctly
4. Change `something` to `something else` in `clipboard.lua`
5. `"+p` -> Does still paste `something...`

Alternative 2.
1. Launch nvim
2. `:set clipboard=unnamedplus`
3. `:luafile clipboard.lua`
4. `"+p` -> Uses the system clipboard instead of our custom clipboard function

Alternative 3.
1. Launch nvim
2. Paste something from the system clipboard
3. `:luafile clipboard.lua`
4. `"+p` -> Still uses the system clipboard

### Expected behavior

The clipboard should update each time it is set.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

Not tested

### Operating system/version

Linux

### Terminal name/version

Alacritty

### $TERM environment variable

xterm-256color

### Installation

Manually built

**Comment by zeertzjq** [comment]
`:h provider-reload`

**Comment by dundargoc** [comment]
> Thanks, that seems to work, but the documentation for `:h g:clipboard` isn't the most helpful here.

Would you like to send a PR to improve what you feels is missing from the docs?
