### ISSUE TITLE
Underline doesn't work in neovim inside tmux but does work in tmux and neovim outside tmux

### ISSUE THREAD

**Issue by Kyren223** [neovim/neovim#29649]
### Problem

Squiggly underlines (and probably other similar things) don't work inside Neovim if it's inside a tmux session (does work on neovim outside of tmux, and tmux on it's own).

Image showing that it doesn't work (taken inside tmux inside neoivm)
The expected output is in "expected behaviour"
![image](https://github.com/neovim/neovim/assets/52241860/4bca9a43-bc7a-4061-a8eb-53ea39136a28)

### Steps to reproduce

Install latest neovim (0.10.0)
Setup a colorscheme or plugin that includes squiggly brackets (like LSP diagnostics)
Open a tmux session with the following config:
```
set -g default-terminal "xterm-256color"
set-option -as terminal-overrides ",xterm-256color:Tc"
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
```
Open neovim inside the tmux session
Open a file with some text that contains a squiggly underline (like a lua file with a LSP error)
See that squiggly brackets are not shown properly, instead a normal underline is shown, and the color inherits the text color rather than have it's own color

### Expected behavior

To properly render squiggly underline with the correct color,
example of neovim outside of a tmux session (same snippet as in problem):
![image](https://github.com/neovim/neovim/assets/52241860/3c550917-fe69-479f-8b93-be3db3745a47)
Note the properly colored squiggly underlines

I don't believe it's an issue with tmux, when running the command:
`printf "\x1b[58:2::255:0:0m\x1b[4:1msingle\x1b[4:2mdouble\x1b[4:3mcurly\x1b[4:4mdotted\x1b[4:5mdashed\x1b[0m\n"`
Inside a tmux session, I get the following output:
![image](https://github.com/neovim/neovim/assets/52241860/4d78dcc0-2f09-4374-bf5e-011b5b13f660)
which shows that tmux can properly display these kind of underlines

From a few hours of research, it might be because I am using xterm-256color (I also tried with screen-256color which seems to have the same result), I was not able to try tmux or tmux-256color because it was not recognized as an option.
This also seems to be somehow related to the way escape codes work on Microsoft, as I am using the "Windows Terminal"

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

N/A-

### Operating system/version

openSUSE Tumbleweed using WSL2 on windows 11

### Terminal name/version

tmux 3.4 (inside a WSL instance using "Windows Terminal" on windows)

### $TERM environment variable

xterm-256color

### Installation

Zypper (system package manager)

**Comment by zeertzjq** [comment]
> I was not able to try tmux or tmux-256color because it was not recognized as an option.

What does this mean?

**Comment by Kyren223** [comment]
@zeertzjq it's an option for $TERM (like xterm-256color) from the research I did, "ncurses" or "terminfo" are the programs that handle $TERM, and only certain versions of ncurses support tmux/tmux-256color, and my setup seems to not have a tmux/tmux-256color option available, and I couldn't figure out if there is even a way to "install" those options.
And screen-256color has the same problem as xterm-256color but also messes up letters I type

**Comment by zeertzjq** [comment]
Then I'm afraid it's not possible to support this, because it's not possible for Nvim to tell a tmux version that supports undercurl from a tmux version that doesn't support it.

**Comment by Kyren223** [comment]
@zeertzjq Is there a way to force neovim to act like it does have support?
Maybe some config option?
And if not, do you know about any resources that explain how to add the tmux-256color to terminfo, I was searching for hours and couldn't find any (or, if you know a better place to ask this kind of question)

**Comment by zeertzjq** [comment]
Wait, actually even if you don't have a `tmux-256color` terminfo entry, Nvim will still work if you set `$TERM` to `tmux-256color`, because Nvim has builtin terminfo for `tmux-256color`. Does this work:
```sh
TERM=tmux-256color nvim
```

**Comment by Kyren223** [comment]
@zeertzjq Yes it does, thank you so much!

**Comment by PeterCardenas** [comment]
This still does not work for me but I also don't see Smulx when executing `infocmp -L`. @Kyren223 do you get anything when you do `infocmp -L | grep Smulx`?

**Comment by PeterCardenas** [comment]
huh looks like the terminfo was in `/opt/local/share/terminfo` since i guess i installed ncurses 6 with macports at some point. setting `TERMINFO_DIRS` to `/opt/local/share/terminfo` did the trick. the following is what i added to my `config.fish`:

```fish
if set -q TERMINFO_DIRS
    set -gx TERMINFO_DIRS /opt/local/share/terminfo:$TERMINFO_DIRS
else
    set -gx TERMINFO_DIRS /opt/local/share/terminfo
end
if set -q TERMINFO
    set -gx TERMINFO_DIRS $TERMINFO:$TERMINFO_DIRS
end
```
