### ISSUE TITLE
No focus gained event while in insert mode

### ISSUE THREAD

**Issue by a73s** [neovim/neovim#29642]
### Problem

When you are in insert mode and you switch focus the window of another process (not another nvim window) you get a focused lost event. When you refocus the window you will not get a focus gained event.

### Steps to reproduce

```
for name, url in pairs {
  -- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
  -- some_plugin = 'https://github.com/author/plugin.nvim'
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

vim.opt.number = true
vim.opt.relativenumber = true
vim.api.nvim_create_augroup("custom-numbertoggle", {clear = true})

vim.api.nvim_create_autocmd({"FocusGained"}, {
	desc = "Toggle on relative numbers",
	group = "custom-numbertoggle",
	callback = function()
		if vim.opt.number and (vim.fn.mode() ~= 'i') then
			vim.opt.relativenumber = true
		end
	end,
})
vim.api.nvim_create_autocmd({"FocusLost"}, {
	desc = "Toggle off relative numbers",
	group = "custom-numbertoggle",
	callback = function()
		if vim.opt.number then
			vim.opt.relativenumber = false
		end
	end,
})

```
add this to a standalone config, run `nvim --clean -u <the config>`, insert a few blank lines so that you can see what happens to the numbers on the left.
You can tab to/focus another program and the numbers will become absolute numbers, then if you go back to nvim then you will get relative numbers back. 
If you go into insert mode, then do the exact same procedure you will see the issue. When focusing the second program it will go to absolute numbers, but when you refocus nvim it will not go back to relative line numbers as it should.

### Expected behavior

refocusing neovim should produce a focus gained event, even while in insert mode.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

Fedora 40

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

reproducable on both alacritty or ansi-256color

### Installation

from fedora repos

**Comment by zeertzjq** [comment]
Relative numbers aren't enabled because the autocommand has an explicit check `(vim.fn.mode() ~= 'i')`. If you remove this condition it will work.

**Comment by a73s** [comment]
Damn i really should have seen that. I just blindly translated that from vim script, my bad.
