### ISSUE TITLE
No focus gained event while in insert mode

### ISSUE THREAD

**Issue by a73s** [neovim/neovim#29640]
### Problem

When you are in insert mode and you switch to another window you get (i think) focused lost event. When you refocus the window you will not get a focus gained event.

### Steps to reproduce

```
vim.opt.number = true
vim.opt.relativenumber = true

vim.api.nvim_create_autocmd({"BufEnter", "FocusGained", "WinEnter"}, {
	desc = "Toggle on relative numbers",
	group = "custom-numbertoggle",
	callback = function()
		if vim.opt.number and (vim.fn.mode() ~= 'i') then
			vim.opt.relativenumber = true
		end
	end,
})
vim.api.nvim_create_autocmd({"BufLeave", "FocusLost", "WinLeave"}, {
	desc = "Toggle off relative numbers",
	group = "custom-numbertoggle",
	callback = function()
		if vim.opt.number then
			vim.opt.relativenumber = false
		end
	end,
})
```
This should be all you need to reproduce the issue, these replicate the behavior of vim numbertoggle, except I removed insert events because that is the behavior I desire.

### Expected behavior

when refocusing while in insert mode you should get a focus gained event

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

idk

### Operating system/version

Fedora 40

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

from fedora repos

**Comment by zeertzjq** [comment]
The steps to reproduce are incomplete. They don't create the `custom-numbertoggle` augroup or create multiple windows.

FocusGained or FocusLost are not triggered if you don't switch from Nvim to another process.
