### ISSUE TITLE
nvim-qt does not appear in the bin folder.

### ISSUE THREAD

**Issue by john-a-m** [neovim/neovim#29655]
### Problem

The instructions at https://github.com/neovim/neovim/blob/master/INSTALL.md imply that nvim-qt.exe should be bundled into the .zip for windows. I am using https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-win64.zip however I don't see the nvim-qt.exe. 
![noqt](https://github.com/neovim/neovim/assets/1537767/83ad2f47-4d82-4b38-85f8-2ce77e7fe03f)

### Steps to reproduce

Documentation bug.

### Expected behavior

nvim-qt should be there.

### Neovim version (nvim -v)

Nvim v0.10.0 

### Vim (not Nvim) behaves the same?

Windows

### Operating system/version

Windows

### Terminal name/version

Windows local install

### $TERM environment variable

Windows

### Installation

Windows

**Comment by john-a-m** [comment]
I tried to download nvim-qt from it's own github repo, however appveyor doesn't keep artifacts that are older than 1 month. nvim-qt's last build was 4 months ago. (maybe this is why it is not being bundled).

**Comment by zeertzjq** [comment]
You can download nvim-qt from its Releases page: https://github.com/equalsraf/neovim-qt/releases

**Comment by john-a-m** [comment]
Thanks, somehow I missed that. I ended up going with nvim 0.9.5 . It has nvim-qt in the bin directory, along with many files not present in the 0.10.0 .zip.

**Comment by clason** [comment]
Nvim-qt has intentionally been removed from our releases; looks like we missed a spot in the documentation.

**Comment by dundargoc** [comment]
Fixed in https://github.com/neovim/neovim/pull/29622
