### ISSUE TITLE
Feature request : * please add a "inbuilt standard" package manager for neovim too, just like emacs.

### ISSUE THREAD

**Issue by zaxebo1** [neovim/neovim#2967]
*Detail:* Emacs has now inbuilt package manager
   https://truongtx.me/2013/01/07/emacs-package-manager/

**please add a "inbuilt standard"  package manager for neovim too.**

Why
------
   people have implemented **vundle, neobundle, pathogen, and various other  package manager for vim. But there is a need for standardizing on this as inbuilt.**
This package manager will be able to list the available packages, and download and install the vimscript,python etc based plugins of neovim.

Advantage:
----------------
The packaged vimscripts of debian etc are very old and stale. We can get
updated packages using inbuilt package manager, it will be easy and less
error prone to install vim plugins

2) why to get behind emacs in one core feature of standardised package
manager.

3) if plugin has been packaged properly, then it will work across
OSes(linux,windows,mac) in the same way without installation differences
from user point of view

**So, please implement a standardised inbuilt package manager for neovim, just
like emacs**

**Comment by fwalch** [comment]
Please see #247.
