### ISSUE TITLE
TmuxNavigateLeft doesn't work

### ISSUE THREAD

**Issue by simendsjo** [neovim/neovim#2968]
I'm using the tmux-navigator plugin: https://github.com/christoomey/vim-tmux-navigator
It works fine in vim, but `<c-h>` in nvim doesn't work, it only moves the caret left.
This looks like an nvim issue as the mapping is present and calling `:TmuxNavigateLeft` gives the correct behavior.

**Comment by fwalch** [comment]
See https://github.com/neovim/neovim/issues/2048.
