### ISSUE TITLE
Bundled treesitter parsers error when installing to /usr/local/lib64

### ISSUE THREAD

**Issue by willeccles** [neovim/neovim#29680]
### Problem

CMake, by default, installs libraries to lib64 on my system. If I manually copy `/usr/local/lib64/nvim` to `/usr/local/lib`, bundled treesitter parsers work. If I don't do this, neovim can't find them. Potentially related to #27951. I do have nvim-treesitter installed, but even if I install the bundled parsers using the plugin, I still get the same error when opening a file.

### Steps to reproduce

```
make CMAKE_BUILD_TYPE=Release
sudo make install
nvim xxx.lua
```

### Expected behavior

Neovim should be able to find the parsers in the location its build system installs them to.

### Neovim version (nvim -v)

v0.10.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Void Linux

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by clason** [comment]
> CMake, by default, installs libraries to lib64 on my system.

That is very unexpected.

**Comment by willeccles** [comment]
I am still trying to figure this one out, as I see that the nvim build system installs to `lib/nvim`.

**Comment by willeccles** [comment]
I have confirmed for sure that it's not a system package--I do not have neovim installed through the PM, and `sudo rm -rf /usr/local/lib64/nvim && sudo make install` does indeed install it back to lib64.

**Comment by willeccles** [comment]
All I can find is that it's probably this: https://gitlab.kitware.com/cmake/cmake/-/blob/v3.26.4/Modules/GNUInstallDirs.cmake?ref_type=tags#L221

`build/src/nvim/cmake_install.cmake` includes the following:

```cmake
file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib64" TYPE DIRECTORY MESSAGE_NEVER FILES "/home/cactus/git/neovim/build/lib/nvim" USE_SOURCE_PERMISSIONS)
```

I also know from experience that with GNUInstallDirs in my own projects, it has also installed libraries to `lib64`.

**Comment by clason** [comment]
It's not standard, so this must be distro-specific behavior that is picked up from _somewhere_. As you use the distro (and we don't), we rely on you to help us figure this out.

**Comment by willeccles** [comment]
This is the offending snippet:
https://github.com/neovim/neovim/blob/10256bb760fcab0dc25f7eb5b0b45966cb771939/src/nvim/CMakeLists.txt#L786-L788

This is actually standard and documented in the [CMake manual](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs):

> `LIBDIR`
>     object code libraries (`lib` or `lib64`)

The source link I sent above also documents the behavior further:

```cmake
  # Override this default 'lib' with 'lib64' iff:
  #  - we are on Linux system but NOT cross-compiling
  #  - we are NOT on debian
  #  - we are NOT building for conda
  #  - we are on a 64 bits system
```

**Comment by willeccles** [comment]
Given that the build system on non-Debian Linux systems is going to do this, I think it would be wise to either force it to ignore GNUInstallDirs for this particular case (probably a bad idea) or let neovim search lib64 (either always or just on these platforms, not sure what's best/possible).

**Comment by willeccles** [comment]
Actually, here's another interesting find: `default_lib_dir` in `pathdef.h` is set to `"/usr/local/lib64/nvim"`, which I would assume means it should work, unless I am missing the point of this variable.

**Comment by clason** [comment]
The question is why this breaks on Void Linux (unlike trillions of other distros -- like openSUSE, which also uses `/usr/lib/64`).

**Comment by willeccles** [comment]
With `--clean`, it includes `lib64`, and without, it includes `lib` only. Looks like the culprit is Lazy, which by default resets your `rtp` and hard codes `lib`. This issue is definitely resolved now. Is there a way from lua to get the library path neovim was built with so that it can be used in Lazy?

**Comment by clason** [comment]
>  Is there a way from lua to get the library path neovim was built with so that it can be used in Lazy?

Yes: `vim.o.rtp`. Please raise the issue with Lazy as this is a bug in its "optimization".

**Comment by willeccles** [comment]
Working on it right now.
