### ISSUE TITLE
Cannot paste from system clipboard into search/command line

### ISSUE THREAD

**Issue by josuecau** [neovim/neovim#2969]
Pasting into command line from OS X clipboard (cmd V) does nothing.
This happens even when launching `nvim -u NONE`, and when using different terminals (iTerm2, Terminal.app).

It works fine in Vim, and it worked with previous versions of Neovim.

I use Homebrew's build, on Mac OS X Yosemite 10.10.4 (14E46):

    $ nvim --version

    NVIM 0.0.0-alpha+201507051833 (compiled Jul  6 2015 10:05:43)
    Commit: deab194413af1475f8f4d8657500c1250521059e
    Build type: RelWithDebInfo
    Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150706-8120-1ccx1hh/build/config -I/tmp/neovim20150706-8120-1ccx1hh/src -I/tmp/neovim20150706-8120-1ccx1hh/.deps/usr/include -I/tmp/neovim20150706-8120-1ccx1hh/.deps/usr/include -I/tmp/neovim20150706-8120-1ccx1hh/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150706-8120-1ccx1hh/.deps/usr/include -I/tmp/neovim20150706-8120-1ccx1hh/.deps/usr/include -I/tmp/neovim20150706-8120-1ccx1hh/.deps/usr/include -I/tmp/neovim20150706-8120-1ccx1hh/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim20150706-8120-1ccx1hh/build/src/nvim/auto -I/tmp/neovim20150706-8120-1ccx1hh/build/include
    Compiled by josh@josh.local

    Optional features included (+) or not (-): +acl   +iconv    +jemalloc
    For differences from Vim, see :help vim-differences

      system vimrc file: "$VIM/nvimrc"
        user vimrc file: "~/.nvimrc"
    2nd user vimrc file: "~/.nvim/nvimrc"
          user exrc file: "~/.exrc"
      fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"

**Comment by gs** [comment]
I found the same strange behavior  and also what I noticed I copied marked text in osx (Cmd+c)
and then being in 'insert mode' in neovim i hit Cmd+v

- text is pasted
- first letter is being capitalized
- go to visual mode

**Comment by josuecau** [comment]
@gs I confirm that I encounter the same problem of "capitalized text"

**Comment by e-kwsm** [comment]
I encounter similar problem on Debian: I hit Shift+Ins, then
1. text is pasted
2. cursor  goes to the beginning of line (```0```)
3. case of the character is switched (```~```)
4. paste mode is switched when the paste is first time since neovim starts (```:set paste/nopaste```)

My environment is as follows:
```
% cat /etc/issue.net
Debian GNU/Linux 8
% nvim --version
NVIM 0.0.0-alpha+201507060407 (compiled Jul  6 2015 20:33:37)
Commit: 1b78ad1c4d1533fe3089b9744a5306616e562f3e
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/kwsm/.src/neovim/build/config -I/home/kwsm/.src/neovim/src -I/home/kwsm/.src/neovim/.deps/usr/include -I/home/kwsm/.src/neovim/.deps/usr/include -I/home/kwsm/.src/neovim/.deps/usr/include/luajit-2.0 -I/home/kwsm/.src/neovim/.deps/usr/include -I/home/kwsm/.src/neovim/.deps/usr/include -I/home/kwsm/.src/neovim/.deps/usr/include -I/home/kwsm/.src/neovim/.deps/usr/include -I/usr/include -I/home/kwsm/.src/neovim/build/src/nvim/auto -I/home/kwsm/.src/neovim/build/include
Compiled by kwsm@local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/neovim/share/nvim"


```

**Comment by xHN35RQ** [comment]
I also have this bug, without the capitalization. Paste mode is switched on the first time I use `Ctrl+Shift=v` or `Shift-Ins` However, I have no bug using `p` to paste with `set clipboard^=unnamedplus`

```
NVIM 0.0.0-alpha (compiled Jul  5 2015 20:37:52)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-E9U1xX/neovim-0.0.0+git201507050731+1732+10~ubuntu14.04.1/build/config -I/build/neovim-E9U1xX/neovim-0.0.0+git201507050731+1732+10~ubuntu14.04.1/src -I/build/neovim-E9U1xX/neovim-0.0.0+git201507050731+1732+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-E9U1xX/neovim-0.0.0+git201507050731+1732+10~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-E9U1xX/neovim-0.0.0+git201507050731+1732+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-E9U1xX/neovim-0.0.0+git201507050731+1732+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-E9U1xX/neovim-0.0.0+git201507050731+1732+10~ubuntu14.04.1/.deps/usr/include -I/build/neovim-E9U1xX/neovim-0.0.0+git201507050731+1732+10~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-E9U1xX/neovim-0.0.0+git201507050731+1732+10~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-E9U1xX/neovim-0.0.0+git201507050731+1732+10~ubuntu14.04.1/build/include
Compiled by buildd@lgw01-16

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by rainkinz** [comment]
Same thing here: OSX, iterm2:

text is pasted
first letter is being capitalized
go to visual mode

**Comment by renstrom** [comment]
Try completely wiping your current neovim installation along with cache folders like `/Library/Caches/Homebrew/`on OS X and build it all from scratch. I had another paste issue that caused Nvim to remain in paste mode after inserting stuff from the system clipboard using <kbd>cmd</kbd>-<kbd>v</kbd>. I solved it with:

```bash
$ brew uninstall neovim
$ brew cleanup
$ brew prune
$ rm -rf /Library/Caches/Homebrew
$ brew install --HEAD neovim
```

**Comment by josuecau** [comment]
@renstrom This workaround seems to work. Thanks!

**Comment by rainkinz** [comment]
@renstrom worked for me too! Thanks!

**Comment by fwalch** [comment]
This might be because https://github.com/neovim/neovim/commit/b165145084ab2cf5671af07944bc8b353c21ef95 got merged in the meantime.

**Comment by dixius99** [comment]
Had this issue, and it was fixed by only doing `brew reinstall --HEAD neovim` today.

**Comment by xHN35RQ** [comment]
Yep, I can report that https://github.com/neovim/neovim/commit/b165145084ab2cf5671af07944bc8b353c21ef95 fixed this for me. Update or rebuild your neovim if you still have this issue.

**Comment by gs** [comment]
great! thx for solving it fast!
