### ISSUE TITLE
Chained wincmd args

### ISSUE THREAD

**Issue by boriselec** [neovim/neovim#29706]
### Problem

I have something like the following in my .vimrc:

wincmd w
wincmd J
wincmd L
wincmd W

I thought it would be useful to rewrite it as:

wincmd wJLW

### Expected behavior

wincmd wJLW works just as 

wincmd w
wincmd J
wincmd L
wincmd W

**Comment by zeertzjq** [comment]
What should happen if a count is specified then?

**Comment by boriselec** [comment]
Whole sequence got repeated, i think

**Comment by LunarLambda** [comment]
You can combine multiple `wincmd`s on a single line using `|`: e.g. `wincmd H | wincmd 80 |` moves the window to the left-most position and resizes it to 80 columns.

**Comment by justinmk** [comment]
> You can combine multiple `wincmd`s on a single line using `|`: e.g. `wincmd H | wincmd 80 |` moves the window to the left-most position and resizes it to 80 columns.

Yes, we should not implement another quasi DSL for `wincmd`.

However, "piping" output from one command to another would be very interesting (perhaps as an ergonomic Lua library rather than extending Vimscript syntax).
