### ISSUE TITLE
Holding the down arrow key until after the end of the file swaps the current buffer

### ISSUE THREAD

**Issue by philix** [neovim/neovim#2970]
I updated Neovim today and it has this weird behaviour where the buffer gets swapped if I hold the arrow key (or 'j') until the end of the file.

It seems very random and hard to reproduce, but anyone who changed code related to motions recently may have an idea of what's the problem.

**Comment by philix** [comment]
If the buffer is unsaved I see the `E37: No write since last change` error message.

**Comment by lucc** [comment]
This might be related to #2936. When using the scroll wheel very fast I also had random buffer switches.  Can you check the fix proposed there?

**Comment by philix** [comment]
@lucc oni-link's patch fixes it. Thanks! I'll close this since there's already a fix on the way.
