### ISSUE TITLE
Are there any plans to support tabline?

### ISSUE THREAD

**Issue by SadSock** [neovim/neovim#29703]
### Problem

Switching buffers through tabline is very intuitive, for a modern editor this seems to have become a essential feature.

This feature would be better implemented out of the box rather than as a plugin, after all, Neovim's usage scenarios are often without network access

### Expected behavior

![图片](https://github.com/user-attachments/assets/0271a04c-be1b-4533-bcd2-c6134b14e424)

**Comment by lewis6991** [comment]
No.
