### ISSUE TITLE
Python command for "default Python interpreter"

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2971]
I often want to use the default Python version, e.g. when in an virtualenv, which would correspond to calling `python` in the shell, but Vim's `:python` would use Python 2 always.

Therefore it would be nice if Neovim would provide such a wrapper.

If it wasn't for backward compatibility with Vim, I'd say that `:python` could provide this, while `:python2` and `:python3` could be used to call an explicit version.

**Comment by fwalch** [comment]
"default Python" == "the `:python`/`:python3` command that corresponds with the version of `python` that is in `$PATH`?

**Comment by ZyX-I** [comment]
Vim and NeoVim currently use python2/3/x for directory names. I suggest that if somebody needs using “default python” always it should either be an option (I do not think this is a good idea because plugin do not expect this) or `:pythonx`/`:pyx` command thus.

**Comment by fwalch** [comment]
When using "default python", you wouldn't even know if you're now using Python 2 or Python 3, let alone what modules are available. I don't really understand how that would be useful, can you explain a bit more?

**Comment by ZyX-I** [comment]
@fwalch There is a huge set of modules which are written to work on both python versions. E.g. check out powerline sources: it works on 2.6-… and 3.2-…, also PyPy and PyPy3 (even though differences are not too big, there are some).

I think this should be useful for plugins written in this fashion: in place of using `:execute` and checking `:if has('python3')` just blindly use `:pythonx`.

**Comment by ZyX-I** [comment]
@fwalch In fact, the situation around python-3 created new pseudo-language python-23: in many cases this is better solution then 2to3.

**Comment by blueyed** [comment]
`:pythonx` / `:pyx` would be a good candidate for this.

My use case is that I just want to use the default Python (from the `python` executable in the PATH).
I am using pyenv and Python's virtualenvs to manage this for projects and the default one, and in my Vim config I would then like to access the effective/default Python for the current env.

The usual `has('python3')` check does not really help here, but I would have to shell out to `python -V` (or similar) to see if I need to `:exec` `py2` or `py3`.

**Comment by bfredl** [comment]
Another usecase is also if a plugin is dual version compatible it should just work if only one of the hosts are available, no matter which.
The same question arise also for rplugins, perhaps a plugin placed in `rplugin/pythonx` should behave similarly ?

**Comment by blueyed** [comment]
@bfredl 
What is an "rplugin"?

**Comment by bfredl** [comment]
A plugin using the remote plugin infrastructure, like [nvim-ipy](https://github.com/bfredl/nvim-ipy) and [deoplete](https://github.com/shougo/deoplete.nvim) .

**Comment by justinmk** [comment]
Vim is working on a `:pythonx` command which we'll merge when it lands.

**Comment by mgedmin** [comment]
Vim added `:pythonx` and `pyxeval()` back in 2017 (vim 8.0.0251).  Will neovim add these?

I ask because 

> Vim is working on a :pythonx command which we'll merge when it lands.

but I just built neovim git master and it doesn't seem to have a `pyxeval()`.
