### ISSUE TITLE
Lines wrap into sign column

### ISSUE THREAD

**Issue by fionn** [neovim/neovim#29711]
### Problem

When the sign column is set, scrolling through text with long lines causes the lines to occasionally wrap incorrectly, where the first character of the word that should be on the next line is still visible on the same line, and the next line appears in the sign column (and number column, if enabled).

### Steps to reproduce

Set the terminal to be reasonably narrow.
```
nvim --clean lorem.txt
:set signcolumn=yes
:set number        # optional, but if unset you must set signcolumn to yes:3 or similar
:set smoothscroll  # optional but makes reproducing the bug easier
```
Scroll up and down a couple of times.

If on Linux, I need to additionally set `linebreak` and `smoothscroll` is not optional.

### Expected behavior

Text does not bleed over semi-randomly into the sign column.

### Neovim version (nvim -v)

v0.11.0-dev-414+g49ba36bec

### Vim (not Nvim) behaves the same?

No, 9.1

### Operating system/version

macOS 14.5

### Terminal name/version

iTerm2 3.5.3 and Alacritty 0.13.2 (1)

### $TERM environment variable

`xterm-256color` and `alacritty`

### Installation

Homebrew

**Comment by zeertzjq** [comment]
1. What does `:set lines? columns?` print?
2. What is the content of lorum.txt?

**Comment by fionn** [comment]
1. Anything that causes enough line brakes. I can specifically reproduce this with a terminal width of 70 characters (`columns` is 70, `lines` is 46).
2. Lorem Ipsum text (attached: [`lorem.txt`](https://github.com/user-attachments/files/16230929/lorem.txt)).
3. Mouse wheel / trackpad.

Minimal reproduction configuration on macOS with both the Homebrew build and the latest nightly build using above column and line lengths.
```lua
vim.opt.signcolumn = "yes:3"
vim.opt.smoothscroll = true  -- Optional but improves reproducibility
```
Demonstration of bad wrapping (macOS, iTerm2): https://asciinema.org/a/J26B3ZRCI06vvYW0JAnqjzarh.

I can also reproduce this on Linux (Arch) using Alacritty and Terminator by additionally setting `linebreak`, which _seems_ to be the same bug.

**Comment by fionn** [comment]
Just built from `master` and can happily confirm that I can no longer reproduce this.

Thank you for your work on Neovim.
