### ISSUE TITLE
Treesitte error in Rust with `:InspectTree` but not with `:TSPlayground`

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#29726]
### Problem

When I execute `:InspectTree` on the attached Rust file I get errors, but there are no errors with `TSPlayground` from nvim-treesitter.

[regular.txt](https://github.com/user-attachments/files/16239154/regular.txt) (change the file extension to `rs`; I had to rename it because of GitHub rules)

I don't know Rust myself, so maybe there is something wrong with the source code or the parser. The reason I am reporting here is because of the discrepancy in errors between the two commands. The file is from [HiPhish/rainbow-delimiters.nvim](https://github.com/hiphish/rainbow-delimiters.nvim).

### Steps to reproduce

1. Open the file in Neovim
2. Execute `:InspectTree`

### Expected behavior

No errors in `:InspectTree`

### Neovim version (nvim -v)

Both `NVIM v0.10.0` and `NVIM v0.11.0-dev-422+g3c803483a`

### Vim (not Nvim) behaves the same?

no applicable

### Operating system/version

Void Linux

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

AppImage

**Comment by clason** [comment]
TSPlayground is archived for a reason, and error nodes are returned by the parser itself. So unless demonstrated otherwise (by a full reproducing example) the difference has to be assumed due to different parser commits. The best place to report this would be the tree-sitter-rust repo (using tree-sitter parse output).

**Comment by HiPhish** [comment]
> So unless demonstrated otherwise (by a full reproducing example) the difference has to be assumed due to different parser commits.

Aren't both commands using the same parser that was installed via `:TSInstall rust` to get the tree?

**Comment by clason** [comment]
Unclear, without details.

**Comment by HiPhish** [comment]
OK, I just tried it with a clean setup, only nvim-treesitter installed (manually, no package manager) to download and install the Rust parser. I get the exact same errors: [tree.txt](https://github.com/user-attachments/files/16240406/tree.txt). No errors with `TSPlaygroundToggle`: [playground.txt](https://github.com/user-attachments/files/16240427/playground.txt)

**Comment by clason** [comment]
Can you post the parsed trees here? (Try minimizing the example.) Also test `tree-sitter parse`.

**Comment by clason** [comment]
I think what's happening here is that TSPlayground never handled injections correctly. In any case, any nodes (including errors) that are shown _are_ in the tree, so there's no bug here.
