### ISSUE TITLE
fixendofline not working on macOS

### ISSUE THREAD

**Issue by multi-io** [neovim/neovim#29728]
### Problem

Just what the title says. Writing `vim.opt.fixendofline = false` into init.lua has no effect. Neither does running `:set nofixendofline` or `:lua vim.opt.fixendofline = false` interactively. It just always adds a newline at the end of a file being saved.

On Linux, everything works as expected.

### Steps to reproduce

On macOS, start with an an empty init.lua, add just `vim.opt.fixendofline = false`. Create a test file, e.g. with `printf 'foo\nbar' >foo`. Confirm, e.g. with cat or hexdump, that the file doesn't end in a newline. Open it in nvim, `:wq`. Now foo does end in a newline. Running `:set nofixendofline` or `:lua vim.opt.fixendofline = false` interactively doesn't change this behaviour either. Tested with v0.9.4 as well as with the current master (v0.11.0-dev-422+g3c803483a / LuaJIT 2.1.1720049189) on macOS.

### Expected behavior

File should not end in a newline if it didn't before saving, and none was added manually.

### Neovim version (nvim -v)

v0.11.0-dev-422+g3c803483a

### Vim (not Nvim) behaves the same?

no, 9.0

### Operating system/version

macOs 14.4.1

### Terminal name/version

iterm2

### $TERM environment variable

xterm-256color

### Installation

downloaded master release binary from https://github.com/neovim/neovim/releases/nightly

**Comment by zeertzjq** [comment]
Do you have a .editorconfig file?

**Comment by multi-io** [comment]
> Do you have a .editorconfig file?

I didn't even know what that is but -- turns out YES I do, and that explains it. Sorry, I should've tested this in another directory. I'm closing the ticket. Thanks again.
