### ISSUE TITLE
inconsistent TSNode:range().end_row inclusiveness 

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#29762]
### Problem

in lua files, i see `chunk`.end_row is exclusive, while all other nodes are inclusive.

### Steps to reproduce

* test.lua
```
local x = {
  1
}
```
* nvim --clean -u NONE test.lua
* `:lua vim.treesitter.inspect_tree()` # to spot the problem easier
* seeing
![0fa0768c-43f0-11ef-99d3-54b203702c9c](https://github.com/user-attachments/assets/4ca9a7c2-d64e-4a17-975b-3a654ee5caf8)

### Expected behavior

the node:range().end_row should always be inclusive. in above case, the end_row and end_col should be `2`, `1` respectively.

i have not tested other parsers, so i'm not sure if it's a problem brought by the lua parser, nonetheless i really dont know where to report except here. i do feel nvim has the responsibility to be strict on this.

### Neovim version (nvim -v)

nvim 0.10

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

st-256color

### Installation

pacman

**Comment by haolian9** [comment]
i also noticed nvim knows that already, and deals with it [in this way](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/treesitter.lua#L190-L197) in vim.treesitter.get_node_text.
and i tested python parser, it behaves the same.

**Comment by lewis6991** [comment]
Pretty sure this is because of the parser. End row is inclusive and end col is exclusive.
