### ISSUE TITLE
Verify that $VIMRUNTIME/$VIM points to Neovim runtime.

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2977]
Adapted from https://github.com/neovim/neovim/pull/1927#issuecomment-95791503:

> Do a sanity check on VIMRUNTIME and show a warning.
> We can trivially detect whether VIMRUNTIME is valid by looking for script(s) that only exist in Neovim.

First implementation suggestion: https://github.com/neovim/neovim/pull/1927#issuecomment-96108014

There has been quite a lot of confusion/reported issues because of this (at least that's my feeling), so I put it in the 0.1 milestone. Feel free to change.

_Edit:_ Hm, this issue is already listed in #1202.. but since #1202 also contains other stuff and is not assigned to a milestone, I'm keeping this open for now.

**Comment by janlazo** [comment]
Does resolving this issue allow Vim and Neovim to coexist, using the same environment variables (handled by the editor in runtime), without using `env`, aliases, or shell scripts?

I resorted to batch files in Windows for Vim 8 and Neovim 1.6+.

**Comment by justinmk** [comment]
@janlazo No, resolving this issue only avoids confusion. Why are you setting VIMRUNTIME? Even the Vim docs mention that it is not recommended, it's meant to be set by n/vim automatically.

**Comment by janlazo** [comment]
@justinmk It doesn't always set VIMRUNTIME correctly in Windows such that my configs don't load. Neovim may use Vim's runtime directory as well. I use both together and often (Neovim for performance and neovim-only plugins, Vim in terminal) so I'd restart either of them to hope that it loads correctly or I  use Notepad++ instead.

Which one should I set, if not VIMRUNTIME? VIM?
If not, should I use an alias and command line arguments instead?
Note that I encounter this only in Windows. I haven't experienced this in Ubuntu so far.

**Comment by justinmk** [comment]
You could set it in vimrc instead of environment. 

> doesn't always set VIMRUNTIME correctly in Windows 

Can you open an issue with more details?

**Comment by janlazo** [comment]
@justinmk I remember now. In Windows, I configured VIM to point to Vim's runtime directory because it's also the root folder for its executables (at least when using the installer for gViim in Windows). I used VIM so I can configure the PATH variable via environment variables because changing absolute filepaths in PATH for cmd.exe in Windows is a PITA. Since Neovim uses the same environment variables (VIM, VIMRUNTIME) and VIM is explicitly set, Neovim will use Vim's runtime directory to set VIMRUNTIME.

I suppose that the solution is to not set VIM and VIMRUNTIME for both Vim/Neovim.

**Comment by justinmk** [comment]
> I suppose that the solution is to not set VIM and VIMRUNTIME for both Vim/Neovim.

Right. Can you set it in your vimrc (at the top) instead?

**Comment by janlazo** [comment]
- It has to be set in runtime since shell scripts may have side-effects on environment variables
- it must happen at the top or before any vimrc is loaded
- support `-u path/to/vimrc`, including NONE and NORC

Only option is to use a separate vim script and source it via `--cmd`.

**Comment by justinmk** [comment]
> in Windows, it can handle Vim (any path), Neovim (any path), Cygwin, and any other POSIX-like environment because setting VIM globally affects all of them

It's not "handling" it, instead it causes the problem you described. And it's not correct anyways, because cygwin vim may be a completely different version of Vim (not Nvim...) which doesn't support runtime files etc from newer versions of Vim.

**Comment by janlazo** [comment]
Yes, but those bullet points were meant to be justifications for handling Vim's environment variables in a vim script, say `env_vars.vim`, such that `vim --cmd "source env_vars.vim"` should fix my issue instead of using batch files.
