### ISSUE TITLE
OSC 52 is enabled in tmux+nvim but does not work

### ISSUE THREAD

**Issue by lifei** [neovim/neovim#29788]
### Problem

OSC 52 works fine in tmux but break in nvim+tmux.

### Steps to reproduce

1. Open WezTerm and use `ssh` to connect to the remote server named t001.
2. Open `tmux` and print some words.
3. Use mouse to select some words and press `command+v` to test if osc 52 works in tmux. and it works fine.
4. Open nvim in tmux, enter some words, then press `"+y`.  and what i got is `Waiting for OSC 52 response from the terminal. Press Ctrl-C to interrupt...` and `a clipboard response timeout error`.
5. when i just press `"`, i get a tip below which i think it's useful for debugging.

```
* ➜  OSC 52 detected, register not checked to maintain compatibility                                  synchronized with the selection clipboard
+ ➜  OSC 52 detected, register not checked to maintain compatibility                                  synchronized with the system clipboard
```

about settings

`set clipboard` shows `clipboard=`
`let g:clipboard` shows `g:clipboard           {'paste': {'*': function('<lambda>4'), '+': function('<lambda>3')}, 'name': 'OSC 52', 'copy': {'*': function('<lambda>2'), '+': function('<lambda>1')}}`

### Expected behavior

osc 52 works fine in nvim+tux.

### Neovim version (nvim -v)

v0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu 22.04

### Terminal name/version

wezterm 20230712-072601-f4abf8fd

### $TERM environment variable

screen-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
WezTerm doesn't support OSC 52 pasting: https://github.com/wez/wezterm/issues/2050
