### ISSUE TITLE
The results of virtcol2col in Nvim 0.10 and Nvim 0.9.5 are inconsistent

### ISSUE THREAD

**Issue by xiyaowong** [neovim/neovim#29786]
### Problem

The results of virtcol2col in Nvim 0.10 and Nvim 0.9.5 are inconsistent

### Steps to reproduce

1. `nvim --clean test.lua`:
```lua
---你好

print(vim.fn.virtcol2col(0, 1, 3))
print(vim.fn.virtcol2col(0, 1, 4))
print(vim.fn.virtcol2col(0, 1, 5))
print(vim.fn.virtcol2col(0, 1, 6))
```
2. Run `:luafile %`

- Nvim 0.9.5, the output is:
```
3
6
6
9
```
- Nvim 0.10.0, the output is:
```
3
4
4
7
```

### Expected behavior

I'm not sure if this is an "intended" change. But I think the result of Nvim 0.9.5 is correct.

### Neovim version (nvim -v)

NVIM v0.10.0    NVIM v0.9.5  Release

### Vim (not Nvim) behaves the same?

Not sure

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal

### $TERM environment variable

-

### Installation

Scoop

**Comment by dundargoc** [comment]
Bisected to a245dd79a267c8b56866023e84b49d0ecffca65b. Unsure which is the correct behavior.

**Comment by zeertzjq** [comment]
The new behavior is correct.

**Comment by xiyaowong** [comment]
The change made it counterintuitive...

https://github.com/user-attachments/assets/601c168d-f9c1-45c9-8552-81c5f62da728

**Comment by zeertzjq** [comment]
How is it counterintuitive? What are you trying to prove with the video?

**Comment by xiyaowong** [comment]
I have simplified my use case.

```test.lua
--------
---你好
--------

vim.o.showmode = false
local fn, api = vim.fn, vim.api
api.nvim_create_autocmd({ "CursorMoved" }, {
  group = api.nvim_create_augroup("test", { clear = true }),
  callback = function()
    local mode = api.nvim_get_mode().mode
    if mode ~= "\x16" then
      return
    end
    local start_vcol = fn.virtcol("v")
    local end_vcol = fn.virtcol(".")
    local start_col = fn.virtcol2col(0, 2, start_vcol)
    local end_col = fn.virtcol2col(0, 2, end_vcol)
    -- print(start_col, end_col)
    print("selected", api.nvim_buf_get_text(0, 1, start_col - 1, 1, end_col, {})[1] or "")
  end,
})
```


https://github.com/user-attachments/assets/9f77627b-2ec5-481f-b221-da2d8be7c755

**Comment by zeertzjq** [comment]
I don't see how the new behavior is more counterintuitive than the old one. If you have a multibyte char at the start of the selection, the old behavior will only include its last byte.
