### ISSUE TITLE
HTML treesitter make neovim crash.

### ISSUE THREAD

**Issue by j0ng4b** [neovim/neovim#29804]
### Problem

When I try to edit any html file with treesitter enabled, neovim closes with exit code 139. If I disable highlight and indent the neovim no more close when do something, but still close suddenly maybe due plugins interaction with treesitter (e.g. tailwind-fold.nvim).

### Steps to reproduce

Edit html file `nvim test.html` with treesitter enabled.

### Expected behavior

Edit the file without crash.

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: None LuaJIT 2.1.0-beta3 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

no, neovim only

### Operating system/version

Void Linux

### Terminal name/version

foot version: 1.17.2 -pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Installation

From Void  repo using system package manager.

**Comment by clason** [comment]
Please report that (with the _exact_ reproducing file/edit) at tree-sitter-html.
