### ISSUE TITLE
Angular template filetype detection

### ISSUE THREAD

**Issue by Ask-786** [neovim/neovim#29808]
### Problem

Currently we are checking this condition for angular filetype detection, 

```lua
    if
      matchregex(
        line,
        [[@\(if\|for\|defer\|switch\)\|\*\(ngIf\|ngFor\|ngSwitch\|ngTemplateOutlet\)\|ng-template\|ng-content\|{{.*}}]]
      )
    then
      return 'htmlangular'

```

The problem with this is when this condition fails, even if the html file is a file from an angular repo, file type sets to `html`. so the angular specific syntax highlights doesn't work (the treesitter parser coupled with `htmlangular` filetype).

is there anything we can do for this issue, like including an `or` case that checking if root_dir contains angular.json?

### Steps to reproduce

- install angular cli - `npm i -g @angular/cli`
- create a new angular project - `ng new test`
- `cd test`
- open neovim in the directory `nvim .`
- open `app.component.html`
- replace the contents with just 
  ```html
  <div>Hello world!!</div>
  ```
- reopen the same file
- check filetype -  `:set filetype?`

### Expected behavior

The filetype should be `htmlangular` instead of `html`

### Neovim version (nvim -v)

NVIM v0.11.0-dev-465+gc69ea53c9

### Vim (not Nvim) behaves the same?

don't know

### Operating system/version

ubuntu 22.04

### Terminal name/version

alacritty

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by Ask-786** [comment]
```lua
  if vim.fn.findfile('angular.json', vim.fn.getcwd() .. ';') ~= '' then
    return 'htmlangular'
  end
```

This seems to work I think.

**Comment by clason** [comment]
This logic is owned by Vim, so please open the issue (or preferably a PR) there.
