### ISSUE TITLE
cursor "follow changes" behavior is inconsistent after :startinsert

### ISSUE THREAD

**Issue by max397574** [neovim/neovim#29811]
### Problem

When a function which using `apply_text_edits` from lsp utils is called in a keymapping the cursor isn't positioned correctly. This isn't the case when calling it otherwise.

### Steps to reproduce

```lua
-- file: repro.lua
local function setup()
    vim.api.nvim_buf_set_lines(0, 0, 0, false, { "test" })
    vim.api.nvim_win_set_cursor(0, { 1, 4 })
    vim.cmd.startinsert({ bang = true })
end
local function test_text_edit()
    vim.lsp.util.apply_text_edits({
        {
            newText = "new test text",
            range = {
                ["end"] = {
                    character = 4,
                    line = 0,
                },
                start = {
                    character = 0,
                    line = 0,
                },
            },
        },
    }, vim.api.nvim_get_current_buf(), "utf-16")
end
setup()
vim.keymap.set("i", "<cr>", function()
    test_text_edit()
end)
test_text_edit()
```

1. `nvim --clean repro.lua`
2. `:so`
3. delete line, comment last line
4. `:so`
5. `<cr>`
See the different behavior

https://github.com/user-attachments/assets/c2334f75-7126-40be-80ce-29e5f8fe8ae1

### Expected behavior

the cursor should be at the same column in both cases

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

not relevant

### Operating system/version

macOS 14.5

### Terminal name/version

Kitty

### $TERM environment variable

xterm-kitty

### Installation

bob

**Comment by justinmk** [comment]
`apply_text_edits()`, no matter how it's called (e.g. manually via `<C-O>:lua test_text_edit()<CR>`), generally does not move the cursor. So it seems like the anomaly is rather the first half of your repro steps, where the cursor *does* follow the text edit.

To confirm this, change `vim.cmd.startinsert({ bang = true })` to `vim.cmd[[norm! A]]`. OTOH, `vim.cmd[[norm! Azz]]` again has the "follow" behavior...

**Comment by zeertzjq** [comment]
`:h :startinsert`
