### ISSUE TITLE
[Treesitter] Detecting injected languages in headless Neovim instance fails

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#29819]
### Problem

I have a buffer with injected languages (e.g. Lua with injected Vim script) and I would like to detect this fact automatically. Normally I can evaluate `vim.tbl_keys(vim.treesitter.get_parser():children())` to get a list of children, but this fails if I am evaluating that code in a headless instance.

To provide some context, I am trying to automate testing in [HiPhish/rainbow-delimiters.nvim](https://github.com/hiphish/rainbow-delimiters.nvim). Currently I have a bunch of sample files, and I want to record all delimiter extmarks in a JSON file. To do this I open each sample file in a separate Neovim process and get all extmarks which belong to the namespace of my plugin. However, each language has its own namespace, so I need a list of languages first.

### Steps to reproduce

Take the following Lua file:

```lua
print('Hello from Lua!')
vim.cmd [[
	echo 'Hello from Vim!'
]]
```

Open it up in Neovim, execute `lua =vim.tbl_keys(vim.treesitter.get_parser():children())` and you get `{'vim'}` as expected.

Now take the following Lua script and `:source %` it:

```lua
local jobopts = {rpc = true, width = 80, height = 40}
local command = {'nvim', '--embed', '--headless'}
local jobid = vim.fn.jobstart(command, jobopts)
vim.rpcrequest(jobid, 'nvim_cmd', {cmd = 'edit', args = {'derp.lua'}}, {})
local children = vim.rpcrequest(jobid, 'nvim_exec_lua', 'return vim.tbl_keys(vim.treesitter.get_parser():children())', {})
vim.rpcnotify(jobid, 'nvim_cmd', {cmd = 'quitall', bang = true}, {})

print(vim.inspect(children))
```

The result is `{}`. The script will start an embedded Neovim process, open the Lua file and ask it for a list of child parsers.

### Expected behavior

The script should also print `{'vim'}`.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Void Linux

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

Void packages.

**Comment by clason** [comment]
Also print the full rtp -- the parsers need to be available, of course.

**Comment by clason** [comment]
You need to make sure that the tree is parsed first (an active highlighter will do that for you, but you should never assume that -- if you're running headless, obviously no syntax highlighting will happen).

**Comment by HiPhish** [comment]
> You need to make sure that the tree is parsed first

Thank you so much! Here is the updated script which works:

```lua
local jobopts = {rpc = true, width = 80, height = 40}
local command = {'nvim', '--embed', '--headless'}
local jobid = vim.fn.jobstart(command, jobopts)
vim.rpcrequest(jobid, 'nvim_cmd', {cmd = 'edit', args = {'derp.lua'}}, {})
-- Changes begin here
vim.rpcrequest(jobid, 'nvim_exec_lua', 'parser = vim.treesitter.get_parser()', {})
vim.rpcrequest(jobid, 'nvim_exec_lua', 'parser:parse(true)', {})
local children = vim.rpcrequest(jobid, 'nvim_exec_lua', 'return vim.tbl_keys(parser:children())', {})
-- Changes end here
vim.rpcnotify(jobid, 'nvim_cmd', {cmd = 'quitall', bang = true}, {})

print(vim.inspect(children))
```
