### ISSUE TITLE
CTRL-W waits for confirmation if remapped to a custom action.

### ISSUE THREAD

**Issue by geneotech** [neovim/neovim#29812]
### Problem

Happens both on the latest stable release and ``master``.
I use Ctrl+W to close the current tab (but happens with any other action too), and it just shows ^W in the right bottom corner as if it's waiting for another key. I have to press Enter or Esc to confirm my intent.
 
![image](https://github.com/user-attachments/assets/3c5c59de-ec2d-4bf1-8dc5-ab9103f9a874)

This doesn't happen if I map the identical action to say CTRL+O instead.
Unmapping with ``nunmap <C-w>`` or ``nnoremap <C-w> <Nop>`` first doesn't work either.

This worked as expected in ``0.9.5-5`` as this is the last version I used before the entire system upgrade on Arch Linux.

### Steps to reproduce

```
nvim --clean
:e foo

:nnoremap <C-w> :echo "test"<CR>
:nnoremap <C-o> :echo "test"<CR>
```

Now Ctrl+o will correctly echo "test" instantly,
whereas Ctrl+w will wait for Enter or Esc to display "test".
Note the two commands only differ by the bound key.

### Expected behavior

CTRL+w should not wait for a confirmation and execute the custom mapped action immediately.

### Neovim version (nvim -v)

v0.11.0-dev-475+g5fc25ecc7

### Vim (not Nvim) behaves the same?

no, vim 9.1.0532-1 behaves as expected

### Operating system/version

6.9.9-arch1-1

### Terminal name/version

Alacritty

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
`:h default-mapppings`
`:h :map-nowait`

**Comment by geneotech** [comment]
Thank you so much for your prompt response! That's a lifesaver :tada:
