### ISSUE TITLE
Autocommand `FileType` called twice for Treesitter query files

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#29829]
### Problem

I don't know if this is a real bug or expected behaviour, but it has thrown me off quite a bit. Since Scheme and Treesitter queries share the same file extension `.scm` the `FileType` autocommand gets fired twice (once per file type), even if there is a modeline that sets the file type explicitly.

The reason this threw me off is because the callback function happens to raise and error for Scheme, but not for Treesitter queries. This would not be an issue because I never expected the file type to be Scheme. The best I can do is silently ignore errors in the callback, but this might come back to haunt me in the future if there happens to be an error after the file type settles.

### Steps to reproduce

Take the following query file:

```
(foo (bar (baz)) @bar) @foo

;;; vim:ft=query
```

In my `init.lua` I have the following code:

```lua
local function on_file_type(_args)
	print(vim.inspect(_args))
end

vim.api.nvim_create_autocmd('FileType', {pattern = '*', callback = on_file_type})
```

The callback function gets called twice:

```
{
  buf = 1,
  event = "FileType",
  file = "test/highlight/samples/query/regular.scm",
  id = 8,
  match = "scheme"
}

{
  buf = 1,
  event = "FileType",
  file = "test/highlight/samples/query/regular.scm",
  id = 8,
  match = "query"
}
```

### Expected behavior

The autocommand should be fired only once after the file type has settled, at least if there is a modeline which explicitly sets the file type.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Void Linux

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

Void packages

**Comment by clason** [comment]
Yes, that is expected. The builtin filetype detection (correctly) detects this as a scheme file; then the modeline overrides this as a query.
