### ISSUE TITLE
nvim_buf_get_extmarks has wrong return value annotation

### ISSUE THREAD

**Issue by viocost** [neovim/neovim#29828]
### Problem

The `nvim_buf_get_extmarks` API used to return extmark id for each found extmark, however now it doesn't, so there is no way to identify returned extmark.

Details also don't contain extmark id.
It would be nice to add extmark id to details for each extmark

### Expected behavior

extmark id is included in the return

**Comment by zeertzjq** [comment]
Please read the documentation.
```
    Return: ~
        List of `[extmark_id, row, col]` tuples in "traversal order".
```

**Comment by viocost** [comment]
@zeertzjq  it does not behave this way: https://github.com/neovim/neovim/blob/7381f0a1d517474dcf8d8d019cbda430ce4bff23/runtime/lua/vim/_meta/api_keysets_extra.lua#L46

**Comment by zeertzjq** [comment]
It does.
