### ISSUE TITLE
`'` mark gets restored automatically after nvim_buf_del_mark

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#29820]
### Problem

in the following snippet, i deleted the `'` mark after floatwin created, but soon it gets restored automatically. i think i'm doing nothing wrong, so i feel it's a bug.

### Steps to reproduce

* test.lua # i added many assertions.
```
local api = vim.api

do
  api.nvim_feedkeys("gg3lm'", "nx", false)
  local pos = api.nvim_buf_get_mark(0, "'")
  vim.print(pos)
  assert(pos[1] == 1 and pos[2] == 3)
end

local bufnr = api.nvim_create_buf(false, true)
local winid = api.nvim_open_win(bufnr, true, { relative = "cursor", width = 5, height = 5, col = 0, row = 0 })

do
  assert(api.nvim_get_current_win() == winid)
  assert(api.nvim_get_current_buf() == bufnr)
  assert(api.nvim_buf_set_mark(bufnr, "'", 0, 0, {}))
  -- assert(api.nvim_buf_del_mark(bufnr, "'"))
  local pos = api.nvim_buf_get_mark(bufnr, "'")
  assert(pos[1] == 0 and pos[2] == 0)
  vim.print(pos)
end

vim.defer_fn(function()
  assert(api.nvim_get_current_win() == winid)
  assert(api.nvim_get_current_buf() == bufnr)
  local pos = api.nvim_buf_get_mark(bufnr, "'")
  vim.print(pos)
end, 3000)
```
* `$ nvim --clean -u NONE test.lua`
* `:so`
* seeing
```
{ 1, 3 }
{ 0, 0 }
{ 1, 3 }
```

### Expected behavior

the deleted `'` mark does not get restored

### Neovim version (nvim -v)

nvim 0.10

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9.2

### $TERM environment variable

st-256color

### Installation

pacman

**Comment by zeertzjq** [comment]
What should be printed with the expected behavior?

**Comment by haolian9** [comment]
ah, sorry, the full output is:
```
{ 1, 3 }
{ 0, 0 }
{ 1, 3 }
```
i had not include the last print.

**Comment by haolian9** [comment]
i think the last one which is print by vim.defer_fn should remain `{0, 0}`

**Comment by justinmk** [comment]
From `:help :delmarks`:

> You cannot delete the ' mark.
