### ISSUE TITLE
Syntax highlighting for plant uml

### ISSUE THREAD

**Issue by colbs255** [neovim/neovim#29830]
### Problem

The default experience of editing [plant uml](https://plantuml.com/) files in neovim is not great since it doesn't have syntax highlighting for it.

### Expected behavior

When editing a plant uml file (.puml), basic syntax highlighting should be enabled (similar to more common languages like C and python)

**Comment by clason** [comment]
Someone has to write a syntax file and make a PR to vim/vim; we will then port it.
