### ISSUE TITLE
Completion popup/preview syntax highlighting

### ISSUE THREAD

**Issue by leath-dub** [neovim/neovim#29849]
### Problem

When you set `completeopt` to have `popup` you get an overlay ui popup from the some lsp servers, however unlike the signature help which has syntax highlighting since (https://github.com/neovim/neovim/pull/25073), there is no syntax highlighting. The same is true for `preview` buffer.

### Expected behavior

Ideally this would highlight the popup with the documentation format that the language server provides. Seems like the spec sais there a `documentationFormat` field that is set: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion.

**Comment by glepnir** [comment]
you can get popup preview buffer number from vim.fn.complete_info then set the filetype of popup buffer to some ft which return from lsp completion result. Do these in CompleteChanged event.
