### ISSUE TITLE
No way to check if neovim has the terminal feature

### ISSUE THREAD

**Issue by bsmith89** [neovim/neovim#2984]
I like to link `~/.nvimrc` to `~/.vimrc` and `~/.nvim/` to `~/.vim/`.  This makes maintaining my configuration very simple.  It's great that almost all of the settings and configuration that I use is compatible with both vim and neovim.

An example of one exception, however, are key mappings for the terminal emulator, or anything calling `:term`.  I've got the following mapping in my `.vimrc`:

```
tnoremap <Esc> <C-\><C-n>
tnoremap <C-\> <Esc>
```

To make this work for the rare times I use standard vim I use:

```
if has('nvim')
    tnoremap <Esc> <C-\><C-n>
    tnoremap <C-\> <Esc>
endif
```

but this seems less than ideal, since historical versions of neovim may lack `:tnoremap` and yell at me about it.  In general, I'd prefer to set my options feature-by-feature, instead of editor-by-editor.  Is there a way to get more granular information about available features, especially `:term`?

In this case, what I'd really like is a `has('term')`.  I've looked through `:h feature-list`, but that doesn't seem to have been edited since `:term` was implemented.

Sorry if this is a duplicate or has already been dealt with.  I couldn't find anything when I looked.

**Comment by fdinoff** [comment]
You can use `exists()`

```
if exists(':tnoremap')
...
endif
```

Read `:help exists()`

**Comment by bsmith89** [comment]
Thanks.  This does the trick.
