### ISSUE TITLE
Doc still says nvim have python and bash tree-sitter parsers

### ISSUE THREAD

**Issue by Futarimiti** [neovim/neovim#29845]
### Problem

Bundled bash and python parsers and queries have been dropped in the latest state release (v0.10.1) for being "unused". This is not reflected in the docs however. I don't know the workflow to change the docs so I'll just put the issue here.

### Steps to reproduce

```
nvim --clean --cmd ':help treesitter-parsers'
```

### Expected behavior

```
PARSER FILES                                              *treesitter-parsers*

Parsers are the heart of treesitter. They are libraries that treesitter will
search for in the `parser` runtime directory.

Nvim includes these parsers:

- C
- Lua
- Markdown
- Vimscript
- Vimdoc
- Treesitter query files |ft-query-plugin|
```

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1720049189

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 14.4.1

### Terminal name/version

iTerm2 Build 3.5.2

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by dundargoc** [comment]
Fixed in https://github.com/neovim/neovim/pull/29719

**Comment by jpoliv** [comment]
@dundargoc Could you backported this documentation change to the 0.10 branch?

Issue:
The current treesitter doc of the release-10 branch still includes bash and python on the list of shipped parsers:
* https://github.com/neovim/neovim/blob/release-0.10/runtime/doc/treesitter.txt

Additional information:
The bash and the python parsers were dropped from neovim 0.10.1, as stated on the respective release notes:
* https://github.com/neovim/neovim/releases/tag/v0.10.1
* Section: Build System / deps: Drop unused bundled bash, python parsers and queries

/tia

**Comment by dundargoc** [comment]
@jpoliv backport fail. Send PR to the release branch if you'd like
