### ISSUE TITLE
Add a config option to disable W11 messages / checking file changes

### ISSUE THREAD

**Issue by LeonB** [neovim/neovim#2985]
I think it would be a nice feature to have a configuration option to disable the checking if a file has changed when a buffer gains focus. Switching between buffers over sshfs starts lagging sometimes when vim checks if a file is modified.

**Comment by fmoralesc** [comment]
For this, use `setlocal noautoread`. You can do this with an autocommand on `BufRead` if you know in advance the path that sshfs uses:
~~~ vim
au! BufRead sshfs_path* setlocal noautoread
~~~

**Comment by LeonB** [comment]
@fmoralesc thanks! I tried it but I can't seem to get it working: `nvim -u NONE -c ':set noautoread'` and it stil automatically refreshes files :(

**Comment by LeonB** [comment]
It really only works if I manually type `:set noautoread` in the buffer. Setting it on startup doesn't seem to work even though `:set autoread?` returns `noautoread`.

**Comment by LeonB** [comment]
Nevermind. Updating to the latest version of neovim fixed it! This is what I'm using now:

```
au! BufRead,BufWrite $HOME/Public/** setlocal noautoread
```

**Comment by fmoralesc** [comment]
I'm glad. I thought I messed up when changing the 'autoread' default for a moment (my bad)!
