### ISSUE TITLE
No commentstring for autohotkey files

### ISSUE THREAD

**Issue by leet0rz** [neovim/neovim#29853]
### Problem

When using the new commenting feature it does not work when trying to comment 1 or more lines in .ahk files (autohotkey).

### Steps to reproduce

Open a .ahk file
Try to comment one or more lines
it fails with message: `Option 'commentstring' is empty.` 

### Expected behavior

For it to comment the line/lines

### Neovim version (nvim -v)

NVIM v0.11.0-dev-474+g2a24d0a43 Build type: RelWithDebInfo LuaJIT 2.1.1720049189 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

vim does not have this afaik.

### Operating system/version

Windows 10

### Terminal name/version

Windows terminal 1.21.240506002-preview

### $TERM environment variable

xterm-256color

### Installation

From this repo with msi.

**Comment by clason** [comment]
Please always test with `nvim --clean`.

**Comment by clason** [comment]
And please tell us what the commentstring should be.

**Comment by telemachus** [comment]
I think these work for `comments` and `commentstring`:

```vim
setlocal comments=s1:/*,mb:*,ex:*/,:;
setlocal commentstring=;\ %s
```

A lot of people seem to use this for a syntax file: https://github.com/vim-scripts/autohotkey-ahk/blob/master/syntax/autohotkey.vim. I can't find a full filetype plugin file, however.

**Comment by leet0rz** [comment]
> I think these work for `comments` and `commentstring`:
> 
> ```viml
> setlocal comments=s1:/*,mb:*,ex:*/,:;
> setlocal commentstring=;\ %s
> ```
> 
> A lot of people seem to use this for a syntax file: https://github.com/vim-scripts/autohotkey-ahk/blob/master/syntax/autohotkey.vim. I can't find a full filetype plugin file, however.

These seem to be working:
```lua
vim.cmd("setlocal comments=s1:/*,mb:*,ex:*/,:;")
vim.cmd("setlocal commentstring=;%s")
```

I guess I will hook them up to an autocmd until they are implemented, thanks.

**Comment by clason** [comment]
(There's no default ftplugin, hence the suggestion to contribute one.)

**Comment by telemachus** [comment]
> (There's no default ftplugin, hence the suggestion to contribute one.)

I will contribute a minimal one. A quick search on GitHub shows at least a handful of people who have an `after/ftplugin` for just this purpose.

@clason One larger question: on vim, `commentstring` has a default, but on neovim, it does not. Do you know the reason? (I could search the issues, but...)

**Comment by clason** [comment]
Yes, it's needed to make the "local" commentstring work (for treesitter injections).

(Also, the default string was legacy K&R C, which was not a great default...)

**Comment by telemachus** [comment]
> > after/ftplugin
> 
> Probably because they just did that without thinking; it'll work, it's just not needed in this case. (It's needed to override but not to first set an option.)

Yeah, fair. I default to recommending `after/ftplugin` because I have seen too many cases where a plugin stomps on a setting in unexpected ways. I get that in this case, there is no `ftplugin/autohotkey.vim`, but I tend to put all my tweaks in `after/` out of (too much?) caution.

**Comment by telemachus** [comment]
@clason https://github.com/vim/vim/pull/15345
