### ISSUE TITLE
multiple foldmethods

### ISSUE THREAD

**Issue by imyxh** [neovim/neovim#29860]
### Problem

It's very common that there's a block of code that I want to manually collapse into a fold, but I also want to keep having nvim fold by indentation or by syntax. For example, the C file I'm currently writing has a bunch of functions, but also a whole block of `#define`s for hardware pins. I would like to be able to `set foldmethod=marker,syntax`, and then enclose the block of `#define`s in `// {{{` and `// }}}` to be able to collapse them away, while still preserving syntax-based folding for the rest of the file.

### Expected behavior

It would be nice to allow at least `foldmethod=marker` and `foldmethod=manual` to exist concurrently with the automatic foldmethods (`syntax`, `indent`, `diff`, etc. ...).

**Comment by sodium-hydroxide** [comment]
Absolutely agree. I think as a first step, the marker fold method would be the highest level fold. For the following code block, each of the functions could fold on their own (as well as other syntax folding within each function) but the marker fold would collapse all three.

```c
// {{{
int func1(int x) {

}
int func2(int x) {

}
int func3(int x) {

}
// }}}
```

Long term, it would be nice if the two fold methods could interact with each other.

```c

int func1(int x) {
    \\{{{ coplicated code block

    \\}}}

    \\{{{ other coplicated code block
    
    while (some_condition) {
        // operation
    }
    \\}}}

    while (new_condition) {
        // operation
    }
}
```

**Comment by justinmk** [comment]
'foldexpr' allows defining a function which can do anything. Deciding the behavior will be hard, but that would also be the case for the interface requested in this issue...
