### ISSUE TITLE
build neovim-ppa with +lua support

### ISSUE THREAD

**Issue by sunaku** [neovim/neovim#2987]
Hello,

Please build the [neovim-ppa](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable) with `+lua` support so that I can use [the neocomplete plugin](https://github.com/Shougo/neocomplete.vim) with NeoVim.

Thanks for your consideration.

**Comment by fwalch** [comment]
Please see https://github.com/neovim/neovim/wiki/FAQ#can-i-use-luaruby-based-vim-plugins
Maybe https://github.com/Shougo/deoplete.nvim is of interest to you.

**Comment by sunaku** [comment]
Thanks, it seems deoplete.nvim requires Python3 and the neovim-ppa is not built with that either, so I'll just have to build the NeoVim package myself. :disappointed:

**Comment by fwalch** [comment]
You don't need to rebuild anything, just install an additional package. See http://neovim.io/doc/user/nvim_python.html

**Comment by sunaku** [comment]
Wow, that's pretty cool. :+1: Thanks for the tip. :bow:
