### ISSUE TITLE
ftplugin/scss.vim wrongly pulls shiftwidth setting from ftplugin/sass.vim

### ISSUE THREAD

**Issue by rmsc** [neovim/neovim#29879]
### Problem

When editing `scss` files, vim wrongly ignores the global `shiftwidth` settings and overrides it to 2.

I've noticed that `ftplugin/scss.vim` just loads the full `ftplugin/sass.vim`, and in the latter uses the option `sass_recommended_style` to control whether or not to override the global setting.

I'd argue that `scss` is much closer to `css` than to `sass`, and forcing a specific shiftwidth for `scss` makes little sense. So perhaps defaulting `sass_recommended_style` to `0` for `scss` would be a simple fix.

That said, I couldn't find any official "recommended" style for `sass`, or any other reason to force `shiftwidth` to be 2 spaces. So honestly I think the following section should just go away:
```
if get(g:, 'sass_recommended_style', 1)
  setlocal shiftwidth=2 softtabstop=2 expandtab
  let b:undo_ftplugin .= ' sw< sts< et<'
endif
```

### Steps to reproduce

Put this anywhere in your `vimrc`:
```
set shiftwidth=4
```

Then create and edit a `test.scss` file with the following content:
```
html {
    margin: 0;
}
```

With the cursor over `margin: 0` press `Shift+==` to autoindent, the line will be indented with 2 spaces.

### Expected behavior

Just like with `css`, the editor should keep indentation at 4 spaces.

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

Linux

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

Pacman

**Comment by clason** [comment]
These files are maintained by vim/vim; please raise the issue there and we will port any fix they make.

**Comment by rmsc** [comment]
Thanks, for future reference I've opened this issue: https://github.com/vim/vim/issues/15366
