### ISSUE TITLE
`json_decode`: Wrong error thrown for large incomplete JSON (`E1510` instad of `E474`)

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#29886]
### Problem

If a large JSON string is incomplete the Error `E1510: Value too large` will be thrown instead of `E474: Unexpected end of input`. This causes problems in plugins which try to catch a decoding error, but then miss this one case. It happens for example in https://github.com/monkoose/nvlime/issues/12 where Neovim is expected to receive very large messages in JSON format from a running Lisp process.

From my limited investigation it looks like error happens in `vim_vsnprintf_typval` because the logic falls into `format_overflow_error` while parsing the format directive `%.*s`, but I was not able to understand how the variable `j` is computed (`src/nvim/strings.c:1616` in Neovim 0.10.1). 

### Steps to reproduce

Take these two large JSON files:

- [buffered.json](https://github.com/user-attachments/files/16403776/buffered.json)
- [buffered-incomplete.json](https://github.com/user-attachments/files/16403777/buffered-incomplete.json) (missing the closing `]` at the end)

Let's try to read both of them in and parse them.

```vim
let complete = readfile('buffered.json')
let incomplete = readfile('buffered-incomplete.json')

" This works fine:
echo json_decode(complete[0])

" This trows E1510
echo json_decode(incomplete[0])

" This throws E474
echo json_decode('[1, 3, 4')
```

### Expected behavior

The error thrown for an incomplete JSON string should be the same for all string sizes.

### Neovim version (nvim -v)

NVIM v0.10.1

### Vim (not Nvim) behaves the same?

No, Vim 9.1 raises `E491` and partially decodes the string

### Operating system/version

Void Linux

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

Void package

**Comment by zeertzjq** [comment]
A possible solution is to just to `vsnprintf()` instead of `snprintf()`:
```diff
diff --git a/src/nvim/message.c b/src/nvim/message.c
index 73712489ad..3543f427b9 100644
--- a/src/nvim/message.c
+++ b/src/nvim/message.c
@@ -818,7 +818,7 @@ static bool semsgv(const char *fmt, va_list ap)
     return true;
   }
 
-  vim_vsnprintf(errbuf, sizeof(errbuf), fmt, ap);
+  vsnprintf(errbuf, sizeof(errbuf), fmt, ap);
 
   return emsg(errbuf);
 }
```
