### ISSUE TITLE
`ALLUSERS` property missing in neovim 0.10.1 MSI

### ISSUE THREAD

**Issue by russellbanks** [neovim/neovim#29885]
### Problem

The 0.10.1 neovim MSI installer doesn't have an `ALLUSERS` property in the MSI property table despite it having the property in 0.10.0. This means that the installer is defined as installing in user scope.

I have documented this in https://github.com/russellbanks/Komac/issues/709#issuecomment-2254422052.

Also see https://github.com/microsoft/winget-pkgs/issues/164944 for issues this causes.

### Steps to reproduce

Open the neovim MSI in [Orca](https://learn.microsoft.com/windows/win32/msi/orca-exe). There is no `ALLUSERS` property in the property table.

### Expected behavior

There should be an `ALLUSERS` property of 1, as there is in neovim 0.10.0.

### Neovim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

N/A

**Comment by sharpjs** [comment]
This bug results in a prior per-machine installation refusing to update.  WinGet logs contain the following:

```
2024-07-28 08:03:17.018 [CLI ] Installer [X64,wix,User,en-US] not applicable: Installer scope does not match currently installed scope: User != Machine
```
