### ISSUE TITLE
`<M-F4>` keymap not working

### ISSUE THREAD

**Issue by mangelozzi** [neovim/neovim#29899]
### Problem

When trying to bind a keymap to `<M-F4>`, it is not detected, whereas issue #8317 indicates that it should work.

### Steps to reproduce

1. `nvim --clean`
2. `:lua vim.keymap.set({"", "!"}, "<F4>", function() print('F4 is detected') end, { noremap = true})`
3. `:lua vim.keymap.set({"", "!"}, "<M-F4>", function() print('Alt F4 should be detected') end, { noremap = true})`
4. Press `F4` to confirm the keymap works.
5. Press `<M-F4>` and see nothing is printed.

### Expected behavior

For it to print `Alt F4 should be detected`

### Neovim version (nvim -v)

NVIM v0.11.0-dev-408+gb1aa8f5eb Build type: RelWithDebInfo LuaJIT 2.1.1720049189

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Debian 22.05

### Terminal name/version

Gnome terminal - Version 3.44.0 for GNOME 42 (one that ships with ubuntu)

### $TERM environment variable

`xterm-256color`

### Installation

appimage

**Comment by zeertzjq** [comment]
As mentioned in #8317, because the terminfo of `xterm-256color` indicted that the sequence for Alt-F4 is `<F52>`, you need to map `<F52>` instead.

**Comment by zeertzjq** [comment]
Duplicate of #8317

**Comment by mangelozzi** [comment]
> As mentioned in #8317, because the terminfo of `xterm-256color` indicted that the sequence for Alt-F4 is `<F52>`, you currently need to map `<F52>` instead.

Thank you! Sorry I did not realise that when reading the issue. I looked at the commit and thought that resolved the issue.
