### ISSUE TITLE
Recursive, incomplete key maps not working

### ISSUE THREAD

**Issue by horriblename** [neovim/neovim#29896]
### Problem

in vim, with `set nocompatible`, I can use `:nmap <c-w>- <c-w>-<c-w>` to do `<c-w>----` to repeatedly reduce window size.

in neovim this doesn't work, typing `<c-w>-` instead acts as if `<c-w>-<c-w><c-w>` were pressed (reduce window size, then switch to next window)

### Steps to reproduce

run `nvim -u NORC --cmd'nmap <c-w>- <c-w>-<c-w>'`
open a split and use `<c-w>-`

### Expected behavior

allow incomplete recursive bindings

### Neovim version (nvim -v)

v0.10.1

### Vim (not Nvim) behaves the same?

no, version 9.1.0509

### Operating system/version

arch linux

### Terminal name/version

kitty 0.35.2

### $TERM environment variable

xterm-kitty

### Installation

nix

**Comment by zeertzjq** [comment]
I can reproduce this in Vim 9.1.0611 as well.

**Comment by zeertzjq** [comment]
I think this is the same problem as the `<c-r><c-p>` problem reported in vim/vim#15376.
