### ISSUE TITLE
Blinking cursor so fast after open CMD

### ISSUE THREAD

**Issue by BElluu** [neovim/neovim#29891]
### Problem

After update to 0.10.1 I got blinking cursor. Everything was ok in 0.9.5. This cursor blinking really fast. Move has lower FPS so it's not 1:1 what I see :D 
[blinking_cursor.webm](https://github.com/user-attachments/assets/4f514a49-4eb8-488c-9d32-b023af4f8e9e)

### Steps to reproduce

Just open nvim and open cmd.

### Expected behavior

Do not blink that much

### Neovim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Windows 10

### Terminal name/version

-

### $TERM environment variable

-

### Installation

MSI Installer

**Comment by clason** [comment]
> Just open nvim and open cmd.

That's clearly not enough, or other people would have noticed. First step is (always!) to test `nvim --clean`. Then provide _much_ more detail about your environment (terminal etc.) Leaving out requested information is an issue template is unacceptable.

**Comment by ferrianes** [comment]
i had same issue in v0.10+ including nightly version 0.11-dev, the bug still exist i dont know why, but in v0.9.5 everything is ok. im on windows 11, terminal using powershell 7

**Comment by zeertzjq** [comment]
This is a bug of noice.
- https://github.com/folke/noice.nvim/issues/923
