### ISSUE TITLE
API: provide in-memory `:source` sugar

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#2991]
We don't have a "transaction" concept, so the context-sensitive nature of VimL becomes problematic for remote clients if `vim_command` batches are received _interleaved_ from multiple clients.

To solve this, clients can `:source` temp files. Other options:
- provide API sugar to allow blocks of vimscript to be sourced in-memory
- change `vim_command` to take an array of strings instead of just a string

From @fdinoff: https://gitter.im/fdinoff/neovim-java-client?at=55a0453fa7d4f38e13c12dcb

> how does overlapping of commands work? For instance if you have two asynchronous remote plugins trying to add `autocmd`s to vim.
> 
> One executing (in a python client) 

``` viml
nvim.command('augroup GROUP')
nvim.command("  autocmd BufEnter * echom 'remote plugin 1'")
nvim.command('augroup END')
```

> And a second (in a separate client)

``` viml
nvim.command("autocmd BufLeave * echom 'remote plugin 2'")
```

> However there is no guarantee that the autocmd from the second remote plugin won't be in the augroup, since neovim could receive and process the commands out-of-order.

This has also been requested for convenience in functional tests.

@neovim/core I've been away this week, so let me know if I'm duplicating work.

**Comment by ZyX-I** [comment]
In tests one can workaround this with `:execute` or `:function` definitions+calls (usually first is used), hidden inside a helper function. But this is rather inconvenient in plugins.

Note that even if such API is added this will not prevent plugins from doing the wrong thing, so how about resetting state and giving a warning for

1. Changed `:redir` state.
2. Changed active autocmd group.
3. Increased active try level (only warning needed, I see that try level is reset) and other blocks (if, while, for, function) level (it seems that they are also ended, but without any errors as well).

**Comment by bfredl** [comment]
`nvim_exec()`
