### ISSUE TITLE
Trouble installing on WSL Ubuntu

### ISSUE THREAD

**Issue by codr1** [neovim/neovim#29926]
### Problem

On an absolutely fresh Ubuntu running under Windows WSL, with a fresh NeoVim install from tarball, I get the following error every time I run :MasonInstall for the very first time.  

Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: Wrong number of arguments
stack traceback:
        [C]: in function 'cmd'
        .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <.../share/nvim/lazy/lazy.nvim/lua/l
azy/core/handler/cmd.lua:16>

### Steps to reproduce

Fresh install on a fresh Ubuntu under WS:

### Expected behavior

Don't get the error. 

### Neovim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

no (it doesn't have Mason)

### Operating system/version

Windows 11

### Terminal name/version

Windows Ubuntu Terminal

### $TERM environment variable

xterm-256color

### Installation

tar ball

**Comment by clason** [comment]
Please report this to the plugin maintainers.
