### ISSUE TITLE
LSP: yamlls reports UriError error when opening YAML file

### ISSUE THREAD

**Issue by mclacore** [neovim/neovim#29922]
### Problem

```
Error executing vim.schedule lua callback: .../neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/client.lua:58
9: RPC[Error] code_name = InternalError, message = "Request initialize failed with message: [UriError]: S
cheme is missing: {scheme: \"\", authority: \"\", path: \"null\", query: \"\", fragment: \"\"}"
stack traceback:
        [C]: in function 'assert'
        .../neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/client.lua:589: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
Getting this error when opening a yaml file. I deleted any update to LSP re: yaml and still getting this error.

### Steps to reproduce using "nvim -u minimal_init.lua"

Using nvim-kickstart. I made some changes adding `yamlls` and also added formatters (`conform.nvim`) and set `yaml = { 'prettierd', 'prettier' },`

I've reverted both of those changes but still encountering the error. `:checkhealth` doesn't reveal any issues.

### Neovim version (nvim -v)

0.10.0

### Language server name/version

yamlls ?

### Operating system/version

macOS Sonoma 14.5

### Log file

https://gist.github.com/mclacore/00488e7bbd504df82e75cb69c0ca52c0

**Comment by amiii123malviya** [comment]
Hello,

Is this issue still active?
I would like to work on this.

Best Regards.

**Comment by clason** [comment]
No need to ask for permission. Best way to help is to create a minimal(!) reproducing example.

**Comment by justinmk** [comment]
> "Request initialize failed with message: [UriError]: Scheme is missing: {scheme: \"\", authority: \"\", path: \"null\", query: \"\", fragment: \"\"}"

Looks like an empty file name was sent. Does the file you edited exist on the filesystem? Please provide full steps to reproduce.

**Comment by valdirjunior011** [comment]
Same issue on yaml or yml file.

**Comment by onexbash** [comment]
I have the same issue. I cant figure out what's causing it. This is my lsp handler for `yamlls`:
```lua
        ["yamlls"] = function()
          require("lspconfig").yamlls.setup({
            capabilities = require("blink.cmp").get_lsp_capabilities(),
            settings = {
              yaml = {
                schemas = {
                  ["https://json.schemastore.org/github-workflow.json"] = ".github/workflows/*",
                  ["https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json"] = "docker-compose*.{yml,yaml}",
                  ["https://json.schemastore.org/yamllint.json"] = "*.{yml,yaml}",
                  ["/Users/fschlegelone/.local/share/nvim/mason/packages/packages/yaml-language-server/mason-schemas/lsp.json"] = "*.{yml,yaml}",
                },
              },
            },
          })
        end,
```
