### ISSUE TITLE
xdg-open doesn't like being run by vim.system

### ISSUE THREAD

**Issue by a3ng7n** [neovim/neovim#29932]
### Problem

When running `xdg-open https://google.com` via `vim.system` nothing seems to happen. But the command outside of nvim and in either zsh or bash seems to work. A summary:
1. (in nvim) `:lua vim.system({'xdg-open', 'https://google.com'}, {text = true, detach = true})` doesn't work - no errors reported, etc.
2. (in nvim) `:! xdg-open https://google.com` doesn't work - no errors
3. (in nvim) `:! xdg-open https://google.com 1>/dev/null 2>&1` *does* work
4. (in nvim) ~`:lua vim.system({'xdg-open', 'https://google.com', '1>/dev/null', '2>&1'}, {text = true, detach = true})` doesn't work, and when examining the output via `...vim.system(...):wait().stderr` it shows "xdg-open: unexpected argument '1>/dev/null' Try 'xdg-open --help' for more information.", which I imagine means I'm not passing `1>/dev/null` etc. to the shell/process correctly?~
**update:** `:lua vim.system({'bash', '-c', 'xdg-open https://google.com 1>/dev/null 2>&1'}, {text = true, detach = true})` does work, albeit with no output
6. (outside of vim) `$ xdg-open https://google.com` works, but notably shows a bunch of "Gtk-WARNING"s etc. in stderr
7. (outside of vim) `$ firefox https://google.com` works, and shows the exact same "Gtk-WARNING"s
8. (in nvim) `:lua vim.system({'firefox', 'https://google.com'}, {text = true, detach = true})` does work, and when examining the output via `...vim.system(...):wait().stderr` it shows the same "Gtk-WARNING"s

I don't quite understand all the internals, but I'm guessing xdg-open returns an exit code before the spawned process writes to stderr, whereas firefox returns an exit code after - and given my naiive understanding about `vim.system` it closes the stdout/stderr pipes once it gets a successful exit code, which causes xdg-open's spawn'ed process to not work?

Oddly enough I put `xdg-open $@ 1>/dev/null 2>&1` in test.sh, and running the following works `:lua vim.system({'bash', 'test.sh', 'https://google.com'}, {text = true, detach = true})` albeit with no output of any kind.

### Steps to reproduce

(in nvim) `:lua vim.system({'xdg-open', 'https://google.com'}, {text = true, detach = true})`

### Expected behavior

Expect browser to open, but nothing happens.

### Neovim version (nvim -v)

v0.11.0-dev

### Vim (not Nvim) behaves the same?

Yes

### Operating system/version

Ubuntu 24.04

### Terminal name/version

kitty 0.32.2

### $TERM environment variable

xterm-kitty

### Installation

sudo apt install neovim

**Comment by a3ng7n** [comment]
Oh and `:call jobstart('xdg-open http://github.com')` works, and so does `:terminal ...`

**Comment by a3ng7n** [comment]
Another detail: figured out how to pass `bash -c "..."` to vim.system correctly, so the following works:
`:lua vim.system({'bash', '-c', 'xdg-open https://google.com 1>/dev/null 2>&1'}, {text = true, detach = true})`

Is there a way to arm wrestle `vim.system` to spawn the process with stdout and stderr set to /dev/null? It seems libuv would need to see the flag `UV_IGNORE` on one (or all?) of the stdios, which it looks like is already happening here: https://github.com/neovim/neovim/blob/e1d48d5cf295293598144c351ace5f1e07c0cb7c/src/nvim/event/libuv_process.c#L47-L49 just unsure if that's what `vim.system` is using?

**Comment by zeertzjq** [comment]
To do this in `vim.system()` it should be like this:
```vim
:lua vim.system({'xdg-open', 'https://google.com/'}, {text = true, detach = true, stdout = false, stderr = false})
```
Does this work?

**Comment by a3ng7n** [comment]
> To do this in `vim.system()` you can set `stdout` and `stderr` to `false`:
> 
> ```lua
> vim.system({'xdg-open', 'https://google.com/'}, {text = true, detach = true, stdout = false, stderr = false})
> ```
> 
> Does this work?

Awesome - yes that worked. I was running in to this problem while using `vim.ui.open` via `gx` - would a PR to change that here-ish be well received? https://github.com/neovim/neovim/blob/e820474cde09273608be5f57e1032aab21e3c97d/runtime/lua/vim/ui.lua#L156-L157 I don't know if it's the right solution, and I'm happy to remap `gx` in my config, but I can imagine others might run in to this as well.
