### ISSUE TITLE
Buffer group/namespace

### ISSUE THREAD

**Issue by caenrique** [neovim/neovim#29941]
### Problem

Working with multiple projects in the same nvim instance is not great. A way that Ive been trying to separate files from different projects is by using tabs and changing the tab working directory to point to the root of each project, but this has the problem that buffers in vim/nvim are not scoped in any way. So things like ctrl-o/ctrl-i, alternate buffer, listing buffers, etc gets polluted from all tabs. There is no way of making a separation.

### Expected behavior

Creating some sort of group or namespace that buffers can be assigned to, and the ability to ser tabs (or even windows) to have visibility over that group/namespace. 

This allows to have a default that maintains the current behavior and is non intrusive for users that don’t want to opt in to use this feature.

**Comment by Hamza12700** [comment]
How I work with multiply projects in neovim is by using a terminal multiplexer, my personal favorite is [zellij](https://zellij.dev/).
I don't think you need `buffer group/namespaces` or anything like that. A terminal multiplexer is good enough for this job.

**Comment by justinmk** [comment]
> Ive been trying to separate files from different projects is by using tabs and changing the tab working directory to point to the root of each project, but this has the problem that buffers in vim/nvim are not scoped in any way.

Tabs are indeed the current best answer. It's true that there is no other "scoping" concept which would "contain" navigation. But also, Nvim is fast to startup, and a "peer to peer" concept would be an alternative that implicitly and fully "scopes" everything by virtue of being in a separate process, while allowing peer Nvims to communicate with each other in an opt-in manner.

So the question is which of these ("multi-tenant" vs "peer to peer") is more tractable/extensible/intuitive/maintainable. Historically, we have moved away from multi-tenancy, in favor of composability.

Note also that for "multi project", we have a proposal outlined here: https://github.com/neovim/neovim/issues/8610#issuecomment-1367994885 . It doesn't address "scoped navigation", but then neither does any other IDE/editor (again, that's multi-tenancy, aka "inner platforms all the way down").
