### ISSUE TITLE
Letters appear and disappear when changing lines

### ISSUE THREAD

**Issue by ladislas** [neovim/neovim#2994]
I'm on OS X Yosemite, brand new Macbook Pro and I just installed Neovim.

When I'm switching lines I have a strange behavior: letter seems to appear and disappear. I made some screenshots, see end of lines.

<img width="678" alt="screenshot 2015-07-11 10 59 16" src="https://cloud.githubusercontent.com/assets/2206544/8633178/927f5398-27bc-11e5-8056-f7c679997fe2.png">
<img width="668" alt="screenshot 2015-07-11 10 59 27" src="https://cloud.githubusercontent.com/assets/2206544/8633179/92c69744-27bc-11e5-8952-d9254a2cb462.png">
<img width="673" alt="screenshot 2015-07-11 10 59 35" src="https://cloud.githubusercontent.com/assets/2206544/8633180/94cf79f2-27bc-11e5-88dc-36475b3ab107.png">
<img width="685" alt="screenshot 2015-07-11 10 59 46" src="https://cloud.githubusercontent.com/assets/2206544/8633181/977a0d20-27bc-11e5-8451-c9261dffb27b.png">

Sometimes I can't even reach the end of the line in normal mode. If I open a new window, the previous one is displayed normally, without the glitches, but if I come back to the first one, glitches come back.

**Comment by ladislas** [comment]
after more investigation, the bug seems to be caused by `set cursorline`. when I have only this in my `.nvimrc` the bug appears, if I remove it, it doesn't appear.

**Comment by ladislas** [comment]
and also, I don't know if it is related, but neovim has issues displaying characters such as `±` -- it adds a space after it, same with `tab`...

**Comment by ladislas** [comment]
I even narrowed it down a little more. This is the minimal requirement to make the bug appear:

```vimL
set cursorline
set list " Show invisible characters
set listchars=tab:│\ ,trail:•,extends:❯,precedes:❮
```

**Comment by mhinz** [comment]
I can't reproduce this with neovim from `master` in iTerm2.

Did you brew neovim or compiled from source?

**Comment by ladislas** [comment]
After much tergiversation, I think I **really** found the issue...

It's all my fault, for an obscure reason I had activated the following option in iTerm2
<img width="337" alt="screenshot 2015-07-14 19 56 41" src="https://cloud.githubusercontent.com/assets/2206544/8680573/84db2fde-2a62-11e5-86b3-1642195e59de.png">

Everything is now in order and the bug has disappeared. :)

Sorry for the inconvenience and all the messages.

**Comment by mhinz** [comment]
Ah, good to know in case someone else has this problem, too. :)
