### ISSUE TITLE
Open the query editor for one of the injected language

### ISSUE THREAD

**Issue by Lattay** [neovim/neovim#29943]
### Problem

Using the InspectTree to develop plugins I noticed it is sometimes useful to be able to open the query editor for one of the injection parser rather than the main parser (say you want to try queries for markdown_inline).
I noticed that it is possible to do it with a direct call to `vim.treesitter.query.edit` but I think it is nicer to have an alternative keybinding. Unfortunately the current implementation of `inspect_tree` doesn't offer hooks (as far as I can tell) to add user defined mappings.

I implemented the feature I want, and it works (https://github.com/neovim/neovim/compare/master...Lattay:neovim:open_injection_query_editor it's a very simple change), but I also figured from the perspective of Neovim it may be more interesting to add a hook in `inspect_tree` instead...

Is this feature interesting by itself, or too specific? Should I propose a hook in `inspect_tree` instead so that users can define custom mappings for this buffer?

### Expected behavior

Pressing O, the user is prompted to select a language in the list of active parsers. Uppon selection the query editor is opened for the selected language.

**Comment by clason** [comment]
No keybinding is needed (or desired), but `:EditQuery` could take a language as an argument (same as `:InspectTree` could).

**Comment by Lattay** [comment]
Ok, actually, I have just seen that `:EditQuery` does take a language argument, but the command is undocumented. I am looking into that.

**Comment by clason** [comment]
Ah, right, it's just `:InspectTree` that's missing the argument. Then there's nothing more to be done.

**Comment by PeterCardenas** [comment]
@Lattay opened up a PR above that has a proper fix for this. I tried just using the language argument but it wasn't sufficient.
