### ISSUE TITLE
Windows: `os.date` formatting does not work with unicode character

### ISSUE THREAD

**Issue by doongjohn** [neovim/neovim#29963]
### Problem

`os.date` formatting does not work with unicode character.
However `string.format` works well with unicode character.

### Steps to reproduce

nvim --clean
`:=os.date("😊%Y")`
![image](https://github.com/user-attachments/assets/d241a339-a9a8-4bf1-af9c-b12df917c71e)

### Expected behavior

`:=os.date("hello%Y")`
![image](https://github.com/user-attachments/assets/98b83e87-d794-4ede-934b-17b811c19ec3)

### Neovim version (nvim -v)

NVIM v0.10.1

### Vim (not Nvim) behaves the same?

vim doesn't have lua support

### Operating system/version

Windows 11

### Terminal name/version

wezterm, windows terminal

### $TERM environment variable

xterm-256color

### Installation

github release

**Comment by clason** [comment]
Can you test this in standalone PUC Lua or LuaJIT?

**Comment by doongjohn** [comment]
It's working with wandbox LuaJIT 2.0.5
https://wandbox.org/permlink/9SbZqFz2u9xCH4RG

**Comment by clason** [comment]
- [ ] It would be better if you could test a current version; 2.0.5 is ancient.

**Comment by doongjohn** [comment]
I've used MSYS2 to build LuaJIT 2.1 branch. It works properly.
![image](https://github.com/user-attachments/assets/79da0c82-4f77-490d-ac2f-2144bd3aca8a)

**Comment by doongjohn** [comment]
I think I found a solution.
The default locale(for my computer) I get from nvim by running `os.setlocale()` is this:
`LC_COLLATE=ko_KR;LC_CTYPE=ko_KR;LC_MONETARY=ko_KR;LC_NUMERIC=C;LC_TIME=ko_KR`

This issue including https://github.com/neovim/neovim/issues/29952 gets fixed if I change `ko_KR` to `ko_KR.UTF8`:
`os.setlocale("LC_COLLATE=ko_KR.UTF8;LC_CTYPE=ko_KR.UTF8;LC_MONETARY=ko_KR.UTF8;LC_NUMERIC=C;LC_TIME=ko_KR.UTF8")
`

**Comment by clason** [comment]
Yes, locale (these days) _must_ include the encoding; just `ko_KR` is (no longer) valid.

**Comment by doongjohn** [comment]
However I'm not sure this issue only happens for korean...

**Comment by clason** [comment]
No, this would affect all locales that 
1. require non-ASCII (e.g. any CJK)
2. don't specify the correct encoding (UTF-8 for Neovim)

**Comment by doongjohn** [comment]
@clason Is there any plan to make nvim automatically use UTF8 locale? Because I think this issue should not exist out of the box.

**Comment by clason** [comment]
The issue is not with neovim but with an incorrect locale. As I said, the locale **must** specify the encoding.

**Comment by doongjohn** [comment]
But my system locale is already set to UTF8. (according to setlocale)

```cpp
int main() {
  setlocale(LC_ALL, "");
  std::cout << "LC_ALL: " << setlocale(LC_ALL, NULL) << '\n';
}
```

```
LC_ALL: Korean_Korea.utf8
```

**Comment by clason** [comment]
> Korean_Korea.utf8

That's not a valid locale either.

**Comment by doongjohn** [comment]
I think it is valid locale (at least on windows: <https://learn.microsoft.com/en-us/cpp/c-runtime-library/locale-names-languages-and-country-region-strings?view=msvc-170>)

Also luajit 2.1 is working fine with this locale:
```lua
print(os.setlocale(""))
print(os.date())
print(os.date("안녕😊%Y"))
```
```
Korean_Korea.utf8
2024-08-04 오전 6:03:21
안녕😊2024
```

**Comment by clason** [comment]
> at least on windows

Yeah, but Microsoft likes writing fan fiction. That doesn't mean cross-platform tools need to cater to their delusions.

**Comment by doongjohn** [comment]
Fair enough 😊
For those who are having this issue: I guess the easiest solution is to put `os.setlocale("")` at the top of your `init.lua`.

**Comment by clason** [comment]
...or specify an actual valid locale (in your case, `ko_KR.uft8`). This is not limited to your locale, or this specific issue -- if your locale is invalid, hilarity ensues.
