### ISSUE TITLE
Clearing terminal 'scrollback' leaves a dangling line

### ISSUE THREAD

**Issue by derekstavis** [neovim/neovim#29969]
### Problem

Clearing the scrollback leaves a dangling line that appears when leaving insert mode. The line disappears when entering insert mode again.

The video shows an example of using `reset` + `set scrollback=0` + `set scrollback=-1`, but just using plain `clear` reproduces the issue (see repro steps below)

https://github.com/user-attachments/assets/c9e89446-c6e0-444e-ab0c-70e4cef9b83a

### Steps to reproduce
```
nvim --clean -u minimal.lua
:term
dmesg # or anything with output greater than number of lines in the window
clear
C-\ C-N
```

### Expected behavior

No dangling lines should appear when going back to normal mode

### Neovim version (nvim -v)

NVIM v0.10.1

### Vim (not Nvim) behaves the same?

No, it does not have clear scrollback feature

### Operating system/version

macOS 14.5

### Terminal name/version

kitty 0.35.2

### $TERM environment variable

xterm-kitty

### Installation

Homebrew

**Comment by zeertzjq** [comment]
I can't understand this issue. Which line is the "dangling line" referring to?

**Comment by derekstavis** [comment]
> I can't understand this issue. Which line is the "dangling line" referring to?

Check the 12s mark of the video. The "random 128" line appears after exiting to normal mode:

<img width="203" alt="image" src="https://github.com/user-attachments/assets/79550be1-c4d6-44f4-8f20-f212387d6b46">

**Comment by justinmk** [comment]
This is "wontfix".  Minimum 'scrollback' is documented as 1. Fixing this is annoying and complicated.

**Comment by derekstavis** [comment]
Even if set to 1 the fact that the wrong line is being kept means there's still a bug to be fixed, but it seems like the return is not worth the investment.

Anyway I just wanted to highlight that not being able to clear the scrollback buffer is definitely annoying and results in bad UX. It's a really minor issue, but it bugs me and thousand other people that use Neovim as their terminal emulator.

If I could have some pointers on where to address this, potentially supporting a scrollback of 0 or even adding a native way of clearing the scrollback buffer completely, I would be happy to put a PR to address this. Let me know!

**Comment by justinmk** [comment]
here's a starting point: https://github.com/neovim/neovim/blob/0f308f1f0c53a49d41f4dd8886e5b89253a6049a/src/nvim/terminal.c#L135

**Comment by nenahp** [comment]
Didn’t dig a lot, but this is a quick workaround I‘ve been used. Maybe of helpful if someone would like to work on this.
https://github.com/phanen/neovim/commit/034ea3d396e5e31a76ef8187851c0524e14cbb72

**Comment by justinmk** [comment]
> this is a quick workaround I‘ve been used. [phanen@034ea3d](https://github.com/phanen/neovim/commit/034ea3d396e5e31a76ef8187851c0524e14cbb72)

If that doesn't cause crashes or ASAN issues then maybe there was a change that makes my previous objection obsolete.
