### ISSUE TITLE
[Windows] TermResponse (and v:termresponse) aren't working

### ISSUE THREAD

**Issue by TheLeoP** [neovim/neovim#29975]
### Problem

`Termresponse` and `v:termresponse` do nothing on Windows even if they are executed in a terminal that supports OSC escape codes.

### Steps to reproduce

1. `nvim --clean`
2. `:call chansend(v:stderr, "\x1b]11;?\x07")`
3. `:echo v:termresponse`
4. Nothing is printed (i.e. `v:termresponse` has no value assigned to it. 

Notes:
- I tested the same steps on Linux and it worked as expected
- Similarly, creating an autocmd for the `TermResponse` event does nothing on Windows, but works as expected on Linux

### Expected behavior

`TermResponse` and `v:termresponse`  should work just like they do in non-Windows platforms

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713484068

### Vim (not Nvim) behaves the same?

No, vim 9.0

### Operating system/version

Windows 11 Pro 23H2

### Terminal name/version

wezterm 20240226-174525-22424c32

### $TERM environment variable

xterm-256color

### Installation

nvim-win64.msi from the github releases page

**Comment by gpanders** [comment]
To clarify, if you run `printf '\x1b]11;?\x07'` in the shell on Windows, it does print some kind of response?

**Comment by zeertzjq** [comment]
I think it's the `chansend()` not working, not `TermResponse`.

**Comment by TheLeoP** [comment]
I stumbled upon this because [mini.misc](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-misc.md) isnt' working for me in Windows. 

> To clarify, if you run printf '\x1b]11;?\x07' in the shell on Windows, it does print some kind of response?

There is no `printf` on Windows, but `:lua io.write('\027]11;?\007')` or `:lua io.stdout:write('\027]11;?\007')` also do not work.

I know that the problem is `TermResponse` and `v:termresponse` because doing `:lua io.write('\027]11;#00ff00\007')` does change the background color

**Comment by zeertzjq** [comment]
Does an OSC response happen if you run `nvim --clean --headless -c 'lua io.write("\027]11;?\007")'` in the shell?

**Comment by TheLeoP** [comment]
> Does an OSC response happen if you run nvim --clean --headless -c "lua io.write('\027]11;?\007')" in the shell?

No

https://github.com/user-attachments/assets/db40fe4a-35df-4b62-acde-ffdbf83f2388

**Comment by zeertzjq** [comment]
The this should be reported to WezTerm.

**Comment by TheLeoP** [comment]
For the sake of documentation, this seems to be a general problem with ConPTY on Windows, not only Wezterm as per:

https://github.com/microsoft/terminal/issues/3718
and
https://github.com/microsoft/terminal/pull/16990#issuecomment-2058684187
