### ISSUE TITLE
LSP: settings field does not work consistently

### ISSUE THREAD

**Issue by Ryntak94** [neovim/neovim#29986]
### Problem

I am currently trying to setup intelephense to work and need to increase the max file size, in vscode using the `settings.json` file it would be down as follows: `"intelephense.files.maxSize" = 1500000`.
I see in the docs that we should be able to set this as follows
```lua
lspconfig.intelephense.setup({
	capabilities = capabilities,
	settings = {
		intelephense = {
			files = {
				maxSize = 1500000,
			},
		},
	},
})
```
Upon using the following:

`:lua=require('lspconfig').intelephense`
I do get a block that includes it, but it's listed below the root_dir.

Originally it did not seem to work at all, however it does seem to work inconsistently, and I don't know what causes it to work when it does.

You can use https://pinetools.com/random-file-generator to create a file with over 1mb of data (I set 1 file, 1100000 bytes, called the file `sample.php` and downloaded it)

You will need to open the file once with the `minimal_init.lua` to let intelephense install, and then a second time for it to attempt to succesfully run intelephense.

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
local pattern = "php"
local cmd = { "node", "intelephense", "--stdio" }
vim.lsp.log.set_level(vim.log.levels.WARN)
-- Add files/folders here that indicate the root of a project
local root_markers = { ".git", ".editorconfig" }
for name, url in pairs({
	mason = "https://github.com/williamboman/mason.nvim",
	masonLspConfig = "https://github.com/williamboman/mason-lspconfig.nvim",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	print(install_path)
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end -- Change to table with settings if required

require("mason").setup()
require("mason-lspconfig").setup({
	ensure_installed = { "intelephense" },
})
local settings = {
	intelephense = {
		files = {
			maxSize = 1500000,
		},
	},
}

vim.api.nvim_create_autocmd("FileType", {
	pattern = pattern,
	callback = function(args)
		local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
		local root_dir = match and vim.fn.fnamemodify(match, ":p:h") or nil
		print(root_dir)
		vim.lsp.start({
			name = "intelephense",
			cmd_cwd = "/Users/[YOU]/.local/share/nvim/mason/bin",
			cmd = cmd,
			root_dir = root_dir,
			settings = settings,
		})
	end,
})
```

### Expected behavior

Intelephense starts up without issue.

### Neovim version (nvim -v)

0.11.0-dev-408+gb1aa8f5eb

### Language server name/version

intelephense 1.11.8

### Operating system/version

MacOS Sonoma 14.2.1

### Log file

https://gist.github.com/Ryntak94/1c00d9976cbe9c89591ca21a239e89fd

**Comment by lewis6991** [comment]
Neovim doesn't do a lot here. I just sends a notification to the server (https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/client.lua#L597-599).

Any issues are likely due to the server itself.
