### ISSUE TITLE
Error using vim.text.hexdecode on large (?) strings.

### ISSUE THREAD

**Issue by pedrohgmacedo** [neovim/neovim#29981]
### Problem

Consider:
```lua
-- https://github.com/neovim/neovim/blob/0c2860d9e5ec5417a94db6e3edd237578b76d418/test/functional/lua/text_spec.lua#L14
local input, output = string.rep("😂", 2 ^ 16), string.rep("F09F9882", 2 ^ 16)
assert(output, vim.text.hexencode(input))
assert(input, vim.text.hexdecode(output))
```
The I get an error `string slice is too long`. It seems the string. functions have a problem with large strings.
I think a better implementation would be to use the jit string.buffer:
```lua
local buffer = require("string.buffer")
local bit = require("bit")

local function hexencode2(str)
  local bytes = buffer.new()
  local enc = buffer.new()
  bytes:set(str)
  local ptr, len = bytes:ref()
  for i = 0, len - 1 do
    -- enc:put(bit.tohex(ptr[i], -2))
    enc:putf("%02X", ptr[i])
  end
  return enc:tostring()
end

local function hexdecode2(enc)
  local dec = buffer.new()
  local enc_buf = buffer.new()
  enc_buf:set(enc)
  local ptr, len = enc_buf:ref()
  for i = 0, len - 1, 2 do
    local hex = (ptr[i] % 0x20 + 0x9) % 0x19 * 0x10 + (ptr[i + 1] % 0x20 + 0x9) % 0x19
    dec:putf("%c", hex)
  end
  return dec:tostring()
end
local input, output = string.rep("😂", 2 ^ 16), string.rep("F09F9882", 2 ^ 16)
assert(output == hexencode2(input))
assert(input == hexdecode2(output))
```

### Steps to reproduce

```lua
-- https://github.com/neovim/neovim/blob/0c2860d9e5ec5417a94db6e3edd237578b76d418/test/functional/lua/text_spec.lua#L14
local input, output = string.rep("😂", 2 ^ 16), string.rep("F09F9882", 2 ^ 16)
assert(output == vim.text.hexencode(input))
assert(input == vim.text.hexdecode(output))
```

### Expected behavior

success

### Neovim version (nvim -v)

NVIM v0.10.1

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Ubuntu 24.04

### Terminal name/version

wezterm

### $TERM environment variable

wezterm

### Installation

Release from github

**Comment by glepnir** [comment]
I just tried with a ffi version there is bench 

```lua
local ffi = require('ffi')
local buffer = require('string.buffer')

local hex_map = ffi.new('char[512]')

for i = 0, 255 do
  local high_nibble = math.floor(i / 16)
  local low_nibble = i % 16
  hex_map[i * 2] =
    string.byte(high_nibble < 10 and tostring(high_nibble) or string.char(55 + high_nibble))
  hex_map[i * 2 + 1] =
    string.byte(low_nibble < 10 and tostring(low_nibble) or string.char(55 + low_nibble))
end

local function hexencode1(str)
  local len = #str
  local enc = ffi.new('char[?]', len * 2 + 1)

  for i = 0, len - 1 do
    local byte = string.byte(str, i + 1)
    enc[i * 2] = hex_map[byte * 2]
    enc[i * 2 + 1] = hex_map[byte * 2 + 1]
  end

  return ffi.string(enc, len * 2)
end

local function hexdecode1(enc)
  if #enc % 2 ~= 0 then
    return nil, 'string must have an even number of hex characters'
  end

  local len = math.floor(#enc / 2)
  local str = ffi.new('char[?]', len + 1)

  for i = 0, len - 1 do
    local high_nibble = hex_map[enc:byte(i * 2 + 1)]
    local low_nibble = hex_map[enc:byte(i * 2 + 2)]
    if high_nibble == nil or low_nibble == nil then
      return nil, 'invalid character in input'
    end
    str[i] = ffi.cast('char', bit.bor(bit.lshift(high_nibble, 4), low_nibble))
  end

  return ffi.string(str, len)
end

-- The buffer-based functions you provided
local function hexencode2(str)
  local bytes = buffer.new()
  local enc = buffer.new()
  bytes:set(str)
  local ptr, len = bytes:ref()
  for i = 0, len - 1 do
    enc:putf('%02X', ptr[i])
  end
  return enc:tostring()
end

local function hexdecode2(enc)
  local dec = buffer.new()
  local enc_buf = buffer.new()
  enc_buf:set(enc)
  local ptr, len = enc_buf:ref()
  for i = 0, len - 1, 2 do
    local hex = (ptr[i] % 0x20 + 0x9) % 0x19 * 0x10 + (ptr[i + 1] % 0x20 + 0x9) % 0x19
    dec:putf('%c', hex)
  end
  return dec:tostring()
end

-- Function to run a benchmark
local function benchmark(func, input, iterations)
  local start_time = os.clock()
  for i = 1, iterations do
    func(input)
  end
  local end_time = os.clock()
  return end_time - start_time
end

-- Assert first
local input, output = string.rep('😂', 2 ^ 16), string.rep('F09F9882', 2 ^ 16)
assert(output, hexencode1(input))
assert(input, hexdecode1(output))

-- Benchmarking
local input = string.rep('hello world', 1000) -- Test with a large string
local encoded_input = hexencode1(input)
local iterations = 1000

print('Benchmarking hexencode1 (ffi-based)...')
local time1 = benchmark(hexencode1, input, iterations)
print('Time taken:', time1)

print('Benchmarking hexdecode1 (ffi-based)...')
local time3 = benchmark(hexdecode1, encoded_input, iterations)
print('Time taken:', time3)

print('Benchmarking hexencode2 (buffer-based)...')
local time2 = benchmark(hexencode2, input, iterations)
print('Time taken:', time2)

print('Benchmarking hexdecode2 (buffer-based)...')
local time4 = benchmark(hexdecode2, encoded_input, iterations)
print('Time taken:', time4)

```

Result in my computer is 
```
Benchmarking hexencode1 (ffi-based)...
Time taken: 0.009597
Benchmarking hexdecode1 (ffi-based)...
Time taken: 0.015724
Benchmarking hexencode2 (buffer-based)...
Time taken: 0.055264
Benchmarking hexdecode2 (buffer-based)...
Time taken: 0.031767
```

**Comment by pedrohgmacedo** [comment]
I get:
```lua
-- Assert first
local input, output = string.rep("😂", 2 ^ 16), string.rep("F09F9882", 2 ^ 16)
assert(output == hexencode2(input), "hexencode2")
assert(input == hexdecode2(output), "hexdecode2")
assert(output == hexencode1(input), "hexencode1")
assert(input == hexdecode1(output), "hexdecode1")
```
```sh
❯ nvim -l text3.lua
E5113: Error while calling lua chunk: text3.lua:85: hexdecode1
stack traceback:
        [C]: in function 'assert'
        text3.lua:85: in main chunk
```

**Comment by glepnir** [comment]
wired..

![QQ_1723628161220](https://github.com/user-attachments/assets/13f249fc-2e3e-4831-89f4-5a4a0647c38a)

**Comment by pedrohgmacedo** [comment]
The assertion on the issue description I posted was wrong. Assert takes a boolean and a message. Have you tried changing that?

**Comment by glepnir** [comment]
@pedrohgmacedo  I have updated code snippet could you relook :)

**Comment by pedrohgmacedo** [comment]
Now it works on my machine! The ffi version is even better! 
```sh
❯ nvim -l text3.lua
Benchmarking hexencode1 (ffi-based)...
Time taken: 0.022802
Benchmarking hexdecode1 (ffi-based)...
Time taken: 0.042
Benchmarking hexencode2 (buffer-based)...
Time taken: 0.16047
Benchmarking hexdecode2 (buffer-based)...
Time taken: 0.13613
```

**Comment by gpanders** [comment]
Neovim targets Lua 5.1. `string.buffer` and the `ffi` module are LuaJIT extensions and are not part of Lua 5.1, so we cannot use those in Neovim core. You are free to use FFI in your own plugins of course (but be warned that users who are not using LuaJIT will not be able to use your code).

If you need to encode a very large string, try chunking the string before passing to `vim.text.hexencode`.

**Comment by pedrohgmacedo** [comment]
> Neovim targets Lua 5.1. `string.buffer` and the `ffi` module are LuaJIT extensions and are not part of Lua 5.1, so we cannot use those in Neovim core.

I understand the desire to maintain compatibility. I do not understand not taking advantage of the features the platform on which neovim is built offers. 
If the jit is not supposed to be used (even when available, and when a compatible implementation exists) why then is neovim built with luajit? Just straight up compile it with lua 5.1 without the jit then. 
Is there any platform where neovim is officially distributed not able to use the jit? When I look at the builds, I can only download it with the jit compiled.

**Comment by gpanders** [comment]
>I do not understand not taking advantage of the features the platform on which neovim is built offers.

The platform on which Neovim is built is Lua 5.1.

>f the jit is not supposed to be used (even when available, and when a compatible implementation exists) why then is neovim built with luajit? Just straight up compile it with lua 5.1 without the jit then.

There are benefits to using LuaJIT even without using the separate Lua extensions (performance, primarily).

>Is there any platform where neovim is officially distributed not able to use the jit? 

Yes, there are platforms which package Neovim without LuaJIT, though they are uncommon. This has been discussed in the issue tracker before ([example](https://github.com/neovim/neovim/issues/19849)), feel free to search for other similar discussions.

**Comment by pedrohgmacedo** [comment]
> If you need to encode a very large string, try chunking the string before passing to `vim.text.hexencode`.

Well, then at least it should be documented exactly what is the length limit of the hexdecode function. Just saying `chunk it` is about as helpful as nothing.  The decoding function has a bug, the issue was closed without fixing or addressing it in any way at all.

**Comment by glepnir** [comment]
override it as a hack in your init.lua like `vim.text.hexencode = buffer verison or ffi version` ..

**Comment by gpanders** [comment]
>The decoding function has a bug, the issue was closed without fixing or addressing it in any way at all.

You're right, this should be fixed. But we can't do it with FFI.

**Comment by pedrohgmacedo** [comment]
> override it as a hack in your init.lua like `vim.text.hexencode = buffer verison or ffi version` ..

I already did that, as a matter of fact I had it with the previous version as well. I was just reminding that there is still a bug!

**Comment by glepnir** [comment]
how this bench on your local a pure-lua5.1 version

```lua
local hex_map = {}
local hex_chars = '0123456789ABCDEF'

for i = 0, 15 do
  local char = hex_chars:sub(i + 1, i + 1)
  hex_map[i] = char
  hex_map[char] = i
  hex_map[char:lower()] = i
end

local function hexencode1(str)
  local len = #str
  local enc = {}

  for i = 1, len do
    local byte = string.byte(str, i)
    enc[#enc + 1] = hex_map[math.floor(byte / 16)]
    enc[#enc + 1] = hex_map[byte % 16]
  end

  return table.concat(enc)
end

local function hexdecode1(enc)
  if #enc % 2 ~= 0 then
    return nil, 'string must have an even number of hex characters'
  end

  local len = math.floor(#enc / 2)
  local str = {}

  for i = 1, len do
    local high_nibble = hex_map[enc:sub(i * 2 - 1, i * 2 - 1)]
    local low_nibble = hex_map[enc:sub(i * 2, i * 2)]
    if high_nibble == nil or low_nibble == nil then
      return nil, 'invalid character in input'
    end
    str[#str + 1] = string.char(high_nibble * 16 + low_nibble)
  end

  return table.concat(str)
end

-- The buffer-based functions you provided
local function hexencode2(str)
  local bytes = {}
  local enc = {}
  for i = 1, #str do
    bytes[i] = string.byte(str, i)
  end
  for i = 1, #bytes do
    enc[#enc + 1] = string.format('%02X', bytes[i])
  end
  return table.concat(enc)
end

local function hexdecode2(enc)
  local str = {}
  for i = 1, #enc, 2 do
    local hex = enc:sub(i, i + 1)
    str[#str + 1] = string.char(tonumber(hex, 16))
  end
  return table.concat(str)
end

-- Function to run a benchmark
local function benchmark(func, input, iterations)
  local start_time = os.clock()
  for i = 1, iterations do
    func(input)
  end
  local end_time = os.clock()
  return end_time - start_time
end

-- Prepare input and output for tests
local input, output = string.rep('😂', 2 ^ 16), string.rep('F09F9882', 2 ^ 16)
assert(output == hexencode2(input), 'hexencode2')
assert(input == hexdecode2(output), 'hexdecode2')
assert(output == hexencode1(input), 'hexencode1')
assert(input == hexdecode1(output), 'hexdecode1')

-- Run benchmarks
local iterations = 10

print('Benchmarking hexencode1 (Lua 5.1)...')
print('Time taken:', benchmark(hexencode1, input, iterations))

print('Benchmarking hexdecode1 (Lua 5.1)...')
print('Time taken:', benchmark(hexdecode1, output, iterations))

print('Benchmarking hexencode2 (buffer-based)...')
print('Time taken:', benchmark(hexencode2, input, iterations))

print('Benchmarking hexdecode2 (buffer-based)...')
print('Time taken:', benchmark(hexdecode2, output, iterations))
```

**Comment by gpanders** [comment]
@glepnir I tried your benchmark script against the implementation in https://github.com/neovim/neovim/pull/30075:

```
Benchmarking hexencode1 (Lua 5.1)...
Time taken: 0.038988
Benchmarking hexdecode1 (Lua 5.1)...
Time taken: 0.086294
Benchmarking vim.text.hexencode (#30075)...
Time taken: 0.059076
Benchmarking vim.text.hexdecode (#30075)...
Time taken: 0.336875
```

There is a small improvement in encoding, but not much. There is a much larger difference in the decoding though. I am not sure, but my guess is that this is due to `tonumber`.

**Comment by glepnir** [comment]
used a lookup table (hex_map) to quickly map each character to its corresponding numeric value, rather than relying on tonumber. This approach reduces the overhead of parsing and computation:
1. Character-to-Number Lookup Table:  created a hex_map that directly maps each hexadecimal character (such as 'A' or 'F') to its corresponding numeric value (10 or 15), thereby avoiding the need to call tonumber.
2. Character Combination:  combined the numeric values of the high and low nibble characters to get a complete byte, which is then converted into a character.

Finally, used table.concat to merge these characters into a complete string. use table lookups with CPU cache to reduce the overhead of some common functions.  I also tried to bind the C implementation to Lua, but it took about the same amount of time and didn't improve much.

```
Benchmarking hexencode1 (Lua 5.1)...
Time taken: 0.026796
Benchmarking hexdecode1 (Lua 5.1)...
Time taken: 0.058105
Benchmarking hexencode2 #30075...
Time taken: 0.04042
Benchmarking hexdecode2 #30075...
Time taken: 0.214805
```
