### ISSUE TITLE
Buggy (unnamed) register pasting in insert mode

### ISSUE THREAD

**Issue by Ilya-JBR** [neovim/neovim#30007]
### Problem

when pasting the contents of the unnamed register text gets strangely indented and it takes a long time to paste long texts 

### Steps to reproduce

nvim --clear
:edit init.html
insert

```
<ul>
	<li>List item 1<\li>
	<li>List item 2<\li>
	<li>List item 3<\li>
	<li>List item 4<\li>
	<li>List item 5<\li>
</ul>

```
```
gg
cG
<C-r>"
```

```
<ul>
		<li>List item 1<\li>
				<li>List item 2<\li>
						<li>List item 3<\li>
								<li>List item 4<\li>
										<li>List item 5<\li>
</ul>
```

### Expected behavior

to not take so long to paste moderately long text. 
to not indent the text in an undesired way

### Neovim version (nvim -v)

NVIM v0.10.1

### Vim (not Nvim) behaves the same?

no, 9.1 (2024 Jan 02)

### Operating system/version

openSUSE Tumbleweed x86_64

### Terminal name/version

Yakuake, Kitty 

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by glepnir** [comment]
`nvim --clean -u NONE -c 'set noautoindent'`

**Comment by Ilya-JBR** [comment]
Thank you for your fast reply setting noautoindent fixed the indenting issue, but still it takes a long to paste compared to pasting from system clipboard or any other.

**Comment by zeertzjq** [comment]
It pastes instantly for me.

**Comment by Ilya-JBR** [comment]
Maybe it's just on my side.  What's the best  way to troubleshoot this issue because it happens even with `nvim --clean`.

**Comment by Ilya-JBR** [comment]
https://github.com/user-attachments/assets/da32143e-ad5e-4a04-b20c-750bf769d207

As you can see noautoindent didn't work this time i don't know what happened last time, and if you pay attention it takes 1 or 2 seconds after i press <C-r>" to paste the contents

**Comment by zeertzjq** [comment]
Yes, setting 'noautoindent' won't really work as 'indentexpr' is also set. It's better to use `<C-R><C-O>"` instead of `<C-R>"` for this.

**Comment by Ilya-JBR** [comment]
IMO the behavior above shouldn't be desired because it just adds a layer of complexity without a justification. 
Also what about the latency between pasting.

**Comment by Ilya-JBR** [comment]
well it seems that using `<C-R><C-O>"` both fixes the indenting and the latency. If that is the desired behavior than i will close this issue.

**Comment by justinmk** [comment]
> The slowness is most likely the 'indentexpr' being slow when indenting continuously,

We should make ctrl-r clipboard paste behave identically to bracketed-paste. The autoindent behavior is useless and broken.
