### ISSUE TITLE
Bracketed paste not documented as a difference between vim and  nvim

### ISSUE THREAD

**Issue by skylerberg** [neovim/neovim#3002]
Bracketed paste is supported by nvim out of the box, but not by vim. This difference should be documented. I was excited to stumble upon this change mentioned on reddit, but I don't know how long I would have been typing `:set paste` `:set nopaste` if I had not been serendipitous.

**Comment by paddor** [comment]
+1

**Comment by mhinz** [comment]
I'll write something up. Thanks for the feedback.

**Comment by skylerberg** [comment]
Great! Thanks for making the change!

**Comment by paddor** [comment]
Thanks a lot. :)
