### ISSUE TITLE
Trouble compiling against preinstalled `lpeg` on MSYS2/MinGW

### ISSUE THREAD

**Issue by sewbacca** [neovim/neovim#30022]
### Problem

I've recently submitted a patch to upgrade neovim to 0.10.1 on msys2/MINGW-packages#21522, but we are not sure if the changes should be applied in the msys2 repo or upstream.

**Details**:

Compiling on MSYS2/MinGW using `makepkg`, which in turn runs CMake fails due to issues linking with `lpeg` during compile *and* runtime.

The two problems during compilation are:
1. Linking against lpeg during runtime fails, because CMake looks for an `.dll.a` file and ignores all `.dll` files, which is easily fixable (see msys2/MINGW-packages#6394)
2. Loading `lpeg` during runtime is however not easily fixable. Since Windows requires a `dll` to lie within `PATH`, and Lua modules are not installed into the `PATH` (since they are normally loaded directly via Lua), my patch loads the `dll` via invoking the Lua `package.loadlib` functionality from C.

For a detailed discussion about potential solutions, see msys2/MINGW-packages#21313

### Steps to reproduce

Clone msys2/MINGW-packages and try to build neovim with version set to 0.10.1 using `makepkg`

### Expected behavior

Compiling under MinGW should work like a charm.

### Neovim version (nvim -v)

0.10.0 and 0.10.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Windows 10

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

pacman MSYS/MinGW

**Comment by clason** [comment]
Have you tried compiling from source following the instructions in BUILD.MD?

**Comment by sewbacca** [comment]
Thanks for pointing out the `BUILD.MD` file. I didn't check it out, since I was trying to fix the PKGBUILD. However after reading the doc's I noticed it is remarkably similar to what we've already have (I didn't wrote the existing PKGBUILD).

After some trial and error the issue can be resolved by statically compiling against lpeg. Ideally we would dynamically link against the `lpeg.dll`, since the package is available for MinGW. This is what is causing the compilation issues I am refering to.

**Comment by clason** [comment]
Then this is not a Neovim issue. You're welcome to make it work, of course, but it's not our job.
