### ISSUE TITLE
Add some simple setting for forcing osc52 clipboard provider

### ISSUE THREAD

**Issue by shmerl** [neovim/neovim#30038]
### Problem

Current method of forcing osc52 (which might not be detected well in remote sessions due to failing TUI autodetection) is cumbersome.

It would be easier to put that ennablement behind some simple global flag.

### Expected behavior

Make available some flag like `vim.g.force_osc52` or something like that.

**Comment by justinmk** [comment]
No

**Comment by shmerl** [comment]
Any reason for No?

**Comment by clason** [comment]
> becasue the described issue is an issue.

Not really; it just says "cumbersome", which is a) vague and b) not compelling enough to add features and documentation which have to be maintained (tested).
