### ISSUE TITLE
Treesitter highlighting breaks on long files when directly jumping to the end

### ISSUE THREAD

**Issue by lokesh-krishna** [neovim/neovim#30033]
### Problem

When working on relatively long files (~300 lines), syntax highlighting works when opening the file but breaks if I jump directly to the bottom. I can only get it to syntax highlight later parts of the file if I manually scroll down to it from the top.  
This is also the case when using `nvim --clean`.

### Steps to reproduce

1. Open [(long) file](https://gist.github.com/lokesh-krishna/de77eb2fc7e6acf4e65a5bbfbc6d08f2)
2. Use <kbd>G</kbd> to jump to bottom 
3. There is no syntax highlighting

![image](https://github.com/user-attachments/assets/11fd3f87-dbcd-436f-b425-e0d82e9f0724)
This is the top of the file with working syntax highlighting

![image](https://github.com/user-attachments/assets/63b95135-80f6-463e-a1f9-a51a50532fbe)
And this is what happens when I jump to the bottom

### Expected behavior

Syntax highlighting continues working irrespective of where in the file I jump to

### Neovim version (nvim -v)

NVIM v0.11.0-dev-578+gb04b263e1

### Vim (not Nvim) behaves the same?

Yes, vim 9.1.672

### Operating system/version

Linux

### Terminal name/version

0.35.2

### $TERM environment variable

xterm-kitty

### Installation

AUR (nightly)

**Comment by lewis6991** [comment]
The steps to reproduce are not detailed enough.

**Comment by lokesh-krishna** [comment]
https://gist.github.com/lokesh-krishna/de77eb2fc7e6acf4e65a5bbfbc6d08f2

Link to a file this happens on. What further information would be required? I can reproduce it with `nvim --clean` and syntax highlighting only works for latter parts of the file if I've scrolled down to them at least once. Not if I open the file and directly jump to somewhere near the bottom.

**Comment by lewis6991** [comment]
Exacts steps and commands are required. Avoid descriptions if possible.

Exact commands can be ported to tests.

**Comment by lokesh-krishna** [comment]
1. Open linked file
2. Jump to bottom of file with <kbd>G</kbd>
3. There is no syntax highlighting

These are the steps I need to replicate the issue. I am actually unsure if this is a treesitter issue since I can replicate it even with `nvim --clean` and unless I'm missing something, that doesn't use treesiter.

**Comment by clason** [comment]
Please edit the issue description to add these steps (including `nvim --clean`), as this is what people will see.

**Comment by lokesh-krishna** [comment]
I updated the issue description and while this does happen with `nvim --clean`, it also happens when I have treesitter syntax highlighting enabled. Does that mean it's an issue with both or does Treesitter fallback to syntax file when jumping directly to the end?

**Comment by clason** [comment]
If it happens with treesitter syntax highlighting, we need a reproducing example for that (starting with `--clean`).

**Comment by lokesh-krishna** [comment]
Turns out my treesitter wasn't configured properly. I was missing the `main` spec before `opts`. Works perfectly after fixing that.
