### ISSUE TITLE
Prevent autoindenting of block comments by default

### ISSUE THREAD

**Issue by JonoLF** [neovim/neovim#30035]
### Problem

When autoindenting block comments, the second level of the comment always gets auto-indented. For example a jsdoc comment gets autoindented like so:
![image](https://github.com/user-attachments/assets/0c2a78e3-9ca2-4ed1-8176-9b2568ef636a)
This is with a tabstop of 4.
It also causes a function or the next line of code to be similarly indented.
Additional info:
- using the native lsp with lsp-zero on top and relevant language servers when hitting `=` to auto indent

### Expected behavior

I would expect block comments to follow in line:
![image](https://github.com/user-attachments/assets/a2297dfd-c160-43e8-ba0b-26ab8fe7bdf9)
I apologise if there is something I'm overlooking here, I haven't found anyone else mentioning it and its quite frustrating when shifting things around after having manually indented block comments to their general form.

**Comment by zeertzjq** [comment]
This should be reported to the maintainer of the corresponding indent file under `$VIMRUNTIME/indent`

**Comment by JonoLF** [comment]
Upon further exploration, this actually had to do with incorrect config of treesitter, attaching the link here in case anyone else runs into the same problem: https://github.com/nvim-treesitter/nvim-treesitter/issues/3830
