### ISSUE TITLE
LSP: promote utf-8 and utf-32 positionEncodings

### ISSUE THREAD

**Issue by saecki** [neovim/neovim#30034]
### Problem

#23903 reverted the previous change of (#23871) which promoted all three available `positionEncodings` because there was no support for multiple clients with different `positionEncoding`s attached to the same buffer.
From looking at the code base each client seems to store it's own `offset_encoding` which is read from the server capabilities or defaults to `utf-16` as the spec demands. Was this implemented after the discussion and would this allow re-enabling the client capabilities for other `positionEncodings`?

This would especially make sense for something like rust-analyzer, because the rust spec demands rust files to be utf-8. So the client is working with `utf-8`, the server is working with `utf-8` and both have to convert all character offsets to `utf-16`.

A somewhat related comment from the rust-analyzer codebase: https://github.com/rust-lang/rust-analyzer/blob/f3d9c9df9010ff4dd7b51f200fc772d38c94f006/crates/rust-analyzer/src/lsp/capabilities.rs#L261

### Expected behavior

If possible set the `positionEncodings` client capability to `{ "utf-8", "utf-32", "utf-16" }` or ``{ "utf-8", "utf-16", "utf-32" }``.

**Comment by gpanders** [comment]
cc @mfussenegger

**Comment by mfussenegger** [comment]
Not much changed about the situation. There are still lots of uses of `make_position_params` in combination with `buf_request` / `buf_request_all` - all of which would be broken with mixed encoding.

**Comment by saecki** [comment]
I see

**Comment by lewis6991** [comment]
@mfussenegger with all the multi-client fixes, Is there any progress we can make here?

**Comment by mfussenegger** [comment]
If I'm not mistaken we should be able to add utf-8, and utf-32 to the positionEncodings now. Looks like all the problematic places now pass along the client.offset_encoding.

**Comment by justinmk** [comment]
> because there was no support for multiple clients with different `positionEncoding`s attached to the same buffer.

Do we now support multiple clients with different encodings attached to the same buffer?

**Comment by lewis6991** [comment]
Yes, I believe so.
