### ISSUE TITLE
claim ":te" for ":terminal"

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3003]
Currently, the shortest abbreviation of `:terminal` is `:term`. Neovim will never have a `:tearoff` command, so we should claim `:te` as the shortest abbreviation of `:terminal`. We should also remove the ex_ni placeholder that apparently exists for `:tearoff`.

**Comment by lucc** [comment]
`:t` is a synonym for `:copy`. I assume that is some vi backwards compatibility stuff as the help entry does not give any other info and I consider this a fairly unintuitive command (there is not even a long version). Maybe we can *also* use `:t` as a short version for `:terminal`.

Is there a way to search for the use of `:t` in existing vim scripts?

**Comment by ZyX-I** [comment]
@lucc I do not think that such search has any value. This synonim is clearly for writing by hand.

By the way, why GUI is not going to have `:tearoff`? I am not actually using it (I do not use GUI Vim versions at all) and thus do not really understand what exactly it is supposed to do, but if it exists then there should be some reason.

**Comment by justinmk** [comment]
> By the way, why GUI is not going to have :tearoff?

@ZyX-I  Ignoring my speculation that it's a useless feature, here are some non-speculative reasons:

- It is not consistent across GUIs. Neovim core project goal is to provide consistent features across all targets.
    - Vim doesn't support the feature on OS X, and I'm not sure if latest GTK supports it.
- It cannot meaningfully be supported in a TUI.

Even if we _do_ decide to support `:tearoff`, it does not deserve `:te`. (IMO it does not even deserve _any_ command: it should be crammed away in an API call. Those who want it can add a mapping or user command.)

**Comment by ZyX-I** [comment]
I agree that it does not deserve `:te`, from the description it looks like a pure-script command (command only useful for plugin writers, placing it inside vimrc bound to some mapping or like this).

**Comment by mhinz** [comment]
I agree that a short command like `:te` shouldn't be wasted on a command no one knows about or uses on-the-fly.
