### ISSUE TITLE
API for finding external dependencies

### ISSUE THREAD

**Issue by mrcjkb** [neovim/neovim#30036]
### Problem

If a plugin has external dependencies, users must specify them manually (e.g. via a config or an environment variable).

Example: [sqlite.lua](https://github.com/kkharji/sqlite.lua)

### Expected behavior

Luarocks has [a mechanism for auto-detecting external dependencies](https://github.com/luarocks/luarocks/blob/f87568a7cba69e2c19411e7a2b73016c80a14a3b/src/luarocks/deps.lua?plain=1#L619), which 

- Falls back to a config if the auto-detection fails.
- Errors if auto-detection fails and there is no config.

If Neovim had an API for a similar mechanism:

- Less users would have to declare external dependencies manually.
- Configurations for external dependencies could be reused across multiple plugins.
- The responsibility for declaring external dependencies is shifted from the user to the plugin author.

Note: The hand-rolled luarocks implementation of auto-detection doesn't work on some systems. Perhaps something that delegates to pkg-config would be more reliable.

Thoughts? :thinking: 

[[related issue]](https://github.com/nvim-neorocks/nvim-best-practices/issues/20)

**Comment by mrcjkb** [comment]
cc @teto

**Comment by clason** [comment]
Did you mean to comment that on neovim/packspec?

**Comment by mrcjkb** [comment]
No, I don't think this is a packspec issue (it wouldn't be used during installation).
The API would be useful for retrieving external libraries at runtime (e.g. for use with `ffi`).

**Comment by justinmk** [comment]
This seems clearly out of scope. Is this not equivalent to becoming a generalized package manager?

Downloading a https://github.com/neovim/packspec/ tree and installing to 'runtimepath' is in-scope because it's a very narrow and well-defined scope. Whereas "find things on my system" is 100% undefined.

**Comment by mrcjkb** [comment]
This has nothing to do with package management or installing dependencies. It's about *being able to use those dependencies* at runtime. A package manager can't help with that, unless it either becomes a dependency itself (which would be a terrible idea), or there's a standard for providing plugins with the information (so that the package manager doesn't need to be aware of the implementation details of the plugins it manages).
The lesser evil would be a Lua library that wraps `pkg-config`.

**Comment by clason** [comment]
Sorry, but plugins are checking for external dependencies just fine already (`vim.uv`, `vim.system`, `vim.fn.executable()` and friends). I don't see how we can seriously improve on that without landing in maintenance hell. ("External dependencies" is a _negative_ description -- "everything not builtin" -- so this is an impossibly wide scope.)

**Comment by mrcjkb** [comment]
I'm specifically talking about C libraries that can be used with FFI.
I agree that Neovim has more than enough for *external applications*, but when it comes to *C libraries* there's no consistency,
with plugins usually relying on users to tell them where to find them.

Some examples:

- sqlite.lua expects users to set something like `let g:sqlite_clib_path = path/to/sqlite3.dll` or a `LIBSQLITE` environment variable.
- telescope-zf-native.nvim [checks pre-built libraries into scm](https://github.com/natecraddock/telescope-zf-native.nvim/tree/beb34b6c48154ec117930180f257a5592606d48f/lib)
- fugit2.nvim has a `libgit2_path` field in its `setup` options.

I do acknowledge that the scope may still be too broad for Neovim, although in the case of pkg-config it's very well-defined.

**Comment by justinmk** [comment]
> or there's a standard for providing plugins with the information

The standard is $PATH / 'runtimepath' / Lua `package.cpath`.

> The lesser evil would be a Lua library that wraps `pkg-config`. ... I'm specifically talking about C libraries that can be used with FFI.

Questions for consideration (not meant to be contentioius):

- What would Nvim do beyond invoking `pkg-config` ? 
- If this use-case is well-defined, why doesn't `pkg-config` (or some other tool) provide it?

**Comment by mrcjkb** [comment]
Afaik (I may be mistaken), `package.cpath` is intended for Lua C libraries built against the Lua headers (i.e. it should be possible to `require` modules on there, and it would be possible, but not ideal, to pollute it with other stuff).
`runtimepath` could be an option (that's what telescope-zf-native.nvim uses).

> What would Nvim do beyond invoking pkg-config

Nothing. Probably just a wrapper for a Lua API.
But pkg-config might not be the best fit for this use case, as it's intended for use at compile time.

> If this use-case is well-defined, why doesn't pkg-config (or some other tool) provide it?

I don't understand this question. Are you asking why pkg-config doesn't have a Lua API?

**Comment by dundargoc** [comment]
pkgconfig isn't available by default on windows, this would either be optional or we'd have to ship pkgconfig.

**Comment by clason** [comment]
> I'm specifically talking about C libraries that can be used with FFI.

Since Neovim only guarantees PUC Lua (LuaJIT is recommended for performance reasons but not required), FFI is not officially supported so _definitely_ out of scope. If plugins rely on that, they're on their own.

**Comment by justinmk** [comment]
> > If this use-case is well-defined, why doesn't pkg-config (or some other tool) provide it?
> 
> I don't understand this question. Are you asking why pkg-config doesn't have a Lua API?

If "find a C library on the system" is well-defined or at least well-trodden, then there should be a CLI tool that does it. Then Nvim can invoke it. If such a tool doesn't exist, that's a hint that we are entering undefined territory.

OTOH, we already do similar dirty work for provider resolution (finding interpreters for node/python/etc). Adding to a list of common search paths isn't too onerous, though it gets tricky when special environment variables and other library-specific lore are involved. Then it becomes a question of how to help users troubleshoot the search-order, "why isn't my library found", etc.

I'm open to this idea except it becomes much less compelling for the reason @clason mentioned , which is that FFI is not where we want to invest core features.

**Comment by mrcjkb** [comment]
> then there should be a CLI tool that does it.

pkg-config is such a CLI tool.

> except it becomes much less compelling for the reason @clason mentioned , which is that FFI is not where we want to invest core features.

Agreed. I haven't realised that FFI is luajit only. 
With that in mind, it would probably be better to create a separate Lua library (preferably not tied to Nvim) that plugins can use.
