### ISSUE TITLE
synIDattr doesnt give correct values

### ISSUE THREAD

**Issue by pvinis** [neovim/neovim#3004]
i use iterm with truecolor, and nvim with truecolor.

i was trying to make `VertSplit` guifg the same as Identifier guifg. one way i found to do that is the one below.
`Identifier` has `ctermfg=1 guifg=#cc6666`. i did `execute 'hi! VertSplit guifg='. synIDattr(hlID('Identifier'), 'fg#')` but then my `VertSplit` had `guifg=1`.

`:echo synIDattr(hlID('Identifier'), 'fg')` this gives 1, as it should, since its the cterm one i guess.
`:echo synIDattr(hlID('Identifier'), 'fg#')` this also gives 1, but i guess it should give `#cc6666` since its the `guifg` one.

**Comment by pvinis** [comment]
#3005

**Comment by Pyrohh** [comment]
@mhinz can this be closed?

**Comment by mhinz** [comment]
Yup, thanks for reminding me!
