### ISSUE TITLE
`colorscheme vim` (bg=light) in init.vim ignores other custom highlights

### ISSUE THREAD

**Issue by vladdeSV** [neovim/neovim#30048]
### Problem

In `init.vim`, setting `colorscheme vim` ignores other `hi` commands. However, running the same highlight command after start works as expected.

### Steps to reproduce

Loading this file has the line numbers still using the default color
```vim
" ~/.config/nvim/init.vim
set notermguicolors 
colorscheme vim

hi LineNr ctermfg=7
set nu
```

… but manually running `:hi LineNr ctermfg=7` sets the correct colors.

(In this example I use `notermguicolors`, but the result is the same without it, and the highlight rule uses `guifg` instead – it does not get applied on load. Also, I have aliased `vim` to `nvim`, so it actually is Neovim that is being run)

![Kapture 2024-08-14 at 16 15 34](https://github.com/user-attachments/assets/39aae996-b987-4e81-b6ba-7f1359561163)

### Expected behavior

I would expect my highlight rules after the `colorscheme vim` to apply, and not have to run them manually.

### Neovim version (nvim -v)

0.10.1 Release

### Vim (not Nvim) behaves the same?

no, N/A

### Operating system/version

macOS 14.5

### Terminal name/version

iTerm2 3.5.4

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by vladdeSV** [comment]
Hey @zeertzjq.

Sorry, this is really weird, but could you please turn on light mode in you system settings?

If I set my macOS system setting to "Light Mode", I can reproduce the problem
<img width="97" alt="image" src="https://github.com/user-attachments/assets/7f8d1468-4761-4ac9-a33a-d77e64aa46f6">

… but with "Dark Mode", the problem disappears.

![Kapture 2024-08-15 at 08 51 44](https://github.com/user-attachments/assets/21b9fb9c-24db-43a5-bc37-b993f86c28f4)

**Comment by saccarosium** [comment]
Try to define a autocmd with `ColorScheme` it should do the trick (`:h ColorScheme`)

```vim
function! SetHighlights()
  if &background == "dark"
    " on dark background
  elseif &background == "light"
    " on light background
  endif
endfunction

autocmd ColorScheme * call SetHighlights()
```

**Comment by vladdeSV** [comment]
@justinmk Is this fixed? I still see this problem in v0.10.2

**Comment by vladdeSV** [comment]
Is the command `colorscheme vim` is still broken then?

The proposed fix is the workaround to manually individually set the colors of the vim color scheme?

**Comment by zeertzjq** [comment]
Add the custom highlights to the `" on light background`

**Comment by vladdeSV** [comment]
I already do this in https://github.com/vladdeSV/dotfiles/commit/68fadbcbad3e2cf32c5bed702f28b529fe36231b. I have to manually add everything that `colorscheme vim` is supposed to do.

It was so frustrating before I knew that "having my computer in light mode" would cause all my syntax highlighting to break.

Why is this? This is not a resolution.

**Comment by vladdeSV** [comment]
Personally, I would like this to either
a) have this issue re-opened
b) get an official stance statement that this broken functionality is intended

I apologize if I sound rough or crude. It feels like this issue that I had tons of trouble with in the past is not being herd out properly. I really appreciate the time and effort other people put into this project.

**Comment by clason** [comment]
https://gist.github.com/romainl/379904f91fa40533175dfaec4c833f2f

**Comment by vladdeSV** [comment]
I'm sorry, I do not want any custom syntax highlight in this scenario. The default highlight "broke" in v0.10.

In v0.10, you now had to set `notermguicolors`, and then call `colorscheme vim` – but this caused the theme to reset when the computer is in light mode; this is *unexpected* and, in my eyes, a bug.

Could I please get any verbal confirmation that my issue is being heard? If my computer is set to light mode, calling `colorscheme vim` causes **ALL** the syntax highlight to reset, both the default and my custom highlights.

**Comment by vladdeSV** [comment]
> I am sorry, but that is literally what you describe in the issue,

You are correct. I got this mixed up. My bad, apologies.

My issue boils down to this: why do I need to apply some special case when my computer is in light mode?

Why do I need this snippet to apply my own color schemes **when in light mode**? Why just light mode? Why does everything work fine in dark mode, but not light mode.

**Comment by clason** [comment]
Because the legacy (Vim) default scheme assumes dark mode; there's no separate set of definitions for `bg=light`.

**Comment by clason** [comment]
No, the default (Nvim) colorscheme defines both light and dark bg variants. (That's one of the big improvements.)

**Comment by vladdeSV** [comment]
> Because the legacy (Vim) default scheme assumes dark mode; there's no separate set of definitions for bg=light.

I don't think this is correct. When I start Nvim with the legacy color scheme, the colors change depending on wether I am in dark or light mode. (screenshots at the bottom)

Take this problem that occurs for me, and please tell me if my reasoning is off or misguided. I have a custom syntax file in `syntax/klog.vim`, and this line in my init.vim `autocmd BufRead,BufNewFile *.klg set filetype=klog`

When my computer is in light mode, when I open my file `nvim time.klg`, my custom syntax highlight is cleared. If then run `:e time.klg`, the same file loads but **with** my custom syntax.

To me, it seems like when Nvim first starts up, it waits until the file has loaded, and then clears the syntax to apply the light legacy Vim color scheme.

## Screenshots of legacy Vim in both dark and light mode
They use different colors with `colorscheme vim`

![Image](https://github.com/user-attachments/assets/7ce785e0-6f87-4375-bb77-c32ee5db3216)

![Image](https://github.com/user-attachments/assets/212ca102-1fc7-447d-a12c-0168c86faad8)

**Comment by clason** [comment]
> I don't think this is correct. When I start Nvim with the legacy color scheme, the colors change depending on wether I am in dark or light mode. (screenshots at the bottom)

You are testing with `notermguicolors`, where you will get your terminal colors -- which very well may change with the background (by being changed _by the terminal_).

**Comment by vladdeSV** [comment]
> which very well may change with the background (by being changed by the terminal).

Sorry for not specifying this earlier. In those screenshots, the ANSI colors are the same. I can guarantee you that this is not my terminal switching the ANSI colors (only background, foreground, and the cursor get switched)

I still think that the legacy Vim color scheme has different colors for the light and dark mode.

![Image](https://github.com/user-attachments/assets/c206aff5-c706-4458-95cd-616138337bce)
![Image](https://github.com/user-attachments/assets/cd4c128a-4634-403c-a598-5ae4c1a61bf0)


Could I please get any acknowledgement of the issue I am experiencing?

> To me, it seems like when Nvim first starts up, it waits until the file has loaded, and then clears the syntax to apply the light legacy Vim color scheme.

**Comment by saccarosium** [comment]
Vim sets in most cases `background` to light. Neovim defaults to dark so it is possible that when using the default colorscheme with the terminal palette set to light but neovim as `background` set to dark some colors will be scuffed.

Try to forcefully set background to light when using light mode on the mac and see if gets better

```vim
set background=light
colorscheme vim
```

If I got this correctly the only thing you can do to make this automatic is either:
1. use a terminal that supports the specific escape sequence that neovim uses to check whether to use dark or light background (in my case I use wezterm)
2. if you want to still use you current terminal (I think you are using iTerm2) you need to check manually whether or not MacOS is in lightmode and switch the background before the colorscheme is loaded with `ColorSchemePre`

```vim
function s:check_background()
  " NOTE: this can definitely increase your startup time 
  " depending on how much time the command used takes to execute 
  let macos_theme = system(<insert command to check macos apperence>)
  if macos_theme ==# 'light'
    set background=light
  endif
endfunction
autocmd ColorSchemePre * call s:check_background()

" all the color ovverrides and setting colorscheme goes here
```

Another alternative may be some plugins but I'm not sure

**Comment by vladdeSV** [comment]
This is a workaround to solve my issue on macOS, such that I can use the default color scheme with my own highlights!

```vim
function s:check_background()
  let macos_theme = system("defaults read -g AppleInterfaceStyle 2>/dev/null")
  if macos_theme ==# ''
    set background=light
  else
    set background=dark
  endif
endfunction
autocmd ColorSchemePre * call s:check_background()

set notermguicolors
colorscheme vim
```

I wish I didn't have to have this snippet in my init file, and this isn't cross platform either, but for now this works for me for now.

If the developers would like to reopen this issue I'd be more than happy. Manually setting the background before running `colorscheme vim` does not clear my syntax highlight that are applied once Neovim opens. I don't know how I'd handle this on my non-macOS machines.

**Comment by saccarosium** [comment]
> I wish I didn't have to have this snippet in my init file, and this isn't cross platform either, but for now this works for me for now.

Unfortunately we cannot do that much to make this more cross platform. We have a mechanism to detect this but it is terminal dependent. Terminal applications do not have the same APIs that GUIs have to detect this sort of things. If we create our own it would probably be junky an hassle to maintain.

> I don't know how I'd handle this on my non-macOS machines.

I think there are plugins for this I DIDN'T TEST THEM:
- [darkman.nvim](https://neovimcraft.com/plugin/4e554c4c/darkman.nvim/) (Linux only)
- [auto-dark-mode](https://neovimcraft.com/plugin/f-person/auto-dark-mode.nvim/) (Cross-platform)

**Comment by dstein64** [comment]
Here's another workaround to prevent highlight groups defined in `init.vim` from being cleared (by running the command asynchronously).

Before:

```vim
highlight HighlightGroup ctermfg=4 guibg=Blue
```

After (Vimscript):

```vim
call timer_start(0, {-> execute('highlight HighlightGroup ctermfg=4 guibg=Blue')})
```

After (Lua):

```lua
vim.defer_fn(function()
  vim.api.nvim_set_hl(0, 'HighlightGroup', { ctermfg = 4, bg = 'Blue' })
end, 0)
```
