### ISSUE TITLE
Link highlight groups with extra arguments

### ISSUE THREAD

**Issue by h3xOo** [neovim/neovim#30041]
### Problem

Let's say I want to override highlight group Foo, which I'd like to be like Bar, but with italics. The following snippet:
```lua
vim.api.nvim_set_hl(0, "Foo", { link = "Bar", italic = true })
```
is accepted by neovim (no errors on startup), but visually Foo is still the same as Bar (although `hi Foo` gives `cterm=italic gui=italic links to Bar`). 

### Expected behavior

Foo will visually look like Bar but with italic.

**Comment by clason** [comment]
That's just how highlights work; ypu are setting two properties (link and italics), and the forst overrides the second. Either olay around with "combine" properties, or -- better yet -- use the get_hl method, modify the return table, and pass the modfied table.
