### ISSUE TITLE
Executing `:Man` pollutes v:errmsg

### ISSUE THREAD

**Issue by adigitoleo** [neovim/neovim#30051]
### Problem

Reproduce using `nvim -u NORC --headless -c 'Man nvim' -c 'echo v:errmsg'`

**Description:**

In headless mode, the result of `:Man nvim` is not the same as in interactive mode. Specifically, a E486 pattern match error is thrown, coming from line 482 of the `man.lua` plugin. This causes issues with my test suite as it masks other expected errors (invalid arg).

The error message is:

`E486: Pattern not found: \s\{199,}^C`

The offending line contains:

     vim.cmd([[silent! keeppatterns keepjumps %s/\s\{199,}/\=repeat(' ', 10)/g]])

So either the man page contents are not being loaded properly in headless mode, or the search is failing for another reason. I wonder if it is possible to add a `nvim_list_uis()` check somewhere after the argument handling/before the offending substitution command. Otherwise, the whole plugin should maybe check for UIs and abort loading otherwise.

### Steps to reproduce

    nvim -u NORC --headless -c 'Man nvim' -c 'echo v:errmsg'

### Expected behavior

Headless mode does not represent a hazard to test suite, because the behaviour of `:Man` is predictable based on UI mode.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-610+g32d17cb6d

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Void Linux 6.6.44_1 x86_64 glibc

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

xterm-256color

### Installation

source build

**Comment by zeertzjq** [comment]
What does this have to do with headless mode? The same happens without `--headless`.

**Comment by adigitoleo** [comment]
>  The same happens without --headless

My mistake, I had the incorrect memory that `v:errmsg` stuff shows up in `:messages` so that's what I was checking in normal UI mode. I can probably figure out a workaround in that case, if #30052 is not accepted.

**Comment by adigitoleo** [comment]
I found that what I actually wanted to check in my test suite was probably `vim.fn.split(vim.fn.execute('messages'))`. Perhaps the docs for `v:errmsg` could clarify the distinction from `:messages`, currently all it says is:

> Last given error message.
