### ISSUE TITLE
update set_vim_var_dict() from 7.4.774

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3006]
7.4.774 only decrements `dv_refcount` if `(val != NULL)`.  

https://github.com/vim/vim/commit/28bbbe49f14bd2bb986bcb20ebc99c879da9da10#diff-de9ab8906fef668ed8042046e0a1eb02R20595

cc @Shougo

**Comment by Shougo** [comment]
It seems good.
Yes, neovim should include it.
