### ISSUE TITLE
Using a skeleton file with `autocmd BufNewFile` and then calling `*CTRL-^* *CTRL-6*` open skeleton file in a new buffer

### ISSUE THREAD

**Issue by epilys** [neovim/neovim#30067]
### Problem

First, configure an `autocmd` that uses a skeleton template file when opening a file that matches a specific glob:

```vim
if has("autocmd")
  augroup templates
    autocmd BufNewFile *.myformat 0r /tmp/skeleton.myformat
  augroup END
endif
```

Reload the configuration. Then open a new file that matches that glob, e.g. `_.myformat`. This will autopopulate the buffer with the contents of `/tmp/skeleton.myformat` as expected. If you at any point use the "go to previous buffer" shortcut, `C-^`, **without** first switching to another buffer manually (by name or number), a new buffer will be made visible, that of the skeleton file.

### Steps to reproduce

vim _.myformat

### Expected behavior

Skeleton file should not ever appear in the buffer list

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

yes, 9.1.496

### Operating system/version

any

### Terminal name/version

any

### $TERM environment variable

any

### Installation

any

**Comment by epilys** [comment]
<https://github.com/vim/vim>: #15513

**Comment by zeertzjq** [comment]
Looks like the solution is `:set cpo-=a`
