### ISSUE TITLE
`vim.api.nvim_buf_get_name()` use backslash('\') although `vim.opt.shellslash` is true in windows

### ISSUE THREAD

**Issue by Jaehaks** [neovim/neovim#30071]
### Problem

if `vim.opt.shellslash` is true, neovim recognizes path delimiter as '/'
so the result of `vim.fn.expand()` use slash instead of backslash in windows. 
but The `vim.api.nvim_buf_get_name()` doesn't be applied.

### Steps to reproduce

1. open nvim
2. set `vim.opt.shellslash = true`
3. see `lua =vim.api.nvim_buf_get_name(buf_id)`
4. see `lua =vim.fn.expand('%:p')

### Expected behavior

Delimiter of result of `vim.api.nvim_buf_get_name()` changes to slash when User set `vim.opt.shellslash` true

### Neovim version (nvim -v)

v0.10.0

### Vim (not Nvim) behaves the same?

no, vim doesn't have nvim_buf_get_name function

### Operating system/version

Windows 10

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

scoop

**Comment by zeertzjq** [comment]
No
