### ISSUE TITLE
neovim fails to set the filetype to c with "Attempt to call global 'C_INCLUDE_HEADER_CLEANUP' (a nil value)" error

### ISSUE THREAD

**Issue by joshua-holmes** [neovim/neovim#30087]
### Problem

`runtime/filetype.lua` fails to execute vim command `setf c` with error message "Attempt to call global 'C_INCLUDE_HEADER_CLEANUP' (a nil value)". Running `:setf c` succeeds in vim v9.1, but fails in neovim v10.1 (latest stable release) and v0.11.0-dev-632+g33464189bc (`neovim-git` from AUR)

### Steps to reproduce

1. Open any C file with neovim, such as this one:
```c
#include <stdio.h>

int main() {
    printf("Hello world!\n");
    return 0;
}
```
2. Execute neovim command `:setf c`

### Expected behavior

- No error message
- Neovim is able to set my LSP to clangd, which it cannot do while this command fails

### Neovim version (nvim -v)

v10.1 and v0.11.0-dev-632+g33464189bc

### Vim (not Nvim) behaves the same?

no, vim v9.1 behaves as expected

### Operating system/version

Arch Linux, kernal version: 6.10.4-arch2-1

### Terminal name/version

kitty 0.35.2

### $TERM environment variable

xterm-kitty

### Installation

AUR, tried both `neovim` and `neovim-git`

**Comment by joshua-holmes** [comment]
Forgot to add a photo. Here's what it looks like when I open a C file, say with `nvim main.c`:
![image](https://github.com/user-attachments/assets/d62f8281-6e8c-4b19-b871-49781009c20e)

Here's what it looks like when I attempt to execute `:setf c` manually after opening a C file:
![image](https://github.com/user-attachments/assets/38c65762-8cda-41fd-8728-3cb9d0668a9e)

**Comment by zeertzjq** [comment]
This is a problem with your config

**Comment by clason** [comment]
Screenshots are not useful; replicating with `nvim --clean` is.

**Comment by joshua-holmes** [comment]
Thanks for the nudge in the right direction. It was a config issue.
