### ISSUE TITLE
nvim in windows terminal

### ISSUE THREAD

**Issue by oison111** [neovim/neovim#30088]
### Problem

Previously, when opening nvim in windows terminal , the background was transparent, but now it is opaque. How can I solve this problem？

### Steps to reproduce

nvim foo

### Expected behavior

the background is transparent

### Neovim version (nvim -v)

NVIM v0.10.1

### Vim (not Nvim) behaves the same?

..

### Operating system/version

windows 11

### Terminal name/version

windows terminal

### $TERM environment variable

xterm-256color

### Installation

scoop install nvim

**Comment by zeertzjq** [comment]
`:h news-0.10`

**Comment by oison111** [comment]
> `:h news`

thank you very much!  i get it!!

**Comment by AH-Merii** [comment]
For anyone else seeing this:  
In Neovim 0.10 (`:h news-0.10`), `termguicolors` is now enabled by default if the terminal supports true color.  
This can cause the background to become opaque and break terminal transparency.

**Fix:** disable it in your config with:

```lua
vim.opt.termguicolors = false
```

**Comment by elyosemite** [comment]
@AH-Merii  It works to me! Thank you!!
