### ISSUE TITLE
Program freeze when executing a particular macro

### ISSUE THREAD

**Issue by Dook97** [neovim/neovim#30093]
### Problem

Presume the binding `vim.keymap.set('n', '<space>e', '<cmd>lua vim.diagnostic.setloclist({severity="error"})<CR>', bufopts)`

Then open a buffer with LSP attached and some diagnostic messages and record a macro: `qq<space>e<CR>q`

Invoking this macro freezes neovim. I bumped into this while defining a macro to correct the same error which appeared on several lines (imagine something like a missing semicolon).

It seems to be independent of the specific language server. Happens with clangd and ruff (python server).

### Steps to reproduce

above

### Expected behavior

no freeze

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1723675123

### Vim (not Nvim) behaves the same?

no lsp in vim

### Operating system/version

Linux 6.6.46-1-lts SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

### Terminal name/version

st v0.9

### $TERM environment variable

xterm-256color 

### Installation

pacman

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by justinmk** [comment]
Did you try removing all unrelated plugins? I.e. only `nvim --clean` and maybe nvim-lspconfig should be enabled.
