### ISSUE TITLE
Set highlight groups for LSP completion kinds

### ISSUE THREAD

**Issue by flexagoon** [neovim/neovim#30118]
### Problem

There's currently no way to highlight different LSP Completion kinds with different colors like third-party completion plugins do, since the extra `hl_group` param is always set to an empty string for them: https://github.com/neovim/neovim/blob/e48179f31e6503bfa86bf08538e64456e96446a8/runtime/lua/vim/lsp/completion.lua#L256

### Expected behavior

Set `hl_group` to the value of `kind` to allow theming them separately.

However, this will be resolved if #30112 is implemented, so perhaps this is not actually something that is needed? This request is easier to implement, at least as a temporary solution, but you can close this issue if #30112 is preferred over this.

**Comment by mfussenegger** [comment]
With https://github.com/neovim/neovim/pull/30060 there's now the option to customise hl_group

**Comment by flexagoon** [comment]
Awesome, thanks!
