### ISSUE TITLE
Allow to configure visible completion menu sections

### ISSUE THREAD

**Issue by flexagoon** [neovim/neovim#30119]
### Problem

The `menu` field of completion items is sometimes way too long:

![image](https://github.com/user-attachments/assets/548a46c5-2a40-4270-97a5-ae4eea3526d8)

It would be great to have a way to hide this field if you don't need it

### Expected behavior

You should be able to hide specific completion item fields using `'completepopup'` or some other option

**Comment by flexagoon** [comment]
This is now addressed by #30060 for the mentioned use case, though I will still live it open since it may also be needed for non-LSP completions

**Comment by glepnir** [comment]
you mean default completion mode or what ?

**Comment by flexagoon** [comment]
My original use case was for LSP completion, and that's now fixed. However, if someone uses the native completion menu without `vim.lsp.completion` (eg. with custom logic or through other plugins), there's still no way to hide specific fields.

Perhaps #27287 is related

**Comment by glepnir** [comment]
Hide a specific field? You just need to set it to empty. If you use the complete function, there is no such problem for the default completion mode.

**Comment by flexagoon** [comment]
Oh, right, I guess that makes sense, thanks!
