### ISSUE TITLE
Highlight groups for completion kinds 

### ISSUE THREAD

**Issue by flexagoon** [neovim/neovim#30112]
### Problem

The documentation for [`complete-items`](https://neovim.io/doc/user/insert.html#complete-items) says the following:

> The "kind" item uses a single letter to indicate the kind of completion.  This
may be used to show the completion differently (different color or icon).

However, it does not seem like there are highlight groups for different completion kinds, so it's not possible to theme them separately 

### Expected behavior

There should be highlight groups or some other way to theme specific completion item kinds

**Comment by zeertzjq** [comment]
Added in #30128
