### ISSUE TITLE
Neovim msi installer windows 10 64

### ISSUE THREAD

**Issue by gGameDevelop** [neovim/neovim#30125]
### Problem

When i install nvim from msi installer file, on win10_x64 after repower my pc i open cmd and type nvim, it clear my console and show $qm and exit i try opening executable app and the same thing it shows $qm and exit.

### Steps to reproduce

nvim
nvim -U NONE

### Expected behavior

Opening nvim for first time without plugins

### Neovim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

no, vim 9.00

### Operating system/version

Windows 10

### Terminal name/version

CMD

### $TERM environment variable

1511

### Installation

MSI installer

**Comment by clason** [comment]
> 1511

There's your issue. Make sure your `$TERM` is set correctly.

**Comment by gGameDevelop** [comment]
I set up the environment variables and checked the config files. This is the first time i tried to install it

**Comment by gGameDevelop** [comment]
I google it, and i have not found any one that have my problem. i follow the installation steps of one video on youtube. But he downloaded the zip file, not the msi installer. i tried to install it, but it was the same thing show $qm and exit.
