### ISSUE TITLE
Nvim not working also when i set up environment variables on windows

### ISSUE THREAD

**Issue by gGameDevelop** [neovim/neovim#30126]
### Problem

After writing nvim on cmd it shows $qm and exit

### Steps to reproduce

nvim
nvim -u NONE
nvim --nopluggin

### Expected behavior

Opening nvim

### Neovim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

no, vim 9.000, vim works correctly without this issue

### Operating system/version

Windows 10 64bit

### Terminal name/version

CMD windows 1511

### $TERM environment variable

C:\Program Files\Neovim\bin

### Installation

MSI installer file, and the zip archive

**Comment by clason** [comment]
Duplicate of #30125 

Please open duplicate issues. If you need help setting up Neovim, ask on Matrix.

**Comment by gGameDevelop** [comment]
Sorry. But please help me

**Comment by gGameDevelop** [comment]
Or if you can, please tell me the correct steps to follow.

**Comment by gGameDevelop** [comment]
Please, answer 🙏
