### ISSUE TITLE
When I move the cursor at the end of a very long line, it lags.

### ISSUE THREAD

**Issue by TinyProbe** [neovim/neovim#30129]
### Problem

When I move the cursor at the end of a very long line, it lags.

OS: Linux Mint 22 x86_64 
Host: MS-7C82 1.0 
Kernel: 6.8.0-41-generic 
Uptime: ? hour, ?? mins 
Packages: ? (dpkg), ? (brew) 
Shell: bash 5.2.21 
Resolution: 2560x1440 
DE: GNOME 46.0 
WM: Mutter 
WM Theme: Mint-Y 
Theme: Mint-L-Dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: kitty 
CPU: Intel i7-10700 (16) @ 4.800GHz 
GPU: NVIDIA GeForce RTX 2070 SUPER 
Memory: 4170MiB / 32031MiB 

### Steps to reproduce

$ for ((i = 0; i < 100000; ++i)); do echo -n "hello " >> tmp; done;
$ nvim tmp
(press $) move cursor via arrow key.

### Expected behavior

When I move the cursor at the end of a very long line, it lags.
It moves in choppy, not smooth motions.
It's smooth in vim.

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1724232689

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.1 (2024 Jan 02, compiled May 03 2024 02:45:42)

### Operating system/version

linux mint 22 wilma

### Terminal name/version

kitty 0.35.2 created by Kovid Goyal

### $TERM environment variable

xterm-kitty

### Installation

linuxbrew

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by TinyProbe** [comment]
i use zsh

**Comment by TinyProbe** [comment]
When you say it's not reproducible, does that mean that you couldn't do the same thing and get the same results? Or does it mean that you can't follow the process to reproduce it?

**Comment by zeertzjq** [comment]
Actually I may now be able to reproduce it. Does `:autocmd! matchparen` fix the problem?

**Comment by TinyProbe** [comment]
It works fast. I hope it gets reflected in the next version.
