### ISSUE TITLE
has("python") is always false

### ISSUE THREAD

**Issue by michael-brade** [neovim/neovim#3012]
Hi all, I have compiled neovim myself, the python development headers (libpython3.4-dev on debian) are installed, and /usr/bin/python and /usr/bin/python3 executables exist. Still, if I do

```
if !has('python') && !has('python3')
  echo 'no python support'
  finish
endif
```

I get no python support. How can I debug this? What am I missing? Or is it a known bug? ccmake does not show any variable with regards to python.

**Comment by Pyrohh** [comment]
Have you read `nvim_python.txt` (in the internal help system)? I ask because you haven't said anything about the `neovim` pip package.

**Comment by ZyX-I** [comment]
Also libpython3.4-dev is not needed for NeoVim.

**Comment by michael-brade** [comment]
Yes, I read it but didn't know and misinterpreted what pip was. Now I also installed the neovim pip package (for which you do need libpython3.4-dev). However, it still does not work as far as I am concerned: start neovim, enter

    :python3 print("hello")

and get
```
Vim(if):Channel was closed by the client

Failed to load Python host. You can try to see what happened by starting Neovim with the environment
variable $NVIM_PYTHON_LOG_FILE set to a file and opening the generated log file. Also, the host
stderr will be available in Neovim log, so it may contain useful information. See also ~/.nvimlog.

Error detected while processing function provider#python3#Call:                       
line 15:
E168: :finish used outside of a sourced file
Press ENTER or type command to continue
```

I did set the NVIM_PYTHON_LOG_FILE variable, and nvim creates the file but nothing is written to it (it stays 0 bytes), and .nvimlog contains nothing but "Starting Neovim main loop."

**Comment by fwalch** [comment]
Hm.. it will probably not be useful in this case, but can you try https://github.com/neovim/neovim/wiki/Troubleshooting#python-support-isnt-working?

**Comment by michael-brade** [comment]
Wow... well, maybe it is: I get a very weired situation, interp is "python2", errors is empty, but 

    :python2

gives "E492: Not an editor command: python2", whereas

    :python3

gives "E471: Argument required". What now?

**Comment by michael-brade** [comment]
PS: I see, you can also check for phython3 by using ``provider#pythonx#Detect(3)``. Then it basically doesn't change much, indeed. I can check successfully for both interpreters but cannot use python3.

**Comment by fwalch** [comment]
`:python2` is indeed not a Vim command, it's just `:python` for Python 2.
