### ISSUE TITLE
Screen flickering when moving cursor

### ISSUE THREAD

**Issue by dwadp** [neovim/neovim#30138]
### Problem

I encountered an issue when opening Neovim, where an LSP is embedded in the workspace. When I move the mouse (up, down, left, right), my terminal screen displays a "flicker." Here are the specifications I'm using:

- **Ubuntu:** 22.04 LTS  
- **Terminal:** WezTerm 20240203-110809-5046fc22  
- **Neovim:** v0.10.1
- **Tmux:** 3.2a

Has anyone experienced a similar issue? I've attached a video to better demonstrate the problem I'm facing.

https://github.com/user-attachments/assets/49eb4c9f-21a1-4e76-b991-21c86100afd2

### Steps to reproduce

- I have tried updating the Neovim version from the previous one: v0.9*.
- I have tried various terminals (Ubuntu Terminal, Alacritty, Kitty, WezTerm).

But the problem still persists.

### Expected behavior

My expectation when using Neovim, whether an LSP is embedded or not, is that when I move the cursor, it should simply move without any "flicker" or "weird rendering" occurring on my terminal screen.

### Neovim version (nvim -v)

v0.10.1

### Vim (not Nvim) behaves the same?

no, 8.2.2121

### Operating system/version

Ubuntu 22.04.4 LTS x86_64

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

repo apt

**Comment by glepnir** [comment]
because you are using stc, the right padding is missing and the lightbulb disappears make the column width changes.

**Comment by dwadp** [comment]
So you're suggesting that i should add more padding to the right of my status line? @glepnir

**Comment by glepnir** [comment]
help statuscolumn

**Comment by dwadp** [comment]
The "lightbulb" icon appeared because I was using the library https://github.com/nvimdev/lspsaga.nvim. I've removed the "lightbulb" icon, and it seems that the issue I was experiencing has disappeared. I think I'll stick with this solution for now. Thank you @glepnir.
