### ISSUE TITLE
annoying error keeps popping up: lsp-status.nvim/lua/lsp-status/messaging.lua:30: attempt to index a nil value 

### ISSUE THREAD

**Issue by svalaskevicius** [neovim/neovim#30158]
### Problem

![2024-08-27T13:43:47,287875115+01:00](https://github.com/user-attachments/assets/2ee8ee10-63ef-4a22-99fc-94111df42afd)

### Steps to reproduce

happens occasionally, when editing a scala file, using metals as lsp provider

it starts hammering that error and I need to keep pressing space / enter / esc for it to go away

### Expected behavior

no error

### Neovim version (nvim -v)

v0.10.1

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

linux

### Terminal name/version

kitty

### $TERM environment variable

tmux-256color

### Installation

arch main repo

**Comment by clason** [comment]
Please report this to the offending plugin (`lsp-status`).
