### ISSUE TITLE
`E888: (NFA regexp) cannot repeat \zs` for `\ze*`/`\ze\+`

### ISSUE THREAD

**Issue by e-kwsm** [neovim/neovim#30159]
### Problem

Searching `\ze*` and `\ze\+` gives `E888: (NFA regexp) cannot repeat \zs` but not `cannot repeat \ze`.

The message must come from
https://github.com/neovim/neovim/blob/dad55f5e763f3f2f436a2ae4f4bb1f6c6442bb45/src/nvim/regexp.c#L1655

### Steps to reproduce

```console
$ LANG=C nvim --clean --headless -c '/\ze*' -c message -c q
Error detected while processing command line:
E888: (NFA regexp) cannot repeat \zs
Error detected while processing command line:
```

### Expected behavior

`E888: (NFA regexp) cannot repeat \ze` for `\ze*` and `\ze\+`.

### Neovim version (nvim -v)

v0.11.0-dev-669+gdad55f5e763f

### Vim (not Nvim) behaves the same?

no, vim 9.1.697

### Operating system/version

EndeavourOS

### Terminal name/version

GNOME Terminal 3.52.2 using VTE 0.76.4 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by e-kwsm** [comment]
```diff
--- a/src/nvim/regexp.c
+++ b/src/nvim/regexp.c
@@ -10166,7 +10166,7 @@ static int nfa_regatom(void)
     case 'e':
       EMIT(NFA_ZEND);
       rex.nfa_has_zend = true;
-      if (!re_mult_next("\\zs")) {
+      if (!re_mult_next("\\ze")) {
         return false;
       }
       break;
```

**Comment by zeertzjq** [comment]
Can you create a PR?
