### ISSUE TITLE
Cursor jump to last line when terminal updates in visual mode

### ISSUE THREAD

**Issue by Shooooooooo** [neovim/neovim#30150]
### Problem

I am not sure if this has been reported before.
When in terminal buffer and visual mode and terminal update its content, the cursor jumps to the last line of the terminal making it impossible to yank something from the terminal.
e.g. running `while true; do echo -ne "\r$(date +"%H:%M:%S")"; sleep 1; done` in a terminal buffer.

### Expected behavior

Cursor should fix in place and not jump to last line.
At least that is the behavior with [emacs-libvterm](https://github.com/akermu/emacs-libvterm)

**Comment by justinmk** [comment]
I can't reproduce this issue. 

- If the :term buffer content exceeds the window height, simply use `ctrl-y` to move the last line one below the window viewport, then the :term buffer will not autoscroll.
- If the entire :term buffer contents fit in the window viewport, visual selection works just fine and isn't interrupted.

Steps that I tried:

```
echo 'i while true; do echo -ne "\r$(date +"%H:%M:%S")"; sleep 1; done' | nvim --clean --cmd "set rows=4" --cmd "te" -s -

go to visual mode, select some text.
cursor does NOT jump to last line; visual mode is maintained correctly.
```

**Comment by Shooooooooo** [comment]
@justinmk You are right, it seems the issue is specific to [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim).
My apologies for not testing using a clean environment.
