### ISSUE TITLE
checkhealth suggestion on tmux termguicolors does not work

### ISSUE THREAD

**Issue by SafetyMary** [neovim/neovim#30162]
### Problem

Following the guide in checkhealth does not fix tmux termguicolors issue
```
tmux ~
- OK escape-time: 10
- OK focus-events: on
- $TERM: tmux-256color
- WARNING True color support could not be detected. |'termguicolors'| won't work properly.
  - ADVICE:
    - Add the following to your tmux configuration file, replacing XXX by the value of $TERM outside of tmux:
      set-option -a terminal-features 'XXX:RGB'
    - For older tmux versions use this instead:
      set-option -a terminal-overrides 'XXX:Tc'
```
Both set-option -a terminal-features 'tmux-256color:RGB' and set-option -a terminal-overrides 'tmux-256color:Tc' does not work

I follow a reddit thread and fixed my color issue.
https://www.reddit.com/r/tmux/comments/mesrci/tmux_2_doesnt_seem_to_use_256_colors/
```
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"
```

Please consider updating checkhealth message

My system:
NVIM v0.10.1
Ubuntu 24.04 LTS
tmux 3.4
colorscheme tokyonight-night

### Steps to reproduce

Fresh kickstart nvim config with tmux 3.4

### Expected behavior

Suggestion in checkhealth should fix the color issue

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713484068

### Vim (not Nvim) behaves the same?

no, vim 9.1.16

### Operating system/version

Ubuntu 24.04 LTS

### Terminal name/version

GNOME Terminal 3.52.0 using VTE 0.76.0 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
Please read the suggestion more carefully
> replacing XXX by the value of $TERM outside of tmux

**Comment by SafetyMary** [comment]
Yes i did replace XXX by the value of $TERM already, sorry i didnt make it clear

**Comment by zeertzjq** [comment]
The $TERM value outside tmux cannot be `tmux-256color`. In GNONE terminal the $TERM value outside tmux is `xterm-256color`.

**Comment by craigmac** [comment]
Ran into this same issue on Debian 13 stable, using default packages: `sudo apt install tmux neovim` which gives you tmux 3.5a and neovim 0.10.4.

The advice in neovim's `:checkhealth` while running under tmux started as `tmux -f /dev/null`:

```
tmux ~
- OK escape-time: 10
- WARNING `focus-events` is not enabled. |'autoread'| may not work.
  - ADVICE:
    - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
      set-option -g focus-events on
- $TERM: tmux-256color
- WARNING True color support could not be detected. |'termguicolors'| won't work properly.
  - ADVICE:
    - Add the following to your tmux configuration file, replacing XXX by the value of $TERM outside of tmux:
      set-option -a terminal-features 'XXX:RGB'
    - For older tmux versions use this instead:
      set-option -a terminal-overrides 'XXX:Tc'
```

Take the advice and create a `tmux-temp.conf` to use with following contents:

```
set-option -g focus-events on
# get the value by running `echo $TERM` outside of a tmux session, most likely something like:
set-option -a terminal-features 'xterm-256color:RGB'
```

start tmux using this config with `tmux -f tmux-temp.conf`, then start start nvim like this: `nvim --clean` to avoid any plugin/config loading.

You will see that nvim still hasn't set `termguicolors`, checking `:checkhealth` output:

```
tmux ~
- OK escape-time: 10
- OK focus-events: on
- $TERM: tmux-256color
```

Seems to indicate it *does* detect 24bit color support and sets `termguicolors`, but in reality it still hasn't. Checking `:set termguicolors?` reports `notermguicolors`.

Trying to switch to the `set-option -a terminal-overrides 'xterm-256color:Tc'` alternative method (for 'older' tmux, this is 3.5a so shouldn't be an issue though) gives the same result and same output from `:checkhealth`.

I think this is a bug with `termguicolors` detection specially related to tmux that hasn't been backported to 0.10.x. I will redo tests with newest nvim 0.11.4 to see if persists.

**Comment by craigmac** [comment]
Ok, had the chance to grab the 0.11.4 binary from the tar.gz release and run it with `./nvim --clean` under tmux using the temp config above (checked both ways, RGB and Tc versions). `termguicolors` is still not set. `checkhealth` on 0.11.4 still shows:

```
tmux ~
- ✅ OK escape-time: 10
- ✅ OK focus-events: on
- $TERM: tmux-256color
```

@justinmk can this be converted to an issue or should I create a new one and link to here?

**Comment by craigmac** [comment]
A long back and forth session with AI suggested adding 'Tc' manually to terminfo and recompiling it - this worked. It's reasoning:

```
[...]

Thank you for testing and confirming. This means:

tmux is advertising Tc via terminal-overrides, but your system’s terminfo for tmux-256color does not actually contain the Tc capability.

Neovim (and most terminfo consumers) only see the base terminfo entry, not the override, when checking for Tc—this is a known limitation on some platforms (especially WSL and some ncurses builds).
This is why termguicolors is not set automatically, even though your config is correct.

Solution: Patch the terminfo entry
You need to add Tc directly to your local tmux-256color terminfo entry. Here’s how:

Dump the current terminfo:

`infocmp tmux-256color > tmux-256color.src`

Edit tmux-256color.src and add `,Tc` to the end of the first long line (the capabilities list). For example:


tmux-256color|tmux with 256 colors,
    ...existing capabilities...,Tc,

Compile the new terminfo:


`tic -x tmux-256color.src`. The terminfo should install to ~/.terminfo/t/tmux-256color and be picked up first over the system installed tmux-256color terminfo.

Restart tmux and try `nvim --clean` again.

Why this works:
This makes the Tc capability available in the actual terminfo database, so Neovim and other programs can detect truecolor support without relying on tmux’s runtime override (which is not always honored by all terminfo consumers).
```

So should the instructions in `:checkhealth` be rewritten if Nvim isn't picking up/parsing tmux's 'terminal-overrides' or 'terminal-features' values?

**Comment by justinmk** [comment]
> [@justinmk](https://github.com/justinmk) can this be converted to an issue or should I create a new one and link to here?

new issue + link to this one



> So should the instructions in `:checkhealth` be rewritten

if the instructions can be improved then great.

i'm kind of getting sick of tmux's shit. why is this so complicated.
