### ISSUE TITLE
`:startinsert` does not consider the current context correctly

### ISSUE THREAD

**Issue by LunarLambda** [neovim/neovim#30172]
### Problem

If `:startinsert` is executed from a autocommand or `nvim_buf_call`/`nvim_win_call`, it will not start insert mode in that buffer/window, but in whatever is the 'user current' buffer/window.

A common way to reproduce this is by having a `TermOpen` autocommand that executes `startinsert`, such as shown in [the documentation for `:terminal`](https://neovim.io/doc/user/various.html#%3Aterminal), and opening a terminal buffer without switching to it, such as when opening multiple windows using `-o` / `-O`.

### Steps to reproduce

minimal.lua:
```lua
vim.cmd('au TermOpen * startinsert')
```

Run `nvim -u minimal.lua -O foo term://sh`

Observe that insert mode is started in the `foo` buffer, not the terminal buffer.

Wrapping the call to `startinsert` in a call to `nvim_buf_call` or `nvim_win_call` furthermore does not work

```lua
vim.api.nvim_create_autocmd('TermOpen', {
    callback = function(event)
        vim.api.nvim_buf_call(event.buf, vim.cmd.startinsert)
    end
})
```

Additional oddity:

`nvim -u NONE -O foo term://sh +'2bufdo set buftype?'` does print `buftype=terminal`, as one would expect, but also causes the leftmost window to also show the terminal buffer instead of the `foo` buffer. This behaviour appears to be shared by `vim` however and occurs even with regular buffers. The same does not occur with `:windo`.

### Expected behavior

Insert mode should be started in the buffer that the autocommand is being executed for, or the window/buffer that is the current API context.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-670+g3bcd5624b

### Vim (not Nvim) behaves the same?

vim -u minimal.vim -O foo bar +'2bufdo terminal ++curwin' does not reproduce it due to immediately becomming the active window.

### Operating system/version

Arch Linux

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

`neovim-nightly-bin` AUR package (downloads latest GitHub release)

**Comment by zeertzjq** [comment]
There is no such thing as a "local Insert mode"

**Comment by LunarLambda** [comment]
Workaround:

```vim
au TermOpen * if v:vim_did_enter == 1 | startinsert | endif
```
or equivalent Lua.

I'm not sure if this kind of edge case can occur in places other than vim startup.
