### ISSUE TITLE
docs & feedback

### ISSUE THREAD

**Issue by MarcWeber** [neovim/neovim#3017]
1)  msgpack_rpc.txt
    A better way is to use the python REPL with the `neovim` package, where API
    functions can be called interactively:

Isn't correct. Ruby ships with irb or with require 'debug' - then you can use a repl as well. Its fine to have a preference for Python .. but that's a way too biased for my taste :)

2) comment job_control

What about \0 chars? Eg xdebug protocol is using them.
My vim-addon-xdebug plugin had to care about it.

I made vim-addon-async return list of strings, eg ['a','b'] means 'a\0b'

You may at least document whether its possible to use them.
Example why I think there could be issues: echo len(nr2char(0).nr2char(1))
expected: 2, got: 1 ? Well, I didn't expect 1 either ..

You may also want to talk about what happens if user is in modal windows - eg q: etc.
Running some VimL functions caused problems to me. I tried working around it by caching the commands till normal mode was entered again.

**Comment by bfredl** [comment]
I think the point was compare running a script vs running in a REPL, rather than python vs ruby (without needing to give examples of all four combinations...) Also python has a better REPL in form of IPython. Perhaps a better formulation is "A better way is to use a REPL, such as irb or the python REPL, ..."  ?

**Comment by tarruda** [comment]
> I think the point was compare running a script vs running in a REPL, rather than python vs ruby (without needing to give examples of all four combinations...) Also python has a better REPL in form of IPython. Perhaps a better formulation is "A better way is to use a REPL, such as irb or the python REPL, ..." ?

True, but another reason for python being preferable is that it already has a wrapper API which improves interactive usage though tab completion for example.

> What about \0 chars? Eg xdebug protocol is using them.

It  returns data in the same format as `readfile()`: Lists of lines with linefeed characters representing zeros, which is also how vim/nvim stores buffer data

**Comment by MarcWeber** [comment]
irb has extensions, also tab completion. vim-addon-async implements such irb buffer with viml completion. Just google "tab completion irb" - just because you've not heard about it doesn't mean such doesn't exist :) My point of view is that your wording causes a very biased impression, while it shoud be only slightly biased eventually.

**Comment by justinmk** [comment]
What is the concrete suggestion here? I.e., specific wording change.

**Comment by justinmk** [comment]
No reply.

**Comment by MarcWeber** [comment]
Suggestion: Drop the REPL hints, everybody knows about it. Its not the task of the neovim docs to educate about how to use python/ruby/... 

http://dpaste.com/2N9WPNB

Everybody knowing python/ruby coding in general usually knows about repl, because today almost all languages provide such (scala, haskell, php, perl, ruby, bash, tcl, js, ..)

I'm unsure whether the last VimL example does exact the same thing, because the echo is not part of the  rpc call.
