### ISSUE TITLE
Cannot install stable version on neovim on Raspberry Pi 5 - Debina released - Bookworm

### ISSUE THREAD

**Issue by moonlinux** [neovim/neovim#30188]
### Problem

I could not install the latest version of Neovim on Raspberry Pi 5 - Debina released (bookworm)
Neovim version on RPI 5 is too old to support Rust plugins and features.

```
alarm@raspberrypi:~$ nvim -v
NVIM v0.7.2
Build type: Release
Lua 5.1
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info



```

### Steps to reproduce

Neovim fresh install fails on **RPI5 Debina bookworm** 

### Expected behavior

When I try to add `ppa for stable  release it fails with no package available for Debian **Bookworm**
``
sudo add-apt-repository ppa:neovim-ppa/stable
PPA publishes dbgsym, you may need to include 'main/debug' component
Repository: 'deb https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu/ book                                                                     worm main'
Description:
Neovim releases backported from Debian.

Homepage: https://neovim.io
Source/Issues: https://github.com/neovim/neovim
Documentation: https://neovim.io/doc
User Manual: https://neovim.io/doc/user
Neovim features: https://neovim.io/doc/user/nvim.html
Packaging: https://launchpad.net/neovim-ppa
More info: https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/neovim-ppa-ubuntu-stable-bookworm.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/neovim-ppa-ubuntu-stable-bookworm.list
Adding key to /etc/apt/trusted.gpg.d/neovim-ppa-ubuntu-stable.gpg with fingerprint 9DBB0BE9366964F134855E2255F96FCF8231B6DD
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 http://archive.raspberrypi.com/debian bookworm InRelease
Ign:5 https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu bookworm InRelease                                                                  
Err:6 https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu bookworm Release 404  Not Found [IP: 185.125.190.80 443]
 
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu bookworm Release' does not have a Release file.                                                                     
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Neovim version (nvim -v)

nvim v0.7.2

### Vim (not Nvim) behaves the same?

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 04 2023 10:24:44

### Operating system/version

 Raspberry Pi 5 - Debina released bookworm

### Terminal name/version

XTerm(379)

### $TERM environment variable

ncurses-term is already the newest version (6.4-4)

### Installation

bookworm

**Comment by clason** [comment]
Debian issue, not Neovim.
