### ISSUE TITLE
`ColorSchemePre` not invoked when setting colorscheme in `UIEnter` autocommand callback

### ISSUE THREAD

**Issue by mrcjkb** [neovim/neovim#30199]
### Problem

The following `minimal.lua` throws an error.

```lua
local test = false
vim.api.nvim_create_autocmd("ColorSchemePre", {
	callback = function()
		test = true
	end,
})
vim.api.nvim_create_autocmd("UIEnter", {
	callback = function()
		pcall(vim.cmd.colorscheme, "somecolorscheme")
		if not test then
			error("ColorSchemePre was not invoked")
		end
	end,
})
```

### Steps to reproduce

`nvim -u NONE -u minimal.lua`

### Expected behavior

No error. I would expect the `ColorSchemePre` callback to be invoked.

### Neovim version (nvim -v)

v0.10.1

### Vim (not Nvim) behaves the same?

No (`UIEnter` doesn't exist in Vim)

### Operating system/version

NixOS 24.05 + NixOS unstable

### Terminal name/version

alacritty 0.13.2 (tmux 3.4)

### $TERM environment variable

xterm-256color

### Installation

nixpkgs

**Comment by zeertzjq** [comment]
The UIEnter autocommand needs `nested = true`
