### ISSUE TITLE
Python Highlighting: "or" and "and" are not highlighted

### ISSUE THREAD

**Issue by venthur** [neovim/neovim#30190]
### Problem

the keywords `or` and `and` are not highlighted since 0.10. Here's a screenshot illustrating the issue. I'm using the default theme:
![image](https://github.com/user-attachments/assets/9411dff3-a33a-41ca-aec8-9efe2a88cbc0)

### Steps to reproduce

see above

### Expected behavior

`or` and `and` should be highlighted as keywords (or whatever the equivalent is in nvim lingo).

### Neovim version (nvim -v)

0.10+

### Vim (not Nvim) behaves the same?

no

### Operating system/version

debian

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

from repo

**Comment by clason** [comment]
They are highlighted as `Operator`, but the -- intentionally minimal -- default colorscheme does not give them a _different_ highlight. Either use a different, less minimal, colorscheme, or set your own `:hi Operator` highlight.

**Comment by venthur** [comment]
That's a bummer, but Ok if that's in purpose, I guess.

**Comment by clason** [comment]
Again, easy to fix on your end if you want it different.
