### ISSUE TITLE
`follow` field doesn't work in `vim.api.nvim_put` function

### ISSUE THREAD

**Issue by Jaehaks** [neovim/neovim#30194]
### Problem

help file said that
>{lines}   |readfile()|-style list of lines. |channel-lines|
   {type}    Edit behavior: any |getregtype()| result, or:
                  • "b" |blockwise-visual| mode (may include width, e.g. "b3")
                  • "c" |charwise| mode
                  • "l" |linewise| mode
                  • "" guess by contents, see |setreg()|
  {after}   If true insert after cursor (like |p|), or before (like  |P|).
   {follow}  If true place cursor at end of inserted text.

But whatever I put true or false in `follow` field, cursor always located at the end of inserted text. when I set `type` to 'c'

### Steps to reproduce

try `:lua vim.api.nvim_put({'test sequence'}, 'c', true, true)`
try `:lua vim.api.nvim_put({'test sequence'}, 'c', true, false)`

### Expected behavior

cursor located at the start of the inserted text when `follow` field is `false`

### Neovim version (nvim -v)

v0.10.0

### Vim (not Nvim) behaves the same?

vim has only `:put` it works with different ways

### Operating system/version

windows 10 

### Terminal name/version

windows-terminal

### $TERM environment variable

xterm-256color

### Installation

scoop

**Comment by zeertzjq** [comment]
There is no guarantee where cursor moves when `follow` is `false`.
