### ISSUE TITLE
mail.vim syntax file is not compatible with colorscheme vim

### ISSUE THREAD

**Issue by alikve** [neovim/neovim#30201]
### Problem

With `colorscheme vim` and `set ft=mail` all lines starting with any number of `>` have the same color.

Reverting `syntax/mail.vim` to the old one (before commit 6916533) fix the problem.

### Steps to reproduce

```
nvim
:set filetype=mail
i
>>>>>
```

### Expected behavior

Colors of lines starting with different numbers `>` must be alternated.

### Neovim version (nvim -v)

v0.10.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Slackware Linux 15

### Terminal name/version

xterm-370-x86_64

### $TERM environment variable

xterm

### Installation

SlackBuild

**Comment by zeertzjq** [comment]
cc @gi1242

**Comment by gi1242** [comment]
1. Fix 1: Tell users to use a colorscheme that uses different highlight groups for `Function` and `Identifier`

2. Fix 2: Tell users to use

        hi link mailQuoted2 PreProc

3. Fix 3: Change mailQuoted2 default highlighting group to something which is highlighted differently by default  (e.g. Added)

If Fix 3 is what you prefer, let me know and I can change it accordingly

**Comment by alikve** [comment]
It may be possible to get the same colors as before? Even `mailQuoted` now are the same they were before, `Identifier`. Odd `mailQuoted` have changed, before they were `Comment`. Is it possible to change `mailQuoted1` to `Comment`?

**Comment by gi1242** [comment]
Preferably not! Recent colorschemes tend to highlighted comment dimmer than other things, so the contrast between the quoted levels will be a bit jarring (to me).

I'd rather leave things as they are and tell users to either `hi link` from their config file, or use a color scheme that differentiates between function and identifier. But if the devs want a different group by default, I'd probably suggest `Added`.

**Comment by alikve** [comment]
It seems there is no `Added` in colorscheme vim. Is it possible to set `mailQuoted1` to `Directory`?

**Comment by gi1242** [comment]
`Directory` is highlighted the same as `Function` in the default color scheme.

After looking again: different quote levels are highlighted differently in the default color scheme. So I would leave things as is and tell affected users to either `hi link` the group or complain to their color scheme maintainer.

**Comment by justinmk** [comment]
why isn't this an issue in regular vim?

**Comment by alikve** [comment]
> `Directory` is highlighted the same as `Function` in the default color scheme.

So, setting `mailQuoted1` to `Directory` will not break the default color scheme and simultaneously fix the vim color scheme. Thus, why not?

> After looking again: different quote levels are highlighted differently in the default color scheme. So I would leave things as is and tell affected users to either hi link the group or complain to their color scheme maintainer.

The default color scheme is very new. It's not completely usable yet. I was shocked when I saw the LaTeX file in the default color scheme, nothing like what I've been used to throughout my life.  On the other hand, the release notes to version 10.0 reads: "Use :colorscheme vim to revert to the old legacy color scheme." With mail filetype this doesn't work.

> why isn't this an issue in regular vim?

Commit [6916533](https://github.com/neovim/neovim/commit/6916533a52c620812dc807778ec1280e82a80525) set `mailQuoted1` to `Function` instead of `Comment` as it is in vim.

**Comment by justinmk** [comment]
> Commit [6916533](https://github.com/neovim/neovim/commit/6916533a52c620812dc807778ec1280e82a80525) set `mailQuoted1` to `Function` instead of `Comment` as it is in vim.

That commit is from Vim. If the latest Vim build is different, then that implies Vim changed it later, and we'll eventually get that change as we update runtime files.

**Comment by clason** [comment]
> v0.10.1

Please always test the latest nightly, especially for issues with runtime files. We are fully synced with Vim, so any issue here that cannot be traced to the different default(!) colorscheme is in fact an upstream issue.
