### ISSUE TITLE
Failed to build with new makefile

### ISSUE THREAD

**Issue by Tech0ne** [neovim/neovim#30218]
### Problem

Might be a nooby question, but I'me not able to build ever since the new Makefile update.

The following error is raised when running `make CMAKE_BUILD_TYPE=RelWithDebInfo` :

```sh
mkdir -p ".deps"
cmake -S /tmp/neovim//cmake.deps -B ".deps" -G Unix Makefiles   
CMake Error: Could not create named generator Unix

Generators
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
* Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.

make: *** [Makefile:105: build/.ran-deps-cmake] Error 1
```

### Steps to reproduce

Easyest way to reproduce the exact bug I got is to use docker.

- Spawn a Ubuntu 22.04 docker: `sudo docker run -it --rm ubuntu:22.04`
- Update packets and install requirements: `apt-get update && apt-get install -y git cmake make gcc` (Note: there might be other dependencies, like gettext, but this is not relevent to that bug)
- Clone the repo: `git clone https://github.com/neovim/neovim`
- Start building: `cd neovim/ && make CMAKE_BUILD_TYPE=RelWithDebInfo`

### Expected behavior

Build the tool ?

### Neovim version (nvim -v)

vim-patch:9.1.0708 commit 97f8d1de1cfaebd67bc994401da38b003b64b6df

### Vim (not Nvim) behaves the same?

no (not relevant)

### Operating system/version

Ubuntu 22.04

### Terminal name/version

bash ? gnome-terminal (not relevant)

### $TERM environment variable

xterm (not relevant)

### Installation

Manual git installation

**Comment by clason** [comment]
Easy workaround: install `ninja` (which is _really_ recommended on Linux and macOS).

(Doesn't mean the quoting bug shouldn't be fixed.)

**Comment by dundargoc** [comment]
Todo note to self: check if the quotes can be embedded in the variable itself so we don't need to quote it everywhere
