### ISSUE TITLE
vim.fs.dirname() returns "." on MSYS2

### ISSUE THREAD

**Issue by Freed-Wu** [neovim/neovim#30212]
### Problem

```
=vim.fs.dirname(vim.fn.stdpath('config'))
.
```

### Steps to reproduce

/

### Expected behavior

```
C:\User\XXX\AppData\Local
```

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 10

### Terminal name/version

windows terminal

### $TERM environment variable

xterm-256color

### Installation

Msys2

**Comment by justinmk** [comment]
What does it return if you replace the `\` slashes with `/` slashes?

    =vim.fs.dirname(vim.fn.stdpath('config'):gsub([[\]], '/'))

Can you try the development version? The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 

Looks like `vim.fs.dirname()` always returns '.' if the input is nonsense:

    =vim.fs.dirname('x')
    .

That seems... undocumented, probably should return `nil` ?

**Comment by Freed-Wu** [comment]
So `C:\a\b` is an invalid input, we must pass `C:/a/b` to `vim.fs.dirname()`?

**Comment by zeertzjq** [comment]
No

**Comment by zeertzjq** [comment]
I don't think there is such thing as "invalid input". Any input is valid.

**Comment by zeertzjq** [comment]
Does it work if you use the Released executable instead of MSYS2?

**Comment by zeertzjq** [comment]
The released executable works as expected, so the problem here is that Windows detection fails in the MSYS2 build. What is the output of `:=vim.uv.os_uname()`.

**Comment by zeertzjq** [comment]
Hmm, it seems that Windows detection is done in many different ways in the codebase:
- In `lsp/protocol.lua`, `fs.lua` and `provider/health.lua` it's `sysname == 'Windows_NT'`
- In `loader.lua` it's `sysname:find('win', 1, true) and not sysname:find('darwin', 1, true)`
- In `test/lua_runner.lua` it's `sysname:lower():find('windows')`
- In `test/testutil.lua` it's `sysname():find('windows') or sysname:find('mingw')`

The last one is the only one that handles MinGW.

**Comment by justinmk** [comment]
What does `vim.fn.has('win32')` return on msys2? `f_has()` is [now marked as `fast`](https://github.com/neovim/neovim/commit/1294e221a205f1f3c6d2e31421b674db6e747406) so most Lua code should prefer it where possible?

**Comment by Freed-Wu** [comment]
return 1.
