### ISSUE TITLE
"hi vertsplit guifg=#ff0000" doesn't work correctly in Windows.

### ISSUE THREAD

**Issue by xvim64** [neovim/neovim#30216]
### Problem

https://github.com/user-attachments/assets/c8b93377-42a5-4fa9-92aa-0ae67c78b2a2

"hi vertsplit guifg=#ff0000" does not work in Windows.
"hi vertsplit guifg" follows "hi normal guifg",

### Steps to reproduce

in Windows Terminal (cmd.exe) on Windows 11 23H2

nvim --clean
:vs
:hi vertsplit guifg=#ff0000
:hi normal guifg=#ffff00
:hi vertsplit guifg=#ff0000  // "hi vertsplit guifg=#ff0000" is yellow, not red.

### Expected behavior

Correct color change of "hi vertsplit"

### Neovim version (nvim -v)

NVIM v0.11.0-dev-693+g9762c5e34

### Vim (not Nvim) behaves the same?

no, vim uses ctermfg in Windows Terminal, not guifg.

### Operating system/version

Windows 11 23H2

### Terminal name/version

Windows Terminal (cmd.exe)

### $TERM environment variable

Windows Terminal (cmd.exe)

### Installation

nightly nvim-win64.zip

**Comment by zeertzjq** [comment]
`:h hl-VertSplit`
