### ISSUE TITLE
alternate-file on german keyboard

### ISSUE THREAD

**Issue by bluebrown** [neovim/neovim#30229]
### Problem

Hi, since some time, I am facing the same issue as describe dhere. https://vi.stackexchange.com/questions/39059/ctrl-work-in-vim-but-not-in-neovim. 

It suddenly stopped working, first on one of my laptops and then on another, without changing the version of neovim installed.

This is running in wsl, so may have something to do with the way nvim determines what keyboard is used by looking at something in the wsl system.

As described in the SO question, instead of `CTRL-^` the binding `CTRL-6` works. In these docs, its mentioned that this would be the case on American keyboard https://vimdoc.sourceforge.net/htmldoc/editing.html#CTRL-^.

However, I do not have an American keyboard layout and none of my other keys is switched around or wrong. Its only that alt file feature that takes 6 instead of ^ on my German keyboard.

### Steps to reproduce

Not entirely sure how to reproduce reliably.

### Expected behavior

`CTRL-^` should toggle the alternate-file

### Neovim version (nvim -v)

NVIM v0.11.0-dev-700+gbcae8be91

### Vim (not Nvim) behaves the same?

yes, vim 9.0

### Operating system/version

windows 10, 5.15.153.1-microsoft-standard-WSL2 GNU/Linux, Bookworm

### Terminal name/version

Windows Terminal Version: 1.20.11781.0

### $TERM environment variable

xterm-256color

### Installation

repo

**Comment by dundargoc** [comment]
This is the same problem as described [here](https://github.com/neovim/neovim/issues/28476#issuecomment-2075124745). Unsure if we should have a tracking issue for this problem in general.

**Comment by justinmk** [comment]
> `CTRL-^` should toggle the alternate-file

Does this work:

    call nvim_input('<c-^>')

if so, this is between you and your terminal

> Vim (not Nvim) behaves the same?
> yes, vim 9.0

👀

**Comment by bluebrown** [comment]
@justinmk, 

```vim
:call nvim_input('<c-^>')  
```

I tested with 2 terminals now. 

1. windows terminal (ships by default on windows 11)

alternate-file works with `<C-6>` and `call nvim_input('<c-^>')`

2 default wsl terminal on windows 10

alternate-file does not work with any keybinding. `call nvim_input('<c-^>')` still works.

---

This seems to be a issue with the terminal itself. I also suspected this at some point but I couldnt find any offending keybindings (windows terminal). I deleted them all at one point but it didnt help.

**Comment by justinmk** [comment]
> `call nvim_input('<c-^>')` still works.

This is a strong indication that the key sequence simply isn't reaching Nvim. It should be possible these days to configure Windows Terminal to send any arbitrary sequence from a mapping that you configure (in Windows Terminal). 

Also check `:help tui-modifyOtherKeys`
