### ISSUE TITLE
Add CI/releases for ARM64 Linux

### ISSUE THREAD

**Issue by LunarLambda** [neovim/neovim#30223]
### Problem

As title says. It would be very nice if we could have nightly builds for ARM64 Linux. The CI seems to use Ubuntu 20.04, which supports ARM64. Neovim seems to already support ARM64 without major issues since there are MacOS ARM64 builds.

### Expected behavior

It would allow easily following HEAD on ARM Linux devices, including phones, laptops, and servers (including small SBCs/embedded devices), some of which are increasingly moving towards ARM if they weren't already primarily using it.

**Comment by clason** [comment]
Duplicate. Until Github has publicly available(!) Linux ARM runners, this is not feasible.

**Comment by LunarLambda** [comment]
Ah, that's quite unfortunate.

**Comment by clason** [comment]
(The flip side is that if and when the runners come out, we'll make use of them like we did for macOS. No need to push for it; we're following this on our own.)

**Comment by LunarLambda** [comment]
Good to hear, thank you!

**Comment by benz0li** [comment]
In the meantime: https://gitlab.b-data.ch/neovim/neovim/-/releases

❗ *Unofficial* and *untested* builds. No intention to build AppImages.

**Comment by LunarLambda** [comment]
https://github.blog/changelog/2024-09-03-github-actions-arm64-linux-and-windows-runners-are-now-generally-available/

As of September GitHub now has ARM64 Linux runners. Could this be reopened?

**Comment by clason** [comment]
> Arm64 runners are available to customers on our Team and Enterprise Cloud plans.

which means they are not available _to us_ (yet), so no.

**Comment by adamency** [comment]
@clason Could this be reopened to be closed as completed with the mention of #32059 ?

**Comment by zeertzjq** [comment]
No, it's #32194
