### ISSUE TITLE
zip.vim can not extract file - shell not defined

### ISSUE THREAD

**Issue by philippseith** [neovim/neovim#30234]
### Problem

Extracting a file with "x" in zip.vim does not work.

The issue was also in vim 9.0 (see https://github.com/vim/vim/issues/15585)

### Steps to reproduce

run nvim some.zip
select a file in the zip
hit x to extract the file
Error occurs:
Error detected while processing function zip#Extract:
line 24:
E121: Undefined variable: shell
E116: Invalid arguments for function shellescape
E116: Invalid arguments for function system

### Expected behavior

The file gets extracted. 

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: RelWithDebInfo LuaJIT 2.1.1713484068

### Vim (not Nvim) behaves the same?

vim 9.2 does not, but vim 9.0 does

### Operating system/version

Ubuntu 22.4, macOS 14.6

### Terminal name/version

windows terminal, iterm

### $TERM environment variable

xterm-256color

### Installation

snap (Linux), brew (macos)

**Comment by clason** [comment]
> NVIM v0.10.0 Build type: RelWithDebInfo LuaJIT 2.1.1713484068

Please test the latest nightly; we are fully synced with Vim's runtime, so if it works there, it should work here. (If it was fixed after 0.10 was released, of course you won't see the fix.)

**Comment by zeertzjq** [comment]
Fixed by #29836
