### ISSUE TITLE
set background is dark removes syntax highlighting

### ISSUE THREAD

**Issue by ranzbak** [neovim/neovim#3024]
When i execute 
#syntax on
#set background=dark

The syntax highlighting disappears

it magically appears again when 
#set background=light 

is executed.

Found on OSX 10.10.4 using brew tap neovim/neovim

**Comment by justinmk** [comment]
This is how Vim works.

**Comment by whitebyte** [comment]
Is this expected behavior?

**Comment by justinmk** [comment]
see `:help 'background'`

**Comment by eraserhd** [comment]
I have this issue as well, and nothing in the help for 'background' seems specific to neovim.  Vim changes the colors when I "set background=dark" to lighter colors.

Vim, background=light:
<img width="249" alt="screen shot 2016-06-22 at 11 39 35 pm" src="https://cloud.githubusercontent.com/assets/147284/16291239/bfe744d0-38d2-11e6-9a0a-731c74eb0eb7.png">

Vim, background=dark:
<img width="228" alt="screen shot 2016-06-22 at 11 41 05 pm" src="https://cloud.githubusercontent.com/assets/147284/16291248/d75bd036-38d2-11e6-9c0e-a6730f25b1e8.png">

Neovim, background=light:
<img width="234" alt="screen shot 2016-06-22 at 11 41 48 pm" src="https://cloud.githubusercontent.com/assets/147284/16291268/ebf9ea28-38d2-11e6-8c57-efa56648f127.png">

Neovim, background=dark:
<img width="233" alt="screen shot 2016-06-22 at 11 42 27 pm" src="https://cloud.githubusercontent.com/assets/147284/16291276/09ff134a-38d3-11e6-94ae-b91df9c8ae8a.png">

**Comment by justinmk** [comment]
@eraserhd That doesn't seem right, could depend on your `$TERM` or if you have true color enabled (in Vim, or Neovim--need details about both cases)

**Comment by eraserhd** [comment]
@justinmk TERM=screen (running tmux in Terminal.app).

Running tmux with "-2" to force 256 color mode: same.
Running tmux with "-2" and manually setting TERM to screen-256: fixes the problem.

**Comment by eraserhd** [comment]
I've added this to my `.tmux.conf`:

```
set -g default-terminal "screen-256color"
```
