### ISSUE TITLE
Changes to .editorconfig should update respective attached buffers

### ISSUE THREAD

**Issue by asmodeus812** [neovim/neovim#30245]
### Problem

Here is the problem, once the editorconfig file properties are loaded into buffers, changes to the editorconfig file will not update these properties in buffers which were already loaded. When an .editorconfig file is changed, all relevant buffers under the directory where the .editorconfig is located should get their properties updated.

### Expected behavior

Update buffer options when .editorconfig change occurs.

```lua
    vim.api.nvim_create_autocmd({ 'BufWritePost', 'BufRead' }, {
        group = modegroup,
        pattern = "*.editorconfig",
        callback = function(args)
            local buffers = vim.api.nvim_list_bufs()
            for _, bufnr in ipairs(buffers) do
                local valid = bufnr and vim.api.nvim_buf_is_valid(bufnr)
                local name = valid and vim.api.nvim_buf_get_name(bufnr)
                local root = valid and vim.fn.fnamemodify(args.match, ":h")
                if root and name and #name > 0 and vim.startswith(name, root) then
                    vim.b[bufnr].editorconfig = false
                    require('editorconfig').config(bufnr)
                end
            end
        end
    })
```
Example is very crude since if you have multi level directory structure with multiple editorconfigs this will do a bit of extra unecessary work, but the editorconfig plugin already has enought context to know which buffer properties are set from which immediate editorconfig. Buffer/File renames/moves are already handled i believe but extra care might need to be taken.

**Comment by justinmk** [comment]
That autocmd would only work if the edit was made in the same Nvim process. Would need a filewatcher to do this more robustly: https://github.com/neovim/neovim/issues/1380

"Reload all buffers" is a delicate UI to get right, and thus I think solving https://github.com/neovim/neovim/issues/1380 is equivalent to solving this.

**Comment by asmodeus812** [comment]
Well yes the way the change to the editorconfig is detected was a **crude** example. But i find it Strange, the issue you have posted does not address the issue above at all, why do we need to "reload" buffers, **instead i would think the .editorconfig has to be re-parsed and the buffer local options re-applied**. How would **autoread** help us with the update/re-application of the **buffer local properties coming from the changes in the .editorconfig** ? In either case something has to change in the editorconfig plugin to accomodate this ?

**Comment by justinmk** [comment]
Reloading a buffer automatically triggers editorconfig processing. Not to mention other stuff. That's why focusing on the narrow case of editorconfig is the wrong framing: this is generally solved by thinking about autoload / filewatch.

**Comment by asmodeus812** [comment]
@justinmk, i am not sure i get that, **we know the actual use case here, and it is that, the only way the buffer local options can change is if a change to the editorconfig is detected**, not other file buffers. If that filewatch / autoreload is implemented, without any changed to the current editorconfig plugin, everytime a file is changed (that is not the editorconfig) it will go and try to re-read the editor config, below is the current implementation. **BufRead will get retriggered**. This seems like so much extra work while the change to the editorconfig file itself will be seldom done, if at all. 

```lua
local group = vim.api.nvim_create_augroup('editorconfig', {})
vim.api.nvim_create_autocmd({ 'BufNewFile', 'BufRead', 'BufFilePost' }, {
  group = group,
  callback = function(args)
    -- Buffer-local enable has higher priority
    local enable = vim.F.if_nil(vim.b.editorconfig, vim.g.editorconfig, true)
    if not enable then
      return
    end

    require('editorconfig').config(args.buf)
  end,
})
```

**Comment by justinmk** [comment]
> If that filewatch / autoreload is implemented, without any changes to the current editorconfig plugin,

We need the filewatch feature in order to watch the editorconfig file for changes.

**Comment by asmodeus812** [comment]
I still think we are not talking about the same thing here, sure, improve the autoread, have a better file change detectection, i do not care how the change is detected to the editorconfig, what i am saying is that the currennt implementation, if it remains unchanged, and a the autoread is improved to detect changes better, the `BufRead` above will get triggered for files that are also not `editorconfigs` (which are the majority of files) and re-parse and re-apply the same properties over and over, doing `_noop_` work, **that is not free**. That is why the implementation has to be changed / inverted and detect changes to the editorconfig and apply them to the affected buffers, not the other way around.

**Comment by clason** [comment]
>  i do not care how the change is detected to the editorconfig

Then you are not part of the technical discussion. We heard what you want; now let us decide _how_ we can do that (within the capabilities and development priorities of the project).
