### ISSUE TITLE
NVIM_APPNAME broken with `nvim: failed to --listen`

### ISSUE THREAD

**Issue by dpetka2001** [neovim/neovim#30256]
### Problem

After this commit https://github.com/neovim/neovim/commit/96128a5076b7e45fc01163151401a9e2acdff565 the behavior of `NVIM_APPNAME` seems to have changed. Since, I'm using Neovim nightly images, I can't be certain 100% of whether this specific commit is responsible or something else. It's just that looking through the commits in between the 2 nightly images, this specific commit made more sense regarding the error that I got. 

`:h $NVIM_APPNAME` mentions the following
> `$NVIM_APPNAME` must be a name, such as "foo", or a relative path, such as "foo/bar".

I'm used to just having a directory `~/.config/test_configs/` in which I create different directories for different distros or other users' Neovim configurations I would like to test. 

After the change in the commit mentioned above, I get an error 
```
nvim: Failed to --listen: "no such file or directory"
                                                     More info with "nvim -h"
```
when trying to do `NVIM_APPNAME=test_configs/test nvim` for example.

On another note this does not seem to happen when you just create a directory `~/.config/test/` and clone there whatever you want and then you run `NVIM_APPNAME=test nvim`. It seems to throwing the error on relative paths from what I tested.

PS: Neovim stable 0.10.1 works as expected. And if I rollback to a version before this commit, then Neovim nightly also works correctly.

### Steps to reproduce

1. Create directory `~/.config/test_configs/test/`.
2. `git clone https://github.com/LazyVim/starter ~/.config/test_configs/test` (just an example distro, I've also tried AstroNvim with same result)
3. NVIM_APPNAME=test_configs/test nvim and observe what happens

### Expected behavior

`$NVIM_APPNAME` should behave as before the change in commit https://github.com/neovim/neovim/commit/96128a5076b7e45fc01163151401a9e2acdff565. 

### Neovim version (nvim -v)

NVIM v0.11.0-dev-705+gae9674704

### Vim (not Nvim) behaves the same?

Not tested

### Operating system/version

Linux Mint 21.3

### Terminal name/version

kitty 0.36.1

### $TERM environment variable

xterm-kitty

### Installation

I used [bob](https://github.com/MordechaiHadad/bob) to install Neovim

**Comment by justinmk** [comment]
Thanks for mentioning this. This was a hidden bug that is now exposed since `--listen` is now validated. Before https://github.com/neovim/neovim/commit/96128a5076b7e45fc01163151401a9e2acdff565 , `NVIM_APPNAME=test_configs/test nvim` would silently fail to create a server and `v:servername` would be empty.
