### ISSUE TITLE
document `default-mouse` behaviour on tablets

### ISSUE THREAD

**Issue by nisbet-hubbard** [neovim/neovim#30267]
### Problem

Default `set mouse=default-mouse` causes scroll gesture on tablets to scroll page instead of cursor. Current [Vim_diff](https://neovim.io/doc/user/vim_diff.html#_default-mouse) only mentions the effect on desktops, which makes it difficult for users like me to identify the source of the problem.

### Steps to reproduce

Scroll on a tablet through Blink shell.

### Expected behavior

Scroll gesture moves cursor up and down.

### Neovim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

no, vim 8.2.0

### Operating system/version

RHEL 9.4

### Terminal name/version

Blink.sh

### $TERM environment variable

screen

### Installation

binary tarball from repo

**Comment by zeertzjq** [comment]
Why should think be documented in Nvim's documentation instead Blink shell's?

**Comment by justinmk** [comment]
Enabling 'mouse' implies mouse-scroll, but that is not specifically called out for desktop or any other device. I guess we can mention "mouse scroll" at `:help default-mouse`.
