### ISSUE TITLE
Please branch nightly for EPEL 9 on COPR

### ISSUE THREAD

**Issue by nisbet-hubbard** [neovim/neovim#30260]
### Problem

The EPEL package (currently 0.8) is often out of step with what’s described in docs. Could you please also build the nightly version for the `epel-9-x86_64` chroot on COPR?

### Steps to reproduce

Not relevant 

### Expected behavior

Not relevant 

### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

x86_64

### Terminal name/version

mosh

### $TERM environment variable

screen

### Installation

DNF

**Comment by 0IHI0** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by clason** [comment]
We do not maintain these builds.
