### ISSUE TITLE
Make BufDelete only fire in response to `bdelete` command (or `bwipeout`)

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#30278]
I requested this feature in https://github.com/vim/vim/issues/12817 but it was rejected due to backwards-compatibility concerns. I'm curious whether Neovim can decide differently.

> Buffer deletion is an ambiguous concept in Vim. Most people think of deletion as "what happens when you bdelete a buffer," which is unloading, unlisting, and clearing some buffer-specific settings. The BufDelete event, by contrast, fires specifically when a buffer is unlisted - the buffer can still be present in a window when this happens. The documentation is clear about the current semantics - it does say that BufDelete means "Before deleting a buffer from the buffer list," and it's distinct from BufUnload. But I think what people probably want to be saying when they register events on BufDelete is "run this when bdelete happens," not "run this when the buffer is unlisted." I think the event should specifically be tied to this command, as well as run on bwipeout prior to BufWipeout. And to support plugins that depend on the existing semantics, maybe create BufUnlisted that they can use instead.

**Comment by clason** [comment]
Tentative: No, as this would open the door to many subtle and annoying bugs in plugins that (rightfully) expect Vim and Neovim to behave the same way.

**Comment by justinmk** [comment]
> to support plugins that depend on the existing semantics, maybe create BufUnlisted that they can use instead

But the inverse is also true already: plugins that want to distinguish `BufDelete` between "unlisted" vs "actually deleted" can check `bufloaded(@%)` and `buflisted(@%)`. 

```vim
au BufDelete * echom bufloaded(@%) buflisted(@%)
setlocal nobuflisted " 1 0
edit foo
bdelete              " 1 1
```

Changing this would be a "lateral move" in terms of capabilities, possibly a minor improvement in terms of interface, and a major cost in terms of ecosystem. Thus low leverage.
