### ISSUE TITLE
Lua Vimscript bridge memory leak

### ISSUE THREAD

**Issue by ronandalton** [neovim/neovim#30283]
### Problem

Memory that is consumed by Lua code and subsequently freed by an automatic garbage collection cycle or manually with `collectgarbage("collect")` often doesn't result in the memory used being released back to the operating system. This causes Neovim to use more memory than necessary, even after memory intensive code has finished running.

The effect of this issue is that when a plugin such as Telescope is used to search a large project multiple times (which is a normal use case), the memory usage will climb to many times what is necessary, and will remain high even after the user has finished searching and the results no longer need to be kept in memory. I have seen memory usage climb up to and exceed 1 GB because of this issue (although typically excess memory usage is around 100-500 MB).

### Steps to reproduce

1. Launch Neovim with `nvim --clean`
2. Run the following commands and monitor memory usage with a system monitor, leaving 5-10 second gaps between each execution:
   `:lua local nums = {} for i = 1, 10000000 do nums[i]=i end vim.g.foo = nums`
   [repeat the previous command two more times]
   `:lua vim.g.foo = nil`
   `:lua collectgarbage("collect")`
   `:lua print(collectgarbage("count"))`
3. Memory usage should have increased to around 1.4 GB, then decreased to around 960 MB, where it remains. The output of the last command should show that only around 323 KB of memory remains in use by Lua, even though the Neovim process is still using 960 MB.

### Expected behavior

Memory usage by the Neovim process should be released or begin decreasing soon after it is no longer in use by Lua.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-714+g220b8aa6f

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux with kernel 6.9.3

### Terminal name/version

Alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

appimage

**Comment by justinmk** [comment]
Since you are assigned `vim.g.foo`, try also calling `garbagecollect()`.

**Comment by ronandalton** [comment]
Calling `vim.fn.garbagecollect()` doesn't seem to have any effect.

**Comment by zeertzjq** [comment]
This is not memory leak. See https://stackoverflow.com/questions/13232119/memory-usage-doesnt-decrease-when-free-used

**Comment by ronandalton** [comment]
I just tested on Windows and it doesn't seem to have this issue. So this seems to be an issue with the default behavior of malloc/free on Linux. Reading around a bit suggests that using malloc_trim or a custom malloc implementation such as tcmalloc could fix this issue. I would be interested in looking more into this issue to see if there's something we can do.

**Comment by justinmk** [comment]
It's not an "issue". It is just a common confusion. Linux will claim the memory when it needs to, no sooner.

**Comment by ronandalton** [comment]
Unfortunately this doesn't seem to be the case, at least for me. Repeating my reproduction method three times with separate Neovim instances running in a VM with 4 GB of memory resulted in the system running out of memory and either killing the third Neovim instance as it was trying to use more memory, or causing the entire system to grind to a halt. This would suggest that your statement does not hold true, at least in this instance.

**Comment by justinmk** [comment]
> Repeating my reproduction method three times with separate Neovim instances running in a VM with 4 GB of memory resulted in the system running out of memory and either killing the third Neovim instance

I assume you ensured that GC was done in the first 2 before trying the 3rd instance? 

If you can shared a shell script to repro the issue, that will avoid lots of back and forth questions.

**Comment by justinmk** [comment]
> This is not memory leak. See https://stackoverflow.com/questions/13232119/memory-usage-doesnt-decrease-when-free-used

If that's the case, then the behavior should be similar if the script is "Lua only" (avoid the vimscript bridge, don't assign `vim.g.foo`).

But there does seem to be a leak on the vimscript side. Try the following script:

```lua
local function test(kind, n)
  local var = 'nums' .. n
  vim.v.testing = 1
  local before = collectgarbage('count')
  collectgarbage('collect')
  vim.fn.test_garbagecollect_now() -- vim.fn.garbagecollect()

  if kind == 'vim-bridge' then
    local nums = {}
    for i = 1, 90000000 do nums[i]=i end
    vim.g[var] = nums
  elseif kind == 'lua-only' then
    _G[var] = {}
    for i = 1, 90000000 do _G[var][i]=i end
  else
    error()
  end

  -- GC
  _G[var] = nil
  vim.g[var] = nil
  -- vim.cmd[[unlet g:nums]]
  collectgarbage('collect')
  vim.fn.test_garbagecollect_now() -- vim.fn.garbagecollect()
  local after = collectgarbage('count')
  vim.cmd.echomsg(([['memory increase/decrease after gc (%s): %f%%']]):format(kind, ((after - before)/before) * 100))
end

test('lua-only', '1')
test('lua-only', '2')
test('lua-only', '3')
test('lua-only', '4')
-- test('vim-bridge', '1')
-- test('vim-bridge', '2')
-- test('vim-bridge', '3')
-- test('vim-bridge', '4')
-- test('vim-bridge', '5')
-- test('vim-bridge', '6')
-- test('vim-bridge', '7')

-- vim: sw=2 et
```

**Comment by zeertzjq** [comment]
But the memory usage only increases on the first use of `vim-bridge` and keep constant in the following uses, so that's indeed the case.

**Comment by ronandalton** [comment]
I can confirm that on Linux, only the `vim-bridge` test causes the memory to not be released after a garbage collection, and subsequent runs do not compound the memory usage. Rerunning my initial reproduction method replacing `vim.g.foo` with `_G.foo` also leads to the memory being freed to the OS after the garbage collection. I also observed that memory usage seems to be around half when using `_G.foo` as opposed to `vim.g.foo` before the call to `collectgarbage`.

I suspect there is still some other issue even when not using the vim-bridge since the Telescope plugin still has this issue with memory not being released, and that doesn't use `vim.g` to store its results. I'll need to have a closer look regarding that to see if there's a simple Lua reproduction I can come up with.
