### ISSUE TITLE
EOL character suddenly showing

### ISSUE THREAD

**Issue by Freaksed** [neovim/neovim#30286]
### Problem

ran update this morning, and now EOL character is showing in my files ^M.
this was not showing yesterday, so i assume it has to do with the update.

### Steps to reproduce

open a file that has this carriage return

### Expected behavior

it should not show this phantom text

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

Windows WSL2 Ubuntu

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

package manager

**Comment by justinmk** [comment]
> ran update this morning

you mean like where you update... all of your plugins at the same time?

**Comment by Freaksed** [comment]
yes, i use LazyVim so i ran the plugin update operation
