### ISSUE TITLE
New default color scheme background is not OLED-friendly

### ISSUE THREAD

**Issue by joshtriplett** [neovim/neovim#30299]
### Problem

Thank you for putting so much effort into a nice default color scheme.

The new scheme uses a background that isn't as friendly for OLED display users. Please consider setting the default to full black, so that oh OLED the background can be *off*, which provides less overall light-in-the-eyes for reading comfort, as well as better battery life for laptops and other mobile devices.

I appreciate that you're balancing many conflicting needs and desires here, and I will understand if this ends up being a matter for configuration. (In which case, I might contribute a PR for a color scheme that inherits the default and sets the background.)

### Steps to reproduce

(use vim on an OLED display)

### Expected behavior

Background pixels turned off.

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1725453128

### Vim (not Nvim) behaves the same?

no, all versions of vim

### Operating system/version

Android 14

### Terminal name/version

termux

### $TERM environment variable

xterm-256color

### Installation

termux

**Comment by clason** [comment]
Yes, as you wrote, there were (too) many concerns; we will probably not revisit the (very deliberate) choices for a long while. If the default colorscheme does not work for you, just use another one or customize it to your liking.

**Comment by joshtriplett** [comment]
Fair enough. Would a PR adding an `nvimoled` color scheme be welcome?

**Comment by clason** [comment]
Probably not, no (thank you). The only colorschemes we bundle are the ones we inherit from Vim as part of the runtime files. We are not looking to add to these (as this is a bottomless barrel, and colorschemes can be installed easily enough).

**Comment by justinmk** [comment]
> Would a PR adding an `nvimoled` color scheme be welcome?

@joshtriplett  I would be interested in seeing this at least for comparison. Another reason for turning off the bg is for the (less common these days) situation where users mouse-select text with 'nomouse'.

**Comment by joshtriplett** [comment]
@justinmk 
> > Would a PR adding an `nvimoled` color scheme be welcome?
> 
> @joshtriplett I would be interested in seeing this at least for comparison. Another reason for turning off the bg is for the (less common these days) situation where users mouse-select text with 'nomouse'. But also, I'm still on the fence about the somewhat low contrast of the current bg.

Sure. Here's a screenshot of the default color scheme:

![Screenshot_20240907-175256](https://github.com/user-attachments/assets/cf3d573f-7f02-490f-8eff-e99ef997d714)

And here's one with the background set to black: 

![Screenshot_20240907-180002](https://github.com/user-attachments/assets/20dab8ba-f5f3-4bd8-8245-1c86e06bcadb)

The difference is even more striking on an OLED screen.

**Comment by clason** [comment]
I don't see _any_ difference on an LCD screen...

**Comment by justinmk** [comment]
@joshtriplett i mean the code diff :)

**Comment by joshtriplett** [comment]
> @joshtriplett i mean the code diff :)

Ah! Will do.

**Comment by joshtriplett** [comment]
Sorry for the greatly delayed response here.

Here's a diff:
```patch
--- /dev/null
+++ b/runtime/colors/defaultoled.vim
@@ -0,0 +1,13 @@
+" Neovim color file
+" Maintainer:        The Neovim Project <https://github.com/neovim/neovim>
+" Last Change:        2024 Sep 13
+
+runtime colors/default.vim
+if vim.o.background == 'light' then
+  hi Normal guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
+else
+  hi Normal guifg=#ffffff guibg=#000000 gui=NONE cterm=NONE
+end
+let colors_name = "defaultoled"
+
+" vim: sw=2
```
