### ISSUE TITLE
LSP: show selected word in quickfix title for LSP commands e.g. "grr"

### ISSUE THREAD

**Issue by ColinKennedy** [neovim/neovim#30305]
### Problem

When I type `gr` to show references I get a generic quickfix list title that just says `References`

![image](https://github.com/user-attachments/assets/6421a1e9-bfb8-4ff1-ac83-6762ae7231bb)

Running :chistory on a number of these calls are indistinguishable from one another because they are all titled References

![image](https://github.com/user-attachments/assets/b954fa76-ae49-4aa9-a617-d239efa6fb30)

### Expected behavior

The `gr` command (and other similar LSP commands) include the word of whatever was selected (see `:chistory` screenshot)

![image](https://github.com/user-attachments/assets/ff0c0e69-2706-4d5c-a38c-321839847461)

**Comment by glepnir** [comment]
emm  the screenshot it's  not neovim defualt lsp handler? run `:lua vim.lsp.buf..reference()` it will show the pattern in qflist.

**Comment by ColinKennedy** [comment]
Ah whoops, I forgot I added an old custom keymap. This is my definition for `gr`.

```lua
vim.keymap.set(
    "n",
    "gr",
    vim.lsp.buf.references,
    {
        buffer=buffer,
        desc="[g]o to [r]eferences - Show all locations where a variable is used."
    }
)
```

So the screenshot from before was already calling the lua function you'd recommended for testing. And `grr` is the same result as the screenshot of course.

My setup is fairly custom so I wouldn't be surprised if I accidentally messed with the default LSP handler but FWIW I don't recall changing anything. How can I check that?

**Comment by ColinKennedy** [comment]
Are you sure the issue is on my side? From the source code it looks like the title really is just hard-coded 

https://github.com/neovim/neovim/blob/b40ec083ae30eb64ddfec2b238c909116e936e99/runtime/lua/vim/lsp/handlers.lua#L245-L268

**Comment by glepnir** [comment]
there pass line as text 

https://github.com/neovim/neovim/blob/b40ec083ae30eb64ddfec2b238c909116e936e99/runtime/lua/vim/lsp/util.lua#L1810-L1818


![QQ_1725781801995](https://github.com/user-attachments/assets/0657ef42-f30c-4e46-8450-ae4c968d71cd)

**Comment by glepnir** [comment]
`:help vim.lsp.ListOpts` you can custom it.

```lua
local function on_list(options)
  options.title = 'Reference: ' .. vim.fn.expand('<cword>')
  vim.fn.setqflist({}, ' ', options)
  vim.cmd.cfirst()
end
vim.lsp.buf.references(nil, { on_list = on_list })
```

**Comment by mfussenegger** [comment]
> ```lua
> options.title = 'Reference: ' .. vim.fn.expand('<cword>')
> ```

Just keep in mind that the current win/buffer can change between the request and receiving the response due to it being asynchronous. To make this reliable it would have to capture the word when making the request and use the captured word in the callback.

**Comment by glepnir** [comment]
yup but this can be done in callback so when trigger buf.xx before user can store the data and do check in this on_list function

**Comment by justinmk** [comment]
Is it hard for the current default title to be changed? If not, let's just do that. Doesn't need to be configurable.

**Comment by ColinKennedy** [comment]
For the time being I've added this to my configuration. It works well

```lua
vim.keymap.set(
    "n",
    "grr",
    function()
        local word = vim.fn.expand('<cword>')

        local function on_list(options)
          options.title = 'Reference: ' .. word
          vim.fn.setqflist({}, ' ', options)
          vim.cmd.cfirst()
        end

        vim.lsp.buf.references(nil, { on_list = on_list })
    end,
    {
        buffer=buffer,
        desc="[g]o to [r]eferences - Show all locations where a variable is used."
    }
)
```

![image](https://github.com/user-attachments/assets/212faf9b-c60f-4f5a-8ec0-d6d82f4f0613)

Though it does require overriding `on_list` so as a general solution it's a bit lacking. As @glepnir suggested keeping the `<cword>` available through the call context would make for a cleaner solution I think.

This works for now though. Thank you for your insights, everyone!

**Comment by mfussenegger** [comment]
Closing as wontfix due to the reasons outlined in https://github.com/neovim/neovim/pull/30394#issuecomment-2387151056

A workaround is available: https://github.com/neovim/neovim/issues/30305#issuecomment-2336595696
