### ISSUE TITLE
Incsearch is executed when I enter some command in command mode

### ISSUE THREAD

**Issue by Jaehaks** [neovim/neovim#30304]
### Problem

When I enter some char in command line, incsearch is executed in case of specific pattern
I think if the pattern has dot(.), it search the words after dot.
This behavior are not shown in before 

https://github.com/user-attachments/assets/c4bccc41-1798-43cd-a024-00c90fb697d3

I tested it with `nvim --clean` and `nvim-nightly` , the problem is same

### Steps to reproduce

enter `:vim.keymap` in command mode

### Expected behavior

command mode is just command mode, not search mode

### Neovim version (nvim -v)

v0.10.1

### Vim (not Nvim) behaves the same?

yes,  vim - VI IMproved 9.1

### Operating system/version

Windows 10

### Terminal name/version

windows-terminal 1.21.240823001

### $TERM environment variable

xterm-256color

### Installation

scoop

**Comment by glepnir** [comment]
`vim` not command `:lua vim.keymap.set`

**Comment by Jaehaks** [comment]
@glepnir  
I know that. it is just exmple of situation.  But this behavior is unnormal as I think.
And even though I add `:lua` , the situation is same

**Comment by zeertzjq** [comment]
`:vim` is the `:vimgrep` command, which supports incsearch.
