### ISSUE TITLE
Text becoming unconcealed when scrolling horizontally

### ISSUE THREAD

**Issue by OXY2DEV** [neovim/neovim#30324]
### Problem

When scrolling horizontally `concealed text` become unconcealed shifting the normal texts.

https://github.com/user-attachments/assets/1411cd5d-4f74-438d-8abc-9780e18f4311

<sub>The ":help" text is becoming unconcealed</sub>

### Steps to reproduce

nvim --clean
:set nowrap
:h

Now, keep scrolling *left* until the space before `:help` goes outside of the screen (you can either use `zl` or `sidescrolloff=999` to make it easier to reproduce).

### Expected behavior

Concealed texts remain concealed even when they are outside the screen.

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1720049189

### Vim (not Nvim) behaves the same?

no, Vim doesn't seem to scroll with the cursor.

### Operating system/version

Android 14

### Terminal name/version

Termux 0.119.0

### $TERM environment variable

xterm-256color

### Installation

Pkg(via `pkg install neovim`)

**Comment by justinmk** [comment]
Please test the latest development version. The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.

**Comment by OXY2DEV** [comment]
> Please test the latest development version.

That's the fun part, I can't 😐.

I have downloaded the `.tar ` file and tried to run the binary which resulted in `exec format error`.

I have also tried copying the repo and using `cmake` to build it. I also installed the `utf8-proc` package(since this caused an error in my first attempt).

Next attempt resulted in this,
![Screenshot_2024-09-10-15-21-57-765_com termux-edit](https://github.com/user-attachments/assets/044d234b-81f9-4f84-91d6-b6a0a92e2037)

**Comment by clason** [comment]
> Android 14

That is not a supported platform. Things may work, but we can't help you if they don't. Best option is to clone the repo, make sure all build requirements (see `BUILD.md`) are installed, then `make` and run `VIMRUNTIME=./runtime ./build/bin/debug/nvim --clean`.

**Comment by OXY2DEV** [comment]
> I certainly can't reproduce the issue.

That is very strange. I have also tested this inside `xfce-terminal` and it's still there.

If you have `markdown` parser installed you can try this.

Set the `conceallevel` to 2(or 3 if you like).

Create a code block.

Add an extmark(at the end of the line) on the line where the code block starts and scroll left and see if the extmark starts moving too.

![Screenshot_2024-09-10-15-46-07-133_com termux-edit](https://github.com/user-attachments/assets/79d1143b-c0c8-4421-90ca-7cf372d5d799)
<sub>The extmarks in the line above & below are off by 2 column.</suv>

**Comment by clason** [comment]
Please provide _exact_ steps (content to copy & paste in a buffer), _exact_ sequence of keystrokes.

**Comment by OXY2DEV** [comment]
Text to add to the buffer.

    ```lua
    vim.print("");
    ```

Set conceallevel to 2 ad
```vim
:set conceallevel=2
```

> You may want to set the `sidescrolloff` to a very high value or use `zl`.

Command to run.
```vim
:lua vim.api.nvim_buf_set_extmark(vim.api.nvim_get_current_buf(), vim.api.nvim_create_namespace("repro"), 0, 6, { virt_text_pos = "inline", virt_text = { { "Virtual text " } } })
```

Initial result.
![Screenshot_2024-09-10-16-03-05-000_com termux-edit](https://github.com/user-attachments/assets/54e05325-195b-492e-80f4-19b1640b5b7f)

After scrolling.
![Screenshot_2024-09-10-16-03-18-977_com termux-edit](https://github.com/user-attachments/assets/b4d79e2a-66e8-4b64-98f5-64d986267c64)

Without `conceallevel`.
![Screenshot_2024-09-10-16-03-32-890_com termux-edit](https://github.com/user-attachments/assets/470e261c-640a-4150-8037-511691cd808e)

**Comment by clason** [comment]
> Initial result.

That does not match your steps.

**Comment by OXY2DEV** [comment]
> > Initial result.
> 
> That does not match your steps.

If you are talking about that gibberish text then that's the simplest way I could get Neovim to scroll.

You can use `zl`, `shrink the window`, `split the window` or use `sidescrolloff`.

**Comment by OXY2DEV** [comment]
Oh, I forgot to remove the command 🤦.

Anyway the text on the bottom is the command I ran(I used `:lua` with visual selection).

I can also include that if that helps.

**Comment by clason** [comment]
Again, we _need_ FULL and EXACT, unambigous, steps that match "expected/actual" outcome. The more you try to hand-wave this, the harder you make it for us (to the point where people will just ignore the issue and wait for a better one if it's an actual bug).

**Comment by OXY2DEV** [comment]
> Again, we _need_ FULL and EXACT, unambigous, steps that match "expected/actual" outcome. The more you try to hand-wave this, the harder you make it for us (to the point where people will just ignore the issue and wait for a better one if it's an actual bug).

I have updated the repro. Does this help?

**Comment by clason** [comment]
1. That's not using `nvim --clean`.
2. The new video does not correspond to the issue title: nothing is being "unconcealed" there; in fact, this looks exactly like I would expect it to behave.

**Comment by OXY2DEV** [comment]
> this looks exactly like I would expect it to behave.

Noted. Closing the issue.
