### ISSUE TITLE
Broken wiki links

### ISSUE THREAD

**Issue by errael** [neovim/neovim#30336]
### Problem

I came across links to locations under neovim/wiki that don't exist. Presumable they used to exists; is there an archive somewhere? The one's I'm interested in seem to have to do with how neovim is/has-been put together.

I'm wondering if there's a cache of early design notes and/or "what/how it is" information. Has this stuff been lost.

In https://github.com/neovim/neovim/wiki/Introduction
    "See the Plugin Architecture page for a detailed overview"
    https://github.com/neovim/neovim/wiki/Plugin-UI-architecture

The following isn't strictly speaking a `neovim` issue. But since the article that has the broken link is referenced from https://neovim.io/ ...

In https://geoff.greer.fm/2015/01/15/why-neovim-is-better-than-vim/
    https://github.com/neovim/neovim/wiki/Porting-OS-layer-to-libuv

### Steps to reproduce

See OP

### Expected behavior

Functional link, possibly to a redirect.

### Neovim version (nvim -v)

NA

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

NA

### Terminal name/version

NA

### $TERM environment variable

NA

### Installation

NA

**Comment by clason** [comment]
> In https://github.com/neovim/neovim/wiki/Introduction
"See the Plugin Architecture page for a detailed overview"
https://github.com/neovim/neovim/wiki/Plugin-UI-architecture

Thanks, removed. That page was severely outdated, see `:h ui` for current info (although that does not fit the context of that Wiki page).

The other link is outside of our control.

**Comment by clason** [comment]
(The Wayback Machine is your friend, if you're interested in digital archaeology.)
