### ISSUE TITLE
lsp semantic highlighting: modifiers: cannot toggle property already defined on type

### ISSUE THREAD

**Issue by qdbp** [neovim/neovim#30351]
### Problem

`@lsp.mod` modifier highlight options do not work if the same field is set on the `@lsp.type`. That is you cannot override existing highlighting options, but only add new ones.

Specifically, setting `bold = false` on the mod does not work if `bold = true` is set on the type, despite the fact that the mod has a higher priority. Note that setting new keys works correctly. The screenshot below captures this situation:

![image](https://github.com/user-attachments/assets/5f557ecc-d2ec-4f86-80f2-08f1fb2fc30a)

### Steps to reproduce

Set `bold = true` on an lsp type, and then set `bold = false` on an lsp mod.

Please note that the `mod` explicitly has a higher priority!

### Expected behavior

The mod property takes precedence and sets `bold = false`. In the screenshot, `sol` should be italic but not bold.

### Neovim version (nvim -v)

NVIM v0.10.1

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Linux MAIN 6.10.6-arch1-1

### Terminal name/version

termite v16.9 vte 0.76.1 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

xterm-256color

### Installation

pacman

**Comment by wnineg** [comment]
For the current implementation of how the style attributes are combined when multiple highlights are applied, the style flags (bold, italic, strikethrough, underline etc, not the color/blend values) cannot be reset once set by one of the groups.

You could workaround that by setting `nocombine = true` for `@lsp.mod.definition`, though that means it will override (instead of combining) all those style flags of the lower ones.

**Comment by qdbp** [comment]
thanks for the explanation, though I must admit this feel like an arbitrary limitation.

out of curiosity, are there any fundamental issues that lead to this limitation, or is this potentially a straightforward fix? would a PR to lift this limitation and allow feature overrides be, in principle, well received?

**Comment by justinmk** [comment]
> would a PR to lift this limitation and allow feature overrides be, in principle, well received?

If it only fixes a bug, then certainly. If it adds another way to "prioritize" highlights, then no. If it's something in between, then... maybe. Review the discussion on these PRs:

- https://github.com/neovim/neovim/pull/21100
- https://github.com/neovim/neovim/pull/22022
- https://github.com/neovim/neovim/pull/27131

cc @jdrouhard @swarn @gpanders
