### ISSUE TITLE
vim.fn.match (and related) bug when dash is present

### ISSUE THREAD

**Issue by componhead** [neovim/neovim#30357]
### Problem

please, refer to [asciinema](https://asciinema.org/a/5rQ0fEzzXRdzOEu3Ao4998SQc)

### Steps to reproduce

please, refer to [asciinema](https://asciinema.org/a/5rQ0fEzzXRdzOEu3Ao4998SQc)

### Expected behavior

please, refer to [asciinema](https://asciinema.org/a/5rQ0fEzzXRdzOEu3Ao4998SQc)

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

is in nvim api specific command (`vim.fn.match`)

### Operating system/version

14.6.1 (23G93)

### Terminal name/version

fish, version 3.7.1

### $TERM environment variable

xterm-256color

### Installation

brew install

**Comment by clason** [comment]
Please use your words; we need a clear description and _explicit_ steps to reproduce the issue.

**Comment by componhead** [comment]
in a statement like:
```
:lua=string.match(vim.fn.expand(‘%:p’), ‘/Users/emiliano/Documents/prova-dash’)
```
if `vim.fn.expand(‘%:p’)` contains a dash `-` the result is incorrect (`nil`)

see the asciinema, I think is exaustive, otherwise you can close the task. Could be a Lua 5.1 issue or a `vim.fn.match` issue.
thank you

**Comment by justinmk** [comment]
p.s. to force something to be escaped, you can use `vim.pesc()`:

    string.match(..., vim.pesc('/Users/emiliano/Documents/prova-dash')
