### ISSUE TITLE
LSP: with "augmentsSyntaxTokens = true", no semantic tokens for many keywords in Rust

### ISSUE THREAD

**Issue by HoldMyBeer1111** [neovim/neovim#30369]
### Problem

Many Rust keywords lack the `lsp.type.keyword.rust` semantic token.

[Relevant discussion](https://github.com/mrcjkb/rustaceanvim/discussions/503)

No additional configuration is required for rust-analyzer to emit these tokens for such common keywords as `let`, `use`, `pub`, etc.
That looks weird, could it be a neovim and rust_analyzer interaction bug? Or do I miss something?

### Steps to reproduce using "nvim -u minimal_init.lua"

Reproducable in any Rust project.

minimal_init.lua
```lua
--- CHANGE THESE
local pattern = 'rust'
local cmd = {'rust-analyzer'}
-- Add files/folders here that indicate the root of a project
local root_markers = {'.git', '.editorconfig'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'bugged-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```

### Neovim version (nvim -v)

v0.11.0-dev-763+gdeac7df80

### Language server name/version

 0.4.2108-standalone

### Operating system/version

Linux 6.10.9-arch1-2 #1 SMP PREEMPT_DYNAMIC Tue, 10 Sep 2024 14:37:32 +0000 x86_64 GNU/Linux

**Comment by clason** [comment]
Why would you expect these to be present? Does VS Code show them? In general, if you see _some_ semantic tokens, you see _all_ of them. So if they don't show up, the server isn't sending them.

**Comment by HoldMyBeer1111** [comment]
> Why would you expect these to be present? Does VS Code show them?

Yes, VS Code shows them. You can follow the discussion link I gave in the original message for more info.

**Comment by justinmk** [comment]
You can use the `:Inspect` command or right-click on the token and choose "Inspect", to see Nvim's current highlights/groups associated with a token.


From the discussion you linked:

> Then I suggest asking in the rust-analyzer discussions. It could be a non-standard token that isn't supported by Neovim

If non-standard tokens are a thing, then that's between you and your LSP server. Inspect the lsp logs. We can't debug every random lsp server.

**Comment by HoldMyBeer1111** [comment]
> You can use the `:Inspect` command or right-click on the token and choose "Inspect", to see Nvim's current highlights/groups associated with a token.

Just like I did.

> We can't debug every random lsp server.

That's an official LSP server for Rust (https://github.com/rust-lang/rfcs/pull/2912).

> If non-standard tokens are a thing, then that's between you and your LSP server. Review your lsp logs.

A file starts with `use std::{`. Logs in VS Code:
```
"semanticTokensProvider": {
            "legend": {
                "tokenTypes": [
                    "comment",
                    "decorator",
                    "enumMember",
                    "enum",
                    "function",
                    "interface",
                    "keyword",
                    "macro",
                    "method",
                    "namespace",
...........................
"tokenModifiers": [
                    "async",
                    "documentation",
                    "declaration",
                    "static",
                    "defaultLibrary",
                    "associated",
                    "attribute",
                    "callable",
                    "constant",
                    "consuming",
                    "controlFlow",
                    "crateRoot",
                    "injected",
                    "intraDocLink",
                    "library",
............................
Received response 'textDocument/semanticTokens/full - (13)' in 3293ms.
Result: {
    "resultId": "2",
    "data": [
        0,
        0,
        3,
        6,
        0,
        0,
        4,
        3,
        9,
        18448,
```
So `use` is just a standard keyword token and `std` is a namespace token with `defaultLibrary`, `crateRoot`, `library` modifiers (18448=100100000010000).

At the same time in neovim:

OK for `std`
```
Semantic Tokens
  - @lsp.type.namespace.rust links to Type priority: 125
  - @lsp.mod.crateRoot.rust links to @lsp priority: 126
  - @lsp.mod.defaultLibrary.rust links to @lsp priority: 126
  - @lsp.mod.library.rust links to @lsp priority: 126
  - @lsp.typemod.namespace.crateRoot.rust links to @lsp priority: 127
  - @lsp.typemod.namespace.defaultLibrary.rust links to @lsp priority: 127
  - @lsp.typemod.namespace.library.rust links to @lsp priority: 127

Syntax
  - rustModPath links to PreProc
```
NOT OK for `use`
```
Syntax
  - rustKeyword links to Statement
```

Any suggestions?
Maybe I can get similar logs in neovim to see `data`?

**Comment by clason** [comment]
`:h vim.lsp.set_log_level()`. Logs are written (by default) to `~/.local/state/nvim/lsp.log`.

**Comment by HoldMyBeer1111** [comment]
I looked at both neovim and rust-analyzer LSP logs and figured out that the reason is [this](https://github.com/neovim/neovim/blob/3b54adc6c6d25dd146fa1eac21321f6bd612f50a/runtime/lua/vim/lsp/protocol.lua#L405) setting.
VS Code sets it to false, and neovim sets it to true.

According to the specification:
> Whether the client uses semantic tokens to augment existing syntax tokens. If set to `true` client side created syntax tokens and semantic tokens are both used for colorization. If set to `false` the client only uses the returned semantic tokens for colorization.

So it depends on a colorization approach and affects how many tokens LSP server sends.

What do you think about having it "true" vs "false" vs configurable ?

**Comment by clason** [comment]
It _is_ configurable: Just set the capability to `false`.

**Comment by HoldMyBeer1111** [comment]
Thank you for the answers.

**Comment by justinmk** [comment]
@HoldMyBeer1111 Thanks for diving in and sharing a resolution!
