### ISSUE TITLE
`vim.opt` vs `vim.o`

### ISSUE THREAD

**Issue by lorypelli** [neovim/neovim#30383]
### Problem

`vim.opt` is the newest method recommended while using neovim, but the problem is that if I hover over it with the lsp, options aren't documented, while they are using `vim.o`, could you please add also documentation to that, or, should I use `vim.o` instead for the code below?

### Steps to reproduce using "nvim -u minimal_init.lua"

vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true

vim.opt.termguicolors = true
vim.opt.relativenumber = true

vim.opt.cursorline = true
vim.opt.cursorlineopt = "number"

vim.opt.clipboard = "unnamedplus"

### Expected behavior

`vim.o` shows simple documentation for options, while `vim.opt` doesn't

### Neovim version (nvim -v)

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
```

### Language server name/version

lua_ls

### Operating system/version

Arch Linux Kernel 6.10 Endeavour OS

**Comment by lorypelli** [comment]
I'm also using `lazydev`

**Comment by lorypelli** [comment]
added neovim full version output to the initial comment

**Comment by justinmk** [comment]
use `vim.o`. `vim.opt` will be removed. Tracked in https://github.com/neovim/neovim/issues/20107 (do not add comments to that issue)

**Comment by clason** [comment]
Also see `:h lua-guide-options`

**Comment by lorypelli** [comment]
> use `vim.o`. `vim.opt` will be removed. Tracked in #20107 (do not add comments to that issue)

wasn't `vim.o` the old way and `vim.opt` the new one?

**Comment by justinmk** [comment]
read the linked issue, not having this discussion again

**Comment by lorypelli** [comment]
```diff
- vim.opt.tabstop = 4
- vim.opt.shiftwidth = 4
- vim.opt.expandtab = true

- vim.opt.termguicolors = true
- vim.opt.relativenumber = true

- vim.opt.cursorline = true
- vim.opt.cursorlineopt = "number"

- vim.opt.clipboard = "unnamedplus"
- vim.opt.tabstop = 4
- vim.opt.shiftwidth = 4
- vim.opt.expandtab = true

- vim.opt.termguicolors = true
- vim.opt.relativenumber = true

- vim.opt.cursorline = true
- vim.opt.cursorlineopt = "number"

- vim.opt.clipboard = "unnamedplus"
+ vim.opt.tabstop = 4
+ vim.opt.shiftwidth = 4
+ vim.opt.expandtab = true

+ vim.o.termguicolors = true
+ vim.o.relativenumber = true

+ vim.o.cursorline = true
+ vim.o.cursorlineopt = "number"

+ vim.o.clipboard = "unnamedplus"
+ vim.o.tabstop = 4
+ vim.o.shiftwidth = 4
+ vim.o.expandtab = true

+ vim.o.termguicolors = true
+ vim.o.relativenumber = true

+ vim.o.cursorline = true
+ vim.o.cursorlineopt = "number"

+ vim.o.clipboard = "unnamedplus"
```

will it work as expected now that I did this?

**Comment by brianhuster** [comment]
I read the issue, but does that mean when `vim.opt` is removed, I can no longer set like `vim.o.backspace = 'indent,start,eol'` but must set it like `vim.o.backspace = { 'indent', 'start', 'eol' }`?

**Comment by justinmk** [comment]
> I read the issue, but does that mean when `vim.opt` is removed, does
> 
> vim.o.backspace = 'indent,start,eol'
> still work?

That will still work, no breaking changes are planned for `vim.o` here.
