### ISSUE TITLE
Compile Error with current master branch 

### ISSUE THREAD

**Issue by pmqtt** [neovim/neovim#30399]
### Problem

Hello dear community,

I am currently trying to compile Neovim, but unfortunately, I am failing. Regardless of whether I use Clang or GCC, I get the following error:

```shell
/home/cefour/projects/opensource/neovim/src/nvim/mbyte.c: In function »utf_char2cells«:
/home/cefour/projects/opensource/neovim/src/nvim/mbyte.c:483:29: error: »utf8proc_property_t« {alias »const struct utf8proc_property_struct«} has no member named »ambiguous_width«
  483 |   if (*p_ambw == 'd' && prop->ambiguous_width) {
      |                             ^~
/home/cefour/projects/opensource/neovim/src/nvim/mbyte.c:489:39: error: »utf8proc_property_t« {alias »const struct utf8proc_property_struct«} has no member named »ambiguous_width«
  489 |   if (p_emoji && c >= 0x1f000 && !prop->ambiguous_width && prop_is_emojilike(prop)) {
      |                                       ^~
/home/cefour/projects/opensource/neovim/src/nvim/mbyte.c: In function »utf_ambiguous_width«:
/home/cefour/projects/opensource/neovim/src/nvim/mbyte.c:1353:13: error: »utf8proc_property_t« {alias »const struct utf8proc_property_struct«} has no member named »ambiguous_width«
 1353 |     if (prop->ambiguous_width || prop_is_emojilike(prop)) {
      |             ^~
make[2]: *** [src/nvim/CMakeFiles/nvim_bin.dir/build.make:5522: src/nvim/CMakeFiles/nvim_bin.dir/mbyte.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:623: src/nvim/CMakeFiles/nvim_bin.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```
A bit of research has shown that the Gentoo community is currently facing this issue as well! I must say I don’t understand this message, as the structure utf8proc_property_struct should have the ambiguous_width field.
Thank you very much!

### Steps to reproduce

mkdir build
cd build
CC=gcc cmake .. 
make

### Expected behavior

should compile!

### Neovim version (nvim -v)

master

### Vim (not Nvim) behaves the same?

-

### Operating system/version

manjaro

### Terminal name/version

kitty

### $TERM environment variable

-

### Installation

sourcecode

**Comment by clason** [comment]
`make distclean`

**Comment by clason** [comment]
Does it work if you actually use the provided Makefile (or follow the build instructions)?

**Comment by pmqtt** [comment]
I just cloned the latest master of Neovim. Then I ran `make distclean`, followed by `mkdir build`, `cd build` and then `cmake ..`

Thank you for your time!

**Comment by clason** [comment]
Yes, and I'm saying you should follow the build instructions; otherwise it's not guaranteed (nor tested) to work. Try `git clean -fdx` and just `make`. Does that work?

**Comment by clason** [comment]
... which our build scripts will pull in if used correctly (which is what I'm trying to debug here)

**Comment by pmqtt** [comment]
Oh guys,
I’m sorry. Those who can read the instructions in BUILD.md definitely have an advantage. It was my mistake!
make distclean
make deps
solved the problem.
Sorry for wasting your time!
