### ISSUE TITLE
'cursorcolor' should be above folds

### ISSUE THREAD

**Issue by mkoskar** [neovim/neovim#3039]
Having `curcorcolor` enabled by doing e.g., `setl cc=+1` and at the same time
having folded fold, `hi Folded ctermbg` overrides `hi CursorColor ctermbg`
i.e., folds are "on top" of `cursorcolor`.  That differs from Vim, where it
is otherwise versa, so `cursorcolor` is "on top" of folds.

I've raised this on irc/gitter first, with @mhinz stating: "Confirmed".

**Comment by mhinz** [comment]
Haven't really looked into it yet, but apparently it was the same behaviour in Vim 7.3 (OSX default), so it's  probably not really broken in Neovim, it just lacks a certain patch. </guessing>

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/3043
