### ISSUE TITLE
docs: mention "x86_64" instead of "linux64" to clarify Intel vs ARM

### ISSUE THREAD

**Issue by libweirdness** [neovim/neovim#30403]
### Problem

Many people now live in 64-bit ARM-based machines.

Telling people "just install the Linux64 package!", when that Linux64 is x86_64 architecture ONLY,
& all the OTHER Linux64 architectures ( ARM, RISC-V, etc ) CANNOT run it,
is .. from our perspective, bullying..

Unintentional, obviously, as x86_64 people may *presume* that no other architecture exists,

but it's bullying from our perspective, nontheless..

Please qualify the instructions correctly,

so that people not in your architecture are not told to try things that won't ever work,
& just batter our lives against non-possible "solutions", that ignore architecture.

This goes for several pages on this site, not just
https://github.com/neovim/neovim/blob/master/INSTALL.md
one, I think.

Salut, Namaste, & Kaizen,

_ /\ _

### Steps to reproduce

it is a bug in the phrasing of the instructions on this site, not in the code, itself.

### Expected behavior

Tell people the correct instructions, at the correct granularity, & don't presume all non-x86_64 architectures don't exist.

### Neovim version (nvim -v)

it's this site's instructions, not the app, itself

### Vim (not Nvim) behaves the same?

no.

### Operating system/version

Ubuntu 24.04LTS aarch64

### Terminal name/version

bash

### $TERM environment variable

xterm-256color

### Installation

I'm using apt.

**Comment by justinmk** [comment]
send a PR

**Comment by dundargoc** [comment]
> I'm using apt.

Uh, does debuntu not support aarch64 @jamessan?

**Comment by jamessan** [comment]
> Uh, does debuntu not support aarch64 @jamessan?

It does, although it's called arm64.

**Comment by dundargoc** [comment]
@libweirdness it seems ubuntu/debian supports arm builds of neovim just fine. What is the problem exactly?

**Comment by justinmk** [comment]
I think the request is that we rename `linux64` to `x86_64` [here](https://github.com/neovim/neovim/blob/master/INSTALL.md#linux).

That will require another breaking URL change...

**Comment by zeertzjq** [comment]
> I think the request is that we rename `linux64` to `x86_64` [here](https://github.com/neovim/neovim/blob/master/INSTALL.md?rgh-link-date=2024-09-18T06%3A33%3A04Z#linux).
> 
> That will require another breaking URL change...

But that doesn't include "linux"

**Comment by justinmk** [comment]
Going to consider this "wontfix" because it would require a breaking change to the URL:

    https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz

When we introduce ARM builds, we'll provide a `nvim-linux-arm64` build or something like that. Until then, yes, there's a small, unfortunate ambiguity.
