### ISSUE TITLE
Incapable of creating iabbrev's for Greek alphabet, copyright-symbols, other unicode items, to match Julialang's entry-method.

### ISSUE THREAD

**Issue by libweirdness** [neovim/neovim#30405]
### Problem

Julialang, THE math/science language,
has *all sorts of characters that can be entered,
https://docs.julialang.org/en/v1/manual/unicode-input/

& given that it's a math/engineering/science language,
it's important that these be the same in one's editor as they are in the language

( having to learn 2 entire sets of entry-"shortcuts",
e.g. :digraphs in Vim & Neovim,
then Julia's \Gamma for the angular Greek capital-G,
is a *insane* abuse-of-finite-mental-resources from our entire population. )

Neovim NEEDS to give us the ability to have our entry-method MATCH Julialang's items.

WHEN I enter

:iab \copyright <ctrl-v>u00a9

( I'm using this as an example, simply because the Greek characters are less likely to be installed on a system than the copyright-symbol is,
but it's the same error, for the entire Greek alphabet )

both Vim & Neovim 9.5 give the error

E474: Invalid argument

"Oh, but you HAVE TO USE VIM'S DIGRAPHS,
& then when you're in Julia, you have to use their shortcuts, instead:
MEMORIZE BOTH, to be able to work,
XOR go switch to some other editor-type!"

*isn't* The Right Answer(tm),
if you see what I mean..

---

It doesn't work when one is in the editor, AND it doesn't work in .vimrc.

In my .vimrc I've got these, to try to make it work,
& it still doesn't work:

set encoding=utf-8
set fileencoding=utf-8
scriptencoding utf-8

( notice the different-format of that one, which took much bashing around the 'web to discover, as almost-all of the "help" out there got that wrong, some including an equals-sign, some including "set ", etc..
again, needless arbitrary-memorization is required, abusing finite mental-resources.. )

then..

iab  \copyright  <ctrl-v>u00a9 ( this produces the actual-symbol that I want to appear, when I type-in \copyright )

is broken.

I'm asking that Neovim be caused to accept the COMPLETE set of Unicode as input-abbreviations:

This would allow people with their *names* in other-character-sets to use :iab to get their *actual* name in their English text-documents,
and this would fix Julia-users' working with Neovim, simultaneously.

( :

### Steps to reproduce

Within the editor:

:iab  \copyright  <ctrl-v>u00a9
( that last token autoconverts to the copyright-symbol: © )

when one taps Enter, then one gets the
invalid argument
error.

---

Within .vimrc

set encoding=utf-8
set fileencoding=utf-8
scriptencoding utf-8

iab \copyright ©
( obviously from the same <ctrl-v>u00a9 key-sequence )

:wq

re-open your .vimrc, & neovim will balk with the
E474 invalid argument
error, again.

### Expected behavior

We should be able to create iabbreviations with ANY unicode-character.

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release, LuaJIT 2.1.1703358377

### Vim (not Nvim) behaves the same?

yes Vim does the same damn bug, 9.1

### Operating system/version

Ubuntu server, aarch64, 24.04LTS

### Terminal name/version

bash 5.2.21

### $TERM environment variable

xterm-256color

### Installation

Ubuntu's apt facility

**Comment by libweirdness** [comment]
* sigh *

My entering of the copyright-symbol got replaced,
on this Git system,
with just-the u00a9

so IT WON'T PERMIT YOU TO SEE WHAT I'D ENTERED.

fscking "helpfulness", that.

Sorry I'm not allowed to show you the actual what-we-enter to produce the bug.

: (

**Comment by zeertzjq** [comment]
`:set iskeyword+=\\`
