### ISSUE TITLE
Still Poor performance with Treesitter highlighting on deep if-else in c

### ISSUE THREAD

**Issue by kaddkaka** [neovim/neovim#30424]
### Problem

Similar/same issue #24965 (Poor performance with Treesitter highlighting on deep if-else in c)

### Steps to reproduce

Perhaps this case is a bit extreme, but a file containing:
```
int main() {
  if (1) {
  } else if (2) {
  } else if (3) {
[...]
  } else if (19999) {
  } else if (20000) {
  }
}
```

1. Go to the bottom of the file `G`.
2. Hold down ctrl-u to scroll up for a while and notice considerable lag.
3. `:TSDisable highlight`
4. Repeat 2. and notice no lag

### Expected behavior

Fast scrolling no matter if basic highlighting or tree sitter highlighting is used.

### Neovim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

no, since treesitter related

### Operating system/version

Ubuntu 22.04

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

downloaded tar.gz from github

**Comment by kaddkaka** [comment]
Related?
- https://github.com/neovim/neovim/pull/22420
- https://github.com/neovim/neovim/issues/27155
- #22426
- https://github.com/neovim/neovim/issues/28017

**Comment by clason** [comment]
Yes, we know. Performance improvements are planned and ongoing. In particular, we need to chunk parsing. Feel free to pick up lewis' async PR.

**Comment by clason** [comment]
https://github.com/tree-sitter/tree-sitter-c/issues/198

**Comment by vanaigr** [comment]
I noticed `nvim-treesitter` overrides fast version of `has-ancestor?` predicate from #28512 with the older slow version since nvim-treesitter/nvim-treesitter@95850f7964e5be713ab984384641cc15973626c6. And the example in the original issue #24965 is now slow again.

**Comment by clason** [comment]
Thank you for the reminder; nvim-treesitter requires 0.10.0 now so we can remove those.

**Comment by clason** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/7272

**Comment by vanaigr** [comment]
With the new version, `G` takes less than 1ms.

Generating the file:
```lua
local s = { 'int main() {', '  if (1) {' }
for i = 2, 20000 do
  table.insert(s, '  } else if (' .. i .. ') {')
end
table.insert(s, '}')
vim.api.nvim_buf_set_lines(0, 0, 0, false, s)
```

Timing:
```
:lua print((function() local a = vim.uv.hrtime(); vim.cmd('norm! G'); local b = vim.uv.hrtime(); return ((b - a) / 1000000) .. 'ms' end)())
```

**Comment by clason** [comment]
(Still, the grammar should be rewritten to avoid such a deeply nested tree so I reopened the tree-sitter-c issue.)
