### ISSUE TITLE
LSP: improved core support for "hint diagnostics"

### ISSUE THREAD

**Issue by jfly** [neovim/neovim#30444]
### Problem

This is sort of a re-post of <https://github.com/neovim/nvim-lspconfig/issues/1788>, but hopefully in a place where it will get some traction. That issue is locked, so I don't know if @bavalpey or @baltitenger got answers somewhere else. CC-ing them here in case they did.

I've read through this awfully long thread on Pyright: <https://github.com/microsoft/pyright/issues/1118>. If you haven't read this before, don't. @baltitenger summarized it well [in their issue to nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/issues/1788).

In short: the Pyright author says that it's a bug if a IDE displays "hint diagnostics" ([VS Code doesn't seem to show them anywhere](https://github.com/microsoft/language-server-protocol/issues/1696#issuecomment-1482487245)). Here's some discussion on the spec about this: <https://github.com/microsoft/language-server-protocol/issues/1696>.

However, Neovim does not behave this way out of the box (I just checked with <https://github.com/neovim/neovim/commit/100bb15d186ce855d064e86ff4630d9ad8d43a5e>, the latest `main` when I started writing this issue):

- `vim.diagnostic.handlers`
  - `sign`: Arguably wrong: displays diagnostic hints in signcolumn
  - `underline`: This handler does the right thing with `DiagnosticTag.Unnecessary`. @lewis6991 did this in <https://github.com/neovim/neovim/pull/22747>. Thanks!
  - `virtual_text`: Arguably wrong: displays diagnostic hints at the end of lines
- `vim.diagnostic.goto_next` and `vim.diagnostic.goto_prev`: Arguably wrong: these navigate to non-actionable hint diagnostics

### Expected behavior

I am not the first person to think neovim should have more nuanced handling of "hint diagnostics".

- The aforementioned nvim-lspconfig issue: <https://github.com/neovim/nvim-lspconfig/issues/1788>
- @gpanders mentions it in <https://github.com/neovim/neovim/pull/22747#issuecomment-1478040364>
  > We could modify the default settings for virtual text, signs, and underline to not display hint messages, but still display them in open_float. That seems like a reasonable middle ground to me.
- I checked, and some of the early iterations of <https://github.com/neovim/neovim/pull/22747> had this filtering, but it looks like it was backed out for a couple of reasons:
  - <https://github.com/neovim/neovim/pull/22747#issuecomment-1478093281>
    > There's a good chance that another language sever assumes that the message stays accessible for users.
  - <https://github.com/neovim/neovim/pull/22747#issuecomment-1478124774>
    > However, up till now vim.diagnostic has remained completely decoupled from any "LSP"-isms. Having goto_next and friends check for an LSP tag would introduce a coupling. Not sure that's a good idea.
- [Here's some lua code from the prolific @lewis6991](https://github.com/neovim/neovim/issues/17757#issuecomment-1401652935) demonstrating monkeypatching the existing `vim.diagnostic.handlers` to ignore `DiagnosticTag.Unnecessary` and adding a new `vim.diagnostic.handlers.unnecessary` that uses `vim.highlight` to annotate the relevant text as "unnecessary".
  - I believe this is the Lua code that @lewis6991 alluded to here: <https://github.com/neovim/neovim/pull/22747#issuecomment-1478074555>
    > I've had a bunch of custom lua code to handle this for a good while
  - However, that filtering logic never landed in `main`. I do see that @lewis6991 [eventually removed that logic from their dotfiles](https://github.com/lewis6991/dotfiles/commit/63f7474ab6862658eaf2371ba09a0832ce599b2f), I don't know why.
- Here's an even older (now closed, never merged) PR that also implements that filter logic: <https://github.com/neovim/neovim/pull/15333/>.

@lewis6991, is there interest in getting some of this filter logic merged into neovim core? I understand from the past discussions that differences between LSP server implementations may mean that there's currently no sane default behavior here, and perhaps whatever we do here needs to be configurable. I don't know if that means this shouldn't be part of core, and is instead something that should be handled by a plugin.

**Comment by lewis6991** [comment]
> In short: the Pyright author says that it's a bug if a IDE displays "hint diagnostics"

The pyright maintainer is wrong. This is why I removed the filtering logic from my dotfiles. These hints are still full diagnostics and the issue with pyright was that there was no way to suppress them.

**Comment by clason** [comment]
To tack on to that:

> I am not the first person to think neovim should have more nuanced handling of "hint diagnostics".

We frankly don't care. We implement the LSP protocol _and nothing but the LSP protocol_. If you are not satisfied with that, lobby Microsoft to extend the protocol.

**Comment by baltitenger** [comment]
Note that I already reposted that issue in this repo, see #17757 for the answers and a couple workarounds.

**Comment by dundargoc** [comment]
> the Pyright author says

top 10 moments before disaster

**Comment by jfly** [comment]
> Note that I already reposted that issue in this repo, see https://github.com/neovim/neovim/issues/17757 for the answers and a couple workarounds.

@baltitenger, I did see that issue, and actually did link to it in my OP.

I should have clicked on a few more links, though. I see that neodim seems to be implementing exactly the `vim.diagnostics.handlers` monkeypatching + filtering that @lewis6991 used to have in their dotfiles: https://github.com/zbirenbaum/neodim/blob/d87470828690342d0139efc2fd56ea0b29e9ecb3/lua/neodim/init.lua#L23. Awesome!

> The pyright maintainer is wrong

>  We implement the LSP specification and nothing but the LSP specification. If you are not satisfied with that, lobby Microsoft to extend the protocol.

I can hear the frustration in both your voices. I spent the last 5+ hours reading through issues and PRs and I've seen the herculean effort @lewis6991 went through to try to get this all sorted. Please bear with me, I only started going deep on this topic yesterday afternoon. You are literally years ahead of me. I'm just trying to understand the state of the world, and Neovim's opinions on this stuff.

One last question:

In Neovim's opinion, does the Language Server Protocol provide a mechanism for a LSP server to annotate some code as unused, *but not actually actionable*? I think this is (would be) a useful feature: I personally like having my unused variables grayed out even when I have to leave them there to satisfy the arity of some Python function.

As you know, the Pyright maintainer says "yes": it's by sending "hint diagnostics" with `DiagnosticTag.Unnecessary`. @zbirenbaum (maintainer of https://github.com/zbirenbaum/neodim) seems to agree ([relevant code here](https://github.com/zbirenbaum/neodim/blob/d87470828690342d0139efc2fd56ea0b29e9ecb3/lua/neodim/init.lua#L23-L31)).

Are you saying that the LSP spec doesn't have a way to do this? Or are you saying there's a different mechanism for this (semantic tokens? something else?)?

For the record, I have filed 2 issues with Microsoft to try to understand things better. It might be useful context for this discussion:

- https://github.com/microsoft/language-server-protocol/issues/2024
- https://github.com/microsoft/language-server-protocol/issues/2025

**Comment by clason** [comment]
> In Neovim's opinion, does the Language Server Protocol provide a mechanism for a LSP server to annotate some code as unused, but not actually actionable? I think this is (would be) a useful feature: I personally like having my unused variables grayed out even when I have to leave them there to satisfy the arity of some Python function.

You can read the specification as well as us; if you can point to a part we're not implementing correctly, feel free to open an issue. 

But the pyright maintainer's opinion (and it is just that, to the best of our knowledge) is irrelevant here.

**Comment by lewis6991** [comment]
> Or are you saying there's a different mechanism for this (semantic tokens)?

My interpretation is that semantics tokens supercede tagged hints. I haven't checked, but my guess is that tagged hints were introduced before semantic tokens.

**Comment by clason** [comment]
Diagnostic tags were added in 3.15.0, semantic tokens in 3.16.0.

**Comment by clason** [comment]
But let's not forget that the central issue here is the pyright's maintainer's refusal to respect common convention about unused values, which is completely unrelated to the LSP specification.

**Comment by jfly** [comment]
> if you can point to a part we're not implementing correctly, feel free to open an issue.

IIUC, I don't think that defining UI behavior is actually in scope for the Language Server Protocol. From https://github.com/microsoft/language-server-protocol/issues/1696#issuecomment-1480983199:

> I will close the issue since I really don't want to enforce UI rendering in the LSP specification.

I really do think that Neovim is completely following the spec by choosing to always display these "hint diagnostics".

I also think Neovim would be following the spec if it chose to do something different (like mostly ignore them, [IIUC, this is what VS Code does](https://github.com/microsoft/language-server-protocol/issues/1696#issuecomment-1482487245)).

I think I understand why y'all have chosen to have the current core-Neovim behavior, and y'all have done an admirable job of providing the Lua hooks necessary for people to do their own thing here (as @zbirenbaum has done in neodim).

> My interpretation is that semantics tokens supercede tagged hints. I haven't checked, but my guess is that tagged hints were introduced before semantic tokens.

You're correct about the history (tagged hints predate semantic tokens).

I don't think you're correct that semantic tokens supersede tagged hints. I wrote up my findings on this over in https://github.com/microsoft/language-server-protocol/issues/2024.

> But let's not forget that the central issue here is the pyright's maintainer's refusal to respect common convention about unused values, which is completely unrelated to the LSP specification

I won't deny that's how I got here. But I would not say that's the central issue. I'd instead phrase this as a feature request: I like having my editor dim out unused variables without telling me it's actionable. I want the Neovim + LSP ecosystem to support this "out of the box" without a plugin (no disrespect to @zbirenbaum for his work on neodim, I will probably use it!).

What I'm hearing from you is that tagged hints are not how Neovim want's to be told about this. I get it, and I get why. But I don't yet understanding what the "missing piece" is in the ecosystem to make this work. I'll follow up with y'all if I get some answers over on https://github.com/microsoft/language-server-protocol/issues/2024.

I hope this conversation has not been too triggering for anyone!

**Comment by clason** [comment]
> I like having my editor dim out unused variables without telling me it's actionable.

And you can do that. But working around a single server's idiosyncratic behavior is _not_ what we want to bake into core.

**Comment by jfly** [comment]
> But working around a single server's idiosyncratic behavior is not what we want to bake into core.

I hear you. I will report back if I learn anything over on https://github.com/microsoft/language-server-protocol/issues/2024

**Comment by gpanders** [comment]
>want the Neovim + LSP ecosystem to support this "out of the box" without a plugin

Could you elaborate a bit on what you’re wanting here? If your requirements are “I want this behavior with no configuration required” then indeed that is not likely to happen unless the LSP specification implements some mechanism for this (as already discussed). But Neovim core *should* already provide the tools (with `vim.diagnostic.config()`) to allow you to implement the behavior you want. If there is something lacking in our core APIs that prevents you from (easily) implementing that behavior then that is something we could fix.

**Comment by jfly** [comment]
> Could you elaborate a bit on what you’re wanting here?

Concretely, I want a world where a LSP server communicates information that causes an otherwise unconfirmed Neovim to behave in the following ways:

- `vim.diagnostic.handlers`
  - `sign`: Doesn't show anything about non-actionable unused code.
  - underline: Continues to do the highlight work that @lewis6991 implemented in  https://github.com/neovim/neovim/pull/22747
  - virtual_text: Doesn't show anything about non-actionable unused code.
- vim.lsp.buf.hover: I honestly am not sure what I want here. Pretty sure I'd rather it not tell me about non-actionable unused code.
- vim.diagnostic.goto_next and vim.diagnostic.goto_prev: These skip past non-actionable unused code.
- (there may be other parts of the core Neovim experience I'm unfamiliar with that should also be tweaked)

> that is not likely to happen unless the LSP specification implements some mechanism for this

That is now crystal clear to me =) I'll follow up with y'all if I get any traction on https://github.com/microsoft/language-server-protocol/issues/2026.

>  If there is something lacking in our core APIs that prevents you from (easily) implementing that behavior then that is something we could fix.

Nope! To repeat myself from earlier: I think y'all have done an admirable job of providing the Lua hooks necessary for people to do their own thing here. I can definitely make Neovim behave the way I want it to here.

**Comment by bavalpey** [comment]
It's interesting that I was mentioned here.

It's actually ironic. I begrudgingly stopped using Neovim in favor of VsCode simply because the ecosystem around it is way more stable and feature-complete.

This thread is ridiculous.

Quite frankly, I don't have the time to dive down into the rabbit holes to learn how to tweak my editor, the configuration for the editor's lsp config, and the configuration for the language server itself.

Balancing all of these things is difficult enough, and when the maintainers of these different components are all pointing fingers at each other saying "not my problem" it leads to a really bad user experience.

Wile I am sympathetic to the perspectives of the Neovim team here, it is indeed your problem. Sure, Eric Trait has his own opinions, and sure they may be wrong. But there's a relationship. You are expected, as a provider of an interface with the language server, to work with the maintainer such that it provides a workable and good user experience.

That is not happening.

Instead, we have Nvim- core maintainerd saying they've implemented the LSP spec to the tee and this issue isn't their problem (this one is fair). Then we have an Lsp-Config maintainer saying the issue was filed in the "wrong repo" (which is so unhelpful, and they never answered my question about what _is_ the right repo).
Then, we have the LSP maintainer doubling down and saying that the editor is doing something wrong.

As a user, I don't care about any of this. I just want to know what settings or configuration I need to do have to get the behavior I want. But after 2 years I still have no idea how to actually do this.
In not one of these issues has someone offered up a configuration solution that will allow us to have our desired behavior.

> But let's not forget that the central issue here is the pyright's maintainer's refusal to respect common convention about unused values

What is the common convention? (Genuine question).

> But Neovim core should already provide the tools (with vim.diagnostic.config()) to allow you to implement the behavior you want.

Great. Mind pointing out exactly how / where?



From a user, I don't want to have my diagnostic list littered with unused variable hints. Hints are not problems. They shouldn't be reported as such.

> (Keep in mind that other servers are using this diagnostic for actionable diagnostics.)

An unused variable *is* an actionable diagnostic. You can remove it, replace it with a bucket, etc...
The issue is the context.


The UX for hint diagnostics in vscode is abysmal. It's also not just a pyright thing. I don't know whose responsibility this is, but showing error/warning squiggles for hints, and also having them appear in the main diagnostic list should be revisited.

**Comment by clason** [comment]
> What is the common convention? (Genuine question).

That underscore arguments are intentionally unused, and thus should not be reported as a diagnostic. (Which I think is what you mean by "bucket"?) This is how many other servers and tooling behave.

> In not one of these issues has someone offered up a configuration solution that will allow us to have our desired behavior.

Did you read `:h vim.diagnostic`? 

>> But Neovim core should already provide the tools (with vim.diagnostic.config()) to allow you to implement the behavior you want.
> Great. Mind pointing out exactly how / where?

He just did.

**Comment by justinmk** [comment]
> As a user, I don't care about any of this. I just want to know what settings or configuration I need to do have to get the behavior I want

This is a fair point, and we're working on it but it will take time since it requires someone to really "own" the project of upstreaming [parts](https://github.com/neovim/neovim/issues/28329) of https://github.com/neovim/nvim-lspconfig and reorienting nvim-lspconfig to be "data only".

The general strategy is that the default behavior should be reasonable, while `:help lsp` provides concrete examples of how to tweak things if you just can't live with, for example, "hints showing up in diagnostics".

> Did you read `:h vim.diagnostic`?

For posterity, I agree it would be useful to provide a code sample in this thread. E.g., a Lua handler that discards hints based on whether the symbol starts with an underscore, or by checking some other flag in the pyright response.

**Comment by bavalpey** [comment]
> No. That is exactly what we should not have to do; otherwise what's the point of having a protocol in the first place, whose selling point was that it solves the "N*M problem" of every editor having to worry about every language server?

I'm going to push back on this. Yes, some part of the neovim maintainers definitely do have to do this. As soon as Pyright support was added to the Neovim ecosystem, (as in, supported by an official extension that is part of the neovim organization), it became your responsibility.

I don't know if the "you"/"your" here should be the maintainers of neovim core, the maintaners of nvim-lspconfig, or some other maintainer.

What makes this worse is Pyright is literally the hello world example for the README of nvim's lspconfig.

**Comment by zeertzjq** [comment]
Since you are reading the README of nvim-lspconfig, you should notice this sentence at the very top of the file:
> These configs are best-effort and supported by the community.

**Comment by bavalpey** [comment]
> Since you are reading the README of nvim-lspconfig, you should have noticed this sentence at the very top of the file:
> 
> > These configs are best-effort and supported by the community.

Yeah, best effort and by the community. So when we post an issue to see if a fix would be welcome / possible / how to, and a maintainer tells us it's the wrong repo and doesn't answer questions asking which would be the right repo..

Makes for a great community doesn't it.

**Comment by justinmk** [comment]
> a maintainer tells us it's the wrong repo and doesn't answer questions asking which would be the right repo..

That particular user is no longer a maintainer. We are responding here, meanwhile.

**Comment by justinmk** [comment]
Regarding pyright, @mfussenegger makes a very clear point [here](https://github.com/microsoft/language-server-protocol/issues/2026#issuecomment-2366328648):

> Afaik eclipse.jdt.ls and luals also use `DiagnosticTag.Unnecessary` for actionable diagnostic. There are probably others too. Seems to me that pyright is the odd duck here.
> 
> I'd also question a bit why there'd need to be a diagnostic at all if something is legitimately/intentionally unused. What'd be the point over a `DiagnosticTag.Unused` over just not emitting any diagnostic? If it isn't actionable it would require lots of special handling on the client side - for what?
> 
> > there are scenarios where you end up with unused variables that are still very much necessary. For example, if you're implementing a method signature, you can end up defining parameters that are unused, but still must be be there in order to preserve the arity of the function.
> 
> This sounds a bit as a more general ambiguity problem. How is a server supposed to know if something is intentionally unused or not, without some additional hint from the person who wrote the code?
> 
> E.g. some languages allow to prefix intentionally unused variables with `_`.

**Comment by clason** [comment]
> E.g. some languages allow to prefix intentionally unused variables with _.

which was brought up with the pyright maintainer in the linked thread, who refused to consider this (for frankly no apparent reason).

But no point in dragging all this history up since a while after things cooled down, he relented and added [a setting to disable it](https://github.com/microsoft/pyright/issues/1118#issuecomment-1893295993):

> Pyright 1.1.347 includes a new language server setting called "pyright.disableTaggedHints". If you set this to true, pyright will not emit any "hint" diagnostics with tags.

> If you disable these hints but are still interested in seeing diagnostics for unreferenced symbols, you can enable reportUnusedImport, reportUnusedClass, reportUnusedFunction or reportUnusedVariable. And if you'd like to see diagnostics for deprecated classes or functions, you can enable reportDeprecated.

**Comment by justinmk** [comment]
> nvim-lspconfig, where this setting could be added or at least documented.

We certainly should do that. Would have saved a lot of time here to mention that initially. I'm not going to read 53 different discussions.

**Comment by lewis6991** [comment]
Instead of configuring anything I just do:

```python

def foo(arg):
    del arg # unused # removes diagnostic 

    ...
```

In python argument names have semantic meaning, so this seems like a good solution to me.

**Comment by clason** [comment]
> Would have saved a lot of time here to mention that initially. I'm not going to read 53 different discussions.

Excuse me for not subscribing to and memorizing 100+ comment chains on language server repositories; I have a hard enough time keeping up with my main responsibility here (treesitter). I only noticed this now when looking back over the thread to quote the maintainer's original refusal to add support for underscored arguments.

**Comment by justinmk** [comment]
> Excuse me for not subscribing to and memorizing 100+ comment chains

Excuse me for "dragging all this history" by linking to a succinct summary.

**Comment by bavalpey** [comment]
> Instead of configuring anything I just do:
> 
> ```python
> def foo(arg):
>     del arg # unused # removes diagnostic 
> 
>     ...
> ```
> 
> In python argument names have semantic meaning, so this seems like a good solution to me.

This doesn't work for lambdas, which is actually where I ran into this issue the most frequently.
