### ISSUE TITLE
`:help editorconfig` doesn't match behavior concerning filename

### ISSUE THREAD

**Issue by errael** [neovim/neovim#30461]
### Problem

`shiftwidth` unexpectedly changed.

### Steps to reproduce

The help says

> Nvim searches all parent directories of that file for ".editorconfig" files

but as seen in the following

```
$ nvim -V1 /junk/repo/neovim/neovim/runtime/lua/man.lua

:verbose set sw

shiftwidth=2                                                                            
      Last set from /junk/install/local/share/nvim/runtime/lua/editorconfig.lua line 121          
```
The file that changes shiftwidth does not match the name as specified in `:help`

### Expected behavior

`shiftwidth` should not be changed.

### Nvim version (nvim -v)

NVIM v0.11.0-dev (sept 21 source)

### Vim (not Nvim) behaves the same?

not in vim

### Operating system/version

ubuntu

### Terminal name/version

ubuntu

### $TERM environment variable

xterm-256color

### Installation

make install

**Comment by zeertzjq** [comment]
https://github.com/neovim/neovim/blob/master/.editorconfig

**Comment by errael** [comment]
@zeertzjq Isn't the message
```
Last set from /junk/install/local/share/nvim/runtime/lua/editorconfig.lua line 121 
```
a bug?

**Comment by zeertzjq** [comment]
No

**Comment by errael** [comment]
Got it, thanks. I conflated the script that finds/reads the `.editorconfig` with the `.editorconfig` itself.
