### ISSUE TITLE
winget nightly installer hash does not match

### ISSUE THREAD

**Issue by albertosantini** [neovim/neovim#30464]
### Problem

```
❯ winget install Neovim.Neovim.Nightly
Found Neovim Nightly [Neovim.Neovim.Nightly] Version 0.11.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.msi
  ██████████████████████████████  16.3 MB / 16.3 MB
Installer hash does not match.
```
Same for `winget install nvim-nightly`

### Steps to reproduce

winget install Neovim.Neovim.Nightly

### Expected behavior

neovim installed

The I followed the instructions https://github.com/microsoft/winget-cli/issues/3640#issuecomment-2083499441

```
One possible workaround is what is described [here](https://stackoverflow.com/a/76828240/4999991). In an elevated terminal run:

 winget settings --enable InstallerHashOverride
now in a normal (i.e., non-elevated) terminal run:

winget install <packageName> --ignore-security-hash
please consider that this workaround is insecure and unsafe!
```

If you think it is the correct solution, it would be better to add a line in installation steps for nightly channel.

### Nvim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal Preview 1.22.2362.0

### $TERM environment variable

xterm-256color

### Installation

winget install Neovim.Neovim.Nightly

**Comment by justinmk** [comment]
> The I followed the instructions [microsoft/winget-cli#3640 (comment)](https://github.com/microsoft/winget-cli/issues/3640#issuecomment-2083499441)

From that thread:

> Hash mismatches are common when a manifest uses a vanity URL and the package becomes updated, such as a new version. The fix here is usually to submit this new version to WinGet's public manifests, and possibly remove the old.

Seems like a general winget issue. 

I guess we could mention `--ignore-security-hash` in our install notes, and link to that discussion.

**Comment by dundargoc** [comment]
I thought our general stance was "nightly distro builds are not supported" partially to not end up constantly debugging every package manager like this.

**Comment by dundargoc** [comment]
> I guess we could mention `--ignore-security-hash` in our install notes, and link to that discussion.

Let's not, these types of "this is a REALLY BAD IDEA and YOU SHOULD NEVER EVER DO THIS, but..." type of advice annoy me to no end, because why are you even telling me if it's such a bad idea?

**Comment by albertosantini** [comment]
Closing, just a reference if someone else find the same glitch. :)
