### ISSUE TITLE
One more example of timoutlen breaking mappings

### ISSUE THREAD

**Issue by crazyminecuber** [neovim/neovim#30465]
### Problem

No way to “truly” disable built-in maps if you have enabled timout.

### Steps to reproduce

`nvim --clean`

`:nnoremap q: <nop>`

press `q:` quickly. Nothing happens as expeded

press `q` wait 2 seconed, press `:`. Now the default action of `q:` is executed, which opens the command-line window.

### Expected behavior

In this specific case, I would expect that nothing would happen and that the command-line window would not open.

The behavior here seems to be that built-in multi-key mappings, which do not have a defined prefix key action, (like q is not mapped to anything and waits for a second key to be pressed, before something is done.) will execute the built-in action, instead of the mapped action if timoutlen expires.

I personally cannot think of a single good reason why this would be expected/wanted behavior for multi-key built-in mappings.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-812+ge697c1b43

### Vim (not Nvim) behaves the same?

Yes, 9.1

### Operating system/version

NixOS 24.05

### Terminal name/version

kitty 0.34.1

### $TERM environment variable

xterm-kitty

### Installation

build from source, as well as NixOS package. Same issue.

**Comment by zeertzjq** [comment]
Why don't you just disable timeouts then?

**Comment by crazyminecuber** [comment]
Yes, that will probably be my workaround, but I do not think that the default behavior makes sense, which is why I reported it.

**Comment by zeertzjq** [comment]
Maybe, but the default behavior is easier to understand as it is the same for all mappings. The behavior you are suggesting requires different timeout behavior for different mappings, which is harder to understand.

**Comment by crazyminecuber** [comment]
I am not suggesting different timeout behavior for different key. I am suggesting that it should be impossible to trigger a built-in mapping if the user has manually overridden it, even if timeoutlen has expired. Because if the user has explicitly overridden the mapping, why would they want the built-in behavior to trigger?

My understanding of timeoutlen is that it is intended to trigger prefix-mappings if there exists a longer mapping. So I guess my suggestion is in the gray area when the prefix-mapping does not do a specific action (like a single q or d or y), but it requires additional keys to complete the mapping. In these cases, I am suggesting that the user specified action should be executed and not the built-in action as it currently works.

**Comment by zeertzjq** [comment]
Built-in commands are commands. They are not mappings.

**Comment by zeertzjq** [comment]
That'll require different timeout behavior for different mappings, because builtin commands are not mappings.
