### ISSUE TITLE
mail.vim regex for emoji's slows down navigation

### ISSUE THREAD

**Issue by GSI** [neovim/neovim#30498]
### Problem

Merely keeping `j` pressed pumps CPU use to 70% while scrolling in a text file when `:set syntax=mail`. The cursor will hang and do a long jump every couple of milliseconds.

https://github.com/neovim/neovim/blob/b7e3003106a4f080f0a9b60d5aaff053318778b4/runtime/syntax/mail.vim#L67

### Steps to reproduce

Have this line in mail.vim:

    syn match mailEmoji contains=@NoSpell "\%#=2\v[\U1f300-\U1f64f\U1f900-\U1f9ff]"

### Expected behavior

Reasonably low CPU usage; Cursor visits every line while `j` is pressed.

### Nvim version (nvim -v)

v0.10.1

### Vim (not Nvim) behaves the same?

unknown

### Operating system/version

Linux

### Terminal name/version

alacritty 0.13.2

### $TERM environment variable

screen-256color

### Installation

XBPS

**Comment by clason** [comment]
We don't maintain these files; please report them to the maintainer listed at the top of the file.
