### ISSUE TITLE
getmousepos() doesn't find non-focusable windows

### ISSUE THREAD

**Issue by errael** [neovim/neovim#30490]
### Problem

vim/neovim difference in `getmousepos()` for floating-windows/popup-windows
In `:help getmousepos`
- `vim`: If the mouse is over a popup window then that window is used.
- `neovim`: If the mouse is over a focusable floating window then that window is used.

I'm looking for a way to get a non-focusable non-hidden window under the mouse. I want to
fill in some of the missing capabilities of plenary.nvim's popup.lua. And popup can not be
focusable. I could go through a list of all windows, filtering as required, and if needed
convert mousepos from screen to floating window. But that seems like a lot of work
to replicate in lua code something that is already mostly in core neovim.

(I noticed that `CTRL-W_CTRL-W` will move to a `hidden` `focusable` window. Is that a bug?)

### Steps to reproduce

Can provide an executable test case if needed.

(https://github.com/neovim/neovim/commit/4e4b1b65903b973cb447b5a70413d0e0363c20f0)

### Expected behavior

Some way to get a non-focusable window from `getmousepos()`.

Is the default, "must be focusable", wrong for `getmousepos()`? Should/can it be changed?

If there is a way to have an option to `getmousepos()`, like ANY_WINDOW, in the following
code, that might take care of this problem. Could get there with optional arg to
getmousepos(). Probably `getmousepos([{dict of options}])`. I'm assuming that
`get_win_by_grid_handle()`/`FOR_ALL_WINDOWS_IN_TAB` is sorted by `zindex`. Also, don't
want a "hidden" window, not sure how that works with FOR_ALL_WINDOWS_IN_TAB.

```
static win_T *mouse_find_grid_win(int *gridp, int *rowp, int *colp)
{
  ...
    if (wp && wp->w_grid_alloc.chars
        && (ANY_WINDOW || !(wp->w_floating && !wp->w_config.focusable))) {
      *rowp = MIN(*rowp - wp->w_grid.row_offset, wp->w_grid.rows - 1);
      *colp = MIN(*colp - wp->w_grid.col_offset, wp->w_grid.cols - 1);
      return wp;
    }
```
or maybe it's something more like
```
&& !(wp->w_floating && (!(ANY_FOCUS || wp->w_config.focusable)))) {
```

Something like `getmousepos({focusable: any, hide: false})` for my case.

I came across nvim__inspect_cell, but it doesn't return the win_id (and ignoring the fact
that it's hidden somewhere in lua metadata).

BTW. I wanted to find the dispatch code to see how f_whatever is called. Opened termdebug
on nvim, put a breakpoint at f_getmousepos, run... But the forking got in the way. Doing
"set follow-fork-mode child" but no luck. Saw some stuff about "dap", but didn't see
anyway to hook up gdb to nvim with dap.

When I found the binary in build, and looked more carefully in there, I came across
"include/*.h.generated.h" and ".../auto/funcs.generated.h", now to see where those came
from...

### Nvim version (nvim -v)

v0.11.0-dev commit db4e4b1b65903b

### Vim (not Nvim) behaves the same?

No, vim 9.1.695 (and for a while)

### Operating system/version

ubuntu

### Terminal name/version

gnome

### $TERM environment variable

xterm-256color

### Installation

make install

**Comment by zeertzjq** [comment]
I do think the default behavior makes sense, as one may want `getmousepos()` to get where the cursor actually moves to on a mouse click.

> I'm assuming that `get_win_by_grid_handle()`/`FOR_ALL_WINDOWS_IN_TAB` is sorted by `zindex`.

That's actually not the case. They are sorted in reverse order of creation (i.e. newest floating windows first).

However, you are checking the wrong branch here, as the branch used in your case is the `*gridp == 0` branch, and `ui_comp_mouse_focus()` is sorted by `zindex`:
```c
  for (ssize_t i = (ssize_t)kv_size(layers) - 1; i > 0; i--) {
    ScreenGrid *grid = kv_A(layers, i);
    if (grid->focusable
        && row >= grid->comp_row && row < grid->comp_row + grid->rows
        && col >= grid->comp_col && col < grid->comp_col + grid->cols) {
      return grid;
    }
  }
```

**Comment by errael** [comment]
> I do think the default behavior makes sense, as one may want `getmousepos()` to get where the cursor actually moves to on a mouse click.


I'm not familiar enough with `neovim`, but I thought that usually the builtin function were similar to `vim`. And it's also possible the tha `neovim` behavior pre-dates the addition of `vim`'s popup stuff. I forget to mention that this might better be considered a feature request if the current behavior is fully intended. Thanks for changing it.

"one may want ... actually move to on a click" and one may want to know what window is displayed under the click. But only one or the other is not the main point of this issue, unless `neovim` said, yes that's a bug:). The idea is to have a way to find either.

The main issue is whether or not something like `getmousepos([{dict_of_options}])` would be accepted, assuming it met the "standards". `neovim` is completely new to me except for the parts that aren't. Don't want to spend much time working on something if there's no chance...

An alternate approach is a vim function that takes screen x/y and some options and return info similar to getmousepos().

Can anyone point me to some links about debuggering nvim. I had no luck with termdebug. I have seen that there's a log file, but no other reference. I see the lua vim.log.levels; is that related?


> > I'm assuming that `get_win_by_grid_handle()`/`FOR_ALL_WINDOWS_IN_TAB` is sorted by `zindex`.
> 
> That's actually not the case. They are sorted in reverse order of creation (i.e. newest floating windows first).

Thanks for the clarification. Ah `ScreenGrid` I saw some stuff about grids. Is `ScreenGrid` and "cell" directly related? I don't get the `multigrid` and `linegrid` and such. (so much new stuff).

> However, you are checking the wrong branch here, as the branch used in your case is the `*gridp == 0` branch, and `ui_comp_mouse_focus()` is sorted by `zindex`:

Cool. I'll take a look. `kv_A(layers, i)` that's interesting.

> ```c
>   for (ssize_t i = (ssize_t)kv_size(layers) - 1; i > 0; i--) {
>     ScreenGrid *grid = kv_A(layers, i);
>     if (grid->focusable
>         && row >= grid->comp_row && row < grid->comp_row + grid->rows
>         && col >= grid->comp_col && col < grid->comp_col + grid->cols) {
>       return grid;
>     }
>   }
> ```

**Comment by justinmk** [comment]
> but I thought that usually the builtin function were similar to `vim`

Yes, but nvim floating windows are a totally different system than vim "popup" windows (which are more limited but sometimes more [DWIM](https://en.wikipedia.org/wiki/DWIM) as well, though we are open to improving DWIM where possible).

**Comment by errael** [comment]
> > but I thought that usually the builtin function were similar to `vim`
> 
> Yes, but nvim floating windows are a totally different system than vim "popup" windows

I've noticed that :) Doesn't explain why visible non-focusable windows are ignored.

> (which are more limited but sometimes more [DWIM](https://en.wikipedia.org/wiki/DWIM) as well, though we are open to improving DWIM where possible).

Assuming the default for `getmousepos()` can't be changed, the first thing that comes to mind is extending it with an optional arg. Possibilities include
1. `getmousepos([boolean])`   - two possible behaviors
2. `getmousepos([enum])`      - "n" behaviors, e.g. 4 based on hide/focusable
3. `getmousepos([dict])`      - dict based on `nvim_open_win`'s `{config}`

A new function could be introduced which might return a list of window position info, matching some criteria specified by dict, optionally orderd by `zindex`, e.g. all the windows under screen x/y or intersecting a bounding box. Like (3) on steroids.

My preference is 3, and the initial implementation only supports `hide`/`focusable` dict keys. If a key is not present, then `any` value is OK. Picks the highest zindex that matches criteria. Easily extended.

If no window matches the criteria could set winrow/wincol to 0, should winid be 0 as well? Could add a new key "found"; only present if dict is used or always present (usual true) and set to false when click in command line (currently indicated by "the others are zero"). Or could have values "window", "command-line", "no-match" (in which case the key could be "result" instead of "found").

**Example**
For `popup` compatibility use `getmousepos({hide: false})` and ignore if window is not a popup window. If add `focusability: false` then if the popup is obscured by a focusable window the popup would be returned even if it isn't visible. (Could add a `{visible: bool}` key/value which is probably better presented as `{hide: false, zindex: "top"}`)

**Comment by bfredl** [comment]
> Is the default, "must be focusable", wrong for getmousepos()? Should/can it be changed?

The default is correct. "focusable" actually means "focusable" which includes both keyboard and mouse. fine as opt-in via a flag.

**Comment by zeertzjq** [comment]
An alternative is to add a another flag to floating windows that makes a non-focusable floating window "clickable". Clicking on such a floating window won't move cursor there, but won't move cursor in the window below either, and `getmousepos()` returns the click position in the floating window, so that a scripts can implement custom click behavior. That's also more similar to how clicks on popup windows are handled in Vim.

**Comment by errael** [comment]
> An alternative is to add a another flag to floating windows that makes a non-focusable floating window "clickable". Clicking on such a floating window won't move cursor there, but won't move cursor in the window below either, and `getmousepos()` returns the click position in the floating window, so that a script can implement custom click behavior. That's also more similar to how clicks on popup windows are handled in Vim.

That's exactly the conclusion I came to when looking at another issue relating to popup/mouse. I'm about to file an enhancement request with that. I'll go ahead and open it. and things can be closed as needed.

**Comment by errael** [comment]
Opened #30504

**Comment by errael** [comment]
> add a another flag to floating windows that makes a non-focusable floating window "clickable"

Just to note. There is not necessarily a "click" involved when doing `getmousepos()` probably best considered independent events.

**Comment by errael** [comment]
Closing. With #30844, `getmousepos()` works with floating windows that have `mouse = true`
