### ISSUE TITLE
mouse event for buffer in non-focusable window

### ISSUE THREAD

**Issue by errael** [neovim/neovim#30504]
### Problem

I'm looking at implementing `vim`'s popup API in `lua` (actually adding missing pieces to `plenary.nvim/popup`). #30490 is targeted to the same goal and shares the problem with `focusable`/mouse-events. This issue is specifically about how to implement `close = click`.

The idea is to do something like
```
vim.keymap.set({'n', 'i'}, '<LeftRelease>', function()
    mouse_click("buffer")
end, {buffer = popup_buffer})
```
The use of `{buffer = popup_buffer}` is important to avoid interfering with other uses of `<LeftRelease>`. So the idea of examining all clicks in parent window is a non-starter.

One idea is to add a key to `nvim_open_win`, `mousable` or`mouse_enable` or `mouseevent` or ..., when true mouse events are delivered to/through the window. (`mouseevent` is similarly named to `mousemoveevent`). A simple way to define this flag's semantics are `mouseevent` defaults to the same value as `focusable`; `mouseevent` is used, not `focusable`, for deciding on whether or not to deliver mouse events. It interesting that with this, #30490 could be finessed without any changes to the `getmousepos()` API.

You can play with the interaction of `focusable` and click using this code.

```lua
local popup_wid

local function mouse_click(tag)
    local mp = vim.fn.getmousepos()
    vim.print(string.format("CLICK %s: line %d, col %d", tag, mp.screenrow, mp.screencol))
end

local xpos = 30
local ypos = 6
local function Pop1Any()
    local bnr = vim.api.nvim_create_buf(false, true)
    assert(bnr, "Failed to create buffer")
    vim.api.nvim_buf_set_lines(bnr, 0, -1, true, {'simple', '=' .. tostring(ypos) .. '='})

    vim.api.nvim_set_option_value("bufhidden", "wipe", {buf = bnr})
    vim.api.nvim_set_option_value("modifiable", true, {buf = bnr})
    popup_wid = vim.api.nvim_open_win(bnr, false, {
        relative = "editor",
        style = "minimal",
        width = 10,
        height = 2,
        focusable = false, -- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        col = xpos,
        row = ypos,
    })
    xpos = xpos + 3
    ypos = ypos + 3
    vim.keymap.set({'n', 'i'}, '<LeftRelease>', function() mouse_click("buffer") end, {buffer = bnr})
end

Pop1Any()

vim.keymap.set({'n', 'i'}, '<LeftRelease>', function() mouse_click("global") end)
```

### Expected behavior

Some way to get this to work.

**Comment by errael** [comment]
(So that's what needs-owner means) 

I am interested in working on this, and #30490. I'm assuming it's a relatively small PR, but involving code, spec, doc is a good introduction to `neovim` development. @justinmk  Other than simply stating this interest, is there a process ...

The idea is to introduce a window config flag [`mousable`](https://wiktionary.org/wiki/mouseable) and use it for handling mouse events and in `getmousepos()`. Are there other places where it's use would be applicable? The precise spec relates to some discussion in in #30507 and specifically from https://github.com/neovim/neovim/pull/30507#issuecomment-2374765534

> In nvim_win_open if mousable is not explicitly set, it should be set to the the value of focusable. 
> If focusable and/or hide are changed, and mousable is not explicitly changed as well, what should happen?

**Comment by zeertzjq** [comment]
I can implement it, but the interface still needs some decision. The `mousable` name is strange. I think `mouseevent` is a better name. The field may also be simple named `mouse`.

In addition, the buffer-local mapping example may not work even if `getmousepos()` works for the floating window, as mappings are applied before mouse handling and use buffer-local mappings from the current buffer at that time.

Instead, how about making the field also also accept a callback that
- handles any mouse events (click, drag, move, scroll) on that window (unlike 'statusline' callbacks that only handle clicks)
- can tell Nvim how to proceed with the mouse event via the return value (e.g. `nil` for no more handling, `false` to pass it to the next window in zindex order, `true` to use default handling in the window)

Such a flag may even be applicable to non-floating windows.

**Comment by errael** [comment]
> I can implement it, but the interface still needs some decision. The `mousable` name is strange. I think `mouseevent` is a better name. The field may also be simple named `mouse`.

I like `mouseevent`, especially if the field accepts a callback. `mousable`, an alternate spelling of `mouseable` is like `focusable`. I looked up `mouseable` and saw "Capable of being navigated, clicked, etc. using a mouse"...; but, as you say, the name is strange (probably part of its appeal to me).

> In addition, the buffer-local mapping example won't work even if `getmousepos()` works for the floating window, as mappings are applied before mouse handling and use buffer-local mappings from the current buffer at that time.

I don't entirely understand this comment. The code in the OP works when `focusable` is true. But doesn't matter when using the following approach of asking the window what it wants to do.

> Instead, how about making the field also also accept a callback that
> 
>     * handles any mouse events (click, drag, move, scroll) on that window (unlike 'statusline' callbacks that only handle clicks)
> 
>     * can tell Nvim how to proceed with the mouse event via the return value (e.g. `nil` for no more handling, `false` to pass it to the next window in zindex order, `true` to use default handling in the window)

Works for me. Interestingly, in the callback could move the focus to a non-focusable window. I suppose there's no way for the callback to get the state of any keys, like Shift/Ctrl/Alt.

Don't see how this has any applicability to `getmousepos()`. Unless the callback might be invoked with something like `getmouseposevent` and return `true`; or return "use-this-window" if `true` would mean skip the window.

> Such a field may even be applicable to non-floating windows.

**Comment by errael** [comment]
>  * can tell Nvim how to proceed with the mouse event via the return value (e.g. `nil` for no more handling, 
> `false` to pass it to the next window in zindex order, `true` to use default handling in the window)

Does the "next window in zindex order" includes hidden windows? (I'm not asking/hoping that it does)

**Comment by zeertzjq** [comment]
> > In addition, the buffer-local mapping example won't work even if `getmousepos()` works for the floating window, as mappings are applied before mouse handling and use buffer-local mappings from the current buffer at that time.
> 
> I don't entirely understand this comment. The code in the OP works when `focusable` is true.

Ah, for that to work, it will require the window to be focusable via a mouse click (i.e. mouse click switches to the window). That may actually not require an extra flag since it's still about focus, but can instead be enabled by allowing `focusable` to be a string (e.g. `mouse`).

**Comment by errael** [comment]
> > > In addition, the buffer-local mapping example won't work even if `getmousepos()` works for the floating window, as mappings are applied before mouse handling and use buffer-local mappings from the current buffer at that time.
> > 
> > 
> > I don't entirely understand this comment. The code in the OP works when `focusable` is true.
> 
> Ah, for that to work, it will require the window to be focusable via a mouse click (i.e. mouse click switches to the window). That may actually not require an extra flag since it's still about focus, but can instead be enabled by allowing `focusable` to be a string (say `mouse`), which is much simpler.
> 
> However, if you don't actually want the cursor to be moved to the window, with this approach you will need to move cursor back manually on `<LeftRelase>`, which is a bit complicated as `<LeftMouse>` and `<LeftRelease>` are two separate keys and anything can happen in between.

With the window mouse callback. I have no need for this. Just curious to understand what is going on.

**Comment by errael** [comment]
The idea of having the controlling logic embedded in the window, with a mouse callback, avoids the problems with interactions as seen between `hide` and `focusable` and trying to handle it generally in the core.

> Instead, how about making the field **also** accept a callback that

"Also"? What might be other possibilities.

Oh, maybe bool value is a shorthand for something like: `function() return bool end`

> * handles any mouse events (click, drag, move, scroll) on that window
>    (unlike 'statusline' callbacks that only handle clicks)
> 
> * can tell Nvim how to proceed with the mouse event via the return value
>    `nil` for no more handling, 
>    `false` to pass it to the next window in zindex order, 
>    `true` to use default handling in the window

Wondering how this might work when there's multiple windows under the cursor.

Windows are checked in `zindex` order. Are hidden included? If there's no `mouseevent` field is that the same as returning `false`, i.e. check the next window?

I guess most callbacks would start with `if this_win.hide then return false end`.

Consider the case where a popup, `{focusable=false,hide=false,}`, wants to close if it is clicked.

If there's a popup which is **partially** obscured by one or more normal windows `{focusable=true,hide=false,}` which have callback that returns `false`. The popup does not want to handle the click, unless the click is on a visible position in the popup. The question is `this_win:is_obscured_xy(x_mouse, y_mouse)`

A window's mouse callback might want to know (maybe more, maybe less)
- this_win
- is_obscured_xy(x, y)
- under_xy_list_win(), this_win_index
- is_obscured_fully()

**Comment by zeertzjq** [comment]
Some part of the suggestions above may be infeasible to implement (e.g. check the next window in zindex order). But anyway, I don't think zindex order should include hidden windows, and it's kind of hard to include hidden windows there.

**Comment by errael** [comment]
> Some part of the suggestions above may be infeasible to implement when using a callback (e.g. checking the next window in zindex order after checking the callback's return value),

I don't know the technical issues. I can imagine that if control is passed to a callback, then when the callback returns it is difficult, if not impossible, to know how the callback may have changed the state.

> and in that case a boolean value may be easier to implement.

IIUC, this won't handle the goal of this enhancement request as you say in https://github.com/neovim/neovim/issues/30504#issuecomment-2375424832. A key point for using a buffer mapping is that it doesn't interfere with other mappings and/or normal non-popup operation; see the end of this post for some discussion.

Something like `mouseevent = { "click" = callback, }` could work; or the simpler `mouseevent = callback`. The key point is that no further `nvim` mouse event processing after the callback returns. Specifying `mouseevent` means the event is consumed.

This is workable for the popup use case `{close = "click"}`. It seems like it would also work for the cases of dragging a popup (assuming the mouse doesn't go outside of the popup while dragging).

It's interesting to note that auto commands, unlike mappings, allow multiple listeners; but no way to consume the event.

> But anyway, I don't think mouse click position checking should include hidden windows,

Makes sense to me.

> and it's kind of hard to include hidden windows there.

-----

**interference example**

The use case I'm looking at, providing vim's popup API for `neovim`, doesn't want to interfere with normal usage.


For example here's a case that is not about catching mouse events for a specific buffer, but shows the issues involved. Consider popup's `mousemoved = "any"` is "close the popup if the cursor moved". I've got an implementation that
1. save the current state of `'mousemoveevent'` and `<MouseMove>` mapping.
2. set up a `<MouseMove>` mapping that closes the popup
3. when the popup closes for any reason, not just mouse move, restore the mapping.

This seems OK because only one mouse event is stolen before the mapping is restored. But other `mousemoved` conditions require continuous monitoring which is undesirable.

**Comment by errael** [comment]
Oops. Just noticed #30542; previous comment out of date before it was written. Still might find the "interference example" of interest.

**Comment by errael** [comment]
With the following diff on top of this PR the popup code has `drag`, `dragall`, `close="click"`, `close="button"` implemented; in addition to almost all of `vim`'s popup functions. See https://github.com/errael/plenary.nvim/blob/PopupDrag/POPUP.md for a summary of what's implemented. `Filter` is done, but needs support, see #30741; also needs more tests.

The diff insures that drag and release mouse events are delivered to the  same window where the click occurred. It only handles the left button. Its structured so it can be easily extended to handle all the buttons. _I can do that if wanted; LMK._

FYI, I checked interactions between multiple button actions during a drag. `Neovim` looks clean; I may not agree with the choices, but they make sense. Interestingly, `vim` is buggy. Here's a summary of behavior

**neovim**

Left drag is prioritized; a left drag interrupts a right drag.

- given: left-click, drag, right-click, drag, right-release, drag, left-release
  `<LeftMouse <LeftDrag ... <RightMouse <LeftDrag ... <RightRelease <LeftDrag ... <LeftRelease`

- given: right-click, drag, left-click, drag, left-release, drag, right-release
  `<RightMouse <RightDrag ... <LeftMouse <LeftDrag ... <LeftRelease <RightDrag ... <RightRelease`

**vim**

No drag priority, looses in progress drag after a release, missing release, unexpected mouse move events (and &mousemoveevent==false)

- given: left-click, drag, right-click, drag, right-release, drag, left-release
  `<LeftMouse <LeftDrag ... <RightMouse <RightDrag ... <RightRelease <MouseMove ...`

- given: right-click, drag, left-click, drag, left-release, drag, right-release
  `<RightMouse <RightDrag ... <LeftMouse <LeftDrag ... <LeftRelease <MouseMove ...`


```diff
diff --git a/src/nvim/mouse.c b/src/nvim/mouse.c
--- a/src/nvim/mouse.c
+++ b/src/nvim/mouse.c
@@ -225,27 +225,60 @@
   got_click = false;
 }
 
+static struct mouse_click_op {
+    handle_T owner;
+    int owned_click;
+    int current_click;
+} left_click;
+
+// Return the window that has a drag related operation in progress.
+static win_T *drag_mouse(int c)
+{
+  if (c == K_LEFTDRAG || c == K_LEFTRELEASE) {
+    Error err = ERROR_INIT;
+    win_T *wp = find_window_by_handle(left_click.owner, &err);
+    if (!ERROR_SET(&err) && wp != NULL && left_click.owned_click == left_click.current_click) {
+      return wp;
+    }
+  }
+  return NULL;
+}
+
 /// When clicking on a window with a mouse callback, invoke it.
 ///
 /// @return  whether to proceeded with mouse handling.
-static bool invoke_mouse_cb(void)
+static bool invoke_mouse_cb(int c)
 {
   int grid = mouse_grid;
   int row = mouse_row;
   int col = mouse_col;
 
+  if (c == K_LEFTMOUSE) {
+      left_click.current_click++;
+  }
+
   if (row < 0 || col < 0) {
     return true;
   }
 
-  win_T *wp = mouse_find_win(&grid, &row, &col);
+  win_T *wp;
+  if ((wp = drag_mouse(c)) == NULL) {
+    wp = mouse_find_win(&grid, &row, &col);
+    if (wp != NULL && c == K_LEFTMOUSE) {
+      left_click.owner = wp->handle;
+      left_click.owned_click = left_click.current_click;
+    }
+  }
+
   if (wp == NULL || wp->w_config.mouse != kWinMouseCallback) {
     return true;
   }
+  DLOG("c = %4x %s, click: %d, winid %d", c&0xffff, get_special_key_name(c, 0),
+       left_click.current_click, wp->handle);
 
   Error err = ERROR_INIT;
-  Object res = nlua_call_ref(wp->w_config.mouse_cb, NULL, (Array)ARRAY_DICT_INIT,
-                             kRetNilBool, NULL, &err);
+  Object res = nlua_call_ref(wp->w_config.mouse_cb, get_special_key_name(c, 0),
+                             (Array)ARRAY_DICT_INIT, kRetNilBool, NULL, &err);
   bool retval = LUARET_TRUTHY(res);
   if (ERROR_SET(&err)) {
     semsg_multiline("E5108: %s", err.msg);
@@ -403,7 +436,7 @@
     break;
   }
 
-  if (!invoke_mouse_cb()) {
+  if (!invoke_mouse_cb(c)) {
     return false;
   }
 
@@ -1099,7 +1132,7 @@
 /// of the MSCR_ values.
 void ins_mousescroll(int dir)
 {
-  if (!invoke_mouse_cb()) {
+  if (!invoke_mouse_cb(0)) {
     return;
   }
 
@@ -1612,7 +1645,7 @@
 /// "cap->arg", which is one of the MSCR_ values.
 void nv_mousescroll(cmdarg_T *cap)
 {
-  if (!invoke_mouse_cb()) {
+  if (!invoke_mouse_cb(0)) {
     return;
   }
 
```

**Comment by zeertzjq** [comment]
> Left drag is prioritized; a left drag interrupts a right drag.

I don't think Nvim is responsible for deciding the priority here. This priority is decided by the terminal emulator. Try running `printf '\x1b[?1002h\x1b[?1006h'; cat; printf '\x1b[?1002l\x1b[?1006l'` in a terminal emulator, and comparing the escape sequences shown during different kinds of drags.

**Comment by errael** [comment]
> > Left drag is prioritized; a left drag interrupts a right drag.
> 
> I don't think Nvim is responsible for deciding the priority here. This priority is decided by the terminal emulator. ...

I took a look at what comes through to quell any doubts that the scheme on directing events to a window's mouse handler wouldn't run into problems. I don't think the behavior is wrong.

BTW, that sequence is pretty cool. A preliminary look indicates those events are essentially passed through. For example, a right button drag is interrupted by left button drag and then the right drag resumes.

**Comment by errael** [comment]
Closing. With #30844, `getmousepos()` works with floating windows that have `mouse = true`.
