### ISSUE TITLE
[RFC] runtime/doc/nvim-faq.txt

### ISSUE THREAD

**Issue by mhinz** [neovim/neovim#3051]
It's time for a FAQ. On gitter and IRC people ask the same questions over and over.

I suggest introducing `runtime/doc/nvim-faq.txt` (and maybe try keeping it synchronized with a similar wiki page).

The FAQ should be about the _now_. I think of it as a means to get new users quickly up to terms. It would include things like..

   - Why does this Ruby plugin not work?
   - Why doesn't `<c-h>` work?
   - How to get Neovim to resize my window? (#3048)
   - How do you manage your plugins?

Your opinions? If you agree, I'd whip up a first draft.

(BTW, on IRC @kevinburke suggested something similar today.)

**Comment by fmoralesc** [comment]
I think it's a great idea. 

Other questions I've seen often:

* How do I bootstrap my nvim configuration? Any suggestions to make neovim usable for `$LANGUAGE`?
* Why does neovim throw an error when I set `$UNAVAILABLE OPTION`? 
* Why is this option's default different now? (If only because I usually read that one as "Why does @fmoralesc hate kittens?")
* How do I leave terminal mode?
* Why don't the colorschemes work, and how can I fix it?

**Comment by fmoralesc** [comment]
> It's time for a FAQ.

This made me think, do we need an `asap` milestone? This is only half-tongue-in-cheek, I imagine it would be for  breaking bugs also. \cc @justinmk

**Comment by fwalch** [comment]
Also see https://github.com/neovim/neovim/wiki/FAQ

**Comment by mhinz** [comment]
Yup, that's the wiki page I thought of. And it must include "Who is that marvim guy on IRC?" ;-)

**Comment by fmoralesc** [comment]
> "Who is that marvim guy on IRC?"

Yeah, what's up with that guy? So nosy!

**Comment by Pyrohh** [comment]
> I suggest introducing runtime/doc/nvim-faq.txt (and maybe try keeping it synchronized with a similar wiki page).

In the past this hasn't worked out great, I think, and has been very tedious (for me) to synchronize. I think it'd be better to just have it in the built in docs.

**Comment by kevinburke** [comment]
I was surprised to see as a user new to Neovim (but a long time vim user) that there wasn't a document laying out how to get up and running with Neovim. This seems like a pretty common use case. I ended up deciding to come back and try again in 6-12 months.

**Comment by kevinburke** [comment]
Might be fine as a Vim help doc, as long as I can google "how to port from vim to neovim" and get that document as the top result.

Vim help docs also don't have great formatting on Github, unfortunately.

**Comment by mhinz** [comment]
So, we agree that it would be useful, but not on the format, I guess.

I guess writing a `help syntax` -> `markdown` transpiler would be simple enough, but if people fear too many additional commits because of `runtime/doc/nvim-faq.txt`, I'd be okay with wiki-only.

**Comment by justinmk** [comment]
> The FAQ should be about the now. 

That's what wikis are for.

> This made me think, do we need an asap milestone?

How's it different than the nearest upcoming milestone? Meta-milestones are meant to have issues moved to actual, achievable milestones. Meta-milestones cannot actually be "achieved", so their targets are always "after the nearest milestone".

**Comment by fmoralesc** [comment]
Agreed. I was thinking of things that come up we must resolve before the
next milestone without them having any reference to the goals set for that
milestone (like the segfaults people are having these days) I used the
"milestone" term only because this idea is so time-bound, a tag would have
worked just the same.

**Comment by mhinz** [comment]
Okay, https://github.com/neovim/neovim/wiki/FAQ it is.

**Comment by fmoralesc** [comment]
I just went ahead and did some changes to that page.

**Comment by mhinz** [comment]
@fmoralesc  :+1:

So putting it in a nutshell: always when you think that a question came up often enough or that a certain change will break stuff for a lot of users for a while.. please edit  https://github.com/neovim/neovim/wiki/FAQ

Thanks!

**Comment by Pyrohh** [comment]
Speaking of all this troubleshooting stuff, someone should take a look at https://github.com/neovim/neovim.github.io/pull/103.
