### ISSUE TITLE
Multithreaded remote plugins throws errors

### ISSUE THREAD

**Issue by critiqjo** [neovim/neovim#3052]
Error: `E475: Invalid argument: Channel doesn't exist`
Steps to reproduce:
* Register [critiqjo/rtest.nvim](https://github.com/critiqjo/rtest.nvim) as a remote plugin
* Execute `:RTest hello` -- will correctly echo `test: hello`.
* Execute `:RTest hello` again -- will show the above error.

More details:
* The plugin has a separate thread running, which calls `echo` when something is pushed to `in_queue`.
* There is a script called `auto.sh` which runs without any error. This script starts Neovim and spawns `auto.py` in a terminal inside. `auto.py` connects to the parent Neovim instance, creates an `RTInterface` object (the plugin), and calls `_test` function, the very same fuction invoked by `:RTest`, multiple times. No errors are reported.
* The plugin code is less than 50 LoC.
* If the last line of `__init.py__` is changed as [specified in the file](https://github.com/critiqjo/rtest.nvim/blob/master/rplugin/python/rtest/__init__.py#L18), the error disappears, but the echo works only the first time. Further, Neovim hangs on exit due to registering `au VimLeavePre * call RTExit()`.
* Resolution of this is crucial to make [lldb.nvim](https://github.com/critiqjo/lldb.nvim/tree/async-dev) truly asynchronous.

**Comment by fdinoff** [comment]
```python
2015-07-19 12:43:40,228 [WARNING @ async_session.py:_on_message:69] 18544 - Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/async_session.py", line 66, in _on_message
    self._handlers.get(msg[0], self._on_invalid_message)(msg)
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/async_session.py", line 87, in _on_response
    self._pending_requests.pop(msg[1])(msg[2], msg[3])
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 133, in response_cb
    gr.switch(err, rv)
error: cannot switch to a different thread
```

I get this in the log file when I run your application. So you have a bug in the python code and your plugin dies.

The log file is generated when you set the environment variable `NVIM_PYTHON_LOG_FILE` (example `NVIM_PYTHON_LOG_FILE=tmp nvim` and is located at `$NVIM_PYTHON_LOG_FILE_${pid of nvim}`

**Comment by critiqjo** [comment]
Thanks @fdinoff . So, how do I resolve this?
And should I move this issue to [neovim/python-client](https://github.com/neovim/python-client) repo?

**Comment by fdinoff** [comment]
Yeah, It should probably be moved to the neovim/python-client.

**Comment by bfredl** [comment]
Yes this is python-client issue. the nvim python API isn't threadsafe, but there is `nvim.session.threadsafe_call` that takes a lambda and executes in on main thread, so something like

    vim = self.vifx.vim
    vim.session.threadsafe_call(lambda: vim.command('echo "test: %s"' % args))

**Comment by critiqjo** [comment]
@bfredl Thank you so much. That solves the issue for now. I'll try this in the debugger project and see how it goes... Closing...
