### ISSUE TITLE
Dot repeat breaks macros with search

### ISSUE THREAD

**Issue by AdelSehic** [neovim/neovim#30524]
### Problem

Using a macro which has any kind of searching simply does not work with neovim. Calling the macro manually (@q) yields the correct result - find next instance and delete, but pressing dot repeat on the same macro after that deletes in place instead of moving. It's extremely frustrating.

### Steps to reproduce

To reproduce it have a file which you need to search through to make modifications, I needed to delete <th> elements from html file whose classes started with 0R so I did the following:
> gg
> qq
> /0R
> d2j
> q
> @q (goes to next iteration of th and removes it)
> . (does not move, instead deleted 3 lines in place)

### Expected behavior

Dot repeat needs to have the same result as @q

### Nvim version (nvim -v)

NVIM v0.10.2-dev-49+ga3f9bd7f7

### Vim (not Nvim) behaves the same?

No, vim executes the dotrepeat on macros perfectly, I ended up editing the file in Vim

### Operating system/version

Ubuntu 24.04

### Terminal name/version

foot version: 1.16.2 +pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Installation

build from repo

**Comment by zeertzjq** [comment]
Please provide the exact steps to reproduce this without plugins.

**Comment by AdelSehic** [comment]
> Please provide the exact steps to reproduce this (including the exact content of the file you edited) without plugins.

I realized that this is an issue on my part. Learned that macros are supposed to be repeated with @@ and not dot repeat :)

Sorry for useless issue, will close it.
