### ISSUE TITLE
Inconsistent Commenting Behavior for Markdown Files

### ISSUE THREAD

**Issue by yuukibarns** [neovim/neovim#30522]
### Problem

When opening a Markdown file in Neovim and attempting to comment a line using the `gc` command, the commenting behavior appears to be inconsistent and changeable. Specifically, the comment format alternates between the expected HTML comment (`<!--%s-->`) and a hash-style comment (`# %s`), even though the `commentstring` is consistently set to the default `<!--%s-->`.

https://github.com/user-attachments/assets/af3a3d65-f8cb-4aaa-8a96-145fe7f1061a

Here is my minimal configuration:
```lua
-- nvim-treesitter
local path = "~/nvim-treesitter"
vim.opt.rtp:prepend(path)

require("nvim-treesitter.configs").setup({
	modules = {},
	sync_install = false,
	ignore_install = {},
	auto_install = true,
	ensure_installed = {
		"markdown",
		"markdown_inline",
	},
	highlight = { enable = true },
})
```
`nvim-treesitter` is a must to reproduce the problem.

### Steps to reproduce

1. Open a Markdown file in Neovim.
2. Type `gc` to comment a line, for example:
   ```markdown
   This is a test
   ```
3. Observe that the line is initially commented correctly as:
   ```markdown
   <!--This is a test-->
   ```
4. Quit Neovim and reopen the file.
5. Repeat the `gc` command on the same line.
6. Notice that the line is now commented as:
   ```markdown
   # This is a test
   ```
7. Repeat steps 4-6 multiple times, and observe that the commenting method alternates randomly between the two formats.

### Expected behavior

The line should always be commented using the `commentstring` specified in Neovim, which is `<!--%s-->` for Markdown files. Therefore, the line should consistently be commented as:
```markdown
<!--This is a test-->
```

### Nvim version (nvim -v)

NVIM v0.10.1

### Vim (not Nvim) behaves the same?

Haven't tried yet.

### Operating system/version

Linux mint

### Terminal name/version

Alacritty

### $TERM environment variable

xterm-256color

### Installation

From repository

**Comment by clason** [comment]
Can't reproduce. Please remove nvim-treesitter from the reproduction since the markdown parsers are bundled with Neovim, so a simple `vim.treesitter.start()` should suffice.
