### ISSUE TITLE
signcolumn is not updated immediately after split

### ISSUE THREAD

**Issue by boltlessengineer** [neovim/neovim#30547]
### Problem

> reproduce steps might be more understandable

I was going to get a full gutter width by `vim.fn.getwininfo(win)[1].textoff`.

But even if I set `number signcolumn=yes`, the value of `textoff right after the `:vsplit` is `4` and not `6`.

I can see it is 6 because of signcolumn width and when I manually retrieve the `textoff` value from command line, it says it is `6`.
But neovim says it is `4` right after the `WinEnter` event.

> [!NOTE]
> this doesn't happen from vim

### Steps to reproduce

**repro.lua**:
```lua
-- to show 'number' option is working
vim.o.number = true
vim.o.signcolumn = "yes"
vim.cmd.wincmd("v")
local infos = vim.fn.getwininfo()
-- new window
vim.print(infos[1].winid, infos[1].textoff)
-- original window
vim.print(infos[2].winid, infos[2].textoff)
```

1. `nvim --clean -u repro.lua`
2. the output is like this:
    ```
    1001
    4
    1000
    6
    ```

> This doesn't happen from vim. Tested with this script:
> **repro.vim**
> ```vim
> set number
> set signcolumn=yes
> 
> wincmd v
> 
> let infos = getwininfo()
> echom infos[0].textoff
> echom infos[1].textoff
> ```
> Running `vim -u repro.vim` prints:
> ```
> 10
> 10
> ```

### Expected behavior

Two windows should have same `textoff` value right after the split.
So output should be like this:
```
1001
6
1000
6
```

### Nvim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

ubuntu 22.04

### Terminal name/version

blink shell

### $TERM environment variable

xterm-256-color

### Installation

build from repo

**Comment by justinmk** [comment]
Please test the latest development version. The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.

**Comment by zeertzjq** [comment]
It may work if you use `:redraw` before `getwininfo()`

**Comment by twittumz** [comment]
Removing the quotations seems to give the expected result.
 
`vim.o.signcolumn = yes`

**Comment by boltlessengineer** [comment]
> It may work if you use `:redraw` before `getwininfo()`

This did the trick.
But I found I can't make a test code for this.
Running `nvim -l repro.lua` still prints `4` and `6`.

Should I open separate issue for `-l` case?

**Comment by zeertzjq** [comment]
No
