### ISSUE TITLE
spell file download is unconditional

### ISSUE THREAD

**Issue by nschloe** [neovim/neovim#3055]
When editing a file that starts out with
```
% vim: spell spelllang=de
```
neovim greets you with
```
"/tmp/test.tex" 1L, 26C
Cannot find spell file for "de" in utf-8
Do you want me to try downloading it?
(Y)es, [N]o:
```
It tries to download to `~/.nvim/spell/de.utf-8.spl`, independently of whether this file exists. If it does, the download exists with an error.

**Comment by fmoralesc** [comment]
I'll take a look at it later today.

**Comment by fmoralesc** [comment]
I can't reproduce. Are you using a version after https://github.com/neovim/neovim/commit/5e9f9a875645af1e3c858daba799fe4a9021a767? That changed the behaviour of `&spell` on startup, but this shouldn't happen.

**Comment by Pyrohh** [comment]
I can't reproduce it either, all invocations of nvim after the file has been downloaded work fine for me. I'm using a commit after the one @fmoralesc mentioned.

**Comment by justinmk** [comment]
I did notice some wonkiness if I chose "no" for one of the intermediate questions in the 3-question sequence (with an empty `~/.nvim`).

**Comment by nschloe** [comment]
I'm using the [PPA](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable) version from
```
NVIM 0.0.0-alpha (compiled Jul 21 2015 07:39:43)
```
I can reproduce the described behavior on two different machines. The typical output would be
```
"/tmp/test.tex" 1L, 26C
Cannot find spell file for "de" in utf-8
Do you want me to try downloading it?
"/tmp/nvim2zwwpd/1.spl" [noeol] 5996L, 2388148C
Press ENTER or type command to continue
In which directory do you want to write the file:
1. /home/nschloe/.nvim/spell

Error detected while processing function spellfile#LoadFile:
line  107:
E13: File exists (add ! to override)
Press ENTER or type command to continue
Do you want me to try getting the .sug file?
This will improve making suggestions for spelling mistakes,
but it uses quite a bit of memory.
[N]o, (Y)es:
```
This is repeated every time I open a file that contains
```
% vim: spell spelllang=de
```

**Comment by nschloe** [comment]
This appear to have been solved. Closing.
