### ISSUE TITLE
Strange behavior in Netrw Directory Listing when `g:netrw_hide_list` is defined with a `.` in it

### ISSUE THREAD

**Issue by nicdgonzalez** [neovim/neovim#30565]
### Problem

The cursor blinks rapidly, sometimes not allowing me to execute commands or open files.

```vimscript
let g:netrw_list_hide = '^\./$,^\.\./$'
```

https://github.com/user-attachments/assets/0c846a24-ec7f-4c6b-9ecf-298f3fbfbe9a

### Steps to reproduce

Open Neovim -> execute `:let g:netrw_list_hide = '.'` and `:let g:netrw_hide = 1`

(You might have to press a key for it to start freaking out like this)

### Expected behavior

Netrw Directory Listing *doesn't* do that :)

### Nvim version (nvim -v)

NVIM v0.11.0-dev-69553f7-dirty

### Vim (not Nvim) behaves the same?

no, Vim 9.1

### Operating system/version

Fedora Linux Workstation 40

### Terminal name/version

GNOME terminal | Version 3.50.1 for GNOME 45

### $TERM environment variable

xterm-256color

### Installation

dnf install, then built from source while trying to fix myself

**Comment by glepnir** [comment]
I can't reproduce it with `nvim --clean -u NONE -c "let g:netrw_list_hide = '.' | let g:netrw_hide = 1" .`

**Comment by nicdgonzalez** [comment]
> I can't reproduce it with `nvim --clean -u NONE -c "let g:netrw_list_hide = '.' | let g:netrw_hide = 1" .`

You're right, I could not reproduce like that either. It definitely turns on and off when I uncomment that line in my configuration, but there must be something else that triggers it. Let me continue debugging. Thank you for your quick response!
