### ISSUE TITLE
Assertion Failure in msg_scroll_flush After Update

### ISSUE THREAD

**Issue by hardikkum444** [neovim/neovim#30577]
### Problem

After updating Neovim to the latest version, I encountered an assertion failure that causes Neovim to crash.

**NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1725453128**

The error message is not seen clearly either as neovim crashes immediately after opening which flashes the error message for like 5 nano seconds.

Was able to get after echoing the error 

`nvim | echo`

Which printed/produced the following error:

`nvim: /usr/src/debug/neovim/neovim/src/nvim/message.c:2403: msg_scroll_flush: Assertion `to_scroll >= 0' failed.`

Loading neovim without configuration works just fine

`nvim -u NONE`

But I know that this aint a problem with the packages or the config as the appimage of the latest stable release works just fine with everything (all configurations and gives no error)

### Steps to reproduce

Just the latest release causes this issue on launch of neovim.

### Expected behavior

**Expected behavior**
Neovim to run smoothly without crashing 
Command window is reopened, see listed files

**Actual behavior**
nvim: /usr/src/debug/neovim/neovim/src/nvim/message.c:2403: msg_scroll_flush: Assertion `to_scroll >= 0' failed.

### Nvim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

no, 9.1.740

### Operating system/version

arch linux

### Terminal name/version

alacritty 0.13.2 (bb8ea18e)

### $TERM environment variable

alacritty

### Installation

Arch Extra Repository

**Comment by zeertzjq** [comment]
Where are the steps to reproduce?

**Comment by hardikkum444** [comment]
I am able to fix it by removing the following packages/plugins from my config (noice)

```
use ('folke/noice.nvim')
use ('MunifTanjim/nui.nvim')
use ('rcarriga/nvim-notify')
```

I believe this is caused due to the noice plugin, which was also mentioned in  #21056
However I am not able to find a valid solution, the appimage of the latest nightly works just fine with all the plugins.

**Comment by justinmk** [comment]
> noice plugin, which was also mentioned in #21056

Let's consider this a duplicate then.
