### ISSUE TITLE
LSP: show rendered/highlighted documentation in completion popup

### ISSUE THREAD

**Issue by flexagoon** [neovim/neovim#30578]
### Problem

In the `vim.lsp.completion` popup, documentation written in markdown is not highlighted in any way

![image](https://github.com/user-attachments/assets/e69f6cce-c1d6-48a7-a0e8-69b2a3d8d539)

### Steps to reproduce

Enable completion with `vim.lsp.completion.enable()` and try to use it with any LSP that uses markdown documentation (eg. elixirls)

### Expected behavior

It should be highlighted automatically, like the `vim.lsp.buf.hover` popup:

![image](https://github.com/user-attachments/assets/35f7bf8c-32d6-4bc9-b77b-76df5a9712cb)

### Nvim version (nvim -v)

NVIM v0.11.0-dev+785-g44afd0744

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Fedora 40

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

neovim-nightly COPR repo

**Comment by glepnir** [comment]
you can set popup buffer filetype to markdown, but it also can be plaintext see https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#markupContent

and iduplicate https://github.com/neovim/neovim/issues/29225 .  the link issue have a  complete code for better popup
