### ISSUE TITLE
buffer mapping on floating window is not found

### ISSUE THREAD

**Issue by errael** [neovim/neovim#30587]
### Problem

I'm only guessing that the source of the problem is floating windows.

This problem applies to `maparg()`, `maplist()`, `:map`

`vim.keymap.del` does find the floating mapping.

### Steps to reproduce

Edit and source the test below, observe that `<F7>` is not found.
Notice that clicking on the floating window and pressing F7 works.
```
""  
':echo "got F6"<CR>'                                                                                
```

test
```
local popup_wid
local popup_bnr

local function Pop1()
    popup_bnr = vim.api.nvim_create_buf(false, true)
    assert(popup_bnr, "Failed to create buffer")
    vim.api.nvim_buf_set_lines(popup_bnr, 0, -1, true, {'simple', 'floater'})

    vim.api.nvim_set_option_value("bufhidden", "wipe", {buf = popup_bnr})
    vim.api.nvim_set_option_value("modifiable", true, {buf = popup_bnr})
	popup_wid = vim.api.nvim_open_win(popup_bnr, false, {
		relative = "editor",
		style = "minimal",
		width = 10,
		height = 2,
		focusable = true,
		col = 30,
		row = 6,
	})
	vim.keymap.set('n', '<F7>', ':echo "got F7"<CR>', {buffer = popup_bnr})
end

vim.keymap.set('n', '<F6>', ':echo "got F6"<CR>', {buffer = vim.fn.bufnr()})

Pop1()

vim.print(vim.inspect(vim.fn.maparg('<F7>')))
vim.print(vim.inspect(vim.fn.maparg('<F6>')))


--vim.print(vim.inspect(vim.fn.maplist()))

-- The following works
--vim.keymap.del('n', '<F7>', {buffer = popup_bnr})
```

### Expected behavior

The mappings from floating windows are found/displayed.

### Nvim version (nvim -v)

NVIM v0.11.0-dev - https://github.com/neovim/neovim/commit/99e0facf3a001608287ec6db69b01c77443c7b9d

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

ubuntu

### Terminal name/version

gnome

### $TERM environment variable

xterm-256color

### Installation

make install

**Comment by zeertzjq** [comment]
`maparg()` and `maplist()` won't find a buffer-local mapping if it's from non-current buffer. This is the case for non-floating windows as well. You can use `nvim_win_call` here.
