### ISSUE TITLE
Add UI protocol for cursorline

### ISSUE THREAD

**Issue by fredizzimo** [neovim/neovim#30584]
### Problem

The cursorline is embedded in the Window grid, which causes problems when scrolling in an UI like Neovide. This can be seen here, with a video https://github.com/neovide/neovide/issues/2818

 

### Expected behavior

It should be possible to use a UI protocol, so that we can deal with the cursorline ourselves, and do our own animations, totally decoupled from the grid scrolling itself.

**Comment by justinmk** [comment]
Duplicate of https://github.com/neovim/neovim/issues/6071 which has more info.
