### ISSUE TITLE
macros across tabs has a bug (with whichkey plugin)

### ISSUE THREAD

**Issue by garydwatson** [neovim/neovim#30598]
### Problem

in neovim execute the following set of keystrokes...

    :edit one.txt<cr>
    ione<esc>:w<cr>
    :edit two.txt<cr>
    itwo<esc>:w<cr>
    :edit three.txt<cr>
    ithree<esc>:w<cr>
    :bfirst<cr>
    :tabnew<cr>
    gt
    qqyygtpgt:bn<cr>q
    @q@q

the No Name buffer should contain

    one
    two
    three

but instead contains

    one
    two

and the tabs are not what they should be...

run the same steps in vim 9, and the output is as expected

### Steps to reproduce

in neovim execute the following set of keystrokes...

    :edit one.txt<cr>
    ione<esc>:w<cr>
    :edit two.txt<cr>
    itwo<esc>:w<cr>
    :edit three.txt<cr>
    ithree<esc>:w<cr>
    :bfirst<cr>
    :tabnew<cr>
    gt
    qqyygtpgt:bn<cr>q
    @q@q

### Expected behavior

the No Name buffer should contain

    one
    two
    three

### Nvim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

vim works correctly only neovim exibits the bug

### Operating system/version

linux debian trixie and macos

### Terminal name/version

gnome-terminal and macs default terminal software

### $TERM environment variable

xterm-256color

### Installation

on mac it was brew insall neovim, on linux I think I had to build from source

**Comment by justinmk** [comment]
did you try `nvim --clean`

**Comment by justinmk** [comment]
did you try `nvim --clean`  ?

Please also test the latest development version. The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by garydwatson** [comment]
ok, I just tested again, when I reset config back to stock config, macro works as expected...

I thought maybe whichkey was screwing things up, when I disable the whichkey plugin it also works properly, so it looks like the problem is with whichkey...   Thanks for the time, sorry for the goose chase.

**Comment by justinmk** [comment]
Please link to the exact whichkey plugin, that is useful as a reference.
