### ISSUE TITLE
why ppa:neovim-ppa/unstable comes with a huge runtime at /usr/share/nvim

### ISSUE THREAD

**Issue by GopherJ** [neovim/neovim#30590]
### Problem

this runtime contains rust.vim which doesn't work at all and its python related things slow down the startup time of  python

### Steps to reproduce

sudo add-apt-repository ppa:neovim-ppa/unstable 
sudo apt install neovim

ls /usr/share/nvim/runtime

I have to manually delete:

- sudo rm /usr/share/nvim/runtime/ftplugin/rust.vim
- sudo rm /usr/share/nvim/runtime/rust*

to removing the wierd rust related commands

### Expected behavior

remove those things which don't work anymore

### Nvim version (nvim -v)

NVIM v0.10.1 Build type: Debug LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux Mint (ubuntu22.04)

### Terminal name/version

alacritty 0.12.2 (9d9982df)

### $TERM environment variable

tmux-256color

### Installation

apt

**Comment by justinmk** [comment]
the ppa has the rust runtime files because nvim has the rust runtime files.

if you found a bug in the rust runtime files then provide steps to reproduce the issue, and report it to https://github.com/vim/vim .

`:help ft_rust.txt` documents various settings that can be disabled.
