### ISSUE TITLE
double click in tab bar does not open a new tab

### ISSUE THREAD

**Issue by garydwatson** [neovim/neovim#30599]
### Problem

in the documentation for tab pages, it says that you should be able to double click in the tab bar to open a new tab to the right of the last tab.  this is the behavior in vim9, in neovim you must double click an existing tab, and it will open to the left of that tab.

### Steps to reproduce

in neovim, open multiple tabs so that the tab bar is shown, double click the tab bar itself and observe that no new tab has been opened

in vim9, open multiple tabs so that the tab bar is shown, double click the tab bar itself and observe that a new tab has been opened

the docs for this feature are here... https://neovim.io/doc/user/tabpage.html#tab-page-commands

A double click with the mouse in the non-GUI tab pages line opens a new, empty
tab page.  It is placed left of the position of the click.  The first click
may select another tab page first, causing an extra screen update.

### Expected behavior

a new tab opens when double clicking the tab bar (to the right of the existing open tabs)

### Nvim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

vim opens the tab properly, neovim does not open a new tab

### Operating system/version

debian trixie

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

built from source I think.

**Comment by zeertzjq** [comment]
Hmm, in Vim single click also goes to the next tabpage.

**Comment by zeertzjq** [comment]
Simple solution:
```diff
diff --git a/src/nvim/mouse.c b/src/nvim/mouse.c
index 5e2f2f0320..5c4606ab7d 100644
--- a/src/nvim/mouse.c
+++ b/src/nvim/mouse.c
@@ -516,7 +516,7 @@ bool do_mouse(oparg_T *oap, int c, int dir, int count, bool fixindent)
 
         switch (tab_page_click_defs[mouse_col].type) {
         case kStlClickDisabled:
-          break;
+          FALLTHROUGH;
         case kStlClickTabSwitch:
           if (which_button != MOUSE_MIDDLE) {
             if ((mod_mask & MOD_MASK_MULTI_CLICK) == MOD_MASK_2CLICK) {
```

But this may be undesirable for a custom tabline.

**Comment by zeertzjq** [comment]
It seems that this behavior was removed in https://github.com/neovim/neovim/commit/ef662498b1ea1aca430624e3fc0d304494282c72

**Comment by zeertzjq** [comment]
I think it makes sense to restore this behavior for the default tabline. For a custom tabline the double-click part is already achievable using a very large tabpage number, although the single-click part is not.
