### ISSUE TITLE
ignorecase gets set globally when editing ada file

### ISSUE THREAD

**Issue by mmalcomson** [neovim/neovim#30596]
### Problem

Global value of `ignorecase` is changed when editing `ada` files.
I assume the same is the case for `hamster` files (based on a grep of the neovim runtime).

I believe the reason is that the `ignorecase` option is global, but `ada.vim` attempts to set it locally (inadvertantly setting it globally).
```
neovim [16:18:40] % grep -A8 "\*'ignorecase'" runtime/doc/options.txt
                        *'ignorecase'* *'ic'* *'noignorecase'* *'noic'*
'ignorecase' 'ic'       boolean (default off)
                        global
        Ignore case in search patterns, |cmdline-completion|, when
        searching in the tags file, and |expr-==|.
        Also see 'smartcase' and 'tagcase'.
        Can be overruled by using "\c" or "\C" in the pattern, see
        |/ignorecase|.

neovim [16:18:46] %
neovim [16:18:57] % git grep -n 'setlocal.*ignorecase'
runtime/ftplugin/ada.vim:52:setlocal ignorecase
runtime/ftplugin/hamster.vim:60:setlocal ignorecase
runtime/syntax/baan.vim:15:"setlocal ignorecase         "This is not a local yet ;-(
neovim [16:19:00] %
```

### Steps to reproduce

```
nvim --clean
:setglobal ignorecase?
:edit test.ada
:setglobal ignorecase?
```

### Expected behavior

Global value of `ignorecase` should not have changed.

### Nvim version (nvim -v)

v0.11.0-dev-422+g3c803483a

### Vim (not Nvim) behaves the same?

Yes.  vim 9.1 with patches 1.16, 647, 678

### Operating system/version

Ubuntu

### Terminal name/version

Xterm

### $TERM environment variable

xterm-256color

### Installation

Built from source.

**Comment by justinmk** [comment]
We don't want to fork the Vim runtime plugins in most cases (especially syntax plugins), unless there's a very good reason. Because if Vim changes something in the same file, it takes time to figure out the differences.

Please send this report to the maintainer, listed at the top of the file, or to https://github.com/vim/vim

**Comment by mmalcomson** [comment]
Sure -- just to link I've raised it here:
 https://github.com/vim/vim/issues/15772
