### ISSUE TITLE
extmarks placed incorrectly when `vim.opt.wrap = true` and `vim.opt.smoothscroll = true`

### ISSUE THREAD

**Issue by hneutr** [neovim/neovim#30603]
### Problem

1. set `vim.opt.wrap = true` and `vim.opt.smoothscroll = true`
2. make a line that takes up more than half the screen (so if there are `Y = vim.o.lines - vim.o.cmdheight` vertical lines and `X = vim.opt.columns` (minus however wide the signcolumn/etc is) columns, make a line of at least `(X+1) * (Y+1)` characters long)
3. yank the long line
4. add a new line with `# ` on it
5. add a new line and paste the long line on it

This will result in the extmark being applied below the expected location. 

Here's a visual representation, with `X` representing the long line and `|` representing the line the cursor is on (cursor column doesn't matter):

add the long line:

```
X|
```

add another line:

```
X
#|
```

add a second long line below the short line:

```
X
#
X|
```
move the cursor up to the short line.

run the following command: 
```
:lua vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace('test'), 1, 0, { virt_lines = { { { '           ', 'DiffDelete' } } }, virt_lines_above = true })
```

Here's a screenshot of the end state: 
<img width="1728" alt="Screenshot 2024-09-30 at 11 11 22 PM" src="https://github.com/user-attachments/assets/0f15dbd7-6ea1-4d13-a5ac-2132534b7776">

and here's a screenshot of the text without the extmark: 
<img width="1728" alt="Screenshot 2024-09-30 at 11 11 31 PM" src="https://github.com/user-attachments/assets/1187a027-979e-4b05-8ee6-00846e779012">

### Steps to reproduce

See above.

### Expected behavior

The extmarks are rendered on the correct line

### Nvim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

N/A (extmarks)

### Operating system/version

macOS 15.0

### Terminal name/version

kitty 0.32.2

### $TERM environment variable

xterm-kitty

### Installation

homebrew

**Comment by zeertzjq** [comment]
This seems to fix the problem:
```diff
diff --git a/src/nvim/drawscreen.c b/src/nvim/drawscreen.c
index 025d8fe721..eb63ec65f6 100644
--- a/src/nvim/drawscreen.c
+++ b/src/nvim/drawscreen.c
@@ -1804,7 +1804,7 @@ static void win_update(win_T *wp)
 
           // Correct the first entry for filler lines at the top
           // when it won't get updated below.
-          if (win_may_fill(wp) && bot_start > 0) {
+          if (win_may_fill(wp) && wp->w_skipcol == 0 && bot_start > 0) {
             wp->w_lines[0].wl_size = (uint16_t)(plines_win_nofill(wp, wp->w_topline, true)
                                                 + wp->w_topfill);
           }
```
