### ISSUE TITLE
Improve error handling for new unimpaired mappings

### ISSUE THREAD

**Issue by gpanders** [neovim/neovim#30625]
Pressing `]q` at the end of the quickfix list shows:

```
E5108: Error executing lua: vim/_defaults.lua:0: Vim:E553: No more items
stack traceback:
        [C]: in function 'cnext'
        vim/_defaults.lua: in function <vim/_defaults.lua:0>
```

when it should simply show

```
E553: No more items
```

just as if the user had used `:cnext` directly.

**Comment by lsvmello** [comment]
Does this do the trick?

```lua
vim.keymap.set('n', ']q', function()
  local _, err = pcall(vim.cmd.cnext, { count = vim.v.count1 })
  if err ~= nil then
    vim.notify(err, vim.log.levels.ERROR)
  end
end, {
  desc = ':cnext',
})
```

Or you want to implement it on `vim.cmd` directly?

**Comment by gpanders** [comment]
> Does this do the trick?
> 
> ```lua
> vim.keymap.set('n', ']q', function()
>   local _, err = pcall(vim.cmd.cnext, { count = vim.v.count1 })
>   if err ~= nil then
>     vim.notify(err, vim.log.levels.ERROR)
>   end
> end, {
>   desc = ':cnext',
> })
> ```
> 
> Or you want to implement it on `vim.cmd` directly?

That looks correct, though we'll want to use `vim.api.nvim_err_writeln()`, not `vim.notify`.

**Comment by gpanders** [comment]
#30884 does not meet the requirements in this issue. The error message should be: `E553: No more items`, but with #30884 the error message is `vim/_defaults.lua:0: Vim:E553: No more items`.

This is not just needless pedantry: the latter error message contains lots of visual noise that is useless to the user. We should be showing just the same error message that the user would see as if they had used `:cnext` directly.
