### ISSUE TITLE
commenting: "gcc" with 'nostartofline' should not affect cursor column

### ISSUE THREAD

**Issue by lsvmello** [neovim/neovim#30624]
### Problem

When you comment a line using `gcc` keymap the cursor goes back to the start of the line.

### Steps to reproduce

1. nvim --clean
2. :e file.lua
3. insert any text
4. gcc

### Expected behavior

Since `yy` and `dd` keeps the cursor on the same column, I think it would be a better if `gcc` also did.

### Nvim version (nvim -v)

v0.10.1

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Windows 11

### Terminal name/version

powershell

### $TERM environment variable

empty

### Installation

chocolatey --pre

**Comment by lsvmello** [comment]
### Workaroud

`vim.keymap.set('n', 'gcc', 'gc$', { desc = 'Toggle comment line' }) `

### Necessary change

https://github.com/neovim/neovim/blob/391c5084d1181a6742ebd8551efda4db7e8ca46e/runtime/lua/vim/_defaults.lua#L143-L146

Change '_' on line 144 to '$' or 'l'.

**Comment by justinmk** [comment]
Builtin `>>` also seems to preserve the cursor, so I guess this seems reasonable.

**Comment by xzbdmw** [comment]
`dd`  behaves different with vim, vim will move cursor to line start, `:h vim-differences` seems not includes this, and the document of `dd` is the same with vim.

**Comment by zeertzjq** [comment]
> - 'startofline' is disabled

**Comment by xzbdmw** [comment]
Ah That's it -)

**Comment by zeertzjq** [comment]
Hmm, maybe `gcc` should also respect 'startofline'?

**Comment by echasnovski** [comment]
The current behavior of moving cursor to the start of line is intentional. It is consistent with other similar built-in operators that modify text and have the same mapping structure: `guu`, `gUU`, `g~~`. All this is based on the [documented behavior of operators](https://github.com/neovim/neovim/blob/b9737891154750e16429e67c92f392d8f29bd820/runtime/doc/motion.txt#L64-L66).
