### ISSUE TITLE
vim.json.decode does not work when a Windows path (forward slashes) is included in the json string

### ISSUE THREAD

**Issue by waynebowie99** [neovim/neovim#30634]
### Problem

vim.json.decode does not like Windows path

### Steps to reproduce

Run the following command
`lua vim.json.decode('{"seq":197, "event":"output","type":"event","body":{"category":"stdout","output":"Trace [0]: Before tracking, Number of tracked entities is 1\\r\\n","source":{"name":"DBContextExtensions.cs","path":"C:\\Users\\wayneb\\source\\Services\\Jobs\\Service-Helper\\ServiceHelper.Helpers\\Extensions\\DBContextExtensions.cs"}}}')`

### Expected behavior

This command works as the Windows path as the backslashes were changed to forward slashes 

`lua vim.json.decode('{"seq":197, "event":"output","type":"event","body":{"category":"stdout","output":"Trace [0]: Before tracking, Number of tracked entities is 1\\r\\n","source":{"name":"DBContextExtensions.cs","path":"C:/Users/wayneb/source/Services/Jobs/Service-Helper/ServiceHelper.Helpers/Extensions/DBContextExtensions.cs"}}}')`

### Nvim version (nvim -v)

NVIM v0.10.1

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Windows 11

### Terminal name/version

Neovide

### $TERM environment variable

NA

### Installation

Chocolatey

**Comment by zeertzjq** [comment]
JSON strings support double slash escaping, so to use a backslash in JSON you need two backslashes in a JSON string, which means four backslashes in a Lua double-quoted string.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/30561 will change the default here

**Comment by zeertzjq** [comment]
No, that's for encoding.

**Comment by waynebowie99** [comment]
Looking at #30561, why did decoding not get the extra options? From my experience with json decoding, my thought was a double slash "\\" would become a single slash "\". The provided example comes from the netcoredbg dap provider as it encodes the string in a way I would expect

Maybe there's something with Lua I don't understand but at least in the C# world, that example would world perfectly
