### ISSUE TITLE
`screenpos()` returns all zeros under specific circumstances

### ISSUE THREAD

**Issue by wincent** [neovim/neovim#30639]
### Problem

`screenpos()` _sometimes_ returns all zeros; ie:

```lua
{
  col = 0,
  curscol = 0,
  endcol = 0,
  row = 0
}
```

instead of the actual screen coordinates, causing plug-ins like [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) to draw their autocomplete pop-up menu in the top-left of the screen instead of at the cursor location:

![autocomplete menu appearing in the wrong place](https://github.com/user-attachments/assets/de1f16ee-88ab-4065-9ba1-acc2d0ffcfbc)

This was originally reported in:

- https://github.com/neovim/neovim/issues/19606

but without a consistent repro. I've been seeing this happen intermittently for years and have never been able to find a reliable repro recipe, until now.

### Steps to reproduce

This one is incredibly sensitive to initial conditions (screen size, font size, path lengths), and rather fiddly to reproduce. Nevertheless, I've found that I can trigger the bug from a clean Neovim install by interacting with the [vim-dirvish](https://github.com/justinmk/vim-dirvish) plug-in and following a very precise set of steps. (I don't think this is a bug with vim-dirvish or with nvim-cmp, but they are useful to illustrate the bug.)

1. Size your terminal window such that it is 137 columns wide. Verify this with:
   ```
   tput cols
   ```
2. Create a new scratch directory in which to reproduce the bug:
   ```
   mkdir /tmp/scratch
   ```
   Note that the name of the path matters here because the path must be of a certain length to trigger the bug.
3. Change into the scratch directory:
   ```
   cd /tmp/scratch
   ```
4. Create directories in which to put the repro files:
   ```
   mkdir -p aspects/nvim/files/.config/nvim/plugin/mappings
   ```
   There's nothing special about the _contents_ of this path (this is just a path from the project I was in when I discovered how to repro the bug) but the _length_ of the path does matter.
5. Create repro files (again, contents don't matter, so `touch` will suffice and, again, the names are just take from the project I was in and its the length that matters):
   ```
   touch aspects/nvim/files/.config/nvim/plugin/mappings/normal.lua
   touch aspects/nvim/files/.config/nvim/plugin/mappings/visual.lua
   ```
6. Grab a copy of vim-dirvish:
   ```
   mkdir -p pack/bundle/opt
   git clone https://github.com/justinmk/vim-dirvish.git pack/bundle/opt/vim-dirvish
   ```
7. Launch Neovim with no config:
   ```
   nvim -u NONE
   ```
8. Load vim-dirvish:
   ```
   set packpath=.
   packadd vim-dirvish
   packloadall
   ```
9. Create a mapping so that you can inspect the result of `screenpos()` (this one taken from #19606):
   ```
   :nmap <c-s> :lua print(vim.inspect(vim.fn.screenpos(0, vim.api.nvim_win_get_cursor(0)[1], vim.api.nvim_win_get_cursor(0)[2]+1)))<cr>
   ```
10. Open the first of the repro files:
    ```
    :e aspects/nvim/files/.config/nvim/plugin/mappings/normal.lua
    ```
11. Create a vertical split:
    ```
    :vs
    ```
12. Move focus to window on right side of the split:
    ```
    <C-w l>
    ```
13. Invoke vim-dirvish to show the contents of the containing directory:
    ```
    :Dirvish
    ```
14. Hit `j` to move down to the sibling file (`visual.lua`).
15. Hit `Enter` to open the file.
16. Hit the `<C-s>` binding you created previously to display the `screenpos()` result; note that it's all zeros:
    ```
    {
      col = 0,
      curscol = 0,
      endcol = 0,
      row = 0
    }
    ```

Additional notes:

- This repros both inside tmux (`TERM=tmux-256color`) and outside (`TERM=xterm-kitty`).
- It also appears to affect the Vim (tested using `-u DEFAULTS` on version 9.1 from Homebrew and 9.0, as provided by Apple with the OS)[^vim].
- As I mentioned above, this whole thing is very sensitive to path lengths and cursor position:
  - In the vim-dirvish listing, move the cursor to the end (`$`) before opening the second file, and the bug repros.
  - Move it to the beginning (`^`) before opening the second file, and it does not repro.
- In common with the original report (#19606), after you've seen the bug, running `:set wrap` (even if it was already set) temporarily fixes the problem and hitting the `<C-s>` mapping shows that `screenpos()` will return sensible results again.
- Font size matters, because it affects the number of characters that appear before the line is too wide to show on the screen. For example, if I make my font small enough so that everything fits, this no longer repros. For reference, this screenshot shows my font size when reproing the issue: ![font size reference](https://github.com/user-attachments/assets/0dc0041f-3add-403c-8a37-621323f73613)

[^vim]: I posted this here first because Neovim is my daily driver, but I will also report upstream.

### Expected behavior

`screenpos()` should return real screen coordinates, like:

```
{
  col = 70,
  curscol = 70,
  endcol = 70,
  row = 1
}
```

### Nvim version (nvim -v)

- NVIM v0.10.1
- NVIM v0.10.2

### Vim (not Nvim) behaves the same?

yes, 9.1

### Operating system/version

macOS 14.7

### Terminal name/version

kitty 0.36.4

### $TERM environment variable

tmux-256color

### Installation

Homebrew

**Comment by justinmk** [comment]
Great report, thanks! Since you mentioned Dirvish I was going to suggest disabling conceal (`set conceallevel=0`) to see if that changes the behavior, but your screenshot looks like it already did?

Also try clearing syntax in the dirvish buffer: `:syn clear`

**Comment by wincent** [comment]
> Great report, thanks! Since you mentioned Dirvish I was going to suggest disabling conceal (`set conceallevel=0`) to see if that changes the behavior, but your screenshot looks like it already did?
> 
> Also try clearing syntax in the dirvish buffer: `:syn clear`

No, I haven't touched `conceallevel`; it's `0` by default, and `2` in the vim-dirvish buffer. If I set it back to `0` in the vim-dirvish buffer, the bug still manifests. Likewise, it still manifests after a `:syn clear`.

Trying it out just now I found I can simplify the repro a little:

- I found that the vertical split isn't needed to repro the bug; the only thing that does is narrow the window enough to make the bug happen. So, if I shrink my terminal window (to 68 columns, as reported by `tput cols`), the bug reproduced without needing a split.
- Likewise, I don't need to actually swap between two files. I can just open vim-dirvish with `:Dirvish`, then hit `<CR>` to open the same file, and the bug repros.

So, it's all about width, and it only happens when `:set wrap?` reports `wrap`.

Meanwhile, there's a potential suggested fix over here:

- https://github.com/vim/vim/issues/15792#issuecomment-2392387779

> Hm, `w_leftcol` hasn't been updated yet and has still the old value. This patch fixes it:
> 
> ```
> diff --git a/src/move.c b/src/move.c
> index f2780e584..b6623e8a0 100644
> --- a/src/move.c
> +++ b/src/move.c
> @@ -1494,7 +1494,8 @@ textpos2screenpos(
>                 col -= rowoff * width;
>                 row += rowoff;
>             }
> -           col -= wp->w_leftcol;
> +           if (col > (int)wp->w_leftcol)
> +               col -= wp->w_leftcol;
>             if (col >= wp->w_width)
>                 col = -1;
>             if (col >= 0 && row >= 0 && row < wp->w_height)
> ```
>
> As the comment a few lines above states, it should behave similar to `validate_cursor_col()` which is what this patch does.

I tried a similar patch against current `master`:

```diff
diff --git a/src/nvim/move.c b/src/nvim/move.c
index 6324466dc..0c2c59f78 100644
--- a/src/nvim/move.c
+++ b/src/nvim/move.c
@@ -1080,7 +1080,9 @@ void textpos2screenpos(win_T *wp, pos_T *pos, int *rowp, int *scolp, int *ccolp,
         row += rowoff;
       }
 
-      col -= wp->w_leftcol;
+      if (col > (int)wp->w_leftcol) {
+        col -= wp->w_leftcol;
+      }
 
       if (col >= 0 && col < wp->w_width_inner && row >= 0 && row < wp->w_height_inner) {
         coloff = col - scol + (local ? 0 : wp->w_wincol + wp->w_wincol_off) + 1;
```

and it does seem to fix the bug.

I note that `move.c` (and `textpos2screenpos()`) has diverged a bit between Vim and Neovim at this point, so not sure if there's anything else to take into consideration.

**Comment by wincent** [comment]
Sent a PR with the suggested fix:

- https://github.com/neovim/neovim/pull/30653

Not sure how to write a test for this though.
