### ISSUE TITLE
`:checkhealth lsp` should show workspace folders

### ISSUE THREAD

**Issue by gpanders** [neovim/neovim#30648]
This client has 2 workspace folders configured, but only shows the root directory. We should also show all workspace folders if there are any (or perhaps if there are >1)?

```
vim.lsp: Active Clients ~
- gopls (id: 1)
    Root directory: ~/src/some/project
    Command: gopls
    Settings: {
      gopls = {
        analyses = {
          nilness = true,
          unusedparams = true,
          unusedwrite = true
        }
      }
    }
    Attached buffers: 1
```

cc @mfussenegger

**Comment by mfussenegger** [comment]
Sounds good to me but keep in mind that we derive the workspace folder from the root directory. 
I'd say only show any that are different from the root directory.

**Comment by justinmk** [comment]
for reference, `:che lspconfig` has some logic for this https://github.com/neovim/nvim-lspconfig/blob/fb453a1a443b6ea6b54a1e4c101b1160c9d37950/lua/lspconfig/health.lua#L132-L137
