### ISSUE TITLE
CANNOT LINK EXECUTABLE "nvim": library "libtree-sitter.so.0.23" not found

### ISSUE THREAD

**Issue by drui9** [neovim/neovim#30657]
### Problem

Neovim editor fails to launch with error message: 
```
CANNOT LINK EXECUTABLE "nvim": library "libtree-sitter.so.0.23" not found
```

Installed tree-sitter version is 0.24.1
Neovim version is: 0.10.2
Platform: android 10 running on termux.

### Steps to reproduce

Installed the above mentioned application versions, and run neovim.

### Expected behavior

Neovim editor should open.

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

android 10

### Terminal name/version

termux 119

### $TERM environment variable

xterm-256color

### Installation

apt

**Comment by clason** [comment]
> Installed tree-sitter version is 0.24.1

There's your issue then. Please report this to the apt packager.

**Comment by drui9** [comment]
Temprorary fix:
cd /usr/lib
cp libtree-sitter.so.0.24 libtree-sitter.so.0.23

**Comment by clason** [comment]
No, that is _not_ a fix!

**Comment by drui9** [comment]
> No, that is _not_ a fix!

I just hoped nvim would open, and it did.

**Comment by Serega124** [comment]
[It's fixed](https://github.com/termux/termux-packages/issues/21659#event-14521188898) in Termux repo

**Comment by epidemicreddz** [comment]
your neovim is probably outdated
0.10.2 expects an older version of treesitter that you dont have

**Comment by drui9** [comment]
Fixed.

**Comment by 86kkd** [comment]
My neovim crashed in arch linux and fix by uninstall neovim then install neovim-nvim-treesitter and neovim

**Comment by frozen905** [comment]
Fixed how?

I'm on latest Termux and it's not fixed at all for me

CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/nvim": cannot locate symbol "uv_udp_try_send2" referenced by "/data/data/com.termux/files/usr/lib/libluv.so"...
$

**Comment by banana9487** [comment]
It doesn't be fixed now
Just run apt update && apt upgrade -y
It upgrade tree-sitter
and then run nvim
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/nvim": library "libtree-sitter.so.0.24" not found: needed by main executable
on termux 
nvim ver 0.10.4
