### ISSUE TITLE
LSP completion: `CompleteDone`: unwanted cursor jumping

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#30656]
### Problem

I noticed that after expanding `vim._with()` context keys the cursor jumps to the end of line instead to the end of completed word (e.g. `bo`). I found that that case is treated as snippet expansion:

https://github.com/neovim/neovim/blob/305012ea073267492e1d626a304c6993b0dfa145/runtime/lua/vim/lsp/completion.lua#L522-L523

Is it correct in that case?

The text after cursor is cut and saved to `suffix` that is then appended to the text expanded as snippet. 

https://github.com/neovim/neovim/blob/305012ea073267492e1d626a304c6993b0dfa145/runtime/lua/vim/lsp/completion.lua#L535-L545

Assuming that I commit complete `bo` in `vim._with({bo}, f)`, I get `bo}, f)` passed to `vim.snippet.expand`.

https://github.com/neovim/neovim/blob/305012ea073267492e1d626a304c6993b0dfa145/runtime/lua/vim/lsp/completion.lua#L117-L123

Maybe in 
https://github.com/neovim/neovim/blob/305012ea073267492e1d626a304c6993b0dfa145/runtime/lua/vim/lsp/completion.lua#L543

replacing `#line` with `cursor_col` would fix it? 

### Steps to reproduce

init.lua:
```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = {'lua'},
  group = vim.api.nvim_create_augroup('luals', {}),
  callback = function ()
    vim.lsp.start({
      name = 'luals',
      filetype = 'lua',
      cmd = {'lua-language-server'},
      root_dir = vim.uv.cwd(),
      settings = {
        Lua = {
          runtime = {
            path = {
              '?.lua',
              '?/init.lua',
            },
            version = 'LuaJIT',
            pathStrict = true,
          },
          workspace = {
            ignoreDir = {'lua'},
            checkThirdParty = false,
            library = {
              vim.fs.joinpath(vim.env.VIMRUNTIME, 'lua'),
              vim.fs.joinpath('${3rd}/luv/library', 'lua'),
            },
          },
          diagnostics = {
            globals = {'vim'},
          },
        },
      },
    })
  end,
})

vim.api.nvim_create_autocmd('LspAttach', {
group = vim.api.nvim_create_augroup('arctgx.completion', {clear = true}),
  callback = function (args)
    local clientId = args.data.client_id
    local client = assert(vim.lsp.get_client_by_id(clientId))
    vim.notify(('Server %s attached'):format(client.name), vim.log.levels.INFO)
    vim.lsp.completion.enable(true, clientId, args.buf, {autotrigger = true})

    vim.keymap.set({'i'}, '<C-Space>', function ()
      vim.lsp.completion.trigger()
    end, {buffer = args.buf})
  end
})

vim.go.completeopt = 'noinsert,menuone'
```
- `nvim --clean -u init.lua new.lua`
- after server is attached insert `vim._with({bo}, f)` and try to confirm `bo` completion with `<C-y>` and see the cursor on the end of line. 

### Expected behavior

Cursor stays at the end of `bo`. 

### Nvim version (nvim -v)

v0.11.0-dev-897+g305012ea0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian Sid

### Terminal name/version

alacritty 0.14.0-dev (6585d604), tmux 3.5

### $TERM environment variable

tmux-256color

### Installation

from repo

**Comment by justinmk** [comment]
> after expanding `vim._with()` context keys the cursor jumps to the end of line instead to the end of completed word (e.g. `bo`).

If a fix for `vim._with`, please consider sending a patch with a test added to `./test/functional/lua/with_spec.lua` .



> replacing `#line` with `cursor_col` would fix it?

also worth a try. try the change and see if `./test/functional/plugin/lsp/completion_spec.lua` fails, or add a test if it's not covered.

**Comment by przepompownia** [comment]
I have no suspicions that metadata of `vim._with` (`@class vim.context.mods`) should be fixed. We have simply `@field bo? table<string, any>`.

https://github.com/neovim/neovim/blob/305012ea073267492e1d626a304c6993b0dfa145/runtime/lua/vim/shared.lua#L1161-L1162

The tests that failed for me on `make functionaltest` are probably not related to the change from #30659 (although I did not repeat them on clean master branch): all come from `tui_spec.lua` or `scrollback_spec.lua`.
