### ISSUE TITLE
`nvim_open_win` `anchor` off by 1 for `NE`, `SW`, `SE`

### ISSUE THREAD

**Issue by errael** [neovim/neovim#30663]
### Problem

This may not be a bug. Looking at the documentation it says
> With relative=editor (row=0,col=0) refers to the top-left corner of the screen-grid

If this refers to a "point" and not a "cell", then it is behaving correctly and there is no bug.

The closest vim has to this is `popup_create`'s `pos` option. There it is a cell.

### Steps to reproduce

Source the following script. The floating window is in the box. Enter the normal
mode mapping `Z1` to re-draw the floating using the next anchor.

```


vim.o.scl = "yes"

--               _______
--              |X      | 
--              |       | 
--               -------

-- Z1 - Delete current floater, new floater at next window anchor

local pos_map = {
    "NW",
    "NE",
    "SW",
    "SE",
}
local pos_index = 0

local popup_wid
local function Pop1()
    local bnr = vim.api.nvim_create_buf(false, true)
    assert(bnr, "Failed to create buffer")
    vim.api.nvim_buf_set_lines(bnr, 0, -1, true, {'simple', 'win'})

    vim.api.nvim_set_option_value("bufhidden", "wipe", {buf = bnr})
    vim.api.nvim_set_option_value("modifiable", true, {buf = bnr})
    local opts = {
        row = 5,
        col = 19,
        relative = "editor",
        style = "minimal",
        width = 7,
        height = 2,
        focusable = false,
    }
    opts.anchor = pos_map[pos_index + 1]
    pos_index = (pos_index + 1) % #pos_map
    popup_wid = vim.api.nvim_open_win(bnr, false, opts)
    vim.print(string.format("WindowCreate: %s", opts.anchor))
end

Pop1()

local function next_anchor()
    vim.api.nvim_win_close(popup_wid, true)
    Pop1()
end

vim.keymap.set('n', 'Z1', next_anchor)

vim.o.tm = 5000
```

### Expected behavior

Expected the "X" to be covered by each anchor corner. (but that may be based on a flawed understanding).

### Nvim version (nvim -v)

https://github.com/neovim/neovim/commit/20251be15a4ad3f6e7016450ca3338d52b2f0951

### Vim (not Nvim) behaves the same?

no but not entirely applicable

### Operating system/version

ubuntu

### Terminal name/version

gnome

### $TERM environment variable

xterm-256color

### Installation

make install

**Comment by zeertzjq** [comment]
See https://github.com/neovim/neovim/pull/15832#discussion_r720112432

**Comment by errael** [comment]
> Ref [#15832 (comment)](https://github.com/neovim/neovim/pull/15832#discussion_r720112432)
> 
> > think of the anchor point as the upper-left corner of the marked cell, not the middle of it.

Thanks for the reference. This is expected behavior, looks like it's "moved" around before settling on including floater's border. I was just getting to checking how it works with the border. It's consistent, and now that I know I can fix the popup compatibility layer to match the behavior.

It will be messy since I'll have to translate back and forth if not "NW" anchor. The `row`, `col` of `nvim` is already adjusted with a constant one to match `vim`'s positioning. Now the adjustment gets even weirder.
