### ISSUE TITLE
Neovim always adding a text when saving zig file

### ISSUE THREAD

**Issue by Rizwanelansyah** [neovim/neovim#30666]
### Problem

when i'm editing zig file after i save the file neovim add "export plugin already enabled" line before saved.
[![asciicast](https://asciinema.org/a/679095.svg)](https://asciinema.org/a/679095)

### Steps to reproduce

nvim src/main.zig
nvim -u NORC -- src/main.zig

### Expected behavior

file saved without additional line

### Nvim version (nvim -v)

NVIM v0.10.1

### Vim (not Nvim) behaves the same?

no, vim 9.1.740

### Operating system/version

archlinux 6.10.2-arch1-1

### Terminal name/version

kitty 0.35.2

### $TERM environment variable

tmux-256color

### Installation

Arch User Repository (AUR)

**Comment by glepnir** [comment]
can't reproduce with my config and please provide more information also try with `nvim --clean u NONE main.zig`

**Comment by Rizwanelansyah** [comment]
> can't reproduce with my config and please provide more information also try with `nvim --clean u NONE main.zig`, check `:au BufWritePre` or `:au BufWritePost`

i get this:
```
:au BufWritePre
--- Autocommands ---
vim-zig  BufWritePre
    <buffer=1>
              if get(g:, 'zig_fmt_autosave', 1) | call zig#fmt#Format() | endif
```

after i remove it the autocommand with `autocmd! vim-zig` the line doesn't appear anymore,
But I don't know where this auto command comes from.

**Comment by glepnir** [comment]
I guess you are using zig.vim ? you can disable it by `let g:zig_fmt_autosave = 0` or `vim.g.zig_fmt_autosave = false`

**Comment by Rizwanelansyah** [comment]
I don't remember i installed something related to Zig, but that's work thanks.
