### ISSUE TITLE
Visual selection clears transparent foldtext coloring

### ISSUE THREAD

**Issue by ribru17** [neovim/neovim#30676]
### Problem

When a folded line is within the visual selection, its transparent fold text coloring is lost.

Before pressing `v`:
![image](https://github.com/user-attachments/assets/09c103f3-4464-45a5-b33c-df47aba8269d)

After pressing `v`:
![image](https://github.com/user-attachments/assets/315e652c-f6e5-4c92-9603-ba3465330e8a)

### Steps to reproduce

`minimal.lua`:
```lua
vim.wo.foldmethod = 'expr'
vim.wo.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
vim.wo.foldtext = ''
vim.api.nvim_create_autocmd('BufEnter', {
  callback = function()
    vim.treesitter.start()
  end,
})
```
Open a file that can be folded:
```md
## Heading

### Another heading `here` [linky](link)

Text
```

### Expected behavior

The foldtext colors should appear still, as they do when in a visual selection regularly (when not folded). Like this:
![image](https://github.com/user-attachments/assets/248d3546-29ac-492c-8664-85fcca6b594f)

### Nvim version (nvim -v)

Nightly, commit f62728cd80a9c458b1c0ef7c5c1251e55fe91090

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

NixOS, linux kernel 6.11.0

### Terminal name/version

kitty 0.36.1

### $TERM environment variable

xterm-kitty

### Installation

NixOS nightly overlay

**Comment by zeertzjq** [comment]
This seems to happen for spell checking as well: normally spell highlight has higher priority than syntax/extmark highlight, but when the text is inside Visual selection, spell highlight has lower priority then syntax/extmark highlight.
