### ISSUE TITLE
LSP: Semantic token highlighting error (Tinymist)

### ISSUE THREAD

**Issue by C0deBr3ak3r** [neovim/neovim#30675]
### Problem

Semantic token highlighting fails when using tinymist with error
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:149: index
 out of range                                                                                                                                                             
stack traceback:                                                                                                                                                          
        [builtin#36]: at 0x7a4e388484e0                                                                                                                                   
        /usr/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: in function 'handler'                                                                                
        /usr/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''                                                                                                
        vim/_editor.lua: in function <vim/_editor.lua:0>   
```
The errors was introduced by the new 0.10.2 version, likely an off by one error
![image](https://github.com/user-attachments/assets/79c3ec8d-8cf5-485d-84e1-b799de6811d4)
on 0.11.0-dev it has highlighting, but they ain't coming from the LSP

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
vim.lsp.set_log_level("debug")

local pattern = 'typst'
local cmd = { 'tinymist' }
-- Add files/folders here that indicate the root of a project
local root_markers = { '.git', '.editorconfig', 'typst.toml' }
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
	pattern = pattern,
	callback = function(args)
		local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
		local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
		vim.lsp.start({
			name = 'bugged-ls',
			cmd = cmd,
			root_dir = root_dir,
			settings = settings,
		})
	end,
})
```

### Expected behavior

The text should be highlighted with the proper LSP tokens, for keywords, strings, functions and so on
![image](https://github.com/user-attachments/assets/84fbbcc8-6824-412c-9b9f-115af0003ac5)

### Nvim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### Language server name/version

tinymist v0.11.28

### Operating system/version

Arch Linux x86_64

### Log file

https://gist.github.com/C0deBr3ak3r/129eb416ab046490b1a529d7a50b6142

**Comment by C0deBr3ak3r** [comment]
> > introduced by the new 0.10.2 version, likely an off by one error
> 
> so 0.10.1 was ok? can you bisect to the exact commit

0.10.1 was ok. Bisecting i found it, it was 003b8a251dc1184e36c222f675bf79a50a40ab3a this commit

**Comment by igorlfs** [comment]
Adding 
```lua
    offset_encoding = "utf-8",
```
To [my lspconfig for tinymist](https://github.com/igorlfs/dotfiles/commit/51199d1a33a5fa28f198a6dcd6858aad8e5e106c) solved the issue.
It might be an issue with tinymist. [This code snippet](https://github.com/Myriad-Dreamin/tinymist/blob/485adc77613d57160b63e298172f9f81a8770706/crates/tinymist-query/src/semantic_tokens/mod.rs#L162-L167) might be related.

**Comment by justinmk** [comment]
@tris203 may be able to say if this is expected or not

**Comment by tris203** [comment]
My gut says that it is a issue where the LSP is sending UTF-8 encoded positions

@igorlfs I haven't worked with typst before, can you create a minimal reproduction repo with the required config files and structure etc to test with?

**Comment by igorlfs** [comment]
> @igorlfs I haven't worked with typst before, can you create a minimal reproduction repo with the required config files and structure etc to test with?

The process should be straightforward. You can use the minimal `init.lua` from the OP and `git init` a repo containing a single typst file (eg, `foo.typ`) with any non-ascii character. For instance

```typst
= é
```

**Comment by tris203** [comment]
Yes, the LSP appears to be sending back UTF-8 encoded positions, not UTF-16 encoded positions (default) so you would need to specify that in the set up.

It was previously being masked by this pcall
https://github.com/neovim/neovim/commit/003b8a251dc1184e36c222f675bf79a50a40ab3a#diff-3b3a433b8799463f3cb0bcfbb0f1b699c0b949e7e31516e82b94a9c6aea3b395L81

But, i think this is the correct behaviour

**Comment by justinmk** [comment]
Can we show an error like "failed to decode server response, expected utf-x"

**Comment by tris203** [comment]
> Can we show an error like "failed to decode server response, expected utf-x"

I don't think so, as we only receive an integer index from the LSP.

Interestingly, I just backported #30585 to 0.10 and the error would not longer through the highlighting would continue to work, although this relies on the lua implementation of ```str_byteindex``` which decided against in the blocking PR

**Comment by john-mutuma** [comment]
Similar errors encountered with plugins that allow switching buffers quickly e.g. Glance.nvim, oil.nvim

```
Error executing vim.schedule lua callback: ...local/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:309: ...local/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:102: Invalid buffer id: 32
stack traceback:
	[builtin#36]: at 0x5a9e035cf470
	...local/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:309: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...local/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:309: ...local/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:102: Invalid buffer id: 33
stack traceback:
	[builtin#36]: at 0x5a9e035cf470
	...local/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:309: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

[#435](https://github.com/stevearc/oil.nvim/issues/435) reported  in a plugin repo.

**Comment by pwnwriter** [comment]
I've been having the same issue on 
```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

Does it need downgrade or is there any update on this?

**Comment by justinmk** [comment]
@pwnwriter notice the milestone (0.10.3) that marks this issue.

**Comment by pwnwriter** [comment]
@justinmk is there any temp solution for this? I can't even work on lsp without this being fixed.
