### ISSUE TITLE
Copy/pasting paragraphs in visual mode inserts extra line.

### ISSUE THREAD

**Issue by zanshin** [neovim/neovim#3067]
Using v}y}p to copy a paragraph and insert it after itself in Neovim works differently than in Vim. In Neovim an extra line is insert.

Before: http://imgur.com/iMmCxai

Highlight, copy, and paste the 5 lines starting with line 1168: v}y}p

After Vim: http://imgur.com/wU8bHfj

After nvim: http://imgur.com/kS54g5P

**Comment by mhinz** [comment]
I can confirm that this is the case since at least Vim 7.3, which means it's most probably no missing patch, but an actual bug.

**Comment by zanshin** [comment]
I'm on VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 13 2015 22:14:38), and NVIM 0.0.0-alpha+201507171736 (compiled Jul 17 2015 16:51:12)

**Comment by mhinz** [comment]
Although I have to admit that the NeoVim behaviour makes more sense to me, but due to consistency this should be looked into nevertheless.

**Comment by mhinz** [comment]
Oops. Vim and Neovim seem to behave the same.

@zanshin `nvim -u NONE` should work as expected. Let me find the culprit option..

**Comment by fmoralesc** [comment]
I imagine it's set to `unnamed`? xsel (or whatever util is used) might be appending an extra `\n` to the register.

**Comment by mhinz** [comment]
Yup.

**Comment by bfredl** [comment]
I can't reproduce locally, but yes this occurs between instances, basically the same issue as #1822. In the pure text format, a trailing `\n` is encoding linewise mode.

**Comment by justinmk** [comment]
Merging this with https://github.com/neovim/neovim/issues/1822 , thanks for the report.
