### ISSUE TITLE
LSP completion error: lsp/_completion.lua:154: attempt to index nil 'range' (server bug: assumes `insertReplaceSupport`)

### ISSUE THREAD

**Issue by RononDex** [neovim/neovim#30688]
### Problem

Since a few weeks, neovim is unable to open / display auto suggestions on one of my pc's. ~~Interestingly it is working on my other pc's.~~ (Edit: reproducible with 0.10.2) They all share the exact same config, I even tried deleting all the neovim dirs (~/.cache/nvim, ~/.local/share/nvim, ~/.config/nvim and /usr/lib/nvim) and reinstalling my dotfiles with still the same result.

When typing code the auto suggestions do not show / open (everything else works, like syntax highlighting, error highlighting etc). When I then try to open the suggestions with a keybind I get the following error message:

```
   Error  Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/_completion.lua:154: attempt to index field 'range' (a nil value)
stack traceback:
	/usr/share/nvim/runtime/lua/vim/lsp/_completion.lua:154: in function 'adjust_start_col'
	/usr/share/nvim/runtime/lua/vim/lsp/_completion.lua:202: in function '_convert_results'
	/usr/share/nvim/runtime/lua/vim/lsp/_completion.lua:253: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

```

This happens on all LSP servers I use.

### Steps to reproduce

My dotfiles can be found here https://github.com/RononDex/dotfiles/tree/master/defaults/.config/nvim

1. Using my dotfiles, open any code document
2.  Try to get suggestions when typing

### Expected behavior

Auto suggestions show

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux 6.10.6

### Terminal name/version

kitty 0.36.4

### $TERM environment variable

xterm-kitty

### Installation

pacman

**Comment by zeertzjq** [comment]
Did you try deleting `/usr/share/nvim`?

**Comment by justinmk** [comment]
also see if `:checkhealth` reports a problem.

**Comment by RononDex** [comment]
> Did you try deleting `/usr/share/nvim`?

Just tried, still same result



> also see if `:checkhealth` reports a problem.

`:checkhealth` is not reporting any issues

**Comment by justinmk** [comment]
Try the latest development version. If you don't want to build from source, the [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.

**Comment by RononDex** [comment]
I have now installed version 
```
11:47:09 AM msg_show   version NVIM v0.11.0-dev-911+ga2008118a0
11:47:09 AM msg_show   version Build type: Release
11:47:09 AM msg_show   version LuaJIT 2.1.1725453128
```

And I am now getting this error message:

```
  Error  Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/completion.lua:311: attempt to index field 'range' (a nil value)
stack traceback:
	/usr/share/nvim/runtime/lua/vim/lsp/completion.lua:311: in function 'adjust_start_col'
	/usr/share/nvim/runtime/lua/vim/lsp/completion.lua:362: in function '_convert_results'
	/usr/share/nvim/runtime/lua/vim/lsp/completion.lua:451: in function 'callback'
	/usr/share/nvim/runtime/lua/vim/lsp/completion.lua:390: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by justinmk** [comment]
> Interestingly it is working on my other pc's. They all share the exact same config ... This happens on all LSP servers I use.

possibly related to encoding, though `_convert_results` is complex so that's just a guess. Once https://github.com/neovim/neovim/pull/30560 is ready, may be worth trying with that.

**Comment by RononDex** [comment]
Is there anyway I can temporarily fix it on my machine?

**Comment by glepnir** [comment]
wired i also can't reproduce it ...

**Comment by RononDex** [comment]
I can also only reproduce on one of my machines

**Comment by wookayin** [comment]
The line 154 in v0.10.2 is 
```lua
    if item.textEdit and item.textEdit.range.start.line == lnum then
```
so `item.textEdit` does not have a field `range`. `textEdit` is either [`lsp.TextEdit`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit) or [`lsp.InsertReplaceEdit`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#insertReplaceEdit), but [`lsp.InsertReplaceEdit`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#insertReplaceEdit) does not have the field `range`. So it looks like our business logic does not consider the latter case. (Neither so does Lua-LS!)

**Comment by RononDex** [comment]
After some more experimenting I was able to narrow down the error somewhat:

The difference between the machine I have where the error happens compared to the other machines where it doesn't was the NeoVim version. I can reproduce it on other machines with 0.10.2 but not with 0.10.1.

Also I have typos_lsp attached to all my buffers, which is probably the one causing the error.

**Comment by mfussenegger** [comment]
neovim doesn't set `insertReplaceSupport` in the client-capabilities which means that servers must not send `InsertReplaceEdit`.
If they're sending that instead of `TextEdit` that's a server bug. They need to honor the client capabilities.

**Comment by justinmk** [comment]
> neovim doesn't set `insertReplaceSupport` in the client-capabilities which means that servers must not send `InsertReplaceEdit`.
> If they're sending that instead of `TextEdit` that's a server bug

Is it feasible for us to validate this kind of thing and throw (more explicit) error if the server returns unexpected events/capabilities?

**Comment by mfussenegger** [comment]
> > neovim doesn't set `insertReplaceSupport` in the client-capabilities which means that servers must not send `InsertReplaceEdit`.
> > If they're sending that instead of `TextEdit` that's a server bug
> 
> Is it feasible for us to validate this kind of thing and throw a (more explicit) error if the server returns unexpected events/capabilities?

It would be possible but manual labour. Even if we generated some sort of runtime-typed-client from the LSP spec-model it wouldn't catch cases like these because the relationship between capabilities and supported structures is not present in the type definitions. That's only in the prose.

**Comment by justinmk** [comment]
> because the relationship between capabilities and supported structures is not present in the type definitions

That's what I was afraid of :( Thanks for confirming.

So nothing actionable on our end here?

**Comment by mfussenegger** [comment]
> So nothing actionable on our end here?

We could do things like:

```diff
diff --git a/runtime/lua/vim/lsp/completion.lua b/runtime/lua/vim/lsp/completion.lua
index 14fad987e0..efb3463565 100644
--- a/runtime/lua/vim/lsp/completion.lua
+++ b/runtime/lua/vim/lsp/completion.lua
@@ -305,15 +305,21 @@ end
 --- @param encoding string
 --- @return integer?
 local function adjust_start_col(lnum, line, items, encoding)
   local min_start_char = nil
   for _, item in pairs(items) do
-    if item.textEdit and item.textEdit.range.start.line == lnum then
-      if min_start_char and min_start_char ~= item.textEdit.range.start.character then
-        return nil
+    if item.textEdit then
+      assert(
+          item.textEdit.range,
+          'item.textEdit must be TextEdit. Server must honor client capability and not send InsertReplaceEdit'
+      )
+      if item.textEdit.range.start.line == lnum then
+        if min_start_char and min_start_char ~= item.textEdit.range.start.character then
+          return nil
+        end
+        min_start_char = item.textEdit.range.start.character
       end
-      min_start_char = item.textEdit.range.start.character
     end
   end
   if min_start_char then
     return lsp.util._str_byteindex_enc(line, min_start_char, encoding)
   else
```

But then you've gotta ask where to draw the line. If we stop trusting servers to behave we'd have to assert _all_ properties. That's getting ugly & tedios quite fast.

Besides that, we've also had bug reports where users extended the client capabilities because they didn't realize that one cannot just add a capability without also extending the implementation accordingly.

I think getting the occassional report is the lesser evil so yes - nothing actionable.

**Comment by justinmk** [comment]
> But then you've gotta ask where to draw the line. If we stop trusting servers to behave we'd have to assert _all_ properties.

If we could encapsulate this "messiness" in a single `validate_response` function that does a kind of "checkhealth" on a response payload, that could be workable. But it might be slow.

**Comment by wookayin** [comment]
I know that this *might* be a LSP server bug, but

> neovim doesn't set insertReplaceSupport in the client-capabilities

this is also a specific assumption that the default client_capabilities is used, which is not necessarily always true.

Users can override client capabilities in which case `insertReplaceSupport` response could arrive validly. Indeed a very popular plugin [`nvim-cmp-lsp` overrides `insertReplaceSupport` with true](https://github.com/hrsh7th/cmp-nvim-lsp/blob/main/lua/cmp_nvim_lsp/init.lua#L54) (so does in my config), so I think neovim's completion logic should also handle this case properly according to the LSP specification.
