### ISSUE TITLE
Implementation of `str_utfindex_enc` seems to be wrong

### ISSUE THREAD

**Issue by wlh320** [neovim/neovim#30692]
### Problem

In #30322,  function `_str_utfindex_enc` compares `index` with `len16` or `len32` for bound checking.

However, as document shows, argument `index` is UTF-8 byte index, `len16` and `len32` are UTF-32 and UTF-16 indices of the end of the line.

I think they should not be compared directly. When buffers contain CJK characters, UTF-8 byte indices and UTF-16 indices are different.

### Steps to reproduce

1. Open a buffer with CJK characters.
2. Request LSP completion at some position.
3. Check `position.character` of LSP request

### Expected behavior

Even the position is not the end of line, it may be set to the end of line.
I think the origin source of this issue is the implementation of `str_utfindex_enc`.

### Nvim version (nvim -v)

v0.10.2

### Vim (not Nvim) behaves the same?

v0.10.1

### Operating system/version

Archlinux

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

Arch Official Repo

**Comment by justinmk** [comment]
I think https://github.com/neovim/neovim/pull/30560 will help with this?

**Comment by wlh320** [comment]
I noticed that this PR may refactor or remove this function. I'll try it once it is ready.
Thank you!

**Comment by wlh320** [comment]
@tris203 Could you please confirm if my understanding of this issue is correct? Will it be addressed in your latest PR? Thank you!

**Comment by tris203** [comment]
This should have been fixed by #30747

**Comment by wlh320** [comment]
> This should have been fixed by [#30747](https://github.com/neovim/neovim/pull/30747)

I think it only fixed `_str_byteindex_enc` but not `_str_utfindex_enc`?

**Comment by tris203** [comment]
> > This should have been fixed by [#30747](https://github.com/neovim/neovim/pull/30747)
> 
> I think it only fixed `_str_byteindex_enc` but not `_str_utfindex_enc`?

Sorry, I read too quickly. Yes, this should be fixed by #30735

Do you have a example that we could add to the test cases?

**Comment by wlh320** [comment]
I tried nightly build and this issue is fixed. Thank you!
