### ISSUE TITLE
Inconsistent Alt Key Layer Activation Timing in Neovim Compared to Other Applications

### ISSUE THREAD

**Issue by Marcos-Gamarra** [neovim/neovim#30694]
### Problem

My left alt key produces ISO_Level3_Shift, which activates a new keyboard layer when pressed.

In Neovim, holding down the left alt key activates the layer for a brief moment immediately after the key is pressed. If no key is pressed within that small window of time, the layer deactivates, and pressing any key afterward produces a character as if the left alt key wasn't pressed.

However, if a key is pressed during that brief period, the layer remains active for as long as the left alt key is held.

The same behavior occurs with ISO_Level5_Shift.

In other applications, such as the terminal or browser, holding down the left alt key keeps the layer active, regardless of whether any keys are pressed.

### Steps to reproduce

map ISO_Level3_Shift to left alt and try to use that layer inside neovim.

### Expected behavior

keyboard layer should work for as long as the key that activates it is being hold regardless of any key being pressed or not.

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch

### Terminal name/version

foot 1.18.1

### $TERM environment variable

foot

### Installation

system package manager

**Comment by zeertzjq** [comment]
Can you try running Nvim in some other terminal emulators (e.g. WezTerm, kitty, Alacritty) and see if it also happens?

**Comment by zeertzjq** [comment]
And, how do you observe which layer is active?

**Comment by Marcos-Gamarra** [comment]
> Can you try running Nvim in some other terminal emulators (e.g. WezTerm, kitty, Alacritty, XTerm, Terminator, rxvt) and see if it also happens?

Ok, I tried it in WezTerm and Alacritty, and it works as expected in both. Closing, as it's most likely related to Foot.
