### ISSUE TITLE
LSP: vim.lsp.buf.code_action() option to show name of the language server providing the action

### ISSUE THREAD

**Issue by piedrahitapablo** [neovim/neovim#30710]
### Problem

I checked the docs and searched online, but as far as I know, `vim.lsp.buf.code_action()` does not currently offer a way to customize the actions shown in the menu. Allowing customization could be useful in cases where there are many available actions or actions with similar wordings, and adding the name of the language server that is offering the action can help select the correct option.

Sorry in advance if this feature already exists but I was not able to find anything related to it.

### Expected behavior

Allow a way to customize `vim.lsp.buf.code_action()` to show the name of the language servers

**Comment by wookayin** [comment]
+1 for more customization/configuration points within neovim core -- without implementing too much logic in custom `vim.ui.select`.

But this is possible if you override `vim.ui.select`, as the code action entry items passed to `vim.ui.select()` already contains the context information, containing the id of the LSP client (via `item.ctx.client_id`.

If you use some cool plugins like https://github.com/stevearc/dressing.nvim, the feature you're specifically looking for is already implemented (when using a telescope backend):

<img src="https://github.com/user-attachments/assets/bb19d082-299b-4848-9d69-33f4f74fa026" width=600 />

**Comment by justinmk** [comment]
> customize `vim.lsp.buf.code_action()` to show the name of the language servers

Why don't we do this by default? Seems like a reasonable default behavior.

**Comment by piedrahitapablo** [comment]
@wookayin thanks for pointing me to override `vim.ui.select`, this is the implementation I ended up with:

```lua
local original_vim_ui_select = vim.ui.select
---@diagnostic disable-next-line: duplicate-set-field
vim.ui.select = function(items, select_opts, on_choice)
    if select_opts.kind ~= "codeaction" then
        return original_vim_ui_select(
            items,
            select_opts,
            on_choice
        )
    end

    -- original fn: https://github.com/neovim/neovim/blob/release-0.10/runtime/lua/vim/lsp/buf.lua#L812
    ---@param item {action: lsp.Command|lsp.CodeAction}
    select_opts.format_item = function(item)
        local formatted = item.action.title
            :gsub("\r\n", "\\r\\n")
            :gsub("\n", "\\n")

        local client_id = item.ctx and item.ctx.client_id
        if client_id then
            local action_client =
                vim.lsp.get_client_by_id(client_id)
            local source_name = action_client
                    and action_client.name
                or "unknown"

            formatted = formatted .. " [" .. source_name .. "]"
        end

        return formatted
    end

    original_vim_ui_select(items, select_opts, on_choice)
end
```
