### ISSUE TITLE
quickfix: preserve current location when updating quickfix/loclist

### ISSUE THREAD

**Issue by jfly** [neovim/neovim#30724]
### Problem

If I'm partway through a quickfix list, and then I do something to refresh the quickfix list, I lose my location in the list.

Here's an example of that happening:

![demo](https://github.com/user-attachments/assets/a4e01b91-dfea-4167-b9a5-4b6c32b1695b)

### Expected behavior

I'd prefer for my quickfix list to preserve my current location, or whatever entry in the list is nearest wherever I was.

I was able to hack this together by monkeypatching `vim.fn.setqflist` in Lua. Here's that hack in plugin form: https://github.com/jfly/sticky-quickfix.nvim.

This isn't perfect: it wouldn't play nicely with Vimscript code that calls `:call setqflist(...)`. There are probably other issues with it that I'm not aware of.

**Comment by justinmk** [comment]
Example of the exact `setqflist` ? If the 'r' ("replace") flag is passed this probably makes sense. But should be requested at https://github.com/vim/vim

**Comment by jfly** [comment]
@glepnir, this isn't a diagnostics issue. I just used LSP diagnostics to try to provide a simple example.

@justinmk here's a simple vim file to demonstrate the issue. I agree that this behavior only makes sense if `'r'` is passed, which I didn't show in my original example.

```vimscript
" Dead simple script to convert every line in the current buffer into
" an entry in the quickfix list.
"
" This replaces the current quickfix list.
" Run with `:source %`

let qflist = []

let line_count = line('$')
for lnum in range(1, line_count)
    let line_text = getline(lnum)
    let bufnr = bufnr('%')
    call add(qflist, {'bufnr': bufnr, 'lnum': lnum, 'text': line_text})
endfor

call setqflist(qflist, 'r')

" Open the quickix list.
copen
```

And here it is in action:

https://github.com/user-attachments/assets/9d2b48a3-8824-4813-9ab5-cd13bd8f0b63


> But should be requested/implemented at https://github.com/vim/vim

Sounds good! I've filed https://github.com/vim/vim/issues/15839. I'm ok closing this issue in favor of that one.

**Comment by justinmk** [comment]
https://github.com/vim/vim/pull/15841 @jfly do you plan to apply the patch here? :)

**Comment by jfly** [comment]
Ha! Thanks, @zeertzjq :)
